### ISSUE TITLE
[s3] Wrong link on python doc, points to ECR lifecycle policy instead of S3

### ISSUE THREAD

**Issue by tinexw** [aws/aws-cdk#10004]
link to reference doc page: https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_s3/Bucket.html

The link for Lifecycle Policy points to the ECR lifecycle policy (https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_ecr/LifecycleRule.html#aws_cdk.aws_ecr.LifecycleRule), not the S3 one.

If someone points me to the place where I can fix it I'll happily submit a PR myself.

---

This is a 📕 documentation issue

**Comment by rrhodes** [comment]
@tinexw, this issue appears to be resolved, if you could confirm I've not missed something?

**Comment by tinexw** [comment]
Thanks @rrhodes , it's resolved.
