### ISSUE TITLE
[aws-eks] The Nodegroup construct does not apply labels to nodes correctly.

### ISSUE THREAD

**Issue by KitFristo** [aws/aws-cdk#10013]
When applying labels to a Managed Nodegroup using the EKS module for the CDK (in python), the labels do not populate correctly on the actual nodes/nodegroups in the AWS console.

### Reproduction Steps

1. Download and install the AWS CDK and python.
2. Create a managed nodegroup and pass the following labels as a list for the aws_cdk.aws_eks.Nodegroup construct:
[ "testkey", "testvalue" ].
3. Spawn the nodegroups using the AWS CDK.

### What did you expect to happen?

I would expect the following label to be applied to all nodes within the nodegroup:
testkey=testvalue

### What actually happened?

The following is the actual labels applied to the nodes within the nodegroup:
0=testkey
1=testvalue

I'm not sure if this was intended by the developers, but it appears that the expected input is a list of strings. Other inputs do not work (like a dictionary, list of dictionaries, etc.). I think a more appropriate input would be a list of dictionaries for each key value pair. Example below:
[
{"key1: "value1"},
{"key2: "value2"},
]

### Environment

  - **CLI Version:** Version 1
  - **Framework Version:**
  - **Node.js Version:** Node v12.18.3
  - **OS:** Ubuntu 18.04
  - **Language (Version):** Python 3.7.9

### Other

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment]
@KitFristo Could you please share the exact code you are using? There are several ways of applying tags and i'm not entirely sure which one are you referring to.

Thanks

**Comment by KitFristo** [comment]
Sure thing @iliapolo. Please see the redacted code below. I'm just creating the nodegroup construct. I have already spawned an eks cluster, and IAM role as well. They're passed to the function.

my_nodegroup = eks.Nodegroup(
            scope=self,
            id='my-nodegroup-id',
            cluster=my_eks_cluster,
            desired_size=2,
            disk_size=100,
            instance_type=ec2.InstanceType(
                't2.medium'
            ),
            labels=[
                'key', 'value'
            ],
            node_role=instance_role,
            max_size=3,
            min_size=1,
            nodegroup_name=(
                'my-amazing-nodegroup'
                ),
            subnets=ec2.SubnetSelection(subnet_name='Private')
        )

**Comment by KitFristo** [comment]
A more optimal format below:

``
my_nodegroup = eks.Nodegroup(
scope=self,
id='my-nodegroup-id',
cluster=my_eks_cluster,
desired_size=2,
disk_size=100,
instance_type=ec2.InstanceType('t2.medium'),
labels=['key', 'value'],
node_role=instance_role,
max_size=3,
min_size=1,
nodegroup_name=('my-amazing-nodegroup'),
subnets=ec2.SubnetSelection(subnet_name='Private')
)
``

**Comment by iliapolo** [comment]
Hi @KitFristo 

Notice that our [reference documentation](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_eks/NodegroupProps.html) states the `labels` should be a simple dictionary:

> - labels (Optional[Mapping[str, str]]) – The Kubernetes labels to be applied to the nodes in the node group when they are created. Default: - None

Have you tried passing:

```python
my_nodegroup = eks.Nodegroup(
  scope=self,
  id='my-nodegroup-id',
  cluster=my_eks_cluster,
  ...,
  labels={ 'foo': 'bar' }, // map[string] => string
  ...
),
```

?

I've deployed that and everything seems to be ok:

![Screen Shot 2020-08-30 at 1 35 34 PM](https://user-images.githubusercontent.com/1428812/91658170-7af18580-eacf-11ea-843a-2070cb44ef68.png)

**Comment by KitFristo** [comment]
@iliapolo I've been able to deploy two separate nodegroups with labels, feel free to close this issue. Sorry for the misunderstanding and thank you for the clarification!
