### ISSUE TITLE
[cdk-pipelines] Error when using pipeline.stackOutput: TypeError: Cannot read property 'Symbol(@aws-cdk/core.Stack.myStack)' of undefined

### ISSUE THREAD

**Issue by markusl** [aws/aws-cdk#10029]
When I'm trying to follow what was demonstrated at https://www.youtube.com/watch?v=1ps0Wh19MHQ (around 37:00) I get the following error:

```text
TypeError: Cannot read property 'Symbol(@aws-cdk/core.Stack.myStack)' of undefined
    at Function.of (node_modules/@aws-cdk/core/lib/stack.ts:152:37)
    at CdkPipeline.stackOutput (node_modules/@aws-cdk/pipelines/lib/pipeline.ts:157:25)
    at new AwsReleaseDocumentArchiverPipelineStack (lib/aws-release-document-archiver-pipeline-stack.ts:65:31)
    at Object.<anonymous> (bin/aws-release-document-archiver.ts:9:1)
    at Module._compile (internal/modules/cjs/loader.js:1251:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
```

The error seems to be related to the usage of `pipeline.stackOutput` because, without it, the code synthesizes successfully. Any ideas?

### Reproduction Steps

```ts
export class InfraStack extends cdk.Stack {
  /**
   * The NLB DNS name.
   */
  public readonly loadBalancerDnsName: cdk.CfnOutput;
...
}

...

    const devStage = new cdk.Stage(...);
    const devService = new InfraStack(devStage, ...);
    const devAppStage = pipeline.addApplicationStage(devStage);
    devAppStage.addActions(new pipelines.ShellScriptAction({
      actionName: 'IntegrationTests',
      additionalArtifacts: [sourceArtifact],
      useOutputs: {
        SERVICE_URL: pipeline.stackOutput(devService.loadBalancerDnsName)
      },
      commands: [
        'curl -v $SERVICE_URL'
      ],
    }));
```

### Environment

  - **CLI Version      :** 1.61.0 (build 72e6727)
  - **Framework Version:** 1.61.0 
  - **Node.js Version:** v14.8.0
  - **OS               :** macOs
  - **Language (Version):** TypeScript 4.0.2

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
Are you sure that `loadBalancerDnsName` actually got initialized? :)

**Comment by rix0rrr** [comment]
The call stack is literally:

https://github.com/aws/aws-cdk/blob/huijbers/cli-default-profile/packages/@aws-cdk/pipelines/lib/pipeline.ts#L156-L157

and then

https://github.com/aws/aws-cdk/blob/f6ccdf0adf1ce405ca70743df85fc55700d30924/packages/%40aws-cdk/core/lib/stack.ts#L147-L152

Which can only really fail if the input object is `undefined`.

**Comment by markusl** [comment]
Ooops! I had a copy-paste error in the setting of the output parameter 🙈 Thanks for noticing this. Should have used a linter even when prototyping!
