### ISSUE TITLE
[aws-rds] Cannot retrieve the children from a ParameterGroup resource

### ISSUE THREAD

**Issue by eswets** [aws/aws-cdk#10033]
Since CDK version 1.52, retrieving the children from a `ParameterGroup` always returns an empty array. This means that for this resource, we cannot override the logical ID anymore (which means we would have to reboot the affected databases).

### Reproduction Steps

Create a new `ParameterGroup`:

```ts
const parameterGroup = new ParameterGroup(this, "DBParameterGroup", {
    engine: DatabaseInstanceEngine.postgres({
        version: PostgresEngineVersion.VER_12_3,
    }),
    description: `Custom parameter group`,
    parameters: {
        idle_in_transaction_session_timeout: "2100000",
    },
});
```

Subsequently, doing a `console.log(parameterGroup.node.children)` yields `[]`. This means we can't get the child to cast to a `CfnDBParameterGroup`, which is needed to override the logical id.

### What did you expect to happen?

Calling `parameterGroup.node.children` (or `parameterGroup.node.defaultChild`) should yield a result.

### What actually happened?

Calling `parameterGroup.node.children` yields `[]`

### Environment

  - **CLI Version:** `1.61`
  - **Framework Version:** `1.61`
  - **Node.js Version:** `v12.16.3`
  - **OS: ** MacOS
  - **Language (Version):** TypeScript (3.8.3)

### Other

Issue seems to be present since CDK 1.52

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hello @eswets ,

thanks for opening the issue. The `ParameterGroup` resource has been slightly modified recently to create the underlying `CfnDBClusterParameterGroup` and `CfnDBParameterGroup` instances lazily, when it's passed to a newly created Cluster or Instance, respectively. After that, the `node.children` and `node.defaultChild` methods will work correctly. So:

```ts
const parameterGroup = new ParameterGroup(this, "DBParameterGroup", {
    engine: DatabaseInstanceEngine.postgres({
        version: PostgresEngineVersion.VER_12_3,
    }),
    description: `Custom parameter group`,
    parameters: {
        idle_in_transaction_session_timeout: "2100000",
    },
});

// pass ParameterGroup to Instance...

const cfnParameterGroup = parameterGroup.node.defaultChild // now this will work
```

Thanks,
Adam

**Comment by eswets** [comment]
Hi Adam,

Thanks! That works fine indeed.

Best,

Erik
