### ISSUE TITLE
[scripts] Build all packages with changes since last build on local dev environment

### ISSUE THREAD

**Issue by andrestone** [aws/aws-cdk#10035]
### Use Case
I'd like to build only the packages changed since last build, instead of rebuilding the whole monorepo every now and then or manually identifying and building updated packages.

### Proposed Solution
A "stateful" script could store the last build's commit reference, use `git` to identify packages with changes, and call a `foreach`-like script to build the list of packages and their dependencies (skipping the ones already built in the current session).

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by eladb** [comment]
@rix0rrr is working on something that may help. Assigning to him for follow up
