### ISSUE TITLE
[aws-dynamodb]: Is there any way in cdk that allow us to add trigger to a dynamodb table. 

### ISSUE THREAD

**Issue by devendra-kumar1** [aws/aws-cdk#10041]
### The Question

I have one requirement where i have to add a lambda as trigger to existing dynamo db table. Is there any way in cdk  through which i can achieve this ?

### Environment

  - **CDK CLI Version:** 1.47.0
  - **Module Version:**  1.60.0
  - **Node.js Version:**  12
  - **OS:** Windows 10
  - **Language (Version):**  TypeScript (3.8.3)

**Comment by devendra-kumar1** [comment]
@skinny85 : Is there any way to do this ?

**Comment by skinny85** [comment]
Hey @devendra-kumar1 ,

can you clarify what you want to achieve exactly? I don't see "triggers" in either Lambda or DynamoDB.

Thanks,
Adam

**Comment by devendra-kumar1** [comment]
Hey @skinny85 
Actually if you go to AWS console. Go to dynamodb page and select any table.
On the options you have on option to add trigger that will be any lambda.
Basically it will triggered on configuration  of dynamo db stream.
Example: I configured stream on insertion into dynamodb.
Then if any records inserted into dynamo db then triggered will be executed. I.e. your lambda.

So my question is that in cdk do we have provision that allow me to define a trigger on dynamo table.

**Comment by skinny85** [comment]
Ah yes. You can do that using the [`aws-lambda-event-sources` library](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-lambda-event-sources-readme.html#dynamodb-streams).

**Comment by devendra-kumar1** [comment]
Thank you so much @skinny85 . Will try that.
