### ISSUE TITLE
[aws-ecs] EcsCluster should specify FARGATE and FARGATE_SPOT capacity providers by default.

### ISSUE THREAD

**Issue by rrrix** [aws/aws-cdk#10046]
`@aws-cdk.aws-ecs.EcsCluster` should include the two [Fargate capacity providers](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/fargate-capacity-providers.html) (`FARGATE` and `FARGATE_SPOT`) by default, similarly to what is provided when creating an ECS Cluster via the AWS Console.

### Use Case

In order to use the `FARGATE_SPOT` capacity provider, it needs to be added to the ECS Cluster Capacity Providers list. This is done automatically when creating an ECS Cluster via the AWS Console, but not when launched via CloudFormation.

### Proposed Solution

https://github.com/rrrix/aws-cdk/blob/87dc78b115c969bc2725ee150ebf5f0ae3878984/packages/@aws-cdk/aws-ecs/lib/cluster.ts#L110-L114

```typescript
    // ./packages/@aws-cdk/aws-ecs/lib/cluster.ts#L110-L114
    const cluster = new CfnCluster(this, 'Resource', {
      clusterName: this.physicalName,
      clusterSettings,
      capacityProviders: ['FARGATE', 'FARGATE_SPOT'],  // <<----- This, please!
    });
```

### Other

Current workaround to add `FARGATE` and `FARGATE_SPOT` capacity providers is:

```typescript
    const ecsCluster = new Cluster(this, `Resource`, {
      vpc: props.vpc,
      clusterName: 'my-cluster'
      containerInsights: true,
    });
    const cfnEcsCluster = this.ecsCluster.node.defaultChild as CfnCluster;
    cfnEcsCluster.capacityProviders = ['FARGATE', 'FARGATE_SPOT'];
```

### Documentation / References

`AWS::ECS::Cluster.CapacityProviders`: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-cluster.html#cfn-ecs-cluster-capacityproviders

AWS Fargate capacity providers: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/fargate-capacity-providers.html

---

* [✅] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by SoManyHs** [comment]
Hi @rrrix!

We have an issue currently open for adding capacity provider support on the L2 construct: https://github.com/aws/aws-cdk/issues/5471

Adding FARGATE and FARGATE SPOT as defaults on the `CfnCluster` would be a breaking change to the current behavior of the `EcsCluster` unfortunately. Please feel free to chime in on the above mentioned issue if you have more input!

**Comment by airmonitor** [comment]
Please keep it open, thx

**Comment by piradeepk** [comment]
Closing in favour of #5471
