### ISSUE TITLE
[elbv2] Regression of NLB with TLS termination 

### ISSUE THREAD

**Issue by sgvandijk** [aws/aws-cdk#10044]
I believe that https://github.com/aws/aws-cdk/pull/9651 has caused a regression for setups with an NLB that should terminate TLS and use HTTP as target group protocol, when using `addTargets`; in any case when using an ECS (Fargate) service. 

### Reproduction Steps

Define an NLB, a TLS listener, a an ECS service and add it as taget (I'm using Python):

```python
lb = elbv2.NetworkLoadBalancer(
    self,
    id="lb",
    vpc=self.vpc,
    internet_facing=True,
)

listener = lb.add_listener(
    id="https-listener-external",
    port=443,
    certificates=[
        elbv2.ListenerCertificate.from_certificate_manager(certificate)
    ],
)

# Create some task with some container
task_definition = ecs.FargateTaskDefinition(...)
container = task_definition.add_container(id="container", ...)

# Container runs an HTTP server on port 8000, set up a TCP port mapping
port_mapping = ecs.PortMapping(
    container_port=8000, protocol=ecs.Protocol.TCP
)
container.add_port_mappings(port_mapping)

# Create service
service = ecs.FargateService(
    self,
    task_definition=task_definition,
    ...
)

# Add service as a target to listener, specifying TCP protocol
listener.add_targets(
    id="target",
    port=443,
    targets=[
        service.load_balancer_target(
            container_name="container", container_port=8000, protocol=ecs.Protocol.TCP
        )
    ],
    health_check=elbv2.HealthCheck(
        enabled=True, protocol=elbv2.Protocol.HTTP, path=health_path
    ),
)
```

Deploy this using CDK 1.59.0, upgrade to CDK 1.60.0 (or 1.61.0) and run `cdk diff` and you get something like:

```
[~] AWS::ElasticLoadBalancingV2::TargetGroup lb/listener/targetGroup [...] replace
 └─ [~] Protocol (requires replacement)                                                                                        
     ├─ [-] TCP                                                                                                                
     └─ [+] TLS  
```

### What did you expect to happen?

The protocol should not change when set explicitly to TCP

### What actually happened?

The protocol was inherited from the load balancer instead of from the configuration for the target

### Environment

  - **CLI Version      :** 1.60
  - **Framework Version:** 1.60
  - **Node.js Version:** 12.16.1
  - **OS               :** Ubuntu 20.04
  - **Language (Version):** Python 3.8.2

--- 

This is :bug: Bug Report

**Comment by hoegertn** [comment]
I am sorry this caused trouble on your side. I am looking into it and see what the reason is.

**Comment by hoegertn** [comment]
So after a dive into the code, I think the following happens

1) the protocol of the `load_balancer_target` is not used to determine the protocol of the target group but only used to validate the port mapping
2) The target group now inherits the protocol of the listener
3) the listener has the protocol set to TLS due to the port 443

Due to bug before 1.60 the target group protocol was set to TCP because it is the default. After fixing this bug it now gets the TLS from the listener. What you really want is to set the protocol to TCP when calling `add_targets`.

This just wasn't necessary due to the missing protocol inheritance.

Again, I am sorry this change had side effects on your code.

**Comment by sgvandijk** [comment]
No worries, the diff made the change clear and I can just stay on 1.59 for now :)

> What you really want is to set the protocol to TCP when calling add_targets

I'm not sure if that is currently possible? It can't be set as part of [AddNetworkTargetsProps](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-elasticloadbalancingv2.AddNetworkTargetsProps.html) and it will always be set to the listener's incoming protocol. I do set it in the call to `load_balancer_target` on the ECS service as I described, but now I see that the protocol set there is meant to be [only applicable to ALBs, not NLBs](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs.LoadBalancerTargetOptions.html#protocol), and `addTargets` may not even be able to retrieve it at that point.

If the original intention of `addTargets` was to always use the same protocol, and the feature of setting up TLS termination at the load balancer with it was accidental, I guess this issue then is a feature request to add an option to override the inheritance behaviour.

But if that's not desired feel free to close this and I guess one can still create the target group manually with the protocol set to TCP and use `addTargetGroups` instead to achieve the desired behaviour.

**Comment by hoegertn** [comment]
Hi, you are right and I mistakenly assumed it was possible. So the old behavior was to always assume TLS termination and the new one is to always use the listener protocol. Both ways are not what we really want.

I will create a PR to add the protocol to the target options and to fall back to the listener protocol as implemented with the new version.

Would this solve your problem?

/cc @rix0rrr I will create a PR for this, can you then please review and merge to get this approved for the next release?

**Comment by sgvandijk** [comment]
That sounds very sensible to me yeah and #10054 looks like it'll solve my problem, yes, cheers!
