### ISSUE TITLE
[aws-appmesh] Add TLS support for VirtualNodes 

### ISSUE THREAD

**Issue by otterley** [aws/aws-cdk#10051]
AWS App Mesh now supports [TLS encryption for Virtual Nodes](https://docs.aws.amazon.com/app-mesh/latest/userguide/tls.html). We should support it.

### Use Case

Customers want to take advantage of App Mesh's ability to easily add encryption-in-transit to their containerized applications.

### Other

Current workaround:

```ts
    (virtualNode.node.defaultChild as cdk.CfnResource).addPropertyOverride(
      'Spec.Listeners.0.TLS.Certificate.ACM.CertificateArn', certificate.certificateArn
    );
    (virtualNode.node.defaultChild as cdk.CfnResource).addPropertyOverride(
      'Spec.Listeners.0.TLS.Mode', 'STRICT'
    );
```

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by alexbrjo** [comment]
I'm working on adding TLS for VirtualNodes and VirtualGateways.

**Comment by alexbrjo** [comment]
TLS support for both Virtual Node and Virtual Gateway listeners was just merged. https://github.com/aws/aws-cdk/pull/11863
