### ISSUE TITLE
[appsync]: adding dependency to GraphQL Api

### ISSUE THREAD

**Issue by gavinyue-vendia** [aws/aws-cdk#10050]
https://github.com/aws/aws-cdk/blob/1ed119e2cdbc37666616f6666b0edb12c2c9ea89/packages/%40aws-cdk/aws-appsync/lib/graphqlapi.ts#L499

Need to add the Schema dependency to DynamoDbDataSource. 

But this does not accept DynamoDbDataSource as the input.  What is the workaround here? 

Thanks.

**Comment by BryanPan342** [comment]
I believe you would need to access the CfnResource which would have to occur through an escape hatch.

Here is some info on it!

https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html#cfn_layer_resource

But in terms of code that would look like this.

```ts
const api = new GraphQLApi(stack, 'api' { name: 'api' });
const tableDS = api.addDynamoDbDataSource('tableDS', table);
api.addSchemaDependency(tableDS.node.defaultChild);
```

using `node.defaultChild` will expose the CfnResouce
