### ISSUE TITLE
[app-sync] -  Appsync requires to have userPoolConfig.defaultAction set, but type definitions says it's optional

### ISSUE THREAD

**Issue by wmattei** [aws/aws-cdk#10060]
Since v1.61.0 version, it is not longer possible to use `CognitoUserPool` as default authorization mode withou providing the `defaultAction`, even the type definitions saying it is optional, and `Allow` is the default option.

To be honest i think it does make sense it being a required field, we should just update the `jsdoc`.
Let me know what should be the behaviour and i would love to raise a PR fixing it.

I'm not sure where to create this issue, i think documentation is appropriate, let me know if i should move it 

---

This is a 📕 documentation issue

**Comment by BryanPan342** [comment]
Yeah this was my bad when I was refactoring.. #10031 this PR went to make the `Allow` the default. Closing this for now as the next release will cover it.
