### ISSUE TITLE
[IAM] attach_inline_policy method does not work causing error

### ISSUE THREAD

**Issue by oonisim** [aws/aws-cdk#10064]
AWS Case 7266168091 . CDK IAM Role ```attach_inline_policy``` method does not work causing the error.

```
5:43:47 pm | CREATE_FAILED        | AWS::SageMaker::Model | MlaiMetadataPredictionModelSummary
Could not access model data at s3://<Bucket>/model.tar.gz. Please ensure that the role "arn:aws:iam::****:role/SagemakerExec
utionRole4E-1UFGLSBH0OLLG" exists and that its trust relationship policy allows the action "sts:AssumeRole" for the service principal "sagemaker.amazonaws.com". Also ensure that the role has "s3:GetObject" permissions and that the object is located in us-east-1. (Servi
ce: AmazonSageMaker; Status Code: 400; Error Code: ValidationException; Request ID: e2f9990c-1ddb-41a7-9230-d31c6d999b50)
```

### Reproduction Steps
Define the IAM role for the SageMaker execution and deploy a SageMaker model. The role has the S3 permission to access the S3 bucket. However, because the attach_inline_policy method does not work to setup the IAM role for the S3 permission, the access to the model in the S3 fails.

Workaround is to put an explicit dependency from the model to the role, which should not be required.

``` py
    def define_execution_role(self) -> aws_iam.Role:
        sagemaker_execution_policy = aws_iam.Policy(
            scope=self,
            id="SagemakerExecutionPolicy"
        )
        sagemaker_execution_policy.add_statements(aws_iam.PolicyStatement(
            actions=[
                "s3:list*",
                "s3:GetObject",
                "s3:PutObject",
                "s3:DeleteObject",
                "s3:AbortMultipartUpload"
            ],
            effect=aws_iam.Effect.ALLOW,
            resources=[
                '*'
            ]
        ))
        sagemaker_execution_role: aws_iam.Role = aws_iam.Role(
            scope=self,
            id="SagemakerExecutionRole",
            assumed_by=aws_iam.ServicePrincipal(service="sagemaker.amazonaws.com"),
            managed_policies=[
                aws_iam.ManagedPolicy.from_aws_managed_policy_name("AmazonSageMakerFullAccess")
            ]
        )
        sagemaker_execution_role.attach_inline_policy(   # <---- Does not work causing the error.
            sagemaker_execution_policy
        )

        return sagemaker_execution_role

    def define_sagemaker_model(
            self,
            vpc: libcdk_vpc.Vpc,
            role: aws_iam.Role,
            parameters: Dict
    ) -> aws_sagemaker.CfnModel:
        cdk_vpc: aws_ec2.IVpc = vpc.vpc
        subnet_selection = cdk_vpc.select_subnets(
            subnet_type=aws_ec2.SubnetType.PRIVATE
        )
        model: aws_sagemaker.CfnModel = aws_sagemaker.CfnModel(
            scope=self,
            id=parameters['id'],
            execution_role_arn=role.role_arn,     # <----- Causes error
            primary_container=aws_sagemaker.CfnModel.ContainerDefinitionProperty(
                image=parameters['primary_container']['image'],
                model_data_url=parameters['primary_container']['model_data_url'],
                mode=parameters['primary_container']['mode'],
                environment=parameters['primary_container']['environment']
            )
            #vpc_config=vpc_config
        )

        return model
```
### Environment

  - **CLI Version      :**
1.58.0
  - **Framework Version:**
  - **Node.js Version:** 
12.13.8
  - **OS               :**
MacOS 10.15.6 (19G73)
  - **Language (Version):** 
Python

### Other

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
You might mean a dependency from the SageMaker model to the POLICY, not the role.

It is required, it is necessary to enforce ordering.

I'm having a hard time believing that `attach_inline_policy` straight up doesn't work, since we use it in multiple places and we have tests on it.

**Comment by oonisim** [comment]
Hi @rix0rrr, it was confirmed by the support team and they provided a workaround. Please have a look at the case?

**Comment by NGL321** [comment]
Hey @oonisim,

If you look at the [Cloudformation description of `ExecutionRoleArn`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sagemaker-model.html#aws-resource-sagemaker-model-properties), it states that: "To be able to pass this role to Amazon SageMaker, the caller of this API must have the iam:PassRole permission.".

Try adjusting the permissions to include `iam:PassRole` and let me know if that resolves your issue!

😸😷

**Comment by oonisim** [comment]
@NGL321 ```iam:PassRole``` is not related. The solution was below and "iam:PassRole" was not requried.
```
sagemaker_model.node.add_dependency(sagemaker_execution_policy)
```

CDK IAM role attach_inline_policy method did not create the dependency from the policy to the role in the code. 
```
sagemaker_execution_role.attach_inline_policy(   # <---- Does not work causing the error.
            sagemaker_execution_policy
        )
```

Hence needed to explicitly create the dependency.
