### ISSUE TITLE
[aws-codepipeline-actions] No option to custom event role on code commit source action

### ISSUE THREAD

**Issue by nirvana124** [aws/aws-cdk#10069]
I want to use my custom role that is be assumed by "events.amazonaws.com" to StartPipelineExecution.
 
`aws-codepipeline-actions/lib/codecommit/source-action` class is binding to `aws-events-target/lib/codepipeline` as target on commit to repository.

`aws-events-target/lib/codepipeline` provides option to pass `eventRole` but there is no option to pass event role in source-action.

### Use Case

I have a role that i need to pass as my event role.

### Proposed Solution

Can have `eventRole` inside `ActionBindOptions` and that can be passed to target codepipeline action

```ts
      this.props.repository.onCommit(`${stage.pipeline.node.uniqueId}${branchIdDisambiguator}EventRule`, {
        target: new targets.CodePipeline(stage.pipeline, **options.eventRole**),
        branches: [this.branch],
      });
```

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by skinny85** [comment]
Hey @nirvana124 ,

thanks for opening the issue. If you want to implement it for your usecase, just pass `CodeCommitTrigger.NONE` to the `CodeCommitSourceAction`, and you can create the Event yourself, just like you want.

Any chance for opening us a Pull Request with this feature? 😉

Thanks,
Adam
