### ISSUE TITLE
[aws-cloudformation] CfnWaitCondition timeout is not using core.Duration

### ISSUE THREAD

**Issue by oonisim** [aws/aws-cdk#10067]
```
        wait = aws_cloudformation.CfnWaitCondition(
            scope=cdk_sagemaker_endpoint,
            id="WaitCondition",
            timeout="600",  <----- Optional[str], not Duration.
            count=1
        )
```

### Reproduction Steps
NA

### What did you expect to happen?
Consistent API interface for duration. At some places, it requires Duration and at others require str is inconsistent and defective.

### Environment

  - **CLI Version      :**
1.58.0
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):** 

### Other

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
This is an L1 class, `Duration` is an L2 class.
