### ISSUE TITLE
[aws-eks] Managed Node Groups with Launch Template Support

### ISSUE THREAD

**Issue by ten-lac** [aws/aws-cdk#10075]
Add support for [Node Group Launch Template Support](https://github.com/aws/containers-roadmap/issues/585) feature that was recently released.

### Use Case

I need the ability to add custom security groups to the worker pool.

---

This is a :rocket: Feature Request

**Comment by iliapolo** [comment]
Closing in favor of https://github.com/aws/aws-cdk/issues/9873
