### ISSUE TITLE
[aws-codepipeline] 

### ISSUE THREAD

**Issue by robert-hanuschke** [aws/aws-cdk#10079]
Add ability to specify KMS key for a Pipeline as [possible for CloudFormation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codepipeline-pipeline-artifactstore-encryptionkey.html)

There currently is no such setting for the [Pipeline ](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-codepipeline.Pipeline.html)or an [ActionProperty](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-codepipeline.ActionProperties.html).

Checking [CodeCommitSourceActionProps](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-codepipeline-actions.CodeCommitSourceActionProps.html) in aws-codepipeline-actions also does not yield a possibility.

### Use Case

When building a cross account pipeline (basically after [this example](https://aws.amazon.com/blogs/devops/aws-building-a-secure-cross-account-continuous-delivery-pipeline/)) and NOT being able to specify an encryption key, at least a CodeCommitSourceAction in CodePipeline will use the default AWS S3 KMS key of the source account (where the codecommit repository resides) to encrypt the artifacts in the tools account.

We need to specify a customer managed KMS key for security reasons and can't (or want to) give an account privileges on the default S3 key of another.

### Proposed Solution

Implement the property for a pipeline key in CDK as is available in CloudFormation.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by skinny85** [comment]
Hi @robert-hanuschke ,

this is possible today. You do it using the `artifactBucket` property when creating the Pipeline, and specifying the Key for the passed Bucket (example: https://github.com/aws/aws-cdk/blob/34f40b9fb4b467c9c7af290400efa2c8ac8c8e10/packages/%40aws-cdk/aws-codepipeline-actions/test/test.pipeline.ts#L987-L993 ).

Thanks,
Adam

**Comment by skinny85** [comment]
Also, the default is for the Pipeline to use an encrypted Bucket with a newly created Key, so it will work for cross-account scenarios out of the box.

**Comment by robert-hanuschke** [comment]
This does not work in our tests @skinny85 .

This is in the stack of our tools prerequisites (in the tools account):

```
        key = aws_kms.Key(
            self,
            id="PipelineKey",
            alias="alias/codepipeline-crossaccounts",
            description=(
                "Used by Assumed Roles in Dev/Test/Prod accounts to "
                "encrypt/decrypt code"
            ),
            enable_key_rotation=True,
            policy=key_policy_document,
        )

        artifact_bucket = aws_s3.Bucket(
            self,
            id=get_conf_artifact_bucket_name(context=self),
            bucket_name=get_conf_artifact_bucket_name(context=self),
            encryption=aws_s3.BucketEncryption.KMS,
            encryption_key=key,
            access_control=aws_s3.BucketAccessControl.BUCKET_OWNER_FULL_CONTROL
        )
```

And in our pipeline definition (also in the tools account; get_artifact_bucket_name is a function that gets the above created artifact bucket name from cdk.json):

```
        artifact_bucket = aws_s3.Bucket.from_bucket_name(
            scope=self,
            id="artifact-bucket",
            bucket_name=get_artifact_bucket_name(context=self)
        )

        pipeline = aws_codepipeline.Pipeline(
            ...,
            artifact_bucket=artifact_bucket,
            role=pipeline_role
        )
```

The CodeCommitSourceAction **still** uses the default AWS managed S3 key of the account of the CodeCommit repo (dev) to encrypt the artifact in the tools account's bucket.

**Comment by robert-hanuschke** [comment]
Opened bug report https://github.com/aws/aws-cdk/issues/10086
