### ISSUE TITLE
[aws-codepipeline] Pipeline does not respect KMS key set on artifact bucket for encrypting artifacts from CodeCommitSourceAction

### ISSUE THREAD

**Issue by robert-hanuschke** [aws/aws-cdk#10086]
Apparently, the aws-codepipeline.Pipeline construct does not respect the KMS key setting of the artifact bucket as described in https://github.com/aws/aws-cdk/issues/10079

Reopening as bug as the issue has been closed without us being able to reproduce the behavior that should happen as described by @skinny85 

### Reproduction Steps

In dev account:

```python
       self.repo = aws_codecommit.Repository(
            scope=stack,
            id="repo",
            repository_name="repo"
        )
```

In tools account (prereqs stack):

```python
       key = aws_kms.Key(
            self,
            id="PipelineKey",
            alias="alias/codepipeline-crossaccounts",
            enable_key_rotation=True,
            policy=key_policy_document,
        )

        artifact_bucket = aws_s3.Bucket(
            self,
            id=get_conf_artifact_bucket_name(context=self),
            bucket_name=get_conf_artifact_bucket_name(context=self),
            encryption=aws_s3.BucketEncryption.KMS,
            encryption_key=key,
            access_control=aws_s3.BucketAccessControl.BUCKET_OWNER_FULL_CONTROL
        )
```

in tools account (pipeline stack):

```python
       artifact_bucket = aws_s3.Bucket.from_bucket_name(
            scope=self,
            id="artifact-bucket",
            bucket_name=get_conf_artifact_bucket_name(context=self)
        )

        # get_repository_arn is a function that reads the arn of the repo created in the dev account from cdk.json
        repo = aws_codecommit.Repository.from_repository_arn(
            self,
            id="repo",
            repository_arn=get_repository_arn(context=self)
        )

        pipeline = aws_codepipeline.Pipeline(
            scope=self,
            id="pipeline",
            pipeline_name="pipeline",
            artifact_bucket=artifact_bucket,
            role=pipeline_role
        )

        source_stage = pipeline.add_stage(stage_name="Source")

        source_stage.add_action(
            aws_codepipeline_actions.CodeCommitSourceAction(
                action_name="CodeCommitSource",
                repository=repo,
                output=aws_codepipeline.Artifact(
                    artifact_name="SCCheckoutArtifact"
                ),
                branch="develop",
                run_order=1,
                role=aws_iam.Role.from_role_arn(
                    self,
                    id="cc-role",
                    role_arn="<codecommit role in dev account>"
                ),
            )
        )
```

### What did you expect to happen?

The pipeline respecting the key set on the artifact_bucket (in its own account no less) to encrypt the CodeCommit artifact. 
As there is no explicit attribute to set an encryption key (in contrast to the [possibility in CloudFormation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codepipeline-pipeline-artifactstore-encryptionkey.html)), that was assumed.

### What actually happened?

The artifact is encrypted using the default AWS managed KMS key for S3 of the source (dev) account, making it inaccessible for the later steps of the pipeline.

### Environment

  - **CLI Version      :** aws-cli/2.0.28 Python/3.7.7 Windows/10 botocore/2.0.0dev32
  - **Framework Version:** 1.59.0 (build 1d082f4)
  - **Node.js Version:**  v12.18.2
  - **OS               :** Windows 10
  - **Language (Version):** Python 3.8.5

### Other

We need to use a customer managed KMS key here for security reasons. Giving the tools account privileges to use the AWS managed KMS key for S3 of the dev account is not an option.

--- 

This is :bug: Bug Report

**Comment by robert-hanuschke** [comment]
Just tested in the same accounts, using the same repo, key, roles etc but using the CfnPipeline resources where the pipeline key is a specific attribute of the artifact_store attribute. 

With that configuration, the pipeline works at it uses the correct key for en/decryption. I wouldn't know how to achieve the same status with the "proper" CDK resources which would be the goal here, but this shows that there is no privilege problem cross account in our setup or something like that.

Used code:
```
        cfn_source_stage = aws_codepipeline.CfnPipeline.StageDeclarationProperty(
            name="Source",
            actions=[
                aws_codepipeline.CfnPipeline.ActionDeclarationProperty(
                    name="CodeCommitSource",
                    action_type_id=aws_codepipeline.CfnPipeline
                    .ActionTypeIdProperty(
                        category="Source",
                        owner="AWS",
                        provider="CodeCommit",
                        version="1"
                    ),
                    configuration={
                        "RepositoryName": repo.repository_name,
                        "BranchName": "develop"
                    },
                    role_arn=(
                        f"arn:aws:iam::{get_conf_account_id(context=self, stage='Dev')}:role/"
                        f"{CICD.get_codepipeline_codecommit_role_name(context=self)}"
                    ),
                    run_order=1,
                    output_artifacts=[
                        aws_codepipeline.CfnPipeline.OutputArtifactProperty(
                            name="SCCheckoutArtifact"
                        )
                    ]
                )
            ]
        )

        cfn_build_stage = aws_codepipeline.CfnPipeline.StageDeclarationProperty(
            name="Build",
            actions=[
                aws_codepipeline.CfnPipeline.ActionDeclarationProperty(
                    name="Build",
                    action_type_id=aws_codepipeline.CfnPipeline
                    .ActionTypeIdProperty(
                        category="Build",
                        owner="AWS",
                        provider="CodeBuild",
                        version="1"
                    ),
                    configuration={"ProjectName": build_project.project_name},
                    run_order=1,
                    input_artifacts=[
                        aws_codepipeline.CfnPipeline.InputArtifactProperty(
                            name="SCCheckoutArtifact"
                        )
                    ]
                )
            ]
        )

        cfn_pipeline = aws_codepipeline.CfnPipeline(
            scope=self,
            id="cfnpipelinetest",
            name="cfnpipelinetest",
            role_arn=pipeline_role.role_arn,
            artifact_store=aws_codepipeline.CfnPipeline.ArtifactStoreProperty(
                location=artifact_bucket.bucket_name,
                encryption_key=aws_codepipeline.CfnPipeline
                .EncryptionKeyProperty(id=key.key_arn, type="KMS"),
                type="S3"
            ),
            stages=[cfn_source_stage, cfn_build_stage]
        )
```

**Comment by skinny85** [comment]
Hey @robert-hanuschke ,

the problem is that in the pipeline you're using this key:

```python
       artifact_bucket = aws_s3.Bucket.from_bucket_name(
            scope=self,
            id="artifact-bucket",
            bucket_name=get_conf_artifact_bucket_name(context=self)
        )
```

Obviously, that Bucket does not have a Key associated with it.

You have 2 options:

1. Use `from_bucket_attributes` instead, passing the `encryption_key` property to it to indicate that Bucket has an encryption Key.
2. Recommended: pass `artifact_bucket` from the pre-reqs stacks to your pipeline stack directly (do not use `from_bucket_*` methods at all).

BTW, I would appreciate if you didn't open multiple GitHub issues for the same problem (just comment in the closed one, and I'll re-open it if you don't have that option).

Thanks,
Adam

**Comment by robert-hanuschke** [comment]
Hi @skinny85 ,

thanks for the reply. I reopened as the last one was a feature request and this one is a bug - if it's in the end all the same and just controlled by tags, I'll keep that in mind. Sorry for the inconvenience.

Thing about the subject matter: That bucket absolutely has a key associated with it. It is the same bucket defined above with

```
artifact_bucket = aws_s3.Bucket(
            self,
            id=get_conf_artifact_bucket_name(context=self),
            bucket_name=get_conf_artifact_bucket_name(context=self),
            encryption=aws_s3.BucketEncryption.KMS,
            encryption_key=key,
            access_control=aws_s3.BucketAccessControl.BUCKET_OWNER_FULL_CONTROL
        )
```

The from_arn function uses the same get_conf_artifact_bucket_name() function reading the exact same value from cdk.json as the original instantiation of the Bucket object.

I also see the key in the console configured on the bucket and a different key (the AWS managed S3 standard from the repo's account) on the object uploaded by the CodeCommitSourceAction. Never did we anywhere specify this key in any definition.

Kind regards,
Robert

**Comment by robert-hanuschke** [comment]
On second thought, am I possibly misinterpreting what you mean by "Obviously, that Bucket does not have a Key associated with it."?

As bucket names are globally unique, the from_bucket_name() function definitely references the same bucket, so much is clear.

But as I'm importing the resource, cdk at that point can indeed uniquely identify which bucket I mean but is NOT aware of the rest of the configuration it has? And I can make it **aware** of the key's existence in the first place by rather using from_bucket_attributes and naming the key as one of them which will make the aws_codepipeline.Pipeline object pick up on it?

Is that way of thinking about it correct?

**Comment by skinny85** [comment]
I'm not sure what you're saying here. I gave you 2 options above to solve this problem, please report back after you've tried either (or both) of them.

**Comment by robert-hanuschke** [comment]
Right, so that from_bucket_attributes worked, thank you!

For anyone possibly stumbling at the same thing, the gist of it:

When creating a Bucket construct that represents an external bucket (the aws-s3.Bucket.from_... functions) and the encryption key of it is important - use the from_attributes() function have the key as one of the parameters there.

I had the wrong way of thinking here, believing the from_bucket_arn()/from_bucket_name() function would possibly be able to gather that during the synth step. They aren't.

Do:
```
        pipeline = aws_codepipeline.Pipeline(
            ...
            artifact_bucket=aws_s3.Bucket.from_bucket_attributes(
                scope=self,
                id="artifact-bucket-pipeline-test",
                bucket_arn=bucket_arn,,
                encryption_key=key
            )
        )
```

This enables the Pipeline construct to set the encryption key of the artifact store to the one of the bucket which will be respected by a CodeCommitSourceAction to any account.

Don't:
```
        pipeline = aws_codepipeline.Pipeline(
            ...
            artifact_bucket=aws_s3.Bucket.from_bucket_arn()
            # also don't: artifact_bucket=aws_s3.Bucket.from_bucket_name()
        )
```

This sets the encryption key of uploaded artifacts to the default AWS managed S3 key of the CodeCommit's account if using a CodeCommitSourceAction.
