### ISSUE TITLE
[@aws-cdk/pipelines] Use existing S3 bucket as CodePipeline artifact bucket

### ISSUE THREAD

**Issue by dihmuzikien** [aws/aws-cdk#10080]
Make `CdkPipeline` construct has an option for reusing existing S3 bucket as CodePipeline Artifact bucket

### Use Case

- Hitting a limit of buckets in AWS account
- Have some policies on the existing buckets 

### Proposed Solution

Add `Bucket= null` in `CdkPipelineProps`. Create a new bucket if none is specified. Something like

```ts
new CdkPipeline(this, 'Pipeline', {
      pipelineName: `${this.stackName}-CicdPipeline`,
      cloudAssemblyArtifact,
      Bucket = "myS3Bucket",
      synthAction: SimpleSynthAction.standardNpmSynth({
        sourceArtifact,
        cloudAssemblyArtifact,
        buildCommand: './build.sh',
      }),
    });
```

### Other

N/A

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by jpSimkins** [comment]
This is already supported... 
I am already using a single S3 bucket for my artifacts. You just need to defined the bucket.
```
this._artifactsS3Bucket = Bucket.fromBucketArn(this, 'S3ArtifactsBucket', this._props.s3ArtifactBucketARN);
new Pipeline(this, 'Pipeline', {
      artifactBucket: this._artifactsS3Bucket,
      pipelineName: this._pipelineName,
      restartExecutionOnUpdate: true
});
```

PiplineProps:
```
    /**
     * The S3 bucket used by this Pipeline to store artifacts.
     *
     * @default - A new S3 bucket will be created.
     */
    readonly artifactBucket?: s3.IBucket;
```

**Comment by dihmuzikien** [comment]
@jpSimkins Thanks for your reply but I think that's a different construct. This is `CdkPipeline` not `codepipeline.Pipeline`. It looks like it's built on top of codepipeline.Pipeline though. Might be able to just pass PipelineProps to CdkPipeline constructor

**Comment by rix0rrr** [comment]
Fixed by https://github.com/aws/aws-cdk/pull/10148

**Comment by quincycs** [comment]
Thanks for the workaround.  I do want to call out that I found myself here after encountering the same issue as the original post.  As other folks who continue using the straightforward/easy API will eventually hit the same limit over time.  I hope those folks are not shipping urgent commits when they do hit the limit.
