### ISSUE TITLE
[apigateway] Ability to specify custom cloudwatch role

### ISSUE THREAD

**Issue by excavador** [aws/aws-cdk#10094]
Take a look there: https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-apigateway/lib/restapi.ts#L505

Class `SpecRestApi` always invokes `configureCloudWatchRole` (in case if `props.cloudWatchRole` missed as well in case if `props.cloudWatchRole` specified)

https://github.com/aws/aws-cdk/blob/384f9cb5e90dba577a216d04cfc0f85a1fc94714/packages/%40aws-cdk/aws-apigateway/lib/restapi.ts#L394

Method `configureCloudWatchRole` unconditionally create new role.

As result, `props.cloudWatchRole` option does not make any sense

### Reproduction Steps

```
new apigateway.LambdaRestApi(.... { cloudWatchRole: <some role>})
```

### What did you expect to happen?

AWS::ApiGateway::Account uses my role

### What actually happened?

AWS::ApiGateway::Account uses unconditionally created role from `configureCloudWatchRole`

### Environment

  - **CLI Version      :** does not matter
  - **Framework Version:**: 1.61.0
  - **Node.js Version:** does not matter
  - **OS               :** does not matter
  - **Language (Version):** TypeScript (3.8.3)

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
`cloudwatchRole` is a boolean. Role creation and configuration will be skipped if you set it to `false`.

We currently don't have an option to configure your own role here. This can definitely be added. Is this what you're looking for?

**Comment by excavador** [comment]
> cloudwatchRole is a boolean. Role creation and configuration will be skipped if you set it to false.

I missed it.

> We currently don't have an option to configure your own role here. This can definitely be added. Is this what you're looking for?

Yes. I need some analogue of LogRetention role for lambda. When I have fine-grained project permissions, I need to follow our internal policy (role name/used managed policies).

That's why I am looking to ability to configure the CloudWatch role

**Comment by nija-at** [comment]
Marking this as a feature request. 

@excavador - you can work around this by setting `cloudwatchRole` to `false` and configuring [`CfnAccount`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-apigateway.CfnAccount.html).

**Comment by excavador** [comment]
@nija-at thank you for workaround

**Comment by alvyn279** [comment]
I'm gonna pick this up if no one is taking it.

**Comment by nija-at** [comment]
@alvyn279 - this `CfnAccount` cloudwatch role area has a few holes here that needs a proper re-think. 
We've got issues like https://github.com/aws/aws-cdk/issues/7140, https://github.com/aws/aws-cdk/issues/10722 and https://github.com/aws/aws-cdk/issues/10878 in our repo.

I would recommend picking something else up, if you're looking to contribute to the CDK. On the other hand, the workaround I've provided above should work if you're looking to fix this specific issue.
