### ISSUE TITLE
[aws-codepipeline-actions] GitHubSourceAction source filtering for monorepo's

### ISSUE THREAD

**Issue by jamiepmullan** [aws/aws-cdk#10098]
We have a few monorepo's where we want to keep the source of the pipeline as GitHubSourceAction; so that the pipelines are kept super simple.
Is it possible to add to GitHubSourceAction so that it allows you to filter and trigger based files which have been edited in a particular package?

The impact is that at the moment when we merge to master, it will trigger all Pipelines configured to the monorepo (as they're configured with GitHubSourceAction).

### Use Case

To enable us to continue using CodePipeline, and not put in a subsidiary CodeBuild action to do this filtering before passing to the pipeline.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by skinny85** [comment]
Hey @jamiepmullan ,

thanks for opening the issue. Unfortunately, I don't think that's possible, even if the `trigger` property of the `GitHubSourceAction` is `GitHubTrigger.WEBHOOK`. Apparently, you can set the [`JsonPath` property in `WebhookFilterRule` to a custom value](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codepipeline-webhook-webhookfilterrule.html#cfn-codepipeline-webhook-webhookfilterrule-jsonpath), but the [GitHub webhook payload doesn't surface which files are part of the push](https://developer.github.com/webhooks/event-payloads/#push).

You can always pass `trigger` as `GitHubTrigger.NONE`, and create the `CfnWebhook` resource directly if you want to take a crack at implementing it for your use case, but I'm afraid it won't be possible. But let me know if you manage to get it to work though!

Thanks,
Adam
