### ISSUE TITLE
[cfn-include] Ref'd `Parameters` in `Conditions` are not replaced when `parameters` are set to ""

### ISSUE THREAD

**Issue by ds17f** [aws/aws-cdk#10107]
I have a CloudFormation template which has both `Parameters` and `Conditions`.  The `Conditions` `Ref` the `Parameters`.  When I set the `parameters` field on the props while instantiating a CfnInclude construct, and then run `cdk synth` (or `deploy` or `diff`),  I see an exception if I set the value of the parameter to the empty string.  

If the parameter is named `SomeParameter`, The error message reads: 
```
Element used in Ref expression with logical ID: 'SomeParameter' not found
```

### Reproduction Steps

`Bug.json` - A cfn template with a parameter and condition
```
{
    "AWSTemplateFormatVersion": "2010-09-09",
    "Description": "Example of bug with conditions ref'ing parameters",
    "Parameters": {
        "SomeParameter": {
            "Type": "String",
            "Description": "Some Value"
        }
    },
    "Conditions": {
        "SomeParameterIsNotEmpty": {
            "Fn::Not": [
                {
                    "Fn::Equals": [
                        {
                            "Ref": "SomeParameter"
                        },
                        ""
                    ]
                }
            ]
        }
    },
    "Resources": {
        "SSMValue": {
            "Type": "AWS::SSM:Parameter",
            "Properties": {
                "Type": "String",
                "Name": "SomeValue",
                "Value": {
                    "Ref": "SomeParameter"
                }
            }
        }
    }
}
```

A CfnInclude construct to add to a stack
```
        // An example of the bug
        const template = new cfn_inc.CfnInclude(this, 'BugConstruct', {
            templateFile: `${__dirname}/Bug.json`,
            parameters: {
                "SomeParameter": ""
            }
        });
```

### What did you expect to happen?
I'd expect to see the value `""` replaced wherever a `Ref` points to `SomeParameter`.  This works as expected with a non-empty string value.

### What actually happened?
The `cdk synth` command failed producing the following error:
```
Element used in Ref expression with logical ID: 'SomeParameter' not found
```

### Environment

  - **CLI Version      :** 1.61.1
  - **Framework Version:** 1.61.1
  - **Node.js Version:** v10.16.3
  - **OS               :** macOS 10.12.6
  - **Language (Version):** TypeScript (3.8.3)

### Other
I did some digging and I'm fairly sure that the issue lies here: 
https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/core/lib/cfn-parse.ts#L435
```
if (specialRef) {
```
and is a result of the value returned from `this.specialCaseRefs` here:
https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/core/lib/cfn-parse.ts#L651-L666

`this.specialCaseRefs` appears to have 3 classes of return value: 
1) the value of the parameter
2) an enum related to the `AWS::*` flag
3) undefined if it's none of these.

if the value of the parameter is falsey (such as an empty string) then the returned value will be seen as NOT a `specialRef` and will not be replaced.

I think the fix is simple, but I haven't tested it.  Will try to open a PR if possible.  The fix should just be:
```
if (specialRef !== undefined) {
```

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hey @ds17f ,

thanks a lot for opening the issue. Yes, I'm fairly certain the fix is exactly to change

```ts
if (specialRef) {
```

to

```ts
if (specialRef !== undefined) {
```

Would appreciate a PR :) Check out our [`Contributing` docs](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md#gitpod) for some tips on how to do that!

Thanks,
Adam

**Comment by skinny85** [comment]
@ds17f how's it going? Do you need something for the PR?

**Comment by ds17f** [comment]
@skinny85 Work wasn't in scope for the story.  :)  As simple as the fix is I don't have an env setup for cdk build work.  I made a gitpod but it started to eat up time that I didn't have allotted. 

I will get to this ASAP, but honestly I'm guessing that you could probably wrap this before I actually got it done.  It's really just the test that's holding me up here too.  I know the fix is stupid easy.

**Comment by skinny85** [comment]
OK, I'll take this one then, no worries 🙂
