### ISSUE TITLE
[pipelines] Support vpc in SimpleSynthAction

### ISSUE THREAD

**Issue by samlecuyer** [aws/aws-cdk#10108]
`SimpleSynthOptions` support a few codebuild options, particularly environment variables. I would also like to pass in a VPC, subnets, and security groups to CodeBuild project that's created.

### Use Case

My team uses a couple of internal repositories that require the build project to run in a specific VPC/subnet. Without the ability to specify a network configuration, the installer cannot access these services and cannot complete the installation.

### Proposed Solution

I would propose expanding the SimpleSynthOptions to support more of the `CommonProjectProps` fields, or to add a new field called `additionalProjectProps : CommonProjectProps` and passing these through to the created CodeBuild Project.

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by markusl** [comment]
Looks similar to what we need #9982

**Comment by rix0rrr** [comment]
If SimpleSynthAction and ShellScriptAction don't satisfy your needs, I recommend you setup a CodeBuild Project directly instead.

**Comment by rix0rrr** [comment]
Duplicate of #9982
