### ISSUE TITLE
[core] addOverride method does not allow for the addition of properties containing periods

### ISSUE THREAD

**Issue by enjaygee** [aws/aws-cdk#10109]
Within @aws-cdk/core/lib/cfn-resource.ts, the public addOverride method accepts a property path and a value. The path is split using a period to allow for dot notation:
    const parts = path.split('.');

Unfortunately, this means that a key (such as 'skip.header.line.count' which is used by Athena for CSV files with a header line) cannot be included.

### Reproduction Steps

example :
cfnTbl.addOverride("Properties.TableInput.StorageDescriptor.SerdeInfo.Parameters.skip.header.line.count", "1");
escaping the periods in the key also fails.

    TableInput:
      StorageDescriptor:
        SerdeInfo:
          Parameters:
            skip:
              header:
                line:
                  count: "1"

### What did you expect to happen?
Able to use method in some manner (e.g., by escaping the key):

```
cfnTbl.addOverride("Properties.TableInput.StorageDescriptor.SerdeInfo.Parameters.skip\\.header\\.line\\.count", "1");

    TableInput:
      StorageDescriptor:
        SerdeInfo:
          Parameters:
            skip.header.line.count: "1"
```

### What actually happened?
See above.

### Environment

  - **CLI Version      : 1.59.0 (build 1d082f4)**
  - **Framework Version: 1.61.1**
  - **Node.js Version: 10.21.0** 
  - **OS               : CentOS Linux release 8.0.1905 (Core) **
  - **Language (Version): TypeScript** 

### Other

--- 

This is :bug: Bug Report

**Comment by enjaygee** [comment]
Replacing:

`
const parts = path.split('.');
`
with

`
const parts = path.match(/([^\\\][^.]|\\.)+/g) || [""];
for(var i=0; i < parts.length; i++) {
 parts[i] = parts[i].replace(/\\/g, '');
}
`
allows for paths to be escaped, e.g.:

`
const path = "Properties.TableInput.StorageDescriptor.SerdeInfo.Parameters.skip\\.header\\.line\\.count"

//const parts = path.split('.');

const parts = path.match(/([^\\\][^.]|\\.)+/g) || [""];
for(var i=0; i < parts.length; i++) {
 parts[i] = parts[i].replace(/\\/g, '');
}

console.log(parts); // returns [ "Properties", "TableInput", "StorageDescriptor", "SerdeInfo", "Parameters", "skip.header.line.count" ]
`

**Comment by rix0rrr** [comment]
You are right, we need escape character support.
