### ISSUE TITLE
[kinesis-analytics] No Docs for aws-kinesisanalytics

### ISSUE THREAD

**Issue by captainrandom** [aws/aws-cdk#10102]
On the aws-kinesisanalytics overview page, there are no docs. Please write some.

https://docs.aws.amazon.com/cdk/api/latest/docs/aws-kinesisanalytics-readme.html

---

This is a 📕 documentation issue

**Comment by Chriscbr** [comment]
Generally doc information only gets added in modules where L2 or L3 constructs have been added. Right now, it looks like the library currently only has L1 constructs (these directly represent the raw cloudformation resources, and don't provide any additional abstraction - see [this page](https://docs.aws.amazon.com/cdk/latest/guide/constructs.html) for more info about the different kinds of constructs).

If you want more information about using the kinesis analytics constructs, I'd recommend going through the individual resources and properties in the sidebar, and/or look at the corresponding section about Kinesis Analytics on the [AWS CloudFormation docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_KinesisAnalytics.html), or look at the [Kinesis Analytics developer guide](https://docs.aws.amazon.com/kinesisanalytics/latest/dev/what-is.html). Hope this helps!
