### ISSUE TITLE
[@aws-cdk/pipelines] Why does the build step bundle all assets even though they are not used in the stack that the pipeline deploys

### ISSUE THREAD

**Issue by adamskicool** [aws/aws-cdk#10122]
In my project I am using two CdkPipelines to deploy one stack each. These stacks contain one lambda each that uses code from asset and docker to bundle typescript code. After deploying these pipelines I can see that the Build step bundles the assets from both stacks.

Why does the build step bundle all assets even though they are not used in the stack that the pipeline deploys?

### Environment

  - **CDK CLI Version:** 1.61.1
  - **Module Version:** 1.61.0
  - **Node.js Version:** v10.16.3
  - **OS:** OSX Catalina
  - **Language (Version):** Typescript (3.9.3)

**Comment by rix0rrr** [comment]
That's a good question. I feel that shouldn't happen. Can you share some of the source?

**Comment by adamskicool** [comment]
Yeah sure, here is some source code and description.

The entry point is simple, just creates two Stacks that use `CdkPipeline` (will get to them shortly):

```javascript
import { App } from "@aws-cdk/core";
import { Pipeline1 } from "./stacks/pipeline/custom-pipelines/pipeline-1/pipeline";
import { Pipeline2 } from "./stacks/pipeline/custom-pipelines/pipeline-2/pipeline";
const app = new App();

new Pipeline1(app, "pipeline-1");
new Pipeline2(app, "pipeline-2");
```

The pipelines (`Pipeline1`, `Pipeline2`) are identical, just that their respective Stage is different. They both use construct `CdkPipelineBaseConstruct` and give it a stage prop (applicationStage) that in the construct is used with the CdkPipeline function `addApplicationStage`. 

```javascript
export class Pipeline1 extends Stack {
  constructor(
    scope: Construct,
    id: string
  ) {
    super(scope, id);
     
  	const pipelineName: string = 'cdk-pipeline-name-1'

    const applicationStage: Stage = new Stage1(
      this,
      "stage-1"
    );
    new CdkPipelineBaseConstruct(
      this,
      "cdk-pipeline-1",
      {
        applicationStage,
        pipelineName
      }
    );
  }
}
```

The `CdkPipelineBaseConstruct` looks something like this:

```javascript
...

export interface CdkPipelineBaseConstructProps
  extends StackProps {
  applicationStage: Stage;
  pipelineName: string;
}

/**
 * The stack that defines the application pipeline
 */
export class CdkPipelineBaseConstruct extends Construct {
  ...

  constructor(
    scope: Construct,
    id: string,
    props?: CdkPipelineBaseConstructProps
  ) {
    super(scope, id);

    ...

    const sourceArtifact = new codepipeline.Artifact();
    const cloudAssemblyArtifact = new codepipeline.Artifact();

    const pipeline = new CdkPipeline(
      this,
      "Pipeline",
      {
        // The pipeline name
        pipelineName:
          props.pipelineName,
        cloudAssemblyArtifact,

        // Where the source can be found
        sourceAction: new codepipeline_actions.GitHubSourceAction(
          {
            actionName: "GitHub",
            output: sourceArtifact,
            oauthToken: ...
            owner: ...,
            repo: ...,
            branch: this.getDeploymentBranch(),
          }
        ),

        // How it will be built and synthesized
        synthAction: SimpleSynthAction.standardNpmSynth(
          {
            sourceArtifact,
            cloudAssemblyArtifact,
            environment: {
              buildImage:
                codebuild
                  .LinuxBuildImage
                  .STANDARD_2_0,
              privileged: true,
            },
            synthCommand:
              "npx cdk synth --exclusively",
          }
        ),
      }
    );

    // This is where we add the application stages
    pipeline.addApplicationStage(
      props.applicationStage,
      { manualApprovals: true }
    );

  }
}


```

The stage that we pass to the `CdkPipelineBaseConstruct` looks something like this:

```javascript
import {
  CfnOutput,
  Construct,
  Stage,
  StageProps,
} from "@aws-cdk/core";
import { BundlingTestStack } from "../../../bundling-test-stack";

export class Stage1 extends Stage {
  constructor(
    scope: Construct,
    id: string
  ) {
    super(scope, id);

    new BundlingTestStack(
      this,
      `application-stack-1`
    );
  }
}

```

where the `BundlingTestStack` creates a lambda function from Asset and uses the option to bundle using a docker container.

**Comment by rix0rrr** [comment]
Nothing obviously jumps out at me here. You could have a look at the `cdk.out/*-assembly/*.asset.json` files as well to see which ones are in there.

I think it's unlikely that they're the same assets though. Probably both stacks just have 2 assets: 1 you were expecting and potentially 1 that got automatically added by a framework construct?
