### ISSUE TITLE
[aws-s3-assets] exclude is marked as deprecated under AssetOptions

### ISSUE THREAD

**Issue by jimhooker2002** [aws/aws-cdk#10125]
exclude is marked as deprecated under AssetOptions here: https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-s3-assets.AssetOptions.html

There is no clear alternative provided.  If this ends up deprecated then there would be no way to exclude files from the asset.

We rely on the ability to exclude files in order to make sure platform dependent files (built differently on local vs Jenkins machines) do not end up as part of the asset, impacting SHA generation.

Please either un-mark this attribute as deprecated and continue to support it, or specify an alternative way to ensure an asset can exclude particular files/globs.

**Comment by jogold** [comment]
It has been moved to `@aws-cdk/core`. It's deprecated in favor of `core.CopyOptions` (which remains):

https://github.com/aws/aws-cdk/blob/4e5829ac5bb55533435772c3f2f294394ab2c973/packages/%40aws-cdk/core/lib/fs/options.ts#L36-L50

**Comment by jimhooker2002** [comment]
Wonderful! Thank you for the information.  Not sure if the docs could/should be updated to make that more obvious.  Good to know the feature isn't going away however!

**Comment by jogold** [comment]
@eladb it would nice to add the deprecation reason to the generated docs in the property description (https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-s3-assets.AssetOptions.html#exclude-span-class-api-icon-api-icon-deprecated-title-this-api-element-is-deprecated-its-use-is-not-recommended-span).

Where is the code for this? I've looked into `jsii-docgen` but it looks like it only renders a table with the properties, is the AWS CDK api docs a modified version?

**Comment by iliapolo** [comment]
@jogold Reference documentation code is not currently available in the public repo. I'll mark an internal feature request to see if we can add this. 

Thanks
