### ISSUE TITLE
resource generation reduction - apigateway via swagger and/or inline policies

### ISSUE THREAD

**Issue by ikluzak** [aws/aws-cdk#1014]
I have a CloudFormation stack for an application made from 12 dynamodb tables, 34 lambdas and an API gateway protected with Cognito user pool authorization.   Currently it's generating 236 resources when I do a cdk deploy.   This of course means I can't deploy.

A grep of the synthesized output shows that I have 34 Policies and 35 Roles in the stack.   @eladb suggested I could possibly define the API with Swagger to try and reduce the number of definitions.

Some of the lambda's invoke other lambda's.

Some of the lambda's are DynamoDB table triggers.

Just doesn't seem to be a great way to split this into multiple stacks.

**Comment by nija-at** [comment]
I'm not entirely sure what the suggestion or request here is.

Is this a request to support swagger definitions in the CDK or documentation on how to split stacks or something else? What things would help you get a better experience with your CDK app?

**Comment by SomayaB** [comment]
> I'm not entirely sure what the suggestion or request here is.
> 
> Is this a request to support swagger definitions in the CDK or documentation on how to split stacks or something else? What things would help you get a better experience with your CDK app?

@ikluzak

**Comment by SomayaB** [comment]
Closing this issue since there hasn't been activity on it in a while. Feel free to reopen
