### ISSUE TITLE
[ecs] Step Scaling policy does not create all steps

### ISSUE THREAD

**Issue by kyler-hyuna** [aws/aws-cdk#10141]
I'm using the `scaleOnMetric` method of the FargateService construct. My requirements need 2 policies.

```ts
construct.scaling.scaleOnMetric('scale-up-policy', {
  scalingSteps: [
    {
      lower: 65,
      change: +2,
    },
    {
      lower: 85,
      change: +3,
    },
  ],
  metric: construct.service.metricCpuUtilization({
    statistic: 'Maximum',
    period: cdk.Duration.minutes(1),
  }),
  cooldown: cdk.Duration.minutes(2),
});

construct.scaling.scaleOnMetric('scale-down-policy', {
  scalingSteps: [
    {
      upper: 50,
      change: -1,
    },
    {
      upper: 40,
      change: -2,
    },
  ],
  metric: construct.service.metricCpuUtilization({
    statistic: 'Average',
  }),
});
```

However it never creates the 65 step. It only creates >85 step.

![Screenshot 2020-09-02 at 3 35 05 PM](https://user-images.githubusercontent.com/13733609/92028458-16823080-ed32-11ea-86a7-a36033707909.png)

### Reproduction Steps

- Create a FargateService
- Add autoscaling
- Make step scaling policies as outlined above

### What did you expect to happen?

I should have 2 alarms created with the actions:

- low alarm
  - remove 1 task < 50% CPU
  - remove 2 tasks < 40 % CPU

- high alarm
  - add 2 tasks > 65% CPU
  - add 3 tasks > 85% CPU

### Environment

  - **CLI Version      :** 1.61.1
  - **Framework Version:** 1.61.1
  - **Node.js Version:**  v14.8.0
  - **OS               :** mac os
  - **Language (Version):**  typescript

### Other

--- 

This is :bug: Bug Report

**Comment by kyler-hyuna** [comment]
Even worse I added in the 65 step twice to test, and now it works. This is definitely a bug

```ts
construct.scaling.scaleOnMetric('scale-up-policy', {
  scalingSteps: [
    {
      lower: 65,
      change: +2,
    },
    {
      lower: 65, // Duplicate of above
      change: +2,
    },
    {
      lower: 85,
      change: +3,
    },
  ],
  metric: construct.service.metricCpuUtilization({
    statistic: 'Maximum',
    period: cdk.Duration.minutes(1),
  }),
  cooldown: cdk.Duration.minutes(2),
});
```

![Screenshot 2020-09-02 at 4 13 26 PM](https://user-images.githubusercontent.com/13733609/92031847-3e27c780-ed37-11ea-8eff-65d0ceb2b5b8.png)

**Comment by olivier-schmitt** [comment]
Same issue in with the Python version; it's a very annoying bug.
Is there a workaround?

**Comment by kyler-hyuna** [comment]
@olivier-schmitt try this

> Even worse I added in the 65 step twice to test, and now it works. This is definitely a bug
> 
> ```ts
> construct.scaling.scaleOnMetric('scale-up-policy', {
>   scalingSteps: [
>     {
>       lower: 65,
>       change: +2,
>     },
>     {
>       lower: 65, // Duplicate of above
>       change: +2,
>     },
>     {
>       lower: 85,
>       change: +3,
>     },
>   ],
>   metric: construct.service.metricCpuUtilization({
>     statistic: 'Maximum',
>     period: cdk.Duration.minutes(1),
>   }),
>   cooldown: cdk.Duration.minutes(2),
> });
> ```
> 
> ![Screenshot 2020-09-02 at 4 13 26 PM](https://user-images.githubusercontent.com/13733609/92031847-3e27c780-ed37-11ea-8eff-65d0ceb2b5b8.png)

**Comment by SoManyHs** [comment]
Hi @kyler-hyuna ,

What happens when you use the aws cli to describe the service/autoscaling policy?

**Comment by kyler-hyuna** [comment]
Hey @SoManyHs 

The code:

```ts
scaleOnMetric('scale-up-policy', {
    scalingSteps: [
      {
        lower: 40,
        change: +3,
      },
      {
        // FIXME: https://github.com/aws/aws-cdk/issues/10141
        lower: 40,
        change: +3,
      },
      {
        lower: 60,
        change: +5,
      },
    ],
    metric: construct.service.metricCpuUtilization({
      statistic: 'Maximum',
      period: cdk.Duration.minutes(1),
    }),
    cooldown: cdk.Duration.minutes(2),
  });
```

The describe (just kept the scaling part of it):

```json
"StepScalingPolicyConfiguration": {
    "AdjustmentType": "ChangeInCapacity",
    "StepAdjustments": [
        {
            "MetricIntervalLowerBound": 0.0,
            "MetricIntervalUpperBound": 20.0,
            "ScalingAdjustment": 3
        },
        {
            "MetricIntervalLowerBound": 20.0,
            "ScalingAdjustment": 5
        }
    ],
    "Cooldown": 120,
    "MetricAggregationType": "Maximum"
}
```

**Comment by coleman-c** [comment]
We are seeing similar unexpected behaviors.  I'm using the .netcore CDK version 1.76.0

The configuration

`[
                    {
                      "Lower": 300,
                      "Change": 1
                    },
                    {
                      "Lower": 600,
                      "Change": 2
                    },
                    {
                      "Lower": 900,
                      "Change": 3
                    }
                  ]`

Results in the following:
```
[
  {
    "MetricIntervalLowerBound": 0,
    "MetricIntervalUpperBound": 300,
    "ScalingAdjustment": 2
  },
  {
    "MetricIntervalLowerBound": 300,
    "ScalingAdjustment": 3
  }
]
```

Wheras I think is should be:
```
[
  {
    "MetricIntervalLowerBound": 300,
    "MetricIntervalUpperBound": 600,
    "ScalingAdjustment": 1
  },
  {
    "MetricIntervalLowerBound": 600,
    "MetricIntervalUpperBound": 900,
    "ScalingAdjustment": 2
  },
  {
    "MetricIntervalLowerBound": 900,
    "ScalingAdjustment": 3
  }
]
```

**Comment by YuryShchanouskiTR** [comment]
Any updates?

**Comment by matheushent** [comment]
Any update on it? I'm facing this.

![Screen Shot 2021-06-24 at 09 21 41](https://user-images.githubusercontent.com/45343359/123261937-bda4a400-d4cd-11eb-864e-6293db629420.png)
![Screen Shot 2021-06-24 at 09 22 01](https://user-images.githubusercontent.com/45343359/123261944-c006fe00-d4cd-11eb-9e80-18383f8d2bd8.png)

**Comment by ruancomelli** [comment]
Hi @SoManyHs
What should be the expected behaviour when the user does not provide any intervals starting from `lower=0`? Should we prepend a dummy scaling interval that takes no actions (that is, `change=0`)? If so, I can readily work on a PR for that.

**Comment by kyler-hyuna** [comment]
Thanks for fixing this @ruancomelli 🎉
