### ISSUE TITLE
[@aws-cdk/aws-ecr-assets] Arguments without values

### ISSUE THREAD

**Issue by enricopesce** [aws/aws-cdk#10150]
### Description

In a docker build command, I can specify build arguments without values, in this way I can use the environment variables mapped to the arguments.

For example in docker command:
```
export var_name="prod"
docker build --build-arg var_name ...
```

### Use Case

With the AWS CDK DockerImageAsset I can't omit the value and I can't use an environment variable as docker command line.

### Benefits
For example, from codebuild instance, is useful to get a secret value with:

```
env:
  parameter-store:
    var_name: gittoken
```
end passing var_name to the docker build phase

I tried with an empty value but not works:

```
    const app_asset = new ecr_assets.DockerImageAsset(this, 'app_asset', {
      directory: path.join(__dirname, '../../'),
      file: 'docker/app/Dockerfile',
      buildArgs: {
        var_name: ""
      }
    })
```

This is a :rocket: Feature Request

**Comment by jogold** [comment]
Wouldn't this work for you?

```ts
if (!process.env.var_name) throw new Error('Missing env var...');

const app_asset = new ecr_assets.DockerImageAsset(this, 'app_asset', {
  directory: path.join(__dirname, '../../'),
  file: 'docker/app/Dockerfile',
  buildArgs: {
    var_name: process.env.var_name
  }
})
```

**Comment by eladb** [comment]
> Wouldn't this work for you?
> 
> 
> 
> ```ts
> 
> if (!process.env.var_name) throw new Error('Missing env var...');
> 
> 
> 
> const app_asset = new ecr_assets.DockerImageAsset(this, 'app_asset', {
> 
>   directory: path.join(__dirname, '../../'),
> 
>   file: 'docker/app/Dockerfile',
> 
>   buildArgs: {
> 
>     var_name: process.env.var_name
> 
>   }
> 
> })
> 
> ```

My thought exactly.

**Comment by enricopesce** [comment]
sure yesterday I have implemented this :) 

The reason for this that I can't pass secret data (SSM or Parameter store) directly from CDK.

Thank you!
