### ISSUE TITLE
Add support for NodeJS latest versions v13.x

### ISSUE THREAD

**Issue by jairov4** [aws/aws-cdk#10157]
Add support for NodeJS latest versions (v13.x in the moment)

### Use Case

AWS CDK is locking its users to specific version of NodeJS reducing its usage spectrum.
More than 2 major versions are leading the nodeJS version supported.

### Proposed Solution

Identify blockers and allow use newer versions

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by hoegertn** [comment]
Can you elaborate or your use case? I am using CDK with Node 14 at the moment.

**Comment by jairov4** [comment]
Hi, This page indicates that CDK is not working with NodeJS v13 and I performed some light test and noticed not working with v12 also (maybe I made a mistake here?).

https://docs.aws.amazon.com/cdk/latest/guide/getting_started.html#getting_started_prerequisites

**Comment by hoegertn** [comment]
It is not working with some versions of v13 as there was a bug. But v12, v14, and some v13 versions are working perfectly.

**Comment by SomayaB** [comment]
@jairov4 were you able to make it work with v12 or v14? As stated above only some versions of v13 should not work.

**Comment by jairov4** [comment]
no I didnt tried anymore, just adopted to work on v10
