### ISSUE TITLE
Deployment wont create S3 resources for lambdas 

### ISSUE THREAD

**Issue by whelen-cchevalier** [aws/aws-cdk#10154]
I tried deploying last night and cloudformation was failing with an s3 resource not found exception for its source files. The buckets for said source files did not have anything in them. This morning I tried deleting those buckets to get the service to upload them but they wont.

### Reproduction Steps
Im using the following constructor to define source code location locally.
```ts
const lambda = this.createLambda('test', "test.handler");
```

### What did you expect to happen?

The files would be uploaded

### What actually happened?

The CLI interface never goes through the upload file portion.

### Environment

  - **CLI Version:**     1.54.0
  - **Framework Version:** 1.11
  - **Node.js Version:** 6.13.4
  - **OS:**            windows10
  - **Language (Version):** typescript

### Other

--- 

This is :bug: Bug Report

**Comment by NGL321** [comment]
Hey @whelen-cchevalier,

Thank you for reporting this. Unfortunately, since `createLambda` is your own function, we have no way of knowing what is going on behind the scenes. Could you please provide more complete source code so we can look into this more?

😸 😷
