### ISSUE TITLE
[CLI] Record any changes in stack termination protection flag as an event in the stack itself

### ISSUE THREAD

**Issue by idclipr** [aws/aws-cdk#10163]
Record any changes in stack termination protection flag as an event in the stack itself.

### Use Case

Currently `cdk bootstrap` command enables and disables the termination protection flag based on the presence or absence of the ` --termination-protection` option in the command line. Users can also modify that flag in AWS Console at any time.

However, this change does not have any audit record and it's impossible to understand when/why/by whom the flag setting have changed.

### Proposed Solution

Add a "stack event" for the termination protection flag change so that it shows up in "Events" in AWS Console.

### Other

This is somewhat a follow-up to https://github.com/aws/aws-cdk/pull/9002 and subsequent https://github.com/aws/aws-cdk/issues/10091, so it can be considered a bug of how the flag was implemented to begin with (and not a new "feature").

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request but could be viewed as a bug of the initial implementation

**Comment by rix0rrr** [comment]
We don't have the power to make those changes in the AWS Console. But CloudTrail has a full record of all API calls done to any service so it will show up there.

**Comment by SomayaB** [comment]
Closing this issue since there doesn't seem to be anything actionable for the cdk. Feel free to reopen.
