### ISSUE TITLE
[@aws-cdk/pipelines] Adding cross-account application stage does not add sufficient KMS permission

### ISSUE THREAD

**Issue by dihmuzikien** [aws/aws-cdk#10166]
Following [this doc](https://aws.amazon.com/blogs/developer/cdk-pipelines-continuous-delivery-for-aws-cdk-applications/) for multi-account deployment in CdkPipeline, KMS created for cross-region/cross-account role does not trust the cloudformation role used for CloudFormation Action in the pipeline.

### Reproduction Steps

Follow https://aws.amazon.com/blogs/developer/cdk-pipelines-continuous-delivery-for-aws-cdk-applications/ and create multi-account deployment stack, attempt to deploy to a different account.

### What did you expect to happen?
KMS key policy should be created with policy that trusts all the accounts that will be deploying the payload.

### What actually happened?

KMS policy does not have a statement trusting any role from the secondary account resulting in
`Access Denied (Service: Amazon S3; Status Code: 403; Error` in CloudFormation `CHANGE_SET_REPLACE` action of Cross-account stage

### Environment

  - **CLI Version      :** 1.61.1
  - **Framework Version:** 1.61.1
  - **Node.js Version:** v10.19.0
  - **OS               :** Ubuntu on Windows (WSL2)
  - **Language (Version):** C# dotnetcore 3.1

### Other

--- 

This is :bug: Bug Report

**Comment by dihmuzikien** [comment]
This is probably related to https://github.com/aws/aws-cdk/issues/3765
but since `ArtifactBucket` isn't exposed in CdkPipeline, the workaround suggested here doesn't work for me, unfortunately.

**Comment by corymhall** [comment]
@rix0rrr It looks like something broke between versions 1.59.0 and 1.60.0. I created a simple test below. 

```ts
const app = new cdk.App();

const pipelineStack = new cdk.Stack(app, 'PipelineStack', {
  env: {
    account: 'ACCOUNT1',
    region: 'us-east-2'
  }
});

const sourceArtifact = new codepipeline.Artifact();
const cloudAssemblyArtifact = new codepipeline.Artifact();

const pipeline = new pipelines.CdkPipeline(pipelineStack, 'Pipeline', {
  pipelineName: 'DeliveryPipeline',
  cloudAssemblyArtifact,
  sourceAction: new actions.GitHubSourceAction({
    actionName: 'GitHub',
    output: sourceArtifact,
    oauthToken: cdk.SecretValue.secretsManager('token'),
    trigger: actions.GitHubTrigger.WEBHOOK,
    owner: 'owner',
    repo: 'repo',
    branch: 'main'
  }),
  synthAction: pipelines.SimpleSynthAction.standardNpmSynth({
    sourceArtifact,
    cloudAssemblyArtifact,
  })
});

pipeline.addApplicationStage(
  new AppStage(app, 'east2App', {
    env: {
      account: 'ACCOUNT2',
      region: 'us-east-2'
    }
  })
);

pipeline.addApplicationStage(
  new AppStage(app, 'east1App', {
    env: {
      account: 'ACCOUNT2',
      region: 'us-east-1'
    }
  })
);
```

If I run this with the version pinned to 1.59.0 it correctly generates the us-east-1 support stack with the correct KMS key policy, i.e.
```json
{
  "Action": [
     "kms:Decrypt",
      "kms:DescribeKey"
  ],
  "Effect": "Allow",
  "Principal": {
     "AWS": {
       "Fn::Sub": "arn:${AWS::Partition}:iam::ACCOUNT2:role/cdk-hnb659fds-deploy-role-ACCOUNT2-us-east-1"
     }
  },
  "Resource": "*"
}
```

If I update the versions to 1.60.0 this action is no longer generated.

**Comment by rix0rrr** [comment]
I just tried deploying a cross-account pipeline using `1.61.1` and it seems to work for me.

I guess it's about the specific resources that are in `AppStage`, and how they use assets. What are they?

**Comment by rix0rrr** [comment]
Oh it's about the support stack, so it's actually about both cross-account AND cross-region?

**Comment by corymhall** [comment]
Yeah cross-account seems to work fine for me, it's only when I add cross-region that the issue occurs.
