### ISSUE TITLE
[@aws-cdk/aws-apigateway] RestApi deployment validation in 1.57.0+ occurring too soon

### ISSUE THREAD

**Issue by johnmarian** [aws/aws-cdk#10164]
The changes to how `RestApi` constructs are validated in packages/@aws-cdk/aws-apigateway/lib/deployment.ts in 1.57.0  are causing an error to get thrown before custom construct using `RestApi` is finished configuring the API.

### Reproduction Steps

(This may not be a regression, but may instead just need a new way of configuring the constructs - I can provide more detailed steps on how to use the library if needed, but you might be able to see the issue from the code and explanations in the 'Other' section)
Using this library: 
https://gitlab.com/cloud-kung-fu/ckf-cdk-rest-api
Locally set CDK versions to 1.57.0
Compile with `tsc`
Use `npm link` to install to a local project and set the project to 1.57.0

Configure an API with multiple endpoints. Run `cdk synth`.

### What did you expect to happen?
Should synthesize without error.

### What actually happened?
Fails with error:
```
Error: Validation failed with the following errors:
  [DEV-VidConLotteryEntryApiStack/EntryApi/EntryApiRestApi] The REST API doesn't contain any methods
    at validateTree ([LOCAL PROJECT PATH]/cdk/node_modules/@aws-cdk/core/lib/private/synthesis.ts:140:11)
    at Object.synthesize ([LOCAL PROJECT PATH]/cdk/node_modules/@aws-cdk/core/lib/private/synthesis.ts:23:5)
    at App.synth ([LOCAL PROJECT PATH]/cdk/node_modules/@aws-cdk/core/lib/stage.ts:175:23)
    at process.<anonymous> ([LOCAL PROJECT PATH]/cdk/node_modules/@aws-cdk/core/lib/app.ts:112:45)
    at Object.onceWrapper (events.js:417:26)
    at process.emit (events.js:310:20)
    at process.EventEmitter.emit (domain.js:482:12)
    at process.emit ([LOCAL PROJECT PATH]/cdk/node_modules/source-map-support/source-map-support.js:495:21)
    at process.topLevelDomainCallback (domain.js:137:15)
Subprocess exited with error 1
```

### Environment

  - **CLI Version      : 1.57.0+**
  - **Framework Version: 1.57.0+**
  - **Node.js Version: Tried with 10.15.3, 12.16.2, and 14.9.0** 
  - **OS               : OS X 10.14.6**
  - **Language (Version): TypeScript 3.9.7** 

### Other

I'm using this library: https://gitlab.com/cloud-kung-fu/ckf-cdk-rest-api and by locking everything to v1.56.0 everything works. If I lock to 1.57.0 the error occurs. I can trace in that code that the validation error is being thrown before the `configure` method at https://gitlab.com/cloud-kung-fu/ckf-cdk-rest-api/-/blob/master/index.ts#L60 has a chance to complete (which is where the methods are being created).

The diff between 1.56.0 and 1.57.0 (https://github.com/aws/aws-cdk/compare/v1.56.0...v1.57.0#) shows that the validation completely changed in `packages/@aws-cdk/aws-apigateway/lib/deployment.ts` and `packages/@aws-cdk/aws-apigateway/lib/restapi.ts`

If this isn't actually a regression, is there updated documentation/a workaround on how to apply methods to a `RestApi` construct so that they're created before the validation occurs?

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
Could you provide a code sample to reproduce this error using just the CDK APIs without using the intermediate library?

**Comment by johnmarian** [comment]
I tried to set up some code to reproduce, and can no longer reproduce with 1.62.0.
