### ISSUE TITLE
[pipelines/core] Pipeline stuck if automatic references removed

### ISSUE THREAD

**Issue by rix0rrr** [aws/aws-cdk#10172]
Let's say there are 2 stacks and they are deployed in a pipeline, with an automatic cross-stack reference between them:

```
                   deploy order                       
─────────────────────────────────────────────────────▶
                                                      
  ┌──────────────┐                ┌──────────────┐    
  │              │                │              │    
  │   Producer   │◀───────────────│   Consumer   │    
  │              │  { Fn::Import  │              │    
  └──────────────┘     Value }    └──────────────┘    
```

Removal of the use of a cross-stack reference is going to lead to the `Export` being removed from the producer stack in the new template.

However, in the pipeline the Producer stack will be deployed before the Consumer stack, and at that point it's not allowed to remove the `Export` yet as the `Consumer` that's currently deployed still depends on it.

The pipeline is therefore stuck, and there's no way to work around this.

With the CLI, this is not a giant issue as one can manually deploy the `Consumer` first to remove the reference, and then deploy as normal.

The best way around this is probably to switch to weak references everywhere, otherwise I don't see a solution.

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
See also https://github.com/aws/aws-cdk/issues/7602

**Comment by rix0rrr** [comment]
Adam's written a nice blog post about it: https://www.endoflineblog.com/cdk-tips-03-how-to-unblock-cross-stack-references

**Comment by justin8** [comment]
@rix0rrr id argue that this has a workaround, but I don’t see how to use that workaround within a CDK pipeline since you don’t directly have access to easily deploy one stack at a time in there. Should this be closed?
