### ISSUE TITLE
[ecs-patterns] Doesn't allow you to specify a security group and create a security group with no ingress

### ISSUE THREAD

**Issue by tachyonics** [aws/aws-cdk#10196]
ECS patterns such as `NetworkLoadBalancedFargateService` 
1. Don't allow you to specify a security group and create a security group with no ingress[2] which seems unexpected since the pattern is explicitly fronted by a load balancer. 
2. Always creates a target group with port 80 which is unexpected if you have already specified a containerPort that isn't port 80.

[1] https://github.com/aws/aws-cdk/blob/v1.62.0/packages/%40aws-cdk/aws-ecs/lib/base/base-service.ts#L621-L623
[2] https://github.com/aws/aws-cdk/blob/v1.62.0/packages/%40aws-cdk/aws-ecs-patterns/lib/base/network-load-balanced-service-base.ts#L284-L286

### Reproduction Steps

```typescript
const fargateService = new NetworkLoadBalancedFargateService(this, fargateExecutable.name, {
                    cluster: cluster, // Required
                    cpu: 512, // Default is 256
                    desiredCount: 6, // Default is 1
                    taskImageOptions: { image: ecs.ContainerImage.fromDockerImageAsset(dockerImageAsset),
                                        containerPort: 8080
                                      },
                    memoryLimitMiB: 2048, // Default is 512
                    publicLoadBalancer: false, // Default is false
                    assignPublicIp: true,
                    listenerPort: 9090,
                });
```

### What did you expect to happen?

A Fargate service would be created where the containers could be called through the listenerPort of the load balancer.

### What actually happened?

Containers were being dropped from the target group as they were considered unhealthy. Requests to the load balancer port failed as the security group had no ingress rules set up.

### Environment

  - **CLI Version      :** v1.62.0
  - **Framework Version:** v1.62.0
  - **Node.js Version:** v12.10.0
  - **OS               :** macOS 10.15
  - **Language (Version):** TypeScript (3.8.3)

--- 

This is :bug: Bug Report

**Comment by SoManyHs** [comment]
We're tracking this issue here: https://github.com/aws/aws-cdk/issues/11969

Closing for now as duplicate. Please feel free to add any detail to the tracking issue!
