### ISSUE TITLE
[aws-cdk] CloudFormation template not updating after CDK deployment 

### ISSUE THREAD

**Issue by johnasiano** [aws/aws-cdk#10204]
### The Question

I have a generated Swagger json file. I have a CDK app that reads in this file and then I do

```ts
const cfnRestApi = this.api.node.defaultChild as apigateway.CfnRestApi;
cfnRestApi.body = JSON.parse(JSON.stringify(swaggerDefinition));
```
After doing cdk deploy when I look at the Cloud Formation template it contains my Swagger info. However when I make changes to the Swagger json file, the template in CloudFormation is not updating even after cdk deploy runs successfully. 

How can I resolve this?

### Environment

  - **CDK CLI Version:**  1.41.0 (build 9e071d2)

  - **Module Version:** 
  - **Node.js Version:**  v12.17.0

  - **OS:**  Mac
  - **Language (Version):**  Typescript

**Comment by peterwoodworth** [comment]
Hey @johnasiano, apologies for no one responding to this yet

I can't reproduce this on the current version of CDK. How are you creating your `swaggerDefinition` variable?
