### ISSUE TITLE
[cloudfront] High level support for AWS::CloudFront::RealtimeLogConfig resource type 

### ISSUE THREAD

**Issue by laurrentt** [aws/aws-cdk#10202]
## Add support for the `AWS::CloudFront::RealtimeLogConfig` resource type

2 days ago, CloudFormation added a new resource type for configuring realtime logging on CloudFront cache behaviours. Obviously being such a recent addition to CloudFormation, I understand this is not yet implemented in CDK. However I thought creating an issue would signify interest and also serve as a way to track the implementation progress.

**Comment by laurrentt** [comment]
I just noticed a low-level CFN Resource constructs support will be added through automation in https://github.com/aws/aws-cdk/pull/10201, although I'd still be interested to have a high-level support of it.

**Comment by SomayaB** [comment]
Hi @laurrentt, as you've discovered, [CFN Resources are periodically generated from the AWS CloudFormation Resource Specification](https://docs.aws.amazon.com/cdk/latest/guide/constructs.html) automatically and are usually up within a few days to a week. I'll update this issue to be a high-level feature request.

**Comment by mrvini** [comment]
Hi, 
is there any updates on this issue? trying to setup realtime log configuration(with Kinesis Data Stream) and attach it to the cloud front distribution, but as of right now haven't found a way or examples online. please advise
Thanks

**Comment by robertsonsamuel** [comment]
@mrvini also trying to do this in https://github.com/serverless-nextjs/serverless-next.js/issues/2284 and hitting the same roadblock. Would love not to have to update logs here. Did you ever find a workaround for this? Does AWS expose any ability to set the distribution id yet?

**Comment by daniel-gato** [comment]
Same here, any news on this?

**Comment by cyberst** [comment]
Are there any plans of implementing this feature?

**Comment by ajoseph-godaddy** [comment]
Any updated on this? There still seems to be no way for us to access the RealtimeLogConfig of the distro via CDK.

**Comment by vaughan-rich** [comment]
+1 - any update on this?

**Comment by chrisammon3000** [comment]
Any update?

**Comment by SantiRaposo** [comment]
Any updates on this issue? There is not way to access each behavior's real time log configuration from the L2 construct.

**Comment by colifran** [comment]
I believe this https://github.com/aws/aws-cdk/pull/26808 closes this issue. Will reopen if needed.
