### ISSUE TITLE
[aws-ec2] Asset based file fingerprint is not included in ec2 user data.

### ISSUE THREAD

**Issue by allanlw** [aws/aws-cdk#10206]
When using CFN init with an `ec2.Instance`, setting `userDataCausesReplacement` (not default) and `initOptions.embedFingerprint` (the default) normally means modifying the provided CloudFormationInit will replace the instance.

However, with `InitFile` (added in #9664) using `InitFile.FromAsset` to specify a local file to be delivered as an asset, updating the local file does not update the fingerprint embedded in the user data, so instances are not replaced, even though the new asset is deployed.

### Reproduction Steps

1. Create an [`ec2.Instance`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ec2.Instance.html) with `userDataCausesReplacement` and `initOptions.embedFingerprint` and a `CloudFormationInit` containing an `InitFile.FromAsset` with a local file.
2. Deploy.
3. Modify the local file.
3. Deploy

### What did you expect to happen?

The instance should be replaced.

### What actually happened?

The instance is not replaced, even though the asset is.

### Environment

  - **CLI Version      :** 1.62.0
  - **Framework Version:** 1.62.0
  - **Node.js Version:** v12.18.0
  - **OS               :** Linux
  - **Language (Version):** Typescript

### Other

This might be intended and/or desirable behavior. Regardless, a flag like `includeFileAssetsInFingerprint` on `initOptions` or `includeInFingerprint` on `initFileOptions` would be prudent.

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
No, you are correct that this is a bug.

**Comment by allanlw** [comment]
Wow, thanks for the quick turn around! Cheers!
