### ISSUE TITLE
[aws-lambda-nodejs] 1.62.0 - fails to compile 

### ISSUE THREAD

**Issue by mbonig** [aws/aws-cdk#10210]
While trying to `cdk synth` a NodejsFunction construct, it errors:

unable to determine cloud assembly output directory. Assets must be defined indirectly within a "Stage" or an "App" scope

This problem does not exist if I rollback to 1.61.0

### Reproduction Steps

Here is a repo that reproduces the problem:

https://github.com/mbonig/nodejs-fails-example

### What did you expect to happen?

I expected the synth to work like it did in 1.61.0

### What actually happened?

Got an error and the template failed to synth

### Environment

  - **CLI Version      :** 1.62.0
  - **Framework Version:** 1.62.0
  - **Node.js Version:**  v12.16.1
  - **OS               :** Distributor ID: LinuxMint
Description:    Linux Mint 19.3 Tricia
Release:        19.3
Codename:       tricia

  - **Language (Version):** Typescript

### Other

--- 

This is :bug: Bug Report

**Comment by jogold** [comment]
Are you sure all your modules are on 1.62.0?

**Comment by mbonig** [comment]
yes.

**Comment by jogold** [comment]
@mbonig this is an error from `core` when outdir cannot be determined. Does a "regular" Lambda function works? I suspect a problem with any construct using assets in your case.

**Comment by mbonig** [comment]
Works fine with a regular Function.

**Comment by jogold** [comment]
> Works fine with a regular Function.

@mbonig I'm now able to reproduce. Very strange... on it.

**Comment by jogold** [comment]
OK I found the issue 😄 

For some unknown reason your `package-lock.json` contains incorrect nested cdk dependencies (see https://github.com/mbonig/nodejs-fails-example/pull/1/files for the diff which fixes it).

This leads to `@aws-cdk/assets` having another "copy" of `@aws-cdk/core` than the one used by `@aws-cdk/aws-lambda-nodejs` (the version is the same though):

![image](https://user-images.githubusercontent.com/12623249/92704279-2235ae80-f353-11ea-9ed1-b31c0d784fcb.png)

I think that the multiple copies of `@aws-cdk/core` break all the `Symbol.for` logic used by core to check if an `App` is an `App`:

https://github.com/aws/aws-cdk/blob/287f808cf34870295e4032995fc083ac204b64c3/packages/%40aws-cdk/core/lib/app.ts#L83-L85


@mbonig how did you end up with this `package-lock.json`?

@eladb you should have a look at this.

**Comment by jogold** [comment]
> This was a very clean and basic new CDK module. So all I did to get here was a `cdk init --language=typescript`, an `npm i` and then started writing code and got errors...

Which version of npm are you using?

**Comment by mbonig** [comment]
Looks like this comes from the [bump-cdk](https://www.npmjs.com/package/bump-cdk) tool I had used to upgrade the versions. 

Closing this and reviewing the tool. Thanks!
