### ISSUE TITLE
[@aws-cdk/aws-codepipeline-actions] Disabled public access on Artifact Bucket

### ISSUE THREAD

**Issue by sudo-shubham** [aws/aws-cdk#10214]
### The Question
CodePipeline actions such as `CodeCommitSourceAction` or `CodeBuildAction` expects `codepipeline.Artifact` as output. But the created artifact buckets has public accces enabled. Is there a way that we can provide existing S3 Buckets in the outputs arguments? Or we can disable public access in codepipeline.Artifact while creating it?
### Environment

  - **CDK CLI Version:** 1.62.0
  - **Module Version:** 1.62.0
  - **Node.js Version:** v12.18.1
  - **OS:** OSX Catalina
  - **Language (Version):** TypeScript (3.8.3)

**Comment by skinny85** [comment]
Hello @sudo-shubham ,

thanks for opening the issue, but I'm not sure what you mean. The default S3 Bucket that gets created for CodePipeline has [public access explicitly disabled](https://github.com/aws/aws-cdk/blob/f945334df339965308e6abb58ebaa0cc82c4c353/packages/%40aws-cdk/aws-codepipeline/lib/pipeline.ts#L238-L238). If you want something different, you can always pass a Bucket you created yourself with the [`artifactsBucket` property](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-codepipeline.Pipeline.html#artifactbucket).

Thanks,
Adam

**Comment by sudo-shubham** [comment]
Let me reiterate the second question. Whenever I am using `CodeBuild` or `S3SourceAction` the outputs parameter expect `codepipeline.Artifact` as an argument. Can we provide existing bucket in outputs?

#### Current:

    const testOutput = new codepipeline.Artifact();
    new codepipeline_actions.CodeBuildAction({
        actionName: 'Test',
        project: TestStage,
        input: sourceOutput,
        outputs: [testOutput]
      })

####  Expected:

    new codepipeline_actions.CodeBuildAction({
        actionName: 'Test',
        project: TestStage,
        input: sourceOutput,
        outputs: [Bucket.fromName('ArtifaceBucket')]
      })

**Comment by skinny85** [comment]
Are you asking if each Action can have their own S3 Bucket?
