### ISSUE TITLE
[lambda] 'valueAsString' works well with lazy resolution with lambda environment variables but the type 'Number' does not.

### ISSUE THREAD

**Issue by knihit** [aws/aws-cdk#10228]
I am using CfnParameter to read various parameters. One of the parameter types is a 'Number' with min value 1 and max value as 100. This value of this parameter is then passed as the lambda environment key value pairs. When I use 'valueAsNumber' method in conjunction with the lambda environment variables, cdk synth does not synthesize this code for lazy resolution through 'Ref'. It rather assigns a value to the lambda environment variable during synth process. 'valueAsString' works well with lazy resolution with lambda environment variables but the type 'Number' does not.

### Reproduction Steps
        const numberOfTopics = new CfnParameter(this, 'NumberOfTopics', {
            type: 'Number',
            default: 10,
            minValue: 1,
            maxValue: 100,
            description: 'The number of topics to be discovered by Topic analysis. The min value is 1 and maximum value is 100'
        });

In another section of the code where I read the CfnParameter values
###
            lambdaFunctionProps: {
                runtime: Runtime.NODEJS_12_X,
                handler: 'index.handler',
                code: Code.fromAsset(`${__dirname}/../../lambda/wf-submit-topic-model`),
                environment: {
                    INGESTION_WINDOW: props.ingestionWindow,
                    RAW_BUCKET_FEED: props.rawBucket.bucketName,
                    **NUMBER_OF_TOPICS: props.numberofTopics,**
                    STACK_NAME: props.stackName
                },
                timeout: Duration.minutes(5),
                memorySize: 512
            },

### What did you expect to happen?
        "NUMBER_OF_TOPICS": {
          "Ref": "NumberOfTopics"
        },

### Environment

  - **CLI Version:**              aws-cli/2.0.44 Python/3.8.5 Darwin/19.6.0 source/x86_64
  - **Framework Version:** 1.62.0
  - **Node.js Version:**       14.9.0
  - **OS:**                            MacOS
  - **Language (Version):** 4.0.2

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
It's because stringification happens in TypeScript without regard to whether it's a Token or not.

Should have been `Tokenization.stringify()`.

**Comment by knihit** [comment]
@rix0rrr, can you please help me understand how should I be reading CfnParameter Number types for lambda functions, is there another way to read them.

**Comment by rix0rrr** [comment]
Yes that will do it.

**Comment by nija-at** [comment]
What language are you using here? typescript or javascript?

The [type for the `environment` property](https://github.com/aws/aws-cdk/blob/483e319d7818ea683cd7d11bd3a7ee5ed2962cc9/packages/%40aws-cdk/aws-lambda/lib/function.ts#L68) is `{ [key: string]: string }`, however `numberOfTopics` is of type `CfnParameter`. So typescript should fail at the compile step if you do the assignment you've claimed as problematic.

If you're on javascript, I believe it's up to you to ensure that you're performing the correct assignments.

As noted, using `valueAsString()` will get you the string representation of the token

**Comment by knihit** [comment]
The language for the runtime is typescript.

@nija-at agree that the lambda environment variable is a string. Traditionally if I were to use CFN directly, I can define the parameter as a Number and have it Ref into the Lambda environment variables. This way I get appropriate parameter validation. In CDK if I can still use it as 'Number' and then be able to Ref the variable when assigning to Lambda still works fine. So there are two problems that I see
1. Having CfnParameter as a Number does not synthesize into the json template. So I cannot do valueAsNumber().toString() when assigning it to lambda environment variables
2. If I use CfnParameter as a String, it does synthesize correctly and I can use it as valueAsString() but I need to add a regex instead of having to provide a min/ max value. So I lose the capability to perform appropriate validation.

**Comment by nija-at** [comment]
Thanks for the explanation @knihit. I see the problem.

**Comment by nija-at** [comment]
You can workaround this by using `Token.asString(numberOfTopics.value)`
