### ISSUE TITLE
[aws-lambda-python] example code does not work, using wrong libraries 

### ISSUE THREAD

**Issue by justin8** [aws/aws-cdk#10229]
link to reference doc page: https://docs.aws.amazon.com/cdk/api/latest/docs/aws-lambda-python-readme.html

describe your issue:

The docs refer to `lambda.PythonFunction` when that is a part of the `aws-lambda-python` module and not `aws-lambda`. Then 3 lines later refer to `lambda.Runtime.PYTHON_3_6` when that *is* a part of the `aws-lambda` module. So it seems for this code to work you must import both `aws-lambda-python` and `aws-lambda` in the same namespace of `lambda`

---

This is a 📕 documentation issue

**Comment by eladb** [comment]
Thanks for reporting. Would be happy to take a contribution for a fix
