### ISSUE TITLE
[aws-apigatewayv2]  HttpMethod.ANY throws error in deployment when specifying AllowedMethods of CORS configuration

### ISSUE THREAD

**Issue by mscheer93** [aws/aws-cdk#10230]
When setting up an HttpApi from [api-gatewayv2](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-apigatewayv2-readme.html), you can specify in [corsPreflight](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-apigatewayv2.HttpApi.html#corspreflight-span-class-api-icon-api-icon-experimental-title-this-api-element-is-experimental-it-may-change-without-notice-span) param the allowed HTTP methods for CORS.
This requires to specify an array of supported HTTP methods from [enum HttpMethod](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-apigatewayv2.HttpMethod.html). 

With code example listed below, `cdk deploy` throws an error saying `Method ANY is not supported` when deploying the stack.

### Reproduction Steps

1. cdk init sample project
2. Declare HttpApi via code snippet below
3. run `cdk deploy --trace --verbose `
4. Inspect trace

```typescript
import * as apiv2 from "@aws-cdk/aws-apigatewayv2";

const api = new apiv2.HttpApi(this, "SimpleApi", {
      corsPreflight:{
        allowHeaders: ["authorization", "x-id-token", "content-type"],
        allowOrigins: ["http://localhost:3000",],
        allowMethods: [HttpMethod.ANY],
        allowCredentials: false
      }
})
```

### What did you expect to happen?

Support `HttpMethod.ANY` from [enum HttpMethod](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-apigatewayv2.HttpMethod.html), when setting AllowMethods in [corsPreflight](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-apigatewayv2.HttpApi.html#corspreflight-span-class-api-icon-api-icon-experimental-title-this-api-element-is-experimental-it-may-change-without-notice-span) param of HttpApi.

### What actually happened?

Deploy Trace: 
```
...
 | CREATE_FAILED        | AWS::ApiGatewayV2::Api                    | HttpApi/SimpleApi (HttpApiSimpleApiF9EF49E2) Method ANY is not supported (Service: AmazonApiGatewayV2; Status Code: 400; Error Code: BadRequestException; Request ID: XXXXXXXXXXXXXXXXX; Proxy: null)
...
```

### Environment

  - **CLI Version      : 1.62.0**
  - **Framework Version:**
  - **Node.js Version: v14.8.0**  
  - **OS               : Linux Mint 20 Ulyana** 
  - **Language (Version): TypeScript 4.0.2** 

### Other

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
This seems to be a validation enforced by APIGateway that disallows the use of `ANY` method for CORS preflight. This is not a CDK limitation. 

Let me know if I misunderstood anything.

**Comment by mscheer93** [comment]
Ok, thanks for the feedback. Makes sense.

You might want to leave a note in the API Gateway documentation for others.

**Comment by lorenzo2897** [comment]
Hi @nija-at , I don't think this is just a limitation of API Gateway but rather a mismatch between what is expected by API Gateway and what is exposed by CDK.

API gateway accepts `*` to represent any HTTP method. The HttpMethod enum doesn't have a value for that.
The following code synthesises and deploys correctly:
```
allowMethods: ["*"] as any
```

I would suggest to either create a separate enum for HTTP methods that aligns with what API gateway expects, or to internally map "ANY" to "*" during synthesis. It's wrong to claim that `allowMethods` accepts an array of `HttpMethod` when in fact not all possible values would be correct.

**Comment by nija-at** [comment]
@lorenzo2897 - I've opened a separate issue to track this - https://github.com/aws/aws-cdk/issues/13280
