### ISSUE TITLE
Getting error while creating DeploymentGroup in v 1.62.0  - Language Java

### ISSUE THREAD

**Issue by mohdarshad** [aws/aws-cdk#10236]
Hi, Getting the below error when creating the DeploymentGroup using v 1.62.0. 

> software.amazon.jsii.JsiiException: Cannot get policy fragment of ApplicationInfraStack/autoscallinggroup, resource imported without a role
> Error: Cannot get policy fragment of ApplicationInfraStack/autoscallinggroup, resource imported without a role

This is working fine with v 1.58.0

**Comment by RomainMuller** [comment]
Hey @mohdarshad - can you show the code that hits the error?
