### ISSUE TITLE
[aws-ec2] UserData.addSignalOnExitCommand should accept something more general than Resource

### ISSUE THREAD

**Issue by anguslees** [aws/aws-cdk#10231]
https://github.com/aws/aws-cdk/blob/8c2d7fca11bb48f43f37dc42e25de47147795452/packages/%40aws-cdk/aws-ec2/lib/user-data.ts#L173

In particular, I would like to be able to do `addSignalOnExitCommand(CfnAutoScalingGroup)`

**Comment by rix0rrr** [comment]
L1 and L2 classes are not intended to be mixed in this way. If you are down to the L1 level, you need to build the UserData yourself.
