### ISSUE TITLE
[aws-ec2] VPC "allowAllOutbound" should also allow all IPv6

### ISSUE THREAD

**Issue by anguslees** [aws/aws-cdk#10239]
VPC `allowAllOutbound=true` (the default) rejects IPv6 :(

### Environment

  - **CLI Version      :**  1.62.0
  - **Language (Version):** all

### Other

I think the fix is to change [`addDefaultEgressRule()`](https://github.com/aws/aws-cdk/blob/8c2d7fca11bb48f43f37dc42e25de47147795452/packages/%40aws-cdk/aws-ec2/lib/security-group.ts#L489) to something like (untested!):

```typescript
private addDefaultEgressRule() {
  if (this.allowAllOutbound) {
    this.directEgressRules.push(ALLOW_ALL_RULE4);
    this.directEgressRules.push(ALLOW_ALL_RULE6);
  } else {
    this.directEgressRules.push(MATCH_NO_TRAFFIC);
  }
}

const ALLOW_ALL_RULE4 = {
  cidrIp: '0.0.0.0/0',
  description: 'Allow all outbound IPv4 traffic by default',
  ipProtocol: '-1',
};

const ALLOW_ALL_RULE6 = {
  cidrIpv6: '::/0',
  description: 'Allow all outbound IPv6 traffic by default',
  ipProtocol: '-1',
};

```

--- 

This is :bug: Bug Report

**Comment by NetaNir** [comment]
Yeah it only adds Ipv4 rule currently, we will release a fix under a feature flag as fixing it will include a breaking change, see [discussion](https://github.com/aws/aws-cdk/pull/7827#discussion_r456199699)
