### ISSUE TITLE
[ec2] SecurityGroup is always creating 0.0.0.0 even if is not specified.

### ISSUE THREAD

**Issue by salsa2k** [aws/aws-cdk#10245]
Hi, I'm trying to create security groups for my RDS/ELB and for both cases I'm getting the same results.
SecurityGroup is always creating 0.0.0.0 rule, even if is not specified.

### Reproduction Steps

    this.group = new SecurityGroup(parent, `RDS`, {
      securityGroupName: `RDS`,
      vpc: props.vpc,
      allowAllOutbound: true,
      description: "RDS SG",
    });

    COMPANY_IPS.map((ip) => {
      this.group.addIngressRule(Peer.ipv4(ip), Port.tcp(DB_PORT), "DB");
    });

The Cloudformation output is generating:

    SGRDS76B3D792:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: RDS SG
      GroupName: RDS
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic by default
          IpProtocol: "-1"
      SecurityGroupIngress:
        - CidrIp: 1.2.3.4/32
          Description: DB
          FromPort: 5432
          IpProtocol: tcp
          ToPort: 5432
        - CidrIp: 5.6.7.8/32
          Description: DB
          FromPort: 5432
          IpProtocol: tcp
          ToPort: 5432
        - CidrIp: 0.0.0.0/0
          Description: from 0.0.0.0/0:5432
          FromPort: 5432
          IpProtocol: tcp
          ToPort: 5432

### What did you expect to happen?

Rule created without the Inbound 0.0.0.0, since I'm not specifying this in cdk.

### What actually happened?

Rule with open inbound is always created.

### Environment

  - **CLI Version      :**
  - **Framework Version:** 1.61.1
  - **Node.js Version:** v12.0.0
  - **OS               :** MacOS
  - **Language (Version):** Typescript 3.7.2

### Other

This case is not only for the RDS, its happing when I create an ApplicationLoadBalancer with se security group.

    const server = new ApplicationLoadBalancer(this, "Server-ALB", {
      vpc: props.vpc,
      internetFacing: true,
      loadBalancerName: "Server-ALB",
      securityGroup: sg,
    });

--- 

This is :bug: Bug Report

**Comment by NetaNir** [comment]
You are setting ` allowAllOutbound: true` which is why the rule is created, set it false and add the rules you require using `addEgressRule`/`addIngressRule` methods

**Comment by salsa2k** [comment]
thanks @NetaNir

**Comment by Voyen** [comment]
> You are setting ` allowAllOutbound: true` which is why the rule is created, set it false and add the rules you require using `addEgressRule`/`addIngressRule` methods

This makes no sense - The `allowAllOutbound` flag should only affect the egress (given it's "outbound"). There's no reason for this flag to create wide-open ingress rules.
What if I want to create a security group that allows all egress but isn't wide open to the internet?

**Comment by augustovictor** [comment]
Now the attribute seems to be just `open` on the listener.
