### ISSUE TITLE
[elbv2] Support SubnetMappings for NLBs

### ISSUE THREAD

**Issue by njlynch** [aws/aws-cdk#10242]
The `subnetMappings` property of NLBs cannot currently be set; this property allows NLBs to map subnets to private IPs and existing elastic IP allocations.

### Use Case

https://github.com/aws/aws-cdk/issues/4319#issuecomment-615851020

> Is there a way to assign existing elastic IP address to NLB via CDK? subnetMappings is not available via construct.

### Other

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-loadbalancer.html#cfn-elasticloadbalancingv2-loadbalancer-subnetmappings
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticloadbalancingv2-loadbalancer-subnetmapping.html

---

This is a :rocket: Feature Request

**Comment by michaelwiles** [comment]
There's already an issue for this #9696

**Comment by njlynch** [comment]
Thanks @michaelwiles ; closing this as a duplicate.
