### ISSUE TITLE
[aws-eks] Install helm chart from asset

### ISSUE THREAD

**Issue by plumdog** [aws/aws-cdk#10247]
Be able to specify a helm chart from a local directory path, that is then staged, and available when running `helm` in the custom resource.

### Use Case

To be able to use private helm charts without needing a private chart repository.

### Proposed Solution

Allow `chart` (https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-eks.HelmChart.html) to be an asset.

This is a :rocket: Feature Request

Related to #9273

**Comment by iliapolo** [comment]
@plumdog Is this any different that the issue you mentioned? #9273 ?

**Comment by plumdog** [comment]
Maybe - it depends what that issue becomes, which is currently not clear to me. The use case stated there is "private S3 repo" which I think is distinct from my use case being able to pass an asset.

**Comment by iliapolo** [comment]
@plumdog Gotcha, thanks 👍

**Comment by plumdog** [comment]
In retrospect, closing in favour of #9273. I have a PR, and discussing it in two places will get confusing.
