### ISSUE TITLE
[aws-lambda-python] runtime should not be optional

### ISSUE THREAD

**Issue by richardhboyd** [aws/aws-cdk#10248]
## :question: General Issue
By defaulting to Python3.7, we are guaranteeing that a breaking change will happen in the next few years when Python3.7 is EOL'd. While some breaking changes are unavoidable, we shouldn't be forcing our customers into one.

https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-lambda-python/lib/function.ts#L61

**Comment by peterwoodworth** [comment]
Sorry no one has responded to this yet @richardhboyd, I've created a PR to fix this.

@corymhall feel free to close these out if this is something we don't want to fix
