### ISSUE TITLE
Add constructs for the AWS Comprehend Service

### ISSUE THREAD

**Issue by artyom-melnikov** [aws/aws-cdk#10243]
Please add at least low-level constructs for the AWS Comprehend. Right now there is nothing at all :(

**Comment by NetaNir** [comment]
It seems like there isn't a CloudFormation resource for Comprehend. Unfortunately we will have to wait for CloudFormation to add it before we can use it in the CDK

**Comment by vitoorgomes** [comment]
Hey guys, does anyone have updates on this topic? or some ways to work around it?

**Comment by artyom-melnikov** [comment]
@vitoorgomes You can use AWS SDK (https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Comprehend.html) to manually perform operations you need after the main deployment
