### ISSUE TITLE
cross language source maps

### ISSUE THREAD

**Issue by kapilt** [aws/aws-cdk#10252]
When analyzing generated cfn outputs, we would like to be able to point out the issues to developers in the native artifacts. While typescript cdk has source maps support its unclear that this support exists with other languages, and it would be nice to support to have better analysis tools (cfn-guard, conftest, etc).

**Comment by RomainMuller** [comment]
I'm not sure source map is the right thing for this problem (at least it is not clear to me with the current problem statement).

We have an issue in `jsii` to support cross-language stack traces (aws/jsii#47). Would this solve your issue?
If not, I guess I would like to know more about the problem you are trying to solve, maybe through a practical example?

**Comment by kapilt** [comment]
we want to look at a generated cloudformation, statically analyze it for any issues (cfn guard/cfn lint style) and then provide the user feedback wrt to where in their cdk source code the issue arises.  source maps seemed like a natural fit if they can be propagated. tracebacks imply runtime generation errors, where as this analysis is post runtime  on the generated output.

**Comment by RomainMuller** [comment]
I see why you say source maps seem like a natural fit here (they do!), however the situation might be a little bit more complicated in our case (we have to often deal with 2 different languages in 2 different processes). This is a very interesting idea though; I'd really like to see that become reality!

This feature actually lies in part in the CDK core framework (to support passing the right information down to the CloudFormation template) and `jsii` (to enable doing so correctly even when the user's code isn't authored in TypeScript or JavaScript.

**Comment by shreyasdamle** [comment]
We are also interested in this feature. @kapilt can you provide some more information on how you currently do it for TypeScript?
