### ISSUE TITLE
[aws-codepipeline-actions] codebuild cross-region build actions 

### ISSUE THREAD

**Issue by amhammett** [aws/aws-cdk#10279]
AWS CodePipeline [Now Supports Cross-Region Actions](https://aws.amazon.com/about-aws/whats-new/2018/11/aws-codepipeline-now-supports-cross-region-actions/) and the CDK has been updated to allow cross-region support for cloudformation but has not been added for CodeBuild.

In https://docs.aws.amazon.com/cdk/api/latest/docs/aws-codepipeline-readme.html CloudFormationCreateUpdateStackAction is referenced as a cross-region action but attempting to use the same implementation for a CodeBuild project results in 

> Object literal may only specify known properties, and 'region' does not exist

### Use Case

I would like to be able to provision CodePipelines in CDK that utilizes cross-region CodeBuild projects. I have my primary CodeCommit repository in RegionA but have some build actions that can only be run in RegionB due to network connectivity/latency.

This capability is available via the console and CloudFormation but hasn't been introduced to CDK.

### Proposed Solution

I have a PR in waiting that, making a similar change as was implemented in https://github.com/aws/aws-cdk/issues/49 allowing for CodeBuildAction to support the region attribute.

### Other

Below is an example stack that shows current and proposed functionality.

```typescript
import {Construct, Stack, StackProps} from '@aws-cdk/core'
import {PipelineProject} from '@aws-cdk/aws-codebuild'
import {Repository} from '@aws-cdk/aws-codecommit'
import {Artifact, Pipeline} from '@aws-cdk/aws-codepipeline'
import {CodeBuildAction, CodeCommitSourceAction} from '@aws-cdk/aws-codepipeline-actions'
import {Bucket, IBucket} from '@aws-cdk/aws-s3'

export class PipelineStack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props)

    const appName = this.node.tryGetContext('appName')
    const regionSecondary = this.node.tryGetContext('regionSecondary')

    const artifactBucket = new Bucket(this, 'PipelineBucket', {
      bucketName: `${appName}-${this.region}-${this.account}`,
    })

    const crossRegionBuckets: {[key: string]: IBucket} = {}

    crossRegionBuckets[this.region] = artifactBucket
    crossRegionBuckets[regionSecondary] = Bucket.fromBucketName(this, 'CrossRegionBucket',
      `${appName}-${regionSecondary}-${this.account}`,
    )

    const sourceArtifact = new Artifact('CodeCommitSource')
    const sourceAction = new CodeCommitSourceAction({
      actionName: 'CodeCommit',
      repository: Repository.fromRepositoryArn(this, 'CodeRepository',
        this.node.tryGetContext('existingRepositoryArn'),
      ),
      output: sourceArtifact,
    })

    // this is valid
    const sameRegionBuildAction = new CodeBuildAction({
      actionName: 'CodeBuild',
      project: new PipelineProject(this, 'SameRegionBuildProject'),
      input: sourceArtifact,
    })

    // this is not invalid
    const crossRegionBuildAction = new CodeBuildAction({
      actionName: 'CodeBuild',
      project: PipelineProject.fromProjectName(this, 'CrossRegionBuildProject',
        this.node.tryGetContext('crossRegionBuildProjectArn'),
      ),
      input: sourceArtifact,
      region: regionSecondary,
    })

    new Pipeline(this, 'CodePipeline', {
      crossRegionReplicationBuckets: crossRegionBuckets,
      stages: [
        {stageName: 'Source', actions: [sourceAction]},
        {stageName: 'Build', actions: [sameRegionBuildAction, crossRegionBuildAction]},
      ],
    })
  }
}
```

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by skinny85** [comment]
Hello @amhammett ,

the CDK supports this capability natively. Just pass a CodeBuild Project that's from a different region into a `CodeBuildAction`, and everything will work!

Thanks,
Adam
