### ISSUE TITLE
[codebuild] git source miss submodules support

### ISSUE THREAD

**Issue by zxkane** [aws/aws-cdk#10271]
CodeBuild git based sources support `submodules`.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-source.html#cfn-codebuild-project-source-gitsubmodulesconfig

### Use Case

Fetching submodules of git repo when cloning the repo.

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by skinny85** [comment]
Thanks for opening the issue @zxkane . Seems like a simple `fetchSubmodules?: boolean` property added to the [`GitHubSourceProps`interface](https://github.com/aws/aws-cdk/blob/40222ef398fd1fb63b3b886624d5bb40562142c6/packages/%40aws-cdk/aws-codebuild/lib/source.ts#L572-L586). Any chance of opening us a PR adding this? 🙂 https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md
