### ISSUE TITLE
[ec2] new CfnEIPAssociation(...).Eip is null

### ISSUE THREAD

**Issue by OlegBoulanov** [aws/aws-cdk#10288]
Shouldn't it be a TOKEN, if not actual IP?

To be used in 
```
new ARecord(this, "arecord", new ARecordProps {
  //Target = RecordTarget.FromIpAddresses(elasticIPAssociations.Select(eipa => eipa.Eip).ToArray()),  // Eip:<null>, remember?
  Target = RecordTarget.FromIpAddresses(elasticIPAssociations.Select(eipa => eipa.Ref).ToArray()), // fails during deployment
...
}
```
using .Ref crashes deployment:
```
`* | 1:58:11 PM | CREATE_FAILED | AWS::Route53::RecordSet
 | ARecord-Public-PreAlloc (ARecordPublicPreAllocCB385358) [Invalid Resource Record: FATAL problem: 
ARRDATAIllegalIPv4Address (Value is not a valid IPv4 address) encountered with
 'eipassoc-0f9299c9975d21e6e'] new RecordSet (...@aws-cdk\aws-route53\lib\record-set.js:134:27)`
```
### Reproduction Steps

```
var eipa = new CfnEIPAssociation(this, "eipa", new CfnEIPAssociationProps
{
  AllocationId = a,
  InstanceId = h.Instance.InstanceId,
});
Console.WriteLine($"Elastic IP: AllocationId:{eipa.AllocationId}, InstanceId:{eipa.InstanceId}, Eip:{eipa.Eip??"<null>"}, Ref:{eipa.Ref??"<null>"}");
```
Output:
`Elastic IP: AllocationId:eipalloc-0d717ea12b4e13c69, InstanceId:${Token[TOKEN.497]}, Eip:<null>, Ref:${Token[TOKEN.499]}`

### What did you expect to happen?

I'd expect it to be a TOKEN, or actual IP

### What actually happened?

It's null

### Environment

  - **CLI Version      :**
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):** 

### Other

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
`cfnXxx.propertyName` is a mutable property of the value you put in as a constructor property, which is `null` if you didn't specify one.

You are looking for `cfnXxx.attrAttributeName`.

**Comment by OlegBoulanov** [comment]
Thank you
