### ISSUE TITLE
[cloudformation] cloudformation deleting the entire pipeline 

### ISSUE THREAD

**Issue by math1eur** [aws/aws-cdk#10293]
### The Question

Why is cloudformation deleting the entire pipeline when deploying a template using `_codepipeline_actions.CloudFormationCreateUpdateStackAction_`

I have configurered a cdk stack and deployed locally from my machine, the pipeline is based on this [example](https://docs.aws.amazon.com/cdk/latest/guide/codepipeline_example.html). However, whenever my stack is deployed and eaches the clean up stage, then entire pipeline is also deleted

any help!

### Environment

  - **CDK CLI Version:** 1.62.0
  - **Module Version:**  1.62.0
  - **Node.js Version:** v12.16.3
  - **OS:** 
  - **Language (Version):**

**Comment by skinny85** [comment]
Hello @rmmang ,

sorry, what is "cleanup stage" here?

Thanks,
Adam

**Comment by rmmang** [comment]
@skinny85, I'm referring to _cleanup_ here as in one of **cloudformation** processing **steps** (see screenshot).
This cleanup deletes my pipeline entirely (including codebuild stacks..)

<img width="884" alt="Screenshot 2020-09-11 at 09 57 13" src="https://user-images.githubusercontent.com/1298059/92897739-5a052a80-f415-11ea-8693-67071f7bccaf.png">

**Comment by skinny85** [comment]
Can you show the entire event log there?

This happens when your deployment fails for some reason.
