### ISSUE TITLE
[aws-eks] kubectl-handler apply race condition causes failure

### ISSUE THREAD

**Issue by jessecollier** [aws/aws-cdk#10295]
Due to [this bug](https://github.com/kubernetes/kubernetes/issues/44165) in the kubectl cli, if there are multiple manifests that apply to the same type of object (ie namespace) the custom resource will fail, causing a rollback.

As a developer, I expect `kubectl apply` to be idempotent. Because of this, I might have a module that ensures a namespace exists using the `KubernetesManifest` construct. 

When I extend this to be used in multiple instances, a race condition for creating this namespace is possible in cloudformation.

### Reproduction Steps

``` 
const namespaceManifest = {
    apiVersion: 'v1',
    kind: 'Namespace',
    metadata: {
        name: 'example'
    }
}

new KubernetesManifest(this, `manifest-example-1`, { cluster: cluster, namespaceManifest });
new KubernetesManifest(this, `manifest-example-2`, { cluster: cluster, namespaceManifest });
```
This will create to non-dependent resources that cloudformation can create in parallel. Making it possible for a race condition.

### What did you expect to happen?

I expect both to pass, and the operation to be idempotent.

### What actually happened?

```
[INFO]	2020-09-10T20:25:09.466Z	c2e11419-68fe-4d14-8a04-9919ea133efa	Running command: ['kubectl', 'apply', '--kubeconfig', '/tmp/kubeconfig', '-f', '/tmp/manifest.yaml']
[ERROR] Exception: b'Error from server (AlreadyExists): error when creating "/tmp/manifest.yaml": namespaces "main" already exists\n'
Traceback (most recent call last):
  File "/var/task/index.py", line 14, in handler
    return apply_handler(event, context)
  File "/var/task/apply/__init__.py", line 43, in apply_handler
    kubectl('apply', manifest_file)
  File "/var/task/apply/__init__.py", line 65, in kubectl
    raise Exception(output)
```

### Environment

  - **CLI Version      :** 1.62.0
  - **Framework Version:**
  - **Node.js Version:** v12.18.2
  - **OS               :** OSX 10.15.5
  - **Language (Version):** Typescript

### Other

It would be nice to retry on this specific type of exception (`AlreadyExists`) as we expect `kubectl apply` to be idempotent on any number of retries.

--- 

This is :bug: Bug Report

**Comment by jessecollier** [comment]
As a workaround for my specific use case, I'm using a global singleton pattern

```
function getOrCreateNamespace(cluster: Cluster, namespace: string): KubernetesManifest {
    const stack = Stack.of(cluster);
    const uniqueid = `manifest-namespace-${namespace}`;
    const namespaceManifest = {
        apiVersion: 'v1',
        kind: 'Namespace',
        metadata: {
            name: namespace
        }
    }
    return stack.node.tryFindChild(uniqueid) as KubernetesManifest ?? cluster.addManifest(uniqueid, namespaceManifest);
}
```

**Comment by iliapolo** [comment]
@jessecollier Can I ask how do you think the CDK can mitigate this issue? Like you mentioned, seems more of a `kubectl apply` issue not being idempotent to some resources (i.e namespaces). P.S I know that namespaces are somewhat of a special resource in k8s, as there is a hard requirement on their existence prior to applying any other resources in them. Have you seen this happen with other resources as well?

The workaround you suggested seems fairly reasonable. Though may I ask why are you instantiating two instances of the same manifest? You could also model you constructs in such a way that they accept a `Namespace` construct if needed. Something like:

```typescript

// create just one namespace instance at the beginning of your program
const namespace = new KubernetesManifest(...);

// pass the namespace to all other resources
const resource = new MyResource(this, 'Resource', { namespace });

// declare a dependency so that the namespace is created first
resource.node.addDependency(namespace)

```

**Comment by jessecollier** [comment]
Because this operation is expected to be idempotent, and this is a none _client_ side issue, a simple solution would to retry on this specific error Similar to how a retry is done on timeouts.

I'm still learning how to develop with CDK, but my approach was creating a re-usable construct. In this construct it would create things like the namespace, Service Account and other resources necessary for my use case. A singleton pattern makes since in my use case because my construct can be called anywhere and N times without having to manage a dependency.

**Comment by iliapolo** [comment]
> A singleton pattern makes since in my use case because my construct can be called anywhere and N times without having to manage a dependency.

I understand you'd like your construct to be self-contained and create its own namespace if needed, and indeed the singleton pattern fits nicely here. 

I think there is a good story here around providing explicit namespace support, which is definitely a little different than other k8s resources. But i'm not sure how or if we should be handling the `AlreadyExists` error in a generic way yet, ignoring it might cause some unexpected behavior. We will take this under consideration. 

Thanks for reporting!

**Comment by iliapolo** [comment]
Closing this issue as I don't think there is a safe and systematic way for CDK to mitigate non-idempotent operations rooted in the behavior of `kubectl`.

The specific issue described here can be solved by utilizing the singleton pattern as mentioned.
