### ISSUE TITLE
[aws-sso] add support for aws sso

### ISSUE THREAD

**Issue by Robertjan123** [aws/aws-cdk#10304]
Some api have been released for AWS SSO and there is now CloudFormation support for two types of resource: Assignment and PermissionSet. It would be great if CDK would support this. 

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sso-assignment.html

### Use Case

We are deploying the landing zone using CDK and AWS SSO is part of the landing zone. We want to allow the users to access the different accounts by using AWS SSO. 

### Proposed Solution

At least create support for the two lower level CloudFormation constructs. For now the APIs only allow you to assign a permission set with a principal to an AWS Account. This is enough for our use case. 

---

This is a :rocket: Feature Request

**Comment by SomayaB** [comment]
Hi @Robertjan123, all Cloudformation resources get automatically generated and added to the CDK shortly after being made available in Cloudformation. I just looked at [changes coming to the next CDK release](https://github.com/aws/aws-cdk/blob/c4f4c6ed724415acbaf99235c10bae6cfc072be4/packages/%40aws-cdk/cfnspec/CHANGELOG.md) and it looks like both `AWS::SSO::Assignment` and `AWS::SSO::PermissionSet` will be added!
