### ISSUE TITLE
[Certificate Manager] Better representation of pending DNS validation from ACM  

### ISSUE THREAD

**Issue by SathyaBhat** [aws/aws-cdk#10307]
### The Question

I have some CDK code requests for a new certificate from ACM using DNS validation in Python

```
cert = acm.Certificate(self, 
                        "Cert", 
                        domain_name=bucket_name,
                        validation=acm.CertificateValidation.from_dns()
                        )
```

When I deploy this, CDK reports the cert creation as "Creating"

```
| CREATE_IN_PROGRESS   | AWS::CertificateManager::Certificate | Cert
```

even though ACM status is pending DNS Validation. I was wondering why it was taking so long, only to follow from Cloudformation to ACM to see its actually pending DNS validation from me. 

I'm wondering if this can be reported better
 
### Environment

I don't believe this is version dependent but can provide if it matters

**Comment by njlynch** [comment]
Hi @SathyaBhat,

That `CREATE_IN_PROGRESS` status is actually the underlying CloudFormation status of the Certificate as a resource. I understand this isn't as useful as having the service-specific (in this case, CertificateManager-specific) messaging, but coding our CLI reporting to each service and its status would be a significant overhead.

In lieu of better reporting during the deployment, we try to make this clear in the service's [README](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-certificatemanager/README.md#dns-validation): 

> If Route 53 is not your DNS provider, the DNS records must be added manually and the stack will not complete creating until the records are added.

```ts
new acm.Certificate(this, 'Certificate', {
  domainName: 'hello.example.com',
  validation: acm.CertificateValidation.fromDns(), // Records must be added manually
});
```

**Comment by SathyaBhat** [comment]
Hi @njlynch thanks - that makes sense. I didn't see the readme for ACM module, so missed that
