### ISSUE TITLE
[core] CfnOptions does not exist in resource type cdk.CfnStack

### ISSUE THREAD

**Issue by r00t-ankit** [aws/aws-cdk#10317]
`CfnOptions` does not exist in resource type `cdk.CfnStack`.

### Reproduction Steps
```ts
const resource = new SampleStack(app)
resource.node.defaultChild.cfnOptions.condition = condition //any condition
```
### What did you expect to happen?
Expected to apply a condition to resource type Stack

Create nested stacks based on condition

### What actually happened?

```
TypeError: Cannot read property 'cfnOptions' of undefined
```

### Environment

  - **CLI Version      :**
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):** 

### Other

--- 

This is :bug: Bug Report

**Comment by SomayaB** [comment]
Hi @r00t-ankit, can you provide a code sample of your stack. Also, can you try `resource.cfnOptions.condition` instead?
