### ISSUE TITLE
[@aws-cdk/aws-s3] More than one CORS origin not applied correctly 

### ISSUE THREAD

**Issue by nonken** [aws/aws-cdk#10310]
The `allowedOrigins` property passed into an `addCorsRule` call is not behaving as expected.

The following code:

```
const bucket = new Bucket(/*...*/);
bucket.addCorsRule({
  allowedMethods: [HttpMethods.GET, HttpMethods.HEAD],
  allowedOrigins: [`https://${domainName}`, `https://www.${domainName}`] // Note, two origins are passed in accordance to the docs.
});
```

Generates the following S3 config:

```
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<CORSRule>
    <AllowedOrigin>https://baseline.dev</AllowedOrigin>
    <AllowedOrigin>https://www.baseline.dev</AllowedOrigin>
    <AllowedMethod>GET</AllowedMethod>
    <AllowedMethod>HEAD</AllowedMethod>
</CORSRule>
</CORSConfiguration>
```

When requesting the object, only the first origin is passed in the header:

```
access-control-allow-origin: https://baseline.dev
```

According to the [docs](https://docs.aws.amazon.com/AmazonS3/latest/dev/cors.html), there should one CORSRule per origin. So the CDK should generate two rules **or** only allow a string, not an array of origins. 

Separating into two `addCoresRule` calls fixes the underlying issue in the meantime.

### Environment

  - **CLI Version      : v1.62.0**
  - **Framework Version: v1.62.0**

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment]
This might be an issue with the underlying CFN resource because the CDK simply mirrors [it](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-cors-corsrule.html#cfn-s3-bucket-cors-corsrule-allowedorigins).

Marking in any case because it can be mitigated by CDK regardless.

**Comment by nonken** [comment]
Yeah, it would save customers debugging time if the CDK would protect against this, even if it's just in the docs.

**Comment by otaviomacedo** [comment]
Hi, @nonken 

Just to clarify one thing: when you say "only the first origin is passed in the header", does that mean that, in the request you passed a header `Origin: https://baseline.dev` and got back a response header `access-control-allow-origin: https://baseline.dev`? 

If so, that's the expected behavior. If you pass a `Origin` request header and it matches one of the CORS rules defined in the bucket, S3 will echo that origin in the `access-control-allow-origin` response header. If the origin passed in the request does not match any CORS rule, the `access-control-allow-origin` header won't be present in the response.

**Comment by nonken** [comment]
@otaviomacedo no, the issue at the time was that I had to do the following:

```
    staticAssetsProduction.addCorsRule({
      allowedMethods: [HttpMethods.GET, HttpMethods.HEAD],
      allowedOrigins: [`https://${domainName}`]
    });

    staticAssetsProduction.addCorsRule({
      allowedMethods: [HttpMethods.GET, HttpMethods.HEAD],
      allowedOrigins: [`https://${websiteHostName}`]
    });
```

Passing an array would create one Rule with two origins. The result would be that one of the two would be ignored.
Instead it should have generated:

```
<CORSRule>
    <AllowedOrigin>https://baseline.dev</AllowedOrigin>
    <AllowedMethod>GET</AllowedMethod>
    <AllowedMethod>HEAD</AllowedMethod>
</CORSRule>
<CORSRule>
    <AllowedOrigin>https://www.baseline.dev</AllowedOrigin>
    <AllowedMethod>GET</AllowedMethod>
    <AllowedMethod>HEAD</AllowedMethod>
</CORSRule>
```

**Comment by otaviomacedo** [comment]
Right. But what do you mean by "ignored"? You sent a `Origin:` header that matched one of the rules and it would not respond with `access-control-allow-origin`?

**Comment by barry-the-sender** [comment]
@otaviomacedo Correct, because you can not have two origins in one rule:

```
<AllowedOrigin>https://baseline.dev</AllowedOrigin>
<AllowedOrigin>https://www.baseline.dev</AllowedOrigin>
```

**Comment by nonken** [comment]
@otaviomacedo Correct, because you can not have two origins in one rule:

```
<AllowedOrigin>https://baseline.dev</AllowedOrigin>
<AllowedOrigin>https://www.baseline.dev</AllowedOrigin>
```

**Comment by otaviomacedo** [comment]
When I create a bucket using your example, the generated CORS configuration is, as you point out:

```json
[
    {
        "AllowedHeaders": [],
        "AllowedMethods": [
            "GET",
            "HEAD"
        ],
        "AllowedOrigins": [
            "https://baseline.dev",
            "https://www.baseline.dev"
        ],
        "ExposeHeaders": []
    }
]
```

which contains one rule with two methods and two origins. When I make HTTP GET or HEAD requests for objects in this bucket, it responds with the same `access-control-allow-origin` response header as the `Origin` request header.

**Comment by nonken** [comment]
@otaviomacedo have you tried fetching the assets with the rule from both origins? When I opened the issue, it would only work for the first origin in the array until I declared two separate rules. If this works as expected now for all origins specified, then the issue is no longer valid.

**Comment by otaviomacedo** [comment]
Yes, I did. But keep in mind that the server (S3 in this case), only controls the headers. It is up to the client to decide whether to make the actual request, based on those headers. A web browser will have this implemented correctly, but if you are using a different HTTP client, it may not be.
