### ISSUE TITLE
[apigateway] Metric Method for HttpApi

### ISSUE THREAD

**Issue by dejonghe** [aws/aws-cdk#10325]
Add the Metric method to the HttpApi object. 

Seems like most L2 objects have a method called metric, that takes a metric_name parameter, and makes it easy to build alarms for the resource. 

### Use Case

I built a config object that represents an alarm, and I loop over a dict of them to create alarms for each of my objects, I've been able to re use this on ECS, RDS, SQS, etc but have to build out the metric myself for API Gateway. 

This is what I want to work:

```
        for key, alarm in props.get('alarms').items():
            monitor = api.metric(alarm.metric_name).create_alarm(
                self, f"Alarm{alarm.metric_name}",
                evaluation_periods=alarm.eval_periods,
                threshold=alarm.threshold,
                actions_enabled=alarm.enabled,
                alarm_description=alarm.description,
                alarm_name=f"{props['ou']}-{props['env']}-api-{alarm.name}",
                comparison_operator=alarm.comparison_operator,
                datapoints_to_alarm=alarm.datapoints,
                period=alarm.period,
                statistic=alarm.statistic,
                treat_missing_data=alarm.missing
            )
            for action in alarm.actions:
                monitor.add_alarm_action(action)
```

### Proposed Solution

This is my work around:

```
        for key, alarm in props.get('alarms').items():
            metric = cloudwatch.Metric(
                metric_name=alarm.metric_name,
                namespace='AWS/ApiGateway',
                dimensions={
                    'ApiId': api.http_api_id
                }
            )
            monitor = metric.create_alarm(
                self, f"Alarm{alarm.metric_name}",
                evaluation_periods=alarm.eval_periods,
                threshold=alarm.threshold,
                actions_enabled=alarm.enabled,
                alarm_description=alarm.description,
                alarm_name=f"{props['ou']}-{props['env']}-api-{alarm.name}",
                comparison_operator=alarm.comparison_operator,
                datapoints_to_alarm=alarm.datapoints,
                period=alarm.period,
                statistic=alarm.statistic,
                treat_missing_data=alarm.missing
            )
            for action in alarm.actions:
                monitor.add_alarm_action(action)
```

### Other

Ultimately this is just a minor inconvenience and not high priority, but thought it should be tracked. 

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by cyuste** [comment]
I'm working on it. Just to clarify, this is what I'm doing:
- Add json file in `packages/@aws-cdk/cfnspec/lib/augmentations/AWS_ApiGateway_RestApi.json` with the metrics.
- The metrics are filtered by api name and the deployment stage
- Rename `packages/@aws-cdk/aws-apigateway/lib/restapi.ts` to `rest-api-base.ts` and update imports
- Add tests :)
