### ISSUE TITLE
[cdk pipelines] Artifact [Artifact_Build_Synth] exceeds max artifact size

### ISSUE THREAD

**Issue by seawatts** [aws/aws-cdk#10330]
### The Question
When creating a aws-cdk/pipeline I am running into an issue where my Artifact synth asset is too large. It looks like the limit is 256MB https://docs.aws.amazon.com/codepipeline/latest/userguide/limits.html

Is there any way we can get around this?

### Environment

  - **CDK CLI Version:** 1.62.0 (build 8c2d7fc)
  - **Module Version:** 1.62.0
  - **Node.js Version:** v14.9.0
  - **OS:** OSX
  - **Language (Version):**  TypeScript (4.0.2)

**Comment by SomayaB** [comment]
Related feature request: https://github.com/aws/aws-cdk/issues/9917

**Comment by seawatts** [comment]
Closing in lue of #9917
