### ISSUE TITLE
[cloudformation] NestedStack with shorter identifiers

### ISSUE THREAD

**Issue by goposky** [aws/aws-cdk#10332]
Shorten the long CDK generated nested stack identifiers.

### Use Case
The AWS CDK generated nested stack identifiers are horribly long and not readable. 
For example see this: https://stackoverflow.com/questions/59771185/aws-cdk-generated-resource-identifiers-are-horrible-and-not-readable-any-way-to

It's understandable that the stack identifiers need to be unique but they don't need to be this long.

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
Unlikely we'll do this. The generated template is an implementation detail and should only be looked at to debug things.
