### ISSUE TITLE
[aws-eks] Fargate cluster should support clusterId 

### ISSUE THREAD

**Issue by dodtsair** [aws/aws-cdk#10347]
EKS Fargate cluster should support clusterId.  When creating an ingress controller via the cdk an IAM Role needs to be created.  That IAM role needs a FederatedPrincipalCondition needs to use the clusterId for the StringEquals clause.  But clusterId is not directly available via the CDK.  clusterId should be made available such that IAM Role needed for the ingress controller can be created.  

### Use Case

To create an ingress controller in the cdk for a fargate cluster You need to create an IAM Role for the ingress controller to assume when it creates the ALB.  For security and functionality (I was not able to make StringLike work, not sure why) There must be a StringEquals clause see instructions here: https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/. In particular look at the section "The following CLI command sequence is equivalent to the steps the eksctl create iamserviceaccount". 

Some sample code creating the IAM Role in the CDK is as follows:
```
        const albIamPrincipal = new iam.FederatedPrincipal(
            fargateCluster.openIdConnectProvider.openIdConnectProviderArn,
            {
                StringEquals: new CfnJson(this, "FederatedPrincipalCondition", {
                    value: {
                        [`oidc.eks.${vpc.env.region}.amazonaws.com/id/${clusterId}:aud`]: "sts.amazonaws.com",
                        [`oidc.eks.${vpc.env.region}.amazonaws.com/id/${clusterId}:sub`]: "system:serviceaccount:kube-system:alb-ingress-controller"
                    }
                })
            }, "sts:AssumeRoleWithWebIdentity")
```

Notice the StringEquals clause must have the following key: 
```
[`oidc.eks.${vpc.env.region}.amazonaws.com/id/${clusterId}:aud`]
```
Everything is available as tokens from the CDK except the fargate clusterId.  I have been able to extract the clusterId using the following code:

```
        //Example URL https://oidc.eks.us-west-2.amazonaws.com/id/B01EF2EC7AC85DCEED81633BDA4ED90A
        const clusterId = Fn.select(4, Fn.split('/', fargateCluster.clusterOpenIdConnectIssuerUrl))
```

If there is a better way to do this I do not know.  But to get the ingress controller working in EKS I needed the clusterId for the EKS cluster in order to create the IAM role.  

### Proposed Solution

A simple additional property/token would be good.  Something like:

```
        const fargateCluster = new eks.FargateCluster(this, 'fargate-cluster', {
            version: eks.KubernetesVersion.V1_17,
            clusterName: 'my-cluster',
            vpc,
            mastersRole,  // Is this a wide open permission?
            coreDnsComputeType: eks.CoreDnsComputeType.FARGATE,
            defaultProfile: {
                selectors: [
                    {
                        namespace: 'default'
                    },
                    {
                        namespace: 'kube-system'
                    },
                ],
                podExecutionRole: icFargateProfile
            }
        })

        const clusterId = fargateCluster.clusterId

```

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by iliapolo** [comment]
@dodtsair Considering that the cluster id isn't directly exposed by the [API](https://docs.aws.amazon.com/eks/latest/APIReference/API_DescribeCluster.html), the way you extract the ID seems reasonable. 

We can potentially pull your solution into the Cluster construct to add some sugar and make it easier, but it would essentially be the same. I think you should feel comfortable with using this method.

**Comment by dodtsair** [comment]
@iliapolo while adding `cluster id` wouldn't necessarily increase the capability of the cdk (the solution I provided is trivial understand and to implement) My bigger concern is the lack of discoverability.  Implementing an eks + fargate + alb ingress controller on cdk was incredibly difficult.  One might argue that there is a broader problem of a lack of a good example to do the above with cdk.  A good documentation page with reference to the solution might solve more people's issues.

**Comment by iliapolo** [comment]
@dodtsair Agree that adding this would be good for discoverability. The use case you describe also sounds like a good fit to an EKS patterns module. We actually already have a request for such a module: https://github.com/aws/aws-cdk/issues/4955.

Would be great if you could drop your solution on that issue and we will think how to integrate this, first as some sort of documentation, and later as a proper pattern perhaps. 

Thanks
