### ISSUE TITLE
[aws-lambda] lambda.Function.fromFunctionArn is not returning the role, role is undefined

### ISSUE THREAD

**Issue by I2olanD** [aws/aws-cdk#10342]
lambda.Function.fromFunctionArn is not returning the role

### Reproduction Steps

```ts
const lambdaProperties = {...};

const myFn = lambda.Function.fromFunctionArn(....);

lambdaProperties.onFailure = new destinations.LambdaDestination(myFn);

new lambda.Function(scope, lambdaName, lambdaProperties);
```
### What did you expect to happen?

fromFunctionArn() returns all information needed to add a destination.

### What actually happened?

It throws following error: `No child with id:....`

### Environment
  - **CLI Version: latest**
  - **Framework Version: latest**
  - **Node.js Version:** 10.19.0
  - **OS               :**
  - **Language (Version):** [TypeScript (3.7.2)]

### Other
It seems like, that the role information is getting lost after calling fromFunctionArn().

```ts
static fromFunctionArn(scope, id, functionArn) {
  return Function.fromFunctionAttributes(scope, id, { functionArn });
}

static fromFunctionAttributes(scope, id, attrs) {
  const functionArn = attrs.functionArn;
  const functionName = extractNameFromArn(attrs.functionArn);
  const role = attrs.role;
  console.log(role); // undefined since attrs only contains functionArn
  ......
}
```

https://github.com/aws/aws-cdk/blob/ad9a70543703e8d8ebaac82001ee9a62f784bea7/packages/%40aws-cdk/aws-lambda/lib/function.ts#L362

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
Hello @I2olanD -

Currently, the CDK cannot determine the IAM role you are using based on just the function ARN. 

You will need to use `fromFunctionAttributes()` for your use case, and explicitly specify the IAM role. Most likely the IAM role is also defined outside of the CDK app, so it will also have to be imported. Your code will look something like -

```ts
const myFn = lambda.Function.fromFunctionArn(this, 'function', {
  functionArn: 'function-arn',
  role: iam.Role.fromRoleArn(this, 'role', 'role-arn'),
});
```

**Comment by alonsnir** [comment]
@nija-at 
> ```ts
> const myFn = lambda.Function.fromFunctionArn(this, 'function', {
>   functionArn: 'function-arn',
>   role: iam.Role.fromRoleArn(this, 'role', 'role-arn'),
> });
> ```
How is this possible given the api?
```
/**
   * Import a lambda function into the CDK using its ARN
   */
  public static fromFunctionArn(scope: Construct, id: string, functionArn: string): IFunction {
    return Function.fromFunctionAttributes(scope, id, { functionArn });
  }

```
