### ISSUE TITLE
[cdk] Need deploy-time refs before-hand

### ISSUE THREAD

**Issue by mainframenzo** [aws/aws-cdk#10353]
I can't wrap my head around this one. How does one keep track of a list of resources that are "deploy time"? This applies to multiple types of resources, but let's use S3 as the example:

I want to create a bunch of S3 buckets, append the bucket name in an entry to a csv file, then store that file in S3...all at once! 

```
const fs = require('fs');

import s3 = require('@aws-cdk/aws-s3');
import s3deploy = require('@aws-cdk/aws-s3-deployment');

const bucketA = new s3.Bucket(this, 'BucketA');
const bucketB = new s3.Bucket(this, 'BucketB');
const bucketStore = new s3.Bucket(this, 'BucketStore');

let csv = 'BucketName';
csv += `\n${bucketA.bucketName}`;
csv += `\n${bucketB.bucketName}`;

//this file on disk looks like "BucketName\nToken[Etc]\nToken[Etc]", which is problematic
fs.writeFileSync('/tmp/bucketStore/buckets.csv', csv);

new s3deploy.BucketDeployment(this, 'DeployBucketStore', {
  sources: [ s3deploy.Source.asset('/tmp/bucketStore') ],
  destinationBucket: bucketStore
});
```

Is this possible with the CDK or should I be doing this after a deployment and grabbing the names as Cloudformation outputs?

**Comment by SomayaB** [comment]
Hi @mainframenzo, is there a reason you need assets to process at the same time as resource creation? What is happening is "code -> synth -> deploy resources -> populate assets".
I don't think it's possible to deploy assets in between resources because cfn doesn't support assets at all and deploy is mostly cfn.
