### ISSUE TITLE
aws-s3 and aws-lambda-event-sources .Bucket Issue: Types of property 'encryptionKey' are incompatible.

### ISSUE THREAD

**Issue by joeviggiano** [aws/aws-cdk#10355]
#7827  :question: General Issue

### The Question
I'm trying to add a simple event notification for S3 to Lambda using S3EventSource from @aws-cdk/aws-lambda-event-sources and I'm receiving the following error:

Argument of type 'import("cdk-project/node_modules/@aws-cdk/aws-s3/lib/bucket").Bucket' is not assignable to parameter of type 'import("cdk-project/node_modules/@aws-cdk/aws-lambda-event-sources/node_modules/@aws-cdk/aws-s3/lib/bucket").Bucket'.
  Types of property 'encryptionKey' are incompatible.
    Type 'import("cdk-project/node_modules/@aws-cdk/aws-kms/lib/key").IKey | undefined' is not assignable to type 'import("cdk-project/node_modules/@aws-cdk/aws-lambda-event-sources/node_modules/@aws-cdk/aws-kms/lib/key").IKey | undefined'.
      Type 'import("cdk-project/node_modules/@aws-cdk/aws-kms/lib/key").IKey' is not assignable to type 'import("cdk-project/node_modules/@aws-cdk/aws-lambda-event-sources/node_modules/@aws-cdk/aws-kms/lib/key").IKey'.
        The types returned by 'addAlias(...)' are incompatible between these types.
          Type 'import("cdk-project/node_modules/@aws-cdk/aws-kms/lib/alias").Alias' is not assignable to type 'import("cdk-project/node_modules/@aws-cdk/aws-lambda-event-sources/node_modules/@aws-cdk/aws-kms/lib/alias").Alias'.
            Property 'generatePhysicalName' is protected but type 'Alias' is not a class derived from 'Alias'.

import s3 = require('@aws-cdk/aws-s3');
import s3event = require('@aws-cdk/aws-lambda-event-sources');

const sourceBucket = new s3.Bucket(this, 'source-bucket', {
      versioned: false,
      publicReadAccess: false,
      blockPublicAccess: BlockPublicAccess.BLOCK_ALL,
      encryption: BucketEncryption.S3_MANAGED,
      removalPolicy: RemovalPolicy.DESTROY
    });

   const uploadEvent = new s3event.S3EventSource(
      sourceBucket,
      { events: [s3.EventType.OBJECT_CREATED] }
    );

### Environment

  - **CDK CLI Version:** CDk 1.63.0
  - **Node.js Version:** 10.16.0
  - **OS:** MacOS
  - **Language (Version):** Typescript

**Comment by joeviggiano** [comment]
Issue caused by some CDK libraries being out of date, closing issue.

**Comment by kevinvaningen** [comment]
Updating your libraries to a newer version.  A migration from  1.115.0 to 1.121.0 solved it for me.
