### ISSUE TITLE
[ecs-patterns] Expose all created Roles for configuration

### ISSUE THREAD

**Issue by michaelfedell** [aws/aws-cdk#10352]
## :question: General Issue

If this should be filed as a feature request, I can reopen

### The Question

In short: Some resources implicitly create ("singleton") roles under the hood without allowing configuration; this blocks creation if account policies require a permission boundary etc. for IAM Roles.

Within my organization (as I understand is quite common), we have some global policies that prevent the creation of IAM Roles without a permission boundary (or specified path). Many resources in CDK allow you to explicitly pass the roles used by a resource meaning we can pre-create the role with proper configuration and then pass it in. However, several operations in CDK create IAM Roles behind the scenes without exposing that role at any point, thus preventing the use of that resource (Role fails to create due to permission/security issues).

I am currently encountering this issue while trying to use  [`ecs-patterns/ScheduledFargateTask`](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-ecs-patterns/lib/fargate/scheduled-fargate-task.ts); the role itself is being created by a call dispatched to [events-targets/utils](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-events-targets/lib/util.ts#L12). However, this same issue appears in other places throughout the library; one such example is the implicit role created when configuring S3 bucket configurations: the lambda created behind the scenes is not configurable or exposed in any way to allow specifying the role.

### Environment

  - **CDK CLI Version:** `1.60.0 (build 8e3f53a)`
  - **Module Version:** `1.63.0`
  - **Node.js Version:** `v12.14.1`
  - **OS:** all (OSX Mojave)
  - **Language (Version):** all (Python 3.7.4)

### Other information

Following is the cdk deploy output showing the trace through implicit role creation (technically tracing back to events-targets, but starting with ecs-patterns)

```
[STACK_NAME]: deploying...
[STACK_NAME]: creating CloudFormation changeset...
4:13:43 PM | CREATE_FAILED        | AWS::IAM::Role           | FargateTaskDefinitionEventsRole[HASH]
API: iam:CreateRole User: arn:aws-us-gov:sts::[ACCOUNT_ID]:assumed-role/advanceduser/[USER] is not authorized to perform: iam:CreateRole on resource: arn:aw
s-us-gov:iam::[ACCOUNT_ID]:role/[STACK_NAME]-FargateTaskDefinitionEventsRole[HASH]

	new Role (/private/var/folders/wv/gltyfn4j6f910j0cydhb2bwc0000gp/T/jsii-kernel-WyU4gb/node_modules/@aws-cdk/aws-iam/lib/role.js:44:22)
	\_ Object.singletonEventRole (/private/var/folders/wv/gltyfn4j6f910j0cydhb2bwc0000gp/T/jsii-kernel-WyU4gb/node_modules/@aws-cdk/aws-events-targets/lib/util.j
[█████████████████████████████·····························] (5/10)

4:13:43 PM | CREATE_FAILED        | AWS::IAM::Role           | FargateTaskDefinition/EventsRole
API: iam:CreateRole User: arn:aws-us-gov:sts:::[ACCOUNT_ID]:assumed-role/advanceduser/[USER] is not authorized to perform: iam:CreateRole on resource: arn:aw
s-us-gov:iam::[ACCOUNT_ID]:role/[STACK_NAME]-FargateTaskDefinitionEventsRole[HASH]

 ❌  [STACK_NAME] failed: Error: The stack named [STACK_NAME] failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE
    at Object.waitForStackDeploy (/usr/local/lib/node_modules/aws-cdk/lib/api/util/cloudformation.ts:292:11)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at Object.deployStack (/usr/local/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:274:26)
    at CdkToolkit.deploy (/usr/local/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:181:24)
    at main (/usr/local/lib/node_modules/aws-cdk/bin/cdk.ts:268:16)
    at initCommandLine (/usr/local/lib/node_modules/aws-cdk/bin/cdk.ts:188:9)
The stack named [STACK_NAME] failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE
```

**Comment by michaelfedell** [comment]
It looks like this could be resolved (for `ecs_patterns.ScheduledFargateTask` at least), by accepting an `eventRole` in the constructor and passing that through to the protected [`addTaskDefinitionToTarget` method](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-ecs-patterns/lib/base/scheduled-task-base.ts#L145) since `events-targets.EcsTask` already [accepts a role prop](https://github.com/aws/aws-cdk/blob/857acbbb7f26feecca938dc881add57fe5cae7e4/packages/%40aws-cdk/aws-events-targets/lib/ecs-task.ts#L108)

**Comment by michaelfedell** [comment]
I haven't yet had time to build a dev env for testing or anything, but opened a [WIP] PR (#10354) to try and better express the above suggestion - sorry if opening that [WIP] PR was bad form

**Comment by callado4** [comment]
Can this feature be re-opened and actually implemented?
