### ISSUE TITLE
Assign AZs to a VPC/Subnet

### ISSUE THREAD

**Issue by moofish32** [aws/aws-cdk#1037]
Separating from: https://github.com/awslabs/aws-cdk/issues/996#issuecomment-432400689

As a VPC designer I would like to be able to assign a specific subset of availability zones to a VPC. This is specifically helpful in us-east-1.

**Comment by eladb** [comment]
Can we add a bit of context/motivation here? I.e why would you want to do that?

**Comment by rix0rrr** [comment]
Two reasons I can think of:

1. There is a particular AZ in us-east-1 which does not have all the features that the other AZs have. For example, it is not possible to start EKS clusters there, and there's probably more.
2. If you're creating multiple VPCs in the same account, you might want to spread out your VPCs over the AZs like `(us-east-1a, b, c), (d, e, f)`, as opposed to not doing this which would lead to the VPCs spreading over `(us-east-1a, b, c), (a, b, c)`

**Comment by rix0rrr** [comment]
This is news to me, but important when implementing this ticket:

* The logical -> physical AZ mapping is exposed: https://docs.aws.amazon.com/ram/latest/userguide/working-with-az-ids.html
* In "newer" regions AZs are no longer randomly mapped for each account, so we might want to do randomization at the CDK level.

**Comment by rob-gonz** [comment]
For additional Context/Motivation:

- For some QA environments I only want 1 instance inside my ASG and I do not want this ASG in 6 AZ's increasing my cost 6x.

- Even for production, I don't need to be in every AZ.  I only want to be in 1, 2, or 3 for some applications that are only for internal purposes.

**Comment by rix0rrr** [comment]
@rob-gonz, I think your issue might be solved by https://github.com/awslabs/aws-cdk/pull/1543, unless you want more fine-grained control over placement

**Comment by rix0rrr** [comment]
I'm confused on the ASG requirement.

You can limit the number of AZs in a VPC using the `maxAZs` property (set it to 1 if you want a cheap VPC).

ASGs will spread over all AZs in the VPC, but you can still create 1 instance even in a VPC with 3 AZs (by setting `maxCapacity` to `1`), so they scale independently.

**Comment by rob-gonz** [comment]
I must have missed the existence of the `maxAZs` property.

>...you can still create 1 instance even in a VPC with 3 AZs (by setting maxCapacity to 1),

It didn't click for me that `maxCapacity` was across all AZ's.  Somehow I had it stuck in my head that it was per AZ.

Thanks for taking the time to point the above out.

**Comment by eladb** [comment]
> It didn't click for me that maxCapacity was across all AZ's. Somehow I had it stuck in my head that it was per AZ.

Probably worth clarifying inn the docs

**Comment by SomayaB** [comment]
Information on MaxAZs is [here](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ec2.Vpc.html#construct-props). Closing issue.
