### ISSUE TITLE
[ecr] Amazon ECR with KMS support

### ISSUE THREAD

**Issue by pahud** [aws/aws-cdk#10379]
https://aws.amazon.com/tw/about-aws/whats-new/2020/07/ecr-supports-encryption-images-aws-kms-keys/

### Use Case

ECR repo with KMS encryption

### Proposed Solution

As it's not yet supported in [cfn](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecr-repository.html), we probably can use custom-resource to create a construct property for it.

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by lony** [comment]
It's now supported by CloudFormation and would be nice if added as well. https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecr-repository.html#cfn-ecr-repository-encryptionconfiguration

**Comment by udondan** [comment]
This is available now since 1.143.0 via https://github.com/aws/aws-cdk/pull/16966

**Comment by udondan** [comment]
Ping @pahud ... uhm... @rix0rrr maybe? This can be closed.

**Comment by pahud** [comment]
@udondan  Thank you!
