### ISSUE TITLE
[aws-ec2] Add Latest AMD HPC Class C6G to InstanceClass ENUM

### ISSUE THREAD

**Issue by JLosinski** [aws/aws-cdk#10372]
InstanceType.of(InstanceClass) ENUM does not support C6G family. https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-ec2/lib/instance-types.ts. 

### Use Case

Utilizing ENUM as best practice rather than string literal to define EC2 instance type in CDK stack.

### Proposed Solution

Add C6G to ENUM - InstanceClass.COMPUTE6_GRAVITRON

`COMPUTE6_GRAVITRON = 'c6g',`

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rrhodes** [comment]
Hello, I'm looking into this request now and should have a PR open shortly.

**Comment by rrhodes** [comment]
After some minor complications - still learning the ropes - there's a PR open for review on this issue. :)
