### ISSUE TITLE
[cli] IAM Statement Changes not compared with existing one (new one created) 

### ISSUE THREAD

**Issue by speedfl** [aws/aws-cdk#10382]
CDK does not take into account existing IAM policies.

### Reproduction Steps

I will put `<account>` to replace account number

Create a role called: **myProduct-group-LambdaSQSRole** with inline policy called **myProduct-group-LambdaSQSRoleInlinePolicy**

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "sqs:ReceiveMessage",
                "sqs:DeleteMessage",
                "sqs:GetQueueAttributes",
                "sqs:ChangeMessageVisibility",
                "sqs:GetQueueUrl"
            ],
            "Resource": "arn:aws:sqs:*:<account>:myProduct-group-*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "logs:CreateLogGroup"
            ],
            "Resource": [
                "arn:aws:logs:*:<account>:*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "logs:CreateLogStream",
                "logs:PutLogEvents"
            ],
            "Resource": [
                "arn:aws:logs:*:<account>:log-group:/aws/lambda/myProduct-group-*:*"
            ]
        }
    ]
}
```

With CDK we will then:

- Create a queue
- Create a Lambda function with eventSource from the queue + Iam role retrieved

```
 // retrieve IAM roles
const myIamRole = iam.Role.fromRoleArn(this,
    `myProduct-group-LambdaSQSRole`,
    `arn:aws:iam::<account>:role/myProduct-group-LambdaSQSRole`);

const myQueue = new sqs.Queue(this,
    `myProduct-group-subgroup-queueOne`,
    {
    queueName: `myProduct-group-subgroup-queueOne`,
    });

// create call lambda function
const myLambda = new lambda.Function(this,
    `myProduct-group-subgroup-handler`, {
    functionName: `myProduct-group-subgroup-handler`,
    code: new lambda.AssetCode('assets'),
    handler: 'lambda.handler',
    runtime: lambda.Runtime.NODEJS_12_X,
    role: myIamRole,
});

myLambda.addEventSource(new awsLambdaEventSource.SqsEventSource(myQueue));
``` 

In assets put a simple **lambda.js**:

```
exports.handler = function (event, context) {
	console.log("Hello world")
};
```

Run `cdk deploy`

### What did you expect to happen?

Cdk is not supposed to mention IAM Statement Changes as my inline policy already matches. 

### What actually happened?

I have IAM statement changes. If I accept them it add in my IAM role an inline policy:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "sqs:ReceiveMessage",
                "sqs:DeleteMessage",
                "sqs:GetQueueAttributes",
                "sqs:ChangeMessageVisibility",
                "sqs:GetQueueUrl"
            ],
            "Resource": "arn:aws:sqs:*:<account>:myProduct-group-subgroup-queueOne"
        }
    ]
}
```

As we can see it is matching my existing policy.

### Environment

  - **CLI Version      :** tested on 1.57.0 and 1.63.0
  - **Framework Version:** 1.63.0
  - **Node.js Version:** 12.15.0
  - **OS               :** Ubuntu 18.04
  - **Language (Version):** TS

### Other

In case it is too complicated to put in place it could be a good solution to have a way to ignore the IAM Statement changes

Like we have `--require-approval` we could have `--ignore-iam-statement-changes`. 

In case this option is sent a warning could be prompted saying:

```
You ignored following IAM Statement Changes
...
Put changes here
...
Your stack may be broken. Please ensure all the IAM permissions are set correctly
```

NOTE: I even tested with full arn (wildcard on the region) and it seems that issue is the same

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
Try `fromRoleArn(...., { mutable: false })`

https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-iam.FromRoleArnOptions.html

**Comment by speedfl** [comment]
Thanks a lot it worked! I close the issue
