### ISSUE TITLE
[aws-eks] Replacement of KubernetesManifest resources results in a deletion, without creation 

### ISSUE THREAD

**Issue by iliapolo** [aws/aws-cdk#10397]
Resources that are deployed as Kubernetes manifests cannot undergo replacement changes. Specifically, since those resources are always eventually a `cdk.CustomResource`, the replacement happens only when the logical ID or the service token changes.

### Reproduction Steps

1. Create a service account:

```typescript
const cluster = eks.Cluster(this, 'Cluster', {
  version: eks.KubernetesVersion.V1_17,
})

cluster.addServiceAccount(this, 'ServiceAccount', {
  name: 'svcaccount'
})
```

2. Deploy the stack.

3. Change the service account ID, but keep the name.

```typescript
cluster.addServiceAccount(this, 'ServiceAccountChanged', {
  name: 'svcaccount'
})
```

4. Deploy again

### What did you expect to happen?

That the deployment will not delete the service account. At the very minimum, the replacement should have failed on a name conflict just like it would with other CFN resources.

### What actually happened?

The service account was simply deleted and never recreated

### Environment

  - **CLI Version      :ALL**
  - **Framework Version:ALL**
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):** 

### Other

See https://github.com/aws/aws-cdk/issues/10388

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment]
Consider using [`kubectl replace`](https://jamesdefabia.github.io/docs/user-guide/kubectl/kubectl_replace/) instead of `kubectl aplpy`

**Comment by iliapolo** [comment]
Actually, `replace` probably won't solve this. We need to somehow fail we try to create an existing resource, simulating CFN behavior. This will prevent the failed state the cluster can wind up in.

**Comment by eladb** [comment]
It appears we need to use `kubectl create --save-config` for CREATE and then `apply` for UPDATE
