### ISSUE TITLE
[cli] cdk deploy using newStyleStackSynthesis cannot handle non-ASCII characters in username

### ISSUE THREAD

**Issue by pergardebrink** [aws/aws-cdk#10401]
### Steps to reproduce
* Create/use a windows user with a username containing å (might also need to set computer to swedish locale or similar)
* Create a CDK project using newStyleStackSynthesis: true
* Run `cdk deploy <stackname>`

### What did you expect to happen?
Stack to be deployed

### What actually happened?
An error is reported:
```
Could not assume role in target account (did you bootstrap the environment with the right '--trust's?): 1 validation error detected: Value 'aws-cdk-PerGårdebrink' at 'roleSessionName' failed to satisfy constraint: Member must satisfy regular expression pattern: [\w+=,.@-]*
```

### Environment

  - **CLI Version      : 1.61-1.63 (at least)**
  - **Framework Version: .NET Core 3.1**
  - **Node.js Version: 12.16.1**
  - **OS               : Windows 10**
  - **Language (Version):**

### Other
This seems like it could be related to the same problem I had before: https://github.com/aws/aws-cdk/issues/7456

I tried to impersonate another local windows user without å in the username and then it worked perfectly with the same AWS credentials

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
😳 oops
