### ISSUE TITLE
Suggestion: Implement warning for aws stack version mismatch

### ISSUE THREAD

**Issue by karlwesterman** [aws/aws-cdk#10407]
### The Question

Everywhere I see people having issues because the versions of their AWS stack aren't matching. It would probably save a lot of hassle for a lot of people new to this if we could get a warning about this.

### Environment

  - **CDK CLI Version:** all
  - **Module Version:** all
  - **Node.js Version:** all
  - **OS:** all
  - **Language:** all

**Comment by SomayaB** [comment]
@karlwesterman we are actively working on a solution to this issue. See https://github.com/aws/aws-cdk/tree/master/packages/monocdk-experiment
