### ISSUE TITLE
[aws-iam] How to produce "all principals" principal? "AWS": "*"

### ISSUE THREAD

**Issue by heikkis** [aws/aws-cdk#10403]
## :question: General Issue

Eg.  https://docs.aws.amazon.com/kms/latest/developerguide/services-dynamodb.html#dynamodb-authz guide says that principal should be in first statement like this:

Principal: {
  "AWS": "*"
}

If I use AnyPrincipal class, the Key policy statement principal looks like this:

Principal: "*"

This is not correct and for example Key resource policy editor gives error and does not allow to save it in that format even Cloudformation is able to create key policy to look like this.

### The Question
How to product Key Policy with correct all principals clause?

For other resources I have replaced the policy with Cfn node override. However, the key's resource policy is more complex and  I would to need to do all other rules also manually which is not nice.

### Environment

  - **CDK CLI Version:** 1.63.0
  - **Module Version:** 1.63.0
  - **Node.js Version:** 12.x
  - **OS:** Mac latest
  - **Language (Version):** Typescript 3.8.3

**Comment by rix0rrr** [comment]
They are equivalent. See the section **Anonymous users (public)** on this page: https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_principal.html

If the KMS service or console are giving your problems with this, please take this bug report to them.

To work around it in the mean time, you can use an `ArnPrincipal` with an ARN of `*`.

**Comment by heikkis** [comment]
I tried also ArnPrincipal with "*" but it also product finally Principal: "*" to CF.

The doc is clear, it should work so the problem is considering more KMS console than CDK.

**Comment by abinash453** [comment]
StarPrincipal can be used.
https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_iam/StarPrincipal.html

**Comment by andrmoel** [comment]
```
import * as iam from 'aws-cdk-lib/aws-iam';

principals: [
    new iam.AnyPrincipal(),
],
```
