### ISSUE TITLE
[Contributing] npm run build: Checking javac version... Found javac version javac 15. Install javac >= 1.8.0 

### ISSUE THREAD

**Issue by Wenzil** [aws/aws-cdk#10416]
Building `aws-cdk` itself fails at the javac version check step.

### Reproduction Steps

```sh
git clone git@github.com:aws/aws-cdk.git
cd aws-cdk
npm run build
```

### What did you expect to happen?

I expected the project to build successfully.

### What actually happened?

The build fails with the following logs:

```
npm run build

> aws-cdk@0.0.0 build /Users/<omitted>/repos/aws/aws-cdk
> ./build.sh

=============================================================================================
installing...
yarn install v1.22.5
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 4.59s.
git: 'secrets' is not a git command. See 'git --help'.
git-secrets scan ok
Checking if node is installed... Ok
Checking node version... Ok
Checking if yarn is installed... Ok
Checking yarn version... Ok
Checking if javac is installed... Ok
Checking javac version... Found javac version javac 15. Install javac >= 1.8.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! aws-cdk@0.0.0 build: `./build.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the aws-cdk@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/<omitted>/.npm/_logs/2020-09-17T16_50_26_331Z-debug.log
```

### Environment

  - **CLI Version      :** 1.63.0
  - **Framework Version:** 1.63.0
  - **Node.js Version:** v14.11.0 
  - **OS               :** macOS Catalina
  - **Language (Version):** 3.9.7 

### Other

I manually installed OpenJDK 15 on macOS Catalina by downloading the `tar.gz` archive from the [official download page](https://jdk.java.net/15/) and copied its contents to `/Library/Java/JavaVirtualMachines/` as described in this [StackOverflow answer](https://stackoverflow.com/a/52524114).

`javac -version` output:

```
javac 15
```

--- 

This is :bug: Bug Report

**Comment by ericzbeard** [comment]
Fixed by #11087
