### ISSUE TITLE
[aws-efs] Add backupPolicy construct prop to FileSystem

### ISSUE THREAD

**Issue by 1davidmichael** [aws/aws-cdk#10414]
[BackupPolicy](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-efs-filesystem.html#cfn-efs-filesystem-backuppolicy) is now supported by CloudFormation and the raw CfnFileSystem construct. It would be nice to use this on the higher level construct for EFS.

### Use Case

I would prefer to add this directly to the resource props, rather than enabling it via an override.

### Proposed Solution

Example override that is confirmed working (in python):

```python

        filesystem = efs.FileSystem(
            self,
            "SharedFilesystem",
            vpc=vpc,
            encrypted=True,
            removal_policy=core.RemovalPolicy.DESTROY,
        )

        # Enable EFS Auto Backups, currently not supported by EFS CDK Construct
        # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-efs-filesystem.html#cfn-efs-filesystem-backuppolicy
        cfn_efs = filesystem.node.default_child
        cfn_efs.add_property_override("BackupPolicy.Status", "ENABLED")
```

* [X] :wave: I may be able to implement this feature request

**Comment by shivlaks** [comment]
@1davidmichael thanks for logging the feature request! sounds like a good idea to expose this property and implement it into our L2. Let me know if you need a hand with getting started in implementing it!
