### ISSUE TITLE
[ecs] Add support for the environmentFiles option in ContainerDefinition

### ISSUE THREAD

**Issue by mmattax** [aws/aws-cdk#10433]
Right now `environment` is supported, but we'd like to add environment variables in bulk using the `environmentFiles` option as described here: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/taskdef-envfiles.html

### Use Case

We'd like to store our `.env` files for a node app in a single place (S3) to avoid drift, the files are quite large and maintaining each variable with `environment` isn't feasible.

### Proposed Solution

Support the [`environmentFiles` field](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-containerdefinitions.html#cfn-ecs-taskdefinition-containerdefinition-environmentfiles)

* [x] :wave: I may be able to implement this feature request

---

This is a :rocket: Feature Request

**Comment by rrhodes** [comment]
Hello @mmattax, I'm working on this feature request now and hope to have something open for review shortly.

**Comment by mmattax** [comment]
@rrhodes Awesome! Thought I'd have time to implement this, but have been swamped. 

Happy to test!

**Comment by rrhodes** [comment]
@mmattax, no problem, happens to us all! This gives me an opportunity to learn about another package, so this request is welcome. :)

**Comment by adminy** [comment]
@SoManyHs I'm getting error `Create TaskDefinition: An invalid environment file extension was used. Specify a valid .env file and try again.`.

the code is literally:
```javascript
		environmentFiles: [
			ecs.EnvironmentFile.fromAsset('.env')
		]
```

**Comment by tommyvca** [comment]
This issues is still exist and can be reproduced.
