### ISSUE TITLE
[aws-apigatewayv2] AuthorizerPayloadFormatVersion is not in CfnAuthorizerProps

### ISSUE THREAD

**Issue by jswalton** [aws/aws-cdk#10431]
AuthorizerPayloadFormatVersion is required for an HTTP API Lambda authorizer, but is not in CfnAuthorizerProps. 

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigatewayv2-authorizer.html#cfn-apigatewayv2-authorizer-authorizerpayloadformatversion

https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-apigatewayv2.CfnAuthorizerProps.html

### Reproduction Steps

Create a CfnAuthorizer with CfnAuthorizerProps:

```
    const httpAuthorizer = new apigwV2.CfnAuthorizer(this, `http-lambda-authorizer`, {
      apiId: httpAPI.ref,
      authorizerType: "REQUEST",
      authorizerUri: httpAuthorizerIntegration.integrationUri,
      identitySource: ['$request.querystring.access_token'],
      name: "http-rest-authorizer",
      authorizerCredentialsArn: role.roleArn
    })
```

`npm run build`
`cdk synth`
`cdk deploy`

### What did you expect to happen?

I would expect that CfnAuthorizerProps has a property for `AuthorizerPayloadFormatVersion` and that a Lambda Authorizer is created for my Api Gateway HTTP Api when deploying. 

### What actually happened?

CfnAuthorizerProps contains no `AuthorizerPayloadFormatVersion` and cdk fails to deploy. 

AWS CDK fails to create a Lambda Authorizer for an Api Gateway HTTP API
```
9:22:31 AM | CREATE_FAILED        | AWS::ApiGatewayV2::Authorizer  | http-lambda-authorizer
AuthorizerPayloadFormatVersion is a required parameter for REQUEST authorizer (Service: AmazonApiGatewayV2; Status Code: 400; Error Code: BadRequ
estException;
```

### Environment

  - **CLI Version      :1.63.0 (build 7a68125)**
  - **Framework Version: 1.63.0**
  - **Node.js Version: v12.12.0** 
  - **OS               : macOS Mojave Version 10.14.6 (18G6020)**
  - **Language (Version): TypeScript 3.9.7**

### Other
Workaround: Use a raw override to add the property

```   
httpAuthorizer.addPropertyOverride('AuthorizerPayloadFormatVersion', '2.0');
```

https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html#cfn_layer_raw

I wasn't sure if this should have been a feature request or a bug, so my apologies ahead of time. 

Thanks!

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
This was introduced in somewhere between CloudFormation spec versions [16.3.0 to 18.3.0](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/cfnspec/CHANGELOG.md#cloudformation-resource-specification-v1830).

We had some trouble for the past few weeks importing the latest CF spec, and have finally completed it. This should be available in the next release of the CDK.

**Comment by jswalton** [comment]
@nija-at cheers! Thanks for the response.

**Comment by armando25723** [comment]
Is there an update for this issue? Im able to deploy but the authorizer is created with Payload format version: 1.0. I have to manually change it in the console because there is not a prop payloadFormatVersion in @aws-cdk/aws-apigatewayv2-authorizers.HttpLambdaAuthorizer.

**Comment by rchandnani0615** [comment]
> 

I am looking for this attribute payloadFormatVersion
