### ISSUE TITLE
[@aws-cdk/aws-cloudfront] Creation fails when using ARN for SSL Certificate from SSM Parameter

### ISSUE THREAD

**Issue by justindra** [aws/aws-cdk#10446]
Setting the `acmCertRef` of a `CloudFrontWebDistribution` using an ARN that is saved as a `StringParameter` is failing but hardcoding the same ARN works fine.

### Reproduction Steps

```ts
export default class StaticSiteStack extends Stack {
  constructor(
    scope: App,
    id: string,
    props?: StaticSiteStackProps
  ) {
    super(scope, id, props);
    // ------> Get the SSL Certificate ARN
    const sslCertificateArn = StringParameter.valueFromLookup(this, '/ssl-certs/global')

    // Create the bucket
    const bucket = new Bucket(this, 'StaticSiteBucket');

    // Create the CloudFront OAI
    const oai = new OriginAccessIdentity(this, 'OAI', {
      comment: `OAI for ${hostingDomainName} bucket`,
    });

    // Create and attach the access policy to the bucket only allowing
    // the CloudFront OAI to access it.
    const policy = new PolicyStatement();
    policy.addActions('s3:GetBucket*');
    policy.addActions('s3:GetObject*');
    policy.addActions('s3:List*');
    policy.addResources(bucket.bucketArn, `${bucket.bucketArn}/$`);
    policy.addCanonicalUserPrincipal(
      oai.cloudFrontOriginAccessIdentityS3CanonicalUserId
    );

    bucket.addToResourcePolicy(policy);

    const distribution = new CloudFrontWebDistribution(
      this,
      'StaticSiteDistribution',
      {
        originConfigs: [
          {
            s3OriginSource: {
              s3BucketSource: bucket,
              originAccessIdentity: oai,
            },
            behaviors: [{ isDefaultBehavior: true }],
          },
        ],
        aliasConfiguration: {
         // -----> If this was set to be just a hardcoded version of the ARN it seems to work
          acmCertRef: sslCertificateArn,
          names: [hostingDomainName],
        },
      }
    );
}
```

### What did you expect to happen?

The Cloudfront Distribution should succeed.

### What actually happened?

```
The specified SSL certificate doesn't exist, isn't in us-east-1 region, isn't valid, or doesn't include a valid certificate chain
```

### Environment

  - **CLI Version      : 1.61.0**
  - **Framework Version: 1.61.0**
  - **Node.js Version: 12 .16.1** 
  - **OS               : Ubuntu 18**
  - **Language (Version): TypeScript** 

### Other

--- 

This is :bug: Bug Report

**Comment by njlynch** [comment]
Thanks for the bug report!

Can you provide me with a bit more information to help diagnose the problem?
* Is this stack, the SSM parameter, and the ACM certificate all in the us-east-1 region?
* Are there any warnings output on synthesis?
* Can you share the generated CloudFormation (YAML/JSON) for the `ViewerCertificate` block of the distribution?

**Comment by justindra** [comment]
* The Stack and the SSM parameter is in the `us-west-2` region (or any other region eventually). The ACM Certificate is in the `us-east-1` region as that's what's required for CloudFront.
* No warnings on the synthesis
* CloudFormation output below

```jsonc
// When using `Fn.import`
 "ViewerCertificate": {
    "AcmCertificateArn": {
      "Fn::ImportValue": "SSLGlobalCertificate"
    },
    "SslSupportMethod": "sni-only"
  }
```

```jsonc
// when hardcoded (not the ideal situation) or SSM Parameter
 "ViewerCertificate": {
    "AcmCertificateArn": "arn:aws:acm:us-east-1:[account-id-here]:certificate/[the-id]",
    "SslSupportMethod": "sni-only"
  }
```

**Comment by njlynch** [comment]
@justindra ,

I definitely think that newline in your parameter is the culprit. I was able to reproduce the same thing by inserting a newline into a SSM parameter.

If you've triple-checked the parameter value doesn't have a newline (anymore), is it possible the CDK context still has the cached value? Check if you have a `cdk.context.json` file, and if the value in that file has a newline (or not). If it does, just delete the file to have it re-generated with the updated value.

**Comment by justindra** [comment]
@njlynch Cool! Yea, removing the context file seems to have fixed that. Thanks for that. I assumed that would get replaced with the actual values when performing a deployment.
