### ISSUE TITLE
Create GitHub Codespaces configuration for contributing guides along with Gitpod

### ISSUE THREAD

**Issue by ayush987goyal** [aws/aws-cdk#10447]
Now that GitHub Codespaces is in beta and available to a lot of people, we can create a configuration for this repository based on this [document](https://docs.github.com/en/github/developing-online-with-codespaces/configuring-codespaces-for-your-project). This can be added as a secondary option to existing configuration for Gitpod

**Comment by skinny85** [comment]
Hey @ayush987goyal ,

thanks for opening the issue. I would love to work on this, unfortunately, my account is still on the waitlist for the beta for CodeSpaces, so I don't think it's feasible for now (I assume a lot of our customers are on the waitlist as well).

Thanks,
Adam

**Comment by ayush987goyal** [comment]
Hi @skinny85 ,

I have actually already started working on it in [this](https://github.com/ayush987goyal/aws-cdk/tree/pr/dev-container) fork. I ran into some issue for which I created a discussion [topic](https://github.community/t/the-configuration-options-placed-in-devcontainer-json-not-getting-picked/133161/2) on Codespaces team. You can follow the conversation there. I would raise the PR once I have a fix on the same.

**Comment by skinny85** [comment]
Cool, thanks @ayush987goyal !

**Comment by ayush987goyal** [comment]
@skinny85 Here the the PR https://github.com/aws/aws-cdk/pull/10470
