### ISSUE TITLE
[aws-codebuild] `addFileSystemLocation()` doesn't append fileSystemLocation

### ISSUE THREAD

**Issue by y13i** [aws/aws-cdk#10442]
[`addFileSystemLocation()`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-codebuild.Project.html#add-wbr-file-wbr-system-wbr-locationfilesystemlocation) doesn't append the fileSystemLocation to the Project.

### Reproduction Steps

1. Set up an app `$ cdk init app --language=typescript`

1. Implement this

```ts
import { Stack, Construct, StackProps } from "@aws-cdk/core";
import {
  Project,
  BuildSpec,
  FileSystemLocation,
  Artifacts,
  Source,
} from "@aws-cdk/aws-codebuild";
import { Bucket } from "@aws-cdk/aws-s3";
import { Repository } from "@aws-cdk/aws-codecommit";

export class App4Stack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);

    const buildSpec = BuildSpec.fromObject({
      version: "0.2",
      phases: {
        build: {
          commands: ['echo "Hello world!"'],
        },
      },
    });

    const fileSystemLocation1 = FileSystemLocation.efs({
      identifier: "efs1",
      location: "fs-11111111.efs.eu-west-1.amazonaws.com:/",
      mountPoint: "/efs1",
    });

    const fileSystemLocation2 = FileSystemLocation.efs({
      identifier: "efs2",
      location: "fs-22222222.efs.eu-west-1.amazonaws.com:/",
      mountPoint: "/efs2",
    });

    // This works
    const project1 = new Project(this, "project1", {
      buildSpec,
      fileSystemLocations: [fileSystemLocation1],
    });

    // This also works
    const project2 = new Project(this, "project2", {
      buildSpec,
      fileSystemLocations: [fileSystemLocation1],
    });
    project2.addFileSystemLocation(fileSystemLocation2);

    // This doesn't work
    const project3 = new Project(this, "project3", {
      buildSpec,
    });
    project3.addFileSystemLocation(fileSystemLocation1);

    // This also doesn't work
    const project4 = new Project(this, "project4", {
      buildSpec,
      fileSystemLocations: [],
    });
    project4.addFileSystemLocation(fileSystemLocation1);

    // Debug output shows no difference
    console.log({
      project1: (project1 as any)._fileSystemLocations,
      project3: (project3 as any)._fileSystemLocations,
      project4: (project4 as any)._fileSystemLocations,
    });

    // .addSecondarySource() works btw
    project3.addSecondarySource(
      Source.codeCommit({
        repository: Repository.fromRepositoryName(this, "repo", "repo"),
        identifier: "secondarySource1",
      })
    );

    // .addSecondaryArtifact() works as well
    project4.addSecondaryArtifact(
      Artifacts.s3({
        bucket: Bucket.fromBucketName(this, "bucket", "bucket"),
        identifier: "secondaryArtifact1",
      })
    );
  }
}
```

3. Synthesize cfn template `cdk synth`

### What did you expect to happen?

All projects `project1`, `project2`, `project3` and `project4` to have `FileSystemLocations` property as defined.

### What actually happened?

`project3` and `project4` lacks `FileSystemLocations` property for each resource definition on cfn template output.

### Environment

  - **CLI Version      :** 1.63.0 (build 7a68125)
  - **Framework Version:** `aws-cdk=1.63.0,@aws-cdk/assets=1.63.0,@aws-cdk/aws-applicationautoscaling=1.63.0,@aws-cdk/aws-autoscaling-common=1.63.0,@aws-cdk/aws-cloudwatch=1.63.0,@aws-cdk/aws-codebuild=1.63.0,@aws-cdk/aws-codecommit=1.63.0,@aws-cdk/aws-codeguruprofiler=1.63.0,@aws-cdk/aws-ec2=1.63.0,@aws-cdk/aws-ecr=1.63.0,@aws-cdk/aws-ecr-assets=1.63.0,@aws-cdk/aws-events=1.63.0,@aws-cdk/aws-iam=1.63.0,@aws-cdk/aws-kms=1.63.0,@aws-cdk/aws-lambda=1.63.0,@aws-cdk/aws-logs=1.63.0,@aws-cdk/aws-s3=1.63.0,@aws-cdk/aws-s3-assets=1.63.0,@aws-cdk/aws-sqs=1.63.0,@aws-cdk/aws-ssm=1.63.0,@aws-cdk/cloud-assembly-schema=1.63.0,@aws-cdk/core=1.63.0,@aws-cdk/custom-resources=1.63.0,@aws-cdk/cx-api=1.63.0,@aws-cdk/region-info=1.63.0,jsii-runtime=node.js/v14.11.0`
  - **Node.js Version:** v14.11.0
  - **OS               :** macOS Mojave 10.14.6
  - **Language (Version):** TypeScript (at least)

### Other

[The implementation of `addFileSystemLocation()` looks very similar to `addSecondaryArtifact()`](https://github.com/nataibi/aws-cdk/blob/7a68125f6cd63d2294cc95ef0a53d04f1c2da85f/packages/%40aws-cdk/aws-codebuild/lib/project.ts#L825-L846). But `addSecondaryArtifact()` works fine as long as I tested.

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hey @y13i ,

thanks for opening the issue. Confirming I was able to reproduce it. Working on a fix.

Thanks,
Adam

**Comment by jialechan** [comment]
> [`addFileSystemLocation()`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-codebuild.Project.html#add-wbr-file-wbr-system-wbr-locationfilesystemlocation) doesn't append the fileSystemLocation to the Project.
> 
> ### Reproduction Steps
> 1. Set up an app `$ cdk init app --language=typescript`
> 2. Implement this
> 
> ```ts
> import { Stack, Construct, StackProps } from "@aws-cdk/core";
> import {
>   Project,
>   BuildSpec,
>   FileSystemLocation,
>   Artifacts,
>   Source,
> } from "@aws-cdk/aws-codebuild";
> import { Bucket } from "@aws-cdk/aws-s3";
> import { Repository } from "@aws-cdk/aws-codecommit";
> 
> export class App4Stack extends Stack {
>   constructor(scope: Construct, id: string, props?: StackProps) {
>     super(scope, id, props);
> 
>     const buildSpec = BuildSpec.fromObject({
>       version: "0.2",
>       phases: {
>         build: {
>           commands: ['echo "Hello world!"'],
>         },
>       },
>     });
> 
>     const fileSystemLocation1 = FileSystemLocation.efs({
>       identifier: "efs1",
>       location: "fs-11111111.efs.eu-west-1.amazonaws.com:/",
>       mountPoint: "/efs1",
>     });
> 
>     const fileSystemLocation2 = FileSystemLocation.efs({
>       identifier: "efs2",
>       location: "fs-22222222.efs.eu-west-1.amazonaws.com:/",
>       mountPoint: "/efs2",
>     });
> 
>     // This works
>     const project1 = new Project(this, "project1", {
>       buildSpec,
>       fileSystemLocations: [fileSystemLocation1],
>     });
> 
>     // This also works
>     const project2 = new Project(this, "project2", {
>       buildSpec,
>       fileSystemLocations: [fileSystemLocation1],
>     });
>     project2.addFileSystemLocation(fileSystemLocation2);
> 
>     // This doesn't work
>     const project3 = new Project(this, "project3", {
>       buildSpec,
>     });
>     project3.addFileSystemLocation(fileSystemLocation1);
> 
>     // This also doesn't work
>     const project4 = new Project(this, "project4", {
>       buildSpec,
>       fileSystemLocations: [],
>     });
>     project4.addFileSystemLocation(fileSystemLocation1);
> 
>     // Debug output shows no difference
>     console.log({
>       project1: (project1 as any)._fileSystemLocations,
>       project3: (project3 as any)._fileSystemLocations,
>       project4: (project4 as any)._fileSystemLocations,
>     });
> 
>     // .addSecondarySource() works btw
>     project3.addSecondarySource(
>       Source.codeCommit({
>         repository: Repository.fromRepositoryName(this, "repo", "repo"),
>         identifier: "secondarySource1",
>       })
>     );
> 
>     // .addSecondaryArtifact() works as well
>     project4.addSecondaryArtifact(
>       Artifacts.s3({
>         bucket: Bucket.fromBucketName(this, "bucket", "bucket"),
>         identifier: "secondaryArtifact1",
>       })
>     );
>   }
> }
> ```
> 
> 1. Synthesize cfn template `cdk synth`
> 
> ### What did you expect to happen?
> All projects `project1`, `project2`, `project3` and `project4` to have `FileSystemLocations` property as defined.
> 
> ### What actually happened?
> `project3` and `project4` lacks `FileSystemLocations` property for each resource definition on cfn template output.
> 
> ### Environment
> * **CLI Version      :** 1.63.0 (build [7a68125](https://github.com/aws/aws-cdk/commit/7a68125f6cd63d2294cc95ef0a53d04f1c2da85f))
> * **Framework Version:** `aws-cdk=1.63.0,@aws-cdk/assets=1.63.0,@aws-cdk/aws-applicationautoscaling=1.63.0,@aws-cdk/aws-autoscaling-common=1.63.0,@aws-cdk/aws-cloudwatch=1.63.0,@aws-cdk/aws-codebuild=1.63.0,@aws-cdk/aws-codecommit=1.63.0,@aws-cdk/aws-codeguruprofiler=1.63.0,@aws-cdk/aws-ec2=1.63.0,@aws-cdk/aws-ecr=1.63.0,@aws-cdk/aws-ecr-assets=1.63.0,@aws-cdk/aws-events=1.63.0,@aws-cdk/aws-iam=1.63.0,@aws-cdk/aws-kms=1.63.0,@aws-cdk/aws-lambda=1.63.0,@aws-cdk/aws-logs=1.63.0,@aws-cdk/aws-s3=1.63.0,@aws-cdk/aws-s3-assets=1.63.0,@aws-cdk/aws-sqs=1.63.0,@aws-cdk/aws-ssm=1.63.0,@aws-cdk/cloud-assembly-schema=1.63.0,@aws-cdk/core=1.63.0,@aws-cdk/custom-resources=1.63.0,@aws-cdk/cx-api=1.63.0,@aws-cdk/region-info=1.63.0,jsii-runtime=node.js/v14.11.0`
> * **Node.js Version:** v14.11.0
> * **OS               :** macOS Mojave 10.14.6
> * **Language (Version):** TypeScript (at least)
> 
> ### Other
> [The implementation of `addFileSystemLocation()` looks very similar to `addSecondaryArtifact()`](https://github.com/nataibi/aws-cdk/blob/7a68125f6cd63d2294cc95ef0a53d04f1c2da85f/packages/%40aws-cdk/aws-codebuild/lib/project.ts#L825-L846). But `addSecondaryArtifact()` works fine as long as I tested.
> 
> This is 🐛 Bug Report

Hello, I want to ask another question. Have you tried using efs to cache the docker layer generated by the codebuild process?
