### ISSUE TITLE
[@aws-cdk/aws-lambda-nodejs] containerEnvironment is in the README, but is not implemented 

### ISSUE THREAD

**Issue by winjer** [aws/aws-cdk#10443]
The docs say:

Use the containerEnvironment prop to pass environments variables to the Docker container running Parcel:
```
new lambda.NodejsFunction(this, 'my-handler', {
  containerEnvironment: {
    NODE_ENV: 'production',
  },
});
```
But this is not implemented.

### Environment

  - **CLI Version      :** 
  - **Framework Version:** 1.63.0
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):** 

### Other

--- 

This is :bug: Bug Report

**Comment by jogold** [comment]
It's `parcelEnvironment`, the doc will be updated.

https://github.com/aws/aws-cdk/blob/9bf8e13bd47608070b73221c11c55b09d03c0a4c/packages/%40aws-cdk/aws-lambda-nodejs/lib/bundling.ts#L46-L51

**Comment by winjer** [comment]
thanks! i failed to guess this ;)
