### ISSUE TITLE
Add Lightsail support

### ISSUE THREAD

**Issue by zulhfreelancer** [aws/aws-cdk#10471]
From my research, I couldn't find CDK constructs for Lightsail product. Would be nice if CDK can support Lightsail too.

### Use Case

My infrastructure uses Lightsail and other AWS products i.e. RDS. Practically, this can be achieved by [VPC peering](https://lightsail.aws.amazon.com/ls/docs/en_us/articles/lightsail-how-to-set-up-vpc-peering-with-aws-resources).

Though there are many alternatives available out there to configure the Lightsail server i.e. Ansible, I think it would be nice if I can leverage the IaC power provided by CDK to setup my Lightsail server i.e. running the user data/script during setup phase.

Without this Lightsail support, I need to rely on other tools or set up my Lightsail server manually using the web UI and that process is time consuming, error-prone and make it hard to get semantic-versioned for internal audit record. 

### Proposed Solution

Add Lightsail support such as:

* Server provisioning:
    * Select type (instance or [database](https://aws.amazon.com/blogs/aws/new-managed-databases-for-amazon-lightsail/))
    * Select region
    * Select OS
    * Select OS versions
    * Add launch script / user data (important)
    * Add SSH key
    * Select instance plan
    * Naming the instance
    * Tagging the instance (key only and key/value)
* VPC peering between Lightsail VPC <> AWS VPC
* Networking:
    * Create static IP
    * Linking static IP to Lightsail instance
* Storage:
    * Create [block storage](https://aws.amazon.com/lightsail/features/highly-available-storage/)
    * Linking block storage to Lightsail instance

### Other

N/A

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by SomayaB** [comment]
Hi @zulhfreelancer, unfortunately until Lightsail is added to CloudFormation we can't add it to the CDK.

**Comment by zulhfreelancer** [comment]
Noted @SomayaB. Do let me know if you need me to open another issue in CloudFormation repo. And please share the link to that repo too.

**Comment by SomayaB** [comment]
@zulhfreelancer I created an issue here: https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/640, I would suggest adding a +1 on it.

**Comment by zulhfreelancer** [comment]
@SomayaB thank you, done!

**Comment by SomayaB** [comment]
I will close this issue for now since it's not actionable by the CDK and we can reopen it when Lightsail is available on Cloudformation. Although lower lever constructs get automatically added to the CDK when CFN adds them so there shouldn't be a need to reopen.

**Comment by esamattis** [comment]
Lightsail seems to available in CloudFormation https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_Lightsail.html
