### ISSUE TITLE
[aws-appsync] Code first object type implementation of multiple interfaces generates invalid graphql output

### ISSUE THREAD

**Issue by chargome** [aws/aws-cdk#10479]
Using the code-first strategy: when an ```ObjectType``` implements several ```InterfaceType```, the generated schema produces a syntax error since the interfaces are appended via ```,``` instead of ```&```.

### Reproduction Steps

Given the following code:
```typescript
const myInterface1 = new InterfaceType('MyInterface1', {
  definition: {
    // ...
  }
});

const myInterface2 = new InterfaceType('MyInterface2', {
  definition: {
    // ...
  }
});

const myObjectType = new ObjectType('MyObjectType', {
  interfaceTypes: [myInterface1, myInterface2],
  // ...
});
```

### What did you expect to happen?
Output should be
```graphql
interface MyInterface1 {
  # ...
}

interface MyInterface2 {
  # ...
}

type MyObjectType implements MyInterface1 & MyInterface2 {
  # ...
}
```

### What actually happened?

Instead the code outputs the following, which is invalid graphql code:
```graphql
interface MyInterface1 {
  # ...
}

interface MyInterface2 {
  # ...
}

type MyObjectType implements MyInterface1, MyInterface2 {
  # ...
}
```

### Environment

  - **CLI Version      :**
  - **Framework Version: 1.63.0**
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):** 

### Other

--- 

This is :bug: Bug Report

**Comment by BryanPan342** [comment]
Nice catch @chargome! Writing a fix right now.

**Comment by BryanPan342** [comment]
@chargome out of curiosity, how has your experience with the code-first approach been so far?

**Comment by chargome** [comment]
@BryanPan342 So far it has helped me a lot writing my (rather complex) GraphQL schema in a more modular and clear way. The only thing I am missing is the final schema output somewhere in my project, is there a straightforward way to do this? Good work!

**Comment by BryanPan342** [comment]
@chargome check out this sample app i made!

It's not complete with functional resolvers at the moment, but I added a bit of code to `cdk-app.ts` to spit out the generated schema :) 

https://github.com/BryanPan342/starwars-code-first/blob/master/bin/starwars-code-first.ts#L7-L20

**Comment by chargome** [comment]
@BryanPan342 cheers, that's what I needed ✌️
