### ISSUE TITLE
[aws-lambda] EventSourceMappingOptions default values for Construct Props

### ISSUE THREAD

**Issue by sekerjak** [aws/aws-cdk#10486]
Dear community,

I am interested in EventSourceMappingOptions, especially **retry_attempts** parameter mentioned here https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_lambda/EventSourceMappingOptions.html and here https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-lambda.EventSourceMappingOptions.html. The documentation is mentioning following:

```
retryAttempts?
Type: number (optional, default: 10000)
The maximum number of times to retry when the function returns an error.

Valid Range:

Minimum value of 0
Maximum value of 10000
```

BUT this documentation https://docs.aws.amazon.com/lambda/latest/dg/API_CreateEventSourceMapping.html is mentioning the following:

```
MaximumRetryAttempts
(Streams) Discard records after the specified number of retries. The default value is infinite (-1). When set to infinite (-1), failed records will be retried until the record expires.

Type: Integer

Valid Range: Minimum value of 0. Maximum value of 10000.

Required: No
```

So I expected, that default value will be **10 000** and not **infinite** as it's mentioned above, so I tried following:

```
  fn = aws_lambda.Function(self.stack, "failing-lambda",
                                 code=aws_lambda.Code.from_inline(lambda_code),
                                 runtime=aws_lambda.Runtime.PYTHON_3_7,
                                 handler='index.failing_lambda',
                                 function_name=self.workspace.name_for("failing-lambda"),
                                 timeout=Duration.seconds(30)
                                 )

   fn.add_event_source_mapping(id="errout-mapping", event_source_arn=consumer.attr_consumer_arn,
                                    starting_position=aws_lambda.StartingPosition.LATEST,
                                    batch_size=500)
```

And when I opened Lambda Designer in AWS console I saw the following values:

```
Batch size: 500
Batch window: None
Concurrent batches per shard: 1
Last processing result: No records processed
Maximum age of record: -1
On-failure destination:
{
  "onFailure": {}
}
Retry attempts: -1  
Split batch on error: No
```

I expected 10 000 as is mentioned in the documentation, but it was set to infinite (btw, I am fine with infinite, but I wanted to make sure, that it will not change in the future and infinite as default is expected)

PS: The similar "issue" is with the Maximum age of record as well I think, as documentation is saying 7 days, but I see -1 (infinite). Am I doing something wrong?

Thank you, Jakub.

---

This is a 📕 documentation issue

**Comment by nija-at** [comment]
@sekerjak - thanks for bringing this to our attention. The documentation on the CDK side is indeed inaccurate. The default is infinite. The minimum configurable value is 0 and the maximum configurable value is 10000.

Apologies for the error.

**Comment by sekerjak** [comment]
Hey @nija-at,

I saw your commit, thank you for your resolution, but I think, that there is the same problem with **Maximum age of record ** parameter as well. I mentioned it in my last paragraph, but I didn't emphasize it too much.
