### ISSUE TITLE
[aws-apigateway] mTLS support 

### ISSUE THREAD

**Issue by doug-ferris** [aws/aws-cdk#10487]
AWS recently added support for mTLS on API Gateway and this has Cloudformation support (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-domainname.html#cfn-apigateway-domainname-mutualtlsauthentication), I would like to be able to configure this using Cloudformation.

### Use Case

We are building a new service which we need to use mTLS for, without this we have to either use straight Cloudformation or use ECS where we can control the webserver.

### Proposed Solution

Support in both CfnDomainName for adding an object with your MutualTlsAuthentication configuration, but also add it to the DomainName construct to allow it to be easier to use.

### Other

* [X] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by doug-ferris** [comment]
I've done an initial implementation of this which involved a CfnBump which changed a non-trivial amount of files (ie, something around 19,000 lines over 18 lines...)
I also found that my WSL had the wrong date... So I'll fix my commit history and open a PR tomorrow.
Is there any etiquette around who does cfn bumps/how they happen so that they don't bleed into PR's like this?

**Comment by nija-at** [comment]
The CDK team runs updates to the CloudFormation spec. This ideally happens once a week but can be delayed if we have issues with adopting the new spec. Please wait for this before opening a PR.

**Comment by doug-ferris** [comment]
More than happy to wait! Is there a specific commit to look out for, or does will that coincide with 1.64.0?
