### ISSUE TITLE
[aws-ec2] Typescript missing SubnetSelection in 1.63.0

### ISSUE THREAD

**Issue by jgarcia-starz** [aws/aws-cdk#10484]
I am trying to create a Lambda and assign subnets but I don't see the SubnetSelection interface. Is it missing?

These are pre-existing subnets I am pulling in from the ec2 module.

Module version: 1.63.0
CLI version: 1.63.0
Language: TypeScript

**Comment by jgarcia-starz** [comment]
found a workaround

**Comment by zubairzahoor** [comment]
What was the workaround? @jgarcia-starz

**Comment by AjkayAlan** [comment]
@zubairzahoor - Myself and @maria-jackson ran into this as well in CDK 1.87.1. We worked around this by first pulling in a pre-existing VPC using ec2.Vpc.fromLookup (https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ec2.Vpc.html#static-fromwbrlookupscope-id-options):

```typescript
import * as ec2 from '@aws-cdk/aws-ec2';

const vpc = ec2.Vpc.fromLookup(this, 'vpc' { ... });
```

After getting your vpc, you can use selectSubnets (https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ec2.Vpc.html#selectwbrsubnetsselection):

```typescript
const subnets = vpc.selectSubnets({ ... });
```

We created a bug report to address this upstream.
