### ISSUE TITLE
[aws-lambda] Construct Function, Construct Props logRetention 

### ISSUE THREAD

**Issue by sekerjak** [aws/aws-cdk#10492]
### Reproduction Steps

        fn = aws_lambda.Function(self.stack, "failing-lambda",
                                 code=aws_lambda.Code.from_inline(lambda_code),
                                 runtime=aws_lambda.Runtime.PYTHON_3_7,
                                 handler='index.failing_lambda',
                                 function_name=self.workspace.name_for("failing-lambda"),
                                 timeout=Duration.seconds(30), log_retention=aws_logs.RetentionDays.FIVE_DAYS
                                 )

### What did you expect to happen?

I expected that the log_retention parameter will be set accordingly to the FIVE DAYS.

### What actually happened?

` botocore.exceptions.ClientError: An error occurred (ValidationError) when calling the CreateStack operation: Parameters: [AssetParameters27b58c1b3f137723c1cdbb881058a4b21230873b55318044de2a913e607a49f9S3Bucket8795CE3D, AssetParameters27b58c1b3f137723c1cdbb881058a4b21230873b55318044de2a913e607a49f9ArtifactHash8DB7EB35, AssetParameters27b58c1b3f137723c1cdbb881058a4b21230873b55318044de2a913e607a49f9S3VersionKeyFC482B2A] must have values`

So I suppose, that problem is that Lambda code is loaded as **inline** and not from **asset**. Is my guess right? Why it should not be possible to set log retention in a case I am loading code as inline?

### Environment

  - **CLI Version      :**
  - **Framework Version:**
  - **Node.js Version:**  v14.11.0
  - **OS               :** macOS Catalina v10.15.6
  - **Language (Version):**  Python 3.8.5

### Workaround

```
    fn = aws_lambda.Function(self.stack, "failing-lambda",
                                 code=aws_lambda.Code.from_inline(lambda_code),
                                 runtime=aws_lambda.Runtime.PYTHON_3_7,
                                 handler='index.failing_lambda',
                                 function_name=self.workspace.name_for("failing-lambda"),
                                 timeout=Duration.seconds(30), log_retention=aws_logs.RetentionDays.FIVE_DAYS
                                 )
    lmb_log_group = aws_logs.LogGroup(self.stack, "failing-lambda-log-group",
                                          log_group_name='/aws/lambda/' + fn.function_name,
                                          retention=aws_logs.RetentionDays.FIVE_DAYS,
                                          removal_policy=core.RemovalPolicy.DESTROY)
```

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
This doesn't seem like an error related to `log_retention`. Something else is going on in your app.

This is my Python CDK app that I'm able to deploy successfully - 

```python
from aws_cdk import (
    core,
    aws_lambda,
    aws_logs
)

app = core.App()
stack = core.Stack(app, "mystack")

aws_lambda.Function(stack, "failing-lambda",
  code=aws_lambda.Code.from_inline("foo"),
  runtime=aws_lambda.Runtime.PYTHON_3_7,
  handler='index.failing_lambda',
  log_retention=aws_logs.RetentionDays.FIVE_DAYS
)

app.synth()
```
