### ISSUE TITLE
[aws-rds] CfnDBSubnetGroup and CfnDBCluster naming only accepts lowercase

### ISSUE THREAD

**Issue by sperka** [aws/aws-cdk#10494]
When trying to create an Aurora Serverless MySql cluster, naming must be lowercase, otherwise CF loses reference to the resources.

### Reproduction Steps

```ts
const isolatedSubnetIds = vpc.isolatedSubnets.map(subnet => subnet.subnetId)

const dbSubnetGroup = new CfnDBSubnetGroup(this, 'AppDatabaseSubnetGroup', {
	dbSubnetGroupDescription: 'Subnet group for AppDatabase',
	subnetIds: isolatedSubnetIds,
	dbSubnetGroupName: 'appdatabasesubnetgroup', // MUST BE LOWERCASE
})

const rdsCluster = new CfnDBCluster(this, 'AppDatabase', {
	engine: 'aurora-mysql',
	dbClusterIdentifier: 'appdatabase', // MUST BE LOWERCASE
	engineMode: 'serverless',
	engineVersion: '5.7.12',
	enableHttpEndpoint: true,
	databaseName: appDatabaseProps.defaultDatabaseName,
	deletionProtection: false,
	masterUsername: dbCredentialsSecret.secretValueFromJson('username').toString(),
	masterUserPassword: dbCredentialsSecret.secretValueFromJson('password').toString(),
	scalingConfiguration: {
		...
	},
	dbSubnetGroupName: dbSubnetGroup.ref, // <-- THIS ONE FAILS IF dbSubnetGroup's name is not lowercase
	vpcSecurityGroupIds: [dbSecurityGroup.securityGroupId],
})
```

### What did you expect to happen?

Cluster should be created even when names have uppercase characters.

### What actually happened?

If I use uppercase characters in the name of the DB Subnet Group, resource **IS** created but the DB fails to be created due to error:

```ts
const dbSubnetGroup = new CfnDBSubnetGroup(this, 'AppDatabaseSubnetGroup', {
	dbSubnetGroupDescription: 'Subnet group for AppDatabase',
	subnetIds: isolatedSubnetIds,
	dbSubnetGroupName: 'AppDatabaseSubnetGroup', // NOW IT'S NOT ALL LOWERCASE
})
```

```
AppDatabaseSubnetGroup | CREATE_COMPLETE
AppDatabase | CREATE_FAILED | DB subnet group 'AppDatabaseSubnetGroup' does not exist. (Service: AmazonRDS; Status Code: 404; Error Code: DBSubnetGroupNotFoundFault; Request ID: a36b4f3f-7b36-4e9d-a17c-843028cbf543; Proxy: null)
```

### Environment

  - **CLI Version      :*`aws-cli/2.0.40 Python/3.8.5 Darwin/19.6.0 source/x86_64`*
  - **Framework Version:*`1.58.0 (build 09e12a6)`*
  - **Node.js Version:*`v12.16.2`* 
  - **OS               :*MacOS Catalina 10.15.6*
  - **Language (Version):*TypeScript 3.7.5* 

### Other

* Same applies to `CfnDBCluster.dbClusterIdentifier`. If it's now all lowercase, it fails to create
* works if names contain dash (-) character

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Thanks for the report @sperka . In general, there's not much we can do here - the `Cfn*` classes correspond directly to the CloudFormation layer, and are all auto-generated, so we can't really add custom validations that the service owner did not include in the schema.

Can I recommend you try using our new [`ServerlessCluster` class instead](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-rds.ServerlessCluster.html)?

Thanks,
Adam
