### ISSUE TITLE
[s3] support s3:ObjectRestore:Completed event type

### ISSUE THREAD

**Issue by mauricioharley** [aws/aws-cdk#10498]
I'm building a solution for a customer that leverages S3 data events. More specifically, it relies on the s3:ObjectRestore:Completed event. According to the CDK Python documentation, it seems this event type is not supported:

https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_s3/EventType.html

I can't understand why nearly all event types are supported, but this one. It would be nice if we could have this in the CDK code itself, instead of having to look for workarounds, such as using CloudFormation templates.

Any possible roadmaps to share on this, or eventual workarounds?

### Use Case

The solution works smoothly considering CloudFormation (or even Terraform). The use case follows as an image attached to this feature request.

### Proposed Solution

Some temporary workaround. Open to suggestions.

### Other
I'm facing problems when trying to code this ("notify_lambda" corresponds to Lambda function B):
<code>
destination_bucket.add_event_notification(
            s3.EventType.RESTORE_COMPLETED,
            s3_notifications.LambdaDestination(self.notify_lambda)
)
</code>

![TEMP - Restore Objects](https://user-images.githubusercontent.com/19189450/94005775-0e506a80-fd9f-11ea-81ca-76919fc0c0ae.jpg)

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rrhodes** [comment]
Hello, I'm looking into this now and hope to have a PR open shortly.
