### ISSUE TITLE
[ApiGatewayV2] integration subtype - sqs

### ISSUE THREAD

**Issue by dsoshawn** [aws/aws-cdk#10497]
## :Question: -->

While declaring AWS::ApiGatewayV2::Integration resource to create an integration with SQS, the option IntegrationSubtype is available in CloudFormation documentation => 
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigatewayv2-integration.html#cfn-apigatewayv2-integration-integrationsubtype 

However, the construct IntegrationSubtype is not available while working with CDK => 
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-apigatewayv2.CfnIntegration.html

I need to configure IntegrationSubtype with CDK. 
Is this a limitation on the CDK end here, as CloudFormation already supports the subtype key?
or Is there any alternative to workaround this such that I can configure IntegrationSubtype using CDK ?

**Comment by rrhodes** [comment]
Hi @dsoshawn,

Looking at the [CDK documentation for CfnIntegrationProps I see an option for IntegrationSubtype](https://docs.aws.amazon.com/cdk/api/latest/typescript/api/aws-apigatewayv2/cfnintegrationprops.html#aws_apigatewayv2_CfnIntegrationProps_integrationSubtype) as expected.

Looks like there's no custom CDK constructs for "AWS::ApiGatewayV2::Integration" resource yet, but the above appears sufficient for your needs using CDK.

If I've misunderstood the problem, give me a shout, happy to investigate further.

**Comment by nija-at** [comment]
Moving this as a feature request. 

Until this is implemented, you can use escape hatches or Cfn construct types (pointed out by @rrhodes) to use this feature

**Comment by hoegertn** [comment]
Using the L1 this is possible as pointed out. Example:

```
  const api = new apigw.HttpApi(this, 'eventbridge-api', {
      createDefaultStage: true,
    });
    const integ = new apigw.CfnIntegration(this, 'Integ', {
      apiId: api.httpApiId,
      integrationType: 'AWS_PROXY',
      integrationSubtype: 'EventBridge-PutEvents',
      credentialsArn: role.roleArn,
      requestParameters: {
        Source: 'Gateway',
        Detail: '$request.body',
        DetailType: "api-call",
        EventBusName: eventBus.eventBusArn,
      },
      payloadFormatVersion: '1.0',
      timeoutInMillis: 10000,
    });
    new apigw.CfnRoute(this, 'DefaultRoute', {
      apiId: api.httpApiId,
      routeKey: apigw.HttpRouteKey.DEFAULT.key,
      target: `integrations/${integ.ref}`,
    });

```

I needed this for some projects and have it on my todo list to implement an `AwsIntegration` L2.

Is somebody else working on it?

**Comment by nija-at** [comment]
I've repurposed this issue to only refer to the sqs subtype so as to track each one. Here's another one for step functions - https://github.com/aws/aws-cdk/issues/11947
