### ISSUE TITLE
[autoscaling] StepScalingPolicy ignores estimatedInstanceWarmup property

### ISSUE THREAD

**Issue by ddneilson** [aws/aws-cdk#10514]
The implementation of [StepScalingPolicy](https://github.com/aws/aws-cdk/blob/8ec1cfe67cc03f34f9ba436d5092209649bb73e3/packages/%40aws-cdk/aws-autoscaling/lib/step-scaling-policy.ts#L66) ignores the [estimatedInstanceWarmup](https://github.com/aws/aws-cdk/blob/8ec1cfe67cc03f34f9ba436d5092209649bb73e3/packages/%40aws-cdk/aws-autoscaling/lib/step-scaling-policy.ts#L39) property of the construct.

The property *should* be passed on to the StepScalingAction objects ([lowerAction ](https://github.com/aws/aws-cdk/blob/8ec1cfe67cc03f34f9ba436d5092209649bb73e3/packages/%40aws-cdk/aws-autoscaling/lib/step-scaling-policy.ts#L88)& [upperAction](https://github.com/aws/aws-cdk/blob/8ec1cfe67cc03f34f9ba436d5092209649bb73e3/packages/%40aws-cdk/aws-autoscaling/lib/step-scaling-policy.ts#L118)) that the StepScalingPolicy creates, but it is not.

### Reproduction Steps

Create a StepScalingPolicy with an estimatedInstanceWarmup property value. 

### What did you expect to happen?

The value of estimatedInstanceWarmup is translated into a value for the [EstimatedInstanceWarmup](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-policy.html#cfn-as-scalingpolicy-estimatedinstancewarmup) property of the generated [AWS::AutoScaling::ScalingPolicy](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-policy.html).

### What actually happened?

There is no EstimatedInstanceWarmup value in the generated AWS::AutoScaling::ScalingPolicy resource.

### Environment

  - **CLI Version      :** 1.63.0+
  - **Framework Version:** 1.63.0+
  - **Node.js Version:** any
  - **OS               :** any
  - **Language (Version):** all

--- 

This is :bug: Bug Report

**Comment by NetaNir** [comment]
It does not seem like it is possible to configure the environment variable using [Canary CloudFormation resource](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-synthetics-canary.html). When creating a Canary the synthetics service creates a lambda function on your behalf, the lambda resource itself is not created via CloudFormation, so if the Canary resource does not expose these properties on its API there is no (easy) way to change them using the resource.

**Comment by BDeus** [comment]
Furthermore, the `cooldown` property should not be proposed on `BasicStepScalingPolicyProps` since it used only for SimpleScalingPolicy [AWS Doc](https://docs.aws.amazon.com/fr_fr/AWSCloudFormation/latest/UserGuide/aws-properties-as-policy.html#cfn-as-scalingpolicy-cooldown)

**Comment by BDeus** [comment]
> Furthermore, the `cooldown` property should not be proposed on `BasicStepScalingPolicyProps` since it used only for SimpleScalingPolicy [AWS Doc](https://docs.aws.amazon.com/fr_fr/AWSCloudFormation/latest/UserGuide/aws-properties-as-policy.html#cfn-as-scalingpolicy-cooldown)

it appears that it use as a default for instance warmup since cloudformation doesn't support defaultInstanceWarmup for now
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-group.html#cfn-as-group-defaultinstancewarmup

**Comment by rgoltz** [comment]
> it appears that it used as a default for instance warmup since cloudformation doesn't support defaultInstanceWarmup for now https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-group.html#cfn-as-group-defaultinstancewarmup

Hi @BDeus Hi @ddneilson - It seems the CFN documentation changed for DefaultInstanceWarmup within the last days - It seems that is now available via CFN (hence at minimum as L1 in CDK).
