### ISSUE TITLE
[synthetics] Support setting environment variables during canary creation

### ISSUE THREAD

**Issue by dlee-cpu** [aws/aws-cdk#10515]
Support setting environment variables during canary creation

### Use Case
Since the canary is wrapped by a lambda, we should be able to create env variables that are available during the lambda execution so we can pass additional runtime information during test runs.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by NetaNir** [comment]
It does not seem like it is possible to configure the environment variable using [Canary CloudFormation resource](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-synthetics-canary.html). When creating a Canary the synthetics service creates a lambda function on your behalf, the lambda resource itself is not created via CloudFormation, so if the Canary resource does not expose these properties on its API there is no (easy) way to change them using the resource.

**Comment by dlee-cpu** [comment]
thanks for the reply.  I should have opened this as a feature request to the cloudformation canary resource rather than the cdk.

**Comment by flochaz** [comment]
It's now possible ( https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-synthetics-canary-runconfig.html#cfn-synthetics-canary-runconfig-environmentvariables )

**Comment by dlee-cpu** [comment]
> It's now possible ( https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-synthetics-canary-runconfig.html#cfn-synthetics-canary-runconfig-environmentvariables )

thanks for keeping me in the loop and constantly improving the developer experience.

**Comment by jonny-rimek** [comment]
adding an env var looks like this:
```js
        const cfnCanary = canary.node.defaultChild as synthetics.CfnCanary
        cfnCanary.addPropertyOverride('RunConfig.EnvironmentVariables', {
            API_URL: "someurl"
        })
```
