### ISSUE TITLE
[certificatemanager] The certificate provided must be owned by the account creating the domain. 

### ISSUE THREAD

**Issue by mainframenzo** [aws/aws-cdk#10529]
In us-west-2 I can not create an API Gateway custom domain by referencing a manually created/validated cert in us-east-1: `Invalid request provided: The certificate provided must be owned by the account creating the domain. (Service: ApiGateway, Status Code: 400, Request ID: dd86be20-8344-4ff9-8680-abb399dbbff3, Extended Request ID: null). CloudFormation errors on the `TestStackDomainName` resource.
`
### Reproduction Steps

`cdk deploy --profile redacted TestStack -v`

lib/test-stack.ts:
```
import * as Route53 from '@aws-cdk/aws-route53';
import * as ACM from '@aws-cdk/aws-certificatemanager';
import * as APIGateway from '@aws-cdk/aws-apigateway';
import * as Lambda from '@aws-cdk/aws-lambda';
import * as CDK from '@aws-cdk/core';

export class TestStack extends CDK.Stack {
  constructor(scope: CDK.Construct, id: string, props?: CDK.StackProps) {
    super(scope, id, props);
    
    const hostedZone = Route53.HostedZone.fromLookup(this, 'HostedZone', {
      domainName: this.node.tryGetContext('domainname')
    });

    const certificate = ACM.Certificate.fromCertificateArn(this, 'ImportedCertificate', this.node.tryGetContext('certarn'));

    const api = new APIGateway.RestApi(this, 'APIGateway', {
      restApiName: 'API',
      endpointConfiguration: {
        types: [APIGateway.EndpointType.REGIONAL]
      }
    });

    const apiDomainName = api.addDomainName('DomainName', {
      domainName: this.node.tryGetContext('apidomainname'),
      certificate: certificate,
      endpointType: APIGateway.EndpointType.REGIONAL
    });

    const testLambda = new Lambda.Function(this, 'TestLambda', {
      runtime: Lambda.Runtime.NODEJS_12_X,
      code: Lambda.Code.fromAsset('functions/test'),
      handler: 'build/index.handler'
    });

    const testResource = api.root.addResource('test');
    testResource.addMethod('GET', new APIGateway.LambdaIntegration(testLambda), {});
  }
}
```

bin/test.ts:
```
#!/usr/bin/env node
import 'source-map-support/register';
import * as CDK from '@aws-cdk/core';
import { TestStack } from '../lib/test-stack';

const app = new CDK.App();

const props = {
  env: { account: app.node.tryGetContext('accountid'), region: app.node.tryGetContext('region') }
}; 

new TestStack(app, 'TestStack', props);

app.synth();
```

cdk.json:
```
{
  "app": "npx ts-node bin/test.ts",
  "context": {
    "@aws-cdk/core:enableStackNameDuplicates": "true",
    "aws-cdk:enableDiffNoFail": "true",
    "@aws-cdk/core:newStyleStackSynthesis": true,
    "accountid": "redacted",
    "region": "us-west-2",
    "domainname": "myspace.com",
    "apidomainname": "api.myspace.com",
    "certarn": "arn:aws:acm:us-east-1:redacted:certificate/redacted"
  }
}
```
### What did you expect to happen?

I would expect to be able to reference this certificate. I have bootstrapped again just to be sure and verified both us-west-2 and us-east-1 have CDKToolkit stacks and relative buckets in S3.

`cdk bootstrap --force --profile redacted --cloudformation-execution-policies arn:aws:iam::aws:policy/AdministratorAccess aws://redacted/us-east-1 aws://redacted/us-west-2`

### What actually happened?

I could not reference this certificate. 

This is problematic because I can not generate a certificate through the CDK due to dns validation timeout issues, so manual creation/validation of certs with references is all that's left!

### Environment

  - **CLI Version      :** (build 7a68125)
  - **Framework Version:**
  - **Node.js Version:** v12.18.2
  - **OS               :** 10.14.3 (18D109)
  - **Language (Version):** TypeScript (3.8.3)

### Other

--- 

This is :bug: Bug Report

**Comment by njlynch** [comment]
There's a dual behavior for an API Gateway certificate, based on the endpoint type. If the endpoint type is EDGE, the certificate must be in us-east-1 (as your certificate is here); if the endpoint type is REGIONAL, the certificate must be in the same region as the API.

See the API Gateway docs:

https://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-custom-domains-prerequisites.html
> To use an ACM certificate with an API Gateway edge-optimized custom domain name, you must request or import the certificate in the US East (N. Virginia) (us-east-1) Region. For an API Gateway Regional custom domain name, you must request or import the certificate in the same Region as your API.

This is partially implied -- but not as strongly stated -- in the CDK docs for the `certificate` as well:
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-apigateway.DomainName.html#certificate
> For "EDGE" domain names, the certificate needs to be in the US East (N. Virginia) region.

If you're creating your API in us-west-2, you'll need a certificate in that region as well.

**Comment by mainframenzo** [comment]
@njlynch Ah, yup, that's it! I switched from EDGE to Regional at some point during this process and didn't create a cert in the region of the API. Thank you!
