### ISSUE TITLE
[step-functions] Decouple CDK ID and Step ID

### ISSUE THREAD

**Issue by carlosafonso** [aws/aws-cdk#10532]
Hi!

This request is for the possibility to decouple the CDK node ID from the Step Functions state ID when defining a Step Functions state machine using CDK.

### Use Case

The current implementation assigns the same ID both to the internal CDK node as well as to the actual step ID in the state machine definition. There might be some cases where I define two state machines in the same stack, and both have a step with the same ID (e.g., "UploadFilesToBucket"). In this case, `cdk synth` fails because there are two constructs with the same ID under the same scope (also called "UploadFilesToBucket").

The CDK already allows to add an arbitrary prefix to the State ID, but there's no way to fully decouple or separate both IDs.

### Proposed Solution

Allowing an optional parameter in the State definition to set a specific name for the step, otherwise falling back to the construct ID.

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by ADTClone** [comment]
Could this be reopened and looked into? I'm unsure why this was closed as it's a very valid point.

The names given to the step function tasks are what shows in the step function interface in AWS. If multiple step functions with overlapping names are created in the same stack, then unique identifiers need to be added to the task name for CDK to work which impacts the end users experience of the step functions.

Maybe a solution is to separate them into different stacks? But regardless within the scope of a step function the task names only need to be unique within that scope.
