### ISSUE TITLE
Grant methods do not grant key decryption permissions when bucket is encrypted with KMS_MANAGED

### ISSUE THREAD

**Issue by lschierer** [aws/aws-cdk#10549]
I am attempting to grant a lambda function read/write access to an S3 bucket using the bucket.grantReadWrite function.  The lambda function is ending up with a role that should be granting access, but the bucket ends up with a blank bucket policy.  the lambda function is getting permission denied errors. 

### Reproduction Steps

```ts
constructor(scope: core.Construct, id: string) {
    super(scope, id);

    const mailbucket = new s3.Bucket(this, "mailbucket", {
      blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
      encryption: s3.BucketEncryption.KMS_MANAGED,
    });

    const delimiter_handler = new lambda.Function(this, "delimiter_handler",{
      runtime: lambda.Runtime.NODEJS_12_X,
      code: lambda.Code.asset("resources"),
      handler: "delimiter_handler.handler",
      environment: {
        BUCKET: mailbucket.bucketName,
      },
    });
    mailbucket.grantReadWrite(delimiter_handler);
}
```

### What did you expect to happen?

I would expect that to set the bucket policy up correctly. 

### What actually happened?

I have a blank S3 bucket policy. 

### Environment
I am on an Ubuntu Focal machine running node v12.18.4 with
dpkg -l | grep -i typescript
ii  node-typescript                        3.8.3-1                             all          TypeScript is a language for application scale JavaScript development
cdk --version
1.64.1 (build 14a8c8d)

### Other

--- 

This is :bug: Bug Report

**Comment by lschierer** [comment]
actually I'm not sure how much of that environment is relevant because while it is my local dev environment, the stack is actually synthesized by codebuild in a aws/codebuild/standard:4.0 environment

**Comment by lschierer** [comment]
after playing around a lot, it is not the s3 bucket policy being blank that is causing the access denies, but rather that the objects in it are encrypted (per the snippet I included originally).  The grant to readWrite is not detecting that, and thus not granting me permissions to the key.

**Comment by iliapolo** [comment]
Looks like the `grant` method only considers encryption when an explicit key is passed:

https://github.com/aws/aws-cdk/blob/d95af009a8d59393d019620aa8878098ce0aed1d/packages/%40aws-cdk/aws-s3/lib/bucket.ts#L658-L660

It does not handle the case where an AWS Managed CMK is used by using the `KMS_MANAGED` encryption type.

**Comment by otaviomacedo** [comment]
Hi, @lschierer 

Are you sure the permission denied you're getting is because of the lack of permissions to the key? I managed to deploy your example, pointing to a lambda handler that reads an object from the bucket and returns its contents. Everything worked fine.
