### ISSUE TITLE
[cli] Pause deploy on permission denied

### ISSUE THREAD

**Issue by kpeters-cbsi** [aws/aws-cdk#10543]
This may be better requested of CloudFormation rather than CDK, but I'm experiencing it in CDK, so I'll put it here.

It would be lovely if there were an option to, when CDK encountered a "permission denied" or similar error, deployment could be paused to give the user a chance to rectify the error rather than the whole stack failing deployment and being rolled back.

### Use Case

If a permission issue is encountered during deployment, the user must wait for the stack to be rolled back before they can try deploying again. This wastes time needlessly.

### Proposed Solution

If this option is passed and CDK deploy encounters an error, the user would be presented with an option to retry the operation or cancel deployment. The process would block until receiving a response from the user. During that time, the user could attempt to correct the problem and then choose to continue, in which case the failed operation would be retried, or to cancel, in which case the stack would be rolled back.

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
I believe there is an option in CFN to not rollback the deployment if it encounters an error. I would assume that this has an API to continue where it left off, but I'm not sure about all the implications of that.

I would welcome a contribution in this area, but it's unlikely we will address this ourselves.
