### ISSUE TITLE
Terraform language support

### ISSUE THREAD

**Issue by colinjfw** [aws/aws-cdk#10565]
Terraform has it's own configuration language that (in my understanding) is sufficient enough to cover being a frontend for CDK. Terraform resources could map to a CDK construct which outputs CloudFormation on the backend. Although this is a bit of an unconventional use case to put this on top of CloudFormation I am curious if the CDK team has considered this.

### Use Case

The main advantages over using Terraform from current CDK supported languages:

1. Limited configuration specific featureset: You won't have developers hitting typescript specific bugs when building modules.
1. Great diff support in Terraform out of the box.
1. Well known among the community.

### Proposed Solution

My understanding of CDK is that it allows other languages to plug in to the construct backend via a JSII interface. Theoretically, if Golang support is implemented, Terraform could plug directly into CDK via JSII. A Terraform resource could map directly to a CDK construct.

I'm guessing that this is probably a long shot to go onto the CDK roadmap. I'm mainly opening an issue because I really love the Terraform configuration language, find it very productive to work in and am curious if that can be married somehow to CDK constructs.

Thanks in advance for considering.

* [x] :wave: I may be able to implement this feature request
* [X] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by doug-ferris** [comment]
Have you looked into https://github.com/hashicorp/terraform-cdk?
