### ISSUE TITLE
Workshop request: real-world configuration

### ISSUE THREAD

**Issue by rix0rrr** [aws/aws-cdk#1056]
During the intro workshop we were asked for a more in-depth lab on configuring apps for different environments and writing conditional logic. Fair enough! I think this lab should treat:

* Environments
* Per-environment configuration
* When to use SSMPS
* importing existing resources 
* `Resource` vs `IResource` (vs `ResourceRef`, soon to be deprecated)
* CI/CD

It will be a good forcing function for ourselves to get answers to these questions.

**Comment by IPyandy** [comment]
How about especially for now since there isn't an L2 construct for everything. When to use L1 vs L2 construct? Or when to even expand on an existing one if necessary?

**Comment by NGL321** [comment]
_Closing for now since Workshop and examples are maintained in a different repo_
