### ISSUE TITLE
[codebuild] can’t change custom image to amazon curated image of project 

### ISSUE THREAD

**Issue by zxkane** [aws/aws-cdk#10569]
Create a codebuild project like below, 

```ts
const prj = new codebuild.Project(this, `project`, {
      source: codebuild.Source.gitHub({
        owner: 'tuna',
        repo: 'opentuna',
        cloneDepth: 1,
        branchOrRef: 'master',
      }),
      environment: {
        // uncomment below line to update the build image from node:12-buster
        // buildImage: codebuild.LinuxBuildImage.AMAZON_LINUX_2_3,
        buildImage: codebuild.LinuxBuildImage.fromDockerRegistry('node:12-buster'),
        privileged: true,
        computeType: codebuild.ComputeType.SMALL,
      },
      buildSpec: codebuild.BuildSpec.fromObject({
        version: '0.2',
        phases: {
          install: {
            'runtime-versions': {
              nodejs: 12
            },
            commands: [
              'npm ci',
            ],
          },
          build: {
            commands: [
              'npm i aws-cdk'
            ],
          },
        },
      })
    });
```
Failed on updating the build image from docker image `node:12-buster` to Amazon Linux 2.3.

### Reproduction Steps

see above

### What actually happened?

```
6:19:27 PM | UPDATE_FAILED        | AWS::CodeBuild::Project | projectC7BA6BD1
Failed to call UpdateProject, reason: Invalid input: cannot use a CodeBuild curated image with imagePullCredentialsType SERVICE_ROLE (Service:
[██████████████████████████████████████▋···················] (2/3)
 
6:19:27 PM | UPDATE_FAILED        | AWS::CodeBuild::Project | project
Failed to call UpdateProject, reason: Invalid input: cannot use a CodeBuild curated image with imagePullCredentialsType SERVICE_ROLE (Service:
AWSCodeBuild; Status Code: 400; Error Code: InvalidInputException; Request ID: e17bc52c-5147-4276-a652-e8fbf5407319; Proxy: null)
6:19:28 PM | UPDATE_ROLLBACK_IN_P | AWS::CloudFormation::Stack | CodebuildChangeImageTypeBugStack
The following resource(s) failed to update: [projectC7BA6BD1].
```

### Environment

  - **CLI Version      :** 1.64.1
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):** 

### Other

There is a same report https://github.com/aws/aws-codebuild-docker-images/issues/163 already.

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hey @zxkane ,

thanks for opening the issue. Can you try and replace the line

```ts
        buildImage: codebuild.LinuxBuildImage.fromDockerRegistry('node:12-buster'),
```

in your code with 

```ts
        buildImage: codebuild.LinuxBuildImage.fromCodeBuildImageId('node:12-buster'),
```

, and see if that helps?

Thanks,
Adam

**Comment by zxkane** [comment]
It works well when changing from `buildImage: codebuild.LinuxBuildImage.fromCodeBuildImageId('node:12-buster'),` to `uildImage: codebuild.LinuxBuildImage.AMAZON_LINUX_2_3,`.

**Comment by skinny85** [comment]
What error do you get with `codebuild.LinuxBuildImage.fromCodeBuildImageId('node:12-buster')`?

**Comment by zxkane** [comment]
Only getting below error updating image of CodeBuild project from `buildImage: codebuild.LinuxBuildImage.fromDockerRegistry('node:12-buster'),` to `buildImage: codebuild.LinuxBuildImage.AMAZON_LINUX_2_3`.

> CodebuildChangeImageTypeBugStack: creating CloudFormation changeset...
12:09:11 AM | UPDATE_FAILED        | AWS::CodeBuild::Project | projectC7BA6BD1
Failed to call UpdateProject, reason: Invalid input: cannot use a CodeBuild curated image with imagePullCredentialsType SERVICE_ROLE (Service:

**Comment by skinny85** [comment]
Then can you please update it to `codebuild.LinuxBuildImage.fromCodeBuildImageId('node:12-buster')`...?

**Comment by zxkane** [comment]
I had workaround to resolve the error when updating build image of my CodeBuild project.

It’s caused by CodeBuild using different service roles for CodeBuild managed images or external images. I think L2 construct should handle with the implicit service role changed base on the image specified.

I’m not sure what’s the difference between `LinuxBuildImage.fromCodeBuildImageId` and `LinuxBuildImage.fromDockerRegistry`. Is `LinuxBuildImage.fromCodeBuildImageId` a proxy of all images in docker.io registry? If so, should we deprecate the `fromDockerRegistry` by `fromCodeBuildImageId`?

**Comment by skinny85** [comment]
I'm not sure what you're asking...

Did specifying `codebuild.LinuxBuildImage.fromCodeBuildImageId('node:12-buster')` work?

**Comment by zxkane** [comment]
Yes.  Using `codebuild.LinuxBuildImage.fromCodeBuildImageId('node:12-buster')` works.

But `codebuild.LinuxBuildImage.fromDockerRegistry('node:12-buster')` also is a public API, and it’s a more intuitive API when using an image from docker.io for the CodeBuild project. Then the user will fail to deploy the stack after updating the build image to a CodeBuild managed image. That’s why I reported it as a bug due to L2 of CodeBuild construct can not properly handle with the service role changing when changing the build image.

**Comment by skinny85** [comment]
I don't think this is a CDK problem - I think it's because the name of that image (`node:12-buster`) is recognized by CodeBuild as one of their curated images (see here: https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-available.html ), and that's why you need to use `fromCodeBuildImageId()`, and not `fromDockerRegistry()`.

**Comment by zxkane** [comment]
I don’t think so. Following the doc link you gave, the name of curated image of CodeBuild starts with `aws/codebuild/` via the command `aws codebuild list-curated-environment-images`.

I think the error is caused by the generated CloudFormation using the implicit default value `CODEBUILD` for [Environment. ImagePullCredentialsType](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-environment.html#cfn-codebuild-project-environment-imagepullcredentialstype) when using `fromCodeBuildImageId ` and `LinuxBuildImage.AMAZON_LINUX_2_3`.

When the project uses image from docker.io, the `Environment. ImagePullCredentialsType` is set as `SERVICE_ROLE` what it’s expected. Looks like the CloudFormation runtime will assume the value of `Environment. ImagePullCredentialsType` not changed when updating the `Environment. Image` without explicitly updating `Environment. ImagePullCredentialsType` accordingly. That’s why I got the deployment error reported above.

**Comment by skinny85** [comment]
I'm pretty sure that's an error with the CodeBuild API then... if you can create a new Stack, and `fromDockerRegistry('node:12-buster')` works fine for it, then that means CodeBuild does not correctly handle edits in its API (we've had this reported before).

In either case, I don't see what the CDK can do here.

**Comment by zxkane** [comment]
The `LinuxBuildImage` already has the `imagePullPrincipalType` field. Why not always generating the `ImagePullCredentialsType` when synthesizing LinuxBuildImage?

Currently the CloudFormation template looks like below when synthesizing `LinuxBuildImage.fromCodeBuildImageId('node:12-buster')`
```yaml
Type: AWS::CodeBuild::Project
    Properties:
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: node:12-buster
        PrivilegedMode: true
        Type: LINUX_CONTAINER
```
CloudFormation template is generated like below when synthesizing `LinuxBuildImage.fromDockerRegistry('node:12-buster')`
```yaml
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: node:12-buster
        ImagePullCredentialsType: SERVICE_ROLE
        PrivilegedMode: true
        Type: LINUX_CONTAINER
```

For the public image hosting by docker.io, either `SERVICE_ROLE` or `CODEBUILD` works.

**Comment by skinny85** [comment]
> The `LinuxBuildImage` already has the `imagePullPrincipalType` field. Why not always generating the `ImagePullCredentialsType` when synthesizing LinuxBuildImage?

Because `CODEBUILD` is the default value for `ImagePullCredentialsType`, so there is no point in setting it (we don't set properties in the CDK explicitly to their default values, as it's redundant).

**Comment by zxkane** [comment]
> > The `LinuxBuildImage` already has the `imagePullPrincipalType` field. Why not always generating the `ImagePullCredentialsType` when synthesizing LinuxBuildImage?
> 
> Because `CODEBUILD` is the default value for `ImagePullCredentialsType`, so there is no point in setting it (we don't set properties in the CDK explicitly to their default values, as it's redundant).

You’re right. It’s redundant for specifying the default value. I double checked the doc of [ImagePullCredentialsType](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-environment.html#cfn-codebuild-project-environment-imagepullcredentialstype), the doc just declares the two possible values of the property and the field is not required. But looks like none of two possible values is the default value, I can not get the info `CODEBUILD` is default value from the doc.
