### ISSUE TITLE
[docs] Universal reference doesn't contain deprecation message

### ISSUE THREAD

**Issue by aripalo** [aws/aws-cdk#10563]
AWS CDK documentation [on Aspects](https://docs.aws.amazon.com/cdk/latest/guide/aspects.html#aspects_example) uses `node.addError` method:
```ts
node.node.addError('Bucket versioning is not enabled');
```

… but the  [API documentation for `ConstructNode`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.ConstructNode.html#add-wbr-errormessage-span-class-api-icon-api-icon-deprecated-title-this-api-element-is-deprecated-its-use-is-not-recommended-span) states that `addError` is `DEPRECATED`:
> _This API element is deprecated. Its use is not recommended._

I'd like to know what is the correct way to error (i.e. fail synth) with Aspects (and also with custom constructs)? Just `throw new Error("...")` … or?

---

This is a 📕 documentation issue *and/or* generic question.

**Comment by rix0rrr** [comment]
It's `Annotations.of(construct).addError()`

**Comment by Jerry-AWS** [comment]
I have an issue over in the Guide repo about this (both tags and aspects have new APIs): https://github.com/awsdocs/aws-cdk-guide/issues/259

Should get to it soon. The deprecated way will continue to work until CDK v2.

I'm going to close this issue; follow the one in the Guide repo.
