### ISSUE TITLE
[aws-glue] "glue:GetTableVersion" permission missing in read permissions

### ISSUE THREAD

**Issue by warrify** [aws/aws-cdk#10577]
When using `table.grantRead(...)` the ["glue:GetTableVersion"](https://docs.aws.amazon.com/glue/latest/dg/aws-glue-api-catalog-tables.html#aws-glue-api-catalog-tables-GetTableVersion) permission is missing.

### Reproduction Steps

1. create an iam Role 
2. create a glue table
3. use `table.grantRead(role)`
4. see CloudFormation Template

### What did you expect to happen?

The "glue:GetTableVersion" should be included since it is required by e.g. firehose with format cob

### Environment

  - **CLI Version      :** 1.64.1
  - **Framework Version:** 1.64.1
  - **Node.js Version:** 14.3.0
  - **OS               :** MacOs
  - **Language (Version):** TypeScript 4.0.2

### Other

It should be updated [here](https://github.com/aws/aws-cdk/blob/fb39803b62bbd0ff62bf421464559c759ef0a923/packages/%40aws-cdk/aws-glue/lib/table.ts#L397)

--- 

This is :bug: Bug Report

**Comment by abury** [comment]
Has this popped back up in the v2 alpha build of @aws-cdk/aws-glue-alpha? I'm seeing this issue again.
