### ISSUE TITLE
[elbv2 targets] add example to docs

### ISSUE THREAD

**Issue by rahejaps** [aws/aws-cdk#10578]
link to reference doc page: https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_elasticloadbalancingv2_targets.html

Can you please assist in updating the documents with an example of the usage?  

I am unable to get my existing EC2's attached to the Network Load Balancer.  A similar issue was documented #5256, unfortunately the author did not provide the working solution. 

---

This is a 📕 documentation issue

**Comment by njlynch** [comment]
If you click on the "Package Overview" link in the docs you linked to, it will take you to the (badly formatted) README of the aws_elasticloadbalancingv2_targets package, which points to the main ELBv2 README for usage:
https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_elasticloadbalancingv2.README.html#targets-and-target-groups

This covers the `add_targets` method with some examples; although there are no examples specifically with EC2 instances, the patterns are the same. It looks like from #5256 you got this working. I can keep this issue open though for adding an instance-specific example to the README.
