### ISSUE TITLE
[aws-dynamodb] 

### ISSUE THREAD

**Issue by martzcodes** [aws/aws-cdk#10576]
When deploying a _removal_ of the `timeToLiveAttribute` in dynamodb it does not disable it for the table.

### Reproduction Steps

Deploy a table with `timeToLiveAttribute` set to something
Deploy an update to that table with `timeToLiveAttribute` removed.
In AWS Console the `timeToLiveAttribute` will still be set and enabled.

### What did you expect to happen?

I expected `timeToLiveAttribute` it to be disabled

### What actually happened?

AWS Console shows the time to live attribute as being set and enabled.

### Environment

Node: 12.6.1
@aws-cdk/*: 1.63.0

### Other

I'm happy to provide additional details or a reproduction repo, but I thought this was a fairly straightforward example.

--- 

This is :bug: Bug Report

**Comment by rrhodes** [comment]
Hi @martzcodes,

Following your steps, I observe the same behaviour, but note that AWS provides the following warning:

> Disabling TTL can take up to 1 hour to apply across all partitions, and you will not be able to re-enable TTL until this action is complete. During this time, the current TTL policy may still be active on partitions that have not yet received the update.

Looking at the generated CloudFormation change set, I see:

```
[
  {
    "resourceChange": {
      "logicalResourceId": "TableCD117FA1",
      "action": "Modify",
      "physicalResourceId": "TestStack-TableCD117FA1-1ALCE6LJZITHN",
      "resourceType": "AWS::DynamoDB::Table",
      "replacement": "False",
      "moduleInfo": null,
      "details": [
        {
          "target": {
            "name": "TimeToLiveSpecification",
            "requiresRecreation": "Never",
            "attribute": "Properties"
          },
          "causingEntity": null,
          "evaluation": "Static",
          "changeSource": "DirectModification"
        }
      ],
      "scope": [
        "Properties"
      ]
    },
    "type": "Resource"
  }
]
```

CDK appears to have worked as expected, changing the CloudFormation template to set TTL to false. I suspect the update has been applied, but TTL remains active until changes are propagated to all partitions in the table. Can you confirm whether or not your TTL remains active one hour after applying the update?

**Comment by skinny85** [comment]
Thanks so much for that answer @rrhodes !

@martzcodes can you confrim?
