### ISSUE TITLE
[rds] invalid default username when using Aurora PostgresSql

### ISSUE THREAD

**Issue by shivlaks** [aws/aws-cdk#10579]
We recently added a property `credentials` to represent the master username and password.
It's an optional property with a default value of `admin` for the username.

### Reproduction Steps

```ts
const cluster = new rds.DatabaseCluster(this, 'Database', {
      engine: rds.DatabaseClusterEngine.AURORA_POSTGRESQL,
      instanceProps: {
        instanceType: ec2.InstanceType.of(ec2.InstanceClass.T3, ec2.InstanceSize.MEDIUM),
        vpc,
        vpcSubnets: { subnetType: ec2.SubnetType.PRIVATE },
      },
      defaultDatabaseName: 'database123',
      parameterGroup: rds.ParameterGroup.fromParameterGroupName(this, 'ParameterGroup', 'default.aurora-postgresql11'),
      instances: 1,
      s3ImportBuckets: [importBucket], 
    });
```

### What did you expect to happen?

Successful deployment when using default property for master username and password.
Specifying 

### What actually happened?

```console
MasterUsername admin cannot be used as it is a reserved word used by the engine
(Service: AmazonRDS; Status Code: 400; Error Code: InvalidParameterValue; Request ID: 37defeec-5b54-4541-ac05-6b5e92412ab2; Proxy: null)
```

### Environment

  - **CLI Version      : 1.63.0**
  - **Framework Version:**
  - **Node.js Version:** v14.8.0
  - **OS               :** Mac OS 10.15.6
  - **Language (Version):** TypeScript (3.8.3) 

### Other

--- 

This is :bug: Bug Report

**Comment by jogold** [comment]
https://github.com/aws/aws-cdk/pull/5076

**Comment by skinny85** [comment]
Thanks @jogold , sometimes we don't learn 😉.

I'll be working on a fix for this today.
