### ISSUE TITLE
[ec2] (design): Private DNS support for VPC endpoint services

### ISSUE THREAD

**Issue by flemjame-at-amazon** [aws/aws-cdk#10580]
https://aws.amazon.com/premiumsupport/knowledge-center/vpc-private-dns-name-endpoint-service/
https://docs.aws.amazon.com/vpc/latest/userguide/verify-domains.html

## :question: General Issue

AWS added the ability to specify a custom DNS name for an endpoint service earlier this year. It makes it so your clients don't have to create aliases for an InterfaceVpcEndpoint when they connect to your service. This reduces undifferentiated lifting done by clients. I'd like to add support for this to CDK.

### The Question

The steps for setting it up involve creating Route53 records in a public hosted zone. I had intended it to be used like so:

```ts
new VpcEndpointService(this, 'EndpointService', {
  vpcEndpointServiceLoadBalancers: [networkLoadBalancer1, networkLoadBalancer2],
  acceptanceRequired: true,
  whitelistedPrincipals: [new ArnPrincipal('arn:aws:iam::123456789012:root')],
  privateDns: {
    privateDnsName: "my-service.mydomain.com",
    hostedZone: myHostedZone
  }
});
```

However this isn't possible -- the route53 module depends on the ec2 module, so I cannot add this feature to the VpcEndpointService construct without creating a circular dependency.

How can I get around this dependency? Would you recommend a different approach?

### Environment

  - **CDK CLI Version:** 1.64.1
  - **Module Version:** 1.64.1
  - **Node.js Version:** all
  - **OS:** all
  - **Language (Version):** all

**Comment by rix0rrr** [comment]
Oh, well that is not nice :(

**Comment by flemjame-at-amazon** [comment]
@rix0rrr do you think this would belong in the route53 module, or route53-patterns? Or something else?

**Comment by rix0rrr** [comment]
Feels like something that should be in `route53`.

**Comment by flemjame-at-amazon** [comment]
Will move to route53
