### ISSUE TITLE
[core] Expose CloudFormation Resource Specification through CDK

### ISSUE THREAD

**Issue by ungood** [aws/aws-cdk#10581]
It would be nice if CDK would provide some way to reflect upon L1 Constructs, effectively exposing the underlying [CloudFormation Resource Specification](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html) that they are generated from.

### Use Case

My use case for this is for developing a CDK Linter that detects certain kinds of issues with CDK templates.  One rule that I'm developing uses Jest's snapshot testing to detect - at build-time - whether a changes, compared to checked-in snapshot files are going to cause a resource to be replaced.  In order to do that, I want to limit my snapshots to only properties that might cause resource replacement - which I could get from the UpdateType of properties in a resource.

### Proposed Solution

I want to do something like:

```
if(node instanceof CfnResource) {
   node.resourceType.properties.forEach((propertyKey, propertySchema) => {
      if(propertySchema.updateType == "Conditional" || propertySchema.updateType == "Immutable") {
          // add node[propertyKey] to snapshot, so that we can detect if it changes.
      }
   });
}
```

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
You can try using the `@aws-cdk/cfnspec` module, though we consider it an implementation detail and are not guaranteeing API stability.
