### ISSUE TITLE
[certificate-manager] Can't Tag with "DnsValidatedCertificate" construct

### ISSUE THREAD

**Issue by Cloudrage** [aws/aws-cdk#10594]
### The Question
When creating a Certificate with **DnsValidatedCertificate**, Tag seem to have troubles :
![image](https://user-images.githubusercontent.com/30436750/94595432-1f134b80-028b-11eb-9456-aae16a35e05f.png)

Adding Tag with, for example :
`Tags.of(Certificate).add('Name', 'cmc-' + AppName + '-' + AppEnv);`

Same with deprecated Method : 
`Tag.add(Certificate, 'Name', 'cmc-' + AppName + '-' + AppEnv);`

**Comment by njlynch** [comment]
The `DnsValidatedCertificate` creates a custom resource, which then does the actual creation of the ACM certificate. Currently, these tags are not being propagated from the custom resource itself to the resulting certificate. This is a request we've had before (#6561) but ended up resolving as the original requester didn't need the functionality anymore.

If you don't need the cross-region functionality of the `DnsValidatedCertificate`, I'd advise switching to the main `Certificate` construct, which does support tagging appropriately.

**Comment by Cloudrage** [comment]
Thanks @njlynch .
Going back to `Certificate` construct then.
