### ISSUE TITLE
[core] Same stack names in different accounts

### ISSUE THREAD

**Issue by jonb-ifit** [aws/aws-cdk#10592]
I would like to deploy the same stack name to two different accounts

### Use Case

It makes more sense to me than trying to make stack names unique org-wide. Also, I have stacks already deployed to multiple accounts that I would like to move into CDK.

### Proposed Solution

I would be ok if the logical name of the stack is unique org wide and still generated separate template files, but the manifest file could define the stack name:

```
    "my-cross-account-stack-dev": {
      "type": "aws:cloudformation:stack",
      "environment": "aws://dev-account-id/unknown-region",
      "stackName": "my-cross-account-stack",
      "properties": {
        "templateFile": "my-cross-account-stack-dev.template.json"
      },
```

### Other

I read through this issue https://github.com/aws/aws-cdk/issues/3401 and this issue https://github.com/aws/aws-cdk/issues/3322 and ultimately that would be the goal. I would like to be able to seamlessly deploy across multiple accounts with the cli.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by jonb-ifit** [comment]
An example of how I might expect this to work. Definitely open to suggestions:
```ts
new MyStack(app, "my-stack-dev", {
  stackName: "my-stack",
  env: { account: devAccountId }
}, { myEnvProp: 'dev' });
new MyStack(app, "my-stack-production", {
  stackName: "my-stack",
  env: { account: devAccountId }
}, { myEnvProp: 'production' })
```

**Comment by NetaNir** [comment]
The CDK does support `stackName` as a stack property:

```ts
new MyStack(app, 'StackId', {
  env: {
    account: '',
    region: 'us-west-1'
  },
  stackName: 'CoolStack'
})
```

**Comment by jonb-ifit** [comment]
@NetaNir Please see the example I gave in my previous comment. I'm proposing the ability to create two stacks with the same name that could deploy to two separate accounts. So, while the property exists, it doesn't do what I'm proposing:
```
new MyStack(app, 'StackId', {
  env: {
    account: '',
    region: 'us-west-1'
  },
  stackName: 'CoolStack'
})
new MyStack(app, 'StackId2', {
  env: {
    account: '',
    region: 'us-west-2'
  },
  stackName: 'CoolStack'
})
```

will synthesize a single file named `CoolStack.template.json`. If it synthesized files based on their logical ids, i.e. StackId.template.json and StackId2.template.json, and the manifest.json supported this as well, then it would do what I'm proposing.

But currently, it does not.

**Comment by NetaNir** [comment]
It will synthesized two files - `StackId.template.json` and `StackId2.template.json`.

**Comment by jonb-ifit** [comment]
I just tested this against version `1.64.1 (build 14a8c8d)`

```ts
new MyStack(app, "my-stack-01", {
  env: { region: "us-east-1" },
  stackName: "my-stack",
});
new MyStack(app, "my-stack-02", {
  env: { region: "us-east-2" },
  stackName: "my-stack",
})
```
This is the output from `cdk synth`
```
> cdk synth
Successfully synthesized to /Users/xxx/projects/cdk-project/cdk.out
Supply a stack id (my-stack) to display its template.
```
It only generated one file: my-stack.template.json

The manifest file only has one entry based on the stack name, not the stack id:

```json
{
"my-stack": {
      "type": "aws:cloudformation:stack",
      "environment": "aws://unknown-account/us-east-2",
      "properties": {
        "templateFile": "my-stack.template.json"
      }
}
```

**Comment by NetaNir** [comment]
I suggest checking your `cdk.json`, if you created your project with a **very** old version of the CDK you might not have this feature enabled in your application:
```
"@aws-cdk/core:enableStackNameDuplicates": "true"
```

But this was added in very early `1.x` version so I doubt this is the problem.

**Comment by jonb-ifit** [comment]
I added looked up that feature flag and added it to my cdk.json and this does work now. Thank you for pointing me to it.
