### ISSUE TITLE
[aws-eks] Support adding service accounts to imported clusters

### ISSUE THREAD

**Issue by aka-toxa** [aws/aws-cdk#10601]
it seems like ICluster interface doesn't have addServiceAccount function. So it's not possible to add service account to the existing cluster

### Reproduction Steps

```
    const cluster = Cluster.fromClusterAttributes(this, clusterName, {
      clusterName: clusterName,
      kubectlRoleArn: 'arn:aws:iam::1111111:role/iam-role-that-has-masters-access'
    });

    const serviceAccount = cluster.addServiceAccount(id);

    serviceAccount.addToPolicy(new PolicyStatement({
      resources: ["arn:aws:s3:::testBucket"],
      actions: [
          "HeadBucket",
          "ListAllMyBuckets",
          "ListBuckets"
      ]
    }))
```

### What did you expect to happen?

no error 

### What actually happened?

cluster.addServiceAccount is not a function

### Environment

  - **CLI Version      :1.64.1**
  - **Framework Version:1.63.0**
  - **Node.js Version:10.7.0** 
  - **OS               :macos**
  - **Language (Version):3.9.6** 

### Other

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment]
Adding Service Accounts to imported cluster is indeed currently unsupported. Marking this as a feature request.

**Comment by ayush987goyal** [comment]
The `ServiceAccount` construct requires a cluster of the type `Cluster` and not `ICluster`. It uses the `clusterOpenIdConnectIssuer` and `openIdConnectProvider` properties of a cluster which are not available on `ICluster`. Since the imported clusters are of the type `ICluster`, adding `ServiceAccount` to them will not be possible currently

**Comment by aka-toxa** [comment]
yeah, also inside the implementation I found that `fromClusterAttributes` actually return an instance of ImportedCluster class. which also don't have `addServiceAccount` method

**Comment by aka-toxa** [comment]
hi @iliapolo if you didn't start with the fix I can take care and prepare the PR. I just really need this one asap

**Comment by aka-toxa** [comment]
feel free to reassign it to me I will create the PR next week in case if you didn't start implementing

**Comment by ayush987goyal** [comment]
@aka-toxa I tried to prepare a PR for this issue but as mentioned in my previous comment, the limitation of `ICluster` is a blocker. How are you planning to implement it?

**Comment by aka-toxa** [comment]
can we import clusterOpenIdConnectIssuer and openIdConnectProvider from the cluster?

**Comment by aka-toxa** [comment]
deploy lambda that will import those fields from the cluster?

**Comment by aka-toxa** [comment]
or also we can provide those fields manually in `fromClusterAttributes` arguments (until better solution happen at least)

**Comment by aka-toxa** [comment]
is that just a matter for setting up of correct values for those two variables?

```
export class ClusterResource extends CoreConstruct {
...
  public readonly attrOpenIdConnectIssuerUrl: string;
  public readonly attrOpenIdConnectIssuer: string;
...
}
```

I think that we can require users to provide those two lines of strings manually for their cluster. To have partial IRSA support at least

**Comment by aka-toxa** [comment]
@ayush987goyal hi I've created the PR with the approach that I see should be fine. Can you please check it? and if it's ok i will refine it with unit tests and some documentation with examples
