### ISSUE TITLE
[apigateway] AddMethod POST using LambdaIntegration doesn't display on the AWS Console as expected. 

### ISSUE THREAD

**Issue by abocati** [aws/aws-cdk#10600]
Using `apigateway.LambdaIntegration` doesn't work as expected OR doesn't display as expected inside the API Gateway Console.

### Reproduction Steps

1. Create a POST method with `LambdaIntegration`.

```
      items.addMethod('POST', new apigateway.LambdaIntegration(lambdaHandler, {
        proxy: true
      }), {  
        authorizationType: apigateway.AuthorizationType.COGNITO,
        authorizer: { authorizerId: authorizer.ref },
        methodResponses: [{ 
          statusCode: '200', 
          responseParameters: {
            'method.response.header.Access-Control-Allow-Origin': true
          },
          responseModels: {
            'application/json': apigateway.Model.EMPTY_MODEL,
          }
        }]
      });
```

### What did you expect to happen?

When I open the API Gateway Console I was expecting to display under the POST method tab of my resource on "Method Response" as follow:

```
HTTP Status: Proxy
Models: application/json => Empty
```

**However it displays **empty****.

Now, If I open the API Gateway Console under my POST method, click in "Integration Request", **uncheck** "Use Lambda Proxy integration", click "Ok" to confirm, and then check again "Use Lambda Proxy integration" and confirm.

Now back under "Method Response" it will display as follows:

```
HTTP Status: Proxy
Models: application/json => Empty
```

### Environment

  - **CLI Version     aws-cli/1.16.173 Python/3.7.7 Darwin/19.6.0 botocore/1.12.163 :**
  - **Framework Version: 1.64.1**
  - **Node.js Version: v13.13.0** 
  - **OS               : Mac OS 10.15.6 (19G2021)**
  - **Language (Version): Typescript** 

### Other

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
Could you run `get-method-response` CLI in both these cases (one where it works for you and the other where you think the CDK is doing something wrong) and report back the responses?

**Comment by abocati** [comment]
Hi @nija-at. After comparing them using `get-method-response` and `get-integration`, I had to add to my LambdaIntegration the `integrationResponses` method with Access-Control-Allow-Origin:

```
      items.addMethod('POST', new apigateway.LambdaIntegration(lambdaHandler, {
        proxy: true,
        contentHandling: apigateway.ContentHandling.CONVERT_TO_TEXT, 
        integrationResponses: [{
            statusCode: '200',
            responseTemplates: {
              'application/json': ''
            },
            responseParameters: {
              'method.response.header.Access-Control-Allow-Origin': `'${env.CORS_ORIGIN!}'`,
            }
          }]
      }), {  
    ...
```

Now the **Method Response** displays correct:
 HTTP Status: Proxy
Models: application/json => Empty

This can be closed. Thank you.
