### ISSUE TITLE
Remove `test` directory from all published packages

### ISSUE THREAD

**Issue by andreialecu** [aws/aws-cdk#10602]
It appears that the `test` directory is part of the published npm packages for all `@aws-cdk` scoped packages. It appears to be only used for internal tests and it shouldn't be exposed.

### Use Case

It makes installation bigger, and wastes resources. Additionally, Yarn v2 has some heuristics that detect whether a package needs to be installed differently depending on whether some file extensions are present, and it is triggered by some packages such as `@aws-cdk/aws-s3-assets` and `aws-cdk` because the `test` directory contains files with `.jar` and `.sh` extensions.

### Proposed Solution

Add `files: ["lib"]` to each of the package's `package.json`.

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
I believe we do this on purpose, pinging @eladb to be sure.

As for the wasted space argument, can you quantify the amount of data we would save and the use case in which this is becoming significant for you?

**Comment by eladb** [comment]
The only place I am aware of that we are actually using this is in the CLI in order to be able to execute integration tests from a released version against new code (for backwards compatibility check). Generally speaking that could be good motivation to include tests in published modules but at the moment we are not utilizing those. I am fine with removing.

Copy @iliapolo

**Comment by andreialecu** [comment]
> As for the wasted space argument, can you quantify the amount of data we would save and the use case in which this is becoming significant for you?

This part is probably negligible. It's just a minor "leak", but depending on the number of installs world-wide it likely ends up "wasting" gigabytes of storage across all systems. `node_modules` caches on CI systems end up being slightly bigger, etc.

The main suboptimal aspect is that there are `.jar` files in npm packages and that can make some tools over-react to package contents. Might even trigger some anti-virus warnings in special circumstances I guess?

I guess the main point is that it's a good practice to only ship production code in NPM packages.

**Comment by rix0rrr** [comment]
Adding `./test` to all `.npmignore`s using `pkglint` (for packages that aren't `aws-cdk`) would be a way to achieve this.
