### ISSUE TITLE
[aws-ec2] expose NatGatewayId from VPC

### ISSUE THREAD

**Issue by jonny-rimek** [aws/aws-cdk#10616]
Expose NatGatewayId from the VPC construct.

### Use Case

I'm building a dashboard and need access to the NatGatewayId in order to access the metrics

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
You can assign `NatProvider` to an object and after instantiating the VPC read the `configuredGateways` property directly.

**Comment by jonny-rimek** [comment]
the solution looks like this.

```js
export class Vpc extends cdk.Construct {
	public readonly vpc: ec2.Vpc;
	public readonly natGateways: ec2.GatewayConfig[];

	constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
		super(scope, id)

		const nat = ec2.NatProvider.gateway()
		this.natGateways = nat.configuredGateways

		this.vpc = new ec2.Vpc(this, 'Vpc', {
			natGateways: 1,
			natGatewayProvider: nat,
			//gateway endpoint will lead to no datatransfer cost for s3 to vpc/NATgateway
			gatewayEndpoints: {
				S3: {
					service: ec2.GatewayVpcEndpointAwsService.S3,
				}
			}
		})
	}
}
```
