### ISSUE TITLE
[pipelines] Support securityGroups in SimpleSynthAction

### ISSUE THREAD

**Issue by nbaillie** [aws/aws-cdk#10621]
Add **securityGroups** as a prop on SimpleSynthAction to set the attached security groups for the action.

### Use Case

Security Groups are normally needed when working in a VPC. Right now you can add a SG after creating a SimpleSynthAction using:
```
actionProject = stageAction.project.node.defaultChild as CfnProject;
actionProject.addPropertyOverride('VpcConfig.SecurityGroupIds', ['<SGID>'])
```
This also leave a default SG that might not be need that was created by constructing the SimpleSynthAction.

Additionally, when working with the RDS constructs and others the option is there.

### Proposed Solution

const someStageAction = new ShellScriptAction({
      actionName: 'database.IntegrationTest',
      vpc: someVpc,
      subnetSelection: someVpc.selectSubnets({ subnetType: SubnetType.PRIVATE }),
      **securityGroups: [someSecurityGroup]**,
    });

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
Sounds good, I would accept a PR that adds this.
