### ISSUE TITLE
[apigatewayv2] Gateway Responses for HTTP APIs 

### ISSUE THREAD

**Issue by jonathan-kosgei** [aws/aws-cdk#10624]
Support for setting gateway responses for HTTP APIs like we can currently do for REST APIs.

### Use Case

I need to migrate a complex production REST API to HTTP. To be able to do so without breaking client applications I need to be able to return the same errors that are currently documented and used by clients and in our own integrations and language libraries.

We use the lambda custom authorizer to authorize API requests. When there is an auth failure or misconfiguration we currently send users a detailed error message to help them troubleshoot their issue.

I can currently do this via $context.authorizer.error with a REST API.

### Proposed Solution

I'm not sure how this should look for HTTP APIs but here is how I do it with REST APIs.

```
        api.add_gateway_response("access_denied_response",
            type=apigateway.ResponseType.ACCESS_DENIED,
            status_code="403",
            response_headers={
                "Access-Control-Allow-Origin": "'*'",
            },
            templates={
                "application/json": '{"message": "$context.authorizer.error"}'
            }
        )
```

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by AjkayAlan** [comment]
Looking at https://aws.amazon.com/blogs/compute/introducing-iam-and-lambda-authorizers-for-amazon-api-gateway-http-apis/, you may be able to at least return the response from your lambda authorizor using the v2 format:

```json
{
  "isAuthorized": true/false,
  "context": {
    "exampleKey": "exampleValue"
  }
}
```

Anything in context is accessible via `$context.authorizer.property`. Now, I definitely don't quite understand how you can then control what you return back to your caller from the auth response via your gateway (for instance, its not super clear to me if that auth response is returned to your caller, or sent to your actual API).

**Comment by jonathan-kosgei** [comment]
Auth errors would be returned to the caller, this is currently doable with REST APIs, see https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-gatewayResponse-definition.html

**Comment by nija-at** [comment]
@jonathan-kosgei - does this feature exist for HTTP APIs? I can't seem to find any documentation for this.

**Comment by jonathan-kosgei** [comment]
@nija-at I don't believe this is available in the console yet.

**Comment by nija-at** [comment]
AFACIT, This is not yet supported by HTTP APIs yet. Please open this or a new issue when the support has been added.
