### ISSUE TITLE
[aws-cognito] Cognito won't send verification email to verify new user email

### ISSUE THREAD

**Issue by apoorvmote** [aws/aws-cdk#10623]
Cognito won't send verification email to verify new user email.

### Reproduction Steps

```typescript
const authPool = new UserPool(this, 'myAuth', {
      userPoolName: 'my-auth',
      selfSignUpEnabled: true,
      signInAliases: {
        email: true
      },
      autoVerify: {
        email: false
      },
      standardAttributes: {
        email: {
          required: true,
          mutable: false
        }
      },
      passwordPolicy: {
        minLength: 12,
        requireSymbols: false
      },
      accountRecovery: AccountRecovery.EMAIL_ONLY
    })
```

### What did you expect to happen?
Each time user signs up then they should receive verification email

### What actually happened?
By going to aws console I found out the error 
see the screenshot below
![error - Imgur](https://user-images.githubusercontent.com/9799239/95827836-df9c3300-0d51-11eb-85fe-a5c3658cc55c.jpg)
If I manually change it to verify attribute email on aws console then it works as expected.

There is no options that says which attributes do you want to verify on aws-congnito cdk api.

### Environment

  - **CLI Version      :** 1.65.0
  - **Framework Version:**
  - **Node.js Version:**  12.18.4
  - **OS               :** Ubuntu 20.04
  - **Language (Version):** Typescript

### Other

--- 

This is :bug: Bug Report

**Comment by jukkasi** [comment]
I have exactly same problem, unable to set verification Email with settings described above.

 It is always "No verification" no matter what.

**Comment by nija-at** [comment]
> see the screenshot

The screenshot link doesn't work. Can you update the link?

**Comment by apoorvmote** [comment]
@nija-at Link updated with screenshot

**Comment by nija-at** [comment]
@apoorvmote - you've configured the `email` property under `autoVerify` to be `false`. This is consistent with what you're seeing on the console.

See the description [here](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cognito.UserPool.html#autoverify-span-class-api-icon-api-icon-experimental-title-this-api-element-is-experimental-it-may-change-without-notice-span).

**Comment by jukkasi** [comment]
If what you say is correct then "autoVerify" is very confusing term because I understand it so that these attributes are _automatically_ set to verified state when the user is created.

So "autoverify: email: false" means to me that user _manually_ needs to confirm this attribute, meaning that email is send by Cognito which then requires user interaction.

**Comment by nija-at** [comment]
@jukkasi - this is language taken from Cognito [documentation](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-email-phone-verification.html) - 

"Amazon Cognito can **automatically verify** email addresses or mobile phone numbers by sending a verification code—or, for email, a verification link."

The action 'auto' refers that Cognito should automatically verify the attribute.

**Comment by apoorvmote** [comment]
@nija-at Yes removing `autoVerify` fixed the issue. I am closing the issue. Please fix the language in documentation by making this more explicit.
