### ISSUE TITLE
[cli] CDKMetada resource warning

### ISSUE THREAD

**Issue by kyler-hyuna** [aws/aws-cdk#10625]
## :question: General Issue

Hey, I'm seeing this warning anytime I run a `diff` or `deploy` command. Is there any way to remove this warning?

```
The stack <stack-name> already includes a CDKMetadata resource
```

### Environment

  - **CDK CLI Version:** 1.65.0
  - **Module Version:** 1.65.0
  - **Node.js Version:** v14.9.0
  - **OS:** macOS Catalina
  - **Language (Version):** TypeScript (3.9.7)

**Comment by skyrpex** [comment]
I'm getting this as well, and can't generate generate the cloud formation YML without deleting the first line :thinking: 

I'm also using the same versions except for Typescript 4.0.3.

**Comment by abocati** [comment]
Getting this as well.

**Environment**
-     CDK CLI Version: 1.65.0
-     Module Version: 1.65.0
-     Node.js Version: v13.13.0
-     OS: macOS Catalina 10.15.6 (19G2021)
-     Language (Version): TypeScript (4.0.2)

**Comment by informity** [comment]
Getting the same thing:

#### Environment
- **CDK CLI Version:** 1.66.0 (build 459488d)
- **Module Version:** 1.65.0
- **Node.js Version:** v12.18.4
- **OS:** MacOS Catalina 10.15.6
- **Language (Version):** TypeScript (Version 4.0.3)

**Comment by colvint** [comment]
This line seems to be the source of the warning: https://github.com/aws/aws-cdk/blob/dfd2baf8b9d4cc930a1c5dc88c178ffe7d1121b0/packages/aws-cdk/lib/api/cxapp/cloud-executable.ts#L134

**Comment by rix0rrr** [comment]
That line is there because of an abundance of caution. I feel it can safely be removed.
