### ISSUE TITLE
[aws-ec2] 

### ISSUE THREAD

**Issue by lschierer** [aws/aws-cdk#10642]
I was attempting to codify the resources required by https://docs.aws.amazon.com/directoryservice/latest/admin-guide/seamlessly_join_linux_instance.html into a stack definition so that I can enforce my configuration as code.  However, it does not seem possible to actually do step 6d "For the Domain join directory, choose your domain from the list."  

This means that as I create each instance in CDK, it still comes up with only the default user for that AMI, and I need to either write custom scripts to run from user-data or I need to manually go in and run configuration commands to fully configure it for my environment before the host is usable.  

### Use Case
adding a linux host to a stack should cause that host to come up fully ready for use - including having its authentication provisioned so that an administrator need not ever used a shared account. 

### Proposed Solution

I think this is supported with cloudformation, but one of the things I like about CDK is that it provides constructs such that I do not have to fully figure out cloudfomrations' confusing json/yaml syntax.   If I'm right, and it can be done with cloudformation, then it should be something that CDK can do as well.  

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
You can probably achieve this using [`cfn-init`](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-ec2-readme.html#configuring-instances-using-cloudformation-init-cfn-init).

Also works for AutoScaling Groups if that's what you're using instead.
