### ISSUE TITLE
[aws-apigatewayv2]  Add support for resource attribute - ApiEndpoint 

### ISSUE THREAD

**Issue by shivlaks** [aws/aws-cdk#10651]
The import of CloudFormation resource specification `18.4` in #10493, `ApiGatewayv2` added 
a new attribute called [`ApiEndpoint`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigatewayv2-api.html#aws-resource-apigatewayv2-api-return-values)

This attribute is not currently exposed through our L2 construct.
A [linter exclusion](https://github.com/aws/aws-cdk/pull/10493/files#diff-e2ab9b5690004c653e58b072574ecf96R107) was added to avoid conflation of the feature into the same PR as the spec import.

This is a tracking issue to ensure we expose it (and get rid of the linter exclusion)

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by iRoachie** [comment]
@shivlaks I don't mind working on this 👋
