### ISSUE TITLE
[CDK Pipelines] cdkCliVersion parameter change no effect on "self-mutate-pipeline" step

### ISSUE THREAD

**Issue by SbgMartin** [aws/aws-cdk#10659]
In order to have **deterministic** build-infrastructure I set the **cdkCliVersion** of my **CdkPipeline** to the desired AWS CDK version. That works as expected. But, if I later decide to go to another version the “self-mutating-pipeline” step is not updated - it remains on the same version. This leads to the effect that I need to destroy the CdkPipelineStack and recreate it

`    const pipeline = new CdkPipeline(this, 'Pipeline', {
      pipelineName: 'GitOpsDemoInfraPipeline',
      cloudAssemblyArtifact,
      cdkCliVersion: '1.64.1'`

### Reproduction Steps

Just change the CDK Version from 1.64.1 to 1.65.0 - the self-mutating-pipeline step will fail then.

`    const pipeline = new CdkPipeline(this, 'Pipeline', {
      pipelineName: 'GitOpsDemoInfraPipeline',
      cloudAssemblyArtifact,
      cdkCliVersion: '1.65.0'`

### What did you expect to happen?

I expected that all resources which are provided along the CdkPipeline construct are updated, this includes the mentioned step, too.

### What actually happened?

Build step fails. You see in the execution logs, that still 

`npm install -g aws-cdk@1.64.1` is executed.

### Environment

  - **CLI Version      :** 1.64.1 and 1.65.0
  - **Framework Version:** 
  - **Node.js Version:** based on image version used by AWS CodeBuild instructed by AWS CDK Pipelines : aws/codebuild/standard:4.0
  - **OS               :** AWS CodeBuild image version : aws/codebuild/standard:4.0
  - **Language (Version):** TypeScript in use, but as it's a generic build step, all languages might be affected

### Other

--- 

This is :bug: Bug Report

**Comment by Drunk3nMonk3y** [comment]
Any changes to the CDK pipeline stack must be manually deployed before the self mutation picks it up from your source code after build succeeds.
