### ISSUE TITLE
[elbv2] Type ApplicationTargetGroup has separate declarations of private property 'connectableMembers' in elbv2 and codedeploy

### ISSUE THREAD

**Issue by banavalikar** [aws/aws-cdk#10653]
### The Question

I am getting the following error when assigning an ApplicationTargetGroup built for elbv2 to a CodeDeploy ServerDeploymentGroup loadBalancer property in a CDK app.

    const ssTg = ssListener.addTargets('ssTg', {   <-- elbv2.ApplicationListener
      port: 80,
      protocol: ApplicationProtocol.HTTP,
      targets: [ssAsg]
    });

    //CodeDeploy
    new Codedeploy.ServerDeploymentGroup(this, 'CodeDeploymentGroup', {
      loadBalancer: Codedeploy.LoadBalancer.application(ssTg)

    })

Argument of type 'import("../cdk-asg-loadbalancer/node_modules/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-target-group").ApplicationTargetGroup' is not assignable to parameter of type 'import("../cdk-asg-loadbalancer/node_modules/@aws-cdk/aws-codedeploy/node_modules/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-target-group").ApplicationTargetGroup'.
  Types have separate declarations of a private property 'connectableMembers'.ts(2345)

### Environment

  - **CDK CLI Version:**  1.64.1 (build 14a8c8d)
  - **Module Version:**  CodeDeploy ^1.65.0 ElbV2 ^1.64.1
  - **Node.js Version:**  v12.18.4
  - **OS:**  Windows 10
  - **Language:**  TypeScript

**Comment by njlynch** [comment]
This is a symptom of having two different versions of the CDK modules installed in the same project. You see from the error it's complaining the type of the ELBv2 ApplicationTargetGroup isn't compatible with the CodeDeploy version of the ELBv2 ApplicationTargetGroup. If you update all of your CDK modules to be consistent (e.g,. ^1.65.0), the error should go away.

**Comment by banavalikar** [comment]
Thanks @njlynch. Updating the modules resolved it.
