### ISSUE TITLE
[aws-codepipeline-actions] Failed to use template strings

### ISSUE THREAD

**Issue by geduld** [aws/aws-cdk#10665]
Template strings below did not work. It makes unintentional destroy. Should use buckticks instead of single quotes or just this.branch.

```typescript
      const branchIdDisambiguator = this.branch === 'master' ? '' : '-${this.branch}-';
```

c.f. #10463

### Reproduction Steps

```typescript
const sourceAction = new codePipelineActions.CodeCommitSourceAction({
    actionName: "CodeCommit",
    repository: repository,
    branch: "dev",  // This line
    output: output,
});
```

### What did you expect to happen?

```bash
$ cdk diff

(omitted)

Stack codecommit-dev
There were no differences
```

### What actually happened?

```bash
$ cdk diff

(omitted)

Resources
[-] AWS::Events::Rule codecommitdevAA3605ADdevEventRule842F00D6 destroy
[+] AWS::Events::Rule codecommit-dev/AA3605AD-${this.branch}-EventRule codecommitdevAA3605ADthisbranchEventRule42AF1F65
```

### Environment

  - **CLI Version      :** 1.66.0
  - **Framework Version:** 1.66.0
  - **Node.js Version:** v13.9.0
  - **OS               :** Ubuntu 18.04
  - **Language (Version):** TypeScript (4.0.3)

### Other

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Thanks for opening @geduld . Any chance of a PR fixing this? 🙂 Here's our contribution docs: https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md .

**Comment by geduld** [comment]
@skinny85 Does the PR really need to write a test to change from single quotes to buckticks?

**Comment by skinny85** [comment]
A test would be ideal, but I'll accept a PR without it 🙂
