### ISSUE TITLE
[aws-lambda-nodejs] Bundling - Packages not installed

### ISSUE THREAD

**Issue by AlexCheema** [aws/aws-cdk#10677]
Bundling should first run `npm install` then parcel bundle.

### Reproduction Steps

- Have a dependency in your `package.json` file in your lambda
- Create a new `NodejsFunction` in your cdk app
- You will see this error:
```
Bundling asset testAuthStack/OIDCConfig/PutPublicKeysLambda/Code/Stage...
Building index.ts...
Building openid-configuration.template.json...
Building send-response.ts...
Building utils.js...
Building defaults.js...
Building bind.js...
Building Cancel.js...
Building CancelToken.js...
Building spread.js...
Building Axios.js...
Building isCancel.js...
🚨 Build failed.
@parcel/core: Failed to resolve 'node-jose' from './src/index.ts'
/asset-input/lambdas/put-public-keys/src/index.ts:3:18
  2 | import { KMS, S3 } from "aws-sdk";
> 3 | import jose from "node-jose";
>   |                  ^^^^^^^^^^^
  4 | import configTemplate from "./openid-configuration.template.json";
  5 | import { sendResponse } from "./send-response";
Failed to bundle asset testAuthStack/OIDCConfig/PutPublicKeysLambda/Code/Stage, bundle output is located at /home/cheema/auth/cdk.out/bundling-temp-wHFE6i-error: Error: docker exited with status 1
```

### What did you expect to happen?

I would expect `NodeJsLambda` to first run `npm install` in the lambda directory, then bundle the lambda using parcel. It seems like this is currently happening the opposite way round: https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-lambda-nodejs/lib/bundlers.ts#L178

### Environment

  - **CLI Version      :** 1.66.0
  - **Framework Version:** 1.66.0
  - **Node.js Version:** 14.9.0 
  - **OS               :** Ubuntu 18.04
  - **Language (Version):** TypeScript (3.8.3)

--- 

This is :bug: Bug Report

**Comment by eladb** [comment]
@jogold correct me if I am wrong but I believe the current behavior is intentional. The expectation is that the dependencies are already installed by the user before the CDK app is executed, and therefore there is no need to re run `npm install` during bundling.

**Comment by jogold** [comment]
> I believe the current behavior is intentional.

@eladb Yes, it is.


> It seems like this is currently happening the opposite way round: https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-lambda-nodejs/lib/bundlers.ts#L178

@AlexCheema this is the installation of packages that are not bundled with Parcel (`nodeModules` prop).


@AlexCheema is this for a multiple programming languages CDK project?

**Comment by eladb** [comment]
Closing for now
