### ISSUE TITLE
[aws-ec2] shellCommand Windows 

### ISSUE THREAD

**Issue by sd3z** [aws/aws-cdk#10684]
When using the latest Windows AMI and using shellcommand the commands fail to run with 'The system cannot find the file specified'. 

### Reproduction Steps

```
ec2.InitCommand.argvCommand(['powershell.exe',` '-command "Set-ExecutionPolicy', 'RemoteSigned -Force"'], { key: "00_executionPolicy", waitAfterCompletion: ec2.InitCommandWaitDuration.none() }),
```

### What did you expect to happen?

The command to run successfully

### What actually happened?

The error reported was 
```

----- Error during cfn-init bootstrapping -----
ERROR] Unhandled exception during build: [Error 2] The system cannot find the file specified
Traceback (most recent call last):
  File "cfn-init", line 171, in <module>
  File "cfnbootstrap\construction.pyc", line 129, in build
  File "cfnbootstrap\construction.pyc", line 530, in build
  File "cfnbootstrap\construction.pyc", line 544, in run_config
  File "cfnbootstrap\construction.pyc", line 138, in run_commands
  File "cfnbootstrap\command_tool.pyc", line 108, in apply
  File "cfnbootstrap\util.pyc", line 497, in call
  File "cfnbootstrap\util.pyc", line 482, in call
  File "subprocess.pyc", line 710, in __init__
  File "subprocess.pyc", line 958, in _execute_child
WindowsError: [Error 2] The system cannot find the file specified
```

### Environment

  - **CLI Version      : 1.66**
  - **Framework Version: 1.66**
  - **Node.js Version: 10.x** 
  - **OS               : Windows 10**
  - **Language (Version): Typescript 4.0.2** 

### Other

I believe the issue is related to shell command outputting to a array with a single element.  According to the documentation [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-init.html#w2ab1c28c15c15c23c15b6) if an array is specified every command and parameter needs to be a new element (no whitespace) but if it is a string (as I think shellCommand prefers), it just needs to be a string, so 

### This will work 
```
commands:
  00_executionPolicy:
    command: powershell.exe -command "Set-ExecutionPolicy RemoteSigned -Force
    waitAfterCompletion: 0
```
### This will work 
```
commands:
  00_executionPolicy:
    command:
      - powershell.exe
      - -command
      - Set-ExecutionPolicy RemoteSigned -Force
    waitAfterCompletion: 0
```

### This will NOT work
```
commands:
  00_executionPolicy:
    command:
      - powershell.exe -command "Set-ExecutionPolicy RemoteSigned -Force"
    waitAfterCompletion: 0
```

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
I don't understand how the example you gave:

```ts
// (A)
ec2.InitCommand.argvCommand(['powershell.exe',` '-command "Set-ExecutionPolicy', 'RemoteSigned -Force"'], { key: "00_executionPolicy", waitAfterCompletion: ec2.InitCommandWaitDuration.none() }),
```

Would lead to this being rendered:

```
// (B)
    command:
      - powershell.exe -command "Set-ExecutionPolicy RemoteSigned -Force"
```

If anything, it should lead to this being rendered:

```
// (C)
    command:
      - powershell.exe 
      - -command "Set-ExecutionPolicy
      - RemoteSigned -Force"
```

And by the way, judging from the quotes I think you probably meant to do this:

```ts
ec2.InitCommand.argvCommand([
  'powershell.exe',
  '-command',
  'Set-ExecutionPolicy RemoteSigned -Force'
]);
```

I agree with you there's a bug in the implementation of shellCommand though.

**Comment by sd3z** [comment]
Oh sorry, you are right on the quotes being a little off. 

So to iterate the issue is purely around shellCommand, specifically when I do this
```
ec2.InitCommand.shellCommand('powershell.exe -command "Set-ExecutionPolicy RemoteSigned -Force"', { key: "00_executionPolicy", waitAfterCompletion: ec2.InitCommandWaitDuration.none() }),
```
i get this
```// (B)
    command:
      - powershell.exe -command "Set-ExecutionPolicy RemoteSigned -Force"
```

but it should be 
```
    command: powershell.exe -command "Set-ExecutionPolicy RemoteSigned -Force"
```
because within the cfn-init scripts, the "subprocess" Python library is used to invoke commands on the Windows command prompt. When a list of strings is specified in the "command" section, the underlying library attempts to run the entire string specified as a single command with no arguments. This will cause Windows to return an error since it attempts to search for a program with the name of 'powershell.exe -command "Set-ExecutionPolicy RemoteSigned -Force"' as opposed to just 'powershell.exe'.

I think argvCommand is good for Windows if it renders to a string too and not string[] with a single element as the same above was happening.
