### ISSUE TITLE
[aws-ecr-assets]  Create fixed ecr repo name

### ISSUE THREAD

**Issue by xcrezd** [aws/aws-cdk#10688]
aws-ecr-assets create fixed ecr repo name

### Reproduction Steps

```
 const asset = new ecrPatterns.DockerImageAsset(this, 'AppImage', {
            directory: path.join(__dirname,'../../../'),

            buildArgs: {
            },
        });
```

![Selection_006](https://user-images.githubusercontent.com/1153266/95048870-4e91e000-06f1-11eb-8ca3-1a63031b202b.png)

### What did you expect to happen?

ECR repo name related to stack or `AppImage`

### What actually happened?

ECR repo name is not generic `aws-cdk/assets`

### Environment

  - **CLI Version      :1.66
  - **Framework Version:1.66
  - **OS               :Ubuntu
  - **Language TypeScript (3.8.3) 

This is :bug: Bug Report

**Comment by eladb** [comment]
There's a single ECR repos for all docker assets in each environment in order to allow cross-environment deployments and CI/CD, the name of the asset ECR repo is governed by the bootstrapping process.

Docker assets are not designed to be consumed outside of CDK apps.
