### ISSUE TITLE
[api-gateway]   Errors in Example. 

### ISSUE THREAD

**Issue by mrpackethead** [aws/aws-cdk#10680]
Example code has errors. 

https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_apigateway.README.html#iam-based-authorizer

The example code has a couple of errors,  with the iam.PolicyStatement.  They look like issues with the automatic translation. 

```py
iam_user.attach_inline_policy(iam.Policy(self, "AllowBooks",
    statements=[
        iam.PolicyStatement(
            actions=["execute-api:Invoke"],
            effect=iam.Effect.Allow,                                          #  (1) should be  effect = iam.Effect.ALLOW
            resources=[get_books.method_arn()]                     # (2) should be resources = [ get_books.method_arn ]

(1) iam.Effect.Allow is not defined.. ALLOW needs to be capitalized
(2)  get_books.method_arn  is the attribute  its not a function to be called. 
```

---

This is a 📕 documentation issue

**Comment by nija-at** [comment]
#1 seems like an conversion error and I've opened an issue here - https://github.com/aws/jsii/issues/2113

#2 is not a conversion error. It's an error in source - https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-apigateway/README.md#iam-based-authorizer
