### ISSUE TITLE
[aws-lambda] EventSourceMappingOptions default values for Construct Props maxRecordAge

### ISSUE THREAD

**Issue by sekerjak** [aws/aws-cdk#10693]
Dear community,

I am interested in EventSourceMappingOptions, especially **max_record_age** parameter mentioned here https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_lambda/EventSourceMappingOptions.html and here https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-lambda.EventSourceMappingOptions.html. The documentation is mentioning following:

```
Type: Duration (optional, default: Duration.days(7))

The maximum age of a record that Lambda sends to a function for processing.

Valid Range:

Minimum value of 60 seconds
Maximum value of 7 days
```

BUT this documentation https://docs.aws.amazon.com/lambda/latest/dg/API_CreateEventSourceMapping.html is mentioning the following:

```
MaximumRecordAgeInSeconds
(Streams) Discard records older than the specified age. The default value is infinite (-1).

Type: Integer

Valid Range: Minimum value of 60. Maximum value of 604800.

Required: No
```

So I expected, that default value will be **7 days** and not **infinite** as it's mentioned above, so I tried following:

```
  fn = aws_lambda.Function(self.stack, "failing-lambda",
                                 code=aws_lambda.Code.from_inline(lambda_code),
                                 runtime=aws_lambda.Runtime.PYTHON_3_7,
                                 handler='index.failing_lambda',
                                 function_name=self.workspace.name_for("failing-lambda"),
                                 timeout=Duration.seconds(30)
                                 )

   fn.add_event_source_mapping(id="errout-mapping", event_source_arn=consumer.attr_consumer_arn,
                                    starting_position=aws_lambda.StartingPosition.LATEST,
                                    batch_size=500)
```

And when I opened Lambda Designer in AWS console I saw the following values:

```
Batch size: 500
Batch window: 1
Concurrent batches per shard: 1
Last processing result: OK
Maximum age of record: -1
On-failure destination:
{
  "onFailure": {}
}
Retry attempts: -1
Split batch on error: No
```

I expected 7 days as is mentioned in the documentation, but it was set to infinite (btw, I am fine with infinite, but I wanted to make sure, that it will not change in the future and infinite as default is expected)

Thank you, Jakub.

---

This is a 📕 documentation issue

**Comment by nija-at** [comment]
CDK's documentation is incorrect. The default value is infinite.
