### ISSUE TITLE
[init-templates] migrate Java init templates to JUnit 5 

### ISSUE THREAD

**Issue by RomainMuller** [aws/aws-cdk#10694]
The Java init templates include unit tests that are built against JUnit 4 (as can be seen via #10670). This is getting a little old and it might be a good idea to upgrade to JUnit 5.

### Use Case

It's silly to start a new project on an older version of frameworks / tools.

### Proposed Solution

Upgrade dependency to JUnit 5, and adjust the test code accordingly.
This ought to be pretty straight-forward since those tests are nothing fancy.

### Other

* [X] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by shivlaks** [comment]
sounds like a good idea! feel free to throw it into progress if you're already on it!
