### ISSUE TITLE
[python docs] Corrupted formatting in python reference documentation

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#10701]
https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_apigatewayv2.README.html

![Untitled](https://user-images.githubusercontent.com/598796/95105196-790a8a00-073f-11eb-9725-231fd7729895.png)

---

This is a 📕 documentation issue

**Comment by rix0rrr** [comment]
Has since been fixed
