### ISSUE TITLE
eslint-plugin-cdk installation issues

### ISSUE THREAD

**Issue by flemjame-at-amazon** [aws/aws-cdk#10709]
After this recent change ([link](https://github.com/flemjame-at-amazon/aws-cdk/commit/3cbb86321269b43b22580921b8a41c2af1172512)) was pulled in, running "buildup" for a package started returning this error:

> Oops! Something went wrong! :(
> 
> ESLint: 7.10.0
> 
> ESLint couldn't find the plugin "eslint-plugin-cdk".
> 
> (The package "eslint-plugin-cdk" was not found when loaded as a Node module from the directory "/home/ec2-user/environment/aws-cdk/tools/pkglint".)
> 
> It's likely that the plugin isn't installed correctly. Try reinstalling by running the following:
> 
>     npm install eslint-plugin-cdk@latest --save-dev
> 
> The plugin "eslint-plugin-cdk" was referenced from the config file in ".eslintrc.js".
> 
> If you still can't figure out the problem, please stop by https://eslint.org/chat/help to chat with the team.
> 

I've spent about an hour trying to get the plugin installed, by running the above command and also by installing peer dependencies. I'm missing *something*.

What do we have to do to our dev environments to continue developing CDK code?

**Comment by nija-at** [comment]
Thanks for reporting. The fix is coming in - https://github.com/aws/aws-cdk/pull/10719

The workaround until this is checked in - manually build `eslint-plugin-cdk` package (run `yarn build`) found in the `tools/` folder and re-run "buildup" as usual.
