### ISSUE TITLE
[python docs] README Headings formatting error

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#10702]
https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_apigatewayv2.README.html

Headings of README are in the wrong level and mix up with document headings:

![Screen Shot 2020-10-05 at 19 19 13](https://user-images.githubusercontent.com/598796/95105348-b3742700-073f-11eb-863e-1ae9cc13cd9f.png)

---

This is a 📕 documentation issue

**Comment by corymhall** [comment]
Looks like this has been fixed.

![Screen Shot 2022-08-09 at 3 24 36 PM](https://user-images.githubusercontent.com/43035978/183744309-af5a827d-aaa7-4079-b5fc-f0685fe86f46.png)
