### ISSUE TITLE
Incorrect documention for ServerlessCluster

### ISSUE THREAD

**Issue by bbreton** [aws/aws-cdk#10705]
https://github.com/aws/aws-cdk/blob/028495e55fed02f727024a443fc29a17d4629fe3/packages/%40aws-cdk/aws-rds/lib/serverless-cluster.ts#L63-L65

Hello,

When I try to set the value to 0 as described in the documentation I get the error:

Invalid backup retention period: 0. Retention period must be between 1 and 35. (Service: AmazonRDS; Status Code: 400; Error Code: InvalidParameterValue; Request ID: 209b96a2-f25c-4cc1-a2cf-09fceba2b968; Proxy: null)

I suspect this is because under the hood it uses read replicas which as explained in the link below require retention to not be 0.  I would like to be able to disable them, but I suspect that it is not possible and the code preventing it is correct and the documentation is incorrect.

https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_ReadRepl.html  

> First, you must enable automatic backups on the source DB instance by setting the backup retention period to a value other than 0.

It also might be good to add info about that restriction to the doco for https://github.com/aws/aws-cdk/blob/028495e55fed02f727024a443fc29a17d4629fe3/packages/%40aws-cdk/aws-rds/lib/instance.ts

**Comment by shivlaks** [comment]
@bbreton - thanks for reporting the issue! I've gone through the docs and tested it out and reached the same place as yourself. 

Backup retention cannot be disabled. I'll fix up the documentation and perhaps throw in some validation while I'm at it if provided value is not within the expected range (1 day - 35 days)
