### ISSUE TITLE
[docs] Package overview headings pulled up in Python documentation

### ISSUE THREAD

**Issue by alexpulver** [aws/aws-cdk#10714]
It happens in other modules as well, but for example:
https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_apigatewayv2.README.html

In this example, the headings of the package overview appear in the side menu, whereas they shouldn't:
![image](https://user-images.githubusercontent.com/4362270/95162003-439c8580-07ad-11eb-9dc2-b8ea79136a47.png)

The ones that are okay look like below:
![image](https://user-images.githubusercontent.com/4362270/95162085-721a6080-07ad-11eb-82e5-08689d93ebde.png)

---

This is a 📕 documentation issue

**Comment by SomayaB** [comment]
Duplicate of #10702
