### ISSUE TITLE
[cli] cdk deploy does not shortcut deployment of stacks with no changes

### ISSUE THREAD

**Issue by mariusingjer** [aws/aws-cdk#10718]
The cdk deploy command seems unable to skip unchaged stack, this leads to long deploy times

### Reproduction Steps

Update a deployed stack by invoking cdk deploy from the command line, deploy outputs this:

stack: checking if we can skip deploy
--
195 | stack: template has changed
196 | stack: deploying...
197 | Attempting to create ChangeSet ... to update stack stack
198 | stack: creating CloudFormation changeset...
199 | Initiated creation of changeset: ...; waiting for it to finish creating...
200 | Waiting for changeset ... on stack stack to finish creating...
201 | No changes are to be performed on stack.
202 |  
203 | ✅  stack (no changes)

I expect the yaml-diff to shortcut the entire process and not create a changeset which is very slow, even for small changes

What were you trying to achieve by performing the steps above?
A fast build

### What actually happened?

I get slow codedeploys, even for hello world examples with no nested stacks.

### Environment

  - **CLI Version      :1.66.0
  - **Framework Version:1.66.0
  - **Node.js Version:Whatever aws codebuild runs at the moment
  - **OS               : aws/codebuild/standard:4.0
  - **Language (Version):TypeScript (3.8.3)

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
Well it says

```
195 | stack: template has changed
```

So I guess the question is figuring out what the change is. What does `cdk diff` say?

**Comment by mariusingjer** [comment]
When running cdk diff from the command line it says:

Stack stack
There were no differences

**Comment by mariusingjer** [comment]
Example stack which causes "stack has changed, then no changes":

export class FooBarStack extends cdk.Stack {
    public readonly bucket: s3.Bucket;
    
    constructor(scope: cdk.Construct, id: string, props: cdk.StackProps) {
        super(scope, id, props);

        this.bucket = new s3.Bucket(this, 'foobar', {
            bucketName: 'foobar-artifacts',
            removalPolicy: RemovalPolicy.RETAIN,
            versioned: true,
            encryption: BucketEncryption.KMS,
            blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
        });

        new cdk.CfnOutput(this, 'exported-bucket-arn', {
            exportName: 'foobar-artifacts-arn',
            value: this.bucket.bucketArn,
            description: 'bla bla bla',
        });

        new cdk.CfnOutput(this, 'exported-bucket-encryption-key', {
            exportName: 'foobar-artifacts-key-arn',
            value: this.bucket.encryptionKey!.keyArn,
            description: 'bla bla bla',
        });
    }
}

**Comment by mariusingjer** [comment]
I suspect this is somehow related to the fact that cdk deploys a codepipeline (in my code) which is dependent on the example stack and the codepipeline stack has changed, but I don't see how that should affect a stack like the one above, which takes no dependencies on other stacks.

**Comment by rix0rrr** [comment]
Thanks for a reproduction. I can confirm that if I put the example stack you gave me by itself in an application and deploy it twice, it short-circuits the second time.

If I add another stack that depends on the example stack and run `cdk deploy FooBarStack` it still short-circuits.

Could it be that the new template has a `Rule` and the deployed template does not?

If not that, I'm going to need help reproducing this.

**Comment by mariusingjer** [comment]
You are absolutely right, just did a quick test myself and it shortcuts without creating a changeset, I will dig a bit further.

**Comment by SomayaB** [comment]
Any updates on your end @mariusingjer?

**Comment by mariusingjer** [comment]
I am observing this on a stack which sets up a rds database with user rotation. I tried to create a small test setting up an rds database with rotation, and it works as expected. I am closing this for now, i'll repoen it if I can prove it.
