### ISSUE TITLE
[ec2] Add tagging to SpotFleetRequestConfigDataProperty using python

### ISSUE THREAD

**Issue by jinamshah** [aws/aws-cdk#10717]
AWS recently announced tagging of spotfleet requests [(link)](https://aws.amazon.com/about-aws/whats-new/2020/02/amazon-ec2-now-supports-tagging-ec2-spot-fleet-requests/) 
This feature is not available with cdk using python

### Use Case

I would use this feature mainly for cost and resource allocation tracking

### Proposed Solution

Add SpotFleetTagSpecificationProperty to SpotFleetRequestConfigDataProperty class as well

---

This is a :rocket: Feature Request

**Comment by NetaNir** [comment]
You should be able to add tags using [`Tag.add()`](https://docs.aws.amazon.com/cdk/latest/guide/tagging.html)

**Comment by jinamshah** [comment]
Hey! I meant that there is no property for tagging the request in SpotFleetRequestConfigDataProperty (similar to the property available in SpotFleetLaunchSpecificationProperty
Example request:
`batch_workers_request_config_data = ec2.CfnSpotFleet.SpotFleetRequestConfigDataProperty(
            iam_fleet_role=spotfleet_iam_role,
            target_capacity=num_of_workers,
            instance_interruption_behavior='terminate',
            launch_specifications=[batch_workers_launch_specification]
        )`

**Comment by rix0rrr** [comment]
Does this feature existing CloudFormation already?

**Comment by jinamshah** [comment]
commenting to keep the issue alive

**Comment by rix0rrr** [comment]
If the feature does not exist in CloudFormation we cannot provide it.
