### ISSUE TITLE
[stepfunctions-tasks] Broken example code

### ISSUE THREAD

**Issue by kafka399** [aws/aws-cdk#10729]
## :question: General Issue

https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_stepfunctions_tasks.README.html

### The Question
According the official AWS documentation, the following code should work:

```py
    vpc = ec2.Vpc.from_lookup(stack, "Vpc",
        is_default=True
    )
    run_task = tasks.EcsRunTask(stack, "RunFargate",
        integration_pattern=sfn.IntegrationPattern.RUN_JOB,
        cluster=cluster,
        task_definition=task_definition,
        container_overrides=[ContainerOverride(
            container_definition=container_definition,
            environment=[TaskEnvironmentVariable(name="SOME_KEY", value=sfn.JsonPath.string_at("$.SomeKey"))]
        )],
        launch_target=tasks.EcsFargateLaunchTarget()
    )
```
However, I'm getting the following error:
```console
    jsii.errors.JSIIError: There are no 'Private' subnet groups in this VPC. Available types: Public
```
I can add the following, but it just pushing the problem into StepFunction task, where subnets are created empty:

```console
    subnets=ec2.SubnetSelection(subnets=vpc.private_subnets)
```

Can you update the documentation with working code?

### Environment

  - **CDK CLI Version:**  1.66.0 (build 459488d) 
  - **Module Version:** 
  - **Node.js Version:**  v10.15.3
  - **OS:** OSX Mojave 
  - **Language (Version):** Python (3.7.3)

**Comment by kafka399** [comment]
The following code allows to create a StepFunction task

    run_task = sf_task.EcsRunTask(self, "RunFargate",
                                        integration_pattern=sfn.IntegrationPattern.RUN_JOB,
                                        cluster=cluster,
                                        task_definition=task_def,
                                        subnets=ec2.SubnetSelection(
                                          subnets=vpc.public_subnets
                                        ),
    .....)

However, the question remains, why docs provide a broken solution.

**Comment by shivlaks** [comment]
thanks for reporting @kafka399 - I'll update the example (or happy to accept a PR if you want to open one!)

**Comment by doodlesbykumbi** [comment]
@kafka399 @shivlaks If I understood the solution correctly (which seems very simple) then here's a PR https://github.com/aws/aws-cdk/pull/11028
