### ISSUE TITLE
[cloudwatch] Public dashboard

### ISSUE THREAD

**Issue by mainframenzo** [aws/aws-cdk#10739]
I do not see functionality in the Dashboard CDK construct that mimics the "Share a single dashboard publicly" from https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch-dashboard-sharing.html. Is this possible? If not, please consider this a feature request so that I can get the public link as a stack output. Thanks!

---

This is a :rocket: Feature Request

**Comment by NetaNir** [comment]
Is there a way to enable this via CloudFormation? I looked at the docs and couldn't find that option. If not, is it possible to enable this via the SDK? We might be able to add a custom resource that turns it on.

**Comment by mainframenzo** [comment]
I don't see the capability in [CloudFormation](https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/CloudWatch-Dashboard-Body-Structure.html) or in the [SDK](https://docs.aws.amazon.com/cli/latest/reference/cloudwatch/put-dashboard.html). I will forward to the right place :)

**Comment by albertodiazdorado** [comment]
Hi @NetaNir , why did you close this feature request? Will it be **not** be implemented?

**Comment by deejbee** [comment]
If the feature is not directly supported in CDK with the Dashboard class, then can the process be documented so it can be built with CDK by hand?
