### ISSUE TITLE
[aws-stepfunctions]: Adjust readme example

### ISSUE THREAD

**Issue by HerrBertling** [aws/aws-cdk#10734]
Hi :wave:

I think I found a tiny issue within the example for step functions given in the [readme file](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-stepfunctions/README.md).

The part that seems off is this:

```js
const getStatus = new tasks.LambdaInvoke(this, 'Get Job Status', {
  lambdaFunction: getStatusLambda,
  // Pass just the field named "guid" into the Lambda, put the
  // Lambda's result in a field called "status" in the response
  inputPath: '$.guid',
  outputPath: '$.Payload',
});
```

The comment says the result would be passed into a field called `status`, but from what I understand, the snippet should then look like this:

```js
const getStatus = new tasks.LambdaInvoke(this, 'Get Job Status', {
  lambdaFunction: getStatusLambda,
  // Pass just the field named "guid" into the Lambda, put the
  // Lambda's result in a field called "status" in the response
  inputPath: '$.guid',
  outputPath: '$.status',
});
```

Since this field is referenced further down in the example within a `Choice` step, this could be confusing for people copy&pasting the example.

If this is actually wrong and not just me misunderstanding things, I'd be happy to provide a short pull request fixing this :blush:

---

This is a 📕 documentation issue

**Comment by shivlaks** [comment]
@HerrBertling - when using the new service integrations, the result of the Lambda itself is in a field called `Payload` (until result selection is implemented) - it's a snippet alluding to the [integration test](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-stepfunctions-tasks/test/lambda/integ.invoke.ts#L37-L50) where the Lambda itself reports the status back.

if you were to update the snippet, ensure that the `payloadResponseOnly` flag is set to true. This will bypass the service integration pattern and return the result of the Lambda directly.

happy to take a PR if you feel the adjustment will be helpful!

**Comment by HerrBertling** [comment]
> the result of the Lambda itself is in a field called Payload (until result selection is implemented) 

Ah, yes. I fiddled around with my first Step Function directly in the AWS Console and was quite surprised to have the `Payload` entry show up when I started using the CDK.

It is quite confusing coming from the Console, but I'd say it's fine as is 😊
