### ISSUE TITLE
[@aws-cdk/core] Allow disabling cloudFormationExecutionRole and deployRoleArn in the DefaultStackSynthesizer

### ISSUE THREAD

**Issue by pmarrone** [aws/aws-cdk#10746]
The legacy stack synthesizer omits setting a role when deploying CloudFormation stacks and uses the permission of the current logged in user.

It would be useful to allow disabling this behaviour to make the transition from the old templates to the new ones more gradual, since this behaviour does not seem intrinsically tied to the modern synthesizer.

### Use Case

We recently hit the limit for the amount of lambdas that are allowed to have in one stack due to the use of 3 CloudFormation Parameters for each lambda (quickly reaching the 60 parameters limit).

Having the new bootstrap template format, since it does not use references to point to the assets locations, would help us to get out of this situation.

When we update to the new format, we realised that the default synthesizer does not allow for a simple way to keep using the permission of the user running a CDK deployment, as it is done in legacy.

Since we already had a pipeline set up in a way which relied on this behaviour, using the default synthesizer for structural reasons (allow for more lambdas) introduces a breaking change that would require us to restructure our pipeline permissions.

Hacking around the DefaultSynthesizer, the old behaviour seems to be restorable while keeping the new structure. 

### Proposed Solution

Allowing to set 
DefaultStackSynthesizer.DEFAULT_CLOUDFORMATION_ROLE_ARN and
DefaultStackSynthesizer.DEFAULT_FILE_ASSET_PUBLISHING_ROLE_ARN to undefined could solve this, if it wasn't that there are marked as readonly (can be worked around typescript) and that those variables would be processes for template substitution, where they are assumed to be non nullish.

I can also think of a flag that could be set on the DefaultStackInitializer before the first stack is created, say `useLegacyRoles` or `useCurrentUsersPermissions`, but being able to configure the default roles instead seems more straightforward.

### Other

To work around this issue, I had to create a custom type of stack where I would configure a custom synthesizer where the only thing that has been changed is adding a hook when executing the .bind function to reset to undefined the deployer and cloudFormationExecutionRole. 

```
export class CurrentExecutionRoleSynthesizer extends DefaultStackSynthesizer {
  bind(stack: Stack) {
    super.bind(stack)
    ;(<any>this)._cloudFormationExecutionRoleArn = undefined
    ;(<any>this)._deployRoleArn = undefined
  }
}

export class CurrentExecutionRoleStack extends Stack {
  constructor(scope: Construct, id: string, props: StackProps) {
    super(scope, id, {
      ...props,
      synthesizer: new CurrentExecutionRoleSynthesizer(),
    })
  }
}
```

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by NetaNir** [comment]
I think that our general approach here, instead of adding knobs for every feature, is for users to implement their own StackSynthesizer.
