### ISSUE TITLE
[cx-api][core] Feature enableStackNameDuplicates and future (v2)

### ISSUE THREAD

**Issue by aripalo** [aws/aws-cdk#10761]
## :question: General Issue

CDK has a feature flag [`@aws-cdk/core:enableStackNameDuplicates`](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/cx-api/lib/features.ts#L11-L21) that is enabled by default for new CDK apps and will result to  _“name of the synthesized template file will be based on the construct path”_ (as described by the code comment).

I have created a tooling for my company which manages naming conventions, and for stacks they are the following:
| Resource Type | 1. `environment` present | 2. Only `account` present | 3. None |
| :--: | :--: | :--: |:--: |
| **Stack** `PascalCase` separated by dash (`-`) | `{ProjectName}-Environment-{Environment}-{Basename}` | `{ProjectName}-Account-{Basename}` | `{ProjectName}-{Basename}` |

… where `environment` and `account` (`dev`|`prod`|`shared`) are values given via CDK runtime context CLI arguments.

Given this naming convention, one was able to:
- `cdk deploy '*Account*'` - deploy just the account-level resources
- `cdk deploy '*Environment*'` - deploy the whole environment(-level resources)
- `cdk deploy '*{Basename}*'` - deploy a specific stack

Given _“In the next major release of the CDK, these feature flags will be removed and will become the default behavior.”_: **Will there be any way to control the synthesized template filename in `v2`?**

One workaround for this would be to change/enforce the construct path naming, but that is much more challenging and would require massive refactor for existing projects (and might be quite challenging in some cases where resources such as databases etc would require a replacement).

So in some sense this is a _feature request_ for `v2` to allow some kind of control to synthesized template filenames I guess...

Or maybe some way to target stacks (in CDK CLI) via some metadata value. Dunno 🤷‍♂️ 

### Environment

  - **CDK CLI Version:** 1.64.1 
  - **Module Version:**  1.64.1 
  - **Node.js Version:** v12.16.3 
  - **OS:** macOS Catalina 
  - **Language (Version):** TypeScript 3.9.7 

### Other information

- https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/cx-api/lib/features.ts
- https://github.com/aws/aws-cdk-rfcs/blob/master/text/0055-feature-flags.md

**Comment by NetaNir** [comment]
You can already do that today using [`Stack.templateFile`](https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/core/lib/stack.ts#L282). Is that what you are looking for?

**Comment by aripalo** [comment]
Hi @NetaNir thanks for pointing it out! :) It's close, but does not resolve this use case since it's a `readonly` property, but still good to know about that one!

**Comment by aripalo** [comment]
I guess, I'll have to consider just refactoring/rewriting my tooling in such a way that the constructs themselves will use somekind of naming patterns in the construct ID, so I could filter by them. It's a bit of work, but I guess it's better to do it to make the tooling future-proof for v2. 

I'm keeping this issue open for couple days - if it's okay (feel free to close if you want) - if anyone happens to have any additional input/ideas and if not, I'll close this.
