### ISSUE TITLE
[CodeCommit] Retrieving repository tags 

### ISSUE THREAD

**Issue by CodeEngineTechnology** [aws/aws-cdk#10769]
Currently you can not retrieve CodeCommit repository tags
Here is an example :

```ts
const repo = new codecommit.Repository(this, 'Repository' ,{
    repositoryName: 'MyRepositoryName',
    description: 'Some description.', // optional property
});
Tags.of(this).add('Key','Value') //tag the repo which works perfectly.
```

**### After deploying the stack you will see the tags in the repo however when you use `hasTags()` on the repository stack
false will be returned** 

### Use Case

I think this very beneficial in DevOps as we want to automatically read the tags on a specific repo

### Proposed Solution

Please add a method to CodeCommit supported methods
Thanks!

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by skinny85** [comment]
Hello @CodeEngineTechnology ,

thanks for opening the issue. When you say `hasTags()` doesn't work, can you be more specific what you mean? Can you show the code that is not working?

Thanks,
Adam

**Comment by CodeEngineTechnology** [comment]
Hey Adam,
My goal is to read the repo tags and generate the right buildspec based on the language type (NodeJS or Java) 
I have tried the following commands to get the tags that I have on the repo but none of them worked:

 //console.log( new cdk.TagManager(cdk.TagType.KEY_VALUE, repository.repositoryName).hasTags());
//console.log(new TagManager(cdk.TagType.KEY_VALUE,AWS::CodeCommit::Repository.prototypecloud8604.Tags").hasTags())
//console.log(repository.stack.tags.hasTags())
//console.log(new TagManager(cdk.TagType.KEY_VALUE,repository.repositoryName).renderTags());
//console.log(repository.stack.tags.tagValues)
//console.log(repository.node.metadata)


Any guidance on how to read repo tags would be very helpful
Best 
Siamak

**Comment by skinny85** [comment]
How do you know which repository will hold which language type? If you have that information in your code, can't you simply pass it to whatever code is creating the `buildspec`?

**Comment by CodeEngineTechnology** [comment]
So in another stack I have tagged the repo and it shows up in the console 
This is what I have: 



//CodeCommtit Stack

const repo = new codecommit.Repository(this, 'Repository' ,{
    repositoryName: 'MyRepositoryName',
    description: 'Some description.', // optional property
});
Tags.of(this).add('Language','Java')


-----------------------------------------------------------------

//CodePipeline Stack :

const repo=codeocmmit.Repository.fromRepositoryName (this, 'repository', props.repositoryname);

now I need to extract the repo tags , How do I do that ?

**Comment by skinny85** [comment]
That is for sure not possible (remember that `fromRepositoryName` does not perform any service calls).

Can't you just pass that information directly?

```ts
const codeCommitStack = new CodeCommitStack(app, 'CodeCommitStack');

new CodePipelineStack(app, 'CodePipelineStack', {
  repositories: [
   {
     repo: codeCommitStack.javaRep,
     type: CodeType.JAVA,
   },
   // ...
  ],
});
```

Something like that?

**Comment by CodeEngineTechnology** [comment]
That is exactly what I am doing now but is there any workaround to make a service call and retrieve the tags. How about cfnRepository?

**Comment by skinny85** [comment]
Nope.

**Comment by CodeEngineTechnology** [comment]
Cool, Thanks for your help :)

**Comment by skinny85** [comment]
NP 🙂.
