### ISSUE TITLE
[cli] cdk diff and cdk deploy ignore DELETE_FAILED state of existing CloudFormation stack 

### ISSUE THREAD

**Issue by eswets** [aws/aws-cdk#10784]
When running `cdk diff` or `cdk deploy` when a stack is in the DELETE_FAILED state, no changes are detected.

### Reproduction Steps

See https://github.com/eswets/cdk-detect-failed-delete

1. Create a CloudFormation stack which you can force into a DELETE_FAILED state. In the attached repo I create a stack with a S3 bucket with a DESTROY removalpolicy and copy a file to the created bucket afterwards.

2. Delete the stack. Because of the file in the bucket, the bucket cannot be destroyed and the stack will end up in a DELETE_FAILED state.

3. Run `cdk diff` and `cdk deploy` on the stack.

### What did you expect to happen?

For `cdk deploy` to detect there has been a change in the stack, perform a deploy and report that the stack cannot be updated due to the DEPLOY_FAILED state.

Ideally, `cdk diff` would report the same.

### What actually happened?

The changes are not detected:

`cdk deploy -vvvvv`
```
CdkDetectFailedDeleteStack: deploying...
Waiting for stack CDKToolkit to finish creating or updating...
[AWS cloudformation 200 0.07s 0 retries] describeStacks({ StackName: 'CDKToolkit' })
[AWS cloudformation 200 0.06s 0 retries] describeStacks({ StackName: 'CdkDetectFailedDeleteStack' })
CdkDetectFailedDeleteStack: checking if we can skip deploy
[AWS cloudformation 200 0.059s 0 retries] getTemplate({ StackName: 'CdkDetectFailedDeleteStack', TemplateStage: 'Original' })
CdkDetectFailedDeleteStack: skipping deployment (use --force to override)

 ✅  CdkDetectFailedDeleteStack (no changes)
```

`cdk diff -vvvvv`
```
Stack CdkDetectFailedDeleteStack
Reading existing template for stack CdkDetectFailedDeleteStack.
[AWS cloudformation 200 0.161s 0 retries] describeStacks({ StackName: 'CdkDetectFailedDeleteStack' })
[AWS cloudformation 200 0.059s 0 retries] getTemplate({ StackName: 'CdkDetectFailedDeleteStack', TemplateStage: 'Original' })
There were no differences
```

### Environment

  - **CLI Version      :** 1.67.0
  - **Framework Version:** 1.67.0
  - **Node.js Version:** 12.16.3
  - **OS               :** MacOS Catalina
  - **Language (Version):** TypeScript (3.8.3)

### Other

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
Needs an additional `if` in `canSkipDeploy`.
