### ISSUE TITLE
[aws-ec2] Missing InstanceClass c5a

### ISSUE THREAD

**Issue by xian13** [aws/aws-cdk#10781]
I can use c5a instance class on AWS Console and Cloudformation,
but I can't create c5a instance on CDK
because it is not declared in the InstanceClass enum

### Use Case

I want to use the instance
when creating container instance for my ECS cluster

### Proposed Solution

Add this line below the c5d declaration in InstanceClass enum
```typescript
    /**
     * Compute optimized instances based on AMD EPYC, 5th generation.
     */
    COMPUTE5_AMD = "m5a",
    /**
     * Compute optimized instances based on AMD EPYC, 5th generation
     */
    C5A = "c5a",
```

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by NetaNir** [comment]
Hi @xian13! 
Want to submit a PR?

**Comment by xian13** [comment]
Hi @NetaNir ,

Sure, I just submit the PR
