### ISSUE TITLE
[pipelines] Unable to use `onStateChange` on applicationStages

### ISSUE THREAD

**Issue by stephankaag** [aws/aws-cdk#10789]
`CdkStage` does not expose the `onStateChange` function from the underlying pipelineStage.

### What did you expect to happen?

I expected to be able to watch state change events of the CdkStage with the `onStateChange` function.

### What actually happened?

Function does not exist.

### Environment

  - **CLI Version      :**  1.66.0
  - **Framework Version:** 1.66.0
  - **Node.js Version:** v12.19.0
  - **OS               :** MacOS
  - **Language (Version):**  TypeScript

### Other

--- 

This is :bug: Bug Report

**Comment by seawatts** [comment]
Duplicate of #9028

**Comment by stephankaag** [comment]
You're right, exusé moi.
