### ISSUE TITLE
[aws-cdk] Add Timestream

### ISSUE THREAD

**Issue by pfried** [aws/aws-cdk#10799]
Since [AWS Timestream](https://aws.amazon.com/de/timestream/) is now available to the public we would like to see AWS-CDK beeing capable of orchestrating it.

### Use Case

To use Timestream for a applications

### Proposed Solution

Add a @aws-cdk/aws-timestream module

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by NetaNir** [comment]
duplicate https://github.com/aws/aws-cdk/issues/10819
