### ISSUE TITLE
[ec2] Resource ID support in CloudFormationInit (e.g. to use `cfn-hup`)

### ISSUE THREAD

**Issue by erikdebruin** [aws/aws-cdk#10791]
I ran into an issue with the new CloudFormationInit feature. I would like to make use of `cfn-hup` (and with it the `cfn-auto-reloader`) scripts. To implent those I need to write the '_/etc/cfn/hooks.d/cfn-auto-reloader.conf_' file and that requires me to enter the Resource ID of the instance/launch configuration that I'm creating. 

CloudFormationInit is implemented in the constructor of the Instance class and at that time there is not yet a Resource ID.

### Use Case

There will be times - like when wanting to implement `cfn-hup` - that one needs access to a resources properties. Having to create the entire CfnInit config in the constructor of the class means that those properties simply do no exist yet, making the feature basically unavailable.

### Proposed Solution

I talked with @njlynch on Slack and he indicated that it was considered to do the CfnInit config append AFTER creation, but there wasn't a strong enough use case for it.

I suggest that the above case presents a strong argument to reconsider taking the CfnInit config out of the constructor and giving it it's own method(s). This would allow us to work with all of the properties of a 'completed' resource when creating the `cfn-init`.

* [x] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
@njlynch isn't it a matter of making this public? https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-ec2/lib/instance.ts#L434

**Comment by njlynch** [comment]
> @njlynch isn't it a matter of making this public?

Yup, that was what I was saying to @erikdebruin. I believe you/we wrote the above to be public initially, then during the review process one (or more) reviewers noted that the most common use case would be to create during construction and asked to limit the public-facing API surface area. 

Besides the one-liner changing `private` to `public`, I think maybe there needs to be just a quick look at any side-effects and/or guards against having init twice (once via the props, once via `applyCloudFormationInit`, or just calling `applyCloudFormationInit` twice). But should be a relatively minor change either way.

**Comment by erikdebruin** [comment]
At the risk of over-asking: shouldn't this pattern not also be available on `AutoScalingGroup`?

Have `init` and `initOptions` properties on `AutoScalingGroupProps`, a call to `applyCloudFormationInit()` in the constructor of `AutoScalingGroup`. That in return calls `_attach()` on `CloudFormationInit` with a reference to the `CfnLaunchConfiguration`. 

Of note is that in the doc on the `_attach()` method there is this comment: "As an app builder, use `instance.applyCloudFormationInit()` or `autoScalingGroup.applyCloudFormationInit()` to trigger this method." That seems to suggest that this should already be in place on `AutoScalingGroup` - albeit maybe privately, as with `Instance` - but I can't find any reference, let alone an implementation, in the released code.

**Comment by rix0rrr** [comment]
We're unlikely to get to this soon ourselves, but if you'd be willing to submit a PR we will accept it.

**Comment by armitagemderivitec** [comment]
I started the process of migrating our cloudformation YAML templates to the c# sdk today after watching some cool tutorials over the weekend. I'm trying to implement the cfn-auto-reloader myself and see that the ApplyCloudFormationInit method is now public. Now I can create my CloudFormationInit object and apply to an auto scaling group with ApplyCloudFormationInit everything appears to be in place for passing the resource id into the  '/etc/cfn/hooks.d/cfn-auto-reloader.conf' file. 

Is this the resource id I'm after: 

```
var autoScalingGroup = new AutoScalingGroup(this, "asg");
var resourceId = Names.UniqueId(autoScalingGroup);
```

**Comment by skinny85** [comment]
I believe what you want @armitagemderivitec is something like:

```csharp
var autoScalingGroup = new AutoScalingGroup(this, "asg");
autoScalingGroup.getNode().getDefaultChild().getLogicalId();
```
