### ISSUE TITLE
Adding tags to the underling lambda of a SingletonFunction

### ISSUE THREAD

**Issue by AdamBoxall** [aws/aws-cdk#1079]
There's no direct or simple way of constructing a `SingletonFunction` and providing tags to the underlying lambda. In some organisations it's a requirement to tag any resources that handle or store sensitive data, such as PII.

The normal workaround would be to use `findChild("Resource")` to get the CFN-level resource object, and override the tags property. However as the underlying lambda of a singleton function is a sibling, not a descendant, that does not work.

Instead you have to access the children of the current stack and findChild() using the ID given to the lambda, based upon the `lambdaPurpose` and `uuid` props:

```ts
const lambda = Stack.find(this).findChild("LambdaPurposeUUID");
const resource = lambda.findChild("Resource") as FunctionResource;
```

(There's some formatting applied to both of those props to strip out invalid characters)

**Comment by moofish32** [comment]
Let me add a test over [here](https://github.com/awslabs/aws-cdk/pull/1007) and see if this can catch your use case too. If you have a test stack in a gist, I'll grab that directly.

**Comment by SomayaB** [comment]
Closing this issue since there hasn't been any activity on it in a while. Feel free to reopen.
