### ISSUE TITLE
[aws-cdk/core] CfnCodeDeployBlueGreenHook

### ISSUE THREAD

**Issue by MikletNg** [aws/aws-cdk#10803]
Hi, I am trying to deploy an ECS service with blue/green deployment following this [tutorial/document](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/blue-green.html#blue-green-template-example).
I am trying to use the L1 constructor - `CfnCodeDeployBlueGreenHook`. At the `trafficRoutingConfig` property, you can only specify `TimeBasedCanary` or `TimeBasedLinear` traffic policy, but the problem is this L1 constructor will create both properties in the CloudFormation template which error occur during the deployment.

### Reproduction Steps
CDK construtor
```typescript
const ecsServiceBlueGreenDeploymentHook = new CfnCodeDeployBlueGreenHook(this, 'EcsServiceBlueGreenDeploymentHook', {
            serviceRole: this.getLogicalId(ecsServiceBlueGreenDeploymentHookServiceRole.node.defaultChild as CfnRole),
            trafficRoutingConfig: {
                type: CfnTrafficRoutingType.TIME_BASED_CANARY,
                timeBasedCanary: {
                    stepPercentage: 15,
                    bakeTimeMins: 5
                }
            },
            applications: [
                {
                    target: {
                        type: 'AWS::ECS::Service',
                        logicalId: 'Service'
                    },
                    ecsAttributes: {
                        taskDefinitions: [
                            this.getLogicalId(blueTaskDefinition.node.defaultChild as CfnTaskDefinition),
                            'GreenTaskDefinition'
                        ],
                        taskSets: [
                            blueTaskSet.logicalId,
                            'GreenTaskSet'
                        ],
                        trafficRouting: {
                            prodTrafficRoute: {
                                type: 'AWS::ElasticLoadBalancingV2::Listener',
                                logicalId: this.getLogicalId(prodListener.node.defaultChild as CfnListener)
                            },
                            testTrafficRoute: {
                                type: 'AWS::ElasticLoadBalancingV2::Listener',
                                logicalId: 'TestListener'
                            },
                            targetGroups: [
                                this.getLogicalId(blueTargetGroup.node.defaultChild as CfnTargetGroup),
                                'GreenTargetGroup'
                            ]
                        }
                    }
                }
            ]
        })
```
### What did you expect to happen?
The `TimeBasedLinear` should be missing in the CloudFormation template, and also other no relevant/empty properties should be missing.
```json
 "Hooks": {
    "EcsServiceBlueGreenDeploymentHook": {
      "Type": "AWS::CodeDeploy::BlueGreen",
      "Properties": {
        ...
        ...
        "TrafficRoutingConfig": {
          "Type": "TimeBasedCanary",
          "TimeBasedCanary": {
            "StepPercentage": 15,
            "BakeTimeMins": 5
          }
        },
        "AdditionalOptions": {},
        "LifecycleEventHooks": {}
      }
    }
  }
```

### What actually happened?
Rendered template
```json
"Hooks": {
    "EcsServiceBlueGreenDeploymentHook": {
      "Type": "AWS::CodeDeploy::BlueGreen",
      "Properties": {
        ...
        ...
        "TrafficRoutingConfig": {
          "Type": "TimeBasedCanary",
          "TimeBasedCanary": {
            "StepPercentage": 15,
            "BakeTimeMins": 5
          },
          "TimeBasedLinear": {}
        },
        "AdditionalOptions": {},
        "LifecycleEventHooks": {}
      }
    }
  }
```
An error occurs during deployment
`
❌  BlueGreenTestStack failed: Error: Failed to create ChangeSet CDK-b5f0ca3f-01f7-412b-ab23-c41324903211 on BlueGreenTestStack: FAILED, 'EcsServiceBlueGreenDeploymentHook' of type AWS::CodeDeploy::BlueGreen failed with message: AllAtOnce and TimeBasedLinear must be null for TimeBasedCanary traffic routing config type
`

### Environment

  - **CLI Version      :1.67.0**
  - **Framework Version:1.67.0**
  - **Node.js Version:v12.16.1** 
  - **OS               :Windows 10 - WSL 2 - Ubuntu 18**
  - **Language (Version): TypeScript (3.7.5)** 

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Thanks for reporting @MikletNg . I'm working on a fix.

**Comment by srethira** [comment]
+1. Ran into the same exact problem!

**Comment by bitfrost** [comment]
> +1
> Ran into the same exact problem!

Ditto, I  just hit it now too.   I am looking forward to the fix's release

**Comment by aedris0** [comment]
Hello @MikletNg, what is the definition of task set, and from where we can get them
