### ISSUE TITLE
[CLI] 1.63.0 jenkins build always fail

### ISSUE THREAD

**Issue by Ranjith072** [aws/aws-cdk#10802]
Hi ,
I'm running the cdk deployments by using  jenkins and i use withAWS plugin of jenkins to get the temp credentials from a role ,
i had no issues till the version 1.63.0 but if i upgrade the cdk version to anything after 1.63.0 my builds are failing to run any cdk commands with the error (Need to perform AWS calls for account XXXXX, but no credentials have been configured.).

### Reproduction Steps
i just need to upgrade the cdk version to anything after 1.63.0  then try to deploy via jenkins builds will always fail.

### What did you expect to happen?
build has to be finished irrespective of cdk version.

What were you trying to achieve by performing the steps above?
deploy the cdk stacks to AWS environment.

What is the unexpected behavior you were seeing? If you got an error, paste it here.
unable to find the credentials.

### Environment

  - **CLI Version      :** 1.17.1
  - **Framework Version:** 1.64.0
  - **Node.js Version:** 12.19.0
  - **OS               :** Amazon Linux 2
  - **Language :** python 3.8.6

![image](https://user-images.githubusercontent.com/57263575/95565582-b3667680-0a20-11eb-9c42-fe864382298a.png)

This is :bug: Bug Report

**Comment by hoegertn** [comment]
Hi, as CDK contributor on the one hand and author of the Jenkins plugin, on the other hand, let me try to help.

Can you please add an awsIdentity() step before the cdk deploy to see if the credentials really are working? Please make sure they belong to the account CDK is trying to access.

Then we can dive deeper into the reasons for this behavior.

**Comment by Ranjith072** [comment]
Hi @hoegertn ,
they are from the same AWS account and this is the response i get.

![image](https://user-images.githubusercontent.com/57263575/95583489-7d36f000-0a3c-11eb-913c-a1d14a444831.png)
as i said earlier this setup still runs correctly with the older version of ckd.

**Comment by Ranjith072** [comment]
thanks @hoegertn for your help, 
i found a  workaround for my issue .
the issues was that i was passing --profile option to run cdk  commands and the below merge caused my script to stop working . 
https://github.com/aws/aws-cdk/pull/10362
resolution:
 do not pass --profile parameter to cdk commands while using the assume role option(which is the case when u use jenkins withAWS package).
