### ISSUE TITLE
AutoScaling: switch to Rolling Updates by default

### ISSUE THREAD

**Issue by rix0rrr** [aws/aws-cdk#1080]
Right now, AutoScalingGroups have `UpdateType: None` by default, which effectively means that if you change anything about its settings (such as what AMI to launch) and you deploy... nothing much happens (other than updating the LaunchConfig).

The deployment completes happily and and gives you the thumbs up.

This is bad for two reasons:

* I probably meant to effect change by changing something about my launch type, such as the AMI or the UserData.
* If I broke something, I'll only notice upon my next scaling operation. Maybe when I'm under load I'll notice new instances are failing to come up--bad! Worse: it's too late to roll this change back in an orderly fashion.

So I'm proposing to switch the default to rolling updates. People that care will still have the opportunity to disable this if they want to, but I feel the default should be "do something sane" and what we're doing now doesn't sound sane.

cc @eladb @RomainMuller @skinny85 @moofish32. Opinions?

**Comment by moofish32** [comment]
Agree with the bad.

I prefer Rolling as it is a distinguishing feature of CFN and my preferred method. I am a little concerned that getting the defaults right will be difficult. Typically, things like PauseTime can vary significantly depending on the app. I don't know if WillReplace is that much easier though. Do we now have better support for cfn-signal or do I still need to use the Override to get the ASG Logical ID?

**Comment by rix0rrr** [comment]
There's no good support for signal yet, stuck in a branch that I haven't worked on in a while.

We can choose some reasonable default, people will always be able to override if their app requires more time (and they'll know/find out).

**Comment by rix0rrr** [comment]
Depends on CFN-init support (we have another PR for that).

**Comment by NetaNir** [comment]
closing in favor of https://github.com/aws/aws-cdk/pull/9674
