### ISSUE TITLE
Execute deployment using a Rest Endpoint

### ISSUE THREAD

**Issue by bigbansal** [aws/aws-cdk#10808]
Can I execute  deployment using a Rest Endpoint. Instead of "cdk deploy" ? For example

1. One Endpoint to Synth
2. One  Endpoint to Deploy
3. One Endpoint to Destroy 

If yes, can you suggest how ? or If is not possible, can u consider this as new feature request.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by SomayaB** [comment]
Hi @bigbansal, sounds like you might want to use [CDK pipelines](https://docs.aws.amazon.com/cdk/latest/guide/cdk_pipeline.html). If not, can you tell us more about what you're trying to accomplish?
