### ISSUE TITLE
(kinesisfirehose): L2 for CfnDeliveryStream

### ISSUE THREAD

**Issue by iliapolo** [aws/aws-cdk#10810]
### Use Case

Better ergonomics for using `CfnDeliveryStream`.

Part of https://github.com/aws/aws-cdk/issues/7536

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by iliapolo** [comment]
We should consider the scenario in this [comment](https://github.com/aws/aws-cdk/issues/10783#issuecomment-706589031) when we start working on this L2.

**Comment by mikelane** [comment]
I've started work on this.

**Comment by iliapolo** [comment]
@mikelane Cool! 

Do you maybe want to flush out the API before we get to the coding/reviewing part? Best option would be is to create a theoretical README and submit that in a draft PR so we can talk about it.

**Comment by mikelane** [comment]
> @mikelane Cool! 
> 
> 
> 
> Do you maybe want to flush out the API before we get to the coding/reviewing part? Best option would be to create a theoretical README and submit that in a draft PR so we can talk about it. 

I'd be happy to do that. I'll model it after other construct overview pages.

**Comment by BenChaimberg** [comment]
@mikelane – the CDK team has started designing this construct and would love to see anything you have in progress to help guide our thinking!
