### ISSUE TITLE
how to debug AWS CDK app in Java Intellij

### ISSUE THREAD

**Issue by bigbansal** [aws/aws-cdk#10811]
I am not able to find, how to debug AWS CDK app in Java Intellij

---

This is a 📕 documentation issue

**Comment by SomayaB** [comment]
Hi @bweigel, you should be able to debug it the same way you debug any other apps. Can you tell us more about what specific issue you're having?

**Comment by bweigel** [comment]
Wrong mention @SomayaB .

CC @bigbansal
