### ISSUE TITLE
[aws-lambda] How to invoke Lambda to run once after CDK deploy

### ISSUE THREAD

**Issue by jvargh** [aws/aws-cdk#10820]
Was able to successfully deploy Lambda via CDK but need to have it executed just once, right after deploy complete. Basically lambda performs a security hardening measure so its a one time run. Any thoughts on how to make this happen?

**Comment by relm923** [comment]
Sounds like a good use case for [Custom Resources](https://docs.aws.amazon.com/cdk/api/latest/docs/custom-resources-readme.html)

**Comment by SomayaB** [comment]
Hi @jvargh, did custom resources solve your issue? If not, I would just suggest writing a bash script to do this.

**Comment by jvargh** [comment]
Hi @SomayaB this can be closed. Resolution was to create a custom event (EventBridge rule) as the Lambda driver. There was another scheduled rule created to run just once (like 5m after deploy).

**Comment by moltar** [comment]
> Hi @SomayaB this can be closed. Resolution was to create a custom event (EventBridge rule) as the Lambda driver. There was another scheduled rule created to run just once (like 5m after deploy). 

@jvargh how did you solve this? How do you trigger an event after deploy? Thank you.

**Comment by YikaiHu** [comment]
> > Hi @SomayaB this can be closed. Resolution was to create a custom event (EventBridge rule) as the Lambda driver. There was another scheduled rule created to run just once (like 5m after deploy).
> 
> @jvargh how did you solve this? How do you trigger an event after deploy? Thank you.

Hi all,

Here is an example may help, using Custom Resources to achieve this.

The code is written in TypeScript.

<details>
<summary>Example to invoke Lambda after the cdk deploy or update</summary>

```typescript
    const checkExecutionLambda = new lambda.Function(this, 'CheckExecutionFunction', {
      runtime: lambda.Runtime.NODEJS_12_X,
      handler: 'step-func.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../lambda')),
      memorySize: 256,
      timeout: cdk.Duration.minutes(15),
      // tracing: lambda.Tracing.ACTIVE,
      environment: {
        STATE_MACHINE_ARN: ecrStateMachine.stateMachineArn
      }
    });    

    //Run checkExecutionLambda on Create
    const lambdaTrigger = new cr.AwsCustomResource(this, 'StatefunctionTrigger', {
      policy: cr.AwsCustomResourcePolicy.fromStatements([new iam.PolicyStatement({
        actions: ['lambda:InvokeFunction'],
        effect: iam.Effect.ALLOW,
        resources: [checkExecutionLambda.functionArn]
      })]),
      timeout: cdk.Duration.minutes(15),
      onCreate: {
        service: 'Lambda',
        action: 'invoke',
        parameters: {
          FunctionName: checkExecutionLambda.functionName,
          InvocationType: 'Event'
        },
        physicalResourceId: cr.PhysicalResourceId.of('JobSenderTriggerPhysicalId')
      },
      onUpdate: {
        service: 'Lambda',
        action: 'invoke',
        parameters: {
          FunctionName: checkExecutionLambda.functionName,
          InvocationType: 'Event'
        },
        physicalResourceId: cr.PhysicalResourceId.of('JobSenderTriggerPhysicalId')
      }
    })
    lambdaTrigger.node.addDependency(ecrStateMachine, smRule)
```
</details>

Then, you can invoke the `checkExecutionLambda` when you create the cdk or update it.

**Comment by anwarjaved** [comment]
> How we create a custom event (EventBridge rule) as the Lambda driver. There was another scheduled rule created to run just once (like 5m after deploy).

**Comment by dmschauer** [comment]
> > > Hi @SomayaB this can be closed. Resolution was to create a custom event (EventBridge rule) as the Lambda driver. There was another scheduled rule created to run just once (like 5m after deploy).
> > 
> > 
> > @jvargh how did you solve this? How do you trigger an event after deploy? Thank you.
> 
> Then, you can invoke the `checkExecutionLambda` when you create the cdk or update it.

@YikaiHu
Can someone please commet on the last line in this piece of code? 
What does `lambdaTrigger.node.addDependency(ecrStateMachine, smRule)` do? I didn't see `ecrStateMachine ` and `smRule ` being created here so I'm confused.

Is this line necessary for automated execution of the Lambda function after it was created? Or is it sufficient to define `lambdaTrigger`?

**Comment by SaiVinay007** [comment]
> @YikaiHu Can someone please comment on the last line in this piece of code? What does `lambdaTrigger.node.addDependency(ecrStateMachine, smRule)` do? I didn't see `ecrStateMachine ` and `smRule ` being created here so I'm confused.
> 
> Is this line necessary for automated execution of the Lambda function after it was created? Or is it sufficient to define `lambdaTrigger`?


@dmschauer  

From https://docs.aws.amazon.com/cdk/api/v1/docs/core-readme.html#dependencies:

>Sometimes AWS resources depend on other resources, and the creation of one resource must be completed before the next one can be started.
>
>If you need to add an ordering dependency that is not automatically inferred, you do so by adding a dependency relationship using constructA.**node.addDependency**(constructB). This will add a dependency relationship between all resources in the scope of constructA and all resources in the scope of constructB.

**Comment by YikaiHu** [comment]
> > > > Hi @SomayaB this can be closed. Resolution was to create a custom event (EventBridge rule) as the Lambda driver. There was another scheduled rule created to run just once (like 5m after deploy).
> > > 
> > > 
> > > @jvargh how did you solve this? How do you trigger an event after deploy? Thank you.
> > 
> > 
> > Then, you can invoke the `checkExecutionLambda` when you create the cdk or update it.
> 
> @YikaiHu Can someone please comment on the last line in this piece of code? What does `lambdaTrigger.node.addDependency(ecrStateMachine, smRule)` do? I didn't see `ecrStateMachine ` and `smRule ` being created here so I'm confused.
> 
> Is this line necessary for automated execution of the Lambda function after it was created? Or is it sufficient to define `lambdaTrigger`?

@dmschauer 
Hi, you can ignore this. 
You can refer to the answer of [SaiVinay007](https://github.com/aws/aws-cdk/issues/10820#issuecomment-1034571900).
I accidentally copied an extra line of code from the project

**Comment by wcheek** [comment]
Thanks for the guide @soonooipo!

For somebody looking to do this in `Python` flavored `CDK`:

```python
cr.AwsCustomResource(
    scope=self,
    id="invoke_lambda",
    policy=(
        cr.AwsCustomResourcePolicy.from_statements(
            statements=[
                iam.PolicyStatement(
                    actions=["lambda:InvokeFunction"],
                    effect=iam.Effect.ALLOW,
                    resources=[my_lambda.function_arn],
                )
            ]
        )
    ),
    timeout=Duration.minutes(15),
    on_create=cr.AwsSdkCall(
        service="Lambda",
        action="invoke",
        parameters={
            "FunctionName": my_lambda.function_name,
            "InvocationType": "Event",
        },
        physical_resource_id=cr.PhysicalResourceId.of(
            "JobSenderTriggerPhysicalId"
        ),
    ),
    on_update=cr.AwsSdkCall(
        service="Lambda",
        action="invoke",
        parameters={
            "FunctionName": my_lambda.function_name,
            "InvocationType": "Event",
        },
        physical_resource_id=cr.PhysicalResourceId.of(
            "JobSenderTriggerPhysicalId"
        ),
    ),
)
```

**Comment by ababakanian** [comment]
I found out about this construct https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.triggers.TriggerFunction.html
based on the description "Invokes an AWS Lambda function during deployment"
