### ISSUE TITLE
[apigateway] Tags do not propagate to API Gateway resource when using openAPI spec (SpecRestApi)

### ISSUE THREAD

**Issue by FergusMcGlynn** [aws/aws-cdk#10827]
When creating a stack containing a `SpecRestApi` resource (an API Gateway resource the uses an Open API specification to define the API), if you add tags to the stack, those tags are NOT applied to the API upon creation. 

### Reproduction Steps

An Open API specification `openApiSpecification.json`:
```
{
  "openapi": "3.0.0",
  "info": {
    "title": "Person API",
    "version": "0.0.1"
  },
  "components": {
    "schemas": {
      "Person": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "name": {
            "type": "string"
          },
          "department": {
            "type": "string"
          }
        }
      }
    }
  },
  "paths": {
    "/person": {
      "get": {
        "summary": "Returns a list of people.",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Person"
                  }
                }
              }
            }
          }
        },
        "x-amazon-apigateway-integration": {
          "type": "mock",
          "responses": {
            "default": {
              "statusCode": "200"
            }
          },
          "requestTemplates": {
            "application/json": "{\"statusCode\": 200}"
          },
          "passthroughBehavior": "when_no_match"
        }
      }
    }
  }
}
```
A stack containing a `SpecRestApi` resource `api-tags-demo-stack.ts`:
```
export class ApiTagsDemoStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    new apiGateway.SpecRestApi(this, 'apiDemoRestApi', {
      apiDefinition: apiGateway.ApiDefinition.fromAsset('openApiSpecification.json'),
    });

  }
}
```
Apply tags to the stack `api-tags-demo.ts`:
```
const app = new cdk.App();
const stack = new ApiTagsDemoStack(app, 'ApiTagsDemoStack');
Tags.of(stack).add("a", "b");
Tags.of(stack).add("c", "d");
```
Run `cdk deploy` and CDK successfully applies the tags to the stack:

![image](https://user-images.githubusercontent.com/62424514/95764300-2cc3ca80-0ca8-11eb-963e-a2d7a8ce4057.png)

But those tags are not present on the API resource:

![image](https://user-images.githubusercontent.com/62424514/95764396-5250d400-0ca8-11eb-8a9c-987a653e88ff.png)

### What did you expect to happen?

The tags applied to the stack are applied to the API

### What actually happened?

The tags applied to the stack have not been applied to the API.

If you add some more tags and run `cdk deploy` again, those new tags DO get applied to the API. It appears that this issue occurs on resource creation.

### Environment

  - **CLI Version      :** 1.67.0
  - **Framework Version:** 1.67.0
  - **Node.js Version:** 12.3.1
  - **OS               :** Windows 10
  - **Language (Version):**  TypeScript

--- 

This is :bug: Bug Report

**Comment by Karthikeya2017** [comment]
+1

**Comment by nija-at** [comment]
@FergusMcGlynn - thanks for opening this issue.

Could you explain what you mean by 'tags are not present on the API resource'? I'm aware of [tags to API stages](https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-tags.html) but am not aware of tagging resources.

Where can I find these on the AWS console or in the documentation?

**Comment by FergusMcGlynn** [comment]
> @FergusMcGlynn - thanks for opening this issue.
> 
> Could you explain what you mean by 'tags are not present on the API resource'? I'm aware of [tags to API stages](https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-tags.html) but am not aware of tagging resources.
> 
> Where can I find these on the AWS console or in the documentation?

To view tags on an API resource in the AWS console:
- go to the API Gateway page
- click on the API in question
- click on `Settings` link in the left hand menu
- click on the `Configure tags` button in the top right corner

To view tags on the API's stage resource(s) in the AWS console:
- go to the API Gateway page
- click on the API in question
- click on `Stages` link in the left hand menu
- click on the stage in question
- click on the `Configure tags` button in the top right corner

**Comment by nija-at** [comment]
@FergusMcGlynn - thanks for those instructions.

This appears to not be an issue with the CDK but instead an issue with either CloudFormation or API Gateway. Unfortunately, there's nothing much the CDK team can do here. Please reach out these teams via AWS support.

Internal ref: t.corp/D18524603

**Comment by alex-a-ncino** [comment]
Also impacted by this issue. We are adding tags to stacks and they get propagated to the resources within those stacks but not for the API Gateways/Stages. Looking at the CF template we do see the tags present but when we check the UI (Configure Tags) the tags are not added. Also, in our cost analysis reports broken down by tags, we don't get the API Gateways.

**Comment by alex-a-ncino** [comment]
After further investigation, we realized the issue was the role that was deploying the CDK app didn't have access to tag APIs. Once that's fixed CDK is actually tagging APIs. One thing to note si that since tags were being added to the CF template re-deploy to an existing stack doesn't see any change to tags so it doesn't add them. So either destroy/deploy or changing the tag values for the tags to be applied.
The required permission was `apigateway:PUT` on `arn:aws:apigateway:*::/tags/*`

**Comment by nija-at** [comment]
Nice. I'm glad you were able to figure this one out.
