### ISSUE TITLE
[@aws-cdk/aws-cloudfront] CfnDistribution.ForwardedValuesProperty should be marked deprecated.

### ISSUE THREAD

**Issue by rcollette** [aws/aws-cdk#10825]
CfnDistribution.ForwardedValuesProperty is not marked as deprecated as mentioned in the user guide 
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-forwardedvalues.html#cfn-cloudfront-distribution-forwardedvalues-cookies

### Environment

  - **CLI Version      : 1.67.0
  - **Framework Version: 1.67.0
  - **Language (Version): all

--- 

This is :bug: Bug Report

**Comment by njlynch** [comment]
Unfortunately – at this time – the CloudFormation specification which we consume to generate the `Cfn*` classes and interfaces does not publish which field(s) are deprecated in an automated, machine-readable format. Until such a format exists, we will not support marking CloudFormation fields as deprecated.

Out of curiosity, can you explain how this is impacting you? Are there use cases you have that aren't covered by either the `Distribution` or `CloudFrontWebDistribution` constructs that requires you to directly use the L1/Cfn constructs?

**Comment by rcollette** [comment]
@njlynch - I was looking to setup cookie, header and query string forwarding for a custom origin added to a `CloudFrontWebDistribution`.  Perhaps I've missed a higher level construct for doing this?   I did notice that a few days ago CDK code was merged for `OriginRequestPolicies` but I wasn't able to find any documentation on it in a Google search, just the source merge request.

```typescript
distributionProperties: {
          originConfigs: [
            {
              behaviors: [
                {
                  pathPattern: '/embark-api/*',
                  forwardedValues: {
                    cookies: {
                      forward: 'all',
                    },
                    headers: [
                      'Origin',
                      'Access-Control-Request-Method',
                      'Access-Control-Request-Headers',
                      'X-PB-TransactionId',
                      'X-request-id',
                    ],
                    // Forward all query string values
                    queryString: true,
                    // Attempting to not cache any values by query string.
                    queryStringCacheKeys: ['dummy-x'],
                  },
                  // Do not cache anything that the API server has not specified to be cached.
                  defaultTtl: Duration.millis(0),
                },
              ],
              customOriginSource: {
                domainName: `my.host.domain.name`,
              },
            },
          ],
        },
```

**Comment by njlynch** [comment]
Ah, I see! I misinterpreted your request as us needing to mark the `CfnDistribution.ForwardedValuesProperty` interface itself as deprecated, but you're pointing out that `Behavior.forwardedValues` (which is a `CfnDistribution.ForwardedValuesProperty`) should be marked as deprecated in favor of the new policies. I hadn't realized that the `Behavior` interface directly exposed the underlying `CfnDistribution*` interfaces; we tend not to do that anymore.  :)

The CloudFront Cache Policies -- which replace the existing forwarded values approach -- are now supported, but only for the new (experimental) `Distribution` construct, and not the older (stable) `CloudFrontWebDistribution` construct. If you're curious, here's the section of the CloudFront README for how to use Cache Policies with the `Distribution` construct: https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/aws-cloudfront#customizing-cache-keys-and-ttls-with-cache-policies

I just created a dedicated feature for porting over support for Cache Policies to the `CloudFrontWebDistribution`: https://github.com/aws/aws-cdk/issues/10829. I'm going to close this out in favor of that one; please let me know if you have any follow-ups.
