### ISSUE TITLE
[lambda] using encryption configuration kmsKeyArn as parameter not implemented yet.

### ISSUE THREAD

**Issue by abocati** [aws/aws-cdk#10837]
I have been trying to add an encryption configuration using **KMS** into my Lambda using the parameter `kmsKeyArn` as per the [documentation](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-lambda.CfnFunctionProps.html) however it doesn't seem it has been implemented just yet.

Anyone can confirm please?

https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-lambda.CfnFunctionProps.html

```      
const lambdaHandler = new lambda.Function(this, lambdaFunction, {
        description: `${lambdaFunction}`,
        timeout: cdk.Duration.seconds(30),
        ...,
        kmsKeyArn???: 
      });
```

---

This is a 📕 documentation issue

**Comment by nija-at** [comment]
Hey @abocati -

No, this has not been implemented. You can workaround this using [escape hatches](https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html#cfn_layer_raw).

**Comment by abocati** [comment]
Thank you @nija-at

**Comment by ale753** [comment]
I will leave a sample code here using the AWS Cloudformation constructs directly.

```typescript
    const Lambda_Example = new cdk.CfnResource(this, 'HandlerExample', {
      type : 'AWS::Lambda::Function',
      properties: {
        Runtime: "python3.8",
        Code: {
          ZipFile : fs.readFileSync(path.join(__dirname, '../lambda/Lambda_Example.py'),'utf8'),
        } ,
        Handler: 'index.lambda_handler',
        KmsKeyArn : k_key.keyArn,
        Environment : {
          Variables : {Region : REGION}, // for example region
        },
        Role : YOUR_ROLE
      }
    });
```
