### ISSUE TITLE
[codepipeline] Error : Artifact Bucket must have a KMS Key to add cross-account action

### ISSUE THREAD

**Issue by VXConsulting** [aws/aws-cdk#10846]
### Environment

  - **CLI Version      :*1.67*
  - **Framework Version:*1.67*
  - **Node.js Version:** 14.4.0
  - **OS               :*Windows 10*
  - **Language (Version):* TypeScript (4.0.3)*

--- 

This is :bug: Bug Report

**Comment by VXConsulting** [comment]
Sorry the code was dropped
` this.pipeline.addStage({
      stageName: 'Integration-Account-Deployment',
      actions: [
        new codepipelineActions.CloudFormationCreateUpdateStackAction({
          runOrder: 1,
          actionName: 'DeployChanges',
          stackName: this.stackNameToDeploy,
          adminPermissions: false,
          role: this.integrationDevOpsRole,
          deploymentRole: this.integrationChangeSetRole,
          parameterOverrides: {
            s3LambdaLayerCodeBucketName: lambdaLayerBuildArtifact.bucketName,
            s3LambdaLayerCodeBucketKey: lambdaLayerBuildArtifact.objectKey,
            s3LambdaCodeBucketName: lambdaBuildArtifact.bucketName,
            s3LambdaCodeBucketKey: lambdaBuildArtifact.objectKey
          },
          extraInputs: [lambdaBuildArtifact, lambdaLayerBuildArtifact],
          templatePath: this.cdkBuildArtifact.atPath(`${templatePath}`),
          capabilities: [cfn.CloudFormationCapabilities.NAMED_IAM, cfn.CloudFormationCapabilities.AUTO_EXPAND],
        })
      ]
    });`

**Comment by skinny85** [comment]
Hello @VXConsulting ,

thanks for opening the issue. A couple of questions:

1. Can you show where `integrationDevOpsRole` is created?
2. Can you show where is your Pipeline created?
3. Is the `CloudFormationCreateUpdateStackAction` supposed to be a cross-account Action? Or is it supposed to deploy to the same account the Pipeline is in?

Thanks,
Adam

**Comment by VXConsulting** [comment]
Hello @skinny85,

Thanks for your questions

integrationDevOpsRole is created in the destination account (integration) in a dedicated stack :
        
```
        new iam.Role(this, 'DevOpsRole', {
            roleName: 'DevOpsRole',
            assumedBy: new iam.AccountPrincipal(Accounts.devops),
        });
        
        new iam.Role(this, 'ChangeSetRole', {
            roleName: 'DevOpsChangeSetExecRole',
            assumedBy: new iam.ServicePrincipal('cloudformation.amazonaws.com'),
        });
```

2 Pipeline is created in devops account :
```
        //Bucket to store all the artifacts of the pipeline
        //to keep the same bucket and encryption key for the cross-account mecanism
        this.artifactBucket = props.technicalParameters.artifactBucket;
        this.encryptionKey = props.technicalParameters.encryptionKey;
```     
```
        //Pipeline creation
        const pipelineName = `${this.assetPrefix}-pipeline`;
        this.pipeline = new codepipeline.Pipeline(this, pipelineName, {
            pipelineName: pipelineName,
            artifactBucket: this.artifactBucket,
            restartExecutionOnUpdate: true,
        });
```
 ```
         //SET THE PERMISSIONS AND THE ROLES FOR CROSS-ACCOUNT DEPLOYMENT
        //---------------------------
        //Give the pipeline the capability to deploy in destination accounts
        const integrationAccountId = Accounts.integration;
```

        // const accountId = props.environmentToDeploy.environmentConfiguration.account;
        this.pipeline.addToRolePolicy(new PolicyStatement({
            resources: [
                `arn:aws:iam::${integrationAccountId}:role/DevOpsRole`,
            ],
            actions: ['sts:AssumeRole']
        }));

        //Assignement of the roles to deploy in the destination accounts
        const integrationDevopRoleName = this.assetPrefix + '-integration-devOpsRole';
        const integrationChangeSetRoleName = this.assetPrefix + 'integration-changeSetRole';
        this.integrationDevOpsRole = Role.fromRoleArn(this, integrationDevopRoleName, `arn:aws:iam::${integrationAccountId}:role/DevOpsRole`);
        this.integrationChangeSetRole = Role.fromRoleArn(this, integrationChangeSetRoleName, `arn:aws:iam::${integrationAccountId}:role/DevOpsChangeSetExecRole`);
```

 
3. It is a cross account action. Devops account has pipelines which execute action in destination accounts

Regards,
Olivier

**Comment by skinny85** [comment]
Can you show how this:

```ts
props.technicalParameters.artifactBucket;
```

Is created?

**Comment by VXConsulting** [comment]
Here is the creation script for the bucket and its encryption key in another stack.


```
    //Name of the bucket that will receive all the code package from XLRelease
    const bucketArtifactName = 'pipeline-artifact-bucket';
```

    //Encryption key for the BictbucketStore
    const keyName = `${bucketArtifactName}-encryptionkey`
    this.ArtifactBucketEncryptionKey = new Key(this, keyName, {
      description: 'EncryptionKey used by the main pipelines to access the content of the ' + bucketArtifactName,
      alias: keyName,
      trustAccountIdentities: true
    });

    //Bucket creation
    this.ArtifactBucket = new Bucket(this, bucketArtifactName, {
      blockPublicAccess: BlockPublicAccess.BLOCK_ALL,
      encryptionKey: this.ArtifactBucketEncryptionKey,
      encryption: BucketEncryption.KMS,
      bucketName: bucketArtifactName,
      versioned: true,
      removalPolicy: RemovalPolicy.DESTROY
    });

    //Securing the bucket
    this.ArtifactBucket.addToResourcePolicy(new PolicyStatement({
      effect: Effect.DENY,
      principals: [new AnyPrincipal()],
      resources: [this.ArtifactBucket.bucketArn + '/*'],
      actions: ["s3:*"],
      conditions: {
        "Bool": {
          "aws:SecureTransport": false
        }
      }
    }));

    this.ArtifactBucket.addToResourcePolicy(new PolicyStatement({
      effect: Effect.DENY,
      principals: [new AnyPrincipal()],
      resources: [this.ArtifactBucket.bucketArn + '/*'],
      actions: ["s3:PutObject"],
      conditions: {
        "StringNotEquals": {
          "s3:x-amz-server-side-encryption": "aws:kms"
        }
      }
    }));

    //Add permissions for the roles that will deploy the stack with cross-account mecanism
    //Give the pipeline the capability to deploy in destination accounts
    const integrationAccountId = Accounts.integration;
    const testAccountId = Accounts.test;
    const acceptanceAccountId = Accounts.acceptance;
    const productionAccountId = Accounts.production;

    //Assignement of the roles to deploy in the destination accounts
    const assetPrefix = 'devops';
    const integrationDevopRoleName = `${assetPrefix}-integration-devOpsRole`;
    const integrationChangeSetRoleName = `${assetPrefix}integration-changeSetRole`;
    const integrationDevOpsRole = Role.fromRoleArn(this, integrationDevopRoleName, `arn:aws:iam::${integrationAccountId}:role/DevOpsRole`);
    const integrationChangeSetRole = Role.fromRoleArn(this, integrationChangeSetRoleName, `arn:aws:iam::${integrationAccountId}:role/DevOpsChangeSetExecRole`);

    const testDevopRoleName = `${assetPrefix}-testDevOpsRole`;
    const testChangeSetRoleName = `${assetPrefix}-testChangeSetRole`;
    const testDevOpsRole = Role.fromRoleArn(this, testDevopRoleName, `arn:aws:iam::${testAccountId}:role/DevOpsRole`);
    const testChangeSetRole = Role.fromRoleArn(this, testChangeSetRoleName, `arn:aws:iam::${testAccountId}:role/DevOpsChangeSetExecRole`);

    const devopRoleName = `${assetPrefix}-acceptanceDevOpsRole`;
    const changeSetRoleName = `${assetPrefix}-acceptanceChangeSetRole`;
    const acceptanceDevOpsRole = Role.fromRoleArn(this, devopRoleName, `arn:aws:iam::${acceptanceAccountId}:role/DevOpsRole`);
    const acceptanceChangeSetRole = Role.fromRoleArn(this, changeSetRoleName, `arn:aws:iam::${acceptanceAccountId}:role/DevOpsChangeSetExecRole`);

    const productionDevopRoleName = assetPrefix + '-productionDevOpsRole';
    const productionChangeSetRoleName = assetPrefix + '-productionChangeSetRole';
    const productionDevOpsRole = Role.fromRoleArn(this, productionDevopRoleName, `arn:aws:iam::${productionAccountId}:role/DevOpsRole`);
    const productionChangeSetRole = Role.fromRoleArn(this, productionChangeSetRoleName, `arn:aws:iam::${productionAccountId}:role/DevOpsChangeSetExecRole`);

    this.ArtifactBucket.grantRead(new ArnPrincipal(integrationDevOpsRole.roleArn));
    this.ArtifactBucket.grantRead(new ArnPrincipal(integrationChangeSetRole.roleArn));

    this.ArtifactBucket.grantRead(new ArnPrincipal(testDevOpsRole.roleArn));
    this.ArtifactBucket.grantRead(new ArnPrincipal(testChangeSetRole.roleArn));

    this.ArtifactBucket.grantRead(new ArnPrincipal(acceptanceDevOpsRole.roleArn));
    this.ArtifactBucket.grantRead(new ArnPrincipal(acceptanceChangeSetRole.roleArn));

    this.ArtifactBucket.grantRead(new ArnPrincipal(productionDevOpsRole.roleArn));
    this.ArtifactBucket.grantRead(new ArnPrincipal(productionChangeSetRole.roleArn));

    this.ArtifactBucketEncryptionKey.addToResourcePolicy(new PolicyStatement({
      effect: Effect.ALLOW,
      principals: [
        new ArnPrincipal(integrationDevOpsRole.roleArn),
        new ArnPrincipal(integrationChangeSetRole.roleArn),
        new ArnPrincipal(testDevOpsRole.roleArn),
        new ArnPrincipal(testChangeSetRole.roleArn),
        new ArnPrincipal(acceptanceDevOpsRole.roleArn),
        new ArnPrincipal(acceptanceChangeSetRole.roleArn),
        new ArnPrincipal(productionDevOpsRole.roleArn),
        new ArnPrincipal(productionChangeSetRole.roleArn)],
      resources: ['*'],
      actions: [
        "kms:Decrypt",
        "kms:DescribeKey"
      ]
    }));

    this.ArtifactBucket.addToResourcePolicy(new PolicyStatement({
      effect: Effect.DENY,
      principals: [new AnyPrincipal()],
      resources: [this.ArtifactBucket.bucketArn + '/*'],
      actions: ["s3:*"],
      conditions: {
        "Bool": {
          "aws:SecureTransport": false
        }
      }
    }));

    this.ArtifactBucket.addToResourcePolicy(new PolicyStatement({
      effect: Effect.DENY,
      principals: [new AnyPrincipal()],
      resources: [this.ArtifactBucket.bucketArn + '/*'],
      actions: ["s3:PutObject"],
      conditions: {
        "StringNotEquals": {
          "s3:x-amz-server-side-encryption": "aws:kms"
        }
      }
    }));

    new CfnOutput(this, `${keyName}Arn`, {
      description: `encryption key Arn artifact files Bucket`,
      exportName: `${keyName}Arn`,
      value: this.ArtifactBucketEncryptionKey.keyArn,
    });

    new CfnOutput(this, `${bucketArtifactName}Arn`, {
      description: `artifact files Bucket Arn`,
      exportName: `${bucketArtifactName}Arn`,
      value: this.ArtifactBucket.bucketArn,
    });`

**Comment by VXConsulting** [comment]
Dear Adam,

I downgraded to 1.64 to be able to deploy (and I removed the crossAccountKeys props)

Regards,

**Comment by skinny85** [comment]
Sorry. I was asking what is the value of `props.technicalParameters.artifactBucket` in your code. Can you show that please?

Thanks,
Adam

**Comment by VXConsulting** [comment]
Sorry :-)
Here it is :

```
const pipelineArtifactBucketArn = Fn.importValue('pipeline-artifact-bucketArn');
        const artifactBucket = Bucket.fromBucketArn(this, 'artifactBucket', pipelineArtifactBucketArn);

 const technicalParameters: TechnicalStackParameters = {
            sourceBucketName: sourceBucketName,
            sourceObjectKey: sourceObjectKey,
            artifactBucket: artifactBucket,
            encryptionKey: encryptionKey
        }
```
Thanks
Olivier

**Comment by skinny85** [comment]
Yep, here's your issue:

```ts
        const artifactBucket = Bucket.fromBucketArn(this, 'artifactBucket', pipelineArtifactBucketArn);
```

You're importing the Bucket in the other Stack without a Key. Use `fromBucketAttributes`, passing the Key there, and everything will work.

Thanks,
Adam

**Comment by VXConsulting** [comment]
Hello Adam,

Thanks a lot, it works !

But why it was working before 1.64 with the current code and not anymore with 1.65 and further ?

Kind regards,
Olivier

**Comment by skinny85** [comment]
I would guess it's because we added some validations to this use-case here: #10396

Glad you were able to get it resolved @VXConsulting !

Let us know if you need anything more from us on this issue.

Thanks,
Adam
