### ISSUE TITLE
[lambda] which spelled as hwich in various places

### ISSUE THREAD

**Issue by Jerry-AWS** [aws/aws-cdk#10855]
It was reported by a customer in: https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-lambda.LayerVersionPermission.html

However, doing a quick search of the docs, it's actually in a number of source files. I'll hunt them down and put together a PR to address them.

---

This is a 📕 documentation issue

**Comment by shivlaks** [comment]
@Jerry-AWS  - I think it's just [this line](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-lambda/lib/layers.ts#L109) that needs updating. you can probably do it directly from the web UI for GitHub if you want to open a PR 🙂
