### ISSUE TITLE
[elbv2] support metric methods on IApplicationTargetGroup

### ISSUE THREAD

**Issue by jarias-opt** [aws/aws-cdk#10850]
ApplicationTargetGroup.FromTargetGroupAttributes returns an IApplicationTargetGroupProxy instead of IApplicationTargetGroup, as outlined in the documentation. This class cannot be cast to ApplicationTargetGroup

### Reproduction Steps

```c#
var targetGroup = (ApplicationTargetGroup) ApplicationTargetGroup.FromTargetGroupAttributes(this, "TargetGroup", new TargetGroupAttributes {
    TargetGroupArn = props.TargetGroupArn,
    LoadBalancerArns = props.LoadBalancerArn
});
_metric = targetGroup.MetricHttpCodeTarget(props.StatusCode);
```

### What did you expect to happen?

IApplicationTargetGroup is cast to ApplicationTargetGroup and returns HttpCode metric

### What actually happened?

On cdk synth:

`Unhandled exception. System.InvalidCastException: Unable to cast object of type 'Amazon.CDK.AWS.ElasticLoadBalancingV2.IApplicationTargetGroupProxy' to type 'Amazon.CDK.AWS.ElasticLoadBalancingV2.ApplicationTargetGroup'.`

### Environment

  - **CLI Version      :** 1.67.0
  - **Framework Version:** 1.67.0
  - **Node.js Version:**  v12.19.0
  - **OS               :** OSX 10.14.6
  - **Language (Version):**  .NET Core 3.1.200

### Other

--- 

This is :bug: Bug Report

**Comment by njlynch** [comment]
This isn't a bug. `FromTargetGroupAttributes` does not return a `ApplicationTargetGroup`, which is why you can't cast it to one. It *does* return a `IApplicationTargetGroupProxy`, which is a concrete implementation of a `IApplicationTargetGroup`.

`IApplicationTargetGroup` doesn't currently support the `metric*` methods, as the metrics need the load balancer name, which an imported group doesn't have (at the moment).

**Comment by jarias-opt** [comment]
Thanks for the response, that explanation makes sense. Is there any expectation that the metric methods will be added to IApplicationTargetGroup, or should I be looking for alternate solutions?

**Comment by njlynch** [comment]
We can convert this to a feature request for exposing the metric methods for `IApplicationTargetGroup`. I can't comment on or commit to a timeline when these will be added; however, pull requests are always appreciated!

**Comment by lenonestrella** [comment]
Hi, we have a separate cdk app for deploying all of our monitoring resources, and this feature would be helpful for us. Right now we are relying on creating and managing each of those metrics, which has proved to be a big effort.

In addition to ApplicationTargetGroup and ApplicationLoadBalancer, there are several other resources whose metrics could be exposed on the interface. Should I create a feature request for each of those resources?

**Comment by chillitom** [comment]
This feature would be very useful.  We use EKS with the aws-load-balancer-controller which defines and owns the target groups so our only option is to look them up when we want to define our monitor alarms via CDK.

**Comment by preeth1** [comment]
I continually get the error:

AttributeError: type object 'ApplicationTargetGroup' has no attribute 'fromTargetGroupAttributes'

In the python documentation, the function `fromTargetGroupAttributes` is only referenced as an alternative [to deprecated functions](https://docs.aws.amazon.com/cdk/api/v1/python/aws_cdk.aws_elasticloadbalancingv2/ApplicationTargetGroup.html?highlight=fromtargetgroupattributes#aws_cdk.aws_elasticloadbalancingv2.ApplicationTargetGroup.import_),but there is no documentation of this function itself.

**Comment by ysfaran** [comment]
In my case we separated resources from deployment. This means in our CI/CD pipeline we first have a job that creates all resources (ECS Cluster, ALB, TargetGroups, DynamoDB's etc..). Secondly all ECS services are created and deployed to the ECS cluster. 

Therefor we import the TargetGroup via `ApplicationTargetGroup.fromTargetGroupAttributes` during the second (deployment) step:

```ts
import elbv2 = require("aws-cdk-lib/aws-elasticloadbalancingv2")

const targetGroup = elbv2.ApplicationTargetGroup.fromTargetGroupAttributes(scope, `TargetGroup`, {
  targetGroupArn: myArn
})
```

And register the service + add a scaling metric for requests (`scaleOnRequestCount`):


```ts
import ecs = require("aws-cdk-lib/aws-ecs")

const service = new ecs.Ec2Service(this, "Service", { /* ... */ })

targetGroup.addTarget(service)

const scaling = service.autoScaleTaskCount({
  minCapacity: 1,
  maxCapacity: 4,
})

scaling.scaleOnRequestCount("RequestScaling", {
  requestsPerTarget: 1200,
  //  ERROR: Type 'IApplicationTargetGroup' is not assignable to type 'ApplicationTargetGroup'.
  targetGroup: targetGroup, 
})
```

Unfortunately `ApplicationTargetGroup.fromTargetGroupAttributes` only returns `IApplicationTargetGroup` and not `ApplicationTargetGroup` which ultimately leads to the error as seen in the snippet. 

I also tried to cast it but it will fail during runtime then:

```ts
//  ERROR: Invalid resource label 'undefined/undefined' for predefined metric type ALBRequestCountPerTarget
targetGroup: props.targetGroup as elbv2.ApplicationTargetGroup
```

Is there any *clean* way to get around this as of now? How to get the actual `ApplicationTargetGroup` instance?

**Comment by edisongustavo** [comment]
This issue was prematurely closed because I've tagged my initial PR (https://github.com/aws/aws-cdk/pull/23853) to close this issue.

This issue will actually be closed by https://github.com/aws/aws-cdk/pull/23993
