### ISSUE TITLE
[aws-apigatewayv2] No docs on Websocket APIs

### ISSUE THREAD

**Issue by rootulp** [aws/aws-cdk#10869]
https://docs.aws.amazon.com/cdk/api/latest/docs/aws-apigatewayv2-readme.html

The API Gateway V2 docs do not include a section on Websockets. I'm attempting to define a Websocket API gateway via CDK and there are no code samples for me to reference.

---

This is a 📕 documentation issue

**Comment by nija-at** [comment]
Unfortunately, we don't have any support for websockets as a higher level construct, hence no documentation. 

We're tracking the overall support of this here - https://github.com/aws/aws-cdk/issues/6830
