### ISSUE TITLE
[aws-codepipeline] Cyclic reference error when importing an S3 bucket in a code pipeline defined in a different stack 

### ISSUE THREAD

**Issue by harshchhatwani** [aws/aws-cdk#10896]
## :question: General Issue
Hi- I am using CDK to create a code pipeline with an S3 bucket as its source. The S3 bucket and code pipeline are defined in different stacks and per the AWS documentation we can access resources in a different stack as long as they are in the same account and AWS region: https://docs.aws.amazon.com/cdk/latest/guide/resources.html#resource_stack

### The Question

This doesn't seem to be working and I am getting a "Cyclic reference" error. Does this mean the AWS documentation is wrong? Or is there something in particular that's missing to make this work? Sample code below

```ts
        const pipelineSourceActionOutput = new Artifact();
        const pipelineSourceAction = new S3SourceAction({
            actionName: "S3SourceAction",
            bucket: s3Bucket, // Versioned Bucket (and CloudTrail) defined in a different stack
            bucketKey: `${id}/upload.zip`,
            output: pipelineSourceActionOutput,
            trigger: S3Trigger.EVENTS,
            runOrder: 1,
        });
        new Pipeline(this, pipelineId, {
            pipelineName: pipelineId,
            stages: [
                {
                    stageName: "Source",
                    actions: [pipelineSourceAction],
                }
            ],
        });
```

I think this line of code is causing the dependency of my stack containing S3 bucket on the stack that defined code pipeline infra: https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-codepipeline-actions/lib/s3/source-action.ts#L120-L124

### Environment

  - **CDK CLI Version:** 1.45.0
  - **Module Version:** 
  - **Node.js Version:** 12.x.31654.0
  - **OS:** OSX Mojave 
  - **Language (Version):** TypeScript

**Comment by skinny85** [comment]
Hello @harshchhatwani ,

can you show the exact error that you get?

Thanks,
Adam

**Comment by harshchhatwani** [comment]
Hi @skinny85: The stack trace contains confidential details of the project so I can't print that. Here's the obfuscated version

Error: 'Persistence-stack' depends on 'CodePipeline-stack' (PersistenceStack -> CodePipeline-stack/<PipelineName>/<StageName>/DeployToPrereleaseBucketAction/CodePipelineActionRole/Resource.Arn, PersistenceStack -> CodePipeline-stack/<PipelineName>/<StageName>/DeployToReleaseBucketAction/CodePipelineActionRole/Resource.Arn, PersistenceStack -> CodePipeline-stack/<PipelineName>/<StageName>/S3SourceAction/CodePipelineActionRole/Resource.Arn, PersistenceStack -> CodePipeline-stack/<PipelineName>/<StageName>/S3ExtractBinaryAction/CodePipelineActionRole/Resource.Arn). Adding this dependency (CodePipeline-stack -> Persistence-stack/UploadsBucket/Resource.Ref) would create a cyclic reference.

**Comment by skinny85** [comment]
@harshchhatwani can you try the solution mentioned here: https://github.com/aws/aws-cdk/issues/5657#issuecomment-571358504 , and see if that works for you?

**Comment by harshchhatwani** [comment]
Thanks for the pointer @skinny85: This did not work for me. I was able to get rid of cyclic error during build time with this, and even deploy the stack successfully but when I upload an object to the S3 bucket the pipeline fails with "Insufficient permissions
The provided role does not have permissions to perform this action."

Looks like this particular line of code is causing this. Without the above workaround, I get a "cyclic reference" error during the build and with the above workaround the role doesn't have required permissions
https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-codepipeline-actions/lib/s3/source-action.ts#L120-L124

**Comment by skinny85** [comment]
Oh I know why that is I think. It's because of this line:

```ts
            trigger: S3Trigger.EVENTS,
```

Can you comment out that line from your `S3SourceAction` @harshchhatwani , and see if that helps?

**Comment by harshchhatwani** [comment]
@skinny85 : That line is in place to use CloudTrail events to trigger the pipeline instead of having the pipeline poll S3 for updates, which is the recommended way per the AWS documentation. What would be the reason to comment this out?

Also, if possible, can we get this reproduced on your end to find the fix and thereby avoid the feedback loop of me trying potential workarounds? It'll save me the churn due to back and forth here. :)

**Comment by skinny85** [comment]
> @skinny85 : That line is in place to use CloudTrail events to trigger the pipeline instead of having the pipeline poll S3 for updates, which is the recommended way per the AWS documentation. What would be the reason to comment this out?

The reason would be it's the Event that is causing this cycle I believe.

 
> Also, if possible, can we get this reproduced on your end to find the fix and thereby avoid the feedback loop of me trying potential workarounds? It'll save me the churn due to back and forth here. :)

I did, and it did help locally.

**Comment by harshchhatwani** [comment]
So is the proposal to not use Event and instead have code pipeline poll the S3 bucket for changes?

**Comment by skinny85** [comment]
That's a temporary fix while I work on this more deeply, yes 🙂.

You can also try creating the Event explicitly in the Pipeline Stack, something like:

```ts
        const pipelineSourceAction = new S3SourceAction({
            actionName: "S3SourceAction",
            bucket: s3Bucket, // Versioned Bucket (and CloudTrail) defined in a different stack
            bucketKey: `${id}/upload.zip`,
            output: pipelineSourceActionOutput,
            trigger: S3Trigger.NONE,
            runOrder: 1,
        });


        const importedBucket = s3.Bucket.fromBucketName(this, 'ImportedBucket', s3Bucket.bucketName);
        importedBucket.onCloudTrailWriteObject('EventId', {
          target: new event_targets.CodePipeline(pipeline),
          paths: [`${id}/upload.zip`],
        });
```

That _should_ make it work with Events, without the need for polling.

**Comment by jzybert** [comment]
Had this same issue, but inside a single stack.

```
export class BuildStack extends DeploymentStack {
    constructor(scope: App, id: string, props: DeploymentStackProps) {
        super(scope, id, props);

        const repository = new Repository(this, 'Repository', {
            repositoryName: 'Application',
            description: 'Read-only CodeCommit repo.'
        });

        const accessLogsKey = new SecureKey(this, 'AccessLogsKey', {
            enableKeyRotation: true,
            trustAccountIdentities: true,
            alias: 'app-encryption-key'
        });
        accessLogsKey.addToResourcePolicy(new SecurePolicyStatement({
            effect: Effect.ALLOW,
            principals: [new SecureAccountRootPrincipal()],
            actions: [
                'kms:Decrypt',
                'kms:DecryptKey'
            ],
            resources: ['*']
        }));

        const accessLogsBucket = new SecureBucket(this, 'AccessLogsBucket', {
            bucketName: 'app-access-logs',
            blockPublicAccess: SecureBlockPublicAccess.BLOCK_ALL,
            encryption: BucketEncryption.KMS,
            encryptionKey: accessLogsKey,
            enforceSSL: true,
            // The access logs bucket can be exempt from requiring its own access logs bucket
            serverAccessLogsBucket: Exempt(undefined)
        });
        accessLogsBucket.addToResourcePolicy(new SecurePolicyStatement({
            effect: Effect.ALLOW,
            principals: [new SecureAccountRootPrincipal()],
            actions: [
                's3:GetObject*',
                's3:GetBucket*',
                's3:List*'
            ],
            resources: [accessLogsBucket.bucketArn, `${accessLogsBucket.bucketArn}/*`]
        }));

        const artifactBucket = new SecureBucket(this, 'ArtifactBucket', {
            bucketName: 'app-artifacts',
            encryption: Exempt(BucketEncryption.S3_MANAGED),
            enforceSSL: true,
            serverAccessLogsBucket: accessLogsBucket
        });
        artifactBucket.addToResourcePolicy(new SecurePolicyStatement({
            effect: Effect.ALLOW,
            principals: [new SecureAccountRootPrincipal()],
            actions: [
                's3:GetObject*',
                's3:GetBucket*',
                's3:List*'
            ],
            resources: [artifactBucket.bucketArn, `${artifactBucket.bucketArn}/*`]
        }));

        const project = new Project(this, 'Project', {
            projectName: 'Application-AutomatedBuild',
            source: Source.codeCommit({
                repository: repository
            }),
            environment: {
                buildImage: WindowsBuildImage.WIN_SERVER_CORE_2019_BASE,
                computeType: WindowsBuildImage.WIN_SERVER_CORE_2019_BASE.defaultComputeType,
            },
            role: new SecureRole(this, 'ProjectRole', {
                roleName: 'CodeBuildProjectRole-DO-NOT-DELETE',
                assumedBy: new SecureServicePrincipal('codebuild.amazonaws.com')
            }),
            artifacts: Artifacts.s3({
                bucket: artifactBucket,
                includeBuildId: false,
                packageZip: false
            })
        });

        // Required policies to access goshawk (in order to pull CodeArtifact NPM packages)
        project.addToRolePolicy(new SecurePolicyStatement({
            effect: Effect.ALLOW,
            actions: ['s3:GetObject'],
            resources: ['arn:aws:s3:::goshawk/*']
        }));
        project.addToRolePolicy(new SecurePolicyStatement({
            effect: Effect.ALLOW,
            actions: [
                'goshawk:GetAuthorizationToken',
                'goshawk:ReadFromRepository'
            ],
            resources: ['*']
        }));

        const pipeline = new Pipeline(this, 'Pipeline', {
            pipelineName: 'Application'
        });
        pipeline.node.addDependency(repository);
        pipeline.node.addDependency(project);

        const sourceOutput = new Artifact('sourceOutput');
        pipeline.addStage({
            stageName: 'Source',
            actions: [
                new CodeCommitSourceAction({
                    actionName: 'source',
                    repository: repository,
                    branch: 'mainline',
                    output: sourceOutput
                })
            ]
        });

        const buildOutput = new Artifact('BuildOutput');
        pipeline.addStage({
            stageName: 'Build',
            actions: [
                new CodeBuildAction({
                    actionName: 'build',
                    project: project,
                    input: sourceOutput,
                    outputs: [buildOutput]
                })
            ]
        });
    }
}
```

Error:
```
Deployment b4e1194a-cc3b-47ed-8e0c-a3248f68655d failed because Couldn't call cloudformation for target arn:aws:cloudformation:**hiding for privacy**:stack/BuildStack because of a validation error. The error was Circular dependency between resources: [PipelineArtifactsBucket4F67921F, PipelineBuildbuildCodePipelineActionRole11965005, PipelineRoleDefaultPolicy0AA25D2C, PipelineArtifactsBucketEncryptionKeyBC3B247B, PipelineRoleD3FFD1A8, PipelineE0CAC50E, PipelineSourcesourceCodePipelineActionRole57B371C3, ProjectRoleDefaultPolicyB1A21FB4, PipelineEventsRoleDefaultPolicyF485194A, PipelineBuildbuildCodePipelineActionRoleDefaultPolicyD6B23CEB, PipelineArtifactsBucketEncryptionKeyAliasC972AB70, RepositoryBuildStackPipeline69086EB1mainlineEventRule74A5046C, PipelineEventsRole8A77C29A, PipelineSourcesourceCodePipelineActionRoleDefaultPolicyE2FCF43C, ProjectC78D97AD] (Service: AmazonCloudFormation; Status Code: 400; Error Code: ValidationError; Request ID: 2955d618-68f2-4cb6-b488-91415d536a22; Proxy: null)
```

**Comment by skinny85** [comment]
@jzybert in the pipeline, you shouldn't provide `source` and `artifacts` for a CodeBuild Project, because those are controlled through the pipeline itself.

Use the `PipelineProject` class instead of `Project`, and that will become much more clear 🙂.

**Comment by jzybert** [comment]
@skinny85 Having a follow up issue with cyclical references. I got my `PipelineProject` working which exists in account A in us-west-2, and have the following stage action:
```
new S3DeployAction({
    actionName: 'deployToAlpha',
    input: alphaBuildOutput,
    bucket: Bucket.fromBucketAttributes(this, 'AlphaBucket', {
        bucketName: 'my-app-releases-alpha'
        region: 'us-east-1' // Having this line causes the below error
    })
})
```

Error:
```
Error: Resolution error: Resolution error: Resolution error: Resolution error: Resolution error: Only DeploymentStack or SupportingStack can be used as dependencies.
Object creation stack:
  at Execute again with CDK_DEBUG=true to capture stack traces.
Object creation stack:
  at Execute again with CDK_DEBUG=true to capture stack traces.
Object creation stack:
  at Execute again with CDK_DEBUG=true to capture stack traces..
```

If I remove the `region`, there are no errors.
