### ISSUE TITLE
[aws-apigateway]- BinaryMediaType multipart/form-data is not getting added to RestApi using cdk 

### ISSUE THREAD

**Issue by devendra-kumar1** [aws/aws-cdk#10891]
### The Question
BinaryMediaType **multipart/form-data** is not getting added to RestApi using cdk.
### Environment

  - **CDK CLI Version:**  1.63
  - **Module Version:**  1.63
  - **Node.js Version:** 12
  - **OS:** Windows 10
  - **Language (Version):** TypeScript (3.8.3)

I am having a ApiGateway. In this under setting i want to add BinaryMediaType i.e.  **multipart/form-data** using RestApi construct of cdk. But it is not getting added. How ever i am trying to add **image/png,image/jpeg, application/octet-stream** using same construct, it is getting added. Is **multipart/form-data** is not supported using CDK or do we have any workaround for that ?

FYI i used below code snipped.

1. binaryMediaTypes: ['image/png','multipart/form-data','image/jpeg','application/octet-stream']
2. binaryMediaTypes: ['image/png','multipart~1form-data','image/jpeg','application/octet-stream']

None of them is adding multipart/form-data to BinaryMediaType.

**Comment by devendra-kumar1** [comment]
I followed mentioned approach as well in below link. But no luck :( 
https://forums.aws.amazon.com/thread.jspa?messageID=797934

**Comment by devendra-kumar1** [comment]
@nija-at any update on this issue ?

**Comment by nija-at** [comment]
As far as the CDK is concerned, we just pass on the strings provided for `binaryMediaTypes` to CloudFormation. 
https://github.com/aws/aws-cdk/blob/8058b38a90529b7d5cf8bf6461bbe0f4f914620a/packages/%40aws-cdk/aws-apigateway/lib/restapi.ts#L689

What is the value of [`BinaryMediaTypes` property](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-restapi.html#cfn-apigateway-restapi-binarymediatypes) in the generated CloudFormation? If the value you expect exists there, the CDK has done the correct thing.

You may have to reach out to the APIGateway service team on how they're processing that property.

**Comment by devendra-kumar1** [comment]
@nija-at Thanks for your points. Please find below CFN getting generated after cdk synth.

AegonRestApi2C91294D:
    Type: AWS::ApiGateway::RestApi
    Properties:
      BinaryMediaTypes:
        - multipart/form-data

But it is not getting set on API GW level.

**Comment by devendra-kumar1** [comment]
If there is no action from your side then can you please pass this to relevant team

**Comment by SomayaB** [comment]
@devendra-kumar1 I've forwarded your issue to the apigateway team and will update this issue when they respond.

**Comment by devendra-kumar1** [comment]
Thanks @SomayaB

**Comment by SomayaB** [comment]
@devendra-kumar1 can you provide the code you used that produced the error? Also, are you using swagger/openapi?

**Comment by SomayaB** [comment]
@devendra-kumar1 Both the Apigateway engineer using Cloudformation and I using the CDK with the first option you provided ```binaryMediaTypes: ['image/png','multipart/form-data','image/jpeg','application/octet-stream']``` wwere able to successfully add `multipart/form-data`. Maybe check your code again? Are you getting any error messages?

**Comment by devendra-kumar1** [comment]
@SomayaB  I am not getting error message. Now i can see things are working as expected. Will open this issue if issue occures
