### ISSUE TITLE
[@aws-cdk/aws-elasticloadbalancingv2]  Having issue with importing existing listener Certificate

### ISSUE THREAD

**Issue by shreyasmm** [aws/aws-cdk#10894]
### The Question

  Having issue when importing  new listener certificate from certificateArn. (As per Docs https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-elasticloadbalancingv2.ListenerCertificate.html)
````
   // having issue when importing this
   this.certificate = new elb.ListenerCertificate(certificateArn: props.certificateArn);

    if( props.appListeningProtocol === common.ApplicationProtocol.HTTP )
      this.listener = this.applicationLoadBalancer.addListener('Listener',{
        defaultTargetGroups: [this.targetGroup],
        port: props.appListeningPort,
        protocol: props.appListeningProtocol
      });
    else
      this.listener = this.applicationLoadBalancer.addListener('Listener',{
        defaultTargetGroups: [this.targetGroup],
        port: props.appListeningPort,
        protocol: props.appListeningProtocol,
        sslPolicy: elb.SslPolicy.RECOMMENDED,
        certificates: [this.certificate]
      });

````
The Issue is Constructor of class 'ListenerCertificate' is protected and only accessible within the class declaration.

![cert](https://user-images.githubusercontent.com/2624635/96153410-4a549680-0f2b-11eb-8399-621eef654366.png)

I might be doing something wrong also

### Environment

  - **CDK CLI Version:** 1.67.0 (build 2b4dd71)
  - **Module Version:** "@aws-cdk/aws-elasticloadbalancingv2": "1.67"
  - **Node.js Version:** v12.18.3
  - **OS:** Ubuntu20.04 - Pop!os 20.04
  - **Language (Version):** TypeScript (3.8.3)

### Other information
the problem i think is in this line https://github.com/aws/aws-cdk/blob/v1.67.0/packages/@aws-cdk/aws-elasticloadbalancingv2/lib/shared/listener-certificate.ts#L36  where constructor is made protected

```
  protected constructor(certificateArn: string) {
    this.certificateArn = certificateArn;
  } 
```
i can use this way also but certificateArns - This API element is deprecated. Its use is not recommended as per CDK docs https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-elasticloadbalancingv2.ApplicationListener.html
```
  const listener = this.applicationLoadBalancer.addListener('Listener', { 
    port: 443, 
    certificateArns: [props.certificateArn] 
  });
```

**Comment by njlynch** [comment]
Rather than use the constructor directly, use one of the provided factory methods (`fromArn` or `fromCertificateManager`).

```ts
this.certificate = elb.ListenerCertificate.fromArn(props.certificateArn);
```

**Comment by shreyasmm** [comment]
thank for update, it works,  do you think documentation (https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-elasticloadbalancingv2.ListenerCertificate.html) needs to be updated and remove this  

new ListenerCertificate(certificateArn: string)

**Comment by MrArnoldPalmer** [comment]
`this.certificate = new elb.ListenerCertificate(certificateArn: props.certificateArn);` is not a valid call of the constructor. Should be:

```
this.certificate = new elb.ListenerCertificate(props.certificateArn);
```

**Comment by njlynch** [comment]
Sure, @shreyasmm - I've opened #10992 to track the documentation improvements. Thanks!
