### ISSUE TITLE
[ecs-patterns] taskDefinition option different between Fargate ALB and QueueProcessing services

### ISSUE THREAD

**Issue by abbottdev** [aws/aws-cdk#10909]
### The Question

The signature for creating a `ApplicationLoadBalancedFargateService` contains a `taskDefinition` parameter which is expected for a `FargateTaskDefinition`.  However, this option is missing for a `QueueProcessingFargateService`.

I was expecting to be able to customise the taskRole, but there could be reasons why you dont specify it for this service - alternatively it could be an API inconsistency so thought I best raise it in case it's not just me!

### Environment

  - **CDK CLI Version:** 
  - **Module Version:** 1.65.0
  - **Node.js Version:** v12.4.0
  - **OS:** Ubuntu
  - **Language (Version):** Typesript

### Other information

The documentation for the relevant option is here:
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs-patterns.ApplicationLoadBalancedFargateService.html

But missing from here:
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs-patterns.QueueProcessingFargateService.html

> 
> taskDefinition? | FargateTaskDefinition | The task definition to use for tasks in the service. TaskDefinition or TaskImageOptions > must be specified, but not both.
>  -- | -- | --

**Comment by NGL321** [comment]
Hey @abbottdev,

After looking at the source, I cant see any reason that you couldn't define `taskDefinition` as a prop for the `QueueProcessingFargateService` construct (task definition is [set internally](https://github.com/aws/aws-cdk/blob/c2f38e80fe5c1df36cffe8762c42fbc89caed0a3/packages/%40aws-cdk/aws-ecs-patterns/lib/fargate/queue-processing-fargate-service.ts#L83-L88) and passed same as with the `ApplicationLoadBalancedFargateService`.

I am going to change this to a feature-request to add the additional customization ability.

@MrArnoldPalmer / @SoManyHs is this something we could implement?

😸 😷

**Comment by SoManyHs** [comment]
Hi @abbottdev!

Thanks for opening this issue -- you're right, we had added the `taskDefinition` field as part of the initializer properties for the other patterns in https://github.com/aws/aws-cdk/pull/4213, and must have just missed it on the QueueProcessing Services. We can definitely add this -- thanks for the catch!

**Comment by SoManyHs** [comment]
Somewhat related: https://github.com/aws/aws-cdk/pull/11093
