### ISSUE TITLE
[cli] Assets.grantRead() does not manage associated KMS key for the bootstrap S3 bucket

### ISSUE THREAD

**Issue by mark-ship-it** [aws/aws-cdk#10904]
While trying to access assets in S3, IAM permissions do not include grants for the custom kms key from the bootstrap stack.  Even after `Assets.grantRead()`

### Reproduction Steps

```
import * as assets from '@aws-cdk/aws-s3-assets';
this.box = new ec2.Instance(this, 'box', {} ); 

const pgAssets = new assets.Asset(this, 'pgAssets', {
      ...
 });

this.box.node.addDependency(pgAssets);
pgAssets.grantRead(this.box.role);

const pgAssetsPath = this.box.userData.addS3DownloadCommand({
      bucket: pgAssets.bucket,
      bucketKey: pgAssets.s3ObjectKey,
});

this.box.addUserData(`
echo "${pgAssetsPath}" > /tmp/pgAssetsPath.txt 
unzip -o "${pgAssetsPath}" -d "$PG_DATA" 
`);

```
### What did you expect to happen?
I thought the unzip would work

### What actually happened?
The file was never downloaded to the EC2 instance due to lack of KMS permissions

In order for the S3 download to work, I had to add the following hack, which should be handled by `Assets.grantRead()`
```
this.box.role.addToPrincipalPolicy(
      new iam.PolicyStatement({
        actions: ['kms:*'],
        effect: iam.Effect.ALLOW,
        resources: ['*'],
      }),
);
```
### Environment
- **CDK Version:** 1.66.0
  - **Node.js Version:** very recent
  - **OS               :** Linux
  - **Language (Version):** Typescript
### Proposed Solution

Need a simple mechanism to find the custom KMS key involved in the bootstrap stack.  
I propose caching the value of the default `Qualifier` as well as the default KMS key in an SSM parameter

We also need to update the `Assets.grantRead()` to transparently handle the kms key

### Other

I see there is support for multiple bootstrap stacks.   I am unsure how to provide a fix when there are multiple bootstrap stacks, as the ssm parameter convention will assume the default `Qualifier` parameter.

* [X] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is :bug: Bug Report

**Comment by ahammond** [comment]
Which kms key and why do you need to look it up?

**Comment by ahammond** [comment]
You're talking about the one that's included in the CDK Toolkit and used for the Assets bucket, right?

**Comment by rix0rrr** [comment]
Can you check the `Outputs` section of your bootstrap stack and tell me the version number?
