### ISSUE TITLE
[pipelines] GitHubSourceAction in README uses default branch 'master' which is no longer the default branch on GitHub

### ISSUE THREAD

**Issue by yattoni** [aws/aws-cdk#10906]
GitHubSourceAction in README uses default branch 'master' which is no longer the default branch on GitHub

Issue is here:
https://docs.aws.amazon.com/cdk/api/latest/docs/pipelines-readme.html
more specifically
https://github.com/aws/aws-cdk/blame/1fbb8bcc5f1aa76710d286f78a59370438a7d0a4/packages/%40aws-cdk/pipelines/README.md#L145-L152

Following the README will cause the first attempt to deploy fail because the pipeline will try and pull from the 'master' branch which does not exist. This is a poor customer experience having to make another pr to change the branch.

The [codepipeline-actions README](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-codepipeline-actions-readme.html#github) already accounts for this:
```
const sourceAction = new codepipeline_actions.GitHubSourceAction({
  actionName: 'GitHub_Source',
  owner: 'awslabs',
  repo: 'aws-cdk',
  oauthToken: cdk.SecretValue.secretsManager('my-github-token'),
  output: sourceOutput,
  branch: 'develop', // default: 'master'
});
```

I propose just adding `branch: 'main', // default: 'master'` to the pipelines README.

---

This is a 📕 documentation issue

**Comment by skinny85** [comment]
Sounds good @yattoni , care to open us a PR fixing this? Here's our docs: https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md

Thanks,
Adam

**Comment by yattoni** [comment]
Sure, I can open a PR @skinny85
