### ISSUE TITLE
[aws-iam] User.fromUserName incorrectly implemented addToPolicy

### ISSUE THREAD

**Issue by necoyam** [aws/aws-cdk#10913]
### Reproduction Steps

iam.User.fromUserName(scope, "test-user-id", "test-user").addToPolicy(policyStatement);

### What did you expect to happen?

Expected policy statement to be added to imported user or throw exception saying "Cannot add policy to imported user"

### What actually happened?

Exception thrown with confusing message saying cannot add inline policy to imported user

### Environment

  - **CLI Version      :**
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):** 

### Other

I can see other methods are meant to be blocked from the code: https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-iam/lib/user.ts#L163-L173

However, addToPolicy() is not blocked which make me think this is allowed. https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-iam/lib/user.ts#L150-L161

Apparently, this is not true as it calls Policy.attachToUser() which then loop back to attachInlinePolicy: https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-iam/lib/policy.ts#L179-L183

This is really confusing and I think either one of below options make sense
* fix addToPolicy() to not throw exception by using unsupported operation
* immediately throw exception with correct error message saying addToPolicy is not supported for imported user.

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
I agree that it could just work.

**Comment by ariain** [comment]
Hi @rix0rrr, can I give it a try??

**Comment by wtho** [comment]
@ariain yes you can, just submit a PR following contribution guidelines and reference this issue. Most issues are open for PRs and especially `good first issue` labeled issues are.

**Comment by ariain** [comment]
Hi @wtho, as I was going through the code, I found out these 2 functions which will give the same error in the end `Cannot add inline policy to imported User`
So, I have to just block these functions here at these lines, right??
https://github.com/aws/aws-cdk/blob/a73a4ee983d0a17c1c6b58ba49146284582f2bb0/packages/%40aws-cdk/aws-iam/lib/user.ts#L150-L161
