### ISSUE TITLE
[rds] Can't export the secret name from a DatabaseCluster

### ISSUE THREAD

**Issue by ericzbeard** [aws/aws-cdk#10914]
It is not possible to export the name of the secret that is generated by the DatabaseCluster construct.

### Reproduction Steps

```python
        # Create the cluster
        cluster = rds.DatabaseCluster(
            self,
            "Database",
            engine=rds.DatabaseClusterEngine.aurora_mysql(
                version=rds.AuroraMysqlEngineVersion.VER_2_09_0
            ),
            instance_props={
                "instance_type": ec2.InstanceType.of(
                    ec2.InstanceClass.BURSTABLE2, ec2.InstanceSize.MEDIUM
                ),
                "vpc_subnets": {"subnet_type": ec2.SubnetType.PRIVATE},
                "vpc": vpc,
                "security_groups": [aurora_sg],
            },
        )

        # Output RDS secret name
        _ = core.CfnOutput(
            self,
            "MySecretOut",
            value=cluster.secret.secret_name,
            export_name="my-secret-name",
        )
```

### What did you expect to happen?

The secret name should be exported in the synthesized template.

### What actually happened?

The resource in the template is missing the Value, which causes a deployment failure.

```json
    "MySecretOut": {
      "Export": {
        "Name": "my-secret-name"
      }
    }
```

### Environment

  - **CLI Version      :** 1.68
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):** 

### Other

We should also modify CfnOutput to fail when the value provided is undefined.

--- 

This is :bug: Bug Report

**Comment by mfsjr** [comment]
I'm experiencing this as well.
