### ISSUE TITLE
[cli] `cdk deploy *` Tries to Deploy README.md as a Stack

### ISSUE THREAD

**Issue by joel-aws** [aws/aws-cdk#10918]
When running `cdk ls` I get:

```bash
stack-1
stack-2
```
However, when I run `cdk deploy *` I get the following error:

`No stack found matching 'README.md'. Use "list" to print manifest`

When I run `cdk deploy * -v`, I see the following listed under "command line arguments":

```
  STACKS: [
    'README.md',
    'app.py',
    'cdk.context.json',
    'cdk.json',
    'cdk.out',
    'config.json',
    'requirements.txt',
    'setup.py',
    'source.bat',
    'src'
  ],
  'S-t-a-c-k-s': [
    'README.md',
    'app.py',
    'cdk.context.json',
    'cdk.json',
    'cdk.out',
    'config.json',
    'requirements.txt',
    'setup.py',
    'source.bat',
    'src'
  ]
```

### Reproduction Steps

```bash
cdk init --language=python
source .env/bin/activate
pip install -r requirements.txt
cdk deploy *
```

### What did you expect to happen?

I expected `stack-1` and `stack-2` to deploy.

### What actually happened?

A non-stack ("README.md") was listed as a stack and an error occurred when trying to deploy it.

### Environment

  - **CLI Version      : *aws-cli/2.0.57 Python/3.9.0 Darwin/19.6.0 source/x86_64*
  - **Framework Version: *1.68.0 (build a6a3f46)*
  - **Node.js Version: *v14.14.0*
  - **OS               : *MacOS 10.15.7*
  - **Language (Version): *Python 3.7.8*

--- 

This is :bug: Bug Report

**Comment by hoegertn** [comment]
The * is interpreted by your shell and replaced with a list of all files and directories in the current folder. You need to put it in single quotes like cdk deploy '*'
