### ISSUE TITLE
[cdk-pipelines] ShellScriptAction: add option to configure build image (and other environment settings)

### ISSUE THREAD

**Issue by arpowers** [aws/aws-cdk#10919]
Hey guys, great work on CDK! 

Looks like I found a bug/bottleneck/critical-feature in the Pipeline construct. Namely, you can't set the environment for certain steps like the `ShellScriptAction`.  In my case, I'm using Node 14 and I get errors like: 

```bash
The engine "node" is incompatible with this module. Expected version ">=14.0.0". Got "12.18.0"
```

In the synth actions, it allows me to set the image, just not in further steps. 

A quick scan of the codebase suggests the problem is here: 
https://github.com/aws/aws-cdk/blob/36fea2824787f47692e78fb5de063f89f5c7da5d/packages/%40aws-cdk/pipelines/lib/validation/shell-script-action.ts#L180

### Reproduction Steps

- Set `package.json` Node engine to `14`
- Run `ShellScriptAction` during pipeline process

### What did you expect to happen?

Would allow me to set the build environment. 

### What actually happened?

The environment is hard-coded.

**Comment by rix0rrr** [comment]
As a workaround, you can create a CodeBuild project directly and add it to the pipeline, rather than having one created for you. This gives you more flexibility.

**Comment by tdikland** [comment]
I will try to implement this in the coming days.
