### ISSUE TITLE
[s3]  applied CORS rule to a bucket is not applied

### ISSUE THREAD

**Issue by jansedlon** [aws/aws-cdk#10910]
If I try to apply CORS rule to a bucket, it's not applied. It's not even in the Cloudformation template after typing `cdk synthesize`

### Reproduction Steps

```
   const filesBucket = new s3.Bucket(this, "UnibuddyFilesStorageS3", {
      bucketName: 'unibuddy-files'
    });

    filesBucket.addCorsRule({
      allowedHeaders: ["*"],
        allowedOrigins: ["*"],
        allowedMethods: [HttpMethods.GET],
    })
```
### What did you expect to happen?

To Apply CORS rule

### What actually happened?

There's no error. It behaves like I didn't even applied that. Both `addCorsRule` and specifying it in a constructor doesn't work.

### Environment

  - **CLI Version      :** aws-cli 2.0.53
  - **Framework Version:** CDK 1.68.0
  - **Node.js Version: v14.12.0** 
  - **OS               :** MacOS Big Sur Beta 10
  - **Language (Version):** Typescript 4.0.3

### Other

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment]
@jansedlon I'm not able to reproduce this.

Given this code:

```ts
const bucket = new s3.Bucket(this, 'Bucket');
bucket.addCorsRule({
  allowedHeaders: ["*"],
  allowedOrigins: ["*"],
  allowedMethods: [s3.HttpMethods.GET],
})
```

I get the following CloudFormation resource:

```json
"Bucket83908E77": {
  "Type": "AWS::S3::Bucket",
  "Properties": {
    "CorsConfiguration": {
      "CorsRules": [
        {
          "AllowedHeaders": [
            "*"
          ],
          "AllowedMethods": [
            "GET"
          ],
          "AllowedOrigins": [
            "*"
          ]
        }
      ]
    }
  },
  "UpdateReplacePolicy": "Retain",
  "DeletionPolicy": "Retain",
  "Metadata": {
    "aws:cdk:path": "CorsBucket/Bucket/Resource"
  }
},
```

Can you share the CloudFormation template you get?
