### ISSUE TITLE
[assert] RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by markusl** [aws/aws-cdk#10926]
After trying to update some projects to AWS CDK 1.68.0 I'm seeing the following behavior in our unit tests:

```
    RangeError: Maximum call stack size exceeded

      at deepCopy (node_modules/@aws-cdk/cloudformation-diff/lib/diff-template.ts:168:18)
      at deepCopy (node_modules/@aws-cdk/cloudformation-diff/lib/diff-template.ts:176:18)
          at Array.map (<anonymous>)
      at deepCopy (node_modules/@aws-cdk/cloudformation-diff/lib/diff-template.ts:170:14)
[...]
      at deepCopy (node_modules/@aws-cdk/cloudformation-diff/lib/diff-template.ts:176:18)
          at Array.map (<anonymous>)
      at deepCopy (node_modules/@aws-cdk/cloudformation-diff/lib/diff-template.ts:170:14)
```

`cdk synth` for the stack in question seems to produce a proper template. Any ideas what might cause this?

### Reproduction Steps

The test cases are pretty much in this form: 

```ts
import { expect as expectCDK, matchTemplate, MatchStyle } from '@aws-cdk/assert';
import * as cdk from '@aws-cdk/core';
import { ExampleStack } from '../lib/example-stack';

test('ExampleStack', () => {
  const app = new cdk.App();
  // WHEN
  const stack = new ExampleStack(app, `ecs-stack`);

  // THEN
  const expected = {
    'Resources': {
        /// ... resource definitions
    }
  };

  expectCDK(stack).to(matchTemplate(expected, MatchStyle.SUPERSET));
});

```

### Environment

  - **CLI Version      :** 1.68.0
  - **Framework Version:** 1.68.0
  - **Node.js Version:** v14.8.0
  - **OS               :** macOs
  - **Language (Version):** TypeScript 4

### Other

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
Not clear. We're using assert library across the entire CDK repo and haven't seen this.

Can you provide an example where I can reproduce this error?

**Comment by markusl** [comment]
@nija-at I see. I think what is different in our case was including a CDK construct with a different version (<1.68.0) of CDK libraries (and assert library) as part of the main CDK project with a library version 1.68.0. I wasn't able to figure out why this happened, but now after upgrading the main project to CDK 1.70.0 the problem went away. I'll get back to this if it happens again.

**Comment by MAGilleeney** [comment]
Sorry for commenting on closed issue, however this is the only solution i found that helped me. Markusl is correct that this was from a version mismatch however in my case i had a version mismatch when I added a new contruct so i used npm-check -u to update all versions. Running my tests gave the exact same error above, even though my versions were in sync. 

Deleting package-lock.json & node_modules and reinstalling packages fixed the issue.

**Comment by stocks29** [comment]
@MAGilleeney 's solution worked for me as well. I had all versions in sync, but was getting call stack errors running tests until I deleted package-lock.json and node_modules and reinstalled.

**Comment by niklaswallerstedt** [comment]
I have a similar issue in a monorepo where each cdk app is a "package". My `devDependencies` are all hoisted to the root package.json. Moving @aws-cdk/assert from the root to the leaf node resolves the error. Not really what I wanted but it works 🤷

**Comment by wizofaus** [comment]
I still get this all the time (even with the latest version of cdk, though still using node 12.2.3), but I noticed that if I just re-run the command it typically works fine, so every I need cdk deploy now I just retry if it fails.

**Comment by praveen-fiserv** [comment]
After change my @aws-cdk/core "@aws-cdk/core": "^1.116.0"  version and re-install packages. Try the "npm run build" and "npm run test".

Thankyou so much @solsen-tl

> Same issue and solution for me. I had this for example:
> 
> ```
> <snip>
>     "@aws-cdk/aws-s3-deployment": "^1.116.0",
>     "@aws-cdk/core": "1.116.0",
> <snip>
> ```
> 
> Once I updated to `"@aws-cdk/core": "^1.116.0"` (with `^`), blew away my package-lock.json and node_modules folder, and `npm i`, then my `npm test` worked fine again. 🙄
> 
> (Note: it could have been caused by the `npm audit fix` I ran too.)
