### ISSUE TITLE
[cloudfront] can’t deploy cloudfront distribution with logging bucket in China regions 

### ISSUE THREAD

**Issue by zxkane** [aws/aws-cdk#10923]
It’s introduced by #10512 

Looks like it’s not all partitions CloudFront allowing the global s3 domain name. My CDK app met below error after upgrading to 1.68.0 in China region(cn-northwest-1),

```
4:04:39 PM | UPDATE_FAILED        | AWS::CloudFront::Distribution                   | CloudFrontDist/CFDistribution
The parameter Logging Bucket is invalid. The bucket is in a Region that you cannot send logs to with this distribution. (Service: AmazonCloudF
ront; Status Code: 400;
```

### What did you expect to happen?

deploy the cloudfront distribution with logging bucket specified

### What actually happened?

failed to deploy the stack

### Environment

  - **CLI Version      :** 1.68.0
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):** 

### Other

--- 

This is :bug: Bug Report

**Comment by njlynch** [comment]
Thanks for the bug report, and sorry for the breakage. We will revert the change to the logging bucket usage, and work with the CloudFront team to fix the original console issue that triggered the change.
