### ISSUE TITLE
[ecs-service-extensions] add listener rules to a `ServiceDescription`

### ISSUE THREAD

**Issue by misterjoshua** [aws/aws-cdk#10937]
I'd like to expose a service produced via `ServiceDescription` through a pre-existing Application Load Balancer listener.

### Use Case
We often share application load balancers between services in single ECS clusters as a cost-saving measure. Because of this, I'd like support from the new ECS service extension paradigm for creating listener rules.

### Proposed Solution
I think that we could introduce an extension that produces both the target group and listener rules.

### Other
I've created a pull request that shows a detailed solution.

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by nathanpeck** [comment]
I'm thinking about making the preexisting `HttpLoadBalancerExtension` accept a preexisting ALB as an optional parameter.
