### ISSUE TITLE
[aws-rds]  ServerlessCluster Snapshot Restore

### ISSUE THREAD

**Issue by tre-dev** [aws/aws-cdk#10936]
The ability to create a `ServerlessCluster` via snapshot.

### Use Case

I'm using `ServerlessCluster` to spin up an Aurora Serverless Cluster and for staging/testing environments, it would be great to have the ability to use a snapshot.

### Proposed Solution

I suggest an implementation similar to #10130

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by machielg** [comment]
this is supported via the AWS Console, having this feature would be a great to migrate existing RDS to serverless

**Comment by 1559550282** [comment]
Hi, Is this feature avalible now? we would like to restore the exisiting aurora database to aurora serverless for dev and testing env with CDK.
Thanks,

**Comment by jacobevans** [comment]
Is there a workaround for this missing feature that anyone's come up with?

**Comment by davenix-palmetto** [comment]
Would love this as well for our use cases. Any word on development? Thanks in advance!

**Comment by dnix** [comment]
This would be very useful for our use cases as well. Any word on development or timeline? Thanks in advance!

**Comment by nrawling** [comment]
> Is there a workaround for this missing feature that anyone's come up with?

You can create a serverless cluster then move schema and data into it via DMS or mysqldump.

**Comment by jumic** [comment]
I've started implementing this feature. I can probably create a pull request in the next few days.
