### ISSUE TITLE
[aws-rds] Availability Zone parameter silently removed from stack when MultiAZ is true

### ISSUE THREAD

**Issue by neovasili** [aws/aws-cdk#10949]
If you have a DB instance created with the `availability_zone` parameter setted and also set `multi_az` parameter to `true` then CDK simply generates the CloudFormation template removing the `availability_zone` setting because, both parameters cannot be used at the same time.

The issue is that the developer doesn't have any visibility on that, so suppose that later in another deploy `multi_az` is setted to `false`, then CDK will consider the `availability_zone` parameter and probably try to make a DB instance replacement due to an AZ change.

### Reproduction Steps

```python
#!/usr/bin/env python3

from aws_cdk import core

from aws_cdk import (
  aws_ec2 as ec2,
  aws_rds as rds,
  core
)


class Cdk167RdsStack(core.Stack):

  def __init__(self, scope: core.Construct, id: str, **kwargs) -> None:
    super().__init__(scope, id, **kwargs)

    vpc = ec2.Vpc.from_lookup(
      self,
      "vpc",
      vpc_id="vpc-xxxxxxxxxxx"
    )

    rds.DatabaseInstance(
      self,
      'DBInstance',
      engine=rds.DatabaseInstanceEngine.postgres(
        version=rds.PostgresEngineVersion.of(
          postgres_full_version="12.3",
          postgres_major_version="12"
        )
      ),
      vpc=vpc,
      availability_zone=vpc.availability_zones[0],
      multi_az=False,
    )

app = core.App()
Cdk167RdsStack(app, "cdk-1-67-rds", env={'region': 'eu-west-1', 'account': 'XXXXXXXXXXXX'})

app.synth()
```

Then change `multi_az` to `True` and synth again.

### What did you expect to happen?

If both parameters are setted at the same time, there must be some kind of exception (IncompatibleParameters or something like that) or at least a warning before apply the change.

### What actually happened?

No warning or exception is shown to the developer, so he/she cannot be aware about the removal of `availability_zone` from CloudFormation output template when `multi_az` is `True`.

### Environment

  - **CLI Version      :** aws-cli/1.18.115 Python/3.8.5 Darwin/19.6.0 botocore/1.17.38  CDK -> 1.67
  - **Framework Version:** 1.67
  - **Node.js Version:** v14.7
  - **OS               :** macos 10.15.7
  - **Language (Version):** Python (3.8.5)

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hello @neovasili ,

thanks for opening the issue. So, to sum up the problem:

1. Create a new `rds. DatabaseInstance` with `multiAz: false` and `availabilityZone` parameter set. Deploy it.
2. Change the `multiAz` parameter to `true`. This causes a replacement of the Database, because the `availabilityZone` property is then removed.

Instead, you would like to see an error raised if `multiAz` is `true`, but the `availabilityZone` property is set?

Thanks,
Adam

**Comment by neovasili** [comment]
Hello Adam,

Thanks for your response.

Yes, that was my suggestion. When a CloudFormation template including `availabilityZone` and `multiAz: true`, the error produced is like this one, due to that incompatibility of those parameters:

```
Requesting a specific availability zone is not valid for Multi-AZ instances. (Service: AmazonRDS; Status Code: 400; Error Code: InvalidParameterCombination; Request ID: xxxxxxxxxx; Proxy: null)
```

If CDK can raise an exception when this occur at synthesize time the developer could be aware of this incompatibility and will avoid undesired results regarding possible replacement of RDS instances.

Regards,

**Comment by skinny85** [comment]
That's fair @neovasili . Leaving it as a small bug then 🙂.

(BTW, if you'd like to submit us a PR fixing it, that would be great :). https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md)

**Comment by neovasili** [comment]
Hi Adam,

Thanks for your response. Now I have more free time for it, so even if Typescript is not my primary programming language, I will try it :D

**Comment by madeline-k** [comment]
Hello, @neovasili ! Are you still working on this issue?

**Comment by neovasili** [comment]
Hello Madeline,

Sorry for the late reply, I just opened a PR with the work a few seconds ago. I hope this can help :)

**Comment by Rian-II** [comment]
Hello @neovasili . I suspect the fix you applied may have caused the new issue described in my SO post [here](https://stackoverflow.com/questions/72286019/does-amazon-cloudformation-make-provision-for-deploying-rds-instances-to-differe). Can you please confirm and if that's the case, I'll gladly open a new issue. I'm not sure what the integration between the CDK and CloudFormation is (to me they should be separated), but this is the only reason I could find for the issue.
