### ISSUE TITLE
[batch] Pass AWS_REGION by default to containers

### ISSUE THREAD

**Issue by Dzhuneyt** [aws/aws-cdk#10952]
Containers started through AWS Batch can't do even the most basic communication with other AWS services due to missing meaningful defaults.

### Use Case

I've created an AWS Batch compute environment, queue and job definition. The job definition is very trivial - a NodeJS app that writes a row to DynamoDB. However, this trivial example fails with an error: `UnhandledPromiseRejectionWarning: ConfigError: Missing region in config`. That's because the AWS Batch container does not pass information about the current AWS region to the container, [the same way it would pass it to the Lambda runtime](https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html#configuration-envvars-runtime), so the NodeJS app and the aws-sdk inside it, fails to connect to the DynamoDB service.

### Proposed Solution

I usually solve this by passing the AWS_REGION as an environment variable to the container definition:
```typescript
 new JobDefinition(this, 'app1', {
            container: {
                image: ContainerImage.fromAsset('./../apps/app1'),
                environment: {
                    AWS_REGION: Stack.of(this).region,
                },
            },
        });
```

This seems like something that can be embedded inside the JobDefinition construct to make life easy for developers that use this construct.

* [X] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by iliapolo** [comment]
@Dzhuneyt cool suggestion. Definitely open to a contribution here.

**Comment by l0b0** [comment]
Ping.

**Comment by microbioticajon** [comment]
This would be very useful. Im currently using a framework that does not give me configurable access to the container definition. My golang sdks are not happy :-(
