### ISSUE TITLE
[api-gateway] RestApi construct does not automatically create new deployments after addGatewayResponse 

### ISSUE THREAD

**Issue by keabarnes** [aws/aws-cdk#10963]
When calling the `addGatewayResponse` method on a `RestApi`, any `GatewayResponse` added doesn't come into effect because it doesn't trigger a new deployment. Manually creating a new deployment through AWS UI fixes this.

Similar to https://github.com/aws/aws-cdk/issues/8024
Related: https://github.com/aws/aws-cdk/issues/5354#issuecomment-591824660

### Reproduction Steps

First deploy:
```typescript
    const restApi = new RestApi(this,"MyRestApi");

    const restNotes = restApi.root.addResource("notes");
    restNotes.addMethod(HttpMethod.GET, ...);
```

Subsequent deploy:
```typescript
    const restApi = new RestApi(this,"MyRestApi");

    restApi.addGatewayResponse("4xxGatewayResponse", {
      type: ResponseType.DEFAULT_4XX,
      responseHeaders: {
        "Access-Control-Allow-Origin": "'*'",
        "Access-Control-Allow-Headers": "'*'",
      },
    });

    const restNotes = restApi.root.addResource("notes");
    restNotes.addMethod(HttpMethod.GET, ...);
```

### What did you expect to happen?

A change in the `GatewayResponse` for an API should trigger a deployment, as that's what's required when using the UI.

### What actually happened?

No new deployment was created when the `GatewayResponse` resource was changed.

### Environment

  - **CLI Version      :1.51.0**
  - **Framework Version: 1.53.0**
  - **Node.js Version: 10.16.3** 
  - **OS               : MacOS**
  - **Language (Version): TypeScript (3.9.6)** 

--- 

This is :bug: Bug Report

**Comment by keabarnes** [comment]
I haven't had the time to create a minimal reproduction of the error and have only observed this issue through debugging of my current project.

**Comment by nija-at** [comment]
Thanks for reporting. The fix is posted here -  https://github.com/aws/aws-cdk/pull/11068
