### ISSUE TITLE
No documentation on building and publishing constructs

### ISSUE THREAD

**Issue by OperationalFallacy** [aws/aws-cdk#10966]
Hi,

I'm trying to set up a pipeline to publish cdk construct inside my org. And I found cdk has no information on how to build, package and publish cdk constructs.

There are comprehensive libraries with constructs, for example https://github.com/awslabs/aws-solutions-constructs but they are doing just bash kung-fu for ci/cd and probably running something proprietary behind the scene.

Am I missing something? Or there is not enough interest in developing and publishing constructs?

Thanks!

**Comment by NetaNir** [comment]
Check out this blog post:https://www.matthewbonig.com/2020/01/11/creating-constructs/. You should also check out [aws-delivlib](https://github.com/awslabs/aws-delivlib), which is the tool we use to release the AWS CDK. 
Other resources:

* [projen](https://github.com/eladb/projen) support for creating and managing jsii modules
* [jsii-release](https://github.com/aws/jsii-release) - a collection of utilities to release jsii modules.

**Comment by OperationalFallacy** [comment]
Hey @NetaNir, thanks for the links. I've read that blog post already, but everything jsii related is skipped...

And since projen is early alfa, so I'm hesitant to use it and in any case, I don't think it's a good idea to bring all this tooling and packages for simple npm package distribution.

What would you recommend? jsii utils, project, delivlib?

**Comment by NetaNir** [comment]
[aws-delivlib](https://github.com/awslabs/aws-delivlib) will be a good starting point, it has a very simple high level API and good docs. About jsii, I would suggest not skipping over it, it is fairly simple to use and provides a lot of value.
