### ISSUE TITLE
[Batch] Add "Secrets" properties in interface JobDefinitionContainer

### ISSUE THREAD

**Issue by Cloudrage** [aws/aws-cdk#10976]
### Use Case

Need to pass Secrets to a Batch Job with CDK Batch Construct.
Not available yet : 
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-batch.JobDefinitionContainer.html

### Proposed Solution

Like with CloudFormation, it'll be interesting to add "Secrets" propertie to the CDK Batch Construct : 
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-batch.CfnJobDefinition.ContainerPropertiesProperty.html#secrets

### Other

https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-batch.CfnJobDefinition.SecretProperty.html

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by iliapolo** [comment]
@Cloudrage Thanks for this. Added. 

Just making sure you are aware of [escape hatches](https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html) to unblock yourself in the meantime.

**Comment by Cloudrage** [comment]
Yep, it's what I'm doing when pasting links about that workaround previously; thanks !

Also, maybe think about an "addSecrets" Method for the Batch Job.

**Comment by daniel-j-h** [comment]
The workaround I came up with looks something like this

```typescript
// Secrets are not yet supported in the high-level JobDefinition
//  - https://github.com/aws/aws-cdk/issues/10976
//  - https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-batch.CfnJobDefinition.ContainerPropertiesProperty.html#secrets
const cfnJobDef = jobDef.node.defaultChild as CfnJobDefinition;
const cfnContainerProps = cfnJobDef.containerProperties as CfnJobDefinition.ContainerPropertiesProperty;

(cfnContainerProps as any).secrets = [  // cast to any needed because .secrets property is readonly
  { name: "MY_SECRET", valueFrom: mySecretArn },
];
```

in case folks are stumbling over this issue.

**Comment by hughack** [comment]
Is there an equivalent for Python? Currently i have:

```python
my_job_definition = batch_alpha.JobDefinition(...)

my_job_definition.node.default_child.container_properties.secrets = [
    batch.CfnJobDefinition.SecretProperty(
        name="...",
        value_from='...'
    )
]
```

But get an attribute error:
```
AttributeError: can't set attribute
```

**Comment by AndreyMarchuk** [comment]
`JobDefinitionContainer` would require defined `execution_role` when using Secrets Manager

Python

1. Create execution role
```python
batch_execution_role = iam.Role(self, "batchExecRole", 
                assumed_by=iam.ServicePrincipal('ecs-tasks.amazonaws.com'), 
                managed_policies=[iam.ManagedPolicy.from_aws_managed_policy_name('service-role/AmazonECSTaskExecutionRolePolicy')])
```

2. Set on `execution_role=batch_execution_role` on `JobDefinitionContainer` level

3. Grant secret read permissions
```python
my_secret.grant_read(batch_execution_role)
```
