### ISSUE TITLE
[ecs-patterns] Blue-green deployments with ApplicationLoadBalancedFargateService

### ISSUE THREAD

**Issue by ligaz** [aws/aws-cdk#10971]
In order to support blue-green deployments with `ApplicationLoadBalancedFargateService` I need to be able to change the deployment controller type of the provisioned Fargate service.

### Use Case

We have been doing blue-green deployments for the past couple of month using a modified version of `ApplicationLoadBalancedFargateService` construct. We have extended it to support changing of the deployment controller type to `CODE_DEPLOY` so we can support blue-green deployments. 

Our workflow is the following:
1. A PR is approved and merged to master.
1. Docker image is built, tagged and pushed to AWS ECR.
1. A blue-green deployment is triggered with `ecs deploy` using [this script](https://gist.github.com/ligaz/7ade15a84a4c66b90acf892a494bf7a4). The script reads its inputs from the outputs of the specified stack provisioned with AWS CDK.

In order to support this we need to be able to change the deployment controller of the Fargate service.

### Proposed Solution

Add option to change the deployment controller of ApplicationLoadBalancedFargateService. Implemented in #10452

**Comment by ligaz** [comment]
@MrArnoldPalmer Do you need anything else from my side in order to get #10452 merged?

**Comment by SoManyHs** [comment]
Related:
https://github.com/aws/aws-cdk/issues/1559
