### ISSUE TITLE
[aws-ecs] Retrieve secret from name fails

### ISSUE THREAD

**Issue by gandroz** [aws/aws-cdk#10989]
When I try to pass a secret to a task definition, it fails if I get the secret from its name but not from its arn. Here is a sample code

```
export class TestSecretStack extends cdk.Stack {
    constructor(scope: cdk.Construct, id: string) {
        super(scope, id);
  
        const taskDefinition = new ecs.Ec2TaskDefinition(this, 'TaskDef');
        
        const secret = secretsmanager.Secret.fromSecretName(this, "Secret", "MySecret")
        const secret2 = secretsmanager.Secret.fromSecretArn(this, "Secret2", "arn:aws:secretsmanager:ca-central-1:xxxxxxxxxx:secret:MySecret-ABCDEF")

        taskDefinition.addContainer('web', {
            image: ecs.ContainerImage.fromRegistry('amazon/amazon-ecs-sample'),
            memoryLimitMiB: 256,
            secrets: {
                // PASSWORD: ecs.Secret.fromSecretsManager(secret, 'password')  <==== fail
                PASSWORD: ecs.Secret.fromSecretsManager(secret2, 'password')
            },
        });
    }
  }
```

### Environment

  - **CDK Version: 1.66.0 (build 459488d)**
  - **Node.js Version: 12.19.0** 
  - **OS               : Ubuntu 18.04**
  - **Language (Version): TypeScript** 

--- 

This is :bug: Bug Report

**Comment by MrArnoldPalmer** [comment]
Looks like there are multiple issues with secret references in ECS. We may want to look at this more holistically just in case there is some fundamental logic issue here.

Related:
https://github.com/aws/aws-cdk/issues/9765
https://github.com/aws/aws-cdk/issues/8405

**Comment by tscully49** [comment]
Are there any thoughts on this issue or workarounds?
