### ISSUE TITLE
[ecs-patterns] Fix typo in example

### ISSUE THREAD

**Issue by christophgysin** [aws/aws-cdk#10986]
https://docs.aws.amazon.com/cdk/api/latest/docs/aws-ecs-patterns-readme.html

`aws-ecs-patterns` used to use the `Schedule` class from the `events` module. This has been changed to use the class from `applicationautoscaling` instead, but the example still references the `events` module.

---

This is a 📕 documentation issue

**Comment by SoManyHs** [comment]
@christophgysin Hi there, were you still planning on opening a PR for this? Thanks!

**Comment by christophgysin** [comment]
@SoManyHs There is already a PR #10987

**Comment by madeline-k** [comment]
This has been fixed. Thanks @kaizen3031593 😄
