### ISSUE TITLE
[apigatewayv2] http api - jwt authorizer

### ISSUE THREAD

**Issue by dave-graham** [aws/aws-cdk#10982]
Please can you add authentication to the higher level constructs in http apis. At the moment to add auth, you need to fall back to the cloud-formation constructs e.g. https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-apigatewayv2.CfnAuthorizer.html. It would be awesome to tie it all into one higher level construct, and have examples in the documentation to get a version with auth off the ground quickly.

### Use Case

To simplify creation and management of http apis with jwt based authentication

This is a :rocket: Feature Request

**Comment by iRoachie** [comment]
Hey @dave-graham I implemented this in #10972

**Comment by nija-at** [comment]
This is actually a duplicate of https://github.com/aws/aws-cdk/issues/10534
