### ISSUE TITLE
[iam] PolicyStatement.fromJson gets undesirably normalized

### ISSUE THREAD

**Issue by matt-slalom** [aws/aws-cdk#10994]
Using `Role.assumeRolePolicy.addStatements` to add a deny statement to the AssumeRolePolicyDocument section of the CFT results in a `"Principal": "*"` instead of the expected (and documented) `"Principal": {"AWS":"*"}`. This seems to be the cause of the error since the other statement in the AssumeRolePolicyDocument uses the latter syntax and produces no errors when cdk deploy runs (i.e. I comment out the `addStatements` section to produce the CFT). 

```
           {
              "Action": "sts:AssumeRole",
              "Condition": {
                "StringNotEquals": {
                  "aws:PrincipalOrgID": "omitted"
                }
              },
              "Effect": "Deny",
              "Principal": "*",
              "Sid": "DefaultDeny"
            }
```

### Reproduction Steps

```
const someVar=new Role(this, "CrossAccountInvokeLambda", {
                assumedBy: new PrincipalWithConditions(new AnyPrincipal(),
                    {
                        "StringEquals": {
                            "aws:PrincipalOrgID": this.orgId
                        }
                    }
                ),
                inlinePolicies: { omitted_for_brevity
            }
        );

someVar.assumeRolePolicy?.addStatements(
            PolicyStatement.fromJson({
                "Sid": "DefaultDeny",
                "Effect": "Deny",
                "Principal": {
                    "AWS": "*"
                },
                "Action": [
                    "sts:AssumeRole"
                ],
                "Condition": {
                    "StringNotEquals": {
                        "aws:PrincipalOrgID": this.orgId
                    }
                }
            })
        );
```

### What did you expect to happen?

I expected the resulting CFT to deploy without error. Based on the error, I'm expecting to see `"Principal": {"AWS":"*"}` instead of `"Principal": "*"`.

### What actually happened?

`AssumeRolepolicy contained an invalid principal: "STAR":"*". (Service: AmazonIdentityManagement; Status Code: 400; Error Code: MalformedPolicyDocument; Request ID: ac783eaf-6fa4-4068-b2c9-402941cb0c7b; Proxy: null)`

```
"Type": "AWS::IAM::Role",
      "Properties": {
        "AssumeRolePolicyDocument": {
          "Statement": [
            {
              "Action": "sts:AssumeRole",
              "Condition": {
                "StringEquals": {
                  "aws:PrincipalOrgID": "omitted"
                }
              },
              "Effect": "Allow",
              "Principal": {
                "AWS": "*"
              }
            },
            {
              "Action": "sts:AssumeRole",
              "Condition": {
                "StringNotEquals": {
                  "aws:PrincipalOrgID": "omitted"
                }
              },
              "Effect": "Deny",
              "Principal": "*",
              "Sid": "DefaultDeny"
            }
          ],
          "Version": "2012-10-17"
        }
```

### Environment

  - **CLI Version      :** aws-cli/2.0.14 Python/3.7.4 Darwin/18.7.0 botocore/2.0.0dev18
  - **Framework Version:** CDK version 1.67.0 (build 2b4dd71)
  - **Node.js Version:** v12.14.1
  - **OS               :** Mac OS X 10.14.6
  - **Language (Version):** TypeScript 3.9.7

### Other

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
AssumeRolePolicies don't respect the equivalence of `Principal:*` and `Principal: { AWS: * }`.

We have code to handle this for automatically created statements, but not for statements added later. We should probably be solving this a different way.
