### ISSUE TITLE
[pipelines] Provide access to secrets inside Docker builds

### ISSUE THREAD

**Issue by enricopesce** [aws/aws-cdk#10990]
## :question: Customize the docker build phase 

![image](https://user-images.githubusercontent.com/2789957/96604940-f1537c80-12f5-11eb-992f-f54bef56081d.png)

I need to implement some environment variables on the DockerAsset stages but these are automatically created by pipelines.

How can I customize these?

Thank you!!

**Comment by hoegertn** [comment]
Can you elaborate on your use case? What env variables do you need to set?

**Comment by enricopesce** [comment]
In the Docker build phase I need to pass credentials to a PHP composer tools for downloading private dependencies.

**Comment by hoegertn** [comment]
Ok I understand, but building assets and so images should happen in the synth phase, shouldn't it?

**Comment by enricopesce** [comment]
yes! another problem is the impossibility to retrieve secrets value in the assets build phase

Thank you

**Comment by rix0rrr** [comment]
There is currently no way to do that, sorry.

**Comment by ulyr** [comment]
If you need to do this there's a way
you can pass an environment variable to the build stage in the pipeline definition and then pass that environment variable onto the actual docker build that's going to build your containers as docker build secrets that take their values from the environment.
kind of a hacky, no so straight forward solution but it works.
