### ISSUE TITLE
Enhancement request : Deploy cdk stack parallely 

### ISSUE THREAD

**Issue by Black742** [aws/aws-cdk#1099]
This is enhancement request to deploy the stacks parallely while run the cdk deploy cli command. This is will reduce the runtime for the developers while deploying multiple stacks into the environment.

**Comment by shivlaks** [comment]
duplicated by #1973

**Comment by pgollucci** [comment]
why were both this and the other one closed?

**Comment by shivlaks** [comment]
@pgollucci this one is closed, and the other one is still open.
am I missing something here?

**Comment by pgollucci** [comment]
No, I'm insane.  Its open.
