### ISSUE TITLE
[aws-stepfunctions-tasks] Allow SQS messageGroupId to be dynamic from input data

### ISSUE THREAD

**Issue by ayenter** [aws/aws-cdk#11001]
For SQS `sendMessage` in stepfunctions, `messageGroupId` can be taken from input data. This is not reflected in the [cdk](https://github.com/aws/aws-cdk/blob/b8490f25a8eb6104163cf03c4e4ea9a61163877d/packages/%40aws-cdk/aws-stepfunctions-tasks/lib/sqs/send-message.ts#L49).

### Use Case
Ability to set `messageGroupId` based on the incoming data.
Also, as noted [here](): "the producer should generate a unique message group ID for each message". This is impossible if messageGroupId is limited to a constant string.

### Proposed Solution
To support this functionality, [`messageGroupId`](https://github.com/aws/aws-cdk/blob/b8490f25a8eb6104163cf03c4e4ea9a61163877d/packages/%40aws-cdk/aws-stepfunctions-tasks/lib/sqs/send-message.ts#L49) should be of type `sfn.TaskInput`.

This is a :rocket: Feature Request

**Comment by shivlaks** [comment]
@ayenter - can you share how you're attempting to use state input data? in place of the string you should simply be able to reference state input through the `JsonPath` convenience class. An example:

```ts
const sendMessageTask = new SqsSendMessage(stack, 'send message to sqs', {
  queue: new sqs.Queue(stack, 'show-me-the-messages'),
  messageBody: sfn.TaskInput.fromText('sending message over'),
  messageGroupId: sfn.JsonPath.stringAt('$.stateInputField'),
});
```

**Comment by shivlaks** [comment]
marking this issue as `guidance` for now as I believe this capability is supported

**Comment by ayenter** [comment]
@shivlaks Thank you! This answers my issue!
