### ISSUE TITLE
[ecs] Circular dependency between EcsDeployAction and Fargate cluster

### ISSUE THREAD

**Issue by flashflexpro** [aws/aws-cdk#11002]
When trying to create ECS cluster with image pipeline together, it can form an annoying dependency:

ECS initialization require the image, the image is not there until the pipeline is created and run for once, the pipeline has a EcsDeployAction depending on ECS as deployment target, eventually ECS will wait for the image until timeout:

```ts
        this.alBFargate = new ecs_patterns.ApplicationLoadBalancedFargateService(this, props.appName, {
            cluster: ecsCluster,
            taskImageOptions: {
                image: ecs.ContainerImage.fromEcrRepository(ecrRepo)
            }
        })

 // . . .

        const imgBuildPipeline = new pipeline.Pipeline(this, 'broadworks-auth-pipeline', {
            pipelineName: id + '-build-deploy-IMG',
            stages: [
                {
                    stageName: 'Build',
                    actions: [
                        new pipelineActions.CodeBuildAction({
                            actionName: 'Img_Build',
                            project: broadworksAuthBuild,// deploy to ecrRepo
                            input: sourceOutput,
                            outputs: [cdkBuildOutput],
                        }),
                    ],
                },
                {
                    stageName: 'Deploy',
                    actions: [
                        new pipelineActions.EcsDeployAction({
                            actionName: 'deployToECS',
                            service: this.alBFargate.service,
                            input: cdkBuildOutput
                        }),
                    ],
                }
            ],
        });
```

I would expect that the ECS cluster can finish initialization without any image.

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hey @flashflexpro ,

I would suggest taking a different approach. Pass the `ApplicationLoadBalancedFargateService` an image from an [Asset](https://docs.aws.amazon.com/cdk/latest/guide/assets.html), and then use [CDK Pipelines](https://docs.aws.amazon.com/cdk/api/latest/docs/pipelines-readme.html) to create your CodePipeline. Your image will be automatically pushed when the assets are published in the pipeline, and you don't have to manage an ECR repository explicitly.

Thanks,
Adam

**Comment by flashflexpro** [comment]
thanks for the tip, this approach will work, but will also need docker
build project coupled with cdk project, any idea how to decouple them?

**Comment by skinny85** [comment]
@flashflexpro Why do you need to decouple them?

**Comment by flashflexpro** [comment]
I have one cdk project with multiple ECS clusters, each cluster can use
multi containers, some containers are heavy and in different git repos, I
do not want to add cdk code to their repos.

**Comment by skinny85** [comment]
Out of curiosity, for those containers in separate Git repositories - how do you reference them in your CDK code?

**Comment by flashflexpro** [comment]
yeah, containers are in separate repos, CDK PipelineProject checkout with
GitHubSourceAction,  build docker image into ECR with PipelineProject, and
deploy with EcsDeployAction, everything is straightforward and clean,
except the dead cirle.

**Comment by flashflexpro** [comment]
This is all about how to draw the boundary between infrastructure and
application:
1) Building application docker image and publishing into ECS is part of CDK
Infra, then CDK defines the image build pipeline, ECR and deployment, the
interface is a repo url and Dockerfile path.
2)  Building application docker image and publishing into ECS is part of
application, then CDK imports image from container image repo, the
interface is a repo url.

I would prefer 1), because it lets application repo focus on app
development.

**Comment by skinny85** [comment]
@flashflexpro if CDK Pipelines doesn't fir your needs, I think what you want is this example: https://github.com/rix0rrr/cdk-ecs-demo

It's for an older version of the CDK, but the general idea is the same.

The crucial class there is [`PipelineContainerImage`](https://github.com/rix0rrr/cdk-ecs-demo/blob/master/lib/pipeline-container-image.ts). It allows you to create an image that is "late bound", that is, will only be created when the pipeline executes.

While we currently don't have `PipelineContainerImage` in the main CDK repo, you can always copy&paste the class into your code, and we could also add it to the CDK if you think that it would be useful.

Let me know if this solves your problem!

Thanks,
Adam

**Comment by flashflexpro** [comment]
Adam,  thanks for sharing the code, I am not sure how to use it, could you
be more specific please?

**Comment by flashflexpro** [comment]
My workaround is to split the pipeline into two, the 1st build and push the
image into ECR, the 2nd use triggered by the ECR with EcrSourceAction and
deploy to ECS.

**Comment by skinny85** [comment]
This is the code for the Pipeline from that repository: https://github.com/rix0rrr/cdk-ecs-demo/blob/90e1a5a712a99db9422550c1d639d4c5282ecbe5/lib/code-pipeline-stack.ts#L9

Does this help @flashflexpro ?

**Comment by flashflexpro** [comment]
Adam, that is helpful, thank you.

**Comment by SomayaB** [comment]
Closing this issue since it seems to have been resolved. Feel free to reopen.
