### ISSUE TITLE
Hardcoding AWS Hosted Zone IDs

### ISSUE THREAD

**Issue by kay-is** [aws/aws-cdk#11009]
It would be nice if I could just pull a hosted zone ID from a construct library.

### Use Case

When I want to create Records for Route53, I usually need hosted zone IDs.

When I want to do this for AWS generated domains (CloudFront, API-Gateway, etc.) I need the AWS owned zone IDs, which seem to be static and can be found somewhere on AWS docs pages.

### Proposed Solution

Adding the hosted zones as a list, so they can simply be referenced by their region, if there is only one hosted zone, reference it directly.

    hostedZoneId = apigatewayv2.hostedZoneIds["eu-west-1"];
    hostedZoneId = cloudfront.hostedZoneId;

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by shivlaks** [comment]
@kay-is - have you see the [`region-info`](https://docs.aws.amazon.com/cdk/api/latest/docs/region-info-readme.html) module?

An example for S3 static website hosted zone id's is [here](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/region-info/build-tools/fact-tables.ts#L42-L71). I think this would be the preferred mechanism to extend if there's missing information.
