### ISSUE TITLE
CDK WorkShop Issue with cdk bootstrap command on Windows 7 Professional 

### ISSUE THREAD

**Issue by Blyseur** [aws/aws-cdk#11010]
In the CDK WorkShop, when we add our first lambda function, we have to import @aws-cdk/aws-lambda. Once, we write the code and we want to deploy, we have an error occured because of the bootstrapping

### Reproduction Steps
On Windows, init a cdk project, follow the steps until arrived to the lambda function step. 
https://cdkworkshop.com/20-typescript/30-hello-cdk/200-lambda.html

### What did you expect to happen?

Deploy correctly CdkWorkshopStack

### What actually happened?

 We obtain an error, where it is sayed we must deployed the toolkit stack.

IAM Statement Changes
┌───┬─────────────────────────────────┬────────┬────────────────┬──────────────────────────────┬───────────┐
│   │ Resource                        │ Effect │ Action         │ Principal                    │ Condition │
├───┼─────────────────────────────────┼────────┼────────────────┼──────────────────────────────┼───────────┤
│ + │ ${HelloHandler/ServiceRole.Arn} │ Allow  │ sts:AssumeRole │ Service:lambda.amazonaws.com │           │
└───┴─────────────────────────────────┴────────┴────────────────┴──────────────────────────────┴───────────┘
IAM Policy Changes
┌───┬─────────────────────────────┬────────────────────────────────────────────────────────────────────────────────┐
│   │ Resource                    │ Managed Policy ARN                                                             │
├───┼─────────────────────────────┼────────────────────────────────────────────────────────────────────────────────┤
│ + │ ${HelloHandler/ServiceRole} │ arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole │
└───┴─────────────────────────────┴────────────────────────────────────────────────────────────────────────────────┘
(NOTE: There may be security-related changes not in this list. See https://github.com/aws/aws-cdk/issues/1299)
```console
Do you wish to deploy these changes (y/n)? y
CdkWorkshopStack: deploying...

 CdkWorkshopStack failed: Error: This stack uses assets, so the toolkit stack must be deployed to the environment (Run "cdk bootstrap aws://unknown-account/unknown-region")
    at Object.addMetadataAssetsToManifest (C:\Users\Toto\AppData\Roaming\npm\node_modules\aws-cdk\lib\assets.ts:27:11)
    at Object.deployStack (C:\Users\Toto\AppData\Roaming\npm\node_modules\aws-cdk\lib\api\deploy-stack.ts:207:29)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at CdkToolkit.deploy (C:\Users\Toto\AppData\Roaming\npm\node_modules\aws-cdk\lib\cdk-toolkit.ts:180:24)
    at initCommandLine (C:\Users\Toto\AppData\Roaming\npm\node_modules\aws-cdk\bin\cdk.ts:197:9)
This stack uses assets, so the toolkit stack must be deployed to the environment (Run "cdk bootstrap aws://unknown-account/unknown-region")
```

So, at this moment, we run cdk bootstrap and an other error occured : 
```console
 ⏳  Bootstrapping environment aws://unknown-account/unknown-region...
 ❌  Environment aws://unknown-account/unknown-region failed bootstrapping: [Error: ENOENT: no such file or directory, mkdtemp 'C:\Users\Toto\Documents\cdk-workshop\ASIA......\........\......\......\......\......\......\......\......\......\......\cdk-bootstrapXXXXXX'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'mkdtemp',
  path: 'C:\\Users\\Toto\\Documents\\cdk-workshop\\ASIA......\......\\......\\......\......\\......\\......\\......\\......\\......\\......\\......\\......\\......\\......\\cdk-bootstrapXXXXXX'
}
ENOENT: no such file or directory, mkdtemp 'C:\\Users\\Toto\\Documents\\cdk-workshop\\ASIA......\......\\......\\......\......\\......\\......\\......\\......\\......\\......\\......\\......\\......\\......\\cdk-bootstrapXXXXXX'
```
### Environment

  - **CLI Version      :** aws-cli/1.18.160
  - **Framework Version:**
  - **Node.js Version:** v12.14.0
  - **OS               :** Windows 7 Professional
  - **Language (Version):** 

This is :bug: Bug Report

**Comment by SomayaB** [comment]
I opened a new issue to redirect this discussion to the workshop repo. https://github.com/aws-samples/aws-cdk-intro-workshop/issues/173
