### ISSUE TITLE
[aws-rds] type for input parameter for rds.Credentials.fromSecret should be ISecret

### ISSUE THREAD

**Issue by dennisseidel** [aws/aws-cdk#11015]
As I understood here rds.Credentials.fromSecret(secret: secretsmanager.Secret) ([link](https://github.com/aws/aws-cdk/blob/a6a3f46e90671ae04986853cf273cd737e813910/packages/%40aws-cdk/aws-rds/lib/props.ts#L175)) expects a object with all the attributes of secretsmanager.Secret ([link](https://github.com/aws/aws-cdk/blob/36fea2824787f47692e78fb5de063f89f5c7da5d/packages/%40aws-cdk/aws-secretsmanager/lib/secret.ts#L243)). Secret extends SecretBase . SecretBase extends Resource and implements ISecret ([link](https://github.com/aws/aws-cdk/blob/36fea2824787f47692e78fb5de063f89f5c7da5d/packages/%40aws-cdk/aws-secretsmanager/lib/secret.ts#L138)). Therefore Secret has more mandatory attributes than ISecret.
The function to create the Secret secretmanager.Secret.fromSecretName(scope: Construct, id: string, secretName: string): ISecret ([link](https://github.com/aws/aws-cdk/blob/a6a3f46e90671ae04986853cf273cd737e813910/packages/%40aws-cdk/aws-secretsmanager/lib/secret.ts#L253)) return only an ISecret.
When I now call the rds.Credentials.fromSecret(iSecretObject) this will never match as ISecret will always miss some attributes.
So from my perspective if secretmanager.Secret.fromSecretName ([link](https://github.com/aws/aws-cdk/blob/a6a3f46e90671ae04986853cf273cd737e813910/packages/%40aws-cdk/aws-secretsmanager/lib/secret.ts#L253)) can only return a secretsmanager.Secret then the return type should be Secret. Or if secretmanager.Secret.fromSecretName can return multiple "secret" types and all of those can be used for rds.Credentials.fromSecret(secret) then this should only expect a secret object of type ISecret.

### Reproduction Steps

```

import * as cdk from '@aws-cdk/core';
import * as rds from '@aws-cdk/aws-rds';
import * as ec2 from '@aws-cdk/aws-ec2';
import * as secretsmanager from '@aws-cdk/aws-secretsmanager';
export class InfrastructureStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);
    const vpc = ec2.Vpc.fromLookup(this, "VPC", {
      isDefault: true
    })
    const engine = rds.DatabaseInstanceEngine.postgres({ version: rds.PostgresEngineVersion.VER_12_3 });
    const mySecret = secretsmanager.Secret.fromSecretName(this, 'DBSecret', 'myDBLoginInfo');
    new rds.DatabaseInstance(this, 'InstanceWithSecretLogin', {
      engine,
      vpc,
      credentials: rds.Credentials.fromSecret(mySecret), // Get both username and password from existing secret
    });
  }
}
```

### What did you expect to happen?

rds.Credentials.fromSecret should have accepted mySecret of type ISecret. 

### What actually happened?

```
TS2345: Argument of type 'ISecret' is not assignable to parameter of type 'Secret'.
  Type 'ISecret' is missing the following properties from type 'Secret': autoCreatePolicy, addTargetAttachment, attach, validate, and 12 more.
48       credentials: rds.Credentials.fromSecret(dbSecret),TS2345: Argument of type 'ISecret' is not assignable to parameter of type 'Secret'.
  Type 'ISecret' is missing the following properties from type 'Secret': autoCreatePolicy, addTargetAttachment, attach, validate, and 12 more.
48       credentials: rds.Credentials.fromSecret(dbSecret),
```

### Environment

  - **CLI Version      :** 1.68
  - **Framework Version:** 1.68
  - **Node.js Version:** v12.19.0
  - **OS               :** OSX 10.15.6
  - **Language (Version):** TypeScript (3.8.3)

### Other

--- 

This is :bug: Bug Report

**Comment by dennisseidel** [comment]
Will add a PR as discussed here: https://app.slack.com/client/T017JQ2SWES/threads/thread/C018XT6REKT-1602879565.264300

**Comment by dennisseidel** [comment]
Changing the type of the input attribute [secret](https://github.com/aws/aws-cdk/blob/a6a3f46e90671ae04986853cf273cd737e813910/packages/%40aws-cdk/aws-rds/lib/props.ts#L175) to `ISecret` is not enough as this is [return](https://github.com/aws/aws-cdk/blob/a6a3f46e90671ae04986853cf273cd737e813910/packages/%40aws-cdk/aws-rds/lib/props.ts#L180) and needs to conform to the Credentials type where it again [expects](https://github.com/aws/aws-cdk/blob/a6a3f46e90671ae04986853cf273cd737e813910/packages/%40aws-cdk/aws-rds/lib/props.ts#L210) this to be an secretmanager.Secret.
And this credentials object is used in rds [cluster.ts](https://github.com/aws/aws-cdk/blob/36fea2824787f47692e78fb5de063f89f5c7da5d/packages/%40aws-cdk/aws-rds/lib/cluster.ts#L494) and expect/uses an [attach](https://github.com/aws/aws-cdk/blob/36fea2824787f47692e78fb5de063f89f5c7da5d/packages/%40aws-cdk/aws-rds/lib/cluster.ts#L526) method that is not available on [ISecret](https://github.com/aws/aws-cdk/blob/36fea2824787f47692e78fb5de063f89f5c7da5d/packages/%40aws-cdk/aws-secretsmanager/lib/secret.ts#L12) but is only implemented on [Secret](https://github.com/aws/aws-cdk/blob/36fea2824787f47692e78fb5de063f89f5c7da5d/packages/%40aws-cdk/aws-secretsmanager/lib/secret.ts#L355).

I see two ways forward

1. We assume that every Secret has an attach method and add this to [ISecret](https://github.com/aws/aws-cdk/blob/36fea2824787f47692e78fb5de063f89f5c7da5d/packages/%40aws-cdk/aws-secretsmanager/lib/secret.ts#L12) but as [BaseSecret](https://github.com/aws/aws-cdk/blob/a6a3f46e90671ae04986853cf273cd737e813910/packages/%40aws-cdk/aws-secretsmanager/lib/secret.ts#L138) imlements ISecret we would need to implement attach then on BaseSecret. 
2. We assume that not every Secret has an attach method, but as [Credentials.fromSecret()](https://github.com/aws/aws-cdk/blob/36fea2824787f47692e78fb5de063f89f5c7da5d/packages/%40aws-cdk/aws-rds/lib/cluster.ts#L526) expects a Secret with an attach method we need to change the type of the input `secret` to the specific secretmanager.Secret that has the attach method. 

Can you provide some guidance on what makes sense in the code based? Thank you :)

**Comment by skinny85** [comment]
@dennisseidel your solution is top-notch, and is what I would have done in that scenario 🙂 I already approved it, I'm just now waiting for a teammate of mine to also take a quick look.

Thanks for the contribution!

**Comment by contrapunctus-xv** [comment]
@skinny85 what's the release cadence for this project? Would love to have this fix in soon. Thank you and @dennisseidel

**Comment by skinny85** [comment]
@contrapunctus-xv we should have a release this week (before October 30).
