### ISSUE TITLE
RDS Oracle Version

### ISSUE THREAD

**Issue by msaltz96** [aws/aws-cdk#11012]
### The Question

When using Oracle RDS Version : rds.OracleEngineVersion.VER_19_0_0_0_2020_04_R1 
CDK works fine.

But, when using newest engine version:
rds.OracleEngineVersion.VER_19_0_0_0_2020_07_R1 
I get error: ("Failed to parse database engine and/or version.")

### Environment

  - **CDK CLI Version:** 1.69.0
  - **Node.js Version:** v12.18.3
  - **OS:** Windows 10
  - **Language:** Python

### Other information
("Failed to parse database engine and/or version.")

**Comment by skinny85** [comment]
Hey @msaltz96 ,

do you get that error during `cdk synth` time, or actually when deploying?

Thanks,
Adam

**Comment by msaltz96** [comment]
@skinny85 During Synth

**Comment by skinny85** [comment]
Can you show the code that's causing the problem?
