### ISSUE TITLE
[@aws-cdk/aws-codepipeline-actions] use a custom build action in CDK project

### ISSUE THREAD

**Issue by phillipCouto** [aws/aws-cdk#11029]
https://docs.aws.amazon.com/cdk/api/latest/docs/aws-codepipeline-actions-readme.html

I am trying to figure out how to reference a custom action for a build stage within my CDK template. I have spent a few hours reading the documentation and source code and I can't see a way to use a custom build action in my pipeline. I have created the pipeline via the console and I am able to use the custom action without any issues.

The custom action I am trying to utilize was actually created from the cloudformation template in this project https://github.com/aws-samples/aws-codepipeline-custom-action

Hope I am just missing something and there is a way with the latest version of the CDK to utilize the action.

---

This is a 📕 documentation issue

**Comment by skinny85** [comment]
Hey @phillipCouto ,

the way you use custom actions in CodePipeline is by creating your own class that implements the `IAction` interface, and fills the appropriate properties like `category`, `provider`, `version`, `owner` (must be `'Custom'` for custom actions), and your custom properties. Then you instantiate that class, and add it to the Pipeline like any other action.

If you want a specific example, take a look at the [`JenkinsAction` class](https://github.com/aws/aws-cdk/blob/585920e69e981187eed036659f6fe3f4bd4096d1/packages/%40aws-cdk/aws-codepipeline-actions/lib/jenkins/jenkins-action.ts#L62-L94).

Thanks,
Adam

**Comment by phillipCouto** [comment]
Thank you @skinny85 I was able to create my class to represent my custom build action. Not sure if it would be valuable to expand the documentation with an example so that people don't have to dig through the source code. The issue with the source code route is the actions in `aws-codepipeline-actions` package use the `Actions` abstract class so I had to keep bouncing around the Jenkins action files as well as the action.ts file at the root to really understand how to implement the `IAction` interface.

**Comment by skinny85** [comment]
Fair enough. Let's keep this issue open to track that work.

(If you'd like to open us a PR adding those docs, that would be awesome too - here's our [Contributing documentation](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md))

**Comment by HarshRohila** [comment]
`JenkinsAction` is extending `Action`
But according to documentation https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-codepipeline-actions.Action.html
`Action` is going to disappear
How to create custom actions now?

**Comment by phillipCouto** [comment]
> `JenkinsAction` is extending `Action`
> But according to documentation https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-codepipeline-actions.Action.html
> `Action` is going to disappear
> How to create custom actions now?

I was able to achieve this by creating a class that implements `@aws-cdk/aws-codepipeline.IAction`. 

Here is the class I created that works with custom action I got from https://github.com/aws-samples/aws-codepipeline-custom-action:

```typescript
import * as cdk from '@aws-cdk/core';
import * as cpl from '@aws-cdk/aws-codepipeline';
import * as events from '@aws-cdk/aws-events';
import * as ec2 from '@aws-cdk/aws-ec2';


export interface CustomBuildImageActionProps extends cpl.CommonActionProps {
    /**
     * This is the provider name given to the action when created with the template in
     * https://github.com/aws-samples/aws-codepipeline-custom-action
     */
    readonly providerName: string;
    readonly providerVersion: string;
    readonly imageId: ec2.IMachineImage;
    readonly instanceType: ec2.InstanceType;
    readonly command: string;
    readonly inputs?: cpl.Artifact[];
    readonly outputs?: cpl.Artifact[];
    readonly outputArtifactPath?: string;
}

export class CustomBuildImageAction implements cpl.IAction {
    private readonly _props: CustomBuildImageActionProps;
    readonly actionProperties: cpl.ActionProperties;
    private _pipeline: cpl.IPipeline;
    private _stage: cpl.IStage;
    private _scope: cdk.Construct;

    constructor(props: CustomBuildImageActionProps) {
        this.actionProperties = {
            artifactBounds: { minInputs: 0, maxInputs: 1, minOutputs: 0, maxOutputs: 1 },
            actionName: props.actionName,
            category: cpl.ActionCategory.BUILD,
            inputs: props.inputs,
            outputs: props.outputs,
            owner: 'Custom',
            provider: props.providerName,
            version: props.providerVersion,
        }
        this._props = props;
    }

    bind(scope: cdk.Construct, stage: cpl.IStage, options: cpl.ActionBindOptions): cpl.ActionConfig {
        this._pipeline = stage.pipeline;
        this._stage = stage;
        this._scope = scope;
        return {
            configuration: {
                ImageId: this._props.imageId.getImage(scope).imageId,
                InstanceType: this._props.instanceType.toString(),
                Command: this._props.command,
                OutputArtifactPath: this._props.outputArtifactPath,
            }
        };
    }

    onStateChange(name: string, target?: events.IRuleTarget, options?: events.RuleProps): events.Rule {
        const rule = new events.Rule(this.scope, name, options);
        rule.addTarget(target);
        rule.addEventPattern({
            detailType: ['CodePipeline Action Execution State Change'],
            source: ['aws.codepipeline'],
            resources: [this.pipeline.pipelineArn],
            detail: {
                stage: [this.stage.stageName],
                action: [this.actionProperties.actionName],
            },
        });
        return rule;
    }

    get pipeline() {
        if (this._pipeline) {
            return this._pipeline;
        }
        else {
            throw new Error('Action must be added to a stage that is part of a pipeline before using onStateChange');
        }
    }
    get stage() {
        if (this._stage) {
            return this._stage;
        }
        else {
            throw new Error('Action must be added to a stage that is part of a pipeline before using onStateChange');
        }
    }
    /**
     * Retrieves the Construct scope of this Action.
     * Only available after the Action has been added to a Stage,
     * and that Stage to a Pipeline.
     */
    get scope() {
        if (this._scope) {
            return this._scope;
        }
        else {
            throw new Error('Action must be added to a stage that is part of a pipeline first');
        }
    }
}
```

This is what the package stage looks like that is using the code above to trigger the custom action:

```typescript
                {
                    stageName: 'Package',
                    actions: [
                        new CustomBuildImageAction({
                            actionName: 'Package',
                            inputs: [sourceArtifact],
                            outputs: [packageArtifact],
                            providerName: 'EC2-CodePipeline-Builder',
                            providerVersion: '1',
                            // Windows Server 2019 image with container support and docker preinstalled provided by amazon
                            imageId: new ec2.GenericWindowsImage({ 'ca-central-1': 'ami-0b403291e00b91c95' }),
                            instanceType: ec2.InstanceType.of(ec2.InstanceClass.C5A, ec2.InstanceSize.LARGE),
                            command: `package.ps1 -accountId ${cdk.Aws.ACCOUNT_ID} -region ${cdk.Aws.REGION} -repositoryName ${props.repo.repositoryUri}`,
                            outputArtifactPath: 'imagedefinitions.json'
                        })
                    ]
                }
```

The custom action in question is used to build a windows container image by using a single use EC2 instance with docker installed.

I will try to make a contribution to the CDK with documentation this weekend but hopefully these code snippets help.
