### ISSUE TITLE
[codepipeline]  CDK Deploy-Step Fails - Lambda Assets not uploaded to S3 after build -- "Error occurred while GetObject. S3 Error Code: NoSuchKey"

### ISSUE THREAD

**Issue by AndyEfaa** [aws/aws-cdk#11025]
## :question: General Issue

I did build a CDK application (let's call it app "A") including multiple lambda functions (all single file python code - no dependencies).
This  CDK application works great and deploys just fine from my local CLI.

Now, I want to deploy app "A" using a CICD Pipeline via a 2nd separate CDK application. 
- I pull the source from a source commit repo - works fine.
- I build app "A" using a codeBuild job with a custom buildspec.yml (including the `cdk synth` call). This works fine. The output artifact contains the expected `cdk.out` including the usual content.
- Now i want to deploy my application. I pass the output artifact from the build step into a CloudFormationCreateUpdateStackAction() (see code below). 

PROBLEM: 
The CloudFormation deploy step fails. 
The CloudFormation deploy fails with the error `Error occurred while GetObject. S3 Error Code: NoSuchKey. S3 Error Message: The specified key does not exist. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 7dbfdd63-58cb-4e58-b005-0a464d1b1055; Proxy: null)`
After closer inspection of the generated CFN template, I notice that the Lambda functions code property references the cdk S3 Bucket and Key (see below). The problem is that the S3 Bucket is empty. It doesn't contain the Key!

### The Question

How do I get the lambda assets from the build step uploaded to the S3 bucket so that CloudFormationCreateUpdateStackAction() can deploy the stack?

What am I missing here? 
Or should I deploy my cloudformation using another codebuilld action with a `cdk deploy` inside?

### Environment

  - **CDK CLI Version:** 1.69.0 (build 2b474b9)
  - **Module Version:** 1.69.0 
  - **Node.js Version:** v10.15.0
  - **OS:** OSX Catalina
  - **Language (Version):** Python (3.7)

### Other information

Action used to deploy the CloudFormation:
The cdk.out content is passed via the artifact source_output_build.
```
        action = codepipeline_actions.CloudFormationCreateUpdateStackAction(
            action_name=action_name,
            admin_permissions=True,
            stack_name=stack_name,
            replace_on_failure=True,
            template_path= source_output_build.at_path(template_path),
            capabilities=[
                cloudformation.CloudFormationCapabilities.NAMED_IAM,
                cloudformation.CloudFormationCapabilities.ANONYMOUS_IAM,
                cloudformation.CloudFormationCapabilities.AUTO_EXPAND
            ],
            run_order=1,
            region=region,
            extra_inputs=[source_output_build]
     )
```

Output of template.json with S3Bucket referncnce (the key doesn't exist - bucket is empty)
```
"IntegrationTestTriggerXXXX": {
      "Type": "AWS::Lambda::Function",
      "Properties": {
        "Code": {
          "S3Bucket": "cdk-hnb6XXXXXX26-eu-west-1",
          "S3Key": "da663XXXXXXXXbc09fa27e9.zip"
        },
```

**Comment by seanWLawrence** [comment]
I just ran into this too. Found this, which I'll try: https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-codepipeline-actions/test/integ.lambda-deployed-through-codepipeline.lit.ts

I'm assuming the lambda is trying to create itself from the code in the s3 bucket before it's there yet. Doing it this way with CloudFormation overrides and a separate cdk deployment probably gets around that

**Comment by ijemmy** [comment]
This happened to me when I forgot to update pipeline (didn't enable selfMutation). Updating pipeline fixed the issue.

It turns out that some assets building action (in `Assets` stage) were missing. Redeploying creates those missing actions.

**Comment by peterwoodworth** [comment]
Did the responses provide a solution to your issue @AndyEfaa?

Can anyone confirm if the responses given were helpful?

**Comment by peterwoodworth** [comment]
I'll be closing this issue due to staleness, ping me if there are additional concerns with this issue and I can reopen it.

**Comment by JeredLittle1** [comment]
To expand upon @ijemmy 's comments:

1. If you are using `.from_asset()` in your Lambda function stack, your CodePipeline will create an extra step `Assets`.
2. This is used to upload your asset files from the `CDKSynth` step to S3. 
3. Looking into the `buildspec.yml` for that step, you will see something like:

```
      "commands": [
        "cdk-assets --path \"assembly-STACK/STACK.assets.json\" --verbose publish \"11eecb7b5ccdb7c71db90f9c453ad052b6cdf36b45f7dcfb207bf60e607508c8:ACCOUNT-NUMBER-REGION\""
      ]
```

4. With this command, it looks to publish resource `11eecb7b5ccdb7c71db90f9c453ad052b6cdf36b45f7dcfb207bf60e607508c8` in the `assembly-STACK/STACK.assets.json` file to S3.

5. On every deployment, that hash value inside the `assembly-STACK/STACK.assets.json` file (from your Synth step) **will change**.
6.  _HOWEVER_, the `Assets` step's `buildspec.yml` file **will still reference the old hash value**. 
7. This means your local assets will never upload to S3. The step still will succeed with message:

```
1 assets found
--
Applied selection: 0 assets selected.
```

Because of this, you **must** enable SelfMutate in your CodePipeline, in order for the `buildspec.yml` in your `Assets` step to update.

Once doing this, you will see the following in your Assets step:

```

verbose: Applied selection: 1 assets selected.
--
33 | info   : [0%] start: Publishing 95c924c84f5d023be4edee540cb2cb401a49f115d01ed403b288f6cb412771df:ACCOUNT-NUMBER-REGION
34 | verbose: [0%] check: Check s3://cdk-hnb659fds-assets-ACCOUNT-NUMBER-REGION/95c924c84f5d023be4edee540cb2cb401a49f115d01ed403b288f6cb412771df.zip
35 | verbose: [0%] upload: Upload s3://cdk-hnb659fds-assets-ACCOUNT-NUMBER-REGION/95c924c84f5d023be4edee540cb2cb401a49f115d01ed403b288f6cb412771df.zip
36 | info   : [100%] success: Published 95c924c84f5d023be4edee540cb2cb401a49f115d01ed403b288f6cb412771df:ACCOUNT-NUMBER-REGION

```

**Comment by scorobogaci** [comment]
> To expand upon @ijemmy 's comments:
> 
> 1. If you are using `.from_asset()` in your Lambda function stack, your CodePipeline will create an extra step `Assets`.
> 2. This is used to upload your asset files from the `CDKSynth` step to S3.
> 3. Looking into the `buildspec.yml` for that step, you will see something like:
> 
> ```
>       "commands": [
>         "cdk-assets --path \"assembly-STACK/STACK.assets.json\" --verbose publish \"11eecb7b5ccdb7c71db90f9c453ad052b6cdf36b45f7dcfb207bf60e607508c8:ACCOUNT-NUMBER-REGION\""
>       ]
> ```
> 
> 4. With this command, it looks to publish resource `11eecb7b5ccdb7c71db90f9c453ad052b6cdf36b45f7dcfb207bf60e607508c8` in the `assembly-STACK/STACK.assets.json` file to S3.
> 5. On every deployment, that hash value inside the `assembly-STACK/STACK.assets.json` file (from your Synth step) **will change**.
> 6. _HOWEVER_, the `Assets` step's `buildspec.yml` file **will still reference the old hash value**.
> 7. This means your local assets will never upload to S3. The step still will succeed with message:
> 
> ```
> 1 assets found
> --
> Applied selection: 0 assets selected.
> ```
> 
> Because of this, you **must** enable SelfMutate in your CodePipeline, in order for the `buildspec.yml` in your `Assets` step to update.
> 
> Once doing this, you will see the following in your Assets step:
> 
> ```
> 
> verbose: Applied selection: 1 assets selected.
> --
> 33 | info   : [0%] start: Publishing 95c924c84f5d023be4edee540cb2cb401a49f115d01ed403b288f6cb412771df:ACCOUNT-NUMBER-REGION
> 34 | verbose: [0%] check: Check s3://cdk-hnb659fds-assets-ACCOUNT-NUMBER-REGION/95c924c84f5d023be4edee540cb2cb401a49f115d01ed403b288f6cb412771df.zip
> 35 | verbose: [0%] upload: Upload s3://cdk-hnb659fds-assets-ACCOUNT-NUMBER-REGION/95c924c84f5d023be4edee540cb2cb401a49f115d01ed403b288f6cb412771df.zip
> 36 | info   : [100%] success: Published 95c924c84f5d023be4edee540cb2cb401a49f115d01ed403b288f6cb412771df:ACCOUNT-NUMBER-REGION
> ```

are you from this planet ? Did you read the problem ?

**Comment by slpenza** [comment]
> I just ran into this too. Found this, which I'll try: https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-codepipeline-actions/test/integ.lambda-deployed-through-codepipeline.lit.ts

The `CfnParametersCode()` solution is great for a CodeBuildAction in a CodePipeline but local deployment is then unsupported. After executing 'deploy' locally, logging indicates the asset is uploaded successfully while the latest CloudFormation template still points to the cached asset from the last build.

> This happened to me when I forgot to update pipeline (didn't enable selfMutation). Updating pipeline fixed the issue.
> 
> It turns out that some assets building action (in `Assets` stage) were missing. Redeploying creates those missing actions.

I was confused reading that a pipeline will "create actions" until realizing I was instantiating a "aws-codepipline.Pipeline" and NOT a "pipeline.CodePipeline". 

Regardless, not sure I understand why the "synth" command will generate the manifest json for asset upload and then require a specific deployment construct to handle the upload. It's easy to miss noticing that you're deploying a cached asset when you've previously executed the "deploy" command. Unless I'm missing something, a more intuitive approach would have the "synth" command automatically upload the assets the same as the "deploy" command.

**Comment by skinny85** [comment]
> > I just ran into this too. Found this, which I'll try: https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-codepipeline-actions/test/integ.lambda-deployed-through-codepipeline.lit.ts
> 
> The `CfnParametersCode()` solution is great for a CodeBuildAction in a CodePipeline but local deployment is then unsupported. After executing 'deploy' locally, logging indicates the asset is uploaded successfully while the latest CloudFormation template still points to the cached asset from the last build.

Yes, and for that reason, you should use a different solution for local development. This repository shows an example: https://github.com/skinny85/cdk-codepipeline-and-local-lambda-guidance.

But yes, using the `CodePipeline` class from the CDK Pipelines library is the preferred solution.

> Regardless, not sure I understand why the "synth" command will generate the manifest json for asset upload and then require a specific deployment construct to handle the upload. It's easy to miss noticing that you're deploying a cached asset when you've previously executed the "deploy" command. Unless I'm missing something, a more intuitive approach would have the "synth" command automatically upload the assets the same as the "deploy" command.

`synth` is a build-time command, and for that reason it doesn't perform any side-effect computations, like uploading assets.

**Comment by slpenza** [comment]
Thanks for the additional info @skinny85; I reviewed and [forked](https://github.com/slpenza/cdk-codepipeline-and-local-lambda-guidance) your "guidance" repository. Your example is an interesting approach but I prefer to keep development and production resources isolated in different repository branches for a number of reasons outside the scope of this issue. I will investigate and decide if I will use the `pipeline.CodePipeline` for my next new project.

My fork provides an example of how to use "fromAsset" code and a single LambdaStack instance for both local and pipeline deployments. It eliminates the potential for deploying cached Lambda code, and is decoupled from the actual stacks so multiple Lambda and/or CDK stacks can be deployed w/ the same pipeline CDK logic.

The only significant change from your example is a dedicated build action for each Lambda function that handles the asset upload. Please let me know if you have any thoughts or feedback
```
{
          version: '0.2',
          phases: {
            install: {
              commands: [
                `cd lib/${stack.lambdaFolder}`,
                `npm install`,
                `cd ../..`,
                `npm i -g npm && npm ci`,
                `npm install -g cdk-assets`,
              ],
            },
            pre_build: {
              commands: [
                `npm run build`,
                `npm run cdk synth ${stack.stackName}`,
              ]
            },
            build: {
              commands: [
                `cdk-assets -p cdk.out/${stack.stackName}.assets.json publish`
              ]
            },
          },
          artifacts: {
            'base-directory': `cdk.out`,
            files: [
              `${stack.stackName}.template.json`,
            ],
          },
        }
```

**Comment by skinny85** [comment]
No comments from my side - that looks pretty much exactly what the `pipelines.CodePipeline` construct does, just "manually". If this solution works for you, that's great!

**Comment by nchylak** [comment]
For those that may encounter the same issue, one way around it is allowing the role executing the code build project to assume the CDK file asset publishing role in the account(s) in which the assets need to be published.

If you used `cdk bootstrap`, the ARN of this role looks like this: `arn:${AWS::Partition}:iam::${AWS::AccountId}:role/cdk-${Qualifier}-file-publishing-role-${AWS::AccountId}-${AWS::Region}`.

**Comment by skinny85** [comment]
@nchylak this is very helpful. Would you mind posting the full code (importing the bootstrap Role, adding the assume Role permissions to the CodeBuild Role, etc.), for other people to see?

**Comment by skinny85** [comment]
> No comments from my side - that looks pretty much exactly what the `pipelines.CodePipeline` construct does, just "manually". If this solution works for you, that's great!

@slpenza maybe one thing I would change: you're re-synthesizing the CDK application in each Asset publish. There's no reason to do that. Simply transfer the Cloud Assembly (basically, the contents on the `cdk.out` directory) as artifacts from the build stage, and just publish from that.

**Comment by nchylak** [comment]
Sure, this is how I did it:

```typescript
    // create the codebuild project 'buildjob'
    const cbProject = new codebuild.PipelineProject(this, "buildjob", {
      projectName: "repo-cdk-synth",
      buildSpec: codebuild.BuildSpec.fromSourceFilename(".build/buildspec.yaml"),
    });

    // create permission to assume the file asset publishing role
    const assetsPublishingPermissions = new iam.PolicyStatement({
      sid: "extraPermissionsRequiredForPublishingAssets",
      effect: iam.Effect.ALLOW,
      actions: ["sts:AssumeRole"],
      resources: [
        `arn:aws:iam::${account}:role/cdk-${cdk.DefaultStackSynthesizer.DEFAULT_QUALIFIER}-file-publishing-role-${account}-${region}`
      ],
    });

    // attach the permission to the role created with 'buildjob'
    cbProject.addToRolePolicy(assetsPublishingPermissions);
```

With `.build/buildspec.yaml` looking like this:
```yaml
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16

  pre_build:
    commands:
      - npm ci
      - npm install -g cdk-assets@2

  build:
    commands:
      - npm run build
      - npx cdk synth
  
  post_build:
    commands:
      - for FILE in cdk.out/*.assets.json; do cdk-assets -p $FILE publish; done

artifacts:
  files:
    - "cdk.out/*.template.json"
  discard-paths: yes
  name: templates
```

**Comment by skinny85** [comment]
Thanks @nchylak!

**Comment by vsarris** [comment]
> This happened to me when I forgot to update pipeline (didn't enable selfMutation). Updating pipeline fixed the issue.
> 
> It turns out that some assets building action (in `Assets` stage) were missing. Redeploying creates those missing actions.

That worked for me thank you!!!!!!!!!
