### ISSUE TITLE
Unable to use EFS without an expensive nat gateway and EIP [aws-efs] 

### ISSUE THREAD

**Issue by pszabop** [aws/aws-cdk#11022]
If you use the default VPC configuration, it allocates a NAT gateway for each AZ, each of which costs $3 per day, and is completely unneeded by EFS.  This also allocates an EIP, of which only 5 are allowed per account, and thus are a scarce resource also not needed by EFS.

If you specify zero `natGateways` on the VPC creation, and create an EFS instance, you get the following error:

`There are no 'Private' subnet groups in this VPC. Available types: Isolated,Public`

Since I'm using Lambda with EFS and want to be able to talk to `Cognito` and other AWS services that do not have a dedicated gateway, I want to be able to use `PUBLIC`, not `ISOLATED`, networks. 

### Reproduction Steps

Error Message:  `There are no 'Private' subnet groups in this VPC. Available types: Isolated,Public`

```
    const fileSystemVpc = new ec2.Vpc(this, 'vpcForEfs', {
      natGateways: 0,
      maxAzs: 2,
    });
   const fileSystemSecurityGroup = new ec2.SecurityGroup(this, 'fileSystemSecurityGroup', {
      vpc: fileSystemVpc,
      allowAllOutbound: true,
    });
    const efsTimeSeriesDbfileSystem = new efs.FileSystem(this, 'theTimeSeriesDbEfsFileSystem', {
      vpc: fileSystemVpc,
      securityGroup: fileSystemSecurityGroup,
      encrypted: true,
      lifecyclePolicy: efs.LifecyclePolicy.AFTER_14_DAYS,
      performanceMode: efs.PerformanceMode.GENERAL_PURPOSE,
      throughputMode: efs.ThroughputMode.BURSTING
    });
```

### What did you expect to happen?

I was expecting the file system to accept being on the default `PUBLIC` subnet created by the VPC without any errors

### What actually happened?

Error Message:  `There are no 'Private' subnet groups in this VPC. Available types: Isolated,Public`

### Environment

  - **CLI Version:   1.63.0   **
  - **Framework Version:  1.63.0 **
  - **Node.js Version:  v12.16.1 ** 
  - **OS:  Linux 83b2fa42fcf5 4.19.76-linuxkit **
  - **Language (Version): Typescript (3.8.3) ** 

### Other

The issues looks like this:  https://github.com/aws/aws-cdk/pull/7188

These VPC issues are related, but trying all the fixes, none solve the problem.

https://github.com/aws/aws-cdk/issues/7062

https://github.com/aws/aws-cdk/issues/1305

https://github.com/aws/aws-cdk/issues/3704

--- 

This is :bug: Bug Report

**Comment by pszabop** [comment]
specifically specifying subnets doesn't fix the issue - the default selection of `PRIVATE` subnets doesn't appear to get overriden:

```
   const fileSystemVpc = new ec2.Vpc(this, 'vpcForEfs', {
      natGateways: 0,
      maxAzs: 2,
    });

   const publicSubnets = fileSystemVpc.selectSubnets({
      subnetType: ec2.SubnetType.PUBLIC,
    });


    const efsTimeSeriesDbfileSystem = new efs.FileSystem(this, 'theTimeSeriesDbEfsFileSystem', {
      vpc: fileSystemVpc,
      vpcSubnets: {
        // attempted all 3 combinations of these
        subnetType: ec2.SubnetType.PUBLIC,
        subnets: publicSubnets.subnets,
      },
      securityGroup: fileSystemSecurityGroup,
      encrypted: true,
      lifecyclePolicy: efs.LifecyclePolicy.AFTER_14_DAYS,
      performanceMode: efs.PerformanceMode.GENERAL_PURPOSE,
      throughputMode: efs.ThroughputMode.BURSTING
    });
```

same error:  `There are no 'Private' subnet groups in this VPC. Available types: Isolated,Public`

**Comment by pszabop** [comment]
I see that user-defined selectors involved large changes in [v1.64,](https://github.com/aws/aws-cdk/pull/10112/files/d622b19b8677837dc56bf32f8d6129c0e41d4e16) so I will upgrade and test again.

Nevertheless the defaults in all the examples create expensive resources by default.  I will close this if I can find a working configuration
1.  Doesn't use unneeded expensive resources
1.  Allows a lambda function to connect to any of the usual AWS services such as Cognito as well as EFS

**Comment by pszabop** [comment]
The bug was in code I didn't paste.  And by bug, I mean it's an AWS-CDK bug, but it's in the EC2 module not EFS.

Please let me know whether I should reuse this issue or file a new one

I apologize I didn't look at the stack trace (though I notice that constructors don't appear in stack traces, which confused me)

```
    const fileSystemVpc = new ec2.Vpc(this, 'vpcForEfs', {
      natGateways: 0,
      maxAzs: 2,
    });

    /// THIS ASSERTS and is a bug in ec2.vpc
    const privateSubnets = fileSystemVpc.selectSubnets({
      subnetType: ec2.SubnetType.PRIVATE,
    });

```

**Comment by shivlaks** [comment]
> I see that user-defined selectors involved large changes in [v1.64,](https://github.com/aws/aws-cdk/pull/10112/files/d622b19b8677837dc56bf32f8d6129c0e41d4e16) so I will upgrade and test again.
> 
> Nevertheless the defaults in all the examples create expensive resources by default. I will close this if I can find a working configuration
> 
>     1. Doesn't use unneeded expensive resources
> 
>     2. Allows a lambda function to connect to any of the usual AWS services such as Cognito as well as EFS
> 
> 
> UPDATE: Reproduces same way in v1.69

@pszabop which examples are you referring to? the ones in the `efs` module or in the `ec2` module?


> The bug was in code I didn't paste. And by bug, I mean it's an AWS-CDK bug, but it's in the EC2 module not EFS.

> Please let me know whether I should reuse this issue or file a new one

> I apologize I didn't look at the stack trace carefully enough (though I notice that constructors don't appear in stack traces, which confused me)

can you expand a little further? it would be helpful if it followed the same format as the initial post of this issue. feel free to reuse this issue, but I would appreciate if you could re-title and summarize the current problem and expected behaviour.

**Comment by pszabop** [comment]
Resubmitting `selectSubnets` issue in new issue

**Comment by gasi** [comment]
I also have issues with using Lambda + EFS without incurring NAT costs. Linking this issue to https://github.com/aws/aws-cdk/issues/11205.

**Comment by wasa-ism** [comment]
Facing the same issue. Why is an expensive NAT needed? while this is fixed what is the workaround? We are planning to go-live in 2 weeks and this is a big blocker for us.
