### ISSUE TITLE
[aws-ec2]

### ISSUE THREAD

**Issue by rahejaps** [aws/aws-cdk#11038]
---

This is a 📕 documentation issue

**Comment by rahejaps** [comment]
I did not see my description show up. 

I am looking for documentation to add multiple existing security groups to an ec2 instance.  I have tried the following code and it has not worked.

```
globalsg =[
ec2.SecurityGroup.from_security_group_id(self, "sg01", security_group_id = "sg-xb9b"),
ec2.SecurityGroup.from_security_group_id(self, "sg02", security_group_id = "sg-x211")
]
    #Webserver 01
    web01 = ec2.Instance(
        self,
        "web01Id",
        instance_type = ec2.InstanceType(instance_type_identifier=variables["inst_type"]),
        instance_name = "A.APP.PR01",
        machine_image = ec2.MachineImage.generic_linux(
                {variables["region"]: linux_ami}
        ),            
        vpc=vpc,
        vpc_subnets = vpc_priv_use1a,
        user_data = ec2.UserData.custom(user_data),
        security_group= globalsg
    )
```

This is the error when I run "cdk ls"
_jsii.errors.JSIIError: Expected object reference, got [{"$jsii.byref":"@aws-cdk/core.Resource@10052"},{"$jsii.byref":"@aws-cdk/core.Resource@10053"}]      
Subprocess exited with error 1_

**Comment by rix0rrr** [comment]
You can do `web01.add_security_group`.
