### ISSUE TITLE
[core] AWS Tagging and Deprecated Methods

### ISSUE THREAD

**Issue by BrandonCookeDev** [aws/aws-cdk#11037]
## AWS Tagging and Deprecated Methods

https://docs.aws.amazon.com/cdk/latest/guide/tagging.html

Hello all,

I was using a CDK solution I created months ago and has been very sturdy for us when I noticed none of our Tags were being applied to the AWS resources it was creating. I then noticed in my IDE that the `Tag.add` and `Tag.remove` functions were deprecated.

I went to the official Documentation on AWS Tagging resources in CDK to find it lists these methods as the standard way to tag resources via CDK.

My IDE has jsdoc that suggests using `Tags.of(construct).add()` which I tried and also did not work. 

So not really sure where to go from here. Any pointers would be greatly appreciated.

(using version 1.69 now btw)

---

This is a 📕 documentation issue

**Comment by BryceLarkin** [comment]
I'm using something similar to `Aspects.of(this).add(new Tag('Region', 'us-east-2'))`, however this seems like a lot of boilerplate compared to the depreciated `Tag.add` method.

**Comment by Jerry-AWS** [comment]
I have an issue over in the CDK Dev Guide repo to update the Tags and Aspects topics to reflect the new API. I've actually completed this work, and it should be published in a couple of days. https://github.com/awsdocs/aws-cdk-guide/issues/259

`Tags.of(construct).add(...)` is indeed the new API. The deprecated API will, however, continue to work until CDK v2 is released.

If either the old or new API, isn't working, that bears further investigation. Both should work, though the old one will cause a warning.

**Comment by Jerry-AWS** [comment]
I've updated the Aspects and Tagging topics in the CDK Developer Guide with the new APIs.

https://docs.aws.amazon.com/cdk/latest/guide/aspects.html  
https://docs.aws.amazon.com/cdk/latest/guide/tagging.html  

If you find an error in one of these topics, please open an issue in the CDK Dev Guide repo.

https://github.com/awsdocs/aws-cdk-guide/issues

If it doesn't work, open a new issue here, that could be a bug and should get some attention from an engineer.

I'll close this.
