### ISSUE TITLE
[codebuild] missing permissions when using Parameter Store variables

### ISSUE THREAD

**Issue by markusl** [aws/aws-cdk#11032]
It seems Pipeline does not have access to the specified `environmentVariables`.

### Reproduction Steps

```ts
    synthAction: SimpleSynthAction.standardNpmSynth({
      environmentVariables: {
        VARIABLE_NAME: {
          type: codebuild.BuildEnvironmentVariableType.PARAMETER_STORE,
          value: '/CodeBuild/VARIABLE_NAME'
        }
      },
      environment: { privileged: true },
      sourceArtifact,
      cloudAssemblyArtifact,

    }),
```

### What did you expect to happen?

The Pipeline would be able to read the specified parameters.

### What actually happened?

```
Decrypted Variables Error: AccessDeniedException: User: arn:aws:sts::xxxx:assumed-role/PipelineBuildSynthCdkBuildPr-1FB7OJQPMW7D5/AWSCodeBuild-dac52976-f00b-4937-bc26-756532fff077 is not authorized to perform: ssm:GetParameters on resource: arn:aws:ssm:eu-central-1:xxx:parameter/CodeBuild/VARIABLE_NAME status code: 400, request id: afc265c1-e85e-4b21-aede-fa53b674f486
```

### Environment

  - **CLI Version      :** 1.69.0 (build 2b474b9)
  - **Framework Version:** 1.69.0
  - **Node.js Version:** v14.13.0
  - **OS               :** macOS
  - **Language (Version):** TypeScript

### Other

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
Better to fix it in the underlying CodeBuild implementation

**Comment by skinny85** [comment]
I believe this should have been fixed already.

@markusl can you verify whether it works with the latest CDK version?

Thanks,
Adam

**Comment by markusl** [comment]
Yep, I believe this has been fixed.
