### ISSUE TITLE
[sqs] Generated fifo queue name not truncating and causes errors

### ISSUE THREAD

**Issue by steveyackey** [aws/aws-cdk#11041]
When creating a FIFO SQS queue, if the name exceeds the allotted characters, it does not truncate, but instead returns this error: 

_Queue (Queue4A7E3555) The name of a FIFO queue can only include alphanumeric characters, hyphens, or underscores, must end with .fifo suffix and be 1 to 80 in length._

### Reproduction Steps

- Create a new stack with a long name
- Add a queue with the ID "Queue"
- Set Fifo:true for the queue

### What did you expect to happen?

When creating a standard (non-fifo) queue, it truncates the name before adding the hash at the end. When enabling FIFO, I expected it to truncate the name and add .fifo to the end. 

### What actually happened?

I received this error: _Queue (Queue4A7E3555) The name of a FIFO queue can only include alphanumeric characters, hyphens, or underscores, must end with .fifo suffix and be 1 to 80 in length._

### Environment

  - **CLI Version      :)** 1.67.0 
  - **Framework Version:** 1.64.0
  - **Node.js Version:** v12.19.0
  - **OS               :** Linux -- Ubuntu 18.04
  - **Language (Version):** 3.1.403

### Other

We have stack names generated partially by the git branch name, which sometimes causes long stack names. 

--- 

This is :bug: Bug Report

**Comment by elemakil** [comment]
This seems to be a duplicate of #5860.
