### ISSUE TITLE
[apigateway] Missing default for enum

### ISSUE THREAD

**Issue by mmuller88** [aws/aws-cdk#11065]
For the model definition you can specify an enum as propery. It is missing to specify the default as well. I attached a picture as proof.

### Reproduction Steps

```TypeScript
const status: Model = api.addModel('status', {
      schema: {
        type: JsonSchemaType.STRING,
        description: "Shows the current state. Even if your instance is in the running state it might take some minutes until the provided url is reachable.",
        enum: [ "running", "terminated", "stopped", "pending", "stopping" ],
        default: "running",
      }
    });
```

### What did you expect to happen?

the **default** property is valid.

### What actually happened?

the **default** property isn't valid.

### Environment

  - **CLI Version      :**
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):** 

### Other

--- 

This is :bug: Bug Report

**Comment by mmuller88** [comment]
AWS Console would complain if default wasn't valid

![defaultProp](https://user-images.githubusercontent.com/18393842/97017084-ccf1dd00-154d-11eb-8f9a-fe81c1a7bc93.png)

**Comment by nija-at** [comment]
`default` needs to be added to our schema here - https://github.com/aws/aws-cdk/blob/0537598a065c74c713d1ec58c96f09f0d66b12ca/packages/%40aws-cdk/aws-apigateway/lib/json-schema.ts#L27

Marking this as a feature request.

**Comment by mmuller88** [comment]
Many thanks. I tried to solve it with https://github.com/aws/aws-cdk/pull/11064 but something is wrong in the unit tests. Unlucky I don't get that unit test running locally. Can you might point me to the instruction for doing that pls.

**Comment by mmuller88** [comment]
jai I got the feat branch passing :)
