### ISSUE TITLE
[RDS] OracleEngineVersion.class is has only outdated minor versions  

### ISSUE THREAD

**Issue by magnusalstad** [aws/aws-cdk#11066]
## :question: General Issue
The latest Java cdk (1.69) is missing the latest minor versions:
https://docs.aws.amazon.com/cdk/api/latest/java/index.html?software/amazon/awscdk/services/rds/OracleEngineVersion.html
OracleEngineVersion class lists 12.2.0.1.ru-2020-04.rur-2020-04.r1, 18.0.0.0.ru-2020-04.rur-2020-04.r1 and 12.2.0.1.ru-2020-04.rur-2020-04.r1 as latest version, I'm missing the latest ones documented here: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Appendix.Oracle.PatchComposition.html
2020 July | 19.0.0.0.ru-2020-07.rur-2020-07.r1 | 18.0.0.0.ru-2020-07.rur-2020-07.r1 | 12.2.0.1.ru-2020-07.rur-2020-07.r1

### The Question
When can we expect the OracleEngineVersion class to be updated with the current minor versions? 

### Environment

  - **CDK CLI Version:** 1.69 
  - **Module Version:** RDS 
  - **Language (Version):** Java

**Comment by skinny85** [comment]
Hey @magnusalstad ,

this should be a simple change, adding the new constants to the [`OracleEngineVersion` class](https://github.com/aws/aws-cdk/blob/24e98cb3f6e91da501db763323655e15611cdca6/packages/%40aws-cdk/aws-rds/lib/instance-engine.ts#L688-L769), similar to other Pull Requests that added these ([[1]](https://github.com/aws/aws-cdk/pull/10757), [[2]](https://github.com/aws/aws-cdk/pull/10857)). Any chance you could submit a change like that to our project? Our contributor documentation is [here](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md).

In the meantime, you can use the `of` static factory method of the `OracleEngineVersion` class to create an arbitrary version.

Thanks,
Adam
