### ISSUE TITLE
[RDS] Deploying RDS only using major RDS version can result in outdated patch/minor version 

### ISSUE THREAD

**Issue by magnusalstad** [aws/aws-cdk#11067]
## :question: General Issue

I've been observing that when you deploy a new RDS instance, specifying only major engine version, eg. MySql 5.7 or Oracle 19, the minor version isn't always the latest one. It looks like the minor version you actually get is non deterministic. 

This can cause issues when restoring a snapshot created on eg a 5.7 engine if you don't explicitly restore it to the latest minor version, or if you don't use the exact minor version contained in the snapshot.   

### The Question
Is the minor version supposed to not always be the latest one? If so why?

### Environment

  - **CDK CLI Version:** 1.64
  - **Module Version:** RDS 1.64
  - **Language (Version):** Java

**Comment by skinny85** [comment]
Hey @magnusalstad ,

thanks for opening the issue, but is there anything CDK-specific about your question? Would maybe engaging with the RDS service team be a better way to go here?

Thanks,
Adam

**Comment by magnusalstad** [comment]
Hi @skinny85,
I was using CDK to create RDS instances & specify major versions like Oracle 19 & MySql 5.7.
That the CloudFormation output contains those values directly, so I suppose you're right that this doesn't relate directly to CDK, but rather the interpretation of CF for RDS. Not sure how can I engage with the RDS service team here?

Br. Magnus

**Comment by skinny85** [comment]
@magnusalstad the best way to reach the RDS team is through premium support, if you have it.

In general, the CDK provisions resources of various services, but we don't really control how each individual service behaves.

Do you maybe want us to add a warning to the documentation on using the major-only versions of the engine, like Oracle `VER_19`?

Thanks,
Adam

**Comment by magnusalstad** [comment]
Thank you, I'll see if I can contact the RDS team about this issue.
 
I'm not sure if adding a general warning on using major-only versions is the right thing, maybe the user has a use case where he doesn't need to care about minor versions. It could however state that you are not guaranteed to get the latest minor version when deploying a major-only version. 

Br. Magnus
