### ISSUE TITLE
[aws-eks] Not Allowing Me to Supply All Roles

### ISSUE THREAD

**Issue by ssg-cnc** [aws/aws-cdk#11074]
### The Question

My company requires that every role have a permission boundary attached to it and be prefix with “cnc-“.  Any roles attempted to be created without both of these will fail and generate a permission denied error.  When I am building out infrastructure using CDK, I generally can create CDK roles that satisfy both requirements, but EKS clusters generate four roles, and I can only replace two of them. The two that I cannot replace is the “kubectlRole” and the “nodeRole” in the node group.  It would be great if I could supply both of these in the ClusterProps class.  

I understand that I will have to make sure each role has the correct policies attached to each.  I’ve seen how the roles/policies are created by running “cdk synth” command.  I appreciate any time you can spend on this.  
### Environment

  - **CDK CLI Version:**  1.69
  - **Module Version:**  1.69
  - **Node.js Version:**  12.18.0
  - **OS:**  macOS Mojave 10.14.6
  - **Language (Version):**  JavaScript

### Other information

I synth the following JavaScript command:
...
       const cluster = new Cluster(this, clusterOptions.name, {
            version: KubernetesVersion.V1_18,
            clusterName: clusterOptions.name,
            role: eksRole,
            mastersRole: eksClusterAdminRole,
        });
...

**Comment by iliapolo** [comment]
Hi @ssg-cnc - Thanks for reporting this. Its a valid use-case so im marking this as a feature request.

Regarding the `nodeRole` though - you can specify it via the [`nodeRole`](https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-eks/lib/managed-nodegroup.ts#L157) property. 

https://github.com/aws/aws-cdk/blob/75875ccbc4c937ef8b57ac996de8afb52f8a8138/packages/%40aws-cdk/aws-eks/lib/managed-nodegroup.ts#L149-L157

Is that not you meant? 

Regarding the `kubectlRole`, you can gain access to it using `cluster.kubectlRole` and use [escape hatches](https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html) to reconfigure the name and the permission boundaries. Its not the most elegant way, but it case you are blocked, this can help.

**Comment by ssg-cnc** [comment]
Eli,

Thank you for the quick reply.

Yes, the nodeRole in NodeGroups is generated automatically for me by the call to create a new Cluster.  The link you specified reads:

>To access the node group that was created on your behalf, you can use cluster.defaultNodegroup.

>Additional customizations are available post instantiation. 

Post instantiation is too late.  I need to pass in a nodeRole to the Cluster class construct method so that the NodeGroup uses the role I specify.  I assume I can use escape hatches for this as well?

For kubectlRole, I will look into escape hatches.  Thank you.

Sincerely,

Jeff

**Comment by ssg-cnc** [comment]
Under the hood, in EKS Cluster, there is a CreationRole that is the "kubectlRole", so I tried to modify the permissions boundary without success.  Here is the code:

        const cluster = new Cluster(this, clusterOptions.name, {
            version: KubernetesVersion.V1_18,
            clusterName: clusterOptions.name,
            role: eksRole,
            mastersRole: eksClusterAdminRole,
        });

        const clusterResource = cluster.node.defaultChild;
        const clusterCreationRole = clusterResource.node.tryFindChild(
            "CreationRole"
        );
        clusterCreationRole.permissionsBoundary = {
            managedPolicyArn: `arn:aws:iam::${props.account}:policy/lz/power-user`,
        };
        console.error(clusterCreationRole);

Although, when I run the synth command, I can see the permission boundary field has been updated by looking through the console error output, but **the permission boundary in the template file has not been updated**:

> cdk synth -a "node bin/cdk-eks.js --cn clusterName --an 458355938168" > template.yaml

**Comment by iliapolo** [comment]
@ssg-cnc Thats a great way to implement it actually.

I just want to clarify some things for future reference. 

You mentioned:

> I need to pass in a nodeRole to the Cluster class construct method so that the NodeGroup uses the role I specify.

You're right that `nodeRole` is not available on the `Cluster` construct. What you can do is set the default capacity of the cluster to 0, and create your own node group:

```ts
const cluster = new eks.Cluster(this, 'Cluster', {
  version: eks.KubernetesVersion.V1_18,
  defaultCapacity: 0,
})

cluster.addNodegroupCapacity(this, 'NodeGroup, {
  instanceType: ec2.InstanceType.of(ec2.InstanceClass.M5, ec2.InstanceSize.LARGE),
  minSize: 2,
  nodeRole: // pass your role here...
})
```

Regarding the `kubectlRole`, there are some subtle points when using escape hatches, here is how it should look like:

```ts
const kubectlCfnRole = cluster.kubectlRole!.node.defaultChild as iam.CfnRole;
kubectlCfnRole.permissionsBoundary = `arn:aws:iam::${props.account}:policy/lz/power-user`;
```

Notice that you need to mutate the underlying L1 `iam.CfnRole` and not the L2 `iam.Role`. Also, the permissions boundary is a string, not an object: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html#cfn-iam-role-permissionsboundary
