### ISSUE TITLE
[@aws-cdk/aws-ses] EventDestinationProperty missing snsDestination

### ISSUE THREAD

**Issue by thibaut-pro** [aws/aws-cdk#11106]
### The Question

I am trying to set up an AWS SES configuration set to track opens on emails I send through cdk. I noticed that the [EventDestinationProperty](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ses.CfnConfigurationSetEventDestination.EventDestinationProperty.html) for SES does not include an SNS event destination even though that is available in the console:

![image](https://user-images.githubusercontent.com/59576766/97127052-c7cf9200-16f5-11eb-9868-ae49d0d90bbf.png)

### Other information

That event destination is available for the pinpoint service: [EventDestinationProperty](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-pinpointemail.CfnConfigurationSetEventDestination.EventDestinationProperty.html).

![image](https://user-images.githubusercontent.com/59576766/97127147-1846ef80-16f6-11eb-8ddb-004f195367f0.png)

**Comment by thibaut-singlefile** [comment]
@iliapolo any update? This is a blocking issue for us.

**Comment by AlexZeitler** [comment]
I'm facing the same issue.

I tried using the `CfnConfigurationSetEventDestination` from `@aws-cdk/aws-pinpointemail` (@1.72.0) instead like this:

```ts
new CfnConfigurationSetEventDestination(this, "ses-email-notification-bounce-sns", {
      configurationSetName: "ses-config-notifications",
      eventDestinationName: "ses-email-notification-bounce-sns",
      eventDestination: {
        matchingEventTypes: ["bounce"],
        snsDestination: {
          topicArn: "..."
        }
      }
    })
```

But it failed with: 

```bash
The event destination contains an invalid event type. (Service: AmazonPinpointEmail; Status Code: 400; Error Code: BadRequestException;
```

**Comment by AlexZeitler** [comment]
I guess the underlying issue is that you can't specify SNS event destinations in CloudFormation:

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ses-configurationseteventdestination-eventdestination.html

![image](https://user-images.githubusercontent.com/287480/98644334-9af3bf80-2330-11eb-83e1-970951ae3f83.png)

**Comment by thibaut-singlefile** [comment]
Good find. I just reached out to CloudFormation support about that.

**Comment by AlexZeitler** [comment]
I've contaced support via Twitter as well https://twitter.com/AWSSupport/status/1326071942328315904

**Comment by thibaut-singlefile** [comment]
Response from AWS Support:
> This is an update to inform you that I have reached out to the internal team and there is already a Feature Request issue raised with the internal team for this and that internal service team is actively working on this.

**Comment by jogold** [comment]
This is tracked here https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/50

**Comment by lielran** [comment]
A workaround till this will be supported by CFN (and then cdk). 
```
const name =  'myConfigSet';
const topic = new Topic(this, 'Topic', {
            displayName: `myTopic`,
 });
const events = ['click', 'bounce', 'send', 'open', 'complaint', 'delivery', 'reject'];
        new AwsCustomResource(this, `EmailDestination`, {
            policy: {
                statements: [
                    new PolicyStatement({
                        effect: Effect.ALLOW,
                        actions: ['ses:CreateConfigurationSetEventDestination'],
                        resources: [
                            `arn:${this.partition}:ses:${this.region}:${this.account}:configuration-set/${name}`,
                        ],
                    }),
                ],
            },

            onUpdate: {
                service: 'SESV2',
                action: 'createConfigurationSetEventDestination',
                parameters: {
                    ConfigurationSetName: name,
                    EventDestinationName: `${props.serviceName}-${props.stage}-topic`,
                    EventDestination: {
                        Enabled: true,
                        MatchingEventTypes: events.map((e) => e.toUpperCase()),
                        SnsDestination: {
                            TopicArn: topic.topicArn,
                        },
                    },
                },
                physicalResourceId: PhysicalResourceId.of(topic.topicArn),
            },
        });

```

**Comment by metdockal** [comment]
Grat tip @lielran !

I just extended your example with `onDelete` and `onCreate` hooks

```typescript
const topic = new sns.Topic(this, 'TopicSes', { topicName: `YOUR_TOPIC_NAME` });
topic.addSubscription(new subscriptions.EmailSubscription('YOUR EMAIL'));

const MatchingEventTypes = ['reject', 'bounce', 'complaint', 'send', 'delivery'].map((e) => e.toUpperCase());
const ConfigurationSetName = `CONFIGURATION_SET_NAME`;
const EventDestinationName = `DEST_NAME`;
new ses.CfnConfigurationSet(this, 'configurationSet', {
	name: ConfigurationSetName,
});

new AwsCustomResource(this, `EmailDestination`, {
	policy: {
		statements: [
			new PolicyStatement({
				effect: Effect.ALLOW,
				actions: ['ses:UpdateConfigurationSetEventDestination', 'ses:CreateConfigurationSetEventDestination', 'ses:DeleteConfigurationSetEventDestination'],
				resources: [`arn:${this.partition}:ses:${this.region}:${this.account}:configuration-set/${ConfigurationSetName}`],
			}),
		],
	},

	onCreate: {
		service: 'SESV2',
		action: 'createConfigurationSetEventDestination',
		parameters: {
			ConfigurationSetName,
			EventDestinationName,
			EventDestination: {
				Enabled: true,
				MatchingEventTypes,
				SnsDestination: {
					TopicArn: topic.topicArn,
				},
			},
		},
		physicalResourceId: PhysicalResourceId.of(topic.topicArn),
	},

	onUpdate: {
		service: 'SESV2',
		action: 'updateConfigurationSetEventDestination',
		parameters: {
			ConfigurationSetName,
			EventDestinationName,
			EventDestination: {
				Enabled: true,
				MatchingEventTypes,
				SnsDestination: {
					TopicArn: topic.topicArn,
				},
			},
		},
		physicalResourceId: PhysicalResourceId.of(topic.topicArn),
	},

	onDelete: {
		service: 'SESV2',
		action: 'deleteConfigurationSetEventDestination',
		parameters: {
			ConfigurationSetName,
			EventDestinationName,
		},
		physicalResourceId: PhysicalResourceId.of(topic.topicArn),
	},
});
```

**Comment by jumic** [comment]
@otaviomacedo I think that this issue can be closed.

In CloudFormation, the functionality is now available. The issue in the CloudFormation coverage roadmap was closed: https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/50 

[EventDestinationProperty](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ses.CfnConfigurationSetEventDestination.EventDestinationProperty.html) (CDK) also supports adding an SNS destination (property `snsDestination`).

**Comment by tim-finnigan** [comment]
Closing issue as [snsDestination](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ses.CfnConfigurationSetEventDestination.EventDestinationProperty.html#snsdestination) is now available.
