### ISSUE TITLE
[@aws-cdk/aws-codedeploy] Add support for Deployment Triggers prop in LambdaDeploymentGroup construct

### ISSUE THREAD

**Issue by Ajaydiwa** [aws/aws-cdk#11110]
LambdaDeploymentGroup construct does not provide prop for adding deployment triggers. Can we have support for this in the construct?

### Use Case

This prop will help to notify based on the different deployment events.

This is a :rocket: Feature Request

**Comment by skinny85** [comment]
Thanks for opening the issue @Ajaydiwa . Would you be interested in working on this issue? Here's our [Contribution documentation](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md).

I'd be glad to discuss the design of this feature in this issue.
