### ISSUE TITLE
[module] codebuild.Cache.none() should resolve to NO_CACHE instead of undefined

### ISSUE THREAD

**Issue by muja** [aws/aws-cdk#11116]
Changing from `codebuild.Cache.bucket` to `codebuild.Cache.none` will leave the s3 bucket intact in the AWS::CodeBuild::Project

### Reproduction Steps

1. Create a stack with a CodeBuild project with `cache` set to `codebuild.Cache.bucket()`
2. Update stack with `cache` set to `codebuild.Cache.none()`
3. Execute CLI command: `aws codebuild batch-get-projects --names <ProjectNameFromStack>`

### What did you expect to happen?

Cache will be empty or "type=NO_CACHE"

### What actually happened?

Cache was still s3

### Environment

  - **CLI Version      :** 1.65.0
  - **Framework Version:** 1.65.0
  - **Node.js Version:** all
  - **OS               :** all
  - **Language (Version):** TypeScript

### Other

If the S3 bucket is deleted, the CodeBuild Project will be unable to update. One needs to manually update the project with parameter `--cache type=NO_CACHE` to repair it.

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hey @muja ,

sorry you are running into this. Note that you can always use ["escape hatches"](https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html#cfn_layer_resource) to set the `cache` property yourself:

```ts
    const cfnProject = project.node.defaultChild as codebuild.CfnProject;
    cfnProject.cache = {
      type: 'NO_CACHE',
    };
```

Can you let me know if that fixes your problem?

Thanks,
Adam

**Comment by muja** [comment]
Thank you for your reply @skinny85.
While that's a workaround that works, it still does not help the fact that the way the normal way works is completely unexpected and goes against the principle of least surprise. So my initial point still stands, the expected behavior would be that specifying `Cache.none()` will lead to *no cache* to be used and not possibly lead to an S3 cache to be used. As such, I'm not sure if it was warranted to have the `bug` label removed. This is clearly a bug.

**Comment by skinny85** [comment]
I agree. The problem is this is a bug in the CodeBuild CloudFormation support, not in the CDK.
