### ISSUE TITLE
[assets] Exclude macOS .DS_Store files by default

### ISSUE THREAD

**Issue by RomainMuller** [aws/aws-cdk#11119]
# Use Case

MacOS tends to drop `.DS_Store` files to store Finder preferences and other metadata when he Finder traverses a directory. Such files are going to change asset hashes and trigger spurious changes.

It is common for macOS users to have a user-level or project-level git ignore list that includes `.DS_Store` files in order to avoid having to deal with them in git history... Meaning regression tests based on inspecting a template for changes will be tripped in a very confusing manner if that file is not excluded.

Reference: https://wikipedia.org/wiki/.DS_Store

**Comment by cokia** [comment]
I think this is already solved issue

**Comment by jaresuth** [comment]
This should be closed due to this being in .gitignore? https://github.com/aws/aws-cdk/blob/master/.gitignore#L11
