### ISSUE TITLE
[cloudwatch]  Python : creating composite alarms using anyOf

### ISSUE THREAD

**Issue by du291** [aws/aws-cdk#11120]
It is not clear how to create composite alarms using the anyOf. Documentation does not cover this and from source code it would appear I need to pass a list of IAlarmRule but that does not work.

### Reproduction Steps

```python
    def create_composite_alarm(alarms: List[aws_cloudwatch.Alarm]) -> aws_cloudwatch.CompositeAlarm:
        any_of_list : List[aws_cloudwatch.IAlarmRule] = [aws_cloudwatch.AlarmRule.from_alarm(
            alarm,
            alarm_state=aws_cloudwatch.AlarmState.ALARM) for alarm in alarms]
        composite_rule: aws_cloudwatch.IAlarmRule = aws_cloudwatch.AlarmRule.any_of(any_of_list)
```

### What did you expect to happen?

Alarm rule is created that is usable for aws_cloudwatch.CompositeAlarm

### What actually happened?

exception

> jsii.errors.JSIIError: Expected object reference, got [{"$jsii.byref":"Object@10112"},{"$jsii.byref":"Object@10113"},{"$jsii.byref":"Object@10114"},{"$jsii.byref":"Object@10115"}]

### Environment

  - **CLI Version      : 1.70**
  - **Framework Version: Python 3.8.5**
  - **Node.js Version: v14.11.0** 
  - **OS               : Linux**
  - **Language (Version): Python (3.8.5)** 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
`any_of` is actually variadic.

So don't call it like:

```
AlarmRule.any_of([one, two, three])

# But like
AlarmRule.any_of(one, two, three)
```
