### ISSUE TITLE
[cdk-pipelines] obscur error when missing a stage

### ISSUE THREAD

**Issue by fbouteruche** [aws/aws-cdk#11129]
https://docs.aws.amazon.com/cdk/api/latest/docs/pipelines-readme.html#cdk-versioning

From my experience, it seems that a CDK Pipelines needs at least one stage while the documentation suggests that you can use only the source action and the synth action.

I developed a CDK pipeline that was missing a stage and I got the following obscur error message: 

`Call failed: getTemplate({"StackName":"XXXStackPipeline","TemplateStage":"Original"}) => User: arn:aws:sts::111111111111:assumed-role/XXXXStackPipeline-XXXXPipelineUpdate-Z9QLO4CVYY06/AWSCodeBuild-a6d7380a-a435-4d66-abb5-f631083e0abb is not authorized to perform: cloudformation:GetTemplate on resource: arn:aws:cloudformation:eu-west-1:111111111111:stack/XXXXStackPipeline/43c0a740-176f-11eb-a7c3-0a7ffa9bc424`

---

This is a 📕 documentation issue

**Comment by rix0rrr** [comment]
This needs some code to reproduce

**Comment by OperationalFallacy** [comment]
This is easy to repro

```
import * as codepipeline from '@aws-cdk/aws-codepipeline';
import * as actions from '@aws-cdk/aws-codepipeline-actions';
import * as cdk from '@aws-cdk/core';
import { CdkPipeline, SimpleSynthAction } from '@aws-cdk/pipelines';

export interface PipelineStackProps extends cdk.StackProps {
  name: string;
}

export class PipelineStack extends cdk.Stack {

  constructor(scope: cdk.Construct, id: string, props: PipelineStackProps) {
    super(scope, id, props);
    
    const sourceArtifact = new codepipeline.Artifact();
    const cloudAssemblyArtifact = new codepipeline.Artifact();

    const pipeline = new CdkPipeline(this, 'Pipeline', {
      pipelineName: `${props.name}-DeliveryPipeline`,
      cloudAssemblyArtifact,
      sourceAction: new actions.GitHubSourceAction({
        actionName: 'GitHub',
        output: sourceArtifact,
        oauthToken: cdk.SecretValue.secretsManager('xxx'),
        trigger: actions.GitHubTrigger.WEBHOOK,
        owner: 'yyy',
        repo: 'somerepo',
        branch: 'master',
      }),

      synthAction: SimpleSynthAction.standardYarnSynth({
        sourceArtifact,
        cloudAssemblyArtifact,
        environment: {
          privileged: true,
        }
      })
    })
    
    console.log(pipeline)

  }
}

```

![image](https://user-images.githubusercontent.com/62673610/108095270-ad774680-704d-11eb-97a6-6f136ba2eb10.png)

**Comment by guusvw** [comment]
Any updates on that one?
