### ISSUE TITLE
[cdk-pipelines] MVP Done, questions about ECS deployment

### ISSUE THREAD

**Issue by arpowers** [aws/aws-cdk#11125]
Hey guys, again great work on CDK. It's an exciting new codebase to work with. 

We have finished an MVP pipeline using the new CDK pipeline construct but have a few lingering questions and it would be helpful to have some direction. 

## Syncing Asset Deployment 
In our stack, we are deploying static assets to CDN like [darwin](https://www.darwin.so)'s tracking script; but we are also potentially making changes to other areas of our backend at the same time. 

There is a syncing issue... in deployment, the static assets may "go live" 5 to 15 minutes before the rest of the stack. (This potentially leads to 15 minutes of fatal errors when they are out of sync)... 

How do we force things to update at the same time? 

## Blue/Green and ECS

The walkthrough by @rix0rrr  in this [video](https://www.youtube.com/watch?v=1ps0Wh19MHQ) discusses "safe" deployment to lambda and techniques for that. 

However, the same features for Fargate are yet to be developed? What would be the current best practice for deployments in ECS?

*Here is our Pipeline:*

![screencapture-console-aws-amazon-codesuite-codepipeline-pipelines-PipelineStack-Pipeline9850B417-WFFOU3FE4YEH-view-2020-10-26-10_51_55](https://user-images.githubusercontent.com/308134/97210690-2db22d00-177b-11eb-9237-7ca8e0215d3a.png)

**Comment by rix0rrr** [comment]
> How do we force things to update at the same time?

In distributed systems, this is generally impossible. How were you expecting to do it?

What you are probably thinking of doing is shrink the window of inconsistency to so little that a casual F5 won't pick up the inconsistency. That is not really a tenable solution in the long term, and break if latency creeps in for whatever reason (or if you want to do rolling updates that stretch a longer period of time). Generally a better long-term strategy is to upload static assets under new identifiers (a timestamp, GUID, or content hash) and reference the new identifier in your HTML later on when your app code is being deployed.

In that case, both old and new assets are available at the same time and both can be referenced by both old and new versions of the code.

> However, the same features for Fargate are yet to be developed? What would be the current best practice for deployments in ECS?

I honestly couldn't tell you. Other blue/green deployments for CloudFormation look *a lot* different from the Lambda ones, and we haven't been able to look into it very deeply yet.

This is brave new frontier land, if you or someone else can tell us what it should look like: great, but we don't have any suggestions yet in that area.

**Comment by arpowers** [comment]
> Generally a better long-term strategy is to upload static assets under new identifiers (a timestamp, GUID, or content hash) and reference the new identifier in your HTML later on when your app code is being deployed.

Typically this is what we would do, however we are distributing a tracking snippet so the script needs to forever live at the same URL. That said, we have a few ideas to keep things consistent. 

Thanks for the answers.
