### ISSUE TITLE
[aws-sns] SNS FIFO 

### ISSUE THREAD

**Issue by sawasawasawa** [aws/aws-cdk#11127]
When can we expect sns cdk to support FIFO? https://docs.aws.amazon.com/cdk/api/latest/docs/aws-sns-readme.html

---

This is a 📕 documentation issue

**Comment by NetaNir** [comment]
You can define a fifo queue today is using `fifo:true`:

```ts
const fifoQueue = new Queue(stack, 'FifoQueue', {
  fifo: true,
  ....
});
```

**Comment by risenberg-cyberark** [comment]
+1, really waiting for this.

**Comment by skyrpex** [comment]
Is it just a documentation issue? Does that mean that I can build SNS FIFO already?

**Comment by frjtrifork** [comment]
Since it is supported in Cloudformation already, then you can use the cdk escape hatch approach and add raw property overrides to make a SNS fifo topic.

Like so:
```public static createFifoTopic(stack: Stack, name: string) {
    if (!name.endsWith('.fifo')) name = name + '.fifo';
    const topic = new sns.Topic(stack, name, {
      displayName: name,
      topicName: name
    });
    
    const cfnTopic = topic.node.defaultChild as CfnTopic
    cfnTopic.addPropertyOverride("FifoTopic", true);
    cfnTopic.addPropertyOverride("ContentBasedDeduplication", false);
    return topic;
  }```

Which called like so
SnsComponent.createFifoTopic(stack, 'foo') 

Will synthesize into
```
    "footopicfifoCAF914F4": {
      "Type": "AWS::SNS::Topic",
      "Properties": {
        "ContentBasedDeduplication": false,
        "DisplayName": "foo.fifo",
        "TopicName": "foo.fifo",
        "FifoTopic": true
      },
      "Metadata": {
        "aws:cdk:path": "fooservice-stack/foo.fifo/Resource"
      }
    },
```

**Comment by skyrpex** [comment]
@frjtrifork thank you, that was very helpful!

**Comment by gergan** [comment]
It seems there is a bug in CloudFormation, the TopicName with the .fifo ending should be created correctly from CloudFormation, but this does not happen currently. That's why @frjtrifork uses fix name with .fifo ending probably?

**Comment by rrhodes** [comment]
Hello, I'm opening a PR now to support content-based deduplication and FIFO topics using the `Topic` CDK construct.

**Comment by gregglazewskiecl** [comment]
Any idea when would it be released after merging PR? This is a super needed feature.
