### ISSUE TITLE
[aws-iam] FederatedPrincipal conditions property should not be required.

### ISSUE THREAD

**Issue by JordanDeBeer** [aws/aws-cdk#11139]
When creating an `iam.FederatedPrincipal`, the `conditions` parameter is required. This property should be optional.

### Reproduction Steps

`new iam.FederatedPrincipal('cognito-identity.amazonaws.com')`

### What did you expect to happen?
The principal would be returned and the FederatedPrincipal added to the policy.

### What actually happened?
```
lib/streamer-badge-live.ts:46:22 - error TS2554: Expected 2-3 arguments, but got 1.

46         principals: [new iam.FederatedPrincipal("aws-cognito")],
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  node_modules/@aws-cdk/aws-iam/lib/principals.d.ts:364:36
    364     constructor(federated: string, conditions: Conditions, assumeRoleAction?: string);
                                           ~~~~~~~~~~~~~~~~~~~~~~
    An argument for 'conditions' was not provided.
```

### Environment

  - **CLI Version      :1.70.0
  - **Framework Version: 1.70.0
  - **Node.js Version:v12.18.3 
  - **OS               : Linux
  - **Language (Version):all 

### Other

--- 

This is :bug: Bug Report

**Comment by JordanDeBeer** [comment]
There is the `WebIdentityPrincipal` class which allows accomplishes what I am trying to do. But most of the docs I had read mentioned the `FederatedPrincipal`.

**Comment by cecheta** [comment]
I've raised https://github.com/aws/aws-cdk/pull/20621 which should close this
