### ISSUE TITLE
[stepfunctions] Choice state should implement INextable

### ISSUE THREAD

**Issue by neukev** [aws/aws-cdk#11159]
To more closely match up with the [Amazon States Language for Choice states](https://docs.aws.amazon.com/step-functions/latest/dg/concepts-amazon-states-language.html), the [Choice](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-stepfunctions/lib/states/choice.ts) class should implement INextable.

### Use Case

One use case is a loop, such as to page through a list API, such as:

```json
{
    "StartAt": "List",
    "States": {
        "List": {
            "Type": "Task",
            "Comment": "List items from a paginated source and output them",
            "Resource": "...",
            "Next": "Process" 
        },
        "Process": {
            "Type": "Task",
            "Comment": "Process items from input",
            "Resource": "...",
            "Next": "NextPageCheck"
        },
        "NextPageCheck": {
            "Type": "Choice",
            "Comment": "Check the input for a nonnull next token",
            "Choices": [
                {
                    "Variable": "$.nextToken",
                    "IsNull": false,
                    "Next": "List"
                }
            ],
            "Default": "Cleanup"
        },
        "Cleanup": {
            "Type": "Task",
            "Resource": "...",
            "End": true
        }
    },
    "TimeoutSeconds": 300
}
```

This should be easily representable when creating a StateMachine definition, such as:

```typescript
const chain = 
    listTask
    .next(processTask)
    .next(new NextableChoice(this, "NextPageCheck")
        .when(Condition.isNotNull("$.nextToken"), listTask),
    )
    .next(cleanupTask)
```

### Proposed Solution

This seems to work, but (without digging into it very much) seems like it might diverge from the existing graph construction; it also has some oddities due to private members in the State class. It also doesn't implement `afterwards()` and other methods from the existing Choice class (which may be unnecessary).  

```typescript
export class NextableChoice extends State implements IChainable, INextable {
    public readonly endStates: INextable[];
    private readonly _choices: ChoiceTransition[] = [];
    private default: IChainable;

    constructor(scope: Construct, id: string, props: ChoiceProps = {}) {
        super(scope, id, props);
        this.endStates = [this];
    }

    public when(condition: Condition, next: State): NextableChoice {
        this._choices.push({condition, next});
        return this;
    }

    public next(next: State): Chain {
        this.default = next;
        super.makeNext(next);
        return Chain.sequence(this, next);
    }

    protected renderChoices(): any {
        return {
            Choices: renderList(this._choices, renderChoice),
        };
    }

    public toStateJson(): object {
        return {
            Type: StateType.CHOICE,
            Comment: this.comment,
            ...this.renderInputOutput(),
            ...this.renderChoices(),
            Default: this.default.id,
        };
    }
}
```

### Other

* [ ] :wave: I may be able to implement this feature request
* [x] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by shivlaks** [comment]
@neukev I think this is an interesting idea and proposal. Are there any limitations in the capabilities in the current API?
I'd like to get a better understanding of the pitfalls of the current developer experience before getting into potential implementation options.

**Comment by neukev** [comment]
I was unable to generate the state definition above using the current API. Perhaps there's something I'm missing (first time using the CDK for StepFunctions), but I was unable to get around [this error](https://github.com/aws/aws-cdk/blob/c124886fbcabea166f34250cad84f7526e05b1bf/packages/%40aws-cdk/aws-stepfunctions/lib/states/state.ts#L284). Additionally, the TS syntax above seems to me to be clearer and more aligned to traditional if statements.
