### ISSUE TITLE
[aws-logs] Support for Destinations is very clunky

### ISSUE THREAD

**Issue by du291** [aws/aws-cdk#11154]
The support for cross account logging destinations deserves a bit of improvement, or at least clear documentation. I've just spent several hours figuring out how to use it!

The documentation only mentions this: 
> Consumers will hardly ever need to use this class. 

As if this was too powerful tool to play with!

The first problem is: the code that creates a `Kinesis`, a `Role` and a `CrossAccountDestination` in one go will fail with very cryptic message on AWS end:
> CREATE_FAILED	Could not deliver test message to specified destination. Check if the destination is valid. (Service: AWSLogs; Status Code: 400; Error Code: InvalidParameterException; Request ID:...

If these resources are created in subsequent runs or if they are created in two stacks (Kinesis, Role) + (Destination) then everything works. Is there a missing dependency enforcement?

The second problem is that it is not very clear how the Policy for the Destination should be constructed.
There are two sub-problems here. The first one is that principals must be supplied as `aws_iam.ArnPrincipal("<account no>") `rather than `AccountPrincipal`, otherwise deployment complains on AWS side that there must be a number, not a root account. 
This is in violation of https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_principal.html 

The second problem with the policy is that it requires the arn of the destination to be created, creating a cyclic dependency.
It must be therefore supplied in a hacky way thus:

```python
        arnString = f'arn:aws:logs:{stack.region}:{stack.account}:destination:{destination_name}'
        stmt = aws_iam.PolicyStatement(actions=['logs:PutSubscriptionFilter'],
                                       principals=[ ... ],
                                       effect=aws_iam.Effect.ALLOW,
                                       resources=[arnString])

        destination.add_to_policy(stmt)
```

The final problem is with using said destination for a log subscription. The `CrossAccountDestination` can be used as a Subscription destination, but it seems to lack a `.fromArn` method and creating the live resource will almost certainly fail. Therefore, `CfnSubscriptionFilter` must be used, where the destination arn can be placed as a string.

### Environment

  - **CLI Version      : 1.70**
  - **Framework Version: 1.70**
  - **Node.js Version: 14.11.0** 
  - **OS               : Linux**
  - **Language (Version): Python (3.8.5)** 

--- 

This is :bug: Bug Report

**Comment by shivlaks** [comment]
@du291 thanks for providing feedback. It certainly seems like we have a few improvement opportunities here to enhance the developer experience. I'm going to mark this as a feature for now and tag it as a `p1` to help prioritize it.

**Comment by mfm24** [comment]
I had this exact problem and banged my head against a wall for a couple of days.

The solution that worked for me was to put an explicit dependency on the `stream.grantWrite` Grant for the destination. I copied the code from https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-logs-destinations/lib/kinesis.ts:
```
stream = kinesis.Stream(...)
role = iam.Role(...
            assumed_by=iam.ServicePrincipal("logs.amazonaws.com"))

grant = stream.grant_write(put_logs_role)
role.grant_pass_role(role)
cross_account_destination = logs.CrossAccountDestination(
             ...
            role=role,
            target_arn=stream.stream_arn
        )
... add policy to destination
**cross_account_destination.node.add_dependency(grant)**
```

Without the last line deployments would fail with `Could not deliver test message to specified destination.` errors.

**Comment by AdeboyeML** [comment]
Thanks @mfm24!! for ☝️..works as expected

**Comment by sammi252** [comment]
Thank you! @du291  and @mfm24  for bringing this up

**Comment by floresmaya** [comment]
This is still a problem. Can we reopen?

**Comment by jaychung-aws** [comment]
This continues to be a problem. When using the addToPolicy() on a aws_logs.CrossAccountDestination L2 construct, the only way to make CloudFormation successfully deploy is passing the accountId into the `iam.ArnPrincipal()`:

```
const myAccountId: string = "111222333444"

const crossAccountDestination = new logs.CrossAccountDestination(this, 'ConstructUnderTest', {
      role: dependencies.role,
      targetArn: dependencies.kinesisStream.streamArn,
      destinationName: 'CrossAccountDestinationScenario1',
    });

crossAccountDestination.addToPolicy(
          new iam.PolicyStatement({
              effect: iam.Effect.ALLOW,
              actions: ['logs:PutSubscriptionFilter'],
              principals: [
                  new iam.ArnPrincipal(myAccountId),
              ],
              resources: [
                  `arn:aws:logs:${region}:${account}:destination:CrossAccountDestinationScenario1`,
              ],
          }),
      )
```

If we instead use `new iam.AccountRootPrincipal()` or `new iam.AccountPrincipal()`, CloudFormation fails deployment with an error that states "Invalid request provided: AWS::Logs::Destination. Principal section of policy contains ARN instead of account ID".

A sensible update would be to add a new class that implements IPrincipal called something along the line of `AcountPrincipalAsId()` that synthesizes to `"Principal\":{\"AWS\":\"219336314822\"}`.
