### ISSUE TITLE
[ecs-patterns] Allow setting additional container definition props 

### ISSUE THREAD

**Issue by ap00rv** [aws/aws-cdk#11152]
In almost all base classes in this module, an interface is defined , which is later used to add container to a task definition. 

For example, the `taskImageOptions` interface : 

https://github.com/aws/aws-cdk/blob/v1.69.0/packages/%40aws-cdk/aws-ecs-patterns/lib/base/application-load-balanced-service-base.ts#L182

This interface  is missing some important properties from the [`ContainerDefinitionOptions`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs.ContainerDefinitionOptions.html) interface, that are useful from a security perspective when defining containers using the [`addContainer()`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs.Ec2TaskDefinition.html#add-wbr-containerid-props) method. 

### Use Case

Allow customers to provide all possible properties for [`ContainerDefinition`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs.ContainerDefinition.html),  when defining constructs in this module. 

We are writing a library that extends AWS CDK and the lack of this feature prevents us from writing unit tests that make sure that output produced by CDK and our constructs is same for ecs-patterns. 

This is because in our "overriden" version of `addContainers()` method , we make some properties in  [`ContainerDefinitionOptions`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs.ContainerDefinitionOptions.html)  mandatory . However, when writing unit tests that compare output of CDK with our construct, we cannot pass these mandatory properties as part of the interfaces like `taskImageOptions` , since it does not extend `ContainerDefinitionOptions`. 

### Proposed Solution

make each of these interfaces extend [`ContainerDefinitionOptions`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs.ContainerDefinitionOptions.html) interface

```ts
export interface ApplicationLoadBalancedTaskImageOptions extends ecs.ContainerDefinitionOptions {

...
...
}

```

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by ap00rv** [comment]
update: I was able to write unit tests by using `as any` type hacks but still this feature would be nice.

**Comment by piradeepk** [comment]
@ap00rv it's not feasible to have every possible property of every construct used in the patterns as this would lead to hundreds of properties. The taskImageOptions only provides a handful of containerDefinition properties. If you have a need to create a task definition with additional properties defined, you can create a TaskDefinition and pass it into the ApplicationLoadBalanced*Service as input to the construct itself.

**Comment by ap00rv** [comment]
agree with @piradeepk 's comment. You may close this issue. Thank you.
