### ISSUE TITLE
[stepfunctions-tasks] Using EvaluateExpression causes a runtime error

### ISSUE THREAD

**Issue by marcioemiranda** [aws/aws-cdk#11151]
I am using EvaluateExpression from the @aws-cdk/aws-stepfunctions-tasks module and CDK 1.7.

The code I am trying is very similar to the one in the documentation:
https://docs.aws.amazon.com/cdk/api/latest/docs/aws-stepfunctions-tasks-readme.html#evaluate-expression

Here is the snippet of code:
```ts
const createExtraVars = new tasks.EvaluateExpression(this, 'Create Extra Vars', {
              // Note: this is a string inside a string.
              expression: '`-c environment=${$.environment} –c customer=${$.customer} -c region=${$.region} core-*`',
              runtime: lambda.Runtime.NODEJS_10_X,
              resultPath: '$.cdkExtraVars'
          });
```
The specific error is 
```console
The runtime nodejs10.x is currently not supported.
Subprocess exited with error 1
```
However, the documentation says:
```
The EvaluateExpression supports a runtime prop to specify the Lambda runtime to use to evaluate the expression. Currently, the only runtime supported is lambda.Runtime.NODEJS_10_X.
```
### Environment

  - CLI Version      : 1.16.180
  - Framework Version: 1.7
  - Node.js Version: 12.6.3
  - OS               : Mac OS 10.15.5
  - Language (Version): TypeScript (3.9.5)

**Comment by shivlaks** [comment]
any idea about this one @jogold ?

**Comment by jogold** [comment]
@marcioemiranda I cannot reproduce... what happens when you don't specify the `runtime` prop?

**Comment by shivlaks** [comment]
@jogold thanks for the sanity check because I thought maybe I was missing something. Adding the `needs-reproduction` label for now.

would you be able to provide us a little more detail on how we can create a minimal repro of this issue @marcioemiranda

**Comment by marcioemiranda** [comment]
Hi all, thanks for the reply.

This issue stopped happening after I updated CDK cli to 1.71.
