### ISSUE TITLE
[ecs-patterns] Add option to create CNAME instead of A alias 

### ISSUE THREAD

**Issue by hoegertn** [aws/aws-cdk#11165]
I propose the addition of an option to the ApplicationLoadBalanced*Service to create a CNAME DNS record instead of the A alias record.

### Use Case

I have several customers that instead of using inbound/outbound resolvers for DNS in a hybrid environment copy the Route53 zones to their local DNS server. So every team/account has an R53 HostedZone and a script copies all records to the local DNS main server.

A-Alias records are something AWS specific and they break on this copy procedure. This is why these customers would love to be able to create a CNAME instead that is pointing to the DNS name of the load balancer.

### Proposed Solution

Add option to create CNAME for the load balancer

### Other

Implemented in #10812 

* [X] :wave: I implemented this feature request

---

This is a :rocket: Feature Request

**Comment by hoegertn** [comment]
@pahud @iamhopaul123 Here is the issue describing the use case. Feel free to ask for more details if needed.

**Comment by hoegertn** [comment]
Given the issue #11123 it might even be better to have an option recordType that could be A, CNAME, or NONE.

**Comment by iamhopaul123** [comment]
Thank you @hoegertn for taking this initiative. I'll be oncall next week and will review your PR!

**Comment by hoegertn** [comment]
Great thanks. Should I add the proposed enum solution?

**Comment by iamhopaul123** [comment]
Agree! That'll be so helpful. Thank you!

**Comment by hoegertn** [comment]
done in #10812
