### ISSUE TITLE
[aws-lambda-python] Building fails: docker: Error response from daemon: invalid repository name (3873c00618823ac379a1322b6f73172bf7ef4702d79860224f37f359c8d2f5ba), cannot specify 64-byte hexadecimal strings.

### ISSUE THREAD

**Issue by CarlosDomingues** [aws/aws-cdk#11179]
When using the `aws-lambda-python` module, I get the following error during the build phase:

```shell
Bundling asset <...>/lambda-function/Code/Stage...
docker: Error response from daemon: invalid repository name (3873c00618823ac379a1322b6f73172bf7ef4702d79860224f37f359c8d2f5ba), cannot specify 64-byte hexadecimal strings.

```
### Reproduction Steps

It breaks with a simple "Hello World" lambda. I've got the same error with the PYTHON_3_7 and PYTHON_3_8 runtimes.

```
        lambda_function = aws_cdk.aws_lambda_python.PythonFunction(
            self,
            "lambda-function",
            entry=path.join(".", "lambda"),
            runtime=lambda_core.Runtime.PYTHON_3_7,
        )
```

### Environment

  - **CLI Version      : 1.70.0**
  - **Framework Version: 1.70.0**
  - **Node.js Version: v13.11.0** 
  - **OS               : Windows 10**
  - **Language (Version): Python 3.8.2** 

--- 

This is :bug: Bug Report

**Comment by jogold** [comment]
Which Docker version are you using? I think that this is #11124

**Comment by CarlosDomingues** [comment]
@jogold seems like it, I'm using `20.10.0-beta1`

**Comment by eladb** [comment]
Thanks for looping back. Closing for now
