### ISSUE TITLE
[aws-certificatemanager] get an already existing wildcard certificate

### ISSUE THREAD

**Issue by StErMi** [aws/aws-cdk#11173]
### The Question

I would like to understand how I can get the Certificate that I've already manually created for a wildcard domain `*.domain.com` to be later used to create a CloudFront Distribution.

Should this do the trick or does it try to create a new one every time?

```ts
const certificate = new DnsValidatedCertificate(this, 'SiteCertificate', {
      domainName: '.domain.com',
      hostedZone: hostedZone,
      region: 'us-east-1',
});
```

### Environment

  - **CDK CLI Version:** 1.68.0 (build a6a3f46)
  - **Module Version:** 1.69.0
  - **Node.js Version:** v12.18.1
  - **OS:** OSX Catalina
  - **Language (Version):** TypeScript (3.8.3)

**Comment by njlynch** [comment]
See https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/aws-certificatemanager/#importing.

You can import an existing certificate by its ARN.
