### ISSUE TITLE
CDK Bootstrap not adding the AdministrativeAccess permission on exec role

### ISSUE THREAD

**Issue by ltamrazov** [aws/aws-cdk#11182]
Hi,
When I bootstrap through a template produced by `cdk bootstrap --show-template`, the cloud formation execution role does not have any policies attached. This is related to https://github.com/aws/aws-cdk/issues/10043 and I got the clue about the role from there.

### Reproduction Steps
```javascript
// VPC
import * as ec2 from '@aws-cdk/aws-ec2';
import * as core from '@aws-cdk/core';

export class VPCStack extends core.Stack {
    readonly vpc: ec2.Vpc

    constructor(scope: core.App, id: string, props?: core.StackProps) {
        super(scope, id, props);

        this.vpc = new ec2.Vpc(this, 'BaseVPC', {
            cidr: '10.0.0.0/16',
            maxAzs: 2,
            subnetConfiguration: [
                {
                    name: 'isolated',
                    subnetType: ec2.SubnetType.ISOLATED,
                },
                {
                    name: 'ingress',
                    subnetType: ec2.SubnetType.PUBLIC,
                },
                {
                    name: 'egress',
                    subnetType: ec2.SubnetType.PRIVATE,
                },
            ],
        });
    }
}

// App
const app = new core.App();

const vpc = new VPCStack(app, 'AtlasVPC', { env });

app.synth();

// cdk.json
...
"@aws-cdk/core:newStyleStackSynthesis": "true"
...
```

Then run:
```bash
export CDK_NEW_BOOTSTRAP=1

# Generate template
./node_modules/.bin/cdk bootstrap --show-template > bootstrap.yaml

# Upload with cloud formation
aws cloudformation create-stack \
    --capabilities CAPABILITY_NAMED_IAM \
    --template-body bootstrap.yaml \
    --stack-name CDKToolkit
```
### What did you expect to happen?
Per https://github.com/aws/aws-cdk/issues/10043#issuecomment-682979864, I expected the execution role to have `AdministratorAccess` policy.

I'm trying to bootstrap my app with the new bootstrap settings and new style synthesis. (CDK_NEW_BOOTSTRAP=1 && "@aws-cdk/core:newStyleStackSynthesis": "true").

Ultimately I'm trying to deploy my app but I'm getting an error:
`VPC failed: Error [ValidationError]: AccessDenied. User doesn't have permission to call ssm:GetParameters`

### What actually happened?
When the bootstrap completes, I see role:
`arn:aws:iam::*******:role/cdk-hnb659fds-cfn-exec-role-********-******`

But it doesn't have any policies attached. 

### Environment
  - **CLI Version      :** 1.70
  - **Framework Version:**
  - **Node.js Version:** 14.14
  - **OS               :** Docker alpine running on osx Catalina 10.15.6
  - **Language (Version):** 3.9.7

### Other

 
Can confirm that new style bootstrap seems to be used:
```bash
/app # ./node_modules/.bin/cdk bootstrap --show-template > ./lib/bootstrap.yaml
CDK_NEW_BOOTSTRAP set, using new-style bootstrapping
```

bootstrap template produced by `cdk bootstrap --show-template > bootstrap.yaml`
https://gist.github.com/ltamrazov/a58295c2432659add3a14d232aa86c09

### UPDATE
```
/app # node_modules/.bin/cdk bootstrap
CDK_NEW_BOOTSTRAP set, using new-style bootstrapping
{ account: '*****', region: 'us-east-1' }
 ⏳  Bootstrapping environment aws://110764899327/us-east-1...
 ❌  Environment aws://******/us-east-1 failed bootstrapping: Error: Please pass '--cloudformation-execution-policies' to specify deployment permissions. Try a managed policy of the form 'arn:aws:iam::aws:policy/<PolicyName>'.
    at Bootstrapper.modernBootstrap (/app/node_modules/aws-cdk/lib/api/bootstrap/bootstrap-environment.ts:101:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at /app/node_modules/aws-cdk/lib/cdk-toolkit.ts:358:24
    at async Promise.all (index 0)
    at CdkToolkit.bootstrap (/app/node_modules/aws-cdk/lib/cdk-toolkit.ts:355:5)
    at initCommandLine (/app/node_modules/aws-cdk/bin/cdk.ts:197:9)
Please pass '--cloudformation-execution-policies' to specify deployment permissions. Try a managed policy of the form 'arn:aws:iam::aws:policy/<PolicyName>'.
```
I'm running this on an account with full admin permissions.

### UPDATE 2
After running into^ I've found https://github.com/aws/aws-cdk/issues/8571. Running 
`/app # node_modules/.bin/cdk bootstrap --cloudformation-execution-policies arn:aws:iam::aws:policy/AdministratorAccess`

worked and produced the `AdministrativeAccess` policy for the exec role. Though I'm not sure if it's intended that this flag is required? Not clear from the docs that it is, since it's only mentioned as a customization option.

However, when I tried to produce a template in a similar fashion:
`node_modules/.bin/cdk bootstrap --cloudformation-execution-policies arn:aws:iam::aws:policy/AdministratorAccess --show-template > ./lib/bootstrap.yaml`

And upload the template through aws cli the same way as before, the role was still missing.

Thank you!

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
Depending on the version of the CLI the flag `--cloudformation-execution-policies` has gone through some changes. 

* In a recent version, it defaults to AdministratorAccess if you don't specify anything.
* In a slightly older version, you'll get an error if you don't specify the flag.
* In an even older version, the template will deploy without errors but you'll get a role without policies that has no permsisions.

In all cases:

> `node_modules/.bin/cdk bootstrap --cloudformation-execution-policies arn:aws:iam::aws:policy/AdministratorAccess --show-template > ./lib/bootstrap.yaml`
>
> And upload the template through aws cli the same way as before, the role was still missing.

That is expected though. `--cloudformation-execution-policies` controls a deploy-time parameter, it will not actually change the template. If you choose to deploy by hand, you are expected to pass the parameter yourself as well.

**Comment by ltamrazov** [comment]
@rix0rrr Thank you for the reply and support!

> That is expected though. --cloudformation-execution-policies controls a deploy-time parameter, it will not actually change the template. 

This seems a bit counter intuitive since this is one of the two officially supported bootstrap options and the docs say that you should be able to just upload this template using w.e. mechanism. Especially that this mode is recommended for any larger deployments. 

> If you choose to deploy by hand, you are expected to pass the parameter yourself as well.

I see. What is the recommended way of doing this / what is the parameter that should be passed it? Is the equivalent flag on cloud formation `set-stack-policy`?
