### ISSUE TITLE
[api-gateway] provide a way to give a variable lambda name to add Method 

### ISSUE THREAD

**Issue by paulsjohnson91** [aws/aws-cdk#11190]
I currently have my lambdas set up as lambda-dev, lambda-preprod and lambda-prod

In terraform I can provide a variable uri to the lambda integration like
```
"arn:aws:apigateway:${var.region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${var.region}:${var.accountid}:function:${var.lambda_name}-$${stageVariables.stageEnv}/invocations"
```

in this way each stage will run it's own deployment version of the lambda

in aws ui this comes out as 
<img width="571" alt="Screenshot 2020-10-29 at 12 25 34" src="https://user-images.githubusercontent.com/28013436/97573618-f6918500-19e1-11eb-836b-c9cc10470340.png">

I'm using the java cdk and you have to provide LambdaIntegration.Builder.create a lambda function.

**Comment by nija-at** [comment]
duplicate issue - https://github.com/aws/aws-cdk/issues/6143
