### ISSUE TITLE
[certificatemanager] CNAME used for SSL Cert. validation is not deleted automatically.

### ISSUE THREAD

**Issue by kerbachi** [aws/aws-cdk#11201]
description of the bug:

**aws_certificatemanager.Certificate** creates and validate the SSL Certificates with '**CertificateValidation.from_dns'** but does not delete the CNAME after 'cdk destroy'

### Reproduction Steps

        hosted_zone = aws_route53.HostedZone.from_hosted_zone_attributes(
            self,
            "HostedZone",
            hosted_zone_id='1234567890ABCDEF',
            zone_name='acme.com',
        )

        acm_certificate = aws_certificatemanager.Certificate(
            self,
            id="ACMSubdomain",
            domain_name='api.acme.com',
            subject_alternative_names=["*.api.acme.com"],
            validation=aws_certificatemanager.CertificateValidation.from_dns(hosted_zone=hosted_zone)
        )

### What did you expect to happen?

"cdk destroy" should deleted the CNAME record it created in Route53 for DNS validation

### What actually happened?

The CNAME record is not deleted automatically after "cdk destroy" or after deleting the CloudFormation Template

### Environment

  - **CLI Version      : CDK 1.70.0 (build c145314)**
  - **Framework Version:**
  - **Node.js Version: v14.14.0** 
  - **OS               :MacOS Catalina 10.15.7**
  - **Language (Version): Python 3.8.6** 

### Other

--- 

This is :bug: Bug Report

**Comment by njlynch** [comment]
Related to #3333, with some of the same implications.

This is the built-in CloudFormation behavior, and I suspect it's intentional. The important point to note is that for the same AWS account and domain name, the same CNAME is generated. This means two (or more) certificates can share the same CNAME record for validation, and removing the record when one certificate is removed will impact the others' ability to be renewed.

The only option here -- besides lobbying to change the built-in CloudFormation behavior -- would be the creation of a new option (`cleanupRecords=true`) that creates a dedicated custom resource to delete the associated records. This is a healthy chunk of work for what appears to be somewhat minor benefits.

@kerbachi, can you provide any details of if/how this is negatively impacting you? Is it mostly the principle of cleanup, or is there some adverse side-effect to these records remaining I might not be aware of?

**Comment by AntonioAngelino** [comment]
> The only option here -- besides lobbying to change the built-in CloudFormation behavior -- would be the creation of a new option (cleanupRecords=true) that creates a dedicated custom resource to delete the associated records. This is a healthy chunk of work for what appears to be somewhat minor benefits.

@njlynch That seems a good solution. Any plan to implement it?

We need to clean up the AWS subaccounts we assign to our customers, therefore it's mandatory that CDK deletes all the created resources.

**Comment by coltenkrauter** [comment]
Any updates here?

**Comment by KunalKarnik** [comment]
^bump. Any updates on this issue?

**Comment by organom** [comment]
was implemented on https://github.com/aws/aws-cdk/pull/18311 in the `acm.DnsValidatedCertificate` construct by defining prop `cleanupRoute53Records: true`. 

I guess this issue can also be close

**Comment by madeline-k** [comment]
Thanks, @organom. I agree with you, this one can be closed. Please also note that `DnsValidatedCertificate` has been deprecated and replaced with [`Certificate`](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_certificatemanager.Certificate.html). If anyone still encounters a problem with this, please open a new issue.

**Comment by wv-tud** [comment]
I'm having the exact same issue when using [Certificate](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_certificatemanager.Certificate.html). Which is now forcing me to go back to using `DnsValidatedCertificate`.

**Comment by ericchuawc** [comment]
> I'm having the exact same issue when using [Certificate](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_certificatemanager.Certificate.html). Which is now forcing me to go back to using `DnsValidatedCertificate`.

I am getting the same issue with Certificate too. Any way to fix it without falling back to the old way?

**Comment by liam-careerhub** [comment]
As per this comment:
https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/837#issuecomment-1468258709

Please upvote https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/837 if this is important to you

**Comment by robzet** [comment]
aws-cloudformation project has closed their issue and aws-cdk has closed theirs. Both projects pointing to eachother but CDK users loosing out on a working destroy command when you run essential infrastructure. Sad.

**Comment by andreprawira** [comment]
@madeline-k @njlynch is `cleanupRecords=true` going to be implemented in `Certificate` class or are we supposed to go back and use the deprecated `DnsValidatedCertificate` class? Aside from the record isnt cleaned up from r53 when using `Certificate` class, do you guys know why the certificate itself isnt removed/destroyed when we executing `cdk destroy` or delete the stack that deploys the certificate?
