### ISSUE TITLE
[aws-events-targets] add a target for Cloudwatch LogGroup

### ISSUE THREAD

**Issue by jacques-** [aws/aws-cdk#11204]
Add support for a log group event target, like the rest here: https://docs.aws.amazon.com/cdk/api/latest/docs/aws-events-targets-readme.html

### Use Case

Log groups targets are super useful in debugging EventBridge based apps.

### Proposed Solution

Current workaround would be to use CFN escape hatch.

---

This is a :rocket: Feature Request

**Comment by shivlaks** [comment]
@jacques- thanks for logging the feature request. I believe it's a duplicate of #9953 which currently has a PR in review.
I'm resolving this in favour of the original.

Feel free to re-open if I've classified it incorrectly!!
