### ISSUE TITLE
When we create a dynamodb table with retain resource true, we are unable to use it again on a fresh deploy[@aws-cdk/aws-dynamodb] 

### ISSUE THREAD

**Issue by mickog** [aws/aws-cdk#11208]
When we create a dynamo table using CDK we can use this table in the stack with no issues. When we delete the stack and go to redeploy we will get an error saying the table already exists. There is no functionality i have seen documented anywhere to check if the table exists and if not then to create it. I also haven't seen any documentation on catching some sort of resource not found error and then importing based on it. 

Could you advise please as this seems like a major flaw to me, how could we have a stack where its resources plan to use this dynamo table but after a fresh deploy it seems impossible without coming up with some hacky solution?

**Comment by hoegertn** [comment]
When you remove a stack the resources are meant to be gone for good. Data resources support retaining to prevent data loss. But is not a means to redeploy your application and reuse existing resources.

Can you elaborate on your use case?

**Comment by mickog** [comment]
We created a CDK project with lambdas and and a dynamoDB table that they will use. We came to a situation where a developer wanted to delete the stack and redeploy it as they were running into some issues and wanted a fresh deploy. We still use the dynamo table when redeployed as it was created here and has all the information that has been sent from the lambdas previously. 

I noticed that if i created the table inside a try catch in my code i have no issues, i catch a generic exception here. I am wondering can you tell me where I can get the right type of exception to catch then I could have something like this in my code

```
  try {
    const dynamoTable = new Table(this, "my-table", {
      tableName: StackConfiguration.tableName,
      partitionKey: { name: "id", type: AttributeType.STRING },
    });
    return dynamoReplayTable;
 } catch (e) { // i would like to know what type of exception to catch here
 //  import the table by name instead here
    }
```

**Comment by michaelwiles** [comment]
What I'd suggest is add a parameter where you can pass in the name of the table and a flag to indicate whether it must create the table or not...

But if you want to get the behaviour you're looking for you're going to need to make an active call to aws to see if the table exists (won't be able to use cdk for this as cdk is used for generating cloudformation - the table is only created when the cloudformation template calls into AWS - not when the code is run).

So use the dynamodb client and check if the table exists and then switch to the create/reuse if it doesn't. To do this you're going to have to name it manually however as you won't know what name cdk/cloudformation has generated for your table.

**Comment by mickog** [comment]
Interesting, I think in this case we are going to move the dynamo table to a separate stack and just delete it as we are not in production yet. I would imagine this feature could be useful though sometimes developers get a stack stuck in rollback_update_failed and need to delete their stack, or need to change a stack around and it is easier to delete the stack. It makes it very awkward for them then to use the same DB on a fresh deploy.

**Comment by skinny85** [comment]
@mickog you can change the retain policy of the Table to remove it when you delete the Stack (obviously, I don't recommend this for your production environment!):

```ts
new dynamodb.Table(this, 'Table', {
  // ...
  removalPolicy: RemovalPolicy.DESTROY,
});
```

Hoe this helps!

Thanks,
Adam

**Comment by aw-huit** [comment]
> @mickog you can change the retain policy of the Table to remove it when you delete the Stack (obviously, I don't recommend this for your production environment!):
> 
> ```ts
> new dynamodb.Table(this, 'Table', {
>   // ...
>   removalPolicy: RemovalPolicy.DESTROY,
> });
> ```

This doesn't work. If the table was created with `RemovalPolicy.RETAIN`, even if you later changed it to `RemovalPolicy.DESTROY`, it will not be removed.

Furthermore, if I run `cdk deploy` after changing it to `RemovalPolicy.DESTROY`, cdk will report `no change`.

**Comment by skinny85** [comment]
@aw-huit this is a peculiarity of CloudFormation, unfortunately; it doesn't allow changes only to the attributes of a resource, you need to have a change to the properties as well. If you change the `removalPolicy` from the default to `RemovalPolicy.DESTROY`, and add some other change to the properties, doesn't matter what it is (for example, I added `readCapacity: 10` to my Table), `cdk diff` will show something like this:

```
$ cdk diff
Stack TestStack
Resources
[~] AWS::DynamoDB::Table Table TableCD117FA1 
 ├─ [~] ProvisionedThroughput
 │   └─ [~] .ReadCapacityUnits:
 │       ├─ [-] 5
 │       └─ [+] 10
 ├─ [~] DeletionPolicy
 │   ├─ [-] Retain
 │   └─ [+] Delete
 └─ [~] UpdateReplacePolicy
     ├─ [-] Retain
     └─ [+] Delete
```

And running `cdk deploy` will update the retention policy of the template - here it is from my AWS CloudFormation Console:

```
Resources:
  TableCD117FA1:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: Id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: 10
        WriteCapacityUnits: 5
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: TestStack/Table/Resource
```

Now, running `cdk destroy` will delete the Stack, and the Table alongside it.

Hope this helps!

Thanks,
Adam

**Comment by aw-huit** [comment]
Thanks Adam, I'll try it.

**Comment by jstag711** [comment]
Honestly... what? 

"property" is a synonym for "attribute". This is very unintuitive behavior by CDK and should be treated as a bug.

I am tired of AWS employees blaming issues on cloudformation. I've seen it time and time again. Cloudformation is part of AWS AFAIK, so maybe you should improve that product instead of offering all of these workarounds in github bug reports. 

It's ridiculous how many "peculiarities" us devs need to keep in our head to effectively work with CDK.

**Comment by skinny85** [comment]
That's fair @jstag711. Apologies for the bad experience.

**Comment by lancedolan** [comment]
@hoegertn 

> When you remove a stack the resources are meant to be gone for good. Data resources support retaining to prevent data loss. But is not a means to redeploy your application and reuse existing resources.

I think some CDK customers are calling that decision into question. Whatever the CDK team's intentions are when a stack is destroyed and persistent resources are left behind with data, it's perfectly reasonable that the customers would want to use them again, and re-deploy a stack around them. 

Hoping to see some customer obsession from AWS CDK here :D

**Comment by cortexcompiler** [comment]
> @hoegertn
> 
> > When you remove a stack the resources are meant to be gone for good. Data resources support retaining to prevent data loss. But is not a means to redeploy your application and reuse existing resources.
> 
> I think some CDK customers are calling that decision into question. Whatever the CDK team's intentions are when a stack is destroyed and persistent resources are left behind with data, it's perfectly reasonable that the customers would want to use them again, and re-deploy a stack around them.
> 
> Hoping to see some customer obsession from AWS CDK here :D

I agree.  This is also very similar to what CDK already does with Lambda LogGroups (via a custom resource).  In addition, it is not uncommon to have to delete and re-deploy a stack due to CloudFormation quirks, it would be nice if we did not have to manage migrating data from a retained table to a new table.
