### ISSUE TITLE
selectSubnet throws when trying to select a type that wasn't created [aws-ec2] 

### ISSUE THREAD

**Issue by pszabop** [aws/aws-cdk#11205]
When attempting to  call `ec2.vpc.selectSubnet()`, which from the name sounds like a query, if no subnets exist given the criteria an error is thrown instead of an empty set returned. 

### Reproduction Steps

    const fileSystemVpc = new ec2.Vpc(this, 'vpcForEfs', {
      natGateways: 0,
      maxAzs: 2,
    });

    // THIS ASSERTS and is a bug in ec2.vpc
    // it should just return an empty set or undefined
    const privateSubnets = fileSystemVpc.selectSubnets({
      subnetType: ec2.SubnetType.PRIVATE,
    });

### What did you expect to happen?

I expected an empty set or `undefined` returned

### What actually happened?

Error `There are no 'Private' subnet groups in this VPC. Available types: Isolated,Public` was thrown

### Environment

  - **CLI Version      :1.63
  - **Framework Version:1.63
  - **Node.js Version:12.16.1 
  - **OS               :Linux
  - **Language (Version):Typescript 3.7.5 

### Other

I have branches in my code that would like to know whether certain subnets exist or not, and right now I have to catch/throw for this exception as a work around.  The exception is hard-coded in the aws-ec2 module and doesn't follow exception
best practices so I have to use a regular expression to look for it rather than looking up an exception type in a map or object.  This makes the code fragile since you could change the text at any time.

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
Take into account for #5927

**Comment by ramesh82** [comment]
I am currently using try catch to handle the exception but it would be good to return empty or null if the subnet types/groups doesn't exist.
