### ISSUE TITLE
[cloudwatch] Allow CfnAlarms in AlarmStatusWidget

### ISSUE THREAD

**Issue by du291** [aws/aws-cdk#11214]
Currently `AlarmStatusWidget` accepts list of `IAlarm` and `CfnAlarm` does not implement this interface.
Because for example anomaly detector alarms must be currently configured via `CfnAlarm`, this disallows to add such alarm to a dashboard. The only workaround is to convert whole dashboard code to Cfn type constructs.
The widget only wants the ARN anyway, and so this seems like a needless complication.

I am not asking for support of anomaly detector alarms, I am asking for support of Cfn type constructs instead of higher level constructs, when reasonable. So that they don't create collateral pollution when used.

---

This is a :rocket: Feature Request

**Comment by NetaNir** [comment]
> I am not asking for support of anomaly detector alarms, I am asking for support of Cfn type constructs instead of higher level constructs, when reasonable. So that they don't create collateral pollution when used.

We don't expose L1 properties in L2 constructs, this is to avoid circular dependencies and general design flows. 

Can you describe the feature you are missing? Is it the ability to create Anomaly detection based alarm via the CDK?

**Comment by du291** [comment]
Yes in this case it was anomaly detectors.
I don't think this is about exposing L1 properties in L2 constructs, it is the opposite - allow to use L1 construct as a parameter for another L2 construct when it will satisty. For example, L1 alarm and L2 alarm both have ARN, and the Dashboard widget only cares about ARN...

**Comment by NetaNir** [comment]
Im not sure exactly what is the use case/API you are describing, but there is L2 representation of an ARN and other properties.  Happy to discuss a feature request

**Comment by rix0rrr** [comment]
The following should work tho:

```ts
const l1 = new CfnAlarm(...);
const l2 = Alarm.fromAlarmArn(l1.alarmArn);

// use l2 as desired
```

**Comment by du291** [comment]
> 
> 
> The following should work tho:
> 
> ```ts
> const l1 = new CfnAlarm(...);
> const l2 = Alarm.fromAlarmArn(l1.alarmArn);
> 
> // use l2 as desired
> ```

Hello, we tried this and it resulted in a complaint from cloudformation that a given alarm already exists. Maybe some trickery with id is required?

**Comment by rix0rrr** [comment]
If you do `new CfnAlarm`, that means that CloudFormation is going to create an alarm for you. If an alarm by that name already exists (for whatever reason), it's going to fail.

If the alarm already exists you can skip the `new CfnAlarm` part and just go `Alarm.fromAlarmArn('arn:aws:us-east-1:....')`.

**Comment by du291** [comment]
You're right, this trick works!
I must've messed up something previously.
Awesome, so this applies to all "L1 to L2 conversion" issues.
Thank you very much!
