### ISSUE TITLE
[aws-codepipeline] Max file size exceeded on appsync api stack w/ resolvers

### ISSUE THREAD

**Issue by danielblignaut** [aws/aws-cdk#11216]
First off, really well done on an awesome AWS development experience. I came from using Amplify which I found massively frustrating and CDK has in general, been the opposite.

I'm currently using the CodePipeline module to run a CI/CD process in a cross-account AWS setup. For the sake of this example, I have 2 AWS accounts:

1. Pipeline account (only responsible for ci/cd)
2. Pre-Dev account (stage environment for all deployment artifacts from the ci/cd)

Most of my stacks are successfully deploying and in fact if I manually deploy the stacks from my local PC to an AWS account (i.e. bypass codepipeline ci/cd and run the synth and deploy commands of the actual infrastructure stacks) the stacks deploy fine.

However, I have one stack where the S3 artifact is 2.2mb in size and I get the below screenshots. I have tried splitting up the problematic stack into multiple nested stacks but this does not help. I have also tried going to cloudformation in both my pipeline account as well as the pre-dev account however the stack in question cant be found there and I cant find any further information than the attached screenshots. Unfortunately I don't think I can split the problematic stack into multiple top level stacks (not nested stacks) as it's a single Appsync API with loads of resolvers attached...

<img width="1424" alt="Screenshot 2020-10-30 at 10 17 29" src="https://user-images.githubusercontent.com/1087177/97693691-70d11080-1a99-11eb-8291-88dbb7e73198.png">

<img width="1408" alt="Screenshot 2020-10-30 at 10 17 34" src="https://user-images.githubusercontent.com/1087177/97693706-7595c480-1a99-11eb-8368-1495ad9afff4.png">

### Reproduction Steps

I can't provide, project is too large and closed-source.

### What did you expect to happen?

I expect the stacks to all deploy succesfully

### What actually happened?

Most stacks deploy, except one, see screenshots below.

### Environment

  - **CLI Version      : ** 1.70.0 (build c145314)
  - **Framework Version: ** 1.70.0
  - **Node.js Version:** v12.14.0
  - **OS               :** Mac OS 10.14.6
  - **Language (Version):** TypeScript

### Other

--- 

This is :bug: Bug Report

**Comment by BryanPan342** [comment]
have you tried using imports?

Using the `appsync.GraphqlApi.fromGraphqlApiAttributes` function you can create a `IGraphqlApi` object that can create data sources and resolvers. This `IGraphqlApi` object can be in a separate stack.

**Comment by danielblignaut** [comment]
@BryanPan342 I have forgotten to close this issue. Main cause is that passing a graphqlApi from one stack (A) to another (B) (to create some of the resolvers in the other stack) and calling createResolver doesn't change the stack context from Stack A -> Stack B. Instead I have to manually call new appsync.Resolver and pass in the new stack's context and reference the API.

This is how AWS CDK works by design so not a bug. However with the ease of how objects can be passed around in stacks (which is great in most cases) there should maybe be a few warning sounds about using high level constructs and doing this as in this scenario
