### ISSUE TITLE
[aws-batch] expose log group on batch job definition 

### ISSUE THREAD

**Issue by mariusingjer** [aws/aws-cdk#11218]
### Proposed Solution

Expose logConfiguration from AWS::Batch::JobDefinition ContainerProperties, so you don't have to do this:

        const jobDefinition = new batch.JobDefinition(this, 'job-definition', {
            ...
        });

        const l1jobDefinition = jobDefinition.node.defaultChild as batch.CfnJobDefinition;
        l1jobDefinition.addOverride('Properties.ContainerProperties.LogConfiguration.LogDriver', 'awslogs');
        l1jobDefinition.addOverride('Properties.ContainerProperties.LogConfiguration.Options.awslogs-stream-prefix', 'my-own-log-group-name');
        l1jobDefinition.addOverride('Properties.ContainerProperties.LogConfiguration.Options.awslogs-region', '...');
        l1jobDefinition.addOverride('Properties.ContainerProperties.LogConfiguration.Options.awslogs-group.Ref', (logGroup.node.defaultChild as cdk.CfnElement).logicalId);

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by iliapolo** [comment]
For future reference: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-batch-jobdefinition-containerproperties.html#cfn-batch-jobdefinition-containerproperties-logconfiguration
