### ISSUE TITLE
[cloudformation] NestedStack doesn't have defaultChild

### ISSUE THREAD

**Issue by edisongustavo** [aws/aws-cdk#11221]
I get an `undefined` object when I access the attribute `defaultChild` from a `NestedStack`'s node.

### Reproduction Steps

I tried this code on https://play-with-cdk.com/

```
import * as cdk from '@aws-cdk/core';

import { CfnStack, NestedStack } from '@aws-cdk/aws-cloudformation';

// Keep the class name stable please
export class AppStack extends cdk.Stack {
    constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
        super(scope, id, props);
    
        // Add your code here
        var nestedStack = new NestedStack(this, 'MyNestedStack');
        var cfn_nestedStack = (nestedStack.node.defaultChild) as CfnStack;
        cfn_nestedStack.addPropertyOverride('TemplateURL', 'http://my-url.com');
    }
}
```

### What did you expect to happen?

The stack to be synthesized without errors and with the `TemplateURL` parameter of the stack overriden.

### What actually happened?

The synth crashes with this error:

```
TypeError: Cannot read property 'addPropertyOverride' of undefined
```

### Environment

I have also tried it with Python and the same error happens.

  - **CLI Version      :** 1.59.0
  - **Framework Version:** 1.59.0
  - **Node.js Version:** 
  - **OS               :** Ubuntu 18.04
  - **Language (Version):**  all

### Other

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
You are very correct. It needs to be assigned as it has a non-standard name.

**Comment by edisongustavo** [comment]
@rix0rrr is there a workaround in the mean time?

I'm confused from your answer because if I call the `children` property, then I get a list of length 0.

**Comment by edisongustavo** [comment]
I have also tried this on version 1.71 with the same result.

**Comment by edisongustavo** [comment]
I found the workaround for `NestedStack`. It is a simple matter of using the `nestedStackResource` property instead of `node.defaultChild`.

**Comment by Jacco** [comment]
@rix0rrr created a PR for this (my first)
