### ISSUE TITLE
[aws-ec2]Add Ability to tag subnets 

### ISSUE THREAD

**Issue by absolutemikex** [aws/aws-cdk#11220]
Currently you can not directly tag subnets in a vpc. While you can tag the vpc - you can not directly tag subnets because they are not constructs. So if you add the tags you want to the vpc - they will flow down from the vpc but - you can't control it.

### Use Case
When creating an Aws-Load-balancer-controller for eks, there is a requirement to tag subnets so it knows what elb to put in either subnet( internet facing or not). 

So since you cannot tag subnets - one would have to do this manually or using a cli tool. If you add the tags to the vpc level construct - it can cause issues. For instance if you add `kubernetes.io/role/internal-elb` with a value of `1` - it will flow down to the public subnets which should have a tag of `kubernetes.io/role/elb` and a value of `1`.

### Proposed Solution

Allow tagging on the subnet resource, either as a property or a method, such as `tags: []` or something along those lines. This may cause a larger discussion around tagging.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by absolutemikex** [comment]
So when deploying and EKS with a managed node group - I do see that it adds those tags automatically - but the docs only say that it will add the Cluster Tag. It does add the `internal-elb` and `elb` to the private and public subnets. However, it doesn't add the Cluster tag sometimes.

**Comment by rix0rrr** [comment]
Feels like the EKS `Cluster` construct should do this for you: https://github.com/aws/aws-cdk/blob/huijbers/stateless-reference-tokens/packages/@aws-cdk/aws-eks-legacy/lib/cluster.ts#L631

If not, you can always do something similar like the code in there to tag the subnets yourself.

You can access them using `vpc.publicSubnets` (etc)

**Comment by joehillen** [comment]
@rix0rrr I create an AwsCustomResource to do this. Do you think y'all would be interested in me opening a PR to add it to the EKS CDK module? https://github.com/aws/aws-cdk/issues/13879#issuecomment-833099652
