### ISSUE TITLE
[iam]  iam policies should allow passing policydocuments via props to constructor like managed policies do

### ISSUE THREAD

**Issue by markus7811** [aws/aws-cdk#11236]
### Use Case

While using eks a lot i often find policy documents for certain tools maintained by the creator of the tool (as an example, aws ingress controller).
I would like to use these policy documents, and don't rewrite them. There is the function, that allows creating policy documents from json - that's fine. Then it is possible to pass the document to the managedpolicy constructor - but not to inline policys.

I see no reason why this shouldn't be allowed for policies to.

### Proposed Solution

extend policy props like it's done in managed policy props and extend constructor of policy like it's done in managed policy.

https://github.com/aws/aws-cdk/blob/55e6130503d2e7346eec81d01ef37098708d0196/packages/%40aws-cdk/aws-iam/lib/managed-policy.ts#L95
https://github.com/aws/aws-cdk/blob/55e6130503d2e7346eec81d01ef37098708d0196/packages/%40aws-cdk/aws-iam/lib/managed-policy.ts#L219

both lines are not included in the normal policy.

### Other

If you agree, i will start to implement this and as far as i can see, there should be no negative side effects.

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
What would the user code look like with your proposed solution in place?

**Comment by rix0rrr** [comment]
(In favor of this functionality in general, btw, but it depends on what the solution looks like)

**Comment by markus7811** [comment]
ok, thats what i do at the moment: 

```
        const albIngressIamPolicyDocument = iam.PolicyDocument.fromJson(JSON.parse(fs.readFileSync(path.join(__dirname + "/addonAwsLoadbalancerControllerFiles", "iam_policy.json"),'utf8')))

        const albIngressPolicy = new iam.ManagedPolicy(scope, "AwsLoadbalancerControllerManagedPolicy", {
            document: albIngressIamPolicyDocument
        })

        const albIngressServiceAccount = new eks.ServiceAccount(scope, "AwsLoadbalancerControllerServiceAccount", {
            cluster: props.eksCluster,
            namespace: namespace,
            name: "aws-load-balancer-controller",
        })

        albIngressPolicy.attachToRole(albIngressServiceAccount.role)
```

and i want to use Policy instead of ManagedPolicy - but it's not supported at the moment

**Comment by markus7811** [comment]
@rix0rrr what do you think? Can i start creating the PR?

**Comment by rix0rrr** [comment]
I was asking about what the could WOULD look like with your ideal API in place, not about your current workaround.

For example, we could pick either of the following:

```ts
const policy = Policy.fromJson(this, 'MyPolicy', '/path/to/bla.json');
albIngressServiceAccount.role.addInlinePolicy(policy);

// OR

const document = PolicyDocument.fromJson('/path/to/bla.json');
const policy = new Policy(this, 'MyPolicy', {
  document: document,
});
albIngressServiceAccount.role.addInlinePolicy(policy);
```

I feel like my preference would be for the 2nd one.

**Comment by markus7811** [comment]
i also prefer the second one (as i wrote, it's like managedpolicy behaves - and i think it should be implemented the same way).

**Comment by markus7811** [comment]
I created a PR with the changes I suggest. I implemented it like your 2nd solution (and as it's implemented in ManagedPolicy).

**Comment by sathishpothuri** [comment]
The require option works fine, but the lint fails.
I have the below working example.

```
managedPolicies: [
          new ManagedPolicy(this, 'myCustomPolicy', {
            document: PolicyDocument.fromJson(JSON.parse(fs.readFileSync(`${__dirname}/../policy/mypolicy.json`, 'utf-8'))),
          }),
        ]
```
