### ISSUE TITLE
[aws-glue] glue.DataFormat.TSV is broken 

### ISSUE THREAD

**Issue by eldargab** [aws/aws-cdk#11239]
[glue.DataFormat.TSV](https://github.com/aws/aws-cdk/blob/55e6130503d2e7346eec81d01ef37098708d0196/packages/%40aws-cdk/aws-glue/lib/data-format.ts#L309) doesn't specify a valid `.tsv` format at all, due to wrong serialization library.

### Reproduction Steps

Just define any `glue.Table` with `dataFormat: DataFormat.TSV`.

### What did you expect to happen?

All columns were recognised.

### What actually happened?

All data consists of a single column.

### Environment

  - **CLI Version      : 1.70.0**
  - **Framework Version: 1.70.0**

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment]
@eldargab Could you elaborate what you mean by:

> due to wrong serialization library.

The library we use is `org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe` - which is whats specified in the [AWS Docs](https://docs.aws.amazon.com/athena/latest/ug/lazy-simple-serde.html) for TSV. 

Can you share the code you're using and some example data? 

Thanks

**Comment by eldargab** [comment]
I expect the following configuration to work:

```typescript
@def
pageTagsTable(): glue.Table {
    return new glue.Table(this, 'PageTagsTable', {
        tableName: "pagetags",
        database: this.glueDatabase(),
        dataFormat: glue.DataFormat.TSV,
        compressed: true,
        columns: [
            {
                name: 'url',
                type: glue.Schema.STRING
            },
            {
                name: 'tag',
                type: glue.Schema.INTEGER            
            }
        ]
        bucket: this.dataBucket(),
        s3Prefix: 'pagetags/'
    })
}
```

i.e. doing `select * from pagetags` with Athena results in correct content. Instead, above query returns table where
`url` column consists of entire line (url+TAB+tag) and `tag` column is empty.


>The library we use is org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe - which is whats specified in the AWS Docs for TSV.

You also need to specify `field.delim`, otherwise it doesn't recognise TAB as a field separator.

The following configuration inspired by `glue.DataFormat.CSV` works for me:

```typescript
@def
pageTagsTable(): glue.CfnTable {
    return new glue.CfnTable(this, 'PageTagsTable', {
        catalogId: this.glueDatabase().catalogId,
        databaseName: this.glueDatabase().databaseName,
        tableInput: {
            name: 'pagetags',
            parameters: {
                classification: 'csv'
            },
            storageDescriptor: {
                location: this.dataBucket().s3UrlForObject('pagetags'),
                compressed: true,
                storedAsSubDirectories: false,
                columns: [
                    {
                        name: 'url',
                        type: glue.Schema.STRING.inputString
                    },
                    {
                        name: 'tag',
                        type: glue.Schema.INTEGER.inputString
                    }
                ],
                inputFormat: glue.InputFormat.TEXT.className,
                outputFormat: glue.OutputFormat.HIVE_IGNORE_KEY_TEXT.className,
                serdeInfo: {
                    serializationLibrary: glue.SerializationLibrary.OPEN_CSV.className,
                    parameters: {
                        'separatorChar': '\t'
                    }
                }
            },
        }
    })
}
```

Note, that you have to break out of `glue.Table` construct, because DataFormat doesn't allow to specify serialization library parameters.

**Comment by iliapolo** [comment]
@eldargab

Thanks for the info. I wonder though - you mention: 

> You also need to specify field.delim, otherwise it doesn't recognise TAB as a field separator.

This implies that just using the current configuration + adding the delimeter would do the trick. No?

But then in your example you use the `glue.SerializationLibrary.OPEN_CSV` instead of `glue.SerializationLibrary.LAZY_SIMPLE` which is used by the TSV data format. 

Appreciate your input here. 

P.S If you'd like to create a PR with a suggested fix that would also be great :)

**Comment by eldargab** [comment]
@iliapolo, hello! 

I just went with `glue.SerializationLibrary.OPEN_CSV`, but `glue.SerializationLibrary.LAZY_SIMPLE` with `field.delim` should work as well and could be a better default.

**Comment by iliapolo** [comment]
Awesome, thanks @eldargab 👍

**Comment by yoshakit** [comment]
Hi, I need this stay open as it is not fixed yet: https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/aws-glue/lib/data-format.ts
