### ISSUE TITLE
[AWS-ImageBuilder] Cross stack reference while propagating subnetId from already created Vpc stack to the stack that builds AMI

### ISSUE THREAD

**Issue by AnatoliiHanziuk** [aws/aws-cdk#11249]
I'm trying to create and AMI using AWS ImageBuilder. There is a need to specify subnetId. I'm providing it from already created stack that creates vpc to a stack that builds AMI. And I receive an error 
`Stack "ami" cannot consume a cross reference from stack "NetworkStack". Cross stack references are only supported for stacks deployed to the same environment or between nested stacks and their parent stack`,

### Reproduction Steps

1. Create stack for vpc and for AMI:
```
const US_EAST_1_ENV: cdk.Environment = {
    account: ACCOUNT_ID,
    region: "us-east-1",
};
const networkStack = new NetworkStack(app, {
    stackName: "network",
    env: US_EAST_1_ENV,
});
new AmiStack(app, {
    stackName: "ami",
    env: US_EAST_1_ENV,
    subnetId: networkStack.vpc.publicSubnets[0].subnetId,
});
```
2. Try to synth CloudFormation template for AMI stack:
`cdk synth ami`.

### What did you expect to happen?

AMI is successfully created. SubnetId is propagated to AmiStack without errors.

### What actually happened?

`Stack "ami" cannot consume a cross reference from stack "NetworkStack". Cross stack references are only supported for stacks deployed to the same environment or between nested stacks and their parent stack` error is thrown.

### Environment

  - **CLI Version      : 2.0.50**
  - **Node.js Version: 15.0.1**
  - **OS               : MacOS**
  - **Language (Version): TypeScript (4.0.3) | Python (3.8.5)** 

--- 

This is :bug: Bug Report

**Comment by shivlaks** [comment]
@AnatoliiHanziuk - can you run the `synth` command with the `-v` flag to get verbose output. The error message is indicative of stacks not using the same environment.

I can see based on this snippet that they *should*. I'd love to get a minimal repro of the issue to dig further, but it doesn't look like an issue specific to `imagebuilder` at first glance.
