### ISSUE TITLE
[cli] Allow overriding of Stack Name 

### ISSUE THREAD

**Issue by damian-bisignano** [aws/aws-cdk#11247]
CLI flag that allows you to override the stack name when deploying..

ie. cdk deploy --stack-name "MyStackName"

The one problem i foresee is trying to pass in stack-name if you're deploying multiple stacks out.

### Use Case

We run CDK synth at build time, and then use that output as an artifact to then run cdk deploy to multiple environments. because  of this, we have to synth 4 "different" templates (1 per environment), rather than just the 1 that we can deploy in multiple places.

### Proposed Solution

 cdk deploy --stack-name "MyStackName" Stack1

If not passed in then it defaults to the stack name

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
Use the app code to customize stack name:

```ts
new Stack(... {
  stackName: 'xyz'
});
```

The CLI flag should be considered deprecated.
