### ISSUE TITLE
[ecs] updating FargateService affects its TaskDefinition

### ISSUE THREAD

**Issue by haandol** [aws/aws-cdk#11243]
updating FargateService should not affect to TaskDefinition.

taskdef.json contains no service related arguments.
if you want to change service attr, you should destroy and re-deploy service which is not available option in production environment.

### Reproduction Steps

```
  const fargateService = new ecs.FargateService(this, `FargateService`, {
      cluster: props.cluster,
      taskDefinition,
      desiredCount: 1,
      platformVersion: ecs.FargatePlatformVersion.LATEST,
      cloudMapOptions: {
        name: props.serviceName
      },
      deploymentController: {
        type: ecs.DeploymentControllerType.CODE_DEPLOY,
      },
      securityGroup,
      vpcSubnets: { subnetType: ec2.SubnetType.PRIVATE },
    });
    securityGroup.connections.allowFromAnyIpv4(ec2.Port.tcp(ServiceConfig.containerPort));
```

changing desiredCount (or any change on service) and cdk deploy

### What did you expect to happen?

updating service configuration

### What actually happened?

occurs below error
```
Invalid request provided: UpdateService error: Unable to update task definition on services with a CODE_DEPLOY deployment controller.
```

update same setting on AWS Console, it works fine.

### Environment

  - **CLI Version      :**1.18.157
  - **Framework Version:** 1.70
  - **Node.js Version:** 12.18.4
  - **OS               :** OSX
  - **Language (Version):**  TypeScript

### Other

--- 

This is :bug: Bug Report

**Comment by piradeepk** [comment]
@haandol would you mind showing the construct configuration before the change as well?
