### ISSUE TITLE
[aws-s3] Clarify Bucket RemovalPolicy documentation

### ISSUE THREAD

**Issue by hertzsprung** [aws/aws-cdk#11268]
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-s3.Bucket.html
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.RemovalPolicy.html

`RemovalPolicy` states that DESTROY is the default policy, but this is not true for S3 buckets (and maybe  other resource types, too?).  Could this be clarified in the docs?

`Bucket.removalPolicy?` documentation could also be made clearer, I'd suggest:

````
/**
 * Policy to apply when the bucket is removed from this stack.
 *
 * @default - RETAIN; the bucket will be retained but orphaned from the stack.
 */
readonly removalPolicy?: RemovalPolicy;
````
---

This is a 📕 documentation issue

**Comment by peterwoodworth** [comment]
The documentation for Bucket has addressed this - any other resources where this isn't the default setting should have it specified on those resources.
