### ISSUE TITLE
[cli] deploy cannot specify S3 SSE for asset upload

### ISSUE THREAD

**Issue by CaseyBurnsSv** [aws/aws-cdk#11265]
### Reproduction Steps

1. cdk bootstrap with legacy bootstrap, provide kms key id as param
2. have a SCP setup that denies s3:PutObject if s3:x-amz-server-side-encryption is missing
3. create a CDK app that provisions a lambda asset
4. execute cdk deploy
5. deploy fails and receive Access Denied error

### What did you expect to happen?
i expect CDK deploy to explicitly use the kms key i specified in the bootstrap when uploading assets.

### What actually happened?
cdk deploy does not provide SSE and the deploy fails with `Access Denied`.
It appears to be relying on the S3 default encryption instead of specifying the SSE options to the S3 put object request.

### Environment

  - **CLI Version      :** 1.71.0
  - **Framework Version:**
  - **Node.js Version:** v12.16.1
  - **OS               :** Windows 10
  - **Language (Version):** Python 3.8.5

### Other

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
> It appears to be relying on the S3 default encryption instead of specifying the SSE options to the S3 put object request.

That is correct, it does rely on default encryption. It seems convenient and logical to me to separate the upload action from the encryption action, which we can easily do in this way.

Can you tell me why you need it to work differently?

**Comment by CaseyBurnsSv** [comment]
> 
> 
> > It appears to be relying on the S3 default encryption instead of specifying the SSE options to the S3 put object request.
> 
> That is correct, it does rely on default encryption. It seems convenient and logical to me to separate the upload action from the encryption action, which we can easily do in this way.
> 
> Can you tell me why you need it to work differently?

I think it should be consistent with other AWS tooling like `sam deploy` and `aws cloudformation deploy` which allow the option of specifying the encryption config used by files uploaded to s3.

Without this option it may make CDK unusable in highly regulated financial services organizations like the one I work for.

**Comment by rix0rrr** [comment]
I probably just don't have enough domain knowledge here.

Can you explain to me why a default encryption setting on the bucket is not good enough to achieve your encryption at rest requirements?

**Comment by CaseyBurnsSv** [comment]
the issue is that we have organizational service control policies in place that Deny PutObject requests that do not explicitly specify the `x-amz-server-side-encryption` header. this is a security control that is commonly applied to enforce the use of encryption across an AWS Organization. relying on default s3 encryption does not specify the required headers.

we need the option of specifying the encryption method and key in the PutObject request sent by CDK.

for example the AWS CLI command `aws cloudformation deploy` allows us to specify this with the `--kms-key-id` parameter. and `sam deploy` provides the same parameter.

**Comment by rix0rrr** [comment]
So if I'm understanding correctly, it's not because of any *functional* reason, right? 

It's not because with default encryption you couldn't achieve the desired end result of files being encrypted with a particular KMS key.

It's because your current set of security policies misses and rejects this particular kind of configuration, even though it would be a valid setup that would achieve the desired end result.

**Comment by CaseyBurnsSv** [comment]
that is correct. this preventive security control (SCP) is on the PutObject request to S3, not on the state of the bucket itself.

**Comment by JanWe92** [comment]
I reproduced this behaviour and we have the same issue. We need the same SCP settings for the staging bucket, which we modified via the bootstrap template, but we cannot deploy the defined stack because of an "Access Denied" failure.

**Comment by hmcmanus** [comment]
I've just come across the same issue today. Any workarounds on this one that people have tried?

**Comment by openfinch** [comment]
Adding onto this, this is a strange feature to leave out considering it exists in other AWS-provided tools. This is a fairly common SCP in larger environments.

**Comment by Ettery** [comment]
We have the same problem - enterprise level requirement to specify the header(s) as a part of the approach to securing all S3 buckets.  There is no way to enforce that all S3 buckets in an account are created with SSE switched on so this approach of enforcing headers on the s3:PutObject call is [Amazon's recommended approach](https://aws.amazon.com/blogs/security/how-to-prevent-uploads-of-unencrypted-objects-to-amazon-s3/) for organisations wanting to enforce encryption at rest.

End result is that CDK is unable to deploy assets.  We'd like to move from Terraform to CDK, but this is stopping us.

**Comment by cagdas-carbon** [comment]
Are there any plans on adding an argument to `cdk deploy` to fix this?

**Comment by bartdevriendt** [comment]
We need this as well.  In our enterprise environment we require every file uploaded to S3 to be encrypted.  In terraform this is solved by defining the encryption on the backend:

```
backend "s3" {
    bucket = "..."
    region = "eu-west-1"
    key = "..."
    kms_key_id = "...."
    encrypt = true
  }

```
This sets the `x-amz-server-side-encryption` header.
