### ISSUE TITLE
[ec2]: cfn init. change to any file in the aws-ec2 module directory results in a change to integ test expectation 

### ISSUE THREAD

**Issue by NetaNir** [aws/aws-cdk#11267]
Any change to any file under the aws-ec2 module folder will change the hash value calculated by the `CloudFormationInit` class, which will result in a change to [integ.instance-init.ts](https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-ec2/test/integ.instance-init.ts) expectation file.  This is either a bug in the way the hash is calculated, or a bug in the test itself (we might be referencing a wrong path).

To reproduce, add a dummy change to any file under the aws-ec2 directory (could be a simple comment), compile and execute `yarn test`.

### Environment

  - **CLI Version      :** 1.70
  - **Framework Version:** 1.70
  - **Node.js Version:** 14
  - **OS               :** osx
  - **Language (Version):** ts 

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
I cannot reproduce this on my machine. Would love to screenshare a repro.
