### ISSUE TITLE
[aws-stepfunctions-tasks] SnsPublish: allow subject to be a TaskInput

### ISSUE THREAD

**Issue by rogerchi** [aws/aws-cdk#11279]
The SnsPublish stepfunction task allows a TaskInput for the message prop, but not the subject prop.  The subject prop should also allow a TaskInput, as "Subject.$" is valid in the step function definition.

### Use Case

Allows for setting the subject of an SNS message based on the step input

### Proposed Solution

Change the SnsPublishProps from subject?: string to subject?: sfn.TaskInput ? And then in the _renderTask() change Subject: to this.props.subject.value ?  Not sure what all would need to change.

### Other

* [x] :wave: I may be able to implement this feature request
* [x] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by shivlaks** [comment]
@rogerchi - are you trying to use state input for the subject?
why not just something like:

```ts
const task = new SnsPublish(stack, 'Publish', {
  topic,
  message: sfn.TaskInput.fromText('Publish this message'),
  subject: sfn.JsonPath.stringAt('$.subject'),
});
```

you should just be able to use state input for string values and the CDK will take care of translating `Subject` to `Subject.$` if a JsonPath is used. I don't believe we need to make this breaking change to allow the type of `TaskInput` which is intended to support both json path as strings as well as nested objects.

**Comment by rogerchi** [comment]
@shivlaks Thank you for that clarification -- it was a little confusing trying to work out how the methods map to the state machine template, since for example JsonPath.stringAt is not valid for the message prop.
