### ISSUE TITLE
[aws-elasticache] ValidationError when upgrading to 1.71.0

### ISSUE THREAD

**Issue by farzad-xgen** [aws/aws-cdk#11274]
After upgrading from 1.70 to 1.71.0, we are receiving this when we want to deploy a stack which contains an ElastiCache - Redis resource:

```
failed: ValidationError: Update of resource type is not permitted. The new template modifies resource type of the following resources: [supportredis2supportredis2cluster******, apiredis2apiredis2cluster*******]
```

### Reproduction Steps

1- Upgrafe aws-cdk to 1.71
2- Upgrade aws-cdk python modules using pip
3- Run cdk deploy

### What did you expect to happen?

We expected the code to run and since we haven't change any resource on that stack, it should just leave the stack intact and return gracefully,

### What actually happened?

We got this:

```
failed: ValidationError: Update of resource type is not permitted. The new template modifies resource type of the following resources: [supportredis2supportredis2cluster******, apiredis2apiredis2cluster*******]
```

### Environment

  - **CLI Version      : 1.71.0 (build 953bc25)
  - **Framework Version: 1.71
  - **Node.js Version:**  v10.22.1
  - **OS               : Ubuntu 18.04.5 LTS
  - **Language (Version):**  Python 3.8.0

This is :bug: Bug Report

**Comment by iliapolo** [comment]
@farzad-xgen I'm not able to reproduce the issue.

Here is the code i'm using:

```ts
export class Issue11274Stack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const securityGroup = new cache.CfnSecurityGroup(this, 'Security', {
      description: 'testing-security-group'
    })

    // The code that defines your stack goes here
    new cache.CfnCacheCluster(this, 'Cache', {
      engine: 'redis',
      cacheNodeType: 'cache.m5.large',
      numCacheNodes: 1,
      cacheSecurityGroupNames: [securityGroup.ref]
    })
  }
}
```

Upon upgrade to version `1.71.0` cdk does not show a diff:

```console
Stack Issue11274Stack
There were no differences
```

And deployment goes through successfully:

```console
Issue11274Stack: deploying...
Issue11274Stack: creating CloudFormation changeset...
[██████████████████████████████████████████████████████████] (2/2)




 ✅  Issue11274Stack

```

Can you share your code? And the output from `cdk diff` and `cdk deploy` after you upgrade?

Thanks
