### ISSUE TITLE
[transfer] SecurityGroupIds propertie missing in interface EndpointDetailsProperty

### ISSUE THREAD

**Issue by Cloudrage** [aws/aws-cdk#11275]
### Use Case

Need to configure a Security Group for a SFTP Transfer in VPC type like availabe in Cloudformation :
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-transfer-server-endpointdetails.html#cfn-transfer-server-endpointdetails-securitygroupids

### Proposed Solution

Add SecurityGroupIds prop in `AWS::Transfer::Server EndpointDetails`.

### Other

If not provided, default VPC SGR is used; and it's not the idea :)

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by iliapolo** [comment]
Should be available once the spec [20.0.0](https://github.com/aws/aws-cdk/pull/11319/) is merged.

**Comment by Cloudrage** [comment]
Hello @iliapolo,

Many thanks about that.
I've a question, maybe another request to open : 
Since few months, it's not possible to create _VPC_ENDPOINT_ type for Transfer, but _VPC_.

It'll create a VPC Endpoint on our behalf, but how to get the "**ID**" and/or "**DNS**" names of this endpoint ?
No outputs with that in Cfn/CDK : 
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-transfer-server.html#aws-resource-transfer-server-return-values

Need it to access the SFTP Server and for example, create a R53 record on it.
`s-xxxxxxxxxxxx.server.transfer.region.amazonaws.com` don't work in private VPC server.

**Comment by iliapolo** [comment]
Discussion moved to https://github.com/aws/aws-cdk/issues/11374#issuecomment-732246413
