### ISSUE TITLE
[core] What even are Aspects

### ISSUE THREAD

**Issue by richardhboyd** [aws/aws-cdk#11271]
https://docs.aws.amazon.com/cdk/latest/guide/aspects.html

The [docs](https://docs.aws.amazon.com/cdk/latest/guide/aspects.html) show people how to use aspects like this
```
myConstruct.node.applyAspect(new SomeAspect(/*...*/));
```

But when they use it they get this warning:

```
[Warning at /python] The API @aws-cdk/core.ConstructNode.applyAspect is deprecated: Use "Aspects.of(construct).add(aspect)" instead. This API will be removed in the next major release 
```

---

This is a 📕 documentation issue

**Comment by markus7811** [comment]
The links you posted show me something like:

```
Aspects.of(myConstruct).add(new SomeAspect(...));
```

maybe language specific?
![image](https://user-images.githubusercontent.com/16692560/98168472-e3534d80-1eea-11eb-918b-478636f11533.png)

**Comment by richardhboyd** [comment]
looks like it's been updated?
