### ISSUE TITLE
aws-lambda: default "handler" per language

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#1127]
We should be able to provide a default value for `handler` per language. For example, in node.js it would usually be `index.handler`.

**Comment by eladb** [comment]
@RomainMuller @rix0rrr what do you guys think about this? Could be nice to have some defaults there?

**Comment by rix0rrr** [comment]
Maybe. This is venturing slightly towards more convention-over-configuration than I'm comfortable with.

Another thing we could add is if you just give a function name, we automatically prepend `"index."`, and we could cross-reference with the type of code (for inline code it MUST be "index.", for another type of code it must be specified, for example).

**Comment by eladb** [comment]
Still relevant.

**Comment by nija-at** [comment]
This has been addressed via language specific lambda constructs, such as `aws-lambda-nodejs`, `aws-lambda-python`, etc.

Closing this issue.
