### ISSUE TITLE
[ecs] FargateService - Ignore task_definition to allow external tool to do deploys

### ISSUE THREAD

**Issue by jritsema** [aws/aws-cdk#11276]
### The Question

I would like to use cdk to deploy an initial fargate app with a running task definition, however, I would like to use an external tool to deploy new task definition on an on-going basis.  This works, however, when re-running `cdk deploy` after an external tool has updated the service to use a new task definition, cdk wants to update the service to use the original, old task definition.

So my question is, is there a way to have future (subsequent to the first) `cdk deploy`s somehow ignore [FargateService's taskDefinition](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs.FargateService.html#taskdefinition-1)? 

Terraform supports this through its [lifecycle ignore_changes](https://www.terraform.io/docs/configuration/resources.html#ignore_changes) config.

**Comment by jritsema** [comment]
Sorry, I was slightly mistaken.  Turns out that (unlike Terraform), cdk/cf aren't aware of external changes, which means that if a service's task definition is updated by an external tool, you can still use cdk to deploy changes to other resources.  However, it looks like if you change any property of the `FargateService` resource, cdk overrides, and the task definition will be replaced by the original one specified in your cdk code.

I guess the question still remains.  Could there be a way to tell cdk to ignore changes to specified properties?

**Comment by piradeepk** [comment]
@jritsema CDK doesn't natively have a way of ignoring certain constructs. However, one thing that you could try is to change your CDK stack implementation to import a task definition using the [fromFargateTaskDefinitionArn](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-ecs/lib/fargate/fargate-task-definition.ts#L64-L73) method, and then pass this into your FargateService. 

Let me know if this doesn't solve your issue!

**Comment by MrArnoldPalmer** [comment]
@jritsema as @piradeepk mentions, the only way to accomplish this is to separate out the task definition into a separate stack that doesn't get redeployed. This is a limitation of cloudformation, which basically redeploys the entire stack template every time. There isn't a way to support this with CDK currently except maybe with some custom resource, but that seems heavy handed.

**Comment by jritsema** [comment]
Thanks for the responses @piradeepk and @MrArnoldPalmer.
