### ISSUE TITLE
[stepfunctions] Support new "States.Format" intrinsic function 

### ISSUE THREAD

**Issue by michaelwiles** [aws/aws-cdk#11286]
Want to be able to make use of the new step function: States.Format [intrinsic function](https://docs.aws.amazon.com/step-functions/latest/dg/amazon-states-language-intrinsic-functions.html).

### Use Case

It enables me to concatenate strings together which I cannot now do. With this feature I can do:

States.Format('Hello {}, this is your new {}', $.Item.name, $.Item.number)

This is not possible at the moment.

### Proposed Solution

Because the input to this function is a string, theoretically it should be possible to just set a value to this use this out of the box. However, in order for the state machine engine to process the string the key needs the .$ suffix.

The way to do this with cdk is to use JsonPath but cdk code insists the JsonPaths start with $.

So I need some mechanism to add the .$ suffix to the key - and if I was to use the existing mechanism - JsonPath - then I need a means to create JsonPath where the input parameter does not start with $

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by michaelwiles** [comment]
The options for adding this are:

Another method on TaskInput called: from_formatted_text('hello {}', ['$.Item.name'])

Or to introduce a new class called States to put this (and other intrinsic functions)

So for TaskInput it would be something like this:

TaskInput.from_text(States.format('hello {}', ['$.Item.name']))

Apologies for the python accent here - I suspect the parameters for replacement would probably have to be a list instead of something more idiomatic as we'd need to support other languages.

This approach might be better as it would allow us to add the $ to the key (not sure how this happens).

**Comment by FaridNeshat-TomTom** [comment]
Is there a workaround for this? I want to use `States.Array` to wrap a value in an array.

**Comment by danielblignaut** [comment]
This seems to work for me (note this is typescript):

```typescript
new sfn.Pass(scope, 'delete-file-request', {
  parameters: {
    ['id.$']: `States.Format('File-{}#{}}__File-{}#{}', $.parameters.newModel.data.previousAttributes.bucketName, $.parameters.newModel.data.previousAttributes.filePath, $.parameters.newModel.data.previousAttributes.bucketName, $.parameters.newModel.data.previousAttributes.filePath)`
  },
  resultPath: '$.deleteFileRequest'
})
```

**Comment by jasdel** [comment]
If the CDK's JsonnTokenPath Or something similar was exported you could workaround this by specifying the `States.Format` string directly.

https://github.com/aws/aws-cdk/blob/79f45125b5c42d07d031884e3cc3043bfdc8fc07/packages/%40aws-cdk/aws-stepfunctions/lib/json-path.ts#L5

```ts
                {name: "RELAUTO_BUILD_ID",                                                 
                    // Value should be a string, but obtained as number :(                 
                    // sfn.JsonPath will not allow any non-JsonPath expression.                
                    // Must use hacked JsonPathToken instead to get the States expressions.
                    value: new JsonPathToken("States.Format('{}', $.buildId)").toString()},
```

**Comment by kennu** [comment]
I'm also having a need for `States.Array` in my Step Function, to "simulate" Map results from a Catch handler.

**Comment by michaelwiles** [comment]
For those interested there has been some movement on this: https://github.com/aws/aws-cdk/pull/15320

**Comment by yamatatsu** [comment]
This is resolved by ＃15320 :+1:

**Comment by kaizen3031593** [comment]
Thanks for the bump @yamatatsu. I'm going to close this issue although there definitely is work to be done modeling intrinsics in a CDK-native way. 

For reference, #15320 added `JsonPath.stringAt()` for which you can do something like this:

```ts
const startQueryExecutionJob = new tasks.AthenaStartQueryExecution(this, 'Athena Start Query', {
  queryString: sfn.JsonPath.stringAt("States.Format('select contacts where year={};', $.year)"),
  queryExecutionContext: {
    databaseName: 'interactions',
  },
  resultConfiguration: {
    encryptionConfiguration: {
      encryptionOption: tasks.EncryptionOption.S3_MANAGED,
    },
    outputLocation: {
      bucketName: 'mybucket',
      objectKey: 'myprefix',
    },
  },
  integrationPattern: sfn.IntegrationPattern.RUN_JOB,
});
```

This is also demonstrated in many examples in the stepfunctions [README](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-stepfunctions/README.md).

**Comment by yamatatsu** [comment]
@kaizen3031593 
Thanks for closing, and we can close also this #11286 !
