### ISSUE TITLE
[monocdk] monocdk vs @aws-cdk/**

### ISSUE THREAD

**Issue by powerful23** [aws/aws-cdk#11281]
### The Question

Hi AWS CDK team,

I am developing several cdk applications as well as some cdk libraries. I noticed that there are two choices for me: `monocdk` or `@aws-cdk/**`. It seems like the reason to use the `monocdk` is to avoid version conflicts: #10407

But the `monocdk` is really heavy, which includes all the cdk packages. I only want to use some of those packages in my applications and libraries. So can I still use the `@aws-cdk/**` packages? Will the `monocdk` completely replace the `@aws-cdk/**` packages in the future?

### Environment

  - **CDK CLI Version:** 
  - **Module Version:** 
  - **Node.js Version:** 
  - **OS:** 
  - **Language (Version):**

**Comment by NetaNir** [comment]
`monocdk` is experimental is **not** intended for use by users. In the future the aws cdk will be published as a monolith. You can read more about it in the monolithic packing [RFC](https://github.com/aws/aws-cdk-rfcs/blob/master/text/0006-monolothic-packaging.md).
