### ISSUE TITLE
[aws-eks] addAutoScalingGroupCapacity specify custom Tags, and security groups

### ISSUE THREAD

**Issue by allamand** [aws/aws-cdk#11290]
I would like to be able to specify additional tags to be created on the ASG.
they can be useful for instance for cluster-autoscaler to auto-discover my ASG

I would also like that the created by default uses the cluster Security Groups. Without it, If I created for instance 1 ASG in each AZ, the ASG are not able to communicate within each others directly. If they have same security groups that will be allowed by default.

### Use Case

Cluster-autoscaler autodiscovery feaure needs to have thoses tags on tha ASG : 

```
kubernetes.io/cluster/<cluster-name>
k8s.io/cluster-autoscaler/enabled
```

in addition we can also be able to add more tags to help to choose the right ASG to scale:

```
        k8s.io/cluster-autoscaler/node-template/label/lifecycle: Ec2Spot
        k8s.io/cluster-autoscaler/node-template/label/intent: apps
        k8s.io/cluster-autoscaler/node-template/label/aws.amazon.com/spot: "true"
        k8s.io/cluster-autoscaler/node-template/taint/spotInstance: "true:PreferNoSchedule"
```

### Proposed Solution

I would like to have a `tags`property and a `securityGroup` property in the `AutoScalingGroupCapacityOptions`object.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by iliapolo** [comment]
@allamand You can control both of these:



```ts
const autoScalingGroup = cluster.addAutoScalingGroupCapacity(...);
Tags.of(autoScalingGroup).add('key', 'value');

autoScalingGroup.addSecurityGroup(...);
```

https://docs.aws.amazon.com/cdk/latest/guide/tagging.html
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-autoscaling.AutoScalingGroup.html#addwbrsecuritywbrgroupsecuritygroup

> I would also like that the created by default uses the cluster Security Groups

What exactly do you mean by that?

**Comment by allamand** [comment]
Hi @iliapolo thanks for your response, and for the Tags option, which works.

I already uses the addSecurityGroups, but in this case, my nodes groups will have 2 SG: 
- the one created with the nodegroup
- the second I added 

And in this case, the aws load balancer controller is not working complaining that it has 2 ENI, so i would like to have the ability to create my autoscaling with only the security of the cluster with already exists.

**Comment by allamand** [comment]
@iliapolo see https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1594

**Comment by iliapolo** [comment]
@allamand I understand the problem. I think the best solution is to, like you mentioned, have the ASG use the cluster security by default, avoiding the need to attach other security groups to it.

We've recently had another issue that stems from this:

https://github.com/aws/aws-cdk/issues/10884

Will that answer your use-case as well?

**Comment by allamand** [comment]
Hi @iliapolo thanks for response. I'm pretty sure this is same problem and that if by default the nodegroup can be created with cluster SG that would solve both problems.

**Comment by iliapolo** [comment]
@allamand Cool, so i'm going to close this issue out in favor of the second [one](#10884).
