### ISSUE TITLE
[aws-ecs-patterns] Add option so that updates don't change desiredCount 

### ISSUE THREAD

**Issue by neoeinstein** [aws/aws-cdk#11299]
Have an option where the `desiredCount` is only used on stack creation, rather than also being applied with every stack update.

### Use Case

Particularly in cases where autoscaling has been attached to a Fargate or EC2 service, the desired count may not match the current scaling of the service in the environment to which changes are going to be applied. Applying the baseline `desiredCount` can result in a service severely scaling down under load, and will require time to scaling back out based on the autoscaling rules. 

### Proposed Solution

Include a property that does not cause `desiredCount` to change after applying a CF update. All options within CDK default to `1` if an attempt is made to _not_ provide an updated value.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by SoManyHs** [comment]
@neoeinstein I believe this should be fixed with https://github.com/aws/aws-cdk/pull/12223!
