### ISSUE TITLE
[ECR] - add image_tag_mutability

### ISSUE THREAD

**Issue by jritsema** [aws/aws-cdk#11295]
Perhaps I'm missing something, but it looks like there's no way to set `image_tag_mutability`?

### Use Case

We want the repo to be immutable.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by jmortlock** [comment]
https://github.com/aws/aws-cdk/pull/10557

**Comment by jritsema** [comment]
Oh sorry for the duplicate.
