### ISSUE TITLE
[ecs-service-extensions] make APP_MESH_ENVOY_SIDECAR_VERSION configurable 

### ISSUE THREAD

**Issue by dfezzie** [aws/aws-cdk#11298]
The `ecs-service-extensions` App Mesh extension has the `APP_MESH_ENVOY_SIDECAR_VERSION` as a hardcoded value: https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk-containers/ecs-service-extensions/lib/extensions/appmesh.ts#L13

It would be useful to make this a configurable value, with the default to the most recent published version. In the future this could be changed to leverage SSM: https://github.com/aws/aws-app-mesh-roadmap/issues/257

### Use Case

Customers may need to pin their deployment to a certain version, or want to take a newer version before the next CDK release

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by nathanpeck** [comment]
Agreed. Some caveats that I want to make sure there aren't weird breaking changes if folks override their version number. But I agree that should be possible, even if it becomes their responsibility if things go wrong.
