### ISSUE TITLE
Documentation code samples need review

### ISSUE THREAD

**Issue by ccurrie-amzn** [aws/aws-cdk#1130]
As an example, in [Define the AWS CDK App](https://awslabs.github.io/aws-cdk/getting-started.html#define-the-cdk-app):

```
import cdk = require('@aws-cdk/cdk');

class MyApp extends cdk.App {
    constructor(argv: string[]) {
        super(argv);
    }
}

new MyApp().run();
```

The use of `argv` is obsolete and should be removed. There are probably other examples where API changes are not reflected in the docs.

**Comment by Jerry-AWS** [comment]
This issue refers to a version of a topic that doesn't exist. The new version of the topic doesn't have this issue. This can be closed.
