### ISSUE TITLE
[cloudwatch] Support adding metrics to GraphWidget after creation 

### ISSUE THREAD

**Issue by hoegertn** [aws/aws-cdk#11305]
### Use Case

I would love to be able to add metrics to the `left` and `right` arrays after the widget object is created. This way I could create a widget object and pass it around and let other constructs add themselves to this widget.

### Proposed Solution

Create an `addMetric` method to the GraphWidget. As it is lazily evaluated in the `toJson()` method it should not be a problem to do this.

### Other

* [X] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
Sounds good.
