### ISSUE TITLE
[apigateway] Configured responseHeaders in apigateway.GatewayResponse doesn't work as documented and has no effect

### ISSUE THREAD

**Issue by dnltsk** [aws/aws-cdk#11306]
Configured `responseHeaders` in `apigateway.GatewayResponse` doesn't work as documented and have no effect.

The documentation I refer to is this one: https://docs.aws.amazon.com/cdk/api/latest/docs/aws-apigateway-readme.html#gateway-response 

### Reproduction Steps

I adopted the documented example the following way:

```typescript
    this.apiGateway.addGatewayResponse('auth-denied-response', {
      type: ResponseType.UNAUTHORIZED,
      statusCode: '403',
      templates: {
        'application/json': '{ "message": "Forbidden!" }',
      },
      responseHeaders: {
        'Access-Control-Allow-Origin': "*",
        'test-key': "test-value",
      },
    });
```

a `cdk deploy` results in the following exception:

```
Invalid mapping expression specified: Validation Result: warnings : [], errors : [Invalid mapping expression specified: test-value] (Service: AmazonApiGateway; Status Code: 400; Error Code: BadRequestException; Request ID: 697f6eb4-6c79-490f-b1e6-0ebf566bd578; Proxy: null)
```

I am able to bypass the exception by surrounding values the header values with additional single-quotes:
```
      responseHeaders: {
        'Access-Control-Allow-Origin': "'*'",
        'test-key': "'test-value'",
      },
```

Thus, the deployment is going to be successful, but the two configured `responseHeaders` doesn't appear in the response:

```bash
curl -i 'https://xxx.execute-api.eu-central-1.amazonaws.com/prod/books' \
  -X 'POST' \
  -H 'authority: xxx.execute-api.eu-central-1.amazonaws.com' \
  -H 'accept: */*' \
  -H 'access-control-request-method: POST' \
  -H 'access-control-request-headers: authorization,content-type' \
  -H 'origin: http://localhost:1234' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: cross-site' \
  -H 'sec-fetch-dest: empty' \
  -H 'referer: http://localhost:1234/' \
  -H 'accept-language: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7' \
  --compressed
HTTP/2 403
date: Thu, 05 Nov 2020 09:34:45 GMT
content-type: application/json
content-length: 27
x-amzn-requestid: abcd
x-amzn-errortype: UnauthorizedException
x-amz-apigw-id: efghi=
x-amzn-trace-id: Root=jklmn

{ "message": "Forbidden!" }%
```

### What did you expect to happen?

I want to enable CORS for error responses.

### What actually happened?

see reproduction steps above ☝️

### Environment

  - **CLI Version      : aws-cli/1.18.160 Python/3.8.5 Darwin/18.7.0 botocore/1.19.0**
  - **Framework Version: 1.70.0**
  - **Node.js Version: v13.12.0** 
  - **OS               : macOS 10.14.6**
  - **Language (Version): TypeScript (4.0.3)** 

### Other

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
What is the value of `AWS::ApiGateway::GatewayResponse` from the generated CloudFormation template?

As far as the CDK is concerned, we take the supplied headers and generate something along the lines of what is shown [here](https://docs.aws.amazon.com/apigateway/api-reference/resource/gateway-response/) (see `responseParameters` in the example at the bottom of the page).

**Comment by dnltsk** [comment]
> What is the value of `AWS::ApiGateway::GatewayResponse` from the generated CloudFormation template?

```
    "apiauthdeniedresponeF2D69496": Object {
      "Properties": Object {
        "ResponseTemplates": Object {
          "application/json": "{ \\"message\\": \\"Forbidden!\\" }",
        },
        "ResponseType": "UNAUTHORIZED",
        "RestApiId": Object {
          "Ref": "apiA9E0BAD5",
        },
        "StatusCode": "403",
      },
      "Type": "AWS::ApiGateway::GatewayResponse",
```

**Comment by dnltsk** [comment]
> What is the value of `AWS::ApiGateway::GatewayResponse` from the generated CloudFormation template?

With a configuration like this

```
      responseHeaders: {
        'Access-Control-Allow-Origin': "*",
        'test-key': "test-value",
      },
```

the result is the following:

```
    "apiauthdeniedresponeF2D69496": Object {
      "Properties": Object {
        "ResponseParameters": Object {
          "gatewayresponse.header.Access-Control-Allow-Origin": "*",
          "gatewayresponse.header.test-key": "test-value",
        },
        "ResponseTemplates": Object {
          "application/json": "{ \\"message\\": \\"Forbidden!\\" }",
        },
        "ResponseType": "UNAUTHORIZED",
        "RestApiId": Object {
          "Ref": "apiA9E0BAD5",
        },
        "StatusCode": "403",
      },
      "Type": "AWS::ApiGateway::GatewayResponse",
    },
```

The deployment of this will fail as described above with the error message

```
Invalid mapping expression specified: Validation Result: warnings : [], errors : [Invalid mapping expression specified: test-value] (Service: AmazonApiGateway; Status Code: 400; Error Code: BadRequestE
xception; Request ID: xxx; Proxy: null)
```

Single-quotes values will appear in the resulting CloudFormation config and Deployment will work.

**Comment by nija-at** [comment]
The problem might be `test-value`. It's possible that something about the string is causing this issue. Maybe the hyphen?

Can you try `testvalue` instead or some other entirely different string?

**Comment by dnltsk** [comment]
Tat doesn't change the behaviour, unfortunately. The issue seems to be independent from key or value.
```
      responseHeaders: {
        "test-key": "foo",
      },
```

results in

```
Invalid mapping expression specified: Validation Result: warnings : [], errors : [Invalid mapping expression specified: foo] (Service: AmazonApiGateway; Status Code: 400; Error Code: BadRequestExceptio
n; Request ID: 4d572768-2645-47f1-9fd0-020f3dd88e7b; Proxy: null)
```

Have you been able to reproduce the issue?

**Comment by nija-at** [comment]
Not clear why these are being rejected. You will need to consult the API Gateway documentation to see what conforms to a valid mapping expression.

Based on this documentation - https://docs.aws.amazon.com/apigateway/latest/developerguide/request-response-data-mappings.html#mapping-request-parameters - something like `responseHeaders: { id: 'x-app-id' }` should work.

If that doesn't work either, it seems you will need to reach out to the API Gateway service.

**Comment by anttispitkanen** [comment]
Still running into this problem, any updates? 👀

**Comment by tmsimont** [comment]
I'm also hitting this problem. Why was this closed?

> Not clear why these are being rejected. You will need to consult the API Gateway documentation to see what conforms to a valid mapping expression.

I'm using the exact example from the documentation here: https://docs.aws.amazon.com/cdk/api/latest/docs/aws-apigateway-readme.html#cross-origin-resource-sharing-cors

What documentation is missing from the existing documentation?

Removal of `test-key` does not fix the problem.

**Comment by anttispitkanen** [comment]
@tmsimont if it helps, here's how I got it working
```typescript
/**
 * Gateway response
 *
 * IF the lambda authorizer returns fail, especially when the token has expired,
 * there might by default be a CORS error instead of a 403 Forbidden, preventing
 * the frontends from doing automatic redirect to login.
 *
 * To avoid that we configure a custom gateway response with CORS enabled for all
 * origins.
 */
apiGateway.addGatewayResponse('GatewayResponse', {
  type: ResponseType.ACCESS_DENIED,
  statusCode: '403',
  responseHeaders: {
    // Note the quoting around the header value:
    // https://blog.ilearnaws.com/2020/05/27/error-unable-to-put-integration-response-on-options-for-resource-at-path/
    'Access-Control-Allow-Origin': "'*'", // <--- SEE THIS LINE
  },
});
```

**Comment by tmsimont** [comment]
Thanks, that helps. It seems that value is a special format called a "mapping expression" that is documented here: https://docs.aws.amazon.com/apigateway/latest/developerguide/request-response-data-mappings.html

It's super annoying that they fail to mention that, and also provide an invalid example on this document: https://docs.aws.amazon.com/cdk/api/latest/docs/aws-apigateway-readme.html#gateway-response

**Comment by peterfranzen** [comment]
This needs to be updated in the documentation.  I just had to struggle for a full afternoon with this before finding this thread.
