### ISSUE TITLE
[pipelines] Stage can't support more than 25 stacks

### ISSUE THREAD

**Issue by JFox** [aws/aws-cdk#11315]
When attempting to deploy a pipeline with more than 25 stacks, the deploy fails due to the stage having more than 50 actions.

### Reproduction Steps

Deploy a pipeline with > 25 stacks.

### What did you expect to happen?

Deployment to succeed

### What actually happened?

On deploy, the following error is hit:

`Pipeline stage '<StageName>' has too many actions. There can only be up to 50 actions in a pipeline stage (Service: AWSCodePipeline; Status Code: 400; Error Code: InvalidStageDeclarationException; Request ID: xxx)`

### Environment

  - **CLI Version      :** 1.71.0
  - **Framework Version:** 1.71.0
  - **Node.js Version:** 13.8.0
  - **OS               :** MacOS
  - **Language (Version):** TypeScript (3.9.7)

### Other

Tried to work it around by referencing cross-stage but got `dependency cannot cross stage boundaries` error.

Similar issue, but for assets: https://github.com/aws/aws-cdk/issues/9353

--- 

This is :bug: Bug Report

**Comment by victorlevasseur** [comment]
I really wonder if this can be fixed as it requires extra stages and stages cannot share cross references.

**Comment by victorlevasseur** [comment]
I'm currently trying to solve this issue. I'll soon create a merge request if I'm able to achieve the correct result.

**Comment by rix0rrr** [comment]
Treated as part of #10872.
