### ISSUE TITLE
[codepipeline] selectively add webhooks to a specific source

### ISSUE THREAD

**Issue by ipeterpeterson** [aws/aws-cdk#11325]
### The Question
CDK adds a webhook to every source repo when using **GitHub** as a source using the new `CodeStarSourceConnection`.

I have 3 GitHub repositories as my sources and I would like to selectively add webhooks to a specific source. However when using the new `CodeStarSourceConnection` the pipeline is triggered whenever any of the repos using the new connection is updated.

```py
qa_source_action = {
        "name": "QASource",
        "actionTypeId": {
            "category": "Source",
            "owner": "AWS",
            "version": "1",
            "provider": "CodeStarSourceConnection"
        },
        "configuration": {
            "ConnectionArn": arn:aws:codestar-connections:us-east-1:999999999999:connection/xxx,
            "FullRepositoryId": "organization/qa-checks",
            "BranchName": "master",
            "OutputArtifactFormat": "CODE_ZIP"
        },
        "outputArtifacts": [{
            "name": "QAChecks"
        }],
        "runOrder": 1
    }
```

While the resulting CloudFormation template does not have a webhook resource for a source using CodeStarSourceConnection, I believe it has something to do with how AWS handles the new connection or there is a setting that is undocumented.

### Environment

  - **CDK CLI Version:** 1.67.0
  - **Module Version:** SAME
  - **Node.js Version:** 14.8.0
  - **OS:** macOS 10.15.7
  - **Language (Version):** Python (3.8.5)

**Comment by skinny85** [comment]
Hi @ipeterpeterson ,

the webhook is actually not created by the CDK, but actually  by the CodeStar Connection resource. There's not really anything we can do here.

Thanks,
Adam
