### ISSUE TITLE
[apigateway] Include additional information when Proxy flag is enabled for LambdaIntegration

### ISSUE THREAD

**Issue by cdugga** [aws/aws-cdk#11337]
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-apigateway.LambdaIntegrationOptions.html

It would be helpful here to expand marginally on the impact of enabling the Proxy flag. The current API description implies enabling the Proxy flag will circumvent the need for an Integration Response however it does not point to the fact that it is then the responsibility of the backend service to return any potentially required CORS headers such as Access-Control-Allow-Origin and Access-Control-Allow-Headers. 

The current description 
proxy? | boolean | Use proxy integration or normal (request/response mapping) integration.
-- | -- | --

could be expanded to include a reference to the developer guide for setting up a proxy integration 

proxy? | boolean | Use proxy integration or normal (request/response mapping) integration. See [Lambda Proxy Integration Developer Guide](https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html#api-gateway-simple-proxy-for-lambda-output-format ) 
-- | -- | --

Failing to return Cors headers from backend Lambda services appears to be a very common omission when using Lambda Proxy Integration and this may help ameliorate this 

This is a 📕 documentation issue

**Comment by nija-at** [comment]
Thanks for filing this @cdugga. 

Are you able to submit a PR to this effect? The change needs to be done here - https://github.com/aws/aws-cdk/blob/07c3ac8630762d8979b9bb55c62829eee88500de/packages/%40aws-cdk/aws-apigateway/lib/integrations/lambda.ts#L9-L13

**Comment by cdugga** [comment]
I've opened [PR 11400](https://github.com/aws/aws-cdk/pull/11400) @nija-at

**Comment by yamatatsu** [comment]
https://github.com/aws/aws-cdk/pull/11400 is merged aleady, so we can close this issus, can't we?
