### ISSUE TITLE
[apigateway] How to escape double quotes from "requestTemplates" prop

### ISSUE THREAD

**Issue by Cloudrage** [aws/aws-cdk#11335]
## :question: General Issue
Sorry for the question, probably inapropriate but I don't have found a solution to escape the double quote here :
![image](https://user-images.githubusercontent.com/30436750/98352963-fcf5b180-201e-11eb-8580-677b89b190d1.png)

### The Question
How to do the job ?
I've tryied to escape double quotes like that : `\"`
But the Stringify escape them again and I don't have the expected value in the end : 
`\"password\":\"$util.escapeJavaScript($input.params('Password')).replaceAll(\\\"\\\\'\\\",\\\"'\\\")\"`

It result with : 
`"password":"$util.escapeJavaScript($input.params('Password')).replaceAll(\"\\'\",\"'\")"`

Any ideas will be appreciated ^^

**Comment by Cloudrage** [comment]
Made with a workaround :
`password: "$util.escapeJavaScript($input.params('Password')).replaceAll(\"\\'\",\"'\")".replace(/\"/g, '"'),`

**Comment by monkeytronics** [comment]
Hey all. Solved by Emilio: https://stackoverflow.com/a/68438129/9115897 -

    `$util.escapeJavaScript(data).replaceAll("\\'","'")`

or

    String.raw(`$util.escapeJavaScript(data).replaceAll("\\'","'")`)
