### ISSUE TITLE
[pipelines] extra room for actions in cdkStage addApplication()

### ISSUE THREAD

**Issue by adriantaut** [aws/aws-cdk#11333]
Reserve room for more actions between the prepare and execute actions added within `addApplication()` method in the CdkStage class. 

### Use Case

Currently there is no way of reordering stages/actions ( https://github.com/aws/aws-cdk/issues/10127 ) once they are created. Getting to the `Prepare` and `Execute` change set actions while adding an application stage, we identified a use case within our company that needs one or more intermediary actions before actually executing the change set. To be more specific, once the prepared change set is reviewed and manually approved, we have to reach out our ticketing tool for creating a change request before actual deployment to production. All the above must run sequentially, as the change request needs the user email that approved the deploy.

### Proposed Solution

To resolve the problem, I would suggest extending the `AddStageOptions` interface with an optional property representing the number of intermediary actions you need room for, thus the `executeRunOrder` will get increased with this optional property. I've already tested it roughly, and it works like expected.

### Raw implementation

```diff
--- a/packages/@aws-cdk/pipelines/lib/stage.ts
+++ b/packages/@aws-cdk/pipelines/lib/stage.ts
@@ -76,6 +76,7 @@ export class CdkStage extends CoreConstruct {
    */
   public addApplication(appStage: Stage, options: AddStageOptions = {}) {
     const asm = appStage.synth();
+    const roomForIntermediaryActions = options.roomForIntermediaryActions ?? 0;

     if (asm.stacks.length === 0) {
       // If we don't check here, a more puzzling "stage contains no actions"
@@ -88,8 +89,8 @@ export class CdkStage extends CoreConstruct {
       stack => stack.dependencies.map(d => d.id));

     for (const stacks of sortedTranches) {
-      const runOrder = this.nextSequentialRunOrder(2); // We need 2 actions
-      let executeRunOrder = runOrder + 1;
+      const runOrder = this.nextSequentialRunOrder(roomForIntermediaryActions + 2); // We need 2 actions for stack actions
+      let executeRunOrder = runOrder + roomForIntermediaryActions + 1;

       // If we need to insert a manual approval action, then what's the executeRunOrder
       // now is where we add a manual approval step, and we allocate 1 more runOrder
@@ -371,6 +372,15 @@ export interface AddStageOptions {
    * @default false
    */
   readonly manualApprovals?: boolean;
+  /**
+   * Add room for intermediary actions
+   *
+   * This increases the executeRunOrder of the execute change set action with
+   * the value passed.
+   *
+   * @default 0
+   */
+  readonly roomForIntermediaryActions?: number;
 }
```

* [x] :wave: I am able to implement this feature request if it's welcome.

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
Does `manualApprovals: true` help you at all? 

https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_pipelines.AddStageOptions.html#manualapprovalsspan-classapi-icon-api-icon-experimental-titlethis-api-element-is-experimental-it-may-change-without-noticespan

I would not mind this being added.

**Comment by adriantaut** [comment]
@rix0rrr unfortunately not, we are using the `manualApprovals` option also, but the extra action we need both consumes the approver email and must run before the ExecuteChangeSet, thus the need for sequential actions.

**Comment by adriantaut** [comment]
@rix0rrr I've implemented the above in https://github.com/aws/aws-cdk/pull/11376, a review would be highly appreciated! Thanks a lot 💯
