### ISSUE TITLE
[dynamodb] Global table with provisioning capacity not supported ?

### ISSUE THREAD

**Issue by debojit777** [aws/aws-cdk#11346]
## :question: General Issue

I am getting below error when I try to setup provisioning for my dynamodb global table in CDK (v 1.45)

```
Error: The `PAY_PER_REQUEST` billing mode must be used when specifying `replicationRegions`
```

I can setup the provisioned capacity on the ddb aws console but why not via CDK ? 

Even the link here : https://docs.aws.amazon.com/cdk/api/latest/typescript/api/aws-dynamodb/tableoptions.html#aws_dynamodb_TableOptions_billingMode says that provisioning cannot be enabled for global tables.

### Environment

  - **CDK CLI Version:** 1.45.0
  - **Module Version:** 1.45.0
  - **Node.js Version:** v15.0.1
  - **OS:** OSX
  - **Language:** typescript

**Comment by debojit777** [comment]
Any update on this ?

**Comment by jonathan-kosgei** [comment]
@skinny85 I have the same issue.

**Comment by skinny85** [comment]
@debojit777 are you working on this issue perhaps?

**Comment by pathik9** [comment]
Facing the same issue

**Comment by skinny85** [comment]
I just tried creating a global DynamoDB Table with billing mode set to `PROVISIONED`, and got the following error from the DynamoDB service:

```
Failed to create resource. Table write capacity should either be Pay-Per-Request or AutoScaled.
```

It seems like the condition that is in the construct is still correct...?

**Comment by jarruda** [comment]
This appears to be as-designed:
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/V2globaltables_reqs_bestpractices.html

> When using the latest version of global tables, you must either use on-demand capacity or enable autoscaling on the table.
> ...
> When you use the provisioned capacity mode, you manage your auto scaling policy with UpdateTableReplicaAutoScaling. Minimum and maximum throughput and target utilization are established globally for the table and passed to all replicas of the table.

**Comment by skinny85** [comment]
Interesting... https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_UpdateTableReplicaAutoScaling.html

**Comment by skinny85** [comment]
I figured it out!

**Comment by debojit777** [comment]
My cdk version is 1.45. Hod do I use this fix without doing a overall CDK bump ?

**Comment by skinny85** [comment]
I think [escape hatches](https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html) is your best bet @debojit777 .
