### ISSUE TITLE
[@aws-cdk/cloudformation-include] CfnInclude not working with MonoCDK

### ISSUE THREAD

**Issue by CaerusKaru** [aws/aws-cdk#11342]
### Reproduction Steps

1. Create a CDK app using MonoCDK
1. Download an existing CFN template as JSON (not YAML)
1. Wire up the app to use `CfnInclude` construct
1. Synthesize the template

### What did you expect to happen?

To have `CfnInclude` work as expected with no errors

### What actually happened?

```
Using cdk out from cdk.json: /Users/main/test/build/cdk.out
internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module '@aws-cdk/aws-codecommit'
Require stack:
- /Users/main/test/node_modules/monocdk/lib/cloudformation-include/lib/cfn-include.js
- /Users/main/test/node_modules/monocdk/lib/cloudformation-include/lib/index.js
- /Users/main/test/node_modules/monocdk/lib/cloudformation-include/index.js
- /Users/main/test/node_modules/monocdk/lib/index.js
- /Users/main/test/dist/lib/app.js
```

### Environment

  - **CDK CLI Version  :** 1.71.0
  - **Framework Version:** 1.69.0
  - **Node.js Version:** 12.18.1
  - **OS               :** macOS
  - **Language (Version):** TypeScript (4.0.3) 

### Other

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hi @CaerusKaru ,

thanks for opening the issue. Unfortunately, we don't really support monoCDK to be used currently, hence it's no surprise that cloudformation-include doesn't work with it. Right now, your only recurse is to switch to using the `@aws-cdk/cloudformation-include` module.

Thanks,
Adam

**Comment by BenChaimberg** [comment]
If you want to hack around this problem, you can change all references of `@aws-cdk` to `monocdk` in `node_modules/monocdk/lib/cloudformation-include/cfn-types-2-classes.json`.
