### ISSUE TITLE
[aws-ecs] Fargate launch type now supports secretmanager parameter names

### ISSUE THREAD

**Issue by fongie** [aws/aws-cdk#11341]
As mentioned in [this issue](https://github.com/aws/containers-roadmap/issues/385) and [here](https://aws.amazon.com/about-aws/whats-new/2020/11/aws-fargate-for-amazon-ecs-launches-features-focused-on-configuration-and-metrics/) AWS ECS Fargate now supports fetching a specific json field in a secret. 

The CDK ecs module supports specifying a field in `Secret.fromSecretsManager(secret, field?)` method, but if you specify a field when using the Fargate launch type then you currently get an error message that this is not supported `Cannot specify secret JSON field for a task using the FARGATE launch type: 'SECRET' in container 'container'`. 

It would be really nice if this new ECS feature could make it into CDK quickly!

### Use Case

I want to keep one secretsmanager secret with f.e 'my-container-env' and use that secret with various fields to specify my container environment for fargate tasks, instead of having to use ssm or one secret for each value.

### Proposed Solution

Not sure. The resources I found dont say whether this is supported in CloudFormation too right away. If it is, maybe you could just start allowing this 'field' to be present in fargate tasks too!

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by jogold** [comment]
Until #11348 is released, you can unblock yourself like this:

```ts
// `secret` is your secret
// `specificField` is the field to be extracted
taskDefinition.addContainer('MyContainer', {
  // ... other props ...
  secrets: {
    SECRET_SPECIFIC_FIELD: {
      arn: `${secret.secretArn}:specificField::`,
      grantRead: grantee => secret.grantRead(grantee),
    },
  },
});
```
