### ISSUE TITLE
[aws-lambda] vpc option to custom resource lambdas

### ISSUE THREAD

**Issue by eruvanos** [aws/aws-cdk#11340]
Add the possibility to add a vpc to a created lambda function.

### Use Case

The environment we are using enforces all Lambdas to be in a VPC. CDK creates Lambdas behind the scenes, which are not placed in a VPC. 

So we thought about iterating through the stack with Aspects, adding the missing VPC to all Lambda functions.

```
@jsii.implements(core.IAspect)
class PlaceLambdaIntoVPC:
    def visit(self, node):
        print(type(node))
        if isinstance(node, _lambda.Function):
            node.add_vpc(vpc=stack.vpc, security_groups=[stack.sg])

Aspects.of(stack).add(PlaceLambdaIntoVPC())
```

### Proposed Solution

An option would be a method like:

def add_vpc(self, vpc: IVpc, subnets: aws_ec2.SubnetSelection, security_groups: List[aws_cdk.aws_ec2.ISecurityGroup]) -> None

### Other

Another option would be to provide a cli option which automatically puts every 'behind the scenes' Lambda into a given VPC.

**Comment by rix0rrr** [comment]
What kinda of Lambdas do you mean? Custom resources, or other ones?

**Comment by eruvanos** [comment]
Hi,
For example lambdas which are created in aws-certificatemanage/dns-validated-certificate.

https://github.com/aws/aws-cdk/blob/a8cef9a7bae3fe0d0108b9cd66d201e49e2bb1f5/packages/%40aws-cdk/aws-certificatemanager/lib/dns-validated-certificate.ts#L77

**Comment by eruvanos** [comment]
An alternative way, how some of the teams are doing is looks like the following code, but it feels not as easy as it could be.


```
import * as cdk from '@aws-cdk/core';
import * as ec2 from '@aws-cdk/aws-ec2';
import * as lambda from '@aws-cdk/aws-lambda';

interface VpcConfig {
	readonly SecurityGroupIds: string[];
	readonly SubnetIds: string[];
}

export class LambdaVPCAspect implements cdk.IAspect {
	private readonly vpc: ec2.Vpc;

    constructor(vpc: ec2.Vpc) {
        this.vpc = vpc;
    }

    public visit(node: cdk.IConstruct): void {
        if (node instanceof lambda.CfnFunction) {
            if (!node.vpcConfig) {
                node.addPropertyOverride('VpcConfig', this.getConfig(node, this.vpc));
            }
        }
    }

    private getConfig(node: cdk.Construct, vpc: ec2.Vpc): VpcConfig {
        let securityGroups: ec2.ISecurityGroup[];

        const securityGroup = new ec2.SecurityGroup(node, 'SecurityGroup', {
            vpc: vpc,
        });

        securityGroups = [securityGroup];
        const { subnetIds } = vpc.selectSubnets();

        return {
            SecurityGroupIds: securityGroups.map(sg => sg.securityGroupId),
            SubnetIds: subnetIds,
        };
    }
}
```
