### ISSUE TITLE
[cdk-pipelines] CodeBuild fails when deploying pipeline stack from Windows

### ISSUE THREAD

**Issue by awohletz** [aws/aws-cdk#11359]
I followed this [CdkPipelines tutorial](https://aws.amazon.com/blogs/developer/cdk-pipelines-continuous-delivery-for-aws-cdk-applications/) exactly, except that I used the subdirectory option of the synth action, because I have my CDK code in a monorepo:

```
synthAction: SimpleSynthAction.standardNpmSynth({
    subdirectory: "packages/infrastructure",
    cloudAssemblyArtifact,
    sourceArtifact,
    buildCommand: "npm run build"
}),
```

When I followed the tutorial's command to deploy my pipeline stack, the CodeBuild step failed after deploy. I figured out that when run on Windows, the pipeline deployment command creates backward slashes for the base-directory in the generated buildSpec. When I run the pipeline deploy on Linux, it creates forward slashes, and then the CodeBuild succeeds. Thus, it appears that CdkPipelines does not properly handle cross-platform path separators.

### Reproduction Steps

Follow the CdkPipelines tutorial, use the subdirectory option, and run `npx cdk deploy \
  --profile account1-profile \
  CdkpipelinesDemoPipelineStack` from Windows PowerShell.

### What did you expect to happen?

I expected the pipeline to create and all steps succeed, as in the screenshot in the tutorial. 

### What actually happened?

The CodeBuild step failed. 

### Environment

  - **CDK CLI Version  :** 1.72.0
  - **Framework Version:** 1.72.0
  - **Node.js Version:** 12.5.0
  - **OS               :** Windows 10
  - **Language (Version):** TypeScript ~3.9.7

### Other
On Windows, the outputted PipelineStack.template.json has:
```
"Source": {
          "BuildSpec": "{\n  \"version\": \"0.2\",\n  \"phases\": {\n    \"pre_build\": {\n      \"commands\": [\n        \"cd packages/infrastructure\",\n        \"npm ci\"\n      ]\n    },\n    \"build\": {\n      \"commands\": [\n        \"npm run build\",\n        \"npx cdk synth\"\n      ]\n    }\n  },\n  \"artifacts\": {\n    \"base-directory\": \"packages\\\\infrastructure\\\\cdk.out\",\n    \"files\": \"**/*\"\n  }\n}",
          "Type": "CODEPIPELINE"
        },
```
On Linux:
```
"Source": {
          "BuildSpec": "{\n  \"version\": \"0.2\",\n  \"phases\": {\n    \"pre_build\": {\n      \"commands\": [\n        \"cd packages/infrastructure\",\n        \"npm ci\"\n      ]\n    },\n    \"build\": {\n      \"commands\": [\n        \"npm run build\",\n        \"npx cdk synth\"\n      ]\n    }\n  },\n  \"artifacts\": {\n    \"base-directory\": \"packages/infrastructure/cdk.out\",\n    \"files\": \"**/*\"\n  }\n}",
          "Type": "CODEPIPELINE"
        },
```

When deployed via Windows, the CodeBuild logs show:

```

[Container] 2020/11/08 17:30:21 Entering phase POST_BUILD
--
835 | [Container] 2020/11/08 17:30:21 Phase complete: POST_BUILD State: SUCCEEDED
836 | [Container] 2020/11/08 17:30:21 Phase context status code:  Message:
837 | [Container] 2020/11/08 17:30:21 Expanding base directory path: packages\infrastructure\cdk.out
838 | [Container] 2020/11/08 17:30:21 Assembling file list
839 | [Container] 2020/11/08 17:30:21 Expanding packages\infrastructure
840 | [Container] 2020/11/08 17:30:21 Skipping invalid file path packages\infrastructure

```

When deployed via Linux, the CodeBuild logs show:
```
[Container] 2020/11/08 17:59:33 Entering phase POST_BUILD
--
572 | [Container] 2020/11/08 17:59:33 Phase complete: POST_BUILD State: SUCCEEDED
573 | [Container] 2020/11/08 17:59:33 Phase context status code:  Message:
574 | [Container] 2020/11/08 17:59:33 Expanding base directory path: packages/infrastructure/cdk.out
575 | [Container] 2020/11/08 17:59:33 Assembling file list
576 | [Container] 2020/11/08 17:59:33 Expanding packages/infrastructure/cdk.out
577 | [Container] 2020/11/08 17:59:33 Expanding file paths for base directory packages/infrastructure/cdk.out
578 | [Container] 2020/11/08 17:59:33 Assembling file list
579 | [Container] 2020/11/08 17:59:33 Expanding **/*
580 | [Container] 2020/11/08 17:59:33 Found 5 file(s)
```

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
Whoopsiedoodle! You are right!
