### ISSUE TITLE
[cdk-pipelines] Cannot add codepipeline action within an Application Stage

### ISSUE THREAD

**Issue by BenTScott** [aws/aws-cdk#11360]
### Adding an action within an Application Stage
I am trying to add an application stage to my pipeline with everything required for deploying a React SPA (S3 bucket, cloudfront, API). I have everything contained within a stage. The issue I'm having is this requires an S3 deployment action. I want to keep things encapsulated and make it simple to deploy to multiple environments but I cannot find a way of having the S3 bucket within a stage and also using it in a deploy action without the following `dependency cannot cross stage boundaries`.

### Environment

  - **CDK CLI Version:** 1.70
  - **Module Version:** 1.70
  - **Node.js Version:** v15.1.0
  - **OS:** Ubuntu
  - **Language (Version):** TypeScript (3.8.3)

**Comment by rix0rrr** [comment]
That's true. It's up to you to make sure the stages are deployed in the right order, and you're going to have to find a different way to move the bucket name across domains.

Either create an SSM parameter with the bucket name, or create a CloudFormation `Export` and construct the `{ Fn::ImportValue}` yourself.
