### ISSUE TITLE
[codebuild] support LogsConfig and QueuedTimeoutInMinutes in L2 construct

### ISSUE THREAD

**Issue by zxkane** [aws/aws-cdk#11364]
The [CodeBuild L2 construct](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-codebuild.Project.html) does not support [LogsConfig](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codebuild-project.html#cfn-codebuild-project-logsconfig) and [QueuedTimeoutInMinutes](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codebuild-project.html#cfn-codebuild-project-queuedtimeoutinminutes).

### Use Case

Specify the `LogsConfig` and `QueuedTimeoutInMinutes` properties via L2 CodeBuild construct. Also those properties should be override when starting build via Step Functions integration. See https://github.com/aws/aws-cdk/pull/10356 for detail.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by zxkane** [comment]
#11444 might implement LogsConfig

**Comment by skinny85** [comment]
> #11444 might implement LogsConfig

Yep, only `QueuedTimeoutInMinutes` left. Should be easy by adding a `queuedTimeout?: cdk.Duration` property to [`CommonProjectProps`](https://github.com/aws/aws-cdk/blob/45677cac1b8a13d272c8e7ecea74b2beba590df7/packages/%40aws-cdk/aws-codebuild/lib/project.ts#L400-L549).
