### ISSUE TITLE
[aws-applicationautoscaling] Add 'kafka' to ServiceNamespace 

### ISSUE THREAD

**Issue by iwt-janbrauer** [aws/aws-cdk#11366]
To use [Autoscaling storage for MSK](https://docs.aws.amazon.com/msk/latest/developerguide/msk-autoexpand.html) with CDK the `ServiceNamespace` enum needs the additional field [`KAFKA`](https://docs.aws.amazon.com/autoscaling/application/APIReference/API_RegisterScalableTarget.html#autoscaling-RegisterScalableTarget-request-ServiceNamespace).

### Use Case

Because I want to use CDK.

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by NetaNir** [comment]
@iwt-janbrauer would you want ton submit a PR?

**Comment by bracki** [comment]
@NetaNir https://github.com/aws/aws-cdk/pull/11394
