### ISSUE TITLE
[transfer] How to get Endpoint ID created by Transfer Server on our behalf

### ISSUE THREAD

**Issue by Cloudrage** [aws/aws-cdk#11374]
### Use Case

Since few months, it's not possible to create VPC_ENDPOINT type for Transfer, but VPC.

It'll create a VPC Endpoint on our behalf, but how to get the "ID" and/or "DNS" names of this endpoint ?
No outputs with that in Cfn/CDK :
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-transfer-server.html#aws-resource-transfer-server-return-values

### Proposed Solution

Add Cloudformation Return values and/or CDK propertie with the ID and DNS Names of the Endpoint created by Transfer.

### Other

Need it to access the SFTP Server and for example, create a R53 record on it.
`s-xxxxxxxxxxxx.server.transfer.region.amazonaws.com` don't work in private VPC server.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by iliapolo** [comment]
@Cloudrage Can you clarify what you mean by *ID* and *DNS* of the endpoint? is the id not the `ServerId` return value mentioned in the docs?

**Comment by Cloudrage** [comment]
Hello @iliapolo ,

To be able to create a R53 Record after creating the Transfer Server, I need t**he endpoint ID** to get **DNS Names** of the endpoint created on our behalf :
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ec2.InterfaceVpcEndpointAttributes.html

And/Or add outputs to Transfer with these 2 values.

**Comment by iliapolo** [comment]
@Cloudrage can you please share the code you are using to create the transfer server?

**Comment by Cloudrage** [comment]
Sure @iliapolo : 
```
// Transfer Server
    const CfnTransferServer = new transfer.CfnServer(this, 'CfnTransferServer', {
      endpointType: 'VPC',
      endpointDetails: {
        securityGroupIds: [SecurityGroupCfnTransferServer.securityGroupId],
        subnetIds: [PrivateSubnet1Id, PrivateSubnet2Id, PrivateSubnet3Id],
        vpcId: vpc.vpcId
      },
      identityProviderType: 'API_GATEWAY',
      identityProviderDetails: {
        invocationRole: IamRoleInvocationCfnTransferServer.roleArn,
        url: 'https://'+RestApi.restApiId+'.execute-api.'+AppAccountRegion+'.amazonaws.com/'+ApiStage.stageName
      },
      loggingRole: IamRoleLoggingCfnTransferServer.roleArn,
      protocols: ['SFTP'],
    });
```

Again, after that, I want to create a R53 targeting the Endpoint DNS Name, ex: `xxxx.eu-west-1.vpce.amazonaws.com`
Previously, it was possible when creating NLB+EndpointService on our own.

**Comment by iliapolo** [comment]
@Cloudrage I think I understand now.

It sounds like a good feature for when we start working on an L2 construct for `CfnServer`.

In the meantime, you can use the `AwsCustomResource` to retrieve the endpoint id:

```ts
import * as cr from '@aws-cdk/custom-resources';
import * as transfer from '@aws-cdk/aws-transfer';

const server = new transfer.CfnServer(...);

const serverDescription = new cr.AwsCustomResource(this, 'ServerDescription', {
  onCreate: {
    action: 'describeServer',
    service: 'Transfer',
    parameters: {
      ServerId: server.attrServerId,
    },
    physicalResourceId: cr.PhysicalResourceId.of(server.attrServerId),
  },
  policy: cr.AwsCustomResourcePolicy.fromSdkCalls({ resources: [server.attrArn] })
});

const endpointId = serverDescription.getResponseField('Server.EndpointDetails.VpcEndpointId');
```

Is this what you had in mind?

**Comment by Cloudrage** [comment]
Yep @iliapolo , a Custom Resource like that can do the job but the idea was to create a Feature Request to do it natively.
But in our case, I need to make another CustomResource to get the DNS Names of the endpoints to be able to create the R53 Record with it !

And in some case, that value need to bet retrieved cross-account, and that way, how to do that ?

Another question "under the table", how can I do to job to write that correctly :
![image](https://user-images.githubusercontent.com/30436750/100472219-1c42a480-30dc-11eb-9e5e-6f6854b7dff1.png)
I've tried : 
`"$util.escapeJavaScript($input.params('Password')).replaceAll(\"\\'\",\"'\")".replace(/\"/g, '"'),`
But don't seems to change something, the replace don't work.

**Comment by iliapolo** [comment]
@Cloudrage 

> a Custom Resource like that can do the job but the idea was to create a Feature Request to do it natively.

Yes, and I am marking this capability as a feature request.

> But in our case, I need to make another CustomResource to get the DNS Names of the endpoints to be able to create the R53 Record with it !

Perhaps this is more suitable on the [`vpc-endpoint`](https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-ec2/lib/vpc-endpoint.ts) construct  in the `ec2` module. We will consider this.

> Another question "under the table", how can I do to job to write that correctly :

I would imagine this should work:

`const template = "$util.escapeJavaScript($input.params('Password').replaceAll(\"\\'\", \"'\")"`, im not sure why you've added the `.replace(/\"/g, '"')`

Apologies but I am not an expert on API Gateway mapping templates. I suggest you ask this question on the *#aws-cdk* slack channel in [`cdk.dev`](https://cdk.dev/) or StackOverflow.

Thanks

**Comment by Cloudrage** [comment]
Already tried that @iliapolo  :
`.replaceAll(\"\\'\", \"'\")",`
But it result in `\"\\'\", \"'\"` instead of `"\\'","'"`

I've open a case few weeks ago about that : #11335
But I was wrong, it's not working as expected (maybe because of a test done manually through the Console).

**Comment by iliapolo** [comment]
This seems to work:

```console
> const c = "$util.escapeJavaScript($input.params('Password').replaceAll(\"\\\\'\", \"'\")"
> console.log(c)
$util.escapeJavaScript($input.params('Password').replaceAll("\\'", "'")
```

**Comment by Cloudrage** [comment]
@iliapolo 
Tested too but with CDK, it result : 
`"$util.escapeJavaScript($input.params('Password').replaceAll(\"\\\\'\", \"'\")"`

Maybe caused by **JSON.stringify** : 
```
new apigateway.Integration({
        type: apigateway.IntegrationType.AWS,
        integrationHttpMethod: 'POST',
        uri: 'arn:aws:apigateway:.....',
        options: {
          integrationResponses: [{statusCode: '200'}],
          requestTemplates: {
            'application/json': JSON.stringify({
              username: "$util.urlDecode($input.params('username'))",
              password: "$util.escapeJavaScript($input.params('Password').replaceAll(\"\\\\'\", \"'\")",
              serverId: "$input.params('serverId')",
              protocol: "$input.params('protocol')",
              sourceIp: "$input.params('sourceIp')"
            })
          }
        }
```
