### ISSUE TITLE
[route53] Certificate custom resource: report region in error message

### ISSUE THREAD

**Issue by hugomallet** [aws/aws-cdk#11390]
Hello,

Recently i had quota error when trying to create certificates. My quota dashboard was saying i had a limit of 2000 certificate requests per year but the error was saying that my limit was 20.
See this issue for details : #5889 

After days of discussion with the support team in finally discovered that i was making a certificate request on another region (because of cloudfront requirements).

I would have found the problem in 5 minutes instead of days if the error was mentioning the requested region.
Can you add the requested region in quota errors at least please ?

Thanks,

---

This is a :rocket: Feature Request

**Comment by njlynch** [comment]
Hi @hugomallet,

This error comes straight from the AWS Certificate Manager service, and we (the CDK team) don't have any direct control over the messaging. I think the confusion here comes from the fact that (I assume) you were using the `DnsValidatedCertificate` construct, which allows cross-region requests. Even with that construct though, the region must be explicitly set to make a cross-region request. Any CloudFormation deployment failure message should be associated with the resource that caused the failure, allowing you to trace back the failure to the `DnsValidatedCertificate` with the region explicit set.

Sorry for the frustration here, but I don't think there's much we can do on the CDK side to make this more explicit.

**Comment by hugomallet** [comment]
Hi @njlynch ,

Cross region resources shouldn't log the used region used in errors ? It would help.
