### ISSUE TITLE
[aws-cognito] give an option to define IDs for user pool, identity pool and client ID

### ISSUE THREAD

**Issue by luizcieslak** [aws/aws-cdk#11392]
Hi! I'd like to have the option to define the IDs for an UserPool (also the id for the Client ID) and IdentityPool or rather keeping them constant.

### Use Case

I'm using [Amplify JS](https://docs.amplify.aws/lib/auth/start/q/platform/js#re-use-existing-authentication-resource) in the client side, which I need to input these IDs above when configuring it.

The thing is, when some configuration in changed and another deploy is done via CDK, these IDs change (I'd like to know more about what exactly triggers a new ID generation), being necessary to update the environment variables and deploy a new version of the frontend, making the service **unavailable** while this is being done (my main concern).

### Proposed Solution

Optional fields

UserPool:

```js
new cognito.UserPool(this, `MyUserPool`, {
			userPoolId: 'abcd1234',
                        ...
}
```

IdentityPool

```js
new cognito.CfnIdentityPool(this, `MyIdentityPool`, {
			identityPoolId: 'XXXXXXXX-XXXX-1234-abcd-1234567890ab',
                        ...
}
```
Client ID
```js
new cognito.UserPoolClient(this, `MyUserPool`, {
			clientId: 'a1b2c3d4e5f6g7h8i9j0k1l2m3',
                        ...
}
```

### Other

[Amplify JS Re-use existing authentication resource](https://docs.amplify.aws/lib/auth/start/q/platform/js#re-use-existing-authentication-resource)

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by luizcieslak** [comment]
Wait.. Exploring it further it seems that is not possible to define them in CloudFormation or even in the AWS Console?

**Comment by nija-at** [comment]
@luizcieslak - correct. Unlike some other resources like Lambda functions, it's not possible to pre-define the identifiers for these resources. A unique is assigned to them by the Cognito service at the time of creation.
