### ISSUE TITLE
[cli] Documentation does not include customization for --bootstrap-customer-key

### ISSUE THREAD

**Issue by rafaelgsr** [aws/aws-cdk#11395]
https://docs.aws.amazon.com/cdk/latest/guide/bootstrapping.html#bootstrapping-customizing
https://docs.aws.amazon.com/cdk/latest/guide/cli.html 

The documentation doesn't mention about the new parameter introduced here: https://github.com/aws/aws-cdk/pull/10365 (--bootstrap-customer-key). It is mentioned on the CDK documentation, though: https://docs.aws.amazon.com/cdk/api/latest/docs/aws-codepipeline-readme.html#cross-account-codepipelines

---

This is a 📕 documentation issue

**Comment by pwrmiller** [comment]
Additionally, I believe we should update the documentation to specify that the default value of this parameter is false, and that the KMS key is not created by default. Can we also clarify / confirm that we're using SSE-S3 (which is the Amazon Managed KMS key) if the customer managed key is not added?

**Comment by Jerry-AWS** [comment]
I've updated the CLI and Bootstrapping topics in the CDK Dev Guide to call out the `--bootstrap-customer-key` flag. Also updated the CLI help content that's reproduced in the Guide (there was a minor change to the CLI's help output so the script I was using to scrape it needed an update). These updates should be live on docs.aws.amazon.com in the next 24 hours.

I'll close this for now; feel free to reopen if you find issues with the revised topics.
