### ISSUE TITLE
[aws-lambda] Unable to import Layer modules from Lamda

### ISSUE THREAD

**Issue by ivorpad** [aws/aws-cdk#11417]
## :question: General Issue

I have a problem when setting up a layer, the lambda function is assigned the layer correctly, but it's unable to import its modules. I found someone having the same issue here: https://stackoverflow.com/questions/63993152/question-trying-to-add-a-layer-but-fails

### The Question

As you can see I'm setting up the layer correctly:

```javascript
const Layer_EZOT = new lambda.LayerVersion(this, "EzOrderTrackingLayer", {
  compatibleRuntimes: [lambda.Runtime.NODEJS_12_X],
  code: lambda.Code.fromAsset(path.join(__dirname, "src/layer")),
});

Layer_EZOT.addPermission("ez-order-grant", {
  accountId: "<account_id>",
});

const Lambda_EZOT_OrderCreate = new lambda.Function(
  this,
  "EzOrderCdkCreateOrder",
  {
    code: lambda.Code.fromAsset(path.join(__dirname, "lambda")),
    handler: "ez-create-order.handler",
    runtime: lambda.Runtime.NODEJS_12_X,
    layers: [Layer_EZOT],
  }
);
```
The project structure is correct:

<img width="185" alt="Screen Shot 2020-11-11 at 2 37 14 PM" src="https://user-images.githubusercontent.com/52452/98818212-834d3180-242b-11eb-9fc9-97ba1a102a65.png">

I can see from console that the Layer is correctly assigned to the Lambda, and I can confirm the code is uploaded as expected. While debugging I downloaded the artifact and uploaded to a Layer I setup manually, then assigned it to the Lambda and it worked as expected.

### Environment

  - **CDK CLI Version:** 1.72.0 (build c2f38e8)
  - **Node.js Version:** 12

### Other information
Stack trace: https://gist.github.com/ivorpad/8a45e73864da44896ed749aa7978d613

**Comment by iRoachie** [comment]
To require npm packages from layers, the folder structure of the layer needs to follow a particular pattern.

```bash
.
├── layer                
│   └── nodejs                   
│          └── node_modules
│          └── package.json
```

See https://docs.aws.amazon.com/lambda/latest/dg/configuration-layers.html#configuration-layers-path

**Comment by ivorpad** [comment]
Thanks @iRoachie 

Already tried that. Same error.

<img width="278" alt="Screen Shot 2020-11-11 at 3 55 03 PM" src="https://user-images.githubusercontent.com/52452/98826732-5fdbb400-2436-11eb-8212-44e9486209cb.png">

```json
{
   "errorType":"Runtime.ImportModuleError",
   "errorMessage":"Error: Cannot find module 'ramda'\nRequire stack:\n- /var/task/ez-create-order.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
   "trace":[
      "Runtime.ImportModuleError: Error: Cannot find module 'ramda'",
      "Require stack:",
      "- /var/task/ez-create-order.js",
      "- /var/runtime/UserFunction.js",
      "- /var/runtime/index.js",
      "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
      "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
      "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
      "    at Module._compile (internal/modules/cjs/loader.js:1137:30)",
      "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)",
      "    at Module.load (internal/modules/cjs/loader.js:985:32)",
      "    at Function.Module._load (internal/modules/cjs/loader.js:878:14)",
      "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)",
      "    at internal/main/run_main_module.js:17:47"
   ]
}
```

**Comment by ivorpad** [comment]
Solved with:

```javascript
// stack.ts
new lambda.LayerVersion(this, "EzOrderTrackingLayer", {
  compatibleRuntimes: [lambda.Runtime.NODEJS_12_X],
  code: lambda.Code.fromAsset(path.join(__dirname, "layer")),
});
```

```
.
├─ lib
│    └─ stack.ts  
│    └─ layer           
│         └─ nodejs                   
│              └─ node_modules
|              └─ package.json
│    
```

```
// https://docs.aws.amazon.com/lambda/latest/dg/configuration-layers.html#configuration-layers-path
xray-sdk.zip
   └ nodejs/node_modules/aws-xray-sdk
```

Thanks for the link @iRoachie
