### ISSUE TITLE
[custom-resources][aws-codepipeline] CustomResources AssetParameters not set during Cloudformation Deploy

### ISSUE THREAD

**Issue by joa44741** [aws/aws-cdk#11415]
### Description of the bug: 
I try to add a custom resource to the CI/CD pipeline which I built exactly like described in this link: https://docs.aws.amazon.com/cdk/latest/guide/codepipeline_example.html

### Reproduction Steps

add these lines to the `lambda-stack.ts` of the example code: https://docs.aws.amazon.com/cdk/latest/guide/codepipeline_example.html

`import * as customres from '@aws-cdk/custom-resources';`
`...`
`
    const provider = new customres.Provider(this, 'mycustomprovider', {
      onEventHandler: alias
    });
`    
`    
    new core.CustomResource(this, 'mycustomresource', {
      serviceToken: provider.serviceToken
    });
`

### What did you expect to happen?

The CodePipeline should add the CustomResource (call the Lambda) in the CloudFormation deploy step.

### What actually happened?
This error occured in the deploy step:

_Parameters: [AssetParametersc691172cdeefa2c91b5a2907f9d81118e47597634943344795f1a844192dd49cS3BucketEAC9DD43, AssetParametersc691172cdeefa2c91b5a2907f9d81118e47597634943344795f1a844192dd49cS3VersionKeyDD9AE9E7, AssetParametersc691172cdeefa2c91b5a2907f9d81118e47597634943344795f1a844192dd49cArtifactHash627DAAA7] must have values (Service: AmazonCloudFormation; Status Code: 400; Error Code: ValidationError; Request ID: e8f9a97f-fee8-48e3-a182-30bf6aa6e2fd)_

### Environment

  - **CDK CLI Version  :** 1.72.0
  - **Framework Version:** 1.72.0
  - **Node.js Version:** I guess the one used by codebuild.LinuxBuildImage.STANDARD_2_0
  - **OS               :** codebuild.LinuxBuildImage.STANDARD_2_0
  - **Language (Version):** TypeScript (3.9.7)

### Other
The same error occurs when using `AwsCustomResource`
```
new customresources.AwsCustomResource(this, CustomThingType, {`
      onCreate: {
        service: 'Iot',
        action: 'createThingType',
        parameters: {
          thingTypeName: thingType,
          thingTypeProperties: {
            searchableAttributes: [
              'status'
            ]
          }
        },
        physicalResourceId: customresources.PhysicalResourceId.fromResponse('VerificationToken') 
      },
      policy: customresources.AwsCustomResourcePolicy.fromSdkCalls({resources: customresources.AwsCustomResourcePolicy.ANY_RESOURCE})
    });
```

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hi @joa44741 ,

thanks for opening the issue. The reason you're seeing that error is because the custom resources use [Assets](https://docs.aws.amazon.com/cdk/latest/guide/assets.html), which are not compatible with that article you quoted (that's why the article uses `Code.fromCfnParameters()`, instead of Assets, for the Lambda code).

I would recommend you take a look at the [CDK Pipelines module](https://docs.aws.amazon.com/cdk/api/latest/docs/pipelines-readme.html), which _does_ correctly support Assets.

Thanks,
Adam

**Comment by joa44741** [comment]
Hi @skinny85 
Thanks for your fast response. 
I also thought about using CDK Pipelines but I saw this limitation: 
_No context queries: context queries are not supported. That means that Vpc.fromLookup() and other functions like it will not work #8905._

How would I use an existing VPC in this case, e.g. to create a new Security Group in this Pipeline?

**Comment by skinny85** [comment]
Hi @joa44741 ,

there is a way to work around that limitation. You need to run `cdk synth` with the AWS credentials of the account the VPC is in. That will populate the `cdk.context.json` file with the VPC information. After you `git push` that file, CDK will use that information instead of doing a lookup, and the pipeline build will succeed.

**Comment by OperationalFallacy** [comment]
Hey @skinny85, is there a way to deploy pipeline stack with cdk.context.json? 
I have context populated with cdk synth, but it doesn't add vpc/subnet info when the pipeline stack is deployed.
Which in turn makes pipeline on synth step because there is no VPC and no Internet access.

**Comment by skinny85** [comment]
> I have context populated with cdk synth, but it doesn't add vpc/subnet info when the pipeline stack is deployed

Can you clarify @OperationalFallacy what does this mean? Why are the VPC/Subnets not populated for the pipeline Stack?

**Comment by OperationalFallacy** [comment]
Sorry, user error. Forgot to commit cdk.context.json in the branch.
