### ISSUE TITLE
[cli] Allow bootstrap toolkit stack to be deployed as a stackset

### ISSUE THREAD

**Issue by wulfmann** [aws/aws-cdk#11420]
### Use Case

I would like to be able to deploy the cdk toolkit stack (bootstrap) as a stackset. I am unable to use the normal bootstrap process because there are some permissions that I needed to change from the normal toolkit stack.

The problem is I have a number of different accounts to manage and would like to put the toolkit into a stackset. This breaks the link with CDK because it is expecting the stack to have a certain name and stacksets append a uuid. I can pass in the toolkit stack name to the CDK commands, but this quickly becomes unwieldly for different environments and it is not easy to tell which to use by looking at the name.

### Proposed Solution

Adding an SSM Parameter with a value of: AWS::StackName (similar to the bootstrap version parameter). CDK can then check this parameter to find the stack name to use.

I see this as a band-aid fix and would like to question the design of this particular piece of the process. I think the bootstrap process may work well for smaller organizations, but if you use stacksets or service catalog (or both) then you will run into a potential issue maintaining these stacks. Additionally, the default cdk bootstrap is pretty permissive in the trust relationships and policies that it receives. If you have a team that manages these permissions, it's very difficult to customize the inner-workings of the role chain without a custom stack.

### Other

Is it necessary to know the stack name with new style stack synthesis? Are we able to just remove that requirement? That would also solve this issue.

* [x] :wave: I may be able to implement this feature request
* [x] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
> Is it necessary to know the stack name with new style stack synthesis?

It shouldn't be, and is probably an accidental historical holdout. Related to https://github.com/aws/aws-cdk/issues/9053

**Comment by redbaron** [comment]
Another solution would be to change ToolKit lookup to use CF `ListExports` API to query individual values they are interested in. Currently it loocates `CDKToolkit` stack and queries it's output . By switching to CF exports in bootstrap stack we also get a nice property, that there is only one export for a given qualifier available, no matter which stack it is coming from

**Comment by wulfmann** [comment]
@redbaron I do like that in that solution you'd take advantage of the outputs being unique. If we're not opposed to introducing another API call to the process this could work for me. I proposed using the parameter simply because that is a pattern that is in-use (bootstrap version).

Ideally I think we still need to get away from pulling this from the stack if you're using new style stack synthesis and overriding the synthesizer inputs. I personally would only use one bootstrap stack per account, but I could see a use case where you might have a few different configurations (different bucket or ecr repo configurations). Even if you directly tell the stack synthesizer what values it needs, you bump into this stack name issue.

**Comment by redbaron** [comment]
Different bootstrap stack in the same account can be distinguished by qualifier. `cdk deploy` knows qualifier it looks for , then looks up CF exports using qualifier.

Another option - move everything to SSM, not just Bootstrap stack name. This would allow more methods to bootstrap accounts and only contract is that there must be SSM values for buckets, registry, iam roles, etc.

**Comment by mrpackethead** [comment]
I found a workaround for the time being..  I'm copying cdk.json into cdk.out.. when cdk deploy does its thing, it will use the stackname thats in cdk.json


```
  pipeline = pipelines.CdkPipeline(self, project_name + 'Pipeline',
        cloud_assembly_artifact = cloud_assembly_artifact,
        pipeline_name = project_name,
        source_action=pipeline_source_action,
        synth_action=pipelines.SimpleSynthAction(
          source_artifact=source_artifact,
          cloud_assembly_artifact=cloud_assembly_artifact,
          install_command='npm install -g aws-cdk && pip install -r requirements.txt',
          #build_command='pytest unittests',
          synth_command='cdk synth && cp cdk.json cdk.out')
    )
```
