### ISSUE TITLE
[pipelines] SimpleSynthAction with subdirectory prop specified produces a wrong buildspec

### ISSUE THREAD

**Issue by tomas-mazak** [aws/aws-cdk#11424]
SimpleSynthAction uses `path.join()` function to render path to artifacts. It seems that buildspec requires the path to use forward-slash as a path separator (probably as the synth action runs on Linux), however, `path.join()` produces a path with backslashes when synthesis is run on Windows. This should hence be hardcoded to join by forward slash (`/`).

I believe the bug is here:

https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/pipelines/lib/synths/simple-synth-action.ts#L376

### Reproduction Steps

Instantiate a `CdkPipeline` with following `synthAction`:

```ts
const synthAction = cdkpipelines.SimpleSynthAction.standardNpmSynth({
  sourceArtifact,
  cloudAssemblyArtifact,
  subdirectory: 'cdk',
});
```
Run `cdk synth` on Windows machine.

### What did you expect to happen?

In synth action CodeBuild project's buildspec, the following should be present:

```json
{
  "artifacts": {
    "base-directory": "cdk/cdk.out",
    "files": "**/*"
  }
}
```

### What actually happened?

If synthetized on Windows machine, result is as follows:

```json
{
  "artifacts": {
    "base-directory": "cdk\\cdk.out",
    "files": "**/*"
  }
}
```

This causes the artifact to be packaged incorrectly and the subsequent `UpdatePipeline` action fails as it cannot find the cloud assembly in the expected path.

### Environment

  - **CDK CLI Version   : 1.73.0 (build eb6f3a9)
  - **Framework Version : 1.72.0
  - **Node.js Version   : v10.16.3
  - **OS                : Windows 10 Enterprise 1909
  - **Language (Version): Typescript 3.9.7

### Other

I will raise a PR to fix this shortly.

--- 

This is :bug: Bug Report

**Comment by hoegertn** [comment]
Shouldn't this be solved by the first mutation as the synth is running on Linux too in the CodePipeline synthesize step?

**Comment by tomas-mazak** [comment]
> Shouldn't this be solved by the first mutation as the synth is running on Linux too in the CodePipeline synthesize step?

@hoegertn, That very first mutation fails already because of this bug:

```
Error: ENOENT: no such file or directory, open 'manifest.json'
```

**Comment by hoegertn** [comment]
Got it. Can you provide a PullRequest with a fix? Should be straight forward.
