### ISSUE TITLE
[aws-lambda-nodejs] document how to install native modules (was: Ability to run post install scripts when nodeModules are explicitely defined)

### ISSUE THREAD

**Issue by whimzyLive** [aws/aws-cdk#11439]
Currently NodejsFunction takes care of installing defined nodeModules and uploading assets to s3 but it will be nice to also be able to define post install scrips. 

### Use Case

I am trying to bundle a handler that makes use of `Sharp` which has node execs ".node" in it's distribution, but since parcel currenty doesn't support bundelling ".node" files (as long as I am aware), I tried it as having an installed node_module by specifying 
```typescript
    nodeModules: ['sharp'],
```  
but this won't work as is, because my development machine uses libvs based on darwin distribution and lambda requires linux based. As [documented](https://sharp.pixelplumbing.com/install#aws-lambda) in sharp this can be resolved by reinstalling/rebuilding sharp for linux platform as 

```typescript
postinstall: npm rebuild sharp --arch=x64 --platform=linux sharp
```

### Proposed Solution

NodejsFunction props to accept postInstal scripts along with nodeModules and applying it to npm postinstall script. 

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by jogold** [comment]
Have a look at https://github.com/jogold/cdk-s3-thumbnail where I use `sharp`. It uses Docker bundling to build `sharp` in a Lambda compatible environment.

If you have Parcel installed and still to want to force Docker bundling you can set the `forceDockerBundling` prop to `true`.

**Comment by whimzyLive** [comment]
@jogold Okay, that worked. Thanks. Not sure it will still be a worth while having an option to allow users to provide post install scripts.

**Comment by eladb** [comment]
@jogold  can we add some documentation to the lambda-nodejs module which explains this?

**Comment by hades2510** [comment]
In case you are having multiple functions declared in the same file, you need to add ```bundling: {nodeModules: ['sharp']}``` to each declared lambda function definition even if you don't use `sharp` in that particular function.

**Comment by stevensnoeijen** [comment]
Tried installing NodeJsFunction with sharp dependency in `forceDockerBundling: true`, but I'm getting the following:
![image](https://user-images.githubusercontent.com/2750503/143099236-c53b927a-d039-48ec-b1cb-57bda2d64e3c.png)
Platform is win 10 x64. Also tried running vscode as administrator, but that also didnt work.
Any idea what is going wrong here?

**Comment by hudsontavares** [comment]
For other people facing the same issue as @stevensnoeijen and I:
This is a Windows permission issue I resolved by using "Run as Administrator" in Windows 10 Home (right-click the terminal icon and choose this option)
