### ISSUE TITLE
[aws-ivs] L2 construct for aws-ivs

### ISSUE THREAD

**Issue by IainCole** [aws/aws-cdk#11434]
I'm going to work on making these since the latest CloudFormation just got merged

I'm making this issue so that others can track it.

**Comment by NetaNir** [comment]
Hi,

Thanks for opening the issue, and for working on this L2. To make the review process more efficient, once you have initial API on mind, add it  in the comments or even better, submit a draft pull request with the future README of the L2. This will allow us to discuss the API before the implementation, reducing code change and long review cycles.

Thanks!

**Comment by IainCole** [comment]
welp.. bit late for that =)
