### ISSUE TITLE
[aws-ecs-patterns] Missing command parameter for task definition

### ISSUE THREAD

**Issue by jolo-dev** [aws/aws-cdk#11437]
The `ApplicationLoadBalancedFargateService` is missing a list of commands when creating the container.

### Use Case

Some docker container needs to run a command after creating the container.
E.g. Airflow needs to run `webserver`.

### Proposed Solution
For Python

```python
load_balanced_fargate_service = ecsp.ApplicationLoadBalancedFargateService(
            self,
            "Service",
            cluster=cluster,
            memory_limit_mib=1024,
            cpu=512,
            image=ecs.ContainerImage.from_registry("apache/airflow"),
            command=["webserver"],
        )
```

This is a :rocket: Feature Request

**Comment by piradeepk** [comment]
@jolo-dev it's not feasible to add every possible property of a task definition or container definition. However you can achieve what you're trying to by creating a Task Definition and [passing it in as input](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-ecs-patterns/lib/fargate/application-load-balanced-fargate-service.ts#L17) to the ApplicationLoadBalancedFargateService construct.

**Comment by jolo-dev** [comment]
@piradeepk Thanks for your answer.
Yes, I ended up creating each component individually. And I used that for passing the command.
It's fine. I thought that might be quite handy for others as well.

**Comment by piradeepk** [comment]
Did you create every component of the ApplicationLoadBalancedFargateService, or just the FargateTaskDefinition and pass it use it as input to ApplicationLoadBalancedFargateService?

**Comment by jolo-dev** [comment]
I created every component individually (class for LoadBalancer, TargetGroups, Ecs + Fargate).

But might be a good case to refactor it.
