### ISSUE TITLE
[aws-apigatewayv2-integrations] getting is not a constructor error

### ISSUE THREAD

**Issue by dave-graham** [aws/aws-cdk#11443]
When I run:

`cdk synth`

On a project that has:

`aws_apigatewayv2_1.LambdaProxyIntegration` in, e.g.:

```ts
import { LambdaProxyIntegration } from "@aws-cdk/aws-apigatewayv2-integrations";

const integration = new LambdaProxyIntegration({
      handler
    });
```

I get the following error:

`aws_apigatewayv2_1.LambdaProxyIntegration is not a constructor`

Any help is really appreciated.

**Comment by mikigraf** [comment]
Can you show your package.json?

**Comment by dave-graham** [comment]
{
    "name": "...",
    "version": "...",
    "scripts": {
        ...
    },
    "devDependencies": {
      "@aws-cdk/assert": "^1.73.0",
      "@aws-cdk/aws-ec2": "^1.73.0",
      "@aws-cdk/aws-events": "^1.73.0",
      "@aws-cdk/aws-events-targets": "^1.73.0",
      "@aws-cdk/aws-iam": "^1.73.0",
      "@aws-cdk/aws-rds": "^1.73.0",
      "@aws-cdk/aws-s3": "^1.73.0",
      "@aws-cdk/core": "^1.73.0",
      "@aws-cdk/aws-apigatewayv2-integrations": "^1.73.0",
      "@org/cdk-common": "^1.0.100",
      "@types/jest": "^26.0.15",
      "aws-cdk": "^1.73.0",
      "jest": "^26.6.3",
      "prettier": "^2.1.2",
      "source-map-support": "^0.5.16",
      "ts-jest": "^26.4.4",
      "ts-node": "^9.0.0",
      "typescript": "^4.0.5"
    },
    "dependencies": {
      "aws-sdk": "^2.792.0"
    },
    "targets": {
      "cdk-lambda": {
        "context": "node",
        "includeNodeModules": {
          "aws-sdk": false
        },
        "sourceMap": false,
        "minify": false,
        "engines": {
          "node": ">= 12"
        }
      }
    }
  }
  
"@org/cdk-common": "^1.0.100"

contains internal re-usable cdk constructs, and it's package json is fully up to date with 1.73.0

**Comment by nija-at** [comment]
I'm not able to reproduce this. I'm able to construct a new `LambdaProxyIntegration` class and synthesize a cloudformation template from it.

Something has likely gone wrong with your set up.

**Comment by schof** [comment]
@dave-graham Did you happen to figure out what caused this issue? I just ran into it myself.

**Comment by schof** [comment]
For anyone struggling with this issue, it looks like the `LambdaProxyIntegration` was recently moved into a new package (aws-apigatewayv2-integrations). I had a third party CDK construct that was relying on the old location so none of this was obvious.
