### ISSUE TITLE
[iam] The value supplied for parameter 'instanceProfileName' is not valid.

### ISSUE THREAD

**Issue by dign17** [aws/aws-cdk#11441]
### Question
Running `cdk deploy` I receive the following error message:

> CREATE_FAILED        | AWS::ImageBuilder::InfrastructureConfiguration | TestInfrastructureConfiguration The value supplied for parameter 'instanceProfileName' is not valid. The provided instance profile does not exist. Please specify a different instance profile and try again. (Service: Imagebuilder, Status Code: 400, Request ID: 41f431d7-8544-48e9-9faf-a870b83b0100, Extended Request ID: null)

The C# code looks like this:

```csharp
var instanceProfile = new CfnInstanceProfile(this, "TestInstanceProfile", new CfnInstanceProfileProps {
  InstanceProfileName = "test-instance-profile",
  Roles = new string[] { "TestServiceRoleForImageBuilder" }
});

var infrastructureConfiguration = new CfnInfrastructureConfiguration(this, "TestInfrastructureConfiguration", new CfnInfrastructureConfigurationProps {
  Name = "test-infrastructure-configuration",
  InstanceProfileName = instanceProfile.InstanceProfileName,
  InstanceTypes = new string[] { "t2.medium" },
  Logging = new CfnInfrastructureConfiguration.LoggingProperty {
    S3Logs = new CfnInfrastructureConfiguration.S3LogsProperty {
      S3BucketName = "s3-test-assets",
      S3KeyPrefix = "ImageBuilder/Logs"
    }
  },
  SubnetId = "subnet-12f3456f",
  SecurityGroupIds = new string[] { "sg-12b3e4e5b67f8900f" }
});
```
The **TestServiceRoleForImageBuilder** exists and was working previously. Same code was running successfully about a month ago. Any suggestions?

If I remove the **CfninfrastructureConfiguration** creation part, deployment runs successfully:, but takes at least 2 minutes to complete.

> AwsImageBuilderStack: deploying...
> AwsImageBuilderStack: creating CloudFormation changeset...
>  0/3 | 14:24:37 | REVIEW_IN_PROGRESS   | AWS::CloudFormation::Stack | AwsImageBuilderStack User Initiated
>  0/3 | 14:24:43 | CREATE_IN_PROGRESS   | AWS::CloudFormation::Stack | AwsImageBuilderStack User Initiated
>  0/3 | 14:24:47 | CREATE_IN_PROGRESS   | AWS::CDK::Metadata        | CDKMetadata/Default (CDKMetadata)
>  0/3 | 14:24:47 | CREATE_IN_PROGRESS   | AWS::IAM::InstanceProfile | TestInstanceProfile
>  0/3 | 14:24:47 | CREATE_IN_PROGRESS   | AWS::IAM::InstanceProfile | TestInstanceProfile Resource creation Initiated
>  1/3 | 14:24:48 | CREATE_IN_PROGRESS   | AWS::CDK::Metadata        | CDKMetadata/Default (CDKMetadata) Resource creation Initiated
>  1/3 | 14:24:48 | CREATE_COMPLETE      | AWS::CDK::Metadata        | CDKMetadata/Default (CDKMetadata)
> 1/3 Currently in progress: AwsImageBuilderStack, TestInstanceProfile
>  3/3 | 14:26:48 | CREATE_COMPLETE      | AWS::IAM::InstanceProfile | TestInstanceProfile
>  3/3 | 14:26:49 | CREATE_COMPLETE      | AWS::CloudFormation::Stack | AwsImageBuilderStack

Is it probably some race condition? Should I use multiple stacks to achieve my goal?

### Environment

  - **CDK CLI Version:** 1.73.0
  - **Node.js Version:** 14.13.0
  - **OS:** Windows 10
  - **Language (Version):** C# (.NET Core 3.1)

**Comment by dign17** [comment]
Should it be possible to use a wait condition [(AWS::CloudFormation::WaitCondition)](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-waitcondition.html) to bypass the 2 minutes of creation time in case it is intended?

**Comment by dign17** [comment]
Since the cause seems to be AWS internal, I used a pre-created instance profile as a workaround. The profile can be either created through IAM Management Console or CLI. However it would be nice to have a proper solution.

**Comment by rix0rrr** [comment]
```
  InstanceProfileName = instanceProfile.InstanceProfileName,
```

Needs to use `AttrInstanceProfileName`, otherwise there is no dependency between the two resources and deployment results in a race condition that sometimes works and sometimes doesn't (depending on which resource gets created first).

**Comment by dign17** [comment]
@rix0rrr: Could you further explain what you mean? In my example I have the same code snippet you show (a dependency between the resources in my opinion).

**Comment by rix0rrr** [comment]
I will repeat:

> Needs to use `AttrInstanceProfileName`

**Comment by dign17** [comment]
@rix0rrr: I can't find this property, can you point me at the right place in .Net documentation?

**Comment by bormm** [comment]
> I will repeat:
> > Needs to use `AttrInstanceProfileName`
How to make the own blog post about "A story of horrible customer support" to the reality for other peoples.
"I always descriped the solution with 4 words. As you didn't understand, I repeat the 4 words again, so we are in an endless horror support loop together now.". Just think about that @rix0rrr

**Comment by roebius** [comment]
@dign17: you already found your way to solve the issue, I am adding mine just to confirm an option you mentioned in your initial question: using multiple stacks. My solution was to use two separate stacks: a `profile_stack` for creating the instance profile and an `image_stack` taking care of the infrastructure. I had to enforce the correct deployment order using also `stack.addDependency(stack)` ([Stack API Developer Guide](https://docs.aws.amazon.com/cdk/latest/guide/stacks.html)).
Using Python, in my case, in the App I added: `image_stack.add_dependency(profile_stack)`

**Comment by michael-pryor-privitar** [comment]
infraConfig.addDependsOn(instanceProfile); worked for me in Java.

**Comment by nadszoney** [comment]
FYI the below worked for me in TypeScript:

```typescript
const instanceProfile = new CfnInstanceProfile(...);

new CfnInfrastructureConfiguration(..., {
  ...

  // using .ref instance of .instanceProfileName
  instanceProfileName: instanceProfile.ref, 
});
```
