### ISSUE TITLE
[aws-dynamodb] Creating a new Table using fromTableName returns a Table object that doesn't include secondary indexes

### ISSUE THREAD

**Issue by alonjupiter** [aws/aws-cdk#11445]
Hello!

I’ve noticed some discrepancies between the behavior of a `dynamodb.Table` created as `new Table()` and ones that are created by using `Table.fromTableName()`

Using `new Table(...).grantReadWriteData(myLambdaFunction)` delegates permissions to the primary table index, alongside all available GSIs.

However, using `new Table.fromTableName(…).grantReadWriteData(myLambdaFunction)` seems to delegate permissions to the primary table index only.

### Reproduction Steps

```typescript
const table = new Table.fromTableName(this, TABLE_NAME, TABLE_NAME).grantReadWriteData(
  myLambdaFunction
);

table.grantReadWrite(lambdaFn);
```

### What did you expect to happen?

Lambda function should be granted permissions to `ReadWrite` to all of the table's indexes, both primary and LSIs/GSIs.

### What actually happened?

Lambda function was granted permissions to `ReadWrite` to the primary index _only_.

### Environment

  - **CDK CLI Version  :** 1.69.0
  - **Framework Version:** 1.69.0
  - **Node.js Version:** 12.9.0
  - **OS               :** Linux
  - **Language (Version):** TypeScript 3.6.4

### Other

To workaround this issue one could explicitly define all partitions and then grant the necessary permissions to each, as such:

```typescript
const primaryIndex = Table.fromTableName(this, "MyTable", "MyTable");

const secondaryIndex = Table.fromTableName(
  this,
  `MyTableGsi`,
  `MyTable/index/Gsi-index`
);

primaryIndex.grantReadWriteData(lambdaFn);
secondaryIndex.grantReadWriteData(lambdaFn);
```

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hello @alonjupiter ,

thanks for opening the issue. `Table.fromTableName()` does not, in fact, create a new Table, but allows you to refer to an already existing one. Because of that, you have to specify all details of the Table yourself. If the Table has indexes, you need to use [`Table.fromTableAttributes method](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-dynamodb.Table.html#static-fromwbrtablewbrattributesscope-id-attrs), and provide the indexes yourself.

Thanks,
Adam

**Comment by alonjupiter** [comment]
Hi @skinny85,

Thanks for the quick response. Now you mention it does make sense that CDK will not be able to import all of its attributes just be referring to it by name.

That said, I ran a quick test today to see if this can be worked around by explicitly defining the table's GSIs using `TablefromTableAttributes` and could still see somewhat of an unexpected behavior.

This the code I used:

```typescript
Table.fromTableAttributes(this, "MyTable", {
  tableName: "MyTable",
  globalIndexes: ["foo", "bar"],
}).grantReadData(lambdaFn);
```
When I tried to deploy my stack the IAM statement warned me of the following changes:

```
IAM Statement Changes
┌───┬───────────────────────────────────────────┬────────┬───────────────────────────────────────────┬───────────────────────────────────────────┬───────────┐
│   │ Resource                                  │ Effect │ Action                                    │ Principal                                 │ Condition │
├───┼───────────────────────────────────────────┼────────┼───────────────────────────────────────────┼───────────────────────────────────────────┼───────────┤
│ + │ arn:${AWS::Partition}:dynamodb:us-east-1: │ Allow  │ dynamodb:BatchGetItem                     │ AWS:${MyStack/MyLambdaRole │           │
│   │ 123456789012:table/MyTable                │        │ dynamodb:GetItem                          │ e}                                        │           │
│   │ arn:${AWS::Partition}:dynamodb:us-east-1: │        │ dynamodb:GetRecords                       │                                           │           │
│   │ 123456789012:table/MyTable/index/*        │        │ dynamodb:GetShardIterator                 │                                           │           │
│   │                                           │        │ dynamodb:Query                            │                                           │           │
│   │                                           │        │ dynamodb:Scan                             │                                           │           │
└───┴───────────────────────────────────────────┴────────┴───────────────────────────────────────────┴───────────────────────────────────────────┴───────────┘
```

It looks as if the IAM role generated for the Lambda function is too permissive as it will grant permissions to all GSIs, while I explicitly stated only 2 out of 4 GSIs.

Is this too the expected behaviour?

**Comment by skinny85** [comment]
Hi @alonjupiter ,

yes, this is the expected behavior. I believe it's done that way, because you don't know the names of indexes before they are deployed in the case of a new Table.

In general, we don't assign per-index permissions - seems a little overkill I think...? Let me know if you disagree.

**Comment by alonjupiter** [comment]
Hi @skinny85! 

I'd say I disagree.

Generally speaking the security posture approach advocated by AWS is is to always go on the path of least privilege and only give access to the services/features/indices that are needed for that specific function or job. 

Granting too permissive permissions to a resource goes against the above, and therefore this behavior should be amended to grant resources the _least_ permissive permissions by default.

Happy to further discuss if needed!

**Comment by skinny85** [comment]
OK. Let's change this to a feature request then 🙂.

**Comment by alonjupiter** [comment]
Great stuff, thank you @skinny85!

**Comment by ranjith-fh** [comment]
@skinny85 Is this feature request has been moved?

**Comment by skinny85** [comment]
If by "moved", you mean "has someone started working on it", then the answer is "No". It's all yours 🙂.

**Comment by ranjith-jagadees** [comment]
@skinny85 Thanks for the update.

**Comment by ChelseaBradbury** [comment]
FYI looks like specifying `grantIndexPermissions` when importing the table should help with this:
https://github.com/aws/aws-cdk/blob/edad593db1882225936be64b5d7dbd4ac6a5094a/packages/aws-cdk-lib/aws-dynamodb/lib/table.ts#L633-L640
