### ISSUE TITLE
[pipelines] How to use endpoint of lambda backend as input for an `npm run build` command

### ISSUE THREAD

**Issue by erudisch** [aws/aws-cdk#11462]
### The Question
I have a stack in an application stage that generates an api gateway. I pass the url of that gateway as `CfnOutput` back to the pipeline to do two things:

1. use a `ShellScriptAction` for validation tests against the url stored in the `CfnOutput` variable.
2. use a `CodeBuildAction` to build a react app with the following command: `npm run build` and set an env var using this `CfnOutput` function

The 1. works fine (I create an env var using the `useOutputs` property of the `ShellScriptAction`).
The 2. doesn't work out of the box. 

Is there a way to use the gateway url in the way I want to use it?

### Environment

  - **CDK CLI Version:** 1.73.0
  - **Module Version:** 1.73.0
  - **Node.js Version:** v13.8.0
  - **OS:** OSX Catalina
  - **Language (Version):** TypeScript (4.0.5)

### Other information
Here is the piece of code:

```
export class InfrastructurePipelineStack extends cdk.Stack {
    constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
        super(scope, id, props)

        ...

        const deploy = new BackendPipelineStage(this, 'Deploy');
        const deployStage = cdkPipeline.addApplicationStage(deploy);
        deployStage.addActions(new pipelines.ShellScriptAction({
            actionName: 'TestAPIGatewayEndpoint',
            useOutputs: {
                ENDPOINT_URL: cdkPipeline.stackOutput(deploy.hcEndpoint)
            },
            commands: [
                'curl -Ssf $ENDPOINT_URL/',
                'curl -Ssf $ENDPOINT_URL/hello',
                'curl -Ssf $ENDPOINT_URL/test'
            ],
            runOrder: 3
        }),
        new codepipeline_actions.CodeBuildAction({
            actionName: 'Website',
            project: new codebuild.PipelineProject(this, 'BuildWebsite', {
              projectName: 'Website',
              buildSpec: codebuild.BuildSpec.fromObject({
                version: '0.2',
                phases: {
                    install: {
                        commands: [
                            'cd frontend',
                            'npm i',
                        ],
                    },
                    build: {
                        commands: [
                            `REACT_APP_API_URL=${deploy.hcEndpoint} npm run build`,
                        ],
                    },
                },
                artifacts: {
                    'base-directory': 'frontend/build',
                    files: '**/*',
                },
            }),
            environment: {
                    buildImage: codebuild.LinuxBuildImage.STANDARD_4_0,
                    computeType: codebuild.ComputeType.SMALL,
                }
            }),
            input: sourceArtifact,
            outputs: [
                craArtifiact
            ],
            environmentVariables: {
                REACT_APP_API_URL: {
                    value: cdk.Fn.importValue('GatewayUrl')
                }
            },
            runOrder: 4
        }));

        ...
    }
}
```

the `BackendPipelineStage` simple builds up the `BackendStack` which looks like this:

```
export class BackendStack extends cdk.Stack {
  public readonly hcEndpoint: cdk.CfnOutput;

  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);


    const gateway = new apigw.LambdaRestApi(this, 'Endpoint', {
      handler: lambda.handler
    });

    this.hcEndpoint = new cdk.CfnOutput(this, 'GatewayUrl', {
      value: gateway.url,
      exportName: 'GatewayUrl'
    });
  }
}
```

So my idea is to get the `gateway.url` from `BackendStack` into the `InfrastructurePipelineStack` by using `cdk.Fn.importValue('GatewayUrl')`. But this results in the error: `No export named GatewayUrl found.`

### Update

The `cdk.Fn.importValue` approach works, when I create the `BackendStack` before the `InfrastructurePipelineStack` like this:
```
const app = new cdk.App();
const backendStack = new BackendStack(app, 'IFA-Cloud-Backend', {
    env: {region: 'eu-west-1'}
});
new InfrastructurePipelineStack(app, 'InfrastructureStack', backendStack, {
    env: {region: 'eu-west-1'}
}).addDependency(backendStack);
```

But then I will lose the `selfMutating` property of the `cdkPipeline`, what I don't want.
I also don't want to create a second pipeline inside the `BackendStack`.

The best would be to use the `useOutputs` property in the `CodeBuildAction` like this:
```
     useOutputs: {
         ENDPOINT_URL: cdkPipeline.stackOutput(deployBackend.hcEndpoint)
     }
```
But `useOutputs` is only available in a `ShellScriptAction` and not in a `CodeBuildAction`.

Or is there a way to use it?

### Update 2

I could solve the issue by creating a custom build action based on the `ShellScriptAction`. I have added an input and output property to it and changed the buildspec of the inner project to build our react app with the needed env var provided by `useOutputs`.

Is there a better way to do it?

Regards
Erik

**Comment by rix0rrr** [comment]
> Is there a better way to do it?

Not right now. It occurs to me that I should have used codepipeline variables and that would have been a better mechanism, but for now you what you did is right.

**Comment by jrmcornish** [comment]
@erudisch I'm facing the same problem. Would you be able to post the complete solution for this that you came up with in the end?

**Comment by jayair** [comment]
FWIW, we spent some time on this issue and came up with a fix for it in SST — https://github.com/serverless-stack/serverless-stack

While deploying, we do a [string replace in the custom resource](https://github.com/serverless-stack/serverless-stack/blob/master/packages/resources/src/StaticSite.ts). And while developing we generate a file that we read on the React side with [a simple CLI](https://www.npmjs.com/package/@serverless-stack/static-site-env).

We wrote about it here — https://serverless-stack.com/chapters/setting-serverless-environments-variables-in-a-react-app.html
