### ISSUE TITLE
[lambda-nodejs] Deploy additional files alongside bundled output

### ISSUE THREAD

**Issue by TLadd** [aws/aws-cdk#11468]
I want to be able to push up some additional files along with the bundled output. One way of doing this would be to expose a hook that allows augmenting the bundling commands.

### Use Case
I'm trying to deploy a lambda function that uses the Prisma database client. They have a [guide](https://www.prisma.io/docs/guides/deployment/deploying-to-aws-lambda) using the serverless cli to deploy to lambda but I was hoping to use cdk since I have other infrastructure to manage as well.

The prisma database client is generated based on a `schema.prisma` file that itself is generated by introspecting the database. It actually automatically performs this generation on install, so my hope was that I could
- Specify `nodeModules: ["@prisma/client", "@prisma/cli"]`
- Bundle up the rest of the function and dependencies
- When install occurs, the client get generated as normal

The problem is that the `schema.prisma` file isn't copied to the output directory and I don't think there's a way for me to accomplish that. Ideally I would like to make use of the bundling functionality while still having some control over what else gets deployed.

### Proposed Solution

Perhaps expose a hook to inject custom commands? [This](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-lambda-nodejs/lib/bundlers.ts#L178) is the area of interest. I got something working hacking around node_modules where all I need to do is insert a `cp schema.prisma ${options.outputDir}` in between `parcelCommand` and `depsCommand`. So I was thinking a function like this:

```ts
const fn = new lambda.NodejsFunction(this, "MyCDKFunction", {
  nodeModules: ["@prisma/client", "@prisma/cli"],
  handler: "handler",
  entry: "lib/index.ts",
  modifyBundleCommand: ({ parcelCommand, depsCommand, options }) => {
    return [parcelCommand, `cp schema.prisma ${options.outputDir}`, depsCommand];
  }   
});
```

The default would just be `({ parcelCommand, depsCommand }) => [parcelCommand, depsCommand]` to maintain the default behavior.

* [X] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by jogold** [comment]
Why does the `cp` needs to be between `parcelCommand` and `depsCommand` in this case ?

**Comment by TLadd** [comment]
The prisma cli auto-generates the client according to the `schema.prisma` as a postinstall. So if the schema.prisma file isn't already in the output directory, it won't auto-generate. Thinking about it a little more though, if I could just run something afterwards, I could manually trigger the generation myself (Just `npx prisma generate`) so it seems like for my use case, the ability to specify commands to run after the default bundling commands are run would be good enough. I would run the copy command and then `npx prisma generate`

**Comment by maoosi** [comment]
+1 for this, I’m facing the same scenario as I'm also using Prisma within a Lambda function. That being said, I'm thinking there are other use cases in which people might want to include additional files and/or run additional commands with lambda.NodejsFunction.

To keep it consistent with the parameters already available in context to [Bundling Asset Code](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-lambda-readme.html#bundling-asset-code), I’d propose something like:

```javascript
new lambda.NodejsFunction(this, "MyFunction", {
    // ...
    bundling: {
        command: [],
    }
})
```

Assuming the command(s) passed gets executed just after the default Parcel bundling command, it should be enough to first copy the `prisma.schema` file and then run `npx prisma generate`?

**Comment by jogold** [comment]
Got it, will try address this after #11289.

**Comment by jogold** [comment]
We could have something like this:

Add a `additionalCommands` prop of type `ICommand`:

```ts
interface ICommand {
  beforeBundling(outputDir: string): string;
  afterBundling(outputDir: string): string;
}
```


```ts
new lambda.NodejsFunction(this, "MyFunction", {
  // ...
  additionalCommands: {
    beforeBundling(outputDir: string): string {
      // return a command to run before bundling
      // it can use the `outputDir` to copy to the right output folder
    },
    afterBundling(outputDir: string): string {
      // return a command to run after bundling
    },
  }
})
```

**Comment by maoosi** [comment]
@jogold I think that would work perfectly.

Quick question: Isn't the outputDir always equal to `/asset-output` like described in https://docs.aws.amazon.com/cdk/api/latest/docs/aws-lambda-readme.html#bundling-asset-code?

**Comment by jogold** [comment]
> Quick question: Isn't the outputDir always equal to `/asset-output` like described in

Not when doing local bundling https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/aws-lambda-nodejs#local-bundling
