### ISSUE TITLE
[aws-eks] Values passed to AddHelmChart are not getting applied

### ISSUE THREAD

**Issue by kishoreallwynraj** [aws/aws-cdk#11475]
I am trying to apply the Helm chart for "aws-load-balancer-controller" from this EKS charts repository https://github.com/aws/eks-charts/tree/master/stable/aws-load-balancer-controller

I am following the documentation from https://www.eksworkshop.com/beginner/180_fargate/prerequisites-for-alb/ and trying to setup the same via CDK. I have created an iamserviceaccount "aws-load-balancer-controller-test" and i am passing this service account to the chart values like below to my Fargate cluster. But when the cluster comes up, the installation has not taken my service account and instead it is creating a new service account irrespective of the data i passed for values.

```c#
cluster.AddHelmChart("albHelm", new HelmChartOptions 
            {
                Namespace = "kube-system",
                Repository = "https://aws.github.io/eks-charts",
                Chart = "aws-load-balancer-controller",
                Release = "aws-load-balancer-controller",
                Values = new Dictionary<string, object> {
                    ["clusterName"] = cluster.ClusterName,
                    ["serviceAccount.create"] = false,
                    ["serviceAccount.name"] = "aws-load-balancer-controller-test",
                },
                Wait = true,
                Timeout = Duration.Minutes(15)
            });
```

### Environment

  - **CDK CLI Version:** 1.73.0
  - **Node.js Version:** v14.15.0
  - **OS:**  Windows 10
  - **Language (Version):** C#

**Comment by kishoreallwynraj** [comment]
If i create a service account with name as "aws-load-balancer-controller" (same as what the chart is creating) then the Helm step is failing with below error. 

> Failed to create resource. Error: b'Release "aws-load-balancer-controller" does not exist. Installing it now.\nError: rendered manifests contain a resource that already exists. Unable to continue with install: ServiceAccount "aws-load-balancer-controller" in namespace "kube-system" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "aws-load-balancer-controller"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "kube-system"\n'

Based on the error i think it expects few labels/annotations to be present on the ServiceAccount which i created. But i am not sure how i can add these labels/annotations to the ServiceAccount to see if this resolves the issue.

**Comment by kishoreallwynraj** [comment]
Similar issue reported in https://github.com/aws/aws-cdk/issues/9910

**Comment by kishoreallwynraj** [comment]
Followed the workaround mentioned in #9910 and made below code change

```
var albControllerServiceAccount = cluster.AddServiceAccount("aws-load-balancer-controller-sa", new ServiceAccountOptions {
                Name = "aws-load-balancer-controller-sa",
                Namespace = "kube-system"
            });
var albController = cluster.AddHelmChart("albHelm", new HelmChartOptions
            {
                Namespace = "kube-system",
                Repository = "https://aws.github.io/eks-charts",
                Chart = "aws-load-balancer-controller",
                Release = "aws-load-balancer-controller",
                Values = new Dictionary<string, object> {
                    ["clusterName"] = cluster.ClusterName,
                    ["serviceAccount.create"] = false,
                    ["serviceAccount.name"] = albControllerServiceAccount.ServiceAccountName,
                },
                Wait = true,
                Timeout = Duration.Minutes(15)
            });
var albControllerServiceAccountManifestResource = cluster.Node.FindChild("manifest-aws-load-balancer-controller-saServiceAccountResource");
albController.Node.AddDependency(albControllerServiceAccount);
albController.Node.AddDependency(albControllerServiceAccountManifestResource);
```

but getting below error while doing the synth process

> Unhandled exception. Amazon.JSII.Runtime.JsiiException: No child with id: 'manifest-aws-load-balancer-controller-saServiceAccountResource'

Rendered template fragment before change
```
"eksew1examplesdevawsloadbalancercontrollersamanifestawsloadbalancercontrollersaServiceAccountResource9C08501E": {
      "Type": "Custom::AWSCDK-EKS-KubernetesResource",
      "Properties": {
        "ServiceToken": {
          "Fn::GetAtt": [
            "awscdkawseksKubectlProviderNestedStackawscdkawseksKubectlProviderNestedStackResourceA7AEBA6B",
            "Outputs.EksFargateStackawscdkawseksKubectlProviderframeworkonEvent6ABD4B23Arn"
          ]
        },
        "Manifest": {
          "Fn::Join": [
            "",
            [
              "[{\"apiVersion\":\"v1\",\"kind\":\"ServiceAccount\",\"metadata\":{\"name\":\"aws-load-balancer-controller-sa\",\"namespace\":\"kube-system\",\"labels\":{\"app.kubernetes.io/name\":\"aws-load-balancer-controller-sa\"},\"annotations\":{\"eks.amazonaws.com/role-arn\":\"",
              {
                "Fn::GetAtt": [
                  "eksew1examplesdevawsloadbalancercontrollersaRoleDEF3A580",
                  "Arn"
                ]
              },
              "\"}}}]"
            ]
          ]
        },
        "ClusterName": {
          "Ref": "eksew1examplesdev5DD40DC9"
        },
        "RoleArn": {
          "Fn::GetAtt": [
            "eksew1examplesdevCreationRoleCC0AC43C",
            "Arn"
          ]
        }
      },
      "DependsOn": [
        "eksew1examplesdevKubectlReadyBarrier9B0E220B"
      ],
      "UpdateReplacePolicy": "Delete",
      "DeletionPolicy": "Delete",
      "Metadata": {
        "aws:cdk:path": "EksFargateStack/eks-ew1-examples-dev/aws-load-balancer-controller-sa/manifest-aws-load-balancer-controller-saServiceAccountResource/Resource/Default"
      }
    },
```

**Comment by iliapolo** [comment]
@kishoreallwynraj Apologies for the late response.

> Unhandled exception. Amazon.JSII.Runtime.JsiiException: No child with id: 'manifest-aws-load-balancer-controller-saServiceAccountResource'

Indeed, turns out my workaround wasn't accurate, you should use:

```ts
var albControllerServiceAccountManifestResource = albControllerServiceAccount.Node.FindChild("manifest-aws-load-balancer-controller-saServiceAccountResource");
```

> Based on the error i think it expects few labels/annotations to be present on the ServiceAccount which i created. But i am not sure how i can add these labels/annotations to the ServiceAccount to see if this resolves the issue.

Unfortunately this isn't supported yet, i've created a feature request to allow passing custom labels to the service account.

https://github.com/aws/aws-cdk/issues/11801

Regarding the values, are you sure the values are not being passed? I've tested this locally with some debug logs and see they are being processed.

```ts
cluster.addHelmChart('dashboard', {
  chart: 'kubernetes-dashboard',
  repository: 'https://kubernetes.github.io/dashboard/',
  values: {
    Foo: 'Bar',
  }
});
```

```console

2020-12-01T12:06:46.170+02:00 | [INFO] 2020-12-01T10:06:46.170Z 4a4cba31-2e9d-41f5-babd-dfd57b47ecb7 Here are the values:
-- | --
  | 2020-12-01T12:06:46.187+02:00 | [INFO] 2020-12-01T10:06:46.187Z 4a4cba31-2e9d-41f5-babd-dfd57b47ecb7 {
  | 2020-12-01T12:06:46.187+02:00 | "Foo": "Bar"
  | 2020-12-01T12:06:46.187+02:00 | }

[INFO] 2020-12-01T10:06:46.187Z 4a4cba31-2e9d-41f5-babd-dfd57b47ecb7 Here is the command: helm upgrade issue11475clusterchartdashboardb61297b6 kubernetes-dashboard --install --create-namespace --repo https://kubernetes.github.io/dashboard/ --values /tmp/values.yaml --namespace default --kubeconfig /tmp/kubeconfig
--
```

Can you share the CloudFormation template fragment for the Chart resource? 

Thanks

**Comment by kishoreallwynraj** [comment]
I will make the changes and test again and share the CloudFormation template

**Comment by frankyhun** [comment]
I'm not sure, but looks a bit ambiguous, that somewhere SENTRY_DSN environment value is written, in somewhere sentry.dsn, in the yaml it is in sentry: dsn: <url> format. Which one is the used one?

**Comment by ffranco-audora** [comment]
I was having the same problem (in typscript). It turned out the values should be passed as an object:
```typescript
cluster.addHelmChart('AWS LoabBalancer Controller', {
  repository: 'https://aws.github.io/eks-charts',
  chart: 'aws-load-balancer-controller',
  namespace: 'kube-system',
  values: {
    'clusterName': cluster.clusterName,
    serviceAccount: {
      create: false,
      name: lbControllerSa.serviceAccountName
    }
  }
});
```
