### ISSUE TITLE
[Cognito] Configuration

### ISSUE THREAD

**Issue by StuartScott5** [aws/aws-cdk#11473]
### The Question
Hi, I am trying to fully automate the generation of my Cognito accounts but have an issue with setting the Identity Pool, Authentication providers, Authenticated Role. I wish to set this to 'Choose Role from Token' instead of the default 'Use default role' (as per attached screen shot). Is it possible to configure this some how?

### Environment

  - **CDK CLI Version:**  1.66.0 (build 459488d)
  - **Module Version:** 
  - **Node.js Version:**  v14.4.0
  - **OS:**  Windows 10 with Ubuntu 20.04 LTS
  - **Language (Version):**  3.9.7
![Change Default Role](https://user-images.githubusercontent.com/46883665/99145267-440a2500-2665-11eb-8a42-8b96ae651e7c.jpg)

**Comment by michaeljpeake** [comment]
@StuartScott5 Hi. I would also love this ability. Did you get anywhere with it?

**Comment by NGL321** [comment]
Hey @StuartScott5!

Thanks for submitting this request. From what I can tell, there is no L2 implementation for Cognito `IdentityPool`s. Unfortunately this means that any customizations to change this segment of the construct library will require fully developing the L2 components for `IdentityPool`s (and this may take some time).

That said, I am not certain that this is impossible with just the existing Cloudformation components. The [`CfnIdentityPoolRoleAttachment`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cognito.CfnIdentityPoolRoleAttachment.html) construct (cfn docs [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-identitypoolroleattachment.html)) allows you to set role mappings and roles for a [`CfnIdentityPool`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cognito.CfnIdentityPool.html). This should allow discrete selection of role. Is this the functionality you are looking for?

😸 😷

**Comment by vumdao** [comment]
2 years later but we still have not have this ability
