### ISSUE TITLE
[sam] Serverless function Apigateway proxy event - Authoriser override

### ISSUE THREAD

**Issue by jackmcguire1** [aws/aws-cdk#11480]
Hi

It appears the Apigateway event for serverless function resources does not support the ability to provide a value to override an assigned authoriser, as is possible in raw SAM cloud formation for  serverless functions.

### Reproduction Steps
Apply an Apigateway proxy event to a aws_sam.CfnFunction, you are not able to provider an authoriser value

### What did you expect 
The ability to apply an authorisation override of NONE to the apigateway proxy serverless function event

### What actually happened?

Option not available 

### Environment

  - **CDK CLI Version  : 1.72.0**
  - **Framework Version:1.72.0**
  - **Language (Version):Python**

### Other

Therefore this means that serverless functions with an HTTP Options api gateway method cannot be assigned to not have the authoriser applied, thus resulting in authorisation access for my publicly available API

Afaik there’s mention of L1 of the aws-Sam cloud formation, but this option should be supported within CDK

Also The get secrets And pinpoint Sam policies do not seem to be supported either 🤡 

--- 

This is :bug: Bug Report

**Comment by njlynch** [comment]
I suspect this is a duplicate of #7493, which in short, is a tracking issue for the fact that the SAM resources in the CDK are out of date and we have no programmatic means of updating them. 

Can you share an example of what the raw SAM for this would look like? That would help to confirm the above theory.
