### ISSUE TITLE
[eks] eks.Cluster.fromAttributes: Allow adding aws managed and self managed nodegroups to the imported cluster. 

### ISSUE THREAD

**Issue by rameshmimit** [aws/aws-cdk#11482]
We are in process of automating our EKS infra using CDK. We have lot of clusters and nodes already running in production that we are planning to move them to CDK. However because CDK does not support adding capacity(aws managed and self managed) nodegroups to the imported cluster, we are kinda blocked. Can we request you to add support for adding capacity to imported cluster as well, just like the standard addAutoScalingGroupCapacity, addNodegroupCapacity and addFargateProfile methods. 

### Use Case
Trying to use existing EKS production clusters using CDK.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by markus7811** [comment]
I am creating a new issue for some strange behavior of the nodegroups. For me, it's no problem adding managed nodegroups to imported clusters - but adding managed nodegroups with crossing the stack border is a problem.

I add managed nodegroups with the constructor of managed nodegroup... (so maybe this is a workaround for you?)

**Comment by markus7811** [comment]
@see https://github.com/aws/aws-cdk/issues/11810
