### ISSUE TITLE
[lambda-nodejs] Accept a user-defined bundler in NodejsFunctionProps

### ISSUE THREAD

**Issue by Garethp** [aws/aws-cdk#11492]
I'd like to be able to pass in an instance of `cdk.ILocalBundling` into `NodejsFunctionProps` rather than having to use the default implementation

### Use Case

I've created a Webpack implementation of `cdk.ILocalBundling` and would like to use this rather than `parcel` or the upcoming `esbuild` without losing the extra functionality of `NodejsFunction`.

### Proposed Solution

I'd like to be able to call `NodejsFunction` like this:

```ts
new NodejsFunction(
      this,
      "getRegistrationFunction",
      {
        entry: "src/lambda/get-registration/index.ts",
        handler: "handler",
        bundler: webpackBundler
      }
);
```

Where `webpackBundler` is an instance of `cdk.ILocalBundling`. The `webpackBundler` would then get passed into the `Bundling` class to be used when it calls `lambda.Code.fromAsset`, that way it can keep all the benefits of both `NodejsFunction` and `Bundler`

### Other

* [x] :wave: I may be able to implement this feature request
If this is approved, I'd be happy to try and create a PR for it

---

This is a :rocket: Feature Request

**Comment by eladb** [comment]
Copy @jogold

**Comment by eladb** [comment]
@Garethp I imagine most of the code in lambda-nodejs is very parcel-specific. You could simply use the @aws-cdk/lambda module directory and specify custom bundling when you define the asset:

```ts
new lambda.Function(this, 'foo', {
  code: lambda.Code.fromAsset('foo/bar', {
    bundling: {
      // << HERE
    }
  })
});
```

@jogold what do you think? Would it make sense to somehow generalize the bundler in lambda-nodejs to allow users to provide a different bundler? Is that reasonable?

**Comment by Garethp** [comment]
@eladb I think there's a surprising amount of non-parcel specific code that could be beneficial to any bundling software. That being said, I recognize that there's still effort in making what needs to be made generic, generic as well as effort in maintenance. If you're happy with this being a feature to take forward, I'm happy to put the effort in to make the PR

**Comment by jogold** [comment]
We can of course discuss how we can make `@aws-cdk/aws-lambda-nodejs` more generic but have you tried the latest release with `esbuild` (v1.77.0)? Do you still see value in using webpack now? If yes, how about improving the current implementation to bring in those missing features?

**Comment by blimmer** [comment]
I stumbled upon this issue as I was looking to upgrade to 1.77+. The reason it would be useful for me to be able to fall back to `parcel` is due to a few package dependencies that `esbuild` does not support. Specifically, these two issues:

- https://github.com/winstonjs/logform/pull/117
- https://github.com/TooTallNate/node-bindings/issues/65

Since these packages don't natively support rollup, I don't think I can upgrade yet unless I figure out how to patch them for my lambda. Maybe there's some workaround to make `esbuild` work? I'd love to switch over - builds are much faster than with parcel.

**Comment by jogold** [comment]
@blimmer have you tried using the `nodeModules` prop? See https://github.com/aws/aws-cdk/blob/v1.78.0/packages/@aws-cdk/aws-lambda-nodejs/README.md#install-modules

**Comment by blimmer** [comment]
Ah, no I haven't. I just read the docs and that seems like something I can try out. Thank you!

**Comment by tonyharrison** [comment]
I think there is value for some in using webpack or being able to provide our own bundler (may or may not be webpack). Neither parcel 1 or esbuild use tsc. So no type checking, and limited support for decorators.

When there is only one bundler you are at the mercy of the opinions of it's maintainers, and often they have very controversial opinions as to what can be sacrificed in the name of performance / speed.

**Comment by Garethp** [comment]
So I understand the desire to get people to contribute to esbuild rather than just passing over it, but I think that misses the main point of what I was hoping for. For our team, we'd rather not maintain two different build systems over our TS stack (Front-end and backend), and we'd also rather not have our build system dictated by an upstream dependency. 

We've built our webpack config to work for us with various plugins that help to optimize our output and debugging tools for our use-case (Ignoring certain parts of TypeORM, having the right type of sourcemaps, having the right bundle analyzers when we want it). When we look at a tool like `NodeJSFunction` it looks fantastic but being locked into a specific build system is a definite downside.

That downside was even more prominent that when it came to trying to use it, I was unable to get parcel 2 working on our codebase and then it was decided to that NodeJSFunction would switch to esbuild instead. Not being able to use our existing build system and not having the certainty that NodeJSFunction will use the same build system one year down the line as it does now is a fairly large issue when it comes to adopting it.

In the end it's less about whether the implementation of esbuild **could** work for us with some tweaks and changes, but more about not **needing** to change our build system just to use NodeJSFunction in the first place.

**Comment by nbaillie** [comment]
@jogold @Garethp, Bring your Own Build System would be useful for me for the reasons that Garethp has outlined.
It would be good to have a layer of flexibility in the build system choice, letting other keep with their currently selected build system and to protect and plan for evolution and emerging/future build systems.
 
However, that said what you have done with lamda-nodejs is a fantastic addition to CDK especially when paired with cdk-pipelines, it takes a way a great deal of pain.

**Comment by eladb** [comment]
You can now use the low-level bundling mechanism in to devise your own build system.

See some details: https://aws.amazon.com/blogs/devops/building-apps-with-aws-cdk/
