### ISSUE TITLE
[cli] cdk init fails due to outdated ts-node dependency

### ISSUE THREAD

**Issue by lancearlaus** [aws/aws-cdk#11495]
### Description

CDK init fail due to an outdated ts-node dependency

### Reproduction Steps

`cdk init --language=typescript`

### What did you expect to happen?

Successful project initialization including module installation

### What actually happened?

Failed to resolve dependency. jest 26.6.3 picks up the new ts-node dependency (>= 9.0.0), which conflicts with version (^8.1.0) stated in package.json

```
...
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: ts-node@8.10.2
npm ERR! node_modules/ts-node
npm ERR!   dev ts-node@"^8.1.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peerOptional ts-node@">=9.0.0" from jest-config@26.6.3
npm ERR! node_modules/jest-config
...
```
### Environment

Versions: cdk: 1.73.0, node: 15.2.0

  - **CDK CLI Version  :** 1.73.0
  - **Framework Version:** 1.73.0
  - **Node.js Version:** 15.2.0

### Other

Upgrading ts-node dependency version to ^9.0.0 in package.json resolves the issue.

Is it also possible to upgrade the typescript version and node types?
```
npm outdated
Package       Current    Wanted   Latest
@types/node  10.17.27  10.17.27  14.14.7
typescript      3.9.7     3.9.7    4.0.5
```

**Comment by NetaNir** [comment]
Oh yes, this seems like it only breaks wit node `15.0.0` as it enforces the optional dependencies version requirements. Looking into it

**Comment by NetaNir** [comment]
https://github.com/aws/aws-cdk/pull/11567
