### ISSUE TITLE
interface EcsDeployActionProps missing Deployment timeout property

### ISSUE THREAD

**Issue by CONJAUMCGCG** [aws/aws-cdk#11500]
![image](https://user-images.githubusercontent.com/55720537/99300704-c92a4100-2801-11eb-9972-b50b60994084.png)

![image](https://user-images.githubusercontent.com/55720537/99300754-d9422080-2801-11eb-8f2d-f54005975207.png)

**Comment by skinny85** [comment]
Added in #11407.

**Comment by CONJAUMCGCG** [comment]
@skinny85 
I don't see it in 1.73.0
Was the change released?

**Comment by skinny85** [comment]
It will be released in the next version, `1.74.0` most likely.
