### ISSUE TITLE
[aws-rds] Generated RDS secret should include the r/o endpoint of a cluster

### ISSUE THREAD

**Issue by dirknilius** [aws/aws-cdk#11517]
The generated Secrets Manager secret for RDS should include the read replica endpoint when creating an Aurora cluster.

Currently it looks like this:

```js
{
  "dbClusterIdentifier": "some-databaseb269d8bb-f6wcexmxi29",
  "password": "somepass",
  "dbname": "theDbName",
  "engine": "postgres",
  "port": 5432,
  "host": "some-databaseb269d8bb-f6wcexmxi29.cluster-cpkrkch4psmq.eu-central-1.rds.amazonaws.com",
  "username": "aUserName"
}
```

### Use Case

When a application can make use of read replicas, it would be awesome to have the reader endpoint in the secret.

### Proposed Solution

This could be something like `readerHost` or whatever fits.

```js
{
  "dbClusterIdentifier": "some-database-xyz987",
  "password": "somepass",
  "dbname": "theDbName",
  "engine": "postgres",
  "port": 5432,
  "host": "some-database-xyz987.cluster-abc123.eu-central-1.rds.amazonaws.com",
   // notice the included `-ro`
  "readerHost": "some-database-xyz987.cluster-ro-abc123.eu-central-1.rds.amazonaws.com",
  "username": "aUserName"
}
```

---

This is a :rocket: Feature Request

**Comment by skinny85** [comment]
Hey @dirknilius ,

thanks for opening the feature request. But I'm afraid we don't control what gets written into the Secret; that's done by the [SecretTargetAttachment resource](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-secretsmanager-secrettargetattachment.html), and it's not customizable (unless I'm missing something).

@jogold do you maybe know anything about customizing the fields SecretTargetAttachment writes?

Thanks,
Adam

**Comment by dirknilius** [comment]
Ah ok, I see. Didn't know that. Seems you are right, there seems to be no customization. Maybe I will file a feature request via Enterprise Support upstream.

**Comment by BDeus** [comment]
I have the same usecase.
I will ask for a feature request too

**Comment by aprat84** [comment]
@dirknilius @BDeus  any news on that?

**Comment by calvinwyoung** [comment]
We'd also love this!
