### ISSUE TITLE
[aws-lambda] Ability to modify the PYTHONPATH

### ISSUE THREAD

**Issue by davidbeers** [aws/aws-cdk#11525]
A new lambda runtime setting that enables setting of environment variables that must be set before the runtime starts if they are to take meaningful effect (e.g. PYTHONPATH)

### Use Case

Since the summer of 2020 it has been possible to attach an EFS volume to a Lambda. One of the compelling reasons to do this is for Python lambda handlers with library dependencies (like pytorch) that are too large to install even with the help of a Layer. However, to import libraries residing on an attached filesystem the PYTHONPATH env var must be modified to include that directory. If I try to set the PYTHONPATH in the Lambda definition it is modified only after the Python runtime has started, so it has no effect. The result is that to use the EFS volume for these dependencies I have to append a hard-coded path in every single module that uses one of these dependencies. It's very difficult to write modular, portable code that references this kind of detail about the host system hard-coded.

### Proposed Solution

One possible workaround might be to create a custom runtime exactly like the pre-built runtimes except for setting the PYTHONPATH. But this is an awful lot of work to accomplish a simple modification of the python path, which is a common use case. 

What would be much better is to have a runtime setting for environment variables that need to be set _before_ the runtime is started. Maybe call it something like `bootstrap_environment` to distinguish it clearly from the `environment` settings. 

![image](https://user-images.githubusercontent.com/4521507/99437542-d9a8ed00-28cf-11eb-8b58-b9debc4b511f.png)

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by nija-at** [comment]
> What would be much better is to have a runtime setting for environment variables that need to be set before the runtime is started.

Given that the start up of the runtime is done on the lambda service, how do you propse the CDK achieve this via just configuration? Is there a configuration that the lambda service provides that we can hook into the bootstrap environment?
