### ISSUE TITLE
[aws-ecs][aws-secretsmanager] Secret lookup fails if the secret is looked up by name and has a `-` in the name

### ISSUE THREAD

**Issue by ltamrazov** [aws/aws-cdk#11526]
It appears that when I try to pull an existing secret using `fromSecretNameV2` and pass it to `secrets` in ecs using `ecs.Secret.fromSecretsManager`, if the secret has a `-` character in the name, container is not able to identify the secret and returns a 400. This works in the exact same setup if the secret has no `-`. 

### Reproduction Steps

```javascript
const creds = secretsmanager.Secret.fromSecretNameV2(
  this,
  'someID,
  'my-name-with-dash', // my/name-with-dash doesn't work either, jwt/myNameWithoutDash works
);
creds.grantRead(this.executionRole);

const secrets = {
  MY_SECRET: ecs.Secret.fromSecretsManager(creds)
}

const taskDef = ...
const container = taskDef.addCOntainer('name', { secrets })

// ... launch fargate cluster
```

### What did you expect to happen?
Expect the secrets to be passed securely to the container and made available there.

### What actually happened?
The service failed to start with error: 
`Fetching secret data from AWS Secrets Manager in region us-east-1: secret arn:aws:secretsmanager:us-east-1:172456244520:secret:my-name-with-dash: ResourceNotFoundException: Secrets Manager can't find the specified secret. status code: 400, request id: 92e16bc3-a734-441e-ba39-64faaf48cc9e;`

### Environment

  - **CDK CLI Version  : 1.73
  - **Framework Version:**
  - **Node.js Version:** 14.14
  - **OS               :** Docker Alpine run on MacOS BigSur
  - **Language (Version):** Typescript 3.9

### Other
I'm wondering if it has to do with the fact that the random suffix on aws arn is separated by a dash? When we look up the secret by name that suffix is missing, as discussed here: https://github.com/aws/aws-cdk/issues/6889

Maybe if its missing but the secret has a dash it in, the arn lookup becomes ambiguous somehow? Just a guess.

--- 

This is :bug: Bug Report

**Comment by njlynch** [comment]
Hmm.. This sounds like it's possibly SecretsManager itself returning the `ResourceNotFoundException`. If you call the `DescribeSecrets` API with that same ARN, does it work or return the same error?

```sh
aws secretsmanager describe-secret --secret-id arn:aws:secretsmanager:us-east-1:172456244520:secret:my-name-with-dash
```

If your secret name was actually `my-name-with-dashes` -- or ending with any other 6-character word -- I'd expect this behavior. Secrets Manager behaves strangely when specifying partial ARNs for secrets that end with a hyphen and six characters. From their [docs](https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_DescribeSecret.html#SecretsManager-DescribeSecret-request-SecretId):

> However, if your secret has a name that ends in a hyphen followed by six characters (before Secrets Manager adds the hyphen and six characters to the ARN) and you try to use that as a partial ARN, then those characters cause Secrets Manager to assume that you’re specifying a complete ARN. This confusion can cause unexpected results. To avoid this situation, we recommend that you don’t create secret names ending with a hyphen followed by six characters.

If the above is the case, then I'm afraid you won't be able to use `fromSecretName(v2)` with ECS. Either re-create the secret so the name doesn't end with a six-character suffix, or use the full ARN to import it.

If it's *not* the case that your secret ends with a 6-character suffix, please let me know and we'll see if there's anything else that can be done.

**Comment by ltamrazov** [comment]
@njlynch thank you for the quick response. You're right, I can confirm that it only fails if the secret ends with dash followed by exactly 6 characters. I've tested with both dash followed by <6 chars and dash followed by >6 chars, and no errors in that case. Closing this since its known and expected behavior. Thank you again for your time!

**Comment by andrew-property-xyz** [comment]
Wow. I've wasted several days trying to understand why my secret cannot be found and it turns out to be due to, I'm sorry to say, an incredibly poor implementation by AWS. "Sorry folks, if your secret name ends with a hyphen followed by 6 characters, you're out of luck, try 5 characters or maybe 7 characters." Really?! Are you serious?

**Comment by joepagan** [comment]
On a similarly idiotic note, when following the pattern for the ARN which I typed into my TD json: [`arn:aws:secretsmanager:region:aws_account_id:secret:secret_name-AbCdEf`](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/specifying-sensitive-data-secrets.html#secrets-examples) from the docs, note that AWS generates the last 6 characters of the ARN.

I thought the example `secret_name-AbCdEf` was simply the "secret name", but it isn't.

**Comment by rodrigomata** [comment]
This just happened to me as well, I was retrieving a secret with `Secret.fromSecretNameV2()` and it kept failing as I thought it was something bad on my implementation, then I arrived at this thread, changed my secret from `test-user` to `testuser` and suddenly the deployment succeeds! I'm using the latest version of `aws-cdk-lib` so this **is still a bug**.

**Comment by dmytrokosiachenko** [comment]
This bug is still there, please reopen and fix it.
