### ISSUE TITLE
[core] Only One Stack per Stacksynthesizer possible?

### ISSUE THREAD

**Issue by markus7811** [aws/aws-cdk#11528]
In my testcases i saw the behaviour, that only one stack per stack synthesizer is possible. If I create more than one stack per app with the same synthesizer, only the last stack is known to cdk.

### Reproduction Steps

```
new Stack1(app, 'Stack1', {
    env: ENV,
    synthesizer: SYNTHESIZER,
});

new Stack2(app, 'Stack2', {
    env: ENV, 
    synthesizer: SYNTHESIZER,
});

cdk list 

Stack2
```

Removing the synthesizer from one of the stacks I can see both stacks ...

Further investigations:

**The problem is that I'm reusing the same synthesizer for several stacks. Using different objects (with the same content) as stack synthesizers works like expected. So I'm not sure if this is a bug?**

### What did you expect to happen?

I expected to see all Stacks ...

### What actually happened?

I only see the last stack defined per Synthesizer

### Environment

cdk 1.73.0

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
It's how these objects currently behave. One could consider it a bug, and I feel you that this could have been checked.

But I agree with you that it's worth addressing. I think I might have an idea for it.

**Comment by rix0rrr** [comment]
Well unfortunately this is no longer fixable without breaking backwards compatibility :(.
