### ISSUE TITLE
[aws-ecs-patterns] UDP support for NLB patterns

### ISSUE THREAD

**Issue by jamesholmes-linktree** [aws/aws-cdk#11535]
UDP support for NLB patterns such as NetworkLoadBalancedFargateService

### Use Case

As Fargate now supports NLBs using UDP (for things like log collection, IoT etc) we'd like to make use of this via CDK deployments.

### Proposed Solution

Add a protocol selection (TCP/UDP) to go with the containerPort in taskImageOptions and listenerPort in the service props.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by MaartenUreel** [comment]
For anyone looking for a workaround with escape hatches, assuming `service` is your `NetworkLoadBalancedFargateService`, you can do something like this:

```python
service = NetworkLoadBalancedFargateService(...)

# Update the default port mapping to be UDP
td = service.task_definition
td.node.default_child.add_override(
        "Properties.ContainerDefinitions.0.PortMappings.0.Protocol", "udp"
)

# Override target group to be UDP/5060
tg = service.target_group.node.default_child
tg.add_override("Properties.Protocol", "UDP")
tg.add_override("Properties.Port", 5060)

# Override the NLB protocol to be UDP
service.listener.node.default_child.add_override("Properties.Protocol", "UDP")
```

In my example I was exposing a service on UDP port 5060.

Don' forget to add a port mapping to make the health check work, since that cannot be on UDP, e.g.:

```python
td.default_container.add_port_mappings(
    PortMapping(container_port=PORT_HEALTH, protocol=Protocol.TCP)
)
```

**Comment by AMGI-Pipeline** [comment]
Please enable nlb UDP Fargate tasks with CDK!   I need this!
