### ISSUE TITLE
[api-gateway] typo: extraneous close paren

### ISSUE THREAD

**Issue by ekeyser** [aws/aws-cdk#11533]
https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-apigateway/README.md
https://docs.aws.amazon.com/cdk/api/latest/docs/aws-apigateway-readme.html

Typo: Line 586 - too many closing parens
(code snippet for mutual TLS, `bucket` param)

---

This is a 📕 documentation issue

**Comment by ekeyser** [comment]
7 days to remove a paren?

**Comment by nija-at** [comment]
You are free to submit a PR with the correct changes. Take a look at our contributing guide at CONTRIBUTING.md.

**Comment by ekeyser** [comment]
Haha. I think you're confused about who the customer is in this instance, bro.

**Comment by RomainMuller** [comment]
Submitted a PR with the fix for this typo.

---

As an aside - we expect **all** contributors to follow the [Open Source at AWS Code of Conduct](https://aws.github.io/code-of-conduct).

**Comment by ekeyser** [comment]
I absolutely agree. I would suggest communicating that code of conduct document specifically regarding welcoming language to your Amazon employed engineers who passive aggressively respond to contributions in the form of feedback and documentation issues and who do so on  their own time. Just a suggestion.
