### ISSUE TITLE
[aws-events] Support AWS::Event::Archive

### ISSUE THREAD

**Issue by baxang** [aws/aws-cdk#11531]
The package https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/aws-events does not have Archive  which was recently added.

- https://aws.amazon.com/blogs/aws/new-archive-and-replay-events-with-amazon-eventbridge/
- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-archive.html

### Use Case

The resources are 

### Proposed Solution

I propose implementing constructs for the aforementioned resources. The implemented construct would look like:

```typescript
const eventBus = new events.EventBus(this, 'MyEventBus', { eventBusName: 'my-event-bus' });
new events.Archive(this, 'EventArchive', {
  description: string,
  eventBus: eventBus,
  retention: cdk.Duration.days(10),
  eventPattern: { /* JSON */ },
});
```

Meanwhile, there's a workaround using `cdk.CfnResource` as the CDK documentation suggests
- https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html

```typescript
new cdk.CfnResource(this, 'EventArchive', {
      type: 'AWS::Events::Archive',
      RetentionDays: 30,
      SourceArn: `arn:aws:events:${this.region}:${this.account}:event-bus/default`
});
```

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by DaWyz** [comment]
We could also add an archive method on the `EventBus` itself (and available as part of the `IEventBus` interface since it's a separate resource and could be added on an imported resource) since it's the only resource it can be applied to.

```ts
const eventBus = new events.EventBus(this, 'MyEventBus', { eventBusName: 'my-event-bus' });

eventBus.archive({
  description?: string, // Should have a generated default
  retention: cdk.Duration.days(10), // Should have a default retention
  eventPattern: { /* JSON */ },
});
```
