### ISSUE TITLE
[dynamodb]  missing metricSystemErrorsForOperations in ITable

### ISSUE THREAD

**Issue by abragx** [aws/aws-cdk#11541]
metricSystemErrorsForOperations is missing in dynamodb.ITable

### Reproduction Steps

> See comment below 

look here in ITable definition

### What did you expect to happen?
the method is there

### What actually happened?
the method is not there

### Environment

  - **CDK CLI Version  :**  1.74.0
  - **Framework Version:** 
  - **Node.js Version:** 10.19.0
  - **OS               :** ubuntu
  - **Language (Version):** TypeScript

This is :bug: Bug Report

**Comment by robertd** [comment]
@abragx Can you please paste the code on how to reproduce this error?

I'm getting the `metricsSystemErrorsForOperations` method to show up on my table object.

![image](https://user-images.githubusercontent.com/31543/99557367-d53c0d00-297f-11eb-9703-d0c7569c12bd.png)

**Comment by abragx** [comment]
yes, but I am talking about the interface

![image](https://user-images.githubusercontent.com/66669919/99645038-fcaddb00-2a4e-11eb-927f-d1a5d3b3f652.png)

**Comment by SomayaB** [comment]
@abragx The `metricSystemErrorsForOperations` method only exists as a method of the class [Table](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-dynamodb.Table.html#metricwbrsystemwbrerrorswbrforwbroperationsprops) and not the [ITable](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-dynamodb.ITable.html#interface-itable) interface.

**Comment by abragx** [comment]
I know, that's why I raised the bug report.

**Comment by skinny85** [comment]
@abragx this should be a simple fix by adding the `metricSystemErrorsForOperations` method to the `ITable` interface (the implementation is already in the correct `TableBase` class). Would you mind submitting us a PR with the fix? Here's our Contributing guide: https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md .

Thanks,
Adam
