### ISSUE TITLE
[bootstrap] bootstrap-template.yaml does not pass cfn-lint checks

### ISSUE THREAD

**Issue by scarytom** [aws/aws-cdk#11545]
I am deploying my CDK bootstrap via an automated CI pipeline that performs cfn-lint checks on all templates.  Those checks fail for the current template.

### Reproduction Steps

cfn-lint --info --include-experimental packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml

### What did you expect to happen?

cfn-lint is successful and returns zero

### What actually happened?

W3011 Both UpdateReplacePolicy and DeletionPolicy are needed to protect Resources/StagingBucket from deletion
cdk.template.yml:141:3

E3012 Property Resources/CdkBootstrapVersion/Properties/Value should be of type String
cdk.template.yml:391:7

### Environment

  - **CDK CLI Version  :**
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):** 

### Other

I will put a couple of pull requests against this issue for the required fixes.  It would be nice to also add an automatic lint check of this template to the aws-cdk build pipeline, but I'm not sure how to do that.

--- 

This is :bug: Bug Report

**Comment by scarytom** [comment]
Not sure if you want those two pull requests combined into a single one, or if you want to iterate on them individually.

Both seem to failing checks that insist on a modification to a test.  I'm not sure what tests you have for this template.

**Comment by PatMyron** [comment]
linking general issue for context: https://github.com/aws/aws-cdk/issues/5309
