### ISSUE TITLE
(logs): delete associated log group when stack is deleted

### ISSUE THREAD

**Issue by duarten** [aws/aws-cdk#11549]
When the log group of a Lambda function is created by the LogRetention custom resource, then those log groups linger after the stack has been deleted. It should be possible to configure the removal policy.

### Use Case

Not having hundreds of dead log groups around, created for PR and test deployments.

### Proposed Solution

This requires setting the `deletionPolicy` on the `CfnResource`, and implementing support for the "Delete" event type in the custom resource itself.

### Other

_N/A_

* [X] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by nija-at** [comment]
We could add this feature on the [`LogRetention`](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-logs/lib/log-retention.ts) construct and [updating the handler with the `Delete` event](https://github.com/aws/aws-cdk/blob/b16a8d3079d1d293ce127d616f82b54cb869f2e5/packages/%40aws-cdk/aws-logs/lib/log-retention-provider/index.ts#L61-L66).

Note that, the default must be to retain the logs.

**Comment by jagregory** [comment]
This would be a really useful feature. I'm creating a lot of temporary stacks for automated testing in CI, and it's leaving behind lots of log groups.

**Comment by wswoboda** [comment]
agreed, for the same reason as jagregory

**Comment by kornicameister** [comment]
I am tempted to give it a shot. Recently been playing with cdk internals to learn a bit more and this particular use case is close to my heart as well. Not promising anything, but will certainly play with it.

**Comment by FilipPyrek** [comment]
+1

Sorry, I'm new to CDK universe (but not to CloudFormation).

**Does anybody know why does the log group needs to be created by custom resource?** I've successfully accomplished this without need for any custom resources in CloudFromation/Serverless Framework in the past.

**Comment by mlafeldt** [comment]
> Does anybody know why does the log group needs to be created by custom resource?

It creates the log group to be able to set the retention time. Otherwise, the log group will only be created once a Lambda logs something - with no expiry date set.

**Comment by FilipPyrek** [comment]
@mlafeldt you can create the log group inside CloudFormation and set it retention as parameter.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-loggroup.html#cfn-logs-loggroup-retentionindays

And then when the stack gets removed, it removes also the log group.

But it's true that I remember some case, when lambda executed during stack removal and in the meantime the log group was removed, but since there was a little delay before cloudwatch delivered the logs, it created a new log group with "Never expire" retention.

So maybe it's trying to address this issue. 🤷‍♂️

**Comment by mlafeldt** [comment]
> @mlafeldt you can create the log group inside CloudFormation and set it retention as parameter.

Yes, that's what I do if I truly care about cleanup.

Most of the time I do not and `LogRetention` is just more convenient.

**Comment by mlafeldt** [comment]
PS: A friend of mine recently released https://github.com/itmettkeDE/lambda-delete-unnused-aws-loggroups, which cleans up Lambda and CodeBuild logs.

**Comment by shishkin** [comment]
> We could add this feature on the [`LogRetention`](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-logs/lib/log-retention.ts) construct and [updating the handler with the `Delete` event](https://github.com/aws/aws-cdk/blob/b16a8d3079d1d293ce127d616f82b54cb869f2e5/packages/%40aws-cdk/aws-logs/lib/log-retention-provider/index.ts#L61-L66).

Yes, `LogRetention` needs a `RemovalPolicy` that when set to `DESTROY` would delete the log group.

**Comment by RomainMuller** [comment]
@shishkin but then what'll delete the LogRetention's backing lambda function's log group after it gets deleted? 🤓

**Comment by shishkin** [comment]
> @shishkin but then what'll delete the LogRetention's backing lambda function's log group after it gets deleted? 🤓

If LogRetention lambda is a singleton resource its single log group is lesser evil than log groups created for each user lambda.

And if it is a singleton resource with a known log group name, maybe another custom resource could delete it as part of the stack deletion? And if that resource lacks CloudWatch permissions it would not leave behind any own logs 🤔

**Comment by greensmith** [comment]
> And if it is a singleton resource with a known log group name, maybe another custom resource could delete it as part of the stack deletion? And if that resource lacks CloudWatch permissions it would not leave behind any own logs

Maybe I'm completely missing something here but I'm not sure why we should be so reliant on Cfn custom resources for everything. Why can we not handle this post-destroy? 

Can we keep track of what Cfn has deployed and any "possible" children (i.e. Lambda LogGroups) then present information on orphaned resources that are not removed during Cfn delete?

This would be useful in CI to just say during post-build teardowns "here's a list of possibly orphaned resources - delete them"

**Comment by TheFlow0360** [comment]
Creating a log group with the same name is a workaround:
```
const nodejsFunction = new NodejsFunction(this, id, {
  ...
});
new logs.LogGroup(this, `LogGroupLambdaFunction ${id}`, {
  retention: logs.RetentionDays.ONE_WEEK,
  logGroupName: `/aws/lambda/${nodejsFunction.functionName}`,
  removalPolicy: RemovalPolicy.DESTROY,
});
```

This, however, breaks other integrations with the custom resource like subscriptions. So a way to directly configure the RemovalPolicy would be better.

**Comment by greensmith** [comment]
Another alternative is changing policies on the role to deny log access , to stop them being created in the first place.
e.g. for BucketDeployment, if we're deploying/destroying multiple dev branches i'd rather not have to worry about going in and tidying up after a destroy than having 99/100 logs saying the zip contents were extracted successfully. 

```typescript
const BucketDeploymentHandler = this.bucketDeployment.node.findChild('CustomResourceHandler') as SingletonFunction;
        BucketDeploymentHandler.addToRolePolicy(new PolicyStatement({
            actions:['logs:*'],
            resources:['*'],
            effect: Effect.DENY
       })
)
 ```

**Comment by deloittepark** [comment]
> Another alternative is changing policies on the role to deny log access , to stop them being created in the first place. e.g. for BucketDeployment, if we're deploying/destroying multiple dev branches i'd rather not have to worry about going in and tidying up after a destroy than having 99/100 logs saying the zip contents were extracted successfully.
> 
> ```ts
> const BucketDeploymentHandler = this.bucketDeployment.node.findChild('CustomResourceHandler') as SingletonFunction;
>         BucketDeploymentHandler.addToRolePolicy(new PolicyStatement({
>             actions:['logs:*'],
>             resources:['*'],
>             effect: Effect.DENY
>        })
> )
> ```

Even if this issue is marked as closed, I want to share with you my working solution to delete LogGroup of CustomResources during stack deletion. and thanks to @greensmith the idea. 

Issue is related on CustomResource Constructor I guess. It creates CloudWatch log group for wrapper lambda. Even if I have defined a log group for the lambda explicitly (/aws/lambda/${lambdaFn.functionName}), this CustomResource Constructor overwrites my log group setting. (https://github.com/aws/aws-cdk/issues/8815)

Workaround is:
- define log group explicitly for your lambda function with removalPolicy and retention.
- attach role policy to your lambda that log:CreateLogGroup is denied.

```ts
declare const onEvent: lambda.Function;

onEvent.addToRolePolicy(new iam.PolicyStatement({
  actions:['logs:CreateLogGroup'],
  resources:['*'],
  effect: iam.Effect.DENY
}));

new logs.LogGroup(this, `${name}-log-group`, {
  logGroupName: `/aws/lambda/${onEvent.functionName}`,
  removalPolicy: RemovalPolicy.DESTROY,
  retention: logs.RetentionDays.ONE_DAY,
})
```

In this way, Lambda Wrapper will not be able to create/overwrite the same log group, but you are still keep logs in the log group that you have defined. This log group will be destroyed with your stack deletion together.

**Comment by gshpychka** [comment]
> Bump
> 
> This is a very important feature IMO

It has been implemented.

**Comment by albertodiazdorado** [comment]
Oh that's great. Thanks for letting me know @gshpychka !
