### ISSUE TITLE
[CodeArtifact] CfnRepository cannot be deployed (missing required CFN param DomainName)

### ISSUE THREAD

**Issue by troyready** [aws/aws-cdk#11569]
As of v1.74.0, a CodeArtifact Repository cannot currently be created because it's missing [the required DomainName parameter](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codeartifact-repository.html#cfn-codeartifact-repository-domainname). Using the `CfnRepository` resource generates an error:

```
Model validation failed (#: required key [DomainName] not found)
```
It looks like this is fixed in the WIP [L2 PR](https://github.com/aws/aws-cdk/issues/11090) in [commit 4489488](https://github.com/aws/aws-cdk/commit/4489488f4f108f44ab9d93cde7f2f97c27076fe2). It might be best to pull this out of the PR to get it included faster to make the basic CFN resources usable.

**Comment by NetaNir** [comment]
So the CloudFormation spec for CodeArtifact is missing properties? If so, we should submit an issue so they can fix it on the spec level. Their spec is open source, and hosted in the [cloudformation](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-codeartifact) repo.

**Comment by troyready** [comment]
I'm not super familiar with the CFN resource provider setup, but from what I can see it already [looks correct to me in the upstream repo](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-codeartifact/blob/40a7e316daad5886c73512cea97e1a419bdb4210/aws-codeartifact-repository/aws-codeartifact-repository.json#L96-L99), but that isn't reflected in the published spec.

**Comment by NetaNir** [comment]
One the spec is published it will imported to the aws cdk.
