### ISSUE TITLE
[api-gateway] Error with HttpAPI L2 construct

### ISSUE THREAD

**Issue by patapurv** [aws/aws-cdk#11564]
I am using escape hatch to provide open API 3.0 schema to the HTTP API construct. The code looks like below

```
        const httpAPI = new HttpApi(this, props.serviceName, {});
        const httpApiResource = httpAPI.node.defaultChild as apigatewayv2.CfnApi;
        httpApiResource.addPropertyOverride("body", swaggerDef);

        httpAPI.addStage(props.stage, {
            autoDeploy: true,
            stageName: props.stage
        });
```
This code throws property validation failure during deployment 

```

3:50:05 PM | CREATE_FAILED        | AWS::ApiGatewayV2::Api   | MyAwesomeHTTPAPICLE
Property validation failure: [Encountered unsupported properties in {/}: [body]]
3:50:06 PM | UPDATE_ROLLBACK_IN_P | AWS::CloudFormation::Stack | httpAPICLEStack
The following resource(s) failed to create: [MyAwesomeHTTPAPICLEB0988C6D].
```

If I use L1 construct directly I do not get the error. If I upload my open API 3.0 schema in AWS console, I do not get the error. I suspect there is some incorrect validation in the L2 construct.

Code for L1:
```
       const httpApi = new apigatewayv2.CfnApi(this, props.serviceName + "_HTTPAPI", {
            body: swaggerDef
        });

        new apigatewayv2.CfnStage(this, props.stage, {
           apiId: httpApi.ref,
           stageName: props.stage,
           autoDeploy: true
        });
```

### What did you expect to happen?

I expect the L2 construct to not fail, or if the failure is valid then I want the failure to be consistent across AWS console and L1 construct.

### What actually happened?
see above

### Environment

  - **CDK CLI Version  :**  1.71.0
  - **Framework Version:** 
  - **Node.js Version:**  v12.18.2
  - **OS               :** macOS Catalina 10.15.7
  - **Language (Version):**  Typescript

### Other

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
Unfortunately, we don't support mixing these two features. 
Using property overrides for a small flag works well, but for something like swagger template, you will have to use the L1s throughout.
