### ISSUE TITLE
[core] Tags of Construct cannot be applied

### ISSUE THREAD

**Issue by Meshonim** [aws/aws-cdk#11574]
Tags of custom Construct are not applied to inner resources

### Reproduction Steps

```
export class CustomFunction extends Construct {
  constructor(scope: Construct, bucket: IBucket, id: string) {
      super(scope, id);
      
      Tags.of(this).add("tagName", "tagValue");
  }
}

export class NewCustomFunction extends CustomFunction {
  constructor(scope: Construct, bucket: IBucket, id: string) {
      super(scope, bucket, id);

      const serviceHandler: lambda.Function = new lambda.Function(scope, "ServiceHandler", {
        runtime: lambda.Runtime.NODEJS_12_X,
        code: lambda.Code.fromBucket(bucket, "fake/code.zip"),
        handler: "index.handler"
      });
  }
}
```

### What did you expect to happen?

Tag ("tagName", "tagValue") in serviceHandler.

### What actually happened?

serviceHandler has no tags.

### Environment

  - **CDK CLI Version  :** 1.71.0
  - **Framework Version:**
  - **Node.js Version:**  12.14.1
  - **OS               :** Windows 10
  - **Language (Version):** TypeScript (4.0.3) 

### Other

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
```
      const serviceHandler: lambda.Function = new lambda.Function(scope, "ServiceHandler", {
```

Should have been `new lambda.Function(this, ...)`
