### ISSUE TITLE
Support for DataSync 

### ISSUE THREAD

**Issue by brachna9** [aws/aws-cdk#11570]
There is no CloudFormation support for AWS DataSync:
https://aws.amazon.com/datasync/

There is an existing feature request for this in CloudFormation as well:
https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/343

---

This is a :rocket: Feature Request

**Comment by SomayaB** [comment]
Hi @brachna9, thanks for opening an issue. Whenever a new resource or new prop is added to Cloudformation it is automatically added to the CDK in the following week or so. 
I will close this issue since it is not actionable from the CDK side until it is added to Cloudformation.
