### ISSUE TITLE
[ec2] keep getting vpc-12345 from vpc lookup

### ISSUE THREAD

**Issue by david2003542** [aws/aws-cdk#11576]
I created a stack and add in into codepipeline stage. Inside this stack I was using vpc lookup function as below
```
const vpc: ec2.IVpc = ec2.Vpc.fromLookup(this, "vpcId", {
            vpcId: "vpc-xxx"
        });

const sg = ec2.SecurityGroup.fromSecurityGroupId(this, 'SecurityGroup', 'sg-yyyyyy')
```
For some reason, I always got vpc-12345 from the template. I have no idea why.
However, In the security group section I can get the correct one.
Therefore, I believe they are using same props with same account and region 

For more detail, I do check the vpcId in the AWS console. It does exsist.

This is :bug: Bug Report

**Comment by hoegertn** [comment]
Are you trying to use CDK pipelines? They do not support lookups yet.
You have to synth locally once and commit the cdk.context.json to the repo. Then it should be picked up correctly.

**Comment by rix0rrr** [comment]
You are being affected by https://github.com/aws/aws-cdk/issues/11631.

What Thorsten suggests will work, assuming your CDK version has this commit in it: https://github.com/aws/aws-cdk/commit/a4a555a9f5e8844a377d8de5041219346d0eb65c (which will be the next release).

**Comment by maggoun** [comment]
> Are you trying to use CDK pipelines? They do not support lookups yet. You have to synth locally once and commit the cdk.context.json to the repo. Then it should be picked up correctly.

Hi, im also getting vpc-12345 when making the below call:

            var vpc = Vpc.FromLookup(this, canamVpc, new VpcLookupOptions()
            {
                VpcName = "MyVPC"

            });

will this be fixed to work in cdk codepipelines?
