### ISSUE TITLE
[codepipeline-actions] Support Github version 2 source actions

### ISSUE THREAD

**Issue by blimmer** [aws/aws-cdk#11582]
It looks like there's a newer version of CodePipeline source actions (v2) vs. the currently supported OAuth connection.

This [documentation](https://docs.aws.amazon.com/codepipeline/latest/userguide/appendix-github-oauth.html#GitHub-create-personal-token-CLI) has information on v1 vs. v2. From that page:

> While we don’t recommend using the GitHub version 1 action, existing pipelines with the GitHub version 1 action will continue to work without any impact. For a pipeline with a GitHub version 1 action, CodePipeline uses OAuth-based tokens to connect to your GitHub repository. By contrast, the GitHub action (version 2) uses a connection resource to associate AWS resources to your GitHub repository. The connection resource uses app-based tokens to connect. For more information about updating your pipeline to the recommended GitHub action that uses a connection, see Update a GitHub version 1 source action to a GitHub version 2 source action. For more information about OAuth-based GitHub access in contrast to app-based GitHub access, see https://docs.github.com/en/developers/apps/differences-between-github-apps-and-oauth-apps. 

### Use Case

I'm testing out CDK Pipelines, and noticed that the documentation link was broken ([PR to fix the link](https://github.com/aws/aws-cdk/pull/11584)). I'm happy to continue on with the oauth flow for now, but it looks like maybe v2 would be ideal moving forward.

### Proposed Solution

Perhaps a new `GithubSourceActionV2` property could provide a seamless way to upgrade without breaking existing users.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by skinny85** [comment]
Hey @blimmer ,

thanks for opening the issue. We actually already support that functionality, just in the unfortunately named `BitBucketSourceAction`. We have an open issue to change that name: #10632.

Thanks,
Adam

**Comment by blimmer** [comment]
Cool - thanks! Closing in favor of #10632.
