### ISSUE TITLE
[cli]  wrong umask on upgraded global modules

### ISSUE THREAD

**Issue by lschierer** [aws/aws-cdk#11580]
`sudo npm install -g aws-cdk`. installs with the wrong umask,  upgrades change to the wrong umask.
### Reproduction Steps

I had a working global `/usr/bin/cdk` command with `0.70`,  and I think `0.71`.  with `0.73` and `0.74`, the umask on `/usr/lib/node-modules/aws-cdk` and its children is changed to remove world read and execute bits, rendering the symlink in `/usr/bin/` inoperable.  Manually fixing it is reverted on the upgrade from `0.73` to `0.74`.
### What did you expect to happen?

upgrading my node modules should not break the symlinks in /usr/bin that were automatically generated to begin with. 

### What actually happened?

I'm working around this by using `npx cdk` instead of `cdk`

### Environment

I'm on a ubuntu focal machine with ubuntu's npm package. 

### Other

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
We didn't change anything here. This must all be `npm`. You should talk to them.
