### ISSUE TITLE
[aws-s3] Bucket OwnershipControls Support

### ISSUE THREAD

**Issue by relm-haven** [aws/aws-cdk#11591]
Support new Bucket Ownership Controls to ensure bucket owner owns all objects in the bucket

### Use Case
https://docs.aws.amazon.com/AmazonS3/latest/user-guide/add-object-ownership.html

Ensure proper object ownership after cross account writes

### Proposed Solution
`cdk.Bucket` to support passing `ownershipControls` to `CfnBucket`

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by saudkhanzada** [comment]
@relm-haven Can I pick this?

**Comment by saudkhanzada** [comment]
@relm-haven Can I take this up?

**Comment by relm-haven** [comment]
@saudkhanzada please do!

**Comment by saudkhanzada** [comment]
@relm-haven, Please suggest between these two approches:
1. Nested approach as followed by the API
```
      new s3.Bucket(stack, 'MyBucket', {
      ownershipControls: {
        rules: [{
          objectOwnership: s3.ObjectOwnership.BUCKET_OWNER_PREFERRED,
        }],
      },
    });
```
2.  Flat props and code will build the required object
```
    new s3.Bucket(stack, 'MyBucket', {
      ownershipControls: s3.ObjectOwnership.BUCKET_OWNER_PREFERRED,
    });
```

**Comment by relm-haven** [comment]
Approach 2 looks cleaner to me

I know CloudFormation supports a list of rules but what is the use case for more than one rule?

**Comment by cynicaljoy** [comment]
I'm not sure of the use case but I'd vote to retain the array to allow for such use cases now or in the future when those uses cases might reveal themselves:

```
new s3.Bucket(stack, 'MyBucket', {
    objectOwnership: [s3.ObjectOwnership.BUCKET_OWNER_PREFERRED]
});
```
