### ISSUE TITLE
[dynamodb] error when trying to create  a Global Table

### ISSUE THREAD

**Issue by Upasna22** [aws/aws-cdk#11593]
Hello,

I am trying to create a Global Table by setting the replicationRegions property on a Table in AWS CDK :
https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_dynamodb/Table.html  .

However, when i set replication_regions to `us-west-2`, i get an error as follows:
```console
raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: staging.relativeStagedPath is not a function
```

Please help me solve this.

### What actually happened?
```console
raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: staging.relativeStagedPath is not a function
```

### Environment

  - **CDK CLI Version  :**
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):** Python (3.7.3) 

### Other

--- 

This is :bug: Bug Report

**Comment by SomayaB** [comment]
Hi @Upasna22, thanks for opening an issue. Please provide minimal reproduction code that demonstrates the problem.
