### ISSUE TITLE
[stepfunctions-tasks] SageMakerUpdateEndpoint creates wrong permissions

### ISSUE THREAD

**Issue by cmwilhelm** [aws/aws-cdk#11594]
### The Question

There appear to be some incorrect permissions generated when using the `aws_stepfunctions_tasks.SageMakerUpdateEndpoint` construct in a state machine
created through CDK.

Specifically, the state machine role is granted a permission for `updateEndpoint` against
resource `"arn:aws:sagemaker:<REGION>:<ACCOUNT_ID>:endpoint/*"`. However, from
the error messages in my StepFn invocation, it appears the resource target should actually
be `endpoint-config/*`:

```json
{
  "resourceType": "sagemaker",
  "resource": "updateEndpoint",
  "error": "SageMaker.AmazonSageMakerException",
  "cause": "User: arn:aws:sts::<ACCOUNT_DI>:assumed-role/<STATE_MACHINE_NAME>-StateMachineRole<ROLE_ID> is not authorized to perform: sagemaker:UpdateEndpoint on resource: arn:aws:sagemaker:<REGION>:<ACCOUNT_ID>:endpoint-config/<ENDPOINT_CONFIG_NAME> (Service: AmazonSageMaker; Status Code: 400; Error Code: AccessDeniedException; Request ID: 3c22b7ab-4687-475a-b82c-643a75f21a13; Proxy: null)"
}
```

### Environment

We're currently pinned at CDK core and CDK module versions 1.72, using the python bindings.
However, I checked the release notes and did not see any mention of fixes since then to this stepfn task.

**Comment by NGL321** [comment]
From what I can tell from the SageMaker docs, they indicate the proper policies for [`CreateEndpoint`](https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_CreateEndpoint.html), but do not indicate for [`UpdateEndpoint`](https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_UpdateEndpoint.html). So I think it is fair to say that the policies for `UpdateEndpoint` should match those for `CreateEndpoint`.

At the moment, you are correct and `update-endpoint` only adds policy for `endpoint/*` not `endpoint-config/*` as docs would indicate:
https://github.com/aws/aws-cdk/blob/054610f8622796a2528b46a07571eb3a89730c84/packages/%40aws-cdk/aws-stepfunctions-tasks/lib/sagemaker/update-endpoint.ts#L62-L79

I can confirm this bug, and it should only be a 1 line fix!

😸 😷

**Comment by zxkane** [comment]
Any plan for fixing it or requiring someone contributing PR?

**Comment by shivlaks** [comment]
@zxkane happy to review it if you want to submit one! it's not currently on my radar but I can pick it up if nobody's interested 😅
