### ISSUE TITLE
[s3-deployment] AWS S3 Deployment is copying only partial file sometimes

### ISSUE THREAD

**Issue by amitksahu** [aws/aws-cdk#11598]
## :question: General Issue
is using  s3deploy.BucketDeployment, code snippet attached below. CDK version is 1.7.
```py
s3deploy.BucketDeployment(
    self,
    "ConfigDeployment",
    sources=[config_files],
    destination_bucket=config_bucket,
    destination_key_prefix=config_dir,
    role=xx_lambda_role
)
```
The zip file size is 9.5 MB, However it works in one AWS account & in the other account the file copied to S3 is only 4.9 MB instead of 9.5 MB . 

We have verified the same during screenshare with the Cx. 

We also tried copying it manually using AWS CLI & console . We were able to do it successfully.

### Environment

  - **CDK CLI Version:** 
  - **Module Version:** 
  - **Node.js Version:** 
  - **OS:** 
  - **Language (Version):**

**Comment by NGL321** [comment]
Hey @amitksahu,

I have as of yet been unable to reproduce this issue. I used the following code and successfully deployed the asset to the bucket intact. If you could provide me with full reproduction code that will generate the problem you describe I can investigate further.

```ts
export class S3DeptestStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const bucket = new s3.Bucket(this, "DepTestBucket");

    const sourceAsset = s3deploy.Source.asset('./test_asset.zip');

    new s3deploy.BucketDeployment(this, "ConfigDeployment", {
      sources: [sourceAsset],
      destinationBucket: bucket
    });
  }
}
```

😸 😷
