### ISSUE TITLE
(lambda): Lambda does not depend on IAM role 

### ISSUE THREAD

**Issue by RishiKapadia20** [aws/aws-cdk#11604]
### Description

When deploying a lambda function within a VPC with a custom IAM execution role, during deployment cloudformation can start creating the lambda function without the IAM role being fully provisioned. This is a problem because if the IAM role does not have the basic VPC execution policy attached by the time the lambda starts provisioning it will crash. This bug does not always happen, I think due to the varied latency within cloudformation the policy sometimes would have been attached to the role first before the lambda starts being provisioned.

### Reproduction Steps

minimal amount of code that causes the bug (if possible) or a reference:
My current codebase is using several high level constructs, however if you need further clarification I can create a simple code version of my problem

### What did you expect to happen?

What were you trying to achieve by performing the steps above?
I would expect cloudformation to wait for my lambda execution role to be provisioned with all policies before trying to provision lambda.

### What actually happened?

What is the unexpected behavior you were seeing? If you got an error, paste it here.
Cloudformation error:
AWS Lambda:The provided execution role does not have permissions to call CreateNetworkInterfaces on EC2

### Environment

  - **CDK CLI Version  :** 1.46.0
  - **Framework Version:** 1.64.0
  - **Node.js Version:** v12.6.0 
  - **OS               :** MacOS
  - **Language (Version):**  Python (3.7.4)

### Other

This stack is synthesised within codebuild and then deployed using cloudformation deploy stage within a codepipeline

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
Thanks for filing this bug.

You can workaround this using the `addDependency()` API.

```ts
lambda.node.addDependency(executionRole);
```
