### ISSUE TITLE
[core] Give all Resources and Outputs a property for condition

### ISSUE THREAD

**Issue by iDVB** [aws/aws-cdk#11607]
Just looking at the implementation for `CfnCondition` for the first time. 
Shouldn’t there be a way to pass in a condition in all resource instantiations? 
Otherwise, seems like an unneeded 2x lines per resource. 

**Additionally**, this could work for Outputs as well? Where the output doesn’t get created if the resource doesn't exist… 
OR also provide a property in Output creation that allows for a condition to be passed in?

Otherwise, this is the minimum code needed to create a single bucket, and related output conditionally...

```javascript
// Create Bucket...
const bucket = new s3.Bucket(this, 'Bucket')

// ...Conditionally
const cfnBucket = bucket.node.defaultChild as s3.CfnBucket
cfnBucket.cfnOptions.condition = isProd

// Create Output...
const outBucket = new cdk.CfnOutput(this, 'Bucket', { value: bucket.bucketName })

// ...Conditionally
const cfnOutBucket = outBucket.node.defaultChild as cdk.CfnOutput
cfnOutBucket.condition = isProd
```

### Use Case
Much less code
Easier to read

### Proposed Solution
What if you could just pass the condition into the resource instantiation?

```javascript
// Create Bucket...  ...Conditionally
const bucket = new s3.Bucket(this, 'Bucket', isProd)

// Create Output...  ...Conditionally
const outBucket = new cdk.CfnOutput(this, 'Bucket', { value: bucket.bucketName }, isProd)
```

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
We support conditions in case you MUST achieve parity with a pre-CDK template, but we recommend you put conditionals in code instead of in CFN templates. 

This is just not how we envision CDK to be used. You can if you want to, but it's not the encouraged path.
