### ISSUE TITLE
[assert] Non-specific stringLike() matching

### ISSUE THREAD

**Issue by aihaddad** [aws/aws-cdk#11619]
## :question: General Issue

https://github.com/aws/aws-cdk/blob/b96efd8aaa143845b9fe315a9ee1e8398c4d83c2/packages/%40aws-cdk/assert/lib/assertions/have-resource-matchers.ts#L246

### The Question
Why does `stringLike()` have to match exact strings? doesn't that defeat the "Like" or "Containing" point?

The RegEx pattern is modified for the matcher to match beginning-to-end. But, when I am testing values within a `Ref` or `Fn::GetAtt` or anything related to auto-generated logical IDs I shouldn't really care for the parts I did not input myself. Dropping the `$` at the end of the RegEx would probably make more sense, wouldn't it? 

Am I missing something?

### Environment

  - **CDK CLI Version:** 1.74.0 (build e86602f)
  - **Node.js Version:** v14.4.0
  - **OS:** all
  - **Language (Version):** TypeScript (4.1.2)

**Comment by peterwoodworth** [comment]
Sorry for the long response time here @aihaddad, I see that this is still the case https://github.com/aws/aws-cdk/blob/b1ecd3d49d7ebf97a54a80d06779ef0f0b113c16/packages/%40aws-cdk/assert-internal/lib/assertions/have-resource-matchers.ts#L244-L246

Seeing as it does require the strings to match,
> stringLike(S) - value must be a string matching S. S may contain * as wildcard to match any number of characters.
this probably isn't great convention. What would you propose renaming it to?

**Comment by peterwoodworth** [comment]
I'm closing this issue due to staleness. If you want to see this changed, please submit a feature request with your suggestion of what it should be called or submit a PR which fixes this 😄
