### ISSUE TITLE
[lambda-nodejs] Add option to use handler from layer

### ISSUE THREAD

**Issue by magidnadav** [aws/aws-cdk#11618]
Allow handler to point outside the index.js file.

### Use Case

I have a shared code in a lambda layer that wraps all my functions with monitoring and logging tools.
With NodejsFunction I cannot point the lambda handler to the layer.
I want an option to override the handler location to locations outside index.js.

### Proposed Solution

Modify OpsNodeLambdaProps to add a new parameter with a default value of False to prevent the following line ` handler: `index.${handler}`,`

### Other

* [X] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by jogold** [comment]
@magidnadav You mean that the Lambda handler should point to a location in `/opt`? Is this supported by Lambda? Thanks.

**Comment by magidnadav** [comment]
@jogold Yes It does, we just added the handler normally, and it looks also into /opt.
that would also apply to entry points defined to an installed package, not just layers.

**Comment by jogold** [comment]
Can you share an example? And what code are you bundling in this case?

**Comment by magidnadav** [comment]
@jogold I wrote a small CDK application to demonstrate my request. [link](https://cdk-issue-11618.s3-eu-west-1.amazonaws.com/issue-11618.zip)
Currently, in the layer, there isn't any "interesting" shared code.in our real layer, we have monitoring and logging tools.
and more common handler for ease of development.

**Comment by jogold** [comment]
@magidnadav I looked at your code. I'm sorry but still do not completely understand your request...

You would like to change/remove the line with `handler: 'index.${handler}'`, but (1) `handler` is a required property for a `lambda.Function` and (2) the bundler is configured to always output a file named `index.js` so it looks to me that we'll always have `index.<something>` there. What I am missing?

**Comment by magidnadav** [comment]
@jogold, what I want is the ability to manually set the `handler` property of the `lambda.Function` to be in a file that is not `index.js`. in my case, the handler function is located on a layer.

I still want the bundling to work with the original handler and to set the lambda handler to a different function.

**Comment by jogold** [comment]
> what I want is the ability to manually set the `handler` property of the `lambda.Function` to be in a file that is not `index.js`. in my case, the handler function is located on a layer.

Sorry for the late reply here. I don't think this is possible with Lambda. The `handler` prop must reference a file in the **code** (not a layer) and an export, e.g. `myFile.myExport`. @nija-at do you agree?

**Comment by nija-at** [comment]
AFAICT, that seems to be accurate. You will need to re-export the method from the layer in your handled code.

**Comment by magidnadav** [comment]
@jogold and @nija-at thanks for your time.
should I close this issue?

**Comment by danielbayerlein** [comment]
#16795
