### ISSUE TITLE
[aws-redshift] Number of nodes does not allow use of input parameter

### ISSUE THREAD

**Issue by chrispaulsantos** [aws/aws-cdk#11610]
Creating a redshift cluster does not allow a template input parameter to be used to set the number of nodes.

### Reproduction Steps

```typescript
import * as cdk from '@aws-cdk/core';
import * as redshift from '@aws-cdk/aws-redshift';
import * as ec2 from '@aws-cdk/aws-ec2';

export class CdkStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const vpc = new ec2.Vpc(this, 'vpc', {});

    const numberOfNodes = new cdk.CfnParameter(this, 'numberOfNodes', {
      type: 'Number'
    });

    const cluster = new redshift.Cluster(this, 'Redshift', {
      masterUser: {
        masterUsername: 'admin',
      },
      numberOfNodes: numberOfNodes.valueAsNumber,
      vpc
    });
  }
}

```

### What did you expect to happen?

A cloudformation parameter should be allowed to be used to pass the desired number of nodes.

### What actually happened?

```bash
$ cdk synth
Number of nodes for cluster type multi-node must be at least 2 and no more than 100
Subprocess exited with error 1
```

### Environment

  - **CDK CLI Version  :** 1.74.0
  - **Framework Version:** 1.74.0
  - **Node.js Version:** v12.18.3
  - **OS               :** macOS 11.0.1
  - **Language (Version):** Typescript 3.9.7

### Other

I have not tested this by hand writing the cloudformation template, but I feel this should be possible since at deploy time the value would get resolved and is only an issue because of the check located here: https://github.com/aws/aws-cdk/blob/d7ca5ca0fb714a716a269ecb2c69b85824253136/packages/%40aws-cdk/aws-redshift/lib/cluster.ts#L557-L559

Could have a global set of refs that have been created and on synth check the value against that set and ignore if it's a valid ref.

--- 

This is :bug: Bug Report

**Comment by njlynch** [comment]
This is common bug type (D'oh!) where a Token isn't validated before manipulating or comparing it.

The right fix here is to add a check to `Token.isUnresolved` at the top of `validateNodeCount`, and just return the `numberOfNodes` as-is if it is an unresolved token. This would be a great first issue for someone to pick up.

**Comment by chrispaulsantos** [comment]
Ah makes sense! I'd be happy to pick it up if that's ok

**Comment by njlynch** [comment]
@chrispaulsantos - Absolutely! Let me know if you need anything to get you started.

**Comment by chrispaulsantos** [comment]
Great thanks, I see the Contributing docs are there so I'll start there
