### ISSUE TITLE
[cloudformation] CfnDashboard's  dashboard_name doesn't work as expected when deploying

### ISSUE THREAD

**Issue by royby-cyberark** [aws/aws-cdk#11621]
description of the bug:
When using CfnDashboard to deploy cloudwatch dashboards, if you allow dashboard_name to be None so that dashboard name is generated, and if you try to use this value during deployment, for example to keep it as.a stack output, you get None instead of the expected token (e.g. "${TOKEN[Dashboard.Name.1234]}")

### Reproduction Steps

```
from aws_cdk.aws_cloudwatch import CfnDashboard

dashboard = CfnDashboard(scope=self, id=f'SomeId', dashboard_body="{}")
print(dashboard.dashboard_name)
```

### What did you expect to happen?
dashboard.dashboard_name should be a token value and not the None value. this is required when you want to refer to the future dashboard name during the cdk deployment, for example. when trying to save it to the stack outputs

### What actually happened?
dashboard.dashboard_name is None and you can't refer to it. 

### Environment

  - **CDK CLI Version  :** 1.74.0 (build e86602f)
  - **Framework Version:** 1.74.0
  - **Node.js Version:** v12.18.3
  - **OS               :** MacOS Catalina 10.15.7 (19H2)
  - **Language (Version):** Python 3.7.6

### Other

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
You are looking for `dashboard.attr_dashboard_name`

**Comment by rix0rrr** [comment]
Or probably `dashboard.ref`
