### ISSUE TITLE
[apigatewayv2] error when doing a change on a deployed apigwv2 using a custom domain

### ISSUE THREAD

**Issue by machielg** [aws/aws-cdk#11637]
When doing a change on a deployed api v2 gateway using a custom domain, I get an error 

### Reproduction Steps

```typescript
       const proxyIntegration = new apigw_intergrations.LambdaProxyIntegration({
            handler: dynamoLambda
        });

        const dn = new apigw.DomainName(this, 'ApiDomain', {
            domainName,
            certificate: props.tlsCertificate
        });

        const cfnDN = dn.node.defaultChild as apigw.CfnDomainName;
        cfnDN.mutualTlsAuthentication = {
            truststoreUri: asset.s3ObjectUrl
        };

        let api = new apigw.HttpApi(this, 'Endpoint', {
            defaultIntegration: proxyIntegration,
            defaultDomainMapping: {
                domainName: dn,
                mappingKey: 'adt'
            }
        });
```

### What did you expect to happen?
I expect a new certificate file to be used. Also removing the mtls configuration doesn't work.

### What actually happened?
I get an error
```
 2/14 | 4:50:15 PM | UPDATE_FAILED        | AWS::ApiGatewayV2::DomainName  | ApiDomain (ApiDomain2D27DFFC) Invalid API identifier specified 123456789:xcdyr1m7zk (Service: AmazonApiGatewayV2; Status Code: 404; Error Code: NotFoundException; Request ID: 966ef0be-e21e-4b5f-96a6-71deea654260; Proxy: null)
	new DomainName (/home/node_modules/@aws-cdk/aws-apigatewayv2/lib/common/domain-name.ts:113:22)
```

 (123456789 is my account ID).

### Environment

  - **CDK CLI Version  :**1.74
  - **Framework Version:** 1.74
  - **Node.js Version:** v15.2.1
  - **OS               :** MacOS/Linux
  - **Language (Version):** TypeScript

### Other

--- 

This is :bug: Bug Report

**Comment by machielg** [comment]
The error is also visible in the console. I think it's not possible to update the mTLS property after creating the domain name.

**Comment by nija-at** [comment]
> When doing a change on a deployed api v2 gateway using a custom domain

Could you be specific about what the original CDK code was when this succeeded and what parts you updated before getting this error?
