### ISSUE TITLE
[aws-eks] docker hub has restricted the pull limit and caused some confusion..

### ISSUE THREAD

**Issue by jialechan** [aws/aws-cdk#11659]
### The Question

Recently, docker hub has restricted the pull limit and caused some confusion...   

The spot created by cdk will automatically install the "AWS Node Termination Handler".
This helm charts will pull the image of amazon/aws-node-termination-handler:v1.7.0, but because of the current pull restriction of docker, an error is caused:

"You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit”

😭

### Environment

  - **CDK CLI Version:**  --
  - **Module Version:**  --
  - **Node.js Version:**  --
  - **OS:**  --
  - **Language (Version):**  --

**Comment by pahud** [comment]
https://github.com/aws/aws-node-termination-handler/issues/295

**Comment by iliapolo** [comment]
Closing as this is tracked in the issue mentioned above and is not CDK specific.
