### ISSUE TITLE
[aws-codebuild] Add ability to define `certificate` in CodeBuild Project Construct Props

### ISSUE THREAD

**Issue by jen-gineer** [aws/aws-cdk#11652]
It doesn't seem possible to define the `certificate` property in the CodeBuild `Project Construct`. I would expect to define it via the [BuildEnvironment interface](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-codebuild.BuildEnvironment.html). 

However, the only option I can find to define it via CDK is using the `CfnProject Construct` via the [EnvironmentProperty](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-codebuild.CfnProject.EnvironmentProperty.html#certificate) interface which I think requires me to use the `CfnProject Construct` instead of the `Project Construct` (unless I can override it somehow?)

### Use Case

When deploying CodeBuild Projects via CDK, to have the ability to enable SSL between on-prem source code repos and CodeBuild. 

### Proposed Solution

Add the `certificate` parameter to the [BuildEnvironment Interface](https://github.com/aws/aws-cdk/blob/2465852eb71461ab984c901bd00933860234c6bb/packages/%40aws-cdk/aws-codebuild/lib/project.ts#L1169-L1201) for the CodeBuild Project Construct

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by skinny85** [comment]
Thanks for opening the issue @jen-gineer . Before we implement this, you can use [escape hatches](https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html) to set that property.

Thanks,
Adam

**Comment by jen-gineer** [comment]
> Thanks for opening the issue @jen-gineer . Before we implement this, you can use [escape hatches](https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html) to set that property.
> 
> Thanks,
> Adam

Oh amazing, thanks for the link Adam! I tried something similar based on a [StackOverflow answer](https://stackoverflow.com/questions/55375376/is-there-a-way-in-aws-cdk-to-associate-a-codebuild-project-with-a-vpc-subnet-an) but I couldn't quite get it working. Your link on escape hatches has a lot more details so I'll give it another go!

**Comment by jen-gineer** [comment]
Thanks again for the link @skinny85. I got it working easily enough with the following two lines of code (if anyone else needs the same functionality).
 
`codeBuildProject` is created with the main CodeBuild `Project` construct
```ts
const cfnProject = codeBuildProject.node.defaultChild as codebuild.CfnProject;
cfnProject.addPropertyOverride('Environment.Certificate', 'arn:aws:s3:::/bucket-name/path/cert.pem');
```

So all good from my end if you want to close or deprioritise this one

**Comment by skinny85** [comment]
Glad you figured it out @jen-gineer 🙂. Let's keep the issue open for adding proper support for this feature, without resorting to escape hatches.
