### ISSUE TITLE
(assert): StackInspector.at hard to use

### ISSUE THREAD

**Issue by iggyzap** [aws/aws-cdk#11660]
## :question: General Issue

When trying to navigate stack object tree and apply assertion, type safety stops you from doing so.

### The Question

When trying to assert a specific path within CDK stack, via
```typescript
import * as asserts from '@aws-cdk/assert';
asserts.expect(stack).at("foo/bar/baz").to(asserts.matchTemplate({}))
```
Typescript compiler gives following error:

`error TS2345: Argument of type 'Assertion<StackInspector>' is not assignable to parameter of type 'Assertion<StackPathInspector>'.
  Property 'path' is missing in type 'StackInspector' but required in type 'StackPathInspector'.`

This is due to following declaration of `to` method of Inspector:
```typescript
  public to(assertion: Assertion<this>): any {
    return this.aroundAssert ? this.aroundAssert(() => this._to(assertion))
      : this._to(assertion);
  }
```
It requires assert to match type of the `Inspector`, which after using `at` command becomes `StackPathInspector` and starts requiring `path` field.

### Environment

  - **CDK CLI Version:** 
```
cdk version
1.50.0 (build 84acc92)
```
  - **Module Version:** 1.60.0
  - **Node.js Version:** 
``` node -v
v15.0.1
```
  - **OS:** OSX BigSur
  - **Language (Version):** 
```
npx tsc --version
Version 3.9.5
```

**Comment by NGL321** [comment]
Hey @iggyzap,

Sorry for the delay on this. This definitely strikes me as a bug report since you are using the assertion library correctly. Adjusting the issue so it will get better attention as a bug.

Please feel free to correct me if I am assuming wrong!

😸 😷

**Comment by nija-at** [comment]
@iggyzap -

Can you describe what you're trying to assert with the line - `asserts.expect(stack).at("foo/bar/baz").to(asserts.matchTemplate({}))` ?

What is 'foo/bar/baz' in this case?

**Comment by iggyzap** [comment]
Hi @nija-at , 
Sorry for delay with response, I'll try to get this written ASAP.
