### ISSUE TITLE
[cli] inaccurate system clock results in indefinite hang with no warning

### ISSUE THREAD

**Issue by chillitom** [aws/aws-cdk#11669]
If local system clock is inaccurate (for example 1 hour behind - reading 1pm when really it is 2pm) then the CLI tool will hang infinitely during deploy.

### Reproduction Steps

Set the system clock to an hour behind.

### What did you expect to happen?

The program should terminate with an error code and descriptive message.

### What actually happened?

Program hung.

Verbose output reveals it hangs at the stage `Reading existing template for stack <stack name>`

### Environment

  - **CDK CLI Version  :** 1.74.0
  - **Framework Version:** 1.74.0
  - **Node.js Version:** 14.15.1
  - **OS               :** Windows
  - **Language (Version):** Typescript 4.1.2

### Other

I found the issue by trying  `aws s3 ls` which gave the following error message `An error occurred (RequestTimeTooSkewed) when calling the ListBuckets operation: The difference between the request time and the current time is too large.`

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
I would assume this would be caused by copious retries by the SDK (we've set to retry calls for up to 15 minutes).

**Comment by minalvnk** [comment]
Is this issue resolved ?

**Comment by m1212e** [comment]
Since I still got the issue, it probably isn't.
