### ISSUE TITLE
[Control Tower] Support and documentation for using CDK with Control Tower

### ISSUE THREAD

**Issue by 0xjjoyy** [aws/aws-cdk#11664]
## :question: General Issue
Have AWS Control Tower enabled. This has multiple S3 SCP guardrails.

When doing a `cdk deploy pipeline` the artifact and supporting S3 buckets are not able to be created.

Error is

`API: s3:SetBucketEncryption Access Denied`

### The Question

Need documentation, guidance, and relevant fixes to be able to use CDK pipelines within AWS Control Tower managed accounts.

### Environment

`AWS Control Tower`

  - **CDK CLI Version:**  `cdk version 1.74.0 (build e86602f)`
  - **Module Version:** 
  - **Node.js Version:** 
  - **OS:** 
  - **Language (Version):**

**Comment by stowns** [comment]
@0xjjoyy I updated the Oganizations -> SCP entries containing the `s3:PutEncryptionConfiguration` and `s3:PutBucketPolicy` actions to allow the deployment role. Crucial to include a `aws:PrincipalOrgPaths` condition, else any account with a role matching your deployment role will have access to carry out actions  ie)
```
{
            "Condition": {
                "ArnNotLike": {
                    "aws:PrincipalARN": [
                        "arn:aws:iam::*:role/AWSControlTowerExecution",
                        "arn:aws:iam::*:role/admin*" # <----your deployment role
                    ]
                },
                "ForAnyValue:StringEquals": {
                    "aws:PrincipalOrgPaths": [
                        "o-my_orgid/ou-my_ou/",
                        "o-my_orgid/ou-my_ou2/"
                    ]
                }
            },
            "Action": [
                "s3:PutEncryptionConfiguration"
            ],
            "Resource": [
                "*"
            ],
            "Effect": "Deny",
            "Sid": "GRAUDITBUCKETENCRYPTIONENABLED"
        },
        {
            "Condition": {
                "ArnNotLike": {
                    "aws:PrincipalARN": [
                        "arn:aws:iam::*:role/AWSControlTowerExecution",
                        "arn:aws:iam::*:role/admin*" # <----your deployment role
                    ]
                },
                "ForAnyValue:StringEquals": {
                    "aws:PrincipalOrgPaths": [
                        "o-my_orgid/ou-my_ou/",
                        "o-my_orgid/ou-my_ou2/"
                    ]
                }
            },
            "Action": [
                "s3:PutBucketPolicy"
            ],
            "Resource": [
                "*"
            ],
            "Effect": "Deny",
            "Sid": "GRAUDITBUCKETPOLICYCHANGESPROHIBITED"
        }
```

**Comment by redbaron** [comment]
Doesn't update to SCPs managed by Control Tower cause configuration drift and will be overwritten on a next CT template version update?

**Comment by rix0rrr** [comment]
Not sure how Control Tower is expecting people to create encrypted buckets. My experience here is lacking.

Anyone else have any insight?

**Comment by 0xjjoyy** [comment]
From what I can tell, the role AWSControlTowerExecution must be used. This means we must assume this role via another role, then run the ```cdk bootstrap```.

One suggestion is to have specific Control Tower documentation and guidance. Also, a specific bootstrap mechanism for Control Tower that will bootstrap all accounts managed by Control Tower.

**Comment by ajhool** [comment]
I'm having a similar problem when configuring lifecycle policies on S3 buckets. Yikes, this is a major constraint and a difficult issue to identify and  to troubleshoot.

Leaving the error message here for future finders:

```
You don’t have permission to create the rule
You or your AWS admin must update your IAM permissions to allow s3:PutBucketLifecycleConfiguration, and then try again. Learn more about Identity and access management in Amazon S3
API response
Access Denied
```

**Comment by dannyburke1** [comment]
> From what I can tell, the role AWSControlTowerExecution must be used. This means we must assume this role via another role, then run the `cdk bootstrap`.
> 
> One suggestion is to have specific Control Tower documentation and guidance. Also, a specific bootstrap mechanism for Control Tower that will bootstrap all accounts managed by Control Tower.

Are you able to assume this role successfully? I'm having the same issue, and bashing my head against the wall with control tower. As mentioned above, altering or removing SCP's will break your landing zone and cause you to update it - not ideal!

**Comment by dannyburke1** [comment]
I created a user in my Control Tower Management account that could assume the Control Tower Execution Role in the account where I was putting my bucket and got it to work like that.

**Comment by peterwoodworth** [comment]
Can anyone else confirm @dannyburke1 's solution?

**Comment by JohnPolansky** [comment]
@peterwoodworth Yes @dannyburke1's solution worked.. as a workaround anyway.

My company recently enabled Control Tower and the SCP rules that are recommended as best practice and it appears they conflict with what `cdk bootstrap` is trying to setup. I managed to get the bootstrap to work by doing the following:

1. Using my `Control Tower` account credentials I assumed the role of `AWSControlTowerExecution` from the account I was trying to `cdk bootstrap`
```
AWS_PROFILE=control-tower aws sts assume-role --role-arn arn:aws:iam::<AcctIdForBootstrapAccount>:role/AWSControlTowerExecution --role-session-name test
```
This provided me with JSON output that gave me an AWS Access KEY/SECRET/TOKEN I then set those as environment variables:
```
export AWS_ACCESS_KEY_ID=<KEY_ID>
export AWS_SECRET_ACCESS_KEY=<SECRET_KEY>
export AWS_SESSION_TOKEN=<VeryLongSessionToken>
```
With that setup I then ran my:
`cdk bootstrap` (without any profile)

And presto the bootstrap worked. I'm not sure why an SCP policy would prevent people from enabling encryption, that seems a bit backwards to me. Is this expected behavior for `aws-cdk` with Control Tower? somehow I'd have expected CDK to work within the best practice SCPs that AWS recommends. Is there some documentation I missed by chance?

I have my doubts that most people using cdk will have Control Tower Admin access capable of switching roles and bypassing SCP policies.

Thanks @dannyburke1  for the suggestion, spent a bunch of time fighting this :)

**Comment by dannyburke1** [comment]
> @peterwoodworth Yes @dannyburke1's solution worked.. as a workaround anyway.
> 
> My company recently enabled Control Tower and the SCP rules that are recommended as best practice and it appears they conflict with what `cdk bootstrap` is trying to setup. I managed to get the bootstrap to work by doing the following:
> 
> 1. Using my `Control Tower` account credentials I assumed the role of `AWSControlTowerExecution` from the account I was trying to `cdk bootstrap`
> 
> ```
> AWS_PROFILE=control-tower aws sts assume-role --role-arn arn:aws:iam::<AcctIdForBootstrapAccount>:role/AWSControlTowerExecution --role-session-name test
> ```
> 
> This provided me with JSON output that gave me an AWS Access KEY/SECRET/TOKEN I then set those as environment variables:
> 
> ```
> export AWS_ACCESS_KEY_ID=<KEY_ID>
> export AWS_SECRET_ACCESS_KEY=<SECRET_KEY>
> export AWS_SESSION_TOKEN=<VeryLongSessionToken>
> ```
> 
> With that setup I then ran my:
> `cdk bootstrap` (without any profile)
> 
> And presto the bootstrap worked. I'm not sure why an SCP policy would prevent people from enabling encryption, that seems a bit backwards to me. Is this expected behavior for `aws-cdk` with Control Tower? somehow I'd have expected CDK to work within the best practice SCPs that AWS recommends. Is there some documentation I missed by chance?
> 
> I have my doubts that most people using cdk will have Control Tower Admin access capable of switching roles and bypassing SCP policies.
> 
> Thanks @dannyburke1 for the suggestion, spent a bunch of time fighting this :)

Thanks @JohnPolansky for the detailed response and glad this worked for you, albeit it being a dirty solution. Do you have any of the Control Tower elective Guard Rails in place, specifically around S3? I'm inclined to think that these will make you unable to deploy encryption methods or put objects into buckets, but I haven't tested this hypothesis (yet).

**Comment by JohnPolansky** [comment]
@dannyburke1  - To answer your question the GuardRails that I found blocking me were these:

* Disallow Changes to Encryption Configuration for Amazon S3 Buckets
* Disallow Changes to Bucket Policy for Amazon S3 Buckets

bootstrap won't work with those enabled, we've disabled them temporarily to allow work, I've opened an AWS Support ticket as well to ask what the recommended course of action. that said there are plenty other guardrails that will likely block CDK work, but not the bootstrap process:

* Disallow Changes to Logging Configuration for Amazon S3 Buckets
* Disallow Changes to Lifecycle Configuration for Amazon S3 Buckets
* Disallow changes to replication configuration for Amazon S3 buckets
* Disallow delete actions on S3 buckets without MFA

and others.. we really need some recommended best practices for using CDK with Control Tower + SCPs it appears. It seems like we'll need an easy way to exclude CDK from SCP control and while assumerole idea works, it's not a very good automation friendly way in my view.

**Comment by tim-finnigan** [comment]
Checking in as there hasn't been any activity on this in a while. Can anyone clarify or expand on the ask here? In terms of documentation I'm wondering what specifically should be added and where (e.g. the [Developer Guide](https://docs.aws.amazon.com/cdk/v2/guide/home.html) or [examples repo](https://github.com/aws-samples/aws-cdk-examples/).)
