### ISSUE TITLE
Unable to deploy using cdk Deploy from local node modules.

### ISSUE THREAD

**Issue by ancheraja** [aws/aws-cdk#11673]
### The Question

Trying to deploy the aws  resources using cdk Deploy -r cdk-deployment-role command from local node modules with out installing the global CDK. 
Error: role has been interpreted as stack name.

```console
**npm run cdk deploy -r cdk-deployment-role**
No stack found matching 'arn:aws:iam::XXX:role/cdk-deployment-role'. Use "list" to print manifest
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! service@0.1.0 cdk: cdk "deploy" "arn:aws:iam::XXX:role/cdk-deployment-role"
npm ERR! Exit status 1
npm ERR! 
```
used below command
npm run cdk deploy -r $cdk_role

### Environment

  - **CDK CLI Version:** 1.70.0
  - **Module Version:**  "aws-cdk": "^1.70.0"
  - **Node.js Version:** 12.16.1
  - **OS:** Ubuntu 
  - **Language:** Java Script
  - **NPM Version:** 6.13.4

**Comment by paulholden2** [comment]
@ancheraja Try `npm run cdk -- deploy -r $role_name`.

**Comment by ancheraja** [comment]
It worked thankyou paulholden2.
