### ISSUE TITLE
(cognito): add idTokenValidity to the UserPoolClient L2

### ISSUE THREAD

**Issue by SomayaB** [aws/aws-cdk#11689]
> Originally from an internal ticket

On checking the CDK Typescript reference, I found that there are two constructs for defining a user pool app client. A high-level construct UserPoolClient [1] and a low-level construct CfnUserPoolClient [2]. The high-level constructor UserPoolClient does not have any provision to specify any token validity. However the low-level construct CfnUserPoolClient does have an option to provide the tokens validity, similar to CloudFormation template parameters.

### Use Case

Customer is currently using the higher-level constructs and he wants to know if there is there a plan to implement the token expires in the higher-level constructs as well. Because the lower-level constructs requires more (ugly) code.

### Other

[1] Class UserPoolClient:
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cognito.UserPoolClient.html

[2] Class CfnUserPoolClient:
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cognito.CfnUserPoolClient.html

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by nija-at** [comment]
The CloudFormation property is https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpoolclient.html#cfn-cognito-userpoolclient-idtokenvalidity.

The workaround is to use [property override escape hatches](https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html#cfn_layer_raw).
