### ISSUE TITLE
[cdk-pipelines] Lookups ( Route53 Zones, VPCs etc ) in Nested Stacks facing environment problems

### ISSUE THREAD

**Issue by mrpackethead** [aws/aws-cdk#11680]
## :Lookups ( Route53 Zones, VPCs etc ) in Nested Stacks,  with pipelines.. facing environment problems..

i'm experimenting with cdk pipelines., and have run into a problem when have nested Templates that are doing lookups;  In this example, its causing my Route53 Zone lookup to fail, but the same thign occurs with a VPC lookup.

At the end of the pipeline definition, i add a stage..

```
# Add stages as required. 
app_env = core.Environment(account="1xxxxxxxxxx7", region="ap-southeast-2")  
prod_app = ApplicationStage(self, 'Prod', env = app_env)
prod_stage = pipeline.add_application_stage(prod_app)
ApplicationStage and the Application Stack look like this.  Dynamo and Apigateway are NestedStacks    [ class Apigateway(cfn.NestedStack): ]
class ApplicationStage(core.Stage):
    def __init__(self, scope: core.Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)
        ApplicationStack(self, 'Application')    
class ApplicationStack(core.Stack):
    def __init__(self, scope: core.Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)
        api_url = 'api.something.click'
        app = core.App()
        root_stack = Top(app, "rootstack")
        dynamodb_stack = DynamoDB(root_stack, 'Dynamodb')   
        api_stack = Apigateway(root_stack, 'apigateway',   
            api_url = api_url,
            hostname = hostname,
        )
```
One of the things that Apigateway does, is a Route53 zone lookup, so it knows where to place a CNAME for the api-gateway.

```
class Apigateway(cfn.NestedStack):
    def __init__(self, scope: core.Construct, id: str,  api_url,  **kwargs) -> None:
        super().__init__(scope, id, **kwargs)        
    r53_zone = r53.HostedZone.from_lookup(self,"DoormanZone",
            domain_name = base_url
        )
```

This fails with this error.
  Error: Cannot retrieve value from context provider hosted-zone since account/region are not specified at the stack level. Either configure "env" with explicit account and region when you define your stack, or use the environment variables "CDK_DEFAULT_ACCOUNT" and "CDK_DEFAULT_REGION" to inherit environment information from the CLI (not recommended for production stacks)
The error originates from the r53 lookup.
Theres no way it seems to pass a the enviroment to the cfn.NestedStacked, but my understanding is that nested stack should be getting the environment from its root stack anyway?
I'm not quite sure how to proceed here. 

I have a workaround, but not sure if its a good one, or if i've missed the way to do this.
In my applicaiton Stack, i can do the Route53 Zone lookup, and then pass that as a parameter to the nested stack.

**Comment by rix0rrr** [comment]
This part is confusing me:

```
        root_stack = Top(app, "rootstack")
```

Looks like you're starting a new hierarchy there outside the scope of the `Stage`. That would explain why the `Stage`'s account and region are not being inherited by your nested stack.

**Comment by mrpackethead** [comment]
Thanks @rix0rrr this really helped me out, and i've got a much better understanding of what i needed to do.  I I'd created something that partially worked, but it was not well constructed.
