### ISSUE TITLE
(stepfunctions): unable to add tasks after instantiating the StateMachine

### ISSUE THREAD

**Issue by moltar** [aws/aws-cdk#11692]
I cannot chain or add more tasks into the task sequence, after the `definition` via `StateMachine` instance.

There is no error produced, nor a step/task is added.

### Reproduction Steps

```ts
this.runsAfterMigrations = new sfn.Parallel(scope, 'RunsAfterMigrations')
this.runsAfterMigrations.branch(new sfn.Succeed(scope, 'Dummy Branch'))
this.migrationTask.next(this.runsAfterMigrations)

// add a branch BEFORE
this.runsAfterMigrations.branch(new sfn.Succeed(this, 'Success1'))

const stateMachine = new sfn.StateMachine(scope, 'DatabaseTasks', {
  definition: this.migrationTask,
})

// add a branch AFTER
this.runsAfterMigrations.branch(new sfn.Succeed(this, 'Success2'))
```

Relevant branch:

```json
{
  "RunsAfterMigrations": {
    "Type": "Parallel",
    "End": true,
    "Branches": [
      {
        "StartAt": "Dummy Branch",
        "States": {
          "Dummy Branch": {
            "Type": "Succeed"
          }
        }
      },
      {
        "StartAt": "Success1",
        "States": {
          "Success1": {
            "Type": "Succeed"
          }
        }
      }
    ]
  }
}
```

### What did you expect to happen?

Either the step is added, or an error is thrown.

### What actually happened?

No step is added.
No error is thrown.

### Environment

  - **CDK CLI Version  :** 1.74.0 (build e86602f)
  - **Framework Version:** 1.74.0
  - **Node.js Version:** v12.18.4
  - **OS               :** macos
  - **Language (Version):** `"typescript": "4.0.5"`

### Other

--- 

This is :bug: Bug Report

**Comment by shivlaks** [comment]
@moltar I agree this should probably throw an error. I'm trying to understand this usage a little better. Curious why it's necessary to add steps after defining the state machine. I would expect it to be the last thing created, but perhaps there's a use case i'm overlooking or missing.

**Comment by moltar** [comment]
The use case is to be able to compose the state machine from different parts of the application. E.g. I want to dynamically add steps _after_ migration, but only for certain feature flags, coming from another nested stack.

The state machine and the database migration task are defined in a single nested stack that is responsible for the database.

Then I want to chain other tasks, that must run only _after_ the migrations run.
