### ISSUE TITLE
(aws-iam): `OpenIdConnectProvider.openIdConnectProviderIssuer` is wrong for a provider that is imported using a token ARN

### ISSUE THREAD

**Issue by iliapolo** [aws/aws-cdk#11705]
`OpenIdConnectProvider.openIdConnectProviderIssuer` is wrong for a provider that is imported using a token ARN.

### Reproduction Steps

Deploy the following:

```ts
const provider = new iam.OpenIdConnectProvider(this, 'Thumbprints', {
  url: 'https://oidc.eks.us-east-1.amazonaws.com/id/test4',
  thumbprints: [
    'aa00aa1122aa00aa1122aa00aa1122aa00aa1122',
    'aa00aa1122aa00aa1122aa00aa1122aa00aa1111',
  ],
});

const imported = iam.OpenIdConnectProvider.fromOpenIdConnectProviderArn(this, 'Imported', provider.openIdConnectProviderArn);

new cdk.CfnOutput(this, 'ImportedProviderIssuer', {
  value: imported.openIdConnectProviderIssuer,
});
```

### What did you expect to happen?

Expected the output value to be: `oidc.eks.us-east-1.amazonaws.com/id/test4`

### What actually happened?

Output value is: `oidc.eks.us-east-1.amazonaws.com`

### Environment

  - **CDK CLI Version  : ALL**
  - **Framework Version : ALL**
  - **Node.js Version: ALL** 
  - **OS               : ALL**
  - **Language (Version): ALL** 

### Other

Thanks to @jumi-dev investigation it looks like the error is coming from:

https://github.com/aws/aws-cdk/blob/13c05bee5882114ccdd4c917cb5cc0204ce15e49/packages/%40aws-cdk/core/lib/arn.ts#L266

This fails in case the resource name includes the separator. Like with an oidc ARN:

`arn:aws:iam::1234567:oidc-provider/oidc.eks.us-east-1.amazonaws.com/id/someid`

Originally reported here: https://github.com/aws/aws-cdk/issues/11682

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment]
@rix0rrr I can whip a quick fix for this by having `parseToken` accept how many parts does the resource name with respect to the separator, and doing:

```ts
const resourceName = hasName ? Fn.join(sep, [...Array(namePartsCount).keys()].map(i => Fn.select(i + 1, lastComponents))).toString()
```

But i'm wondering if there is something more generic we can do?

**Comment by rix0rrr** [comment]
This is one of those things that I feel we can't properly do anything about without *slicing* support in CFN.

We could use a Custom Resource for that though, in order to do something like:

```
{ Fn::Join: ['/', { Fn::Slice: [6, { Fn::Split: ['/', ARN]} ]} ]}
                    ~~~~~~~~~ this doesn't exist yet
```

**Comment by rix0rrr** [comment]
> I can whip a quick fix for this by having `parseToken` accept how many parts does the resource name have with respect to the separator

Well but how will you know in advance?

**Comment by rix0rrr** [comment]
Are you sure this hasn't been fixed recently? The current code looks like a good hack which, although not 100% correct, will do in most cases:

https://github.com/aws/aws-cdk/blame/huijbers/userdata-replacement/packages/%40aws-cdk/aws-iam/lib/oidc-provider.ts#L161

**Comment by rix0rrr** [comment]
Oh duh, no that should have been here as well: https://github.com/aws/aws-cdk/blame/master/packages/%40aws-cdk/aws-iam/lib/oidc-provider.ts#L116

But, the same strategy could apply.

1. Pretend the resource name separator is `:` (even though it is actually `/`, but it will net us the entire `oidc-provider/oidc.eks.us-east-1.amazonaws.com/id/someid` string.
2. Split on `oidc-provider/`. This is dangerous if the string contains that substring more than once, but let's assume it doesn't.
3. That gives us the array `['', 'oidc.eks.us-east-1.amazonaws.com/id/someid']` of which we select the 2nd element.

**Comment by iliapolo** [comment]
> > I can whip a quick fix for this by having `parseToken` accept how many parts does the resource name have with respect to the separator
> 
> Well but how will you know in advance?

Every resource knows how its ARN looks like, so when the resource calls `Stack.of(this).parseArn` that information can be passed in.

**Comment by rix0rrr** [comment]
That whole 'split-on-prefix-and-take-2nd-element' logic could actually be added to `parseArn`. It might come in useful.

**Comment by rix0rrr** [comment]
> > Well but how will you know in advance?
> 
> Every resource knows how its ARN looks like, so when the resource calls `Stack.of(this).parseArn` that information can be passed in.

Ah but you won't know how many `/` there will be in the URL, or will you?
