### ISSUE TITLE
(eks): Custom Bootstrap Arguments for NodeGroup

### ISSUE THREAD

**Issue by fentas** [aws/aws-cdk#11719]
:wave: The ability to set `BootstrapOptions` or at least user data.

### Use Case

We need to configure `--pod-max-pids` as an extra kubelet argument.
Prevent pids fork bombs.

---

This is a :rocket: Feature Request

**Comment by iliapolo** [comment]
@fentas You can do this by creating a launch template and using it when you add the node group:

https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/aws-eks#launch-template-support

Is this a request to enable this more easily? just making sure i'm not missing something.

**Comment by fentas** [comment]
Ah. Ok. Got misled with the BootstrapOptions for Autoscaling groups. 
I will try with the launch template :+1:  Thanks a lot.
Will close for now.
