### ISSUE TITLE
(monocdk): Include ecs-service-extensions in monocdk

### ISSUE THREAD

**Issue by psnoblin** [aws/aws-cdk#11712]
I'd like to use the new ecs-service-extensions library, but it doesn't appear to be included in the monocdk build, nor does it appear to be possible to mix the monocdk constructs with those of the extensions library.

### Use Case

I have a CDK defined stack that includes ECS services, using the monocdk build. I'd like to make use of the new ecs-service-extensions library to simplify creation of my task definitions (e.g. adding in XRay and AppMesh sidecar containers). I'm unable to do so because:
* I have to use the monocdk because I need to use some internal construct libraries that also use it
* The monocdk doesn't include the ecs-service-extensions
* Adding `@aws-cdk-containers/ecs-service-extensions` as a dependency doesn't work, as it transitively depends on the modularized CDK packages.

### Proposed Solution

I'm pretty unfamiliar with typescript, NPM, etc, so I may be missing some things, but I'd venture a guess that one of these two options would work:

1. Include ecs-service-extensions in the monocdk build.
2. Publish an alternate version of ecs-service-extensions that depends on monocdk instead of the modularized CDK. (Something like "monocdk/ecs-service-extensions"?)

---

This is a :rocket: Feature Request

**Comment by NetaNir** [comment]
monocdk is an experimental package that should not be used. It was mostly published for internal needs. 

Once aws cdk v2 is released we will provide migration guidance to both cdk application and cdk libraries.
