### ISSUE TITLE
(pipelines): pass variables from pipeline to stages

### ISSUE THREAD

**Issue by tdikland** [aws/aws-cdk#11714]
### The Question

For my application I want to do an integration test,  for which I use the ```ShellScriptAction``` with a configured VPC. I now want to allow connection between the securitygroup of the codebuild stage and the securitygroup of my application (that is deployed using the pipeline) to run the tests. 

I think there are two ways to think about this:
1) Add a connection to the codebuild sg using information about the application sg deployed by the pipeline. This however seems not the way to go, because the pipeline is deployed before the application
2) Add a connection to the application sg using information about the codebuild sg. This seems like the right way. However cdk does not allow me to pass variables/constructs defined in the pipeline stack to the application stack. 

What is the correct way to tackle this problem? Is this an error on my part, or a limitation of CDK/Cloudformation?

### Environment

  - **CDK CLI Version:** 1.74.0
  - **Module Version:** 1.74.0
  - **Node.js Version:** 10.22.1
  - **OS:** Ubuntu 
  - **Language (Version):** Python (3.7.3)

**Comment by rix0rrr** [comment]
You could achieve this by exporting the Security Group Id to an SSM parameter in the pipeline stack, and then importing that SSM parameter as a security group in the stack.

There's nothing currently to make that transparent.
