### ISSUE TITLE
(apigatewayv2): Error while deploying AWS::ApiGatewayV2::Model via CfnModel

### ISSUE THREAD

**Issue by chegger** [aws/aws-cdk#11716]
Deploying a `AWS::ApiGatewayV2::Model` fails with the error message `Invalid modle schema specified`, even when the model schema is a valid model schema. **The error occurs when using  camelCase properties, such as `minLength` or `maxLength` properties.**

According to the [docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigatewayv2-model.html#cfn-apigatewayv2-model-schema), the model schema is supposed to be a `draft-04` json schema.

A minimal valid `draft-04` schema is the following (correct me if I am wrong, I  validated the scema using [this tool](https://jsonschemalint.com/#!/version/draft-04/markup/json)):

```json
{
    "type": "string",
    "minLength": 2
}
```
The above schema is considered valid when working with the `aws cli` directly, i.e. calling `create-model` with this schema.

### Reproduction Steps

```typescript
import * as cdk from "@aws-cdk/core";
import * as apigatewayv2 from "@aws-cdk/aws-apigatewayv2";

const app = new cdk.App();
const stack = new cdk.Stack(app, "ApiStack");

// Create an api as it is needed to create a model
const api = new apigatewayv2.CfnApi(stack, "Api", {
  protocolType: 'WEBSOCKET',
  routeSelectionExpression: "\\$default",
  name: "TestApiName",
});

// Create the actual model
const model = new apigatewayv2.CfnModel(
      stack,
      "Model",
      {
        apiId: api.ref,
        name: "TestModel",
        schema:  {
          "type": "object",
          "properties": {
            "prop1": {
              "type": "string",
              "minLength": 1
            }
          }
        },
        contentType: "application/json",
        description: "Some model description",
      }
    );
```

### What did you expect to happen?

I was trying to deploy a Route Request Model for a `AWS::ApiGatewayV2::Api` and was **expecting** the model to successfully deploy.

### What actually happened?

I received the following error message during deployment of the model:

```
 0/2 | 3:05:49 PM | CREATE_FAILED        | AWS::ApiGatewayV2::Model         | Model Invalid model specified: Validation Result: warnings : [], errors : [Invalid model schema specified, Invalid model schema specified] (Service: AmazonApiGatewayV2; Status Code: 400; Error Code: BadRequestException; Request ID: 51f89d21-6c85-4b49-926e-27180cf689db; Proxy: null)
	new <omitted> (/builds/<omitted>)
	\_ Object.<anonymous> (/builds/<omitted>)
	\_ Module._compile (node:internal/modules/cjs/loader:1102:14)
	\_ Module.m._compile (/builds/<omitted>/node_modules/ts-node/src/index.ts:1043:23)
	\_ Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
	\_ Object.require.extensions.<computed> [as .ts] (/builds/<omitted>/node_modules/ts-node/src/index.ts:1046:12)
	\_ Module.load (node:internal/modules/cjs/loader:967:32)
	\_ Function.Module._load (node:internal/modules/cjs/loader:807:14)
	\_ Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
	\_ main (/builds/<omitted>/node_modules/ts-node/src/bin.ts:225:14)
	\_ Object.<anonymous> (/builds/<omitted>/node_modules/ts-node/src/bin.ts:512:3)
	\_ Module._compile (node:internal/modules/cjs/loader:1102:14)
	\_ Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
	\_ Module.load (node:internal/modules/cjs/loader:967:32)
	\_ Function.Module._load (node:internal/modules/cjs/loader:807:14)
	\_ Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
	\_ node:internal/main/run_main_module:17:47
```

### Environment

  - **CDK CLI Version**: *1.74.0*
  - **Framework Version**: *1.74.0*
  - **Node.js Version**: *15.3.0* 
  - **OS**: *Running within node:current docker container.*
  - **Language (Version)**: *Typescript (4.1.2)*

### Other

I think the bug happens in the parsing of the `schema` object properties, where `minLength` and `maxLength` are maybe accidently translated to differently styled cloudformation props, instead of leaving them out. It also happens when using `addtionalProperties`.

Notice however, using the `aws cli` camelCase properties are supported.

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
Unfortunately, the `Cfn*` constructs are a simple wrapper on top of CloudFormation. We add no additional logic to validate or make it easier to define a Model.

The error you are receiving is from API Gateway. You will need to refer to their documentation and see how to define a model.

> I think the bug happens in the parsing of the schema object properties, where minLength and maxLength are maybe accidently translated to differently styled cloudformation props, instead of leaving them out

The generated CloudFormation template should be present in the generated output under `cdk.out/`. Can you check what the you find in there against the `AWS::ApiGatewayV2::Model` resource type?

**Comment by chegger** [comment]
Hi, thanks for your fast reply, greatly appreciated!

This is the generated output for my created stack in `cdk.out/`:

```json
{
  "Resources": {
    ...
    "Model": {
      "Type": "AWS::ApiGatewayV2::Model",
      "Properties": {
        "ApiId": {
          "Ref": "TestApi"
        },
        "Name": "TestModel",
        "Schema": {
          "type": "object",
          "properties": {
            "prop1": {
              "type": "string",
              "minLength": 1
            }
          }
        },
        "ContentType": "application/json",
        "Description": "Some model description"
      },
      "Metadata": {
        "aws:cdk:path": "TestStack/Model"
      }
    },
  ...
  },
"Conditions": {...}
}
```

**NOTE** that when I leave any camelCase attributes out (`minLength`) here, the model deploys perfectly fine.

**Comment by chegger** [comment]
Creating the model via the `aws cli` also works perfectly fine, including the `minLength` property:

`aws apigatewayv2 create-model --api-id <omitted> --name testModel --schema "{\"type\": \"object\", \"properties\": { \"prop1\": { \"type\": \"string\", \"minLength\": 1}}}" --content-type application/json`

**Comment by nija-at** [comment]
As far as I can tell, the CDK is correctly translating the specified properties to the CloudFormation template. 

The error is coming from CloudFormation or the API Gateway service. You will need to reach out to these teams via AWS support to see why this isn't working as expected.

**Comment by iain-opti** [comment]
4 years later, still the same issue, this is the only result when searching online too. I hereby vow to come back with an answer when I find out.

**Comment by iain-opti** [comment]
After some digging in to this issue:

Looking at the CloudTrail request made by AWS CloudFormation to API Gateway, I noticed that it was serialising all properties of the Schema as strings like: `"minItems": "1"` even though they were numbers in the passed schema. Since this is happening internally with CloudFormation, and there's no way AWS are going to fix it anytime soon (this original issue is 4 years old). I instead created a CustomResource to deploy it.

The aws-sdk for NodeJS have library: `client-apigatewayv2`, which has an `ApiGatewayV2Client` and `CreateModelCommand`, `UpdateModelCommand`, and `DeleteModelCommand`.
Each can be quickly mapped to the corresponding AWS CloudFormation `RequestType`s of `Create`, `Update`, and `Delete`. Passing through each of the parameters - pretty much identically to the AWS CF resource. Remember to `JSON.stringify` the schema, and pass the `PhysicalResourceId` as the `Response.ModelId` back to CloudFormation so that the `ModelId` can be passed on the `Update` and `Delete` requests too.
