### ISSUE TITLE
(general): hundreds of nested cdk.out/asset directories in %temp% broke Windows

### ISSUE THREAD

**Issue by beatyt** [aws/aws-cdk#11730]
### The Question

Original problem:  Windows machine after a restart was hanging at "Please wait for the User Profile Service" [[1](#1)]. I let it run over night and had no success.

After some investigating, I tried to delete my user %TEMP% directory. The only thing that failed to delete was a CDK.out asset directory. I used robocopy to delete the many nested directories. [[2](#2)] [[3](#3)] [[4](#4)]

Resolution: After 30 minutes of running a command, all of the nested directories were deleted and I was able to restart my machine.

It should be noted I've also been using VSCode as my IDE. It could be contributing or causing the issue as well?

### Environment

  - **CDK CLI Version:** 1.74.0 (build e86602f)
  - **Module Version:** n/a
  - **Node.js Version:** v12.13.0
  - **OS:** Windows 10 Version 1909 (OS Build 18363.959)
  - **Language (Version):** TypeScript 4.0.3

### Other information

(#1) The original problem and error message.
![image](https://user-images.githubusercontent.com/1040103/100351047-cde8b500-2fb8-11eb-95fc-d99ec731ca75.png)
(#2) Many nested cdk.out asset directories
![image](https://user-images.githubusercontent.com/1040103/100351320-451e4900-2fb9-11eb-957b-41e6b8f8cf50.png)
(#3) Running the delete
![image](https://user-images.githubusercontent.com/1040103/100351568-a0503b80-2fb9-11eb-94b7-61eeff7d69ad.png)
(#4) The result of deletion - `robocopy newTempFolder Temp /purge` was the command I ran to delete everything in Temp
![image](https://user-images.githubusercontent.com/1040103/100351400-62531780-2fb9-11eb-964e-cb383a5d19c4.png)

Thank you and please let me know if anything needs clarifying or more info. I can share the CDK project I was playing with if that would help.

**Comment by NetaNir** [comment]
Hi @beatyt!

Sorry about that!

To help us debug this, can you share if this happen after upgrading your CDK version? If so, what version were you upgrading from?

Thanks!

**Comment by NGL321** [comment]
Hey @beatyt,

Thanks for reporting this, and sorry you ran into it! It would be super helpful to get a little more information on this so we can better investigate and try to reproduce.

The following info would be great:
- Minimum sample code for reproduction (what were you actually building)
- As @NetaNir mentioned, if the code worked with a different version, which version upgrade caused the problem?

That should give us enough to start looking into what caused this 😄 


😸 😷

**Comment by beatyt** [comment]
I've just been playing with CDK off and on. Not really a previous version that I can say worked.
 
I have a mix of versions: https://github.com/beatyt/typescript-web-api-with-aws-cdk/blob/master/infrastructure/package.json#L34 so I should probably fix those and upgrade to latest.

`@aws-cdk/core` & `aws-cdk` is `1.67.0`

Sample project: https://github.com/beatyt/typescript-web-api-with-aws-cdk/tree/master/infrastructure

The project is broken into an ./application and ./infrastructure directory, the CDK stuff is in ./infrastructure.

**Comment by NGL321** [comment]
@beatyt,

After reviewing the CDK code it all looks kosher, I dont see a reason the code itself would cause this; especially since you don't seem to have any assets to deploy.

HOWEVER, I am surprised you are able to get the code to synth at all since we have a requirement that all packages in the project share a version (having different versions should cause synth-time exceptions). So with that said, my suggestion is to first update all the packages to the same version (latest or otherwise), and see if that fixes the problem. If not, I can keep digging.

😸 😷
