### ISSUE TITLE
(s3-deployment): Add vpc to BucketDeploymentProps

### ISSUE THREAD

**Issue by erudisch** [aws/aws-cdk#11734]
Add custom Vpc to BucketDeploymentProps to be able to run build commands in a more restricted environment.

### Use Case

According to [this](https://aws.amazon.com/blogs/devops/building-apps-with-aws-cdk/) it's possible to build websites inside the BucketDeployment, see `Building inside a Docker container`

Due to company restrictions we are only able to use it when there would be a way to set a custom Vpc that is passed to the lambda that runs the build command inside the BucketDeployment, see [constructor](https://github.com/aws/aws-cdk/blob/a76428bd8559e497cd631d17ff9af2a01792b4c2/packages/%40aws-cdk/aws-s3-deployment/lib/bucket-deployment.ts).

### Proposed Solution
1. add Vpc to `BucketDeploymentProps` in `bucket-deployment.ts`

```
export interface BucketDeploymentProps {
    ...
    readonly vpc?: ec2.IVpc;
}
```

2. pass the vpc to the build lambda:

```
export class BucketDeployment extends cdk.Construct {
  constructor(scope: Construct, id: string, props: BucketDeploymentProps) {
    ...
    const handler = new lambda.SingletonFunction(this, 'CustomResourceHandler', {
      uuid: this.renderSingletonUuid(props.memoryLimit),
      code: lambda.Code.fromAsset(handlerCodeBundle, { assetHash }),
      runtime: lambda.Runtime.PYTHON_3_6,
      handler: 'index.handler',
      lambdaPurpose: 'Custom::CDKBucketDeployment',
      timeout: cdk.Duration.minutes(15),
      role: props.role,
      memorySize: props.memoryLimit,
      vpc: props.vpc, <-- add vpc here
    });
    ...
  }
}
```

3. call `BuckerDeployment` like this:

```
new s3deployment.BucketDeployment(this, 'IFA-Cloud-Frontend-Deploy', {
          destinationBucket: bucket,
          vpc: custom-vpc,    <-- set vpc here
          sources: [
            s3deployment.Source.asset('../frontend', {
              bundling: {
                image: cdk.BundlingDockerImage.fromRegistry(`${env?.account}.dkr.ecr.${env?.region}.amazonaws.com/node:latest`),
                command: [
                  'bash', '-c', [
                    'npm i',
                    `export REACT_APP_API_URL=${apiUrl}`,
                    'npm run build',
                    'cp -r /asset-input/build/* /asset-output/',
                  ].join(' && '),
                ],
              },
            }),
          ],
        });
```

* [x] :wave: I may be able to implement this feature request

---

This is a :rocket: Feature Request

**Comment by iliapolo** [comment]
@erudisch I agree that `BucketDeployment` should support accepting a VPC. However, you also mentioned:

> Vpc that is passed to the lambda that runs the build command inside the BucketDeployment

The build commands are not executed in the bucket deployment lambda. They are executed on the machine running `cdk synth`. This is a feature of the bundling mechanism, unrelated to `BucketDeployment`, which just uploads the artifact of the build process to the destination bucket.

Does this offer some mitigation for your use-case?

**Comment by sachin10101998** [comment]
+1
