### ISSUE TITLE
(lambda-nodejs): Support for running CDK in a subfolder

### ISSUE THREAD

**Issue by adam-nielsen** [aws/aws-cdk#11747]
If CDK is set up inside a `deploy` subfolder in your project, with your stack using relative paths outside this area (e.g. `../index.js`) then the build fails with a Parcel error, because the file is not accessible within the Docker container.

There should be a way of specifying the root for the Docker container (if it can't detect this automatically from the `entry` filename) so that you can successfully reference files above the CDK root directory.

### Use Case

I want the root of my project to have my own `node_modules`, `package.json`, etc. so I can publish it on npmjs.org if I choose.  I also want to use CDK to deploy it, with all CDK's files inside a `deploy` subfolder, so I can run the deploy the same way as I run my unit tests.

I have tried this already, but I run into a few issues:

* If I make a `deploy` folder and run `cdk init` in there, I end up with a `DeployStack` instead of `MyProjectStack`.

* If I create a `myproject` folder, `cdk init` inside that, then rename the folder to `deploy` then I end up with `MyProjectStack` as desired.  However when I go to deploy the stack, I get Parcel packaging errors.  The problem is my CDK stack refers to paths like `../src/mylambda.js` which exist above the CDK project root folder.  These files thus are not available inside the Docker container used for packaging, so I get an error about being unable to access the files.

### Proposed Solution

Allow the root of the Docker container to be specified in the `NodejsFunction` props, so that files above the CDK root such as `../index.js` can be accessed.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by jogold** [comment]
There's the `projectRoot` prop for this in the version you're using.

As of v1.75.0 it's now `depsLockFilePath`.

**Comment by adam-nielsen** [comment]
Oh, you are right!  When it mentioned `package.json` it didn't click that this meant mine and not CDK's.  I tried this option and it completely solved my problem.

Many thanks for your help :)
