### ISSUE TITLE
local environment emulation: Re-creating your AWS infrastructure locally

### ISSUE THREAD

**Issue by danielblignaut** [aws/aws-cdk#11746]
Hey guys,

I've started working on using CDK on quite a large project. One qualm I've had with working with AWS serverless technologies is the real lack / gaps in the local development environment setup. I've looked at trying to parse cloudformation templates directly which is an option but what I've managed to do with CDK is create a script that uses aspects to aggregate all instances of low-level CDK constructs that are integral to my infrastructure (i.e. for now I ignore roles and permissions for examples), and then loop through these aspects and try to re-create them locally (DynamoDb local, Step functions local, localstack, my own hacky lambda server for step functions that invoke lambdas). There's still a lot of gaps here but I think there is huge potential to use CDK to deploy these resources locally for local development and end to end tests. Is there room for something like this in the CDK project? And is the local development emulation experience something that's currently being worked on?

### Use Case

Improve local development experience

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
You can *try* using LocalStack, or something that emulates AWS. I think it might even have a fake CloudFormation implementation.

I appreciate the desire, and if you can make it work with some small additional indirections in the code all the more power to you, and we definitely won't reject patches that introduce the necessary flexilibity.

But in general I'm afraid it's just not possible to try and chase the feature set and development speed of AWS in these clone projects, and it's unlikely we will invest significant effort into making it more easy. 

If you can make it work for yourself: great! But unless and until it satisfies 90+% of our user base we're better off recommending you to test against actual AWS services in a developer account (and trying to make that as easy as possible) than in chasing emulation.
