### ISSUE TITLE
route53 public hosted zone: Updating NS Record

### ISSUE THREAD

**Issue by youngjeong46** [aws/aws-cdk#11757]
### The Question
I created a Public Hosted Zone using a domain that I'm bringing from the outside (by calling Route53.PublicHostedZone). When you create a zone it produces an NS record automatically, but I need to update it with the NS records from the place of domain purchase. Simply creating an NS record with route53.RecordSet does not replace the existing one, and throws an error during stack creation saying it already exists. How could I solve this issue?

### Environment

  - **CDK CLI Version:** 1.75.0
  - **Module Version:** 1.75.0
  - **Node.js Version:** 14.15.1
  - **OS:** OSX Catalina
  - **Language (Version):** Typescript 4.1.2

**Comment by jumi-dev** [comment]
@youngjeong46 In my opinion, it's not an CDK issue. In your scenario, you don't have to create/update the NS records in Route 53.

Instead, you have to update the NS records at your external provider where you've purchase the domain. The NS record defines which name server is responsible for a domain (or subdomain). By default, the external provider where you've purchased the domain is responsible. When you maintain the NS records at the external provider with the information from Route 53, you're hosted zone will be active.

More details can be found in the documentation:
https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/MigratingDNS.html

**Comment by youngjeong46** [comment]
Oops, sorry. I had that all backwards, you are right. I have to change the DNS server on the side of where I purchased the domain with the ones created from Route53 Zone. It's been fixed, thanks!
