### ISSUE TITLE
(aws-lambda-python): Manage dependencies with Poetry

### ISSUE THREAD

**Issue by Padwicker** [aws/aws-cdk#11753]
Are there any plans to support dependency management using Poetry in the same way that requirements.txt and Pipfile are?

Use Case

Poetry is a increasingly popular dependency management/packaging solution for Python and is arguably more user friendly than either pipenv or pip. It would be great if this method had direct support.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by setu4993** [comment]
I took a stab at this in https://github.com/aws/aws-cdk/pull/11850.
