### ISSUE TITLE
(pipelines): pass variables between stacks

### ISSUE THREAD

**Issue by erudisch** [aws/aws-cdk#11756]
## :question: General Issue

Within a `@aws-cdk/core.Stage` I create two `@aws-cdk/core.Stage.Stack`.

```
        const backendService = new BackendStack(this, 'Backend', {
            env,
        });
        
        new FrontendStack(this, 'Frontend', {
            env,
            apiUrl: backendService.hcEndpoint,
        }).addDependency(backendService);
```

BackendStack:
```
export class BackendStack extends cdk.Stack {
  public readonly hcEndpoint: cdk.CfnOutput;

  constructor(scope: cdk.Construct, id: string, props: BackendStackProps) {
    super(scope, id, props);

    const api = new apigw.LambdaRestApi(this, 'Rest-API',{
      handler: <some_handler>
    })

    this.hcEndpoint = new cdk.CfnOutput(this, 'GatewayUrl', {
      value: api.url,
      exportName: 'GatewayUrl'
    });
  }
}
```

FrontendStack:
```
export class FrontendStack extends cdk.Stack {
    constructor(scope: cdk.Construct, id: string, props?: FrontendStackProps) {
        super(scope, id, props);

        new s3deployment.BucketDeployment(this, 'Frontend-Deploy', {
          ...,
          sources: [
            s3deployment.Source.asset('../frontend', {
              bundling: {
                image: <some_image>,
                command: [
                  'bash', '-c', [
                    'npm i',
                    'REACT_APP_API_URL=$API_URL npm run build',
                    'cp -r /asset-input/build/* /asset-output/',
                  ].join(' && '),
                ],
                environment: {
                  API_URL: apiUrl?.value
                }
              },
            }),
          ],
        });
    }
}
```

After everything is deployed, the passed `apiUrl` is not fully resolved: `https://${Token[TOKEN.265]}.execute-api.eu-west-1.${Token[AWS.URLSuffix.1]}/${Token[TOKEN.283]}/`.
According to this issue: https://github.com/aws/aws-cdk/issues/7079, Tokens are resolved in the `prepare` phase.

Here is a snippet of my pipeline:

<img width="299" alt="Screenshot 2020-11-27 at 23 59 56" src="https://user-images.githubusercontent.com/57360330/100488134-aacf1a00-310c-11eb-969d-cfb9a8e4de2d.png">

Why is the Token not resolved within the `FrontendStack` `prepare` phase?

### Environment

  - **CDK CLI Version:** 1.75.0
  - **Module Version:** 1.75.0
  - **Node.js Version:** 13.8.0
  - **OS:**OSX Catalina
  - **Language (Version):** TypeScript (4.1.2

**Comment by hoegertn** [comment]
You are trying to use the token during bundling which is happening in the synth phase. So the value is not resolved yet.
There is no way to know the value already during synth. You have to load it in your webapp from somewhere else.

**Comment by rix0rrr** [comment]
Don't do this:

```
    this.hcEndpoint = new cdk.CfnOutput(this, 'GatewayUrl', {
      value: api.url,
      exportName: 'GatewayUrl'
    });
```

Just pass the `api.url` directly from one stack to the other.

**Comment by shellscape** [comment]
@rix0rrr premature close, bummer. the OP's question hasn't been answered with a viable solution.
