### ISSUE TITLE
(aws-transfer): L2 construct for `CfnServer`

### ISSUE THREAD

**Issue by iliapolo** [aws/aws-cdk#11751]
### Use Case

Increase L2 coverage.

### Proposed Solution

Standard

### Other

We should consider this issue when we pick this up.

https://github.com/aws/aws-cdk/issues/11374

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by revmischa** [comment]
Would love this!
Looks like there is something on construct hub: https://constructs.dev/packages/@richkang/cdk-construct-transfer-sftp-s3-kms/v/0.1.1?lang=typescript
