### ISSUE TITLE
(core): CfnParameter valueAsList -> List<String> is added as Token

### ISSUE THREAD

**Issue by bundgaard** [aws/aws-cdk#11750]
When deploying the stack, #TOKEN will be written out in the resource and no conversion from TOKEN to real values happens

`cdk deploy --parameters=oneitem stack`

### Reproduction Steps
```kotlin
val externListOfStrings = CfnParameter(this, "externalListOfIds", CfnParameterProps.builder()
                .type("List<String>")
                .description("list of strings for some purpose")
                .build())
externListOfStrings.valueAsList -> #TOKEN{...}
```

### What did you expect to happen?

The incoming comma separated list of strings would be converted into listOf("a","b","c") or in this case listOf("oneitem")

### What actually happened?
The token was written out to the resource and no mapping happend.

### Environment

  - **CDK CLI Version  : 1.74**
  - **Framework Version: 1.63**
  - **Node.js Version:** v12.19.0
  - **OS               : Linux **
  - **Language (Version):**  Kotlin

### Other

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
You need to show me how you are using `externListOfStrings.valueAsList`.

Just writing:

```
externListOfStrings.valueAsList -> #TOKEN{...}
```

Doesn't tell me enough.

If you `console.log()`ged that value, then yes this is what you will see.

If you converted the value to a string in another way before using it, this is what you will see.

If you use the value in another CDK construct, you will NOT see this.
