### ISSUE TITLE
(secretsmanager): Access secret string stored in secret manager from CDK

### ISSUE THREAD

**Issue by simran66** [aws/aws-cdk#11758]
I am storing the Codestar connection string for Bitbucket in Secret manager. How can I retrieve it in the CDK app:

I am trying with:

    // Get Bitbucket Connection String
    const bitbucketConnectionString = Secret.fromSecretCompleteArn(this, "bitbucketConnectionString", "arn:aws:secretsmanager:us-west-2:1000000000:secret:BitbucketCloudConnection-abcdef0");
    
    
    // SourceAction
    const sourceAction = new BitBucketSourceAction({
        actionName: 'BitbucketSource',
        owner: 'abc',
        repo: repoName,
        output: sourceOutputArtifact,
        connectionArn: bitbucketConnectionString,
    })

`bitbucketConnectionString` is not a string though. 

1. How do I access the secret value which is actually a connectionString stored in Secret Manager. 
2. What is the right way to replace region and accountId with Pseudo variables in the connection string;

    arn:aws:secretsmanager:us-west-2:1000000000:secret:BitbucketCloudConnection-abcdef0

**Comment by jogold** [comment]
You need to use the `SecretValue` class from `core`: https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/core/README.md#secrets

**Comment by simran66** [comment]
@simran66  Did you mean bitbucketConnectionString.secreValue ? It doesn't return me a string. Can you share in the context of the question, please? I read through the page and didn't understand still

**Comment by jogold** [comment]
```ts
// SourceAction
const sourceAction = new BitBucketSourceAction({
    actionName: 'BitbucketSource',
    owner: 'abc',
    repo: repoName,
    output: sourceOutputArtifact,
    connectionArn: SecretValue.fromSecretsManager('BitbucketCloudConnection-abcdef0').toString()
})
```

Just like the example in the README

**Comment by SomayaB** [comment]
Closing since jogold's guidance seems to have solved the issue.
