### ISSUE TITLE
(lambda):removing vpc from lambda, fail to remove automatic security group and associated ENIs

### ISSUE THREAD

**Issue by davegariepy** [aws/aws-cdk#11765]
I deployed a lambda using the `aws-lambda-nodejs` packaged to a vpc to see if it would work. It worked, but then when I went to move it back out of the VPC the security group and associated ENIs failed to delete. I had to manually log into the console, delete the ENIs then delete the security group.

### Reproduction Steps

https://docs.aws.amazon.com/cdk/api/latest/docs/aws-lambda-nodejs-readme.html

### What did you expect to happen?

move lambda out of vpc 

### What actually happened?

lambda was updated but vpc security group and associated ENIs were not deleted, causing cloudformation to error

### Environment

  - **CDK CLI Version  :** 1.75
  - **Framework Version:** 1.75
  - **Node.js Version:**  v12.19.0
  - **OS               :** macOS 10.14.6 
  - **Language (Version):** JavaScript

### Other

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
This sounds like the same issue as this one - https://github.com/aws/aws-cdk/issues/6701. Can you confirm?

**Comment by davegariepy** [comment]
Hi @nija-at, yes that seems like the same thing. 

I used the output from the vpc construct directly instead of with `fromVpcAttributes`. Also, I wasn't destroying the stack, just updating to not include the vpc in the NodeJs lambda's construct options. The end goal of deleting the security group and ENIs are the same, so those details probably don't matter.

**Comment by nija-at** [comment]
Resolving this one in favour of the duplicate. A workaround is posted in the other issue.
