### ISSUE TITLE
(secretsmanager): Can't get the tags of imported Secret

### ISSUE THREAD

**Issue by ilko-rbi** [aws/aws-cdk#11761]
It seens that at the moment there is no way to read the tags of imported secret

### Reproduction Steps

1st Approach with high level ISecret constuct

```python
imported_secret = asm.Secret.from_secret_attributes(
        scope=scope, id=secret_arn, secret_complete_arn=secret_arn, encryption_key=key
    )
imported_secret.tags # -> no such attribute
core.Tags.of(imported_secret) # ... no idea how to come to the tags???
```

2nd approach - CfnSecret:
```python
imported_secret = asm.Secret.from_secret_attributes(
        scope=scope, id=secret_arn, secret_complete_arn=secret_arn, encryption_key=key
    )
cfn = imported_secret.node.default_child
cfn.tags.tag_values() # cfn is NoneType ???
```

### What did you expect to happen?

To be able to list the tags of an existing secret

### What actually happened?

Seems that at the moment this is either not possible or I have no clue how to do it.

### Environment

  - **CDK CLI Version  : 1.73.0**
  - **Framework Version:**
  - **Node.js Version: v10.19.0**
  - **OS               : ubuntu 18**
  - **Language (Version): Python 3.7.7** 

### Other

--- 

This is :bug: Bug Report

**Comment by njlynch** [comment]
In general, imported resources only have information that you have provided (plus sometimes some sane defaults). Imported constructs (e.g., those generated by `from_*` methods) are simply a way to convert a resource's ARN (or other identifier) into an `IConstruct`/`IResource`/`IFoo` that can be passed into another construct. They do not make AWS API calls to retrieve additional information about a resource.

In contrast, there are a small handful of `from_lookup` or similar methods that actually *do* make AWS API calls to populate other properties of a resource. There is an existing open feature request for a lookup method for secrets (see #1689), which is primarily concerned with being able to automatically determine the encryptionKey used for a secret. Feel free to add your use case there as additional motivation for that issue to be prioritized.

Another option would be to create a custom resource yourself which would do the lookup of the tags based on the secretArn.

**Comment by ilko-rbi** [comment]
Thanks for the info. I have two additional questions:

1) I've tried to use custom resource and failed to use the returned reference in python - whatever I've tried to convert it to I was not able to get "compilable" code, is there an example for this somewhere? The type of the Tag structure from [describeSecret](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SecretsManager.html#describeSecret-property) method is a list of mappings and I don't know how to handle it, trying to_string(), to_json() Token.as_list(), etc - nothing worked.

2) I think that I have a general understanding issue with the Tags implementation - my assumption was that each construct should have the `tags` attribute so that I can always use `constr.tags.tag_values()`. Unfortunately this is not the case, so that a reference to the documentation / examples / code would be very helpful how it is supposed to list the available tags of a resource - preferably in python.

**Comment by njlynch** [comment]
> I've tried to use custom resource and failed to use the returned reference in python - whatever I've tried to convert it to I was not able to get "compilable" code

The return from a custom resource will be a [Token](https://docs.aws.amazon.com/cdk/latest/guide/tokens.html), and won't be directly manipulatable by your CDK code (e.g.., tags[0].value). One way to manipulate and work with tokens is to use CloudFormation intrinsic functions like [Fn.select](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.core/Fn.html#aws_cdk.core.Fn.select) or [Fn.get_att](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.core/Fn.html#aws_cdk.core.Fn.get_att). In this case, using a [`AwsCustomResource`](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.custom_resources.README.html#custom-resources-for-aws-apis) might be useful; you can use that pattern to access specific tags of the response directly (e.g., `aws_custom1.get_response_field("Items.0.Key")`). Depending on your use this, this approach might work.

> [A] reference to the documentation / examples / code would be very helpful how it is supposed to list the available tags of a resource - preferably in python.

I'm afraid I don't have an example for you off-hand. The existing methods in the CDK are concerned with defining the tags (adding/removing) much more so than reading existing tags. I would suggest you try this question over to the \#aws-cdk or \#examples Slack channel of [cdk.dev](https://cdk.dev). Lots of folks there who are working with the CDK and might have done something similar.
