### ISSUE TITLE
(aws-lambda-nodejs): can't build with lambda layers

### ISSUE THREAD

**Issue by elthrasher** [aws/aws-cdk#11762]
The `NodejsFunction` fails with the following error when attempting to build with a lambda layer.
```bash
$ cdk synth
Converting circular structure to JSON
    --> starting at object with constructor 'LayerVersion'
    |     property 'node' -> object with constructor 'ConstructNode'
    --- property 'host' closes the circle
Subprocess exited with error 1
error Command failed with exit code 1.
```

### Reproduction Steps

I created a repo to demonstrate the error here: https://github.com/elthrasher/circular-layer
Should be reproducible with any NodejsFunction + layer combo. Instructions in the README.

### What did you expect to happen?

Add a lambda layer to a NodejsFunction construct.

### What actually happened?

Got the error above.

### Environment

  - **CDK CLI Version: 1.75.0**
  - **Node.js Version: 12.19.1**
  - **OS: macOS Catalina**
  - **Language (Version): TypeScript (all)**

### Other

There is a workaround available (see https://github.com/elthrasher/circular-layer).

--- 

This is :bug: Bug Report

**Comment by elthrasher** [comment]
Just thought to check earlier versions and I see the same issue prior to cdk 1.75.0 so I don't think it was introduced with esbuild.

**Comment by jogold** [comment]
#11698
