### ISSUE TITLE
(aws-eks): Add validate flag to KubernetesManifest class to pass invalidated objects

### ISSUE THREAD

**Issue by shrivastavshubham34** [aws/aws-cdk#11763]
It would be great if we could pass unvalidated resources.
Since the flag **--validate=false** was added to kubectl. We could probably have a constructor attribute called validate.

### Use Case

I'm trying to add an ALB ingress controller to the EKS cluster. But right now cannot do that through CDK.
I need to add cert-manager which needs to be run without validation.
**Source**:[EKS-ALB-Ingress-Guide](https://docs.aws.amazon.com/eks/latest/userguide/alb-ingress.html)
``` 
kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v1.0.2/cert-manager.yaml
```

### Proposed Solution

Add constructor props to KubernetesManifest class to include **--validate** as an boolean argument.
Also add a validate prop to addManifest() function of @aws-cdk/aws-eks.Cluster class

```
        cluster.add_manifest('alb-ingress-controller-core',*manifest,validate=false)

```
---

This is a :rocket: Feature Request

**Comment by shrivastavshubham34** [comment]
Hi, do we have an ETA for this? If not I can switch to EKSCTL for the time being, 😄

**Comment by andremcdecarvalho** [comment]
Hello everyone, 

When will this feature be available? I'm developing a US story and I'm facing this exact problem. 

Thanks in advance!

**Comment by iliapolo** [comment]
This will be available in the next release.

**Comment by shrivastavshubham34** [comment]
Thanks @iliapolo !
