### ISSUE TITLE
(lambda): Cannot deploy LayerVersion (Some files do not have read permissions)

### ISSUE THREAD

**Issue by artyom-melnikov** [aws/aws-cdk#11776]
I'm using Java version of the CDK. While deploying Shared Layer I receive the following error:
```
Layer conversion failed: Some files do not have read permissions; (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 4adda2ee-ff96-4287-b145-ceade1db3687)
```

### Reproduction Steps

This is how I create layer:
```java
        this.sharedLayer = new LayerVersion(this, withEnv("lambda-layer", env),
            LayerVersionProps.builder()
                .compatibleRuntimes(Collections.singletonList(Runtime.JAVA_11))
                .description("Shared layer with all lib jars")
                .code(Code.fromAsset(LAMBDA_LIBS_PATH))
                .layerVersionName(withEnv("lambda-layer", env))
                .build());
```

My layers zip is generated via Gradle:
```kotlin
tasks.register<Zip>("packageLibs") {
    archiveFileName.set("lambda-libs.zip")
    into("java/lib") {
        from(configurations.runtimeClasspath)
    }
    dirMode = 755
    fileMode = 755
}
```

### What did you expect to happen?

The LayerVersion should be created

### What actually happened?

```
Layer conversion failed: Some files do not have read permissions; (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 4adda2ee-ff96-4287-b145-ceade1db3687)
```

### Environment

  - **CDK CLI Version  :** 1.75.0
  - **Framework Version:** 1.73.0
  - **Node.js Version:** v12.18.3 
  - **OS               :** Windows 10
  - **Language (Version):** Java 11 

### Other

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
This doesn't seem directly related to the CDK. The lambda backend service doesn't seem to like something in your `.zip` file.

Are you able to post the contents of the zip file for further investigation?

**Comment by artyom-melnikov** [comment]
Yeah, I investigated it and it seems like the permissions preserved in the zip file were the reason
