### ISSUE TITLE
(aws-eks): kubectlProvider can run out of memory

### ISSUE THREAD

**Issue by winjer** [aws/aws-cdk#11787]
When using the HelmChart resource it is possible to deploy changes that cause the provider to run out of memory. 

### Reproduction Steps

create an `eks.HelmChart` for a large chart update. In my case it was to `efs-provisioner`.

### What did you expect to happen?

It to work.

### What actually happened?
```2:20:16 PM | UPDATE_FAILED        | Custom::AWSCDK-EKS-HelmChart | ChartD6199871
Response object is too long.

        new CustomResource (/home/doug/projects/trustsrv.io/node_modules/@aws-cdk/core/lib/custom-resource.ts:115:21)
        \_ new HelmChart (/home/doug/projects/trustsrv.io/node_modules/@aws-cdk/aws-eks/lib/helm-chart.ts:104:5)
        \_ Object.exports.deployRelease (/home/doug/projects/trustsrv.io/src/core/cluster/charts.ts:68:5)
        \_ Object.exports.systemCharts (/home/doug/projects/trustsrv.io/src/core/cluster/charts.ts:104:9)
        \_ processTicksAndRejections (internal/process/task_queues.js:97:5)
```

In the logs for the kubectl provider lambda function i got:

```fatal error: runtime: out of memory```

and a whole lot of go traceback.

### Environment

  - **CDK CLI Version  :** 1.59.0
  - **Framework Version:** 1.59.0
  - **Node.js Version:** 14.2
  - **OS               :** Debian
  - **Language (Version):** Typescript 3.7.3

### Other

I resolved this by manually changing the memory on the kubectl provider python lambda function and giving it 1024MB, using the console.

--- 

This is :bug: Bug Report

**Comment by jumi-dev** [comment]
I run into the same error message today ("Response object is too long") when I deployed a larger Kubernetes Manifests using `eks.addManifest`.

It should be the same issue. In both cases, the deployment is done using the kubectl provider lambda.

Maybe this information is relevant if you do some tests etc.
