### ISSUE TITLE
(cli): placeholders in cloudformation-execution-policies  are not replaced when bootstrapping

### ISSUE THREAD

**Issue by redbaron** [aws/aws-cdk#11786]
### Reproduction Steps

Run
```
CDK_NEW_BOOTSTRAP=1  cdk bootstrap --trust 999999999 aws://88888888/eu-west-2 \
--cloudformation-execution-policies 'arn:${AWS::Partition}:iam::aws:policy/AdministratorAccess'
```

### What did you expect to happen?

Placeholders are replaced in a value passed to  ` --cloudformation-execution-policies` 

### What actually happened?

Value used as-is, resulting in CF error:

```
1:22:56 PM | CREATE_FAILED        | AWS::IAM::Role        | CloudFormationExecutionRole
ARN arn:${AWS::Partition}:iam::aws:policy/AdministratorAccess is not valid. (Service: AmazonIdentityManagement; Status Code: 400; Error Code: InvalidInput
```

### Environment

  - **CDK CLI Version  :** 1.75.0
  - **Framework Version:** ??
  - **Node.js Version:** 14.15.1
  - **OS               :** OpenSUSE
  - **Language (Version):** all

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
It's true that these strings are not replaced. I don't think we tell you anywhere that they would be.

More of a feature request than a bug, imo.
