### ISSUE TITLE
(CloudFront): Support TrustedSigners & Key Groups

### ISSUE THREAD

**Issue by stmasc** [aws/aws-cdk#11791]
In CloudFront in AWS Console I can create Public Keys, Key Groups and associate a Web Distributions Behavior with the trusted Key Group. I'd like to, at a minimum, create Key Groups and associate them with behaviors so I can serve private content out of Web Distributions created by CDK.

### Use Case

I want to serve private content out of a Web Distribution created via CDK.

**Comment by stoyan-scava** [comment]
IMO it'd be best to add `trustedKeyGroups` to the `Behavior` interface of CloudFrontWebDistribution.

For the time being, I'm adding the trusted key group with a raw override of the CloudFormation template.
```
cfnDistribution.addOverride("Properties.DistributionConfig.DefaultCacheBehavior.TrustedKeyGroups", ["<my cloudfront key group id>"]);
```

**Comment by saksham** [comment]
Would be great to have this. I am resorting to L1 construct for creating my cloudfront distribution due to lack of this feature. My use case is exactly the same as that from @stmasc. Thanks!

**Comment by ronak2121** [comment]
Would the fix for this issue also add support for this in CloudFormation?

**Comment by ilgarm** [comment]
Also interested in this feature

**Comment by NateBank** [comment]
> IMO it'd be best to add `trustedKeyGroups` to the `Behavior` interface of CloudFrontWebDistribution.
> 
> For the time being, I'm adding the trusted key group with a raw override of the CloudFormation template.
> 
> ```
> cfnDistribution.addOverride("Properties.DistributionConfig.DefaultCacheBehavior.TrustedKeyGroups", ["<my cloudfront key group id>"]);
> ```

Isn't CloudFrontWebDistribution deprecated though?  The CloudFront overview says ```Users are encouraged to use the newer Distribution instead, as it has a simpler interface and receives new features faster.```  I also am interested in how to set up trusted signers or whatever the new flavor of this is supposed to be using the correct construct.

**Comment by okonon** [comment]
I just ran into this myself. I have a need to have private only dist and serve content using signed urls. https://github.com/aws/aws-cdk/issues/12584

**Comment by okonon** [comment]
@njlynch i wonder if there are any updates regarding this request

**Comment by njlynch** [comment]
@okonon  - No progress to report at the moment; I'm afraid I can't comment on when we'll be able to deliver this.

That being said, given the current :+1:s, I've bumped this up to a p1 to note it's a top priority. I am also more than willing to work with anyone who's motivated to contribute to this (discuss design/review PRs).

I see this as (likely) 3 separate tasks/PRs, and can split them out for tracking purposes if anyone wants to tackle just one:
1. Creation of a `PublicKey` L2 construct. (Medium)
2. Creation of a `KeyGroup` L2 construct. (Small-to-Medium)
3. Integration of the `KeyGroups` with the `Distribution` and `CloudFrontWebDistribution`. (Medium+)

If anyone is interested in contributing, please let me know! Feel free to comment here or hit me up on the cdk.dev Slack channel to discuss design/implementation.
