### ISSUE TITLE
(aws-codeartifact): CfnRepository is missing DomainName parameter?

### ISSUE THREAD

**Issue by heikkis** [aws/aws-cdk#11790]
AWS CodeArtifact CfnRepository is missing eg. domain relationship parameter and cannot be used. Or I'm missing something big.

https://docs.aws.amazon.com/cdk/api/latest/docs/aws-codeartifact-readme.html
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codeartifact-repository.html

I thought that Cfn are following tightly the Cloudformation interface but if not this should be feature request then.

--- 

This is :bug: Bug Report

**Comment by njlynch** [comment]
The actual CloudFormation spec is currently missing these properties at the moment; they are aware and are working on correcting the issue. In the meantime, I've created a patch to add the missing properties (#11804).
