### ISSUE TITLE
(Constructs): How to guide for generating constructs in the support languages 

### ISSUE THREAD

**Issue by 0xjjoyy** [aws/aws-cdk#11806]
Please provide documentation and guidance on how to take a Typescript construct and generate the corresponding python, .net, java, etc CDK construct libraries.

It's not clear beyond the first step of generating the project of how to take this forward and generate the corresponding libraries in the other supported CDK languages.
```
cdk init lib --language=typescript
```

https://github.com/aws/aws-cdk/blob/master/packages/aws-cdk/README.md#cdk-init

Beyond the README, unable to find any other documentation.

Unable to generate python, .NET, Java CDK constructs from the Typescript construct created with the command
```
cdk init lib --language=typescript
```

---

This is a 📕 documentation issue

**Comment by NetaNir** [comment]
Check out [aws-delivlib](https://github.com/awslabs/aws-delivlib). You can also use [Projen](https://github.com/projen/projen) to generate a jsii module:

```
npx projen new jsii
```

**Comment by 0xjjoyy** [comment]
Referencing open issue

https://github.com/awsdocs/aws-cdk-guide/issues/126
