### ISSUE TITLE
(constructs): Document how to take a Python construct to multiple languages

### ISSUE THREAD

**Issue by 0xjjoyy** [aws/aws-cdk#11808]
How can I write my own construct, say in Python, and generate the corresponding constructs in all CDK supported languages?

https://docs.aws.amazon.com/cdk/latest/guide/constructs.html#constructs_author

The documentation only provides details on writing my own construct in one language at at time. I would like to write a construct in the language of my choice and then generate constructs for all CDK languages.

---

This is a 📕 documentation issue

**Comment by NetaNir** [comment]
Hi! 

To create a construct in multi languages you will need to first write it in typescript, and build it using [jsii](https://github.com/aws/jsii). Check out [aws-delivlib](https://github.com/awslabs/aws-delivlib), which is the library we use to release the CDK in all supported languages.

**Comment by 0xjjoyy** [comment]
Thanks, do you have a pointer to your Github repo how CDK constructs is configured to use aws-delivlib? I"m still trying to figure out all the commands and how to use all these projects. All the associated commands required to initialize a project, configure it for multiple language support, then generate the bindings, aren't immediately obvious to me.

**Comment by Jerry-AWS** [comment]
BTW, we have an open issue in the CDK Guide repo to add this information to the Dev Guide. I hope to see some motion on it in the next month or two.

https://github.com/awsdocs/aws-cdk-guide/issues/126

**Comment by 0xjjoyy** [comment]
Thanks @Jerry-AWS , I referenced the issue on a related close issue here
https://github.com/aws/aws-cdk/issues/11806

**Comment by 0xjjoyy** [comment]
@NetaNir is there any roadmap item to be able to write constructs in a language of choice and then reuse these constructs across multiple languages?

**Comment by peterwoodworth** [comment]
Sorry for the delay here.

JSII doesn't work bidirectionally - you need to write TypeScript classes to be able to convert it to all languages. A feature request to make it so you could do the same with Python would essentially be another project entirely, so it's certainly not something we can promise.

On writing TypeScript classes - there has been good documentation on the topic, especially with the release of [Construct Hub](https://constructs.dev)

[This](https://dev.to/aws-builders/a-beginner-s-guide-to-create-aws-cdk-construct-library-with-projen-5eh40 is a great guide on creating your own construct library, and [this](https://aws.github.io/jsii/user-guides/#library-author-guide) is the best source for using JSII

I hope this helps clear things up!
