### ISSUE TITLE
(aws-eks): Support for custom labels to ServiceAccount

### ISSUE THREAD

**Issue by iliapolo** [aws/aws-cdk#11801]
I'd like to be able to pass labels when creating a service account:

```ts
cluster.addServiceAccount('sa', {
  labels: {
    foo: 'bar,
  }
})
```

### Use Case

This initially surfaced as an issue with helm not being able to adopt existing service accounts because it was missing some labels.

More details here: https://github.com/aws/aws-cdk/issues/11475#issuecomment-727263289

While the original issue should actually be resolved differently, Its probably still a good idea to allow for this customization.

### Proposed Solution

Add a `labels` property to `ServiceAccountOptions`. 

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by atlennon** [comment]
Any update on this? I am also running into the issue described in #11475 when trying to deploy the aws-load-balancer-controller helm chart using cdk and getting an error stating that annotations are required for it to be able to use an existing service account.

**Comment by ryan-wendel** [comment]
This would be really nice to have to easily provision an aws-load-balancer-controller in k8s via cdk. Pretty please?

**Comment by caoheyang** [comment]
Any update on this too??  I have the sam features requests.

Thanks.

**Comment by Nintorac** [comment]
Also useful for enabling cluster autoscaler
