### ISSUE TITLE
(cli): progress bar goes over 100%

### ISSUE THREAD

**Issue by moltar** [aws/aws-cdk#11805]
Shows: 121/101

<img width="711" alt="image" src="https://user-images.githubusercontent.com/491247/100749041-b1b0a200-3416-11eb-9299-7bf948674995.png">

### Reproduction Steps

Not sure how, maybe it is because of Nested Stacks?

### What did you expect to happen?

The completed count should be <= total number.

### What actually happened?

The completed count is higher than total count.

### Environment

  - **CDK CLI Version  :** 1.75.0
  - **Framework Version:** 1.75.0
  - **Node.js Version:**  v12.18.4
  - **OS               :** macOS
  - **Language (Version):** TypeScript

### Other

--- 

This is :bug: Bug Report

**Comment by moltar** [comment]
This also might be related to Custom Resource that runs on deployment. E.g. log managing lambdas.

**Comment by SamStephens** [comment]
I'm seeing this too:

[██████████████████████████████████████████████████████████] (158/101)

Interestingly, my denominator is also 101. Is there a bug that prevents the total number going above 101? Or is that just a coincidence?

**Comment by fredsensibill** [comment]
Same thing here...

[██████████████████████████████████████████████████████████] (122/101)

❯ cdk --version
2.15.0 (build 151055e)

**Comment by RomainMuller** [comment]
This is because the change count is derived from `DescribeCHangeSet` but the CLI only ever looks at the first page (so up to `100` changes, plus `1` for the stack itself). I submitted a PR to address this.
