### ISSUE TITLE
(logs): Adding Tags to LogGroups Construct Not working

### ISSUE THREAD

**Issue by super7egazi** [aws/aws-cdk#11814]
### Description
I'm trying to add tags to a LogGroup and tags are not being added. Deployment is successful but not tags are added.

### Reproduction Steps
```
const lg = new LogGroup(this, `lg`, {
        logGroupName: `/aws/appsync/apis/${this.graphQLApi.attrApiId}`,
        removalPolicy: RemovalPolicy.DESTROY,
});
Tags.of(lg).add('stringKey','stringValue');
```

### What did you expect to happen?
Tags to be added to the log group

### What actually happened?
No tags were added

### Environment

  - **CDK CLI Version  :** 1.75.0
  - **Node.js Version:** 12.x
  - **OS               :** MacOs
  - **Language (Version):** typescript 4.0.3

### Other

--- 

This is :bug: Bug Report

**Comment by kedarkolhatkar** [comment]
@super7egazi I am also experiencing same and Tags.of works for most other resources, just not for LogGroup. If anyone knows about a workaround please that will be great!

**Comment by swar8080** [comment]
Strangely adding tags to LogGroup is not supported by CloudFormation (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-loggroup.html) but it is possible to add tags through the API (https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_TagLogGroup.html)

**Comment by rittneje** [comment]
Seems like support was added to CloudFormation for this, but it hasn't been officially released yet due to some security review. https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-logs/pull/53

I assume once that goes through, support can be added to CDK without much difficulty?

**Comment by kornicameister** [comment]
@rittneje @swar8080 to best of my knowledge the support for tags landed in cloud formation. Perhaps work can be resumed here?

**Comment by RaphaelManke** [comment]
I managed to build a workaround by using an Aspect on the stack
```javascript
import { IAspect, Stack } from "aws-cdk-lib";
import { CfnLogGroup, LogGroup } from "aws-cdk-lib/aws-logs";
import { IConstruct } from "constructs";

export class AddTagsToLoggroups implements IAspect {
  public visit(node: IConstruct): void {
    if (node instanceof LogGroup) {
      const loggroupNode = node.node;
      const stackTags = Stack.of(node).tags.tagValues();
      const cfnLoggroup = loggroupNode.findChild("Resource");
      if (!(cfnLoggroup instanceof CfnLogGroup)) {
        throw new Error("Detected Ressource is not a CfnLogGroup");
      }
      for (const [key, value] of Object.entries(stackTags)) {
        cfnLoggroup.tags.setTag(key, value);
      }
    }
  }
}

```


apply to all loggroups


```javascript
const app = new cdk.App();
const stack = new Stack(app, "Stack", {tags: { someTag: "someValue" }});
const loggroup = new LogGroup(stack, `${id}-log-group`, {
      logGroupName: "loggroup-with-tags",
    });
Aspects.of(stack).add(new AddTagsToLoggroups());
```

or apply to only one loggroup


```javascript
const app = new cdk.App();
const stack = new Stack(app, "Stack", {tags: { someTag: "someValue" }});
const loggroup = new LogGroup(stack, `${id}-log-group`, {
      logGroupName: "loggroup-with-tags",
    });
Aspects.of(stack).add(new AddTagsToLoggroups());
```

Maybe that can help in the meantime until it is added to cdk and demonstrate that it is possible to tag loggroups.

**Comment by corymhall** [comment]
I'm going to close this since tags can now be added to LogGroups.
