### ISSUE TITLE
(sns): Subscribing to a Lambda function in another region is not allowed, even though its legal

### ISSUE THREAD

**Issue by NickTheSecurityDude** [aws/aws-cdk#11826]
(aws_sns): Subscribing to a Lambda function in another region is not allowed, even though its legal, and works fine in both the cli and boto3 sdk (as well as the console).

For example create a stack in us-west-2 and try to subscribe to a Lambda function in us-east-1:
```
        my_topic.add_subscription(
            subscription = sns_subs.LambdaSubscription(fn = aws_lambda.Function.from_function_arn(self,
                "US EAST 1 SNS Function",function_arn))
        )
```

You will get the error:
```
8:41:18 PM | CREATE_FAILED        | AWS::Lambda::Permission | US EAST 1 SNS Functi...ogSNSTopic0CEE
Functions from 'us-east-1' are not reachable in this region ('eu-west-1') (Service: AWSLambda; Status Code: 404; Error Code: ResourceNotFoundException; Request ID: 3345c
b-a50e-4asda-9474-390sdfw9f7; Proxy: null)
```

This is :bug: Bug Report

**Comment by NetaNir** [comment]
This error looks like it is thrown by CloudFormation, and the limitation is coming from the service itself? Im not sure we can fix it on the cdk side
