### ISSUE TITLE
(s3): support S3 bucket keys

### ISSUE THREAD

**Issue by hoegertn** [aws/aws-cdk#11828]
Add property to S3 Bucket to configure bucket-level keys.

https://docs.aws.amazon.com/AmazonS3/latest/dev/configuring-bucket-key.html#enable-bucket-key-cloudformation

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by iliapolo** [comment]
@hoegertn Can you please elaborate exactly what you'd like to configure? ideally with a theoretical API?

We already have support for passing an encryption key and the encryption type:

https://github.com/aws/aws-cdk/blob/968df9715123d92ef6be302cd6c852a14c350856/packages/%40aws-cdk/aws-s3/lib/bucket.ts#L1001

https://github.com/aws/aws-cdk/blob/968df9715123d92ef6be302cd6c852a14c350856/packages/%40aws-cdk/aws-s3/lib/bucket.ts#L1013

Are you referring to the `BucketEnabledKey` we currently don't support and the ability to configure multiple rules?

**Comment by hoegertn** [comment]
Exactly, this is meant as a tracking ticket for the newly released BucketEnabledKEy field to enable bucket-level keys for S3
