### ISSUE TITLE
(ecs-service-extensions): Add return type to key interface ServiceExtension methods

### ISSUE THREAD

**Issue by brentryan** [aws/aws-cdk#11836]
The new [ServiceExtension](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk-containers/ecs-service-extensions/lib/extensions/extension-interfaces.ts) abstract class does not define return types on the key interface methods. This makes it a little more painful to implement your own ServiceExtension classes because you don't know what to return on each interface method. The only way to figure this out is to go look at the source code of the interface. Instead, this could be fixed by simply adding the return type to each method.

### Use Case

Easier to implement key extension point.

### Proposed Solution

Add return types to each interface method.

Example:
 
```
public modifyTaskDefinitionProps(props: ecs.TaskDefinitionProps):  ecs.TaskDefinitionProps {
    return {
      ...props,
    } as ecs.TaskDefinitionProps;
}

```

* [X] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by nathanpeck** [comment]
Great suggestion! I can't believe I missed that the first time. Will address in a PR soon

**Comment by nathanpeck** [comment]
Just opened https://github.com/aws/aws-cdk/pull/11916

**Comment by nathanpeck** [comment]
Thanks for calling this out! The PR has been merged and this change will be available in the next version of CDK (generally released late Tuesday night or early Wednesday morning in EST time)
