### ISSUE TITLE
(aws-ec2): ApplicationLoadBalancer - Expose created Listeners as collection

### ISSUE THREAD

**Issue by rcollette** [aws/aws-cdk#11841]
Listeners that are created via calls to `addListener()` should be exposed as a collection property of `ApplicationLoadBalancer`.

### Use Case
When the ALB is created through mechanisms outside of my direct control, such as `ApplicationLoadBalancedFargateService`, I am unable to alter listener properties such as the sslPolicy (see https://github.com/aws/aws-cdk/issues/8816).

### Proposed Solution
There is a general OO design principal that goes something like "that which creates contains".   (At least according to [Craig Larman](https://www.amazon.com/Applying-UML-Patterns-Introduction-Object-Oriented/dp/0131489062) there is).  This principal seems to be followed generally throughout the CDK but seems to have been missed in this instance.

Add a public Listeners property which includes listeners that were added via `addListeners`.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rcollette** [comment]
I tried monkey patching in my stack like:

```typescript
        const loadBalancer = new ApplicationLoadBalancer(this, 'LB', {
            vpc: cluster.vpc,
            internetFacing: this._props.publicLoadBalancer !== undefined ? this._props.publicLoadBalancer : true
        });
        const originalAddListener = loadBalancer.addListener;
        loadBalancer.addListener = (id: string, props: BaseApplicationListenerProps): ApplicationListener => {
            // ELBSecurityPolicy-FS-1-2-2019-08
            const newProps = {...props, sslPolicy: SslPolicy.FORWARD_SECRECY_TLS12};
            return originalAddListener(id, newProps);
        };
        const fargateService = new ApplicationLoadBalancedFargateService(this, this._props.serviceName, {
            cluster,
            loadBalancer,
        ...
        ...
```

but I ran into an error (whose stack I had to obtain using VSCode debugging, I wish the stack would just print out when using the cdk command line).   The code above is roughly what `ApplicationLoadBalancedFargateService` does to create the load balancer so I'm not sure why this error is happening.

```
/Users/richardcollette/Documents/code/sdm/cdk/cdk-resources/node_modules/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-listener.ts:192
        pathPattern: props.pathPattern,
                                          ^
node_modules/source-map-support/source-map-support.js:475
TypeError: Cannot read property 'loadBalancerArn' of undefined
    at new ApplicationListener (/Users/richardcollette/Documents/code/sdm/cdk/cdk-resources/node_modules/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-listener.ts:192:43)
    at addListener (/Users/richardcollette/Documents/code/sdm/cdk/cdk-resources/node_modules/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-load-balancer.ts:106:12)
    at ApplicationLoadBalancer.loadBalancer.addListener (/Users/richardcollette/Documents/code/sdm/cdk/cdk-resources/src/fargate/libs/FargateEnvironmentStack.ts:146:20)
    at new ApplicationLoadBalancedServiceBase (/Users/richardcollette/Documents/code/sdm/cdk/cdk-resources/node_modules/@aws-cdk/aws-ecs-patterns/lib/base/application-load-balanced-service-base.ts:385:34)
    at new ApplicationLoadBalancedFargateService (/Users/richardcollette/Documents/code/sdm/cdk/cdk-resources/node_modules/@aws-cdk/aws-ecs-patterns/lib/fargate/application-load-balanced-fargate-service.ts:111:5)
    at FargateEnvironmentStack._createFargateService (/Users/richardcollette/Documents/code/sdm/cdk/cdk-resources/src/fargate/libs/FargateEnvironmentStack.ts:148:32)
```

**Comment by rcollette** [comment]
I have to remember with Typescript that the goto method of overriding behavior is not necessarily Monkey Patching.  Inheritance works.

I would still classify this as a workaround.

```typescript
/**
 * An ApplicationLoadBalancer whose listener ssPolicy is set to SslPolicy.FORWARD_SECRECY_TLS12
 *
 * <p>The default ApplicationLoadBalancer sslPolicy is set to include TLS 1.1 and static ciphers.</p>
 * <p>ApplicationLoadBalancer's constructor properties do not include an option for specifying the default sslPolicy
 * used when the addListener method is called by other constructs such as ApplicationLoadBalancedFargateService and
 * it also does not expose the listeners collection as a property so that the sslPolicy can be modified after the
 * fact.</p>
 * <p>We use this class to provide a means of consistently set the TLS version to corporate standards when using an ALB.</p>
 */
export class ApplicationLoadBalancerStandardized extends ApplicationLoadBalancer {

    public addListener(id: string, props: BaseApplicationListenerProps): ApplicationListener {
        // HACK: cast to any so we can override a "readonly" property.
        (props.sslPolicy as any) = SslPolicy.FORWARD_SECRECY_TLS12;
        return super.addListener(id, props);
    }
}
```

In use
```typescript
// We create the ALB explicitly rather than letting ApplicationLoadBalancedFargateService (ALBFS)
// create it so that we can set the sslPolicy, which is not possible when the ALB is created with ALBFS.
// To match the ALB id that would be generated by ALBFS if it were to create the ALB, we must prefix
// the ALB id with the same id as the ALBFS.
const loadBalancer = new ApplicationLoadBalancerStandardized(this, `${this._props.serviceName}LB`, {
  vpc: cluster.vpc,
  internetFacing: this._props.publicLoadBalancer !== undefined ? this._props.publicLoadBalancer : true
});
const fargateService = new ApplicationLoadBalancedFargateService(this, this._props.serviceName, {
  cluster,
  loadBalancer,
  ...
  ...
```

**Comment by agalazis** [comment]
> I have to remember with Typescript that the goto method of overriding behavior is not necessarily Monkey Patching. Inheritance works.
> 
> I would still classify this as a workaround.
> 
> ```ts
> /**
>  * An ApplicationLoadBalancer whose listener ssPolicy is set to SslPolicy.FORWARD_SECRECY_TLS12
>  *
>  * <p>The default ApplicationLoadBalancer sslPolicy is set to include TLS 1.1 and static ciphers.</p>
>  * <p>ApplicationLoadBalancer's constructor properties do not include an option for specifying the default sslPolicy
>  * used when the addListener method is called by other constructs such as ApplicationLoadBalancedFargateService and
>  * it also does not expose the listeners collection as a property so that the sslPolicy can be modified after the
>  * fact.</p>
>  * <p>We use this class to provide a means of consistently set the TLS version to corporate standards when using an ALB.</p>
>  */
> export class ApplicationLoadBalancerStandardized extends ApplicationLoadBalancer {
> 
>     public addListener(id: string, props: BaseApplicationListenerProps): ApplicationListener {
>         // HACK: cast to any so we can override a "readonly" property.
>         (props.sslPolicy as any) = SslPolicy.FORWARD_SECRECY_TLS12;
>         return super.addListener(id, props);
>     }
> }
> ```

I would rather do:
```
export class ApplicationLoadBalancerStandardized extends ApplicationLoadBalancer {

    public addListener(id: string, props: BaseApplicationListenerProps): ApplicationListener {
            return super.addListener(id, {
              ...props,
              sslPolicy:SslPolicy.FORWARD_SECRECY_TLS12,
            });
    }
}
```

**Comment by hedrall** [comment]
I check implementation around application load balancer. I think, there is two point to consider.
1. `addListener` just call construct of Listener and Listener instance has alb instance.
2. `ApplicationLoadBalancedServiceBase` ( `ApplicationLoadBalancedFargateService` extends this ) creates listener for given alb instance by call `addListner` , but pass only `port` and `oepn` props (ie, not `sslPolicy` and so on).

So, I think, there is two solutions. ( may be 2 is bad )
1. Change props of `ApplicationLoadBalancedServiceBase` to have all props of listener construct. 
2. Change `addListener` method to preserve listener in alb instance property. But  almost all variables in `ApplicationListenerProps` is readonly …

(I’d like to contribute, so look forward to your advice. )
