### ISSUE TITLE
(@aws-cdk/aws-apigatewayv2): Add apiEndpoint to IHttpApi interface

### ISSUE THREAD

**Issue by marcandjulien** [aws/aws-cdk#11845]
I can't use IHttpApi in my stack presently because it is missing the property apiEndpoint. This force me to use HttpApi as type instead of IHttpApi.

### Use Case
Imagine 2 stacks: 
- Stack A represent the backend (Api Gateway + Lambda)
- Stack B represent a CI in Codebuild to build a frontend 

I use the apiEndpoint from stack A to add an environment variable in the Codebuild project in stack B that contain the url of the API.

### Proposed Solution
Add properties to IHttpApi.
```
    /**
     * (experimental) The default endpoint for an API.
     *
     * @experimental
     * @attribute true
     */
    readonly apiEndpoint: string;
```

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by ayush987goyal** [comment]
Hi @marcandjulien , I see the requested property `apiEndpoint` is already present in the `IHttpApi` interface. [Ref](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-apigatewayv2/lib/http/api.ts#L25)

Is there something more this this issue? If not, can we close it?

**Comment by nija-at** [comment]
This has been fixed here - https://github.com/aws/aws-cdk/commit/bc5b9b659444bfbef9cfc3c8666fce7e6f45465a

Thanks for bringing this up @ayush987goyal.

Closing this issue.
