### ISSUE TITLE
aws-cdk: show changes and request approval by default for `NestedStack` substacks

### ISSUE THREAD

**Issue by strottos** [aws/aws-cdk#11840]
Currently when I have a main stack with lots of NestedStacks, when I run `cdk deploy` it doesn't present me with a list of changes and prompt me whether I want to continue. Even if I've accidentally removed all resources it will proceed to delete every resource without prompting.

### Use Case

We managed to heavily break a production system today (which is our fault) by running this in and it just deleted whole heaps of the system without us realising. This is extremely valuable to me and my current team at least.

### Proposed Solution

I just want it to be consistent with how it works for non-nested stacks. I'd imagine it might have to diff each substack but not sure how this works internally in CDK.

### Other

This is a :rocket: Feature Request

**Comment by strottos** [comment]
Possibly related to this issue: https://github.com/aws/aws-cdk/issues/5722

**Comment by NetaNir** [comment]
Yes it is related to https://github.com/aws/aws-cdk/issues/5722. Lets close this one and discuss in https://github.com/aws/aws-cdk/issues/5722
