### ISSUE TITLE
CDK general: Add an export functionality to export an IAM policy with the required permissions for deploy

### ISSUE THREAD

**Issue by MatthewWaanders** [aws/aws-cdk#11856]
Using CDK to deploy complex applications from CI/CD systems requires a lot of manual configuration of IAM policies to ensure that the CI/CD system's assumed role has the permissions required to run the CDK script. As CDK knows what it will deploy, and Amazon knows which permissions are necessary for these actions, please create a command for the CDK that allows exporting a complete IAM policy with all required permissions.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
Without going into more detail about your current setup and your proposed workflow this request is not really actionable.

If you mean, "give me the list of IAM permissions necessary to successfully deploy this CloudFormation template once", that question is actually not as trivially answerable as you think it is.

For one, we actually don't have that list of API calls that could potentially be made anywhere.

For two, it depends on the current state of your stack.

```yaml
Resources:
  MyQueue:
    Type: AWS::SQS::Queue
```

Can require either `sqs:CreateQueue` or `sqs:UpdateQueue`, and just from the template itself we cannot know which one it will be. 

The following template:

```yaml
```

Could require `sqs:DeleteQueue`, or `s3:DeleteBucket`. If it contains custom resources, it might as well require `s3:DeleteObject`, or `ses:SendEmail`.

There is honestly not much more to do than give your CloudFormation execution role admin permissions, and be vigilant about code reviews.

We will be working on mechanisms that make you safer--but the answer does probably not lie in limiting IAM permissions of the CFN execution role.
