### ISSUE TITLE
Documentation: Link objects badly generated

### ISSUE THREAD

**Issue by chefren** [aws/aws-cdk#11864]
### link to reference doc page:

One of many examples:

- <https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-codebuild.IBuildImage.html>
- [python doc](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_codebuild/IBuildImage.html)

### describe your issue:

Links are shown as , eg: ` {@link LinuxBuildImage}`

In the python docs, the html becomes a `mailto` link, eg: `mailto:%7B%40link`

![Screen Shot 2020-12-04 at 2 25 00 pm](https://user-images.githubusercontent.com/2918150/101118084-85766a80-363c-11eb-8553-8864b592de9d.png)

### Expected

For this example

- Default doc should be a link to: <https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-codebuild.LinuxBuildImage.html>
- Python doc should be a link to: <https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_codebuild/LinuxBuildImage.html>

### May be related

To the changes in #5863

---

This is a 📕 documentation issue

**Comment by chefren** [comment]
@RomainMuller I searched for related issues but couldn't find in here or jsii, maybe you are able to assist please?

**Comment by RomainMuller** [comment]
Ah well... `{@link}` is not really supported here (this is a Java-ism)... Not sure why it was introduced in the first place... Unfortunately, the standardisation level for this JS/TSDoc feature is in quite a bad state right now, and this isn't really workable for us right now...

We should actually get those removed for now; or actually implement support for "some" form of `{@link}`.

**Comment by rix0rrr** [comment]
So many things are bad here. I'm not actually convinced it's worth fixing in the current system we have.
