### ISSUE TITLE
(eks): HelmChart support for username / password

### ISSUE THREAD

**Issue by ten-lac** [aws/aws-cdk#11860]
When using the `cluster.addChart` or instantiation of a `HelmChart` object.  Have these entry points support credentials as `helm repo add ...` does where you can pass in `--username` and `--password`

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by andrewdibiasio6** [comment]
This would be great to have. We can not use our private repos without this.

**Comment by quintonn** [comment]
I would like this feature?
