### ISSUE TITLE
(sam): endpointConfiguration should be Object rather than string

### ISSUE THREAD

**Issue by wangajing** [aws/aws-cdk#11861]
I'm using AWS-CDK's CfnAPI to build the APIGateway resource. I need setup endpointConfiguration to PRIVATE with list of vpc endpoints.

In CDK API, it's string: https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-sam.CfnApi.html#endpointconfiguration-1

endpointConfiguration? Type: string (optional)
AWS::Serverless::Api.EndpointConfiguration.
However the type is AWS::Serverless::Api.EndpointConfiguration, which should be an Object. https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-api-endpointconfiguration.html

EndpointConfiguration:
  Type: PRIVATE
  VPCEndpointIds:
    - vpce-123a123a
    - vpce-321a321a
Given this issues, how we can setup endpointConfiguration correctly with list of vpc endpoints? or this is the CDK bug?

### Reproduction Steps
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-api-endpointconfiguration.html

### What did you expect to happen?

endpointConfiguration should be an EndpointConfiguration object to allow pass vpcendpoints and types. 

### What actually happened?

it's a string value. 

### Environment

  - **CDK CLI Version  :** latest cdk documentation. 
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):** 

### Other

--- 

This is :bug: Bug Report

**Comment by njlynch** [comment]
Related to #7493 (the sam resources, in general, are out of date). We don't as of yet have an automated way of keeping it up to date.

**Comment by AKK9** [comment]
This seems to have been fixed in version 1.111.0 but doesn't appear to be mentioned in the changelog, unless it's included in one of those spec updates?

**Comment by skinny85** [comment]
Yes, you're exactly right @AKK9 - it was done here: https://github.com/aws/aws-cdk/pull/15362/files.
