### ISSUE TITLE
(synthetics): Add new runtimes

### ISSUE THREAD

**Issue by flochaz** [aws/aws-cdk#11870]
AWS Cloudwatch synthetics now support two newer version of the nodejs runtime and one new python one.

Would be great to have it available in the aws-synthetics construct

### Use Case

Use latest Cloudwatch synthetics feature

### Proposed Solution

Add new runtimes ref

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by NetaNir** [comment]
commented on the PR, adding here for visibility. 

> 
> The `Canary` module assume the runtime is always Nodejs, and enforce the below:
> 
> 1. The Canary code does include `node_moduels` folder. See synthetics docs: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Synthetics_Canaries_WritingCanary_Nodejs.html
> 2.   The handler file is named `index.handler`
> 
> Before we introduce Python as runtime we need to address it. Im happy to accept a PR which adds the new node runtime in the meantime 
https://github.com/aws/aws-cdk/pull/11866#pullrequestreview-545323050
