### ISSUE TITLE
(lambda): Unnecessary custom resource for Lambda log retention?

### ISSUE THREAD

**Issue by drissamri** [aws/aws-cdk#11878]
### Custom CloudFormation resource is created to set Lambda Log Retention 
When added `logRetention` to a Lambda, a custom resource is created.
```
        return Function.Builder.create(this, id)
                .code(Code.fromAsset("qrcode-service-lambdas/qrcode-processor/target/qrcode-processor.zip"))
                .handler("io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest")
                .runtime(Runtime.JAVA_11)
                .logRetention(RetentionDays.ONE_WEEK)
                .build();
```
It looks like this is a workaround for a lerna issue in CDK itself? https://github.com/aws/aws-cdk/blob/3727c715e17b5fb41a8a7a6f012d5a1936bac347/packages/%40aws-cdk/aws-logs/lib/log-retention.ts#L82-L82

Shouldn't there be a better way/workaround instead of creating unnecessary resources like this in AWS? It's very confusing to explain to people who are less familiar in AWS why this is needed. With AWS SAM/Serverless Framework this is not required. 

### Environment

  - **CDK CLI Version:** 1.75
  - **Language (Version):**  Java (8)

**Comment by jogold** [comment]
This is not a workaround for lerna issue, see the discussions in https://github.com/aws/aws-cdk/issues/248 and in https://github.com/aws/aws-cdk/issues/667.

The comment about the lerna issue simply says that the custom resource here is implemented with a L1 (`CfnResource`) instead of the L2 construct for custom resources (and since the custom resource has been moved to `core` in the meantime it could actually be implemented with the L2 now).

**Comment by drissamri** [comment]
I'm sorry, I was just rephrasing what I was told on the cdk.dev to me before :) 

Even with the core L2 construct it still would be a custom resource?

**Comment by jogold** [comment]
> Even with the core L2 construct it still would be a custom resource?

Yes because a log group is created implicitly when a Lambda function starts to log. So we need a custom resource to cover all the edge cases as discussed in #248 and #667.

**Comment by eladb** [comment]
As @jogold said above, the custom resource is needed because the log group is implicitly created.
