### ISSUE TITLE
(cloudfront): Behavior with LambdaFunctionAssociation removes function reference

### ISSUE THREAD

**Issue by jwoytek** [aws/aws-cdk#11881]
After upgrading to 1.76, a `cdk diff` on an existing, deployed infrastructure indicates that the LambdaFunctionAssociation for all of the CloudFront Behaviors will be removed. The EventType is left in the resulting template, with no LambdaFunctionARN. 

We are using the Python bindings.

### Reproduction Steps

  1. `cdk synth`
  2. `cdk diff`

Relevant code: 

```python
        sec_func_ver = get_lambda_latest_version_num(self.sec_lambda_arn, 'us-east-1')
        sec_func = Function.from_function_arn(self, 'sec-func-redacted',
                                              f"{self.sec_lambda_arn}:{sec_func_ver}")
        sec_fassoc = LambdaFunctionAssociation(event_type=LambdaEdgeEventType.VIEWER_RESPONSE,
                                               lambda_function=sec_func)

# ...

       forward_cookies = {
            'forward': 'none'
        }
        forward_headers = [
            'Access-Control-Request-Headers',
            'Access-Control-Request-Method',
            'Origin',
        ]
        fvalues = CfnDistribution.ForwardedValuesProperty(headers=forward_headers, query_string=False,
                                                          cookies=forward_cookies)
        b6 = Behavior(allowed_methods=CloudFrontAllowedMethods.GET_HEAD,
                      is_default_behavior=False,
                      path_pattern='/redacted/static-*',
                      default_ttl=core.Duration.seconds(300),
                      min_ttl=core.Duration.seconds(0),
                      max_ttl=core.Duration.seconds(86400),
                      forwarded_values=fvalues,
                      lambda_function_associations=[sec_fassoc]
                      )
```

### What did you expect to happen?

As there are no changes here from prior to the upgrade, the template should have remained the same.

### What actually happened?

The resulting template diff shows that the LambdaFunctionARN has been removed:

```
Resources
[~] AWS::CloudFront::Distribution redacted-distribution/CFDistribution redacteddistributionCFDistributionDredacted 
 └─ [~] DistributionConfig
     ├─ [~] .CacheBehaviors:
     │   └─ @@ -26,8 +26,7 @@
     │      [ ] },
     │      [ ] "LambdaFunctionAssociations": [
     │      [ ]   {
     │      [-]     "EventType": "viewer-response",
     │      [-]     "LambdaFunctionARN": "arn:aws:lambda:us-east-1:redacted:4"
     │      [+]     "EventType": "viewer-response"
     │      [ ]   }
     │      [ ] ],
     │      [ ] "MaxTTL": 86400,
```

### Environment

  - **CDK CLI Version  :** 1.76.0 (build c207717)
  - **Framework Version:** 1.76.0
  - **Node.js Version:** v14.4.0
  - **OS               :** MacOS 10.15.6
  - **Language (Version):** Python 3.7.6

### Other

--- 

This is :bug: Bug Report

**Comment by njlynch** [comment]
Thanks for the bug report!

I am not able to immediately reproduce this behavior. Is this repeatable? In other words, can you downgrade to 1.75.0, do `cdk diff` and get no output, then upgrade to 1.76.0, and get the above diff? 

I do see something odd with your code, but it shouldn't be different between 1.75.0 and 1.76.0:
```python
        sec_func_ver = get_lambda_latest_version_num(self.sec_lambda_arn, 'us-east-1')
        sec_func = Function.from_function_arn(self, 'sec-func-redacted',
                                              f"{self.sec_lambda_arn}:{sec_func_ver}")
        sec_fassoc = LambdaFunctionAssociation(event_type=LambdaEdgeEventType.VIEWER_RESPONSE,
                                               lambda_function=sec_func)
```

[`from_function_arn`](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_lambda/Function.html#aws_cdk.aws_lambda.Function.from_function_arn) returns an `IFunction`, so `sec_func` is an `IFunction`. However, the type of `LambdaFunctionAssociation.lambda_function` is an `IVersion` (see the docs [here](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_cloudfront/LambdaFunctionAssociation.html#lambdafunctionassociation)).

What's likely happening here is that the `CloudFrontWebDistribution` is calling `sec_func.edge_arn` as it tries to build the CloudFormation; given that's not a valid method on `IFunction`, I'm guessing it's returning `None` and you're ending up with the result you get.

Try swapping out `Function.from_function_arn` with `Version.from_version_arn`. That should solve your issue.

**Comment by jwoytek** [comment]
Ah, this was a distinction that I missed in the docs when I was trying to figure out what was going on. This code had been working under 1.36, which was the last time it was touched in a significant way. I knew we had some changes to make, so I decided to update CDK to latest (1.76) and fix all of the breaking changes/deprecated things in preparation. I didn't write the original code here, but was surprised when it stopped working and could not find a "breaking change" release note that seemed to explain it. 

I'll fix this up to get the IVersion reference and I'm going to be that it works. I'll respond and will close if so.

**Comment by jwoytek** [comment]
That was it! Thanks for the clue-stick.
