### ISSUE TITLE
 CDK pipeline for multiple branches at the same time

### ISSUE THREAD

**Issue by s1mrankaur** [aws/aws-cdk#11883]
I would like to have the CI-CD pipeline deployed for the develop and master branch at all times. Pipeline for feature branches to be created manually developers as and when needed. 

I am using the pipeline from https://github.com/awslabs/aws-simple-cicd

In project-config.json , we have :
```

    "Backend": [
      {
        "pipelineName": "backend",
        "ccRepoName": "backend",
        "branch": "master",
        "type": "BitBucket",
        "cron": ""
      }
    ],
```

Step 1. Pipeline deployed for branch `master`
Step 2. Edit project-config.json and change branch name:

```
 "Backend": [
      {
        "pipelineName": "backend",
        "ccRepoName": "backend",
        "branch": "develop",
        "type": "BitBucket",
        "cron": ""
      }
    ],
```

Step 3. Pipeline deployed for `develop` branch

At this stage, it deletes the pipeline for the `master` branch and deploys it for the `develop` branch. How can we keep the pipeline for multiple branches at the same time?

**Comment by skinny85** [comment]
Hey @s1mrankaur ,

I think you might be better off opening an issue in the https://github.com/awslabs/aws-simple-cicd repository - it seems like you're using a bunch of things (like the `project-config.json` file) that is not really CDK-specific.

I will say that if you want to have 2 Pipelines, then you probably need to deploy them in separate Stacks (change the name of the Stack on one of the branches).

Thanks,
Adam
