### ISSUE TITLE
(core): Wrong methods names in Expiration docs

### ISSUE THREAD

**Issue by mrpackethead** [aws/aws-cdk#11886]
https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.core/Expiration.html

The methods is_after() and  and is_before() do not exisit,  they are after() and before()

---

This is a 📕 documentation issue

**Comment by NetaNir** [comment]
Looks like they do:
https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.core/Expiration.html#aws_cdk.core.Expiration.is_after
https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.core/Expiration.html#aws_cdk.core.Expiration.is_before

**Comment by mrpackethead** [comment]
@NetaNir , its in the docs as  is_after and is_before()  but the actual methods are not named that, they are named after() and before().    The docs need editing to reflect the actual names of the method.

**Comment by NGL321** [comment]
I am closing this as the question has been answered!

😸 😷
