### ISSUE TITLE
(aws-lambda): exclude tags from custom log-retention service provider function

### ISSUE THREAD

**Issue by matthias-pichler-warrify** [aws/aws-cdk#11897]
I am looking for a way to stop tags from applying to the service provider function of the log retention custom resource that is created when setting the `logRetention` prop on a lambda function. 

### Use Case

We have a third party monitoring solution that allows filtering functions on a tag level, so we added a special `monitored` tag that marks lambda functions that are of interest for monitoring. Unfortunately this tag propages down to the custom resource that create the log group and sets the log retention.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by nija-at** [comment]
Moving this to core, since tags are a core feature.

**Comment by rix0rrr** [comment]
You should be able to apply a `Tags.of(xxx).remove(...)` to the Log Group.
