### ISSUE TITLE
cdk.Include : Not updating the external template changes.

### ISSUE THREAD

**Issue by Black742** [aws/aws-cdk#1189]
cdk.Include constructor doesn't incorporating the changes in the external template to the CDK app.

Steps to replicate:
1. Create a test.yaml file with some sample resource.
    ``` 
     const SPEC_FILE_LOCATION = "test.yaml";
    let template: any =yaml.safeLoad(fs.readFileSync(path.join(__dirname, SPEC_FILE_LOCATION), 'utf8'));
    
    new cdk.Include(this, 'IncludeConfigTemplate', { template });

2. Deploy the app.
3. Update the text.yaml file with the below output code.
```
Outputs:
  TestOutput:
    Description: 'test'
    Value: 'test'
    Export:
      Name: 'testcdkupdate'
```
4. Build and run the deploy command. The stacks not getting updated and outputs the below msg.
Stack was already up-to-date, it has ARN arn:aws:cloudformation:ap-southeast-2:***********:stack/HelloCdkStack/3ff234e0-e930-11e8-b0c7-027753bcaabc 

Note: While running cdk diff, the changes are showing the as difference.
```
$ cdk diff
[+] Added TestOutput: {"Description":"test","Value":"test","Export":{"Name":"testcdkupdate"}}
```

Version used is 0.14.0

**Comment by Black742** [comment]
Additional to the description, have tried to use the cdk.output constructor to update the template. However, the template is not getting updated.

new cdk.Output(this, "test", {
      description: 'test',
      value: "test"
  });

**Comment by rix0rrr** [comment]
It's a known issue that just adding a `cdk.Output` will not cause a deployment to execute. This is CloudFormation behavior that we haven't adapted for yet. There should be a couple of open issues on this already, for example https://github.com/awslabs/aws-cdk/issues/778

**Comment by Black742** [comment]
Thanks for the response. Have added additional resource and the stack getting updated.

**Comment by NGL321** [comment]
_Is stale and resolved. Closing now_

😸
