### ISSUE TITLE
(init-templates/typescript): exclude node_modules

### ISSUE THREAD

**Issue by bmacher** [aws/aws-cdk#11902]
### The Question

I don't know whether it is intentional or not, however when initializing a Typescript app the `node_modules` are included into the project and will therefore be type checked and so on. This is because you override the default settings of exclude to `"exclude": ["cdk.out"]`.

> Note: without an exclude list, node_modules is excluded by default; as soon as one is added, it's important to explicitly add node_modules to the list. (Source: [Specifying Files](https://github.com/microsoft/TypeScript/wiki/Performance#specifying-files))

Regarding the [Performance recommendation](https://github.com/microsoft/TypeScript/wiki/Performance) by the official Typescript team, it is considered a best practice to exclude `node_modules`.  This could easily be achieved by adding it to `exclude`:

https://github.com/aws/aws-cdk/blob/60875a5d6cd93b7d6f0f9b1b94153f6d1f4766b1/packages/aws-cdk/lib/init-templates/v2/app/typescript/tsconfig.json#L22

```jsonc
{
  // ...
  "exclude": [
    "node_modules",
    "cdk.out"
  ]
}
```

If you don't mind I would create a PR myself. :-)

### Environment

  - **CDK CLI Version:** 1.76.0
  - **Node.js Version:** v12.16.2
  - **OS:** macOS Catalina
  - **Language (Version):** ^4.0.2

**Comment by SomayaB** [comment]
Hi @bmacher yes, that seems like a reasonable feature. Go ahead and create that PR and someone from the team will review it. Thanks!

**Comment by bmacher** [comment]
Thanks @SomayaB, I will work on that.

**Comment by bmacher** [comment]
@SomayaB it took a while but now I am working on the feature. I already changed the the `tsconfig`s ([see](https://github.com/bmacher/aws-cdk/tree/feature/exclude-node-modules-in-tsconfig-templates)). However, regarding the Contribution Guide I have to coordinate the update of the integration tests with the team. So shall I open a PR and let the discussion be there or is this issue the right place?

**Comment by peterwoodworth** [comment]
Hey @bmacher, thank you for working on this! Whenever you are ready feel free to go ahead and create the PR. Integration tests won't be necessary in this case, as you aren't changing any actual functionality that should affect any cloudformation output
