### ISSUE TITLE
(general-issues): rename OSX to macOS

### ISSUE THREAD

**Issue by bmacher** [aws/aws-cdk#11903]
Since version 10.12 (Sierra) the mac operation system is called **macOS** and not **OSX** anymore. This should therefore be corrected in the guiding lines in the [general-issues template](https://github.com/aws/aws-cdk/edit/master/.github/ISSUE_TEMPLATE/general-issues.md#L30).

See https://de.wikipedia.org/wiki/MacOS and 

> "[Sierra] was the first version of the operating system issued under the June 2016 rebranding as macOS." (Source: [macOS Sierra](https://en.wikipedia.org/wiki/MacOS_Sierra))

---

This is a 📕 documentation issue

**Comment by Jerry-AWS** [comment]
Will update this in the Dev Guide as well.

https://github.com/awsdocs/aws-cdk-guide/issues/300
