### ISSUE TITLE
(codebuild): Build image from ECR error

### ISSUE THREAD

**Issue by mydarpa** [aws/aws-cdk#11912]
I have an ECR repository "**my-ecr-repo**" with a docker image that I want to use in a code-build project:

```python
code_build.Project(
            self, "MyProject",
            description="Deployment",
            source=code_build.Source.code_commit(
                repository=my_repository),
            environment=code_build.BuildEnvironment(
                build_image=code_build.LinuxBuildImage.from_ecr_repository("my-ecr-repo")
            ),
            role=myl_role.role_arn,
            build_spec=code_build.BuildSpec.from_source_filename(
                filename="buildspec.yml"
            ),
            vpc=vpc,
            subnet_selection=subnet,
            security_groups=[my_sg]
        )
```
when I synth my code, I get this error:

`jsii.errors.JSIIError: Expected object reference, got "my-ecr-repo"`

I tried to get the ECR repository using:

```python
ecr_repo = ecr.Repository.from_repository_name(self, "EcrRepo", repository_name="my-ecr-repo")

code_build.Project(
            self, "MyProject",
            ...
            environment=code_build.BuildEnvironment(
                build_image=code_build.LinuxBuildImage.from_ecr_repository(ecr_repo)
            ),
            ...
        )
```
but now the error is:

`jsii.errors.JSIIError: Expected object reference, got "${Token[TOKEN.105]}"`

How should I reference an existing ECR repository?

### Environment

  - **CDK CLI Version  :**  1.72.0
  - **Node.js Version:**  v15.2.0
  - **OS               : OSX**
  - **Language (Version):** Python 3.9.0

### Other

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hey @mydarpa ,

thanks for opening the issue. I'm fairly sure your problem lies somewhere else, because I just tried this snippet, and it synthesizes without a problem:

```python
        ecr_repo = ecr.Repository.from_repository_name(self, "EcrRepo", repository_name="my-ecr-repo")
        codebuild.Project(
            self, "MyProject",
            environment=codebuild.BuildEnvironment(
                build_image=codebuild.LinuxBuildImage.from_ecr_repository(ecr_repo),
            ),
            build_spec=codebuild.BuildSpec.from_object({
                'version': '0.2',
                'phases': {
                    'build': {
                        'commands': ['ls -al /'],
                    },
                },
            }),
        )
```

Can you try the above, and let me know if it works for you?

Thanks,
Adam

**Comment by mydarpa** [comment]
Hi @skinny85, I found that the error `jsii.errors.JSIIError: Expected object reference, got "${Token[TOKEN.105]}"` was actually coming from `role=myl_role.role_arn`. I shouldn't pass the arn.

Thank you for your help
