### ISSUE TITLE
(core): Long CDK runtimes when using an expired AWS credential

### ISSUE THREAD

**Issue by pwrmiller** [aws/aws-cdk#11920]
### The Question

When attempting to run CDK, if your AWS credentials are expired, CDK commands succeed, but take up to 161% more time to run. This happens for all `cdk` commands. Should CDK notify users if their credentials are expired? Should CDK run more quickly despite the expired credentials? 

### Environment

  - **CDK CLI Version:**   1.70.0 (build c145314) (also tried 1.75.0) 
  - **Module Version:**  (does not matter - create an empty TypeScript CDK app and run `cdk synth` on it with an expired or not present credential)
  - **Node.js Version:**  v15.3.0 (also tried LTS) 
  - **OS:**  macOS Catalina 10.15.7
  - **Language (Version):**  typescript 3.9.7, Python 3.8.6

### Other information

```
# with profile set:
> time cdk synth
cdk synth  2.59s user 0.42s system 152% cpu 1.966 total
> time cdk synth
cdk synth  2.67s user 0.41s system 154% cpu 1.996 total

# without profile set: 
> time cdk synth
cdk synth  2.77s user 0.44s system 16% cpu 18.896 total
> time cdk synth
cdk synth  2.81s user 0.44s system 25% cpu 12.685 total
```

**Comment by rix0rrr** [comment]
`-vvvv` might tell you where the time is going. I would guess in retries :/

**Comment by pwrmiller** [comment]
It's the STS getCallerIdentity call - see below it taking 12.894 seconds, 6 retries. 

**Questions:**

1. Should CDK retry failed STS getCallerIdentity calls raising ExpiredToken? Presumably this is only truly retryable if we have an agent of some sort refreshing our credentials (otherwise, we can expect it to fail repeatably, since an expired credential is never going to unexpire by itself).
1. I see in some test code that STS is passed a config with `maxRetries: 1`. Would it not be appropriate to do with this STS call as well? 

**Suggested Fix:** 
[The currentAccount code](https://github.com/aws/aws-cdk/blob/0153028e6438eb13b07b8f2043745e5bc3faa6b7/packages/aws-cdk/lib/api/aws-auth/sdk.ts#L100) should be updated to specify maxRetries, or have a graceful failure mode for expired tokens, since this really should only be called once at the start of running CDK (unless I'm mistaken or deployments across accounts in the same CDK run is encouraged or part of your desired feature set)

*Failure details:* 

```
Toolkit stack: CDKToolkit
Setting "CDK_DEFAULT_REGION" environment variable to us-east-1
Resolving default credentials
Looking up default account ID from STS
[AWS sts 403 12.894s 6 retries] getCallerIdentity({})
Unable to determine the default AWS account: ExpiredToken: The security token included in the request is expired
    at Request.extractError (/Users/pwmiller/.local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/Users/pwmiller/.local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/pwmiller/.local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/pwmiller/.local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/Users/pwmiller/.local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/pwmiller/.local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/pwmiller/.local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/pwmiller/.local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/pwmiller/.local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/Users/pwmiller/.local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'ExpiredToken',
  time: 2020-12-09T13:13:31.525Z,
  requestId: '53301e3d-0bd0-4d14-8802-1fdc4901bdb4',
  statusCode: 403,
  retryable: true
}
```

**Comment by rix0rrr** [comment]
The root cause seems to be classifying `ExpiredToken` as `retryable: true`. This is not correct; it *might* have been done to hope to account for clock skew, but it might equally well be an oversight.

Since classification and retry happen purely in the [aws-sdk-js](https://github.com/aws/aws-sdk-js) library, nothing to be done for CDK to alleviate this. 

I suggest you report this issue as a bug report over there.
