### ISSUE TITLE
(pipelines): x-acct permissions broken after recreating bootstrap stack

### ISSUE THREAD

**Issue by rix0rrr** [aws/aws-cdk#11934]
The policies of the artifact (and replication) buckets in CDK Pipelines refer to cross-account roles that can read from the bucket (for x-acct deployments).

Without you being able to tell from the outside, those role ARNs are resolved to canonical role IDs, and if the roles get recreated (such as by destroying and recreating the bootstrap stack) the policies will look fine but contain the wrong canonical IDs and the permissions won't apply.

Deployments will fail for inexplicable reasons with "Access Denied" and CloudFormation drift detection will not pick up on this.

We need to encode those permissions differently.

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
This could also be solved by documentation.

In that some doc topic could be mentioned that changing the qualifier of something that already has things deployed to it will break.

**Comment by njlynch** [comment]
We have documented a set of work-arounds for users that get into this position. See #15405 and the package README for more details.

The actual solution (`We need to encode those permissions differently.`) is a larger task and not in scope for the GA milestone. Adjusting the effort label and removing the milestone from the issue.

**Comment by rix0rrr** [comment]
Documented how to work around this.
