### ISSUE TITLE
(aws-eks): cluster.getServiceLoadBalancerAddress supports ingress resource

### ISSUE THREAD

**Issue by zxkane** [aws/aws-cdk#11933]
Currently EKS cluster can retrieve the load balancer address from service with type `LoadBalancer`. Also the `ingress` type still can create load balancer. It’s ideally also adding retrieving load balancer address from ingress resource.

### Use Case

retrieving load balancer address from ingress resource

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by iliapolo** [comment]
@zxkane until this is implemented, you can directly use the [`KuberneteObjectValue`](https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-eks/lib/k8s-object-value.ts#L58) construct to retrieve any value you need.
