### ISSUE TITLE
(aws-apigatewayv2-integrations): integration sub type - step functions

### ISSUE THREAD

**Issue by davingreen** [aws/aws-cdk#11947]
### The Question
I don't see a way of adding Step Functions as an integration on a route. Is this not available yet? Is there a workaround?

Thanks!

### Environment

  - **CDK CLI Version:** <1.77.0
  - **Node.js Version:** v12.18.3

**Comment by drobtravels** [comment]
There does not appear to be support for any of the [HTTP API service integrations](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-aws-services-reference.html) at this time.  I don't see it noted on the roadmap either.

Would be a great addition.

**Comment by douglasnaphas** [comment]
It looks like #1465 has workarounds using L1 Constructs.
