### ISSUE TITLE
(aws-s3): Add support for an array of objectsKeyPattern as input for granting permissions to an S3 bucket

### ISSUE THREAD

**Issue by hammad13060** [aws/aws-cdk#11940]
Proposal is to add support for an array of objectsKeyPattern for granting permissions on files/directories in an S3 bucket. At present following APIs is supported by the [aws-s3/bucket](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-s3/lib/bucket.ts) interface which accepts an objectsKeyPattern value as input

1. [grantDelete(identity, objectsKeyPattern?)](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-s3.Bucket.html#grantwbrdeleteidentity-objectskeypattern)
2. [grantRead(identity, objectsKeyPattern?)](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-s3.Bucket.html#grantwbrputidentity-objectskeypattern)
3. [rantRead(identity, objectsKeyPattern?)](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-s3.Bucket.html#grantwbrreadidentity-objectskeypattern)
4. [grantWrite(identity, objectsKeyPattern?)](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-s3.Bucket.html#grantwbrwriteidentity-objectskeypattern)

### Use Case

This is useful when permissions need to be granted for multiple object key patterns for a given S3 bucket. Recently ran into this requirement while configuring OAI ([Origin Access Identity](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-restricting-access-to-s3.html)) to have read access to specific object key patterns.

### Proposed Solution

Proposal is to enhance the existing interface definition with following new API methods.

```
  grantRead(identity: iam.IGrantable, objectsKeyPattern?: any[]): iam.Grant;


  grantWrite(identity: iam.IGrantable, objectsKeyPattern?: any[]): iam.Grant;

 
  grantPut(identity: iam.IGrantable, objectsKeyPattern?: any[]): iam.Grant;

 
  grantDelete(identity: iam.IGrantable, objectsKeyPattern?: any[]): iam.Grant;


  grantReadWrite(identity: iam.IGrantable, objectsKeyPattern?: any[]): iam.Grant;
```

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by hammad13060** [comment]
@iliapolo any updates on this? Can I give it a shot?

**Comment by iliapolo** [comment]
@hammad13060  are you suggesting just a convenience method that does:

```ts
for (const pattern of objectKeyPatterns) {
  bucket.grantRead(identity, pattern)
}
``` 

Or something more inherent?
