### ISSUE TITLE
(RDS): Scheduling modifications on RDS Instance/Cluster bug

### ISSUE THREAD

**Issue by dhruvdakoria** [aws/aws-cdk#11942]
Noticing inconsistent behavior when modifying RDS instance/cluster. Attribute like IAM Database Authentication gets applied on next scheduled maintenance window **whereas** all other changes like backup window modification, backup retention modification, instance size/settings update, maintenance window updates etc. get applied immediately. 

The console provides with an option to apply this changes either immediately or during the next maintenance window. There is no such option when doing modifications/updates with CDK. Is this something that can be implemented as a property which will decide the modification time?

![image](https://user-images.githubusercontent.com/24723459/101514972-d7c0cf80-394b-11eb-87d5-e7e597992e3d.png)

### Environment

  - **CDK CLI Version  : 1.76**
  - **Framework Version:**
  - **Node.js Version:**  v10.22
  - **OS               : Linux**
  - **Language (Version):**  TypeScript (3.8.3) 

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hey @dhruvdakoria ,

thanks for opening the issue. I wonder if that level of control that you showed in the AWS Console is even available when using CloudFormation (which is the service that CDK uses to provision and update the databases).

I've checked the properties of the [CloudFormation DBInstance resource](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html#cfn-rds-dbinstance-preferredmaintenancewindow), and I can't find anything that would allow setting those...

**Comment by dhruvdakoria** [comment]
Hi Adam, yes you’re right. CFN doesn’t support that level of control yet. I’ll open a ticket with them. Thanks!

**Comment by skinny85** [comment]
Thanks @dhruvdakoria . Feel free to link back here, and we can re-open the issue when CloudFormation support is available.

**Comment by sturdeac** [comment]
Are there any updates on this issue? I'm currently looking for a solution to make changes apply immediately with CDK.

**Comment by skinny85** [comment]
@dhruvdakoria any news?

**Comment by bates-sdx** [comment]
I wrote into AWS Support today about this and they said there is a feature request for this but no update. This seems to still be pending support from CloudFormation and nothing can be done from CDK side.
