### ISSUE TITLE
(ec2): addSignalOnExit and userDataCausesReplacement does not work together

### ISSUE THREAD

**Issue by Harper04** [aws/aws-cdk#11959]
Hi,

i am using `userDataCausesReplacement` which does add a Hash to the logical ID of the instance.
i also want to use `addSignalOnExitCommand` which uses `cfn-signal` and needs the logical ID of the instance in the cf template.

As the logical id of the instance becomes part of the user script which is part of the hash... i do smell a circle here.

However:
addSignalOnExitCommand seems to use the logical ID WITHOUT the hash suffix.
```
Dec  9 09:19:10 ip-10-0-14-7 cloud-init[1720]: ValidationError: Resource instanceB7CCE687 does not exist for stack ASPStack
``` 

The correct logical ID would be: `instanceB7CCE6875f795b6afdab820e`

### Reproduction Steps
```
    const instance = new ec2.Instance(this, 'instance', {
      ...
      userDataCausesReplacement: true,
    })
instance.userData.addSignalOnExitCommand(instance)
```

### What did you expect to happen?

cfn-signal should work

### What actually happened?

cfn-signal got the wrong logical-id which leads to the error above and no successfull deployment

### Environment

  - **CDK CLI Version  :** 1.77.0
  - **Framework Version:** 1.77.0
  - **Node.js Version:** 14.15.0
  - **OS               :** Mac OS Catalina
  - **Language (Version):** Typescript 4

### Other

Maybe to avoid the circular issue the best way could be to just read the tag `aws:cloudformation:logical-id` from `http://169.254.169.254`

--- 

This is :bug: Bug Report

**Comment by corymhall** [comment]
Closing this in favor of #12749
