### ISSUE TITLE
`TemplateURL` is not set for Nested Stack.

### ISSUE THREAD

**Issue by aman25m** [aws/aws-cdk#11950]
### **TemplateURL** is set to `<unresolved>` in parent stack.

The latest changes in my CDK application consists of a nested stack. The stack deployment failed with issue `TemplateURL must be an Amazon S3 URL.`

On noticing more, I tried to build both my service package and the pipeline package. The service package builds fine with the parent template referencing the nested stack with a S3 location.

But if I build my CDK application, it produces all the required templates and the nested stack template as well, but in the parent stack, the TemplateURL parameter of the nested stack resource is set to <unresolved>. Attached screenshots for the same.

### Reproduction Steps
Build the service package and then built the pipeline cdk package. 
`cdk synth`

Note:  NO `cdk deploy` was run as the changes got deployed through pipeline.

For local deployments to personal aws account commands used :

`bb cdk synth`
`bb deply:assets <STACKNAME>`
`bb cdk deploy <STACKNAME>`

Note: This change went through the pipeline and broke at the time of stack deployment with error `TemplateURL must be an Amazon S3 URL.`

### What did you expect to happen?

It is expected that once the `cdk synth` is run, the nested stack is referenced in parent stack with the correct S3 location.
 
### What actually happened?

`TemplateURL is set to <unresolved> in parent stack.`

### Environment

  - **CDK CLI Version:** 1.32.2
  - **Node.js Version:** 12.x
  - **OS:** macOS Catalina
  - **Language (Version):** TypeScript 3.6.2
<img width="776" alt="templates_generated" src="https://user-images.githubusercontent.com/26578603/101553871-5fb5d200-396a-11eb-8a79-f3275dfa4daf.png">
<img width="1374" alt="AlarmNestedStack_Details" src="https://user-images.githubusercontent.com/26578603/101553888-693f3a00-396a-11eb-9474-a61c5666c8ee.png">

**Comment by aman25m** [comment]
@rix0rrr any updates?

**Comment by NetaNir** [comment]
`bb deploy:assets` is not a CDK command.

**Comment by aman25m** [comment]
@NetaNir @rix0rrr I am not sure why this ticket is closed. `bb deploy:assets` is ONLY used for local deployments and nothing else. We are talking here about the stacks which are generated in CDK pipelines.
