### ISSUE TITLE
(aws-ec2): addS3DownloadCommand does not work in China, opt-in regions

### ISSUE THREAD

**Issue by wchaws** [aws/aws-cdk#11958]
### Use Case

Currently, AWS China region need `aws s3 cp --region cn-north-1` to be able to download file from s3

https://github.com/aws/aws-cdk/blob/3530e8c758df3ea2fb26d654109e17a75f157b37/packages/%40aws-cdk/aws-ec2/lib/user-data.ts#L159

### Proposed Solution

```ts
export interface S3DownloadOptions {

  /**
   * Name of the S3 bucket to download from
   */
  readonly bucket: IBucket;

  /**
   * The key of the file to download
   */
  readonly bucketKey: string;

  /**
   * The name of the local file.
   *
   * @default Linux   - /tmp/bucketKey
   *          Windows - %TEMP%/bucketKey
   */
  readonly localFile?: string;

  /**
   * The region to use
   */
  readonly region?: string;
}
```

```ts
  public addS3DownloadCommand(params: S3DownloadOptions): string {
    const s3Path = `s3://${params.bucket.bucketName}/${params.bucketKey}`;
    const localPath = ( params.localFile && params.localFile.length !== 0 ) ? params.localFile : `/tmp/${ params.bucketKey }`;
    this.addCommands(
      `mkdir -p $(dirname '${localPath}')`,
      `aws s3 cp --region '${params.region ?? stack.region}' '${s3Path}' '${localPath}'`,
    );

    return localPath;
  }
```

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by owenCCY** [comment]
Way to reproduce this bug: 
When you store sth in s3 bucket in CN regions like: cn-northwest-1, calling addS3DownloadCommand will result in checking s3 buckets in global region, instead of the right region we want. So as a result, actions like "aws s3 cp" will fail.
Please kindly help, thanks!

**Comment by rix0rrr** [comment]
I guess it's only accidental that the other commands even work :( .

A better fix would have been to set `AWS_REGION` at the start of UserData, but that's probably a change we can't make anymore. Adding in the `--region` parameter seems like the best solution.

**Comment by maclema** [comment]
Also of note, in addition to adding in region. The addS3DownloadCommand will need to add --endpoint-url to the resulting command to ensure when using opt-in regions that a IllegalLocationConstraintException isn't thrown.

**Comment by gadams999** [comment]
This also affects all opt-in regions in the same manner as the GRC (and possibly GovCloud?) regions.

**Comment by rix0rrr** [comment]
Feels like it shouldn't be a user parameter though, but be automatically derived from the location of the bucket.

We can use `bucket.resourceEnv.region` to get it.

**Comment by rix0rrr** [comment]
> Also of note, in addition to adding in region. The addS3DownloadCommand will need to add --endpoint-url to the resulting command to ensure when using opt-in regions that a IllegalLocationConstraintException isn't thrown.

Do you have a link that explains the need?

**Comment by LukvonStrom** [comment]
This issue is in parts related to the issue raised in #8287 and my PR for that issue in #16667
