### ISSUE TITLE
(ecs-patterns): pass in target group for NLB Service patterns

### ISSUE THREAD

**Issue by SoManyHs** [aws/aws-cdk#11969]
Currently, the NetworkLoadBalanced*Services create the listener and default target group for you, with the ECS service as a target. However, this limits you to having only one service behind the NLB. Since NLB listeners have only one default rule that routes traffic to a single target group, being able to pass in a target group or add other services to the target group would enable putting multiple services behind the same NLB.

Passing in a target group would allow for finer-grained control for configuring ingress/ports as well.

Related: 
- https://github.com/aws/aws-cdk/issues/8040
- https://github.com/aws/aws-cdk/issues/10196

Simliar (for ALB patterns):
- https://github.com/aws/aws-cdk/issues/12003
- https://github.com/aws/aws-cdk/issues/7989

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by brifordwylie** [comment]
So I have this issue (2024-09-14). Perhaps I'm not understanding something but when I used this code it's not using my security group (only allowing whitelist ip) and make a default that is WIDE open. I'll be happy if someone just says 'do this' instead :)

```
        # Create security group for the load balancer
        lb_security_group = ec2.SecurityGroup(self, "LoadBalancerSecurityGroup", vpc=cluster.vpc)

        # Add rules for the whitelist IPs
        if props.whitelist_ips:
            for ip in props.whitelist_ips:
                lb_security_group.add_ingress_rule(
                    ec2.Peer.ipv4(ip),
                    ec2.Port.tcp(80)
                )

        # Adding LoadBalancer with Fargate Service
        fargate_service = ApplicationLoadBalancedFargateService(
            self,
            "SageworksService",
            cluster=cluster,
            cpu=2048,
            desired_count=1,
            task_definition=task_definition,
            memory_limit_mib=4096,
            public_load_balancer=True,
            security_groups=[lb_security_group],
        )
  ```
  The result of this is a creation of a default security group with incoming 0.0.0.0/0	Allow from anyone on port 80, so hoping someone can point me in the right direction... my chatbot is failing me :)

**Comment by jotadepicas** [comment]
@brifordwylie hi there? Did you ever resolved the security group issue? I'm facing it too, the default is creating a totally open security group (allows port 443 from 0.0.0.0), but I'd need to only whitelist specific IPs. Do you know of any workarounds? Thanks!
