### ISSUE TITLE
(pipelines): Parameters / Secrets Gathering Before Pipeline Definition

### ISSUE THREAD

**Issue by stlserverless** [aws/aws-cdk#11972]
I'm working with a security-conscious client that absolutely doesn't want AWS account numbers or ARNs, etc. in the source code.

CDK supports the idea of reading Secrets or Parameters in application stacks. When these calls are defined, they are inserted as TOKENs in the code to be resolved at deploy time. However, the pipeline itself cannot be defined using tokens.  If you try to do that, errors are thrown indicating the values must be known and can't be tokens.

### Use Case

For instance, when instantiating a stage, you cannot do something like this because the account and region values will be tokens:

```
new DeploymentStage(this, 'prodStage'. {
     env: {
        account: ssm.StringParameter.valueForStringParameter(this, '/project1/app1/prod/ACCOUNT'),
        region: ssm.StringParameter.valueForStringParameter(this, '/project1/app1/prod/REGION')
     },
     ...
}
```

### Proposed Solution

A direct solution would be if the aws-ssm module supported some kind of actual value method to enable a real (not TOKEN) value to be resolved. For example:

```
new DeploymentStage(this, 'prodStage'. {
     env: {
        account: ssm.StringParameter.actualValueForStringParameter(this, '/project1/app1/prod/ACCOUNT'),
        region: ssm.StringParameter.actualValueForStringParameter(this, '/project1/app1/prod/REGION')
     },
     ...
}
```

Alternatively, a pre-pipeline definition step that would allow any external values to be gathered from Parameter Store, Secrets Manager, environment variables, externalized config files from S3, whatever. Importantly, these values would be fully realized, not tokens. I've experimented with adding the **aws-sdk** into the deployment and making SDK calls out to Parameter Store, but ran into permissions issues. This still may be a promising approach as the pipeline can be prepared with any data available via sdk calls.

### Other

Here's a gist of an example CDK Pipeline definition that today won't work because the account and region passed into the **env** is a Parameter Store lookup: https://gist.github.com/stlserverless/2dfd9390ef252d8b79f445485587b054

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
I would suggest you write a custom script that will retrieve those SSM values and inject them into your CDK app using environment variables or a structured file.
