### ISSUE TITLE
(cli): cdk synth need to disable printing the Cloudformation Template to console

### ISSUE THREAD

**Issue by caruso-billfire** [aws/aws-cdk#11970]
### The Question
There should be a way to run cdk synth and disable printing the Cloudformation Template to stdout. 
It would make sense for this to work when use --output or for it to be its own flag. 

The reason: In our Codebuild logs it is very annoying to have a giant template printed line by line when we are only running the synth to use the --output flag to analyse the Cloudformation Template. 

### Environment

  - **CDK CLI Version:** all
  - **Module Version:** all
  - **Node.js Version:** n/a
  - **OS:** all
  - **Language (Version):** TypeScript / possibly all

**Comment by briete** [comment]
Are you sure you want to work on this issue?
