### ISSUE TITLE
(@aws-cdk/aws-apigateway): RestApi.urlForPath(...) fails with separate Stage and Deployment

### ISSUE THREAD

**Issue by michaelfecher** [aws/aws-cdk#11986]
I followed the guide here:
https://docs.aws.amazon.com/cdk/api/latest/docs/aws-apigateway-readme.html#breaking-up-methods-and-resources-across-stacks

When trying to access the RestApi.urlForPath AFTER the Deployment stack, I am getting the error:
`Cannot determine deployment stage for API from "deploymentStage". Use "deploy" or explicitly set "deploymentStage"`

When the RestApi is instantiated, I added the same argument `deployment: false` to it.

Differences to the example:
- I am not using NestedStacks
- Use proxied Lambda instead of Mock integration 
- calling `urlForPath` on the original RestApi instead of a templated string after the DeploymentStack

### What did you expect to happen?

Pass the token (of the deployable prod-staged URL) to the next stack, in the same manner as in the mentioned example from above.

### What actually happened?

Cannot determine deployment stage for API from "deploymentStage". Use "deploy" or explicitly set "deploymentStage"

### Environment

  - **CDK CLI Version  : 1.74.0**
  - **Framework Version: 1.63.0 (can't migrate right now)**
  - **Node.js Version: 14.15** 
  - **OS               : Ubuntu**
  - **Language (Version): TypeScript** 

### Other

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
From what I can tell, this is as expected. You cannot ask for a URL without a deployment stage configured. 
The `RestApi`, by default, creates a Deployment and Stage for you. The setting `deploy: false` explicitly disables this.

You will have to use `urlForPath()` from the `Stage` construct defined in `DeployStack`.
