### ISSUE TITLE
(s3): tagging buckets

### ISSUE THREAD

**Issue by rsmogura** [aws/aws-cdk#11985]
Enable tagging of S3 buckets & tags propagation from 'global' tags.

### Use Case

Right now we have specified stack tags we want to be propagated to every construct. For S3 tags are not getting propagated and I can't find tags options when constructing buckets.

Tagging S3 can be useful for various management purposes.

### Proposed Solution

There's tag manager in CDK and some small support for tagging for CF constructs. This should be changed to allow specifying tags as the options and propagating tags from (global) stack tags.

### Other

* [x] :wave: I may be able to implement this feature request
* [x] :warning: This feature might incur a breaking change ( this change should not be breaking in context of API, however it can introduce number of stacks updates)

---

This is a :rocket: Feature Request

**Comment by iliapolo** [comment]
@rsmogura How exactly are you trying to configure the tags?

I am able to successfully assign tags to the bucket using the both the standard `Tags` aspect and by applying stack tags:

```ts
export class Issue11985 extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props: cdk.StackProps) {
    super(scope, id, props);

    new s3.Bucket(this, 'Bucket');

    cdk.Tags.of(this).add('foo', 'bar');
  }
}
```

```ts
export class Issue11985 extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props: cdk.StackProps) {
    super(scope, id, {
      ...props,
      tags: {
        foo: 'bar'
      }
    });

    new s3.Bucket(this, 'Bucket');
  }
}
```

Can you share your code?
