### ISSUE TITLE
(aws-appmesh): Client Policies object should not be part of the Virtual Service

### ISSUE THREAD

**Issue by sshver** [aws/aws-cdk#11996]
Client Policies are inherently not related to the Virtual Service. It should be thought of as the client (the VN) telling envoy what connections they want to allow to the server (the Virtual Service). The server `shouldn't` be the one to define what policies are used to enforce connections with itself.

### Reproduction Steps
None

### What did you expect to happen?
Client policy object should be a part of Virtual Node, not Virtual Service. A VirtualNode can have a VirtualService as a backend and an associated client policy and a different VirtualNode should have the same VirtualService backend without associated client policy. 

### What actually happened?
Client Policy is a part of Virtual Service. We cannot use same VirtualService with different client policies as the client policy is now attached to a Virtual Service itself. 

### Environment

  - **CDK CLI Version  :**
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):** 

### Other

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
@sshver I thought you _could_ use multiple policies for the same `VirtualService` if you used different `backendsDefaultClientPolicy`ies for two different `VirtualNode`s? (assuming the `VirtualService` `clientPolicy` has not been provided, of course)

**Comment by dfezzie** [comment]
A `VirtualService` should not be enforcing the `ClientPolicy` a `VirtualNode` uses to communicate.

You can think of a `VirtualService` as a _smart pointer_ that acts as the entry point to a service in the mesh. When one of your `VirtualNode`s attempts to make a connection to service in the mesh, that service is abstracted by the `VirtualService` (which can be backed by a virtual router or virtual node directly). The intent of a client policy is to define policies to enforce on a connection being made from that specific virtual node to the specified VirtualService (specified in the backend field). The policy is specific to the virtual node, and should not be affected by the policies made by other virtual nodes in the mesh. You may have a VirtualNode which requires strict TLS enforcement on any backends it connects to, and in that case it would reject connections to a virtual service that is backed by a non TLS VN. A different VN may not have that requirement and should be able to connect to the same VN with no issues.

**Comment by skinny85** [comment]
Thanks for the great explanation @dfezzie 🙂.
