### ISSUE TITLE
(cloudfront): Specify the minimum origin SSL protocol version in the new Distribution construct

### ISSUE THREAD

**Issue by robertd** [aws/aws-cdk#11994]
## :question: General Issue

Is it possible to specify the minimum origin SSL protocol version in the new Distribution construct natively? (without using the escape hatches 😄 )Currently it defaults to SSLv3.

![image](https://user-images.githubusercontent.com/31543/101809682-1209a880-3ad5-11eb-8888-88d2ae6aadd5.png)

cc @njlynch 

### Environment

  - **CDK CLI Version:** 1.77.0 (build a941c53)
  - **Node.js Version:** v15.3.0
  - **OS:** macOS Mojave
  - **Language (Version):** TypeScript (4.0.3)

**Comment by njlynch** [comment]
Nope, there's not a way to do this without escape hatches at the moment.

Re-tagging this as a feature request. Should be a relatively minor feature to add a prop for the SSL protocol version.
