### ISSUE TITLE
(aws-elasticloadbalancingv2-targets): Type 'IpTarget' is not assignable to type 'INetworkLoadBalancerTarget'.

### ISSUE THREAD

**Issue by Cloudrage** [aws/aws-cdk#11991]
### Reproduction Steps
When trying to use the new experimental Class from **aws-elasticloadbalancingv2-targets** with an NLB :
`targets: [new elbv2Targets.IpTarget(PrdIp, PrdPort)],`

We can't go further :
```
Type 'IpTarget' is not assignable to type 'INetworkLoadBalancerTarget'.
  Types of property 'attachToNetworkTargetGroup' are incompatible.
```
 

### What did you expect to happen?

The deprecated Class is working : 

`targets: [new elbv2.IpTarget(PrdIp, PrdPort)],`

Can you fix it or maybe I'm doing something wrong ?

### Environment

 **CDK CLI Version  : 1.76.0**

--- 

This is :bug: Bug Report

**Comment by njlynch** [comment]
It sounds like you have different versions of `aws-elasticloadbalancingv2` and `aws-elasticloadbalancingv2-targets` installed. Can you double-check your package versions and see if that fixes it?

**Comment by Cloudrage** [comment]
Thanks @njlynch , I've sync everything on version : 1.77.0 and it's ok now
