### ISSUE TITLE
CLI - Deploy Pre-Synthed Cloudformation

### ISSUE THREAD

**Issue by jcamilli** [aws/aws-cdk#11998]
With AWS SAM we can package/build the cloudformation and push all dependencies to a repo somewhere. For example, Docker images to ECR or lambda jars to S3. Once these compile and package phases are complete, we have an artifact that can be deployed to any AWS account. There is no reason to regenerate the cloudformation or the lambda jars do not need to be redeployed to s3. For example, when deploying a lambda, the cloudformation will have a pointer to the s3 bucket where the jar resides. Same for something like ECS which uses an ECR docker image which can be pulled from a centralized location. 

With sam the build and package phase needs to only occur one time and from that, a cloudformation can be deployed to any account and the dependencies (jars, images) can be pulled from a single source. No reason to recompile or regenerage the cloudformation for every account that it is pushed into.

Can the above be accomplished with the CDK command line tool? I would like the CDK tool to be able to simply generate a cloudformation (synth) and then use the CDK to deploy this synthed cloudformation. 

### Use Case

Our build system has many environments where we can deploy a single commit from code repo. A Lambda can move from DEV to QA to PROD and in our CICD pipeline, the lambda and cloudformation is built only one time. I don't want to run CDK over again to build the cloudformation for each environment (separate AWS account). That is a waste since it was already built for the commit. We can take the generated cloudformation and deploy it into a given account and use parameters to change specific information that differs between environments.

### Proposed Solution

Perhaps this feature already exists? I was not able to see it in the documentation here:
https://docs.aws.amazon.com/cdk/latest/guide/home.html

The CDK team could add a command to 'cdk deploy' command so that it takes a pre-built cloudformation as input and deploys it given a stack name, and parameters and other arguments required to deploy a stack.

As a work around, perhaps one way to accomplish this is to generate the cloudformation with CDK synth, and then use AWS SAM to deploy the cloudformation.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by skinny85** [comment]
Hello @jcamilli ,

yes, this feature already exists. You can use the `-a` switch and point it to the path with the files for the Cloud Assembly (the contents of the `cdk.out` directory locally).

If you want to have CI/CD pipelines in your CDK code, take a look at the [CDK Pipelines module](https://docs.aws.amazon.com/cdk/api/latest/docs/pipelines-readme.html).

Thanks,
Adam

**Comment by jcamilli** [comment]
Thank you @skinny85
