### ISSUE TITLE
(lambda): Cannot increase timeout duration

### ISSUE THREAD

**Issue by alu-men** [aws/aws-cdk#12000]
Unable to increase timeout duration on Lambda functions using Typescript language for CDK, 

### Reproduction Steps

const lambdafn = new lambda.Function(this, 'MyLambda', {
  runtime: lambda.Runtime.NODEJS_12_X,
  handler: 'app.handler',
  code: lambda.Code.fromAsset(path.join(__dirname, './importFunction')),
  memorySize: 512,
  timeout: cdk.Duration.seconds(30),
  environment: {
    DYNAMO_TABLE: DDBtable.tableName,
  }
});

### What actually happened?

Resulted in error:

Type 'import(".../@aws-cdk/core/lib/duration").Duration' is not assignable to type 'import(".../@aws-cdk/aws-events/node_modules/@aws-cdk/core/lib/duration").Duration'.
  Types have separate declarations of a private property 'amount'.

The expected type comes from property 'timeout' which is declared here on type 'FunctionProps'

### Environment

  - **CDK CLI Version  :** 1.75.0 (build 7708242)
  - **Node.js Version:** v12.18.4
  - **OS               :** MacOS
  - **Language (Version):** Version 4.0.3

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hello @alu-men ,

you have 2 separate versions of the CDK in your dependency closure:

* @aws-cdk/core/lib/duration
* @aws-cdk/aws-events/node_modules/@aws-cdk/core/lib/duration

`npm ls` should show you the problem. Make sure there's a single version of the libraries that you're using.

Thanks,
Adam

**Comment by alu-men** [comment]
You are correct! My mistake.

Thanks
