### ISSUE TITLE
(ecs-patterns): Allow to disable default security group in ApplicationLoadBalancedFargateService

### ISSUE THREAD

**Issue by selvathiruarul** [aws/aws-cdk#12003]
Setting open_listener=True in ApplicationLoadBalancedFargateService removes inbound ingress from the default sg so that sg is not really used anyway. It would be nicer if we could delete default_sg if open_listener=True or allow a method to add custom ingress rule to that sg will also be helpful. Thanks

**Comment by SoManyHs** [comment]
Note: Similar to https://github.com/aws/aws-cdk/issues/10196, which is being tracked in https://github.com/aws/aws-cdk/issues/11969
