### ISSUE TITLE
(core, maybe ec2?): More fine grained subnet selection

### ISSUE THREAD

**Issue by markus7811** [aws/aws-cdk#12019]
We need some more fine-grained way of subnet selection. 

Right now, I'm struggling with the subnet selection cdk offers to me. In all of my use cases, I have no chance to create a vpc or subnets. I have to reuse those that are already created in my aws account. 
All of them are private subnets, but not all are equal. 

When starting with a fresh account there are only 3 subnets - one per az. When I'm running out of IP addresses, I get 3 more subnets. But not all resources like it, if I offer them 3 more subnets (eks cluster will be recreated if you change the subnet configuration).

Apart from that I have 3 more subnets, with non-routed IP addresses - so they are private, but not usable for all use cases.

At the moment, I using the subnet from attributes method, to "select" my subnets - but therefore i have to copy-paste all values from my account config to to my app (subnet cidr range, route-tableid, availability zone, ...). 

### Use Case

I want to be able to select subnets by it's name, or by it's tags so that I don't have to define all attributes, but can rely on the lookups.

### Proposed Solution

No concrete idea at the moment, but I think there would be more to change than ec2.vpc or ec2.subnet...

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by NetaNir** [comment]
We are tracking this in https://github.com/aws/aws-cdk/issues/5927
