### ISSUE TITLE
(elasticsearch): Two ES Domains with logging cannot be created in the same stack

### ISSUE THREAD

**Issue by peterb154** [aws/aws-cdk#12017]
When 2 ES Domains, both with logging enabled, are created in the same stack, a Construct naming conflict occurs

Error:
> There is already a Construct with name 'AppLogs' in Stack [es-bug-stack]

### Reproduction Steps

```
#!/usr/bin/env node
import { App, Stack } from '@aws-cdk/core';
import { Domain, ElasticsearchVersion } from '@aws-cdk/aws-elasticsearch';

const app = new App();
const stack = new Stack(app, 'es-bug-stack');
new Domain(stack, 'domain1', {
    version: ElasticsearchVersion.V7_7,
    logging: { appLogEnabled: true }
})
new Domain(stack, 'domain2', {
    version: ElasticsearchVersion.V7_7,
    logging: { appLogEnabled: true }
})
app.synth()
```

```
$ cdk synth
There is already a Construct with name 'AppLogs' in Stack [es-bug-stack]
Subprocess exited with error 1
```

### What did you expect to happen?

That 2 ES Domains can co-exist in the same stack

### What actually happened?

`cdk synth` throws the error:
> There is already a Construct with name 'AppLogs' in Stack [es-bug-stack]

### Environment

  - **CDK CLI Version  : 1.70.0
  - **Framework Version: 1.70.0
  - **Node.js Version:** v12.18.4
  - **OS               : macos
  - **Language (Version):** all

### Other

https://github.com/aws/aws-cdk/blob/ae2e9c1a40070509e2fb5a95de8881906b500546/packages/%40aws-cdk/aws-elasticsearch/lib/domain.ts#L1399

The following constructs have statically named construct LogicalIds: `SlowSearchLogs`, `SlowIndexLogs` & `AppLogs` which creates a conflict when 2 Domains exist in the same stack

```
    // Setup logging
    const logGroups: logs.ILogGroup[] = [];

    if (props.logging?.slowSearchLogEnabled) {
      this.slowSearchLogGroup = props.logging.slowSearchLogGroup ??
        new logs.LogGroup(scope, 'SlowSearchLogs', {
          retention: logs.RetentionDays.ONE_MONTH,
        });

      logGroups.push(this.slowSearchLogGroup);
    };

    if (props.logging?.slowIndexLogEnabled) {
      this.slowIndexLogGroup = props.logging.slowIndexLogGroup ??
        new logs.LogGroup(scope, 'SlowIndexLogs', {
          retention: logs.RetentionDays.ONE_MONTH,
        });

      logGroups.push(this.slowIndexLogGroup);
    };

    if (props.logging?.appLogEnabled) {
      this.appLogGroup = props.logging.appLogGroup ??
        new logs.LogGroup(scope, 'AppLogs', {
          retention: logs.RetentionDays.ONE_MONTH,
        });

      logGroups.push(this.appLogGroup);
    };
```

--- 

This is :bug: Bug Report

**Comment by peterb154** [comment]
@iliapolo , I can also do a PR for this bug if you like. Let me know.

**Comment by iliapolo** [comment]
@peterb154 Nice catch. 

>  I can also do a PR for this bug if you like. Let me know.

That would be great. Basically we need to use `this` as the scope of the log groups, instead of `scope`.

**Comment by peterb154** [comment]
@iliapolo  - here  is the PR  https://github.com/aws/aws-cdk/pull/12055
Its my first contribution to aws-cdk so let me know if I missed anything.
