### ISSUE TITLE
(elbv2): IApplicationLoadBalancer had no add security group method but ApplicationLoadBalancer does

### ISSUE THREAD

**Issue by dxunix** [aws/aws-cdk#12037]
### The Question

IApplicationLoadBalancer had no add security group method but ApplicationLoadBalancer does. Will it be implemented?

### Environment

  - **CDK CLI Version:** 
  - **Module Version:** 
  - **Node.js Version:** 
  - **OS:** 
  - **Language:**

**Comment by d-baps** [comment]
I could really use this as it's blocking me at the moment. Any news?

**Comment by david-r-emcins** [comment]
Any progress on this?  Or a workaround in Python?
