### ISSUE TITLE
(eks): Helm Chart Fails to Deploy On First Try

### ISSUE THREAD

**Issue by pauljrob** [aws/aws-cdk#12030]
When trying to deploy a Helm chart I get the following error:

2:44:03 PM | CREATE_FAILED        | Custom::AWSCDK-EKS-HelmChart | JenkinsHelm/Resource/Default
Failed to create resource. Error: b'Release "cicd" does not exist. Installing it now.\n'

If I repeat the deploy again (sometimes 2x) it will then work.

### Reproduction Steps

new eks.HelmChart(this, 'JenkinsHelm', {
            cluster,
            repository: "https://charts.helm.sh/stable", 
            chart: "jenkins", 
            release: "cicd", 
            namespace: "jenkins", 
});
### What did you expect to happen?

I expected the chart to launch successfully.

### What actually happened?

It threw an error stating the release was not available and it had to be installed:

2:44:03 PM | CREATE_FAILED        | Custom::AWSCDK-EKS-HelmChart | JenkinsHelm/Resource/Default
Failed to create resource. Error: b'Release "cicd" does not exist. Installing it now.\n'

### Environment

  - **CDK CLI Version  :** 1.75.0
  - **Framework Version:** 1.75.0
  - **Node.js Version:** v10.15.3
  - **OS               :** MacOS Catalina
  - **Language (Version):** Typescript

### Other

--- 

This is :bug: Bug Report

**Comment by yjw113080** [comment]
I get similar error too. I used to have no issue when deploying the following code, but I can't from the most recent version of CDK.

1. Code
```
    const stable = 'https://kubernetes-charts.storage.googleapis.com/';

    cluster.addHelmChart(`metrics-server`, {
      repository: stable,
      chart: 'metrics-server'
    });
```

2. Environment
- CDK CLI Version : 1.78.0
- Framework Version: 1.78.0
- Node.js Version: v10.15.3
- OS : cloud 9
```
NAME="Amazon Linux AMI"
VERSION="2018.03"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2018.03"
PRETTY_NAME="Amazon Linux AMI 2018.03"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2018.03:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"
```
- Language (Version): Typescript

**Comment by iliapolo** [comment]
@pauljrob @yjw113080 Can you please share the entire lambda execution log from CloudWatch? I believe you are either hitting a memory limit, or perhaps some helm deprecation issues.

We've had a similar [discussion](https://github.com/aws/aws-cdk/issues/11477) a while back that didn't result in a problem with CDK. Worth taking a look.

Thanks

**Comment by yjw113080** [comment]
It turns out to be the chart issue in my case. 
Uploading the log just in case it helps anyone. Thanks @iliapolo 
[log-events-viewer-result.csv.zip](https://github.com/aws/aws-cdk/files/5704689/log-events-viewer-result.csv.zip)
