### ISSUE TITLE
(ec2): make it easy to set vpc name via a property (instead of tags)

### ISSUE THREAD

**Issue by aakrem** [aws/aws-cdk#12043]
it's mentioned in the documentation below that we can specify a physical name by using the property <resourceType>Name, 
however, it doesn't work for creating a vpc.

https://docs.aws.amazon.com/cdk/latest/guide/resources.html#resources_physical_names

So this will throw an error:
```
new EC2.Vpc(this, 'VPC', {
      vpcName: 'myVPC',
}
```

**Comment by NetaNir** [comment]
According to CloudFormation docs, it is not possible to set a name to a VPC: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpc.html
Physical names are not supported in all CloudFormation resources.

**Comment by rix0rrr** [comment]
Unlikely we will do this. Tags are the way to go.
