### ISSUE TITLE
(autoscaling): I couldn't find how to encrypt an EBS volume used by an ASG through CDK

### ISSUE THREAD

**Issue by andybirenzi** [aws/aws-cdk#12049]
Hi I would like to encrypt EBS created through an ASG. Any guide on how to  do this? I couldn't find a good guide on how to

---

This is a 📕 documentation issue

**Comment by leandrodamascena** [comment]
Well, you can define the volume using "EbsDeviceOptions" Interface.

Check here the documentation https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-autoscaling.EbsDeviceOptions.html#properties.
