### ISSUE TITLE
(aws-lambda-nodejs): Expose optional settings of logging and preserve name of function and  classes while bundling

### ISSUE THREAD

**Issue by hassanazharkhan** [aws/aws-cdk#12046]
This feature request is to add bundling props while bundling from local or docker build from esbuild, there are lots of features that needs to be exposed from aws-lambda-nodejs

### Use Case

There are cases where bundler prints warnings and errors in the terminal but most of the time these warnings are just warning and ignorable, so with the current implementation of bundler props we don't have any exposed settings to change the log level of the bundler.

Along with the above, there are no options to preserve the name of function and classes while bundling this is really useful where the name function or class used somewhere in the code dynamically.

I am also thinking to add a property that will be used to identify `tsconfig` if one doesn't want to use default `tsconfig` that property will tell the `esbuild` to use a particular config, i.e `bundler.tsconfig.json`. there are valid use cases of this.  

### Proposed Solution

```ts
const props: NodejsFunctionProps = {
             entry: `index.ts`,
             bundling: {
                 minify: false,
                 sourceMap: true,
                 logLevel: LogLevel.ERROR,
                 keepNames: true
             },
         }
```
### Other

* [ ] :wave: I can implement this feature request, it won't be difficult

---

This is a :rocket: Feature Request

**Comment by hassanazharkhan** [comment]
@jogold When this will be available?

**Comment by jogold** [comment]
> @jogold When this will be available?

In the next release
