### ISSUE TITLE
(cloudformation): cfnCustomResource Class [No way to specify properties other than serviceToken]

### ISSUE THREAD

**Issue by catalyst0** [aws/aws-cdk#12057]
I am trying to use the Java CDK with the cfn* constructs for declaring a cfnCustomResource object. 

From what I found, I can prepare a cfnCustomResource like so:

```java
CfnCustomResource cResource = new CfnCustomResource(this, "cResource", 
CfnCustomResourceProps.builder().serviceToken("REDACTED").build()
);
```
- but I cannot specify any other properties I want to pass onto the Custom Resource provider; for example, I want to pass another ARN String to a Lambda backed Custom Resource - there is no way I can do that because the CfnCustomResourceProps builder only allows me to specify the serviceToken.

Can someone please suggest if this is a recognized issue somewhere else, or what the workaround maybe? 

Thanks, C

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by aughban** [comment]
+1 - finding the same thing

**Comment by peterwoodworth** [comment]
Sorry for the long response time.

This library is deprecated, you'll want to use [core's custom resource](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.CustomResource.html) which allows you to pass properties in.
