### ISSUE TITLE
(ec2): io2 support - Cfn Supports natively but CDK does not

### ISSUE THREAD

**Issue by miztiik** [aws/aws-cdk#12052]
The newly released `io2` volumes are supported by Cloudformation. But `aws_cdk.aws_ec2.EbsDeviceVolumeType` does not seem support it yet. Similar to https://github.com/aws/aws-cdk/issues/12020
Ref: https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_ec2/EbsDeviceVolumeType.html#aws_cdk.aws_ec2.EbsDeviceVolumeType

**Comment by kirintwn** [comment]
This should be close as #12074 was merged.
