### ISSUE TITLE
(cloudwatch): Single Value Widget graph option: Number Widget Format

### ISSUE THREAD

**Issue by cukierkowychleb** [aws/aws-cdk#12066]
AWS Console supports option: Number Widget Format (Show as many digits as can fit, before rounding) however it is not possible to set **singleValueFullPrecision** property via cdk.
### Use Case
CDK provides less configuration option than AWS Console so it not fully supports dashboard/graph creation programatically.

### Proposed Solution
Add to https://github.com/aws/aws-cdk/blob/09e994a204697930987ee9fa420ccbe1b20fb97b/packages/%40aws-cdk/aws-cloudwatch/lib/graph.ts#L237

property singleValueFullPrecision as boolean.

---

This is a :rocket: Feature Request

**Comment by evmin** [comment]
+1
