### ISSUE TITLE
(codepipeline_actions): cloudformation.CloudFormationCapabilities is deprecated

### ISSUE THREAD

**Issue by matwerber1** [aws/aws-cdk#12079]
The CloudFormation deploy type expects the `capabilities` parameter to be of type `cloudformation.CloudFormationCapabilities`. However, Typescript is giving a warning that this type is deprecated and that `core.CfnCapabilities` should be used instead. 

### Reproduction Steps

Create a codepipeline action for CloudFormation, like below:

```js
new codepipeline_actions.CloudFormationCreateUpdateStackAction({
              actionName: 'Deploy_to_Prod',
              ...
              ...
              capabilities: [
                cloudformation.CloudFormationCapabilities.NAMED_IAM
             ],
              ...
}
```

While deployment works, I receive the following warning in my IDE: 

![image](https://user-images.githubusercontent.com/28939541/102158631-b32a9300-3e36-11eb-9b0a-40e008cb7f66.png)

### What did you expect to happen?

Shouldn't receive an error. 

### What actually happened?

See above.

### Environment

  - **CDK CLI Version  :** 1.77.0 (build a941c53)
  - **Framework Version:** (not sure what this means?)
  - **Node.js Version:**  v12.19.0
  - **OS               :** MacOs
  - **Language (Version):**  TypeScript

### Other

As shown below, `cloudformation. CloudFormationCapabilities` is deprecated and `core.CfnCapabilities` should be used instead. 

https://github.com/aws/aws-cdk/blob/f2ecaf2d879be3a904296dafc3e04b4cf4505ed0/packages/%40aws-cdk/aws-cloudformation/lib/cloud-formation-capabilities.ts#L3

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hello @matwerber1 ,

thanks for opening the issue. Unfortunately, other than deprecating the current `capabilities` property and creating a new one, this is not a change we can do, as it would be backwards-incompatible.

We can change it when we release CDK v2.

Thanks,
Adam
