### ISSUE TITLE
(rds): Cannot create DB with secrets from other region

### ISSUE THREAD

**Issue by felipepulpo** [aws/aws-cdk#12086]
Cannot create DB with secrets from other region even when I reference them by ARN

### Reproduction Steps
Stack is created in eu-central-1

```ts
    const dbCredentials = config.isProduction ?
         secretsmanager.Secret.fromSecretCompleteArn(
             stack, 'DBSecret',
             'arn:aws:secretsmanager:us-east-2:123:secret:database-credentials-prod') :
         secretsmanager.Secret.fromSecretCompleteArn(
             stack, 'DBSecret',
             'arn:aws:secretsmanager:us-east-2:123:secret:database-credentials-test');
 
 
     // left out restore from snapshot as it was never used
     const database = new rds.DatabaseInstance(stack, 'Database', {
        engine: rds.DatabaseInstanceEngine.postgres({ version: rds.PostgresEngineVersion.VER_12_3 }),
         instanceType: new ec2.InstanceType(instanceType.valueAsString),
         vpc,
         instanceIdentifier: `${config.stackName}-database`,
         allocatedStorage: config.isProduction ? 20 : 5,
         allowMajorVersionUpgrade: true,
         databaseName: config.databases.backend.name,
         parameterGroup: parameterGroup,
         removalPolicy: config.isProduction ? cdk.RemovalPolicy.SNAPSHOT : cdk.RemovalPolicy.DESTROY,
         backupRetention: config.isProduction ? cdk.Duration.days(7) : cdk.Duration.days(2),
        securityGroups: [dbSecurityGroup],
         vpcSubnets: {
             subnetType: ec2.SubnetType.PUBLIC
         },
         credentials: rds.Credentials.fromSecret(dbCredentials)
     });
```
### What did you expect to happen?
The secrets are referenced and the datbase is created

### What actually happened?
The cdk deploy failed saying that it cannot find the linked secrets

### Environment

  - **CDK CLI Version  : 1.76**
  - **Framework Version:  1.76**
  - **Node.js Version:** 10.18.1
  - **OS               : MAC**
  - **Language (Version):**TypeScript (3.8.3)

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hey @felipepulpo,

can you please show:

a) what account and region is the `stack` in.
b) the full error message that you get, and whether it happens during `synth`, or `deploy`.

Thanks,
Adam

**Comment by felipepulpo** [comment]
Hi,

a) eu-central-1 and the secrets were in us-east-2. My account number is better not to post it here right?
b) on deployment time. At that time I was getting "secret not found in this region" or something similar. I dont have it anymore

Thanks,
Felipe

**Comment by skinny85** [comment]
> a) eu-central-1 and the secrets were in us-east-2. My account number is better not to post it here right?

I'm not asking about the specific account number, feel free to edit it out. I'm asking whether `stack` is in the same account as the Secret you're importing.

> b) on deployment time. At that time I was getting "secret not found in this region" or something similar. I dont have it anymore

Can you reproduce the error? It's going to be pretty hard for us to diagnose this issue without the actual error that you received.

Thanks,
Adam

**Comment by felipepulpo** [comment]
Oh. Yes they are in the same account but in different regions. 
Yes you can reproduce the error with the code I pasted in the bug.
At the end I recreated the secrets in the other region which is not very nice because of the data duplication.
I don't have time to reproduce it again

**Comment by peterwoodworth** [comment]
Pretty sure that this is a requirement from cloudformation. The strings [seen on this page](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/dynamic-references.html) are what the CDK generates, so it's not actually getting the values before deployment time.

[This response](https://stackoverflow.com/a/59774628) explains how to get around this with CDK custom resources, and without having to duplicate your data 😄
