### ISSUE TITLE
(aws-stepfunctions-tasks): Fargate task definition contains version which causes step function failure when new task definition is pushed. 

### ISSUE THREAD

**Issue by gupta-n** [aws/aws-cdk#12080]
Hi Team,
Currently task definition created by step function CDK appends task version which cause step function failure.

**Scenario:** Step function failed to launch fargate task because of some transient issue, before retry kicks in there was another deployment went which modified task definition and caused version bump. In this scenario running step function execution will failed as existing task is inactive now.

### Reproduction Steps

**Scenario:** Step function failed to launch fargate task because of some transient issue, before retry kicks in there was another deployment went which modified task definition and caused version bump. In this scenario running step function execution will failed as existing task is inactive now.

```
const workerTask = new sfn.Task(this, 'Worker', {
            task: new tasks.RunEcsFargateTask({
                cluster: props.ecsCluster,
                taskDefinition: taskDefn,
                integrationPattern: sfn.ServiceIntegrationPattern.SYNC,
                containerOverrides: [
                    {
                        containerName: "TestContainer",
                        environment: []
                    }]
            }),
            outputPath: "$"
        }
```
Actual Task definition in step function
```
"parameters": {
    "Cluster": "arn:aws:ecs:us-east-1:XXXXXXXXXXX:cluster/EcsCluster-Cluster2e",
    "TaskDefinition": "arn:aws:ecs:us-east-1:XXXXXXXXXXX:task-definition/TaskDefinition75BC8FE8:16",
    "NetworkConfiguration": {
      "AwsvpcConfiguration": {
        "Subnets": [
          "subnet-XXXXXXXXXXX"
        ],
        "SecurityGroups": [
          "sg-XXXXXXXXXXX"
        ]
      }
    },
```
Expected output

```
"parameters": {
    "Cluster": "arn:aws:ecs:us-east-1:XXXXXXXXXXX:cluster/EcsCluster-Cluster2e",
    "TaskDefinition": "arn:aws:ecs:us-east-1:XXXXXXXXXXX:task-definition/TaskDefinition75BC8FE8",
    "NetworkConfiguration": {
      "AwsvpcConfiguration": {
        "Subnets": [
          "subnet-XXXXXXXXXXX"
        ],
        "SecurityGroups": [
          "sg-XXXXXXXXXXX"
        ]
      }
    },
```
### What did you expect to happen?
When creating fargate task definition step function can attach definition to task family which will ensure to always pickup latest version and will make step function not to fail when new deployment is pushed.

https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_RunTask.html#ECS-RunTask-request-taskDefinition

Expected output

```
"parameters": {
    "Cluster": "arn:aws:ecs:us-east-1:XXXXXXXXXXX:cluster/EcsCluster-Cluster2e",
    "TaskDefinition": "arn:aws:ecs:us-east-1:XXXXXXXXXXX:task-definition/TaskDefinition75BC8FE8",
    "NetworkConfiguration": {
      "AwsvpcConfiguration": {
        "Subnets": [
          "subnet-XXXXXXXXXXX"
        ],
        "SecurityGroups": [
          "sg-XXXXXXXXXXX"
        ]
      }
    },
```

### What actually happened?
Step function failed when new changes to task definition were pushed. 

### Environment

  - **CDK CLI Version  :** 1.32.2
  - **Framework Version:** 1.32.2
  - **Node.js Version:** NodeJS = 12.x
  - **OS               : Mac
  - **Language (Version):** Type script ^3.6.4

--- 

This is :bug: Bug Report

**Comment by shivlaks** [comment]
@gupta-n thanks for reporting the issue.

I think we'll need some more information before this can be actioned:

> Currently task definition created by step function CDK appends task version which cause step function failure.

what's the code required to produce it? what's the expectation? 
how do i reproduce this error

> Step function failed to launch fargate task because of some transient issue,
what's the point of failure? when executing the state machine? when deploying the CloudFormation template?

>  before retry kicks in there was another deployment went which modified task definition and caused version bump.
I'm a little lost, are multiple deployments needed to produce this issue? how/where is the task definition defined? 
when you say version bump, what are you referring to? how is that version bump observed?

> please provide a minimal set of reproduction steps to define a state machine with a problematic task definition.

Step function failed when new changes to task definition were pushed.
> what kind of changes? are they prerequisites to producing the error?

Environment
> can you fill in all of the requisite version information (NA is not possible for Node.js version and OS). Please mention the specific version that you are using as it's not asking for which versions the bug might be present in.

As i see it, a first step would be to reproduce this error. A minimal code sample and the steps required to produce the failure scenario would be a starting point.

**Comment by gupta-n** [comment]
> before retry kicks in there was another deployment went which modified task definition and caused version bump.

I'm a little lost, are multiple deployments needed to produce this issue? 
> Yes

how/where is the task definition defined?
> using step function ``new tasks.RunEcsFargateTask`` added code snippet. 
when you say version bump, what are you referring to? how is that version bump observed?
> Version bump happens when ever you modified task definition one way could be to change fargate memory size.

please provide a minimal set of reproduction steps to define a state machine with a problematic task definition.
> Added, Let me know if something else is needed.
