### ISSUE TITLE
(s3): BucketKeyEnabled in L2 construct for S3 Bucket resource.

### ISSUE THREAD

**Issue by shantgup** [aws/aws-cdk#12089]
`ServerSideEncryptionRule` now supports the property `BucketKeyEnabled` as seen in the documentation [here](https://docs.aws.amazon.com/AmazonS3/latest/dev/configuring-bucket-key.html#enable-bucket-key-cloudformation).

However, it is not supported yet by CDK as it is not available in the CDK docs [here](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-s3.BucketEncryption.html).

An enterprise customer reached out to me about this and we have this submitted as an internal Feature Request, creating one here as well so customers can track it.

---

This is a :rocket: Feature Request

**Comment by matthewdaniel** [comment]
it appeared to me that the places that need updating are generated from https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html
I'd be happy to work on a PR if there is a way of doing this without the resource specification not being updated. I'd just need a push in the right direction.

**Comment by NGL321** [comment]
Hey @shantgup,

This this functionality has already been added to Cloudformation, __however__, it has not been added to their resource specification and therefore we cannot add it to the CDK (all our base-level/L1 constructs are generated from the Cloudformation resource specification).

The current source spec looks like:
``` json
    "AWS::S3::Bucket.BucketEncryption": {
      "Documentation": "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-bucketencryption.html",
      "Properties": {
        "ServerSideEncryptionConfiguration": {
          "Documentation": "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-bucketencryption.html#cfn-s3-bucket-bucketencryption-serversideencryptionconfiguration",
          "DuplicatesAllowed": false,
          "ItemType": "ServerSideEncryptionRule",
          "Required": true,
          "Type": "List",
          "UpdateType": "Mutable"
        }
      }
    },
    "AWS::S3::Bucket.ServerSideEncryptionByDefault": {
      "Documentation": "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-serversideencryptionbydefault.html",
      "Properties": {
        "KMSMasterKeyID": {
          "Documentation": "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-serversideencryptionbydefault.html#cfn-s3-bucket-serversideencryptionbydefault-kmsmasterkeyid",
          "PrimitiveType": "String",
          "Required": false,
          "UpdateType": "Mutable"
        },
        "SSEAlgorithm": {
          "Documentation": "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-serversideencryptionbydefault.html#cfn-s3-bucket-serversideencryptionbydefault-ssealgorithm",
          "PrimitiveType": "String",
          "Required": true,
          "UpdateType": "Mutable"
        }
      }
    },
    "AWS::S3::Bucket.ServerSideEncryptionRule": {
      "Documentation": "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-serversideencryptionrule.html",
      "Properties": {
        "ServerSideEncryptionByDefault": {
          "Documentation": "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-serversideencryptionrule.html#cfn-s3-bucket-serversideencryptionrule-serversideencryptionbydefault",
          "Required": false,
          "Type": "ServerSideEncryptionByDefault",
          "UpdateType": "Mutable"
        }
      }
    },
```

We are currently tracking the fix to the cfn resource spec via internal ticket (I believe yours), and will update there and here when it is added to the resource spec. It will be available in the CDK L1 construct in the following CDK release.

To have it added to the L2 I will keep this ticket open for tracking and pass it back to the relevant dev when that time comes.

😸 😷

**Comment by NGL321** [comment]
@matthewdaniel once the resource spec is updated and this feature exists in the L1 construct, your addition to the L2 would be __very__ much appreciated!! 🎉 🚀 

😸 😷

**Comment by peterwoodworth** [comment]
Cfn supports this now. L2 support should be pretty simple from here

**Comment by watany-dev** [comment]
I want this feature and will work on it as soon as possible.

**Comment by comcalvi** [comment]
:+1: thanks for the investigation @watany-dev. You're right this can be closed
