### ISSUE TITLE
(rds): copy_tags_to_snapshot option missing from DatabaseCluster class

### ISSUE THREAD

**Issue by aktungmak** [aws/aws-cdk#12085]
### The Question
The class `aws_cdk.aws_rds.DatabaseInstance` provides the keyword argument `copy_tags_to_snapshot` in its constructor, to ensure that snapshots are created with the same tags as the database.

However, the class `aws_cdk.aws_rds.DatabaseCluster` does not offer this option and this means that snapshots are created without tags.

To verify this was the problem, I deployed the following stack and then checked the "Backup" section of the AWS console 
and I could see that the option "Copy tags to snapshots" was set to "Disabled".

```
from aws_cdk import (
    aws_ec2 as ec2,
    aws_rds as rds,
    core,
)

class TestStack(core.Stack):
    def __init__(self, scope: core.Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        self.cluster()

    def cluster(self):
        return rds.DatabaseCluster(
            self,
            "cluster",
            engine=rds.DatabaseClusterEngine.aurora_postgres(
                version=rds.AuroraPostgresEngineVersion.VER_11_8
            ),
            instance_props=rds.InstanceProps(
                vpc=ec2.Vpc.from_lookup(
                    self, "vpc", vpc_name="vpc-1"
                ),
                instance_type=ec2.InstanceType.of(
                    ec2.InstanceClass.BURSTABLE3, ec2.InstanceSize.MEDIUM
                ),
            ),
        )
```

### Expectation
The keyword argument `copy_tags_to_snapshot` is available in the constructor of `aws_cdk.aws_rds.DatabaseCluster` and it has the same behaviour as in`aws_cdk.aws_rds.DatabaseInstance`.

### Environment

  - **CDK CLI Version:** 1.78.0 (build 2c74f4c)
  - **Module Version:** 1.78.0
  - **Node.js Version:** v14.11.0
  - **OS:** macos Catalina 10.15.7 (19H15)
  - **Language:** Python

**Comment by skinny85** [comment]
Thanks for opening the issue @aktungmak . Any chance of creating a PR adding this property to the [`InstanceProps` interface](https://github.com/aws/aws-cdk/blob/2cd233a94fc2f3cb06211157738e59e8c7ee85e5/packages/%40aws-cdk/aws-rds/lib/props.ts#L10-L87)? Here's our "Contributing" guide: https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md#gitpod

Thanks,
Adam

**Comment by aktungmak** [comment]
Hi Adam! While doing some further searching on this subject, I discovered that this is actually not supported in CloudFormation (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbcluster.html) and indeed someone has already created a feature request (https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/238).

If I understand correctly, CDK can only use features that exist in CloudFormation so this cannot be resolved until the feature is added to CloudFormation. Or is there another way around this?

**Comment by skinny85** [comment]
Hey @aktungmak ,

in theory, the could provide that functionality with a [CloudFormation Custom Resource](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-custom-resources.html). However, we usually reserve that for bigger features, as it requires deploying a Lambda function along with your Stack, which is a pretty large and expensive abstraction 🙂. Usually we don't do that for single properties like these.

I'll add the `needs-cfn` label to indicate this is waiting for CloudFormation support.

**Comment by Bryconc** [comment]
Hi all,

Looks like the property `CopyTagsToSnapshot` has recently been added to the CloudFormation resource (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbcluster.html#cfn-rds-dbcluster-copytagstosnapshot).

(https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/238#issuecomment-875806934)

Does this mean this is ready for implementation?

**Comment by skinny85** [comment]
Yep @Bryconc. PRs are very much welcome, as always! https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md

**Comment by blimmer** [comment]
It looks like this property is available on Cluster now, so I think this issue can be closed: https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_rds.DatabaseClusterProps.html#copytagstosnapshot

**Comment by skinny85** [comment]
Yep, thanks @blimmer!
