### ISSUE TITLE
(cloudfront): cross region EdgeFunction does not work within a Stage

### ISSUE THREAD

**Issue by corymhall** [aws/aws-cdk#12092]
If I create an `EdgeFunction` in a region other than `us-east-1`, it throws an error if it is being created in a `Stage`

```bash
You cannot add a dependency from 'Blog-Frontend/TestStack' (in Stage 'Blog-Frontend') to 'edge-lambda-stack-us-east-2' (in the App): dependency cannot cross stage boundaries
```

### Reproduction Steps

```typescript
export class Frontend extends cdk.Stage {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StageProps) {
    super(scope, id, props);
    const testStack = new cdk.Stack(this, 'TestStack', { env: region: 'us-east-2' });
    new cloudfront.experimental.EdgeFunction(testStack, 'EdgeFunction', {
      code: lambda.Code.fromAsset(path.join(__dirname, '../code')),
      runtime: lambda.Runtime.NODEJS_12_X,
      handler: 'index.handler',
    });
  }
}
```

### What did you expect to happen?

I expect the `edge-lambda-stack-us-east-2` support stack to be created within the parent stage.

### What actually happened?

It looks like instead of creating the `edge-lambda-stack-us-east-2` support stack within the parent `Stage`, it is creating it within the root `App`. 

It looks like it may be caused by this line:
https://github.com/aws/aws-cdk/blob/3b301231a2d28c3f46d22d44010eb75adc77bc6b/packages/%40aws-cdk/aws-cloudfront/lib/experimental/edge-function.ts#L197

### Environment

  - **CDK CLI Version  :** 1.78.0
  - **Framework Version:** 1.78.0
  - **Node.js Version:** v12.16.1 
  - **OS               :** Ubuntu 18.04
  - **Language (Version):** TypeScript 

### Other

--- 

This is :bug: Bug Report

**Comment by njlynch** [comment]
Thanks for the bug report (and being an early adopter of `EdgeFunction`)! Fix is #12103.
