### ISSUE TITLE
(lambda-event-sources): Support MSK and self hosted Kafka

### ISSUE THREAD

**Issue by bracki** [aws/aws-cdk#12099]
Add a `KafkaEventSource` that implements `StreamEventSource` and allows configuring either MSK or a self hosted Kafka cluster as described [here](https://docs.aws.amazon.com/lambda/latest/dg/with-msk.html) and [here](https://docs.aws.amazon.com/lambda/latest/dg/kafka-smaa.html).

### Use Case

I want to setup MSK/Kafka as event source for Lambda without doing it with the lower level `CfnEventSourceMapping`.

### Proposed Solution

Add a class `KafkaEventSource` that implements `StreamEventSource`.

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by bracki** [comment]
It could look like this:

```typescript
export type KafkaEventSourceProps = StreamEventSourceProps

class KafkaEventSource extends StreamEventSource {
    constructor(readonly clusterArn: string, readonly kafkaTopic: string, readonly secretArn: string, props: KafkaEventSourceProps) {
        super(props);
    }

    public bind(target: lambda.IFunction) {
        const eventSourceMapping = target.addEventSourceMapping(
            `KafkaEventSource:${this.kafkaTopic}`,
            this.enrichMappingOptions({
                eventSourceArn: this.clusterArn,
                kafkaTopic: this.kafkaTopic,
                startingPosition: this.props.startingPosition
            })
        );
        target.role?.addManagedPolicy(iam.ManagedPolicy.fromAwsManagedPolicyName('AWSLambdaMSKExecutionRole'));
        target.addToRolePolicy(new iam.PolicyStatement(
            {
                actions: ['secretsmanager:GetSecretValue'],
                resources: [this.secretArn],
            })
        );
        const cfnEventSourceMapping = eventSourceMapping.node.defaultChild as lambda.CfnEventSourceMapping;
        cfnEventSourceMapping.sourceAccessConfigurations = [{type: 'SASL_SCRAM_512_AUTH', uri: this.secretArn}];
    }
}
```

**Comment by bracki** [comment]
For a self hosted Kafka cluster this is needed as well: https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/723 Or it could be retrofitted with `AwsCustomResource`.

Maybe we have a quick chat @nija-at?

**Comment by nija-at** [comment]
If it's supported by the AWS SDK for Javascript, you could absolutely use a custom resource until support for it is available via CloudFormation.

@bracki - I'm out on vacation for the next 2 weeks but feel free to take a stab at a PR here. You can DM me (once I'm back) on the public CDK Slack channel (details at https://cdk.dev/)
