### ISSUE TITLE
(lambda): Provide a way to provision secrets in lambdas similar to ECS

### ISSUE THREAD

**Issue by ltamrazov** [aws/aws-cdk#12095]
### The Question
Hi, what is the recommended way to provision secrets in lambda functions?

I was looking at the definition of the [DockerImageFunction](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-lambda.DockerImageFunction.html) and was hoping to find a `secrets` property similar to [ContainerDefinition](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs.ContainerDefinition.html) in ECS module but did not see anything like that, only `environment`. 

[AWS docs](https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html) seem to indicate that this is possible through Cloudformation, though I might be missunderstanding?
```
Another option is to store passwords in AWS Secrets Manager secrets. You can reference the secret in your AWS CloudFormation templates to set passwords on databases. You can also set the value of an environment variable on the Lambda function. For an example, see the next section. 
```

### Environment

  - **CDK CLI Version:** 1.77.0 (build a941c53)
  - **Module Version:** 1.77
  - **Node.js Version:** v14.14.0
  - **OS:** Docker Alpine on MacOS Big Sur
  - **Language (Version):** Typescript

Thank you!

**Comment by ltamrazov** [comment]
Hi @nija-at , any updates on this by chance?

**Comment by nija-at** [comment]
We're able to provide this feature in ECS by leveraging a feature ECS provides natively - https://docs.aws.amazon.com/AmazonECS/latest/developerguide/specifying-sensitive-data.html

No such feature exists for Lambda, unfortunately. You will need to use AWS Secrets Manager to store your secrets and access them in your lambda function. 
There are quite a few articles out there that show how to achieve this. Here's one - https://aws.amazon.com/blogs/security/how-to-securely-provide-database-credentials-to-lambda-functions-by-using-aws-secrets-manager/ -  but there are also others.

**Comment by ltamrazov** [comment]
Thank you!

**Comment by schlichtanders** [comment]
@nija-at can you point to the new documentation how to provision secrets in lambda similar to ECS?
