### ISSUE TITLE
(cli): diff - detect and warn when consumed exports are modified

### ISSUE THREAD

**Issue by nija-at** [aws/aws-cdk#12104]
CloudFormation does not allow modification or deletion of stack exports that are consumed by other stacks.

While running `cdk diff`, if any stack export that consumed by other stacks are detected to be modified or removed, the diff should show a clear message that the deployment will not succeed.

---

This is a :rocket: Feature Request

**Comment by redbaron** [comment]
CDK relies on CloudFormation changsets for diff. Does CF changeset warn you if output changes?
