### ISSUE TITLE
[aws-ecs][aws-codepipeline-actions][aws-codepipeline]: ecs.FargateService.fromFargateServiceArn 

### ISSUE THREAD

**Issue by joa44741** [aws/aws-cdk#12100]
I'm trying to create a pipeline with a deploy step that should deploy from the pipeline account to another account.

Unfortunately I'm not able to get it running.

```ts
    private getEcsFargateService(stage: string): ecs.IFargateService {
        const props = this.node.tryGetContext(stage); // needed to figure out which account and region is used
        const clusterName = 'myCluster';
        const ecsServiceName = 'myService';
        const fargateServiceArn = `arn:aws:ecs:${props.region}:${props.account}:service/${clusterName}/${ecsServiceName}`;
        const fargateService = ecs.FargateService.fromFargateServiceArn(this.stack, `MLEcsFargateService-${stage}`, fargateServiceArn);
        return fargateService;
    }

    private getDeployToDevStage(): codepipeline.StageProps {
        return {
            stageName: 'Deploy-Dev',
            actions: [
                new codepipelineActions.EcsDeployAction({
                    actionName: 'Deploy-Dev',
                    input: buildDeployImageOutput,
                    service: this.getEcsFargateService('dev')
                })
            ]
        }
    }
```
In this line `service: this.getEcsFargateService('dev')` I'm getting the error:
`Property 'cluster' is missing in type 'IFargateService' but required in type 'IBaseService'`

I think the account, region and cluster name should already be defined in the arn, isn't it? 

### Reproduction Steps

just try out the code written above

### What did you expect to happen?
I would expect that the IFargateService could be used in the CodePipeline action.

### What actually happened?

Error occured: `Property 'cluster' is missing in type 'IFargateService' but required in type 'IBaseService'`

### Environment

  - **CDK CLI Version  :** 1.77.0
  - **Framework Version: ** 1.77.0
  - **Node.js Version:** I guess the one used by codebuild.LinuxBuildImage.STANDARD_4_0
  - **OS               :** codebuild.LinuxBuildImage.STANDARD_4_0
  - **Language (Version):** 

### Other

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hello @joa44741 ,

like the compiler is telling you, the types don't exactly match here. You want to use the `fromFargateServiceAttributes()` method here, which specifies the Cluster the service belongs to, which is needed for the Action.

Thanks,
Adam

**Comment by joa44741** [comment]
Hey Adam, 
thanks a lot for your fast response - as always :-) 
I really appreciate it!

I've already tried the `fromFargateServiceAttributes()` but I couldn't manage it as I'm not able to use the vpc of the target account in the `ecs.Cluster.fromClusterAttributes()` function. I received the error `Could not find any VPCs matching`

**Is there any other solution? :)**

   
    private getDeployToProdStage(): codepipeline.StageProps {
        return {
            stageName: 'Deploy-Prod',
            actions: [
                new codepipelineActions.EcsDeployAction({
                    actionName: 'Deploy-Prod',
                    input: buildDeployImageOutput,
                    service: this.getProdEcsService()
                })
            ]
        }
    }

    private getProdEcsService(): ecs.IBaseService {
        const stage = 'prod';
        const props = this.node.tryGetContext(stage);
        const clusterName = 'myCluster';
        const ecsServiceName = 'myService';
        const fargateServiceArn = `arn:aws:ecs:${props.region}:${props.account}:service/${clusterName}/${ecsServiceName}`;
        let vpc = ec2.Vpc.fromLookup(this, `ExistingVpc-${stage}`, {
            vpcId: props.vpcId, # this is the id in the target account and of course not retrievable in the pipeline account
        });

        const cluster = ecs.Cluster.fromClusterAttributes(this, `AIOps-ExistingECSCluster-${stage}`, {
            clusterName: clusterName,
            clusterArn: `arn:aws:ecs:${props.region}:${props.account}:cluster/${clusterName}`,
            vpc: vpc,
            securityGroups: []
        });

        const fargateService = ecs.FargateService.fromFargateServiceAttributes(this.stack, `MLEcsFargateService-${stage}`, {
            cluster: cluster,
            serviceArn: fargateServiceArn
        });
        return fargateService;
    }

**Comment by skinny85** [comment]
Try using `Vpc.fromVpcAttributes()` instead, and provide the ID from the other account.

Honestly, I _think_ you might get away with specifying a dummy ID there, because these particular function of the Service will not need to refer to the VPC. But a real ID will work for sure 🙂.

**Comment by joa44741** [comment]
Yes that worked! :-) 
thanks very much!
