### ISSUE TITLE
(apigateway): an example on applying a custom RestAPI role on api gateway

### ISSUE THREAD

**Issue by dariusjs** [aws/aws-cdk#12102]
https://docs.aws.amazon.com/cdk/api/latest/docs/aws-apigateway-readme.html#deployments

```
By default, an IAM role will be created and associated with API Gateway to allow it to write logs and metrics to AWS CloudWatch unless cloudWatchRole is set to false.
```

The documentation page describes that when using the apigateway.RestApi construct an IAM role is automatically created with permissions to write metrics and logs. To disable this you set the boolean cloudWatchRole to false. 

I would like to submit this example somewhere to documentation or examples where a custom IAM role is set that has a boundary policy applied. This role is then applied to the API gateway. Perhaps there is even a cleaner way to do this.

The following example shows a custom IAM role that has a boundary policy configured attached to the API gateway.
```ts
const apiLogRole = new Role(this, "CloudWatchRole", {
  assumedBy: new ServicePrincipal("apigateway.amazonaws.com"),
  managedPolicies: [ManagedPolicy.fromAwsManagedPolicyName("service-role/AmazonAPIGatewayPushToCloudWatchLogs")],
  permissionsBoundary: ManagedPolicy.fromManagedPolicyArn(
    this,
    "app-boundary",
    "arn:aws:iam::${Stack.of(this).account}:policy/app-boundary`,
  ),
  roleName: "app-role",
});

const accessLogGroup = new LogGroup(this, "app-accessLogs", {
  logGroupName: "app-api-access-logs",
  retention: 30,
});

const api = new RestApi(this, "app-rest-api", {
  cloudWatchRole: false,
  deployOptions: {
    accessLogDestination: new LogGroupLogDestination(accessLogGroup),
    accessLogFormat: AccessLogFormat.jsonWithStandardFields(),
  },
  restApiName: "app-api",
});

const resource = new CfnAccount(this, "app-account-config", {
  cloudWatchRoleArn: apiLogRole.roleArn,
});
resource.node.addDependency(api);
api.root.addMethod("ANY");
```

---

This is a 📕 documentation issue

**Comment by nija-at** [comment]
Could you describe what you're looking to achieve by adding this to the apigateway documentation? Is it to document the use of `CfnAccount` or something else?

**Comment by dariusjs** [comment]
I've closed this issue as I was mainly affected by global boundary policies required by my projects.

I ended up solving this by following examples outlined here https://github.com/aws/aws-cdk/issues/3242 which applies boundary policies to all my resources
