### ISSUE TITLE
(eks): need to override kubectl handler lambda IAM role

### ISSUE THREAD

**Issue by aka-toxa** [aws/aws-cdk#12107]
we've noticed that when we want to create the service account through cdk with IAM role attached, the cdk requires us to specify the IAM role that has access to Kubernetes API:

![image](https://user-images.githubusercontent.com/1811078/102359926-1133b380-3fba-11eb-9d8c-ef733820c3dc.png)

Also, we've noticed that the lambda that does kubectl apply tries to assume that role to make `kubectl apply` command, which is fine. 

The one thing that we noticed that when this kubectl handler lambda created it is created with the new role every time with the assume role inline policy. 

![image](https://user-images.githubusercontent.com/1811078/102361451-e9454f80-3fbb-11eb-8919-835c8b598da5.png)
![image](https://user-images.githubusercontent.com/1811078/102361462-ec404000-3fbb-11eb-8b22-59b71c964224.png)

Which is could be fine as well but we find that this is not quite secure, because in this case, we need to put "root account" to the trusted entities of kubectlRole to let all that lambdas assume this role. 

For dev/qa environments it is fine but for production account, we really don't want to have Kubernetes admin role which can be assumed by anyone who has assumeRole policy we want to tight that kubectl role by trusted entities some how.

### Use Case

we use IRSA for Imported clusters service-per-service. Each service has it's own cdk stack with Cluster.addServiceAccount() call. So each service create it's own kubectl handler lambda with it's own lambda role with random name. 

our kubectl role should be assumable by only one entity, but in the environment where we have huge amount of lambdas for each service it is not possible to list all that lambda roles in the trusted entity of kubectl role.

### Proposed Solution

I see here two possible solutions:

1. Add an optional parameter with the kubectl handler lambda. so each cdk stack can load that lambda and use the same lambda in a different stacks that creates IRSA. So we create that lambda once with the role and put that role to the trusted entity of kubectlRole.
2. Add an optional parameter to `.addServiceAccount()` function to pass the existing role arn for kubectl handler lambda. so we can create that role once, put it inside the trusted entities of kubectl role and all kubectl handlers will run under this role.

### Other

* [X] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by iliapolo** [comment]
@aka-toxa You mention:

> For dev/qa environments it is fine but for production account, we really don't want to have Kubernetes admin role which can be assumed by anyone who has assumeRole policy we want to tight that kubectl role by trusted entities some how.

I'm wondering what is the specific concern here. Is there a scenario where undesirable roles would have assume role permissions on the kubectl role you pass to the cluster?

**Comment by aka-toxa** [comment]
we just don't want to have any chances that someone accidentally or not will add assume role policy to something that shouldn't have it. and we want to use "trusted entities" field properly for our kubectl role. 

if we put just account root there that would mean that everyone who has permissions to add inline policies to some role/user would have access to k8s master role. With proper trusted entities (like we restrict that kubectl role can be assumed **only** by some special cdk role) we will ensure that no one will add assume role policy and get access to k8s even accidentally

**Comment by iliapolo** [comment]
@aka-toxa Thanks, I understand the concern now.

Could you elaborate on proposal number 2 you mentioned?

I was thinking about doing something similar to proposal 1, but instead of exposing the entire lambda handler, just exposing an optional role that would be used as the lambda execution role. You would then create that role once, and use its name as the trusted entity of the kubectl role.

So something like:

```ts
const cluster = eks.Cluster.fromClusterAttributes(this, 'Cluster', {
  ...,
  kubectlRole: <role-that-is-mapped-to-k8s-masters>,
  kubectlHandlerRole: <role-that-can-assume-kubectlRole>
});
```

Would that work for you? This is also makes me think that we might possibly just use `kubectlRole` as the lambda execution role, so the lambda won't even have to assume another role to operate the cluster.

**Comment by aka-toxa** [comment]
yeah I think that also that we can just put `kubectlRole` and don't spam account with many roles. 
sure I will proceed with that bit later 
also I think that this change might depends on this PR https://github.com/aws/aws-cdk/pull/12131

**Comment by iliapolo** [comment]
@aka-toxa Let me know when you start working on this to finalize the approach because i'm still not sure about it.

**Comment by aka-toxa** [comment]
hi @iliapolo are you still happy with the second approach? 
I'm going to open PR in a couple of days

**Comment by iliapolo** [comment]
@aka-toxa Just to make sure we are aligned. The plan is basically to use `kubectlRole` as the execution role of the `KubectlProvider` handler, which effectively means getting rid of the `--role-arn` argument:

https://github.com/aws/aws-cdk/blob/9e6dc6b00d4de6e892be3356ea6d24dd0d45bb2a/packages/%40aws-cdk/aws-eks/lib/kubectl-handler/apply/__init__.py#L30-L33

And making sure everything works the same - right?

My only concern is with regards to breaking changes, would this change require any changes to the trusted entities of the `kubectlRole`? Now that is has to be assumable by Lambda?

**Comment by aka-toxa** [comment]
yes i'm going this path 

I believe that role `kubectlRole` had to be assumable by Lambda initially, so no changes needed

**Comment by iliapolo** [comment]
> I believe that role kubectlRole had to be assumable by Lambda initially, so no changes needed

How come? We never used that role as a lambda execution role before. My guess is that requiring root account, like we do now, would also cover the ability of lambda to assume it, but this needs to be verified.

**Comment by aka-toxa** [comment]
let me doublecheck my aws account config

**Comment by aka-toxa** [comment]
yes right I didn't understand your question, sorry... 
so now kubectlRole has to be set to be assumable by account root to work with IRSA
so with those changes, nothing will be broken, but the customer will need to tighten trusted entities to lambda service

**Comment by iliapolo** [comment]
Sounds good. Lets try 👍

**Comment by aka-toxa** [comment]
hi @iliapolo after an internal round of review of my PR and internal discussing we find that this solution is not great at all. 
ideally having IAM role with admin permissions to the cluster we want to make sure that only one particular lambda can assume it. 
with this approach, we will be forced to put lambda.amazonaws.com to the trusted entities and allow any lambda get admin access to the cluster.


I think we should revisit this and think of how we can have single lambda for each stack that will use kubectl handler.

**Comment by aka-toxa** [comment]
we have multiple separated stacks that uses kubectl handler and each of them creates new lambda

**Comment by aka-toxa** [comment]
I think about separated function to deploy kubectl handler lambda 
then getting this lambda by its ARN and passing it to the Cluster configuration

so we can create lambda, then create kubectl role and put that lambda to the trusted entities and then use that lambda and role wherever we want

what do you think?

**Comment by iliapolo** [comment]
@aka-toxa 

> we will be forced to put lambda.amazonaws.com to the trusted entities and allow any lambda get admin access to the cluster.

Agreed thats not good.

> I think about separated function to deploy kubectl handler lambda
then getting this lambda by its ARN and passing it to the Cluster configuration

Can you elaborate exactly what you had in mind? Maybe sketch out the theoretical API in a README?

**Comment by aka-toxa** [comment]
yes I'm preparing the draft changes for that, it is a bit tough 
will show soon I'm almost done

**Comment by aka-toxa** [comment]
hi @iliapolo i've created another PR with different approach to resolve this 

https://github.com/aws/aws-cdk/pull/14689

I've added ability to provide existing kubectl provider lambda to the imported cluster so we can tight kubectl admin role to single lambda and make it more secure 

can you please check this approach, if it is ok I will cleanup it, add tests and documentation
