### ISSUE TITLE
(@aws-cdk/aws-lambda-event-sources) DynamoEventSource fails to associated with lambda

### ISSUE THREAD

**Issue by kazimanzurrashid** [aws/aws-cdk#12119]
Unable to associate lambda with DynamoEventSource.

The dynamodb table has been created by a different stack with stream of "new image". and I am trying to associate it with lambda in a separate stack.

### Reproduction Steps
```
var table =  Table.FromTableArn("...");
lambda.AddEventSource(new DynamoEventSource(table, new DynamoEventSourceProps {
   Enabled = true,
   StartingPosition = StartingPosition.LATEST
}));
```

### What did you expect to happen?

it should associate the lambda.

### What actually happened?

I am getting the following exception:
" Amazon.JSII.Runtime.JsiiException: DynamoDB Streams must be enabled on the table AnalyticsPusher/DepositsDynamoDBTable"

### Environment

  - **CDK CLI Version  : 1.78.0
  - **Framework Version:1.78.0
  - **Node.js Version: 14.4
  - **OS: mac mojave 10.14.3
  - **Language (Version): CSharp but it also happens in other languages as well, js/ts 

### Other

--- 

This is :bug: Bug Report

**Comment by redbaron** [comment]
`Table.FromTableArn` doesn't query table, it just creates object with a given ARN. It doesn't know if straming is enabled for that table.

Try using `Table.FromTableAttributes` and pass table ARN and stream ARN.

**Comment by kazimanzurrashid** [comment]
Well in that case the DynamoEventSource should take the table and stream arn instead of Table otherwise it breaks the basic principle of oop.

**Comment by redbaron** [comment]
does `Table.FromTableAttributes` work for you?

**Comment by kazimanzurrashid** [comment]
yes, but to find the stream arn i had use the aws sdk which i was not anticipating.

**Comment by redbaron** [comment]
Given that it works for you know and there is no actual bug in CDK, would you consider this issue resolved  and close it?
