### ISSUE TITLE
(iam): how to create combined managed policy?

### ISSUE THREAD

**Issue by akefirad** [aws/aws-cdk#12111]
Is there a way to create combined policy using CDK?

### Use Case
I'm trying to import (AWS or customer) managed policies into a new managed policy. I couldn't find any info regarding how to do this.

This is needed to cope with size limitations (e.g. number of policies in a group).

### Other
As a workaround I did this:
```typescript
const myManagedPolicy = ...;
const myCombinedPolicy = new iam.ManagedPolicy(this, "MyCombinedPolicy", {
  statements: myManagedPolicy.document.toJSON().Statement.map((s: any) => iam.PolicyStatement.fromJson(s))
});
```
This works fine, but has two limitations:
1. I can't assign any SID to the statements.
2. It won't work with AWS managed policy (since they're of type `iam.IManagedPolicy`)

**Comment by redbaron** [comment]
1. Try passing `autoAssignSids: false` to the combined managed policy. You can also reuse statements from `myManagedPolicy` constructor, then you can avoid JSON roundtrip

2. You'll have to make calls with `aws-sdk` yourself to query AWS managed policies I am afraid.

**Comment by akefirad** [comment]
> I can't assign any SID to the statements.

I think this is not relevant. I misspoke. Never mind.
> You can also reuse statements from myManagedPolicy constructor

I don't necessarily have access to them.
> You'll have to make calls with aws-sdk...

Right. I did it in a different way.

So based on the comment, my understanding is that, there's straightforward way to do and it's not to be considered as a feature.

**Comment by redbaron** [comment]
There is a history of adding lookup functions to contexts: https://docs.aws.amazon.com/cdk/latest/guide/context.html#context_methods   . Maybe managed policy lookups  can be added to the list?

**Comment by rix0rrr** [comment]
Yes, the contents of AWS Managed Policies are not available to CDK, without querying. It *could* be added, but this is of value to only a few individuals so unlikely to make it into CDK core.

An easy way to go about this is write a script that queries the policies you're looking for, writes the result to a `.json` file, and have your CDK app read and apply that json file at runtime.
