### ISSUE TITLE
(Cognito): specified callbackURL/logoutURL not set on app client

### ISSUE THREAD

**Issue by haiko** [aws/aws-cdk#12116]
When specifying the callbackUrl or logoutURL on a UserPoolClient of a UserPool the specified URL is not set upon succesfull creating the Stack.

### Reproduction Steps
- create a UserPool and UserPoolClient

          UserPool cognitoPool = UserPool.Builder.create(this, "GoodRefzPool")
                .userPoolName("ExamplePool")
                .autoVerify(AutoVerifiedAttrs.builder().email(Boolean.TRUE).build())
                .signInAliases(SignInAliases.builder().email(Boolean.TRUE).build())
              ...
                .build();

        UserPoolClient webClient = UserPoolClient.Builder
                .create(this, "ExamplePoolClient")
                .generateSecret(Boolean.FALSE)
                .idTokenValidity(Duration.days(1))
                .preventUserExistenceErrors(Boolean.TRUE)
                .oAuth(OAuthSettings.builder()
                        .callbackUrls(List.of("http://localhost:4200"))
                        .logoutUrls(List.of("http://localhost:4200"))
                        .build())
                .userPoolClientName("Example Client app")
                .userPool(cognitoPool)
                .oAuth(OAuthSettings.builder()
                        .flows(OAuthFlows.builder()
                                .authorizationCodeGrant(Boolean.TRUE)
                                .build())
                        .build())
                .build();

### What did you expect to happen?

An UserPool with a client with specified callbackURL and logoutURL

### What actually happened?

The default value for the callbackURL is listed

### Environment

  - **CDK CLI Version  :1.75.0
  - **Framework Version: 1.77.0
  - **Node.js Version:** v12.16.3
  - **OS               :Macos
  - **Language (Version):**  Java (11)

### Other
-

This is :bug: Bug Report

**Comment by haiko** [comment]
mistakenly closed

**Comment by nija-at** [comment]
Hey @haiko - how did you verify that the callback url is missing? 
Can you check the output of the CloudFormation template and see if it's present there?

**Comment by haiko** [comment]
Hi @nija-at I did not see the callback urls in the console. They are present in the CloudFormation template

**Comment by nija-at** [comment]
If they are present in the CloudFormation template and the template deploys successfully, the CDK is likely doing all of the correct things. 
You will need to talk to someone from Cognito via AWS support to get more help on this.
