### ISSUE TITLE
(custom-resources): support custom lambda role in provider framework

### ISSUE THREAD

**Issue by Ruben-E** [aws/aws-cdk#12126]
My project uses custom resources with the provider framework to handle the callback to CloudFormation. Thanks for making that easier!

But the provider framework does not support a custom role for the lambda function yet. 
We need it because the policy requires a permission boundary to be set on a role. Without permission boundary, roles cannot be created, including default roles.

### Use Case

* To pass a custom role with a permission boundary to the lambda.

### Proposed Solution

```
const aCustomRole = new iam.Role(this, 'CustomRole', {
    assumedBy: new ServicePrincipal('lambda.amazonaws.com'),
    managedPolicies: ...,
    permissionsBoundary: ...
});

const myProvider = new cr.Provider(this, 'MyProvider', {
    onEventHandler: onEvent,
    role: aCustomRole
});
```

### Other

* [x] :wave: I may be able to implement this feature request

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
Aren't you better off using an escape hatch to add this PermissionBoundary field onto the generated role object? By the very nature of the framework being in the Core library it cannot use any of the IAM classes so it will be mostly string manipulation anyway.
