### ISSUE TITLE
(aws-cloudfront): Origin Groups for CloudFrontWebDistribution construct  

### ISSUE THREAD

**Issue by yashgorana** [aws/aws-cdk#12137]
### The Question
Is there any way where we can use aws-cloudfront-origin's OriginGroup with an existing instance of CloudFrontWebDistribution construct?

We want to continue using the legacy CloudFrontWebDistribution construct and be able to use the newer CloudFront features like Origin Group, Cache Policy & Origin Request policy. I see we already have issues tracking the OriginRequestPolicy #10829 & CachePolicy #10830 support for CloudFrontWebDistribution, but don't have anything around Origin Groups.

**Comment by njlynch** [comment]
@yashgorana -

Support for Origin Groups was actually added to `CloudFrontWebDistribution` prior to the support in `Distribution`. See this section of the README for usage: https://docs.aws.amazon.com/cdk/api/latest/docs/aws-cloudfront-readme.html#origin-fallback

Hope that helps! Closing this out -- feel free to reopen if you have any follow-up questions.
