### ISSUE TITLE
(cloudfront): provide stack name for EdgeLambda 

### ISSUE THREAD

**Issue by bcraft** [aws/aws-cdk#12136]
Please would it be possible to add a parameter into the new edge lambda construct to specify the stack name which is created in us-east-1.

### Use Case

Different applications hosted in the same accounts who require independent lambda functions in us-east-1, currently the stack name is fixed at edge-lambda-stack-{REGION}, it would be useful to be able to override this.

This is a :rocket: Feature Request

**Comment by njlynch** [comment]
Sure, this is a reasonable request, and a fairly easy one to achieve. We'd just need to add a prop to `EdgeFunctionProps` and then use the value here:

https://github.com/aws/aws-cdk/blob/d90c5f0c11bbfc3c7a54a718544b223206fad3f2/packages/@aws-cdk/aws-cloudfront/lib/experimental/edge-function.ts#L206

**Comment by saudkhanzada** [comment]
@njlynch Can I take this up?
