### ISSUE TITLE
CDK-wide: Chainable Interfaces 

### ISSUE THREAD

**Issue by ellistarn** [aws/aws-cdk#12144]
Instead of:
```  
/**
   * Add one or more commands to the user data
   */
  public abstract addCommands(...commands: string[]): void
```
I'd prefer
```
  /**
   * Add one or more commands to the user data. Can be chained with subsequent withCommands.
   */
  public abstract withCommands(...commands: string[]): UserData
```

### Use Case
Many interfaces across CDK are not chainable. I've shown just one example. Is this an explicit style choice or an oversight?

This would allow my client code to be much more functional, less mutation, etc. 

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
It's an explicit style choice to not do fluent interfaces. Unlikely we're going to change anything there.
