### ISSUE TITLE
CDK prompt for MFA does not wait when executed as part of lerna run

### ISSUE THREAD

**Issue by dls314** [aws/aws-cdk#12143]
### The Question
What is the expected behavior when a CDK command like synth is executed as part of  `lerna run` with respect to asking for MFA token input?

What I observe is that the CDK synth command shows the MFA token input prompt, but does not wait for input, and no error occurs, but no output is generated.

### Environment

  - **CDK CLI Version:** 1.79.0 (build 8b3bf9c)     
  - **Module Version:** @aws-cdk/core 1.79.0
  - **Node.js Version:** v12.16.3
  - **OS:** Windows 10
  - **Language (Version):** TypeScript 4.1.3

### Other information
If I export temporary credentials into the environment, `cdk synth` works as expected when executed as part of `lerna run`.

**Comment by peterwoodworth** [comment]
This issue has to do with Lerna and not CDK. Sorry for not responding to you sooner and for the disappointing response, but there's nothing we can do here.
