### ISSUE TITLE
(pipelines): Should corresponding CloudFormation template start with pipeline name?

### ISSUE THREAD

**Issue by eikeon** [aws/aws-cdk#12145]
Proposing that a pipeline with stages would result in CloudFormation templates with names like:

pipelinename-stagename-... 

Currently it results in templates named

stagename-...

### Use Case

This would allow for using multiple CDK pipeline from the same account without possible collisions between them.

In particular, in our case we have a few pipelines for parts of our app that we've split off into dependencies that are packaged up into libraries of CDK constructs. And these pipelines also deploy the constructs as part of a test using them before the libraries get published. And I believe some of these names are going to clash when the app uses these constructs in the end via it depending on the libraries. Since all of this is happening from a single AWS account.

### Proposed Solution

Not proposing a solution at this time since I'm not deep enough in to know if this would make sense or is possible at this point.

### Other

* [x] :wave: I may be able to implement this feature request -- but only if it's fairly trivial :|
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by jumi-dev** [comment]
In the Stage class of the cdk pipeline, it's already possible to specify the name of the CloudFormation stack using the `stackName` property. You could pass the name of the pipeline into the StageProps and generate a custom stack name.

Example for stackName usage:
```ts
export class PipelineTestingStage extends Stage {
  constructor(scope: cdk.Construct, id: string, props?: StageProps) {
    super(scope, id, props);

    new TestingStack(this, 'TestingStack', {
      stackName: 'MyStackName',
    });

  }
}
```

**Comment by eikeon** [comment]
@jumi-dev Easy enough; although it might still make for a nice default name to have the pipeline prepended?

**Comment by rix0rrr** [comment]
Yes, I think the answer is customizing `stageName`.
