### ISSUE TITLE
(cloudfront): Authorization@Edge for private content

### ISSUE THREAD

**Issue by jumi-dev** [aws/aws-cdk#12158]
Private web applications hosted on CloudFront should be accessible only to authorized users (Cognito). This can be achieved using Lambda@Edge.

To fullfill this requirement with less effort, I would propose to implement a CDK construct to provide the authorization logic.

### Use Case
CloudFront is great to host static content / single-page applications. If companies are hosting private web applications, they should be accessible only to authorized users. 

### Proposed Solution

There is already a [reference implementation](https://aws.amazon.com/de/blogs/networking-and-content-delivery/authorizationedge-using-cookies-protect-your-amazon-cloudfront-content-from-being-downloaded-by-unauthenticated-users/) in die AWS blog. [Repository](https://github.com/aws-samples/cloudfront-authorization-at-edge).

This solution can be deployed with Serverless Application Repository / SAM.

I would propose to develop a similar solution in CDK.

### Other

The new [Lambda@Edge](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-cloudfront-readme.html#lambdaedge) construct could be a basis function for the implementation. Maybe it has to be enhanced for this feature if it will be implemented similar to the reference implementation. The example uses a function called lambda-code-inject (see [Readme](https://github.com/aws-samples/cloudfront-authorization-at-edge)) to inject configurations into the Lamda@Edge which could be an enhancement for the Lambda@Edge construct.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by stephenwiebe** [comment]
There's a construct for this here: https://github.com/cloudcomponents/cdk-constructs/tree/master/packages/cdk-cloudfront-authorization that I've been using and it seems to work well! It might be nice to have it as a native CDK provided construct though.

**Comment by njlynch** [comment]
Thanks for the feature request.

The scope of what you're describing, and what's described in the blog post, is generally what we'd describe as an "L3 construct"; this exceeds simply making it easier to construct an AWS resource, and into a more useful -- but targeted -- combination of resources to achieve a specific purpose. We generally consider L3s out of scope for the CDK itself. We'd prefer to build the basic building blocks (L1s and L2s) in the CDK itself, and have the community publish interesting combinations and full applications as third-party libraries. I can't personally attest for the library stephenwiebe linked above, but at a quick glance it looks like it might be what you're looking for.

I'm going to close this as out of scope, but feel free to reopen if you have any follow-ups.
