### ISSUE TITLE
(@aws-cdk/aws-ecs): unable to add data volumes to a task definition

### ISSUE THREAD

**Issue by wistonk** [aws/aws-cdk#12157]
Getting below errors when adding a volume on a task definition using `@aws-cdk/aws-ecs` module.
```
- Volume' does not exist on type 'typeof import...
- Property 'EfsVolumeConfiguration' does not exist ...
```
### Reproduction Steps
- Create a task definition and add a volume

```
const volume = ecs.Volume("Volume", {
  // Use an Elastic FileSystem
  name: "mydatavolume",
  efsVolumeConfiguration: ecs.EfsVolumeConfiguration({
    fileSystemId: "EFS"
    // ... other options here ...
  })
});

const container = fargateTaskDefinition.addVolume("mydatavolume");

```

### What did you expect to happen?

Successfully add data volumes to a task definition without above stated error

### What actually happened?

```
error TS2339: Property 'Volume' does not exist on type 'typeof import("/Users/me/../../myproject/node_modules/@aws-cdk/aws-ecs/lib/index")'.
```
and
```
error TS2339: Property 'EfsVolumeConfiguration' does not exist on type 'typeof import("/Users/me/../../myproject/node_modules/@aws-cdk/aws-ecs/lib/index")'.
```
### Environment

  - **CDK CLI Version  : 1.79.0 (build 8b3bf9c)
  - **Framework Version:** 
  - **Node.js Version: v14.4.0
  - **OS               :macOs Catalina
  - **Language (Version):TypeScript (3.8.3) 

--- 

This is :bug: Bug Report

**Comment by whilp** [comment]
Ran into this, too. It seems like `Volume` was only added as an interface in https://github.com/aws/aws-cdk/pull/8467. There, the documentation disagrees with the test:

https://github.com/aws/aws-cdk/blob/e8801a0ddb04e75de87ba34f3a58b1adebae5301/packages/%40aws-cdk/aws-ecs/README.md#L249-L258
https://github.com/aws/aws-cdk/blob/85ff9fd7cf93082e88e2aafc97916fa505484c6d/packages/%40aws-cdk/aws-ecs/test/ec2/test.ec2-task-definition.ts#L988-L993

I can at least proceed to compile (TypeScript) using the approach evident in the tests.
