### ISSUE TITLE
(cli): cross account deployments still don't work

### ISSUE THREAD

**Issue by redbaron** [aws/aws-cdk#12151]
### Reproduction Steps

CI account: 0147xxxxxxxx
Target account: 1454xxxxxxx

Target account  is bootstrapped to trust CI account with `--trust 0147xxxxxxxx` .  IAM user in CI account graned permission `iam:AssumeRole` to all roles created by bootstrap stack.

Create CDK app with environment in target account and an S3 asset:

```
...
new Stack(app, 'Stack', { env: {account: "1454xxxxxxx", region: "eu-west-2" }});
...
```
Do `cdk deploy` from CI account.

### What did you expect to happen?

Successfull deploy

### What actually happened?

If we try to deploy it with `cdk deploy -v` following happens:

```
OrganizationStack
OrganizationStack: deploying...
Looking up default account ID from STS
Default account ID: 0147xxxxxx
Assuming role 'arn:aws:iam::1454xxxxxx:role/cdk-hnb659fds-deploy-role-1454xxxxx-eu-west-2'.
Waiting for stack CDKToolkit to finish creating or updating...
[0%] start: Publishing 4a3609ad912843e581892f37ae9d6fb0fa1648b547693aaa562b0119452b8956:145469417702-eu-west-2
[50%] fail: Need to perform AWS calls for account 1454xxxxxxx, but the current credentials are for 0147xxxxxx
[50%] start: Publishing 97b2255ceb5577d4534d825ed8407ced52d0f8917ce15f7a76d5c47aba9bd603:145469417702-eu-west-2
[100%] fail: Need to perform AWS calls for account 1454xxxxxxxx, but the current credentials are for 0147xxxxxx
```

### Environment

  - **CDK CLI Version  :** 1.78.-
  - **Framework Version:**
  - **Node.js Version:** 14
  - **OS               :** Linux
  - **Language (Version):** Typescript

### Other

Interestingly, `cdk-assets` uploads just fine. Exact commands when run from CI:

```
  - yarn add -D aws-cdk@1.78.0 
  - node_modules/.bin/cdk synth --verbose
  - node_modules/.bin/cdk-assets publish -p cdk.out/OrganizationStack.assets.json -v
  - node_modules/.bin/cdk deploy --require-approval=never --all --verbose
```

Produce following output (tail):

```
$ node_modules/.bin/cdk synth --verbose
Successfully synthesized to /data/build/X-WKy9gs/0/dir/devops/iac/organization/cdk.out
Supply a stack id (OrganizationStack, SingleSignOnStack) to display its template.

$ node_modules/.bin/cdk-assets publish -p cdk.out/OrganizationStack.assets.json -v
verbose: Loaded manifest from cdk.out/OrganizationStack.assets.json: 2 assets found
info   : [0%] start: Publishing 4a3609ad912843e581892f37ae9d6fb0fa1648b547693aaa562b0119452b8956:1454xxxxxxx-eu-west-2
verbose: Assume arn:aws:iam::1454xxxxxxx:role/cdk-hnb659fds-file-publishing-role-1454xxxxxxx-eu-west-2
verbose: [0%] check: Check s3://cdk-hnb659fds-assets-1454xxxxxxx-eu-west-2/4a3609ad912843e581892f37ae9d6fb0fa1648b547693aaa562b0119452b8956.zip
verbose: [0%] found: Found s3://cdk-hnb659fds-assets-1454xxxxxxx-eu-west-2/4a3609ad912843e581892f37ae9d6fb0fa1648b547693aaa562b0119452b8956.zip
info   : [50%] success: Published 4a3609ad912843e581892f37ae9d6fb0fa1648b547693aaa562b0119452b8956:1454xxxxxxx-eu-west-2
info   : [50%] start: Publishing 97b2255ceb5577d4534d825ed8407ced52d0f8917ce15f7a76d5c47aba9bd603:1454xxxxxxx-eu-west-2
verbose: Assume arn:aws:iam::1454xxxxxxx:role/cdk-hnb659fds-file-publishing-role-1454xxxxxxx-eu-west-2
verbose: [50%] check: Check s3://cdk-hnb659fds-assets-1454xxxxxxx-eu-west-2/97b2255ceb5577d4534d825ed8407ced52d0f8917ce15f7a76d5c47aba9bd603
verbose: [50%] upload: Upload s3://cdk-hnb659fds-assets-1454xxxxxxx-eu-west-2/97b2255ceb5577d4534d825ed8407ced52d0f8917ce15f7a76d5c47aba9bd603
info   : [100%] success: Published 97b2255ceb5577d4534d825ed8407ced52d0f8917ce15f7a76d5c47aba9bd603:1454xxxxxxx-eu-west-2


$ node_modules/.bin/cdk deploy --require-approval=never --all --verbose
...
OrganizationStack
OrganizationStack: deploying...
Looking up default account ID from STS
Default account ID: 0147xxxxxxx
Assuming role 'arn:aws:iam::1454xxxxxxx:role/cdk-hnb659fds-deploy-role-1454xxxxxxx-eu-west-2'.
Waiting for stack CDKToolkit to finish creating or updating...
[0%] start: Publishing 4a3609ad912843e581892f37ae9d6fb0fa1648b547693aaa562b0119452b8956:1454xxxxxxx-eu-west-2
[50%] fail: Need to perform AWS calls for account 1454xxxxxxx, but the current credentials are for 0147xxxxxxx
[50%] start: Publishing 97b2255ceb5577d4534d825ed8407ced52d0f8917ce15f7a76d5c47aba9bd603:1454xxxxxxx-eu-west-2
[100%] fail: Need to perform AWS calls for account 1454xxxxxxx, but the current credentials are for 0147xxxxxxx
```

Looks like fix done in https://github.com/aws/aws-cdk/pull/11966 is incomplete. 

/cc @rix0rrr , @scarytom , @polothy 

--- 

This is :bug: Bug Report

**Comment by redbaron** [comment]
I tracked it down to:

https://github.com/aws/aws-cdk/blob/4e1d951f39b171759db14223175324e28d03e582/packages/aws-cdk/lib/util/asset-publishing.ts#L46-L48

`cdk_assets.IAws.discoverCurrentAccount()` method meant to return id a of a target account. Among other users,it is used by `FileAssetHandler` from `cdk_asset` to replace placeholders in `asset.destination`:

https://github.com/aws/aws-cdk/blob/4e1d951f39b171759db14223175324e28d03e582/packages/cdk-assets/lib/private/handlers/files.ts#L22

But `asset.destination` contains `assumeRoleArn`  (via `cloud-assembly-schema.AwsDestination`), which can contain placeholders!  Problem  lies in a circular dependency: 
- To template `assumeRoleArn` we need to call `STS().getCallerIdentity()`
- but `getCallerIdentity()`  need to be called from the assumed role `assumeRoleArn` to produce target account id!


`SdkProvider.ForEnvironment` expects either source account to match target account or to be called with fully resolved role to assume in the target account.  `cdk_assets.IAws.discoverCurrentAccount()` doesn't have that role yet, because it is used to resolve that very role.

It would be tricky to resolve. Possibly if placeholder replacement for `AwsDestination` was done with source  (base) credentials only it can fix it. This will break circular dependency without breaking APIs.

**Comment by OperationalFallacy** [comment]
Seeing this with CloudFormationCreateUpdateStackAction and CdkPipeline.

I have a question, how the CDK Pipeline is able to deploy across accounts (example here https://github.com/aws/aws-cdk/issues/10166)?
Isn't this broken plugin-based assume creds functionality relies on the same account/roles bootstrapping by cdk?

**Comment by polothy** [comment]
Just got back from PTO - in my testing, the CDK diff seemed to work cross account, but then yeah, got the same error as you when it tried to deploy and it failed to upload an asset.

Thanks for submitting that PR, hopefully that gets us across the line and I can drop this plugin 🤞

**Comment by polothy** [comment]
Maybe no one will see this comment, but I was just able to deploy cross account with no plugins 🎉 

Thanks @redbaron and @rix0rrr for fixing this!
