### ISSUE TITLE
(ecr): repository missing in container image

### ISSUE THREAD

**Issue by kay-is** [aws/aws-cdk#12167]
Somehow the `repository` attribute is empty in a `ContainerImage` instance created via `fromDockerImageAsset`.

### Reproduction Steps

I used the `fromDockerImageAsset` method with a path pointing to a local directory with a `Dockerfile`.

### What did you expect to happen?

I expected an image to be built from a local `Dockerfile`, uploaded to a (AWS internal?) registry, and then it getting used in my task/container definition.

### What actually happened?

I tried to use `ecs.ContainerImage.fromDockerImageAsset("./services/api")` which resulted in an error on `cdk synth`.

```
/home/ec2-user/environment/ecs-test/node_modules/@aws-cdk/aws-ecs/lib/container-image.js:47
                asset.repository.grantPull(containerDefinition.taskDefinition.obtainExecutionRole());
                                 ^

TypeError: Cannot read property 'grantPull' of undefined
```
--- 

This is :bug: Bug Report

**Comment by redbaron** [comment]
`fromDockerImageAsset` doesn't accept string, but instance of DockerImageAsset: https://docs.aws.amazon.com/cdk/api/latest/typescript/api/aws-ecs/containerimage.html#aws_ecs_ContainerImage_fromDockerImageAsset

So you'd need to do something like this:

```
ecs.ContainerImage.fromDockerImageAsset(new DockerImageAsset(this, 'Image', {
      directory: path.join(__dirname, 'services', 'api')
    }))
```
