### ISSUE TITLE
(@aws-cdk/core): DefaultStackSynthesizer doesn't support Aws.REGION leads to cdk-assets publish error

### ISSUE THREAD

**Issue by wchaws** [aws/aws-cdk#12161]
`DefaultStackSynthesizer` doesn't support Aws token like `Aws.REGION`, that will lead to `cdk-assets publish` error because the generated `assets.json` includes `"bucketName": "my-solutions-${Token[AWS.Region.4]}"` which is un-recognizable for `cdk-assets`

### Reproduction Steps

```ts
import {Aws, DefaultStackSynthesizer } from '@aws-cdk/core';

...

new MyWidgetServiceStack(app, 'MyWidgetServiceStack', {
  synthesizer: new DefaultStackSynthesizer({
    fileAssetsBucketName: `my-solutions-${Aws.REGION}`,
    bucketPrefix: 'cdknewstyle/latest/',
  })
});
```

### What did you expect to happen?

assets publish success

### Environment

  - **CDK CLI Version  :** 1.79.0 (build 8b3bf9c)
  - **Framework Version:** 1.79.0
  - **Node.js Version:**  v14.4.0
  - **OS               :** MacOS Catalina 10.15.7
  - **Language (Version):**  n/a

### Other

--- 

This is :bug: Bug Report

**Comment by redbaron** [comment]
newstyle synth requires target account bootstrapping, which AFAIK have to be done per region as well. When you deploy newstyle synth stack, it discovers correct bucket for each stack you try to deploy.

It is unlikely that even if this token is fixed, stack will become deployable without further changes to `CDKToolkit` stack created by `cdk bootstrap`.

Also `aws-core.Aws` contains tokens for CF [pseudoparameters](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/pseudo-parameter-reference.html) , which have no meaning outside of cloudformation stack.

**Comment by rix0rrr** [comment]
Yes you can't use tokens here. We do support this though (in a very limited fashion), but you need to write it as:

```
    fileAssetsBucketName: 'my-solutions-${AWS::Region}',
```

We use "magic markers" that happen to be the same as the magic markers that CloudFormation uses (although they will be interpreted by us and not by CFN).

Sorry if this is confusing.
