### ISSUE TITLE
@aws-cdk/aws-apigatewayv2: DomainName cannot be imported and used in another stack

### ISSUE THREAD

**Issue by brentryan** [aws/aws-cdk#12173]
When creating a CDK application, we often have a CDK App that is composed of more than 1 stack. In some cases we may have 1 stack that represents the API Gateway and another stack that represents Route53 records pointing to the DomainName created in the other stack. 

### Reproduction Steps

Stack 1 creates an HttpApi and DomainName.
Stack 2 tries to use the DomainName created in Stack 1 like:
```
    new route53.RecordSet(scope, `DnsRecord`, {
      recordType: route53.RecordType.A,
      target: route53.RecordTarget.fromAlias(new targets.ApiGatewayv2Domain(dn)),
      zone,
      recordName,
      ttl: cdk.Duration.minutes(5)
    });

```

This will fail with an error during "cdk synth" that will say something like regionalDomainName attribute is missing.

### What did you expect to happen?

I'd expect to be able to reference DomainName created in other stacks. For example, I can do the same thing above with an application load balancer and it works fine, but the way the DomainName is written it doesn't work because it's looking for attributes referenced in the current stack.

### Environment

  - **CDK CLI Version  :** 1.79.0
  - **Framework Version:** 1.79.0
  - **Node.js Version:** 12.18.4
  - **OS               :** MacOS
  - **Language (Version):** TypeScript

--- 

This is :bug: Bug Report

**Comment by redbaron** [comment]
How do you instantiate `zone`?

**Comment by brentryan** [comment]
This is how the domain name is created in Stack 1.
```
    const dn = new apigw.DomainName(scope, 'APIDomainName', {
      domainName: recordName,
      certificate: acm.Certificate.fromCertificateArn(scope, 'APICert', cert.certificateArn)
    });
```

**Comment by brentryan** [comment]
Are you saying that in Stack 2 we'd have to do this (where dnFromStack1 comes from Stack 1):

```
const dn = apigw.DomainName.fromDomainNameAttributes(scope, 'DN', {
  name: dnFromStack1.name,
  regionalDomainName: dnFromStack1.regionalDomainName,
  regionalHostedZoneId: dnFromStack1.regionalHostedZoneId
});

    new route53.RecordSet(scope, `DnsRecord`, {
      recordType: route53.RecordType.A,
      target: route53.RecordTarget.fromAlias(new targets.ApiGatewayv2Domain(dn)),
      zone,
      recordName,
      ttl: cdk.Duration.minutes(5)
    });
```

**Comment by brentryan** [comment]
Ignore this issue. It appears that I wasn't properly exporting the domain name from the other stack. And it doesn't matter anyways because you can't have a different Route53 domain name pointing to the same custom domain name anyways because of SNI. Scratch this idea...
