### ISSUE TITLE
cdk init lib: should create a sample unit test

### ISSUE THREAD

**Issue by rix0rrr** [aws/aws-cdk#1217]
But probably not using `nodeunit`, let's set a good example.

I don't care as much about what we use, but we shouldn't force/encourage other people to use a deprecated project.

**Comment by moofish32** [comment]
I've been using Jest and I think we could port our Assert library over there. We have matchers in various packages that would be nice to consolidate too.

**Comment by NGL321** [comment]
For future tracking see #3945
