### ISSUE TITLE
(cfnspec): cloudformation spec v22.0.0

### ISSUE THREAD

**Issue by pahud** [aws/aws-cdk#12170]
`v22.0.0` was released and we need bump this version for new resources/properties.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by MarkBiesheuvel** [comment]
I would like this feature to be able to use `EnclaveOptions` in `AWS::EC2::Instance`.

Docs: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-enclaveoptions
