### ISSUE TITLE
(aws-cdk): Installing CLI locally should be the default

### ISSUE THREAD

**Issue by kmturley** [aws/aws-cdk#12187]
**Reference docs**
```
$ npm i -g aws-cdk
```
https://github.com/aws/aws-cdk/blob/master/README.md#at-a-glance
```
npm install -g aws-cdk
```
https://docs.aws.amazon.com/cdk/latest/guide/getting_started.html#getting_started_install

**Issue**

I switched CDK projects and found issues with the package.json being:
```
"aws-cdk": "1.68.0",
```
But my global version:
```
cdk --version // 1.79.0 (build 8b3bf9c)
```

Quoting from the webpack installation guide regarding global installation:

> Note that this is not a recommended practice. Installing globally locks you down to a specific version of webpack and could fail in projects that use a different version.

https://webpack.js.org/guides/installation/#global-installation

**Recommendation**

Make installing locally the default option:
```
npm install aws-cdk
```
And install globally as an alternative option (not recommended)
```
npm install aws-cdk -g
```

---

This is a 📕 documentation issue

**Comment by redbaron** [comment]
`aws-cdk` is a CLI tool and is not directly related to `@aws-cdk` packages you use in your CDK app.

**Comment by NGL321** [comment]
Hey @kmturley,

@redbaron is exactly right. In general we would hope that (like most other node tools) the cdk is installed and kept updated globally in most cases (with the potential exception of projects on your system incompatible with the latest cdk version you want installed globally). The individual @aws-cdk packages are not installed globally, so there should be fewer conflicts (ie. you can deploy a cdk application that uses packages of version `@aws-cdk@1.81.0` using any version of the cli greater than `1.81.0`)

I hope that helps!

😸 😷

**Comment by kmturley** [comment]
@NGL321 maybe the confusion is because the packages are the same name? Should the cli and cdk be tightly coupled?

**Comment by kmturley** [comment]
Looks like there has been an improvement in the documentation for this:

_If you regularly work with multiple versions of the AWS CDK, you may want to install a matching version of the AWS CDK Toolkit in individual CDK projects. To do this, omit -g from the npm install command. Then use npx cdk to invoke it; this will run the local version if one exists, falling back to a global version if not._
https://docs.aws.amazon.com/cdk/latest/guide/cli.html

This does exactly what I was asking for! ensuring cdk cli version matches cdk package versions.

I would recommend `npx cdk` becomes the default cli command in the future if cdk versioning does not follow semvar...
