### ISSUE TITLE
(@aws-cdk/aws-iot): Create CfnTopicRule and failed to add timestream as action

### ISSUE THREAD

**Issue by aedris0** [aws/aws-cdk#12198]
I want to create CfnTopicRule using @aws-cdk/aws-io and I want to add action timestream to save data.
I created it manually from the management console and everything fine, but when I'm trying to create the rule from the cdk and add timestream as action, the actions list doesn't support timestream note that all actions appear except timestream.

error:
`TS2322: Type '{ timestream: { roleArn: string; databaseName: string; tableName: string; timestamp: { value: string; unit: string; }; dimensions: { name: string; value: string; }[]; }; }' is not assignable to type 'IResolvable | ActionProperty'.   Object literal may only specify known properties, and 'timestream' does not exist in type 'IResolvable | ActionProperty'.`

**Environment**

- CDK Version : 1.79.0
- Framework Version: 1.79.0
- Node.js Version: 12.16.3
- OS : windows
- Language: Typescript

**Comment by JoshM1994** [comment]
I believe this is blocked by CloudFormation not yet supporting timestream IoT rules... https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/663 🤦‍♂️

**Comment by FabioGentile** [comment]
Cloudformation now supports Timestream actions: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-iot-topicrule-timestreamaction.html

**Comment by peterwoodworth** [comment]
Supported now, so good to close?
