### ISSUE TITLE
ElasticSearch: support V7_9

### ISSUE THREAD

**Issue by ce-tomas** [aws/aws-cdk#12202]
Although AWS supports the creation of ES domains with version 7.9 CDK only supports 7.7:
`aws_elasticsearch.ElasticsearchVersion.V7_7` is max we can get as of Today (CDK 1.80)

### Use Case

by simply adding enumerator `ElasticsearchVersion.V7_9` to the `aws_elasticsearch` module people would be able to enjoy the benefits of the newer ES version.

### Proposed Solution

add enum `V7_9`

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by NetaNir** [comment]
You can workaround this today by passing a version:

```
ElasticsearchVersion.of('7.9')
```

We can add it to the list of predefined types, happy to review a PR, should be added: https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-elasticsearch/lib/domain.ts#L20
