### ISSUE TITLE
(s3-deployment): handler uses deprecated botocore API

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#12219]
I am seeing this warning in the logs of the custom resource used by the s3-deployment module:

```
/var/runtime/botocore/vendored/requests/api.py:72: DeprecationWarning: You are using the put() function from 'botocore.vendored.requests'.  This dependency was removed from Botocore and will be removed from Lambda after 2021/01/30. https://aws.amazon.com/blogs/developer/removing-the-vendored-version-of-requests-from-botocore/. Install the requests package, 'import requests' directly, and use the requests.put() function instead.
--
```

### Reproduction Steps

Run integ s3-deploy integ tests.

### What did you expect to happen?

We should use a different way to submit CFN responses (maybe move to the custom resources framework?)

### What actually happened?

This will no longer work after the end of Jan 2021.

### Environment

  - **CDK CLI Version  :** 1.80.0
  - **Framework Version:** 1.80.0

### Other

--- 

This is :bug: Bug Report

**Comment by NetaNir** [comment]
Im following up on this

**Comment by NetaNir** [comment]
https://aws.amazon.com/blogs/compute/upcoming-changes-to-the-python-sdk-in-aws-lambda/
