### ISSUE TITLE
(elasticsearch): UpdatePolicy for Domain

### ISSUE THREAD

**Issue by bnelson-unit** [aws/aws-cdk#12210]
Adding the ability to set an UpdatePolicy for an Elasticsearch Domain

### Use Case

Cloud formation supports the ability to set an UpdatePolicy for Elasticsearch domains. As a result, it's possible to perform an in-place upgrade between versions via cloudformation. This functionality was added to the CfnDomain earlier in the year ([issue 6158 ](https://github.com/aws/aws-cdk/issues/6158) ).  However, as far as I can tell, it's not possible to set an update policy when using the Domain construct.   As a result, changing the ElasticsearchVersion in Domain will always cause a replacement upgrade.  

Could it be possible to add this?

---

This is a :rocket: Feature Request

**Comment by iliapolo** [comment]
Marking this as a feature request to add to the L2 construct.

In the meantime, you can use the following workaround:

```ts
const domain = new elastic.Domain(this, 'Domain', {
  version: elastic.ElasticsearchVersion.V7_7,
});

const cfnDomain = domain.node.defaultChild as elastic.CfnDomain;
cfnDomain.cfnOptions.updatePolicy = {
  ...cfnDomain.cfnOptions.updatePolicy,
  enableVersionUpgrade: true,
}

```

**Comment by hassanazharkhan** [comment]
@iliapolo Can I take this up?

**Comment by iliapolo** [comment]
@hassanazharkhan for sure! 👍
