### ISSUE TITLE
(lambda): Add ability to sign code using a code signing profile

### ISSUE THREAD

**Issue by dontirun** [aws/aws-cdk#12216]
Lambda supports now [code signing](https://aws.amazon.com/blogs/aws/new-code-signing-a-trust-and-integrity-control-for-aws-lambda/) . I suggest the CDK should add the ability to take a signer profile and sign unbundled/bundled assets after they are uploaded to S3. (This will require versioning to be enabled on the Bootstrap bucket)

I can currently do this with CloudFormation deployments utilizing the SAM CLI but not with the CDK

### Use Case
I would like to verify the Lambda functions that I deploy as part of a Pipeline have been created by a trusted entity and unmodified. 

---

This is a :rocket: Feature Request

**Comment by nija-at** [comment]
This feature is not yet available in CloudFormation.

**Comment by dontirun** [comment]
Although the CloudFormation documentation says it's unsupported, the [SAM documentation](
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-codesigningconfigarn) for the CodeSigningConfigArn says that it is supported and passes it directly to that property for CloudFormation

**Comment by dontirun** [comment]
Additionally the ability to use signed code is independent from the CodeSigning config on the lambda function. The code needs to be signed via AWS Signer using a valid profile. If the Lambda then has the proper configuration the signing profile then the function will properly deploy.

This ask is to implement both parts (with lambda bundling/assets)

[This is the code](https://github.com/aws/aws-sam-cli/blob/develop/samcli/lib/package/code_signer.py) used in the SAM CLI to upload the code to and S3 bucket, start the signing job, and then returned the S3 location to the signed artifact.

**Comment by nija-at** [comment]
Thanks for letting me know that this is available in CloudFormation.

**Comment by hedrall** [comment]
It seems to Cdk has Cfn resource named CfnCodeSigning Config , now.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-codesigningconfigarn

**Comment by dontirun** [comment]
I really appreciate the work that has gone into PR #12656 , but I do not believe the PR will fully address this issue. If the code signing profile is set to Enforce, and I specify local code the deployment will fail due to code not being signed. The PR will resolve all the CloudFormation related aspects of this request, but there is an additional component to sign the code after it  is uploaded to S3 (which I believe the CDK can handle)
