### ISSUE TITLE
aws-iam: add AWS::IAM::InstanceProfile

### ISSUE THREAD

**Issue by cmaurer** [aws/aws-cdk#1223]
implement AWS::IAM::InstanceProfile

**Comment by SomayaB** [comment]
Seems to be implemented, see [docs](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-iam.CfnInstanceProfile.html#class-cfninstanceprofile-construct).
Closing this issue. Feel free to reopen if this doesn't address your request.
