### ISSUE TITLE
(aws-apigatewayv2): Support DisableExecuteApiEndpoint parameter

### ISSUE THREAD

**Issue by kennu** [aws/aws-cdk#12241]
CloudFormation AWS::ApiGatewayV2::Api supports a simple boolean [DisableExecuteApiEndpoint](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigatewayv2-api.html#cfn-apigatewayv2-api-disableexecuteapiendpoint) parameter.

The DisableExecuteApiEndpoint parameter is missing from @aws-cdk/aws-apigatewayv2 [HttpApi](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-apigatewayv2.HttpApi.html).

### Environment

  - **CDK CLI Version  :** 1.80.0
  - **Framework Version:** 1.80.0

--- 

This is :bug: Bug Report

**Comment by kennu** [comment]
My simple escape hatch override for this is:

    import { HttpApi, CfnApi } from '@aws-cdk/aws-apigatewayv2'
    const httpApi = new HttpApi(this, 'HttpApi', { ... })
    const cfnApi = httpApi.node.defaultChild as CfnApi
    cfnApi.disableExecuteApiEndpoint = true

**Comment by rrhodes** [comment]
Hi @nija-at, @kennu, I've opened a PR to add support for `DisableExecuteApiEndpoint` parameter, hopefully have that merged in shortly for you.
