### ISSUE TITLE
[pipelines]: AddStageOptions in addApplication needs config for variable namespace

### ISSUE THREAD

**Issue by OperationalFallacy** [aws/aws-cdk#12252]
### The Question

Would like below feature supported in CDK pipelines, when cf outputs available as env variables 
https://docs.aws.amazon.com/codepipeline/latest/userguide/tutorials-cloudformation-action.html 

```
const DeployCDK = pipeline.addStage('deployApp');
const app = new PipelineStage(this, 'deployApp', {env: {region: xxx, account: xxx} })

// new property variablesNamespace
DeployCDK.addApplication(app, {
    variablesNamespace: 'CfOutputs' 
  });
```

### Other information

The workaround is to use `CloudFormationCreateUpdateStackAction` from '@aws-cdk/aws-codepipeline-actions' which has variablesNamespace in the properties.

**Comment by skinny85** [comment]
Hello @OperationalFallacy ,

Actually, the `CloudFormationCreateUpdateStackAction` does not support any variables at this time... we need to fix that first.

Docs: https://docs.aws.amazon.com/codepipeline/latest/userguide/reference-variables.html#w2aac48c29b9b7

Thanks,
Adam

**Comment by OperationalFallacy** [comment]
If I add action like this to the pipeline

```
    const b = new actions.CloudFormationCreateUpdateStackAction({
      stackName: 'somestack',
      templatePath: cloudAssemblyArtifact.atPath('somepath'),
      actionName: 'actionz',
      variablesNamespace: 'MyVars'
    });

  CdkStage1.addActions(comboAction, b);
```

 I see the namespace in the generated CF. Am I missing something here?

Do you think it is possible to extend CdkPipeline.addApplicationStage method to make the resulting actions set namespace? Or just "patch" synth stack? 

I needed this to access stack outputs from many parallel CF deployments in a stage since just 5 artifacts (inputs) available in Codepipeline and those are used in ShellScriptAction to access CF outputs. As mentioned here https://github.com/aws/aws-cdk/issues/11462 the ShellScriptAction should've used Codepiline variables rather than parsing cloudformation deployment artifacts
