### ISSUE TITLE
(eks): launch template user data docs wrong

### ISSUE THREAD

**Issue by dirknilius** [aws/aws-cdk#12256]
The docs have an example of providing custom user data to EKS managed node groups: https://docs.aws.amazon.com/cdk/api/latest/docs/aws-eks-readme.html#launch-template-support

This produces the error `User data was not in the MIME multipart format`. This does not work as the user data has to be in `MIME multipart` format as described here: https://docs.aws.amazon.com/eks/latest/userguide/launch-templates.html#launch-template-user-data

There is already a feature request regarding MIME multipart in EC2 userdata: https://github.com/aws/aws-cdk/issues/8315

This works:

```typescript
const userData = `MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="==MYBOUNDARY=="

--==MYBOUNDARY==
Content-Type: text/x-shellscript; charset="us-ascii"

#!/bin/bash
echo "Running custom user data script"

--==MYBOUNDARY==--\\
`

const launchTemplate = new ec2.CfnLaunchTemplate(this, 'ManagedNodeLaunchTemplate', {
  launchTemplateData: {
    userData: cdk.Fn.base64(userData)
  }
})
```

It would be nice to update the docs and really really nice to add the MIME multipart support to `ec2.UserData`

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment]
@dirknilius The example in the docs specifically refers to when a custom AMI is used, to which the EKS docs state:

> Amazon EKS doesn't merge user data when a custom AMI ID is specified in a launch template.

In this case I believe it doesn't have to be a multipart. From the code you posted, can I assume you didn't specify a custom AMI? if so than its the expected behavior. But I agree the example should be clearer though.

**Comment by dirknilius** [comment]
@iliapolo Oh yes, you are right. I didn't have a custom AMI defined. I also agree that the docs should cover custom user data without a custom AMI. Do you think the snipped that's included in my bug description is suitable as an example for the docs? In that case I would contribute a PR.

**Comment by iliapolo** [comment]
@dirknilius Yes, that would be great :)

**Comment by dirknilius** [comment]
@iliapolo 

PR pending: https://github.com/aws/aws-cdk/pull/12272
