### ISSUE TITLE
(ec2): Cannot reference an imported Subnet's IPv4 CIDR

### ISSUE THREAD

**Issue by Cloudrage** [aws/aws-cdk#12268]
### Reproduction Steps
When importing a VPC and trying to get Subnets CIDR (from another account) :

`You cannot reference an imported Subnet's IPv4 CIDR if it was not supplied. Add the ipv4CidrBlock when importing using Subnet.fromSubnetAttributes()
`

Just want  to say "lol".
If I want to import the IPv4 CIDR Block, I can't provide it when importing Subnets ;D

### What did you expect to happen?
Since few months/years (and related issues); we can't import CIDR Block easily; just want to do that natively (I'm using Secrets with VPC properties like that).

### What actually happened?

We can't import easily Subnet CIDR Block easily, especialy from another account.

### Environment

  - **CDK CLI Version  : 1.77.0**

--- 

This is :bug: Bug Report

**Comment by coleman-c** [comment]
There's a work around in this thread reporting the same issue:  https://github.com/aws/aws-cdk/issues/11821.  It's in Typescript, but the principle can be applied to whatever language you are using.

Duplicate of # 11821

**Comment by rix0rrr** [comment]
Closing as duplicate.
