### ISSUE TITLE
(aws-lambda): Error: No child with id: 'InvokeServicePrincipal(apigateway.amazonaws.com)'

### ISSUE THREAD

**Issue by devendra-kumar1** [aws/aws-cdk#12263]
I have a stack where i have  resources called api gateway and lambda.
Also i am importing one lambda which is part of different stack and attaching it to once resource of api gateway.

I am facing below issues.

1. API GW resource is giving 500 error while invocation due to  invalid permission for imported lambda however it is not for lambda created as part of stack.
   **Note** :  Later on I learnt from issue that this is as per design due to variable **canCreatePermissions**
2.  So to avoid the above issue i thought to add below line of code to grantInvoke but it is also throwing error while trying to synth
Code : this.importedLambda.grantInvoke(new ServicePrincipal('apigateway.amazonaws.com'));

### Reproduction Steps

  - **CDK CLI Version  :*1.62.0*
  - **Framework Version:*1.62.0*
  - **Node.js Version:** 12.0
  - **OS               :*Windows*
  - **Language (Version):** TypeScript (3.8.3)

Reffered issue #8240 but no luck.

Please guide me in right direction

**Comment by nija-at** [comment]
Hi @devendra-kumar1 - where is this imported lambda? Is it part of the same account and region or elsewhere?

Please provide a code that reproduces this issue.

**Comment by devendra-kumar1** [comment]
@nija-at Imported lambda in same account and region.
Sample code i am using .
const importedLambda = Function.fromFunctionArn(scope, 'importedLambda', 'Arn of imported lambda');
this.importedLambda.grantInvoke(new ServicePrincipal('apigateway.amazonaws.com'));

**Comment by devendra-kumar1** [comment]
as a workaround i used below code to sort this issue.

 new CfnPermission(scope, 'ImportedLambdaPermission', {
            action: 'lambda:InvokeFunction',
            functionName: importedLambda.functionArn,
            principal: 'apigateway.amazonaws.com'
        })

**Comment by nija-at** [comment]
We support this use case starting from CDK version 1.75.0 - https://github.com/aws/aws-cdk/commit/715a0300ea44c7cfcb6ae9973bd4ca16585c8fa5.

You need to set the `sameEvironment` property.

**Comment by devendra-kumar1** [comment]
Thanks @nija-at . Will give a try and update the ticket accordingly

**Comment by devendra-kumar1** [comment]
@nija-at It is working fine  :)
