### ISSUE TITLE
(stepfunctions-tasks): containerOverrides environment - allow reference to JSON path

### ISSUE THREAD

**Issue by itzhapaz** [aws/aws-cdk#12289]
https://github.com/aws/aws-cdk/blob/31132caec4565735d2ccc32b43f078d634a5ca43/packages/%40aws-cdk/aws-stepfunctions-tasks/lib/batch/submit-job.ts#L288

If you need to read from another section in the JSON (for example input parameters), you need to add $ sign to the value but the rendering is only creating "Name": key, "Value": value. Need to allow to render as "Name": key, "Value.$": value in case of wanting to create a reference.

ref: https://docs.aws.amazon.com/step-functions/latest/dg/input-output-inputpath-params.html

For example:
Input JSON:
```
{
   "params": {
      "SOURCE_FILE": "/opt/src/myfile.txt"
   }
}
```

Needs the following in order to reference it in the ContainerOverrides
```
{
  "ContainerOverrides": {
    "Environment": [
      {
        "Name": "SOURCE_FILE",
         "Value.$": "$.params.SOURCE_FILE"
      }
    ]
  }
}
```

**Comment by NGL321** [comment]
Thank you for submitting this @itzhapaz!

We have gotten a request for this from an external source, so I am bumping this feature-request.

😸 😷
