### ISSUE TITLE
Queries on CDK,, passing parameters, Importing from CF Export etc.

### ISSUE THREAD

**Issue by vikrantsundriyal** [aws/aws-cdk#12281]
### The Question

Hi,
i want to get clarification on few queries regarding the use of cdk.
1) How can we pass input as Json with cdk deploy command. If i have many resources created using CDK (like serverless components) i want to pass deploy time configurations, adding --paramter for 20+ or 50+ params may not be wise. Looking for better approach.

2) am attaching a file where am using importfunction and parameters to pass / append few things dynamically. Pls assist whether its right approach,

```ts
import * as cdk from '@aws-cdk/core';
import * as appsync from '@aws-cdk/aws-appsync';
import * as lambda from '@aws-cdk/aws-lambda';

// lib/appsync-cdk-app-stack.ts
_**export class AppsyncCdkAppStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

// Assign values from input parameters
const Envname = new cdk.CfnParameter(this, "Env", {
  type: "String",
  description: "Name of the Environemnt for which GraphQL Api is to be provisioned"});**_

const ExpStack = new cdk.CfnParameter(this, "ExpStackName", {
  type: "String",
  description: "Name of the Stack Exported for Input"});

    // Creates the AppSync API
    const api = new appsync.GraphqlApi(this, 'Api', {
      name: cdk.Fn.join('-',['CsdCommon',Envname.valueAsString]),
      schema: appsync.Schema.fromAsset('graphql/schema.graphql'),
      authorizationConfig: {
        defaultAuthorization: {
          authorizationType: appsync.AuthorizationType.API_KEY,
          apiKeyConfig: {
            expires: cdk.Expiration.after(cdk.Duration.days(365))
          }
        },
      },
      xrayEnabled: true,
    });

// lib/appsync-cdk-app-stack.ts
const notesLambda = new lambda.Function(this, 'AppSyncNotesHandler', {
  functionName: cdk.Fn.join('-',['CsdResolver1',Envname.valueAsString]),
  runtime: lambda.Runtime.NODEJS_12_X,
  handler: 'main.handler',
  code: lambda.Code.fromAsset('lambda-fns'),
  memorySize: 1024,
  environment: {
          databaseName: cdk.Fn.importValue(cdk.Fn.join('',[ExpStack.valueAsString,'CsdSite']))
  }
});

// Set the new Lambda function as a data source for the AppSync API
const lambdaDs = api.addLambdaDataSource('lambdaDatasource', notesLambda);


    // Prints out the AppSync GraphQL endpoint to the terminal
    new cdk.CfnOutput(this, "GraphQLAPIURL", {
     value: api.graphqlUrl
    });

    // Prints out the AppSync GraphQL API key to the terminal
    new cdk.CfnOutput(this, "GraphQLAPIKey", {
      value: api.apiKey || ''
    });

    // Prints out the stack region to the terminal
    new cdk.CfnOutput(this, "Stack Region", {
      value: this.region
    });
  }
}
```

### Environment

  - **CDK CLI Version:** 
  - **Module Version:** 
  - **Node.js Version:** 
  - **OS:** 
  - **Language (Version):**

**Comment by NGL321** [comment]
Hey @vikrantsundriyal,

I'll try to tackle your questions separately:

1. There is not a baked-in method for importing large clusters of input parameters, however importing JSON in Typescript/Javascript is fairly straightforward. You can either use a `require` statement (but thats [not recommended](https://goenning.net/2016/04/14/stop-reading-json-files-with-require/)), or use the `fs` library. Then you can just use CDK [context](https://docs.aws.amazon.com/cdk/latest/guide/context.html) to select the file.
See here:

```ts
import { readFileSync } from 'fs';
import * as cdk from '@aws-cdk/core';

export class DemoStack extends cdk.Stack {
   constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
      super(scope, id, props);

      const inputFile = this.node.tryGetContext('infile');
      const data = readFileSync(inputFile);
      const json = JSON.parse(data.toString());

      ...

      const getData = json.TopLevel.SubLevel.data;
   }

}
```

then you run like so:

```bash
npx cdk synth -c infile='PATH'
```

2. I am not certain what you want to know here. Could you be more specific?

**Comment by vikrantsundriyal** [comment]
Hi Noah!
Thanks for your response above. Lemme conclude point1-> As mentioned above, there is no native CDK was of passing inputs to an app. However we may achieve this by going js way i.e using 'fs' file server library.
2) Providing additional details:
I wish to refer parameters exported by other stacks (Non CDK, like CloudFormation) inside my CDK app. For instance, i have a base infra repo where i create dynamodb resources (say Stack1). Few of my lambdas used as Appsync Datasource connect to Dynamodb, db name is passed as environment variable in lambda. In my AppSync CDK application i wish to pass those Dynamodb table name exported in  Stack1. Is cdk.Fn.importValue with export parameter name .valusAsString the right way??? NOTE: Above snippet is to handle dev/qa etc so i am passing Exported Stack as input param.
3) If i wish to dynamically provide couple of input parameters during cdk deploy, e.g in above snippet i use EnvName as parameters, "cdk.CfnParameter". And further use it as name: cdk.Fn.join('-',['CsdCommon',Envname.valueAsString]), do you think its right approach??

**Comment by NGL321** [comment]
Okay, I think I understand better what you are trying to accomplish.

In summary (correct me if I am wrong), you want to create a stack with deploy-time parameters. Some of these parameters will be derived from other, existing stacks (created with Cloudformation).
The JSON previously discussed was to import said parameters rather than passing them via `--parameters`, NOT context like I had mentioned.

If I am correct about all of the above, I think you may be a little stuck in the Cloudformation methodology. As mentioned [here](https://docs.aws.amazon.com/cdk/latest/guide/parameters.html) we advise __against__ using Cfn parameters as they are not available during synth time.

My suggestion in that case is to forego parameters altogether and just use a JSON configuration file passed through `--context`. It would be as follows:

## JSON File
```json
{
   "EnvironmentName": "XXXXX",
   "ExportedStackName": "XXXXXX"
}
```

## Stack
``` ts
import * as cdk from '@aws-cdk/core';
import * as appsync from '@aws-cdk/aws-appsync';
import * as lambda from '@aws-cdk/aws-lambda';
import { readFileSync } from 'fs';

// lib/appsync-cdk-app-stack.ts
export class AppsyncCdkAppStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    // Get file name from context and parse JSON
    const inputFile = this.node.tryGetContext('configfile');
    const context = JSON.parse(readFileSync(inputFile).toString());

    // Creates the AppSync API
    const api = new appsync.GraphqlApi(this, 'Api', {
        name: cdk.Fn.join('-',['CsdCommon',context.EnvironmentName]),
        schema: appsync.Schema.fromAsset('graphql/schema.graphql'),
        authorizationConfig: {
        defaultAuthorization: {
            authorizationType: appsync.AuthorizationType.API_KEY,
            apiKeyConfig: {
            expires: cdk.Expiration.after(cdk.Duration.days(365))
            }
        },
        },
        xrayEnabled: true,
    });

    // lib/appsync-cdk-app-stack.ts
    const notesLambda = new lambda.Function(this, 'AppSyncNotesHandler', {
    functionName: cdk.Fn.join('-',['CsdResolver1',context.EnvironmentName]),
    runtime: lambda.Runtime.NODEJS_12_X,
    handler: 'main.handler',
    code: lambda.Code.fromAsset('lambda-fns'),
    memorySize: 1024,
    environment: {
            databaseName: cdk.Fn.importValue(cdk.Fn.join('',
                [context.ExportedStackName,'CsdSite']
            ))
    }
});

    // Set the new Lambda function as a data source for the AppSync API
    const lambdaDs = api.addLambdaDataSource('lambdaDatasource', notesLambda);


        // Prints out the AppSync GraphQL endpoint to the terminal
        new cdk.CfnOutput(this, "GraphQLAPIURL", {
        value: api.graphqlUrl
        });

        // Prints out the AppSync GraphQL API key to the terminal
        new cdk.CfnOutput(this, "GraphQLAPIKey", {
        value: api.apiKey || ''
        });

        // Prints out the stack region to the terminal
        new cdk.CfnOutput(this, "Stack Region", {
        value: this.region
        });
    }
}
```

## Deploy Command
``` bash
npx cdk deploy -c configfile='~/config_file.json'
```


Let me know if this is what you were looking for!

😸 😷

**Comment by vikrantsundriyal** [comment]
Thanks !
Indeed this is close to what i was looking for. Even i was not convinced, and you rightly pointed, am trying to use CF way in CDK.
Will try your approach, looks straightforward. 

One last followup query, if I need to pass input parameters as properties for different resources of same type.. e.g i want to create 10 lambdas. In terraform i write one file inside module and call same with multiple inputs, how this can be done in CDK.
In my example memory size and say lambda names change for every lambda, rest remains same. Ideally i should not copy lambda block 10 times.
This is applicable for any other service where i need to create multiple resources of same type with minor changes. Instead of repeating the code, i should invoke same block multiple times. 
Can you please share the recommended way for this scenario.

**Comment by NGL321** [comment]
This is pretty straightforward, and you have already tackled the way I would configure it to begin with (JSON rather than hardcoded values).

```json
{
   "EnvironmentName": "XXXXX",
   "ExportedStackName": "XXXXXX",
   "Lambdas": [
      {
         "Name": "XXXXXX",
         "Handler": "XXXXXX",
         "AssetPath": "XXXXXXX"
      },
      {
         "Name": "YYYYYYYYY",
         "Handler": "YYYYYYYY",
         "AssetPath": "YYYYYYYYY"
      }
   ]
}
```

``` ts
...


let lambdas: Array<lambda.Function>;
context.Lambdas.forEach( ( lamContext ) => {
   lambdas.push(new lambda.Function(this, 'AppSyncNotesHandler', {
      functionName: cdk.Fn.join('-',[lamContext.Name,context.EnvironmentName]),
      runtime: lambda.Runtime.NODEJS_12_X,
      handler: lamContext.Handler,
      code: lambda.Code.fromAsset(lamContext.AssetPath),
      memorySize: 1024,
      environment: {
              databaseName: cdk.Fn.importValue(cdk.Fn.join('',
                  [context.ExportedStackName,'CsdSite']
              ))
      }
   });
});
```

**Comment by NGL321** [comment]
I'm going to close this issue as it has expanded beyond the initial context, but I hope all that helped!

😸 😷
