### ISSUE TITLE
(aws-autoscaling): Placement group with Autoscaling group

### ISSUE THREAD

**Issue by suyashdb** [aws/aws-cdk#12298]
## :question: General Issue

For autoscaling group, there doesn't seem to be any option to specify placement group and strategy. In our case, we need EC2 instances to be autoscaled within particular placement group. Documentation or source code doesnt point to information in this regard. 
### The Question

With above shortcoming i am not sure if there is already a feature and its a documentation issue. 

Can someone point me to way to use placement group within autoscaling ?
### Environment

  - **CDK CLI Version:** `1.81.0`
  - **Module Version:** @aws-cdk/aws-autoscaling@1.81.0
  - **Node.js Version:** v14.15.1
  - **OS:**  macOS Mojave 
  - **Language (Version):** TypeScript (3.8.3) ]

**Comment by NetaNir** [comment]
You are right, it is currently missing from the L2. You can use [escape hatches](https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html) to configure it.

**Comment by suyashdb** [comment]
Thanks @NetaNir !

escape latches doesnt seem to fit our use case.
I have autoscaling group already defined via cdk. we DONOT want to define complete AutoscalingGroup with CF construct in cdk, 
we just want to add unavailable parameter of placement group to already running cdk asg code. 

```
 var teradataDatabaseASG = new autoscaling.AutoScalingGroup(this, 'TeradataDBAsg', {
      vpc:vpc,
      instanceType: ec2.InstanceType.of(ec2.InstanceClass.M5, ec2.InstanceSize.XLARGE12),
      machineImage: ec2.MachineImage.lookup({
        name : "TeradataVantageEnterpriseASCC"
      }),
      vpcSubnets: {subnetGroupName: this.ascc.vpc.SubnetGroups.privateData},
      blockDevices: [
                {
                    deviceName: '/dev/xvda',
                    volume: autoscaling.BlockDeviceVolume.ebs(50, {encrypted:true, volumeType:autoscaling.EbsDeviceVolumeType.GP2})
                }
            ],
      allowAllOutbound: false,
      minCapacity: 1,
      maxCapacity: 2,
      securityGroup: tdSecurity,
    });
    
```

In this code already built resource how to add plaement group using esape latches. 
Can you please help how to code with above example/resource?

Thanks!

**Comment by NetaNir** [comment]
Escape hatches can be used to modify the higher level construct (the L2):

```ts
const asg = new autoscaling.AutoScalingGroup(...)
const cfnResource = asg.node.defaultChild as CfnAutoScalingGroup;
cfnResource.placementGroup = 'myPlacementGroup'
```

**Comment by suyashdb** [comment]
Thank you @NetaNir!

I tried the above way to add placement group but it doesnt seem to work. 

```
const viewpointASG = autoscaling builder ....
const cfnResourceViewpoint= viewpointASG.node.defaultChild as CfnAutoScalingGroup;
cfnResourceViewpoint.placementGroup =  'tdPlacementGroup';
```
so when i check on ec2 console, i don't see any placement group linked to my  viewpoint instance.

**Comment by NetaNir** [comment]
Do you see the value set in the synthesized template? (in the `cdk.out` folder)

**Comment by suyashdb** [comment]
@NetaNir 
well it does, but given i have no way to mention placement strategy in the escape hatch nor a way to use already built placement group, template just shows asg has placement group field but no value...

```
"tdviewpointASG": {
      "Type": "AWS::AutoScaling::AutoScalingGroup",
      "Properties": {
        "MaxSize": "1",
        "MinSize": "1",
        "AutoScalingGroupName": "td viewpoint asg",
        "LaunchConfigurationName": {
          "Ref": "tdviewpointASG"
        },
        "PlacementGroup": "tdPlacementGroup",
}
```
already prdefined Placement group looks like
```
"TDdbPlacementGroup": {
      "Type": "AWS::EC2::PlacementGroup",
      "Properties": {
        "Strategy": "cluster"
      },
      "Metadata": {
        "aws:cdk:path": "teradata-dev/TDdbPlacementGroup"
      }
 ```

**Comment by wdavjones** [comment]
I'm guessing you need to create a PlacementGroup resource first:
```typescript
const placementGroup = new ec2.CfnPlacementGroup(this, 'PlacementGroup', {
    strategy: 'cluster',
});
```

Then, use `.ref` to reference your placement group:

```typescript
const cfnAutoScalingGroup = asg.node.defaultChild as asg.CfnAutoScalingGroup;
cfnAutoScalingGroup.placementGroup = placementGroup.ref;
```

Also, you probably need to set the AZ in the ASG Subnet Selection (if you are trying to limit to one AZ):
```typescript
vpcSubnets: {
    subnetGroupName: this.ascc.vpc.SubnetGroups.privateData
    subnetFilters: [
        ec2.SubnetFilter.availabilityZones(['us-east-1a]) // set AZ here
    ]
},
```
