### ISSUE TITLE
(aws-rds): Broken link to Serverless docs in README

### ISSUE THREAD

**Issue by douglasnaphas** [aws/aws-cdk#12308]
The link to the [Aurora Serverless docs](https://aws.amazon.com/rds/aurora/serverless/) in the [README](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-rds-readme.html#serverless) has a typo, an extra set of parentheses around the URL.

---

This is a 📕 documentation issue

**Comment by skinny85** [comment]
This was fixed in https://github.com/aws/aws-cdk/pull/12309.
