### ISSUE TITLE
Invalid request provided: AWS::ElasticLoadBalancingV2::Listener Validation exception

### ISSUE THREAD

**Issue by atulmjoshi** [aws/aws-cdk#12327]
### The Question

I am trying to create 3 simple resources - 1) Application Load Balancer 2) Target Group with no registered targets (yet) 3) Listener which connects ALB to the Target Group.  CDK (CloudFormation) always fails while creating a Listener. I am able to create ALB and TargetGroup through CDK and then manually (Console) be able to add Listener, but not through CDK/CF. Synth works well and creates proper output.

Here is my CDK code.

from aws_cdk import (
    aws_ec2 as ec2,
    aws_ecs as ecs,
    aws_ecs_patterns as ecs_patterns,
    core,
    aws_iam as iam,
    aws_elasticloadbalancingv2 as elb
)

class MyInfraStack_lb_li_tg(core.Stack):

    def __init__(self, scope: core.Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        # The code that defines your stack goes here
        vpnVPC = ec2.Vpc.from_lookup(self, "vpn-vpc", vpc_name="myvpc")
        #
        tr=iam.Role.from_role_arn(self, 'Role', 'arn:aws:iam::111111111111:role/service-role/ecsTaskExecutionRole')        
        #
        ss=ec2.SubnetSelection(subnets=[ec2.Subnet.from_subnet_id(self,'privatesubnet1','subnet-111b1111'),
                                        ec2.Subnet.from_subnet_id(self,'privatesubnet2','subnet-11cf11111')])        
        #
        lb1 = elb.ApplicationLoadBalancer(self,'my-app-lb',
                                    internet_facing=False,
                                    vpc=vpnVPC,
                                    vpc_subnets=ss,
                                    http2_enabled=True, 
                                    ip_address_type=elb.IpAddressType.IPV4,
                                    load_balancer_name='my-app-lb',
                                    security_group=None)
        #
        tg1 = elb.ApplicationTargetGroup(self,'my-app-tg',
                                            port=8080,
                                            vpc=vpnVPC,
                                            target_type=elb.TargetType.IP,
                                            target_group_name='my-app-tg')
        #
        lb1.add_listener('my-app-li',
                        port=80, 
                        default_action=elb.ListenerAction.forward(target_groups=[tg1]))

**Error**
1/10 | 9:53:39 AM | CREATE_FAILED        | AWS::ElasticLoadBalancingV2::Listener       | my-app-lb/my-app-li (MyapplbITroadmapappliFBC0409A) Invalid request provided: AWS::ElasticLoadBalancingV2::Listener Validation exception
	new BaseListener (/tmp/jsii-kernel-Bs02kl/node_modules/@aws-cdk/aws-elasticloadbalancingv2/lib/shared/base-listener.js:17:26)
	\_ new ApplicationListener (/tmp/jsii-kernel-Bs02kl/node_modules/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-listener.js:29:9)
	\_ LookedUpApplicationLoadBalancer.addListener (/tmp/jsii-kernel-Bs02kl/node_modules/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-load-balancer.js:448:16)
	\_ /myagent/_work/12/s/roadmap-infra/.venv/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:3380:51
	\_ Kernel._wrapSandboxCode (/myagent/_work/12/s/roadmap-infra/.venv/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:4040:16)
	\_ /myagent/_work/12/s/roadmap-infra/.venv/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:3380:25
	\_ Kernel._ensureSync (/myagent/_work/12/s/roadmap-infra/.venv/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:4017:20)
	\_ Kernel.invoke (/myagent/_work/12/s/roadmap-infra/.venv/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:3379:26)
	\_ KernelHost.processRequest (/myagent/_work/12/s/roadmap-infra/.venv/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:13119:28)
	\_ KernelHost.run (/myagent/_work/12/s/roadmap-infra/.venv/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:13057:14)
	\_ Immediate._onImmediate (/myagent/_work/12/s/roadmap-infra/.venv/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:13060:37)
	\_ processImmediate (internal/timers.js:461:21)

### Environment

aws-cdk=1.80.0,@aws-cdk/assets=1.74.0,@aws-cdk/aws-apigateway=1.74.0,@aws-cdk/aws-apigatewayv2=1.74.0,@aws-cdk/aws-applicationautoscaling=1.74.0,@aws-cdk/aws-autoscaling=1.74.0,@aws-cdk/aws-autoscaling-common=1.74.0,@aws-cdk/aws-autoscaling-hooktargets=1.74.0,@aws-cdk/aws-batch=1.74.0,@aws-cdk/aws-certificatemanager=1.74.0,@aws-cdk/aws-cloudformation=1.74.0,@aws-cdk/aws-cloudfront=1.74.0,@aws-cdk/aws-cloudwatch=1.74.0,@aws-cdk/aws-codebuild=1.74.0,@aws-cdk/aws-codecommit=1.74.0,@aws-cdk/aws-codeguruprofiler=1.74.0,@aws-cdk/aws-codepipeline=1.74.0,@aws-cdk/aws-cognito=1.74.0,@aws-cdk/aws-ec2=1.74.0,@aws-cdk/aws-ecr=1.74.0,@aws-cdk/aws-ecr-assets=1.74.0,@aws-cdk/aws-ecs=1.74.0,@aws-cdk/aws-ecs-patterns=1.74.0,@aws-cdk/aws-efs=1.74.0,@aws-cdk/aws-elasticloadbalancing=1.74.0,@aws-cdk/aws-elasticloadbalancingv2=1.74.0,@aws-cdk/aws-events=1.74.0,@aws-cdk/aws-events-targets=1.74.0,@aws-cdk/aws-iam=1.74.0,@aws-cdk/aws-kinesis=1.74.0,@aws-cdk/aws-kinesisfirehose=1.74.0,@aws-cdk/aws-kms=1.74.0,@aws-cdk/aws-lambda=1.74.0,@aws-cdk/aws-logs=1.74.0,@aws-cdk/aws-route53=1.74.0,@aws-cdk/aws-route53-targets=1.74.0,@aws-cdk/aws-s3=1.74.0,@aws-cdk/aws-s3-assets=1.74.0,@aws-cdk/aws-sam=1.74.0,@aws-cdk/aws-secretsmanager=1.74.0,@aws-cdk/aws-servicediscovery=1.74.0,@aws-cdk/aws-sns=1.74.0,@aws-cdk/aws-sns-subscriptions=1.74.0,@aws-cdk/aws-sqs=1.74.0,@aws-cdk/aws-ssm=1.74.0,@aws-cdk/aws-stepfunctions=1.74.0,@aws-cdk/cloud-assembly-schema=1.74.0,@aws-cdk/core=1.74.0,@aws-cdk/custom-resources=1.74.0,@aws-cdk/cx-api=1.74.0,@aws-cdk/region-info=1.74.0,jsii-runtime=Python/3.7.6

**Comment by atulmjoshi** [comment]
Resulting JSON
{
  "Resources": {
    "ITroadmapapplb7C8E17F6": {
      "Type": "AWS::ElasticLoadBalancingV2::LoadBalancer",
      "Properties": {
        "IpAddressType": "ipv4",
        "LoadBalancerAttributes": [
          {
            "Key": "deletion_protection.enabled",
            "Value": "false"
          }
        ],
        "Name": "my-app-lb",
        "Scheme": "internal",
        "SecurityGroups": [
          {
            "Fn::GetAtt": [
              "ITroadmapapplbSecurityGroupE3690BD7",
              "GroupId"
            ]
          }
        ],
        "Subnets": [
          "subnet-11111111",
          "subnet-22222222"
        ],
        "Type": "application"
      },
      "Metadata": {
        "aws:cdk:path": "my-infra-lb-li-tg/my-app-lb/Resource"
      }
    },
    "ITroadmapapplbSecurityGroupE3690BD7": {
      "Type": "AWS::EC2::SecurityGroup",
      "Properties": {
        "GroupDescription": "Automatically created Security Group for ELB ITArchroadmapinfralblitgITroadmapapplb22B72F9C",
        "SecurityGroupEgress": [
          {
            "CidrIp": "255.255.255.255/32",
            "Description": "Disallow all traffic",
            "FromPort": 252,
            "IpProtocol": "icmp",
            "ToPort": 86
          }
        ],
        "SecurityGroupIngress": [
          {
            "CidrIp": "0.0.0.0/0",
            "Description": "Allow from anyone on port 80",
            "FromPort": 80,
            "IpProtocol": "tcp",
            "ToPort": 80
          }
        ],
        "VpcId": "vpc-1111111"
      },
      "Metadata": {
        "aws:cdk:path": "my-infra-lb-li-tg/my-app-lb/SecurityGroup/Resource"
      }
    },
    "ITroadmapapplbITroadmapappliFBC0409A": {
      "Type": "AWS::ElasticLoadBalancingV2::Listener",
      "Properties": {
        "DefaultActions": [
          {
            "TargetGroupArn": {
              "Ref": "ITroadmapapptg1AB5D958"
            },
            "Type": "forward"
          }
        ],
        "LoadBalancerArn": {
          "Ref": "ITroadmapapplb7C8E17F6"
        },
        "Port": 80,
        "Protocol": "HTTP"
      },
      "Metadata": {
        "aws:cdk:path": "my-infra-lb-li-tg/my-app-lb/my-app-li/Resource"
      }
    },
    "ITroadmapapptg1AB5D958": {
      "Type": "AWS::ElasticLoadBalancingV2::TargetGroup",
      "Properties": {
        "Name": "my-app-tg",
        "Port": 8080,
        "Protocol": "HTTP",
        "TargetType": "ip",
        "VpcId": "vpc-1111111"
      },
      "Metadata": {
        "aws:cdk:path": "my-infra-lb-li-tg/my-app-tg/Resource"
      }
    },
    "CDKMetadata": {
      "Type": "AWS::CDK::Metadata",
      "Properties": {
        "Modules": "aws-cdk=1.80.0,@aws-cdk/assets=1.74.0,@aws-cdk/aws-apigateway=1.74.0,@aws-cdk/aws-apigatewayv2=1.74.0,@aws-cdk/aws-applicationautoscaling=1.74.0,@aws-cdk/aws-autoscaling=1.74.0,@aws-cdk/aws-autoscaling-common=1.74.0,@aws-cdk/aws-autoscaling-hooktargets=1.74.0,@aws-cdk/aws-batch=1.74.0,@aws-cdk/aws-certificatemanager=1.74.0,@aws-cdk/aws-cloudformation=1.74.0,@aws-cdk/aws-cloudfront=1.74.0,@aws-cdk/aws-cloudwatch=1.74.0,@aws-cdk/aws-codebuild=1.74.0,@aws-cdk/aws-codecommit=1.74.0,@aws-cdk/aws-codeguruprofiler=1.74.0,@aws-cdk/aws-codepipeline=1.74.0,@aws-cdk/aws-cognito=1.74.0,@aws-cdk/aws-ec2=1.74.0,@aws-cdk/aws-ecr=1.74.0,@aws-cdk/aws-ecr-assets=1.74.0,@aws-cdk/aws-ecs=1.74.0,@aws-cdk/aws-ecs-patterns=1.74.0,@aws-cdk/aws-efs=1.74.0,@aws-cdk/aws-elasticloadbalancing=1.74.0,@aws-cdk/aws-elasticloadbalancingv2=1.74.0,@aws-cdk/aws-events=1.74.0,@aws-cdk/aws-events-targets=1.74.0,@aws-cdk/aws-iam=1.74.0,@aws-cdk/aws-kinesis=1.74.0,@aws-cdk/aws-kinesisfirehose=1.74.0,@aws-cdk/aws-kms=1.74.0,@aws-cdk/aws-lambda=1.74.0,@aws-cdk/aws-logs=1.74.0,@aws-cdk/aws-route53=1.74.0,@aws-cdk/aws-route53-targets=1.74.0,@aws-cdk/aws-s3=1.74.0,@aws-cdk/aws-s3-assets=1.74.0,@aws-cdk/aws-sam=1.74.0,@aws-cdk/aws-secretsmanager=1.74.0,@aws-cdk/aws-servicediscovery=1.74.0,@aws-cdk/aws-sns=1.74.0,@aws-cdk/aws-sns-subscriptions=1.74.0,@aws-cdk/aws-sqs=1.74.0,@aws-cdk/aws-ssm=1.74.0,@aws-cdk/aws-stepfunctions=1.74.0,@aws-cdk/cloud-assembly-schema=1.74.0,@aws-cdk/core=1.74.0,@aws-cdk/custom-resources=1.74.0,@aws-cdk/cx-api=1.74.0,@aws-cdk/region-info=1.74.0,jsii-runtime=Python/3.7.6"
      },
      "Metadata": {
        "aws:cdk:path": "my-infra-lb-li-tg/CDKMetadata/Default"
      }
    }
  }
}

**Comment by meghnaparsan** [comment]
I also have the same issue. 

Code Snippet


        load_balancer = aws_elasticloadbalancingv2.CfnLoadBalancer (
            self,
            "Test-Loadbalancer",
            ip_address_type = "ipv4",
            name = "Test-LoadBalancer",
            scheme = "internal",
            security_groups = ["sg-XXX"],
            subnets = ["subnet-XXX", "subnet-XXX"],
            type = "application"
        )

        # Target Group
        target_group_resource = aws_elasticloadbalancingv2.CfnTargetGroup (
            self,
            "Test-TargetGroup",
            health_check_enabled = True,
            health_check_interval_seconds = 10,
            health_check_port = "traffic-port",
            health_check_protocol = "HTTP",
            health_check_path = "/health",
            health_check_timeout_seconds = 5,
            healthy_threshold_count = 2,
            name = "Test-TargetGroup",
            port = 80,
            protocol = "HTTP",
            target_type = "ip",
            unhealthy_threshold_count = 2,
            targets = [
                aws_elasticloadbalancingv2.CfnTargetGroup.TargetDescriptionProperty (
                    id = "XXX",
                    port = 80
                )
            ],
            vpc_id = "vpc-XXX"
        )

        # Listener 
        listener_prop = aws_elasticloadbalancingv2.CfnListener (
            self,
            "Test-Listener",
            default_actions = [
                aws_elasticloadbalancingv2.CfnListener.ActionProperty (
                    target_group_arn = target_group_resource.ref,
                    type = 'forward'
                )
            ],
            load_balancer_arn = load_balancer.ref,
            protocol = "HTTP"
        )

**Comment by meghnaparsan** [comment]
I also have the same issue.

My Code:

`load_balancer = aws_elasticloadbalancingv2.CfnLoadBalancer (
            self,
            "Test-Loadbalancer",
            ip_address_type = "ipv4",
            name = "Test-LoadBalancer",
            scheme = "internal",
            security_groups = ["sg-XXX"],
            subnets = ["subnet-XXX", "subnet-XXX"],
            type = "application"
        )

        # Target Group
        target_group_resource = aws_elasticloadbalancingv2.CfnTargetGroup (
            self,
            "Test-TargetGroup",
            health_check_enabled = True,
            health_check_interval_seconds = 10,
            health_check_port = "traffic-port",
            health_check_protocol = "HTTP",
            health_check_path = "/health",
            health_check_timeout_seconds = 5,
            healthy_threshold_count = 2,
            name = "Test-TargetGroup",
            port = 80,
            protocol = "HTTP",
            target_type = "ip",
            unhealthy_threshold_count = 2,
            targets = [
                aws_elasticloadbalancingv2.CfnTargetGroup.TargetDescriptionProperty (
                    id = "XX",
                    port = 80
                )
            ],
            vpc_id = "vpc-XXX"
        )

        # Listener 
        listener_prop = aws_elasticloadbalancingv2.CfnListener (
            self,
            "Test-Listener",
            default_actions = [
                aws_elasticloadbalancingv2.CfnListener.ActionProperty (
                    target_group_arn = target_group_resource.ref,
                    type = 'forward'
                )
            ],
            load_balancer_arn = load_balancer.ref,
            protocol = "HTTP"
        )`

**Comment by meghnaparsan** [comment]
I also have the same issue. I'm able to add Listener from Console, but not through CDK.

My Code:

        load_balancer = aws_elasticloadbalancingv2.CfnLoadBalancer (
            self,
            "Test-Loadbalancer",
            ip_address_type = "ipv4",
            name = "Test-LoadBalancer",
            scheme = "internal",
            security_groups = ["sg-XXX"],
            subnets = ["subnet-XXX", "subnet-XXX"],
            type = "application"
        )

        # Target Group
        target_group_resource = aws_elasticloadbalancingv2.CfnTargetGroup (
            self,
            "Test-TargetGroup",
            health_check_enabled = True,
            health_check_interval_seconds = 10,
            health_check_port = "traffic-port",
            health_check_protocol = "HTTP",
            health_check_path = "/health",
            health_check_timeout_seconds = 5,
            healthy_threshold_count = 2,
            name = "Test-TargetGroup",
            port = 80,
            protocol = "HTTP",
            target_type = "ip",
            unhealthy_threshold_count = 2,
            targets = [
                aws_elasticloadbalancingv2.CfnTargetGroup.TargetDescriptionProperty (
                    id = "XXX",
                    port = 80
                )
            ],
            vpc_id = "vpc-XXX"
        )

        # Listener 
        listener_prop = aws_elasticloadbalancingv2.CfnListener (
            self,
            "Test-Listener",
            default_actions = [
                aws_elasticloadbalancingv2.CfnListener.ActionProperty (
                    target_group_arn = target_group_resource.ref,
                    type = 'forward'
                )
            ],
            load_balancer_arn = load_balancer.ref,
            protocol = "HTTP"
        )

**Comment by escarbor** [comment]
Running into the same issue. I have a CDK project that used to work, but now throws: 
`Invalid request provided: AWS::ElasticLoadBalancingV2::Listener Validation exception` with no indication as to what is the underlying issue, or what changed.

**Comment by atulmjoshi** [comment]
Open a ticket with AWS. I just realised that the stack was successfully created in another account. Not sure about the root cause though. Update here if you able to investigate.

**Comment by ragebiswas** [comment]
Did you find out a reason? I'm seeing the exact same problem.

**Comment by meghnaparsan** [comment]
No. I did not come across any solution yet.

**Comment by ragebiswas** [comment]
Okay, never mind. For my case, it was due to a silly reason. I was creating my stack via AWS CDK, and I had a space in the ACM certificate I had attached to the listener.

**Comment by escarbor** [comment]
@ragebiswas I made a similar mistake using an ACM cert (a simple typo). Since the validation error message is broad, going through the request/creation structure line by line and tracing any dependencies would now be my first step. That was a painful one.

**Comment by atulmjoshi** [comment]
In my case its simple port 80 HTTP listener, still facing issue in one account. Generated script is valid and works in different account.

**Comment by atulmjoshi** [comment]
For my problem I got the solution - updating in case it help others.
It was issue with the permission - the agent where my task is running haven't had CreateListener permission. Having said that - it is very unusual for cloudformation to spit out message like "invalid request". For all resources CF does give error indicating "not authorized to perform action". This is very misleading for Listener entity. Request AWS to take a note.

**Comment by esperecyan** [comment]
`Invalid request provided: AWS::ElasticLoadBalancingV2::ListenerRule Validation exception` occurred when the value of `Values` was set to 6 or more in the `PathPatternConfig` of `Conditions`.
https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-limits.html

**Comment by erosen03** [comment]
Why is this issue closed? Many people receive this vague error message with the cause being a permissions issue. The error message needs to be correction to return the actual permissions error, such as:
> Resource handler returned message: "Invalid request provided: User: arn:aws:sts::---:assumed-role/---/AWSCloudFormation is not authorized to perform: elasticloadbalancing:CreateRule on resource: arn:aws:ssm:us-east-1:---:listener-rule/--- because no identity-based policy allows the elasticloadbalancing:CreateRule action ...

That's the typical error message one would receive and for a permissions issue.

**Comment by sammcj** [comment]
This is a really vague error message and a great example of the painfully opaque nature of CDK.

**Comment by rthadr** [comment]
@esperecyan  Thank you! I was passing in a list of values for IP ranges and this was the cause.
