### ISSUE TITLE
monocdk: instructions on importing 'core' don't work

### ISSUE THREAD

**Issue by kjpgit** [aws/aws-cdk#12335]
### Reproduction Steps

import { core } from 'monocdk';

bin/codebuild2.ts(3,10): error TS2305: Module '"../node_modules/monocdk/lib"' has no exported member 'core'.

docs: https://www.npmjs.com/package/monocdk

#### Expected Behavior

It would be nice to have a "cdk" or "core" export.  Instead, my workaround is to:

import { Construct, Stack, StackProps } from 'monocdk'

Which I find a lot uglier.

**Comment by NetaNir** [comment]
Note that `monocdk` is an experimental module, not intended for consumption, it was mainly released for internal needs.
There is no core package anymore, all core types have been hoisted to the root, you can use `as cdk`:

```
import * as cdk from monocdk
```
