### ISSUE TITLE
(aws-lambda-event-sources): MaximumBatchingWindowInSeconds for SQS eventsources

### ISSUE THREAD

**Issue by jacques-** [aws/aws-cdk#12339]
Essentially the request is to implement new MaximumBatchingWindowInSeconds support for SQS as described here: https://aws.amazon.com/about-aws/whats-new/2020/11/aws-lambda-now-supports-batch-windows-of-up-to-5-minutes-for-functions/

It seems like the underlying bits already exist in here: https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-lambda.EventSourceMapping.html#maxbatchingwindow

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by wmakeev** [comment]
Is where any workaround to set MaximumBatchingWindowInSeconds in current version?

**Comment by KoStard** [comment]
Is there any update on this? Thanks!

**Comment by shellscape** [comment]
https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-lambda-event-sources.SqsEventSourceProps.html#maxbatchingwindow

Not sure I understand the nature of the issue. Here's what we're doing:

```ts
    const eventOptions: SqsEventSourceProps = {
      batchSize,
      maxBatchingWindow = Duration.seconds(10),
      reportBatchItemFailures: true
    };

    if (batchSize > 10)
      (eventOptions as any).(maxBatchingWindowSeconds);
```

**Comment by madeline-k** [comment]
Thanks @shellscape, it looks like this feature request is already supported. If not, or if there is still a feature gap, please open a new issue.
