### ISSUE TITLE
(aws-iam): User does not have a fromAttributes or fromArn method

### ISSUE THREAD

**Issue by richardhboyd** [aws/aws-cdk#12340]
The current iteration of IAM User in CDK does not allow customers to build a representation of an IAM user in a separate account with the `from...()` methonds. 

### Reproduction Steps

For example, suppose you wanted to authorize an IAM User in AccountB to pull Images from an ECR Repository in AccountA. Typically this would be done by adding a principal `arn:aws:iam::AccountB-id:user/MyUser` to the ECR Repository Policy. But, since the StatementProps expects an IPrincipal, of which User is one, I can only build IAM Users that reference the current account.

### What did you expect to happen?

```typescript
const myUser = new iam.User.fromAttributes({arn: 'arn:aws:iam::AccountB-id:user/MyUser'});
```
Should return a valid IAM User.

### What actually happened?

Method does not exist and I spent the afternoon crying.

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
In this particular case, just saying "any old principal (regardless of its type) with this ARN" probab§ly would have worked:

```
new iam.ArnPrincipal('arn:aws:iam::AccountB-id:user/MyUser');
```

 But I agree the lack of the method is confusing.

**Comment by rrhodes** [comment]
Hi @rix0rrr, @richardhboyd, I've taken a look into this. PR coming up shortly for review.
