### ISSUE TITLE
CDK- How to pass values in the IFunction Type parameter

### ISSUE THREAD

**Issue by vikrantsundriyal** [aws/aws-cdk#12342]
## :question: General Issue
CDK- How to pass values in the IFunction Type parameter

### The Question

Hi,
I want  to know how i can pass a Function ARN or name in a method which expects iFunction.
eg:
Below is the snippet:

```ts
const notesLambda = new lambda.Function(this, 'AppSyncNotesHandler', {
  functionName: cdk.Fn.join('-',['CsdResolver1',context.EnvironmentName]),
  runtime: lambda.Runtime.NODEJS_12_X,
  handler: 'main.handler',
  code: lambda.Code.fromAsset('lambda-fns'),
  memorySize: 1024,
  environment: {
          databaseName: cdk.Fn.importValue(cdk.Fn.join('',
                [context.ExportedStackName,'CsdSite']
                                                      ))
  }
});

const lambdaDs = api.addLambdaDataSource('lambdaDatasource', notesLambda);
```
This works.

Whereas if i want to use ARN of a lambda which is already created i get and error:

```
----AWS CDK Type 'string' is not assignable to type 'IFunction'.---
```

```ts
const lambdaDs = api.addLambdaDataSource('lambdaDatasource',  'arn:aws:lambda:us-east-1:108970575545:function:Function1Hello-qa');
```
I beleive its a trivial error where the way am passing values is wrong. Can you please help.

[2]: http://xyproblem.info
-->

### Environment

  - **CDK CLI Version:** 
  - **Module Version:** 
  - **Node.js Version:** 
  - **OS:** 
  - **Language (Version):**

**Comment by skinny85** [comment]
Hey @vikrantsundriyal ,

you can create an `IFunction` from an ARN using the `Function.fromFunctionArn()` method:

```ts
const existingLambda: lambda.IFunction = lambda.Function.fromFunctionArn(this, 'Function',
  'arn:aws:lambda:us-east-1:108970575545:function:Function1Hello-qa');
```

Thanks,
Adam
