### ISSUE TITLE
(aws-ec2): AmazonLinuxImage: add option to remember selected AMI in context for stateful instances

### ISSUE THREAD

**Issue by felipepulpo** [aws/aws-cdk#12355]
The ec2 instance was recreated when I made a deployment where only the cdk version was updated.

### Reproduction Steps
- update the CDK version from 1.78 to 1.82
- deploy cdk

### What did you expect to happen?
The ec2 instance (and any other resource) stays running

### What actually happened?
The ec2 instance was removed and recreated

### Environment

  - **CDK CLI Version  : 1.77**
  - **Framework Version: 1.82**
  - **Node.js Version:** 10.18.1
  - **OS               :**
  - **Language (Version):**  TypeScript (3.8.3)

### Other

--- 

This is :bug: Bug Report

**Comment by felipeloha** [comment]
Any news? This is costing us loads of efforts as we have to setup the server every time it gets recreated. 
How does cdk decides if an instance must be recreated? The behavior is totally random

**Comment by felipeloha** [comment]
the following screenshots show the resources I have in the stack and the recreation event logs. we just added a new s3 bucket which was in no way connected to the ec2 instance.

![image](https://user-images.githubusercontent.com/36071293/106357671-ce2e6500-6307-11eb-8b5c-4840f4f26a3c.png)

![image](https://user-images.githubusercontent.com/36071293/106357673-d25a8280-6307-11eb-8af0-6fb9baa32ed1.png)

**Comment by felipeloha** [comment]
I found the problem.
We were getting the AMI ID as
    const machineImage = new ec2.AmazonLinuxImage({
        generation: ec2.AmazonLinuxGeneration.AMAZON_LINUX_2,
        edition: ec2.AmazonLinuxEdition.STANDARD,
        virtualization: ec2.AmazonLinuxVirt.HVM,
        storage: ec2.AmazonLinuxStorage.GENERAL_PURPOSE,
    });

which is not stable.

sorry for the inconvenience.

**Comment by rix0rrr** [comment]
As the doc page says: 

> This Machine Image automatically updates to the latest version on every deployment. Be aware this will cause your instances to be replaced when a new version of the image becomes available. Do not store stateful information on the instance if you are using this image.

https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ec2.AmazonLinuxImage.html

It's most clear if you use the `MachineImage.fromXxx()` factory functions:

https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ec2.MachineImage.html

You probably want to use `MachineImage.lookup()`.

Nevertheless, we could add a feature to these images to *remember* the value of the SSM parameter that's being retrieved (by using an SSM context lookup). This would require you to commit `cdk.context.json`, but should be easy enough to add by adding a `rememberValue?: boolean` property.

**Comment by rix0rrr** [comment]
Also, as a general practice I would recommend you move away from either stateful or manually-installed instances. Try using https://docs.aws.amazon.com/cdk/api/latest/docs/aws-ec2-readme.html#configuring-instances-using-cloudformation-init-cfn-init to configure your instance at bootup time.

**Comment by felipeloha** [comment]
thanks for the recommendation. we do that so far we can but there are some things that cannot be done in those scripts. for example generating certificates, creating database users to avoid using root users, creating application configuration and and the very end deploy the software which is running.

anyway if the instance would boot all its own it would be around 5 minutes down which for some software is a long time.
