### ISSUE TITLE
(codebuild): trigger "release change" after a codebuild.Project finishes successfully

### ISSUE THREAD

**Issue by erudisch** [aws/aws-cdk#12358]
### The Question
Is it possible to trigger "release change" of `codesuite/codepipeline/pipelines/<pipeline>` after a `codebuild.Project` finishes successfully?

I have a `codebuild.Project` that updates my docker images in `ecr` periodically. After it finishes successfully I want to run the pipeline to use the updated docker images in the deployed application.

### Environment

  - **CDK CLI Version:** 1.82.0
  - **Module Version:** 1.82.0
  - **Node.js Version:** v13.8.0
  - **OS:** MacOS 11.1
  - **Language (Version):** TypeScript (4.1.3)

**Comment by skinny85** [comment]
@erudisch absolutely!

```ts
import * as events_targets from '@aws-cdk/aws-events-targets';

// project is an IProject
// pipeline is an IPipeline
project.onBuildSucceeded('StartPipeline', {
  target: new events_targets.CodePipeline(pipeline),
});
```

Thanks,
Adam

**Comment by erudisch** [comment]
@skinny85 thank you very much!

In case one is using a `pipelines.CdkPipeline` `onBuildSucceeded` can be triggered like this:

```
import * as pipelines from '@aws-cdk/pipelines';
import * as events_targets from '@aws-cdk/aws-events-targets';

const cdkPipeline = new pipelines.CdkPipeline(this, 'Cdk-Pipeline', {
    pipelineName: 'CdkPipeline',
    cloudAssemblyArtifact,
    sourceAction: sourceAction,
    synthAction: synthAction,
});

project.onBuildSucceeded('StartPipeline', {
  target: new events_targets.CodePipeline(cdkPipeline.codePipeline),
});
```
