### ISSUE TITLE
(aws-iam): implement policydocument statement sorting by sid when present

### ISSUE THREAD

**Issue by apmclean** [aws/aws-cdk#12357]
When programmatically constructing an IAM policy statement the statement entries may arrive in different orders with each execution or synthesis.  Currently the `render()` method of the `policy-document` treats the order that `addStatements()` was called in as absolute.  

Within an IAM policy the order within the `Statement: []` array of objects has no bearing on the implemented permissions.  ie: the following are identical from an IAM permission perspective:
`Statement: [a, b, c]` 
`Statement: [b, a, c]` 
`Statement: [c, b, a]` 

On first deployment a stack may synthesize as [a, b, c].  On second deployment it may synthesize as [c, b, a] and so on.  This will deploy a change even though the functional intention behind the stack is identical.

### Use Case

When creating an S3 bucket policy that restricts access to certain assumed Roles, it requires the use of the `aws:userId` conditional.  When under an assumed role it is best to use the resolved AROA role unique identifier since the resolved role arn can include suffixes which will fail to match a Principal string.  Resolving the AROA requires an SDK call in advance to DescribeRole to resolve it.  

Where this is done programmatically within the construct it may resolve / construct the policy `Statements: []` in different orders.  To aid in resolution speed I'm resolving these with a Promise.all() approach versus synchronously so my order isn't guaranteed.

### Proposed Solution

I am proposing to modify the `render()` method in [policy-document.ts](https://github.com/aws/aws-cdk/blob/v1.82.0/packages/@aws-cdk/aws-iam/lib/policy-document.ts#L143) to sort the `this.statements` array by `Sid` when a 'Sid' is present.  This will assure the order of the `Statement: []` will synth the same way every time.  Sorting by Sid can also aid in readability for humans reading the policies.  Could alternately generate a hash of each statement and use that to sort as well.

Functionally I would like the synthesized template to be identical every time since the functional intention within IAM is identical.

### Other

You can use this to reproduce the jist of the issue:

```typescript
import * as cdk from '@aws-cdk/core';
import * as iam from '@aws-cdk/aws-iam';

export class CdkIamStatementsStack extends cdk.Stack {
    constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
        super(scope, id, props);

        let Statements: Array<iam.PolicyStatement> = [
            new iam.PolicyStatement({
                sid: "StatementOne",
                effect: iam.Effect.ALLOW,
                resources: ["*"],
                actions: ["s3:*"]
            }),
            new iam.PolicyStatement({
                sid: "StatementTwo",
                effect: iam.Effect.ALLOW,
                resources: ["*"],
                actions: ["ec2:*"]
            })
        ]
        
        // Simulate different ordering of the statements
        Statements = Statements.sort(() => Math.random() - 0.5)

        const PolicyDocument = new iam.PolicyDocument()

        PolicyDocument.addStatements(Statements[0], Statements[1])

        new iam.ManagedPolicy(this, 'ManagedPolicy', {
            document: PolicyDocument
        })
    }
}
```

Deploy this template, then run a few 'cdk diff's.  You'll find an update is triggered occasionally when the statement order changes.

[ * ] :wave: I may be able to implement this feature request

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
I am not against this, but surprised that randomized ordering would happen.

As far as I am aware, it shouldn't.

```
        // Simulate different ordering of the statements
        Statements = Statements.sort(() => Math.random() - 0.5)
```

Well yes obviously :). But how does this happen in real situations?

**Comment by apmclean** [comment]
In my scenario I used a helper that would generate statements for me that had conditionals against resolved RoleIds.  The resolution of a Role Arn to RoleID was handled using a promise.all() so it could arrive in any order.  So the helper class returned the statement fragments to go into the policy in 'resolved' order which changed now and then forcing a re-deploy of the stack.

I have since retooled with a different approach, but that was the scenario I was working under! :)

**Comment by Jacco** [comment]
Note: might be hard to sort in cdk rendering in case of intrinsics being used for the sids? (or is that already forbidden)

I think actually the AWS backend should have an equality checker for the documents that is insensitive to different sortings of the same values (with or without sid).
