### ISSUE TITLE
npm ci fails on trying to chmod bin/cdk

### ISSUE THREAD

**Issue by dirkgomez** [aws/aws-cdk#12354]
I use containers in my CI/CD pipeline that have specific versions of CDK globally preinstalled. When running npm ci I get this error

```
$ npm ci
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /builds/reporting/sepa_service/node_modules/aws-cdk/bin/cdk
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/builds/reporting/sepa_service/node_modules/aws-cdk/bin/cdk'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
npm ERR! A complete log of this run can be found in:
npm ERR!     /build/.npm/_logs/2021-01-05T13_09_59_080Z-debug.log
```
Note that the container is pristine, there's no node_modules folder yet.

Here are my devDependencies:

```
  "devDependencies": {
    "@aws-cdk/assert": "1.79.0",
    "@types/jest": "^26.0.10",
    "@types/node": "10.17.27",
    "aws-cdk": "1.79.0",
    "jest": "^26.6.3",
    "ts-jest": "^26.2.0",
    "ts-node": "^9.0.0",
    "typescript": "~3.9.7"
  },

```
I've already tried different versions of CDK, more recent versions of the dependent libraries - it doesn't work.

To the best of my knowledge I have started observing this behaviour since upgrading to npm 7.3.0 (from 6.14.5), going back to an older version didn't change the behavious.

Here's now the folder in question looks like when the install fails:

```
ls -l node_modules/aws-cdk/
drwxr-xr-x 157 build build 5024 Jan  5 13:53 node_modules

```

### Environment

  - **CDK CLI Version  :** 1.18.147
  - **Framework Version:** 1.79.0
  - **Node.js Version:** v14.4.0
  - **OS               :** Amazon Linux 2 container
  - **Language (Version):** TypeScript (3.9.7)

--- 

This is :bug: Bug Report

**Comment by chrismckenna555** [comment]
Seeing this as well with v1.78.0

**Comment by revmischa** [comment]
Getting this with `1.85.0 (build 5f44668)` and npm v7

**Comment by jkoelewijn** [comment]
Switching from npm 7.3.0 to npm 6.14.11 solved the problem for me.

**Comment by gradybarrett** [comment]
Seeing this as well. Currently using cdk 1.88.0 and npm 7.4.3.

**Comment by mrgrain** [comment]
Also happens with npm 7.5.3 and seems to be an issues with other packages as well: https://github.com/appium/appium/issues/15095

Maybe it's a certain pattern, that is currently broken in npm 7?

**Comment by igilham** [comment]
I've seen the same problem with npm 7.5.4 and CDK 1.88.0 and 1.89.0.

CDK 1.87.0 seems to work on My Mac but not on a Linux container in Jenkins.

Mac details:

- MacOS 10.15.7
- NodeJS 12.18,0
- NPM 7.5.4
- CDK versions tested
  - 1.87.0: OK
  - 1.88.0: Fail
  - 1.89.0: Fail

I'm not sure of the details of my Linux container. Another team manages that.

**Comment by fulvio-m** [comment]
Also happend on npm 7.5.3 and 7.5.4 and CDK 1.90.0.
Worked fine in npm 7.5.3 and CDK 1.89.0.

**Comment by Blufe** [comment]
I also happened with NPM (7.5.3 | 7.5.4) and CDK (1.90.0 | 1.90.1).
Earlier versions worked fine.

**Comment by pv93** [comment]
Seeing the same issue. Deleting package-lock.json is not really an acceptable solution because it defeats the purpose of running `npm ci`.

**Comment by mrgrain** [comment]
npm 7.5.5+ and 7.6.0+ solved this issue for me.

**Comment by dirkgomez** [comment]
> Seeing the same issue. Deleting package-lock.json is not really an acceptable solution because it defeats the purpose of running `npm ci`.

Exactly, I want to use my package-lock.json.

**Comment by revmischa** [comment]
Still a big problem! Breaks CI!
https://github.com/jetbridge/jkv2-playground/runs/2370169170?check_suite_focus=true#step:5:14

**Comment by dirkgomez** [comment]
Haven't observed this in quite some time.
