### ISSUE TITLE
aws-ecs-patterns: Add CircuitBreaker pattern for QueueProcessingFargateService

### ISSUE THREAD

**Issue by daveharmon** [aws/aws-cdk#12360]
The DeploymentController was recently released, but I can't configure the CircuitBreaker as described in this blog:

https://aws.amazon.com/blogs/containers/announcing-amazon-ecs-deployment-circuit-breaker/
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs.DeploymentCircuitBreaker.html

### Use Case

Automatic rollback of failing deployment.

### Proposed Solution

Add CircuitBreaker to the configuration options (optional)

### Other

I'm assuming all the details needed to add this are in the blog post. The CircuitBreaker type exists for the BaseService from which ECS and FargateService classes are derived. We should just need to expose the option to this higher level props type.

---

This is a :rocket: Feature Request

**Comment by pepastach** [comment]
Also please add the circuit breaker support to other ECS patterns such as [ApplicationLoadBalancedFargateService](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs-patterns.ApplicationLoadBalancedFargateService.html)

This is currently the last missing piece to make our ECS experience a pure joy 😄

**Comment by ramesh82** [comment]
Awaiting to have this for ApplicationLoadBalancedFargateService pattern.

**Comment by daveharmon** [comment]
I need this pretty quickly. I'd like to contribute a solution. I've read the contributors guide, could someone please assign the issue to me?
