### ISSUE TITLE
(certificatemanager): DnsValidatedCertificate does not allow you to customize tags on the requested certificate

### ISSUE THREAD

**Issue by bigkraig** [aws/aws-cdk#12382]
Add a `certificateTags` parameter to `DnsValidatedCertificateProps` which will configure the Lambda to create tags on the requested certificate.

### Use Case

We use permission boundaries to control what CDK can create roles for. As DnsValidatedCertificate creates a role for the function that manages the certificate, we need to be able to limit this role using tags to just the managed certificate.

### Proposed Solution

Include an `acm.addTagsToCertificate` call in the `requestCertificate` function with tags defined in `DnsValidatedCertificateProps`.

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by timothy-farestad** [comment]
@njlynch Any chance this can get looked at again?  Would be a huge help for our organization as our Governance team requires certain tags on all resources, and our current workaround is to embed some cli calls post-deploy.

**Comment by njlynch** [comment]
@bigkraig  submitted a PR, but the approach would have required tags to be explicitly added to the `DnsValidatedCertificate`, separate from every other construct in a stack. I proposed an alternative approach in https://github.com/aws/aws-cdk/pull/12383#pullrequestreview-576420578.

@timothy-farestad  - Happy to help you -- or any other contributor -- get this merged in. It should be a reasonably small contribution.

**Comment by timothy-farestad** [comment]
@njlynch I took a stab following your suggestion... in https://github.com/aws/aws-cdk/pull/13990
