### ISSUE TITLE
(sns): fifo topic construct doesn't append .fifo to the topic name

### ISSUE THREAD

**Issue by skyrpex** [aws/aws-cdk#12386]
The SNS FIFO topics are failing to deploy because the topic name is missing `.fifo` at the end.

### Reproduction Steps

Create a minimal cdk app with the following SNS FIFO topic and deploy it:

```ts
import * as sns from "@aws-cdk/aws-sns";
import * as cdk from "@aws-cdk/core";

class MyStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, properties?: cdk.StackProps) {
    super(scope, id, properties);

    new sns.Topic(this, "MyTopic", {
      fifo: true,
    });
  }
}

const app = new cdk.App();

new MyStack(app, "MyStack");
```

### What did you expect to happen?

The SNS topic should append `.fifo` to the topic name if `topic: true` and `.fifo` is not present already.

### What actually happened?

The deploy failed:

```
9:48:48 PM | CREATE_FAILED        | AWS::SNS::Topic                 | FanOutTopic
Invalid parameter: Topic Name (Service: AmazonSNS; Status Code: 400; Error Code: InvalidParameter; Request ID: xxxxx-xxxx-xxxx-xxxxx; Proxy: null)
```

### Environment

  - **CDK CLI Version  :** v1.83.0
  - **Framework Version:** v1.83.0
  - **Node.js Version:**  v12.20.0
  - **OS               :** Ubuntu 20
  - **Language (Version):**  TypeScript (4.1)

### Other

It works if you manually set the topicName to include `.fifo` at the end, like this:

```ts
new sns.Topic(this, "MyTopic", {
    fifo: true,
    topicName: "MyTopic.fifo",
});
```

--- 

This is :bug: Bug Report

**Comment by skyrpex** [comment]
I've made the minimal reproduction more complete.

**Comment by NetaNir** [comment]
If you don't pass a name, does it work? Cause CloudFormation should add it if a name is not given.

**Comment by skyrpex** [comment]
@NetaNir deliverately passing an empty topicName as follows:

```ts
new sns.Topic(this, "MyTopic", {
      fifo: true,
      topicName: "",
});
```

Ends up with error too:

```
10:38:04 AM | CREATE_FAILED        | AWS::SNS::Topic    | MyTopic
Property TopicName cannot be empty if specified.
```

**Comment by NetaNir** [comment]
That's not an empty name. What happens if you don't pass a name at all?

**Comment by skyrpex** [comment]
If you mean not passing `topicName` at all, that's in the original reproduction steps.

**Comment by NetaNir** [comment]
Thanks @skyrpex.

@rrhodes I see you have added it in https://github.com/aws/aws-cdk/commit/7e60d8e7aa7a6507675a24991d9c9832017ddfed. The integration tests expected output suggest that this should work. Any ideas?

**Comment by rrhodes** [comment]
Hi @NetaNir, the integration test explicitly passes in topic name `fooTopic.fifo`, so it does not cover the case presented in this issue.

Correct me if I'm wrong, but I don't think the CDK code holds any custom logic for auto-generating a topic name if it's not provided in the props? Certainly I didn't add anything specific to FIFO.

Is it possible this is a CloudFormation bug, if its [default behavior is to generate a name](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sns-topic.html#cfn-sns-topic-topicname) and we're finding this to be invalid for FIFO topics?

**Comment by NetaNir** [comment]
So currently the API is broken, if a name is not passed- the queue creation will fail. And if a name is passed but does not have the `.fifo` suffix - the queue creation will fail. 

This is not a great customer experience and we should make it better, the minimum is to throw an error if `fifo` is set to true and `queueName` is not passed or missing the `.fifo`. Build time errors are always better than deploy time error. 

The better experience will be to append the `fifo` suffix if a name is passed and to throw if a name is not passed.

**Comment by rrhodes** [comment]
Agreed, that sounds like a good step forward until the underlying problem is resolved. Happy to open a PR for this.

**Comment by rrhodes** [comment]
Hi @NetaNir, @MrArnoldPalmer, that's a [PR opened for review](https://github.com/aws/aws-cdk/pull/12437) now. Feedback welcome.
