### ISSUE TITLE
(ec2): Missing C6gn instance class

### ISSUE THREAD

**Issue by tpunder** [aws/aws-cdk#12381]
The new C6gn instance types (https://aws.amazon.com/blogs/aws/coming-soon-ec2-c6gn-instances-100-gbps-networking-with-aws-graviton2-processors/) are missing from the InstanceClass enum.

### Use Case

In order to be able to use the new C6gn instance types via CDK

### Proposed Solution

Add the missing enum entry

### Other

* [X] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by NetaNir** [comment]
You can use pass any string using:

```ts
new InstanceType('C6gn.small') 
```

Happy to review a PR to get this added to the predefined list
