### ISSUE TITLE
(ec2): Add RDS VPC interface endpoints

### ISSUE THREAD

**Issue by choweiyuan** [aws/aws-cdk#12402]
Add RDS VPC interface endpoints

### Use Case

VPC interface endpoints are supported for RDS, but don't exist in CDK:

https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/vpc-interface-endpoints.html

### Proposed Solution

Add support for RDS VPC interface endpoints

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by johnculkin** [comment]
You can create interface endpoints with the CDK 

Here is the method on the VPC Construct 

https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ec2.Vpc.html#addwbrinterfacewbrendpointid-options

Here is an example of creating a RDS endpoint in Python 

`        vpc.add_interface_endpoint(
            'VPCRDSInterfaceEndpoint',
            service=ec2.InterfaceVpcEndpointAwsService('rds'),  # Find names with - aws ec2 describe-vpc-endpoint-services | jq '.ServiceNames'
            private_dns_enabled=True,
            subnets=ec2.SubnetSelection(
                one_per_az=False,
                subnet_type=ec2.SubnetType.ISOLATED
            ),
        )`
