### ISSUE TITLE
aws-cdk-aws_logs module log subscription (Distribution by logstream)

### ISSUE THREAD

**Issue by WoodProgrammer** [aws/aws-cdk#12410]
Hello guys
AWS log-subscription is supporting a couple of option like RANDOM and ByLogStream but I could not find how I can change logGroup distribution type on AWS CDK.In boto3 I can do that easily but I could not see any option on aws_cdk log modules.

This is the code block with CDK:

```
        aws_logs.SubscriptionFilter(
            self,
            "SubscriptionFilter",
            log_group=logGroup,
            filter_pattern=aws_logs.FilterPattern().all_events(),
            destination=destinationObject,
            distribution = ? 

        )

```
DestionObject and  LogGroup objects are done there is no issue in there but I need to be ensure about this one.
Do you have any suggestions?

Thank you

**Comment by peterwoodworth** [comment]
Sorry for the slow response time

Looks like there isn't any way to do this, as [CloudFormation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-subscriptionfilter.html) currently doesn't support it. I'm sorry for the poor experience here, ping me if you have additional questions 😄
