### ISSUE TITLE
(aws-sqs): allow specifying removalPolicy on `Queue`

### ISSUE THREAD

**Issue by grncdr** [aws/aws-cdk#12418]
I couldn't find a way to specify the removal policy for an SQS `Queue` construct without dropping down to the underlying `CfnQueue`.

### Use Case

I am importing an existing queue into a cdk-managed cloudformation stack by synthesizing an appropriate template, then manually importing via the web console.

### Proposed Solution

Add a `removalPolicy` prop and/or forward the `applyRemovalPolicy` method.

### Other

One can work around this like so:

```ts
const queue = new sqs.Queue(...)
const cfnQueue = queue.node.defaultChild as sqs.CfnQueue
cfnQueue.applyRemovalPolicy(RemovalPolicy.RETAIN)
```

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by y5mei** [comment]
```
import * as cdk from 'aws-cdk-lib';
    const queue = new sqs.Queue(this, 'CdkWorkshopQueue', {
      visibilityTimeout: Duration.seconds(300)
    });
   queue.applyRemovalPolicy(cdk.RemovalPolicy.DESTROY)
```
