### ISSUE TITLE
(apigateway): `RestApi.fromRestApiAttributes()` does not add salt to resource

### ISSUE THREAD

**Issue by taoatmars** [aws/aws-cdk#12425]
If the RestApi is define by RestApi.fromRestApiAttributes(), any deployment will not add salt to the deployment resource.

### Reproduction Steps
This is my code.
```
const api = RestApi.fromRestApiAttributes(this, 'ImportedApi', {
      restApiId: XXX,
      rootResourceId: XXX,
    });

    const allResources = api.root.addResource('cdk');

    allResources.addCorsPreflight({ allowOrigins: Cors.ALL_ORIGINS });

    const method = allResources.addMethod('PUT', ifn, {
      methodResponses: [
        {
          statusCode: '200',
          responseParameters: {
            'method.response.header.Access-Control-Allow-Origin': true,
          },
        },
      ],
      authorizationType: AuthorizationType.IAM,
    });

    // Handle deployment
    const deployment = new Deployment(this, '123_deployment', {
      api: RestApi.fromRestApiId(this, 'abc', apiCDKApiApiId),
    });
    new Stage(this, 'CDKApiStageDev', { deployment, stageName: `${ENV}` });
```

"o4aytaotest123deploymentC642C343" is the resource name in the Cloudformation template.

### What did you expect to happen?

add salt to the resource name

### What actually happened?

no salt was added to the resource name

### Environment

  - **CDK CLI Version  :*1.83*
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :*MAC*
  - **Language (Version):*TypeScript* 
  
### Other

!!!!!!!!!!!!!!!!
WORKAROUND: Just in case anyone ran into the same problem, you can manually add salt to the logical ID by calling deployment.addToLogicalId()

--- 

This is :bug: Bug Report

**Comment by NGL321** [comment]
Hey @taoatmars,

Thank you for reporting this, someone from the team will take a look as soon as able. In the future however, please ensure that your issue title follows the template guidelines so it gets properly sorted and we get to it in a more timely fashion!

Thanks much! 😄 

😸 😷

**Comment by nija-at** [comment]
We're already tracking this issue - https://github.com/aws/aws-cdk/issues/12417

Thanks.
