### ISSUE TITLE
(@aws-cdk/pipelines): SSM Parameter Store for custom environment variables in addApplicationStage not working

### ISSUE THREAD

**Issue by meleksomai** [aws/aws-cdk#12438]
We are trying to use Parameter Store and/or secret manager to store both secure and non-encrypted parameters for our CodePipeline project. We used config files before which worked fine but we believe that this is a more appropriate way than storing account ID and other parameters in a config file `config.json` in the repository.

### Reproduction Steps

This is an example code below:

```typescript
import { Construct, SecretValue, Stack, StackProps } from "@aws-cdk/core";
import { CdkPipeline, CdkStage, SimpleSynthAction } from "@aws-cdk/pipelines";
import * as secretsmanager from "@aws-cdk/aws-secretsmanager";

import { MyCustomStage } from "./stages/my-custom-stage";

export class MyPipelineStack extends Stack {
  constructor(scope?: Construct, id?: string, props?: StackProps) {
    super(scope, id, props);
    
    // ...........

    const target = process.env.NODE_ENV // retrieving the current stage "prod", "staging", "dev", etc from NODE_ENV
    const targetAccount = secretsmanager.Secret.fromSecretNameV2(
      this,
      "build-account",
      `mypipeline/${target}/account`
    );
​
    const targetRegion = secretsmanager.Secret.fromSecretNameV2(
      this,
      "build-region",
      `mypipeline/${target}/region`
    );
​
    // The application stage does not take into account the parameters
    pipeline.addApplicationStage(
      new MyCustomStage(this, "custom-stage", {
        env: {
          account: targetAccount.secretValue.toString(),
          region: targetRegion.secretValue.toString(),
        },
      })
    );
  }
}
```

### What did you expect to happen?

We shall expect the stage to deploy in the account and the region defined in the Parameter Store

### What actually happened?

The stage is deployed in the root account and region in which the code-pipeline is deployed to.

### Environment

  - **CDK CLI Version  :** 1.78.0 (build 2c74f4c)
  - **Framework Version:** 1.83.0
  - **Node.js Version:** v14.1.0
  - **OS:** Mac OS
  - **Language (Version):** TypeScript (4.1.3)

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
> We shall expect the stage to deploy in the account and the region defined in the Parameter Store

There is a circular dependency here. We need to know an account and region before we can start looking up ANYTHING in parameter store. 

Also, this is just not the way this works, and it's unlikely to change soon. Sorry.
