### ISSUE TITLE
(aws-glue): Job construct

### ISSUE THREAD

**Issue by humanzz** [aws/aws-cdk#12443]
In https://github.com/aws/aws-cdk/issues/5172 and its PRs, the suggestion was made to break a PR down into 2
1. Add Connection construct
2. Add Job construct

I've since had a look and realized the work needed involves 3 constructs
1. Connection construct #12442
2. SecurityConfiguration construct #12449
3. Job construct (this request)

Since the original issue and PR have gone without progress for a time, I am contributing some effort here and as such will be creating 3 issues and hopefully 3 PRs to address each of the issues.

This is the first issue; to add the Glue `Job` construct

### Use Case

Be able to create Glue jobs with L2 constructs that utilize Glue connections. My immediate use case is to be able to connect data sources in a VPC

### Proposed Solution

Introduce a `Job` L2 construct wrapping the [Glue Job CloudFormation resource](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-job.html)

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by humanzz** [comment]
@iliapolo there are now 3 PRs ready for review
- `Connection` construct https://github.com/aws/aws-cdk/pull/12444
- `SecurityConfiguration` construct: https://github.com/aws/aws-cdk/pull/12450
- `Job` construct https://github.com/aws/aws-cdk/pull/12506 which is the larger one with the above 2 as prerequisites

**Comment by iliapolo** [comment]
@humanzz amazing, thanks so much for these PR's. Should we start with the `Connection` construct PR?

**Comment by humanzz** [comment]
@iliapolo I'd say either Connection or SecurityConfiguration are good to start with, or even both in parallel as they're independent.

Job has dependencies on both, so for it to be complete both PRs will have to be merged first. It's currently kinda complete but for using them and I anticipate it will take some reviewing/discussion as it's not a small one.

**Comment by straygar** [comment]
Thanks @humanzz , super excited to see this merged! 🔥

**Comment by maddy2u** [comment]
Any update on this?

**Comment by tdikland** [comment]
Would love to see this merged. Anything I can help with?
