### ISSUE TITLE
(cli): Extend the cdk bootstrap command to optionally accept one or more stack arguments

### ISSUE THREAD

**Issue by mpvosseller** [aws/aws-cdk#12446]
Extend the `cdk bootstrap` CLI command to optionally accept one or more `--stack` arguments. When one or more stacks are provided the CLI should only bootstrap the environments referenced by those stacks.

### Use Case

Currently a developer can run `cdk bootstrap` (without arguments) to bootstrap every environment referenced in the app. This is problematic for developers who may not have permission to all these environments and does not intend on deploying all stacks. Consider an app like the below that has a `prod` and a `dev` stack. The `prod` stack has a hardcoded production environment while the `dev` stack is intended for each developer's personal environment. 

```typescript
const app = new App()

new MyStack(app, 'prod', {
  env: {
    account: '1234567890',
    region: 'us-east-1',
  },
})

new MyStack(app, 'dev', {
  env: {
    account: process.env.CDK_DEFAULT_ACCOUNT,
    region: process.env.CDK_DEFAULT_REGION,
  },
})
```

If a developer does not have access to `prod` they will see errors when they run `cdk bootstrap`. It would be nice if we could allow a developer to bootstrap only the environments referenced by the stacks they intend on deploying.

> `cdk bootstrap --stack dev`

### Proposed Solution

Update the `cdk bootstrap` CLI to optionally accept one or more `--stack` arguments and only bootstrap the environments referenced by those stacks.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
I agree that it's potentially not a bad feature, user expectations-wise.

Right now the accepted arguments are of the form `aws://<account>/<region>`.

**Comment by mpvosseller** [comment]
👍

And just to put a finer point on this. The above would allow us to offer a generic bootstrap script so each developer would not need to run a unique command where they need to substitute in their own account id and region.

Consider  `cdk bootstrap aws://<YOUR_ACCOUNT>/<YOUR_REGION>` vs `npm run bootstrap:dev`

where the latter could be implemented like this:
```json
  # package.json
  "scripts": {
     "bootstrap:dev": "cdk bootstrap --stack dev",
   }
```

Thanks for the consideration.
