### ISSUE TITLE
(assets): Request to add --force publish option

### ISSUE THREAD

**Issue by wchaws** [aws/aws-cdk#12440]
Since cdk support customize synthesizer, so I wrote a https://github.com/wchaws/cdk-bootstrapless-synthesizer/ for people who wants to provide only a cloudformation template for their customers instead of a cdk repo. The generated `assets.json` is quite different which may contain duplicate assets name(it's not a checksum) like below:

```js
{
    ...

    "MyStack.template.json": {
      "source": {
        "path": "MyStack.template.json",
        "packaging": "file"
      },
      "destinations": {
        "current_account-current_region": {
          "bucketName": "my-dist-bucketname",
          "objectKey": "project-name/latest/MyStack.template.json"  // THIS LINE
        }
      }
    }
  },
  "dockerImages": {}
}
```
So I need a way to push that asset to S3 bucket even if it exists

### Proposed Solution

From the current code, cdk-assets won't upload asset if it exists

https://github.com/aws/aws-cdk/blob/da1ed08a6a2de584f5ddf43dab4efbb530541419/packages/cdk-assets/lib/private/handlers/files.ts#L40-L43

Maybe cdk-assets could do this `cdk-assets publish --force` to force push the assets even if it exists

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by eladb** [comment]
The current design of `cdk-assets` heavily relies on the immutability of assets, so I am not sure this is something we would like to support. @rix0rrr , what do you think?

**Comment by rix0rrr** [comment]
Agreed. I would like to see a strong use case for this, something driven by real-world requirements and not "I want this because I can".
