### ISSUE TITLE
aws-cdk/aws-assert: Can I run a test against a resource ONLY if it exists in stack?

### ISSUE THREAD

**Issue by lachlan-vass** [aws/aws-cdk#12452]
## :question: General Issue

Can I run a test against a resource ONLY if it exists in stack?

### The Question

Basically, I wanted to write a suite of standard validation tests to ensure that my stack complies with standards, best practices and guidelines for my environment. To do that, I want to run tests against resources even if they do not exist in the current stack (so all stacks can be subject to the same validation tests). 

Consider these this tests:

```
it("should have no IAM users with bad names", () => {
  // Setup
  const app = new App();
  const stack = new testStack(app, "stack");

  expectCDK(stack).to(haveResourceLike("AWS::IAM::User", {
    UserName: stringLike("REQUIRED-PREFIX-username"),
  }));
});
```

If the testStack does not have any IAM users, the test will fail. That makes sense, since I am asking CDK if there is any IAM Users, and if those users have the correctly formatted username. 

However I want this test to only run if the stack under test has the resource in question (IAM::User, in this case), so this suite of standard validation tests does not report on failures just because a resource does not exist.

### Environment

  - **CDK CLI Version:** 1.83.0
  - **Module Version:** @aws-cdk/aws-assert 1.83.0
  - **Node.js Version:** 15.40.02
  - **OS:** Linux (Manjaro 20.1) 
  - **Language (Version):** TypeScript

**Comment by peterwoodworth** [comment]
Hey @lachlan-vass,

You can run tests on resources only if the exist in the stack! To do this, you'll have to implement a bit of logic in your application to skip the test if there is no resource to test on. We can create a loop that goes through each stack, and each stack will be checked for the resource before the test is ran. Using your example, it should look something like this:

```ts
const app = new App();
const testStacks: Array<IStack> = [new testStack(app, "stack"), ...];
​
testStacks.foreach(stack => {
  it("should have no IAM users with bad names", () => {
    if(haveResourcesLike("AWS::IAM::User")){
      expectCDK(stack).to(haveResourceLike("AWS::IAM::User", {
        UserName: stringLike("REQUIRED-PREFIX-username"),
      }));
    } else {
      return true;
    }
  });
	
  it(...);
});
```

Let me know if you run into any more issues with this!

**Comment by lachlan-vass** [comment]
@peterwoodworth - what a great example. Now that I see it, it is so simple and .... beautiful. 

This will help me a lot and go a long way to writing some general validation tests :)
