### ISSUE TITLE
(aws-ecs): fromClusterAttributes requires VPC

### ISSUE THREAD

**Issue by mimozell** [aws/aws-cdk#12468]
I'm trying to fetch an ECS cluster based on its name, but security groups (mentioned [here](https://github.com/aws/aws-cdk/issues/11146)) and VPC (at least) are required. 

### Reproduction Steps
```
    Cluster.fromClusterAttributes(
        this, 
        "importedCluster",
        ClusterAttributes.builder()
            .clusterName(clusterName)
            .securityGroups(emptyList())
            .build()
```

### What did you expect to happen?
I would expect `fromClusterAttributes` to have the same behaviour as `aws ecs describe-clusters <clusterName>`. The API clearly doesn't require you to provide the VPC (or security groups), so why does this?

### What actually happened?

`Exception in thread "main" java.lang.NullPointerException: vpc is required`

### Environment

  - **CDK CLI Version**: 1.78.0 (build 2c74f4c) and 1.83.0 (build 827c5f4)
  - **Node.js Version**: v12.16.3
  - **OS**: MacOS
  - **Language (Version)**: Kotlin (openjdk version "11.0.8")

--- 

This is :bug: Bug Report

**Comment by tscully49** [comment]
We are having the same issue in a different context.  In cloudformation, creating a fargate serivice only requires `The short name or full Amazon Resource Name (ARN) of the cluster on which to run your service. If you do not specify a cluster, the default cluster is assumed.` (from https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-service.html) and I would expect that to have similar behavior here.  Instead, for CDK, to create a FargateService construct, I have to find the cluster with this function by passing both the securityGroups and VPC, when it seems a cluster name or ARN should be fine.

**Comment by DandyDev** [comment]
I'm having a similar issue. I've searched all afternoon to find a way to reuse an ECS cluster in another CDK App than the one where the cluster was created. Referencing an existing ECS cluster requires (among other things):

- VPC: I can export the `id` of the VPC when that VPC is created, but I cannot retrieve the that `id` using `Fn.importValue` due to [this bug](https://github.com/aws/aws-cdk/issues/4096)
- Security Groups: I cannot even _export_ the security group ids when creating the cluster using the following code:

```python
cluster = ecs.Cluster(self, "ECSCluster", cluster_name='my-cluster', vpc=self.vpc)
security_group_ids = [sg.security_group_id for sg in cluster.connections.security_groups]
CfnOutput(self, "SGExport", value=Fn.join(',', security_group_ids), export_name='sg-ids')
```

Because it gives me this error: `Error: FnJoin requires at least one value to be provided`

Apparently `cluster.connections.security_groups` is empty?

**Comment by vgribok** [comment]
Same applies to EKS Cluster.fromClusterAttributes().
All the API seems to need is account, region and cluster name, as in "`aws eks describe-cluster --name <cluster name>`"

**Comment by mimozell** [comment]
I have a feeling they are making some really strange design decisions with cdk :( Not only do they go against expectations and logic (a unique ID should be enough to give you the object, such as the cluster), but also against what we are used to with the cli and sdk...

**Comment by teuber789** [comment]
Any update on this? Still facing this problem today.

My situation is similar to @DandyDev 's; I'm trying to reuse an ECS cluster in another CDK app.
