### ISSUE TITLE
(aws-apigateway): api.url not resolved when passed between stacks

### ISSUE THREAD

**Issue by alex9311** [aws/aws-cdk#12465]
I have one stack creating an `aws_apigateway.RestApi`. I pass the url to a second stack but rathe than getting a url I get a token (Like `https://${Token[TOKEN.189]}.execute-api.${Token[AWS.Region.4]}.${Token[AWS.URLSuffix.1]}/${Token[TOKEN.207]}/`).

### Reproduction Steps
app.py
```
from aws_cdk import core

from repro.api_stack import ApiStack
from repro.depending_stack import DependingStack


app = core.App()
api_stack = ApiStack(app, "stack1")
DependingStack(app, "stack2",
               api_url=api_stack.url)
app.synth()
```

api_stack.py
```
from aws_cdk import core
from aws_cdk import aws_apigateway


class ApiStack(core.Stack):

    def __init__(self, scope: core.Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        my_api = aws_apigateway.RestApi(self, 'MyApi', rest_api_name='MyApi')
        api_entity = my_api.root.add_resource('images')
        api_entity.add_method('GET')

        self.url = my_api.url
```

depending_stack.py
```
from aws_cdk import core

class DependingStack(core.Stack):
    def __init__(self, scope: core.Construct, construct_id: str, api_url) -> None:
        super().__init__(scope, construct_id)
        print("got api_url: "+api_url)
```

### What did you expect to happen?
I expected the api_url to be treated as a dependency and be resolved when it is passed to the second stack

### What actually happened?
A token was passed

### Environment

  - **CDK CLI Version  : ** 1.83
  - **Framework Version:** 1.83
  - **Node.js Version:** v14.4.0
  - **OS               :** MacOS
  - **Language (Version):**  python 3.8.3

### Other
related SO post
https://stackoverflow.com/questions/60074546/aws-cdk-passing-api-gateway-url-to-static-site-in-same-stack
--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
This is how tokens in the CDK work. See https://docs.aws.amazon.com/cdk/latest/guide/tokens.html

The API URL cannot be known to the CDK until the stack is deployed, so we use token to represent it at the time of CDK app synthesis.
