### ISSUE TITLE
(SQS): Unable to import a FIFO queue when the queue ARN is a Token

### ISSUE THREAD

**Issue by gibsonan** [aws/aws-cdk#12466]
Unable to use `fromQueueArn` or `fromQueueAttributes` to import an existing queue with the `fifo` property set to True when the queue ARN is a Token.

### Reproduction Steps

```python
queue_arn = core.Fn.import_value(shared_value_to_import=EXISTING_FIFO_QUEUE_ARN_EXPORT_NAME)

# CDK assumes it's a standard queue and there is no option to override
fifo_queue = aws_cdk.aws_sqs.Queue.from_queue_arn(self, 'SharedFifoQueue', queue_arn)
assert fifo_queue.fifo  # Fails assert

# Explicitly specifying the queue url with the `.fifo` suffix doesn't help
fifo_queue = aws_cdk.aws_sqs.Queue.from_queue_attributes(
    self, 'SharedFifoQueue',
    queue_arn=queue_arn,  # Required argument
    queue_url='https://sqs.us-west-2.amazonaws.com/123456789012/ExistingFifoQueue.fifo'
)
assert fifo_queue.fifo  # Fails assert
```

### What did you expect to happen?
CDK either automatically resolves that the queue is FIFO, deduces that it's FIFO from the URL, or provides a mechanism for manually setting the `fifo` property to True.

### What actually happened?
CDK imported the FIFO SQS queue with the `fifo` property set to `False`

### Environment

  - **CDK CLI Version  :** 1.83.0
  - **Framework Version:** 1.83.0
  - **Node.js Version:** 15.5.1
  - **OS               :** MacOS v11.1
  - **Language (Version):** Python 3.8.6 

### Other

This matters because it's not possible to synthesize this EventBridge Rule.  CDK rejects the `message_group_id` parameter since `fifo_queue.fifo` is `False`.
```python
aws_cdk.aws_events.Rule(
    self, 'EventsToFifoQueue',
    targets=[
        aws_cdk.aws_events_targets.SqsQueue(
            queue=fifo_queue,
            message_group_id='default',  
        )
    ],
    event_pattern=aws_cdk.aws_events.EventPattern(detail_type=['Foo Event'])
)
```

--- 

This is :bug: Bug Report

**Comment by rubfergor** [comment]
Is there any advance on this? If trying to import a SQS FIFO queue using its ARN from another stack, you can't use the queue as an EventBridge target with a messageId on Typescript neither.
