### ISSUE TITLE
(aws-cdk): can't create cache policy with minTtl, maxTtl, defaultTtl: 0

### ISSUE THREAD

**Issue by I2olanD** [aws/aws-cdk#12461]
## :question: General Issue

I'm trying to deploy a cache policy for my cloudfront distribution, to disable caching for a certian pattern. When I try doing following settings, my deployment fails:

minTtl: Duraton.seconds(0)
maxTtl: Duraton.seconds(0)
defaultTtl: Duraton.seconds(0)

Is there another way to disable caching for a certain path with CDK?

### Environment

  - **CDK CLI Version:** 1.83.0
  - **Module Version:** 1.83.0
  - **Node.js Version:** 12.18.0
  - **Language (Version):** [TypeScript (3.8.3)]

**Comment by robertd** [comment]
Try this out and see if it works.

```ts
distro.addBehavior("/foo/baz/*", new origins.S3Origin(bucket), {
   cachePolicy: cloudfront.CachePolicy.CACHING_DISABLED
});
```

I wasn't sure what kind of origin you're using so I've used S3 bucket as an example.

**Comment by I2olanD** [comment]
@robertd 

That's exactly what i was looking for. Thank you so much!

**Comment by robertd** [comment]
You're welcome! 👍
