### ISSUE TITLE
(SNS): SQS to SNS subscription permissions issue

### ISSUE THREAD

**Issue by SZubarev** [aws/aws-cdk#12476]
I have two stacks - Stack1 creates SNS, Stack2 creates SQS. I need to subscribe SQS to SNS

If I'm adding subscription in Stack1, importing SQS by ARN and using SNS topic created - CDK doesn't create proper permissions for SNS to publish to the SQS and getting error when SNS publishes to the SQS:

        "providerResponse": "{\"ErrorCode\":\"AccessDenied\",\"ErrorMessage\":\"Access to the resource https://sqs.eu-central-1.amazonaws.com/NNNNN/MMMMM-queue is denied.\",\"sqsRequestId\":\"Unrecoverable\"}",

If I'm adding the subscription in Stack2, using created SQS and importing SNS topic - everything works fine.

### What did you expect to happen?

I'd expect the same behavior regardless which of the stacks adds the subscription. Current behavior causes the error quite tricky to find and troubleshoot.

### Environment

  - **CDK CLI Version  :** 1.41
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :** MacOS
  - **Language (Version):**  TypeScript

### Other

--- 

This is :bug: Bug Report

**Comment by karthikns16** [comment]
I am facing the same problem too. Right now I am on 1.76.0 and attempting to use CfnQueuePolicy, but https://github.com/aws/aws-cdk/pull/11651 issue prevents me from using the queueURL generated by cdk instead are trying a custom resource to build the queue URL 

```

aws_sdk_call = cr.AwsSdkCall(
            service='SQS',
            action='getQueueUrl',
            parameters={
                "QueueName": queue_name,
                # TODO: for cross account access should go to deployment_metadata
                "QueueOwnerAWSAccountId": "XXXX"
            },
            # this is anti pattern as per the aws docs,
            # TODO: for cross account access should go to deployment_metadata
            region="XXXX",
            physical_resource_id=cr.PhysicalResourceId.of("GetQueueURL")
        )




```

**Comment by csujiabin** [comment]
I think you need explicitly grant permission to SNS in the SQS, refer below sample permission:

```typescript
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Service": "sns.amazonaws.com"
      },
      "Action": "sqs:SendMessage",
      "Resource": "arn:aws:sqs:us-west-2:<account>:<queue-name>",
      "Condition": {
        "ArnEquals": {
          "aws:SourceArn": "arn:aws:sns:us-west-2:<account>:<sns-name>"
        }
      }
    }
  ]
}
```
