### ISSUE TITLE
(codebuild): documentation and type restriction for SecretsManager stored environment variables

### ISSUE THREAD

**Issue by blimmer** [aws/aws-cdk#12478]
When upgrading to the latest version of CDK, I ran into this warning, introduced with [this PR](https://github.com/aws/aws-cdk/pull/12150).

> Plaintext environment variable 'NPM_TOKEN' contains a secret value! This means the value of this variable will be visible in plain text in the AWS Console. Please consider using CodeBuild's SecretsManager environment variables feature instead. If you'd like to continue with having this secret in the plaintext environment variables, please set the checkSecretsInPlainTextEnvVariables property to false

However, it's unclear to me what I should use as the `value` property with `BuildEnvironmentVariableType.SECRETS_MANAGER` because it's currently typed as `any`: https://github.com/aws/aws-cdk/blob/422dc8e9d50105af4e710d409a4f301079d43f3f/packages/%40aws-cdk/aws-codebuild/lib/project.ts#L1780-L1784

### Use Case

After the warning message was introduced, I was trying to follow the best-practice of using the SECRETS_MANAGER build environment variable type, but it wasn't clear how to do so. Other users might also be confused.

#### Ideally

Dynamically type `value` based on the `type` specified. If `BuildEnvironmentVariableType.SECRETS_MANAGER`, require `secretsManager.ISecret`. Do the same for the other supported types. This would require an update, as it currently looks to require `secret.secretName`, which is a string.

#### Either way

- Update the documentation to show examples of each possible environment type.
- In the warning introduced with https://github.com/aws/aws-cdk/pull/12150, link to the documentation so users can easily opt-in to the suggested behavior.

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by skinny85** [comment]
Hey @blimmer ,

thanks for opening the issue. The trick when using `type` BuildEnvironmentVariableType.SECRETS_MANAGER` is that `value` points to the name of the SecretsManager Parameter, same as when `type` is `BuildEnvironmentVariableType.PARAMETER_STORE`.

I'll update the docs that property.

Thanks,
Adam

**Comment by skinny85** [comment]
I should add, if you want to take a stab at it @blimmer , that would be awesome too 🙂. https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md
