### ISSUE TITLE
(lambda): Lambda insights functionality

### ISSUE THREAD

**Issue by flemjame-at-amazon** [aws/aws-cdk#12489]
## :question: General Issue

Lambda insights was released and the process for enabling requires writing the following code:

```ts
const layerArn = `arn:aws:lambda:us-west-1:580247275435:layer:LambdaInsightsExtension:12`;
const layer = lambda.LayerVersion.fromLayerVersionArn(this, 'LayerFromArn', layerArn);
const lambdaFunction = new lambda.Function(this, 'Function', {
    ...otherProps,
    layers: [layer]
});
lambdaFunction.role?.addManagedPolicy(ManagedPolicy.fromAwsManagedPolicyName('CloudWatchLambdaInsightsExecutionRolePolicy'))
```

### The Question
I'd like this to be natively integrated with Lambda functions, and want feedback on an approach to do so. Here's what I'm thinking now:

```ts
const lambdaFunction = new lambda.Function(this, 'Function', {
  lambdaInsightsOptions? : {
    layerArn?: string,
    insightsVersion?: InsightsVersion
  }
});

export class InsightsVersion {
    public static readonly 1_0_89_0 = new InsightsVersion(...);
    public static readonly 1_0_86_0 = new InsightsVersion(...);
    private constructor(...);
}
```

If `lambdaInsightsOptions` isn't provided, nothing happens. If it is provided, then the relevant managed policy and the appropriate lambda layer are applied to the function automatically.

Either `layerArn` or `insightsVersion` must be provided, but not both. This is what builds the lambda layer object. `layerArn` is an escape hatch, to allow for providing an arbitrary ARN in case a new version is released and a customer wants to use it immediately.

Insights versions are based on the provided versions: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Lambda-Insights-extension-versions.html

### Environment

  - **CDK CLI Version:** 1.84.0
  - **Language (Version):** all

**Comment by flemjame-at-amazon** [comment]
@nija-at any update on this?

**Comment by nija-at** [comment]
Sorry for the late reply @flemjame-at-amazon. This seem to have slipped between the cracks.

We could do something simpler like this -

```ts
new lambda.Function(this, 'MyFunction', {
  // ...
  insightsVersion: InsightsVersion.1_0_89_0
});
```

This would automatically bring the correct insights layer.

In case, there's a new version not supported by lambda, this could be done by -

```ts
new lambda.Function(this, 'MyFunction', {
  // ...
  insightsVersion: InsightsVersion.custom({
    layerArn: ...,
  });
});
```

**Comment by jonnekaunisto** [comment]
I have an issue that is sort of related to this one #13001. There should probably be a way that people can easily add AWS first party layers. Other than using the ARN. We can use the same one for this and every other layer.
