### ISSUE TITLE
(cli): A way to get profile name in stack when it's specified in the command-line option

### ISSUE THREAD

**Issue by tbrand** [aws/aws-cdk#12481]
I use AWS SDK in my CDK stack to fetch information that is not managed by CDK.
When I set the profile name by using '--profile' option, it only affects to stack itself but not the inner AWS SDK.
It means that CDK stack will deploy on Account A but AWS SDK fetch the information from Account B.

Of course, when I set the profile manually in the source code like this, it works.
But it's not flexible especially when I want to switch deploy stages.
```typescript
AWS.config.credentials = new AWS.SharedIniFileCredentials({ profile: 'MyProfileNameForAccountA' });
```

Is there any way to get the profile name specified in the command line option?
If not, I would like to ask you to add the way to get the profile name in the stack like this.
```typescript
const profileName = // A way to get profile name that is specified in the command-line option.
AWS.config.credentials = new AWS.SharedIniFileCredentials({ profile: profileName });
```

### Use Case

This feature is useful for those who want or need to use AWS SDK in the stacks even if it is not a recommended way to manage resources.

### Proposed Solution

A way to get profile name when it is specified in the command-line option.
I saw the profile name in the result of  `cdk deploy --verbose` as command-line arguments, so I hope the information is passed to the stack. (But cannot get it directly for now.)

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
It is not recommended to use the SDK inside CDK apps. Your application should be deterministic, and not make network calls.

Try and use context providers if possible, if not then wrap your CDK app in a script that does SDK calls and writes them to a file, then read that file in your CDK application.

**Comment by acme-im** [comment]
Why this issue is closed? It's still actual, generic and is unrelated to "using SDK from CDK anti-pattern".

**Comment by rayrapetyan** [comment]
Why this issue is closed? It's still actual, generic and is unrelated to "using SDK from CDK anti-pattern".

**Comment by jnawk** [comment]
interesting how the leap of logic has worked - "oh, they want to know what profile is being used - it must be because they want to do things we don't approve of, quick, close the issue, put our heads in the sand!"

**Comment by jnawk** [comment]
here's such a wrapper - rough as guts - it assumes heaps, specifically that you have your real `app` command in `_app` in your `cdk.json`, and just whacks all the arguments you added to that command - you'd need to do all the parsing yourself in your app, etc.
also assumes you have `jq` 

```shell-script
#!/bin/bash
APP="$(jq -r ._app < cdk.json) $@"
SCRIPT=".app=\"${APP}\""
jq "$SCRIPT" < cdk.json > _cdk.json
mv _cdk.json cdk.json
cdk $@
```

**Comment by adam-nielsen** [comment]
I worked around this by changing the way I specified the profile.  Instead of `npx cdk --profile my-aws-profile deploy` I specified it in the standard `AWS_PROFILE` environment variable:

    AWS_PROFILE=my-aws-profile npx cdk deploy

This worked just the same as using `--profile`, but with the added advantage that the AWS SDK also picked up the profile automatically so I could do the lookups I needed that CDK doesn't support.

**Comment by rnag** [comment]
This is a blocker for me. I too, use AWS SDK calls in my CDK app code. This is a blocker because passing `--profile` to `cdk` does not allow a path to retrieve said profile name in user CDK code.

The workaround as mentioned, is to use environment `$AWS_PROFILE` instead, but unfortunately this is still a missing feature, and something that I will have to mention in documentation -- that passing `--profile` to cdk tool in this use case, is a no-go.

**Comment by jnawk** [comment]
love how the cdk guys say don't make network calls, yet cdk itself makes them, eg Vpc lookups, etc. don't do as we do, do as we say.

**Comment by dirkluijk** [comment]
Can this be reopened? This is a valid feature request, even when making no calls with AWS SDK it must be possible to obtain the profile from the CDK context, right?
