### ISSUE TITLE
feature-request: support mfa_serial (consistency with aws cli)

### ISSUE THREAD

**Issue by ChintanRaval** [aws/aws-cdk#1248]
if a profile in `~/.aws/config` includes `mfa_serial` option, then aws cli reads it and asks for MFA code:
```
Enter MFA code for arn:aws:iam::665544332211:mfa/myusername:
```
where as cdk simply errors out:
```
The security token included in the request is expired
```
for the time being, I use a hacky solution where i first use AWS CLI with a sample command like `aws ec2 describe-availability-zones --profile my-profile` which asks me for MFA token and then upon authentication, creates a file `~/.aws/cli/cache/xxxx.json` from where I can extract the temp access key, secret and session token and set them as environment variables for terminal. then, AWS CDK utilises those values and works as expected.

Can mfa support please be added to cdk also please?

**Comment by rix0rrr** [comment]
I've never used this feature. Does the CLI request an MFA token on every request, or only once in a while?

**Comment by solcyr** [comment]
+1 for this feature. This could be very useful to practice CDK in my organization.

**Comment by zmgehlke** [comment]
I think I'm also running into this while trying to use `cdk deploy`.

**Comment by angusfz** [comment]
+1  cdk support mfa for IAM best practice https://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html#enable-mfa-for-privileged-users

**Comment by abbottdev** [comment]
Our org only allows for accounts with MFA enabled using IAM. The workaround is ugly and not very accessible unless you're an advanced user.. The CDK (IMO) makes cloudformation more accessible, which is kind of the opposite of this workaround 😄  Hopefully this gets prioritised soon!

**Comment by timoteialbu** [comment]
Our organization also enforces MFA access, so until that is added we won't be able to use the CDK.

**Comment by dacoty** [comment]
I can't use CDK until MFA support is included.

**Comment by qoomon** [comment]
@dacoty You may can use my little helper script, to store temporary role session credentials in your credential file. It supports MFA as well.
https://gist.github.com/qoomon/e08136f7d50df0cfac1e618c0de94fec

**Comment by rix0rrr** [comment]
JS SDK seems to support this now:

https://github.com/aws/aws-sdk-js/pull/2126

**Comment by dcoty** [comment]
I Hate to resurrect this, **but this issue/request is NOT resolved**. At least not for people using Python anyway. I'm Posting the following in case anyone else runs into the issue and hits this when using teh googles.

You have to use a 3rd party python library(aws-mfa) to get MFA to work with this.
I've checked it out beforehand , no funkiness or typo squatting so the library seems safe. It would be nice if this can get included in the CDK project though. Anyways.....

**how to fix the problem:**
- **download and install aws-mfa python library(https://github.com/broamski/aws-mfa)**
- **in your credentials file, copy everything from [default] and make new entry called [default-long-term]**
- **copy your MFA arn from your AWS environment( in IAM/users/username/security credentials/assigned mfa device)**
- **run this command: aws-mfa --duration 1800 --device<your device arn>**
- **enter your MFA code when prompted**
- **Rejoice and finally use cdk deploy.**

**Comment by dcoty** [comment]
> @dacoty You may can use my little helper script, to store temporary role session credentials in your credential file. It shares the same credential cache as aws cli. It supports MFA as well. Should work out of the box if you've installed aws cli already
> https://gist.github.com/qoomon/e08136f7d50df0cfac1e618c0de94fec

The link to this is broken, but you could script out the steps i have above if you wanted.

**Comment by mateja82** [comment]
This is a feature stopping us from adopting CDK as an official Deployer, so +1

**Comment by Dzhuneyt** [comment]
I use https://github.com/99designs/aws-vault as a workaround. It supports MFA natively and is a tiny wrapper around the "cdk deploy: command basically.

My tipical workflow would like:
```
aws-vault exec --duration 8h mycompanyprofile // this one prompts for MFA and stores short term credentials for 8 hours == working day
cdk deploy // Notice there's no need for AWS_PROFILE or any other trickeries anymore because it uses the credentials, set in environment from the previous command
```
