### ISSUE TITLE
(aws-cognito): UserPoolDomain.baseUrl() returns incorrect URL for gov cloud

### ISSUE THREAD

**Issue by kastork** [aws/aws-cdk#12500]
When operating in `us-gov-west-1`, `baseUrl()` returns 

`https://<prefix>.auth.us-gov-west-1.amazoncognito.com`

when it should return

`https://<prefix>.auth-fips.us-gov-west-1.amazoncognito.com`

This is :bug: Bug Report

**Comment by nija-at** [comment]
Thanks for filing this issue. 
Is there any documentation around this you can point to? I'm wondering about things like the FIPS endpoint being opt-in or just standard for gov cloud.

**Comment by kastork** [comment]
One would expect this page to document ALL the gov cloud differences, but it does not:  https://docs.aws.amazon.com/govcloud-us/latest/UserGuide/govcloud-cog.html.  Perhaps an issue should be raised with the documentation people.

FIPs info is available here, but it doesn't mention non-fips for cognito:  https://aws.amazon.com/compliance/fips/

I don't think you can opt out of FIPS for the authorization endpoint in the gov partition.  This WOULD make  sense considering cognito is likely to be used to protect services that also require FIPS.

**Comment by sky-c** [comment]
@nija-at Any update or workaround on this?  I presently can not deploy an API with a Cognito authorizer to GovCloud with the CDK.

**Comment by cmckni3** [comment]
> One would expect this page to document ALL the gov cloud differences, but it does not: https://docs.aws.amazon.com/govcloud-us/latest/UserGuide/govcloud-cog.html. Perhaps an issue should be raised with the documentation people.
> 
> FIPs info is available here, but it doesn't mention non-fips for cognito: https://aws.amazon.com/compliance/fips/
> 

Yes, GovCloud documentation is lacking.

The page above should list `<your_user_pool_domain>.auth-fips.us-gov-west-1.amazoncognito.com` in the middle column for GovCloud. Personally, I think `<your_user_pool_domain>` should say `<your_user_pool_domain_prefix>`.

> I don't think you can opt out of FIPS for the authorization endpoint in the gov partition. This would make sense considering cognito is likely to be used to protect services that also require FIPS.

Yes, Cognito in GovCloud (only available in us-gov-west-1 right now) requires using a subdomain of `auth-fips.us-gov-west-1.amazoncognito.com`. Custom domains are not available (leverages CloudFront in Commercial partition).
