### ISSUE TITLE
(stepfunctions-tasks): EMR createCluster command, add Instances > InstanceFleets > LaunchSpecifications > OnDemandSpecification

### ISSUE THREAD

**Issue by mohanrajendran** [aws/aws-cdk#12501]
The current InstanceFleetProvisioningSpecificationsProperty (https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-stepfunctions-tasks.EmrCreateCluster.InstanceFleetProvisioningSpecificationsProperty.html) only supports spot specification whereas the EMR InstanceFleetProvisioningSpecifications supports OnDemandSpecification (https://docs.aws.amazon.com/emr/latest/APIReference/API_InstanceFleetProvisioningSpecifications.html#EMR-Type-InstanceFleetProvisioningSpecifications-OnDemandSpecification). I would like the functionality to add OnDemandSpecifications for our usecase.

### Use Case

Functional parity with options available in EMR and for our internal use where we need to specify AllocationStrategy under OnDemandSpecifications.

### Proposed Solution

Add OnDemandProvisioningSpecificationProperty type with allocationStrategyProperty. Add a field called onDemandSpecification to InstanceFleetProvisioningSpecificationsProperty here. https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-stepfunctions-tasks/lib/emr/emr-create-cluster.ts#L598

Finally modify this function (https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-stepfunctions-tasks/lib/emr/private/cluster-utils.ts#L123) to emit the relevant parameters for ondemand specification.

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by zanussbaum** [comment]
Is this being actively developed? This a feature that would be a big win for our current Step Function and make migrating to flexible fleets incredibly easy for our team. Otherwise, we will need to re-haul our step function.

**Comment by JiahuiTao** [comment]
This feature will benefit our team a lot. We have many StepFunctions state machines with most steps running on EMR. Creating an EMR cluster with FlexibleFleet in Sfn with CDK will make our job a lot more efficient.

**Comment by itsrts** [comment]
This becomes really crucial where required. It would be really helpful if this can be picked up.

**Comment by rsmayda** [comment]
FYI it appears this is implemented in CDK v2 https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_emr.CfnCluster.InstanceFleetProvisioningSpecificationsProperty.html

**Comment by rsmayda** [comment]
Created duplicate here https://github.com/aws/aws-cdk/issues/27761 -- feel free to follow progress.
