### ISSUE TITLE
(aws-events): Allow EventBridge Rule to Target Lambda by Alias or Version

### ISSUE THREAD

**Issue by baumannalexj** [aws/aws-cdk#12522]
When creating an EventBridge Rule with CDK, I want to target a lambda function Alias or Version. Targeting an alias or version is allowed in the AWS Console UI, but I cannot find this option through the CDK, the resulting targets the base lambda ARN, effectively pointing to $LATEST.

### Use Case

We  continuously deploy of our Lambdas through a CICD pipeline, but we manually "release" by pointing the Alias to a specific version. All our services reference our lambdas by alias/version (apigateway, sqs, sns, ...)

### Proposed Solution

Add an option for Alias or Version when creating an EventTarget

```

const awsEvents = require("@aws-cdk/aws-events");
const awsEventsTargets = require("@aws-cdk/aws-events-targets");

//my function
 const lambdaFunction = new lambda.Function(this, generateConstructName("lambda"), {
            runtime: lambda.Runtime.NODEJS_12_X,
            code: lambda.Code.fromAsset(`../${FUNCTION_NAME}.zip`),
            handler: "src/index.handler",
           ...
}


//event bridge
const myEventPayload = {...};

const eventTarget = new awsEventsTargets.LambdaFunction(lambdaFunction, {
            event: awsEvents.RuleTargetInput.fromObject(myEventPayload),      
            version:        <---- allow this ------
            alias:             <----or this ----------
        });

const eventRule = new awsEvents.Rule(this, generateConstructName("event-rule"), {
    enabled: true,
    description: `event to invoke ${FUNCTION_NAME}`,
    ruleName: "cdk-test-rule",
    targets : [
              eventTarget
    ],
    schedule: awsEvents.Schedule.rate(EVENT_MEETING_SYNC_RATE)
});
```

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by baumannalexj** [comment]
Hello @rix0rrr !

If this functionality already exists, let me know. I wasn't able to find it in the documentation.

**Comment by rix0rrr** [comment]
Try `Alias.fromAliasAttributes()` or `Version.fromVersionArn/fromVersionAttributes()`

**Comment by baumannalexj** [comment]
@rix0rrr can you elaborate with an example; your suggestion seems to be providing an interface for EventSources, not EventBridge Rules.

Do you mean when creating the rule, pass the lambdafunction created from Version, not from the lambdafunction created in the CDK?

```
lambdaFromVersion = lambdacdk.Version.fromVersionArn( `${previously-created-lambda-arn}:${currentVersion}`)

new awsEventsTargets.LambdaFunction(lambdaFromVersion ...)
```

**Comment by baumannalexj** [comment]
@rix0rrr can we reopen please? 

This approach does not seem to fix the issue -- I tried getting the function from the alias to use as a parameter

```
const lambdaAlias
        
        = new lambda.Alias(this, generateConstructName(`dev-alias`), {
            aliasName: "DEV",
            version: lambdaFunction.currentVersion,
            description: DATETIME_ISO
        });
        
const eventTarget = new awsEventsTargets.LambdaFunction(**lambdaAlias.lambda**, {
            event: awsEvents.RuleTargetInput.fromObject(meetingSyncEvent)
        });

        const eventRule = new awsEvents.Rule(this, generateConstructName("event-rule"), {
            enabled: true,
            description: `event to invoke GET /meeting/sync for ${FUNCTION_NAME}`,
            ruleName: "gemstone-sync-meetings-CDKTEST",
            targets: [
                eventTarget
            ],
            schedule: awsEvents.Schedule.rate(EVENT_MEETING_SYNC_RATE)
        });
```

but the rule still targets the base Function ARN, not the Alias ARN.

**Comment by baumannalexj** [comment]
Thank you @rix0rrr 

I noticed `IAlias` extends `IFunction`

Once I created an alias, I passed the alias object into the event rule: 
```
 const eventTarget = new awsEventsTargets.LambdaFunction(lambdaAlias, {
            event: awsEvents.RuleTargetInput.fromObject(meetingSyncEvent)
        });
        ```

**Comment by sowston** [comment]
This issue is not resolved.  I have attempted the following:
`const eventTarget = new awsEventsTargets.LambdaFunction(lambdaAlias, {
            event: awsEvents.RuleTargetInput.fromObject(meetingSyncEvent)
        });
`

This still targets the lambda and not the alias.

I have also attempting trying to set an "alias" Property of the EventRule using the methodology suggested above:

`
lambda_event_rule = _events.Rule(
                self,
                id=args["rule_name"],
                event_bus=_events.EventBus.from_event_bus_name(scope=self, id=args["event_bus_id"], event_bus_name=args["event_bus_name"]),
                rule_name=args["rule_name"],
                event_pattern=args["event_rule_patterns"][0],
                targets= [_targets.LambdaFunction(self.function,
                            max_event_age=Duration.hours(2),
                            retry_attempts=2
                )],
                alias=self.alias.fromAliasAttributes()
            )
`
The rule gets created but never sets the "configure version/alias Option of the Rule, it still is generated as "Default" option.

The event rule will trigger, but the lambda is never invoked.  If I manually change the alias rule option to the name of the alias in the UI, the rule will then invoke the lambda.  

The request is is to please enable the "version" and/or "alias" options above as requested and please provide a working code sample.

**Comment by alexanderbaumann-toast** [comment]
@sowston see if this works for you https://stackoverflow.com/a/65786727/6791342
