### ISSUE TITLE
(cli): Init support for custom templates

### ISSUE THREAD

**Issue by 1davidmichael** [aws/aws-cdk#12535]
The SAM CLI allows custom cookiecutter templates to be used to generate your own projects based on a source repo. It would be really nice to have similar functionality for the CDK.

`sam init` documentation: <https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-init.html>

### Use Case

This would enable organizations to create their own CDK templates that embed best practices in them or include configuration files for CI/CD processes.

### Proposed Solution

Initially, this could just be used to pull the templates from a local repo and later could be expanded to use git repositories.

```bash
cdk init --language python --template /path/to/template/dir
```

If this was added the `versionedTemplatesDir` function could be overridden and the specified directory could be used instead.

https://github.com/aws/aws-cdk/blob/master/packages/aws-cdk/lib/init.ts#L197-L208

### Other

* [X] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
Unsure why you would want `cdk init` to use these templates; why wouldn't you just run `cookiecutter` directly?

**Comment by 1davidmichael** [comment]
@rix0rrr my thought was to have similar parity with SAM but I can use cookiecutter or some other tool to create my own. Feel free to close this issue if that is the preferred way to handle it.

**Comment by rix0rrr** [comment]
I'd prefer not too mix too many concerns into one tool, especially if there's already another tool out there that can do the same thing.
