### ISSUE TITLE
aws-ecs-patterns: Add CircuitBreaker pattern for ApplicationLoadBalancedFargateService

### ISSUE THREAD

**Issue by pepastach** [aws/aws-cdk#12534]
The [ApplicationLoadBalancedFargateService](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs-patterns.ApplicationLoadBalancedFargateService.html) ECS pattern currently does not support the [new CircuitBreaker functionality](https://aws.amazon.com/blogs/containers/announcing-amazon-ecs-deployment-circuit-breaker/). Anyone who wants to use is is currently forced to use lower-level constructs ([FargateService](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs.FargateService.html))

### Use Case

Automatic rollback of failing deployments.

### Proposed Solution

Add CircuitBreaker support to the higher-level constructs such as [ApplicationLoadBalancedFargateService](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs-patterns.ApplicationLoadBalancedFargateService.html).

### Other

Related to #12360

---

This is a :rocket: Feature Request

**Comment by rectalogic** [comment]
Is there any way to set this using `addOverride` escape hatch? We can access the `FargateService` on [ApplicationLoadBalancedFargateService.service](https://docs.aws.amazon.com/cdk/api/latest/typescript/api/aws-ecs-patterns/applicationloadbalancedfargateservice.html#aws_ecs_patterns_ApplicationLoadBalancedFargateService_service) but it has no `node.defaultChild` Cfn resource to add overrides to.

**Comment by aka47** [comment]
@rectalogic - I tried this one:

```
const cfnService = this.loadBalancedFS.node.tryFindChild('Service') as ecs.CfnService
cfnService.deploymentConfiguration = {
            maximumPercent:  200,
            minimumHealthyPercent:  50,
            deploymentCircuitBreaker:  {
                enable: true,
                rollback: true,
            }
}
```
But it does not seem to work. 

@SoManyHs it would be helpful to just have something like:

```
new ecs_patterns.ApplicationLoadBalancedFargateService(this, `ALB-FS-${id}`, {
    serviceOptions: FargateServiceProps,
    taskImageOptions...
}
```
Right now they are all passed on first level, makes it more complicated than it should be..

**Comment by rectalogic** [comment]
I was able to set it via an override like this (Python):
```python
        service = ecs_service.service.node.try_find_child("Service")
        assert isinstance(service, ecs.CfnService)
        service.add_property_override(
            "DeploymentCircuitBreaker",
            ecs.CfnService.DeploymentCircuitBreakerProperty(
                enable=True,
                rollback=True,
            ),
        )
```
