### ISSUE TITLE
(codepipeline): Default Artifact Encryption key is not AWS Managed

### ISSUE THREAD

**Issue by Schavras** [aws/aws-cdk#12547]
Based on the [docs](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-codebuild.PipelineProject.html#encryptionkey), when the encryptionKey attribute is not set, codebuild should use `The AWS-managed CMK for Amazon Simple Storage Service (Amazon S3)`, but it creates a new Customer Managed key.

### Reproduction Steps
```ts
const project = new PipelineProject(this, `Project`, {});
  const sourceOutput = new Artifact();
  const sourceAction = new GitHubSourceAction({/**...*//.});
const buildOutput = new Artifact();
const buildAction = new CodeBuildAction({
    actionName: 'CodeBuild',
    project,
    input: sourceOutput,
    outputs: [buildOutput]
});

const pipeline = new Pipeline(this, `Pipeline`, {
    pipelineName: `Pipeline`,
    stages: [
    {
	 stageName: 'Source',
         actions: [sourceAction],
    },
    {
	 stageName: 'Build',
	 actions: [buildAction],
    
    }, ],
});

```

### What did you expect to happen?

On the artifact page on codebuild, the encryption key should something like `arn:aws:kms:REGION:ACCOUNTID:alias/aws/s3` and no customer key to be created. 

### What actually happened?

A resource with type `AWS::KMS:Key` and name like `XXXArtifactsBucketEncryptionKeyXXXX` was created, and in the artifact page the code build was using this key. 

### Environment

  - **CDK CLI Version  : 1.85.0**
  - **Framework Version:**
  - **Node.js Version*v12.14.1**
  - **OS               :Windows 10**
  - **Language (Version):TypeScript (3.9.7)**

### Other

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hello @Schavras ,

the reason there's a Key there is because you're using CodePipeline, which does create a Key by default. If you want to turn off that behavior, either pass your own unencrypted S3 Bucket to the Pipeline as the `artifactBucket` property, or pass the [`crossAccountKeys` property](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-codepipeline.PipelineProps.html#crossaccountkeys) as `false`.

Thanks,
Adam

**Comment by Schavras** [comment]
Hello @skinny85 ,

Thanks for the quick answer. I can confirm that with crossAccountKeys it works as expected! It loooks like I was looking on the wrong place for the solution.
