### ISSUE TITLE
CDK fails when creating gateway endpoint

### ISSUE THREAD

**Issue by ozahavi** [aws/aws-cdk#12548]
CDK that creates VPC endpoints (both gateway and interface) fails.
The error message - "Cannot create a VPC Endpoint with no subnets".
The VPC is imported using fromLookup.

When removing the gateway endpoint and running the CDK it finishes successfully. After the CDK successfully finishes the gateway endpoint can now be added to the CDK and then re-run successfully finishing (i.e only after the 'cdk.context.json' is generated does the gateway endpoint succeed).

### Reproduction Steps

    const vpc = ec2.Vpc.fromLookup(this, 'feVpc',{isDefault: false,vpcId: VPCID]});
    let vpcS3Props = {
      service: ec2.GatewayVpcEndpointAwsService.S3,
      subnets: [{subnetType: ec2.SubnetType.ISOLATED}]
    }
    vpc.addGatewayEndpoint('vpcS3Endpoint',vpcS3Props);

### What did you expect to happen?

The gateway endpoint will be created.

### What actually happened?

Error: "Cannot create a VPC Endpoint with no subnets".

### Environment

  - **CDK CLI Version  : 1.84.0**
  - **Framework Version:**
  - **Node.js Version: 12.18.3** 
  - **OS: macOS BigSur**
  - **Language (Version): 3.9.7** 

### Other

--- 

This is :bug: Bug Report

**Comment by YikaiHu** [comment]
HI @ozahavi , do you find the solution for this issue?
