### ISSUE TITLE
Lambda Code: TypeScript Function Support

### ISSUE THREAD

**Issue by revmischa** [aws/aws-cdk#12553]
I would like to be able to write my lambda functions in TypeScript, not JavaScript.
It is 2021, we should be using typed languages.
I can do it with https://github.com/cloudeninc/clouden-cdk-aws-lambda-typescript, but this should be built in. The CDK is in TS, why not my lambda functions?

### Use Case

I want to write less buggy lambda functions.

### Proposed Solution

See https://github.com/cloudeninc/clouden-cdk-aws-lambda-typescript

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by DaWyz** [comment]
@revmischa , it's already the case when using The [`NodeJsFunction` construct](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-lambda-nodejs-readme.html).

> This file is used as "entry" for esbuild. This means that your code is automatically transpiled and bundled whether it's written in JavaScript or TypeScript. Alternatively, an entry file and handler can be specified:

```ts
new lambda.NodejsFunction(this, 'MyFunction', {
  entry: '/path/to/my/file.ts', // accepts .js, .jsx, .ts and .tsx files
  handler: 'myExportedFunc'
});
```

**Comment by revmischa** [comment]
Thank you @DaWyz, I didn't realize that from the Serverless application tutorial I was doing https://docs.aws.amazon.com/cdk/latest/guide/serverless_example.html
