### ISSUE TITLE
(route53) changing id of RecordSet fails 

### ISSUE THREAD

**Issue by danilobuerger** [aws/aws-cdk#12564]
When changing the id of a RecordSet, the following deploy fails with:

> [Tried to create resource record set [name='example.com.', type='A'] but it already exists]

### Reproduction Steps

1. Deploy with
```
new ARecord(this, "FirstID", { recordName: "example.com", target, zone });
```

2. Deploy with
```
new ARecord(this, "SecondID", { recordName: "example.com", target, zone });
```

### What did you expect to happen?

I expected to be able to change the id of a record (for example when restructuring code and its now nested differently) without the deploy breaking.

### What actually happened?

The deploy breaks as CloudFormation sees this as a new resources, tries to create it and fails because the old record set is still there and blocking the update.

### Environment

  - **CDK CLI Version  :** 1.85.0
  - **Framework Version:** 1.85.0
  - **Node.js Version:** 15.5.1
  - **OS               :** Mac
  - **Language (Version):** TypeScript

### Other

--- 

This is :bug: Bug Report

**Comment by njlynch** [comment]
This is a known limitation of the way these IDs are handled and interpreted by CloudFormation under the hood.

If you've simply refactored some code, which has caused the logical ID to change when you didn't necessarily want it to, you can override the logical ID back to whatever it was before to work around this.

```
const record = new ARecord(this, "SecondID", { recordName: "example.com", target, zone });
(record.node.defaultChild as CfnRecordSet).overrideLogicalId('FirstID');
```

**Comment by leonelgalan** [comment]
@njlynch thanks for your insight! I'm new to the CDK ecosystem. What if we want to change the logical ID? Is destroying the only option? 

1. `cdk destroy`
2. Rename
3. `cdk deploy`

**Comment by erikerikson** [comment]
As a workaround, you can:

1. comment out the record
2. deploy
3. uncomment the record
4. change the record logical ID
5. deploy

Obviously DNS will be in a bad state between the deletion and recreation, you'll need to thoughtfully consider the consequences.
