### ISSUE TITLE
(many): a number of stateful resources don't have a removal policy

### ISSUE THREAD

**Issue by rix0rrr** [aws/aws-cdk#12563]
- [ ] AWS::CloudFormation::Stack
- [x] AWS::Cognito::UserPool
- [x] AWS::DocDB::DBInstance
- [x] AWS::EC2::Volume
- [x] AWS::Elasticsearch::Domain
- [x] AWS::FSx::FileSystem
- [x] AWS::SQS::Queue

--- 

This is :bug: Bug Report

**Comment by PatMyron** [comment]
To clarify, does this mean they don't have a default removal policy explicitly set? Or removal policy cannot be set at all? If the latter, I'd prefer a resource type agnostic fix since there are always going to be new stateful resource types

**Comment by rix0rrr** [comment]
They don't have one by default. You can always set a RemovalPolicy via Escape Hatching:

```ts
(myResource.node.defaultChild as CfnResource).applyRemovalPolicy(...);
```

**Comment by jotompki** [comment]
Any way to surface this in docs/is this called out anywhere?

See some customers having issues with [this thinking it is a settable property](https://stackoverflow.com/questions/62142524/is-there-a-way-to-specify-cloudformation-stack-deletion-policy-using-aws-cdk) by default and not aware of the method to apply it after creation.

**Comment by Jerry-AWS** [comment]
We have this in the Developer Guide: https://docs.aws.amazon.com/cdk/latest/guide/resources.html#resources_removal

However, we don't have a list of resources that this applies to. I'm loath to include such a list because it can easily become outdated.

**Comment by Jerry-AWS** [comment]
I went ahead and added the list.

**Comment by rix0rrr** [comment]
I actually don't agree with `AWS::CloudFormation::Stack`.

**Comment by rix0rrr** [comment]
Also... not sure that I agree with `AWS::SQS::Queue`... but for a different reason

**Comment by PatMyron** [comment]
I think I misinterpreted this issue as making sure `removalPolicy` can be set at all from something @jotompki mentioned

---

I think inconsistent and changing defaults are confusing and a false sense of safety

Customers are going to have higher bills and limits are going to start being hit with resources being retained/snapshotted all of a sudden, singleton resource types that get replaced all of a sudden can't be updated anymore, etc.

**Comment by rix0rrr** [comment]
If we just say `removalPolicy` *can* be configured, but it doesn't have to be (and it defaults to `Delete`), then we're back in the situation where CloudFormation left us, which is EXACTLY the point we're trying to avoid.

Here are the options as far as I see them:

| Description | Default | cfn-lint | Notes |
|----|----|-----|-----|
| 1. Don't emit a value | CFN default = Delete | will yell at you | Effectively 4, but without tool support |
| 2. Do emit a value | Delete | happy | We are now emulating CloudFormation in the *before* cfn-lint days (= dangerous) |
| 3. Do emit a value | Retain | happy | Maximum safety, but deployments will fail if you gave physical names to your resource. |
| 4. Require user to select | - | happy | Compatibility breaking change |

There really are no good solutions here.
