### ISSUE TITLE
(s3): Add support for transfer acceleration

### ISSUE THREAD

**Issue by pdlug** [aws/aws-cdk#12570]
The S3 module does not currently have support for setting [transfer acceleration status](https://docs.aws.amazon.com/AmazonS3/latest/dev/transfer-acceleration.html) on a bucket. Cloudformation already has support for this [AWS::S3::Bucket AccelerateConfiguration](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-accelerateconfiguration.html)

### Use Case

Needed to enable transfer acceleration on S3 bucket.

### Proposed Solution

Propose adding an enum for `TransferAccelerationStatus`:

```typescript
export enum TransferAccelerationStatus {
  /**
   * Transfer acceleration is suspended.
   */
  Suspended = 'Suspended',
  /**
   * Transfer acceleration is enabled.
   */
  Enabled = 'Enabled',
}
```

Along with support in construct props for `Bucket`:

```typescript
const bucket = new s3.Bucket(this, "uploads", {
  accelerationStatus: s3.TransferAccelerationStatus.Enabled,
  // ...
});
```

associated property:

```typescript
transferAccelerationStatus
```

and method:

```typescript
public configureTransferAcceleration(status: TransferAccelerationStatus): void

s3.configureTransferAcceleration(s3.TransferAccelerationStatus.Enabled);
```

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by ffxsam** [comment]
Any suggestions on how we should work around this, since CDK doesn't support it? Other than just enabling it manually via the AWS Console? Or is there some sort of under-the-hood way of defining this in our CDK scripts?

**Comment by TheAksh** [comment]
Two options until this issue is implemented/resolved:
1. You can enable it every time in the code that calls the S3 method. (the one that uses aws-sdk)
2. Enable it manually via AWS Console (but this setting will reset every time CDK Deployment happens)

**Comment by ffxsam** [comment]
Regarding #1: I don't think that'll work. Transfer acceleration has to be enabled first for the bucket, before you can use it in S3 API calls.

This means the code would have to use [PutBucketAccelerateConfigurationCommand](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-s3/classes/putbucketaccelerateconfigurationcommand.html) in the runtime code.

Not sure either of these options is better than the other. I'm surprised CDK went live without this option.

**Comment by christophgysin** [comment]
Since it is [supported by Cloudformation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-accelerateconfiguration.html) you can use [Escape hatches](https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html).

**Comment by ffxsam** [comment]
Perfect, thank you! Looks like `addPropertyOverride` is what I need.

**Comment by christophgysin** [comment]
That would work, allthough `addPropertyOverride` is meant for properties that are supported by CloudFormation but missing from the spec. In this case it's even possible to set the property in a type-safe way:
```typescript
const bucket = new s3.Bucket(this, 'Bucket')
const cfnBucket = bucket.node.defaultChild as s3.CfnBucket
cfnBucket.accelerateConfiguration = {
  accelerationStatus: 'true',
}

**Comment by ffxsam** [comment]
Thanks! I definitely would not have figured that out on my own.

**Comment by ffxsam** [comment]
One quick note: that should be:

```ts
accelerationStatus: 'Enabled',
```

**Comment by christophgysin** [comment]
Thanks, fixed the example.

**Comment by jumic** [comment]
@otaviomacedo I ping you here because new issues related to S3 will be assigned to you at the moment.
I could submit a PR for this feature. Can you give me a short feedback which option you prefer.
- New enum `TransferAccelerationStatus` as proposed in the original message of this feature request?
- New boolean property `transferAcceleration` which can be used to enable transfer acceleration. The CloudFormation configurations for [transfer acceleration](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-accelerateconfiguration.html) and [bucket versioning](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-versioningconfig.html) follow the same structure. For versioning, CDK uses a boolean property. Because of that, it could be an option to use a boolean property for transfer acceleration, too.

Thanks.
