### ISSUE TITLE
(cloudwatch) System.ArgumentException : Could not infer JSII type for .NET type 'IWidget' (Parameter 'type')

### ISSUE THREAD

**Issue by ChristopheVico** [aws/aws-cdk#12587]
When trying to create a Dashboard using Dashboard props and IWidget Jagged array in the props, the unit test fail with error:
System.ArgumentException : Could not infer JSII type for .NET type 'IWidget' (Parameter 'type')

(dotnet build will compile the code successfully, while the App.Synth will fail)

Create the dashboard empty & adding the widget using the AddWidgets method works as expected.

### Reproduction Steps
        public IResource CreateCloudWatchDashboard()
        {
        IWidget[][] widgets = new IWidget[1][]; 
        
        widgets[0]= new IWidget[1];

        widgets[0][0] = new LogQueryWidget (new LogQueryWidgetProps() {
            Height=6,
            Width=24,
            LogGroupNames=new []{"/some/valid/groupname"},
            Title="Task Activity Logs",
            QueryLines=new []{"some valid Query lines"},
            View=LogQueryVisualizationType.TABLE,
            Region="a valid region code"
        });

        var myDashboard = new Dashboard(Scope,  "dashboard", new DashboardProps()
        {
            DashboardName="Some Name",
            Widgets= widgets 
        
        } );
        return null;
       }

### What did you expect to happen?

App.Synth() generates a valid CloudFormation template.

### What actually happened?

System.ArgumentException : Could not infer JSII type for .NET type 'IWidget' (Parameter 'type')

### Environment

  - CDK CLI Version  : 1.85.0
  - Framework Version:  .NET Core 3.1.11
  - Node.js Version: 14.15.2
  - OS               : Windows 10 64bits
  - Language (Version): C#

### Other

The following code will work as expected:

        public IResource CreateCloudWatchDashboard()
        {
        IWidget[][] widgets = new IWidget[1][]; 
        
        widgets[0]= new IWidget[1];

        widgets[0][0] = new LogQueryWidget (new LogQueryWidgetProps() {
            Height=6,
            Width=24,
            LogGroupNames=new []{"/some/valid/groupname"},
            Title="Task Activity Logs",
            QueryLines=new []{"some valid Query lines"},
            View=LogQueryVisualizationType.TABLE,
            Region="a valid region code"
        });

        var myDashboard = new Dashboard(Scope,  "dashboard", new DashboardProps()
        {
            DashboardName="Some Name"
        
        } );
        myDashboard.AddWidgets(widgets[0][0]);

        return null;
       }

--- 

This is :bug: Bug Report

**Comment by RomainMuller** [comment]
Thanks for reporting. I will have a look into this.
