### ISSUE TITLE
(aws_dynamodb): What is the purpose of the `scope` and `id` parameters to Table?

### ISSUE THREAD

**Issue by l0b0** [aws/aws-cdk#12582]
The [API documentation for `Table`](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_dynamodb/Table.html#aws_cdk.aws_dynamodb.Table) does not explain the purpose of `scope` and `id`, and the [upstream documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html) doesn't mention either property. The code is using too much dynamic dispatch for me to find where the `id` parameter is used. 

As a secondary issue the default value for `table_name` is missing. Is `id` used as the table name if `table_name` is unspecified.

---

This is a 📕 documentation issue

**Comment by NetaNir** [comment]
Scope and id are general CDK concepts, they are mentioned in the AWS CDK [basic concepts docs:](https://docs.aws.amazon.com/cdk/latest/guide/constructs.html#constructs_init)

> Scope – The construct within which this construct is defined. You should usually pass this for the scope, because it represents the current scope in which you are defining the construct.

> id – An identifier that must be unique within this scope. The identifier serves as a namespace for everything that's defined within the current construct and is used to allocate unique identities such as resource names and AWS CloudFormation logical IDs.

The table name, if not provided is set by CloudFormation - see [docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html#cfn-dynamodb-table-tablename).
