### ISSUE TITLE
(core) Applying tags through Tags Class doesn't update the construct's tags

### ISSUE THREAD

**Issue by tom-beatdapp** [aws/aws-cdk#12601]
Applying tags through Tags Class (Aspects) doesn't update the construct's TagManager.

### Reproduction Steps

Reproduce like so:

```
import { Stack, Tags } from "@aws-cdk/core";

const testStack = new Stack();
Tags.of(testStack).add("test","test");
testStack.tags.hasTags(); // false
testStack.tags.renderTags(); // []
testStack.tags.tagValues(); // {}

testStack.tags.setTag("test2", "test2");
testStack.tags.hasTags(); // true
testStack.tags.renderTags(); // [ { Key: 'test2', Value: 'test2' } ]
testStack.tags.tagValues(); // { test2: 'test2' }
```

### What did you expect to happen?

I expect the construct's TagManager to show the tags exist, like this:

```
const testStack = new Stack();
Tags.of(testStack).add("test","test");
testStack.tags.hasTags(); // true
testStack.tags.renderTags(); // [ { Key: 'test', Value: 'test' } ]
testStack.tags.tagValues(); // { test: 'test' }
```

## Extra note:
- the `Tags.of` tags are correctly applied to stack + resources upon deploying with `cdk deploy`.

### Environment

  - **CDK CLI Version  :** 1.84.0 
  - **Framework Version:**
  - **Node.js Version:** v12.16.2
  - **OS               :** MacOS
  - **Language (Version):** TypeScript (3.8.3)

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
Your code cannot be written to inspect the tags that have been applied so far. If that is what you need, please describe that with a use case and file it as a feature request.
