### ISSUE TITLE
(ecr): add option to auto delete images upon ECR repository removal

### ISSUE THREAD

**Issue by kirintwn** [aws/aws-cdk#12618]
### Use Case

ECR repositories currently do not get delete if they contain images even the `removalPolicy` is set to `DESTROY`.

It was reported in #2765, and was thought to be a responsibility of CloudFormation team https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/515.

### Proposed Solution

I do think we should add a option to force delete the images using custom resource provider, which is just like #12090 that uses a custom resource provider to delete objects in s3.

The code might looks like this:
```typescript
const bucket = new ecr.Repository(this, 'Repo', {
  repositoryName: 'delete-even-if-contains-images',
  removalPolicy: cdk.RemovalPolicy.DESTROY,
  autoDeleteImages: true,
});
```

The props `autoDeleteImages` can only to be true if `removalPolicy` is set to `DESTROY`.

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by kirintwn** [comment]
I have created a [branch](https://github.com/kirintwn/aws-cdk/tree/ecr-auto-delete-images) to show how it works. Note that the unit tests are not completed because I think we better wait until #12620 get merged.

**Comment by MrArnoldPalmer** [comment]
hey @kirintwn, would you be interested in publishing this as a separate module? There definitely is a need and it would be a good way to get some users testing it before merging into the CDK. It may be possible to extend the existing ecr.Repository class and intercept this prop and then create the custom resource.

**Comment by heiba** [comment]
@kirintwn any chance we can publish your branch if it's fully working ? we need this feature terribly.

**Comment by heiba** [comment]
@MrArnoldPalmer is there anyway the CDK team can help on publishing this feature ?

**Comment by kirintwn** [comment]
Hi @heiba , I have updated my branch, added more tests & opened a PR #15932.

**Comment by nemmison** [comment]
Any update or workaround for this?

**Comment by mikaeelkhalidnbs** [comment]
do we have any updates on this feature?

**Comment by JessieWadman** [comment]
This would be very nice. Constantly running into issues because of lack of this.

**Comment by MikeGongolidis** [comment]
We would really appreciate such an option!

**Comment by kushal-ti** [comment]
We really need this feature as well, would be a huge help

**Comment by ozgenbaris1** [comment]
please add this feature

**Comment by amirse** [comment]
indeed, please add.

**Comment by madeline-k** [comment]
To whoever ends up implementing this, be mindful of this issue: https://github.com/aws/aws-cdk/issues/16603 We don't want to end up with the same problem.

**Comment by missourian55** [comment]
Tested this feature this morning with cdk 2.70.0. I am still seeing the error

```
Resource handler returned message: "The repository with name 'test-app' in registry with id '1234567890' cannot be deleted because it still contains images (Service: Ecr, Status Code: 400,
Request ID: 842c370d-f12344XXXXX-ed47d07f0443)" (RequestToken: c64e0c80-9xxxxxxca5006c6c, HandlerErrorCode: GeneralServiceException)
```

**Comment by markmansur** [comment]
This is now supported by CloudFormation 
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecr-repository.html#cfn-ecr-repository-emptyondelete

Do we still need this custom resource?
