### ISSUE TITLE
CDK CLI and Cloud Assembly Version Mismatch issue.....

### ISSUE THREAD

**Issue by vikrantsundriyal** [aws/aws-cdk#12612]
Hi,
Am unable to figure out the compatibility matrix of @aws-cdk/core" and cdk cli.
Its weird but no matter what combination i try am ending up with below error:
This CDK CLI is not compatible with the CDK library used by your application. Please upgrade the CLI to the latest version.
(Cloud assembly schema version mismatch: Maximum schema version supported is 7.0.0, but found 8.0.0)

Here are the steps:
1) Login to CodeArtifact repo.
2) Copy package from my repo. package.json is copied below.
3) npm install
4) npm run build (since its a lambda repo)
5) cdk synth 
6) cdk deploy

package.json
  "dependencies": {
    "@aws-cdk/aws-appsync": "^1.81.0",
    "@aws-cdk/aws-ec2": "^1.81.0",
    "@aws-cdk/aws-iam": "^1.81.0",
    "@aws-cdk/aws-lambda": "^1.81.0",
    "@aws-cdk/aws-logs": "^1.81.0",
    "@aws-cdk/core": "^1.81.0",
    "dotenv": "^8.2.0",
    "fs": "0.0.1-security",
    "source-map-support": "^0.5.16"
  }

CLI version- + aws-cdk@1.85.0

Other version combinations which gave same error:
1) Have tried above package.json with even other cdk version (1.81.0 (build 6ef67c7)), got same error.
2) Have tried changing package.json versions to 1.85 with cdk version (1.81.0 (build 6ef67c7) & 1.85.0), got same error.

Please assist how to fix and where can i see this CLI to assemble version mapping. 

Thanks
Vikrant

### Environment

  - **CDK CLI Version:** 
  - **Module Version:** 
  - **Node.js Version:** 
  - **OS:** 
  - **Language (Version):**

**Comment by NetaNir** [comment]
The CLI version must always be greater than the Framework version.

**Comment by vikrantsundriyal** [comment]
Thanks @NetaNir , In that case my initial deploy should not fail. I was running framework @81 and CLI @85.
Where are these versions cached  ? Am using Amazon Linux, other versions:
npm- 6.14
node-v14.15
cdk - 1.85
package.json "@aws-cdk/core": "^1.81.0",

WIll it matter if my npm is linked to Private AWS Code Artifact which has npm store as upstream repo ?

**Comment by NetaNir** [comment]
I suspect that you are not using CDK CLI version 1.85.0 but an earlier version. The `aws-cdk` declares a dependency on the `@aws-cdk/cloud-assembly-schema` module, see [code](https://github.com/aws/aws-cdk/blob/master/packages/aws-cdk/package.json#L70).
When the AWS CDK is released, all of the modules are released together and their dependencies are update to the same released version.  In the CDK CLI case (the aws-cdk module), this means that version `1.85.0` of the module,  will declare a dependency on `@aws-cdk/cloud-assembly-schema` version `1.85.0`. The version file of version 1.85.0 of the `@aws-cdk/cloud-assembly-schema`:

https://github.com/aws/aws-cdk/blob/5f446681aa8ae9867f8ca03d48916a05736ee62e/packages/%40aws-cdk/cloud-assembly-schema/schema/cloud-assembly.version.json#L1

Which means that if version `1.85.0` of  the aws-cdk module is installed you will not see the error.

**Comment by 1kings** [comment]
Solved! exact same issue, mine version 1.86.0  `npm i -g aws-cdk@latest` is pointless.
Solution: downgrade run `cdk --version` use output version (got 1.82.0) to update all aws-cdk dependencies in package.json
