### ISSUE TITLE
Facing an issue in AWS CDK pipelines

### ISSUE THREAD

**Issue by geshugoyal** [aws/aws-cdk#12629]
Facing an issue in AWS CDK pipelines, where builds are failing with the following error:

toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit

I need a way to authenticate it from ECR in place of the default docker image it uses or other guidance on how to circumvent this issue.

### Environment

  - **CDK CLI Version:** 1.78.0
  - **Language (Version):** Python 3

**Comment by NetaNir** [comment]
Duplicate https://github.com/aws/aws-cdk/issues/10999
