### ISSUE TITLE
Inconsistent error behavior when using Table together with CfnTable

### ISSUE THREAD

**Issue by andreimcristof** [aws/aws-cdk#12634]
Lack of `KeySchema` and `AttributeDefinitions` on the `Table` construct forces me to use a mix of `Table` and `CfnTable`, which causes `cdk synth` to complete successfully, but `cdk deploy` to fail. I expect consistency - both commands should either fail or be successful. Please see details below.

### Reproduction Steps

```typescript
let tbl = new Table(scope, withAppname("table"), {
    tableName: appConstants.dynamoDb.tableName,
    billingMode: BillingMode.PAY_PER_REQUEST,
    partitionKey: { name: "pk", type: AttributeType.STRING },
    encryption: TableEncryption.AWS_MANAGED,
    stream: StreamViewType.NEW_IMAGE,
  } as TableProps);

  const cfnTable = tbl.node.defaultChild as CfnTable;

  cfnTable.addPropertyOverride("KeySchema", [
    {
      attributeName: "pk",
      keyType: "HASH",
    },
    {
      attributeName: "sk",
      keyType: "RANGE",
    },
  ]);
  cfnTable.addPropertyOverride("AttributeDefinitions", [
    {
      attributeName: "pk",
      attributeType: "S",
    },
    {
      attributeName: "sk",
      attributeType: "S",
    },
    {
      attributeName: "data",
      attributeType: "S",
    },
  ]);

  cfnTable.addPropertyOverride("GlobalSecondaryIndexes", [
    {
      indexName: "gsi_1", 
      keySchema: [
        {
          attributeName: "sk",
          keyType: "HASH",
        },
        {
          attributeName: "data",
          keyType: "RANGE",
        },
      ],
      projection: {
        projectionType: "ALL",
      },
    },
  ]);
```

### What did you expect to happen?

I would like to see some consistency:
- Ideally, I would like the L2 `Table` Construct to expose `keySchema` and `attributeDefinitions` just like the L1 `CfnTable`, as I think these two properties are "high-level" enough (philosophical discussion probably), but there probably is a deliberate decision and reasoning of them not being exposed by Table. 
- In the absence of that, I expect both `cdk synth` and `cdk deploy` to at least either fail together or be successful together. 

I am learning the PROPER way to use DynamoDB. this is done with index overloading. I am following a tutorial [here](https://www.trek10.com/blog/dynamodb-single-table-relational-modeling). In this tutorial it's explained how to do index overloading: 

> Step 2: Create a DynamoDB table with three generic attributes: “partition key”, “sort key”, **and “data”**

> The three generic attributes will be used to support two indexes: the main table index which uses pk as the partition and sk as the sort key, and a global secondary index which uses sk as the partition **and data as the sort**.

As you can see, the tutorial demands advanced configuration of `keySchema` and `attributeDefinitions` in order to add a 3rd attribute definition called `data`. To do this, I cannot use the L2 `Table` construct because it does not expose these props: I must instead use the `CfnTAble` construct. But I still need the convenience methods of the `Table` for other things such as adding permissions. So as my code sample shows, I used a mix of both.   

### What actually happened?

What happens is that the `cdk synth` command completes and outputs the synth'ed script, but the `cdk deploy` command fails with the error: 

> Encountered unsupported property attributeType

....which is confusing behavior. 

> Encountered unsupported property attributeType

### Environment

  - **CDK CLI Version  :** 1.85.0 (build 5f44668)
  - **Framework Version:**  
  - **Node.js Version:**  v12.11.1
  - **OS               :** Linux Ubuntu
  - **Language (Version):**  Typescript 3.7.3

### Other

I have also asked on SO, but rather answered my own question there. However, it STILL does not work because of the error above. 
https://stackoverflow.com/questions/65812390/how-to-add-add-a-3rd-indexable-attribute-to-dynamodb-through-the-cdk

--- 

This is :bug: Bug Report

**Comment by andreimcristof** [comment]
I think this can actually be closed. It's most probably a very specific scenario and not prio to ensure smooth Table / CfnTable working together. I will just stick to CfnTable for my needs. 👍

**Comment by andreimcristof** [comment]
If someone has this error, I fixed this with another solution.
1. You begin the other way around: define your `CfnTable` first. Add the necessary `AttributeDefinitions` and `KeySchema`.
```typescript 
const cfnTbl = new CfnTable(...)
```
2. Then you create a Table from the **existing** CfnTable resource, like so: 
```typescript
const tbl = Table.fromTableArn(scope, id, cfnTbl.attrArn);
```

**Comment by givsly-stephen** [comment]
`cfnTbl.attrArn` vs `tbl.tableArn` blows my mind!  Why the interface inconsistency?

Also `cfnTbl.tableName` vs `tbl.tableName` are different too. Why?
