### ISSUE TITLE
(aws-certificatemanager): Auto assign nameservers to registered domain

### ISSUE THREAD

**Issue by I2olanD** [aws/aws-cdk#12633]
### The Question
Right now i have my domain registered at AWS. When i create my stack and route53 gets setup, it will created new nameservers for it. How do i tell my domain via cdk those nameservers automatically? Otherwise the certificate validation stays in status pending and the stack fails to create after some time.

### Environment

  - **CDK CLI Version:** 1.85.0
  - **Module Version:** 1.85.0
  - **Node.js Version:** 15.5.1
  - **OS:** macOS big sur
  - **Language (Version):** TypeScript (3.9.7)

**Comment by njlynch** [comment]
Setting your domain's name servers is typically a one-time (and manual) setup; any automation would depend on who your domain registrar is and what automated mechanisms -- if any -- they support. See https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/MigratingDNS.html for the Route53 help on this topic.

My suggestion would be to break this up into two steps: first deploy the route53 zone(s) and manually update your name servers, and then add the certificate(s) and other infrastructure as a second deployment. This will give time for the name server changes to propagate.

**Comment by I2olanD** [comment]
@njlynch  Thank you for the awesome explanation!
