### ISSUE TITLE
(s3): Bucket doesn't implement grantPutAcl

### ISSUE THREAD

**Issue by pv93** [aws/aws-cdk#12631]
When used as an Interface, bucket objects throw a compiler error because they do not implement the grantPutAcl method

### Reproduction Steps
```
    const contentStreamsBucket = new s3.Bucket(this, 'ContentStreamsBucket', {
      bucketName: props.contentStreamsBucketName,
    })

    new cloudfront.Distribution(this, 'ContentStreamsCloudfrontDistribution', {
      defaultBehavior: {
        origin: new S3Origin(contentStreamsBucket)
      }
    })
```
### What did you expect to happen?

Should be able to provide an S3 bucket to the distribution object

### What actually happened?

![Screen Shot 2021-01-20 at 12 12 28 PM](https://user-images.githubusercontent.com/7632943/105210398-f7d1da00-5b18-11eb-9830-4c9ed42314b6.png)

### Environment

  - **CDK CLI Version  :** ﻿﻿﻿﻿﻿﻿﻿﻿﻿1.84.0 (build 866c8dc)
  - **Framework Version:** 1.70.0
  - **Node.js Version:**  v15.5.1
  - **OS               :** macOS Big Sur
  - **Language (Version):**  "~3.9.7"

### Other

--- 

This is :bug: Bug Report

**Comment by pv93** [comment]
Fixed, just had to update. Sorry!

**Comment by david-kerins** [comment]
I saw this too and updating aws-cdk node packages from 1.84.0 to 1.86.0 resolved the issue.
