### ISSUE TITLE
(core): Support for file assets (not just directories) when bundling with docker

### ISSUE THREAD

**Issue by paulpearcy** [aws/aws-cdk#12651]
I am attempting to use the S3 assets module to deploy a jar file code asset for AWS lambda. 

Placing the jar file in /asset-output it gets re-zipped when the asset is deployed. Jars are already a zip file so this leads to the lambda failing with a ClassNotFoundException. 

### Reproduction Steps

        code_asset = aws_lambda.Code.from_asset(
            "service",
            asset_hash_type=core.AssetHashType.SOURCE,
            bundling=core.BundlingOptions(
                image=core.BundlingDockerImage.from_registry("public.ecr.aws/l8v7c0k7/maven:3.6-jdk-11-slim"),
                command=[
                    "bash",
                    "-c",
                    "mvn -DskipTests package shade:shade && mv /asset-input/target/test-0.0.1.jar /asset-output,
                ]))

### What did you expect to happen?

The jar to be deployed without zipping. 

### What actually happened?

The jar was zipped.

### Environment

  - **CDK CLI Version  :** 1.85
  - **Framework Version:** ?
  - **Node.js Version:** v10.21.0
  - **OS               :** Mac
  - **Language (Version):** Python (but should apply to all)

### Other

The fix I would recommend is that if there is only a single zip or jar file in the /asset-output dir to skip zipping and use it directly. 

I attempted to work around this by unzipping the contents of my jar to the /asset-output dir, but the jar I am dealing with is quite large and things failed for unknown reasons. This might work for smaller jars. 

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment]
We could apply some heuristics as mentioned by @paulpearcy - but I think it might be worth starting with something more explicit. We could expose a `outputPath` property on `bundling` to tell where to look inside `/asset-output`, from that point onwards our normal asset mechanism would determine that the packaging type is `FILE` and skip the unwanted zipping.

@paulpearcy 

> I attempted to work around this by unzipping the contents of my jar to the /asset-output dir, but the jar I am dealing with is quite large and things failed for unknown reasons.

This should work..I'm wondering what kind of errors you encountered. Feel free to paste some of them here if you have them, maybe we can figure it out.
