### ISSUE TITLE
(ec2): InitElement is implemented by InitFile, but documentation does not state that

### ISSUE THREAD

**Issue by mbp** [aws/aws-cdk#12664]
Referring to these 2 pages:
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ec2.InitFile.html
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ec2.InitElement.html

The first one states:

> class InitFile
[...]
Extends InitElement

The second one states:
> class InitElement
[...]
Implemented by InitCommand, InitGroup, InitPackage, InitService, InitUser

I think InitFile is missing in that list.

---

This is a 📕 documentation issue

**Comment by rix0rrr** [comment]
Huh! Good find!
