### ISSUE TITLE
(aws-cloudwatch): CompositeAlarm missing dependsOn

### ISSUE THREAD

**Issue by mina-asham** [aws/aws-cdk#12662]
The CompositeAlarm L2 doesn't add any of its dependent alarms in the dependsOn clause, causing CloudFormation deploys to fail if it tries to create the CfnCompositeAlarm before any of the dependent CfnCompositeAlarm or CfnAlarm are created.

### Reproduction Steps

```js
const alarm = new Alarm(this, "MyAlarm", {
    evaluationPeriods: 1,
    threshold: 1,
    metric: new Metric({
        namespace: "MyNamespace",
        metricName: "MyMetric"
    })
});

new CompositeAlarm(this, "MyCompositeAlarm", {
    alarmRule: AlarmRule.anyOf(alarm);
});
```

Results in:

```json
{
  "MyAlarm696658B6": {
    "Type": "AWS::CloudWatch::Alarm",
    "Properties": {
      "ComparisonOperator": "GreaterThanOrEqualToThreshold",
      "EvaluationPeriods": 1,
      "MetricName": "MyMetric",
      "Namespace": "MyNamespace",
      "Period": 300,
      "Statistic": "Average",
      "Threshold": 1
    }
  },
  "MyCompositeAlarm0F045229": {
    "Type": "AWS::CloudWatch::CompositeAlarm",
    "Properties": {
      "AlarmName": "BlaMyCompositeAlarmDE492BED",
      "AlarmRule": {
        "Fn::Join": [
          "",
          [
            "(ALARM(",
            {
              "Fn::GetAtt": [
                "MyAlarm696658B6",
                "Arn"
              ]
            },
            "))"
          ]
        ]
      }
    }
  }
}
```

### What did you expect to happen?

The resource `MyCompositeAlarm0F045229` to contains a `dependsOn` array containing the alarm:

```json
"DependsOn": [
  "MyAlarm696658B6"
]
```

### What actually happened?

Well it doesn't, making me do a hack like which I shouldn't need to do with a L2+ construct:

```js
compositeAlarm.node.addDependency(alarm.node.defaultChild as CfnAlarm);
```

### Environment

Don't think any of the below matters but providing anyway

  - **CDK CLI Version:** 1.85.0
  - **Framework Version:** 1.85.0
  - **Node.js Version:**  v12.16.1
  - **OS               :** Mac
  - **Language (Version):**  Typescript (4.1.3)

### Other

N/A

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
Good catch, that's silly.

**Comment by swar8080** [comment]
@mina-asham did the deploy of this stack fail?

I think an implicit dependency is created by `Fn:GetAtt` with:

```
"Fn::GetAtt": [
  "MyAlarm696658B6",
  "Arn"
]
```
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-dependson.html
https://aws.amazon.com/blogs/devops/optimize-aws-cloudformation-templates/

**Comment by mina-asham** [comment]
@swar8080 Ah, you are right, my stack did fail and adding the dependencies fixed it, but not that I looked a bit deeper into it, my stack was failing for something else that I mistook as the missing dependencies! I am resolving this since there is no need for action here, thanks!

**Comment by mina-asham** [comment]
@ckamzn I don't quite recall tbh, that was about 2.5 years ago, but I think the main issues I faced with alarms was that there was a rate limit, and if you deployed a stack with enough new alarms, you can get into failures that might look like missing dependencies.
