### ISSUE TITLE
(ec2): allowAllOutbound on default security group should mimic allowAllTraffic on NAT instance

### ISSUE THREAD

**Issue by f0rr0** [aws/aws-cdk#12673]
Setting `allowAllTraffic` to `false` in `ec2.NatProvider.instance` should set `allowAllOutbound` on the default security group created for the NAT instance.

### Reproduction Steps

```js
ec2.NatProvider.instance({
      instanceType: new ec2.InstanceType('t2.micro'),
      keyName: key.name,
      allowAllTraffic: false,
})
```
### What did you expect to happen?

Default security group associated with NAT instance disallows all outbound connections.

### What actually happened?

All outbound connections are allowed on the default security group.

--- 

This is :bug: Bug Report

**Comment by hedrall** [comment]
This is a comment of allowAllTraffic.
https://github.com/aws/aws-cdk/blob/31b1b3289b99c4ec4ed19c51705d66f0e83783dd/packages/%40aws-cdk/aws-ec2/lib/nat.ts#L150-L162
```
/**
   * Allow all traffic through the NAT instance
   *
   * If you set this to false, you must configure the NAT instance's security
   * groups in another way, either by passing in a fully configured Security
   * Group using the `securityGroup` property, or by configuring it using the
   * `.securityGroup` or `.connections` members after passing the NAT Instance
   * Provider to a Vpc.
   *
   * @default true
   */
```

I also feel that this may be a bit misleading, because it looks like the behavior when allowAllTraffic is false is practically not implemented.

**Comment by f0rr0** [comment]
The way I (and potentially others) use this option is to let CDK generate a default security group and then configure it manually. However this default security group should not have all outbound connections allowed if the flag is explicitly passed.

Pre configuring a security group before creating a NAT instance seems impossible since the preconfigured security group would depend on a VPC which would in turn depend on the NAT instance.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
