### ISSUE TITLE
(api-gateway): Add ability to get UsagePlan from id

### ISSUE THREAD

**Issue by satyamkondle** [aws/aws-cdk#12677]
Add the ability to get usage plan using id, like:
UsagePlan.from_id()

https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_apigateway/UsagePlan.html

### Use Case
We have several microservices in our setup and they use common infrastructure. We want to create the Usage Plan as part of this infrastructure and then allow microservices to add their api stages to this usage plan. For a microservice to do that, it needs to construct the Usageplan from the id they get from infrastructure and then add their api stage to it.

However, there seems no way to get UsagePlan from its id.

### Proposed Solution

Add UsagePlan.from_id() similar to what you have for other constructs

---

This is a :rocket: Feature Request

**Comment by satyamkondle** [comment]
Any idea if and when this could land? If it is going to take time, any workarounds that you can suggest?

**Comment by pirklmar** [comment]
> Any idea if and when this could land? If it is going to take time, any workarounds that you can suggest?

Maybe this could help to solve your issue?
https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_apigateway/RestApi.html#aws_cdk.aws_apigateway.RestApi.add_usage_plan

**Comment by satyamkondle** [comment]
@ericzbeard @nija-at ... we are having to workaround this and are running into unexpected issues with our workarounds. Can this be prioritized since the effort seems to be small?
