### ISSUE TITLE
(ssm): ARN separator error message should provide more detail

### ISSUE THREAD

**Issue by stephenwiebe** [aws/aws-cdk#12682]
## :question: General Issue

After updating from CDK 1.80 to 1.86, I started getting the error message `Unable to determine ARN separator for SSM parameter since the parameter name is an unresolved token. Use "fromAttributes" and specify "simpleName" explicitly` upon synth. It took me quite a while to track down the problem which was due to a 3rd party library I'm using which wasn't working correctly with NestedStacks.

This error message at https://github.com/aws/aws-cdk/blob/31b1b3289b99c4ec4ed19c51705d66f0e83783dd/packages/%40aws-cdk/aws-ssm/lib/util.ts#L43-L45 should have more information provided to assist in resolution - at least the name of the parameter that is attempting to be resolved.

### Environment

  - **CDK CLI Version:** 1.86.0
  - **Module Version:** 1.86.0
  - **Node.js Version:** 
  - **OS:** 
  - **Language (Version):** TypeScript

**Comment by peterwoodworth** [comment]
Can you make a suggestion for what the error message should be instead? I'm not sure why exactly you were getting an error there so I don't really know how we could improve this error message.

**Comment by harnamc** [comment]
I came across a similar issue recently and resolved it using `StringParameter.fromStringParameterAttributes` function. The error message also implies this.

```js
const param = StringParameter.fromStringParameterAttributes(this, 'SomeID', {
        parameterName: "NAME_OF_THE_PARAM || TOKEN_OF_PARAM",
      }).stringValue
```
