### ISSUE TITLE
(aws-eks): KubernetesPatch doesn't restorePatch on update

### ISSUE THREAD

**Issue by foriequal0** [aws/aws-cdk#12685]
### Reproduction Steps

1. Have a KubernetesManifest (m)
1. Create a KubernetesPatch (applyPatch1, restorePatch1) on m & deploy 
2. Update the KubernetesPatch (applyPatch2, restorePatch2) on m & deploy
3. Get m'

### What did you expect to happen?

`m' = m + applyPatch2`

### What actually happened?

`m' = m + applyPatch1 + applyPatch2`

Assume that I made a patch that appends container's argument `--loglevel verbose`
Then I changed the patch to append `--loglevel warn`.
After the update, both arguments are appended, even if I correctly supplied restorePatch to undo it properly.

### Environment

  - **CDK CLI Version  :** 1.86.0
  - **Framework Version:** 1.86.0
  - 
### Other

Also I found that the patch is not re-applied when the dependant manifest is redeployed (e.g. patch on the `HelmChart`)

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment]
@foriequal0 Thanks for reporting this. Yes we currently only apply the `restorePatch` on delete, but you present a valid use case.
