### ISSUE TITLE
(autoscaling): Launch Template Changes that modify ASG not visable when using cdk diff

### ISSUE THREAD

**Issue by caruso-billfire** [aws/aws-cdk#12694]
### Reproduction Steps

```ts
    const launchTemplate = new CfnLaunchTemplate(scope, `${name}-lt`, {
      launchTemplateName: config.name,
      launchTemplateData: {
        imageId: "ami-0e472933a1395e172",
        instanceType: config.instanceType.toString(),
        iamInstanceProfile: { name: instanceProfile.instanceProfileName },
        securityGroupIds: [securityGroup.securityGroupId],
      },
    });

    const asg: CfnAutoScalingGroup = new CfnAutoScalingGroup(
      scope,
      `${name}-asg`,
      {
        launchTemplate: {
          version: launchTemplate.attrLatestVersionNumber,
          launchTemplateName: launchTemplate.launchTemplateName,
        },

        terminationPolicies: ["OldestInstance"],
        vpcZoneIdentifier: subnetIds,
        autoScalingGroupName: `${name}-${launchTemplate.ref}-${launchTemplate.attrLatestVersionNumber}`,
        maxSize:  "1",
        minSize:  "1",
        desiredCapacity:  "1",
        healthCheckType: "EC2",
      }
    );

    asg.addDependsOn(launchTemplate);
```

This should be enough to show the issue, 
What happened with us is we changed the `iamInstanceProfile` from arn to name. 

When we do that, that produces a new LT version. but we do not see any changes to the  `autoScalingGroupName` property or a reference to the ASG changing at all. 

### What did you expect to happen?

We wanted to see in the cdk diff properties changing on the auto scaling group, IE the asg name. 

### What actually happened?

We do not see properties on the ASG changing during a cdk diff. 

Another solution to this issue could be an easy way intuitive way of viewing the stack-set generated from cdk deploy --no-execute from the CLI. 

Maybe, cdk diff --generate-stack-set or something? 

### Environment

  - **CDK CLI Version :** 1.83.0
  - **Node.js Version:** 12.20
  - **OS               :** linux
  - **Language (Version):** TypeScript

--- 

This is :bug: Bug Report

**Comment by NetaNir** [comment]
Since you are using an L1, the CDK does not in fact adds any special sauce on top of the CloudFormation deployment process. If the name property was changed it should be reflected in the created template, and as a result show the change the change when executing `cdk diff`.  Was the change reflected in the synthesized  template? If not, then it will not be reflected in `cdk diff`.

**Comment by caruso-billfire** [comment]
when running cdk diff we do not see a change in the autoscaling group when making a change to the launch template. 

But, when we use cdk deploy --no-execute we will see a modification to the auto scaling group in the CF stack set in the UI. 

Maybe I should write a feature request about a nicer way to view stack sets?

**Comment by NetaNir** [comment]
> when making a change to the launch template.

You mean in change to the template content our name? If the change is not detectable to cloudFormation, i.e the LaunchTemplate is created out of band, it will not be detected when executing `cdk diff` (or deploy)

**Comment by ryparker** [comment]
@caruso-billfire were you able to resolve your issue?

**Comment by caruso-billfire** [comment]
No but given how cdk diffs are generated I do not believe this can be fixed. 

Since the cdk diff simply does a diff against the deployed template and the local one, it doesn't take into account computed values. 

If you generate a stack set using --no-execute you will see the diff on computed values thought

**Comment by peterwoodworth** [comment]
Thanks for your feedback here, I'm glad you're happy with the `--no-execute` option
