### ISSUE TITLE
(aws-s3-assets): Object keys don't preserve the full extension name

### ISSUE THREAD

**Issue by zhangfand** [aws/aws-cdk#12699]
I'm using aws-s3-assets to upload data artifacts I used for a Sagemaker model. According to the documentation of Sagemaker, the S3 object needs to end with `tar.gz` extension. However, the uploaded asset is renamed to `<random-id>.gz`.

### Reproduction Steps
```
import * as cdk from "@aws-cdk/core";
import * as s3assets from "@aws-cdk/aws-s3-assets";

export class ModelStack extends cdk.Stack {
    constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
        super(scope, id, props);
        const modelArtifactAsset = new s3assets.Asset(this, 'ModelArtifact', {
            path: "artifact.tar.gz"
        });
        new cdk.CfnOutput(this, "modelArtifactS3Url", {
            description: "S3 url to the model artifact.",
            exportName: "modelArtifactS3Url",
            value: modelArtifactAsset.s3ObjectUrl,
        });
    }
}
```
### What did you expect to happen?
I expect the s3 object key is ended with `tar.gz`

### What actually happened?
The generated object is named as `<id>.gz`. Here is an example output from one run:
`s3://<bucket-name>/assets/f43ce33c42b10b3e1fe78d87a46cd0dff8611c37637edcf1857a36c33f302ee5.gz`

### Environment

  - **CDK CLI Version  :**: 1.85.0
  - **Framework Version:**: 1.86.0
  - **Node.js Version:**: v15.2.0
  - **OS               :**  Mac OS X
  - **Language (Version):** Typescript 3.9.7

### Other
A possible fix is to add an optional parameter for customize the extension name of the asset.

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment]
Happens because we use `path.extname` when calculating the target asset name:

https://github.com/aws/aws-cdk/blob/0963f786e49fc3cef9cc5c4cde3ecba5540a2749/packages/%40aws-cdk/core/lib/asset-staging.ts#L247-L249.

Which means this would happen for any multi dot extension. Maybe worth applying some heuristics here or possibly exposing some configuration for the user to specify the extension of an asset.

**Comment by javiercani** [comment]
Are there any news about this issue?

**Comment by peterwoodworth** [comment]
in progress
