### ISSUE TITLE
aws-elasticbeanstalk: Make L2 Version

### ISSUE THREAD

**Issue by maria-jackson** [aws/aws-cdk#12693]
Currently, aws-elasticbeanstalk only has the L1 version available

### Use Case

My team needs to spin up 100+ Elastic Beanstalk applications. From what I can see from your backlog, roadmap, and issues, it doesn't look like this is coming up.

### Proposed Solution

I want to make sure that this isn't on your roadmap. If it isn't is there a possibility that could be added? I may be able to contribute with a PR.  (I would need to fill out some paperwork to get it approved) If I/my team got something started that meet the Guidelines and passed awslint, would AWS be willing to collaborate and give some guidance beyond the (excellent) Guidelines?

### Other

I've found the guidelines in this so helpful and I'm really excited about CDK v2 and I love CDK! 👍 

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by maria-jackson** [comment]
Looks like this is the same as https://github.com/aws/aws-cdk/issues/6909

**Comment by NetaNir** [comment]
duplicate https://github.com/aws/aws-cdk/issues/6909
