### ISSUE TITLE
(aws-lambda-python): CfnFunction environment.variables returns None

### ISSUE THREAD

**Issue by quickshore** [aws/aws-cdk#12691]
When reading environment variables for CfnFunction in aspect CfnFunction.environment.variables returns None

### Reproduction Steps

1. Create a stack that contains Lambda with an environment variable set
2. Create an aspect that reads the environment variables from CfnFunction node
3. Apply aspect to the stack
4. Run `cdk synth`

Code example:

**app.py**
```
#!/usr/bin/env python3
from aws_cdk import core
from lambdastack import TestStack, MyAspect

app = core.App()
main_stack = TestStack(app, "test-stack")
core.Aspects.of(main_stack).add(MyAspect())

app.synth()
```
**lambdastack.py**

```
import jsii, pathlib
from aws_cdk import (
    core,
    aws_lambda as _lambda,
    aws_iam as iam,
    aws_s3 as s3_
)
from aws_cdk.core import RemovalPolicy


class TestStack(core.Stack):

    def __init__(self, scope: core.Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        # Defines an AWS Lambda resource
        my_lambda = _lambda.Function(
            self, 'MRTestEnv',
            runtime=_lambda.Runtime.PYTHON_3_7,
            code=_lambda.Code.asset(f"{pathlib.Path(__file__).parents[0]}/lambda"),
            handler='hello.handler',
            environment=dict(
                SQS_QUEUE_URL = "test_queue",
                DYNAMO_TABLE_NAME = "test_dynamo",
                SOME_ENV = "test_some_env"
            )
        )

@jsii.implements(core.IAspect)
class MyAspect:
    def visit(self, node):
        if isinstance(node, _lambda.CfnFunction):
            print("CfnFunction.name:" + node.function_name)
            print("CfnFunction.environment.variables:" + str(node.environment.variables))
            node.add_override("Properties.Environment.Variables.SOME_ENV","Something else")
```

### What did you expect to happen?

The aspect prints dictionary content with SQS_QUEUE_URL, DYNAMO_TABLE_NAME, SOME_ENV keys.

### What actually happened?

The aspect prints "CfnFunction.environment.variables:None"

### Environment

  - **CDK CLI Version  : 1.86.0**
  - **Node.js Version: v12.18.2** 
  - **OS               : Ubuntu 16.04.6 LTS**
  - **Language (Version): Python 3.6.12**

### Other

The line `node.add_override("Properties.Environment.Variables.SOME_ENV","Something else")` Lambda's env. variables (see it in cdk synth output) though we can't read those.

--- 

This is :bug: Bug Report

**Comment by eladb** [comment]
Reading properties from the low-level (L1) CFN resource (in this case `CfnFunction`) may depend on the implementation of the high-level (L2) construct (in this case `PythonFunction`). In this case, the L2 construct uses lazy evaluation in order to render the function's environment and this is why reading it from the L1 will not yield what you expect.

Can you describe what you are trying to achieve with the aspect? Perhaps there is way to achieve that without reading the L1 properties.

**Comment by quickshore** [comment]
We have a ready high-level stack that defines a microservice and need to add additional behavior/functionality to it using aspects. As part of this modification, we need to add/change Lambda's environment variables: if there is no env. variable, we just add it, if there isn't, then we need to modify it. Very simple case. Are there different ways to achieve this goal?

**Comment by corymhall** [comment]
@quickshore is this still an issue for you? It doesn't look like it will be possible for us to change the way we render environment variables for the L2 so the solution will most likely involve not using Aspects for this use case.
