### ISSUE TITLE
(elasticloadbalancingv2):  Default Security Group Issues

### ISSUE THREAD

**Issue by msaltz96** [aws/aws-cdk#12692]
**Language (Version): Python

 By Default, ALB creates a default security group if you do not reference one.
This is the outbound rules it creates:
       "SecurityGroupEgress": [
          {
            "CidrIp": "255.255.255.255/32",
            "Description": "Disallow all traffic",
            "FromPort": 252,
            "IpProtocol": "icmp",
            "ToPort": 86
          }
        ],

Question: 
1. Why does the default security not allow all outbound by default.
Should look like this:
        "SecurityGroupEgress": [
          {
            "CidrIp": "0.0.0.0/0",
            "Description": "Allow all outbound traffic by default",
            "IpProtocol": "-1"
          }
        ],

2. What is the easiest way to edit the properties of the default security group made, without generating a new one?

**Comment by peterwoodworth** [comment]
Sorry for the long wait here @msaltz96,

Security Groups can be configured by setting the `allowAllOutbound` prop to true. The constructor will then call this function upon creating a security group
https://github.com/aws/aws-cdk/blob/a655819128c11309d88d5f5535678e8c02e292a9/packages/%40aws-cdk/aws-ec2/lib/security-group.ts#L548-L558
However you can't do that when the ALB is creating a default security group. Here is where it does that:
https://github.com/aws/aws-cdk/blob/a655819128c11309d88d5f5535678e8c02e292a9/packages/%40aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-load-balancer.ts#L92-L96
As you can see, `allowAllOutbound` is set to false. However I can't really tell you why this is the default case

**Comment by peterwoodworth** [comment]
I'll be closing this issue now. Ping me if you have any additional concerns!
