### ISSUE TITLE
cloudfront: How to migrate CloudFrontWebDistribution to the new Distribution class

### ISSUE THREAD

**Issue by bdadam** [aws/aws-cdk#12707]
## :question: General Issue

Please consider the following code:
```ts
new cloudfront.CloudFrontWebDistribution(this, 'CFDistribution', {
    // ...
});
```

I converted this into the new Distribution class.

```ts
new cloudfront.Distribution(this, 'CFDistribution', {
    // ...
});
```

When I deployed this new code I got the following error:

```
One or more of the CNAMEs you provided are already associated with a different resource. (Service: AmazonCloudFront; Status Code: 409; Error Code: CNAMEAlreadyExists;
```

This is because the deployment tried to create a new CloudFront distribution instead of reusing the old one.

### The Question

How could I make CDK reuse the old Cloudfront distribution? Would an override of the LogicalID help here? If yes then how can it be done?

**Comment by Roshy10** [comment]
Is there any progress on this issue? I don't want to have to delete my stack and faff around with persisting buckets and such

**Comment by hanazuki** [comment]
FWIW, the following change works for me.
```diff
-    const distribution = new cloudfront.CloudFrontWebDistribution(this, 'Distribution', {
-      // ...
-    });
+    const distribution = new cloudfront.Distribution(this, 'Distribution', {
+      // ...
+    });

+    (distribution.node.defaultChild as cloudfront.CfnDistribution).overrideLogicalId('DistributionCFDistributionXXXXXXXX');
```
where the logicalId comes from my existing stack. Check `cdk diff` to make sure the distribution is reused.

**Comment by Roshy10** [comment]
@hanazuki thanks, I've just decided to delete the distribution and the stats it had, I really don't like the idea of having to hardcode a distribution id.

**Comment by DarshanAwachat** [comment]
> FWIW, the following change works for me.
> 
> ```diff
> -    const distribution = new cloudfront.CloudFrontWebDistribution(this, 'Distribution', {
> -      // ...
> -    });
> +    const distribution = new cloudfront.Distribution(this, 'Distribution', {
> +      // ...
> +    });
> 
> +    (distribution.node.defaultChild as cloudfront.CfnDistribution).overrideLogicalId('DistributionCFDistributionXXXXXXXX');
> ```
> 
> where the logicalId comes from my existing stack. Check `cdk diff` to make sure the distribution is reused.

I followed the same steps. Got this error =>
`"Invalid request provided: The parameter globPattern is too small or empty. (Service: CloudFront, Status Code: 400`
Any ways to resolve this? or other ways to reuse the same cloudfront.

**Comment by peterwoodworth** [comment]
We have a section on this in our docs https://docs.aws.amazon.com/cdk/api/v1/docs/aws-cloudfront-readme.html#migrating-from-the-original-cloudfrontwebdistribution-to-the-newer-distribution-construct

**Comment by caevv** [comment]
I can't see that being scalable or possible when you have hundreds of environments being deployed.

**Comment by saksiuchenka** [comment]
```
        (<any>(this.distribution.node.defaultChild as CfnElement).node).id = 'CFDistribution';

```

This worked for me as a scalable solution for tens of distributions.

**Comment by hqv-divya** [comment]
@saksiuchenka Thank you so much for the solution, it worked like a charm, but how does this work exactly? It would be really nice if you could explain it to me

**Comment by santiagovj22** [comment]
@bdadam @saksiuchenka hi! any solutions for this?
