### ISSUE TITLE
(events-targets): Add target class for API Gateway target in EventBridge

### ISSUE THREAD

**Issue by hugomallet** [aws/aws-cdk#12708]
Hi,

The API Gateway target is missing from the events-targets module.

This target is available in EventBridge as described here : https://docs.aws.amazon.com/eventbridge/latest/userguide/targets-apigateway.html
And in cloudformation (HttpParameters) : https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-events-rule-target.html#cfn-events-rule-target-httpparameters

(For future readers : AwsApi target class is not related to api gateway !) 

Can you add this target ?

Thanks,

---

This is a :rocket: Feature Request

**Comment by hedrall** [comment]
I’d like to work on it.
