### ISSUE TITLE
(aws-apigateway): CDK Api Gateway Construct missing dependency between Stage and internally created CloudWatch Role

### ISSUE THREAD

**Issue by zrieq** [aws/aws-cdk#12701]
I am using CDK to create our API GW component using JAVA implementation.

I found when deploying our stack to a new AWS account, API gateway is trying to deploy the Stage before the Cloudwatch role is being completed, causing "cdk deploy" to fail and rollback. Please check the 1st attached image to see the sequence of events happening in the stack.

I came up with a workaround as you see in the 2nd screenshot, and it seems to work as shown in the 3rd screenshot. I don't think it is an ideal workaround.

As per the documentation for SpecRestApi construct -see 4th screenshot, the CloudWatch Role will be created automatically (the default is true for this boolean)

Can you please help with this, I think it is a defect in CDK .. maybe I am mistaken.

Thanks

![ApiGW failing](https://user-images.githubusercontent.com/18265998/105776585-d7e65000-5f36-11eb-84bb-dcdf7dfa1939.png)
![CDK Api Gw workaround](https://user-images.githubusercontent.com/18265998/105776602-dcab0400-5f36-11eb-8b6d-264372d865e0.png)
![CDK Api Gateway workaround result](https://user-images.githubusercontent.com/18265998/105776609-de74c780-5f36-11eb-92b4-39a075e3ed10.png)
![image](https://user-images.githubusercontent.com/18265998/105776785-33b0d900-5f37-11eb-9fe3-fe4afead49a5.png)

### Reproduction Steps

```
SpecRestApi pubSubSpecRestApi = SpecRestApi.Builder.create(this, "pub-sub")
                    .apiDefinition(ApiDefinition.fromAsset(pubSubApiSpecsFIle.getAbsolutePath()))
                    .endpointTypes(List.of(EndpointType.REGIONAL))
                    .deployOptions(StageOptions.builder()
                            .stageName(env.toLowerCase())
                            .loggingLevel(MethodLoggingLevel.INFO)
                            .dataTraceEnabled(true)
                            .build())
                    .build();
```

### What did you expect to happen?

Create Api Gateway.

### What actually happened?

Failed to create Api gateway due to missing CloudWatch role.

### Environment

  - **CDK CLI Version  :** 1.85
  - **Node.js Version:** v12.14.1
  - **Language (Version):** java

This is :bug: Bug Report

**Comment by zrieq** [comment]
Also I think there is another defect in ApiGateway where:

Basically, if ARN string was set once for an AWS Account, it will stay there for every API, even it is pointing to a NON existing CloudWatch role.

This means even when rolling back the internally created role (due to some failure) OR destroying the Stack, the cloudwatch ARN value is still saved on the account level with an invalid value -the role was deleted but only the ARN string value is left.

Having the ARN value string prepopulated, will make all cdk deployments in this account to bypass the cloud watch role issue, as the validation for the deploy stage step is just validating the cloudwatch ARN is not empty! 

That's why the same stack is working for me in another account over and over with no issues.
I can prove this with some recording if needed.

**Comment by nija-at** [comment]
We're tracking this already in two different issues already -

https://github.com/aws/aws-cdk/issues/10722
https://github.com/aws/aws-cdk/issues/10878

**Comment by zrieq** [comment]
@nija-at thanks for looking into this issue.

But I think the referred issues are not related to the main issue here.

The issue here is talking about setting dependency for internal created role. Which is not happening.

The issues are related to another defect that I mentioned in my comment, which speaks about cfnaccount.

**Comment by nija-at** [comment]
> But I think the referred issues are not related to the main issue here.

The race condition issue - #10722 - I believe is the same.
