### ISSUE TITLE
build.Project role requires ec2:CreateNetworkInterfacePermission

### ISSUE THREAD

**Issue by WillBroadbent** [aws/aws-cdk#12705]
When I deploy my CodeBuild cdk code the created build project fails to provision with following error: VPC_CLIENT_ERROR: Unexpected EC2 error: UnauthorizedOperation when provisioning the codebuild instance (I am deploying my CodeBuild project to my VPC)

### Reproduction Steps

```python
        build.Project(self, "MasterBuildLibrary", 
            source = build.Source.code_commit(repository=source_repo),
            build_spec=anyOldBuildspec,
            role = someExistingRole,
            environment=build.BuildEnvironment(build_image = build.LinuxBuildImage.STANDARD_5_0, privileged=True),
            project_name="myProject",
            vpc=vpc
        )
```

### What did you expect to happen?

I expect the permission ec2:CreateNetworkInterfacePermission to also be included in the inline policy (this may only be required if a VPC is provided)

### What actually happened?

The following inline policy is created, CreateNetworkInterfacePermission is missing
This code adds the following inline policy to the specified existing role:

```json
    "MasterBuildLibraryPolicyDocumentCA3A4C7D": {
      "Type": "AWS::IAM::Policy",
      "Properties": {
        "PolicyDocument": {
          "Statement": [
            {
              "Action": [
                "ec2:CreateNetworkInterface",
                "ec2:DescribeNetworkInterfaces",
                "ec2:DeleteNetworkInterface",
                "ec2:DescribeSubnets",
                "ec2:DescribeSecurityGroups",
                "ec2:DescribeDhcpOptions",
                "ec2:DescribeVpcs"
              ],
              "Effect": "Allow",
              "Resource": "*"
            }
          ],
          "Version": "2012-10-17"
        },
        "PolicyName": "MasterBuildLibraryPolicyDocumentCA3A4C7D",
        "Roles": [
          "adf-codebuild-role"
        ]
      },
      "Metadata": {
        "aws:cdk:path": "Library-Build/MasterBuildLibrary/PolicyDocument/Resource"
      }
    },
```

### Environment

  - **CDK CLI Version  : 1.86**
  - **Framework Version:**
  - **Node.js Version: v13.8.0**
  - **OS               :  MacOs**
  - **Language (Version): Python (3.7.6)**

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hey @WillBroadbentMSM ,

I've just tried it myself, and this:

```ts
        const defaultVpc = ec2.Vpc.fromLookup(this, 'Vpc', { isDefault: true });
        const project = new codebuild.Project(this, 'GitHubSourceProject', {
            projectName: 'GitHubSourceEncryptedProject',
            source: codebuild.Source.gitHub({
                owner: 'skinny85',
                repo: 'test-code-build-deploy-spring-boot-project',
                webhook: true,
                webhookFilters: [
                    codebuild.FilterGroup.inEventOf(
                        codebuild.EventAction.PUSH,
                        codebuild.EventAction.PULL_REQUEST_CREATED,
                    ).andBranchIs('webhook-tes.*'),
                ],
            }),
            environment: {
                buildImage: codebuild.LinuxBuildImage.STANDARD_5_0,
            },
            vpc: defaultVpc,
        });
```

Deploys and runs the build correctly...

What's `someExistingRole` in your code? Can you show how are you creating it?

Thanks,
Adam

**Comment by WillBroadbentMSM** [comment]
The exisiting role is just imported using:

adf_code_build_role=iam.Role.from_role_arn(self, "AdfCodeBuildRole", role_arn="arn:aws:iam::000000000000:role/adf-codebuild-role")

and then cdk is attaching an inline policy to it. I guess there could be some settings on the VPC requiring the additional permission of CreateNetworkInterfacePermission but I dont know what setting I could have that would be making my CodeBuilds different.

**Comment by skinny85** [comment]
@WillBroadbentMSM is there any chance you could share how is your VPC created, so I can try to reproduce this?

**Comment by WillBroadbentMSM** [comment]
Hi sorry for late reply, my notifications seem to be no working and I dont use GH much.

def createVpcWithSubnets(self):
        private_subnet = ec2.SubnetConfiguration(name="privateSubnet",subnet_type=ec2.SubnetType.PRIVATE, cidr_mask=24)
        public_subnet = ec2.SubnetConfiguration(name="publicSubnet",subnet_type=ec2.SubnetType.PUBLIC,cidr_mask=24)
        vpc = ec2.Vpc(
            self, "prod",
            cidr="10.255.0.0/16",
            enable_dns_hostnames=True,
            enable_dns_support=True,
            nat_gateways=2,
            max_azs=2,
            subnet_configuration=[private_subnet, public_subnet],
            vpn_gateway_asn=9059
        )
        ssm.StringParameter(self, "vpc_id", string_value=vpc.vpc_id, parameter_name="vpc_id")
        return vpc

**Comment by skinny85** [comment]
Thanks @WillBroadbentMSM , that's super helpful!

**Comment by NGL321** [comment]
@skinny85 Were you able to reproduce this in the end?

**Comment by skinny85** [comment]
> @skinny85 Were you able to reproduce this in the end?

I didn't try @NGL321, feel free to take a stab at it.
