### ISSUE TITLE
(aws_iam): service roles are doubled, causing a fatal error, when using the same role for 2 resources

### ISSUE THREAD

**Issue by NickTheSecurityDude** [aws/aws-cdk#12714]
service roles are doubled, causing a fatal error, when using the same role for 2 resources

I have 2 lambda functions and 2 config rules and as you can see the AWSConfigRulesExecutionRole is attached as a managed policy twice, even though I don't have it at all in my iam stack:
`IAM Policy Changes
┌───┬──────────────────────────────┬────────────────────────────────────────────────────────────────────────────────┐
│   │ Resource                     │ Managed Policy ARN                                                             │
├───┼──────────────────────────────┼────────────────────────────────────────────────────────────────────────────────┤
│ + │ ${EBS Encrypted Lambda Role} │ arn:${AWS::Partition}:iam::aws:policy/IAMReadOnlyAccess                        │
│ + │ ${EBS Encrypted Lambda Role} │ arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole │
│ + │ ${EBS Encrypted Lambda Role} │ arn:${AWS::Partition}:iam::aws:policy/service-role/AWSConfigRulesExecutionRole │
│ + │ ${EBS Encrypted Lambda Role} │ arn:${AWS::Partition}:iam::aws:policy/service-role/AWSConfigRulesExecutionRole │
└───┴──────────────────────────────┴────────────────────────────────────────────────────────────────────────────────┘`

The stack then errors out:
`iam: deploying...
iam: creating CloudFormation changeset...
[██████████████████████████████████████▋···················] (2/3)

1:40:37 PM | CREATE_FAILED        | AWS::IAM::Role     | EBS Encryp`
Property ManagedPolicyArns contains duplicate values.

### Reproduction Steps

create 2 lambda functions and 2 custom config rules, use the same role for each lambda function

If I comment the 2nd config custom rule it works fine

### What did you expect to happen?

I didn't know it would add the service role at all because I don't explicitly specify it, but it certainly shouldn't be adding it twice.

### What actually happened?

arn:${AWS::Partition}:iam::aws:policy/service-role/AWSConfigRulesExecutionRole was added twice

### Environment

  - **CDK CLI Version: 1.85.0 (build 5f44668)**
  - **Framework Version:  How do I find this?**
  - **Node.js Version:15.6.0** 
  - **OS               : Mac Big Sur** 
  - **Language (Version): Python 3.8.6** 

### Other

URL to the code:
[https://github.com/NickTheSecurityDude/config-security-risks](url)

--- 

This is :bug: Bug Report

**Comment by NickTheSecurityDude** [comment]
Fixed, had to use .without_policy_updates() at the end of the role.
https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_iam/Role.html#aws_cdk.aws_iam.Role.without_policy_updates

**Comment by skinny85** [comment]
I still think this is a bug in the IAM service library 🙂 (the Managed Policy should be attached to the Role only once)

**Comment by jackhopner** [comment]
The equality check in `addManagedPolicy` doesn't work because at the time the policies aren't actually evaluated.. They're still tokens.

**Comment by kirintwn** [comment]
It be might related to https://github.com/aws/aws-cdk/issues/11073#issuecomment-765262059.
