### ISSUE TITLE
When a new release occurs, brief failures on running npm install

### ISSUE THREAD

**Issue by jdwalker-emis** [aws/aws-cdk#12729]
### The Question

Installing  1.87.0 fails with

$ npm install -g aws-cdk@1.87.0
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @aws-cdk/cloudformation-diff@1.87.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting  
npm ERR! notarget a package version that doesn't exist.

Now seems to be working, but errored when a release occurred

### Environment

  - **CDK CLI Version:** 1.87.0
  - **Node.js Version:** v12.16.2
  - **OS:** Windows 10
  - **Language (Version):** Typescript

**Comment by christophgysin** [comment]
This seems to happen on every release. In what order are the packages published on a new release? Could we reorder them so dependencies are published first?

**Comment by jdwalker-emis** [comment]
Now seems to be working

**Comment by FElliger** [comment]
Just had the same issue. It lasted ~15 minutes which is quite a lot I think. From my perspective, `aws-cdk` should be the last one to be published.

**Comment by andcea** [comment]
This is causing CodePipeline to fail as well if you define your CDK dependencies as `"@aws-cdk/core": "^1.86.0"`

Minor releases should be backward compatible and not break anything.

```
This CDK CLI is not compatible with the CDK library used by your application. Please upgrade the CLI to the latest version.
--
390 | (Cloud assembly schema version mismatch: Maximum schema version supported is 8.0.0, but found 9.0.0)
```

I'm gonna start defining CDK dependencies as `"@aws-cdk/core": "~1.xx.0"` to avoid this issue in the future.

**Comment by henrist** [comment]
We are also hit by this in CDK Pipelines. We recently moved some of our more active projects into CDK pipelines and have noticed this for the last 3-4 releases or so (failing the CodePipeline job), including the ongoing 1.87.1 release. We've not set `cdkCliVersion`, so it is affected since it by default uses the latest version.

**Comment by rix0rrr** [comment]
This is true. Sorry for the inconviences encountered, publishing in a different order might help but probably not (as packages will still be independently eventually-consistently replicated between NPM mirrors).

The work planned for v2 will solve this as well. Closing issue as there's no additional work we'll be taking up here.

**Comment by AlexChesters** [comment]
@rix0rrr is there a specific issue we can track for this? or will it be in the first release of v2?
