### ISSUE TITLE
(apigateway): Usage Plan association fails with imported RestApi resource

### ISSUE THREAD

**Issue by pirklmar** [aws/aws-cdk#12731]
When I import RestApi resource, it seems the restApiId is not propagated to the Usage Plan resource (null value is passed)

### Reproduction Steps

```
const apiKey = apigateway.ApiKey.fromApiKeyId(this, "apiKey", "apikeyId");

        const supportApi = apigateway.RestApi.fromRestApiId(this, "support", "restApiId");

        new apigateway.UsagePlan(this, "usagePlan", {
            name: props.label.id,
            apiKey,
            apiStages: [
                {
                    api: supportApi,
                    stage: supportApi.deploymentStage,
                },
            ],
        });
```

### What actually happened?

```
(UsagePlan) UPDATE FAILED

Invalid API identifier specified <accountId>:null (Service: AmazonApiGateway; Status Code: 404; Error Code: NotFoundException; Request ID: 8fe5a647-adb2-48f0-afc7-53bff8ac6f08; Proxy: null)
```

--- 

CDK 1.87

This is :bug: Bug Report

**Comment by nija-at** [comment]
Hey @pirklmar -

What values are you providing for `restApiId` and `apiKeyId`? Are these valid identifiers?

**Comment by pirklmar** [comment]
> Hey @pirklmar -
> 
> What values are you providing for `restApiId` and `apiKeyId`? Are these valid identifiers?

Hi @nija-at, thanks for your reply, I double-checked they are valid ids of existing resources

**Comment by nija-at** [comment]
I see what's going on. 

Imported RestApis do not have a `deploymentStage` configured and hence return `undefined`. 
@pirklmar - what you're doing is unfortunately not going to work. You need to also import the stage associated with this API. Unfortunately, we're missing 

Two things are needed here -

1. validation in UsagePlan that ensures that a usage plan is associated with at least one API
2. import API for the `Stage` construct - https://github.com/aws/aws-cdk/issues/12965
