### ISSUE TITLE
(codedeploy): Install of codedeploy on Windows fail

### ISSUE THREAD

**Issue by mbonig** [aws/aws-cdk#12734]
When using a ServerDeploymentGroup and setting 'installAgent' to true, the following gets added to the UserData:

```
<powershell>Set-Variable -Name TEMPDIR -Value (New-TemporaryFile).DirectoryName
aws s3 cp s3://aws-codedeploy-us-east-1/latest/codedeploy-agent.msi $TEMPDIR\codedeploy-agent.msi
$TEMPDIR\codedeploy-agent.msi /quiet /l c:\temp\host-agent-install-log.txt</powershell>
```

However, this does not work and produces this error (c:\ProgramData\Amazon\EC2-Windows\Launch\Log\UserdataExecution.log)

```
+ $TEMPDIR\codedeploy-agent.msi /quiet /l c:\temp\host-agent-install-lo ...
+         ~~~~~~~~~~~~~~~~~~~~~
Unexpected token '\codedeploy-agent.msi' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : UnexpectedToken
```

### Reproduction Steps

```typescript
    const deploymentGroup = new ServerDeploymentGroup(this, 'v1AppDeployment', {
      application,
      autoScalingGroups: [ asg ],
      // adds User Data that installs the CodeDeploy agent on your auto-scaling groups hosts
      // default: true
      installAgent: true,
      deploymentConfig: ServerDeploymentConfig.ONE_AT_A_TIME,
    });
```

The launch configuration ends up with this powershell script:

```
<powershell>Set-Variable -Name TEMPDIR -Value (New-TemporaryFile).DirectoryName
aws s3 cp s3://aws-codedeploy-us-east-1/latest/codedeploy-agent.msi $TEMPDIR\codedeploy-agent.msi
$TEMPDIR\codedeploy-agent.msi /quiet /l c:\temp\host-agent-install-log.txt</powershell>
```

### What did you expect to happen?

I'd expect a script to be added that would allow for the proper installation. Maybe this?

### What actually happened?

Got an error from the instance during startup.

### Environment

  - **CDK CLI Version  :** 1.86.0
  - **Framework Version:** 
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):** 

### Other

Looks like this is the line of code that needs changing: 
https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-codedeploy/lib/server/deployment-group.ts#L375

I'd recommend maybe:

```
Set-Variable -Name TEMPDIR -Value (New-TemporaryFile).DirectoryName
aws s3 cp s3://aws-codedeploy-us-east-1/latest/codedeploy-agent.msi $TEMPDIR\codedeploy-agent.msi
cd $TEMPDIR
.\codedeploy-agent.msi /quiet /l c:\temp\host-agent-install-log.txt
```

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Thanks for reporting @mbonig ! Any chance of a PR fixing this? 🙂

**Comment by mbonig** [comment]
yup. I didn't see any tests so it's a simple two-liner.
