### ISSUE TITLE
Custom CDK Synthesizer w/ assets using pre-defined resources w/o CDKToolkit stack 

### ISSUE THREAD

**Issue by mh-love** [aws/aws-cdk#12739]
I would like to bootstrap a CDK project, but without creating a CDKToolkit stack. Someone in my org with permissions created resources for my project. This [BootstraplessSynthesizer](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/core/lib/stack-synthesizers/bootstrapless-synthesizer.ts) is not what I want, because I want Assets! So, how does one use pre-defined resources and have synthesis pick them up? Purportedly I can do this by configuring the DefaultSynthesizer, but perhaps I need to write a custom one? 
 
Here is what my DefaultSynthesizer looks like:

```
const props = {
      env: { account: '1234567890', region: 'us-west-2' },
      synthesizer: new CDK.DefaultStackSynthesizer({
        qualifier: '', //ignore
        generateBootstrapVersionRule: false,

        // Name of the S3 bucket for file assets
        fileAssetsBucketName: 'my-bucket',
        fileAssetKeyArnExportName: 'arn:aws:kms:us-west-2:1234567890:key/blahblahblah',
        
        // Name of the ECR repository for Docker image assets - ignoring not used atm
        imageAssetsRepositoryName: '', //ignore
      
        // ARN of the role assumed by the CLI and Pipeline to deploy here
        deployRoleArn: 'arn:aws:iam::1234567890:role/my-deploy-role',  
        
        // ARN of the role used for file asset publishing (assumed from the deploy role)
        fileAssetPublishingRoleArn: 'arn:aws:iam::1234567890:role/my-file-publishing-role',
        fileAssetPublishingExternalId: '', //ignore
        
        // ARN of the role used for Docker asset publishing (assumed from the deploy role) - ignoring not used atm
        imageAssetPublishingRoleArn: '', //ignore
        imageAssetPublishingExternalId: '', //ignore
      
        // ARN of the role passed to CloudFormation to execute the deployments
        cloudFormationExecutionRole: 'arn:aws:iam::1234567890:role/my-cfn-exec-role',
      })
    }; 
    
   new PipelineAppStack(app, 'PipelineAppStack', { stage }, props);

```

When synthesizing from above, an error is thrown:

`A StackSynthesizer can only be used for one Stack: create a new instance to use with a different Stack` 

I believe this is because I already have a CDKToolkit stack in the 1234567890 for another CDK project, but I do not want to use _that_ CDKToolkit stack, because I don't want to use a CDKToolkit stack at all :)

 CDK_CLI_VERSION: '1.87.1'

Thanks!

**Comment by peterwoodworth** [comment]
Sorry no one has replied to this yet @mh-love,

This error is occurring because you're using the same Stack Synthesizer for multiple stacks. https://github.com/aws/aws-cdk/pull/11635

Let me know if I'm wrong here
