### ISSUE TITLE
(core): newStyleStackSynthesis=true causes files upload to s3 without file extension

### ISSUE THREAD

**Issue by kokachev** [aws/aws-cdk#12740]
New style synthesis uploads files to s3 without file extension. This causes AWS Glue script compilation failures and makes it impossible to use Glue with custom JARs  and newStyleStackSynthesis: true.

### Reproduction Steps

1. Set "@aws-cdk/core:newStyleStackSynthesis": "true"
2. Create s3.assets.Asset from local jar file
3. Deploy stack

### What did you expect to happen?

Uploaded file should have "jar" extension

### What actually happened?

Filename does not have an extension

### Environment

  - **CDK CLI Version  : 1.86.0**
  - **Framework Version: 1.86.0**
  - **Node.js Version: v15.7.0**
  - **OS               :Mac Os**
  - **Language (Version): Java 8**

### Other

We use CDK to upload custom JAR files for AWS Glue jobs. Glue Java compiler requires custom jars to have "jar" extension, otherwise script compilation fails. Because, of this it's impossible for us to use CDK pipelines.

When core:newStyleStackSynthesis is set to false, files are uploaded with extensions and everything is working as expected.

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment]
@rix0rrr Can you take a look? Could this have been intentional?
