### ISSUE TITLE
(pipelines) Environment variables placed in Pipeline > Stages > Action > Configuration break deploy

### ISSUE THREAD

**Issue by makr11** [aws/aws-cdk#12747]
Environment variables were previously placed in AWS::CodeBuildProject > Properties > Environment as a list. 

Now it is placed in Pipeline > Stages > Action > Configuration as a string which causes:

```
1 validation error detected: Value at 'pipeline.stages.2.member.actions.1.member.configuration' failed to satisfy constrain
t: Map value must satisfy constraint: [Member must have length less than or equal to 1000, Member must have length greater than or equal to 1] (Service: AWSCodePipeline; Status Code: 400; Error Code: ValidationException; Request ID: e4
df2712-2f07-45e6-a0bd-9ebf10a0b8c2; Proxy: null)
```

and I am unable to deploy pipeline.

### Reproduction Steps

```python
environment_variables = {name: codebuild.BuildEnvironmentVariable(value=value.value)
                                 for name, value in EnvVars.__members__.items()}

pipeline = pipelines.CdkPipeline(self, "Pipeline",
                                         cloud_assembly_artifact=cloud_assembly_artifact,
                                         pipeline_name="MyPipeline",
                                         source_action=cp_actions.CodeCommitSourceAction(
                                            action_name="GetSourceCode",
                                            output=source_artifact,
                                            repository=repository),
                                         synth_action=pipelines.SimpleSynthAction(
                                            environment={"privileged": True},
                                            environment_variables=environment_variables,
                                            source_artifact=source_artifact,
                                            cloud_assembly_artifact=cloud_assembly_artifact,
                                            install_commands=["npm install -g aws-cdk"],
                                            synth_command="cdk synth")
                                         )
```

  - 1.87.0
  - **Framework Version:**
  - node v14.15.1
  - Windows 10
  - Python 3.8
  - 
This is :bug: Bug Report

**Comment by skinny85** [comment]
@makr11 apologies this happened. Can you let me know what's inside `environment_variables`? How many variables do you have there?

**Comment by makr11** [comment]
@skinny85 Hi, well there are 30 environment variables that should go in the build project, but until the  version 1.87.0 I had no issue with it and the format was:

`
"PipelineBuildSynthCdkBuildProject": {
      "Type": "AWS::CodeBuild::Project",
      "Properties": {
        "Artifacts": {
          "Type": "CODEPIPELINE"
        },
        "Environment": {
          "ComputeType": "BUILD_GENERAL1_SMALL",
          "EnvironmentVariables": [
            {
              "Name": "ENDPOINT1",
              "Type": "PLAINTEXT",
              "Value": "......."
            },
            {
              "Name": "USERNAME",
              "Type": "PLAINTEXT",
              "Value": "......"
            },
            {
              "Name": "PASSWORD",
              "Type": "PLAINTEXT",
              "Value": "....."
            },
............
`
and 
`
"Pipeline9850B417": {
      "Type": "AWS::CodePipeline::Pipeline",
      "Properties": {
        "RoleArn": {
          "Fn::GetAtt": [
            "PipelineRoleB27FAA37",
            "Arn"
          ]
        },
        "Stages": [       
          {
            "Actions": [
              {
                "ActionTypeId": {
                  "Category": "Build",
                  "Owner": "AWS",
                  "Provider": "CodeBuild",
                  "Version": "1"
                },
                "Configuration": {
                  "ProjectName": {
                    "Ref": "PipelineBuildSynthCdkBuildProject6BEFA8E6"
                  },
                  "EnvironmentVariables": "[{\"name\":\"_PROJECT_CONFIG_HASH\",\"type\":\"PLAINTEXT\",\"value\":\"5ec320366979b49fb50c1553e5eb4d550156ea968622a7993e6d4f0430e2a2aa\"}]"
                },
                "InputArtifacts": [
                  {
                    "Name": "Artifact_Source_GetSourceCode"
                  }
                ],
                "Name": "Synth",
                "OutputArtifacts": [
                  {
                    "Name": "Artifact_Build_Synth"
                  }
                ],
                "RoleArn": {
                  "Fn::GetAtt": [
                    "PipelineBuildSynthCodePipelineActionRole4E7A6C97",
                    "Arn"
                  ]
                },
                "RunOrder": 1
              }
            ],
            "Name": "Build"
          },
............
`

With version 1.87.0 environment variables went into action configuration and resulted with an error mention above.

**Comment by skinny85** [comment]
@makr11 can you try a simple change for me, and see if it helps?

Instead of

```python
  synth_action=pipelines.SimpleSynthAction(
    environment={"privileged": True},
    environment_variables=environment_variables,
    source_artifact=source_artifact,
    cloud_assembly_artifact=cloud_assembly_artifact,
    install_commands=["npm install -g aws-cdk"],
    synth_command="cdk synth")
```

Can you try

```python
  synth_action=pipelines.SimpleSynthAction(
    environment={
        'privileged': True,
        'environment_variables': environment_variables,
    },
    source_artifact=source_artifact,
    cloud_assembly_artifact=cloud_assembly_artifact,
    install_commands=['npm install -g aws-cdk'],
    synth_command='cdk synth',
  )
```

? I _think_ this will solve your problem.

Thanks,
Adam

**Comment by makr11** [comment]
@skinny85 This resolved my issue, thanks!

**Comment by gshpychka** [comment]
@skinny85 Maybe it'd be a good idea to document this?

**Comment by skinny85** [comment]
Agreed @gshpychka 🙂. Want to open us a Pull Request clarifying this? Our "Contributing" guide: https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md.

**Comment by gshpychka** [comment]
Sure! What would be the correct clarification, though? Do we advise something at least relatively specific, or do we just say "if you have a lot of variables, use this way" without specifying what "a lot" is?

**Comment by skinny85** [comment]
How about we base it on the error the OP encountered?

```
1 validation error detected: Value at 'pipeline.stages.2.member.actions.1.member.configuration' failed to satisfy constrain
t: Map value must satisfy constraint: [Member must have length less than or equal to 1000, Member must have length greater than or equal to 1] (Service: AWSCodePipeline; Status Code: 400; Error Code: ValidationException; Request ID: e4
df2712-2f07-45e6-a0bd-9ebf10a0b8c2; Proxy: null)
```

"If you encounter an error similar to this, try this instead", something like that?

**Comment by skinny85** [comment]
Sure! Yes, the limitation comes from the fact that passing `environment_variables` directly in `SimpleSynthAction` sets them on the CodePipeline configuration for an Action, and that configuration has a limit of 1,000 characters.

Passing them inside `environment` sets them on the CodeBuild Project itself, which does not have a size limitation. _However_, it's important to note that you can't use CodePipeline Variables in this case.

Does this make sense @gshpychka?

**Comment by gshpychka** [comment]
Yes! One more thing, and I apologize: what are CodePipeline Variables?

**Comment by skinny85** [comment]
It's a CodePipeline feature that allows you to easily transfer certain information between Actions in a CodePipeline - for example, a source Action can easily transmit what is the Git hash of the last commit that triggered the Action.

More information: https://docs.aws.amazon.com/codepipeline/latest/userguide/reference-variables.html

**Comment by gshpychka** [comment]
@skinny85 I opened a PR, please advise regarding further steps

**Comment by skinny85** [comment]
> @skinny85 I opened a PR, please advise regarding further steps

Next steps would be me reviewing the PR 🙂.
