### ISSUE TITLE
(aws-ec2): Multi-region VPC and Peering specification in the same app

### ISSUE THREAD

**Issue by wobbals** [aws/aws-cdk#12754]
### The Question

Is it possible to define/synth/deploy a pair (or series even) of VPCs and peer them all in the same CDK app? I've found that, in allocating `ec2.Vpc` instances in separate regional stacks, the attributes of the VPC (eg.`vpcId`) are Token strings that cannot be referenced in the specification for a `CfnVPCPeeringConnection`:

```ts
const vpc =  new Vpc(this, `my-vpc-${id}`, {
  cidr,
  //...
})
console.log(vpc.vpcId) // ${Token[TOKEN.67]}
```

Referencing the above `vpcId` token in a peering connection is illegal:

```ts
const pcx = new CfnVPCPeeringConnection(this, description, {
  vpcId: leftVPC.vpcId, // '${Token[TOKEN.364]}'
  peerVpcId: rightVPC.vpcId, // '${Token[TOKEN.67]}'
  peerRegion: rightVPC.region,
})
// Stack [...] cannot consume a cross reference from stack...

const pcx = new CfnVPCPeeringConnection(this, description, {
  vpcId: leftVPC.vpcId, // 'vpc-12345'
  peerVpcId: rightVPC.vpcId, // 'vpc-23456'
  peerRegion: rightVPC.region,
})
// works
```

To work around this, I can split the VPC and the peering connections into separate CDK apps, feeding the output vpcIDs/regions of the former into the ladder. If this is not a bug or is intended behavior, any suggestions about how I might go about streamlining the approach would be helpful.

### Environment

  - **CDK CLI Version:** `1.87.0 (build be72c59)`
  - **Module Version:** `1.87.0`
  - **Node.js Version:** `v14.15.1`
  - **OS:** `osx 10.15.7`
  - **Language (Version):** `typescript 3.9.7`

**Comment by rix0rrr** [comment]
CDK will not be able to share VPC IDs between accounts and regions. If your stacks in the same account/region, everything will work. Otherwise you will need a different mechanism to transport those values. Either by inserting them by hand, using `Vpc.fromLookup()` (after the initial VPC has been deployed), or writing custom resources to propagate those values cross-region/cross-account.

**Comment by rcollette** [comment]
@rix0rrr Did you mean `Vpc.fromAttributes` rather than `Vpc.fromLookup`?   `Vpc.fromLookup` to another account requiring another set of credentials doesn't appear to work.   Would be fantastic if the env struct would allow a profile name to be specified and CDK could use multiple credentials.
