### ISSUE TITLE
(lambda): Retain Existing Lambda Aliases When Adding an Alias to Version

### ISSUE THREAD

**Issue by baumannalexj** [aws/aws-cdk#12751]
Would like to manage multiple Lambda Alias from CDK deploy. We want to update an Alias to point to a specific version without deleting existing Aliases.

Whenever we try to add an alias to a Lambda Version, it deletes existing Aliases:
```
 lambdaFunction.currentVersion.addAlias( <alias name>,{
                        description: DATETIME_ISO
                    })
```

### Use Case

We want to manage multiple aliases for a single lambda. We will deploy multiple versions, but when we "release" we will point the alias(es) to a specific version.

example of what we want: 
          versions deployed 
          29
          28 <- QA
          27
          26
          25 <- DEV
          24

### Proposed solution 
Add an Alias removal policy 

```
a removal policy when adding an alias
cdkLambda.Version
           .fromVersionArn(...get function version...)
           .addAlias( <aliasName>, {

                        description: CDK_CONFIG.DATETIME_ISO
                           ...
                       retentionPolicy: cdkLambda.Alias.RentionPolicy.RETAIN_OTHER_ALIASES
})
  
```

### Other

Example of my cdk code to deploy lambda:
```
const lambda = require("@aws-cdk/aws-lambda");

const lambdaFunction = new lambda.Function(this, `lambda-${CDK_CONFIG.ENV_LOWER}`, {
            functionName: `${CDK_CONFIG.FUNCTION_NAME}`,
            runtime: lambda.Runtime.NODEJS_12_X,
            code: lambda.Code.fromAsset(`../${CDK_CONFIG.FUNCTION_NAME}.zip`),
            handler: "src/index.handler",
            description: CDK_CONFIG.DATETIME_ISO,
            currentVersionOptions: {
                removalPolicy: cdk.RemovalPolicy.RETAIN,
                // codeSha256:
            },
            timeout: CDK_CONFIG.LAMBDA_TIMEOUT,
            memorySize: CDK_CONFIG.LAMBDA_MEMORY_SIZE,
            vpc: lambdaVpc,

            vpcSubnets: {
                subnets: [
                    {subnetId: cdk.Fn.importValue("k8s-subnet-a-lambda")},
                    {subnetId: cdk.Fn.importValue("k8s-subnet-b-lambda")},
                ]
            },
            securityGroups: [
                {securityGroupId: "a"},
                {securityGroupId: "b"},
                {securityGroupId: "c"},
            ],

            environment: {
                ENVIRONMENT: CDK_CONFIG.ENV_UPPER,
                LOG_LEVEL: CDK_CONFIG.LOG_LEVEL
            },
        });

if ( updateAliasToThisVersion ) {
 lambdaFunction
                    .currentVersion
                    .addAlias(CDK_CONFIG.ENV_UPPER ,{
                        description: CDK_CONFIG.DATETIME_ISO
                    })
} 
```

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by nija-at** [comment]
Hi @baumannalexj -

Thanks for filing this feature request.

To support this natively in the CDK would need a bit of design work to see how it can be achieved and build an easy to use customer experience.

However, you can achieve the same on your end by managing all of the versions in the CDK. Instead of using `currentVersion`, explicitly creating a new `Version` constructs each time your version changes and overriding its logical id.

```ts
const version1 = new Version(this, 'Version1', {
  lambda: lambdaFunction,
});
version1.overrideLogicalId('version1');

const version2 = new Version(this, 'Version1', {
  lambda: lambdaFunction,
});
version2.overrideLogicalId('version2');
```

To point an alias at one of these versions, you just create an `Alias` construct and pass the required version in its props.

Could you check if this works for you?

**Comment by baumannalexj** [comment]
hi @nija-at 

Thank you for responding. I am out of town for a week or so, and don't want this to be closed. I will try when I get back.

**Comment by baumannalexj** [comment]
@nija-at  I will not be able to test this with the scope of work we have. Thank you for the suggestion, we can close the ticket if that's the protocol.

**Comment by nija-at** [comment]
I'm keeping this issue in our backlog as a way to implement in this in a more elegant way.

**Comment by baumannalexj** [comment]
Thank you @nija-at !

**Comment by creatorrr** [comment]
Any update on this, @nija-at ?

**Comment by rix0rrr** [comment]
If all you want is really to retain the existing `Alias` when you define a new name, then setting a retention policy will be enough:

```ts
(alias.node.defaultChild as CfnResource).applyRemovalPolicy(RemovalPolicy.RETAIN);
```

However, that still won't allow you to achieve this:

```
29
28 <- QA
27
26
25 <- DEV
24
```

Which looks like something else: it looks like there will always be 2 aliases that in a controlled fashion get pointed to a different version. In a CDK+CFN deployment, there isn't really a way to switch on that "yes update the Alias, no don't update the Alias" on a per-deployment basis.

You could make it with a custom resource, but this is not how we expect CDK to be used. We would expect different Stacks to be deployed for DEV and QA stages, preferably in different accounts.

**Comment by snowe2010** [comment]
@rix0rrr Our team's account manager (A. Langford) had said that the cdk team _was_ working on this issue. Our problem is not solved with separate stacks. We want to retain an alias for _every_ version that we deploy (we deploy hundreds of versions for a single stack, never updating old versions). Are you saying that setting the retention policy will be enough to accomplish that?

**Comment by snowe2010** [comment]
It seems like `(alias.node.defaultChild as CfnResource).applyRemovalPolicy(RemovalPolicy.RETAIN);` might work for our use case.

**Comment by harry77914** [comment]
![image](https://github.com/aws/aws-cdk/assets/128270310/f94451fa-45bf-4e67-b466-9859ecdd0aa0)

How do I achieve this in Java. Tried above and still the old alias gets removed from old version and new one gets created with this new version.
