### ISSUE TITLE
step-functions: implement IEventRuleTarget, add grant() methods

### ISSUE THREAD

**Issue by rix0rrr** [aws/aws-cdk#1275]
To improve the usability of Step Functions library, we should do these things.

Came up on Gitter channel.

(While at it, Chain() has a crazy constructor signature, which should mostly have been a copy constructor I think)

**Comment by nija-at** [comment]
StateMachine now has [`grantStartExecution()` API](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-stepfunctions/lib/state-machine.ts#L86) and a [state machine event target](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-events-targets/lib/state-machine.ts)

Closing.
