### ISSUE TITLE
(aws-certificatemanager): Can't add imported (custom) certificate to cloudfront distribution

### ISSUE THREAD

**Issue by I2olanD** [aws/aws-cdk#12750]
Hello,

i'm trying to add a imported certificate to my cloudfront distribution. While in the console it works just fine, via cloudformation i get problems.

Cloudformation runs into following error:
One or more of the CNAMEs you provided are already associated with a different resource.

### The Question
How do i properly add a imported (custom) certificate to a cloudfront distribution? I don't want to setup Route 53 for this. I just want to add the certificate.

```
const certificate = importMyCertificate(arn);

...
return new Distribution(this.scope, distributionId, {
	defaultBehavior: {
		origin,
		allowedMethods,
		cachePolicy,
		originRequestPolicy,
		viewerProtocolPolicy
	},
	domainNames,
	certificate,
	webAclId
});
```

### Environment

  - **CDK CLI Version:** 1.79.0
  - **Module Version:** 1.79.0
  - **Node.js Version:** 12.18.0

Thank you very much! 

Edit:

The distribution was already deployed without the certificate and i'm trying to run a "update".

**Comment by njlynch** [comment]
Have you un-associated the domain names from any other distributions, including the ones you did by hand in the console? This is usually the cause of the error. If you associated your certificate and domain(s) with a distribution in the console, that change would need to be reverted, and the distribution would need to have completely updated before you can re-associate that domain with the distribution again. CloudFront has some good documentation surrounding this:

https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/CNAMEs.html#alternate-domain-names-move

**Comment by I2olanD** [comment]
Hello @njlynch,

thanks for the quick response! The only thing i did, was adding the certificate in the cloudfront console. All of my distributions are back using the default *.cloudfront.net certificate.

**Comment by njlynch** [comment]
This isn't an issue with the certificate _per se_, this is related to the domains you're passing in via the `domainNames` property. One (or more) of the domain names listed there is associated with another CloudFront distribution -- in the same account or another. I'd suggest working through the linked guide, and/or use a tool like `dig` to discover what those domains are currently pointing to.

**Comment by I2olanD** [comment]
As far as i can see, there's  no distribution associated with the values inside domainNames. Thank you for help! I will dig into this :)

**Comment by I2olanD** [comment]
You're right! I'm deploying 2 distributions at the same time and had the same domain associated for both! I'm separating them now for each environment.

**Comment by njlynch** [comment]
Glad you found the culprit!
