### ISSUE TITLE
(codedeploy): addExecuteFileCommand with installAgent set to true fails 

### ISSUE THREAD

**Issue by timothy-mcphie** [aws/aws-cdk#12764]
When using `addExecuteFileCommand` for EC2 user data on an ASG associated with a Code Deploy deployment group with `installAgent` set to true, the generated user data script will fail if the dependencies are already installed/install commands exit with non zero statuses.

### Reproduction Steps
```ts
const asg = new AutoScalingGroup(this, "ASG", { ...props });

asg.userData.addExecuteFileCommand({ filePath: "some/path" });

new ServerDeploymentGroup(this, "DeploymentGroup", {
    autoScalingGroups: [asg],
    installAgent: true,
});
```
### What did you expect to happen?

- My file to be executed and the Code Deploy agent + dependencies to be installed.

### What actually happened?

- My file executed, but the script failed on installing the Code Deploy agent + dependencies 

### Other
The generated user data script looks like this:

```sh
#!/bin/bash
set -e
chmod +x 'some/path'
'some/path' undefined
PKG_CMD=`which yum 2>/dev/null`
if [ -z "$PKG_CMD" ]; then
PKG_CMD=apt-get
else
PKG=CMD=yum
fi
$PKG_CMD update -y
$PKG_CMD install -y ruby2.0
if [ $? -ne 0 ]; then #won't be run - script will fail out
$PKG_CMD install -y ruby
fi
$PKG_CMD install -y awscli
TMP_DIR=`mktemp -d`
cd $TMP_DIR
aws s3 cp s3://aws-codedeploy-eu-west-1/latest/install . --region eu-west-1
chmod +x ./install
./install auto
rm -fr $TMP_DIR
```

The [install agent code](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-codedeploy/lib/server/deployment-group.ts#L350-L368) relies on exit codes of commands to determine what to do, whilst the [`addExecuteFileCommand` code](https://github.com/aws/aws-cdk/blob/a72cfbd5d0f9af87aacf0657a6fc370ce2a23c55/packages/%40aws-cdk/aws-ec2/lib/user-data.ts#L165-L170) adds a `set -e` to fail the script if the file fails to run, but never swaps the flag back.

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Thanks for the report @timothy-mcphie !

This should be a simple fix [adding `set +e` to the beginning of the CodeDeploy agent install script](https://github.com/aws/aws-cdk/blob/6e2c0e9f6a50a66a12f9bfd477339fec8f87145e/packages/%40aws-cdk/aws-codedeploy/lib/server/deployment-group.ts#L350-L369). Any chance you could submit us a PR with the fix? Here's our Contribution Guide: https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md .

Thanks,
Adam

**Comment by timothy-mcphie** [comment]
Semi related issue https://github.com/aws/aws-cdk/issues/12946
