### ISSUE TITLE
(@aws-cdk/aws-ssm): grantRead in Integration Test fails compile

### ISSUE THREAD

**Issue by shellscape** [aws/aws-cdk#12760]
The integration tested located here: https://github.com/aws/aws-cdk/blob/HEAD/packages/@aws-cdk/aws-ssm/test/integ.parameter.lit.ts

Contains a grant on line 22: `param.grantRead(role);`

I'm unsure how the test is passing, as that doesn't pass TypeScript muster. It fails to compile.

### Reproduction Steps

Install `@aws-cdk/aws-ssm` and the other dependencies in that file, replace the import of `../lib` on line 3 with `@aws-cdk/aws-ssm`. Attempt to compile.

### What did you expect to happen?

I expected the code in the integration test to be compilable by TypeScript

### What actually happened?

`Argument of type 'Role' is not assignable to parameter of type `IGrantable'`

### Environment

  - **CDK CLI Version  :** 1.87.0 (build be72c59)
  - **Framework Version:** <unsure>
  - **Node.js Version:**  14.15.4
  - **OS               :** MacOS
  - **Language (Version):**  Typescript 4.1.3

### Other

--- 

This is :bug: Bug Report

**Comment by shellscape** [comment]
This appears to be some kind of dependency collision/confusion:

```
error TS2345: Argument of type 'import("/Users/<user>/code/medly/noapp-task-service/node_modules/@aws-cdk/aws-iam/lib/policy-statement").PolicyStatement' is not assignable to parameter of type 'import("/Users/<user>/code/medly/noapp-task-service/node_modules/@aws-cdk/aws-cloudwatch/node_modules/@aws-cdk/aws-iam/lib/policy-statement").PolicyStatement'.
  Types have separate declarations of a private property 'action'.

 67       new PolicyStatement({
          ~~~~~~~~~~~~~~~~~~~~~
 68         sid: 'sns-allow',
    ~~~~~~~~~~~~~~~~~~~~~~~~~
... 
 71         actions: ['kms:Decrypt', 'kms:GenerateDataKey'],
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by MrArnoldPalmer** [comment]
So this is an issue with typescript, since you're replacing the import of a type that exists in the local module, with one installed elsewhere, there are two separate versions of the module being resolved. Those two versions of `PolicyStatement` are not equivalent. I know this is kinda funky because typescript is "structurally typed" and these two versions of the class are structurally compatibly, but in fact TS treats them as different types.

[The docs](https://www.typescriptlang.org/docs/handbook/classes.html) have this to say on the subject:

>TypeScript is a structural type system. When we compare two different types, regardless of where they came from, if the types of all members are compatible, then we say the types themselves are compatible.
>
>However, when comparing types that have private and protected members, we treat these types differently. For two types to be considered compatible, if one of them has a private member, then the other must have a private member that originated in the same declaration. The same applies to protected members.

Reopen this if you have additional info or I'm missing something related.

**Comment by shellscape** [comment]
I'm somewhat unsure of what the solution here would be. Others happening across this will also be starting into the abyss. If we're just pointing at TS and saying that it's confused... do we need to report this to the TS project, or can the CDK project do something more to guard against this? Or, is there a guard we can add as users?

**Comment by athewsey** [comment]
@MrArnoldPalmer I also recently came across something similar with `@aws-cdk/aws-dynamodb` trying to use `ddbTable.grantWriteData(iamRole)`: And agree that (to me at least?) the solution is not obvious...

@shellscape perhaps you could re-open this issue, unless I'm missing something easy here?
