### ISSUE TITLE
(aws-lambda-python): Change assetHashType to cdk.AssetHashType.SOURCE

### ISSUE THREAD

**Issue by fsmanuel** [aws/aws-cdk#12770]
I noticed that my lambda layers get rebuild everytime I run the cdk.

Becaus the current implementation defines `cdk.AssetHashType.BUNDLE` it has some side effects if dependencies change. I can mitigate the side effects by specifining the versions in the `requirements.txt` e.g. `pandas==1.1.*` but still it always bundles the layer even if nothing changes.

I would propose to change the `assetHashType` to `SOURCE` especially because `BUNDLE` is deprecated and the suggested change to `OUTPUT` would still have the described side effects mentioned above.

https://github.com/aws/aws-cdk/blob/7dc45b2d8fc2f63497adb624fdfe4207c4eca269/packages/%40aws-cdk/aws-lambda-python/lib/bundling.ts#L65

That would also solve #12684

**Comment by TLadd** [comment]
Would the fix for this also address aws-lambda-nodejs? As seen in https://github.com/aws/aws-cdk/issues/11625#issuecomment-771306806, node js lambda functions always end up being rebuilt as well.

**Comment by fsmanuel** [comment]
@TLadd no, the current PR only addresses the python lambdas. But for nodejs the same approach would work:

https://github.com/aws/aws-cdk/blob/7dc45b2d8fc2f63497adb624fdfe4207c4eca269/packages/%40aws-cdk/aws-lambda-nodejs/lib/bundling.ts#L37-L42

Currently we are discussing the best solution to this in the PR #12984
