### ISSUE TITLE
(aws-elasticloadbalancingv2): Can't get Arn from Target Group

### ISSUE THREAD

**Issue by tomburge** [aws/aws-cdk#12797]
The default actions JSON for creating a CfnListener is being misinterpreted when the synth occurs.

### Reproduction Steps

`        self.hz_int_elb_listener_443 = elb.CfnListener(self,
            id='Horizon Internal Elastic Load Balancer 443 Listener',
            load_balancer_arn=self.hz_int_elb.ref,
            port=443,
            protocol='HTTPS',
            ssl_policy='ELBSecurityPolicy-2016-08',
            certificates=[
                elb.CfnListener.CertificateProperty(
                    certificate_arn=main_stack.hz_cert_arn.value_as_string
                )
            ],
            default_actions=[
                {
                    "type" : "forward",
                    "ForwardConfig" : {
                        "TargetGroups" : [{
                            "TargetGroupArn" : self.hz_int_elb_tg.ref,
                            "Weight" : 1
                        }]
                    }
                }
            ]
        )`

### What did you expect to happen?

The expected behavior is to show the Object Ref in the created CF template.

### What actually happened?

The Object reference does not show up.

### Environment

  - **CDK CLI Version:** 1.87.0 (build be72c59)
  - **Module Version:** 1.87.0
  - **Node.js Version:** v12.18.3
  - **OS:** Windows 10
  - **Language (Version):** Python 3.8.5

### Other

The CfnListener docs page (https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_elasticloadbalancingv2/CfnListener.html) shows default_actions as one of the parameters in the form of a list. It says there is an ActionProperty you can use, but you can also just use the raw JSON like you would for CloudFormation.

The problem occurs as follows:

The keyword Type is used instead of the keyword type. 

You get this error on synth:

jsii.errors.JSIIError: Value did not match any type in union: Value did not match any type in union: Missing required properties for @aws-cdk/aws-elasticloadbalancingv2.CfnListener.ActionProperty: type, Expected object reference, got {"$jsii.map":{"Type":"forward","TargetGroupArn":"${Token[TOKEN.267]}"}}, Expected object reference, got [{"$jsii.map":{"Type":"forward","TargetGroupArn":"${Token[TOKEN.267]}"}}]

Notice it says missing required properties: type. The CloudFormation reference shows type as capitalized. Reference: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticloadbalancingv2-listener-action.html

The next problem is this:

The keyword TargetGroupArn is used instead of targetGroupArn.

The synth works fine, but you get this error from CloudFormation:

A target group ARN must be specified (Service: ElasticLoadBalancingV2, Status Code: 400, Request ID: a4ebd58b-00c0-4f74-b704-aa3ca85067ac, Extended Request ID: null)

When you look at the template that was synthed then TargetGroupArn is completely missing and there was no synth error:

This also happens with the other keywords that would be used in the JSON like RedirectConfig, ForwardConfig, etc.

The problem at first glance seems to be code looking for properly cased keywords and not handling exceptions properly.
--- 

This is :bug: Bug Report

**Comment by njlynch** [comment]
It looks like you're passing in a list + dict into the `default_actions` argument, rather than a List of `ActionProperty` as the docs specify.  That's likely the cause of the issues you're encountering. Try something closer to this:

```
        self.hz_int_elb_listener_443 = elb.CfnListener(self,
            id='Horizon Internal Elastic Load Balancer 443 Listener',
            load_balancer_arn=self.hz_int_elb.ref,
            port=443,
            protocol='HTTPS',
            ssl_policy='ELBSecurityPolicy-2016-08',
            certificates=[
                elb.CfnListener.CertificateProperty(
                    certificate_arn=main_stack.hz_cert_arn.value_as_string
                )
            ],
            default_actions=[
                elb.CfnListener.ActionProperty(
                    type: "forward",
                    forward_config: elb.CfnListener.ForwardConfigProperty(
                        target_groups: [elb.CfnListener.TargetGroupTupleProperty(
                            target_group_arn: self.hz_int_elb_tg.ref,
                            weight: 1
                        }]
                    }
                }
            ]
        )
```
