### ISSUE TITLE
(ecs-patterns): Add support for public IP assignment on QueueProcessingFargateService construct

### ISSUE THREAD

**Issue by lnregalias** [aws/aws-cdk#12815]
Allow specifying the `assignPublicIp` property for `QueueProcessingFargateService`

### Use Case

Allow the use of public IPs and subnets with `QueueProcessingFargateService`

### Proposed Solution

Add a `assignPublicIp` property to `QueueProcessingFargateService`, which could be propagated to the underlying `FargateService` construct here:

https://github.com/aws/aws-cdk/blob/8990e8fbdd7fa6fc6d31fa7090cb916d1b7917c0/packages/%40aws-cdk/aws-ecs-patterns/lib/fargate/queue-processing-fargate-service.ts#L109

### Other

https://github.com/aws/aws-cdk/issues/12603 has a workaround noted, though not ideal.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by lgvo** [comment]
I can change https://github.com/aws/aws-cdk/pull/12604 to cover both https://github.com/aws/aws-cdk/issues/12815  and https://github.com/aws/aws-cdk/issues/12603. I just need to know if we API changes are ok and maybe have someone take a quick look on the PR before I put any more work on it.
