### ISSUE TITLE
(aws-events-targets): Change taskDefinition property to ITaskDefinition in EcsTask

### ISSUE THREAD

**Issue by stephenwiebe** [aws/aws-cdk#12811]
`EcsTaskProps` requires a `taskDefinition` property of type `TaskDefinition`, whereas the rest of the properties accept the imported constructs. This means we can't import an `ITaskDefinition` with `TaskDefinition.fromTaskDefinitionArn` and use it with `EcsTask`. Unless there is some needed capability not supported in `ITaskDefinition`, the type should be changed to support the imported `ITaskDefinition`.

### Use Case

I would like to create an `EcsTask` event target with an `ITaskDefinition`.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by otaviomacedo** [comment]
I don't think that's possible. `EcsTask` needs at least two attributes from `TaskDefinition`  that are not defined in `ITaskDefinition`: `node` and `networkMode`.
