### ISSUE TITLE
aws-ecs: accessing the log group name

### ISSUE THREAD

**Issue by jonny-rimek** [aws/aws-cdk#12849]
## :question: General Issue

I'm looking to build a dashboard with a log query widget, for which I need the log group name. 

Is there a way to get the name of the log group name that get's created automatically?
If not as far as I have seen I can give it a specific name, which is probably not ideal, for the same reason we shouldn't give s3 bucket's specific names

UPDATE:

I tried creating a logGroup before hands and passing it in, but it doesn't work, because LogGroup doesn't implement ILogGroup

```ts
    const nginxLoggroup = new LogGroup(this, "NginxLog", {
      retention: RetentionDays.ONE_WEEK,
    })

    const nginx = taskDefinition.addContainer("Nginx", {
      image: nginxImage,
      essential: true,
      logging: ecs.LogDrivers.awsLogs({
        logGroup: nginxLoggroup,
      }),
    })
```
`Type 'LogGroup' is not assignable to type 'ILogGroup'.
  The types of 'addStream(...).stack.tags' are incompatible between these types.
    Type 'import("/home/jonny/dev/aws/node_modules/@aws-cdk/aws-logs/node_modules/@aws-cdk/core/lib/tag-manager").TagManager' is not assignable to type 'import("/home/jonny/dev/aws/node_modules/@`

Not sure how one would ever use the loggroup property here, if the above doesn't work. I can get the name if I create a log group myself so that would solve the issue in theory

### Environment

  - **CDK CLI Version:** 1.87.1

**Comment by peterwoodworth** [comment]
Hey @jonny-rimek,

Check your `aws-ecs` and `aws-logs` module imports in package.json to see what version they are. Chances are that this is a versioning issue, an interface of one version cannot be assigned to an interface of another version. Please let me know if this is the case, if it is not we will continue to investigate.

**Comment by jonny-rimek** [comment]
@peterwoodworth I thought I didn't have aws-logs installed and did npm install it, thus upgrading it, above the other packages and shooting myself in the foot.

thanks for the help.

**Comment by jonny-rimek** [comment]
working code:

```ts
    const logGroup = new LogGroup(this, "ShopLog", {
      retention: RetentionDays.ONE_WEEK,
    })
    this.logGroupName = logGroup.logGroupName

    const shopContainer = taskDefinition.addContainer("Shop", {
      image: shopImage,
      essential: true,
      logging: ecs.LogDrivers.awsLogs({
        streamPrefix: "shop",
        logGroup: logGroup,
      }),
    })
```

```ts

    new cloudwatch.Dashboard(this, "Logs", {
      dashboardName: props.logDashboardName,
    }).addWidgets(
      new Row(
        new LogQueryWidget({
          logGroupNames: [props.logGroupName],
          height: 12,
          width: 24,
          queryLines: ["fields @timestamp, @message", "sort @timestamp desc"],
        })
      ),
    )
```
