### ISSUE TITLE
(aws-cdk/aws-apigateway): Migrating API Gateway Custom domain name Endpoint type

### ISSUE THREAD

**Issue by ReethiJ** [aws/aws-cdk#12845]
### Use Case

I am trying to modify my API Gateway custom domain name endpoint type from regional to edge but I receive the error:

`"Can only perform one update operation at a time. Request would delete regional endpoint, create edge endpoint"`

Ideally, to [migrate a custom domain name endpoint type](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-regional-api-custom-domain-migrate.html), we need to first add the other endpoint type, update the DNS records  and then remove the other endpoint type. Due to this reason, in Cloudformation the [EndpointConfiguration property ](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apigateway-domainname-endpointconfiguration.html)allows a list of Types.

When I attempted to add a similar configuration in CDK:
```
endpointType: [api.EndpointType.EDGE,  api.EndpointType.REGIONAL]
```
I received the error: 
```
CfnSynthesisError: Resolution error: Supplied properties not correct for "CfnDomainNameProps"
  endpointConfiguration: supplied properties not correct for "EndpointConfigurationProperty"
    types: element 0: ["EDGE","REGIONAL"] should be a string.
```

It would be great if there is a way to migrate a domain name endpoint type in CDK.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by nija-at** [comment]
I tried the following sample app and was able to successfully synthesize -

``ts
import { Stack, App } from '@aws-cdk/core';
import { EndpointType, RestApi } from '@aws-cdk/aws-apigateway';

const app = new App();
const stack = new Stack(app, 'MyStack');

const api = new RestApi(stack, 'Api', {
  endpointTypes: [EndpointType.EDGE, EndpointType.REGIONAL]
});
const resource = api.root.addResource('books')
resource.addMethod('GET');
```

The synthesized template contains the resource type snippet - 

```
  "ApiF70053CD": {
      "Type": "AWS::ApiGateway::RestApi",
      "Properties": {
        "EndpointConfiguration": {
          "Types": [
            "EDGE",
            "REGIONAL"
          ]
        },
        "Name": "Api"
      },
      "Metadata": {
        "aws:cdk:path": "MyStack/Api/Resource"
      }
```

Could you provide a sample app that doesn't work for you?

**Comment by ReethiJ** [comment]
This is issue is specific to endointType defined under domainName. Here is a sample snippet: 

```
const restApi = new api.RestApi(this, 'CDK-API', {
            restApiName: 'CDK-API',
            domainName: {
                domainName: 'abc.com',
                certificate:  acm.Certificate.fromCertificateArn(this, 'ACM_Certificate','arn:aws:acm:us-east-1:xxxxxx:certificate/xxxxxx'),
                endpointType: [api.EndpointType.EDGE, api.EndpointType.REGIONAL]
                  
            }
        });
```

With the above code I get the below provided error message on attempting to synthesize the template.

```
CfnSynthesisError: Resolution error: Supplied properties not correct for "CfnDomainNameProps"
  endpointConfiguration: supplied properties not correct for "EndpointConfigurationProperty"
    types: element 0: ["EDGE","REGIONAL"] should be a string.
```

Please let me know if any additional information is required.
