### ISSUE TITLE
Cannot set sessionTimeout for elbv2.ListenerAction

### ISSUE THREAD

**Issue by lmichelbacher** [aws/aws-cdk#12843]
For `ListenerAction.authenciateOidc()`, `sessionTimeout` is supposed to be a Duration ([docs](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-elasticloadbalancingv2.AuthenticateOidcOptions.html#sessiontimeout)).

I’m probably missing something really obvious here but 
when I do

```ts
    return elbv2.ListenerAction.authenticateOidc({
       ...,
       sessionTimeout: Duration.seconds(36000)       
    });
```
I get

> `sessionTimeout: “36000” should be a number` 

When I do
```ts
    return elbv2.ListenerAction.authenticateOidc({
       ...,
       sessionTimeout: 36000
    });
```
I get 

> Type 'number' is not assignable to type 'Duration | undefined'

I believe this has to do with a recent change in CloudFormation and a change in CDK ([commit](https://github.com/aws/aws-cdk/pull/11539/commits/f8fffbddf3eeea285a4187f38ade887c1a4478ba)). Two related resource types have a `sessionTimeout` parameter but with different types

1. AWS::ElasticLoadBalancingV2::Listener -> String (changed recently from Integer)
    * => CfnListener construct
1. AWS::ElasticLoadBalancingV2::ListenerRule -> Integer
    * => CfnListenerRule construct

Arguably, it would be better if the type was consistent in CloudFormation but the customer-facing bug is technically in CDK.

### Environment

MonoCDK 1.75

**Comment by njlynch** [comment]
Thanks for the bug report and research.

If I understand correctly, the error occurs when using `authenticateOidc` on an `ApplicationListenerRule` (not an `ApplicationListener`). This is because while technically in CloudFormation there are distinct types for `AuthenticateOidcConfig` ([ListenerRule AuthenticateOidcConfig](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticloadbalancingv2-listenerrule-authenticateoidcconfig.html) and [Listener AuthenticateOidcConfig](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticloadbalancingv2-listener-authenticateoidcconfig.html)), in the CDK it's modelled as the same config (because it *was*, until the type was changed in a backwards-incompatible way in version v20.3.0 of the spec).

The dumbest fix I can think of off the bat is to have the ListenerRule/Listener post-process the action and convert the type to the correct one at final render. I'm hoping there's something just a tad more clever we can come up with though. Suggestions and PRs welcome!

**Comment by Pouja** [comment]
Is there any workaround for this at the moment?
Maybe a stupid question, but why not compile it to `AWS::ElasticLoadBalancingV2::Listener` instead of `AWS::ElasticLoadBalancingV2::ListenerRule` ? 
Or provide an `ListenerAction` and a `ListenerActionRule` since they are different in 2 properties.

**Comment by lmichelbacher** [comment]
> If I understand correctly, the error occurs when using authenticateOidc on an ApplicationListenerRule (not an ApplicationListener). 

It's on an `ApplicationListener` object.

```
const listener = new elbv2.ApplicationListener(...);
listener.addAction("...",  {
  action: elbv2.ListenerAction.authenticateOidc(...);
})
```

> post-process the action and convert the type to the correct one at final render

Is that something I can do client-side?

**Comment by lmichelbacher** [comment]
This worked:

```typescript
listenerAction["actionJson"].authenticateOidcConfig.sessionTimeout = 36000;
```

**Comment by enricopesce** [comment]
The same for me: 

```
this.listener.addAction('web_app_protected', {
				priority: 110,
				conditions: [
					elbv2.ListenerCondition.pathPatterns(['/*']),
				],
				action: elbv2.ListenerAction.authenticateOidc({
					authorizationEndpoint: 'xxxx',
					clientId: 'xxxx',
					clientSecret: xxxx),
					issuer: 'xxx',
					tokenEndpoint: 'xxx',
					userInfoEndpoint: 'xxxx',
					next: elbv2.ListenerAction.forward([this.target_group_web_app]),
					sessionTimeout: cdk.Duration.days(1)
				})
```

Resolution error: Supplied properties not correct for "CfnListenerRuleProps"
  actions: element 0: supplied properties not correct for "ActionProperty"
    authenticateOidcConfig: supplied properties not correct for "AuthenticateOidcConfigProperty"
      sessionTimeout: "86400" should be a number.

Fortunately, the sessionTimeout prop is optional but I need to reduce it from 7 days to 1! :)

With:

CDK 1.90.1 (build 0aee440)
Typescript Version 4.1.5

**Comment by lmichelbacher** [comment]
Hi Enrico,

See my previous comment for a workaround.

**Comment by httpdigest** [comment]
While I was trying to refactor my CDK TypeScript code away from using the cfn `elbv2.CfnListenerRule` resource towards the `elbv2actions.AuthenticateCognitoAction` construct, I also hit that issue with the `sessionTimeout`. So, for the time being I am going to stay at using `elbv2.CfnListenerRule` as a workaround.

**Comment by IllarionovDimitri** [comment]
Hi all

run into the same problem. 

In my project I have ALB with 3 path based rules (default action, rule with prio1 and rule with prio2)

Find following solution (replaced some project specific implementations with ...):

```
        alb_listener_443 = elbv2.ApplicationListener(
            self,
            "alb_listerner443",
            load_balancer=alb,
            port=443,
            ....
        )

        self.alb_listener_443.add_action(
            "forward_to_target_one_action",
            action=elbv2.ListenerAction.forward(...),
            conditions=[elbv2.ListenerCondition.path_patterns(["/path_abc"])],
            priority=1,
        )

        self.alb_listener_443.add_action(
            "forward_to_target_two_action",
            action=actions.AuthenticateCognitoAction(
                # here I want to set session timeout, but it didn't work, hence workaround via cfn_listener_443 below                
                # session_timeout=Duration.seconds(3600), 
                ),
            ),
            conditions=[elbv2.ListenerCondition.path_patterns(["/path_xyz"])],
            priority=2,
        )

        cfn_listener_443 = self.alb_listener_443.node.children[2].node.default_child

        cfn_listener_443.add_property_override(
            "Actions.0.AuthenticateCognitoConfig.SessionTimeout", 7200
        )
``
