### ISSUE TITLE
CdkPipeline: resource naming, compliance and customizations

### ISSUE THREAD

**Issue by OperationalFallacy** [aws/aws-cdk#12856]
Hi,

Just wanted to clarify something for CdkPipeline, when it is declared the cdk creates pipeline stack with a LOT of things.

I'm working atm in a medium size enterprise and there are some standard, about naming convention, IAM policies etc.

My questions are:
1. Is there a way to re-use any of these between projects? These seems like waste of resources to create for each app. Unless this is designed to run in app-dedicated aws micro accounts.
2. Is there a way to customize any of these below? For example I could re-use some of existing roles, buckets... Or is it designed to go in all as one package?

Thank you!
```
// [+] AWS::KMS::Key Pipeline/Pipeline/ArtifactsBucketEncryptionKey PipelineArtifactsBucketEncryptionKeyF5BF0670
// [+] AWS::KMS::Alias Pipeline/Pipeline/ArtifactsBucketEncryptionKeyAlias PipelineArtifactsBucketEncryptionKeyAlias94A07392
// [+] AWS::S3::Bucket Pipeline/Pipeline/ArtifactsBucket PipelineArtifactsBucketAEA9A052
// [+] AWS::IAM::Role Pipeline/Pipeline/Role PipelineRoleB27FAA37
// [+] AWS::IAM::Policy Pipeline/Pipeline/Role/DefaultPolicy PipelineRoleDefaultPolicy7BDC1ABB
// [+] AWS::CodePipeline::Pipeline Pipeline/Pipeline Pipeline9850B417
// [+] AWS::IAM::Role Pipeline/Pipeline/Source/CodeCommit/CodePipelineActionRole PipelineSourceCodeCommitCodePipelineActionRole48F8DEFA
// [+] AWS::IAM::Policy Pipeline/Pipeline/Source/CodeCommit/CodePipelineActionRole/DefaultPolicy PipelineSourceCodeCommitCodePipelineActionRoleDefaultPolicy3CEB31C0
// [+] AWS::IAM::Role Pipeline/Pipeline/EventsRole PipelineEventsRole96280D9B
// [+] AWS::IAM::Policy Pipeline/Pipeline/EventsRole/DefaultPolicy PipelineEventsRoleDefaultPolicy62809D8F
// [+] AWS::IAM::Role Pipeline/Pipeline/Build/Synth/CodePipelineActionRole PipelineBuildSynthCodePipelineActionRole4E7A6C97
// [+] AWS::IAM::Policy Pipeline/Pipeline/Build/Synth/CodePipelineActionRole/DefaultPolicy PipelineBuildSynthCodePipelineActionRoleDefaultPolicy92C90290
// [+] AWS::IAM::Role Pipeline/Pipeline/Build/Synth/CdkBuildProject/Role PipelineBuildSynthCdkBuildProjectRole231EEA2A
// [+] AWS::IAM::Policy Pipeline/Pipeline/Build/Synth/CdkBuildProject/Role/DefaultPolicy PipelineBuildSynthCdkBuildProjectRoleDefaultPolicyFB6C941C
// [+] AWS::CodeBuild::Project Pipeline/Pipeline/Build/Synth/CdkBuildProject PipelineBuildSynthCdkBuildProject6BEFA8E6
// [+] AWS::IAM::Role Pipeline/Pipeline/UpdatePipeline/SelfMutate/CodePipelineActionRole PipelineUpdatePipelineSelfMutateCodePipelineActionRoleD6D4E5CF
// [+] AWS::IAM::Policy Pipeline/Pipeline/UpdatePipeline/SelfMutate/CodePipelineActionRole/DefaultPolicy PipelineUpdatePipelineSelfMutateCodePipelineActionRoleDefaultPolicyE626265B
// [+] AWS::IAM::Role Pipeline/UpdatePipeline/SelfMutation/Role PipelineUpdatePipelineSelfMutationRole57E559E8
// [+] AWS::IAM::Policy Pipeline/UpdatePipeline/SelfMutation/Role/DefaultPolicy PipelineUpdatePipelineSelfMutationRoleDefaultPolicyA225DA4E
// [+] AWS::CodeBuild::Project Pipeline/UpdatePipeline/SelfMutation PipelineUpdatePipelineSelfMutationDAA41400
```

**Comment by OperationalFallacy** [comment]
Could anybody point me to design documentation, perhaps?

I'm trying to understand if CDK Pipeline is designed as an additional to a cdk app, or it can be defined as a common cicd stack for multiple apps?

Use case: team's account with a hundred services and apps. Instead of each app creating pipeline with  `PipelineBuildSynthCodePipelineActionRole`, `PipelineUpdatePipelineSelfMutateCodePipelineActionRoleDefaultPolicy` - more than half a thousand roles for a hundred apps to deploy - wouldn't it be easier to have all these roles and policies  defined in one stack and then each app reuses them?

**Comment by manalikekre** [comment]
I am not quite sure if CDK Pipelines allows you to specify already existing IAM Roles, but I believe the general guiding principle is that users shouldn't need to worry about creating these numerous roles by hand - CDK Pipeline's was written deliberately to simply setting up a full-fledged CI/CD pipeline per app with minimal efforts.

https://github.com/aws/aws-cdk-rfcs/blob/master/text/0049-continuous-delivery.md is a very good starting point for understanding the design for cdk pipelines.

**Comment by nayaran** [comment]
I am not quite sure if CDK Pipelines allows you to specify already existing IAM Roles, but I believe the general guiding principle is that users shouldn't need to worry about creating these numerous roles by hand - CDK Pipeline's was written deliberately to simply setting up a full-fledged CI/CD pipeline per app with minimal efforts.

https://github.com/aws/aws-cdk-rfcs/blob/master/text/0049-continuous-delivery.md is a very good starting point for understanding the design for cdk pipelines.

**Comment by OperationalFallacy** [comment]
Thanks for the link!
Do you know if authors considering next iteration for pipelines to run in organizations, with all security, compliance, segregation etc requirements?

This is a great implementation for users, I just pondering how organization will be adopting it given all the scattered resources. 

This is a stacker diagram generated for [a Pipeline CF template](https://d1ulzh31ez0luk.cloudfront.net/registry/?repo=https://github.com/OperationalFallacy/templates-temp/blob/main/template.yaml)
 
![image](https://user-images.githubusercontent.com/62673610/109828508-b0a43200-7c0a-11eb-82e2-8e583274b486.png)

**Comment by peterwoodworth** [comment]
Please check out #15649 @OperationalFallacy, it has information on how to potentially use your own roles instead of having them be created automatically.

I'll research this more to see if anything else is replaceable

**Comment by kennu** [comment]
I have a slightly related question: When you use CodePipeline.addStage() to deploy stages, can you customize the actual CloudFormation stack names?

Currently it seems CDK is formatting the actual stack name as "stageName-stackName". Our deployed stack names already include stage suffixes, so the stack name ends up like "dev-mystack-dev", which doesn't match the real existing stack "mystack-dev". CDK Pipeline then tries to create a new stack "dev-mystack-dev" and fails because of overlapping identifiers.

So how could I create a stage whose final stack name is "mystack-dev"?

**Comment by peterwoodworth** [comment]
@kennu the stack name will be generated if the [`stackName`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.Stack.html#stackname-1) prop isn't defined. The code which generates the stack name is here:

https://github.com/aws/aws-cdk/blob/2921d641171e0833b50f47418f444373a2592835/packages/%40aws-cdk/core/lib/stack.ts#L1065-L1089

To not have the name be automatically generated with the stagename at the beginning, you can use the `stackName` prop when creating the Stack construct

**Comment by kennu** [comment]
That's awesome @peterwoodworth, thanks! I hadn't realized that the "id" parameter is in addition to a separate stackName property, because I tend to call the id parameter "stackName" for clarity for simple stacks.

**Comment by peterwoodworth** [comment]
Additionally, something that hasn't been discussed yet is that these resources that are automatically created can be modified using [escape hatches](https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html). All you have to do is figure out which construct is creating a given resource, and then from there you should be able to access the desired resource using `node.children`.
