### ISSUE TITLE
(aws-cloudfront): CfnPublicKey return "Invalid request provided: AWS::CloudFront::PublicKey"

### ISSUE THREAD

**Issue by bmVsc29u** [aws/aws-cdk#12852]
## :question: General Issue

It can be reproduce by the following steps:

1. create a new key `test.public.key` in ssm manually like this:
```
-----BEGIN RSA PUBLIC KEY-----\nMIIBCgKCAQEA3E2+7gIOOC2djAaFlGBHXLZ2cmmjjmfIRlxdYNNwkLmxXx\nXYN7p8rv3BxES7BhsWP8jdjABJjC1OnxBccYx/yslpTeA+HXc2F03\njWFG9itqYTP0mSfit6GauzGza0IDNUkz5rDvlV00K4sBkuikwwmuQCqBfQBjNOM3\njdpgSVFCrLNfriuNhm18kwLGmPMcYJHrYzolYnQS2+U9r3hLX0rWeGyooa0+MJao\n4PuSy9f6Mx03UxedPsFDmuOYdhSyDrMmY2LErw3FUgYZXrErFraEaiK9NIoU/E79\nqiBQ6sZvODDDJU+1ew35gBZpP0fQ8O+qoQIDAQAB\n-----END RSA PUBLIC KEY-----\n
```
2. create a stack contains the following code:
```typescript
 const key = ssm.StringParameter.fromStringParameterName(
            this,
            'key',
            'test.public.key'
        );
   const pk = new cloudfront.CfnPublicKey(this, 'CdnPk', {
            publicKeyConfig: {
                name: 'testPubkey',
                callerReference: 'v3',
                encodedKey: key.stringValue,
// also tried below with no luck
              //  encodedKey: '{{resolve::ssm:test.public.key:1}}',
            },
        });
```

Then run `cdk deploy`

### The Question

If the key is provided as a plain string directly to `encodedKey` field then it will success. But then the key become hard to re-use. When I try to reference it in the way above, cloudformation simply throws error without more detail. 
![image](https://user-images.githubusercontent.com/46260795/106787427-a550fb80-668a-11eb-8ae5-ac97109a39b3.png)

### Environment

  - **CDK CLI Version:** 1.87.1
  - **Module Version:** cloudfront 1.87.1
  - **Node.js Version:** 10.22.1
  - **OS:** macOS 10.15.7
  - **Language (Version):** Typescript 3.9.7

**Comment by peterwoodworth** [comment]
Hey @bmVsc29u,

The problem is with how you are storing the value of the RSA key in Parameter Store. I see you have some "\n"s in your string that you paste inside the string when hardcoding it in. Make sure that you generate the new lines in Parameter Store, as it does not use Linux standard line breaks. Fixing this should help with your issue, I was able to reproduce and fix the issue by doing this.

**Comment by bmVsc29u** [comment]
@peterwoodworth you're right!! that's helped a lot. Thanks.
