### ISSUE TITLE
2.0 alpha changelog link on releases page is broken

### ISSUE THREAD

**Issue by mb-dev** [aws/aws-cdk#12853]
2.0.0 alpha on the releases page (https://github.com/aws/aws-cdk/releases) points to:
```
See [CHANGELOG](https://github.com/aws/aws-cdk/blob/bump/2.0.0-alpha.3/CHANGELOG.md)
```

However the link is broken.

The right link is:
https://github.com/aws/aws-cdk/blob/v2-main/CHANGELOG.v2.md

**Comment by NGL321** [comment]
Hey @mb-dev,

Sorry for long delays in responding to this. Unfortunately because the link is in the comment of a PR it is just part of the commit history and cannot be altered.

I am going through and clearing no-op issues, but please rest assured this was seen.

😸 😷
