### ISSUE TITLE
certificate-manager: CertificateRequestorFunction uses soon to be EOL Node.js 10.3 runtime

### ISSUE THREAD

**Issue by clementallen** [aws/aws-cdk#12871]
### The Question

I know Node.js 10.x is still supported by AWS Lambda but with the official EOL given by Node.js of 30th April 2021 is it worth updating to Node.js 12.x or 14.x now?

Node.js release timeline: https://nodejs.org/en/about/releases/

![image](https://user-images.githubusercontent.com/6305750/106941983-82225c80-671b-11eb-96f7-2660bc6c7429.png)

### Environment

  - **CDK CLI Version:** 1.88.0
  - **Module Version:** 1.88.0
  - **Node.js Version:** N/A
  - **OS:** All
  - **Language (Version):** All

### Other information

I am happy to raise a Merge Request with this change but wanted to check it would be worthwhile first.

**Comment by tom-mi** [comment]
Thanks for bringing this up!
Instead of upgrading to v12 what do you think about upgrading to v14 now so we don't have the same issue again next year?

**Comment by njlynch** [comment]
@clementallen - Thanks for bringing this up! A PR would be much appreciated. I agree with @tom-mi  that we should jump up to v14.

**Comment by njlynch** [comment]
Actually, it looks like #13488 is already handling this. You can track the fix there. 

Thanks for the issue!
