### ISSUE TITLE
[aws-rds] No way of configuring a security group for an DatabaseCluster

### ISSUE THREAD

**Issue by jonahbeckford** [aws/aws-cdk#12876]
This is an extension of bug #9240, whose fix was only for databases with an OptionGroup.

I am using Aurora PostgreSQL 11.9 with a DatabaseCluster. A default security group allowing all outbound connections is created.

A `DatabaseCluster` does not work with an `OptionGroup` (which require a `engine: IInstanceEngine` property), and regardless PostgreSQL does not have option groups. 

#### CDK

```typescript
const vpc = ...
const cluster = new DatabaseCluster(this, 'Database', {
    engine: DatabaseClusterEngine.auroraPostgres({ version: AuroraPostgresEngineVersion.VER_11_9 }),
    instanceProps: {
        vpc: vpc,
    },
})
```
#### CFN

```javascript
    "DatabaseB269D8BB": {
      "Type": "AWS::RDS::DBCluster",
      "Properties": {
        "Engine": "aurora-postgresql",
        "DBClusterParameterGroupName": "default.aurora-postgresql11",
        "DBSubnetGroupName": {
          "Ref": "DatabaseSubnets56F17B9A"
        },
        "EngineVersion": "11.9",
        "Port": 5432,
        "VpcSecurityGroupIds": [
          {
            "Fn::GetAtt": [
              "DatabaseSecurityGroup5C91FDCB",
              "GroupId"
            ]
          }
        ]
      },
      "UpdateReplacePolicy": "Snapshot",
    },
    "DatabaseSecurityGroup5C91FDCB": {
      "Type": "AWS::EC2::SecurityGroup",
      "Properties": {
        "GroupDescription": "RDS security group",
        "SecurityGroupEgress": [
          {
            "CidrIp": "0.0.0.0/0",
            "Description": "Allow all outbound traffic by default",
            "IpProtocol": "-1"
          }
        ],
        "VpcId": {
          "Fn::ImportValue": "Infrastructure:ExportsOutputRefVPCB9E5F0B4BD23A326"
        }
      },
    },
```

### What did you expect to happen?

I would expect some configuration so that the `AWS::EC2::SecurityGroup` is:

```javascript
    "DatabaseSecurityGroup5C91FDCB": {
      "Type": "AWS::EC2::SecurityGroup",
      "Properties": {
        "GroupDescription": "RDS security group",
        "SecurityGroupEgress": [
          {
            "CidrIp": "255.255.255.255/32",
            "Description": "Disallow all traffic",
            "FromPort": 252,
            "IpProtocol": "icmp",
            "ToPort": 86
          }
        ],
        "VpcId": {
          "Fn::ImportValue": "Infrastructure:ExportsOutputRefVPCB9E5F0B4BD23A326"
        }
      },
    },
```

### What actually happened?

Instead I'm stuck with default security group:

```javascript
    "DatabaseSecurityGroup5C91FDCB": {
      "Type": "AWS::EC2::SecurityGroup",
      "Properties": {
        "GroupDescription": "RDS security group",
        "SecurityGroupEgress": [
          {
            "CidrIp": "0.0.0.0/0",
            "Description": "Allow all outbound traffic by default",
            "IpProtocol": "-1"
          }
        ],
        "VpcId": {
          "Fn::ImportValue": "Infrastructure:ExportsOutputRefVPCB9E5F0B4BD23A326"
        }
      },
    },
```

### Environment

  - **CDK CLI Version  :** 1.88.0 (build f65009b)
  - **Framework Version:** aws-cli/2.1.8 Python/3.7.3 Linux/4.19.128-microsoft-standard exe/x86_64.ubuntu.18 prompt/off
  - **Node.js Version:** v12.20.1
  - **OS               :** Ubuntu 18.04 on WSL 2
  - **Language (Version):** TypeScript 3.9.7

### Other

My suggestion is to add an `allowAllOutbound?: boolean` property to the `DatabaseCluster` construct; that will cover the 80% use case.

Since option groups do now support security groups, it sounds like a correct approach is to deprecate specifying security groups in option groups, and instead have it on the `DatabaseCluster` and `DatabaseInstance`.

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hey @jonahbeckford ,

thanks for opening the issue. You can configure the Security Groups for the Cluster by passing the [`securityGroups` property to the `instanceProps` property](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-rds.InstanceProps.html#securitygroups) when creating the Cluster.

Hope this helps!

Thanks,
Adam

**Comment by jonahbeckford** [comment]
Sigh. Not sure why I didn't see that. Thanks. Non-issue / non-bug.

**Comment by skinny85** [comment]
No worries @jonahbeckford, glad you got unblocked!
