### ISSUE TITLE
Julia language support

### ISSUE THREAD

**Issue by mattBrzezinski** [aws/aws-cdk#12874]
Tracking issue for [Julia](https://github.com/JuliaLang/julia) support for CDK.

**Comment by mattBrzezinski** [comment]
Created this issue so I can reference it in my RFC

**Comment by peterwoodworth** [comment]
Hey, this looks like it might be a JSII issue. @RomainMuller what do you think?

**Comment by mattBrzezinski** [comment]
> Hey, this looks like it might be a JSII issue. @RomainMuller what do you think?

Yes. I was following the [RFC](https://github.com/aws/aws-cdk-rfcs/blob/master/text/204-golang-bindings.md) for GoLang bindings. There may have been some confusion on where a main tracking issue for this should be.

Feel free to move this into another repository as you see fit.
