### ISSUE TITLE
(cli): CDK v1.88 Init 

### ISSUE THREAD

**Issue by antawad** [aws/aws-cdk#12870]
The CDK init command in the latest version is failing to init with the following error.
Using:
$ npm -v
6.14.10
$ node -v
v14.15.4
$ tsc -v
Version 4.1.3

Reverting back to 1.87.1 fixes it.
The cdk init command I am trying is: `cdk init --language typescript`

Error thrown:
```
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'source-map-support/register'
Require stack:
- /usr/local/lib/node_modules/aws-cdk/bin/cdk.js
- /usr/local/lib/node_modules/aws-cdk/bin/cdk
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/aws-cdk/bin/cdk.js:4:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/aws-cdk/bin/cdk.js',
    '/usr/local/lib/node_modules/aws-cdk/bin/cdk'
  ]
}
```

### Reproduction Steps
1. Install the latest aws cdk `npm i -g aws-cdk`
2. Run the following: `cdk init --language typescript`
3. Observe the error attached above

### What did you expect to happen?
- Expected the typescript cdk project to be inited

### What actually happened?
- Error thrown as per above

### Environment

  - **CDK CLI Version  :** 1.88.0 (causing the error)
  - **Framework Version:** ?
  - **Node.js Version:** v14.15.4
  - **OS               :** macOS Catalina 10.15.7 
  - **Language (Version):**  Typescript

### Other

N/A

--- 

This is :bug: Bug Report

**Comment by peterwoodworth** [comment]
Hey @antawad,

I wasn't able to reproduce this issue. I'm currently using node `v15.6.0` and npm `7.4.0`. Are you able to try updating these versions? If you still encounter this, let us know and we will see if we can reproduce a different way.

**Comment by antawad** [comment]
Hi @peterwoodworth,
Unfortunately node v15.x is not LTS. I would prefer staying with the LTS. For now reverting back to 1.87.1 solved it. 
Just thought I would mention to you guys since a lot of our customers would be on an LTS version for production workloads. 
To replicate you can download the LTS and give it a quick shot and then maybe revert back to the current version.
Thoughts?
Cheers

**Comment by rix0rrr** [comment]
Does not reproduce for me:

```
$ node --version
v12.12.0

$ npx cdk@1.88.0 init -l=typescript
(...does things...)
✅ All done!
```

**Comment by rix0rrr** [comment]
It IS true that `cdk.js` starts with a `require('source-map-support/register');`, but at the same time `aws-cdk/package.json` declares `source-map-support` as a dependency, so a regular `npm install` should have installed that dependency in the right place.

Whatever it is, seems to be particular to your specific installation.

**Comment by Jonathan-Hill** [comment]
I get exactly the same error, reverting to 1.87.1 also fixes it for me. So whatever the issue is, it's not specific to just one person's installation.

$ npm -v
7.5.0
$ node -v
v15.8.0

I'm running on Mac OSX Big Sur (11.2).

**Comment by Jonathan-Hill** [comment]
@rix0rrr Tagging so you see my previous comment.

**Comment by JackNova** [comment]
I'm having the same problem

`npm -v
7.6.3
node -v
v14.16.0
cdk --version
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'source-map-support/register'
Require stack:
- /usr/local/lib/node_modules/aws-cdk/bin/cdk.js
- /usr/local/lib/node_modules/aws-cdk/bin/cdk
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/aws-cdk/bin/cdk.js:4:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/aws-cdk/bin/cdk.js',
    '/usr/local/lib/node_modules/aws-cdk/bin/cdk'
  ]
}
 ✘ which cdk
/usr/local/bin/cdk
cat /usr/local/bin/cdk
#!/usr/bin/env node
require('./cdk.js');`

**Comment by JackNova** [comment]
@Jonathan-Hill just a couple of observations that helped me to sort it out:

- I just installed nvm and configured it to run the lts version
- I issued the uninstall command both for the local (eventually) and the global version of aws-cdk
- I issued the `which cdk` command and noticed that the symbolic link for cdk was pointing to a wrong location (according to the nvm version of node and npm)
- I removed the symbolic link and installed it aws-cdk globally

now it works as expected

**Comment by mickog** [comment]
Uninstalling and reinstalling CDK worked for me

**Comment by Baza-86** [comment]
Thanks @mickog, that did the trick for me too.

**Comment by byongwu** [comment]
Another solution worked for me is using `npm update -g`.

**Comment by mconta** [comment]
@byongwu solution worked for me, thanks!
