### ISSUE TITLE
(aws-cdk/pipelines): Possible to specify a path in the repo?

### ISSUE THREAD

**Issue by calvin-li-compass** [aws/aws-cdk#12873]
### The Question
Is it possible to specify a path for my source code with the repo? For example if my cdk code is rooted in `app/app_name/`?
Can I specify that somewhere in the pipeline stack?

Also for the pipeline stages. Is it possible to make it so that the links like `AWS Cloudformation` or `Details` take me to the account where the resources are being deployed?

### Environment

  - **CDK CLI Version:** 1.88.0 (build f65009b)
  - **Module Version:** "^1.87.1"

**Comment by OperationalFallacy** [comment]
1. You probably can configure "app" property in cdk.json so cdk understands how to run it:
`"app": "npx ts-node --prefer-ts-exts app/blah/index.ts"`

If your cdk diff|synth|deploy etc work locally from repo's root, then pipeline should be able to deploy it without any additional configurations.

2. No, direct links don't work. They mention it somewhere in the docs. I tried assumed roles in the console to quickly switch accounts, but it only works for personal type accounts. In any shop with multiple accounts it will be a pita.

**Comment by calvin-li-compass** [comment]
1. Hm I see, not exactly what I'm looking for but I can work around it.
2. I see the doc you're referring to: https://docs.aws.amazon.com/cdk/latest/guide/cdk_pipeline.html

I hope `2` gets addressed at some point because it is quite annoying.

**Comment by snyderizer** [comment]
for 1, you could  use the `subdirectory` prop of SimpleSynthActionProps:

https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_pipelines.SimpleSynthActionProps.html#subdirectoryspan-classapi-icon-api-icon-experimental-titlethis-api-element-is-experimental-it-may-change-without-noticespan


example:

```typescript
      synthAction: SimpleSynthAction.standardNpmSynth({
        sourceArtifact,
        cloudAssemblyArtifact,
        subdirectory: 'app/app_name',
      }),
```
