### ISSUE TITLE
(core): creating an ecr.Repository in one stack and using in a second stack errors

### ISSUE THREAD

**Issue by dhensen** [aws/aws-cdk#12886]
cdk deploy ends in an error: Parameter values specified for a template which does not require them.

### Reproduction Steps

isolated_example.py
```python
from aws_cdk import aws_ecr as ecr
from aws_cdk import aws_ecs as ecs
from aws_cdk import core


class PreliminaryStack(core.Stack):
    def __init__(self, scope: core.Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        self.anw_docker_image_repo = ecr.Repository(
            self, "anw-service-img-repo", repository_name=f"{id}-anw"
        )


class AnwStack(core.Stack):
    def __init__(
        self, scope: core.Construct, id: str, anw_image_repo: ecr.Repository,
        **kwargs
    ) -> None:
        super().__init__(scope, id, **kwargs)

        anw_image_tag = core.CfnParameter(
            self,
            "anwImageTag",
            type="String",
            description="The tag of the anw image that is going to be deployed.",
        )

        container_image = ecs.ContainerImage.from_ecr_repository(
            repository=anw_image_repo,
            tag=anw_image_tag.value_as_string,
        )

        core.CfnOutput(self, "somethingSomething", value=container_image.image_name)


app = core.App()
preliminary_stack = PreliminaryStack(app, "anw-preliminary-stack-debug")
AnwStack(app, "anw-stack-debug", anw_image_repo=preliminary_stack.anw_docker_image_repo)

app.synth()
```

```
cdk deploy --app "python3 isolated_example.py" anw-preliminary-stack-debug
# here I would be able to docker push my image to ecr repo just created
# then I would provision the rest of my stack
cdk deploy --app "python3 isolated_example.py" --parameters anwImageTag="foobar" anw-stack-debug
```

The second deploy ends in an error:
> see What actually happened?

Adding more verbosity does not really help me out.

### What did you expect to happen?

I expected the anw-stack-debug to complete without an error.

### What actually happened?

```
Including dependency stacks: anw-preliminary-stack-debug
anw-preliminary-stack-debug
anw-preliminary-stack-debug: deploying...
anw-preliminary-stack-debug: creating CloudFormation changeset...

 ❌  anw-preliminary-stack-debug failed: Error [ValidationError]: Parameter values specified for a template which does not require them.
    at Request.extractError (/usr/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/usr/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/usr/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/usr/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'ValidationError',
  time: 2021-02-05T13:20:18.817Z,
  requestId: 'd576fcc0-64e1-44e5-ada9-81ac09789b7f',
  statusCode: 400,
  retryable: false,
  retryDelay: 577.1151619294412
}
Parameter values specified for a template which does not require them.
```

### Environment

  - **CDK CLI Version  :** 1.88.0 (build f65009b)
  - **Framework Version:** 1.88.0
  - **Node.js Version:** v12.20.0
  - **OS               :** WSL1 Ubuntu 18.04 LTS
  - **Language (Version):** Python 3.8.6

### Other

My actual stack is more complicated, I made an isolated example to share in this issue.
This issue is also happening on 1.79.0 (i upgraded to 1.88.0 to see if this issue would disappear)
I can repo this locally (WSL1) and in our Jenkins pipelines.

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
The issue here is probably that this command doesn't do what you think it does (and I agree, it's not obvious at first why it does what it does):

```
cdk deploy --app "python3 isolated_example.py" --parameters anwImageTag="foobar" anw-stack-debug
```

In parts:

```
cdk deploy [...] anw-stack-debug
```

Doesn't JUST deploy `anw-stack-debug`. It deploys `anw-stack-debug` **and all stacks it depends on**. So in this case, it also deploys `anw-preliminary-stack-debug` (as you can see in your log).

So since `cdk deploy` can deploy anywhere from 1 up to 100 stacks in one command (you can't know in advance), when you write:

```
cdk deploy [...] --parameters anwImageTag=foobar
```

What stack is that one parameter for? Are we going to guess which of the 100 stacks it's intended for?

The current, although kinda silly, answer is that it applies to **all stacks**, even stacks that don't take this particular argument. The latter decision was taken to guard you against typoes: what if you meant to pass a parameter but you fat-fingered it?

The solution is either:

* **Really only deploy one stack**: `cdk deploy --exclusively anw-stack-debug`, and pass your `--parameters` in there.
* **Be explicit what stack the parameter is for**: `cdk deploy --parameters anw-stack-debug:anwImageTag=foobar`

**Comment by dhensen** [comment]
Thank you @rix0rrr, have been searching without finding this: `--exclusively` and the fact that you can specify parameters for specific stacks. Going to do even more R(T)FM'ing :+1:
