### ISSUE TITLE
CdkPipelines deploy with custom bucket fails

### ISSUE THREAD

**Issue by zgre** [aws/aws-cdk#12884]
I am trying to deploy CdkPipelines python example from https://github.com/aws-samples/cdk-pipelines-demo/tree/python

Did the bootstrap with the following command:

```
PIPELINE_ACCOUNT=1234567890 CDK_NEW_BOOTSTRAP=1 npx cdk bootstrap \
   --cloudformation-execution-policies arn:aws:iam::aws:policy/AWSCodePipelineFullAccess \
   aws://${PIPELINE_ACCOUNT}/eu-west-1 \
   --bootstrap-bucket-name cdk-bootstrap-test-a1b2c3d4e5 \
   --qualifier a1b2c3d4e5 \
   --tags Application=a1b2c3d4e5

```

When I try to deploy the bootstrap-bucket-name is not taken into account. 
Deploy tries to use cdk-a1b2c3d4e5-assets-<ID>-eu-west-1 bucket

No bucket named: cdk-a1b2c3d4e5-assets-<ID>-eu-west-1  Is account bootstrapped?

-->

### Environment

  - **CDK CLI Version: 1.88.0**
  - **Framework Version:**
  - **Node.js Version:12.16.3**
  - **OS               : Centos**
  - **Language (Version): Python (3.8.0)** 

### Other

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
Changing the bucket name also requires changing your application (specifically, telling the synthesizer about the new stack name). See:

* https://docs.aws.amazon.com/cdk/latest/guide/bootstrapping.html#bootstrapping-customizing
* https://docs.aws.amazon.com/cdk/latest/guide/bootstrapping.html#bootstrapping-custom-synth
