### ISSUE TITLE
(aws-cdk): asset bundling skipped when using --exclusively option

### ISSUE THREAD

**Issue by supaiku0** [aws/aws-cdk#12898]
Asset bundling is currently broken when using the `--exclusively` option during deploy. 

In our case we have an `aws-lambda-nodejs` with [forceDockerBuild](https://github.com/aws/aws-cdk/blob/98ab29206903a235331a9a0b4b38a5e6ad6d89dc/packages/%40aws-cdk/aws-lambda-nodejs/lib/types.ts#L190) set to true (but it shouldn't matter).

However, due to the following check the bundling never happens when e.g. running `cdk deploy --exclusively 'MyStack'` -
as in it will skip the bundling step completely.

Concretely, this minimatch evaluates to `false` for any given stack name, except when using `--all` which evaluates to the wildcard `*` satisfying anything.
https://github.com/aws/aws-cdk/blob/9417b0211eb2939f5a853751333f7941d9dd99f8/packages/%40aws-cdk/core/lib/asset-staging.ts#L164

That is because `Stack.of(this).stackName` is not resolved at this point. The screenshot shows the output of running with `--all` (bundlingStacks contains `[*]`) against the unresolved stack name:

![image](https://user-images.githubusercontent.com/1311798/107117793-ffb1ae00-687c-11eb-88a8-b3ebaf11a51b.png)

Tested on Linux and Windows and CDK 1.88.

--- 

This is :bug: Bug Report

**Comment by hedrall** [comment]
I couldn't reproduce it. The bundle runs without problems. I would appreciate it if you could share the detailed settings.

**Comment by supaiku0** [comment]
@hedrall Sorry, my bad. I forgot one important detail - it only happens when using nested stacks.

Here is a small reproduce:

```ts
#!/usr/bin/env node
import 'source-map-support/register';
import * as cdk from '@aws-cdk/core';
import { CdkStack } from '../lib/cdk-stack';

const app = new cdk.App();
new CdkStack(app, 'CdkStack');

```

```ts
import * as cdk from '@aws-cdk/core';
import { Bundling } from "@aws-cdk/aws-lambda-nodejs/lib/bundling";
import * as synthetics from '@aws-cdk/aws-synthetics';
import * as lambda from '@aws-cdk/aws-lambda';
import { join } from 'path';

export class CdkStack extends cdk.Stack {

  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps & { ref: cdk.Stack }) {
    super(scope, id, props);

    new NestedStack(this, "NestedStack");
  }
}
class NestedStack extends cdk.NestedStack {

  constructor(scope: cdk.Construct, id: string) {
    super(scope, id);

    new synthetics.Canary(this, "Canary", {
      runtime: synthetics.Runtime.SYNTHETICS_NODEJS_PUPPETEER_3_0,
      schedule: synthetics.Schedule.rate(cdk.Duration.minutes(30)),
      test: synthetics.Test.custom({
        handler: "index.handler",
        code: Bundling.bundle({
          depsLockFilePath: join(__dirname, "js"),
          entry: join(__dirname, "js", "index.js"),
          runtime: lambda.Runtime.NODEJS_12_X,
          forceDockerBundling: true,
          minify: true,
        }),
      }),
    });
  }
}
```

Doing a `cdk deploy --exclusively 'CdkStack'` will fail.

**Comment by aax** [comment]
I stumbled into this when using a simple PythonFunction construct (no nested stacks).

**Comment by moltar** [comment]
This is a **massive** issue and it's a nasty one!

---

@miekassu and I have have spent 10+ hours on debugging this issue.

@miekassu has created a repro here: https://github.com/miekassu/lambda-build-fail

To test it:

```sh
git clone https://github.com/miekassu/lambda-build-fail.git
cd lambda-build-fail
npm i
cdk deploy -e 'Stage/Stack'
```

During the deployment you'll not see any errors, but the publishing step may take a minute, because the bundle is large

This part:

```
[0%] start: Publishing faf451f1ef16a0f6b0ba19f78797d6a4ad88835f5bef11210c7999dd898de1df:current_account-current_region
```

Then you can try:

```
du -hs cdk.out
```

And observe that the directory is unreasonable large.

You can also inspect the S3 bucket and see the asset that was uploaded and it will be ~ 70 MB, I think.

---

What happens is that not that asset bundling just gets skipped. That wouldn't be too bad.

But in reality, what happens is that, _somehow_, the asset for each lambda becomes the **entire** project directory (`./`), with all git history (`.git`) and `node_modules` and all of that gets bundled into a single zip file (> 500 MB) and uploaded to S3.

This, of course fails completely with:

```
Resource handler returned message: "Unzipped size must be smaller than 262144000 bytes (Service: Lambda, Status Code: 400, Request ID:
6b2ad171-9371-4a88-b2bd-d468ed223082, Extended Request ID: null)" (RequestToken: 7b59e8ca-5b76-ac79-d46a-079e2d97d2d8, HandlerErrorCode
: InvalidRequest)
```

---

Another observation. When running `cdk synth` it will produce the correct asset paths and hashes. Then running `cdk deploy -e 'Stage/Stack'` it will overwrite the asset paths and hashes with incorrect values.

**Comment by moltar** [comment]
It looks like on that line that @supaiku0 specified (minimatch), the value of `Stack.of(this).stackName` is `Stage-Stack`, while the pattern is `Stage/Stack`.

**Comment by moltar** [comment]
But if `cdk deploy -e Stage-Stack` command it used then bundling seems to happen, but deploying isn't. It just cleanly exists 🤷🏼‍♂️ 

```
❯ npx cdk deploy -e Stage-Stack
Bundling asset Stage/Stack/DummyTSLambda/Code/Stage...

  cdk.out/bundling-temp-559a6b1ee287e12c42e2357ee8b6702dd1dc62a1cb205f390bf1377ff93afefb/index.js  646b

⚡ Done in 2ms

❯ echo $?
0
```

**Comment by miekassu** [comment]
I added more stacks and lambdas to the example [repository](https://github.com/miekassu/lambda-build-fail).
Some of my observations while debugging:

Produces not wanted Lambda asset path pointing to the root folder of the project:
```
 cdk diff -e Stage/Stack1
```

Targeting manifest in `cdk.out/assembly` folder produces right asset path when using `-e` tag.
To update templates, I used synth commands, which then also bundles other lambdas in the other stacks during synth, 
this is unwanted and in large projects takes a lot of time.
```
 cdk synth && cdk -a cdk.out/assembly-Stage diff -e Stage/Stack1
```

Using `-e` tag with synth commands only bundles lambdas from wanted stack, but it also points lambda asset path to project root.
```
 cdk synth -e Stage/Stack1 && cdk -a cdk.out/assembly-Stage diff -e Stage/Stack1
```

This known issue is preventing the usage of new `--hotswap` feature with multi stack projects.

**Comment by reecefenwick** [comment]
A workaround I found was doing the following within my stack, not exactly thrilled to be doing this but it has helped me avoid more drastic workarounds.

```typescript
export class NodeLambdaConsumer extends NestedStack {
  public readonly lambda: lambda.Function;

  constructor(
    scope: Construct,
    id: string,
    {
      ...
    }: NodeLambdaConsumerProps,
  ) {
    super(scope, id, {});

    // mutate the BUNDLING_STACKS config in ctx
    const config = this.node.getContext(BUNDLING_STACKS);
    config.push(this.node.path);
```

Something I was also considering was just replacing `NodejsFunction` with my own construct that takes care of bundling, but for now I'll stick with the above and see how we go 🤷

**Comment by codyfrisch** [comment]
Here we are in 2025 and this issue still exists using -e with a stack that contains nested stacks results in the lambda .zip including the whole repository directory. Wasted a whole morning trying to figure out whats going wrong. At least I know its an ignored known issue and that I just have to avoid using -e or else rearchitect everything to not use nested stacks.

I'm really regretting investing so much in CDK at this point when I should have used Terraform and avoided this nonsense. But too deeply invested to switch to a well managed tool.
