### ISSUE TITLE
(aws-cdk/pipelines): InternalFailure on CFN/Stack.Prepare after importing resources

### ISSUE THREAD

**Issue by calvin-li-compass** [aws/aws-cdk#12895]
Importing resources into my CDK stack causes CDK Pipeline to fail. Please see reproduction steps.

### Reproduction Steps
1. Deploy CDK pipeline with empty stack called `S3Stack`
2. Follow this guide to import existing S3 buckets into `S3Stack`: https://medium.com/@visya/how-to-import-existing-aws-resources-into-cdk-stack-f1cea491e9
3. Import succeeds
4. Next deployment on the pipeline (with and without code change) will fail at `S3Stack.Prepare` step. Details show `Action execution failed: InternalFailure`

### What did you expect to happen?
Pipeline should deploy as normal.

### What actually happened?
Pipeline no longer works with the modified stack.

### Environment

  - **CDK CLI Version  :** 1.88.0
  - **Framework Version:** 1.88.0
  - **Node.js Version:**  v14.15.4
  - **OS               :** Mac OS
  - **Language (Version):** Typescript

### Other

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
That is interesting. You will probably observe the same behavior when deploying that stack using `cdk deploy`, or for that matter, using `aws cloudformation create-change-set`.

At first glance this appears to be a CloudFormation issue. `InternalFailure` indicates to me that the `CreateChangeSet` API call failed, and honestly it should never do this.

Can you confirm from CloudTrail that the `CreateChangeSet` API call failed? If so, this would be an issue to take up with the CloudFormation team.
