### ISSUE TITLE
(ec2): __jsii_type__ error when calling  aws_ec2.Vpc.from_lookup() in Python

### ISSUE THREAD

**Issue by blake-enyart** [aws/aws-cdk#12900]
I am attempting to have a decoupled multistack deployment in Python for the CDK and I am running into an issue where it throws an `AttributeError: type object 'tuple' has no attribute '__jsii_type__'` when performing `cdk synth`. This issue looks very similar to this aws/jsii/issues/483 which appears to be resolved through this issue aws/jsii/issues/537. 

However, in the Python `aws_ec2.Vpc.from_lookup()` call it appears to resurface.  I verified this is isolated to Python as I created a Typescript project and replicated the code shown below and it works fine.

Considering the impact of this, I would be okay if there were a workaround while this gets resolved such as writing one of the stacks in Typescript and formatting the project such that both the Python CDK stacks and Typescript CDK stack are able to be synthesized from the same project.

If the fix seems achievable as a first issue, I'm happy to try and resolve this myself.

### Reproduction Steps

* Run `cdk synth` with the following code:

```
from aws_cdk import (
    core,
    aws_ec2 as ec2,
)

class TwitterStreamAppStack(core.Stack):

    def __init__(
        self,
        scope: core.Construct,
        id: str,
        **kwargs,
    ) -> None:
        super().__init__(scope, id, **kwargs)

        vpc = ec2.Vpc.from_lookup(
            self, "vpc", vpc_id='vpc-06587757a30949b2e',
        )
```

### What did you expect to happen?
I expected to be able to import an existing VPC into the CDK application

### What actually happened?
The following exception occurs when executing `cdk synth`

 

```
Traceback (most recent call last):
  File "app.py", line 30, in <module>
    twitter_stream_app = TwitterStreamAppStack(
  File "/Users/blackenyart/gh_projects/data_pipeline_practice/.venv/lib/python3.8/site-packages/jsii/_runtime.py", line 73, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/blackenyart/gh_projects/data_pipeline_practice/data_pipeline_practice/twitter_stream_app_stack.py", line 38, in __init__
    vpc = ec2.Vpc.from_lookup(
  File "/Users/blackenyart/gh_projects/data_pipeline_practice/.venv/lib/python3.8/site-packages/aws_cdk/aws_ec2/__init__.py", line 38363, in from_lookup
    return jsii.sinvoke(cls, "fromLookup", [scope, id, options])
  File "/Users/blackenyart/gh_projects/data_pipeline_practice/.venv/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 126, in wrapped
    return _recursize_dereference(kernel, fn(kernel, *args, **kwargs))
  File "/Users/blackenyart/gh_projects/data_pipeline_practice/.venv/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 353, in sinvoke
    args=_make_reference_for_native(self, args),
  File "/Users/blackenyart/gh_projects/data_pipeline_practice/.venv/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 141, in _make_reference_for_native
    return [_make_reference_for_native(kernel, i) for i in d]
  File "/Users/blackenyart/gh_projects/data_pipeline_practice/.venv/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 141, in <listcomp>
    return [_make_reference_for_native(kernel, i) for i in d]
  File "/Users/blackenyart/gh_projects/data_pipeline_practice/.venv/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 154, in _make_reference_for_native
    "data": {
  File "/Users/blackenyart/gh_projects/data_pipeline_practice/.venv/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 155, in <dictcomp>
    jsii_name: _make_reference_for_native(
  File "/Users/blackenyart/gh_projects/data_pipeline_practice/.venv/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 174, in _make_reference_for_native
    kernel.create(d.__class__, d)
  File "/Users/blackenyart/gh_projects/data_pipeline_practice/.venv/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 267, in create
    fqn=klass.__jsii_type__ or "Object",
AttributeError: type object 'tuple' has no attribute '__jsii_type__'
Subprocess exited with error 1
```

### Environment

  - **CDK CLI Version  :** 1.83.0 (build 827c5f4)
  - **Framework Version:** 1.83.0
  - **Node.js Version:** v15.7.0
  - **OS               :** macOS Catalina 10.15.7 (19H114)
  - **Language (Version):** Python 3.8.7

### Other

* https://github.com/aws/jsii/issues/483
* https://github.com/aws/jsii/issues/537
* https://github.com/aws/aws-cdk/issues/12160

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
Unsure why you are getting this error, but I cannot reproduce it. 

If I do 

```
$ cdk init -l=python

# Edit setup.py to include a dependency on the ec2 library (versions at 1.83.0)

# Edit app.py to look like this:

# TestpythonStack(app, "testpython", env={
#   'account': os.environ['CDK_DEFAULT_ACCOUNT'],
#  'region': os.environ['CDK_DEFAULT_REGION'],
#   })

$ cdk synth
```

Granted, I'm using python 3.6 and an older version of Node, but I don't see how those would make a difference.

Passing to @RomainMuller  to see if he has any clue, but this is not a trivial but and it's like `Vpc.from_lookup()` is broken.

----- 

Just occurred to me  it might have something to do with the return value `Vpc.from_lookup()` is trying to return, i.e. it might have something to do with the specific configuration of your VPC.

Can you paste what's in `cdk.context.json` ?

**Comment by blake-enyart** [comment]
@rix0rrr I completely agree with the potential impact of this. here is the `cdk.context.json` file: 
```json
{
  "availability-zones:account=848684029682:region=us-east-2": [
    "us-east-2a",
    "us-east-2b",
    "us-east-2c"
  ],
  "availability-zones:account=848684029682:region=us-east-1": [
    "us-east-1a",
    "us-east-1b",
    "us-east-1c",
    "us-east-1d",
    "us-east-1e",
    "us-east-1f"
  ],
  "availability-zones:account=251357961920:region=us-east-1": [
    "us-east-1a",
    "us-east-1b",
    "us-east-1c",
    "us-east-1d",
    "us-east-1e",
    "us-east-1f"
  ]
}
```

I was able to work around this with stack imports as I created the VPC in another stack, but I configured a default VPC which was constrained to 2 availability zones as seen here:

```
class NetworkingStack(core.Stack):
    @property
    def vpc(self):
        return self._vpc

    def __init__(
        self, scope: core.Construct, construct_id: str, **kwargs
    ) -> None:
        super().__init__(scope, construct_id, **kwargs)

        self._vpc = ec2.Vpc(self, "Vpc", max_azs=2)

        core.CfnOutput(self, "vpcId", value=self._vpc.vpc_id)
```

**Comment by rix0rrr** [comment]
I think you are now pasting the contents of `cdk.context.json` in your new solution.

Can you paste them from the project that threw the `__jsii_type__` error? It should look somewhat like this:

```
  "vpc-provider:account=993655754359:filter.isDefault=true:region=us-east-2:returnAsymmetricSubnets=true": {
    "vpcId": "vpc-4407e42d",
    "vpcCidrBlock": "172.31.0.0/16",
    "availabilityZones": [],
    "subnetGroups": [
      ....
}
```

**Comment by blake-enyart** [comment]
@rix0rrr so I had continued to work on this post message and didn't branch at this point to preserve the original issue. I replicated the VPC import in a new stack and was able to create a resource that depended on that VPC import which worked without issue.

With that, this ticket can be closed and I can reopen if the issue surfaces again.

**Comment by signet-rajv2021** [comment]
I am running into a similar issue 
AttributeError: type object 'tuple' has no attribute '__jsii_type__'

vpc = ec2.Vpc.from_lookup(self, id="VPC", is_default=False),

I have a VPC with 3 subnets - CT Account

Here is the contents of the cdk.context.json
"vpc-provider:account=XXXXYYY11111:filter.isDefault=false:region=us-east-2:returnAsymmetricSubnets=true": {
    "vpcId": "vpc-09ac222f279a7a11112",
    "vpcCidrBlock": "141.11.0.0/16",
    "availabilityZones": [],
    "subnetGroups": [
      {
        "name": "Private",
        "type": "Private",
        "subnets": [
          {
            "subnetId": "subnet-0xxxxab87aec4yyyy",
            "cidr": "141.11.64.0/20",
            "availabilityZone": "us-east-2a",
            "routeTableId": "rtb-0xxxycf8cbc9aa9yyx"
          },
          {
            "subnetId": "subnet-xxxx1ae6e4fa3yyyy",
            "cidr": "141.11.32.0/20",
            "availabilityZone": "us-east-2b",
            "routeTableId": "rtb-048xxxe00c59fyyyy"
          },
          {
            "subnetId": "subnet-xxxx16fa2ce1ae5yyy",
            "cidr": "141.11.80.0/20",
            "availabilityZone": "us-east-2c",
            "routeTableId": "rtb-068axxxx1a9d1yyyy"
