### ISSUE TITLE
CfnCondition is instance of Construct

### ISSUE THREAD

**Issue by jahtoe** [aws/aws-cdk#12915]
I'm wondering why a the Construct Condition in an AWS template is an instanceof software.amazon.awscdk.core.Construct and not and instanceof CfnCondition?

### Reproduction Steps
Given the java code:

```
CfnInclude template;
List<IConstruct> lic = template.getNode().getChildren();
for (IConstruct IC : lic) {
  LOG.debug("TemplateToTreeMap class name " + IC.getClass().getTypeName());
  if (IC instanceof CfnCondition) {
    LOG.debug("IC is instanceof of CfnCondition");
  }else if (IC instanceof CfnParameter) {
    LOG.debug("IC is instanceof of CfnParameter");
  }
}
```

When the Construct is a template Condition it is an instanceof software.amazon.awscdk.core.Construct rather than a CfnCondition which differs from the case when the Construct is a CfnParameter which is an instanceof CfnParameter.

Both CfnCondition and CfnParameter extend CfnElement.

Why does that happen and how then do I identify a Condition?

Alternatively I've tried as a work around the following:

`    if (IC.toString().contains("$Conditions")) { 
        LOG.debug(IC.toString()); Construct C = (Construct) IC; 
        LOG.debug(toJsonString(C.getNode())); LOG.debug(stack.resolve(C).toString());`

Which gives output as follows

AwsCdkStack/Template/$Conditions
${Token[TOKEN.646]}

But then results in an error

    software.amazon.jsii.JsiiException: 
Unable to resolve object tree with circular reference. Path: /node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node
Error: Unable to resolve object tree with circular reference. Path: /node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node
    at resolve (/tmp/jsii-kernel-w8xgCb/node_modules/@aws-cdk/core/lib/private/resolve.js:35:15)
    at Object.resolve (/tmp/jsii-kernel-w8xgCb/node_modules/@aws-cdk/core/lib/private/resolve.js:29:33)
    at resolve (/tmp/jsii-kernel-w8xgCb/node_modules/@aws-cdk/core/lib/private/resolve.js:118:43)
    at Object.resolve (/tmp/jsii-kernel-w8xgCb/node_modules/@aws-cdk/core/lib/private/resolve.js:29:33)
    at resolve (/tmp/jsii-kernel-w8xgCb/node_modules/@aws-cdk/core/lib/private/resolve.js:118:43)
    at Object.resolve (/tmp/jsii-kernel-w8xgCb/node_modules/@aws-cdk/core/lib/private/resolve.js:29:33)
    at resolve (/tmp/jsii-kernel-w8xgCb/node_modules/@aws-cdk/core/lib/private/resolve.js:118:43)
    at Object.resolve (/tmp/jsii-kernel-w8xgCb/node_modules/@aws-cdk/core/lib/private/resolve.js:29:33)
    at resolve (/tmp/jsii-kernel-w8xgCb/node_modules/@aws-cdk/core/lib/private/resolve.js:118:43)
    at Object.resolve (/tmp/jsii-kernel-w8xgCb/node_modules/@aws-cdk/core/lib/private/resolve.js:29:33)
    at com.iriusrisk.cfimport.BasicApplicationTests.Example1_1(BasicApplicationTests.java:29)

### What did you expect to happen?

The Template Condition to be a CfnCondition

### What actually happened?

The Template condition was an instanceof Construct

### Environment

 <dependency>
            <groupId>software.amazon.awscdk</groupId>
            <artifactId>cdk-cloudformation-include</artifactId>
            <version>1.86.0</version>
        </dependency>
        <dependency>
            <groupId>software.amazon.jsii</groupId>
            <artifactId>jsii-runtime</artifactId>
            <version>1.20.1</version>
        </dependency>

  - **CDK CLI Version  :1.79**
  - **Framework Version:1.86.0**
  - **Node.js Version:v14.15.3**
  - **OS               : Ubuntu 18.04**
  - **Language (Version):Java 8**-->

### Other

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hello @jahtoe,

thanks for opening the issue. I have to confess I don't understand what

> When the Construct is a template Condition it is an instanceof software.amazon.awscdk.core.Construct rather than a CfnCondition which differs from the case when the Construct is a CfnParameter which is an instanceof CfnParameter.

means, but you can retrieve Conditions from a `CfnInclude` template using the [`getCondition()` method](https://docs.aws.amazon.com/cdk/api/latest/java/software/amazon/awscdk/cloudformation/include/CfnInclude.html#getCondition-java.lang.String-), which returns a `CfnCondtion`.

Do _not_ use `node.getChildren()` or similar APIs on `CfnInclude` classes - those are implementation details of the class, and can change in the future.

Thanks,
Adam

**Comment by jahtoe** [comment]
Hi Adam,

Okay that helps resolve my issue then.

What I was trying to say was that when using the getChildren()

List<IConstruct> lic = template.getNode().getChildren();
    for (IConstruct IC : lic) {

The AwsCdkStack/Template/$Conditions IConstruct is of type
software.amazon.awscdk.core.Construct rather than CfnCondition but clearly
it's not the way to get at the conditions.

I've been accessing all the Resources and parameters using this method so I
assumed this would be how to access the conditions as well

List<IConstruct> lic = template.getNode().getChildren();
    for (IConstruct IC : lic) {
   if (IC instanceof CfnParameter) {
        LOG.debug("IC is instanceof of CfnParameter");
        CfnParameter C = (CfnParameter) IC;
       ...

      } else if (IC instanceof CfnInternetGateway) {
        LOG.debug("IC is instanceof of CfnInternetGateway");
        CfnInternetGateway C = (CfnInternetGateway) IC;
      ...
      } else if (IC instanceof CfnVPCGatewayAttachment) {
        LOG.debug("IC is instanceof of CfnVPCGatewayAttachment");
        CfnVPCGatewayAttachment C = (CfnVPCGatewayAttachment) IC;
       ...
      } else if (IC instanceof CfnSubnet) {
        LOG.debug("IC is instanceof of CfnSubnet");
        CfnSubnet C = (CfnSubnet) IC;
       ...
      } else if (IC instanceof CfnDBInstance) {
        LOG.debug("IC is instanceof CfnDBInstance");
        CfnDBInstance C = (CfnDBInstance) IC;
      ...
      }

Thanks very much!

Regards
Alex Muir
Chief Data Engineer/Architect
Jahtoe Technology
tech.jahtoe.com

**Comment by jahtoe** [comment]
Hi Adam,

Actually now that I review the  template.getCondition(conditionName) method
it doesn't help me as I'm not aware of the condition names that are in the
template that is being read in unless there is a way to get the names.

Otherwise it would help my use case to have a way to get a list of the
conditions or condition names.

Regards
Alex Muir
Chief Data Engineer/Architect
Jahtoe Technology
tech.jahtoe.com

**Comment by jahtoe** [comment]
Oh I've just realized my error here. I do have the condition names in the
template later on..

Regards
Alex Muir
Chief Data Engineer/Architect
Jahtoe Technology
tech.jahtoe.com

**Comment by skinny85** [comment]
So... are we done here? 🙂 Do you need anything else from my side @jahtoe ?

**Comment by jahtoe** [comment]
@skinny85  we are done thanks again
