### ISSUE TITLE
ApplicationLoadBalancedFargateService CDK construct: currently there is no way to specify idleTimeout for the load balancer

### ISSUE THREAD

**Issue by anvisergeev** [aws/aws-cdk#12913]
Hello.

Currently there is no way to specify an idleTimeout for the load balancer if we create an ApplicationLoadBalancedFargateService.
Even though we do have such option when we are creating an ApplicationLoadBalancer directly via the ApplicationLoadBalancer construct.

I suggest to implement such option for the ApplicationLoadBalancedFargateService as it is needed very much.

### Use Case

I'm using a Fargate service to run a docker container with a 3rd party library that provides http endpoint. This library can take longer than 1 minute to respond (depending on the input) even on the most performant configuration. In that case I'm receiving a 504 Gateway Time-out error from the load balancer. That's why I need a way to specify the idleTimeout for the ApplicationLoadBalancedFargateService.

### Proposed Solution

To add a set of load balancer related configuration options to the ApplicationLoadBalancedFargateServiceProps.

### Other
Related to the support case 7958289501

Regards,
Anton.

**Comment by mrvisser** [comment]
@anvisergeev I was able to accomplish this by accessing `service.loadBalancer` after instantiating the service:

```typescript
const service = new ApplicationLoadBalancedFargateService(...);
service.loadBalancer.setAttribute('idle_timeout.timeout_seconds', '900');
```

Available attributes:
https://docs.aws.amazon.com/elasticloadbalancing/latest/application/application-load-balancers.html#load-balancer-attributes

Hope that helps someone.

**Comment by JacobTheEvans** [comment]
Thanks for the workaround @mrvisser!

**Comment by ibrahimikram** [comment]
This was very helpful. Thanks @mrvisser!

**Comment by eugene-larikov** [comment]
@mrvisser Thanks for the tip 🙏
