### ISSUE TITLE
Queue: Support default DLQ creation

### ISSUE THREAD

**Issue by rake32** [aws/aws-cdk#12927]
Support default DLQ creation

### Use Case

It is the typical use case to add a DLQ for the queue.
I also see this being supported for a lambda function https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-lambda.Function.html type. I think we should do the same for a Queue construct.

### Proposed Solution

1. Add new property: deadLetterQueueEnabled: boolean
2. Update construct to create a default DLQ, an SQS queue with 14 day retention period if deadLetterQueueEnabled is true.
and deadLetterQueue is not explicitly passed.

### Other
N/A

* [ Yes] :wave: I may be able to implement this feature request

---

This is a :rocket: Feature Request

**Comment by MrArnoldPalmer** [comment]
Hey there! So I see this as the role of other higher level constructs. For example https://github.com/awslabs/aws-solutions-constructs/tree/main/source/patterns/%40aws-solutions-constructs/aws-sqs-lambda lets you hook up a lambda to a queue and by default creates and enables a DLQ. There are equivalent constructs for (sns|s3|cloudwatch)->sqs as well.

Using a DLQ I would define as a "pattern" and so I think the current interface is the right one for the L2.  So for now I'd say check out the aws-solutions-constructs library. Reopen this if you feel strongly though and we can revisit.
