### ISSUE TITLE
Add option to make dockerImageAsset build show docker build logs

### ISSUE THREAD

**Issue by sentient-kshaffer** [aws/aws-cdk#1292]
I'm building a docker image using `DockerImageAsset`, and would love if I could see the docker build output to (1) see how far along my build is, and (2) see any errors/warnings that come up during the build.

I see the build command has the --quiet flag hardcoded right now. If that could be an option, that would be fantastic.

**Comment by eladb** [comment]
I'd argue that the default should be to show build logs. Docker builds usually take a long time...

**Comment by eladb** [comment]
Still relevant

**Comment by adidevocean8** [comment]
still relevant

**Comment by tomschut** [comment]
would be nice though

**Comment by tormich** [comment]
still relevant
