### ISSUE TITLE
(@aws-cdk/aws-amplify): invalid security token when deploying changes for existing amplify app

### ISSUE THREAD

**Issue by arnaskro** [aws/aws-cdk#12929]
When we try to update existing amplify apps, we get an invalid security token error. Although other stack deployments that are not using amplify are successful.

### Reproduction Steps

- Install @aws-cdk/aws-amplify 
- Create a TestAmplifyStack and create an amplify app. Example:
```
const amplifyApp = new CfnApp(this, 'app-test-amplify', {
      name: `Test Amplify 2`,
      customRules: []
})
```
- Deploy with `npx cdk deploy TestAmplifyStack`
- Make a code change, for example: add a custom rule
- Try to deploy again with `npx cdk deploy TestAmplifyStack`
- Deployment fails saying The security token in the request is invalid.

### What did you expect to happen?

I have expected the cdk deployment to be successful and amplify app to be updated.

### What actually happened?

Deployment fails and gives the following error:
`The security token included in the request is invalid (Service: Amplify; Status Code: 403; Error Code: UnrecognizedClientException; Request ID: 91ae4232-9740-4818-9fd6-f53489611f4a; Proxy: null)`

### Environment

  - **CDK CLI Version  :** 1.88.0
  - **Framework Version:** 1.88.0
  - **Node.js Version:** v14.15.4
  - **OS               :** macOS Big Sur 11.1
  - **Language (Version):** TypeScript (4.1.3)

### Other

I have to delete the stacks manually in AWS Console if I want to make a deployment with amplify stack code change. 
This doesn't happen with other aws-cdk packages, we have 9 other stacks running with various services and they all work as expected so I doubt that it could be a local authentication issue.

--- 

This is :bug: Bug Report

**Comment by malditogeek** [comment]
I'm experienced the same issue while trying to add an env var to an existing app. I was on v1.89; upgraded to v1.91 (latest as of 4/3/2021) but the issue persisted. Kept failing with `The security token included in the request is invalid`. Had to delete the stack and re-create again.

**Comment by arnaskro** [comment]
Hi, any update on this? I see it's tagged with with a small effort label, but that would be a huge help for us to get this working move forward 🤞

**Comment by MrArnoldPalmer** [comment]
Hi, we have no update on this currently. Amplify is in developer preview and we don't have any set plans to work on this right now on the core team side. PRs are welcome though if you're able.
