### ISSUE TITLE
(aws-cognito): Lambda Trigger lambda.Code.fromInline() example should be valid

### ISSUE THREAD

**Issue by douglasnaphas** [aws/aws-cdk#12930]
https://docs.aws.amazon.com/cdk/api/latest/docs/aws-cognito-readme.html#lambda-triggers

The code sample at the above link has

```ts
const authChallengeFn = new lambda.Function(this, 'authChallengeFn', {
  runtime: lambda.Runtime.NODEJS_10_X,
  handler: 'index.handler',
  code: lambda.Code.fromInline('auth challenge'),
});
```
and
```ts
userpool.addTrigger(cognito.UserPoolOperation.USER_MIGRATION, new lambda.Function(this, 'userMigrationFn', {
    runtime: lambda.Runtime.NODEJS_10_X,
  handler: 'index.handler',
  code: lambda.Code.fromInline('user migration'),
}));
```

The argument to [lambda.Code.fromInline](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-lambda.Code.html#static-fromwbrinlinecode) is supposed to be valid function code, like in the example at [Lambda with DLQ](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-lambda-readme.html#lambda-with-dlq):

```ts
...
code: lambda.Code.fromInline('exports.handler = function(event, ctx, cb) { return cb(null, "hi"); }'),
...
```

It is confusing for readers to have something syntactically invalid like `lambda.Code.fromInline('auth challenge')` in the docs. We should replace `'auth challenge'` and `'user migration'` with syntactically valid function code, or use [lambda.Code.fromAsset](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-lambda.Code.html#static-fromwbrassetpath-options) instead of `fromInline`.

---

This is a 📕 documentation issue

**Comment by nija-at** [comment]
You make a good point @douglasnaphas.

We should just use `fromAsset()` or replace the property with ellipses instead of being specific to use `Code.fromInline()`, like -

```ts
code: ...
```

Feel free to submit a PR for this.
