### ISSUE TITLE
(aws-cognito): Don't use {username} in verification email templates

### ISSUE THREAD

**Issue by douglasnaphas** [aws/aws-cdk#12931]
https://docs.aws.amazon.com/cdk/api/latest/docs/aws-cognito-readme.html#sign-up

The above link has this code sample for setting up user verification:

```ts
new cognito.UserPool(this, 'myuserpool', {
  // ...
  selfSignUpEnabled: true,
  userVerification: {
    emailSubject: 'Verify your email for our awesome app!',
    emailBody: 'Hello {username}, Thanks for signing up to our awesome app! Your verification code is {####}',
    emailStyle: cognito.VerificationEmailStyle.CODE,
    smsMessage: 'Hello {username}, Thanks for signing up to our awesome app! Your verification code is {####}',
  }
});
```

But the [Message Template docs](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pool-settings-message-templates.html) say:

> Note
{username} can't be used in verification emails. {username} is available for invitation emails sent after AdminCreateUser call. These invitation emails provide two place holders: username {username} and temporary password {####}

Remove `{username}` from `emailBody`, if it is indeed invalid there. I have not tested whether the `emailBody` and `smsMessage` from the docs will work in a real User Pool, but I intend to in a [test project](https://github.com/cdk-turnkey/cognito).

---

This is a 📕 documentation issue

**Comment by nija-at** [comment]
Sounds good. I'm sure that 'Note' in the documentation is a recent additional and wasn't present when this code was original written.
