### ISSUE TITLE
(dynamodb-global): synth fails when using DDB Global Tables with --no-staging

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#12937]
I'm trying to use the SAM CLI for local application testing  by following these instructions: https://docs.aws.amazon.com/cdk/latest/guide/sam.html

### Reproduction Steps

1. Create a CDK app with global DynamoDB tables.
2. Synthesize the stacks with `cdk synth --no-staging`

### What did you expect to happen?

No error.

### What actually happened?

The cdk abruptly exits with an unhandled file access error:

```
Running cdk with args: synth,--no-staging
Error: ENOENT: no such file or directory, open '<redacted>/aws-dynamodb/lib/replica-handler.zip'
```

### Environment

- CDK CLI Version : 1.80.0 (build 31132ca)
- Framework Version: (where do I find this?)
- Node.js Version: 12.20.1
- OS : MacOS Catalina 10.15.7 (19H512)
- Language (Version): TypeScript (3.9.7)

### Other

Internal reference: V310286616

--- 

This is :bug: Bug Report

**Comment by jarruda** [comment]
Environment

- CDK CLI Version : 1.80.0 (build 31132ca)
- Framework Version: (where do I find this?)
- Node.js Version: 12.20.1
- OS : MacOS Catalina 10.15.7 (19H512)
- Language (Version): TypeScript (3.9.7)

**Comment by eladb** [comment]
Thanks @jarruda - updated description with environment info.
