### ISSUE TITLE
lambda-python: Allow passing build args to Docker in PythonFunction

### ISSUE THREAD

**Issue by jamesTait-jt** [aws/aws-cdk#12949]
Ability to pass args to docker when using `aws_lambda_python.PythonFunction`

### Use Case
I am trying to deploy a stack from behind a proxy. I want to be able to pass `--network host` to the PythonLambda docker command so that the container is able to access the internet through the proxy.

### Proposed Solution
This seems to have been solved for `aws_lambda_nodejs` here:
https://github.com/aws/aws-cdk/issues/8117

So perhaps a similar solution?

### Other
* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by eladb** [comment]
Happy to accept contributions

**Comment by rirze** [comment]
Looking at this to pass ssh agent inside Docker. Would help in getting access to private repositories.

I'm going to try to implement this and make a PR, but I'm not fluent in typescript or CDK internals.

**Comment by jia2** [comment]
When will this feature be added?

**Comment by rirze** [comment]
Sorry, I've been procrastinating this for a while now-- mostly because I'm not super comfortable with TypseScript and not knowing how to implement this feature properly. 

I'll try to reopen the PR sometime this week or next week and move this forward.

**Comment by setu4993** [comment]
I have https://github.com/aws/aws-cdk/pull/15324 open which would resolve this.

**Comment by setu4993** [comment]
Not 100% sure what the desired solution was since the OP mentions:

> ...I want to be able to pass `--network host` to the PythonLambda docker command so that the container is able to access the internet through the proxy.

Going from https://github.com/aws/aws-cdk/pull/13938, if the goal was to only expose `HTTPS_PROXY` as a build arg that is used while bundling, #18082 added support for that.

**Comment by corymhall** [comment]
This should be fixed in #18082
