### ISSUE TITLE
custom_resources: AwsCustomResource missing dependencies between lambda and policies

### ISSUE THREAD

**Issue by rittneje** [aws/aws-cdk#12945]
We are trying to upgrade from v1.53.0 to v1.84.0. However, one of our custom resources is failing to create properly due to a permission issue while the lambda is running. It is important to note that the exact same CDK code works flawlessly in v1.53.0.

From looking at the CloudFormation template, it seems that CDK used to specify a dependency between the lambda and the (monolithic) policy. However, at some point CDK switched to generating separate policies for each AwsCustomResource, and the dependencies from the lambda to those policies are missing in the template. So it seems that the lambda is now racing the policy creation, possibly resulting in the bug we are seeing.

**Comment by ryparker** [comment]
Hey @rittneje :wave:

I just wanted to follow up on this and let you know that we've marked this issue as p1 which means that it has been prioritized as important and should see attention soon. Although please keep in mind that we do have a large number of issues at the moment. It may be some time before we are able to solve this particular issue. We use +1s to help us prioritize our work, and as always we are happy to take contributions if anyone is interested to pick this up and submit a PR.
