### ISSUE TITLE
(ec2): using encryption key on volume does not grant the correct permissions with the kms future flag

### ISSUE THREAD

**Issue by nija-at** [aws/aws-cdk#12962]
Future flag: `aws-kms:defaultKeyPolicies`

When the above future flag is set and an `encryptionKey` is configured on the volume, the EC2 service is not granted explicit permission to the key - https://github.com/aws/aws-cdk/blob/dd90e5464b24e097a3e41a81556924018a422181/packages/%40aws-cdk/aws-ec2/lib/volume.ts#L473-L488.

Manifested in the unit test - https://github.com/aws/aws-cdk/blob/59e58c740d2a8c25d2a122e441da743b8987b31e/packages/%40aws-cdk/aws-ec2/test/volume.test.ts#L209.

This is likely related to https://github.com/aws/aws-cdk/issues/10160#issuecomment-687169633

--- 

This is :bug: Bug Report

**Comment by corymhall** [comment]
@njlynch do you know if this is still an issue? It's not clear to me what the original issue is and in testing I was able to deploy and instance that attached a KMS encrypted volume.
