### ISSUE TITLE
(aws-ecr-assets): How to authenticate with Docker hub?

### ISSUE THREAD

**Issue by volkanunsal** [aws/aws-cdk#12977]
As you may know, Docker hub imposed [a daily pull limit on public repos](https://aws.amazon.com/blogs/containers/advice-for-customers-dealing-with-docker-hub-rate-limits-and-a-coming-soon-announcement/). As a result, our builds that use the `DockerImageAsset` construct have started to fail periodically when this limit is reached. 

![Screen Shot 2021-02-10 at 8 14 46 PM](https://user-images.githubusercontent.com/151600/107593670-e347a580-6bdd-11eb-8c0b-b62e4d1f8faf.png)

We can get around the limit by authenticating with Docker hub, but I can't figure out how to do that with CDK. Is there any way to use our Docker hub credentials instead of the generic AWS credentials? What can we do?

This is a :rocket: Feature Request

**Comment by eladb** [comment]
@volkanunsal where are you running your builds? Technically, you should be able to use `docker login` to authenticate before you run `cdk synth`. Would that work for your use case?

**Comment by volkanunsal** [comment]
Us-east-1.

 I can give that a try. Is there a code example showing how to do that?

**Comment by chris-nielsen-visiontree** [comment]
It would also help my team if it were clearer how to authenticate to dockerhub while building images from the CDK.
