### ISSUE TITLE
(aws-elasticache): Support AWS::ElastiCache::GlobalReplicationGroup as L1 Construct

### ISSUE THREAD

**Issue by dillon-odonovan** [aws/aws-cdk#12972]
There's a CloudFormation resource for [AWS::ElastiCache::GlobalReplicationGroup](https://docs.amazonaws.cn/en_us/AWSCloudFormation/latest/UserGuide/aws-resource-elasticache-globalreplicationgroup.html) but no matching L1 construct within the CDK.

### Use Case

We're exploring using [AWS Global Datastore](https://aws.amazon.com/elasticache/redis/global-datastore/) for a new application, and have recently been using the CDK to manage our infrastructure. If possible, we would like the ability to provision a global datastore via the CDK.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by iliapolo** [comment]
Should be resolved when https://github.com/aws/aws-cdk/pull/12960 is merged.
