### ISSUE TITLE
(core): Cannot read property 'cfnOptions' for sns.Topic.fromTopicArn

### ISSUE THREAD

**Issue by jacoblangston** [aws/aws-cdk#12974]
When referencing a SNS Topic from another account, I am unable to access the level 1 construct, and apply a condition.

### Reproduction Steps

import * as sns from '@aws-cdk/aws-sns';
import * as cdk from '@aws-cdk/core';

const condition = new cdk.CfnCondition(this, 'MyCondition', {
    expression: cdk.Fn.conditionEquals(cdk.Stack.of(this).environment, 'dev'),
  });

const topic = sns.Topic.fromTopicArn(this, 'myTopic', 'arn');
const cfnTopic = topic.node.defaultChild as sns.CfnTopic;
cfnTopic.cfnOptions.condition = condition;

### What did you expect to happen?

Per https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html, the level 1 construct should be available, the condition should be applied, and there should not be an error.

### What actually happened?

Build fails with 'Cannot read property 'cfnOptions' of undefined'.

### Environment

  - **CDK CLI Version  :*1.86.00*
  - **Framework Version:*1.72.0*
  - **Node.js Version:*v14.15.4* 
  - **OS               :*Mac OS X*
  - **Language (Version):*TypeScript (3.7.2)* 

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
You are trying to combine two things that don't go together.

* CFN Conditions can be used to *conditionally create* a resource.
* You are importing a resource that *definitely already exists*.

It's not possible to not have created a thing that already exists. It's also not possible to un-create it.

Don't use CFN Conditions. If you need to sometimes do something to a function and sometimes not, do it in your CDK app at synthesis time, and pass around an `IFunction | undefined`, or potentially create your own class implementing `IFunction` that does nothing at strategic points in time.

**Comment by alekspickle** [comment]
Welp, any workaround for this? even if I simply trying to create new DDB table I get this error

```
import * as ddb from "@aws-cdk/aws-dynamodb";
...
        let table = new ddb.Table(this, "locks", {
            billingMode: ddb.BillingMode.PAY_PER_REQUEST,
            partitionKey: {
                name: "LockID",
                type: ddb.AttributeType.STRING,
            },
        });

        let table1 = table.node.defaultChild as ddb.Table;
        table1.cfnOptions.metadata = {
            cfn_nag: {
                rules_to_suppress: [
                    {
                        id: "W12",
                    }
                ]
            }
        };
...
error TS2339: Property 'cfnOptions' does not exist on type 'Table'.

```
