### ISSUE TITLE
(aws-s3): Wrong type stated as the default for Bucket's blockPublicAccess prop

### ISSUE THREAD

**Issue by douglasnaphas** [aws/aws-cdk#12978]
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-s3.Bucket.html#blockpublicaccess

In the above section of the docs, the default for `Bucket`'s constructor prop of `blockPublicAccess` is stated as `false`, but the type of the `blockPublicAccess` prop is `BlockPublicAccess`, not `boolean`.

I am not able to compile, for example:
```ts
const myBucket = new s3.Bucket(this, "MyBucket", {
  blockPublicAccess: false,
});
```

I get the error:

```
Type 'false' is not assignable to type 'BlockPublicAccess | undefined'
```

I don't see an assignment to `blockPublicAccess` prior to [where we pass it on to the CfnBucket](https://github.com/aws/aws-cdk/blob/3b5ff0562090059f3a94140161acce53e484776c/packages/%40aws-cdk/aws-s3/lib/bucket.ts#L1329), so maybe instead of `@default false` [here](https://github.com/aws/aws-cdk/blob/3b5ff0562090059f3a94140161acce53e484776c/packages/%40aws-cdk/aws-s3/lib/bucket.ts#L1164) we need `default undefined`?

---

This is a 📕 documentation issue

**Comment by iliapolo** [comment]
@douglasnaphas Thanks!
