### ISSUE TITLE
(cognito): CfnIdentityPoolRoleAttachment with rolemappings seems impossible...

### ISSUE THREAD

**Issue by sblackstone** [aws/aws-cdk#12988]
The roleMappings property requires that you use identity provider as a key, however if you try to do:

```  
const identityProviderUrl : string = `cognito-idp.us-east-1.amazonaws.com/${this.userPool.userPoolId}:${this.userPoolClient.userPoolClientId}`;
```

You get:

```      
throw new Error(`"${key}" is used as the key in a map so must resolve to a string, but it resolves to: ${JSON.stringify(resolvedKey)}. Consider using "CfnJson" to delay resolution to deployment-time`);
```

Is there any workaround to this that doesn't require hard coding it as a property / multiple deploys to bootstrap?

### Reproduction Steps

```
    const identityProviderUrl : string = `cognito-idp.us-east-1.amazonaws.com/${this.userPool.userPoolId}:${this.userPoolClient.userPoolClientId}`;

    const roleMapping : cognito.CfnIdentityPoolRoleAttachment.RoleMappingProperty = {
      identityProvider: identityProviderUrl,
      ambiguousRoleResolution: "Deny",
      type: "Rules",
      rulesConfiguration: {
        rules: [{
          claim: "cognito:groups",
          matchType: "Contains",
          value: "xxxxxxxx",
          roleArn: this.authenticatedRole.roleArn
        }]
      }
    }

    new cognito.CfnIdentityPoolRoleAttachment(this as any, "IdentityPoolRoleAttachment", {
        identityPoolId: this.identityPool.ref,
        roles: {},
        roleMappings: {
          [identityProviderUrl]: roleMapping   // <---- Problem occurs here...
        }
    });
```

This is :bug: Bug Report

**Comment by nija-at** [comment]
Keys in CloudFormation templates cannot contain tokens. Information such as `userPoolId` and `userPoolClientId` are tokens that get resolved only during deployment. 

As indicated by the error message, have you tried using `CfnJson`?

**Comment by sblackstone** [comment]
@nija-at Any suggestions on syntax here?

I've been trying to use CfnJson as below but I'm getting an error:

```
Property validation failure: [Encountered unsupported properties in {/RoleMappings/cognito-idp.us-east-1.amazonaws.com~1us-east-1_MizO6F8rI:pf32vucitv5voc4umfngh4b3f}: [rulesConfiguration, type, identityProvider, ambiguousRoleResolution]]
```
    const identityProviderUrl : string = `cognito-idp.us-east-1.amazonaws.com/${this.userPool.userPoolId}:${this.userPoolClient.userPoolClientId}`;

    const roleMapping : cognito.CfnIdentityPoolRoleAttachment.RoleMappingProperty = {
      identityProvider: identityProviderUrl,
      ambiguousRoleResolution: "Deny",
      type: "Rules",
      rulesConfiguration: {
        rules: [{
          claim: "cognito:groups",
          matchType: "Contains",
          value: "subscribers",
          roleArn: this.authenticatedRole.roleArn
        }]
      }
    }

    const roleMapJson = new cdk.CfnJson(this, 'roleMappingJson1', {
      value: {
        [identityProviderUrl]: roleMapping
      }
    });
    ```

**Comment by nija-at** [comment]
Can you provide the CloudFormation snippet for `AWS::Cognito::IdentityPoolRoleAttachment` from the synthesized template?

**Comment by juanpujol** [comment]
Having the same issue, can't resolve the right role mapping for Cognito. 

```
hrow new Error(`"${String(key)}" is used as the key in a map so must resolve to a string, but it resolves to: ${JSON.stringify(resolvedKey)}. Consider using "CfnJson" to delay resolution to deployment-time`);
              ^
Error: Resolution error: Resolution error: "${Token[TOKEN.123]}" is used as the key in a map so must resolve to a string, but it resolves to: {"Fn::Join":["",["\"cognito-idp.us-east-1.amazonaws.com/",{"Ref":"UserPool6BA7E5F2"},":",{"Ref":"UserPoolClient2F5918F7"},"\""]]}. Consider using "CfnJson" to delay resolution to deployment-time..
```

**Comment by EzequielMoroni** [comment]
Hi @juanpujol I am facing the same issue, did you find a solution?

**Comment by chauncey-garrett** [comment]
For anyone stumbling into this issue, see https://docs.aws.amazon.com/cdk/api/latest/docs/core-readme.html#cfnjson.

```js
const tagParam = new CfnParameter(this, 'TagName');

const stringEquals = new CfnJson(this, 'ConditionJson', {
  value: {
    [`aws:PrincipalTag/${tagParam.valueAsString}`]: true,
  },
});

const principal = new iam.AccountRootPrincipal().withConditions({
  StringEquals: stringEquals,
});

new iam.Role(this, 'MyRole', { assumedBy: principal });
```
