### ISSUE TITLE
(aws-ecs-patterns): Some service patterns still inline desired count to 1 when not present

### ISSUE THREAD

**Issue by dastbe** [aws/aws-cdk#12990]
[Previous changes](https://github.com/aws/aws-cdk/pull/12223) were made to make desired count truly optional through to cloudformation to make autoscaling work more consistently for create and update. However, this change was not applied to all patterns ([example](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-ecs-patterns/lib/base/application-load-balanced-service-base.ts#L368-L371))

### Reproduction Steps

Use ApplicationLoadBalancedEc2Service and do not set a desired count. This will result in a desired count of 1 in the template.

### What did you expect to happen?

The final template should have no desired count set.

### What actually happened?

The desired count was set to 1.

### Environment

Cut this on behalf of someone else, but I've provided references to the issue in cdk itself

  - **CDK CLI Version  :** n/a
  - **Framework Version:** n/a
  - **Node.js Version:**  n/a
  - **OS               :** n/a
  - **Language (Version):**  n/a

### Other

--- 

This is :bug: Bug Report

**Comment by piradeepk** [comment]
@dastbe Thanks for reporting this issue. There is a PR out to fix this issue across all patterns, but in the meantime, you would be able to override the current construct using the ConstructNode escape hatch. This will allow users to override the current desiredCount behaviour to generate the cfn template without the desiredCount specified. 

For instance, if you have a service defined like so:

```
export class TestingDirStack extends cdk.Stack {
  constructor(scope: cdk.App, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const vpc = new ec2.Vpc(this, 'MyVpc', { maxAzs: 2 });
    const cluster = new ecs.Cluster(this, 'Cluster', { vpc });

    const albFargateService = new ecs_patterns.ApplicationLoadBalancedFargateService(this, "FargateService", {
      cluster,
      taskImageOptions: {
        image: ecs.ContainerImage.fromRegistry("amazon/amazon-ecs-sample"),
      },
    });
  }
}

const app = new cdk.App();
new TestingDirStack(app, 'Bonjour');
app.synth();
```

You can override the desiredCount set in the ApplicationLoadBalancedFargateService construct by adding the following:
```
const cfnService = albFargateService.service.node.children.find(c => c instanceof ecs.CfnService) as ecs.CfnService;
cfnService.desiredCount = undefined;
```

Based on the original app, the new app would look like the following:
export class TestingDirStack extends cdk.Stack {
  constructor(scope: cdk.App, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const vpc = new ec2.Vpc(this, 'MyVpc', { maxAzs: 2 });
    const cluster = new ecs.Cluster(this, 'Cluster', { vpc });

    const albFargateService = new ecs_patterns.ApplicationLoadBalancedFargateService(this, "FargateService", {
      cluster,
      taskImageOptions: {
        image: ecs.ContainerImage.fromRegistry("amazon/amazon-ecs-sample"),
      },
    });

    const cfnService = albFargateService.service.node.children.find(c => c instanceof ecs.CfnService) as ecs.CfnService;
    cfnService.desiredCount = undefined;
  }
}

const app = new cdk.App();
new TestingDirStack(app, 'Bonjour');
app.synth();
```
