### ISSUE TITLE
(ApplicationLoadBalancedFargateService): Auto scaling won't scale-in after update service with force new deployment option

### ISSUE THREAD

**Issue by tai-acall** [aws/aws-cdk#13004]
The ECS(Fargate) auto scaling out is working as expect, but if I update the ECS service with force new deployment option in the AWS web UI, after the deployment process done, the ECS service CPU/MEN usage decreased and the CloudWatch Alarm which named with 'AlarmLow' triggered but the Desired count not decreasing.

### Reproduction Steps

1. Deploy a ECS service with ApplicationLoadBalancedFargateService as following.

https://docs.aws.amazon.com/cdk/api/latest/docs/aws-ecs-patterns-readme.html#add-metric-based-auto-scaling-to-an-applicationloadbalancedfargateservice

2. Trigger auto-scale out with some test traffic
3. Click update in ECS service panel in AWS UI
4. Check 'force new deployment' box, don't touch anything else and update the ECS service
5. waiting for new deployment done and the CPU/MEN usage should below the auto scale alert count.
6. Check the CloudWatch and the alarm named with 'AlarmLow' should in alarm status but ECS Desired Count not decrease

### What did you expect to happen?

the CPU/MEN usage is below the alert setting and the 'AlarmLow' in alarm status, the desired count should be decreased.

### What actually happened?

'AlarmLow' in alarm status but the ECS desired count not decreased.

### Environment

  - **CDK CLI Version  : @aws-cdk/core@1.88.0, @aws-cdk/aws-ecs-patterns@1.88.0**
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):** 

### Other

--- 

This is :bug: Bug Report

**Comment by tai-acall** [comment]
Just a quick update.

I contact AWS Support for further detail information, this case might causing by ECS auto scaling trigger. 

for short, the scale-in trigger value is too close so ECS won't scale-in for prevent aggressive scale-out and in. 

in my case the scale-out trigger value is 70% of memory usage that set in CDK, while the ECS service memory usage down to 61% it should run scale-in as except (at least the scale-in alarm is 63% automatically set by CDK), but for ECS it still too close.

If I change the scale-out trigger to 90% of memory usage the ECS service run scale-in as except.

**Comment by TrentonAdams** [comment]
I'm not sure if this is related, but I'm having a problem with deleting a stack with an ASG for ECS.  

There's a message in the ASG configuration (activity tab) saying `Could not scale to desired capacity because all remaining instances are protected from scale-in.`.  I go disable scale-in protection on the instance, and it continues deleting the stack almost immediately.

I'm guessing the following should default `newInstancesProtectedFromScaleIn` to false in the properties???

```typescript
        const autoScalingGroup = new autoscaling.AutoScalingGroup(this, 'ASG', {
            vpc: props.smw_vpc,
            instanceType: new ec2.InstanceType('t2.micro'),
            machineImage: ecs.EcsOptimizedImage.amazonLinux2(),
            minCapacity: 0,
            desiredCapacity: 1,
            maxCapacity: 2,
        });
```

e.g.
```typescript
        const autoScalingGroup = new autoscaling.AutoScalingGroup(this, 'ASG', {
            vpc: props.smw_vpc,
            instanceType: new ec2.InstanceType('t2.micro'),
            newInstancesProtectedFromScaleIn: false,
            machineImage: ecs.EcsOptimizedImage.amazonLinux2(),
            minCapacity: 0,
            desiredCapacity: 1,
            maxCapacity: 2,
        });
```

Should I file a separate issue, or is this related?

**Comment by TrentonAdams** [comment]
According to the [docs](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-autoscaling-readme.html), the property I mentioned (`newInstancesProtectedFromScaleIn: false`) should need to be explicitly set to true in order for scale in protection to be enabled, but that's not the case.  In fact it ignores the value altogether, preventing a false value from being noticed.

**Comment by tdna** [comment]
@TrentonAdams if you are using `AsgCapacityProvider` and `enableManagedTerminationProtection` is turned on `newInstancesProtectedFromScaleIn`  is set to true automatically. This is done by cloudformation not CDK.

> The Auto Scaling group and each instance in the Auto Scaling group must have instance protection from scale-in actions enabled as well.

**Comment by TrentonAdams** [comment]
I completely forgot about this issue.  @tdna You are correct, I had discovered that myself awhile back.  Closing.

**Comment by TrentonAdams** [comment]
Oh, I don't have permission to close.  Who can?

**Comment by TrentonAdams** [comment]
Oh, I didn't create it, duh. :P
