### ISSUE TITLE
(Imagebuilder): cdk diff not detecting changes

### ISSUE THREAD

**Issue by nigel-heaney** [aws/aws-cdk#13016]
Updating a component or image recipe version is not reflected in cdk diff and will report no changes but a deploy will replace those resources with the new version.  

### Reproduction Steps

```typescript
const exampleYumUpdate = new imagebuilder.CfnComponent(this, 'exampleYumUpdate', {
  name: "exampleYumUpdate",
  platform: "Linux",
  version: "0.0.1",
  uri: `s3://${s3bucket.bucketName}/components/yum_update.yml`,
})

const exampleRecipe = new imagebuilder.CfnImageRecipe(this, "exampleRecipe", {
  name: 'exampleRecipe',
  version: '0.0.1',
  components: [
    { "componentArn": exampleYumUpdate.attrArn }
  ],
  parentImage: "ami-0f82969826859fb14",
})
```

update the versions to 0.0.2 and cdk diff shows

```bash
cdk diff
Stack ExampleStack
There were no differences

# then deploy
cdk deploy
ExampleStack: deploying...
ExampleStack: creating CloudFormation changeset...
[█████████████████████████████·····························] (2/4)

 ✅  ExampleStack
```

### What did you expect to happen?

It should report that those resources will be replaced.

### Environment

  - **CDK CLI Version  :** 1.89.0
  - **Framework Version:**
  - **Node.js Version:** v12.14.1
  - **OS               :** macOS 10.15.7
  - **Language (Version):** typescript@3.9.8

### Other

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Thanks for reporting @nigel-heaney . Confirming I was able to reproduce it. Digging into this further.

**Comment by skinny85** [comment]
The problem is [this line](https://github.com/aws/aws-cdk/blob/09ba573a816cc4fa9898c1700136bb332801721c/packages/%40aws-cdk/cloudformation-diff/lib/diff/util.ts#L26-L26). Apparently, in JavaScript, `parseFloat('0.0.1') === parseFloat('0.0.2') === 0`.
