### ISSUE TITLE
(apigateway): proxy=false ignored on LambdaRestApi

### ISSUE THREAD

**Issue by losalamosal** [aws/aws-cdk#13026]
Setting `proxy=false` on a `LambdaRestApi` appears to be ignored. The resulting lambda function in the API is still proxied.

### Reproduction Steps

I first reported this as a bug on the [`cognito-api-example`](https://github.com/aws-samples/aws-cdk-examples/issues/385) in the `aws-samples/aws-cdk-samples` repository. My own code was experiencing the same bug and I used the example (with similar code to mine) to test the bug. I now believe the bug is in CDK and not that specific example (or my code).

As test code, to reproduce the bug, I've trimmed that example down to the bare minimum and published it at [my GitHub repo](https://github.com/losalamosal/cdk-proxy-bug). Shown below is the relevant code. First, `index.js` that defines the stack, etc.:
```javascript
const { App, Stack } = require("@aws-cdk/core");
const { Function, Runtime, AssetCode } = require("@aws-cdk/aws-lambda");
const { LambdaRestApi, LambdaIntegration } = require("@aws-cdk/aws-apigateway");

class CdkProxyBugStack extends Stack {
  constructor(app, id) {
    super(app, id);

    // Function that returns 201 with "Hello world!"
    const helloWorldFunction = new Function(this, 'helloWorldFunction', {
      code: new AssetCode('src'),
      handler: 'helloworld.handler',
      runtime: Runtime.NODEJS_12_X
    });

    // Rest API backed by the helloWorldFunction
    const helloWorldLambdaRestApi = new LambdaRestApi(this, 'helloWorldLambdaRestApi', {
      restApiName: 'Hello World API',
      handler: helloWorldFunction,
      proxy: false,
    });

    // Hello Resource API for the REST API. 
    const hello = helloWorldLambdaRestApi.root.addResource('HELLO');

    // GET method for the HELLO API resource.
    hello.addMethod('GET', new LambdaIntegration(helloWorldFunction))
  }
}

const app = new App();
new CdkProxyBugStack(app, 'CdkProxyBugStack');
app.synth();
module.exports = { CdkProxyBugStack }
```
and the simple lambda function:
```javascript
exports.handler = async (event) => {
  console.log(event);
  return { statusCode: 201, body: 'Hello world!' };
}
```

### What did you expect to happen?

One expects that this will create a REST API with a single lambda, not proxied.

### What actually happened?

The code works fine, the lambda is called successfully. However, if I visit the API in the AWS console I see the following:
- the Integration Request on the `GET` method shows *Use Lambda Proxy integration*
- the Integration Response box in the UI is greyed out and inactive

### Environment

  - CDK CLI Version  : 1.89.0 (and before)
  - Framework Version: 1.89.0 (and before)
  - Node.js Version: 15.1.0
  - OS: MacOS 10.14.5
  - Language (Version): N/A

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
I'm unable to replicate your issue. This works just fine for me.

I was able to deploy the below app to an AWS account and execute the /HELLO/GET from the APIGateway console which correctly returned 'Hello World!'. I've also attached the screenshot.

```ts
import { Stack, App, Lazy, CfnOutput } from '@aws-cdk/core';
import { LambdaRestApi } from '@aws-cdk/aws-apigateway';
import { Code, Function, Runtime } from '@aws-cdk/aws-lambda';

const app = new App();
const stack = new Stack(app, 'MyStack');

const fn = new Function(stack, 'MyFn', {
  code: Code.fromInline('exports.handler = async (event) => { console.log(event); return { statusCode: 200, body: "Hello world!" }; }'),
  handler: 'index.handler',
  runtime: Runtime.NODEJS_12_X,
});

const api = new LambdaRestApi(stack, 'LambdaRestApi', {
  handler: fn,
  proxy: false,
});

const resource = api.root.addResource('HELLO')

resource.addMethod('GET');
```

![Screenshot 2021-02-25 at 10 16 48](https://user-images.githubusercontent.com/16217941/109138733-9540af00-7752-11eb-89b4-047e6f15ad1f.png)

**Comment by losalamosal** [comment]
Thanks very much for taking a look at this (and for showing me how to shorten a test example).

As I said, my code also works fine. The problem I'm pointing out is that the REST API appears to be proxied even though `proxy=false`. Would you mind checking your test, via a similar screenshot, to see if the Integration Response box on the main API page is greyed out? This is the problem I'm seeing.

I'm new to this, and this may simply be a minor bug where a flag is not being set. I'm simply wondering if the will cause problems down the line (e.g. if I were to try and attach an integration response to the Rest API.

@nija-at

**Comment by nija-at** [comment]
As far as I can tell, the correct flags are being set. You can check this yourself by comparing the CloudFormation template by setting and unsetting the flag and looking at what changes.

Let us know if something there is incorrectly configured. Closing this issue.

**Comment by zoe-L** [comment]
I encountered the same issue while using the LambdaRestApi() function.

```
const restApi = new LambdaRestApi(this, 'someApi', {
      handler: someLambdaFunction,
      proxy: false
});
```

The return message I get from AWS Console:
```
Thu Jun 24 21:14:55 UTC 2021 : Execution failed due to configuration error: Malformed Lambda proxy response
Thu Jun 24 21:14:55 UTC 2021 : Method completed with status: 502
```

**Comment by losalamosal** [comment]
@zoe-L I still think this is a bug. I'm not sue they looked at console issues that I pointed out in the bug report. They're understandably (1.8K open issues) busy, and I don't have time to chase i down myself (right now). Maybe I'll dig into it down the road.

**Comment by rajivjeyaraj** [comment]
I am facing the same issue while using the LambdaRestApi() function in Python. Though I mention proxy=False while using this function, the Integration Request type, in every API method, is being set to LAMBDA_PROXY. **Use Lambda Proxy integration** checkbox is enabled.
I am using _**aws-cdk.core==1.138.1**_
Are there any work-around available?

**Comment by iiian** [comment]
> I am facing the same issue while using the LambdaRestApi() function in Python. Though I mention proxy=False while using this function, the Integration Request type, in every API method, is being set to LAMBDA_PROXY. **Use Lambda Proxy integration** checkbox is enabled. I am using _**aws-cdk.core==1.138.1**_ Are there any work-around available?

Same. Could we please reopen this issue, @nija-at ?

**Comment by iiian** [comment]
To those looking for a solution that come across this thread, the solution is to **not** use `LambdaRestApi`. Instead, you should specify that you want your api to be a proxy in the `LambdaIntegration` that you attach to a method via `api.addMethod`. For example:

```typescript
const api = new RestApi(this, 'my-rest-api', ...);
const resource = api.root.addResource('resource');
const integration = new LambdaIntegration(
  getMyIntegration(...), {
    proxy: false 
  }
);
resource.addMethod('POST', integration, ...);
```

**Comment by ChristianUlbrich** [comment]
@iiian You are right, but your code example is too contrived. A complete example can be seen in https://github.com/aws/aws-cdk/issues/21787#issuecomment-1229359699 and this - as of now (2024-08-21) - solves the problem.

@rajivjeyaraj The bugs are not bound to any specific language, because all languages are "under the hood" are calling the _TypeScript_ one, i.e. this `aws-cdk`, so it is not surprising, that you are suffering from exact the same problems...
