### ISSUE TITLE
(@aws-cdk/aws-appsync): Internal error while saving the schema

### ISSUE THREAD

**Issue by owenashurst** [aws/aws-cdk#13032]
When creating a GraphQL API, cloudformation keeps failing with an "Internal error while saving the schema" error.

### Reproduction Steps
Typescript
```
const websiteGraphqlApi = new GraphqlApi(this, 'api', {
	name: `My API`,
	logConfig: {
	  fieldLogLevel: FieldLogLevel.ALL,
	},
	authorizationConfig: {
		defaultAuthorization: {
			authorizationType: AuthorizationType.USER_POOL,
			userPoolConfig: {
				userPool: props.userPool,
				defaultAction: UserPoolDefaultAction.ALLOW
			},
		},
		additionalAuthorizationModes: [{
			authorizationType: AuthorizationType.API_KEY,
		}],
	},
	schema: Schema.fromAsset(join(__dirname, 'schema.graphql'))
});

const productsTable = new Table(this, 'products-table', {
	partitionKey: {
	  name: 'id',
	  type: AttributeType.STRING,
	},
});

const productsDataSource = websiteGraphqlApi.addDynamoDbDataSource('products-datasource', productsTable);

productsDataSource.createResolver({
	typeName: 'Query',
	fieldName: 'getProducts',
	requestMappingTemplate: MappingTemplate.dynamoDbScanTable(),
	responseMappingTemplate: MappingTemplate.dynamoDbResultList(),
});

productsDataSource.createResolver({
	typeName: 'Mutation',
	fieldName: 'addProduct',
	requestMappingTemplate: MappingTemplate.dynamoDbPutItem(
		PrimaryKey.partition('id').auto(),
		Values.projecting('Product')
	),
	responseMappingTemplate: MappingTemplate.dynamoDbResultItem(),
});
```

schema.graphql
```
type Product {
    id: ID!
    title: String!
    price: Int!
    quantity: Int!
    category: Category!
}

type Category {
    id: ID!
    title: String!
    Products: [Product!]!
}

type Query {
    getProducts: [Product!]!
}

input CategoryInput {
    id: String!
}

input AddProductInput {
    title: String!
    price: Int!
    quantity: Int!
    category: CategoryInput!
}

type Mutation {
    addProduct(input: AddProductInput!): Product
}
```

### What did you expect to happen?
Appsync to be created with the schema.

### What actually happened?
CloudFormation fails with the error:
`Schema Creation Status is FAILED with details: Internal Failure while saving the schema.`

### Environment

  - **CDK CLI Version  :** 1.88.0 (build f65009b)
  - **Framework Version:**
  - **Node.js Version:** node12.18
  - **OS:** Linux
  - **Language (Version):** TypeScript (3.8.3)

### Other
I've tried using the example on the AWS-CDK documentation [here](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-appsync-readme.html) for both the schema and typescript however I still get the same issue.

This is :bug: Bug Report

**Comment by owenashurst** [comment]
@MrArnoldPalmer turns out the issue was due to an issue with how the CI/CD pipeline was setup. This can be closed.

**Comment by PeterEckIII** [comment]
@owenashurst , out of curiosity, what was the solution? Currently running into this issue myself. Curious if you saw logs in Cloudwatch regarding the server shutting down and restarting, as that seems to be the only indication things are going wrong with my stack deploying. Thanks

**Comment by owenashurst** [comment]
> @owenashurst , out of curiosity, what was the solution? Currently running into this issue myself. Curious if you saw logs in Cloudwatch regarding the server shutting down and restarting, as that seems to be the only indication things are going wrong with my stack deploying. Thanks

In my case it wasn't using the correct branch in my pipeline. If you're having the same kind of issue, it'll most likely be your schema.

**Comment by MrArnoldPalmer** [comment]
thanks @owenashurst for the update. Closing this for now. It seems AppSync can throw quite a few "internal errors" during deploy related to the schema. It would be nice if we could start to catch these earlier and trow better messages. Closing for now but @PeterEckIII open another issue with your repro if you haven't solved it and we will take another look.
