### ISSUE TITLE
`targets` is invalid as stack id

### ISSUE THREAD

**Issue by ctrahey** [aws/aws-cdk#13039]
### The Question
When I use `targets` as the id of my stack, behavior is unexpected and destructive. 

Specifically, I have a stack that adds Nodegroup capacity to an existing EKS cluster. Whenever I use `targets` as the id for this stack, the CF output includes destruction of any existing Nodegroups on the cluster (even if I add references to the existing Nodegroups in my stack). When I change this id to anything else (including `target`, dropping the `s`), the stack appears to work ok.

### Environment

  - **CDK CLI Version:** 1.89.0 (build df7253c)
  - **Module Version:** aws-cdk.aws-eks==1.89.0
  - **Node.js Version:** v15.5.1
  - **OS:** Debian Buster (official Node docker image, FROM node:15.5-buster)
  - **Language:** Python

### Other information
I am adding the nodegroup via the Nodegroup constructor, since the stack has to import the cluster by reference, so add_nodegroup_capacity is not available. 

```
class TargetsStack(core.Stack):
    def __init__(self, scope: core.Construct, construct_id: str,  **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        # resolve_cluster_name(), resolve_vpc_id(), existing_ng_names()
        # these functions use aws cli calls to find the existing cluster/vpc/ng names.
        # I have verified they work as expected.
        cluster_name = resolve_cluster_name() 
        vpc_id = resolve_vpc_id(cluster_name)
        vpc = ec2.Vpc.from_lookup(self, 'eks_vpc', vpc_id=vpc_id)
        cluster = eks.Cluster.from_cluster_attributes(self, 'BenchmarkingCluster',
                                                      cluster_name=cluster_name,
                                                      vpc=vpc)
        existing_nodegroups = existing_ng_names(cluster_name)
        for ng in existing_nodegroups:
            eks.Nodegroup.from_nodegroup_name(self, ng, ng)
        new_ng = eks.Nodegroup(self, 'new_nodegroup',
                           cluster=cluster,
                           desired_size=2,
                           instance_types=[ec2.InstanceType('c6g.large')],
                           labels={'benchmarking-role': 'target-d'}
                           )
```

```
### DESTROYS EXISTING NODEGROUPS ###
# in app.py
TargetsStack(app, "targets", env=env)
# at shell...
cdk diff targets
....
Resources
[-] AWS::IAM::Role targetcNodeGroupRole4DDBDE04 destroy
[-] AWS::EKS::Nodegroup targetcB24A4719 destroy       <<<<--------- NOT GOOD/NOT INTENDED! ---------|||||
[+] AWS::IAM::Role target_d/NodeGroupRole targetdNodeGroupRole371D4317 
[+] AWS::EKS::Nodegroup target_d targetd96D84717 



### WORKS ###
# in app.py
TargetsStack(app, "foobar", env=env)
# at shell...
cdk diff foobar
....
Resources
[+] AWS::IAM::Role target_d/NodeGroupRole targetdNodeGroupRole371D4317 
[+] AWS::EKS::Nodegroup target_d targetd96D84717 

```
Notice that to move from not-working to working, I did not change my stack code at all - only the "id" param when constructing the Stack object.

**Comment by peterwoodworth** [comment]
Hey @ctrahey, sorry for the long response. This didn't get labelled as a guidance issue or a bug for some reason

This is happening because you first deployed the stack with the name 'targets' with a different `id` for the `eks.Nodegroup` you're creating. You have since updated the name to `new_nodegroup`, so the CDK will detect this difference and remove the old nodegroup you first deployed.

Try supplying a different `id` to the nodegroup you're creating in your `foobar` stack and you'll get the same diff. Hope this helps! Ping me if you need additional guidance
