### ISSUE TITLE
@aws-cdk/aws-iam

### ISSUE THREAD

**Issue by geomen888** [aws/aws-cdk#13040]
I try to add role as root user. Put { env: { account: 857018159998, region: eu-central-1 } } , core version 1.8.5
add role and get trace error:
"metadata": {
        "/ProductionModuleVVCR/Ec2SqsRoleVvcrMc/Resource": [
          {
            "type": "aws:cdk:logicalId",
            "data": "Ec2SqsRoleVvcrMcB263195E",
            "trace": [
              "new Role (/Users/yevgeniygeyman/PROJECTS/vvcr-ms/node_modules/@aws-cdk/aws-iam/lib/role.js:70:22)",
              "ConfigAMIService.updateRole (/Users/yevgeniygeyman/PROJECTS/vvcr-ms/dist/src/api/autoscaling/aws-config/config.ami.service.js:35:32)",
              "AutoscalingGateway.start (/Users/yevgeniygeyman/PROJECTS/vvcr-ms/dist/src/api/autoscaling/autoscaling.gateway.js:30:54)",
              "EventEmitter.eventEmitter.on.args (/Users/yevgeniygeyman/PROJECTS/vvcr-ms/node_modules/@nestjs/event-emitter/dist/event-subscribers.loader.js:47:70)",
              "Immediate._onImmediate (/Users/yevgeniygeyman/PROJECTS/vvcr-ms/node_modules/eventemitter2/lib/eventemitter2.js:767:23)",
              "runCallback (timers.js:705:18)",
              "tryOnImmediate (timers.js:676:5)",
              "processImmediate (timers.js:658:5)",
              "process.topLevelDomainCallback (domain.js:126:23)"
            ]
          }
   
### Reproduction Steps
const role = new Role(this, Ec2SqsRoleVvcrMc , {
      assumedBy: new ServicePrincipal('sns.amazonaws.com'), 
      // managedPolicies: [ManagedPolicy.fromAwsManagedPolicyName(policy)], // policy ec2.amazonaws.com
      //roleName: Util.getAwsId(roleName),  // Ec2SqsRoleVvcrMc
      //description,
      // externalIds: ['SUPPLY-ME'],
      maxSessionDuration: cdk.Duration.hours(2),
    });
  const phase = await this.scope.synth();
  console.log('ConfigAMIService:updateRole:manifest:', JSON.stringify(phase.manifest, null, 2))

### What did you expect to happen?
I want to obtain role name in list of IAM roles in AWS console

### What actually happened?
Nothing role not deployed to AWS console

### Environment

  - **CDK CLI Version  :1.85
  - **Framework Version:** nestjs@7.6
  - **Node.js Version:** 10.23
  - **OS               : Mac OS big sur
  - **Language (Version):**  TypeScript (3.8.3) 

### Other

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
This bug report confuses me. I have been trying to read this for 5 minutes, and due to the lack of formatting, explaining what the goal was, example code that obviously won't compile, and a weird way of using `synth`, I still can't figure out what you were trying to achieve or how you thought you were going to go about it.

I'm going to close this. If you want to create a new issue for this, please explain WHAT you want to do, WHY you think what you're doing will achieve that, then paste in working code and paste the complete error message.
