### ISSUE TITLE
(aws-cdk-lib): npm install aws-cdk-lib doesn't bring the latest alpha release

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#13058]
When running `npm install aws-cdk-lib`, users get the last published module into the `latest` dist-tag, which is currently `2.0.0-alpha.0`, while the `next` dist-tag includes the actual latest.

Since aws-cdk-lib is a new module, I think we should publish our alpha releases under the `latest` dist-tag in order to allow early adopters to install the correct version. There is no notion of "next" for aws-cdk-lib yet. When we prepare CDK v3.0, it will make sense to publish it under the @next dist-tag since at that point @latest will refer to the stable v2.x line.

### Reproduction Steps

```shell
npm instal aws-cdk-lib
```

### What did you expect to happen?

I expected `v2.0.0-alpha.4`.

### What actually happened?

I got `v2.0.0-alpha.0`.

### Other

Output of `npm view aws-cdk-lib`:

```
aws-cdk-lib@2.0.0-alpha.0 | Apache-2.0 | deps: 9 | versions: 5
The AWS Cloud Development Kit library
https://github.com/aws/aws-cdk

keywords: aws, cdk

dist
.tarball: https://registry.npmjs.org/aws-cdk-lib/-/aws-cdk-lib-2.0.0-alpha.0.tgz
.shasum: 70def4619e8bc4250da7d569ca87871de08117be
.integrity: sha512-8gG8gbazCVJPYbS7bwadJyEsRAGfdWr5jlqiw3DS7yTzXGCwufc5DMmTv89pEO3KTdO9naIAND+T58n3f9MFEg==
.unpackedSize: 105.3 MB

dependencies:
@balena/dockerignore: ^1.0.2 fs-extra: ^9.0.1             jsonschema: ^1.4.0           punycode: ^2.1.1             yaml: 1.10.0
case: 1.6.3                  ignore: ^5.1.8               minimatch: ^3.0.4            semver: ^7.3.2

maintainers:
- aws-cdk-team <aws-cdk-dev@amazon.com>

dist-tags:
latest: 2.0.0-alpha.0      next: 2.0.0-alpha.4        preview-v2: 2.0.0-alpha.0
```

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
We've misjudged the tagging work here. We should probably drop 'next' here and just go back to using 'latest'.

**Comment by njlynch** [comment]
Really, using `latest` only makes sense for `aws-cdk-lib`; for all the others we publish (e.g., `@aws-cdk/cx-api`, `@aws-cdk/cloudformation-diff`) continuing with the existing strategy is probably ok.

Proposal:
1. Add a `npmdisttag` property to the `aws-cdk-lib` `package.json` with a value of `"latest"`.
2. Alter the NPM publishing job to use any `npmdisttag` value present as an override to the current disttag value.
3. Remove the `preview-v2` disttag from all published versions; the presence of this disttag is likely to cause confusion and provides no value.

Thoughts?

**Comment by eladb** [comment]
Sounds good. Bear in mind that npm already has support for specifying [`publishConfig`](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#publishconfig) but I think our publishers ignore it.

**Comment by nija-at** [comment]
Can we use the npmdisttag property in `package.json` across all of our v2 packages? Keep it consistent.

And drop this - https://github.com/aws/aws-cdk/blob/355fed870cf427afe1dbfadb05a854f040ef2680/release.json#L4 - in both branches.

**Comment by eladb** [comment]
We could, but then i would require this field in all package.json files to make sure we don't accidentally publish latest.
