### ISSUE TITLE
Implement DynamoDB as an event source in @aws-cdk/aws-lambda-event-sources

### ISSUE THREAD

**Issue by dchw** [aws/aws-cdk#1306]
This doesn't look like it would be too hard, but as per the contributing guidelines I am posting here first to see if this is something in the works.

Is there something like this in progress?

**Comment by rix0rrr** [comment]
There is not. You are very welcome to it :)

**Comment by eladb** [comment]
👍 that will be awesome

**Comment by ranguard** [comment]
This has been merged: https://github.com/awslabs/aws-cdk/pull/1563 but not released yet
