### ISSUE TITLE
acm: certificate import error

### ISSUE THREAD

**Issue by makr11** [aws/aws-cdk#13062]
Certificate import throws TypeError: Don't know how to convert object to JSON
Setup is pretty basic and I can get the certificate with the same arn with AWS CLI.

### Reproduction Steps

```
arn = "arn:aws:acm:us-east-1:.......:certificate/......."
certificate = cert_mngr.Certificate.from_certificate_arn(
    self, "Certificate",
    arn
)
```

### Environment

  - **CDK CLI Version  : 1.89.0
  - **Framework Version: 
  - **Node.js Version: v14.15.4
  - **OS               : Debian
  - **Language (Version): Python (3.8.7)

### Other

```
File "app.py", line 24, in <module>
    PortalStack(app, getenv("DEVELOPER"), env=env_local_dev)
  File "/mnt/c/Users/marin/project/.venv/lib/python3.8/site-packages/jsii/_runtime.py", line 83, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/mnt/c/Users/marin/project/project/portal_stack.py", line 15, in __init__
    certificate = cert_mngr.Certificate.from_certificate_arn(
  File "/mnt/c/Users/marin/project/.venv/lib/python3.8/site-packages/aws_cdk/aws_certificatemanager/__init__.py", line 1103, in from_certificate_arn
    return jsii.sinvoke(cls, "fromCertificateArn", [scope, id, certificate_arn])
  File "/mnt/c/Users/marin/project/.venv/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 126, in wrapped
    return _recursize_dereference(kernel, fn(kernel, *args, **kwargs))
  File "/mnt/c/Users/marin/project/.venv/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 349, in sinvoke
    response = self.provider.sinvoke(
  File "/mnt/c/Users/marin/project/.venv/lib/python3.8/site-packages/jsii/_kernel/providers/process.py", line 365, in sinvoke
    return self._process.send(request, InvokeResponse)
  File "/mnt/c/Users/marin/project/.venv/lib/python3.8/site-packages/jsii/_kernel/providers/process.py", line 314, in send
    data = json.dumps(req_dict, default=jdefault).encode("utf8")
  File "/usr/local/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/mnt/c/Users/marin/project/.venv/lib/python3.8/site-packages/jsii/_kernel/providers/process.py", line 155, in jdefault
    raise TypeError("Don't know how to convert object to JSON: %r" % obj)
TypeError: Don't know how to convert object to JSON: <project.portal_stack.PortalStack object at 0x7fdbb36a79a0>
```

--- 

This is :bug: Bug Report

**Comment by njlynch** [comment]
You left `**Framework Version**:` blank above. What version(s) of the CDK libraries do you have installed for this project (e.g., what's the output of `pip freeze`)? My best guess is that you have different versions of .core, .aws_certificatemanager, etc. installed.

**Comment by makr11** [comment]
pip freeze

aws-cdk.assets==1.89.0
aws-cdk.aws-apigateway==1.89.0
aws-cdk.aws-apigatewayv2==1.89.0
aws-cdk.aws-applicationautoscaling==1.89.0
aws-cdk.aws-autoscaling==1.89.0
aws-cdk.aws-autoscaling-common==1.89.0
aws-cdk.aws-autoscaling-hooktargets==1.89.0
aws-cdk.aws-batch==1.89.0
aws-cdk.aws-certificatemanager==1.89.0
aws-cdk.aws-cloudformation==1.89.0
aws-cdk.aws-cloudfront==1.89.0
aws-cdk.aws-cloudfront-origins==1.89.0
aws-cdk.aws-cloudtrail==1.89.0
aws-cdk.aws-cloudwatch==1.89.0
aws-cdk.aws-codebuild==1.89.0
aws-cdk.aws-codecommit==1.89.0
aws-cdk.aws-codedeploy==1.89.0
aws-cdk.aws-codeguruprofiler==1.89.0
aws-cdk.aws-codepipeline==1.89.0
aws-cdk.aws-codepipeline-actions==1.89.0
aws-cdk.aws-cognito==1.89.0
aws-cdk.aws-dynamodb==1.89.0
aws-cdk.aws-ec2==1.89.0
aws-cdk.aws-ecr==1.89.0
aws-cdk.aws-ecr-assets==1.89.0
aws-cdk.aws-ecs==1.89.0
aws-cdk.aws-efs==1.89.0
aws-cdk.aws-elasticloadbalancing==1.89.0
aws-cdk.aws-elasticloadbalancingv2==1.89.0
aws-cdk.aws-events==1.89.0
aws-cdk.aws-events-targets==1.89.0
aws-cdk.aws-iam==1.89.0
aws-cdk.aws-kinesis==1.89.0
aws-cdk.aws-kinesisfirehose==1.89.0
aws-cdk.aws-kms==1.89.0
aws-cdk.aws-lambda==1.89.0
aws-cdk.aws-lambda-nodejs==1.89.0
aws-cdk.aws-lambda-python==1.89.0
aws-cdk.aws-logs==1.89.0
aws-cdk.aws-route53==1.89.0
aws-cdk.aws-route53-targets==1.89.0
aws-cdk.aws-s3==1.89.0
aws-cdk.aws-s3-assets==1.89.0
aws-cdk.aws-sam==1.89.0
aws-cdk.aws-secretsmanager==1.89.0
aws-cdk.aws-servicecatalog==1.89.0
aws-cdk.aws-servicediscovery==1.89.0
aws-cdk.aws-sns==1.89.0
aws-cdk.aws-sns-subscriptions==1.89.0
aws-cdk.aws-sqs==1.89.0
aws-cdk.aws-ssm==1.89.0
aws-cdk.aws-stepfunctions==1.89.0
aws-cdk.cloud-assembly-schema==1.89.0
aws-cdk.core==1.89.0
aws-cdk.custom-resources==1.89.0
aws-cdk.cx-api==1.89.0
aws-cdk.pipelines==1.89.0
aws-cdk.region-info==1.89.0

cdk version 1.89.0 (build df7253c)

**Comment by njlynch** [comment]
Hmm.

Unfortunately, I can't reproduce. I'm using the same version of the CDK, same Node version. Is this reproducible in a small app, independent from your main app (with all of those other dependencies)?

**Comment by makr11** [comment]
Well, sorry for the trouble, it was my mistake.
But maybe for any future beginner with cdk..
Don't forget to set ++ super().__init__(scope, construct_id, **kwargs) ++
when you define new Stack class.
