### ISSUE TITLE
(typescript): Interface properties inheritance 

### ISSUE THREAD

**Issue by Haschikeks** [aws/aws-cdk#13083]
Hey,

I noticed, that some typescript interfaces only show their direct properties. For example the [LambdaIntegrationOptions](https://docs.aws.amazon.com/cdk/api/latest/typescript/api/aws-apigateway/lambdaintegrationoptions.html) only shows 2 properties. `allowTestInvoke` and `proxy`.

Checking with the general documentation [here](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-apigateway.LambdaIntegrationOptions.html) we can see, that it should have a lot more properties.

Having a look at the [source code](https://github.com/aws/aws-cdk/blob/v1.89.0/packages/@aws-cdk/aws-apigateway/lib/integrations/lambda.ts#L39) we can see that `LambdaIntegrationOptions` extends the `IntegrationOptions` interface. But the documentation is missing those properties from `IntegrationOptions` and also the information, that it extends something.

I guess the typescript documentation is automatically generated and doesn't account for inheritance.

---

This is a 📕 documentation issue

**Comment by Jerry-AWS** [comment]
I think this is @rix0rrr's bailiwick as it's about the API ref generation.
