### ISSUE TITLE
(sns): unsubscribe sqs from the sns topic will cause message delivery failure

### ISSUE THREAD

**Issue by jerrypeng7773** [aws/aws-cdk#13088]
We are using `topic.addSubscription(new SqsSubscription(queue))` API to subscribe a queue to a topic, there will be a SQS policy as well as the subscription be created. However, when we delete this line, i.e. unsubscribe, looks like the CFN will try to delete both policy and the subscription at the meanwhile, since there is no dependency between the SQSPolicy and the SNSSubscritpion. Thus, we get message delivery failure alarms, and by checking the delivery status log, the error is due to AccessDenied. This indicates that the policy gets deleted before the subscription, so there are on-fly messages cant gets delivered successfully.

### Reproduction Steps

`topic.addSubscription(new SqsSubscription(queue))` do CFN deployment, and then delete it, and redo deployment.

### What did you expect to happen?

The policy gets deleted after the subscription.

### What actually happened?

The policy gets deleted before the subscription. causing `"providerResponse": "{\"ErrorCode\":\"AccessDenied\",\"ErrorMessage\":\"Access to the resource https://sqs.us-west-2.amazonaws.com/xxxx/xxxx is denied.\",\"sqsRequestId\":\"Unrecoverable\"}"`

### Environment

  - **CDK CLI Version  : 1.73
  - **Framework Version: 1.69.0
  - **Node.js Version:v12.16.3   
  - **OS     linux          :MAC OS
  - **Language (Version):TS 

### Other

--- 

This is :bug: Bug Report

**Comment by MrArnoldPalmer** [comment]
This one's interesting. I'm not sure there is much we can do from the CDK side as the order create/deletes is handled by CFN. Though I'm curious if we can devise a workaround somehow. The deployment actually completes successfully right? just during some period of time in the middle of deploying the stack changes message deliveries fail?

**Comment by jerrypeng7773** [comment]
this is correct, policy should be deleted after the subscriber queue is gone, looks like there should be a default dependency between the SQS policy and the queue.

**Comment by MrArnoldPalmer** [comment]
Yeah creating an explicit dependency here might be the solution. Are you able to test this by creating the dependency using [escape hatches](https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html) to access the L1s and call [`addDependsOn`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.CfnResource.html#addwbrdependswbrontarget) manually?

**Comment by jerrypeng7773** [comment]
can you give me an example about letting a `SqsSubscription` depends on a sqs resource policy ? 

I have those resources created already, if using Cfn to re-create them again, then the deletion of the old resources might trigger the delivery failure alarm again.

**Comment by MrArnoldPalmer** [comment]
Ahh you can't actually do it in the way I was thinking. Because this policy is added to the sqs queue resource via [`queue.addToResourcePolicy`](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-sns-subscriptions/lib/sqs.ts#L44), there is nothing to depend on. I'm not sure if there is a good solution to this on the CDK, or even on the CFN side. There is no way to tell CFN that a particular statement inside the queue resource policy is linked to a specific subscription, and needs to stay until the subscription is gone. This will require some investigation.

For now, anyone who needs to work around this can add the policy to the resource manually when you're deleting the subscription. Then after you deploy the change removing the subscription, remove the policy as well.
```typescript
    queue.addToResourcePolicy(new iam.PolicyStatement({
      resources: [queue.queueArn],
      actions: ['sqs:SendMessage'],
      principals: [new iam.ServicePrincipal('sns.amazonaws.com')],
      conditions: {
        ArnEquals: { 'aws:SourceArn': topic.topicArn },
      },
    }));
```

**Comment by jerrypeng7773** [comment]
thanks, yep, thats what I did.
