### ISSUE TITLE
(eks): Kubernetes 1.19 support

### ISSUE THREAD

**Issue by pahud** [aws/aws-cdk#13093]
Allow user to select Kubernetes version 1.19

https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-1.19

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by guan840912** [comment]
so fast 👍
