### ISSUE TITLE
(aws-batch): Internal failure when deploying compute environment after upgrading to 1.89.0

### ISSUE THREAD

**Issue by l0b0** [aws/aws-cdk#13091]
After [upgrading CDK from 1.71 to 1.89](https://github.com/linz/geospatial-data-lake/commit/19d45cd81f23ec1833b4ac455b635ce46f4c8e4e) deployments of [this project](https://github.com/linz/geospatial-data-lake) have been [consistently failing](https://github.com/linz/geospatial-data-lake/actions?query=workflow%3ADeploy) with an "internal failure" message.

### Reproduction Steps

Deploy the master branch of [this project](https://github.com/linz/geospatial-data-lake/).

### What did you expect to happen?

The deployment should work like before.

### What actually happened?

Consistent update failure of a compute environment, leading to cancellation of the CI pipeline.

### Environment

  - **CDK CLI Version  :** 1.89.0
  - **Framework Version:** Unknown (Which framework?)
  - **Node.js Version:** v14.15.1
  - **OS               :** Arch Linux
  - **Language (Version):** Python (3.8.6)

### Other

From a [deployment log](https://github.com/linz/geospatial-data-lake/runs/1884273548):

```text
  2/14 | 2:20:38 AM | UPDATE_FAILED        | AWS::Batch::ComputeEnvironment   | processing/batch_job_queue/compute-environment (batchjobqueuecomputeenvironment37F33E59) Internal Failure
	new ComputeEnvironment (/tmp/jsii-kernel-qteva9/node_modules/@aws-cdk/aws-batch/lib/compute-environment.js:81:36)
	\_ /tmp/tmpm0hf4k_u/lib/program.js:2700:58
	\_ Kernel._wrapSandboxCode (/tmp/tmpm0hf4k_u/lib/program.js:3128:24)
	\_ Kernel._create (/tmp/tmpm0hf4k_u/lib/program.js:2700:34)
	\_ Kernel.create (/tmp/tmpm0hf4k_u/lib/program.js:2441:29)
	\_ KernelHost.processRequest (/tmp/tmpm0hf4k_u/lib/program.js:9437:36)
	\_ KernelHost.run (/tmp/tmpm0hf4k_u/lib/program.js:9400:22)
	\_ Immediate._onImmediate (/tmp/tmpm0hf4k_u/lib/program.js:9401:46)
	\_ processImmediate (internal/timers.js:461:21)
```

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment]
@l0b0 Can you please provide minimal reproduction code? Its hard to navigate through the project you referenced as its quite large. 

Would be good if you can extract the relevant code.  

Thanks

**Comment by l0b0** [comment]
I've worked around the issue by tearing down the environment and redeploying it just a few hours ago. Since I'm able to deploy from scratch we can probably close this as an incompatibility between CDK 1.71 and 1.89.
