### ISSUE TITLE
(aws-events-targets): AwsApi service should toUppercase and better error message if not found

### ISSUE THREAD

**Issue by ahammond** [aws/aws-cdk#13090]
### Reproduction Steps

```
    const taskTarget = new eventsTargets.AwsApi({
      service: 'dms',
      action: 'startReplicationTask',
      parameters: {
        ReplicationTaskArn: task.ref,
        StartReplicationTaskType: 'reload-target',
      },
    });

    const clockRuleName = new core.Namer(['clock', 'rule']);
    const clockRule = new events.Rule(this, clockRuleName.pascal, {
      schedule: events.Schedule.cron({ minute: '0', hour: '0/2' }),
      targets: [taskTarget],
    });
```

### What did you expect to happen?

The rule should trigger a lambda which starts a DMS task.

### What actually happened?

```
2021-02-16T20:00:10.450Z	9014fe65-c8be-4703-ab32-36e79dd062fa	ERROR	Invoke Error 	
{
    "errorType": "TypeError",
    "errorMessage": "AWS[event.service] is not a constructor",
    "stack": [
        "TypeError: AWS[event.service] is not a constructor",
        "    at Runtime.handler (/var/task/index.js:10:24)",
        "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"
    ]
}
```

The actual error is that I should be passing

```
      service: 'DMS',
```

I think that the passed `service` should be `.toUppercase()`'d and that if it's not found, the resulting error message should provide better guidance.

### Environment

  - **CDK CLI Version  :** 1.89.0
  - **Framework Version:** 1.89.0
  - **Node.js Version:** v14.3.0
  - **OS               :** MacOS
  - **Language (Version):** TypeScript (4.1.5)

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
I agree, that sounds like a good idea.

I wonder if we could pull this validation to synth-time, even...

**Comment by mprencipe** [comment]
I'd like to work on this issue. Is there any way to check if the service (and maybe the action) is available during synth?

**Comment by rix0rrr** [comment]
I am not sure :) but I imagine there is. You'll see it when you look at the code I suppose.

**Comment by ahammond** [comment]
@mprencipe detection at synth would be awesome.

**Comment by ahammond** [comment]
The aws-sdk library is probably already available, you could probably grope around in there?

**Comment by mprencipe** [comment]
Yep, got it.
