### ISSUE TITLE
CDK cli configuration

### ISSUE THREAD

**Issue by usmanbinnaeem** [aws/aws-cdk#13095]
Hi, Hope You all are doing well, need little help, I have created my IAM user and configured every thing fine, but still getting this error, "Unable to resolve AWS account to use. It must be either configured when you define your CDK or through the environment" any body can help to know what I am doing wrong.

here is my .aws/config and .aws/credentials files
.aws/credentials : 

[default]
aws_access_key_id=AKIAZGKxxxxxxxxxxx
aws_secret_access_key=aK83fP4v7Lmsly8Yxxxxxxxxxxxxx

.aws/config: 

[default]
region=us-east-1

Regards: usman Naeem.

**Comment by GeoSnipes** [comment]
May be similar to what I had.

Instead of "aws configure" do "aws configure --profile <give a profile name>"
Then when running the cdk do: "cdk --profile <profile name entered above>"

**Comment by usmanbinnaeem** [comment]
@GeoSnipes  Thanks buddy, now its resolved I've been facing this error for the last one month
