### ISSUE TITLE
cdk.Arn.format: adds region automatically for services not requiring one

### ISSUE THREAD

**Issue by mpuhacz** [aws/aws-cdk#13104]
### Reproduction Steps

```ts
cdk.Arn.format({ service: "iam", resource: "role", resourceName: "*" }, this.props.serviceStack),
```

### What did you expect to happen?

I expect Arn `format` method to skip region for services like IAM

### What actually happened?

```
 0/3 | 10:47:56 AM | UPDATE_FAILED        | AWS::IAM::Policy                             | Pipeline/Pipeline/Integration/IntegrationCloudTest/Project/Role/DefaultPolicy (PipelineIntegrationIntegrationCloudTestProjectRoleDefaultPolicyCA2B5C47) IAM resource arn:aws:iam:us-east-1:1111111111111:role/* cannot contain region information. (Service: AmazonIdentityManagement; Status Code: 400; Error Code: MalformedPolicyDocument; 
```

### Environment

  - **CDK CLI Version :** 1.89.0
  - **Framework Version:** 1.89.0
  - **Node.js Version:** v14.14.0
  - **OS               :** OS X
  - **Language (Version):** ts-node v9.1.1

### Other

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
Yeah. It doesn't have that knowledge though, and it's not a great place to encode that.

If you know you need to have no region, pass in `region: ''`.
