### ISSUE TITLE
📊Tracking: Cognito Identity Pools

### ISSUE THREAD

**Issue by nija-at** [aws/aws-cdk#13102]
Add your +1 👍  to help us prioritize high-level constructs for this service
--- 

### Overview:

[AWS Docs](https://docs.aws.amazon.com/cognito/latest/developerguide/identity-pools.html)  

### Maturity: CloudFormation Resources Only

See the [AWS Construct Library Module Lifecycle doc](https://github.com/aws/aws-cdk-rfcs/blob/master/text/0107-construct-library-module-lifecycle.md) for more information about maturity levels.

### Issue list:

--- 
This is a  📊Tracking Issue

**Comment by cyuste** [comment]
I'd love to help developing this feature

**Comment by CaerusKaru** [comment]
Is this a duplicate of #8630?

**Comment by nija-at** [comment]
oh god yes. Not sure how I missed that. Thanks @CaerusKaru.
