### ISSUE TITLE
(pipelines): EnableKeyRotation

### ISSUE THREAD

**Issue by jaidisido** [aws/aws-cdk#13113]
As part of my CDK Pipeline definition, I have specified that the CloudFormation template synthesized by CDK must be checked for security issues with cfn_nag:

```python
  synth_action=pipelines.SimpleSynthAction(
      source_artifact=source_artifact,
      cloud_assembly_artifact=cloud_assembly_artifact,
      install_command="npm install -g aws-cdk && gem install cfn-nag && pip install -r requirements.txt",
      synth_command="cdk synth && fname=$(find ./cdk.out/*.template.json) && cfn_nag_scan --input-path $fname",
  ),
```
This returned a FAIL indicating that KMS key rotation should be enabled:
<img width="618" alt="Screenshot 2021-02-17 at 14 49 25" src="https://user-images.githubusercontent.com/16362107/108221220-74af9e00-712f-11eb-827a-13506410efc5.png">

### Use Case
Being able to run CFN nag on the pipelines CDK module without receiving a FAIL

### Proposed Solution

EnableKeyRotation within the module or expose KMS options

### Other

Beyond this use case, it would be great if CDK synthesized modules (with sane defaults) pass basic CFN nag checks

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

**Comment by rix0rrr** [comment]
You can write an Aspect to turn on key rotation.

**Comment by jaidisido** [comment]
Thanks @rix0rrr

For anyone wondering how to workaround this in Python:
```
 # CDK Pipelines does not enable KMS key rotation by default
 cfn_pipeline_bucket_key = (
     pipeline.code_pipeline.artifact_bucket.encryption_key.node.default_child  # type: ignore
 )
 cfn_pipeline_bucket_key.enable_key_rotation = True  # type: ignore
```
