### ISSUE TITLE
(aws-cdk-lib): module core does not exist

### ISSUE THREAD

**Issue by rectalogic** [aws/aws-cdk#13118]
"classic import" example does not work, `core` is not defined
https://pypi.org/project/aws-cdk-lib/

### Reproduction Steps
```python
$ pip install aws-cdk-lib
$ python
Python 3.8.6 (default, Sep 28 2020, 04:41:02)
[Clang 11.0.3 (clang-1103.0.32.62)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from aws_cdk_lib import core, aws_s3 as s3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'core' from 'aws_cdk_lib' (/.../env/lib/python3.8/site-packages/aws_cdk_lib/__init__.py)
```

### What did you expect to happen?
`core` should be exported from `aws_cdk_lib/__init__.py`

### Environment

  - **CDK CLI Version  :** 2.0.0a4
  - **Framework Version:**
  - **Node.js Version:** v14.15.0
  - **OS               :** macOS 10.15.7
  - **Language (Version):** python 3.8.6

### Other

Add `core = sys.modules[__name__]` to `aws_cdk_lib/__init__.py`?

**Comment by NetaNir** [comment]
Note that `aws-cdk-lib` is experimental and only exist in v1 to allow easy code migration to CDK v2 (currently in alpha), I would highly discourage you from using it.

having said that, `core` does not exist in `aws-cdk-lib` all types from core were hoisted to the root of `aws-cdk-lib`.
