### ISSUE TITLE
(iam):  validation for identity based policy occurs even if it is not identity-based

### ISSUE THREAD

**Issue by ap00rv** [aws/aws-cdk#13123]
CDK checks whether policy is identity based by running length check on `Users`, `Groups`, or `Role` properties of `Policy` construct 

https://github.com/aws/aws-cdk/blob/33339e1c5f3ac280018e294c268c68929707dcce/packages/%40aws-cdk/aws-iam/lib/policy.ts#L257-L259

However, when documents in a policy are validated, it is not checked if the policy is identity-based . 

https://github.com/aws/aws-cdk/blob/33339e1c5f3ac280018e294c268c68929707dcce/packages/%40aws-cdk/aws-iam/lib/policy.ts#L248-L250

### Reproduction Steps

```
const statements = [new PolicyStatement({
        actions: ["execute-api:Invoke"],
        effect: Effect.ALLOW,
        principals: [new AccountPrincipal(99999999)],
        resources: [
          "arn:aws:execute-api:*:*:*/*/POST/GetProfileWithFilter",
        ],
      })];


const sp = new Policy(this, "ApiGatewayResourcePolicy", {statements});
```

### What did you expect to happen?

Policy is created without any errors. 

### What actually happened?

received error

```
Error: Validation failed with the following errors:
  [CdkGettingStartedStack3/ApiGatewayResourcePolicy] A PolicyStatement used in an identity-based policy cannot specify any IAM principals.
```

### Environment

  - **CDK CLI Version  : *1.74.0*
  - **Framework Version:**
  - **Node.js Version:*14.1.0* 
  - **OS               :*Amazon Linux 2*
  - **Language (Version):*TypeScript (4.1.3)* 

### Other

Stack trace: 
```
Error: Validation failed with the following errors:
  [CdkGettingStartedStack3/ApiGatewayResourcePolicy] A PolicyStatement used in an identity-based policy cannot specify any IAM principals.
    at validateTree (/src/cdk-demo/node_modules/monocdk/lib/core/lib/private/synthesis.ts:164:15)
    at Object.synthesize (/src/cdk-demo/node_modules/monocdk/lib/core/lib/private/synthesis.ts:22:9)
    at App.synth (/src/cdk-demo/node_modules/monocdk/lib/core/lib/stage.ts:168:29)
    at process.<anonymous> (/src/cdk-demo/node_modules/monocdk/lib/core/lib/app.ts:109:51)
    at Object.onceWrapper (events.js:422:26)
    at process.emit (events.js:315:20)
    at process.EventEmitter.emit (domain.js:483:12)
    at process.emit (/src/cdk-demo/node_modules/source-map-support/source-map-support.js:495:21)
Command failed: /src/cdk-demo/node_modules/.bin/ts-node bin/cdk_getting_started.ts
```

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
An `iam.Policy` is always an identity policy, so this error makes sense.

Discussed offline, you were only using `iam.Policy` as a vessel to hold a `PolicyDocument`, which would then be used as a resource policy later on. Use `PolicyDocument` directly instead of creating an `iam.Policy`.
