### ISSUE TITLE
[aws-codepipeline-actions] Cannot assume role by code pipeline on code pipeline action AWS CDK

### ISSUE THREAD

**Issue by JohnSimerlink** [aws/aws-cdk#13139]
When I try to create a codepipeline with two actions via cdk I get a $PIPELINE_ROLE cannot assume $PIPELINE_ACTION_ROLE error.

### The Question
I have a Cdk stack with the following code:
![image](https://user-images.githubusercontent.com/4733612/108417223-b27af800-71fd-11eb-9552-87513093efd5.png)
![image](https://user-images.githubusercontent.com/4733612/108417181-a2fbaf00-71fd-11eb-9dbe-9bd3ef8bfebe.png)

Running `cdk deploy` on it generates the following error:
![](https://i.imgur.com/YdgEtQk.png)

This seems to be inconsistent with the shown permissions in the AWS Console:

If you comment out lines 73 - 104, in cdk_error_stack.py, `cdk synth` will successfully deploy, upon which you can inspect the roles in the AWS IAM Console. Doing so, shows the following trust relationships for pipeline_action_role.
![](https://i.imgur.com/ZV7XYrw.png)

Clicking on "Edit Trust Relationship" Shows the following JSON for the trust relationship
![](https://i.imgur.com/1einnaY.png)

This reflects the explicit assume role policy set up on line 49
![](https://i.imgur.com/PZfJARs.png)

The reason I am manually specifying roles on lines 78, 88, 99 is because I was also getting an assumeRole error if I used the roles implicitly created in the `codepipepline.Pipeline` and `codepipeline.StageProps` constructs.

How can I get rid of the Not Authorized to Perform AssumeRole Error upon `cdk deploy`?

The below related issues/questions on the internet do not appear to be the same question I have:
- [aws pipeline role is not authorized to perform AssumeRole on cross account role](https://stackoverflow.com/questions/60958114/aws-pipeline-role-is-not-authorized-to-perform-assumerole-on-cross-account-role)
- [[aws-codepipeline-actions] Cannot assume role by code pipeline on code pipeline action AWS CDK #10068](https://github.com/aws/aws-cdk/issues/10068)

Manually creating the roles with their trust policies first, and then referencing them via ARN inside of CDK to set up the codepipeline also throws the same error.

### Environment

  - CDK CLI Version: 1.85.0 (build 5f44668)
  - Module Version: 1.85.0
  - Node.js Version: 10.19.0
  - OS: MacOS Catalina 10.15.2 (19C57)
  - Language (Version: Python: 3.8.6)

### Other information
[Here is my repo](https://github.com/JohnSimerlink/cdk-error) which contains the full code that is generating the error for me.

**Comment by skinny85** [comment]
Hey @JohnSimerlink ,

thanks for opening the issue.

As a first step, you're freezing the version of the `aws-cdk.core` package to `1.85.0` [here](https://github.com/JohnSimerlink/cdk-error/blob/f2d1941268ebc41bbb8d6353b1e04b4e615e69f1/setup.py#L22-L22), but use latest for the other packages, which doesn't make sense.

Either freeze all of them, or use 'latest' for all of them.

Thanks,
Adam

**Comment by JohnSimerlink** [comment]
Thanks @skinny85 , I changed it to use latest for all packages.

You can try out my latest code with `git checkout tags/v2` on my [repo](https://github.com/JohnSimerlink/cdk-error/tree/john-withIamOnRole). I still receive the same error.

**Comment by JohnSimerlink** [comment]
The issue was that our AWS account had an SCP policy blocking sts, as it wasn't on a whitelist our IT used to determine for HIPAA complaince.
