### ISSUE TITLE
external API gateway (v1) not triggering new deployment

### ISSUE THREAD

**Issue by s-dschro** [aws/aws-cdk#13134]
Hey guys,

do you know why an external API gateway (V1) is not triggering new deployments automatically when resources/methods/etc. change? Especially/Even when the `deploy` property is set to `true`?

https://stackoverflow.com/questions/63950199/how-to-use-an-existing-stage-in-api-gateway-deployments-in-aws-cdk/

I can only work around when creating a new deployment with a unique logical ID:

```
const api = apigateway.RestApi.fromRestApiAttributes(this, apiId, {
  restApiId: cdk.Fn.importValue(apiId),
  rootResourceId: cdk.Fn.importValue(resourceId),
});

// Add new resources and methods here ...
    
const deployment = new apigateway.Deployment(this, `${uuid()}-apigateway-deployment`, {
  api,
});
```
But this way I cannot destroy the stack anymore, because every time (when deploying/destroying) a new ID is created ...

Thanks in advance!

Unfortunately, just changing the `description` property did not work. xD

```
const deployment = new apigateway.Deployment(this, `apigateway-deployment`, {
  api,
  description: uuid(),
});
```

**Comment by nija-at** [comment]
This is currently unsupported. We're tracking this here - https://github.com/aws/aws-cdk/issues/12417
