### ISSUE TITLE
Support all Step Function task resources

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#1314]
At the moment, step functions only support Lambda and `Action`, it would be awesome to add support for the rest of the resources as described here: https://docs.aws.amazon.com/step-functions/latest/dg/connectors-supported-services.html:

Namely:

- [ ] AWS Batch
- [ ] Amazon DynamoDB
- [x] Amazon ECS/Fargate
- [x] Amazon SNS
- [x] Amazon SQS
- [ ] AWS Glue
- [x] Amazon SageMaker

**Comment by 0xdevalias** [comment]
Curious if there is any known ETA/vague roadmap on this? In particular, interested in AWS batch (for this project), and ECS/Fargate (for future projects)

**Comment by eladb** [comment]
See #1646 #1275

**Comment by ymwdalex** [comment]
I am curious when glue job can be supported here?

**Comment by dmoser04** [comment]
Support for Glue jobs would also be highly appreciated from my side!

**Comment by rix0rrr** [comment]
This is open for contribution. We are not currently working on this.

**Comment by andrewrobertmadsen** [comment]
Support for batch would be super helpful to our team.

**Comment by abdullahodibat** [comment]
Also for me there is a need for Batch Support. is it going to be implemented soon?

**Comment by ayush987goyal** [comment]
Hi, I have created a PR for adding Batch Support #6396

**Comment by nija-at** [comment]
In an effort to break this further and track implementation of each separately, and, to track the +1s better, I've created separate tasks for the remaining items here -

* AWS Batch - https://github.com/aws/aws-cdk/issues/6467
* DynamoDB - https://github.com/aws/aws-cdk/issues/6468
* AWS Glue - https://github.com/aws/aws-cdk/issues/6469

If you're still waiting for any of these, kindly transfer your +1s to these separate issues. Thanks in advance!
