### ISSUE TITLE
(ec2): Update default AmazonLinuxImage to use AMAZON_LINUX_2

### ISSUE THREAD

**Issue by scottnixonjr** [aws/aws-cdk#13164]
## Breaking Change feature/request. 

The `ec2.AmazonLinuxImage` defaults to using the latest Amazon Linux image which reached end-of-life at the end of 2020. I'd suggest updating the default image to `ec2.AmazonLinuxGeneration.AMAZON_LINUX_2`

### Environment

  - **CDK CLI Version:** 1.90.0 (build 7edba31)
  - **Module Version:** 1.90.1
  - **Node.js Version:** v15.9.0
  - **OS:**  macOS Big Sur 11.2.1
  - **Language (Version):** typescript 4.1.5

**Comment by hoegertn** [comment]
This would be a breaking change in CDK 1.x but I would love to see this in CDK 2.x as this change could be done then.

**Comment by rix0rrr** [comment]
That sounds like a plan. If we're going to make this change though, it can't be in a mad PR dash just before v2 gets released.

The way to do that in a controlled fashion is to add a feature flag which flips the default. We can then change the flag's default value for v2.

**Comment by nija-at** [comment]
The feature flag mechanism is a good way to achieve this. Adding it to the [`FEATURE_FLAGS_EXPIRED` list on the `v2-main` branch](https://github.com/aws/aws-cdk/blob/v2-main/packages/%40aws-cdk/cx-api/lib/features.ts#L138) is the way to go. I've captured this here - https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md#cdkv2.

The only diff between the two branches would be the docs where the the `@default` is documented differently.

Anything else we should consider @rix0rrr ?

**Comment by scottnixonjr** [comment]
Thanks for priorizing this change! 

I did notice a number of other related issues that I figured I'd mention. Using Amazon Linux 2 image seemed to break ec2.InitService which I discovered was because v2 uses systemd, and v1 uses init.d. Other ec2.Init classes seem to be effected as well but I don't have details I can provide without more tinkering.
