### ISSUE TITLE
(aws-lambda-nodejs): does not properly detect `esbuild` when used with Yarn 2+ in PnP mode

### ISSUE THREAD

**Issue by andreialecu** [aws/aws-cdk#13179]
`aws-cdk` in general works properly with yarn 2+ in Plug'n'Play (PnP) mode. See https://yarnpkg.com/features/pnp

PnP mode does not use `node_modules` and thus `npx` cannot detect that `esbuild` is installed in the project, so this block of code fails:

https://github.com/aws/aws-cdk/blob/8f1cfe4087b765cecd3ceb01745167646d617fec/packages/%40aws-cdk/aws-lambda-nodejs/lib/util.ts#L115-L130

Also this block of code is problematic as well since it also uses `npx`:
https://github.com/aws/aws-cdk/blob/8f1cfe4087b765cecd3ceb01745167646d617fec/packages/%40aws-cdk/aws-lambda-nodejs/lib/bundling.ts#L141-L158

Overall, spawning `esbuild` via its CLI seems far less than ideal. Instead, it should probably be executed via its nodejs api:

Example: 

```js
require('esbuild').buildSync({
  entryPoints: ['in.ts'],
  outfile: 'out.js',
})
```

Getting the installed version would be as easy as: `require('esbuild/package.json').version`

### Reproduction Steps

```
mkdir test
yarn init -2
...set up cdk project...
yarn add esbuild

yarn cdk deploy '*'
```

Prints: `esbuild cannot run locally. Switching to Docker bundling.`

A workaround is possible by installing `esbuild` globally, but this is far from ideal.

### What did you expect to happen?

`esbuild` should work properly

### What actually happened?

`esbuild cannot run locally. Switching to Docker bundling.`

### Environment

  - **CDK CLI Version  :** 1.90.1
  - **Framework Version:** 1.90.1
  - **Node.js Version:** 15.9.0
  - **OS               :** macOS
  - **Language (Version):** TypeScript 4.0.5

### Other

Originally added in https://github.com/aws/aws-cdk/pull/11289 by @jogold 

--- 

This is :bug: Bug Report

**Comment by andreialecu** [comment]
One other important things would be to add `esbuild` as a `peerDependency`:

https://github.com/aws/aws-cdk/blob/8f1cfe4087b765cecd3ceb01745167646d617fec/packages/%40aws-cdk/aws-lambda-nodejs/package.json#L79-L82

**Comment by jogold** [comment]
Hi @andreialecu 

Thanks for the feedback.

Because the CDK uses [`jsii`](https://github.com/aws/jsii) and the CDK team doesn't currently want to bundle `esbuild` in the CDK we cannot use the Node.js API or declare `esbuild` as a peer dependency unfortunately.

We can however improve detection with Yarn v2. We could do `yarn run esbuild --version` when working with a `yarn.lock`. A similar approach can be used to run the `esbuild` CLI.

**Comment by andreialecu** [comment]
@jogold `yarn run esbuild` would indeed work for `yarn`, but it still wouldn't really work for `pnpm` for example. `pnpm` also supports the `PnP` installation mechanism: https://pnpm.js.org/blog/2020/10/17/node-modules-configuration-options-with-pnpm#plugnplay-the-strictest-configuration

Regarding peer dependencies, `esbuild` could be added as an optional peer dependency:

All package managers support optional peer dependencies:

https://docs.npmjs.com/cli/v7/configuring-npm/package-json#peerdependenciesmeta
https://yarnpkg.com/configuration/manifest#peerDependenciesMeta
https://pnpm.js.org/en/package_json#peerdependenciesmeta

Calling `esbuild` via its api would fully abstract this and make it package manager independent, meaning it should work with `pnpm` as well.

**Comment by jogold** [comment]
> it still wouldn't really work for pnpm for example

No too familiar with `pnpm` but will have a look.

> All package managers support optional peer dependencies:

Of course but with `jsii` you can only include a module as a peer dependency if it's `jsii-enabled`. Otherwise you need to add it as a bundled dependency (which is what the CDK team doesn't want for the moment).

**Comment by andreialecu** [comment]
> Of course but with jsii you can only include a module as a peer dependency if it's jsii-enabled. Otherwise you need to add it as a bundled dependency (which is what the CDK team doesn't want for the moment).

Interesting. Could you kindly point to a link that describes what the actual limitation is here, out of curiosity? I'd like to do some reading on this.

Is it a hardcoded limitation in jsii?

The way it could work in a normal program would be to:

```js
try {
  require("esbuild");
  // esbuild is installed locally
} catch (err) {
  // esbuild not installed locally, try with `npx` here
}
```

I'm not sure why this would cause problems for `jsii` unless it enforces a hard constraint on peer deps.

**Comment by andreialecu** [comment]
I guess this might be related, though it doesn't go into specifics:

https://github.com/aws/jsii/issues/1137

Anyways: 

> We can however improve detection with Yarn v2. We could do yarn run esbuild --version when working with a yarn.lock. A similar approach can be used to run the esbuild CLI.

This would be a good workaround for now.

**Comment by jogold** [comment]
> I guess this might be related, though it doesn't go into specifics:

Not a `jsii` specialist but yes for now `jsii` cannot handle peer deps that are not also deps or bundled deps.

Trying to fix your issue in #13257, feel free to review it!

**Comment by hirenumradia** [comment]
Are there any workarounds for this issue? I have installed `esbuild` globally but it still doesn't work. I can't build any functions at the moment.

**Comment by andreialecu** [comment]
@hirenumradia what is the error or behavior you're seeing?

**Comment by hirenumradia** [comment]
When running `cdk synth` I get the following error using NodeJsFunction on my Macbook. 

`Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
Bundling asset BackendStack/example_ms/example-lambda/Code/Stage...
esbuild cannot run locally. Switching to Docker bundling.`

My Docker bundling is not working so I have been relying on the `esbuild`. I have installed `esbuild` globally and am using yarn v2 inside the project.

If I run the project on my windows machine using WSL2, CDK commands run fine.

**Comment by andreialecu** [comment]
Did you run `npm install -g esbuild`? Esbuild needs to be installed using npm (not yarn) for the workaround to work.

**Comment by hirenumradia** [comment]
@andreialecu Yeah I just tried it again and run that same command `npm install -g esbuild`

**Comment by hirenumradia** [comment]
@andreialecu update on this, I found my issue. I was using the local cdk cli which I was running via a yarn script called `cdk` which was `yarn cdk deploy`. I guess it looks for a local version of esbuild in that case even if there is one available globally. By running the command `cdk deploy`, I was able to work around this issue.

**Comment by andreialecu** [comment]
I'm running it via `yarn cdk deploy` personally and everything works fine. You could try troubleshooting the cdk source and check why it fails to find esbuild.

**Comment by hirenumradia** [comment]
@andreialecu sure will give that a go and report back.

**Comment by titanjer** [comment]
Just report I got `error Command "esbuild" not found.` under yarn v1.22.10 and cdk 1.106.1 (build c832c1b)

**Comment by jogold** [comment]
> Just report I got `error Command "esbuild" not found.` under yarn v1.22.10 and cdk 1.106.1 (build [c832c1b](https://github.com/aws/aws-cdk/commit/c832c1bf68d528c347cbe52a67cd7c0824d33d64))

Can you open an issue with more details? I'm not able to reproduce this with cdk 1.106.1 and yarn 1.22.10.

**Comment by corrjo** [comment]
We are getting the same issue as @titanjer 

Error message:
```
Bundling asset ClientVPN/client-vpn-idp/IdpCreator/Code/Stage...
yarn run v1.22.10
warning ../../../package.json: No license field
error Command "esbuild" not found.
```

These are the relevant package.json and yarn.lock files.
https://gist.github.com/corrjo/e73f4c8db6b29fb613b7039e5e94c9e8

pretty straight forward use of  NodejsFunction
```
    const idpCreatorLambda = new nodelambda.NodejsFunction(this, 'IdpCreator', {
      bundling: {
        nodeModules: ['axios'],
      },
      timeout: cdk.Duration.minutes(1),
      handler: 'handler',
    });
````

**Comment by ahammond** [comment]
Same issue with `error Command " esbuild not found.` while using a `NodejsFunction()`.

**Comment by ahammond** [comment]
I suspect that using projen got us yarn 2 with PnP which is what's breaking us.

**Comment by jogold** [comment]
> We are getting the same issue as @titanjer
> 
> Error message:
> 
> ```
> Bundling asset ClientVPN/client-vpn-idp/IdpCreator/Code/Stage...
> yarn run v1.22.10
> warning ../../../package.json: No license field
> error Command "esbuild" not found.
> ```
> 
> These are the relevant package.json and yarn.lock files.
> https://gist.github.com/corrjo/e73f4c8db6b29fb613b7039e5e94c9e8
> 
> pretty straight forward use of NodejsFunction
> 
> ```
>     const idpCreatorLambda = new nodelambda.NodejsFunction(this, 'IdpCreator', {
>       bundling: {
>         nodeModules: ['axios'],
>       },
>       timeout: cdk.Duration.minutes(1),
>       handler: 'handler',
>     });
> ```

Can you share a minimal repro in a new issue?

**Comment by jogold** [comment]
OK found the problem, will fix it.

Only happens when consuming a node module that uses a `NodejsFunction`.

**Comment by jogold** [comment]
#14914

**Comment by corrjo** [comment]
> #14914

🙏🏼

**Comment by phuctm97** [comment]
Just got esbuild not found when using with pnpm workspace, any workaround?

**Comment by denistsyplakov** [comment]
Is it still non fixed? Have this issue with latest CDK for NodejsFunction

**Comment by blanchma** [comment]
Same here. 

`Bundling asset SodEtlStack/RollbarNotifierLambda/Code/Stage...
yarn run v1.22.18
warning ../../package.json: No license field
error Command "esbuild" not found.`

`cdk --version
2.139.0 (build 2699ffd)`

`node --version
v18.19.1`

**Comment by yuki-yamamura** [comment]
I got `error Command "esbuild" not found.` with pnpm in CI, and just added `npm install -g esbuild` before `cdk sync` is executed for a workaround.

https://github.com/aws/aws-cdk/issues/13179#issuecomment-841726148
