### ISSUE TITLE
(aws-appsync): grant data api access to rds data source

### ISSUE THREAD

**Issue by MrArnoldPalmer** [aws/aws-cdk#13189]
### Use Case

Currently, user's need to manually grant access to the RDS serverless cluster data api to their appsync data source that uses it. This can be done when calling `addRdsDataSource` on the passed in `IServerlessCluster` using [`grantDataApiAccess`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-rds.IServerlessCluster.html#grantwbrdatawbrapiwbraccessgranteespan-classapi-icon-api-icon-experimental-titlethis-api-element-is-experimental-it-may-change-without-noticespan)

### Proposed Solution

Call `grantDataApiAccess` on the data source in the body of `GraphQLApi.addRdsDataSource`.

---

This is a :rocket: Feature Request

**Comment by BryanPan342** [comment]
Currently we are already doing this 

https://github.com/aws/aws-cdk/blob/bf16642482a9264eda0a4866b5372580744fad94/packages/%40aws-cdk/aws-appsync/lib/data-source.ts#L351-L364

When I looked into the `grantDataApiAccess`, I'm not sure if the iam policy is thorough enough?

**Comment by BryanPan342** [comment]
We would be changing people's deploy if we switched to using the `grantDataApiAccess` function

**Comment by MrArnoldPalmer** [comment]
@BryanPan342 we need to add `grantDataApiAccess` in addition to what we already have. This is for aurora serverless usage specifically which requires appsync have access to this data api in order to query the DB.

https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/data-api.html
