### ISSUE TITLE
(aws-docdb): bring cloudwatch support on aws-docdb DatabaseCluster

### ISSUE THREAD

**Issue by anandakrishnan-a** [aws/aws-cdk#13191]
At present, DatabaseCluster/DatabaseClusterProps from "aws-docdb" doesn't have the support of cloudwatch. 
Expecting props such as cloudwatchLogsExports, cloudwatchLogsRetention, cloudwatchLogsRetentionRole here

### Use Case
To enable cloudwatch logging for DocumentDb cluster.
The CfnDBCluster has this support, however we would like to use DatabaseCluster, as the former one requires masterpassword to be set, which we do not want to set in the code logic. 

### Proposed Solution
Similar to [RDS DatabaseCluster](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-rds.DatabaseCluster.html#cloudwatchlogsexports) , bring these props to DocumentDB Cluster. 

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by jumic** [comment]
Audit and profiler logs were implemented in PR #17478.
Not yet implemented: logs retention option (`cloudwatchLogsRetention`, `cloudwatchLogsRetentionRole`).
