### ISSUE TITLE
ecs: ability to access tag parameter value of TagParameterContainerImage

### ISSUE THREAD

**Issue by alastair-watts-avrios** [aws/aws-cdk#13202]
It would be useful to be able to easily access the value of the docker image tag on a `TagParameterContainerImage`. Currently one can only access the parameter name which is very difficult to work with.  The parameter itself can only be access by getting round the typing on `TagParameterContainerImage` and accessing the `imageTagParameter` field directly.

This change could give access to the whole parameter or just the value.

### Use Case

Adding an environment variable with that version to the container should be easy and is very useful for having monitoring aware of what version is running. Basically useful whenever you want a CloudFormation to be able to see the version running.

### Proposed Solution

add:

### Other

add

```ts
  public get tagParameterValue(): string {
    return cdk.Lazy.string({
      produce: () => {
        if (this.imageTagParameter) {
          return this.imageTagParameter.valueAsString;
        } else {
          throw new Error('TagParameterContainerImage must be used in a container definition when using tagParameterName');
        }
      },
    });
  }
  ```
  
or

  ```ts
  public get tagParameter(): string {
    return cdk.Lazy.string({
      produce: () => {
        if (this.imageTagParameter) {
          return this.imageTagParameter;
        } else {
          throw new Error('TagParameterContainerImage must be used in a container definition when using tagParameterName');
        }
      },
    });
  }
  ```

to `TagParameterContainerImage`.

Happy to submit a PR with the first soon (as I think it fits with the existing method (and the move away from using parameters) best.

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by skinny85** [comment]
Thanks for opening the issue @alastair-watts-avrios ! I agree this can be useful.

I'd love to have a PR for this 🙂. I like the first version a little more, so if you could go with that, it would be great 🙂.

Not sure if you've seen it already, but just to make sure, our Contributing guide is here: https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md#linking-against-this-repository.

Thanks,
Adam

**Comment by alastair-watts-avrios** [comment]
Thanks for having a look @skinny85.

Have submitted a PR (I went with the first method), https://github.com/aws/aws-cdk/pull/13340. Have tried to fallow the guidelines and the checks are passing so I hope it is ready to merge once it has approval.
