### ISSUE TITLE
Property 'SagemakerTrainTask' does not exist on @aws-cdk/aws-stepfunctions

### ISSUE THREAD

**Issue by ihorfito** [aws/aws-cdk#13201]
### The Question
https://docs.aws.amazon.com/cdk/api/latest/docs/aws-stepfunctions-tasks-readme.html#create-training-job 

```
new sfn.SagemakerTrainTask(this, 'TrainSagemaker', {
  trainingJobName: sfn.JsonPath.stringAt('$.JobName'),
  role,
  algorithmSpecification: {
    algorithmName: 'BlazingText',
    trainingInputMode: tasks.InputMode.FILE,
  },
  inputDataConfig: [{
    channelName: 'train',
    dataSource: {
      s3DataSource: {
        s3DataType: tasks.S3DataType.S3_PREFIX,
        s3Location: tasks.S3Location.fromJsonExpression('$.S3Bucket'),
      },
    },
  }],
  outputDataConfig: {
    s3OutputLocation: tasks.S3Location.fromBucket(s3.Bucket.fromBucketName(stack, 'Bucket', 'mybucket'), 'myoutputpath'),
  },
  resourceConfig: {
    instanceCount: 1,
    instanceType: ec2.InstanceType.of(ec2.InstanceClass.P3, ec2.InstanceSize.XLARGE2),
    volumeSize: cdk.Size.gibibytes(50),
  },
  stoppingCondition: {
    maxRuntime: cdk.Duration.hours(1),
  },
});
```

import * as sfn from '@aws-cdk/aws-stepfunctions';
import * as tasks from '@aws-cdk/aws-stepfunctions-tasks';

=> new sfn.SagemakerTrainTask
Property 'SagemakerTrainTask' does not exist on type 'typeof import(".../node_modules/@aws-cdk/aws-stepfunctions/lib/index")'.

### Environment

  - **CDK CLI Version:** 1.90.1
  - **Module Version:** 1.90.1
  - **Node.js Version:** v14
  - **OS:**  OSX 
  - **Language:** TypeScript

**Comment by ihorfito** [comment]
Should it be `new tasks.SageMakerCreateTrainingJob`  ?

**Comment by wong-a** [comment]
It should be SageMakerCreateTrainingJob. This was fixed in https://github.com/aws/aws-cdk/pull/12727. The docs are correct now.

**Comment by NGL321** [comment]
Closing due to resolution. Please reopen if this is in error.
