### ISSUE TITLE
(s3): IBucket.grantRead method not working

### ISSUE THREAD

**Issue by asanthan-amazon** [aws/aws-cdk#13205]
If I lookup existing Bucket by bucket-name (or probably bucket props) , and calling 'grantRead' method in IBucket reference throws error.
 

### Reproduction Steps

Use the below code and run it.
```
const bucket = Bucket.fromBucketName(scope, id, 'test-bucket');
bucket.grantRead(role);
```

### What did you expect to happen?
It should not throw any error.

method 'grantRead' should work based on bucketArn set in IBucket object.

### What actually happened?

```
/node_modules/monocdk/lib/aws-s3/lib/bucket.js:241
        return this.grant(identity, perms.BUCKET_READ_ACTIONS, perms.KEY_READ_ACTIONS, this.bucketArn, this.arnForObjects(objectsKeyPattern));
                    ^

TypeError: Cannot read property 'grant' of undefined
    at grantRead (/Users/****/*****/src/*****/node_modules/monocdk/lib/aws-s3/lib/bucket.js:241:21)
    at Array.forEach (<anonymous>)
    at Function.fromExistingBucket 

```

### Environment

  - **CDK CLI Version  :** 1.89.0
  - **Framework Version:** Any
  - **Node.js Version:** 
  - **OS               :** mac
  - **Language (Version):**  Any

### Other

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment]
@asanthan-amazon I am unable to reproduce this with the following code:

```ts
import * as cdk from 'monocdk';
import { aws_s3 as s3 } from 'monocdk';
import { aws_iam as iam } from 'monocdk';

export class CdkIbucketStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    // The code that defines your stack goes here

    const bucket = s3.Bucket.fromBucketName(this, 'Bucket', 'bucket-name');
    const role = new iam.Role(this, 'Role', { assumedBy: new iam.AccountRootPrincipal() });
    bucket.grantRead(role);
  }
}
```

Could you please provide a full code snippet?

**Comment by asanthan-amazon** [comment]
I found that my code to call '.grantRead' was wrong. it is working now. I am closing as false positive.
