### ISSUE TITLE
EC2: Name tag not automatically added for default NACL in custom VPC

### ISSUE THREAD

**Issue by MHacker9404** [aws/aws-cdk#13219]
The default NACL created with a custom VPC is not picking up a name like the other resources....
![custom-subnets](https://user-images.githubusercontent.com/4184348/108864297-0f8cfa00-75c0-11eb-8916-2cfaf3649094.png)
![custom-vpc](https://user-images.githubusercontent.com/4184348/108864299-10259080-75c0-11eb-93e9-d8e17e4f7d0e.png)
![default-NACL](https://user-images.githubusercontent.com/4184348/108864300-10259080-75c0-11eb-83dd-149ea0d80746.png)

### Environment

  - **CDK CLI Version  :**
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):** 

### Other

--- 

This is :bug: Bug Report

**Comment by BLasan** [comment]
@rix0rrr Hi! I'm new to the community. What kind of name we should use as the default one? This enhancement also needs to be added to the ec2 creation. Would like to pickup this issue

**Comment by rix0rrr** [comment]
Given that Network ACLs seem to be implicitly created as part of VPC creation, I'm not actually sure anymore this is as good of a first issue as I made it out to be.
