### ISSUE TITLE
(core): importValue docs refer to a missing example

### ISSUE THREAD

**Issue by douglasnaphas** [aws/aws-cdk#13222]
https://docs.aws.amazon.com/cdk/api/latest/docs/core-readme.html#parameters

The docs for `importValue` say:

> In the following example template snippets, Stack A exports VPC security group values and Stack B imports them.

but no example follows.

---

This is a 📕 documentation issue

**Comment by yattoni** [comment]
Issue is [here](https://github.com/aws/aws-cdk/blob/7966f8d48c4bff26beb22856d289f9d0c7e7081d/packages/%40aws-cdk/core/lib/cfn-fn.ts#L208) on the `static importValue(sharedValueToImport)` function in `core/lib/cfn-fn.ts`, not in the README, create the [generated api reference](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.Fn.html#static-importwbrvaluesharedvaluetoimport).

Docs for that method are copied from the [CFN docs for Fn::ImportValue](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-importvalue.html).

It seems like a large example to cram into the docs for a method, can probably just link the CFN docs and provide an example in the README?
