### ISSUE TITLE
(aws-codepipeline-actions): Missing docs for props that use assets from cdk

### ISSUE THREAD

**Issue by yokomizor** [aws/aws-cdk#13229]
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-s3.Bucket.html#autodeleteobjects

### Context

> autoDeleteObjects?
> 
> Type: boolean (optional, default: false)
> 
> Whether all objects should be automatically deleted when the bucket is removed from the stack or when the stack is deleted.
>
> Requires the removalPolicy to be set to RemovalPolicy.DESTROY.

The construct prop `autoDeleteObjects` seems just like any other prop. Users expect it to work just like other props - pure Cfn "transpilers".

### Problem

By setting `autoDeleteObjects`, a lambda will be created using code stored inside the sdk:
https://github.com/aws/aws-cdk/blob/b9cdd52274eca55940c65b830939132d0e074365/packages/%40aws-cdk/aws-s3/lib/auto-delete-objects-handler/index.ts

This option works fine with `cdk deploy` locally.

However, if you try to deploy the stack using `@aws-cdk/aws-codepipeline-actions/CloudFormationCreateUpdateStackAction`, you need to provide the lambda code yourself, as explained here: https://docs.aws.amazon.com/cdk/latest/guide/codepipeline_example.html

### Question

Is there a way access `aws-s3/lib/auto-delete-objects-handler/index.ts` from `@aws-cdk/aws-codepipeline-actions/CloudFormationCreateUpdateStackAction` or we have to submit the lambda ourselves?

If there is a way (even if it is submitting the code ourselves - which defeats the purpose of this construct IMO), it should be documented somehow in the `autoDeleteObjects` prop and any other prop that depends on assets, so users don't get surprised by hidden assets when using `@aws-cdk/aws-codepipeline-actions/CloudFormationCreateUpdateStackAction`.

---

This is a 📕 documentation issue

**Comment by skinny85** [comment]
Hello @yokomizor ,

the solution is to use the [CDK Pipelines module](https://docs.aws.amazon.com/cdk/api/latest/docs/pipelines-readme.html), which handles Assets for you.

Or, simply not use the `autoDeleteObjects` property - sorry!

Thanks,
Adam

**Comment by yokomizor** [comment]
Hey @skinny85,

I did not know about @aws-cdk/pipelines, but it looks like it fulfills my needs. I will take a deeper look into it.
About the documentation issue, I believe it will be solved as @aws-cdk/pipelines becomes stable so I am closing this issue.

Thanks,
Rogério
