### ISSUE TITLE
(aws-ses): use lambda.Runtime.NODEJS_12_X in DropSpamReceiptRule

### ISSUE THREAD

**Issue by trivikr** [aws/aws-cdk#13223]
DropSpamReceiptRule currently uses lambda.Runtime.NODEJS_10_X https://github.com/aws/aws-cdk/blob/e628a73f460fc805b9f5157be1f01aa5380d3e90/packages/%40aws-cdk/aws-ses/lib/receipt-rule.ts#L177-L182

Use lambda.Runtime.NODEJS_12_X instead.

### Use Case

Reasons for recommending NODEJS_12_X:
* Node.js 12.x went LTS in October 2019, and has been actively supported since October 2020.
* Node.js 10.x is going end-of-life on April 30th, 2021

https://endoflife.date/nodejs

### Proposed Solution

Use lambda.Runtime.NODEJS_12_X in DropSpamReceiptRule.

### Other

Suggested in https://github.com/aws/aws-cdk/pull/12808#discussion_r581113327

* [x] :wave: I may be able to implement this feature request
* [x] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by iliapolo** [comment]
Sounds good.
