### ISSUE TITLE
(ecs): add a service extension interface to ECS services

### ISSUE THREAD

**Issue by misterjoshua** [aws/aws-cdk#13234]
I'd like ECS services to have an extension interface similar to `TaskDefinition.addExtension` and `ITaskDefinitionExtension`.

### Use Case

I want to create packaged sets of modifications for ECS services. For instance, I may have a standard set of service discovery options or scaling policies that I want to apply to a service. I would like the option to create these packaged modifications in a way that works on either or both of Fargate and EC2 services.

### Proposed Solution
Add an `IServiceExtension` interface and an `addExtension` method to `BaseService`. Users could then implement an `IServiceExtension` and provide it as a parameter to the service's `addExtension` method.

```ts
class MyStandardScaling implements ecs.IFargateServiceExtension, ecs.IEc2ServiceExtension {
  extend(service: ecs.FargateService | ecs.Ec2Service): void {
    service.autoScaleTaskCount({
      maxCapacity: 100,
      minCapacity: 2,
    }).scaleOnCpuUtilization('Target40', {
      targetUtilizationPercent: 40,
    });
  }
}

service.addExtension(new MyStandardScaling());
```

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by SoManyHs** [comment]
Closing as per comment in #13235
