### ISSUE TITLE
RolePolicy already exists error: ResourceIDs generated for IAM policies are not unique

### ISSUE THREAD

**Issue by gagan405** [aws/aws-cdk#13233]
### The Question

I am creating a few resources (SQS) in each of the region and granting write access to an IAM role.

The relevant code which does this: 

~~~
this.requestQueue = new Queue(this, props.clientConfig.queue, {
            queueName: props.clientConfig.queue + "-" + props.deploymentRegion,
            visibilityTimeout: Duration.minutes(props.clientConfig.visibilityTimeoutInMinutes),
            deadLetterQueue: {
                maxReceiveCount: props.clientConfig.dlqMaxRecieve,
                queue: this.requestDeadLetterQueue
            }
        });

// This `createIAMRole` is true only in one region

       if (props.createIAMRole) {
           const role = new Role(this, props.clientConfig.name + '-sqs-role', {
               assumedBy: new AccountPrincipal(props.clientConfig.accountId),
               roleName: props.clientConfig.name + '-sqs-role'
           });
           this.requestQueue.grantSendMessages(role); // This attaches a policy to the role
       } else {
           const role = Role.fromRoleArn(this, 'Role', `arn:aws:iam::${props.pipelineStage.accountId}:role/${props.clientConfig.name}-sqs-role`);
           this.requestQueue.grantSendMessages(role);
       }
~~~

In short, I am granting the permission using: `this.requestQueue.grantSendMessages(role);`

The above statement creates a policy and attaches it to the IAM role. For e.g.,
~~~
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "sqs:SendMessage",
                "sqs:GetQueueAttributes",
                "sqs:GetQueueUrl"
            ],
            "Resource": "arn:aws:sqs:us-east-1:XXXX:TestQueue-NA",
            "Effect": "Allow"
        }
    ]
}
~~~
This successfully works in 2 of the regions (us-east-1, es-west-2) but fails in one saying the RolePolicy already exists. So I checked what resources are getting created, and I see the role policy LogicalIDs are inconsistent:

For FE (us-west-2): [QueueName]sqsroleDefaultPolicy93D17409

For NA (us-east-1): RolePolicy1234

For EU (eu-west-1): RolePolicy1234

As seen, the logical IDs are the same for both EU and NA, which results in the failure.

Questions:

1. Is there anyway to enforce logicalIds while granting write access to roles?
2. Why the logicalIds have different formats in FE compared to NA/EU?

### Environment

  - **CDK CLI Version:** 1.89.0
  - **OS:** OSX Mojave
  - **Language:** TypeScript

**Comment by rix0rrr** [comment]
> Why the logicalIds have different formats in FE compared to NA/EU?

You didn't tell, but let me guess. Is that the one region where 

```
// This `createIAMRole` is true only in one region
       if (props.createIAMRole) {
```

Is true, and a different code path is taken to get to 

```
           this.requestQueue.grantSendMessages(role); // This attaches a policy to the role
```

?

That would probably be the reason why.

--------------

> Is there anyway to enforce logicalIds while granting write access to roles?

I'm not sure there is, but the policy identifier is at least determined from the construct ID of the Role it gets added to. So if you make sure this identifier is different for every region:

```
const role = Role.fromRoleArn(this, 'Role', `arn:aws:iam::${props.pipelineStage.accountId}:role/${props.clientConfig.name}-sqs-role`);
                                    ^^^^^ this
```

The policy will get a unique logical ID.

**Comment by gagan405** [comment]
Thanks for the clarification. It would be better if the behavior is documented somewhere (if not already). I see that `Queue.grantSendMessages(role);` is the standard way of granting access, and also role is a global entity. So I guess it is a point of confusion.
