### ISSUE TITLE
(aws-events): Rule.addTarget() not configuring all lambda targets with event trigger

### ISSUE THREAD

**Issue by mharnicher-cxp** [aws/aws-cdk#13231]
I create three lambda functions, and add each of them as a target of a event rule cron. It successfully adds the first lambda function as a target, but it doesn't fully configure the other two.

### Reproduction Steps
```
const historicalLambdaProps = {
      runtime: Runtime.NODEJS_12_X,
      handler: 'handler',
      entry: 'lambda/historical-lambda.js',
      description: 'I send historical files to teleopti',
      timeout: Duration.seconds(25),
      memorySize: 256,
      tracing: Tracing.ACTIVE,
      environment: {
        ENV: 'dev',
        LOAD_S3_BUCKET_NAME: loadBucket.bucketName,
        FILE_TYPE: '',
        SNOWFLAKE_DATABASE: 'CXP',
        SNOWFLAKE_SCHEMA: 'DW',
        SNOWFLAKE_ACCOUNT: StringParameter.fromStringParameterAttributes(this, 'SnowflakeAccount', {
            parameterName: '/snowflake/account',
        }).stringValue,
        SNOWFLAKE_USERNAME: StringParameter.fromStringParameterAttributes(this, 'SnowflakeUsername', {
          parameterName: '/snowflake/username',
        }).stringValue,
      },
    }

    // Compiles Agent File
    historicalLambdaProps.environment.FILE_TYPE = 'Agent';  
    const agent = new NodejsFunction(this, 'Agent', historicalLambdaProps);

    // Compiles Agent Queue File
    historicalLambdaProps.environment.FILE_TYPE = 'AgentQueue';
    const agentQueue = new NodejsFunction(this, 'AgentQueue', historicalLambdaProps);

    // Compiles Queue File
    historicalLambdaProps.environment.FILE_TYPE = 'Queue';
    const queue = new NodejsFunction(this, 'Queue', historicalLambdaProps);

    // Run every 15 minutes
    const rule = new Rule(this, 'Cron', {
      schedule: Schedule.cron({minute: '*/15'}),
    });

    // Add cron to each lambda
    rule.addTarget(new LambdaFunction(agent));
    rule.addTarget(new LambdaFunction(agentQueue));
    rule.addTarget(new LambdaFunction(queue));
```

### What did you expect to happen?
For all 3 lambda's to run on a cron of every 15 minutes.

### What actually happened?
It successfully added all three targets to the event rule, but only the agent function was configured with the cron trigger. So it is running every 15 minutes, but the other two aren't.

<img width="1432" alt="Screen Shot 2021-02-23 at 1 07 10 PM" src="https://user-images.githubusercontent.com/8713659/108901530-37885780-75d8-11eb-8bfd-125f63d20dbf.png">
<img width="1313" alt="Screen Shot 2021-02-23 at 1 05 04 PM" src="https://user-images.githubusercontent.com/8713659/108901542-3a834800-75d8-11eb-96ac-ed8bdeed2d48.png">
<img width="1302" alt="Screen Shot 2021-02-23 at 1 05 34 PM" src="https://user-images.githubusercontent.com/8713659/108901539-39eab180-75d8-11eb-8d5d-0a3bf6a5b7ad.png">
<img width="1299" alt="Screen Shot 2021-02-23 at 1 05 21 PM" src="https://user-images.githubusercontent.com/8713659/108901540-3a834800-75d8-11eb-8591-06ddc7d2d05f.png">

### Environment

  - **CDK CLI Version: 1.89.0**
  - **Framework Version: 1.90.1**
  - **Node.js Version: v12.20.1** 
  - **OS: macOS Big Sur 11.2**
  - **Language (Version): TypeScript (3.9.5)**

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
I sympathize but this seems to be a Lambda and/or EventBridge bug, not a CDK bug.

Everything is configured correctly from the EventBridge side, but not from the Lambda side. Unless there is some documentation that says something like "you cannot add more than one Lambda target to an event rule" (in which case CDK should add validation), this seems like a bug you should report to AWS Lambda. They will engage EventBridge if the problem originates on the other end.

**Comment by rix0rrr** [comment]
Our friendly neighbourhood Lambda wizard informed me it's probably due to missing permissions

**Comment by rix0rrr** [comment]
Womp wooommmppp. It's totally that:

https://github.com/aws/aws-cdk/blob/4553d4b37cc7c2062eebc36bfe7a03b0226b598d/packages/%40aws-cdk/aws-events-targets/lib/util.ts#L42

**Comment by mharnicher-cxp** [comment]
ah, that makes sense!
