### ISSUE TITLE
(cloudfront, lambda): cyclic dependency for Lambda@Edge when using role

### ISSUE THREAD

**Issue by arjunnaha** [aws/aws-cdk#13236]
When using the CloudFront `EdgeFunction` with a role specified by the developer, a cyclic dependency error occurs.

### Reproduction Steps

```typescript
import * as cloudfront from "@aws-cdk/aws-cloudfront";
import * as origins from "@aws-cdk/aws-cloudfront-origins";
import * as lambda from "@aws-cdk/aws-lambda";
import * as core from "@aws-cdk/core";
import * as iam from "@aws-cdk/aws-iam";

import { Stack, StackProps } from "@_org_/lib-infra-common";

export class EdgeLambdaStack extends Stack {
  constructor(scope: core.Construct, customProps: StackProps, stackProps: core.StackProps = {}) {
    super(scope, customProps, stackProps);

    const edgeLambdaRole = new iam.Role(this, "LambdaRole", {
      roleName: core.PhysicalName.GENERATE_IF_NEEDED,
      assumedBy: new iam.CompositePrincipal(
        new iam.ServicePrincipal("lambda.amazonaws.com"),
        new iam.ServicePrincipal("edgelambda.amazonaws.com"),
      ),
       // ...any sort of managed policy (not needed to reproduce)
    });

    const myFunc1 = new cloudfront.experimental.EdgeFunction(this, "MyFunction1", {
      runtime: lambda.Runtime.NODEJS_10_X,
      handler: "index.handler",
      code: lambda.Code.fromInline("return"),
      role: edgeLambdaRole,
    });

    new cloudfront.Distribution(this, "myDist", {
      defaultBehavior: {
        origin: new origins.HttpOrigin("www.example.com"),
        edgeLambdas: [
          {
            functionVersion: myFunc1.currentVersion,
            eventType: cloudfront.LambdaEdgeEventType.VIEWER_REQUEST,
          },
        ],
      },
    });
  }
}

```
### What did you expect to happen?
A Lambda function would be created in the us-east-1 region, and the role would be created in IAM globally.

### What actually happened?

```
Error: 'Dev-Marketing-EdgeLambdaStack' depends on 'edge-lambda-stack-c8c09337b87f7807acc2002239aca2181ae1916d18' (dependency added using stack.addDependency()). Adding this dependency ("edge-lambda-stack-c8c09337b87f7807acc2002239aca2181ae1916d18/MyFunction1/Resource" depends on "Dev-Marketing-EdgeLambdaStack/LambdaRole/Resource") would create a cyclic reference.
    at Stack._addAssemblyDependency (/Users/arjunnaha/Developer/_org_/web-marketing/node_modules/@aws-cdk/core/lib/stack.ts:724:13)
    at Object.addDependency (/Users/arjunnaha/Developer/_org_/web-marketing/node_modules/@aws-cdk/core/lib/deps.ts:52:20)
    at CfnFunction.addDependsOn (/Users/arjunnaha/Developer/_org_/web-marketing/node_modules/@aws-cdk/core/lib/cfn-resource.ts:245:5)
    at Object.prepareApp (/Users/arjunnaha/Developer/_org_/web-marketing/node_modules/@aws-cdk/core/lib/private/prepare-app.ts:26:16)
    at Object.synthesize (/Users/arjunnaha/Developer/_org_/web-marketing/node_modules/@aws-cdk/core/lib/private/synthesis.ts:24:3)
    at App.synth (/Users/arjunnaha/Developer/_org_/web-marketing/node_modules/@aws-cdk/core/lib/stage.ts:188:23)
    at process.<anonymous> (/Users/arjunnaha/Developer/_org_/web-marketing/node_modules/@aws-cdk/core/lib/app.ts:123:45)
    at Object.onceWrapper (node:events:483:26)
    at process.emit (node:events:376:20)
    at process.EventEmitter.emit (node:domain:470:12)
```

### Environment

  - **CDK CLI Version:** 1.90.1 (build 0aee440)
  - **Framework Version:** 1.90.1
  - **Node.js Version:** v15.5.0
  - **OS:** macOS Big Sur 11.2.1
  - **Language (Version):** TypeScript (4.1.3)

--- 

This is :bug: Bug Report

**Comment by njlynch** [comment]
This one is a bit tricky.

The created us-east-1 stack _must_ have a dependency on the "main" stack, as the main stack can't be created first; doing so would mean the function ARN isn't available to read and that the Distribution would not deploy correctly. Creating the role in the main stack certainly leads to a circular dependency.

Two options to consider:
1. Let the `Function` create the role, and add any custom policies to the role after the function is created. This still allows you control of the permissions attached to role, but would solve the scope/cyclic referencing of that role.
2. Create the role in a third stack, and either pass it into your main stack or import it (e.g., `iam.Role.fromRoleArn()`). This would create a dependency chain where the role stack was the first, then the EdgeFunction stack, then your main stack.

Would either of the above two work for you as a work-around?

**Comment by arjunnaha** [comment]
Completely understand and thanks for the work-arounds. I think the second option will work for us, as the role is used a few times in the stack.

Would this be a permanent work-around 😄? Or could something be incorporated into the CDK to auto-create the third stack? (I can probably see this getting quite messy if there are lots of circular dependencies.)

**Comment by njlynch** [comment]
I think this is likely a permanent work-around, until someone more clever than me comes around with a solution. :)

Detecting that the Role passed in might cause a circular dependency, then creating a third stack, then re-parenting the role into a new stack, is not something I would expect (nor really want) the construct to do. I can imagine all sorts of unintended consequences with that approach.

I'm going to close this, but feel free to comment (and @ me) if you have any follow-ups.

**Comment by asnaseer-resilient** [comment]
I thought my code is written such that the edge lambda function is indeed creating the role (as suggested by @njlynch above) as follows (please note that this code uses a helper library I wrote named **CDK_UTILS** that encapsulates some of the common things we do across various CDK stacks):
```
    const lambdaAtEdgeFunction = new cdkCloudfront.experimental.EdgeFunction(this, 'LambdaAtEdgeFunction', {
      runtime: cdkLambda.Runtime.NODEJS_12_X,
      code: cdkLambda.Code.fromAsset('.build/request-routing-lambda'),
      handler: 'request-routing-lambda.requestRoutingLambda',
      role: new cdkIam.Role(this, 'LambdaAtEdgeRole', {
        roleName: CDK_UTILS.resourceName('cf-lae-role'),
        assumedBy: new cdkIam.CompositePrincipal(new cdkIam.ServicePrincipal('lambda.amazonaws.com'), new cdkIam.ServicePrincipal('edgelambda.amazonaws.com'))
      }),
      initialPolicy: [
        new cdkIam.PolicyStatement({
          effect: cdkIam.Effect.ALLOW,
          actions: ['servicediscovery:DiscoverInstances'],
          resources: ['*']
        }),
        CDK_UTILS.hubbleSirenPolicyStatement(),
        CDK_UTILS.lambdaCloudwatchLogsPolicyStatement(),
        CDK_UTILS.vpcPolicyStatement()
      ],
      logRetention: 60,
      timeout: cdk.Duration.seconds(5),
      tracing: cdkLambda.Tracing.ACTIVE,
      vpc: CDK_UTILS.vpcLookupByName(this, vpcName),
      environment: {
        STAGE: stage,
        HUBBLE_ALERTS_S3_BUCKET_NAME: hubbleAlertsS3BucketName,
        SERVICE_DISCOVEY_REGION: env!.region!
      }
    });
```
However, I am hitting the cyclic dependency error. Am I doing something else incorrectly?

**Comment by njlynch** [comment]
@asnaseer-resilient -

> I thought my code is written such that the edge lambda function is indeed creating the role 
>       role: new cdkIam.Role(this, 'LambdaAtEdgeRole', {
>         roleName: CDK_UTILS.resourceName('cf-lae-role'),
>         assumedBy: new cdkIam.CompositePrincipal(new cdkIam.ServicePrincipal('lambda.amazonaws.com'), new cdkIam.ServicePrincipal('edgelambda.amazonaws.com'))
>       }),

No, in the above example, you are still creating the role explicitly and passing it to the Function. For the function to create the role, you need to leave the role parameter as undefined; then once the Function has been created, use `lambdaAtEdgeFunction.role` to access the role and modify the permissions as required.
