### ISSUE TITLE
[custom-resources] allow for no policy to be specified

### ISSUE THREAD

**Issue by mh-love** [aws/aws-cdk#13232]
I do not have the ability to modify roles and the CDK assumes I do for an `AwsCustomResource`.  I can specify the execution role for the custom resource Lambda, but I _have_ to specify a policy, and `cdk deploy` fails for me because I don't have access to modify the execution role with the new policy. I would expect for _policy_ to be optional if _role_ is specified. I am in a corporate setting where permissions are "locked down" and roles exist but can not be modified.

### Reproduction Steps

```
export class ExistingS3BucketEventSource extends CDK.Construct {
  constructor(scope: CDK.Construct, id: string, props: S3NotificationLambdaProps) {
    super(scope, id);

    new CR.AwsCustomResource(scope, id + 'CustomResource', {
      onCreate: {
        ...
      },
      onDelete: {
        ...
      },
      policy: CR.AwsCustomResourcePolicy.fromStatements([]), // I don't want this! Also specifying no statements doesn't work!
      role: props.role // I want permissions from here!
    });

    props.lambda.addPermission('AllowS3Invocation', {
      action: 'lambda:InvokeFunction',
      principal: new IAM.ServicePrincipal('s3.amazonaws.com'),
      sourceArn: props.bucket.bucketArn
    });
  }
}

interface S3NotificationLambdaProps {
  role: IAM.IRole;
  bucket: S3.IBucket;
  lambda: Lambda.IFunction;
  events: string[];
  prefix: string;
}
```

### What did you expect to happen?

I do not want to modify the execution role.

### What actually happened?

The execution role is modified.

### Environment

  - **CDK CLI Version  : 1.90.0 (build 7edba31)**
  - **Framework Version: 1.90.0**
  - **Node.js Version: v12.18.3** 
  - **OS               : Catalina 10.15.7**
  - **Language (Version): TypeScript (3.8.3)**

### Other

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
I guess I don't mind that field being optional.

In the mean time, you can use `role.withoutPolicyUpdates()` (or call `Role.fromRoleName(..., { mutable: false })`) to prevent your existing role from being attempted to be updated.

**Comment by mainframenzo** [comment]
@rix0rrr Very useful tip. Thank you!

**Comment by BLasan** [comment]
@rix0rrr Still opened?

**Comment by jacobsnapp** [comment]
> I guess I don't mind that field being optional.
> 
> In the mean time, you can use `role.withoutPolicyUpdates()` (or call `Role.fromRoleName(..., { mutable: false })`) to prevent your existing role from being attempted to be updated.

@rix0rrr - I have used Role.from_role_arn( ..., mutable=False) and role.without_policy_updates() with no luck. AwsCustomResource does not seem to respect the immutable role and always adds duplicate inline policies.

**Comment by mattiamatrix** [comment]
Hello, I am also having the same issue with CDK 2.17.0. Did anyone find a workaround for this? I currently have a role with 60+ replicated inline policies and almost reached the characters limit.

**Comment by mattiamatrix** [comment]
#19114 might partially help

**Comment by haslam22** [comment]
Experiencing the same problem. I need to provide an immutable role to `AwsCustomResource` which already has the correct permissions to do what I want. I'm not allowed to update an IAM role with a new policy in my corporate environment.

No workaround available as far as I can see, it always tries to attach a policy if `role` is defined: [aws-custom-resource.ts#L409](https://github.com/aws/aws-cdk/blob/main/packages/@aws-cdk/custom-resources/lib/aws-custom-resource/aws-custom-resource.ts#L409)
