### ISSUE TITLE
API Documents no longer ordered alphabetically.. ( after version 1.91 )

### ISSUE THREAD

**Issue by mrpackethead** [aws/aws-cdk#13246]
API Documents ( Python ) no longer alphabetially ordered..
v 1.91 seems to have messed the documetns up a wee bit..   The list on the left hand side used to be alphabetaically arranged, now its random.

https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_apigatewayv2.html

4 replies

This is a 📕 documentation issue

**Comment by rix0rrr** [comment]
Oh wow, thanks for alerting me!

**Comment by rix0rrr** [comment]
Fixed for the next release.
