### ISSUE TITLE
(EventBus): make it easy to grant multiple actions in one go

### ISSUE THREAD

**Issue by dnltsk** [aws/aws-cdk#13253]
Currently it is not possible to open an EventBus to other accounts programmatically. The only way to modify the Resource Policy of an EventBus is the GUI.

### Use Case

IaC in general - when we roll out a Stack again, we wont to restore the ResourcePolicy of the EventBus

In fact, we are not able to create a new EventBus and open it to other Accounts without manually editing the Bus' Resource Policy in the GUI.

### Proposed Solution

very granular

```typescript
const eventBus = new events.EventBus(this, 'new-event-bus', {eventBusName: 'new-events'});
eventBus.addToResourcePolicy(new PolicyStatement({
  effect: Effect.ALLOW,
  actions: ["events:PutEvents", "events:PutRule", "events:DeleteRule", "events:DisableRule", "events:EnableRule", "events:TagResource", "events:UntagResource", "events:DescribeRule", "events:ListTargetsByRule", "events:ListTagsForResource"],
  resources: [eventBus.eventBusArn],
  principals: ["*"],
  conditions: {
       "StringEquals": {
         "aws:PrincipalOrgID": "abc-123"
       }
    }
}));
```

or very general

```typescript
eventBus.grantPut(new AWSPrincipal("*"));
eventBus.grantRead(new AWSPrincipal("*"));
...
```

### Other

We already tried alot

#### 1. Looping over `CfnEventBusPolicy`

`CfnEventBusPolicy` can only handle a single action and it seems to be limited to `events:PutEvents`.

```typescript
["events:PutEvents", "events:PutRule", "events:DeleteRule", "events:DisableRule", "events:EnableRule", "events:TagResource", "events:UntagResource", "events:DescribeRule", "events:ListTargetsByRule", "events:ListTagsForResource"].forEach((action, index) => {
  new CfnEventBusPolicy(this, `new-event-bus-resource-polic-${index}`, {
    eventBusName: eventBus.eventBusName,
    action,
    statementId: `sid${index}`,
    principal: '*',
    condition: {
      key: 'aws:PrincipalOrgID',
      type: 'StringEquals',
      value: 'abc-123',
    },
  });
});
```

=> Throws `Provided value in parameter 'action' is not supported. (Service: AWSEvents; Status Code: 400; Error Code: ValidationException; Request ID: 048b6e6d-b482-4c5f-94ef-b2be15c4a7b1; Proxy: null)`

#### 2. Escape Hatch via addPropertyOverride on CfnEventBusPolicy

```typescript
const templateSingleAction = new CfnEventBusPolicy(this, `new-event-bus-resource-policy`, {
  eventBusName: eventBus.eventBusName,
  action: 'events:PutEvents',
  statementId: 'sid',
  principal: '*',
  condition: {
    key: 'aws:PrincipalOrgID',
    type: 'StringEquals',
    value: 'abc-123',
  },
});

templateSingleAction.addPropertyOverride("Action", ["events:PutEvents", "events:PutRule", "events:DeleteRule", "events:DisableRule", "events:EnableRule", "events:TagResource", "events:UntagResource", "events:DescribeRule", "events:ListTargetsByRule", "events:ListTagsForResource"]);
```

=> The synthed CloudFormation looks pretty well, but the deployment throws `Property validation failure: [Value of property {/Action} does not match type {String}]`

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
It looks true that EventBusPolicy only accepts a single string as Action, so trying to work around that and jamming a list of strings into that property anyway is not going to work; CloudFormation will reject it however way you do it.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-eventbuspolicy.html

What you can always do is make a new `CfnEventBusPolicy` for every string in your list of strings.

**Comment by dnltsk** [comment]
@rix0rrr Thanks for your reply. I tried this as well. The documentation of `CfnEventBusPolicy` is misleading, unfortunately. It'll fail because `events:PutEvent` is the only accepted value.

After playing a bit more around it seems that I misunderstood the EventBus' cross-account concept. I think the cross account communication is intended to be only one-way: so that roles from external accounts can perform the `events:PutEvent` action. 

Just to verify the expectation behaviour: Is it intended that a role of account B can consume events from the account A's EventBus by using a Rule?
