### ISSUE TITLE
ECR's "fromDockerHub" name is inadequate

### ISSUE THREAD

**Issue by RomainMuller** [aws/aws-cdk#1325]
The value passed to ECR's `fromDockerHub` can be any image reference in a registry that is accessible. The default registry is Docker Hub, however one can absolutely pass an ECR image name there, as they also can pass an image from another public registry.

The method should be renamed to not be dockerhub-centric.

**Comment by eladb** [comment]
Maybe `fromPublicImage‘?

**Comment by rix0rrr** [comment]
It's no longer called this by a wide margin.
