### ISSUE TITLE
(autoscaling): StepScalingPolicy add evaluationPeriods parameter

### ISSUE THREAD

**Issue by BDeus** [aws/aws-cdk#13252]
When creating a `StepScalingPolicy` for an ASG, we cannot configured the evaluationPeriods of the CloudwatchAlarm created in underlying.
The default value is enforced to `1`

### Proposed Solution
Add a property in `BasicStepScalingPolicyProps`:

```ts
/**
  * The number of the most recent periods, or data points, to evaluate when determining alarm state.
  * @default Default evaluation periods for cloudwatch alarms
  */
  readonly alarmEvaluationPeriods?: number;
}
...
this.upperAlarm = new cloudwatch.Alarm(this, 'UpperAlarm', {
    // Recommended by AutoScaling
    metric: props.metric,
    alarmDescription: 'Upper threshold scaling alarm',
    comparisonOperator: cloudwatch.ComparisonOperator.GREATER_THAN_OR_EQUAL_TO_THRESHOLD,
    evaluationPeriods: props.alarmEvaluationPeriods,
    threshold,
});
```

### Links
https://github.com/aws/aws-cdk/blob/404b5569bb76e3f579dd3005dcf06eeeae9df7f6/packages/%40aws-cdk/aws-autoscaling/lib/step-scaling-policy.ts#L109

https://github.com/aws/aws-cdk/blob/404b5569bb76e3f579dd3005dcf06eeeae9df7f6/packages/%40aws-cdk/aws-autoscaling/lib/step-scaling-policy.ts#L144

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
Closed by #13366
