### ISSUE TITLE
(ec2): Allow SecurityGroup to accept a VpcId instead of requiring IVpc

### ISSUE THREAD

**Issue by apmclean** [aws/aws-cdk#13259]
Currently the constructor for SecurityGroup requires type IVpc.  

In some scenarios the VPC ID is imported via an SSM Parameter, and constructing a Vpc using 'fromLookup' or 'fromAttributes' can be onerous.  'fromLookup' requires IAM permissions that may not exist in pipeline based deployments.  'fromAttributes' requires additional context values besides just the Vpc ID to construct.

Understanding that the only 'vpc' attribute used by this construct is `vpcId: props.vpc.vpcId` I'd like the ability to supply this information without needing to construct a full Vpc.

### Use Case

In a constrained environment:
- Pipeline based deployments often don't have permissions outside of invoking CloudFormation with a passed role.  Performing 'Describe' operations on Subnets, Vpcs, etc makes using 'fromLookup()' difficult.
- Using a 'layer cake' approach the VPC is often already deployed.  The values for subnets, vpcs, etc are in Parameter store and retrieved by CloudFormation at run-time.

### Proposed Solution

Permit passing the VPC ID as a 'string', or perhaps make it easier to get an IVpc where values are retrieved from SSM.

Would expect something like this to work:
```typescript
        const securityGroup = new ec2.SecurityGroup(this, 'SecurityGroup', {
            vpc: ssm.StringParameter.valueForStringParameter(this, '/network/vpc/id')
        })
```

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
You can make your own implementation of `IVpc` that only supports returning the `vpcId`.
