### ISSUE TITLE
(aws-lambda): Validate Lambda functionName

### ISSUE THREAD

**Issue by jonnekaunisto** [aws/aws-cdk#13264]
The lambda Function class should validate the functionName. Currently the only restriction is that the name is less than equal to 64 characters: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-functionname

### Use Case

Catching bugs during build time instead of when deploying.

### Proposed Solution

`if (functionName.length > 64) {
    throw Error
}`

### Other

This is the error that I got recently:

`1 validation error detected: Value 'veryLongFunctionName' at 'functionName' failed to satisfy constraint: Member must have length less than or equal to 64 (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 5d3d811c-ff88-43db-b9e0-468197776ee0; Proxy: null)
`

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change (technically we will limit function names, but those would be rejected by CFN anyways)

---

This is a :rocket: Feature Request

**Comment by jonnekaunisto** [comment]
Yeah I'm not sure why CloudFormation doesn't mention anything, but from the console you can see this: "Use only letters, numbers, hyphens, or underscores with no spaces."

**Comment by mishabruml** [comment]
I suppose the design choice here was: the validation is already being done (probably by a common unit) by the service apis that eventually get called e.g. `aws lambda create-function`, and it's easier to just let the validation errors surface up back to client

if there is value to be added by moving/replicating the existing validation ruleset in client library then I would be happy to give this PR a shot!

**Comment by kaizio** [comment]
Ran into with a nested stack failing because of a function name length being too long. Combine with with issue #5974 you have to dig through cloudformation console to find the issue. Validation is needed.

**Comment by damianlluch** [comment]
@kaizio @mishabruml @jonnekaunisto @lewisdiamond 

Hi guys, I'm having this problem with the latest version of CDK.

How can I fix it? I have several Lambda functions, and the framework doesn't explicitly indicate which function has the problem.

If you can help me.

thanks

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/1463804/223589937-94544885-6848-4a51-9a82-014e25be45d3.png">
