### ISSUE TITLE
[cdk-pipelines]: use existing roles instead of creating or modifying them

### ISSUE THREAD

**Issue by mainframenzo** [aws/aws-cdk#13270]
I specify 3 existing roles in the DefaultStackSynthesizer for a CDK project: one to assume to deploy the CdkPipeline stack (locally), one that is assumed to publish assets to S3, and the other CloudFormation assumes to deploy my actual software stack. I would like to use these everywhere. Specifically for this request, I would like the CdkPipeline to not create / modify roles like what I see happening https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/pipelines/lib/pipeline.ts and instead use role(s) I specify.

For the asset publishing role, I'd like to pass-through from CdkPipeline -> AssetPublishing -> PublishAssetsAction:

```
  const pipeline = new CdkPipeline(this, 'CdkPipeline', {
      pipelineName: this.node.tryGetContext('pipeline_stack_name'),
      fileAssetPublishingRole: IRole
```

...and something of the sort if any other roles are created.

### Use Case

I do not have permissions to create or modify roles - corporate environment is "locked down".

### Proposed Solution

Not familiar enough with implementation (yet) to propose a solution.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by nathanyocum-ridgeline** [comment]
Does
```typescript
Role.fromRoleArn(
  this,
  'role',
  'arn:aws:iam::${ACCOUNT_ID}:role/pre-defined-role',
  { mutable: false }
);
```
meet your use case?

**Comment by rix0rrr** [comment]
Wait -- why is passing the Role ARNs to the DefaultSynthesizer not good enough?

https://docs.aws.amazon.com/cdk/latest/guide/bootstrapping.html#bootstrapping-custom-synth
