### ISSUE TITLE
(aws-ecs): `Volume` no longer exists on ecs

### ISSUE THREAD

**Issue by radiosilence** [aws/aws-cdk#13282]
https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-ecs/README.md

```
Property 'Volume' does not exist on type 'typeof import(.../node_modules/@aws-cdk/aws-ecs/lib/index")'.
```

I guess it has been moved? I tried with ec2.Volume and it didn't like that either. It seems to exist as an interface, but not as code.

---

This is a 📕 documentation issue

**Comment by MrArnoldPalmer** [comment]
`Volume` is just an interface so changed the example to reflect that. https://github.com/aws/aws-cdk/pull/13302
