### ISSUE TITLE
(aws-s3): Python cdk 1.91.0 returns incorrect S3 bucket website domain name

### ISSUE THREAD

**Issue by crawfobw** [aws/aws-cdk#13291]
`bucket.bucket_website_domain_name`
returns the incorrect format <bucket-name>.s3-website-us-east-2.amazonaws.com
instead of the correct format <bucket-name>.s3-website.us-east-2.amazonaws.com

This is :bug: Bug Report

**Comment by iliapolo** [comment]
@crawfobw You can tell CDK to use the new formatting using this [property](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-s3.BucketAttributes.html#bucketwebsitenewurlformat).

**Comment by crawfobw** [comment]
Can't this property be based on the resource creation time? Does not seem like something that should require the developer to configure manually.

**Comment by iliapolo** [comment]
@crawfobw I agree its a little awkward, but this was done to maintain backwards compatibility. We [initially](https://github.com/aws/aws-cdk/pull/1550/files) only used `-`, which still works for the older regions.
