### ISSUE TITLE
SQS: Unable to pass Policy in QueuePolicy Construct

### ISSUE THREAD

**Issue by vikrantsundriyal** [aws/aws-cdk#13296]
## :question: General Issue

Hi,
Am trying to work on an automation where I wish to create a SQS and add a QueuePOlicy using a CDK application.
While doing so am unable to figure out how Document will be passed. Referring to the doc link given below, i see Queue list is the only property so unable to figure out how to pass policy document.
Referring below doc link:
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-sqs.QueuePolicy.html

**Comment by Prashanna313** [comment]
I think you can make use of the method addToResourcePolicy(statement) [Queue method](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-sqs.Queue.html)

**Comment by vikrantsundriyal** [comment]
@Prashanna313 -- addToResourcePolicy and QueuePolicy solve different purpose. I have couple of existing SNS, in CDK app am creating a Queue dollowed by attaching a policy. Policy statement is defined in CDK app. Based on my understanding in this case QueuePOlicy is the construct to be used. 
Thats why am specific in my question, how to pass policy document in QueuePolicy. I dont see this documented.

**Comment by SimonJang** [comment]
I encountered the same issue, but there is a simple workaround using the `CfnQueuePolicy` construct instead. @vikrantsundriyal worked for me, hope it helps.

```
const customPolicyDocument = new iam.PolicyDocument({
    statements: [
        new iam.PolicyStatement({
            actions: ['sqs:sendMessage'],
            effect: iam.Effect.ALLOW,
            conditions: {
                ArnEquals: {
                    'aws:SourceArn': myTopic.topicArn
                }
            },
            principals: [
                new iam.ServicePrincipal('sns.amazonaws.com')
            ],
            resources: [
                myQueue.queueArn
            ]
        })
    ]
});

new sqs.CfnQueuePolicy(this, 'MyCustomQueuePolicyDocument', {
    queues: [myQueue.queueUrl],
    policyDocument: customPolicyDocument.toJSON()
});
```

**Comment by vikrantsundriyal** [comment]
@SimonJang  - thanks for sharing your snippet... I had some other areas to be covered for my use case... Sharing what worked for me 
import * as cdk from '@aws-cdk/core';
import * as sqs from "@aws-cdk/aws-sqs";
import * as sns from "@aws-cdk/aws-sns";
import * as iam from "@aws-cdk/aws-iam";

export class CdkSqssnsStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);
    // Create a Queue, we can create a loop which runs from a list of Queue configuration given in a config file
    const queue = new sqs.Queue(this, 'xyzQueue', {
             queueName: "ingress-publisher-topic-subscription"
          });
   // Add Policy to queue         
      queue.addToResourcePolicy(new iam.PolicyStatement({
      sid: "allow-sns-messages",
      effect: iam.Effect.ALLOW,
      resources: [queue.queueArn],
      actions: ['sqs:*'],
      principals: [
              new iam.ArnPrincipal('arn:aws:iam::xxxxxxxxxx:root'),
              new iam.ArnPrincipal('arn:aws:iam::xxxxxxxxxx:user/abcuser')
                  ],
    }));
  // Create Subscription for the Queue created above
     const snsSubscriptionCom = new sns.Subscription(this, 'snsSubscriptionCom', {
      endpoint: queue.queueArn,
      protocol: sns.SubscriptionProtocol.SQS,
      topic: sns.Topic.fromTopicArn(this, 'topicId', 'arn:aws:sns:us-east-1:xxxxxxx:ocs-ingress-publisher-com-topic'),
      filterPolicy: {
        EVENT_NAME: sns.SubscriptionFilter.stringFilter({
              whitelist: ["UPDATE", "RECALLED", "DISPATCH", "TRANSMITTED"]}),
        SUPPORTED_XYZ: sns.SubscriptionFilter.stringFilter({
              whitelist: ["gaming"]})
      }
    });
    // The code that defines your stack goes here
  }
}

**Comment by peterwoodworth** [comment]
Thank you both for sharing your solutions! It's much appreciated
