### ISSUE TITLE
(ecs-service-extensions): The ability to create the taskRole

### ISSUE THREAD

**Issue by brentryan** [aws/aws-cdk#13304]
We need the ability to create the taskRole of a taskDefinition ahead of time and not rely on the auto-generated taskRole because we deploy our CDK applications in 2 stacks (infrastructure and service). We create the infrastructure before the service so when I create things like S3 buckets with resource policies in the infrastructure stack, I want to be able to build a bucket policy with taskRole. If we could create the taskRole ourself and pass it into the infrastructure and the service stacks then everything would work.

Expose the task definition props through the service props: https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk-containers/ecs-service-extensions/lib/service.ts#L132

* [X] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by tobli** [comment]
Since the PR is merged this issue could be closed, right @brentryan?

**Comment by brentryan** [comment]
Yes
