### ISSUE TITLE
(pipelines): --output Argument leaks into SimpleSynthAction when deploying the Pipeline

### ISSUE THREAD

**Issue by aax** [aws/aws-cdk#13303]
I ran into this issue when synthesizing an app containing a CdkPipeline with a SimpleSynthAction. For my needs, I have to specify a custom --output folder when deploying the app. But this output folder path somehow leaks into the CdkPipeline itself. The SimpleSynthAction expects the cloud assembly artifact to be at the same location within the CodeBuild project.

### Reproduction Steps

Define a CdkPipeline with a SimpleSynthAction:
```
cloud_assembly_artifact = codepipeline.Artifact()

CdkPipeline(stack, "Pipeline",
    cloud_assembly_artifact=cloud_assembly_artifact,
    source_action=...,
    synth_action=SimpleSynthAction(
        source_artifact=...,
        cloud_assembly_artifact=cloud_assembly_artifact,
        install_command='npm install -g aws-cdk@1.91.0',
        synth_command='cdk synth'
    )
)
```

Deploy the app with a custom output argument:
```
cdk deploy --output /tmp/cdk
```

### What did you expect to happen?

I would expect the pipeline to be deployed and executed successfully.

### What actually happened?

The synth action in the pipeline fails. The build spec generated for the synth action looks as follows. Note the primary artifact's base-directory is `/tmp/cdk`, but the synth command writes its output to `cdk.out` by default. Therefore the action has an empty output artifact and the build fails.
```
{
  "version": "0.2",
  "phases": {
    "pre_build": {
      "commands": [
        "npm install -g aws-cdk@1.91.0"
      ]
    },
    "build": {
      "commands": [
        "pipenv run cdk synth"
      ]
    }
  },
  "artifacts": {
    "base-directory": "/tmp/cdk",
    "files": "**/*"
  }
}
```

### Environment

  - **CDK CLI Version  :** 1.91.0
  - **Framework Version:** 1.91.0
  - **Node.js Version:** v15.5.0
  - **OS               :** Windows
  - **Language (Version):**  Python 3.7.9

### Other

I can't see how this behaviour is intended. But if it is, I would need to change it for my case. Can I somehow specify the location of the cloud assembly artifact within the SimpleSynthAction?

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
The relative paths we use in the ACTUAL synth dir are still correct, but the base output directory should ALWAYS be `cdk.out`, and not depend on deploy settings.
