### ISSUE TITLE
(aws-apigateway): Change default DomainName default SecurityPolicy to TLS_1_2

### ISSUE THREAD

**Issue by jonnekaunisto** [aws/aws-cdk#13306]
Change the default DomainName SecurityPolicy to TLS1.2, since major browsers are dropping support for TLS1.0, so it is not a sensible default anymore

* [ x ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by jonnekaunisto** [comment]
According to #13309 this cannot be done since it'd be a breaking change

**Comment by rrhodes** [comment]
Disappointed to see this issue closed. IMO this seems like a reasonable request. If there is any argument to made for limited exceptions to the "no breaking changes in stable packages" rule then it would be nice to see TLS 1.2 set as the default.
