### ISSUE TITLE
aws-lambda-nodejs: Paths with Spaces Break ESBuild

### ISSUE THREAD

**Issue by GEMISIS** [aws/aws-cdk#13311]
When creating a NodeJS lambda function using the aws-lambda-nodejs module, if a path has spaces in it on Windows, then esbuild will fail to properly bundle the package.

### Reproduction Steps

1. Create a new with code like this:
```typescript
    const userAuthLambda = new NodejsFunction(this, 'user-auth-lambda', {
      runtime: Runtime.NODEJS_14_X,
      entry: path.join(__dirname, '../functions/UserAuth.ts'),
      handler: 'handler'
    });
```
2. Run `npm run build`
3. Run `cdk synth`
4. Observe error

### What did you expect to happen?
`cdk synth` should create the CloudFormation template as expected.

### What actually happened?
Receiving the error ` error: Must use "outdir" when there are multiple input files`

### Environment

  - **CDK CLI Version  :** 1.91.0
  - **Framework Version:** 1.91.0
  - **Node.js Version: **v12.19.0
  - **OS               :** Windows
  - **Language (Version):** TypeScript (3.8.3)

### Other
Issue #13210 previously reported this and [Pull Request 13268](https://github.com/aws/aws-cdk/pull/13268) attempted to fix it. However, after testing this out locally on my Windows machine, this does not seem to have actually resolved it. I have a fix incoming for this now and will make sure to reference this issue.

--- 

This is :bug: Bug Report

**Comment by MichaelVidStep** [comment]
Hi there,

I'm still getting this error. What is the fix?
