### ISSUE TITLE
chore(aws-lambda-destinations):  Missing record in .github/workflows/issue-label-assign.yml

### ISSUE THREAD

**Issue by robertd** [aws/aws-cdk#13314]
Hi @SomayaB. Module `aws-lambda-destinations` (and maintainer/assignee) seems to be missing in https://github.com/aws/aws-cdk/blob/master/.github/workflows/issue-label-assign.yml. Thanks!

**Comment by peterwoodworth** [comment]
Hey @robertd, thank you for letting us know about this! We're currently in the process of rethinking the way we do auto assignment, as our current solution has some limitations. We'll be sure to have auto labelling and assignment for all construct libraries working soon, but in the meantime feel free to use `aws-lambda` in place of `aws-lambda-destinations`.
