### ISSUE TITLE
Docker assets: deploy two stacks that use the same image would upload the image twice

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#1331]
If I do want to deploy multiple different stacks that use the same image, I definitely don't want to upload the image multiple times to ECR!

Bear in mind that the "repository adoption" mechanism may block our way to do this, but maybe this whole idea of repository adoption should be address as part of asset garbage collection (#1332) instead.

**Comment by eladb** [comment]
Repurposing issue.

Original title: __Docker assets: cannot deploy two stacks that use the same image__

Original description:

Since the name of the ECR image is solely determined by the content of the image, when trying to deploy two stacks into the same account/region with the same image, I am getting the following error:

```
This repository is already owned by another stack: .....
```

**Comment by rix0rrr** [comment]
This is true. Some form of garbage collection might make sense as well, but now we need to do refcounting... (?)

Or I guess the Toolkit Stack could contain a Lambda that runs every day deleting unused resources (detected by enumerating all stacks and looking at the asset parameters?)

**Comment by eladb** [comment]
I like the periodic garbage collector lambda idea!

**Comment by eladb** [comment]
This is already resolved. Docker images are now identified by the source hash and therefore will not be built/uploaded twice if used by multiple stacks within the same app.
