### ISSUE TITLE
CdkPipelines tags not propagated to Application stack

### ISSUE THREAD

**Issue by zgre** [aws/aws-cdk#13328]
I am trying to pass some tags (mandatory tagging of resources) to the application

```

app = core.App()
for key, value in get_tags(stage).items():
    core.Tag.add(app, key, value)

PipelineStack(app, f'{stack_name}-{stage}', env={
        'account': os.environ['CICD_ACCOUNT'],
        'region': 'eu-west-1',
})

```

### Reproduction Steps

When I deploy the pipeline to CICD account, resources created in CICD account are tagged. Pipeline then trigger cross-account deployment to DEV account but resource tags are missing there.

### What did you expect to happen?

Configured tags for resources also in DEV environment

### What actually happened?

No tags in DEV environment

### Environment

  - **CDK CLI Version  : 1.91.0**
  - **Framework Version:**
  - **Node.js Version:12.16.3** 
  - **OS               : CentOs**
  - **Language (Version):** Python (3.8.0)  

### Other

Another question in regards to resource naming in DEV stack. Is ti possible to omit stage.env name?

All resources are named as <stage-name>-XYZ (we have some policies to start resource names XYZ when possible)?

In our case naming is DEV-XYZ- but we would like to start with XYZ- ...

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
Aspects are not applied across Stage boundaries; you will need to apply the tags to each stage individually.

> In our case naming is DEV-XYZ- but we would like to start with XYZ- ...

Resources names are based off of the stack name. You can pass a stack name by passing `stack_name='...'` as one of the arguments to the stack constructor.

**Comment by zgre** [comment]
Did you mean something like this:

https://github.com/aws/aws-cdk/blob/4106f9d1973528ae38c765577cc8764fb199f6d8/packages/%40aws-cdk/pipelines/test/pipeline.test.ts#L412
