### ISSUE TITLE
Add  sagemaker:createTrainingJob.sync

### ISSUE THREAD

**Issue by ihorfito** [aws/aws-cdk#13325]
Please, make it possible to create
"Resource":"arn:aws:states:::sagemaker:createTrainingJob.sync"
for stepfunctions.

https://docs.aws.amazon.com/step-functions/latest/dg/connect-sagemaker.html

Currently, it is creating 
"Resource":"arn:aws:states:::sagemaker:createTrainingJob" without "sync" option

import * as tasks from '@aws-cdk/aws-stepfunctions-tasks';
new tasks.SageMakerCreateTrainingJob

**Comment by zxkane** [comment]
assign `integrationPattern` prop to  `IntegrationPattern.RUN_JOB` when you want it as sync job

**Comment by shivlaks** [comment]
@ihorfito - this is supported today. As mentioned by @zxkane , you. need to set the. `integrationPattern` property 

Here's a reference to the [documentation](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-stepfunctions-tasks.SageMakerCreateTrainingJob.html) for the `createEndpoint` API and the options for the [`integrationPattern`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-stepfunctions.IntegrationPattern.html) property.

**Comment by peterwoodworth** [comment]
This issue seems resolved
