### ISSUE TITLE
(cli) - Init template documentation generation support

### ISSUE THREAD

**Issue by smaud** [aws/aws-cdk#13320]
Support for automatic documentation of app & lib 

### Use Case

We need to reduce toil and manual documentation of stacks (READMEs and Help files in html) is toil. Autogeneration of stack and construct documentation is required.

### Proposed Solution

Please support typedoc (and similar auto generation tools) for aws-cdk stacks & components.

### Other
n/a

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by MrArnoldPalmer** [comment]
Can you clarify your use case a bit? Are you writing cdk apps/stacks/constructs that you want to document using typedoc? What prevents you from doing that currently? Can you provide an example of your code and how you're trying to build the docs site?

Or is this a request that the reference documentation for the aws-cdk itself use typedoc?

**Comment by smaud** [comment]
During **cdk init** the aws-cdk uses/provides a number of libraries and writes a number of files to disk. Eg. tsconfig.json, jest.config.js, .gitignore .npmignore.  
In alignment with the preferenced libraries/packages, preference for a documentation package (like typedoc) should be provided during the **init** process. The generated package.json should provide a script option for  **npm run doco**.

In this way the cdk can provide a recommended pathway for programmatic generation of doco, and then suggestions on how the documentation might be hosted on the AWS platform (Perhaps with Amplify or some other service).

**Comment by MrArnoldPalmer** [comment]
Got it, so init template support for some standard documentation site generation for the TS template.

**Comment by smaud** [comment]
That would make sense. 

And then perhaps as a stretch goal, some doco on how host the generated doco (perhaps using Amplify as per previous suggestion).
