### ISSUE TITLE
Mypy complaining too many issues with the latest version of cdk(1.91.0) 

### ISSUE THREAD

**Issue by Ranjith072** [aws/aws-cdk#13326]
i have been using mypy with cdk python version since 1 year i didnt have much issues with it but when i upgraded my cdk to latest version ()1.91.0) i have started to get too many errors but it turns out to be they are actually not errors 
ex:
error: Argument "api_key" to "UsagePlan" has incompatible type "ApiKey"; expected "Optional[IApiKey]" but actually the return type of ApIKey is IApiKey not sure why it is complaining now and it is happening to lot interface implementations.

renovate/aws-cdk-monorepo
![Screenshot 2021-03-01 at 14 29 21](https://user-images.githubusercontent.com/57263575/109503459-98150a00-7a9a-11eb-9103-a3fdb0842bca.png)

### Reproduction Steps

we just need to update the cdk version to 1.91.0 and run mypy we will get all the errors

### What did you expect to happen?

mypy should not complain of any errors.
### What actually happened?

mypy complaining all the implementation of @jsii.implements("") which was not happening before.

### Environment

  - **CDK CLI Version  :*1.91.0*
  - **Framework Version:**
  - **Node.js Version:*12.19.0* 
  - **OS               :*mac/linux same issues on mac and linux*
  - **Language (Version):*python3.8.6*

--- 

This is :bug: Bug Report

**Comment by MrArnoldPalmer** [comment]
hey @Ranjith072, what version of mypy are you using that throws these errors?

**Comment by Ranjith072** [comment]
Hi @MrArnoldPalmer ,
i am using mypy==0.790 version.

**Comment by RomainMuller** [comment]
Do you still have the issue with the most recent release of `mypy` (`0.812` at time of writing)?

**Comment by Ranjith072** [comment]
HI @RomainMuller   i have tried with mypy version mypy==0.812 as well and i got the same issue.

**Comment by jkrukoff-tiaa** [comment]
I'm seeing this same issue across our codebase with either of CDK version 1.90 or 1.91. We did not have the same issue with CDK version 1.89.

Example of error in one of our stacks:

```
cdk/child/child.py:158: error: Argument 1 to "append" of "list" has incompatible type "ManagedPolicy"; expected "IManagedPolicy"
cdk/child/child.py:158: note: Following member(s) of "ManagedPolicy" have conflicts:
cdk/child/child.py:158: note:     Expected:
cdk/child/child.py:158: note:         def __jsii_proxy_class__() -> Type[_IManagedPolicyProxy]
cdk/child/child.py:158: note:     Got:
cdk/child/child.py:158: note:         def __jsii_proxy_class__() -> Type[_ResourceProxy]
cdk/child/child.py:165: error: Argument "assumed_by" to "Role" has incompatible type "ServicePrincipal"; expected "IPrincipal"
cdk/child/child.py:165: note: Following member(s) of "ServicePrincipal" have conflicts:
cdk/child/child.py:165: note:     Expected:
cdk/child/child.py:165: note:         def __jsii_proxy_class__() -> Type[_IPrincipalProxy]
cdk/child/child.py:165: note:     Got:
cdk/child/child.py:165: note:         def __jsii_proxy_class__() -> Type[_PrincipalBaseProxy]
cdk/child/child.py:176: error: Argument "assumed_by" to "Role" has incompatible type "ServicePrincipal"; expected "IPrincipal"
cdk/child/child.py:176: note: Following member(s) of "ServicePrincipal" have conflicts:
cdk/child/child.py:176: note:     Expected:
cdk/child/child.py:176: note:         def __jsii_proxy_class__() -> Type[_IPrincipalProxy]
cdk/child/child.py:176: note:     Got:
cdk/child/child.py:176: note:         def __jsii_proxy_class__() -> Type[_PrincipalBaseProxy]
```

I started down the path of ignoring these errors but issue was so widespread I'm just reverting to 1.89. If it persists, I'll likely be ripping mypy out of my CI pipeline and writing off the CDK type information as busted.

**Comment by jkrukoff-tiaa** [comment]
I should probably note that we're running mypy 0.812:

```
$ mypy --version
mypy 0.812
```
