### ISSUE TITLE
(dynamodb): support continuous backups

### ISSUE THREAD

**Issue by bigkraig** [aws/aws-cdk#13333]
CloudFormation is missing support for configuring continuous backups, but CDK should be able to work around it.

https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_UpdateContinuousBackups.html

### Use Case

point in time recovery

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by peterwoodworth** [comment]
Thanks for letting us know @nikp !
