### ISSUE TITLE
eks node group role access?

### ISSUE THREAD

**Issue by priteshwatch** [aws/aws-cdk#13336]
When a new EKS Cluster is created, it looks like it creates nodegroup roles for you. 
Example: play-shared-eks-1-stack-playsharedeks1Nodegrouppla-60GKW78USA05

How do I get access to it? I would like to add the CloudWatchAgentServerPolicy Managed policy to it, so that I can get cloudwatch logging to work.

This does not work.

    mainCluster.getDefaultNodegroup().getRole().addManagedPolicy(
        ManagedPolicy.fromAwsManagedPolicyName("CloudWatchAgentServerPolicy"));

Thank you

**Comment by priteshwatch** [comment]
I found this ticket https://github.com/aws/aws-cdk/issues/9898 however, i cannot figure out how to get access to the default service account.

**Comment by iliapolo** [comment]
@priteshwatch 

> i cannot figure out how to get access to the default service account.

There is no default service account. The issue you mention refers to adding managed policies to service accounts explicitly created with `cluster.addServiceAccount`.

The code you pasted should properly add the policy to the node group roles. What exactly do you mean by "This does not work"? Are you getting an error?

**Comment by priteshwatch** [comment]
Hmm. I absolutely have no idea it did not work first time around. Turns out after couple days of research, i decided to try it again this morning and it worked. Thank you once again and sorry about wasting your time.
