### ISSUE TITLE
Github now uses main instead of master

### ISSUE THREAD

**Issue by OksanaH** [aws/aws-cdk#13335]
I was using CDKPipelines to create a CodePipeline with BitbucketAction (using a Github repo with one 'main' branch as the source, created by default when I created the repo), and did not specify a branch to pull from. I noticed when the action execution failed there was a message in the console 'No branch [master] found for the repository'. It looks like Github uses 'main' instead of 'master' now, so that error message probably needs changing? Where is the best place to report this issue if this is not relevant here (I imagine it is a Codebuild issue)?

**Comment by skinny85** [comment]
Hi @OksanaH ,

actually, it _is_ an issue with the `BitbucketAction`, as it defaults to `master` [here](https://github.com/aws/aws-cdk/blob/b3197db1c87067231b0642b7f9e1e37a48b12b6d/packages/%40aws-cdk/aws-codepipeline-actions/lib/bitbucket/source-action.ts#L123-L123).

Unfortunately, this is not really a default we can change now - although when we introduce a better-named Action for this, something like `CodeStarConnectAction`, we can revisit this decision.

Same problem is present with `GitHubSourceAction`, `CodeCommitSourceAction`, etc.

**Comment by rix0rrr** [comment]
We're in a bit of a pickle in that:

* Even though `main` is the new default in most code repositories, many people will still be on old repositories that were created when `master` was the default.
* If we change the default value, all existing infrastructure that happily uses `master` today will break if they upgrade CDK versions (as they will be implicitly switched to `main`)

**Comment by skinny85** [comment]
I'm actually debating whether we should make `branch` required in V2 for all these Actions.

I feel like a feature flag is actually a pretty bad experience for this change, since it doesn't matter when you created the CDK application, it matters when the repository you're using as a source was created, and that can be much earlier than your CDK application. So, if you create a new CDK application , and it suddenly defaults to `main`, it's pretty irritating if you're using it with an old repository that's still on `master`.

We can then make the `branch` property in V2 optional again after enough time has passed, and the transition from `main` to `master` can be considered complete.

**Comment by OksanaH** [comment]
I like the idea of making the branch required.

**Comment by skinny85** [comment]
@OksanaH if you're willing to work on this, that would be amazing!

Note that, since this is a change only in V2, the submitted PR would have to target the `v2-main` branch, **not** the current default of this repository, `master`.

Let me know if you're still interested in working on this!

**Comment by OksanaH** [comment]
@skinny85 sure I'm going to have a go! Just to double check since there's been conversation about feature flags as well - I need to make the branch name required, right?

**Comment by skinny85** [comment]
Let's go with the "make `branch` required" plan for now, yes.

**Comment by skinny85** [comment]
And thanks!

**Comment by OksanaH** [comment]
@skinny85 so, I've switched to v2-main, and I'm getting an error ` Unable to locate jsii assembly for "@aws-cdk/aws-cloudformation". If this module is not jsii-enabled, it must also be declared under bundledDependencies`, when I try to buildup or run `yarn build`.  I've also tried to run some commands from the Troubleshooting section of the Contributing.MD document. Any idea what I might be doing wrong or is there anything that needs to be done differently for `v2-main` (I work in Gitpod, and have tried using an existing space, and creating a new space)? 
Thanks

**Comment by skinny85** [comment]
Did you run `yarn install --frozen-lockfile` after switching to `v2-main`?

**Comment by OksanaH** [comment]
@skinny85 I ran `yarn install --frozen-lockfile` and after that if I run `scripts/buildup` from a module folder or `scripts/foreach.sh yarn build` from the root, I get this error during the build of `lambda-layer-awscli`: `OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: write sysctl key net.ipv4.ip_unprivileged_port_start: open /proc/sys/net/ipv4/ip_unprivileged_port_start: read-only file system: unknown`. Thanks

**Comment by skinny85** [comment]
@OksanaH I think that might be because `lambda-layer-awscli` uses Docker, which is tricky to make work in Gitpod - see here: https://github.com/gitpod-io/gitpod/issues/52#issuecomment-738629624 on how to start the Docker demon inside your Gitpod workspace.

if that's too difficult/doesn't work for some reason, you can also use Lerna with the `--no-bail` switch to "simulate" the `buildup` script. Execute something like this in the root of the CDK workspace:

```
$ ./node_modules/.bin/lerna run --stream build --include-dependencies --no-bail --scope @aws-cdk/aws-codepipeline
```

(Replace `@aws-cdk/aws-codepipeline` with whatever module you were running `buildup` from)

Let me know if this helps!

Thanks,
Adam

**Comment by OksanaH** [comment]
Hi @skinny85, thanks for the suggestion; when I run the above command, no errors are thrown, but then the same error persists when I try to build the `aws-codepipeline-actions`  module: `Unable to locate jsii assembly for "@aws-cdk/aws-cloudformation". If this module is not jsii-enabled, it must also be declared under bundledDependencies`.
I've also tried VSCode but there I get a different error when I try to do the buildup of `aws-codepipeline-actions` or `yarn build` after having run `yarn install --frozen-lockfile`: `\node_modules\jsii\bin\jsii' is not recognized as an internal or external command, 
operable program or batch file`

It looks both errors happen when [this ](https://github.com/aws/aws-cdk/blob/ded111fc03402d1d2ebaa16e393d11abe77d10cb/tools/cdk-build-tools/lib/package-info.ts#L104 ) is run.

Thanks,
Oksana

**Comment by skinny85** [comment]
> Hi @skinny85, thanks for the suggestion; when I run the above command, no errors are thrown, but then the same error persists when I try to build the `aws-codepipeline-actions` module:

Did you switch `@aws-cdk/aws-codepipeline` to `@aws-cdk/aws-codepipeline-actions` in the above command I gave?

```shell
$ ./node_modules/.bin/lerna run --stream build --include-dependencies --no-bail --scope @aws-cdk/aws-codepipeline-actions
```

**Comment by OksanaH** [comment]
@skinny85 yes I did. Am getting the same error now about unprivileged port start.

**Comment by skinny85** [comment]
Hmm, you're right, I was just able to reproduce this...

I see you asked https://community.gitpod.io/t/docker-inside-gitpod/3688/2, I've commented there as well - let's see what they say.

**Comment by Sabin-K-Lama** [comment]
[GitHub] No Branch [master] found for FullRepositoryName even though there is master branch
