### ISSUE TITLE
toolkit: --rename is superficial

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#1333]
When using the `--rename` option in the toolkit, the stack rename only happens at the toolkit level and not inside the app. This means that `uniqueId`s and `path`s would still be based on the original name, and this might break when we rely on these for global-uniqueness (contrary to logical IDs which are stack-unique).

See example #1331

**Comment by RomainMuller** [comment]
If we are to keep the rename mechanism, it definitely needs to somehow pass into the synthesizer, otherwise it is also way too easy to forgot to apply renames in tooling.

**Comment by eladb** [comment]
--rename no longer exists
