### ISSUE TITLE
(deploy): cdk deploy breaks when qualifier is used

### ISSUE THREAD

**Issue by naveenkoppula** [aws/aws-cdk#13358]
### Reproduction Steps

1. ``` cdk bootstrap aws://XXXXXXXXXXXX/ca-central-1 --require-approval never --toolkit-stack-name=CustomQual-CDKToolkit --cloudformation-execution-policies=arn:aws:iam::aws:policy/AdministratorAccess --qualifier=customqual ```
2. ``` cdk deploy --require-approval never --toolkit-stack-name=CustomQual-CDKToolkit ```
3. Did provide ``` synthesizer: new cdk.DefaultStackSynthesizer({
      qualifier,
generateBootstrapVersionRule: false,
}) ``` to StackProps while initiating

Able to create CloudFormationChange set and got following request details from CloudTrail

``` 
{
        "roleARN": "arn:aws:iam::XXXXXXXXXXXX:role/cdk-customqual-cfn-exec-role-XXXXXXXXXXXX-ca-central-1",
        "capabilities": [
            "CAPABILITY_IAM",
            "CAPABILITY_NAMED_IAM",
            "CAPABILITY_AUTO_EXPAND"
        ],
        "changeSetName": "CDK-f762ff10-97e2-4b42-a180-fe9be3b969be",
        "stackName": "CustomQual-Deploy",
        "parameters": [],
        "templateURL": "https://s3.ca-central-1.amazonaws.com/cdk-customqual-assets-XXXXXXXXXXXX-ca-central-1/fb4ee5f37388eea78bb4a2d77535c86d316a00ad5498c06951cbde2f356e0d5b",
        "description": "CDK Changeset for execution f762ff10-97e2-4b42-a180-fe9be3b969be"
    }
```

We can see "roleARN" provided for creating changeset is correct with respect to the qualifier, But the creation of changeSet fails after 20 mins with the following error

``` 

❌  CustomQual-Deploy failed: Error: Failed to create ChangeSet CDK-f762ff10-97e2-4b42-a180-fe9be3b969be on CustomQual-Deploy: FAILED, Role arn:aws:iam::XXXXXXXXXXXX:role/cdk-hnb659fds-cfn-exec-role-XXXXXXXXXXXX-ca-central-1 is invalid or cannot be assumed

--

```

### Environment

  - **CDK CLI Version  :** 1.85.0
  - **Framework Version:** 1.85.0
  - **Node.js Version:** v12.16.1
  - **OS               :** MacOs, Linux
  - **Language (Version):** TypeScript (3.8.3)

### Other

❌  CustomQual-Deploy failed: Error: Failed to create ChangeSet CDK-4c47b26b-527b-4939-90e2-13d82aa666dc on CustomQual-Deploy: FAILED, Role arn:aws:iam::XXXXXXXXXXXX:role/cdk-hnb659fds-cfn-exec-role-XXXXXXXXXXXX-ca-central-1 is invalid or cannot be assumed
    at /Users/xxxxx/cdk-workspace/xxxxx/node_modules/.pnpm/aws-cdk@1.85.0/node_modules/aws-cdk/lib/api/util/cloudformation.js:209:15
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at waitFor (/Users/xxxxx/cdk-workspace/xxxxx/node_modules/.pnpm/aws-cdk@1.85.0/node_modules/aws-cdk/lib/api/util/cloudformation.js:172:24)
    at Object.waitForChangeSet (/Users/xxxxx/cdk-workspace/xxxxx/node_modules/.pnpm/aws-cdk@1.85.0/node_modules/aws-cdk/lib/api/util/cloudformation.js:197:17)
    at Object.deployStack (/Users/xxxxx/cdk-workspace/xxxxx/node_modules/.pnpm/aws-cdk@1.85.0/node_modules/aws-cdk/lib/api/deploy-stack.js:90:34)
    at CdkToolkit.deploy (/Users/xxxxx/cdk-workspace/xxxxx/node_modules/.pnpm/aws-cdk@1.85.0/node_modules/aws-cdk/lib/cdk-toolkit.js:121:32)
    at initCommandLine (/Users/xxxxx/cdk-workspace/xxxxx/node_modules/.pnpm/aws-cdk@1.85.0/node_modules/aws-cdk/bin/cdk.js:186:15)
Failed to create ChangeSet CDK-4c47b26b-527b-4939-90e2-13d82aa666dc on CustomQual-Deploy: FAILED, Role arn:aws:iam::XXXXXXXXXXXX:role/cdk-hnb659fds-cfn-exec-role-XXXXXXXXXXXXX-ca-central-1 is invalid or cannot be assumed

--- 

This is :bug: Bug Report

**Comment by Brian969** [comment]
@rix0rrr - any timeline on when you can assess? you'll be able to fix?  THANKS!

**Comment by rix0rrr** [comment]
Can you have a look at `cdk.out/manifest.json` (and/or `cdk.out/assembly-*/manifest.json`) and see what `cfn-exec-role` is referenced in there?

**Comment by rix0rrr** [comment]
Also -- is this perhaps an Update to a Stack which was previously deployed using a bootstrap stack with the default qualifier?

**Comment by rix0rrr** [comment]
If that is the issue, use the CloudFormation console to change the role that's currently associated with the stack first.

**Comment by naveenkoppula** [comment]
> Also -- is this perhaps an Update to a Stack which was previously deployed using a bootstrap stack with the default qualifier?
> 
> Given that the RoleARN passed to the API request is correct, I don't see where else CloudFormation would try to get the "old" role from. It probably remembered it from the previous deploy.

Yes. That is update from default qualifier.

I can try new once if that won't cause any issue

**Comment by naveenkoppula** [comment]
> Also -- is this perhaps an Update to a Stack which was previously deployed using a bootstrap stack with the default qualifier?
> 
> Given that the RoleARN passed to the API request is correct, I don't see where else CloudFormation would try to get the "old" role from. It probably remembered it from the previous deploy.

Got same issue for new Account synth and deploy

**Comment by Brian969** [comment]
@rix0rrr

**Comment by Brian969** [comment]
@rix0rrr
