### ISSUE TITLE
(aws-ec2): no support for nitroEnclaveEnabled as option of InstanceProps

### ISSUE THREAD

**Issue by allthatjazzleo** [aws/aws-cdk#13359]
No support for nitroEnclaveEnabled as option of InstanceProps

https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-ec2/lib/instance.ts
### Use Case

https://aws.amazon.com/ec2/nitro/nitro-enclaves/

**Comment by digitwolf** [comment]
I think this issue still exists. Please add the nitro option. It is impossible to start EC2 instance with Nitro using CDK
