### ISSUE TITLE
[aws-ecs] TaskDefinition that uses cross account ECR repository image throws an error

### ISSUE THREAD

**Issue by garyd203** [aws/aws-cdk#13360]
On v1.60.0 (and current latest release v.1.90.1 too), a TaskDefinition that uses a cross account ECR repository image has multiple related problems:

1. The internally generated execution role for the task definition does not have `role_name=PhysicalName.GENERATE_IF_NEEDED` set, meaning that it can't be referenced by the repository policy for the target ECR repository in the other account/stack.
2. The Repository policy generated for the ECR repository uses the IAM role in the other account as the principal in the policy statement. This makes it impossible to deploy the resulting CDK application, since the ECR stack depends implicitly on the IAM role in the ECS task stack, which is used by the ECS Task Definition, which depends on the ECR repository in the ECR stack.

These issues are fully described in #10233, so I won't reproduce the description and discussion here. Given that other ticket was closed by a bot without the bug actually being fixed, can you please fix the bug so that this CDK construct will work out of the box.

--- 

This is :bug: Bug Report

**Comment by SoManyHs** [comment]
Reopened https://github.com/aws/aws-cdk/issues/10233, closing this as duplicate.
