### ISSUE TITLE
(ecs-patterns): Add task role parameter to ScheduledFargateTaskImageOptions

### ISSUE THREAD

**Issue by scottenriquez** [aws/aws-cdk#13377]
Using the [`ScheduledFargateTask`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs-patterns.ScheduledFargateTask.html) construct requires passing in either [`ScheduledFargateTaskDefinitionOptions`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs-patterns.ScheduledFargateTaskDefinitionOptions.html) or [`ScheduledFargateTaskImageOptions`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs-patterns.ScheduledFargateTaskImageOptions.html). `ScheduledFargateTaskImageOptions` requires much less configuration than instantiating a [`FargateTaskDefinition`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs.FargateTaskDefinition.html) construct for `ScheduledFargateTaskDefinitionOptions`. However, `ScheduledFargateTaskImageOptions` does not have a parameter for a task role which severely limits its use cases.

### Use Case
Without the ability to pass in a task role, there's not a good way to consume other AWS services (other than passing in credentials via [`Secret`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs.Secret.html) which is obviously not a good practice). Note that there is a workaround by using `ScheduledFargateTaskDefinitionOptions`, but utilizing an IAM role seems like a very common requirement.

### Proposed Solution
Update `ScheduledFargateTaskImageOptions` to have a `taskRole` parameter and use the role when creating the underlying task definition.

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by SoManyHs** [comment]
Related: https://github.com/aws/aws-cdk/issues/9094
