### ISSUE TITLE
(aws-apigatewayv2): AWS service integrations L2 support for HTTP APIs

### ISSUE THREAD

**Issue by zxkane** [aws/aws-cdk#13374]
Working with AWS service integrations for HTTP APIs

https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-aws-services.html

### Use Case

Start/stop executions of stepfunctions without introducing lambda. 

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by nija-at** [comment]
We have an issue to support EventBridge here - https://github.com/aws/aws-cdk/issues/11947

Similarly, can you open individual issues for the specific integration you'd like to see. It would help us track them separately rather an umbrella issue.

Thanks!
