### ISSUE TITLE
(stepfunctions-tasks): configure Managed Scaling Policy in EmrCreateCluster task

### ISSUE THREAD

**Issue by shivlaks** [aws/aws-cdk#13376]
The [ManagedScalingPolicy](https://docs.aws.amazon.com/emr/latest/APIReference/API_RunJobFlow.html#EMR-RunJobFlow-request-ManagedScalingPolicy) for an EMR cluster is not currently configurable as a part of the `EmrCreateCluster` task.

It was also added recently in the CloudFormation resource specification [v20.0.0](https://github.com/aws/aws-cdk/issues/11319)

### Use Case

Parity with the EMR `RunJobFlow` API

### Proposed Solution

introduce the `ManagedScalingPolicy` property in `EmrCreateCluster` class in `stepfunctions-tasks`

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by christiandietze** [comment]
We made it work with the following code snippet:
```
class EmrCreateClusterWithManagedScaling extends EmrCreateCluster {
    protected _renderTask(): any {
        const baseObject = super._renderTask();
        return {
            ...baseObject, Parameters: {
                ...baseObject.Parameters, ManagedScalingPolicy: {
                    ComputeLimits: {
                        MaximumCapacityUnits: 10,
                        MinimumCapacityUnits: 1,
                        UnitType: 'InstanceFleetUnits'
                    }
                }
            }
        };
    }
}
```

👍  for the Feature request, so that we can remove the workaround.
