### ISSUE TITLE
(pipelines): allow docker buildArgs to be evaluated at runtime

### ISSUE THREAD

**Issue by JFox** [aws/aws-cdk#13375]
Currently when using DockerImageAsset buildArgs under a CDK Pipeline, the assets step translates these args using quotes so the values are passed explicitly without any evaluation or replacement.

This is fine for most cases, but sometimes it is needed to evaluate, for example, environment variables that are only present during the pipeline execution

### Use Case

```javascript
const appEcrImage = ContainerImage.fromAsset(
  path.join(process.cwd(), "app"),
  {
    buildArgs: {
      SOME_VAR: "${CODEBUILD_RESOLVED_SOURCE_VERSION}",
    },
  },
);
```

That code generates a DockerAsset action inside the pipeline that internally executes `docker build --build-arg 'SOME_VAR=${CODEBUILD_RESOLVED_SOURCE_VERSION}' --tag <cdkasset-hash> .`.

The problem here is that the value of the env var is not replaced and passed as a literal `${CODEBUILD_RESOLVED_SOURCE_VERSION}` to the docker build execution instead of the value. This caused by the single quotes surrounding the build arg definition.

### Proposed Solution

Maybe something better could be proposed, but I guess a flag that allows us to indicate that the quotation shouldn't be done and that makes the command parameter to be `--build-arg SOME_VAR=${CODEBUILD_RESOLVED_SOURCE_VERSION}` (notice the absence of the quotes)

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by JFox** [comment]
Just in case someone ends up here trying to get a workaround you can do this:

```javascript
const appEcrImage = ContainerImage.fromAsset(
  path.join(process.cwd(), "app"),
  {
    buildArgs: {
      SOME_VAR: this.node.tryGetContext("SOURCE_VERSION"),
    },
  },
);
```
and then on your CDK pipeline synth action add `--context SOURCE_VERSION=$CODEBUILD_RESOLVED_SOURCE_VERSION`

**Comment by eladb** [comment]
Reassigning to @rix0rrr for CDK pipelines.

**Comment by rix0rrr** [comment]
> and then on your CDK pipeline synth action add `--context SOURCE_VERSION=$CODEBUILD_RESOLVED_SOURCE_VERSION`

You could probably also do:

```ts
const appEcrImage = ContainerImage.fromAsset(
  path.join(process.cwd(), "app"),
  {
    buildArgs: {
      SOME_VAR: process.env.CODEBUILD_RESOLVED_SOURCE_VERSION,
    },
  },
);
```

**Comment by rix0rrr** [comment]
I'm not inclined to change anything upstream. There is a workaround and it's arguably more idiomatic CDK to put as many decisions as possible into code.
