### ISSUE TITLE
(Lambda): Support for blueprints

### ISSUE THREAD

**Issue by radu-malliu** [aws/aws-cdk#13384]
Deploy Lambda functions from blueprints through TypeScript CDK.

### Use Case

The Lambda console supports clicking "use a blueprint" on the Lambda create function workflow and choosing from a set of ready code files to use as the Lambda source code. The CDK equivalent for TypeScript is not available.

The objective is not to manage the function code via CDK, just to be able to deploy a function via CDK exactly as it gets generated from the blueprint. There are cases where a function as generated from the blueprint can be useful without further modification.

### Proposed Solution

Ideally, instead of having to copy over the code and be responsible for maintaining and testing it, developers would be able to leverage the blueprints available in the Lambda console by doing something similar to the following:

```
import * as lambda from 'monocdk/aws-lambda';

const blueprint = lambda.Blueprint.fromName('kinesis-firehose-cloudwatch-logs-processor');
const lambda = new Function(this, 'ProcessorLambda', {
  code: blueprint.code,
  handler: blueprint.handler,
  runtime: blueprint.runtime
});

// alternatively
const lambda = new Function(this, 'ProcessorLambda', {
  code: lambda.Code.fromBlueprint('kinesis-firehose-cloudwatch-logs-processor'),
  handler: 'index.handler',
  runtime: lambda.Runtime.NODEJS_12_X
});
```

### Other

N/A

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by NetaNir** [comment]
We had a very similar suggestion for the `aws-synthetics` module, see [issue])(https://github.com/aws/aws-cdk/issues/9613) . I think a good next step is to open an issue in the [AWS-CDK-RFC](https://github.com/aws/aws-cdk-rfcs) repo.

**Comment by nija-at** [comment]
This is now something we want to do in the CDK, and is in fact, opposite of how we want CDK code to be managed.

Instead, we have the concept of 'constructs'. Any 'blueprint' you'd like to encode will be modeled as a construct. 

While we don't plan to ship these as part of the AWS CDK packages, we encourage our customers to publish their own CDK constructs with these abstractions and many more. 
See our construct catalog for the all of our community managed options - https://awscdk.io/
