### ISSUE TITLE
(core): feature flag values inconsistent in default cdk.json, features.ts

### ISSUE THREAD

**Issue by Jerry-AWS** [aws/aws-cdk#13382]
Some feature flags have a value of `"true"` while others have a value of `true`. Either works, although if a customer wants to temporarily disable a flag, changing it to `"false"` will actually leave the feature flag enabled since `"false"` is a non-zero-length string.

Suggest changing these all to proper Boolean values to avoid possibly leading customers into making an error.

Should also scrub the READMEs for places where we talk about feature flags to make sure we use Booleans there, too. (Already fixed Developer Guide.)

I can put together a PR for this if it is confirmed to be a bug.

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
You are right, this would be a good thing to do.

**Comment by Jerry-AWS** [comment]
@rix0rrr I'll probably get to a PR some time next week.
