### ISSUE TITLE
(secretsmanager): db password rotation does not work in other partitions

### ISSUE THREAD

**Issue by zxkane** [aws/aws-cdk#13385]
The rotation feat is implemented by a SAR app that is NOT available in other partitions, such as `aws-cn`.

It impacts all RDS, Aurora and DocDB.

### Reproduction Steps

Deploying a CDK app with DocDB with rotation password, the deployment failed with below error,

```
Embedded stack arn:aws-cn:cloudformation:cn-northwest-1:xxx:stack/fraud-detection-dashboardNestedStackdashboardNestedStackResourceB80305B3-ZM4BVGTZU82L/81befa20-7c40-11eb-84bf-0665999c0414 was not successfully created: Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [DashboardDatabaseRotationSingleUser0EB18E12] is invalid. User: arn:aws-cn:sts::xxx:assumed-role/Admin/mengxinz-Isengard is not authorized to perform: serverlessrepo:CreateCloudFormationTemplate on resource: arn:aws:serverlessrepo:us-east-1:297356227824:applications/SecretsManagerMongoDBRotationSingleUser
```

### Environment

  - **CDK CLI Version  :** 1.91.0
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):** 

### Other

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment]
Effort here is `large` since i'm not sure what it would take to enable the SAR application in the `aws-cn` region, or alternatively, what would it take to not use it. So its more of an `unknown` effort.

**Comment by zxkane** [comment]
Is there any particular reason to use SAR here? It makes the maintenance of SAR app is out of CDK. 

Like `kubectl` it's updated to lambda layer instead of SAR. The NodejsFunc/PythonFunc is mature to replace the SAR app.

**Comment by zxkane** [comment]
@iliapolo Eli, the password rotation SAR apps are available in China regions. How about creating internal mapping for those SAR apps? If you think so, I will submit PR to fix it.

**Comment by iliapolo** [comment]
@zxkane I think that's probably the most pragmatic thing to do here. @njlynch What do you think?

**Comment by njlynch** [comment]
That sounds reasonable to me. Thanks for the report and suggestion, @zxkane !
