### ISSUE TITLE
cloudfront: Failed to forward Authorization header from cloudfront to API Gateway

### ISSUE THREAD

**Issue by apoorvmote** [aws/aws-cdk#13408]
I am using distribution HTTP API with cloudfront. And I want to pass `Authorization` header from cloudfront to HTTP API lambda authorizer. And I am not able to whitelist any header from cloudfront.

### Reproduction Steps

In brand new CDK Projest just create the following policy 
```ts
    new OriginRequestPolicy(this, 'testOriginPolicy', {
      cookieBehavior: OriginRequestCookieBehavior.all(),
      headerBehavior: OriginRequestHeaderBehavior.allowList('Authorization'),
      queryStringBehavior: OriginRequestQueryStringBehavior.all()
    })
```
### What did you expect to happen?

I expcted to successfully deploy the origin policy. I haven't even attached to cloudfront distribution yet.
### What actually happened?

The deploy fails with following error
```bash
Invalid request provided: AWS::CloudFront::OriginRequestPolicy
The following resource(s) failed to create: [testOriginPolicyBBC7F32C].
```

### Environment

  - **CDK CLI Version  :** 1.91.0 
  - **Framework Version:**
  - **Node.js Version:**  v14.16.0
  - **OS               :** Ubuntu 20.04 on WSL2 
  - **Language (Version):**  Typescript ~3.9.7

### Other

--- 

This is :bug: Bug Report

**Comment by robertd** [comment]
@apoorvmote You can't pass `Authorization` header behavior when creating `OriginRequestPolicy`. I'd suggest using `CachePolicy` instead if you need to pass auth header (see links below). 

![image](https://user-images.githubusercontent.com/31543/110070046-586a4e80-7d36-11eb-92f2-2fad3b67460b.png)

See these references for more info:

- https://aws.amazon.com/premiumsupport/knowledge-center/cloudfront-authorization-header/
- https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/571

**Comment by robertd** [comment]
@njlynch I couldn't really find in docs anywhere that `Authorization` header is not allowed when creating `OriginRequestPolicy`. Should we sanitize `OriginRequestHeaderBehavior` just in case so users don't find this out the hard way during deployment?... just to be on the safe side

**Comment by robertd** [comment]
@njlynch  `Accept-Encoding` is also not allowed...
![image](https://user-images.githubusercontent.com/31543/110070861-22c66500-7d38-11eb-8f6e-1897db9fbe5a.png)

And I found out there is limitation on how many headers you can pass (total of 10).

![image](https://user-images.githubusercontent.com/31543/110070946-53a69a00-7d38-11eb-8943-46c9503dd4d6.png)

AFAIK... none of this is captured anywhere in `OriginRequestPolicy` docs. Should we sanitize/check all this when creating `OriginRequestPolicy` resource for better user experience?

**Comment by apoorvmote** [comment]
@robertd Thanks very much for quick reply. I though I had to wait many days before anyone will take a look at it.

I would like help setting Cache Policy because its for API endpoint I have been using static `CachePolicy.CACHING_DISABLED`

Now to allow Headers I need to recreate the `CACHING_DISABLED` and add whitelist for header.

I was working on workaround. Instead of passing token through header I was going to pass it through body.

https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-apigatewayv2-authorizers.UserPoolAuthorizerProps.html#identitysourcespan-classapi-icon-api-icon-experimental-titlethis-api-element-is-experimental-it-may-change-without-noticespan

Changing `identitySource` from `$request.header.Authorization` to `$request.body.Authorization`

Is there any security concern by passing token via body? or I MUST pass token via header?

**Comment by njlynch** [comment]
> I would like help setting Cache Policy because its for API endpoint I have been using static CachePolicy.CACHING_DISABLED. Now to allow Headers I need to recreate the CACHING_DISABLED and add whitelist for header.

This is actually reasonably straightforward. Simply create a new CachePolicy with 0s for all TTLs, and add the header policy. Then use this new cache policy with your distribution.

```ts
const cachePolicy = new cloudfront.CachePolicy(stack, 'CachingDisabledButWithAuth', {
  defaultTtl: Duration.minutes(0),
  minTtl: Duration.minutes(0),
  maxTtl: Duration.minutes(0),
  headerBehavior: cloudfront.CacheHeaderBehavior.allowList('Authorization'),
});
```

**Comment by bblanke** [comment]
Quick addition to @njlynch 's response. I had to set at least 1 of the TTL's to something in order to create the cache policy, so I set max TTL to 1 second:

```
const cachePolicy = new cloudfront.CachePolicy(stack, 'CachingDisabledButWithAuth', {
  defaultTtl: Duration.minutes(0),
  minTtl: Duration.minutes(0),
  maxTtl: Duration.minutes(1),
  headerBehavior: cloudfront.CacheHeaderBehavior.allowList('Authorization'),
});
```

**Comment by ischia-exigenter** [comment]
> Quick addition to @njlynch 's response. I had to set at least 1 of the TTL's to something in order to create the cache policy, so I set max TTL to 1 second:
> 
> ```ts
> const cachePolicy = new cloudfront.CachePolicy(stack, 'CachingDisabledButWithAuth', {
>   defaultTtl: Duration.minutes(0),
>   minTtl: Duration.minutes(0),
>   maxTtl: Duration.minutes(1),
>   headerBehavior: cloudfront.CacheHeaderBehavior.allowList('Authorization'),
> });
> ```

Seeing the same issue, and it happens if you try to create a stand-alone cache policy in the AWS Console. You get the annoying error: "The parameter HeaderBehavior is invalid for policy with caching disabled."

However, if you manually modify caching on a CloudFront distribution, somehow AWS Console allows it. So "yes, we want caching disabled, and YES we want to pass an API Token, or other authorization header to the API Gateway!!"
