### ISSUE TITLE
Code Pipeline does not expose grant methods for management API calls.

### ISSUE THREAD

**Issue by sam-goodwin** [aws/aws-cdk#1340]
The only grant methods exposed on the Code Pipeline construct are `grantBucketRead` and `grantBucketReadWrite`. We should add grants for operations such as `GetPipeline` and `GetPipelineState` for workers who need to monitor or control the pipeline directly.

Pipeline permission reference: https://docs.aws.amazon.com/codepipeline/latest/userguide/permissions-reference.html

**Comment by sam-goodwin** [comment]
Perhaps we need something like `grantRead` and `grantWrite` for the pipeline and its stages themselves?

**Comment by eladb** [comment]
Even if we don't explicitly expose grant methods for every API, at least a generic `grant` method should be there as a fallback.

**Comment by skinny85** [comment]
Still relevant.
