### ISSUE TITLE
(@aws-cdk/aws-lambda-event-sources): Can't install

### ISSUE THREAD

**Issue by bestickley** [aws/aws-cdk#13402]
When I try and run `npm i @aws-cdk/aws-lambda-event-sources` I get the error:
```
❯ npm i @aws-cdk/aws-lambda-event-sources
npm ERR! code ERESOLVE
npm ERR! Cannot destructure property 'name' of 'node' as it is null.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/stickb/.npm/_logs/2021-03-04T19_25_28_605Z-debug.log
```

### Reproduction Steps

`npm i @aws-cdk/aws-lambda-event-sources`
### What did you expect to happen?

Proper install
### What actually happened?

Error

### Environment

  - **CDK CLI Version:** 1.91.0
  - **Framework Version:** 1.89.0
  - **Node.js Version:** 14.15.4 
  - **NPM Version"** 7.6.0
  - **OS               :** MacOS
  - **Language (Version):** TypeScript 4.1

### Other
When I ran `npm i @aws-cdk/aws-lambda-event-sources --legacy-peer-deps` it worked but then I got type errors.

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
This specifically occurs on npm@7 with their [new feature to auto-install peer dependencies](https://github.blog/2020-10-13-presenting-v7-0-0-of-the-npm-cli/).

When you run `npm i @aws-cdk/aws-lambda-event-sources`, `npm` automatically defaults to the latest version of this package. Around the time you opened this issue, this likely would've been `1.92.0`.
Based on the *Environment* section you've filled out, your `package.json` likely contained CDK package dependencies `1.89.0`.

We're using peer dependencies to explicitly notify you that all CDK dependencies must be aligned to the same version. Using different versions of CDK modules in the same project can lead to unexpected behaviour and compatibility issues. We're using the peer dependencies mechanism to prevent this. 
Until `npm@6`, these were warnings during installation but starting `npm@7`, these have turned into errors. But we do apologize for the vague error message. 

The correct way to do this would be to run `npm i @aws-cdk/aws-lambda-event-sources@1.89.0` which should succeed.

In the coming months, we plan to release CDKv2 which will come with [monopackaging](https://github.com/aws/aws-cdk-rfcs/blob/master/text/0006-monolothic-packaging.md), which will solve the version alignment problem.

**Comment by bestickley** [comment]
Thank you, @nija-at! I look forward to the CDKv2 :)
