### ISSUE TITLE
Role.addToPolicy(...) introduces cyclic dependency

### ISSUE THREAD

**Issue by alex-berger** [aws/aws-cdk#1341]
The following line in IAM `Role`'s `addToPolicy(statement: PolicyStatement)` method can introduce cyclic dependencies in the generated CloudFormation template. 

https://github.com/awslabs/aws-cdk/blob/2625a055f4d2c8a3419cb379ee5b1b4234976c53/packages/%40aws-cdk/aws-iam/lib/role.ts#L164

This happens if a `PolicyStatement` added to the `DefaultPolicy` references a resource (e.g. a `LambdaFunction`) which in turn references the `Role`. So, we end up with a cycle that looks like this:

`LambdaFunction (a)` → `Role (b)` ← `Policy (c)` ↔ `LambdaFunction (a)`

Note, the cyclic dependency between (a) and (c), which is introduces by an explicit `DependsOn`
statement in the generated template. If I remove the mentioned line, the cycle (`DependsOn` statement) disappears and the stack can be deployed. 

`LambdaFunction (a)` → `Role (b)` ← `Policy (c)` → `LambdaFunction (a)`

# How to reproduce 

```typescript
let lambda = new Function(this, "PostgreSQLSingleUserRotation", {...})
lambda.addToRolePolicy(new PolicyStatement().addActions(
      "secretsmanager:DescribeSecret",
      "secretsmanager:GetSecretValue",
      "secretsmanager:PutSecretValue",
      "secretsmanager:UpdateSecretVersionStage",
    ).addAllResources().addCondition("StringEquals",{
      "secretsmanager:resource/AllowRotationLambdaArn": `${lambda.functionArn}`
    }))
```

# Expected Behavior

No (unnecessary) cyclic dependency are created and the stack can be deployed. In this case the dependency graph looks like this:

`LambdaFunction (a)` → `Role (b)` ← `Policy (c)` → `LambdaFunction (a)`

# Observed Behavior 

An unnecessary cyclic dependency is created and the stack can not be deployed. In this case the dependency graph looks like this:

`LambdaFunction (a)` → `Role (b)` ← `Policy (c)` ↔ `LambdaFunction (a)`

# Workaround

Currently, a possible workaround is to ensure that the `PolicyStatement` is not attached to the `Role`'s `DefaultPolicy`:

```typescript
let lambda = new Function(this, "PostgreSQLSingleUserRotation", {...})
let policy = new Policy(this, "NonDefaultPolicy", {})
lambda.role!.attachInlinePolicy(policy)
policy.addStatement(new PolicyStatement().addActions(
      "secretsmanager:DescribeSecret",
      "secretsmanager:GetSecretValue",
      "secretsmanager:PutSecretValue",
      "secretsmanager:UpdateSecretVersionStage",
    ).addAllResources().addCondition("StringEquals",{
      "secretsmanager:resource/AllowRotationLambdaArn": `${lambda.functionArn}`
    }))
```

**Comment by rix0rrr** [comment]
Not disputing the bug report, but seems to me that referring to the Lambda from the Lambda's policy itself should not be necessary (given that you know which is the Lambda that will be executing).

Isn't `AllowRotationLambdaArn` intended as a condition key on a secret's *Resource* policy?

**Comment by rix0rrr** [comment]
As far as I can tell, a Lambda has had a dependency on its policy for as long as the feature has existed. 

The dependency seems to make intuitive sense. Without it, CloudFormation would be free to associate the policy with the role at any point in time after creating the Lambda, which means the Lambda could potentially execute without its policy in place. I am loathe to change this, since it might break lots of stacks in operation.

**Comment by rix0rrr** [comment]
In fact, I think I'm going to close this issue as a WONTFIX. I'm open to having my mind changed though.
