### ISSUE TITLE
(ecr-assets): How to control the name of the image

### ISSUE THREAD

**Issue by konstantinj** [aws/aws-cdk#13416]
## :question: General Issue

We want to make use of the ECR Vulnerabilities Scanner and therefore it should be possible to easily identify which image comes from which application. Having all images in one repo only with hashes and even without any meaningful tags makes no sense to me.

In the past there were several different ways setting the repo or the source/asset hash name. All of them are now deprecated.

### The Question

What's the proposed way to have meaningful image names and/or tags with the latest CDK version?

### Environment

  - **CDK CLI Version:** 1.91.0
  - **Module Version:** 1.91.0
  - **Node.js Version:** v15.11.0
  - **OS:** osx
  - **Language (Version):** all

**Comment by eladb** [comment]
We think of the ECR repository used for image assets as an implementation detail.

The proposed way (which is still unsupported) is to "deploy" the image asset to a specific ECR repository using something like `ecr-deployment`. See #12597 for more details.

Closing this as a duplicate of #12597 - please add comment if you believe ecr-deployment will not serve your use case.

**Comment by eladb** [comment]
copy @skinny85
