### ISSUE TITLE
(CDK Workshop Java project): IntelliJ cannot find software.amazon... dependencies

### ISSUE THREAD

**Issue by gelpenaddict** [aws/aws-cdk#13427]
### The Question
How do you get IntelliJ to detect software.amazon... dependencies?

### Environment

  - **CDK CLI Version:** 1.91.0 (build 0f728ce)
  - **Module Version:** 
  - **Node.js Version:** 
  - **OS:** macOS Catalina
  - **Language (Version):** Java (15)

### Other information
Following https://cdkworkshop.com/50-java.html , I did a 
> cdk init sample-app --language java
> mvn package

and opened the project in IntelliJ 2020.3.2

It cannot detect the dependency `software.amazon...`

In the pom file, this dependency looks ok (no red font)
```
        <dependency>
            <groupId>software.amazon.awscdk</groupId>
            <artifactId>core</artifactId>
            <version>${cdk.version}</version>
        </dependency>
```
while this plugin's version field 3.0.0 is in red font:
```
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.0.0</version>
                <configuration>
                    <mainClass>com.myorg.CdkWorkshopApp</mainClass>
                </configuration>
            </plugin>
```

When building via `mvn package` in the terminal, there is this warning:
```
> mvn package
[INFO] Scanning for projects...
[INFO] 
[INFO] -----------------------< com.myorg:cdk-workshop >-----------------------
[INFO] Building cdk-workshop 0.1
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for software.constructs:constructs:jar:3.2.110 is missing, no dependency information available
```

**Comment by gelpenaddict** [comment]
![image](https://user-images.githubusercontent.com/6164318/110178542-74640380-7dbb-11eb-9ee8-90ce97cef2bb.png)

**Comment by peterwoodworth** [comment]
Hey @gelpenaddict, sorry for the long response time

This isn't exactly a CDK question and I am not familiar with Java, so the help I can offer you is limited here. [Be sure to read the guide on working with CDK in Java](https://docs.aws.amazon.com/cdk/latest/guide/work-with-cdk-java.html#java-managemodules), I linked the section where it discusses working with dependencies. If you followed this and it's not working, then the issue might be with IntelliJ software. Sorry about this!
