### ISSUE TITLE
[Question] Deploy lambda in VPC: cdk - private subnets only vs. console - all subnets allowed

### ISSUE THREAD

**Issue by mouyigang** [aws/aws-cdk#1342]
My question is:

```js
const vpc = ec2.VpcNetworkRef.import(this, 'VPC', {
  vpcId: 'vpc-12345',
  availabilityZones: ['us-east-1a', 'us-east-1b']
  publicSubnetIds: ['subnet-4381', 'subnet-123'],
  privateSubnetIds: ['subnet-1425', 'subnet-86845'],
});

new lambda.Function(this, 'Lambda', {
  vpc: vpc,
  vpcPlacement: { subnetType: ec2.subnetType.Private }
});
```
this code will deploy lambda to 'subnet-1425', 'subnet-86845', and you can't specify subnetType.Public:

`
/home/ec2-user/environment//node_modules/@aws-cdk/aws-lambda/lib/lambda.js:158
                throw new Error('Not possible to place Lambda Functions in a Public subnet');
`

However after lambda gets deployed, I can go to console and add public subnets to lambda network.

Is this by design behaviour? Why the difference?

Thanks,
Andy

**Comment by RomainMuller** [comment]
What is the rationale for wanting to have your Lambda function deploy across both private and public subnets? I guess the CDK shouldn't be opinionated about what you can or can't do, however Lamdbas deployed in public subnets are barred from accessing internet no matter what (when in Private subnets, they can use a NAT gateway).

**Comment by SomayaB** [comment]
Closing this issue since there hasn't been any activity on it in a while. Feel free to reopen.

**Comment by kyunghoon** [comment]
i am also getting this error.

i have RDS serverless postgres running in the default public VPC, and by running the lambda inside that VPC allows me to connect to it. my current workaround is to execute the CDK stack without a vpc, then manually change it. is there a better way?
