### ISSUE TITLE
aws-rds : add MariaDbEngineVersion.VER_10_5_8

### ISSUE THREAD

**Issue by umutc** [aws/aws-cdk#13421]
### Reproduction Steps
-

### What did you expect to happen?
I want to that there must a  constant in class, such as that rds.MariaDbEngineVersion.VER_10_5_8

### What actually happened?
There is latest version is rds.MariaDbEngineVersion.VER_10_4_13 currently.

### Environment

  - **CDK CLI Version  : 1.91.0 **
  - **Node.js Version: 14.16.0**
  - **OS: Mac OS**
  - **Language (Version): typescript 4.2.2** 

### Other
-

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hi @umutc ,

thanks for opening the issue. Would you consider opening us a PR adding this version? It can be similar to this one: https://github.com/aws/aws-cdk/pull/12888, for example. Here's our Contributing guide: https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md.

Before that version is added, remember that you can always use the `of()` static factory method of the `MariaDbEngineVersion` to create a version for which a constant has not yet been defined.

Thanks,
Adam

**Comment by umutc** [comment]
Sure, thanks for reply 👌🙃🙂

**Comment by BLasan** [comment]
@umutc Are you working on this? If not shall I send a PR for this? @skinny85

**Comment by BLasan** [comment]
> > @umutc Are you working on this? If not shall I send a PR for this? @skinny85
> 
> Hi @BLasan , i have not started yet

No problem :)

**Comment by umutc** [comment]
@skinny85 @BLasan  
Well, i have just sent a PR #13531 to fix this problem.
