### ISSUE TITLE
aws-chatbot: addXXXPermisions() does not work

### ISSUE THREAD

**Issue by aqilzeeshan** [aws/aws-cdk#13444]
### What did you expect to happen?

According to https://docs.aws.amazon.com/cdk/api/latest/docs/aws-chatbot-readme.html the following should work

```
slackChannel.addLambdaInvokeCommandPermissions();
slackChannel.addNotificationPermissions();
slackChannel.addSupportCommandPermissions();
slackChannel.addReadOnlyCommandPermissions();
```

### What actually happened?

![3](https://user-images.githubusercontent.com/5244119/110210725-f0794c80-7e8a-11eb-97a5-10453e4965e9.JPG)

### Environment

  - **CDK CLI Version  :*1.91.0 *
  - **Framework Version:*1.91.0 *
  - **Node.js Version:*v10.24.0* 
  - **OS               :*Amazon Linux AMI 2018.03*
  - **Language (Version):*TypeScript Version 3.7.5* 

### Other

Of course I can do it long way as shown below but it would be nice to reduce lines of code if above works.

```
    const lambdaInvokeCommandStatement = new iam.PolicyStatement({
      effect: iam.Effect.ALLOW,
      resources: ['*'],
      actions: [
        "lambda:invokeAsync",
        "lambda:invokeFunction"
      ],
    });
    slackChannel.addToRolePolicy(lambdaInvokeCommandStatement);
```

--- 

This is :bug: Bug Report

**Comment by OG84** [comment]
yep just noticed the same. Documentation seems not to be in sync.
This was never implemented, if I read the pull request correctly.

**Comment by skinny85** [comment]
Hey @aqilzeeshan ,

yes, this is an error in the documentation. These were removed from the original PR, in favor of just having the [`addToRolePolicy` method](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-chatbot.SlackChannelConfiguration.html#addwbrtowbrrolewbrpolicystatementspan-classapi-icon-api-icon-experimental-titlethis-api-element-is-experimental-it-may-change-without-noticespan).

Any chance of a PR fixing the docs? Here's our Contributing guide: https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md.

Thanks,
Adam

**Comment by BLasan** [comment]
> Hey @aqilzeeshan ,
> 
> yes, this is an error in the documentation. These were removed from the original PR, in favor of just having the [`addToRolePolicy` method](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-chatbot.SlackChannelConfiguration.html#addwbrtowbrrolewbrpolicystatementspan-classapi-icon-api-icon-experimental-titlethis-api-element-is-experimental-it-may-change-without-noticespan).
> 
> Any chance of a PR fixing the docs? Here's our Contributing guide: https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md.
> 
> Thanks,
> Adam

Can I work on this? Basically we need to replace `slackChannel.addLambdaInvokeCommandPermissions();` with `slackChannel.addToRolePolicy(lambdaInvokeCommandStatement);` right?

**Comment by MrArnoldPalmer** [comment]
@BLasan whoever wants to pick it is  welcome. Yeah it's just replacing references in the docs to the old methods with usage of addToResourcePolicy.

**Comment by BLasan** [comment]
@MrArnoldPalmer So I need to do the change in awsdocs/aws-cdk-guide right?
