### ISSUE TITLE
(aws-ecs): setup Webrtc on Fargate

### ISSUE THREAD

**Issue by mostafafarzaneh** [aws/aws-cdk#13443]
I am trying to set up a Webrtc agent on Fargate in an ECS service. Webrtc agents use a huge range of UDP ports and therefore I need to open that range. The only network type that Fargate support is `awsvpc` and I cannot use `host` network mode for my task. So I have to port map the whole range of UDP ports which led me to this error:
> Invalid request provided: Create TaskDefinition: Actual length: '293371'. Max allowed length is '65536' bytes.

If I use the EC2 instance type, I can use `host` network mode to remedy this problem. But unfortunately, I cannot use that either because my service is inside app mesh, and the app mesh only supports `awsvpc` network type.

**Comment by mostafafarzaneh** [comment]
I just tested the Webrtc agent service on Fargate. In the task definition, I have not mapped any UDP port and only just mapped a TCP port for signaling. Also, I have opened all UDP ports in the service security group. It just works! I can send a video to my Fargate service with the Webrtc protocol. 
To make sure that the video is transmitted through UDP ports, I closed all UDP ports in the service security group. It won't work anymore.

I think on `awsvpc` you do not need to map any UDP port. Is that right?

**Comment by SoManyHs** [comment]
Correct, in `awsvpc` mode you don't need to specify a host port (See: [Port Mappings](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#container_definition_portmappings)), regardless of the protocol. Feel free to include what your task definition looks like if you wanted further verification, otherwise I'll go ahead and close this!

**Comment by mostafafarzaneh** [comment]
Here is my task definition in cdk:

>      container = task_definition.add_container(f"container",
>                                             image=image,
>                                             environment=env,
>                                             essential=True,
>                                             logging=logging,
>                                             memory_reservation_mib=4096,
>                                             )
>         port_mapping = ecs.PortMapping(container_port=81)
>         container.add_port_mappings(port_mapping)
> 

I have not mapped any UDP port. Just mapped 81 TCP. But still, I can send videos to my service via Webrtc.
Am I missing something?

**Comment by mostafafarzaneh** [comment]
something to notice, the Webrtc connection is too slow on Fargate.
I have tested the same docker container on an EC2 with the option `--net=host`. It works very well.

Again, I am confused. Despite I have not mapped any UDP port on Fargate, I can send Video via Webrtc. Although it is very slow.

**Comment by mostafafarzaneh** [comment]
@SoManyHs Do you have any ides?

**Comment by SoManyHs** [comment]
Hm, could you include the generated CFN stack?

**Comment by mostafafarzaneh** [comment]
Thanks, @SoManyHs
You can find the generated CFN attached
[IPSA.template.txt](https://github.com/aws/aws-cdk/files/6120877/IPSA.template.txt)
.

**Comment by mostafafarzaneh** [comment]
Regarding the slow Webrtc connection on Fargate, after some experiments, I found that if I config the ICE protocol to exclude the local network(by setting the `disable_link_local_networks` to false in `webrtc::PeerConnectionInterface::RTCConfiguration`), it would be much faster. The odd thing is this is problematic in Fargate not in EC2.
