### ISSUE TITLE
(cloudfront): Cache Policy cannot forward Authorization header.

### ISSUE THREAD

**Issue by apoorvmote** [aws/aws-cdk#13441]
I am distributing HTTP API with cloudfront distribution and I wanted to forward `Authorization` Header.

https://github.com/aws/aws-cdk/issues/13408#issuecomment-791323037

I was told to create cache policy with allow list 

I get error `Invalid request provided: AWS::CloudFront::CachePolicy`

### Reproduction Steps

As per the instructions https://github.com/aws/aws-cdk/issues/13408#issuecomment-791323037 I did 
```ts
new CachePolicy(this, 'apiCachePolicy', {
      defaultTtl: Duration.minutes(0),
      maxTtl: Duration.minutes(0),
      minTtl: Duration.minutes(0),
      headerBehavior: CacheHeaderBehavior.allowList('Authorization'),
    })
```

So I went to the cloudfront console and added new policy
![cachePolicy](https://user-images.githubusercontent.com/9799239/110205727-c7af8200-7e9f-11eb-850b-fe103cbb9566.jpg)

### What did you expect to happen?

As per documentation https://aws.amazon.com/premiumsupport/knowledge-center/cloudfront-authorization-header/
I should be able to forward `Authorization` header with cache policy.

### What actually happened?

When I set default, max & min ttl to zero then all remaining options are disabled. 

### Environment

  - **CDK CLI Version  :** 1.92.0
  - **Framework Version:**
  - **Node.js Version:**  14.16.0
  - **OS               :** Ubuntu 20.04 WSL2
  - **Language (Version):**  Typescript ~3.9.7

### Other

--- 

This is :bug: Bug Report

**Comment by njlynch** [comment]
I see you got help in the linked issue; the quick answer is that a cache policy must have _some_ TTL set to non-zero value to allow for any other settings, so setting a maxTTL of 1 second is sufficient.
