### ISSUE TITLE
(custom-resources): provider framework: asynchronous waiter has state

### ISSUE THREAD

**Issue by elemakil** [aws/aws-cdk#13458]
The [custom resource provider framework](https://docs.aws.amazon.com/cdk/api/latest/docs/custom-resources-readme.html) was a great addition to CDK, that I have been using with great success to make my deployments more capable. However, the current implementation is limited to constructing the "state" (i.e. `event` object) of the asynchronous `isComplete` handler once at the start of the provider StateMachine. 

Sometimes it would be useful to pass information (i.e. state) from one invocation of the `isComplete` handler to the next. As the provider framework is based on Lambda and StepFunctions, this should be a relatively simple extension of the current functionality.

I would like to request that the request and response interface of the `isComplete` handler is extended to allow for user-defined data to be passed from invocation to invocation.

### Use Case

(Somewhat Contrived) **Example**: A series of EC2 instances must be started in a specific order (e.g. instances A, B, and C in that order, or formulated as list `[A, B, C]`) and each subsequent instance must not be started until all previous instances are up and running. Currently, this can be achieved by iterating through the instance array and looking for the first instance that is not "running & ok" and either starting the next instance (if previous instance is "running & ok") or waiting for the next invocation of `isComplete`. By allowing to pass state from each invocation of `isComplete` to the next, the instance list can be gradually reduced with each new "running & ok" instance, thereby reducing the number of API calls to be made.

This example can be re-imagined for various AWS resources that are not active instantaneously.

### Proposed Solution

Extend the existing [provider framework](https://github.com/aws/aws-cdk/blob/de536cc5eb8d290fcbfed2ff2af6f5d7f8049275/packages/%40aws-cdk/custom-resources/lib/provider-framework/runtime/framework.ts) such that 
- the response and request interface of the `isComplete` handler allow for custom userdata
- capture the response from an invocation of `isComplete` and pass it along to the next invocation of `isComplete`.

### Other

I am willing and able to implement this feature request myself.

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
The example given is not too strong, in my opinion. This one feels like it could have been modeled as 3 individual executions of the custom resource for each of the instances `A, B, C`, with dependencies between them to enforce the ordering.

I would like to see a more realistic example. There must have been a use case for yourself to request this feature--why don't you describe that?

**Comment by elemakil** [comment]
Interesting :smirk:. Your proposed solution to the example seems indeed much cleaner than my suggested approach. :+1:

The actual use case I want to solve is the following: I have a stack that contains a DynamoDB and as part of the deployment I also want to create several GlobalSecondaryIndexes (GSI) for that DynamoDB. GSI creation can be performed through CDK, however, due to limitations in DynamoDB, only one GSI creation (request) can be performed at a time. This has already been raised as issue #12246. 

Unlike the EC2 example, there is not really any dependency regarding the ordering of GSI creations as long as no more than one index creation is attempted/ongoing at a time. I have created a custom resource that follows the design outlined in my initial post for the EC2 example. I am inclined to say that this too could be solved using the approach you suggest and it would be a cleaner solution as I would yield one "Resource" per GSI.

(Un)fortunately, this leaves me without a use case that can not be solved elegantly otherwise. I'll give it some more thought, but I'm not sure that this feature request is needed after all.

**Comment by rix0rrr** [comment]
> (Un)fortunately, this leaves me without a use case that can not be solved elegantly otherwise.

😄 glad to hear it. I'll set this to autoclose, if you come up with something in the mean time it will automatically stay open.

Cheers.
