### ISSUE TITLE
(aws-ec2): SecurityGroup never inlines ingress rules when peer is a SecurityGroup

### ISSUE THREAD

**Issue by rectalogic** [aws/aws-cdk#13451]
SecurityGroup never inlines ingress rules where the peer is another SecurityGroup, even when the reference is not cyclic. This is because `SecurityGroupBase` sets `canInlineRule = false`
https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-ec2/lib/security-group.ts#L65

Creating a new `AWS::EC2::SecurityGroupIngress` for every rule consumes limited resources unnecessarily

### Reproduction Steps

synth this stack, the ingress rule is a new `AWS::EC2::SecurityGroupIngress` resource instead of inline:
```python
#!/usr/bin/env python3

from aws_cdk import core, aws_ec2 as ec2


app = core.App()
stack = core.Stack(app, "stack")
vpc = ec2.Vpc(stack, "VPC", cidr="10.0.0.0/16")
sg1 = ec2.SecurityGroup(
    stack,
    "SG1",
    vpc=vpc,
)
sg2 = ec2.SecurityGroup(
    stack,
    "SG2",
    vpc=vpc,
)
sg2.add_ingress_rule(peer=sg1, connection=ec2.Port.tcp(22))

app.synth()
```

### What did you expect to happen?
Inline rules to be used

### What actually happened?
A new `AWS::EC2::SecurityGroupIngress` resource is always created for every rule.

### Environment

  - **CDK CLI Version  :** 1.91.0 (build 0f728ce)
  - **Framework Version:** 1.91.0
  - **Node.js Version:** v14.15.0
  - **OS               :** macOS 10.15.7
  - **Language (Version):** Python 3.8.7

### Other

A separate resource is only necessary if the SecurityGroup is immutable or if the ingress rule would create a circular reference.

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
It's true, but we can't know beforehand whether a cyclic reference would be created or not. To be safe, we never inline rules that reference other security groups in this way.
