### ISSUE TITLE
constructs: is anyone watching the repo?

### ISSUE THREAD

**Issue by shellscape** [aws/aws-cdk#13459]
### The Question

Is anyone watching the repo at https://github.com/aws/constructs? I had considered opening a new feature request to allow developers to retrieve the `id` passed to the constructor for a `Construct`, but given that there are two issues open there without a reply _from anyone_ for over 6 months, I got to wondering if that'd even get human attention. I don't mean to sound ungrateful or perturbed - more so wondering if those pour souls were speaking into the void. Given that this package is literally the bedrock of the entire AWS CDK, I hope there's a team assigned to check in on it, and maybe receive a nudge and a wink to take a look at it.

### Environment

  - **CDK CLI Version:** n/a
  - **Module Version:** n/a
  - **Node.js Version:** n/a
  - **OS:** n/a
  - **Language (Version):** n/a

**Comment by peterwoodworth** [comment]
Thank you for the concern! The repo is being watched, multiple issues have been submitted in the past few months and they have been looked at quickly by a couple different people. One of the issues left open for 6 months was opened by a team member. The other issue hasn't received any response and isn't from a team member, which is a bit concerning, so thank you for bringing this to our attention. Apologies for if this dissuaded you from contributing, please feel free to contribute! Your contribution won't get lost in the void.

Let me know if this answers your question!

**Comment by shellscape** [comment]
Great, thanks for the kind response!
