### ISSUE TITLE
(cdk-pipelines): allow user to pass IAM roles in the add_application_stage method

### ISSUE THREAD

**Issue by jaidisido** [aws/aws-cdk#13454]
In the `pipelines` module, a user should be able to specify the CloudFormation execution IAM role used in the `add_application_stage`

### Use Case

We intend to leverage multiple CDK pipelines to deploy multiple applications within an account. Following the least privilege principle, these pipelines cannot share the same IAM role. At the moment, a CFN execution IAM role created at bootstrap is implicitly used for every application stage definition. Instead each pipeline/stage deploying an application should have its own role.

### Proposed Solution

```
pipeline.add_application_stage(
    FoundationsStage(
        self,
        "stage_id",
        env=Environment(account="111111111111", region="us-east-1"),
    ),
    action_role="...", # pass an action role
    cloud_formation_execution_role="...", # pass a CFN execution role
)
```
These arguments can be optional. In which case, the default is to use the IAM role created at bootstrap.

### Other

One workaround is to leverage the `DeployCdkStackAction` construct, but that involves passing a path to a CFN template and configuration which is not straightforward

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
The roles are determined from the synthesizer passed to the Stacks inside the stages.

Read this on how to customize those settings: https://docs.aws.amazon.com/cdk/latest/guide/bootstrapping.html#bootstrapping-custom-synth

**Comment by jaidisido** [comment]
Thank you @rix0rrr, that solves it!
Here is a [link](https://stackoverflow.com/questions/66508536/aws-cdk-pipelines-pass-synthesized-cloudformation-template-name-and-configurati/66569076#66569076) with more details for those interested in an example
