### ISSUE TITLE
(aws-certificatemanager): 'ExampleNet' is misspelled as 'ExampelNet'

### ISSUE THREAD

**Issue by douglasnaphas** [aws/aws-cdk#13460]
https://docs.aws.amazon.com/cdk/api/latest/docs/aws-certificatemanager-readme.html#dns-validation

A code sample under **DNS validation** includes:

```
const exampleNet = new route53.HostedZone(this, 'ExampelNet', {
  zoneName: 'example.net',
});
```

`'ExampelNet'` should be `'ExampleNet'`.

https://github.com/aws/aws-cdk/blame/e244c5d7409980267d1fa48afbfea38c42e88a28/packages/%40aws-cdk/aws-certificatemanager/README.md#L71

---

This is a 📕 documentation issue

**Comment by njlynch** [comment]
closed via #13319
