### ISSUE TITLE
aws-iam: policy statements are trying to validate tokens

### ISSUE THREAD

**Issue by cheng-kevin** [aws/aws-cdk#13479]
## :question: General Issue

Are IAM PolicyDocument Actions limited to string types?  I am trying to reference a cloudformation parameter as my action.

```ts
 new iam.PolicyStatement({
      actions: [
         core.Fn.join('',
          [ core.Fn.ref(Parameters.myparameter, ':*' )]
      ],
      effect: iam.Effect.ALLOW,
      resources: [ '*' ] 
    }
)
```

### Environment

  - **CDK CLI Version:** 
  - **Module Version:** 
  - **Node.js Version:** 
  - **OS:** 
  - **Language (Version):**

**Comment by skinny85** [comment]
Hey @cheng-kevin ,

looks like you're right - while usually in the CDK you can do things like:

```ts
        const myParameter = new cdk.CfnParameter(this, 'Param');
        new iam.Role(this, 'Role', {
            assumedBy: new iam.AnyPrincipal(),
        });
        new iam.PolicyStatement({
                actions: [
                    `${myParameter.value}:*`,
                ],
                effect: iam.Effect.ALLOW,
                resources: [ '*' ]
            }
        );
```

This results in the following error:

```
Action '${Token[Param.Ref.20]}:*' is invalid. An action string consists of a service namespace, a colon, and the name of an action. Action names can include wildcards.
```

Probably [this code](https://github.com/aws/aws-cdk/blob/e09250bc92c62cb8ee0a8706ce90d0e82faf2d84/packages/%40aws-cdk/aws-iam/lib/policy-statement.ts#L66-L70) should check if `action` is a Token using the `Token.isUnresolved()` method.

**Comment by rix0rrr** [comment]
What @skinny85 said is accurate
