### ISSUE TITLE
(@aws-cdk/aws-lambda): fn.addEventSource DynamoEventSource failing

### ISSUE THREAD

**Issue by stefdaems** [aws/aws-cdk#13472]
On adding the eventSource to the lambda function, the deploy is no longer working.

```
   const lambda = require('@aws-cdk/aws-lambda-nodejs');
   const eventSource = require('@aws-cdk/aws-lambda-event-sources');
   const fn = new lambda.NodejsFunction(this, 'tableConfigDynamoStreams', {
      entry: 'lambda/info/info.js',
    });
    const streamEventSource = new eventSource.DynamoEventSource(this.dynamoStack.tableInventory.configTable, {
      batchSize: 1
   });
      
   fn.addEventSource(streamEventSource)
```

Where configTable in the stack is holding the dynamodb table generated already ( in another stack ).
Everything runs fine till the  fn.addEventSource(streamEventSource) line of code is executed.

```
The following resource(s) failed to create: [tableConfigDynamoStreamsDyn
amoDBEventSource....
```

### Reproduction Steps

```
  const lambda = require('@aws-cdk/aws-lambda-nodejs');
  const eventSource = require('@aws-cdk/aws-lambda-event-sources');
  const fn = new lambda.NodejsFunction(this, 'tableConfigDynamoStreams', {
      //entry: 'lambda/centralChannelManagement/dynamostreams.js',
      entry: 'lambda/info/info.js',
    });
    const streamEventSource = new eventSource.DynamoEventSource(this.dynamoStack.tableInventory.configTable, {
      batchSize: 1
   });
      
   fn.addEventSource(streamEventSource)
```
### What did you expect to happen?

The eventsource should be loaded.

### What actually happened?

cdk deploy failed.

### Environment

  - **CDK CLI Version  :** 1.90.1 (build 0aee440)
  - **Framework Version:** 1.90.1
  - **Node.js Version: v14.15.0
  - **OS               : macOs
  - **Language (Version):** Javascript

### Other

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
Can you provide a full working CDK app with the two stacks for a reproduction?

Could you also provide the actual error message on event source could not be created? It should be available both in the output of `cdk deploy` and in the CloudFormation console.
