### ISSUE TITLE
(aws-cdk): Cannot find module './assets' @aws-cdk/cloud-assembly-schema/lib/index.js

### ISSUE THREAD

**Issue by fkoner** [aws/aws-cdk#13483]
I have a mono repository.

Everything is fine when I execute a `lerna bootstrap`, or `yarn install`. But I see these packages are deleted after `lerna` or `yarn` command completes:

```
node_modules/@aws-cdk/assets
node_modules/@aws-cdk/cloud-assembly-schema/lib/assets
```

### What did you expect to happen?

Be able to execute yarn cdk deploy o any cdk commmand.

Also, that these packages not deleted after `lerna` or `yarn` command completes:

```
node_modules/@aws-cdk/assets
node_modules/@aws-cdk/cloud-assembly-schema/lib/assets
```

### What actually happened?

These packages are deleted after `lerna` or `yarn` command completes:

```
node_modules/@aws-cdk/assets
node_modules/@aws-cdk/cloud-assembly-schema/lib/assets
```

And when I execute a command like cdk synth o cdk deploy, It throws the following error:

```bash
Cannot find module './assets'
Require stack:
- /home/paco/development/github-projects/microsip/infraestructura-serverless/node_modules/@aws-cdk/cloud-assembly-schema/lib/index.js
- /home/paco/development/github-projects/microsip/infraestructura-serverless/node_modules/@aws-cdk/core/lib/annotations.js
- /home/paco/development/github-projects/microsip/infraestructura-serverless/node_modules/@aws-cdk/core/lib/tag-aspect.js
- /home/paco/development/github-projects/microsip/infraestructura-serverless/node_modules/@aws-cdk/core/lib/index.js
- /home/paco/development/github-projects/microsip/infraestructura-serverless/packages/stack/bin/infraestructura-serverless.ts
```

### Environment

  - **CDK CLI Version: *1.92.0*
  - **Framework Version: *1.92.0*
  - **Node.js Version: *14.15.4*
  - **OS               : *Linux Ubuntu 20.04*
  - **Language (Version): *Typescript 4.1.3*

## Other

Here are the imports of infraestructura-serverless.ts

```typescript
import * as cdk from '@aws-cdk/core'
import * as ec2 from '@aws-cdk/aws-ec2'
import * as lambda from '@aws-cdk/aws-lambda'
import * as api from '@aws-cdk/aws-apigateway'
import * as cognito from '@aws-cdk/aws-cognito'
import * as route53 from '@aws-cdk/aws-route53'
import * as route53Targets from '@aws-cdk/aws-route53-targets'
import * as certifateManager from '@aws-cdk/aws-certificatemanager'
import * as iam from '@aws-cdk/aws-iam'
import * as s3 from '@aws-cdk/aws-s3'
import * as logs from '@aws-cdk/aws-logs'
```

This only happens at this new repo, I tried to delete all node_modules, reinstall it, clear yarn cache, etc, nothings solves these issue. I have another repository with similar setup, and that works ok.

**Thanks in advance**
**_Paco_**

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
I understand this might be frustrating and/or confusing, but there is nothing in our code that will delete directories on your disk. 

You also did not give us a lot of information to go on. What is the layout of your monorepo? What do your `package.json` files look like? Do the directories get deleted immediately after `yarn install`? Or after ANY `yarn` command? Maybe `yarn build` or `yarn test`?

This seems like something particular to your situation.

**Comment by fkoner** [comment]
Hi @rix0rrr. Thanks for you reply and valuable time.

The problem was not the monorepo, in fact we converted a normal project to a monorepo type project, and along the way an upgrade of the cdk was carried out, so the doubt if something changed in cdk that we did not know. We did the same upgrade on the other project and this one worked perfectly. So I got to work and finally debugging the `yarn install` command, it was appreciated that it was executing a cleaning of the node modules compared to the other repository.

I finally found the culprit. It is a [`.yarnclean`](https://classic.yarnpkg.com/en/docs/cli/autoclean/) file that what it does is clean the node modules to remove tests and some other assets (it just removes any file or directory called assets), but this file was only integrated into the CI Pipeline.

Just for reference I share part of the content of such file:
```bash
# test directories
__tests__
test
tests
powered-test

# asset directories
docs
doc
website
images
assets

# examples
example
examples

# code coverage directories
coverage
.nyc_output

# build scripts
Makefile
Gulpfile.js
Gruntfile.js

# configs
appveyor.yml
circle.yml
codeship-services.yml
codeship-steps.yml
wercker.yml
.tern-project
.gitattributes
.editorconfig
.*ignore
.eslintrc
.jshintrc
.flowconfig
.documentup.json
.yarn-metadata.json
.travis.yml

# misc
*.md
```

I close this issue.

**Thanks in advance**
**_Paco_**
