### ISSUE TITLE
(@aws-cdk/aws-ec2): ec2.Subnet does not return the expected subnet with subnet_id

### ISSUE THREAD

**Issue by kevmando** [aws/aws-cdk#13482]
ec2.Subnet.from_subnet_id does not get the subnet selection which is defined by subnet_id and just get the first subnet from context. 

### Reproduction Steps
Create VPC and more than 2 Subnets in public network from aws console or some other tools such as terraform.

Create EC2 instance with the following CDK and try `$ cdk synth`

```
# VPC
vpc = ec2.Vpc.from_lookup(self, id="vpc", vpc_id="vpc-id which has more than 2 subnets in public")

# Subnet
subnet_selection = ec2.Subnet.from_subnet_id(self, id='subnet', subnet_id="subnet id which is not at the top in cdk.context.json")

# EC2 instance
instance = ec2.Instance(self,
                        id="cdk-test",
                        instance_type=ec2.InstanceType("t2.micro"),
                        vpc=vpc,
                        vpc_subnets=subnet_selection,
                        machine_image=ubuntu20_04,
                        security_group=sg
                        )

...
```

### What did you expect to happen?
EC2 instance is created where the selected subnet from existing VPC.

### What actually happened?
EC2 instance is created in the wrong subnet, which is just at the first of cdk.context.json.

### Environment

  - **CDK CLI Version  :**1.92.0
  - **Framework Version:**1.92.0
  - **Node.js Version:**v14.15.0
  - **OS               :**Mac OS X 11.2.2
  - **Language (Version):**Python (3.8.5)

### Other
So if you have the following context such as a vpc with multiple subnets, then `from_subnet_id` or `from_subnet_attributes` returns the first one - subnet-aaa even I tried to use subnet-bbb or subnet-ccc.

```
cdk.context.json

  "vpc-provider:account=1234567890:filter.vpc-id=vpc-vpc:region=us-east-1:returnAsymmetricSubnets=true": {
    "vpcId": "vpc-vpc",
    "vpcCidrBlock": "10.1.0.0/16",
    "availabilityZones": [],
    "subnetGroups": [
      {
        "name": "Public",
        "type": "Public",
        "subnets": [
          {
            "subnetId": "subnet-aaa",
            "cidr": "10.1.2.0/24",
            "availabilityZone": "us-east-1a",
            "routeTableId": "rtb-aaa"
          },
          {
            "subnetId": "subnet-bbb",
            "cidr": "10.1.4.0/24",
            "availabilityZone": "us-east-1a",
            "routeTableId": "rtb-bbb"
          },
          {
            "subnetId": "subnet-ccc",
            "cidr": "10.1.6.0/24",
            "availabilityZone": "us-east-1a",
            "routeTableId": "rtb-ccc"
          },
          ...
```

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
A `Subnet` is not a `subnetSelection`. To be frank, I'm surprised this doesn't throw, but I guess that's because it happens to work out in untyped Python.

Try something like:

```
                        vpc_subnets=ec2.SubnetSelection(subnets=[imported_subnet]),
```

**Comment by kevmando** [comment]
Thanks @rix0rrr. I just tried to use ec2.SubnetSelection, then ec2.Instance returns the following message even cdk.context.json has availability zone same as previous.

How can I specify or pass az on the subnet..? Is it related other issues mentioning imported vpc..?

` You cannot reference a Subnet's availability zone if it was not supplied. Add the availabilityZone when importing using Subnet.fromSubnetAttributes()`
