### ISSUE TITLE
(core): deletion of custom resources is broken since CDK 1.92

### ISSUE THREAD

**Issue by dirknilius** [aws/aws-cdk#13486]
Deletion of any cfn custom resource  results in a `Failed to delete resource. Unexpected token o in JSON at position 1`.

it doesn't matter what kind of custom resource. Can be a `DnsValidatedCertificate` or `AwsCustomResource` or whatever.

### Environment

  - **CDK CLI Version  :**
  - **Framework Version: 1.92**
  - **Node.js Version: v14.16.0** 
  - **OS               : MacOS 11.2.2**
  - **Language (Version): TypeScript 4.2.3** 

### Other

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
Probably introduced by this: https://github.com/aws/aws-cdk/pull/13074

I'm guessing `event.ResourceProperties` contains the non-JSON-encoded values from `<1.92.0`, which now fail to be decoded.

**Comment by rix0rrr** [comment]
Asked @eladb  to follow up on this.

**Comment by eladb** [comment]
@dirknilius Curious if this is indeed related to what @rix0rrr said. Any chance you can downgrade your CDK and try to delete the resource and then upgrade?

**Comment by dirknilius** [comment]
@eladb Unfortunately that was not possible. The CloudFormation stack was stuck for a while trying to delete the resource(s) and then just deleted the resource reference from the stack. The underlying resources where still there, in my case ACM certs and custom resource lambdas. I had to delete them manually. So, the worst thing is that you end up with a stack that deletes the custom resources from the stack, but the physical resources stay. ATM I downgraded the stack and did not upgrade any other stack.

**Comment by eladb** [comment]
This sounds like a pretty frustrating experience. Sorry about that.

I'll try to reproduce this next week and see if we are able to ensure this doesn't happen again.

Thanks 🙏

**Comment by dirknilius** [comment]
Sounds good. Let me now if you need my support on that one.

**Comment by eladb** [comment]
@dirknilius sorry, I haven't been able to attend to this yet. As mentioned, this is likely a result of a non-compatible change we did in how `AwsCustomResource` is modeled. Is this is still something that blocks you?

**Comment by dirknilius** [comment]
Hi @eladb , thanks for coming back to this. Actually I was able to successfully upgrade the affected stacks to CDK 1.98. You will still see a "Cannot delete resource" error, but after the upgrade it is fine.I believe this can be closed.

**Comment by eladb** [comment]
🙏
