### ISSUE TITLE
CDK v2 init fails with Constructs 10.0.0-pre.5 not found

### ISSUE THREAD

**Issue by ndonkor75701** [aws/aws-cdk#13498]
### The Question
Trying to follow instructions to set up a new install of the CDK.  I'd like to do this with v2 as its a private project. However when I try to install the requirements I get an error as per below.

### Environment

  - **CDK CLI Version:** 2.0.0-alpha.6 (build 5fc8c67)
  - **Module Version:** constructs==10.0.0-pre.5
  - **Node.js Version:** v12.16.3
  - **OS:** OSX Catalina
  - **Language:** Python

### Other information

```
pip install -r requirements.txt
Obtaining file:///Users/ndonkor/Projects/Personal/playground/cdk/greengrass-module (from -r requirements.txt (line 1))
Collecting aws-cdk-lib==2.0.0-alpha.6
  Using cached aws_cdk_lib-2.0.0a6-py3-none-any.whl (51.5 MB)
ERROR: Could not find a version that satisfies the requirement constructs==10.0.0-pre.5 (from greengrass-module)
ERROR: No matching distribution found for constructs==10.0.0-pre.5
```

**Comment by nija-at** [comment]
@rix0rrr - can you take a look at this as part of your work for v2 init templates?

**Comment by nija-at** [comment]
@rix0rrr - can you take a look at this while you're looking into the V2 init template?

**Comment by rix0rrr** [comment]
This issue will be fixed by the time the new v2 release goes out, as we're now depending on `constructs 10` and don't care about the pre-release tag anymore.
