### ISSUE TITLE
(aws-eks): Unable to migrate from managed to imported cluster

### ISSUE THREAD

**Issue by adrialucena-seat** [aws/aws-cdk#13499]
We had a single cdk app with a large number of stacks and was creating a huge infrastructure in AWS.
One of this stacks was creating the EKS Cluster and then we were passing the Cluster object as argument to some other stacks which were applying some k8s manifests through KubernetesManifest (a required argument for this construct is the Eks Cluster object). We had many projects in this cdk app, so it made sense for us to split in different stacks every project that was using EKS, so each of them was creating the namespaces and the resources inside every namespace.

As the cdk app was getting bigger, we decided to split the app in smaller apps. Every project should have its github repository and its own infrastructure, leaving only the EKS Cluster creation in the original cdk app. In this point, we needed to pass the object ICluster (instead of the object Cluster) to the KubernetesManifest construct, as we needed to import the cluster in every smaller cdk app using `Cluster.fromClusterAttributes` method (this method provides you the ICluster object).

The problem with this change (using ICluster in KubernetesManifest instead of Cluster object) is that cdk (and CloudFormation) wanted to change the ServiceToken of the CloudFormation:CustomResource, something that is not supported by CloudFormation, getting this error: `Modifying service token is not allowed.`

### Reproduction Steps

```
val eksCluster = Cluster.fromClusterAttributes(
            this,
            "eksCluster",
            ClusterAttributes
                    .builder()
                    .clusterName(clusterName)
                    .kubectlRoleArn(eksPodExecutionRoleArn)
                    .build()
    )

val kubernetesManifest = KubernetesManifest(
            scope,
            "eksManifest",
            KubernetesManifestProps
                    .builder()
                    .cluster(eksCluster)
                    .prune(false)
                    .manifest(mutableListOf(manifest))
                    .build()
    )
```
This peace of code works if a new resource is created but not if we change the cluster property of KubernetesManifest from Cluster object to ICluster object for the same k8s manifest (same resource, same stack).

### What did you expect to happen?

There shouldn't be any change in the CloudFormation Template as the value of the CloudFormation:CustomResource ServiceToken does not change.

### What actually happened?

When doing `cdk diff` we notice this change in the Custom::AWSCDK-EKS-KubernetesResource created by KubernetesManifest construct:
```
 └─ [~] ServiceToken
     ├─ [+] Added: .Fn::GetAtt
     └─ [-] Removed: .Fn::ImportValue
```
And when deploying using `cdk deploy` we see this error:
 `Modifying service token is not allowed.`
and rolling back the cloudformation stack to the previous state.

### Environment

  - **CDK CLI Version  :** 1.88.0
  - **Framework Version:**
  - **Node.js Version:** v15.9.0
  - **OS               :** ubuntu-latest
  - **Language (Version):** Java (11)

### Other

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment]
@adrialucena-seat Let me see if I understand this correctly. 

From what I gather, you initially had a CDK app that provisioned the EKS in one stack, and applied manifests in another, and you simply passed the cluster object from one stack to another. Something like this:

(excuse my TS :))

```ts
export class ClusterStack extends cdk.Stack {

  public readonly cluster: eks.Cluster;

  constructor(scope: cdk.Construct, id: string) {
    super(scope, id, props);
    this.cluster = new eks.Cluster(this, 'Cluster', {...})
  }
}

export class ManifestStack extends cdk.Stack {

  constructor(scope: cdk.Construct, id: string, cluster: eks.Cluster) {
    super(scope, id, props);
    new eks.KubernetesManifest(this, 'manifest', {
      cluster: cluster, // the object from the cluster stack
      ...
    })
  }
}
```

This worked fine, and caused the `ServiceToken` to accept an `Fn::ImportValue` since it was imported from a different stack.

You then moved the manifest to a dedicated CDK app, which means you now have to use `Cluster.fromClusterAttributes` to obtain a reference to the cluster.

```ts
export class ManifestStack extends cdk.Stack {

  constructor(scope: cdk.Construct, id: string) {
    super(scope, id, props);

    cluster = eks.Cluster.fromClusterAttributes(this, 'Cluster', {...});

    new eks.KubernetesManifest(this, 'manifest', {
      cluster: cluster, // an imported cluster from the original app
      ...
    })
  }
}
```

And at this point the deployment of the manifest broke because the service token was replaced, even though nothing effectively changed. 

Did I get this right?

BTW - The manifest app has a diff even though it was never deployed because you preserved the stack name from before?

**Comment by adrialucena-seat** [comment]
You explained better than me xD. Yes, you got it right.
Now it's me who I am not sure if I understand your last question.

**Comment by iliapolo** [comment]
@adrialucena-seat 

> As the stack name didn't change

Yeah, thats what I suspected. Thats fine, sorta.  

What happens is that every time you use the `KubernetesManifest` resource, a dedicated stack singleton lambda is created that supports the resource by issuing the `kubectl` commands. 

Since this stack is now in a different app, there is no way to reuse that lambda that was originally created, as we don't allow providing an external lambda.

I'm going to convert this issue to a feature request for being able to use an externally provided `KubectlHandler`, let me know if you feel differently. 

One hack I can think of is to rename the manifest stack, this will recreate all the manifests, but since nothing changed, the `kubectl apply` command we invoke shouldn't have any effect. The only problem is that you'll effectively be stuck with this old stack. 

Or, if you can afford it, destroy the old stack, that would also untangle you. If you can't afford it, you can effectively destroy the stack without deleting any k8s resource by using `prune: false` and removing all the manifest declarations from the resources.

**Comment by iliapolo** [comment]
> I'm going to convert this issue to a feature request for being able to use an externally provided KubectlHandler

On second thought, even that wouldn't have helped because the service token would have to change from `Fn::ImportValue` to something else. 

This requires some more thinking to figure out if there is a feasible way to support such a use case.

**Comment by adrialucena-seat** [comment]
We tried the hack that you suggested, renaming the manifest stack, but it seems that the Lambda Function responsable for applying the k8s manifest somehow detects the existing resource and fails with the following error (this case is the namespace creation, the rest of the manifests depend on namespace):
`Failed to create resource. Error: b'Error from server (AlreadyExists): error when creating "/tmp/manifest.yaml": namespaces "platform" already exists\n' Logs: /aws/lambda/dev-platform-eks-devplatformeksimp-Handler886CB40B-1P5PKK4LR6WYH at invokeUserFunction (/var/task/framework.js:95:19) at process._tickCallback (internal/process/next_tick.js:68:7)`

**Comment by starchx** [comment]
> We tried the hack that you suggested, renaming the manifest stack, but it seems that the Lambda Function responsable for applying the k8s manifest somehow detects the existing resource and fails with the following error (this case is the namespace creation, the rest of the manifests depend on namespace):
> `Failed to create resource. Error: b'Error from server (AlreadyExists): error when creating "/tmp/manifest.yaml": namespaces "platform" already exists\n' Logs: /aws/lambda/dev-platform-eks-devplatformeksimp-Handler886CB40B-1P5PKK4LR6WYH at invokeUserFunction (/var/task/framework.js:95:19) at process._tickCallback (internal/process/next_tick.js:68:7)`

That's because `kubectl create` was used when creating the resources initially. You can set `overwrite` to true in this case:
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-eks.KubernetesManifest.html#overwrite

**Comment by iliapolo** [comment]
@starchx Is right. I forgot to mention that.

**Comment by adrialucena-seat** [comment]
Thank you @starchx ! That worked like a charm!

What I am now struggling with is how to delete del old stack, so I'll just see one stack for the k8s resources.
I've been trying to use the Cloudformation`DeletionPolicy` attribute of every resource in the stack in order to delete the old stack but retain all the k8s resources, but I can't find a way to modify the current value `DeletionPolicy: Delete` to `DeletionPolicy: Retain`.
I don't know how to tell `KubernetesManifest` class to change this attribute. If I understood it right, `KubernetesManifest` class generates a CloudFormation `CustomResource` which has `applyRemovalPolicy` method to modify the `DeletionPolicy`, but I am unable to use this method when I get the `KubernetesManifest` object.
Any clues on that?

Thank you!!

**Comment by adrialucena-seat** [comment]
I forgot to mention that I tried to use this approach:
```
    val kubernetesManifest = KubernetesManifest(
            scope,
            id,
            KubernetesManifestProps
                    .builder()
                    .cluster(eksCluster)
                    .prune(false)
                    .manifest(mutableListOf(manifest))
                    .overwrite(override)
                    .build()
    )
    val cfnResource = kubernetesManifest.node.findChild("Resource") as CfnResource
    cfnResource.cfnOptions.deletionPolicy = CfnDeletionPolicy.RETAIN
```
but get the following error:
`Exception in thread "main" java.lang.ClassCastException: class software.amazon.awscdk.core.CustomResource cannot be cast to class software.amazon.awscdk.core.CfnResource (software.amazon.awscdk.core.CustomResource and software.amazon.awscdk.core.CfnResource are in unnamed module of loader 'app')`

So it seems the cast can't be permformed using a CustomResource.

**Comment by adrialucena-seat** [comment]
I've been able to delete the old stack by modifying manually the stack template, changing the `DeletionPolicy` to `Retain` and uploading the new template file to the old stack. Then, after deleting the stack, I create the new one using `overwrite` parameter in the `KubernetesManifest` class as @starchx suggested.

Thank you for your help!

**Comment by iliapolo** [comment]
@adrialucena-seat Glad you managed to work this out. 

I've created this [feature request](https://github.com/aws/aws-cdk/issues/13713) to discuss a nicer way of allowing this, and gather some more feedback.
