### ISSUE TITLE
aws-cdk/aws-elasticloadbalancingv2: Cyclic dependency when stack registers itself AND needs dns name

### ISSUE THREAD

**Issue by ltamrazov** [aws/aws-cdk#13492]
### The Question
Hi, we have a stack that creates a shared load balancer and other stacks that use it. I understand this set up is typical and is similar to what is discussed in https://github.com/aws/aws-cdk/issues/3689. However, in our case the subsequent stacks also require the DNS name of the load balancer (to inject it as an environment variable):

```javascript
export default class PrivateLoadBalancerStack extends core.Stack {
    public lb: elbv2.ApplicationLoadBalancer

    constructor(scope: core.Construct, id: string, props: PrivateLoadBalancerStackProps) {
        super(scope, id, props);

        this.lb = new elbv2.ApplicationLoadBalancer(...)
    }
}

export default class FargateServiceStack extends core.Stack {
    constructor(scope: core.Construct, id: string, props: FargateServiceStackProps) {
        super(scope, id, props);

        const containerProps = {
            image: ...,
            environment: {
                LB_HOST:  this.props.lb.loadBalancerDnsName, // Need dns name to talk to other services
            },
        };

        props.lb.addTarget({ ... }) // Register itself with the LB
    }
}
```

This set up creates a cyclic dependency because `addTarget` adds a dependency on FargateServiceStack and `loadBalancerDnsName` adds a dependency on the PrivateLoadBalancerStack. It seems counter intuitive that `addTarget` would create the dependency on the `FargateServiceStack`, though this is likely due my lack of understanding. Is this intended behavior? Is there a workaround or a way to break the dependency? This seems to me like a valid use case otherwise.

### Environment

  - **CDK CLI Version:** 1.91.0 (build 0f728ce)
  - **Module Version:** 1.91
  - **Node.js Version:** v14.14.0
  - **OS:** Docker Alpine
  - **Language (Version):** Version 3.9.7

Thank you!

**Comment by peterwoodworth** [comment]
Hey @ltamrazov, I'm sorry no one has responded to this yet.

I'm interested in reproducing this, but I'm getting stuck at where you're using the `lb.addTarget()` method. From what I can tell, this doesn't seem to be a method on [the ALB construct](https://github.com/aws/aws-cdk/issues/6734)

Is there something I'm missing here?
