### ISSUE TITLE
Licensing in PyPI packages

### ISSUE THREAD

**Issue by hyandell** [aws/aws-cdk#13505]
Using as an example https://pypi.org/project/aws-cdk.aws-elasticloadbalancingv2/1.92.0/#files - the PyPI packages have:

        "license": "Apache-2.0",

However their classifier is only "OSI Approved" and there is no LICENSE or NOTICE file in the root of the package.

Could the classifier be changed to:

    License :: OSI Approved :: Apache Software License

and could the LICENSE and NOTICE be included in the root of each package please.

**Comment by MrArnoldPalmer** [comment]
Pulling in @RomainMuller as my favorite license expert. Is copying license files over into pacmaked artifacts "the right way" here?

**Comment by eladb** [comment]
I don't see why we shouldn't copy the license file. The Pacmaked module is owned and licensed by the same person as the original.

**Comment by MrArnoldPalmer** [comment]
yeah I agree, seems straightforward enough. I'd imagine this should be the case across all language artifacts.
