### ISSUE TITLE
(tools): Out of Memory for `cdk`

### ISSUE THREAD

**Issue by fogfish** [aws/aws-cdk#13503]
A simple script can causes crash of node process with `JavaScript heap out of memory`.

### Reproduction Steps

Please see the gist for details. It was expected that it would crash. However, the behaviour of the tool is not expected.
https://gist.github.com/fogfish/2580fd40a24fe034ef22d6608a7f51d6

### What did you expect to happen?

When you run a tool with depth level 2 (see line 17) then you see a proper error but any large values causes OOM. Because the cap of 500 resource is well-know. It would be nice to fail fast instead of trying to "render" whole tree and count nodes afterwards.

```
Error: Number of resources: XXXX is greater than allowed maximum of 500
 ...
```

### What actually happened?

```
<--- Last few GCs --->

[39342:0x110008000]   223418 ms: Mark-sweep 3999.4 (4130.0) -> 3984.1 (4131.2) MB, 2162.2 / 0.0 ms  (average mu = 0.106, current mu = 0.017) allocation failure scavenge might not succeed
[39342:0x110008000]   225616 ms: Mark-sweep 4000.2 (4131.2) -> 3984.9 (4131.7) MB, 2162.3 / 0.0 ms  (average mu = 0.063, current mu = 0.016) allocation failure scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x1000a92ba node::Abort() [/usr/local/bin/node]
 2: 0x1000a9430 node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
 3: 0x1001deae1 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 4: 0x1001dea8b v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 5: 0x100322427 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/usr/local/bin/node]
 6: 0x100323734 v8::internal::Heap::MarkCompactPrologue() [/usr/local/bin/node]
 7: 0x100320f91 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/local/bin/node]
 8: 0x10031f51b v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
 9: 0x1003282ea v8::internal::Heap::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
10: 0x100328342 v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
11: 0x100305595 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/usr/local/bin/node]
12: 0x10058b2a2 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/usr/local/bin/node]
13: 0x10082db59 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/usr/local/bin/node]
```

### Environment

  - **CDK CLI Version  :** `1.91.0 (build 0f728ce)`
  - **Framework Version:**
  - **Node.js Version:** `v15.1.0`
  - **OS               :** `MacOS`
  - **Language (Version):** `Version 4.2.2`

### Other

--- 

This is :bug: Bug Report

**Comment by MrArnoldPalmer** [comment]
@fogfish so is what you're suggesting counting resource nodes before full tree construction to fail when this exceeds the cfn resource limit?

**Comment by fogfish** [comment]
Yes, I'd propose to count resource while constructing the tree. However, I've never looked into the code that actually maps declaration of resource to "cloud assembly". It is hard for me to say if this is an easy to make. I'd assume you are using some kind of tree visit/fold algorithms.
