### ISSUE TITLE
aws-apigateway: race condition when using restApi with cloudwatch role not yet created.

### ISSUE THREAD

**Issue by williexu** [aws/aws-cdk#13511]
Deploying a cdk stack in a new account failed due to the `CloudWatchRole` not being created before the deployment stage and restApi Account.
Error: ```CloudWatch Logs role ARN must be set in account settings to enable logging (Service: AmazonApiGateway; Status Code: 400; Error Code: BadRequestException; Request ID: 6f07d5a0-2244-43fe-83a1-e5f05306d96e; Proxy: null)```

The same stack in a different account succeeded.

### Reproduction Steps

Pretty common restApi def:
```
const restApi = new RestApi(this, "restAPI", {
      endpointConfiguration: {
        types: [EndpointType.EDGE],
      },
      deployOptions: {
        stageName: `beta`,
        dataTraceEnabled: props.dataTraceEnabled,
        loggingLevel: MethodLoggingLevel.ERROR,
      },
      domainName: {
        domainName: publicDomainName,
        certificate: certificate,
      },
      defaultCorsPreflightOptions: {
        allowOrigins: props.corsAllowOrigins,
        allowHeaders: props.corsAllowHeaders,
        allowMethods: Cors.ALL_METHODS,
        allowCredentials: true,
      },
    });
```

### What did you expect to happen?

The restApi construct to be deployed properly with child resources.

### What actually happened?

The stack failed to complete. Looking in my events list:
I see that the `CloudWatchRole` was still in `CREATE_IN_PROGRESS`.
The `RestAPI` and `Deployment` resources completed.
The `Stage` resource started creation, and then promptly failed with the error:
```
CloudWatch Logs role ARN must be set in account settings to enable logging (Service: AmazonApiGateway; Status Code: 400; Error Code: BadRequestException; Request ID: 6f07d5a0-2244-43fe-83a1-e5f05306d96e; Proxy: null)
```
Before the account and role were created.

### Environment

  - **CDK CLI Version  :**  1.75.0
  - **Framework Version:** 1.75.0
  - **Node.js Version:**  v14.16.0
  - **OS               :** MacOS
  - **Language (Version):**  Typescript

### Other

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
Thanks for filing this bug @williexu.

We're already tracking this issue here - https://github.com/aws/aws-cdk/issues/10722. Could you upvote the issue so we can assess the impact and prioritize.
