### ISSUE TITLE
Cognito: allow for app client creation and disable refresh token

### ISSUE THREAD

**Issue by mattiLeBlanc** [aws/aws-cdk#13514]
So I tried to disable the refreshToken in my appClient via the CDK but that option is not available.
Surely it must be possible to create an AppClient without using refresh token and renew the token manually.

### Use Case

We want to manage our session lifetime very strictly (banking level) and I am having issues with the minimum accesstoken lifetime of 5 minutes, combined with our 5 minute inactivity timer in our dashboard. On token expiration, cognito automatically uses the refreshtoken to get a new accesstoken just when we redirect them to a Logged out page. This creates a bug in our flow.
I either have to set our timer to 4:55 instead of 5 minutes :) or just not use the refresh token.

### Proposed Solution

```
 this.userPoolClient = new UserPoolClient(this, `${this.props.applicationName}-userpool-client`, {
      userPool: this.userPool,
      userPoolClientName: `${this.props.applicationName}-client`,
      generateSecret: false,
      authFlows: {
        userPassword: false,
        adminUserPassword: false,
        userSrp: true,
        custom: true,
        refreshToken: false.    <-----------
      },
      accessTokenValidity: Duration.minutes(5),
    });
```

**Comment by nija-at** [comment]
Hi @mattiLeBlanc -

Thanks for filing this issue. I'm afraid this is not related to the CDK, but rather about the Cognito service itself.

You will need to reach out the AWS Cognito team (via AWS support) to talk about how to correctly set up the user pool client for the flow you would like to achieve.

**Comment by mattiLeBlanc** [comment]
@nija-at Are you sure this is not CDK related since I can't configure the Cognito UserPoolClient the way I want. As in it doesn;t allow me to set `refreshToken` to false at all.

There is a good chance the lower level constructs might allow for it, but I haven't checked that and they are a bit of pain to work with.

**Comment by nija-at** [comment]
@mattiLeBlanc - you can always jump down to the lower level constructs from the higher level constructs using escape hatches - https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html#cfn_layer_raw

Let me know what you find. If there's a combination of properties that's valid using the lower level constructs, then we will need to make that available via the higher level constructs.
