### ISSUE TITLE
(iam): Over 10 management policies in a group

### ISSUE THREAD

**Issue by yukihato** [aws/aws-cdk#13515]
### The Question

When I tried to generate an IAM group using 11 managed policies, the `cdk deploy` command worked fine.
However, when I deploy the CloudFormation template output by `cdk synth`, I get a quota limit error.
(This seems to be the correct behavior)
Why didn't cdk give an error on the quota limit?

### Environment

  - **CDK CLI Version:1.91.0
  - **Module Version:1.91.0
  - **Node.js Version:v12.18.1
  - **OS:Windows 10
  - **Language (Version):Javascript

### Other

Reference:
https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_iam-quotas.html

CloudFormation error message: 
Cannot exceed quota for PoliciesPerGroup: 10 (Service: AmazonIdentityManagement; Status Code: 409; Error Code: LimitExceeded;

**Comment by rix0rrr** [comment]
> Why didn't cdk give an error on the quota limit?

Because it takes effort for us to duplicate all validations performed by all other AWS services (and subsequently to keep them updated when the service changes). We tend to optimize our development time by checking for the most common misconfigurations, not to have an exhaustive list.
