### ISSUE TITLE
[apigateway] The certificate provided must be owned by the account creating the domain

### ISSUE THREAD

**Issue by Lock128** [aws/aws-cdk#13512]
I have a manually imported certifcated in ACM in us-east-1 (not part of the CDK stack) and a EDGE API created by CDK in eu-central-1

Unfortunately when trying to deploy the stack I am getting 

> 
> 3/26 \| 1:04:21 AM \| CREATE_FAILED        \| AWS::ApiGateway::DomainName      \| Widgets/Widgets-API/CustomDomain (WidgetsWidgetsAPICustomDomainAFFC7939) Invalid request provided: The certificate provided must be owned by the account creating the domain. (Service: ApiGateway, Status Code: 400, Request ID: 368eb32d-f0e0-442e-b38e-31590def84e4, Extended Request ID: null)
> 109 | new DomainName (/tmp/jsii-kernel-g3fCMN/node_modules/@aws-cdk/aws-apigateway/lib/domain-name.js:36:26)
> 110 | \_ RestApi.addDomainName (/tmp/jsii-kernel-g3fCMN/node_modules/@aws-cdk/aws-apigateway/lib/restapi.js:83:28)
> 111 | \_ new RestApi (/tmp/jsii-kernel-g3fCMN/node_modules/@aws-cdk/aws-apigateway/lib/restapi.js:409:18)
> 112 | \_ /tmp/jsii-java-runtime2101771176231171458/lib/program.js:2720:58
> 113 | \_ Kernel._wrapSandboxCode (/tmp/jsii-java-runtime2101771176231171458/lib/program.js:3148:24)
> 114 | \_ Kernel._create (/tmp/jsii-java-runtime2101771176231171458/lib/program.js:2720:34)
> 115 | \_ Kernel.create (/tmp/jsii-java-runtime2101771176231171458/lib/program.js:2461:29)
> 116 | \_ KernelHost.processRequest (/tmp/jsii-java-runtime2101771176231171458/lib/program.js:9457:36)
> 117 | \_ KernelHost.run (/tmp/jsii-java-runtime2101771176231171458/lib/program.js:9420:22)
> 118 | \_ Immediate._onImmediate (/tmp/jsii-java-runtime2101771176231171458/lib/program.js:9421:46)
> 119 | \_ processImmediate (internal/timers.js:461:21)

### Reproduction Steps

Java code used for API:

> String domainName = "api.domain.com";
> 		SecurityPolicy securityPolicy = SecurityPolicy.TLS_1_2;
> 		String certificateArn = "arn:aws:acm:us-east-1:acc:certificate/arn";
> 		ICertificate certificate = Certificate.fromCertificateArn(this, "sslCertificate", certificateArn);
> 		RestApi api = RestApi.Builder.create(this, "Widgets-API").restApiName("Widget Service")
> 				.description("This service services widgets.").domainName(DomainNameOptions.builder()
> 						.domainName(domainName).securityPolicy(securityPolicy).certificate(certificate).build())
> 				.build();

### What did you expect to happen?

I was expecting that "api.domain.com" is created as custom domain for the API Gateway

### What actually happened?

Got the error message mentioned above

### Environment

  - **CDK CLI Version  :** 1.91.0 (build 0f728ce)
  - **Framework Version:**
  - **Node.js Version:** v15.8.0
  - **OS               :**  LinuxBuildImage.AMAZON_LINUX_2_3
  - **Language (Version):** Java 11

### Other

see above

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
Hey @Lock128 -

This doesn't seem to be related to the CDK.

According to the issue you've linked - https://github.com/aws/aws-cdk/issues/9548 - it seems that the certificate and ApiGateway need to be in the same region and account. However, I'm not intimately aware of the requirements and limitations of ACM.

You will need to contact the relevant teams via AWS support. Let us know if I misunderstood something here and requires attention from the CDK.

**Comment by Lock128** [comment]
Hey @nija-at 

I think t his is a CDK issue as somewhere it automatically references the certificate in the wrong region (in eu-central-1 where the apigateway is deployed, however due to the nature of the APIGateway using cloudfront to provide the HTTPS functionality, the certificate needs to be placed in the us-east-1 region).

Manually I was able to set up the set up the customdomain

Regards
Johannes

**Comment by nija-at** [comment]
Hey @Lock128 - Thanks for your response. 

You will need to provide a code sample and reproduction steps for me to proceed.

**Comment by Lock128** [comment]
..just execute "cdk deploy" and you get

[```
0%] start: Publishing f0028501cc449d6ff9b4b9782cc90e006a0df17f7336b40bbda3d2c82ae12d25:current
[100%] success: Published f0028501cc449d6ff9b4b9782cc90e006a0df17f7336b40bbda3d2c82ae12d25:current
AwsCdk13512Stack: creating CloudFormation changeset...
  0/23 | 4:44:02 PM | REVIEW_IN_PROGRESS   | AWS::CloudFormation::Stack       | AwsCdk13512Stack User Initiated
  0/23 | 4:44:08 PM | CREATE_IN_PROGRESS   | AWS::CloudFormation::Stack       | AwsCdk13512Stack User Initiated
  2/23 | 4:44:29 PM | CREATE_IN_PROGRESS   | AWS::S3::Bucket                  | WidgetStore (WidgetStoreDA467545)
  2/23 | 4:44:29 PM | CREATE_IN_PROGRESS   | AWS::CDK::Metadata               | CDKMetadata/Default (CDKMetadata)
  2/23 | 4:44:29 PM | CREATE_IN_PROGRESS   | AWS::ApiGateway::DomainName      | Widgets-API/CustomDomain (WidgetsAPICustomDomainDC6E303E)
  2/23 | 4:44:29 PM | CREATE_IN_PROGRESS   | AWS::ApiGateway::RestApi         | Widgets-API (WidgetsAPIE2DF7F47)
  2/23 | 4:44:29 PM | CREATE_IN_PROGRESS   | AWS::IAM::Role                   | Widgets-API/CloudWatchRole (WidgetsAPICloudWatchRole4BA3E757)
  2/23 | 4:44:30 PM | CREATE_IN_PROGRESS   | AWS::IAM::Role                   | WidgetHandler/ServiceRole (WidgetHandlerServiceRole455C9244)
  2/23 | 4:44:30 PM | CREATE_IN_PROGRESS   | AWS::ApiGateway::RestApi         | Widgets-API (WidgetsAPIE2DF7F47) Resource creation Initiated
  2/23 | 4:44:30 PM | CREATE_IN_PROGRESS   | AWS::IAM::Role                   | Widgets-API/CloudWatchRole (WidgetsAPICloudWatchRole4BA3E757) Resource creation Initiated
  2/23 | 4:44:30 PM | CREATE_IN_PROGRESS   | AWS::IAM::Role                   | WidgetHandler/ServiceRole (WidgetHandlerServiceRole455C9244) Resource creation Initiated
  2/23 | 4:44:30 PM | CREATE_COMPLETE      | AWS::ApiGateway::RestApi         | Widgets-API (WidgetsAPIE2DF7F47)
  2/23 | 4:44:30 PM | CREATE_IN_PROGRESS   | AWS::S3::Bucket                  | WidgetStore (WidgetStoreDA467545) Resource creation Initiated
  2/23 | 4:44:31 PM | CREATE_IN_PROGRESS   | AWS::CDK::Metadata               | CDKMetadata/Default (CDKMetadata) Resource creation Initiated
  2/23 | 4:44:31 PM | CREATE_COMPLETE      | AWS::CDK::Metadata               | CDKMetadata/Default (CDKMetadata)
  2/23 | 4:44:31 PM | CREATE_IN_PROGRESS   | AWS::ApiGateway::Resource        | Widgets-API/Default/{id} (WidgetsAPIidC26E0BEE)
  2/23 | 4:44:32 PM | CREATE_FAILED        | AWS::ApiGateway::DomainName      | Widgets-API/CustomDomain (WidgetsAPICustomDomainDC6E303E) Invalid request provided: The certificate provided must be owned by the account creating the domain. (Service: ApiGateway, Status Code: 400, Request ID: c9854821-7b46-4b43-98e6-d15f82543675, Extended Request ID: null)
        new DomainName (C:\Users\JOHANN~1\AppData\Local\Temp\jsii-kernel-vtuFiz\node_modules\@aws-cdk\aws-apigateway\lib\domain-name.js:36:26)
        \_ RestApi.addDomainName (C:\Users\JOHANN~1\AppData\Local\Temp\jsii-kernel-vtuFiz\node_modules\@aws-cdk\aws-apigateway\lib\restapi.js:83:28)
        \_ new RestApi (C:\Users\JOHANN~1\AppData\Local\Temp\jsii-kernel-vtuFiz\node_modules\@aws-cdk\aws-apigateway\lib\restapi.js:409:18)
        \_ C:\Users\JOHANN~1\AppData\Local\Temp\jsii-java-runtime7394644670692665525\lib\program.js:8154:58
        \_ Kernel._wrapSandboxCode (C:\Users\JOHANN~1\AppData\Local\Temp\jsii-java-runtime7394644670692665525\lib\program.js:8582:24)
        \_ Kernel._create (C:\Users\JOHANN~1\AppData\Local\Temp\jsii-java-runtime7394644670692665525\lib\program.js:8154:34)
        \_ Kernel.create (C:\Users\JOHANN~1\AppData\Local\Temp\jsii-java-runtime7394644670692665525\lib\program.js:7895:29)
        \_ KernelHost.processRequest (C:\Users\JOHANN~1\AppData\Local\Temp\jsii-java-runtime7394644670692665525\lib\program.js:9479:36)
        \_ KernelHost.run (C:\Users\JOHANN~1\AppData\Local\Temp\jsii-java-runtime7394644670692665525\lib\program.js:9442:22)
        \_ Immediate._onImmediate (C:\Users\JOHANN~1\AppData\Local\Temp\jsii-java-runtime7394644670692665525\lib\program.js:9443:46)
        \_ processImmediate (node:internal/timers:463:21)
  2/23 | 4:44:32 PM | CREATE_IN_PROGRESS   | AWS::ApiGateway::Resource        | Widgets-API/Default/{id} (WidgetsAPIidC26E0BEE) Resource creation Initiated
  2/23 | 4:44:32 PM | CREATE_FAILED        | AWS::IAM::Role                   | Widgets-API/CloudWatchRole (WidgetsAPICloudWatchRole4BA3E757) Resource creation cancelled
        new Role (C:\Users\JOHANN~1\AppData\Local\Temp\jsii-kernel-vtuFiz\node_modules\@aws-cdk\aws-iam\lib\role.js:72:22)
        \_ RestApi.configureCloudWatchRole (C:\Users\JOHANN~1\AppData\Local\Temp\jsii-kernel-vtuFiz\node_modules\@aws-cdk\aws-apigateway\lib\restapi.js:250:22)
        \_ new RestApi (C:\Users\JOHANN~1\AppData\Local\Temp\jsii-kernel-vtuFiz\node_modules\@aws-cdk\aws-apigateway\lib\restapi.js:405:18)
        \_ C:\Users\JOHANN~1\AppData\Local\Temp\jsii-java-runtime7394644670692665525\lib\program.js:8154:58
        \_ Kernel._wrapSandboxCode (C:\Users\JOHANN~1\AppData\Local\Temp\jsii-java-runtime7394644670692665525\lib\program.js:8582:24)
        \_ Kernel._create (C:\Users\JOHANN~1\AppData\Local\Temp\jsii-java-runtime7394644670692665525\lib\program.js:8154:34)
        \_ Kernel.create (C:\Users\JOHANN~1\AppData\Local\Temp\jsii-java-runtime7394644670692665525\lib\program.js:7895:29)
        \_ KernelHost.processRequest (C:\Users\JOHANN~1\AppData\Local\Temp\jsii-java-runtime7394644670692665525\lib\program.js:9479:36)
        \_ KernelHost.run (C:\Users\JOHANN~1\AppData\Local\Temp\jsii-java-runtime7394644670692665525\lib\program.js:9442:22)
        \_ Immediate._onImmediate (C:\Users\JOHANN~1\AppData\Local\Temp\jsii-java-runtime7394644670692665525\lib\program.js:9443:46)
        \_ processImmediate (node:internal/timers:463:21)
  2/23 | 4:44:32 PM | CREATE_FAILED        | AWS::IAM::Role                   | WidgetHandler/ServiceRole (WidgetHandlerServiceRole455C9244) Resource creation cancelled
        new Role (C:\Users\JOHANN~1\AppData\Local\Temp\jsii-kernel-vtuFiz\node_modules\@aws-cdk\aws-iam\lib\role.js:72:22)
        \_ new Function (C:\Users\JOHANN~1\AppData\Local\Temp\jsii-kernel-vtuFiz\node_modules\@aws-cdk\aws-lambda\lib\function.js:79:35)
        \_ C:\Users\JOHANN~1\AppData\Local\Temp\jsii-java-runtime7394644670692665525\lib\program.js:8154:58
        \_ Kernel._wrapSandboxCode (C:\Users\JOHANN~1\AppData\Local\Temp\jsii-java-runtime7394644670692665525\lib\program.js:8582:24)
        \_ Kernel._create (C:\Users\JOHANN~1\AppData\Local\Temp\jsii-java-runtime7394644670692665525\lib\program.js:8154:34)
        \_ Kernel.create (C:\Users\JOHANN~1\AppData\Local\Temp\jsii-java-runtime7394644670692665525\lib\program.js:7895:29)
        \_ KernelHost.processRequest (C:\Users\JOHANN~1\AppData\Local\Temp\jsii-java-runtime7394644670692665525\lib\program.js:9479:36)
        \_ KernelHost.run (C:\Users\JOHANN~1\AppData\Local\Temp\jsii-java-runtime7394644670692665525\lib\program.js:9442:22)
        \_ Immediate._onImmediate (C:\Users\JOHANN~1\AppData\Local\Temp\jsii-java-runtime7394644670692665525\lib\program.js:9443:46)
        \_ processImmediate (node:internal/timers:463:21)
  2/23 | 4:44:32 PM | CREATE_FAILED        | AWS::S3::Bucket                  | WidgetStore (WidgetStoreDA467545) Resource creation cancelled
        new Bucket (C:\Users\JOHANN~1\AppData\Local\Temp\jsii-kernel-vtuFiz\node_modules\@aws-cdk\aws-s3\lib\bucket.js:521:26)
        \_ C:\Users\JOHANN~1\AppData\Local\Temp\jsii-java-runtime7394644670692665525\lib\program.js:8154:58
        \_ Kernel._wrapSandboxCode (C:\Users\JOHANN~1\AppData\Local\Temp\jsii-java-runtime7394644670692665525\lib\program.js:8582:24)
        \_ Kernel._create (C:\Users\JOHANN~1\AppData\Local\Temp\jsii-java-runtime7394644670692665525\lib\program.js:8154:34)
        \_ Kernel.create (C:\Users\JOHANN~1\AppData\Local\Temp\jsii-java-runtime7394644670692665525\lib\program.js:7895:29)
        \_ KernelHost.processRequest (C:\Users\JOHANN~1\AppData\Local\Temp\jsii-java-runtime7394644670692665525\lib\program.js:9479:36)
        \_ KernelHost.run (C:\Users\JOHANN~1\AppData\Local\Temp\jsii-java-runtime7394644670692665525\lib\program.js:9442:22)
        \_ Immediate._onImmediate (C:\Users\JOHANN~1\AppData\Local\Temp\jsii-java-runtime7394644670692665525\lib\program.js:9443:46)
        \_ processImmediate (node:internal/timers:463:21)
  2/23 | 4:44:32 PM | CREATE_FAILED        | AWS::ApiGateway::Resource        | Widgets-API/Default/{id} (WidgetsAPIidC26E0BEE) Resource creation cancelled
        new Resource (C:\Users\JOHANN~1\AppData\Local\Temp\jsii-kernel-vtuFiz\node_modules\@aws-cdk\aws-apigateway\lib\resource.js:231:26)
        \_ RootResource.addResource (C:\Users\JOHANN~1\AppData\Local\Temp\jsii-kernel-vtuFiz\node_modules\@aws-cdk\aws-apigateway\lib\resource.js:28:16)
        \_ C:\Users\JOHANN~1\AppData\Local\Temp\jsii-java-runtime7394644670692665525\lib\program.js:7970:134
        \_ Kernel._wrapSandboxCode (C:\Users\JOHANN~1\AppData\Local\Temp\jsii-java-runtime7394644670692665525\lib\program.js:8582:24)
        \_ C:\Users\JOHANN~1\AppData\Local\Temp\jsii-java-runtime7394644670692665525\lib\program.js:7970:107
        \_ Kernel._ensureSync (C:\Users\JOHANN~1\AppData\Local\Temp\jsii-java-runtime7394644670692665525\lib\program.js:8563:28)
        \_ Kernel.invoke (C:\Users\JOHANN~1\AppData\Local\Temp\jsii-java-runtime7394644670692665525\lib\program.js:7970:34)
        \_ KernelHost.processRequest (C:\Users\JOHANN~1\AppData\Local\Temp\jsii-java-runtime7394644670692665525\lib\program.js:9479:36)
        \_ KernelHost.run (C:\Users\JOHANN~1\AppData\Local\Temp\jsii-java-runtime7394644670692665525\lib\program.js:9442:22)
        \_ Immediate._onImmediate (C:\Users\JOHANN~1\AppData\Local\Temp\jsii-java-runtime7394644670692665525\lib\program.js:9443:46)
        \_ processImmediate (node:internal/timers:463:21)
  2/23 | 4:44:33 PM | ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack       | AwsCdk13512Stack The following resource(s) failed to create: [WidgetStoreDA467545, WidgetsAPIidC26E0BEE, WidgetHandlerServiceRole455C9244, WidgetsAPICloudWatchRole4BA3E757, WidgetsAPICustomDomainDC6E303E]. Rollback requested by user.
  4/23 | 4:44:36 PM | DELETE_IN_PROGRESS   | AWS::CDK::Metadata               | CDKMetadata/Default (CDKMetadata)
  4/23 | 4:44:36 PM | DELETE_IN_PROGRESS   | AWS::IAM::Role                   | WidgetHandler/ServiceRole (WidgetHandlerServiceRole455C9244)
  4/23 | 4:44:36 PM | DELETE_IN_PROGRESS   | AWS::IAM::Role                   | Widgets-API/CloudWatchRole (WidgetsAPICloudWatchRole4BA3E757)
  4/23 | 4:44:36 PM | DELETE_IN_PROGRESS   | AWS::ApiGateway::Resource        | Widgets-API/Default/{id} (WidgetsAPIidC26E0BEE)
  4/23 | 4:44:36 PM | DELETE_SKIPPED       | AWS::S3::Bucket                  | WidgetStore (WidgetStoreDA467545)
  4/23 | 4:44:36 PM | DELETE_COMPLETE      | AWS::ApiGateway::DomainName      | Widgets-API/CustomDomain (WidgetsAPICustomDomainDC6E303E)
  4/23 | 4:44:37 PM | DELETE_COMPLETE      | AWS::ApiGateway::Resource        | Widgets-API/Default/{id} (WidgetsAPIidC26E0BEE)
  4/23 | 4:44:37 PM | DELETE_COMPLETE      | AWS::CDK::Metadata               | CDKMetadata/Default (CDKMetadata)
  4/23 | 4:44:37 PM | DELETE_IN_PROGRESS   | AWS::ApiGateway::RestApi         | Widgets-API (WidgetsAPIE2DF7F47)
  4/23 | 4:44:37 PM | DELETE_COMPLETE      | AWS::IAM::Role                   | WidgetHandler/ServiceRole (WidgetHandlerServiceRole455C9244)
  4/23 | 4:44:38 PM | DELETE_COMPLETE      | AWS::IAM::Role                   | Widgets-API/CloudWatchRole (WidgetsAPICloudWatchRole4BA3E757)
  4/23 | 4:44:38 PM | DELETE_COMPLETE      | AWS::ApiGateway::RestApi         | Widgets-API (WidgetsAPIE2DF7F47)
  5/23 | 4:44:38 PM | ROLLBACK_COMPLETE    | AWS::CloudFormation::Stack       | AwsCdk13512Stack

 ❌  AwsCdk13512Stack failed: Error: The stack named AwsCdk13512Stack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE
    at Object.waitForStackDeploy (C:\Users\JohannesKoch\AppData\Roaming\npm\node_modules\aws-cdk\lib\api\util\cloudformation.ts:305:11)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at Object.deployStack (C:\Users\JohannesKoch\AppData\Roaming\npm\node_modules\aws-cdk\lib\api\deploy-stack.ts:291:26)
    at CdkToolkit.deploy (C:\Users\JohannesKoch\AppData\Roaming\npm\node_modules\aws-cdk\lib\cdk-toolkit.ts:180:24)
    at initCommandLine (C:\Users\JohannesKoch\AppData\Roaming\npm\node_modules\aws-cdk\bin\cdk.ts:207:9)
The stack named AwsCdk13512Stack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE
```

**Comment by Lock128** [comment]
C:\Users\JohannesKoch\git-private\aws-cdk-13512>cdk --version
1.91.0 (build 0f728ce)

**Comment by nija-at** [comment]
The generated template, references the ARN only in one place, namely the [`RegionalCertificateArn` property](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-domainname.html#cfn-apigateway-domainname-regionalcertificatearn) and it contains the correct region information -

```
    "WidgetsAPICustomDomainDC6E303E": {
      "Type": "AWS::ApiGateway::DomainName",
      "Properties": {
        "DomainName": "<##redacted##>",
        "EndpointConfiguration": {
          "Types": [
            "REGIONAL"
          ]
        },
        "RegionalCertificateArn": "<##redacted##>",
        "SecurityPolicy": "TLS_1_2"
      },
      "Metadata": {
        "aws:cdk:path": "AwsCdk13512Stack/Widgets-API/CustomDomain/Resource"
      }
    },
```

I'm still suspecting that this is something with APIGateway and CloudFormation. 

As far as I can tell, I cannot see any other incorrect reference of region.

**Comment by vsuzdaltsev** [comment]
having the same issue
