### ISSUE TITLE
(aws-cloudwatch): Invalid MetricDataQuery Id is generated for alarms

### ISSUE THREAD

**Issue by manumaki** [aws/aws-cdk#13535]
Since version 1.92.0 (works with 1.91.0) we are unable to create CloudWatch alarms. I believe the issue was introduced in this [PR](https://github.com/aws/aws-cdk/pull/13070). 

The problem is already in the unit test, which generates wrong kind of `Id` for the `MetricDataQuery`:

```
        "Alarm2A7122E13": {
            "Type": "AWS::CloudWatch::Alarm",
            "Properties": {
                "Metrics": [
                    {
                        "Id": "Metric",
                        "Label": "Metric [AVG: ${AVG}]",
                        "MetricStat": {
                            "Metric": {
                                "MetricName": "Metric",
                                "Namespace": "CDK/Test"
                            },
                            "Period": 300,
                            "Stat": "Average"
                        },
                        "ReturnData": true
                    }
                ],
                "ComparisonOperator": "GreaterThanOrEqualToThreshold",
                "EvaluationPeriods": 3,
                "Threshold": 100
            }
        }
```

The `Id` here is `Metric` (while the first letter should be lower-cased). In the CloudFormation specification for [AWS::CloudWatch::Alarm](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudwatch-alarm-metricdataquery.html), it says:

"_A short name used to tie this object to the results in the response. This name must be unique within a single call to GetMetricData. If you are performing math expressions on this set of data, this name represents that data and can serve as a variable in the mathematical expression. The valid characters are letters, numbers, and underscore. **The first character must be a lowercase letter**._"

In our case the `Id` is `CPUUtilization` and it the CloudFormation stack fails to deploy saying `Invalid metrics list`. Changing it manually to `cPUUtilization` makes it work.

I haven't found how to fix this in the CDK code written in TS yet.

### Reproduction Steps

```
  const runningCountMetric = fargateService.metricCpuUtilization({
    period: Duration.minutes(1),
    statistic: "SampleCount",
    label: "RunningTaskCount"
  })

  const noRunningTasksAlarm = new Alarm(
    stack,
    "AlarmNoRunningTasks",
    {
      alarmName: `test-cluster/test-service: No running tasks`,
      alarmDescription: `Service test-service in cluster test-cluster has no running tasks`,
      threshold: 0,
      metric: runningCountMetric,
      comparisonOperator: ComparisonOperator.LESS_THAN_OR_EQUAL_TO_THRESHOLD,
      evaluationPeriods: 5,
      treatMissingData: TreatMissingData.BREACHING
    }
  )
```

### Environment

  - **CDK CLI Version**  : v1.92.0 
  - **Node.js Version:** v14.15.4
  - **Language (Version):** TypeScript 

--- 

This is :bug: Bug Report

**Comment by shamelesscookie** [comment]
+1. Problem still exists in 1.93.0.  Your workaround of using a lowercase metric name worked for me as well, thanks.

**Comment by NetaNir** [comment]
Yup seems nasty :/ , sorry about that. This was fixed in https://github.com/aws/aws-cdk/commit/278029f25b41d956091835364e5a8de91429712c, and will be shipped with the next release (1.94.0).

**Comment by vamega** [comment]
I think this can be closed now since 1.94.0 has been released?

**Comment by manumaki** [comment]
Yes the fix works great! Thanks!

**Comment by PatMyron** [comment]
caught in `cfn-lint` now as well:
https://github.com/aws-cloudformation/cfn-python-lint/issues/1944
