### ISSUE TITLE
(aws-eks): Cluster.DefaultCapacity set from CfnParameter.ValueAsNumber results in 0 nodes after cluster is created

### ISSUE THREAD

**Issue by vgribok** [aws/aws-cdk#13533]
Cluster construct, `DefaultCapacity` (number/double) property can't be set from CfnParameter.ValueAsNumber. When attempted, results in cluster with no nodes.

### Reproduction Steps

```C#
using Amazon.CDK;
using Amazon.CDK.AWS.EKS;

namespace DaprOnAwsCdk
{
    public class DaprOnAwsCdkStack : Stack
    {
        internal DaprOnAwsCdkStack(Construct scope, string id, IStackProps props = null) : base(scope, id, props)
        {
            var instanceCountParam = new CfnParameter(this, "InstanceCount", new CfnParameterProps{
				Default = 3,
				Description = "Initial number of worker node VMs",
				Type = "Number"
			  });

            var cluster = new Cluster(this, "eks-cluster", new ClusterProps {
                DefaultCapacity = instanceCountParam.ValueAsNumber,
                Version = KubernetesVersion.V1_19,
            });
        }
    }
}
```

### What did you expect to happen?

EKS cluster with 3 EC2 nodes created. Instead 0 nodes are created. 

Create an EKS cluster where initial capacity is parameter-driven.

### What actually happened?
EKS cluster was created with 0 nodes, resulting in no ability to run workloads on the cluster.

No errors, just silently creating zero-node cluster.

### Environment

  - **CDK CLI Version  :** 1.92.0
  - **Framework Version:** 1.92.0
  - **Node.js Version:**  15.5.0
  - **OS               :** Windows 10
  - **Language (Version):**  C# 8, .NET Core 3.1

### Other

When debugging, ValueAsNumber returns -1.8881545897087546e+289 or something.

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment]
@vgribok Thanks for reporting this. 

The reason this happens is because upon cluster instantiation, the `DefaultCapacity` property conditionally controls whether or not to create a node-group, and this conditional logic currently doesn't take into account the fact it can be a token.

You can workaround this issue by explicitly creating the nodegroup:

```ts
const clusterCapacityParameter = new cdk.CfnParameter(this, 'ClusterCapacity', {
  default: 3,
  description: 'The number of nodes in the EKS cluster',
  type: 'Number'
});

const cluster = new eks.Cluster(this, "EKSCluster", {
  version: eks.KubernetesVersion.V1_18,
  defaultCapacity: 0
});

cluster.addNodegroupCapacity('node-group', {
  minSize: clusterCapacityParameter.valueAsNumber
});
``

**Comment by vgribok** [comment]
Thanks. That's a good enough workaround. I ended up using cdk context for parameters. Using cfn parameters adds risks, and if one runs 'cdk deploy' in there ci/cd pipeline rather then committing synthesized cfn stacks, then using cfn parameters becomes mostly pointless.
