### ISSUE TITLE
(aws-stepfunctions-tasks): StepFunctionsStartExecution accepts invalid input type

### ISSUE THREAD

**Issue by rrhodes** [aws/aws-cdk#13548]
StepFunctionsStartExecution supports an `input` argument of type [TaskInput](https://docs.aws.amazon.com/cdk/api/latest/typescript/api/aws-stepfunctions/taskinput.html). If I pass in a value which is not of type `TaskInput`, CDK successfully built and deployed the Step Functions task, but ignored the input argument. In other words, a CloudFormation template was generated and deployed, but the task input was not included in the template.

### Reproduction Steps
```typescript
new StepFunctionsStartExecution(this, 'ExampleStateMachineStartExecution', {
  input: TaskInput.fromDataAt('$.exampleJsonPath').value,
  stateMachine: 'example-state-machine',
});
```

### What did you expect to happen?
CDK raises an error at build time because `TaskInput.fromDataAt('$.exampleJsonPath').value` is not of type `TaskInput`.

### What actually happened?
CDK successfully built and deployed the stack. `input` was not included in the generated CloudFormation template.

### Environment
  - CDK Version : 1.75.0
  - Language (Version): TypeScript (3.7.5)
--- 

This is :bug: Bug Report

**Comment by rrhodes** [comment]
Looking further into this, I think the issue lies in the [_renderTask method](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-stepfunctions-tasks/lib/stepfunctions/start-execution.ts#L76), where `this.props.input` evaluates true, it extracts `.value` from something which is not `TaskInput`, leaving us with undefined input. Happy to try and produce a fix for this.

**Comment by rrhodes** [comment]
Hi @shivlaks, not heard any updates here or on the PR. Anything further I can do to help move this along?

**Comment by shivlaks** [comment]
what if you used the `TaskInput` without the `.value`? does that render as you would expect?

```
input: TaskInput.fromDataAt('$.exampleJsonPath'),
```

**Comment by rrhodes** [comment]
@shivlaks, yes, your example would render correctly. When input of type `TaskInput` is provided, the `StepFunctionsStartExecution` task builds and deploys as expected. My issue lies with erroneous input. When, say, a string is provided, I expect that to be captured and raised as a problem at build time. Currently that's not the case.

**Comment by rrhodes** [comment]
It appears the same problem arises in `LambdaInvoke`, which uses `TaskInput` for its `payload` property.
