### ISSUE TITLE
DynamoDB: Add stream to external DynamoDB table

### ISSUE THREAD

**Issue by ShepelievD** [aws/aws-cdk#13543]
I used to use AppSync and created DynamoDB tables via GraphQL "@model" directive. I've switched to CDK and I need to turn on streams for a DynamoDB table. Right now according to the documentation I can do it only with a table I created using 
CDK with the following code:

```
const commentsTable = new DynamoDB.Table(this, 'commentsTable', {
  tableName: `Comment`,
  partitionKey: {
    name: 'id',
    type: DynamoDB.AttributeType.NUMBER
  },
  stream: DynamoDB.StreamViewType.NEW_AND_OLD_IMAGES
})
```

How can I do it with the existing table like this:
```
const commentsTable = DynamoDB.Table.fromTableAttributes(this, 'commentsTable', {
    tableName: `Comment`
})
```

Please help me. Thanks

---

This is a 📕 documentation issue

**Comment by RomainMuller** [comment]
Hey @ShepelievD 

You'll need to obtain the Table Stream ARN from the AWS Console, CLI or API, then specify the `tableStreamArn` property when you call `DynamoDB.Table.fromTableAttributes`.

If the table does NOT have streams enabled yet - unfortunately it is not possible to "enable" that without resorting to a custom resource implementation... As there is not dedicated resource for a DynamoDB Table Stream in CloudFormation -- those are created at the same time as the table (so if your app does not _create_ the table, then it cannot "easily" modify it).

**Comment by peterwoodworth** [comment]
Hey @ShepelievD, has the above advice helped at all?
