### ISSUE TITLE
AWS CDK Sns Topic as Target for EventRule

### ISSUE THREAD

**Issue by zakriya753** [aws/aws-cdk#13540]
Below Cdk code gives issue when adding topic as target.
    
    const asg_fail_topic = new sns.Topic(this, 'ASGNotifTopic', {
      displayName: `asg-notif-alarm-${stackSuffix}`
    });
    const eventRule =  new events.Rule(this, 'Asg-Rule', {
      eventPattern: {
          source: [
              'aws.autoscaling'
          ],
          detail: {
            'AutoScalingGroupName': [
              backendASG.autoScalingGroupName
            ]
          },
          detailType: [
            'EC2 Instance Launch Unsuccessful'
        ],
      }
    });
    eventRule.addTarget(new rule_targets.SnsTopic(asg_fail_topic))
    
    I am using the above code in cdk the last line gives following error
    "Argument of type topic is not assignable to parameter of type ITopic.
    Property env is missing in Topic but required in ITopic"

**Comment by MrArnoldPalmer** [comment]
Hey there! I'm unable to reproduce this with the current module version v1.93.0. Are all of your CDK modules using the same version? If they are all the same version, what version are you using?

Here is the full stack I'm using
```typescript
import * as sns from '@aws-cdk/aws-sns';
import * as events from '@aws-cdk/aws-events';
import * as events_targets from '@aws-cdk/aws-events-targets';

export class Issue13540Stack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const topic = new sns.Topic(this, 'SnsTopic');
    const eventRule =  new events.Rule(this, 'EventRule');
    const target = new events_targets.SnsTopic(topic);
    eventRule.addTarget(target);
  }
}
```

**Comment by zakriya753** [comment]
Thanks for the response. 
The issue was difference in version, using same version for all fixed it.
