### ISSUE TITLE
codepipeline: support stage concurrency (automatic RunOrder)

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#1355]
We found out that it might be useful to be able to specify a `concurrency` limit at the stage level and have the pipeline automatically allocate `RunOrder `to each action.

Here is an example for how we implemented this in aws-delivlib: https://github.com/awslabs/aws-delivlib/pull/9

**Comment by rix0rrr** [comment]
I would like to add to this feature request: it should do dataflow analysis on the artifacts and properly schedule actions in tranches if they need to run sequentially.

**Comment by eladb** [comment]
Delivlib has some logic that implements something like this (albeit less sophisticated)
