### ISSUE TITLE
(core,cloudfront): Catch 22 with Lambda@Edge custom resource runtime

### ISSUE THREAD

**Issue by robertd** [aws/aws-cdk#13551]
Continuation of discussion from https://github.com/aws/aws-cdk/pull/13301

> @viniciuskneves You're correct... Lambda@Edge doesn't but custom resource lambda does (inline version).
> 
> ![image](https://user-images.githubusercontent.com/31543/110833263-7addf980-8259-11eb-8aec-760eff2f28c0.png)
> 
> ![image](https://user-images.githubusercontent.com/31543/110833145-60a41b80-8259-11eb-9b34-d6912e8add67.png)
> 
> @nija-at @rix0rrr @njlynch Any thoughts on how to handle this catch 22?
> 
> Should we revert custom resource to use Node 12 only? Or should we put checks in place for Lambda@Edge since it's experimental feature at the moment?

* [x] :wave: I may be able to implement this change

**Comment by robertd** [comment]
cc @viniciuskneves (not sure why Github didn't pick you up as participant)

**Comment by njlynch** [comment]
@robertd  - Is this really a catch-22? I think I'm missing why... At the surface, Lambda@Edge doesn't support Node 14. That's absolutely something we can special-case validate for. See #9833 which is a catch-all issue for adding additional validation to the `_checkEdgeCompatibility` function. The `EdgeFunction` `CustomResource` which grabs the us-east-1 function ARN can use Node 12, 14, etc.; that's completely independent of the actual runtime of the Lambda@Edge function.

**Comment by robertd** [comment]
@njlynch catch-22 in the sense that Lambda@Edge is build on top of custom resources (due to us-east-1 target) and custom resources allow use of Node14, but Lambda@Edge itself is not Node14 ready according to the docs :)...

https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-requirements-limits.html#lambda-requirements-lambda-function-configuration (although docs are somewhat stale too)

Also, since `EdgeFunctionProperties` extend `LambdaFunctionProperties` one can easily override Lambda@Edge runtime... thus causing @viniciuskneves 's error.

That's my understanding.... Am I missing something?

**Comment by robertd** [comment]
@viniciuskneves what exact error are you getting?

**Comment by robertd** [comment]
@njlynch Sorry for the false alarm... I was running by what's in docs and I didn't really check if Lambda@Edge supports NodeJS14 myself.

**Comment by robertd** [comment]
Im closing this issue. @viniciuskneves let us know if this needs to reopened if you’re still experiencing issues.

**Comment by viniciuskneves** [comment]
Hey @robertd, sorry for the "late" response, I'm in another timezone I think hehehe

So, I just updated my stack to use Node 14 and I get the following:

> UPDATE_FAILED        | AWS::CloudFront::Distribution                   | sliderstestdistributionCFF253BB
Invalid request provided: The function has a runtime that is not supported by Lambda@Edge: nodejs14.x Function: *** Supported runtimes: [nodejs12.x, nodejs8.10, nodejs10.x, nodejs6.10, python3.7, python3.8] (Service: CloudFront, Status Code: 400, Request ID: ***, Extended Request ID: null)

My Lambda setup is quite simple at the moment:

```javascript
const edgeFunction = new experimental.EdgeFunction(this, 'SlidersLambdaEdge', {
  runtime: Runtime.NODEJS_14_X,
  handler: 'edge.handler',
  code: Code.fromAsset('./lambda'),
});
```

Does it help or do you need more details?

**Comment by njlynch** [comment]
> catch-22 in the sense that Lambda@Edge is build on top of custom resources

@robertd - That doesn't matter though... Ultimately, what can't run Node 14 is the Function that lives in us-east-1 and is attached to a CloudFront distribution. The fact that the `EdgeFunction` construct makes use of a Custom Resource to read the ARN of the us-east-1 Function is irrelevant.

@viniciuskneves  - Correct. Lambda@Edge does not support Node 14 at the moment (according to both the docs and the error you've received). You'll need to run with Node 12 for the moment until they add support for Node 14.

**Comment by viniciuskneves** [comment]
@njlynch yep, I get that. M question is: does it make sense to keep [accepting Node 14 in the cloudfront.experimental.EdgeFunction](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-cloudfront/lib/experimental/edge-function.ts#L20-L27)?

Would it be any good to add it in the docs?

**Comment by njlynch** [comment]
We absolutely can and should add validation to let users know the deployment will fail with Node 14. This is part of #9833, which I linked above. PRs welcome!

**Comment by robertd** [comment]
>@robertd - That doesn't matter though... Ultimately, what can't run Node 14 is the Function that lives in us-east-1 and is attached to a CloudFront distribution. The fact that the EdgeFunction construct makes use of a Custom Resource to read the ARN of the us-east-1 Function is irrelevant.

@njlynch Ahhh... thanks for clarifying that. I believe the whole misunderstanding was on my part because @viniciuskneves reached out to me on my PR (#13301  which added NodeJS14 to a custom resource) noting that `Lambda@Edge` function cannot run Node14. And I simply didn't connect two dots and really differentiate between the two at the time. Now I know better that a custom resources are only used to read cross-region ARN in `us-east-1` while while the actual L@E function is `lambda.Function` under the hood. Live and learn. 😄
