### ISSUE TITLE
aws-codebuild: typed interface for BuildSpec.fromObject()

### ISSUE THREAD

**Issue by lachlan-vass** [aws/aws-cdk#13565]
Being able to define a codebuild buildspec in cdk is very useful. However I noticed the interface for doing so is not typed and does not provide intellisense for properties. 

It would be great if we could have a typed interface implementation to provide this information, and improve static type checking in the IDE. 

An example of this is the iam.PolicyStatement resource, which maps a typed object to create the JSON that policy statements use in AWS. 

### Use Case

More productive creation of buildspec configurations in CDK. 

### Proposed Solution

Unsure. 

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by Ray0427** [comment]
I have been implement buildSpec fromObject properties type in my private project before, I can contribute for this.
But I am not familiar with contributing project.

**Comment by skinny85** [comment]
Thanks @Ray0427! This would be a good place to get started on the contributing experience: https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md.

Let me know if you have any questions!

**Comment by Ray0427** [comment]
I have some trouble about interface fromObjectProps

`error JSII5016: Members cannot be named "build" as it conflicts with synthetic declarations in some languages.`

but build is the property of buildSpec phases

any help?

**Comment by skinny85** [comment]
What's the TypeScript code that gives you these errors?

**Comment by Ray0427** [comment]
This is my commit
https://github.com/Ray0427/aws-cdk/commit/8d086f5990d48848f3a6ab6ed9eebef3de586c08

**Comment by skinny85** [comment]
Got it. So I think you might have to re-name the props a little bit, like the error message says. Something like this should work:

```ts
export interface BuildSpecPhasesProps {
  readonly installPhase?: BuildSpecPhasesInstallProps;
  readonly preBuildPhase?: BuildSpecPhasesBuildProps;
  readonly buildPhase?: BuildSpecPhasesBuildProps;
  readonly postBuildPhase?: BuildSpecPhasesBuildProps;
};
```

Thanks,
Adam

**Comment by Ray0427** [comment]
I Know that I have to re-name in camelCase But the Buildspec syntax is not in camelCase.
https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html#build-spec-ref-syntax
The core function toBuildSpec using to JSON string, so its format might not be accept.

**Comment by skinny85** [comment]
So we have to make sure we change it to JSON correctly, changing camelCase to snake_case 🙂.
