### ISSUE TITLE
(events): specifying a schedule duration in seconds results in an error

### ISSUE THREAD

**Issue by andrestone** [aws/aws-cdk#13566]
## :question: General Issue

This [PR](https://github.com/aws/aws-cdk/pull/13064) breaks `Schedule.rule()` in `aws-events`. Previously it was possible to define a `Duration` in seconds, now it throws an error.

**Comment by nija-at** [comment]
Thanks for filing this @andrestone. 

This was never intended to be a breaking change, and hence was not added to the changelog. 
I've re-classified this as a bug and have prepared a fix for this - https://github.com/aws/aws-cdk/pull/13689
