### ISSUE TITLE
Subnet 'XXX' is in Availability Zone 'XXX' where service is not available

### ISSUE THREAD

**Issue by speedfl** [aws/aws-cdk#13569]
### The Question

When deploying an Api Gateway v2 vpcLink an issue is caught:

```
1:25:32 PM | CREATE_FAILED        | AWS::ApiGatewayV2::VpcLink                | VPCLink
Subnet 'subnet-02e27e63b313ca12d' is in Availability Zone 'euw3-az2' where service is not available (Service: AmazonApiGatewayV2; Status Code: 400; Error Code: BadRequestException; Request ID: 0d4a66c3-16fc-43e4-be2c-3199f9e40f34; Proxy: null)
``` 

### Environment

  - **CDK CLI Version:** 1.93.0
  - **Module Version:** 1.93.0
  - **Node.js Version:** v12.15.0
  - **OS:** Ubuntu
  - **Language:** TypeScript

### Other information

I created a sample app for easy reproduction:

Reproduce: https://github.com/speedfl/reproduce-issue-apigateway

Just change the account-id: 

lib/reproduce-issue-apigateway-stack.ts

```
const props = { env: { account: 'account-id', region: 'eu-west-3' } };
```

**Comment by speedfl** [comment]
For information I tried with APIGatewayV1 and a NetworkLoadBalancer. Everything looks ok. 

I wanted to use an ALB because I have an ECS cluster behind and would like to use ALB Health checks.

**Comment by speedfl** [comment]
For information I tried with APIGatewayV1 and a NetworkLoadBalancer. Everything looks ok. 

I wanted to use an ALB because I have an ECS cluster behind and would like to use ALB Health checks.

**Comment by peterwoodworth** [comment]
Hey @speedfl, sorry for the long response time, this didn't get caught by our bot for some reason.

This is simply a matter of CloudFormation not supporting this service in the region you specified. You can view the [resource specification](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html) and see that VpcLink isn't supported in eu-west-3. Sorry about that, but there's nothing we can do here :/
