### ISSUE TITLE
(CodeBuild): Environment Variables from cross account SecretsManager

### ISSUE THREAD

**Issue by Kruspe** [aws/aws-cdk#13567]
When using CodeBuild EnvironmentVariables we have to use values from a SecretsManager in another account. We are currently supplying the SecretARN as the value and the role created by CDK creates the policy as this secret would live in our account.

The EnvironmentVariable
``` JSON
"VAR1": {
  "value": "<SecretARN>",
  "type": "BuildEnvironmentVariableType.SECRETS_MANAGER"
},
```
The created policy
``` JSON
"Action": "secretsmanager:GetSecretValue",
"Resource": [
  "arn:aws:secretsmanager:<AWS-Region>:<AccountID>:secret:arn:aws:secretsmanager:<AWS-Region>: 
    <OtherAccountID>:secret:secretName"
],
"Effect": "Allow"
```

### Use Case

Use Secrets of other account without having to extend the policy

### Proposed Solution

Checking if the supplied value is an ARN to then configure the policy for the correct account.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by skinny85** [comment]
Thanks for reporting @Kruspe ! There's a related issue as well: https://github.com/aws/aws-cdk/issues/12703

**Comment by Kruspe** [comment]
Ah okay didn't see that one. Guess we can close this one then :)
