### ISSUE TITLE
aws-events-targets: cross-account targets broken permissions for Lambda target

### ISSUE THREAD

**Issue by john-tipper** [aws/aws-cdk#13568]
I had a hitherto working CDK project, where events in one account were triggering a Lambda in a different account. I upgraded from 1.68.0 to 1.93.0 and now cannot deploy. The source stack does not have permissions to create resources in a different account.  Reference guide is here: https://docs.aws.amazon.com/cdk/api/latest/docs/aws-events-readme.html#cross-account-targets

### Reproduction Steps

I have a stack with a lambda in it (note that after moving from `1.68.0` I am forced to define the function name using `PhysicalName.GENERATE_IF_NEEDED`, whereas that statement was not required before):

```
const stack1 = new Stack(app, 'Stack1', { env: { account: account1, region: 'eu-west-2' } });
const lambda= new SingletonFunction(stack1, 'targetLambda', {
  functionName: PhysicalName.GENERATE_IF_NEEDED,
  // ...
});
```

There is a second stack with an event rule:

```
const stack2 = new Stack(app, 'Stack2', { env: { account: account2, region: 'eu-west-2' } });
const rule = new Rule(stack2, 'SsmRunCommandEventRule', {
  // ...
  targets: [
      new LambdaFunction(lambda)
  ]
});
```

### What did you expect to happen?

Previously, this worked as expected. When I deploy, I should not get an error.

### What actually happened?

Now I find that the synthesized CloudFormation adds an `AWS::Lambda::Permission` resource inside `Stack2` pointing at the Lambda in `Stack1`.  When I deploy, I get a permissions error, stating that the role used to deploy `Stack2` is not permitted to add permissions to the lambda in the other account.

```
 0/6 | 09:48:20 | CREATE_FAILED        | AWS::Lambda::Permission | SsmRunCommandEventRule/AllowEventRuleXXX (SsmRunCommandEventRuleAllowEventRuleXXX) User: arn:aws:sts::222222222222:assumed-role/cdk-hnb659fds-cfn-exec-role-222222222222-eu-west-2/AWSCloudFormation is not authorized to perform: lambda:AddPermission on resource: arn:aws:lambda:eu-west-2:111111111111:function:YYY (Service: AWSLambda; Status Code: 403; 
```

The CloudFormation template for the stack which is erroring (stack 2, account 222222222222) now looks like this, where this resource has been added and which never used to exist:

```
"SsmRunCommandEventRuleAllowEventRuleZZZZZZ": {
      "Type": "AWS::Lambda::Permission",
      "Properties": {
        "Action": "lambda:InvokeFunction",
        "FunctionName": {
          "Fn::Join": [
            "",
            [
              "arn:",
              {
                "Ref": "AWS::Partition"
              },
              ":lambda:eu-west-2:111111111111:function:stack1bbf210d6f9226d036eef876f2e0b7a99605b"
            ]
          ]
        },
        "Principal": "events.amazonaws.com",
        "SourceArn": {
          "Fn::GetAtt": [
            "SsmRunCommandEventRuleA6D4D1F0",
            "Arn"
          ]
        }
      },
      ...
    },
```

### Environment

  - **CDK CLI Version  :** 1.89.0
  - **Framework Version:** 1.93.0
  - **Node.js Version:**  v12.16.0
  - **OS               :** Windows & Linux
  - **Language (Version):**  Java

### Other

This feels like perhaps the lambda permission resource is being added to the wrong stack.

- Why is the stack defining the source event adding resources that belong in another stack? 
- Why is the addition of the `invokeLambda` permission necessary at all in the first place, given that it is not needed in `1.68.0`?
- Why is the permission not being added within stack 1, referencing the rule in stack 2?

--- 

This is :bug: Bug Report

**Comment by john-tipper** [comment]
This issue results from a change introduced as a result of the migration from `v1.71.0` to `v1.72.0`, and specifically this PR #11217 for #10942.

@nija-at, you worked on this fix and @tmokmss you reported the original issue: what are your thoughts here please?

**Comment by john-tipper** [comment]
Here is a very slightly modified version of the example in #10942, where I explicitly set the account to deploy the different stacks to.  Prior to the incorporation of the change (i.e. using v <= 1.71.0), there is a circular dependency error is the accounts are either unspecified or are identical.  However, if the accounts are different (as below) then there is no such error:

```
import { Rule, Schedule } from '@aws-cdk/aws-events';
import { LambdaFunction } from '@aws-cdk/aws-events-targets';
import { Code, Function, IFunction, Runtime } from '@aws-cdk/aws-lambda';
import { App, Duration, PhysicalName, Stack, StackProps } from '@aws-cdk/core';

const app = new App();

const lambdaStackProps : StackProps = {
  env: {
    account: '111111111111',
    region: 'us-east-1',
  },
};

const cwStackProps : StackProps = {
  env: {
    account: '222222222222',
    region: 'us-east-1',
  },
};

class LambdaStack extends Stack {
  readonly handler: IFunction;

  constructor(scope: App, id: string, props?: StackProps) {
    super(scope, id, props);
    const handler = new Function(this, 'handler', {
      runtime: Runtime.NODEJS_12_X,
      handler: 'main.handler',
      code: Code.fromInline('hoge'),

    });

    this.handler = handler;
  }
}


class CwStack extends Stack {
  constructor(scope: App, id: string, handler: IFunction, props?: StackProps) {
    super(scope, id, props);
    const target = new LambdaFunction(handler);

    new Rule(this, 'rule', {
      schedule: Schedule.rate(Duration.minutes(10)),
      targets: [target],
      ruleName: PhysicalName.GENERATE_IF_NEEDED,
    });
  }
}

const lambdaStack = new LambdaStack(app, 'LambdaStack', lambdaStackProps);
new CwStack(app, 'CwStack', lambdaStack.handler, cwStackProps);

app.synth();
```

Could we perhaps do something like "add the permission to the event stack rule (the `CwStack` above) if the accounts are the same, but keep the permission in the lambda stack if the accounts are different?"

**Comment by nija-at** [comment]
Thanks for filing the bug @john-tipper. We'll look into this.

As a workaround, you could remove the permission node from the construct tree and add your own permission to the correct stack. 

Something like -

```ts
lambda.permissionNode.scope.node.tryRemoveChild(`AllowEventRule${rule.node.uniqueId}`);
```

(Haven't checked if this statement is correct. Take it as guidance instead of exact usage)

**Comment by nija-at** [comment]
We're also accepting pull requests if you'd like to submit a fix for this. Looks like you've done most of the work of digging into the code.

**Comment by john-tipper** [comment]
I've added a PR (#14030) incorporating your suggested change, thanks, plus a test to cover the case of 2 stacks in different accounts. I am seeing 2 `AWS::Lambda::Permission` created in the stack whereas I had thought there should be one, details in the PR, would appreciate your guidance here if you get a chance to look, as to whether this is expected.
