### ISSUE TITLE
(region-info): aws-entities.ts AWS_REGIONS missing ap-northeast-3

### ISSUE THREAD

**Issue by archelangelo** [aws/aws-cdk#13561]
[`@aws-cdk/region-info/build-tools/aws-entities.ts`](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/region-info/build-tools/aws-entities.ts#L6-L33) doesn't have `ap-northeast-3` in `AWS_REGIONS` list, while `ap-northeast-3` region has some facts hardcoded in `fact-tables.ts` ([example](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/region-info/build-tools/fact-tables.ts#L101)).

### Reproduction Steps

In my case, I tried to enable load balancer access logging and encountered an error. Example:

```typescript
// loadBalancer is an ApplicationLoadBalancer instance
// logBucket is a Bucket instance
loadBalancer.logAccessLogs(logBucket);
```

### What did you expect to happen?

Expect no error.

### What actually happened?

When building the templates, I got `Error: Cannot enable access logging; don't know ELBv2 account for region ap-northeast-3`

### Environment

These are more or less irrelevant to the issue as I already know what's missing.

  - **CDK CLI Version  :** 1.91.0
  - **Framework Version:** 1.80.0
  - **Node.js Version:** node-v12.18.3
  - **OS               :** MacOS
  - **Language (Version):** TypeScript (3.9.7)

### Other

I'm also wondering if there is a particular reason why `ap-northeast-3` is not included right now and if there is a plan to include that in the future.

--- 

This is :bug: Bug Report

**Comment by archelangelo** [comment]
For others that have the same issue, I have a small hack to resolve it. You can use `Fact.register()` to manually hardcode some information in your app. [Refer](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/region-info/lib/fact.ts).

Eg. `Fact.register({ region: 'ap-northeast-3', name: FactName.ELBV2_ACCOUNT, value: '383597477331' });`

**Comment by RomainMuller** [comment]
Thanks for reporting! A fix is in the pipes now!
