### ISSUE TITLE
Provide a uniform method for cloning constructs

### ISSUE THREAD

**Issue by otterley** [aws/aws-cdk#13571]
Constructs should have a universal `.clone()` or `.copy()` method that allows them to be trivially duplicated. Most end users probably won't need this, but libraries that need to make copies of constructs will. 

### Use Case

I'm developing a library that handles EBS volume attachments for ECS singleton services (i.e. services having a replica count of 1). Part of the solution involves adding an initialization container to the task definition that handles attaching the volume. The main application container is only started after the initialization container exits.

The library should make it easy to wrap existing `ecs.Service` instances, or provide a drop-in substitute or subclass for `ecs.Service`. The idea is that customers needn't concern themselves about how to handle volume management - the construct takes care of all that for them, as long as they provide an `ec2.Volume` and where it should be mounted into their application container.

An `ecs.Service` is associated with a task definition. However, the nature of this solution is such that the original task definition will have to be modified so that there is a unique one for each Service -- think partitioned services or replicas, each mounting a different EBS volume. Since each volume ID will differ, so must the Task Definition associated with each Service. (Services don't allow customers to declare Task Definition overrides; otherwise this would be easier.)

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
I understand where you're coming from and I agree it would be useful, but this is something that would require a lot of work that we're not willing to take on currently.

The easiest way to achieve what you're looking for (multiple instances of a construct that your library customer controls), is to do one of the following:

* Classes are the reusable "blueprint" mechanism in CDK. Have your customers define and pass you a class, you instantiate it however many times you want. Downside of this is it is not jsii-able, but it most closely maps to how the rest of the CDK works, and what we consider to be "abstract" or "concrete".
* If you don't want your users to define classes, have them provide a callbacks that instantiates/configures the constructs. Effectively the same without the requirement of defining and naming a class. You can make it a one-method interface (a la Java) if you want this to be jsii-able. 

Going to close this issue to not raise unrealistic expectations.
