### ISSUE TITLE
pipeline to install npm modules from a private nexus repo

### ISSUE THREAD

**Issue by s1mrankaur** [aws/aws-cdk#13580]
npm install command fails in my pipeline written using aws-cdk with the following error:

`npm ERR! code ENOTFOUND 33 npm ERR! syscall getaddrinfo 34 npm ERR! errno ENOTFOUND 35 npm ERR! network request to http://nexus.company.com:8081/nexus/repository/npm-group/zip-stream/-/zip-stream-4.1.0.tgz failed, reason: getaddrinfo ENOTFOUND nexus.company.com`

How can this be fixed? npm run command works okay in my local system,

.npmrc file looks as follows:
`registry="http://nexus.company.com:8081/nexus/repository/npm-group/"

`How to whitelist access to private registry from the pipeline?

**Comment by skinny85** [comment]
Hey @s1mrankaur ,

looks like `nexus.company.com` is not reachable from the CodeBuild instance.

Can you verify how do you have access to that domain name locally? Do you use a VPN, or something else?

Thanks,
Adam
