### ISSUE TITLE
(cloudfront): failed to deploy Distribution to AWS China caused by unsupported 'CachePolicyId'

### ISSUE THREAD

**Issue by zxkane** [aws/aws-cdk#13584]
The deployment failed with error message,

```

2021-03-14 15:31:07 UTC+0800 | Distribution830FAC52 | CREATE_FAILED | The parameter CachePolicyId can't be set for this region. (Service: AmazonCloudFront; Status Code: 400; Error Code: InvalidArgument; Request ID: 682d46e9-2ccc-49ea-aeb9-57d0c508a814; Proxy: null)
```

### Reproduction Steps

Create a distribution like below, then deploy it AWS China,

```ts
    const websiteBucket = new Bucket(this, 'DashboardUI', {
      removalPolicy: RemovalPolicy.DESTROY,
      autoDeleteObjects: true,
      encryption: BucketEncryption.S3_MANAGED,
      blockPublicAccess: BlockPublicAccess.BLOCK_ALL,
    });

    const distribution = new Distribution(this, 'Distribution', {
      defaultBehavior: {
        origin: new S3Origin(websiteBucket),
        viewerProtocolPolicy: ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
        allowedMethods: AllowedMethods.ALLOW_GET_HEAD,
      },
      defaultRootObject: 'index.html',
      enableIpv6: false,
      priceClass: PriceClass.PRICE_CLASS_ALL,
      enableLogging: true,
    });
```

### What did you expect to happen?

The new CloudFront distribution can be deployed to AWS China regions.

### Environment

  - **CDK CLI Version  :** 1.91.0
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):** 

### Other

--- 

This is :bug: Bug Report

**Comment by njlynch** [comment]
Thanks for the bug report, @zxkane.

This is because we always default to using a Cache Policy, even if one is not specified.

https://github.com/aws/aws-cdk/blob/ab2c48e05ca3e2edf04e21a41051a46a5061b2dc/packages/@aws-cdk/aws-cloudfront/lib/private/cache-behavior.ts#L48

I can't find any documentation stating that cache policies aren't supported in CN, but from the console experience and the above report, it appears they are not (yet) supported. As a temporary work-around, you might be able to use [escape hatches](https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html#cfn_layer_resource) to remove the cache policy id. Can you try this as a work-around and see if it works?

```ts
    const distribution = new Distribution(this, 'Distribution', {
      defaultBehavior: {
        origin: new S3Origin(websiteBucket),
        viewerProtocolPolicy: ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
        allowedMethods: AllowedMethods.ALLOW_GET_HEAD,
      },
      defaultRootObject: 'index.html',
      enableIpv6: false,
      priceClass: PriceClass.PRICE_CLASS_ALL,
      enableLogging: true,
    });
    const cfnDist = (dist.node.defaultChild as CfnDistribution);
    cfnDist.addPropertyDeletionOverride('DistributionConfig.DefaultCacheBehavior.CachePolicyId');
```

**Comment by zxkane** [comment]
Hi Nick,

Thanks for your workaround. 

Per [the doc](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-defaultcachebehavior.html#cfn-cloudfront-distribution-defaultcachebehavior-cachepolicyid), one of `CachePolicyId` and `ForwardedValues` is mandatory.

I have to add below overriding for a working workaround,

```ts
    cfnDist.addPropertyOverride('DistributionConfig.DefaultCacheBehavior.ForwardedValues', {
      "QueryString": false
    });
```
Also `CachePolicy` can not be used when creating CloudFront distribution in China regions. Defining cache behavior must hack the [CacheBehaviors](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-distributionconfig.html#cfn-cloudfront-distribution-distributionconfig-cachebehaviors) prop of distribution created by `Distribution`.

The old [CloudFrontWebDistribution](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cloudfront.CloudFrontWebDistribution.html) is still maintained, is it recommended for creating distribution in China regions?

**Comment by pahud** [comment]
closing as the workaround https://github.com/aws/aws-cdk/issues/31033#issuecomment-2289097819 is relevant.
