### ISSUE TITLE
(ECS Fargate): Stack arn is missing in CDK CLI output

### ISSUE THREAD

**Issue by ganeshnj** [aws/aws-cdk#13597]
Stack arn is missing in CDK CLI output

![snip2](https://user-images.githubusercontent.com/8882380/111192161-04513c80-8576-11eb-892d-2b88d8800a82.PNG)

### Reproduction Steps

- Deploy a webapp to Fargate.

### What did you expect to happen?

`Stack arn` must be populated with created CloudFormation stack.

### What actually happened?

`Stack arn` is empty

### Environment

  - **CDK CLI Version  :** 1.80.0 (build 31132ca)
  - **Framework Version:**
  - **Node.js Version:**  v12.18.4
  - **OS               :** Microsoft Windows 10 Enterprise; 10.0.18363 N/A Build 18363
  - **Language (Version):**  all

### Other

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
Is this for all stacks?

If not, can you figure out what makes the stack for which the ARN doesn't appear different?

Is it about the stack itself? Is it about the order in which they deploy in the CLI?
