### ISSUE TITLE
(aws-batch): Fargate support for batch jobs

### ISSUE THREAD

**Issue by kokachev** [aws/aws-cdk#13590]
Support FARGATE and FARGATE_SPOT compute environments for Batch jobs.

### Use Case

Use Fargate for AWS Batch jobs

* [] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by reini1989** [comment]
Is there an Eta for reviewing/merging this?
