### ISSUE TITLE
(aws-iam): Deployment will fail if it attach a managed policy that must not contain an account ID.

### ISSUE THREAD

**Issue by intptr-t** [aws/aws-cdk#13608]
I get an error when I try to assign a managed policy for `AWSIoTDataAccess`.

### Reproduction Steps

Create a project in TypeScript and deploy the following stack code.

```typescript
import * as cdk from '@aws-cdk/core';
import * as iam from '@aws-cdk/aws-iam';

export class Sample extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);
    new iam.User(this, 'SampleUser', {
      managedPolicies: [
        iam.ManagedPolicy.fromManagedPolicyName(this, 'SampleStackPolicy', 'AWSIoTDataAccess')
      ]
    });
  }
}
```
### What did you expect to happen?

I can create a new IAM user with the management policy "AWSIoTDataAccess" attached to it.

### What actually happened?

Deployment will fail.

**terminal output**
```
IAM Policy Changes
┌───┬───────────────┬──────────────────────────────────────────────────────────────────────┐
│   │ Resource      │ Managed Policy ARN                                                   │
├───┼───────────────┼──────────────────────────────────────────────────────────────────────┤
│ + │ ${SampleUser} │ arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/AWSIoTDataAccess │
└───┴───────────────┴──────────────────────────────────────────────────────────────────────┘
(NOTE: There may be security-related changes not in this list. See https://github.com/aws/aws-cdk/issues/1299)

Do you wish to deploy these changes (y/n)? y
SampleStack: deploying...
SampleStack: creating CloudFormation changeset...
15:08:35 | CREATE_FAILED        | AWS::IAM::User     | SampleUser84148EDB
Policy arn:aws:iam::870851252102:policy/AWSIoTDataAccess does not exist or is not attachable. (Service: AmazonIdentityManagement; Status Code: 404; E
rror Code: NoSuchEntity; Request ID: b443d9cb-43a5-472f-8283-14ade7d43c94; Proxy: null)
```

### Environment

  - **CDK CLI Version  :** 1.93.0
  - **Node.js Version:** v14.15.4
  - **OS               :** Mac OS X / 10.15.7 / 19H524
  - **Language (Version):** TypeScript (3.9.7)

### Other

The correct ARN for AWSIoTDataAccess is `arn:aws:iam::aws:policy/AWSIoTDataAccess`
In some services, such as in the case of AWSIoTDataAccess, the return value of ManagedPolicy.fromManagedPolicyName must not contain ${AWS::AccountId}.

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
I think you are looking for [fromAwsManagedPolicyName](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-iam.ManagedPolicy.html#static-fromwbrawswbrmanagedwbrpolicywbrnamemanagedpolicyname)
