### ISSUE TITLE
(aws-events-targets): Support new EventBridge API Destinations feature

### ISSUE THREAD

**Issue by msimpsonnz** [aws/aws-cdk#13607]
Add construct to support event targets using API Destinations

### Use Case

Looking to integrate with external parties as direct EventBridge targets
https://aws.amazon.com/blogs/compute/using-api-destinations-with-amazon-eventbridge/

### Proposed Solution
Follow established patterns as add this as a new target type

* [X] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by indrora** [comment]
Closing as this ticket is stale (over 9 months since last event or relates to the CDKv1). 

If this is still a relevant request in the CDKv2, please open a new ticket.
