### ISSUE TITLE
iam: consider an alternative to the fluent api for policy statements

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#1362]
`iam.PolicyStatement` is currently one of the only places in the framework that we use a fluent "builder-style" API, and oftentimes confuses people because it's not idiomatic to the CDK (and very idiomatic elsewhere [looking at you Java folks]).

**Comment by rix0rrr** [comment]
Fluent API is  still there for backwards compat, but we  encourage the constructor now which is a lot better.
