### ISSUE TITLE
(@aws-cdk/aws-codebuild): not able to access the the synthesized cdk stack template

### ISSUE THREAD

**Issue by nkhine** [aws/aws-cdk#13622]
## :question: General Issue

From my sample code in https://bitbucket.org/nkhine/cdk-docker-lambda/src/master/ when I run the pipeline we can't deploy the app because for some reason, it is not able to access the the synthesized cdk stack template.

If I go to the execution details and click on the input artifact,  it's missing from the S3 bucket.
So, For some reason, It's deleting that artifact before deploy step runs or that artifact was never created and for some reason, it's trying to access a non-existent artifact and I have this error

```
The object "CdkStack-CdkSta/Artifact_B/TZSLLB8" was not found
This object may have been deleted or is not an object in this bucket or your account.
```

checking my S3 and i can confirm that the Atifact_B/TZSLLB8 is empty

### Environment

  - **CDK CLI Version:** 1.93.0 (build c506d3b)
  - **Module Version:** 
  - **Node.js Version:** v12.18.3
  - **OS:** 
  - **Language (Version):** TypeScript (3.8.3)

**Comment by skinny85** [comment]
Hey @nkhine ,

thanks for opening the issue. I can see a few problems with your code:

1. You're not using the `dockerImageContents` CodePipeline Artifact in your Deploy Action. I assume it's needed.
2. Your BuildDockerImage CodeBuild Project is using the `secondary-artifacts` property of the buildspec, but you're not naming your CodePipeline Artifacts, and also your build `Docker_Image` CodePipeline Action only has a single output. See here: https://docs.aws.amazon.com/cdk/api/latest/docs/aws-codepipeline-actions-readme.html#multiple-inputs-and-outputs

Fix these problems, and your build will start working I bet 🙂.

Thanks,
Adam

**Comment by nkhine** [comment]
hi @skinny85 ,
thanks for the quick reply.

1. We are using Docker images in Lambda. In the Docker image build step, we build the image and push it to ECR and then refer back to this image using image URI. So, We don't need to depend on dockerImageContents in the deploy step. 

2. We do not tag images with the latest tag and the image version is made from `CODEBUILD_BUILD_NUMBER` among other things. We needed a way to access this variable outside of codebuild environment so I used this `_trick_` of writing the variable to a JSON file, Exporting this json file in an artifact and then reading the value from this file using getparam.

**Comment by skinny85** [comment]
> 1. We are using Docker images in Lambda. In the Docker image build step, we build the image and push it to ECR and then refer back to this image using image URI. So, We don't need to depend on dockerImageContents in the deploy step.

Can you get rid of the this output completely then? I feel like having an output that is not used is pretty confusing...

> 2. We do not tag images with the latest tag and the image version is made from `CODEBUILD_BUILD_NUMBER` among other things. We needed a way to access this variable outside of codebuild environment so I used this `_trick_` of writing the variable to a JSON file, Exporting this json file in an artifact and then reading the value from this file using getparam.

Except that's not what is happening 🙂. You never actually use the `codeBuildNumber` Artifact as the input or output of any Action in the Pipeline. You only ever pass it to the `buildDockerImagePipeline` function.

**Comment by skinny85** [comment]
Also, I just realized, that this cannot work. You cannot use the `Fn::GetParam` expression (which is that `Artifact.getParam()` does) in a CloudFormation template. You can only use it in the `parameterOverrides` property of CloudFormation CodePipeline Actions.

What you need to do is add a CFN Parameter to your Lambda Stack, and then use `Artifact.getParam()` to fill it inside your Pipeline stack.

Hope that helps!

Thanks,
Adam
