### ISSUE TITLE
(cloudfront): the auto generated name of cache policy must be unique in the account

### ISSUE THREAD

**Issue by zxkane** [aws/aws-cdk#13629]
Deploying the same application in different regions, the second deployment failed with error message `Internal error reported from downstream service during operation 'AWS::CloudFront::CachePolicy'`. It’s caused by the generated name of `CachePolicy` are same for multiple deployments.

### Reproduction Steps

Create an app with a distribution like below,

```ts
      new Distribution(this, 'Distribution', {
        defaultBehavior: {
          origin: new S3Origin(websiteBucket),
          viewerProtocolPolicy: ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
          allowedMethods: AllowedMethods.ALLOW_GET_HEAD,
          cachePolicy: new CachePolicy(this, 'defaultCachePolicy', {
            defaultTtl: Duration.days(7),
            minTtl: Duration.seconds(0),
            maxTtl: Duration.days(30),
            enableAcceptEncodingGzip: true,
            enableAcceptEncodingBrotli: true,
          }),
        },
        defaultRootObject: 'index.html',
      });
    }
```

### What did you expect to happen?

The auto generated name of policy name is unique in the account, it might depend on the region and name of stack.

### Environment

  - **CDK CLI Version  :** 1.91.0
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):** 

### Other

--- 

This is :bug: Bug Report

**Comment by njlynch** [comment]
Thanks for the bug report.

The autogenerated name should take into account Stack name, but it certainly doesn't take into account region today. We absolutely could add the region to the name though. It's not a bad idea. It would be a relatively straightforward change to alter the below to use something like `Stack.of(this).region` along with the `Names.uniqueId()` call:

https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-cloudfront/lib/cache-policy.ts#L128

If you (or anyone else) is up for submitting a PR, I'd be happy to work with you to get the fix merged in.

As a work-around, you can specify the `cachePolicyName` yourself, and add the region to it:

```ts
          new CachePolicy(this, 'defaultCachePolicy', {
            cachePolicyName: `MyPolicy-${Stack.of(this).region}`,
            defaultTtl: Duration.days(7),
            minTtl: Duration.seconds(0),
            maxTtl: Duration.days(30),
            enableAcceptEncodingGzip: true,
            enableAcceptEncodingBrotli: true,
          })
```

**Comment by zxkane** [comment]
Hi Nick, 

The current `cachePolicyName` is generated from `construct id` only. My CDK app is created `Distribution` in nested stack, which always has unique stack name. I can reproducible this bug when deploying the same application to multiple regions.

Another proposal is making the property `cachePolicyName` as a mandatory property, the caller makes sure using the unique name in account wide for it. But it’s a breaking change, we probably should avoid.
