### ISSUE TITLE
BucketNotificationsHandler lambda cannot be deployed

### ISSUE THREAD

**Issue by VessyAscentSoftware** [aws/aws-cdk#13635]
##  The BucketNotificationsHandler lambda cannot be deployed 
"ZipFile can only be used when Runtime is set to either of nodejs8.10, nodejs10.x, nodejs12.x"

### The Question
The Trusted Advisor flagged two lambdas that run on NodeJS 10, because support for it is about to be dropped. 

The problem is that it is the BucketNotificationsHandler  lambdas that are generated by CDK when "addEventSource" is used.

I updated Amazon.CDK and Amazon.CDK.AWS.S3 to 1.94.0 , so they get update to NodeJS 14.0.
That builds and synth succeeds, and I see that the lambdas are configured on NodeJS 14... but when I try to deploy I get :

"ZipFile can only be used when Runtime is set to either of nodejs8.10, nodejs10.x, nodejs12.x"

### Environment

  - **CDK CLI Version:**  aws-cdk@1.94.0
  - **Module Version:** 1.94.0
  - **Node.js Version:** 14
  - **OS:**  Ubuntu -->
  - **Language (Version):** .net

**Comment by andreaspoldi** [comment]
+1, same problem for me with 1.94.0

**Comment by VessyAscentSoftware** [comment]
Hello,
Any update on this?

**Comment by andreaspoldi** [comment]
1.94.1 fixes this

**Comment by nija-at** [comment]
We have pushed a fix for this - https://github.com/aws/aws-cdk/pull/13624 - and released it in 1.94.1.
