### ISSUE TITLE
(pipelines): short-lived branches deploys

### ISSUE THREAD

**Issue by carles-vancast** [aws/aws-cdk#13638]
I want to migrate my old "primitive" CloudFormation deploying system to AWS CDK, however, after a two-days research I couldn't find any piece of documentation that talks about how to implement a CDK Pipeline that deploys an instance of my application specifically for a short-lived branch, a.k.a pull request. 

All the examples and documents I found about CDK Pipelines explain how to implement a workflow that always builds and deploys to the same stages (prod, staging, dev, ...) However what I want to accomplish is a way to deploy an instance of my application that runs a specific change (fix, feature, refactor...). These instances live for a very short time, basically until QA gives the ok. 

### Use Case

As a code reviewer I want to deploy the changes accumulated by a Pull Request so I can validate them, either manually or using some sort of automated E2E testing engine. I expect each Pull Request deploy to be independent from other deploys. 

If new commits are pushed to the PR a new deploy is executed applying the changes to the stacks.

Once I've validated the changes I accept the Pull Request therefore the changes get merged to the trunk branch and the deploy is destroyed.

### Proposed Solution

A CDK Pipeline should be able to give a Stage an ID that depends in some way on the source action that originated the execution, for example the PR ID. Following actions triggered from the same source event should generate the same Stage ID (new pushes to the same PR).

### Other
I'm quite new to CDK so I probably said a few stupid things I am totally open to corrections and further discussion. 

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
Pipelines is currently built on CodePipeline, which as far as I know has no way to trigger on short-lived branches this way.

You probably need to look at something like GitHub Actions to build this for yourself.

I will keep this open as a feature request, but it's unlikely to get any traction from our end in the near future.

**Comment by carles-vancast** [comment]
Thank you @rix0rrr.

The main reason I want to migrate to CDK is to give my developers better tools to build and review applications but at the same time keep the budget under control. 

We have been reviewing code like I explained for a few years now and it has proved really powerful and cost-effective. Instead of keeping several 24/7 PRE environments we use these short-lived deploys to validate small changes. Reviewers can have several independent deployments running at the same time each of them isolated from the other. When a change is accepted, the reviewer knows for sure that he or she is accepting a change that has been proved without anything unexpected affecting it. 

Ideally we should focus on improving our e2e testing coverage to the point that reviewers don't need to validate changes manually. That's our long term goal. But for a small company as ours it might take a long time to get there. In the meantime, manual validations, although human-error prone, are better than not validating at all. 

However, your response makes me wonder if my use case goes in any way against AWS CDK best practices and/or I am seeing the problem from the wrong angle. If I am not in the right path perhaps I should explore other options.

**Comment by ahammond** [comment]
This (absurd) limitation of CodePipeline is literally the reason we haven't used pipelines. It is shocking to me that CI with feature branches is not part of the MVP.
