### ISSUE TITLE
(@aws-cdk/aws-events-targets module): Falsely detect change to Chinese text string

### ISSUE THREAD

**Issue by tamakisquare** [aws/aws-cdk#13634]
CDK CLI falsely detects a change to Chinese characters when there's no change at all. 

The Chinese characters are passed into the constructor of Lambda function invoking event rule target as the event object. 

### Reproduction Steps
```
new Rule(this, 'MonthlyReminder', {
  enabled: true,
  schedule: Schedule.cron({ day: '1', hour: '0', minute: '0' }),
  targets: [
    new LambdaFunction(sendReminderFn, {
      event: RuleTargetInput.fromObject({ message: '今日五號，請交月報。' }),
    }),
  ],
});
```

### What did you expect to happen?
CDK CLI should know there's no change.

### What actually happened?
CDK CLI falsely recognizes there's a change to the Chinese text string. Somehow, CDK CLI shows the current version of the text as a series of question marks "????".
<img width="707" alt="Screen Shot 2021-03-17 at 4 40 27 PM" src="https://user-images.githubusercontent.com/538353/111441728-91e18780-8742-11eb-992f-a93c05bd2e36.png">

### Environment

  - **CDK CLI Version  :** 1.93
  - **Framework Version:** 1.93
  - **Node.js Version:** 14.6
  - **OS               :** MacOS 10.15.7
  - **Language (Version):** TypeScript (4.1.2)

### Other

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
Unfortunately this is a bug in CloudFormation, and the CDK cannot do anything about this.

I've created an issue for you in their public bug tracker: https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/814

Please go upvote that there, or ask your AWS support contact to escalate the issue internally.

**Comment by tamakisquare** [comment]
Thanks @rix0rrr. It's good to know the source of the issue.
