### ISSUE TITLE
(Cognito): LambdaTriggers forces to auto verify phone number and email

### ISSUE THREAD

**Issue by EinApfelBaum** [aws/aws-cdk#13648]
I am working on a CDK cognito user pool stack with two app clients.
* app with custom auth flow for a passwordless signup/signin
* web with email and password signup, hostedUI

Individually, I can get both to work. Combining them together in one CDK stack I am not able to signup for both clients.

### Reproduction Steps
Source: https://github.com/EinApfelBaum/aws-cdk-user-pool-passwordless

* Uncomment the LambdaTriggers
* cdk synth and cdk deploy
* Open Cognito Console and open App client setting 
* Launch the hostedUi for the web client Id
* Try to signup with email and password

````
var userPool = new UserPool(this, $"{props.Stage}-userpool", new UserPoolProps
{
    UserPoolName = $"{props.Stage}-userpool",
    SelfSignUpEnabled = true,
    UserVerification = new UserVerificationConfig
    {
        EmailSubject = "Verify your email for our awesome app!",
        EmailBody = "Hello {username}, Thanks for signing up to our awesome app! Your verification code is {####}",
        EmailStyle = VerificationEmailStyle.CODE,
        SmsMessage = "Hello {username}, Thanks for signing up to our awesome app! Your verification code is {####}",
    },
    UserInvitation = new UserInvitationConfig
    {
        EmailSubject = "Invite to join our awesome app!",
        EmailBody = "Hello {username}, you have been invited to join our awesome app! Your temporary password is {####}",
        SmsMessage = "Hello {username}, your temporary password for our awesome app is {####}"
    },
    SignInAliases = new SignInAliases { Username = false, Email = true, Phone = true },
    AutoVerify = new AutoVerifiedAttrs { Email = true },
    SignInCaseSensitive = false,
    
    PasswordPolicy = new PasswordPolicy
    {
        MinLength = 10,
        RequireLowercase = true,
        RequireUppercase = true,
        RequireDigits = true,
        RequireSymbols = true,
        TempPasswordValidity = Duration.Days(10)
    },
    AccountRecovery = AccountRecovery.EMAIL_ONLY,

    //LambdaTriggers = new UserPoolTriggers()
    //{
    //    PreSignUp = preSignUp,
    //    DefineAuthChallenge = defineAuthChallenge,
    //    CreateAuthChallenge = createAuthChallenge,
    //    VerifyAuthChallengeResponse = verifyAuthChallenge
    //}
});

var appClient = userPool.AddClient("app", new UserPoolClientOptions
{
   AuthFlows = new AuthFlow
   {
       Custom = true
   },
   OAuth = new OAuthSettings
   {
       Flows = new OAuthFlows { AuthorizationCodeGrant = true },
       Scopes = new[] { OAuthScope.EMAIL, OAuthScope.PROFILE, OAuthScope.PHONE, OAuthScope.OPENID },
       CallbackUrls = new[] { "app://oauthredirect" },
       LogoutUrls = new[] { "app://oauthredirect" }
   },
   AccessTokenValidity = Duration.Minutes(60),
   IdTokenValidity = Duration.Minutes(5),
   RefreshTokenValidity = Duration.Days(30),
});

var webClient = userPool.AddClient("web", new UserPoolClientOptions
{
    AuthFlows = new AuthFlow
    {
        UserSrp = true
    },
    OAuth = new OAuthSettings
    {
        Flows = new OAuthFlows { AuthorizationCodeGrant = true },
        Scopes = new[] { OAuthScope.EMAIL, OAuthScope.PROFILE, OAuthScope.PHONE, OAuthScope.OPENID },
        CallbackUrls = new[] { "https://github.com/aws/aws-cdk" },
        LogoutUrls = new[] { "https://github.com/aws/aws-cdk" }
    },
    AccessTokenValidity = Duration.Minutes(60),
    IdTokenValidity = Duration.Minutes(5),
    RefreshTokenValidity = Duration.Days(30)
});
````

### What did you expect to happen?

I would expect, that I am able to signup 
* with the appClientId within my app with the custom auth flow and 
* with the web clientId within the hostedUI with email and password.

### What actually happened?

With the LambdaTrigger commented out I could signup with email and password within the hostedUI with the webClientId.

After I uncomment the LambdaTriggers to enabled the custom flow I am not able to signup.
I am getting the following error message when I try to sign up with web client id within hostedUI:
![image](https://user-images.githubusercontent.com/4492357/111513635-4d111d00-8751-11eb-9c95-4be5bb5343bd.png)

If I try to signup with amplify with the app clientId `Auth.signUp({ phoneNumber: phoneNumber, password: "1234567!Qq", username: phoneNumber })` I am getting "Email auto verified was set to true, but no email was provided during signup."

Amplify is configured with region, UserPoolId and appClientId.

### Environment

  - **CDK CLI Version  :** 1.91.0 (build 0f728ce)
  - **Framework Version:** 1.91.0 (build 0f728ce)
  - **Node.js Version:** v14.7.0
  - **OS               :** Windows 10 Pro - 20H2
  - **Language (Version):** dotnet 5

### Other

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
Hi @EinApfelBaum -

This does not look like an issue with the CDK, but the Cognito user pool service itself. You will need to contact AWS support to get more help on this.

**Comment by EinApfelBaum** [comment]
Hi @nija-at 

thanks for looking into the issue. I just want to leave a comment, because it seems to be pretty obvious that's not a bug. 

In my PreSignUp lambda function I am setting `AutoVerifyPhone = true` and `AutoVerfiyEmail = true`. In this case Cognito expects that there is an email address present in the request. 

A solution for this would be to check in the preSignUp lambda function if the user signs up with phone or mail address.

Greetings! =)
