### ISSUE TITLE
[pipelines]: Allow customizing the CodeBuild project for building Docker images

### ISSUE THREAD

**Issue by wolverian** [aws/aws-cdk#13645]
Allow the user to specify environment variables, build images etc. for how Docker images are built with CDK pipelines.

### Use Case

I have a Docker image that requires `DOCKER_BUILDKIT=1` set. I would also like to update the environment image from `aws/codebuild/standard:4.0` to `aws/codebuild/standard:5.0`. I don't see easy ways to do this right now, and dropping down from automatic builds with cdk-pipelines to configuring your own CodeBuildActions seems like a fairly big refactoring.

### Proposed Solution

I don't have a proposed API for this; the current "automagic" configuration of Docker builds via Stages doesn't really surface any hooks to us where we could add customization options. Some options would be:

- Add properties to the `CdkPipeline` itself with high-level configuration properties for building assets.
- Add API to `CdkPipeline` to get the build projects for each assets and let the user configure them directly.

This is a :rocket: Feature Request

**Comment by nemanjko** [comment]
I think this goes along my issue that I am currently experiencing with CDKPipeline construct. Thinks were working fine until today. Today my CodeBuild stage was breaking with the following error:

[Container] 2021/04/12 13:22:33 Running command npm install -g aws-cdk
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @aws-cdk/region-info@1.98.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-04-12T13_22_38_578Z-debug.log
[Container] 2021/04/12 13:22:38 Command did not exit successfully npm install -g aws-cdk exit status 1
[Container] 2021/04/12 13:22:38 Phase complete: INSTALL State: FAILED
[Container] 2021/04/12 13:22:38 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: npm install -g aws-cdk. Reason: exit status 1

The only explanation I see is that the new aws-cdk version 1.98.0 has some dependency issue (as usual with CDK).

I solved it by manually modifying buildspec in CodeBuild,  replacing 
"commands": "npm install -g aws-cdk" with 
"commands": "npm install -g aws-cdk@1.96.0"

Then it worked again.

**Comment by njlynch** [comment]
@nemanjko  - I'm super late to the party, but I don't think the error you encountered was related to this issue. From the timestamps, it looks like you ran into this error just as [1.98.0](https://github.com/aws/aws-cdk/releases/tag/v1.98.0) was being published. I suspect `aws-cdk@1.98.0` had been fully propagated and was available, but `@aws-cdk/region-info@1.98.0` had not, resulting in the error. We publish our packages in topological order, but that doesn't always translate into when they're available via `npm install`. Had you simply re-tried the failing job (likely after ~20 minutes), I suspect the error would have gone away on its own.

**Comment by rix0rrr** [comment]
This issue will be addressed by https://github.com/aws/aws-cdk/issues/15169 and https://github.com/aws/aws-cdk/pull/12326, so closing as duplicate.
