### ISSUE TITLE
(core): Add a method like exportResourceAttrs to support proactively exporting resource attributes

### ISSUE THREAD

**Issue by liamfd** [aws/aws-cdk#13650]
Expose a higher level helper on top of `Stack.exportValue` that takes a resource and generates Outputs/exports for every value that the CDK _might_ automatically generate Outputs for, e.g:

```ts
// in MyStack's constructor

this.exportResourceAttrs(lambda); // where `lambda` is a lambda.Function instance

// equivalent to calling:
this.exportValue(lambda.functionArn);
this.exportValue(lambda.functionName);
```

### Use Case

Right now, `exportValue` seems useful for reactively forcing `Outputs` when the deadly embrace has been encountered. You'll know which of your Outputs would get deleted, so you can just go back, add the `exportValue` for it, and run your deploys, then go and clean up the `exportValue`.

But if you want to _proactively_ prevent it, you'd need to understand which values the CDK _could_ produce Outputs for, which seems to be any attribute you can pull with `Ref` or `Fn:GetAtt`. While that's a finite, well documented set of values, it feels like it would be better to treat all of this as a CDK implementation detail.

Also, explicitly writing out this list feels contrary to the dependency pattern the CDK seems to encourage. For example, from the S3 docs:

```ts
/**
 * Stack that defines the bucket
 */
class Producer extends cdk.Stack {
  public readonly myBucket: s3.Bucket;

  constructor(scope: cdk.App, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const bucket = new s3.Bucket(this, 'MyBucket', {
      removalPolicy: cdk.RemovalPolicy.DESTROY,
    });
    this.myBucket = bucket;
  }
}

interface ConsumerProps extends cdk.StackProps {
  userBucket: s3.IBucket;
}

/**
 * Stack that consumes the bucket
 */
class Consumer extends cdk.Stack {
  constructor(scope: cdk.App, id: string, props: ConsumerProps) {
    super(scope, id, props);

    const user = new iam.User(this, 'MyUser');
    props.userBucket.grantReadWrite(user);
  }
}

const producer = new Producer(app, 'ProducerStack');
new Consumer(app, 'ConsumerStack', { userBucket: producer.myBucket });
```

Here, the full `bucket` is shared, and my understanding is, any attribute that can be accessed with `Ref` or `GetAtt` could potentially be used by a consumer, which would add an `Output`.

It would be nice to have an abstraction for explicitly declaring exports/Outputs that operates on the same level of abstraction as the actual values being passed around (meaning the resource objects) . Right now, the `Producer` is required to drop down a level and define individual attributes to pass to `exportValue`, which seems to run counter to the high level, "let the CDK decide how to wire up the import/exports" philosophy. If a value might be automatically imported, then it seems worth adding the export.

In terms of _why_ I might want to do this proactively - we have close to a thousand, very granular, stacks at my company, so my understanding is that we're more vulnerable to the deadly embrace than most because so many of our dependencies are cross stack. Every engineer has their own environment, in addition to a handful of shared environments, so any rollout that requires two separate deploys (like adding and removing a reactive `exportValue` patch) is going to be pretty disruptive. I understand that this scenario probably isn't that common, but I don't think it hurts to something opt-in like this, and I think it could be a good option even for apps with fewer stacks.

Prior to migrating to the CDK, our convention was for each stack to expose a standard set of Outputs for each resource type that might be depended upon by other stacks, so we rarely ran into this problem. I could keep that going, but I don't think I've got a good way to ensure only those exports are used with the current system, unless I only allow low level exports like ARNs, access them with `Fn.ImportValue`'s, and pass those values to various `Resource.from*` methods to get my hands on resource objects. That's a lot less ergonomic than just passing resources around, and requires us to explicitly wire up the actual stack dependencies.

### Proposed Solution

My understanding is that the auto-export system kicks in when a resource property is a `Reference`. If that's correct, and the full set of potentially autogenerated Outputs is the set of properties that are `Reference`s, then in theory this could be implemented like:

```ts
// on the core Stack class

exportResourceAttrs(resource: Resource){
  resource.references.forEach((reference) => {
    this.exportValue(reference);
  });
}
```

Not sure how best to implement `resource.references`, if something like it doesn't already exist. The resource class could append to that list every time a Reference is added. That means extra state, but seems less error prone than trying to filter down class members after the fact.

### Other

I'm not sure how widely useful this would be, but I'm probably going to take a pass at implementing it myself outside of the CDK regardless, so if there's interest I can share what I come up with.

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

Also, thanks to the team for adding `exportValue` in the first place!

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
I understand your need, but as you mentioned yourself your case seems like an outlier AND this is something that could be implemented on top of the CDK (and shared as a 3rd party library should the need arise).

I will keep this issue open to collect potential upvotes, but this is unlikely to be something that we'll address in CDK core.

**Comment by liamfd** [comment]
@rix0rrr makes sense, thanks!

**Comment by liamfd** [comment]
For anyone else encountering this, I can share what I've come up with so far. 

```ts
import * as cdk from '@aws-cdk/core';

const isCdkReferenceToken = <T>(member: T, s: string) => {
  // taken from `exportValue`
  // https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/core/lib/stack.ts#L833-L836
  const resolvable = cdk.Tokenization.reverse(member);
  return resolvable && cdk.Reference.isReference(resolvable);
};

export const exportResourceAttrs = (
  scope: cdk.Stack,
  resource: cdk.Resource
) => {
  // note that Object.entries only pulls "own" properties, which is what we want,
  // we don't want to traverse the prototype chain
  Object.entries(resource)
    .filter(([memberKey, memberVal]) =>
      isCdkReferenceToken(memberVal, memberKey)
    )
    .forEach(([memberKey, memberVal]) => {
      scope.exportValue(memberVal);
    });
};
```


This approach is based off of this assumption I mention above:

> My understanding is that the auto-export system kicks in when a resource property is a Reference. If that's correct, and the full set of potentially autogenerated Outputs is the set of properties that are References...

(As far as I can tell, anything that can be accessed with `Fn::GetAtt` or `Ref` gets represented as a `Reference`).

I have a suspicion that this is over-exporting for some resources. Meaning, some References might not ever get used by the CDK for imports, but I'm not 100% sure about that. Either way, for our needs, over-exporting is better than under-exporting.
