### ISSUE TITLE
AppSync: resolver can become detached when renaming resources

### ISSUE THREAD

**Issue by ansman** [aws/aws-cdk#13653]
If an AppSync data source or Lambda function is renamed then on the next deploy AppSync will sometimes leave the resolver detached after deploying successfully

### Reproduction Steps
1. Create an AppSync app with a single data source backed by a lambda function
2. Deploy the stack
3. Change the name of the lambda function and/or data source
4. Deploy again

### What did you expect to happen?
The resolver should be attached after deployment.

### What actually happened?
The resolver is not attached.

### Environment
  - **CDK CLI Version:** 1.91.1
  - **Framework Version:** 1.91.0
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):** 

### Other
When this happens I typically have to comment out the resolvers and data source creation, deploy, uncomment and deploy again.

--- 

This is :bug: Bug Report

**Comment by ansman** [comment]
I've also had issues where new data sources aren't created when backed by the same lambda function, though I'm unsure if that is the same problem.

**Comment by MrArnoldPalmer** [comment]
Hey ansman, we have this covered in https://github.com/aws/aws-cdk/issues/13269. Its quite an annoying one. Keep on eye on that issue for updates and provide any new info there so we can keep things consolidated. Feel free to reopen if you think this isn't covered.
