### ISSUE TITLE
[cdk-pipelines]: Typescript pipeline fails with module missing errors on code build

### ISSUE THREAD

**Issue by pankajagrawal16** [aws/aws-cdk#13666]
It exactly the same issue as mentioned here on stackoverflow

https://stackoverflow.com/questions/66590492/aws-codebuild-tsc-error-ts2307-cannot-find-module

If we follow https://cdkworkshop.com/20-typescript/70-advanced-topics/200-pipelines.html.

Essentially, npm i (or npm ci) + tsc works fine locally, but when done over CodeBuild, it appears my dependencies don't have their dependencies installed, causing tsc to break.

### What did you expect to happen?

To build successfully on code build

### What actually happened?

Build fails with missing module errors

### Environment

  - **CDK CLI Version  :** 1.94.1
  - **Framework Version:**
  - **Node.js Version:** v12.19.1
  - **OS               :** Linux
  - **Language (Version):** TypeScript

### Other

https://stackoverflow.com/questions/66590492/aws-codebuild-tsc-error-ts2307-cannot-find-module

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
That is a weird problem, that seems to have to do with the particulars of NPM. I'm going to need your help debugging this.

* What are the versions of your local NPM and the NPM on the CodeBuild image? (`npm --version`)
* Does the `package-lock.json` contain the dependencies that seem to be missing? (`grep constructs package-lock.json`)
* What do the dependency trees on your local machine and the CodeBuild server look like after running `npm ci` ? (`find . -name package.json`)

See if you can start forming some hypotheses about what might be wrong from the clues that these checks turn up

**Comment by pankajagrawal16** [comment]
> * What are the versions of your local NPM and the NPM on the CodeBuild image? (`npm --version`)

Local: 7.6.0
CodeBuild: 6.14.8

**Comment by rix0rrr** [comment]
I think it MIGHT be.

Can you try running the following locally:

```ts
$ npx npm@6 install
```

This should probably update your `package-lock.json`. Commit and push that new `package-lock.json` file, and then see if the CodeBuild job proceeds to work correctly...?

**Comment by rix0rrr** [comment]
Wait:

> > Does the package-lock.json contain the dependencies that seem to be missing? (grep constructs package-lock.json)
> No. package-lock.json looks correct

What do you mean "no" ?

The question was: "Are the dependencies in there". Is the answer: "they are not in there" ?

**Comment by rix0rrr** [comment]
Here is my hypothesis:

In NPM7, the dependency resolution algorithm has changed.

It *might* be that NPM7 writes a `package-lock.json` that contains less information: enough information for the NPM7 dependency resolution algo, but not enough for the NPM6 algo.

**Comment by pankajagrawal16** [comment]
> 
> The question was: "Are the dependencies in there". Is the answer: "they are not in there" ?

Yeah sorry for confusion, they are not in there

**Comment by pankajagrawal16** [comment]
> Here is my hypothesis:
> 
> In NPM7, the dependency resolution algorithm has changed.
> 
> It _might_ be that NPM7 writes a `package-lock.json` that contains less information: enough information for the NPM7 dependency resolution algo, but not enough for the NPM6 algo.

I tried upgrading npm on code build image and that solved the issue. So your hypothesis might be correct

**Comment by rix0rrr** [comment]
> Yeah sorry for confusion, they are not in there

From my point of view them not being in there is NOT "correct", it is incorrect.

But, looks like NPM has changed the definition of what correct means in this case... 😖
