### ISSUE TITLE
SFN DynamoPutItem task has problems storing number from input

### ISSUE THREAD

**Issue by ivan-luska** [aws/aws-cdk#13669]
In my step function I am storing values from input JSON using DynamoPutItem task.
For numeric value the task fails, although the number is far below the limit.

### Reproduction Steps

The code:
`
DynamoPutItem(
            self,
            "StoreInputData",
            table=table,
            item={
                "ttl": DynamoAttributeValue.from_number(JsonPath.number_at("$.ttl"))
            },
            result_path=JsonPath.DISCARD,
        )
`

Input JSON:
`  
{
"ttl": 1617285482
}
`

In generated SFN definition I can see something malformed:
`
"ttl":{"N":"-1.8881545897088288e+289"}
`

Instead of expected:
`
"ttl":{"N.$":"$.ttl"}
`
### What did you expect to happen?
Numeric value is stored into the Dynamo table

### What actually happened?
Failure.

Task fails with the following error:

_Error_

_DynamoDB.AmazonDynamoDBException_
_Cause_

_Number overflow. Attempting to store a number with magnitude larger than supported range (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ValidationException; Request ID: 390d6e8a-8520-4e6e-ac23-2824221ad91f; Proxy: null)_

### Environment

  - **CDK CLI Version  : 1.94.1**
  - **Framework Version: 1.93.0**
  - **Node.js Version: 15.5.1** 
  - **OS               : MacOS Catalina**
  - **Language (Version): Python 3.7.10, Clang 12.0.0** 

### Other

--- 

This is :bug: Bug Report

**Comment by shivlaks** [comment]
@ivan-luska 

rather than 
```
DynamoAttributeValue.from_number(JsonPath.number_at("$.ttl"))
```

have you tried using:

```
DynamoAttributeValue.number_from_string(JsonPath.number_at("$.ttl"))
```

The key difference here is that `number_at` is intended to read a literal number.
However, `number_from_string` allows you to use numbers such that they may be expressed as literal strings or as JsonPath, which is what you're really attempting to do here.

I'm marking this issue as `guidance` and dropping the `bug` label.

Let me know how it goes!

**Comment by ivan-luska** [comment]
Well the only way it works is:

`DynamoAttributeValue.number_from_string(JsonPath.string_at("$.ttl"))`

Assuming I send "ttl" as string. But that is fine for use-case too. No need to investigate further I think.

**Comment by peterwoodworth** [comment]
Seems like this issue is resolved, ping me if you have more concerns with this :smile:
