### ISSUE TITLE
(@aws-cdk/aws-apigatewayv2-integrations): Set Secure server name 

### ISSUE THREAD

**Issue by rettal** [aws/aws-cdk#13673]
### The Question

Can I set the "Secure Server Name" for an API Gateway Integration in cdk code? On the console you can by visiting:
API Gateway > Integrations > Edit, then Advanced Settings.

### Environment

  - **CDK CLI Version:** 1.93.0 (build c506d3b)
  - **Module Version:** 1.94.1
  - **Node.js Version:** v14.16.0
  - **OS:** macOS Catalina
  - **Language (Version):** TypeScript (3.9.9)

### Other information
![Screenshot 2021-03-18 at 17 29 55](https://user-images.githubusercontent.com/399569/111670227-81e3a980-880f-11eb-92cc-d60adaf3eb96.png)

**Comment by peterwoodworth** [comment]
Thanks for the question @rettal,

Unfortunately there is currently no way to do this, as CloudFormation currently does not allow you to set the secure server name. Is this a feature you would like to see the CDK have?

**Comment by rettal** [comment]
Thanks very much for the response peterwoodworth.

Yes, it would be great if we could set this with the CDK, as this value needs to be set in our case as our backend is https but it's the only thing we can't set in code.

We can work around now we know it's currently not possible.

Thanks again for the response.

**Comment by peterwoodworth** [comment]
@rettal I apologize for the earlier guidance, as I believe it was incorrect.

You can set the [TlsConfig property](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apigatewayv2-integration-tlsconfig.html) in an [L1 ApiGateway::V2::Integration](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-apigatewayv2.CfnIntegration.html#tlsconfig) to set the Secure Server name in CDK code.

**Comment by rettal** [comment]
@peterwoodworth no worries.

I don't want this issue to turn into a long support ticket but in our case we are using an ALB as the backend for the gateway, and we are doing this:

`const integration = new HttpAlbIntegration({
    listener: appListener,
    vpcLink: vpcLink
});`

and then to add to a API Gateway route we do:

`httpApi.addRoutes({
    path: '/api',
    methods: [
        HttpMethod.GET,
        HttpMethod.OPTIONS,
    ],
    integration: integration      
 });`

We were hoping to be able to set the secure server name by passing a prop to `HttpAlbIntegration`.

At first I tried just passing the CfnIntegration instance to `integration` prop. on `httpApi.addRoutes` but I got an error saying `bind` was not implemented but I think I have fixed this now by extending `CfnIntegration` and implementing a `bind` method, this means I can now pass it to `httpApi.addRoutes`, it seems to work but it's creating 2 integrations,  one with the secure server name and one without, I am planning to tackle this next.

I just wanted to give you a more specific example of what we are exactly doing.

Thanks again.

**Comment by peterwoodworth** [comment]
Thank you for the specific example, I was first looking into being able to set the prop in `HttpAlbIntegration()`, and I continued to look last night. I don't think there's a way to do this right now, I'll check to verify and if not we can submit a feature request for that.

You _are_ able to use them with L1 constructs, which I mentioned and linked above. I'm glad you tried to use the `CfnIntegration()` I linked, let me know if you need additional guidance! Read through [this link](https://docs.aws.amazon.com/cdk/latest/guide/constructs.html#constructs_l1_using) if you're going to continue using L1 constructs.

**Comment by peterwoodworth** [comment]
I can confirm that there is no current way to set the SSN with use of `HttpAlbIntegration()`. As this would be helpful for you, there should be a feature request up for this, I'll make sure this gets done if there isn't already a request up for this. 

Have you been able to successfully find a workaround @rettal?

**Comment by peterwoodworth** [comment]
I'll be closing now, as I have a feature request up for this. Feel free to ping me if you need additional guidance!
