### ISSUE TITLE
CDK Tree: ability to easily add node attributes to Constructs

### ISSUE THREAD

**Issue by pistazie** [aws/aws-cdk#13672]
While coding https://github.com/pistazie/cdk-dia I used CDK's tree in order to create diagrams that have a clear structure (thanks to the Tree's hierarchy).

In order to allow a developer to customize these diagrams, I need a way to add attributes to an existing/new IConstruct.

The only current way I could find was: Extend the Construct, implement IInspectable, implement the 'inspect' method. this israther complicated/verbose/cumbersome (see example in cdk-dia).

The dream solution could look like:
```
const bucket = s3.Bucket(...)
bucket.addTreeAttribute("key","val")
```

I am guessing this is quite a unique use-case and would appreciate any other suggestion regarding how could one pass data from the site of object construction to the Tree.

### Other
Additionally having the option to plugin to CDK and be able to put a hook on Tree construction could be very nice-to-have.

I am following up here on:
@webratz yes! that's the direction. And obvsiouly we want to also model the construct tree... Would love a contribution if you are inclined 😉. Might require some low-level changes, so ping us if you need some guidance.

_Originally posted by @eladb in https://github.com/aws/aws-cdk/issues/301#issuecomment-405220311_

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
You can try investigating `construct.node.addMetadata()`. Not exactly sure whether those will end up in the `tree.json`, but if not I'm okay defining a metadata protocol that will render to the tree schema. Propose a PR!
