### ISSUE TITLE
(aws-ecs): Unable to update a service -- Resource of type 'AWS::ECS::Service' with identifier 'xxx' already exists

### ISSUE THREAD

**Issue by pv93** [aws/aws-cdk#13678]
### The Question

I'd like to add a deployment circuit breaker to my existing service. Here's the output of `cdk diff`:

```
Resources
[~] AWS::ECS::Service ApiFargateService/Service/Service ApiFargateServiceB7375C2C replace
 ├─ [~] DeploymentConfiguration
 │   └─ [+] Added: .DeploymentCircuitBreaker
 └─ [+] DeploymentController (requires replacement)
     └─ {"Type":"ECS"}
[~] AWS::ECS::Service WorkerService/Service PollerService2DE8D360 replace
 ├─ [~] DeploymentConfiguration
 │   └─ [+] Added: .DeploymentCircuitBreaker
 └─ [+] DeploymentController (requires replacement)
     └─ {"Type":"ECS"}
```

When I try to deploy these changes, the WorkerService (EC2-backed service) fails to deploy, with this error:

```
Resource of type 'AWS::ECS::Service' with identifier 'worker' already exists.
```

What should I do here? I can update it in the UI just fine so I figure cloudformation should be able to do the same.

### Environment

  - **CDK CLI Version:** 1.94.1 (build 60d8f91)
  - **Module Version:** 1.94.1
  - **Node.js Version:** 15.4.0
  - **OS:** docker image: node:15.4.0-buster-slim
  - **Language (Version):** Typescript

**Comment by peterwoodworth** [comment]
Each physical resource attached to your AWS account has to have a unique name. [Read here](https://docs.aws.amazon.com/cdk/latest/guide/resources.html#resources_physical_names) to learn more about how physical resource names work. Check the AWS console to see the existing physical resource with the serviceName `xxx`

You are likely specifying the service's physical `serviceName` when a service with that physical name already exists. There could be a number of reasons why the resource already exists, and without seeing your stack code I'm not sure exactly why this might be happening. I'd like to point out something in the link above that could be your problem:
```
Most importantly, any changes to deployed resources that require a resource replacement, such as changes to a resource's properties that are immutable after creation, will fail if a resource has a physical name assigned. If you end up in a state like that, the only solution is to delete the AWS CloudFormation stack, then deploy the AWS CDK app again.
```

Let me know if this helps!

**Comment by pv93** [comment]
@peterwoodworth Thanks for that info peter, that does help.
