### ISSUE TITLE
(s3): L2 Construct for S3 Object Lambda

### ISSUE THREAD

**Issue by NukaCody** [aws/aws-cdk#13675]
L2 Construct for S3 Object Lambda

### Use Case

To allow the ability to add custom logic in front of S3 Get Request

### Proposed Solution

- @aws-cdk/aws-lambda-event-sources
- @aws-cdk/aws-lambda
- @aws-cdk/aws-s3

```typescript
const fn = new lambda.Function(this, 'MyFunction', {
  runtime: lambda.Runtime.NODEJS_12_X,
  handler: 'index.handler',
  code: lambda.Code.fromAsset(path.join(__dirname, 'lambda-handler')),
});

const bucket = new Bucket(this, 'MyEncryptedBucket', {
    encryption: BucketEncryption.KMS
    objectLambda: fn
});
```

### Other

- https://aws.amazon.com/about-aws/whats-new/2021/03/s3-object-lambda-allows-you-to-add-your-own-code-to-s3-get-requests-to-modify-and-process-data-as-it-is-returned-to-an-application/
- https://aws.amazon.com/blogs/aws/introducing-amazon-s3-object-lambda-use-your-code-to-process-data-as-it-is-being-retrieved-from-s3/

Does not seem to have CFN support yet, so may have to wait a little bit.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by jansepke** [comment]
CDK support is here https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-s3objectlambda-accesspoint.html and CDK L1 support here https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_s3objectlambda.CfnAccessPoint.html but as it is so hard to find a L2 construct would be great

**Comment by melchii** [comment]
Is there any plan to add `AccessPointPolicy`?

Ref: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-s3objectlambda-accesspointpolicy.html

It will work fine to combine the L2 and L1 constructs, but ideally this would be vended as an L2 construct.
