### ISSUE TITLE
Amazon Resource Name acronym varies throughout documentation

### ISSUE THREAD

**Issue by OksanaH** [aws/aws-cdk#13688]
In the documentation/comments Amazon Resource Name acronym varies - it can be "arn", "Arn" or "ARN". Perhaps it should be the same throughout? ("ARN") If this is a legitimate piece of work, I'm happy to do it because I'm looking to start contributing to CDK :)
![ARN](https://user-images.githubusercontent.com/34384274/111773324-f23d0a00-88a5-11eb-9547-83b1e42275d2.JPG)
![arn_lower](https://user-images.githubusercontent.com/34384274/111773330-f406cd80-88a5-11eb-8cac-f75ad1b812b2.JPG)
![Arn_firstCapital](https://user-images.githubusercontent.com/34384274/111773341-f6692780-88a5-11eb-99fc-e54bca46f181.JPG)

**Comment by peterwoodworth** [comment]
Hey @OksanaH, 
We're happy you're looking to start contributing to the CDK! However, this is a trivial change, as the meaning of the current documentation is understood 😄 

If you're looking to start contributing check out our contributions guide [`CONTRIBUTING.MD`](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md#documentation) to find a way you'd like to contribute!

Let me know if you have any additional questions
