### ISSUE TITLE
Creating my own templates to initialise a Cdk project with. 

### ISSUE THREAD

**Issue by mrpackethead** [aws/aws-cdk#13680]
Creating my own templates to initialise a Cdk project with. 

### Use Case

When I start up a new CDK rpojects theres a whole stack of thigns that i need to do in order to get it 'ready' for our environment.. 

- we change virtualenv from  .venv to  .projectname
- we modify our python pip environment to use a code artifact repo rather than pypi.
- we typically would start a project with a few things,  that are specific to our project, and layout folders etc.
- set up git for a new repo

These things all take a bit of time and because they are done manually are prone to subtle and annoying changes. 

### Proposed Solution

No real idea how this could be done. 

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
I happen to know about an existing tool that allows you to create project templates: https://github.com/cookiecutter/cookiecutter

There are probably more.

It's unlikely we will do anything about this in our CLI, project templates are not our core business.
