### ISSUE TITLE
(ecs): add a name prop to ContainerDefinition

### ISSUE THREAD

**Issue by CarlosDomingues** [aws/aws-cdk#13681]
When creating a [ContainerDefinition](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs.ContainerDefinition.html) resource, it's not currently possible to specify its name. It seems the current behavior is to use the object's `id` as name, but that's not documented and can lead to surprising behavior.

My suggestion is to add a new optional prop `name` that maps directly to `CfnTaskDefinition.ContainerDefinitionProperty.Name`. 

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by MrArnoldPalmer** [comment]
@CarlosDomingues, this shouldn't be an issue, but generally speaking CDK discourages naming things explicitly. Though there are some cases where it makes sense. What "unexpected behavior" is it that you've encountered?

**Comment by CarlosDomingues** [comment]
@MrArnoldPalmer my use case is to configure `AppMeshProxyConfiguration`. In my understanding it expects a `container_name` prop (at least in Python) that indicates explicitly in which container an envoy proxy will be instantiated.

**Comment by MrArnoldPalmer** [comment]
Sounds good to me! thanks for providing more context, always helps.

**Comment by SoManyHs** [comment]
Closing in favor of https://github.com/aws/aws-cdk/issues/8044
