### ISSUE TITLE
(aws-codepipeline-actions): Type 'string' is not assignable to type 'S3EventSelector'.

### ISSUE THREAD

**Issue by niklaswallerstedt** [aws/aws-cdk#13684]
**Docs**
(CDK v1.94.1)
https://docs.aws.amazon.com/cdk/api/latest/docs/aws-codepipeline-actions-readme.html#aws-s3-source

Using the example for setting up CloudTrail with CloudWatch Events to trigger a pipeline produces:
>Type 'string' is not assignable to type 'S3EventSelector'.

```ts
trail.addS3EventSelector([sourceBucket.arnForObjects(key)], {
      ...
    });
```
Working with:
```ts
trail.addS3EventSelector([{
      bucket: sourceBucket,
      objectPrefix: key
    }], {
      ...
    });
```
---

This is a 📕 documentation issue

**Comment by skinny85** [comment]
Thanks for reporting @niklaswallerstedt ! Any chance of a PR fixing this? Our contribution guide: https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md. The offending example is here: https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-codepipeline-actions/README.md#aws-s3-source

Thanks,
Adam

**Comment by BLasan** [comment]
@skinny85 Shall I work on this?

**Comment by niklaswallerstedt** [comment]
@skinny85 made the change, noticed that the readme was missing fixtures though @BLasan

**Comment by BLasan** [comment]
> @skinny85 made the change, noticed that the readme was missing fixtures though @BLasan

Hope your PR fully fixes this issue. :)
