### ISSUE TITLE
(dynamodb): lambda resource boundaries changed after updating cdk 

### ISSUE THREAD

**Issue by quzaid** [aws/aws-cdk#13695]
After updating our cdk version from 1.32 to 1.92, our lambda resource permission is changed from a specific table to `*` 

### Reproduction Steps
```
 const someTable= new dynamodb.Table(this, 'someTable', {
      tableName: resourcesNamePrefix + 'someTableName',
      partitionKey: {
        name: 'oi',
        type: AttributeType.STRING
      },
      sortKey: {
        name: 'vn',
        type: AttributeType.NUMBER
      },
      billingMode: BillingMode.PAY_PER_REQUEST,
      pointInTimeRecovery: true,
      serverSideEncryption: true,
      stream: StreamViewType.NEW_IMAGE,
    });
    const someLambda = new lambda.Function(this, 'SomeLambdaName', {
      functionName: resourcesNamePrefix + 'SomeLambdaName',
      code: <some lambda resource >,
      handler: "SomeLambdaName.handler",
      timeout: cdk.Duration.seconds(30),
      runtime: lambda.Runtime.NODEJS_12_X,
    });
    someLambda.addEventSource(new DynamoEventSource(someTable, {
      startingPosition: StartingPosition.LATEST,
      batchSize: 25
    }));
    someLambda.addToRolePolicy(new iam.PolicyStatement({
      effect: iam.Effect.ALLOW,
      actions: [ 'dynamodb:Query', 'dynamodb:BatchWriteItem' ],
      resources: [ anotherTableArn, `${anotherTableArn}/index/*` ]
    }));
```
### What did you expect to happen?

Because this stack is already deployed in production, after updating cdk version from 1.32 to 1.92 I expected no changes with this lambda, especially no changes to IAM policies.

### What actually happened?
![image](https://user-images.githubusercontent.com/80969056/111798509-82785080-88a0-11eb-8360-c026c556f0f3.png)

IAM policy on the lambda changes to allow db streams from any resource rather than the specific one added through:

```
someLambda.addEventSource(new DynamoEventSource(someTable, {
      startingPosition: StartingPosition.LATEST,
      batchSize: 25
    }));
```

### Environment

  - **CDK CLI Version  : ** 1.92.0
  - **Framework Version:**
  - **Node.js Version:** 12.21
  - **OS               : ** AmazonLinux2
  - **Language (Version):**  Typescript 3.6.4

### Other

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
The change is coming from this commit - https://github.com/aws/aws-cdk/commit/b2f16b3c051406b58961327b7d4924d61ea09057. As described in the commit description and the linked documentation, `dynamodb:ListStreams` does not support specifying a specific resource type. It only supports `*`.

**Comment by quzaid** [comment]
no, I wasn't aware that ListStreams only supports `*`. Thank you for your response.
