### ISSUE TITLE
Issue importing with CfnInclude when template do not have quotes 

### ISSUE THREAD

**Issue by vincent851** [aws/aws-cdk#13709]
I encounter this issue when trying to import CloudFormation YAML Template to create IAM role.

The template have the following header:
AWSTemplateFormatVersion: 2010-09-09
and also version with date
Version: 2012-10-17.

The error I encounter is when trying to deploy the template to the AWS via CDK.
The build is fine but when deploying I encounter the following error:
failed: Error [ValidationError]: Template format error: unsupported value for AWSTemplateFormatVersion.

I noticed that the same template can be deploy via AWS CLI and validated without issue using:
aws cloudformation create-stack --stack-name
and 
aws cloudformation validate-template --template-body

I think this is a bug because AWS CLI have no issue with this why would deploying via CDK raises error.

### Reproduction Steps

Deploying via CDK with any template with the above header would work that do not have quotes around the date. 

### What did you expect to happen?

it would throw an error 
failed: Error [ValidationError]: Template format error: unsupported value for AWSTemplateFormatVersion.
### What actually happened?

failed: Error [ValidationError]: Template format error: unsupported value for AWSTemplateFormatVersion.

### Environment

  - **CDK CLI Version  :1.81.0**
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               : MacOS**
  - **Language (Version): Typescript** 

### Other

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hi @vincent851 ,

Thanks for opening the issue. Can you please attach the template that is causing this error?

Thanks,
Adam

**Comment by vincent851** [comment]
AWSTemplateFormatVersion: 2010-09-09
Resources: 
  RootRole: 
    Type: "AWS::IAM::Role"
    Properties: 
      AssumeRolePolicyDocument: 
        Version: 2012-10-17
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "ec2.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Path: "/"
  RolePolicies: 
    Type: "AWS::IAM::Policy"
    Properties: 
      PolicyName: "root"
      PolicyDocument: 
        Version: 2012-10-17
        Statement: 
          - Effect: "Allow"
            Action: "*"
            Resource: "*"
      Roles: 
        - Ref: "RootRole"
  RootInstanceProfile: 
    Type: "AWS::IAM::InstanceProfile"
    Properties: 
      Path: "/"
      Roles: 
        - Ref: "RootRole"

**Comment by vincent851** [comment]
I am editing the above to remove the quotes to match the issue I have. the above will still work with AWS CLI but will not work when deploying via CDK. the CDK Will built but deployment will fail

**Comment by skinny85** [comment]
Thanks for the template @vincent851 . I can confirm I'm able to reproduce the problem. I have a guess what happens (the YAML library interprets `2010-09-09` as a Date instead of a String). I'm working on a fix.
