### ISSUE TITLE
(aws-cdk/aws-ec2.UserData): Didn't run properly user data commands

### ISSUE THREAD

**Issue by fabriciolelis** [aws/aws-cdk#13704]
I try to deploy a EC2 instance and execute user data commands but it didn't run.

### Reproduction Steps

      const ubuntuLinux = ec2.MachineImage.genericLinux({
            'ca-central-1': 'ami-02e44367276fe7adc',
      });

        const ec2Instace = new ec2.Instance(this, 'Instance', {
            vpc,
            instanceType: ec2.InstanceType.of(ec2.InstanceClass.T2, ec2.InstanceSize.MEDIUM),
            machineImage: ubuntuLinux,
            securityGroup: ejabberdSecurityGroup
        });

        ec2Instace.userData.addCommands(
            "wget https://conf-machine.sh",
            "chmod +x conf-machine.sh",
            "./conf-machine.sh" 
        );

### What did you expect to happen?

I expect that download this bash file and execute the commands. This bash file is stored on S3 Bucket.

### What actually happened?
The commands are not executed and the file is not downloaded.

### Environment

  - **CDK CLI Version  :** 1.94.1 
  - **Framework Version:**
  - **Node.js Version:** 12.19.0
  - **OS               :** Linux
  - **Language (Version):** 3.7.2 

### Other

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
That is unfortunate to hear. We are going to need your help debugging though. Does the UserData show up in the template? Have you Googled for possible causes yet?

**Comment by fabriciolelis** [comment]
@rix0rrr The UserData shows in template. I think that the machine doesn't have connection because when I connect to it through to AWS console and I run a command like apt update shows that no connection and the command fails.

**Comment by rix0rrr** [comment]
Thanks for figuring that out. Going to close this issue then, as it's not really a bug in the CDK.

We can't know beforehand whether your instance is going to have internet connectivity, nor whether the UserData commands you're going to run require internet connectivity or not.

**Comment by fabriciolelis** [comment]
> Thanks for figuring that out. Going to close this issue then, as it's not really a bug in the CDK.
> 
> We can't know beforehand whether your instance is going to have internet connectivity, nor whether the UserData commands you're going to run require internet connectivity or not.

But when I use a older version of CDK that works. Could you help me?

**Comment by fabriciolelis** [comment]
> Thanks for figuring that out. Going to close this issue then, as it's not really a bug in the CDK.
> 
> We can't know beforehand whether your instance is going to have internet connectivity, nor whether the UserData commands you're going to run require internet connectivity or not.

@rix0rrr I belive if you try to create a EC2 instance with CDK, you have the same problem. Could you try?
