### ISSUE TITLE
aws-eks: OpenIDConnectProvider property not accessible during synthesizing

### ISSUE THREAD

**Issue by SbgMartin** [aws/aws-cdk#13701]
Building or synthesizing an AWS CDK app which creates an AWS IAM Role for ServiceAccount (IRSA) fails with error message

`"openIdConnectProvider" is not defined for this imported cluster`

This happens when you try

`npm run test`
or
`cdk synth`

### Reproduction Steps

1. Import an AWS EKS Cluster into your stack

```
const eksCluster = Cluster.fromClusterAttributes(this,"my-imported-eks-cluster",{
    clusterName: eksClusterName
});
```

2. Access openIdConnectProvider

`eksCluster.openIdConnectProvider.openIdConnectProviderIssuer`

3. cdk synth or npm run test

### What did you expect to happen?

That this property is despite lazy loading, "accessible" and doesn't throw this exception.

### What actually happened?

<img width="537" alt="image" src="https://user-images.githubusercontent.com/5551897/111818289-4a443280-88df-11eb-9ca5-0c2f138f1c26.png">

### Environment

  - **CDK CLI Version  : *1.93.0*
  - **Framework Version: *1.93.0*
  - **Node.js Version: *v15.11.0*
  - **OS               :*OS X*
  - **Language (Version):*TypeScript 4.2.3*

### Other

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment]
@SbgMartin When importing an external cluster, you must provide the OpenID provider as well if you wish to use it. See [Service Accounts](https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/aws-eks#service-accounts).

When creating a new cluster, a provider is created on your behalf, so you don't need to provide it.

```ts
const cluster = new eks.Cluster(...);
const provider = cluster.openIdConnectProvider;
```

**Comment by SbgMartin** [comment]
Thanks, @iliapolo for clarification and your help. I will close this bug as it works as designed.
From user perspective I would see a benefit to obtain those transparent dependencies like OIDC providers to EKS clusters more or less "automatically" based on the existing relation on AWS Account. If we need to know also IAM Provider ARN (as an detail of an internal dependency) then we need to publish two pieces of information (Cluster name + OIDC ARN) to application teams who want to use IRSA. Let's see, maybe there is a chance to wrap this in a project specific higher level construct or pattern.

Thanks again
