### ISSUE TITLE
(rds): addRotationMultiUser expects an attached secret

### ISSUE THREAD

**Issue by akefirad** [aws/aws-cdk#13719]
https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-rds/README.md

`addRotationMultiUser` expect a secret that is attached (has `host`, etc) and has `masterarn` key.

* [x] :wave: I may be able to implement this feature request

---

This is a :rocket: Feature Request

**Comment by akefirad** [comment]
@skinny85 I'm thinking if this could/should be a feature request, meaning could/should we attach the secret to the instance (for all practical purposes it does make sense).

**Comment by skinny85** [comment]
Sorry @akefirad , can you explain what is this issue about? I have to say, I don't understand what the problem is from the description...

**Comment by akefirad** [comment]
Copied from the documentation:
```typescript
const myUserSecret = new rds.DatabaseSecret(this, 'MyUserSecret', {
  username: 'myuser',
  secretName: 'my-user-secret', // optional, defaults to a CloudFormation-generated name
  masterSecret: instance.secret,
  excludeCharacters: '{}[]()\'"/\\', // defaults to the set " %+~`#$&*()|[]{}:;<>?!'/@\"\\"
});
const myUserSecretAttached = myUserSecret.attach(instance); // Adds DB connections information in the secret

instance.addRotationMultiUser('MyUser', { // Add rotation using the multi user scheme
  secret: myUserSecretAttached,
});
```
To me it does make sense to attach the secret to the instance inside `addRotationMultiUser` method, not asking the user to do it. Is there any reason not to do it?

**Comment by skinny85** [comment]
I agree with you 🙂.

**Comment by akefirad** [comment]
Now the question is, where to do it, in `DatabaseSecret` or in the rotation feature? Or both? And how to check if it's already attached since this can be a breaking change.

**Comment by skinny85** [comment]
So, I see there's already code in `Secret` to check that: https://github.com/aws/aws-cdk/blob/6f6e079569fcdb7e0631717fbe269e94f8f7b127/packages/%40aws-cdk/aws-secretsmanager/lib/secret.ts#L286-L291

Let's piggy-back on that, and maybe add an `isAttached(target): boolean` method to `Secret`, and use it here, to make it backwards-compatible?
