### ISSUE TITLE
(rds): additional single-user secret rotation

### ISSUE THREAD

**Issue by akefirad** [aws/aws-cdk#13718]
As a user, I want to add additional single-user secret rotation to RDS instance.

### Use Case
We have an RDS instance in which we created a administrator user. We need to add a secret rotation to it, and since we're using it only during the application startup, it doesn't need to rotate in multi-user manner (please note that we can't use multi-user rotation for this secret). If I understand it correctly, `addRotationSingleUser` adds a rotation to only the master secret of the DB instance. 
It would be nice to use the method to add single-user rotation for additional secrets.

### Proposed Solution

```typescript
instance.addRotationSingleUser("AddtionalSigleUserRotation", {
  secret: someSecret // Is it possible to add this to RotationSingleUserOptions similar to RotationMultiUserOptions?
});

```

### Other
My understand is that if we refactor `addRotationSingleUser` to check if `secret` in the given options is null, then it's a rotation for the master secret, otherwise it's a new one. I took a quick look at the implementation and I think it's possible to do so.

* [x] :wave: I may be able to implement this feature request

---

This is a :rocket: Feature Request

**Comment by skinny85** [comment]
Hey @akefirad ,

thanks for opening the issue, but I believe what you're asking is not possible.

RDS does not support a single-user rotation of any secret beyond the master user secret. The reason why is that the rotation must be integrated with the database engine (so the secret needs to change in SecretsManager, and then in the database itself as well).

If you think I'm wrong, feel free to experiment; use our ["Contributing" guide](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md#linking-against-this-repository) to build the project, and then link a sample CDK application against it. Try adding a `secret` option to the `addSingleRotation()` method, and see if it works! I have a feeling it will not, and the secret will be changed in SecretsManager, but _not_ in the database, and everything will break.

Let me know if you need any help in setting up the code for the experiment!

Thanks,
Adam

**Comment by akefirad** [comment]
Hi @skinny85 

I gave it a quick try and it seems doable, unless I'm missing something.
First I created a normal stack (using explicit secret rotation):
```typescript
export class TestRdsStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const instance = new rds.DatabaseInstance(this, 'Instance', {
      vpc, engine, instanceType, vpcSubnets,
    });
    instance.addRotationSingleUser();

    const additionalSecret = new secrets.Secret(this, "AdditionalSecret", {
      generateSecretString: {
        secretStringTemplate: '{ "username": "additiona_secret" }',
        generateStringKey: "password",
      },
    });

    const additionalSecretRotation = new secrets.SecretRotation(this, "InstanceAdditionalSecretRotation", {
      application: engine.singleUserRotationApplication,
      secret: additionalSecret.attach(instance),
      target: instance,
      vpc,
    });
  }
}
```
And synthesized the template. Then I added `secret` to `RotationSingleUserOptions` and refactored the RDS package:
```typescript
  public addRotationSingleUser(options: RotationSingleUserOptions = {}): secretsmanager.SecretRotation {
    if (options.secret) {
      // TODO: check given secret is not master secret of this!
      // TODO: check given secret is not added already!
      const id = 'AdditionalSecretRotation'; // TODO: how to generate proper ID?
      return this.newSecretRotation(id, options.secret, options); // TODO: should we remove secret from options?
    } else {
      return this.addRotationSingleUserMasterSecret(options);
    }
  }

  private addRotationSingleUserMasterSecret(options: RotationSingleUserOptions): secretsmanager.SecretRotation {
    if (!this.secret) {
      throw new Error('Cannot add single user rotation for an instance without secret.');
    }

    const id = 'RotationSingleUser';
    const existing = this.node.tryFindChild(id);
    if (existing) {
      throw new Error('A single user rotation was already added to this instance.');
    }

    return this.newSecretRotation(id, this.secret, options);
  }

  private newSecretRotation(id: string, secret: secretsmanager.ISecret, options: RotationSingleUserOptions): secretsmanager.SecretRotation {
    return new secretsmanager.SecretRotation(this, id, {
      secret: secret,
      application: this.singleUserRotationApplication,
      vpc: this.vpc,
      vpcSubnets: this.vpcPlacement,
      target: this,
      ...options,
      excludeCharacters: options.excludeCharacters ?? DEFAULT_PASSWORD_EXCLUDE_CHARS,
    });
  }
```
And use it like this:
```typescript
    instance.addRotationSingleUser({secret: additionalSecret.attach(instance)});
```
The synthesized template is exactly the same as the previous one.
Let me know what you think.

Cheers,
Rad

**Comment by skinny85** [comment]
Right. But the question is: will the secret rotation update the password of the user inside the database?

Because if it won't (which I suspect is the case), then this feature doesn't really make sense I think.

**Comment by akefirad** [comment]
Ah, probably I wasn't clear. We already have such setup (with explicit single-user rotation for additional secret) working just fine. And since the synthesized template is the same I'd expect it to work.

**Comment by akefirad** [comment]
🤔 Are you talking about the fact that the user must exist in the DB for the rotation to work?

**Comment by skinny85** [comment]
Ok @akefirad . If you're certain it does what you think, then can you submit a PR with this feature? Should be very easy, based on your experiment 🙂.

**Comment by akefirad** [comment]
Sure, just a couple of questions (since this is the first time I'm working on internal of CDK):
1. How to check the given secret is not master secret of this?
2. How to check given secret is not added already?
3. How to generate proper IDs for secrets? (I was thinking to as the ID from the caller, but then it doesn't fit into the existing code) 😕

**Comment by skinny85** [comment]
My recommendation? Don't worry about any of that now, submit the PR with whatever you have, and we'll hash out those details there 😃.

**Comment by akefirad** [comment]
There you go!

**Comment by akefirad** [comment]
BTW, I couldn't get Gitpod working. For some reason the instance that I get doesn't have proper tools installed (e.g. node, yarn, etc). Any idea who to fix the issue?

**Comment by skinny85** [comment]
Yes, I think it's because of https://github.com/aws/jsii/pull/2741 (Gitpod uses the `superchain` Docker image from that project).

**Comment by skinny85** [comment]
Sorry @akefirad , did you open a Pull Request? I can't see it...

**Comment by akefirad** [comment]
Oops, sorry, there it is #13799.

**Comment by jogold** [comment]
> (please note that we can't use multi-user rotation for this secret)

@akefirad could you explain why? And also how you're creating this second admin user?

**Comment by akefirad** [comment]
@jogold this is due to the specific user mgmt style we have in our setup. You can see the details [here](https://dba.stackexchange.com/questions/242545). In short it's quite difficult to have a user with DDL privileges in a multi-user rotate setup.
Regarding the second question, we don't share master credential with anyone. Maybe the term `admin` is misleading here. It's just a user with DDL privileges, whereas other _application_ users don't have such privileges.

**Comment by akefirad** [comment]
@skinny85 Let's discuss it here to keep it as part of the ticket. Forget about my case for a moment. This is what I'm trying to do:
1. Each RDS instance has a master credentials. That has to have single-user rotation. All good!
2. You can also have other db users which you can manage via the same stack (only the rotation aspect of them).
3. Currently, CDK allow to setup only multi-user rotation for non-master credentials. But this is not a fundamental limitation.

What I'm proposing to add support for single-user rotation for non-master credentials as well. In other words you already can have:
```typescript
rdsInstance = // create the instance here;
rdsInstance.addSingleUserRotation(); // add rotation for the master credentials

dbWriterSecret = // create or import the secret
rdsInstance.addMultiUserRotation({ secret: dbWriterSercret });

dbReaderSecret = // create or import the secret
rdsInstance.addMultiUserRotation({ secret: dbReaderSecret });
```
And I'm suggesting to have (in addition to the above):
```typescript
dbAdminSecret = // create or import secret
rdsInstance.addSingleUserRotation({ secret: dbAdminSecret });
```
Again, the use case is to support single user rotation for additional DB users/secrets (zero or more, in addition to the master credentials).
Does that make sense?

**Comment by skinny85** [comment]
Yes, I understand completely @akefirad 🙂.

My only concern is: does CloudFormation have support, with their existing resources for RDS and SecretsManager, for this use case?

**Comment by akefirad** [comment]
> with their existing resources for RDS and SecretsManager

As far as CFN is concerned, it's just a secret like any other secret (RDS or non-RDS) and any secret can have rotation setup. (the only difference is the secret attachment which is not relevant here!)
You can prove this by deploying the first stack given above which creates additional secret with single rotation (the catch is that you have to create the user in DB right away for the rotation to succeed, just like multi-user-rotated secrets).
Now what I'm proposing is to use the existing code to do the same, which effectively is the same code (compare my `new secrets.SecretRotation` with the existing CDK code, they're the same).
Does that make sense?
