### ISSUE TITLE
(rds): Missing EnableIAMDatabaseAuthentication on DatabaseCluster 

### ISSUE THREAD

**Issue by mbp** [aws/aws-cdk#13722]
AWS::RDS::DBCluster has a EnableIAMDatabaseAuthentication property, but the CDK DatabaseCluster does not expose it

### Use Case

Enabling IAM Authentication for Aurora RDS Clusters.

### Proposed Solution

Add it :-) It should exist on DatabaseClusterFromSnapshot, too.

This is a :rocket: Feature Request

**Comment by skinny85** [comment]
Thanks for opening the issue @mbp. As always, Pull Requests are very welcome for adding this feature 🙂. Our "Contributing" guide: https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md.

Thanks,
Adam

**Comment by BLasan** [comment]
@skinny85 Can I work on this?

**Comment by skinny85** [comment]
@BLasan sure, go ahead 🙂.
