### ISSUE TITLE
ECS: missing grant methods

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#1372]

**Comment by pgarbe** [comment]
Is anyone working on that? And how would an implementation look like?

I'd like to see something like this:
```typescript
    const table = new dynamodb.Table(this, "myTable", { ... });

    const fargateService = new ecs_patterns.LoadBalancedFargateService(this, "FargateService", { ... });

    table.grantReadData(fargateService);
```

In my understanding, the grantPrincipal must be the TaskRole. But that might be conflicting if someone is creating a Service by the `fromFargateServiceArn` method. And adding the taskRole would be a breaking change.
