### ISSUE TITLE
(lambda): Not able to provision concurrency for the current version of a lambda

### ISSUE THREAD

**Issue by tmhung88** [aws/aws-cdk#13731]
Not able to provision concurrency for the current version of a lambda

### Reproduction Steps

I have a simple stack below to configure provisioned concurrency for a lambda

```
export class LambdaAutoScalingStack extends cdk.Stack {
    constructor(scope: cdk.App, id: string) {
        super(scope, id);

        new lambda.Function(this, 'lambda1', {
            code: new lambda.InlineCode('exports.handler = async () => { console.log(\'hello world\'); };'),
            handler: 'index.handler',
            runtime: lambda.Runtime.NODEJS_10_X,
            currentVersionOptions: {
                provisionedConcurrentExecutions: 3
            }
        })

    }
}
```

### What did you expect to happen?

The lambda should have concurrency provisioned as 3
![image](https://user-images.githubusercontent.com/2813016/111978058-157de880-8b36-11eb-892a-3ca9a760edf2.png)

### What actually happened?

No concurrency was provisioned
![image](https://user-images.githubusercontent.com/2813016/111976747-8e7c4080-8b34-11eb-9524-e0186ad856df.png)

### Environment

  - **CDK CLI Version  : 1.94.1**
  - **Framework Version: 1.94.1**
  - **Node.js Version: v14.15.4**
  - **OS               : Windows**
  - **Language (Version): TypeScript (3.9.7)**

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
Hi @tmhung88 -

Can you check what the CloudFormation template contains against the resource type `AWS::Lambda::Version`? 
It should contain the [`ProvisionedConcurrencyConfig` section](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-version.html).

If that is present, you can also run the [`get-provisioned-concurrency-config` from the CLI](https://docs.aws.amazon.com/cli/latest/reference/lambda/get-provisioned-concurrency-config.html) and check whether that's configured.

Could you try these out and report back?

**Comment by tmhung88** [comment]
Will set aside some time tomorrow to try again.

**Comment by tmhung88** [comment]
@nija-at I don't see any ProvisionedConcurrencyConfig, or Lambda version in the the template.json.

Attached the template json
[tmh-provisioned-lambda-stack.template.json.txt](https://github.com/aws/aws-cdk/files/6254708/tmh-provisioned-lambda-stack.template.json.txt)

**Comment by nija-at** [comment]
Hi @tmhung88 -

`currentVersionOptions` take effect only when the `currentVersion` getter is called.

You will need to modify your code as -

```ts
const fn = new lambda.Function(...);
fn.currentVersion;
```

**Comment by tmhung88** [comment]
> Hi @tmhung88 -
> 
> `currentVersionOptions` take effect only when the `currentVersion` getter is called.
> 
> You will need to modify your code as -
> 
> ```ts
> const fn = new lambda.Function(...);
> fn.currentVersion;
> ```
> 
> The last line actually creates the `currentVersion`.

Thanks. I confirm the provision is done when `fn.currentVersion` is called.

// The getter call is quite unexpected. It'd be great if the constructor `lambdas.Function` invokes this getter, or hide this detail from developers.
