### ISSUE TITLE
(aws-cdk/pipeline): Allow setting cdk deployment role using CLI or setting role to addApplicationStage

### ISSUE THREAD

**Issue by leantorres73** [aws/aws-cdk#13734]
### The Question
I want to set the roles for cdk bootstrap in the cli command. 
My problem starts with CdkPipelines creating one KMS per pipeline created. That implies $1 per pipeline and using a multi-account strategy, with multiple cdk stacks it becomes too expensive. To avoid that I saw you can create a `Pipeline` (from '@aws-cdk/aws-codepipeline') instead of `CdkPipeline` (from '@aws-cdk/pipelines') and set the bucket and KMS, and use the pipeline inside the CdkPipeline. 
With that said, the `addApplicationStage` of `CdkPipeline` uses the role created in the bootstrap, but it doesn't have the rights for accessing the bucket or the KMS specified in the pipeline.

So what I want:
1- Be able to bootstrap setting a role like `cdk bootstrap --trust account2 --deployment-role arn:aws:iam::account2:role/ExistingManagedRole`
2- Another option is to be able of setting a role to the `addApplicationStage` function.

### Environment

  - **CDK CLI Version:** 1.91.0
  - **Module Version:** 1.91.0
  - **Node.js Version:** 12
  - **OS:** Ubuntu
  - **Language (Version):** Javascript

**Comment by rix0rrr** [comment]
Roles are configured on the `Synthesizer` object: https://docs.aws.amazon.com/cdk/latest/guide/bootstrapping.html#bootstrapping-custom-synth
