### ISSUE TITLE
(aws-iam): Validate Role path at build time.

### ISSUE THREAD

**Issue by rcollette** [aws/aws-cdk#13747]
The path of a Role should be validated at build time such as the fact that a leading slash is required along with the valid character types.

### Use Case

To prevent wasted developer time.  Deployments take a while to run and this slows down iteration.

### Proposed Solution

Self explanatory.  

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
Sounds good.
