### ISSUE TITLE
[rds]: ability to specify the name for the automatically generated master password in AWS Secrets Manager

### ISSUE THREAD

**Issue by sunshineo** [aws/aws-cdk#13746]
This was requested in https://github.com/aws/aws-cdk/issues/8984 . But the issue was closed. I looked at the merge request, it seems to provide a way to specify the secret name when attach new secret to the RDS. But what we would prefer is set the name for the auto generated master password that saved in AWS Secrets Manager

@CONJAUMCGCG @hedrall

**Comment by skinny85** [comment]
Hey @sunshineo ,

thanks for opening the issue. The issue you linked to was closed, because the PR adding that feature was merged (#13626), although not yet released.

Does #13626 cover what you need, or are you looking for something else?

Thanks,
Adam

**Comment by sunshineo** [comment]
@skinny85 #13626 does not cover what we need. It does not cover what #8984 ask for. #8984 should not have been closed by #13626

One more time:
When create an RDS, [`By default, the master password will be generated and stored in AWS Secrets Manager with auto-generated description.`](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-rds-readme.html#starting-a-clustered-database) 

The name of that secret is auto-generated as well, we want to be able to specify that name

**Comment by skinny85** [comment]
@sunshineo can you show what code you are using for creating the Cluster?

**Comment by sunshineo** [comment]
```typescript
  const vpc = new ec2.Vpc(stack, 'VPC');
  const cluster = new rds.DatabaseCluster(stack, 'Database', {
    engine: rds.DatabaseClusterEngine.auroraMysql({ version: rds.AuroraMysqlEngineVersion.VER_2_08_1 }),
    instances: 3,
    instanceProps: {
      vpcSubnets: {
        subnetType: ec2.SubnetType.PUBLIC,
      },
      vpc,
    },
  })
  cluster.connections.allowFromAnyIpv4(
    new ec2.Port({
      stringRepresentation: '3306',
      protocol: ec2.Protocol.TCP,
      fromPort: 3306,
      toPort: 3306
    }),
    'Open to everyone')
  // We cannot control the name of the rds secret yet
  // This is a workaround to save the secret full arn with a fixed name
  new ssm.StringParameter(stack, 'temporal-rds-secret-full-arn', {
    description: 'The name of the secret for the rds',
    // This will be the name used by cdk8s project to setup temporal
    parameterName: 'temporal-rds-secret-full-arn',
    stringValue: cluster.secret?.secretFullArn || 'nosecret',
    simpleName: true,
  })
```

**Comment by sunshineo** [comment]
@skinny85 It works. Thank you very much! I guess I did not understand the merge request. However I do get a deprecated warning on `fromUsername`

**Comment by sunshineo** [comment]
I should use `fromGeneratedSecret`

**Comment by sunshineo** [comment]
Shit, adding this will destroy the old db and create a new one
