### ISSUE TITLE
(aws/aws-cdk): CodeBuild step fails after updating cdk version 1.94.1

### ISSUE THREAD

**Issue by A-Fries** [aws/aws-cdk#13743]
The self-mutating cdk pipeline fails at the CodeBuild step. The problem is probably the package-lock.json. From two different systems I created this by "npm i". 

**1. System: -> CodeBuild step successful**
- npm version: 7.5.4
- cdk version: 1.62

**2. System -> CodeBuild step fails**
- npm version: 7.6.3
- cdk version: 1.94.1

### Reproduction Steps

node_modules/@aws-cdk/aws-codebuild/lib/artifacts.d.ts(1,21): error TS2307: Cannot find module '@aws-cdk/aws-s3' or its corresponding type declarations.

node_modules/@aws-cdk/aws-codebuild/lib/cache.d.ts(1,25): error TS2307: Cannot find module '@aws-cdk/aws-s3' or its corresponding type declarations.

node_modules/@aws-cdk/aws-codebuild/lib/pipeline-project.d.ts(1,27): error TS2307: Cannot find module 'constructs' or its corresponding type declarations.

node_modules/@aws-cdk/aws-codebuild/lib/project-logs.d.ts(1,23): error TS2307: Cannot find module '@aws-cdk/aws-logs' or its corresponding type declarations.

node_modules/@aws-cdk/aws-codebuild/lib/project-logs.d.ts(2,21): error TS2307: Cannot find module '@aws-cdk/aws-s3' or its corresponding type declarations.

node_modules/@aws-cdk/aws-codebuild/lib/project.d.ts(1,29): error TS2307: Cannot find module '@aws-cdk/aws-cloudwatch' or its corresponding type declarations.

node_modules/@aws-cdk/aws-codebuild/lib/project.d.ts(2,22): error TS2307: Cannot find module '@aws-cdk/aws-ec2' or its corresponding type declarations.

**and more TS2307 errors...**

[Container] 2021/03/22 18:10:34 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: npm run build. Reason: exit status 2

[Container] 2021/03/22 18:10:34 Entering phase POST_BUILD

[Container] 2021/03/22 18:10:34 Phase complete: POST_BUILD State: SUCCEEDED

[Container] 2021/03/22 18:10:34 Phase context status code:  Message: 

[Container] 2021/03/22 18:10:34 Expanding base directory path: cdk.out

[Container] 2021/03/22 18:10:34 Assembling file list

[Container] 2021/03/22 18:10:34 Expanding cdk.out

[Container] 2021/03/22 18:10:34 Skipping invalid file path cdk.out

[Container] 2021/03/22 18:10:34 Phase complete: UPLOAD_ARTIFACTS State: FAILED

[Container] 2021/03/22 18:10:34 Phase context status code: CLIENT_ERROR Message: no matching base directory path found for cdk.out

### Environment

  - **CDK Version  :*1.94.1*
  - **Node.js Version:*7.6.3* 

### Other

--- 

This is :bug: Bug Report

**Comment by henrist** [comment]
The CodeBuild container you are using most likely uses npm v6. It will not properly understand your v2 lockfile from npm v7. Your easiest fix would be to downgrade to npm v6 for now (and recreate the lockfile so it is created as v1 instead).

See https://github.com/aws/aws-cdk/issues/13541#issuecomment-801606777
