### ISSUE TITLE
(aws-eks): Unable to deploy cluster in regions that are not enabled by default

### ISSUE THREAD

**Issue by civilizeddev** [aws/aws-cdk#13748]
In AWS **Bahrain region (me-south-1)**, establishing an EKS cluster with cdk has been failed,

with this error message:

`"AWS was not able to validate the provided access credentials"`

While it succeeded in AWS Seoul region (ap-northeast-2)

It seems to be related to [the STS endpoint problem](https://aws.amazon.com/premiumsupport/knowledge-center/iam-validate-access-credentials/).

### Reproduction Steps

My Stack contains:

```
import * as cdk from '@aws-cdk/core'
import * as eks from '@aws-cdk/aws-eks'

export class EksStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props: cdk.StackProps) {
    super(scope, id, props)
    new eks.Cluster(this, 'cluster', {})
  }
}

// ...

const app = new cdk.App()
new EksStack(app, 'eks', { env: { region: 'me-south-1' } })
app.synth()
```

When I run it:

```
$ cdk deploy eks
```

It is aborted with an error like:

```
ERROR: AWS was not able to validate the provided access credentials
```

### What did you expect to happen?

The stack should be successfully deployed.

### What actually happened?

```
Failed to create resource. The security token included in the request is invalid

Logs: /aws/lambda/eks-awscdkawseksClusterReso-OnEventHandler42BEBAE0-4QPUO1YX3M0U
```

```
Failed to delete resource. The security token included in the request is invalid

Logs: /aws/lambda/eks-awscdkawseksClusterRe-IsCompleteHandler7073F4D-ER83I62J68AJ
```

The stack deployment was aborted at this stage:

https://github.com/aws/aws-cdk/blob/77ce45d878f2d1cb453e36ae4d83228bee878ef1/packages/%40aws-cdk/aws-eks/lib/cluster.ts#L1007-L1030

### Environment

  - **CDK CLI Version  :** 1.94.1
  - **Framework Version:**
  - **Node.js Version:**  14.16.0
  - **OS               :** macOS BigSur 11.2.3(20D91)
  - **Language (Version):**  TypeScript 4.2.3

### Other

- [Managing AWS STS in an AWS Region](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_enable-regions.html)
- [Why did I receive the IAM error "AWS was not able to validate the provided access credentials" in some AWS Regions?](https://aws.amazon.com/premiumsupport/knowledge-center/iam-validate-access-credentials/)

--- 

This is :bug: Bug Report

**Comment by civilizeddev** [comment]
https://github.com/aws/aws-cdk/blob/77ce45d878f2d1cb453e36ae4d83228bee878ef1/packages/%40aws-cdk/aws-eks/lib/cluster-resource-handler/index.ts#L31

**Comment by civilizeddev** [comment]
In some AWS regions, such as `ap-east-1` and `me-south-1`,

aws-sdk and aws-cli behave differently when calling STS endpoints.

To fix this to do the same in all the regions,

lambda functions used in cluster-resource-provider in cdk should have an environment variable: 

- AWS_STS_REGIONAL_ENDPOINTS: regional

> https://github.com/aws/aws-cli/issues/4370#issuecomment-632314372

https://github.com/aws/aws-cdk/blob/77ce45d878f2d1cb453e36ae4d83228bee878ef1/packages/%40aws-cdk/aws-eks/lib/cluster-resource-provider.ts#L61-L70

https://github.com/aws/aws-cdk/blob/77ce45d878f2d1cb453e36ae4d83228bee878ef1/packages/%40aws-cdk/aws-eks/lib/cluster-resource-provider.ts#L71-L80

To be:

```
new lambda.Function(this, 'XXXHandler', {
  ...,
  environment: {
    ...props.environment,
    AWS_STS_REGIONAL_ENDPOINTS: 'regional'
  }
}
```

**Comment by iliapolo** [comment]
@civilizeddev Thanks for reporting this. 

You can workaround this issue for now by applying an aspect that injects that environment variable to all lambda functions associated with the cluster:

```ts
const cluster = new eks.Cluster(...)
cdk.Aspects.of(Stack.of(cluster)).add({
  visit: (node: cdk.IConstruct) => {
    if (node instanceof lambda.CfnFunction) {
      node.addPropertyOverride('Environment.Variables.AWS_STS_REGIONAL_ENDPOINTS', 'regional')
    }
  }
})
```

Another option, though less recommended, is [enabling global STS endpoints](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_enable-regions.html#sts-regions-manage-tokens) for all regions in your account. 

![Screen Shot 2021-03-25 at 4 00 17 PM](https://user-images.githubusercontent.com/1428812/112485192-53bc1780-8d83-11eb-88d6-94da27bdbd00.png)
