### ISSUE TITLE
Javascript NestedStack CREATE_FAILED when replicationRegions is specified

### ISSUE THREAD

**Issue by kirillfazliev** [aws/aws-cdk#13750]
I created stack:

```
class MyAmazonStack extends Stack {
    constructor(scope, id, props) {
        super(scope, id, props);
        const myNestedStack = new MyNestedStack(this, 'DynamoStack', region);

    }
}
```
And nested stack:

```
class MyNestedStack extends NestedStack {
    constructor(scope, id, NestedStackProps) {
        super(scope, id, NestedStackProps);
        const myReplicationTable = new Table(scope, `UsersReplication`, {
            partitionKey: { name: 'id', type: AttributeType.STRING },
            stream: StreamViewType.NEW_AND_OLD_IMAGES,
            serverSideEncryption: true,
            tableName: `UsersReplication`,
            //replicationRegions: ['eu-west-2'],
            removalPolicy: RemovalPolicy.DESTROY
        });
    }
}
```
When deploying, I get an error if i uncommend line:
```

//replicationRegions: ['eu-west-2'], 
Error:

| @aws-cdk--aws-dynamodb.ReplicaProvider.NestedStack/@aws-cdk--aws-dynamodb.ReplicaProvider.NestedStackResource (awscdkawsdynamodbReplicaProviderNestedStackawscdkawsdynamodbReplicaProviderNestedStackResource18E3F12D) Embedded stack arn:aws:cloudformation:us-west-2:*:stack/MyAmazonStack-awscdkawsdynamodbReplicaProviderNestedStackawscdkawsdynamodbReplicaProv-1WZGQXGZ06E76/94fa8740-8806-11eb-bdaa-06b06ae60541 was not successfully created: The following resource(s) failed to create: [Providerwaiterstatemachine5D4A9DF0].
        new NestedStack (C:\Work\amazon-iot\deploy\node_modules\@aws-cdk\core\lib\nested-stack.js:54:25)
        \_ new ReplicaProvider (C:\Work\amazon-iot\deploy\node_modules\@aws-cdk\aws-dynamodb\lib\replica-provider.js:11:9)
        \_ Function.getOrCreate (C:\Work\amazon-iot\deploy\node_modules\@aws-cdk\aws-dynamodb\lib\replica-provider.js:54:48)
        \_ Table.createReplicaTables (C:\Work\amazon-iot\deploy\node_modules\@aws-cdk\aws-dynamodb\lib\table.js:863:61)
        \_ new Table (C:\Work\amazon-iot\deploy\node_modules\@aws-cdk\aws-dynamodb\lib\table.js:487:18)
        \_ new MyNestedStack(C:\Work\amazon-iot\deploy\lib\MyNestedStack.js:16:39)
        \_ new AmazonIoTStack (C:\Work\amazon-iot\deploy\lib\AmazonIoTStack.js:57:35)
        \_ Object.<anonymous> (C:\Work\amazon-iot\deploy\bin\deploy.js:18:1)
        \_ Module._compile (internal/modules/cjs/loader.js:1063:30)
        \_ Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
        \_ Module.load (internal/modules/cjs/loader.js:928:32)
        \_ Function.Module._load (internal/modules/cjs/loader.js:769:14)
        \_ Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
        \_ internal/main/run_main_module.js:17:47
```
Tried various other regions and other stack and table's names. Nothing changes When I use the web interface, the table replica is created successfully. So i can't understand the problem. npx cdk version is 1.85.0 (build 5f44668)

**Comment by kirillfazliev** [comment]
> Can you look for the detailed error message in the nested stack (in the CF console)?

CF - Cloud Front? I cannot find more detailed information. Maybe I'm missing something

**Comment by jogold** [comment]
> CF - Cloud Front?

In the CloudFormation console, you can look for the events of your nested stack.

**Comment by kirillfazliev** [comment]
User: arn:aws:iam::*:user/TestUser is not authorized to perform: states:CreateStateMachine on resource: arn:aws:states:us-west-2:970950324796:stateMachine:Providerwaiterstatemachine5D4A9DF0-oiOKzqjGqYif (Service: AWSStepFunctions; Status Code: 400; Error Code: AccessDeniedException; Request ID: 56596551-7147-4866-a477-bf377a36c779; Proxy: null)

The following resource(s) failed to create: [Providerwaiterstatemachine5D4A9DF0].

**Comment by jogold** [comment]
It looks like the user deploying the stack doesn't have permissions to create a state machine. 

The replication provider uses a state machine for the custom resource implementation.

**Comment by kirillfazliev** [comment]
> It looks like the user deploying the stack doesn't have permissions to create a state machine.
> 
> The replication provider uses a state machine for the custom resource implementation.

Can you tell me, please, what exactly rights are needed?

**Comment by jogold** [comment]
> Can you tell me, please, what exactly rights are needed?

You need to add `states:CreateStateMachine`.

**Comment by kirillfazliev** [comment]
> > Can you tell me, please, what exactly rights are needed?
> 
> You need to add `states:CreateStateMachine`.

Thank you. It helps
