### ISSUE TITLE
RDS: DatabaseInstanceFromSnapshot usability concerns

### ISSUE THREAD

**Issue by finey** [aws/aws-cdk#13752]
DatabaseInstanceFromSnapshot does not allow unset engine or instanceType (which should default to the same as the snapshot) and the allocated storage is allowed to be empty but defaults to "100" instead of the allocated storage of the snapshot.

### Reproduction Steps

Here is my Java code:
```
DatabaseInstanceFromSnapshot dbInstance = DatabaseInstanceFromSnapshot.Builder.create(this, "Mysql")
					.instanceIdentifier("Mysql")
					.deleteAutomatedBackups(true)
					.snapshotIdentifier("production")
					.instanceType(new InstanceType("t3.large"))
					.allocatedStorage(500)
					.engine(DatabaseInstanceEngine.mysql(MySqlInstanceEngineProps.builder().version(MysqlEngineVersion.VER_5_7_31).build()))
					.subnetGroup(mysqlSubnetGroup)
					.securityGroups(Arrays.asList(mysqlSG))
					.removalPolicy(RemovalPolicy.DESTROY)
					.vpc(vpc)
					.build();
```

### What did you expect to happen?

I expected to not have to set instanceType, allocatedStorage and engine at all, and that it would quickly deploy an image of our production database.
### What actually happened?

I'm getting a deploy that spends an hour "Applying modification to allocated storage" on the RDS (although the allocated storage on the snapshot is also 500).

### Environment

  - **CDK CLI Version  : 1.91.0 (build 0f728ce)**
  - **Framework Version: Which framework??**
  - **Node.js Version: v10.19.0** 
  - **OS               : Unix**
  - **Language (Version): Java version "1.8.0_282"** 

### Other

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hey @finey,

thanks for opening the issue. Your description has a few dimensions, let's tackle them one by one 🙂.

#### 1. Engine is required

Yes. Unfortunately, it's required on the CloudFormation level. We can't really get the engine from the snapshot that exists only on the server side at build time - we would need something like a Custom Resource for this, and I don't think it's worth it.

#### 2. `InstanceType` is required

Actually, it is not! It is an optional property, and should default to an M5 Large [here](https://github.com/aws/aws-cdk/blob/5d6233164611d69ac1bf5c73e1518eb14dbace8d/packages/%40aws-cdk/aws-rds/lib/instance.ts#L845-L845).

#### 3. `allocatedStorage` is defaulted to `100`

Yep. This is unfortunate. We are tracking this in https://github.com/aws/aws-cdk/issues/12916.

----------------------------------------

Hope this clears this up!

Thanks,
Adam

**Comment by jogold** [comment]
> I'm getting a deploy that spends an hour "Applying modification to allocated storage" on the RDS (although the allocated storage on the snapshot is also 500).

Do you happen to change the storage type maybe? Snapshot is io1 and you're recreating with gp2, or standard and gp2, ...

**Comment by finey** [comment]
@skinny85 Thanks for the clarification. Maybe I have misunderstood, but I thought the instance type was specific for an RDS snapshot, so a new instance from snapshot could default to the instance type of the snapshot?

@jogold As it seems, I had not explicitly set the storage type to STANDARD, which we had in the snapshot.

I just assumed that since there is a separate class for instancing a database from snapshot (called DatabaseInstanceFromSnapshot), it exists solely for the purpose of inheriting all these attributes discussed above from the snapshot? As it seems to me right now, the only difference between DatabaseInstance and DatabaseInstanceFromSnapshot is that the latter contains a setter for the snapshot identifier and the former contains a setter for credentials?

**Comment by skinny85** [comment]
@finey hmm, I was under the impression that the snapshot did _not_ contain the info about what instance type it was used in...

Any way you can experiment, and see whether that's true or not?

**Comment by finey** [comment]
@skinny85 Maybe I'm just noob. I'm coming from a pretty pure Dev side, trying to do DevOps things. It's obvious I don't fully understand everything yet. But thank you so much for your support and help!

**Comment by skinny85** [comment]
@finey no worries, we're all learning here, as you can see 😊.

Let me know if you need any more help from our side for this issue!

Thanks,
Adam
