### ISSUE TITLE
(lambda): allow associating vpc to a function after initialization

### ISSUE THREAD

**Issue by pragmasoft-ua** [aws/aws-cdk#13757]
Refactor function.ts to make Function#configureVPC() method public

### Use Case

In my use case I have a serverless stack with a relatively large number of lambdas defined. I have a requirement to attach all lambdas in a stack to a VPC for security reasons. To avoid modifying each lambda definition, I decided to instead create an aspect, which attaches VPC to all existing lambdas. Unfortunately, currently VPC can be attached to a lambda only in constructor, particularly because configureVPC() method is private.

I managed to create an aspect, but I had to reverse engineer and reimplement the VPC configuration logic in it.

### Proposed Solution

Refactor function.ts to make Function#configureVPC() method public. This is not the only change required though, managed role creation should also be moved here, as well as special parameter type needs to be created. 

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by nija-at** [comment]
How many lambdas are we talking about? 
I'm curious how much effort would it be to update all the lambda functions in your app to use the `vpc` attribute?

**Comment by pragmasoft-ua** [comment]
It may be not that much, maybe about 30; the problem is that they're in different constructs - some of them are api gateway handlers and custom authorizers, some are listeners of infrastructure events, some are listeners of domain events, some are step function handlers. I wanted to reduce the coupling between these constructs and security related concerns, so I think aspect is a right choice here.

**Comment by nija-at** [comment]
Thanks. I've marking this a p2 feature request, which means we're unable to work on this immediately.

We are happy to take contributions if anyone is interested to pick this up and submit a PR (please make sure to follow our [contribution guidelines](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md))
