### ISSUE TITLE
@aws-cdk/aws-lambda-event-sources: Update the batch size and enable the batch window options

### ISSUE THREAD

**Issue by mckalexee** [aws/aws-cdk#13770]
### Use Case

The `SqsEventSource` in `@aws-cdk/aws-lambda-event-sources` allows for a `batchSize` between 1 and 10.

As of November 24, 2020 it is now possible to specify a batch size of up to 10,000, and a batching window of 5 minutes.

This is helpful to increase throughput and efficiency when using Lambda with SQS.

### Proposed Solution

The `SqsEventSource` should be modified to allow for these larger batch sizes and allow specifying a batching window.

```js
fn.addEventSource(
  new SqsEventSource(queue, {
    batchSize: 1000,
    maximumBatchingWindow: Duration.minutes(1)
  }),
);
```

### Other

Here's the announcement on the new changes:
https://aws.amazon.com/about-aws/whats-new/2020/11/aws-lambda-now-supports-batch-windows-of-up-to-5-minutes-for-functions/

Here is where this has been updated for AWS SAM:
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-sqs.html

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by nija-at** [comment]
This is currently in PR here - https://github.com/aws/aws-cdk/pull/13406
