### ISSUE TITLE
redshift: Storing database credentials in AWS Secrets Manager

### ISSUE THREAD

**Issue by erudisch** [aws/aws-cdk#13777]
Hello

I need to create a secret exactly this way:

[data-api-secrets](https://docs.aws.amazon.com/redshift/latest/mgmt/data-api.html#data-api-secrets)

My problem is that i'm not able to find any documentation on how to do it in cdk.

What i'm doing now is to create the redshift cluster:
```
const cluster = new redshift.Cluster(this, `DataWareHouse${stageName}`, {
    ...
});
```

And then try to create the secret:
```
const secret = new redshift.DatabaseSecret(this, 'RedshiftDataSecret', {
    username: 'user',
});
secret.attach(cluster);
```
But this results in a secret that looks like this:
<img width="1300" alt="wrong_key" src="https://user-images.githubusercontent.com/57360330/112388135-fb3d3980-8cf2-11eb-97ad-64f2823ba046.png">

What i need is a secret like this:
<img width="1270" alt="correct_key" src="https://user-images.githubusercontent.com/57360330/112388414-6a1a9280-8cf3-11eb-8539-8e1ee1b17513.png">

Help is much appreciated.

Thank you very much
Erik

---

This is a 📕 documentation issue

**Comment by njlynch** [comment]
@erudisch -

What you show as expected is what the redshift DatabaseSecret does by default. For example:

```ts
    new redshift.Cluster(this, 'Redshift', {
      masterUser: {
        masterUsername: 'admin',
      },
      vpc,
    });
```

The above will create a secret with the username of 'admin', and associate the dbname, engine, etc. with the secret, just as shown in your second screenshot.

If that's not the behavior you're seeing, perhaps you're on an older version of the CDK? What version(s) are you running? What behavior do you get with the above example?

**Comment by erudisch** [comment]
Thanks for your answer. after upgrading to the latest version i was able to use the generated secret from the cluster.

**Comment by grousseva** [comment]
@erudisch how were you able to get the password later from the generated secret from the cluster?

**Comment by grousseva** [comment]
@njlynch any chance you know how to access the secret in the same stack^? P
