### ISSUE TITLE
[MonoCDK] NetworkLoadBalancedFargateService deployment options

### ISSUE THREAD

**Issue by micahThor** [aws/aws-cdk#13773]
### The Question
Is there a difference between monocdk/* and aws-cdk/* modules/props?  Are all fields/attributes in aws-cdk props available to the monocdk version?

### Environment

  - **Module Version:** monocdk version: ^1.72.0"
  - **Language (Version):** TypeScript (3.8.3)

### Other information
Hello, our team is creating a Fargate service with CDK solutions.  We are using MonoCDK library constructs to accomplish this task, and I'm running into some issues between @monocdk library and @aws-cdk library.

When I'm creating our NetworkLoadBalancedFargateService, there are deployment options such as a circuitbreaker and maxHealthyPercent that I would like to include in our Fargate construct, but I do not have the auto-fill feature of IntelliJ picking up these fields.  As I understand it, monocdk includes all of the @aws-cdk/* modules, which means there is only a single dependency to manage.  With this in mind I'm unsure why the monocdk version of the NetworkLoadBalancedFargateService has different prop field options as the aws-cdk version?

NetworkLoadBalancedFargateService API: https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs-patterns.NetworkLoadBalancedFargateService.html

Any help is greatly appreciated!

Micah

**Comment by peterwoodworth** [comment]
Hey @micahThor, I apologize for the long response time here.

I've been unable to reproduce this, all of the props show up fine for me. How did you install monocdk and import the modules? Hopefully you've been able to figure this out in the meantime, if not, let me know 😄

**Comment by peterwoodworth** [comment]
Ping me if you still need help with this issue 😄
