### ISSUE TITLE
(aws-wafv2): there's no `LoggingConfiguration`, so it is impossible `logging` to Kinesis firehose

### ISSUE THREAD

**Issue by gsy0911** [aws/aws-cdk#13787]
Currently, there is no `LoggingConfiguration` in `aws-wafv2`.

### Use Case

To connect (or associate) to Kinesis firehose.

### Proposed Solution

create new class such as `CfnLoggingConfiguration`.

```
import * as wafv2 from '@aws-cdk/aws-wafv2';

const loggingConfiguration = wafv2.CfnLoggingConfiguration(scope, id, {
    webAclArn: string,
    firehoseArn: string
})
```

### Other

Though I found the reference about `LoggingConfiguration` in [here](https://docs.aws.amazon.com/ja_jp/waf/latest/APIReference/API_LoggingConfiguration.html),
`LoggingConfiguration` may not exist in `CloudFormation` ... ?

In addition, the code in [aws-wafv2.index.ts](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-wafv2/lib/index.ts) may reference the `CloudFormation` and may generate the CDK code, I think.

So, is it possible to add `CfnLoggingConfiguration` ?
I am concerned about difference between `CloudFormation` (i.e. origin source code) and `CDK` (i.e. generated source code).

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by njlynch** [comment]
Currently blocked on CloudFormation support. See https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/349

**Comment by gsy0911** [comment]
I see. Thanks for quoting!

**Comment by peterwoodworth** [comment]
As @phrastnik mentioned, this is supported now 🙂
