### ISSUE TITLE
(aws-eks): OpenIdConnectProvider does not work with Aspects

### ISSUE THREAD

**Issue by hangchan** [aws/aws-cdk#13783]
OpenIdConnectProvider does not work with Aspects.  We have an iam policy which requires a boundary policy to be applied to all created roles.  There doesn't seem to be a way to apply a boundary policy to the role that OpenIdConnectProvider creates.  Tags are also not added to the resources that are created.  The methods below works for all other resources in the stack

### Reproduction Steps
        
self.provider = self.eks_cluster.open_id_connect_provider
iam.PermissionsBoundary.of(self).apply(boundary)
core.Tags.of(self).add('app', 'eks')

### What did you expect to happen?

Have permission boundary and tags applied to the role and lambda created by the open_id_connect_provider custom resource.

### What actually happened?

No permission boundary policy or tags applied to the resources created.

### Environment

  - **CDK CLI Version  :** 1.9.1
  - **Framework Version:**
  - **Node.js Version:** v15.5.0
  - **OS               :** MacOS 10.14.6
  - **Language (Version):** Python 3.6.8
### Other

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment]
Blocked by https://github.com/aws/aws-cdk/issues/13850 and https://github.com/aws/aws-cdk/issues/13850

**Comment by otaviomacedo** [comment]
Resolved by https://github.com/aws/aws-cdk/pull/14754
