### ISSUE TITLE
(eks): Bottlerocket OS isn't available as one of the ami type when adding nodegroup to EKS cluster

### ISSUE THREAD

**Issue by VijoyChoyi** [aws/aws-cdk#13784]
When adding nodes to EKS cluster using 'add_nodegroup_capacity' there is no way to indicate AMI for Bottlerocket OS. The enum for NodegroupAmiType only contains AL2 flavors. So it's not possible to use this api call to add nodes that run Bottlerocket.

https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_eks/NodegroupAmiType.html#aws_cdk.aws_eks.NodegroupAmiType

### Reproduction Steps

I've tried using the below python code.

    def create_eks(self, vpc):
        # create eks cluster
        cluster = eks.Cluster(self, "EKS", vpc=vpc, version=eks.KubernetesVersion.V1_19,
                                default_capacity=0)

        # add bottlerocket/graviton2 nodegroup
        ng = cluster.add_nodegroup_capacity("graviton", desired_size=1,
                                instance_type=ec2.InstanceType("m6g.large"),
                                ami_type=NodegroupAmiType.???, // no option to indicate Bottlerocket type of ami
                                nodegroup_name="graviton")

### What did you expect to happen?
The api 'add_nodegroup_capacity' for Cluster object would allow the caller to provide the kind of OS either using the existing 'ami_type' input parameter or through some other input parameter.

I'm basically trying to create a EKS cluster and then add worker nodes that run Bottlerocket OS.

### What actually happened?

 In the add_nodegroup_capacity api, i would like to pass in the input that i need a Bottlerocket based AMI. But looking at the currently supported values for NodegroupAmiType enum to initialize 'ami_type' param, there isn't a way to indicate Bottlerocket as the OS for the ami. Also, depending upon the ec2 instance type, this enum needs to support the OS for different processor architectures like x86_64, ARM64, etc.

### Environment

  - **CDK CLI Version  : 1.94.1**
  - **Framework Version: 1.94.1** 
  - **Node.js Version: v15.12.0** 
  - **OS               : AL2**
  - **Language (Version): Python 3.7** 

### Other

--- 

This is :bug: Bug Report

**Comment by VijoyChoyi** [comment]
I just noticed in the below linked EKS issue it talks about allowing Bottlerocket as an AMI type option directly through the managed node groups API in EKS. So it sounds like the issue i logged here needs to be marked as a feature request instead of a bug.
https://github.com/aws/containers-roadmap/issues/950

**Comment by VijoyChoyi** [comment]
The issue i filed here is gated by EKS resolving their issue https://github.com/aws/containers-roadmap/issues/950. So i'll close this issue for now.

**Comment by gfina** [comment]
EKS fixed there issue, this is now a bug and should be opened.
