### ISSUE TITLE
aws_ec2: Unable to do change source_destination check value on the "instance"

### ISSUE THREAD

**Issue by rahejaps** [aws/aws-cdk#13791]
I have created an ec2 instance with 2 additional network interface cards.  I am trying to disable the source/destination check on all interface.   I have added "source_dest_check=False" in the main ec2 configuration and each of the additional interfaces I have created.  Based on the log, it is successful on 2nd and 3rd interface, however it fails on the primary interface. I am able to synthesize the code, however when I deploy, I get this error.
4/7 | 3:28:19 PM | UPDATE_COMPLETE      | AWS::EC2::NetworkInterface           | mgmtInt24PR
4/7 | 3:28:19 PM | UPDATE_COMPLETE      | AWS::EC2::NetworkInterface           | mgmtInt12PR
4/7 | 3:28:19 PM | UPDATE_COMPLETE      | AWS::EC2::NetworkInterface           | secInt12PR
4/7 | 3:28:19 PM | UPDATE_COMPLETE      | AWS::EC2::NetworkInterface           | secInt24PR
4/7 | 3:28:19 PM | UPDATE_FAILED        | AWS::EC2::Instance                   | server24PR012 (server243108) ****There are multiple interfaces attached to instance 'i-0fee'. Please specify an interface ID for the operation instead. (Service: AmazonEC2; Status Code: 400; Error Code: InvalidInstanceID; Request ID: a088-cbf20bbaa2c8; Proxy: null)****

Can someone provide a pointer as to fix this on the "instance"?  Here is my code for the instance.
```
serv = ec2.Instance(
            self,
            id= "server24PR012",
            instance_type = ec2.InstanceType(instance_type_identifier= inst_type), 
            instance_name = servname, 
            machine_image = ec2.MachineImage.generic_linux({region: linux_ami}),            
            vpc=vpc,
            key_name= key,
            role = role,
            vpc_subnets = vpc_priv_use1,
	    source_dest_check=False,
            security_group = security_group, 
    )

```
I have posted this on the Slack channel as well, however, have not received any hits.

**Comment by peterwoodworth** [comment]
Hey @rahejaps, sorry for the long response time.

Based on some quick googling, multiple sources tell me this is because you have `source_dest_check` specified on your instance. EC2 doesn't like it when this setting is specified on both your instance and your network interfaces
