### ISSUE TITLE
Rendering and deleting personal CDK in same AWS account deletes S3 event notification for already-deployed stack

### ISSUE THREAD

**Issue by phch** [aws/aws-cdk#13797]
Based on the logic here, if I delete a personal stack in the same AWS account as our development environment the logic will remove all S3 bucket notifications. We only want to remove the S3 notification for which we configured.

e.g. Personal stack in AWS Account A generates S3 event notification on bucket B. Bucket B has bucket notification from already-deployed stack for development environment. When I'm done testing my personal stack, I delete it but the code for deletion removes all the S3 event notifications from the bucket. It should only remove the one generated by my personal stack.

https://github.com/aws/aws-cdk/blob/25e8d04d7266a2642f11154750bef49a31b1892e/packages/%40aws-cdk/aws-s3/lib/notifications-resource/notifications-resource-handler.ts#L118

**Comment by phch** [comment]
```
              if (event.RequestType === 'Delete') {
                  props.NotificationConfiguration = {}; // this is how you clean out notifications
              }
```
This line should change to get the existing bucket configuration and remove the Lambda's input notification configuration to delete.

**Comment by iliapolo** [comment]
@phch This is a known limitation. Currently bucket notifications can only be used on buckets that are solely managed by the same CDK app. There is already an ongoing PR to enhance this and support externally managed buckets.

See https://github.com/aws/aws-cdk/pull/11773
