### ISSUE TITLE
(@aws-cdk/aws-datapipeline.CfnPipeline): Data Pipeline only supports 10 tags

### ISSUE THREAD

**Issue by yiantony** [aws/aws-cdk#13794]
The CfnPipeline component only supports up to 10 tags but other components support more than 10. That caused system inconsistency in building tags during the deployment process

### Reproduction Steps

The pipelineTags of CfnPipeline natively support only up to 10 tags

### What did you expect to happen?

It will support more than 10 tags (50) just like other components

### What actually happened?

Getting an error during deployment 'xxxxx at 'tags' failed to satisfy constraint: Member must have length less than or equal to 10 (Service: DataPipeline; Status Code: 400; Error Code: ValidationException;'

### Environment

  - **CDK CLI Version  : **1.94.1
  - **Framework Version: **1.94.1
  - **Node.js Version:**v12.17.0
  - **OS               :** 
  - **Language (Version):** Typescript 4.2.3
### Other
N/A

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment]
@yiantony The `CfnPipeline` is an [L1](https://docs.aws.amazon.com/cdk/latest/guide/constructs.html#constructs_l1_using) construct purely generated from the CloudFormation spec. 

Deployment failures related to it are most likely rooted either in CloudFormation or the service API itself. I suggest you refer to the [AWS Developer Forum](https://forums.aws.amazon.com/) as they will be better equipped to address this issue. 

Thanks
