### ISSUE TITLE
(DynamoDB): Existing table has stream enabled but CDK complains it does not...

### ISSUE THREAD

**Issue by dxunix** [aws/aws-cdk#13800]
### The Question

Looks like if a ddb table exists, and the ddb stream is enabled, using cdk is not able to create the trigger

```python
        table = dynamodb.Table.from_table_arn(self, 'SourceTable', table_arn)
        lambda_event_sources.DynamoEventSource(
            table=table,
            starting_position=_lambda.StartingPosition.LATEST
        ).bind(lambda_function)
```

But i got the following error, though the ddb stream on the table is enabled.
```
jsii.errors.JSIIError: DynamoDB Streams must be enabled on the table test-cdk/SourceTable
```

### Environment

  - **CDK CLI Version: 1.91.0 ** 
  - **Module Version: 1.94.1  ** 
  - **Node.js Version: 15.10.0 ** 
  - **OS: macOS ** 
  - **Language (Version): Python 3.8.3 **

**Comment by DaWyz** [comment]
@dxunix , the `from_*` methods are only creating a representation of the resource given the information you pass as argument. **It does not do a lookup of the current infra.**

In your case, you need to use the **from_table_attributes** and pass the `tableArn` & `tableStreamArn`. See [documentation here](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_dynamodb/Table.html#aws_cdk.aws_dynamodb.Table.from_table_attributes)

**Comment by RomainMuller** [comment]
@DaWyz got it all correct. The `from_table_arn` cannot be used to import a table with stream support (it's a convenience way to pass only the table ARN - which doesn't have much other information than the table name).
