### ISSUE TITLE
@aws-cdk/route-53 : Ability to create NS records

### ISSUE THREAD

**Issue by stijnbrouwers** [aws/aws-cdk#13816]
I would like to be able to create NS records for a hosted zone through CDK.

### Use Case
I want to manage all NS records for a hosted zone through CDK.

### Proposed Solution
Create a NsRecord in the @aws-cdk/route-53 lib to be able to deploy NS records in the same way as it's currently possible to manage: A records, TXT records, MX records, ...

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by njlynch** [comment]
Hi @stijnbrouwers ,

Thanks for the feature request. You can create NS records through the CDK today, via the `route53.RecordSet` construct, using the `route53.RecordType.NS` record type.

However, given that we have L2 constructs specifically for `ARecord`, `TxtRecord`, etc., I suppose it makes sense we could create an `NSRecord` as well. I wouldn't consider this a blocking/top priority, but would be willing to accept a pull request if you're interested in implementing it.

Thanks.

**Comment by stijnbrouwers** [comment]
Hi @njlynch ,

You can indeed assign the ticket to me, I'll implement it.

Kr

**Comment by njlynch** [comment]
Closed via #13895
