### ISSUE TITLE
(ec2): typo variable name "clientVpnEndoint"

### ISSUE THREAD

**Issue by do-su-0805** [aws/aws-cdk#13810]
### The Question

- i found wrong ~variable~ member name "clientVpnEndoint" in this PR [feat(ec2): client vpn endpoint by jogold · Pull Request #12234 · aws/aws-cdk](https://github.com/aws/aws-cdk/pull/12234). Correctly "clientVpnEndpoint"

### Environment

- **Module Version:** v1.95.0

### Other information

P.S. Probably here too https://github.com/aws/aws-cdk/pull/12234/files#diff-53d5a35c408bb5bcd8c3b8e135dbd00660447763e9003af414536ab603d4a25dR712. Correctly "addAuthorizationRule()"

**Comment by rix0rrr** [comment]
Great finds! If this is about released code, the proper solution would be to add a new member with the right name and add the `@deprecated` tag to the typo'ed members.

Mind submitting a PR for that?

**Comment by do-su-0805** [comment]
Thank you for your reaction and for telling me how to fix it.It was good. 
I'm sorry I just found it and haven't prepared a fix yet. Please submit the correction PR.

**Comment by do-su-0805** [comment]
Sorry, It seems that you misunderstood your intention.
Unfortunately, I have no time to deal with this issue temporarily. I'd like to ask you leave it opened or close this for now. I'll create a PR in the next month or so.

**Comment by BLasan** [comment]
@rix0rrr @do-su-0805 If you guys don't mind shall I send a PR for this?

**Comment by do-su-0805** [comment]
@BLasan Please by all means. I'm sorry I couldn't implement it.

**Comment by cokia** [comment]
I made a PR because this is not being solved.
I need a lot of feedback because this is my first contribution to this project
Thanks

**Comment by jumic** [comment]
@peterwoodworth Could you please close this issue? It was resolved by PR #14902. Thanks.
