### ISSUE TITLE
(custom-resources): Ability to remap output

### ISSUE THREAD

**Issue by ralovely** [aws/aws-cdk#13827]
When using CustomResource.AwsCustomResource, most often, `onCreate` and `onUpdate` will call different actions (ie, create-resource and describe-resource).
In some cases, the response of the two commands will have a different structure.
That makes using the output of both one and the other impossible.

### Use Case

A specific use case is for verifying an SES identity (actually an example in the doc).
`onCreate` calls `ses:verifyDomainIdentity`, but `onUpdate` (which would be called when the underlying lambda function is updated by a CDK upgrade, for instance), would need to use `ses:getIdentityVerificationAttributes`.

The former returns 
```
{
        "VerificationToken": "CuNgnXWHXaJ2dJayaWoGpzyjXPUcHlUi7k9jmjZHdi0="
}
```

the latter returns:

```
{
        "VerificationAttributes.myDomain.com.VerificationToken": "CuNgnXWHXaJ2dJayaWoGpzyjXPUcHlUi7k9jmjZHdi0="
}
```

If another construct needs to use that output, it would need to know the context (update or create) in order to know the path.

### Proposed Solution

Without going as far as reformatting the whole response, being able to remap part of it would go a long way.
The construct already has the `outputPath` parameter (which was designed to reduce the size of the output).
Maybe adding, say, an `outputKey` would be enough, ie:

```javascript
const verifySESDomainIdentity = new customresources.AwsCustomResource(this, 'VerifySESDomainIdentity', {
    onCreate: {
        service: 'SES',
        action: 'verifyDomainIdentity',
        parameters: {
            Domain: 'myDomain.com'
        },
        outputPath: 'VerificationToken',
        outputKey: 'myCustomKey'
        physicalResourceId: customresources.PhysicalResourceId.fromResponse('VerificationToken'),
    },
    onUpdate: {
        service: 'SES',
        action: 'getIdentityVerificationAttributes',
        parameters: {
            Identities: [ 'myDomain.com' ]
        },
        outputPath: 'VerificationAttributes.myDomain.com.VerificationToken',
        outputKey: 'myCustomKey'
        physicalResourceId: customresources.PhysicalResourceId.fromResponse('VerificationAttributes.myDomain.com.VerificationToken'),
    },
    // ...
})
```

which would output:

```json
{
    "myCustomKey": "CuNgnXWHXaJ2dJayaWoGpzyjXPUcHlUi7k9jmjZHdi0="
}
```

Does that make sense?

Thank you.

---

This is a :rocket: Feature Request

**Comment by jogold** [comment]
> which would be called when the underlying lambda function is updated by a CDK upgrade, for instance

If the underlying Lambda is updated the `onUpdate` will not be called. `onUpdate` only runs for CF updates of the custom resource, that is when its properties are updated.

That being said, I get how an output remap could be useful, can you think of another use case?

**Comment by ralovely** [comment]
Thank you, Jonathan.

I might have a specific setup, but twice I had the case where a pure CDK upgrade resulted in the custom resource running an `onUpdate` event (it might be because it has an explicit dependency on another custom resource, or the CDK upgrade introduced a difference in default parameters maybe).

Even though the AWS SDK/API are generally consistent, assuming that all the events of a same custom resource will have the same response structure is probably assuming too much (but I must admit, at this minute, my imagination fails to think of some other specific use cases 😀 ).
