### ISSUE TITLE
(aws-cdk CLI): Add a hook to run code between synthesize and deploy

### ISSUE THREAD

**Issue by TikiTDO** [aws/aws-cdk#13836]
Add a command that runs after the cloud assembly is synthesized, but before the the deploy runs when running `cdk deploy`.

### Use Case

I have a multi-stage pipeline deploy, and I would like to reproduce the full deployment process from the CLI. This would be much easier to accomplish if I could trigger a tasks in `cdk.out` after the stacks have been completely synthesized, but before they are be deployed to the server. 

In my CI environment these steps are managed by the pipeline eliminating the need for a `cdk deploy` command entirely. However I would like to have a similar behaviour locally for development and QA, which would be much easier if I had a hook at this stage.

### Proposed Solution

This can be added to `cdk.json` as an extra [context feature](https://github.com/aws/aws-cdk/blob/aa9fd9cd9bbaea4149927e08d57d29e547933f49/packages/@aws-cdk/cx-api/lib/features.ts), and and could be configured to run before [this loop](https://github.com/aws/aws-cdk/blob/aa9fd9cd9bbaea4149927e08d57d29e547933f49/packages/aws-cdk/lib/cdk-toolkit.ts#L133).

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
You can achieve this today by doing:

```
$ cdk synth
$ (whatever command you need)
$ cdk deploy -a cdk.out
```
