### ISSUE TITLE
(aws_elasticloadbalancingv2_targets): Listener switching target group between lambda and its alias causing failure in deployment (update fails and rollback fails)

### ISSUE THREAD

**Issue by dxunix** [aws/aws-cdk#13833]
## :question: General Issue

Listener switching target group between lambda and its alias causing failure in deployment. 

### The Question

We want to dynamically create the target group for a listener so we can switch between alias and lambda function as needed down the development stage.  Here is what we use

```python
        if provisioned_concurrent_executions > 0:
            listener.add_targets(
                f'{name}ALBListenerTarget',
                targets=[
                    elbv2_target.LambdaTarget(
                        self.lambda_suite.provisioned_alias)]
            )
        else:
            listener.add_targets(
                f'{name}ALBListenerTarget',
                targets=[
                    elbv2_target.LambdaTarget(
                        self.lambda_suite.lambda_function)]
            )
```

Here the `provisioned_alias` is created by
```python
        self.provisioned_alias = _lambda.Alias(
            self, "ProvisionedAlias",
            alias_name='provisioned-concurrency',
            description='provisioned concurrency alias',
            version=self.lambda_function.current_version,
            provisioned_concurrent_executions=provisioned_concurrent_executions,
            retry_attempts=retry_attempts
        )
```

what we notice is we deploy using lambda function as target, then we change it the alias,  or vice versa, the stack cannot be updated and failed with the following error:
please note the initial deployment is always successful, the error only happens if we want to switch the target.

```
6:15:13 PM | UPDATE_FAILED        | AWS::ElasticLoadBalancingV2::TargetGroup  | ****...istenerTargetGroup
ElasticLoadBalancerV2 TargetGroup did not stabilize.
```

Please suggest

### Environment

  - **CDK CLI Version:  1.95.1** 
  - **Module Version:1.95.1** 
  - **Node.js Version:v15.12.0** 
  - **OS: MacOS 10.15.7** 
  - **Language (Version): Python**

**Comment by peterwoodworth** [comment]
Hey @dxunix, sorry for the long reply here.

Could you post what the difference is in the synth output between the two possibilities here? Thanks

**Comment by peterwoodworth** [comment]
I was able to reproduce this, here's my `cdk diff`

```
[-] AWS::Lambda::Permission MyFnInvokeServicePrincipalelasticloadbalancingamazonawscomE3C04543 destroy
[+] AWS::Lambda::Permission MyAlias/InvokeServicePrincipal(elasticloadbalancing.amazonaws.com) MyAliasInvokeServicePrincipalelasticloadbalancingamazonawscom2FAA506F 
[~] AWS::ElasticLoadBalancingV2::TargetGroup Listener/FnTargetGroup ListenerFnTargetGroup80C6967F 
 ├─ [~] Targets
 │   └─ @@ -1,10 +1,7 @@
 │      [ ] [
 │      [ ]   {
 │      [ ]     "Id": {
 │      [-]       "Fn::GetAtt": [
 │      [-]         "MyFn6F8F742F",
 │      [-]         "Arn"
 │      [-]       ]
 │      [+]       "Ref": "MyAlias9A08CB8C"
 │      [ ]     }
 │      [ ]   }
 │      [ ] ]
 └─ [~] DependsOn
     └─ @@ -1,3 +1,3 @@
        [ ] [
        [-]   "MyFnInvokeServicePrincipalelasticloadbalancingamazonawscomE3C04543"
        [+]   "MyAliasInvokeServicePrincipalelasticloadbalancingamazonawscom2FAA506F"
        [ ] ]
```

According to [CloudFormation docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-targetgroup.html#cfn-elasticloadbalancingv2-targetgroup-targets), there should be no interruption when changing these properties.

@njlynch is this a problem on CloudFormation's end?
