### ISSUE TITLE
(ApplicationLoadBalancer): Workaround for loadBalancer.addListener() and listener.addTargets() for existing alb in ECS

### ISSUE THREAD

**Issue by zinaLacina** [aws/aws-cdk#13837]
https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_ecs/README.html#using-a-load-balancer-from-a-different-stack

We have an existing CDK project that has already created the Application load balancer, VPC, ...
I am putting in place a new CDK Global template to deploy our microservices in ECS and auto-register in an existing ALB. 

That new project has two stacks TaskDefintionStack and ServiceTask(Dynamic stack). 
Every new service to deploy will give as env variable the name of its stack, like that we can deploy multiple services with the same CDK project.

    _env = {'account': os.environ['CDK_DEFAULT_ACCOUNT'], 'region': os.environ['CDK_DEFAULT_REGION']}
    props = {}
    environment = os.getenv("ENVIRONMENT", "int")
    taskStackName = "{}-{}-task".format(environment, os.environ["SERVICE_NAME"])
    serviceStackName = "{}-{}-service".format(environment, os.environ["SERVICE_NAME"])
    
    task = PayiciTaskDefStack(app, taskStackName, props, env=_env)
    
    service = PayiciServiceStack(app, serviceStackName, task.outputs, env=_env)
    task.add_dependency(task)
    app.synth()

If the service is open to the world it has to register a rule to forward traffics to its target in the existing ALB listener.
Unfortunately, from the CDK documentation, it states that we can not call loadBalancer.addListener() and listener.addTargets().
https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_ecs/README.html#using-a-load-balancer-from-a-different-stack

    if props["need_alb"] == "True":  
        _alb = elbv2.ApplicationLoadBalancer.from_lookup(self,id="ALB",load_balancer_arn=props["load_balancer_arn"])  
        _listener = elbv2.ApplicationListener.from_lookup(self,id="albLiistener",listener_arn=props["listener_arn"],  listener_port=80)  
        if props["need_alb_ssl"] != "True":  
            # here port 80 check if port 80 listener exist  
    	  _target_group = _listener.add_targets("ECS1", port=80,  target=[_fargate_service]  )  
            _fargate_service.register_load_balancer_targets()  
      
       else:  
           # here port 443  
    	  _target_group = _listener.add_targets("ECS1",  port=443,  targets=[_fargate_service] )

My question is there a workaround? The workaround gave here does not work, or at least it works only for the first service registered. All new services fall into the issue I stated above.
https://github.com/aws-samples/aws-cdk-examples/tree/master/typescript/ecs/cross-stack-load-balancer

**Comment by njlynch** [comment]
Sorry for the delayed response here.

You said that the patterns mentioned in https://github.com/aws-samples/aws-cdk-examples/tree/master/typescript/ecs/cross-stack-load-balancer don't work for you. This is effectively just defining the Listener and/or TargetGroup yourself, to allow you to properly set the scope.

> .. or at least it works only for the first service registered. All new services fall into the issue I stated above.

Can you give a short example of what you're trying to do with multiple services, and more details on why it's not working? A short reproducible example would go a long way to helping me understand what issues you're running into.
