### ISSUE TITLE
ecr_assets: DockerImageAsset diff doesn't work with newStyleStackSynthesis

### ISSUE THREAD

**Issue by oaromeror** [aws/aws-cdk#13847]
If **_newStyleStackSynthesis_** is enabled in a CDK stack and the stack uses a DockerImageAsset, the diff-action is not able to identify any change in the _Dockerfile_ used to build the asset.

### Reproduction Steps

1. Create a new CDK project and enable `newStyleStackSynthesis` in `cdk.json` by adding `"@aws-cdk/core:newStyleStackSynthesis": true.`

2. Add a `DockerImageAsset` to the new stack as described in the documentation:

**Dockerfile:**

```dockerfile
FROM python:3.7.6-slim
```

**Stack:**

```py
aws_ecs.Cluster(self, 'FargateCluster', vpc=vpc)
asset = ecr_assets.DockerImageAsset(scope=self, directory="test/images", id="pythonImage")
image = aws_ecs.ContainerImage.from_docker_image_asset(asset=asset)
task_definition = aws_ecs.FargateTaskDefinition(self, id="FargateContainerTaskDefinition",
                                                execution_role=role, task_role=role, cpu=1024,
                                                memory_limit_mib=3072)
container = task_definition.add_container("Container", image=image)
```

3. Deploy the stack.

4. Modify the Dockerfile use to create the asset by adding any change:

**Dockerfile:**

```dockerfile
FROM python:3.7.6-slim
RUN apt-get update -y
```

5. Execute cdk diff

### What did you expect to happen?

The cdk diff-action must show the change in the asset:

```
        [-]       "/aws-cdk/assets:159221c1058e0842cfcc0829a7dd87628e0a14ed8b4fd842711677e0bdbc870e"
        [+]       "/aws-cdk/assets:f40362cdade509fa9a7ec383191eef545f0ce4c9361dd66b33e9ee259d8eb2c3"
```

### What actually happened?

The diff-action shows no differences

```
Stack TestStack
There were no differences
```

### Environment

  - **CDK CLI Version:** 1.91.0 (build 0f728ce)  /  Also tested in 1.94.1 (build 60d8f91) 
  - **Module Version:** 1.91.0
  - **Node.js Version:** v12.18.2
  - **OS:** Ubuntu 20.10
  - **Language (Version):** Python 3.8.6

### Other

The same test has been done with  **_newStyleStackSynthesis_** disabled and it works as expected.
We are not able to disable the _newStyleStackSynthesis_ because this change will recreate all deployed resources.

--- 

This is :bug: Bug Report

**Comment by eladb** [comment]
@peterwoodworth I am wondering if perhaps you can try to reproduce this

**Comment by peterwoodworth** [comment]
@eladb I wasn't able to reproduce this on the latest CDK build with Typescript

**Comment by peterwoodworth** [comment]
I'm unable to reproduce this on Python using CDK version 1.91.0. I have `newStyleStackSynthesis` enabled, and any changes I make to the Dockerfile are detected by `cdk diff`. 

The stack I have is *slightly* different than yours, but the slight changes I made shouldn't matter if the bug has to deal with `newStyleStackSynthesis` and detecting changes in the Dockerfile.

```py
vpc = aws_ec2.Vpc(scope=self, id="myvpc")
aws_ecs.Cluster(self, 'FargateCluster', vpc=vpc)
asset = ecr_assets.DockerImageAsset(scope=self, directory="test/images", id="pythonImage")
image = aws_ecs.ContainerImage.from_docker_image_asset(asset=asset)
task_definition = aws_ecs.FargateTaskDefinition(self, id="FargateContainerTaskDefinition",
                                                cpu=1024,
                                                memory_limit_mib=3072)
container = task_definition.add_container("Container", image=image)
```

**Comment by peterwoodworth** [comment]
@oaromeror I can't seem to reproduce this. Is it okay to close the issue?

**Comment by oaromeror** [comment]
Hi guys, let me test again. If it fails, I'll upload the project.

**Comment by peterwoodworth** [comment]
Ping me when ya do @oaromeror and I'll be happy to try and test it again

**Comment by oaromeror** [comment]
Hi @peterwoodworth, I tested again and the issue is not happening.
Thank you.
