### ISSUE TITLE
(aws-core): Get stack tree with dependencies

### ISSUE THREAD

**Issue by laimonassutkus** [aws/aws-cdk#13849]
### The Question

Is there a possibility to know which stack depends on which stacks? 

I mean, somehow AWS CDK knows the order in which stacks need to be deployed, also AWS CDK knows when there are circular dependencies in stacks, etc. So I assume AWS CDK knows the whole dependency tree and has an algorithm to determine which stacks to deploy.

So, back again to the original question - is there a possibility to know which stack depends on which stacks **OR** is there a possibility to get this dependency tree?

_WHAT I WANT TO ACHIEVE - is to create custom parallel deployment functionality that would allow deploying some of the stacks in parallel._

### Environment

The environment is not relevant.

**Comment by laimonassutkus** [comment]
I have already started building such functionality, which can be found here: 
https://github.com/Biomapas/B.AwsCdkParallel

But it is messy since I don't know the dependency tree.

**Comment by NetaNir** [comment]
The cloudAssembly scheme have all this information, see [dependencies](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/cloud-assembly-schema/schema/cloud-assembly.schema.json#L57)
