### ISSUE TITLE
(@aws-cdk/aws-ecs): Expose logdriver "mode" property for @aws-cdk/aws-ecs.AwsLogDriverProps

### ISSUE THREAD

**Issue by nicohartto** [aws/aws-cdk#13845]
Currently it is possible to change aws logdriver "mode" in CloudFormation https://docs.aws.amazon.com/AmazonECS/latest/developerguide/using_awslogs.html 

But _AwsLogDriverProps_ do not expose the property in CDK.

### Use Case

We have a performance need to deliver logs, but the ordering is not as relevant to us. Adjusting the mode to non-blocking would help. 

### Proposed Solution

Add "mode" as configurable option for _AwsLogDriverProps_ / reach parity with CloudFormation API.

### Other
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/using_awslogs.html 

This is a :rocket: Feature Request

**Comment by hassanazharkhan** [comment]
@SoManyHs Can I pick this up?

**Comment by SoManyHs** [comment]
@hassanazharkhan absolutely!! We'd love your contribution. I'll go ahead and assign you to this issue!

**Comment by Bio2hazard** [comment]
In case anyone is looking for a workaround while this feature is in progress:

It is possible to adjust this flag by falling back to the L1 Cfn resources.
Using a L3 `ApplicationLoadBalancedEc2Service` as an example:

```
const albEc2Service = new ecs_patterns.ApplicationLoadBalancedEc2Service(...);

let cfnTaskDefinition = albEc2Service.taskDefinition.node.defaultChild as ecs.CfnTaskDefinition;
cfnTaskDefinition.addPropertyOverride('ContainerDefinitions.0.LogConfiguration.Options', {
  'mode': 'non-blocking'
});
```

This can of course be used on anything that surfaces a L2 TaskDefinition. 👍
