### ISSUE TITLE
(aws-cdk/aws-s3-deployment): Directory deployment doesn't work

### ISSUE THREAD

**Issue by codenamestif** [aws/aws-cdk#13841]
Hello,

It looks like that `BucketDeployment` doesn't work for directories. I have an non-empty directory with some files which i want to deploy. When I deploy, i receive an error `Uploaded file must be a non-empty zip`. However the documentation states that source of the `BucketDeployment` can be a directory.

### Reproduction Steps

Create a resource similar to this one: 
```
        s3_deployment.BucketDeployment(
            self,
            "MyResource",
            sources=[s3_deployment.Source.asset("./mydir")],
            destination_bucket=workspace_bucket,
            destination_key_prefix="/mydir",
            vpc=vpc,
            vpc_subnets=ec2.SubnetSelection(subnets=vpc.private_subnets)
        )
```

where `mydir` is a non empty directory.

### What did you expect to happen?

`mydir` folder is synced with with destination folder.

### What actually happened?

I receive an error `Uploaded file must be a non-empty zip`

### Environment

  - **CDK CLI Version  :** 1.95.1
  - **Framework Version:** 1.95.1
  - **Node.js Version:** v15.12.0
  - **OS               :**  Mac OS 11.1
  - **Language (Version):** Python 3.9.2
--- 

This is :bug: Bug Report

**Comment by codenamestif** [comment]
One more note. I tried to zip my folder and provide a path to the zip file. And i still get the same error `Uploaded file must be a non-empty zip`. So basically `BucketDeployment` doesn't work at all.

**Comment by iliapolo** [comment]
@codenamestif I wasn't able to reproduce this. 

Can you double check you are using the CDK version you specified in the issue? We had this exact issue a few releases back and it was resolved: https://github.com/aws/aws-cdk/issues/12536

**Comment by codenamestif** [comment]
I confirm the versions. It's reproducible on my side. I even reproduced it with java lib. Since my cdk is installed with brew, i also tried to reinstall it with npm with no luck. As a next step i will try to deploy from a docker container.

**Comment by codenamestif** [comment]
@iliapolo i prepared a reproducible example https://github.com/codenamestif/s3-deployment-issue. You just need to provide credentials and destination bucket/key with env variables.

**Comment by codenamestif** [comment]
@iliapolo Thanks for the tip. I have cleaned up the bootstrap bucket and it works now. I'm closing the issue.
