### ISSUE TITLE
Referencing the AppSync URL with an instance of URL throws an error

### ISSUE THREAD

**Issue by owenashurst** [aws/aws-cdk#13852]
Referencing the automatically generated AppSync URL throws a `Invalid URL: ${Token[TOKEN.326]}` error.

### Reproduction Steps

1. Create an appsync resource.
2. Reference the graphql url with an instance of URL e.g. `new URL(graphqlApi.graphqlUrl);`

### What did you expect to happen?
For the URL to be parsed so you can use the properties from the URL instance.

### What actually happened?
Throws an error:
Invalid URL: ${Token[TOKEN.326]}

### Environment

  - **CDK CLI Version  :** 1.94.1 (build 60d8f91)
  - **Framework Version:** 1.94.1
  - **Node.js Version:** v14.16.0
  - **OS               :** Linux
  - **Language (Version):** TypeScript
--- 

This is :bug: Bug Report

**Comment by MrArnoldPalmer** [comment]
hey @owenashurst, most of the properties of constructs return as tokens. In this case the value isn't known until the stack is deployed and cloudformation creates the resource. If you need to do some string parsing of tokens for use elsewhere in your template, you can use the [cloudformation intrinsic functions](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.Fn.html). If you need to use this value in another application, like in a client of your api etc, you can export the value as a [cloudformation output](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html) or put it in a ssm parameter.

Check out the developer guide for more information about tokens https://docs.aws.amazon.com/cdk/latest/guide/tokens.html
