### ISSUE TITLE
aws-cdk/pipelines:   Pipeline stack which uses cross-environment actions must have an explicitly set region

### ISSUE THREAD

**Issue by mrpackethead** [aws/aws-cdk#13856]
I've run into an error that i just can't resolve, i've reduced the problem down to a minimum, where i can still reproduce it.

The error is
```
jsii.errors.JSIIError: Pipeline stack which uses cross-environment actions must have an explicitly set region
```

I am trying to add multiple stacks to a stage. The stacks are in different accounts...
I'm creating the stage.... and and adding it to my pipeline..

```
stage_env = core.Environment(
                account='111111222222',
                region='ap-southeast-2' 
            )
this_stage = PipelineStage(self, f'{stage_name}',
                env = stage_env,
                stage_stacks = stage_cfg['Stacks'],
                local_lookup_profile = pipeline_cfg['Pipeline']['LocalLookupProfile']
            ) 
self.pipeline.add_application_stage(
                app_stage = this_stage,
            )
```            
            
The Pipeline stage is configured like this..

```
class PipelineStage(cdk.Stage):
    def __init__(self, scope, id: str, *, env=None, outdir=None, stage_stacks: dict, local_lookup_profile: str, **kwargs):
        super().__init__(scope, id, env=env, outdir=outdir, **kwargs)
        print(self.region)
        print(self.account)
        Mystack= Stack(self, 'blahblah',
                        env = cdk.Environment(
                            account='1111113333333',
                            region='ap-southeast-2'
                        )
        )
```   
and the stack  ( which is just empty right now for the sake of testing.

```
class Stack(cdk.Stack):
    def __init__(self, scope: cdk.Stack, id: str, *, env=None,  **kwargs):
        super().__init__(scope, id, env=env,**kwargs)
```

when i cdk synth this.. i get the error above, but I'm confused, because i' have ( well i think i have ) set the environment for the stack....

I belive i'm 

### Environment

  - **CDK CLI Version:**     1.94.1 (build 60d8f91)
  - **OS:**    Amazon Linux 2
  - **Language (Version):**     Python 3.8.5

**Comment by mrpackethead** [comment]
When i call the Stack, without passing an env, it runs fine, but the Stack is deployed into the account that the stage is set up to.

**Comment by mrpackethead** [comment]
line 900 of https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-codepipeline/lib/pipeline.ts is what is raising the error.

**Comment by skinny85** [comment]
Hey @mrpackethead ,

can you show how do you create the Pipeline Stack?

Thanks,
Adam

**Comment by mrpackethead** [comment]
I was not passing env to my superclass...    This fixes it!  Simple bug, that i missed entirely.


class MultiStagePipeline(cdk.Stack):
    def __init__(self, scope: cdk.Construct, id: str, *,  pipeline_cfg: dict, prefix=None, env=None, **kwargs):
        super().__init__(scope, id, env=env)
