### ISSUE TITLE
(apigatewayv2): Allow to set Lambda authorizer for WebSocket API

### ISSUE THREAD

**Issue by tmokmss** [aws/aws-cdk#13869]
Please allow us to set a Lambda authorizer for a WebSocket API.
Currently we cannot set it because there's no interface for it.

### Use Case
Restrict access to a WebSocket API by cognito auth or other auth method.

### Proposed Solution
Setting an authorizer for a WebSocket API is simple.
You must only set `authorizationType` and `authorizerId` when creating a `CfnRoute` to `$connect`
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigatewayv2-route.html

Because you can only set authorizer for `$connect` route.

And there's only one authorizer type; LambdaAuthorizer.

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by nija-at** [comment]
We are unassigning and marking this issue as p2, which means that we are unable to work on this immediately.
We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. You can reach out to the cdk.dev community on Slack to solicit support for reprioritization.

**Comment by nija-at** [comment]
_Originally posted by @michaelgmcd in https://github.com/aws/aws-cdk/issues/14085#issuecomment-816853462_

I was able to get to to work with a patch:
```typescript
const wsApi = new WebSocketApi(stack, 'wsApi', {
    routeSelectionExpression: '$request.body.action',
    disconnectRouteOptions: {
      integration: new LambdaWebSocketIntegration({
        handler: lambdas.wsDisconnect,
      }),
    },
    defaultRouteOptions: {
      integration: new LambdaWebSocketIntegration({
        handler: lambdas.wsDefault,
      }),
    },
  });

  new WebSocketStage(stack, 'wsStage', {
    webSocketApi: wsApi,
    stageName: 'ws',
    autoDeploy: true,
    domainMapping: { domainName: wsDomainName },
  });

  const wsAuthorizer = new CfnAuthorizer(stack, 'WSAuthorizer', {
    name: 'wsAuthorizer',
    apiId: wsApi.apiId,
    authorizerType: 'REQUEST',
    authorizerUri: `arn:aws:apigateway:${constants.region}:lambda:path/2015-03-31/functions/${lambdas.wsAuth.functionArn}/invocations`,
    identitySource: ['route.request.querystring.token'],
  });

  wsApi.addRoute('$connect', {
    // @ts-ignore
    authorizerId: wsAuthorizer.ref,
    authorizationType: 'CUSTOM',
    integration: new LambdaWebSocketIntegration({
      handler: lambdas.wsConnect,
    }),
  });
```


node_modules/@aws-cdk/aws-apigatewayv2/lib/websocket/route.js
```javascript
class WebSocketRoute extends core_1.Resource {
    /**
     * @experimental
     */
    constructor(scope, id, props) {
        super(scope, id);
        this.webSocketApi = props.webSocketApi;
        this.routeKey = props.routeKey;
        const config = props.integration.bind({
            route: this,
            scope: this,
        });
        const integration = props.webSocketApi._addIntegration(this, config);
        const route = new apigatewayv2_generated_1.CfnRoute(this, 'Resource', {
            apiId: props.webSocketApi.apiId,
            routeKey: props.routeKey,
            target: `integrations/${integration.integrationId}`,
            authorizerId: props.authorizerId, // <========================== Added this
            authorizationType: props.authorizationType, // <=================== Added this
        });
        this.routeId = route.ref;
    }
}
```

**Comment by tmokmss** [comment]
Also there is a sample for adding Lambda authorizer to a WebSocket API written in TypeScript.
https://github.com/aws-samples/websocket-api-cognito-auth-sample/blob/main/cdk/lib/construct/websocket.ts

**Comment by wakeupmh** [comment]
@tmokmss  @nija-at Did u have an example using an user pool and authorizerType with cognito?

**Comment by tmokmss** [comment]
@wakeupmh 
Hi, here's an example for that. https://github.com/aws-samples/websocket-api-cognito-auth-sample/tree/main/cdk
