### ISSUE TITLE
(@aws-cdk/aws-cloudfront): Cannot create a distribution with a certificate. Type 'Certificate' is not assignable to type 'ICertificate'.

### ISSUE THREAD

**Issue by stringbeans** [aws/aws-cdk#13868]
I'm trying to create a Cloudfront distribution with an ACM certificate that I create previously in the stack and I get a Typescript error:

```
Type 'Certificate' is not assignable to type 'ICertificate'.
  The types of 'stack.tags' are incompatible between these types.
```

### Reproduction Steps

```
const myCertificate = new acm.Certificate(this, 'Cert', {
      domainName: '*.domain.com',
      validation: {
        method: acm.ValidationMethod.EMAIL,
        props: {}
      }
    })

...

new cloudfront.Distribution(this, 'ClientAssetsDist', {
      defaultBehavior: {
        origin: new origins.S3Origin(myS3Bucket)
      },
      domainNames: ['my.domain.com'],
      certificate: myCertificate
    })
```

### What did you expect to happen?

My certificate should be assignable to the `certificate` property

### What actually happened?

Typescript error as shown above!

### Environment

  - **CDK CLI Version  :** 1.95.1
  - **Framework Version:** 1.95.0
  - **Node.js Version:** 12.21.0
  - **OS               :** MacOS 10.14.6
  - **Language (Version):** TypeScript (3.9.9)

--- 

This is :bug: Bug Report

**Comment by njlynch** [comment]
The most likely cause of this is having mismatched versions of the cdk libraries (e.g., 1.95.0 for `@aws-cdk/aws-certificatemanager` and 1.95.1 for `@aws-cdk/aws-cloudfront`). 

Can you double-check all packages are on the same version, do a `npm ci` and see if that fixes it?

**Comment by blakeanator** [comment]
I have this same issue
