### ISSUE TITLE
AWS CodeBuild Code Coverage supporting clover.xml

### ISSUE THREAD

**Issue by xrzhuang** [aws/aws-cdk#13867]
I am using CDK to deploy a CodePipeline which then handles cross account deployments for my NodeJS Lambda. In the build stage of my CodePipeline, I would like to run unit tests and generate a code coverage report. I am using jest with the coverage flag which default creates a clover.xml for code coverage.

https://docs.aws.amazon.com/codebuild/latest/userguide/code-coverage-report.html says it supports clover.xml but I have been struggling to find a good example on how to do this, when I try to deploy my cdk pipeline stack with reports like this
```
          reports: {
            jest_reports: {
              files: ['reports/CodeCoverageReport.xml'],
              fileFormat: 'JUNITXML',
              baseDirectory: 'reports',
            },
            clover_reports: {
                files: ['reports/coverage/jest/clover.xml'],
                fileFormat: 'CLOVERXML',
                baseDirectory: 'reports',
            },
          },
```
I am getting this error:
```
[code_coverage_reports: [error processing report: [/codebuild/output/src245295669/src/reports/coverage/jest/clover.xml: expected element type <testsuite> but have <coverage>]]]
```

Is there any examples on how to do this or any advice on how to fix this?

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hey @xrzhuang ,

thanks for opening the issue. Looks like you're using the wrong keys. The CodeBuild documentation you linked to talks about the key being `file-format`, while you have it as `fileFormat`. That's probably the issue.

Thanks,
Adam

**Comment by skinny85** [comment]
Same for `baseDirectory` - should be `base-directory`: https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html#reports-buildspec-file

**Comment by xrzhuang** [comment]
think you may be wrong, because the `jest_reports` actually works just fine. My cdk is in javascript whereas the example seems like yml to me.

**Comment by xrzhuang** [comment]
lmao i cant even compile it in skewer case

**Comment by skinny85** [comment]
It doesn't matter whether it's JavaScript, or YAML. The key is the key.

**Comment by skinny85** [comment]
`jest_reports` is an arbitrary name that you choose. You can put whatever in there, it's not part of the schema.

**Comment by xrzhuang** [comment]
the `jest_reports` works like it finds the directory is what i'm saying

**Comment by skinny85** [comment]
Are you sure the file format for `CodeCoverageReport.xml` should be `JUNITXML`? Shouldn't it something related to code coverage?

**Comment by skinny85** [comment]
Also, I'm pretty sure you're specifying the `reports` directory twice.

**Comment by xrzhuang** [comment]
regarding CodeCoverageReport.xml. It is `JUNITXML`. Sorry for the confusion, I misnamed it. Using this from the original snippet:
```
          reports: {
            jest_reports: {
              files: ['reports/CodeCoverageReport.xml'],
              fileFormat: 'JUNITXML',
              baseDirectory: 'reports',
          },
```

the `jest_reports` works fine.

What do you mean I am specifying the reports directory twice?

**Comment by xrzhuang** [comment]
So I updated the redundant reports directory which appears to have fixed the error in `jest_reports` but it seems to me that `clover_reports` still isn't working and the error looks to be about the same from the original post.  

Code:
```
          reports: {
            jest_reports: {
              files: ['CodeCoverageReport.xml'],
              'file-format' : 'JUNITXML',
              'base-directory' : 'reports',
            },
            clover_reports: {
              files: ['coverage/jest/clover.xml'],
              'file-format' : 'CLOVERXML',
              'base-directory' : 'reports',
            }
          },
```

Error:

```
Error in UPLOAD_ARTIFACTS phase: [clover_reports: [error creating report: InvalidInputException: Report group type doesn't match expected report type, report group type is TEST, but report type is CODE_COVERAGE]]
```

**Comment by xrzhuang** [comment]
alrighty thanks

**Comment by skinny85** [comment]
NP, good luck!

**Comment by xrzhuang** [comment]
Commenting the fix here for visibility in case anyone else runs into this. What happens is the incorrect version in my original post created the report group `clover_reports` as a `TEST` report type. This is because the keys were incorrect and the default is `JUNITXML`. The code snippet here: https://github.com/aws/aws-cdk/issues/13867#issuecomment-810555222 is correct, all I had to do was delete the incorrectly created report group. Alternatively, one could simply rename the report group to something else.

**Comment by skinny85** [comment]
Thanks for the follow up @xrzhuang!
