### ISSUE TITLE
(aws-cdk/core): CfnOutput doesn't print anything from inside of the nested stack

### ISSUE THREAD

**Issue by codenamestif** [aws/aws-cdk#13870]
`CfnOutput` doesn't print anything if it's placed inside of the `NestedStack`. As soon as I move to the main Stack, it starts working again.

### Reproduction Steps

Create a `Stack` with `NestedStack` inside. Place a `CfnOutput` inside of the `NestedStack`.

### What did you expect to happen?

I expect to see an output.

### What actually happened?

Nothing happens.

### Environment

  - **CDK CLI Version  :** 1.95.1
  - **Framework Version:** 1.95.1
  - **Node.js Version:** 15.12.0
  - **OS               :** Mac OS 11.1
  - **Language (Version):** Python 3.9.2

--- 

This is :bug: Bug Report

**Comment by codenamestif** [comment]
One more small note. When I open cloudformation and then nested stack, there is `Outputs` tab. And my output is actually there. However I would expect to see the output in **terminal** as it happens when the `CfnOutput` is placed inside of the main stack.

**Comment by rix0rrr** [comment]
This is working as intended.

`CfnOutput` is not a mechanism to print things to your console. It's a mechanism to add Outputs to CloudFormation stacks.

The top-level stack's Outputs HAPPEN to be printed, for convenience. Add your Output to the top-level stack if you need to see it.
