### ISSUE TITLE
(aws-eks/aws-ec2): Subnet tagging removed from kubernetes 1.19 and CDK does not allow tagging existing subnets

### ISSUE THREAD

**Issue by adriantaut** [aws/aws-cdk#13879]
There is a very known intended limitation in CDK that does not allow you to tag existing VPC subnets, so wondering if someone found a way of doing this already, or if offering this functionality is something that might be even taken into consideration.

### Use Case

The main use case we found so far is around the automation for provisioning EKS Clusters as a Service for our internal customers. The EKS Clusters are deployed in already-existing VPCs, and there are a bunch of Tags required by EKS for provisioning ELBs (https://docs.aws.amazon.com/eks/latest/userguide/network_reqs.html):
* `kubernetes.io/role/internal-elb: 1` & `kubernetes.io/role/elb: 1`
* `kubernetes.io/cluster/<cluster-name>: shared/owned` - Tag that is not applied anymore starting with `v1.19` of kubernetes

While we managed to deal with the first "static" set of tags (elb/internal-elb) by adding the tags while creating the VPC itself, the same cannot be applied with the latter one since the `<cluster-name>` it's a dynamic field. This prevents our users to create ELBs without manual intervention for every new cluster being deployed, degradating both the user experience and the "everything-as-a-code" paradigm we are trying to follow.

### Proposed Solution

Not exactly sure how the solution should look like, I think it depends both on the CDK Capabilities and eventually the AWS position in regards to the decision of disabling the auto-tagging starting with `v1.19`. 

Could someone advise if this is something it can be addressed from CDK or if there exists a workaround for this limitation?

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by adriantaut** [comment]
it looks like the AWS Load Balancer Controller has all the mechanisms in place for not needing those tags: https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1905 , but we had some interferences between clusters.

so I guess we can close this now. Not sure if other similar requests for tagging subnets will come in the near future 🤷‍♂️ .

**Comment by joehillen** [comment]
I created a custom resource to work around this issue:

```typescript
import { createHash } from 'crypto';

import * as cdk from '@aws-cdk/core';
import * as lambda from '@aws-cdk/aws-lambda';
import {
  AwsCustomResource,
  AwsCustomResourcePolicy,
  AwsSdkCall,
  PhysicalResourceId,
} from '@aws-cdk/custom-resources';
import * as iam from '@aws-cdk/aws-iam';

import { BaseResource } from './base-resource';

interface TaggerProps {
  arns: string[];
  tags: { [key: string]: string };
  physicalResourceId?: PhysicalResourceId;
}

/**
 * This construct is to work around the limitation with CDK where it's not able
 * to add tags to external existing resources, so we'll do it using a lambda instead.
 */
export class EC2Tagger extends BaseResource {
  constructor(scope: cdk.Construct, id: string, props: TaggerProps) {
    super(scope, id);

    const tags = Object.entries(props.tags).map(([key, value]) => ({
      Key: key,
      Value: value,
    }));

    const parameters = {
      Resources: props.arns.map((arn) => cdk.Arn.parse(arn).resourceName).filter(Boolean),
      Tags: tags,
    };

    const hash = createHash('sha256').update(JSON.stringify(parameters)).digest('hex');

    const sdkCall: AwsSdkCall = {
      service: 'EC2',
      action: 'createTags',
      parameters,
      physicalResourceId: PhysicalResourceId.of(hash),
    };

    const func = new AwsCustomResource(this, 'CustomResource', {
      onCreate: sdkCall,
      onUpdate: sdkCall,
      onDelete: {
        ...sdkCall,
        action: 'deleteTags',
      },
      policy: AwsCustomResourcePolicy.fromSdkCalls({
        resources: props.arns,
      }),
    });
  }
}
```

**Usage:**
```typescript
    new EC2Tagger(this, 'PrivateSubnetK8sRoleTags', {
      arns: this.vpc.privateSubnets.map(subnetArn),
      tags: {
        'kubernetes.io/role/internal-elb': '1',
      },
    });
```
