### ISSUE TITLE
(aws-efs): RemovalPolicy.Snapshot does nothing?

### ISSUE THREAD

**Issue by w-** [aws/aws-cdk#13876]
In my stack I create a `FileSystem`  with `removalPolicy: RemovalPolicy.SNAPSHOT`

https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.RemovalPolicy.html
the docs say:
> This retention policy deletes the resource, but saves a snapshot of its data before deleting, so that it can be re-created later.

having destroyed my stack and recreated it several times, I cannot see any snapshots in AWS Backup or S3. Where are these snapshots?

### Reproduction Steps

```
const fileSystem = new FileSystem(this, 'my-EFS', {
            vpc,
            lifecyclePolicy: LifecyclePolicy.AFTER_30_DAYS,
            performanceMode: PerformanceMode.GENERAL_PURPOSE,
            throughputMode: ThroughputMode.BURSTING,
            removalPolicy: cdk.RemovalPolicy.SNAPSHOT,
        })
```

### What did you expect to happen?

when stack deleted, I expect a snapshot i can restore from

### What actually happened?

no snapshot found

### Environment

  - **CDK CLI Version  :** 1.95.1 (build ed2bbe6)
  - **Framework Version:** 1.95.1 (build ed2bbe6)
  - **Node.js Version:** <v12.21.0
  - **OS               :** ubuntu 20 LTS
  - **Language (Version):** Typescript 4.2.3

### Other

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment]
@NGL321 I think the issue here is that EFS simply doesn't support snapshots. Can you follow up and verify?

**Comment by peterwoodworth** [comment]
Eli is correct here. EFS doesn't support snapshots, so this won't work. Sorry about that!
