### ISSUE TITLE
(lambda-nodejs): non-deterministic runtime version

### ISSUE THREAD

**Issue by zxkane** [aws/aws-cdk#13893]
## :question: General Issue

The mutation default runtime of nodejs lambda looks like not a good practice.  

https://github.com/aws/aws-cdk/blob/df5c133312cef3f40374488973361ca9ef3303f7/packages/%40aws-cdk/aws-lambda-nodejs/lib/function.ts#L33-L40

Assuming a `NodejsFunction` lambda with default runtime, the unit test will fail if the CI uses matrix nodejs versions, such as `12.x`, `14.x`.

### Environment

  - **CDK CLI Version:**  1.95.1
  - **Module Version:** 
  - **Node.js Version:**  12.x / 14.x
  - **OS:** 
  - **Language (Version):**

**Comment by eladb** [comment]
I totally agree. Defaults should be completely deterministic. I think we should use nodejs 12.x as the default. @jogold can you please pick this up?

**Comment by jogold** [comment]
> I think we should use nodejs 12.x

Why not nodejs 14.x which is the current LTS?

**Comment by eladb** [comment]
I am okay with node 12 as well.
