### ISSUE TITLE
aws-elasticloadbalancingv2: can not remove/update listeners

### ISSUE THREAD

**Issue by rafaelmarques7** [aws/aws-cdk#13901]
Hello all.
My team currently has a stack that, among other things, is composed of an application load balancer, with a number of listeners and target groups. More recently, we tried to update the stack as to remove some of those listeners, but **removing an application load-balancer listener does not seem possible given my setup.**

Upon removing some of the listeners, CDK, or Cloudformation, threw an error saying:
```
Listener port '${PORT_NUMBER}' is already in use (Service: ElasticLoadBalancingV2, Status Code: 400, Request ID: ${REQUEST_ID}, Extended Request ID: null)
```

So, why/how did this happen?
Please read below for more details, and for a workaround I found - which is unfortunately not ideal.

### Reproduction Steps

The way our code is setup is as follows.

1) We have a PORT_MAP variable, which is a list of objects, each object containing the information necessary to setup a listener. Example:
```ts
const accessMap = {
  vpn: {
    cidr: process.env.CIDR_VPN,
    description: 'VPN',
  },
  workspace: {
    cidr: process.env.CIDR_WORKSPACES,
    description: 'Workspaces',
  },
};

const openToHTTPList = [accessMap.vpn];
const openToHTTPSList = [accessMap.vpn];
const openToSSHList = [accessMap.vpn, accessMap.workspace];

export const PORT_MAP: ISecurityGroupPortMap[] = [
    { externalPort: 22, internalPort: 22, openTo: openToSSHList },
    { externalPort: 80, internalPort: 80, openTo: openToHTTPList },
    { externalPort: 443, internalPort: 80, openTo: openToHTTPSList, sslCertificateId: SSL_CERTIFICATE_ARN},
];
```

2) We then create an application load-balancer
```ts
    const applicationLoadBalancer = new ApplicationLoadBalancer(this, 'alb', {
      vpc,
      internetFacing: false,
      securityGroup: sgLb,
      loadBalancerName: `${RESOURCES_PREFIX}-lb-cuefront`,
    });
```

3) We iterate over the PORT_MAP variable, and add a listener (and a SG rule) for each port 
```ts
    PORT_MAP.forEach((port: ISecurityGroupPortMap, index) => {
        applicationLoadBalancer.addListener(`listener-${index}`, {
          port: port.externalPort,
          certificates,
          protocol:
            port.externalPort === 443
              ? ApplicationProtocol.HTTPS
              : ApplicationProtocol.HTTP,
          defaultTargetGroups: [targetGroup],
          open: false,
        });
      });
      
        // <-- THE CODE BELOW IS NOT RELEVANT FOR THE BUG IN QUESTION -->
        // Update load balancer security group to be open on the right ports to the right sources
        port.openTo.forEach((openTo: ICidr, j) => {
          let peer;

          if (openTo.cidr) {
            peer = Peer.ipv4(openTo.cidr);
          } else if (openTo.securityGroupId) {
            peer = SecurityGroup.fromLookup(this, `sg-${index}-${j}`, openTo.securityGroupId);
          } else {
            throw Error('CIDR or SecurityGroup ID required for Ingress Rule');
          }

          sgLb.addIngressRule(
            peer,
            new Port({
              protocol: Protocol.TCP,
              fromPort: port.externalPort,
              stringRepresentation: '',
              toPort: port.externalPort,
            }),
            openTo.description,
          );
        });
```

### What did you expect to happen?

Now, let's say I remove one of the port mappings, for example, I remove the mapping regarding port 22:
```ts
export const PORT_MAP: ISecurityGroupPortMap[] = [
    //  { externalPort: 22, internalPort: 22, openTo: [] }, // this has been commented out to remove it from the stack
    { externalPort: 80, internalPort: 80, openTo: openToHTTPList },
    { externalPort: 443, internalPort: 80, openTo: openToHTTPSList, sslCertificateId: SSL_CERTIFICATE_ARN},
];
```

If I try to update the stack, I would expect that
1) the listener for port 22 is removed
2) the listeners for port 80 and port 443 work as expected, without any changes

### What actually happened?

When we update the port mappings, instead of removing the listener that was dropped from the mapping (22), CDK/Cloudformation complains that the listener on ports 80 and 443 already exist.

What I believe is happening is:
1) The mapping of port 22 is removed, and, becaue of this, the forEach loop starts on the next item of the PORT_MAP, the one with port 80
2) The forEach loop tried to `addListener` for port 80, but **it can not do this, because a listener on port 80 already exists in the stack**

For the same reason, if we, instead of removing a listener from the PORT_MAP, were to shuffle the order of the mappings, a similar error would have been thrown.

Now, it might be worth noting that I did NOT find a workaround for removing the listener.

However, my main goal was to update the security groups associated to the ALB, to make them more restrictive, and I was able to do this with a tricky workaround that is not ideal in my opinion. 

My workaround to keep the listener, but restrict the security group, was to keep the original port mappings - as the stack was created - but do not allow any traffic to it. Using port 22 again as an example:

```ts
export const PORT_MAP: ISecurityGroupPortMap[] = [
    { externalPort: 22, internalPort: 22, openTo: [] }, // keep mapping but do not open to anything
    { externalPort: 80, internalPort: 80, openTo: openToHTTPList },
    { externalPort: 443, internalPort: 80, openTo: openToHTTPSList, sslCertificateId: SSL_CERTIFICATE_ARN},
];
```

With the above mapping, and the code described above, I would keep the ALB listener, but the SG would have been restricted, and no errors would be thrown.

### Environment

  - **CDK CLI Version  :** 1.75
  - **Framework Version:**
  - **Node.js Version:**  v14.13.1
  - **OS               :** Mac OS X
  - **Language (Version):**  Typescript 3.7.3

### Other

I hope this bug report makes sense, and if there's anything I can do to help clarify this, please let me know. Thank you!

--- 

This is :bug: Bug Report

**Comment by njlynch** [comment]
Thanks for the detailed write-up!

I think what's happening here is related to the way you're creating the IDs of the listeners:

> ```ts
>     PORT_MAP.forEach((port: ISecurityGroupPortMap, index) => {
>         applicationLoadBalancer.addListener(`listener-${index}`, {
>           port: port.externalPort,
> ```

This means your port 22 listener is `listener-0`, your port 80 is `listener-1`, and port 443 is `listener-2`. When you remove your port 22 listener, port 80 becomes `listener-0` and port 443 becomes `listener-1`. Those logical IDs are how the CDK (and CloudFormation) identify resources and determine what updates/changes to make.

If you look at the `cdk diff` output of your broken version (just removing the 22 port entry from the PORT_MAP), you'll see that `listener-0` is being changed from a port 22 listener to a port 80 listener. As CloudFormation tries to process that change, it fails due to an existing port 80 listener (`listener-1`) already existing.

I'd recommend you label these listeners in another way (e.g., port number, hard-coded ID) to avoid this kind of index-ID shifting from happening in the future.

I think that should resolve this; let us know if there's anything else!
