### ISSUE TITLE
(aws-cdk): allow user to set ClientRequestToken when calling deployStack

### ISSUE THREAD

**Issue by rossng** [aws/aws-cdk#13902]
I am using CDK to deploy CloudFormation stacks programmatically, using something like this:

```ts
const cloudFormation = new CloudFormationDeployments({ sdkProvider });
return cloudFormation.deployStack({ stack });
```

I would like to be able to set CloudFormation's `ClientRequestToken` property for the stack.

### Use Case

I am using CDK to deploy media processing stacks (MediaLive + MediaPackage + CloudFront) at runtime. I trigger the deployment, then wait for notifications to come back from the CloudFormation stack via SNS. When the stack fires its `CREATE_COMPLETE` event, I gather details of what has been constructed and store it in a database.

However, it is not especially easy to figure out which 'job' those SNS events pertain to. As far as I can tell, it isn't possible to get the `PhysicalResourceId` or Arn of the stack, because you have to wait for `deployStack` to complete and return a `DeployStackResult`. I want to be resilient to my microservice restarting, so I need to be able to persist a unique ID for the stack *before* calling `deployStack` rather than after.

For now, I've settled on choosing a unique `LogicalResourceID` for the CloudFormation stack and keeping track of that. But it seems like the `ClientRequestToken` would be much more suitable - were it accessible through the CDK.

### Proposed Solution

I think it would be possible to add a `clientRequestToken?: string` field to the `DeployStackOptions`.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
You are using an unsupported API here.

A more supported way would be to synth the application to disk and calling CloudFormation yourself. 

If you feel like adding this to the CLI code yourself, I wouldn't be opposed to it... but again be aware that there aren't any contracts or guarantees on that API.

Closing because this is not something we'll work on.

**Comment by rossng** [comment]
@rix0rrr is there any chance of this becoming a supported API in the future? Who should I direct my request at?

**Comment by rix0rrr** [comment]
https://github.com/aws/aws-cdk-rfcs/issues/300
