### ISSUE TITLE
(ec2): CDK replaces EC2 instances without any diff

### ISSUE THREAD

**Issue by akefirad** [aws/aws-cdk#13925]
### The Question
Every time I try to deploy my stack (which includes a some EC2 instances, for example a bastion, an auto-scaling-group), before deploying, I check the `diff`. And it says "There were no differences". However when I proceed with `deploy`, it replaces all of the instances, even if the code is not changed at all since the last deployment.
I'm not sure why it happens, sometimes it does (for example when I upgrade CDK, or even without upgrade!), sometimes it doesn't. My questions are:
1. Why is this happening? Is it something with my code or something with CDK or CFN?
2. How can I prevent this from happening?
3. If it's not possible to stop this, how can I know in advance that this's gonna happen?

### Environment

  - **CDK CLI Version:** 1.94.1 (build 60d8f91) // this is not specific to this version!
  - **Module Version:** 1.94.1 // this is not specific to this version!
  - **Node.js Version:** v15.5.1
  - **OS:** macOS 11.2.3 build 20D91
  - **Language (Version):** TypeScript (3.8.3)

**Comment by rix0rrr** [comment]
Because the default [machineImage](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ec2.BastionHostLinux.html#machineimagespan-classapi-icon-api-icon-experimental-titlethis-api-element-is-experimental-it-may-change-without-noticespan) property for BastionHost says:

> An Amazon Linux 2 image which is kept up-to-date automatically (the instance may be replaced on every deployment) and already has SSM Agent installed.

`MachineImage.lookup()` will find you an AMI that doesn't auto-update.

**Comment by akefirad** [comment]
Thanks @rix0rrr. Just to be sure, is this applicable to auto scaling groups as well?
