### ISSUE TITLE
(aws-dynamodb): Add Table.streamToEventBridge() method

### ISSUE THREAD

**Issue by alan-cooney** [aws/aws-cdk#13926]
Add a `table.streamToEventBridge()` method to the Dynamo DB `Table` class, making it quick and easy to add this common pattern.

### Use Case

 - It's very common to want to stream DynamoDB records to EventBridge, as a way of enabling asynchronous communication between (micro)services.
 - Dynamo DB streams have a soft limit of 2 listeners - when you want to have many more than this it's very common to stream to an Event Bus and then add multiple listeners there.

At my company we use these patterns on over half of our tables - I understand this is quite typical.

### Proposed Solution

I propose we add a method to the DynamoDB table that works like this:

```
table.streamToEventBridge({
  eventBus: eventBus, // Optional - default to account event bus
  detailTypePrefix: "User", // Prefix for the event DetailType, which will be suffixed with the event type e.g. Create
  deadLetterQueue: true // Optional 
})
```

This would work very much like https://github.com/amazon-archives/aws-dynamodb-stream-eventbridge-fanout , with:

- A lambda that listens to the DynamoDB stream and pushes the events to Event Bridge (using an environmental variable to set the detailTypePrefix)
- A dead letter que if required for failed events

---

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by RomainMuller** [comment]
While I'm not entirely against this feature, it sounds like this involves a bit of a contraption that will effectively be abstracted away here:

> This would work very much like https://github.com/amazon-archives/aws-dynamodb-stream-eventbridge-fanout , with:
>
>- A lambda that listens to the DynamoDB stream and pushes the events to Event Bridge (using an environmental variable to set the detailTypePrefix)
>- A dead letter que if required for failed events

The proposed API makes it look like it's a native DynamoDB feature (which it is not)... I wonder if there are other considerations to take into account... For example, is it guaranteed the Lambda function can scale up high enough to actually match the DynamoDB table's event throughput?

---

At this stage I'd be more favorable to either have an "integration" construct in the EventBridge library; or even as a third-party construct (very much as it was in the archived repository you pointed out)...

Obviously, I'm open to reconsider this position if this feature request gathers sufficient interest...

**Comment by alan-cooney** [comment]
Thanks @RomainMuller - makes sense if you'd prefer to make it not look like native functionality. 

I'll create it as a third-party node module instead (the scaling issues can all be resolved with batching).
