### ISSUE TITLE
CloudWatch Log Exports property not available for class DatabaseCluster(Amazon Document DB)

### ISSUE THREAD

**Issue by ManojkumarAlaguduraiEmis** [aws/aws-cdk#13927]
We should be able to enable the cloud watch logs for "audit or profiler" using cdk, but at the moment, there is no support for cloud watch log exports or cloud watch log retention in DatabaseCluster class for amazon document DB. But, this feature is available in DatabaseCluster class for RDS.

### Use Case

We should be able to enable or disable cloud watch logs for amazon documentDB using CDK. 

https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-docdb.DatabaseCluster.html

### Proposed Solution

Be able to set Cloudwatch logs exports with EnableCloudwatchLogsExports prop similar to DatabaseCluster class for RDS.

https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-rds.DatabaseCluster.html

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by peterwoodworth** [comment]
Sorry for the slow response here @ManojkumarAlaguduraiEmis 

I don't see why this functionality couldn't be somewhat easily copied over from the RDS DBCluster construct, as CloudFormation allows for the same [input for DocDb](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-docdb-dbcluster.html#cfn-docdb-dbcluster-enablecloudwatchlogsexports) as [RDS](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbcluster.html#cfn-rds-dbcluster-enablecloudwatchlogsexports)

I'm marking this as a p2, which means we can't get to it immediately. however I'd love to review a PR for this addition if you would like to submit one.
