### ISSUE TITLE
(kinesis): KMS key should automatically be modified to allow use through Kinesis

### ISSUE THREAD

**Issue by S3ky** [aws/aws-cdk#13931]
Lambda CloudWatch logs are not delivered to Lambda's subscription filter destination (in our case Kinesis destination) when the Kinesis stream (in our case error stream) is encrypted with a custom managed KMS key. 

PS: Without the encryption it DOES work.

### Reproduction Steps

```python
kms_key = aws_kms.Key(self.stack, "kms-key",
                  alias=self.kms_key, enable_key_rotation=True,
                  removal_policy=core.RemovalPolicy.DESTROY, 
                  trust_account_identities=True)

kms_key.grant_encrypt(aws_iam.ServicePrincipal("cloudtrail.amazonaws.com"))  

error_stream = aws_kinesis.Stream(self.stack, scope,
                                  stream_name=error_stream,
                                  encryption=aws_kinesis.StreamEncryption.KMS,
                                  encryption_key=kms_key)
   
fn = aws_lambda.Function(scope, id,
                             code=code,
                             runtime=aws_lambda.Runtime.PYTHON_3_8,
                             handler=handler,
                             function_name=name,
                             environment=environment,
                             timeout=timeout,
                             memory_size=memory
                             )
log_group = aws_logs.LogGroup(scope, f'log-{id}',
                                  log_group_name='/aws/lambda/' + fn.function_name,
                                  retention=aws_logs.RetentionDays.FIVE_DAYS,
                                  removal_policy=core.RemovalPolicy.DESTROY)
kms_key.grant_encrypt_decrypt(fn.role)

lmb_log_group.add_subscription_filter(f'{id}-log-subscription',
                                          filter_pattern=aws_logs.FilterPattern().literal("-START -END -REPORT"),
                                          destination=aws_logs_destinations.KinesisDestination(stream=error_stream))
```

Execute Lambda and wait for logs delivered to the Kinesis error_stream - they shouldn't arrive

### What did you expect to happen?

Lambda's logs will be delivered via log subscription filter to the Kinesis error_stream

### What actually happened?

Logs weren't delivered to the Kinesis error stream

### Environment

  - **CDK CLI Version  :*1.92.0*
  - **Framework Version:*Python 3.9.2*
  - **Node.js Version:*v15.11.0* 
  - **OS               :*macOS Catalina 10.15.7*
  - **Language (Version):*Python 3.9.2*

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
The key would probably benefit from having a "grant encrypt to *" with condition [ViaService: logs.$REGION.amazonaws.com](https://docs.aws.amazon.com/kms/latest/developerguide/policy-conditions.html#conditions-kms-via-service) on it.

**Comment by rix0rrr** [comment]
It's unclear where this should go in the CDK. The key policy should probably be modified as soon as it's being used in the Kinesis stream.
