### ISSUE TITLE
(aws-lambda): cannot deploy DockerImageFunction

### ISSUE THREAD

**Issue by hermes-z** [aws/aws-cdk#13932]
When I try to deploy a simple DockerImageFunction using the default parameters, I get an error related to code signing not being supported.

### Reproduction Steps

```
test_function = lambda_.DockerImageFunction(
    self,
    "TestLambda",
    code=lambda_.DockerImageCode.from_ecr(
        repository=ecr.Repository.from_repository_name(
            self,
            “TestEcr",
            repository_name=“test",
        ),
        tag=“0.0.1",
    ),
)
```

### What did you expect to happen?

A new Lambda is deployed.

### What actually happened?

```
Resource handler returned message: "Code signing is not supported for functions created with container images. (Service: Lambda, Status Code: 400,
Request ID: 901461c4-b094-4b22-bf87-fc3d4cdb3b67, Extended Request ID: null)" (RequestToken: fc7310cc-6c90-a01c-78da-a422c2c2848b, HandlerErrorCod
e: InvalidRequest)
```

### Environment

  - **CDK CLI Version  :** 1.95.2
  - **aws-cdk.core:** 1.96.0
  - **aws-cdk.aws-lambda:** 1.96.0
  - **Node.js Version:** v14.15.5
  - **OS               :** macOS Catalina Version v14.15.5
  - **Language (Version):** Python 3.8.2

### Other

The change happened overnight. It was working one day and the next one not, without any change in the environment. Also, when I manually create a Lambda from the console using the same Iamge, it works.

--- 

This is :bug: Bug Report

**Comment by andreaschiappacasse** [comment]
I am experiencing the same problem. Same code used to work until today and no updates were applied to my environment.

**Environment**
CDK CLI Version : 1.87.1 (build 9eeaa93)
aws-cdk.core: 1.87.1
aws-cdk.aws-lambda: 1.78.0
Node.js Version: v14.15.1
OS : Windows 10
Language (Version): Python 3.8.5

**Comment by luca-ferreri** [comment]
I'm having the same issue.

**Environment**
CDK CLI Version : 1.96.0
aws-cdk.core: 1.96.0
aws-cdk.aws-lambda: 1.96.0
Node.js Version: v14.15.4
OS : Windows 10
Language (Version): Python 3.8.5

**Comment by FloWi** [comment]
Thanks for opening the issue. I have the same problem. Worked on Thursday and now it's broken :-( I guess it's aws' way of telling us to not work over the easter-holidays ;-)

**Comment by FloWi** [comment]
Any update on that, @nija-at? I checked the synthesised output of cdk and it didn't show anything regarding code signing. Looks to me like a bug in cloudformation that can hopefully rolled back easily.

**Comment by hermes-z** [comment]
> Any update on that, @nija-at? I checked the synthesised output of cdk and it didn't show anything regarding code signing. Looks to me like a bug in cloudformation that can hopefully rolled back easily.

I tried deploying again this morning, and it worked. I guess what you describe is what happened.

**Comment by FloWi** [comment]
> I tried deploying again this morning, and it worked. I guess what you describe is what happened.

That's great news. Thanks for the update, @hermes-z. Can confirm that deployment worked in eu-central-1.

**Comment by nija-at** [comment]
Since this seems to have been resolved, marking this as 'closing soon'.
Let us know if the issue still persists.
