### ISSUE TITLE
(aws-synthetics): Add support for Playwright based Canaries?..

### ISSUE THREAD

**Issue by busticated** [aws/aws-cdk#13949]
hey there :wave:

i'm very much enjoying AWS Synthetics Canaries here. One request: I'd love to be able to run Canaries built on top of `playwright` - https://github.com/microsoft/playwright | https://playwright.dev

### Use Case

Ability to run tests under browsers other than Chrome / Chromium (e.g. Firefox)

### Proposed Solution

support and expose the `playwright` library within the Canary runtime environment in addition to or in place of `puppeteer`.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by NetaNir** [comment]
I think this is a feature request for AWS synthetics.

**Comment by busticated** [comment]
>I think this is a feature request for AWS synthetics.

it is! is that not this? 👉  https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/aws-synthetics

**Comment by NetaNir** [comment]
This is the AWS CDK construct built on top of the service (in this case, AWS synthetics). If the capability does not exist on the service and in its's CloudFormation resource, then it cannot be provisioned via the CDK. See the service docs: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Synthetics_Canaries.html

**Comment by busticated** [comment]
well, fwiw i guess 👍
