### ISSUE TITLE
Automatically synthesize a dedicated template for security-related resources (IAM, security groups)

### ISSUE THREAD

**Issue by arnghosh** [aws/aws-cdk#13941]
Security Groups and IAM roles created or updated, as a part of CDK can affect overall security posture of an application, so certain organizations might need to have the changes reviewed before deploying. The complexity of this review process can be reduced, if a dedicated Cloudformation template is generated for these (Security Groups and IAM constructs like User/Roles etc) resources in addition to the main cloudformation template. This is dedicated Cloudformation template can then be reviewed and approved before initiating the main deployment.

### Use Case
This feature is required for easy integration with existing review processes in an organization that is using CDK for deployment of infrastructure.

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
I'm not sure we can do this. The ordering is going to be tricky when setting up least-privilege permissions.

The policies are going to need to refer to resources that are going to get created AFTER all the roles have been created.

A mechanism like Permissions Boundaries or another mechanism that will only create permissions the DevOps group have explicitly approved will be better--separate stacks are probably not the way.

This needs an RFC going into the details of how this would be implemented.
