### ISSUE TITLE
(aws-codepipeline): dynamic bucket content fails in CodePipeline

### ISSUE THREAD

**Issue by warden** [aws/aws-cdk#13940]
When a BucketDeployment is used together with a CodePipeline definition, it fails because of not providing dynamic parameter definitions. Check the code below:

```typescript
import { Bucket } from "@aws-cdk/aws-s3";
import { BucketDeployment, Source } from "@aws-cdk/aws-s3-deployment";
import * as cdk from "@aws-cdk/core";
import { Construct, Fn, Stack } from "@aws-cdk/core";

export class TestStack extends Stack {
  constructor(scope: Construct, id: string) {
    super(scope, id);

    const athenaOutputBucketArn = Fn.importValue("foqBucketArn");
    const athenaOutputBucket = Bucket.fromBucketArn(
      this,
      "athenaOutputBucket",
      athenaOutputBucketArn
    );

    //Scripts deployment
    new BucketDeployment(this, "EtlScriptsDeployment", {
      sources: [Source.asset("etl")],
      destinationBucket: athenaOutputBucket,
      destinationKeyPrefix: "foq-etl-scripts",
    });
  }
}

const app = new cdk.App();
new TestStack(app, "test-stack");

```

That code runs fine when it is run locally via `code deploy`.

However, what we are doing, is that we have a CodePipeline that does:
- `cdk synth` 
- archives the CF artifact from `cdk.out/*.json`
- in the later stages it takes that artifact and applies the JSON manifest with some additional CustomParameters.

In that scenario, the above code does not work, because the JSON template contains this:
```
  "Parameters": {
    "AssetParameterse9882ab123687399f934da0d45effe675ecc8ce13b40cb946f3e1d6141fe8d68S3BucketAEADE8C7": {
      "Type": "String",
      "Description": "S3 bucket for asset \"e9882ab123687399f934da0d45effe675ecc8ce13b40cb946f3e1d6141fe8d68\""
    },
    "AssetParameterse9882ab123687399f934da0d45effe675ecc8ce13b40cb946f3e1d6141fe8d68S3VersionKeyE415415F": {
      "Type": "String",
      "Description": "S3 key for asset version \"e9882ab123687399f934da0d45effe675ecc8ce13b40cb946f3e1d6141fe8d68\""
    },
    "AssetParameterse9882ab123687399f934da0d45effe675ecc8ce13b40cb946f3e1d6141fe8d68ArtifactHashD9A515C3": {
      "Type": "String",
      "Description": "Artifact hash for asset \"e9882ab123687399f934da0d45effe675ecc8ce13b40cb946f3e1d6141fe8d68\""
    },
    "AssetParametersc24b999656e4fe6c609c31bae56a1cf4717a405619c3aa6ba1bc686b8c2c86cfS3Bucket55EFA30C": {
      "Type": "String",
      "Description": "S3 bucket for asset \"c24b999656e4fe6c609c31bae56a1cf4717a405619c3aa6ba1bc686b8c2c86cf\""
    },
    "AssetParametersc24b999656e4fe6c609c31bae56a1cf4717a405619c3aa6ba1bc686b8c2c86cfS3VersionKey60329B70": {
      "Type": "String",
      "Description": "S3 key for asset version \"c24b999656e4fe6c609c31bae56a1cf4717a405619c3aa6ba1bc686b8c2c86cf\""
    },
    "AssetParametersc24b999656e4fe6c609c31bae56a1cf4717a405619c3aa6ba1bc686b8c2c86cfArtifactHash85F58E48": {
      "Type": "String",
      "Description": "Artifact hash for asset \"c24b999656e4fe6c609c31bae56a1cf4717a405619c3aa6ba1bc686b8c2c86cf\""
    },
    "AssetParameters5ef945e6e08a251616e0809dcfabf96a7c4d48567feea30b940107fe69cecb90S3Bucket901C920F": {
      "Type": "String",
      "Description": "S3 bucket for asset \"5ef945e6e08a251616e0809dcfabf96a7c4d48567feea30b940107fe69cecb90\""
    },
    "AssetParameters5ef945e6e08a251616e0809dcfabf96a7c4d48567feea30b940107fe69cecb90S3VersionKey970C036B": {
      "Type": "String",
      "Description": "S3 key for asset version \"5ef945e6e08a251616e0809dcfabf96a7c4d48567feea30b940107fe69cecb90\""
    },
    "AssetParameters5ef945e6e08a251616e0809dcfabf96a7c4d48567feea30b940107fe69cecb90ArtifactHashB56BC137": {
      "Type": "String",
      "Description": "Artifact hash for asset \"5ef945e6e08a251616e0809dcfabf96a7c4d48567feea30b940107fe69cecb90\""
    }
  },
```

and the pipeline bails out because the parameters were not provided. (in the CLI via `cdk deploy` I am **guessing** they come from `manifest.json` that we are not archiving as an artefact - I did not find any documentation on this...)

Is this an unsupported scenario, bug or we are doing something wrong in the pipeline?

### Environment

  - **CDK CLI Version  :** 1.95.2
  - **Framework Version:** 1.86.0
  - **Node.js Version:** Node 12.20.0
  - **Language (Version):** TypeScript ~4.1.3

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hi @warden,

thanks for opening the issue. Those parameters are in the template because the `BucketDeployment` class uses [CDK Assets](https://docs.aws.amazon.com/cdk/latest/guide/assets.html) for the code of the Custom Resource that implements the actual deployment.

If you want to deploy a Stack like that through CodePipeline, I would suggest using the [CDK Pipelines](https://docs.aws.amazon.com/cdk/api/latest/docs/pipelines-readme.html) module, that does handle deploying Assets.

Thanks,
Adam

**Comment by warden** [comment]
Thanks @skinny85 for a quick answer. Indeed, we are using CDK Pipelines and this is the stage that is failing:

```
this.pipeline.addStage({
      stageName: "Integration-Deployment",
      actions: [
        new codepipelineActions.CloudFormationCreateUpdateStackAction({
          runOrder: 1,
          actionName: "ChangesDeployment",
          stackName: this.stackNameToDeploy,
          adminPermissions: false,
          parameterOverrides: {
            s3LambdaLayerCodeBucketName: lambdaLayerBuildArtifact.bucketName,
            s3LambdaLayerCodeBucketKey: lambdaLayerBuildArtifact.objectKey
          },
          extraInputs: [lambdaBuildArtifact, lambdaLayerBuildArtifact],
          templatePath: pipelineCdkStageConstruct.cdkBuildArtifact.atPath(
            `${templatePath}`
          ),
          capabilities: [
            cfn.CloudFormationCapabilities.NAMED_IAM,
            cfn.CloudFormationCapabilities.AUTO_EXPAND
          ]
        })
      ]
    });
```

because the template generated contains the custom parameters.

I thought since this works locally, it would also generate a working CDK template for pipeline deployment (this looks very similar to https://github.com/aws/aws-cdk/issues/4928 and https://github.com/aws/aws-cdk/pull/3437/files).
If I read you correct, this scenario is not supported in the pipeline directly and a separate (artefact producing) intermediate stage needs to be added by design, just like we do with the LambdaLayer parameters?

It would be great to see that somehow from TypeScript type/CDK documentation if this is not supported, although I understand that this might be hard, because the CDK template might be anything and is just a JSON that is just passed to the pipeline stage..

**Comment by skinny85** [comment]
I believe you missed an important step in working with CDK Pipelines, and that is enabling the feature flag for new-style synthesis. See documentation here: https://docs.aws.amazon.com/cdk/api/latest/docs/pipelines-readme.html#cdk-versioning

Thanks,
Adam

**Comment by peterwoodworth** [comment]
@warden did the above advice help you out?
