### ISSUE TITLE
(aws-cdk): `cdk context --refresh` command

### ISSUE THREAD

**Issue by TikiTDO** [aws/aws-cdk#13943]
Add a `hasMissingContext` function to the `Stack` construct.

### Use Case

Often if a Stack has yet to fetch it's context I don't want or need to do CPU intensive synth operations, since they will be re-run anyway once the context is available. 

The ability to query the Stack to check if there are missing context values would help ensure that I don't run these expensive operations until the context is available

### Proposed Solution

Add:

```ts
/**
  * Returns true if the current stack has missing context entries.
  */
public get hasMissingContext(): boolean {
  return this._missingContext.length !== 0;
}
```

to [this file](https://github.com/aws/aws-cdk/blob/88f2c5ac302145f0b56462943a72e2b133c70bdf/packages/%40aws-cdk/core/lib/stack.ts#L151).

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
Feels like there should be a better way to achieve what you plan to do. In what cases specifically would you call this method?

**Comment by TikiTDO** [comment]
@rix0rrr I have a root-level stack which pulls in a whole bunch of context variables (`ssm.StringParameter.valueFromLookup`,  `ec2.Vpc.fromLookup`, `elasticloadbalancingv2.ApplicationLoadBalancer.fromLookup`,  `s3.Bucket.fromBucketName`, `lambda.Version.fromVersionArn`, `cloudfront.OriginAccessIdentity.fromOriginAccessIdentityName`) with some context variables dependent on each other. These values are then used by a nested stack. 

Some of these nested stacks then process and upload some assets using [asset bundling options](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.BundlingOptions.html). The net result is that my bundling code runs multiple times until all the context variables resolve, which can increase the runtime quite significantly.

To facilitate this use case I would call this method in the code that processes the context. If I find that there is a missing context value then I could skip the nested stacks entirely until the next loop when all the values those stacks need are available. This would allow me to configure my CI environment to re-fetch the context on every run, which is necessary to pick up changes to the environment. 

As an alternative, if the context system could automatically detect changes to context variables and re-run when a value changes, then that would hit 95% of my normal use cases. I then would be able to swallow the extra runtime for the remaining 5% of builds.

I'm certainly open to other approaches, but I haven't been able to find anything better in my search thus far.

**Comment by rix0rrr** [comment]
> if the context system could automatically detect changes to context variables and re-run when a value changes, then that would hit 95% of my normal use cases.

Ha! In fact it has been designed to do the opposite, and stay the same UNLESS you manually refresh it (keeping in mind things like AMIs, AZs etc which you wouldn't want to have change out from under you).

But I like this idea, actually.

I think a `cdk context --refresh [WILDCARD]` command would not be out of order.
