### ISSUE TITLE
!! NOTICE Empty java init template

### ISSUE THREAD

**Issue by earthling-amzn** [aws/aws-cdk#13964]
Please add your +1 👍 to let us know you have encountered this
---

### Overview:
A [recent change to the init templates](https://github.com/aws/aws-cdk/commit/b9407102304f043adcd9a4fc1cde4d23d3da9004) caused the application emitted by default java init template to not instantiate the stack class correctly. This results in `cdk synth` emitting an empty template.

#### Complete Error Message:
No error emitted, result is an empty stack.

### Workaround:
Change the call to the builder of the generated stack to a call to the class constructor instead.

example:
change
```java
MyAppStack.Builder.create(app, "MyAppStack")
                .build();
```
to
```java
new MyAppStack(app, "MyAppStack")
```

### Solution:
Remove the attempted usage of the nested builder classes in the init template output and replace with call to stack constructor.

### Related Issues:

Original Issue
----
After running `cdk init --language java`, the generated `App` doesn't use the generated `Stack`.

### Reproduction Steps
```
$ mkdir cdk-init-broken && cd cdk-init-broken
$ cdk init --language java
# Setup a stack in CdkInitBrokenStack.java
$ cdk synth
# Stack is empty
```
### What did you expect to happen?
Expected my stack to be rendered into cloud formation templates.

### What actually happened?
Generated an empty stack.

### Environment

  - **CDK CLI Version  :** 1.96.0
  - **Framework Version:** 1.96.0
  - **Node.js Version:** v10.19.0
  - **OS               :** Ubuntu 20.04
  - **Language (Version):** Java

### Other
Replaced generated `App` code with code from examples and it worked great:
```java
public class CdkInitBrokenApp {
    public static void main(final String[] args) {
        App app = new App();

        new CdkInitBrokenStack(app, "CdkInitBrokenStack");

        app.synth();
    }
}
```

--- 

This is :bug: Bug Report

**Comment by NetaNir** [comment]
executing `cdk init -l java` creates the below main:

```java
    public static void main(final String[] args) {
        App app = new App();

        JavainitStack.Builder.create(app, "JavainitStack").build(); // stack 
        app.synth();
    }
```

Can you try again?

**Comment by earthling-amzn** [comment]
That's similar to the code I see generated for the `App` (less a few comments). The trouble is, that code doesn't actually invoke the constructor of the generated `JavainitStack`, so you end up with an empty Cfn template.

```java
public class JavainitStack extends Stack {
    public JavainitStack(final Construct scope, final String id) {
        this(scope, id, null);
    }

    public JavainitStack(final Construct scope, final String id, final StackProps props) {
        super(scope, id, props);
        // This code from the lambda cron example in aws-cdk-examples is never called.
        SingletonFunction lambdaFunction =
          SingletonFunction.Builder.create(this, "cdk-lambda-cron")
            .description("Lambda which prints \"I'm running\"")
            .code(Code.fromInline("def main(event, context):\n" + "    print(\"I'm running!\")\n"))
            .handler("index.main")
            .timeout(Duration.seconds(300))
            .runtime(Runtime.PYTHON_2_7)
            .uuid(UUID.randomUUID().toString())
            .build();

        Rule rule =
          Rule.Builder.create(this, "cdk-lambda-cron-rule")
            .description("Run every day at 6PM UTC")
            .schedule(Schedule.expression("cron(0 18 ? * MON-FRI *)"))
            .build();

       rule.addTarget(new LambdaFunction(lambdaFunction));
    }
}
```

**Comment by hombyk-nevzi2-dAxzyd** [comment]
60K

**Comment by NetaNir** [comment]
Related: https://github.com/aws/aws-cdk/commit/b9407102304f043adcd9a4fc1cde4d23d3da9004
