### ISSUE TITLE
bootstrap s3 bucket: add lifecycle policy option

### ISSUE THREAD

**Issue by kjpgit** [aws/aws-cdk#13968]
I looked at the bootstrap template and am unsure if it's safe to add a lifecycle policy to the staging s3 bucket to delete objects after 7 days or even 1 day.
https://github.com/aws/aws-cdk/blob/master/packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml

It would be helpful if there was an option or at least a comment saying if this is safe to do, and frankly I'm not sure why it's not the default.  Isn't 100 trillion objects in S3 enough for you guys?  Are these assets needed for more than a day, to handle stack deploys?

**Comment by NetaNir** [comment]
The bootstrap bucket is used for several other Assets such as Lambda runtime code. We are considering adding some from of Assets garbage collection to address this, you can read more about in this [issue](https://github.com/aws/aws-cdk-rfcs/issues/64) on the CDK RFC repo.

In the meantime you can customize the bootstrap template by using the `--template` option.
