### ISSUE TITLE
(ServerlessCluster): cdk deploy failure with custom subnetgroup reference

### ISSUE THREAD

**Issue by quixoticmonk** [aws/aws-cdk#13976]
### Description of the bug:
CDK deploy fails for an aurora serverless cluster when the subnetgroup name provided by user is uppercase. I had the resources in the cluster ( security group, subnetgroup etc) created with the names including the clustername as well; which was provided using a context value in cdk.json.

### Reproduction Steps
* Create Aurora serverless cluster construct with a subnet group defined rather than leaving it blank.
* The name of the subnet group is derived using the cluster name defined in the cdk.json.
* Cluster name is Uppercase and run a cdk synth .
* CDK/CloudFormation converts the subnetgroup name to lowercase.
* The cdk synth output shows cluster is referencing the id of the subnet group in cloudformation json/yaml.
* Deploy fails with the message " <subnetgroupname> does not exist" while the subnet group exists.

## Note: 
* The subnet group is created before the cluster as expected and then rolls back as the association to the cluster fails.

![Screen Shot 2021-04-02 at 4 04 28 PM](https://user-images.githubusercontent.com/11953035/113514522-1dc62280-953d-11eb-8fc0-0c5237a3aacc.png)
![Screen Shot 2021-04-02 at 4 02 32 PM](https://user-images.githubusercontent.com/11953035/113514523-1e5eb900-953d-11eb-88ee-991b21b15f84.png)
![Screen Shot 2021-04-02 at 4 02 50 PM](https://user-images.githubusercontent.com/11953035/113514541-31718900-953d-11eb-9ff5-2277c47a99b2.png)

![Screen Shot 2021-04-02 at 4 07 08 PM](https://user-images.githubusercontent.com/11953035/113514515-1c94f580-953d-11eb-8383-8ae264267c93.png)
![Screen Shot 2021-04-02 at 4 10 12 PM](https://user-images.githubusercontent.com/11953035/113514519-1d2d8c00-953d-11eb-9ef4-19ef9e907b17.png)
![Screen Shot 2021-04-02 at 4 10 06 PM](https://user-images.githubusercontent.com/11953035/113514520-1d2d8c00-953d-11eb-98d3-8b4679e650cb.png)
![Screen Shot 2021-04-02 at 4 07 53 PM](https://user-images.githubusercontent.com/11953035/113514521-1dc62280-953d-11eb-9239-36cebe9e4b3d.png)

### What did you expect to happen?
Since the reference was to the id of the subnetgroup, I would expect the cdk deploy to work and deploy the cluster

### What actually happened?
Error message as in screenshot below
![Screen Shot 2021-04-02 at 4 07 08 PM](https://user-images.githubusercontent.com/11953035/113514455-bf00a900-953c-11eb-85e0-da85cc052352.png)

### Environment

  - **CDK CLI Version  :** 1.96.0
  - **Framework Version:**1.96.0
  - **OS               :** Linux ( CDK pipeline & Cloud9 environment)
  - **Language (Version):** Python 3.8

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Thanks for reporting @quixoticmonk. Confirming I was able to reproduce the problem.
