### ISSUE TITLE
(Custom Resource): Custom Resource is deploying two lambda functions to the account.

### ISSUE THREAD

**Issue by CodeEngineTechnology** [aws/aws-cdk#13972]
Custom Resource is deploying two lambda functions to the account. The normal behavior is to see one lambda function that talks to custom resource not two. 

### Reproduction Steps
Created a cdk (typescript) project and added the following stack  :

```
import { ManagedPolicy, Role, ServicePrincipal } from '@aws-cdk/aws-iam';
import * as cdk from '@aws-cdk/core';
import { CustomResource, Duration } from '@aws-cdk/core';
import { join } from 'path';
import * as lambda from '@aws-cdk/aws-lambda';
import { Runtime } from '@aws-cdk/aws-lambda';
import { Provider } from '@aws-cdk/custom-resources';


export class TesCustomResourceStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const lambdaRole = new Role(this, `test-lambda-role`, {
      assumedBy: new ServicePrincipal('lambda.amazonaws.com'),
    });
    lambdaRole.addManagedPolicy(ManagedPolicy.fromAwsManagedPolicyName('AdministratorAccess-AWSElasticBeanstalk'));
    lambdaRole.addManagedPolicy(ManagedPolicy.fromAwsManagedPolicyName('CloudWatchFullAccess'));
    lambdaRole.addManagedPolicy(ManagedPolicy.fromAwsManagedPolicyName('AWSCertificateManagerFullAccess'));

    const albHelperFunction = new lambda.SingletonFunction(this, `test-alb-helper-function`, {
      role: lambdaRole,
      uuid: '1231231231',
      runtime: Runtime.NODEJS_12_X,
      code: lambda.Code.fromAsset(join(__dirname, './functions'),),
      handler: 'albHelperFunction.handler',
    });

    const provider = new Provider(this, `test-provider`, {
      onEventHandler: albHelperFunction,
    });

    const customResource = new CustomResource(this, `test-custom-resource`, {
      serviceToken: provider.serviceToken,
    });

  }
}

```

### What did you expect to happen?
The normal behavior is to see one lambda function in the account that talks to custom resource not two. 
![image](https://user-images.githubusercontent.com/54181887/113501684-00ad3780-94dc-11eb-9958-09a8caf13fda.png)

### Environment

  - **CDK CLI Version  :**
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):** 

### Other

--- 

This is :bug: Bug Report

**Comment by jogold** [comment]
@CodeEngineTechnology you're using the "mini-framework" for implementing providers for AWS CloudFormation (https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/custom-resources#provider-framework).

This framework "encapsulates" your Lambda function in its own Lambda function that handles error handling and communication with CloudFormation. That's why you end up with two Lambda functions deployed.

See also [Custom Resource Providers](https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/core#custom-resource-providers) for a comparison of the Custom Resource Providers.

If you want to fully implement the custom resource yourself you should do:

```ts
const customResource = new CustomResource(this, `test-custom-resource`, {
  serviceToken: albHelperFunction.functionArn,
});
```

I recommend you also have a look at the [`core.CustomResourceProvider class](https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/core#the-corecustomresourceprovider-class).

**Comment by CodeEngineTechnology** [comment]
@jogold Thanks you for getting back to me. I will test that and get back to you.

**Comment by CodeEngineTechnology** [comment]
@jogold I now see one lambda function in the account which is great. The only problem with this approach is Cloudformation gets stuck in Custom Resource creation process. 
I see the lambda during deployment and a success response that I created but Cloudformation is still waiting for Cutom Resource. Do you know the reason for this behavior?

Thanks for your help!


![image](https://user-images.githubusercontent.com/54181887/116450243-ea12ab80-a80f-11eb-9fdf-8a395020008f.png)

![B70A2062-092B-424F-B0A6-3DFA54A73097_1_201_a](https://user-images.githubusercontent.com/54181887/116450694-7329e280-a810-11eb-8f0b-cd0d8e72e49d.jpeg)

**Comment by jogold** [comment]
This most likely a problem with CloudFormation not receiving the correct response from your custom resource. One of the advantage of the framework is to avoid this situation.
