### ISSUE TITLE
(lambda) bundling: change default path from `/asset` to `/var/task`

### ISSUE THREAD

**Issue by nakedible-p** [aws/aws-cdk#13974]
Currently the documentation for @aws-cdk/aws-lambda states this:

> `lambda.Code.fromDockerBuild(path, options)` - use the result of a Docker build as code. The runtime code is expected to be located at `/asset` in the image and will be zipped and uploaded to S3 as an asset.

My suggestion is to change that path to be instead `/var/task` for the following reasons:

- `/var/task` is where AWS uncompresses the zip when it is being run, so if there are any absolute path references, they will be correct if the runnable code is installed directly in `/var/task`
- If there's a wish to use the same dockerfile for test invocations using AWS Lambda RIE, then `/var/task` is the correct path for that
- If using using the dockerfile also for Lambda Container Images, it is easy to switch between ZIP and Docker Image deployments as long as the generated code does not depend on anything outside `/var/task`

However, since the module seems to be declared already stable, I'm not sure if there's a reasonable path towards changing this default anymore. If that is the case, feel free to close this issue - no sense dragging it on any further.

The relevant constant is here, so the actual change would be trivial:

https://github.com/aws/aws-cdk/blob/7966f8d48c4bff26beb22856d289f9d0c7e7081d/packages/%40aws-cdk/aws-lambda/lib/code.ts#L70

**Comment by rix0rrr** [comment]
This is already configurable, right? So you're not actually blocked, except you'd like the default to be different?

**Comment by nakedible-p** [comment]
Yes, definitely - no problems with the current way things are - I'm just suggesting a "better" default. However, like said, I think the module is marked stable, so changing the default might be out of the question now - if so, feel free to close this bug.

**Comment by nakedible-p** [comment]
Also, I'm not sure why this would be "core", as the string in question to be changed is very solidly in "aws-lambda" package:

https://github.com/aws/aws-cdk/blob/7966f8d48c4bff26beb22856d289f9d0c7e7081d/packages/%40aws-cdk/aws-lambda/lib/code.ts#L69-L84

**Comment by nija-at** [comment]
@nakedible-p  - As you've correctly noted, the default is very hard to change in this stable module. 

We've got mechanisms to do so when we find something that's REALLY wrong, but it doesn't feel like this qualifies.

I'm going to mark this issue to be closed soon.
