### ISSUE TITLE
(Securitygroup): cdk diff shows no changes on ingress rule and progress bar at 2/5

### ISSUE THREAD

**Issue by quixoticmonk** [aws/aws-cdk#13989]
### Description of the bug:

- Updating the ingress rule on a security group shows " There were no differences" on a cdk diff.
- The progress bar on the cdk deploy from a cloud9 environment stops at 2/5, while the cloudformation changeset is executed 100%.  

**Note**:  The aurora cluster I am deploying has a secret associated with hosted rotation. The change in ingress rules in the main stack does seem like trying to update the hostedrotation lambda nested stack while there are no changes there. I somehow think this is why the progress bar is showing incorrect results.

### Reproduction Steps

- Created a serverless aurora cluster with security groups created custom. ( set to a ingress IP range of 10.0.0.0/8)
- Perform cdk depploy
- Make a change to the ingress IP range to 10.0.0.0/16
- Perform cdk diff
- Perform cdk deploy 

### What did you expect to happen?

- Expected the cdk diff to show the changes in the ingress IP change.
- If I make a change in the port and perform a cdk diff, the change in IP is also shown.

### What actually happened?

- Screenshots below:
- cdk diff
![Screen Shot 2021-04-05 at 10 02 31 PM](https://user-images.githubusercontent.com/11953035/113648627-e8175b80-965a-11eb-89fe-64a37a82210d.png)

- Progress bar :
![Screen Shot 2021-04-05 at 10 01 36 PM](https://user-images.githubusercontent.com/11953035/113648359-81923d80-965a-11eb-9df6-997c425db5d6.png)
![Screen Shot 2021-04-05 at 10 17 12 PM](https://user-images.githubusercontent.com/11953035/113649644-cd45e680-965c-11eb-861b-013b40e47656.png)

### Environment

  - **CDK CLI Version  :** 1.96.0
  - **Node.js Version:** v10.24.0
  - **OS               :** Linux
  - **Language (Version):** Python 3.8

--- 

This is :bug: Bug Report

**Comment by quixoticmonk** [comment]
![Screen Shot 2021-04-05 at 10 30 21 PM](https://user-images.githubusercontent.com/11953035/113650624-82c56980-965e-11eb-9ed9-8ed25aeb510c.png)
Another example where there was a rollback on the cluster was fixed. From a diff, only the main stack has status change from the rollback_complete status while the nested stack and a secret in that is considered part of changeset, but not updated.

**Comment by rix0rrr** [comment]
This is 2 bugs reported as one, which makes it very hard to triage this ticket and/or close it and/or set a priority.

> Updating the ingress rule on a security group shows " There were no differences" on a cdk diff.

Can you show example code that causes this? Can you reproduce it with a smaller example?

> The progress bar on the cdk deploy from a cloud9 environment stops at 2/5, while the cloudformation changeset is executed 100%.

You explicitly mention "from a cloud9 environment', does that mean it does NOT happen for non-Cloud9 environments? Are you able to produce a minimal reproducible example that shows that the behavior on Cloud9 is different? Or even a template for which you can ensure the progress bar does not fill up all the way?

**Comment by quixoticmonk** [comment]
@rix0rrr  Apologies for the multiple issues. I can split it into two. 

- **Code sample:** https://gist.github.com/quixoticmonk/a88f7a2d258ea0124fcc2eb87cd5a6a3
- CDK deploy this code and it will have a nested stack due to the hosted rotation lambda.
- Once deployed, make a change and do another deploy.
- I mentioned cloud9 since that is the only environment I have access to do a cdk based deploy on cli.  I don't have an option to test this on a local terminal with aws creds.

**Comment by quixoticmonk** [comment]
@rix0rrr 
```
        _vpc = ec2.Vpc.from_lookup(
            self,
            "vpc",
            vpc_id=vpcid
        )

       _cluster_sg = ec2.SecurityGroup(
            self,
            id="sg",
            vpc=_vpc,
            security_group_name="cluster-sg"
        )
        _cluster_sg.add_ingress_rule(
            peer=ec2.Peer.ipv4('10.0.0.0/8'),
            connection=ec2.Port.tcp(3306),
            description="Alow DB access"
        )
```

- cdk deploy
- changed ingress port entries and ran cdk diff
- cdk deploy again

![Screen Shot 2021-04-12 at 12 23 21 PM](https://user-images.githubusercontent.com/11953035/114428334-11b81180-9b8a-11eb-9102-c4ef75f353b0.png)
