### ISSUE TITLE
(lambda): Consider renaming `Function`

### ISSUE THREAD

**Issue by TimothyJones** [aws/aws-cdk#13991]
The current API for `@aws-cdk/aws-lambda` exposes a type called `Function`. In addition to being easily confused with the built-in `Function` type, this clashes with typescript-eslint rules like [`ban-types`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/ban-types.md), as [discussed here](https://github.com/typescript-eslint/typescript-eslint/issues/2338). Would it not be more correct to name the export `LambdaFunction`?

Additionally, `@aws-cdk/aws-events-targets` _does_ expose a type called `LambdaFunction`, but (unless I am missing something) would it not be more correct to name that export `LambdaFunctionTarget`?

### Use Case

I'd like this feature so that newcomers to the CDK can easily tell that `Function` is not the same as the `Function` built-in type, and can use eslint rules with no additional challenges, and so that the API surface exposed by aws-cdk is more intuitive.

### Proposed Solution

for the next major release of aws-cdk:

* In `aws-lambda`, rename `Function` to `LambdaFunction`
* In `aws-event-targets`, rename `LambdaFunction` to `LambdaFunctionTarget` (or similar) (There may be other similar renames in that module).

### Other

If you would be willing to accept it, I am happy to make a PR for this one

* [X] :wave: I may be able to implement this feature request
* [X] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by nija-at** [comment]
Hi @TimothyJones -

Thanks for filing this issue. We will consider it as part of the next major release of the CDK.

We have not heard much complaints about much confusion here. I will leave this issue open if others in the community feels this way and want to 👍 this issue.

**Comment by TimothyJones** [comment]
Makes sense! It’s small fish, so I’m not sure many people who notice it would come to report it- but either way I’m happy with whatever resolution the maintainers think is right.

Would you like a PR for your consideration?

**Comment by TimothyJones** [comment]
My view is that if you close the issue now, then it will discourage others from making similar comments. To be honest, I'm surprised this is contentious:

* The CDK maps to underlying Cloudformation resources - the resource in this case is `AWS::Lambda::Function`. I think the best user experience would be not to deviate from those names.
* `Function` is part of the built-in type interface, so overloading it means that code using it is less clear (currently, it has caused problems with some lint rules - and possibly other unforeseen issues)
* I brought this up because I noticed the packages were changing for the next release, so it would be a good time to do a breaking types improvement. However, if you wanted to release it without breaking, then you could expose the old types as an alias.
 
I think my role as a user is to report issues. If you think it's not a sensible change or worth doing, then of course I'm happy with whatever resolution you think is reasonable.

**Comment by nija-at** [comment]
I'm happy to leave this open to see if there's more interest here, or if there are more complaints in this area.

If we don't see that signal over time, we will have to close this request out. We will need to prioritize which requests to service.
