### ISSUE TITLE
Guidance: why are lookup results recommended to always be cached in `cdk.context.json`?

### ISSUE THREAD

**Issue by mrpackethead** [aws/aws-cdk#14006]
See this comment: https://github.com/aws/aws-cdk/issues/14006#issuecomment-814724673 for the description of the issue.

**Comment by mrpackethead** [comment]
Situation:

(1) CDK is never run locally on a desktop after development has finished.   Its only ever run on as part of a pipeline.    
(2) Configuration for our stacks is done via simple YAML files, which the cdk app reads..    For example, i have a route53 resolver stack that creates rules for a simple list of domains.. 
(3) the intention is that many 'updates' / 'chanages' can be done by operations folks at much lower cost that developers..  If they can update a text file and submit a PR to a repo. they can do the job. 

(5) We use Tags on accounts in the organsation to determine were stacks are applied..   This means tehres only ever one source of truth..  The account list in orgs.     The cdk app looks up the org to determine which accounts will get stacks deployed to it, and which accounts to share my route resolvers rules to. 

(6) The app  then deploys an 'assosciation' stack to all accounts that resolver rules have been shared to..  It associates the rules with the VPC.   The app does a VPC lookup.      While VPC's in the accounts are veyr unlikely to change.. they could.   If the cdk.context.json was cached from teh first time it ran.  it woudl try to deploy to a vpc that doe'stn exisit any longer. 

The example, brings me to this point.. I need my stack to 'look' at an environment right now, and do soemthign based on what it looks like right now..  not what it looked like sometime ago.. 

The recommednation is that thigns shoudl be cached..  but in this case, that doe'stn seem to work..

I'm using this technique and its working well for me. but its running in conflict with this recommedation.  

I understand that synthing. ( essentially populating the cdk.context.json ) and then committing to a repo, means that every commit point in your repo represents a everythign you need to reconstruct the stack...   However even if you have all those commit points, its highly likely you can't go back anyway, as the infrastructure that might be deployed that this stack is using, may have changed..    

essentially what got created 'last' time, has not nessarily going to reflect what we need this time. So caching what we did last time and using it is, not really useful. 

If i don't cache. ( efectively by recreating cdk.context.json ) everytime we deply/redploy i can see that i loose some of this 'history,' but what i gain in automaton by not having to deal to this. might make the loss ok.   But to be honest right now, i can't see that i'm loosing anything useful.  

( I certainly see in SOME circumstances that caching cdk.context.json ) is a very good idea. but not in ALL.  

Assuming i'm 'loosing' something by not keeping my cdk.context.json,  I could potentially have my pipeline synth stage, do the synth, and then push the the context back into the repo..  I'd probalby apply tags on those commits so that it was very obvious that it was the pipeline..       That would mean, at a pinch if i really needed to i could get the context back for any given deployment...    But just because i can, does'tn mean i need to..  

So, what do you really loose if you dont' cache.

**Comment by skinny85** [comment]
@eladb do you mind giving your opinion here?

**Comment by eladb** [comment]
The rationale is documented [here](https://docs.aws.amazon.com/cdk/latest/guide/context.html). Let us know if this answers your questions or if we should improve our docs on the topic.

**Comment by mrpackethead** [comment]
It woudl be increadibly useful to be able to set a 'do-not-cache' flag on any lookup.  This would give you the flexiblity to do what you need.

**Comment by eladb** [comment]
@mrpackethead wrote:

> If what exists changes, i need to change things. If 'changes' get masked because things were cached, the caching falls if your environment is not static. Thats just not always going to be the case.

I am trying to understand your use case a bit better: let's say you didn't commit the lookup results (which you can of course) and every time you deployed, a new lookup was performed. What would happen if *after* a deployment, some resource you depend on seized to exist? Wouldn't that cause disruption to your service?

My point is: if your service depends on some external resource, and you want to make sure that every time this resource changes somehow, your service gets re-deployed, my advise is to automatically commit a change to your source control and have your normal CI/CD workflow kick-in. This will give you both deterministic behavior from a CI/CD perspective (e.g. you can roll-back, etc) *and* will make sure your system doesn't depend on an external resource that doesn't exist.

**Comment by eladb** [comment]
@mrpackethead I am closing this issue for now. Please let us know if you need additional guidance.
