### ISSUE TITLE
(aws-cdk): Unable to deploy CDK app after upgrading to Aws Cli v2

### ISSUE THREAD

**Issue by MandoKapeso** [aws/aws-cdk#14003]
## :question: General Issue
After upgrading to the Aws Cli v2, I am unable to deploy my CDK application, (FYI I have also tried using the CDK sample application). I get an assert publish error as below

```
cdkworkshop: deploying...
[0%] Publishing d8374ac...
[100%] fail: Unexpected close tag
Line: 14
Column: 6
Char: >

cdkworkshop failed: Error: Failed to publish one or more assets. See the error messages above for more information.
```

I have also run the` cdk deploy --verbose` and the stack trace is in conclusive as it provides the same error with not much more information on a plausible root cause.

### The Question

I was able to successfully deploy the application when I use the Aws Cli v1. I have updated all my Aws Construct libraries via npm and I am able to create the bootstrap stack successfully. Is there any additional modules I should be upgrading that could perhaps cause this issue?  

### Environment

  - **CDK CLI Version:**  1.94.1
  - **Module Version:** 
  - **Node.js Version:**  10.24.0
  - **OS:**  Redhat
  - **Language (Version):**  Python (3.7)

**Comment by rix0rrr** [comment]
It is unlikely that your version of AWS CLI has anything to do with this. It's possible, but I don't really see how that would work.

From the error message, I would guess it has to be something with XML parsing somewhere, but without more information it's hard to say.

Would you mind running the CLI through [mitmproxy](https://mitmproxy.org/) and trying again, seeing if it's something obviously in the request/response against S3?

Rough steps:

```
# install mitmproxy via whatever means you prefer

(in terminal 1)
$ mitmdump -vvv

(in terminal 2)
$ export https_proxy=http://localhost:8080/
$ export NODE_TLS_REJECT_UNAUTHORIZED=0 
$ cdk deploy

(see what appears in the mitmdump log)
```
