### ISSUE TITLE
core: golang bundling not detecting changes in packages

### ISSUE THREAD

**Issue by strongishllama** [aws/aws-cdk#14018]
When bunding Golang Lambda Functions with Docker changes to imported packages are not detected. I've attached an [example project](https://github.com/aws/aws-cdk/files/6270716/temp.zip) where the issue is present.

### Reproduction Steps
1. Download and extract the attached example CDK project.
2. Run ```cdk deploy``` to deploy the stack.
3. Remove the exclamation mark in the ```Hello World!``` message on line ```6``` of ```./pkg/print/print.go```.
4. Run ```cdk deploy``` again and no changes will be detected on the stack.

### What did you expect to happen?
The stack to detect the changes in the Lambda Function source and re-deploy it.

### What actually happened?
The changes in the Lambda Function source aren't detected. Note this issue isn't present if the changes aren't in the imported ```print``` package but in the ```main.go``` file.

### Environment

  - **CDK CLI Version :** 1.97.0 (build c52c2dc)
  - **Framework Version:** 1.97.0
  - **Node.js Version:** 

14.16.0
  - **OS :** Ubuntu 20.10
  - **Language (Version):** TypeScript (4.1.3)
--- 

This is :bug: Bug Report

**Comment by jogold** [comment]
Hi @strongishllama 

When doing `lambda.Code.fromAsset(path.join(__dirname, "../lambdas/hello-world"), ...)` you indicate that `lambdas/hello-world` is your "source". The CDK hashes the content of this "source" and if it doesn't change it won't update the asset/redeploy.

If you put your `print.go` file in `lambdas/hello-world`, changes will be detected.

Another option could be to calculate your asset hash on the content of the bundling output, this can be done by setting `assetHashType` to `cdk.AssetHashType.OUTPUT`.

**Comment by strongishllama** [comment]
Hi @jogold, changing the ```assetHashType``` to ```cdk.AssetHashType.OUTPUT``` has fixed my issue. Cheers!
