### ISSUE TITLE
(s3): autoDeleteObjects does not work when updating the BucketName on existing logical resource

### ISSUE THREAD

**Issue by ryanwilliams83** [aws/aws-cdk#14011]
Changing BucketName without changing the Logical Resource ID causes CloudFormation to issue an UPDATE RequestType to the CustomS3AutoDeleteObjects Lambda which then does NOT empty the old physical bucket which effectively creates an orphaned bucket even though AutoDeleteObjects = true and RemovalPolicy = RemovalPolicy.DESTROY

**Problem Code**
https://github.com/jogold/aws-cdk/blob/master/packages/@aws-cdk/aws-s3/lib/auto-delete-objects-handler/index.ts#L10

**Example Request**
{
  "RequestType": "Update"
  "ResourceProperties": {
    "BucketName": "IRenamedThisBucketSinceLastDeploy"
  },
  "OldResourceProperties": {
   "BucketName": "ThisBucketWillNotBeEmptiedEvenThoughItShould" 
  }
}

### Reproduction Steps
1) Create and deploy stack containing bucket with AutoDeleteObjects = true, BucketName = "SomethingStatic", RemovalPolicy = RemovalPolicy.DESTROY
2) Manually upload a file to the bucket
3) Change BucketName property
4) deploy stack again to observe error

### What did you expect to happen?
Old bucket to be emptied before CloudFormation tried to delete it.

### What actually happened?
Error: The bucket you tried to delete is not empty (Service: Amazon S3; Status Code: 409; Error Code: BucketNotEmpty;

### Environment
  - **CDK CLI Version: aws-cli/2.0.47 Python/3.7.7 Windows/10 exe/AMD64**
  - **Framework Version:**
  - **Node.js Version: v14.16.0** 
  - **OS    Windows 10           :**
  - **Language (Version): C#** 

### Other

--- 

This is :bug: Bug Report

**Comment by berenddeboer** [comment]
I've observed slightly different behaviour. When just changing `bucketName` on a non-empty bucket and deploying, it deploys fine, but the original bucket gets orphaned, even though `autoDeleteObjects` is true. So I didn't see an error.

I'm on cdk 1.101.0 (build 149f0fc).
