### ISSUE TITLE
(account): multi-account deploys and shared resources - not supported?

### ISSUE THREAD

**Issue by Plasma** [aws/aws-cdk#14021]
### The Question

Hey,

Its unclear how you’re supposed to use CDK when you work with multiple AWS accounts in the “best practice” style:

1. Primary account (SSO, billing)
2. Shared tools account (eg code pipeline and ECR)
2. Test environment account 
3. Production environment account 
4. ... etc

This could have been setup as part of Control Tower or regular organisation. 

An application stack (RDS, web servers, etc) would be deployed both to the Test and Prod accounts, and then a once off CodePipeline/ECR to the shared tools account.

Trying to do this out of the box fails.

Even if you specify the Env (region and account Id) for each stack in the cdk, the cli seems to fail because the aws credentials you’re using is for a specific account, so multi account stack deployments fail.

I managed to kind of get some of it working by calling deploy multiple times with different —profile parameters (one for each account ID), and limiting what stack I deployed with —exclusively so no dependencies were touched, but that doesn’t work when one stack references a shared resource in another stack that’s in a different account.

I’ve not been able to find offical guidance on this workflow, which seems to be recommended best practice (multi account setups).

Thank you

### Environment

  - **CDK CLI Version:** 
  - **Module Version:** 
  - **Node.js Version:** 
  - **OS:** 
  - **Language (Version):**

**Comment by NGL321** [comment]
Hey @Plasma,

Thank you for reaching out! Sorry it has taken us so long to get back to you. I am not entirely certain I understand the problem you are facing.

I have not had any trouble deploying stacks to multiple accounts simultaneously. Additionally, our recommendation is to have a deployment stack when deploying to multiple accounts (typically CDK pipelines), this should be able to handle the credential management you are concerned with.

If you are still unable to deploy the same stack to multiple accounts could you provide a little more information on how it is failing? (logs, stack code, error messages, etc.).

😸 😷
