### ISSUE TITLE
Validate AppSync Code-First GraphQL Schema before deploying

### ISSUE THREAD

**Issue by hirenumradia** [aws/aws-cdk#14022]
I am using the code-first approach to constructing my GraphQL schema with `@aws-cdk/aws-appsync`. I have noticed that the schemas errors are really vague when pushing new schema changes via CDK.

E.G the last error I got was:
`Schema Creation Status is FAILED with details: Failed to parse schema document - ensure it's a valid SDL-formatted document.`

I would love to be able to validate the schema before deployment or even print / save the schema to file as a test run. Its sometimes hard to spot mistakes when you are composing your schema using multiple files.

### Use Case

We use AWS CDK and App Sync to build our GraphQL API. We need to be able to write the GraphQL schema reliably and test it before deploys.

### Current Workaround

Currently, I am doing a `console.log()` of the schema during deployment to try and spot issues.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by MrArnoldPalmer** [comment]
@hirenumradia I definitely think this is something we should pursue. Can you provide some of the example errors that CFN is throwing?

**Comment by hirenumradia** [comment]
Thanks, @MrArnoldPalmer. 👍🏽 I left a message in the other chat but am copying it here as well so there is a proper thread for this feature.  

We are at the start of setting up our infrastructure hence why these types of issues more likely to come up.

**Background**

Our setup has one Backend Stack that composes the various microservices. Each microservice is a Nested Stack that has any common infrastructure resources such as the API passed down to them. 

The types and the fields are composed within these Nested Stacks, specifically, I am creating these types and fields within a CDK construct so that each use case that we are developing is separated into a "cloud component".

**The issue**

When composing the schema, I was able to put together the schema that passed the static compilation steps of Typescript, however, the syntactical validation was failing when deploying the schema.

I was previously generating a schema file that was "stitching together" multiple types and resolvers via a code generation module I wrote. I was able to see the schema before deploys and fix the issues. I moved onto this code-first approach for maintainability.

These were the Cloudformation errors I was getting

`Schema Creation Status is FAILED with details: Internal Failure while saving the schema.`

`Schema Creation Status is FAILED with details: Failed to parse schema document - ensure it's a valid SDL-formatted document.`

**Immediate Thoughts / Suggestions**

- We could have some way of testing the schema before deployment where any validation errors of the schema are caught at the time of bootstrapping the stack and presented.
- Provide a Class that helps to build the schema and contains some utility functions for validation

**Comment by BryanPan342** [comment]
This feature is a big part of the appsync experience (esp the code-first). 

Currently, I'm thinking we would have to run a check on synthesis after the entire gql string is built out.. Speaking top of mind, there are two parts to this issue: syntax and semantics. 

The code-first model should protect against most syntactical errors. Since we are generating most of the actual output itself, as long as the construct isn't generating bad code, our syntax issues should be assuaged. I'm sure there are probably some issues here and there that need to be resolved to make it more robust, but in theory, the code-first model should save us from syntax errors. 

As for the more semantic problems, I think the [`graphql` ](https://graphql.org/graphql-js/validation/) library itself has a tone of great resources for this. 

@MrArnoldPalmer how well-received would it be to add another package to the CDK dependencies?

**Comment by MrArnoldPalmer** [comment]
@BryanPan342 I think it would be received fine for this case. Definitely seems like something we prioritize 👍🏻

**Comment by hirenumradia** [comment]
FYI, I ran into this issue again today. I am trying to teach the team how to use CDK and during the deployment of a new service, the GraphQl schema is the only thing that is causing the Coudformation build to fail.

Our schema is fragmented where each service looks after its own part. So it's sometimes hard to reason about how it all fits together semantically.

Here is the error I just encountered. I know I mentioned it before but through it may be useful so that we can think about incidence rate:

`Schema Creation Status is FAILED with details: Failed to parse schema document - ensure it's a valid SDL-formatted document.`

@BryanPan342 that looks really promising! The synthesis stage sounds like it would be the best time. As you have mentioned, this is where the string is constructed and where it can be validated most easily.

Also, from developer experience, you can focus on writing your syntactically valid code-first schema and then catch the semantic issues just before deploying.

I guess an even nicer experience in the future could be having some sort of watch feature that watches for changes in the schema before deployment. However, that seems out of scope for the initial implementation.

**Comment by BryanPan342** [comment]
I started implementing validation and will post a PR today! There are **some** complications with some of the custom AppSync directives and scalar types, but I'm figuring it out as I go haha. 

I wonder if it would be helpful to have a setting to push out the schema file, kind of like some sort of `eject` method! This might be helpful for debugging?

**Comment by hirenumradia** [comment]
@BryanPan342 An eject method would be pretty useful, most of the time it's just viewing the schema to make sure it makes sense.  Adding some schema validation that understands AppSync directives will make the CDK experience even better. There are also some other code generation use cases we would love to build from the GraphQL schema. So an ability to registerMiddlewares (the first being a validator) would be great. That means we can extend the tooling with our custom use cases. Just a thought.
