### ISSUE TITLE
(@aws-cdk/custom-resources): custom resources do not support renaming a resource with giving broad permissions 

### ISSUE THREAD

**Issue by royby-cyberark** [aws/aws-cdk#14037]
### The Question
I am not sure if this is a feature request, a bug or simply using custom resources the wrong way. 
What I am trying to achieve is create a custom resource which name is part of its arn and also be able to update its name if needed. 
If I only give the custom resource lambda permissions for the exact resource arn, then it will fail when trying to delete the old resource. which makes sense because it now have permissions for the new arn, but not the old one. 
but this means that you cannot use custom resource to update names (or arn related property) without giving the lambda permissions to '*' (example below), and of course, we would like to give as narrow permissions as possible.

the code below gives the needed permissions for the exact parameter arn which is good (see call to from_sdk_calls), 
but it fails when you try to update the resource name, since the lambda will create the new parameter and call delete on the old one, unless you add the delete permissions to '*' parameters like I did on the last line (call to resource.grant_principal.add_to_policy)

```
param_name = some-value # This is the ssm param name that is part of the arn
policy = AwsCustomResourcePolicy.from_sdk_calls(resources=[f'arn:aws:ssm:{region}:{account_id}:parameter/{param_name}])

resource = AwsCustomResource(scope=self, id=f'{id_}AwsCustomResource', policy=policy, log_retention=log_retention,
                                            on_create=on_create, on_update=on_update, on_delete=on_delete,
                                            resource_type='Custom::AWSSecureString', 
                                            timeout=timeout)

resource.grant_principal.add_to_policy(iam.PolicyStatement(actions=['ssm:DeleteParameter'], resources=[f'arn:aws:ssm:{region}:{account_id}:parameter/*']))  
```

Is there a way to do it without giving the '*' permissions? 
is this a bug? or maybe a feature request, or perhaps i'm using this wrong.

Thanks for your help

**Comment by royby-cyberark** [comment]
I did some more testing and it seems that its not as straight forward as I thought. 
On one scenario i'm missing the delete permissions on the old resource, but on another, i'm missing the create permissions.

Here are the scenarios I reproduced:

This is the code i'm starting with:
param_name - is the parameter name which i'll update in the next scenario.


```
    account_id = core.Stack.of(self).account
    region = core.Stack.of(self).region

    param_name = # See different scenarios and results below

    on_create = self.get_on_create_update(param_name=param_name)
    on_update = self.get_on_create_update(param_name=param_name)
    on_delete = self.get_on_delete(param_name=param_name)

    policy = AwsCustomResourcePolicy.from_sdk_calls(resources=[f'arn:aws:ssm:{region}:{account_id}:parameter{param_name}'])

    resource = AwsCustomResource(scope=self, id=f'{id}AwsCustomResource', policy=policy,
                                            on_create=on_create, on_update=on_update, on_delete=on_delete,
                                            resource_type='Custom::AWSSecureString')

    # Some helper functions

    def get_on_create_update(self, param_name):
        params = {
            "Name": param_name,
            # Cannot create with empty value. Neve deploy real secrets in CDK/CF. populate after deployment
            "Value": "<PLACEHOLDER>",
            "Type": "SecureString",
            "Overwrite": True
        }
        return self.get_sdk_operation(resource_id=param_name, params=params, action_name='putParameter')

    def get_on_delete(self, param_name: str):
        params = {"Name": param_name}
        return self.get_sdk_operation(resource_id=param_name, params=params, action_name='deleteParameter')

    def get_sdk_operation(self, resource_id, params, action_name):
        action = AwsSdkCall(
            action=action_name,
            service='SSM',
            parameters=params,
            physical_resource_id=PhysicalResourceId.of(id=resource_id),
        )
        return action
```

1. **first scenario**
Clean, first time deplyment, one parameter - using the above code. 

param_name = f"/TestParamPath/testParam1"

Deployed ok
see cdk output template: [cdk-custom-resource-example.template-clean-deploy-one-parm-1.json](https://gist.github.com/royby-cyberark/27940c35aee99b9184e5f373c156e1be)

2. **Second scenario: same code, updated the param name:**

param name was testParam1, changed to testParam2

`param_name = f"/TestParamPath/testParam2"`

deploy failed

cdk deploy template file: [cdk-custom-resource-example.template-update-name-one-param.json](https://gist.github.com/royby-cyberark/6d5633eba941388f9e918a34bee15fe1)

Error:

> 9:34:15 PM | UPDATE_FAILED        | Custom::AWSSecureString | cdkcustomresourcee...omResource5011686B
> Received response status [FAILED] from custom resource. Message returned: User: arn:aws:sts::195361640859:assumed-role/cdk-custom-resource-examp-AWS679f53fac002430cb0da5-1D0XZPJ7WUUZG/cdk-c
> ustom-resource-examp-AWS679f53fac002430cb0da5-13MT35OFA6902 is not authorized to perform: ssm:PutParameter on resource: arn:aws:ssm:us-east-1:195361640859:parameter/TestParamPath/testParam2
> (RequestId: b4724d2c-8f93-4222-806f-d4411d388150)

3.  **clean deploy with two parameters**

in addition to the above code, I added a second parameter:

```
param_name2 = f"/TestParamPath/testParam2-1"

on_create = self.get_on_create_update(param_name=param_name2)
on_update = self.get_on_create_update(param_name=param_name2)
on_delete = self.get_on_delete(param_name=param_name2)

policy2 = AwsCustomResourcePolicy.from_sdk_calls(resources=[f'arn:aws:ssm:{region}:{account_id}:parameter{param_name2}'])

resource = AwsCustomResource(scope=self, id=f'{id}AwsCustomResource2', policy=policy2,
                                        on_create=on_create, on_update=on_update, on_delete=on_delete,
                                        resource_type='Custom::AWSSecureString')
```

The rest of the code is the same.

deploy ok

cdk deploy template: [cdk-custom-resource-example.template-clean-deploy-two-params.json](https://gist.github.com/royby-cyberark/6b5ee01c713a2426871ad30893183251)

4. **Update only the first parmeter name**

`param_name = f"/TestParamPath/testParam1-2"`

(Sorry for the naming, the first param_name started as testParam2 and changed now to testParam1-2)

And now i'm getting the error that i'm missing the delete on testParam2:

> 
> 10:20:46 PM | DELETE_FAILED        | AWS::CloudFormation::CustomResource | cdkcustomresourcee...omResource5011686B
> Received response status [FAILED] from custom resource. Message returned: User: arn:aws:sts::195361640859:assumed-role/cdk-custom-resource-examp-AWS679f53fac002430cb0da
> 5-1NAA8QWP4NI65/cdk-custom-resource-examp-AWS679f53fac002430cb0da5-1PHWHZCLW0C69 is not authorized to perform: ssm:DeleteParameter on resource: arn:aws:ssm:us-east-1:19
> 

cdk deploy template:

[cdk-custom-resource-example.template-two-params-update-first-param.json](https://gist.github.com/royby-cyberark/4abab17fa967a6cfc56d8c49263b8505)

------------

It seems that in this scenario, i'm getting an error for missing delete permissions on the old param name. which was my original issue, but in the second scenario I got an error about missing update permissions for the NEW parameter. 
so it seems that I not only need to give '*' permissions to delete but also to update.

**Comment by rix0rrr** [comment]
One trick that was used in the `AwsCustomResource` is to create a policy object (`AWS::IAM::Policy`) for every individual resource grant, instead of combining all permissions into the same `AWS::IAM::Policy` (as is the default). The logicalId would have to be unique and based on the resource ARN, or something.

By doing this, when an UPDATE happens the new grant is applied first, the Custom REsource is executed with the new permissions, then the Custom Resource is executed to DELETE the old resource and then the old permissions are deleted.

In `AwsCustomResource` they used an `AWS::IAM::ManagedPolicy` instead to achieve the same effect, but that's actually not necessary -- a regular `AWS::IAM::Policy` would have the same effect.

**Comment by royby-cyberark** [comment]
@rix0rrr thanks for your help!
I am trying to do what you suggested without success so far.  but before I share my code a quick question, i'm a little confused because you suggest the AWSCustomResource should not suffer from my issue because they use this trick (only cdk custom resource should suffer from this?), but my issue and my code snippets above, is when using AWSCustomResource (and also cdk custom resource).

If I understand what you suggest, is that I create a different policy for putParameter, deleteParameter for the param name (which are the permissions needed). 

I tried the following:

```
# I am required to provide the policy param, so I did, although i'm also providing the policy to the role next. 

       policy = AwsCustomResourcePolicy.from_sdk_calls(resources=[f'arn:aws:ssm:{region}:{account_id}:parameter{param_name}'])

        role = Role(
                scope=self,
                id=f'LambdaRole',
                assumed_by=ServicePrincipal('lambda.amazonaws.com'),
                # managed_policies=[ManagedPolicy.from_aws_managed_policy_name("service-role/AWSLambdaBasicExecutionRole")],
            )

        role.attach_inline_policy(
            Policy(scope=self, 
                   id='policy1putparam', 
                   statements=[PolicyStatement(actions=["ssm:PutParameter"], resources=[f'arn:aws:ssm:{region}:{account_id}:parameter{param_name}'])]))

        role.attach_inline_policy(
            Policy(scope=self, 
                   id='policy1delparam', 
                   statements=[PolicyStatement(actions=["ssm:DeleteParameter"], resources=[f'arn:aws:ssm:{region}:{account_id}:parameter{param_name}'])]))


        resource = AwsCustomResource(scope=self, id=f'{id}AwsCustomResource', role=role, policy=policy,
                                                on_create=on_create, on_update=on_update, on_delete=on_delete,
                                                resource_type='Custom::AWSSecureString')
```

Is this what you meant? 
When I did this for both parameters and updated the second one (like in my original reproduction above) I still got the error:

9f53fac002430cb0da5-1LHTX4VBE9I82 is not authorized to perform: ssm:DeleteParameter on resource: arn:aws:ssm:us-east-1:195361640859:parameter/TestParamPath/testParam2-1 (RequestId: b3f62550-3815-4570-a357-15f1bd
43f65e)

Did I misunderstand you?
Is there another way I was supposed to do it?
If a solution does require using the role parameter, i'm afraid it would suffer from this issue: https://github.com/aws/aws-cdk/issues/13601, which I think the comments suggest, would become an error when its solved.

Thanks for your help again.

**Comment by rix0rrr** [comment]
It doesn't work right now because the `AwsCustomResource` doesn't have dependencies on the policies you added.

The custom resource code explicitly adds dependencies to make sure the policy doesn't get deleted before the CR is executed:

https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/custom-resources/lib/aws-custom-resource/aws-custom-resource.ts#L419

In your case it would look like:

```
custom_resource.node.default_child.node.add_dependency(policy)
```

**Comment by rix0rrr** [comment]
BTW I think you can put `ssm:PutParameter` and `ssm:DeleteParameter` in the same policy. Should be fine.

**Comment by royby-cyberark** [comment]
@rix0rrr  thanks again for you help.
so I tried using your suggestion of calling 
`custom_resource.node.default_child.node.add_dependency(policy)`
Since the policy from from_sdk_calls is not an iam policy (it does not implement DependableTrait), I needed to do it on a role that I created.
but it still fails when trying to rename the param, I still get an error, unauthorized to putParam on the **new** param name.
i'll try to make sure that I don't miss anything technical,
but I was wondering a couple of things that maybe you can help with in the meantime:
1. if the [code you pointed to](https://github.com/aws/aws-cdk/blob/8b293b058594317bf4b77234ba00d2deb7afd5d9/packages/%40aws-cdk/custom-resources/lib/aws-custom-resource/aws-custom-resource.ts#L417-L419) already calls addDependency for the policy that is created internally from the from_sdk_calls policy, then why do I need to add an dependency myself? it seems like i'm trying to do the same, only by passing a role and adding the dependency on it.
so i'm wondering if i'm even trying to do something that make sense, or perhaps there's something more fundamental that's not working for me here.

2. For the sake of trying things, do I have any way to access the internally created [provider](https://github.com/aws/aws-cdk/blob/8b293b058594317bf4b77234ba00d2deb7afd5d9/packages/%40aws-cdk/custom-resources/lib/aws-custom-resource/aws-custom-resource.ts#L360), [policy](https://github.com/aws/aws-cdk/blob/8b293b058594317bf4b77234ba00d2deb7afd5d9/packages/%40aws-cdk/custom-resources/lib/aws-custom-resource/aws-custom-resource.ts#L398) and such? 

This is the code I was trying:
```
        account_id = core.Stack.of(self).account
        region = core.Stack.of(self).region

        param_name = "someparam2"

        on_create = self.get_on_create_update(param_name=param_name)
        on_update = self.get_on_create_update(param_name=param_name)
        on_delete = self.get_on_delete(param_name=param_name)

        role = Role(scope=self, id=f'LambdaRole', assumed_by=ServicePrincipal('lambda.amazonaws.com'))

        role.attach_inline_policy(
            Policy(scope=self, 
                id='paramsPolicy', 
                statements=[
                    PolicyStatement(actions=["ssm:PutParameter", "ssm:DeleteParameter"], 
                    resources=[f'arn:aws:ssm:{region}:{account_id}:parameter/{param_name}'])
                ]))

        policy = AwsCustomResourcePolicy.from_sdk_calls(resources=[f'arn:aws:ssm:{region}:{account_id}:parameter/{param_name}'])

        custom_resource = AwsCustomResource(scope=self, id=f'{id}AwsCustomResource', policy=policy, role=role,
                                                on_create=on_create, on_update=on_update, on_delete=on_delete,
                                                resource_type='Custom::AWSSecureString')


        custom_resource.node.default_child.node.add_dependency(role)
```

Thank you again for investing your time in this, I truly appreciate it.

**Comment by peterwoodworth** [comment]
The original question has been resolved, so I'll be closing the issue.

@royby-cyberark I'm sorry no one has responded to this in a while, if you'd like more help with this please create a new issue 🙂

**Comment by peterwoodworth** [comment]
Also - I believe that the policy that the resource needs to depend on is the policy you add to the role you pass in:

```
Policy(scope=self, 
                id='paramsPolicy', 
                statements=[
                    PolicyStatement(actions=["ssm:PutParameter", "ssm:DeleteParameter"], 
                    resources=[f'arn:aws:ssm:{region}:{account_id}:parameter/{param_name}'])
                ])
```
