### ISSUE TITLE
(apigatewayv2-integrations): Set SecureServerName with higher level HTTP API libraries

### ISSUE THREAD

**Issue by peterwoodworth** [aws/aws-cdk#14036]
I'd like to have the ability to set the SecureServerName for HTTP APIs with L2 or L3 constructs. Setting the SecureServerName through Cloudformation can be done through `AWS::ApiGatewayV2::Integration`'s property `TlsConfig`.

### Use Case

Functionality only exists in L1 construct, would like to be able to set SecureServerName using higher level libraries

### Proposed Solution

_tbd_

### Other

_Sourced from guidance issue_ #13673 

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by dan-lind** [comment]
@peterwoodworth Have you done any work on this yet? I saw that it's currently not even possible to set tlsConfig in the L2 construct in the apigatewayv2 package, and I was considering implementing that.

**Comment by peterwoodworth** [comment]
@dan-lind I haven't worked on this, and don't plan to do so soon. I'll be happy to take a look at a pr if you make one for this though, it shouldn't be too much trouble. Let me know if you need help with it

**Comment by dan-lind** [comment]
Hmm, besides what is there in `aws-apigatewayv2/test/http/api.test.ts` for default integrations, I cannot find any unit tests for what is defined in `aws-apigatewayv2/lib/http/integration.ts`. Am I looking in the wrong place? Where should I add unit tests for the `tlsConfig`?

**Comment by peterwoodworth** [comment]
Looks like this is where the tests for the integrations are: https://github.com/aws/aws-cdk/blob/b1ecd3d49d7ebf97a54a80d06779ef0f0b113c16/packages/%40aws-cdk/aws-apigateway/test/http.test.ts

**Comment by dan-lind** [comment]
Isn't that another package though? `aws-apigateway`, rather than `aws-apigatewayv2`

**Comment by peterwoodworth** [comment]
Ah you're right, that's my mistake. I didn't look closely enough 😅 Let me look again

**Comment by peterwoodworth** [comment]
It doesn't look like current tests exist, so if you're making changes to just the apigatewayv2 package then feel free to create your own test file!
