### ISSUE TITLE
elasticloadbalancingv2: logAccessLogs() switching away from a prefix 

### ISSUE THREAD

**Issue by fknittel** [aws/aws-cdk#14044]
`logAccessLogs()` does not actively unset a previously set log prefix, which causes the ELB to continue to use the old prefix.

And while the work-around is really easy to apply, getting to the point of understanding the need for the work-around was really time consuming. (The cloudformation / ALB error message is not as helpful as it could be.)

### Reproduction Steps

1. Assign bucket with a prefix: `applicationLoadBalancer.logAccessLogs(bucket, "some-log-prefix")`
2. Deploy.
3. Change code to assign bucket without a prefix: `applicationLoadBalancer.logAccessLogs(bucket)`
4. Deploy again.

### What did you expect to happen?

I expected the ALB to accept the new configuration and no longer use a path prefix during logging.

### What actually happened?

The deployment fails with the following error message:
`Access Denied for bucket: <BUCKET-NAME>. Please check S3bucket permission (Service:
 AmazonElasticLoadBalancing; Status Code: 400; Error Code: InvalidConfigurationRequest; Request ID: <...>; Proxy: null)`

This is due to the ALB still using the prefix, combined with the tight resource path permissions on the target bucket.

### Environment
  - **CDK CLI Version  :** 1.95.1 (build ed2bbe6)
  - **Framework Version:** 1.95.1
  - **Language (Version):** Java

#### Workaround
The problem goes away if I explicitly call `logAccessLogs()` with an empty prefix:
```java
        applicationLoadBalancer.logAccessLogs(bucket, "")`
```
or manually set the prefix to an empty string:
```java
        applicationLoadBalancer.setAttribute("access_logs.s3.prefix", "");
```

#### Suggested fix
I would suggest moving this line

https://github.com/aws/aws-cdk/blob/3c03d878dd81454628545b1529691ac083862247/packages/%40aws-cdk/aws-elasticloadbalancingv2/lib/shared/base-load-balancer.ts#L250
above this line

https://github.com/aws/aws-cdk/blob/3c03d878dd81454628545b1529691ac083862247/packages/%40aws-cdk/aws-elasticloadbalancingv2/lib/shared/base-load-balancer.ts#L238

so that the intended state is explicitly enforced and overrides any potential previous state.

--- 

This is :bug: Bug Report

**Comment by njlynch** [comment]
Thanks for the report, and the proposed fix!

Ideally, CloudFormation would see that the attribute is no longer being included, and remove the attribute, but in this (and several other cases) it appears once an attribute is set, it must be explicitly un-set after. It looks like your proposed fix would do the job.
