### ISSUE TITLE
(aws-eks): FromClusterAttributes() functions requires parameters at synth time commonly available at deploy time

### ISSUE THREAD

**Issue by vgribok** [aws/aws-cdk#14058]
Finding an existing cluster via CDK `FromClusterAttributes()` may require several arguments, like VPC and OIDC provider id that are frequently available at deploy time.

### Reproduction Steps

```cs
var eksCluster = Cluster.FromClusterAttributes(this, "EksCluster", new ClusterAttributes
            {
                ClusterName = "my-cluster"
            };
```
Adding installation of AWS LB Controller and App Mesh Controller that involve creating service accounts, using OIDC and Helm result in
```
"Amazon.JSII.Runtime.JsiiException: "kubectlRole" is not defined, cannot issue kubectl commands against this cluster"
"Amazon.JSII.Runtime.JsiiException: "openIdConnectProvider" is not defined for this imported cluster"
"Amazon.JSII.Runtime.JsiiException: "vpc" is not defined for this imported cluster"
```
Running `aws eks describe-cluster --name clusterName` returns information on VPC, OIDC, but not a role suitable for kubectl mapped to "system:masters". The latter is understandable, but VPC and OIDC data may be (dare I say likely to be) accessible at deploy time and should be made optional for FromClusterAttributes()

### What did you expect to happen?
cdk synth should not fail if vpc and OpenIdConnectProvider arguments are not supplied to Cluster.FromClusterAttributes() even if subsequent EKS stack operations require them. diff/deploy should fail only if vpc and OpenIdConnectProvider are not supplied and "aws eks describe-cluster --name clustername" or its equivalent API call does not return required data.

Install AWS LB Controller, AWS App Mesh Controller and App Mesh Ingress Gateway on an existing EKS cluster without having to dig for cluster information accessible to the stack at deploy time.

### What actually happened?
I had to create an (imperative) script returning data that is then fed to "cdk deploy -c" (declarative) stack, while I should not be required to do the boilerplate step that could be performed by the stack itself. I also had to add three outputs to another EKS cluster creating stack to supply this information.

"Amazon.JSII.Runtime.JsiiException: "openIdConnectProvider" is not defined for this imported cluster"
"Amazon.JSII.Runtime.JsiiException: "vpc" is not defined for this imported cluster"

### Environment

  - **CDK CLI Version  : 1.92.0**
  - **Framework Version: 1.92.0**
  - **Node.js Version: v15.5.0** 
  - **OS               : Windows 10 20H2**
  - **Language (Version): all** 

### Other

Related to https://github.com/aws/aws-cdk/issues/12468

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment]
@vgribok The `fromClusterAttributes` method is intentionally not designed to perform live queries, it is simply a way to create type-safe objects from well known static values. 

What you are referring to is called [context lookups](https://docs.aws.amazon.com/cdk/latest/guide/context.html#context_methods). And we actually already have a [feature request](https://github.com/aws/aws-cdk/issues/7825) to add a `Cluster.fromLookup` method, similarly to how we do [VPC Lookups](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ec2.Vpc.html#static-fromwbrlookupscope-id-options).
