### ISSUE TITLE
(secretsmanager): RDS_DB_CLUSTER/INSTANCE is not available as an attachment type

### ISSUE THREAD

**Issue by quixoticmonk** [aws/aws-cdk#14059]
### Description of the bug:
Python documentation for SecretAttachmentTargetProps refers to using "AttachmentTargetType" as target_type object value. The available values are 
- CLUSTER
- REDSHIFT_CLUSTER
- DOCDB_DB_CLUSTER

CLUSTER is marked as deprecated and is recommended to use RDS_DB_CLUSTER which is unavailable in the selections.

![Screen Shot 2021-04-08 at 2 34 30 PM](https://user-images.githubusercontent.com/11953035/114078907-88e26280-9877-11eb-8f22-6de54d5cb330.png)
![Screen Shot 2021-04-08 at 2 34 50 PM](https://user-images.githubusercontent.com/11953035/114078966-9697e800-9877-11eb-8d2e-d27e3f6d7c90.png)

### Reproduction Steps

- Create a DatabaseSecret entity
- Attempt to attach a cluster endpoint with the secret created
- Reference the SecretAttachmentTargetProps which has a target_type argument.
- Try to bring up the available selections of the target type from secretsmanager.AttachmentTargetType

### What did you expect to happen?
Expected the recommended selection to be present as the targettype

### What actually happened?
The deprecated value is present , but the recommended value is not.

### Environment

  - **CDK CLI Version  :** 1.96.0
  - **Node.js Version:** 10.24
  - **OS               :** Linux ( Cloud9)
  - **Language (Version):** Python 3.9

--- 

This is :bug: Bug Report

**Comment by njlynch** [comment]
Thanks for the bug report, @quixoticmonk .

This looks to be an issue with our underlying multi-language framework, `jsii`. I've filed a bug there (https://github.com/aws/jsii/issues/2782) to track the fix.

In the meantime, it's worth noting I think you don't actually need to reference this prop directly. To attach the db secret to your cluster should be as simple as this:

```python
_db_secret.attach(_cluster)
```

The RDS Cluster class implements the `ISecretAttachmentTarget` interface, so you don't need to hand-craft the target yourself.

**Comment by quixoticmonk** [comment]
Aah. Thank you. I will try that as well.

**Comment by peterwoodworth** [comment]
Closing in favor of #16443
