### ISSUE TITLE
(Secrets Manager): Add Replicate Secret Functionality

### ISSUE THREAD

**Issue by dassowmd** [aws/aws-cdk#14061]
As a user, it would be very useful to be able to replicate a secret to multiple regions, similar to how this can be done in Cloudformation. 

### Use Case

Right now to replicate a secret we have a separate process in our pipeline to replicate using boto3. Adding this feature would make deployments simpler to manage

### Proposed Solution

Please add a ReplicaRegions parameter to the current aws_cdk.aws_secretsmanager.Secret constructor to be able to a list of aws regions

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by njlynch** [comment]
Thanks for the feature request!

Support for replication regions for secrets was added to CloudFormation in their v30.1.0 spec update, which went out in our 1.93.0 release (2021-03-11). Until this functionality is bubbled up to `Secret`, you can use [escape hatches](https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html#cfn_layer_resource) to get at the underlying `CfnSecret` and add ReplicaRegions manually.

This would be a reasonably small addition, and I'd welcome working with someone to get a PR created and merged in for it. We'd want to create a new `ReplicaRegion` interface with a key (`kms.IKey`) and region parameter, and then extend the `SecretProps` to accept an array of `ReplicaRegion` as an optional prop.
