### ISSUE TITLE
(aws-eks): Cluster creation fails due to cfn-response

### ISSUE THREAD

**Issue by Marakai** [aws/aws-cdk#14069]
### Issue:

Creation of minimal EKS cluster fails due to time-out of stack creation. The cluster is correctly created, but then the final steps don't finish. The error is

### Reproduction Steps

```
from aws_cdk import \
    (
    core as cdk,
    aws_ec2 as ec2,
    aws_eks as eks,
    aws_iam as iam,
)


class ClustercdkStack(cdk.Stack):

    def __init__(self, scope: cdk.Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        vpc = ec2.Vpc(self, 'EKSVpc',
            subnet_configuration = [
                ec2.SubnetConfiguration(
                    subnet_type=ec2.SubnetType.ISOLATED,
                    name='EKS',
                    cidr_mask=21
                ),
            ])

      
        cluster_admin = iam.Role(
            self, 'ClusterAdmin',
            assumed_by=iam.AccountRootPrincipal(),
            role_name='eks_cdk_admin'
        )

        eks_cluster = eks.Cluster(self, 'EKSCluster',
                                  vpc=vpc,
                                  cluster_name='cdkcluster',
                                  default_capacity=0,
                                  vpc_subnets=vpc.select_subnets(subnet_type=ec2.SubnetType.ISOLATED,
                                                                     one_per_az=True).subnets,
                                  default_capacity_type=eks.DefaultCapacityType.NODEGROUP,
                                  endpoint_access=eks.EndpointAccess.PRIVATE,
                                  version=eks.KubernetesVersion.V1_19,
                                  masters_role=cluster_admin
                                  )

```

Create a simple Python CDK app, use code above and deploy the usual way (bootstrap/synth/deploy)

### What did you expect to happen?

Stack should complete with deployed cluster.

### What actually happened?

In step 'EKSClusterAwsAuthmanifest<randomID> I receive

```CloudFormation did not receive a response from your Custom Resource. Please check your logs for requestId [5a9c5fbd-6d88-452e-ad77-eafe92992b41]. If you are using the Python cfn-response module, you may need to update your Lambda function code so that CloudFormation can attach the updated version.```

This is documented to occur due to outdated lambda function - which I have no control over in this context, as it's generated somewhere in the bowels of CDK, isn't it?

### Environment

  - **CDK CLI Version  :** 1.97.0
  - **Framework Version:**
  - **Node.js Version:** 14.6.1
  - **OS               :** MacOS Big Sur 11.2.3
  - **Language (Version):** Python 3.9.2

### Other

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment]
@Marakai Unfortunately there is currently a limitation around creating clusters in isolated VPCs. 

See https://github.com/aws/aws-cdk/issues/12171 for some more detail.

**Comment by Marakai** [comment]
I see. Thanks. I'll keep an eye on updates and will work around it for now.

**Comment by guybagi435** [comment]
@Marakai did you manage to solve the issue? 
I'm currently struggling with the same exact issue.
