### ISSUE TITLE
(elasticsearch): DomainProps.advancedOptions has no effect (doesn't actually set AdvancedOptions)

### ISSUE THREAD

**Issue by ran-arigur** [aws/aws-cdk#14067]
DomainProps has an 'advancedOptions' field [[code](https://github.com/aws/aws-cdk/blob/63923ff431afdc031ee27a0fc9a99ffe4eb14405/packages/%40aws-cdk/aws-elasticsearch/lib/domain.ts#L407-L412)] [[doc](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-elasticsearch.DomainProps.html#advancedoptions)]:

```
  /**
   * Additional options to specify for the Amazon ES domain.
   *
   * @default - no advanced options are specified
   */
  readonly advancedOptions?: { [key: string]: (string) };
```

However, this field doesn't seem to be used anywhere. [[code search](https://github.com/aws/aws-cdk/search?q=advancedOptions)]

In particular, it's not used to set the 'AdvancedOptions' field in CloudFormation's AWS::Elasticsearch::Domain resource [[doc](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticsearch-domain.html)], which was surely the intent.

### Reproduction Steps

- Take any CDK code that uses the 'Domain' class to create an Elasticsearch domain.
- Add the 'advancedOptions' field, which is a map from string keys to string values, containing whatever mappings strike your fancy.
    - The "Advanced Options" section at https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-createupdatedomains.html#es-createdomain-configure-advanced-options lists the ones that Amazon Elasticsearch Service currently supports, though I think that other mappings might still be accepted as no-ops.
- Execute the CDK code to obtain the generated CloudFormation template.
- [optional] Deploy the CloudFormation template to create the actual Elasticsearch domain.

### What did you expect to happen?

- The generated CloudFormation template should include an 'AdvancedOptions' field with the specified mappings.
- The resultant Elasticsearch domain should have the specified advanced options.

### What actually happened?

- The generated CloudFormation template does *not* have an 'AdvancedOptions' field, and more generally, the 'advancedOptions' field seems to have no effect on the generated CloudFormation template. (I confirmed this via `diff -r`.)
- The resultant Elasticsearch domain does *not* have the specified advanced options, and more generally, the 'advancedOptions' field has no effect on the resultant Elasticsearch domain.

### Environment

- cdk 1.96.0
- TypeScript ~4.0.5

### Other

N/A

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment]
Thanks @ran-arigur - quite an embracing oversight. We'll address it.
