### ISSUE TITLE
Java: Provide a Bill of Materials (BOM) for CDK dependencies

### ISSUE THREAD

**Issue by digitalsanctum** [aws/aws-cdk#1406]
To ease Maven dependency management, provide a BOM for the CDK dependencies.

**Comment by eladb** [comment]
Accidental reference of this issue

**Comment by drissamri** [comment]
I would love to see this one!

**Comment by rix0rrr** [comment]
I'm not quite sure what the request is here. If you are looking for a complete set of transitive dependencies, Maven can generate that for you:

```
mvn dependency:tree -Dverbose=true
```

If you mean something else, then would you mind clarifying what it is you need that Maven cannot give you? (in a new issue)
