### ISSUE TITLE
(aws-kinesis): Implement L2 construct for StreamConsumer resource

### ISSUE THREAD

**Issue by peterwoodworth** [aws/aws-cdk#14062]
`@aws-cdk/aws-kinesis` currently has an L2 construct for `Stream` but not for `StreamResource`. It would be helpful to have a `StreamResource` L2 construct with methods that grant proper permissions for the most common ways customers use [Enhanced Fanout](https://docs.aws.amazon.com/streams/latest/dev/enhanced-consumers.html), which is most commonly implemented by customers through the [KCL](https://github.com/awslabs/amazon-kinesis-client) or Lambda.

When using the KCL the required permissions will be `kinesis:SubscribeToShard` on the `StreamConsumer`, `kinesis:DescribeStreamSummary` and `kinesis:ListShards` on the `Stream`.

When using Lambda a policy document can be consumed: `arn:aws:iam::aws:policy/service-role/AWSLambdaKinesisExecutionRole` which has the following permissions for Kinesis: `kinesis:DescribeStream`, `kinesis:DescribeStreamSummary`, `kinesis:GetRecords`, `kinesis:GetShardIterator`, `kinesis:ListShards`, `kinesis:ListStreams` and `kinesis:SubscribeToShard`

### Use Case

Kinesis features a L2 `Stream` resource already, it would be nice to have an L2 `StreamConsumer` resource that can grant permissions similarly to the L2 `Stream` resource.

### Proposed Solution

Proposed construct creation: 
```ts
// create the stream
const stream = new kinesis.Stream(this, 'Stream', {})
// register the consumer with this stream
const consumer = new kinesis.Consumer(this, 'Consumer', { stream });
```
Possible methods to grant proper permissions:
```ts
consumer.grantReadKCL()
consumer.grantReadLambda()
```

### Other

_sourced from guidance issue_ #13067

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by jrbarnard** [comment]
Is it possible to re open this?
