### ISSUE TITLE
(aws-events): EventBus.fromEventBusName should exist

### ISSUE THREAD

**Issue by vkamzn** [aws/aws-cdk#14072]
This fix: https://github.com/aws/aws-cdk/commit/57e540432c1446f2233a9b0c0f4caba4e9e155d9 makes eventBusArn effectively a required attribute. It used to be possible to import event bus by name if arn was not known. This is no longer possible.

### Reproduction Steps

```
const bus = EventBus.fromEventBusAttributes(scope, "DefaultEventBus", {
    eventBusName: "default",
    eventBusPolicy: "",
    eventBusArn: ""
});
```

### What did you expect to happen?

EventBus to be successfully imported, just like it did until and including version 1.92.0

### What actually happened?
Failure with the following stacktrace:
```
Error: ARNs must start with "arn:" and have at least 6 components:
    at parseArnShape (/workplace/(redacted)/node_modules/monocdk/lib/core/lib/arn.js:228:15)
    at Function.parse (/workplace/(redacted)/node_modules/monocdk/lib/core/lib/arn.js:83:28)
    at XXXXXRedactedXXXXX.parseArn (/workplace/(redacted)/node_modules/monocdk/lib/core/lib/stack.js:357:26)
    at new ImportedEventBus (/workplace/(redacted)/node_modules/monocdk/lib/aws-events/lib/event-bus.js:161:49)
    at Function.fromEventBusAttributes (/workplace/(redacted)/node_modules/monocdk/lib/aws-events/lib/event-bus.js:92:16)
	(the rest is redacted)
Subprocess exited with error 1
```

### Environment

  - **Framework Version: 1.93.0**
  - **Node.js Version: 12** 
  - **OS               : Amazon Linux 2; x86_64**
  - **Language (Version): TypeScript (3.9.7)** 

### Other

The original fix makes sense, but it introduces arn parsing into constructor, which is common code. The constructor is used by both EventBus.fromEventBusArn(...) and EventBus.fromEventBusAttributes(...). The fix makes sense for the former, but breaks the latter. 

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
I would say that if `eventBusArn` was a required parameter, the fact that you were able to get away with passing an empty string is an accident. If we had **intended** for `eventBusArn` to be optional, we would have made it an optional argument.

----

To get around your current issue: you can just construct an ARN given only the name. Something like:

```
eventBusArn: `arn:aws:events:${Stack.of(this).region}:${Stack.of(this).account}:event-bus/${eventBusName}`
```

Would do it.

----

This is a feature request for an `EventBus.fromEventBusName()` function that does the above for you automatically.
