### ISSUE TITLE
(aws-core): Reuse built assets

### ISSUE THREAD

**Issue by laimonassutkus** [aws/aws-cdk#14075]
### The Question

Once I run something like `cdk deploy "*"` AWS CDK firstly builds all assets (e.g. Lambda Layer) with docker (if specified so), creates `cdk.out` directory, and lastly sequently deploys to CloudFormation. 

Is there a possibility to ask AWS CDK to reuse built assets from a previous execution - something like `cdk deploy "*" --reuse-assets`

(I think that the. `-E, --build-exclude` option somehow can be used but I am not sure whether its the right one and the documentation is very minimal).

**The general problem that I have is:**
Building lambda layers with docker (installing various dependencies, etc.) is not only time-demanding but also very memory-demanding, hence parallel stack deployments become very very very memory-demanding. If I could build assets once and reuse them in my parallel deployments I would save time and memory.

### Environment

Not relevant.

**Comment by laimonassutkus** [comment]
Hey, guys @rix0rrr, @eladb, any possible answer?

**Comment by eladb** [comment]
@jogold would you be able to chime in?

**Comment by hoegertn** [comment]
I think this should already work if you call `cdk synth` once and then deploy all your stacks using the generated cloud assembly: `cdk deploy -a cdk.out <stackName>`.

For Docker, it should only build once per asset as the local docker daemon should cache the result.

Or am I missing something here?

**Comment by laimonassutkus** [comment]
@hoegertn, interesting approach, did not know you can do that this way. Doesn't the `-a` flag tell to deploy all of the stacks?

**Comment by hoegertn** [comment]
No, it overrides the app definition and tells CDK to deploy the assembly directly without synth:

I wrote a blog post about deployments here:
https://taimos.de/blog/deploying-your-cdk-app-to-different-stages-and-environments

**Comment by laimonassutkus** [comment]
@hoegertn you are a life-saver. 
Now I can proudly present an **efficient** and **practical** AWS CDK deployment tool that deploys stacks in parallel: https://github.com/Biomapas/B.AwsCdkParallel. You should definitely check it out and even maybe write a blog post about it ;)
