### ISSUE TITLE
How to associate an existing lambda function with a Cloudfront Behavior

### ISSUE THREAD

**Issue by wasitim** [aws/aws-cdk#14087]
### The Question

I can't find any way to associate an existing lambda function with a Cloudfront Behavior. 
I've opened a ticket with tech support but they told me the CDK isn't supported and to bring my question here.

I've tried different ways of getting a handle to the Function. 
I've found some write-ups where others have struggled and suggested I needed to create a new Version as in the commented out code below.

```
 const edgeFunction = Function.fromFunctionArn(this, "edgeFunction", props.edgeFunctionArn) as Function;
    // const edgeFunctionVerion = new Version(this, "EdgeFunctionVersion", {
    //   lambda: edgeFunction
    // })
```
That gives and error: 
`A version for this Lambda function exists ( 2 ). Modify the function to create a new version.`

Trying to associate this way with the edgeFunction reference above:
```
              lambdaFunctionAssociations: [
                {
                  eventType: LambdaEdgeEventType.VIEWER_REQUEST,
                  lambdaFunction: Version.fromVersionArn(this, "sdf", edgeFunction.functionArn),
                  includeBody: true,
                }
              ]
```
Returns:
```
A version for this Lambda function exists ( 2 ). Modify the function to create a new version.

        new Version (/Users/tim/projects/ae/ae-infrastructure/ae-cloudfront-stack/node_modules/@aws-cdk/aws-lambda/lib/lambda-version.ts:187:21)
        \_ new AeCloudfrontStack (/Users/tim/projects/ae/ae-infrastructure/ae-cloudfront-stack/lib/ae-cloudfront-stack.ts:79:32)
        \_ Object.<anonymous> (/Users/tim/projects/ae/ae-infrastructure/ae-cloudfront-stack/bin/ae-cloudfront-app.ts:26:1)
        \_ Module._compile (internal/modules/cjs/loader.js:1201:30)
        \_ Module.m._compile (/Users/tim/projects/ae/ae-infrastructure/ae-cloudfront-stack/node_modules/ts-node/src/index.ts:1056:23)
        \_ Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
```

Trying with latestVersion:
```
lambdaFunctionAssociations: [
                {
                  eventType: LambdaEdgeEventType.VIEWER_REQUEST,
                  lambdaFunction: edgeFunction.latestVersion,
                  includeBody: true,
                }
              ]
```
Returns:
```
$LATEST function version cannot be used for Lambda@Edge
Subprocess exited with error 1
```

Trying with currentVersion:
```
lambdaFunctionAssociations: [
                {
                  eventType: LambdaEdgeEventType.VIEWER_REQUEST,
                  lambdaFunction: edgeFunction.currentVersion,
                  includeBody: true,
                }
              ]
```
Returns:
```
Cannot read property 'role' of undefined
Subprocess exited with error 1
```

This seems like it should be pretty simple. 

### Environment

  - **CDK CLI Version:**  1.97.0 (build c52c2dc)
  - **Module Version:** 
  - **Node.js Version:**  v14.5.0
  - **OS:**  macOS Catalina
  - **Language (Version):**  Typescript 4.1.2

**Comment by njlynch** [comment]
Lambda@Edge requires a specific version (not $LATEST). If you already have the function defined elsewhere, you can directly use the *version* ARN (the function ARN with the version appended to the end):

```ts
              lambdaFunctionAssociations: [
                {
                  eventType: LambdaEdgeEventType.VIEWER_REQUEST,
                  lambdaFunction: lambda.Version.fromVersionArn(this, "sdf", "arn:aws:lambda:us-east-2:123456789012:function:my-function:1"),
                  includeBody: true,
                }
              ]
```

**Comment by wasitim** [comment]
Interesting,

The lambda is built and deployed in a cdk constructed pipeline. 

There's no way to get this all to "play nice" in the cicd context? 

If I'm reading things correctly, it seems like we'd have to come into the Cloudfront stack and manually update the arn with the version string and deploy manually?

**Comment by njlynch** [comment]
If you have a reference to the function, just use `function.currentVersion`. I mentioned importing by ARN because that's what was in your examples. If you are referencing the function cross-region, take a look at the experimental [`EdgeLambda`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cloudfront.EdgeLambda.html) construct.

**Comment by wasitim** [comment]
Thanks for the follow-up Nick.

As you can see in the last example in my OP, using .currentVersion throws this error:

```
Cannot read property 'role' of undefined
Subprocess exited with error 1
```

**Comment by wasitim** [comment]
@njlynch , 
Any idea on how to get around the issue above?

**Comment by wasitim** [comment]
Checking to see if there are any further comments on this issue. 
The function is defined as and EdgeLambda construct and deploying using function.currentVersion approach throws the "role" error above.

**Comment by njlynch** [comment]
Can you share more of your code? 

This line is problematic:
```ts
 const edgeFunction = Function.fromFunctionArn(this, "edgeFunction", props.edgeFunctionArn) as Function;
```

You're taking an `IFunction` and casting it to `Function`, which isn't necessarily correct (and in this case isn't correct). That's likely (one of) the cause(s) of the errors.

> The function is defined as and EdgeLambda construct and deploying using function.currentVersion approach throws the "role" error above.

Here's an example of an EdgeLambda construct being used with a CloudFront distribution (from the package README).

```ts
const myFunc = new cloudfront.experimental.EdgeFunction(this, 'MyFunction', {
  runtime: lambda.Runtime.NODEJS_12_X,
  handler: 'index.handler',
  code: lambda.Code.fromAsset(path.join(__dirname, 'lambda-handler')),
});
new cloudfront.Distribution(this, 'myDist', {
  defaultBehavior: {
    origin: new origins.S3Origin(myBucket),
    edgeLambdas: [
      {
        functionVersion: myFunc.currentVersion,
        eventType: cloudfront.LambdaEdgeEventType.VIEWER_REQUEST,
      }
    ],
  },
});
```

The above is known to work. If you can share more about what you're doing that's different from the above, maybe we can help. Ideally, a trimmed-down, reproducible example.

**Comment by wasitim** [comment]
Yeah, I think the difficulty is in getting the reference to the EdgeFunction defined in another stack.

```
DEFINED IN STACK A

    const edgeLambda = new EdgeFunction(this, "EdgeLambdaFunction", {
        code: this.lambdaCode,
        functionName: `${props.deployEnvironmentName}-AeAuthApiLambda`,
        handler: "api.handler",
        runtime: Runtime.NODEJS_12_X, // LambdaEdge doesn't support 14.x
        memorySize: 128,
        timeout: Duration.seconds(5),
        role: lambdaRole,
    });

DEFINED IN STACK B
    
    What is the correct way to get this reference?
    const edgeFunction = Function.fromFunctionArn(this, "edgeFunction", props.edgeFunctionArn) as Function;
    // edgeFunction.currentVersion.functionArn
    // const version = Version.fromVersionArn(this, "edgeFunctionVersion", edgeFunction.functionArn);
    // const edgeFunctionVerion = new Version(this, "EdgeFunctionVersion", {
    //   lambda: edgeFunction
    // })

  const cloudFrontWebDistribution = new CloudFrontWebDistribution(this, "Distribution", {
      originConfigs: [
        {
          s3OriginSource: {
            s3BucketSource: deployBucket,
            originAccessIdentity,
          },

          behaviors : [
            {
              pathPattern: "index.html",
              minTtl: Duration.seconds(0),
              maxTtl: Duration.seconds(0),
              defaultTtl: Duration.seconds(0),
              allowedMethods: CloudFrontAllowedMethods.GET_HEAD
            },
            {
              isDefaultBehavior: true,
              minTtl: Duration.seconds(0),
              allowedMethods: CloudFrontAllowedMethods.GET_HEAD_OPTIONS,
              forwardedValues: {queryString: true}
            }
          ]
        },
        {
          customOriginSource: {
            domainName: props.dahApiDomainName,
            originProtocolPolicy: OriginProtocolPolicy.HTTPS_ONLY,
            httpsPort: 443,
          },
          originPath: "/prod",
          behaviors: [
            {
              pathPattern: "/digital-asset-handler/api/*", 
              forwardedValues: { queryString: true, headers: ['Accept', 'Authorization', 'Origin', 'Referer'], cookies: { forward: "all" } },
              allowedMethods: CloudFrontAllowedMethods.ALL,
              cachedMethods: CloudFrontAllowedCachedMethods.GET_HEAD_OPTIONS,
              compress: true,
              // lambdaFunctionAssociations: [
              //   {
              //     eventType: LambdaEdgeEventType.VIEWER_REQUEST,
              //     lambdaFunction: edgeFunction.currentVersion,
              //     includeBody: true,
              //   }
              // ]
            }
          ]
        }  ]})


```

**Comment by njlynch** [comment]
You can directly pass a reference to the function (i.e., have `props.function` instead of `props.functionArn`). Or, you can ensure the ARN you pass references a version instead of the function, and then import the Version (`this.versionArn = function.currentVersion.edgeArn` and `const functionVersion = lambda.Version.fromVersionArn(...)`).

**Comment by peterwoodworth** [comment]
Hey @wasitim, did the above advice help you out?
