### ISSUE TITLE
(custom-resources): broken usage of list tokens in parameters

### ISSUE THREAD

**Issue by MrArnoldPalmer** [aws/aws-cdk#14088]
Referencing a token that is a list of strings within a custom resource parameters object results in a reference to an undefined parameter.

### Reproduction Steps

<details><summary>Reproduction App</summary>
<p>

```typescript
import * as cdk from '@aws-cdk/core';
import * as ec2 from '@aws-cdk/aws-ec2';
import * as cr from '@aws-cdk/custom-resources';

export class BadrefStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const vpc = new ec2.Vpc(this, 'MyVpc');

    const vpce = new ec2.InterfaceVpcEndpoint(this, 'MyVpcEndpoint', {
      vpc,
      service: {
        name: 'com.amazonaws.us-east-1.execute-api',
        port: 443
      }
    });

    const policy = cr.AwsCustomResourcePolicy.fromSdkCalls({
      resources: cr.AwsCustomResourcePolicy.ANY_RESOURCE,
    });

    new cr.AwsCustomResource(this, 'GetEdnpointIp', {
      policy,
      onUpdate: {
        service: 'EC2',
        action: 'DescribeNetworkInterfaces',
        outputPath: 'NetworkInterfaces.${index}.PrivateIpAddress',
        parameters: {
          // NetworkInterfaceIds: vpce.vpcEndpointNetworkInterfaceIds,
          NetworkInterfaceIds: [cdk.Token.asList(cdk.Stack.of(this).toJsonString(cdk.Fn.join('","', vpce.vpcEndpointNetworkInterfaceIds)))]
        },
        physicalResourceId: cr.PhysicalResourceId.of('resourceid'),
      }
    });
  }
}

```

</p>
</details>

### What did you expect to happen?

Deploys the app to cloudformation with the CR having access to the vpce network interface IDs as json.

### What actually happened?

`cdk deploy` results in
```
Template error: instance of Fn::GetAtt references undefined resource CdkJsonStringify3
```

### Environment

  - **CDK CLI Version  :** 1.97.0
  - **Framework Version:** 1.97.0
  - **Node.js Version:**  14.15.4
  - **OS               :** MacOS
  - **Language (Version):**  all

### Other

Related to some recent changes:
https://github.com/aws/aws-cdk/issues/13465
https://github.com/aws/aws-cdk/pull/13544

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
Not sure what to make of the following:

```
          // NetworkInterfaceIds: vpce.vpcEndpointNetworkInterfaceIds,
          NetworkInterfaceIds: [cdk.Token.asList(cdk.Stack.of(this).toJsonString(cdk.Fn.join('","', vpce.vpcEndpointNetworkInterfaceIds)))]
```

Is the first one broken, the 2nd one a workaround?

```
[Token.asList(...)]
```

Is confusing me a little because it would end up as `[[ x, y, z]]` which seems not intended. At the same time, that shouldn't cause the error you're seeing.

**Comment by rix0rrr** [comment]
<3 on the repro though. Feature haz test but I can confirm this example fails. Hey-ho, a-digging we will go

**Comment by rix0rrr** [comment]
```
  CdkJsonStringify1:
    Type: Custom::AWSCDKCfnJsonStringify
    Properties:
```

```
            - Fn::GetAtt:
                - CdkJsonStringify3
                - Value
```

😳

Must be because of separate prepare/synth cycles.

🤬

**Comment by MrArnoldPalmer** [comment]
Oooh sorry, yeah the second one was an attempt at a workaround but both failed.
