### ISSUE TITLE
(@aws-cdk/aws-sam.CfnFunction): Support EventInvokeConfig property

### ISSUE THREAD

**Issue by naokimakino** [aws/aws-cdk#14096]
When I tried to recreate the existing sam template in cdk, I noticed that the eventInvokeconfig property that exists in

AWS::Serverless::Function is not in the @aws-cdk/aws-sam.CfnFunction.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by skinny85** [comment]
Thanks for opening the issue @naokimakino. We're tracking updating the SAM spec in https://github.com/aws/aws-cdk/issues/13507, please +1 that issue!
