### ISSUE TITLE
cfnspec: Revert patch on AWS::ServiceDiscovery::Instance.InstanceAttributes.PrimitiveType

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#1409]
We requested the primitive type to be fixed in the CFN spec source. Once that's done, we should be able to revert [this commit](https://github.com/awslabs/aws-cdk/pull/1407/commits/8086cd00887cf7c01b5e8c087af29446548e4d9c)

**Comment by SoManyHs** [comment]
@eladb What's the status of this? Wondering if it will affect #1804

**Comment by rix0rrr** [comment]
It probably shouldn't impact your PR. We patch the CloudFormation spec if the documentation disagrees with the published spec. You should not notice a difference downstream.
