### ISSUE TITLE
(aws-ecs-patterns): Allow ApplicationLoadBalanced*Service to pass in ProtocolVersion for HTTP2/GRPC support

### ISSUE THREAD

**Issue by yiluncui** [aws/aws-cdk#14091]
https://github.com/aws/aws-cdk/pull/13570 adds support for the ALB constructs to specify ProtocolVersion in target groups, but this parameter isn't passed into the ecs-patterns high level construct.

### Use Case

I want to create ALBs that support GRPC/HTTP2 protocols in their target groups using the ecs_patterns.ApplicationLoadBalanced___Service() pattern

### Proposed Solution

Propagate the ProtocolVersion parameter to AddApplicationTargetsProps and ApplicationLoadBalancedServiceBaseProps

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by SoManyHs** [comment]
Closed by https://github.com/aws/aws-cdk/pull/14092. Thanks @yiluncui ! ❤️
