### ISSUE TITLE
(cli): does not work in VPC with interface endpoints

### ISSUE THREAD

**Issue by dhruvdakoria** [aws/aws-cdk#14090]
Cross region deployment with 'cdk deploy' times out when run inside VPC with S3 interface endpoint. It times out when trying to upload assets to the staging bucket "cdktoolkit-staging-xxxx". S3 upload using CLI works cross-region in the same scenario.

It seems like there isn't a way to pass endpoint_url parameter in cdk deploy or aws-s3-assets class so that assets inside the template could be uploaded by passing s3 interface endpoint url of another region.

### Reproduction Steps

With a codebuild inside a VPC with no internet connectivity and interface endpoints configured for s3,cloudformation,sts to perform cross-region deployments.

"cdk deploy" passes cross-region deployment for cdk stacks without assets (ex. stacks without lambdas) - indicating endpoints working correctly.

"cdk deploy" gets stuck at uploading assets to staging bucket, when cdk stacks contains assets (ex. stacks with lambdas).

### What did you expect to happen?

Expecting cdk deploy to work with cross-region deployments inside VPC using interface endpoints. 

### What actually happened?

Gets stuck when there are assets (lambdas) in cdk code and it tries to upload them to a staging bucket in another region. S3 upload using CLI works cross-region.

```
aws s3 --endpoint-url https://bucket.vpce-1a2b3c4d-5e6f.s3.us-east-1.vpce.amazonaws.com cp ./xyz.txt s3://cdktoolkit-staging-xxx/
```

cdk deploy Output:

```
cdk-deployment-test-sbx01: deploying...
Waiting for stack CDKToolkit to finish creating or updating...
Preparing asset 252c7530b6cbdaac3b8afcf65856519a72e58ab5972a65bfbeec2b04274e595d: {"path":"asset.252c7530b6cbdaac3b8afcf65856519a72e58ab5972a65bfbeec2b04274e595d","id":"252c7530b6cbdaac3b8afcf65856519a72e58ab5972a65bfbeec2b04274e595d","packaging":"zip","sourceHash":"252c7530b6cbdaac3b8afcf65856519a72e58ab5972a65bfbeec2b04274e595d","s3BucketParameter":"AssetParameters252c7530b6cbdaac3b8afcf65856519a72e58ab5972a65bfbeec2b04274e595dS3Bucket110F952B","s3KeyParameter":"AssetParameters252c7530b6cbdaac3b8afcf65856519a72e58ab5972a65bfbeec2b04274e595dS3VersionKey35628DF5","artifactHashParameter":"AssetParameters252c7530b6cbdaac3b8afcf65856519a72e58ab5972a65bfbeec2b04274e595dArtifactHash18245D00"}
Storing asset asset.252c7530b6cbdaac3b8afcf65856519a72e58ab5972a65bfbeec2b04274e595d at s3://cdktoolkit-stagingbucket-nsgrj8sxxxx/assets/252c7530b6cbdaac3b8afcf65856519a72e58ab5972a65bfbeec2b04274e595d.zip
cdk-deployment-test-sbx01: checking if we can skip deploy
cdk-deployment-test-sbx01: template has changed
cdk-deployment-test-sbx01: deploying...
[0%] start: Publishing 252c7530b6cbdaac3b8afcf65856519a72e58ab5972a65bfbeec2b04274e595d:current
[0%] check: Check s3://cdktoolkit-stagingbucket-nsgrj8sxxxx/assets/252c7530b6cbdaac3b8afcf65856519a72e58ab5972a65bfbeec2b04274e595d.zip
```

### Environment

  - **CDK CLI Version  :*1.97.0*
  - **Framework Version:**
  - **Node.js Version:**  14.6.1
  - **OS               :** ubuntu
  - **Language (Version):**  TypeScript 4.2.4

### Other

https://github.com/aws/aws-cdk/blob/7966f8d48c4bff26beb22856d289f9d0c7e7081d/packages/cdk-assets/lib/private/handlers/files.ts

Adding endpoint_url property to assets may fix this issue.

https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-s3-assets.Asset.html
https://docs.aws.amazon.com/cdk/latest/guide/assets.html

--- 

This is :bug: Bug Report

**Comment by eladb** [comment]
Classified as a CLI issue

**Comment by rix0rrr** [comment]
The same probably applies to ECR and CloudFormation itself, right?

**Comment by suhaibchishti** [comment]
> The same probably applies to ECR and CloudFormation itself, right?

yes, as vpc endpoints don't support cross region. However for cloud formation this can be fixed by adding an entry in codebuild local host file and point it to vpc interface endpoint of another region.  Even this workaround doesn't work for resources that need asserts like lambda, as S3 upload timesout despite similar entry in host file for S3 vpc interface endpoint. This S3 vpc interface endpoint entry in host file solution works for aws cli with s3, it doesn't work with cdk deploy. 

```
- echo "10.160.40.xx cloudformation.us-east-1.amazonaws.com" >> /etc/hosts
- echo "10.160.40.xx sts.us-east-1.amazonaws.com" >> /etc/hosts
```
