### ISSUE TITLE
npx cdk synth errors with "Cannot find module 'constructs'"

### ISSUE THREAD

**Issue by jkodroff** [aws/aws-cdk#14102]
Given the following CDK Pipelines code:

```node
      synthAction: SimpleSynthAction.standardNpmSynth({
        sourceArtifact,
        cloudAssemblyArtifact,
        subdirectory: 'cdk',
        environment: {
          buildImage: LinuxBuildImage.STANDARD_5_0
        }
      }),
```

The above step errors in CodeBuild with the following message:

```bash
Cannot find module 'constructs'
Require stack:
- /Users/jkodroff/src/bcbsa-cdk-demo/cdk/node_modules/@aws-cdk/core/lib/annotations.js
- /Users/jkodroff/src/bcbsa-cdk-demo/cdk/node_modules/@aws-cdk/core/lib/tag-aspect.js
- /Users/jkodroff/src/bcbsa-cdk-demo/cdk/node_modules/@aws-cdk/core/lib/index.js
- /Users/jkodroff/src/bcbsa-cdk-demo/cdk/bin/cdk.ts
```

If I execute `cdk init --language TypeScript` under Node 15:
  - The directory `./node_modules/constructs/` **is not** present.
  - `cdk synth` works fine if executed under Node 15.
  - `cdk synth` fails with the above error if executed under Node 14 (locally via nvm or in CodeBuild).

If I execute `cdk init --language TypeScript` under Node 14:
  - The directory `./node_modules/constructs/` **is** present.
  - `cdk synth` works fine if executed under Node 14.

I'm using CDK 1.97.0 (build c52c2dc).  My CDK code is written in TypeScript.

I'm using the new style stack synthesis as well (`"@aws-cdk/core:newStyleStackSynthesis": true,`).  Other than that, I have not changed any defaults.

--- 

This is :bug: Bug Report

**Comment by jkodroff** [comment]
Workaround (your CDK app may require additional dependencies, depending on which features of CDK you're using - just `npm i` whatever `npx cdk synth` complains about not being able to find):

```bash
npm i constructs @aws-cdk/assets @aws-cdk/region-info
```

**Comment by rix0rrr** [comment]
I think this is probably an NPM6 vs NPM7 mismatch

**Comment by claraberendsen** [comment]
> I think this is probably an NPM6 vs NPM7 mismatch

Indeed moving from npm to yarn on the installCommands solved the problem for me.
