### ISSUE TITLE
aws-cloudfront: Distribution IAM Certificate Support

### ISSUE THREAD

**Issue by ssaarela** [aws/aws-cdk#14116]
IAM Certificate support for the new CloudFront Distribution construct.

### Use Case

Deploying to China requires IAM Certificate.

### Proposed Solution

An alternative for the DistributionProps.certificate property: 
```
DistributionProps.iamCertificateId?: string
```

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by njlynch** [comment]
Thanks for the feature request!

I had hoped to keep `Distribution` free and clear of the IAM certificate references, but if CloudFront China requires it, then we should certainly include it and make it easier to do so.

I agree, adding a `iamCertificateId` to `DistributionProps` makes sense, and then altering the `renderViewerCertificate` logic and where it's called makes sense:

https://github.com/aws/aws-cdk/blob/54fddc64c7b541f9192fb904fa9a3b44b8aacf90/packages/@aws-cdk/aws-cloudfront/lib/distribution.ts#L304

If you're interested in contributing the feature, I'd be happy to work with you to get it merged in. Let me know how I can help!
