### ISSUE TITLE
(@aws-cdk/aws-ec2): Attaching volume to EC2 results in circular dependency

### ISSUE THREAD

**Issue by stijnbrouwers** [aws/aws-cdk#14111]
link to reference doc page:
https://docs.aws.amazon.com/cdk/api/latest/docs/aws-ec2-readme.html#attaching-volumes

describe your issue:
When implementing the sample code from the aws-ec2 readme page for attaching volumes:
https://docs.aws.amazon.com/cdk/api/latest/docs/aws-ec2-readme.html#attaching-volumes
you will get a circular dependency when deploying the CDK stack. This is because in the creation of the EC2 instance, there is a reference to the instance we are creating itself. It comes from this line of code in the last block (instance.userData.addCommands):
```
`aws --region ${Stack.of(this).region} ec2 attach-volume --volume-id ${volume.volumeId} --instance-id ${instance.instanceId} --device ${targetDevice}`
```

where ```instance.instanceId``` is a reference to the instanceId of itself...

---
This is a 📕 documentation issue

**Comment by tom10271** [comment]
Is it a new bug? Just face it and wasted me ~2 hours figuring out what is wrong again in AWS CDK.

**Comment by stijnbrouwers** [comment]
@tom10271 
I have no idea, I used this for the first time last friday so I am just facing this now...

I do have a workaround though:

replace
```
instance.userData.addCommands(
  // Attach the volume to /dev/xvdz
  `aws --region ${Stack.of(this).region} ec2 attach-volume --volume-id ${volume.volumeId} --instance-id ${instance.instanceId} --device ${targetDevice}`,
  // Wait until the volume has attached
  `while ! test -e ${targetDevice}; do sleep 1; done`
  // The volume will now be mounted. You may have to add additional code to format the volume if it has not been prepared.
);
```
with
```
instance.userData.addCommands(
  //Retrieve the instance ID from the folder name in /var/lib/cloud/instances
  `InstanceID=$(ls /var/lib/cloud/instances)`,
  // Attach the volume to /dev/xvdz
  `aws --region ${Stack.of(this).region} ec2 attach-volume --volume-id ${volume.volumeId} --instance-id $InstanceID --device ${targetDevice}`,
  // Wait until the volume has attached
  `while ! test -e ${targetDevice}; do sleep 1; done`
  // The volume will now be mounted. You may have to add additional code to format the volume if it has not been prepared.
);
```

I don't know if there is a better way to do this, but you need to eliminate the need to provided the instance id in the CDK directly to avoid the circular dependency.
I noticed a directory that carries the ID of the instance and am using that for now...
I hope to trigger a discussion here to see if this is an acceptable way to solve it.

**Comment by tom10271** [comment]
@stijnbrouwers

Thank you very much for sharing your solution. Hope AWS can advise us in case we might further improve anything.

**Comment by stijnbrouwers** [comment]
Just an FYI, I also tried another route:

1. Add cloudformation:DescribeStackResources to the EC2 instance role.
2. Retrieve the Instance ID by running
```
`InstanceID=$(aws cloudformation describe-stack-resources --stack-name ${props.stackName} --region eu-west-1 --query "StackResources[?ResourceType=='AWS::EC2::Instance'] | [?ResourceStatus!='CREATE_COMPLETE'].PhysicalResourceId" --output text)`
```
This will retrieve the EC2 instance from the current stack and not the local folder in the EC2 instance. 
It will filter the cloudformation resources to only retrieve the EC2 instances where status != CREATE_COMPLETE. This is required when updating the stack because a new instance will be created before deleting the old one.
However, this seems more error prone than my previous solution because it will only work when the stack has a single instance, not with multiple instances...

**Comment by rix0rrr** [comment]
Thanks for reporting this!

We are open to better sample code here. Would retrieving the instance ID from IMDS be a good solution?

```
TOKEN=$(curl -SsfX PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")
instance_id=$(curl -SsfH "X-aws-ec2-metadata-token: $TOKEN" http://169.254.169.254/latest/meta-data/instance-id)
```

**Comment by rix0rrr** [comment]
Would ❤️ for someone to validate this and submit a PR with an updated example if that works.

**Comment by stijnbrouwers** [comment]
@rix0rrr 
Thx for the feedback.
I'll have a look at it sometime soon and see if it works.
If it does, I'll change the readme file of the aws-ec2 package accordingly and submit a PR.

**Comment by stijnbrouwers** [comment]
@rix0rrr 
I checked out your sample and it works like a charm!
I edited the documentation to reflect the change and submitted a PR (#14376).

**Comment by antonioarenzanapulido** [comment]
This really should be improved inside CDK, we should not have to make this workarounds
