### ISSUE TITLE
(Config): Add support for S3KmsKeyArn property to CfnDeliveryChannel

### ISSUE THREAD

**Issue by tvb** [aws/aws-cdk#14119]
In this `AWS::Config::DeliveryChannel` CloudFormation Resource, it has support for the [S3KmsKeyArn](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-config-deliverychannel.html#cfn-config-deliverychannel-s3kmskeyarn) property to encrypt objects delivered by AWS Config.

However, the[ CDK low-level equivalent](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_config/CfnDeliveryChannel.html) does not support this property yet.

### Use Case

Encrypt my Config logs with a Customer Managed KMS Key

### Proposed Solution

Implement support for the missing property

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by MrArnoldPalmer** [comment]
I don't see this defined in our current CFN spec so it may have been recently added. This should automatically be handled next time we update from the spec.

**Comment by tvb** [comment]
Gotcha! Ok, I am looking forward to it.

**Comment by MrArnoldPalmer** [comment]
Update, it is now in the latest spec as you can see [here](https://github.com/aws/aws-cdk/pull/14300/files#diff-db0dab61b544f58bb3162b9fd5e07d5b8450aff43a5b1f81415366e622c95991R61), but there are breakages that are preventing us from pulling it in. We are working to resolve these.
