### ISSUE TITLE
(aws-iam): unable to use new Lex service for custom resource

### ISSUE THREAD

**Issue by bpottier** [aws/aws-cdk#14122]
I'm trying to create a custom resource in order to manage a Lex bot but when I reference the "LexModelsV2" service I get the following error: "Error: Action 'models.lex.v2:CreateBot' is invalid. An action string consists of a service namespace, a colon, and the name of an action. Action names can include wildcards."

See: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/LexModelsV2.html#createBot-property

First time submitting an issue so I apologize if I don't have everything required.

```
export class LexBotResource extends cdk.Construct {
    constructor(scope: cdk.Stack, id: string, props: LexBotProps) {
        super(scope, id);
        new customresource.AwsCustomResource(this, id, {
            onCreate: {
                service: 'LexModelsV2',
                action: 'createBot',
                parameters: props.parameters,
                physicalResourceId: customresource.PhysicalResourceId.fromResponse('checksum'),
            },
            policy: customresource.AwsCustomResourcePolicy.fromSdkCalls({ resources: customresource.AwsCustomResourcePolicy.ANY_RESOURCE })
        });
    }
}
```

### Environment

  - **CDK CLI Version  :** 1.98.0 (build 79f4512)
  - **Framework Version:** 1.98.0
  - **Node.js Version:** v15.13.0
  - **OS               :** macOS 11.2.3
  - **Language (Version):** TypeScript 4.1.3

--- 

This is :bug: Bug Report

**Comment by jogold** [comment]
Looks like the `AwsCustomResource` fails to correctly determine the right action from this specific SDK call.

You can do:

```ts
policy: AwsCustomResourcePolicy.fromStatements([
  new iam.PolicyStatement({
    actions: ['lex:CreateBot'],
    resources: ['*'],
  }),
]),
```

**Comment by bpottier** [comment]
That worked. Thank you. Now I just need to wrangle Lex into working with CDK.
