### ISSUE TITLE
cdk-core: bootstrapping and later consumption do not appear to work correctly as documented

### ISSUE THREAD

**Issue by roskelleycj** [aws/aws-cdk#14121]
https://docs.aws.amazon.com/cdk/latest/guide/bootstrapping.html

See `The bootstrapping template contract`

Question:
--
How does one configure the 'BucketName' for the DefaultStackSynthesizer if a custom bucket name was selected during the CDK bootstrapping process?

According to the documentation it says this:

```
The AWS CDK Toolkit requires that the following CloudFormation outputs exist on the bootstrap stack.

    * BucketName: the name of the file asset bucket

    * BucketDomainName: the file asset bucket in domain name format

```

So if one has a CDK Bootstrap using a custom bucket name than everything should work just fine.  However, when I run CDK deploy with the following configuration it does not work.  And presents an error indicating that the bucket (using the NON customized name) does not exist. 

```
npx cdk deploy \
      --context "@aws-cdk/core:bootstrapQualifier=adhoc-v1" \
      --context "@aws-cdk/core:newStyleStackSynthesis=true" \
      --toolkit-stack-name=adhoc-cdk-bootstrap-adhoc-v1 \

```

And this is the error that is presented:

```
fail: No bucket named 'cdk-adhoc-v1-assets-XXXXXXXXXXX-us-east-1'. Is account XXXXXXXXXXX bootstrapped?
```

The custom bucket name is `adhoc-cdk-adhoc-v1-assets-XXXXXXXXXXX-us-east-1` and if the toolkit stack was consulted for the `BucketName` as documented this would be the bucket name that is returned.  However, there does not appear to be a means to 'configure'.

Additionally, I found, through debug logs, that this property `toolkitBucket` exists and appears to match the need so I configured in this manner in the cdk.json

```
toolkitBucket: { bucketName: 'adhoc-cdk-adhoc-v1-assets-XXXXXXXXXXX-us-east-1' }
```

However, it has absolutely no effect.  Reporting the same error message as previously.  Research appears to indicate that this is the property one sets to make a custom bucket name.  I do find it interesting that toolkitStackName is also the property used to name the bootstrap stack along with the qualifier.  In other words CDK deploy allows --toolkit-stack-name to be specified, but it does not appear that --toolkit-bucket-name can be specified.  Etc.

So this returns me to the first question:  How does one configure the custom bucket name for CDK Deploy when a custom bucket name was used during the bootstrap process?

### Found a work around

I found the following workaround, but it is not a very acceptable solution.  Is this the only means for making it work?

I had to override the following Stack method:
```
  public  IStackSynthesizer getSynthesizer()
```

And in this method I constructed a DefaultStackSynthesizer and bound that to the Stack.

```
    DefaultStackSynthesizerProps props = new DefaultStackSynthesizerProps.Builder()
        .fileAssetsBucketName("adhoc-cdk-${Qualifier}-assets-${AWS::AccountId}-${AWS::Region}")
        .build();
    DefaultStackSynthesizer defaultStackSynthesizer = new DefaultStackSynthesizer(props);

    defaultStackSynthesizer.bind(this);

```

Again this worked.  However, it was not entirely expected.  Either the documentation is missing this step OR the documentation is missing the intentional design for configuration during execution OR this is a bug in the software.  As noted I've approached this as a documentation issue.  Please advise if this is likely a software issue and I will add a new issue describing the versions/etc.

---

This is a 📕 documentation issue

**Comment by rix0rrr** [comment]
That kind of customization is supposed to happen by passing arguments to the `DefaultStackSynthesizer`, that is correct. You are supposed to pass one to every `Stack` you instantiate. This is described here:

https://docs.aws.amazon.com/cdk/latest/guide/bootstrapping.html#bootstrapping-custom-synth

**Comment by roskelleycj** [comment]
Thank you for helping me see the error in my understanding.  This was the key:
```
All the other DefaultStackSynthesizer properties relate to the names of the resources in the modern bootstrapping template. You only need to provide any of these properties if you modified the bootstrap template and changed the resource names or naming scheme. 
```

I.e., `All` means all.  And I was not totally understanding that.  I will correct my understanding.  Thank you.
