### ISSUE TITLE
(apigateway): support integration timeout

### ISSUE THREAD

**Issue by Samrose-Ahmed** [aws/aws-cdk#14123]
API gateway lets you specify a timeout for integrations. This is available in CloudFormation (see [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apitgateway-method-integration.html#cfn-apigateway-method-integration-timeoutinmillis)). However, this isn't available when using RestApi construct.

### Reproduction Steps

Create any `RestApi` with an integration, can't specify the timeout directly.

### What did you expect to happen?

To be able to specify a custom timeout.

### What actually happened?

Default timeout used.

Can use overrides to achieve (see [here](https://play-with-cdk.com/?s=8a4ae926b2acd896488533f2c96d539f)), but should be directly available:

```typescript
const api = new apig.RestApi(this, "MyRestApi");
const httpIntegration = new apig.HttpIntegration("https://example.com");
const proxy = api.root.addProxy({
   defaultIntegration: httpIntegration,
   anyMethod: true,
});
// Override the timeout on integration since CDK doesn't expose property.
const anyMethod = proxy!.anyMethod;
const cfnAnyMethod = (anyMethod!.node!.defaultChild as apig.CfnMethod);
cfnAnyMethod.addPropertyOverride("Integration.TimeoutInMillis", cdk.Duration.seconds(10).toMilliseconds())
```

### Environment

  - **CDK CLI Version  :**
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):** 

### Other

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
Hi @Samrose-Ahmed -

I've reclassified this issue as a feature request.

I am also marking this issue as p2, which means that we are unable to work on this immediately. We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. 

We are also happy to accept pull requests.
