### ISSUE TITLE
cdk-workshop: For pipeline stage tutorial getting error trying to resolve lambda asset

### ISSUE THREAD

**Issue by asween16** [aws/aws-cdk#14125]
## I am going through the cdk-workshop fir typescript. (https://cdkworkshop.com/20-typescript.html). I am going through the tutorial to Create a New pipeline and when I deploy I keep getting the error. 

[Container] 2021/04/12 23:46:24 Running command npx cdk synth
--
32 | npx: installed 202 in 6.043s
33 | /codebuild/output/src241076631/src/node_modules/@aws-cdk/core/lib/asset-staging.js:52
34 | throw new Error(`Cannot find asset at ${this.sourcePath}`);
35 | ^
36 |  
37 | Error: Cannot find asset at /codebuild/output/src241076631/src/lambda
38 | at new AssetStaging (/codebuild/output/src241076631/src/node_modules/@aws-cdk/core/lib/asset-staging.js:52:19)
39 | at new Asset (/codebuild/output/src241076631/src/node_modules/@aws-cdk/aws-s3-assets/lib/asset.js:28:25)
40 | at AssetCode.bind (/codebuild/output/src241076631/src/node_modules/@aws-cdk/aws-lambda/lib/code.js:258:26)
41 | at new Function (/codebuild/output/src241076631/src/node_modules/@aws-cdk/aws-lambda/lib/function.js:97:33)
42 | at new CdkWorkshopStack (/codebuild/output/src241076631/src/lib/cdk-workshop-stack.js:13:23)
43 | at new WorkshopPipelineStage (/codebuild/output/src241076631/src/lib/pipeline-stage.js:9:25)
44 | at new WorkshopPipelineStack (/codebuild/output/src241076631/src/lib/pipeline-stack.js:40:24)
45 | at Object.<anonymous> (/codebuild/output/src241076631/src/bin/cdk-workshop.js:7:1)
46 | at Module._compile (internal/modules/cjs/loader.js:1015:30)
47 | at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)

### Environment

  - **CDK CLI Version:** 1.98.0
  - **Node.js Version:** v10.3.0
  - **OS:** macOS Mojave  
  - **Typescript (Version):** 4.2.4 

### Other information

Full log

[Container] 2021/04/12 23:46:02 Waiting for agent ping
--
2 | [Container] 2021/04/12 23:46:04 Waiting for DOWNLOAD_SOURCE
3 | [Container] 2021/04/12 23:46:06 Phase is DOWNLOAD_SOURCE
4 | [Container] 2021/04/12 23:46:06 CODEBUILD_SRC_DIR=/codebuild/output/src241076631/src
5 | [Container] 2021/04/12 23:46:06 YAML location is /codebuild/readonly/buildspec.yml
6 | [Container] 2021/04/12 23:46:06 Processing environment variables
7 | [Container] 2021/04/12 23:46:06 No runtime version selected in buildspec.
8 | [Container] 2021/04/12 23:46:06 Moving to directory /codebuild/output/src241076631/src
9 | [Container] 2021/04/12 23:46:06 Registering with agent
10 | [Container] 2021/04/12 23:46:06 Phases found in YAML: 2
11 | [Container] 2021/04/12 23:46:06  PRE_BUILD: 1 commands
12 | [Container] 2021/04/12 23:46:06  BUILD: 2 commands
13 | [Container] 2021/04/12 23:46:06 Phase complete: DOWNLOAD_SOURCE State: SUCCEEDED
14 | [Container] 2021/04/12 23:46:06 Phase context status code:  Message:
15 | [Container] 2021/04/12 23:46:06 Entering phase INSTALL
16 | [Container] 2021/04/12 23:46:06 Phase complete: INSTALL State: SUCCEEDED
17 | [Container] 2021/04/12 23:46:06 Phase context status code:  Message:
18 | [Container] 2021/04/12 23:46:06 Entering phase PRE_BUILD
19 | [Container] 2021/04/12 23:46:06 Running command npm ci
20 | added 615 packages in 6.037s
21 |  
22 | [Container] 2021/04/12 23:46:16 Phase complete: PRE_BUILD State: SUCCEEDED
23 | [Container] 2021/04/12 23:46:16 Phase context status code:  Message:
24 | [Container] 2021/04/12 23:46:16 Entering phase BUILD
25 | [Container] 2021/04/12 23:46:16 Running command npm run build
26 |  
27 | > cdk-workshop@0.1.0 build /codebuild/output/src241076631/src
28 | > tsc
29 |  
30 |  
31 | [Container] 2021/04/12 23:46:24 Running command npx cdk synth
32 | npx: installed 202 in 6.043s
33 | /codebuild/output/src241076631/src/node_modules/@aws-cdk/core/lib/asset-staging.js:52
34 | throw new Error(`Cannot find asset at ${this.sourcePath}`);
35 | ^
36 |  
37 | Error: Cannot find asset at /codebuild/output/src241076631/src/lambda
38 | at new AssetStaging (/codebuild/output/src241076631/src/node_modules/@aws-cdk/core/lib/asset-staging.js:52:19)
39 | at new Asset (/codebuild/output/src241076631/src/node_modules/@aws-cdk/aws-s3-assets/lib/asset.js:28:25)
40 | at AssetCode.bind (/codebuild/output/src241076631/src/node_modules/@aws-cdk/aws-lambda/lib/code.js:258:26)
41 | at new Function (/codebuild/output/src241076631/src/node_modules/@aws-cdk/aws-lambda/lib/function.js:97:33)
42 | at new CdkWorkshopStack (/codebuild/output/src241076631/src/lib/cdk-workshop-stack.js:13:23)
43 | at new WorkshopPipelineStage (/codebuild/output/src241076631/src/lib/pipeline-stage.js:9:25)
44 | at new WorkshopPipelineStack (/codebuild/output/src241076631/src/lib/pipeline-stack.js:40:24)
45 | at Object.<anonymous> (/codebuild/output/src241076631/src/bin/cdk-workshop.js:7:1)
46 | at Module._compile (internal/modules/cjs/loader.js:1015:30)
47 | at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
48 | Subprocess exited with error 1
49 |  
50 | [Container] 2021/04/12 23:46:31 Command did not exit successfully npx cdk synth exit status 1
51 | [Container] 2021/04/12 23:46:31 Phase complete: BUILD State: FAILED
52 | [Container] 2021/04/12 23:46:31 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: npx cdk synth. Reason: exit status 1
53 | [Container] 2021/04/12 23:46:31 Entering phase POST_BUILD
54 | [Container] 2021/04/12 23:46:31 Phase complete: POST_BUILD State: SUCCEEDED
55 | [Container] 2021/04/12 23:46:31 Phase context status code:  Message:
56 | [Container] 2021/04/12 23:46:32 Expanding base directory path: cdk.out
57 | [Container] 2021/04/12 23:46:32 Assembling file list
58 | [Container] 2021/04/12 23:46:32 Expanding cdk.out
59 | [Container] 2021/04/12 23:46:32 Expanding file paths for base directory cdk.out
60 | [Container] 2021/04/12 23:46:32 Assembling file list
61 | [Container] 2021/04/12 23:46:32 Expanding **/*
62 | [Container] 2021/04/12 23:46:32 Phase complete: UPLOAD_ARTIFACTS State: FAILED
63 | [Container] 2021/04/12 23:46:32 Phase context status code: CLIENT_ERROR Message: no matching artifact paths found

**Comment by peterwoodworth** [comment]
Hey @asween16, welcome to using the CDK!

I think I need some more info from you. Were you able to successfully deploy the lambda function before adding the pipeline? What does your code look like where you are declaring the Lambda function? It should look like this

```ts
    const hello = new lambda.Function(this, 'HelloHandler', {
      runtime: lambda.Runtime.NODEJS_10_X,    // execution environment
      code: lambda.Code.fromAsset('lambda'),  // code loaded from "lambda" directory
      handler: 'hello.handler'                // file is "hello", function is "handler"
    });
```

You should have a folder called "lambda" in the root of your project, and inside that folder have a file called "hello.js" that exports a handler like so:

```ts
exports.handler = async function(event) {
  console.log("request:", JSON.stringify(event, undefined, 2));
  return {
    statusCode: 200,
    headers: { "Content-Type": "text/plain" },
    body: `Hello, CDK! You've hit ${event.path}\n`
  };
};
```
