### ISSUE TITLE
(aws-apigateway): Per client per method usage plan for SpecRestApi

### ISSUE THREAD

**Issue by SSJ-Goku** [aws/aws-cdk#14128]
### The Question
While creating a usage plan for an api, we need to explicitly pass the Method object to set a per client per method throttling limits. 

However, for SpecRestApi which is created using openapi definition, I couldn't find a way to extract an array of Method objects associated with the api like we get in RestApi. 

I did a lot of workarounds like creating a clone RestApi from SpecRestAPi but the method array comes empty in that case.
I was wondering if Usage plan could take method path like we define the methodOptions attribute:

`readonly methodOptions?: {
        [path: string]: MethodDeploymentOptions;
    };`

instead of the Method object itself. Or is there another way to achieve what I am trying to do?

**Comment by peterwoodworth** [comment]
Hey @SSJ-Goku,

According to the docs page for [SpecRestApi](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-apigateway.SpecRestApi.html): "some properties normally accessible on RestApi - such as the description - must be declared in the specification. All Resources and Methods need to be defined as part of the OpenAPI specification file, and cannot be added via the CDK."

Hope this points you in the right direction, let me know if you need additional guidance with this

**Comment by koder-1** [comment]
Does that mean if I use spec rest api, it isn't possible to set per method throttling for clients in usage plans via cdk?

**Comment by peterwoodworth** [comment]
Unfortunately, this doesn't seem possible using the spec rest api with the CDK :/ 

Sorry for the long response time, took a while to research this.
