### ISSUE TITLE
EC2 EBS: Delete on termination should be assigneable on BlockDevice in @aws-cdk/aws-ec2/lib/volume.d.ts

### ISSUE THREAD

**Issue by tom10271** [aws/aws-cdk#14129]
### Use Case

I want to reserve the EBS used by instance on EC2 instance deletion

### Proposed Solution

Support `deleteOnTermination?: boolean` in BlockDevice.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by bitoku** [comment]
There seems to be an option in [EbsDeviceProps](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ec2.EbsDeviceProps.html), which is the argument of [BlockDeviceVolume](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ec2.BlockDeviceVolume.html).

This is the example to use the `deleteOnTermination` option.

```typescript
const instance = new Instance(this, 'instance', {
    vpc,
    vpcSubnets: {subnetType: SubnetType.ISOLATED},
    instanceType: new InstanceType('t3a.nano'),
    machineImage: MachineImage.latestAmazonLinux(
        { generation: AmazonLinuxGeneration.AMAZON_LINUX_2 }
    ),
    instanceName: 'testInstance',
    blockDevices: [
        {
            deviceName: "/dev/xvda",
            volume: BlockDeviceVolume.ebs(
                8,
                {
                    deleteOnTermination: false,  /* This is the option! */
                })
        }
    ],
});
```

**Comment by Dzhuneyt** [comment]
Seems like there's nothing to be done here. Shouldn't this be closed?

**Comment by njlynch** [comment]
It seems so. Thanks for pointing this out, @Dzhuneyt .
