### ISSUE TITLE
(eks): Pass pre-created IAM roles into EKS cluster construct

### ISSUE THREAD

**Issue by erikbbr** [aws/aws-cdk#14120]
The EKS cluster creation role used in the L2 EKS construct cannot be provided as an input to the construct. This is the only role that has this limitation.

### Use Case

We want to be able to create all IAM roles needed for the cdk EKS cluster ahead of time and pass those roles into the creation of the EKS cluster construct. This will allow customers that deploy cdk under roles that do not have IAM permissions to still be able to use the EKS construct.

### Proposed Solution

Modify EKS cluster creation construct to allow cluster creation role as well as all lambda function helper roles to be passed in via ARN.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by markussiebert** [comment]
We are deploying several eks cluster per account and it would be nice to reduce the IAM roles. But I think it would better to reuse the Whole eks Creation Lambda.
