### ISSUE TITLE
(aws-lambda-nodejs): single build with multiple entrypoints

### ISSUE THREAD

**Issue by nihalgonsalves** [aws/aws-cdk#14137]
Before `aws-lambda-nodejs` was promoted to stable, we used `esbuild` and a custom build script to build all our handlers at once.

### Use Case

The main benefit is speed of bundling – instead of having to run esbuild, install (for `nodeModules`), and hooks N times, the bundling can be completed in one single step. It reduces the synth+bundle time significantly.

It also reduces the total bundle size since common modules and code are bundled into shared chunks. Only a single asset bundle is required for the entire stack – so `nodeModules`-configured deps would also be shared.

### Proposed Solution

In our custom solution using the base `aws-lambda` package, the bundle step was run separately, and then the output directory was specified as a `Code` asset and the relative output path was referenced in the Lambda functions.

I'm not familiar with the architecture of this module, but if it were possible to collect all `NodejsFunction` declarations, it would be relatively simple to then call esbuild for all at once.

Is this something that's possible, or is it out of scope for this module?

### Other

Possible problems:

- How would the configuration work for common bundler settings?

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by skyrpex** [comment]
I don't think it'd be possible to do it they way you're proposing (under the hood, running esbuild once for all of the functions): you may have completely different functions that live in different directory trees, and these functions may have different building props.

Although, there's a different way to do so. I just requested to export the esbuild's asset code bundler so it can be manually used to bundle your code: https://github.com/aws/aws-cdk/issues/14215. There's even a small self-made implementation as a workaround.

If you change the `input: string` to `entryPoints: string[]`, you should be able to generate a big bundle with all of your functions' entry points and assets. Then, it'd be a matter of reusing your bundled big AssetCode object when necessary.

**Comment by skyrpex** [comment]
The multi-entry point bundler would **look** like this:

```ts
import * as lambda from "@aws-cdk/aws-lambda";
import * as cdk from "@aws-cdk/core";
import * as esbuild from "esbuild";
import findUp from "find-up";
import * as path from "path";

const findDepsLockFilePath = (input: string) => {
  const lockFilePath = findUp.sync(["package-lock.json", "yarn.lock"], {
    cwd: input,
  });

  if (!lockFilePath) {
    throw new Error("Couldn't find a lock file (package-lock.json or yarn.lock)");
  }

  return lockFilePath;
};

/**
 * Converts a Lambda runtime to an esbuild node target.
 */
function toTarget(runtime: lambda.Runtime): string {
  const match = runtime.name.match(/nodejs(\d+)/);

  if (!match) throw new Error("Cannot extract version from runtime.");

  return `node${match[1]}`;
}

export interface EsbuildBundlingProps {
  entryPoints: string[];
  runtime: lambda.Runtime;
  external?: string[];
  define?: {
    [key: string]: string;
  };
}

export class EsbuildBundling {
  public static bundle(options: EsbuildBundlingProps): lambda.AssetCode {
    const depsLockFilePath = findDepsLockFilePath(options.entryPoints[0]);

    return lambda.Code.fromAsset(path.dirname(depsLockFilePath), {
      assetHashType: cdk.AssetHashType.OUTPUT,
      bundling: new EsbuildBundling(options),
    });
  }

  public readonly image: cdk.DockerImage;

  public readonly local: cdk.ILocalBundling;

  constructor(props: EsbuildBundlingProps) {
    this.image = cdk.DockerImage.fromRegistry("dummy");
    this.local = {
      tryBundle(outputDir) {
        esbuild.buildSync({
          entryPoints: props.entryPoints,
          bundle: true,
          platform: "node",
          target: toTarget(props.runtime),
          // outfile: `${outputDir}/index.js`,
          outdir: outputDir,
          external: ["aws-sdk", ...(props.external || [])],
          define: props.define,
          // minify: true,
        });
        return true;
      },
    };
  }
}
```

And it's used like this:

```ts
const code = EsbuildBundling.bundle({
  entryPoints: ["file-a.js", "file-b.js"],
  runtime: lambda.Runtime.NODEJS_14_X,
});

new lambda.Function(this, "FunctionA", {
  code,
  handler: "file-a.handler",
  runtime: lambda.Runtime.NODEJS_14_X,
});

new lambda.Function(this, "FunctionB", {
  code,
  handler: "file-b.handler",
  runtime: lambda.Runtime.NODEJS_14_X,
});
```

**Comment by eladb** [comment]
I am unassigning and marking this issue as `p2`, which means that we are unable to work on this immediately.

We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://join.slack.com/t/cdk-dev/shared_invite/zt-mso6p56d-qJp7SOTBvMaQuDrx7R2wHg) to solicit support for reprioritization.
