### ISSUE TITLE
cli: Vpc lookup reported error is not very clear

### ISSUE THREAD

**Issue by poliak9** [aws/aws-cdk#14144]
When using the `Vpc.from_lookup` function without the proper permissions the output it produces from for example `deploy` is just
```
[Error at /file] You are not authorized to perform this operation.
Found errors
```
Which makes it very cumbersome to find out what permissions are missing, as otherwise the cdk fails with a specific `arn` and `action` why.

### Reproduction Steps

- bootstrap cdk
- create IAM user that is allowed only to assume the bootstrapped roles.
- stack with `Vpc.from_lookup`
- `deploy` the stack with the user's credentials

### What did you expect to happen?

Logged error what specific action failed as it is the case with missing permissions during deployment.

### What actually happened?

Vague debugging information provided without identification what caused it.

### Environment

  - **CDK CLI Version  :** 1.87.1
  - **Framework Version:** 1.89.0
  - **Node.js Version:** v10.23.2 
  - **OS               :** Centos
  - **Language (Version):**  Python 3.7

### Other

Unfortunately I am not that knowledgeable about the internals, but I assume this might happen in all the context methods.

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
A good start would be to catch the error in the VPC lookup provider and wrap with a text like "DescribeVpc failed: $ERROR"
