### ISSUE TITLE
(CodeStarConnectionsSourceAction): vestigial BitBucket-only reference 

### ISSUE THREAD

**Issue by jrobbins-LiveData** [aws/aws-cdk#14142]
The new `CodeStarConnectionsSourceAction` construct still refers only to BitBucket in its description of the`connection_arn` parameter.

[CodeStarConnectionsSourceAction](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_codepipeline_actions/CodeStarConnectionsSourceAction.html)

The description says:

> The ARN of the CodeStar Connection created in the AWS console that has permissions to access this BitBucket repository.

It should say:

> The ARN of the CodeStar Connection created in the AWS console that has permissions to access this GitHub or BitBucket repository.

![codestarconnectionsourceaction_doc](https://user-images.githubusercontent.com/79278744/114569671-2dcbb980-9c43-11eb-9c4a-3f6b3099ef7b.png)

---

This is a 📕 documentation issue

**Comment by skinny85** [comment]
Nice catch @jrobbins-LiveData, thanks! Any chance you could submit a quick PR fixing this? 😃

**Comment by jrobbins-LiveData** [comment]
@skinny85, happy to do so.  Full confession -- I'm somewhat inexperienced with Git, so it might not happen right away as I try to figure out what to do!

**Comment by skinny85** [comment]
Judging from https://github.com/aws/aws-cdk/pull/14155, you're pretty quick in figuring things out 😃.

**Comment by jrobbins-LiveData** [comment]
Thanks, I appreciate it.

-Jeff
