### ISSUE TITLE
(aws-s3): urlForObject() returns invalid URL if bucket is not in same region as stack

### ISSUE THREAD

**Issue by peterwoodworth** [aws/aws-cdk#14149]
The code for `urlForObject()` [here](https://github.com/aws/aws-cdk/blob/7966f8d48c4bff26beb22856d289f9d0c7e7081d/packages/%40aws-cdk/aws-s3/lib/bucket.ts#L533) builds the URL by using the region of the stack rather than the bucket. This causes the function to return an incorrect URL if an existing bucket is imported from another region using `fromBucketXXX()` function

### Workarounds

You can currently get around this by copying the bucket objects to a bucket in the same region as the stack that is being deployed
OR use "low level overriding" to change the low level `AWS::CloudFormation::Init` section

### Potential solution

Construct the URL using data from `bucketRegionalDomainName` prop

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment]
Just adding this for future implementors - since imported buckets can have explicit regions [set](https://github.com/aws/aws-cdk/pull/9936), we might be able to properly construct the URL even if `bucketRegionalDomainName` is not set.
