### ISSUE TITLE
(glue): Missing parameter *parameters* from class Table (construct)

### ISSUE THREAD

**Issue by braidenjudd** [aws/aws-cdk#14159]
Add [cfn-glue-table-tableinput-parameters](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-table-tableinput.html#cfn-glue-table-tableinput-parameters) to the [Glue Table Construct](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-glue.Table.html)

### Use Case

I want to be able to set parameters at create time of the table to make the table compatible with a crawler I am using.

### Proposed Solution

Optional props parameters to [TableProps](https://github.com/aws/aws-cdk/blob/v1.98.0/packages/@aws-cdk/aws-glue/lib/table.ts#L63) and append them here [Table](https://github.com/aws/aws-cdk/blob/v1.98.0/packages/@aws-cdk/aws-glue/lib/table.ts#L265)

* [x] :wave: I may be able to implement this feature request

---

This is a :rocket: Feature Request

**Comment by iliapolo** [comment]
We are unassigning and marking this issue as p2, which means that we are unable to work on this immediately.
We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://join.slack.com/t/cdk-dev/shared_invite/zt-mso6p56d-qJp7SOTBvMaQuDrx7R2wHg) to solicit support for reprioritization.

If you'd like to contribute this feature, that would also be great :)

**Comment by fs111** [comment]
I ran into this limitation yesterday and it took me a while to figure out a work-around. Could you please reconsider adding this?

If you come here and wonder how to solve this, you can "hack" around it by using the CDK escape hatch into Cfn types like so (example is in java):

```
var glueTable = Table.Builder.create(this, "glueTable")[...].build();
CfnTable cfnTable = (CfnTable) glueTable.getNode().getDefaultChild();
cfnTable.addPropertyOverride("TableInput.StorageDescriptor.SerdeInfo.Parameters.serialization\\.format", 1);
```

**Comment by mattiamatrix** [comment]
This is a possible solution in TS

```ts
(<CfnTable>table.node.defaultChild).addPropertyOverride(
    'TableInput.StorageDescriptor.SerdeInfo.Parameters.serialization\\.format',
    1
);
```

**Comment by lihonosov** [comment]
@mattiamatrix @fs111 thanks for the workaround, it was useful! I needed to add `useGlueParquetWriter=true` to the `Parameters` section:
```js
(<CfnTable>table.node.defaultChild).addPropertyOverride(
      "TableInput.Parameters.useGlueParquetWriter",
      "true"
);
```

**Comment by lawofcycles** [comment]
I may be able to implement this fix.
