### ISSUE TITLE
(aws-ecs): "Task Auto-Scaling" Documentation example incomplete

### ISSUE THREAD

**Issue by piraka9011** [aws/aws-cdk#14152]
Link to reference doc page:
https://docs.aws.amazon.com/cdk/api/latest/docs/aws-ecs-readme.html#task-auto-scaling

## Issue

The task autoscaling example is incomplete. It references a `target` variable, but no variable exists in the example or the documentation page.

```ts
const scaling = service.autoScaleTaskCount({ maxCapacity: 10 });
scaling.scaleOnCpuUtilization('CpuScaling', {
  targetUtilizationPercent: 50
});

scaling.scaleOnRequestCount('RequestScaling', {
  requestsPerTarget: 10000,
  targetGroup: target  // target doesn't exist?
})
```
---

This is a 📕 documentation issue

**Comment by peterwoodworth** [comment]
Hey @piraka9011, sorry for the long response time.

If you take a look at the [docs for scaleOnRequestCount](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs.RequestCountScalingProps.html) you'll find that the `targetGroup` prop is only an [ALB Target Group construct](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-elasticloadbalancingv2.ApplicationTargetGroup.html). So I don't think this is an incomplete example, as showing the creation of a separate targetGroup is unnecessary to express the info the example is trying to convey :)
