### ISSUE TITLE
aws_rds: Cannot call secret attach with rds proxy as target

### ISSUE THREAD

**Issue by tl24** [aws/aws-cdk#14163]
I'm trying to use an RDS proxy as the target for secret attach.  I'm hoping that the target attachment will update the secret with the proxy endpoint after its created.  I'm also passing this secret to the add_proxy method since it will be the same user.  DatabaseProxy implements the ISecretAttachmentTarget interface but I don't see that listed on as a valid target on cloud formation docs https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-secretsmanager-secrettargetattachment.html

When I try and deploy my stack I get an error: 

```
12:23:34 AM | CREATE_FAILED        | AWS::SecretsManager::SecretTargetAttachment | dbproxysecretAttachment6FC29616
Unsupported target type
```

Should this work for an rds proxy?  If not, is there a recommended way to do this?

### Environment

  - **CDK CLI Version:** 1.96.0
  - **Module Version:** 1.97
  - **Node.js Version:** v15.9.0
  - **OS:** Ubuntu 20.04 WSL
  - **Language (Version):** Python 3.8.5

### Sample Code

```python
  self.rds = DatabaseCluster(
      self,
      "rds",
      engine=DatabaseClusterEngine.aurora_postgres(version=AuroraPostgresEngineVersion.VER_11_9),
      instance_props=InstanceProps(
          vpc=vpc,
          vpc_subnets=SubnetSelection(subnet_type=SubnetType.PRIVATE),
          enable_performance_insights=True,
          publicly_accessible=False,
          instance_type=InstanceType(instance_type),
          security_groups=[security_group],
      ),
      instances=min_instances,
      removal_policy=removal_policy,
      default_database_name=database_name,
      storage_encrypted=True,
      credentials=Credentials.from_generated_secret(username="admin", secret_name=construct_name(self, "rds-master")),
  )

  master_secret = self.rds.secret
  proxy_secret = Secret(
      self,
      "proxy-secret",
      encryption_key=master_secret.encryption_key,
      generate_secret_string=SecretStringGenerator(
          secret_string_template=clone_secret_template(
              master_secret, "proxy_user", self.rds.cluster_endpoint.hostname, ["reader", "writer"]
          ),
          generate_string_key="password",
      ),
  )
  self.rds_proxy = self.rds.add_proxy(
      "rds-proxy",
      secrets=[self.rds.secret],
      vpc=vpc,
      db_proxy_name=construct_name(self, "proxy"),
      security_groups=[security_group],
      require_tls=False,
  )

  #####  Issue is here with secret.attach ########
  self.proxy_secret = proxy_secret.attach(self.rds_proxy)
```

**Comment by skinny85** [comment]
Hey @tl24, thanks for opening the issue. I believe you're correct, and you can't use a Proxy as the target of Secret Attachment. This is most likely an error in the RDS library, which we should fix.

In the meantime, you can access the endpoint of the proxy using the `endpoint` property of the class. You can then pass it somewhere as an environment variable, for example.

Thanks,
Adam
