### ISSUE TITLE
CDK does not update stack

### ISSUE THREAD

**Issue by einavh** [aws/aws-cdk#14164]
when I update a metric which is connected to a dashboard in my monitoring stack the changes does not apply. it seems like cdk is not performing diffs as good as terraform. this is not the only case I have experienced that the stack was not updated although finished execution with success.

**Comment by straygar** [comment]
I've used CW dashboards with frequently changing metrics in CDK with no issues.

Could you describe the issue in more detail, using the issue template? E.g. at least reproduction steps and the before/after CDK code would be great help in debugging this. :)

**Comment by peterwoodworth** [comment]
Thank you @straygar for offering to help with this issue. @einavh if you could provide more information that would allow us to help you 😄
