### ISSUE TITLE
(aws-ssm): Create constructs for common ssm tasks

### ISSUE THREAD

**Issue by cyuste** [aws/aws-cdk#14166]
I would like to have constructs to perform common tasks, such as update my instances with latest security patches, in an assisted way similar to the console procedure SSM > Node Management > Patch Manager. 
I have managed to configure it using Cfn constructs but it's quite difficult and prone to errors as a lot of fields are not validated for correct input. 

I can provide my solution encapsulated in a construct, but I don't know if you would prefer constructs for a more general case.

* [x] :wave: I may be able to implement this feature request

---

This is a :rocket: Feature Request

**Comment by MrArnoldPalmer** [comment]
@cyuste I would love to see these! I would suggest creating a separate package to iterate on design and test with. Also check out https://github.com/udondan/cdk-ssm-document and talk to @udondan. You may want to use some of the constructs in that package to build upon.
