### ISSUE TITLE
(aws-lambda-nodejs): Disable bundling

### ISSUE THREAD

**Issue by hugomallet** [aws/aws-cdk#14187]
Hello,

Context :
I have a weird runtime error that seems to be unfixable (edit: https://github.com/aws/aws-cdk/issues/14188#issuecomment-820285387) from my side : 
```sh
"Runtime.ImportModuleError: Error: Cannot find module 'aws-sdk/lib/config_service_placeholders'",
        "Require stack:",
        "- /var/task/index.js",
        "- /var/runtime/UserFunction.js",
        "- /var/runtime/index.js",
        "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
```

So I tried to uninstall esbuild to avoid bundling but it doesn't look to have any effect.

Feature request : Be able to disable completely bundling.

This is a :rocket: Feature Request

**Comment by eladb** [comment]
@hugomallet seems like you managed to resolve your issue (great!). I am not sure I can see the use case for disabling bundling, given that without bundling your app won't work. I am closing this issue for now, but feel free to add a comment with a more specific use case.
