### ISSUE TITLE
(ec2): Add option to turn Auto-assign public IPv4 address off for public subnets

### ISSUE THREAD

**Issue by sandrom** [aws/aws-cdk#14194]
I need to be able to create Public Subnets with "Auto-assign public IPv4 address" turned off and I would like to do that using the ec2.Vpc functionality and not go full on manual just because of this tiny detail.

### Use Case

Corporate Regulations that can not be changed.

### Proposed Solution

```
const vpc = new ec2.Vpc(this, "Test123", {
      maxAzs: 3,
      subnetConfiguration: [
        {
          cidrMask: 24,
          name: "PublicSubnet",
          subnetType: ec2.SubnetType.PUBLIC,
          mapPublicIpOnLaunch: false
        }
      ],
    });
```

### Other

* [X] :wave: I should be able to implement this feature request

As default can stay as it is, there shouldn't be any impact.

---

This is a :rocket: Feature Request

**Comment by hguillermo** [comment]
It will be fixed with https://github.com/aws/aws-cdk/pull/17346
