### ISSUE TITLE
(codepipeline_Actions): Support for Full Clone for GitHubSourceAction

### ISSUE THREAD

**Issue by philasmar** [aws/aws-cdk#14196]
We are looking for support for doing a full clone of the GitHub repo using GitHubSourceAction.
Currently, CodeCommitSourceAction has a property "codeBuildCloneOutput" that allows the user to do a full clone.
The feature set is inconsistent between CodeCommit and GitHub.
Can you please add this support?

### Environment

  - **CDK CLI Version  :** 1.98.0
  - **Language (Version):** all
  
### Other

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hey @philasmar ,

thanks for opening the issue. Unfortunately, the `GitHubSourceAction` does not have this capability (I'm talking about CodePipeline here - not that it doesn't have this capability in the CDK).

You can use the `CodeStarConnectionsSourceAction`, which [does have this option](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-codepipeline-actions.CodeStarConnectionsSourceActionProps.html#codebuildcloneoutput).

Thanks,
Adam

**Comment by philasmar** [comment]
Hey @skinny85,

Thank you for the prompt answer. How can I use CodeStarConnectionsSourceAction to connect to a GitHub repo ?
Is there a code snippet or example that you can share?

Regards,
Philippe

**Comment by skinny85** [comment]
Sure: https://docs.aws.amazon.com/cdk/api/latest/docs/aws-codepipeline-actions-readme.html#bitbucket
