### ISSUE TITLE
(aws-logs-destinations/LambdaDestination): LambdaDestination without added permission

### ISSUE THREAD

**Issue by zARODz11z** [aws/aws-cdk#14198]
### The Question
We have made a [Datadog CDK Construct library](https://github.com/DataDog/datadog-cdk-constructs) and one of the purposes of our construct is to create a subscription filter from our Datadog Forwarder Lambda function to Lambda function Log Groups. [This](https://github.com/DataDog/datadog-cdk-constructs/blob/d8f324b6a537c7c7f03be239dc031e2f7247790f/src/forwarder.ts#L47) is how we are currently doing it however when we create a Lambda destination [here](https://github.com/DataDog/datadog-cdk-constructs/blob/d8f324b6a537c7c7f03be239dc031e2f7247790f/src/forwarder.ts#L43) by using the aws-logs-desinations library we run into issues with customers who are deploying a high amount of Lambdas via CDK and instrumenting it with our Construct. 

The error is `The final policy size (20497) is bigger than the limit (20480).`. We believe the issue is the fact that LambdaDestination creates a permission for the lambda function [here](https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-logs-destinations/lib/lambda.ts#L16). Our Datadog Forwarder Lambda Function is deployed with a global permission policy to allow ANY log group to invoke the Forwarder. So When customers use our construct with a high number of lambdas their policy exceeds the limit because of [this](https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-logs-destinations/lib/lambda.ts#L16). Is there any way around this?

Is there something equivalent to this [LambdaDestination](https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-logs-destinations/lib/lambda.ts) class that does not add a '[CanInvokeLambda](https://github.com/aws/aws-cdk/blob/a99e9015b2308c99c6b68c3727f839aa039e4fe3/packages/%40aws-cdk/aws-logs-destinations/lib/lambda.ts#L16)' permission? 

### Environment

  - **Language (Version):** Typescript

**Comment by rix0rrr** [comment]
> Is there something equivalent to this LambdaDestination class that does not add a 'CanInvokeLambda' permission?

Not built-in, but you could easily make one yourself. You can subclass `LambdaDestination`, or implement `ILogSubscriptionDestination` completely on a new class.

You could also subclass `Lambda` and override `addPermission` to not add the permissions if the service principal is `logs.amazonaws.com`.

Finally, I *guess* adding options to `LambdaDestination` to add an option like `addPermissions: false` would be welcome if you'd care to implement it.

**Comment by zARODz11z** [comment]
@rix0rrr I made the changes, I am unable to push to a dev branch 
```
git push origin AR/makeLambdaPermissionsOptional
remote: Permission to aws/aws-cdk.git denied to zARODz11z.
fatal: unable to access 'https://github.com/aws/aws-cdk.git/': The requested URL returned error: 403
```
I can't seem to find anything in the contributing file about this
