### ISSUE TITLE
(aws-batch): Providing service role is mandatory for CfnComputeEnvironment

### ISSUE THREAD

**Issue by mlech-payability** [aws/aws-cdk#14191]
### Reproduction Steps

Create `CfnComputeEnvironment` instance without specifying `service_role`.

### What did you expect to happen?

The `service_role` should be optional and by default it should use/create a service-linked role as described [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-batch-computeenvironment.html). 

### What actually happened?

It fails, because the parameter is required.

### Environment

  - **CDK CLI Version:** 1.98.0
  - **Framework Version:** 1.98.0
  - **Node.js Version:** 14.6.1
  - **OS               :** macOS Big Sur 11.2.3
  - **Language (Version):** Python (3.9.2)

### Other

As a workaround, it's enough to pass an empty string to use/create a service-linked role, but is shouldn't be required.

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment]
@mlech-payability Thanks for reporting this. 

Looks like there might discrepancies between the CloudFormation schema and the documentation, we will investigate.

**Comment by iliapolo** [comment]
This was fixed with [merging](https://github.com/aws/aws-cdk/commit/49e49e7ef50ee008be66b1887e4e15e51a4ae576) spec version 35.0.0.

Will be available in the next release. Resolving.
