### ISSUE TITLE
(aws_ecs): Cluster container instance with wrong configurations for EC2 launch-type

### ISSUE THREAD

**Issue by siriuslan** [aws/aws-cdk#14208]
I need to create EC2 launch-type ecs by using below code in screenshot

![image](https://user-images.githubusercontent.com/39588576/115010168-72c84800-9ef0-11eb-86cc-9f8b2a699f43.png)
 
The problem for me are below
1. The cluster created is Fargate instead of EC2 launch-type(sample code in python install package suggest this to create EC2-launch-type one but does not work)
2. There is no way(also no need according to sample code) to specify IAM role which should be ecsInstanceRole including AmazonEC2ContainerServiceforEC2Role policy. So the IAM role used by container instance is new created with other inline policy.
3. The security_group configured to container instance is also new created though I specify existing one.

Here I attach sample code from python install package.
![image](https://user-images.githubusercontent.com/39588576/115011274-cc7d4200-9ef1-11eb-8299-0451e8723033.png)

### Environment

  - **CDK CLI Version:** 1.98.0
  - **Module Version:** 1.98.0
  - **Node.js Version:** 12.19.0
  - **OS:** Windows 10
  - **Language (Version):** Python 3.8.2

**Comment by rix0rrr** [comment]
Calling `Cluster.from_cluster_attributes()` in this way does nothing. You already created the cluster on the lines before, that's where configuration should go.

From this example https://github.com/aws-samples/aws-cdk-examples/blob/master/python/ecs/cluster/app.py it looks like you can just add EC2 capacity to a plain `ecs.Cluster`, so I wouldn't be too worried.

Try to start with some examples from the [aws-cdk-examples](https://github.com/aws-samples/aws-cdk-examples) repo and work your work up by making changes from there, you will probably work out the missing piece.
