### ISSUE TITLE
(aws_lambda_python): PythonFunction runtime is not respected

### ISSUE THREAD

**Issue by l0b0** [aws/aws-cdk#14200]
When trying to change from deploying an `aws_lambda.Function` to an `aws_lambda_python.PythonFunction`, even though I've set `runtime=aws_lambda.Runtime.PYTHON_3_8` the Docker builds are performed with `ARG IMAGE=amazon/aws-sam-cli-build-image-python3.7`

### Reproduction Steps

1. Instantiate a `PythonFunction` with `runtime=aws_lambda.Runtime.PYTHON_3_8`.
2. `cdk synth`

### What did you expect to happen?

CDK should use the Python 3.8 image to build.

### What actually happened?

CDK used the default Python 3.7 image to build.

### Environment

  - **CDK CLI Version  :** 1.98.0 (build 79f4512)
  - **Framework Version:** aws-cli/1.19.52 Python/3.8.6 Linux/5.11.13-arch1-1 botocore/1.20.52
  - **Node.js Version:** v14.15.1
  - **OS               :** Arch Linux
  - **Language (Version):** Python (3.8.6)

### Other

--- 

This is :bug: Bug Report

**Comment by eladb** [comment]
@adamelmore can you please take a look?

**Comment by eladb** [comment]
@peterwoodworth can you try to reproduce this? Code seems to suggest that the runtime version _is_ respected

**Comment by peterwoodworth** [comment]
I can't seem to reproduce this @eladb 

@l0b0 are you still running into this issue?

**Comment by eladb** [comment]
I am closing this for now. @l0b0 let us know if this is still relevant.
