### ISSUE TITLE
(@aws-cdk/aws cli) Unable to pass --no-verify-ssl to cdk cli 

### ISSUE THREAD

**Issue by gurkarangulati** [aws/aws-cdk#14216]
Currently utilizing the aws cli I am capable to run the following command 

`aws s3 ls --profile temp --no-verify-ssl`

I would like to do the same utilizing 
`cdk synth --no-verify-ssl`

Currently cdk doesn't accept --no-verify-ssl

but can't at this point of time. Is there a solution or can we add this as a feature request? I am currently unable to control or fix the enterprise setup of my laptop or gain permissions for the ssl cert issues.

**Comment by rix0rrr** [comment]
You can use an environment variable to control the behavior of Nodejs:

```
export NODE_TLS_REJECT_UNAUTHORIZED=0
```

https://nodejs.org/api/cli.html#cli_node_tls_reject_unauthorized_value

**Comment by gurkarangulati** [comment]
Confirmed the above step does temporarily solve the problem! Thank you for your response! Is there a way to request the flag to be added as a feature request?

**Comment by rix0rrr** [comment]
Just turned this into a feature request :)

But honestly, given that there is a workaround and somewhat swamped, we are unlikely to pick this up on our side. Your best bet of getting it added would be to add a PR yourself.

**Comment by nohack** [comment]
@gurkarangulati For which specific use case of s3, do you need this flag.During synth actual s3 invocation will not happen if I am not wrong.Resources are created during cdk deploy.
