### ISSUE TITLE
Support for Cache Policy and Origin Request Policy in Behavior for Cloudfront

### ISSUE THREAD

**Issue by wasitim** [aws/aws-cdk#14218]
The Behavior interface do not have properties to set Cache Policy nor Origin Request Policy , although they can be set from AWS console. This request is specific to CloudFrontWebDistributions and Behaviors associated.

Please add support for this property.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by njlynch** [comment]
Hi @wasitim !

Support for both are being tracked in #10829 and #10830, respectively. Please go :+1: there so we can track priority!
