### ISSUE TITLE
(@aws-cdk/aws-cloudfront.experimental): `cdk deploy` support for Lambda@Edge code changes

### ISSUE THREAD

**Issue by viventra** [aws/aws-cdk#14230]
### The Question

I am using `@aws-cdk/aws-cloudfront.experimental` module's EdgeFunction to simplify Lambda@Edge deployment for a cross-region application stack (app is in ap-south-1 and Lambda@Edge is in us-east-1). 

I am looking for guidance on `cdk deploy` for making changes to Lambda@Edge function source code.

The initial deploy goes well. The problem is when we make changes in Lambda@Edge and have to redeploy the change, if we just run `cdk deploy --all`, we get an error that the application stack is using an export from the Lambda stack and the deployment fails with a rollback.

I am able to do a `cdk destroy` of my application stack and then do a `cdk deploy --all` to get the stacks deployed. But this is not optimal due to availability issues that crop up.

What is the simplest intuitive way to do this for a developer without sacrificing availability? I am looking for guidance if something exists for this. If not, I would like to make a proposal as outlined below for a feat. request.

### Environment

This request is environment agnostic.
FWIW, my CDK version is: 1.96.0 (build 39f3df8)

### Other information

Ideally, I would think a `cdk deploy` should handle this transparently in the backend without the user having to specify or configure anything. But, if a construct (similar to BucketDeployment for S3 buckets) needs to be used, that may be acceptable too. The idea is to get `cdk deploy` to just work.

**Comment by njlynch** [comment]
Hi @viventra,

It sounds like something in the deployment is triggering a deletion (or rename) of one of the exports used by the Lambda@Edge construct. This shouldn't be the case when merely updating the function code; I suspect perhaps a logical ID was changed somewhere (e.g., code was refactored and received a new parent scope and/or ID).

Can you share the (sanitized) output of `cdk diff`, or -- even better -- a minimal reproducible example where making a change to only the function code causes this?

If you _are_ in this spot, another option besides destroying everything and rebuilding is to use the strategies outlined here on breaking cross-stack references: https://docs.aws.amazon.com/cdk/api/latest/docs/core-readme.html#removing-automatic-cross-stack-references. Depending on what's causing the export issue, this may (or may not) be helpful.

**Comment by viventra** [comment]
Thanks for the link. I will go through it and try out recommendations there.

Sorry about the delay in response. I had to sanitize the sample. Here it is.

See: https://github.com/viventra/authlambda.git for a minimal sample that reproduces the issue.

Steps to repro:
0. I am re-using a cloudfront OAI name.  Configure this in this line in AuthlambdaStack.cs after creating a cloudfront OAI manually or add it through CDK api.

AuthlambdaStack.cs (Line 17):
```
        const string cloudfrontOAIName = "<REPLACE WITH YOUR CLOUDFRONT OAI NAME>";
```

1. Before deploying for the first time, in AuthlambdaStack.cs comment out signOutBehavior in lines 142 - 154 and the reference in line 168. In AuthlambdaFunctionsStack.cs comment out `signOutHandler = new EdgeFunction(...)`, in lines 63-67.
2. Build and deploy the stack. I use ap-south-1 to deploy the app stack (LambdaEdge deploys to us-east-1) and we have a cross-stack scenario. See Program.cs for the region configurations for the stacks.
3. Now, uncomment the lines that were commented in step 1 to add signOutBehavior. Rebuild and re-deploy

You should get the error.

Reference Notes:

The actual lambda@Edge code is taken from [this AWS sample for Cloudfront Authorization at Edge](https://github.com/aws-samples/cloudfront-authorization-at-edge)

I have taken the lambda@Edge typescript modules alone from the above sample and integrated with this demo CDK app for a static website deployed on Cloudfront with lambda@Edge.

**Comment by NGL321** [comment]
Hey @viventra,

Did the provided guidance help fix your problem? If not, just comment and we will take a look again.

😸 😷
