### ISSUE TITLE
(@aws-cdk/core): overrideLogicalId ineffective on @aws-cdk/events Rule

### ISSUE THREAD

**Issue by shellscape** [aws/aws-cdk#14244]
`CfnResource.overrideLogicalId` appears to be ineffective on `Rule` resources.

### Reproduction Steps

I have a small convenience method to handle some of the lifting:

```ts
  public overrideId(thing: Resource, id: string) {
    const prefix = id.startsWith(this.appName) ? '' : `${this.appName}-`;
    const result = camelcase(`${prefix}${id}`);
    log.info('Overiding Logical ID:', chalk.dim(result));
    (thing.node.defaultChild as CfnResource).overrideLogicalId(result);
  }
```

I created a new `Rule` and called the convenience method:

```ts
  const rule = new Rule(scope, cronName, { schedule, targets });

  scope.overrideId(rule, cronName);
```

### What did you expect to happen?

Like other resources, I expected the logicalId of the resource to be overridden, and the display name in the AWS Console to match.

### What actually happened?

Using a target logicalId of `myStackNameMyCron` what I'm seeing in the AWS Console for the name of the `Rule` appears as:

```
my-stack-name-myStackNameMyCron-66DKD8UUPXFQ
```

### Environment

  - **CDK CLI Version  :** 1.96.0 (build 39f3df8)
  - **Framework Version:** 1.96.0
  - **Node.js Version:** 14.15.3
  - **OS               :** MacOS
  - **Language (Version):** 4.1.3

### Other

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
>  the display name in the AWS Console to match.

You are looking at a name generated by CloudFormation. Names are automatically generated by appending a unique string to the logical ID.  This is not different for Rules vs other resources.

If you MUST have a fixed name, then you need to pass `ruleName`. I'd recommend against doing that unless you have very specific reasons to do so, and using tags instead to identify resources.

**Comment by shellscape** [comment]
Thanks for the explanation. This JustWorked™️ on so many other resources that there was an expectation there.

**Comment by shellscape** [comment]
Checking in to report that as of the v1.138.2, SQS `Queue` falls into the bucket of special resources that don't respect `overrideLogicalId` without also passing `{resource}Name` to the constructor.

_Aside: this is some silly inconsistency and speakers towards a wider need. `overrideLogicalId` is prolific on the web when reading about CDK, and so many people are using that as part of wrappers around CDK that it's a little odd that it hasn't gotten attention in the core. Inconsistencies like this are only discoverable within obscure issues (like this one) and aren't present in the documentation._
