### ISSUE TITLE
(aws-cdk/aws-cli): Deploy as fire and forget

### ISSUE THREAD

**Issue by codenamestif** [aws/aws-cdk#14252]
I would be good to have a parameter for `cdk deploy` command that allows you to trigger deployment and don't wait until it's done.

### Use Case

Our use case is that we want to trigger the `cdk deploy` from lambda and not wait until it's done. And then we pull for the status in a different place (like from CircleCI).

### Proposed Solution

There could be a parameter `--fire-and-forget` for `cdk deploy` command

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
You can do this today by using the `--no-execute` flag and using the AWS CLI to call `execute-change-set` afterwards.
