### ISSUE TITLE
Scrutiny report needs line wrapping

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#1425]
<img width="1379" alt="screen shot 2018-12-24 at 9 07 20 am" src="https://user-images.githubusercontent.com/598796/50392964-633ef700-075b-11e9-9efe-71747499a4e5.png">

**Comment by rix0rrr** [comment]
It does have line wrapping  (or rather, it should), so the title of this issue is not quite accurate.

The question should be, why did it fail for you in this particular case, and does it still?
