### ISSUE TITLE
aws rds : Create snapshot before recreation of Database and then restore from it

### ISSUE THREAD

**Issue by bcteam2020** [aws/aws-cdk#14259]
Create snapshot before recreation of Database and then restore from it

### Use Case
Due to changes in the parameters/options supplied to a databaseinstance, sometimes the database is dropped and recreated. (Right now there is protection from deletion option available, and also final snapshot in case of deletion.) 
Both of them require additional efforts to maintain.

Most of the rds users are worried about dataloss or the best practises they have to follow for rds, This way most of the users are ensured that no data is lost during the execution.

### Proposed Solution
when there is a need to re-create a database, shutdown the database, take a snapshot and based on that snapshot restore it.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by Releef** [comment]
closed.. but what a feature request we would like to see!
