### ISSUE TITLE
(assets): docker login clashes with ecr-login

### ISSUE THREAD

**Issue by balkat** [aws/aws-cdk#14265]
Common best practice is to use https://github.com/awslabs/amazon-ecr-credential-helper to manage docker access to ECR.
If you configure your docker `config.json` file this way you never need to use docker login.  This is ideal in pipelines.
A characteristic of this helper is that it will fail with a `not implemented` error if you do try to perform (an unnecessary) docker login.  When using CDK with a docker image-based lambda function CDK will attempt a docker login, which will fail.

Because we pull other images from other ECR repos in our pipeline we need to continue using the `amazon-ecr-credential-helper`.  The outcome is that jobs will fail when CDK attempts the docker login.  We cannot work around the problem because we need the helper for access to one of our ECRs and CDK wants to use docker login to access its ECR.

### Reproduction Steps

Our docker `config.json` (as recommended for use with `amazon-ecr-credential-helper`)
```
{
  "credsStore": "ecr-login"
}
```
### What did you expect to happen?

CDK should successfully build and push the docker image for the lambda function
### What actually happened?

```
arn:aws:cloudformation:us-east-1:REDACTED:stack/REDACTED
[0%] start: Publishing REDACTED:current
[100%] fail: docker login --username AWS --password-stdin https://REDACTED.dkr.ecr.us-east-1.amazonaws.com exited with error code 1: Error saving credentials: error storing credentials - err: exit status 1, out: `not implemented`
```

### Environment

  - **CDK CLI Version  :*1.97.0*
  - **Framework Version:*1.97.0*
  - **Node.js Version:*12* 
  - **OS               :*Ubuntu 18*
  - **Language (Version):*Typescript 4* 

### Other

1. I suggest CDK provides an option to stop any attempts to perform a docker login.
1. Consider that using the `amazon-ecr-credential-helper` is a best practice and should be the default (breaking).

--- 

This is :bug: Bug Report

**Comment by balkat** [comment]
Have found a workaround that seems to be reliable:
In our pipeline script we:
1. First pull any base images we need (from private ECRs in other accounts) which gets them into the local docker cache
2. Export DOCKER_CONFIG set to the path of an empty directory
3. Run cdk deploy
Fortunately when CDK invokes docker to build the lambda asset docker seems to be happy to use its cache and does
not try to login to the other repos.  The empty config directory allows the CDK-initiated docker login to work

**Comment by eladb** [comment]
@rix0rrr makes sense that we should support `amazon-ecr-credential-helper`. What do you think?
