### ISSUE TITLE
(rds): forcing lowercase of subnet name breaks existing stacks

### ISSUE THREAD

**Issue by grncdr** [aws/aws-cdk#14269]
### Reproduction Steps

1. Create a stack containing an RDS `SubnetGroup` named 'MyTestSubnetGroup' with using v1.97 of the CDK (or lower).
2. Upgrade `@aws-cdk/aws-rds` to the latest version.
3. Run `cdk diff`

### What did you expect to happen?

No differences.

### What actually happened?

The subnet group name is lower-cased in the CloudFormation template, which would cause CloudFormation to replace it.

### Environment

  - **CDK CLI Version:** 1.99.0 (build 2691986)
  - **Framework Version:** 1.99.0 (build 2691986)
  - **Node.js Version:** v14.13.0
  - **OS               :** OSX
  - **Language (Version):** TypeScript

### Other

It seems like PR https://github.com/aws/aws-cdk/pull/13986 introduced the change, and the reasoning there makes sense, but unfortunately causes differences with existing stacks.

The impact of the bug is potentially quite large because replacing the subnet group would _also_ cause a replacement of an  RDS instance using that subnet group. Luckily I check my diffs manually and have a removal policy in place for the RDS instance, somebody less cautious could get their database destroyed by a patch upgrade. 😬 

--- 

This is :bug: Bug Report

**Comment by grncdr** [comment]
What's strange is I was able to deploy with a mixed case subnet group name. I can see in the RDS console that it has been lowercased, but the Cloudformation console shows the mixed case version.

It sounds like mixed case names were breaking deployments for other stacks, in that case I would prefer if the construct threw an exception on invalid names instead of silently lowercasing the name. It still sucks for me, but at least it makes it the error obvious and I can take manual steps to correct it.

**Comment by skinny85** [comment]
Thanks for opening the issue @grncdr. I'm very curious how were you able to deploy with SubnetGroup that has a mixed-case name. Any chance you could show us your CloudFormation template?

Thanks,
Adam

**Comment by grncdr** [comment]
The full template is pretty large and includes some more-or-less private details, so I've included what I think are the most relevant excerpts below. If you still want to see the full template I can e-mail you.

<details>
<summary>
Source code in custom 'PSPDFKit' stack constructor

</summary>

```ts
    const subnetGroup = new SubnetGroup(this, 'NewDatabaseSubnetGroup', {
      vpc: sharedInfrastructure.vpc,
      description: 'Private subnets in Fargate VPC',
      subnetGroupName: 'PSPDFKit',
      vpcSubnets: {
        subnets: sharedInfrastructure.vpc.privateSubnets,
      },
    })
```
</details>

<details>
<summary>
Output in <code>cdk.out/PSPDFKit.template.json</code>

</summary>

```json
"NewDatabaseSubnetGroup": {
      "Type": "AWS::RDS::DBSubnetGroup",
      "Properties": {
        "DBSubnetGroupDescription": "Private subnets in Fargate VPC",
        "SubnetIds": [
          {
            "Fn::ImportValue": "DropscanStack:ExportsOutputRefVPCPrivateSubnet1Subnet8BCA10E01F79A1B7"
          },
          {
            "Fn::ImportValue": "DropscanStack:ExportsOutputRefVPCPrivateSubnet2SubnetCFCDAA7AB22CF85D"
          },
          {
            "Fn::ImportValue": "DropscanStack:ExportsOutputRefVPCPrivateSubnet3Subnet3EDCD457113A215F"
          }
        ],
        "DBSubnetGroupName": "PSPDFKit"
      },
      "Metadata": {
        "aws:cdk:path": "PSPDFKit/NewDatabaseSubnetGroup/Default"
      }
```
</details>

<details>
<summary>
Result of <code>aws cloudformation get-template --stack-name PSPDFKit</code>

</summary> 

Actually, since this is again huge, I've used the following pipeline, apologies for the ruby stuff in the middle, it was the quickest way to parse the YAML template content hidden in the JSON response 😉 

```sh
aws cloudformation get-template --stack-name PSPDFKit \
  | jq -r .TemplateBody
  | ruby -r yaml -r pp -e 'pp YAML.load(STDIN)["Resources"]["NewDatabaseSubnetGroup"]["Properties"]'
```

```ruby
{"DBSubnetGroupDescription"=>"Private subnets in Fargate VPC",
 "SubnetIds"=>
  [{"Fn::ImportValue"=>
     "DropscanStack:ExportsOutputRefVPCPrivateSubnet1Subnet8BCA10E01F79A1B7"},
   {"Fn::ImportValue"=>
     "DropscanStack:ExportsOutputRefVPCPrivateSubnet2SubnetCFCDAA7AB22CF85D"},
   {"Fn::ImportValue"=>
     "DropscanStack:ExportsOutputRefVPCPrivateSubnet3Subnet3EDCD457113A215F"}],
 "DBSubnetGroupName"=>"PSPDFKit"}
```

</details>

<details>
<summary>The output of <code>aws rds describe-db-subnet-groups --db-subnet-group-name PSPDFKit</code> (here we finally see lowercase).</summary>

```json
{
    "DBSubnetGroups": [
        {
            "DBSubnetGroupName": "pspdfkit",
            "DBSubnetGroupDescription": "Private subnets in Fargate VPC",
            "VpcId": "vpc-XXXXXX",
            "SubnetGroupStatus": "Complete",
            "Subnets": [
                {
                    "SubnetIdentifier": "subnet-XXXXXXX",
                    "SubnetAvailabilityZone": {
                        "Name": "eu-central-1a"
                    },
                    "SubnetOutpost": {},
                    "SubnetStatus": "Active"
                },
                {
                    "SubnetIdentifier": "subnet-XXXXXXX",
                    "SubnetAvailabilityZone": {
                        "Name": "eu-central-1b"
                    },
                    "SubnetOutpost": {},
                    "SubnetStatus": "Active"
                },
                {
                    "SubnetIdentifier": "subnet-XXXXXX",
                    "SubnetAvailabilityZone": {
                        "Name": "eu-central-1c"
                    },
                    "SubnetOutpost": {},
                    "SubnetStatus": "Active"
                }
            ],
            "DBSubnetGroupArn": "arn:aws:rds:eu-central-1:ACCOUNT_ID:subgrp:pspdfkit"
        }
    ]
}
```

</details>

It seems like the case is preserved everywhere except RDS.

I don't know if there could be regional differences with CloudFormation, but this is all running in the eu-central-1 (Frankfurt) region.

**Comment by skinny85** [comment]
Thanks @grncdr!

Can you also show me the template fragments that actually use `NewDatabaseSubnetGroup`?

**Comment by grncdr** [comment]
Sure, the only other part of the template that uses the `NewDatabaseSubnetGroup`  is an RDS instance:

```json
    "DatabaseB269D8BB": {
      "Type": "AWS::RDS::DBInstance",
      "Properties": {
        "DBInstanceClass": "db.t2.small",
        "AllocatedStorage": "20",
        "AutoMinorVersionUpgrade": true,
        "CopyTagsToSnapshot": true,
        "DBName": "pspdfkit",
        "DBSubnetGroupName": {
          "Ref": "NewDatabaseSubnetGroup"
        },
        "DeletionProtection": true,
        "Engine": "postgres",
        "EngineVersion": "9.6",
        "MasterUsername": {
          "Fn::Join": [
            "",
            [
              "{{resolve:secretsmanager:arn:",
              {
                "Ref": "AWS::Partition"
              },
              ":secretsmanager:eu-central-1:ACCOUNT_ID:secret:SECRET_NAME:SecretString:username::}}"
            ]
          ]
        },
        "MasterUserPassword": {
          "Fn::Join": [
            "",
            [
              "{{resolve:secretsmanager:arn:",
              {
                "Ref": "AWS::Partition"
              },
              ":secretsmanager:eu-central-1:ACCOUNT_ID:secret:SECRET_NAME:SecretString:password::}}"
            ]
          ]
        },
        "MultiAZ": false,
        "StorageType": "gp2",
        "VPCSecurityGroups": [
          {
            "Fn::GetAtt": ["NewDatabaseSecurityGroup766D0AAB", "GroupId"]
          }
        ]
      },
      "UpdateReplacePolicy": "Retain",
      "DeletionPolicy": "Retain",
      "Metadata": {
        "aws:cdk:path": "PSPDFKit/Database/Resource"
      }
    },
```

**Comment by skinny85** [comment]
Right. So how can this work?

`{ "Ref": "NewDatabaseSubnetGroup" }` is `"PSPDFKit"`, which is not the name of an Subnet Group in RDS.

Can you add an Output that uses `{ "Ref": "NewDatabaseSubnetGroup" }` to the template, and confirm that it returns `"PSPDFKit"`?

**Comment by grncdr** [comment]
> Right. So how can this work?

:shrug: no idea 😅 


> `{ "Ref": "NewDatabaseSubnetGroup" }` is `"PSPDFKit"`, which is not the name of an Subnet Group in RDS.

I know, but it is working. I think the RDS API is actually case-insensitive (e.g. it lowercases subnet names internally). I say that because the `aws rds describe-db-subnet-groups` command works even if I type in something like `pSpDfKiT`.

> Can you add an Output that uses `{ "Ref": "NewDatabaseSubnetGroup" }` to the template, and confirm that it returns `"PSPDFKit"`?

Sure, I added the following code to my stack constructor and deployed:

```ts
new CfnOutput(this, 'NewDatabaseSubnetGroupName', {value: subnetGroup.subnetGroupName})
```

And in the CloudFormation console I see this:

<img width="1290" alt="Bildschirmfoto 2021-04-22 um 15 58 33" src="https://user-images.githubusercontent.com/82634/115727105-9a516180-a383-11eb-9590-9af9adf28943.png">

**Comment by grncdr** [comment]
I also tested calling the RDS `DescribeDBSubnetGroups` operation directly from the node `aws-sdk` with a mixed-case subnet name (in case the CLI was somehow normalizing the name) and that also worked.

**Comment by skinny85** [comment]
> > Right. So how can this work?
> 
> 🤷 no idea 😅
> 
> > `{ "Ref": "NewDatabaseSubnetGroup" }` is `"PSPDFKit"`, which is not the name of an Subnet Group in RDS.
> 
> I know, but it is working. I think the RDS API is actually case-insensitive (e.g. it lowercases subnet names internally). I say that because the `aws rds describe-db-subnet-groups` command works even if I type in something like `pSpDfKiT`.

That's an interesting hypothesis, but the error report in https://github.com/aws/aws-cdk/issues/13976 definitely seems to suggest otherwise 🙂.

**Comment by grncdr** [comment]
Very interesting! I noticed in that report the subnet group itself is created successfully, but the RDS cluster fails to be created. This gives me two ideas and an idea for a fix:

1. Is it possible that this is Aurora-specific? I'm using Postgres.
2. Is it possible this only fails when _creating_ an RDS cluster? My cluster was *imported* into CloudFormation, and then updated to use the database subnet in question. (Hence the "New" in the name).
3. Fix idea: In either case, it seems like only the subnet group name property of the _cluster_ is actually case sensitive. If the lowercase transform was done in the Cluster construct (using cfn string functions) instead of the subnet group that should resolve both issues.


Finally, full disclosure: since I was importing & updating existing resources, it's very possible that I encountered the same bug, worked around it manually, then forgot.

**Comment by skinny85** [comment]
> 3\. Fix idea: In either case, it seems like only the subnet group name property of the _cluster_ is actually case sensitive. If the lowercase transform was done in the Cluster construct (using cfn string functions) instead of the subnet group that should resolve both issues.

This would be amazing, unfortunately, there's no `Fn::StringToLowerCase` 😕.

**Comment by grncdr** [comment]
Ah, I assumed too much. 😄
 
Since it seems like I've just managed to create a weird/unique state, I've fixed my stack by editing the template to lowercase the subnet group name and manually updating in the CloudFormation console. I no longer have any differences in `cdk diff` so this issue can probably be closed.

However, that brings up a question: why does `cdk diff` show that updating the subnet group name will _replace_ both the subnet group and database instance, when CloudFormation will actually modify the subnet group in place?

**Comment by skinny85** [comment]
That's actually correct. If you look at the CloudFormation docs, [changing the Subnet Group of an Instance](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html#cfn-rds-dbinstance-dbsubnetgroupname) requires replacing the Instance; and changing the [name of the SubnetGroup](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbsubnet-group.html#cfn-rds-dbsubnetgroup-dbsubnetgroupname) replaces the Subnet Group.

So replacing the name of the Subnet Group, transitively, also replaces the Instance.
