### ISSUE TITLE
(aws-logs.CrossAccountDestination): No statement block with AWS provider found.

### ISSUE THREAD

**Issue by Cloudrage** [aws/aws-cdk#14274]
When trying to create a policy for **CrossAccountDestination** logs I've an error :
`Error occurred while parsing policy: no statement block with AWS provider found. (Service: AWSLogs; Status Code: 400; Error Code: InvalidParameterException; Request ID: c4b2dad5-303d-4d9b-8461-d7be6c10d031; Proxy: null)`

### Reproduction Steps

The code : 
```
    LogsCrossAccountDestination.addToPolicy(
      new iam.PolicyStatement({
        principals:[new iam.AnyPrincipal],
        resources: ['*'],
        actions: [
          'logs:PutSubscriptionFilter'
        ]
      })
    );
```

### What did you expect to happen?

Want to have that generated policy : 
```
{
  "Version" : "2012-10-17",
  "Statement" : [
    {
      "Effect" : "Allow",
      "Principal" : {
        "AWS" : "*"
      },
      "Action" : "logs:PutSubscriptionFilter",
      "Resource" : "*"
    }
  ]
}
```

### What actually happened?

Indeed, the "cdk synth" show : 
`DestinationPolicy: '{"Statement":[{"Action":"logs:PutSubscriptionFilter","Effect":"Allow","Principal":"*","Resource":"*"}],"Version":"2012-10-17"}'`

And not { "AWS": "*" } like described : 
https://docs.aws.amazon.com/cdk/api/latest/docs/aws-iam-readme.html#iam-principals

### Environment

  - **CDK CLI Version  : 1.98.0**
  - **OS               : Linux**
  - **Language (Version): TypeScript**

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
Add `()`

```
        principals:[new iam.AnyPrincipal()],
```

**Comment by rix0rrr** [comment]
You can try `new ArnPricipal('*')`

**Comment by rix0rrr** [comment]
Root cause: there is a simplification that happens somewhere in the IAM library, because the IAM JSON spec says `*` and `{ AWS: '*' }` are equivalent. Apparently not all services agree.

https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_principal.html

**Comment by Cloudrage** [comment]
Hi @rix0rrr,

Thanks for your reply.
I've also tested that alternative but unfortunatly don't work too :(

`Error occurred while parsing policy: no statement block with AWS provider found. (Service: AWSLogs; Status Code: 400; Error`

The "synth" :
`DestinationPolicy: '{"Statement":[{"Action":"logs:PutSubscriptionFilter","Effect":"Allow","Principal":"*","Resource":"*"}],"Version":"2012-10-17"}'`


The code : 
```
    LogsCrossAccountDestination.addToPolicy(
      new iam.PolicyStatement({
        principals:[new iam.ArnPrincipal('*')],
        resources: ['*'],
        actions: [
          'logs:PutSubscriptionFilter'
        ]
      })
    );
```

**Comment by hoegertn** [comment]
AFAIK: `AWS: *` means every AWS principal (users, roles, services) and `*` means anonymous access

**Comment by rix0rrr** [comment]
It looks even more subtle than that. I have an internal customer saying their DMS subscription doesn't work with `{ AWS: * }`, and all parts of that are fully in AWS.
