### ISSUE TITLE
python: numerous type errors and mypy failures in recent versions of several modules due to type inconsistency in _jsii_proxy_class__()

### ISSUE THREAD

**Issue by jeremiq** [aws/aws-cdk#14286]
### Summary
After updating the `aws_cdk` python library, I've started seeing numerous typing failures when running mypy checks against previously valid, working code.

The failures occur across multiple modules including, 

Summary of Mypy issues that I have seen: 

#### IAM 
```shell 
stack_with_type_failures.py:11: error: List item 0 has incompatible type "ServicePrincipal"; expected "IPrincipal"
stack_with_type_failures.py:11: note: Following member(s) of "ServicePrincipal" have conflicts:
stack_with_type_failures.py:11: note:     Expected:
stack_with_type_failures.py:11: note:         def __jsii_proxy_class__() -> Type[_IPrincipalProxy]
stack_with_type_failures.py:11: note:     Got:
stack_with_type_failures.py:11: note:         def __jsii_proxy_class__() -> Type[_PrincipalBaseProxy]
stack_with_type_failures.py:18: error: List comprehension has incompatible type List[ArnPrincipal]; expected List[IPrincipal]
stack_with_type_failures.py:18: note: Following member(s) of "ArnPrincipal" have conflicts:
stack_with_type_failures.py:18: note:     Expected:
stack_with_type_failures.py:18: note:         def __jsii_proxy_class__() -> Type[_IPrincipalProxy]
stack_with_type_failures.py:18: note:     Got:
stack_with_type_failures.py:18: note:         def __jsii_proxy_class__() -> Type[_PrincipalBaseProxy]
```

#### SQS
```shell  
 note: 'SqsSubscription' is missing following 'ITopicSubscription' protocol member:
  __jsii_proxy_class__
```

#### Glue
```shell 
error: Item "IResolvable" of "Union[IResolvable, DatabaseInputProperty]" has no attribute "name"
error: Item "IResolvable" of "Union[IResolvable, ConnectionInputProperty]" has no attribute "name"
```

### Reproduction Steps

I have created a minimal reprod case here, https://github.com/jeremiq/cdk-typing-bug with instructions in the `README.md` that illustrate, for example, the IAM typing failures. 

### What did you expect to happen?

The python library should have consistent types and pass a mypy check when correctly invoked. 

### What actually happened?

Mypy checks failed. 

### Environment

  - **CDK CLI Version  :** n/a
  - **Framework Version:** many, but including latest, `1.100.0`
  - **Node.js Version:** `v15.14.0`
  - **OS               :** OSX, `10.15.7`
  - **Language (Version):** Python `3.8.9`
### Other

I've dug into this a bit, and I suspect the root cause of the issue may actually lie inside `jsii`.

I've been able to avoid these failures by using an older version of aws_cdk (`1.86.0`). Unfortunately, this only continues to work when I further version lock `jsii` to 1.17.1. This older version also forces an older version of the `constructs` library 

I'm happy to try to pinpoint the failure further if it's not obvious to anyone here wiht more knowledge of the cdk --> constructs --> jsii dependency stack. 

I'd also be happy to add a few more details to that repro case, in case the problems with the sqs and glue (and likely other) modules are not obviously related to the issue as stated here. 

--- 

This is :bug: Bug Report

**Comment by peterwoodworth** [comment]
Thank you for this report! 

I can confirm that I can reproduce this error

If this is a JSII bug, it would be better to submit this to the JSII repo https://github.com/aws/jsii. @MrArnoldPalmer what do you think about this?

**Comment by jeremiq** [comment]
Thanks for confirming @peterwoodworth! I'm honestly not sure yet of where the exact problem lies. 

In my simple repro case, going back to an older version of aws-cdk seems to avoid the problems, for example I do see this...

 ```shell
pip install aws-cdk.aws-iam==1.86.0
mypy stack_with_type_failures.py
Success: no issues found in 1 source file
```

Let me know if any other info would make this easier to nail down!

**Comment by MrArnoldPalmer** [comment]
hey @jeremiq, we have an issue for this [here](https://github.com/aws/aws-cdk/issues/13474). Gonna close this but follow that one for updates. Someone has a test in JSII to repro and that will help us find a solution.
