### ISSUE TITLE
(aws-lambda-python): docker image missing bash executable

### ISSUE THREAD

**Issue by jfrconley** [aws/aws-cdk#14285]
The AWS lambda python package fails to bundle my python application within docker. It successfully builds the image and installs dependencies from my requirements.txt, but fails on the final step of actually bundling the app. From the output, it seems like bash is missing from the python build docker image.

EDIT: This only happens when the runtime is set to python 3.7 or 3.8, not 3.6. Seems to be an issue with 3.7 build image downloaded for both of those runtimes.

Build log:
(some paths redacted)
```
 ---> d18a59d69219
Step 9/9 : CMD [ "python" ]
 ---> Running in 1a6272d30834
Removing intermediate container 1a6272d30834
 ---> 55b5051dae8b
Successfully built 55b5051dae8b
Successfully tagged cdk-2b88e34f016a118c98bb3bc5844004fb3eec7ce85763ed1251d02eaaf24f746a:latest
Bundling asset ****/****/****/Code/Stage...
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"bash\": executable file not found in $PATH": unknown.
(node:371444) UnhandledPromiseRejectionWarning: Error: Failed to bundle asset ****/****/****/Code/Stage, bundle output is located at ****/cdk.out/asset.d3f3f02628e08310faa50949b0167cbbbc1e9152fabcfdc5f4d960cfeecd866d-error: Error: docker exited with status 127
```

### Reproduction Steps

Create a PythonFunction with a valid entrypoint and run `cdk deploy`. The problem does not occur when using `cdk synth`.

### What did you expect to happen?

The application should be bundled and deployed 

### What actually happened?

The application failed to bundle, causing the deployment to fail

### Environment

  - **CDK CLI Version  :** 1.100.0 (build d996c6d)
  - **Framework Version:**
  - **Node.js Version:** v14.15.0
  - **OS               :** Ubuntu 20.04
  - **Language (Version):** TypeScript (4.0.2)

### Other

--- 

This is :bug: Bug Report

**Comment by eladb** [comment]
@adamelmore can you please take a look?

**Comment by redbaron** [comment]
It can possibly be solved by using `lambda.Code.fromDockerBuild` (with `imagePath` option set to `/asset-output`) instead of `lambda.Code.fromAsset`, as former doesn't run the container and just copies files from a predfined path. It will also make it a bit faster to build, as you wont need to install rsync in the bundler image and could use SAM bundler as is.

**Comment by eladb** [comment]
@jfrconley can you advise if @redbaron's solution works for you?

**Comment by redbaron** [comment]
@eladb , my "solution" was a comment about a possible change to CDK. It is not something what end user could do without forking a package.

**Comment by eladb** [comment]
@jfrconley I ran some tests and it seems like the latest version of public.ecr.aws/sam/build-python3.7 includes `bash`, so I believe your issue should now be resolved.

I am closing this issue for now. Can you please verify and reopen the issue if your issue persists?
