### ISSUE TITLE
aws-route53-targets | v1.100.0 | 'ApiGatewayv2Domain' class does not exist

### ISSUE THREAD

**Issue by kensukesaito** [aws/aws-cdk#14287]
In v1.100.0, 'ApiGatewayv2Domain' class does not exist. In v1.99.0, it did exist.

```typescript
// API Gateway V2 custom domains
new route53.ARecord(this, 'AliasRecord', {
  zone,
  target: route53.RecordTarget.fromAlias(new alias.ApiGatewayv2Domain(domainName)),
});
```

https://docs.aws.amazon.com/cdk/api/latest/docs/aws-route53-targets-readme.html

### Reproduction Steps

https://codesandbox.io/s/elastic-lewin-hu6h0

### What did you expect to happen?

The above code works.

--- 

This is :bug: Bug Report

**Comment by NetaNir** [comment]
The API was removed and replaced with from the release [notes](https://github.com/aws/aws-cdk/releases/tag/v1.100.0):

```
route53-targets: ApiGatewayv2Domain was replaced with ApiGatewayv2DomainProperties which accepts regionalDomainName and regionalHostedZoneId
```

It was an experimental API that created a dependency between a stable module (stepfunctions-tasks) to experimental module (apigatewayv2). These type of dependencies are not allowed anymore, hence the API needed to be changed. Apologize for the inconvenience.
