### ISSUE TITLE
(events): EventPattern produces mismatched key when using detailType for S3 events

### ISSUE THREAD

**Issue by ZypherJ** [aws/aws-cdk#14282]
When using the EventPattern class to create a pattern for a CfnRule, if you include the detailType property, it produces an EventPattern json with the key "detailType" when deployed. This does not match the pattern produced when creating an event pattern in console.

### Reproduction Steps

```
final EventPattern pattern = EventPattern.builder()
                .source(ImmutableList.of("aws.s3"))
                .detailType("AWS API Call via CloudTrail")
                .detail(ImmutableMap.of(
                        "eventSource", ImmutableList.of("s3.amazonaws.com"),
                        "eventName", ImmutableList.of("PutObject")))
                .build();
```

### What did you expect to happen?

Events produced by S3 data events feature the property "detail-type". If you create an S3 rule in console, this also produces json with the key "detail-type". I expected the json produced by EventPattern to also match "detail-type".

### What actually happened?

The json produced had the property key "detailType", which does not match the key found in the S3 event json produced by CloudTrail, causing the rule to never fire.

### Environment

  - **CDK CLI Version  :** 1.96.0
  - **Framework Version:** 1.96
  - **Node.js Version:** v12.22.1
  - **OS               :** Amazon Linux 2
  - **Language (Version):** Java

### Other

--- 

This is :bug: Bug Report

**Comment by ZypherJ** [comment]
This issue looks like a duplicate of the following:

https://github.com/aws/aws-cdk/issues/5703

The problem is that I'm mixing L1 and L2 types, (the rest of my code uses CfnRule). I'll have to figure out how to migrate my code to one or the other.

**Comment by rix0rrr** [comment]
Closing as duplicate.
