### ISSUE TITLE
Autoscaling Group generated without AvailabilityZones or vpcZoneIdentifier

### ISSUE THREAD

**Issue by dpllpd** [aws/aws-cdk#1429]
When creating an autoscaling group, it does not seem that there is a way to specify either AvailabilityZones or VPCZoneIdentifier. In the code it says that "The ASG spans all availability zones". When I look at the generated template, AvailabilityZones is not specified and VPCZoneIdentifier is empty. As a result, creation of the stack errors out with the message that the AvailabilityZones have to be specified. I had to patch the resulting template with propertyOverrides to get it to work.

**Comment by dpllpd** [comment]
Sure. 
The vpc reference is created like this. The vpc itself already exists, I don't need to create it here.
const vpc = VpcNetwork.import(this.parent, this.serviceName + 'ExternalVpc', { vpcId: vpcName, availabilityZones: ['us-east1a', 'us-east-1b'], });
Nothing else is done as far as security groups, I commented it all out. The autoscaling group is created like this:
 group = new autoscaling.AutoScalingGroup(this.parent, name, { vpc, minSize: 1, maxSize: 4, desiredCapacity: Number(nodeCount), instanceType: new InstanceType(nodeType), machineImage: new GenericLinuxImage(amiMap), keyName: key, tags: { Name: name }, });

This is the security group that I get in the template. I don't know where it comes from and how to suppress it other than through template manipulations. I certainly don't need it.
 DataAutoScalingGroupInstanceSecurityGroupD1712E13: Type: AWS::EC2::SecurityGroup Properties: GroupDescription: cb6/DataAutoScalingGroup/InstanceSecurityGroup SecurityGroupEgress: - CidrIp: 0.0.0.0/0 Description: Allow all outbound traffic by default IpProtocol: "-1" SecurityGroupIngress: [] Tags: - Key: Name Value: DataAutoScalingGroup VpcId: vpc-07ad58ac5ad4caea8 Metadata: aws:cdk:path: cb6/DataAutoScalingGroup/InstanceSecurityGroup/Resource
Thanks.
David    On Thursday, December 27, 2018, 5:24:59 AM EST, Romain Marcadier-Muller <notifications@github.com> wrote:  
 
 
Hey @dpllpd would you be able to provide code for a minimal reproduction?

**Comment by RomainMuller** [comment]
Are you using an imported `VpcNetwork` (from `VpcNetwork.import`)? I think this might be the issue.
You will only be able to use an imported `VpcNetwork` with an `AutoScalingGroup` if you specify the `publicSubnetIds` and/or `isolatedSubnetIds` in the import props.

This might be fairly inconvenient to set-up, and you might be able to instead use the `VpcNetworkProvider` class to obtain the full props to pass to `import`. It uses a CDK context provider and will automatically determine the VPC's components (Subnets & all) by making a describe call on the target account (the results of which will be cached in `cdk.json`, so that it needs to be done only once).

**Comment by erdalkucukk** [comment]
Hi Romain,

I am facing the same issue and as you mentioned above, I use VpcNetwork while defining the VPC and use the construct while importing to the autoscaling group. 

You suggested to use VpcNetworkProvider but when I try I still get the same error regarding the Availability Zones, Can you provide a working example if possible?

More or less this is the code

    const vpc = new ec2.VpcNetwork(this, 'vpc', {
      maxAZs: 3,
      natGateways: 0,
      cidr: '10.0.0.0/16',
      subnetConfiguration: [{ cidrMask: 20, name: 'Default-', subnetType: ec2.SubnetType.Public }],  
      defaultInstanceTenancy: ec2.DefaultInstanceTenancy.Default,  
    });

    const cluster = new ecs.Cluster(this, 'Cluster', {
      vpc: vpc,
      clusterName: 'Cluster'  
    });

    const autoScalingGroup = new autoscaling.AutoScalingGroup(this, 'Cluster-ASG', {
      vpc: vpc,
      minSize: 1,
      maxSize: 4,
      instanceType: new ec2.InstanceType('t2.xlarge'),
      machineImage: new ecs.EcsOptimizedAmi(),
      desiredCapacity: 1,
    });

**Comment by renatomjr** [comment]
I faced the same issue but I think the docs gives us a hint: 

https://awslabs.github.io/aws-cdk/refs/_aws-cdk_aws-ec2.html
> Our default VpcNetwork class creates a private and public subnet for every availability zone. Classes that use the VPC will generally launch instances into all private subnets, and provide a parameter called vpcPlacement to allow you to override the placement. Read more about subnets.

When I add the `vpcPlacement` to ASG declaration it works:

```js
const autoScalingGroup = new autoscaling.AutoScalingGroup(this, 'Cluster-ASG', {
  vpc: vpc,
  minSize: 1,
  maxSize: 4,
  instanceType: new ec2.InstanceType('t2.xlarge'),
  machineImage: new ecs.EcsOptimizedAmi(),
  desiredCapacity: 1,
  vpcPlacement: {
    subnetsToUse: SubnetType.Public
  }
});
```

**Comment by erdalkucukk** [comment]
Yes the above solution fixes the problem, thank you very much! I saw the documentation but whatever I tried with vpcPlacement, it was complaining, this is the correct usage it seems.
