### ISSUE TITLE
cdk-assets: cannot publish DockerImageAsset

### ISSUE THREAD

**Issue by tmpfs** [aws/aws-cdk#14292]
When using `DockerImageAsset` the CDK fails to push to the ECR repository.

### Reproduction Steps

This is the stack that causes the problem, all my other stacks work as expected. The purpose of this stack is to run database migrations via a docker container.

```typescript
import * as cdk from '@aws-cdk/core';
import * as ecs from "@aws-cdk/aws-ecs";
import * as ec2 from '@aws-cdk/aws-ec2';

import { DockerImageAsset } from "@aws-cdk/aws-ecr-assets";
import { Environment, CustomStackProps, getDatabaseUrl } from './common';

export class MigrateStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: CustomStackProps) {
    super(scope, id, props);

    const databaseUrl = getDatabaseUrl(this);

    const cluster = new ecs.Cluster(this, 'MigrateCluster', {
      vpc: props?.netInfo.vpc as ec2.IVpc,
    });

    cluster.addCapacity('DefaultAutoScalingGroupCapacity', {
      instanceType: new ec2.InstanceType("t2.micro"),
      desiredCapacity: 1,
    });

    const migration = new DockerImageAsset(this, 'MigrateImageAsset', {
      directory: '../backend',
      file: 'Dockerfile-Migrate',
    });
    const image = ecs.ContainerImage.fromDockerImageAsset(migration);

    const taskDefinition = new ecs.Ec2TaskDefinition(this, 'MigrateTaskDef');
    taskDefinition.addContainer('MigrateContainer', {
      image,
      command: ['./migrate.sh'],
      environment: {'DATABASE_URL': databaseUrl},
      memoryLimitMiB: 2048,
    });

    const ecsService = new ecs.Ec2Service(this, 'MigrateService', {
      cluster,
      taskDefinition,
    });
  }
}
```

### What did you expect to happen?

I expected the stack to deploy and execute the container with the supplied command.

### What actually happened?

```
[0%] start: Publishing 8e5bc898b3f1843c8bd64df34a4853e5ec7d2e30d68487b44264f94a8cc19f3a:current
Assuming role failed: this._credentials.getPromise is not a function
[100%] fail: Could not assume role in target account (did you bootstrap the environment with the right '--trust's?): this._credentials.getPromise is not a function
```

I am not using the new style synthesis so cannot use the `--trust` option and I don't think that is the real cause of the problem as I tried migrating to new style synthesis and it still failed (afterwards I reverted).

### Environment

  - **CDK CLI Version  :** 1.100.0
  - **Framework Version:**
  - **Node.js Version:** 12.22.1
  - **OS               :**: Linux opal 4.8.0-53-generic #56~16.04.1-Ubuntu
  - **Language (Version):** 4.2.4

### Other

We are using a plugin to handle deploying to different `stage` and `production` accounts but I don't think this is the cause of the problem as all the other stacks work ok.

--- 

This is :bug: Bug Report

**Comment by tmpfs** [comment]
For anyone that stumbles across this, after posting this I noticed that `DockerImageAsset` is marked as experimental in the documentation so I changed my stacks to use images from an ECR repository (`ecs.ContainerImage.fromEcrRepository`) to move past this issue that was preventing a migration to AWS.

**Comment by eladb** [comment]
@rix0rrr `Assuming role failed: this._credentials.getPromise is not a function` seems like it's a bug in `cdk-assets`. Can you take a look?

**Comment by rix0rrr** [comment]
> We are using a plugin to handle deploying to different `stage` and `production` accounts but I don't think this is the cause of the problem as all the other stacks work ok.

I do think the plugin is going to be cause of these issues. Can you share a little more information about the plugin and the commands you're running?
