### ISSUE TITLE
(AWS CDK): output-files on cdk.json

### ISSUE THREAD

**Issue by henriqueribeiro** [aws/aws-cdk#14307]
Accept `output-files` parameter on `cdk.json`

### Use Case

I always want to write a json file with  stack's outputs. It would be nice that I could add it to `cdk.sjon` instead of passing `output-files` on the cli.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
Sounds good
