### ISSUE TITLE
Cross Account Pipeline Getting Failed with No IAM Role Found.

### ISSUE THREAD

**Issue by rajnikhil17** [aws/aws-cdk#14314]
**EDIT**: see this comment: https://github.com/aws/aws-cdk/issues/14314#issuecomment-826907182 for what needs to be done for this issue.

-------------------------------------

I am trying to create a cross-account pipeline in python i.e,
**Pipeline will be in dev, it should be able to deploy into the production account.**
I found **CloudFormationCreateUpdateStackAction**
construct in CDK python documentation,
**I have added two stages, one for deploying the stack into dev and another stage for deploying the stack into production,**
I was able to deploy the stack in dev with no issues,
In the dev deployment stage, I am not passing any role parameters for dev.
**I see attributes for the CloudFormatonCreateUpdateStackAction construct as deployment_role and role,**
**Created Cross-Account Role and Another Role for Deploying CloudFormaton Stack in Production Account.**
I am trying to pass the above roles in the construct, once I deploy the Pipeline Stack, It is throwing the error like,
**The role with the name CrossAccountRole cannot be found..**

Please find the code attached as Images,

![Line 1-29.jpg](https://user-images.githubusercontent.com/22904814/115616852-4fe1cd80-a30e-11eb-97a3-1c5f8dd06ddf.jpg)
![Line 30-58.jpg](https://user-images.githubusercontent.com/22904814/115616867-54a68180-a30e-11eb-92fc-c462e2f72d01.jpg)
![Line 58-84.jpg](https://user-images.githubusercontent.com/22904814/115616877-58d29f00-a30e-11eb-9a00-6966e0e76d99.jpg)
![Line 82-110.jpg](https://user-images.githubusercontent.com/22904814/115616891-5cfebc80-a30e-11eb-83fb-235012329b23.jpg)
![Line 110-138.jpg](https://user-images.githubusercontent.com/22904814/115616909-625c0700-a30e-11eb-950a-784e28cf4e5b.jpg)
![Line 138-166.jpg](https://user-images.githubusercontent.com/22904814/115616980-79025e00-a30e-11eb-9dc4-2fe80ec1d221.jpg)
![Line 165-190.jpg](https://user-images.githubusercontent.com/22904814/115617005-7dc71200-a30e-11eb-861d-1343bba0bfd2.jpg)

**Comment by skinny85** [comment]
I see `assume_role_arn` is taken from the context (`node.try_get_context('assume_role_arn'`).

Can you please show a) your `cdk.json`, b) `cdk.context.json`, c) the entire command you invoke that makes this fail.

Also, please do not use images for your code. They make it very difficult to see what's going on.

Please copy&paste the appropriate code to the issue instead.

**Comment by rajnikhil17** [comment]
a) cdk.json

{
  "app": "python3 app.py",
  "context": {
    "@aws-cdk/core:enableStackNameDuplicates": "true",
    "aws-cdk:enableDiffNoFail": "true",
    "@aws-cdk/core:stackRelativeExports": "true",
    "@aws-cdk/aws-ecr-assets:dockerIgnoreSupport": true,
    "@aws-cdk/aws-secretsmanager:parseOwnedSecretName": true,
    "@aws-cdk/aws-kms:defaultKeyPolicies": true,
    "@aws-cdk/aws-s3:grantWriteWithoutAcl": true,
    "@aws-cdk/aws-ecs-patterns:removeDefaultDesiredCount": true,
    "emails_for_prod_deploy_approval": [],
    "connection_arn": "arn:aws:codestar-connections:us-east-1:XXXXXXXXXX:connection/abcdef-ghijkl-mnopqrs-tuvwxyz",
    "branch": "",
    "repo": "",
    "owner": "",
    "production_account_id": "222222222222",
    "role_arn":  "arn:aws:iam::111111111111:role/DEVAdminsRole",
    "assume_role_arn":  "arn:aws:iam::222222222222:role/CrossAccountAccess",
    "codepipeline_role_arn":  "arn:aws:iam::222222222222:role/CodePipelineCrossAccountRole",
    "cloudformation_role_arn":  "arn:aws:iam::222222222222:role/CloudFormationDeploymentRole"
  }
}


b) I don't have cdk.context.json.

c)  Command:
                          cdk  deploy pipelinestack.

Error  Message: 


cdk deploy PipelineStack

Do you wish to deploy these changes (y/n)? y
PipelineStack: deploying...
PipelineStack: creating CloudFormation changeset...


9:34:34 AM | CREATE_FAILED        | AWS::IAM::Policy            | prodCrossAccountRole/Policy
[██████▉···················································] (3/25)


9:34:34 AM | CREATE_FAILED        | AWS::IAM::Policy            | prodCrossAccountRole/Policy
9:34:34 AM | CREATE_FAILED        | AWS::IAM::Policy            | prodCrossAccountRolePolicy62B79F2D
The role with name CrossAccountAccessforMSD0017 cannot be found. (Service: AmazonIdentityManagement; Status Code: 4
04; Error Code: NoSuchEntity; Request ID: a8c975e3-bfaa-497f-9491-6c1f76034d90; Proxy: null)

        new Policy (/tmp/jsii-kernel-8e1yud/node_modules/@aws-cdk/aws-iam/lib/policy.js:56:26)
        \_ Import.addToPrincipalPolicy (/tmp/jsii-kernel-8e1yud/node_modules/@aws-cdk/aws-iam/lib/role.js:148:42)
        \_ Function.addToPrincipal (/tmp/jsii-kernel-8e1yud/node_modules/@aws-cdk/aws-iam/lib/grant.js:90:65)
        \_ Function.addToPrincipalOrResource (/tmp/jsii-kernel-8e1yud/node_modules/@aws-cdk/aws-iam/lib/grant.js:45:30)
        \_ Key.grant (/tmp/jsii-kernel-8e1yud/node_modules/@aws-cdk/aws-kms/lib/key.js:95:30)
        \_ Key.grantDecrypt (/tmp/jsii-kernel-8e1yud/node_modules/@aws-cdk/aws-kms/lib/key.js:114:21)
        \_ /tmp/tmp5gg09kxm/lib/program.js:7970:134
        \_ Kernel._wrapSandboxCode (/tmp/tmp5gg09kxm/lib/program.js:8582:24)
        \_ /tmp/tmp5gg09kxm/lib/program.js:7970:107
        \_ Kernel._ensureSync (/tmp/tmp5gg09kxm/lib/program.js:8563:28)
        \_ Kernel.invoke (/tmp/tmp5gg09kxm/lib/program.js:7970:34)
[████████████████▏·········································] (7/25)

9:34:34 AM | CREATE_FAILED        | AWS::IAM::Policy            | prodCrossAccountRole/Policy
The role with name CrossAccountAccess cannot be found. (Service: AmazonIdentityManagement; Status Code: 4
04; Error Code: NoSuchEntity; Request ID: a8c975e3-bfaa-497f-9491-6c1f76034d90; Proxy: null)
9:34:38 AM | UPDATE_ROLLBACK_IN_P | AWS::CloudFormation::Stack  | PipelineStack
The following resource(s) failed to create: [ArtifactKeyAliasB27DA94F, ArtifactBucket7410C9EF, prodCrossAccountRole
Policy62B79F2D]. The following resource(s) failed to update: [CdkBuild455F642E, LambdaBuildCF1FE7ED].



 ❌  PipelineStack failed: Error: The stack named PipelineStack failed to deploy: UPDATE_ROLLBACK_COMPLETE
    at Object.waitForStackDeploy (/usr/lib/node_modules/aws-cdk/lib/api/util/cloudformation.ts:307:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Object.deployStack (/usr/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:297:26)
    at CdkToolkit.deploy (/usr/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:180:24)
    at initCommandLine (/usr/lib/node_modules/aws-cdk/bin/cdk.ts:208:9)
The stack named PipelineStack failed to deploy: UPDATE_ROLLBACK_COMPLETE

**Comment by skinny85** [comment]
Right. So the situation is the following:

1. You're telling CDK to use the Role `arn:aws:iam::222222222222:role/CrossAccountAccess`.
2. During deployment, IAM says there is no Role with name `CrossAccountAccess` in account `222222222222`.

So... are you sure you're providing the correct Role name and account?

**Comment by rajnikhil17** [comment]
Yes, I do have the same role in my Production account.

**Comment by skinny85** [comment]
Ah. I think I might know what's happening.

Can you try changing your code to `iam.Role.from_role_arn(..., mutable=False)`, and see if that changes anything?

**Comment by rajnikhil17** [comment]
Now, It is going to the Next Step.
The Production Deploy Stage of the Pipeline is getting failed.

The Error is:
Cross-account pass role is not allowed. (Service: AmazonCloudFormation; Status Code: 403; Error Code: AccessDenied; Request ID: 1d9016ee-5a37-47fd-b23a-142df0e652c9; Proxy: null)

**Comment by skinny85** [comment]
Yes. This is because of [this code](https://github.com/aws/aws-cdk/blob/82143381ef886a3ae39246ba780efca8e24d679d/packages/%40aws-cdk/aws-codepipeline-actions/lib/cloudformation/pipeline-actions.ts#L290-L296).

Basically, the Action needs to create a deployment Role in account `222222222222`, but there is no Stack to create it in. I agree the validation could be better here.

There are a few things you can do here:

1) Pass a `deployment_role`yourself  to `CloudFormationCreateUpdateStackAction`, similarly like you pass `role` now.
2) Create a new Stack in account `222222222222` that imports the `prodCrossAccountRole` (instead of importing it into the Pipeline Stack). This way, CDK will create the new Role in that Stack.

**Comment by rajnikhil17** [comment]
@skinny85 Great, It worked.

Thank You very much.

Was able to deploy the cdk cross account stacks in python using Codepipeline

**Comment by skinny85** [comment]
Awesome @rajnikhil17 , I'm glad you got unblocked.

I'll keep this open to fix the code [here](https://github.com/aws/aws-cdk/blob/82143381ef886a3ae39246ba780efca8e24d679d/packages/%40aws-cdk/aws-codepipeline-actions/lib/cloudformation/pipeline-actions.ts#L290-L296) to take the account from the resources, instead of its Stacks, and also validates that we have somewhere to put that Role in, and fail otherwise.
