### ISSUE TITLE
(aws-cdk): changeset fails with Description attribute mismatch

### ISSUE THREAD

**Issue by shellscape** [aws/aws-cdk#14316]
Upon deploying a stack which has not seen any changes to the local CDK code via `cdk deploy`, we receive a message of:

```
ChangeSet cdk-deploy-change-set cannot be created due to a mismatch with existing attribute Description
```

My first stop was to synth and output the template for the failing stack. The template only had one resource which had a `Description` field. The value in the template matched perfectly to what had been in the code for some time prior, and the Description on the resource in the AWS Console.

Next, I went into the CloudFormation Stack for the failing stack and took a look at the changesets. For each of our failing stacks, there was a pending changeset. Each changeset had `JSON changes` which looked like this:

```json
[
  {
    "resourceChange": {
      "logicalResourceId": "CDKMetadata",
      "action": "Modify",
      "physicalResourceId": "6fffac30-9bfd-11eb-9c43-0e0748486565",
      "resourceType": "AWS::CDK::Metadata",
      "replacement": "Conditional",
      "moduleInfo": null,
      "details": [
        {
          "target": {
            "name": "Analytics",
            "requiresRecreation": "Conditionally",
            "attribute": "Properties"
          },
          "causingEntity": null,
          "evaluation": "Static",
          "changeSource": "DirectModification"
        }
      ],
      "changeSetId": null,
      "scope": [
        "Properties"
      ]
    },
    "hookInvocationCount": null,
    "type": "Resource"
  }
]
```

My initial thought was to delete the pending changesets for the failing services, thinking that maybe they were left over from some interrupted deploy and were causing the conflict. Deleting the changesets just resulted in new pending changesets from subsequent deploy attempts.

Next, I figured I would manually execute the changesets in the failing stacks to see what happened. **Every changeset in every failing stack, suffering from the error above, executed successfully when triggered manually in the AWS Console.** After manually executing, all failing stacks succeeded with `(no changes)` in their success messages via `cdk deploy`

The only possible correlation that I could find in the code here was: https://github.com/aws/aws-cdk/blob/9e421e5b25c43cb9f49ebfb29751a42d73b87e6a/packages/aws-cdk/lib/api/deploy-stack.ts#L250

Other than that, I'm at a loss.

### Reproduction Steps

I'm honestly not sure how to reproduce this. After we initially solved the problem by manually executing the changesets, everything seemed to work as expected.

### What did you expect to happen?

Successful deploys. 

### What actually happened?

Please see above

### Environment

  - **CDK CLI Version  :** 1.98.0
  - **Framework Version:** 1.98.0
  - **Node.js Version:** 14.15.3
  - **OS               :** MacOS
  - **Language (Version):** TS 4.1.3

### Other

--- 

This is :bug: Bug Report

**Comment by shellscape** [comment]
It's worth noting that this is occurring in a monorepo with multiple parallel deployments. The monorepo in question has 14 services and we started seeing this issue with more than one deployment being run at once. This may be a red herring, but that added context may be useful. I suspect that there is some issue with the `executionId` and parallel deploys, but I could find no evidence for that to be the case.

**Comment by rix0rrr** [comment]
This error seems to occur when two CDK invocations create the change set at the same time. They'll try to create a change set with the same name, which is causing this error.

Pass `--change-set-name` to potentially parallel invocations to make sure they create different change sets.

Only one of them will be able to deploy successfully anyway, but at least the error message will be different :)

**Comment by shellscape** [comment]
@rix0rrr appreciate the reply here, but seems like a premature close. Passing the buck to the users for a race/context conflict comes across as (forgive me, I can't think of another word, and I don't mean to be overly negative here) lazy. For a project with as much reach as this one, it seems like an important problem to solve without requiring user intervention. 

At the very least, this should be codified in documentation explicitly, no?

**Comment by cristianrat** [comment]
We are having the exact issue with parallel deployments, which use some shared resources.
So we'll have to extract those resources and deploy them at an earlier stage, and not do parallel

**Comment by elliot-smith** [comment]
For those that run into this issue and are trying to deploy into multiple regions or potentially accounts in separate shells, you can stop this error from occurring by specifying an output directory for the cdk stack.

i.e. Shell 1
`export AWS_REGION=us-west-2 && cdk deploy --all --output /my/custom/cdk-out/directory/1`

Shell 2
`export AWS_REGION=ap-southeast-2 && cdk deploy --all --output /my/custom/cdk-out/directory/2`

**Comment by shellscape** [comment]
@elliot-smith thank you for sharing this. it's wild that CDK doesn't do this by default.

**Comment by shellscape** [comment]
@rix0rrr see previous comment. seems there's an easy fix the team could make here.

**Comment by heitorlessa** [comment]
I've just bumped into this issue when running tests in parallel w/ distinct stacks - did anyone come with a solution?

**Comment by heitorlessa** [comment]
Managed to fix this yesterday. What I was missing was using `--output` within `cdk synth` and using `cdk deploy --app` pointing to the output directory cdk synth created.

Snippet from our parallel deploy piece.

```python
    def deploy(self) -> Dict[str, str]:
        """Synthesize and deploy a CDK app, and return its stack outputs

        NOTE: It auto-generates a temporary CDK app to benefit from CDK CLI lookup features

        Returns
        -------
        Dict[str, str]
            CloudFormation Stack Outputs with output key and value
        """
        stack_file = self._create_temp_cdk_app()
        synth_command = f"npx cdk synth --app 'python {stack_file}' -o {self._cdk_out_dir}"
        deploy_command = (
            f"npx cdk deploy --app '{self._cdk_out_dir}' -O {self.stack_outputs_file} --require-approval=never"
        )
```

**Comment by gagipro** [comment]
encounter same issue, even changing the changeset name. deployments are different regions same account.

**Comment by renatoargh** [comment]
I am getting the exact same prob in Sep 2024

**Comment by MrPrimate** [comment]
I get this error when trying to to a cdk bootstrap to upgrade by bootstrap.

**Comment by PatrikValkovic** [comment]
I think you need to setup both `--output` and `--change-set-name`, so far it seems to work in my case when I deploy multiple stack in parallel from the same shell into the same account and region.
