### ISSUE TITLE
Hardcoded cdk version ssm parameter

### ISSUE THREAD

**Issue by rabbittsoup** [aws/aws-cdk#14313]
The hard coding of the ssm cdk version parameter limits custom bootstrap configurations.  In a large organization, I would like to manage bootstrap resources in a more granular way, with multiple bootstrap stacks.  I am able to create multiple bootstrap stacks and customize all the needed roles and resources through a custom Synthesizer, except for the location of the ssm cdk version parameter.  Our organization has strict naming conventions and the hard coded ssm cdk version parameter does not work in our environment. I would think that if the other bootstrap info is being customized, there would likely be a desire to customize the location of the version parameter.  It seems like it would be easy to add the ssm cdk version parameter location to the options passed into the synthesizer just like the others.

https://github.com/aws/aws-cdk/blob/9e421e5b25c43cb9f49ebfb29751a42d73b87e6a/packages/%40aws-cdk/core/lib/stack-synthesizers/default-synthesizer.ts#L393

and here

https://github.com/aws/aws-cdk/blob/9e421e5b25c43cb9f49ebfb29751a42d73b87e6a/packages/%40aws-cdk/core/lib/stack-synthesizers/default-synthesizer.ts#L482

and here

https://github.com/aws/aws-cdk/blob/9e421e5b25c43cb9f49ebfb29751a42d73b87e6a/packages/%40aws-cdk/core/lib/stack-synthesizers/default-synthesizer.ts#L558

**Comment by rabbittsoup** [comment]
Not actually related to aws-ssm.  More related to aws-cdk stack-synthesizers

**Comment by MrArnoldPalmer** [comment]
Moving this to @rix0rrr as I think its an issue with bootstrap and not ssm? tell me if I'm wrong though.

**Comment by rabbittsoup** [comment]
correct

**Comment by rabbittsoup** [comment]
Man, I've figured out how to intercept and modify 2 of the 3.  But the asset manifest properties one can't be intercepted by any publicly available api calls.  This one has me blocked.  I believe my only workarounds are to manually read in the manifest file, modify, and write back out after app.synth() returns (yuck!), or maybe implement an ISynthesizer from scratch?

https://github.com/aws/aws-cdk/blob/9e421e5b25c43cb9f49ebfb29751a42d73b87e6a/packages/%40aws-cdk/core/lib/stack-synthesizers/default-synthesizer.ts#L482

**Comment by rix0rrr** [comment]
If you want to make a change to CDK to make this easier to configure/override, I'd be open to that.

**Comment by rabbittsoup** [comment]
PR #14626

**Comment by rabbittsoup** [comment]
Resolved by PR #14626
