### ISSUE TITLE
(eks): awsAuth methods should account for role path

### ISSUE THREAD

**Issue by rafaelpereyra** [aws/aws-cdk#14311]
As described [here](https://github.com/aws/containers-roadmap/issues/573) and IAM role containing a Path won't work on the aws-auth configmap and the path must be removed.

Currently passing a role that includes a path to any of the awsAuth methods of the cluster object (i.e `awsAuth.addMastersRole`) will produce a config map that will not allow the role to authenticate.

For example, creating a [no-ingress Cloud9](https://docs.aws.amazon.com/cloud9/latest/user-guide/ec2-ssm.html) environment and mapping the instance role, fails to authenticate with the default Instance role as it includes a Path by default (`/service-role/`)

### Reproduction Steps

1. Create a CDK Stack with C9 environment with CONNECT_SSM connection type and an EKS cluster.
2. Add the Cloud9 role to the awsAuth as master to the EKS cluster.
3. Log into the Cloud9 instance.
4. Update kubeconfig using the instance role.
5. List nodes will fail with authentication error.

### What did you expect to happen?

awsAuth interface should strip the path from the role arn when updating the aws-auth configmap, otherwise allow for a method to pass the arn as String. A method with a signature like:

`public addMastersRole(role: string, username?: string): void`

### What actually happened?
Configmap entry created includes the role path (`service-role`) and there is not way to exclude it:

{\"rolearn\":\"arn:aws:iam::123456789012:role/service-role/AWSCloud9SSMAccessRole\",\"username\":\"arn:aws:iam::123456789012:role/service-role/AWSCloud9SSMAccessRole\",\"groups\":[\"system:masters\"]}

### Environment

  - **CDK CLI Version  : 1.97.0**
  - **Framework Version:**
  - **Node.js Version:** v14.16.1
  - **OS               : Any**
  - **Language (Version):** TypeScript-->

### Other

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment]
We are unassigning and marking this issue as `p2`, which means that we are unable to work on this immediately.  
We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://join.slack.com/t/cdk-dev/shared_invite/zt-mso6p56d-qJp7SOTBvMaQuDrx7R2wHg) to solicit support for reprioritization.

@rafaelpereyra In the meantime, How are you extracting the Cloud9 role from the environment? Can you please share the code you use? specifically how you invoke `addMastersRole`. 

If you are statically passing the `arn:aws:iam::123456789012:role/service-role/AWSCloud9SSMAccessRole` - can't you just remove the `/service-role/` path? 

If its a dynamic role, you can use:

```ts
const c9RoleParts = cdk.Fn.split('/service-role/', c9Role.roleArn);
const replaced = cdk.Fn.join('/', [cdk.Fn.select(0, c9RoleParts), cdk.Fn.select(1, c9RoleParts)])
```

**Comment by rafaelpereyra** [comment]
Thanks for the response. In order to use connectionType `CONNECT_SSM` in Cloud9, I'm creating the role based on the instructions provided in the Cloud9 [documentation](https://docs.aws.amazon.com/cloud9/latest/user-guide/ec2-ssm.html#service-role-ssm). The path is required unfortunately :

```
            const c9SSMRole = new iam.Role(this,'AWSCloud9SSMAccessRole', {
                path: '/service-role/',
                roleName: 'AWSCloud9SSMAccessRole',
                assumedBy: new iam.CompositePrincipal(new iam.ServicePrincipal("ec2.amazonaws.com"), new iam.ServicePrincipal("cloud9.amazonaws.com")),
                managedPolicies: [iam.ManagedPolicy.fromAwsManagedPolicyName("AWSCloud9SSMInstanceProfile"),iam.ManagedPolicy.fromAwsManagedPolicyName("AdministratorAccess")]
            });

            new iam.CfnInstanceProfile(this, 'AWSCloud9SSMInstanceProfile', {
                path: '/cloud9/',
                roles: [c9SSMRole.roleName],
                instanceProfileName: 'AWSCloud9SSMInstanceProfile'
            });
            
            cluster.awsAuth.addMastersRole(c9SSMRole);
```

The problem with the suggested workaround is that the awsAuth [method](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-eks.AwsAuth.html#addwbrmasterswbrrolerole-username) requires an `IRole` and not a string. My suggestion is creating a second method that can accept a string so removing the path outside the method is possible (or even passing a cross account role / role that will be created at later time, etc).

As a security best practice I'll like to create the Cloud9 instance in my private VPC and allow access using SSM.

```
public addMastersRole(role: IRole, username?: string): void
```

**Comment by iliapolo** [comment]
@rafaelpereyra

> The problem with the suggested workaround is that the awsAuth method requires an IRole and not a string

You can always create an `IRole` from a string by doing `iam.Role.fromRoleArn(this, 'Role', <the-arn-string-or-token>)`

**Comment by rafaelpereyra** [comment]
Nice, I'll try that. I thought the ARN had to be valid for that method to work (it won't be due to the missing path).
Thanks!

**Comment by Richardmbs12** [comment]
Thanks for providing the workaround, this gave me issues. A proper fix for this will be good however, as I can see many many people will fall in this trap, that the aws-auth configmap does not support role paths, and that its not as straight forward to fix from CDK

**Comment by jsimpson1** [comment]
any updates on a more official fix for this issue? i have encountered this same issue.
