### ISSUE TITLE
(@aws-cdk/aws-codepipeline): CodePipeline notifications

### ISSUE THREAD

**Issue by jakubgruber** [aws/aws-cdk#14327]
### The Question
Hello, could you please provide an example, if CDK supports that, how to send notification in case CodePipeline succeeds/fails?

I was trying to come up with a solution via `@aws-cdk/aws-codepipeline-actions`, but only usage of email was in `ManualApprovalAction`.

I believe it could be solved by creating Lambda function + SNS topic, but it seems unnecessarily complicated and hopefully could come out-of-the-box in the CDK.

**Comment by skinny85** [comment]
Hey @jakubgruber ,

are you looking for an example that sends email specifically, or just any example of notifications?

Thanks,
Adam

**Comment by jakubgruber** [comment]
Hello @skinny85, I would be mostly interested in email notification. 

**Example:** If codepipeline finished succefully, send email to specified recipients (or commit author etc.).

**Comment by skinny85** [comment]
Sure. Here's a simple example.

```ts
import { App, Stack } from '@aws-cdk/core';
import codepipeline = require('@aws-cdk/aws-codepipeline');
import event_targets = require('@aws-cdk/aws-events-targets');
import sns = require('@aws-cdk/aws-sns');
import sns_sub = require('@aws-cdk/aws-sns-subscriptions');

// lots of code here...
       const pipeline: codepipeline.IPipeline = ...

        const topic = new sns.Topic(this, 'Topic', {
           topicName: 'codebuild-events-consuming-topic',
        });
        topic.addSubscription(new sns_sub.EmailSubscription('your-email@example.com'));

        pipeline.onStateChange('BuildStarted', {
            target: new event_targets.SnsTopic(topic),
        });
    }
}
```

Hope this helps!

Thanks,
Adam

**Comment by jakubgruber** [comment]
Thank you for help, have a nice day!
