### ISSUE TITLE
(core): BootstraplessSynthesizer Deploy Role Default Behavior

### ISSUE THREAD

**Issue by rabbittsoup** [aws/aws-cdk#14331]
## :question: General Issue

The BootstraplessSynthesizer refers to the deploy role arn default as using the CLI credentials.  When no deploy role arn is provided on construction it does eventually fall to the CLI credentials.  However, this is only falling back to the CLI credentials after attempting and failing to assume role with the default DefaultSynthesizer deploy role arn.  Although the end result is correct, the failure to assume role and resulting user warning message can be avoided since the lack of providing a deploy role arn to BootstraplessSynthesizer should instead result in bypassing the assume role attempt altogether.

https://github.com/aws/aws-cdk/blob/2d01c0748426887dc876f9fa59cc3fa2ce0db56b/packages/%40aws-cdk/core/lib/stack-synthesizers/bootstrapless-synthesizer.ts#L13

I believe this is somewhat attributable to the below undefined comparison, combined with the cloud assembly values and BootstraplessSynthesizer constructor, where I don't believe assumeRoleArn will ever be undefined.  Some other mechanism may be needed to pass along the intent of a missing deploy role arn when constructing BootstraplessSynthesizer.

https://github.com/aws/aws-cdk/blob/75c96d7a8f67a5ebee008cf78d4dbb1907bf2be6/packages/aws-cdk/lib/api/aws-auth/sdk-provider.ts#L153

### Environment

  - **CDK CLI Version: 1.100.0** 
  - **Module Version: 1.100.0** 
  - **Node.js Version: 14.16.0** 
  - **OS: Amazon Linux 2** 
  - **Language (Version): Python 3.8**

**Comment by rix0rrr** [comment]
What I'm taking away from this is that apparently when using a `BootstraplessSynthesizer`, the CLI tries to go into assuming a role even though that could never work.

Haven't completely understood why that is happening, but that is left for investigation.

**Comment by rix0rrr** [comment]
`BootstraplessSynthesizer` is misnomed. I've recently cleared up the docs for the synthesizers a bit more.
