### ISSUE TITLE
CDK v2 - Go: Cannot use Fn If in allowed by Cloudformation way

### ISSUE THREAD

**Issue by xrn** [aws/aws-cdk#14342]
I have code like

```
	lambdaFn := awslambda.NewFunction(stack, jsii.String("Singleton"), &awslambda.FunctionProps{
		Code:    awslambda.NewAssetCode(jsii.String("lambda"), nil),
		Handler: jsii.String("handler.main"),
		Timeout: awscdk.Duration_Seconds(jsii.Number(300)),
		Runtime: awslambda.Runtime_PYTHON_3_6(),
	})

	awscognito.NewUserPool(stack, aws.String("UserPoll"), &awscognito.UserPoolProps{
		UserPoolName: awscdk.Fn_Sub(aws.String("${Environment}-SC-Pool"), nil),
		LambdaTriggers: awscdk.Fn_ConditionIf("Condition",
			&awscognito.UserPoolTriggers{
				PostAuthentication: lambdaFn,
			},
			&awscognito.UserPoolTriggers{},
		),
	})
```

Which from perspective Cloudfroamtion should work - I can create if statement for the whole object. But Fn_ConditionIf returns type ICfnConditionExpression and I am expecting &awscognito.UserPoolTriggers

### Reproduction Steps
Code attached

### What did you expect to happen?
If statement should be allowed

### What actually happened?
If statement could not be used here because of type

### Environment
  - **aws-cdk@2.0.0-alpha.12
  - **OS: MP Debian 5.10.28-1 (2021-04-09) x86_64 GNU/Linux
  - **Language (Version):**  Go 1.16.3

**Comment by nija-at** [comment]
Hi @xrn -

You will need to convert `ICfnConditionExpression` into an any token. Something like this -

```go
LambdaTriggers: awscdk.Token_asAny(awscdk.Fn_ConditionIf("Condition",
  &awscognito.UserPoolTriggers{
    PostAuthentication: lambdaFn,
  },
  &awscognito.UserPoolTriggers{},
)),
```

Can you check if that works?

**Comment by xrn** [comment]
Hi @nija-at 

```
LambdaTriggers: awscdk.Token_AsAny(awscdk.Fn_ConditionIf(aws.String("Condition"),
			&awscognito.UserPoolTriggers{
				PostAuthentication: lambdaFn,
			},
			&awscognito.UserPoolTriggers{},
		)),
```

Still do not work because Token_AsAny returns `IResolvable` and `LambdaTriggers` is expecting `awscognito.UserPoolTriggers` type

**Comment by nija-at** [comment]
This is a Go question targeted to the jsii repo. I believe you already have an issue open there - https://github.com/aws/jsii/issues/2798

Closing this as a dupe.
