### ISSUE TITLE
(cdk-pipelines): unable to add assets stage to existing pipeline within a vpc

### ISSUE THREAD

**Issue by ekbarber** [aws/aws-cdk#14343]
When you have an existing cdk pipeline, attached to a vpc, that does not have assets (either File or Docker), and you make a change to the stack that requires adding the assets stage (i.e. adding a lambda), the cloudformation may fail when attempting to create the CodeBuild project(s) responsible for managing the assets with the error `Not authorized to perform DescribeSecurityGroups (Service: AWSCodeBuild; Status Code: 400; Error Code: InvalidInputException;`

This is related to https://github.com/aws/aws-cdk/issues/11815

### Reproduction Steps

1. create a simple CDK pipeline with an application stage that does not have any lambdas. 
2. deploy the pipeline
3. it should deploy the pipeline and associated stack just fine
4. change the application stage to include a lambda
5. attempt to deploy
6. You should encounter an error: `Error: The stack named [STACK_NAME] failed to deploy: UPDATE_ROLLBACK_COMPLETE`

### What did you expect to happen?

The pipeline to be successfully updated with the new Assets stage

### What actually happened?

Received error when CloudFormation attempts to create the Assets CodeBuild project: `Not authorized to perform DescribeSecurityGroups (Service: AWSCodeBuild; Status Code: 400; Error Code: InvalidInputException;`

### Environment

  - **CDK CLI Version  :1.91.0**
  - **Framework Version:1.91.0**
  - **Node.js Version:12.17.0** 
  - **OS               :MacOS**
  - **Language (Version):Javascript** 

### Other

It appears this is due to Cloudformation attempting to create the FileAssets Codebuild project before the IAM Policy which CodeBuild requires when it is part of a vpc is finished being created. That policy adds the following permissions to the role used by CodeBuild.
```            
'ec2:CreateNetworkInterface',
'ec2:DescribeNetworkInterfaces',
'ec2:DeleteNetworkInterface',
'ec2:DescribeSubnets',
'ec2:DescribeSecurityGroups',
'ec2:DescribeDhcpOptions',
'ec2:DescribeVpcs',
```

When CodeBuild is responsible for creating this role and the policy, it adds a dependency between the project and the Policy (See https://github.com/aws/aws-cdk/blob/a16f09c9ea675caf5b1e50a4e1cc288e5afd1237/packages/%40aws-cdk/aws-codebuild/lib/project.ts#L1211)

However, CDKPipelines appears to create a single role that is shared amongst all the FileAssets Codebuild Projects, so this dependency isn't set. 

The image below shows the Role being created, and then immediately following both the `fileassetsBugAssetsFileRoleVpcPolicy24F81276` and the `fileassetsBugAssetsFileAsset1F9C19E21` begin creation at the same time.
![image](https://user-images.githubusercontent.com/4382558/115883306-a688fd80-a41b-11eb-98ab-f641c7a08650.png)

--- 

This is :bug: Bug Report

**Comment by erikatgreenbyte** [comment]
Running into the exact same problem with v1.101.0 and it is currently blocking CI/CD pipeline rollout for me.
Are there any known mitigations/workarounds?
Let me know if I can help out with testing or providing debug info.

**Comment by rix0rrr** [comment]
You are right that the problem is probably solved by adding a dependency between the policy and the CodeBuild project

**Comment by erikatgreenbyte** [comment]
@rix0rrr Do you have any updates to this? I am stuck due to this VPC issue.
Can I work around it somehow?

**Comment by erikatgreenbyte** [comment]
@ericzbeard Any news to share regarding ETA for a fix?

**Comment by ericzbeard** [comment]
This issue is included in the GA milestone, which we are actively working towards. Can't promise a date, but hopefully within a month.

**Comment by erikatgreenbyte** [comment]
> This issue is included in the GA milestone, which we are actively working towards. Can't promise a date, but hopefully within a month.

Thanks! Appreciate the answer nonetheless! 🙏
