### ISSUE TITLE
cli: ChangeSetNotFound error should be translated into informative message about parallel deployments

### ISSUE THREAD

**Issue by shellscape** [aws/aws-cdk#14350]
Using `--change-set-name` with multiple, parallel deployments results in context-bleed of the various changeset names being provided to each independent run of `cdk deploy`. I originally raised this issue on https://github.com/aws/aws-cdk/issues/14316, but it was closed by @rix0rrr with instructions to use `---change-set-name`. Unfortunately, the fix suggested reveals that there's more wrong in CDK.

Either there's a pretty big bug with concurrent/parallel deployments, or CDK doesn't support concurrent deployments and there should be a critical documentation update.

### Reproduction Steps

While I can't grant access to the repo, I can shared the redacted build output showing concurrent deploys and information that verifies there's an internal CDK issue:

<details>
services/service2 predeploy$ pnpm build && make-dedicated-lockfile && pnpm deploy:copy
services/service3 predeploy$ pnpm build && make-dedicated-lockfile && pnpm deploy:copy
services/service1 predeploy$ pnpm build && make-dedicated-lockfile && pnpm deploy:copy
services/service1 predeploy: > @redacted/service1@0.1.1 build /home/runner/work/harbor/harbor/services/service1
services/service1 predeploy: > tsc --project ./tsconfig.build.json
services/service2 predeploy: > @redacted/service2@0.1.1 build /home/runner/work/harbor/harbor/services/service2
services/service2 predeploy: > tsc --project ./tsconfig.build.json
services/service3 predeploy: > @redacted/service3@0.1.2 build /home/runner/work/harbor/harbor/services/service3
services/service3 predeploy: > tsc --project ./tsconfig.build.json
services/service2 predeploy: .                                        | Progress: resolved 1, reused 0, downloaded 0, added 0
services/service3 predeploy: .                                        | Progress: resolved 1, reused 0, downloaded 0, added 0
services/service1 predeploy: .                                        | Progress: resolved 1, reused 0, downloaded 0, added 0
services/service2 predeploy: .                                        | Progress: resolved 95, reused 95, downloaded 0, added 0
services/service2 predeploy: .                                        | Progress: resolved 96, reused 95, downloaded 0, added 0
services/service3 predeploy: .                                        | Progress: resolved 64, reused 64, downloaded 0, added 0
services/service3 predeploy: .                                        | Progress: resolved 65, reused 64, downloaded 0, added 0
services/service1 predeploy: .                                        | Progress: resolved 78, reused 78, downloaded 0, added 0
services/service1 predeploy: .                                        | Progress: resolved 79, reused 78, downloaded 0, added 0
services/service2 predeploy: .                                        | Progress: resolved 300, reused 298, downloaded 1, added 0
services/service3 predeploy: .                                        | Progress: resolved 299, reused 298, downloaded 0, added 0
services/service2 predeploy: .                                        | Progress: resolved 301, reused 298, downloaded 1, added 0
services/service1 predeploy: .                                        | Progress: resolved 271, reused 269, downloaded 1, added 0
services/service1 predeploy: .                                        | Progress: resolved 272, reused 269, downloaded 1, added 0
services/service3 predeploy: .                                        | Progress: resolved 300, reused 298, downloaded 0, added 0
services/service2 predeploy: .                                        | Progress: resolved 612, reused 611, downloaded 1, added 0
services/service2 predeploy: .                                        | Progress: resolved 613, reused 611, downloaded 1, added 0
services/service1 predeploy: .                                        | Progress: resolved 465, reused 462, downloaded 1, added 0
services/service1 predeploy: .                                        | Progress: resolved 466, reused 462, downloaded 1, added 0
services/service3 predeploy: .                                        | Progress: resolved 655, reused 655, downloaded 0, added 0
services/service3 predeploy: .                                        | Progress: resolved 656, reused 655, downloaded 0, added 0
services/service2 predeploy: .                                        | Progress: resolved 786, reused 785, downloaded 1, added 0
services/service2 predeploy: .                                        | Progress: resolved 787, reused 785, downloaded 1, added 0
services/service1 predeploy: .                                        | Progress: resolved 721, reused 720, downloaded 1, added 0
services/service1 predeploy: .                                        | Progress: resolved 722, reused 720, downloaded 1, added 0
services/service3 predeploy: .                                        | Progress: resolved 904, reused 904, downloaded 0, added 0
services/service3 predeploy: .                                        | Progress: resolved 905, reused 904, downloaded 0, added 0
services/service3 predeploy: .                                        | Progress: resolved 920, reused 920, downloaded 0, added 0, done
services/service2 predeploy: .                                        | Progress: resolved 920, reused 919, downloaded 1, added 0, done
services/service1 predeploy: .                                        | Progress: resolved 920, reused 919, downloaded 1, added 0
services/service1 predeploy: .                                        | Progress: resolved 920, reused 919, downloaded 1, added 0, done
services/service3 deploy: Attempting to create ChangeSet with name cdk-deploy-b2679811af to update stack service3-stack
services/service3 deploy: service3-stack: creating CloudFormation changeset...
services/service2 deploy: [100%] success: Published 69507b97cb1bb6f50c4bb613c93f65755b190df4591429a74a45568d2d52bc82:current
services/service2 deploy: Removing existing change set with name cdk-deploy-4043dca991 if it exists
services/service2 deploy: Attempting to create ChangeSet with name cdk-deploy-4043dca991 to update stack service2-stack
services/service2 deploy: service2-stack: creating CloudFormation changeset...
services/service3 deploy: Initiated creation of changeset: arn:aws:cloudformation:us-east-1:***:changeSet/cdk-deploy-b2679811af/2994ef3c-1caa-4692-a1d7-cf058135e698; waiting for it to finish creating...
services/service3 deploy: Waiting for changeset cdk-deploy-b2679811af on stack service3-stack to finish creating...
services/service1 deploy: Initiated creation of changeset: arn:aws:cloudformation:us-east-1:***:changeSet/cdk-deploy-7cd4e66f54/a7edcedb-94c3-406a-8d0e-302e49f142ca; waiting for it to finish creating...
services/service1 deploy: Waiting for changeset cdk-deploy-7cd4e66f54 on stack service2-stack to finish creating...
services/service3 deploy: Changeset cdk-deploy-b2679811af on stack service3-stack is still creating
services/service2 deploy: Initiated creation of changeset: arn:aws:cloudformation:us-east-1:***:changeSet/cdk-deploy-4043dca991/c2e4e8f2-5715-4f5f-a209-f624276b9c07; waiting for it to finish creating...
services/service2 deploy: Waiting for changeset cdk-deploy-4043dca991 on stack service2-stack to finish creating...
services/service1 deploy: Changeset cdk-deploy-7cd4e66f54 on stack service2-stack is still creating
services/service2 deploy: Changeset cdk-deploy-4043dca991 on stack service2-stack is still creating
services/service3 deploy: Changeset cdk-deploy-b2679811af on stack service3-stack is still creating
services/service1 deploy: Changeset cdk-deploy-7cd4e66f54 on stack service2-stack is still creating
services/service2 deploy: Changeset cdk-deploy-4043dca991 on stack service2-stack is still creating
services/service3 deploy: Changeset cdk-deploy-b2679811af on stack service3-stack is still creating
services/service1 deploy: Changeset cdk-deploy-7cd4e66f54 on stack service2-stack is still creating
services/service2 deploy: Changeset cdk-deploy-4043dca991 on stack service2-stack is still creating
services/service3 deploy: Initiating execution of changeset arn:aws:cloudformation:us-east-1:***:changeSet/cdk-deploy-b2679811af/2994ef3c-1caa-4692-a1d7-cf058135e698 on stack service3-stack
services/service1 deploy: Initiating execution of changeset arn:aws:cloudformation:us-east-1:***:changeSet/cdk-deploy-7cd4e66f54/a7edcedb-94c3-406a-8d0e-302e49f142ca on stack service2-stack
services/service2 deploy: Initiating execution of changeset arn:aws:cloudformation:us-east-1:***:changeSet/cdk-deploy-4043dca991/c2e4e8f2-5715-4f5f-a209-f624276b9c07 on stack service2-stack
services/service3 deploy: Execution of changeset arn:aws:cloudformation:us-east-1:***:changeSet/cdk-deploy-b2679811af/2994ef3c-1caa-4692-a1d7-cf058135e698 on stack service3-stack has started; waiting for the update to complete...
services/service3 deploy: Waiting for stack service3-stack to finish creating or updating...
services/service3 deploy: Stack service3-stack has an ongoing operation in progress and is not stable (UPDATE_IN_PROGRESS (User Initiated))
services/service1 deploy: Execution of changeset arn:aws:cloudformation:us-east-1:***:changeSet/cdk-deploy-7cd4e66f54/a7edcedb-94c3-406a-8d0e-302e49f142ca on stack service2-stack has started; waiting for the update to complete...
services/service1 deploy: Waiting for stack service2-stack to finish creating or updating...
services/service1 deploy: Stack service2-stack has an ongoing operation in progress and is not stable (UPDATE_IN_PROGRESS (User Initiated))
services/service2 deploy: Call failed: executeChangeSet({"StackName":"service2-stack","ChangeSetName":"cdk-deploy-4043dca991"}) => ChangeSet [cdk-deploy-4043dca991] does not exist (code=ChangeSetNotFound)
services/service2 deploy:  ❌  service2-stack failed: ChangeSetNotFound: ChangeSet [cdk-deploy-4043dca991] does not exist
services/service2 deploy:     at Request.extractError (/opt/hostedtoolcache/node/14.16.1/x64/pnpm-global/4/node_modules/.pnpm/aws-sdk@2.891.0/node_modules/aws-sdk/lib/protocol/query.js:50:29)
services/service2 deploy:     at Request.callListeners (/opt/hostedtoolcache/node/14.16.1/x64/pnpm-global/4/node_modules/.pnpm/aws-sdk@2.891.0/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
services/service2 deploy:     at Request.emit (/opt/hostedtoolcache/node/14.16.1/x64/pnpm-global/4/node_modules/.pnpm/aws-sdk@2.891.0/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
services/service2 deploy:     at Request.emit (/opt/hostedtoolcache/node/14.16.1/x64/pnpm-global/4/node_modules/.pnpm/aws-sdk@2.891.0/node_modules/aws-sdk/lib/request.js:688:14)
services/service2 deploy:     at Request.transition (/opt/hostedtoolcache/node/14.16.1/x64/pnpm-global/4/node_modules/.pnpm/aws-sdk@2.891.0/node_modules/aws-sdk/lib/request.js:22:10)
services/service2 deploy:     at AcceptorStateMachine.runTo (/opt/hostedtoolcache/node/14.16.1/x64/pnpm-global/4/node_modules/.pnpm/aws-sdk@2.891.0/node_modules/aws-sdk/lib/state_machine.js:14:12)
services/service2 deploy:     at /opt/hostedtoolcache/node/14.16.1/x64/pnpm-global/4/node_modules/.pnpm/aws-sdk@2.891.0/node_modules/aws-sdk/lib/state_machine.js:26:10
services/service2 deploy:     at Request.<anonymous> (/opt/hostedtoolcache/node/14.16.1/x64/pnpm-global/4/node_modules/.pnpm/aws-sdk@2.891.0/node_modules/aws-sdk/lib/request.js:38:9)
services/service2 deploy:     at Request.<anonymous> (/opt/hostedtoolcache/node/14.16.1/x64/pnpm-global/4/node_modules/.pnpm/aws-sdk@2.891.0/node_modules/aws-sdk/lib/request.js:690:12)
services/service2 deploy:     at Request.callListeners (/opt/hostedtoolcache/node/14.16.1/x64/pnpm-global/4/node_modules/.pnpm/aws-sdk@2.891.0/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
services/service2 deploy:   code: 'ChangeSetNotFound',
services/service2 deploy:   time: 2021-04-23T18:14:14.964Z,
services/service2 deploy:   requestId: '8caba8c9-21d4-4bb2-8a50-71dfd019474e',
services/service2 deploy:   statusCode: 404,
services/service2 deploy:   retryable: false,
services/service2 deploy:   retryDelay: 377.11254367312665
services/service2 deploy: }
services/service2 deploy: ChangeSet [cdk-deploy-4043dca991] does not exist
services/service2 deploy: ChangeSetNotFound: ChangeSet [cdk-deploy-4043dca991] does not exist
services/service2 deploy:     at Request.extractError (/opt/hostedtoolcache/node/14.16.1/x64/pnpm-global/4/node_modules/.pnpm/aws-sdk@2.891.0/node_modules/aws-sdk/lib/protocol/query.js:50:29)
services/service2 deploy:     at Request.callListeners (/opt/hostedtoolcache/node/14.16.1/x64/pnpm-global/4/node_modules/.pnpm/aws-sdk@2.891.0/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
services/service2 deploy:     at Request.emit (/opt/hostedtoolcache/node/14.16.1/x64/pnpm-global/4/node_modules/.pnpm/aws-sdk@2.891.0/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
services/service2 deploy:     at Request.emit (/opt/hostedtoolcache/node/14.16.1/x64/pnpm-global/4/node_modules/.pnpm/aws-sdk@2.891.0/node_modules/aws-sdk/lib/request.js:688:14)
services/service2 deploy:     at Request.transition (/opt/hostedtoolcache/node/14.16.1/x64/pnpm-global/4/node_modules/.pnpm/aws-sdk@2.891.0/node_modules/aws-sdk/lib/request.js:22:10)
services/service2 deploy:     at AcceptorStateMachine.runTo (/opt/hostedtoolcache/node/14.16.1/x64/pnpm-global/4/node_modules/.pnpm/aws-sdk@2.891.0/node_modules/aws-sdk/lib/state_machine.js:14:12)
services/service2 deploy:     at /opt/hostedtoolcache/node/14.16.1/x64/pnpm-global/4/node_modules/.pnpm/aws-sdk@2.891.0/node_modules/aws-sdk/lib/state_machine.js:26:10
services/service2 deploy:     at Request.<anonymous> (/opt/hostedtoolcache/node/14.16.1/x64/pnpm-global/4/node_modules/.pnpm/aws-sdk@2.891.0/node_modules/aws-sdk/lib/request.js:38:9)
services/service2 deploy:     at Request.<anonymous> (/opt/hostedtoolcache/node/14.16.1/x64/pnpm-global/4/node_modules/.pnpm/aws-sdk@2.891.0/node_modules/aws-sdk/lib/request.js:690:12)
services/service2 deploy:     at Request.callListeners (/opt/hostedtoolcache/node/14.16.1/x64/pnpm-global/4/node_modules/.pnpm/aws-sdk@2.891.0/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
services/service2 deploy:  ERROR  Command failed with exit code 1.
services/service2 deploy: Failed
undefined
/home/runner/work/harbor/harbor/services/service2:
 ERROR  @redacted/service2@0.1.1 deploy: `DEPLOY_PACKAGE_NAME=$npm_package_name pnpm service:deploy --workspace-root`
Exit status 1
</details>

### What did you expect to happen?

All three successful deploys.

### What actually happened?

Please see above. Note the `service2-stack failed: ChangeSetNotFound: ChangeSet [cdk-deploy-4043dca991] does not exist` error, even though the log output from the CDK CLI states that the `cdk-deploy-4043dca991` changeset name was provided for that deploy. 

Next, please note this screenshot from the AWS Console, showing `service2` in CloudFormation and the changeset that _was_ executed for that stack:

<img width="900" alt="Screen Shot 2021-04-23 at 2 26 30 PM" src="https://user-images.githubusercontent.com/76371/115914510-08f3f500-a440-11eb-8fea-33fdedd84b8e.png">

We can see that cdk executed the `cdk-deploy-7cd4e66f54` changeset, which belongs to `service1`, also visible in the logs above.

### Environment

  - **CDK CLI Version  :** 1.98.0
  - **Framework Version:** 1.98.0
  - **Node.js Version:** 14.15.3
  - **OS               :** MacOS
  - **Language (Version):** TS 4.1.3

### Other

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
Parallel deployments are not possible. CloudFormation doesn't support it: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-changesets.html

I will take this ticket as a feature request to detect that error and provide a more descriptive error message for it. 

---------

Here's the change: if `ChangeSetNotFound` is detected during `ExecuteChangeSet`, we should translate that error into something like: `The change set (${changeSetName}) disappeared. This may happen if the stack got updated in the mean time. Be aware that you cannot perform multiple updates to the same stack in parallel.`

**Comment by shellscape** [comment]
That's just the thing - we're not updating the same stack at the same time, and I think my description demonstrated that. We're updating two different stacks at the same time, using the same entry point for `cdk deploy`. CDK CLI has a nasty race condition, and I'm not sure it's correct to consider this a feature request. If you can provide a throw away AWS account, I can provide a reproduction.

**Comment by shellscape** [comment]
@rix0rrr please review my last reply when you have the opportunity.
