### ISSUE TITLE
aws-elasticloadbalancingv2: Unwanted Allow All ingress rule added to security group

### ISSUE THREAD

**Issue by markilott** [aws/aws-cdk#14359]
The ELBv2 ApplicationLoadBalancer construct adds an allow all inbound rule to an existing security group.

This occurs both for SG's created in the stack and imported via Id.

### Reproduction Steps

Create or import a security group, including custom restricted ingress rules.
Create Application Load Balancer that uses the security group.

```javascript
// security group
const securityGroup = new SecurityGroup(this, 'sg', {
    vpc,
    allowAllOutbound: true,
});
securityGroup.addIngressRule(Peer.ipv4(vpc.vpcCidrBlock), Port.tcp(80), 'allow internal ALB access');

// load balancer
const alb = new ApplicationLoadBalancer(this, 'alb', {
    vpc,
    vpcSubnets: SubnetType.PRIVATE,
    internetFacing: false, // the issue also occurs on internet facing load balancers
    securityGroup,
});
// listeners
const http = alb.addListener('http', {
    port: 80,
    protocol: ApplicationProtocol.HTTP,
});

// add default routing actions
http.addAction('default', {
     action: ListenerAction.fixedResponse(404, {
     contentType: 'text/plain',
     messageBody: 'Nothing to see here',
     }),
});
```

### What did you expect to happen?

Security Group would only include the specified or existing rules.

### What actually happened?

Security Group now includes an allow all ingress rule.

```json
{
"SecurityGroupIngress": [
          {
            "CidrIp": "172.31.0.0/16",
            "Description": "allow internal ALB access",
            "FromPort": 80,
            "IpProtocol": "tcp",
            "ToPort": 80
          },
          {
            "CidrIp": "0.0.0.0/0",
            "Description": "Allow from anyone on port 80",
            "FromPort": 80,
            "IpProtocol": "tcp",
            "ToPort": 80
          }
        ]
}
```

### Environment

  - **CDK CLI Version:** 1.100
  - **Module Version:** 1.100
  - **Node.js Version:** 14.x
  - **Language:** Javascript

### Other

I discovered this when importing security groups previously created by Terraform and noticing they had been modified.

Workaround is to import and use the mutable flag:
```javascript
const sg = SecurityGroup.fromSecurityGroupId(this, 'sg', 'sg-123456789', { mutable: false });
```

**Comment by njlynch** [comment]
Hi @markilott ,

When you call [`addListener`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-elasticloadbalancingv2.ApplicationLoadBalancer.html#addwbrlistenerid-props), the second argument is a [`BaseApplicationListenerProps`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-elasticloadbalancingv2.BaseApplicationListenerProps.html). The `open` property of that structure defaults to `true`, and is what adds the ingress rules; it is set to true as the default, as it's by far the more common behavior.

Simply add `open: false` to your `addListener` calls, and the rule will be omitted.

Thanks!
