### ISSUE TITLE
(asset): lambda asset bundle being moved

### ISSUE THREAD

**Issue by strongishllama** [aws/aws-cdk#14369]
Bunding my Go Lambda function with Docker and having the output of the bundle a zip works the first time, but subsequent bundles fail. I've had a dig through the source code and I believe it's because the bundled zip file is being moved after it is created (see [here](https://github.com/aws/aws-cdk/blob/55e737ffb378cc8690b201a6c52424102dee9c3b/packages/%40aws-cdk/core/lib/asset-staging.ts#L338)).

Below is the code being used to bundle and create the Lambda function. One thing to note, the  ```ouputType``` property needs to be set to ```cdk.BundingOutput.ARCHIVED``` because Windows 10 will strip the execute permission off the binary if it isn't zipped (see [here](https://github.com/aws/aws-cdk/issues/10776)).

```ts
new lambda.Function(props.scope, props.id, {
    runtime: lambda.Runtime.GO_1_X,
    code: lambda.Code.fromAsset(path.join(__dirname, "../"), {
      assetHashType: cdk.AssetHashType.OUTPUT,
      bundling: {
        image: lambda.Runtime.GO_1_X.bundlingImage,
        command: [
          "bash", "-c", [
            `cd ${props.sourceDir}`,
            `GOOS=linux go build -o main -ldflags="-s -w"`,
            // Zip file while in Docker container so file permissions
            // aren't lost when deploying with Windows 10.
            "zip /asset-output/main.zip main",
            "rm main"
          ].join(" && ")
        ],
        user: "root",
        outputType: cdk.BundlingOutput.ARCHIVED
      }
    }),
    handler: "main"
  });
```

### Reproduction Steps

I've attached a simple [CDK project](https://github.com/aws/aws-cdk/files/6371868/possible-bug.zip) that demonstrates this issue. Simply unzip the attached project and run either ```cdk synth``` or ```cdk deploy``` twice. The first time should succeed and the second time should fail with the following error message. ```Error: Bundling output directory is expected to include only a single .zip or .jar file when `output` is set to `ARCHIVED` ```

### What did you expect to happen?

The Lambda source code to be successfully bundled both times.

### What actually happened?

The Lambda source code failed to be bundled the second time. Returning the following error message ```Error: Bundling output directory is expected to include only a single .zip or .jar file when `output` is set to `ARCHIVED` ```

### Environment

  - **CDK CLI Version:** 1.100.0 (build d996c6d)
  - **Framework Version:** 1.100.0
  - **Node.js Version:** v14.16.0
  - **OS :** Ubuntu 20.04 LTS
  - **Language (Version):** v4.1.3
--- 

This is :bug: Bug Report

**Comment by jogold** [comment]
Confirmed bug. The second time bundling runs the bundling directory already exists so bundling is correctly skipped but in this case it cannot determine if bundling resulted in a single archive file or not because the bundling directory is empty.

Working on a fix.

**Comment by saga95** [comment]
I was using pnpm and esbuild and got this error. Installing pnpm globally resolved me the issue

**Comment by hoegertn** [comment]
@jogold I hit a new bug very similar to this one. The touching of the file leads to errors of the hashType is OUTPUT.

The second build will skip bundling but create a new hash for the asset because of the now empty file and then the asset will be moved again but empty.

My suggestion is to remove the temporary bundleDir in that case instead of touching the file. Any objections?

I will create a new PR for this just wanted to note it down somewhere.
