### ISSUE TITLE
(aws-s3-deployment): Support include and exclude options for S3 sync

### ISSUE THREAD

**Issue by davidtucker** [aws/aws-cdk#14362]
The `aws-s3-deployment` module currently does not support the `include` and `exclude` options that are available in the S3 sync command. By adding this, additional use cases can be supported. 

### Use Case

In my case, I have a single-page web app that uses a config file that is generated by a CloudFormation custom resource.  I would like to leverage aws-s3-deployment for the deployment of the web application, but I want to ensure that the config file is not deleted when `prune` is set to true (although I do want all of the other files to be deleted). 

### Proposed Solution

By supporting the include and exclude properties for the S3 sync command with the aws-s3-deployment Lambda function, you can support this use case.

* [X] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by iliapolo** [comment]
I'm not sure I follow. Are you looking for the `exclude` flag to only be considered on delete? 

Can you share a code snippet of how your use-case would be supported?

**Comment by davidtucker** [comment]
I'll get a sample up for this early next week.

**Comment by davidtucker** [comment]
In this case, it is common to generate config from the CDK that needs to be read at runtime by a web application (items that aren't yet known at synth time).  With this being the case, I generally (and I have seen others do this as well) generate a file that is read at runtime (for the purposes of this example, I will call this `config.js`). This leads to the situation where you would want to leverage `prune` for the webapp, but yet also not remove the configuration file.

This can be accomplished with the AWS CLI by using either the `exclude` or `include` options for the s3 `sync` command.  Thus, you could accomplish this with the following commands:

```bash
# build webapp
npm run build
# deploy webapp
aws s3 sync . s3://cdk-s3sync-test/
# generate config file (by whatever process)
# upload config file
aws s3 cp config.js s3://cdk-s3sync-test/
# redeploy webapp on change (doesn't delete config.js)
aws s3 sync . s3://cdk-s3sync-test/ --delete --exclude config.js
```

In terms of the CDK, I would like to see this work in the following manner:

```typescript
new s3Deploy.BucketDeployment(this, 'WebAppDeploy', {
	// bundling options....
	prune: true,
	exclude: 'config.js'
});
```

Include could also be used for a similar effect.  Since both options are supported in the AWS CLI, these could be added into the current process with minimal rework.

**Comment by iliapolo** [comment]
@davidtucker Thanks for the explanation, I understand what you mean now.

I am unassigning and marking this issue as `p2`, which means that we are unable to work on this immediately.

We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://join.slack.com/t/cdk-dev/shared_invite/zt-mso6p56d-qJp7SOTBvMaQuDrx7R2wHg) to solicit support for reprioritization.

**Comment by davidtucker** [comment]
@iliapolo I'm working to implement this and get a pull request up for it.  I think the main purpose of this would be to exclude files from the prune process.  With that being the case, there could be an `exclude` property, but I am concerned people would be confused that this was for the `s3 cp` command.  We could do `excludePrune` which would be more clear.  

Any preference on this?
