### ISSUE TITLE
aws-events: Unable to create CfnEventBusPolicy - Invalid Relative ID

### ISSUE THREAD

**Issue by kheriox-technologies** [aws/aws-cdk#14371]
We are trying to create EventBus and corresponding EventBusPolicy using CDK. The CfnEventBus is created successfully. But when we try to create CfnEventBusPolicy, we get below error.

`The relative-id "event-bus/my-custom-eventbus" is invalid for ARN "arn:aws:events:ap-southeast-2:123456789012:event-bus/my-custom-eventbus" (Service: AWSEvents; Status Code: 400; Error Code: ValidationException; Request ID: 0aef0c95-e415-441f-82bb-f3a6fdfc343d; Proxy: null)`

### Environment

  - **CDK CLI Version:** 1.100.0 (build d996c6d)
  - **Module Version:** 1.100.0
  - **Node.js Version:** v15.13.0
  - **OS:** macOS & Amazon Linux
  - **Language (Version):** Typescript 4.2.4

### Other information

Stack

```
// Custom Event Bus
    const bus = new CfnEventBus(this, 'bus', { name: 'my-custom-eventbus });

    // Event Bus policy
    const busPolicy = new CfnEventBusPolicy(this, 'busPolicy', {
      statementId: 'crossAccountAccess',
      statement: {
        Effect: 'Allow',
        Principal: { AWS:["arn:aws:iam::123456789012:root", "arn:aws:iam::123456789013:root"] },
        Action: ['events:PutEvents'],
        Resource: bus.attrArn,
      },
    });
    busPolicy.node.addDependency(bus);
```

**Comment by peterwoodworth** [comment]
I recommend using the other direct `EventBusPolicy` properties rather than the statement property like so:
```ts
const bus = new CfnEventBus(this, 'bus', { name: 'my-custom-eventbus });

const busPolicy = new events.CfnEventBusPolicy(this, 'busPolicy', {
  statementId: 'crossAccountAccess',
  action: 'events:PutEvents',
  principal: '*',
  eventBusName: bus.attrName
});
```

Doing this will result in the created event having the following policy when looking at the console:
```json
{
  "Version": "2012-10-17",
  "Statement": [{
    "Sid": "crossAccountAccess",
    "Effect": "Allow",
    "Principal": "*",
    "Action": "events:PutEvents",
    "Resource": "arn:aws:events:us-west-2:123456789012:event-bus/my-custom-eventbus"
  }]
}
```

Hope this helps @kheriox-technologies

**Comment by kheriox-technologies** [comment]
Thanks for the reply @peterwoodworth . I tried your suggestion using the direct properties.

```
new CfnEventBusPolicy(this, 'busPolicy', {
        statementId: 'crossAccountAccess',
        action: 'events:PutEvents',
        principal: `{ AWS: 123456789012 }`,
        eventBusName: bus.eventBusName,
      });
```

- I want to give access only to specific accounts
- principal is expecting a string, so I had to put the AWS account id as string.
- I get validation error when I add the AWS account ID as principal
- adding principal as '*' works fine, but I want to restrict it to multiple specific AWS accounts

`2 validation errors detected: Value '{ AWS: 123456789012 }' at 'principal' failed to satisfy constraint: Member must satisfy regular expression pattern: (\d{12}|\*); Value '{ AWS: 123456789012 }' at 'principal' failed to satisfy constraint: Member must have length less than or equal to 12 (Service: AWSEvents; Status Code: 400; Error Code: ValidationException; Request ID: a54d1688-cede-4c2e-ba66-f352cfa70dbc; Proxy: null)`

**Comment by peterwoodworth** [comment]
no problem @kheriox-technologies 

It is expecting a string, so you should be inputting `principal: '123456789012'` instead of putting it in JSON format.

However this doesn't solve your problem that you want multiple accounts to have access to this resource. To do this you can create an [AWS Organization](https://docs.aws.amazon.com/organizations/latest/userguide/orgs_introduction.html) with all the accounts you want to manage your event bus. Then if you set principal to `*` and set [`condition`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-events-eventbuspolicy-condition.html) to the organization you create then I think you'll be able to accomplish what you want to. 

I'm not sure why the method you tried at first didn't work, I got the same bug. Seems like it should work to me, but it doesn't so hopefully this works for you.

**Comment by kheriox-technologies** [comment]
Thanks @peterwoodworth 

Yeah OrgID condition works for now. But it still would be better if we have a method to add specific AWS accounts within organization instead of allowing all orgs.

I was expecting the statement property with principal should work with multiple AWS accounts as principals.

Thanks for your help.

**Comment by peterwoodworth** [comment]
After researching this more I'm pretty sure this is a bug with cloudformation. There's no reason this shouldn't work the way you did it. I can't even get this to work with an existing event bus aside from `default`.

I'll close this because you have a workaround now, and there's no telling when the way you want to do it might get fixed. Ping me if you have any further questions or concerns!

**Comment by peterwoodworth** [comment]
Hey @kheriox-technologies I actually found the issue here.

Cloudformation requires that the `EventBusName` property on `CfnEventBusPolicy` be defined when using the `Statement` property, as the default value for this is `default`. 

Here's my stack which successfully deploys:

```ts
    const bus = new events.CfnEventBus(this, 'bus', { name: 'my-custom-eventbus' });

    const busPolicy = new events.CfnEventBusPolicy(this, 'busPolicy', {
      statementId: 'crossAccountAccess',
      eventBusName: 'my-custom-eventbus',
      statement: {
        Effect: 'Allow',
        Principal: { AWS:["arn:aws:iam::123456789012:root", "arn:aws:iam::123456789013:root"]},
        Action: 'events:PutEvents',
        Resource: bus.attrArn,
      },
    });
```

**Comment by kheriox-technologies** [comment]
That worked @peterwoodworth. Thanks for your help.

**Comment by trademark18** [comment]
> Cloudformation requires that the `EventBusName` property on `CfnEventBusPolicy` be defined when using the `Statement` property, as the default value for this is `default`.

@peterwoodworth Thank you!  This solution also is required for CloudFormation, in case anyone is wondering.  

In short, if you're using `Statement` you also need to specify `EventBusName` which is NOT documented by AWS.  Here's an example of a valid CloudFormation implementation:

```yaml
MyCustomEventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: "MyCustomEventBus"
  
MyCustomEventBusPolicy:
  Type: AWS::Events::EventBusPolicy
  Properties:
    StatementId: ExternalAccountPutEventsPolicy
    EventBusName: !GetAtt MyCustomEventBus.Name # You need this...
    Statement: 
      Effect: Allow
      Principal:
        AWS: !Split [ ',', !Ref CommaDelimitedAccountList ]
      Action:
        - events:PutEvents
      Resource: !GetAtt MyCustomEventBus.Arn # if you have this.
```
