### ISSUE TITLE
cdk.SecretValue.secretsmanager: cdk synth generates an IAM Policy with wrong ARN

### ISSUE THREAD

**Issue by iuuso** [aws/aws-cdk#14378]
We're trying to reference an Arn for a secret in Secrets Manager. The secret in question is deployed into an another account. When referencing said secret in CodeBuild as env-variable, it tries to create a role which references the secret in the current account, rather than the account which is specified in the Arn.

### Reproduction Steps

```typescript
const SecretsArn = 'arn:aws:secretsmanager:<region>:<account-number-1>:secret:<secretId>';

[..SNIP..]
const project = new codebuild.PipelineProject(scope, 'ImageScan-${targetAccount}', {
   projectName: 'ImageScan-${targetAccount}',
   environment: {
      environmentVariables: {
         SECRET_KEY_ID: {
            value: cdk.SecretValue.secretsManager(SecretsArn, { 
               jsonField: 'key_id'
            }),
            type: codebuild.BuildEnvironmentVariableType.SECRETS_MANAGER,
        },
  },
} 
```

### What did you expect to happen?

Synthesis should result in an IAM policy, where the policy dictates a permission to GetSecretValue from the whole ARN, which was provided as a parameter.

```json
"ImageScan<account-number-2>RoleDefaultPolicy0B9D888": {
    "Type": "AWS::IAM::Policy",
    "Properties": {
        "PolicyDocument": {
             "Statement": [
             {
                "Action": "secretsmanager:GetSecretValue",
                "Effect": "Allow",
                "Resource": {
                    'arn:aws:secretsmanager:<region>:<account-number-1>:secret:<secretId>,
                },
[..SNIP..]
```

### What actually happened?

During the synthesis of the stage, the update fails on message that resource reference is not a valid Arn:

```sh
2/11 | 8:57:16 AM | UPDATE_FAILED | AWS::IAM::Policy | ImageScan-<account-number-2>/Role/DefaultPolicy(ImageScan<account-number-2>RoleDefaultPolicy0B9D888) Resource <value-of-key_id> must be in ARN format or "*" . (Service: AmazonIdentityManagement; Status Code: 400, Error Code: MalformedPolicyDocument; Request ID: <request-id>, Proxy: null)
```
The generated template shows a following segment:
```json
[..SNIP..]
"ImageScan<account-number-2>RoleDefaultPolicy0B9D888": {
   "Type": "AWS::IAM::Policy",
   "Properties": {
      "PolicyDocument": {
         "Statement": [
         {
             "Action": "secretsmanager:GetSecretValue",
             "Effect": "Allow",
             "Resource": {
                 "Fn::Join": [
                     "",
                     [
                         "arn:",
                        {
                            "Ref": "AWS::Partition",
                        },
                        ":secretsmanager:<region>:<current-account>:secret:<CDK App Name>/Secret-??????"  
   [..SNIP..]
```

### Environment

  - **CDK CLI Version  : 1.99.0 (build 2691986)**
  - **Framework Version: **
  - **Node.js Version: v14.16.0** 
  - **OS               :**
  - **Language (Version):** 

### Other

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hey @iuuso,

thanks for opening the issue. Like the [documentation of the `value` property states](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-codebuild.BuildEnvironmentVariable.html):

> For SecretsManager variables secrets, pass either the secret name (secretName property of ISecret) or the secret ARN (secretArn property of ISecret) here, along with optional SecretsManager qualifiers separated by ':', like the JSON key, or the version or stage

So, what you need to pass there is:

```ts
const project = new codebuild.PipelineProject(scope, 'ImageScan-${targetAccount}', {
  // ...
  environment: {
    environmentVariables: {
      SECRET_KEY_ID: {
        value:  'arn:aws:secretsmanager:<region>:<account-number-1>:secret:<secretId>:key_id',
        type: codebuild.BuildEnvironmentVariableType.SECRETS_MANAGER,
      },
    },
  },
});
```

Thanks,
Adam

**Comment by iuuso** [comment]
Thank you @skinny85,

This solved the issue. Sorry about the delayed response.
