### ISSUE TITLE
aws-rds: instance identifiers and endpoints not available on DatabaseCluster

### ISSUE THREAD

**Issue by vilikin** [aws/aws-cdk#14377]
DatabaseCluster should have instanceIdentifiers and instanceEndpoints props available. However, it looks like these are always empty.

From the code we can see that those are not actually set to the right values returned by the `createInstances` method:
https://github.com/aws/aws-cdk/blob/55e737ffb378cc8690b201a6c52424102dee9c3b/packages/%40aws-cdk/aws-rds/lib/cluster.ts#L527

### Reproduction Steps

Create a DatabaseCluster with at least 1 instance and try to access instanceIdentifiers or instanceEndpoints prop. Those are always empty arrays.

This is :bug: Bug Report

**Comment by skinny85** [comment]
Thanks for opening the issue @vilikin. You are correct, I was able to reproduce the problem.

Any chance of submitting us a PR fixing this? It should be a fairly easy change. Here's our "Contributing" guide: https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md.

Thanks,
Adam
