### ISSUE TITLE
RDS Proxy uses `id` instead of `uniqueId` for the Proxy name

### ISSUE THREAD

**Issue by dave-graham** [aws/aws-cdk#14374]
When a DatabaseProxy is created, the default id appears to take the id of the resource when dbProxyName isn't specified. This generates a non unique id, meaning that if we were to spin up another stack with the same id, we would have a clash. Is there a way to generate the id to be unique as default, as is the case for many other constructs?

### Reproduction Steps

```ts
this.proxy = this.database.addProxy("Proxy", {
        maxConnectionsPercent: 100,
        secrets: [this.database.secret],
        vpcSubnets: {
          subnetType,
        },
        vpc,
        securityGroups: [rDSPostgresSecurityGroup],
      });
```

### What did you expect to happen?

Cloud formation id of Proxykhsf98bsj

### What actually happened?

Cloud formation id of Proxy

This is :bug: Bug Report

**Comment by skinny85** [comment]
Thanks for opening the issue @dave-graham. You are correct, this is a bug in the RDS library.

To unblock yourself, you can always pass an explicit `dbProxyName` property when calling `addProxy`.
