### ISSUE TITLE
aws-cdk.core: Expose full context at run time.

### ISSUE THREAD

**Issue by OrEisenberg** [aws/aws-cdk#14383]
I don't know if this is possible, but I would find it very useful if instead of just exposing a method which only lets one query the values associated to individual keys from the runtime context, one could somehow construct the entire dictionary of runtime context. That is, instead of having just a ``ConstructNode.tryGetContext`` method (which requires one to have knowledge ahead of time of what keys are being passed), one could instead get the full context dictionary. 

### Use Case
I'm trying to use the context feature to allow users to pass arbitrary configuration parameters (and therefore don't have knowledge ahead of time of what values will be passed). Unfortunately, I'd like these parameters to be crystalized at synthesis-time, which I think eliminates the option of using CloudFormation parameters. My current working solution is to have the user pass a JSON string which encodes a dictionary for the value of a context key called ``params``, but this feels pretty bad in light of the fact that it means that the user has to embed JSON which encodes a dict into JSON which encodes a dict...

### Proposed Solution

It would be nice if a method called ``getContext`` which returned a dict was exposed in the ``ConstructNode`` class.

### Other

Thanks in advance for considering the request either way!

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
I think you do not want to do this. 

The preferred way of passing configuration should by via explicit parameters. If you don't know what the parameters will be, the parameter could be a dictionary if arbitrary values.

If for whatever reason that doesn't work, you can designate a single context value to hold a dictionary with the parameters (yes, you will not be able to pass it via the CLI, but you can still pass it via `cdk.json` or via code).

But I would suggest the former. Context is not intended as a place to pass construct parameters (it should encode "environmental" settings).
