### ISSUE TITLE
(aws-cloudwatch): AlarmRule.anyOf returns invalid alarm rule

### ISSUE THREAD

**Issue by andsok75** [aws/aws-cdk#14387]
AlarmRule.anyOf(...alarms) where alarms is empty yields "()" which is not a valid alarm rule. 

### Reproduction Steps

    const alarms: Array<cw.Alarm> = [];
    new cw.CompositeAlarm(this, 'CompositeAlarm', {
      compositeAlarmName: "CompositeAlarm",
      alarmRule: cw.AlarmRule.anyOf(...alarms),
    });

Adding the above to the basic example (generated by cdk init) and running cdk synth

### What did you expect to happen?

I expected a valid alarm rule to be created even for cases when the list of alarms passed to anyOf is empty.

### What actually happened?

Running cdk synth and checking the generated template shows the AlarmRule as () which is not valid

  CompositeAlarmF4C3D082:
    Type: AWS::CloudWatch::CompositeAlarm
    Properties:
      AlarmName: CompositeAlarm
      AlarmRule: ()

### Environment

  - **CDK CLI Version  : 1.72.0** 
  - **Framework Version:**
  - **Node.js Version:* v11.13.0* 
  - **OS               :**
  - **Language (Version):** 

### Other

--- 

This is :bug: Bug Report

**Comment by kimsa** [comment]
I ran into the same issue, especially when a team might have multiple environments and is dynamically providing the alarms in the `AlarmRule.anyOf(...)`

e.g.
- Alpha/Beta stage -> ends up with 0 alarms
- Gamma/Prod stage -> ends up with >0 alarms

Ideally, if `AlarmRule.anyOf(...)` has an empty input, it at least throws an error at build time...

Or (as I'm doing to get around this issue), provide an `AlarmRule.fromBoolean(false)`.

**Comment by jacklin213** [comment]
This is a very valid callout. Can we consider having CDK throw an error if `expression` is undefined? If we don't plan on giving `alarmRule` some fallback default
https://github.com/aws/aws-cdk/blob/dc30faa3d7506537ce4c56f291874b20d2c61334/packages/aws-cdk-lib/aws-cloudwatch/lib/alarm-rule.ts#L111-L121

With something like

```
private static concat(operator: Operator, ...operands: IAlarmRule[]): IAlarmRule {
    return new class implements IAlarmRule {
      public renderAlarmRule(): string {
        const expression = operands
          .map(operand => `${operand.renderAlarmRule()}`)
          .join(` ${operator} `);
        if (!expression) {
            // Throw exception here
        }
        return `(${expression})`;
      }
    };
}
```

Otherwise users only find out during deployment time when CloudFormation fails with
```
Resource handler returned message: "Error in AlarmRule [Unsupported token ')' at char 1] (Service: AmazonCloudWatch ...)
```
