### ISSUE TITLE
CDK Pipelines: nested stack definition is not uploaded to S3 artifacts bucket

### ISSUE THREAD

**Issue by rareelement** [aws/aws-cdk#14397]
### Environment

  - **CDK CLI Version:** 1.100.0 (build d996c6d)
  - **Module Version:** 1.100.0 (build d996c6d)
  - **Node.js Version:** v14.16.1
  - **OS:** Ubuntu 20.04.2 LTS
  - **Language (Version):** TypeScript 4.1.3

### Other information
The source code for the project is located at https://github.com/rareelement/cdk-pipeline-with-nested-stacks/tree/master/deployment

Error message in CloudFormation:
![cd-nested-stack-error](https://user-images.githubusercontent.com/49535468/116251169-6a67dc80-a73c-11eb-8e5d-7260cf537c60.png)

Nested stack definition references code in S3:
```      "Type": "AWS::CloudFormation::Stack",
      "Properties": {
        "TemplateURL": {
          "Fn::Join": [
            "",
            [
              "https://s3.us-east-1.",
              {
                "Ref": "AWS::URLSuffix"
              },
              "/",
              {
                "Fn::Sub": "cdk-hnb659fds-assets-${AWS::AccountId}-us-east-1"
              },
              "/50c43da1c5969d0083bfe835019e207594bd5e2b7f2810d4898997a292be8221.json"
            ]
          ]
        },
```

50c43da1c5969d0083bfe835019e207594bd5e2b7f2810d4898997a292be8221.json is not uploaded to cdk-hnb659fds-assets-${AWS::AccountId}-us-east-1 bucket during CodePipeline execution.

Did I miss something in the configuration?

**Comment by otaviomacedo** [comment]
Hi, @rareelement 

In your pipeline stack, you are [referencing the application stack template][1]. But you should also make sure that the asset has been uploaded to S3 by the time the pipeline template is deployed to CloudFormation. To do this, you'll need to use [cdk-assets] in one of your build specs. 

Alternatively, you can try out [CDK Pipelines](https://aws.amazon.com/blogs/developer/cdk-pipelines-continuous-delivery-for-aws-cdk-applications/), which does a lot of that heavy lifting for you.

[1]: https://github.com/rareelement/cdk-pipeline-with-nested-stacks/blob/master/deployment/lib/pipeline-stack.ts#L146
[cdk-assets]: https://www.npmjs.com/package/cdk-assets
