### ISSUE TITLE
(@aws-cdk/pipelines): Cloning cross-account repository in SimpleSynthAction

### ISSUE THREAD

**Issue by hugdru** [aws/aws-cdk#14398]
### The Question
Hi, I am trying to set up a Secure Cross-Account Continuous Delivery Pipeline with four accounts (Dev, Test, Prod, Tools) using Cdk Pipelines.

We have tree repositories that live in the Dev Account. The repo that is used as the sourceAction of the Cdk Pipeline contains all the cdk code and triggers successfully whenever a new commit is pushed. However, the SimpleSynthAction is failing because some lambdas require access to the other repositories that live in a separate account, the Dev Account.

I tried the following, but it did not work: passed the CodeRepositoriesStack (in the Dev Account) to the CdkPipelineStack (in the Tools account) in its extended cdk.StackProps, and then granted read access to the other repos by calling props.codeRepositories.otherRepoInDev.grantRead(simpleSynthAction).

I looked into the CoreRepositoriesStack Resources in Cloudformation and did not see any policies there for the other repos. So the problem might be related to that and assumeRole, but I am not sure.

### Environment

  - **CDK CLI Version:** 1.100.0 (build d996c6d)
  - **Module Version:** 1.100.0
  - **Node.js Version:** v14.15.0
  - **OS:** Ubuntu 21.04
  - **Language (Version):** TypeScript (4.2.4)

### Other information
<details>
  <summary>CdkPipelineStack</summary>

```typescript
import * as cdk from '@aws-cdk/core';
import { CdkPipeline, SimpleSynthAction } from '@aws-cdk/pipelines';

import * as codepipeline from '@aws-cdk/aws-codepipeline';
import * as codepipelineActions from '@aws-cdk/aws-codepipeline-actions';
import { CodeRepositoriesStack } from './codeRepositoriesStack';
import * as codebuild from '@aws-cdk/aws-codebuild';
import { ComputeType } from '@aws-cdk/aws-codebuild';

export type CdkPipelineStackProps = cdk.StackProps & {
    codeRepositories: CodeRepositoriesStack;
};

export class CdkPipelineStack extends cdk.Stack {
    constructor(scope: cdk.Construct, id: string, props: CdkPipelineStackProps) {
        super(scope, id, props);

        const { codeRepositories } = props;

        const sourceArtifact = new codepipeline.Artifact();
        const codeCommitSourceAction = new codepipelineActions.CodeCommitSourceAction({
            actionName: 'GetCode',
            repository: codeRepositories.cdk,
            branch: codeRepositories.mainlineBranchName,
            output: sourceArtifact,
        });

        const codeCommitConfigurationCommands = this.getCodeCommitConfigurationCommands();
        const cloudAssemblyArtifact = new codepipeline.Artifact();
        const simpleSynthAction = new SimpleSynthAction({
            actionName: `CompileAppAndSynthesizeCloudAssembly`,
            environment: {
                buildImage: codebuild.LinuxBuildImage.STANDARD_5_0,
                computeType: ComputeType.SMALL,
                privileged: false,
            },
            cloudAssemblyArtifact,
            sourceArtifact,
            subdirectory: 'cdk',
            installCommands: [...codeCommitConfigurationCommands, 'yarn install:ci'],
            buildCommands: ['yarn build:ci'],
            synthCommand: 'yarn synth:ci',
        });

        new CdkPipeline(this, 'Pipeline', {
            pipelineName: 'Pipeline',
            cloudAssemblyArtifact,
            crossAccountKeys: true,
            selfMutating: true,
            sourceAction: codeCommitSourceAction,
            synthAction: simpleSynthAction,
        });

        codeRepositories.otherA.grantRead(simpleSynthAction);
        codeRepositories.otherB.grantRead(simpleSynthAction);
    }

    private getCodeCommitConfigurationCommands(): string[] {
        return [
            'touch /etc/gitconfig',
            `echo '[credential "https://git-codecommit.eu-central-1.amazonaws.com"]' >> /etc/gitconfig`,
            `echo '    helper = !aws codecommit credential-helper $@' >> /etc/gitconfig`,
            `echo '    UseHttpPath = true' >> /etc/gitconfig`,
        ];
    }
}
```

</details>

<details>
  <summary>CodeRepositoriesStack</summary>

```typescript
import * as cdk from '@aws-cdk/core';
import { IRepository, Repository } from '@aws-cdk/aws-codecommit';

export class CodeRepositoriesStack extends cdk.Stack {
    public readonly cdk: IRepository;
    public readonly otherA: IRepository;
    public readonly otherB: IRepository;
    public readonly mainlineBranchName: string;
    public readonly releaseBranchName: string;

    constructor(scope: cdk.Construct, id: string, props: cdk.StackProps) {
        super(scope, id, props);
        this.cdk = Repository.fromRepositoryName(this, 'Cdk', 'cdk');
        this.otherA = Repository.fromRepositoryName(this, 'OtherA', 'otherA');
        this.otherB = Repository.fromRepositoryName(this, 'OtherB', 'otherB');
        this.mainlineBranchName = 'dev';
        this.releaseBranchName = 'master';
    }
}
```

</details>

<details>
  <summary>App</summary>

```typescript
import { CdkPipelineStack } from '../stacks/cdkPipelineStack';
import { CodeRepositoriesStack } from '../stacks/codeRepositoriesStack';
import * as cdk from '@aws-cdk/core';

const app = new cdk.App();

const devAccount = '#devAccountId';
const codeRepositories = new CodeRepositoriesStack(app, 'CodeRepositories', {
    env: {
        account: devAccount,
        region: 'eu-central-1',
    },
});

const toolsAccount = '#toolsAccountId';
new CdkPipelineStack(app, 'CdkPipeline', {
    env: {
        account: toolsAccount,
        region: 'eu-central-1',
    },
    codeRepositories,
});
```

</details>

**Comment by skinny85** [comment]
Hi @hugdru ,

thanks for opening the issue.

Can you please clarify this statement?

> However, the SimpleSynthAction is failing because some lambdas require access to the other repositories that live in a separate account, the Dev Account.

What are the "some lambdas"? Where do they come from?

Thanks,
Adam

**Comment by hugdru** [comment]
Hi, the lambdas are part of the CDK app. We use the @aws-cdk/aws-lambda-nodejs construct. Some of them depend on code in repositories otherA and otherB in the Dev Account.

<details>

  ```
  "dependencies": {
    "otherA": "git+https://git-codecommit.eu-central-1.amazonaws.com/v1/repos/otherA#1.0.0"
  },
```

</details>

**Comment by skinny85** [comment]
Can you please show the relevant parts of your code then?

**Comment by hugdru** [comment]
Sorry, I didn't explain the situation well. In the buildCommands property in SimpleSynthAction we call yarn build:ci, `lerna bootstrap && tsc --build`, to install the dependencies of the lambda code in the cdk project which includes code in codecommit repos, `"git+https://git-codecommit.eu-central-1.amazonaws.com/v1/repos/otherA#1.0.0"`.

The cdk pipeline in the tools account fails with `fatal: unable to access 'https://git-codecommit.eu-central-1.amazonaws.com/v1/repos/otherA/': The requested URL returned error: 403` because the lambda code depends on repositories otherA and otherB that live in a different account, the dev account. I tried adding the right permissions, as shown in the code in the first comment in CdkPipelineStack, but without success.

**Comment by skinny85** [comment]
Ah. OK. I think this is actually a non-starter - you cannot access CodeCommit repositories cross-account (Repository does not have a resource policy).

What you can do is assume a Role in the repo account before running the CDK commands. I think that's the only way.

Thanks,
Adam
