### ISSUE TITLE
Missing Quicksight Cfn ressources

### ISSUE THREAD

**Issue by nassahmed** [aws/aws-cdk#14399]
Hello, 

CDK seems to be missing the folowing resources for QuickSight : 

- AWS::QuickSight::DataSet
- AWS::QuickSight::DataSource

Is this intended or a bug?
I cannot find theses resources in the cdk library or [documentation](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-quicksight-readme.html) but they are in the [CloudFormation documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_QuickSight.html).

This is :bug: Bug Report

**Comment by peterwoodworth** [comment]
We are currently a few versions behind CFN on the resource spec due to issues in the spec (unrelated to this) preventing us from merging. We're working on this, and whenever the resource spec gets fixed & merged the resources you named will be supported by the CDK.

**Comment by peterwoodworth** [comment]
These are now included in the newest release of the CDK 🎉
