### ISSUE TITLE
synthetics: add run config props for canary

### ISSUE THREAD

**Issue by codingdiaz** [aws/aws-cdk#14407]
Ability to set run config for a synthetics Canary. Mainly to set environment variables and enable tracing.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-synthetics-canary-runconfig.html

### Use Case

To pass environment variables to a synthetic.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by NetaNir** [comment]
duplicate https://github.com/aws/aws-cdk/issues/9300
