### ISSUE TITLE
(aws-mwaa): unable to use existing LogGroup via via mwaa.CfnEnvironment

### ISSUE THREAD

**Issue by Ksennios** [aws/aws-cdk#14414]
I am unable to use existing LogGroups via mwaa.CfnEnvironment. cdk deploy raised error

### Reproduction Steps

```python
class AirflowStack(core.Stack):

    def __init__(self, scope: core.Construct, construct_id: str, environment: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        scheduler_log = aws_logs.LogGroup(
                scope=self,
                id=f'airflow-cloudwatch-{environment}-Scheduler',
                log_group_name=f'/aws/airflow/{environment}/Scheduler',
                encryption_key=key,
                removal_policy=core.RemovalPolicy.DESTROY,
                retention=aws_logs.RetentionDays.INFINITE
            )

        logging_configuration = aws_mwaa.CfnEnvironment.LoggingConfigurationProperty(
            scheduler_logs=aws_mwaa.CfnEnvironment.ModuleLoggingConfigurationProperty(
                enabled=True,
                cloud_watch_log_group_arn=scheduler_log.log_group_arn,
                log_level='WARNING'
           )
        )

        mwaa_env = aws_mwaa.CfnEnvironment(
            scope=self,
            id=f'airflow-{environment}',
            name=f'{environment}',
            airflow_version='1.10.12',
            dag_s3_path='dags',
            environment_class='mw1.small',
            execution_role_arn=role.role_arn,
            kms_key=key.key_arn,
            logging_configuration=logging_configuration,
            max_workers=10,
            network_configuration=network_configuration,
            requirements_s3_path='requirements.txt',
            source_bucket_arn=bucket.bucket_arn,
            tags=None,
            webserver_access_mode='PRIVATE_ONLY'
        )
```

### What did you expect to happen?

Successful deployment of the stack

### What actually happened?

The following error occurred while calling cdk deploy

```
1/4 | 2:35:29 AM | UPDATE_IN_PROGRESS   | AWS::Logs::LogGroup         | airflow-cloudwatch-development-Scheduler (airflowcloudwatchdevelopmentScheduler657AD12B) Resource creation Initiated
1/4 | 2:35:29 AM | UPDATE_COMPLETE      | AWS::Logs::LogGroup         | airflow-cloudwatch-development-Scheduler (airflowcloudwatchdevelopmentScheduler657AD12B)
1/4 | 2:35:35 AM | UPDATE_FAILED        | AWS::MWAA::Environment      | airflow-development-det (airflowdevelopmentdet) Properties validation failed for resource airflowdevelopment with message:
#/LoggingConfiguration/SchedulerLogs/CloudWatchLogGroupArn: failed validation constraint for keyword [pattern]
        tmp\tmp_s9pvqvk\lib\program.js:8154:58
        \_ Kernel._wrapSandboxCode (tmp\tmp_s9pvqvk\lib\program.js:8582:24)
        \_ Kernel._create (tmp\tmp_s9pvqvk\lib\program.js:8154:34)
        \_ Kernel.create (tmp\tmp_s9pvqvk\lib\program.js:7895:29)
        \_ KernelHost.processRequest (tmp\tmp_s9pvqvk\lib\program.js:9479:36)
        \_ KernelHost.run (tmp\tmp_s9pvqvk\lib\program.js:9442:22)
        \_ Immediate._onImmediate (tmp\tmp_s9pvqvk\lib\program.js:9443:46)
        \_ processImmediate (internal/timers.js:456:21)
```

### Environment

  - **CDK CLI Version  :** 1.100.0 (build d996c6d)
  - **Framework Version:**
  - **Node.js Version:** v12.16.1
  - **OS               :**  Windows Server 2016 Datacenter
  - **Language (Version):** Python (3.8.6)

### Other

--- 

This is :bug: Bug Report

**Comment by peterwoodworth** [comment]
Hey @Ksennios, thanks for submitting this issue!

According to [CDK docs](https://docs.aws.amazon.com/cdk/latest/guide/constructs.html#constructs_l1_using), L2 property types can't be used with L1 constructs (and vice versa). I think you'll have to change the `LogGroup` to be a `CfnLogGroup`.

Let me know if this helps!

**Comment by Ksennios** [comment]
Hi @peterwoodworth 

I've changed my code to

```python
class AirflowStack(core.Stack):

    def __init__(self, scope: core.Construct, construct_id: str, environment: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        scheduler_log = aws_logs.CfnLogGroup(
            scope=self,
            id=f'airflow-cloudwatch-{environment}-Scheduler',
            log_group_name=f'/aws/airflow/{environment}/Scheduler',
            kms_key_id=key.key_arn
        )

        logging_configuration = aws_mwaa.CfnEnvironment.LoggingConfigurationProperty(
            scheduler_logs=aws_mwaa.CfnEnvironment.ModuleLoggingConfigurationProperty(
                enabled=True,
                cloud_watch_log_group_arn=scheduler_log.attr_arn,
                log_level='WARNING'
           )
        )

        mwaa_env = aws_mwaa.CfnEnvironment(
            scope=self,
            id=f'airflow-{environment}',
            name=f'{environment}',
            airflow_version='1.10.12',
            dag_s3_path='dags',
            environment_class='mw1.small',
            execution_role_arn=role.role_arn,
            kms_key=key.key_arn,
            logging_configuration=logging_configuration,
            max_workers=10,
            network_configuration=network_configuration,
            requirements_s3_path='requirements.txt',
            source_bucket_arn=bucket.bucket_arn,
            tags=None,
            webserver_access_mode='PRIVATE_ONLY'
        )
```

and got the same error

```
2/6 | 1:23:57 AM | CREATE_IN_PROGRESS   | AWS::Logs::LogGroup         | airflow-cloudwatch-development-Scheduler (airflowcloudwatchdevelopmentScheduler) Resource creation Initiated
2/6 | 1:23:57 AM | CREATE_COMPLETE      | AWS::Logs::LogGroup         | airflow-cloudwatch-development-Scheduler (airflowcloudwatchdevelopmentScheduler) 
2/6 | 1:24:02 AM | UPDATE_FAILED        | AWS::MWAA::Environment      | airflow-development (airflowdevelopment) Properties validation failed for resource airflowdevelopmentdet with message:
#/LoggingConfiguration/SchedulerLogs/CloudWatchLogGroupArn: failed validation constraint for keyword [pattern]
        tmpdpv1ypxn\lib\program.js:8154:58
        \_ Kernel._wrapSandboxCode (tmpdpv1ypxn\lib\program.js:8582:24)
        \_ Kernel._create (tmpdpv1ypxn\lib\program.js:8154:34)
        \_ Kernel.create (tmpdpv1ypxn\lib\program.js:7895:29)
        \_ KernelHost.processRequest (tmpdpv1ypxn\lib\program.js:9479:36)
        \_ KernelHost.run (tmpdpv1ypxn\lib\program.js:9442:22)
        \_ Immediate._onImmediate (tmpdpv1ypxn\lib\program.js:9443:46)
        \_ processImmediate (internal/timers.js:456:21)

```

**Comment by peterwoodworth** [comment]
Apologies for my earlier guidance being incorrect @Ksennios. I didn't have the time yesterday to try and dive into this and reproduce it

I've also found [this issue thread](https://github.com/serverless/serverless/issues/8758#issuecomment-764724762) which may be of help to you. I don't think I'll have time today to go further into this, so in the meantime I'd figure I'd at least point you to this thread which may help you in the meantime!

**Comment by Patrick-Postnl** [comment]
@kostiantyn-priv what was your solution for this issue?

**Comment by kostiantyn-priv** [comment]
@Patrick-Postnl 

My solution is

1. Create LogGroups
```python
       log_groups = {}
        for log_group in ['DAGProcessing', 'Scheduler', 'Task', 'WebServer', 'Worker']:
            log_groups[log_group] = aws_logs.LogGroup(
                scope=self,
                id=f'{environment}-{log_group}',
                log_group_name=f'airflow-{environment}-{log_group}',
                removal_policy=core.RemovalPolicy.DESTROY,
                retention=aws_logs.RetentionDays.SIX_MONTHS
            )
```

2. Create LoggingConfigurationProperty
```python
        logging_configuration = aws_mwaa.CfnEnvironment.LoggingConfigurationProperty(
            dag_processing_logs=aws_mwaa.CfnEnvironment.ModuleLoggingConfigurationProperty(
                enabled=True,
                cloud_watch_log_group_arn=log_groups['DAGProcessing'].log_group_arn,
                log_level='INFO'
            ),
            scheduler_logs=aws_mwaa.CfnEnvironment.ModuleLoggingConfigurationProperty(
                enabled=True,
                cloud_watch_log_group_arn=log_groups['Scheduler'].log_group_arn,
                log_level='INFO'
            ),
            task_logs=aws_mwaa.CfnEnvironment.ModuleLoggingConfigurationProperty(
                enabled=True,
                cloud_watch_log_group_arn=log_groups['Task'].log_group_arn,
                log_level='INFO'
            ),
            webserver_logs=aws_mwaa.CfnEnvironment.ModuleLoggingConfigurationProperty(
                enabled=False,
                cloud_watch_log_group_arn=log_groups['WebServer'].log_group_arn,
                log_level='INFO'
            ),
            worker_logs=aws_mwaa.CfnEnvironment.ModuleLoggingConfigurationProperty(
                enabled=True,
                cloud_watch_log_group_arn=log_groups['Worker'].log_group_arn,
                log_level='WARNING'
            )
        )
```
3. And use it in mwaa
```python
        mwaa_env = aws_mwaa.CfnEnvironment(
            scope=self,
            id='airflow',
            name=f'{environment}',
            airflow_configuration_options=None,
            airflow_version='1.10.12',
            dag_s3_path='dags',
            environment_class='mw1.small',
            execution_role_arn=role.role_arn,
            logging_configuration=logging_configuration,
            max_workers=10,
            network_configuration=network_configuration,
            plugins_s3_object_version=None,
            plugins_s3_path=None,
            requirements_s3_object_version=None,
            requirements_s3_path='requirements.txt',
            source_bucket_arn=bucket.bucket_arn,
            tags=None,
            webserver_access_mode='PRIVATE_ONLY',
            weekly_maintenance_window_start='SUN:03:30'
        )
```

**Comment by omazhelis** [comment]
> [@Patrick-Postnl](https://github.com/Patrick-Postnl)
> 
> My solution is
> 
> 1. Create LogGroups
> 
>        log_groups = {}
>         for log_group in ['DAGProcessing', 'Scheduler', 'Task', 'WebServer', 'Worker']:
>             log_groups[log_group] = aws_logs.LogGroup(
>                 scope=self,
>                 id=f'{environment}-{log_group}',
>                 log_group_name=f'airflow-{environment}-{log_group}',
>                 removal_policy=core.RemovalPolicy.DESTROY,
>                 retention=aws_logs.RetentionDays.SIX_MONTHS
>             )
> 2. Create LoggingConfigurationProperty
> 
>         logging_configuration = aws_mwaa.CfnEnvironment.LoggingConfigurationProperty(
>             dag_processing_logs=aws_mwaa.CfnEnvironment.ModuleLoggingConfigurationProperty(
>                 enabled=True,
>                 cloud_watch_log_group_arn=log_groups['DAGProcessing'].log_group_arn,
>                 log_level='INFO'
>             ),
>             scheduler_logs=aws_mwaa.CfnEnvironment.ModuleLoggingConfigurationProperty(
>                 enabled=True,
>                 cloud_watch_log_group_arn=log_groups['Scheduler'].log_group_arn,
>                 log_level='INFO'
>             ),
>             task_logs=aws_mwaa.CfnEnvironment.ModuleLoggingConfigurationProperty(
>                 enabled=True,
>                 cloud_watch_log_group_arn=log_groups['Task'].log_group_arn,
>                 log_level='INFO'
>             ),
>             webserver_logs=aws_mwaa.CfnEnvironment.ModuleLoggingConfigurationProperty(
>                 enabled=False,
>                 cloud_watch_log_group_arn=log_groups['WebServer'].log_group_arn,
>                 log_level='INFO'
>             ),
>             worker_logs=aws_mwaa.CfnEnvironment.ModuleLoggingConfigurationProperty(
>                 enabled=True,
>                 cloud_watch_log_group_arn=log_groups['Worker'].log_group_arn,
>                 log_level='WARNING'
>             )
>         )
> 3. And use it in mwaa
> 
>         mwaa_env = aws_mwaa.CfnEnvironment(
>             scope=self,
>             id='airflow',
>             name=f'{environment}',
>             airflow_configuration_options=None,
>             airflow_version='1.10.12',
>             dag_s3_path='dags',
>             environment_class='mw1.small',
>             execution_role_arn=role.role_arn,
>             logging_configuration=logging_configuration,
>             max_workers=10,
>             network_configuration=network_configuration,
>             plugins_s3_object_version=None,
>             plugins_s3_path=None,
>             requirements_s3_object_version=None,
>             requirements_s3_path='requirements.txt',
>             source_bucket_arn=bucket.bucket_arn,
>             tags=None,
>             webserver_access_mode='PRIVATE_ONLY',
>             weekly_maintenance_window_start='SUN:03:30'
>         )

Could anyone please confirm that this is actually working? Looks like supplying a custom `cloud_watch_log_group_arn` to `ModuleLoggingConfigurationProperty` has no effect. There is also a note in the [docs](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_mwaa/CfnEnvironment.html#moduleloggingconfigurationproperty) saying that 

> CloudWatchLogGroupArn is available only as a return value, accessible when specified as an attribute in the `Fn:GetAtt <https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-mwaa-environment.html#aws-resource-mwaa-environment-return-values>`_ intrinsic function. Any value you provide for CloudWatchLogGroupArn is discarded by Amazon MWAA.

**Comment by hupe1980** [comment]
@omazhelis **No, this is not working.** The `CloudWatchLogGroupArn` in `ModuleLoggingConfigurationProperty` is **only a return value** and cannot be set manually. Any value you provide for it will be ignored by Amazon MWAA.  

For changing the log retention, I use a **custom resource**. I’ve implemented this in my **cdk-mwaa** GitHub repo. You can check out the details here:  
🔗 [GitHub - cdk-mwaa: log retention implementation](https://github.com/hupe1980/cdk-mwaa/blob/2aa85ffed05c282164fdc7a9e2c6b236683a0e64/src/environment.ts#L198)
