### ISSUE TITLE
(ec2): S3 interface VPC endpoint

### ISSUE THREAD

**Issue by lysterious** [aws/aws-cdk#14423]
### Use Case
To use S3 without a NAT GW, in an isolated subnet.

### Proposed Solution
Adding missing definition in code

### Other
 👋 I may be able to implement this feature request

This is a :rocket: Feature Request

**Comment by jogold** [comment]
S3 is available as a gateway (not interface) vpc endpoint.

Example https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-ec2/test/integ.vpc-endpoint.lit.ts

See https://docs.aws.amazon.com/vpc/latest/privatelink/vpc-endpoints-s3.html

**Comment by lysterious** [comment]
Hello @jogold,
As of February 2021, I believe that S3 is available as an Interface VPC Endpoint as well: https://aws.amazon.com/blogs/aws/aws-privatelink-for-amazon-s3-now-available/

I have managed to launch it manually in the console and test it out, but couldn't find support for it in the CDK.

**Comment by jogold** [comment]
> Hello @jogold,
> As of February 2021, I believe that S3 is available as an Interface VPC Endpoint as well: [aws.amazon.com/blogs/aws/aws-privatelink-for-amazon-s3-now-available](https://aws.amazon.com/blogs/aws/aws-privatelink-for-amazon-s3-now-available/)
> 
> I have managed to launch it manually in the console and test it out, but couldn't find support for it in the CDK.

You're right, missed that.

**Comment by ThinkinGim** [comment]
Would you mind updating me on the status of this request? If there is no issue to add  S3 into InterfaceVpcEndpointAwsService, it should be done as quick as possible because to access to S3 through Interface-Endpoint is common practice for security reason, I think.

**Comment by TheRealAmazonKendra** [comment]
This has now been completed.
