### ISSUE TITLE
aws-codepipeline-actions: Termination protection and tags are not applied to stack when CloudFormationCreateUpdateStackAction is used

### ISSUE THREAD

**Issue by rareelement** [aws/aws-cdk#14429]
Stack terminationProtection property and stack tags are not applied to a stack deployed with CloudFormationCreateUpdateStackAction class. If the stack is deployed using cdk cli deploy command those settings are properly set.

### Reproduction Steps
Create a stack with termination protection

```ts
const stack = new cdk.Stack(app, 'some-stack', {
    terminationProtection: true,
    tags: {
        'important_tag': 'that\'s right'
    }
});

const bucket = new s3.Bucket(stack, 'Bucket', {
    removalPolicy: cdk.RemovalPolicy.DESTROY,
});
```

Deploy this stack using CloudFormationCreateUpdateStackAction

```ts
   deployStage.addAction(
      new codepipeline_actions.CloudFormationCreateUpdateStackAction({ 
        actionName: 'Deploy',
        templatePath: cdkSynthArtifacts.atPath('some-stack.template.json'), 
        stackName: 'some-stack',
        adminPermissions: true,
      }),
    );
```

### What did you expect to happen?
I expect created stack to have termination protection enabled and both the stack and S3 bucket to contain 'important_tag' tag.

### What actually happened?

Stack termination protection is not enabled and tags are missing.

### Environment

    CDK CLI Version: 1.100.0 (build d996c6d)
    Module Version: 1.100.0 (build d996c6d)
    Node.js Version: v14.16.1
    OS: Ubuntu 20.04.2 LTS
    Language (Version): TypeScript 4.1.3

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hey @rareelement ,

thanks for opening the issue.

1. The `terminationProtection` setting is not available to be set on the CodePipeline CloudFormation actions, unfortunately (this is CodePipeline limitation, nothing to do with CDK). So you'll have to change that setting manually if you want to have it in your pipeline.
2. For tags - can you try using `Tags.of(this).add('important_tag', 'that\'s right')`, and see if that helps?

Thanks,
Adam

**Comment by rareelement** [comment]
@skinny85  Thank you for your quick reply.

1. Can you please advise what's the process of raising a feature request for the CodePipeline?

As a workaround, I guess, I can just create a CodeBuild action which will enable terminationProtection for the stack after the deployment finishes or will deploy the stack using cdk cli instead of utilizing codepipeline actions.

2. The code below doesn't add tag at the stack level, but tags the bucket (I had to fix the invalid tag value):

```
cdk.Tags.of(stack).add('important_tag', 'thatsright');
```

**Comment by skinny85** [comment]
> 1. Can you please advise what's the process of raising a feature request for the CodePipeline?

If you have AWS Premium Support, you can raise a feature request to the CodePipeline team through there.

> As a workaround, I guess, I can just create a CodeBuild action which will enable terminationProtection for the stack after the deployment finishes or will deploy the stack using cdk cli instead of utilizing codepipeline actions.

Yep, that sounds good to me.

> 2. The code below doesn't add tag at the stack level, but tags the bucket (I had to fix the invalid tag value):
> 
> ```
> cdk.Tags.of(stack).add('important_tag', 'thatsright');
> ```

Yes, you're right. This is tricky. For the Stack-level tags, you actually, in CodePipeline, have to pass them through a separate file. Here's the documentation on that topic: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/continuous-delivery-codepipeline-cfn-artifacts.html.

Thanks,
Adam

**Comment by rareelement** [comment]
> For the Stack-level tags, you actually, in CodePipeline, have to pass them through a separate file. Here's the documentation on that topic: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/continuous-delivery-codepipeline-cfn-artifacts.html.

So it can be fixed/implemented? ;)

Thanks

**Comment by skinny85** [comment]
Not in the CodePipeline construct, as it doesn't take a Stack as its input (just a template file, which might or might not have been created using the CDK).

It is implemented in the [CDK Pipelines](https://docs.aws.amazon.com/cdk/api/latest/docs/pipelines-readme.html) module though.
