### ISSUE TITLE
Guidelines: consider renaming "asXxx" to "_asXxx"

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#1443]
The various "asXxx" methods/properties are used to indicate "private interface implementation" (supported in C# for example). I was wondering if perhaps a more explicit way to indicate this would be to use an underscore prefix to make it clearer for people that this is not something they are expected to interact with (I've seen many people use those methods).

jsii also hides any underscore prefixed members, which has the benefit that non-JS languages won't have them.

@rix0rrr @RomainMuller - thoughts?

**Comment by RomainMuller** [comment]
As long as "prohibiting usage from non-JS languages" cannot block a user out of something they need to be doing, then I'm fine with it.

**Comment by rix0rrr** [comment]
I'm not in favor of removing the "as", but the prefixing with "_", sure.

I share Romain's concern that we'll be chipping away at JSII users' ability to define fully-fledged constructs in this way, or (say) reimplement ApplicationLoadBalancer slightly differently if they wanted to.

On the other hand, let's wait for that to become a real issue and then we can always introduce two levels of "special members", where one is more hidden than the other.

**Comment by eladb** [comment]
okay so we'll go with `_asXxx`
