### ISSUE TITLE
@aws-cdk/aws-route53resolver: Route53 Resolver DNS Firewall Resources

### ISSUE THREAD

**Issue by rafaelpereyra** [aws/aws-cdk#14435]
Add initial support for Route53 Resolver DNS Firewall recently introduced by AWS. (https://aws.amazon.com/about-aws/whats-new/2021/03/introducing-amazon-route-53-resolver-dns-firewall/)

### Use Case

Any user could benefit of this feature that is easy to activate and configure in existing environments improving security and observability of DNS issues. 

### Proposed Solution

Implement the new resources as part of the aws-route53resolver module:

AWS::Route53Resolver::FirewallRuleGroup
AWS::Route53Resolver::FirewallDomainList
AWS::Route53Resolver::FirewallRuleGroupAssociation

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by njlynch** [comment]
Thanks for the feature request!

These will be supported (at the same level as the rest of Route53Resolver, with the "level 1" `Cfn*` classes) when the latest version of the CloudFormation spec is merged in. The current PR tracking this is #14411. Once that is merged, support for the above resources will be included.
