### ISSUE TITLE
(aws_cdk.aws_s3_deployment.BucketDeployment): Unable to perform upload

### ISSUE THREAD

**Issue by evanerwee** [aws/aws-cdk#14459]
# Upload asset to S3 bucket
        self.pefix_common_lambda_layer_s3_dep_id = f'{helpers.ENTITY_PREFIX}common_lambda_layer_asset{helpers.STAGE}'
        self.prefix_common_lambda_layer_s3_dep = s3_dep.BucketDeployment(
            self,
            self.prefix_common_lambda_layer_s3_dep_id,
            destination_bucket=props['ll_bucket_name'],
            sources=[_lambda.Code.from_asset('../mssp-master/lambda/Common_Layer/layers/python.zip')],
            retain_on_delete=True
        )

/************************************************************/
/ More information

props['ll_bucket_name'] = <aws_cdk.aws_s3.Bucket object at 0x0000022A05BA1670>

    jsii.create(BucketDeployment, self, [scope, id, props])
  File "C:\usa-repo\mssp-master\venv\lib\site-packages\jsii\_kernel\__init__.py", line 275, in create
    response = self.provider.create(
  File "C:\usa-repo\mssp-master\venv\lib\site-packages\jsii\_kernel\providers\process.py", line 344, in create
    return self._process.send(request, CreateResponse)
  File "C:\usa-repo\mssp-master\venv\lib\site-packages\jsii\_kernel\providers\process.py", line 326, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: Cannot read property 'bucketName' of undefined

(I use nested stack and props work for everything else.)

**Comment by peterwoodworth** [comment]
Not sure i have enough info to help you out here @evanerwee, how are you passing in the bucket as a prop?
