### ISSUE TITLE
aws-cdk-lib: Module '"aws-cdk-lib"' has no exported member 'core'.

### ISSUE THREAD

**Issue by dan-lind** [aws/aws-cdk#14453]
I wanted to test CDK v2 RC-1 and followed the docs here:
https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib-readme.html

It gives an example of a classic import, like this
```
import { core, aws_s3 as s3 } from 'aws-cdk-lib';

const app = new core.App();
const stack = new core.Stack(app, 'TestStack');

new s3.Bucket(stack, 'TestBucket');
```

However when I'm trying to import like below, I get the error "Module '"aws-cdk-lib"' has no exported member 'core'." 

```
import {
    core,
    aws_ecs as ecs,
    aws_ec2 as ec2,
    aws_autoscaling as autoscaling,
    aws_iam as iam,
    aws_elasticloadbalancingv2 as elbv2,
    StackProps,
    Stack,
} from 'aws-cdk-lib';
```

---

This is a 📕 documentation issue

**Comment by NetaNir** [comment]
You are right, the `core` module has been removed, all core types such as `Stack`, `App` are now at the root level:

```ts
import {App, Stack } from 'aws-cdk-lib'
```

Updated the docs to have the right import.
