### ISSUE TITLE
(ecs.fargateservice): Fargate service creation times out during deploy

### ISSUE THREAD

**Issue by MattKirchhof** [aws/aws-cdk#14457]
This relatively simple aws cdk defined stack fails to deploy due to a timeout (3+ hours for the timeout to occur) at the final step, creating the fargate service. This stack is loosely based on the example provided here:

https://github.com/aws-samples/aws-cdk-examples/tree/master/python/ecs/fargate-service-with-autoscaling/

And our personalized version of the cdk defined stack is listed here:

```
class MyStack(core.Stack):
    def __init__(self, scope: core.Construct, construct_id: str, environment_name: str,  **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        env_name = "-" + environment_name
        if environment_name == "red":
            subnet_id = "subnet-xxx"
            fargate_capacity = 30
        else:
            subnet_id = "subnet-yyy"
            fargate_capacity = 3

        # Retrieve VPC information
        vpc = ec2.Vpc.from_lookup(self, "VPC",
            vpc_id = "vpc-xxx"
        )

        vpc_subnet = ec2.Subnet.from_subnet_id(self,
            id="subnet-xxx",
            subnet_id=subnet_id
        )

        # Init a new cluster with id
        cluster = ecs.Cluster(
            self, 'fargate-service-autoscaling-cluster' + env_name,
            vpc=vpc,
            capacity_providers=['FARGATE_SPOT']
        )

        dockerRepository = ecr.Repository.from_repository_arn(
            self,
            "docker_repository",
            "arn:aws:ecr:us-east-1:12345678912:company/mydocker"
        )
    
        containerImg = ecs.ContainerImage.from_ecr_repository(
            dockerRepository 
        )

        fargateTask = ecs.FargateTaskDefinition(self,
            "task_definition" + env_name,
            cpu=1024,
            memory_limit_mib=2048
        )
        fargateTask .add_container(
            "task_container" + env_name,
            image=containerImg,
            stop_timeout=core.Duration.seconds(60)
        )

        # Define fargate security group
        new_security_group = ec2.SecurityGroup(self, 
            "security_group" + env_name,
            vpc=vpc,
            allow_all_outbound=True
        )
        new_security_group.add_ingress_rule(
            ec2.Peer.ipv4('10.0.0.0/8'), 
            ec2.Port.all_tcp()
        )
        new_security_group.add_ingress_rule(
            ec2.Peer.ipv4('0.0.0.0/0'), 
            ec2.Port.tcp(1234)
        )
        new_security_group.add_ingress_rule(
            ec2.Peer.ipv4('0.0.0.0/0'), 
            ec2.Port.tcp_range(1000, 1234)
        )


        # Create Fargate Service
        fargate_service = ecs.FargateService(self, 
            "fargate-service" + env_name,
            cluster=cluster,
            task_definition=fargateTask,
            assign_public_ip=True,
            desired_count=1,
            vpc_subnets=vpc_subnet,
            #enable_ecs_managed_tags=True,
            security_group=new_security_group
        )
```

### Reproduction Steps

Attempt to deploy the above cdk definintion (python)

### What did you expect to happen?

Fargate service is expected to successfully create and continue the ecs cloudFormation process

### What actually happened?

cdk deploy hangs (3-4 hours) and times out at step 7 of 15 with the following exception:

  7/15 Currently in progress: MyStack, fargateserviceblue2Service663729E3
  7/15 | 4:46:54 PM | CREATE_FAILED        | AWS::ECS::Service        | fargate-service-blue2/Service (fargateserviceblue2Service663729E3) Resource timed out waiting for completion (RequestToken: 20a1b215-c78c-a4b2-b23d-aa886ad562cf)
        new BaseService (C:\Users\xxx\AppData\Local\Temp\jsii-kernel-V3I6Yf\node_modules\@aws-cdk\aws-ecs\lib\base\base-service.js:137:25)
        \_ new FargateService (C:\Users\xxx\AppData\Local\Temp\jsii-kernel-V3I6Yf\node_modules\@aws-cdk\aws-ecs\lib\fargate\fargate-service.js:38:9)
        \_ C:\Users\xxx\AppData\Local\Temp\tmpda3gdox0\lib\program.js:8154:58
        \_ Kernel._wrapSandboxCode (C:\Users\xxx\AppData\Local\Temp\tmpda3gdox0\lib\program.js:8582:24)
        \_ Kernel._create (C:\Users\xxx\AppData\Local\Temp\tmpda3gdox0\lib\program.js:8154:34)
        \_ Kernel.create (C:\Users\xxx\AppData\Local\Temp\tmpda3gdox0\lib\program.js:7895:29)
        \_ KernelHost.processRequest (C:\Users\xxx\AppData\Local\Temp\tmpda3gdox0\lib\program.js:9479:36)
        \_ KernelHost.run (C:\Users\xxx\AppData\Local\Temp\tmpda3gdox0\lib\program.js:9442:22)
        \_ Immediate._onImmediate (C:\Users\xxx\AppData\Local\Temp\tmpda3gdox0\lib\program.js:9443:46)
        \_ processImmediate (internal/timers.js:461:21)
  7/15 | 4:47:04 PM | UPDATE_ROLLBACK_IN_P | AWS::CloudFormation::Stack | MyStack The following resource(s) failed to create: [fargateserviceblue2Service663729E3]. 

### Environment

  - **CDK CLI Version  :** 1.100.0 (build d996c6d)
  - **Framework Version:** 
  - **Node.js Version:**  v14.16.1
  - **OS               :** Windows 10 Pro
  - **Language (Version):** Python 3.9.4

### Other
What we have tried:

- Removed creation of the fargate_service, and the cdk deploy works properly.
- Simplifying the fargate_service to its current state
- Removed fargate autoscaling.
- ECS and CloudTrail do not seem to provide information on why the service creation timed out.

Thanks for your help!
--- 

This is :bug: Bug Report

**Comment by SoManyHs** [comment]
Hi @MattKirchhof,
If you look in your ECS console and click into your service, does it say anything under the `events` tab? That might provide a little more information as to why the service failed to start.

**Comment by MattKirchhof** [comment]
Hello @SoManyHs 

Thank you for your help. Watching closely within the ecs events tab, we noticed it would repeatedly try to start the given task and fail. It appears we get a 403 when trying to resolve the reference to our docker container image, likely due to IAM permissions being incorrectly set.

`CannotPullContainerError: inspect image has been retried 1 time(s): failed to resolve ref "xxxxx.xxx": unexpected status code [manifests 6981141]: 403 Forbidden`

Thank you for the help!
