### ISSUE TITLE
Thoughts about a new build system

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#1445]
## Phases

A full build process of every module in the library consists of the following phases:

0. install (install dependencies)
1. gen (code generation)
2. compile (jsii)
3. lint (tslint, pkglint, awslint)
4. test (coverage + nodeunit/jest)
5. package (jsii-pacmak)

Today, our full build process runs in four phases:
1. install
2. build (gen + compile + lint)
3. test (compile + test)
4. package

Furthermore, the way "package.json" files work today, if we want to introduce options to the build system or new phases, we need to modify all "package.json" files. That can be done quite easily with pkglint but why?

I saw that people recommend to use a single `build` npm script that will be the entry point for a central build system. If you just execute "npm run build" the entire process will be performed (all phases). But you could also run certain phases by specifying the phase name. e.g. "npm run build compile" or "npm run build gen". 

If you want to run a specific phase across the repo, you could just do "lerna run build gen" and it will generate everything or "lerna run build test" to run all tests.

We should also support something like "build compile test" in case you want to compile & test, but we should keep each build phase with minimum overhead (i.e. if you just want to run test without compilation because you have a watcher in the background, you shouldn't pay that price).

## Distributed Builds

When running in CI, I would love to be able to distribute the build tasks based on the dep graph. Each node in the graph will be responsible to full-build one module.

The challenge would naturally be how to orchestrate the artifact management such that the right artifacts will be available to each module based on it's dependency graph.

Say we produce a CodePipline pipeline every time a build starts which has a task to build each module in the dependency graph. I believe CodePipeline is theoretically designed to support exactly something like this but I am concerned about limits (we have over 150 modules) and we want maximum parallelism. Still it does seem like we might get most of the artifact management capabilities from it.

If CodePipelines won't work, we should look into Step Functions as an alternative.

## Caching

My observation is that merkle-build (the tool that checks if we can avoid rebuilding by hashing the source contents and dependencies) is taking up a lot of time, and doesn't seem like it's providing too much value at the moment.

I think we should probably just get rid of it for now, but I'd love to be able to cache build artifacts and reuse them if they haven't changed (also amongst developers).

**Comment by RomainMuller** [comment]
I'm not sure whether striping the build steps over multiple containers (phased in dependency layers) will actually save time - the overhead of provisioning the build container, and making everything needed available on each host is probably going to eat away the benefits of the parallelization. That sounds like a fairly costly marginal optimization to me (but I will not fight to prevent it from happening).

Regarding the Merkle tree building, I had investigated it a while back and the culprit is that it is computed entirely serially. It would be much faster if it were to be done in parallel (in-process), but this makes symlink-loop detection trickier to implement.

**Comment by eladb** [comment]
#1475 - let's start by removing merkle build
