### ISSUE TITLE
(aws-eks): Support bottlerocket `arm64` AMI's

### ISSUE THREAD

**Issue by gfina** [aws/aws-cdk#14466]
We currently only use `x86_64` for bottlerocket AMI's even though sometimes `arm64` is needed (for graviton instance types for example). 

---------------------------------

*Originaly reported as*

EKS: using add_auto_scaling_group_capacity fails  OS BOTTLEROCKET and Graviton Instance type  

description of the bug:

EKS: using add_auto_scaling_group_capacity fails with machine_image_type=eks.MachineImageType.BOTTLEROCKET and Graviton Instance type  

        cluster.add_auto_scaling_group_capacity(id='BottlerocketNodes', instance_type=ec2.InstanceType('t4g.large'),
                                                machine_image_type=eks.MachineImageType.BOTTLEROCKET,
                                                  min_capacity=2.0)

### Reproduction Steps
setup an EKS cluster with CDK and then add to it an addition capacity, with BOTTLEROCKET and graviton instance using this:
 
```
   cluster.add_auto_scaling_group_capacity(id='BottlerocketNodes', instance_type=ec2.InstanceType('t4g.large'),
                                                machine_image_type=eks.MachineImageType.BOTTLEROCKET,
                                                  min_capacity=2.0)
```

cdk  --version
1.101.0 (build 149f0fc)

The Autoscaling throws and error: 
Launching a new EC2 instance. Status Reason: The architecture 'arm64' of the specified instance type does not match the architecture 'x86_64' of the specified AMI. Specify an instance type and an AMI that have matching architectures, and try again. You can use 'describe-instance-types' or 'describe-images' to discover the architecture of the instance type or AMI. Launching EC2 instance failed

### What did you expect to happen?

I would expect an AutoScaling group to be created with 2 instances on t4g.large. 

### What actually happened?

Launching a new EC2 instance. Status Reason: The architecture 'arm64' of the specified instance type does not match the architecture 'x86_64' of the specified AMI. Specify an instance type and an AMI that have matching architectures, and try again. You can use 'describe-instance-types' or 'describe-images' to discover the architecture of the instance type or AMI. Launching EC2 instance failed

### Environment

  - **CDK CLI Version  : **   1.101.0 (build 149f0fc)
  - **Framework Version:**
  - **Node.js Version:**  v12.10.0 
  - **OS               :**  Mac OS Big Sur 10.2.3 
  - **Language (Version):**   Python 3.8.7 (v3.8.7:6503f05dd5, Dec 21 2020, 12:45:15) 

### Other
This code swapping out the instance works as expected: 
```
        cluster.add_auto_scaling_group_capacity(id='BottlerocketNodes', instance_type=ec2.InstanceType('t3.xlarge'),
                                                machine_image_type=eks.MachineImageType.BOTTLEROCKET,
                                                  min_capacity=2.0)
```
So it appears that CDK is not making the correct AMI decision with Bottlerocket and ARM instance types.   However is for intel instance types. 

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment]
Looks like we are always assuming `x86_64` for bottlerocket.

https://github.com/aws/aws-cdk/blob/527f6622146f007035ca669c33ad73861afe608a/packages/%40aws-cdk/aws-eks/lib/private/bottlerocket.ts#L30

@pahud You have some insight on this? Can we use `arm64` in the SSM parameter type when needed?

**Comment by rmsy** [comment]
Just wanted to ask about the same thing, but for the ECS variant of the image:
https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-ecs/lib/cluster.ts#L788

An AMI does exist for `aws-ecs-1`/`arm64`. If this is something straightforward to submit a PR for, I would be willing to give it a shot.

**Comment by pahud** [comment]
> Looks like we are always assuming `x86_64` for bottlerocket.
> 
> https://github.com/aws/aws-cdk/blob/527f6622146f007035ca669c33ad73861afe608a/packages/%40aws-cdk/aws-eks/lib/private/bottlerocket.ts#L30
> 
> @pahud You have some insight on this? Can we use `arm64` in the SSM parameter type when needed?


According to the bottlerocket github repo, we do have `arm64` support now.
https://github.com/bottlerocket-os/bottlerocket#architectures

```sh
aws ssm get-parameters --names /aws/service/bottlerocket/aws-k8s-1.20/arm64/latest/image_id
{
    "Parameters": [
        {
            "Name": "/aws/service/bottlerocket/aws-k8s-1.20/arm64/latest/image_id",
            "Type": "String",
            "Value": "ami-0212d00ded9cb67f4",
            "Version": 2,
            "LastModifiedDate": "2021-05-20T01:14:42.129000+08:00",
            "ARN": "arn:aws:ssm:ap-northeast-1::parameter/aws/service/bottlerocket/aws-k8s-1.20/arm64/latest/image_id",
            "DataType": "text"
        }
    ],
    "InvalidParameters": []
}
```

I support the PR for it.

**Comment by iliapolo** [comment]
@pahud Thanks. Converting this to a feature request. Happy to accept a contribution here.
