### ISSUE TITLE
(core): add setter for termination protection

### ISSUE THREAD

**Issue by rittneje** [aws/aws-cdk#14463]
Please add a setter for the termination protection flag to the `Stack` class. https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.Stack.html#terminationprotection

### Use Case

We would like to be able to automatically enable termination protection to all of our stacks via an `Aspect`. However, since there is no setter for this property (it can only be set in the constructor), there's no way for that to work.

---

This is a :rocket: Feature Request

**Comment by jashgala** [comment]
Not sure if this will solve your problem, but have you considered creating an aspect that loops over your stacks and sets termination protection over them?

e.g.

```typescript
export class DisableTerminationProtectionAspect implements IAspect {
  visit(construct: IConstruct): void {
    if (Stack.isStack(construct)) {
      (<any>construct).terminationProtection = false;
    }
  }
}
```

And then add the aspect to all your stacks which you are defining:
```typescript
for (const stack of listOfStacks) {
      Aspects.of(stack).add(new StackTerminationAllowedAspect());
}
```

**Comment by jashgala** [comment]
@rittneje 

I tried testing this behavior locally and here's a easy to re-produce example:
(Tested with AWS CDK version 1.102.0 build a75d52f - currently latest on NPM)

```typescript
import * as cdk from '@aws-cdk/core';
import * as s3 from '@aws-cdk/aws-s3';
import { Aspects, IAspect, IConstruct, Stack } from '@aws-cdk/core';

export class DisableTerminationProtectionAspect implements IAspect {
  visit(construct: IConstruct): void {
    if (Stack.isStack(construct)) {
      (<any>construct).terminationProtection = false;
    }
  }
}

export class CdkPlaygroundStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);
    const bucket = new s3.Bucket(this, 'Bucket');
  }
}

const app = new cdk.App();

const stack1 =new CdkPlaygroundStack(app, 'CdkPlaygroundStack1', {
  env: {
    account: process.env.ACCOUNT_ID,
    region: process.env.REGION,
  },
  terminationProtection: true
});


const stack2 = new CdkPlaygroundStack(app, 'CdkPlaygroundStack2', {
  env: {
    account: process.env.ACCOUNT_ID,
    region: process.env.REGION,
  },
  terminationProtection: true
});


Aspects.of(stack1).add(new DisableTerminationProtectionAspect());
Aspects.of(stack2).add(new DisableTerminationProtectionAspect());
```

When I deployed the above without the last two lines, the stacks deployed with termination protection enabled. However, after adding the last two lines and re-deploying, the stacks have their termination protection disabled.

Somehow the aspect is working fine without needing a separate setter.

**Comment by rittneje** [comment]
Then it sounds like there is a bug in CDK allowing you to set purportedly read-only fields.

For example, the Java documentation does not have a setter. https://docs.aws.amazon.com/cdk/api/latest/java/index.html?software/amazon/awscdk/core/Stack.html

Neither does the C# documentation. https://docs.aws.amazon.com/cdk/api/latest/dotnet/api/Amazon.CDK.Stack.html#Amazon_CDK_Stack_TerminationProtection

Even the TypeScript code claims it is read-only. https://github.com/aws/aws-cdk/blob/283ed02c64f827161edba3e11c3cead3b54b7ee9/packages/%40aws-cdk/core/lib/stack.ts#L132-L137

**Comment by rittneje** [comment]
ping @rix0rrr

**Comment by rittneje** [comment]
Do not close.

**Comment by msambol** [comment]
@rittneje Can I take this?
