### ISSUE TITLE
(Tags): Not able to tag imported role from CloudFormation

### ISSUE THREAD

**Issue by 0xjjoyy** [aws/aws-cdk#14461]
I'm importing the bootstrap template and adding a tag to the role. Though not tag is added.

I import as a L1 CfnRole then create the L2 role.

### Reproduction Steps

```python
        template = cfn_inc.CfnInclude(
            self, "bootstrap-template", template_file="bootstrap-template.yaml"
        )

        cfn_file_publishing_role = template.get_resource("FilePublishingRole")

        file_publishing_role = iam.Role.from_role_arn(
            self, "file_publishing_role_l2", cfn_file_publishing_role.attr_arn
        )

        cdk.Tags.of(file_publishing_role).add("test-key", "test-value")


```

### What did you expect to happen?

Tag key test-key and tag value test-value to be added.

Tag a role that exists in a CloudFormation template.

### What actually happened?

No error message, silently doesn't do anything and fails.

### Environment

  - **CDK CLI Version  :**
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):** 

### Other

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hi @0xjjoyy ,

thanks for opening the issue. The problem is you're passing `file_publishing_role` to the `Tags` static factory method. That Role is not a resource - it's just a concept of an existing Role CDK uses. So, it can't really be modified in any way.

If you pass `cfn_file_publishing_role` there, like this:

```python
        template = cfn_inc.CfnInclude(
            self, "bootstrap-template", template_file="bootstrap-template.yaml"
        )

        cfn_file_publishing_role = template.get_resource("FilePublishingRole")

        file_publishing_role = iam.Role.from_role_arn(
            self, "file_publishing_role_l2", cfn_file_publishing_role.attr_arn
        )

        cdk.Tags.of(cfn_file_publishing_role).add("test-key", "test-value")
```

This will do what you want.

Thanks,
Adam

**Comment by 0xjjoyy** [comment]
Thanks! I didn't realize that cdk.Tags.of could be applied to L1 resources. Good to know!
