### ISSUE TITLE
(CodeBuild): Add KMS decrypt to policy for secrets imported by name

### ISSUE THREAD

**Issue by Kruspe** [aws/aws-cdk#14477]
Following up on #14043 and #14226. I was thinking about also allowing the `kms:Decrypt` action for secrets that get provided via `Token`.

https://github.com/aws/aws-cdk/blob/e31587a2d644637ba85449396c6274bcb5e1569a/packages/%40aws-cdk/aws-codebuild/lib/project.ts#L766-L773

Since we already assume that the value is an Arn, we could parse it and then create an Arn for the kms key with the wildcard and add it to the set of `kmsIamResources`.

If this is worth implementing I can create the PR. :)

### Environment

  - **CDK CLI Version  :** 1.101.0
  - **Framework Version:** 1.101.0
  - **Node.js Version:** 15.11.0
  - **OS               :** MacOS
  - **Language (Version):** all

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hey @Kruspe ,

why would the CodeBuild role need `kms:Decrypt`? Isn't that used only for writing using the Key, while the Project will only read using it (it will read the secrets from SecretsManager)?

Thanks,
Adam

**Comment by Kruspe** [comment]
Hey @skinny85,

`kms:Decrypt` is used by SecretsManager when getting the secret. Have a look [here](https://docs.aws.amazon.com/kms/latest/developerguide/services-secrets-manager.html#asm-encrypt)

We already give that permission when the secret is added via Arn [here](https://github.com/aws/aws-cdk/blob/e31587a2d644637ba85449396c6274bcb5e1569a/packages/%40aws-cdk/aws-codebuild/lib/project.ts#L837-L842)

So it would be just a matter of adding the policy to the `kmsIamResources` Set.

**Comment by skinny85** [comment]
Ah, OK. For some reason I thought we granted `kms:Encrypt`, but yeah, that doesn't make sense 😜.

**Comment by skinny85** [comment]
If the value of the SecretsManager env variable is a Token, doesn't it mean it's referencing a Secret from the same account?

We only add the `kms:Decrypt` permissions when the Secret is from a different account.

**Comment by Kruspe** [comment]
I do not think so. The Ref can also point to a secret in another account. The policy for secrets manager already works just `kms:decrypt` is missing.
So I would say it makes sense to add the behavior also for tokens. I would like to implement the different account check and it is possible through `Token.compareString` though I am not sure how a test would look like. The secret we create would have to have a different account. I didn't check if we can create one in the test case.


Side note: Right now we add a resource for every token, meaning that tokens which are extended with `:username` but reference the same secret add the same arn to the resource. Maybe we can fix that as well ^^

**Comment by skinny85** [comment]
> I do not think so. The Ref can also point to a secret in another account.

Nope! That is not allowed in CloudFormation.

> So I would say it makes sense to add the behavior also for tokens. I would like to implement the different account check and it is possible through Token.compareString though I am not sure how a test would look like. The secret we create would have to have a different account. I didn't check if we can create one in the test case.

Gotta say, I'm not following this at all.

Maybe you can create a draft Pull Request, and show me in a unit test what is the expected behavior?

> Side note: Right now we add a resource for every token, meaning that tokens which are extended with :username but reference the same secret add the same arn to the resource. Maybe we can fix that as well ^^

Again, you lost me here. Another unit test in that draft PR?

**Comment by Kruspe** [comment]
Alright draft is ready at #14483. Sorry for the confusion. I hope this clarifies things. :)

**Comment by skinny85** [comment]
Awesome, thanks!
