### ISSUE TITLE
context:  make it possible to write to cdk.context.json from the cdk app to allow for 'determinism' of values othe than the lookups. 

### ISSUE THREAD

**Issue by mrpackethead** [aws/aws-cdk#14485]
There are situations when it is helpful to include a 'deterministic' 'lookup' of information that gets used by cdk, to provide a parameter/value to some part of the app.    These values could be things inside  or the AWS cloud.     There are some values which can be 'determined' and effectively cached, by cdk.context.json by using various lookups ( eg ec2.vpc_fromlookup ), but no built in way to do this for values that are not covered by cdk.context.json. 

### Use Case

There are multiple use-cases.   a good one, is getting the api-version of an 'outside' system, which could determine which image gets used to build a component.     A change the 'latest' api-verison coudl potentially cause a rebuild of the system. ( its very similar to what may happen with looking up the 'latest ami'.. 

### Proposed Solution

Create a method to write any value to cdk.context.json, as this is not currently not exposed.  This could be a potentional extention to node.set_context

```
 self.node.set_context(
                key=key,
                value = value,
                context_cache = True         # Add this as an option 
            )
```

My work around is to have my app write directly to cdk.context.json. This example is 'trivial', its just finding a list of AZ's in the region..  It seems to work ok.       I would have expected that 
```
from aws_cdk import(
    core as cdk,
    core
)
import boto3
import os.path
import json


def WriteCdkContext(key: str, value: str) -> None:
    
    json_file = 'cdk.context.json'

    if os.path.isfile(json_file):
        with open(json_file) as json_file:
            json_decoded = json.load(json_file)
            json_decoded[key] = value

        with open(json_file, 'w') as json_file:
            json.dump(json_decoded, json_file)

    else: 
        with open(json_file, 'w') as outfile:
            json.dump(
                {key:value},
                outfile
            )

class ContextStack(cdk.Stack):

    def __init__(self, scope: cdk.Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)
	
        key=f'availability-zones:account={self.account}:region={self.region}'
        context = self.node.try_get_context(
            key=f'availability-zones:account={self.account}:region={self.region}'
        )

        
        if context == None:
            print('There was no context - Adding it to cdk.context.json')

            # Do some lookup. Example, get the list of AvailabilityZones
            session = boto3.session.Session(profile_name='myprofile, region_name='ap-southeast-2')
            ec2 = session.client('ec2')
            response = ec2.describe_availability_zones()['AvailabilityZones']
            zones = []
            for zone in response:
                zones.append(zone['ZoneId'])
            

            # create a key/value to write to the context file.
            key = f'availability-zones:account={self.account}:region={self.region}'
            value = zones
            WriteCdkContext(key,value)
    
            # Set the context 
            self.node.set_context(
                key=key,
                value = value
            )
        
        else:
            print('There was existing context')
            zones = context
    
        print('Zones: ',zones)

        cdk.CfnOutput(self, "ListofAZ", 
            value = str(zones),
            description = 'Placeholder minium viable stack Output'
        )
 ```       

### Other
https://cdk-dev.slack.com/archives/C018XT6REKT/p1619711718066100
This is a :rocket: Feature Request

**Comment by benbridts** [comment]
This should probably be implemented as a hook on top of or into `registerContextProvider` (https://github.com/aws/aws-cdk/blob/e31587a2d644637ba85449396c6274bcb5e1569a/packages/aws-cdk/lib/context-providers/index.ts#L55)?

Writing your own ContextProviderPlugin, and building a construct around that will better integrate into existing workflows

**Comment by rix0rrr** [comment]
I'm not sure about your AvailabilityZone provider example. There is a context provider for that already which caches its results in `cdk.context.json`. Did you write this as an example, or are you purposely not using that provider?

We don't recommend the CDK app performs SDK calls. I'd recommend you write an accompanying shell script or mini-program that fetches the information you need, writes it to a JSON file, and you read that JSON file in your CDK app.

Other than that, this request seems to be covered by: https://github.com/aws/aws-cdk-rfcs/issues/18
