### ISSUE TITLE
CDK: Signed Lambda can only be deployed once

### ISSUE THREAD

**Issue by evanerwee** [aws/aws-cdk#14489]
Stack define signing profile and config successfully.

        # --------------------------------------------------------------------------------
        #
        # Setup Code Signing for Lambda
        #

        # Define code signing profile & config
        self.mssp_lambda_signing_profile_id = f'{helpers.ENTITY_PREFIX}-' \
                                              f'signing_profile_2{helpers.STAGE}'
        self.mssp_lambda_signing_profile = signer.SigningProfile(
            self,
            self.mssp_lambda_signing_profile_id,
            platform=signer.Platform.AWS_LAMBDA_SHA384_ECDSA
        )

        self.mssp_lambda_signing_config_id = f'{helpers.ENTITY_PREFIX}-' \
                                             f'signing_config_2{helpers.STAGE}'
        self.mssp_lambda_signing_config = _lambda.CodeSigningConfig(
            self,
            self.mssp_lambda_signing_config_id,
            signing_profiles=[self.mssp_lambda_signing_profile],
            untrusted_artifact_on_deployment=_lambda.UntrustedArtifactOnDeployment.ENFORCE
        )
        props['signing_config'] = self.mssp_lambda_signing_config

A lambda function successfully use the configuration.

# Defines  AWS Lambda resource
        self.mssp_hello_world_lambda_id = f'{helpers.ENTITY_PREFIX}hi_world_lambda-{helpers.STAGE}'
        self.mssp_hello_world_lambda = _lambda.Function(
            self,
            self.mssp_hello_world_lambda_id,
            role=self.mssp_lambda_role,
            tracing=_lambda.Tracing.ACTIVE,
            layers=[props['common_layer']],
            code_signing_config=props['signing_config'],
            runtime=_lambda.Runtime.PYTHON_3_8,
            code=_lambda.Code.asset('../cdk-backup/lambda/SAMPLE_Hello_World/src'),
            handler='SampleHelloWorldClass.lambda_handler',
            function_name=f'Hi_World_Sample_Lamdba{helpers.STAGE}',
            environment={
                'NAME': 'cdk-lambda-example'
            }
        )

After the stack successfully deployed once it never again can deploy with error:

(Neither the configuration or the profile changed.) 

Lambda cannot deploy the function. The function or layer might be signed using a signature that the client is not configured to accept. Check the provided signature for Hi_World_Sample_Lamdba-dev. (Service: AWSLambdaInternal; Status Code: 400; Error Code: CodeVerificationFailedException; Request ID: 8dd23354-d4ab-420a-9f16-3fbe0f8a8b1a; Proxy: null)

**Comment by nija-at** [comment]
Hi,

Can you update the code examples in your bug report above to follow SSCCE guidelines - http://sscce.org/ ?

> After the stack successfully deployed once it never again can deploy with error:

Are you unable to deploy the stack again with or without modifications or both? What did you modify to test the deployment of your example?

**Comment by evanerwee** [comment]
I have learned that I have to add props and specify a profile

**Comment by peterwoodworth** [comment]
Closing because it seems like the issue has been solved, please ping me if you'd like to reopen this 😄
