### ISSUE TITLE
CDK: Urgent: Lambda code signing - poor implementation , cannot be used with layers

### ISSUE THREAD

**Issue by evanerwee** [aws/aws-cdk#14481]
We have encountered several error with Lambda Code Signing. First of all, we have observed that intermitted we can longer deployed the lambda function. The error state the key is wrong, yet we have not touch the key and it is the exact same key the CDK deployed. We deployed the key in the main stack and lambda in a nested stack.

We have also found no method to signed layers with the CDK and therefore, once Lambda is signed layers can no longer be added.

This is a major show stopper as we have to implement sign code. Please let us know if there is plans to fix this implementation.

**Comment by peterwoodworth** [comment]
Hey @evanerwee, it would be helpful if you could post the error code you're getting. Or post any stack code you're comfortable with sharing.

In the meantime I'll research this to see what I can do

**Comment by evanerwee** [comment]
This can be closed. Apologies for not closing earlier. Adding props and specifying a profile solve the issue
