### ISSUE TITLE
(iam): Support dynamic arn parts in PolicyStatement.fromJson (like CFN PseudoParameters)

### ISSUE THREAD

**Issue by hodavidhara** [aws/aws-cdk#14482]
I would like to be able to define policy statements with resource arns that have dynamic values for things like partition, region, or account id like I can in CFN.

I would like to be able to do something like:

```javascript
const policyStatement = iam.PolicyStatement.fromJson([{
	"Effect": "Allow",
	"Action": [
		"cloudformation:DescribeStacks"
	],
	"Resource": [{
		"Fn::Sub": "arn:${AWS::Partition}:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/MyAwesomeStack/*"
	}]
}])
```

to accomplish defining a CFN stack that might look like:

```
{
	"Type": "AWS::IAM::ManagedPolicy",
	"Properties": {
		"Description": "My Awesome Managed Policy",
		"ManagedPolicyName": "MyPolicy",
		"PolicyDocument": {
			"Version": "2012-10-17",
			"Statement": [{
				"Effect": "Allow",
				"Action": [
					"cloudformation:DescribeStacks"
				],
				"Resource": [{
					"Fn::Sub": "arn:${AWS::Partition}:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/MyAwesomeStack/*"
				}]
			}]
		}
	}
}
```

### Use Case

I have many different managed policies to deploy to many different accounts in different regions and partitions and I'd like those policies to be able to work in those different partitions and regions. To make it easier for contributors who aren't familiar with CDK to add new managed policies, I have them all defined in JSON files in a folder. My CDK stack reads from those JSON files and turns them into managed policies using `PolicyStatement.fromJson`. When I tried to do something like the `Fn::Sub` above, I got an error like `Error: Fields must be either a string or an array of strings`

### Proposed Solution

No proposed solution, but see description for possible developer experience.

### Other

stack trace of error:
```
Error: Fields must be either a string or an array of strings
    at ensureArrayOrUndefined (.../node_modules/@aws-cdk/aws-iam/lib/policy-statement.ts:16:11)
    at fromJson (.../node_modules/@aws-cdk/aws-iam/lib/policy-statement.ts:35:18)
```

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
You should be able to use string interpolation with the regular Aws pseudoparameters:

```ts
const policyStatement = iam.PolicyStatement.fromJson([{
  Resource: `arn:${Aws.PARTITION}:cloudformation:${Aws.REGION}:${aws.ACCOUNT_ID}:stack/MyAwesomeStack/*`
}])
```
