### ISSUE TITLE
(docdb): Not all properties of Interface DatabaseClusterAttributes should be required

### ISSUE THREAD

**Issue by bpinhosilva** [aws/aws-cdk#14492]
`DatabaseCluster.fromDatabaseClusterAttributes(scope, id, attrs)` expects too many mandatory attributes (attrs - DatabaseClusterAttributes) to simply import a DocumentDB Cluster, which makes method's usage not friendly as it should be.

### What did you expect to happen?
Only necessary properties of DatabaseClusterAttributes should be mandatory for `fromDatabaseClusterAttributes()` usage, for example: clusterIdentifier.

### What actually happened?
There is no simple way to create a reference of DocumentDB inside CDK App using `DatabaseCluster.fromDatabaseClusterAttributes()` unless **all** properties are passed, which makes it cumbersome and not practical. Besides, the interface accepts `securityGroup` but the L1 construct CfnDBCluster accepts an array - of vpcSecurityGroupIds.

A similar issue was reported and fixed for **rds** (see reference below). Perhaps, the same fix could fit docdb lib as well.

### Environment

  - **CDK CLI Version  :** 1.100.0
  - **Framework Version:** 1.100.0
  - **Node.js Version:** v.14.16.1
  - **OS               :** win 10 (64 bits)
  - **Language (Version):** TypeScript (3.8.3)

### Other
Related issue: https://github.com/aws/aws-cdk/issues/3587 

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment]
@bpinhosilva Thanks for reporting this. Definitely agree its too strict as of now. 

I am unassigning and marking this issue as `p2`, which means that we are unable to work on this immediately.

We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://join.slack.com/t/cdk-dev/shared_invite/zt-mso6p56d-qJp7SOTBvMaQuDrx7R2wHg) to solicit support for reprioritization.

**Comment by Synohara** [comment]
We fixed this issue!
