### ISSUE TITLE
@aws-cdk/pipelines. CdkPipeline: Enable multiple sources

### ISSUE THREAD

**Issue by brimock** [aws/aws-cdk#14493]
Currently we can only specify a single source repository for a CdkPipeline, however it would be cleaner to enable us to store different parts of our application in different repositories.

### Use Case

I have infrastructure and application code in different repos, and would like to have them deployed within the same pipeline.

### Proposed Solution

Change sourceAction to be an array of source actions, i.e. sourceActions

This is a :rocket: Feature Request

**Comment by bodokaiser** [comment]
Related https://github.com/aws/aws-cdk/issues/14490

**Comment by rix0rrr** [comment]
Will be addressed by #12326, closing as duplicate.

**Comment by robert-hanuschke** [comment]
@rix0rrr #12326 is merged now but I think it does not include multiple sources (at least I don't see it in the documentation and couldn't configure it in v1.125.0). Should this be reopened?

**Comment by bodokaiser** [comment]
@robert-hanuschke You find `additionalInputs` in [`ShellStepProps`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_pipelines.ShellStepProps.html). 

This is also explained in the [additional inputs section](https://docs.aws.amazon.com/cdk/api/latest/docs/pipelines-readme.html#synth-and-sources):

```typescript
const prebuild = new ShellStep('Prebuild', {
  input: CodePipelineSource.gitHub('myorg/repo1'),
  primaryOutputDirectory: './build',
  commands: ['./build.sh'],
});

const pipeline = new CodePipeline(this, 'Pipeline', {
  synth: new ShellStep('Synth', {
    input: CodePipelineSource.gitHub('myorg/repo2'),
    additionalInputs: {
      'subdir': CodePipelineSource.gitHub('myorg/repo3'),
      '../siblingdir': prebuild,
    },

    commands: ['./build.sh'],
  })
});
```

and yes, I agree that such a great feature deserves more visibility.

**Comment by robert-hanuschke** [comment]
@bodokaiser ah, so the additional inputs defined in that way also trigger the pipeline (e.g. if nothing changed in myorg/repo1 but in myorg/repo3)? I interpreted that section in the way that the trigger still would only be morg/repo1 but once that fires it additionally loads repo2 and repo3 for supplementary data in support of repo1's changes.

If I thought wrong there and changes to repo2 and repo3 also fire the pipeline - very cool, will try that!

**Comment by bodokaiser** [comment]
@robert-hanuschke I think so, in the [`ShellStep` constructor](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/pipelines/lib/blueprint/shell-step.ts#L155-L174) they get the same treatment.
