### ISSUE TITLE
(@aws-cdk/pipelines): allow multiple source actions

### ISSUE THREAD

**Issue by bodokaiser** [aws/aws-cdk#14490]
Typically, we set up a `CdkPipeline` as

```typescript
const pipeline = new CdkPipeline(this, 'Pipeline', {
      cloudAssemblyArtifact,
      sourceAction: new GitHubSourceAction({
        actionName: 'GitHub',
        output: sourceArtifact,
        oauthToken: SecretValue.secretsManager('GitHubToken'),
        owner: 'foobar',
        repo: 'cdk',
        branch: 'main',
      }),
      synthAction: SimpleSynthAction.standardYarnSynth({
        sourceArtifact,
        cloudAssemblyArtifact,
        buildCommand: 'yarn run build',
      }),
})
```

where there is a single `sourceAction` pulling the (aws-cdk) source code.

The blog article [CDK Pipelines: Continuous delivery for AWS CDK applications](https://aws.amazon.com/blogs/developer/cdk-pipelines-continuous-delivery-for-aws-cdk-applications/) as well as [aws-cdk-rfc 0049](https://github.com/aws/aws-cdk-rfcs/blob/master/text/0049-continuous-delivery.md#publishing-1) suggest that the application modules should be built inside the `CdkPipeline` and published as assets which in turn are referenced in the (cross-account) stack deployments.

### Use Case

Having a multi-repo setup, for instance, `foobar/cdk` for the cdk code and `foobar/lambda` or `foobar/web` for a Lambda and web frontend is not possible with a single `sourceAction`.

If one uses `go` for the Lambda one requires a custom `Pipeline`, same is true for recent web apps.

### Proposed Solution

Changing `sourceAction` to `sourceActions` allowing an array of `sourceAction`, e.g.,

```typescript
const pipeline = new CdkPipeline(this, 'Pipeline', {
      cloudAssemblyArtifact,
      sourceActions: [
        new GitHubSourceAction({
          actionName: 'GitHub',
          output: sourceArtifact,
          oauthToken: SecretValue.secretsManager('GitHubToken'),
          owner: 'foobar',
          repo: 'cdk',
          branch: 'main',
        }),
        new GitHubSourceAction({
          actionName: 'GitHub',
          output: sourceArtifact,
          oauthToken: SecretValue.secretsManager('GitHubToken'),
          owner: 'foobar',
          repo: 'web',
          branch: 'main',
        }),
        new GitHubSourceAction({
          actionName: 'GitHub',
          output: sourceArtifact,
          oauthToken: SecretValue.secretsManager('GitHubToken'),
          owner: 'foobar',
          repo: 'lambda-in-go',
          branch: 'main',
        }),
        // ...
      ],
      synthAction: SimpleSynthAction.standardYarnSynth({
        sourceArtifact,
        cloudAssemblyArtifact,
        buildCommand: 'yarn run build',
      }),
})
```

we could then use
```typescript
const buildStage = pipeline.addStage('Build')
buildStage.addActions(new CodeBuildAction({
  actionName: 'Web',
  input: sourceArtifact,
  outputs: [cloudAssemblyArtifact],
});)
```

I am not sure how to reference the build results inside `cloudAssemblyArtifact` using `Asset.from(..)` or the like, for example, when defining the lambda `Function` in the cdk code but I guess this is already somewhat inside the cdk `assets.json`.

Alternatively, one could define a `CodePipelineStack` which is deployed with each `ApplicationStage`. However, this would contradict the idea of building all assets in a central pipeline.

* [ ] :wave: I may be able to implement this feature request
* [x] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by yattoni** [comment]
Related #10872
