### ISSUE TITLE
How do we protect against breaking changes in construct libraries?

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#145]
@ccfife wrote:

Users expressed a concern that CDK constructs, that are routinely updated to fix issues and add functionality, will not be deterministic. i.e. A developer updates the construct libraries on their machine via a package manager. These constructs contain changes to IAM policy that is not obvious from just inspecting the repo. They then push changes to a stack that results in unexpected security permission changes.

The `cdk diff` command can help identify unexpected modifications to infrastructure, but that seems like half the story.  Is tight versioning of CDK constructs the other part of the story; so that CDK stacks are more deterministic?

**Comment by rix0rrr** [comment]
Plan of attack:

- [x] Parse stability annotations from docs
- [ ] Expose stability annotations through jsii-reflect
- [ ] Write jsii tool to compare two assemblies for compatibility (jsii-compat?)
- [ ] Update awslint to require people to write docs and add stability annotations to all constructs
- [ ] Reflect stability in docs
- [ ] Use jsii-compat in bump script

**Comment by eladb** [comment]
My thought for a name for this tool was `jsii-diff`, that can be used to generally compare two APIs, but can also work in a "superset/subset" mode.

I am thinking that perhaps we should run this as an integration test in the pipeline and not during bump. It would cause the pipeline to stop and then people would need to fix the error and commit a fix to revert any breaking changes.

**Comment by rix0rrr** [comment]
You're right, when we're in post-1.0 we should be finding incompatibilities as early on as possible.

The big question will be: where are we going to get the previous release's .jsii file?

Check it in? Download from GitHub?

**Comment by eladb** [comment]
I've been contemplating on this. I think download from npm because that's that's the authoritative last published version by definition, no?

**Comment by rix0rrr** [comment]
Yes. It's just not so nice to do a download from NPM for every  build.

But I guess we can make it an option.

**Comment by eladb** [comment]
That's why I felt it should be an integration test. Also, it should be possible to just download the tar.gz file from npm without actually installing all the dependencies.

**Comment by rix0rrr** [comment]
That's not working because `jsii-reflect` borks if it can't find a package's dependencies.

**Comment by skinny85** [comment]
Is this done? :)

**Comment by eladb** [comment]
Yes
