### ISSUE TITLE
(@aws-cdk/aws-apigatewayv2): Incorrect metric names for 4xx and 5xx

### ISSUE THREAD

**Issue by kjpgit** [aws/aws-cdk#14503]
My code:

      add_http_api_alarm(api: apigw.HttpApi, alarm_name: string) {
        const metric = new cloudwatch.MathExpression({
          expression: "IF(invocations > 100, (client_errors + server_errors) * 100, 0) / invocations",
          period: cdk.Duration.hours(1),
          usingMetrics: {
            client_errors: api.metricClientError({statistic:"sum"}),
            server_errors: api.metricServerError({statistic:"sum"}),
            invocations: api.metricCount({statistic: "sum"})
          }
        });
       
No data is being shown for metricClientError or metricServerError.  That is because the CDK is incorrectly calling it `4XXError`  instead of `4xx` required by HTTP APIs https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-metrics.html

cdk version 1.100.0 (build d996c6d)

**Comment by kjpgit** [comment]
This code is a workaround:

    function fix_error_metric(metric: cloudwatch.Metric) : cloudwatch.Metric {
      return new cloudwatch.Metric({
        metricName: metric.metricName.replace("XXError", "xx"),  // note capitalization change
        namespace: metric.namespace,
        period: metric.period,
        statistic: metric.statistic,
        color: metric.color,
        account: metric.account,
        dimensions: metric.dimensions,
        label: metric.label,
        region: metric.region,
        unit: metric.unit,
      })
    }
    
     const metric = new cloudwatch.MathExpression({
        expression: "IF(invocations > 100, (client_errors + server_errors) * 100, 0) / invocations",
        period: cdk.Duration.hours(1),
        usingMetrics: {
          client_errors: fix_error_metric(api.metricClientError({statistic:"sum"})),
          server_errors: fix_error_metric(api.metricServerError({statistic:"sum"})),
          invocations: api.metricCount({statistic: "sum"})
        }
      });

**Comment by nija-at** [comment]
Hi @kjpgit - Thanks for reporting this issue. I've prepared a fix for this #14541
