### ISSUE TITLE
(elasticsearch): support V7_10

### ISSUE THREAD

**Issue by prashanttct07** [aws/aws-cdk#14502]
AWS supports the creation of ES domains with version 7.10 CDK only supports 7.9,
aws_elasticsearch.ElasticsearchVersion.V7_9 is max we can get as of Today (CDK 1.101)

Probably by simply adding enumerator ElasticsearchVersion.V7_10 to the aws_elasticsearch module, people would be able to get the benefits of the newer ES version.

### Use Case
To support Amazon ES version in one of the AWS sample [amazon-elasticsearch-service-monitor](https://github.com/aws-samples/amazon-elasticsearch-service-monitor) 

### Proposed Solution

add enum V7_10

* [May not be] :wave: I may be able to implement this feature request
* [Not Sure] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by iliapolo** [comment]
As a workaround, one can use:

```ts
new es.Domain(this, 'Domain', {
  version: es.ElasticsearchVersion.of('7.10'),
});
```

**Comment by prashanttct07** [comment]
Thanks @iliapolo. 
Workaround seems to work fine. Do you want me to close this request or should I keep it open as it's still good to update the CDK code too.

**Comment by iliapolo** [comment]
We can keep it open.
