### ISSUE TITLE
Requested attribute Endpoint.Address does not exist in schema for AWS::Redshift::Cluster

### ISSUE THREAD

**Issue by mydarpa** [aws/aws-cdk#14524]
### The Question

I deployed a Redshift cluster and I would like to export the hostname of the endpoint like this:

```
cluster = redshift.Cluster(
            self, "redshift-cluster",
            vpc=vpc,
            cluster_name="mycluster",
            cluster_type=redshift.ClusterType.MULTI_NODE,
            number_of_nodes=4,
            logging_bucket=cluster_logging_bucket,
            security_groups=[cluster_security_group],
            master_user=redshift.Login(
                master_username="master",
            ),
            roles=[access_role],
            port=5439,
            node_type=redshift.NodeType.DC2_LARGE,
            publicly_accessible=True,
            subnet_group=redshift.ClusterSubnetGroup(
                self, 'subnet-group',
                vpc=vpc,
                vpc_subnets=ec2.SubnetSelection(subnet_type=ec2.SubnetType.PUBLIC),
                description="public subnet")
        )

core.CfnOutput(
            self, "cluster-hostname",
            value=cluster.cluster_endpoint.hostname,
            export_name="cluster-hostname"
        )
```

However I get the error:

`Requested attribute Endpoint.Address does not exist in schema for AWS::Redshift::Cluster`

The same stack was deployed some days ago in another account without problems. According to the documentation this property is valid for the class Endpoint [1] and the Endpoint.Address attribute still exists in CloudFormation [2].

[1] https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-redshift.Endpoint.html
[2] https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-redshift-cluster.html#aws-resource-redshift-cluster-return-values

### Environment

  - **CDK CLI Version:**  1.72.0
  - **Module Version:**  aws-cdk.aws-redshift==1.72.0
  - **Node.js Version:** 
  - **OS:**  
  - **Language:**  Python

### Other information

This issue is only for Endpoint exports. I don't get any problems with other exports like:

```
core.CfnOutput(
            self, "password-arn",
            value=cluster.secret.secret_arn,
            export_name="password-arn"
        )
```

**Comment by NGL321** [comment]
Hey @mydarpa,

Thanks for reporting this. I am unsure as to why it was not marked as a bug report, but I have adjusted it. Someone will take a look into this as soon as we are able.

**Comment by kayzbui** [comment]
I encountered a similar issue when attempting to create a Redshift Cluster and establish an SSM reference to `Cluster.Endpoint.Address`. To resolve this, I divided the deployment into two stages. Initially, I created the Redshift Cluster, followed by a separate deployment for setting up the SSM reference.
