### ISSUE TITLE
(aws-ecs): addPortMappings for ContainerDefinition needs PortMapping not PortMapping[]

### ISSUE THREAD

**Issue by chrisbirster** [aws/aws-cdk#14523]
Documentation on an ECS ContainerDefiniation to create a Container.
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs.ContainerDefinition.html
Port Mapping definition: https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs.ContainerDefinition.html#portmappings

Hello, I think the documentation might be misleading. It says you can add a PortMapping array to the Container Definition but I am only able to add one PortMapping object at a time in the code below.
```
const apiContainer = apiTask.addContainer("apiContainer", {
  image: ecs.ContainerImage.fromRegistry("api:1.0"),
  logging: new ecs.AwsLogDriver({
    streamPrefix: "api",
    logGroup: fargateLogGroup,
  }),
  environment: {
    USER: "username",
    PROXY_ADDRESS_FORWARDING: "true",
});

const portMappings: ecs.PortMapping[] = [
  { containerPort: 8080, hostPort: 8080 },
  { containerPort: 8443, hostPort: 8443 },
];
apiContainer.addPortMappings(portMappings);
```

I am getting the error below:
```
[tsserver 2345] [E] Argument of type 'PortMapping[]' is not assignable to
parameter of type 'PortMapping'.
  Property 'containerPort' is missing in type 'PortMapping[]' but required in
type 'PortMapping'.
```

Instead I have to do this:
```
apiContainer.addPortMappings({ containerPort: 8080, hostPort: 8080 });
apiContainer.addPortMappings({ containerPort: 8443, hostPort: 8443 });
```

---

This is a 📕 documentation issue

**Comment by SoManyHs** [comment]
Hi @chrisbirster,

I believe in this case it's a syntax issue -- the method signature for `addParameters` is `...PortMappings[]` as a [rest parameter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/rest_parameters). If you change your last line to:

```
apiContainer.addPortMappings(...portMappings);
```

Your code should work. Hope that helps!
