### ISSUE TITLE
(ec2): Feedback about importing security groups

### ISSUE THREAD

**Issue by kjpgit** [aws/aws-cdk#14535]
This code takes a list of security group ids, and does some "pipe fitting" to assign it to a Lambda Function, which needs a list of ISecurityGroup:

     // props.security_group_ids is a string[], which contains pre-existing / legacy security group ids to use
     let secgroups: ec2.ISecurityGroup[] = []
      props.security_group_ids.forEach(secgroup_id => {

        secgroups.push(ec2.SecurityGroup.fromSecurityGroupId(this, "secgroup", secgroup_id, {   
          mutable: false  
        }))
      })
      
1) Is having the constant name "secgroup" a problem?  Do I need to give it a unique name for each iteration of the loop?  This is a bit of a hassle just to import a list of security groups.  In general, I don't understand the need for giving a resource name to imported things, since cloudformation isn't creating anything.

2) Why are imported security groups mutable by default?  That shocked me.  That's not how other things work, such as imported IAM Roles or Groups.  Those can't be modified, last I checked.

**Comment by kirintwn** [comment]
For the `id` thing, you can check out [the docs about `Identifiers`](https://docs.aws.amazon.com/cdk/latest/guide/identifiers.html).
As for the the example you gave, you can use index as part of the id to make it unique:
```typescript
const securityGroups = props.security_group_ids.map((id, index) =>
  ec2.SecurityGroup.fromSecurityGroupId(this, `SecurityGroup${index}`, id, { mutable: false }),
);
```

**Comment by peterwoodworth** [comment]
Hey @kjpgit,

kirintwn provided a full answer to your first question. (thank you @kirintwn!) The docs page linked discusses the importance of `identifiers`. 

As for why imported security groups are mutable by default, [this page explains it](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ec2.SecurityGroupImportOptions.html#mutable). 

> If a SecurityGroup is mutable CDK can add rules to existing groups.
> Beware that making a SecurityGroup immutable might lead to issue due to missing ingress/egress rules for new resources.

Hope this helps!
