### ISSUE TITLE
Strings composed unpredictably

### ISSUE THREAD

**Issue by benwainwright** [aws/aws-cdk#14547]
### The Question

Hi there!

I use the CDK at work, and we try our hardest to write as many tests as we can for it. For this, we tend to make use of the cdk-assert library. One of the problems we have when writing tests for the CDK is the way that the framework will tend to break down certain strings when generating things like ARNs and compose them together using CloudFormation primitives in unpredictable ways. For example: 

The CDK code `iam.ManagedPolicy.fromAwsManagedPolicyName('AWSSupportAccess')` results in the following CloudFormation:

```
{
  "Fn::Join": [
    "",
    [
      "arn:",
      {
        "Ref": "AWS::Partition"
      },
      ":iam::aws:policy/AWSSupportAccess"
    ]
  ]
}
```

While this probably the right thing to do, it makes things very difficult to test.

Now I _could_ write a test that looks for this exact construction, but it feels very much like if I do that, I'm testing the internal implementation of the framework. The CDK could easily change the way this string is constructed in the future and my test would break.

What I'd *like* to be able to do is resolve the whole thing to a string, and then look for complete strings that end with `aws:policy/AWSSupportAccess`, however I suspect that that kind of resolution is not possible to do without actually deploying the template.

I feel like I'm not going to be the only person to ever have encountered this problem, so I'm curious to know how people write these kind of tests.

**Comment by skinny85** [comment]
Hey @benwainwright ,

thanks for opening the issue. Out of curiosity, why are you worried about doing assertions against

```
{
  "Fn::Join": ["", [
    "arn:",
    {
      "Ref": "AWS::Partition"
    },
    ":iam::aws:policy/AWSSupportAccess"
  ]]
}
```

?

**Comment by benwainwright** [comment]
@skinny85 I'm a little confused. Did I not explain that in my original post?

> Now I could write a test that looks for this exact construction, but it feels very much like if I do that, I'm testing the internal implementation of the framework. The CDK could easily change the way this string is constructed in the future and my test would break.

Or a further reason; I could change the implementation of my code to something that causes an output that is *functionally identical*, but produces a different output. E.g. in one instance we previously used

```
iam.ManagedPolicy.fromManagedPolicyArn(
  this,
 `OurSystemAdministrator`,
 'arn:aws:iam::aws:policy/job-function/SystemAdministrator'
),
```

before we realised that we could simply replace it with `iam.ManagedPolicy.fromAwsManagedPolicyName('job-function/SystemAdministrator')`. Now the former produces a complete ARN without any decomposition. The latter produces CF that is more like the example given in the original issue; yet they are _functionally_ identical. I'd have to rewrite my tests to handle this change.

**Comment by skinny85** [comment]
OK. There are a few interesting things happening here 🙂.

First of all, `{ "Fn::Join": ["", ["arn:", { "Ref": "AWS::Partition" }, ":iam::aws:policy/AWSSupportAccess"  ]]}` and `"arn:aws:iam::aws:policy/job-function/SystemAdministrator"` are _not_ equivalent. Try deploying the latter in `cn-north-1`, and you'll see what I mean 🙂.

Secondly, I think it all depends on what you exactly want to test for.

If I'm a vendor a CDK library, I want to minimize any diff I cause in the templates of my consumers. So, I would actually want to have a test that confirms I generate exactly ``{ "Fn::Join": ["", ["arn:", { "Ref": ...`` - I want to be notified when something changes in my resources that might affect my users.

If you're authoring a CDK application - not a library that might be re-used - then I think what you want to assert in your tests is that you're using the `:iam::aws:policy/job-function/SystemAdministrator` policy. For those cases, you can call the [`Stack.resolve()` method](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.Stack.html#resolveobj) inside your tests. Here's an example using that method in a test from the CDK codebase: https://github.com/aws/aws-cdk/blob/46a16312825cc7b5bf985bc8b69146a1397690d0/packages/%40aws-cdk/cloudformation-include/test/yaml-templates.test.ts#L423-L441

Hope this helps!

Thanks,
Adam
