### ISSUE TITLE
(cli): v2 CLI needs some way to initialize v1 projects

### ISSUE THREAD

**Issue by Jerry-AWS** [aws/aws-cdk#14549]
Since the v2 CLI is backward-compatible, it can be used to synth and deploy v1 stacks. But when initializing a new project, it always creates v2-style projects that assume the new monolithic library structure. 

Since v2 is currently in developer preview, this means customers who are trying out v2 will need to roll back to the latest v1 CLI when creating new production projects (or else initialize their projects some other way).

### Proposed Solution

Include the v1 app templates with the v2 CLI. Name them `v1app` and so on. Add this information to the v2 migration topic.

* [X] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by madeline-k** [comment]
Closing, since we are not going to implement this. For anyone needing to create a v1 app, you can run 

`npx cdk@1 init app --language=<lang>`
