### ISSUE TITLE
ssm/codepipeline-actions: StringParameter.valueForStringParameter issue when used to fill a lambda invoke pipeline step after upgrading from 1.100.0 > 1.102.0

### ISSUE THREAD

**Issue by jvlch** [aws/aws-cdk#14548]
-----------------------------------------------------------------------------------------------------
Old (1.100.0 : Working) compiled template.json referenced a cloudformation template parameter:
-----------------------------------------------------------------------------------------------------
```
"Parameters": {
    "GetDemandsLambdaImportParameter": {
      "Type": "AWS::SSM::Parameter::Value<String>",
      "Default": "GetDemandsLambdaArn"
    },
}

"Fn::Select": [
                      6,
                      {
                        "Fn::Split": [
                          ":",
                          {
                            "Ref": "GetDemandsLambdaImportParameter"
                          }
                        ]
                      }
                    ]
```
-----------------------------------------------------------------------------------------------------
New(1.102.0 : Broken) compiled template.json changed this to
-----------------------------------------------------------------------------------------------------
```
"Fn::Select": [
                      6,
                      {
                        "Fn::Split": [
                          ":",
                          "{{resolve:ssm:GetDemandsLambdaArn}}"
                        ]
                      }
                    ]
```
-----------------------------------------------------------------------------------------------------

Now getting this error in the self-mutation step of the cdk-pipeline

infrapipeline-develop failed: Error [ValidationError]: Template error: Fn::Select  cannot select nonexistent value at index 6

-----------------------------------------------------------------------------------------------------
### Reproduction Steps
-----------------------------------------------------------------------------------------------------
```
    import codepipeline_actions = require('@aws-cdk/aws-codepipeline-actions');
    import lambda = require('@aws-cdk/aws-lambda');
    import ssm = require('@aws-cdk/aws-ssm');

    const getDemandsLambdaArn = ssm.StringParameter.valueForStringParameter(this, 'GetDemandsLambdaArn')

    const action = new codepipeline_actions.LambdaInvokeAction({
      actionName: 'GetDemands',
      lambda: lambda.Function.fromFunctionArn(this, 'GetDemandsLambda', getDemandsLambdaArn),
      runOrder: 1,
    });
```
    
-----------------------------------------------------------------------------------------------------
### What did you expect to happen?
-----------------------------------------------------------------------------------------------------
Lambda arn would be correctly referenced in the compiled cfn template

-----------------------------------------------------------------------------------------------------
### What actually happened?
-----------------------------------------------------------------------------------------------------
Validation error in self-mutate step of cdk pipeline

-----------------------------------------------------------------------------------------------------
### Environment
-----------------------------------------------------------------------------------------------------

  - **CDK CLI Version  :*npx cdk --version = 1.88.0*
  - **Framework Version:*1.102.0*
  - **Node.js Version:** v12.18.2
  - **OS               :*macOS Big Sur 11.2.3*
  - **Language (Version):** TypeScript (4.1.2) -->
 
-----------------------------------------------------------------------------------------------------
### Workaround
-----------------------------------------------------------------------------------------------------

After clearing the initial issue with this workaround, there were a lot more downstream stacks that are encountering the same problem and would require much more refactoring. Going to roll back to 1.100.0 to avoid this issue, 1.101.0 also has this issue.

```
    const getDemandsLambdaArnParameter = new cdk.CfnParameter(this, 'GetDemandsLambdaArnParameter', {
      type: "AWS::SSM::Parameter::Value<String>",
      default: 'GetDemandsLambdaArn'
    })

    const getDemandsAction = new codepipeline_actions.LambdaInvokeAction({
      actionName: 'GetDemands',
      lambda: lambda.Function.fromFunctionArn(this, 'GetDemandsLambda', getDemandsLambdaArnParameter.valueAsString), 
      runOrder: 1,
    });

```

This is :bug: Bug Report

**Comment by jogold** [comment]
This behavior has been reverted in #14527 and will be released with the next version.

**Comment by jvlch** [comment]
awesome, thank you!
