### ISSUE TITLE
(stepfunctions-tasks): EcsRunTask does not have PropagateTags parameter

### ISSUE THREAD

**Issue by metgrahamr** [aws/aws-cdk#14553]
The stepfunction service integration with ecs has the option of propagating tags to a task based on those applied to the task definition - [docs](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_RunTask.html#ECS-RunTask-request-propagateTags). This option doesn't appear to be available when using EcsRunTask.

### Use Case

Tagging individual tasks will allow better allocation of costs to internal projects.

### Proposed Solution

Add the PropagateTags parameter as an option to EcsRunTask.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by BenChaimberg** [comment]
Workaround:
```
class ModifiedEcsRunTask extends sfntasks.EcsRunTask {
  constructor(scope: Construct, id: string, props: sfntasks.EcsRunTaskProps) {
    super(scope, id, props);
  }

  protected _renderTask(): any {
    const orig = super._renderTask()
    const ret = {};
    Object.assign(ret, orig, { Parameters: { PropagateTags: 'TASK_DEFINITION', ...orig.Parameters } });
    return ret;
  }
}
```

**Comment by BenChaimberg** [comment]
I am unassigning myself and marking this issue as `p2`, which means that we are unable to work on this immediately.

We use +1s to help prioritize our work, and are happy to reevaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://join.slack.com/t/cdk-dev/shared_invite/zt-mso6p56d-qJp7SOTBvMaQuDrx7R2wHg) to solicit support for reprioritization. Please feel free to work on this issue yourself and request my review if you submit a PR or would like design help! See [CONTRIBUTING.md](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) for guidelines.

**Comment by metgrahamr** [comment]
Thanks for looking at this and also suggesting a workaround. I'm not familiar with TypeScript and jsii. Can I try a similar workaround with the Python source code directly or do I need to make the changes as above and somehow automatically generate the Python?

Another workaround that I have used elsewhere is to use the L2 construct to generate state JSON, add the required parameters and then create a custom state from the JSON. Unfortunately, in this case, I need to add things such as retries to the EcsRunTask object which aren't available to a custom state object.

**Comment by BenChaimberg** [comment]
Not a Python expert, but here's the equivalent
```py
class ModifiedEcsRunTask(sfntasks.EcsRunTask):
  def to_state_json(self):
    orig = super().to_state_json()
    ret = copy(orig)
    ret['Parameters']['PropagateTags'] = 'TASK_DEFINITION'
    return ret
```

**Comment by metgrahamr** [comment]
Awesome, thank you. I will give that a try.
