### ISSUE TITLE
(eks): Warnings about insecure `kubeconfig` file when running helm

### ISSUE THREAD

**Issue by iliapolo** [aws/aws-cdk#14560]
When installing helm charts, we started seeing these warning pop up in the lambda handler log:

```console
[INFO]	2021-05-05T10:25:13.417Z	a5811ffd-8493-4ea7-b3ed-eaabebc456e6	b'WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /tmp/kubeconfig\nWARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /tmp/kubeconfig
```

There doesn't seem to be any apparent disruption caused by this, but it probably still requires some investigation.  

### Reproduction Steps

Install any helm chart and inspect the lambda handler logs. 

### What did you expect to happen?

No warnings.

### What actually happened?

Warnings about an insecure `kubeconfig` file.

### Environment

  - **CDK CLI Version  :ALL**
  - **Framework Version: 1.102.0**
  - **Node.js Version: ALL** 
  - **OS               : ALL**
  - **Language (Version): ALL** 

### Other

Originally reported in https://github.com/aws/aws-cdk/issues/14416

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment]
I am unassigning and marking this issue as `p2`, which means that we are unable to work on this immediately.

We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://join.slack.com/t/cdk-dev/shared_invite/zt-mso6p56d-qJp7SOTBvMaQuDrx7R2wHg) to solicit support for reprioritization.

**Comment by markus7811** [comment]
This makes debugging of helm failures more complicated, because this error is also returned by cloudformation (you have to know that this is not the error causing the fail of resource update/creation, but format is not good in cf webconsole).
 Shouldn't an chmod og-r kubeconfig fix everything?

**Comment by iliapolo** [comment]
@markus7811 

> Shouldn't an chmod og-r kubeconfig fix everything?

Probably. You want to take a stab at it? If it is that simple we should probably be able to merge it quickly.

**Comment by mrsiejas** [comment]
I really think this should be looked into, post EKS update 1.19 to 1.20 seeing this regularly and it is causing helm charts to fail.
