### ISSUE TITLE
(aws-batch): jobDefinitionName of JobDefinition and jobQueueName of JobQueue don't return their name

### ISSUE THREAD

**Issue by jakemraz** [aws/aws-cdk#14563]
jobDefinitionName of JobDefinition and jobQueueName of JobQueue don't return their name, but they return their arn

### Reproduction Steps

```typescript
const jobDef = new batch.JobDefinition(this, 'JobDefinition', { ... });
const jobDefName = jobDef.jobDefinitionName; // it contains ARN of jobDefinition, not Name

const jobQueue = new batch.JobQueue(this, 'jobQueue', { ... });
const jobQueueName = jobQueue.jobQueueName; // it contains ARN of jobQueue, not Name
```

### What did you expect to happen?

it returns job queue name and job definition name

### What actually happened?

it returns job queue arn and job definition arn

### Environment

  - **CDK CLI Version  :** 1.02
  - **Framework Version:** 1.02
  - **Node.js Version:**  v14.15.1
  - **OS               :** mac 10.15.7
  - **Language (Version):** typescript 3.9.0

### Other

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment]
@jakemraz Thanks for reporting this. 

I am unassigning and marking this issue as `p2`, which means that we are unable to work on this immediately.

We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://join.slack.com/t/cdk-dev/shared_invite/zt-mso6p56d-qJp7SOTBvMaQuDrx7R2wHg) to solicit support for reprioritization.

As a workaround, you can extract the name from the ARN like so:

```ts
const jobQueueName = cdk.Fn.select(1, cdk.Fn.split('job-queue/', jobQueue.jobQueueArn));
const jobDefinitionName = cdk.Fn.select(1, cdk.Fn.split('job-definition/', jobDefinition.jobDefinitionArn));
```
