### ISSUE TITLE
(aws-lambda-event-sources): batching window support doesn't include SendMessageBatch permissions

### ISSUE THREAD

**Issue by 0xjjoyy** [aws/aws-cdk#14569]
The batching window support doesn't grant SendMessageBatch permissions.

Batching window support added here
https://github.com/aws/aws-cdk/issues/11722

The following permissions are added
```


    sqs:SendMessage

    sqs:GetQueueAttributes

    sqs:GetQueueUrl
```

### Reproduction Steps

        self.event_rule.add_target(event_targets.SqsQueue(queue))

### What did you expect to happen?

messages to be sent as batch with batch permission included

### What actually happened?

no batch permission included

### Environment

  - **CDK CLI Version  :**
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):** 

### Other

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
@0xjjoyy - can you describe what you are unable to do or is not working when this permission is missing?

**Comment by 0xjjoyy** [comment]
@nija-at I'm not seeing multiple records coming through (batching) when I'm testing.

Code below

```
        queue = sqs.Queue(
            self,
            "queue",
            visibility_timeout=core.Duration.seconds(300),
        )

        batch_lambda.add_event_source(
            aws_lambda_event_sources.SqsEventSource(
                queue=queue,
                batch_size=100,
                max_batching_window=core.Duration.seconds(10),
                enabled=True,
            )
        )
```

**Comment by nija-at** [comment]
Adding an SQS event source to a lambda lets the lambda function consume messages from an SQS queue, not send messages to an SQS queue.

Can you update the original report with a full example (as described here - http://sscce.org/)?
Could you also provide the CloudFormation template or snippet where you see the `sqs:SendMessage` permissions and expect to see `sqs:SendMessageBatch`?
