### ISSUE TITLE
(rds): wrongly synths DBClusterIdentifier on AWS::RDS::DBCluster

### ISSUE THREAD

**Issue by GreggGut** [aws/aws-cdk#14561]
When my application is synth-ed using CDK-Pipeline the AWS::RDS::DBCluster identifier (DBClusterIdentifier) is lowercased causing a diff detection which in turn starts a re-creation of the DB Cluster but fails since the cluster name already exists.

This is the output of synth ran manually:

```
"PPXDatabaseClusterABC": {
      "Type": "AWS::RDS::DBCluster",
      "Properties": {
        "Engine": "aurora-mysql",
        "DatabaseName": "ppx",
        "DBClusterIdentifier": "PPX-Cluster",
        "DBClusterParameterGroupName": "default.aurora-mysql5.7",
        "DBSubnetGroupName": {
          "Ref": "PPXDatabaseClusterSubnetsXYZ"
        },
}....
```

Here is the synth ran using cdk-pipeline:

```
"PPXDatabaseClusterABC": {
      "Type": "AWS::RDS::DBCluster",
      "Properties": {
        "Engine": "aurora-mysql",
        "DatabaseName": "ppx",
        "DBClusterIdentifier": "ppx-cluster",
        "DBClusterParameterGroupName": "default.aurora-mysql5.7",
        "DBSubnetGroupName": {
          "Ref": "PPXDatabaseClusterSubnetsXYZ"
        },
}....
```

Note the casing difference between the 2:
"DBClusterIdentifier": "PPX-Cluster" VS "DBClusterIdentifier": "ppx-cluster"

If we name the DBCluster with all lowercase then there is no diff detected and all is deployed fine using local cdk and cdk-pipeline

Sample stack code:

```
const source = new codepipeline_actions.CodeStarConnectionsSourceAction({...});
const cdkOutput = new codepipeline.Artifact("CdkOutput");

const synthAction = SimpleSynthAction.standardNpmSynth({
	actionName: 'SynthPPX',
	sourceArtifact: new codepipeline.Artifact(),
	cloudAssemblyArtifact: cdkOutput,
	environment: {
		buildImage: LinuxBuildImage.AMAZON_LINUX_2_3,
		privileged: true
	},
	subdirectory: 'cdk',
	buildCommand: 'npm run build'
});

var pipeLine = new CdkPipeline(this, 'Pipeline', {
	pipelineName: 'The_pipe',
	cloudAssemblyArtifact: cdkOutput,
	sourceAction: source,
	cdkCliVersion: '1.101.0',
	crossAccountKeys: false,
	synthAction: synthAction
});

const deploy = new ApplicationStage(this, 'ApplicationStage', props);
```

It is the synth of the `ApplicationStage` that results in the wrong casing of the DBClusterIdentifier 

### Environment

  - **CDK CLI Version  :** 1.101.0

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
This is not pipelines-specific, it's an RDS behavior. Should be controlled by a feature flag, but afaik the flag shouldn't automatically be flipped for you. @skinny85 ?

**Comment by GreggGut** [comment]
Thanks for pointing in the right direction!
In happens that we had this feature flag enabled by mistake for the pipeline.

Appreciate you help!
