### ISSUE TITLE
(@aws-cdk/custom-resources): AwsCustomResource's use of SingletonFunction causes the role parameter to be ignored

### ISSUE THREAD

**Issue by joehillen** [aws/aws-cdk#14567]
When there are multiple AwsCustomResources, only one instance of the Lambda function is created because of SingletonFunction but if they have different roles, whichever one that comes first will have the role that is used for all subsequent uses of AwsCustomResource even if a different role is specified for later instances of AwsCustomResource.

### Reproduction Steps

Create a stack with 2 AwsCustomResources, one with a `role` as a parameter and one without. 

### What did you expect to happen?

Create another new instance of the lambda with the correct role.

### What actually happened?

Both roles are created but only one is used in the resulting CloudFormation template.

### Environment

  - **CDK CLI Version  :** 1.102.0
  - **Framework Version:** 1.102.0
  - **Node.js Version:** v14.16.0
  - **OS               :** All
  - **Language (Version):** All

### Other

**Relevant parts of the code:**

* https://github.com/aws/aws-cdk/blob/7966f8d48c4bff26beb22856d289f9d0c7e7081d/packages/%40aws-cdk/aws-lambda/lib/singleton-lambda.ts#L111
* https://github.com/aws/aws-cdk/blob/7966f8d48c4bff26beb22856d289f9d0c7e7081d/packages/%40aws-cdk/custom-resources/lib/aws-custom-resource/aws-custom-resource.ts#L342

**Suggested resolution:** Include the role as part of the lookup key for SingletonFunction in ensureLambda?

--- 

This is :bug: Bug Report

**Comment by NGL321** [comment]
Hey @joehillen,

Thank you for submitting this report. Someone from the team will look into it in more depth as time permits. If you are interested in getting this resolved faster, feel free to submit a PR for a fix yourself or alternatively you can get more likes and we will bump this up our priority list.

😸 😷
