### ISSUE TITLE
(init-templates): Region is fixed in Python template sample-app

### ISSUE THREAD

**Issue by dev-julian** [aws/aws-cdk#14577]
### The Question

In the init templates (`packages/aws-cdk/lib/init-templates`) both v1 and v2 of the `sample-app` **Python** template have region **us-west-2** as a fixed parameter in `(v1|v2)/sample-app/python/app.template.py`.
This can cause issues when following along cdkworkshop.com, especially for people new to AWS and CDK.

Is it necessary to have the region fixed here, or can this be removed, so the default region is used for bootstrapping and deployment?

### Environment

  - **CDK CLI Version:** 
  - **Module Version:** 
  - **Node.js Version:** 
  - **OS:** 
  - **Language (Version):**  Python

**Comment by peterwoodworth** [comment]
Thank you for letting us know about this @dev-julian! I've created a PR that fixes this and it should be changed in the next version
