### ISSUE TITLE
(s3-assets): Asset.grantRead() doesn't return the Grant that it creates

### ISSUE THREAD

**Issue by JJC1138** [aws/aws-cdk#14571]
This prevents the `Grant` from being used as a dependency for another resource.

### Reproduction Steps

An example of where this is required is setting up a GameLift server build:

```python
class GameLiftServerBuild(cdk.Stack):
    def __init__(self, scope: cdk.Construct, build_version: str, build_zip_path):
        super().__init__(scope, f"{self.__class__.__name__}-{build_version.replace('.', 'dot')}")

        build_zip_asset = aws_s3_assets.Asset(self, "BuildZipAsset", path=str(build_zip_path))

        gamelift_build_storage_access_role = aws_iam.Role(self, "GameLiftBuildStorageAccessRole", assumed_by=aws_iam.ServicePrincipal("gamelift.amazonaws.com"))
        gamelift_build_storage_access_grant = build_zip_asset.grant_read(gamelift_build_storage_access_role)

        build_storage_location = aws_gamelift.CfnBuild.S3LocationProperty(
            bucket=build_zip_asset.s3_bucket_name,
            key=build_zip_asset.s3_object_key,
            role_arn=gamelift_build_storage_access_role.role_arn,
        )
        build = aws_gamelift.CfnBuild(self, "Build", name="Awesome Game", version=build_version, operating_system="AMAZON_LINUX_2", storage_location=build_storage_location)
        # Because the build is a CFN Resource that doesn't hold real references to the other resources we need to manually ensure that the build asset is uploaded and that the role is granted its permission before GameLift tries to use them when creating the build.
        build.node.add_dependency(build_zip_asset)
        build.node.add_dependency(gamelift_build_storage_access_grant)
```

### What did you expect to happen?

I expected the `CfnBuild` to depend on the `Grant` so that the build creation is delayed until the service has access to the build asset.

### What actually happened?

```
jsii.errors.JavaScriptError:
  Error: Got 'undefined' for non-optional instance of {"name":"dependencies","type":{"fqn":"@aws-cdk/core.IDependable"},"variadic":true}
      at nullAndOk (C:\Users\jon\AppData\Local\Temp\tmpg3afrh3v\lib\program.js:9318:23)
      at Object.deserialize (C:\Users\jon\AppData\Local\Temp\tmpg3afrh3v\lib\program.js:9092:25)
      at Kernel._toSandbox (C:\Users\jon\AppData\Local\Temp\tmpg3afrh3v\lib\program.js:8505:69)
      at C:\Users\jon\AppData\Local\Temp\tmpg3afrh3v\lib\program.js:8553:42
      at Array.map (<anonymous>)
      at Kernel._boxUnboxParameters (C:\Users\jon\AppData\Local\Temp\tmpg3afrh3v\lib\program.js:8553:27)
      at Kernel._toSandboxValues (C:\Users\jon\AppData\Local\Temp\tmpg3afrh3v\lib\program.js:8539:29)
      at C:\Users\jon\AppData\Local\Temp\tmpg3afrh3v\lib\program.js:7970:150
      at Kernel._wrapSandboxCode (C:\Users\jon\AppData\Local\Temp\tmpg3afrh3v\lib\program.js:8582:24)
      at C:\Users\jon\AppData\Local\Temp\tmpg3afrh3v\lib\program.js:7970:107
```

which is a nice way of saying that `gamelift_build_storage_access_grant` is None.

### Environment

  - **CDK CLI Version  :** 1.102.0 (build a75d52f)
  - **Framework Version:** 
  - **Node.js Version:** v14.16.1
  - **OS               :** Microsoft Windows [Version 10.0.19042.928]
  - **Language (Version):** all

### Other

An easy workaround is to grant on the asset's bucket, instead of on the asset itself:

```python
gamelift_build_storage_access_grant = build_zip_asset.bucket.grant_read(gamelift_build_storage_access_role)
```

That actually has exactly the same effect because `Asset.grantRead()` grants access to the whole asset bucket and not just the asset in question.

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment]
@JJC1138 Thanks for reporting this. I'm going to repurpose this as a feature request since its *technically* not a bug.

I am also unassigning and marking this issue as `p2`, which means that we are unable to work on this immediately.

We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://join.slack.com/t/cdk-dev/shared_invite/zt-mso6p56d-qJp7SOTBvMaQuDrx7R2wHg) to solicit support for reprioritization.
