### ISSUE TITLE
(pipelines): should use pipeline variables for Stack outputs

### ISSUE THREAD

**Issue by rix0rrr** [aws/aws-cdk#14584]
Wayyyy better mechanism than we're using right now!

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by skinny85** [comment]
Note that step 1 of this should be adding support for CodePipeline variables to the `CloudFormationCreateUpdateStackAction` and `CloudFormationExecuteChangeSetAction`, similarly like we support them [today for the `CodeBuildAction](https://github.com/aws/aws-cdk/blob/46a16312825cc7b5bf985bc8b69146a1397690d0/packages/%40aws-cdk/aws-codepipeline-actions/lib/codebuild/build-action.ts#L128-L140).

**Comment by rix0rrr** [comment]
Ah ap-cray :(

**Comment by rix0rrr** [comment]
Will be addressed by #12326, closing early as duplicate to keep tracking more manageable.
