### ISSUE TITLE
diff ui: `replace` is as dangerous as `destroy` - so should be in red

### ISSUE THREAD

**Issue by ranguard** [aws/aws-cdk#1458]
Adding an attribute to Cognito user group destroys the old one (with manually added users) with no warning..

Diff show's `replace` against the top level, but that's not as clear as when I remove an attribute and it has `destroy` in red!

I didn't realise it was replacing the whole thing, not just the schema change I'd made.. maybe : change it to `replace (e.g. destroy/create)` on the diff output? and have it in red?

**Comment by rix0rrr** [comment]
Yes, that seems appropriate. Thanks for the report.
