### ISSUE TITLE
CfnImage attrs broken

### ISSUE THREAD

**Issue by OrEisenberg** [aws/aws-cdk#14588]
As near as I can tell, both the `cdk` utility attributes on `imagebuilder.CfnImage` objects as well as the corresponding `get_att` calls are broken. The error message I'm getting is

```Unable to retrieve Name attribute for AWS::ImageBuilder::Image, with error message Resource of type 'AWS::ImageBuilder::Image' with identifier 'Not able to find the image id in current region.' was not found.```

Despite my suspecting that this is a Cloudformation issue rather than a CDK issue, I figured I'd start off by posting here to confirm this.

### Reproduction Steps

```python
image = aws_imagebuilder.CfnImage(
    self,
    id,
    infrastructure_configuration_arn=infra_arn,
    container_recipe_arn=recipe_arn
)
image.attr_arn
```
or
```python
image = aws_imagebuilder.CfnImage(
    self,
    id,
    infrastructure_configuration_arn=infra_arn,
    container_recipe_arn=recipe_arn
)
image.get_att('Arn')
```
### What did you expect to happen?

To get a token for the arn.

### What actually happened?

At deployment time I get an error (where the *name* of the resource it's trying to retrieve is, somewhat comically, 'Not able to find the image id in current region.')

**Update**: I've narrowed down the problem to accessing attributes for *container* images, which makes sense, since the `ImageId` attribute does not exist for them. Therefore, if on the backend, `ImageId` is used to determine the `Arn` attribute for both AMI and container images, then this will break for container images.

--- 

This is :bug: Bug Report

**Comment by peterwoodworth** [comment]
Our L1s are autogenerated from CFN, so you're probably right that this is an issue that lies with them rather than with us, as the synth output looks good to me.

If your update is correct, then there's definitely nothing that we can do about this. Raise this issue with CFN, and I hope they're able to help you! If they aren't, feel free to reopen this issue 😄
