### ISSUE TITLE
[aws-stepfunctions]: Nested arrays are not serialized correctly on input

### ISSUE THREAD

**Issue by marciocarmona** [aws/aws-cdk#14599]
If part of a Step Function task contains a nested array, part of the array is serialized as an object with the indexes as their string keys.

The issue seems to be inside the `TaskInput.fromObject` call, more specifically in the `recurseArray` calls.

### Reproduction Steps
```
        let test = {
            x: [["Hello", "world"], ["this", "is", "bugged"]]
        }

        console.log(util.inspect(renderObject(test), {showHidden: false, depth: null}))
```

### What did you expect to happen?
This should have been returned:
```
{
  x: [
    ['Hello', 'world'],
    ['this', 'is', 'bugged']
  ]
}
```

### What actually happened?
It returned this:
```
{
  x: [
    { '0': 'Hello', '1': 'world' },
    { '0': 'this', '1': 'is', '2': 'bugged' }
  ]
}
```

### Environment

  - **CDK CLI Version  :** 1.98.0 (build 79f4512)
  - **Framework Version:** ?
  - **Node.js Version:** v12.22.1
  - **OS               :** Linux Red Hat 7.2.1-2
  - **Language (Version):** TypeScript (4.0.5)

### Other
After doing some research I noticed that for deeply nested arrays, every other array ends up mapped to an object. e.g.
```
        let test = {
            x: [[[[[[[[[[["Hi!"]]]]]]]]]]]
        }

        console.log(util.inspect(renderObject(test), {showHidden: false, depth: null}))
```
Output:
```
{
  x: [
    {
      '0': [
        {
          '0': [
            {
              '0': [
                {
                  '0': [ { '0': [ 'Hi!' ] } ]
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}
```

The problem seems to come from this `recurseArray` method:
https://github.com/aws/aws-cdk/blob/7966f8d48c4bff26beb22856d289f9d0c7e7081d/packages/%40aws-cdk/aws-stepfunctions/lib/json-path.ts#L115-L139

Notice that it checks if `value` is an object before checking if it's an array, since arrays are actually considered objects by Javascript, it ends up calling the `recurseObject` method.

Recommendation:
- Check if `value` is an array first and call the `recurseArray` method instead.

--- 

This is :bug: Bug Report

**Comment by markmansur** [comment]
This is still an issue fyi
