### ISSUE TITLE
eslint-plugin-cdk license

### ISSUE THREAD

**Issue by jusiskin** [aws/aws-cdk#14594]
There appears to be contradictory licenses declared in the `tools/eslint-plugin-cdk` package.

In the `tools/eslint-plugin-cdk/package.json`, it reads:

https://github.com/aws/aws-cdk/blob/4a24d61654ef77557350e35443ddab7597d61736/tools/eslint-plugin-cdk/package.json#L35

but in `tools/eslint-plugin-cdk/LICENSE` the license appears to be Apache 2.0:

https://github.com/aws/aws-cdk/blob/4a24d61654ef77557350e35443ddab7597d61736/tools/eslint-plugin-cdk/LICENSE#L1-L3

We'd like clarity on what the correct license is.

---

This is a 📕 documentation issue

**Comment by eladb** [comment]
Like all of our codebase, it is licensed under Apache 2.0 - created a PR to update.

However, @jusiskin, this is a private package, with mostly rules that are very CDK-repo specific. Curious what is your use case for using this, or generally what's the reason you are asking about this specific module.

**Comment by jusiskin** [comment]
A CDK construct library that I help develop maintains a fork of `pkglint`. We use it to lint our code to follow the same standards as The AWS Construct Library. Periodically, we look upstream (here) to merge in any changes into our fork. I had noticed that CDK has introduced this new package (`eslint-plugin-cdk`) as a dependency to `pkglint`.

I had investigated porting this new package over as well, but noticed ambiguity in the license. Do you think this package is relevant for construct libraries who are mirroring the CDK tooling?
