### ISSUE TITLE
(S3): S3 bucket is created with block public access off

### ISSUE THREAD

**Issue by jakemraz** [aws/aws-cdk#14606]
new s3.Bucket(...) creates a bucket with block public access off

### Reproduction Steps

```
const mcBucket = new s3.Bucket(this, "TestBucket", {
      bucketName: `test-bucket-asdfasdfasdfasdfasdfqwer`
    });
```
### What did you expect to happen?

S3 bucket is created with Block Public Access **On**.

### What actually happened?

S3 bucket is created with Block Public Access **Off**.

### Environment

  - **CDK CLI Version  :** 1.02
  - **Framework Version:** 1.02
  - **Node.js Version:**  v14.15.1
  - **OS               :** mac os 10.15.7
  - **Language (Version):** TypeScript (3.9.9)

### Other

S3 is created with public access enabled...
I think it's a critical issue for security.
should be fixed quickly..

additional: It works well on cdk 1.83.
but it is occured on 1.102 of cdk

--- 

This is :bug: Bug Report

**Comment by hoegertn** [comment]
Block Public Access "Off" does not mean that the bucket is publicly accessible. It just means that it is possible to open it up.

With Block Public Access set to "on" it is not possible to make a bucket public.

So while I think it is important to set this to "on" on many buckets it is not a security risk per see if it is set to "off".

IMHO, changing the default value is definitely not possible on the S3 module as it would break a lot of CDK apps.

**Comment by iliapolo** [comment]
@jakemraz I'm not sure what your specific concern was, but @hoegertn is right. 

In any case, we cannot change the default value, and since the configuration itself is available via CDK - we don't have much to do here.

**Comment by peterwoodworth** [comment]
Closing because the bot missed this, been open for at least 2 weeks without a response. Please ping me if you want this issue to be reopened! 😄

**Comment by Samrose-Ahmed** [comment]
can we add a feature flag so its opt in at least.
