### ISSUE TITLE
Custom Deploy Confirmation: allow to do custom checks before cdk deploy proceeds

### ISSUE THREAD

**Issue by benm5678** [aws/aws-cdk#14603]
I'd like a way to add confirmation prompt for certain stacks when running "cdk deploy <stackname>" so that the user can be asked something like "Are you sure u want to proceed?" and based on their feedback choose if to terminate or proceed with deploy.

Let's say in our scripts we have stacks for DEV / TEST stages & custom StackProps that include params for "requireApproval" & "approvalDate".  I'd like to set the TEST stage to "requireApproval" and force the person who is deploying to update "approvalDate" to current time.  This way if they accidentally run "cdk deploy TEST" it will fail if they forgot to update the approvalDate.

---

This is a :rocket: Feature Request

**Comment by Ragnoroct** [comment]
@benm5678 Were you able to solve this yourself?

**Comment by Ragnoroct** [comment]
I figured out how to do this, so I thought I might as well document it here.

**Problems**: 
1. Once you are inside the application code to create your stacks/apps/etc `stdin` is a redirection and you have no access to it.
2. Cdk doesn't play nice with async nodejs

**Solution**:
1. Read directly from `/dev/tty`
2. Make everything synchronous

**NOTE**: This code does not check which command you are running. So a simple `synth` will still prompt. The code will have to check what command is being run if you want it to be smarter.
```typescript
import * as fs from "fs";

// read from /dev/tty directly itself since cdk redirects stdin
function prompt(promptText: string){
    // https://github.com/nodejs/node/issues/26450#issue-417306344
    const fd = fs.openSync("/dev/tty", "r")
    const stream = fs.createReadStream("/dev/tty", {
        flags: "r",
        fd: fd,
    })

    process.stdout.write(promptText)

    // https://stackoverflow.com/a/60203932/2276637
    const CHAR_LF = 10
    const CHAR_CR = 13
    const data = []
    const buffer = Buffer.alloc ? Buffer.alloc(1) : new Buffer(1);
    while (true) {
        const bytesRead = fs.readSync(fd, buffer, 0, 1, null)
        if (bytesRead > 0) {
            if (buffer[0] === CHAR_LF){
                break
            } else if (buffer[0] !== CHAR_CR) {
                data.push(Buffer.from(buffer))
            }
        }
    }

    stream.close()
    return Buffer.concat(data).toString("utf-8")
}

const promptResponse = prompt("WARNING: Stack is a production stack. Continue? (y/n*): ")
if (promptResponse.toLowerCase().trim() !== "y") {
    process.exit(1)
}
```

**Comment by gadams999** [comment]
Appreciate the details @Ragnoroct ! This is helpful for creating demo stacks and other uses where CDK is not fully embedded into a pipeline. +1 my friend!
