### ISSUE TITLE
(aws-iam): edit the trust relationship in ECS-task-instance-role via CDK

### ISSUE THREAD

**Issue by TiffanyHsuuuu** [aws/aws-cdk#14611]
Hello, 
I have a general question here. How do I edit the trust relationship in a role via CDK? Before transforming all definitions I wrote in typescript to cloud templates, I already want to add "arn:aws:iam::user:root" to the trust relationship of ECS-task-instance-role, which will be created in cloudformation after I build it. But I couldn't find a way to do it in code instead of adding it manually in console. Can someone please help? :)

**Comment by rix0rrr** [comment]
You can do:

```
role.assumeRolePolicy.addStatements(new iam.PolicyStatement({
  // ... statement here
}));
```

**Comment by TiffanyHsuuuu** [comment]
Hey,
Thank you for answering. It's still a bit confusing for me.
So if I want to attach below policy to a task role, how should I write?
`{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::user:root",
        "Service": "ecs-tasks.amazonaws.com",
      },
      "Action": "sts:AssumeRole"
    }
  ]
}`
