### ISSUE TITLE
(aws-cdk): automated gitpod dev setup currently fails

### ISSUE THREAD

**Issue by jankeromnes** [aws/aws-cdk#14634]
Hello AWS CDK! 👋

I noticed that your Gitpod automated dev setup is broken. Specifically, it's the `.gitpod.yml` `init` task:

https://github.com/aws/aws-cdk/blob/3d9321e816b2e2d1aa381f0b40cd1ff57b0958fb/.gitpod.yml#L8-L9

... that currently fails with:

```
yarn run v1.22.5
$ node ./scripts/check-yarn-lock.js
/workspace/aws-cdk/scripts/check-yarn-lock.js:48
    Object.entries(p.devDependencies ?? {}).forEach(([depName, depVersion]) => errorIfNotInYarnLock(p, depName, depVersion));
                                      ^

SyntaxError: Unexpected token ?
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
error Command failed with exit code 1.
```

I suspect that's because the ES2020 nullish coalescing operator (`??`) used in:

https://github.com/aws/aws-cdk/blob/3d9321e816b2e2d1aa381f0b40cd1ff57b0958fb/scripts/check-yarn-lock.js#L47-L51

is only available in Node.js >= `14.0.0` (source: [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator#browser_compatibility)). However, your `jsii/superchain` Docker image seems to come with Node.js `10.24.1`:

```
/workspace/aws-cdk $ node --version
v10.24.1
```

### Reproduction Steps

1. Open https://gitpod.io/#https://github.com/aws/aws-cdk
2. Notice the error in the Terminal

### What did you expect to happen?

The Gitpod prebuild should work.

### What actually happened?

The prebuild logs an error, and AWS CDK is not prebuilt when opened in Gitpod.

### Environment

  - **CDK CLI Version  :** `master`
  - **Framework Version:** `master`
  - **Node.js Version:**  `10.24.1`
  - **OS               :** `Amazon Linux 2`
  - **Language (Version):** JavaScript (ES2020)

### Other

I'm happy to send a Pull Request to fix this. Please advise whether I should:

1. Upgrade your `jsii/superchain` image to Node.js 14
2. Downsugar the `??` nullish coalescing operator to a Node.js 10 compatible syntax
3. Somehow skip the `check-yarn-lock.js` script and/or modify your `.gitpod.yml` `init` task

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Thanks a lot for reporting @jankeromnes! It's nice to get this level of support from the Gitpod team 😃.

Your suspicions are correct, I've raised https://github.com/aws/aws-cdk/pull/14644 to fix this issue.

Thanks,
Adam
