### ISSUE TITLE
(aws-autoscaling): notificationTarget shouldn't be compulsory in LifecycleHook

### ISSUE THREAD

**Issue by abeer91** [aws/aws-cdk#14641]
The `notificationTarget` property can be unset and by default it will be able to use CWE to deliver Autoscaling Group notifications.

ASG API - https://docs.aws.amazon.com/cli/latest/reference/autoscaling/put-lifecycle-hook.html , keeps `[--notification-target-arn <value>]` as an optional param.

I was able to use L1 construct - `CfnLifecycleHook` as such without providing the `notificationTarget`

```
        const lcHook = new autoscaling.CfnLifecycleHook(this, "LCHook", {
            autoScalingGroupName: nodegroup.autoScalingGroupName,
            lifecycleTransition: LifecycleTransition.INSTANCE_TERMINATING,
            defaultResult: DefaultResult.CONTINUE,
            lifecycleHookName: "TerminateLifecycleHook",
            heartbeatTimeout: 300
        })
``` 

### Reproduction Steps

Documentation shows property is mandatory - https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-autoscaling.LifecycleHook.html

### What did you expect to happen?

notificationTarget should be optional or should have a way to use the default CWE integration.

### What actually happened?

Could not use CWE integration which is how aws-node-termination-handler needs to be configured

### Environment

  - **CDK CLI Version  :** 1.97.0
  - **Framework Version:**
  - **Node.js Version:**  v15.9.0
  - **OS               :** Mac
  - **Language (Version):**  TypeScript

### Other

--- 

This is :bug: Bug Report

**Comment by peterwoodworth** [comment]
Sorry for the long reply here,

You're right. This isn't required from the Cfn side of things, so the L2 construct could have `notificationTargets` be an optional property. This seems to be the only place the property is used: lines 104 and 113

https://github.com/aws/aws-cdk/blob/32f00eb26486b18619f4cf6ca497759c46aa7c8a/packages/%40aws-cdk/aws-autoscaling/lib/lifecycle-hook.ts#L104-L115

I'm not sure why this is required in the first place, but I can't find a reason for making it required
