### ISSUE TITLE
(pipelines): 'npx cdk' is failing in version 1.103.0, causing CDK pipelines synth action to fail

### ISSUE THREAD

**Issue by tomas-mazak** [aws/aws-cdk#14658]
CDK Pipeline, when using NPM simple synth action, runs:

* `npm ci` to install dependencies (including dev dependencies) according to `package-lock.json`
* `npx cdk synth` to synthesize the app

If `aws-cdk` is not listed in package's dependencies, the first command will not install it. Then the `npx` command will not find `aws-cdk` locally and installs it. However, it will install the latest version available, so release is not properly versioned. Also, from version 1.103.0 it fails with following message: `Cannot find module '.../aws-sdk/scripts/check-node-version.js'`.

I would like to raise the following questions:

* Is it correct and desirable that the pipeline installs dev dependencies? Wouldn't it be cleaner to only install prod ones using `npm ci --production`? In that case, `aws-cdk` would need to become production dependency of each project
* Would it be better to run `npx --no-install cdk synth` as synth command, to ensure the pipeline *requires* the `aws-cdk` dependecy and cannot just silently use the latest cdk cli?

Anyways, I would assume that for convenience, `npx cdk ...` should still work without the package being previously installed.

### Reproduction Steps

For consistency, I am using `aws/codebuild/standard:5.0` docker image that CDK pipelines use for synthesis, can be find here: https://github.com/aws/aws-codebuild-docker-images/tree/master/ubuntu/standard/5.0 and build using `docker build -t aws/codebuild/standard:5.0 .`

### What did you expect to happen?

Previous version (1.102.0) works fine:

```
tomas@arkham:~$ docker run --rm -it --entrypoint='' aws/codebuild/standard:5.0 npx --package aws-cdk@1.102.0 cdk version
npx: installed 188 in 9.121s
1.102.0 (build a75d52f)
***************************************************
*** Newer version of CDK is available [1.103.0] ***
*** Upgrade recommended                         ***
***************************************************
```

### What actually happened?

Latest version (1.103.0) fails:

```
tomas@arkham:~$ docker run --rm -it --entrypoint='' aws/codebuild/standard:5.0 npx cdk version
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '/root/.npm/_npx/1/lib/node_modules/cdk/node_modules/aws-cdk/node_modules/aws-sdk/scripts/check-node-version.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! aws-sdk@2.903.0 postinstall: `node scripts/check-node-version.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the aws-sdk@2.903.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-05-12T10_51_22_468Z-debug.log
Install for [ 'cdk@latest' ] failed with code 1
```

### Environment

  - **CDK CLI Version  :** 1.103.0
  - **Framework Version:** N/A
  - **Node.js Version:** v14.15.4
  - **OS               :** CodeBuild standard:5.0 container image
  - **Language (Version):** TypeScript

--- 

This is :bug: Bug Report

**Comment by tomas-mazak** [comment]
Now thinking about it, I am probably mixing two distinct issues here: one is the CDK CLI bug introduced in 1.103.0 version, and the second is pipeline synth silently using extraneous dependency. Would you like me to split the issue?

**Comment by jacktar283** [comment]
I have the same issue, running npx cdk version in a container with aws-cdk@1.103.0 + node 14.5.0 yields the same "sh: node: command not found". I had tried to constrain this via package.json with 'aws-cdk "1.98.0"' but npx cdk seems to fetch the latest version regardless.

At this time I cannot reproduce that in an instance/VM with (nominally) the same environment - This seems to be specific to a containerised environment.

Uplifting the node version to the latest lts release resolves the issue in the same container. ie

container$ nvm install --lts
container$ npm install aws-cdk@1.103.0
container$ npx cdk version
1.103.0 (build bc13a66)

If I can investigate further and attach logs, I will.

**Comment by rix0rrr** [comment]
> Now thinking about it, I am probably mixing two distinct issues here: one is the CDK CLI bug introduced in 1.103.0 version, and the second is pipeline synth silently using extraneous dependency. Would you like me to split the issue?

Yes please. You're right that these have nothing to do with each other.

> * Is it correct and desirable that the pipeline installs dev dependencies?

It's tough to say and it depends on your use case, but in general I would say "yes". The project is being built from source. That typically requires `devDependencies` -- just think of `typescript`. If you disagree with the defaults, you are free to use a SimpleSynthAction that runs exactly the commands you desire. Nothing is forcing you to use `standardNpmSynth`.

> Would it be better to run npx --no-install cdk synth as synth command, to ensure the pipeline requires the aws-cdk dependecy and cannot just silently use the latest cdk cli?

In fact I think the current behavior is more desirable --  people who care can control the version of the CLI by putting it in their `package.json`, and people who don't will just automatically get the latest.

All in all, I think the current behavior of dependency management is correct or at least a desirable default. You are free to deviate from this as you want.

The fact that the CLI has an installation problem is a separate issue

**Comment by rix0rrr** [comment]
Huh, I can reproduce this problem with `aws/codebuild/standard:5.0` but I cannot reproduce it with `jsii/superchain`. Weeeiiiirddd

**Comment by rix0rrr** [comment]
Ha-haaah here is the magic:

```
$ npm set unsafe-perm true
```

**Comment by rix0rrr** [comment]
```
env NPM_CONFIG_UNSAFE_PERM=true npx my-demo-postinstall-plugin@1.0.0
```

**Comment by tomas-mazak** [comment]
Hi @rix0rrr , thanks a million for looking into this!

> In fact I think the current behavior is more desirable -- people who care can control the version of the CLI by putting it in their package.json, and people who don't will just automatically get the latest.

I tend to disagree, I guess reproducible releases are desired in any CI/CD system. Also, this is very much hidden - we weren't aware that latest CDK version is used in our pipelines until we hit the above bug, that triggered without any change to the source repo, I guess many people can be misled the same way we were. Also, `cdk init` produces package.json with the dependency in place, so pipelines should work by default, even if `--no-install` is provided.

But I might be missing the bigger picture here, so I am just going to make the change on our side and not raising a issue/PR for this now.

Thanks again for fixing the actual bug!
