### ISSUE TITLE
(@aws-cdk/pipelines.CDKPipeline) Need the ability to specify template/stack name in UpdatePipeline stage

### ISSUE THREAD

**Issue by gurkarangulati** [aws/aws-cdk#14663]
But I create multiple of these pipelines in one stack. We have one stack that controls all related pipelines. That said, when this synthesizes and deploys, CdKPipeline creates an UpdateSelf Action that only updates the stack that all of this resides in and not the other CFN stacks we want to update/synthesized. Need a way to pass the UpdateSelf the name of the pipeline/template that has been synthesized.

The below code sits in a repo/stack called mycompany-accounts. But also needs to create a CdKPipeline for other repos like mycompany-finances, mycompany-processing, etc. So we had 1 stack that was going to handle all 3 pipelines but CdkPipeline's Update self stage just keeps trying to deploy mycompany-accounts in the last step. I just want to update it's Properties.Source.Buildspec of the created selfMutation step but can't find a way to doso.

Utilizing the below code I create a CdkPipeline 

```

pipeline_cdk = pipelines.CdkPipeline(self, id=f"{pipeline_name}_id",
                                                cloud_assembly_artifact=pipeline_cloud_assembly_artifact,
                                                code_pipeline=pipeline_cp, source_action=pipeline_source_action,
                                                synth_action=pipeline_synth_action, vpc=self._vpc, self_mutating=True)```
                                                
                                                
                                                
"UpdatePipelineSelfMutationB85AAD04": {
      "Type": "AWS::CodeBuild::Project",
      "Properties": {
        "Artifacts": {
          "Type": "CODEPIPELINE"
        },
        "Environment": {
          "ComputeType": "BUILD_GENERAL1_SMALL",
          "Image": "aws/codebuild/standard:4.0",
          "ImagePullCredentialsType": "CODEBUILD",
          "PrivilegedMode": false,
          "Type": "LINUX_CONTAINER"
        },
        "ServiceRole": {
          "Fn::GetAtt": [
            "UpdatePipelineSelfMutationRole33FA4895",
            "Arn"
          ]
        },
        "Source": {
          "BuildSpec": "{\n  \"version\": \"0.2\",\n  \"phases\": {\n    \"install\": {\n      \"commands\": \"npm install -g aws-cdk\"\n    },\n    \"build\": {\n      \"commands\": [\n        \"cdk -a . deploy accounts-dv --require-approval=never --verbose\"\n      ]\n    }\n  }\n}",
          "Type": "CODEPIPELINE"
        },
        "EncryptionKey": "alias/aws/s3"
      },

      "Metadata": {
        "aws:cdk:path": "accounts-dv/mycompany_accounts_services_pipe_id/UpdatePipeline/SelfMutation/Resource"
      }
    }

**Comment by rix0rrr** [comment]
The SelfUpdate action will always deploy the stack the pipeline is defined in, plus the stacks that stack depends on.

If you want to deploy multiple different stacks, make sure there is a dependency between the pipeline stack and the stack you want deployed. Normally this happens automatically if you use constructs in a cross-stack fashion, but if it doesn't you can always call [stack.addDependency](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.Stack.html#addwbrdependencytarget-reason)
