### ISSUE TITLE
(@aws/aws-cdk) aws-cdk.pipelines - CDKPipeline just keeps updating, deploying CF and retriggering the pipeline

### ISSUE THREAD

**Issue by gurkarangulati** [aws/aws-cdk#14664]
I have a mycompany-accounts repository. The repository has a CDKPipeline that deploys the codecommit repo called mycompany-accounts and deploys the mycompany-accounts-dv. 

Currently everything deploys well but then the CdkPipeline/CodePipeline is synthesizing, then Updating/deploying, the mycompany-accounts to the mycompany-accounts-dv stack that also holds the pipeline. Once this updates, it's triggering the synthesizing and the deploy again which keeps going and going. 

What is going on that is incorrect here. 

repo=mycompany-accounts
stack_name= mycompany-accounts-dv
cdk pipeline lives in the same repo.

**Comment by gurkarangulati** [comment]
Solve this - Turns out the local vs Cloud Versions of the aws_cdk libraries were mixed. Some were setting codebuild versions to "Image": "aws/codebuild/standard:4.0" and every future deployment kept trying to go back and forth betwen "Image": "aws/codebuild/standard:5.0" and "Image": "aws/codebuild/standard:4.0". This caused all sorts of updates to keep happening.

**Comment by peterwoodworth** [comment]
Thanks for posting an update to this with your fix, ping me if you need any more help with this issue!
