### ISSUE TITLE
aws-cloudwatch: Add missing statistics

### ISSUE THREAD

**Issue by RyanDawkins** [aws/aws-cdk#14688]
Add missing statistics to Statistic enum for cloud watch graphs.

### Use Case
Graphing p50, p90, p99 metrics using the CDK.

### Proposed Solution
Update the enum to include p50/p90/p99

https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cloudwatch.Statistic.html
### Other
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cloudwatch.Statistic.html

* :wave: I may be able to implement this feature request

---

This is a :rocket: Feature Request

**Comment by RyanDawkins** [comment]
A hack around this if you're using TypeScript in case you run into this issue:

```typescript
import { Statistic as MonoCdkStatistic } from 'monocdk/aws-cloudwatch';

export const Statistic = {
  ...MonoCdkStatistic,
  p50: 'p50',
  p90: 'p90',
  p99: 'p99',
};
```

**Comment by j-schwerer** [comment]
Does it also cover https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_cloudwatch.MetricOptions.html?

There are now 12 statistics on https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Statistics-definitions.html, including trimmed mean, percentile rank, etc. in addition to percentiles…
