### ISSUE TITLE
(aws-eks): updating cluster's endpoint access fails when cluster already in desired configuration

### ISSUE THREAD

**Issue by chillitom** [aws/aws-cdk#14698]
I had to change cluster api endpoint access from PUBLIC_AND_PRIVATE to PUBLIC through the console and then later I updated my CDK constructs to match.   Unexpectedly the updates then fail to apply as the cluster is already in the desired configuration.

```
 5/19 | 09:15:10 | UPDATE_FAILED        | Custom::AWSCDK-EKS-Cluster            | KubeCluster/Resource/Resource/Default (KubeClusterEAB598EB) Received response status [FAILED] from custom resource. Message returned: Cluster is already at the desired configuration with endpointPrivateAccess: false , endpointPublicAccess: true, and Public Endpoint Restrictions: [0.0.0.0/0]

Logs: /aws/lambda/ProductionKubernetesStack-a-OnEventHandler42BEBAE0-1WL89AK3Z0GR5

    at Object.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)
    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at R
        new CustomResource (C:\code\TradingUI\stack\node_modules\@aws-cdk\core\lib\custom-resource.ts:119:21)
        \_ new ClusterResource (C:\code\TradingUI\stack\node_modules\@aws-cdk\aws-eks\lib\cluster-resource.ts:67:22)
        \_ new Cluster (C:\code\TradingUI\stack\node_modules\@aws-cdk\aws-eks\lib\cluster.ts:1007:46)
        \_ new KubernetesStack (C:\code\TradingUI\stack\lib\KubernetesStack.ts:26:25)
```

### Reproduction Steps

Create a cluster.

```typescript
        const cluster = new eks.Cluster(this,
            'KubeCluster',
            {
                clusterName,
                version: eks.KubernetesVersion.V1_18,
                coreDnsComputeType: eks.CoreDnsComputeType.EC2,
                defaultCapacity: 1,
                defaultCapacityInstance: ec2.InstanceType.of(ec2.InstanceClass.T2, ec2.InstanceSize.LARGE),
                vpc: props.vpc,
                vpcSubnets: [
                    { subnetType: ec2.SubnetType.PRIVATE }
                ],
                mastersRole: mastersRole,
                endpointAccess: eks.EndpointAccess.PUBLIC_AND_PRIVATE,
            })
```

In EKS Console change the endpoint access to public only.

Change the CDK endpointAccess parameter to `eks.EndpointAccess.PUBLIC` and deploy the stack.

### What did you expect to happen?

Configuration is already in the desired state so update should succeed.

### What actually happened?

Configuration of the stack failed and rolled back.  I had to revert the configuration to PUBLIC_AND_PRIVATE through the console (slow!) and then re-deploy the stack with `eks.EndpointAccess.PUBLIC`.

### Environment

  - **CDK CLI Version  : 1.103.0**
  - **Framework Version: 1.103.0**
  - **Node.js Version:** 
  - **OS               : **
  - **Language (Version):  Typescript ** 

### Other

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment]
I am unassigning and marking this issue as `p2`, which means that we are unable to work on this immediately.

We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://join.slack.com/t/cdk-dev/shared_invite/zt-mso6p56d-qJp7SOTBvMaQuDrx7R2wHg) to solicit support for reprioritization.

**Comment by petteriv-nordic** [comment]
Can this be re-opened, this is still an issue.
