### ISSUE TITLE
(aws-eks): aws-eks.Cluster.addCdk8sChart() guidance

### ISSUE THREAD

**Issue by adriantaut** [aws/aws-cdk#14696]
## :question: General Issue

hey guys, I’m a newbie with cdk8s and looking for some guidance, please. I am trying to do the following in a single CDK App as instructed in link:
create a simple Cdk8s Chart
apply the Cdk8s Chart to an existing EKS Cluster via the @aws-cdk/aws-eks.Cluster.addCdk8sChart() method

My cdk8s.ts file:

```
import * as cdk8s from 'cdk8s';
import * as kplus from 'cdk8s-plus';
import * as constructs from 'constructs';

export class MyCdk8sChart extends cdk8s.Chart {
  constructor(scope: constructs.Construct, id: string) {
    super(scope, id);

    new kplus.Deployment(this, 'refkube-kplus-deploy', {
        replicas: 1,
        metadata: {
            name: 'cdk8s-deployment',
            labels: {
                'app': 'cdk8s'
            },
        },
        containers: [
            new kplus.Container({
                name: 'cdk8s',
                image: 'nginx:1.14.2',
                port: 80
            })
        ]
    });
  }
}
```

My application-stack.ts

```
import * as cdk from '@aws-cdk/core';
import {KubernetesApplication} from '@flutter-global/cdk-lib-ppb';
import deployment from '../resources/deployment.json';
import service from '../resources/service.json';
import { MyCdk8sChart } from './ck8s'
import * as cdk8s from 'cdk8s';

export interface ApplicationStackProps extends cdk.StackProps {
    /**
     * Logical name of the deployment environment (stage): qa/nxt/drk/prd/...
     */
    readonly deployEnvironment: string;
    readonly clusterName: string;
    readonly vpcName?: string;
}

/**
 * Application stack
 */
export class ApplicationStack extends cdk.Stack {
    constructor(scope: cdk.Construct, id: string, props: ApplicationStackProps) {
        super(scope, id, props);

        const k8sApp = new KubernetesApplication(this, 'refkubeService', {
            tla: 'refkube',
            deployEnvironment: props.deployEnvironment,
            vpcName: props.vpcName,
            clusterName: props.clusterName,
        });
        // create a cdk8s chart and use `cdk8s.App` as the scope.
        const myChart = new MyCdk8sChart(new cdk8s.App(), 'MyChart');

        // add the cdk8s chart to the cluster
        k8sApp.cluster.addCdk8sChart('my-chart', myChart);
    }
}
```

This application is working with a raw k8s manifest and the `@aws-cdk/aws-eks.Cluster.addManifest() method, however, when trying to cdk synth using the addCdk8sChart() method I get

```
# cdk synth
construct does not have an associated node. All constructs must extend the "Construct" base class
Subprocess exited with error 1
```

I guess it might be something related with the Cdk8sChart being created with the constructs.Construc scope, while the CDK App with the @aws-cdk/core Construct. Could someone help with some guidance around bundling these two together?

⚠️ Important Information
For support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/tagged/aws-cdk). This repository's issues are intended for feature requests and bug reports.
-->

### Environment

  - **CDK CLI Version:** 1.103.0 (build bc13a66)
  - **Module Version:** aws-cdk
  - **Node.js Version:** v15.5.1
  - **OS:** macOS Catalina
  - **Language (Version):** TypeScript (3.8.3)

**Comment by bryanmig** [comment]
I am experiencing the same issue.  I cant figure out if this is a documentation issue or a regression. Any guidance would be much appreciated.

**Comment by adriantaut** [comment]
@iliapolo thank you, indeed, your code works, but this time also works our code. Will investigate if it was a version mismatch or simply the `cdk8s-plus` vs `cdk8s-plus-17` dependencies you've changed.

Cheers!

**Comment by peterwoodworth** [comment]
Hey @adriantaut, do you have an update on your investigation?

If you don't need any more help from us, feel free to close the issue 😄

**Comment by bryanmig** [comment]
For me it turned out to be a dependency conflict - I ha copied some example code which used an old/incompatible version.  Once I updated, the issue was gone.

**Comment by adriantaut** [comment]
I agree, I will close the issue. Many thanks!
