### ISSUE TITLE
(eks): Reusable Kubectl Provider for imported clusters

### ISSUE THREAD

**Issue by SomeoneWeird** [aws/aws-cdk#14692]
It would be great if we could define reusable a Kubectl Provider for imported clusters with `eks.Cluster.fromClusterAttributes`.

### Use Case

Currently when a cluster is referred to for the first time in a stack it deploys a new NestedStack that contains a single lambda. For accounts with a large number of stacks this can be a problem when getting close to the service limit of 200 stacks per account.

### Proposed Solution

Being able to deploy a single provider for a cluster manually, and then do something like

```ts
eks.Cluster.fromClusterAttributes({
   ...
   provider: eks.Provider.fromExisting({ ... })
})
```

Another potentially solution is to change the `KubectlProvider` from being a `NestedStack` to being a `Construct`.

### Other

There is already a [`getOrCreate`](https://github.com/aws/aws-cdk/blob/7966f8d48c4bff26beb22856d289f9d0c7e7081d/packages/%40aws-cdk/aws-eks/lib/kubectl-provider.ts#L24-L40) function that calls [`_attachKubectlResourceScope`](https://github.com/aws/aws-cdk/blob/7966f8d48c4bff26beb22856d289f9d0c7e7081d/packages/%40aws-cdk/aws-eks/lib/cluster.ts#L1402-L1405), but this would only work for an existing `eks.Cluster` instance, not one being created using `fromClusterAttributes`

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by iliapolo** [comment]
Related to https://github.com/aws/aws-cdk/issues/12107

**Comment by SomeoneWeird** [comment]
This is still relevant.
