### ISSUE TITLE
(cli) cdk ls displays every stack as undefined 

### ISSUE THREAD

**Issue by digihunch** [aws/aws-cdk#14693]
ls command displays stack name as undefined

### Reproduction Steps

I've been working on my python [project](https://github.com/digihunch/kubelab) consisting of several stacks. i start with ls command to verify stack. This has been without issues but it breaks since 1.102.0. I was hoping it was fixed in 1.103.0 but it displays undefined instead of stack name.

Observation:

```
(.venv)  > cdk --version
1.101.0 (build 149f0fc)
(.venv)  > cdk ls
vpc-stack
security-stack
bastion-stack
private-stack
public-stack
(.venv)  > npm install -g aws-cdk@1.102.0

changed 182 packages, and audited 189 packages in 3s

found 0 vulnerabilities
(.venv)  > cdk ls
Cannot read property 'length' of undefined
(.venv)  > npm install -g aws-cdk@1.103.0

removed 9 packages, changed 173 packages, and audited 180 packages in 3s

found 0 vulnerabilities
(.venv)  > cdk ls
undefined
undefined
undefined
undefined
undefined
(.venv)  > npm install -g aws-cdk@1.101.0

added 9 packages, changed 173 packages, and audited 189 packages in 3s

found 0 vulnerabilities
(.venv)  > cdk ls
vpc-stack
security-stack
bastion-stack
private-stack
public-stack
(.venv)  >
```

Expectation:
- Newer versions should not break existing behaivour.

### Environment

  - **CDK CLI Version  :** 1.103.0
  - **Framework Version:** 
  - **Node.js Version:** 16.0.0
  - **OS               : MAC OS 11.2.3
  - **Language (Version):** Python (3.9.4)

### Other

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
If you are using NPM 7, you may be running into this bug, which means not all CLI dependency packages were upgraded successfully: https://github.com/npm/cli/issues/3196

A clean reinstall of the CLI should fix it.

**Comment by digihunch** [comment]
Thanks. I updated npm which appears to have fixed the issue
