### ISSUE TITLE
Toolkit: toolkit output domain name needs to use `RegionalDomainName` for GovCloud and CN compatibility

### ISSUE THREAD

**Issue by rix0rrr** [aws/aws-cdk#1469]
Although `{ "Fn::GetAtt": "DomainName" }` seems to work in CN, it does not work in GovCloud (in GovCloud the wrong domain name is returned).

`RegionalDomainName` seems to work; don't know if that will break something else.

**Comment by eladb** [comment]
@RomainMuller @rix0rrr what would you recommend we do to resolve this?

**Comment by rix0rrr** [comment]
Update the bootstrap template and test it in a couple of commercial regions.

**Comment by beary** [comment]
I just tried in `cn-north-1`, `{ "Fn::GetAtt": "DomainName" }` [reports an error](https://github.com/aws/aws-cdk/issues/1459#issuecomment-517705446).

After modified the `DomainName` to `RegionalDomainName`, the problem above was resolved.
https://github.com/aws/aws-cdk/blob/6d762f97c9ed59d3182ae1688dec4bd015d8953d/packages/aws-cdk/lib/api/bootstrap-environment.ts#L37

---

But there is anthor problem,
```bash
CREATE_FAILED | AWS::IAM::Role | xGetFunction/ServiceRole (xGetFunctionServiceRoleE6AF8C22) Invalid principal in policy: "SERVICE":"lambda.amazonaws.com.cn" (Service: AmazonIdentityManagement; Status Code: 400; Error Code: MalformedPolicyDocument; Request ID: xxxxxxxxx)
```
Maybe the service principal should be hardcoded to `*.amazonaws.com` but not use `AWS::URLSuffix`.
Here is my explanation in serverless.js project https://github.com/serverless/serverless/pull/6127#issuecomment-495457189

**Comment by wimzyLive** [comment]
@rix0rrr @eladb  This also doesn't work with CN regions.

**Comment by sassoo** [comment]
specifically govcloud customers are being negatively impacted by this. cdk deploy's do not work at all.
