### ISSUE TITLE
Vpc creation fails when using values passed in via the Context

### ISSUE THREAD

**Issue by tzs34** [aws/aws-cdk#14700]
Hello

I am filing this as a bug but please correct me if I am mistaken.

I create a Vpc using values from my context e.g.

`    const {
      vpc_name,
      vpc_cidr,
      cidr_mask,
      ingress_port,
      isolated_subnet_name,
      max_azs,
      egress_security_group_name,
      ingess_security_group_name,
    } = this.node.tryGetContext("vpc_config");`

`   this.vpc = new Vpc(this, vpc_name, {
      cidr: vpc_cidr,
      maxAzs: max_azs,
      subnetConfiguration: [
        {
          cidrMask: cidr_mask,
          name: isolated_subnet_name,
          subnetType: SubnetType.ISOLATED,
        },
      ],
    });`

I get an error

`      throw new Error(`${count} of /${mask} exceeds remaining space of ${this.networkCidr.cidr}`);
            ^
Error: 1 of /28 exceeds remaining space of 10.0.0.0/21`

But when I hard code the cidr and cidrMask values it works fine. The stack is deployed as I would expect. Can someone tell me how I can avoid hard coding the values into my Vpc please ? Or where I am going wrong.

  - **CDK CLI Version  :  1.102.0**
  - **Node.js Version: v14.16.1** 
  - **OS               : Windows 10**
  - **Language (Version): TypeScript (3.8.3)** 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
There is no reason why values you're getting from context and values you'd be passing directly into the construct should have different behavior.

Only reason I can think of is that the values you are passing now are not the values you think you are passing.

Have you tried `console.log`ing all values (specifically the CIDRs) to see what they are?

**Comment by peterwoodworth** [comment]
Closing because it's been more than 2 weeks without a response (bot missed this!) Ping me if you'd like to reopen this issue 😄
