### ISSUE TITLE
(aws-stepfunctions-tasks): How to specify JSON Path as whole DynamoDB item

### ISSUE THREAD

**Issue by acomagu** [aws/aws-cdk#14702]
## :question: General Issue

I want to get configure StepFunctions Task like

```json
"Save Foo": {
  "Type": "Task",
  "Resource": "arn:aws:states:::dynamodb:putItem",
  "Parameters": {
    "TableName": "Foo",
    "Item.$": "$.foo"
  }
}
```

But seems to have no way to specify JSON Path to "Item" field.

```typescript
const saveFooTask = new tasks.DynamoPutItem(this, 'SaveFooTask', {
  table: fooTable,
  item:              // What should I specify here?
});
```

I guess a function like `tasks.JsonPath.dynamoAttributeMapAs(path)` is needed.

### Environment

  - **CDK CLI Version:** 2.0.0-rc.3
  - **Module Version:** 2.0.0-rc.3
  - **Node.js Version:** v16.1.0
  - **OS:** Linux acm-envy2-win-wsl 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 GNU/Linux
  - **Language (Version):** TypeScript(4.2.3)

**Comment by peterwoodworth** [comment]
Hey @acomagu, sorry for the long response time.

Here's a template for what you'll want to input:

```ts
    const task = new tasks.DynamoPutItem(this, "SaveFooTask", {
      table: table,
      item: {
        "foo": tasks.DynamoAttributeValue.fromString(JsonPath.stringAt('$.bar')
      }
    })
```

The [`fromString`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-stepfunctions-tasks.DynamoAttributeValue.html#static-fromwbrstringvalue) method can be a JsonPath 😄
