### ISSUE TITLE
@aws-cdk/aws-ec2.InterfaceVpcEndpoint Fails Test

### ISSUE THREAD

**Issue by fractionalJoe** [aws/aws-cdk#14703]
### Reproduction Steps
Run the jest test below:
```typescript
import { InterfaceVpcEndpoint, InterfaceVpcEndpointAwsService, Vpc }
  from "@aws-cdk/aws-ec2";
import { Stack } from "@aws-cdk/core";

test("InterfaceVpcEndpoint", () => {
  // given
  const stack = new Stack();
  const vpc = new Vpc(stack, "TestVpc");
  // when
  new InterfaceVpcEndpoint(stack, "TestEndpoint", {
    lookupSupportedAzs: true,
    service: InterfaceVpcEndpointAwsService.SECRETS_MANAGER,
    vpc: vpc,
  });
});
````

### What did you expect to happen?
The test to succeed.

### What actually happened?
The test failed with the error `Cannot look up VPC endpoint availability zones if account/region are not specified` and stack trace:
``` 
at InterfaceVpcEndpoint.validateCanLookupSupportedAzs (node_modules/@aws-cdk/aws-ec2/lib/vpc-endpoint.ts:556:13)
      at InterfaceVpcEndpoint.endpointSubnets (node_modules/@aws-cdk/aws-ec2/lib/vpc-endpoint.ts:526:10)
      at new InterfaceVpcEndpoint (node_modules/@aws-cdk/aws-ec2/lib/vpc-endpoint.ts:480:28)
      at Object.<anonymous> (test/cdk-constructs/interface-vpc-endpoint.test.ts:10:3)
```

### Environment

  - **CDK CLI Version  :** 1.103.0 (build bc13a66)
  - **Framework Version:** 1.103.0
  - **Node.js Version:** v14.15.1
  - **OS               :** Ubuntu 20.04.2 LTS
  - **Language (Version):** TypeScript 4.2.4
  - **Jest (Version) :** 26.6.3
  - **ts-jest (version):** 26.5.6

### Other

I understand this can work without the `lookupSupportedAzs: true,` param property, but my default profile is configured. I'm unable to determine why this is failing.

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
Hey, have you seen this page? https://docs.aws.amazon.com/cdk/latest/guide/environments.html

**Comment by fractionalJoe** [comment]
thanks rix0rrrr!

**Comment by fractionalJoe** [comment]
Premature closing. The test still fails after updating to
``` typescript
import "@aws-cdk/assert/jest";
import { InterfaceVpcEndpoint, InterfaceVpcEndpointAwsService, Vpc }
  from "@aws-cdk/aws-ec2";
import { App, Stack } from "@aws-cdk/core";
import "jest-cdk-snapshot";

describe("InterfaceVpcEndpoint", () => {
  // given
  const app = new App();
  const stack = new Stack(app, "TestStack", {
    env: {
      account: process.env.CDK_DEFAULT_ACCOUNT,
      region: process.env.CDK_DEFAULT_REGION,
    },
  });
  const vpc = new Vpc(stack, "TestVpc");
  // when
  new InterfaceVpcEndpoint(stack, "TestEndpoint", {
    lookupSupportedAzs: true,
    service: InterfaceVpcEndpointAwsService.SECRETS_MANAGER,
    vpc: vpc,
  });

  it("matches the snapshot", () => {
    expect(stack).toMatchCdkSnapshot({ yaml: true });
  });
});
```
Am I missing something in that doc?

**Comment by fractionalJoe** [comment]
Following up on this, I'm still unable to make progress and it's becoming a blocker. I have read through the docs and am unable to see what I'm doing wrong. Any update?

**Comment by peterwoodworth** [comment]
@fractionalJoe sorry for the long response time,

`process.env.CDK_DEFAULT_ACCOUNT` returns _undefined_ when just running the tests. This is because you aren't running the file in the `/bin` folder when testing, so you won't get the same context the CDK will grab. 

You'll have to supply the account and region credentials yourself in the test file

**Comment by peterwoodworth** [comment]
This test will work, even with the dummy account number
```ts
it("Should have InterfaceVpcEndpoint", () => {
  // given
  const app = new App();
  const env = { account: '123456789012', region: 'us-west-2' };
  const stack = new Vpctest.VpctestStack(app, "TestStack", {env: env});

  expectCDK(stack).to(haveResourceLike("AWS::EC2::VPCEndpoint"))
});
```
The code will throw an error only if both account and region are undefined, it doesn't actually matter what the values are for this test to pass 
https://github.com/aws/aws-cdk/blob/7966f8d48c4bff26beb22856d289f9d0c7e7081d/packages/%40aws-cdk/aws-ec2/lib/vpc-endpoint.ts#L546-L557

**Comment by peterwoodworth** [comment]
I'll be closing this issue now, let me know if the above didn't help you out here or if you have any questions!

**Comment by fractionalJoe** [comment]
Thanks @peterwoodworth, that solved my issue. Is this quirk of CDK_DEFAULT_ACCOUNT (and I'm assuming CDK_DEFAULT_REGION) returning _undefined_ documented anywhere for future reference? I'm aware now but others may have similar questions.

**Comment by khliu1238** [comment]
> The code will throw the error you received on creating an InterfaceVpcEndpoint only if both account and region of the stack are undefined and lookupSupportedAzs is true. So it doesn't actually matter what the values are for this test to pass

From the condition `if (agnosticAcct || agnosticRegion) { `, looks like if either of these is undefined it'll throw.
