### ISSUE TITLE
(sqs queue): ability to add secure transport condition

### ISSUE THREAD

**Issue by 0xjjoyy** [aws/aws-cdk#14705]
When adding a queue to cloudwatch events, I use add_target. However, it's not straightforward to customize the resource policy that's created. There's an sqs  queue policy with the principal get att to the cloudwatch rule, though no hook to expose the resource policy.

```
event_rule.add_target(event_targets.SqsQueue(queue))
```

### Use Case

I need to add "aws:SecureTransport".

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by MrArnoldPalmer** [comment]
Hey @0xjjoyy, thanks for the request.

Have you tried using [`addToResourcePolicy`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-sqs.Queue.html#addwbrtowbrresourcewbrpolicystatement) on the `Queue` to add `aws:secureTransport` actions?

Are you requesting that this action be enabled by default on the resource policy by default when adding a target so that only https traffic is accepted?

**Comment by 0xjjoyy** [comment]
1. Thanks, I could use addToResourcePolicy, though the policy already exists and added. So I need to lookup the principal, which is auto generated and if I do a ref I get a circular dependency message.

There might be a way to do it, though I'm probably just doing something wrong.

2. Yes, that would be even easier if there was a toggle to enable secure transport!

**Comment by MrArnoldPalmer** [comment]
1. Have you tried using [escape hatches](https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html) to access the L1 resources and updating the policy that way? I'm not sure if this is doable but may help avoid a circular dependency if you're encountering one with the L2s.
2. Makes sense to me!

**Comment by 0xjjoyy** [comment]
For now I just used addToResourcePolicy and for the principal applied to all events service principal. That works for now as all service principals should be using TLS for this use case.

**Comment by 0xjjoyy** [comment]
I did the following

```
        enforce_tls_statement = iam.PolicyStatement(
            sid="Enforce TLS for all principals",
            effect=iam.Effect.DENY,
            principals=[
                iam.AnyPrincipal(),
            ],
            actions=[
                "sqs:*",
            ],
            resources=[queue.queue_arn],
            conditions={
                "Bool": {"aws:secureTransport": "false"},
            },
        )
```

**Comment by frankwese** [comment]
> enforce_tls_statement = iam.PolicyStatement(
>             sid="Enforce TLS for all principals",
>             effect=iam.Effect.DENY,
>             principals=[
>                 iam.AnyPrincipal(),
>             ],
>             actions=[
>                 "sqs:*",
>             ],
>             resources=[queue.queue_arn],
>             conditions={
>                 "Bool": {"aws:secureTransport": "false"},
>             },
>         )

There is a typo it has to be `aws:SecureTransport` not `aws:secureTransport`
