### ISSUE TITLE
(aws_apigatewayv2_integrations.LambdaWebSocketIntegration): how to subclass?

### ISSUE THREAD

**Issue by jrobbins-LiveData** [aws/aws-cdk#14716]
## :question: General Issue
I need access to the `integration_uri` created by `WebSocketApi`'s use of `LambdaWebSocketIntegration`'s `bind` function.
(See this [issue](https://github.com/aws/aws-cdk/issues/14715) for reasons why this makes sense.) 

I can retrieve it using a `recursiveFind` function searching through the construct's `node.children`, but this seemed suboptimal.

I thought it might make sense to subclass `LambdaWebSocketIntegration` instead, in order to retrieve the result of the internal `bind` call.   

### The Question

Since `WebSocketApi` doesn't currently surface the integration's uri, I thought I could subclass `LambdaWebSocketIntegration` and capture the uri during the `bind` process.

```python
            class MyIntegration(LambdaWebSocketIntegration):
                def bind(self, options):
                    integration_config = super().bind(
                        route=options.route, scope=options.scope
                    )
                    self.uri = integration_config.uri
                    return integration_config
```

The above class works, but note the signature on `bind`.  This is not the [documented signature](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_apigatewayv2_integrations/LambdaWebSocketIntegration.html), which should be

```python
            def bind(self, *, route, scope):
```

Apparently, the `bind` method of my subclass gets called with [WebSocketRouteIntegrationBindOptions](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_apigatewayv2/WebSocketRouteIntegrationBindOptions.html?highlight=websocketrouteintegrationbindoptions)?

The CDK code which is calling my `bind` function is in `Lib\site-packages\jsii\_kernel\__init__.py`:

```python
def _handle_callback(kernel, callback):
    # need to handle get, set requests here as well as invoke requests
    if callback.invoke:
        obj = _reference_map.resolve_id(callback.invoke.objref.ref)
        method = getattr(obj, callback.cookie)
        hydrated_args = [
            _recursize_dereference(kernel, a) for a in callback.invoke.args
        ]
        return method(*hydrated_args)
```

This callback mechanism doesn't seem to be aware that it is calling a user-written subclass `bind` method.

Are construct classes meant to be subclassable in Python?  

If so, why is the subclass's `bind` called back with a different signature than `super's` signature? 

(Note that `super().bind(route=options.route, scope=options.scope` works, and shows that one needs to follow the documentation in calling the base `LambdaWebSocketIntegration` class.)

### Environment

  - **CDK CLI Version:** 1.104.0 (build 44d3383)
  - **Module Version:** Name: aws-cdk.aws-apigatewayv2-integrations Version: 1.104.0
  - **Node.js Version:** v14.16.1
  - **OS:** Windows 10 
  - **Language (Version):** Python (3.9.5)

**Comment by ryparker** [comment]
Hey @jrobbins-LiveData 👋🏻 

Are you still seeking guidance on this? Our documentation for the python `LambdaWebSocketIntegration` has been updated to reflect your implementation `bind(*, route, scope)`.

> This callback mechanism doesn't seem to be aware that it is calling a user-written subclass bind method.

Could you elaborate on how you're coming to this conclusion?

**Comment by jrobbins-LiveData** [comment]
Hi @ryparker.  Sorry for my delayed response.  I tried implementing a `bind` (in Python) and went in with the debugger to see how it was actually getting called.  At the time, it wasn't getting called the way the doc shows it.  Rather, it gets called with an object (I called it `options`) that has `route` and `scope` as attributes.
