### ISSUE TITLE
apigatewayv2 WebSocketApi: please surface more attributes

### ISSUE THREAD

**Issue by jrobbins-LiveData** [aws/aws-cdk#14715]
[aws_apigatewayv2.WebSocketApi](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_apigatewayv2/WebSocketApi.html?highlight=websocketapi) is a really great start, but to build our websocket app, we need access to attributes it creates but doesn't surface. 

Examples of these "hidden" attributes include the [integration_uri](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_apigatewayv2/WebSocketIntegrationProps.html?highlight=integration_uri#aws_cdk.aws_apigatewayv2.WebSocketIntegrationProps.integration_uri)(s), and the [routes](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_apigatewayv2/WebSocketRoute.html?highlight=websocketroute)

### Use Case

Without this feature, we are forced to use a `recursiveFind` function to recursively search out these attributes in the construct's `node.children` tree.  While this works, the ergonomics are obviously worse than those of the high-level `WebSocketApi` construct.

The reason we need access to these attributes is to finish defining the actual WebSocketApi.  For example, if you want to use the same Lambda you are using for the integration(s) as your authorizer, you'll need to use the lower-level [CfnAuthorizer](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_apigatewayv2/CfnAuthorizer.html?highlight=cfnauthorizer) construct. This construct requires [authorizer_uri](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_apigatewayv2/CfnAuthorizer.html?highlight=cfnauthorizer#aws_cdk.aws_apigatewayv2.CfnAuthorizer.authorizer_uri) as one of its params. Without this proposed additional set of published attributes from the `WebSocketApi`, one has to repeat oneself and construct this special `uri` by hand, despite the fact that the constructor for `WebSocketApi` has already done this behind the scenes.

Similarly, if your `$default` route has a response, you need to do something like this

```
            defaultRoute = recursiveFind(
                webSocketApi, apigw2.WebSocketRoute, lambda x: x.route_key == "$default"
            )
            defaultRoute.node.default_child.route_response_selection_expression = (
                "$default"
            )
```

to configure the response.  

We also found that configuring this response created a dependency that had to be manually declared using the "hidden" routes.

```
            deployment.add_depends_on(connectCfnRoute)
            deployment.add_depends_on(disconnectRoute.node.default_child)
            deployment.add_depends_on(defaultRouteResponse)
```

### Proposed Solution

Minimally, it would be great if `WebSocketApi` surfaced attributes for the integration(s) and route(s) it creates.  

Maximally, it would make it easier to configure a response path and an authorizer without requiring the  use of other `Cfn` low-level constructs.  Also, ideally, it would handle all dependencies as part of the high-level construct.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by nija-at** [comment]
Hi @jrobbins-LiveData,

Thanks for filing this issue!

However, surfacing more of the internals is not the approach we usually take in the CDK. The underlying implementation can change in the future for any number of reasons (bug fixes, new features, refactors, etc.).

> For example, if you want to use the same Lambda you are using for the integration(s) as your authorizer, you'll need to use the lower-level CfnAuthorizer construct

We're actually missing implementations for authorizers for Websocket APIs. This would've looked similar to what we have for HTTP APIs - https://docs.aws.amazon.com/cdk/api/latest/docs/aws-apigatewayv2-authorizers-readme.html and perhaps other similar constructs.

Feel free to open a feature request asking for specific features in the Websocket APIs, such as authorizer support, etc.

However, we're unable to invest time in this area currently but we welcome contributions. In fact, a lot of the support for HTTP APIs and Websocket APIs have been contributions.

**Comment by peterwoodworth** [comment]
Closing now because the bot missed it
