### ISSUE TITLE
Best practices for adding CFN parameters to existing constructs.

### ISSUE THREAD

**Issue by CLowenthal-zmi** [aws/aws-cdk#1471]
Looking at the S3 Bucket construct, it seems like there is not a good option for using the existing construct while using additional cloudformation options that aren't already included.

Specifically we are looking to create a Bucket construct that by default sets the [PublicAccessBlockConfiguration](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html#cfn-s3-bucket-publicaccessblockconfiguration) options.

In the current Bucket construct the [CfnBucket is created](https://github.com/awslabs/aws-cdk/blob/master/packages/%40aws-cdk/aws-s3/lib/bucket.ts#L586) without any way to set these options.

Here is a simple example of what we're trying to build:
```
export class Bucket extends Construct {
    constructor(parent: Construct, id: string, _: BucketProps){
        super(parent, id);

        new CfnBucket(this, 'Resource', {
            publicAccessBlockConfiguration: {
                blockPublicAcls: true,
                ignorePublicAcls: true,
                blockPublicPolicy: true,
                restrictPublicBuckets: true
            }
        });
    }
}
```

But we would like to be able to include all the functionality provided by the existing Bucket construct as well. Is there any guidance on how to best accomplish this?

**Comment by NGL321** [comment]
_Closing stale_

Please feel free to reopen if pertinent questions arise.
😸
