### ISSUE TITLE
CodePipeline: it should be possible to explicitly provide a stage/action name

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#1472]
At the moment, CodePipeline stage and action names are automatically derived from the construct ID. This is usually a great default, but since there are limitations to construct IDs (namely, they don't allow the usage of tokens), there might be cases where people would want to customize this behavior.

I am proposing to add an optional property to Stage/Action with a "@default" indication that the name is derived from the construct ID (and mention the limitation above).

**Comment by skinny85** [comment]
We now have an explicit `stageName` / `actionName` :).

Resolving.
