### ISSUE TITLE
[aws-eks]: Cluster construct "Cannot auto-tag subnet" warning when creating default NodeGroup, when given existing subnet

### ISSUE THREAD

**Issue by lucaswilric** [aws/aws-cdk#14724]
I am trying to create an EKS cluster using the `eks.Cluster` construct, and I am providing specific subnets that have been created by a separate CloudFormation stack.

When I run `cdk synth`, I get this warning, repeated for every subnet in the VPC:

```
[Warning at /MyCdkStack/cluster] Could not auto-tag private subnet subnet-1a2b3c4d with "kubernetes.io/role/internal-elb=1", please remember to do this manually
```

### Reproduction Steps

```typescript
// Assume "exisingSubnet1" and "existingSubnet2" are
// ISubnet objects representing subnets created outside
// CDK, that are tagged with
// `kubernetes.io/role/internal-elb=1`

new eks.Cluster(this, "cluster", {
  version: eks.KubernetesVersion.V1_19,
  clusterName: "myCluster",
  vpc: existingVpc,
  vpcSubnets: [{ subnets: [existingSubnet1, existingSubnet2] }],
  defaultCapacity: 0,
});
```

### What did you expect to happen?

* I expected no warnings to appear for subnets that are already tagged in the way the construct expects.
* I expected no warnings to appear for subnets that the construct shouldn't care about (i.e. they aren't part of the `SubnetSelection` that I assigned to `vpcSubnets`).

I would only expect to receive a warning when:

* I pass a subnet into the `eks.Cluster` construct, AND
* The subnet is not tagged with `kubernetes.io/role/internal-elb=1`, AND
* The subnet cannot be auto-tagged.

### What actually happened?

I receive a warning for every subnet in my VPC, including the subnets that are tagged in the way the warning describes, and subnets that I have deliberately decided to leave untagged. I suspect the "every subnet" part is related to aws/aws-cdk#10312.

### Environment

  - **CDK CLI Version  :** 1.100.0 (build d996c6d)
  - **Framework Version:** 1.102.0
  - **Node.js Version:** v16.0.0
  - **OS               :** MacOS 10.15.7
  - **Language (Version):** Typescript (4.2.4)

### Other

The warning appears to be created [here](https://github.com/aws/aws-cdk/blob/3d9321e816b2e2d1aa381f0b40cd1ff57b0958fb/packages/%40aws-cdk/aws-eks/lib/cluster.ts#L1487), and there doesn't seem to be any logic to check for existing tags.

Resolving aws/aws-cdk#10312 should be sufficient to ensure that warnings about irrelevant subnets don't appear.

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment]
@lucaswilric When running, we don't explicitly query AWS to find the actual state of the subnets. This warning for all imported subnets simply because we have no way of guaranteeing its tagged correctly, so we figured its better to assume its not, then it is. 

Not sure there is anything we can do here apart from removing the warning altogether, which we don't want to.

**Comment by lucaswilric** [comment]
Thanks for the response @iliapolo. My team and I are a little concerned about developing a habit of ignoring warnings, so we'd prefer not to print those warnings if we can manage it.

If checking the actual tags on the subnets isn't feasible, is there a way to suppress those warnings without also suppressing warnings that we should pay attention to?

**Comment by iliapolo** [comment]
@lucaswilric unfortunately there is no way to suppress them. You can convert this issue to a feature request and we will consider addressing it.

**Comment by peterwoodworth** [comment]
Hey @lucaswilric are you interested in creating a feature request out of this issue?

**Comment by lucaswilric** [comment]
Thanks for the prompt @peterwoodworth. I have created feature request #15079.
