### ISSUE TITLE
aws-amazonmq: RabbitMQ broker attrIpAddresses returns nothing

### ISSUE THREAD

**Issue by d-t-bird** [aws/aws-cdk#14736]
Using broker attribute attrIpAddresses on a stack export gives an error in the CloudFormation console, stack update fails to deploy.

### Reproduction Steps

First create a broker with a RabbitMQ multi-AZ cluster deployment.

this.broker = new amazonmq.CfnBroker(this, 'Broker', {
autoMinorVersionUpgrade: false,
brokerName: ${this.stackName}-broker,
engineType: "RABBITMQ",
engineVersion: "3.8.11",
deploymentMode:'CLUSTER_MULTI_AZ',
....etc.

Then attempt to output the ip addresses as an export.

new CfnOutput(this, 'OutputRabbitMQIpAddresses', {
exportName: 'RabbitMQIpAddresses',
value: Fn.join(',', this.broker.attrIpAddresses)
});

### What did you expect to happen?

Expected the Cloudformation stack to complete with a new output, listing the IP Addresses from the RabbitMQ multi-AZ cluster deployment

### What actually happened?

The stack update failed and rolled back, with the following error:

"Cannot export output OutputRabbitMQIpAddresses. Exported values must not be empty or whitespace-only."

### Environment

  -1.103.0
  - 1.103.0
  -v12.18.4
  - Windows
  -TypeScript (3.9.9)

### Other

Stack was being deployed as a stage in a cdk pipeline.

--- 

This is :bug: Bug Report

**Comment by MrArnoldPalmer** [comment]
Can you show the .yml of the template where the output is defined? Also, can you deploy without the cfn output and verify that this attribute is not an empty list in your `Broker` resource? If the attribute is empty, then joining with `,` results in an empty string which causes the error above?

**Comment by d-t-bird** [comment]
Hi @MrArnoldPalmer.  The attribute does seem to be empty.  Just found that CloudFormation doc states the ip addresses to not be applicable for a rabbit broker.  https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-amazonmq-broker.html#aws-resource-amazonmq-broker-return-values.

My plan was to retrieve them in a cdk stack, in order to add dimensions for node metrics.  I can create graphs based on a search expression, but I can't create alarms from cdk without the names of each rabbit node from a cluster deployment.

Should this be a feature request rather than a bug?

**Comment by MrArnoldPalmer** [comment]
@d-t-bird this might be a feature request for cloudformation cause I can't figure out a way to access each instance within a broker and get a name.

Even looking through the sdk for `describeBroker` its not clear how to construct this from the returned values.
