### ISSUE TITLE
‼️ NOTICE: aws-cdk CLI - "Cloud assembly schema version mismatch: Maximum schema version supported is 10.0.0, but found 11.0.0"

### ISSUE THREAD

**Issue by gerroldksky** [aws/aws-cdk#14738]
Please add your +1 👍 to let us know you have encountered this

---

### Status: __IN-PROGRESS__

This is a bug in `npm`  **version 7 only** (`npm` versions 6 and below work fine). See here for details: https://github.com/npm/cli/issues/3196

### Overview:

After upgrading the CDK CLI package (`aws-cdk`) with `npm` version 7, running any CDK command in your CDK application fails with the error `Cloud assembly schema version mismatch: Maximum schema version supported is 10.0.0, but found 11.0.0`.

#### Complete Error Message

```
$ npx cdk ls
This CDK CLI is not compatible with the CDK library used by your application. Please upgrade the CLI to the latest version.
(Cloud assembly schema version mismatch: Maximum schema version supported is 10.0.0, but found 11.0.0)
```

### Workaround:

Please remove the installed `aws-cdk` package, and then install it again:

```shell
$ npm uninstall -g aws-cdk
$ npm install -g aws-cdk
```

------------------------------

# Original opening post

This CDK CLI is not compatible with the CDK library used by your application. Please upgrade the CLI to the latest version.
(Cloud assembly schema version mismatch: Maximum schema version supported is 10.0.0, but found 11.0.0)

aws-cdk version 1.103.0 and 1.104.0 do not work.
aws-cdk version 1.102.0 works fine

### Reproduction Steps

Install aws-cdk 1.103.0 (or 1.104.0)
pip install -r requirements.txt

cdk ls

### What did you expect to happen?

List of stacks displayed

### What actually happened?

"This CDK CLI is not compatible with the CDK library used by your application. Please upgrade the CLI to the latest version.
(Cloud assembly schema version mismatch: Maximum schema version supported is 10.0.0, but found 11.0.0)
"

### Environment

  - **CDK CLI Version  :** 1.104.0 
  - **Framework Version:** 1.103.0 & 1.104.0
  - **Node.js Version:** v16.1.0
  - **OS               : Mac Big Sur
  - **Language (Version):** Python 3.8.7

### Other

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
The error message says:

> Please upgrade the CLI to the latest version.

Have you tried to do this? What commands have you run?

**Comment by rix0rrr** [comment]
Does not reproduce for me:

```
$ npx cdk@1.104.0 init -l=python
$ python3 -m venv .venv
$ source .venv/bin/activate.fish
(.venv)$ pip install -r requirements.txt
(.venv)$ npx cdk@1.104.0 ls
PythonStack
```

**Comment by hoegertn** [comment]
Very weird as I saw the error too.

I tried to reproduce using your commands and I observe the following

```bash
(.venv) [hoegertn@MacMini ws-0ec1ae (main)]$ npx cdk@1.104.0 ls
Ws0Ec1AeStack
(.venv) [hoegertn@MacMini ws-0ec1ae (main)]$ npx cdk ls
This CDK CLI is not compatible with the CDK library used by your application. Please upgrade the CLI to the latest version.
(Cloud assembly schema version mismatch: Maximum schema version supported is 10.0.0, but found 11.0.0)
(.venv) [hoegertn@MacMini ws-0ec1ae (main)]$ npx cdk --version
1.104.0 (build 44d3383)
(.venv) [hoegertn@MacMini ws-0ec1ae (main)]$
```

So it works using the fixed version but not without despite it being the same version according to `--version`

**Comment by rix0rrr** [comment]
Huh!

**Comment by rix0rrr** [comment]
Oh well I might know what it is. `npx cdk` happens to use whatever `cdk` it finds on the `$PATH`, if available.

What about:

```
$ npx --ignore-existing cdk ls
```

?

**Comment by hoegertn** [comment]
```
(.venv) [hoegertn@MacMini ws-9fbbac (main)]$ npx cdk@1.104.0 ls
Ws9FbbacStack
(.venv) [hoegertn@MacMini ws-9fbbac (main)]$ npx cdk ls
This CDK CLI is not compatible with the CDK library used by your application. Please upgrade the CLI to the latest version.
(Cloud assembly schema version mismatch: Maximum schema version supported is 10.0.0, but found 11.0.0)
(.venv) [hoegertn@MacMini ws-9fbbac (main)]$ npx --ignore-existing cdk ls
npx: the --ignore-existing argument has been removed.
See `npm help exec` for more information
This CDK CLI is not compatible with the CDK library used by your application. Please upgrade the CLI to the latest version.
(Cloud assembly schema version mismatch: Maximum schema version supported is 10.0.0, but found 11.0.0)
(.venv) [hoegertn@MacMini ws-9fbbac (main)]$ npx cdk version
1.104.0 (build 44d3383)
(.venv) [hoegertn@MacMini ws-9fbbac (main)]$ npx --ignore-existing cdk version
npx: the --ignore-existing argument has been removed.
See `npm help exec` for more information
1.104.0 (build 44d3383)
(.venv) [hoegertn@MacMini ws-9fbbac (main)]$ cdk
bash: cdk: command not found
(.venv) [hoegertn@MacMini ws-9fbbac (main)]$ 
```

**Comment by rix0rrr** [comment]
Hm.

I see what you're saying, but I also see that `npx cdk` does *not* do an npm install (because I don't see the NPM progress bar).

Do you have `cdk` in `../node_modules/.bin` or `../../node_modules/.bin` or something?

If I make sure that `npx cdk` installs something by getting rid of traces of CDK in all kinds of `node_modules` dirs:

```
$ npx cdk ls
[npm install garble here]
PythonStack
```

**Comment by rix0rrr** [comment]
I do have NPM 6 but that feels like it shouldn't matter too much (but who knows)

**Comment by shubham391** [comment]
Related issue: https://github.com/aws/aws-cdk/issues/14710

**Comment by sudhirpandey** [comment]
I running to the same issue 
cdk bootstrap --debug
This CDK CLI is not compatible with the CDK library used by your application. Please upgrade the CLI to the latest version.
(Cloud assembly schema version mismatch: Maximum schema version supported is 9.0.0, but found 11.0.0),

By this post it seems it needs to work as long as cli is in same version with cdk lib, but its failing.

```
cdk --version
1.104.0 (build 44d3383)

pip list |grep aws
aws-cdk.assets                     1.104.0
aws-cdk.aws-apigateway             1.104.0
aws-cdk.aws-applicationautoscaling 1.104.0
aws-cdk.aws-autoscaling-common     1.104.0
aws-cdk.aws-certificatemanager     1.104.0
aws-cdk.aws-cloudformation         1.104.0
aws-cdk.aws-cloudwatch             1.104.0
aws-cdk.aws-codeguruprofiler       1.104.0
aws-cdk.aws-cognito                1.104.0
aws-cdk.aws-dynamodb               1.104.0
aws-cdk.aws-ec2                    1.104.0
aws-cdk.aws-ecr                    1.104.0
aws-cdk.aws-ecr-assets             1.104.0
aws-cdk.aws-efs                    1.104.0
aws-cdk.aws-elasticloadbalancingv2 1.104.0
aws-cdk.aws-events                 1.104.0
aws-cdk.aws-iam                    1.104.0
aws-cdk.aws-kinesis                1.104.0
aws-cdk.aws-kms                    1.104.0
aws-cdk.aws-lambda                 1.104.0
aws-cdk.aws-lambda-event-sources   1.104.0
aws-cdk.aws-logs                   1.104.0
aws-cdk.aws-route53                1.104.0
aws-cdk.aws-s3                     1.104.0
aws-cdk.aws-s3-assets              1.104.0
aws-cdk.aws-s3-notifications       1.104.0
aws-cdk.aws-sam                    1.104.0
aws-cdk.aws-secretsmanager         1.104.0
aws-cdk.aws-signer                 1.104.0
aws-cdk.aws-sns                    1.104.0
aws-cdk.aws-sns-subscriptions      1.104.0
aws-cdk.aws-sqs                    1.104.0
aws-cdk.aws-ssm                    1.104.0
aws-cdk.cloud-assembly-schema      1.104.0
aws-cdk.core                       1.104.0
aws-cdk.custom-resources           1.104.0
aws-cdk.cx-api                     1.104.0
aws-cdk.region-info                1.104.0

node --version
v15.5.1

npm --version
7.13.0

````

**Comment by rix0rrr** [comment]
I really need someone who has this problem to help me out because I can't seem to reproduce it. Can you do the following:

```
$ which cdk
(note down the path, exclude the 'bin/cdk' part)

$ cat /path/to/cdk/package.json
$ cat /path/to/cdk/node_modules/@aws-cdk/cloud-assembly-schema/package.json
$ cat /path/to/cdk/node_modules/@aws-cdk/cloud-assembly-schema/schema/cloud-assembly.version.json 
```

It might be that `.../node_modules/@aws-cdk/cloud-assembly-schema` is not found IN the `/path/to/cdk` directory, but somewhere up the tree from there. So for example, it could either be in:

```
/usr/local/lib/node_modules/aws-cdk/node_modules/@aws-cdk/cloud-assembly-schema/schema/cloud-assembly.version.json 
# or in
/usr/local/lib//node_modules/@aws-cdk/cloud-assembly-schema/schema/cloud-assembly.version.json 
```

**Comment by gerroldksky** [comment]
Looks like a few references to the older/previous 102 version in the cloud-assembly-schema/package.json

**Comment by rix0rrr** [comment]
Thanks a lot @gerroldksky, that is very helpful. Although even more confusing, because it don't understand why `npm` would install version `1.102` of `cloud-assembly-schema`, even though all the references clearly say `1.104`.

**Comment by rix0rrr** [comment]
Best I can recommend at this moment is trying:

```
$ npm uninstall -g aws-cdk
$ npm install -g aws-cdk
```

And seeing if that fixes it.

NPM left your install in an inconsistent state, and without being able to reproduce it it's hard to say why.

**Comment by hoegertn** [comment]
In my last comment, you can see that I do not have a global cdk at all and I still get this error. I will search for other assembly packages on my machine.

**Comment by binh-nguyen-exwzd** [comment]
> Best I can recommend at this moment is trying:
> 
> ```
> $ npm uninstall -g aws-cdk
> $ npm install -g aws-cdk
> ```
> 
> And seeing if that fixes it.
> 
> NPM left your install in an inconsistent state, and without being able to reproduce it it's hard to say why.

Thank you so much. I suffered a lot until follow your guide by uninstalling/installing.

**Comment by gerroldksky** [comment]
Yes, a complete aws-cdk uninstall and re-install has also fixed it for me.
Something is/got 'broken' in the upgrade process. But happy enough that a simple uninstall/install fixed it. A bit of a 'face-palm' moment that I did not try this myself.....

Thanks to all on this thread for your prompt support, patience and help!

**Comment by rix0rrr** [comment]
> I do not have a global cdk at all and I still get this error.

Not global, no, but it might be in a parent directory. `npx` would still find it that place.

**Comment by hoegertn** [comment]
I have no idea why but I could track it down to the npx folder containing cdk 1.105 but the node_modules inside where of version 1.102

Removing the npx cache solved it now.

**Comment by rix0rrr** [comment]
Hm, that's weird by itself because the `npx` directory should be removed automatically after running the program (i.e., it shouldn't persist and so shouldn't affect future runs).

What's even more interesting is that apparently you were stuck on `1.102` as well, same as for the OP. I wonder if there was something wrong with that version...

But at the same time, I tried installing `1.102` and then upgrading to `1.104`, same as OP, and that worked fine for me.

This is so frustrating 🤬

**Comment by hoegertn** [comment]
And I had this with 103, 104, and 105 until I removed the folder manually now.

**Comment by rix0rrr** [comment]
I wonder if it's the `npm-shrinkwrap.json` or not. But I'm not sure how to confirm/disconfirm that hypothesis easily...

**Comment by skinny85** [comment]
OK, I was playing with this all day, and, while I'm not sure why this happens, I have been able to consistently reproduce this error with NPM 7. It manifests itself with local installs the same as with global installs.

This is a sequence in a CDK project created with `1.105.0` that _doesn't_ have a `package.json` itself (for example, a Java/Python CDK project):

```
$ npm --version 
7.13.0

$ npm install aws-cdk@1.98.0 
added 201 packages, and audited 202 packages in 12s
found 0 vulnerabilities

$ npx cdk synth 
This CDK CLI is not compatible with the CDK library used by your application. Please upgrade the CLI to the latest version.
(Cloud assembly schema version mismatch: Maximum schema version supported is 9.0.0, but found 11.0.0)

$ npm install aws-cdk
added 8 packages, removed 36 packages, changed 14 packages, and audited 181 packages in 9s
found 0 vulnerabilities

$ npx cdk synth 
This CDK CLI is not compatible with the CDK library used by your application. Please upgrade the CLI to the latest version.
(Cloud assembly schema version mismatch: Maximum schema version supported is 9.0.0, but found 11.0.0)

$ cat node_modules/aws-cdk/node_modules/\@aws-cdk/cx-api/package.json 
{
  "name": "@aws-cdk/cx-api",
  "version": "1.98.0",
  "description": "Cloud executable protocol",
  "main": "lib/index.js",
  "types": "lib/index.d.ts",
  "jsii": {
    "outdir": "dist",
    "targets": {
      "java": {
        "package": "software.amazon.awscdk.cxapi",
        "maven": {
          "groupId": "software.amazon.awscdk",
          "artifactId": "cdk-cx-api"
        }
      },
      "dotnet": {
        "namespace": "Amazon.CDK.CXAPI",
        "packageId": "Amazon.CDK.CXAPI",
        "iconUrl": "https://raw.githubusercontent.com/aws/aws-cdk/master/logo/default-256-dark.png"
      },
      "python": {
        "distName": "aws-cdk.cx-api",
        "module": "aws_cdk.cx_api",
        "classifiers": [
          "Framework :: AWS CDK",
          "Framework :: AWS CDK :: 1"
        ]
      }
    },
    "projectReferences": true,
    "metadata": {
      "jsii": {
        "rosetta": {
          "strict": true
        }
      }
    }
  },
  "scripts": {
    "build": "cdk-build",
    "watch": "cdk-watch",
    "lint": "cdk-lint",
    "test": "cdk-test",
    "pkglint": "pkglint -f",
    "package": "cdk-package",
    "awslint": "cdk-awslint",
    "build+test+package": "yarn build+test && yarn package",
    "build+test": "yarn build && yarn test",
    "compat": "cdk-compat",
    "rosetta:extract": "yarn --silent jsii-rosetta extract"
  },
  "author": {
    "name": "Amazon Web Services",
    "url": "https://aws.amazon.com",
    "organization": true
  },
  "dependencies": {
    "@aws-cdk/cloud-assembly-schema": "1.98.0",
    "semver": "^7.3.5"
  },
  "peerDependencies": {
    "@aws-cdk/cloud-assembly-schema": "1.98.0"
  },
  "license": "Apache-2.0",
  "devDependencies": {
    "@types/jest": "^26.0.22",
    "@types/mock-fs": "^4.13.0",
    "@types/semver": "^7.3.4",
    "cdk-build-tools": "1.98.0",
    "jest": "^26.6.3",
    "mock-fs": "^4.13.0",
    "pkglint": "1.98.0"
  },
  "repository": {
    "url": "https://github.com/aws/aws-cdk.git",
    "type": "git",
    "directory": "packages/@aws-cdk/cx-api"
  },
  "keywords": [
    "aws",
    "cdk"
  ],
  "homepage": "https://github.com/aws/aws-cdk",
  "bundledDependencies": [
    "semver"
  ],
  "engines": {
    "node": ">= 10.13.0 <13 || >=13.7.0"
  },
  "stability": "stable",
  "maturity": "stable",
  "awslint": {
    "exclude": [
      "props-default-doc:@aws-cdk/cx-api.MetadataEntry.data",
      "docs-public-apis:@aws-cdk/cx-api.CloudArtifact.assembly",
      "docs-public-apis:@aws-cdk/cx-api.CloudArtifact.findMetadataByType",
      "docs-public-apis:@aws-cdk/cx-api.CloudAssembly.stacks",
      "docs-public-apis:@aws-cdk/cx-api.CloudFormationStackArtifact",
      "docs-public-apis:@aws-cdk/cx-api.EnvironmentUtils",
      "docs-public-apis:@aws-cdk/cx-api.EnvironmentUtils.format",
      "docs-public-apis:@aws-cdk/cx-api.EnvironmentUtils.parse",
      "docs-public-apis:@aws-cdk/cx-api.TreeCloudArtifact",
      "docs-public-apis:@aws-cdk/cx-api.TreeCloudArtifact.file",
      "props-default-doc:@aws-cdk/cx-api.ArtifactManifest.dependencies",
      "props-default-doc:@aws-cdk/cx-api.ArtifactManifest.environment",
      "props-default-doc:@aws-cdk/cx-api.ArtifactManifest.metadata",
      "props-default-doc:@aws-cdk/cx-api.ArtifactManifest.properties",
      "docs-public-apis:@aws-cdk/cx-api.AssemblyBuildOptions",
      "props-default-doc:@aws-cdk/cx-api.AssemblyManifest.artifacts",
      "props-default-doc:@aws-cdk/cx-api.AssemblyManifest.missing",
      "props-default-doc:@aws-cdk/cx-api.AssemblyManifest.runtime",
      "props-default-doc:@aws-cdk/cx-api.AvailabilityZonesContextQuery.account",
      "props-default-doc:@aws-cdk/cx-api.AvailabilityZonesContextQuery.region",
      "props-default-doc:@aws-cdk/cx-api.EndpointServiceAvailabilityZonesContextQuery.account",
      "props-default-doc:@aws-cdk/cx-api.EndpointServiceAvailabilityZonesContextQuery.region",
      "props-default-doc:@aws-cdk/cx-api.EndpointServiceAvailabilityZonesContextQuery.serviceName",
      "props-default-doc:@aws-cdk/cx-api.AwsCloudFormationStackProperties.parameters",
      "docs-public-apis:@aws-cdk/cx-api.ContainerImageAssetMetadataEntry",
      "docs-public-apis:@aws-cdk/cx-api.FileAssetMetadataEntry",
      "props-default-doc:@aws-cdk/cx-api.HostedZoneContextQuery.account",
      "props-default-doc:@aws-cdk/cx-api.HostedZoneContextQuery.privateZone",
      "props-default-doc:@aws-cdk/cx-api.HostedZoneContextQuery.region",
      "props-default-doc:@aws-cdk/cx-api.HostedZoneContextQuery.vpcId",
      "docs-public-apis:@aws-cdk/cx-api.CloudArtifact.id",
      "props-default-doc:@aws-cdk/cx-api.MetadataEntry.trace",
      "docs-public-apis:@aws-cdk/cx-api.MetadataEntryResult",
      "props-default-doc:@aws-cdk/cx-api.SSMParameterContextQuery.account",
      "props-default-doc:@aws-cdk/cx-api.SSMParameterContextQuery.parameterName",
      "props-default-doc:@aws-cdk/cx-api.SSMParameterContextQuery.region",
      "docs-public-apis:@aws-cdk/cx-api.SynthesisMessage",
      "docs-public-apis:@aws-cdk/cx-api.SynthesisMessage.entry",
      "docs-public-apis:@aws-cdk/cx-api.SynthesisMessage.id",
      "docs-public-apis:@aws-cdk/cx-api.SynthesisMessage.level",
      "props-default-doc:@aws-cdk/cx-api.VpcContextQuery.account",
      "props-default-doc:@aws-cdk/cx-api.VpcContextQuery.region",
      "props-default-doc:@aws-cdk/cx-api.VpcContextResponse.isolatedSubnetIds",
      "props-default-doc:@aws-cdk/cx-api.VpcContextResponse.isolatedSubnetNames",
      "props-default-doc:@aws-cdk/cx-api.VpcContextResponse.isolatedSubnetRouteTableIds",
      "props-default-doc:@aws-cdk/cx-api.VpcContextResponse.privateSubnetIds",
      "props-default-doc:@aws-cdk/cx-api.VpcContextResponse.privateSubnetNames",
      "props-default-doc:@aws-cdk/cx-api.VpcContextResponse.privateSubnetRouteTableIds",
      "props-default-doc:@aws-cdk/cx-api.VpcContextResponse.publicSubnetIds",
      "props-default-doc:@aws-cdk/cx-api.VpcContextResponse.publicSubnetNames",
      "props-default-doc:@aws-cdk/cx-api.VpcContextResponse.publicSubnetRouteTableIds",
      "props-default-doc:@aws-cdk/cx-api.VpcContextResponse.vpnGatewayId",
      "docs-public-apis:@aws-cdk/cx-api.ArtifactType.NONE",
      "docs-public-apis:@aws-cdk/cx-api.SynthesisMessageLevel",
      "docs-public-apis:@aws-cdk/cx-api.SynthesisMessageLevel.INFO",
      "docs-public-apis:@aws-cdk/cx-api.SynthesisMessageLevel.WARNING",
      "docs-public-apis:@aws-cdk/cx-api.SynthesisMessageLevel.ERROR"
    ]
  },
  "awscdkio": {
    "announce": false
  },
  "cdk-build": {
    "jest": true
  },
  "publishConfig": {
    "tag": "latest"
  }
}
```

Clearly, the `@aws-cdk/cx-api` package stays at `1.98.0`, instead of being updated to `1.105.0`.

**Comment by skinny85** [comment]
This does not happen with NPM 6:

```
$ npm --version 
6.14.4

$ npm install aws-cdk@1.98.0 
npm WARN saveError ENOENT: no such file or directory, open '/Users/adamruka/workplace/cdk/on-call/cli-cx-api-bug/java-example-app/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/Users/adamruka/workplace/cdk/on-call/cli-cx-api-bug/java-example-app/package.json'
npm WARN java-example-app No description
npm WARN java-example-app No repository field.
npm WARN java-example-app No README data
npm WARN java-example-app No license field.

+ aws-cdk@1.98.0
added 201 packages from 189 contributors and audited 201 packages in 27.957s

17 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

$ npx cdk synth 
This CDK CLI is not compatible with the CDK library used by your application. Please upgrade the CLI to the latest version.
(Cloud assembly schema version mismatch: Maximum schema version supported is 9.0.0, but found 11.0.0)

$ npm install aws-cdk
> aws-sdk@2.903.0 postinstall /Users/adamruka/workplace/cdk/on-call/cli-cx-api-bug/java-example-app/node_modules/aws-cdk/node_modules/aws-sdk
> node scripts/check-node-version.js

npm WARN saveError ENOENT: no such file or directory, open '/Users/adamruka/workplace/cdk/on-call/cli-cx-api-bug/java-example-app/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/adamruka/workplace/cdk/on-call/cli-cx-api-bug/java-example-app/package.json'
npm WARN java-example-app No description
npm WARN java-example-app No repository field.
npm WARN java-example-app No README data
npm WARN java-example-app No license field.

+ aws-cdk@1.105.0
added 8 packages from 36 contributors, removed 29 packages, updated 20 packages and audited 180 packages in 27.184s

3 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

$ npx cdk synth 
Resources:
  JavaExampleAppQueue3527C576:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 300
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: JavaExampleAppStack/JavaExampleAppQueue/Resource
  JavaExampleAppQueuePolicy971E1824:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Statement:
          - Action: sqs:SendMessage
            Condition:
              ArnEquals:
                aws:SourceArn:
                  Ref: JavaExampleAppTopic433D6DC3
            Effect: Allow
            Principal:
              Service: sns.amazonaws.com
            Resource:
              Fn::GetAtt:
                - JavaExampleAppQueue3527C576
                - Arn
        Version: "2012-10-17"
      Queues:
        - Ref: JavaExampleAppQueue3527C576
    Metadata:
      aws:cdk:path: JavaExampleAppStack/JavaExampleAppQueue/Policy/Resource
  JavaExampleAppQueueJavaExampleAppStackJavaExampleAppTopic06BE8912B2D69E27:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sqs
      TopicArn:
        Ref: JavaExampleAppTopic433D6DC3
      Endpoint:
        Fn::GetAtt:
          - JavaExampleAppQueue3527C576
          - Arn
    Metadata:
      aws:cdk:path: JavaExampleAppStack/JavaExampleAppQueue/JavaExampleAppStackJavaExampleAppTopic06BE8912/Resource
  JavaExampleAppTopic433D6DC3:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: My First Topic Yeah
    Metadata:
      aws:cdk:path: JavaExampleAppStack/JavaExampleAppTopic/Resource
```

**Comment by skinny85** [comment]
Looks like someone already reported this to NPM: https://github.com/npm/cli/issues/3196

**Comment by rix0rrr** [comment]
I can only reproduce this if I install directly from `npmjs.com` using NPM 7. If I install from an alternative NPM repository like Verdaccio or CodeArtifact, the behavior doesn't reproduce.

**Comment by TingDaoK** [comment]
I have the same issue. I checked the aws-cdk version (by `cdk --version`) is the same as the one in my package.json and tried to install the latest version, but the error message is always like `pleas upgrade CDK CLI`. I resolved the error by `npm ci`. I guess some node modules are out of sync or something.

**Comment by nirvana124** [comment]
I am facing this issue on version 1.106.1 as well as 1.108.1.
I have tried uninstalling, used npm version 6.14.4 and 7.17.0 but still getting below error :
This CDK CLI is not compatible with the CDK library used by your application. Please upgrade the CLI to the latest version.
(Cloud assembly schema version mismatch: Maximum schema version supported is 11.0.0, but found 12.0.0)

**Comment by nirvana124** [comment]
After a lot of trials it is working for me for below settings: 
cdk lib version: 1.108.1
cdk cli version: 1.109.0
npm version: 7.17.0
node version: 14.17.1

**Comment by eXpire163** [comment]
Hi, i was using cdk in a WSL and i got the same error:

`which cdk ` pointed to /mnt/c/Users/xxx/AppData/Roaming/npm/cdk
removed it there and then it pointed to /usr/local/bin/cdk and everything was OK

**Comment by Nicko-13** [comment]
The issue is still persisting with CDK version 1.116.0. `npm install -g aws-cdk@1.116.0` still install version 1.113.0.

**Comment by ishanjain28** [comment]
From the logs here this looks like a genuine problem but I want to present another data point.
Please review your config. Make sure you have not done something like what I had done in my project. 

```
{
aws-cdk: "1.108.0",
"@aws-cdk/xyz": "^1.108.0"
...more cdk dependencies 
}
```

It'll keep working perfectly fine until one day all the other dependencies are updated and `aws-cdk` is not compatible anymore and then you get this error.

**Comment by ganeshnj** [comment]
Encountered similar issue when deploying to AppRunner

```
This CDK CLI is not compatible with the CDK library used by your application. Please upgrade the CLI to the latest version.

(Cloud assembly schema version mismatch: Maximum schema version supported is 11.0.0, but found 13.0.
```

**Comment by jpSimkins** [comment]
For me, the issue was that I had my `dependencies` using version: `1.124.0` but my `devDependencies` were using `1.117.0`. Changing that fixed it for me.

**Comment by m1mohamad** [comment]
I uninstalled it then did the following but still see the failure without npx: 

$ npm install -g aws-cdk

added 198 packages, and audited 199 packages in 10s

found 0 vulnerabilities
$ cdk synth
This CDK CLI is not compatible with the CDK library used by your application. Please upgrade the CLI to the latest version.
(Cloud assembly schema version mismatch: Maximum schema version supported is 14.0.0, but found 15.0.0)
$ npx cdk synth
Resources:
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/zPUMzQ21TNQdEgsL9ZNTsnWT84vStWrDi5JTM7Wcc7PKy4pKk0u0XFOywtKLc4vLUpOrdXJy09J1csq1i8zNAPq1jNUzCrOzNQtKs0rycxN1QuC0ADLxBKHWQAAAA==
    Metadata:
      aws:cdk:path: CdkappStack/CDKMetadata/Default

$ npm --version
8.2.0

**Comment by antonrogo1** [comment]
Hi recently began experiencing similar issue:
This CDK CLI is not compatible with the CDK library used by your application. Please upgrade the CLI to the latest version.
(Cloud assembly schema version mismatch: Maximum schema version supported is 15.0.0, but found 16.0.0)

Running commands
npm uninstall -g aws-cdk
npm install -g aws-cdk
didn't do the trick.

cdk --version
2.5.0 (build 0951122)

node --version
v12.22.5

**Comment by MinCheTsai** [comment]
> I'm getting the same issue too on a new stack, and reinstalling aws-cdk also doesn't fix it.

same problem

cdk --version
2.2.0 (build 4f5c27c)

node --version
v14.18.1

npm --version
6.14.15

**Comment by jezxube** [comment]
I'm getting the same issue using CodeBuild:
```

[Container] 2022/01/12 08:49:52 Running command npm install -g aws-cdk
/usr/local/bin/cdk -> /usr/local/lib/node_modules/aws-cdk/bin/cdk
 + aws-cdk@2.5.0
added 213 packages from 233 contributors in 6.632s
 
[Container] 2022/01/12 08:49:59 Running command cdk version
2.5.0 (build 0951122)

[Container] 2022/01/12 08:50:02 Running command npx cdk synth

...

This CDK CLI is not compatible with the CDK library used by your application. Please upgrade the CLI to the latest version.
(Cloud assembly schema version mismatch: Maximum schema version supported is 15.0.0, but found 16.0.0)
```

**Comment by gshpychka** [comment]
This is because schema version 16.0.0 was introduced in CDK 1.139. CDKv2 does not support it yet as of 2.5.0.

Solutions:
1. Use the 1.139 version of the CDK CLI instead of the latest v2.
2. Downgrade your construct modules to 1.138
3. Switch your construct modules to CDKv2.

**Comment by jezxube** [comment]
> This is because schema version 16.0.0 was introduced in CDK 1.139. CDKv2 does not support it yet as of 2.5.0.
> 
> Solutions:
> 
> 1. Use the 1.139 version of the CDK CLI instead of the latest v2.
> 2. Downgrade your construct modules to 1.138
> 3. Switch your construct modules to CDKv2.

Solution 1 worked for me - thanks!

**Comment by ahileseverquote** [comment]
> This is because schema version 16.0.0 was introduced in CDK 1.139. CDKv2 does not support it yet as of 2.5.0.
> 
> Solutions:
> 
> 1. Use the 1.139 version of the CDK CLI instead of the latest v2.
> 2. Downgrade your construct modules to 1.138
> 3. Switch your construct modules to CDKv2.

Thanks @gshpychka - Solutions 1 and 2 have helped unblock my team.

**Comment by OrGamliel8** [comment]
Solution 1 worked for me too !

**Comment by skinny85** [comment]
Related issue: https://github.com/aws/aws-cdk/issues/18370.

**Comment by addihorowitz** [comment]
This issue was resolved by #18370.

**Comment by Kmelow** [comment]
Hello,

This is for future reference.
I'm using CDK to deploy a pipeline stack in one account, then have that account (`deploy-account`) deploy on my behalf to other accounts (`dev`, `prod`, etc.)

I'm using TS for the CDK and have installed `aws-cdk`.
node version: `v16.14.0`
npm version: v8.3.1`
cdk --version: `v2.45.0`

Locally, everything was fine when doing `cdk synth` and `cdk ls`.

When I deploied to my `deploy-account` I was exevuting `npx cdk synth` as described [in the docs](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.pipelines-readme.html#at-a-glance).
Then I was getting this error.

I tried:

```bash
npm uninstall -g aws-cdk
npm install -g aws-cdk
```

As suggested, but it didn't worked for me.

What I did was:

```bash
# Updated the lib in my project
npm i -D aws-cdk@latest

# Reinstalling all packages
rm -fr node_modules package-lock.json cdk.out

# Reinstalling
npm i
```

After, when I redeployied it worked 🤷‍♂️

Hope it helps,

**Comment by IshanTaldekar** [comment]
I upgraded my node version to the latest - v20.10.0 (with npm 10.2.3). Then, reinstalled the aws-cdk. Updated package.json to use the latest `aws-cdk` and `aws-cdk-lib`. This fixed my issue.
```
> npm --version
10.2.3
> npx cdk --version
2.114.1 (build 02bbb1d)
```

I am using hte following dependencies:
```
  "devDependencies": {
    "@types/jest": "^29.5.5",
    "@types/node": "20.7.1",
    "jest": "^29.7.0",
    "ts-jest": "^29.1.1",
    "aws-cdk": "2.114.1",
    "ts-node": "^10.9.1",
    "typescript": "~5.2.2"
  },
  "dependencies": {
    "aws-cdk-lib": "2.114.1",
    "constructs": "10.3.0",
    "source-map-support": "^0.5.21"
  }
```

**Comment by kaspar-p** [comment]
Upgrading the package is not a solution. This will happen again.

Why does `aws-cdk` take a dependency on `aws-cdk-lib` for Cloud Assembly versions, but not declare that dependency in `package.json` as a peer dependency? If a version of `aws-cdk` only supports generating up to version 10, but the library needs version 11, then there should be a dependency relationship between the two.

**Comment by KumarHalder** [comment]
Might be helpful for some people, with addition to others, try 

```npm upgrade```

**Comment by celso-alexandre** [comment]
I've deleted the cdk.context.json and this error disappeared. Seems to be related to me upgrading aws-cdk and aws-cdk-lib

**Comment by juliogarces** [comment]
Similar issue happens to me during AWS CodePipeline execution
```
Running command cdk-assets -p cdk.out/my-stack.assets.json publish
Error: Cannot read asset manifest 'cdk.out/my-stack.assets.json': Cloud assembly schema version mismatch: Maximum schema version supported is 44.x.x, but found 45.0.0
```
I tried downgrading aws-cdk-lib from ^2.204.0 to an older version without luck.

What works for me was upgrading the node version in CodeBuild from 20.x to 22.x
`"runtime-versions": { "nodejs": "22.x" }`

Hope this helps others in the future :)
