### ISSUE TITLE
CloudFront: support for Lambda function associations

### ISSUE THREAD

**Issue by rix0rrr** [aws/aws-cdk#1474]
Implicitly requested on StackOverflow:

https://stackoverflow.com/questions/53990910/aws-cdk-associate-lambda-function-with-cloudfront-web-distribution

Right now the only way to do this is with CloudFormation overrides.

**Comment by btakita** [comment]
Has there been any progress on this? I'm running into this issue as well?

**Comment by btakita** [comment]
It also looks like the solution to https://stackoverflow.com/questions/53990910/aws-cdk-associate-lambda-function-with-cloudfront-web-distribution is out of date, as I'm getting an error:

`Lambda@Edge cannot retrieve the specified Lambda function. Update the IAM policy to add pe
rmission: lambda:GetFunction for resource: arn:aws:lambda:us-east-1:rest-of-arn:2 and try again. (Service: AmazonCloudFront; Status Code: 400; Error Code: InvalidLambdaFunctionAssociation; Request ID: uuid)

**Comment by omnigrok** [comment]
It looks like maybe it's there now? Does [this](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cloudfront.Behavior.html#lambdafunctionassociations-span-class-api-icon-api-icon-experimental-title-this-api-element-is-experimental-it-may-change-without-notice-span) work as documented?

**Comment by btakita** [comment]
I tried adding but got the error:

```typescript
		const distribution = new cloudfront.CloudFrontWebDistribution(this,
			`SiteDistribution`, {
				aliasConfiguration: {
					acmCertRef: certificateArn,
					names: [siteDomain],
					sslMethod: cloudfront.SSLMethod.SNI,
					securityPolicy: cloudfront.SecurityPolicyProtocol.TLS_V1_1_2016,
				},
				originConfigs: [
					{
						customOriginSource: {
							domainName:
								api.url.replace('https://', '')
									.split('/')[0]
						},
						// s3OriginSource: {
						// 	s3BucketSource: siteBucket
						// },
						behaviors: [{
							isDefaultBehavior: true,
							lambdaFunctionAssociations: [{
								eventType: 'origin-response',
								lambdaFunction: web_version
							} as cloudfront.LambdaFunctionAssociation]
						}],
					}
				],
			})
```

```
502 ERROR
The request could not be satisfied.
The Lambda function returned an invalid entry in the headers object: Each header entry in the headers object must be an array. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner. 
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation. 
```

**Comment by eladb** [comment]
This is supported now

**Comment by dmisdm** [comment]
> This is supported now

Awesome! Do you mind linking resources that explain how to do this? Maybe then people who stumble upon this thread will save time :)

**Comment by thekevinbrown** [comment]
Here's an example: https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-cloudfront/test/integ.cloudfront-lambda-association.ts

**Comment by junaid2314** [comment]
##### web browser response ###
502 ERROR
The request could not be satisfied.
The Lambda function returned an invalid entry in the headers object: Each header entry in the headers object must be an array. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner

.### logs from cloudfront ####
(bhlaGH_WuVUym_0z9-ujMAjRf1CDHLjgHcGBGIkGcHnnVQ9ljKMfww==) ERROR Validation error: The Lambda function returned an invalid entry in the headers object, each header entry in the headers object must be an array, header : x-powered-by is not an array.

**Comment by albanx** [comment]
I am getting the same  error

**Comment by alexter42** [comment]
Has anyone solved this error?


`The Lambda function returned an invalid entry in the headers object: Each header entry in the headers object must be an array. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.. `

**Comment by uglow** [comment]
@thekevinbrown The example you provided does not relate to the original issue, as it uses a _new_ CF distribution, rather than an_ **existing** CF Distribution. 

@eladb Can you provide an example of how CDK supports this, please?
