### ISSUE TITLE
(ec2): InstanceSize enum does not support 3XLARGE

### ISSUE THREAD

**Issue by shamelesscookie** [aws/aws-cdk#14746]
The `ec2.InstanceSize` enum does not provide a value for 3xlarge instances. This is a valid option for some instances such as the [z1d.3xlarge](https://aws.amazon.com/ec2/instance-types/z1d/)

### Reproduction Steps

Attempt to describe a `z1d.3xlarge` instance using the `ec2.InstanceType.of()` static method. You cannot. 

### What did you expect to happen?

I expect the `ec2.InstanceSize` enum to provide a value `XLARGE3` which evaluates to the string `3xlarge`

### What actually happened?

I am unable to create z1d.3xlarge instances with CDK

### Environment

  - **CDK CLI Version  :** 1.104.0
  - **Framework Version:** 1.104.0
  - **Node.js Version:** 14.17.0
  - **OS               :** macOS BigSur 11.3.1
  - **Language (Version):** Python 3.9.5

--- 

This is :bug: Bug Report

**Comment by peterwoodworth** [comment]
@rix0rrr could there be some way to automatically support all the types listed [here?](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-instancetype)
