### ISSUE TITLE
(eks): Kubernetes 1.20 support

### ISSUE THREAD

**Issue by kirintwn** [aws/aws-cdk#14756]
Allow user to select Kubernetes version 1.20

https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-1.20

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by kirintwn** [comment]
Hey @iliapolo , I have already submit a PR 8 days ago, thanks.

**Comment by shubham391** [comment]
@iliapolo Thank you providing the workaround.
