### ISSUE TITLE
(AWS-Route53): Check exists of a HostedZone by using fromLookUp

### ISSUE THREAD

**Issue by Fitmavincent** [aws/aws-cdk#14755]
### The Question
How do I utilise a error handling or try catch block to do a exist check of a resource. 

```ts
let zone;
try {
  zone = HostedZone.fromLookup(scope, `${domainName}LookUpHostedZone`, {
    domainName: domainName
  });      
} catch (error) {
  zone = new PublicHostedZone(scope, `${domainName}HostedZone`, {
    zoneName: domainName
  });
}
```

the fromLookup methods fail immediately and what's the recommendation of performing a try catch block for operation like this? 

### Environment

  - **CDK CLI Version:** 1.102.0
  - **Module Version:** aws-route53
  - **Node.js Version:** 16.0.0
  - **OS:** all
  - **Language (Version):** Typescript

### Other information

Similar problems for other AWS resources: 
[How to check if a custom VPC already exist using AWS CDK?](https://stackoverflow.com/questions/67026214/how-to-check-if-a-custom-vpc-already-exist-using-aws-cdk)

**Comment by NGL321** [comment]
Hey @Fitmavincent,

The best way to do this is to use the SDK to try to get the HostedZone. This way the existence of the resource is determined not during deploy time but during synth. Additionally, this means that no extraneous Cloudformation actions are taken.

This is our standard method (something I have used a few times). It should look something like the below:
``` ts
var AWS = require('aws-sdk');
AWS.config.update({region: 'REGION'});
var route53 = new AWS.Route53({apiVersion: '2016-11-15'});

let zone;
let params = {
	Id: 'XXXX'
};

route53.getHostedZone(params, function(err, data) {
  if (err) {
	zone = new PublicHostedZone(scope, `${domainName}HostedZone`, {
    	zoneName: domainName
	});
  } else {
    console.log("Zone Exists");
  }
});
```

I hope that this helps!

😸 😷
