### ISSUE TITLE
(aws-lambda-nodejs): support pnpm

### ISSUE THREAD

**Issue by donaldpipowitch** [aws/aws-cdk#14757]
`aws-lambda-nodejs` currently only supports npm and yarn, but it would be nice to also support pnpm.

E.g. see https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-lambda-nodejs/lib/function.ts#L55.

### Use Case

pnpm is a powerful and fast alternative dependency manager in the Node ecosystem - with a growing popularity.

### Proposed Solution

E.g. `depsLockFilePath` should also support `pnpm-lock.yaml`.

If you don't want to support pnpm it would be nice to get some hint about this as soon as possible (- currently it fails during deployment).

(Stupid question... I just looked at the source code and it looks like `depsLockFilePath` isn't really used for something meaningful - at least nothing lock file specific, besides a small yarn/npm difference check. It's more used to get the project path. Maybe two dedicated settings `projectPath` and `packageManager` would be more useful?)

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by jogold** [comment]
Hey @donaldpipowitch, I think we can easily add support for pnpm after #14739

**Comment by donaldpipowitch** [comment]
Cool, thank you!
