### ISSUE TITLE
(stepfunctions-tasks): support Context parameters in EvaluateExpression

### ISSUE THREAD

**Issue by iOnline247** [aws/aws-cdk#14777]
Using Context parameters within the `expression`, the lambda doesn't fire and creates this error:

```js
{
  "error": "States.Runtime",
  "cause": "An error occurred while executing the state 'Seed Exeuction Id' (entered at the event id #9). The JSONPath '$.Execution.Id' specified for the field '$.Execution.Id.$' could not be found in the input '{\"id\": \"export.csv-ff3e3c7c-9a6c-494d-9eaa-4277235b3307\", \"timestamp\": \"2021-05-19T02:24:47.644Z\", \"source\": \"Export\", \"data\": {\"exportType\": \"csv\", \"entity\": \"test\", \"s3\": {\"bucketName\": \"etl\", \"prefix\": \"exports/\", \"key\": \"exports/test/export.csv\"}}}'"
}
```

### Reproduction Steps

Add this to a SFN chain as described in the [docs as a string within a string](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-stepfunctions-tasks-readme.html#evaluate-expression).

```
    const getExecutionId = new EvaluateExpression(scope, 'Get Exeuction Id', {
        // Almost works... Passes executionId, but it's not wrapped in quotes, so `eval` within the lambda fails.
        // expression: JsonPath.stringAt('$$.Execution.Id'),
        expression: '`${$$.Execution.Id}`',
        resultPath: '$.AWS_STEP_FUNCTIONS_STARTED_BY_EXECUTION_ID',
    });
```

### What did you expect to happen?

I would like the Context parameters to be able to parse correctly and put onto the input object.

### What actually happened?

A States.Runtime error occurred on the lambda and the SFN failed.

### Environment

  - **CDK CLI Version  : 1.103.0
  - **Framework Version: 1.103.0
  - **Node.js Version: v14.0.0 
  - **OS               : Windows
  - **Language (Version): TypeScript (3.8.3) 

--- 

This is :bug: Bug Report

**Comment by BenChaimberg** [comment]
The JSON path lookup functionality needs to be updated to match either one or two $ at the beginning of beginning of the path: https://github.com/aws/aws-cdk/blob/7bc6c6eb14ee73c490caa649aeff509e34eb2c52/packages/%40aws-cdk/aws-stepfunctions-tasks/lib/evaluate-expression.ts#L73

Workaround: create [a Pass state](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-stepfunctions.Pass.html) that transfers the Context value to a value in the state, then refer to that path in the EvaluateExpression

**Comment by BenChaimberg** [comment]
I am unassigning myself and marking this issue as `p2`, which means that we are unable to work on this immediately.

We use +1s to help prioritize our work, and are happy to reevaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://join.slack.com/t/cdk-dev/shared_invite/zt-mso6p56d-qJp7SOTBvMaQuDrx7R2wHg) to solicit support for reprioritization. Please feel free to work on this issue yourself and request my review if you submit a PR or would like design help! See [CONTRIBUTING.md](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) for guidelines.
