### ISSUE TITLE
(aws-elasticsearch): Can't set up r6gd with instance type storage

### ISSUE THREAD

**Issue by ofirnk** [aws/aws-cdk#14773]
### Reproduction Steps

```
        const domain = new Domain(this, "Resource" + domainName, {
            domainName,
            version: ElasticsearchVersion.of("7.9"),
            capacity: {
                dataNodeInstanceType: "r6gd.large.elasticsearch",
                dataNodes: this.isMainState() ? 3 : 1
            },
            ...
        });

```

### Error I get:

```
Error: EBS volumes are required when using instance types other than r3 or i3.
    at new Domain (/home/circleci/repo/node_modules/@aws-cdk/aws-elasticsearch/lib/domain.js:589:19)
    at StateStack.addElasticSearch (/home/circleci/repo/state/template.js:134:24)
    at new StateStack (/home/circleci/repo/state/template.js:30:14)
    at /home/circleci/repo/cdkapp.js:31:5
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

### Fix:

Here:
https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-elasticsearch/lib/domain.ts#L1475
![image](https://user-images.githubusercontent.com/8449713/119338605-e0f2ee00-bc98-11eb-8549-468b2db9c5f2.png)

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment]
@ofirnk Thanks for reporting this. Looks our validation is indeed out of place according to the [pricing page](https://aws.amazon.com/elasticsearch-service/pricing/)

I am unassigning and marking this issue as `p2`, which means that we are unable to work on this immediately.

However, a contribution is more than welcome.
