### ISSUE TITLE
(cli): `cdk init` produces a git repository with a `master` branch

### ISSUE THREAD

**Issue by kellertk** [aws/aws-cdk#14786]
Currently, running `cdk init` produces a git repository with a `master` branch. This may be undesirable. Instead, the CDK could default to creating a git repository with a different branch name.

This is in https://github.com/aws/aws-cdk/blob/6179ac16f2fcab5bf5e03a3629db281018d7585b/packages/aws-cdk/lib/init.ts#L288

### Proposed Solution

Since version 2.28.0, git has included functionality to [specify the default branch name](https://git-scm.com/docs/git-init#Documentation/git-init.txt--bltbranch-namegt) on repository initialization. Using that approach would mean that CDK depends on git 2.28.0, which was only released in July 2020. Some customers may be unable to update to this version because their operating system doesn't provide packages that new (for example, Debian). This seems to be too exclusionary.

Instead, the CDK would need to implement some logic:
* Has the customer configured a default branch name via the `init.defaultBranch` git configuration variable? If so, use that branch name and initialize with `git init`.
* Is the git version >= 2.28.0? If so, initialize the repository using `git init -b main`.
* Is the git version < 2.28.0 and the default branch set to the git default? Initialize with `git init` and then `git branch -m master main`

### Other

I'm marking this as a potential breaking change because it is a change in past behavior. Documentation and scripts (3P or otherwise) that relies on the branch being named `master` might be out of date.

* [X] :wave: I may be able to implement this feature request
* [X] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
Good point, and you're right, bothersomely complicated implementation. But it'll have to do, I suppose.
