### ISSUE TITLE
Support secret for ecs fargate task definition

### ISSUE THREAD

**Issue by mouyigang** [aws/aws-cdk#1478]
I couldn't find a way to specify secret for task definition like this:

https://docs.aws.amazon.com/AmazonECS/latest/developerguide/specifying-sensitive-data.html

Will this be supported?

Thanks,
Andy

**Comment by rix0rrr** [comment]
It will be at some point, but as you correctly noted it isn't right now.

You can use the [CloudFormation layer override mechanism](https://awslabs.github.io/aws-cdk/aws-construct-lib.html#access-the-aws-cloudformation-layer) to access CloudFormation capabilities that aren't exposed in our classes right now.

**Comment by BDQ** [comment]
I looked into this, but it appear the `secrets` key isn't supported by Cloudformation yet, as per: 

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-containerdefinitions.html

So there's nothing that can be done via CDK until that's available?

**Comment by rix0rrr** [comment]
Oh in that case, yes, it needs to be available in CloudFormation first.

**Comment by mouyigang** [comment]
Not sure if console actually work it out without cloudformation or not, but it support secret:
<img width="789" alt="screen shot 2019-01-04 at 15 09 46" src="https://user-images.githubusercontent.com/1716495/50694904-07b21a80-1033-11e9-8001-7c0c04ee95b1.png">

**Comment by cynicaljoy** [comment]
The request to support secrets from CloudFormation is being tracked on the containers roadmap: https://github.com/aws/containers-roadmap/issues/97

**Comment by ScottBrenner** [comment]
CloudFormation added support for `secrets` in ECS task definitions! https://github.com/aws/containers-roadmap/issues/97#issuecomment-501953048
