### ISSUE TITLE
(iam): Support passing a policy to .grantRead()

### ISSUE THREAD

**Issue by adam-nielsen** [aws/aws-cdk#14790]
I would like to be able to pass a Policy to `.grantRead()` whereas I can currently only pass a Role or similar.

### Use Case

Currently, I can do this:

```
const lambdaA = new cdkLambda(...);
const lambdaB = new cdkLambda(...);
const param = new cdkSSM.StringParameter(...);
param.grantRead(lambdaA.role);
param.grantRead(lambdaB.role);
```
This creates PolicyA granting read access to the SSM parameter, and attaches it to lambdaA's role.  But then it creates an identical PolicyB, doing exactly the same as PolicyA, and attaches it to lambdaB's role.

I am trying to work out how to avoid all these duplicate policies, and instead create just one policy that gets attached to all the Lambda roles.

I can do this:

```
const policyParams = new cdkIAM.Policy(this, 'policy-ps');
policyParams.attachToRole(lambdaA.role);
policyParams.attachToRole(lambdaB.role);
```

But the problem is, how do I then pass the policy to `grantRead()`?

```
const param = new cdkSSM.StringParameter(...);
param.grantRead(policyParams); // fails, no Principal
```

It would be nice if we could pass a Policy to all the `grantRead()` and similar functions, to avoid having to specify the policy statements manually.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
It's operating as I would recommend it operates. Passing a Policy to `grantRead()` is the wrong mental model -- a policy is the *result* of `grantRead()`, not its target.

I'm curious why you care what the policies look like in CloudFormation. The result in AWS is going to be the same regardless, so I suggest you don't concern yourself too much it with.

Regardless, if you really really hate it, you can always build the policies yourself and deduplicate that way.
