### ISSUE TITLE
(aws-ecs): ecs.Cluster.fromClusterAttributes: Allow adding capacity providers on imported clusters

### ISSUE THREAD

**Issue by drigos** [aws/aws-cdk#14799]
Add capacity providers from another stack.

### Use Case

The cluster can receive more than one capacity provider, so it may be necessary during the cluster lifetime to add these capacity providers from other stacks.

### Proposed Solution

When using the [fromClusterAttributes](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-eks.Cluster.html#static-fromwbrclusterwbrattributesscope-id-attrs) method, the returned object, [ImportedCluster](https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-ecs/lib/cluster.ts#L846), must allow the addition of capacity providers.

### Other

```
const cluster = ecs.Cluster.fromClusterAttributes(this, 'EcsCluster', {
  vpc,
  clusterName: props.clusterName,
  securityGroups: [asgSecurityGroup]
});
const capacityProvider = new ecs.AsgCapacityProvider(this, 'AsgCapacityProvider', {
  autoScalingGroup,
});
cluster.addAsgCapacityProvider(capacityProvider);
```

![image](https://user-images.githubusercontent.com/3015823/119012034-0962ab80-b96c-11eb-82e7-354f2c073cda.png)

Obs.: Similar to https://github.com/aws/aws-cdk/issues/5383

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by FlorinAsavoaie** [comment]
Not sure why this was closed...

**Comment by trobert2** [comment]
This issue is still relevant today for ECS users.
Is this being ignored because people mostly use EKS nowadays? Would be great to get some roadmap insights from the AWS team

**Comment by Elycin** [comment]
@trobert2 There's a fair bit of work that is involved with EKS compared to using ECS. 

The ideal ECS use case is a quick way to get a container scaled up and deployed whereas EKS is more operationally involved with managing cloud infrastructure - which incidentally is a reason why organizations may choose to avoid EKS, or its additional costs of paying roughly $70/month just for a control plane to run in the background and scale your deployments - whereas with ECS can be seen as an abstracted implementation of autoscaling groups and EC2 instances being managed for you via ECS.

+1 on roadmap request

**Comment by dsinghvi** [comment]
+1 What's the status on this ?

**Comment by Tore189** [comment]
+1 
This is still not possible. I have existing clusters which unfortunately were not created using CDK in the first place. I'm unable to add CapacityProviders for clusters imported into cdk using the fromClusterArn or fromClusterAttributes functions since ICluster doesn't allow it

**Comment by jamescarter-le** [comment]
+1, when you have a Cluster created as part of a Stack, it is impossible to attach the next Stack's ASG to the Cluster, as it appears like a circular dependency, OR, you cannot get the Name of the previous ASG in order to drop into the Cfn functions to fully define the associations, but this means you have to have context of all other ASGs you have.
