### ISSUE TITLE
(AWS Cognito): No way to set logo in Authenticator apps, force MFA frequency 

### ISSUE THREAD

**Issue by Arvanaghi** [aws/aws-cdk#14806]
### Reproduction Steps

N/A

### What did you expect to happen?

There must be a way to set the logo that will appear in DUO / Google Auth when you link a device. It's not available in CDK. Furthermore, I can't set the frequency with which a user is prompted for 2FA.

### What actually happened?

N/A

### Environment

N/A

### Other

N/A

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
Hi @Arvanaghi -

Can you please update your report with the Cognito documentation on how to do this? 
Could you check if this is available via CloudFormation? If not, we cannot support this in the CDK.

**Comment by peterwoodworth** [comment]
Closing because the bot missed this, has gone 2 weeks without response. Please ping me if you want to reopen this issue!
