### ISSUE TITLE
(s3): autoDeleteObjects resources should use stack tags when provided

### ISSUE THREAD

**Issue by AjkayAlan** [aws/aws-cdk#14808]
## Current State

Any resources automatically created from `autoDeleteObjects` appear to not honor stack-wide tags.

## Setup

If I create a stack similar to the following (in python):

```python
from aws_cdk import aws_s3 as s3
from aws_cdk import core as cdk

class MyStack(cdk.Stack):
    def __init__(
        self,
        scope: cdk.Construct,
        construct_id: str,
        **kwargs,
    ) -> None:
        super().__init__(scope, construct_id, **kwargs)
        s3.Bucket(
            self,
            "SqlBucket",
            auto_delete_objects=True,
            removal_policy=cdk.RemovalPolicy.DESTROY,
        )
```

And my app.py looks something like:

```python
from aws_cdk import core as cdk

from stacks.my_stack import MyStack


class Main:
    def __init__(self) -> None:
        super().__init__()
        app = cdk.App()
        my_stack = MyStack(app, construct_id=f"MyCoolConstructId")
        cdk.Tags.of(my_stack).add("tag1key", "tag1value")

if __name__ == "__main__":
    Main()
```

Any of the resources created by having `auto_delete_objects=True` (generally named something like `CustomS3AutoDeleteObjects` are not tagged, including an `AWS::Lambda::Function` and an `AWS::IAM::Role`

## My Ask

Can resources being created by [`CustomResourceProvider` or `CustomResourceProviderProps`](https://github.com/aws/aws-cdk/blob/e11d5378c33bea609ed09c998b305fdfd28999a9/packages/%40aws-cdk/core/lib/custom-resource-provider/custom-resource-provider.ts#L160) include stack-wide tags?

**Comment by iliapolo** [comment]
@AjkayAlan thanks for reporting this. As you already pointed out, this is a consequence of stack tags not being applied to resources created by the `CustomResourceProvider`. Not specific to s3 here. 

You can see more details here: https://github.com/aws/aws-cdk/issues/13851

**Comment by AjkayAlan** [comment]
I am going to close this in favor of using the issue linked above.
