### ISSUE TITLE
(aws-route53): Cannot create alias of record in the same hosted zone?

### ISSUE THREAD

**Issue by jpSimkins** [aws/aws-cdk#14800]
## :question: General Issue

I am trying to create an alias in my hosted zone for a non-www to point to a www record.

In console, I just create an A record, set it as an alias, and choose `Alias to another record in this hosted zone` and select the www target but I don't see a way to do this in the CDK.

This won't work as it's not an IP address:
```typescript
    // Add non-www alias for domain
    const _nonWwwARecord = new ARecord(this, 'non-www-to-www', {
      zone: _prodHostedZone,
      target: RecordTarget.fromValues(`www.${DOMAIN}`),
      ttl: Duration.minutes(5),
    });
```

I get:
> [Invalid Resource Record: 'FATAL problem: ARRDATAIllegalIPv4Address (Value is not a valid IPv4 address) 

If I attempt to use `RecordTarget` from `@aws-cdk/aws-route53-targets` I don't see any options for a record in the same hosted zone. 

It may help to understand that the www record is set by `ApplicationLoadBalancedFargateService`.

### Environment

 - **CDK CLI Version :**  1.102.0 (build a75d52f)
 - **Module Version :**  1.102.0
 - **Node.js Version :**  v14.17.0
 - **OS               :**  Linux Zeus 5.8.0-53-generic #60~20.04.1-Ubuntu SMP Thu May 6 09:52:46 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
 - **Language (Version):** Typescript (6.14.13)

**Comment by peterwoodworth** [comment]
Adding feature request label, thanks jogold for submitting a PR for this! We'll look at it soon
