### ISSUE TITLE
(backup): Support for advancedBackupSettings

### ISSUE THREAD

**Issue by jhojgaard** [aws/aws-cdk#14803]
AWS Backup BackupPlan construct is missing support for AdvancedBackupSetting
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-backup-backupplan-advancedbackupsettingresourcetype.html

### Use Case

This is needed to support Windows VSS in AWS Backup configured with CDK

### Proposed Solution

Add something like:  `backupOptions: {"WindowsVSS": "enabled"}` to support the advanced backup options

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by Patil2099** [comment]
@MrArnoldPalmer  I would love to work on this issue. Can you guide me a little on how can I solve it?

**Comment by MrArnoldPalmer** [comment]
hey @Patil2099. This should be pretty straightforward if you checkout the [`BackupPlan`](https://github.com/aws/aws-cdk/blob/v1.105.0/packages/@aws-cdk/aws-backup/lib/plan.ts) resource you will need to add a new optional property to [`BackupPlanProps`](https://github.com/aws/aws-cdk/blob/v1.105.0/packages/@aws-cdk/aws-backup/lib/plan.ts#L23) that then is pass in the [constructor](https://github.com/aws/aws-cdk/blob/v1.105.0/packages/@aws-cdk/aws-backup/lib/plan.ts#L23) to the [`CfnBackupPlan`](https://github.com/aws/aws-cdk/blob/v1.105.0/packages/@aws-cdk/aws-backup/lib/plan.ts#L125) arguments.

**Comment by BenChaimberg** [comment]
I am unassigning myself and marking this issue as `p2`, which means that we are unable to work on this immediately.

We use +1s to help prioritize our work, and are happy to reevaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://join.slack.com/t/cdk-dev/shared_invite/zt-mso6p56d-qJp7SOTBvMaQuDrx7R2wHg) to solicit support for reprioritization.

Please feel free to work on this issue yourself and request my review if you submit a PR or would like design help! See [CONTRIBUTING.md](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) for guidelines.

**Comment by cyuste** [comment]
As a workaround, you can use this code 
```
 const plan = backup.BackupPlan.daily35DayRetention(this, 'Plan');

const cfnPlan = plan.node.defaultChild as backup.CfnBackupPlan;
const currPlan = cfnPlan.backupPlan as backup.CfnBackupPlan.BackupPlanResourceTypeProperty;
const backupPlan : backup.CfnBackupPlan.BackupPlanResourceTypeProperty = {
  ...currPlan,
  advancedBackupSettings: [{
    backupOptions: {"WindowsVSS": "enabled"},
    resourceType : 'EC2',
  }]
};
cfnPlan.backupPlan = backupPlan;
```

**Comment by fitzoh** [comment]
I wasn't sure how to do @cyuste 's workaround in python, so here's an alternate method in python:
```python
        plan = aws_backup.BackupPlan.daily35_day_retention(self, "plan")
        cfn_plan: aws_backup.CfnBackupPlan = plan.node.default_child
        cfn_plan.add_property_override(
            "BackupPlan.AdvancedBackupSettings",
            [
                {
                    "BackupOptions": {"WindowsVSS": "enabled"},
                    "ResourceType": "EC2",
                }
            ],
        )
```

Also looks like https://github.com/aws/aws-cdk/pull/15934 might be getting close to the finish line

**Comment by fitzoh** [comment]
Thanks @cokia ! 🎉
