### ISSUE TITLE
(@aws-cdk/aws-s3): Create bucket if not exists

### ISSUE THREAD

**Issue by TRANTANKHOA** [aws/aws-cdk#14810]
Provide an option to create new bucket only when not exists, otherwise refer to existing bucket.

### Logical name changes
1. Bucket name `physical-bucket` is created in stack A with logical ID `BucketA1`
2. Stack A was refactored, logical ID for the bucket is now `BucketA2` but the `physical-bucket` name is the same
3. Deployment failed with error "Bucket already exists"

### Deploying stack after deletion
1. Bucket name `physical-bucket` is created in stack A with logical ID `BucketA1`
2. Stack A was deleted due to some breaking changes or else.
3. Future deployment failed with error "Bucket already exists"

## Proposed Solution

I know Cfn has the procedure for importing external resource into stack but it's very manual and cumbersome. Even then, it's not clear how one would perform that procedure from within CDK. So I don't think that is in line with the CDK workflow.

S3 really is special persistent resource and should be treated differently, and recovering existing S3 buckets from programming mishaps should be simple. Formal bucket migration can be done with changing physical bucket name only when really needed.

## Other

I've tried doing this with aws-sdk for javascript but since it must be an async function due to aws-sdk implementation, I can't get it to work inside the cdk app. There is this [synchronized-promise](https://www.npmjs.com/package/synchronized-promise) package that I tried to use to get rid of the async call, but it doesn't work reliably and hang very often.
```javascript
private async checkBucketExists(bucket: string): Promise<IBucket> {
    const s3 = new aws.S3();
    try {
        await s3.headBucket({Bucket: bucket}).promise();
        return Bucket.fromBucketName(this, 'Bucket', bucket);
    } catch (error) {
        if (error.statusCode === 404) {
            return new Bucket(this, 'Bucket', {
                bucketName: bucket,
                removalPolicy: RemovalPolicy.RETAIN,
                versioned: true,
                lifecycleRules: [{
                    id: 'GlacierArchive',
                    enabled: true,
                    abortIncompleteMultipartUploadAfter: Duration.days(1),
                    noncurrentVersionExpiration: Duration.days(365 * 3),
                    transitions: [{
                        transitionAfter: Duration.days(365),
                        storageClass: StorageClass.DEEP_ARCHIVE
                    }],
                    prefix: 'data/'
                }]
            })
        }
        throw error;
    }
}
```

As a work around at the moment, I plan to list out and verify the existence of the buckets in my stacks prior to deployment using a script external to cdk and store the result in a json format. This will help me get rid of the need to use aws-sdk async call in javascript.

---

This is a :rocket: Feature Request

**Comment by peterwoodworth** [comment]
Closing because the issue has gone 2 weeks without a response, the bot missed this issue. Please ping me if you want to reopen this feature request!
