### ISSUE TITLE
(aws-lambda-event-sources): batch_size and max_batching_window specified, though lambda function being invoked before either batch size or batching window met

### ISSUE THREAD

**Issue by 0xjjoyy** [aws/aws-cdk#14826]
[resubmitted](https://github.com/aws/aws-cdk/issues/14569) to clarify problem and provide examples

Scenario is that events are generated and sent to a SQS queue. A lambda then receives the messages from the SQS queue.

Batch delivery is configured so that the Lambda will receive multiple messages in a single invocation.

Configured batch_size to 100 and max_batching_window to 2 minutes. Though the Lambda is invoked multiple times within milliseconds and with only 1 or 2 messages.

Expecting that either 100 messages will be batched or all messages within 2 minutes, whichever comes first.

The scenario trying to achieve is the [following](https://docs.aws.amazon.com/lambda/latest/dg/with-sqs.html)

> By default, Lambda invokes your function as soon as records are available in the SQS queue. Lambda will poll up to 10 messages in your queue at once and will send that batch to the function. To avoid invoking the function with a small number of records, you can tell the event source to buffer records for up to five minutes by configuring a batch window. Before invoking the function, Lambda continues to poll messages from the SQS standard queue until batch window expires, the payload limit is reached or full batch size is reached.

Log data within 300 milliseconds
> 2021-05-17T09:15:41.999-04:00 - 1 record
2021-05-17T09:15:42.237-04:00 - 2 records

### Reproduction Steps

```
        # avoid circular dependency
        function_name = "batch-messages"

        batch_lambda_role = iam.Role(
            self,
            f"{function_name}-role",
            path="/",
            assumed_by=iam.ServicePrincipal("lambda.amazonaws.com"),
        )

        queue_encryption_key = aws_kms.Key(
            self,
            "sqs-encryption-key",
            alias="SQSEncryptionKey",
            enable_key_rotation=True,
            pending_window=core.Duration.days(30),
        )
        queue_encryption_key.grant_decrypt(batch_lambda_role)

        queue = sqs.Queue(
            self,
            "findings-queue",
            visibility_timeout=core.Duration.seconds(130),
            encryption_master_key=queue_encryption_key,
            encryption=sqs.QueueEncryption.KMS,
        )

        lambda_layer = self.create_dependencies_layer(
            id="lambdalayer",
            requirements_path="./lambda/requirements.txt",
            output_dir="./lambda_layer",
        )

        batch_lambda = _lambda.Function(
            self,
            "batchupdate",
            runtime=_lambda.Runtime.PYTHON_3_8,
            code=_lambda.Code.asset("lambda"),
            layers=[lambda_layer],
            handler="batch_update.handler",
            role=batch_lambda_role,
            function_name=function_name,
            retry_attempts=2,
            timeout=core.Duration.minutes(2),
        )

        batch_lambda.add_event_source(
            aws_lambda_event_sources.SqsEventSource(
                queue=queue,
                batch_size=100,
                max_batching_window=core.Duration.seconds(10),
                enabled=True,
            )
        )

        batch_lambda_policy = iam.ManagedPolicy(
            self,
            f"{function_name}-policy",
            path="/",
            statements=[
                iam.PolicyStatement(
                    sid="CloudWatchLogs",
                    effect=iam.Effect.ALLOW,
                    actions=[
                        "logs:CreateLogGroup",
                        "logs:CreateLogStream",
                        "logs:PutLogEvents",
                        "*",
                    ],
                    resources=[
                        f"arn:aws:logs:{core.Aws.REGION}:{core.Aws.ACCOUNT_ID}:log-group:/aws/lambda/{function_name}:*"
                    ],
                ),
            ],
        )

        batch_lambda_role.add_managed_policy(batch_lambda_policy)

    """
    Performs a local pip install to create a folder of the dependencies.
    CDK will then bundle the layer folder, create assets zip, create hash, and upload to the assets zip to the s3 bucket to create the layer.
    https://github.com/aws-samples/aws-cdk-examples/issues/130
    """

    def create_dependencies_layer(
            self, id: str, requirements_path: str, output_dir: str
    ) -> _lambda.LayerVersion:
        # Install requirements for layer
        if not os.environ.get("SKIP_PIP"):
            subprocess.check_call(
                # Note: Pip will create the output dir if it does not exist
                f"pip install -r {requirements_path} -t {output_dir}/python".split()
            )
        return _lambda.LayerVersion(self, id, code=_lambda.Code.from_asset(output_dir))
```

lambda
```
def handler(event, context):
    records = event["Records"]
    logger.info(f"records {records}")
```

### What did you expect to happen?

Expecting that either 100 messages will be batched or all messages within 2 minutes, whichever comes first.

The scenario trying to achieve is the [following](https://docs.aws.amazon.com/lambda/latest/dg/with-sqs.html)

> By default, Lambda invokes your function as soon as records are available in the SQS queue. Lambda will poll up to 10 messages in your queue at once and will send that batch to the function. To avoid invoking the function with a small number of records, you can tell the event source to buffer records for up to five minutes by configuring a batch window. Before invoking the function, Lambda continues to poll messages from the SQS standard queue until batch window expires, the payload limit is reached or full batch size is reached.

Checking the payload size of each event is under 8KB. Meaning up to 32 records should fit.

The lambda [limits](https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-limits.html) are 
> 6 MB (synchronous)
256 KB (asynchronous)

### What actually happened?

The Lambda is invoked multiple times within milliseconds and with only 1 or 2 messages.

Log data within 300 milliseconds
> 2021-05-17T09:15:41.999-04:00 - 1 record
2021-05-17T09:15:42.237-04:00 - 2 records

### Environment

  - **CDK CLI Version  :  1.104.0**
  - **Framework Version:**
  - **Node.js Version:  v15.3.0** 
  - **OS               :**
  - **Language (Version): Python 3.9.0 (default, Dec  6 2020, 20:20:21) ** 

### Other

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
Hi @0xjjoyy -

As far as the CDK is concerned, we only configure the values provided under [`MaximumBatchingWindowInSeconds`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-eventsourcemapping.html#cfn-lambda-eventsourcemapping-maximumbatchingwindowinseconds) and [`BatchSize`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-eventsourcemapping.html#cfn-lambda-eventsourcemapping-batchsize).

Can you check that the CloudFormation template produced by the CDK has the correct values that you expect here?

If so, you will need to contact the Lambda service team to find out why the behaviour does not match up to what they've documented as.

Of course, it would be great to feed your findings back into our docs somewhere for folks looking to do the same in the future.

**Comment by peterwoodworth** [comment]
Hey @0xjjoyy, can you please do this:

>Can you check that the CloudFormation template produced by the CDK has the correct values that you expect here?

thanks.
