### ISSUE TITLE
(@aws-cdk/aws-lambda-nodejs): NodejsFunction dependency installation behavior (`package-lock.json`, npm install)

### ISSUE THREAD

**Issue by jmm** [aws/aws-cdk#14823]
### The Question

I'm having trouble following the [NodejsFunction](https://github.com/aws/aws-cdk/blob/v1.105.0/packages/@aws-cdk/aws-lambda-nodejs/README.md) documentation about dependency management. It says that a dependencies lock file is required and that dependencies will be installed, but with CDK v1.105.0 I'm not seeing that behavior with esbuild in the environment or using Docker.

With a tree like:

```
component/
└── function-a/
    ├── index.js
    ├── package-lock.json
    └── package.json
```

And a construct like:

```js
const functionA = new NodejsFunction(this, "function-a", {
  entry: path.join(baseDirectory, "component", "function-a", "index.js"),
  runtime: lambda.Runtime.NODEJS_14_X,
})

// or

const functionA = new NodejsFunction(this, "function-a", {
  depsLockFilePath: path.join(baseDirectory, "component", "function-a", "package-lock.json"),
  entry: path.join(baseDirectory, "component", "function-a", "index.js"),
  runtime: lambda.Runtime.NODEJS_14_X,
})
```

My expectation is that `component/function-a/package-lock.json` would be required and would be used to install the dependencies prior to bundling.

What I'm observing is that `package-lock.json` isn't required (there's no complaint if it's omitted), dependencies aren't installed, and synth fails if there wasn't already a `node_modules/` populated with dependencies.

Here is a [minimal repro](https://github.com/jmm/cdk-repro-nodejs-function-no-dependency-installation).

I get the same result if I set `bundling.forceDockerBundling` to `true`.

And in both cases if I define `bundling.commandHooks.beforeInstall` it doesn't get executed (and before I get to that point I get errors about the other hooks not being defined, which I'll open a separate issue about if there isn't one already).

---

Where the documentation says...

> Alternatively, you can specify the `depsLockFilePath` prop manually. In this case you need to ensure that this path includes `entry` and any module/dependencies used by your function. Otherwise bundling will fail.

...does...

> you need to ensure that this path includes `entry`

...mean that the file specified as `entry` has to be in the directory that the file specified as `depsLockFilePath` is in? And if so, why?

What does it mean by:

> you need to ensure that this path includes [...] any module/dependencies used by your function.

Is it referring to the lock file or a `node_modules/` directory?

### Environment

  - **CDK CLI Version:** 1.105.0 (build 4813992)
  - **Module Version:** 1.105.0
  - **Node.js Version:** v14.16.0
  - **OS:** macOS
  - **Language (Version):**

**Comment by jogold** [comment]
You don't need a separate package.json per function. 

You can put all your dependencies (= cdk deps and runtime deps) at the root of your project and let the construct find your lock file. The construct bundles only what is required by each function.

Will update the README to explain this better.

**Comment by eladb** [comment]
@jogold, thanks for following up with a quick PR to update documentation.

**Comment by jmm** [comment]
Hi @jogold, thanks for the reply and documentation update (I don't know if you made it yet, but at any rate I haven't seen it yet).

What if I want separate dependency management per function though? Say for example I have functions A-Z and want to incrementally update them to use a new major version of a dependency.

**Comment by jogold** [comment]
> What if I want separate dependency management per function though? Say for example I have functions A-Z and want to incrementally update them to use a new major version of a dependency.

I would do this the "node way"... with a monorepo where you have multiple packages and `package.json` files but only one lock file and a single install command.

**Comment by pankajagrawal16** [comment]
What if I am using CDK construct in a different language say Java than my lambda function itself .

**Comment by jogold** [comment]
> What if I am using CDK construct in a different language say Java than my lambda function itself .

I would say that you can still have single `package.json` file either at the root of your project or inside a folder with all your Lambda's

**Comment by pankajagrawal16** [comment]
> > What if I am using CDK construct in a different language say Java than my lambda function itself .
> 
> I would say that you can still have single `package.json` file either at the root of your project or inside a folder with all your Lambda's

But still it does not seem to build successfully if node_modules does not exists already locally.

**Comment by jogold** [comment]
> > > What if I am using CDK construct in a different language say Java than my lambda function itself .
> > 
> > 
> > I would say that you can still have single `package.json` file either at the root of your project or inside a folder with all your Lambda's
> 
> But still it does not seem to build successfully if node_modules does not exists already locally. So do I need to still make sure that npm install is run locally as well ? 🤔

Yes, you need to run `npm install`, the construct expects the dependencies to be available.

**Comment by pfried** [comment]
@jogold 

I stumbled across this issue switching over from custom docker bundling to `NodejsFunction` bundling. As of this I do have folders with a typescript handler, a `package.json` and a `package-lock.json`

As I do run a CI/CD pipeline with `aws-cdk pipeline` I came across the issues described here. It is also unclear from the documentation as the statements about the `package-lock.json` and the `commandHooks` indicate there is some kind of `install` happening.

Locally that works if `node_modules` is present but in the CI it fails.  I think the docs should just state that there is no install happening? Or am I getting this wrong?

**Comment by jogold** [comment]
> I stumbled across this issue switching over from custom docker bundling to `NodejsFunction` bundling. As of this I do have folders with a typescript handler, a `package.json` and a `package-lock.json`

If you have separate `package.json` and `package-lock.json` files then you have to run `npm install` inside those folders. Modules that should be bundled by `esbuild` must be available (= installed, = in `node_modules`). Note that you don't need sperate dependency files, see [reference architecture](https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/aws-lambda-nodejs#reference-project-architecture).

> and the `commandHooks` indicate there is some kind of install happening

This is for the [`nodeModules`](https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/aws-lambda-nodejs#install-modules) prop (for modules that are not bundled by `esbuild` but installed afterwards in the asset output directory.

**Comment by pfried** [comment]
@jogold Thanks for clarification.

I now wonder if it would be possible to automate Lambda Layer bundling somehow. A typical application might have dozens of lambda functions and it would really help to bundle all (or many) dependencies in a  LambdaLayer and then exclude them from the `esbuild` build to make the bundles smaller.

Have you seen anything like that already?

**Comment by bodokaiser** [comment]
@pfried as you both have pointed out it seems sufficient to insert an install command through the `commandHooks`.

For reference, the following worked for me when you pull a separate repo with independent dependencies next to the cdk directory, i.e., `../lambda` if `cwd` is the cdk directory:

```
this.lambda = new NodejsFunction(this, 'Lambda', {
      handler: 'handler',
      entry: path.join(__dirname, '../../lambda/main.ts'),
      bundling: {
        commandHooks: {
          beforeBundling(inputDir: string, outputDir: string) {
            return [
              `cd ${inputDir} && cd lambda && yarn install --frozen-lockfile`
            ]
          },
          beforeInstall() {
            return []
          },
          afterBundling() {
            return []
          }
        }
      },
      memorySize: 256,
      timeout: Duration.seconds(10),
    })
```

If you pull in the codebase **into** the cdk directory, you need to exclude it via `tsconfig.json`. Otherwise, `yarn run build` in the `SynthStep` fails as it tries to compile the other codebase without having the dependencies available.
