### ISSUE TITLE
(cdk-go): malformed module path in Go code generation when attempting to build example

### ISSUE THREAD

**Issue by skeeters1** [aws/aws-cdk#14838]
Attempt to get started with the go cdk, initialise and test the example crashed. Tentatively reporting as a bug in case linked to https://github.com/aws/jsii/issues/2842.

### Reproduction Steps

Fresh go project following steps in https://docs.aws.amazon.com/cdk/latest/guide/work-with-cdk-go.html

aws configure
mkdir gotest
cd gotest
cdk init app --language go                         //  comment: this works fine
cdk ls -v (or cdk deploy, cdk bootstrap, cdk synth)

### What did you expect to happen?
This was an initial check that the toolchain is working by testing the example. I expected ls to build and launch a container to return the names of two existing CDK stacks in this account and region, created in a Typescript project, which seems to work perfectly in the same user session. So I think my AWS creds, cdk and node installations are correct.

### What actually happened?
Go build failed with following error (tail of output)

build command-line-arguments: cannot load embed: malformed module path "embed": missing dot in first path element
Subprocess exited with error 1
Error: Subprocess exited with error 1
    at ChildProcess.<anonymous> (/home/drskeet/.nvm/versions/node/v14.17.0/lib/node_modules/aws-cdk/lib/api/cxapp/exec.ts:122:23)
    at ChildProcess.emit (events.js:376:20)
    at ChildProcess.emit (domain.js:470:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)

### Environment

  - **CDK CLI Version  :** 1.105.0 (build 4813992)
  - **Framework Version:** 
  - **Node.js Version:**  v14.17.0
  - **OS               :** Kubuntu Linux 5.4.0-58-generic
  - **Language (Version):**  go version go1.16 linux/amd64

### Other

Unfortunately I can't rule out configuration mistakes elsewhere since this was my first attempt to use the Go bindings. I don't have a known-good version in golang. 

Looks like this might be related to https://github.com/aws/jsii/issues/2842? But if so, much easier to reproduce.

--- 

This is :bug: Bug Report

**Comment by MrArnoldPalmer** [comment]
@skeeters1 `build command-line-arguments: cannot load embed: malformed module path "embed": missing dot in first path element` indicates that the go version is < 1.16 though 1.16 is the minimum and thats what you reported using. Can you double check that please? This is probably unrelated to aws/jsii#2842

**Comment by skeeters1** [comment]
Thanks for quick reply. Don't think I am accidentally running an older go version:
which go
`/usr/bin/go`

go version
`go version go1.16 linux/amd64`

cat go.mod
```
module cdkgotest

go 1.16

require (
        github.com/aws/aws-cdk-go/awscdk v1.105.0-devpreview
        github.com/aws/constructs-go/constructs/v3 v3.3.75
        github.com/aws/jsii-runtime-go v1.29.0
        github.com/stretchr/testify v1.7.0

        // for testing
        github.com/tidwall/gjson v1.7.4
)
```

**Comment by MrArnoldPalmer** [comment]
This is likely some other environment issue but I'm not sure what it could be then. I'm unable to reproduce on either of my machines (macos & ubuntu) and the paths in the `go.mod` file are fine.

As far as I can tell the error comes from [JSII using the `embed` package](https://github.com/aws/jsii/blob/main/packages/%40jsii/go-runtime/jsii-runtime-go/internal/embedded/embedded.go#L4) which is in the [stdlib](https://golang.org/pkg/embed/) of go 1.16. You can try running in a container or on a different machine with a clean install of go and node to verify if this is in fact an environment issue and hopefully help isolate it.

**Comment by skeeters1** [comment]
Many thanks indeed, will try exactly that. Sorry for reporting as a bug, I rather suspected it would be something local. Will poke around in JSII and let you know. Might be relevant for FAQ or installation instructions for full release.

**Comment by skeeters1** [comment]
Fixed. Local config error: go aliased to go1.16 but /usr/bin/go symlinked to 1.13. Thank you for the key information that it was picking up the wrong go version. Closing.
