### ISSUE TITLE
(apigatewayv2): property to extract WebSocket control endpoint URL

### ISSUE THREAD

**Issue by adam-nielsen** [aws/aws-cdk#14836]
In Lambda, if you want to send a message to a WebSocket, you have to supply a HTTPS endpoint for the API Gateway control interface.  However there appears to be no way to obtain this URL when the WebSocket is created via CDK,

### Use Case

I want to create a WebSocket, and have a Lambda function send messages to connected clients in response to non-WebSocket events (e.g. SQS message arrival).  This means I can't extract the WebSocket control address from the Lambda `event` object as it is not a WebSocket message that has triggered the function.  Instead I must pass the WebSocket control URL in via some other method such as an environment variable.

### Proposed Solution

There is already a `WebSocketApi.apiEndpoint` property for the WebSocket itself (minus the stage) so I guess it would work better in `WebSocketStage` having a property like `.controlEndpoint`.

So far I have worked around the issue by (in CDK) using a constructed string like this:

    `https://${webSocketApi.apiId}.execute-api.${this.region}.amazonaws.com/${webSocketStage.stageName}`

But it would be nicer if this was provided by the library.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by nija-at** [comment]
What about these properties - [`WebsocketStage.url`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-apigatewayv2.WebSocketStage.html#urlspan-classapi-icon-api-icon-experimental-titlethis-api-element-is-experimental-it-may-change-without-noticespan) or [`Websocket.apiEndpoint`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-apigatewayv2.WebSocketApi.html#apiendpointspan-classapi-icon-api-icon-experimental-titlethis-api-element-is-experimental-it-may-change-without-noticespan) ? Do these not give what you're expecting?

**Comment by adam-nielsen** [comment]
Not quite - they give some information but one of the values required to fully use the websocket is missing:
```
Websocket.apiEndpoint:  wss://example.execute-api.ap-southeast-2.amazonaws.com
WebsocketStage.url:     wss://example.execute-api.ap-southeast-2.amazonaws.com/v1
Value wanted:         https://example.execute-api.ap-southeast-2.amazonaws.com/v1
```
The Websocket.apiEndpoint is the base URL (not sure exactly what it's needed for), the WebsocketStage.url is the public URL clients connect to and send messages to your server process, and the [HTTPS endpoint](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-how-to-call-websocket-api-connections.html) is how your server process pushes data and responses out to clients connected to the websocket.  Without this URL you can only receive messages from websocket clients, but not push any data out to them.

The WebsocketStage.url comes out in the CloudFormation template like this:
```
            Fn::Join:
              - ""
              - - wss://
                - Ref: example12345
                - .execute-api.
                - Ref: AWS::Region
                - "."
                - Ref: AWS::URLSuffix
                - /v1
```
So it looks like it's just building the URL with "wss://" on the front, which suggests copying this implementation and changing "wss://" to "https://" would provide the missing endpoint URL.

**Comment by nija-at** [comment]
Thanks for the fantastic details here @adam-nielsen.

Since we have a workaround for this, I'm marking this as a p2 feature. This means we can't get to this right away.
We're accept pull requests though.
