### ISSUE TITLE
(aws-vpc): connect fargate in VPC of one AWS account to DynamoDB in another AWS account

### ISSUE THREAD

**Issue by TiffanyHsuuuu** [aws/aws-cdk#14844]
Hi,

As topic, could you please advise how I can connect/communicate EC2 or Fargate ECS instances in VPC of one AWS account to/with DynamoDB in another AWS account? I attached an image below.
(The motivation behind this is to separate data storage from other components, to prevent accidentally messing with database.)

One post in Stackoverflow says credentials needed to connect another AWS account, could you please advise how to implement this via CDK? And this seems not an idea way for me (because credentials needed to be provided), are there any workaround in this case, such as IAM or STS(Security Token Service) can possibly play a role here? Thank you.

https://stackoverflow.com/questions/53085423/can-i-connect-to-different-account-aws-servicess3-dynamodb-from-my-account-ec
![image](https://user-images.githubusercontent.com/50206789/119273830-063a1a80-bc0d-11eb-9ee2-a519007feb63.png)

**Comment by NGL321** [comment]
Hey @TiffanyHsuuuu,

This is a bit of a non-sequitur. While you can absolutely interface between services across accounts, and those services can be deployed via the CDK, the actual interfacing would not consist of CDK code. You have to write an application of some kind using the AWS SDK or direct API service calls.

I'm not certain what it is you would like to do with the CDK here, but I recommend you take a look at our [SDK Documentation](https://aws.amazon.com/tools/).

😸 😷

**Comment by peterwoodworth** [comment]
Closing because the closing soon label has been applied for over 4 days. Ping me if you need more help with this! 😄
