### ISSUE TITLE
(aws-ecr-assets): Infinite folder creation when cdk.out is not excluded

### ISSUE THREAD

**Issue by AlexGue** [aws/aws-cdk#14841]
When creating a DockerImageAsset, if you specify the project root path as the build directory, an infinite loop creating folders is started and no error is logged in the console (even with verbose activated).

### Reproduction Steps

Create a DockerImageAsset specifying root path as directory.
(The Dockerfile must exist in the example-folder)
```
    let imageAssetFailing = new aws_ecr_assets.DockerImageAsset(this, 'image-asset-failing', {
      directory: ".",
      file: "/example-folder/Dockerfile",
    });
```

And execute
`cdk deploy`
or
`cdk synth`

If the cdk.out is added in the exclude glob patterns, the problem is solved:
```
    const imageAssetWorking = new aws_ecr_assets.DockerImageAsset(this, 'image-asset-working', {
      directory: ".",
      file: "/example-folder/Dockerfile",
      exclude: ["cdk.out"] //Node_modules can be also added.
    });
```

### What did you expect to happen?

The dockerImageAsset should be created or an error must be returned to the user avoiding the infinite loop.

### What actually happened?

The CDK deploy process doesn't log anything in the console and an infinite loop creating folders inside cdk.out is started.

![image](https://user-images.githubusercontent.com/34453017/119244636-e524eb80-bb72-11eb-9ec6-c35128bcb755.png)

### Environment

  - **CDK CLI Version  :**  2.0.0-rc.4 (Also tested in 1.105.0)
  - **Framework Version:**
  - **Node.js Version:** v14.16.1
  - **OS               :** Microsoft Windows [Versión 10.0.19041.804]
  - **Language (Version):** Javascript | TypeScript (3.8.3)

### Other

Pull request with a possible fix:
#14842 

--- 

This is :bug: Bug Report

**Comment by eladb** [comment]
@AlexGue thanks for submitting the pull request for this!
