### ISSUE TITLE
(stepfunctions-tasks): Default Policy for AthenaStartQueryExecution doesn't support other partitions when specifiy bucket name in outputLocation

### ISSUE THREAD

**Issue by Momo0621** [aws/aws-cdk#14846]
https://github.com/aws/aws-cdk/blob/53ee025ae038018e56aea84b3de20f5770c874fa/packages/%40aws-cdk/aws-stepfunctions-tasks/lib/athena/start-query-execution.ts#L109

The partition here is specified to aws partition which resulted in cloudformation deployment failed when deploy to aws-cn partition.

### Cloud Formation  error
Partition "aws" is not valid for resource "arn:aws:s3:::<bucket_name>/*". (Service: AmazonIdentityManagement; Status Code: 400; Error Code: MalformedPolicyDocument; Proxy: null)

### Reproduction Steps

Create following resource for aws-cn partition.

```
const startQueryExecutionJob = new tasks.AthenaStartQueryExecution(this, 'Start Athena Query', {
  queryString: sfn.JsonPath.stringAt('$.queryString'),
  queryExecutionContext: {
    databaseName: 'mydatabase',
  },
  resultConfiguration: {
    encryptionConfiguration: {
      encryptionOption: tasks.EncryptionOption.S3_MANAGED,
    },
    outputLocation: {
      bucketName: 'query-results-bucket',
      objectKey: 'folder',
    },
  },
});
```

**Comment by shivlaks** [comment]
thanks for raising this issue @Momo0621 - I believe this is a  bug and a straightforward fix to make it partition aware.
