### ISSUE TITLE
(aws-lambda-nodejs): support full configuration for source maps in esbuild options

### ISSUE THREAD

**Issue by seawatts** [aws/aws-cdk#14857]
Currently, there is only support for passing in `sourceMap: boolean` https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-lambda-nodejs.BundlingOptions.html#sourcemap into the `bundling` options in the `@aws-cdk/aws-lambda-nodejs` `NodejsFunction`. The documentation for sourceMaps in esbuild can be found here https://esbuild.github.io/api/#sourcemap
I would like to be able to pass in any of the options `inline` `external` `both`

### Use Case

I am trying to set up Sentry, an error monitoring service for my lambdas but it is not correctly picking up the source maps for my compiled Typescript files. It requires the source maps to be inline https://docs.sentry.io/platforms/node/guides/aws-lambda/typescript/

### Proposed Solution

Change the type of `sourceMap: boolean` to `sourceMap: 'inline' | 'external' | 'both' | boolean` here https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-lambda-nodejs.BundlingOptions.html#sourcemap

* [ ] :wave: I may be able to implement this feature request
* [x] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by eladb** [comment]
@seawatts thanks for proposing this feature. It might take some time before we are able to prioritize this, but if you'd like to contribute I am happy to help out.

Since this is a production module we are unable to break existing api, but we can mark it as @deprecated (while still supporting it) and add a new option with a different name with an enum type (maybe call it `sourceMapOptions` for lack of a more creative idea).

**Comment by haimlit** [comment]
The possible values for an enum will be `DEFAULT, EXTERNAL, INLINE, BOTH` - Default is the existing behavior, where no additional flag is passed to [sourcemap](https://esbuild.github.io/api/#sourcemap). So if we'll create a `SourceMapMode` enum, we can have it side by side with the `sourceMap` boolean flag, preserving backward compatibility without deprecating anything. Example:

```
{
  sourceMap: true,
  sourceMapMode: SourceMapMode.DEFAULT
} 
```

Or is it preferred to deprecate the `sourceMap` boolean, in favor of keeping consistency with the `xxxOptions` pattern? Example:

```
{
  sourceMap: { // SourceMapOptions
    enabled: true,
    mode: SourceMapMode.DEFAULT
  }
}
```

**Comment by jogold** [comment]
@eladb This issue can be closed.

**Comment by seawatts** [comment]
Hi @vvo I have not figured this out yet 😢
