### ISSUE TITLE
how to configure cfn-hup helper script?

### ISSUE THREAD

**Issue by hnajera** [aws/aws-cdk#14855]
### The Question
I'm implementing the cfn-hub configuration because I didn't see any feature for that in the cdk documentation. 

I'm configuring everything inline using the  ec2.InstanceProps property of Instance:

        const instance = new ec2.Instance(this, 'Instance', {  
            vpc: vpc,
            instanceType: props.instanceType,
            machineImage: props.machineImage,.
            init: ec2.CloudFormationInit.fromConfigSets({
                configSets: {
                    // Applies the configs below in this order
                    default: ['yumPreinstall', 'config'],
                },
                configs: {
....

This is how i'am creating the cfn-auto-reloader.conf file

                        ec2.InitFile.fromString('/etc/cfn/hooks.d/cfn-auto-reloader.conf',
                            [
                                '[cfn-auto-reloader-hook]\n',
                                'triggers=post.update\n',
                                `path=Resources.**$LogicalResourceId.**Metadata.AWS::CloudFormation::Init\n`,
                                'action=/opt/aws/bin/cfn-init -v ',
                                `--stack ${cdk.Stack.of(this).stackName} `,
                                '--resource $LogicalResourceId ',
                                '--configsets default',
                                `region=${cdk.Stack.of(this).region}\n`,
                                'runas=root\n'
                            ].join('')
                        ),

the issue is that  I can't  be able to obtain the LogicalResourceId because that lines are inside the ec2.Instance constructor.

Please let me know if you have any ideas on how to obtain the instance LogicalResourceId or any alternative to configure the cfn-hup 
### Environment

  - **CDK CLI Version:** 1.102.0
  - **Module Version:** 
  - **Node.js Version:** 
  - **OS:**  Windows 10
  - **Language (Version):** TypeScript (3.9.7)

**Comment by hzainuddin2002** [comment]
I had a similar issue when attempting to use cfn-signal for a windows instance. I used the method to manually override the metadata of the resource. That will probably be your best bet. Your override will come after the constructor so you can reference the logicalresourceid its a bit more declarative and you'll need to pass the entire json object as string

**Comment by peterwoodworth** [comment]
Hey @hnajera, have you tried hzainuddin2002's workaround?

The CDK doesn't feature support for `cfn-hup`, [here's a feature request for it](https://github.com/aws/aws-cdk/issues/12529) that you should upvote if you would like to see this feature!

**Comment by hnajera** [comment]
> ## ❓ General Issue
> ### The Question
> I'm implementing the cfn-hub configuration because I didn't see any feature for that in the cdk documentation.
> 
> I'm configuring everything inline using the ec2.InstanceProps property of Instance:
> 
> ```
>     const instance = new ec2.Instance(this, 'Instance', {  
>         vpc: vpc,
>         instanceType: props.instanceType,
>         machineImage: props.machineImage,.
>         init: ec2.CloudFormationInit.fromConfigSets({
>             configSets: {
>                 // Applies the configs below in this order
>                 default: ['yumPreinstall', 'config'],
>             },
>             configs: {
> ```
> 
> ....
> 
> This is how i'am creating the cfn-auto-reloader.conf file
> 
> ```
>                     ec2.InitFile.fromString('/etc/cfn/hooks.d/cfn-auto-reloader.conf',
>                         [
>                             '[cfn-auto-reloader-hook]\n',
>                             'triggers=post.update\n',
>                             `path=Resources.**$LogicalResourceId.**Metadata.AWS::CloudFormation::Init\n`,
>                             'action=/opt/aws/bin/cfn-init -v ',
>                             `--stack ${cdk.Stack.of(this).stackName} `,
>                             '--resource $LogicalResourceId ',
>                             '--configsets default',
>                             `region=${cdk.Stack.of(this).region}\n`,
>                             'runas=root\n'
>                         ].join('')
>                     ),
> ```
> 
> the issue is that I can't be able to obtain the LogicalResourceId because that lines are inside the ec2.Instance constructor.
> 
> Please let me know if you have any ideas on how to obtain the instance LogicalResourceId or any alternative to configure the cfn-hup
> 
> ### Environment
> * **CDK CLI Version:** 1.102.0
> * **Module Version:**
> * **Node.js Version:**
> * **OS:**  Windows 10
> * **Language (Version):** TypeScript (3.9.7)
> 
> ### Other information



> Hey @hnajera, have you tried hzainuddin2002's workaround?
> 
> The CDK doesn't feature support for `cfn-hup`, [here's a feature request for it](https://github.com/aws/aws-cdk/issues/12529) that you should upvote if you would like to see this feature!

Hi @peterwoodworth and @hzainuddin2002  and thanks for your responses, even I'm working on a workaround to obtain the logical id , I just want to share the progress on this because I was able to implement the cfn-hup in this way: 

```
import * as cdk from '@aws-cdk/core';
import * as ec2 from '@aws-cdk/aws-ec2';
import * as iam from '@aws-cdk/aws-iam';

export interface InstanceProps {
    vpcName: string,
    targetSecurityGroupId?: string;
    targetSecurityGroupPort?: number,
    instanceType: ec2.InstanceType,
    machineImage: ec2.IMachineImage,
    instanceConnectEnabled?: boolean
}

export class Instance extends cdk.Construct {

    constructor(scope: cdk.Construct, id: string, props: InstanceProps) {
        super(scope, id);
        const vpc = ec2.Vpc.fromLookup(this, 'VPC', {
            tags: {
                "Name": props.vpcName
            }
        });

        const handle = new ec2.InitServiceRestartHandle();
        const instance = new ec2.Instance(this, 'Instance', {
            vpc: vpc,
            instanceType: props.instanceType,
            machineImage: props.machineImage,
            keyName: "key",
            userDataCausesReplacement: false,
            init: ec2.CloudFormationInit.fromConfigSets({
                configSets: {
                    // Applies the configs below in this order
                    default: [
                        'updateOS',
                        'setupCfnHup',
                        'setupCloudWatchAgent',
                        'configureCloudWatchAgent',
                        'restartCloudWatchAgent'
                    ],
                    Update: [
                        'updateOS',
                        'configureCloudWatchAgent',
                        'restartCloudWatchAgent',
                        'testCfnHup'
                    ]
                },
                configs: {
                    setupCfnHup: new ec2.InitConfig([
                        ec2.InitFile.fromString('/etc/cfn/cfn-hup.conf',
                            [
                                '[main]\n',
                                `stack=${cdk.Stack.of(this).stackName}\n`,
                                `region=${cdk.Stack.of(this).region}\n`,
                                'interval=2\n',
                                'verbose=true'
                            ].join(''),
                            { serviceRestartHandles: [handle] }
                        ),
                        ec2.InitFile.fromString('/etc/cfn/hooks.d/cfn-auto-reloader.conf',
                            [
                                '[cfn-auto-reloader-hook]\n',
                                'triggers=post.update\n',
                                'path=Resources.BaseInstanceDD81DA14.Metadata.AWS::CloudFormation::Init\n',
                                'action=/opt/aws/bin/cfn-init -v ',
                                `--stack ${cdk.Stack.of(this).stackName} `,
                                '--resource BaseInstanceDD81DA14 ',
                                `--region ${cdk.Stack.of(this).region} `,
                                '--configsets Update\n'
                            ].join(''),
                            { serviceRestartHandles: [handle] }
                        ),
                        ec2.InitService.enable('cfn-hup', {
                            enabled: true,
                            ensureRunning: true,
                            serviceRestartHandle: handle
                        })
                    ]),
                    setupCloudWatchAgent: new ec2.InitConfig([
                        ec2.InitPackage.yum('amazon-cloudwatch-agent'),
                    ]),
                    configureCloudWatchAgent: new ec2.InitConfig([
                        ec2.InitFile.fromObject('/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json', {
                            "metrics": {
                                "append_dimensions": {
                                    "AutoScalingGroupName": "${!aws:AutoScalingGroupName}",
                                    "ImageId": "${!aws:ImageId}",
                                    "InstanceId": "${!aws:InstanceId}",
                                    "InstanceType": "${!aws:InstanceType}"
                                },
                                "metrics_collected": {
                                    "mem": {
                                        "measurement": [
                                            "mem_used_percent"
                                        ]
                                    },
                                    "swap": {
                                        "measurement": [
                                            "swap_used_percent"
                                        ]
                                    },
                                    "disk": {
                                        "measurement": [
                                            "used_percent"
                                        ],
                                    }
                                }
                            },
                            "logs": {
                                "logs_collected": {
                                    "files": {
                                        "collect_list": [
                                            {
                                                "file_path": "/opt/aws/amazon-cloudwatch-agent/logs/amazon-cloudwatch-agent.log",
                                                "log_group_name": "/aws/ec2/instances/cloudwatch-agent",
                                                "log_stream_name": `{instance_id}`,
                                                "timezone": "UTC"
                                            },
                                            {
                                                "file_path": "/var/log/cfn-init.log",
                                                "log_group_name": "/aws/ec2/instances/cfninit",
                                                "log_stream_name": "{instance_id}/cfn-init",
                                                "timezone": "UTC"
                                            },
                                            {
                                                "file_path": "/var/log/cfn-init-cmd.log",
                                                "log_group_name": "/aws/ec2/instances/cfnint",
                                                "log_stream_name": "{instance_id}/cfn-init-cmd",
                                                "timezone": "UTC"
                                            },
                                            {
                                                "file_path": "/var/log/secure",
                                                "log_group_name": "/aws/ec2/instances/linux/var/log/secure",
                                                "log_stream_name": "{instance_id}-var-log-secure",
                                                "timezone": "UTC"
                                            },
                                            {
                                                "file_path": "/var/log/audit/audit.log",
                                                "log_group_name": "/aws/ec2/instances/linux/var/log/audit",
                                                "log_stream_name": "{instance_id}-var-log-audit",
                                                "timezone": "UTC"
                                            },
                                            {
                                                "file_path": "/var/log/messages",
                                                "log_group_name": "/aws/ec2/instances/linux/var/log/messages",
                                                "log_stream_name": "{instance_id}-var-log-messages",
                                                "timezone": "UTC"
                                            },
                                        ]
                                    }
                                },
                            }
                        },
                        ),
                    ]),
                    restartCloudWatchAgent: new ec2.InitConfig([
                        ec2.InitCommand.shellCommand('sudo /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a stop'),
                        ec2.InitCommand.shellCommand('sudo /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -c file:/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json -s'),
                    ]),
                    updateOS: new ec2.InitConfig([
                        ec2.InitCommand.shellCommand('sudo yum update -y')
                    ]),
                    testCfnHup: new ec2.InitConfig([
                        ec2.InitCommand.shellCommand('echo "+*+*+*+CFN-HUP+*+*+*+Working Well++++++"'),
                    ]),
                },
            }),
            initOptions: {
                // Optional, which configsets to activate (['default'] by default)
                configSets: ['default'],

                // Optional, how long the installation is expected to take (5 minutes by default)
                timeout: cdk.Duration.minutes(50),
            },
            blockDevices: [
                {
                    deviceName: '/dev/sda1',
                    volume: ec2.BlockDeviceVolume.ebs(50),
                },
            ],
        });

        //Security Groups
        if (props.instanceConnectEnabled) {
            instance.connections.allowFrom(ec2.Peer.ipv4('18.206.107.24/29'), ec2.Port.tcp(22), 'Allow inbound ssh from aws ec2 instance connect');
        }

        //Instance Profile Policies
        instance.role.addManagedPolicy(iam.ManagedPolicy.fromAwsManagedPolicyName("CloudWatchAgentServerPolicy"));
    }

}

```

As you can see I'm hardcoding the logical id of the instance **BaseInstanceDD81DA14** but I will try to use placeholder to later replace that value dynamically  with the instance id using a sed command in the user data and restart the cfn-hup to reload the configuration. Something like this:

```
        instance.userData.addCommands(
            `sed -i -e "s/\\**$LogicalResourceId**/${**(instance.node.defaultChild as ec2.CfnInstance).logicalId**}/" /etc/cfn/hooks.d/amazon-cloudwatch-agent-auto-reloader.conf`,
            'systemctl start cfn-hup.service'
        );
```
I'll let you know if I find anything, but any ideas are welcome.

**Comment by hzainuddin2002** [comment]
Set this block as a placeholder: 
   
               setupCfnHup: new ec2.InitConfig([
                      ec2.InitFile.fromString('/etc/cfn/cfn-hup.conf',
                          [
                              'placeholder'
                          ]

Outside your ec2 construct override its value:

```
instance.instance.addOverride('Metadata.AWS::CloudFormation::Init.setupCfnHup.files./etc/cfn/cfn-hup.conf.content', 
            `<Add configuration here - use instance.instance.logicalId for the --resource flag`)
```

Havent tested - just double check you overriding the right metadata path. Look at the synthesized cfn output and double check.

**Comment by peterwoodworth** [comment]
I'm going to close this issue and ask for discussions and workarounds to be moved to the [feature request](https://github.com/aws/aws-cdk/issues/12529) for cfn-hup. That thread would appreciate what you both have contributed so far 😄
