### ISSUE TITLE
docs(Readme): remove unused image resource (screencast.gif)

### ISSUE THREAD

**Issue by cokia** [aws/aws-cdk#14851]
This is a 📕 documentation issue

I think "screencast.gif" at project root directory is not used (I thinks it already deprecated)
So I think it's possible to delete this file.

**Comment by peterwoodworth** [comment]
Thank you for your issue submission @cokia, we're happy to see that you want to contribute!

`screencast.gif` isn't supposed to be "used" anywhere. It's a [tutorial gif](https://github.com/aws/aws-cdk/blob/master/screencast.gif) showing how to do basic CDK commands on the CLI, so it's definitely still worth keeping around. Let me know if you want help finding other ways to contribute!

**Comment by skinny85** [comment]
`screencast.gif` used to be linked to from the main ReadMe. Now that it's not, I would also support removing it.

**Comment by peterwoodworth** [comment]
You're right, if it used to be linked in the readme and isn't anymore then it does make sense to remove the gif

**Comment by peterwoodworth** [comment]
Thank you for helping us to clean this up @cokia 😄
