### ISSUE TITLE
(apigatewayv2): Support Lambda Authorizer Payload Format Version 2

### ISSUE THREAD

**Issue by davidarmstronglewis** [aws/aws-cdk#14858]
`HttpApi` should support attaching a default authorizer configured to accept `AuthorizerPayloadVersion.VERSION_2_0`. Right now it's impossible to do this unless you drop down to a lower level, which I've had issues finding proper documentation for how to accomplish (probably a me-problem, so if there's somewhere I should look I'd appreciate some pointers).

### Use Case

Version 2 is a nice payload format.

### Proposed Solution

Add support for `AuthorizerPayloadVersion.VERSION_2_0` in the constructor of `HttpApi` as well as the `addRoutes` convenience methods.

---

This is a :rocket: Feature Request

**Comment by iRoachie** [comment]
You can accomplish this right now by using response types.

```ts
const authorizer = new HttpLambdaAuthorizer({
  responseTypes: [HttpLambdaResponseType.SIMPLE],
})

// Default authorizer
new HttpApi(this, 'api', {
  defaultAuthorizer: authorizer,
})

// Add routes
const api = new HttpApi(this, 'api');

api.addRoutes({
  authorizer,
});
```

**Comment by nija-at** [comment]
+1 to @iRoachie's comment above.

**Comment by peterwoodworth** [comment]
Closing this issue due to staleness, please ping me if you'd like to revisit this issue!
