### ISSUE TITLE
(cloudfront/s3): Incorrect S3 origin region assumed

### ISSUE THREAD

**Issue by callumthomson** [aws/aws-cdk#14850]
I've got a bucket located in `eu-west-2` which is used as an origin for 5 different CloudFront distributions. This bucket was created manually outside of the CDK / CloudFormation.

I've got some stacks created in the `eu-west-2` region and also a stack in the `us-east-2` region. All my CloudFront distributions created by the CDK in the `eu-west-2` region are configuring successfully with the S3 bucket origin. However, the CloudFront distribution which is created by a stack in the `us-east-2` region is incorrectly assuming the region that the bucket is in, and so it's pointing to a non-existent S3 bucket.

Essentially, the bucket URL is `<my-bucket>.s3.eu-west-2.amazonaws.com`, but the CDK is creating a Cloudfront distribution with an S3 origin of `<my-bucket>.s3.us-east-2.amazonaws.com`, which of course doesn't exist.

I'm assuming that this is because of the nature of S3 bucket names, which are globally unique, and the bucket ARN does not contain the actual region in which the S3 bucket exists.

### Reproduction Steps

1. Manually create an S3 bucket in `eu-west-2`
2. Create a stack using the CDK which creates a CloudFront distribution, and has an S3 origin identified using `new origins.S3Origin(s3.Bucket.fromBucketArn())`
3. Deploy the stack to `eu-west-2`
4. Deploy the stack to `us-east-2`
5. Notice how the CloudFront distribution created by the stack located in `us-east-2` has an invalid domain name. The CDK appears to have assumed that the S3 bucket is located in the same region that the stack is located.

Here's my code used to configure the CloudFront distribution:

```typescript
new cloudfront.Distribution(this, 'CloudfrontDistribution', {
  defaultBehavior: {
    origin: appHttpOrigin, // instance of origins.HttpOrigin
    cachePolicy: cloudfront.CachePolicy.CACHING_DISABLED,
    viewerProtocolPolicy: cloudfront.ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
    compress: true,
  },
  additionalBehaviors: {
    // some other behaviours
    '/errors/*': {
      origin: new origins.S3Origin(s3.Bucket.fromBucketArn(this, 'S3BucketHttpErrors', 'arn:aws:s3:::<my-bucket>')),
      cachePolicy: cloudfront.CachePolicy.CACHING_DISABLED,
      compress: true,
    },
  },
  errorResponses: [
    {
      httpStatus: 503,
      responseHttpStatus: 503,
      responsePagePath: '/errors/5XX.html'
    },
    {
      httpStatus: 504,
      responseHttpStatus: 504,
      responsePagePath: '/errors/5XX.html'
    }
  ],
  domainNames: props.config.cloudfront.cnames.domains, // instance of string[]
  certificate, // instance of certificatemanager.ICertificate
  priceClass: cloudfront.PriceClass.PRICE_CLASS_100,
});
```

### What did you expect to happen?

The S3 origin should be configure with the correct URL of `<my-bucket>.s3.eu-west-2.amazonaws.com`

### What actually happened?

The S3 origin is incorrectly configured with the incorrect URL of `<my-bucket>.s3.us-east-2.amazonaws.com`

### Environment

  - **CDK CLI Version  :** 2.1.10
  - **Framework Version:** 1.105.0
  - **Node.js Version:** 14.15.3
  - **OS               :** Windows 10 Pro
  - **Language (Version):** TypeScript (3.9.9)

### Other

In the meantime, is it safe for me to use the console to manually change the origin to point to the correct region or will this cause issues with drift detection?

--- 

This is :bug: Bug Report

**Comment by njlynch** [comment]
As you noted, the bucket ARN does not contain enough information for us to correctly ascertain the region of the bucket. The simple solution is to import the bucket with a method that provides this information:

```ts
// Replace your fromBucketArn call with this:
s3.Bucket.fromBucketAttributes(this, 'S3BucketHttpErrors', {
  bucketArn: 'arn:aws:s3:::<my-bucket>',
  region: 'us-east-2',
});
```

That will set the proper bucket domain name attributes so the CloudFront Distribution can use the right domain.

**Comment by callumthomson** [comment]
@njlynch Ok thanks for the solution, but should the CDK be making such assumptions? Could at least fail or give a warning indicating that the required information is missing. It seems like an issue to me that the CDK will go ahead and configure something incorrectly like this.

**Comment by njlynch** [comment]
In these types of situations, we try to assume reasonable defaults for the majority cases. Users importing buckets often either are using the buckets in the stack's region or the region isn't important for their use-case; by defaulting domains to the current region, we can enable reasonable defaults without making the user explicitly provide the region to be able to import a bucket. Requiring the region to be explicitly set to use any of the domain properties would be a backwards-incompatible change that would impact many users and applications.
