### ISSUE TITLE
(aws-cognito): Incorrect default string attribute maxLen

### ISSUE THREAD

**Issue by phuctm97** [aws/aws-cdk#14870]
Docs said that `StringAttribute` default`maxLen` is 2048, but it actually is `256`

### Reproduction Steps

Add a user pool resource and configure a custom string attribute without `maxLen`.

### What did you expect to happen?

No `maxLen` or `maxLen = 2048`.

### What actually happened?

Go to Cognito Console, check the attribute, it said max len is 256.

### Environment

  - **CDK CLI Version  :** 1.106.0
  - **Framework Version:** 1.106.0
  - **Node.js Version:**  14
  - **OS               :** macOS Big Sur
  - **Language (Version):**  TypeScript

### Other

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
The console does autofill the max length field with 256 but this is not the actual limit. I was able to create a custom attribute of length 1024. See attached screenshot.

![Screenshot 2021-06-01 at 10 33 38](https://user-images.githubusercontent.com/16217941/120301589-ee296180-c2c4-11eb-8cb6-eae6630d12a9.png)

**Comment by phuctm97** [comment]
So it's the Congito Console bug, anyway we can report that?

**Comment by nija-at** [comment]
I don't know if it's a bug. It's just a suggested value that you can always modify.

You will need to reach out via AWS support.

**Comment by phuctm97** [comment]
Based on AWS docs, it is not possible to change the constraint of a custom attribute after it was created. Anyway, will close this and report error to AWS later. Thanks for checking.
