### ISSUE TITLE
(aws-cdk): Cannot create a retry a step in state machine without creating multiple states 

### ISSUE THREAD

**Issue by suryakola** [aws/aws-cdk#14871]
## :question: General Issue
Cannot create a retry a step in state machine without creating multiple states like how specify the same task in "next" here https://docs.aws.amazon.com/step-functions/latest/dg/tutorial-create-iterate-pattern-section.html but when we create a chain or do a .next from cdk it expects a unique, which made me create multiple states instead of just retry and my workflow looks like below just for 3 retries but if we have 10, my graph looks really ugly

![image](https://user-images.githubusercontent.com/84830364/119606529-5f25d080-be10-11eb-849e-1e0b783a6b8b.png)

so, is there a way we can retry the same state from cdk?

### Environment

  - **CDK CLI Version:** 
  - **Module Version:** 
  - **Node.js Version:** 
  - **OS:** 
  - **Language (Version):**

**Comment by NGL321** [comment]
Hey @suryakola!

It looks like there is a missed opportunity here to use the [`Choice` state](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-stepfunctions-readme.html#choice). This state will allow for dynamic retries. Remember, when declaring the state machine in CDK, you define your tasks and THEN order them. This allows you to create sub-loops (smaller state machines essentially).

In your case it should look something like this:

```ts
const filterSplit = new Task(...);
const findMatching = new Task(...);
const storeResults = new Task(...);
const retryWait = new Wait(...);

const findMatchSteps = Chain
	.start(filterSplit)
	.next(findMatching)
	.next(storeResults);

const def = findMatchSteps
	.next(new Choice(this, 'IsFinished')
		.when(
			Condition.booleanEquals('$.successState', true),
			new Succeed(this, 'Done')
		)
		.when(
			Condition.numberGreaterThan('$.retryCount', 10),
			new Fail(this, 'Failed')
		)
		.otherwise(retryWait.next(findMatchSteps)));

new StateMachine(this, 'SM', {
	definition: def
});
```

The above of course has a total of 10 possible retries and on each, retries the sub-component `findMatchSteps`.

Please let me know if this fixes your problem!

😸 😷

**Comment by suryakola** [comment]
Hi @NGL321 I will give a try to check if it works or not, but Task class from software.amazon.awscdk.services.stepfunctions is deprecated in java so we cannot use it.

**Comment by peterwoodworth** [comment]
The Task construct is deprecated because the [Stepfunctions-Tasks](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-stepfunctions-tasks-readme.html) library exists! Use the constructs in this library in place of the generic tasks in the example

**Comment by suryakola** [comment]
Thanks a lot @NGL321  it worked :)
