### ISSUE TITLE
Rest API deploymentStage undefined

### ISSUE THREAD

**Issue by stefwoj** [aws/aws-cdk#14880]
### The Question

I am trying to add multiple base path mappings for my APIs. The stage however is always undefined, which requires manual setting in the GUI. the RestApis are defined in another stack in another repository and rely on CDK to automatically create deployment/stage objects. This works apparently, except when trying to refer to the deployment stage below:
 
        Object.entries(apiIds).forEach(
            ([key, value]) => {
                const api = apigateway.RestApi.fromRestApiId(this, key + 'Api', value);
                dvpDomain.addBasePathMapping(api, {
                    basePath: key,
                    stage: api.deploymentStage // doesn't appear to work yet
                });
            });

### Environment

  - **CDK CLI Version:** 1.105.0 (build 4813992)
  - **Module Version:** 1.105.0
  - **Node.js Version:** v12.18.4
  - **OS:** MacOS Catalina 10.15.7
  - **Language:** Typescript

**Comment by peterwoodworth** [comment]
Hey @stefwoj, have you tried setting the stage for the RestApi on declaration using the [`deploy`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-apigateway.RestApi.html#deploy) and [`deployOptions`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-apigateway.StageOptions.html#stagename) properties?

The `deploymentStage` prop says "API Gateway stage that points to the latest deployment (if defined)", so I would guess that the property isn't supposed to work if the stage isn't set before deployment

**Comment by stefwoj** [comment]
Hey @peterwoodworth, I just tried setting the stage/deployment manually in the repo that contains the example code and it works. I had created the stage/deployment in the repo that creates the `restApi` object. It would still have been nice if the `fromRestApiId` function returned the `deploymentStage` which is supposedly set when the `deploy` field is enabled, even though it's in another repo.

**Comment by peterwoodworth** [comment]
@stefwoj I've been researching this, neither the `fromRestApiId` or `fromRestApiAttributes` functions have the ability to return the `deploymentStage`. They don't actually get data from AWS, so there's no way to get the deployment stage of an existing Api. Our imported resources are typically pretty barebones and minimal, however there are some exceptions. Unfortunately though, this isn't an exception.

The difference between `fromRestApiId` and `fromRestApiAttributes` is that the latter will allow you to use the `root` property. This isn't obvious when looking at our documentation, it should probably be easier to know what you're getting when you're importing resources.

**Comment by peterwoodworth** [comment]
We're going to update our documentation to make the limitations of importing resources more clear. Let me know if you have any more concerns regarding this issue 😄
