### ISSUE TITLE
(@aws-cdk/custom-resources): NodeJs / Python Sample Code Links Dead

### ISSUE THREAD

**Issue by ayachnes2** [aws/aws-cdk#14895]
In the [S3Assert](https://docs.aws.amazon.com/cdk/api/latest/docs/custom-resources-readme.html#s3assert) section on the [custom resources module overview page](https://docs.aws.amazon.com/cdk/api/latest/docs/custom-resources-readme.html), the last sentence of the first paragraph has two dead links:

Verbatim, the last sentence is:

> See the source code for the [construct](https://docs.aws.amazon.com/cdk/api/latest/docs/test/provider-framework/integration-test-fixtures/s3-assert.ts) and [handler](https://docs.aws.amazon.com/cdk/api/latest/docs/test/provider-framework/integration-test-fixtures/s3-assert-handler/index.py).

`construct` should link to this: https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/custom-resources/test/provider-framework/integration-test-fixtures/s3-assert.ts
`handler` should link to this: https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/custom-resources/test/provider-framework/integration-test-fixtures/s3-assert-handler/index.py

---

This is a 📕 documentation issue

**Comment by rix0rrr** [comment]
Thanks!
