### ISSUE TITLE
(aws-eks): Is there a KubernetesVersion.V1_20? 

### ISSUE THREAD

**Issue by Ashleyhen** [aws/aws-cdk#14907]
Is there a KubernetesVersion.V1_20? The newest version V1_19 in @aws-cdk/aws-eks:"^1.106.1" appears to be deprecated 

![image](https://user-images.githubusercontent.com/84979436/120000715-1bae9c00-bfa1-11eb-8600-0e2f01685fd7.png)

**Comment by shubham391** [comment]
@Ashleyhen CDK doesn't directly support 1.20 at the moment. There's an issue created to add this support: https://github.com/aws/aws-cdk/issues/14756

There is a workaround to this though which worked for me: https://github.com/aws/aws-cdk/issues/14756#issuecomment-849635115

**Comment by peterwoodworth** [comment]
The next CDK version to release should include this PR that has been approved: https://github.com/aws/aws-cdk/pull/14758

In the meantime the workaround already posted should work just fine
