### ISSUE TITLE
(@aws-cdk/aws-events): detailType property does not translate to `detail-type` JSON field on Archive creation

### ISSUE THREAD

**Issue by anafaggiano** [aws/aws-cdk#14905]
During an Archive creation, when defining an event pattern to filter events sent to the soon-to-be-created archive, **the `detailType` field does not translate to `detail-type` in the produced event pattern**. 

It stays as `detailType` in the produced JSON filtering pattern used by the archive. This results in us not being able to set the `detail-type` field on archive creation.

### Reproduction Steps

```
class OurStack extends Stack {
  constructor(scope: Construct, id: string, props: OurStackProps) {
    super(scope, id, props);

    // ARCHIVE
    new Archive(this, 'ourArchive', {
      eventPattern:  {
      detail: { importantId: [{ exists: true }] },
      detailType: ['processed-record'],
      source: [custom.source],
    },
      sourceEventBus: EventBus.fromEventBusArn(
        this,
        'ImportedEventBus',
        `arn:aws:events:${props.env?.region}:${props.env?.account}:event-bus/${props.eventBusName}`,
      ),
      archiveName: `${props.archiveId}-archive`,
    });
  }
}
```

### What did you expect to happen?

In the AWS console, for the JSON to be:
```
{
  "detail-type": [
    "processed-record"
  ],
  "detail": {
    "importantId": [
      {
        "exists": true
      }
    ]
  },
  "source": [
    "custom.source"
  ]
}
```
and subsequently, for events to be filtered on that schema.

### What actually happened?

In the AWS console, the actual JSON is:
```
{
  "detailType": [
    "processed-record"
  ],
  "detail": {
    "importantId": [
      {
        "exists": true
      }
    ]
  },
  "source": [
    "custom.source"
  ]
}
```
and subsequently, events don't get filtered since the Cloudwatch field is `detail-type`

### Other 

We are using the `EventPattern` interface in a `Rule` too, and the event pattern `detailType` resolves correctly to `detail-type` for the created rule (in the same stack)

### Environment

  - **CDK CLI Version  : N/A
  - **Framework Version:*1.102.0*
  - **Node.js Version: *14.16.0* 
  - **OS               : *MacOs Big Sur 11.2.3*
  - **Language (Version):*Typescript 4.2.4* 

### Other

N/A

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
Yep, a translation of `EventPattern` should have been done (like in `Rule`), but the author of `Archive` forgot to do that.

**Comment by DaWyz** [comment]
Hey @anafaggiano , I think it's my bad. The quick fix for you would be to set `detail-type` directly instead of `detailType` and cast it as `EventPattern`.

I will try and work on a fix today.

**Comment by anafaggiano** [comment]
> Hey @anafaggiano , I think it's my bad. The quick fix for you would be to set `detail-type` directly instead of `detailType` and cast it as `EventPattern`.
> 
> I will try and work on a fix today. I'm planning to extract the `renderEventPattern` method from the rule in the utility file so both `Rule` and `Archive` constructs can use it. The fix should be backward compatible (It will try to convert `detailType` to `detail-type` only if it exists.)

Thank you, @DaWyz !
