### ISSUE TITLE
(aws-appsync): the api key expiry date keeps changing after each deploy 

### ISSUE THREAD

**Issue by apoorvmote** [aws/aws-cdk#14915]
I have created api key for graphql api authentication and set expiry date after 365 days from deployment. See the link below.

https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.Expiration.html#static-aftert

It says `Expire once the specified duration has passed since deployment time.`

It keeps recalculating expiry date on every deploy and updating expiry date. 

Is that intended behaviour or it should have been fixed 365 days from first deploy?

### Reproduction Steps

```ts
const queryApi = new GraphqlApi(this, 'grwabGraphqlApi', {
      name: 'grwabApi',
      schema: Schema.fromAsset('graphql/schema.graphql'),
      authorizationConfig: {
        defaultAuthorization: {
          authorizationType: AuthorizationType.USER_POOL,
          userPoolConfig: {
            userPool: authPool,
          }
        },
        additionalAuthorizationModes: [
          {
            authorizationType: AuthorizationType.API_KEY,
            apiKeyConfig: {
              expires: Expiration.after(Duration.days(365))
            }
          }
        ]
      }
    })
```
### What did you expect to happen?

I was hoping it would set expiry date after 365 days from first deploy and stay there.

### What actually happened?

It recalculates expiry date based on each deploy time as starting time and added 365 days to it and updates the expiry date.

### Environment

  - **CDK CLI Version  :** 1.106.1
  - **Framework Version:** 1.106.1
  - **Node.js Version:**  v.14.17.0
  - **OS               :** Ubuntu 20.04
  - **Language (Version):**  Typescript ~3.9.7

### Other

--- 

This is :bug: Bug Report

**Comment by otaviomacedo** [comment]
Hi, @apoorvmote. Your expectation makes sense.

I am unassigning and marking this issue as `p2`, which means that we are unable to work on this immediately. Also, keep in mind that this is an experimental library and some of these behaviors haven't been fully defined yet.

We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://join.slack.com/t/cdk-dev/shared_invite/zt-mso6p56d-qJp7SOTBvMaQuDrx7R2wHg) to solicit support for reprioritization.

**Comment by rmarscher** [comment]
This also seems to invalidate the previous key and generate a new key with the new expiration date on deploys with `expires: Expiration.after(Duration.days(365))` which is problematic.

To workaround, I used a fixed timestamp for the expiration (`Expiration.atDate()` or `Expiration.atTimestamp()`) and then will have to remember to update it manually.
