### ISSUE TITLE
updating aws_cdk.core.Stack id leaves previous CF stack deployed/behind

### ISSUE THREAD

**Issue by gliptak** [aws/aws-cdk#14911]
updating aws_cdk.core.Stack id leaves previous CF stack deployed/behind

### Reproduction Steps

```
cdk init app --language python
source .venv/bin/activate
python -m pip install -r requirements.txt
cdk deploy
```

At this point `AppStack` is deployed.

Update

```
app = core.App()
AppStack(app, "AppStack")
```

to

```
app = core.App()
AppStack(app, "company-AppStack")
```
and run

```
cdk deploy
```

### What did you expect to happen?

After creating new CF stack, old CF stack removed.

### What actually happened?

There are now two CFs deployed, both old and new one, Running `cdk destroy` only deletes the new CF stack leaving old CF behind.

### Environment

  - **CDK CLI Version  :** 1.105.0 (build 4813992)
  - **Framework Version:** 1.105.0
  - **Node.js Version:** v14.16.1 
  - **OS               :** Linux
  - **Language (Version):** Python (3.8.10)

### Other

https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.core/Stack.html

https://github.com/aws/aws-cdk/issues/9662
https://github.com/aws/aws-cdk/issues/4733

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
This is true. Unfortunately, given the information we have there's not a lot we can do about it.

**Comment by gliptak** [comment]
@rix0rrr what did you mean by "Unfortunately, given the information we have there's not a lot we can do about it."? Do you need more details on reproducibility?
