### ISSUE TITLE
ecr-assets: can't use docker build options like --ssh/--secret available when BUILDKIT is enabled

### ISSUE THREAD

**Issue by hizvi** [aws/aws-cdk#14910]
docker build options `--ssh` / `--secret` can not be used with `aws-ecs.AssetImage` or `aws-ecr-assets.DockerImageAsset`

these options are available with docker build when `DOCKER_BUILDKIT=1` is enabled.

### Use Case

Docker image builds may require access to private resources that require ssh keys and/or secrets. Docker BuildKit allows mounting them safely. 

### Proposed Solution

The docker utility in cdk already has options for build args and such. the `--ssh` and `--secret` options can be implemented similarly. 

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by peterwoodworth** [comment]
@SoManyHs can you comment on why this is an ecr-assets issue?

**Comment by eladb** [comment]
Seems like a useful addition, contributions are welcome.

**Comment by rob3c** [comment]
Lack of support for BuildKit options like `--secret` and `--ssh` is a problem everywhere in the codebase where a `docker build` command is created:

- _packages/@aws-cdk/core/lib/bundling.ts_
- _packages/cdk-assets/lib/private/docker.ts_
- maybe elsewhere

None of the modern docker args like those for BuildKit are explicitly supported via options params, and there's no mechanism for decorating any CDK-created docker commands with additional args to allow for CLI updates that haven't been coded for yet in the CDK.

In the meantime, I've posted a placeholder solution for my use cases to this gist:

https://gist.github.com/rob3c/8bf845918bc5270c5e22da0674081f90

It has functions `assetCodeFromDockerBuildKitBuild()` and `dockerImageFromBuildKitBuild()`.

Here's sample usage showing lambda code built using BuildKit `--secret` and `--ssh` args along with an extra Docker `--progress` arg:
```typescript
new aws_lambda.Function(this, 'MyLambda', {
  runtime: aws_lambda.Runtime.DOTNET_CORE_3_1,
  code: assetCodeFromDockerBuildKitBuild(buildContextDir, {
    buildArgs: { CONFIG: 'Release' },
    secrets: { nuget_config: 'NuGetPrivateFeed.Config' },
    additionalArgs: {
      '--progress': 'plain',
      '--ssh': 'myserver=$HOME/.ssh/myserver_rsa',
    },
  }),
  handler: 'MyAssembly::MyNamespace.MyHandlerClass::MyHandlerMethod',
});
```

**Comment by hxy1991** [comment]
@peterwoodworth @eladb 
Hello, is this feature being implemented?

How can I achieve the same effect as "DOCKER_BUILDKIT=1 docker build --secret id=aws,src=$HOME/.aws/credentials --progress=plain" through awscdk/awsecrassets

```go
asset := awsecrassets.NewDockerImageAsset(stack, jsii.String("dockerImage"), &awsecrassets.DockerImageAssetProps{
	Directory: jsii.String(path.Join(dir, "./app")),
})
```

I really need to pass aws/credentials when building the docker image, because I want to import another aws codecommit (golang project) as a module.

```
package main

import (
	"git-codecommit.eu-central-1.amazonaws.com/v1/repos/xxx.git/service/xxx"
)
```

**Comment by rob3c** [comment]
> How can I achieve the same effect as "DOCKER_BUILDKIT=1 docker build --secret id=aws,src=$HOME/.aws/credentials --progress=plain" through awscdk/awsecrassets

@hxy1991 See my message and the gist I posted a link to. There are functions that produce `DockerImage` and `AssetCode` CDK instances. Just add the single source file to a CDK v2 project and you can use the functions for arbitrary Docker BuildKit builds with the CDK. Otherwise, you'll be stuck waiting for this issue to be addressed that's been open for 7 months and counting now. It doesn't seem to be a priority.

**Comment by RichiCoder1** [comment]
@eladb as a simple half step to adding all the new BuildKit args, would a generic `additionalArgs` escape hatch be acceptable?

**Comment by danw-mpl** [comment]
@rob3c Would you know how to use your code with an `ecs.ContainerImage.fromAsset(...)`?

**Comment by lox** [comment]
Buildkit is now the default in Docker for Mac. This means pretty much any of the docker build integrations currently across cdk won't work. 

https://github.com/aws/aws-cdk/issues/21990

**Comment by newit-manhp** [comment]
It seem currently cdk not support with ssh/secret option.
To build docker image with private git repo access, I can workaround with this: https://vsupalov.com/build-docker-image-clone-private-repo-ssh-key/
Using ARG + multiple stage + buildArg to build the image

**Comment by simonloach** [comment]
Please work on this, this is a blocker for my team

**Comment by rcraigfiedorek** [comment]
@hizvi could this issue be reopened? It has only been partially solved: the `--secret` option is now available but `--ssh` still is not.
