### ISSUE TITLE
(aws-ecs): AddCapacityOptions not allowing associate_public_ip_address=True while specifying AZ

### ISSUE THREAD

**Issue by gshpychka** [aws/aws-cdk#14929]
When adding capacity to a ECS cluster, I can't specify the availability zones I want while also setting associate_public_ip_address to True.

### Reproduction Steps

Apologies for an incomplete sample, I hope this is enough to illustrate the issue

```
cluster = ecs.Cluster(
    . . .
    capacity=ecs.AddCapacityOptions(
        associate_public_ip_address=True,
        vpc_subnets=ec2.SubnetSelection(
            subnet_type=ec2.SubnetType.PUBLIC,
            availability_zones=['eu-west-1b']
        )
        . . .
    )
)
```

### What did you expect to happen?

I expected it to successfully select Public subnets in the specified AZ

### What actually happened?

During synth, there's an error: 
`jsii.errors.JSIIError: To set 'associatePublicIpAddress: true' you must select Public subnets`

### Environment

  - **CDK CLI Version  :** 1.106.1
  - **Framework Version:** 1.106.1

--- 

This is :bug: Bug Report

**Comment by gshpychka** [comment]
I now realize that I cannot assign public IP to a EC2-based ECS service, so my use-case is not relevant. Not sure what that says about the issue overall.

**Comment by SoManyHs** [comment]
@gshpychka That's corect, I'll go ahead and close this issue then!
