### ISSUE TITLE
(module name): short issue description

### ISSUE THREAD

**Issue by wascou** [aws/aws-cdk#14926]
I try to build a serverless cluster in a default VPC without nat gateways.
There's a mutual dependency between ServerlessCluster and VPC with no NatGateways.
A VPC can be created with nat gatways, but a serverless cluster requires to have a private subnet.
If you provide a natgateways=0 param, then module is raising an exception as configuration has a PRIVATE subnet.

Resources:
1. Doc of VPC [construct](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-ec2-readme.html#advanced-subnet-configuration) 
2. [Commit ](https://github.com/aws/aws-cdk/pull/8817/files/10ae6cc7359a9e29f4c7f2c52684d6eb86d71ce7) with code describing the added check that mess things up

### Reproduction Steps
```
    const vpc = new ec2.Vpc(this, 'rds-vpc', { 
      natGateways: 0    
    });
    const cluster = new rds.ServerlessCluster(this, 'aurora-cluster', {
      engine: rds.DatabaseClusterEngine.AURORA_MYSQL,
      enableDataApi: true,
      parameterGroup: rds.ParameterGroup.fromParameterGroupName(this, 'ParameterGroup', 'default.aurora-mysql5.7'),
      vpc,
      credentials: rds.Credentials.fromSecret(databaseSecret),
    });
```

### What did you expect to happen?
The more natural thing would be to let serverless handle the vpc subnet for us by creating it.

### What actually happened?
I received either 

```
Error: If you do not want NAT gateways (natGateways=0), make sure you don't configure any PRIVATE subnets in 'subnetConfiguration' (make them PUBLIC or ISOLATED instead)
```

either 

```
Error: There are no 'Private' subnet groups in this VPC. Available types: Isolated,Public
```

### Environment

  - **CDK CLI Version  : 1.106.1**
  - **Framework Version: c832c1b**
  - **Node.js Version: 14.17.0** 
  - **OS               : Windows**
  - **Language (Version): Node** 

### Other

--- 

This is :bug: Bug Report

**Comment by wascou** [comment]
And as always, I'm finding the solution just after having submitted the issue !

In the ServerlessCluster, we can put a `vpcSubnets` params describing in which kind of subnet type we want to put the database.

We can then set this up:

```
     vpcSubnets: {
        subnetType: ec2.SubnetType.ISOLATED
      },

```

Doc [here](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-rds-readme.html#starting-an-instance-database).

**Comment by skinny85** [comment]
Glad you figured it out @wascou 🙂.
