### ISSUE TITLE
(aws-kms): sse-s3 key policy not updated

### ISSUE THREAD

**Issue by warden** [aws/aws-cdk#14934]
I have defined a bucket like this, to use the `aws/s3` SSE-S3 managed key:

```ts
const artifactBucket = new Bucket(this, 'artifacts', {
    blockPublicAccess: BlockPublicAccess.BLOCK_ALL,
    encryption: BucketEncryption.S3_MANAGED,
    versioned: true,
    removalPolicy: RemovalPolicy.DESTROY,
});
```

Now, for the cross-account pipeline deployment (launch pipeline from main account, grant access from the target account to read from the main's account bucket above) I am granting access to this bucket to **other IAM accounts** with:
```
artifactBucket.grantReadWrite(new ArnPrincipal(arn:aws:iam::${TEST}:role/PipelineRole`));
```

This works for the Bucket policy, but seems it misses adding permissions on the KMS managed key, I can see in KMS that the key policy is not updated and only contains the bucket-owning account principal.

I tried adding the permissions like this:

```ts
    const s3EncryptionKey = Key.fromKeyArn(this, "S3EncryptionKey", `arn:aws:key:::key/XXX`);
    s3EncryptionKey.grantDecrypt(new ArnPrincipal(acceptancePipelineRole.roleArn));
    s3EncryptionKey.addToResourcePolicy(new PolicyStatement({
      effect: Effect.ALLOW,
      principals: [
        new ArnPrincipal(new ArnPrincipal(arn:aws:iam::${TEST}:role/PipelineRole`)),
      ],
      resources: ['*'],
      actions: [
        "kms:Decrypt",
        "kms:DescribeKey",
      ],
    }));
```

but I can see those are no-ops as well... what's the correct way to do this then?

```
aws-cdk: 1.106.1
```

**Comment by warden** [comment]
I'm reading this and I start to get a feeling that the SSE-S3 key that is auto-created doesn't have the optional Policy attached to it, so I cannot modify it - and indeed if I add false to addToResourcePolicy(...,false) then cdk fails.
Is my feeling correct that I need to have to use CMK in such case instead?

**Comment by skinny85** [comment]
Hey @warden ,

thanks for opening the issue.

> Is my feeling correct that I need to have to use CMK in such case instead?

Yes, you need to use a CMK for cross-account CodePipeline.

> If that's the case, how can I leverage the [SSE-S3](https://docs.aws.amazon.com/AmazonS3/latest/userguide/serv-side-encryption.html) as I only see `S3_MANAGED` in `BucketEncryption` to use that key by default for objects instead of specyfing `encryptionKey` through all the pipeline objects?

Simply specify `encryption` as `BucketEncryption.KMS`. The CDK will take care of the rest.

**Comment by warden** [comment]
Hi @skinny85,

Thanks for quick response. Indeed, I think I misintepreted [this blog post](https://aws.amazon.com/about-aws/whats-new/2020/12/amazon-s3-bucket-keys-reduce-the-costs-of-server-side-encryption-with-aws-key-management-service-sse-kms/) and I thought that I have to use `SSE-S3` not to pay for extra KMS traffic, now that I re-read it, I understand that if the CMK is just on the bucket-level, then all should be fine.

**Comment by skinny85** [comment]
Glad you got yourself unblocked!

> (still curious then what it the S3_MANAGED option for?)

It's for using the S3-managed KMS Key. You can't use it for cross-account CodePipelines though.
