### ISSUE TITLE
(aws-cloudfront): Invalid Cloudformation specification for AWS::Cloudfront::Function

### ISSUE THREAD

**Issue by touzoku** [aws/aws-cdk#14932]
The newly released `AWS::Cloudfront::Function` has a mistake in specification and therefore has an invalid autogenerated `cloudfront.CfnFunction` construct code.

[Here in the documentation ](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudfront-function.html#cfn-cloudfront-function-functionconfig) it says that `FunctionConfig` is not required, while in practice it is. Omitting it results in the `Resource handler returned message: "null" (RequestToken: ...., HandlerErrorCode: InternalFailure)` error.

I know it is probably not a CDK bug, since the code is autogenerated, but I have no idea where to file the Cloudformation specification bugs, please bear with me.

### Reproduction Steps

The following code fails even though TSC perfectly compiles it due to `functionConfig` being marked as optional:
```typescript
new cloudfront.CfnFunction(this, 'Function', {
    name: 'TestFunction',
    autoPublish: true,
    functionCode: 'function handler(event) { return event.request }',
})
```

### What did you expect to happen?

Cloudfront Function should be created.

### What actually happened?

It fails with the `Resource handler returned message: "null"` error.

### Environment

  - **CDK CLI Version  :** 2.0.0-rc.5
  - **Framework Version:** 2.0.0-rc.5
  - **Node.js Version:** v16.2.0
  - **OS               :** MacOS 10.15.7
  - **Language (Version):** all

### Other

Specifying `functionConfig` as follows makes it work:

```typescript
new cloudfront.CfnFunction(this, 'Function', {
  name: 'TestFunction',
  autoPublish: true,
  functionCode: 'function handler(event) { return event.request }',
  functionConfig: {
    comment: '',
    runtime: 'cloudfront-js-1.0',
  }
})
```

--- 

This is :bug: Bug Report

**Comment by touzoku** [comment]
Also, while we are at it, could you please instruct how to use `this.physicalName` in this case?

I am trying to use it as follows from looking at similar code at dynamodb/table.ts and rds/instance.ts:

```typescript
import { Construct } from 'constructs'
import {  aws_cloudfront as cloudfront, Resource } from 'aws-cdk-lib'

export interface CloudfrontFunctionProps {
  name?: string
  autopublish?: boolean
  code: string
}
export class CloudfrontFunction extends Resource {
  constructor(scope: Construct, id: string, props: CloudfrontFunctionProps) {
    super(scope, id, {
      physicalName: props.name,
    })
    const func = new cloudfront.CfnFunction(this, 'Function', {
      name: this.physicalName,
      autoPublish: props.autopublish ?? true,
      functionCode: props.code,
      functionConfig: {
        comment: '',
        runtime: 'cloudfront-js-1.0',
      },
    })
  }
}
```

but it fails during synth with `Error: Resolution error: Supplied properties not correct for "CfnFunctionProps" name: required but missing. at ValidationResult.assertSuccess ...`

I was under assumption that CDK must generate a random physical name in such case.

Calling it as follows fixes the issue, but it does not match the code for similar thing in dynamodb/rds, for example.
 `{ name: props.name ?? this.generatePhysicalName() }`

**Comment by hoegertn** [comment]
You can look at https://github.com/aws/aws-cdk/pull/14511 which implements the L2 for CF Functions.

**Comment by njlynch** [comment]
@touzoku - Thanks for the bug report. You can file issues with the CloudFormation documentation here: https://github.com/awsdocs/aws-cloudformation-user-guide/issues. 
I've created a quick fix there on your behalf: https://github.com/awsdocs/aws-cloudformation-user-guide/pull/993

In regards to the `physicalName`, the difference between the Function and things like a DynamoDB Table are that the name is optional for a Table, but required for a Function; with the table, `physicalName` can be undefined.

As @hoegertn said, I'd encourage you to look at (and use!) the newly-released L2 for Function, which should paper over these details for you and make it easier to work with.

I'm going to close this out in favor of the above update to the docs. Please feel free to comment and mention me if you have any other follow-ups.
