### ISSUE TITLE
(eks): KubernetesObjectValue returns the warning msg from kubectl

### ISSUE THREAD

**Issue by zxkane** [aws/aws-cdk#14933]
Have a code snippet to fetch the value of Kubernetes object,

```ts
    const albAddress = new eks.KubernetesObjectValue(this, 'Nexus3ALBAddress', {
      cluster,
      objectType: 'ingress',
      objectNamespace: nexus3Namespace,
      objectName: `${nexus3ChartName}-sonatype-nexus`,
      jsonPath: '.status.loadBalancer.ingress[0].hostname',
    });
```

The k8s object uses the deprecated object in latest Kubernetes, for example,

```
kubectl get -n default ingress nexus3-sonatype-nexus -o=jsonpath='{.status.loadBalancer.ingress[0].hostname}'
```

> Warning: extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
> k8s-default-nexus3so-4674f0d6c2-2064499656.cn-northwest-1.elb.amazonaws.com.cn

 Though the command runs without error. The output of `kubectl` has a warning message for the deprecated usage.

Have a look at the implementation of `get` handler, it redirects the stderr to stdout. Any reason for it?

https://github.com/aws/aws-cdk/blob/ed72ad322a2739709cad91759ea18e159f28f795/packages/%40aws-cdk/aws-eks/lib/kubectl-handler/get/__init__.py#L74

### What did you expect to happen?

Exclude the message in `stderr` from the output of `KubernetesObjectValue`.

### Environment

  - **CDK CLI Version  :** 1.104.0
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):** 

### Other

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment]
Hi @zxkane - Thanks for reporting this. 

> Have a look at the implementation of get handler, it redirects the stderr to stdout. Any reason for it?

The reasoning here being that if `stderr` exists, the command actually fails and an exception is throw with the complete output.
It seems like this reasoning may not always be correct, but i'm also not a 100% convinced this warning isn't being printed to `stdout` - Have you verified this? 

In any case, I acknowledge its an issue and I am unassigning and marking this issue as `p2`, which means that we are unable to work on this immediately.

We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://join.slack.com/t/cdk-dev/shared_invite/zt-mso6p56d-qJp7SOTBvMaQuDrx7R2wHg) to solicit support for reprioritization.

**Comment by zxkane** [comment]
It’s a behavior occurring in EKS v1.19 which is the default version of EKS.

I can confirm the warning output is to `stderr`. The warning message is suppressed if redirecting the `stderr` to `/dev/null`.

```bash
$ kubectl get -n default ingress nexus3-sonatype-nexus -o=jsonpath='{.status.loadBalancer.ingress[0].hostname}'            
Warning: extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
k8s-default-nexus3so-65be6f6b46-325415033.ap-east-1.elb.amazonaws.com%                                                                       
$ kubectl get -n default ingress nexus3-sonatype-nexus -o=jsonpath='{.status.loadBalancer.ingress[0].hostname}' 2>/dev/null
k8s-default-nexus3so-65be6f6b46-325415033.ap-east-1.elb.amazonaws.com% 
```

**Comment by briancaffey** [comment]
@zxkane I am experiencing the same issue with `KubernetesObjectValue`. It would be nice if this worked correctly. I'm currently getting around this by annotating my Ingress:

```typescript
export const appIngress = {
  apiVersion: 'networking.k8s.io/v1',
  kind: 'Ingress',
  metadata: {
    name: 'app-ingress',
    namespace: 'app',
    annotations: {
      'kubernetes.io/ingress.class': 'alb',
      'alb.ingress.kubernetes.io/scheme': 'internet-facing',
      'alb.ingress.kubernetes.io/tags': 'Environment=test',
    },
  },
  ...
```

 and then doing a `.fromLookup`:

```typescript
    const alb = elbv2.ApplicationLoadBalancer.fromLookup(this, 'appAlb', {
      loadBalancerTags: {
        Environment: 'test'
      },
    });
```

Then I can do: 

```ts
    new cdk.CfnOutput(this, 'apiUrl', { value: alb.loadBalancerDnsName });
```

**Comment by RadekDvorak** [comment]
Hello, the stderr handling may be less than ok for me as well. When I try getting ingress hostname there is a throttling message in the output. Unsurprisingly the following CNAME update fails. Can we reopen this issue, please? @iliapolo 

I have verified the retured hostname is correct.

> 1 validation error detected: Value '{AWS_INSTANCE_CNAME=0930 14:56:58.741861 13 request.go:655] Throttling request took 1.170805758s, request: GET:https://redacted.gr7.eu-central-1.eks.amazonaws.com/apis/networking.istio.io/v1beta1?timeout=32s 'k8s-redacted.eu-central-1.elb.amazonaws.com}' at 'attributes' failed to satisfy constraint: Map value must satisfy constraint: [Member must have length less than or equal to 1024, Member must have length greater than or equal to 0, Member must satisfy regular expression pattern: ^([a-zA-Z0-9!-~][ \ta-zA-Z0-9!-~]*){0,1}[a-zA-Z0-9!-~]{0,1}$] (Service: AWSServiceDiscovery; Status Code: 400; Error Code: InvalidInput; Request ID: 49adb279-d52f-4e31-929e-4821d1c2a7a7; Proxy: null)
