### ISSUE TITLE
Python construct to generate and use Pipenv for package management

### ISSUE THREAD

**Issue by gliptak** [aws/aws-cdk#14930]
Python construct to generate and use Pipenv for package management

https://packaging.python.org/tutorials/managing-dependencies/

### Use Case

Currently generated Python construct sample app uses `virtualenv`

### Proposed Solution

Generate and use Pipenv for package management instead

### Other

https://github.com/aws/aws-cdk/issues/9324

* [x] :wave: I may be able to implement this feature request
* [x] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by nija-at** [comment]
Why is `pipenv` preferred over `virtualenv`?

**Comment by gliptak** [comment]
@nija-at as above linked page https://packaging.python.org/tutorials/managing-dependencies/ states, `Pipenv` is the standard dependency management tooling

**Comment by offbyone** [comment]
Pipenv isn't the standard, per se, but rather it's _a_ tool recognized by the Python Packaging group as a useful way to think about dependencies. There are, however, many other ways, and most of them roll up to "build a virtualenv and use that". Given that virtualenv is directly supported in the stdlib, that's probably the right mechanism to ship by default in the CDK Python construct example, and I'd recommend sticking with it on the basis of that.

**Comment by brettcannon** [comment]
To be very clear/nit-picky, virtualenv is not in the stdlib, venv is. Virtualenv is a PyPA project which does extra stuff on top of venv.

And as @offbyone said, pipenv is _a_ recommended tool, but it isn't _the_ recommended tool (basically the people who wrote those docs decided to take an opinionated stance to give clear direction and went with pipenv).

**Comment by nija-at** [comment]
@gliptak - given what @brettcannon and @offbyone, I'm inclined to close this issue and say that we will support only `virtualenv` for now. 
We can revisit this at a later time if the tooling and recommendations change.

You can always build your own pipenv based construct library and publish this out. Check out projen that helps you set this up quickly - https://github.com/projen/projen. We'll be happy to add a link to it from the README of our package.
