### ISSUE TITLE
📊Tracking: AWS APIGateway V2 - Websocket APIs

### ISSUE THREAD

**Issue by nija-at** [aws/aws-cdk#14935]
Add your +1 👍  to help us prioritize high-level constructs for this service
--- 

### Overview:

[AWS Docs](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-websocket-api.html)  

### Maturity: Experimental

See the [AWS Construct Library Module Lifecycle doc](https://github.com/aws/aws-cdk-rfcs/blob/master/text/0107-construct-library-module-lifecycle.md) for more information about maturity levels.

### Implementation:

See the [CDK API Reference](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-apigatewayv2-readme.html#websocket-api) for more implementation details.

### Issue list:

--- 
This is a  📊Tracking Issue

**Comment by evgenyka** [comment]
Closing Tracking issue.
