### ISSUE TITLE
`from_managed_policy_name` method in `aws_iam` not working as advertised (description below)

### ISSUE THREAD

**Issue by AdminTurnedDevOps** [aws/aws-cdk#14941]
`aws_iam` in the AWS CDK has a method called `from_managed_policy_name`. The definition of the method states on line `5144` that you only need to know the name of the policy. However, that's not true. The `from_managed_policy_name` method requires you to add in the `scope` and `id`

### Reproduction Steps

Code below of what fails:

```iam_role.add_managed_policy(aws_iam.ManagedPolicy.from_managed_policy_name(
            managed_policy_name='AmazonElasticSearchLambdaFullAccess'
        ))
```

### What did you expect to happen?

Expected the ability to add the customer managed policy

### What actually happened?

Received an error that I was missing 2 required params, `scope` and `id`

`TypeError: from_managed_policy_name() missing 2 required positional arguments: 'scope' and 'id'`

### Environment

  - **CDK CLI Version: 1.106.1 (build c832c1b)
  - **OS               : MacOS Big Sur
  - **Language (Version): Python 3.9.5

This is :bug: Bug Report

**Comment by peterwoodworth** [comment]
Hey @AdminTurnedDevOps, thanks for submitting this issue

`scope` and `id` are parameters that the CDK requires whenever you declare a construct in your CDK code. You can read about these params [here](https://docs.aws.amazon.com/cdk/latest/guide/constructs.html#constructs_init)

The `props` parameter is different for each construct, and [in this case](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-iam.ManagedPolicy.html#static-fromwbrmanagedwbrpolicywbrnamescope-id-managedpolicyname) the only thing you have to pass in to the `props` parameter is `managedPolicyName`.

Here's an example of using this function:

```py
elasticSearchLambdaManagedPolicy = iam.ManagedPolicy.from_managed_policy_name(self, "MyElasticSearchLambdaManagedPolicy", "AmazonElasticSearchLambdaFullAccess")
```

You should usually input `this` (or `self` for Python) for the scope, and the `id` can be anything you want!

Hope this all helps, let me know if you have additional questions
