### ISSUE TITLE
codepipeline: Deploy EKS via codepipeline reported a S3 access denied error

### ISSUE THREAD

**Issue by uxth** [aws/aws-cdk#14944]
Hello

I have created a pipeline via cdk scripts, which deploys a VPC, an EKS, and some other stuff.
Manually deploy all the stacks via cdk deploy, works fine.
Deploy the codepipeline, works.
codepipeline tries to deploy the application stage, which contains all the stacks above.
1st step, download code from github, works.
2nd step,  synth, works,
the application stage
1st step, deploy VPC, works
2nd step, deploy EKS, NOT WORKING, the error was happening when it tries to deploy the nested stack, the error is S3 access denied. no other messages.

### Reproduction Steps

use codepipeline to deploy a VPC and an EKS

### What did you expect to happen?

I am trying to deploy all the resources I need for my project by using codepipeline in AWS, CI/CD

### What actually happened?

the EKS could not be deployed by codepipeline, but it does not have any problem in deploying via cdk deploy command locally.

### Environment

  - **CDK CLI Version  :** 1.106.1 (build c832c1b)
  - **Framework Version:**
  - **Node.js Version:**  16
  - **OS               :** mac big sur
  - **Language (Version):**  python3.8

### Other

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hey @uxth,

thanks for opening the issue. Can you please show your code creating the Pipeline?

Thanks,
Adam

**Comment by uxth** [comment]
Hello @skinny85 ,

it is in my github repo, named cdkpipeline.

Thanks

**Comment by skinny85** [comment]
Great, can I see it? 🙂

**Comment by uxth** [comment]
definitely

**Comment by skinny85** [comment]
Can you send me the link to the code then please?

**Comment by uxth** [comment]
https://github.com/uxth/cdkpipeline

sorry, I thought you are able to see

**Comment by skinny85** [comment]
Did you perform the correct bootstrapping of the account you are deploying to, as described here? https://docs.aws.amazon.com/cdk/api/latest/docs/pipelines-readme.html#cdk-environment-bootstrapping

**Comment by uxth** [comment]
do you mean in the code or in my terminal?

**Comment by skinny85** [comment]
I see it's a Nested Stack. Maybe that's the problem? Perhaps Nested Stack support has some bug in CDK Pipelines?

I'm leaving this one for @rix0rrr and @otaviomacedo to diagnose, since it's a CDK Pipelines issue (and not just CodePipeline, which I initially thought).

**Comment by uxth** [comment]
any updates?

**Comment by uxth** [comment]
@skinny85 is there any other people who can answer this question?
I dont think @otaviomacedo @rix0rrr have the time here.

**Comment by rix0rrr** [comment]
Hi @uxth, @otaviomacedo is trying to get to the bottom of this as we speak. Our current suspicion is nested stacks, but the issue might be more complicated.

**Comment by otaviomacedo** [comment]
Hi, @uxth. The problem here is that your pipeline is [not self-mutating][1]. Because of that, the "Asset" stage of the pipeline get out of sync with the main stack template, which references a nested stack template that doesn't exist.

We are considering changing this flow to be less reliant on self mutation. But for now what you can do is change it to `self_mutating=True` (or remove `self_mutating` it altogether) and this will solve your problem.

[1]: https://github.com/uxth/cdkpipeline/blob/main/workflow_cdk/stacks/cdk_pipeline_stack.py#L116

**Comment by uxth** [comment]
hi @otaviomacedo , the reason I turned off the self-mutating option is because with it on the source code could not be downloaded from github.

**Comment by uxth** [comment]
it is working, thank you for pointing this out.
