### ISSUE TITLE
(aws-apigateway): Support DisableExecuteApiEndpoint parameter

### ISSUE THREAD

**Issue by NickIannelli** [aws/aws-cdk#14949]
(Almost the same as #12241)

Cloudformation AWS::ApiGateway::RestApi supports simple boolean [DisableExecuteApiEndpoint](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-restapi.html) parameter.

The DisableExecuteApiEndpoint parameter is missing from @aws-cdk/aws-apigateway [RestApi](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-apigateway.RestApi.html)

**Environment**
**CDK CLI Version:** 1.106.1
**Framework Version:** 1.106.1

--- 

This is :bug: Bug Report

**Comment by cokia** [comment]
I checked that this is normally in the document and code. Where did you decide it was missing?

**Comment by NickIannelli** [comment]
@cokia This was missing at the time for version v1.106.1, however does look to have been added since then.

Closing this issue as it appears to be resolved.
