### ISSUE TITLE
(cloudformation-diff): Addition of the bootstrap version Rule is not recognized and printed confusingly

### ISSUE THREAD

**Issue by l0b0** [aws/aws-cdk#14961]
### Reproduction Steps

Based on [How to upgrade CDK bootstrapping?](https://stackoverflow.com/q/67783136/96588):

1. Observe the following within a single CI pipeline:

   ```
   $ cdk bootstrap aws://unknown-account/ap-southeast-2
   '@aws-cdk/core:newStyleStackSynthesis' context set, using new-style bootstrapping
   […]
    ⏳  Bootstrapping environment aws://unknown-account/ap-southeast-2...
   Trusted accounts:   (none)
   Using default execution policy of 'arn:aws:iam::aws:policy/AdministratorAccess'. Pass '--cloudformation-execution-policies' to customize.
   […]
   ```

### What did you expect to happen?

There should be no warnings or error messages when running `cdk diff` after this.

### What actually happened?

```
$ cdk diff
[…]
Other Changes
[+] Unknown Rules: {"CheckBootstrapVersion":{"Assertions":[{"Assert":{"Fn::Not":[{"Fn::Contains":[["1","2","3"],{"Ref":"BootstrapVersion"}]}]},"AssertDescription":"CDK bootstrap stack version 4 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI."}]}}
```

Since the pipeline had already run `cdk bootstrap` with the very latest CDK version, the "Please run 'cdk bootstrap' with a recent version of the CDK CLI" message is surprising.

### Environment

  - **CDK CLI Version  :** 1.106.1 (build c832c1b)
  - **Framework Version:** aws-sdk@2.903.0
  - **Node.js Version:**  v14.17.0
  - **OS               :** Ubuntu 20.04.2
  - **Language (Version):** CPython (3.8.10)

### Other

I tried two workarounds suggested elsewhere, both neither of them helped:

- `cdk bootstrap --force`
- Deleting the existing bootstrapping and recreating it - see [job](https://github.com/linz/geostore/runs/2732047231?check_suite_focus=true#step:3:8)

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
Nothing is actually wrong. The `cdk diff` is telling you about a `Rule` that got added to the template, but it doesn't actually know what the `Rule` means and so is printing it in a confusing way.

The diff will disappear after your next deployment.
