### ISSUE TITLE
CloudFront Functions definition from file

### ISSUE THREAD

**Issue by cornelcroi** [aws/aws-cdk#14967]
CF2 definition from a file instead from inline code 

### Use Case

It allows to have a cleaner code instead of mixing everything in a single cdk file.
It is also easier to read.

### Proposed Solution

Could be something similair with what we have for Lambda:

```
const vreq_function = new cloudfront.Function(this, 'Function', {
      code: cloudfront.Function.Code.fromAsset('resources/my_function_code.js'),
 });
```

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by hoegertn** [comment]
Yes, that is already planned and I am working on it. I just wanted to get the feature out asap.

**Comment by njlynch** [comment]
Thanks for continuing this work, @hoegertn ! I'm assigning the issue to you for tracking purposes.

**Comment by covertbert** [comment]
Is there any plan to make an esbuild wrapper around these like we have with `NodejsFunction` for Lambdas?

**Comment by hoegertn** [comment]
As I pointed out in the PR I would love this, but esbuild does not (yet) support ES5 so bundles do not work in CFF currently.

Any ideas to solve this are welcome.

**Comment by covertbert** [comment]
Ahh I didn't realise that! Have you considered running the bundle through webpack (or maybe microbundle or parcel) after esbuild or just using one of those tools instead?

Reading through the esbuild docs it doesn't sound like they'll *ever* support ES5 and I think it would be quite a hindrance to the adoptability of CFF if they never support bundling either.

**Comment by hoegertn** [comment]
I am still hoping for an esbuild plugin for ES5. But I am completely open for any other ideas how to transpile this. I did not have the time to try webpack for this.

**Comment by covertbert** [comment]
Fair enough, makes sense! I will see if I can contribute to this in some way. Thanks for all your work on this anyway!
