### ISSUE TITLE
(aws-docdb): Missing option to enable minor version upgrade

### ISSUE THREAD

**Issue by h1008** [aws/aws-cdk#14964]
When creating a DocumentDB cluster using the DatabaseCluster construct, there is no way to set the option autoMinorVersionUpgrade for instances created by that cluster. The DatabaseInstance construct offers this option but since the DocumentDB cluster construct always creates at least one instance automatically, there is no way to enable this option for all instances.

### Use Case

For security reasons I would like to set the option autoMinorVersionUpgrade for all instances in my cluster.

### Proposed Solution

Add an additional optional field such as instanceAutoMinorVersionUpgrade to DatabaseClusterProps which is applied to all instances created by the DatabaseCluster construct:

```
const cluster = new DatabaseCluster(this, 'Database', {
    //...
   instanceAutoMinorVersionUpgrade: true
});
```

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by skinny85** [comment]
Thanks for opening the issue @h1008! We encourage community contributions, so if you'd like to open us a Pull Request adding this feature, that would be fantastic! Our "Contributing" guide: https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md.

Thanks,
Adam

**Comment by jumic** [comment]
Does this option exist for DocumentDB in general? I couldn't find it in the AWS console when creating a new DocumentDB cluster.

Attribute `autoMinorVersionUpgrade` has the following comment in the [CloudFormation documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-docdb-dbinstance.html#cfn-docdb-dbinstance-autominorversionupgrade): 
> This parameter does not apply to Amazon DocumentDB. Amazon DocumentDB does not perform minor version upgrades regardless of the value set.

So I think we shouldn't add this option at this point in time.

**Comment by h1008** [comment]
Yes, I think you're right! Sorry for the confusion - I assumed this option existed because [prowler](https://github.com/toniblyx/prowler) complained that it should be set. But apparently this was an issue with prowler...
