### ISSUE TITLE
(elb) set accessLoggingPolicy property with L2 LoadBalancer

### ISSUE THREAD

**Issue by ramancloudsmartz** [aws/aws-cdk#14972]
As the **elb** property readonly private , it has no visibilty outside. Also there is no method to access it. There is no provision to enable access log for LB

https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-elasticloadbalancing/lib/load-balancer.ts

**Comment by peterwoodworth** [comment]
Thanks for the feature request! If you want to do something like this immediately using the CDK you can set these same properties in your load balancer using ElbV2 ALB or NLB and using the [`logAccessLogs` method](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-elasticloadbalancingv2.NetworkLoadBalancer.html#logwbraccesswbrlogsbucket-prefix)

**Comment by ramancloudsmartz** [comment]
@peterwoodworth I need it with Elb LoadBalancer ( Classic Loadbalancer )

**Comment by ramancloudsmartz** [comment]
@peterwoodworth  Please review PR , I have added tests as well. Please let me know if required any change
Thanks

**Comment by ramancloudsmartz** [comment]
Please review **feat(elb): set accessLoggingPolicy property with L2 LoadBalancer** #14983
