### ISSUE TITLE
@aws-cdk/aws-s3-deployment: replacing all content of deployed folder results in missing files

### ISSUE THREAD

**Issue by jonlegendre** [aws/aws-cdk#14977]
Given a folder path to which I deployed a set of files, something like the following:  
bucket/folder/common/file1.py  
bucket/folder/common/file2.py  
bucket/folder/common/file3.py  
  
When I update my code, removing all 3 of those files, and putting a new one in, something like:  
bucket/folder/common/newfile.zip  
  
The initial deployment after that change results in the common folder going away.   
A few things of note (more detail in repro steps below):  
- My bucketDeployment has retainOnDelete set to false.
- The Logical ID of the entity of the bucketDeployment remained the same.
- If I make a subsequent change to the new file, the next deployment correctly deploys it.

### Reproduction Steps
I am using the following helper function in the two sets of repo steps below:  
```
import * as core from '@aws-cdk/core';
import * as s3 from '@aws-cdk/aws-s3';
import * as s3deploy from '@aws-cdk/aws-s3-deployment';

  public static provisionS3FilesToFolder = (stack: core.Stack, targetBucket: s3.IBucket, targetFolder: string, sourceFolder: string, sourceFiles: string[]) => {
    const excludes = ["**", ".**"]
    sourceFiles.forEach(function (file) {
      excludes.push(`!${file}`)
    });
    const files = new s3deploy.BucketDeployment(stack, `provision_s3_files_from_${sourceFolder}_to_${targetFolder}`, {
      destinationBucket: targetBucket,
      destinationKeyPrefix: targetFolder,
      sources: [s3deploy.Source.asset(sourceFolder, { exclude: excludes })],
      retainOnDelete: false
    });
    files.node.addDependency(targetBucket);
  }
```

On the initial deployment, deploy something like:
```
provisionS3FilesToFolder(this, myBucket, "folder/common/","./files/",["file1.py","file2.py","file3.py"])
```
On the next run deploy something like:
```
provisionS3FilesToFolder(this, myBucket, "folder/common/","./files/",["newfile.zip"])
```

### What did you expect to happen?
When I changed the files in the S3 folder, I expected the old files to be removed and the new files to be added.

### What actually happened?
When I changed the files in the S3 folder, the folder was removed, and the new file was not present.

### Environment

  - **CDK CLI Version  :**1.103.0
  - **Node.js Version:** v14.15.5
  - **OS               :Debian 10
  - **Language (Version):**  TypeScript (4.2.4)

### Other

My best guess is that there is an order of operations error between when we identify that the entire contents of the folder should be deleted, and the new file added to the folder (and or creating the folder).  
I know of course that S3 doesn't really have folders, so this was surprising to me, I suspect there is some sort of optimization where we are deleting everything under the keyprefix/folder instead of just the explicit files that are removed, when it detects that nothing will be left, and that delete is happening after we deploy the new file.  

--- 

This is :bug: Bug Report

**Comment by NGL321** [comment]
Hey @jonlegendre,

Thank you for reporting this bug! From quick evaluation the problem here is likely to stem from the retention policy of `BucketDeployment`. As you can see here:
https://github.com/aws/aws-cdk/blob/52c443474a97a6f8d5cac402e9cb7343f6af9db4/packages/%40aws-cdk/aws-s3-deployment/lib/bucket-deployment.ts#L232
It SHOULD be strictly converting over the supplied prop, however it does not seem to be. This could either be a bug in our code I am missing (maybe in `CustomResource`, or a translation error for the prop), OR it could be a bug in Cloudformation itself, so that makes it a little harder to evaluate.

Due to the limited impact of this I am going to prioritize as `p2`, however if more users encounter this problem we will escalate to `p1`.

😸 😷

**Comment by jonlegendre** [comment]
Apologies, I just realized that my logical ID is different, but destination is the same. Per this documentation that will cause a deletion:  
https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/aws-s3-deployment#retain-on-delete  
As such I will close this ticket.  
The described functionality seems flawed, but is clearly documented. 
Thank you!
