### ISSUE TITLE
(aws_iam): iam.ManagedPolicy.from_aws_managed_policy_name("AWSCodeDeployRole") fails lookup

### ISSUE THREAD

**Issue by robertofd1995** [aws/aws-cdk#14988]
I am trying to a Role the aws managed policy AWSCodeDeployRole.

After doing cdk deploy it fails and rollsback in cloudformation due to the following error:

Policy arn:aws:iam::aws:policy/AWSCodeDeployRole does not exist or is not attachable. (Service: AmazonIdentityManagement; Status Code: 404; Error Code: NoSuchEntity; Request ID: 0267d254-8bc5-40ea-81cd-5b857da0c322; Proxy: null)

I located the policy and for some reason the arn is the following:
arn:aws:iam::aws:policy/service-role/AWSCodeDeployRole 
instead of 
arn:aws:iam::aws:policy/AWSCodeDeployRole

I check and it looks that most of the AWS managed policies don't go into the subfolder service-role.

### Reproduction Steps

```
from aws_cdk import (
    core,
    aws_iam as iam
)

self.role_code_deploy = iam.Role(
            self, "CodeDeployRole",
            assumed_by=iam.ServicePrincipal("codedeploy.amazonaws.com")
)
self.role_code_deploy.add_managed_policy(iam.ManagedPolicy.from_aws_managed_policy_name("AWSCodeDeployRole"))

```

### What did you expect to happen?

Add AWSCodeDeployRole to the role 

### What actually happened?

It fails to lookup for the policy, and roollback the change

### Environment

  - **CDK CLI Version  : 1.102.0 (build a75d52f)
  - **Framework Version: 
  - **Node.js Version: v14.16.1
  - **OS : macos Mojave
  - **Language (Version): Python ( 3.9.0) 

### Other

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
Thanks
