### ISSUE TITLE
(aws-s3objectlambda): ObjectLambdaConfiguration is not produced in CloudFormation Template when using CDK for C#

### ISSUE THREAD

**Issue by OksanaH** [aws/aws-cdk#14995]
I'm unable to fully create `S3ObjectLambdaAccessPoint` resource using CDK for C#

I've been trying to create an S3ObjectLambda using CDK for C#. The code for creating a Lambda Access point is:

### Reproduction Steps

1) write this code: 

```csharp
var objectLambdaAccessPoint  = new CfnAccessPoint(this, "S3ObjectLambdaAccessPoint", new CfnAccessPointProps
{
    Name = "S3ObjectLambdaAccessPoint",
    ObjectLambdaConfiguration = new Dictionary<string,object>()
    {
        { "SupportingAccessPoint", "testpoint"},
        { "TransformationConfigurations", new object []{}}
    }
}
```

2) run `cdk synth`

### What did you expect to happen?
The template produced should include ObjectLambdaConfiguration property:

```json
    "S3ObjectLambdaAccessPoint": {
      "Type": "AWS::S3ObjectLambda::AccessPoint",
      "Properties": {
        "Name": "S3ObjectLambdaAccessPoint",
        "ObjectLambdaConfiguration": {
          "SupportingAccessPoint": "testpoint",
          "TransformationConfigurations": []
        }
      },
```

### What actually happened?
The section of the CloudFormation template produced is:

```json
    "S3ObjectLambdaAccessPoint": {
      "Type": "AWS::S3ObjectLambda::AccessPoint",
      "Properties": {
        "Name": "S3ObjectLambdaAccessPoint"
      },      
    },
```

### Environment

  - **CDK CLI Version  :*1.105.0*
  - **Framework Version:*1.98* (also tried 1.106)
  - **Node.js Version:*16.1.0* 
  - **OS               :*Windows 10*
  - **Language (Version):*C#* 

### Other
The Typescript code below outputs ObjectLambdaConfiguration to CloudFormation template correctly

```ts
    const objectLambdaAccessPoint = new s3object.CfnAccessPoint(this, 'S3ObjectLambdaAccessPoint', {
       name: ('S3ObjectLambdaAccessPoint'),
       objectLambdaConfiguration: {         
         supportingAccessPoint: "testpoint",
         transformationConfigurations: [],
       }
    });
```

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
Problem with the spec?

**Comment by skinny85** [comment]
Hey @OksanaH,

the property `objectLambdaConfiguration` is not a dictionary, but a well-typed object, of type `CfnAccessPoint.ObjectLambdaConfigurationProperty`:

```csharp
            var objectLambdaAccessPoint = new CfnAccessPoint(this, "S3ObjectLambdaAccessPoint", new CfnAccessPointProps
            {
                Name = "S3ObjectLambdaAccessPoint",
                ObjectLambdaConfiguration = new CfnAccessPoint.ObjectLambdaConfigurationProperty
                {
                    SupportingAccessPoint = "testpoint",
                    TransformationConfigurations = new object []{}
                }
            });
```

Hope this helps!

Thanks,
Adam

**Comment by OksanaH** [comment]
@skinny85 @rix0rrr Thanks, yes that works! And sorry for raising the bug!! Do you think it will be helpful to put an example in C# into the `aws-cdk-examples` repo? (unless it's going to be converted to L2 soon)?

**Comment by peterwoodworth** [comment]
Hey @OksanaH, I'm glad that the advice given has helped you!

If you'd like to contribute to the examples repo, make sure you read the [contributing document](https://github.com/aws-samples/aws-cdk-examples/blob/master/CONTRIBUTING.md#New) first. We don't require you to have the example in every language anymore (that part of the contributing guide is outdated), and we would love to have more C# examples! Make sure the example meets the criteria listed, and be sure to post an issue first if you aren't sure.

Closing the issue, but feel free to ping me if you have any additional questions 😄
