### ISSUE TITLE
(@aws-cdk/aws-cloudfront): Go Binding for CloudFront Function Synth Fails

### ISSUE THREAD

**Issue by trevorrobertsjr** [aws/aws-cdk#15007]
When attempting to run cdk synth for a CloudFront Function deployment with the CDK Go support, I get an error requesting comment and runtime properties that I do provide:
```
panic: "Resolution error: Supplied properties not correct for \"CfnFunctionProps\"\n  functionConfig: supplied properties not correct for \"FunctionConfigProperty\"\n    comment: required but missing\n    runtime: required but missing."
```

### Reproduction Steps

```
	awscloudfront.NewCfnFunction(stack, jsii.String("myCDKFunction"), &awscloudfront.CfnFunctionProps{
		Name:         jsii.String("myCfnFunctionCdk"),
		FunctionCode: jsii.String(myFunctionCode),
		AutoPublish:  jsii.Bool(true),
		FunctionConfig: &awscloudfront.CfnFunction_FunctionConfigProperty{
			Comment: jsii.String("testcdk"),
			Runtime: jsii.String("cloudfront-js-1.0"),
		},
	})
```

### What did you expect to happen?

I expect cdk.out to contain generated CloudFormation JSON similar to the following template:
```
{
    "Resources": {
      "myCDKFunction": {
        "Type": "AWS::CloudFront::Function",
        "Properties": {
          "Name": "whyfunccdk",
          "AutoPublish": true,
          "FunctionConfig": {
            "Comment" : "will this work",
            "Runtime" : "cloudfront-js-1.0"
          },
          "FunctionCode": "function handler(event) {\n\t\tvar request = event.request;\n\t\tvar uri = request.uri;\n\t\n\t\t// Check whether the URI is missing a file name.\n\t\tif (uri.endsWith('/')) {\n\t\t\trequest.uri += 'index.html';\n\t\t}\n\t\t// Check whether the URI is missing a file extension.\n\t\telse if (!uri.includes('.')) {\n\t\t\trequest.uri += '/index.html';\n\t\t}\n\t\treturn request;\n\t}"
        },
        "Metadata": {
          "aws:cdk:path": "HelloCdkGoStackCfnFunc/myCDKFunction"
        }
      }
    }
}
```

### What actually happened?

cdk synth fails to complete

### Environment

  - **CDK CLI Version  :** 1.107 and 2.0 rc6
  - **Framework Version:**
  - **Node.js Version:** v15.11.0 
  - **OS               :*Big Sur*
  - **Language (Version):**go1.16.3 

### Other

--- 

This is :bug: Bug Report

**Comment by hoegertn** [comment]
Can you try it out with the CloudFront Functions L2 construct? So we can see if it breaks in the L1 or somewhere else.

**Comment by trevorrobertsjr** [comment]
Thank you for the reply @hoegertn. I will try looking for the CloudFront Functions L2 support in the Go bindings and try again today.

**Comment by trevorrobertsjr** [comment]
Thank you for the suggestion. CDK 2.0.0 rc6 did not have L2 constructs for CloudFront Functions (at least, I could not find them). My code worked after I changed back to CDK 1.0.7 and used the L2 construct syntax (i.e. newFunction instead of NewCfnFunction). There were differences in the syntax between the L1 and L2 functions, and I adjusted accordingly for the deploy to succeed.

Any ideas why the code was not accepting the parameters that I was specifying? In Visual Studio Code, it did not indicate any errors with my original code.

**Comment by njlynch** [comment]
I think this might be a bug in jsii that's Go-specific. I filed an issue https://github.com/aws/jsii/issues/2880 to track it. Please track the resolution there.

In the meantime, CDK 2.0.0 rc7 has the Function L2, which does work:

```
awscloudfront.NewFunction(stack, jsii.String("myCDKFunction"), &awscloudfront.FunctionProps{
  Code: awscloudfront.FunctionCode_FromInline(jsii.String("hello world")),
})
```
