### ISSUE TITLE
(apigatewayv2): support for mock integration type

### ISSUE THREAD

**Issue by lyraddigital** [aws/aws-cdk#15008]
Currently in the @aws-cdk/aws-apigatewayv2 library only one WebSocketIntegrationType is supported. The AWS_PROXY integration type. The @aws-cdk/aws-apigatewayv2-integrations also only supports the LambdaWebSocketIntegration class to help connect a particular route to a Lambda function.

However when I create a Websocket API in the AWS console, there is support for HTTP, Mock, AWS Service and VPC Link.

I have created a simple Websocket API that does not require the client to communicate to the server. Only the server to communicate to the client. Therefore my $default route just has a simple MOCK integration, which works for my scenario.

Can we please add the other integrations type into this library? I am happy to assist if this is not already in progress. Just let me know.

### Use Case

The reason for this requirement is because I'm using API Gateway to create a web socket server that talks to both a Twitch Bot and a React.js application which is hosted on my local machine and runs inside of OBS. Basically this is a requirement for a Twitch  app I am creating. I could try another option (EC2 / ECS), AWS AppSync or event IOT, but in my research I believe using API Gateway and Lambda is the cheapest option.

### Proposed Solution

Not much to propose. Just make it work similar to how the UI works now.

### Other

* [x] :wave: I may be able to implement this feature request
* [x] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by austinatchley** [comment]
I'd like to take a stab at this one. This will be my first issue so I'm working through `CONTRIBUTING.md` and other docs first and hopefully I'll get to this in the next few days

The scope outlined in the title conflicts a bit with that of the description. I think I will proceed with only implementing the mock integration type for this issue, and we can open other issues for the other integration types as needed

Also curious as to why this was given the indicator for `This feature might incur a breaking change`. AFAIK no existing functionality will be affected
