### ISSUE TITLE
(cognito user pools): support for setting rules for user devices 

### ISSUE THREAD

**Issue by Aijaz12550** [aws/aws-cdk#15013]
enable cdk cognito module to manage actions for user devices and ip addresses in a pool.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-deviceconfiguration.html

### Use Case
we can set up rules for user device, either logging in from social account or cognito.

### Proposed Solution
Add functions to cdk for configuring user devices and IP addresses.

**Comment by nija-at** [comment]
Please provide the list of CloudFormation resource types or properties that need to be configured to enable this.

Additionally, please provide links to Cognito docs that describe this feature.

**Comment by Aijaz12550** [comment]
Thanks @nija-at for your response.

Below is the document url 

1. Cloudformation 
     https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-deviceconfiguration.html

2. Cognito docs
    https://aws.amazon.com/premiumsupport/knowledge-center/cognito-user-pool-remembered-devices/#:~:text=In%20the%20Amazon%20Cognito%20console,Always%20or%20User%20Opt%20In.

**Comment by ShengHow95** [comment]
Same here. Would like to have High Level Construct for User Pools to have the Device Configuration
