### ISSUE TITLE
(opensearch): domain doesn't handle tokens in capacity configuration

### ISSUE THREAD

**Issue by leantorres73** [aws/aws-cdk#15014]
If I set SSM for some parameters like `dataNodeInstanceType`,  if fails on deployment time

### Reproduction Steps

Create a ES Domain, and set capacity using SSM, like this:

``` 
capacity: {
      dataNodeInstanceType: `${ssm.StringParameter.valueForStringParameter(stack, 'ESInstanceTypeSSM', `elasticsearch/instance-type`)}.elasticsearch`,
      masterNodeInstanceType: `${ssm.StringParameter.valueForStringParameter(stack, 'ESInstanceTypeSSM', `elasticsearch/instance-type`)}.elasticsearch`,
      masterNodes: '1', 
      dataNodes: 2
}, 
```

Also, it shouldn't check if '.elasticsearch' is part of the text if a token is set there, but this second one is minor bug, the other one is an impediment of using SSM with ES configurations

### What did you expect to happen?

Token resolved correctly.

### What actually happened?

It fails, internally it's doing a .toLowerCase() and it's breaking the token 

`"${token[token.718]}.elasticsearch"` instead of `"${Token[Token.718]}.elasticsearch"`

### Environment

  - **CDK CLI Version: 1.106.0
  - **Node.js Version: 12
  - **OS               : Linux
  - **Language (Version): Javascript

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
We need to add a `Token.isUnresolved()` check [here](https://github.com/aws/aws-cdk/blob/af6d49f2e245b60ae3bbea3bb2c5d283beedba3f/packages/%40aws-cdk/aws-elasticsearch/lib/domain.ts#L1281-L1283) (and probably a few similar places in that class as well).

**Comment by BenChaimberg** [comment]
smaller reproducible example without SSM:
```
new Domain(stack, 'Domain', {
  version: ElasticsearchVersion.V6_5,
  capacity: {
    dataNodeInstanceType: `${Fn.ref('SomeLogicalId')}.elasticsearch`,
  },
});
```
