### ISSUE TITLE
(aws-stepfunctions-tasks): CallApiGatewayRestApiEndpoint doesn't support json path for path field.

### ISSUE THREAD

**Issue by thantos** [aws/aws-cdk#15022]
Sometimes API Gateway paths need to use variables from the state machine state, but this task will fail when computing the arn from Api Gateway. 

### Reproduction Steps

```ts
new CallApiGatewayRestApiEndpoint(this, "myApiCall", {
    api: someApi,
    method: HttpMethod.POST,
    stageName: "prod",
    apiPath: JsonPath.stringAt('$.something'),
    ...
  }
);
```

### What did you expect to happen?

Path should be a computed path, resource arn should reflect a wildcard for the path. 

### What actually happened?

```
"path" must begin with a "/"
```

https://github.com/aws/aws-cdk/blob/52c443474a97a6f8d5cac402e9cb7343f6af9db4/packages/%40aws-cdk/aws-apigateway/lib/restapi.ts#L356

### Environment

  - **CDK CLI Version  :** 1.102.0
  - **Framework Version:** 1.102.0
  - **Node.js Version:**  12
  - **OS               :** WSL 2 - Ubuntu
  - **Language (Version):**  TS 4

### Other

Workaround for anyone blocked by this...

```ts
export interface CallApiGatewayRestApiEndpointV2Props extends CallApiGatewayRestApiEndpointProps {
  realPath: string;
}

export class CallApiGatewayRestApiEndpointV2 extends CallApiGatewayRestApiEndpoint {
  constructor(scope: Construct, id: string, private _props: CallApiGatewayRestApiEndpointV2Props) {
    super(scope, id, _props);
  }

  _renderTask(): {
    Resource: string;
    Parameters:
      | {
          [key: string]: any;
        }
      | undefined;
  } {
    const rendered = super._renderTask();

    return {
      ...rendered,
      Parameters: FieldUtils.renderObject({
        ...rendered.Parameters,
        Path: this._props.realPath,
      }),
    };
  }
}
```
--- 

This is :bug: Bug Report

**Comment by BenChaimberg** [comment]
[RestApiBase's `arnForExecuteApi`](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-apigateway/lib/restapi.ts#L364) needs to check if its arguments are unresolved Tokens and, if so, use wildcards instead.

Workaround is to subclass whatever REST API is being passed to CallApiGatewayRestApiEndpoint to override  `arnForExecuteApi` and modify the validation:
```
someRestApi['arnForExecuteApi'] = (method: string = '*', path: string = '/*', stage: string = '*') => {
  if (Token.isUnresolved(path)) {
    path = '/*';
  } else if (!path.startsWith('/')) {
    throw new Error(`"path" must begin with a "/": '${path}'`);
  }
  if (method.toUpperCase() === 'ANY') {
    method = '*';
  }
  return Stack.of(someRestApi).formatArn({
    service: 'execute-api',
    resource: someRestApi.restApiId,
    sep: '/',
    resourceName: `${stage}/${method}${path}`,
  });
}
```

**Comment by wimlewis-amazon** [comment]
Another workaround is to use a `CustomState` containing the [ASL definition](https://docs.aws.amazon.com/step-functions/latest/dg/amazon-states-language-task-state.html) (with, e.g., `'Path.$': '$.url_path'`) and to manually add permission to invoke the API to the state machine role. For me this was marginally easier.
