### ISSUE TITLE
(aws-cdk/aws-amplify): basicAuth cannot be removed

### ISSUE THREAD

**Issue by mwiarda-fette** [aws/aws-cdk#15028]
Hi, 

basicAuth can be enabled on an amplify application using the cdk.
Unfortunately, that setting can not be reversed. The cloudformation template changes but basic auth is still active in amplify.

### Reproduction Steps
1)  Create new amplify app with basic auth:

```ts
import * as codebuild from '@aws-cdk/aws-codebuild';
import * as amplify from '@aws-cdk/aws-amplify';
import * as cdk from '@aws-cdk/core';

const amplifyApp = new amplify.App(this, 'MyApp', {
  basicAuth: amplify.BasicAuth.fromCredentials("admin", this.secret.secretValueFromJson("password")),
  sourceCodeProvider: new amplify.GitHubSourceCodeProvider({
    owner: '<user>',
    repository: '<repo>',
    oauthToken: cdk.SecretValue.secretsManager('my-github-token')
  }),
  buildSpec: codebuild.BuildSpec.fromObjectToYaml({ // Alternatively add a `amplify.yml` to the repo
    version: '1.0',
    frontend: {
      phases: {
        preBuild: {
          commands: [
            'yarn'
          ]
        },
        build: {
          commands: [
            'yarn build'
          ]
        }
      },
      artifacts: {
        baseDirectory: 'public',
        files: '**/*'
      }
    }
  })
});
```
2) Website should now be password protected
3) Remove line basicAuth: amplify.BasicAuth.fromCredentials("admin", this.secret.secretValueFromJson("password"))
4) **App is still password protected**

### What did you expect to happen?

Password protection should be removed

### What actually happened?

Template changes (shows in cdk diff) but protection not removed in amplify

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hi @mwiarda-fette,

thanks for opening the issue. Do you perhaps have Premium Support? I think this might be worth it to open to the Amplify team directly - looks like their CloudFormation support does not handle edits correctly. Unfortunately, there's not much we can do here from the CDK side.

Thanks,
Adam

**Comment by jogold** [comment]
There's maybe something to do with https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-amplify-app-basicauthconfig.html#cfn-amplify-app-basicauthconfig-enablebasicauth?

**Comment by mwiarda-fette** [comment]
Hi Adam, thanks for the feedback.
Unfortunately, we only have basic support. 
I will try to create a case anyway. Maybe they are interested in this.

Best,
Michael
