### ISSUE TITLE
AWS::IAM::Role of an instance cannot be automatically deleted

### ISSUE THREAD

**Issue by Flauschbaellchen** [aws/aws-cdk#15024]
If deleting an Auto-Scaling-Group or a LinuxBastionHost, the linked IAM instance role cannot be deleted as an attached AmazonSSMManagedInstanceCore policy blocks the deletion.

### Reproduction Steps

Create a minimal LinuxBastionHost or an Auto-Scaling-Group, e.g.
```
new ec2.BastionHostLinux(this, 'BastionHost', { vpc });
```

### What did you expect to happen?

On stack deletion all components should be deleted cleanly.

### What actually happened?

The stack cannot be deleted as the AWS::IAM::Role of the corresponding instance cannot be deleted.
Error:
```
Cannot delete entity, must detach all policies first. (Service: AmazonIdentityManagement; Status Code: 409; Error Code: DeleteConflict; Request ID: 9380ca3e-cc4c-4c94-bfd2-b11f44e8ee96; Proxy: null)
```
The role in question has only `AmazonSSMManagedInstanceCore` attached.
Removing the policy allows the stack to be deleted cleanly.

### Environment

  - **CDK CLI Version: *1.105.0*
  - **Framework Version: *1.105.0*
  - **Node.js Version: *v14.16.0*
  - **OS: *Ubuntu 16.04*
  - **Language (Version): *TypeScript 3.9.9*

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
Did `AmazonSSMManagedInstanceCore` get attached by some other mechanism after creating the Role using CloudFormation?

By hand using the console, by using some script, by using the CLI, ... ?

**Comment by Flauschbaellchen** [comment]
Hi @rix0rrr,

sorry for the report. It seems that the organisation set up some lamda function/hooks within the account to inject those policies automatically.
Since this was just about the time I updated the CDK, I figured this would be a bug. :see_no_evil:

Thanks anyway for pointing me in the right direction.
