### ISSUE TITLE
(log-retention): Using Node 12.x lambda when a new LTS is available

### ISSUE THREAD

**Issue by mitchlloyd** [aws/aws-cdk#15038]
## :question: General Issue

As I'm upgrading CDK in many projects to remove EOL Node 10.x lambdas, I'm seeing an upgrade go from 10.x -> 12.x instead of the expected 14.x (current LTS). This means that I'm going to need to revisit this upgrading process sooner than if this were set to 14.x.

This construct is specifying `'nodejs12.x'` https://github.com/aws/aws-cdk/blob/b1ecd3d49d7ebf97a54a80d06779ef0f0b113c16/packages/%40aws-cdk/aws-logs/lib/log-retention.ts#L161.

I believe this should be upgraded to the latest LTS. I wonder if this was overlooked because it uses `CfnLambda` and a string literal for the `Runtime` property. 

### Environment

  - **CDK CLI Version:** 1.107.0
  - **Module Version:** 1.107.0
  - **Node.js Version:** v14.17.0
  - **OS:** all
  - **Language (Version):** all

**Comment by peterwoodworth** [comment]
Thanks for this submission @mitchlloyd, would you like to go ahead and implement this fix?

**Comment by mitchlloyd** [comment]
@peterwoodworth I'd be happy to create a PR. 

Is there a reason we want to avoid a dependency on the `aws-lambda` package for the log-retention and customer-resource-provider modules? I imagine in the pre-monocdk/v2 era it made sense to avoid pulling in sibling service packages when possible. Going forward do we still want these packages to remain independent from `aws-lambda`? If not, it may makes sense to convert these resources to `lambda.Function`s.

**Comment by peterwoodworth** [comment]
If we have a dependency on `aws-lambda` in `aws-logs` it will create a circular dependency, so hardcoding it in this case is a good call 😄
