### ISSUE TITLE
(aws-cdk): add "diode" to service principal exceptions

### ISSUE THREAD

**Issue by bluesun33** [aws/aws-cdk#15035]
Add "diode" to service principal exceptions.

### Use Case

Per Amazon internal docs, diode uses the Service Principals "diode.sc2s.sgov.gov" and "diode.c2s.ic.gov" for Secret and Top Secret regions, but the current code always returns "diode.amazonaws.com" when we specify the above SPs. 

### Proposed Solution

Proposing to add exceptions for diode to allow for the partitional principal [here](https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/region-info/lib/default.ts#L23-L99).

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by cervantn** [comment]
Hello bluesun33,

I believe whatever AWS Diode documentation you're referring to is out of date. Please use the `diode.amazonaws.com` Service Principal instead in the Secret and Top Secret regions.
