### ISSUE TITLE
(aws-appsync): Bad error message - Missing default OIDC Configuration

### ISSUE THREAD

**Issue by Matt-Butler** [aws/aws-cdk#15039]
https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-appsync/lib/graphqlapi.ts#L498

if (mode.authorizationType === AuthorizationType.USER_POOL &amp;&amp; !mode.userPoolConfig) { 
  throw new Error('Missing default OIDC Configuration');      
}

----

 throw new Error('Missing userPoolConfig');

**Comment by peterwoodworth** [comment]
Hey @Matt-Butler, can you more clearly state what the problem here is? Thanks.

**Comment by Matt-Butler** [comment]
In this case, the user isn't missing the OIDC configuration. The user is missing userPoolConfig. 

Expected:
```
Missing userPoolConfig
```

Actual:
```
Missing default OIDC Configuration
```

**Comment by peterwoodworth** [comment]
Thank you for clarifying, is this something that you'd like to fix yourself? I'd be happy to take a look at the PR you make
