### ISSUE TITLE
(aws-logs): FilterPattern.stringValue creates invalid metric filter pattern

### ISSUE THREAD

**Issue by danielwoerner** [aws/aws-cdk#15047]
Creating a filter pattern for a metric filter via the `FilterPattern.stringValue()` method, results in an `InvalidParameterException` when deploying via `cdk deploy`.
`cdk diff` does NOT fail and correctly shows the MetricFilter.

### Reproduction Steps

```ts
const stack = new cdk.Stack(app, "test-stack")
const apiLoggroup = logs.LogGroup.fromLogGroupArn(stack, "api-loggroup", "ARN HERE")
const api401MetricFilter = new logs.MetricFilter(stack, "HTTP401", {
    logGroup: apiLoggroup,
    metricNamespace: "AWS/ApiGateway",
    metricName: "401",
    filterPattern: logs.FilterPattern.stringValue("status", "=", "401"),
    metricValue: "1",
    defaultValue: 0
});
```
deploy via `cdk deploy`

### What did you expect to happen?

I want to create a metric filter for having API Gateway HTTP Errors as CloudWatch Alarms (specifically 400, 401, 404).
To do this, I get my the loggroup, which the API Gateway writes its logs to, and then create a `MetricFilter` to filter these logs.

Obviously after that, still need to setup the alarm and do other stuff (e.g. SNS Topic as action), but thats not where the error occurs so I left if out.

### What actually happened?

3/8 | 12:42:10 | CREATE_FAILED        | AWS::Logs::MetricFilter    | DrkleinrkCloudwatchStack/HTTP401 (HTTP4010B8C6331) Invalid metric filter pattern (Service: AWSLogs; Status Code: 400; Error Code: InvalidParameterException; Request ID: 547040da-1428-4c23-bdf7-4ae
6d0b07728; Proxy: null)

A look into the stack-template (Cloudformation) shows the following:

```json
"HTTP4010B8C6331": {
    "Type": "AWS::Logs::MetricFilter",
    "Properties": {
        "FilterPattern": "{ status = \"401\" }",
        "LogGroupName": "xxx",
        "MetricTransformations": [
            {
                "DefaultValue": 0,
                "MetricName": "HTTP401",
                "MetricNamespace": "AWS/ApiGateway",
                "MetricValue": "1"
            }
        ]
    },
    "Metadata": {
        "aws:cdk:path": "test-stack/HTTP401/Resource"
      }
},
```
For safety-reasons I anonymized loggroup-name.

### Environment

  - **CDK CLI Version  : 1.107.0**
  - **Node.js Version: v14.15.4** 
  - **OS               : Windows 10**
  - **Language (Version): TypeScript (4.3.2)** 

### Other

**Stack-Trace**
new MetricFilter (..\cdk\node_modules\@aws-cdk\aws-logs\lib\metric-filter.ts:39:5)
        \_ Function.createMetricFilter (..\cdk\lib\cloudwatch\cloudwatch-helper.ts:91:12)
        \_ test-stack.initStack (..\cdk\lib\drkleinrk-cloudwatch-stack.ts:62:49)
        \_ new TestStack (..\cdk\lib\drkleinrk-cloudwatch-stack.ts:16:10)
        \_ Object.<anonymous> (..\cdk\bin\cdk.ts:33:1)
        \_ Module._compile (internal/modules/cjs/loader.js:1063:30)
        \_ Module.m._compile (..\cdk\node_modules\ts-node\src\index.ts:1295:23)
        \_ Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
        \_ Object.require.extensions.<computed> [as .ts] (..\cdk\node_modules\ts-node\src\index.ts:1298:12)
        \_ Module.load (internal/modules/cjs/loader.js:928:32)
        \_ Function.Module._load (internal/modules/cjs/loader.js:769:14)
        \_ Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
        \_ main (..\cdk\node_modules\ts-node\src\bin.ts:246:14)
        \_ Object.<anonymous> (..\cdk\node_modules\ts-node\src\bin.ts:382:3)
        \_ Module._compile (internal/modules/cjs/loader.js:1063:30)
        \_ Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
        \_ Module.load (internal/modules/cjs/loader.js:928:32)
        \_ Function.Module._load (internal/modules/cjs/loader.js:769:14)
        \_ Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
        \_ internal/main/run_main_module.js:17:47

Paths up to CDK folder are anonymized.

I found a [Stackoverflow Question](https://stackoverflow.com/questions/54261797/how-do-i-define-an-aws-metricfilter-filterpattern-to-match-a-json-formatted-log) which makes me think, the filter pattern needs to include parenthesis, but I have no proof.

--- 

This is :bug: Bug Report

**Comment by danielwoerner** [comment]
after some troubleshooting, i think I know where the issue is:

the FilterPattern should look like this:
`{ ($.status = \"400\") }`
or
`{ $.status = \"400\" }`

In the template which was generated by my code `$.` is missing.
I'll try again with using 

```ts
filterPattern: logs.FilterPattern.stringValue("$.status", "=", "401"),
```

as the filter pattern. Should this work, this bug report can be closed, although the question remains, if this way of accessing the JSON fields is user friendly or not (especially if it's not documented properly as currently)

**Comment by danielwoerner** [comment]
What I stated in my previous comment made it work.
So I guess this bug report is invalid and can be closed.

**Comment by rix0rrr** [comment]
The pattern is documented here: https://docs.aws.amazon.com/cdk/api/latest/docs/aws-logs-readme.html#text-patterns
