### ISSUE TITLE
(aws-msk): Missing L2 Cluster construct in 2.0 RC

### ISSUE THREAD

**Issue by blaenk** [aws/aws-cdk#15040]
I'm not sure if this is a bug or not, I'm not sure what the strategy is with version 2 RCs, maybe you're not merging in new features since the 2.0 RC came out?

Specifically, it seems that PR #9908 which added the MSK L2 construct for a Cluster and was released as part of [1.103.0](https://github.com/aws/aws-cdk/blob/master/CHANGELOG.md#11030-2021-05-10) never got into the RC line, but maybe this is to be expected and many other changes aren't making it into 2 RC?

### Reproduction Steps

``` console
$ curl -OJLR $(npm view aws-cdk-lib@2.0.0-rc.6 dist.tarball)
$ tar xvf aws-cdk-lib-2.0.0-rc.6.tgz
$ find package -path '*aws-msk*' -name '*cluster*'

# I think this is where it should be based on
# https://github.com/aws/aws-cdk/blob/v2.0.0-rc.6/packages/%40aws-cdk/aws-msk/lib/cluster.ts

$ stat package/lib/aws-msk/lib/cluster.js
```

### What did you expect to happen?

I expected the L2 MSK Cluster construct to exist in the 2 RC line.

### What actually happened?

It's not there.

### Environment

Any.

### Other

--- 

This is :bug: Bug Report

**Comment by otaviomacedo** [comment]
Hi, @blaenk 

This is expected. Version 2 of the CDK is still in developer preview. During this phase, it won't be possible to use experimental modules. So you basically have two options: use v1 or wait until v2 is released to general availability later this year.
