### ISSUE TITLE
(pipelines): redundant default installCommand 

### ISSUE THREAD

**Issue by jefftham** [aws/aws-cdk#15056]
https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/pipelines/lib/synths/simple-synth-action.ts#L210

as document stated, developer pass either `installCommands` or `installCommand`.
However, `installCommand` is default it anyhow.

### Reproduction Steps

 synthAction: SimpleSynthAction.standardNpmSynth({
        sourceArtifact,
        cloudAssemblyArtifact,
        environment: {
          buildImage: codebuild.LinuxBuildImage.STANDARD_5_0,
        },
        installCommands: ['node --version'],
      })

### What did you expect to happen?

Expect to pass installCommands to SimpleSynthAction.standardNpmSynth

### What actually happened?

Error: Pass either 'installCommand' or 'installCommands', but not both

### Environment

  - **CDK CLI Version  : 1.108.0**
  - **Framework Version: 1.108.0**
  - **Node.js Version: v14.16.0** 
  - **OS               : Mac OS**
  - **Language (Version): NodeJs ** 

### Other

--- 

This is :bug: Bug Report

**Comment by hoegertn** [comment]
@rix0rrr should we just clean this up and use the new args only? I added testCommands so I could cleanup the rest. But it would be a breaking change.

**Comment by rix0rrr** [comment]
I am loath to break backwards compatibility, so preferably no.
