### ISSUE TITLE
(@aws-cdk/aws-sqs): Support configuring high throughput for FIFO queues

### ISSUE THREAD

**Issue by westonsteimel** [aws/aws-cdk#15063]
[High throughput mode](https://docs.amazonaws.cn/en_us/AWSSimpleQueueService/latest/SQSDeveloperGuide/high-throughput-fifo.html) on FIFO SQS queues is now generally available, and it would be convenient to be able to configure it via the CDK 

### Proposed Solution

Allow setting the following queue attributes:

deduplication_scope: 
- MESSAGE_GROUP
- QUEUE

Default: QUEUE

fifo_throughput_limit:
- PER_QUEUE
- PER_MESSAGE_GROUP_ID

Default: PER_QUEUE
 
An example of the options from boto3:
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sqs.html#SQS.Client.set_queue_attributes

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by druska** [comment]
As far as I can tell, these properties aren't even available in CloudFormation yet.
https://docs.amazonaws.cn/en_us/AWSCloudFormation/latest/UserGuide/aws-properties-sqs-queues.html

**Comment by njlynch** [comment]
Thanks for the feature request!

As @druska points out (thanks!), it looks like this feature isn't available via CloudFormation yet. Once support is added there, we can introduce the support to the `Queue` construct.

**Comment by paul-doherty** [comment]
The attributes look to be available in CFN now https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sqs-queues.html#aws-sqs-queue-deduplicationscope
