### ISSUE TITLE
(@aws-cdk/aws-lambda): lambda asset created with Code.fromDockerBuild output empty .zip

### ISSUE THREAD

**Issue by vkml** [aws/aws-cdk#15062]
Trying to deploy EdgeFunction:
```typescript
const viewerRequest = new cloudfront.experimental.EdgeFunction(this, 'viewer-request', {
      memorySize: 128,
      timeout: cdk.Duration.seconds(5),
      runtime: lambda.Runtime.NODEJS_14_X,
      handler: "lambda.handler",
      functionName: "edge-viewer-request",
      code: lambda.Code.fromDockerBuild(pathToLambdas, {
        file: 'viewer-request.Dockerfile',
      }),
    });
```
leads to a deployment error: `Uploaded file must be a non-empty zip (Serv
ice: Lambda, Status Code: 400, Request ID: 1745237f-146a-45e4-a67b-f918e8a4e5f9
, Extended Request ID: null)`.

### Reproduction Steps

Running `cdk deploy` with code snippet above

### What did you expect to happen?

Lambda@edge successfully deployed

### What actually happened?

Zip file with assets is pushed to S3 cdk-toolkit bucket, but it's an empty archive

### Environment

  - **CDK CLI Version  :** 1.108.0
  - **Framework Version:** 1.108.0
  - **Node.js Version:** 14.15.1
  - **OS               :** Ubuntu 19.04
  - **Language (Version):** TypeScript (3.9.7)

### Other

Running the command inside the image container shows that all the code is in place
```
****@****:~/.../deploy/lambdas$ docker run --rm 7a1f21459c63 ls /asset
lambda.js
node_modules
```

but the cdk-toolkit bucket asset is an empty archive

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
Hi @vkml -

To reproduce and further debug this issue, you will need to provide the contents of the folder `pathToLambdas`.

**Comment by peterwoodworth** [comment]
Hey @vkml, can you please provide what niranjan asked for?
