### ISSUE TITLE
elasticloadbalancingv2: Fargate Target Groups use first port for all target groups

### ISSUE THREAD

**Issue by levischuckeats** [aws/aws-cdk#15077]
While trying to follow the documentation for "Exposing multiple ports from the same container"
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/register-multiple-targetgroups.html

I specified the
1. A container definition with two port mappings 8080, 50051 (grpc)
2. A single FargateService with that container definition, no other containers
3. created a target group for HTTP with the instance port being 8080
4. created a target group for gRPC with the instance port being 50051
5. With a shared ALB, added a rule to the HTTPS 443 listener to forward to the HTTP target group
6. With a shared ALB, added a rule to the gRPC listener to forward to the gRPC target group

The failure here is that the **second** target group (gRPC) used the same port to the container as the **first** target group despite it being specified as 8080 and 50051 respectively.

When I switched the order the target group, container mappings, and rules were added so that gRPC came first, the same thing happened to the HTTP target group as viewed in the console.

<img width="584" alt="Screen Shot 2021-06-10 at 3 59 15 PM" src="https://user-images.githubusercontent.com/28264383/121597836-c6de3d00-ca06-11eb-858c-207306289442.png">

### Reproduction Steps

You'd need
* a container image that exposes both http and grpc for this, http has a /health endpoint that returns 200
* a VPC
* subnets
* An ALB
* Two ALB Listeners with different ports on the same alb

Code supplied includes `val` from lombok, best effort on something small and self contained

```java

IVpc primaryVpc = Vpc.fromLookup(this, "vpc", VpcLookupOptions.builder()
                .vpcId("vpc-abcd1234")
                .build());
Cluster cluster = Cluster.Builder.create(this, "fargate")
                .vpc(primaryVpc)
                .build();

ISubnet subnet1b = Subnet.fromSubnetId(this, "subnet1b", "id-here");
ISubnet subnet1c = Subnet.fromSubnetId(this, "subnet1b", "id-here");
ISubnet subnet1e = Subnet.fromSubnetId(this, "subnet1b", "id-here");
val albsg = SecurityGroup.fromSecurityGroupId(this,"albsgref", "alb security group id here")
val vpcSubnets = SubnetSelection.builder()
                .subnets(Arrays.asList(subnet1b, subnet1c, subnet1e))
                .build();

val taskRole = new Role(this, "taskRole", RoleProps.builder()
                .assumedBy(new ServicePrincipal("ecs-tasks.amazonaws.com"))
                .build());

val executionRole = new Role(this, "executionRole", RoleProps.builder()
                .assumedBy(new ServicePrincipal("ecs-tasks.amazonaws.com"))
                .build());
executionRole.addManagedPolicy(ManagedPolicy.fromAwsManagedPolicyName("service-role/AmazonECSTaskExecutionRolePolicy"));

val sg = new SecurityGroup(this, "sg", SecurityGroupProps.builder()
                .vpc(primaryVpc)
                .allowAllOutbound(true)
                .build());

val grpcTask = new FargateTaskDefinition(this, "grpcDef", FargateTaskDefinitionProps.builder()
                .memoryLimitMiB(2048)
                .executionRole(execution)
                .taskRole(task)
                .cpu(1024)
                .build());
val grpcContainer = new ContainerDefinition(this,
        "grpcContainer",
        ContainerDefinitionProps
                .builder()
                .image(ContainerImage.fromRegistry("container image here"))
                .taskDefinition(grpcTask)
                .essential(true)
                .build());

grpcContainer.addPortMappings(portMapping(50051, 50051));
grpcContainer.addPortMappings(portMapping(8080, 8080));

grpcTask.setDefaultContainer(grpcContainer);

val grpcService = new FargateService(this, "svc", FargateServiceProps.builder()
        .taskDefinition(grpcTask)
        .cluster(cluster)
        .securityGroups(Collections.singletonList(sg))
        .vpcSubnets(vpcSubnets)
        .desiredCount(1)
        .minHealthyPercent(100)
        .maxHealthyPercent(200)
        .deploymentController(DeploymentController.builder()
           .type(DeploymentControllerType.ECS)
           .build())
        .build());


val grpcTgGrpc = new ApplicationTargetGroup(this, id, ApplicationTargetGroupProps.builder()
                .port(50051)
                .protocol(ApplicationProtocol.HTTP)
                .protocolVersion(ApplicationProtocolVersion.GRPC)
                .vpc(primaryVpc)
                .targets(Collections.singletonList(grpcService))
                .healthCheck(HealthCheck.builder()
                    .enabled(true)
                    .healthyGrpcCodes("0,12") // 0 OK, 12 unimplemented
                    .interval(Duration.minutes(1))
                    .unhealthyThresholdCount(5)
                    .build())
                .deregistrationDelay(Duration.seconds(30))
                .build());

val grpcListener = ApplicationListener.fromApplicationListenerAttributes(this,"grpcListener", ApplicationListenerAttributes.builder()
                .listenerArn("grpc listener arn here")
                .securityGroup(albsg)
                .build());

val httpListener = ApplicationListener.fromApplicationListenerAttributes(this, "listener", ApplicationListenerAttributes.builder()
                .listenerArn("http listener arn here")
                .securityGroup(albsg)
                .build());

albRule("grpcRule", grpcListener, grpcTgGrpc, props.getDnsName(), props.getAlbPriority());
new ApplicationListenerRule(this, "albgrpcrule", ApplicationListenerRuleProps.builder()
                .listener(grpcListener)
                .conditions(Collections.singletonList(ListenerCondition.hostHeaders(Collections.singletonList("dns-name-here.com"))))
                .action(ListenerAction.forward(Collections.singletonList(grpcTgGrpc)))
                .priority(10)
                .build());

val grpcTgHttp = new ApplicationTargetGroup(this, id, ApplicationTargetGroupProps.builder()
                .port(8080)
                .protocol(ApplicationProtocol.HTTP)
                .vpc(primaryVpc)
                .targets(Collections.singletonList(grpcService))
                .healthCheck(HealthCheck.builder()
                    .enabled(true)
                    .healthyHttpCodes("200")
                    .path("/health")
                    .interval(Duration.minutes(1))
                    .unhealthyThresholdCount(5)
                    .build())
                .deregistrationDelay(Duration.seconds(30))
                .build());

new ApplicationListenerRule(this, id, ApplicationListenerRuleProps.builder()
                .listener(httpListener)
                .conditions(Collections.singletonList(ListenerCondition.hostHeaders(Collections.singletonList("dns-name-here.com"))))
                .action(ListenerAction.forward(Collections.singletonList(grpcTgHttp)))
                .priority(1001)
                .build());

```

### What did you expect to happen?

I expect that the second target group uses the port it was instructed to use

![image](https://user-images.githubusercontent.com/28264383/121600385-00647780-ca0a-11eb-89b5-b2e31a32b7bb.png)

### What actually happened?

The second target group uses the same port as another target group

<img width="584" alt="Screen Shot 2021-06-10 at 3 59 15 PM" src="https://user-images.githubusercontent.com/28264383/121597836-c6de3d00-ca06-11eb-858c-207306289442.png">

### Environment

  - **CDK CLI Version  :** 1.103.0 (build bc13a66)
  - **Framework Version:** 2.16.43
  - **Node.js Version:** v14.4.0
  - **OS               :** MacOS 11.3.1
  - **Language (Version):** Java 8

### Other

N/A

--- 

This is :bug: Bug Report

**Comment by njlynch** [comment]
Apologies for the delay in first response.

This isn't a bug, but it is a subtle bit of behavior. If you have a container with multiple ports, adding the service to an `ApplicationTargetGroup` via `.targets(Collections.singletonList(grpcService))` isn't sufficient. Instead, you need to use the [`grpcService.loadBalancerTarget()`](https://docs.aws.amazon.com/cdk/api/latest/java/software/amazon/awscdk/services/ecs/BaseService.html#loadBalancerTarget-software.amazon.awscdk.services.ecs.LoadBalancerTargetOptions-) method to specify the container name and port to use.

This is documented in the ECS docs readme under the "Include an application/network load balancer" section heading: https://docs.aws.amazon.com/cdk/api/latest/java/index.html?software/amazon/awscdk/services/ecs/package-summary.html

Hope that helps! Feel free to mention me to re-open this if you have any follow-ups.
