### ISSUE TITLE
(module name): short issue description

### ISSUE THREAD

**Issue by dayyehm** [aws/aws-cdk#15076]
The documentation is missing the following regarding importing existing firehose stream to CFN stacks : 
https://docs.aws.amazon.com/cdk/api/latest/docs/aws-kinesisfirehose-readme.html
This is for Firehose 

We don't see a construct : "fromSteamArn" method on kinesisfirehose.CfnDeliveryStream,  is this a missing feature for this construct?

========The requirement is to import existing resource using CDK===========
  const firehose = kinesisfirehose.CfnDeliveryStream.fromArn(myImportedFirehoseArn);
  
    const eventRule = new eventBus.Rule(this, `example-eventbus-eventlake-rule-${this.id}`, {
      enabled: true,
      description: `Send all events to event lake for ${this.id}.`,
      ruleName: `example-eventbus-eventlake-rule-${this.id}`,
      eventBus: bus,
      targets: [
        new eventsTarget.KinesisFirehoseStream(firehose)
      ],
      eventPattern: {
        source: [ { prefix: "" } ] as any[] // send all events to event lake
      }
    });
============================================

---

This is a 📕 documentation issue

**Comment by peterwoodworth** [comment]
Hey @dayyehm,

All our constructs starting with "Cfn" are [Level 1 resources.](https://docs.aws.amazon.com/cdk/latest/guide/constructs.html#constructs_l1_using) Meaning they are imported from CloudFormation and have no additional functionality (such as importing). So unfortunately without an L2 construct this won't be possible. 

[Looks like it's currently being worked on though!](https://github.com/aws/aws-cdk/issues/7536)
