### ISSUE TITLE
(aws-eks): Ability to suppress selected warnings

### ISSUE THREAD

**Issue by lucaswilric** [aws/aws-cdk#15079]
Introduce a means of selectively suppressing warnings

### Use Case

The `@aws-eks/Cluster` construct sometimes emits warnings for which the most appropriate response is to ignore them. See #14724 for an example of this.

Non-actionable warnings introduce a usability issue because they make it harder to spot warnings that do need action.

To remedy this, it would be useful to have some way of selectively suppressing errors that we know to be non-actionable, to avoid confusion for folks who are new to our codebase, and to help us reliably notice warnings that we need to pay attention to.

### Proposed Solution

The following workaround suppresses warnings by bypassing the Cluster construct's standard interface:

(Works with `aws-cdk` version 1.104.1)

```typescript
import * as eks from "@aws-cdk/aws-eks";

function filterSomeWarning(cluster: eks.Cluster) {
  const node = cluster.node._actualNode;

  (node as any)._metadata = node.metadata.filter(
    (m) => m.type != "aws:cdk:warning" || !m.data.includes("Some substring of the warning message")
  );
}
```

Although this works, it is not really satisfactory, because it is undocumented and relies on knowledge of CDK's internal workings, which could theoretically change at any time.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by peterwoodworth** [comment]
I am marking this issue as p2, which means that we are unable to work on this immediately.

We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://join.slack.com/t/cdk-dev/shared_invite/zt-mso6p56d-qJp7SOTBvMaQuDrx7R2wHg) to solicit support for reprioritization.

**Comment by cayman-amzn** [comment]
Another possible solution: https://github.com/aws/aws-cdk/issues/23403

**Comment by peterwoodworth** [comment]
I think we can close this in favor of the one you've opened @cayman-amzn, thanks for bringing this to our attention 🙂
