### ISSUE TITLE
(aws-codepipeline): cross-account-support-stack customisation

### ISSUE THREAD

**Issue by danwiltshire** [aws/aws-cdk#15086]
### The Question
Is it possible to customise the `cross-account-support-stack` created by CodePipeline?  In my case I need to supply a permission boundary for IAM Roles to appease organisation config rules.

### Environment

  - **CDK CLI Version: 1.107.0 (build 52c4434)** 
  - **Module Version: 1.107.0** 
  - **Node.js Version: 14.16.0** 
  - **OS: WSL2 (Ubuntu 20.04) on Windows 10** 
  - **Language (Version): TypeScript 3.9.9**

**Comment by skinny85** [comment]
Hey @danwiltshire,

today, there is not. However, you can simply pass your own `role` to the appropriate Action, and no `cross-account-support-stack` will be generated.

This way, you have full control over the entire Stack that Role belongs to, and you can customize it in whatever way you want.

Thanks,
Adam

**Comment by danwiltshire** [comment]
Thanks.  So I've achieved this with a new stack in the target account.  Would there be any easy way to avoid cyclic dependencies if I wanted to dynamically populate information for the 'role stack' as the CDK does already with the default cross-account-support-stack?
