### ISSUE TITLE
(core|pipelines): Easily 'stage' a usable CloudFormation template with assets, like SAM

### ISSUE THREAD

**Issue by athewsey** [aws/aws-cdk#15083]
(I've been looking at this use case for a while now and still not fully sure if I'm just missing some easy/obvious way to do this... If nothing else, would ask for the documentation to better reflect the use case!).

Looking for a straightforward way to "package" a CDK stack with basic assets (for me, mainly just Lambda function bundles) to a *human-usable* CloudFormation template:

- With the locations of the assets already embedded into the template - so users don't have to configure
- Preferably with tokenizable asset locations, to support cross-region hosting

From my experiments so far it seems like Pipelines comes close to this, but introduces a CI/CD angle I don't necessarily need (e.g. having to tie to a source repository supported by CodePipline).

### Use Case

I currently manage a few application stacks written in AWS SAM, but pretty much just using SAM for its containerized Lambda build functionality - the stacks are mainly plain CloudFormation, but with some `AWS::Serverless::Function`s.

Of course it would be nice to migrate these stacks to CDK for easier code re-use and etc 😄 

`sam package` lets us stage the Lambda assets to an S3 bucket, and then provide users a CloudFormation stack (or Service Catalog product) which they can deploy specifying just the parameters they know/care about.

In fact, we can currently offer multi-region stacks by:

1. Setting up cross-region replication with region-named buckets e.g. `my-cool-assets-us-east-1`->`my-cool-assets-ap-northeast-1`
2. Post-editing the CloudFormation template generated by SAM to tokenize asset URIs e.g. to `my-cool-assets-${AWS::Region}`

### Proposed Solution

- A top level CDK CLI command which goes beyond `cdk synth` to also stage assets into the current target environment and resolve their locations in the generated template.
- Preferably with built in configuration options to support tokenization of the template for some basic cross-region replication deployment use cases

I think this could make it much easier for users to create reusable CloudFormation/Service Catalog templates from CDK code.

### Other

* [ ] :wave: I may be able to implement this feature request
    * Probably not familiar enough with the code to tackle this myself yet
* [ ] :warning: This feature might incur a breaking change
    * I tentatively think it might be possible to achieve something compatible with CDK pipelines implementation and the current CLI here?

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
At the moment, making template-agnostic stacks that use the `DefaultStackSynthesizer` seems like it would get you closest to what you want. Yes, this mechanism is required by CDK Pipelines, but it's also available independently of CDK Pipelines (that is: you don't need to make a pipeline to deploy these!).

I believe there's also an ongoing PR to add Service Catalog support. Maybe wait for that support to land?
