### ISSUE TITLE
Issue with conditions, intrinsic functions and CDK's construct non-string properties 

### ISSUE THREAD

**Issue by devendra-kumar1** [aws/aws-cdk#15084]
```ts
const parameter = new CfnParameter(this, 'Env', {type: 'String', default: 'test'});
const condition = new CfnCondition(this, 'ConditionLogicalId', { expression: Fn.conditionEquals(parameter, 'test') });

new Table(this, 'DynamoTable', {
            tableName: 'test',
            billingMode: BillingMode.PAY_PER_REQUEST,
            partitionKey: { name: 'id', type: AttributeType.STRING },
            pointInTimeRecovery: Fn.conditionIf(condition.logicalId, true, false)
});
```

It is not allowing me to set **pointInTimeRecovery** to set it conditionally.

However i tried to set string type property it allowing me to do so.

Can you please help me out here ?
### Environment

  - **CDK CLI Version  :*1.90.0*
  - **Framework Version:**
  - **Node.js Version:*14.0* 
  - **OS               :*windows*
  - **Language (Version):**  TypeScript (3.8.3)

### Other

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hi @devendra-kumar1 ,

this is a limitation of the `Table` class. If you want to set it, you will need to use [escape hatches](https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html) to set it:

```ts
        const table = new dynamodb.Table(this, 'DynamoTable', {
          tableName: 'test',
          billingMode: dynamodb.BillingMode.PAY_PER_REQUEST,
          partitionKey: { name: 'id', type: dynamodb.AttributeType.STRING },
        });
        const cfnTable = table.node.defaultChild as dynamodb.CfnTable;
        cfnTable.pointInTimeRecoverySpecification = {
            pointInTimeRecoveryEnabled: cdk.Fn.conditionIf(condition.logicalId, true, false),
        };
```

Thanks,
Adam

**Comment by devendra-kumar1** [comment]
Thanks @skinny85 . It worked :)
