### ISSUE TITLE
(aws-s3-deployment): Support "include" for Source.asset options

### ISSUE THREAD

**Issue by iDVB** [aws/aws-cdk#15090]
Add support for `include` (not just exclude) to "Source.asset()" options.

### Use Case
Prerendered SPAs like GatsbyJS have a directory structure of assets that each have [specific caching requirements](https://www.gatsbyjs.com/docs/caching/).
In the before-CDK days, we would manage asset caching/uploading using a aws cli bash script to handle this.
As you can see below, this requires a strategic assortment of `includes` after starting with a global `exclude "*"`

```bash
# Long Cache for static, css, js except for sw.js
aws s3 sync ./public/ "s3://${BUCKET_NAME}/" \
  --exclude "*" \
  --include "static/*" \
  --include "*.css" \
  --include "*.js" \
  --exclude "sw.js" \
  --cache-control 'public,max-age=31536000,immutable' --delete
# NO cache for html, page-data, and sw.js
aws s3 sync ./public/ "s3://${BUCKET_NAME}/" \
  --exclude "*" \
  --include "*.html" \
  --include "page-data/*.json" \
  --include "sw.js" \
  --include "robot.txt" \
  --include "sitemap/*" \
  --cache-control 'public,max-age=0,must-revalidate' --delete
# Upload/Sync everything else, w/o cache-control
aws s3 sync ./public/ "s3://${BUCKET_NAME}/" \
  --exclude "*.html" \
  --exclude "page-data/*.json" \
  --exclude "*.js" \
  --exclude "*.css" \
  --exclude "static/*" \
  --exclude "robot.txt" \
  --exclude "sitemap/*" \
  --delete
```

`aws-s3-deployment`'s Source doesn't seem to have an `include` option. Nor does it appear that the `asset(path)` can be targeted with a glob pattern. 
```javascript
new BucketDeployment(this, 'BucketDeployment', {
  sources: [Source.asset('./website', { exclude: ['index.html'] })],
  destinationBucket: bucket,
  cacheControl: [CacheControl.fromString('max-age=31536000,public,immutable')],
  prune: false,
})
```

### Proposed Solution
In order to support something like this...
```bash
aws s3 sync ./public/ "s3://${BUCKET_NAME}/" \
  --exclude "*" \
  --include "static/*" \
  --include "*.css" \
  --include "*.js" \
  --exclude "sw.js" \
  --cache-control 'public,max-age=31536000,immutable' --delete

aws s3 sync ./public/ "s3://${BUCKET_NAME}/" \
  --exclude "*" \
  --include "*.html" \
  --include "page-data/*.json" \
  --include "sw.js" \
  --include "robot.txt" \
  --include "sitemap/*" \
  --cache-control 'public,max-age=0,must-revalidate' --delete
```
...you would do this...
```javascript
new BucketDeployment(this, 'BucketDeployment', {
  sources: [Source.asset('./website', { exclude: ['*'], include: ['static/*', '*.css', '*.js', 'sw.js'] })],
  destinationBucket: bucket,
  cacheControl: [CacheControl.fromString('public,max-age=31536000,immutable')],
  prune: true,
})

new BucketDeployment(this, 'BucketDeployment', {
  sources: [Source.asset('./website', { exclude: ['*', 'sw.js'], include: ['page-data/*.json', 'robot.txt', 'sitemap/*', 'sitemap/*'] })],
  destinationBucket: bucket,
  cacheControl: [CacheControl.fromString('public,max-age=0,must-revalidate')],
  prune: false,
})
```

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by iDVB** [comment]
Actually, now that I see that in the CLI the order of the `exclude` and `includes` matter.... I'm not entirely sure how this can translate to Source.assets() neatly. But maybe I've not had enough ☕  yet? Thoughts?

**Comment by iDVB** [comment]
UPDATE: Currently trying to formulate an complex exclude glob that negates to get what I would want...
My brain hurts already... closest I can get is what I want in an INCLUDE pattern
`{**/!(sw).js,**/*.css,/static/**}`
But struggling to get this inverted to work as an EXCLUDE.

**Comment by otaviomacedo** [comment]
What you can do is use the glob strategy to simulate the same sequence of includes and excludes you used to do with the AWS CLI:

```typescript
new s3deploy.BucketDeployment(this, 'DeployWebsite', {
  sources: [s3deploy.Source.asset('./public, {
    exclude: ['*', '!static*', '!static/**', '!*.css', '!*.js', 'sw.js'],
    ignoreMode: IgnoreMode.GLOB,
  })],
  destinationBucket: websiteBucket,
  prune: true,
});
```

**Comment by NGL321** [comment]
Hey @iDVB,

Did @otaviomacedo's suggestion above work for you?

**Comment by peterwoodworth** [comment]
Closing due to staleness, if otavio's suggestion didn't work please ping me and I can reopen the issue
