### ISSUE TITLE
Go: AppRunner - failed mapping between fields and types

### ISSUE THREAD

**Issue by a-h** [aws/aws-cdk#15114]
## :question: General Issue

The generated Go code doesn't connect fields with the correct data types.

In the example below, the `CfnServiceProps` struct has a `SourceConfiguration` field, but this field is of type `interface{}` instead of the generated type`CfnService_SourceConfigurationProperty`.

```go
type CfnService_SourceConfigurationProperty struct {
	// `CfnService.SourceConfigurationProperty.AuthenticationConfiguration`.
	AuthenticationConfiguration interface{} `json:"authenticationConfiguration"`
	// `CfnService.SourceConfigurationProperty.AutoDeploymentsEnabled`.
	AutoDeploymentsEnabled interface{} `json:"autoDeploymentsEnabled"`
	// `CfnService.SourceConfigurationProperty.CodeRepository`.
	CodeRepository interface{} `json:"codeRepository"`
	// `CfnService.SourceConfigurationProperty.ImageRepository`.
	ImageRepository interface{} `json:"imageRepository"`
}

// Properties for defining a `AWS::AppRunner::Service`.
type CfnServiceProps struct {
	// `AWS::AppRunner::Service.SourceConfiguration`.
	SourceConfiguration interface{} `json:"sourceConfiguration"`
	// `AWS::AppRunner::Service.AutoScalingConfigurationArn`.
	AutoScalingConfigurationArn *string `json:"autoScalingConfigurationArn"`
	// `AWS::AppRunner::Service.EncryptionConfiguration`.
	EncryptionConfiguration interface{} `json:"encryptionConfiguration"`
	// `AWS::AppRunner::Service.HealthCheckConfiguration`.
	HealthCheckConfiguration interface{} `json:"healthCheckConfiguration"`
	// `AWS::AppRunner::Service.InstanceConfiguration`.
	InstanceConfiguration interface{} `json:"instanceConfiguration"`
	// `AWS::AppRunner::Service.ServiceName`.
	ServiceName *string `json:"serviceName"`
	// `AWS::AppRunner::Service.Tags`.
	Tags *[]*awscdk.CfnTag `json:"tags"`
}
```

This led me to (incorrectly) guessing at the config:

```go
	awsapprunner.NewCfnService(stack, jsii.String("AppRunner"), &awsapprunner.CfnServiceProps{
		SourceConfiguration: &awsapprunner.CfnService_SourceConfigurationProperty{
			ImageRepository: &awsapprunner.CfnService_ImageRepositoryProperty{
				ImageIdentifier: image.ImageUri(),
				ImageConfiguration: &awsapprunner.CfnService_ImageConfigurationProperty{
					Port: jsii.String("80"),
				},
				ImageRepositoryType: jsii.String("ECR"),
			},
		},
	})
```

This resulted in incorrect SourceConfiguration and unexpected errors.

```yaml
  AppRunner:
    Type: AWS::AppRunner::Service
    Properties:
      SourceConfiguration: {}
    Metadata:
      aws:cdk:path: CdkGoAppRunnerStack/AppRunner
```

I documented the correct way here: https://adrianhesketh.com/2021/06/14/go-cdk-app-runner/

### Environment

  - **CDK CLI Version:** 1.108.1
  - **Module Version:** github.com/aws/aws-cdk-go/awscdk v1.108.0-devpreview
  - **Node.js Version:** v14.15.5
  - **OS:** MacOS
  - **Language (Version):** Go

### Other information

Suggest that:

* CfnService_SourceConfigurationProperty is renamed to remove the "CfnService_" prefix unless it's required.
* CfnService_SourceConfigurationProperty is renamed to remove the "Property" prefix. Go structs don't have properties, they have fields.

**Comment by peterwoodworth** [comment]
I'm not too familiar with Go, but I can answer some of the concerns here.

`interface {}` is what we use for `any` or `JSON` types. So looking at the [CfnServiceProps](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-apprunner.CfnServiceProps.html) all the fields which have the `interface {}` are JSON types. Looking at all the other `Cfn` declarations in Go, they all follow this pattern so I'm pretty sure this is right.

>CfnService_SourceConfigurationProperty is renamed to remove the "CfnService_" prefix unless it's required.
CfnService_SourceConfigurationProperty is renamed to remove the "Property" prefix. Go structs don't have properties, they have fields.

Our L1s (denoted by Cfn) are auto-generated from the [CfnResourceSpec](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html). Since this is an automatic process we don't explicitly declare the name anywhere. I'm not certain how the Go CDK code is generated, nor am I familiar with JSII, but I would assume that renaming of the L1 stuff for Go specifically isn't in the scope of these projects.

Hope this addressed some concerns you have 😄

**Comment by a-h** [comment]
Thanks @peterwoodworth!

## Generation

In that case, I'm think there's a wider problem with the Go CDK generation. I've been using TypeScript CDK for a while, and decided to give the preview Go support a try.

Go's a strongly typed language, and the types have clearly been generated, it's just that the types of the fields are not being set. This means there's no IDE autocomplete, I'm pretty sure that's a bug, because the TypeScript CDK has autocompletion for the same types.

For example when I use the TypeScript CDK, with the same CloudFormation resources, you get autocomplete because it's aware of the types. It doesn't just say that the `imageRepository` field on the `SourceConfigurationProperty` type is of type `any`, it knows that `imageRepository` is of type `CfnService.ImageRepositoryProperty`.

<img width="588" alt="Screen Shot 2021-06-18 at 15 25 55" src="https://user-images.githubusercontent.com/1029947/122576524-ac7d1280-d049-11eb-97b7-ed2e2bb9a18e.png">

This extends through to children of children:

<img width="897" alt="Screen Shot 2021-06-18 at 15 28 10" src="https://user-images.githubusercontent.com/1029947/122576675-d5050c80-d049-11eb-950b-aab9ab92a8db.png">

## Naming

Given what you said about the types being autogenerated, it makes sense to have the `Property` suffix because it exactly matches the  
name in the docs, (e.g. https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-apprunner.CfnService.SourceConfigurationProperty.html) even if it looks unwieldy in the Go code.

But if it's possible to make the name changes during generation, it would tighten up Go CDK code quite a lot, from this:

```go
awsapprunner.NewCfnService(stack, jsii.String("AppRunner"), &awsapprunner.CfnServiceProps{
	SourceConfiguration: awsapprunner.CfnService_SourceConfigurationProperty{
		ImageRepository: awsapprunner.CfnService_ImageRepositoryProperty{
			ImageIdentifier: image.ImageUri(),
			ImageConfiguration: awsapprunner.CfnService_ImageConfigurationProperty{
				Port: jsii.String("8000"),
			},
			ImageRepositoryType: jsii.String("ECR"),
		},
		AuthenticationConfiguration: awsapprunner.CfnService_AuthenticationConfigurationProperty{
			AccessRoleArn: ecrAccessRole.RoleArn(),
		},
	},
})
```

To this:

```go
awsapprunner.NewCfnService(stack, "AppRunner", &awsapprunner.CfnServiceProps{
	SourceConfiguration: awsapprunner.SourceConfiguration{
		ImageRepository: awsapprunner.ImageRepository{
			ImageIdentifier: image.ImageUri(),
			ImageConfiguration: awsapprunner.ImageConfiguration{
				Port: "8000",
			},
			ImageRepositoryType: jsii.String("ECR"),
		},
		AuthenticationConfiguration: awsapprunner.AuthenticationConfiguration{
			AccessRoleArn: ecrAccessRole.RoleArn(),
		},
	},
})
```

**Comment by peterwoodworth** [comment]
Thanks for the thorough reply. @MrArnoldPalmer can you take a look at this?

**Comment by peterwoodworth** [comment]
Marking this as a feature request. Mitch should be able to give you a response soon

**Comment by peterwoodworth** [comment]
Related issue: #16128

**Comment by kaihendry** [comment]
Has anything improved with wrt autocomplete DX with v2? https://aws.amazon.com/about-aws/whats-new/2021/12/aws-cloud-development-kit-cdk-generally-available/

**Comment by MrArnoldPalmer** [comment]
@kaihendry not related to V2, but we are working on improving Go support for both v1 and v2 of the CDK. Because of limitations with JSII, there are some inherent limitations to what types can be rendered in Go. Specifically this issue relates to union types which are currently rendered as `interface{}`.

Specifically, we are investigating improvements to autocomplete through better doc comment generation on properties/types.

**Comment by MrArnoldPalmer** [comment]
We have added runtime type checking with more descriptive error messages to help users fix problems with types that are not verifiable at compile time. This should give hints as to what types that started as unions in typescript, or otherwise end up as `interface{}` in Go, need to be.
