### ISSUE TITLE
codebuild: CDK_DEFAULT_ACCOUNT is not set

### ISSUE THREAD

**Issue by erudisch** [aws/aws-cdk#15122]
Somehow the env var `CDK_DEFAULT_ACCOUNT` is not set. We are using a https proxy and prefix the install command of our synth action with `HTTPS_PROXY=<proxy_url>`.

We also didn't find a solution [here](https://github.com/aws/aws-cdk/issues/5743)

The `.aws` folder is missing as well.

![image](https://user-images.githubusercontent.com/57360330/121944874-71ca6000-cd53-11eb-8edc-2d18d983c079.png)

Sadly there is nothing more to say...

### Reproduction Steps

Maybe setting up a proxy like we did leads to the same problem.

### What did you expect to happen?

That the env var CDK_DEFAULT_ACCOUNT is set.

### What actually happened?

CDK_DEFAULT_ACCOUNT is not set.

### Environment

  - **CDK CLI Version  :*1.108.1 (build ae24d8a)*
  - **Framework Version:*1.108*
  - **Node.js Version:*v14.16.1* 
  - **OS               :*macos 11.4*
  - **Language (Version):*Typescript 4.3.2* 

### Other

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hi @erudisch,

can you specify what command are you running on the CodeBuild job?

Thanks,
Adam

**Comment by peterwoodworth** [comment]
Hey @erudisch, can you please specify which command you're running on your CodeBuild job? Thanks.

**Comment by flashflexpro** [comment]
can use CODEBUILD_BUILD_ARN=arn:aws:codebuild:us-east-1:<account>:build/.......  as workaround
