### ISSUE TITLE
(wafv2): required key [Name] not found, extraneous key [name] is not permitted

### ISSUE THREAD

**Issue by I2olanD** [aws/aws-cdk#15133]
Hello,

i'm not sure if this is a bug or not, but creating a statement with a field to match for singleQueryArgument throws an error, if the key [Name] is actually lowercase.

required key [Name] not found, extraneous key [name] is not permitted.

### Reproduction Steps
```
regexPatternSetReferenceStatement: {
    arn: queryParamRegexPatternSet.attrArn,
        fieldToMatch: {
            singleQueryArgument: {
                name: 'page' //  produces error
             // Name: 'page' works
            }
        },
        ....

}
```
### Environment

  - **CDK CLI Version  :*1.100.0*
  - **Framework Version:*1.100.0*

This is :bug: Bug Report

**Comment by njlynch** [comment]
Thanks for the report.

This isn't a bug, more so than an awkwardness of the native CloudFormation implementation. As these are "L1s" (CloudFormation-only), we are simply modeling what exists in the official spec. The type for singleQueryArgument is documented as ["Json"](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-wafv2-rulegroup-fieldtomatch.html#cfn-wafv2-rulegroup-fieldtomatch-singlequeryargument), with the API docs documenting that the contents of that should be a single field of ["Name"](https://docs.aws.amazon.com/waf/latest/APIReference/API_SingleQueryArgument.html).

In Typescript, this naming convention obviously stands out. Once L2s are created for WAFv2 (see #6878 for tracking), we'll likely try to paper over this so it's more intuitive.
