### ISSUE TITLE
@aws-cdk/aws-lambda-nodejs: permission error on WSL 2

### ISSUE THREAD

**Issue by Andrapyre** [aws/aws-cdk#15131]
When developing on Windows Subsystem for Linux 2, creating a NodeJsFunction leads to the following error on cdk synth:

"Got permission denied while trying to connect to the Docker daemon socket"

### Reproduction Steps

```
import { NodejsFunction } from "@aws-cdk/aws-lambda-nodejs"

export class ServiceStack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props)

    const role = new Role(this, "sample-role", {
      assumedBy: new ServicePrincipal("lambda.amazonaws.com"),
    })

    const lambda = new NodejsFunction(this, "sample-handler", {
      role,
      entry: path.join(__dirname, "index.ts"),
    })
  }
}

```
### What did you expect to happen?
I expected it to synthesize on cdk synth.

### What actually happened?
It generated the following error: "Got permission denied while trying to connect to the Docker daemon socket"

### Environment

  - **CDK CLI Version  : 1.108.1**
  - **Framework Version:**
  - **Node.js Version: 14.0**
  - **OS               : WSL 2**
  - **Language (Version): Typescript(^4.0)**

### Other

--- 

This is :bug: Bug Report

**Comment by aeldo-bw** [comment]
@Andrapyre were you able to find a fix for this?
