### ISSUE TITLE
(pipelines): move update pipeline stage to before build stage

### ISSUE THREAD

**Issue by Andrapyre** [aws/aws-cdk#15141]
The update pipeline stage should come immediately after the source stage and before the build stage.

### Use Case

This is especially important if I need the pipeline to update in order for the build to pass. For example, if I added a lambda function via the NodejsFunction, which requires Docker, but forgot to pass in the privileged flag to the standard yarn synth action. Fixing this, under the current setup, would require removing my function and passing the "privileged" flag to the synth action and running the pipeline. Then I would need to re-add my function and re-run the pipeline again. Preferably, I could just pass in the "privileged" flag, keep my function, and run the pipeline once.

More day-to-day, the update pipeline stage regularly runs when I haven't changed the pipeline and then rebuilds the project. Most of the time that I have run a cdk pipeline it builds the code twice (and I rarely change the pipeline). Moving the update pipeline stage before the build stage would ensure that the build only runs once and that it's always running with the most current version of the pipeline.

Of course, if I change the pipeline, then the build will always run twice by design and that is not ideal.

### Proposed Solution

As indicated above, re-order the pipeline so that the self-update stage always precedes the build stage. Happy to collaborate on this as well - just let me know.

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
Unfortunately this cannot work. 

We cannot update the pipeline before the build happens because the build produces the cloud assembly that contain the pipeline definition.

> if I added a lambda function via the NodejsFunction, which requires Docker, but forgot to pass in the privileged flag to the standard yarn synth action. Fixing this, under the current setup, would require removing my function and passing the "privileged" flag to the synth action and running the pipeline. Then I would need to re-add my function and re-run the pipeline again.

Yes, this is an unfortunate limitation of self-mutation. We will have to see how we might work around that, but I don't see how moving the stages around would fix things (at least not naively).

Keeping this thread open for discussion and to collect upvotes, but the solution probably needs a fair bit of design before any work can start.

**Comment by Andrapyre** [comment]
@rix0rrr , stepping back for some context, why is it necessary to go through a second build stage after the pipeline changes? Won't the second build produce the same resultant infrastructure as the first build?
