### ISSUE TITLE
(Go: awsec2): adding Cidr option in SubnetConfiguration

### ISSUE THREAD

**Issue by O7Oghany** [aws/aws-cdk#15142]
**Is your feature request related to a problem? Please describe.**
yes, as I want control over the IP for each subnet

**Describe the solution you'd like**
adding Cidr option so Developer can choose, if he wants control, or let AWS assign IP range from the VPC Cidr
```
privatSubnet1 := awsec2.SubnetConfiguration{
		Name:       jsii.String("DEVStack PrivatSubnet-Subnet3"),
		SubnetType: "PRIVATE",
                Cidr:               jsii.String("10.0.1.0/19"),
	}

privatSubnet1 := awsec2.SubnetConfiguration{
		Name:       jsii.String("DEVStack PrivatSubnet-Subnet3"),
		SubnetType: "PRIVATE",
                Cidr:               jsii.String("10.0.96.0/19"),
	}
```

**Describe alternatives you've considered**
fo the time being, I have just this option to choose the CidrMask

**Comment by peterwoodworth** [comment]
Hey @abdelmmu,

You can directly configure the CidrBlock of your Subnets. [There's an L2 Subnet Construct](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ec2.Subnet.html) where you can use the `cidrBlock` property and assign it to your VPC on creation of the Subnet

Let me know if you need additional help with this 😄

**Comment by abdelmmu** [comment]
Hi @peterwoodworth,

thanks for pointing me out to this, I thought that under `SubnetConfiguration`  can be implemented, so I can add it as `SubnetProps `or `SubnetAttributes`.
Example working fine:
```
sub := awsec2.NewSubnet(scope, jsii.String("test"), &awsec2.SubnetProps{
		AvailabilityZone:    jsii.String("eu-west-1"),
		CidrBlock:           jsii.String("10.0.1.0/19"),
		VpcId:               jsii.String("TestVPC"),
	})
```
with the creation of the VPC with `SubnetConfiguration `, aws will assign the CidrBlock based on the `CidrMask `, is there a way to do both world 😄? SubnetConfiguration  and control the CidrBlock without a need to initiate the Subnet after creating the VPC ?

Thanks

**Comment by peterwoodworth** [comment]
I'm not sure I understand exactly what you're asking for @abdelmmu, what is it exactly you would like to accomplish and why does creating the subnets after creating the VPC not work for you?

**Comment by mrpackethead** [comment]
My understanding is that ec2.Vpc will divide the entire CIDR block up, and create all the subnets for you.  Its that behavior thats problematic.     I have for a long time, really disliked the ec2.Vpc construct, as it is not flexible enough to build 'real world' networks. Its probalby fine for one project vpcs, but at least in the enterprise space this doe'stn work. 

The way I have worked around this, is to use the L1 constructs ( CfnVpc, CfnSubnet etc, and build up all the parts bit by bit. Its a bit more work, but i get exactly what i want..   If you create it as your own construct, you can just call it in..  The down side of this, is that it difficult to refer back to the object you make.   as many of the cdk constructs need a ec2.Vpc to work. 

In my world, all my vpcs are defined in stacks outside of my applications, so we can import them in using a ec2.Vpc.fromlookup.

**Comment by peterwoodworth** [comment]
Thanks for the response @mrpackethead, you're correct in that the VPC will divide the entire CIDR block up and create the subnets for you. But this is only true if you don't use the [`subnetConfiguration`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ec2.Vpc.html#subnetconfiguration) property. If you [use the subnetConfiguration property](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-ec2-readme.html#advanced-subnet-configuration) you'll be able to create subnets of the type and size you want, and it won't create additional subnets other than what you provide. However, the only downside here is you won't be able to explicitly choose the CIDR block.

**Comment by peterwoodworth** [comment]
If you really want to be able to change the CIDR block of these subnets instead of having the CDK create the blocks for you, you can override the properties: 

```ts
    const cfnSubnet = MyCustomVpc.publicSubnets[0].node.defaultChild as CfnSubnet
    cfnSubnet.addPropertyOverride('CidrBlock', '10.0.0.0/28');
```

**Comment by abdelmmu** [comment]
thanks @mrpackethead for making it more clear, that the subent config will divide the entire CIDR block up, Even if I just want one subnet it will automatically make 3 for me and add the suffix.

If I will create the VPC without `SubnetConfiguration` it will create for me the 6 subnets, 3 Public and 3 Private 
`	vpc := awsec2.NewVpc(stack, jsii.String("DEVStack"), &awsec2.VpcProps{
		Cidr:               jsii.String("10.0.0.0/16"),
		MaxAzs:             jsii.Number(3),
		NatGatewayProvider: natProvider,
		NatGateways:        jsii.Number(3),
		NatGatewaySubnets: &awsec2.SubnetSelection{
			SubnetType: "PUBLIC",
		},
	})`
But as said, if this option `CidrBlock`  can not be implemented ` awsec2.SubnetConfiguration` then I have to live with it and create just one `awsec2.SubnetConfiguration` to have 3 or use `awsec2.NewSubnet` with the 3 auto generated Subents.

**Comment by peterwoodworth** [comment]
I am marking this issue as p2, which means that we are unable to work on this immediately.

We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://join.slack.com/t/cdk-dev/shared_invite/zt-mso6p56d-qJp7SOTBvMaQuDrx7R2wHg) to solicit support for reprioritization.
