### ISSUE TITLE
(CodeStarConnectionsSourceAction): repo name wrongly formated

### ISSUE THREAD

**Issue by evanerwee01** [aws/aws-cdk#15154]
# :question: Repo name wrongly submitted. (Pipeline fail) Unwanted character added.

When a repo name is specified, e.g. f'dso', a '/' is always inserted in front. Example:
f'Greenwidget/dso' become /Greenwidget/dso'
f'dso' become /dso'  

## Code Sample

```python
self.mssp_pip_for_tf = codepipeline.Pipeline(
    self, "Pipeline",
    stages=[
        codepipeline.StageProps(stage_name="Source",
                                actions=[
                                    codepipeline_actions.CodeStarConnectionsSourceAction(
                                        action_name='Greenwidget-GitHub-' + self.repo_name.split("/", 1)[1],
                                        connection_arn=self.connection_arn,
                                        owner=self.repo_owner,
                                        repo=self.repo_name,
                                        branch=self.branch_name,
                                        trigger_on_push=True,
                                        code_build_clone_output=True,
                                        output=self.mssp_tf_source_output)]),
        codepipeline.StageProps(stage_name="Build",
                                actions=[
                                    codepipeline_actions.CodeBuildAction(
                                        action_name="Terraform_Build",
                                        project=self.mssp_pipj_for_tf,
                                        input=self.mssp_tf_source_output,
                                        outputs=[self.mssp_tf_build_output])])
    ]
)
```

### The Question

Repo field must have the ability to pass the name without formatting, e.g. Organization/RepoName, example: Greenwidget/dso.

### Environment

  - **CDK CLI Version:** 1.8
  - **Module Version:** 1.8
  - **Node.js Version:** 16.3.0
  - **OS:** Windows 10
  - **Language (Version):** Python (3.9)

### Other information
Destination repo is GitHub with repo's in an organization

**Comment by skinny85** [comment]
Hi @evanerwee01,

can you please show what is `self.repo_name` in your above code?

Thanks,
Adam

**Comment by skinny85** [comment]
And `self.repo_owner` and `self. repo_name`, while we're at it 😜.

**Comment by evanerwee01** [comment]
self.repo_name is set to Greenwidget/repo-name.  

        for pod in helpers.ECS_PODS:
            self.team_name = f'{pod}'.lower()
            self.mssp_pipeline_id = f'{helpers.NESTED_ENTITY_PREFIX}-{self.team_name}-pipeline-{helpers.STAGE}'
            self.mssp_pipeline_state = ECRPipelineMasterStack(
                self,
                self.mssp_pipeline_id,
                branch_name='main',
                repo_name=f'Greenwidget/mssp-dso-{pod}',
                repo_owner='',
                env=helpers.ENV_DSO,
                pipeline_policy=getattr(policy_def, f'{pod.upper()}_DSO_POLICY'),
                team_name=self.team_name,
                props=props
            )

**Comment by skinny85** [comment]
That's wrong then. `repo_owner` should be `'Greenwidget'` (it's now empty), and `repo_name` should be `'repo-name'`.

**Comment by evanerwee01** [comment]
Fantastic. Let me change the code and I will post back shortly. Thank You.

**Comment by evanerwee01** [comment]
I can confirm that setting the **repo_owner** to the Github **organization** name solve the problem. Thank you for the very quick response.

**Comment by evanerwee01** [comment]
### Code snippet now.

        for pod in helpers.CDK_PODS:
            self.team_name = f'{pod}'.lower()
            self.mssp_pipeline_id = f'{helpers.NESTED_ENTITY_PREFIX}-{self.team_name}-pipeline-{helpers.STAGE}'
            self.mssp_pipeline_state = CDKPipelineMasterStack(
                self,
                self.mssp_pipeline_id,
                branch_name='main',
                repo_name=f'mssp-dso-{pod}',
                repo_owner='Greenwidget',
                env=helpers.ENV_DSO,
                pipeline_policy=getattr(policy_def, f'{pod.upper()}_DSO_POLICY'),
                team_name=self.team_name,
                props=props
            )
