### ISSUE TITLE
(aws-cdk): Add support for TOML to output-file

### ISSUE THREAD

**Issue by iDVB** [aws/aws-cdk#15159]
It would be super helpful if there were two additions to `--outputs-file`
1) that you could pick the output type. We typically slurp these up as TOML files in `.env`
2) that I could choose to flatten the file for that the top node is just the vars and not the stackname. At the very least that this would happen if you only have a single stack.

### Use Case
We're currently trying to get CDK outputs into a GatsbyJS build which uses `dotenv` (`.env`) to slurp them up.
We'd like to keep the build agnostic of the stack name so can have it nested in one. 

### Proposed Solution
```
cdk deploy --outputs-file .env --outputs-format toml
```

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by peterwoodworth** [comment]
Thank you for the request @iDVB 😄 

I am marking this issue as p2, which means that we are unable to work on this immediately.

We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://join.slack.com/t/cdk-dev/shared_invite/zt-mso6p56d-qJp7SOTBvMaQuDrx7R2wHg) to solicit support for reprioritization.

If you're able to implement this yourself someone would be happy to take a look at the PR!
