### ISSUE TITLE
(Role): role.d.ts[24,14] Class Role incorrectly implements interface IRole

### ISSUE THREAD

**Issue by normjon** [aws/aws-cdk#15150]
### Environment

  - **CDK CLI Version  :1.107.0 (build 52c4434)
  - **Framework Version:1.108.1
  - **Node.js Version:v16.3.0 
  - **OS              :MAC
  - **Language (Version):Typescript 

### Other

--- 

This is :bug: Bug Report

**Comment by peterwoodworth** [comment]
Hey @normjon, without more information I'm not able to help you. Can you tell me more about your problem?

**Comment by normjon** [comment]
I thought I provided details, but clearly I didn't.  Here you go.

Example code giving error:
const role = new iam.Role(this, 'myRole', {
      assumedBy: new iam.AccountPrincipal('1234')
});

Error description coming from IDE:
Type 'AccountPrincipal' is not assignable to type 'IPrincipal'.
  Types of property 'principalAccount' are incompatible.
    Type 'string | undefined' is not assignable to type 'string'.
      Type 'undefined' is not assignable to type 'string'.

Error description for Class Role (role.d.ts):
Class 'Role' incorrectly implements interface 'IRole'.
  Types of property 'principalAccount' are incompatible.
    Type 'string | undefined' is not assignable to type 'string'.
      Type 'undefined' is not assignable to type 'string'.

Let me know if more details are needed.

Thanks

**Comment by peterwoodworth** [comment]
Can you check your package.json to make sure all CDK related packages are the same version?

**Comment by mweitzel2005** [comment]
@peterwoodworth response worked for me when I got the following error: `Type 'Role' is not assignable to type 'IRole'.`
CDK dependencies installed after the initialisation had a higher version number than the `core` package. Set them all to the same version as the `core` package and it works (i.e. no errors).

**Comment by peterwoodworth** [comment]
Yup, that's the most common cause of this error, it's likely what happened to @normjon as well

**Comment by peterwoodworth** [comment]
Ping me if you need any more help with this 😄

**Comment by normjon** [comment]
Thanks for looking into this.  I'll be sure to check the library and core versions

**Comment by BwL1289** [comment]
@peterwoodworth Having an issue with this (using `Python` and `CDKv2` in my case). 

Error (using `PyLance`):
```
Argument of type "Role" cannot be assigned to parameter "role" of type "IRole | None" in function "__init__"
  Type "Role" cannot be assigned to type "IRole | None"
    "Role" is incompatible with protocol "IRole"
      "grant_pass_role" is an incompatible type
        Type "(identity: IPrincipal) -> Grant" cannot be assigned to type "(grantee: IPrincipal) -> Grant"
          Parameter name mismatch: "grantee" versus "identity"
    Type cannot be assigned to type 
```

Steps I've taken to mitigate, given feedback above:
1. Deactivate and delete my virtual environment
2. Updated my constraints.txt file with the following versions:
```
pytest==6.2.5
boto3==1.20.37
aws-cdk-lib==2.23.0
constructs==10.1.5
cdk8s==2.2.85
cfnresponse==1.1.2
```
3. Updated npm: `npm update`
4. Updated aws CLI: `npm i -g aws-cdk` 
5. Created new virtual environment: `python3 -m venv .venv`
6. Activated my virtual environment: `. .venv/bin/activate`
7. Install requirements: `pip install -r requirements.txt -r requirements-dev.txt -c constraints.txt`

Still seeing this error :/. I'm not sure how the `Pipfile` plays into this, but would appreciate any clarification possible.

**Comment by tezz-io** [comment]
Can you try `npm i -g aws-cdk@2.23.0`?
