### ISSUE TITLE
(aws-elasticloadbalancingv2): expose target group routing algorithm

### ISSUE THREAD

**Issue by KirkF** [aws/aws-cdk#15160]
Although it appears to be supported in [CloudFormation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticloadbalancingv2-targetgroup-targetgroupattribute.html) changing the target group routing algorithm from the default of round_robin to least_outstanding_requests does not seem possible in CDK according to both the API documentation and my understanding of the [source code](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-target-group.ts)

### Use Case
As part of our stack we create a target group which gets attached to an ALB, and round_robin is not the most appropriate routing algorithm for our use case

### Proposed Solution
Add ApplicationTargetGroup property which implements underlying target group attribute of CloudFormation.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by njlynch** [comment]
You're correct that there's no CDK-native way to do this currently. You can use [escape hatches](https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html) to set the property yourself.

This seems like a reasonable feature request, and one that would be relatively simple to add. The implementation itself would be a (simpler) version of supporting cookie stickiness (https://github.com/aws/aws-cdk/pull/13142), which was the most recent ALB attribute support added.

We welcome community contributions! If you are able, we encourage you to [contribute](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) a bug fix or new feature to the CDK. If you decide to contribute, please start an engineering discussion in this issue to ensure there is a commonly understood design before submitting code. This will minimize the number of review cycles and get your code merged faster.

**Comment by bitoku** [comment]
There is no way to do it when you create a target group.
However you can do it after creating a target group using `setAttribute`.

```typescript
const app = new App();
const stack = new Stack(app, 'stack1');
const vpc = new Vpc(stack, 'vpc');

const targetGroup = new ApplicationTargetGroup(stack, 'targetGroup', {
  vpc,
  protocol: ApplicationProtocol.HTTP
});
targetGroup.setAttribute('load_balancing.algorithm.type', 'least_outstanding_requests');
```

This is very minimal example, and I confirmed it worked.

**Comment by nohack** [comment]
@njlynch created a pr #15622. thanks
