### ISSUE TITLE
(aws-lambda-nodejs): pnpm esbuild localCommand fails

### ISSUE THREAD

**Issue by hugdru** [aws/aws-cdk#15164]
The created localCommand for pnpm is failing because of an `--` after esbuild:

```json
[
  "pnpm exec esbuild --",
  "--bundle",
  "\"/home/me/repo/cdk/lib/lambda/quickSightGetUrl/lambdaCode/index.ts\"",
  "--target=node14.0.0",
  "--platform=node",
  "--outfile=\"/tmp/me/cdk.outKYr4UP/bundling-temp-be2edeadca3c5bca8951944d3db169f0f4c6f0dfbde8b9fcc9ee1bae265871f9/index.js\"",
  "--minify",
  "--external:aws-sdk"
]
```

Returns:

`> error: Invalid build flag: "--"`

The command works if I run it without the "--".

### Reproduction Steps

```bash
npm install -g pnpm
mkdir test && cd test && pnpx cdk init app --language typescript
pnpm add @aws-cdk/aws-lambda-nodejs && pnpm add esbuild -D


cat << 'EOF' > "lib/test-stack.ts"
import * as cdk from '@aws-cdk/core';
import * as nodeLambda from '@aws-cdk/aws-lambda-nodejs';

export class TestStack extends cdk.Stack {
    constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
        super(scope, id, props);

        new nodeLambda.NodejsFunction(this, 'index', {})
    }
}
EOF

touch "lib/test-stack.index.ts"

pnpm install && pnpm cdk synth
```

### What did you expect to happen?

A successful bundling when using pnpm  

### What actually happened?

The esbuild command failed with `> error: Invalid build flag: "--"` 

### Environment

  - **CDK CLI Version  :** 1.108.1 (build ae24d8a)
  - **Framework Version:** 1.108.1
  - **Node.js Version:** v14.16.1
  - **OS               :** Ubuntu 21.04
  - **Language (Version):** TypeScript (4.3.2)
  - **pnpm:** 6.7.6
  - **esbuild:** 0.12.9

### Other

I had a look at https://github.com/pnpm/pnpm/blob/76136751958ceac0ee77e9a0466b96d4a093a094/packages/plugin-commands-script-runners/src/exec.ts#L73 and -- seems to be needed for backward compatibility as a first argument for exec.

--- 

This is :bug: Bug Report

**Comment by jogold** [comment]
@relm923 any idea?

**Comment by hugdru** [comment]
@jogold I think #15410 fixes the issue
