### ISSUE TITLE
(pipelines): add testCommand(s) property to standardYarnSynth and standardNpmSynth action

### ISSUE THREAD

**Issue by bmacher** [aws/aws-cdk#15168]
When creating a `SimpleSynthAction` it is preferred to use the helpers `standardYarnSynth` and `standardNpmSynth`. However both are missing the `testCommands` property from `SimpleSynthAction` which is kind of useful. Otherwise we have to put the test command into the build or synth command. Like:

```ts
const synthAction = SimpleSynthAction.standardYarnSynth({
  // ...
  buildCommand: 'yarn test && yarn build',
});
```

### Use Case

With the `testCommands` prop I don't have to mix the test command with build or synth command.

### Proposed Solution

```ts
const synthAction = SimpleSynthAction.standardYarnSynth({
  // ...
  testCommands: ['yarn test'],
  buildCommand: 'yarn build',
});
```

Could also just be `testCommand: 'yarn test'`

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by hoegertn** [comment]
This was release today

https://github.com/aws/aws-cdk/pull/14979

**Comment by bmacher** [comment]
Sorry, just looked in the Issues sections.
