### ISSUE TITLE
(pipelines): need full control of BuildSpec

### ISSUE THREAD

**Issue by rix0rrr** [aws/aws-cdk#15169]
So set things like `runtime-versions`, `caching`, etc.

Would be good if we could merge artifacts parts of buildspecs...

---

This is a :rocket: Feature Request

**Comment by hoegertn** [comment]
For which CodeBuild job? Synth, Assets, or UpdatePipeline?

**Comment by rix0rrr** [comment]
Synth is foremost in my mind.

**Comment by mrpackethead** [comment]
+1 for this.  This would be reallyk handy.

**Comment by hoegertn** [comment]
@rix0rrr did you create this for tracking only or is this not on your roadmap? I could take it over if you like.

**Comment by rix0rrr** [comment]
Notes on our discussion:

- BuildSpecs will become mergeable
- In principle this can be serviced by doing a deep JSON merge (recurse into objects, append lists), with the following exceptions:
  - Decided to disallow merging of artifact specs (actually impossible since we can't merge two buildspecs with a single primary output into a buildspec with multiple outputs--in case of multiple outputs they must have identifiers but we won't have that information)
  - In case of test reports we replace the whole object with the RHS (instead of recursively merging)
- SynthAction and the Pipeline will get `buildSpec?` or `partialBuildSpec?` properties (name tbd) which will be merged with the generated buildspecs to produce a full, final buildspec.

**Comment by mrpackethead** [comment]
Possibly related, and you might be able to address this with this work.  ( or not )
https://github.com/aws/aws-cdk/issues/15279
