### ISSUE TITLE
(aws-cdk): The CDK CLI fails to run via npx in node:12 and node:14

### ISSUE THREAD

**Issue by misterjoshua** [aws/aws-cdk#15162]
The CDK CLI fails to run via `npx` in the `node:12` and `node:14` container images. The `postinstall` script for the `aws-sdk` dependency fails with a `MODULE_NOT_FOUND` error.

This is problematic in container-based build environments. For instance, as a step in one of our build pipelines, we like to run `npx cdk --app cdk.out diff SomeStack` or `npx cdk --app cdk.out deploy SomeStack`. But, this approach broke somewhere around `aws-cdk@1.103.0`.

### Reproduction Steps

Run any of these commands: 

```
docker run --rm -it node:14 npx -p aws-cdk cdk --version
```
```
docker run --rm -it node:12 npx -p aws-cdk cdk --version
```

### What did you expect to happen?

I expected the CDK CLI to run and display the CDK CLI's version number.

### What actually happened?

A `MODULE_NOT_FOUND` error is thrown:

```
docker run --rm node:14 npx -p aws-cdk cdk --version
internal/modules/cjs/loader.js:888
  throw err;
  ^

Error: Cannot find module '/root/.npm/_npx/1/lib/node_modules/aws-cdk/node_modules/aws-sdk/scripts/check-node-version.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! aws-sdk@2.922.0 postinstall: `node scripts/check-node-version.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the aws-sdk@2.922.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-06-16T20_49_41_663Z-debug.log
Install for [ 'aws-cdk@latest' ] failed with code 1
```

### Environment

  - **CDK CLI Version  :** 1.103.0 and later.
  - **Framework Version:** 1.103.0 and later.
  - **Node.js Version:**  node 12 and 14
  - **OS               :** Linux / Docker node:12 and node:14
  - **Language (Version):**  all

### Other

The AWS CDK `1.102.0` was the last version worked with npx in the node 12 and 14 containers. e.g.:

```
docker run --rm -it node:14 npx -p aws-cdk@1.102.0 cdk --version
```

There's an AWS SDK issue here, but there doesn't seem much traction: https://github.com/aws/aws-sdk-js/issues/3763

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
As this is a JS SDK issue, not something the CDK can do something about. Upgrading to JS SDK v3 won't help as it has the exact same `postinstall` script.

Experimentation shows that the following environment variable serves as a workaround:

```
NPM_CONFIG_UNSAFE_PERM=true
```

Good luck.
