### ISSUE TITLE
(aws-cdk): Error after upgrading to 1.109.0: This CDK deployment requires bootstrap stack version '6', found '5'.

### ISSUE THREAD

**Issue by markusl** [aws/aws-cdk#15172]
Our deployments fail after upgrading CDK to the latest version: `This CDK deployment requires bootstrap stack version '6', found '5'. Please run 'cdk bootstrap'.`.

### Reproduction Steps

Upgrade from 1.108.0 to 1.109.0.

### What did you expect to happen?
 
Smooth upgrade process.

### What actually happened?

It seems a breaking change has been introduced without any notice in the changelog.

### Environment

  - **CDK CLI Version  :** 1.109.0 (build c647e38)
  - **Framework Version:** 1.109.0 (build c647e38)
  - **Node.js Version:** 14
  - **OS               :** macOS
  - **Language (Version):** 4

### Other

--- 

This is :bug: Bug Report

**Comment by markusl** [comment]
@straygar the issue here is we have hundreds of accounts and this kind of change is very unexpected and will break the usual workflows. I wish this change would have been bundled with CDK v2 which includes other breaking changes.

**Comment by jonathanlemonsonos** [comment]
I am seeing the following, when trying to then bootstrap my application:

This CDK CLI is not compatible with the CDK library used by your application. Please upgrade the CLI to the latest version.
(Cloud assembly schema version mismatch: Maximum schema version supported is 11.0.0, but found 12.0.0)

**Comment by rkustner** [comment]
we feel the same pain as @markusl ... we could push the bootstrap upgrade to all accounts but I wonder if the new bootstrap is backwards compatible? so will it work if an account is using a slightly older version of the cdk?

**Comment by mrpackethead** [comment]
@rkustner .. the bootstrap is backwards compatible,   templates created with cdk 1.109 need bootstrap 6 or higher..    So a template that requried version 4 or higher ( about version 0.72? ) will work very happily with bootstreap version 6.    

We run an evergreen environment.  We take the approach that we'll always keep uptodate, and we'll make what changes we need to keep to date at all times.   It means we need to be quite quick on our feet at time when an upgrade like this occurs...

**Comment by rix0rrr** [comment]
You are correct @markusl, this should have been in the changelog. Sorry about that.
