### ISSUE TITLE
(stepfunctions-tasks): EcsRunTask containerOverrides throws if container name doesn't match construct ID

### ISSUE THREAD

**Issue by Cruaier** [aws/aws-cdk#15171]
I ran into an issue while updating CDK from 1.77.0 to1.109.0. I create a step function which utilizes ECS tasks (Fargate) to run a long-running task. It uses `EcsRunTask` from the `@aws-cdk/aws-stepfunctions-tasks` library.

### Reproduction Steps

```
const vpc = new ec2.Vpc(this, 'VPC');
const taskDefinition = new ecs.FargateTaskDefinition(this, 'TaskDefinition', {
  cpu: 1024,
  memoryLimitMiB: 8192,
});
const containerDefinition = taskDefinition.addContainer('TaskContainer', {
  image: ecs.ContainerImage.fromDockerImageAsset(new ecrassets.DockerImageAsset(this, 'asset', { directory: path.join(__dirname, './image-asset') })),
  containerName: 'AnyOtherNameThatIsNotTheConstructId',
  environment: {
    EVENT: '',
  },
});
new sfntasks.EcsRunTask(this, 'ECSTaskRun', {
  cluster: new ecs.Cluster(this, 'Cluster', { vpc }),
  launchTarget: new sfntasks.EcsFargateLaunchTarget(),
  taskDefinition: taskDefinition,
  assignPublicIp: true,
  containerOverrides: [
    {
      containerDefinition: containerDefinition,
      environment: [{ name: 'EVENT', value: 'something' }],
    },
  ],
  integrationPattern: sfn.IntegrationPattern.RUN_JOB,
  resultPath: sfn.JsonPath.DISCARD,
});
```

### What did you expect to happen?

No error, since the container definition defined in the override is directly returned from the call to `TaskDefinition.addContainer`, implying that the container does in fact exist in the task definition.

### What actually happened?

```
Error: Overrides mention container with name 'XXX', but no such container in task definition
```

### Environment

  - **Framework Version:** 1.109.0
  - **Node.js Version:** v14.16.1

### Other

Error is coming from the code in `cdk\node_modules\@aws-cdk\aws-stepfunctions-tasks\lib\ecs\run-task.js` line 141 were it takes the name of the container (as defined in the overriding option) and looks for it (as a key) in the task definition (with the function `tryFindChild`:

```
            const name = override.containerDefinition.containerName;
            if (!cdk.Token.isUnresolved(name)) {
                const cont = this.props.taskDefinition.node.tryFindChild(name);
                if (!cont) {
                    throw new Error(`Overrides mention container with name '${name}', but no such container in task definition`);
                }
            }
```

--- 

This is :bug: Bug Report

**Comment by BenChaimberg** [comment]
Workaround before a fix can be made: set the construct ID and the container name to be the same value:
```
const containerName = 'TaskContainer';
const containerDefinition = taskDefinition.addContainer(containerName, {
  containerName: containerName,
  // ...
});
```

**Comment by BenChaimberg** [comment]
@Cruaier please feel free to assign me to a fix PR if you happen to work on one. The proper solution is probably to just expose `ecs.TaskDefinition.findContainer` as public and use that instead of inspecting the construct tree as we do currently. But happy to discuss different options!
