### ISSUE TITLE
aws-docdb - missing deletion protection

### ISSUE THREAD

**Issue by dr-star** [aws/aws-cdk#15170]
In aws-cdk/aws-docdb I saw that isn't possible to set the deletion protection using the construct DatabaseCluster.

### Use Case

Is possible to add also in that construct the attribute "deletionProtection" that is available into CfnDBCluster ?

### Proposed Solution

...

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by NGL321** [comment]
Hey @dr-star,

Thank you for submitting this request. I have looked it over and it sounds like something that should be added to our L2!

It looks like this is a feature that exists in the L1, so if you need a workaround before this is implemented, using the L1 should do the trick!

If you want to see this get implemented faster, feel free to garner upvotes or submit a PR with the feature yourself.

😸 😷

**Comment by cjihrig** [comment]
> If you want to see this get implemented faster, feel free to garner upvotes or submit a PR with the feature yourself.

@NGL321 I've opened a PR at https://github.com/aws/aws-cdk/pull/15216.
