### ISSUE TITLE
@aws-cdk/aws-lambda-event-sources: Unable to add sqs event source to lambda

### ISSUE THREAD

**Issue by adirshab** [aws/aws-cdk#15178]
### The Question
I'm trying to add SQS event source from existing queue to a new lambda, but when i'm running cdk deploy i encounter this problem.

`5:08:08 PM | CREATE_FAILED        | AWS::IAM::Policy                | <PolicyName>
The policy <PolicyName> already exists on the role <Role>.`

I was able to add a lambda trigger to the queue manually after deploy the lambda with no event source.

This is the code I used:

```
const lambda = new Lambda.Function(this, `MY_LAMBDA_NAME`, {
                runtime: Lambda.Runtime.NODEJS_12_X,
                code: Lambda.Code.fromAsset('lambda'),
                handler: 'HANDLER',
                reservedConcurrentExecutions: 1,
                role,
                timeout: Cdk.Duration.seconds(900),
                memorySize: 2048
            });

            const queue = sqs.Queue.fromQueueArn(this, 'QUEUE_NAME', 'MY_ARN');

            lambda.addEventSource(new SqsEventSource(queue))
```

### Environment

  - **CDK CLI Version:** 1.108.1
  - **Module Version:**  1.108.1
  - **Node.js Version:** v14.5.0
  - **OS:**  macOS Big Sur
  - **Language (Version):** TypeScript 4.0.5

**Comment by peterwoodworth** [comment]
Hey @adirshab, can you share which `<PolicyName>` already exists, and which role it's trying to add the policy to? 

I wonder if it was [either of the policies](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-lambda.Function.html#role) that are required for the lambda function to have

I wasn't able to reproduce this so I'm going to need more info to help you out. How are you creating the role?

**Comment by adirshab** [comment]
The policy is `CreativesServiceRolePolicy03F02C35` and the role is `CreativesServiceRole`.

Both already existed before i tried to deploy with the sqs trigger

**Comment by adirshab** [comment]
Found the issue, an auto generated policy has not beed destructed correctly. Thanks!
