### ISSUE TITLE
Prior warning for bootstrap changes

### ISSUE THREAD

**Issue by mrpackethead** [aws/aws-cdk#15186]
Changes to the bootstrap are evitable, as CDK evolves..  There can be a bit of pain when it changes, particularly if it catches you out when a version updates and things no longer work...

So..

(1) It would be great if new bootstrap templates versions get released several versions before cdk generates templates requiring them.   As there is backwards compatibility,   this wont' cause much trouble if you use a newer bootstrap than you require.   I dont' think you need to make this particually long..  I would be happy if i had 7-14 days 'warning' of a change. 

(2) It would also be very helpful if a well known SSM parameter could be published,, ( similar to the ones that tell you what the latest ami id is etc )..   We could use that to check against when our pipelines run ( or maybe even have synth look at it and produce a warning ) to see if we are currnent.

Expanding on this, you might even be able to create some kind of subscription service, (SNS?) that pushes out a version change notice.. That would mean it shoudl be easy enough to automate an upgrade if you wanted. 

### Use Case

We have deliberately chosen to run an 'evergreen' environment.  We only pin versions as a last resort to keep things working, so anything we can do to keep ahead of changes is a good thing.

This is a :rocket: Feature Request

**Comment by njlynch** [comment]
Thanks for the suggestion, @mrpackethead !

I agree that the current bootstrap upgrade experience leaves something to be desired. 

There are some good suggestions here. I suspect we might also come up with other creative solutions to improving this upgrade experience for our customers. I'm going to mark this as a p1, which means it should be on our near-term roadmap. I'd love to gather more feedback from the team and community on ways we can improve this process. Feedback welcome!
