### ISSUE TITLE
(@aws-cdk/assert): Unable to pass test if a resource doesn't exist

### ISSUE THREAD

**Issue by longtv2222** [aws/aws-cdk#15184]
### The Question

I want to write validation tests and make it a library so that every stack can follow best security practices, naming convention, ... for my cdk stacks.

I've been looking at aws-assert for it and it seems not possible to run test **only**  if a resource exists in the stack.

For example, if I were to write:

```typescript
import { haveResourceLike,expect } from "@aws-cdk/assert";
import { mystack } from "..."

test('Bucket versioning must be enabled', () => {
        expect(mystack).to(haveResourceLike("AWS::S3::Bucket", {
            VersioningConfiguration: {
                Status: "Enabled"
            }
        }));
})
```

without any bucket in the stack then that would fail as expected.

The issue https://github.com/aws/aws-cdk/issues/12452 had similar problem as mine and I tried the proposed solution which was 
```typescript
import { haveResourceLike,expect } from "@aws-cdk/assert";
import { mystack } from "..."

test('Bucket versioning must be enabled', () => {
    if (haveResourceLike("AWS::S3::Bucket"))
        expect(mystack).to(haveResourceLike("AWS::S3::Bucket", {
            VersioningConfiguration: {
                Status: "Enabled"
            }
        }));
})
```
However, the test didn't pass.

Is there anyway to bypass this limitation?

### Environment

  - **CDK CLI Version:** 1.109
  - **Module Version:** 1.109.0
  - **Node.js Version:** v12.18.3
  - **OS:** Windows 10  
  - **Language (Version):** TypeScript (4.3.3)

**Comment by peterwoodworth** [comment]
Hey @longtv2222, I think in theory what you posted should work, can you tell me what specifically is going wrong when the test doesn't pass?

**Comment by longtv2222** [comment]
I created a sample repo for this https://github.com/longtv2222/cdk-assert-error. (Created with ```cdk init sample-app --language typescript```)

![image](https://user-images.githubusercontent.com/61606375/122469144-d36c1380-cf79-11eb-932b-0ac3e8e3426f.png)

It seems to me that the if statement didn't verify the existence of Queue.

**Comment by longtv2222** [comment]
For sanity check, I tried 

```typescript
import { expect as expectCDK, haveResourceLike } from '@aws-cdk/assert';
import * as cdk from '@aws-cdk/core';
import * as CdkAssertError from '../lib/cdk-assert-error-stack';

test('SQS Queue Exist', () => {
  const app = new cdk.App();
  // WHEN
  const stack = new CdkAssertError.CdkAssertErrorStack(app, 'MyTestStack');
  // THEN

  if (!haveResourceLike("AWS::SQS::Queue")) //Test if the if statement does anything
    expectCDK(stack).to(haveResourceLike("AWS::SQS::Queue", {
      VisibilityTimeout: 300
    }));
});
```
with 

```typescript
import * as sqs from '@aws-cdk/aws-sqs';
import * as cdk from '@aws-cdk/core';

export class CdkAssertErrorStack extends cdk.Stack {
  constructor(scope: cdk.App, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const queue = new sqs.Queue(this, 'CdkAssertErrorQueue', {
      visibilityTimeout: cdk.Duration.seconds(200)
    });
    
  }
}
```

However the test passed
![image](https://user-images.githubusercontent.com/61606375/122470768-af113680-cf7b-11eb-823f-8ea71d4b3256.png)

**Comment by peterwoodworth** [comment]
Hmm I'm finding the same thing as you. The if statement isn't working, I'll research this and get back to you

**Comment by longtv2222** [comment]
For anyone who encounters this problem, my work around is to wrap haveResourceLike inside a try catch to check if a resource exists or not. 
Sample code is as below: 
```typescript 

import { expect as expectCDK, haveResourceLike } from '@aws-cdk/assert';
import * as cdk from '@aws-cdk/core';
import * as CdkAssertError from '../lib/cdk-assert-error-stack';

test('SQS Queue Exist', () => {
  const app = new cdk.App();
  // WHEN
  const stack = new CdkAssertError.CdkAssertErrorStack(app, 'MyTestStack');
  // THEN

  let sqsExist = true;
  try {
    expectCDK(stack).to(haveResourceLike("AWS::SQS::Queue"));
  } catch (error) {
    sqsExist = false; //SQS doesn't exist if haveResourceLike throws an error
  }

  if (sqsExist) {
    expectCDK(stack).to(haveResourceLike("AWS::SQS::Queue", {
      VisibilityTimeout: 300
    }));
  } else {
    console.warn('Resource does not exist but we pass them anyway');
  }
});


```
