### ISSUE TITLE
(dynamodb): CfnGlobalTableProps missing pointInTimeRecoverySpecification

### ISSUE THREAD

**Issue by dontirun** [aws/aws-cdk#15183]
GlobalTables have a [point in time recovery](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-dynamodb-globaltable-pointintimerecoveryspecification.html) property which is missing from the CfnGlobalTableProps

### Environment

  - **Framework Version:** 1.108.1
  - **Language (Version):** all 

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hey @dontirun ,

thanks for opening the issue. The documentation that you pointed to is for the type. However, there doesn't seem to be a property yet on the [`AWS::DynamoDB::GlobalTable` resource](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-globaltable.html) that uses that type:

```json
{
  "Type" : "AWS::DynamoDB::GlobalTable",
  "Properties" : {
      "AttributeDefinitions" : [ AttributeDefinition, ... ],
      "BillingMode" : String,
      "GlobalSecondaryIndexes" : [ GlobalSecondaryIndex, ... ],
      "KeySchema" : [ KeySchema, ... ],
      "LocalSecondaryIndexes" : [ LocalSecondaryIndex, ... ],
      "Replicas" : [ ReplicaSpecification, ... ],
      "SSESpecification" : SSESpecification,
      "StreamSpecification" : StreamSpecification,
      "TableName" : String,
      "TimeToLiveSpecification" : TimeToLiveSpecification,
      "WriteProvisionedThroughputSettings" : WriteProvisionedThroughputSettings
    }
}
```

So, pretty sure the DynamoDB support for this feature is still not done yet 🙂.

Thanks,
Adam

**Comment by dontirun** [comment]
My mistake! Looks like there is nothing to be done then.
