### ISSUE TITLE
(@aws-cdk/aws-s3-deployment): BucketDeployment Prune function does not align with aws s3 sync --delete

### ISSUE THREAD

**Issue by iDVB** [aws/aws-cdk#15182]
BucketDeployment Prune is based off only the filtered assets and not the local directory.

### Reproduction Steps
Compare...
**A:**
```javascript
new BucketDeployment(this, 'BucketDeployment', {
  sources: [Source.asset('./local', { exclude: ['!*.html'] })],
  destinationBucket: bucket,
  prune: true,
});
```
and
**B:**
```bash
aws s3 sync /local s3://mybucket include *.html --delete
```

In example **A** only **html files** would get pruned/deleted if orphan.
However, in example **B** ALL FILES not in `/local` will be deleted.

### What did you expect to happen?
I think the intension is for prune to function the same as does the CLI's `--delete` and it should be based off the files in the source folder and not just the filtered files.

**OR**

If you could specify `cache-control` settings per `source` of files in a single deploy it would work as well.
This would allow the `prune` to encompass the whole deploy, while still being able to have specific `cache-control` settings.

Likely if this was possible, all settings changes should be optional to move to the source level vs the deployment level.
```javascript
new BucketDeployment(this, 'BucketDeployment', {
  sources: [
    s3deploy.Source.asset(props.siteAssetsPath, {
      ignoreMode: cdk.IgnoreMode.GIT,
      exclude: [
        '*.*',
        '!*.html',
        '!page-data/**/*.json',
        '!sw.js',
        '!robots.txt',
        '!sitemap/**',
        '!_redirects',
      ],
      cacheControl: [s3deploy.CacheControl.fromString('public,max-age=31536000,immutable')],
    }),
    s3deploy.Source.asset(props.siteAssetsPath, {
      ignoreMode: cdk.IgnoreMode.GIT,
      exclude: [
        '*.*',
        '!*.html',
        '!page-data/**/*.json',
        '!sw.js',
        '!robots.txt',
        '!sitemap/**',
        '!_redirects',
      ],
      cacheControl: [s3deploy.CacheControl.fromString('public,max-age=0,must-revalidate')],
    }),
    s3deploy.Source.asset(props.siteAssetsPath, {
      ignoreMode: cdk.IgnoreMode.GIT,
      exclude: [
        '*.*',
        '!*.html',
        '!page-data/**/*.json',
        '!sw.js',
        '!robots.txt',
        '!sitemap/**',
        '!_redirects',
      ],
    }),
  ],
  memoryLimit: 512,
  destinationBucket: bucket,
  prune: true,
});
```

### Rational
This issue limits the ability for people to migrate from AWS CLI s3 asset deployment over to CDK `aws-s3-deployment` if their deployments require targeting specific assets with specific options. In our case this is `cache-control` settings.

Many SPA frontend frameworks have very specific `cache control` settings, like with [gatsbyjs](https://www.gatsbyjs.com/docs/caching/).

I can only seem to get it to work on FIRST upload if I use..
- [3x deployments](https://gist.github.com/iDVB/fbcf30de3ff37e9a450824cf679b9e54#file-staticsite-ts-L1-L52)
- order the deployments [with deps](https://gist.github.com/iDVB/fbcf30de3ff37e9a450824cf679b9e54#file-staticsite-ts-L54-L56)
- prune only on [first deploy](https://gist.github.com/iDVB/fbcf30de3ff37e9a450824cf679b9e54#file-staticsite-ts-L11)

However, on proceeding deploys, if you change a file name (or delete file) that impacts only say the 2nd deployment package, then you will have the old file(s) as an orphan. 

That and there seems to be no way to have 1x single deployment that handles multiple sources “and their associated cache control settings” which if that were possible, it could have `prune:true` and it would work the charm.

### Other things I’ve half-baked-considered
- running aws `s3 cp bucket bucket` to retroactively update cache control settings.
    - many challenges here…
    - time consuming looping throw assets twice
    - can’t be built into a Construct (unless rewriting the deploy construct) since it would need to have the target bucket already deployed/created.
- using programmatic CDK deploy and using `execSync` to upload the assets AFTER CDK deploys.

--- 

This is :bug: Bug Report

**Comment by otaviomacedo** [comment]
Yes, it makes sense for prune to apply to the whole folder contents and not the filter results.

I am unassigning and marking this issue as `p2`, which means that we are unable to work on this immediately.

We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://join.slack.com/t/cdk-dev/shared_invite/zt-mso6p56d-qJp7SOTBvMaQuDrx7R2wHg) to solicit support for reprioritization.
