### ISSUE TITLE
(elasticsearch): Domain.fromDomainAttributes gives "Invalid URL" when endpoint is a token

### ISSUE THREAD

**Issue by HelioStrike** [aws/aws-cdk#15188]
I'm getting a `Invalid URL` when trying to use `Domain.fromDomainAttributes` with a CfnDomain object. The CfnDomain object was retrieved from a CfnInclude object. Here's the snippet of code that's failing for me.

```
private getDomainFromTemplate(name: string, cfnTemplate: CfnInclude): IDomain {
    const cfnDomain = cfnTemplate.getResource(name) as CfnDomain;
    return Domain.fromDomainAttributes(this, name, {domainArn: cfnDomain.attrArn, domainEndpoint: cfnDomain.attrDomainEndpoint});
}
```

### Reproduction Steps

Here's some minimal code that causes the bug.
```
import * as elasticsearch from '@aws-cdk/aws-elasticsearch';

const domain = new elasticsearch.CfnDomain(this, "domain", {
    domainName: "domainName"
});
elasticsearch.Domain.fromDomainAttributes(this, name, {domainArn: domain.attrArn, domainEndpoint: domain.attrDomainEndpoint});
```

### What did you expect to happen?

The error shouldn't happen and the Domain object should be successfully created.

### What actually happened?

```
internal/url.js:257
  throw new ERR_INVALID_URL(input);
  ^

TypeError [ERR_INVALID_URL]: Invalid URL: ${Token[TOKEN.1766]}
    at onParseError (internal/url.js:257:9)
    at new URL (internal/url.js:333:5)
    at extractNameFromEndpoint (/Users/saimuty/workplace/dr_infra/src/JuryDisputeResolutionNAWSCDK/node_modules/monocdk/lib/aws-elasticsearch/lib/domain.js:946:26)
    at Function.fromDomainAttributes (/Users/saimuty/workplace/dr_infra/src/JuryDisputeResolutionNAWSCDK/node_modules/monocdk/lib/aws-elasticsearch/lib/domain.js:903:28)
```

### Environment

  - **CDK CLI Version  :** 1.107.0 (build 52c4434)
  - **Framework Version:** 1.107.0 (build 52c4434)
  - **Node.js Version:** v12.21.0
  - **OS               :** MacOS Big Sur 11.4
  - **Language (Version):** Typescript (4.0.5)

--- 

This is :bug: Bug Report

**Comment by BenChaimberg** [comment]
We should extract the domain name from the ARN instead of the endpoint, if it's available. Change required here: https://github.com/aws/aws-cdk/blob/7c5b2aa4854d24535693e1ceefa7e7fb38313887/packages/%40aws-cdk/aws-elasticsearch/lib/domain.ts#L1214 to use [`Stack.parseArn`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.Stack.html#parsewbrarnarn-sepiftoken-hasname).

@HelioStrike if you create a PR for this fix, please feel free to request my review
