### ISSUE TITLE
v1.109.0 CLI cuts off step progress and outputs misleading "Failed resources:" message

### ISSUE THREAD

**Issue by severn-everett** [aws/aws-cdk#15196]
When deploying an AWS stack using v1.109.0 the CLI...

- Outputs "Failed resources:" message even if all resources were deployed successfully.
- Does not print finished progress of every step.

### Reproduction Steps
Upgrade from 1.108.1 to 1.109.0.

### What did you expect to happen?
AWS stacks should deploy as they did before.

```shell
CDK_NEW_BOOTSTRAP set, using new-style bootstrapping
 ⏳  Bootstrapping environment aws://##########/eu-west-1...
Trusted accounts for deployment: (none)
Trusted accounts for lookup: (none)
Using default execution policy of 'arn:aws:iam::aws:policy/AdministratorAccess'. Pass '--cloudformation-execution-policies' to customize.
AN_AWS_STACK: creating CloudFormation changeset...
 0/4 | 15:13:48 | UPDATE_IN_PROGRESS   | AWS::CloudFormation::Stack | AN_AWS_STACK User Initiated
 0/4 | 15:13:54 | UPDATE_IN_PROGRESS   | AWS::IAM::Role        | FilePublishingRole
 0/4 | 15:13:54 | UPDATE_IN_PROGRESS   | AWS::IAM::Role        | ImagePublishingRole
 0/4 | 15:13:55 | UPDATE_IN_PROGRESS   | AWS::IAM::Role        | DeploymentActionRole
 3/4 | 15:14:10 | UPDATE_COMPLETE      | AWS::IAM::Role        | ImagePublishingRole
 3/4 | 15:14:10 | UPDATE_COMPLETE      | AWS::IAM::Role        | FilePublishingRole
 3/4 | 15:14:10 | UPDATE_COMPLETE      | AWS::IAM::Role        | DeploymentActionRole
 4/4 | 15:14:15 | UPDATE_COMPLETE_CLEA | AWS::CloudFormation::Stack | AN_AWS_STACK
 4/4 | 15:14:15 | UPDATE_COMPLETE      | AWS::CloudFormation::Stack | AN_AWS_STACK
 ✅  Environment aws://##########/eu-west-1 bootstrapped.
 ```

### What actually happened?
The stack deployment fails to clean up, although the stack itself does get deployed.

```shell
CDK_NEW_BOOTSTRAP set, using new-style bootstrapping
 ⏳  Bootstrapping environment aws://##########/eu-west-1...
Trusted accounts for deployment: (none)
Trusted accounts for lookup: (none)
Using default execution policy of 'arn:aws:iam::aws:policy/AdministratorAccess'. Pass '--cloudformation-execution-policies' to customize.
AN_AWS_STACK: creating CloudFormation changeset...
  0/4 |15:20:04 | UPDATE_IN_PROGRESS   | AWS::CloudFormation::Stack | AN_AWS_STACK User Initiated
  0/4 |15:20:11 | UPDATE_IN_PROGRESS   | AWS::IAM::Role        | DeploymentActionRole
  0/4 |15:20:11 | UPDATE_IN_PROGRESS   | AWS::IAM::Role        | FilePublishingRole
  0/4 |15:20:11 | UPDATE_IN_PROGRESS   | AWS::IAM::Role        | ImagePublishingRole
  3/4 |15:20:28 | UPDATE_COMPLETE      | AWS::IAM::Role        | FilePublishingRole
  3/4 |15:20:28 | UPDATE_COMPLETE      | AWS::IAM::Role        | ImagePublishingRole
  3/4 |15:20:28 | UPDATE_COMPLETE      | AWS::IAM::Role        | DeploymentActionRole

Failed resources:
 ✅  Environment aws://##########/eu-west-1 bootstrapped.
 ```

_Notice that step 4/4 did not print._

### Environment

  - **CDK CLI Version  :1.109.0
  - **Framework Version:1.109.0
  - **Node.js Version:** 14.17.0
  - **OS               :Windows 10
  - **Language (Version):** 4.3.2

### Other

--- 

This is :bug: Bug Report

**Comment by ryparker** [comment]
Hello @severn-everett :wave:

After investigating this CLI output it looks to be a little misleading. The CLI will always output `Failed resources:` even when there are no failed deployments (see implementation). As long as all resources listed have the green checkmark emoji (`✅`)  this means that all resources succeeded. 

You should be able to see that the stack was successfully deployed via the AWS console.

**Comment by severn-everett** [comment]
What about the cleanup step (4/4)? That output has disappeared in the deployments using 1.109.0 as well.

**Comment by ryparker** [comment]
I missed that bug, sorry about that. I opened a [PR](https://github.com/aws/aws-cdk/pull/15207) to fix the misleading `Failed resources:` message but will need to dedicate more time into investigating the cutoff of step progress output.

I am marking this issue as p1 due to the number of users that will be impacted. It has been prioritized as important and should see attention soon. We use +1s to help us prioritize our work.

**Comment by ryparker** [comment]
Fix for both issues has been implemented in https://github.com/aws/aws-cdk/pull/15207
