### ISSUE TITLE
Toolkit: add a `compile` option which will build the code before executing any cx command 

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#152]
We could add to `cdk.json`:

```json
{
  "build": "tsc",
  "watch": "tsc -w"
}
```

Which will automatically invoke the compiler before executing any cx commands. The downside is that the compiler is normally quite slow so the current common practice is to use some "watching" compiler ("tsc -w" or "jsii -w") in order to incrementally compile the project as you iterate.

Also, cdk-init for the various languages should include build steps in their `cdk.json`.

**Comment by rix0rrr** [comment]
I would have liked this a couple of times already.
