### ISSUE TITLE
(lambda-layer-kubectl): local pack skipped because package.json contains invalid value for "private" key

### ISSUE THREAD

**Issue by BenChaimberg** [aws/aws-cdk#15203]
Running `./foreach.sh --up yarn run package` for @aws-cdk/aws-eks fails with error:
> /tmp/npm-packChkI8a/Amazon.CDK.AWS.EKS/Amazon.CDK.AWS.EKS.csproj : error NU1102: Unable to find package Amazon.CDK.LambdaLayer.Kubectl with version (= 0.0.0) [/tmp/npm-packChkI8a/JsiiBuild.sln]

This is because, earlier in the tree traversal, the packaging for lambda-layer-kubectl was skipped with message:
> No packaging for private modules.

This is due to [the "private" entry in package.json](https://github.com/aws/aws-cdk/blob/7c5b2aa4854d24535693e1ceefa7e7fb38313887/packages/%40aws-cdk/lambda-layer-kubectl/package.json#L3) in lambda-layer-kubectl being set to `false`. When `yarn run package` calls `cdk-package`, [we skip packaging](https://github.com/aws/aws-cdk/blob/7c5b2aa4854d24535693e1ceefa7e7fb38313887/tools/cdk-build-tools/bin/cdk-package.ts#L30-L34) because we expect the "private" entry to be missing if the package is not private.

This issue does not occur during our CI packing because pack.sh calls jsii-pacmak directly on jsii modules, as opposed to calling cdk-package.

--- 

This is :bug: Bug Report

**Comment by BenChaimberg** [comment]
cc @dillon-odonovan

**Comment by eladb** [comment]
I think this is the culprit:

https://github.com/aws/aws-cdk/blob/7c5b2aa4854d24535693e1ceefa7e7fb38313887/tools/cdk-build-tools/lib/package-info.ts#L45

We need to change this logic to:

```ts
return currentPackageJson().private;
```

**Comment by eladb** [comment]
@BenChaimberg I am assigning back to you. You should pick this up :-D
