### ISSUE TITLE
[Route53]: CrossAccountZoneDelegationRecord should support RemovalPolicy

### ISSUE THREAD

**Issue by epheat** [aws/aws-cdk#15211]
[CrossAccountZoneDelegationRecord](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-route53.CrossAccountZoneDelegationRecord.html#towbrstring) currently does not support the application of a RemovalPolicy. When the resource is deleted, it will assume the DelegationRole and issue a ChangeResourceRecordSets call with action DELETE. In our case, we would rather leave the delegation intact (at least in production-like environments) so we don't risk tearing down our endpoints accidentally.

### Use Case
We would like to apply a removal policy of RETAIN on the CrossAccountZoneDelegationRecord resource, in order to protect against accidental deletion of the resource.

### Proposed Solution

```typescript
let hostedZone = new HostedZone(this, 'HostedZone', {
  zoneName: 'my.cool.zone'
});

let delegation = new CrossAccountZoneDelegationRecord(this, 'CrossAccountDelegation', {
  delegatedZone: hostedZone,
  parentHostedZoneName: 'cool.zone',
  delegationRole: Role.fromRoleArn(this, 'DelegationRole', 'arn:aws:iam::000000000000:role/delegator')
});

// vvv NEW vvv
delegation.applyRemovalPolicy(RemovalPolicy.RETAIN);

```

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by epheat** [comment]
Alternatively, the CrossAccountZoneDelegationRecord could somehow inherit the RemovalPolicy from the HostedZone that it delegates to. It would be an antipattern to have a HostedZone with RemovalPolicy.DESTROY, meanwhile a Delegation with RemovalPolicy.RETAIN, since that would leave you with a dangling delegation.

**Comment by njlynch** [comment]
Agreed that this construct should expose a removalPolicy, and potentially default to the removal policy of the delegatedZone. 

I've tagged it as P1, which means it should be on our near-term roadmap.

We welcome community contributions! If you are able, we encourage you to [contribute](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) a bug fix or new feature to the CDK. If you decide to contribute, please start an engineering discussion in this issue to ensure there is a commonly understood design before submitting code. This will minimize the number of review cycles and get your code merged faster.
