### ISSUE TITLE
(aws_codestarnotifications): props.source.bindAsNotificationRuleSource is not a function

### ISSUE THREAD

**Issue by n0ts** [aws/aws-cdk#15212]
I use example code for codestarnotifications.
https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_codestarnotifications/README.html

But I failed that set notification for codebuild.

### Reproduction Steps

```
project = codebuild.PipelineProject(stack, "MyProject")
topic = sns.Topic(stack, "MyTopic1")
...
rule = notifications.NotificationRule(stack, "NotificationRule",
    source=project,
    events=["codebuild-project-build-state-succeeded", "codebuild-project-build-state-failed"
    ],
    targets=[topic]
)
rule.add_target(slack)
```

### What did you expect to happen?

Successfully Notification configuration for CodeBuild.

### What actually happened?

I got a below error.

```
jsii.errors.JavaScriptError: 
  TypeError: props.source.bindAsNotificationRuleSource is not a function

...

jsii.errors.JSIIError: props.source.bindAsNotificationRuleSource is not a function
```

### Environment

  - **CDK CLI Version  :** 1.109.0 (build c647e38)
  - **Framework Version:** 1.109.0
  - **Node.js Version:**  v14.15.4
  - **OS               :** macOS 10.15.7
  - **Language (Version):** Python 3.8.0

### Other

--- 

This is :bug: Bug Report

**Comment by luckily** [comment]
Hi @n0ts ,
My environment is similar to you, but it's works for me.

Something like this:
```python
from aws_cdk import core as cdk
import aws_cdk.aws_codestarnotifications as notifications
import aws_cdk.aws_codebuild as codebuild
import aws_cdk.aws_sns as sns

class AwsCdkPythonTestStack(cdk.Stack):
    def __init__(self, scope: cdk.Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)
        project = codebuild.PipelineProject(self, "MyProject")
        topic = sns.Topic(self, "MyTopic1")
        notifications.NotificationRule(self, "NotificationRule",
            source=project,
            events=["codebuild-project-build-state-succeeded", "codebuild-project-build-state-failed"
            ],
            targets=[topic]
        )

```

And `install_requires` parameter in `setup.py`
```python
    install_requires=[
        "aws-cdk.core==1.109.0",
        "aws_cdk.aws_codestarnotifications==1.109.0",
        "aws_cdk.aws_codebuild==1.109.0",
        "aws_cdk.aws_sns==1.109.0",
        "aws_cdk.aws_chatbot===1.109.0",
    ],
```

**Comment by skinny85** [comment]
Hey @n0ts,

can you show the output of `pip list` in your project?

Thanks,
Adam

**Comment by n0ts** [comment]
@skinny85 @luckily 
Thanks for your comment.

aws-cdk.aws-codestarnotifications is not installed my local machine.
I install aws-cdk.aws-codestarnotifications, It's worked!
