### ISSUE TITLE
cli: passing a --region param should be treated as an unknown flag

### ISSUE THREAD

**Issue by carlsborg** [aws/aws-cdk#15218]
### The Question

cdk deploy happily takes a --region flag but ignores it. given the region is picked up from the env var or the hard coded env, the cli should print a message about an unknown argument  and exit.

### Environment

  - **CDK CLI Version:** 1.109.0 (build c647e38)
  - **Module Version:** 
  - **Node.js Version:** v14.15.4
  - **OS:** Ubuntu
  -   **Language (Version):** Python 3.8.5

**Comment by rix0rrr** [comment]
In fact CDK CLI will take `--any --argument` and ignore it if it's unknown.

I agree with you that it's poor behavior. At the same time, it's hard to change this now for fear of breaking existing users who mistyped arguments but the CLI happily keeps on trucking. They will feel like we broke them if their scripts suddenly fail.

I would accept a PR that adds strict command line validation in case the CLI is running as v2 though.
