### ISSUE TITLE
Glue: Table construct insists on having columns even with partition keys present

### ISSUE THREAD

**Issue by wolfadr** [aws/aws-cdk#15214]
I wish to create a table definition that contains only partition keys and no other columns. These are to be discovered later by a Glue Crawler. However, the `Table` construct doesn't allow me to do that. CDK responds with either a type error, if I omit the `columns` property or with the error _"you must specify at least one column for the table"_, if I give it an empty array.

If I construct the same table using `CfnTable` (see below, section "Other") or using CloudFormation directly, it works just fine.

#### 1. Create CDK App with the following content:

```typescript
import { App, Construct, Stack } from '@aws-cdk/core';
import { Bucket } from '@aws-cdk/aws-s3';
import { Database, DataFormat, Schema, Table } from '@aws-cdk/aws-glue';

const app = new App();

export class MinimalGlueTableStack extends Stack {
  constructor(scope: Construct, id: string) {
    super(scope, id);

    const bucket = new Bucket(this, 'Bucket');

    const database = new Database(this, 'Database', {
      databaseName: 'glue-db',
    });

    new Table(this, 'Table', {
      database: database,
      tableName: 'glue-table',
      bucket: bucket,
      s3Prefix: 'data',
      partitionKeys: [
        { name: 'year', type: Schema.INTEGER },
        { name: 'month', type: Schema.INTEGER },
        { name: 'day', type: Schema.INTEGER },
      ],
      columns: [],  // omitting this property leads to a type error
      dataFormat: DataFormat.PARQUET,
      storedAsSubDirectories: false,
      compressed: true,
    });
  }
}

new MinimalGlueTableStack(app, 'GlueTableNotWorking');

app.synth();
```

#### 2. Run `cdk synth`

Getting the error:
```console
Error: you must specify at least one column for the table
```

or a type error, if I omit the `columns` property completely.

### What did you expect to happen?

I expected to have the Glue Table created with only the partition keys present as columns.

### What actually happened?

It gave me an error as described above.

### Environment

  - **CDK CLI Version  :** 1.108.1
  - **Framework Version:** 1.109.0
  - **Node.js Version:** 15.14.0
  - **OS               :** WSL2 Ubuntu on Windows 10
  - **Language (Version):** TypeScript (4.3.2)

### Other

If I write the same stack using `CfnTable`, having no additional columns other than my partition keys works just fine. To reproduce:

```typescript
import { App, Construct, Stack } from '@aws-cdk/core';
import { Bucket } from '@aws-cdk/aws-s3';
import { CfnTable, Database } from '@aws-cdk/aws-glue';

const app = new App();

export class MinimalGlueTableStack extends Stack {
  constructor(scope: Construct, id: string) {
    super(scope, id);

    const bucket = new Bucket(this, 'Bucket');

    const database = new Database(this, 'Database', {
      databaseName: 'glue-db',
    });

    new CfnTable(this, 'Table', {
      catalogId: this.account,
      databaseName: database.databaseName,
      tableInput: {
        name: 'glue-table',
        tableType: 'EXTERNAL_TABLE',
        parameters: {
          classification: 'parquet',
          has_encrypted_data: false,
        },
        partitionKeys: [
          { name: 'year', type: 'int' },
          { name: 'month', type: 'int' },
          { name: 'day', type: 'int' },
        ],
        storageDescriptor: {
          location: `s3://${bucket.bucketName}/data`,
          inputFormat: 'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat',
          outputFormat: 'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat',
          serdeInfo: {
            serializationLibrary: 'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe'
          },
          compressed: true,
          storedAsSubDirectories: false
        },
      },
    });
  }
}

new MinimalGlueTableStack(app, 'GlueTableWorkingFine');

app.synth();
```

--- 

This is :bug: Bug Report

**Comment by BenChaimberg** [comment]
Sorry for all of the back in forth with the labeling. We should definitely allow this to happen, as long as `partitionKeys` are supplied. To fix this, we will need to change the following line to only throw if `partitionKeys` were not supplied or are also empty.
https://github.com/aws/aws-cdk/blob/440ca35cf0f0e9f6f86bef445bd9aa6ef05ff9be/packages/%40aws-cdk/aws-glue/lib/table.ts#L342

I am unassigning myself and marking this issue as `p2`, which means that we are unable to work on this immediately.

We use +1s to help prioritize our work, and are happy to reevaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://join.slack.com/t/cdk-dev/shared_invite/zt-mso6p56d-qJp7SOTBvMaQuDrx7R2wHg) to solicit support for reprioritization.

Please feel free to work on this issue yourself and request my review if you submit a PR! See [CONTRIBUTING.md](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) for guidelines.
