### ISSUE TITLE
(aws-ec2): Allow selecting subnets by Id or CIDR mask

### ISSUE THREAD

**Issue by ABevier** [aws/aws-cdk#15228]
I would like the ability to create a SubnetSelection based on the exact subnet ids or based or the CIDR range of subnets in a VPC.  While `SubnetSelection` does allow specifying a list of explicit subnets to use, these use cases are probably common enough support first class without requiring a "custom" filter.

### Use Case

I would like this feature because some of the VPC's I'm using have multiple public and private subnets with different CIDR masks and the current subnet selection capability forces me to write my own filters on the list of `ISubnets` in the vpc and then pass them explicitly to the `SubnetSelection`. 
 
### Proposed Solution

Ideally I would like to do something like this:

```
    const vpc = Vpc.fromLookup(this, "Vpc", {
      vpcId: props.vpcId,
    });

    const subnetsById: SubnetSelection = {
      subnetFilters: [SubnetFilter.byId('subnet-abc', 'subnet-efg', 'subnet-hij')]
    }
```

or something like this:

```
    const vpc = Vpc.fromLookup(this, "Vpc", {
      vpcId: props.vpcId,
    });

    const subnetsByCidr: SubnetSelection = {
      subnetFilters: [SubnetFilter.withCidrMask('26')]
    }
```
* [x] :wave: I may be able to implement this feature request

---

This is a :rocket: Feature Request

**Comment by njlynch** [comment]
Thanks for the feature request -- and to those who've already :+1: it.

Just so I understand the use case, this is functionality equivalent to using [`SubnetSelection.subnets`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ec2.SubnetSelection.html#subnets), with the main difference being that you're selecting by subnet IDs, rather than `ISubnet`s. Is that correct?

The quick (untested) version (as the intermediate workaround) looks like this:

```ts
class SubnetIdSubnetFilter extends SubnetFilter {
  constructor(private readonly subnetIds: string[]) {  }
  public selectSubnets(subnets: ISubnet[]): ISubnet[] {
    return subnets.filter(s => this.subnetIds.includes(s.subnetId));
  }
}
const subnetsById: SubnetSelection = {
  subnetFilters: [new SubnetIdSubnetFilter('subnet-abc', 'subnet-efg', 'subnet-hij')]
}
```

**Comment by ABevier** [comment]
Yup, your understanding is correct.  It would be nice to make the more common filtering use cases part of the library itself instead of us building our own custom filters.

This is what we've typically been doing:
```
        const subnetIds = ['subnet-abc, 'subnet-efg, 'subnet-hij'];
        const subnets = subnetIds.map(subnetId => Subnet.fromSubnetId(this, subnetId, subnetId));
        const subnetSelection = { subnets }
```
