### ISSUE TITLE
aws_lambda AssetImageCodeProps :  I need to pass arguments to docker build

### ISSUE THREAD

**Issue by sebsto** [aws/aws-cdk#15226]
I would like to pass additional arguments to the docker build command, such as "--tag" and "--volume" 
Tag will make developer life easier to track all docker images on their machines 
Volume will allow to speed up build process when having many dependencies. 

### Use Case

Currently the `buildArgs` property only allows to pass value to `docker build --build-args`
It is not possible to pass arbitrary command line options to the `docker build`command.

Currently, each tiny Lambda function code change triggers a full rebuild of my Lambda function, because the build is done inside the containers layer.  Having the possibility to specify my own volume mapping to my local filesystem will allow containers to reuse my build directory and to not download all my dependencies at each build. It will allow to recompile only the files that changed since last build.  This would allow to reduce my build time from ~10 minutes to seconds.

### Proposed Solution

Add a property of type [string:string] that would allow to pass any command line flag to the `docker build`command

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by nija-at** [comment]
@eladb - as far as I can tell, this feature is not available as part of docker assets in the cdk. Is this a feature request for docker assets?

**Comment by eladb** [comment]
Sounds like a useful feature. Contributions are welcome.
