### ISSUE TITLE
(aws_s3): Is there a way to apply s3 replication rule on existing bucket ?

### ISSUE THREAD

**Issue by krishansubudhi** [aws/aws-cdk#15221]
I am trying to apply s3 replication rule using existing s3 bucket(which is not created using cdk).

```
class HelloCdkStack(cdk.Stack):

    def __init__(self, scope: cdk.Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)


        self.replication_conf = s3.CfnBucket.ReplicationConfigurationProperty(
            role = 'arn:aws:iam::*******:role/service-role/s3crr_role_for_bucket',
            rules=[
                s3.CfnBucket.ReplicationRuleProperty(
                    id='rule-replicate-all-data',
                    destination=s3.CfnBucket.ReplicationDestinationProperty(
                        bucket= 'arn:aws:s3::*****:testreplication-1'),
                    status="Enabled",
                )
            ]
        )
        s3.CfnBucket(
            self,
            'test',
            bucket_name= 'source_bucket',
            versioning_configuration = s3.CfnBucket.VersioningConfigurationProperty(
                status='Enabled'
            ),
            replication_configuration=self.replication_conf
        )
```

Here my source_bucket already exists. Is there a way to pass already existing bucket instead of creating a new one ?

**Comment by peterwoodworth** [comment]
Hey @krishansubudhi,

Couple things here. You say that your `source_bucket` exists but the code you just gave _is_ creating a new bucket. If you want to use the [`Bucket.fromBucketAttributes` function](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-s3.Bucket.html#static-fromwbrbucketwbrattributesscope-id-attrs)

However, once you have that imported bucket [you cannot modify the imported resource.](https://docs.aws.amazon.com/cdk/latest/guide/resources.html#resources_importing) So you won't be able to apply a replication rule on an existing bucket.

Let me know if you have additional concerns 😄
