### ISSUE TITLE
(aws-stepfunctions-tasks): Set StepConcurrencyLevel when creating EMR clusters through Step Functions

### ISSUE THREAD

**Issue by MousaZeidBaker** [aws/aws-cdk#15223]
How do one specify the `StepConcurrencyLevel` parameter when creating EMR clusters through Step Functions?

The following can be found in the [AWS Step Functions docs](https://docs.aws.amazon.com/step-functions/latest/dg/connect-emr.html)
> As of emr-5.28.0, you can specify the parameter StepConcurrencyLevel when creating a cluster to allow multiple steps to run in parallel on a single cluster.

... but there is nothing about step concurrency level in the CDK Step Functions Task [EmrCreateCluster docs](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-stepfunctions-tasks.EmrCreateCluster.html) 

### Environment

  - **CDK CLI Version:** 1.100.0
  - **Module Version:** 1.100.0
  - **Node.js Version:** v14.15.0
  - **OS:** Ubuntu 20.04.2 LTS
  - **Language (Version):** Python (3.8.5)

**Comment by peterwoodworth** [comment]
This currently isn't possible. When you use the `EmrCreateCluster` construct, the CDK will create a new Emr Cluster here: https://github.com/aws/aws-cdk/blob/c647e389bd279b34e91110c9418885fe904739c3/packages/%40aws-cdk/aws-stepfunctions-tasks/lib/emr/emr-create-cluster.ts#L235-L259
Note how there is no `StepConcurrencyLevel` prop set here.
However, the [`StepConcurrencyLevel` is on `CfnCluster`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-emr.CfnCluster.html#stepconcurrencylevel), so this is currently supported by CloudFormation. So this shouldn't be a very difficult feature to implement 😄
