### ISSUE TITLE
(ec2): Add rds-data VPC interface endpoints 

### ISSUE THREAD

**Issue by neilferreira** [aws/aws-cdk#15239]
Add `rds-data` VPC interface endpoints

### Use Case

VPC interface endpoints are supported for `rds-data` but don't exist in CDK:

https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/vpc-interface-endpoints.html

### Proposed Solution

Add support for `rds-data` VPC interface endpoints

### Other

Temporary workaround:
```
vpc.addInterfaceEndpoint("rds-data", {
      service: {
        name: `com.amazonaws.${process.env.CDK_DEFAULT_REGION}.rds-data`,
        port: 443,
      },
```

I "presume" the implementation would be:

https://github.com/aws/aws-cdk/blob/7966f8d48c4bff26beb22856d289f9d0c7e7081d/packages/%40aws-cdk/aws-ec2/lib/vpc-endpoint.ts#L290

```
public static readonly RDS_DATA = new InterfaceVpcEndpointAwsService('rds-data');
```

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by neilferreira** [comment]
ref: https://aws.amazon.com/about-aws/whats-new/2020/02/amazon-rds-data-api-now-supports-aws-privatelink/

**Comment by owenashurst** [comment]
+1

Just about to create an issue myself about this. This needs implementing.
