### ISSUE TITLE
(stepfunctions-tasks): emr-containers CreateVirtualCluster, DeleteVirtualCluster, and StartJobRun task

### ISSUE THREAD

**Issue by matthewsvu** [aws/aws-cdk#15234]
EMR on EKS (emr-containers) integration has been introduced in Step Functions for a few months now, CDK support has been held off until recently till I took up the issue.

### Use Case

To use Step Function's integrations with EMR on EKS on CDK, it's been on the backlog for quite a bit.
https://docs.aws.amazon.com/step-functions/latest/dg/connect-emr-eks.html

### Proposed Solution

The implementation would be like the other service integrations from ``step-functions-tasks``
[like so](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-stepfunctions-tasks-readme.html#tasks-for-aws-step-functions). The api properties are defined in [here](https://docs.aws.amazon.com/step-functions/latest/dg/connect-emr-eks.html)

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by BenChaimberg** [comment]
Thanks for opening this! When you have thought about your design more, please open a PR that contains the user-facing API (essentially the props that will be passed in to each of the tasks). We should discuss this first before diving into the implementation.

**Comment by wojtekwalczak** [comment]
Hi, I needed `StartJobRun` functionality this week, so I implemented it [in the following way](https://github.com/wojtekwalczak/aws-cdk/commit/2d153c70a3b9ea533c69754ec9bf74f761d3a03e).

I think I could give it a shot and implement full `emr-containers` API for `stepfunctions-tasks`, but before I do so, could you take a look at the code under the link above and let me know if my approach is OK for you?

**Comment by matthewsvu** [comment]
> Hi, I needed `StartJobRun` functionality this week, so I implemented it [in the following way](https://github.com/wojtekwalczak/aws-cdk/commit/2d153c70a3b9ea533c69754ec9bf74f761d3a03e).
> 
> I think I could give it a shot and implement full `emr-containers` API for `stepfunctions-tasks`, but before I do so, could you take a look at the code under the link above and let me know if my approach is OK for you?

Upon initial glance your approach looks fine, however the implementation on my #15262 PR only has a few unit tests and integration tests left before full completion. There is a lot of stuff to dig through on that PR post. I would also run it by @BenChaimberg to see what he thinks.
