### ISSUE TITLE
(codepipeline): AccessDeniedException when calling the PutJobSuccessResult

### ISSUE THREAD

**Issue by warden** [aws/aws-cdk#15235]
This is likely to be a guidance question, but I'm not sure I'm not hitting some CodePipeline limitation. I have a scenario like this:

1. I have a devops central IAM account that I have the pipelines
1. in that pipeline I am invoking a lambda, that uses a PipelineRole on a cross-IAM another target IAM account
1. that Lambda executes some operations (e.g. CloudFront)

Those three things work fine, but... the Lambda must return a result to the initial IAM account to the CodePipeline and that is what doesn't work for me.
I tried assigning even full permissions for `codepipeline:*` for `*` resources on both sides, but I am still getting the error:
```
[ERROR] ClientError: An error occurred (AccessDeniedException) when calling the PutJobSuccessResult operation: User: arn:aws:sts::1234:assumed-role/PipelineRole/1624294113598 is not authorized to perform: codepipeline:PutJobSuccessResult
```

In the Python Lambda, I am executing the CloudFront operations with the assumed role passed from the CodePipeline `role: ` parameter in a standard way:
```
cloudfront_client = boto3.client('cloudfront')
```

Then, for returning the result, I use Session token like this:
```
    key_id = job_data['artifactCredentials']['accessKeyId']
    key_secret = job_data['artifactCredentials']['secretAccessKey']
    session_token = job_data['artifactCredentials']['sessionToken']

    session = Session(aws_access_key_id=key_id,
                      aws_secret_access_key=key_secret,
                      aws_session_token=session_token)
    return session.client('codepipeline', config=botocore.client.Config(signature_version='s3v4'))

```

Am I missing something or maybe the artifactCredentials do not allow it? If that's the case, how can I pass the result of Lambda from the target account to the original account?
Thanks a lot in advance for support, I already spent 2 days trying to figure this out and I'm banging the wall it seems...

**Comment by skinny85** [comment]
Hey @warden ,

thanks for opening the issue. I think this might not work, because you would need to give the Lambda's execution Role in the other account permissions to `codepipeline:PutJobSuccessResult` and `codepipeline:PutJobFailureResult` in your pipeline account. However, CodePipelines do not have a resource policy, and so they cannot trust your Lambda account.

Sorry for the bad news 😕.

Thanks,
Adam

**Comment by warden** [comment]
Thanks for quick answer, that's indeed bad news. Does it make sense for this to be a feature request? (e.g. to grant the Artifact privileges also the codepipeline required privileges?) I guess this depends on the CodePipeline supporting resource policies?

I guess then I need to try doing it the other way round:
- move the lambda to the central account
- in the lambda for CloudFront operations assume the target account role

**Comment by warden** [comment]
I have a working solution already with the inverted scenario so I'll probably post it to aws-labs for sharing.
Quick question yet though:
For the CloudFront origin, I need to have the bucket domain name as returned by CloudFront['DomainName'], so in format:
```<bucketname>.s3.eu-west-1.amazonaws.com```.
However, the methods from (Bucket)[https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-s3.Bucket.html#bucketname-1] all seem to return some incompatible naming, like:
```<bucketname>.s3.amazonaws.com.s3.eu-west-1.amazonaws.com```.

I obviously am constructing the string manually right now:
```
bucketName + '.s3.' + codepipeline_client.meta.region_name + '.amazonaws.com'
```

but it seems to me there should be a method that returns CloudFront compatible naming?

**Comment by skinny85** [comment]
> Quick question yet though:
> For the CloudFront origin, I need to have the bucket domain name as returned by CloudFront['DomainName'], so in format:
> `<bucketname>.s3.eu-west-1.amazonaws.com`.
> However, the methods from [Bucket](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-s3.Bucket.html#bucketname-1) all seem to return some incompatible naming, like:
> `<bucketname>.s3.amazonaws.com.s3.eu-west-1.amazonaws.com`.
> 
> I obviously am constructing the string manually right now:
> 
> ```
> bucketName + '.s3.' + codepipeline_client.meta.region_name + '.amazonaws.com'
> ```
> 
> but it seems to me there should be a method that returns CloudFront compatible naming?

I believe your are looking for the [`bucketRegionalDomainName` property](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-s3.Bucket.html#bucketregionaldomainname).

**Comment by skinny85** [comment]
> Thanks for quick answer, that's indeed bad news. Does it make sense for this to be a feature request? (e.g. to grant the Artifact privileges also the codepipeline required privileges?) I guess this depends on the CodePipeline supporting resource policies?

Yes, this would require CodePipeline (not the artifacts - they already support cross-account access by way of S3 Buckets) to have a Resource Policy. You can open the team a feature request.

**Comment by warden** [comment]
Yeah, I tested before `bucketRegionalDomainName` but I must have mistyped something, that was it indeed, thanks a lot!

> Yes, this would require CodePipeline (not the artifacts - they already support cross-account access by way of S3 Buckets) to have a Resource Policy. You can open the team a feature request.

I'm happy to, but I guess this does not belong to `https://github.com/aws/aws-cdk/` but somewhere else, could you point me to the best place to open that request?

**Comment by skinny85** [comment]
> > Yes, this would require CodePipeline (not the artifacts - they already support cross-account access by way of S3 Buckets) to have a Resource Policy. You can open the team a feature request.
> 
> I'm happy to, but I guess this does not belong to `https://github.com/aws/aws-cdk/` but somewhere else, could you point me to the best place to open that request?

The best place would be reaching out through AWS support (Premium is best, if you have it).

**Comment by warden** [comment]
Case reported: 8502989041.

**Comment by FaresKi** [comment]
Any news on this feature request? I'm currently in the same boat as @rantoniuk and would like to see if a solution has been designed.

**Comment by rantoniuk** [comment]
@FaresKi I just went the other way round approach, you can see the working Lambda solution [here](https://gist.github.com/rantoniuk/c3d0dae4e499d0c11f0c756f6c1da73c#file-cloudfront-invalidation-lambda-py)

**Comment by skinny85** [comment]
I would probably try assuming a Role in the pipeline account.
