### ISSUE TITLE
aws-ecs-patterns: adding loadbalancerName fails to update existing ApplicationLoadBalancedFargateService

### ISSUE THREAD

**Issue by h3adache** [aws/aws-cdk#15233]
Adding a loadBalancerName to  an existing `ApplicationLoadBalancedFargateService` fails to deploy name change.

loadBalancerName was added in `1.108.0` 

### Reproduction Steps

Create an `ApplicationLoadBalancedFargateService` without a `loadBalancerName` using the ecs pattern.
Deploy it.
Update the cdk to add a `loadBalancerName`

The only change is
```
+      loadBalancerName: name,
```

### What did you expect to happen?

I expected the load balancer name to change but I got an error instead.

### What actually happened?

```
Resource handler returned message: "The following target groups cannot be associated with more than one load balancer: arn:aws:elasticloadbalancing:us-west-2:xxxxxxxxxxxx:targetgroup/EcsSe-EcsSe-1IC22F89LVS79/d6ec3e00e48b95c5 (Service: ElasticLoadBalanc
ingV2, Status Code: 400, Request ID: 3210ddb8-700d-448f-ad20-fff37d3a7b0c, Extended Request ID: null)" (RequestToken: 6e5ebe88-d842-db66-ff87-6c7d10bbc542, HandlerErrorCode: ServiceLimitExceeded)
```

### Environment

  - **CDK CLI Version  :** 1.107.0 (build 52c4434)
  - **Framework Version:** 1.108.0
  - **Node.js Version:**  v12.22.1
  - **OS               :** both macos and linux fail
  - **Language (Version):**  Typescript 4.3.2

### Other

--- 

This is :bug: Bug Report

**Comment by madeline-k** [comment]
I was able to repro the same error by first deploying this stack:

```
export class EcsStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);
      new ecsPatterns.ApplicationLoadBalancedFargateService(this, 'MyAppLBFargateService', {
        taskImageOptions: {
          image: ecs.ContainerImage.fromRegistry('amazon/amazon-ecs-sample')
        },
      });
  }
}
```

And then modifying it to this and attempting to deploy:

```
export class EcsStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);
      new ecsPatterns.ApplicationLoadBalancedFargateService(this, 'MyAppLBFargateService', {
        taskImageOptions: {
          image: ecs.ContainerImage.fromRegistry('amazon/amazon-ecs-sample')
        },
        loadBalancerName: "MadelinesLoadBalancer",
      });
  }
}
```

I diffed the two CloudFormation templates produced by each of these stacks and there is only one line different which is the new name being added to the LB. So there is nothing in the resulting CloudFormation template that would explain the error: "The following target groups cannot be associated with more than one load balancer". Since there is still only one load balancer in the template. There is probably an issue with the replacement order of operations where CloudFormation creates a new LB (because name change requires replacement), and has not yet deleted the old one, but tries to hook the existing TargetGroup to the new LB.

**Comment by madeline-k** [comment]
@h3adache, are you trying to deploy this update in a production environment? If not, you should be able to just delete and re-deploy your stack to get around the issue. 

A change like this even if CloudFormation could successfully delete the old LB, create the new LB and make the switch with the TargetGroup in some order that does not result in an error, would probably result in some amount of downtime for your service.

**Comment by h3adache** [comment]
> @h3adache, are you trying to deploy this update in a production environment? If not, you should be able to just delete and re-deploy your stack to get around the issue. 
> 
> 
> 
> A change like this even if CloudFormation could successfully delete the old LB, create the new LB and make the switch with the TargetGroup in some order that does not result in an error, would probably result in some amount of downtime for your service. 

Hi thanks for the quick response! This is not yet in production so yes we can just recreate. I am able to work around it by detaching the target group from the listener rules and redeploy. Terraform handles this using a create before destroy life cycle and 'moving' the target groups as you mentioned. But I understand that isn't really possible in CDK/CF.

**Comment by madeline-k** [comment]
Looks like CloudFormation is aware of this, and they have an issue open on it https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/780

**Comment by suavelizard** [comment]
This is still an issue and shouldn't be closed.

**Comment by SvenMarquardt5772** [comment]
Yes, this is still an issue. Even changing the property publicLoadBalancer from true to false, gives me the following error.
```
The following target groups cannot be associated with more than one load balancer:
```

**Comment by Conaire** [comment]
still an issue

**Comment by pahud** [comment]
This issue has been closed for staleness. If you still have this issue, please create a new one so we can better follow up and address it. Thanks.

**Comment by Conaire** [comment]
The way I worked around this issue is to detect changes in the load balancer and append a v${versionNumber} to the lb and target group.
