### ISSUE TITLE
(bootstrap): allow control of CDKToolkit bucket lifecycle

### ISSUE THREAD

**Issue by chefren** [aws/aws-cdk#15241]
Adding boostrap template parameters to avoid manual changes (drift) to the CDKToolkit s3 bucket resource and avoid increasing usage

### Use Case

Where cost needs to be tightly controlled, but the boostrap Stack continues to exist, continuous deployments will increase S3 usage and varies depending on the assets.

### Proposed Solution

Update the [template](https://github.com/aws/aws-cdk/blob/master/packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml) to allow parameters to setup an S3 lifecycle policy

* [ x] :wave: I may be able to implement this feature request
* [  ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by peterwoodworth** [comment]
Hey @chefren,

You can already configure the bootstrap stack, check out [this page](https://docs.aws.amazon.com/cdk/latest/guide/bootstrapping.html#bootstrapping-customizing) for more information.

Let me know if this doesn't provide what you need, thanks!

**Comment by chefren** [comment]
Hi @peterwoodworth , I see the [template](https://raw.githubusercontent.com/chefren/aws-cdk/master/packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml) has some parameters, but not for the Bucket's [LifecycleConfiguration](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html#cfn-s3-bucket-lifecycleconfig)

I was thinking in adding parameters for this to avoid unlimited growth of storage for artifacts which I think, should be disposable.

From the link you sent, I can see the only way to do this is by creating a new template from the one provided and use it to run bootstrap. Is this what you propose? I understand that to make it configurable through the CLI, will also require extra arguments, but if at least the stack has parameters with default values, it can easily be updated without redeploying the bootstrap template.

**Comment by peterwoodworth** [comment]
Yes, I'm proposing that modifying the bootstrap template is an alternative to your proposed solution. However I think your proposal is reasonable. @rix0rrr what do you think?

**Comment by rix0rrr** [comment]
Your instincts were right @peterwoodworth . We're not going to be offering endless customization of the bootstrap stack out of the box. There are too many different tweaks any number of people are going to want to do, and we can't cater to them all. Customization is possible by editing the template and deploying that.
