### ISSUE TITLE
aws_cloudfront: Has no attribute 'experimental'

### ISSUE THREAD

**Issue by pcolmer** [aws/aws-cdk#15247]
In a Python CDK stack, I want to take advantage of `aws_cdk.aws_cloudfront.experimental.EdgeFunction` as documented at https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_cloudfront.experimental/EdgeFunction.html but, despite the code seeming to be in the installed library, I'm getting a "no attribute" error when I try to use it.

### Reproduction Steps

```
mkdir foo
cd foo
cdk init app --language python
source .venv/bin/activate
python -m pip install -r requirements.txt
pip install aws-cdk.aws-cloudfront
python3
```

then, inside interactive Python:

```
import aws_cdk.aws_cloudfront as cloudfront
foo = cloudfront.experimental.EdgeFunction()
```

### What did you expect to happen?

There should not be an error.

### What actually happened?

Python reports:

`AttributeError: module 'aws_cdk.aws_cloudfront' has no attribute 'experimental'`

### Environment

  - **CDK CLI Version  :** 1.109.0 (build c647e38)
  - **Framework Version:** 1.109.0
  - **Node.js Version:** v12.19.0
  - **OS               :** Ubuntu 20.04.2 LTS
  - **Language (Version):** Python 3.8.5

--- 

This is :bug: Bug Report

**Comment by ryparker** [comment]
Hey @pcolmer :wave:

Thanks for bringing this to our attention. It does look like there is an error in the documentation or python package.

Here is a printout of `aws_cdk.aws_cloudfront`'s attributes:

```
AddBehaviorOptions
AliasConfiguration
AllowedMethods
Behavior
BehaviorOptions
CacheCookieBehavior
CacheHeaderBehavior
CachePolicy
CachePolicyProps
CacheQueryStringBehavior
CachedMethods
CfnCachePolicy
CfnCachePolicyProps
CfnCloudFrontOriginAccessIdentity
CfnCloudFrontOriginAccessIdentityProps
CfnDistribution
CfnDistributionProps
CfnFunction
CfnFunctionProps
CfnKeyGroup
CfnKeyGroupProps
CfnOriginRequestPolicy
CfnOriginRequestPolicyProps
CfnPublicKey
CfnPublicKeyProps
CfnRealtimeLogConfig
CfnRealtimeLogConfigProps
CfnStreamingDistribution
CfnStreamingDistributionProps
CloudFrontAllowedCachedMethods
CloudFrontAllowedMethods
CloudFrontWebDistribution
CloudFrontWebDistributionAttributes
CloudFrontWebDistributionProps
CustomOriginConfig
Distribution
DistributionAttributes
DistributionProps
EdgeLambda
ErrorResponse
FailoverStatusCode
FileCodeOptions
Function
FunctionAssociation
FunctionAttributes
FunctionCode
FunctionEventType
FunctionProps
GeoRestriction
HttpVersion
ICachePolicy
IDistribution
IFunction
IKeyGroup
IOrigin
IOriginAccessIdentity
IOriginRequestPolicy
IPublicKey
KeyGroup
KeyGroupProps
LambdaEdgeEventType
LambdaFunctionAssociation
LoggingConfiguration
OriginAccessIdentity
OriginAccessIdentityProps
OriginBase
OriginBindConfig
OriginBindOptions
OriginFailoverConfig
OriginProps
OriginProtocolPolicy
OriginRequestCookieBehavior
OriginRequestHeaderBehavior
OriginRequestPolicy
OriginRequestPolicyProps
OriginRequestQueryStringBehavior
OriginSslPolicy
PriceClass
PublicKey
PublicKeyProps
S3OriginConfig
SSLMethod
SecurityPolicyProtocol
SourceConfiguration
ViewerCertificate
ViewerCertificateOptions
ViewerProtocolPolicy
__all__
__cached__
__doc__
__file__
__loader__
__name__
__package__
__path__
__spec__
_private
```

_No sign of an `exprimental` attribute_

I will mark this as p1 which means it has been prioritized as important and should see attention soon, although please keep in mind that we do have a large number of issues at the moment. It may be some time before we are able to solve this particular issue. We use +1s to help us prioritize our work.
