### ISSUE TITLE
(custom-resources): Parameters passed to CustomResource are changed to strings.

### ISSUE THREAD

**Issue by mcteo** [aws/aws-cdk#15249]
When you pass parameters of type string, or integer, into a "Lambda backed" Custom Resource they are changed to strings before the Lambda is invoked.

I am using this method to send HTTP requests to Elasticsearch to set up permissions + audit logging, and the API required explicit booleans and integers, therefore have to write extra code to convert these back to integers and booleans.

### Reproduction Steps
Deploy the following, and check the log stream for the Custom Resource's Lambda.

#### lib/stack.ts
```ts
import { Code, Function, Runtime } from "@aws-cdk/aws-lambda";
import { Construct, CustomResource, Stack, StackProps } from '@aws-cdk/core';
import { Provider } from "@aws-cdk/custom-resources";
import * as path from 'path';

export class BugStack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);

    const onEvent = new Function(this, 'MyHandler', { 
      runtime: Runtime.PYTHON_3_8,
      handler: "handler.handle",
      code: Code.fromAsset(path.join(__dirname, "lambda-handler")),
    });

    const myProvider = new Provider(this, 'MyProvider', {
      onEventHandler: onEvent,
    });

    new CustomResource(this, 'MyCustomResource', {
      serviceToken: myProvider.serviceToken,
      properties: {
        values: {
          "string_value": "works",
          "int_value": 123,  // Passing in an integer
          "bool_value": true,  // passing in a boolean
        }
      }
    });
  }
}
```
#### lib/lambda-handler/handler.py
```python
def handle(event, _):
    values = event["ResourceProperties"]["values"]
    print(values)
```

### What did you expect to happen?

I expect the types to be maintained, so the following would be printed (added spacing for clarity):

```text
{
    'string_value': 'works',
    'bool_value': true,
    'int_value': 123
}
```
### What actually happened?

The values were converted into strings, so the following was printed (added spacing for clarity):

```text
{
    'string_value': 'works',
    'bool_value': 'true',
    'int_value': '123'
}
```

### Environment

  - **CDK CLI Version  :** 1.109.0
  - **Framework Version:**1.109.0
  - **Node.js Version:** v12.22.1
  - **OS               :** OSX Catalina
  - **Language (Version):** `"typescript": "~4.3.4"`

### Other

Maybe this is a known issue and the documentation just needs to be updated?

--- 

This is :bug: Bug Report

**Comment by jogold** [comment]
This is unfortunately the behavior of CloudFormation (not CDK). As a workaround, you can `JSON.stringify` your `values` in `lib/stack.ts` and then parse in `lib/lambda-handler/handler.py`.

The [`AwsCustomResource`](https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/custom-resources#custom-resources-for-aws-apis) uses this technique.

**Comment by rix0rrr** [comment]
Thanks for chiming in @jogold
