### ISSUE TITLE
(rds / cloudwatch): DatabaseCluster metric methods do not show data on CloudWatch for alarms 

### ISSUE THREAD

**Issue by JerryBLi** [aws/aws-cdk#15252]
### The Question
I am creating a database cluster using CDK with the [DatabaseCluster](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-rds.DatabaseCluster.html) construct. I want to monitor the database instance using Cloudwatch [Alarms](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cloudwatch.Alarm.html) and have created alarms based on `metricFreeableMemory`, `metricCPUUtilization` and `metricDatabaseConnections` metrics from the DatabaseCluster construct. When I view the alarms and its associated metrics in CloudWatch, no data is being graphed.

From a glance at the Cloudwatch dashboards, it seems like the metrics are case sensitive and the metric being used for the alarm from CDK is not the one that receives data from RDS. The alarm that's created via CDK uses the metric `RDS•CPUUtilization•DBClusterIdentifier: TestDatabase` which does not receive any data. When I dig through all the metrics in Cloudwatch, the following graphs the data I am looking for: `RDS•CPUUtilization•DBClusterIdentifier: testdatabase` (Note the alarm metric has the capital T and D and is the same name as the DBClusterIdentifier as the CDK while the metric that has data is lowercase t and d)

Am I missing something or is this a valid issue? And if this is a valid issue, is there a workaround?

### Environment

  - **CDK CLI Version:** 1.97.0
  - **Node.js Version:** v14.17.0
  - **OS:** Amazon AL2
  - **Language (Version):** Typescript

### Other information
Here is the test stack I created:

```ts
import {Stack, StackProps} from 'monocdk';
import { Construct, Duration } from 'monocdk';
import { SecurityGroup, SubnetType, Vpc } from 'monocdk/aws-ec2';
import { AuroraPostgresEngineVersion, Credentials, DatabaseCluster, DatabaseClusterEngine, DatabaseSecret } from 'monocdk/aws-rds';
import {Alarm, ComparisonOperator, TreatMissingData, Unit} from 'monocdk/aws-cloudwatch';

export class TestStack extends Stack {

  constructor(
    scope: Construct,
    id: string,
    props: StackProps,
  ) {
    super(scope, id, props);
    const rdsVpc = new Vpc(this, 'TestVpc');
    const rdsSecurityGroup = new SecurityGroup(this, 'TestSecurityGroup', {
        vpc: rdsVpc,
      });
        // Create the Database cluster
    const rdsCluster = new DatabaseCluster(this, 'TestDatabase', {
      engine: DatabaseClusterEngine.auroraPostgres({
        version: AuroraPostgresEngineVersion.VER_11_8,
      }),
      backup: {
        retention: Duration.days(7),
      },
      credentials: Credentials.fromSecret(new DatabaseSecret(
        this,
        'TestAdminSecret',
        {
          username: 'postgres',
        },
      )),
      instanceProps: {
        vpc: rdsVpc,
        vpcSubnets: {
          subnetType: SubnetType.PRIVATE,
        },
        securityGroups: [rdsSecurityGroup],
      },
      storageEncrypted: true,
      clusterIdentifier: 'TestDatabase',
      defaultDatabaseName: 'test_database',
      instances: 1,
    });

    const rdsCpuUsage = new Alarm(this, 'TestCpuUsageAlarm', {
        alarmDescription: 'Alarm for too high of CPU Usage for the RDS instance',
        evaluationPeriods: 10,
        metric: rdsCluster.metricCPUUtilization({
            period: Duration.seconds(60),
          }),
        threshold: 90,
        datapointsToAlarm: 5,
        treatMissingData: TreatMissingData.NOT_BREACHING,
    });
    const rdsFreeMem = new Alarm(this, 'TestRdsFreeMemAlarm', {
        alarmDescription: 'Alarm for too high of RAM Usage for the RDS instance',
        evaluationPeriods: 10,
        metric: rdsCluster.metricFreeableMemory({
            unit: Unit.MEGABYTES,
            period: Duration.seconds(60),
        }),
        comparisonOperator: ComparisonOperator.LESS_THAN_OR_EQUAL_TO_THRESHOLD,
        threshold: 256, // 256MB
        datapointsToAlarm: 5,
        treatMissingData: TreatMissingData.NOT_BREACHING,
    });
    const rdsNumConnections = new Alarm(this, 'TestNumConnectionsAlarm', {
        alarmDescription: 'Alarm for too many connections to the RDS instance',
        evaluationPeriods: 10,
        metric: rdsCluster.metricDatabaseConnections({
            period: Duration.seconds(60),
          }),
        threshold: 300,
        datapointsToAlarm: 5,
        treatMissingData: TreatMissingData.NOT_BREACHING,
    });
  }
}
```

**Comment by skinny85** [comment]
Hey @JerryBLi ,

thanks a lot for opening the issue. I believe the problem is this line in your above code:

```ts
      clusterIdentifier: 'TestDatabase',
```

RDS actualy lowercases the name of the database (so in the console, the name of the Cluster will actually be `testdatabase`.

Can you show me your `cdk.json` file? I'm looking whether you have the `@aws-cdk/aws-rds:lowercaseDbIdentifier` feature flag enabled.

**Comment by JerryBLi** [comment]
Thanks for the quick response @skinny85 , it seems like the name of the cluster is indeed lowercase. Is this default behavior to set the clusterIdentifier to be lowercase? I do not have a `lowercaseDbIdentifier` feature flag in my cdk.json. 

My cdk.json is:
```
{
  "app": "node dist/lib/app",
  "output": "build/cdk.out"
}
```

I'd assume for my case, the only fix is to rename the cluster to be all lowercase or to not use the metric methods from the construct?

**Comment by JerryBLi** [comment]
Update, I seemed to be able to fix the metrics showing up by adding the `dimensions` value to the metric prop with the `DBClusterIdentifier` value set to the lowercase value.

So the code initially was
```
    const rdsCpuUsage = new Alarm(this, 'TestCpuUsageAlarm', {
        alarmDescription: 'Alarm for too high of CPU Usage for the RDS instance',
        evaluationPeriods: 10,
        metric: rdsCluster.metricCPUUtilization({
            period: Duration.seconds(60),
          }),
        threshold: 90,
        datapointsToAlarm: 5,
        treatMissingData: TreatMissingData.NOT_BREACHING,
    });
```

and I changed it to
```
    const clusterIdentifier = 'TestDatabase'
    const rdsCpuUsage = new Alarm(this, 'TestCpuUsageAlarm', {
        alarmDescription: 'Alarm for too high of CPU Usage for the RDS instance',
        evaluationPeriods: 10,
        metric: rdsCluster.metricCPUUtilization({
            period: Duration.seconds(60),
            dimensions: {DBClusterIdentifier: clusterIdentifier.toLowerCase()},
          }),
        threshold: 90,
        datapointsToAlarm: 5,
        treatMissingData: TreatMissingData.NOT_BREACHING,
    });
```

I am still interested to know if this is a bug with the RDS CDK or if it's expected behavior.

**Comment by skinny85** [comment]
My take is that it's a bug in RDS - we should lowercase the `DBClusterIdentifier` dimension ourselves (we can't do it for the Cluster itself without the feature flag, as it would cause its replacement, but there's no reason we can't do it for the metric, always, as those are stateless).
