### ISSUE TITLE
(@aws-cdk/aws-dynamodb): CMK should be supported with Global dynamo db

### ISSUE THREAD

**Issue by vishleshpatel** [aws/aws-cdk#15258]
### description of the bug:

CDK throws error when Global Dynamo DB is used with CMK. 

Error: TableEncryption.CUSTOMER_MANAGED is not supported by DynamoDB Global Tables (where replicationRegions was set)

### What did you expect to happen?

build Global Dynamo DB with CMK. 

### What actually happened?

Resource creation failed with : TableEncryption.CUSTOMER_MANAGED is not supported by DynamoDB Global Tables (where replicationRegions was set)

### Environment

  - **CDK CLI Version  :**
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):** 

### Other

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hey @vishleshpatel ,

thanks for opening the issue, but I actually believe this is a DynamoDB limitation. Do you have some documentation that says this should work?

Thanks,
Adam

**Comment by vishleshpatel** [comment]
@skinny85 , sure. they started allowing since Nov 2020 it seems. 

https://aws.amazon.com/about-aws/whats-new/2020/11/encrypt-your-amazon-dynamodb-global-tables-by-using-your-own-encryption-keys/

**Comment by skinny85** [comment]
Thanks for the info @vishleshpatel. Marking this as a feature request. If you'd be interested in contributing it, that would be awesome! Here's our "Contributing" guide: https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md.

**Comment by peterwoodworth** [comment]
Closing in favor of #15957
