### ISSUE TITLE
(backup): support copying backups to other vaults

### ISSUE THREAD

**Issue by tuanardouin** [aws/aws-cdk#15255]
Hi !

The "Copy to destination" functionality is currently unavailable in the BackupPlanProps interface.

### Use Case

When creating a rule, one of the option is to copy the backup to another vault. It's also useful when you want your backup to be stored in another region.

### Proposed Solution

Adding the option to the interface using the required parameter : 
DestinationBackupVaultArn

```typescript
plan.addRule(new backup.BackupPlanRule({
      ruleName: 'theRuleName',
      completionWindow: cdk.Duration.hours(2),
      startWindow: cdk.Duration.hours(1),
      scheduleExpression: events.Schedule.cron({
        hour: '23',
        minute: '30'
      }),
      moveToColdStorageAfter: cdk.Duration.days(30),
      destinationBackupVaultArn: 'arn:aws:backup:us-east-1:123456789012:vault:aBackupVault'
    }))
```

I'm new to CDK and Backup so I could be wrong but : 
- Should the role used by the destination be provided here ?
- Is a cross region copy is event possible using CDK ?

### Other

Documentation : 
Cloudformation Backup [doc](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-backup-backupplan-copyactionresourcetype.html)
CDK BackupPlanProps [doc](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-backup.BackupPlanProps.html)
AWS Backup Cross Region copy [doc](https://docs.aws.amazon.com/aws-backup/latest/devguide/cross-region-backup.html)

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by BenChaimberg** [comment]
Workaround using L1 escape hatch:
```
const crossRegionVaultArn = 'arn:aws:backup:us-east-1:111122223333:vault:crossRegionVault';
const crossRegionVault = backup.BackupVault.fromBackupVaultArn(this, 'Cross Region Vault', crossRegionVaultArn);
const copyPlan = backup.BackupPlan.dailyMonthly1YearRetention(this, 'Copy Plan');
(copyPlan.node.defaultChild as backup.CfnBackupPlan).addPropertyOverride('BackupPlan.CopyActions', [{
  DestinationBackupVaultArn: crossRegionVault.backupVaultArn,
}]);
```

**Comment by BenChaimberg** [comment]
I am unassigning myself and marking this issue as `p2`, which means that we are unable to work on this immediately.

We use +1s to help prioritize our work, and are happy to reevaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://join.slack.com/t/cdk-dev/shared_invite/zt-mso6p56d-qJp7SOTBvMaQuDrx7R2wHg) to solicit support for reprioritization.

Please feel free to work on this issue yourself and request my review if you submit a PR or would like design help! See [CONTRIBUTING.md](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) for guidelines.

**Comment by roblambell** [comment]
The property we override here to get this working is `BackupPlan.BackupPlanRule.0.CopyActions`

**Comment by ashishdhingra** [comment]
@tuanardouin  In CDK v2, [BackupPlanCopyActionProps](https://github.com/aws/aws-cdk/blob/448b441379209b21fe12311e7a7ff6383460b2fb/packages/aws-cdk-lib/aws-backup/lib/rule.ts#L96) has a property `destinationBackupVault` which specifies Destination Vault for recovery points to be copied into. Closing this issue. Feel free to reopen if it doesn't satisfy your use case.
