### ISSUE TITLE
Asynchronous DNS Certificate validation 

### ISSUE THREAD

**Issue by epricer** [aws/aws-cdk#15263]
It would be useful to be able to create certificates that will eventually be validated by DNS but which do not block stack creation.

### Use Case

I have a SaaS product for which we offer domain white labeling to our tenants. We need to be able to create certificates for HTTPS termination, and there can be many that we need to create. Creating them with CDK makes a lot of sense, and allows for automated configuration of the load balancers. Unfortunately, when we create with the CDK, the stack creation process hangs until the DNS is validated. Email validation might work in some cases, but is not what we want. If there were a way to configure the validation to use DNS but to not block stack creation, we could then notify our tenants of the configuration changes that they need to perform.

### Proposed Solution
Offer a new CertificateValidation type such as .fromAsynchronousDns()

### Other

Not sure if this requires a change to CloudFormation or CDK.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by peterwoodworth** [comment]
Thanks for submitting this issue @epricer

I am marking this issue as p2, which means that we are unable to work on this immediately.

We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://join.slack.com/t/cdk-dev/shared_invite/zt-mso6p56d-qJp7SOTBvMaQuDrx7R2wHg) to solicit support for reprioritization.

**Comment by bfg-cloudsupport** [comment]
Can this be reopened. We would like to use CDK to provision public certificates against zone's that are hosted by our infra team. This means manual validation. Since it holds the stack open until they do their bit it blocks subsequent environment pipeline stages meaning we go back to infra with 4 separate requests as the pipeline slowly progresses over the week.
