### ISSUE TITLE
(code pipeline): Unable to assume role when role is explicitly allowed

### ISSUE THREAD

**Issue by jpascoe** [aws/aws-cdk#15265]
## :question: General Issue

I am creating a pipeline that works using previous versions of the CDK but not working in 1.108

### The Question
I'm not sure if anything has changed, but my stack is no longer building due to an error assuming the role

### Environment

  - **CDK CLI Version:** 1.108.1
  - **OS:** Ubuntu
  - **Language (Version):** Python 3.8

IAM Role

```
arn:aws:iam::845899112025:role/SC-845899112025-pp-uryivbgdyx-pipelineRole55399C5D-1KYOVS3NI1A26
```

Trusted: `codepipeline.amazonaws.com`

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "s3:GetObject*",
                "s3:GetBucket*",
                "s3:List*",
                "s3:DeleteObject*",
                "s3:PutObject*",
                "s3:Abort*"
            ],
            "Resource": [
                "arn:aws:s3:::codepipeline-bucket-jpas-452-tst",
                "arn:aws:s3:::codepipeline-bucket-jpas-452-tst/*"
            ],
            "Effect": "Allow"
        },
        {
            "Action": "sts:AssumeRole",
            "Resource": "arn:aws:iam::845899112025:role/SC-845899112025-pp-uryivb-pipelineBuildPyCompileCo-1O2J7VVAH7IVZ",
            "Effect": "Allow"
        },
        {
            "Action": "sts:AssumeRole",
            "Resource": "arn:aws:iam::845899112025:role/SC-845899112025-pp-uryivb-pipelineBuildSourceBuild-1GA2OXO1LPIK4",
            "Effect": "Allow"
        },
        {
            "Action": "sts:AssumeRole",
            "Resource": "arn:aws:iam::845899112025:role/SC-845899112025-pp-uryivb-pipelineSandboxManualApp-1GIAQDMVP6XMD",
            "Effect": "Allow"
        },
        {
            "Action": "sts:AssumeRole",
            "Resource": "arn:aws:iam::845899112025:role/SC-845899112025-pp-uryivb-pipelineSandboxCfnDeploy-1UTQZKHPJ7MHH",
            "Effect": "Allow"
        },
        {
            "Action": "sts:AssumeRole",
            "Resource": "arn:aws:iam::845899112025:role/SC-845899112025-pp-uryivb-pipelineSandboxAppDeploy-GENUXLWDBXBQ",
            "Effect": "Allow"
        },
        {
            "Action": "sts:AssumeRole",
            "Resource": "arn:aws:iam::845899112025:role/SC-845899112025-pp-uryivb-pipelinePreProdManualApp-15Q99M5297BDA",
            "Effect": "Allow"
        },
        {
            "Action": "sts:AssumeRole",
            "Resource": "arn:aws:iam::845899112025:role/SC-845899112025-pp-uryivb-pipelinePreProdCfnDeploy-148OAJ6YUH9KZ",
            "Effect": "Allow"
        },
        {
            "Action": "sts:AssumeRole",
            "Resource": "arn:aws:iam::845899112025:role/SC-845899112025-pp-uryivb-pipelinePreProdAppDeploy-5TOXGWA58ORD",
            "Effect": "Allow"
        },
        {
            "Action": "sts:AssumeRole",
            "Resource": "arn:aws:iam::845899112025:role/SC-845899112025-pp-uryivb-pipelineProdManualApprov-1BKL1CA3AEY2R",
            "Effect": "Allow"
        },
        {
            "Action": "sts:AssumeRole",
            "Resource": "arn:aws:iam::845899112025:role/SC-845899112025-pp-uryivb-pipelineProdCfnDeployPro-1DXQV98MBJ2IH",
            "Effect": "Allow"
        },
        {
            "Action": "sts:AssumeRole",
            "Resource": "arn:aws:iam::845899112025:role/SC-845899112025-pp-uryivb-pipelineProdAppDeployPro-1DI3UY7D3T5J6",
            "Effect": "Allow"
        }
    ]
}
```

### Other information

Error in CloudFormation:

```
arn:aws:iam::845899112025:role/SC-845899112025-pp-uryivbgdyx-pipelineRole55399C5D-1KYOVS3NI1A26
is not authorized to perform AssumeRole on role
arn:aws:iam::845899112025:role/SC-845899112025-pp-uryivb-pipelineBuildPyCompileCo-1O2J7VVAH7IVZ
(Service: AWSCodePipeline; Status Code: 400; Error Code: InvalidStructureException; Request ID: 8face23e-9bca-435f-9b65-b43ad0a0804f; Proxy: null)
```

**Comment by otaviomacedo** [comment]
Hi, @jpascoe. Can you please try to re-bootstrap your account using version 1.109.0 or higher?

**Comment by skinny85** [comment]
Hey @jpascoe,

thanks for opening the issue. Can you explain when do you get this error? You mentioned that your stack is "no longer building", what does that mean?

Can you also rollback to the last CDK version that works, and compare the contents of the `cdk.out` directories that are generated with that version, and with `1.109.0`?

Thanks,
Adam

**Comment by jpascoe** [comment]
I have tried 1.109.0 but that version has completely stopped deploying stacks.
Says...
--app points to a cloud assembly, so we bypass synth

So no stacks get deployed. I'm hoping this is a bug in 109 that will be fixed as it is a major showstopper for us

**Comment by skinny85** [comment]
Like I said, my main question is about `synth`, and comparing the`cdk.out` directory contents between the last revision that was working, and the first revision that is causing problems. Not necessarily `deploy` (although I understand that it's a problem, it's most likely a separate issue).

**Comment by jpascoe** [comment]
The format of deploy parameters has changed. I modified the parameters of deploy and deploy is now working for 109

**Comment by jpascoe** [comment]
I've deployed with 109 but same error.

**Comment by skinny85** [comment]
Can you compare the contents of the `cdk.out` directory after running `cdk synth` with your application using CDK version `1.109.0`, and then `1.107.0` (which I assume was the last one working), and report what are the differences?

**Comment by peterwoodworth** [comment]
Closing this issue for staleness, please follow the instructions Adam posted and ping me or him if you still need help with this issue 😄

**Comment by jpascoe** [comment]
No problem. I’ll create new one once I can can identity exact diff between versions. I think it is between 98 and 99 but not identified exact cause yet
Jason
