### ISSUE TITLE
(@aws-cdk/core.CustomResource): AWS Lambda not receiving parameters passed from CDK CustomResource

### ISSUE THREAD

**Issue by dhirajkhodade** [aws/aws-cdk#15272]
### The Question

I am trying to create lambda based custom resource using AWS CDK but the parameters that I am passing to lambda using `ResourceProperties `are not being received in lambda event object. 

I am not sure what am I doing wrong.

I am getting below error while deploying stack 

> Received response status [FAILED] from custom resource. Message returned: Error: 'EbEnvironmentName'

### CDK Code

```typescript
import * as cdk from '@aws-cdk/core';
import { CustomResource } from '@aws-cdk/core';
import { Provider } from '@aws-cdk/custom-resources';
import lambda = require('@aws-cdk/aws-lambda');

export class CreateEbInfraDevDKStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

   
    const lc_patcher_fn = new lambda.Function(this, `eb_launch_config_patcher`, {
      runtime: lambda.Runtime.PYTHON_3_7,
      code: lambda.Code.fromAsset('./custom_resource_handlers/'),
      handler: 'eb_launch_config_patcher.lambda_handler',
    });

    const lc_patcher_provider = new Provider(this, 'lc_patcher_provider', {
      onEventHandler: lc_patcher_fn,
    });
    
    const customResource = new  CustomResource(this, `CustomResource`, {
      serviceToken: lc_patcher_provider.serviceToken,
      properties: {
        "EbEnvironmentName": "test-parameter",
        "Region": "us-east-1"
      }
    });
  }
}
```

### lambda function code

```python
import os
import sys
import json
import boto3
import base64


def lambda_handler(event, context):
    print("Received event: " + json.dumps(event, indent=2))
    props = event['ResourceProperties']
    aws_region = props['Region']
    eb_environment_name = props['EbEnvironmentName']

```

### lambda log

```json
{
"RequestType": "Create",
"ServiceToken": "arn:aws:lambda:us-east-1:XXXX:function:CreateEbInfraDevStack-lcpatcherproviderframeworkon-Nk9Go2S4g4sh",
"ResponseURL": "https://cloudformation-custom-resource-response-XXXXXXX",
"StackId": "arn:aws:cloudformation:us-east-1:XXXXX:stack/CreateEbInfraDevStack/12f54120-d31c-11eb-a9b3-0e443e7db6f3",
"RequestId": "5f24fc02-2cd4-49e4-a61b-3258b7de3fb4",
"LogicalResourceId": "EBTestCustomResource",
"ResourceType": "AWS::CloudFormation::CustomResource",
"ResourceProperties": {
	"ServiceToken": "arn:aws:lambda:us-east-1:XXXXXX:function:CreateEbInfraDevStack-lcpatcherproviderframeworkon-Nk9Go2S4g4sh",
	"Region": "us-east-1"
	}
}


[ERROR] KeyError: 'EbEnvironmentName'
Traceback (most recent call last):
  File "/var/task/eb_launch_config_patcher.py", line 171, in lambda_handler
    eb_environment_name = props['EbEnvironmentName']
```

### Environment

  - **CDK CLI Version:**  1.105.0
  - **Example:**  custom-resource
  - **Example Version:** 
  - **OS:**  Windows 10
  - **Language:**  TypeScript
  - **Node.js Version:**  12.16.1

  
### Other information 

I am following this CDK example - https://github.com/aws-samples/aws-cdk-examples/tree/master/typescript/custom-resource

**Comment by peterwoodworth** [comment]
Hey @dhirajkhodade, sorry for the long response time.

To use a Lambda function with a custom resource provider, there are certain ways you need to configure your lambda function. Our docs [here](https://docs.aws.amazon.com/cdk/api/latest/docs/custom-resources-readme.html#provider-framework) describe everything necessary to get a function up and running. Notably:

> At the minimum, users must define the onEvent handler, which is invoked by the framework for all resource lifecycle events (Create, Update and Delete) and returns a result which is then submitted to CloudFormation.

It then provides a nice example on how to configure your function

Hope this helps! Ping me if you have any additional questions
