### ISSUE TITLE
(cognito): CfnIdentityPoolRoleAttachment issue with roleMapping when trying to use CfnJson

### ISSUE THREAD

**Issue by EzequielMoroni** [aws/aws-cdk#15288]
The roleMappings property requires that you use identity provider as a key, however if you try to do:

```const identityProvider = `cognito-idp.${region}.amazonaws.com/${userPool.userPoolId}:${userPoolClient.userPoolClientId}` ```

You get:

> throw new Error(`"${key}" is used as the key in a map so must resolve to a string, but it resolves to: ${JSON.stringify(resolvedKey)}. Consider using "CfnJson" to delay resolution to deployment-time`);

So then I am trying to use CfnJson but I am getting this error

> Property validation failure: [Encountered unsupported properties in {/RoleMappings/cognito-idp.us-west-2.amazonaws.com~1us-west-2_m74oKGSkB:72n6ldhbjhd643fk3aob3ag52d}: [type, identityProvider, ambiguousRoleResolution]]

### Reproduction Steps
```ts
const identityProvider = `cognito-idp.${region}.amazonaws.com/${userPool.userPoolId}:${userPoolClient.userPoolClientId}`;

    const roleMapping: cognito.CfnIdentityPoolRoleAttachment.RoleMappingProperty =
      {
        identityProvider: identityProvider,
        type: "Token",
        ambiguousRoleResolution: "AuthenticatedRole",
      };

    const roleMapJson = new cdk.CfnJson(this, "roleMappingJson1", {
      value: {
        [identityProvider]: roleMapping,
      },
    });


    new cognito.CfnIdentityPoolRoleAttachment(
      this,
      getResourceName("identityPoolRoleAttachment"),
      {
        identityPoolId: identityPool.ref,
        roles: {
          authenticated: cognitoAuthRole.roleArn,
          unauthenticated: cognitoUnauthRole.roleArn,
        },
        roleMappings: roleMapJson,
      }
    );
  }
}
```

  

### Other
Please check generated cloudformation attached
[cdk synth.txt](https://github.com/aws/aws-cdk/files/6707375/cdk.synth.txt)

--- 

This is :bug: Bug Report

**Comment by BenChaimberg** [comment]
Because the value returned from CfnJson is directly inserted via CloudFormation, you will need to use the actual CFN property names, as opposed to the "fluent" property names that we generate for the L1 constructs. Concretely, this means that you need to capitalize the keys in `roleMapping`:
```
const roleMapping = {
  IdentityProvider: identityProvider,
  Type: "Token",
  AmbiguousRoleResolution: "AuthenticatedRole",
};
```
