### ISSUE TITLE
toolkit: allow customizing bucket encryption in toolkit bucket

### ISSUE THREAD

**Issue by cybergoof** [aws/aws-cdk#1528]
Request that when running ```cdk deploy```, that s3 bucket name and --sse/--sse-kms-key-id be optional parameters.  I need the ability to specify how the Cloudformation template is stored in the staging S3.

**Comment by eladb** [comment]
Renamed to reflect the intent rather mechanism

**Comment by Obirah** [comment]
Hi, any news on this topic? We also need this feature badly for our enterprise environment.

**Comment by hoegertn** [comment]
Hi, I can see if I can implement this. @eladb Any special wishes what to do and what not to do?

**Comment by uncledru** [comment]
Any update on this?
