### ISSUE TITLE
(s3): bucket.grant_read(role) leads to "bucket-name already exists in stack" error

### ISSUE THREAD

**Issue by l0b0** [aws/aws-cdk#15284]
### Reproduction Steps

1. Instantiate a single copy of [this construct](https://github.com/linz/geostore/blob/31a425aa9abf24aa4e1712949d7574b03427be8a/infrastructure/constructs/staging.py):

   ```python
   from aws_cdk import aws_iam, aws_s3
   from aws_cdk.core import Construct, RemovalPolicy, Tags
   
   
   class Staging(Construct):
       def __init__(self, scope: Construct, stack_id: str) -> None:
           super().__init__(scope, stack_id)
   
           aws_s3.Bucket(
               self,
               "some-id",
               bucket_name="some-static-name",
               access_control=aws_s3.BucketAccessControl.PRIVATE,
               block_public_access=aws_s3.BlockPublicAccess.BLOCK_ALL,
               versioned=True,
               removal_policy=RemovalPolicy.DESTROY,
           )
   ```
1. Give a user read access to this bucket by [adding a single line to the construct](https://github.com/linz/geostore/blob/e5420bb071c417ee73e2576f6dea7ffe3b8bae7c/infrastructure/constructs/staging.py):

   ```python
   from aws_cdk import aws_iam, aws_s3
   from aws_cdk.core import Construct, RemovalPolicy, Tags
   
   
   class Staging(Construct):
       def __init__(self, scope: Construct, stack_id: str, *, users_role: aws_iam.Role) -> None:
           super().__init__(scope, stack_id)
   
           staging_bucket = aws_s3.Bucket(
               self,
               "some-id",
               bucket_name="some-static-name",
               access_control=aws_s3.BucketAccessControl.PRIVATE,
               block_public_access=aws_s3.BlockPublicAccess.BLOCK_ALL,
               versioned=True,
               removal_policy=RemovalPolicy.DESTROY,
           )
           staging_bucket.grant_read(users_role)  # type: ignore[arg-type]
   ```

### What did you expect to happen?

This change should apply just fine.

### What actually happened?

[This](https://github.com/linz/geostore/runs/2881804576?check_suite_focus=true):

```text
… | CREATE_FAILED | AWS::S3::Bucket | processing/staging/some-static-name (…8FF4F2C9) some-static-name already exists in stack arn:aws:cloudformation:ap-southeast-2:***:stack/…/…
```

### Environment

- **CDK CLI Version  :** 1.109.0 (build c647e38)
- **Framework Version:** aws-cli/1.19.53 Python/3.8.10 Linux/5.10.45-1-lts botocore/1.20.53
- **Node.js Version:** v14.17.0
- **OS               :** Arch Linux
- **Language (Version):** Python 3.8.10

### Other

Breaking PRs: [1](https://github.com/linz/geostore/commit/c9541c4852adaaf5b9108d421e9512ae00e51aea) + [2](https://github.com/linz/geostore/commit/72f08910b8c94455df15f92c0a004c75f6170feb); `git diff 31a425a..72f0891 -- infrastructure` to see all the infrastructure changes, even though the above should be the only relevant bit.

Could this be related to https://github.com/aws/aws-cdk/issues/6548?

--- 

This is :bug: Bug Report

**Comment by otaviomacedo** [comment]
Hi, @l0b0. I can't reproduce this issue. Could you point me to a repository that has the minimum amount of code to reproduce it?

Thanks.

**Comment by l0b0** [comment]
Sorry, that was a red herring. The actual issue was that [CDK changes unique IDs when moving a construct](https://docs.aws.amazon.com/cdk/latest/guide/identifiers.html#identifiers_unique_ids):

> AWS CDK generates the necessary unique identifiers by concatenating the elements of the path and adding an 8-digit hash

Unfortunately this means we have to keep the construct where it was originally created, rather than where it belongs, because overriding the ID generation or hard-coding the ID is going to be uglier and more brittle.
