### ISSUE TITLE
(aws-route53): add logging configuration method

### ISSUE THREAD

**Issue by warden** [aws/aws-cdk#15296]
As far as I know, the domain registration in AWS needs to be a manual step via the UI.
That's fine, however we would like then to make sure via CDK that the logging is properly configured for the HostedZone, but the [HostedZone](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-route53.HostedZone.html#static-fromwbrlookupscope-id-query) only allows the queryLogsLogArn to be done inside a constructor - so we have a chicken-egg problem.

Could a method for configuring the loggingGroup be added for a HostedZone retrieved by `fromLookup` ?

**Comment by njlynch** [comment]
To clarify, you are asking if you can lookup an existing `HostedZone` via `fromLookup`, and then set the `queryLogsLogGroupArn` property on the `HostedZone`? If so, the answer is "unfortunately not".

Imported resources (whether via from...Attributes or fromLookup) cannot be modified, only referenced. To modify existing resources, you'll need to either update them in the Stack where they were created, or create a CustomResource to do the job for you.

I hope that answers your question. Feel free to mention me in any follow-ups!

**Comment by warden** [comment]
@njlynch that's exactly what I want to do and I think this is a sensible feature request.
The HostedZone is not created via stack, because it is automatically created when the domain is registered via the UI.
Or maybe I have missed a way to register a domain via CDK together with HostedZone and logging configuration ?

**Comment by njlynch** [comment]
It is a completely reasonable thing to want, but isn't something currently supported by the CDK.

You can track https://github.com/aws/aws-cdk-rfcs/issues/2 for our RFC on the topic of importing resources into the CDK that were created elsewhere (e.g., the console).

**Comment by warden** [comment]
@njlynch uhm, that should remain open as a feature request then IMHO. The RFC you referenced is quite empty I'd say and I don't think it contributes anyhow to getting visibility for this specific request.

Furthermore, it's not entirely true that CDK doesn't support importing resources, because it does for other resources like [S3 Buckets for example](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-s3.Bucket.html#static-fromwbrbucketwbrnamescope-id-bucketname)

**Comment by warden** [comment]
Thanks for detailed explanation. The only comment I have is that... I don't think that RFC :+1: works - it's there for 2 years and only 1 👍🏻 - I'm sure that there are *a lot* of other use cases needing this :-)
