### ISSUE TITLE
(pipelines): pipeline stage variables are not getting replaced in the application stack cfn template

### ISSUE THREAD

**Issue by Shanusk** [aws/aws-cdk#15291]
## :question: General Issue

I have a cdk pipeline with a codebuild stage which runs a bunch of aws cli commands and exports some environment variables using "exported-variables". I'm trying to refer these variables in the downstream application stage (stack), but these variables (example - "#{BuildVariables.xyz}") are not getting replaced in the cloudformation template.

Is there anyway we can refer the codepipeline stage variables in the cloudformation template?

### Environment

  - **CDK CLI Version:** 1.108.1
  - **Module Version:** 1.108.1
  - **Node.js Version:** v16.0.0
  - **Language (Version):** Python (3.9.5)

**Comment by skinny85** [comment]
Hey @Shanusk ,

thanks for opening the issue. The way to refer to CodePipeline Variables in your template is using CloudFormation Parameters in your template, and then setting the values of that parameters with the [`parameterOverrides` property](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-codepipeline-actions.CloudFormationCreateReplaceChangeSetActionProps.html#parameteroverrides) by using the values of the CodePipeline Variables, like `#{BuildVariables.xyz}`.

Thanks,
Adam

**Comment by peterwoodworth** [comment]
Closing because the question has been answered and the bot handling our automatic labels is down. ping me if you need more help with this

- Peter
