### ISSUE TITLE
(aws-ec2): When adding security group via `allowFrom`, it removes the Outbound allow-all-traffic rule from source security group

### ISSUE THREAD

**Issue by jsnowacki** [aws/aws-cdk#15297]
I've encountered this bug when I was setting up service that should allow inbound traffic from EKS cluster, hence, using EKS Cluster Security Group as an external inbound/source group. After adding the SG via `SecurityGroup.connections.allowFrom` method, it removes Allow All Traffic Outbound rule and replaces it with the same as for Inbound in the new group. 
### Reproduction Steps
```typescript
import * as cdk from '@aws-cdk/core';
import * as ec2 from '@aws-cdk/aws-ec2';

export class SgBugStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const someVpc = ec2.Vpc.fromLookup(this, 'Vpc', {isDefault: true});
    const firstSecurityGroup = new ec2.SecurityGroup(this, 'firstSecurityGroup', {vpc: someVpc});
    // This security group has beed created elsewhere; you can create it manually
    const externalSecurityGroupId = 'sg-your-security-group-id';
    const externalSecurityGroup = ec2.SecurityGroup.fromLookup(this, 'externalSecurityGroup', externalSecurityGroupId);
    firstSecurityGroup.connections.allowFrom(externalSecurityGroup, ec2.Port.tcp(443));
  }
}
```

### What did you expect to happen?
Expected behaviour is to either do nothing as there is Allow All Rule (works like that if both Security Groups were created in the same CDK stack), or add this rule without removing other ones.

### What actually happened?
The Allow All Traffic rule has been removed and replaced with the Inbound rule added to the first security group.

### Environment

  - **CDK CLI Version  :** 1.101.0 
  - **Framework Version:** 1.101.0 
  - **Node.js Version:** v14.16.1
  - **OS               :** MacOS X 11.4
  - **Language (Version):** TypeScript (4.3.2) (but I don't think this matter)

### Other
NA

**Comment by njlynch** [comment]
> After adding the SG via SecurityGroup.connections.allowFrom method, it removes Allow All Traffic Outbound rule and replaces it with the same as for Inbound in the new group.

I'd like to ensure I understand the reported behavior correctly.

Prior to deployment, the `externalSecurityGroup` has an "allow all traffic" outbound rule. After deploying the above, the `firstSecurityGroup` is created, and has an inbound rule to allow traffic from `externalSecurityGroup`. `externalSecurityGroup` has a new outbound rule created, allowing traffic to `firstSecurityGroup`; this is removing the default (allow all) outbound rule. Is that correct?

Can you share what the relevant bits of `cdk diff` look like before/after this change? I have a suspicion about the behavior here, but I'm not completely sure about it.

**Comment by jsnowacki** [comment]
> Prior to deployment, the externalSecurityGroup has an "allow all traffic" outbound rule. After deploying the above, the firstSecurityGroup is created, and has an inbound rule to allow traffic from externalSecurityGroup. externalSecurityGroup has a new outbound rule created, allowing traffic to firstSecurityGroup; this is removing the default (allow all) outbound rule. Is that correct?

Yes, you are correct; the addition of inbound rule to `firstSecurityGroup` removes the default (allow all) outbound rule from `externalSecurityGroup` and adds only outbound rule from `externalSecurityGroup` to `firstSecurityGroup` .

`cdk diff` before `cdk deploy`
```
Stack SgBugStack
Security Group Changes
┌───┬───────────────────────────────┬─────┬────────────┬───────────────────────────────┐
│   │ Group                         │ Dir │ Protocol   │ Peer                          │
├───┼───────────────────────────────┼─────┼────────────┼───────────────────────────────┤
│ + │ ${firstSecurityGroup.GroupId} │ In  │ TCP 443    │ sg-0f4d22dab05c2c2c0          │
│ + │ ${firstSecurityGroup.GroupId} │ Out │ Everything │ Everyone (IPv4)               │
├───┼───────────────────────────────┼─────┼────────────┼───────────────────────────────┤
│ + │ sg-0f4d22dab05c2c2c0          │ Out │ TCP 443    │ ${firstSecurityGroup.GroupId} │
└───┴───────────────────────────────┴─────┴────────────┴───────────────────────────────┘
(NOTE: There may be security-related changes not in this list. See https://github.com/aws/aws-cdk/issues/1299)

Resources
[+] AWS::EC2::SecurityGroup firstSecurityGroup firstSecurityGroupEB384935 
[+] AWS::EC2::SecurityGroupIngress firstSecurityGroup/from SgBugStackexternalSecurityGroup60B88D6F:443 firstSecurityGroupfromSgBugStackexternalSecurityGroup60B88D6F443DB749040 
[+] AWS::EC2::SecurityGroupEgress externalSecurityGroup/to SgBugStackfirstSecurityGroup40BA4C9A:443 externalSecurityGrouptoSgBugStackfirstSecurityGroup40BA4C9A443571D1D79 
```

`cdk diff` after `cdk deploy`
```
Stack SgBugStack
There were no differences
```

**Comment by njlynch** [comment]
It appears this is effectively CloudFormation behavior; without a `AWS::EC2::SecurityGroupEgress`, the default "allow all" rule takes effect. Once a `AWS::EC2::SecurityGroupEgress` resource is created, it replaces the default rule.

This can be worked around in this specific case in two ways:
1. Explicitly create an "allow all rule" as well (making the more specific rule redundant)
2. Import the security group using `fromSecurityGroupId`, specifying `mutable` as false to prevent creating the more specific egress rule.

It's possible we could do something creative here with the `fromLookup` version, detecting when the default egress/ingress rules are in place. I'm going to leave this open to track that possibility.
