### ISSUE TITLE
(lambda): Function.fromFunctionArn overwrites the given region from the ARN

### ISSUE THREAD

**Issue by MaartenCleenders** [aws/aws-cdk#15312]
When using the fromFunctionArn function when trying to import a Lambda than the given arn's region gets overwritten by the region defined in the env props.

### Reproduction Steps

**Code:** 
```
const cloudFrontRedirectLambda = Function.fromFunctionArn(this,
        "myFunction",
        "arn:aws:lambda:us-east-1:xxxxxxxxxxxxx:function:myFunction"
);
```

**CDK.json**
```
"env": {
        "region": "eu-central-1",
        "account": "xxxxxxxxxxxxx"
},
```

### What did you expect to happen?

Importing an existing lambda into my current stack

### What actually happened?

```
11:41:36 | CREATE_FAILED        | AWS::Lambda::Version                            | LambdaVersionFA49E61E
Function not found: arn:aws:lambda:eu-central-1:xxxxxxxxxxxxx:function:myfunction(Service: AWSLambdaInternal; Status Co
de: 404; Error Code: ResourceNotFoundException; Request ID: 4e53a496-a24e-408d-89e7-6e993c408917; Proxy: null)

```

### Environment

  - **CDK CLI Version  : 1.109.0**
  - **Node.js Version: v15.11.0** 
  - **OS  : Arch linux**
  - **Language (Version): Javascript** 

--- 

This is :bug: Bug Report

**Comment by BenChaimberg** [comment]
It seems like you are trying to create a new version in eu-central-1 for a function in us-east-1, which is not allowed. Note that eu-central-1 is chosen because we provide only the function name to the CfnVersion definition:
https://github.com/aws/aws-cdk/blob/d88b45eb21bcd051146477e3c97de7dd7b8634d3/packages/%40aws-cdk/aws-lambda/lib/lambda-version.ts#L190
Overriding this to use the full ARN
```
const importedFunctionArn = "arn:aws:lambda:us-east-1:898231755174:function:my-us-east-1-function";
const importedFunction = Function.fromFunctionArn(this, "Imported Function", importedFunctionArn);
const newVersion = new Version(this, 'Version', {
  lambda: importedFunction,
});
(newVersion.node.defaultChild as CfnVersion).addPropertyOverride('FunctionName', importedFunctionArn);
```
simply produces a different error at deploy time:
> Functions from 'us-east-1' are not reachable in this region ('us-west-2') (Service: AWSLambdaInternal; Status Code: 404; Error Code: ResourceNotFoundException; ...)
