### ISSUE TITLE
(aws-dynamoDB): Looking for a construct to restore a dynamoDB table backup

### ISSUE THREAD

**Issue by aiudkc3** [aws/aws-cdk#15319]
### The Question

I am looking for a CDK construct using which I can restore a dynamoDB table form backup.

### Environment

  - **CDK CLI Version:**  1.108.0 (build b23f781)
  - **Module Version:**  1.110.0

**Comment by peterwoodworth** [comment]
On a quick look, I don't think there's currently a construct for this

**Comment by skinny85** [comment]
Hey @aiudkc3,

thanks for opening the issue. Do you know whether this functionality is supported in CloudFormation currently?

Thanks,
Adam

**Comment by aiudkc3** [comment]
Hi Adam,
I don't see this "restore table" functionality on Cloudformation too. I am expecting similar functionality like RDS where we have parameter to provide a snapshot name so that cluster gets created from snapshot. 
at the moment I am just going with SDK.

**Comment by peterwoodworth** [comment]
I wasn't able to find CFN support for this either

**Comment by skinny85** [comment]
OK, that means we would need a CloudFormation Custom Resource to implement this, which makes this issue bigger than just adding a new Layer2 CDK Construct.

**Comment by jumic** [comment]
The feature is requested in CloudFormation, too. See: https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/83 

@aiudkc3 You can add a thumbs up reaction there to prioritize the feature for the CloudFormation team.

**Comment by Gtofig** [comment]
I think it's still relevant. DynamoDB table restoration currently is a heavyweight process if you want to maintain table with CloudFormation/CDK. A construct to help with this would save everyone a lot of time.
