### ISSUE TITLE
(stepfunction_tasks): LambdaInvoke accepts wrong type for payload 

### ISSUE THREAD

**Issue by kkiani** [aws/aws-cdk#15325]
As the documentation says, the LambdaInvoke accepts a list of TaskInputs for parameter payload (`Optional[TaskInput]`). However, when I pass the list of InputTasks as blow, the jsii throws an error that the jsii expected object reference.

### Code
```python
lambda_evaluation_query_task = tasks.LambdaInvoke(self, "RecSysRecipe Get Evaluation Results Step",
            lambda_function=fn,
            payload=[
                sfn.TaskInput.from_json_path_at("$.EvaluationJobName"),
                sfn.TaskInput.from_text('"cdk_mode": true')
            ]
        )
```

### Output
```
 raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: Expected object reference, got [{"$jsii.byref":"@aws-cdk/aws-stepfunctions.TaskInput@10037"},{"$jsii.byref":"@aws-cdk/aws-stepfunctions.TaskInput@10038"}]
```

### What actually happened?
I've tested passing single TaskInput, and the jsii accepts it, which it shouldn't!

```python
lambda_evaluation_query_task = tasks.LambdaInvoke(self, "RecSysRecipe Get Evaluation Results Step",
            lambda_function=fn,
            payload=sfn.TaskInput.from_json_path_at("$.EvaluationJobName")
        )
```
### Environment

  - **CDK CLI Version  :** 1.110.0 (build 32f00eb)
  - **Framework Version:** 1.110.0 (build 32f00eb)
  - **Node.js Version:** 14.16.1
  - **OS               :** macOS 10.15
  - **Language (Version):** Python (3.9)

This is :bug: Bug Report

**Comment by peterwoodworth** [comment]
Where are you seeing that the payload parameter accepts an array of TaskInputs? The code, and therefore [the docs](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-stepfunctions-tasks.LambdaInvoke.html#payload) accept a single TaskInput https://github.com/aws/aws-cdk/blob/32f00eb26486b18619f4cf6ca497759c46aa7c8a/packages/%40aws-cdk/aws-stepfunctions-tasks/lib/lambda/invoke.ts#L23

**Comment by kkiani** [comment]
You are right, my bad. I"m closing the issue
