### ISSUE TITLE
(@aws/cx-api): metadata deployed when no Stack differences

### ISSUE THREAD

**Issue by codeedog** [aws/aws-cdk#15322]
While reviewing the fix to [bug 15023](https://github.com/aws/aws-cdk/issues/15023) we found that metadata reporting (`"versionReporting": true`) causes `cdk deploy` to upload metadata even when `cdk diff` reports no differences and no files have changed. This occurs when the commands are run on different operating systems.

### Reproduction Steps

Craft any stable stack that is javascript only (no native code) and ensure all modules versions are explicit. This [repo](https://github.com/codeedog/aws-test-hello-world) abides by that. Note, `versionReporting` has been set to `false` in that repo's cdk.json. It would need to be set to `true` to see the issue.

````bash
# On a macOS
> git clone git@github.com:codeedog/aws-test-hello-world.git
> cd aws-test-hello-world
> node --version && npm --version
> npm ci      # this will also build the subdirectory
> cdk deploy

# On Ubuntu
> git clone git@github.com:codeedog/aws-test-hello-world.git
> cd aws-test-hello-world
> node --version && npm --version
> npm ci      # this will also build the subdirectory
> cdk diff    # Should show no diffs
> cdk deploy  # Will deploy 2 "changes"; metadata only
````

### What did you expect to happen?

I expected there to be no `deploy` on the second machine due to the lack of any code changes.

### What actually happened?

Metadata was collected making it look like there were changes to the Stack that needed to be built.

### Environment

  - **CDK CLI Version  :** 1.110.0
  - **Framework Version:** 1.110.0
  - **Node.js Version:** v14.17.0 (**note**: also, npm Version: 7.17.0)
  - **OS               :**  macOS Catalina 10.15.7 (19H524) & Ubuntu (20.04.2 LTS, on GitHub)
  - **Language (Version):** Typescript (3.9.9 from package-lock.json)

### Other

Notes from my comment in the now fixed Bug 15023:

> I don't mind turning off metadata to stop this. On the other hand, I'm more than happy to share build results with the AWS CDK team. It seems to me that if there are no differences in a Stack (according to `cdk diff`), metadata should not be pushed. At least, this should be a configuration option (`"versionReporting": "no-deploy-on-no-diffs" | true | false`). Pick a better name for it... Anyway, I'd prefer the first be the default, but at least make this available to folks.

> When I see the system rebuild despite my knowing no files have changed, I worry something has failed or some merge has or hasn't happened. I suspect others may feel this way, too.

To me this feels like a bug (trigger a deploy when no code changed and all modules are stable). You don't send metadata from the same OS when `cdk deploy` is called with no differences. Why should you do so when the command is run on a different operating system and still there are no differences?

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
Can you share the `Metadata` part of the templates, the one that changes between systems? I agree with you that it shouldn't change, but since it does we have to figure out where the change is coming from.

**Comment by codeedog** [comment]
@rix0rrr It looks like they re-opened 15023. I'm going to focus on this issue there.

**Comment by jogold** [comment]
Looks like gzip compression doesn't give the same results on Linux vs macOS...

See https://github.com/aws/aws-cdk/issues/15023#issuecomment-869745179

**Comment by njlynch** [comment]
With `zlib`, it looks like one option might be to convert to using [`deflateRawSync`](https://nodejs.org/api/zlib.html#zlib_zlib_deflaterawsync_buffer_options), which intentionally omit the standard headers in favor of just the raw compressed data.

The server-side for this would need to be tested to verify a corresponding inflate method is available, and also likely need to involve bumping the version as well to indicate that the data coming in is header-less. 

Alternatively, we could potentially just hack the resulting output (from `zlib.gzipSync`) to set the OS byte to "unknown". Slightly uglier implementation, but certainly also less involved.

**Comment by codeedog** [comment]
There is a third option: compare the decompressed data rather than assume the compressed data is stable. This will (1) provide you the guarantee you're looking for across OSes, (2) won't disrupt every deployment like the `deflateSync` change and (3) won't run the risk of some future standard change that blitting over the OS byte does (as unlikely as that will ever be to happen).

The above fix still assumes the compression algorithm is stable across all implementations, OSes and individual runs. I do not believe this assumption is valid and that only comparing the inflated values is guaranteed.

**Comment by jogold** [comment]
For the `diff` vs `deploy` part, there's the question of normalizing the different implementations:

https://github.com/aws/aws-cdk/blob/d2c76aa23f5ac0d596bce7c648753f05a8dd718f/packages/aws-cdk/lib/diff.ts#L26-L34

vs

https://github.com/aws/aws-cdk/blob/d2c76aa23f5ac0d596bce7c648753f05a8dd718f/packages/aws-cdk/lib/api/deploy-stack.ts#L434-L438


For the metadata string (and I don't know your backend of course) I wonder if compression makes sense... I have a template with around 140 resources with constructs from various packages and the difference in bytes is `868`... also doesn't it go against the principle that CF templates are "human readable" (to understand diffs and change sets)?

**Comment by rix0rrr** [comment]
> I wonder if compression makes sense... [...] doesn't it go against the principle that CF templates are "human readable" 

Sure, but at the same time the metadata isn't load-bearing, and if we listed out the data in there in full it would be distractingly huge (taking up a lot of vertical space in a viewer program). Plus, we would be eating 10x more space in a space-constrained template. So I think compression is an acceptable trade-off.

It's a good point that this might cause unintended updates, which don't really harm anyone but take up unnecessary time.

I think a combination of:

* hacking out the OS byte like Nick suggested, plus
* having the short-circuit function disregard the metadata resource

are the best we can do (apart from you configuring `--no-version-reporting`).

**Comment by codeedog** [comment]
@rix0rrr I don't agree that "unintended" Layer rebuilds resulting in new versions are entirely "harmless".

**Comment by eladb** [comment]
This also affects GitHub Workflows support for CDK Pipelines because the asset ID of the template that's encoded in the deploy.yml workflow (generated on the developer machine) is inconsistent with the asset ID generated during the workflow run.

Currently we have to disable version reporting to make that work.
