### ISSUE TITLE
Lambda Alias AppSync Resolvers

### ISSUE THREAD

**Issue by romanfq** [aws/aws-cdk#15321]
Allow a Lambda Data Source that can point to an alias

### Use Case

When using Provisioned Concurrency today in a Lambda- for lower cold-starts- an alias gets created, which is usually called `live`. The ARN of this alias is that of the Lambda Function with a `:live` suffix.

Now, when a lambda data source is added to an AppSync API, the data source is pointing to the Lambda function and not the the alias, and then calls from AppSync don't call the alias but the $LATEST version of the function (no idea why this doesn't work). This defeats Provisioned Concurrency.

There's a manual workaround: after deploying the AppSync API and the Lambda, you can go to the console and
* Adjust the resolver arn to point to the alias
* Adjust the IAM policy that allows AppSync calling into Lambda to point to the alias

### Proposed Solution

Add native support to the CDK to generate an Alias datasource, similar to

```
const alias = ...
const aliasDs: LambdaAliasDataSource = this.appSync.addLambdaAliasDataSource("LambdaDataSource", alias);
``` 

or simply add an override to `addLambdaDataSource` that allows to supply an alias

```
const alias = ...
const lambdaDs: LambdaDataSource = this.appSync.addLambdaAliasDataSource("LambdaDataSource", lambdaFunction, alias);
```

I tried to simulate the same by creating my own types under the DataSource hierarchies (i.e. creating a new sub-type of `BackedDataSource` and forcing a `grantInvoke` on the IAM role for the alias but it didn't work well- I might post repro code at some later stage. 

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by otaviomacedo** [comment]
Hi, @romanfq

I am unassigning and marking this issue as `p2`, which means that we are unable to work on this immediately.

We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://join.slack.com/t/cdk-dev/shared_invite/zt-mso6p56d-qJp7SOTBvMaQuDrx7R2wHg) to solicit support for reprioritization.

**Comment by BryanPan342** [comment]
@romanfq I'm surprised you can't just run 

```
const alias = ...
api.addLambdaDataSource('LambdaDataSource', alias);
```

`addLambdaDataSource` takes `IFunction` as the property type which `Version` and `Alias` extend from...
