### ISSUE TITLE
(@aws: EventBridge): fixed rate scheduler rule not invoking lambda via CDK deployment

### ISSUE THREAD

**Issue by mattiLeBlanc** [aws/aws-cdk#15323]
### The Question

I have setup a rule that invokes a lambda at a set interval. Everything deploys well, but when I look at Cloudwatch, I do not see any logs appear meaning the Lambda doesn't get invoked.
When I go to the console, edit the rule and save it, it starts working.
Logs start to appear in Cloudwatch.

Also, before I edit and save the rule, when I run:
```
aws lambda get-policy --function-name [functionName] --region ap-southeast-2 
```
I get the following error:
```
An error occurred (ResourceNotFoundException) when calling the GetPolicy operation: The resource you requested does not exist.
```
If I run the `get-policy` after saving the rule in Aws Console, I get a policy back:
```
{
  "Version": "2012-10-17",
  "Id": "default",
  "Statement": [
    {
      "Sid": "*****,
      "Effect": "Allow",
      "Principal": {
        "Service": "events.amazonaws.com"
      },
      "Action": "lambda:InvokeFunction",
      "Resource": "arn:aws:lambda:ap-southeast-2:******:functionadmin-api_testScheduler",
      "Condition": {
        "ArnLike": {
          "AWS:SourceArn": "arn:aws:events:ap-southeast-2:*******:rule/AdminApiStack-schedulerRuleE*****
        }
      }
    }
  ]
}
```

My CDK code is like this, as directed in the docs of AWS:
```
export class EventBridgeConstruct extends Construct {

  private props: EventBridgeStackProps;

  constructor(
    scope: Construct,
    id: string,
    props: EventBridgeStackProps
  ) {
    super(scope, id);
    this.props = props;

   // instead of creating a lambda, I am referencing and existing lambda that is already created in my stack
    const fn = LambdaFunction.fromFunctionArn(this, 'testScheduler', this.createLambdaArn('testScheduler'));

    const eventTarget = new LambdaTarget(fn);

    const rule = new Rule(this, 'Rule', {
      enabled: true,
      description: 'test',
      ruleName: 'test23',
      targets: [
        eventTarget
      ],
      schedule: Schedule.rate(Duration.minutes(1)),
    });
  }

  private createLambdaArn(name: string) {
    return `arn:aws:lambda:${Stack.of(this).region}:${Stack.of(this).account}:function:${this.props.applicationName}_${name}`;
  }
}

```

Just to be clear, the lambda is generated earlier with a policy as :
```
  "resources": ["*"],
    "actions": ["*"]
```
So I assume that should allow the lambda to be invoked for any service.

I tried to add a policy:
```
fn.addToRolePolicy(new PolicyStatement({
      actions: ['lambda:InvokeFunction'],
      principals: [new ServicePrincipal('events.amazonaws.com')],
      effect: Effect.ALLOW,
      resources: [fn.functionArn],
      conditions: {
        ArnLike: {
          'AWS:SourceArn': `arn:aws:events:${Stack.of(this).region}:${Stack.of(this).account}:rule/${fn.functionName}`
        }
      }
    }));
```

But that doesnt seem to work. When I call get-policy via the command line it is still undefined.
How can this issue be resolved? 
Why is the CDK not adding the correct policy which is created when I save the existing rule via the console?

### Environment

  - **CDK CLI Version:** 1.107.0
  - **Module Version:** "@aws-cdk/aws-events": "^1.94.1",    "@aws-cdk/aws-events-targets": "^1.94.1",
  - **Node.js Version:** v14.16.1
  - **OS:** acOS Mojave
  - **Language (Version):**  TypeScript (4.2)

**Comment by mattiLeBlanc** [comment]
Okay, I have been digging all day to figure out what is going on.
 I have a working solution like this:

```
export class EventBridgeConstruct extends Construct {

  private props: EventBridgeStackProps;

  constructor(
    scope: Construct,
    id: string,
    props: EventBridgeStackProps
  ) {
    super(scope, id);
    this.props = props;

    const rule = new Rule(this, 'Rule', {
      // schedule: Schedule.rate(Duration.minutes(1))
      schedule: Schedule.cron({
        minute: '0',
        hour: '0',
        day: '*',
      })
    });

    let lambdaFunction = new Function(this, `testScheduler`, {
      runtime: Runtime.NODEJS_12_X,
      code: new AssetCode(`dist/functions/testScheduler`),
      handler: 'index.handler',
    });

    rule.addTarget(
      new LambdaFunction(lambdaFunction
      )
    );
  }
}
```
This works because I am creating a new Lambda and I do not seem to have to add a policy.

The other way, where I am creating a Function from an ARN (`Function.fromFunctionArn(this, 'testScheduler', this.createLambdaArn('testScheduler')),`) doesn't invoke unless I edit the rule and save it again.
This lambda from Arn is created in my Appsync construct and those are lambdas that are normally also linked to appsync queries.
However, I always create them with actions and resources as `'*'`.

**Comment by peterwoodworth** [comment]
When you're importing a resource, you're not actually querying AWS for the resource. So the role that you have attached to your function isn't getting imported here. When you're calling `addToRolePolicy()`  it's doing nothing because there is no role

https://github.com/aws/aws-cdk/blob/0028d09486b96ea95196aa39df9480689b022951/packages/%40aws-cdk/aws-lambda/lib/function-base.ts#L259-L265

To import a function and be able to call `addToRolePolicy()`, you can use the [`fromFunctionAttributes()`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-lambda.Function.html#static-fromwbrfunctionwbrattributesscope-id-attrs) method like so:

```ts
const fn = Function.fromFunctionAttributes(this, 'testScheduler', {
  functionArn: 'arn:aws:lambda:us-west-2:123456789012:function:MyFunction',
  role: role // role can be imported
});

fn.addToRolePolicy(new PolicyStatement({
  actions: ['lambda:InvokeFunction'],
  principals: [new ServicePrincipal('events.amazonaws.com')],
  effect: Effect.ALLOW,
  resources: [fn.functionArn],
  conditions: {
    ArnLike: {
      'AWS:SourceArn': `arn:aws:events:${Stack.of(this).region}:${Stack.of(this).account}:rule/${fn.functionName}`
    }
  }
}));
```

this worked for me. Let me know if you have any more questions!
