### ISSUE TITLE
Is it typo? clientVpnEndoint, not clientVpnEndpoint? 

### ISSUE THREAD

**Issue by kevinhuang40856** [aws/aws-cdk#15337]
https://github.com/aws/aws-cdk/blob/b33e1c524d2928bb64809dea3f17de7ab1deef4d/packages/%40aws-cdk/aws-ec2/lib/client-vpn-route.ts#L68

**Comment by NetaNir** [comment]
Sadly it is, however, changing it is a breaking change.

duplicate https://github.com/aws/aws-cdk/issues/13810
