### ISSUE TITLE
(aws-ecr-assets): DockerImageAsset needs a build breaking functionality based on scan results

### ISSUE THREAD

**Issue by gbvanrenswoude** [aws/aws-cdk#15347]
DockerImageAsset needs a build breaking functionality based on scan results. When building Docker images as separate artifacts, it's fairly easy to scan after build and break the build or at least notify in the same process when any (critical) vulnerabilities are found. CDK should offer this functionality too as an optional parameter, so the scan results can be combined with the information available in the deployment process.

### Use Case

The same use case probably any (fintech) org (bound by compliance rules) has when implementing build breaking functionality when pushing artifacts.

### Proposed Solution

Flag on the class / Different class / probably need a custom resource for this.

This is a :rocket: Feature Request

**Comment by eladb** [comment]
@gbvanrenswoude thanks for proposing this feature. I've marked it as P2, which means we are unlikely to be able to prioritize this in the coming months. Happy to discuss some design options over this issue if you are interested to work on contributing this feature.

**Comment by gbvanrenswoude** [comment]
@eladb This construct comes close to the proposed feature: https://www.npmjs.com/package/cdk-ecr-asset-scanner. A PyPi version is available too. I'll be closing this issue too, assuming improving security insight is a priority on the backlog in itself :)
