### ISSUE TITLE
Codepipeline package installation issue when pushed to github

### ISSUE THREAD

**Issue by SeyiKayode** [aws/aws-cdk#15342]
### Environment

  - **CDK CLI Version:** 1.108.1
  - **Node.js Version:** 14.1
  - **OS:** Ubuntu
  - **Language (Version):** TypeScript 

### Other information
Deploying my application stack works well. But I started getting problems when I created pipeline stages. Each time I push to github, it succeeds on the codepipeline but when I try to test the lambda function, it says "runtime error, module not found 'uuid' ". Meaning the modules are not installed probably on codepipeline. But when I deploy manually again using "cdk deploy", it works. All my lambda functions have their own package.json and it works well when deploying manually with "cdk deploy" but doesnt work when pushed to github and codepipeline.

**Comment by SeyiKayode** [comment]
i am using one repositiry, but deploying to 2 branches. i created 2 application stages and they deploy to 2 separate branches.
i followed the codepipeline guide stated here --> https://docs.aws.amazon.com/cdk/latest/guide/cdk_pipeline.html
i do install my dependencies with "npm install". For the each lamba function, i run 'npm install' inside each lambda function folder then deploy with cdk deploy. 
but when i push to github and codepipeline builds the code, the packages doesnt work anymore unless i deploy with 'cdk deploy' again.
I have also used lambda layers to connect the packages to the lambda functions but its still not working.

**Comment by skinny85** [comment]
Ok, so this is a CDK Pipelines issue.

Do you know about the self-mutating step? If you have any CDK code changes locally that are not pushed, the Pipeline will automatically revert to the state in the GitHub repo each time it runs, "losing" your local changes.

**Comment by SeyiKayode** [comment]
I do push my changes even before deploying. After installing the packages with "npm install" myself, I push them to github. But it doesn't show that the packages have been installed unless i deploy with 'cdk deploy'.

**Comment by SeyiKayode** [comment]
The node modules are still not working on pipeline yet. Tried using lambda layers but it's not working. Only when I deploy manually.

**Comment by rix0rrr** [comment]
> For the each lamba function, i run 'npm install' inside each lambda function folder then deploy with cdk deploy.

Well here's the difference. CDK Pipelines isn't going to `cd` into every directory and run `npm install` inside it-- it doesn't even know what those directories are or that `npm install` needs to be run inside them.

You need to tell it that. Put the same commands you would run locally into `SimpleSynthAction`, for example into [buildCommand](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_pipelines.StandardNpmSynthOptions.html#buildcommandspan-classapi-icon-api-icon-experimental-titlethis-api-element-is-experimental-it-may-change-without-noticespan): 

```ts
SimpleSynthAction.standardNpmSynth({
  // ...
  buildCommand: '(cd dir1 && npm install) && (cd dir2 && npm install) && npm run build'
}),
```
