### ISSUE TITLE
(Tags): Support case sensitive Tags like Cloudformation

### ISSUE THREAD

**Issue by ayozemr** [aws/aws-cdk#15343]
Aws console handles case sensitive tags, for example tag key "Name" displays name in console for VPCs but not if the tag key is "name". Cloudformation supports case sensitive, but even that CDK pass the tag as "Name" if you define the key, seems internally handles it as insensitive dropping duplicate tags if you define both lowercase and capital case. 

### Use Case
Tags.of(dynamodb).add("Name", tableName);
Tags.of(dynamodb).add("name", tableName);
Duplicate tag keys found. Please note that Tag keys are case insensitive.

We use lowercase (As its common practice). Its useful for external monitoring tools but not for aws console, as aws likes them capitalized. To handle this we duplicate them allowing both keys. CDK is not allowing this with a duplicate tag keys found.

### Proposed Solution
Support case sensitive tag keys like cloudformation do

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
Needs investigation why we put that check there in the first place.

**Comment by lxop** [comment]
It seems like some AWS services treat tag keys as case sensitive, and others as case insensitive. As a couple of examples, VPCs can have both `Name` and `name` tags held simultaneously, while IAM roles fail to deploy if both `Name` and `name` are specified. I'm not sure that this is a CDK problem

**Comment by FabrizioCafolla** [comment]
I think the problem is related to CDK, as by default it automatically sets tags to resources, and one of them is `Name`

**Comment by evgenyka** [comment]
It seems like some AWS services treat tag keys as case sensitive, and others as case insensitive. To ensure compatibility and consistent behavior across different AWS services, the CDK treats tag keys as case-insensitive.
