### ISSUE TITLE
(synthetics): support tagging canaries

### ISSUE THREAD

**Issue by iwt-dennyschaefer** [aws/aws-cdk#15344]
Support tags on the Canary resource. Tags defined at the stack level should percolate down and be applied to the canary.

### Use Case

Resource tags are used for access management, financial analysis, and governance. Tags defined at a scope should apply to canaries in that scope.

### Proposed Solution

Have the Canary construct implement ITaggable by adding a `tags` property. The tag format type is "standard". Example implementation: [firehose.DeliveryStream.tags](https://github.com/aws/aws-cdk/blob/1fb1398538bb0bc29b973e4a10f3382983b851a5/packages/%40aws-cdk/aws-kinesisfirehose/lib/delivery-stream.ts#L104). See: [CfnCanary.Tags](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-synthetics-canary.html#cfn-synthetics-canary-tags).

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

--- 

This is a :rocket: Feature Request

**Comment by BenChaimberg** [comment]
@iwt-dennyschaefer I have repurposed this issue into a feature request, hopefully I got your meaning across!

**Comment by BenChaimberg** [comment]
I am unassigning myself and marking this issue as `p2`, which means that we are unable to work on this immediately.

We use +1s to help prioritize our work, and are happy to reevaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://join.slack.com/t/cdk-dev/shared_invite/zt-mso6p56d-qJp7SOTBvMaQuDrx7R2wHg) to solicit support for reprioritization.

Please feel free to work on this issue yourself and request my review if you submit a PR or would like design help! See [CONTRIBUTING.md](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) for guidelines.

**Comment by iwt-dennyschaefer** [comment]
>@iwt-dennyschaefer I have repurposed this issue into a feature request, hopefully I got your meaning across!

Yea this is absolutely OK.

> I am unassigning myself and marking this issue as p2, which means that we are unable to work on this immediately.

Understandable, it's not a super important task.

> We use +1s to help prioritize our work, and are happy to reevaluate this issue based on community feedback. You can reach out to the cdk.dev community on Slack to solicit support for reprioritization.

I'll see what I can do about it :smile:

> Please feel free to work on this issue yourself and request my review if you submit a PR or would like design help! See CONTRIBUTING.md for guidelines.

Yea I would like but so far I'm completely lost in CDK code magic functionality :smirk:

**Comment by BenChaimberg** [comment]
I added an example of what needs to be done in the description, hopefully that helps!

**Comment by iwt-dennyschaefer** [comment]
Cool, I will have a look later this week.

**Comment by BenChaimberg** [comment]
Actually, this is even simpler than I thought as the [L1 already supports tags](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-synthetics.CfnCanary.html#tags-1). Stack-level tags should already be applied to the canary resource. Can you please confirm that you have tried tagging via the canary scope and the tags have not been applied?
