### ISSUE TITLE
(deploy): Where are CloudFormation change sets generated?

### ISSUE THREAD

**Issue by l0b0** [aws/aws-cdk#15359]
https://github.com/aws/aws-cdk/blob/master/packages/aws-cdk/README.md#externally-executable-cloudformation-change-sets

To reproduce, run `cdk deploy --no-execute --change-set-name MyChangeSetName`

What should happen: CDK should either _print the change set_ or _create it in the relevant stack_, or at least _give some indication where the change set has been created_ if it is not going to appear in either of those places. It should then exit immediately with an exit code of 0.

What does happen: CDK prints the standard list of changes to be applied and asks whether I want to apply the change, despite `--no-execute`. When I answer in the negative, because I'm trying to figure out why the deployment is broken and I don't want to break it further, it exits with exit code 1. The stack I'm debugging has no change sets in it after this command.

---

This is a 📕 documentation issue

**Comment by rix0rrr** [comment]
You are probably running into the `--require-approval` prompt. Specify `--require-approval=never` or just answer affirmative, the changeset will be created afterwards.
