### ISSUE TITLE
Feature Request: Allow bucket.onEvent to supply imported roles

### ISSUE THREAD

**Issue by cybergoof** [aws/aws-cdk#1535]
Orgs may require IAM Roles to be pre-created and approved, and thus they can't be created by the CDK template.  Allow the "bucket.OnEvent()" method to have an optional parameter for IRole rather than always creating a new one to be used by the BucketNotificationHandler lambda function.

**Comment by eladb** [comment]
👍

**Comment by MichaelHindley** [comment]
Running into this issue as well, org does not allow ManagedPolicies.

There are places in the CDK where ManagedPolicies are attached and there is no mechanism to supply your own. 
ManagedPolicies are a security and stability concern so it would be great if the CDK didn't enforce using them without offering a way of supplying your own.

**Comment by rix0rrr** [comment]
Still relevant
