### ISSUE TITLE
(core): Unable to update stack because stack already exists

### ISSUE THREAD

**Issue by adam-nielsen** [aws/aws-cdk#15357]
I have been deploying the same CDK stack for a while now, but I had a break of a month or so.  Now when I deploy it, it complains that it can't update some of the resources in my stack, because they already exist in my stack.  Yes, they already exist from the previous deploy, they are supposed to be updated!

I have had this happen with Parameter Store values.  It tried to create a resource with a name "example" but CloudFormation complained "example" already existed.  So I changed the name to "example2" and it deployed, renaming the existing resource.  So I renamed it back to "example" in CDK and deployed again and it updated successfully, going back to the original name that was supposedly in use.  If it could identify and update the resource, why did it initially complain that it already existed?

My latest issue (with a different stack) is now it is complaining it can't create IAM policies because the policy already exists, even though I have not updated that policy:

```
ads-aws-permissions-stack: deploying...
ads-aws-permissions-stack: creating CloudFormation changeset...
12:00:24 pm | CREATE_FAILED        | AWS::IAM::ManagedPolicy | adspermissionsexec...ycdkdeploy7255323D
ads-cdk-deploy already exists in stack arn:aws:cloudformation:ap-southeast-2:12345:stack/ads-aws-permissions-stack/7a5b8790-74ba-11eb-b3aa-06babe40fd84
```
The problem is that I can't simply destroy the stack and redeploy, because all these permissions are attached to users and groups which I have to manually remove and then manually set up again.  Plus one of the policies that will be destroyed is the one that allows me to deploy, so if I destroy the stack I won't have access to deploy it again.

It looks like this could be a newly introduced bug in CloudFormation as I haven't changed anything on the CDK side, other than upgrading the CDK client to see if anything changed but it did not.  If I run `cdk diff` then it does not list the affected resources at all, further suggesting to me that CDK thinks the resources aren't changing and it's CF that is misidentifying them.  Is this a known issue with recent changes to CF?  If not, how can I get CDK to update these existing resources the way it used to?

### Reproduction Steps

Hard to reproduce as it seems you need to re-deploy a stack that was deployed more than a month ago, and the resources that get picked up as conflicting are somewhat random - not all resources in a CDK stack are identified as conflicting.

### What did you expect to happen?

The CDK stack should have deployed as it has done in the past, updating the resources as needed.

### What actually happened?

The CDK stack did not deploy, returning CloudFormation errors complaining that it could not create resources when it should have updated them instead.

### Environment

  - **CDK CLI Version:** 1.109.0
  - **Framework Version:** 1.73.0
  - **Node.js Version:**  16.2.0
  - **OS:** Linux
  - **Language (Version):**  JS

### Other

If you have any suggestions for how to further troubleshoot (e.g. if I can try to manually deploy the CF template) let me know.

--- 

This is :bug: Bug Report

**Comment by adam-nielsen** [comment]
I worked out where to find the CF template and manually uploaded it.  I got the same error, but interestingly before I deployed it, CF told me it was planning to *delete* the resource it was complaining about:

![ads-perms-cdk-remove](https://user-images.githubusercontent.com/278772/123896312-a91c4c00-d9a4-11eb-8a28-6600d6e5c7bd.png)

It didn't delete it though and just came back with the same error:

> 2021-06-30 12:46:38 UTC+1000	adspermissionsexecdeploycdkpolicycdkdeploy7255323D	
CREATE_FAILED	ads-cdk-deploy already exists in stack arn:aws:cloudformation:ap-southeast-2:12345:stack/ads-aws-permissions-stack/7a5b8790-74ba-11eb-b3aa-06babe40fd84

I now see however that it was planning to remove the resource ending in 4B8 and the one it's complaining about is 23D so now I'm wondering whether it's an ordering issue and it's trying to create the new resource before removing the old one?

At any rate, it looks like this is a bug in CloudFormation so I opened a support ticket (Case ID 8526026211) under the CloudFormation category so hopefully they can work out what has happened.

The only thing that comes to mind is that I'm using `cdk --profile xxx` to deploy to two different AWS accounts (prod and test).  Could it be that CDK is caching something globally rather than per-account?  I've never run into any issues before but now I am wondering whether it could have cached a resource identifier from the test account and is now using it for the prod account.  I presume CDK would take care of this automatically though as one of the main use cases is to be able to deploy the same thing across multiple accounts.

**Comment by adam-nielsen** [comment]
AWS support got back to me with this explanation:

> I checked "arn:aws:cloudformation:ap-southeast-2:12345:stack/ads-aws-permissions-stack/7a5b8790-74ba-11eb-b3aa-06babe40fd84" for further information and I found out that issue you are facing is with "adspermissionsexecprojectpfdredeploycdkpfdrepolicycdkdeploy3B9384B8". However in your new template that you attached, you are deploying it with logical id "adspermissionsexecdeploycdkpolicycdkdeploy7255323D".
> 
> Here you are changing the logical id but not Managed Policy Name which is "ads-cdk-deploy". So the stack is trying to create another Policy with same name, which is  not possible without deleting the first. 
> 
> Now to solve this you can either change the Logical id to the older one, this will update already existing policy of yours and the new stack update will be deployed. Or you can change the Policy name in new stack update and than deploy, this will deploy the new policy.

So it appears the problem is this:

1. I create an IAM policy in CDK code with a specific name, CDK puts it under the autogenerated logical ID xxx4B8.
2. I update the IAM policy in CDK code, but CDK changes the logical ID to a new autogenerated value xxx23D.
3. CloudFormation can't deploy the stack because it sees two separate resources (because they have different logical IDs) but both with the same name, so it fails.  It won't delete the old resource to create the new one, which is correct, because this would cause data loss (the new policy would not be attached to the same resources as the old one was, or in the case of Parameter Store, the new parameters would not contain the values the old ones did.)

So the question seems to be - why does CDK change the logical ID when it appears that this should always remain the same?

**Comment by rix0rrr** [comment]
From the changes:

```
adspermissionsexecprojectpfdredeploycdkpfdrepolicycdkdeploy3B9384B8
adspermissionsexecdeploycdkpolicycdkdeploy7255323D
```

It looks like you moved constructs around, which changes their logical id.

See this section of the developer guide: https://docs.aws.amazon.com/cdk/latest/guide/identifiers.html#identifiers_logical_ids

In general, I would recommend you avoid physical-naming resources to combat exactly this problem. See [this blog post](https://aws.amazon.com/blogs/devops/best-practices-for-developing-cloud-applications-with-aws-cdk/), section **Use generated resource names, not physical names**.

To unblock yourself in the current situation, you can use [`stack.renameLogicalId`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.Stack.html#renamewbrlogicalwbridoldid-newid) to force the ids to be the same.
