### ISSUE TITLE
class:aws_cdk.aws_ecs.TaskDefinition: Unable to find property to return task name and task revision

### ISSUE THREAD

**Issue by evanerwee01** [aws/aws-cdk#15358]
## :question: General Issue

Important Information
After I created an Fargate Task I reguire to obtain the Task Name and Revision. E.g.: 
Amazon ECS/Task Definitions
Task Definition: ecs-task-dso:1

Where 'ecs-task-dso' is the task name
and '1' the revision.

I'm unable to find any property that will return these values.

Code

```py
self.ecs_task_definition_name = f'{helpers.ENTITY_PREFIX}ecs-task-{helpers.STAGE}'  
self.ecs_task_definition = TaskDefinition(  
  self,  
    self.ecs_task_definition_name,  
    family=self.ecs_task_definition_name,  
    network_mode=NetworkMode.AWS_VPC,  
    compatibility=Compatibility.FARGATE,  
    cpu='256',  
    memory_mib='512',  
    task_role=self.task_role,  
    execution_role=self.exec_role  
)  
self.log_driver = AwsLogDriver(   
  stream_prefix="git"  
)  
  
self.ecs_task_definition.add_container(  
  os.getenv('BROKER_CONTAINER_NAME',  
              f'{helpers.ENTITY_PREFIX}repo-copy-broker-container{helpers.STAGE}'),  
    image=ContainerImage.from_registry(  
  name=self.image_uri  
    ), port_mappings=[  
  PortMapping(  
  container_port=80  
  ),  
        PortMapping(  
  container_port=443  
  )  
  ],  
    logging=self.log_driver,  
    environment={  
 })
 ```

### The Question

I need to understand how to return the above properties, namely: Task Name and Task Revision

### Environment

  - **CDK CLI Version:** 1.10
  - **Module Version:** 1.10
  - **Node.js Version:** v16.3.0
  - **OS:** Windows 10
  - **Language (Version):** Python 3.9

**Comment by peterwoodworth** [comment]
Hey @evanerwee01,

You're setting the task name by setting the `family` prop. You can still access this prop afterwards by using `self.ecs_task_definition_name.family`

Unfortunately I don't think there's a way to return the revision of a particular TaskDefinition with just the CDK. You would have to use the SDK alongside the CDK to query AWS for the current revision of your TaskDefinition. 

Let me know if you have any more questions 😄

**Comment by evanerwee01** [comment]
We have a number of Lambda functions that start the Fargate task as ad-hoc. We write the task name and revision as an environment variable to Lambda. This is breaking every time we update the CDK deploy. Could we run a post job to query the detail and update Lambda? Is so could you provide an basic example where in the CDK flow. We know how to export the Lambda detail as well as making Boto3 calls.

On Jul 1, 2021, at 8:27 PM, Peter Woodworth ***@***.***> wrote:

﻿

Hey @evanerwee01<https://secure-web.cisco.com/1XWqpzvSgqTOFydNdjgoVjxhiE7qV2qVnzHjdAA8JPiGpy5vy3Ded9KhvHmFW7squI12JcdmywTqY9Rn5RzlkJOwT0GlpCRbB-3U_VQ91nvOn6WoWn4Rz4KAHmHG5UUhhCATSWxhtxzQ87M4OPKjIRuwPM3uJNRLjtqPTveSRuUzRppsi1GC1hqReVv6Eq6bpVE2LR5u7d6dUhLDjLusz6QfQyXRqn1W1kJcus6XX5tm7GpL0oO1qR2rWy05yLCenQJQ9_hACQTznXT8gwHaXFYo8ST7qQTKTasK7Owdm9mpcYE5xxfi4zj5Kin_JJolOnWHKs_j5LNWCNSx46sOQH91ZNZtJAWfyEuXLKd6pg133ZMV7EysZfpnBqV7jk6CaZUFZjXX2HicXDElapmCY2PpBnd3TJY5WrVvUXzVOGM4oXW-1-8d3mLBN9nxbb5VZc1jp2kUCdhVdk2thkQdocoRvJXdaPe6LLtWK4htyukFsYxuZAEqeDmqHa_fnD3RQZcc4iB3R5oFtH1q0DNGH9Q/https%3A%2F%2Fgithub.com%2Fevanerwee01>,

You're setting the task name by setting the family prop. You can still access this prop afterwards by using self.ecs_task_definition_name.family

Unfortunately I don't think there's a way to return the revision of a particular TaskDefinition with just the CDK. You would have to use the SDK alongside the CDK to query AWS for the current revision of your TaskDefinition.

Let me know if you have any more questions 😄

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://secure-web.cisco.com/1NrtHFDUPQjEHfXC_zjXge0Z-EbcnvitCGM4mvv2ku084HMyHjw4rXI3MJPQMWDciM9e9rVuREotcpxWYRPfF2jyNgo8Knkt4CnH3DJmUKZ0GlU3agZARxWCz3FOr1qldmJ84G5TqpfMLiK3iuUP06S2sUi992WtG3vkKSUrf1vfmxxHdMKt8mH8myARm38pdNxNRLxdvRY3BDhf9xgrJbF3tyzaqNcV-qhZB1fzlqawSRyVUDC1hnk7CTsL9NJ77qosVnJ4c7l1NMNV98JufzXHPJdXtNQqvkQObV3cz63SYm0MMONT3EzFExHQvAFcAQiC5Fgr_WIP4PsER9RQVWheT5NMFQc3yjUdGBXMcOwQiqavRN_eJSumTcItJF4abHDePzF9-yOv2FpkIqaMD_eaCdeEDNxHqcvSEexGKTCY2_AF9DDYgONx5iR2KQMyu1f45rDF8Ew9pW2GK1sIDUcbNrdYLXaXs2JtQIR0aH-5BkNjwKXsTUTRTQOc5fKXjQ5U66A2gJknhF3vYlBx0bQ/https%3A%2F%2Fgithub.com%2Faws%2Faws-cdk%2Fissues%2F15358%23issuecomment-872629450>, or unsubscribe<https://secure-web.cisco.com/1GBmoul4CWVInvrNOdnd6Hv_zIObmlAlr2gC3WkpDo8H3vFMZ6HgiWyiBaRKg3JtkW-cnqUZqZM9hftJ8OrKQWbshmJNzDpzzitEftqDWiYssQ2DnoPAZ-K7QfNpo2D3SGUoGQgbkJMWX_5VH1Aw9jXnpD--9D6YdXXPPEl7X8q_6k09esO-_3R9ME6NeMj3YD0I3AAA_3NZtx0tZ3nY7KNeQVnG3CINzrwEzvT703sr8CFXRqcJ-D23Kd05-zDgF5ju9vMnEM-VckHmtoEcIuvoe8enuwKyuQUfSTURBvMNko_VZX2KPjxeHQRhHj2Vk4vsJe5jYJC_oUfaxUCEJEqt9Z7cFnppRIUEXW7hJz5KyGDXMGgZ4WaBp0cW9i4NoFbhrrZPDIwgAofGn1kiKaeTN0frGPFoAUmEzcb6Z0FQLO8jSPCAbl2Uvu_5j9JuF4UwS18OViIlHz4QsagifGjXxM_4PHSLKLVm6fh4y1b5b-cmsU1wdAMkO3t8tib8qf5MXGfJJTvUquciJ8QU2iA/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAUPKU3B2Y6ZZPELNEJBOOFLTVUBWLANCNFSM47RM27BA>.

This message (including any attachments) contains confidential information intended for a specific individual and purpose, and is protected by law. If you are not the intended recipient, you should delete this message and any disclosure, copying, or distribution of this message, or the taking of any action based on it, by you is strictly prohibited.

Deloitte refers to a Deloitte member firm, one of its related entities, or Deloitte Touche Tohmatsu Limited ("DTTL"). Each Deloitte member firm is a separate legal entity and a member of DTTL. DTTL does not provide services to clients. Please see www.deloitte.com/about to learn more.

v.E.1

**Comment by evanerwee01** [comment]
I check in the code, self.ecs_task_definition_name does not have a property called family.  self.ecs_task_definition does, but I dont see a property for the task name.  Could share share an example please.

**Comment by evanerwee01** [comment]
OK, I can see how family work, thank you.  From the SDK I believe ECS, describe_task_definition(**kwargs) will return what we are looking for. I stand to be corrected.

(https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_DescribeTaskDefinition.html)

response = client.describe_task_definition(
    taskDefinition='string',
    include=[
        'TAGS',
    ]
)

The return will contain:

'family': 'string',
'revision': 123,


Where: 

**family (string) --**

The name of a family that this task definition is registered to. Up to 255 letters (uppercase and lowercase), numbers, hyphens, and underscores are allowed.

A family groups multiple versions of a task definition. Amazon ECS gives the first task definition that you registered to a family a revision number of 1. Amazon ECS gives sequential revision numbers to each task definition that you add.

**revision (integer) --**

The revision of the task in a particular family. The revision is a version number of a task definition in a family. When you register a task definition for the first time, the revision is 1 . Each time that you register a new revision of a task definition in the same family, the revision value always increases by one, even if you have deregistered previous revisions in this family.

How do we obtain these values? I believe the taskDefinition = self.ecs_task_definition.task_definition_arn

I looked at: 

from aws_cdk import core, custom_resources

I'm not 109% sure I understand how to do this.

I think calling the SDK will look something like this:

self.task_defintion_detail = custom_resources.AwsSdkCall(
            action='DescribeTaskDefinition',
            service='ECS',
            parameters={
                'Name': 'taskDefinition',
                'Type': 'String',
                'Value': 'task_arn'
            },
            physical_resource_id=self.custom_name
        )

**Comment by evanerwee01** [comment]
After many circles I can kick myself.  The task definition arn contains the family name and revision. (self.ecs_task_definition.task_definition_arn)

arn:aws:ecs:us-east-1:XXXXXXXXXXXX:task-definition/mssp-ecs-task-dso:4

Setting this value to LAMBDA Environment variable is working. When I get the value, I do an rsplit("/",1) and take the second element ["1"]. That is my family name and revision.

**Comment by peterwoodworth** [comment]
Ah I see, glad you got this figured out!
