### ISSUE TITLE
(ec2): Add VpnTunnelOptionsSpecification properties to VpnConnection

### ISSUE THREAD

**Issue by ToppScorer** [aws/aws-cdk#15363]
Add `VpnTunnelOptionsSpecification` properties to `VpnConnection`

### Use Case

`VpnTunnelOptionsSpecification` properties are supported but don't exist in CDK

https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_VpnTunnelOptionsSpecification.html

### Proposed Solution

Add support for `VpnTunnelOptionsSpecification`

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by njlynch** [comment]
Hi @ToppScorer !

We do currently support `VpnTunnelOptions` (see https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ec2.VpnTunnelOption.html). The coverage right now matches both properties available in the [CloudFormation spec](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-vpnconnection-vpntunneloptionsspecification.html), but does not include the other properties listed in the [API reference](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_VpnTunnelOptionsSpecification.html) that aren't yet available in CloudFormation.

It looks like https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/429 is the CloudFormation roadmap issue for tracking adding these missing fields. I'd suggest :+1: that issue and tracking coverage there. In the meantime, I'll mark this item as `needs-cfn` while we wait for the upstream coverage to be added.
