### ISSUE TITLE
(aws-elasticache): Can't update stacks containing CfnUserGroup

### ISSUE THREAD

**Issue by conkiztador** [aws/aws-cdk#15378]
If I use CfnUserGroup in a stack, it initially deploys OK but any updates to the stack later (e.g., adding new resources, changing tags etc) fail with an UPDATE_FAILED in CloudFormation trying to update the UserGroup. This happens despite there being no changes made to the UserGroup itself.

### Reproduction Steps

Deploy the following, then uncomment the CfnOutput definition and deploy again:
```typescript
import * as cdk from '@aws-cdk/core';
import * as elasticache from '@aws-cdk/aws-elasticache';

export class RedisStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const redisUserName = "default";

    const user = new elasticache.CfnUser(this, 'User', {
      engine: 'redis',
      userName: redisUserName,
      accessString: "on +subscribe +unsubscribe +publish",
      userId: `test-${redisUserName}`,
      passwords: ['dontdothis'],
    });

    const userGroup = new elasticache.CfnUserGroup(this, 'UserGroup', {
      engine: 'redis',
      userGroupId: 'test',
      userIds: [user.ref],
    });

    // new cdk.CfnOutput(this, 'RedisOutput', {
    //   value: 'blah',
    //   description: 'Redis output',
    //   exportName: 'redisOutput',
    // });
  }
}
```

### What did you expect to happen?

Updating a stack containing a UserGroup should succeed.

### What actually happened?

CloudFormation 
```
4:22:05 pm | UPDATE_FAILED        | AWS::ElastiCache::UserGroup | UserGroup
Resource handler returned message: "Please specify the list of user IDs to be added or removed. (Service: ElastiCache, Status Code: 400, Request ID: 7748eec8-0ba4-4ba5-a09f-f309078ee3a8, Extended Request ID: null)"
```

### Environment

  - **CDK CLI Version  :** 1.110.1 (build 0028d09)
  - **Framework Version:** 1.110.1
  - **Node.js Version:** v14.16.0
  - **OS               :** Mac OS
  - **Language (Version):** TypeScript (3.9.7)

### Other

--- 

This is :bug: Bug Report

**Comment by otaviomacedo** [comment]
Hi, @conkiztador 

I can't reproduce this issue. Are you sure the only thing that changed between deployments was the new `CfnOutput`? Do you have a GitHub repository you can point me to?

**Comment by conkiztador** [comment]
Thanks for checking @otaviomacedo. That was a cut-down test case based on a larger stack I was seeing the issue in. I could repro on both when I submitted the bug but now both stacks are updating fine for me so 🤷 . Sorry for the noise.

**Comment by deepak-sreekumar** [comment]
I am facing the same issue and found a way to consistently reproduce this. Please ref:https://github.com/aws/aws-cdk/issues/16266
@otaviomacedo @conkiztador
