### ISSUE TITLE
(lambda-nodejs): NodeJsFunction does not correctly install function dependencies since 1.110.0

### ISSUE THREAD

**Issue by HQarroum** [aws/aws-cdk#15389]
This [pull request](https://github.com/aws/aws-cdk/pull/15229) which has been merged into 1.110.0 seems to create issues with our CDK project which cannot bundle our Lambda functions part of our project anymore.

While running `npm ci` instead of `npm install` seems like a good idea since it will not update `package-lock.json`, in reality it is preventing us to build our Lambda functions that are part of a CDK project.

### Reproduction Steps

Create a sample CDK project and a `NodeJsFunction` that is part of the project. The function should be in its own directory with its own `package.json` and `package-lock.json`. Give the Lambda function a dependency (e.g `lodash.template`).

Instanciate `NodeJsFunction` in the CDK project to use with ESBuild.

```js
const description = JSON.parse(fs.readFileSync(path.resolve(__dirname, 'lambdas', 'transformer', 'package.json')).toString());
const transformer = new node.NodejsFunction(this, 'Transformer', {
  entry: `${__dirname}/lambdas/transformer/index.js`,
  runtime: lambda.Runtime.NODEJS_14_X,
  handler: 'handler',
  logRetention: logs.RetentionDays.ONE_MONTH,
  bundling: {
    nodeModules: Object.keys(description.dependencies),
    externalModules: ['aws-sdk']
  }
});
```

The above example will install the `dependencies` specified in the `package.json` of the Lambda function and since 1.110.0 will run `npm ci` instead of `npm install`.

### What did you expect to happen?

The installation of the dependencies to be correctly installed and the function to be bundled.

### What actually happened?

The installation failed with error `cipm can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.`.

This happens even if the `package.json` and the `package-lock.json` of the Lambda function are in sync.

The reason why this happens is because the `package.json` the AWS CDK creates for the function before running `npm` in the `cdk.out/` directory is not the same as the original `package.json` of the Lambda function. The generated `package.json` in the bundle folder looks like the below.

```json
{"dependencies": {"lodash.template": "^4.5.0"}}
```

Because `npm ci` will stop if it finds that the `package.json` and `package-lock.json` are not the same, which is clearly the case because the CDK generates a `package.json` instead of using the original one, we get the error message.

### Environment

  - **CDK CLI Version  :** 1.110.0
  - **Framework Version:**
  - **Node.js Version:** 14.17.0
  - **OS               :** MacOS
  - **Language (Version):** TypeScript (4.3.5)

--- 

This is :bug: Bug Report

**Comment by jogold** [comment]
Looking into this but what happens if you don't have separate `package.json` and `package-lock.json` files for the Lambda function? 

There's no need for a separate `package.json`,  see [reference architecture](https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/aws-lambda-nodejs#reference-project-architecture)

**Comment by HQarroum** [comment]
Hi @jogold, thanks for your reply!

In our case we have some Lambda functions that are shared across projects, and they have their own `package.json` and are  developed and tested separately, because they basically have their own NPM repo. We don't use monorepos.

My point is mainly that a new minor version of the CDK _should not_ break the build of a project with previous version 😉 .

**Comment by jogold** [comment]
@HQarroum sorry for the breaking change.

How about specifying `depsLockFilePath`? I think it should solve your issue. Without it it's the root lock file that is being copied and that's why `npm` complains about the files not being in sync.

```ts
const description = JSON.parse(fs.readFileSync(path.resolve(__dirname, 'lambdas', 'transformer', 'package.json')).toString());
const transformer = new node.NodejsFunction(this, 'Transformer', {
  entry: `${__dirname}/lambdas/transformer/index.js`,
  depsLockFilePath: `${__dirname}/lambdas/transformer/package-lock.json`, // <-- add this line
  runtime: lambda.Runtime.NODEJS_14_X,
  handler: 'handler',
  logRetention: logs.RetentionDays.ONE_MONTH,
  bundling: {
    nodeModules: Object.keys(description.dependencies),
    externalModules: ['aws-sdk']
  }
});
```

**Comment by HQarroum** [comment]
Hi @jogold,

We've tested this change in our code base and so far the build works with 1.111.0 by locking the `package-lock.json`.

Thanks for the pointer !
