### ISSUE TITLE
Failed cdk deploy/delete actions should try to tell me why

### ISSUE THREAD

**Issue by mipearson** [aws/aws-cdk#1538]
Deleting a "demo" stack that contains a bucket with `removalPolicy: cdk.RemovalPolicy.Destroy`

```
$ cdk destroy DemoBucketStack
...
 ❌  DemoBucketStack: destroy failed Error: The stack named DemoBucketStack is in a failed state: DELETE_FAILED (The following resource(s) failed to delete: [Bucket83908E77]. )
    at waitFor (/Users/mp/.nvm/versions/node/v10.13.0/lib/node_modules/aws-cdk/lib/api/util/cloudformation.ts:144:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
The stack named DemoBucketStack is in a failed state: DELETE_FAILED (The following resource(s) failed to delete: [Bucket83908E77]. )
```

Checking the CFN, I see:
```
The bucket you tried to delete is not empty (Service: Amazon S3; Status Code: 409; Error Code: BucketNotEmpty; ...)
```

The CDK toolkit should try to retrieve & display this information if an operation fails rather than relying on the user to use the aws CLI or console to discover it themselves.

**Comment by eladb** [comment]
Would you be able to paste in the entire destroy logs?

**Comment by eladb** [comment]
> I'm starting to feel that this whole "deploy a CloudFormation stack and do monitoring/progress reporting etc" could be its own NPM library.

+1

**Comment by mipearson** [comment]
I don’t have the scrollback handy, but I do remember checking it for the error message. It was a smal stack, so I’m confident it wasn’t something lost in the noise.

+1 to a TS lib for wrangling CFN updates and dealing with logs being a good thing ;)
