### ISSUE TITLE
(pipelines): SelfMutate action uses the latest version of CDK and not the version from package.json

### ISSUE THREAD

**Issue by bmacher** [aws/aws-cdk#15381]
### The Question

I am using [CdkPipelines](https://docs.aws.amazon.com/cdk/api/latest/docs/pipelines-readme.html) with [self-mutating](https://docs.aws.amazon.com/cdk/api/latest/docs/pipelines-readme.html#developing-the-pipeline) enabled, which is pretty neat. However I have concerns that the SelfMutate action could break because it uses the latest version of the CDK and not the version from `package.json` (in my case v1.109.0).

```sh
[Container] 2021/07/01 09:51:22 Running command npm install -g aws-cdk
# ...
+ aws-cdk@1.110.1
added 181 packages from 216 contributors in 6.384s
# ...
[Container] 2021/07/01 09:51:34 Running command cdk -a . deploy CorePipeline --require-approval=never --verbose
```

By doing so you must assume that CDK will always be backward compatible, otherwise could fail in the future. One escape could be to keep the `node_modules` in the  Synth action and run `npx cdk` (at least in TypeScript projects).

### Environment

  - **CDK CLI Version:** 1.109.0
  - **Module Version:** 1.109.0
  - **OS:** Linux
  - **Language (Version):** Typescript

**Comment by rix0rrr** [comment]
You can fix the version by specifying `cdkCliVersion`: https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_pipelines.CdkPipeline.html#cdkcliversionspan-classapi-icon-api-icon-experimental-titlethis-api-element-is-experimental-it-may-change-without-noticespan
