### ISSUE TITLE
(lambda-python): PythonFunction index/handler logic broken if handler in subdirectory

### ISSUE THREAD

**Issue by ewahl-al** [aws/aws-cdk#15391]
If a handler function is located in a subdirectory of the lambda code package, the aws_lambda.Function handler property is set to an incorrect value by this line of code in [aws-lambda-python/lib/function.ts](https://github.com/aws/aws-cdk/blob/6b639bee925a9e552c405fde9d221d515e6023c3/packages/%40aws-cdk/aws-lambda-python/lib/function.ts#L116): 
```
      handler: `${index.slice(0, -3)}.${handler}`,
```

### Reproduction Steps

1. Create a python lambda code package where a handler function is not in the root directory of the package. Example
```
root/
--- main_file.py
--- handlers/
------ __init__.py
------ my_handler.py
--- lib/
------ __init__.py
------ other_python_code.py
```
2. Then deploy a CDK stack containing a PythonFunction construct using this handler. Example:
``` python
from aws_cdk import aws_lambda_python as lambda_python

lambda_python.PythonFunction(
    self, 'ExampleFunction',
    entry="../root",
    handler="handle_lambda",
    index="handlers/my_handler.py")
```

### What did you expect to happen?

A lambda function should be deployed with the handler property set to `handlers.my_handler.handle_lambda`

### What actually happened?

A lambda function was deployed with the handler property set to `handlers/my_handler.handle_lambda`

### Environment

  - **CDK CLI Version  : 1.107.00
  - **Framework Version: 1.107.0
  - **Node.js Version: v12.8.3
  - **OS               : macos
  - **Language (Version): Python 3.8.5

### Other

The index.slice string substitution should replace `/` characters with `.` characters. 

--- 

This is :bug: Bug Report

**Comment by BenChaimberg** [comment]
Workaround:
```
(func.node.defaultChild as lambda.CfnFunction).addPropertyOverride('Handler', 'overridden.handler');
```
Solution is as described above: do string substitution to replace `/` with `.`.

**Comment by ewahl-al** [comment]
Thank you, I didn't know that trick on using the Cfn property override.

**Comment by vincent-turato** [comment]
@ewahl-al Could you explain why or point to documentation that shows that the handler should be using dot notation? Do you receive an error?

**Comment by ewahl-al** [comment]
> @ewahl-al Could you explain why or point to documentation that shows that the handler should be using dot notation? Do you receive an error?

If the lambda function is deployed with the handler path that contains a slash like `handlers/my_handler.handle_lambda` the lambda function will not execute at all. Python package paths use `.` characters and won't work with filesystem `/` characters in the path.  For example, in python one writes `import os.path` not `import os/path`

**Comment by ztane** [comment]
The Python handler name is *not* a file or a simple top-level name inside the file on the lambda. It is an importable object. It could even make sense for it to be inside a layer. Checking that the handler is a file or anything to that effect is an unnecessary restriction over what AWS Lambda Python runtimes allow outside CDK.

**Comment by setu4993** [comment]
#18082 should have fixed this. We replaced parsing of the handler there for subdirectories.
https://github.com/aws/aws-cdk/blob/a1508afab55c3ba0aa88b6aa85ca947badacb4a9/packages/%40aws-cdk/aws-lambda-python/lib/function.ts#L70
