### ISSUE TITLE
(eks): private cluster create fails due to 

### ISSUE THREAD

**Issue by sheetaljoshi** [aws/aws-cdk#15394]
Private cluster create fails because the lamda which adds aws-auth requires kubeconfig to apply config map, the kubeconfig is created via aws eks update-kubeconfig command which requires access to EKS control plane APIs. 
https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-eks/lib/kubectl-handler/apply/__init__.py#L30

### Reproduction Steps

Provisioning private cluster with sample code here https://github.com/aws-samples/aws-cdk-examples/tree/master/typescript/eks/cluster. 

### What did you expect to happen?

EKS Cluster creation to be successful. 

### What actually happened?

EKS Cluster creation is pending at lamba to create aws-auth to succeed.

--- 

This is :bug: Bug [Report](url)

**Comment by amaheshwari21** [comment]
We have a custom who needs this fix right away. Missing capability is causing us to halt the progress in the project.

**Comment by ramuakula** [comment]
[](url)
[EKS Private cluster issue.docx](https://github.com/aws/aws-cdk/files/6755158/EKS.Private.cluster.issue.docx)

**Comment by otaviomacedo** [comment]
Hi @sheetaljoshi 

You say that you are provisioning a private cluster with the code from here: https://github.com/aws-samples/aws-cdk-examples/tree/master/typescript/eks/cluster. But this code doesn't actually configure a private cluster. So I presume you modified the example a bit. Can you please share your code with me so we have a more concrete artifact to discuss?

**Comment by peterwoodworth** [comment]
please ping me with the requested information if you'd like us to investigate this issue.
