### ISSUE TITLE
pipelines: Missing ability to modify the SimpleSynthAction buildspec

### ISSUE THREAD

**Issue by justin8** [aws/aws-cdk#15397]
Currently you can't modify the BuildSpec, which means some features such as git credential helpers (https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html#build-spec.env.git-credential-helper) cannot be used as we can't modify that easily.

### Use Case

git-credential-helper allows for providing git credentials in to the build instance, allowing for example private NPM repos on github to be pulled as a part of the build process.

### Proposed Solution

Passing through the `env` key from the creation of the `SimpleSynthAction`, or better yet the entire buildspec to allow for overrides would probably be the easiest solution here. I imagine usage similar to:

```
const synthAction = SimpleSynthAction.standardYarnSynth({
  sourceArtifact,
  cloudAssemblyArtifact,
  buildSpecOverrides: {
    env: {
      git-credential-helper: "yes"
      }
    }
});
```

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by hoegertn** [comment]
This might be a duplicate of #15169 and is already worked on.

**Comment by justin8** [comment]
Ahh, it definitely is a duplicate of #15169. I tried to search and didn't find that one. Thanks :)
