### ISSUE TITLE
(s3): CustomS3AutoDeleteObjectsCustomResourceProviderHandler description is misleading

### ISSUE THREAD

**Issue by douglasnaphas** [aws/aws-cdk#15398]
The Lambda function `CustomS3AutoDeleteObjectsCustomResourceProviderHandler`, created [here](https://github.com/aws/aws-cdk/blob/7d218c22e5cbfeaf19b1573b537fc34dd07f7b22/packages/%40aws-cdk/aws-s3/lib/bucket.ts#L1880-L1884), gets a `description` of `Lambda function for auto-deleting objects in ${this.bucketName} S3 bucket`, which is misleading if the same function is used for auto-deleting objects in multiple buckets. When the function is used to auto-delete objects in multiple buckets, its description sounds as though it is only used for auto-deleting objects in the first of these buckets to appear in the stack with `autoDeleteObjects` set to `true`.

### Reproduction Steps

Deploy a template including:
```ts
    const frontendLogBucket = new s3.Bucket(this, "FrontendLogBucket", {
      removalPolicy: RemovalPolicy.DESTROY,
      autoDeleteObjects: true,
    });

    const canaryBucket = new s3.Bucket(this, "CanaryBucket", {
      removalPolicy: RemovalPolicy.DESTROY,
      autoDeleteObjects: true,
    });
```

Then change the above to
```ts
    const canaryBucket = new s3.Bucket(this, "CanaryBucket", {
      removalPolicy: RemovalPolicy.DESTROY,
      autoDeleteObjects: true,
    });

    const frontendLogBucket = new s3.Bucket(this, "FrontendLogBucket", {
      removalPolicy: RemovalPolicy.DESTROY,
      autoDeleteObjects: true,
    });
```

Then run `cdk diff`.

### What did you expect to happen?

I would expect to see `cdk diff` output to show no changes, or to show a change in resource descriptions that reflected that no actual changes would happen to the stack resources.

### What actually happened?

I got [output](https://github.com/cdk-turnkey/brian-liberation/runs/2958802041?check_suite_focus=true) that included:
```
[~] AWS::Lambda::Function Custom::S3AutoDeleteObjectsCustomResourceProvider/Handler CustomS3AutoDeleteObjectsCustomResourceProviderHandler9D90184F 
 └─ [~] Description
     └─ [~] .Fn::Join:
         └─ @@ -3,7 +3,7 @@
            [ ] [
            [ ]   "Lambda function for auto-deleting objects in ",
            [ ]   {
            [-]     "Ref": "FrontendLogBucket3DBF59BB"
            [+]     "Ref": "CanaryBucket3FE82AD4"
            [ ]   },
            [ ]   " S3 bucket."
            [ ] ]
```
The above output makes it sound like my `CustomS3AutoDeleteObjectsCustomResourceProviderHandler` would be changed from being associated only with `FrontendLogBucket3DBF59BB` to being associated only with `CanaryBucket3FE82AD4`.

### Environment

  - **CDK CLI Version  :** 1.107.0.
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):**  TypeScript

### Other

--- 

This is :bug: Bug Report

**Comment by douglasnaphas** [comment]
This should probably be considered a breaking change unfortunately, since anything that addressed it would have to change descriptions of Lambdas in existing templates.

**Comment by otaviomacedo** [comment]
Hi, @douglasnaphas 

Thanks for raising this. I am unassigning and marking this issue as `p2`, which means that we are unable to work on this immediately.

We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://join.slack.com/t/cdk-dev/shared_invite/zt-mso6p56d-qJp7SOTBvMaQuDrx7R2wHg) to solicit support for reprioritization.
