### ISSUE TITLE
Trying to use Bucket for BucketDeployment shows weird error

### ISSUE THREAD

**Issue by joshbedo** [aws/aws-cdk#15399]
I setup a pretty simple example where you create a bucket and then create a bucket deployment. When i add the destinationBucket and set it to the bucket created its showing me `Type Bucket is not assignable to IBucket`. I'm not really sure how to fix it and it kind of seems like a bug. I was following a course and the code below is what they had to get things working.

![Screen Shot 2021-07-02 at 4 38 26 AM](https://user-images.githubusercontent.com/607239/124247081-8b0f3280-daef-11eb-8b5e-2a1f96e474e4.png)
![Screen Shot 2021-07-02 at 4 38 36 AM](https://user-images.githubusercontent.com/607239/124247084-8ba7c900-daef-11eb-8b1e-0eaa236041a0.png)

**Comment by peterwoodworth** [comment]
Hey @joshbedo,

This error usually shows up when your cdk package versions are different. Check your `package.json` and make sure all CDK related packages are the same version. Thanks!

**Comment by joshbedo** [comment]
Hey @peterwoodworth, thanks for getting back to me. Ah i thought the same thing initially and went back to change them but I guess I missed one of the packages. That was exactly the issue. Thanks!
