### ISSUE TITLE
(aws-appmesh): Share Mesh through CDK

### ISSUE THREAD

**Issue by rishijatia** [aws/aws-cdk#15404]
Currently in order for a customer to share meshes and set `meshOwner` correctly, they will need to do a manual step outside of CDK to share the mesh through AWS Resource Access Manager (through the CLI or RAM Console).

This feature request proposing adding a custom resource in CDK to be able to do that. (or automatically share?)

### Use Case

```
const arn = 'arn:aws:appmesh:us-east-1:123456789012:mesh/testMesh';
sharedMesh = appmesh.Mesh.fromMeshArn(stack, 'imported-mesh', arn);
// This VirtualNode resource can communicate with the resources in the mesh from different AWS IAM account ID.
new appmesh.VirtualNode(stack, 'test-node', {
  mesh: sharedMesh,
});
```

In this example, the `sharedMesh` has to be shared by the `meshOwner` with `resourceOwners` outside of CDK for the Virtual Node to be created successfully.

This is needed because since CDK is an Infrastructure as a Process language, there should be no manual steps outside of CDK to get infrastructure deployed.

### Proposed Solution

We can add a custom resource to enable customers to perform the RAM operation of sharing meshes in CDK.

### Other

https://github.com/aws/aws-cdk/pull/15353/files

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by skinny85** [comment]
Thanks @rishijatia!
