### ISSUE TITLE
(aws-ecr): Repository construct is missing EncryptionConfiguration

### ISSUE THREAD

**Issue by nikovirtala** [aws/aws-cdk#15400]
Add missing EncryptionConfiguration to the [ECR Repository construct](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecr.Repository.html).

### Use Case

I want to be able to encrypt the container images stored to ECR with a KMS customer managed key (CMK).

### Proposed Solution

Add missing EncryptionConfiguration to the ECR Repository construct.

### Other

This feature has been available on ECR since July 2020: 
- https://aws.amazon.com/about-aws/whats-new/2020/07/ecr-supports-encryption-images-aws-kms-keys/

CloudFormation, as well as the CDK L1 construct, supports it: 

- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecr-repository-encryptionconfiguration.html
- https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecr.CfnRepository.html

You can work around this with an escape hatch, but it should not be necessary.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by madeline-k** [comment]
Agreed this would be a great feature to add! @nikovirtala I am triaging this as a p2, which means the CDK team will not be able to prioritize it right now. But we always welcome contributions! Check out the [contributing guide](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) for instructions on how to submit a PR.

**Comment by nohack** [comment]
@madeline-k created a pr for this.thanks.
