### ISSUE TITLE
(CDK Bootstrap): AWS Configure authentication issue with aws configure credentials and session token

### ISSUE THREAD

**Issue by vkumarrocky1** [aws/aws-cdk#15402]
I configured my aws credentials with session token 
[default]
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_SESSION_TOKEN=

My AWS CLI V2 is working as expected.
But the CDK is unable to recognize the credentials while trying to perfrom CDK Bootstrap

### Environment

  - **CDK CLI Version  :**  1.111.0 (build 556ca93)
  - **OS               :** windows
  - **Language (Version):**  

### Other

--- 

This is :bug: Bug Report

**Comment by gsingh04** [comment]
CDK cli seems sensitive to small/capital casing. It works with 
```
aws_access_key_id = xxxx
aws_secret_access_key = xxxx
aws_session_token = xxxxx
```

**Comment by vkumarrocky1** [comment]
Perfect. It was working. Thank you so much.
