### ISSUE TITLE
(asg): code generated using new SSM parameters result in Internal Failure

### ISSUE THREAD

**Issue by bundgaard** [aws/aws-cdk#15416]
Upgraded to 1.111.0 from 1.101 and the generated CloudFormation code is going to make these changes

```
[~] AWS::AutoScaling::LaunchConfiguration cfx-test-ec2-asg/LaunchConfig cfxtestec2asgLaunchConfig2BCB8A79 replace
 └─ [~] ImageId (requires replacement)
     └─ @@ -1,1 +1,3 @@
        [-] "{{resolve:ssm:/aws/service/ecs/optimized-ami/amazon-linux-2/recommended/image_id}}"
        [+] {
        [+]   "Ref": "SsmParameterValueawsserviceecsoptimizedamiamazonlinux2recommendedimageidC96584B6F00A464EAD1953AFF4B05118Parameter"
        [+] }
```

This result in we are not able to upgrade to the latest CDK and if we would remove the existing stack and upgrade it would result in downtime, which is not optimal.

If this is not the correct sub-module, feel free to update to the correct module.

This is the Kotlin CDK code we are using
```
val autoScalingBuilder = AutoScalingGroupProps.builder()
    .machineImage(EcsOptimizedImage.amazonLinux2())
    .instanceType(InstanceType("c5.2xlarge"))
    .vpc(vpc)
    .vpcSubnets(SubnetSelection.builder().subnetType(SubnetType.PRIVATE).build())
    .minCapacity(2)
    .maxCapacity(4)
```

Also we saw it was working in 1.102 and not 1.103

### Reproduction Steps

Upgrade to the latest version specified and run cdk synth on the stack and deploy using deplou

### What actually happened?

Cannot deploy `INTERNAL FAILURE` during deploy.

### Environment

  - **CDK CLI Version  : 1.111.0**

  - **Node.js Version:** 12.18.2
  - **OS               : Linux**
  - **Language (Version): Kotlin/Java 15** 

### Other

--- 

This is :bug: Bug Report

**Comment by bundgaard** [comment]
Related issue #14629

**Comment by madeline-k** [comment]
Hello @bundgaard, I am not able to reproduce any deployment error when deploying the following code using version 1.101.0 and then upgrading to 1.111.0 and deploying again.  Even though the following code sample produces the same output that you are seeing with `cdk diff` after upgrading to 1.111.0.

```
// Typescript:
new asg.AutoScalingGroup(this, 'group', {
  instanceType: ec2.InstanceType.of(ec2.InstanceClass.C5, ec2.InstanceSize.XLARGE2),
  machineImage: ecs.EcsOptimizedImage.amazonLinux2(),
  vpc: new ec2.Vpc(this, 'vpc'),
  vpcSubnets: {
   subnetType: ec2.SubnetType.PRIVATE,
  },
  minCapacity: 2,
  maxCapacity: 4,
});
```

Can you please share a minimum working cdk stack that reproduces your issue? And also some more detail about the error you are seeing at `cdk deploy`?
