### ISSUE TITLE
(assets): Support fromTar for docker image assets

### ISSUE THREAD

**Issue by pgarbe** [aws/aws-cdk#15419]
It should be possible to add Docker images also from an existing tar file.

```ts
    const taskDefinition = new ecs.FargateTaskDefinition(this, 'TaskDef');
    taskDefinition.addContainer('DefaultContainer', {
      image: ecs.ContainerImage.fromTar('path/to/tarfile'),
      memoryLimitMiB: 512,
    });
```

### Use Case
Some projects do not have a Dockerfile but use external tools to generate their images (e.g. jib). In that case, the image has to be uploaded manually to ECR and it's cumbersome to ensure that the stack has the correct reference (name / tag)  But if it's handled as a regular container image asset CDK could do the heavy lifting. 

### Proposed Solution
Just an idea, needs to be validated:
Run `docker load -i myTar.tar | sed "s/Loaded image: //g"` as executable. This command returns the image name as required. Not sure yet, how to get the tar as asset from the synth to upload assets stage and how to deal with the hash (it should take over the hash of the tar file).

### Other
* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by peterwoodworth** [comment]
Thanks for submitting a request and PR for this @pgarbe! Someone should be able to review the PR soon 😄

**Comment by pgarbe** [comment]
Thanks. Still working on some tests, but looking forward to some feedback.
