### ISSUE TITLE
(aws-cognito): UserPoolResourceServer Identifier as property

### ISSUE THREAD

**Issue by vicmattos** [aws/aws-cdk#15428]
UserPoolResourceServer have Identifier as property

### Use Case
To create a custom OAuthScope there is a requirement for the UserPoolResourceServer Identifier, but this isn't accesible through the object.

### Proposed Solution
Make UserPoolResourceServer have an accessible property with the value Identifier

### Other
* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by nija-at** [comment]
Not sure what you mean. 

It's available here - https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cognito.UserPoolResourceServer.html#userpoolresourceserverid

**Comment by peterwoodworth** [comment]
closing, please open if you need to revisit this
