### ISSUE TITLE
(aws-ec2): new Vpc() creates additional unnecessary AWS::EC2::EIP when NatGatewayProps.eipAllocationIds is provided

### ISSUE THREAD

**Issue by darshan-yadav** [aws/aws-cdk#15422]
On creating a VPC with existing EIP. It creates Natgateway with that EIP. But it also creates an additional EIP which is not associated with any resource. 

### Reproduction Steps

        subnet1 = SubnetConfiguration(
                name="Public",
                subnet_type=SubnetType.PUBLIC,
                cidr_mask=24)
        subnet2 = SubnetConfiguration(
                name="Private",
                subnet_type=SubnetType.PRIVATE,
                cidr_mask=24)

        vpc = Vpc(self,
                  "VPC",
                  cidr="60.0.0.0/16",
                  enable_dns_hostnames=False,
                  enable_dns_support=True,
                  max_azs=2,
                  nat_gateway_provider=NatProvider.gateway(eip_allocation_ids=["eipalloc-0b3efa74ac9d306a9"]),
                  nat_gateways=1,
                  nat_gateway_subnets=ec2.SubnetSelection(subnet_type=ec2.SubnetType.PUBLIC),
                  subnet_configuration=[subnet1, subnet2]
                  )

This will create NG and attach with passed EIP. But it will also create an additional EIP. To run this you need to create an EIP manually. I want to do that to assign the same public IP to my NG every time. 

### What did you expect to happen?

It should have not created additional EIP.

### What actually happened?

Created an additional EIP

### Environment

  - **CDK CLI Version  :1.111.0.0
  - **Framework Version:Python
  - **Node.js Version:** v14.17.1
  - **OS               :Windows
  - **Language (Version):** Python 3.8

### Other

--- 

This is :bug: Bug Report

**Comment by madeline-k** [comment]
Hi @darshan-yadav, thanks for opening an issue. Yep it looks like the CDK is automatically creating an EIP even if you provide an EIP Allocation Id. 

See here for creation of the EIP: https://github.com/aws/aws-cdk/blob/ebfc0e092addbcf21562ce63328457285f7b2d77/packages/%40aws-cdk/aws-ec2/lib/vpc.ts#L1776 

If an EIP allocation Id is provided, then the `gateway.allocationId` field is replaced with the provided one here: https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-ec2/lib/nat.ts#L230 

And so the resulting Cloudformation template still has the EIP that was generated, but it is not being referenced anywhere.

**Comment by madeline-k** [comment]
What impact does this issue have for you? Is it just that there is an extra EIP resource that you didn't intend to allocate? 

I am triaging this as a p2, which means the CDK team will not be able to prioritize fixing this right now. But we always welcome contributions! If you want to try to fix this yourself, the code links I provided above should give you a good place to start. And please take a look at the [contributing guide.](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md)

**Comment by darshan-yadav** [comment]
It's okie to have it as P2. I just want to make sure this is an issue, not something that I am doing wrong. I will try to fix it in a branch and submit it for review.
