### ISSUE TITLE
NAT Gateway’s Dependence on Internet Gateway for Private Communications

### ISSUE THREAD

**Issue by abjoshi2785** [aws/aws-cdk#15432]
### The Question
<!--
do you have any insight into CDK support for this https://aws.amazon.com/about-aws/whats-new/2021/06/aws-removes-nat-gateways-dependence-on-internet-gateway-for-private-communications/?

**Comment by peterwoodworth** [comment]
Hey @abjoshi2785, you're going to need to include a description of your issue for us to help you out 😄

**Comment by abjoshi2785** [comment]
@peterwoodworth Please find below the description :)
Recently AWS has removed NAT Gateway’s dependence on Internet Gateway for private communications. I tried exploring the L2 constructs and coudn't find a way to use this feature. Could you please suggest is this implementation supported via CDK? 

https://aws.amazon.com/about-aws/whats-new/2021/06/aws-removes-nat-gateways-dependence-on-internet-gateway-for-private-communications/

**Comment by peterwoodworth** [comment]
According to the docs you linked:

> A private NAT Gateway, or NAT Gateway with connectivity type set to private, does not require EIP and you do not need to attach an internet gateway with your VPC.

Looks to me like our NAT Gateway is only available [as an L1 construct](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ec2.CfnNatGateway.html), but you can directly set its connectivity type. Looking at the [Cfn docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-natgateway.html), `private` is an accepted value for the prop `connectivityType`. So it looks to me like you can use this feature with the CDK!

**Comment by peterwoodworth** [comment]
As a heads up though, the CDK will automatically create an Internet Gateway (and more) for your L2 VPC if you have any non-isolated subnets. See here: https://github.com/aws/aws-cdk/blob/556ca93e2f66ea44b1d6f1649a11d5cc5168b3ef/packages/%40aws-cdk/aws-ec2/lib/vpc.ts#L1246-L1271

**Comment by abjoshi2785** [comment]
@peterwoodworth There is a addNatGateway method available for L2 construct class PublicSubnet https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ec2.PublicSubnet.html#addwbrnatwbrgateway

As of now as per the documentation it only creates a new managed NAT gateway attached to this public subnet.

**Comment by peterwoodworth** [comment]
The addNatGateway method will create a public NatGateway with an AllocationId though, are you sure this is what you want? https://github.com/aws/aws-cdk/blob/556ca93e2f66ea44b1d6f1649a11d5cc5168b3ef/packages/%40aws-cdk/aws-ec2/lib/vpc.ts#L1772-L1781

The new feature you linked describes public communications, so I don't think you want to use this function

**Comment by abjoshi2785** [comment]
Actually i was looking for a similar method to create a NAT geteway for private communications. But was not able to find one.

**Comment by peterwoodworth** [comment]
There isn't one currently, we could make a feature request for that if you're interested. 

If you want to accomplish this now, you'll have to create a `CfnNatGateway` in your code. That's all the `addNatGateway()` function is doing anyway, you can see that in the code I posted in the above comment :)

```ts
const myNatGateway = new CfnNatGateway(this, 'NATGateway', { 
   subnetId: myPrivateSubnet.subnetId, 
   connectivityType: 'private'
}); 
```

**Comment by abjoshi2785** [comment]
Thank you! I will create a feature request for it. Meanwhile will use the L1 construct :)

**Comment by peterwoodworth** [comment]
@abjoshi2785 you can also create a PR and implement this yourself if you'd like

**Comment by peterwoodworth** [comment]
Once you confirm that the workaround I posted works for you and post a feature request we can go ahead and close this issue :)

**Comment by peterwoodworth** [comment]
Feel free to ping me if you still need help with this issue 😄
