### ISSUE TITLE
(aws-apigatewayv2-authorizers): HttpUserPoolAuthorizer constructor should take and array of user pool client ids

### ISSUE THREAD

**Issue by dan-lind** [aws/aws-cdk#15431]
The current HttpUserPoolAuthorizer is created like this

```
const authorizer = new HttpUserPoolAuthorizer({
    userPool: userPool,
    userPoolClient: userPoolClient,
});
```

This will synthesize to 
```
 "MyTestHttpProxyPrivateApiUserPoolAuthorizer":{
   "Type":"AWS::ApiGatewayV2::Authorizer",
   "Properties":{
      "ApiId":{
         "Ref":"MyTestHttpProxyPrivateApi"
      },
      "AuthorizerType":"JWT",
      "Name":"UserPoolAuthorizer",
      "IdentitySource":[
         "$request.header.Authorization"
      ],
      "JwtConfiguration":{
         "Audience":[
            "<user pool id>"
         ],
         "Issuer":"https://cognito-idp.eu-west-1.amazonaws.com/eu-west-1_XXXXXXXXX"
      }
   }
},

```
Where the provided user pool client id end up in the `Audience` array

### Use Case

Currently it is possible to provide multiple user pool ids using a HttpJwtAuthorizer

```
const jwtAuthorizer = new HttpJwtAuthorizer({
    jwtAudience: ['XXXXXX', 'YYYYYY'],
    jwtIssuer: `https://cognito-idp.eu-west-1.amazonaws.com/eu-west-1_XXXXXXXXX`
})
```

For consistency and ease of use, HttpUserPoolAuthorizer should also allow users to pass an array of user pool clients, rather than a single one.

### Proposed Solution

Allow users to pass an array of user pool clients like so

```
const authorizer = new HttpUserPoolAuthorizer({
    userPool: userPool,
    userPoolClient: [userPoolClient1, userPoolClient2, userPoolClient3]
});
```

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by nija-at** [comment]
Thanks for submitting this feature request.

I'm marking this issue as a p2, which means we will not be working on this right away. We are accepting pull requests if you would like to contribute.

**Comment by yogarasu** [comment]
I am also facing this problem.
I can't target multiple app clients and I'm looking for a workaround.
