### ISSUE TITLE
How can I ensure customers making requests from app to Apigateway Http Api can only view certain data in dynamodb?

### ISSUE THREAD

**Issue by DanielStarkey** [aws/aws-cdk#15449]
## :question: General Issue
I've got a HTTP API GW generated using @aws-cdk/aws-apigatewayv2 with a number of NodeJs Lambda Functions.

I've created both a User Pool and Identity Pool and linked them together, and a React app that uses Amplify to take care of gaining the JWT and temporary credentials.

The React app is able to send the temporary credentials in the appropriate headers, but I need to secure the API Gateway so that it gets the appropriate IAM role (auth/unauth) based on the credentials.

### Environment

  - **CDK CLI Version:** 
  - **Module Version:** 
  - **Node.js Version:** 
  - **OS:** 
  - **Language (Version):**

**Comment by peterwoodworth** [comment]
I'm not sure what you mean by the API Gateway getting an IAM role. From what I can tell, you can't assign a role to an API. What exactly do you want to accomplish here?

**Comment by DanielStarkey** [comment]
The user in Cognitio User Pools have an attribute specifying which company they belong to.
They login into the React app, and this gets a JWT from User Pool and then temporary credentials from Identity Pool - the authenticated user is mapped to an IAM role which contains policies saying what data the user can and can't see.

When the user makes requests from the React app to the API Gateway (which invokes a lambda, and then queries DynamoDb), I want to ensure they are only able to view specific data (i.e. partitions where the PK starts with their company name) based on the policies from the IAM role.

**Comment by peterwoodworth** [comment]
What part are you currently getting stuck at? The docs [here](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_examples_dynamodb_items.html) show how you can accomplish this just with policies

[Here's a nice guide](https://aws.amazon.com/blogs/mobile/building-fine-grained-authorization-using-amazon-cognito-user-pools-groups/) that describes how to do this (not with the CDK)

Let me know if these links aren't helpful
