### ISSUE TITLE
(aws-codepipeline): ActionDeclaration - Support CombineArtifacts configuration when BatchEnabled is enable

### ISSUE THREAD

**Issue by martinmicunda** [aws/aws-cdk#15455]
See this [doc](https://docs.aws.amazon.com/codebuild/latest/userguide/sample-pipeline-batch.html) which says

> To enable batch builds in CodePipeline, set the BatchEnabled parameter of the configuration object to true. To combine the build artifacts into the same location, set the CombineArtifacts parameter of the configuration object to true.

The configuration object it is referring to is [this](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codepipeline-pipeline-stages-actions.html#cfn-codepipeline-pipeline-stages-actions-configuration).

It is not possible right now to provide this on the [CodeBuildAction](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-codepipeline-actions.CodeBuildAction.html)

### Use Case

We need to add a combine artifacts for batch code build action to our pipeline.

### Proposed Solution

```javascript
    const codebuildAction = new codepipelineActions.CodeBuildAction({
      actionName: 'Build',
      project: createCodeBuildProject(),
      input,
      outputs,
      batchEnabled: true,
      combineBatchBuildArtifacts: true // something like this
    })
```
would set the `CombineArtifacts` and property on Configuration to true. The implementation should happen somewhere around this [place](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-codepipeline-actions/lib/codebuild/build-action.ts#L216).

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by skinny85** [comment]
Thanks for opening the issue @martinmicunda. [Pull Requests are always very much welcome](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) 😉.

**Comment by martinmicunda** [comment]
@skinny85 PR [created](https://github.com/aws/aws-cdk/pull/15457)
