### ISSUE TITLE
(aws-cloudtrail): import trail from_trail_arn

### ISSUE THREAD

**Issue by jaidisido** [aws/aws-cdk#15462]
Add a `from_trail_arn` method to the Trail construct.

The solution suggested in this closed [issue](https://github.com/aws/aws-cdk/issues/6716) does not address our use case (described below).

### Use Case
Our users create multiple buckets across multiple CDK applications and stacks. Each of these buckets must be added as an S3 event selector to the same trail (`add_s3_event_selector`).

### Proposed Solution
Adding `from_trail_arn` would allow us to instantiate an `ITrail` and add each bucket to the event selectors list in the same place where the bucket is defined instead of where the trail was initially defined.

**Comment by rix0rrr** [comment]
Even if you could import a CloudTrail with `from_trail_arn`, it would still not be possible to add selectors to it. CloudFormation only allows defining selectors in the template that CREATES the trail, not any other template.
