### ISSUE TITLE
Breaking Change Between Versions For Handling RDS Generated Secret Username Causing Database Replacement

### ISSUE THREAD

**Issue by danbo0001** [aws/aws-cdk#15478]
Using CDK v1.61.1, I generated an RDS db instance and it automatically added the master username I provided into a generated secret and **the subsequent generated CF contained a secret lookup to get that username for the stack create**.

This is the version we went to production with late last year and development has recently picked up again so I have upgraded to a newer version (v1.110.0) and made a change to use a custom subnet group which is a no-replacement-required change.

However, this version has the DatabaseInstance not requiring a master username, but instead a credential that can be created using the original master username. **The generated CF displays the username as a literal string instead of the secret lookup causing CF to think this is a change and unfortunately a master username change is a replacement-required change so the db gets deleted and a new one is spun up**.

This is a production system and it is unacceptable to have the db deleted, especially for this unnecessary reason.

### Reproduction Steps

In both samples, props.MasterUserName is my_master_user.

In a v1.61.1 c# .net core project, create an rds instance using:-

      _db = new DatabaseInstance(this, "MyDatabase", new DatabaseInstanceProps()
      {
        Engine = DatabaseInstanceEngine.Postgres(new PostgresInstanceEngineProps()
        {
          Version = PostgresEngineVersion.VER_12_3
        }),
        Vpc = vpc,
        VpcPlacement = new SubnetSelection(){SubnetType = SubnetType.PRIVATE},
        MasterUsername = props.MasterUserName,
        DatabaseName = props.DatabaseName,
        InstanceType = InstanceType.Of(InstanceClass.BURSTABLE3, InstanceSize.LARGE),
        Port = props.DbPort, 
        MultiAz = props.MultiAz, 
        AllocatedStorage = props.AllocatedStorage, 
        Iops = props.Iops, 
        BackupRetention = Duration.Days(props.BackupRetentionDays),
        DeletionProtection = false,
        SecurityGroups = _securityGroups,
        EnablePerformanceInsights = true,
        MonitoringRole = _rdsMonitoringRole
      });

The key here is what is generated in CF for masterusername:-

        "MasterUsername": {
          "Fn::Join": [
            "",
            [
              "{{resolve:secretsmanager:",
              {
                "Ref": "MyDatabaseSecret9EF5DC81"
              },
              ":SecretString:username::}}"
            ]
          ]
        },

In a v1.110.0 c# .net core project, use the same code with the mandatory changes as required by the updated cdk version (I have included my actual required change of a custom parameter group):-

      _db = new DatabaseInstance(this, "MyDatabase", new DatabaseInstanceProps()
      {
        Engine = DatabaseInstanceEngine.Postgres(new PostgresInstanceEngineProps()
        {
          Version = pgVersion
        }),
        Vpc = vpc,
        VpcSubnets = new SubnetSelection(){SubnetType = SubnetType.PRIVATE},
        Credentials =  Credentials.FromGeneratedSecret(props.MasterUserName),
        DatabaseName = props.DatabaseName,
        InstanceType = InstanceType.Of(InstanceClass.BURSTABLE3, InstanceSize.LARGE),
        Port = props.DbPort, 
        MultiAz = props.MultiAz, 
        AllocatedStorage = props.AllocatedStorage, 
        Iops = props.Iops, 
        BackupRetention = Duration.Days(props.BackupRetentionDays),
        DeletionProtection = false,
        SecurityGroups = _securityGroups,
        EnablePerformanceInsights = true,
        MonitoringRole = _rdsMonitoringRole,
        AutoMinorVersionUpgrade = false,
        ParameterGroup = parameterGroup
      });

Here is what is generated in CF for masterusername:-

        "MasterUsername": "my_master_user"

This difference causes the db delete/replace as CF considers these two different values for master username.

### What did you expect to happen?

I expected to see a changeset containing only non-replacing changes (i.e. my new custom parameter group).

### What actually happened?

I got a changeset that, in addition to my custom parameter group, contained a master username change which required a db replacement.

### Environment

  - cdk cli v1.61.1
  - _what is framework version if it is not the same as language version?_
  - v14.17.1
  - windows 10
  - c# .net core 3.1

### Other

I have tried to find a way to circumvent this and make it so that i can upgrade cdk version and also not blow away the prod db.

The first option was to use a property override as this is the standard way of handling cdk generation issues.
However, c# .net core does not handle json natively (i think this is the correct way of describing it?), so it is not possible to generate the json in the format as it would be expected by CF. It generates an escaped string - this issue has been noted previously in GH at:-

https://github.com/aws/aws-cdk/issues/2533

There was no solution provided for it and it only got a first response 5 months after it was created so i am not hopeful that there is a solution.

The second option was to dig through the cdk docs and try to find a way to get the new version to generate the secret lookup. There is in fact a property on the Credential class that seems ideal for this - UsernameAsString. I attempted to find a way to set this to false, but couldn't as it doesn't seem exposed anywhere.

I then had a look at the source code and found that it is only set in the constructor which i cannot call and it is hardcoded to true in both of the static functions that i am able to call.

This is why in my opinion this is a bug - this property should be accessible, if it is always true there is no point in even having it exist!

I am really hoping that I have missed something obvious and it will indeed be possible to avoid the db replacement, but I think I have been looking too hard at this now and cannot see the wood for the trees :)

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hey @danbo0001 ,

thanks for opening the issue. I believe your problem stems from using the `Credentials.FromGeneratedSecret()` method here. I believe what you want in this situation is to use the `Credentials.FromUsername()` instead.

Thanks,
Adam

**Comment by danbo0001** [comment]
hi skinny85!

i didn't even think to use that function as it had no setting of the UsernameAsString property, but then i realised of course that meant it would default to false which is what i need :)

but i also didn't look at it properly as it is deprecated which is a more worrying issue - does that mean at some point it will disappear from the credentials class and i will be forced to use one of the functions that cause a db replacement?

i don't mind changing to use one of the newer functions as long as i can set property and ensure master username can continue to be a secret lookup :)

**Comment by danbo0001** [comment]
oops forgot to make it @skinny85 so you'd get notified

**Comment by skinny85** [comment]
Hey @danbo0001. That method is deprecated mainly so that new users use the other ones, in order to avoid exactly the problems that you are running into right now 🙂. But we don't anticipate removing it anytime soon.

Hope this clarifies things, let me know if you need any more info from our side on this issue!

Thanks,
Adam
