### ISSUE TITLE
(aws-eks): NodeGroups are not accepting CfnParameters

### ISSUE THREAD

**Issue by hemandee** [aws/aws-cdk#15485]
Desired Size,Max Size and Min Size are not accepting CfnParameters properly, the evaluation leads to incorrect evaluation at synth time. 

Error:
Desired capacity -1.888154589708894e+289 can't be greater than max size -1.8881545897088942e+289

### Reproduction Steps

    // The code that defines your stack goes here
    const count = new CfnParameter(this,'count',{
      default: "2",
      type: "Number"
    })
    const mincount = new CfnParameter(this,'mincount',{
      default: "2",
      type: "Number"
    })

    const maxcount = new CfnParameter(this,'maxcount',{
      default: "10",
      type: "Number"
    })

    const eksCluster = new Cluster(this,'ekscluster',{
      version: KubernetesVersion.V1_20
    })

    const nodegroup = new Nodegroup(this,'eksnodegroup',{
      cluster: eksCluster,
      desiredSize: count.valueAsNumber,
      maxSize: maxcount.valueAsNumber,
      minSize: mincount.valueAsNumber
    })

### Environment

  - **CDK CLI Version  : 1.109.0 (build c647e38)
  - **Framework Version:**
  - **Node.js Version:**  v12.12.0
  - **OS               : big Sur
  - **Language (Version):** Typescript
### Other

--- 

This is :bug: Bug Report

**Comment by otaviomacedo** [comment]
Hi, @hemandee 

Thanks for reporting this.

I am unassigning and marking this issue as `p2`, which means that we are unable to work on this immediately.

We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://join.slack.com/t/cdk-dev/shared_invite/zt-mso6p56d-qJp7SOTBvMaQuDrx7R2wHg) to solicit support for reprioritization.
