### ISSUE TITLE
(aws-cdk): Add a .prettierrc

### ISSUE THREAD

**Issue by douglasnaphas** [aws/aws-cdk#15489]
I want a [Prettier configuration file](https://prettier.io/docs/en/configuration.html) added at the root of the project, to avoid linter errors where the linter's formatting rules differ from Prettier's defaults.

### Use Case

I bet that Visual Studio Code is the most commonly used editor for working on contributions to the CDK, and that most VS Code users have the formatting extension Prettier set up to auto-format on save.

In the case of trailing commas and single-quoted strings, and maybe other cases, checks run in CDK packages with `yarn run lint` can fail when files have been formatted using Prettier's default settings.

Prettier uses [double-quoted strings by default](https://prettier.io/docs/en/options.html#quotes), and a [trailing comma setting](https://prettier.io/docs/en/options.html#trailing-commas) of `es5`. The CDK linter is looking for single-quoted strings, and more trailing commas than are added by the `es5` setting.

This is a nuisance, because it's annoying to have to run `yarn run lint --fix` after every save to undo the changes Prettier has made. At the same time, having Prettier set to format on save is a huge productivity boost, in the case of the many changes it makes that do not disagree with the CDK linter, like breaking up long lines.

### Proposed Solution

Add a file called `.prettierrc` to the root of the project with the following contents:

```json
{
  "trailingComma": "all",
  "singleQuote": true
}
```

When I added this in my local fork of the project, my linter errors went away. I have not exhaustively checked for other cases where Prettier's defaults differ from CDK linter requirements.

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
I understand this is not an unreasonable request, but I am hesitant to commit to maintaining more config, that barely anyone in our team uses and so can only get out of sync and disappoint people in the future.

We use `eslint` to fix formatting. 

If you want to use prettier, I think it should be easy enough for you to add your own `.prettierrc` file to your CDK checkout.
