### ISSUE TITLE
(aws-sns): How can I specify a Secret as the Subscription endpoint

### ISSUE THREAD

**Issue by JerryBLi** [aws/aws-cdk#15482]
## :question: General Issue
I am trying to create a SNS [Subscription](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-sns.Subscription.html) that sends messages to a slack webhook. Typically, I can set the slack webhook URL as the `endpoint` property of the `Subscription` and set the `protocol` to be `SubscriptionProtocol.HTTPS` and things would work; however, due to InfoSec guidance, hardcoded Slack webhook URLs are a risk and cannot be hardcoded in the CDK code and committed to source control. 

### The Question
Is there a way to set the `Subscription` construct `endpoint` property to be the value of a [Secret](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-secretsmanager.Secret.html)?

I tried the following:

```
    // Securely store the Slack URL in a Secret
    const slackWebhookUrlSecret = new Secret(this, 'SlackWebhookUrlSecret');
    const webhookSubscription = new Subscription(this, 'WebhookSubscription', {
      endpoint: Secret.fromSecretNameV2(
        this,
        'SlackWebhookURL',
        slackWebhookUrlSecret.secretName,
      ).secretValue.toString(),
      protocol: SubscriptionProtocol.HTTPS,
      topic,
    });
```
but I get the following error when trying to deploy to CloudFormation: `"Invalid parameter: Endpoint must match the specified protocol".`

### Environment

  - **CDK CLI Version:** 1.109.0
  - **Node.js Version:** v14.17.0
  - **OS:** Amazon AL2
  - **Language (Version):** Typescript

### Other information

If using Secrets Manager is not the correct method of securely storing the webhook URL, can you give guidance how to securely store a URL and use it as the endpoint for a SNS Subscription?

**Comment by jumic** [comment]
You are trying to create the secret and the SNS subscription based on the secret in a single stack. When the SNS subscription is created during the Cloudformation deployment, the URL in the secret is initial/empty. This means, that it doesn't match the specified protocol (empty string doesn't match an URL).

If you create the secret (manually or in another stack) and maintain the correct URL, you can create the SNS subscription based on the secret. In this case, Cloudformation can read the correct value (HTTPS URL) during the deployment and the validation will not fail.

```
new sns.Subscription(this, 'WebhookSubscription', {
  endpoint: secretsmanager.Secret.fromSecretNameV2(
    this,
    'SlackWebhookURL',
    'SlackWebhookURL',
  ).secretValue.toString(),
  protocol: sns.SubscriptionProtocol.HTTPS,
  topic,
});
```

Please also check the SNS subscription after the deloyment. In the SNS subscription which is created, the URL is stored without encryption. Probably, this is ok. However, if this is considered as a security risk, you could create a lambda subscription for the SNS topic. In the lambda, you can read the secret value from Secrets Manager and call the target URL from the secret.

**Comment by JerryBLi** [comment]
@jumic That worked! Thanks for the input!
