### ISSUE TITLE
Move Existing Stack Code to CdkPipeline Stage Creates Duplicate Resources

### ISSUE THREAD

**Issue by matthew-valenti** [aws/aws-cdk#15490]
I have a CDK app with multiple stacks (Cognito, Aurora/MySQL, AppSync, etc). These stacks have been deployed manually using the CLI e.g. `cdk deploy CognitoStack` A `cdk list` shows the following stacks:
CognitoStack
MySqlStack
AppSyncStack

Now I want to deploy all stacks via CI/CD using CdkPipeline. Following the docs, I simply move these stacks into a cdk application stage. Now when I do a `cdk list` I see the following stacks:
CdkPipelineStack/CognitoStack
CdkPipelineStack/MySqlStack
CdkPipelineStack/AppSyncStack

The cdk pipeline runs successfully but has created a duplicate of each resource (and duplicate of each CloudFormation stack). It's okay to delete some of the original resources e.g. AppSync. But the original Cognito cannot be deleted and re-created (or userpool information will be lost). Backing up and restoring MySQL seems tedious.

I would expect the CDK to know these resources already exist and not re-create them (since no actual stack code has been changed).

### Reproduction Steps

1. Create a simple CDK app with one stack.
2. Deploy the stack. Code example below creates an AppSync api.
3. Add a CDK pipeline stack.
4. Move the stack to the CDK pipeline stage.
5. When the CDK pipeline runs it will create a duplicate AppSync api resource. i.e. the AWS account will contain two AppSync apis.

Create CDK app with one stack:
```
// cdk.ts
import * as cdk from '@aws-cdk/core';
import ApiStack from '../api-stack';

new ApiStack(app, 'ApiStack', {});
```

```
// api-stack.ts
import * as cdk from '@aws-cdk/core';
import * as appsync from '@aws-cdk/aws-appsync';

export default class ApiStack extends cdk.Stack {
    constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
        super(scope, id, props);
        
        new appsync.GraphqlApi(this, 'api', {
            name: 'api',
            schema: appsync.Schema.fromAsset('./schema.graphql')
        });
    }
}
```

Move stack to CDK pipeline stage.

```
// cdk.ts
import * as cdk from '@aws-cdk/core';
import { CdkPipelineStack } from './cdk-matthew-pipeline-stack';

const app = new cdk.App();
new CdkPipelineStack(app, 'CdkPipelineStack', {});

app.synth();
```

```
// cdk-pipeline-stack.ts
export class CdkPipelineStack extends cdk.Stack {
    constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
        super(scope, id, props);

        const sourceArtifact = new codepipeline.Artifact();
        const cloudAssemblyArtifact = new codepipeline.Artifact();

        const pipeline = new CdkPipeline(this, 'Pipeline', {
            selfMutating: true,
            pipelineName: 'CdkPipelineStack',
            cloudAssemblyArtifact,

            sourceAction: new codepipelineActions.GitHubSourceAction({
                actionName: 'GitHub',
                output: sourceArtifact,
                oauthToken: cdk.SecretValue.secretsManager('my-github-token'),
                trigger: codepipelineActions.GitHubTrigger.POLL,
                owner: 'ParetoHealth',
                repo: 'xxx',
                branch: 'xxx'
            }),

            synthAction: SimpleSynthAction.standardNpmSynth({
                sourceArtifact,
                cloudAssemblyArtifact,
            }),
        });

        pipeline.addApplicationStage(new CdkApplicationStage(this, 'CdkApplicationStage',  props! ));
    }
}

class CdkApplicationStage extends cdk.Stage {
    constructor(scope: cdk.Construct, id: string, props: cdk.StackProps) {
        super(scope, id, props);

            new ApiStack(app, 'ApiStack', {});
    }
}
```

### What did you expect to happen?
CDK pipeline deploy to detect no changes (and not deploy duplicate resource).

### What actually happened?
A duplicate resource was created.

A duplicate resource was created and for resources such as Cognito it's not possible to delete the original resource (or migrate data).

### Environment

  - **CDK CLI Version  :** 1.112.0
  - **Framework Version:** 1.112.0
  - **Node.js Version:** 14.16.1
  - **OS               :** Windows 10
  - **Language (Version):** TypeScript (3.9.7)

### Other
Unable to find any reference to this problem or possible workarounds.

--- 

This is :bug: Bug Report

**Comment by AhmadDaoud** [comment]
I had the same issue (using Python) but worked around it by explicitly specifying passing **stack_name** argument when defining the stack:

```
stack_name = "cognitostack"
ApiStack(self, "stack-id", stack_name=stack_name)
```

**Comment by rix0rrr** [comment]
Yes exactly. If your stack names changed as part of putting them into Stages (which they probably will have) you need to force them back to the original names.

**Comment by matthew-valenti** [comment]
Interesting! Specifying an explicit stack name does resolve this issue. However, it also results in a bit of unexpected behavior.

CloudFormation in the console displays the specified stack name e.g. CognitoStack
But `cdk list` displays the long stack name: CdkPipelineStack/CdkApplicationStage/CognitoStack

`cdk deploy CognitoStack` seems to run stack code. e.g. adding console.log statement outputs to terminal. However, it does not deploy the stack. `cdk deploy CdkPipelineStack/CdkApplicationStage/CognitoStack` does successfully deploy the stack.
