### ISSUE TITLE
context lookups should have an option to force a new lookup and not cache.

### ISSUE THREAD

**Issue by mrpackethead** [aws/aws-cdk#15498]
Context lookups in some cases SHOULD have caching disabled.  ( and in many cases they should be cached ).  I am requesting that an option be added so that you can if you want disable caching, so a new lookup is completed each time a synth is done. 

### Use Case

My specific use case ( this time ) is that i am building a app, that uses ec2imagebuilder to produce new golden AMI's based on the latest AL2 and Windows AMI's..      In this case, the entire point is to get the lastest image, everytime!     

This is not an argument that caching and deterministic builds are bad,  but there are edge cases when they are not appropriate. 

### Proposed Solution

amzn_linux = ec2.MachineImage.latest_amazon_linux(
    generation=ec2.AmazonLinuxGeneration.AMAZON_LINUX,
    edition=ec2.AmazonLinuxEdition.STANDARD,
    virtualization=ec2.AmazonLinuxVirt.HVM,
    storage=ec2.AmazonLinuxStorage.GENERAL_PURPOSE,
    cpu_type=ec2.AmazonLinuxCpuType.X86_64
    do_not_cache = True
)

This is a :rocket: Feature Request

**Comment by peterwoodworth** [comment]
Hey @mrpackethead 

Thanks for this feature request! Are you aware you can currently [manage your context information?](https://docs.aws.amazon.com/cdk/latest/guide/context.html#context_viewing) 

Do you have a use case where forcing the CDK to not cache works and the current functionality doesn't?

**Comment by rix0rrr** [comment]
I believe `latest_amazon_linux` is by default not cached (which is why it's called `latest`) -- it uses an SSM parameter lookup which will be looked up at every CFN deployment.

Poorly chosen example perhaps?
