### ISSUE TITLE
(aws-apigateway): response_parameters param of MethodResponse class doesn't add header to Response Headers

### ISSUE THREAD

**Issue by BielosX** [aws/aws-cdk#15493]
Hello, i use Api Gateway RestApi and i want to add integration response header mapping. When i use `method_responses` param and define response only `statusCode` is applied. When i check the mapping in AWS Console the `Response Headers` list is empty and my integration doesn't work. When i add this header manually it starts working.
Also when i change `response_parameters` property of my object passed to `method_responses` (for example when i add second header) and use `cdk deploy` my stack doesn't change.

### Reproduction Steps

```python

from aws_cdk import core as cdk
from aws_cdk import aws_apigateway as api_gateway
from aws_cdk import aws_s3 as s3
from aws_cdk import aws_iam as iam


class ApiGwTestStack(cdk.Stack):

    def __init__(self, scope: cdk.Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        api = api_gateway.RestApi(self, "demo-api")

        web_bucket = s3.Bucket(self, "WebsiteBucket",
            public_read_access=True,
            website_index_document="index.html")

        s3_access_role = iam.Role(self, "S3AccessRole",
            assumed_by=iam.ServicePrincipal('apigateway.amazonaws.com'),
            managed_policies=[
                iam.ManagedPolicy.from_aws_managed_policy_name('AmazonS3ReadOnlyAccess')
            ]
        )

        api.root.add_method("GET", api_gateway.AwsIntegration(
            service="s3",
            integration_http_method='GET',
            path="{}/{}".format(web_bucket.bucket_name, "index.html"),
            options={
                'credentials_role': s3_access_role,
                'integration_responses': [
                    {
                        'statusCode': "200",
                        'response_parameters': {
                            'method.response.header.Content-Type': 'integration.response.header.Content-Type'
                        }
                    }
                ]
            }),
            method_responses=[
                {
                    'statusCode': "200",
                    'response_parameters': {
                        'method.response.header.Content-Type': True
                    }
                }
            ],
        )

```

### What did you expect to happen?

Headers listed in objects provided to `method_responses` should appear on the list in AWS Console. Adding more headers shoud affect stack changes. As the bucket returns `index.html` with `Content-Type: text/html` API Gateway should also return this resource with `text/html` but return header is `Content-Type: application/json`.

### What actually happened?

No headers listed. Adding more headers to `response_parameters` doesn't change deployed API.
Returned header is `Content-Type: application/json` even though S3 bucket returns `text/html`.

### Environment

  - **CDK CLI Version  : 1.110.0 (build 32f00eb)**
  - **Framework Version: 1.112.0**
  - **Node.js Version: v16.4.2** 
  - **OS               : Arch Linux 5.12.14-arch1-1**
  - **Language (Version): Python (3.9.6)** 

### Other

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
Can you provide the `AWS::ApiGateway::Method` resources from the synthesized CloudFormation template?

**Comment by peterwoodworth** [comment]
Please ping me with the requested information if you'd like us to continue to investigate this issue. Closing for now
