### ISSUE TITLE
(aws-apigateway): Python IntegrationResponse and MethodResponse status_code error

### ISSUE THREAD

**Issue by BielosX** [aws/aws-cdk#15492]
https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_apigateway/MethodResponse.html#aws_cdk.aws_apigateway.MethodResponse
https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_apigateway/IntegrationResponse.html#aws_cdk.aws_apigateway.IntegrationResponse

Documentation says that parameter is called `status_code` but when i use it i get:
`jsii.errors.JSIIError: Missing required properties for @aws-cdk/aws-apigateway.IntegrationResponse: statusCode`

`jsii.errors.JSIIError: Missing required properties for @aws-cdk/aws-apigateway.MethodResponse: statusCode`

when i change the parameter to `statusCode` it works fine.

---

This is a 📕 documentation issue

**Comment by nija-at** [comment]
Reassigning to @RomainMuller for investigation.

**Comment by rix0rrr** [comment]
I'm pretty sure you used dictionaries and not the recommended form of the code here:

```py
method_response = apigateway.MethodResponse(
    status_code="statusCode",

    # the properties below are optional
    response_models={
        "response_models_key": model
    },
    response_parameters={
        "response_parameters_key": False
    }
)
```

Closing, please create a new issue if I'm wrong.
