### ISSUE TITLE
(cdk-build-tools): Add a watch mode for cdk-test

### ISSUE THREAD

**Issue by douglasnaphas** [aws/aws-cdk#15491]
Add the ability to pass `--watch` to Jest when running `cdk-test`.

### Use Case

I want to keep tests running in [watch mode](https://jestjs.io/docs/cli#--watch) while working on a change.

### Proposed Solution

Add a script similar to [cdk-watch](https://github.com/aws/aws-cdk/blob/aa1d229ddfa15d6229befa7ba37944feba1a5571/tools/cdk-build-tools/bin/cdk-watch.ts), or add `--watch` as an option to `cdk-test`.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
I don't think we'll likely add this. You can run `jest` directly like

```
../../../tools/cdk-build-tools/node_modules/.bin/jest --watch
```
