### ISSUE TITLE
Dependency housekeeping

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#155]
We need a robust way to housekeep our upstream dependencies. At the moment we are doing some weekly manual updates as described in our [contributing] guide, but we should obvsiouly automate this and also make sure to include regular major version updates some how.

We should also consider solutions such as [Greenkeeper] or [Renovate].

[contributing]: https://github.com/awslabs/aws-cdk/blob/master/CONTRIBUTING.md#updating-all-dependencies
[Greenkeeper]: https://greenkeeper.io/
[Renovate]: https://renovatebot.com/

**Comment by skinny85** [comment]
Can we close this, now that dependabot is running? :)
