### ISSUE TITLE
(aws-kinesisfirehose): Elasticsearch destination for DeliveryStream

### ISSUE THREAD

**Issue by madeline-k** [aws/aws-cdk#15504]
### Use Case
Specifying an Elasticsearch domain destination in CloudFormation or with L1 constructs is very complex, this should be included in the L2 to make it easier for users.

### Proposed Solution

See [RFC 340: Kinesis Firehose Delivery Stream](https://github.com/aws/aws-cdk-rfcs/pull/342)

And [this branch with the prototype](https://github.com/madeline-k/aws-cdk/tree/madeline-k/feat/kinesisfirehose-l2)

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by eugene-screenmeet** [comment]
+1 for expediting this
