### ISSUE TITLE
(CloudTrail): add conditions to service principal trust statement

### ISSUE THREAD

**Issue by biffgaut** [aws/aws-cdk#15515]
Implement a security enhancement to better address Confused Deputy concerns when setting up CloudTrail. CloudTrail has recently been updated to include headers for aws:SourceAccount and aws:SourceArn. Adding conditions in policies that check for one or both of these values in the Bucket Policy ensures that calls from cloudtrail.amazonaws.com are originating from the expected source - avoiding any Confused Deputy issues.

### Use Case

We have an internal AWS project built on CDK that is now being flagged by a new rule checking for this issue. We could write code that adds these conditions after the CDK call, but we don't really want to write code we will have to "unwrite" if this feature is implemented at the CDK level.

### Proposed Solution

This code:

```
this.cloudtrail = new cloudtrail.Trail(this, 'S3EventsTrail', {
        bucket: this.cloudtrailBucket
      });
```

currently creates a policy statements like this:

```
[
  {
    "Action": "s3:GetBucketAcl",
    "Effect": "Allow",
    "Principal": {
      "Service": "cloudtrail.amazonaws.com"
    },
    "Resource": {
      "Fn::GetAtt": [
        "myBucket",
        "Arn"
      ]
    }
  },
  {
    "Action": "s3:PutObject",
    "Condition": {
      "StringEquals": {
        "s3:x-amz-acl": "bucket-owner-full-control"
      }
    },
    "Effect": "Allow",
    "Principal": {
      "Service": "cloudtrail.amazonaws.com"
    },
    "Resource": {
      "Fn::Join": [
        "",
        [
          {
            "Fn::GetAtt": [
              "myBucket",
              "Arn"
            ]
          },
          "/AWSLogs/",
          {
            "Ref": "AWS::AccountId"
          },
          "/*"
        ]
      ]
    }
  }
]
```

The requested change would add a check of aws:SourceArn and/or aws:SourceAccount to the policy, like this:

```
[
  {
    "Action": "s3:GetBucketAcl",
    "Effect": "Allow",
    "Principal": {
      "Service": "cloudtrail.amazonaws.com"
    },
    "Resource": {
      "Fn::GetAtt": [
        "myBucket",
        "Arn"
      ]
    },
    "Condition": {
      "StringEquals": {
        "aws:SourceAccount": "123456789012",
        "aws:SourceArn": "arn:aws:acm:us-east-1:123456789012:certificate/12345678-1234-1234-1234-123456789012"
      }
    }
  },
  {
    "Action": "s3:PutObject",
    "Condition": {
      "StringEquals": {
        "s3:x-amz-acl": "bucket-owner-full-control",
        "aws:SourceAccount": "123456789012",
        "aws:SourceArn": "arn:aws:acm:us-east-1:123456789012:certificate/12345678-1234-1234-1234-123456789012"
      }
    },
    "Effect": "Allow",
    "Principal": {
      "Service": "cloudtrail.amazonaws.com"
    },
    "Resource": {
      "Fn::Join": [
        "",
        [
          {
            "Fn::GetAtt": [
              "myBucket",
              "Arn"
            ]
          },
          "/AWSLogs/",
          {
            "Ref": "AWS::AccountId"
          },
          "/*"
        ]
      ]
    }
  }
]
```

As determining the specific resource adding to the CloudTrail logs would be problematic, I would just check the account ID (that would address the issue tagged to our project :-) 

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by biffgaut** [comment]
We just got an additional message on the ticket flagging this issue saying the ticket would be auto-resolved and any changes should be removed as the service does not support these headers yet, but a new ticket would be opened in the coming weeks when the service implements this support. I guess we can leave this issue open for when that occurs or let it close and reopen it when that occcurs.

**Comment by rix0rrr** [comment]
Sounds like if we implement a fix for it today, it would not work (so we cannot test it) and in fact if we accidentally release it everyone would be broken.

So let's close until CloudTrail actually implements those features?

It's kind of tricky though -- how is the CDK supposed to know from which accounts you are expecting to receive events? That information is not anywhere, and it's not safe to assume it's *just* the current account.

**Comment by rix0rrr** [comment]
Ah well I suppose we ARE already restricting to a single account's prefix, so we can just assume it's that account.

**Comment by biffgaut** [comment]
Closing this for the time being is OK with me.

**Comment by NGL321** [comment]
Closing as discussed until CloudTrail implements features! Please feel free to reopen as soon as they are added
