### ISSUE TITLE
Setup Cross Account Delegation for existing PublicHostedZone

### ISSUE THREAD

**Issue by reidca** [aws/aws-cdk#15513]
### The Question
I have an existing Route53 Public hosted zone in a root AWS account that was created outside of CDK. 
Let's call this mycompany.com

I want to create a new sub-domain called data.mycompany.com and delegate this to a child account

I am aware this requires the hosted zone to be created in the child account and for the nameserver records in the parent hostedzone to point at the new delegate zone.

I can see in the constructor for PublicHostedZone (https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-route53.PublicHostedZone.html)  there is an option to create a principal to allow cross account delegation using crossAccountZoneDelegationPrincipal property in the constructor.

However since this hosted zone already exists I cannot use this constructor and instead must use the static method "fromLookup" which returns an IPublicHostedZone

This interface does not have any properties or methods for creating the cross account principal.

Therefore my question is, how can I add cross account delegation support for an existing public hosted zone?

### Environment

  - **CDK CLI Version:** CDK Version: 1.112.0 (build 2815a44)
  - **Module Version:**  "@aws-cdk/aws-route53": "^1.112.0",
  - **Node.js Version:**  v16.2.0
  - **OS:**  Ubuntu 18.04
  - **Language:** TypeScript

**Comment by peterwoodworth** [comment]
Thanks for submitting this question and providing all the detail! But unfortunately, I don't believe you're able to accomplish this with the CDK. According to [our documentation:](https://docs.aws.amazon.com/cdk/latest/guide/resources.html#resources_importing)
> Although you can use an imported resource anywhere, you cannot modify the imported resource.
I'll research this a bit more tomorrow to see for certain, but I'm not hopeful

**Comment by reidca** [comment]
Thanks for the reply Peter.

I guess in this case I am not trying to modify the resource so much as creating a cross account role that has permission to write name server records into it. There are no properties of the actual resource that change.

I am expecting the role to be created and then the sub domain will write data into it.

Seems to me that should be possible right?

I am sure there will be many people who are inheriting an existing hosted zone that could benefit from this pattern since its likely that root hosted zones will already exist.

If you do find out anything I'd appreciate it.

Cheers

Carl

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by McDoit** [comment]
Hello, i guess you can create your own setup of ns records using AwsCustomResource?
I added a property for a RoleArn to be assumed by the customresource, that would allow you to modify the parent HZ to add the subdomain

**Comment by reidca** [comment]
Yeah I guess that's an option, is your custom resource on GitHub?

 I was looking for something built in to CDK really. It's an odd one as I liken Route53 to a database and therefore believe that the ability to add entries into the database should not be restricted to only on creation.

**Comment by McDoit** [comment]
Its in the CDK project, a bit information in this PR:
https://github.com/aws/aws-cdk/issues/13915

**Comment by peterwoodworth** [comment]
So if all it's doing is creating a role, couldn't you create that role yourself using the [iam.Role](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-iam.Role.html) construct? After all, that's all the source code is doing in the constructor for PublicHostedZone

https://github.com/aws/aws-cdk/blob/d04661d5b0f8ce6de7af5b95b2d9aff7afcc998a/packages/%40aws-cdk/aws-route53/lib/hosted-zone.ts#L258-L276
