### ISSUE TITLE
(cli): stackName can no longer be used to refer to stacks

### ISSUE THREAD

**Issue by gmokki** [aws/aws-cdk#15510]
cdk 1.102.0 broke referring to stacks by stackName when using wildcards. I know this will change in 2.x version, but we are now stuck at older release that still works with our build script.

### Reproduction Steps

```js
import cdk = require('@aws-cdk/core');

class BugStack1 extends cdk.Stack {
  constructor(app: cdk.App, id: string, props: cdk.StackProps) {
    super(app, id, props);
  }
}
class BugStack2 extends cdk.Stack {
  constructor(app: cdk.App, id: string, props: cdk.StackProps) {
    super(app, id, props);
  }
}

const app = new cdk.App();
new BugStack1(app, 'BugStack1', { stackName: 'bug1-stack' });
new BugStack2(app, 'BugStack2', { stackName: 'bug2-stack' });
app.synth();
```

The example assumes package.json tsconfig.json and cdk.json are copied from here: https://github.com/aws-samples/aws-cdk-examples/tree/master/typescript/application-load-balancer

### What did you expect to happen?

```sh
$ cdk diff 'bug*-stack'
<no output>
```

### What actually happened?

Referring by exact stackName still works:
```sh
$ cdk diff 'bug1-stack'
Selecting stack by identifier "bug1-stack". This identifier is deprecated and will be removed in v2. Please use "BugStack1" instead.
Run "cdk ls" to see a list of all stack identifiers
Stack bug1-stack
```

And referring to stack id works with wild cards:
```sh
$ cdk diff 'BugStack*'
Stack bug1-stack
Stack bug2-stack
```

### Environment

  - **CDK CLI Version  : 1.102.0 ... 1.112.0**
  - **Language (Version):** TypeScript

### Other

Background, we use a stackName format of `[projectPrefix]-[phase]-[name]` for our stackName. The stack id has been human readable version, basically just the name of the stack. Where phase defines if the stack is account level `1` (= shared between feature branches) or feature branch level stack `2` (= duplicated for each feature branch). So we can just clean up an feature development environment by running `cdk destroy prefix-2`, without needing to know what stacks they used.

We also considered that we could write a wrapper that lists the stackNames, does manually the wildcard matching and runs the cdk command with the stack identifier values. But the cdk has no usable output that lists both stack identifeirs and stackName values. 1.102 `cdk ls` lists only stack identifiers, And `cdk ls --long` only lists stackNames, maybe that latter one is another bug?
It outputs
```sh
$ cdk ls -l
- id: bug1-stack
  name: bug1-stack
  environment:
    account: unknown-account
- id: bug2-stack
  name: bug2-stack
  environment:
    account: unknown-account
```

Should both the `id` and `name` field have the same stackName value`

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
The recommended stack selectors are based on the construct path. So you could put your hierarchy into a construct tree and select that way, perhaps into a `Stage`:

```ts
class MyStage {
  constructor() {
    new Stack1(this, '...');
    new Stack2(this, '...');
  }
}


new MyStage(app, 'Stage-1');
```

You can now do:

```ts
cdk de{pl,str}oy Stage-1/*
```

**Comment by rix0rrr** [comment]
Stack names will automatically include parent stage names, if not overridden.
