### ISSUE TITLE
EKS Fargate: Unable to create VPC

### ISSUE THREAD

**Issue by evmartinelli** [aws/aws-cdk#15518]
Im trying to create a simple VPC to use with EKS Fargate service, but im getting error. Could anyone help me, please?

### Environment

  - **CDK CLI Version:1.113.0
  - **Module Version:1.110.1
  - **Node.js Version:16.4.1
  - **OS:** osx
  - **Language (Version): TypeScript (3.8.3)

Code:
`const vpc = new ec2.Vpc(this, "MyVpc", {
      maxAzs: 3 // Default is all AZs in region
    });

    const cluster = new eks.FargateCluster(this, "MyCluster", {
      version: eks.KubernetesVersion.V1_20,
      vpc: vpc
    });`

Error:
 Type 'import("path/node_modules/@aws-cdk/aws-ec2/lib/vpc").IVpc' is not assignable to type 'import("path/node_modules/@aws-cdk/aws-autoscaling/node_modules/@aws-cdk/aws-ec2/lib/vpc").IVpc'.
  Types of property 'publicSubnets' are incompatible.
    Type 'import("path/node_modules/@aws-cdk/aws-ec2/lib/vpc").ISubnet[]' is not assignable to type 'import("path/node_modules/@aws-cdk/aws-autoscaling/node_modules/@aws-cdk/aws-ec2/lib/vpc").ISubnet[]'.

16       vpc,
         ~~~

  node_modules/@aws-cdk/aws-eks/lib/cluster.d.ts:332:14
    332     readonly vpc?: ec2.IVpc;
                     ~~~
    The expected type comes from property 'vpc' which is declared here on type 'ClusterProps'

lib/eks-stack.ts:26:7 - error TS2322: Type 'Vpc' is not assignable to type 'IVpc'.
  Types of property 'publicSubnets' are incompatible.
    Type 'import("/node_modules/@aws-cdk/aws-ec2/lib/vpc").ISubnet[]' is not assignable to type 'import("/node_modules/@aws-cdk/aws-autoscaling/node_modules/@aws-cdk/aws-ec2/lib/vpc").ISubnet[]'.
      Type 'import("/node_modules/@aws-cdk/aws-ec2/lib/vpc").ISubnet' is not assignable to type 'import("/node_modules/@aws-cdk/aws-autoscaling/node_modules/@aws-cdk/aws-ec2/lib/vpc").ISubnet'.
        Types of property 'associateNetworkAcl' are incompatible.
          Type '(id: string, acl: import("node_modules/@aws-cdk/aws-ec2/lib/network-acl").INetworkAcl) => void' is not assignable to type '(id: string, acl: import("/node_modules/@aws-cdk/aws-autoscaling/node_modules/@aws-cdk/aws-ec2/lib/network-acl").INetworkAcl) => void'.
            Types of parameters 'acl' and 'acl' are incompatible.
              Type 'import("node_modules/@aws-cdk/aws-autoscaling/node_modules/@aws-cdk/aws-ec2/lib/network-acl").INetworkAcl' is not assignable to type 'import(node_modules/@aws-cdk/aws-ec2/lib/network-acl").INetworkAcl'.
                The types of 'addEntry(...).stack.tags' are incompatible between these types.
                  Type 'import("/node_modules/@aws-cdk/core/lib/tag-manager").TagManager' is not assignable to type 'import("node_modules/@aws-cdk/aws-events/node_modules/@aws-cdk/core/lib/tag-manager").TagManager'.
                    Types have separate declarations of a private property 'tags'.

26       vpc: vpc
         ~~~

  node_modules/@aws-cdk/aws-eks/lib/cluster.d.ts:332:14
    332     readonly vpc?: ec2.IVpc;
                     ~~~
    The expected type comes from property 'vpc' which is declared here on type 'FargateClusterProps'

Found 2 errors.

**Comment by otaviomacedo** [comment]
Hi, @evmartinelli

Please make sure that all CDK dependencies in your `package.json` file have the same version.

**Comment by evmartinelli** [comment]
Hello, @otaviomacedo 

Worked! Thank you!!
All dependecies except eks (1.113.0) was 1.111.0.

See you!
