### ISSUE TITLE
(npm install): npm install CANNOT fetch package behind proxy or corporate artifactory

### ISSUE THREAD

**Issue by cqcmdwym** [aws/aws-cdk#15522]
## :question: General Issue
Since published aws-cdk include npm-shrinkwrap.json file(will be published by default, package-lock.json not), if we are behind a proxy or corporate artifactory(will block public yarn/npm) or we have no packages cached, npm install will fail. 

### Environment

  - **CDK CLI Version:** v1
  - **Module Version:** 
  - **Node.js Version:** v12.18.3
  - **OS:** all
  - **Language (Version):** ts/js

**Comment by peterwoodworth** [comment]
Hey @cqcmdwym, sorry you're running into this issue. Are you looking for help in working around this?

**Comment by cqcmdwym** [comment]
I have a workaround in temp.
1. delete package-lock.json and set package-lock=false in .npmrc
2. npm install
3. set package-lock=true in .npmrc
4. npm install

Seems will not use the hardcoded public yarn repo url in npm-shrinkwrap.json.

Is there any reason for keep npm-shrinkwrap.json in published package? Thanks.

**Comment by cqcmdwym** [comment]
Hi @peterwoodworth is there any update on it? Thanks.

**Comment by ryparker** [comment]
Hey @cqcmdwym I'd be happy to help, however I'm having trouble understanding what you are trying to achieve.

Could you provide the error you're seeing when running `npm install`?

It sounds like you're wanting to delete the `package-lock.json` so that NPM uses `npm-shrinkwrap.json` however according to NPM's docs this should be the default behavior:

> If both package-lock.json and npm-shrinkwrap.json are present in the root of a package, package-lock.json will be completely ignored.

https://docs.npmjs.com/cli/v6/configuring-npm/package-lock-json#description

**Comment by cqcmdwym** [comment]
@ryparker , not really.
Since the published package has a npm-shrinkwrap.json which point to public yarn repo, behind corporate proxy corporate artifactory, we couldn't fetch packages hard coded pointing to public yarn.
Always download package timeout.

**Comment by peterwoodworth** [comment]
[The readme here](https://github.com/aws/aws-cdk/blob/7966f8d48c4bff26beb22856d289f9d0c7e7081d/tools/yarn-cling/README.md) states why we publish an npm shrinkwrap file. In short, it is for the user's safety from installing malware or installing untested, potentially broken versions of packages. If you're willing to take these risks on, feel free 😄 

Let me know if you have any additional questions.

**Comment by cqcmdwym** [comment]
@peterwoodworth It make sense to protect user's safety, but we cannot directly successfully `npm install` if our project has a .npmrc file pointing to corporate artifactory.  And it always fails to download the packages whose url points to public npm/yarn.

**Comment by peterwoodworth** [comment]
I'm sorry, I thought you just wanted an explanation for why we have the shrinkwrap file. I thought you have a workaround for this, are you blocked?

I'm not sure exactly what you need from us here. Do you think that we should be doing something differently with the shrinkwrap generation?

**Comment by cqcmdwym** [comment]
@peterwoodworth Thanks for your reply.
Perhaps I just want to get some straightforward ways to download the npm packages instead of workaround because I guess not only me is forced to use corporate artifactory.
Thanks again.

**Comment by peterwoodworth** [comment]
I'm honestly not familiar with this, so I'm sorry but I will be unable to help you find a better workaround. Maybe @rix0rrr is familiar with fetching public packages behind a proxy

This isn't specifically a CDK issue so Im going to leave it closed, given that we want the shrinkwrap. If you know of any ways to make the shrinkwrap friendly to users behind proxies please let me know

**Comment by cqcmdwym** [comment]
Since npm-shrinkwrap.json has point to **https://registry.yarnpkg.com**, however due to some issue, 'https://registry.yarnpkg.com' has been blocked after corp proxy. So when we run npm install or yarn we could not fetch those packages with 'https://registry.yarnpkg.com' which causing install failure. 
Is there any easy way can make install successfully, thanks? @peterwoodworth @rix0rrr
