### ISSUE TITLE
(aws-cdk): "cdk bootstrap" to upgrade from v6 to v7 result of CDKPipeline Failure with S3 Access Denied 

### ISSUE THREAD

**Issue by Pandafriendd** [aws/aws-cdk#15525]
### Reproduction Steps

Following the [CDK Workshop for CDKPipeline](https://cdkworkshop.com/20-typescript/70-advanced-topics/200-pipelines.html). With the latest version of bootstrap template (`v7`), in the `CHANGE_SET_REPLACE` action of deployment stage, it failed with error `Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied;`

### What did you expect to happen?

The deployment stage should be successful when setting up something similar as [CDK Workshop for CDKPipeline](https://cdkworkshop.com/20-typescript/70-advanced-topics/200-pipelines.html).

### What actually happened?

This error was due to the deployment action role (`DeploymentActionRole`) in the [v7 bootstrap template](https://github.com/aws/aws-cdk/blob/master/packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml) seems doesn't have the correct S3 permissions, where the S3 permissions are only granted to the `StagingBucket` created by `CDKToolkit` and the trusted accounts. Due to this, the role cannot access the Pipeline artifact bucket needed by the CDKPipeline.

However, in `v6` the S3 permissions also granted to all buckets, allowing access to the Pipeline artifact bucket. 

I would expect the S3 permissions should be granted to the buckets in the same account where Pipeline executes, not only just the `StagingBucket`.

### Environment

  - **CDK CLI Version  :1.111
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):**  TypeScript

--- 

This is :bug: Bug Report

**Comment by crisboarna** [comment]
I am also encountering this issue, as well having the issue that any CodePipeline UpdatePipeline step fails with following error:

![CleanShot 2021-07-15 at 20 02 27](https://user-images.githubusercontent.com/12763781/125828383-61078c45-80bb-4688-850c-dd32af935b3c.png)

This is happening since 1.107.0 and I am unable to upgrade versions since as I have to use 1.106.0 to be able to run the pipelines.

**Comment by rix0rrr** [comment]
@Pandafriendd the permissions are supposed to be granted on the Bucket, **to** the `deploy-role`, so it's correct that you're not seeing them on the `deploy-role` itself. That is the whole point of the change of bootstrap template from v6 to v7.

If they are not added on the bucket, that might be

**Comment by rix0rrr** [comment]
@crisboarna I would have guessed you were running into this change https://github.com/aws/aws-cdk/pull/14969 which requires a rebootstrap with a more recent CLI version. However, that was not released in 1.107 (but in 1.109) so I'm confused there.

Have you tried investigating why the AssumeRole operation fails? The two places to look are:

* The  **assume role policy document** of the target role (`*-deploy-role-*-eu-west-1`).
* The **policies** of the source role (`PipelineUpdatePipelineSelf-*`).

Both of them should be allowing `sts:AssumeRole` from and to their respective peers.

**Comment by crisboarna** [comment]
@rix0rrr 
I have completely wiped the two environments CDKToolkit included, and have rebootstrapped with 1.114.0.

This is the error I get in the CodePipeline during the synth step with everything vanilla after CDK bootstrap.
![CleanShot 2021-07-16 at 16 04 38](https://user-images.githubusercontent.com/12763781/125952915-146880c5-1b75-46fc-a6cf-651252ac280c.png)

The `*-deploy-role-*` and the `PipelineUpdatePipelineSelf-*` as well as the `*-lookup-role-*` are created by the CDK itself and I should not have to modify them to ensure the pipelines work.

**Comment by crisboarna** [comment]
@rix0rrr 

I have performed a wipe of both environments and have then bootstrapped the two accounts, tool account(yellow) and dev account(red)(with --trust tool id) and am getting the following error:

![CleanShot 2021-07-17 at 06 38 29@2x](https://user-images.githubusercontent.com/12763781/126024368-1abf3759-94b9-4898-9174-0f4da15a4f63.png)

Upon investigating the IAM role and adding the sts:AssumeRole policy for the dev account, the UpdatePipeline task passed successfully.

![CleanShot 2021-07-17 at 06 42 53@2x](https://user-images.githubusercontent.com/12763781/126024427-9f8bca13-eb67-48e7-a250-5ec5c58bd568.png)

Am I missing a step or why is the role not populated with all the correct permissions ? I am using a CdkPipeline so this is auto-generated.

**Comment by crisboarna** [comment]
@rix0rrr I have also attempted to add this via `Aspects.of(this).add(...)` to add at the root pipeline stack level the addition of the `sts:AssumeRole` to the role but it seems that, unless I am doing something wrong, `aspects` do not work on the pipeline, only on stacks themselves :(

**Comment by rix0rrr** [comment]
I mean that is correct though. If your terminology is like this:

* `dev` account => where we are deploying the application
* `tool` account => where the pipeline lives

Then the SelfUpdate step should *not* be trying to make changes to the `dev` account (it's the pipeline living in the `tool` account deploying to the `tool` account).

So the fact that it's even trying to is mystifying to me.
