### ISSUE TITLE
Amazon.CDK.AWS.RDS: Add CopyTagsToSnapshot Property to Class InstanceProps

### ISSUE THREAD

**Issue by mickgortenmulder** [aws/aws-cdk#15521]
We're using the DatabaseCluster Class in the C# library (Amazon.CDK.AWS.RDS) which implements DatabaseClusterProps where we use the InstanceProps propery to set properties for database instances on the DatabaseCluster.

We've seen that the CopyTagsToSnapshot property is added to the libraries, however it's not yet available in the InstanceProps.

I'd like the new property CopyTagsToSnapshot to be added to the InstanceProps: https://docs.aws.amazon.com/cdk/api/latest/dotnet/api/Amazon.CDK.AWS.RDS.InstanceProps.html

### Use Case
We would like to add the property CopyTagsToSnapshot to the DB Cluster to all Instances so it copies the tags to snapshots so in case of restores we don't have to set the tags ourselves.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by skinny85** [comment]
Thanks for opening the issue @mickgortenmulder! The fastest way to get this in would be to submit us a Pull Request adding this option - should be fairly straightforward! Here's our "Contributing guide": https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md.

Thanks,
Adam
