### ISSUE TITLE
(aws-stepfunctions): Support dynamic Task timeouts (TimeoutSecondsPath/HeartbeatSecondsPath)

### ISSUE THREAD

**Issue by wong-a** [aws/aws-cdk#15531]
Amazon States Language supports dynamic Task state timeout and heartbeat configurations by the `TimeoutSecondsPath` and `HeartbeatSecondsPath` properties respectively. `TimeoutSecondsPath` has the same effect as `TimeoutSeconds` but reads the seconds value at runtime from the state input using JSONPath. This is not supported in CDK without a CustomState.

- https://docs.aws.amazon.com/step-functions/latest/dg/amazon-states-language-task-state.html
- https://states-language.net/spec.html#task-state

### Use Case

Allows CDK users to specify Task state timeout and heartbeat settings at runtime instead of hardcoding static values in the state machine definition.

### Proposed Solution

* Option 1 - Expose explicit `timeoutPath` and `heartbeatPath` in [TaskBaseProps](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-stepfunctions/lib/states/task-base.ts)

```javaScript
const myTask = new EcsRunTask(scope, "MyTask", {
    ...
    timeoutPath: JsonPath.numberAt("$.myTimeoutInSeconds")
    ...
});

// OR

const myTask = new EcsRunTask(scope, "MyTask", {
    ...
    timeoutPath: "$.myTimeoutInSeconds"
    ...
});
```

* Option 2 - Use the existing `timeout` and `heartbeat` properties and append "Path" to the generated ASL if the provided value is JSONPath, similar to how Parameters works in [json-path.ts](https://github.com/aws/aws-cdk/blob/94f81c441f9e2cb8dc70eb2e772d2cd75e468b67/packages/%40aws-cdk/aws-stepfunctions/lib/json-path.ts)

```javaScript
const myTask = new EcsRunTask(scope, "MyTask", {
    ...
    timeout: JsonPath.numberAt("$.myTimeoutInSeconds")
    ...
});
```

Both would render the same ASL:

```json
{
  "Type": "Task",
  "Resource": "...",
  ...
  "TimeoutSecondsPath": "$.myTimeoutInSeconds",
  ...
}
```

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by BenChaimberg** [comment]
Workaround (can extend any current task integration that extends sfn.TaskStateBase):
```ts
class TaskWithTimeoutSecondsPath extends sfn.TaskStateBase {
  protected readonly taskMetrics?: sfn.TaskMetricsConfig;
  protected readonly taskPolicies?: iam.PolicyStatement[];
  protected _renderTask(): any {
    return {};
  }
  public toStateJson(): object {
    const underlyingJson = super.toStateJson();
    return {
      ...underlyingJson,
      TimeoutSecondsPath: '$.myTimeoutSecondsPath',
    };
  }
}
```

**Comment by BenChaimberg** [comment]
Option 1 would be nice but we'd have to add a new property anyway to avoid breaking existing subclasses and the workaround to support jsii would be annoying. Leaning towards option 2

**Comment by BenChaimberg** [comment]
I am unassigning myself as it is not in my short-term work queue, but please respond here if you want to discuss further. And, of course, please feel free to work on this issue yourself and request my review if you submit a PR or would like design help! See [CONTRIBUTING.md](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) for guidelines.

**Comment by natenez** [comment]
+1 on this feature request.  I am developing a new step function and need to use the heartbeatPath since a compile time heartbeat isn't appropriate.  I'll give the work around a try until the feature is available.

**Comment by Serede** [comment]
> Workaround (can extend any current task integration that extends sfn.TaskStateBase):
> 
> ```ts
> class TaskWithTimeoutSecondsPath extends sfn.TaskStateBase {
>   protected readonly taskMetrics?: sfn.TaskMetricsConfig;
>   protected readonly taskPolicies?: iam.PolicyStatement[];
>   protected _renderTask(): any {
>     return {};
>   }
>   public toStateJson(): object {
>     const underlyingJson = super.toStateJson();
>     return {
>       ...underlyingJson,
>       TimeoutSecondsPath: '$.myTimeoutSecondsPath',
>     };
>   }
> }
> ```

I tried this for my particular case (extending `aws-stepfunctions-tasks.EcsRunTask`) and it messed up the stack dependencies so the CDK deployment broke and I had to rollback the changes.

Still in need of a working solution :/

**Comment by BenChaimberg** [comment]
@Serede can you be more specific about what broke when trying the workaround? From your description, it doesn't seem to be related to the example code provided.

**Comment by Serede** [comment]
@BenChaimberg Sure, I will DM you the details. That's probably easier.

**Comment by BenChaimberg** [comment]
Confirmed that the issue encountered by @Serede is unrelated to the workaround (construct IDs changed, leading to a change in logical IDs, leading to resource re-creation)

**Comment by Serede** [comment]
Just to clarify, the deployment error was indeed caused by the workaround. Thank you @BenChaimberg for updating it in the original comment.

**Comment by mzyil** [comment]
Here is a workaround that does not break the synth
```
  let renderer: any = LambdaInvoke.prototype["renderTaskBase"];
  LambdaInvoke.prototype["renderTaskBase"] = function () {
    let result = renderer.apply(this);
    let timeoutSecondsPath = (this as any)["timeoutSecondsPath"];
    if (timeoutSecondsPath) {
      result["TimeoutSecondsPath"] = timeoutSecondsPath;
    }
    return result;
  }
```
later 
```
(theStep as any)["timeoutSecondsPath"] = JsonPath.stringAt("$.somePath")
```

**Comment by ashterenberg-paramount** [comment]
We are looking for this feature - being able to dynamically define timeouts for ECS tasks (for example) would be very useful.
