### ISSUE TITLE
Prevent ec2 instance from bring recreated when using latest amazon linux 2 ami

### ISSUE THREAD

**Issue by shanecarey17** [aws/aws-cdk#15541]
### The Question

Using an ec2 instance in cdk (python) like so

```
self.instance = ec2.Instance(self, "my-instance",
             machine_image=ec2.AmazonLinuxImage(generation=ec2.AmazonLinuxGeneration.AMAZON_LINUX_2),
              ...
 )
```

will according to the documentation fetch the latest AMI from the SSM. The problem is, `cdk diff` will not show the diff when the latest version updates. Instead, it will show no diff and attempt to replace the instance on `cdk deploy`. This is pretty dangerous.  Is there a way to fetch the latest AMI on creation, but on subsequent `cdk deploy` operations do not update the instance?

My other alternative is to use the machine image name explicitly, but this is more difficult to manage since I need to look up the current AMI name.

```
machine_image=ec2.MachineImage.lookup(name='amzn2-ami-hvm-2.0.20210617.0-x86_64-gp2'),
```

### Environment

  - **CDK CLI Version:** 1.103.0 (build bc13a66) 
  - **Module Version:** aws-cdk.aws-ec2==1.103.0 
  - **Node.js Version:** n/a 
  - **OS:** all 
  - **Language:** Python

**Comment by madeline-k** [comment]
@shanecarey17 , As far as I know, there is not a way to use `generation=ec2.AmazonLinuxGeneration.AMAZON_LINUX_2` but then "lock in" your cdk stack on using the version that was there the first time you deployed your stack. 

One way to enforce that the image ID does not change for future deployments is to add unit tests to your CDK app that will fail if the ImageId property in your cloudformation template changes. This will prevent you from unintentionally replacing your EC2 instance on subsequent deployments. 

@njlynch, Leaving this issue open in case you have more recommendations for @shanecarey17.
