### ISSUE TITLE
Unable to assign multiple Security Groups to a Lambda Function

### ISSUE THREAD

**Issue by AdamBoxall** [aws/aws-cdk#1555]
Through the AWS Console it's possible to assign multiple Security Groups to one Lambda Function.

The `AWS::Lambda::Function` CFN spec also allows this through the [`VpcConfig` property](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-function-vpcconfig.html), which is correctly replicated in [CDK's L1 Lambda construct](https://awslabs.github.io/aws-cdk/refs/_aws-cdk_aws-lambda.html#@aws-cdk/aws-lambda.CfnFunctionProps.vpcConfig).

CDK's L2 Lambda construct however abstracts away the use of the `VpcConfig` property, and ultimately only provides the ability to assign a single Security Group to a Lambda Function, with no ability to override the property.

Therefore if you wish to assign multiple Security Groups you have to implement everything at the L1 construct level, which also of course means you can't use L2 (L3?) constructs like `SingletonFunction`.

Personally I don't think CDK should be _that_ opinionated about what developers do with AWS.

**Example use case:**

I work on a project that handles PII data in AWS and has very tight-knit security practises to follow.

We communicate with S3 and DynamoDB using VPC Gateway Endpoints, and have a Security Group created for each of those that whitelists outbound communication as needed.

If a lambda needs to communicate with either service, you can import the relevant Security Group and assign it to the resource; possibly in addition to another Security Group specific for its other needs.

Ordinarily you would just assign the relevant rules directly to the lambda's own Security Group, instead of importing a shared one, however CFN doesn't support fetching the "prefix lists" needed to do that (see [here](https://forums.aws.amazon.com/thread.jspa?threadID=215423) and [here](https://www.reddit.com/r/aws/comments/3x4bto/aws_help_cloudformation_security_groups_and_vpc/) for other people running into the same problem).

Instead, we export an empty Security Group in CDK and as part of our deployment pipeline we use the AWS CLI to apply the prefix list IDs to the shared Security Groups. It's a little bit hacky, but it's the only solution we found that still adheres to the security rules we have to follow.

Without being able to assign multiple Security Groups to a lambda though, it doesn't work.

**Comment by AdamBoxall** [comment]
Yeah you can add prefix list IDs through CFN/CFK, but you don't know what those IDs should be without calling [`describe-prefix-lists`](https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-prefix-lists.html).

**Comment by AdamBoxall** [comment]
The "prefix list" terminology is pretty poor really, and the lack of CFN support is quire surprising given it's in the nature of tighter security.

From what I've observed the prefix lists are shared per-region, so perhaps it's something to do with that. I'm sure they have their reasons for not implementing it.

**Comment by rix0rrr** [comment]
Aha, I see. Thanks for clarifying.

You could write a Lambda-backed Custom Resource to do that lookup in the mean time if you wanted to, but I'm not sure you want to go that way.

**Comment by AdamBoxall** [comment]
Thanks for the suggestion. I did consider using a Lambda-backed Custom Resource, however I'd have the same problem: the Lambda would need a Security Group that allows access to S3 via the VPC Gateway Endpoint, which means it needs to know the prefix list IDs. It's a chicken and egg type scenario.

Our security policy has given me some headaches over the last few months :D

**Comment by rix0rrr** [comment]
Do you need to be in a Security Group to call `describe-prefix-lists`?

**Comment by AdamBoxall** [comment]
That's called from our CI server using the AWS CLI. There's no PII data there so the rules are more relaxed.

**Comment by rix0rrr** [comment]
I see, so any Lambda in that account should only be able to access S3 and no other service, even if it doesn't actually need to touch the S3 bucket?

**Comment by AdamBoxall** [comment]
Lambdas (or any other resources) that **_need_** access to S3, must connect to it via the VPC Gateway Endpoint. On top of that, all Security Groups must have explicit egress rules.

For example Lambda-backed Custom Resources, which have to upload their completion status to S3, need access to S3 (obviously) and any other services the Lambda will hit doing whatever task it exists to do.

The egress rules needed would look something like these:

| Protocol | Port | Destination |
|----------|------|-------------|
| TCP | 443 | pl-123abcdef |
| TCP | 443 | 10.252.130.200/32 |
| TCP | 443 | 10.252.130.100/32 |

The first rule allowing access to S3, and the second and third allowing access to some made up HTTPS services.

It would be nice to have them all in one Security Group, but as getting hold of that "pl-123abcdef" ID is tricky, it's only written to one shared group when the VPC is spun up. The other two rules would make up the lambda's _own_ Security Group.

Hope that clears it up a bit better?

**Comment by rix0rrr** [comment]
Yes, I forgot that the Lambda need to post its result to S3, but of course it does.

My suggestion would have been to have `pl-123abcdef` be the output of the Custom Resource Lambda, but I see it's not allowed to run that Lambda outside the VPC.

**Comment by ashwgupt** [comment]
With the new Lambda architecture, it's advised to reuse the security groups across all lambdas in a VPC to reuse the ENI and save on cold start penalties that a Function sees in a VPC otherwise.

But while doing so, if the case like the one above has to be addressed i.e. to have one SG per service (one to allow to connect to Elasticsearch, another to RDS etc.) such that, one lambda can choose to use from the pre-existing SGs for appropriate access.

This can only happen when one can pass a list of existing SGs to the Function construct, and not letting CDK create a new dedicated SG, for particular use of the Lambda.

However the `lambda.Function()` from aws-lambda doesn't accept the list of SGs, that is otherwise accepted by AWS API.

@AdamBoxall  did you manage to solved this for your use case? Any inputs on this will be of great help.

**Comment by AdamBoxall** [comment]
@ashwgupt I believe I solved it by accessing the underlying resource (the L1 Lambda construct) and forcibly adding the extra Security Group there. Unfortunately though I'm quite far removed from CDK these days, so I can't say if that's still a viable solution.

**Comment by ashwgupt** [comment]
Oh! Okay.

@rix0rrr @nija-at @eladb is there any plans to match aws-cdk/aws-lambda with CFN and allow it to accept list of SGs instead? This gap is really going to cause adoption of CDK difficult for those running Lambda in VPC and hence get away from one SG per Lambda design.

**Comment by ashwgupt** [comment]
Guys, I also tried to use the `addSecurityGroup` method as below to add more security groups to the Lambda but this code doesn't seem to work. Any idea if I am doing anything wrong here?

```
this.lambdaFunction.connections.addSecurityGroup(...[
            ec2.SecurityGroup.fromSecurityGroupId(this, 'dw-lambda-sg', lambdaSGId),
        ]);
```

**Comment by ashwgupt** [comment]
I've worked on the Function class to make it start accepting a list of security groups, as an another optional parameter. Shall soon raise the PR for acceptance and merge.

**Comment by ashwgupt** [comment]
PR raised for it under #5049

**Comment by nija-at** [comment]
Fixed here - https://github.com/aws/aws-cdk/pull/5049
