### ISSUE TITLE
FullRepositoryId contains owner "AWS", branch could not be found

### ISSUE THREAD

**Issue by uxth** [aws/aws-cdk#15559]
Hello,

I met this bug when using codepipeline to download source code and build.

in the code pipeline, I have used CodeStarConnectionsSourceAction for source code stage, in which it will ask for owner and repo.
the owner is AWS, the repo is my repo name. and the branch I set to master
but after deploying it, it could not find the branch for my repo.

after download the json schema of my pipeline, I found this:
in the json, there is a field named "FullRepositoryId", which is composed as the owner + repo name.

I believe this is the issue, because when I removed the "AWS" in FullRepositoryId, and update the pipeline, it works.

The issue is that both owner and repo are mandatory for the CodeStarConnectionsSourceAction, and it will combine the owner and repo name to FullRepositoryId, which caused the error.

Could you help me to solve this?

Thanks,

### Reproduction Steps

build a code pipeline using CodeStarConnectionsSourceAction, give owner and repo name. deploy it, it will fail

### What did you expect to happen?

the FullRepositoryId should be the repo name alone, not include the owner

### What actually happened?

actually the FullRepositoryId = owner + repo

### Environment

  - **CDK CLI Version  :**1.113.0 (build 61e1f65)
  - **Framework Version:**
  - **Node.js Version:**  v16.2
  - **OS               :** mac big sure
  - **Language (Version):**  python 3.8

### Other

manually created pipelines have the FullRepositoryId equals to repo.

why the code generated pipelines fail?

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hi @uxth,

thanks for opening the issue. Can you specify:

1. The `owner` and `repo` that you provided for `CodeStarConnectionsSourceAction`.
2. The full URL to the GitHub repository that you want to connect to.

Thanks,
Adam

**Comment by uxth** [comment]
hi @skinny85 

                        connection_arn='arn:aws:codestar-connections:us-west-2:192878884426:connection/81711257-3407'
                                       '-4781-bc43-5e5f7db2fadc',
                        output=source_artifact,
                        owner='AWS',
                        repo='TuSimple/map-aws-infra',
                        branch='ningxu/argo_persistence',

this is directly from the code, but I don't know if you can see this because the repo is private.

**Comment by uxth** [comment]
BTW, this can be found in the cdk_out folder, in some json files.

each time, if I ran 'cdk ls', this will automatically change back to owner + repo.

**Comment by skinny85** [comment]
Sorry. Is the owner of the repo `'AWS'`, or `'TuSimple'`? Like, what is the GItHub link to the repo? (Just show it to me, it doesn't matter that I won't have access to it)

**Comment by uxth** [comment]
the owner is AWS, and it does not allow for other values except for AWS, Custom, ThirdParty.

the TuSimple is the organization.

the git repo link is  https://ghe.tusimple.io/TuSimple/map-aws-infra/

**Comment by skinny85** [comment]
Ah. I understand. You're thinking of a different "owner" 🙂.

Here, the `owner` is `'TuSimple`. So, it should be:

```ts
                    owner='TuSimple',
                    repo='map-aws-infra',
```

**Comment by skinny85** [comment]
`owner` means the owner of the repo. Not the owner of the Action.

**Comment by uxth** [comment]
yes, I know that, but if I change the owner to other values it will give me this error:

An error occurred (ValidationException) when calling the UpdatePipeline operation: 1 validation error detected: Value at 'pipeline.stages.1.member.actions.1.member.actionTypeId.owner' failed to satisfy constraint: Member must satisfy enum value set: [Custom, AWS, ThirdParty]

**Comment by uxth** [comment]
oh, I think I know what is wrong, let me try it

**Comment by skinny85** [comment]
Did it? 🙂

**Comment by uxth** [comment]
it has not finished, but I think it works. thank you! :)
