### ISSUE TITLE
@aws-cdk/aws-eks: KubernetesVersion V1.20 from string results in wrong machine image SSM parameter name

### ISSUE THREAD

**Issue by Obirah** [aws/aws-cdk#15567]
When parsing the string `'1.20'` as `KubernetesVersion`, the automatic resolving of the machine image SSM parameter name results in a wrong name.

### Reproduction Steps

Either:
`this.machineImage = new EksOptimizedImage({ kubernetesVersion: this.config.version });` where `this.config.version` is `'1.20'`.

Or create an EKS cluster with `KubernetesVersion.of('1.20')`.

### What did you expect to happen?

I expect the stack to use the SSM parameter name `/aws/service/eks/optimized-ami/1.20/amazon-linux-2/recommended/image_id`.

### What actually happened?

The stack uses the SSM parameter name `/aws/service/eks/optimized-ami/1.2/amazon-linux-2/recommended/image_id`.

### Environment

  - **CDK CLI Version : 1.113.0**
  - **Framework Version: 1.113.0**
  - **Node.js Version: v15.7.0** 
  - **OS: MacOs 11.4**
  - **Language (Version): TypeScript (4.3.5)**

**Comment by otaviomacedo** [comment]
Hi, @Obirah 

I can't reproduce this issue. Can you share some minimal code example?

**Comment by Obirah** [comment]
Hi @otaviomacedo, thank you for your feedback. I investigated one more time and it turns out that my config file parser interpreted the string as a decimal number because it was not quoted. Sorry to bother you!
