### ISSUE TITLE
How can I add existing EC2 instances to an EndpointGroup?

### ISSUE THREAD

**Issue by kidbrax** [aws/aws-cdk#15566]
## :question: General Issue

I am trying to create an [EndpointGroup](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_globalaccelerator/EndpointGroup.html) and use existing instances. How can I do this? I tried using [InstanceEndpoint](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_globalaccelerator_endpoints/InstanceEndpoint.html).

I am using Python.

I have something like this:

```
import aws_cdk.aws_globalaccelerator as aga
import aws_cdk.aws_globalaccelerator_endpoints as aga_endpoints
new_endpoint = aga_endpoints.InstanceEndpoint(ec2.IInstance(instance_id=existing_instance_id)))
my_endpoint_group.add_endpoint(new_endpoint)
```

Along the same lines, what is the difference between
- [IInstance](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_ec2/IInstance.html) (what does the I in front indicate?)
- [Instance](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_ec2/Instance.html)
- [CfnInstance](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_ec2/CfnInstance.html)

### Environment

  - **CDK CLI Version:** 1.112.0 (build 2815a44)
  - **Module Version:** 
  - **OS:** macos big sur
  - **Language (Version):** python 3.8

**Comment by madeline-k** [comment]
Hello @kidbrax, most CDK constructs have a variety of `fromXXX` methods, however there are not yet any implemented for `ec2.Instance` which is what you would need to be able to do `my_endpoint_group.add_endpoint(InstanceEndpoint(ec2.Instance.fromInstanceId(...)))`

Feel free to open up a [new issue](https://github.com/aws/aws-cdk/issues/new/choose) if you are interested in implementing that feature yourself, or adding it to the CDK backlog. 

In the meantime, one way to add an existing Ec2 instance to an EndpointGroup is to use [escape hatches](https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html). Here is an example in typescript. (There are Java examples of escape hatching at the previous link.)

```
const endpointGroup = new globalaccelerator.EndpointGroup(this, 'group', {
      listener: myListener
});
    
const cfnEndpointGroup = eg.node.defaultChild as globalaccelerator.CfnEndpointGroup;
cfnEg.endpointConfigurations = [
  {
    endpointId: 'myInstanceId',
  },
];
```

**Comment by madeline-k** [comment]
> Along the same lines, what is the difference between
> - IInstance (what does the I in front indicate?)
> - Instance
>  - CfnInstance

- `IInstance` is the interface used for Ec2 instances. This is the type that will be used everywhere to reference an Ec2 Instance, and it is implemented by `Instance`.  
- `Instance` is the CDK L2 implementation of an Ec2 Instance. See [this doc](https://docs.aws.amazon.com/cdk/latest/guide/constructs.html) for a description of what an L2 is. 
- `CfnInstance` is a type which exactly maps to the Cloudformation entity [AWS::EC2::Instance](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html) 

A couple things to note: `CfnInstance` does not implement the `IInstance` interface and cannot be used anywhere that an `IInstance` is required. Any `Instance` can be cast to a `CfnInstance` using the escape hatching method above. 

I hope this clears things up for you! Please let me know if you have any further questions.

**Comment by kidbrax** [comment]
Thank you, this worked perfectly.

In case anyone else comes across this, this is what I ended up in Python

```
# import aws_cdk.aws_globalaccelerator as aga

# get active instance ids in cluster(s) using Boto3
cluster_instances = []
instances = ec2_client.describe_instances(
    Filters=[
        { 'Name': 'tag:Name', 'Values': myName },
        { 'Name': 'instance-state-name', 'Values': [ 'running' ] }
    ],
)
for reservation in instances['Reservations']:
    for instance in reservation['Instances']:
        cluster_instances.append(instance['InstanceId'])

eg = aga.EndpointGroup(
    self,
    id=myEg,
    listener=my_listener,
    health_check_port=nnn,
    region=us-east-1,
    port_overrides=[aga.PortOverride(endpoint_port=nnn, listener_port=53)],
)

# we are using existing instances as endpoints
# so we have to add them after the fact
endpoint_configs = []
for cluster_instance in cluster_instances:
    endpoint_configs.append({'endpointId': cluster_instance})
print(endpoint_configs)
eg.node.default_child.endpoint_configurations = endpoint_configs
```
