### ISSUE TITLE
(aws-s3): add_event_notification does not generate Cloud Formation template with cross-stack bucket dependency

### ISSUE THREAD

**Issue by crawfobw** [aws/aws-cdk#15575]
I'm attempting to add `add_event_notification` to a bucket in a separate stack from where the bucket is owned but no cloudformation template is generated to create the event notification

### Reproduction Steps
```
class BucketStack(core.Stack):
  def __init__(self, scope, construct_id, **kwargs):
     self.bucket = aws_s3.Bucket(self, 'bucket', bucket_name='somebucketname')

class TriggerStack(core.Stack):
  def __init__(self, scope, construct_id, bucket: aws_s3.Bucket, handler_function: aws_lambda.Function, **kwargs):
    signature_report_bucket.add_event_notification(
            event=aws_s3.EventType.OBJECT_CREATED,
            dest=aws_s3_notifications.LambdaDestination(handler_function)
        )
```

### What did you expect to happen?
Cloud Formation template to be generated for S3 event notification

### What actually happened?
No cloudformation rtemplate is generated for the S3 event notification

### Environment

  - **CDK CLI Version  :** 1.108.1
  - **Framework Version:** 1.110.0
  - **Node.js Version:** 16.3.0
  - **OS               :** mac OSx 11.4
  - **Language (Version):** Python 3.8.6

--- 

This is :bug: Bug Report

**Comment by crawfobw** [comment]
Note doing the following will result in the Cloud formation template generating correctly
```
  def __init__(self, scope, construct_id, **kwargs):
     self.bucket = aws_s3.Bucket(self, 'bucket', bucket_name='somebucketname')

class TriggerStack(core.Stack):
  def __init__(self, scope, construct_id, handler_function: aws_lambda.Function, **kwargs):
    # define bucket by name not as cross stack import
    bucket = aws_s3.Bucket.from_bucket_name(self, 'bucket-import',  bucket_name='somebucketname')

    signature_report_bucket.add_event_notification(
            event=aws_s3.EventType.OBJECT_CREATED,
            dest=aws_s3_notifications.LambdaDestination(handler_function)
        )
```

**Comment by rix0rrr** [comment]
The `add_event_notification` function doesn't have a `scope` parameter, it really has no choice other than to create new constructs under itself. Since it leaves in `BucketStack`, it can only create new constructs that then will also live in `BucketStack`.

The code *cannot know* you are calling it from the constructor of `TriggerStack`. 

What you are doing seems like a fine workaround. By the way, I would not hardcode the bucket name, but you can do the following:

```python
class BucketStack(core.Stack):
  def __init__(self, scope, construct_id, **kwargs):
     self.bucket = aws_s3.Bucket(self, 'bucket', bucket_name='somebucketname')

class TriggerStack(core.Stack):
  def __init__(self, scope, construct_id, bucket: aws_s3.Bucket, handler_function: aws_lambda.Function, **kwargs):
    # Import bucket as construct here to force creation of resources in this stack
    imported_bucket = aws_s3.Bucket.from_bucket_name(self, 'bucket-import',  bucket_name=bucket.bucket_name)

    imported_bucket.add_event_notification(
            event=aws_s3.EventType.OBJECT_CREATED,
            dest=aws_s3_notifications.LambdaDestination(handler_function)
        )
```
