### ISSUE TITLE
Finalize the names of the unstable modules in V2

### ISSUE THREAD

**Issue by skinny85** [aws/aws-cdk#15576]
We need to decide on the exact names of the V2 unstable packages: things like the NodeJS module name, the Java `groupId`, `artifactId`, and Java package, C# package name and C# namespace, etc. - specifically, how they compare to their V1 counterparts. We need to choose the names deliberately so that the migration from V1 to V2 is as smooth as possible.

Right now, after #15442 has been merged, the names are:

- NodeJS:
    - module name is `@aws-cdk-lib-alpha/aws-<service>` (compared to `@aws-cdk/aws-<service>`)
- Java:
    - `groupId`: `software.amazon.awscdk` (same as V1)
    - `artifactId`: `cdk-alpha.aws-<service>` (compared to just `<service>` in V1)
    - Java package: `software.amazon.awscdk.alpha.services.<service>` (compared to `software.amazon.awscdk.services.<service>` in V1)
- C#:
    - `packageId`: `Amazon.CDK.AWS.<Service>` (same as V1)
     - C# namespace: `Amazon.CDK.Alpha.AWS.<Service>` (as compared to `Amazon.CDK.AWS.<Service>` for V1)
- Python:
    - `distName`: `aws-cdk.alpha.aws-<service>` (as compared to `aws-cdk.aws-<service>` in V1)
    - `module`: `aws_cdk.alpha.aws_<service>` (as compared to `aws_cdk.aws_<service>` in V1)
 - Go: no idea. Requires further investigation.

This might require changes in our [`pkglint` rules](https://github.com/aws/aws-cdk/blob/a2e95e97fc775d061b405fdb932ffda269084357/tools/pkglint/lib/rules.ts#L834).

It might also require changes to package manager permissions (for example, we might have to claim rights to a new scope in npmjs.org).

**Comment by eladb** [comment]
Why do we need `-lib` in the nodejs scope. I would go with `@aws-cdk-alpha/` or `@aws-cdk-experimental/`

**Comment by nija-at** [comment]
+1 to @eladb's comment above.

> Java
> artifactId: cdk-alpha.aws-<service>

Drop `cdk-` from here. It's already part of groupId.

**Comment by skinny85** [comment]
The final decision is to put "alpha" everywhere - both in the module name, and in the customer-facing parts of the code.

So, the final names will be:

- NodeJS:
    - module name is `@aws-cdk-alpha/aws-<service>` (compared to V1: `@aws-cdk/aws-<service>`)
- Java:
    - `groupId`: `software.amazon.awscdk.alpha` (compared to V1: `software.amazon.awscdk`)
    - `artifactId`: `<service>` (same as in V1)
    - Java package: `software.amazon.awscdk.alpha.services.<service>` (compared to `software.amazon.awscdk.services.<service>` in V1)
- C#:
    - `packageId`: `Amazon.CDK.Alpha.AWS.<Service>` (compared to V1: `Amazon.CDK.AWS.<Service>`)
     - C# namespace: `Amazon.CDK.Alpha.AWS.<Service>` (compared to V1: `Amazon.CDK.AWS.<Service>`)
- Python:
    - `distName`: `aws-cdk-alpha.aws-<service>` (compared to V1: `aws-cdk.aws-<service>`)
    - `module`: `aws_cdk_alpha.aws_<service>` (compared to V1: `aws_cdk.aws_<service>`)

**Comment by skinny85** [comment]
In Go, the name of the module is a combination of the Git repository name and the NodeJS package name. Our current repository is ` github.com/aws/aws-cdk-go`, which seems like a fine start for the module name. If we re-use that repository for the unstable modules, their name should be something like `github.com/aws/aws-cdk-go/awscdkalpha/aws<service>`, which I think looks quite good.

So, in summary, there shouldn't be too much work required to support Go.

**Comment by njlynch** [comment]
Latest proposal:


- NodeJS:
    - module name is `@aws-cdk/aws-<service>-alpha` (V1: `@aws-cdk/aws-<service>`)
- Java:
    - `groupId`: `software.amazon.awscdk` (V1: same)
    - `artifactId`: `<service>.alpha` (V1: <service>)
    - Java package: `software.amazon.awscdk.services.<service>.alpha` (V1: `software.amazon.awscdk.services.<service>`)
- C#:
    - `packageId`: `Amazon.CDK.AWS.<Service>.Alpha` (V1: `Amazon.CDK.AWS.<Service>`)
     - C# namespace: `Amazon.CDK.AWS.<Service>.Alpha.` (V1: `Amazon.CDK.AWS.<Service>`)
- Python:
    - `distName`: `aws-cdk.aws-<service>-alpha` (V1: `aws-cdk.aws-<service>`)
    - `module`: `aws_cdk.aws_<service>_alpha` (V1: `aws_cdk.aws_<service>`)
- Go:
    - `github.com/aws/aws-cdk-go/awscdk/<service>alpha` (V2 stable: `github.com/aws/aws-cdk-go/awscdk/<service>`)
