### ISSUE TITLE
Release stable L3 modules separately

### ISSUE THREAD

**Issue by skinny85** [aws/aws-cdk#15582]
Right now, L3 modules like `@aws-cdk/aws-ecs-patterns` and `@aws-cdk/aws-route53-patterns` are included in the `aws-cdk-lib` package.

We can use the same mechanism we use for unstable modules to release these stable modules too, outside of `aws-cdk-lib`.

**Comment by nija-at** [comment]
I believe the original motivation for this is so that ECS folks can manage their own release lifecycle for the ECS L3s.
Are there other motivations? They were interested in releasing their own V2 of their modules.

What about the `aws-lambda-*` modules? Should we do the same?

**Comment by skinny85** [comment]
> I believe the original motivation for this is so that ECS folks can manage their own release lifecycle for the ECS L3s.
> Are there other motivations? They were interested in releasing their own V2 of their modules.

I think the other motivation was just making `aws-cdk-lib` smaller, with a clearer definition ("this only contains L1s and L2s").

> What about the `aws-lambda-*` modules? Should we do the same?

We had a discussion about it, and @eladb strongly feels like the are L2 (maybe L2.5) constructs, and belong to `aws-cdk-lib`.
