### ISSUE TITLE
Handle the `@aws-cdk/assertions` library in the V2 build of unstable modules

### ISSUE THREAD

**Issue by skinny85** [aws/aws-cdk#15589]
The `@aws-cdk/assertions` library uses a [build process](https://github.com/aws/aws-cdk/blob/dd38eff318c31bf2c5308f6b3daae0fd433b4370/packages/%40aws-cdk/assertions/package.json#L54) to "vendor in" a few dependencies (`@aws-cdk/cfnspec` and `@aws-cdk/assert`, I believe). This makes it incompatible with the V2 build of experimental modules added in https://github.com/aws/aws-cdk/pull/15442. We need to fix that process.

This will also unblock including its dependents, like `@aws-cdk/aws-synthetics` (excluded [here](https://github.com/aws/aws-cdk/blob/a2e95e97fc775d061b405fdb932ffda269084357/packages/%40aws-cdk/aws-synthetics/package.json#L112-L112)).

**Comment by nija-at** [comment]
The fix is to change the `vendor-in.sh` script to use relative paths from the repo root, instead of relative paths from the module root. This will make the script work in both cases.
