### ISSUE TITLE
RDS: Support enabling IAM DATABASE Authentication

### ISSUE THREAD

**Issue by RomainMuller** [aws/aws-cdk#1558]
The current RDS constructs do not surface the IAM DB Authentication configuration, making it unusable without resorting to escape hatches.

----

https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.html

**Comment by RomainMuller** [comment]
I have a WIP for this, but the permission-granting API for the `grantConnect` primitive requires the "resource ID" of the `DBInstances`, which isn't surfaced by CloudFormation (hence requires a `CustomResource`).

**Comment by saltman424** [comment]
+1

**Comment by gbooth27** [comment]
any news on this?

**Comment by skinny85** [comment]
@RomainMuller did you submit your WiP anywhere?

**Comment by RomainMuller** [comment]
@skinny85 - nope I never managed to finish that completely; and the underlying APIs changed quite a bit in between... so it's as good as not existent.

**Comment by nija-at** [comment]
Work left here is to build a `grantConnect()` method that will grant an IAM `IPrincipal` with the permissions to connect. Any calls to `grantConnect()` should automatically turn set the [`iamAuthentication` property](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-rds/lib/instance.ts#L343), if not already.
