### ISSUE TITLE
(aws-eks): roles with paths do not work in the EKS master role or other awsAuth role maps

### ISSUE THREAD

**Issue by njlaw** [aws/aws-cdk#15596]
Because role paths are not included in authentication data, roles with paths must be represented as though the do not have a path.  See [AWS documentation](https://docs.aws.amazon.com/eks/latest/userguide/troubleshooting_iam.html#security-iam-troubleshoot-ConfigMap).  However, [`AwsAuth.synthesizeMapRoles()`](https://github.com/aws/aws-cdk/blob/ebfc0e092addbcf21562ce63328457285f7b2d77/packages/%40aws-cdk/aws-eks/lib/aws-auth.ts#L118) does not strip the path.

### Reproduction Steps

```typescript
const cluster = new Cluster(stack, 'Cluster', { version: CLUSTER_VERSION, prune: false });
const roleWithPath = new iam.Role(stack, 'roleWithPath', {
  assumedBy: new iam.AnyPrincipal(),
  path: 'path-segment-1',
});
cluster.awsAuth.addRoleMapping(role1, { groups: ['rolewithPath-group1'] });
```

### What did you expect to happen?

The value of mapRoles in the aws-auth ConfigMap in Kubernetes should be:
```typescript
[
  {
    // master role map entry
  },
  {
    // node group role map entry
  }
  {
    "rolearn": "arn:aws:iam::123456789123:role/roleWithPathABCD...",
    "username": "arn:aws:iam::123456789123:role/roleWithPathABCD...",
    "groups": ["rolewithPath-group1"]
  }
]
```

### What actually happened?

Instead the following is generated, which does not work to authenticate since the role ARN without the role is required.
```typescript
[
  {
    // master role map entry
  },
  {
    // node group role map entry
  }
  {
    "rolearn": "arn:aws:iam::123456789123:role/path-segment-1/roleWithPathABCD...",
    "username": "arn:aws:iam::123456789123:role/path-segment-1/roleWithPathABCD...",
    "groups": ["rolewithPath-group1"]
  }
]
```

### Environment

  - **CDK CLI Version  :** 1.114.0
  - **Framework Version:** 1.114.0
  - **Node.js Version:** v14.16.1
  - **OS               :**  Linux, Windows, and Mac OS
  - **Language (Version):** all

### Attempted (but Failed) Fix

I forked the repo and tried to come up with a fix; however, with current limitations in CloudFormation, I was unable produce one.

My attempted fix looked like this:
```typescript
/**
   * Remove the path from the role ARN since it is not permitted and will not work for authentication.
   *
   * @see https://docs.aws.amazon.com/eks/latest/userguide/troubleshooting_iam.html#security-iam-troubleshoot-ConfigMap
   *
   * @param roleArn
   * @returns the role ARN without the path
   */
  private removePathFromRoleArn(roleArn: string) {
    return Lazy.any({
      produce: () => Fn.join('/', [Fn.select(0, Fn.split('/', roleArn)), Fn.select(Fn.size(Fn.split('/', roleArn)) - 1, Fn.split('/', roleArn))]),
    });
  }

  private synthesizeMapRoles() {
    return Lazy.any({
      produce: () => this.stack.toJsonString(this.roleMappings.map(m => ({
        rolearn: this.removePathFromRoleArn(m.role.roleArn),
        username: m.mapping.username ?? m.role.roleArn,
        groups: m.mapping.groups,
      }))),
    });
  }
```

However, [there is no `Fn::Size` CloudFormation function](aws-cloudformation/cfn-language-discussion#61) or Fn::Length or something similar.

I'd love to hear if anyone has ideas on how to resolve this and I'd be happy to create a pull request.

--- 

This is :bug: Bug Report

**Comment by otaviomacedo** [comment]
Have you tried using `Fn.sub` to replace each group with the empty string?

**Comment by njlaw** [comment]
> Have you tried using `Fn.sub` to replace each group with the empty string?

Hmm, because there's not length-like function in CloudFormation, I'm not sure how I'd specify which groups to replace.

**Comment by njlaw** [comment]
I was doing some other work today, and noticed the following [documentation on `Role.fromRoleArn`](https://github.com/aws/aws-cdk/blob/7e41b6b745ff185110b7aba3db15d30bb35577bc/packages/%40aws-cdk/aws-iam/lib/role.ts#L172), so it looks like this has probably received a fair bit of thought and won't be resolvable without upstream (CloudFormation) updates such as [Issue #204 there](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/204):

https://github.com/aws/aws-cdk/blob/7e41b6b745ff185110b7aba3db15d30bb35577bc/packages/%40aws-cdk/aws-iam/lib/role.ts#L172-L179
