### ISSUE TITLE
Add the logic for the release of the unstable modules

### ISSUE THREAD

**Issue by skinny85** [aws/aws-cdk#15591]
We need to:

1. Create the [bump logic](https://github.com/aws/aws-cdk/blob/09591c6268d0e03937741e4f7cad9b97e21b131b/bump.sh#L1) in the [`cdk-release` tool](https://github.com/aws/aws-cdk/tree/09591c6268d0e03937741e4f7cad9b97e21b131b/tools/cdk-release#L79-L79) for unstable modules. The exact logic of the version bumping depends on the questions answered in https://github.com/aws/aws-cdk/issues/15581.

    The probable implementation is creating a `version.json` file in each directory of the generated unstable package with the current version, and bumping it if already exists.
2. Modify the build of the alpha packages to take the version from the above mentioned file.
3. Change the [`align-versions` script](https://github.com/aws/aws-cdk/blob/09591c6268d0e03937741e4f7cad9b97e21b131b/scripts/align-version.sh#L1-L1) to use the version from the above mentioned file to change the actual versions in `package.json` to the stated version.
4. Add logic to the  [`cdk-release` tool](https://github.com/aws/aws-cdk/tree/09591c6268d0e03937741e4f7cad9b97e21b131b/tools/cdk-release#L79-L79) that generates the individual Changelogs, and possibly integrates them with the master V2 Changelog.

**Comment by njlynch** [comment]
#16043 tackles the first part of this task: the bump logic itself. Given the decisions made in the versioning discussion (#15581 ), this was actually rather straightforward; simply add a new alpha version to the main `version.vN.json` file and bump alongside the primary/stable version.

I'm tackling the fourth item (changelogs) next.

**Comment by madeline-k** [comment]
https://github.com/aws/aws-cdk/pull/16321 and https://github.com/aws/aws-cdk/pull/16322/ address items 2 and 3.
