### ISSUE TITLE
Deploying EKS gives an error Inaccessible host: `lambda.us-west-2.amazonaws.com'.

### ISSUE THREAD

**Issue by uxth** [aws/aws-cdk#15597]
This error came up recently when deploying an EKS cluster in codepipeline, could you help to take a look?

Received response status 
```
[FAILED] from custom resource. Message returned: UnknownEndpoint: Inaccessible host: `lambda.us-west-2.amazonaws.com'. This service may not be available in the `us-west-2' region. at Request.ENOTFOUND_ERROR (/var/runtime/node_modules/aws-sdk/lib/event_listeners.js:507:46) at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20) at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10) at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:688:14) at ClientRequest.error (/var/runtime/node_modules/aws-sdk/lib/event_listeners.js:339:22) at ClientRequest.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/http/node.js:96:19) at ClientRequest.emit (events.js:376:20) at ClientRequest.emit (domain.js:470:12) at TLSSocket.socketErrorListener (_http_client.js:475:9) at TLSSocket.emit (events.js:376:20) (RequestId: dcc56880-197d-4799-9728-5add336cfb84)
```

### Reproduction Steps

I have two stages, a test stage and a dev stage.
the weird part is the code pipeline deploys them, test stage does not have issues, but the dev stage failed.

### What did you expect to happen?

it should not have any issues

### What actually happened?
it failed due to lambda not found

### Environment

  - **CDK CLI Version  :**
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):** 

### Other

--- 

This is :bug: Bug Report

**Comment by otaviomacedo** [comment]
Hi, @uxth 

Can you please share a minimal code example to reproduce this error?

Thanks.

**Comment by uxth** [comment]
Hi @otaviomacedo 


here is the code how the eks cluster is created:
        self.cluster = eks.Cluster(
            self, id='map-eks-cluster',
            cluster_name=config.getValue('eks.cluster_name'),
            version=eks.KubernetesVersion.V1_19,
            vpc=vpc_stack.vpc,
            vpc_subnets=[ec2.SubnetSelection(subnet_type=ec2.SubnetType.PRIVATE)],
            default_capacity=0,
            masters_role=eks_role
        )

        self.cluster.add_nodegroup_capacity(
            'map-eks-nodegroup',
            instance_types=[ec2.InstanceType(config.getValue('eks.nodegroup.instance_type'))],
            disk_size=config.getValue('eks.nodegroup.disk_size'),
            min_size=config.getValue('eks.nodegroup.min_size'),
            max_size=config.getValue('eks.nodegroup.max_size'),
            desired_size=config.getValue('eks.nodegroup.desired_size'),
            subnets=ec2.SubnetSelection(subnet_type=ec2.SubnetType.PRIVATE),
            capacity_type=eks.CapacityType.SPOT
        )

**Comment by otaviomacedo** [comment]
Thanks for the response. I managed to deploy a cluster based on this code snippet without any errors.

Without more information about your VPC and role (and in which region they are) it's hard to tell what's going on.
