### ISSUE TITLE
CDK deploy fails: S3 error: Access Denied in response to CreateChangeSet

### ISSUE THREAD

**Issue by abjoshi2785** [aws/aws-cdk#15593]
**Steps followed to store assets in Centralized account.**

Account used:
1. CENTRALIZED-ACCOUNT - 111111111111
2. APPLICATION-ACCOUNT - 222222222222

**Command executed on the centralized account to establish trust:**

`cdk bootstrap --profile CENTRALISED-ACCOUNT --trust 222222222222 --cloudformation-execution-policies arn:aws:iam::aws:policy/AdministratorAccess \
    aws://<CENTRALIZED-ACCOUNT-ID>/us-east-2`
    
  Changes to app.py
      # synthesizer properties
`    synthesizer=cdk.DefaultStackSynthesizer(
        file_assets_bucket_name="cdk-hnb659fds-assets-111111111111-us-east-2",
        file_asset_publishing_role_arn = "arn:aws:iam::111111111111:role/cdk-hnb659fds-file-publishing-role-111111111111-us-east-2"
    )`
    
   

<details>
  <summary>CDK Deploy on application account (verbose)</summary>
<pre>
   `CDK toolkit version: 1.113.0 (build 61e1f65)
Command line arguments: {
  _: [ 'deploy' ],
  verbose: 1,
  v: 1,
  lookups: true,
  'ignore-errors': false,
  ignoreErrors: false,
  json: false,
  j: false,
  debug: false,
  ec2creds: undefined,
  i: undefined,
  'version-reporting': undefined,
  versionReporting: undefined,
  'path-metadata': true,
  pathMetadata: true,
  'asset-metadata': true,
  assetMetadata: true,
  'role-arn': undefined,
  r: undefined,
  roleArn: undefined,
  staging: true,
  'no-color': false,
  noColor: false,
  fail: false,
  all: false,
  'build-exclude': [],
  E: [],
  buildExclude: [],
  ci: false,
  execute: true,
  force: false,
  f: false,
  parameters: [ {} ],
  'previous-parameters': true,
  previousParameters: true,
  '$0': 'cdk'
}
cdk.json: {
  "app": "python3 app.py",
  "context": {
    "@aws-cdk/aws-apigateway:usagePlanKeyOrderInsensitiveId": true,
    "@aws-cdk/core:enableStackNameDuplicates": "true",
    "aws-cdk:enableDiffNoFail": "true",
    "@aws-cdk/core:stackRelativeExports": "true",
    "@aws-cdk/aws-ecr-assets:dockerIgnoreSupport": true,
    "@aws-cdk/aws-secretsmanager:parseOwnedSecretName": true,
    "@aws-cdk/aws-kms:defaultKeyPolicies": true,
    "@aws-cdk/aws-s3:grantWriteWithoutAcl": true,
    "@aws-cdk/aws-ecs-patterns:removeDefaultDesiredCount": true,
    "@aws-cdk/aws-rds:lowercaseDbIdentifier": true,
    "@aws-cdk/aws-efs:defaultEncryptionAtRest": true,
    "@aws-cdk/core:newStyleStackSynthesis": true
  }
}
merged settings: {
  versionReporting: true,
  pathMetadata: true,
  output: 'cdk.out',
  app: 'python3 app.py',
  context: {
    '@aws-cdk/aws-apigateway:usagePlanKeyOrderInsensitiveId': true,
    '@aws-cdk/core:enableStackNameDuplicates': 'true',
    'aws-cdk:enableDiffNoFail': 'true',
    '@aws-cdk/core:stackRelativeExports': 'true',
    '@aws-cdk/aws-ecr-assets:dockerIgnoreSupport': true,
    '@aws-cdk/aws-secretsmanager:parseOwnedSecretName': true,
    '@aws-cdk/aws-kms:defaultKeyPolicies': true,
    '@aws-cdk/aws-s3:grantWriteWithoutAcl': true,
    '@aws-cdk/aws-ecs-patterns:removeDefaultDesiredCount': true,
    '@aws-cdk/aws-rds:lowercaseDbIdentifier': true,
    '@aws-cdk/aws-efs:defaultEncryptionAtRest': true,
    '@aws-cdk/core:newStyleStackSynthesis': true
  },
  debug: false,
  assetMetadata: true,
  toolkitBucket: {},
  staging: true,
  bundlingStacks: [ '*' ],
  lookups: true
}
Determining if we're on an EC2 instance.
Does not look like an EC2 instance.
Toolkit stack: CDKToolkit
Setting "CDK_DEFAULT_REGION" environment variable to us-east-2
Resolving default credentials
Retrieved account ID 111111111111 from disk cache
Setting "CDK_DEFAULT_ACCOUNT" environment variable to 111111111111
context: {
  '@aws-cdk/aws-apigateway:usagePlanKeyOrderInsensitiveId': true,
  '@aws-cdk/core:enableStackNameDuplicates': 'true',
  'aws-cdk:enableDiffNoFail': 'true',
  '@aws-cdk/core:stackRelativeExports': 'true',
  '@aws-cdk/aws-ecr-assets:dockerIgnoreSupport': true,
  '@aws-cdk/aws-secretsmanager:parseOwnedSecretName': true,
  '@aws-cdk/aws-kms:defaultKeyPolicies': true,
  '@aws-cdk/aws-s3:grantWriteWithoutAcl': true,
  '@aws-cdk/aws-ecs-patterns:removeDefaultDesiredCount': true,
  '@aws-cdk/aws-rds:lowercaseDbIdentifier': true,
  '@aws-cdk/aws-efs:defaultEncryptionAtRest': true,
  '@aws-cdk/core:newStyleStackSynthesis': true,
  'aws:cdk:enable-path-metadata': true,
  'aws:cdk:enable-asset-metadata': true,
  'aws:cdk:version-reporting': true,
  'aws:cdk:bundling-stacks': [ '*' ]
}
outdir: cdk.out
env: {
  CDK_DEFAULT_REGION: 'us-east-2',
  CDK_DEFAULT_ACCOUNT: '111111111111',
  CDK_CONTEXT_JSON: '{"@aws-cdk/aws-apigateway:usagePlanKeyOrderInsensitiveId":true,"@aws-cdk/core:enableStackNameDuplicates":"true","aws-cdk:enableDiffNoFail":"true","@aws-cdk/core:stackRelativeExports":"true","@aws-cdk/aws-ecr-assets:dockerIgnoreSupport":true,"@aws-cdk/aws-secretsmanager:parseOwnedSecretName":true,"@aws-cdk/aws-kms:defaultKeyPolicies":true,"@aws-cdk/aws-s3:grantWriteWithoutAcl":true,"@aws-cdk/aws-ecs-patterns:removeDefaultDesiredCount":true,"@aws-cdk/aws-rds:lowercaseDbIdentifier":true,"@aws-cdk/aws-efs:defaultEncryptionAtRest":true,"@aws-cdk/core:newStyleStackSynthesis":true,"aws:cdk:enable-path-metadata":true,"aws:cdk:enable-asset-metadata":true,"aws:cdk:version-reporting":true,"aws:cdk:bundling-stacks":["*"]}',
  CDK_OUTDIR: 'cdk.out',
  CDK_CLI_ASM_VERSION: '12.0.0',
  CDK_CLI_VERSION: '1.113.0'
}
Reading existing template for stack HelloCdkStack.
Retrieved account ID 111111111111 from disk cache
Assuming role 'arn:aws:iam::111111111111:role/cdk-hnb659fds-deploy-role-111111111111-us-east-2'.
HelloCdkStack: deploying...
Retrieved account ID 111111111111 from disk cache
Assuming role 'arn:aws:iam::111111111111:role/cdk-hnb659fds-deploy-role-111111111111-us-east-2'.
Waiting for stack CDKToolkit to finish creating or updating...
[0%] start: Publishing 4cd61014b71160e8c66fe167e43710d5ba068b80b134e9bd84508cf9238b2392:current_account-current_region
Assuming role 'arn:aws:iam::222222222222:role/cdk-hnb659fds-file-publishing-role-222222222222-us-east-2'.
[0%] check: Check s3://cdk-hnb659fds-assets-222222222222-us-east-2/4cd61014b71160e8c66fe167e43710d5ba068b80b134e9bd84508cf9238b2392.zip
[0%] found: Found s3://cdk-hnb659fds-assets-222222222222-us-east-2/4cd61014b71160e8c66fe167e43710d5ba068b80b134e9bd84508cf9238b2392.zip
[50%] success: Published 4cd61014b71160e8c66fe167e43710d5ba068b80b134e9bd84508cf9238b2392:current_account-current_region
[50%] start: Publishing 90ef6303f9164ade0a2ee037d412255eb9277db661506d65d8cefd2aec6afb56:current_account-current_region
Assuming role 'arn:aws:iam::222222222222:role/cdk-hnb659fds-file-publishing-role-222222222222-us-east-2'.
[50%] check: Check s3://cdk-hnb659fds-assets-222222222222-us-east-2/90ef6303f9164ade0a2ee037d412255eb9277db661506d65d8cefd2aec6afb56.json
[50%] found: Found s3://cdk-hnb659fds-assets-222222222222-us-east-2/90ef6303f9164ade0a2ee037d412255eb9277db661506d65d8cefd2aec6afb56.json
[100%] success: Published 90ef6303f9164ade0a2ee037d412255eb9277db661506d65d8cefd2aec6afb56:current_account-current_region
HelloCdkStack: checking if we can skip deploy
HelloCdkStack: template has changed
HelloCdkStack: deploying...
Removing existing change set with name cdk-deploy-change-set if it exists
Attempting to create ChangeSet with name cdk-deploy-change-set to update stack HelloCdkStack
HelloCdkStack: creating CloudFormation changeset...
Call failed: createChangeSet({"StackName":"HelloCdkStack","ChangeSetName":"cdk-deploy-change-set","ChangeSetType":"UPDATE","Description":"CDK Changeset for execution 39fec47c-95ab-46a0-ae4e-e0c8d8277c20","TemplateURL":"https://s3.us-east-2.amazonaws.com/cdk-hnb659fds-assets-222222222222-us-east-2/90ef6303f9164ade0a2ee037d412255eb9277db661506d65d8cefd2aec6afb56.json","Parameters":[{"ParameterKey":"BootstrapVersion","UsePreviousValue":true}],"RoleARN":"arn:aws:iam::111111111111:role/cdk-hnb659fds-cfn-exec-role-111111111111-us-east-2","Capabilities":["CAPABILITY_IAM","CAPABILITY_NAMED_IAM","CAPABILITY_AUTO_EXPAND"],"Tags":[]}) => S3 error: Access Denied
For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html (code=ValidationError)

 ❌  HelloCdkStack failed: Error [ValidationError]: S3 error: Access Denied
For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html
    at Request.extractError (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'ValidationError',
  time: 2021-07-15T18:21:11.615Z,
  requestId: '27054ea5-3197-404f-bc15-22cbadc300ce',
  statusCode: 400,
  retryable: false,
  retryDelay: 860.3586564374019
}
S3 error: Access Denied
For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html
ValidationError: S3 error: Access Denied
For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html
    at Request.extractError (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:116:18)`
</pre>

</details>

**Comment by rix0rrr** [comment]
I have seen this error before, and I'm not sure what's causing it. In all cases I've seen, it seems to be transient, and goes away if you retry the command. 

Is that true for you?

**Comment by abjoshi2785** [comment]
@rix0rrr Its consistently happenning. I think its because how the IAM policies and the bucket policies are created when cdk bootstrap command is executed.

If you see the deploy IAM role it has access to the resources in the resepctive account only. So when we do cdk deploy in application account, synthesizer give us the flexibility to save the assets in centralized account but the deploy role in app account dosent seem to have necessary permissions to pick assets from the centralized account. 

`synthesizer=cdk.DefaultStackSynthesizer( **file_assets_bucket_name**="cdk-hnb659fds-assets-111111111111-us-east-2", **file_asset_publishing_role_arn** = "arn:aws:iam::111111111111:role/cdk-hnb659fds-file-publishing-role-111111111111-us-east-2" )`

**Comment by rix0rrr** [comment]
Ah, I now see what you are trying to do.

Not a use case we really considered and the out-of-the-box resources don't accomodate this.

`--trust` means:

* Other account can assume `deploy-role` in this account.

`--trust` does NOT mean:

* `file-publishing-role` in other account can write assets to bucket in this account.

Nevertheless, if you really want to do this you can probably get it to work by breaking out of the standard bootstrap template and adding in your own policies. Read ["customizing the template" on this page](https://docs.aws.amazon.com/cdk/latest/guide/bootstrapping.html#bootstrapping-customizing)
