### ISSUE TITLE
[@aws-cdk/aws-s3-deployment] speed up aws s3 sync (--delete) which takes 20+ minutes

### ISSUE THREAD

**Issue by naseemkullah** [aws/aws-cdk#15609]
https://github.com/aws/aws-cdk/blob/2647cf300ae0f9053104e3a545e2fd94dd7249e1/packages/%40aws-cdk/aws-s3-deployment/lib/lambda/index.py#L137-L144

Currently the `aws s3 sync --delete` command above is taking 20+ minutes to complete in our case, I would like to [speed this up](https://aws.amazon.com/premiumsupport/knowledge-center/s3-improve-transfer-sync-command/).

In particular I would like a way to both provide `max_concurrent_requests` and if not available already a way to configure the  lambda resources (in proportion to max_concurrent requests).

Any other tips on how to get this from 20+ minutes to something more reasonable would be highly appreciated!

**Comment by otaviomacedo** [comment]
Hi, @naseemkullah

We can probably implement some of the optimizations mentioned in the article you linked. However, we can't work on this immediately.

We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://join.slack.com/t/cdk-dev/shared_invite/zt-mso6p56d-qJp7SOTBvMaQuDrx7R2wHg) to solicit support for reprioritization.

**Comment by naseemkullah** [comment]
Hi @otaviomacedo, we were able to speed up the sync by increasing the lambda's memory. Thanks, closing.
