### ISSUE TITLE
(SQSPolicy): Invalid value for the parameter Policy.

### ISSUE THREAD

**Issue by mnanchev** [aws/aws-cdk#15602]
I tried to add policy statement to SQS queue,  but i get Invalid value for the parameter Policy.

### Reproduction Steps

`
 const policyStatement = new iam.PolicyStatement();
    policyStatement.effect = Effect.ALLOW;
    policyStatement.addActions(
      'sqs:ChangeMessageVisibility',
      'sqs:DeleteMessage',
      'sqs:GetQueueAttributes',
      'sqs:GetQueueUrl',
      'sqs:ListQueues',
      'sqs:ReceiveMessage',
      'sqs:SendMessage',
    );
    policyStatement.addResources(this.sqsARN);
    policyStatement.addArnPrincipal(cloudProps.getAIWorkerIAMRoleARN(cloudProps));
    policyStatement.addAwsAccountPrincipal(cloudProps.orgs.backendAccount.env!.account!);
    this.queue.addToResourcePolicy(policyStatement);

`

### What did you expect to happen?

The SQS policy should be added to the queue

### What actually happened?

Invalid value for the parameter Policy.

### Environment

  - **CDK CLI Version  :1.108.1
  - **Framework Version:
  - **Node.js Version:** 14.6.1
  - **OS               :Windows
  - **Language (Version):**  TypeScript 4.3.2

### Other
Here is the cloudformation template, i replaced the account ids with <ACCOUNT_ID_HIDDEN>
 "exerciseEventResultQueueStackexerciseEventResultQueueStackdlqPolicy96369426": {
      "Type": "AWS::SQS::QueuePolicy",
      "Properties": {
        "PolicyDocument": {
          "Statement": [
            {
              "Action": [
                "sqs:ChangeMessageVisibility",
                "sqs:DeleteMessage",
                "sqs:GetQueueAttributes",
                "sqs:GetQueueUrl",
                "sqs:ListQueues",
                "sqs:ReceiveMessage",
                "sqs:SendMessage"
              ],
              "Effect": "Allow",
              "Principal": {
                "AWS": [
                  "arn:aws:iam::<ACCOUNT_ID_HIDDEN>:role/S3-ECR-registry-full-access",
                  {
                    "Fn::Join": [
                      "",
                      [
                        "arn:",
                        {
                          "Ref": "AWS::Partition"
                        },
                        ":iam::<ACCOUNT_ID_HIDDEN>:root"
                      ]
                    ]
                  }
                ]
              },
              "Resource": {
                "Fn::GetAtt": [
                  "exerciseEventResultQueueStackexerciseEventResultQueueStackdlq05F0A762",
                  "Arn"
                ]
              }
            }
          ],
          "Version": "2012-10-17"
        },
        "Queues": [
          {
            "Ref": "exerciseEventResultQueueStackexerciseEventResultQueueStackdlq05F0A762"
          }
        ]
      },
      "Metadata": {
        "aws:cdk:path": "aiComposition/exerciseEventResultQueueStack/exerciseEventResultQueueStack/exerciseEventResultQueueStack-dlq/Policy/Resource"
      }
    },

--- 

This is :bug: Bug Report

**Comment by peterwoodworth** [comment]
@mnanchev could you please be more clear with exactly what's going wrong, thanks :)

**Comment by peterwoodworth** [comment]
I've tried to reproduce this and am unable to, if you could give me more information I could try to help you 😄
