### ISSUE TITLE
(AwsCustomResource): missing children in node tree

### ISSUE THREAD

**Issue by gsingh04** [aws/aws-cdk#15611]
When using [custom-resource module](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_custom-resources.AwsCustomResource.html), I believe there is issue in tree node construction. There is no child for the provider singleton function (snippet below). As a result we cannot access underlying lambda function and the resource properties for eg.  to add cfn_nag metadata to the lambda function resource.

### Reproduction Steps
```
const s3Deploy = new AwsCustomResource(this, "CopyManifest", {
      onCreate: {
        service: "S3",
        action: "copyObject",
        parameters: {
          Bucket: policyBucket.bucketName,
          CopySource: MY_BUCKET,
          Key: "policy_manifest.json",
        },
        physicalResourceId: PhysicalResourceId.of(Date.now().toString()),
      },
      policy: AwsCustomResourcePolicy.fromStatements([
        new PolicyStatement({
          effect: Effect.ALLOW,
          sid: "S3Get",
          actions: ["s3:GetObject"],
          resources: [`arn:aws:s3:::BUCKET/*`],
        }),
        new PolicyStatement({
          effect: Effect.ALLOW,
          sid: "S3Put",
          actions: ["s3:PutObject"],
          resources: [`BUCKET/*`],
        }),
      ]),
    });

```

### What did you expect to happen?

I should be able to access the underlying resource and add metadata as follows
```
(s3Deploy.node.children[0].node.findChild(
      "Resource"
    ) as CfnFunction).cfnOptions.metadata = {
      cfn_nag: {
        rules_to_suppress: [
          {
            id: "W58",
            reason:
              "CloudWatch logs write permissions added with managed role AWSLambdaBasicExecutionRole",
          },
          ...cfn_nag_w89_w92,
        ],
      },
    };
```

### What actually happened?
There is no child under the provider function node tree

### Environment

  - **CDK CLI Version  :** 1.98.0 (build 79f4512)
  - **Framework Version:** 
  - **Node.js Version:** v12.22.1
  - **OS:** macOS
  - **Language (Version):**  typescript: 4.0.2

### Other

--- 

This is :bug: Bug Report

**Comment by i05nagai** [comment]
I had a similar use case where I want to add some specific tags to the lambda created by `AwsCustomResource` class.

The actual lambda can be found directly under the stack. That's how `SingletonLamdba` class ensures the lambda is singleton over the stack. The logic is defined here: https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-lambda/lib/singleton-lambda.ts#L128 The following code would work as a workaround.

```ts
    // UUID is defined in AwsCustomResource side. https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/custom-resources/lib/aws-custom-resource/aws-custom-resource.ts#L364
    const actualLambda = (cdk.Stack.of(this).node.findChild("AWS679f53fac002430cb0da5b7982bd2287") as lambda.Function);
    (actualLambda.node.defaultChild as lambda.CfnFunction).cfnOptions.metadata = {
      cfn_nag: {
        rules_to_suppress: [
          {
            id: "W58",
            reason: "CloudWatch logs write permissions added with managed role AWSLambdaBasicExecutionRole",
          },
        ],
      }
    };
```

If `SingletonLambda` class can expose the construct name of lambda, that's great. In this way, we don't have to rely on the hard-coded UUID inside `AwsCustomResource`. Similarly, if `SingletonLambda` class can expose the lambda as a property, it would be nicer.

```ts
  public get lambdaConstructName(): string {
    return (props.lambdaPurpose || 'SingletonLambda') + slugify(props.uuid);
  }
  // const singletonLambda = (s3Deploy.node.findChild("Provider") as lambda.SingletonFunction);
  // const actualLambda = (cdk.Stack.of(this).node.findChild(singletonLambda.lambdaConstructName) as lambda.Function);
```

**Comment by rix0rrr** [comment]
Thanks @i05nagai !
