### ISSUE TITLE
(aws-lambda-nodejs): expose the eslint bundling process as a CLI / function for Fargate

### ISSUE THREAD

**Issue by jgoux** [aws/aws-cdk#15613]
Hello,

We are using Fargate to run node.js services. We would like to benefit from the build process implemented for the aws-lambda-nodejs package in order to keep our containers small and avoid installing the dependencies from them.

### Use Case

We can use esbuild externally but we are missing : 
- Bundling native deps with a target OS (the one the bundle will be copied into) with docker
- Mark packages that contain native modules in order to generate a node_modules folder along with the final bundle
The goal is to produce an assets folder containing everything needed and COPY it inside our docker image.

### Proposed Solution

If the code doing the bundling could be isolated and exported it would be awesome for our Fargate use case.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
I'm sure this would be very helpful. I'm not sure this needs to go into CDK core right away. Ultimately `aws-lambda-nodejs` is just another construct library, and so you can reimplement the code in there, and publish it to https://constructs.dev/ for everyone to benefit from. Maybe someone already has. If the demand and solution have been proven out, we may reconsider integration the solution into the core library.
