### ISSUE TITLE
(@aws-cdk/aws-ec2): Using existing VPC (non default ) from AWS account of app deployment 

### ISSUE THREAD

**Issue by vineet85s** [aws/aws-cdk#15619]
## :question: General Issue

I am trying to create App (containing EC2, Load balancer  etc) using CDK . The app will be deployed in various AWS account in same region via jenkins pipeline in VPC of choice . To do this , I want to import VPC that is existing in each AWS account to be used when CDK deploy is triggered. Each account has its own VPC.
I could not find any way to achieve this. I tired fromlookup but it hardcodes name or VPC ID to work. I also tried parameterising the VPC ID but that also does not work.

What is the best way to import existing vpc to accomplish the automation ? 

### Environment

  - **CDK CLI Version:**  1.111.0 (build 556ca93)
  - **Module Version:** 
  - **Node.js Version:** v14.17.3
  - **OS:** macOS Mojave 
  - **Language (Version):**  Version 4.3.5

**Comment by vikloud** [comment]
I tried with SSM parameter
1. Create a  vpcNetId parameter via aws cli in the AWS account .
2. Defined a type like 
`const ssmVpcValue = ssm.StringParameter.valueForStringParameter(this, 'vpcNetId')`

3. used the above value in lookup 

```
    const vpcId = ec2.Vpc.fromLookup(this, 'VPC', {
      vpcId: ssmVpcValue
    })
```

**Comment by nohack** [comment]
What are the vpc lookup parameters you wanted to use.vpc id is not mandatory btw.

https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ec2.VpcLookupOptions.html

**Comment by peterwoodworth** [comment]
Thanks for the answer @nohack, this is correct. @vineet85s if you want to import an existing Vpc with fromLookup, all you have to do is give enough LookupOptions (linked above) in any combination which filter down to exactly one Vpc in your account. For example you could accomplish that by assigning those [Vpcs a special tag](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ec2.VpcLookupOptions.html#tags) which specifies you want to use them with this Cdk project.

**Comment by vineet85s** [comment]
fromlookup used either VPC ID or tags .. resulting in hardcoding or either ID or Tags..  which was not solving my problem. I was able to get the solution via SSM parameter and dynamic referencing then synthesising the stack to get the value during the runtime.

This is solved now.
