### ISSUE TITLE
(aws-cloudfront): Can EdgeFunction be environment-agnostic?

### ISSUE THREAD

**Issue by NickDarvey** [aws/aws-cdk#15620]
### The Question

Would it be possible to make `@aws-cdk/aws-cloudfront`'s `EdgeFunction` environment-agnostic? Presently it's not because it relies on the region to build the name of a SSM parameter.

https://github.com/aws/aws-cdk/blob/dd8466f548a368541fa16461e325b269914bc0af/packages/%40aws-cdk/aws-cloudfront/lib/experimental/edge-function.ts#L148-L151

I'm not super familiar with the technologies in question, but it looks like SSM is region-specific.

https://github.com/aws/aws-cdk/blob/dd8466f548a368541fa16461e325b269914bc0af/packages/%40aws-cdk/aws-cloudfront/lib/experimental/edge-function/index.js#L9-L10

Does this mean the parameter can be disambiguated without including the region name?

```typescript
const parameterName = `${parameterNamePrefix}/${this.node.path}`;
```

### Environment

  - **CDK CLI Version:** 1.114.0
  - **Module Version:** 1.114.0
  - **Node.js Version:** 14.17.2
  - **OS:** All
  - **Language (Version):** Typescript 4.3.5

**Comment by peterwoodworth** [comment]
Is there a reason you'd like to see EdgeFunction be environment-agnostic? I could relabel this as a feature request @NickDarvey

**Comment by NickDarvey** [comment]
So that it doesn't force the stack that I use it in to be environment-specific. 
I wasn't sure it was even possible, but if it is, then yes please make it a feature request @peterwoodworth!
