### ISSUE TITLE
(pipelines): Property 'addWave' does not exist on type 'CdkPipeline'

### ISSUE THREAD

**Issue by james-kontralto** [aws/aws-cdk#15635]
When creating a CDK Pipeline and calling the addWave() method, an error is thrown - `Property 'addWave' does not exist on type 'CdkPipeline'`.

### Reproduction Steps
1) Create a new Typescript app using `cdk init app --language typescript`.

2) Add the pipelines module with `yarn add @aws-cdk/pipelines`.

2) Use the following library code, which only has a single line added to the end of the documentation's example pipeline definition in order to add a Wave.

```
import { Stack, StackProps, Construct, SecretValue } from '@aws-cdk/core';
import { CdkPipeline, SimpleSynthAction } from '@aws-cdk/pipelines';

import * as codepipeline from '@aws-cdk/aws-codepipeline';
import * as codepipeline_actions from '@aws-cdk/aws-codepipeline-actions';

export class MyPipelineStack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);

    const sourceArtifact = new codepipeline.Artifact();
    const cloudAssemblyArtifact = new codepipeline.Artifact();

    const pipeline = new CdkPipeline(this, 'Pipeline', {
      pipelineName: 'MyAppPipeline',
      cloudAssemblyArtifact,

      sourceAction: new codepipeline_actions.GitHubSourceAction({
        actionName: 'GitHub',
        output: sourceArtifact,
        oauthToken: SecretValue.secretsManager('GITHUB_TOKEN_NAME'),
        trigger: codepipeline_actions.GitHubTrigger.POLL,
        // Replace these with your actual GitHub project info
        owner: 'GITHUB-OWNER',
        repo: 'GITHUB-REPO',
      }),

      synthAction: SimpleSynthAction.standardNpmSynth({
        sourceArtifact,
        cloudAssemblyArtifact,

        // Use this if you need a build step (if you're not using ts-node
        // or if you have TypeScript Lambdas that need to be compiled).
        buildCommand: 'npm run build',
      }),
    });
    const coreInfraWave = pipeline.addWave('CoreInfra');
  }
}
```

3) Use the following app definition:

```
#!/usr/bin/env node
import 'source-map-support/register';
import * as cdk from '@aws-cdk/core';
import { MyPipelineStack } from '../lib/cdk-pipeline-test2-stack';

const app = new cdk.App();
new MyPipelineStack(app, 'MyPipelineStack', {
});
```

4) Delete the test folder with `rm -rf test/`.

5) Run `yarn run build`.

### What did you expect to happen?

Code would compile as normal, and I would be able to add a Wave to the CDK Pipeline.

### What actually happened?

An error was thrown, `error TS2339: Property 'addWave' does not exist on type 'CdkPipeline'.`.

### Environment

  - **CDK CLI Version  :** 1.114.0
  - **Framework Version:** 1.114.0
  - **Node.js Version:** v14.17.3
  - **OS               :** Linux(Pop! OS 20.04)
  - **Language (Version):** Typescript 4.3.5

### Other

I checked out the AWS CDK repo at tag `v1.114.0` and I found the `addWave` method, but am not familiar enough with the codebase to know why it's not available on the construct. Originally I discovered this issue on an existing project where I upgraded from 1.113 -> 1.114, but created another one with the steps shown above to confirm the bug on a brand new project using `v1.114.0`.

--- 

This is :bug: Bug Report

**Comment by hoegertn** [comment]
The new class is CodePipeline and not CdkPipeline anymore

There is a complete new API

**Comment by james-kontralto** [comment]
Apologies, I missed the new API - there looks to be plenty of documentation on it. Closing this issue, thanks @hoegertn for the response!
