### ISSUE TITLE
@aws-cdk/aws-ecs-patterns: Add ability to set healthCheck for QueueProcessingFargateService

### ISSUE THREAD

**Issue by paya-cz** [aws/aws-cdk#15636]
`QueueProcessingFargateService` currently does not offer `healthCheck` options property, even though it is very simple to add it here:
https://github.com/aws/aws-cdk/blob/8668e15b8a85b369153e9d36d4eab016fc8856f4/packages/%40aws-cdk/aws-ecs-patterns/lib/fargate/queue-processing-fargate-service.ts#L124

So, there is no good way to set a `healthCheck` on a container.

### Use Case

I use healthcheck to make sure the tasks are healthy. [Fargate ignores `HEALTHCHECK` instruction in `Dockerfile`](https://github.com/aws/containers-roadmap/issues/1443), so I am forced to supply the `healthCheck` instruction via CDK. However, `QueueProcessingFargateService` does not let me.

### Proposed Solution

Add a healthcheck property here:
https://github.com/aws/aws-cdk/blob/8668e15b8a85b369153e9d36d4eab016fc8856f4/packages/%40aws-cdk/aws-ecs-patterns/lib/fargate/queue-processing-fargate-service.ts#L10

Pass it to the container here:
https://github.com/aws/aws-cdk/blob/8668e15b8a85b369153e9d36d4eab016fc8856f4/packages/%40aws-cdk/aws-ecs-patterns/lib/fargate/queue-processing-fargate-service.ts#L124

### Workaround

This is not nice, but works.

```js
// @ts-ignore
service.taskDefinition.defaultContainer!.props.healthCheck = <ecs.HealthCheck>{
    command: ['CMD', 'node /app/healthcheck.js'],
    interval: cdk.Duration.seconds(15),
    retries: 3,
    timeout: cdk.Duration.seconds(5),
};
```

---

This is a :rocket: Feature Request

**Comment by paya-cz** [comment]
Same problem for `ScheduledFargateTask`:
https://github.com/aws/aws-cdk/blob/8668e15b8a85b369153e9d36d4eab016fc8856f4/packages/%40aws-cdk/aws-ecs-patterns/lib/fargate/scheduled-fargate-task.ts#L118

**Comment by peterwoodworth** [comment]
Hey @paya-cz, sorry for the slow response

Would you like to submit a PR for this feature request yourself? I can't guarantee anyone from the team will be able to tackle this anytime soon

**Comment by paya-cz** [comment]
This issue seems to be somewhat related to #8320, perhaps both issues could be tackled at the same time one day.
