### ISSUE TITLE
(vpc.selectSubnets): Cannot find a subnet by subnetGroupName in a lookup VPC

### ISSUE THREAD

**Issue by ludbek** [aws/aws-cdk#15637]
Unable to get subnets by their group name in a lookup VPC

### Reproduction Steps

I have created a vpc in my infrastructure repo and is  referenced in another repo. When I try to get subnets with group name  `rds-private-subnet`, I get following error.

```
Error: There are no subnet groups with name 'rds-private-subnet' in this VPC. Available names: public-subnet,private-subnet
    at LookedUpVpc.selectSubnetObjectsByName (/Users/user/projects/auth/node_modules/@aws-cdk/aws-ec2/lib/vpc.ts:343:13)
```
Below is the code snippet that caused it.
```typescript
// @ infrastructure/stack.ts
   const privateSubnectConfiguration = {
      cidrMask: 24,
      name: "private-subnet",
      subnetType: ec2.SubnetType.PRIVATE,
    };

    const publicSubnectConfiguration = {
      cidrMask: 24,
      name: "public-subnet",
      subnetType: ec2.SubnetType.PUBLIC,
    };

    const rdsPrivateSubnetConfiguration = {
      cidrMask: 24,
      name: "rds-private-subnet",
      subnetType: ec2.SubnetType.PRIVATE,
    };

const vpc = new ec2.Vpc(this, "test-vpc", {
      cidr: "10.0.0.0/16",
      subnetConfiguration: [
        publicSubnectConfiguration,
        privateSubnectConfiguration,
        rdsPrivateSubnetConfiguration,
      ],
      maxAzs: 2,
      natGateways: 1,
      natGatewayProvider,
    });

// @ auth/stack.ts
const vpc = ec2.Vpc.fromLookup(this, "vpc", {
      vpcId: <vpc-id>
 });

const rdsSubnetGroup = new rds.SubnetGroup(this, "RDS subnet group", {
      description: "RDS subnet group",
      vpc: vpc,
      vpcSubnets: vpc.selectSubnets({
        subnetGroupName: "rds-private-subnet",
      }),
    });
```

### What did you expect to happen?
I expected to get the subnets with group name `rds-private-subnet`.

### What actually happened?
`cdk` threw an error saying the subnets with group name `rds-private-subnet` does not exist.

```
Error: There are no subnet groups with name 'rds-private-subnet' in this VPC. Available names: public-subnet,private-subnet
    at LookedUpVpc.selectSubnetObjectsByName (/Users/user/projects/auth/node_modules/@aws-cdk/aws-ec2/lib/vpc.ts:343:13)
```

### Environment

  - **CDK CLI Version  :*1.112.0*
  - **Framework Version:**
  - **Node.js Version:*15.3.0* 
  - **OS               :*macos*
  - **Language (Version):*~3.9.7* 

### Other

--- 

This is :bug: Bug Report

**Comment by njlynch** [comment]
Hi @ludbek ,

Thanks for the bug report. I'm afraid I can't reproduce the issue with the given code. My stack is able to successfully find the named subnets from the looked up VPC.

Is it possible that the `rds-private-subnet` configuration was added after the fact, and that stack hasn't yet been updated/deployed?

**Comment by ludbek** [comment]
@njlynch Thanks for taking a look at it. I can confirm that 'rds-private-subnet' has already been created.

**Comment by peterwoodworth** [comment]
Hey @ludbek,

I was able to reproduce this error if I:
- First lookup the VPC  _before_ configuring the RDS private subnet
  - this will cache `public-subnet` and `private-subnet` in your `cdk.context.json`
- Then add the RDS subnet to the VPC and deploy
- Add the RDS subnet group to the stack with the looked up VPC. Your `cdk.context.json` already has the data cached for your VPC from when we first looked up the VPC, so it will use this cached data instead of actually getting data.

To fix this, you can simply delete your `cd.context.json` or you can [manage your cached data](https://docs.aws.amazon.com/cdk/latest/guide/context.html#context_viewing)

**Comment by ludbek** [comment]
@peterwoodworth The steps you mentions sounds about right.

**Comment by peterwoodworth** [comment]
Great, let me know if you need any more help 😄
