### ISSUE TITLE
(cli): Consider including an HTTPS policy to bootstrap bucket

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#15658]
Our assets S3 bucket does not comply with [`s3-bucket-ssl-requests-only`](https://docs.aws.amazon.com/config/latest/developerguide/s3-bucket-ssl-requests-only.html).

### Use Case

Security best practices recommend to enforce that all requests to an S3 bucket will use SSL:
https://aws.amazon.com/premiumsupport/knowledge-center/s3-bucket-policy-for-config-rule/

### Proposed Solution

We should consider adding that to the assets bucket we create as part of bootstrapping.

### Other

This was brought up as part of a pen test to a customer service.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
Do you know why this isn't good enough?

https://github.com/aws/aws-cdk/blob/b934976f057cd395de660dc4099e2303415cdc78/packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml#L193-L201

**Comment by eladb** [comment]
Seems like this is what we need.
