### ISSUE TITLE
(aws-autoscaling): support for terminationPolicies

### ISSUE THREAD

**Issue by nwalters512** [aws/aws-cdk#15654]
I'd like to be able to configure the [termination policies](https://docs.aws.amazon.com/autoscaling/ec2/userguide/as-instance-termination.html) on an `AutoScalingGroup`. 

### Use Case

I'm currently using the L2 `AutoScalingGroup` construct. I can configure the termination policies with the L1 `CfnAutoScalingGroup` via the `terminationPolicies` prop, but I'd like to avoid falling back to the L1 construct if possible.

### Proposed Solution

The solution could look as simple as this:

```ts
import * as autoscaling from '@aws-cdk/aws-autoscaling';

new autoscaling.AutoScalingGroup(this, 'ASG', {
  // ...
  terminationPolicies: ["ClosestToNextInstanceHour"],
};
```

For symmetry with other pieces of the CDK, the policies could be represented as an enum:

```ts
import * as autoscaling from '@aws-cdk/aws-autoscaling';

new autoscaling.AutoScalingGroup(this, 'ASG', {
  // ...
  terminationPolicies: [autoscaling.TerminationPolicy.CLOSEST_TO_NEXT_INSTANCE_HOUR],
};
```

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by nwalters512** [comment]
Hey @rix0rrr, can you help with triaging this? I'd be happy to help with implementation if I can get some assurance that this change would be accepted.

**Comment by rix0rrr** [comment]
Sounds like a good idea, and your enum solution does look like the right solution. I would totally accept this!
