### ISSUE TITLE
(@aws-cdk/aws-api-gateway): `endpointExportName` not using correct key in the outputs file

### ISSUE THREAD

**Issue by ChrisSargent** [aws/aws-cdk#15664]
Using `endpointExportName` does not put the value under the correct name in the outputs file

Using this code:

```ts
    const restApi = new api.RestApi(this, "test-api", {
      endpointExportName: "EndpointTestName",
    });
```

Results in the following output

```json
{
  "CdkTestStack": {
    "testapiEndpoint4AE34D29": "https://xxxxxxxxxx.execute-api.eu-west-2.amazonaws.com/prod/"
  }
}
```

### Reproduction Steps

https://github.com/ChrisSargent/cdk-issues
Run `cdk deploy` and view the outputs.json file.

### What did you expect to happen?

To have an `outputs.json` file like:
```json
{
  "CdkTestStack": {
    "EndpointTestName": "https://xxxxxxxxxx.execute-api.eu-west-2.amazonaws.com/prod/"
  }
}
```

### What actually happened?

The outputs.json file

```json
{
  "CdkTestStack": {
    "testapiEndpoint4AE34D29": "https://xxxxxxxxxx.execute-api.eu-west-2.amazonaws.com/prod/"
  }
}
```

The CW Stack

<img width="1735" alt="Screenshot 2021-07-20 at 16 27 28" src="https://user-images.githubusercontent.com/12176122/126341669-cbfeafaa-b23e-4560-8b4a-319fcf41dd01.png">

### Environment

  - **CDK CLI Version:** 1.113.0
  - **Framework Version:**
  - **Node.js Version:** 14
  - **OS               : ** MacOS
  - **Language (Version):** Typescript

### Other

I tried a `console.log(props)` at this line: https://github.com/aws/aws-cdk/blob/b3a7d5ba67bec09e422c0c843d7dee4653fe9aec/packages/%40aws-cdk/aws-apigateway/lib/restapi.ts#L554 and it has the expected value for `endpointExportName`, as probably the screenshot from the AWS console demonstrates.

**Comment by jumic** [comment]
The property `endpointExportName` can be used to specify the export name for the value in the CloudFormation outputs. In the last column (named 'Export name'), you can see this value in your screenshot. 

https://github.com/aws/aws-cdk/blob/b3a7d5ba67bec09e422c0c843d7dee4653fe9aec/packages/%40aws-cdk/aws-apigateway/lib/restapi.ts#L159-L164

As far as I know, there is no standard option to change the name in the outputs.json. As a workaround, you could solve this by overriding the logical id:
```
(restApi.node.tryFindChild('Endpoint') as cdk.CfnResource).overrideLogicalId('myCustomName');
```
In this case, in file output.json the output should be named 'myCustomName' instead of 'testapiEndpoint4AE34D29'.

**Comment by ChrisSargent** [comment]
thanks for the quick answer! Okay, I see. Looks like in my other code that I was comparing this to we were providing an id but I was seeing some slightly inconsistent naming. Sorry for the false report.

FYI, use case is being able to get the valid rest API endpoint from a totally separate front end in another package, hence important to have a stable name for the field.

**Comment by NGL321** [comment]
Looks like this has been answered, thanks @jumic! 🎉 🎉 🎉 

Closing now due to resolution, please feel free to reopen if I am in error!

😸 😷
