### ISSUE TITLE
(core): publish v2 of cdk core library

### ISSUE THREAD

**Issue by eduardomourar** [aws/aws-cdk#15668]
Currently, in CDK v2, we are unable to consume the CDK core library without installing the whole [`aws-cdk-lib`](https://www.npmjs.com/package/aws-cdk-lib).

### Use Case

I would like to extend functionalities from the core library, which will not need/touch other AWS services.

### Proposed Solution

Ideally the v2 for NPM library [@aws-cdk/core](https://www.npmjs.com/package/@aws-cdk/core) should be available, even if it needs to be renamed to avoid confusion.

---

This is a :rocket: Feature Request

**Comment by nija-at** [comment]
Hi @eduardomourar - what specific parts of the core library are you looking to consume?

**Comment by eduardomourar** [comment]
Currently, I have the following dependency:

```ts
import { App, CfnResource, CfnResourceProps, CfnDeletionPolicy, DefaultStackSynthesizer, FileSystem, Fn, IStackSynthesizer, Stack } from "aws-cdk-lib/lib/core";
```

But, because this will most likely be expanded, I have no objection in depending on the full content of `/package/@aws-cdk/core`.

**Comment by nija-at** [comment]
Unfortunately, we have decided to go with monolithic packaging for CDKv2. This RFC goes into the reasons for this - https://github.com/aws/aws-cdk-rfcs/blob/master/text/0006-monolothic-packaging.md

We have separated out the "constructs" part of the CDK into [its own module](https://github.com/aws/constructs/), so users can build their own CDKs. 

For users who want to extend the AWS CDK, they will need to use the 'aws-cdk-lib'.
If you are building a construct library, the best practice is to declare 'aws-cdk-lib' as a `devDependency` and `peerDependency' with a caret version range. 
This way your construct library does not bring in 'aws-cdk-lib' but tells users that they need to bring it in, which is what they will need to do if they're working with the AWS CDK.

If you have a specific requirement that is not satisfied here, I'm interested to hear why this is not a good option. And why having a separate core library would be better.

**Comment by eduardomourar** [comment]
I have a meeting with @eladb in August to show him what we've got at [Stedi](https://docs.stedi.com/) in regards to CDK. In sum, we have a service that accepts a CloudFormation-like template, which can be synthesized using a simplified version of the AWS CDK.

Think of this along the lines of cdktf and cdk8s, but requires less customization because we are a lot closer to CloudFormation syntax. In our case, the constructs are not built to interact with AWS CloudFormation at all (just like cdktf and cdk8s) but we have a bundle size of around 161MB with the additional AWS specific code. By removing them, we reduce our bundle size to 35MB.

Just to clarify, we are not asking to remove the core library from `aws-cdk-lib`, only to publish it as a separate library.

**Comment by nija-at** [comment]
If you are building your own cdk (like cdktf or cdk8s), you should only be using 'constructs' module, custom building your own synthesis mechanisms.

On the other hand, if you are building constructs for the AWS CDK, you should be depending on 'aws-cdk-lib'.

We currently don't have a solution for "cloudformation like" CDK that is not the AWS CDK. 

We will need to look closely at your use case to see if there are useful concepts there that can be extracted out as independent libraries. 
For example, we would like to extract the 'token' mechanism in the AWS CDK as its own module. There may be others like that.

The previously defined 'core' module has lots of AWS specific concepts mixed in, and is not "thin" enough to be extracted as an independent module.
