### ISSUE TITLE
(module name): unable to add KMSKey to @aws-cdk/aws-mwaa construct

### ISSUE THREAD

**Issue by vincent851** [aws/aws-cdk#15670]
description of the bug: 

I am trying to use the optional KMSKey option for deploying MWAA via CDK but I am encountering weird error only on deployment. 

> 3:47:23 PM | UPDATE_FAILED        | AWS::MWAA::Environment | **********************1188E4D3
> Properties validation failed for resource **********************1188E4D3 with message:
> #/KmsKey: failed validation constraint for keyword [pattern]

I dont see anywhere that this KMS have to fit into a specific pattern. I am not understanding the error.

### Reproduction Steps

minimal amount of code that causes the bug (if possible) or a reference.
```
this.mwaa = new MWAAConstruct(this, `${Config.LOWERCASE_PREFIX}-mwaa-${stageName}`, {
            region: stageConfig.stage.awsRegion,
            stage: stageConfig.stage.stageName,
            name: `${Config.PREFIX}`,
            airflowVersion: `${Config.AIRFLOW_VERSION}`,
            environmentClass: `${Config.AIRFLOW_CLUSTER_SIZE}`,
            maxWorkers: Config.AIRFLOW_WORKER_COUNT,
            kmsKey: this.kms.key.toString(),  <<<< THIS IS THE CODE IN QUESTION
            networkConfiguration: {
                securityGroupIds: [VpcStack.securityGroup.securityGroupId],
                subnetIds: VpcStack.vpc.privateSubnets.map(subnet => subnet.subnetId)
            },
            airflowConfigurationOptions: {"core.lazy_load_plugins": "false"},
            dagS3Path: "dags",
            pluginsS3Path: "plugins.zip",
            sourceBucketArn: s3Bucket.bucketArn,
            outputBucketArn: s3Bucket.bucketArn,
            requirementsS3Path: "requirements.txt"
        });
```

### What did you expect to happen?

I expected the code deploy without any issues and added KMS to MWAA.

What were you trying to achieve by performing the steps above?

to add KMS to MWAA.

### What actually happened?

The deployment failed with the above error.

### Environment

  - **CDK CLI Version  : 1.110.0**
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               : Linux 4.9.230-0.1.ac.224.84.332.metal1.x86_64**
  - **Language (Version): Typescript ~4.0.5** 

### Other

--- 

This is :bug: Bug Report

**Comment by jumic** [comment]
Instead of `key.toString()`, you could try to use `key.keyArn` or `key.keyId`. Maybe this will work.
The `toString()` method returns the path of the construct in your stack which will not be accepted as a KMS key.

Unfortunately, the [CloudFormation documentation for MWAA](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-mwaa-environment.html#cfn-mwaa-environment-kmskey) doesn't explain in which format (e.g. key id, key ARN, alias name) the key must be specified. Therefore, I recommend to try key id or key ARN.

MWAAConstruct is a custom construct created in your stack (I can't find it in the CDK source code). Thus, we can't use it to reproduce your issue.

The MWAA module only contains L1 constructs / CloudFormation resources. Therefore, the main question is how to use the CloudFormation resource. In my opinion, it's not a bug in CDK.

**Comment by vincent851** [comment]
> Instead of `key.toString()`, you could try to use `key.keyArn` or `key.keyId`. Maybe this will work.
> The `toString()` method returns the path of the construct in your stack which will not be accepted as a KMS key.
> 
> Unfortunately, the [CloudFormation documentation for MWAA](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-mwaa-environment.html#cfn-mwaa-environment-kmskey) doesn't explain in which format (e.g. key id, key ARN, alias name) the key must be specified. Therefore, I recommend to try key id or key ARN.
> 
> MWAAConstruct is a custom construct created in your stack (I can't find it in the CDK source code). Thus, we can't use it to reproduce your issue.
> 
> The MWAA module only contains L1 constructs / CloudFormation resources. Therefore, the main question is how to use the CloudFormation resource. In my opinion, it's not a bug in CDK.

I tried the `key.keyArn` and `key.keyId` none of them work. I resorted to `key.toString()` after I tried all of them...

**Comment by vincent851** [comment]
I believe you can reproduce this by just using the above MWAA construct and create your own. Then add the KMS. see if you can deploy the construct. that is the issue. I am unable to deploy the construction using the optional KMSKey option.

**Comment by vincent851** [comment]
I want to add I was able to use `key.keyArn` to resolve this. I was unable to use `key.keyId` and `key.toString()`

**Comment by rix0rrr** [comment]
Glad to hear it's solved. You can report issues with the documentation on the documentation page, it may help people in the future:

![2021-07-22 at 10 50](https://user-images.githubusercontent.com/524162/126613068-5b5422e5-ec12-4472-ad57-76f7e22d1bda.png)
