### ISSUE TITLE
(eks): EKS cluster fails deletion due to long name

### ISSUE THREAD

**Issue by chauncey-garrett** [aws/aws-cdk#15672]
I have an EKS cluster stack that I'm currently debugging (see #15608). I've noticed that the stack will fail to delete if the cluster name is too long. See the screenshots below. The long name that is generated is not (intentionally) of my doing. It appears that something is being concatenated or not trimmed (or both).

### Reproduction Steps

I have the cluster in a nested stack. This may be part of the issue because of the extra name length.

### What did you expect to happen?

Stack to delete without error.

#### Error log from lambda

![CleanShot 2021-07-20 at 13 04 02](https://user-images.githubusercontent.com/302358/126374015-35cb1171-153e-4469-b8a9-c3c4bf66b206.png)

#### EKS console name of cluster

![CleanShot 2021-07-20 at 13 03 20](https://user-images.githubusercontent.com/302358/126374079-b55207a4-1935-4259-9a71-385cf69fca82.png)

#### CF error

![CleanShot 2021-07-20 at 13 03 03](https://user-images.githubusercontent.com/302358/126374119-56158ca9-c165-4761-a4a8-de7fe30a431d.png)

### Environment

- CDK CLI Version : 7.18.1
- Framework Version: v1.114.0
- Node.js Version: v16.4.1
- Language (Version): TypeScript (3.9.10)

--- 

This is :bug: Bug Report

**Comment by otaviomacedo** [comment]
Hi, @chauncey-garrett 

I am unassigning and marking this issue as `p2`, which means that we are unable to work on this immediately.

We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://join.slack.com/t/cdk-dev/shared_invite/zt-mso6p56d-qJp7SOTBvMaQuDrx7R2wHg) to solicit support for reprioritization.

**Comment by otaviomacedo** [comment]
I doubt that the two are related, but it's possible.
