### ISSUE TITLE
EFS: Unable to read/write to EFS inside a Fargate Docker Container

### ISSUE THREAD

**Issue by eob** [aws/aws-cdk#15675]
I can successfully create and mount an EFS volume to a Fargate Docker container, but I can not read or write to it. (I get Permission Denied errors).

I have customized the AWS-provided `ApplicationLoadBalancedFargateService` class with the following:

```
// FILESYSTEM
const fs = new efs.FileSystem(this, "IndexFilesystem", {
  vpc: vpc,
  performanceMode: efs.PerformanceMode.GENERAL_PURPOSE,
  throughputMode: efs.ThroughputMode.BURSTING,
  fileSystemName: "indexFilesystem"
})
  
// VOLUME
const volume = {      
  name: "indexVolume",
  efsVolumeConfiguration: {
    fileSystemId: fs.fileSystemId,
    TransitEncryption: 'ENABLED',
  },
};

// this is a FargateTaskDefinition object
this.taskDefinition.addVolume(volume)  


// MOUNT POINT
const mountPoint = {
  containerPath: "/data",
  sourceVolume: volume.name,
  readOnly: false,
};

// This is the container created inside ApplicationLoadBalancedFargateService
container.addMountPoints(mountPoint)

// PROVIDE ACCESS
// this.service is the FargateService
this.service.connections.allowFrom(fs, Port.tcp(2049));
this.service.connections.allowTo(fs, Port.tcp(2049));
```

### Reproduction Steps

Modify the ApplicationLoadBalancedFargateService template to include that code.

### What did you expect to happen?

Expect `/data` to be readable and writable.

### What actually happened?

I get **Permission Denied** errors when reading/writing to `/data`

### Environment

  - **CDK CLI Version  :** 1.108.0 (build b23f781)
  - **Framework Version:** 
  - **Node.js Version:** 
  - **OS               :** OSX
  - **Language (Version):** TypeScript

### Other

Everything synthesizes fine -- there's just no connectivity.

--- 

This is :bug: Bug Report

**Comment by NGL321** [comment]
Hey @eob,

Thank you for submitting this report. Someone on the team will take a look into it as soon as they are able!

😸 😷

**Comment by jeznag** [comment]
In case it helps, here's a gist where I got it working: https://gist.github.com/jeznag/623132d2a98eff5392acd702702f1ef7

I'm on     "@aws-cdk/aws-ecs": "1.118.0",

**Comment by nija-at** [comment]
@eob - I'm not familiar with the EFS/Fargate integration. Can you help identify what configuration that should be in the template is missing?

@jeznag - can you help us identify what @eob might have missed here?

**Comment by eob** [comment]
Hi @jeznag and @nija-at,

Thanks for the help. I was able to get this resolved by wiring everything up in a slightly different way -- I'm afraid I"m not sure exactly which of the changes was the one that caused things to transition from not working to working,
