### ISSUE TITLE
(aws-dynamodb): Support ContributorInsightsSpecification for Global Secondary Index

### ISSUE THREAD

**Issue by schwar** [aws/aws-cdk#15671]
The Table construct currently supports the [contributorInsightsEnabled](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-dynamodb.Table.html#contributorinsightsenabled) property in order to specify the base table [ContributorInsightsSpecification](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html#cfn-dynamodb-contributorinsightsspecification-enabled). This request is to support the same idea in the [GlobalSecondaryIndexProps](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-dynamodb.GlobalSecondaryIndexProps.html). This is supported in CloudFormation [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-dynamodb-gsi.html#cfn-dynamodb-contributorinsightsspecification-enabled).

### Use Case
I would like to enable CloudWatch Contributor Insights on my global secondary index.

### Proposed Solution
Add a contributorInsightsEnabled? property to GlobalSecondaryIndexProps and use that to set the ContributorInsightsSpecification in the underlying CloudFormation.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by skinny85** [comment]
Thanks for opening the issue @schwar! We encourage community contributions, so if you'd like to open us a PR adding this functionality, that would be amazing! Our "Contributing" guide: https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md.

Thanks,
Adam

**Comment by schwar** [comment]
This is still an open request for a missing feature.
