### ISSUE TITLE
(v2.0.0.rc* aws-cdk/pipelines): Cannot import aws-cdk/pipelines - Python

### ISSUE THREAD

**Issue by kyri-petrou** [aws/aws-cdk#15683]
The aws-cdk.pipelines module is not importable in v2.0.0.rc* in Python.

I have also noticed that the sections in the documentation referring to the aws-cdk/pipelines module have been removed both from the main (Typescript) and Python documentation pages. Has this module been deprecated or moved to another module in v2?

### Reproduction Steps

``` bash
npm install -g aws-cdk@next
pip install aws-cdk-lib==2.0.0.rc13 "constructs>=10.0.0"
python -c "from aws_cdk import pipelines"
```

### What did you expect to happen?

For the command not to fail

### What actually happened?

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'pipelines' from 'aws_cdk' (/home/jovyan/.conda/envs/cmd-cdk/lib/python3.8/site-packages/aws_cdk/__init__.py)
```

**Comment by rix0rrr** [comment]
Experimental modules are not available in v2 yet, since we are committing to API stability and experimental modules are not guaranteed to be API stable.
