### ISSUE TITLE
(cdk-CfnFlow): Unable to add task property

### ISSUE THREAD

**Issue by shiv-lch** [aws/aws-cdk#15680]
Team - I'm trying to create an appflow job and one of the block is to pass 'Task Property' using 'TaskPropertiesObjectProperty' class. But it fails with below error, and I could figure out, the error points to 'task_property' . 

**Class Reference** 
>> classCfnFlow.TaskPropertiesObjectProperty(*, key, value)

**Code**
```python
myflow.CfnFlow.TaskProperty(
                        task_type='Map_all',
                        source_fields=[],
                        task_properties=myflow.CfnFlow.TaskPropertiesObjectProperty(key='EXCLUDE_SOURCE_FIELDS_LIST',value=[]),
                        connector_operator=myflow.CfnFlow.ConnectorOperatorProperty(zendesk='NO_OP')
```

**Error**
jsii.errors.JSIIError: Value did not match any type in union: Value did not match any type in union: Value did not match any type in union: Expected array type, got {"$jsii.struct":{"fqn":"@aws-cdk/aws-appflow.CfnFlow.TaskPropertiesObjectProperty","data":{"key":"EXCLUDE_SOURCE_FIELDS_LIST","value":[]}}}, 

**Reference URL** https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_appflow/CfnFlow.html#aws_cdk.aws_appflow.CfnFlow.TaskPropertiesObjectProperty

**Reproduction Steps**
Create new appflow job with 'exclusion list as []' along with 'map_all' task_type. 'Map_all' is supported by CFN/SDK and tested working correcting via CFN. 

**What did you expect to happen?**
Create new appflow job mapping all fields from the source object in Zendesk. 

**What actually happened?**
Getting union/value not match error

Environment
CDK CLI Version : 1.114.0 (build 7e41b6b)
Framework Version:
Language: Python.3.6.8

**Comment by peterwoodworth** [comment]
It looks like the `value` should be a `string`. You currently have it as an empty array

**Comment by shiv-lch** [comment]
Well, the way Appflow works was - we need to supply all 4 attributes (TaskType, Sourcefields, TaskProperties & Connector Operator' to get the valid response from Appflow backend create-API. Below is the snippet from CFN (yaml) and it worked successfully. I need to translate this block to CDK/Python and it fails.

,,,
      Tasks:
        - TaskType: Map_all
          SourceFields: []
          TaskProperties:
            - Key: EXCLUDE_SOURCE_FIELDS_LIST
              Value: '[]'
          ConnectorOperator:
            Zendesk: NO_OP
,,,


As you have noted, there is no 'exclusion' to the source field and it was intended, hence it's an empty list. But it looks CDK class 'TaskPropertiesObjectProperty' expects both key and value to be string. 

Is there a way around to pass it as string to get an empty list that will look like the above YAML block ?

**Comment by peterwoodworth** [comment]
@shiv-lch task_properties wants to take in an array. Here's an example

```python
tasks=[appflow.CfnFlow.TaskProperty(
    task_type='Map_all',
    source_fields=['fes','yub'],
    task_properties=[appflow.CfnFlow.TaskPropertiesObjectProperty(key='KEY1',value='VALUE1'), appflow.CfnFlow.TaskPropertiesObjectProperty(key='KEY2',value='VALUE2')],
    connector_operator=appflow.CfnFlow.ConnectorOperatorProperty(zendesk='NO_OP')
)],
```

**Comment by shiv-lch** [comment]
Thanks.
