### ISSUE TITLE
(core): Use the Output values (not tokens) of first stack in second stack in a CDK App.

### ISSUE THREAD

**Issue by gbvanrenswoude** [aws/aws-cdk#15695]
### Situation
Situation: CDK app with 2 stacks. The first stack deploys the backend, the 2th deploys the frontend. In the frontend stack we need the APIGW urls and API tokens. The packaging off the frontend app is done with an off stack command (like npm run build) (e.g. Angular + webpack environment plugin)

### Current behavior
Current behavior is that cdk runs synth on both stacks and starts deploying them one by one. The packaging then in the second stack will be done at synth time using {TOKEN} when using this off stack command (for example doing a npm run build)

### Proposed feature 
We should be able to run cdk synth for the 2th stack of a cdk app only after cdk has deployed the first stack. For example one does need these stack outputs in an npm run build. Maybe this could be a flag in the InfrastructureStack class / done in the dependsOn method. If that all is hard, or too far off the cdk design, maybe implement multiple App() support or make people able to chain apps.

This is a :rocket: Feature Request

Edit: cdk pipelines could wrap certain behavior, but not every customer does want another cicd solution.

**Comment by rix0rrr** [comment]
It seems that what you want is the following:

```
┌─────────────┐      ┌──────────────┐    use   ┌──────────────┐     ┌────────────────┐
│             │      │              │  outputs │              │     │                │
│Build Backend│─────▶│Deploy Backend│─────────▶│Build Frontend│────▶│Deploy Frontend │
│             │      │              │          │              │     │                │
└─────────────┘      └──────────────┘          └──────────────┘     └────────────────┘
```

Where CDK has been designed to do this instead:

```
┌─────────────┐             ┌────────────────┐               
│             │             │                │               
│Build Backend│────────────▶│ Deploy Backend │               
│             │             │                │               
└─────────────┘             └────────────────┘               
       ▲                             ▲                       
       │  reference                  │ use actual            
       │ using tokens                │ output values         
       │                             │                       
┌──────────────┐            ┌────────────────┐               
│              │            │                │               
│Build Frontend│───────────▶│Deploy Frontend │               
│              │            │                │               
└──────────────┘            └────────────────┘               
```

That is, you can symbolically use the outputs from your backend in your frontend infrastructure, and the actual values will be substituted at deploy time.

If you definitely want to do the first solution, you can write your own shell script to first trigger the backend deploy, potentially using `cdk deploy --outputs-file outputs.json` to capture the outputs, and then trigger your second deploy.

**Comment by gbvanrenswoude** [comment]
Thanks for getting back, we broke up the App in 2 Apps for now. The multiple App support suggestion still stands. All the best with this nice product, we love it :)
