### ISSUE TITLE
AWS Lambda Destinations: EventBridgeDestination created when creating Lambda destination using CDK for .NET

### ISSUE THREAD

**Issue by awsanitha** [aws/aws-cdk#15691]
description of the bug:

`EventBridgeDestination` is created when creating Lambda destination using CDK for .NET

### Reproduction Steps

minimal amount of code that causes the bug (if possible) or a reference.
``` c#
// Create Lambda function
var updateInventoryLambda = new Function(this,"UpdateInventoryLambdaDemo", new FunctionProps
{
    Runtime = Runtime.DOTNET_CORE_3_1,
    Handler = "UpdateInventoryLambda::UpdateInventoryLambda.UpdateInventory::FunctionHandler",
    Role = iamLambdaRole,
    Code = Code.FromAsset("lambdas/UpdateInventoryLambda.zip"),
    Timeout = Duration.Minutes(5)
});
var placeOrderLambda = new Function(this,"PlaceOrderLambdaDemo", new FunctionProps
{
    Runtime = Runtime.DOTNET_CORE_3_1,
    Handler = "PlaceOrderLambda::PlaceOrderLambda.PlaceOrder::FunctionHandler",
    Role = iamLambdaRole,
    Code = Code.FromAsset("lambdas/PlaceOrderLambda.zip"),
    Timeout = Duration.Minutes(5),
    OnSuccess = new LambdaDestination(updateInventoryLambda, new LambdaDestinationOptions
    {
        ResponseOnly = true
    })
});
```
Please see the `OnSuccess` property of `placeOrderLambda` function

### What did you expect to happen?

LambdaDestination to be created 

### What actually happened?

EventBridge destination was created

### Environment

  - **CDK CLI Version  :1.111.0
  - **Framework Version:**: net core 3.1
  - **Node.js Version:** : 14.17.0
  - **OS               :macOS Catalina 10.15.7
  - **Language (Version):** : dotnet core 3.1, C#

### Other

The code is creating an eventbrodge destination rather than a LambdaDestination.

https://github.com/aws/aws-cdk/blob/7e41b6b745ff185110b7aba3db15d30bb35577bc/packages/%40aws-cdk/aws-lambda-destinations/lib/lambda.ts#L35

Lambda is a supported target. So this behaviour is incorrect. 
--- 

This is :bug: Bug Report

**Comment by NGL321** [comment]
Hey @awsanitha,

Thank you for reporting this, the repro code was exactly what was needed. However, I tried to reproduce this, but I was able to return the lambda destination without error. Could you provide the incorrect cfn template?

😸 😷

**Comment by jogold** [comment]
Hi @awsanitha,

This is how `ResponseOnly` works. It automatically creates an `EventBridgeDestination` with a Lambda target so that the response part of the event can be extracted by Event Bridge for you.

If you want a `LambdaDestination`, do not specify `ResponseOnly`

**Comment by awsanitha** [comment]
Hi @jogold - Ok, I'll try that.
