### ISSUE TITLE
aws-codebuild/Project: BuildEnvironment should support certificate

### ISSUE THREAD

**Issue by mneil** [aws/aws-cdk#15701]
The codebuild project environment definition in Cloudformation [supports a custom certificate](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-environment.html). There doesn't appear to be a first class way to add a certificate path.

### Use Case

It is sometimes necessary for projects running in a VPC connected to on-prem DNS to use their own certificate for SSL.

### Proposed Solution

As a workaround I can add it to the Project node during synthesis but it should have better support.

Allow users to set the Certificate as an [Arn]https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.Arn.html). The certificate value is an S3 arn which can be constructed from the Arn. Another option is to use the ISource implementation of S3Source. Arn seems simpler.

---

This is a :rocket: Feature Request

**Comment by skinny85** [comment]
@mneil thanks for opening the issue. If you'd be willing to open us a Pull Request adding this, that would be amazing! Our "Contributing" guide: https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md.

In the meantime, you should be able to use [escape hatches](https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html) to enable this functionality.

**Comment by mneil** [comment]
Ok, glad I wasn't just missing it :). I'm using the escape hatch already. I can try and implement this on Friday if nobody beats me to it.
