### ISSUE TITLE
(cdk-pipelines) Automatically resolving stack outputs in LambdaInvokeAction for CDK Pipelines

### ISSUE THREAD

**Issue by PeterBaker0** [aws/aws-cdk#15708]
When creating a CdkPipeline and adding stages, the ShellScriptAction stage has the helpful optional field `use_outputs` which allows a mapping of key words to `StackOutput` which are automatically resolved at the time of the `ShellScriptAction` running and are available as environment variables as we expect in the rest of the CDK Lambda workflow. 

Upon trying to add a `LambdaInvokeAction` to the pipeline from the `aws_codepipeline_actions` package, I see that there is the option for `user_parameters`, `inputs` and `outputs` (artifacts) but no direct equivalent. It seems that user_parameters are statically defined at the time of synthesis for the pipeline stack and when read inside the Lambda function are not resolved to their values.

It seems that there is some guidance [here](https://docs.aws.amazon.com/codepipeline/latest/userguide/actions-invoke-lambda-function.html) about how to manually pull the zip files from the relevant artefact s3 bucket, however this really breaks the workflow that CDK usually provides. 

Is there an equivalent, or something closer, to the kindness of just being able to throw in StackOutputs from the `pipeline.stack_output` function directly into environment variables for a LambdaInvokeAction? 

If not, I think this could be a valuable feature.

_Originally posted by @PeterBaker0 in https://github.com/aws/aws-cdk/discussions/15707_

**Comment by PeterBaker0** [comment]
I have since 'resolved' the artifacts manually by following the guidance of the above link, though I believe this would be a helpful feature request to keep that clean workflow in the rest of the CDK pipelines experience.

**Comment by rix0rrr** [comment]
I do not disagree this would be helpful, but invoking Lambdas is outside the design scope of CDK Pipelines. Glad you got it to work. You might consider publishing your solution to the internet and have it show up on https://constructs.dev/ for other people to use.
