### ISSUE TITLE
(aws-events-targets): Add scheduling a Redshift query to "Event Targets for Amazon EventBridge"

### ISSUE THREAD

**Issue by dirkgomez** [aws/aws-cdk#15712]
The event targets module has implemented a couple of event targets but is missing some, one of which is scheduling a Redshift query. 

### Use Case

Schedule RedShift queries.

### Proposed Solution

Cloudformation already allows for this, here's my current implementation which isn't yet very CDKish:

```
    const redshiftClusterArn = ...

    const redshiftRole = new iam.Role(this, 'RedshiftEventRole', {
      assumedBy: new iam.CompositePrincipal(new iam.ServicePrincipal('events.amazonaws.com'), new iam.AccountRootPrincipal()),
      managedPolicies: [iam.ManagedPolicy.fromAwsManagedPolicyName('AmazonRedshiftDataFullAccess')],
    });

    redshiftRole.addToPolicy(
      new iam.PolicyStatement({
        resources: [redshiftClusterArn],
        actions: [
          'sts:AssumeRole',
        ],
      }),
    );

    const redshiftSecret = ...
    redshiftSecret.grantRead(redshiftRole);

    const loader = new events.Rule(this, 'eventRule', {
      schedule: events.Schedule.expression('cron(2 */1 * * ? *)'),
    });

    const cfnLoader = loader.node.defaultChild as events.CfnRule;
    cfnLoader.targets = [{
      arn: `${redshiftClusterArn}`,
      roleArn: redshiftRole.roleArn,
      id: 'loader',
      redshiftDataParameters: {
        database: 'databasename',
        sql: 'call myprocedure()',
        secretManagerArn: redshiftSecret.secretArn,
      },
    }];


```

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by njlynch** [comment]
Thanks for the feature request and sample code, @dirkgomez .

We welcome community contributions! If you are able, we encourage you to [contribute](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md). If you decide to contribute, please start an engineering discussion in this issue to ensure there is a commonly understood design before submitting code. This will minimize the number of review cycles and get your code merged faster.

**Comment by dirkgomez** [comment]
@njlynch I will try to figure out how a simple event target works, the CodeBuildProject looks like a  good start.

**Comment by dirkgomez** [comment]
@njlynch I hit the first roadblock (which may have been the reason to not implement this in the first place).

I added aws-redshift to the dependencies and the peerDependencies in package.json and I get this error:

In package package.json
- [no-experimental-dependencies] It is not allowed to depend on experimental modules. @aws-cdk/aws-events-targets added a dependency on experimental module @aws-cdk/aws-redshift
Error: Some package.json files had errors

Can you please advise me if it makes sense to continue and if so, how? Thanks!

**Comment by rix0rrr** [comment]
For now, it probably makes the most sense to replace `clusterName` and `queryNqme` (or whatever the parameters are) as `string`, instead of as typed objects. They should be replaced with typed references to `ICluster` and `IQuery` when the redshift module is stabilized (let's add a comment saying so, and potentially a GitHub ticket, so we don't forget)

**Comment by Rizxcviii** [comment]
Just created a PR for this

**Comment by manmartgarc** [comment]
Why is this closed? There's an open PR 🤔

**Comment by moelasmar** [comment]
closed as duplicate of issue https://github.com/aws/aws-cdk/issues/31017
