### ISSUE TITLE
CDK / NodeJsFunction: Provide access to bundle role to grant permissions for SSM store

### ISSUE THREAD

**Issue by goosefraba** [aws/aws-cdk#15713]
### The Question
I use CDK and a NodejsFunction from @aws-cdk/aws-lambda-nodejs. As my lambda function requires an external module to be loaded from npmjs (from a private repository) I need to configure the .npmrc file.
In a raw CodeBuild project I do this quite easily by loading the secret key for npmjs.org from the SSM paramter store.

[1] Is there a native way to modify the .npmrc file?
[2] How can I access the role of the actual bundler for my function to grant access to SSM parameter store so that I can execute the hook commands to load the secret key into my .npmrc manually?

The regular command I use to do this in a buildspec.yml:

`- echo "//registry.npmjs.org/:_authToken=$(aws ssm get-parameter --name PARAMETER_VALUE_GOES_HERE | jq '.[].Value' --raw-output)" > ./src/lambda/common/.npmrc`

**Comment by jogold** [comment]
Where does the `cdk synth` run? 

Usually you install all your dependencies then run `cdk synth` and your private dependency should be available for bundling?

**Comment by nija-at** [comment]
Closing this issue since there has been no response in a while.
