### ISSUE TITLE
(pipelines): missing capabilities to deploy stack with secret rotation application

### ISSUE THREAD

**Issue by asterikx** [aws/aws-cdk#15711]
The modern `pipelines.CodePipeline` fails to create/update stacks that contain a secret rotation application, e.g. [SecretsManagerRDSMySQLRotationSingleUser](https://serverlessrepo.aws.amazon.com/applications/us-east-1/297356227824/SecretsManagerRDSMySQLRotationSingleUser) created by `myCluster.addRotationSingleUser()`, due to missing capabilities:

```
Requires capabilities : [CAPABILITY_AUTO_EXPAND]
```

This could be a regression from the he original `pipelines.CdkPipeline` which successfully deploys the same stack.

### Reproduction Steps

```ts
class MyDatabaseStack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    // ...
    const myCluster = new rds.DatabaseCluster(this, 'Database', {
      // ...
    });
    myCluster.addRotationSingleUser(); // <-- This line created the rotation application
  }
}

class MyPipelineStack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    // ...
    const pipeline = new CodePipeline(this, 'Pipeline', {
      // ...
    });
    pipeline.addStage(new MyApplication(this, 'Prod', {
      // ...
    }));
  }
}

class MyApplication extends Stage {
  constructor(scope: Construct, id: string, props?: StageProps) {
    // ...
    const dbStack = new MyDatabaseStack(this, 'Database');
  }
}

new MyPipelineStack(app, 'PipelineStack');
```

### What did you expect to happen?

The modern `pipelines.CodePipeline` successfully deploys stacks with secret rotation applications (as the original `pipelines.CdkPipeline` does).

### What actually happened?

The modern `pipelines.CodePipeline` fails to deploy stacks with secret rotation applications.

### Environment

  - **CDK CLI Version  :** 1.115.0 (build f0ca40f)
  - **Framework Version:** 1.115.0

--- 

This is :bug: Bug Report

**Comment by ksco92** [comment]
Having the same issue: 

https://stackoverflow.com/questions/68523505/add-iam-capabilities-to-stack-in-cdk

By adding this to the resources in my stack I start getting this issue:

```
    rdsInstance.addRotationSingleUser({
        automaticallyAfter: Duration.days(1),
        excludeCharacters: '/@" '
    });
```

Also happening in 1.115, which I installed today.
