### ISSUE TITLE
Toolkit: improve error reporting when Toolkit bucket has been deleted

### ISSUE THREAD

**Issue by jesterhazy** [aws/aws-cdk#1573]
I am trying to create a simple CodePipeline stack, but `cdk deploy` fails with a `<stackname> failed: NoSuchBucket: The specified bucket does not exist` error.

The only S3 bucket in the stack is the CodePipeline artifactBucket that was automatically added by the CodePipeline construct.

`cdk synth` succeeds and shows plausible-looking template. `cdk diff` succeeds and shows all the expected changes, including creation of the S3 bucket. 

minimal example:

`app.ts`:

```
#!/usr/bin/env node
import cdk = require('@aws-cdk/cdk');
import { GithubPipelineStack } from '../lib/cb0'

const app = new cdk.App();
new GithubPipelineStack(app, 'GH0Stack')
app.run();
```

`lib/cb0.ts`:

```
import cdk = require('@aws-cdk/cdk');
import codebuild = require('@aws-cdk/aws-codebuild');
import codepipeline = require('@aws-cdk/aws-codepipeline');
import s3 = require('@aws-cdk/aws-s3');

export class GithubPipelineStack extends cdk.Stack {
    constructor(scope: cdk.App, id: string, props?: cdk.StackProps) {
        super(scope, id, props);

        const project = new codebuild.PipelineProject(this, 'MyProject');
        const pipeline = new codepipeline.Pipeline(this, 'MyPipeline');
        const sourceStage = pipeline.addStage('Source');

        new codepipeline.GitHubSourceAction(this, 'GitHubSourceAction', {
            stage: sourceStage,
            owner: '<owner>',
            repo: '<repo name>',
            oauthToken: new cdk.SecretParameter(this, 'GithubToken', { ssmParameter: '<parameter name>'}).value
        })

        const buildStage = pipeline.addStage('Build');
        new codebuild.PipelineBuildAction(this, 'CodeBuild', {
          stage: buildStage,
          project,
        });
    }
}
```

additional info:
```
cdk doctor
ℹ️ CDK Version: 0.22.0 (build 644ebf5)
ℹ️ No AWS environment variables
ℹ️ No CDK environment variables
```

**Comment by jesterhazy** [comment]
It turns out that i had a CDKToolkit stack deployed, but the underlying bucket for the CDKToolkit had been deleted. Removing the broken stack fixed the NoSuchBucket error.

CDK should have better error logging for this situation - NoSuchBucket error should at least include the bucket name or logical id.

Also, CDK probably shouldn't fail due to problems with the toolkit when it's deploying a stack that doesn't actually depend on the toolkit.

**Comment by bahrmichael** [comment]
I encountered this issue as well today. CDK version 1.26. The CDK Bootstrap stack had a different one, than the deployment wanted (according to the verbose logs). I removed the bootstrap stack, rerun the cdk bootstrap and then successfully deployed my stack.

My main concern here is the error message, which can be misleading if you don't understand that the first value refers to the stack, not the bucket.

```
MyDevStackSomeRandomLongIdentifier823756468234978 failed: NoSuchBucket
```

I wasn't able to pinpoint where this error is thrown. If you could help me find it, I'll can create a PR to clarify the error message.
