### ISSUE TITLE
(ITopic/Queue): sqs.addToResourcePolicy not added when topic.addSubscription is executed ealier. 

### ISSUE THREAD

**Issue by argenstijn** [aws/aws-cdk#15735]
When you have the following code:

```
 Queue.addToResourcePolicy(XXX)
  ITopic.addSubscription(sqsSubscription);   
```

The policy statement is added to the SQS but when you do the following:
 
```
 ITopic.addSubscription(sqsSubscription);   
 Queue.addToResourcePolicy(XXX)
```

the policy statement is not added!
    

### Reproduction Steps

See code above.

### What did you expect to happen?

IN both cases the result is the same!.

### Environment

  - **CDK CLI Version  : 1.114.0 
  - **Node.js Version: v16.4.0
  - **OS               :Windows
  - **Language (Version): Java 11 -->

### Other

--- 

This is :bug: Bug Report

**Comment by NGL321** [comment]
Hey @argenstijn,

Thanks for reporting this, unfortunately the provided snippets are a little too vague to properly attempt to reproduce. Could you provide a minimum reproduction sample?


😸 😷

**Comment by argenstijn** [comment]
The situation is an existing sns topic and then you create an sqs and add it as subscriber to the topic. If you execute the sqs.addToResourcePolicy before rather than after the subscription the result is different.

I will try to add an example late next week. I am on short break.

Outlook voor Android<https://aka.ms/AAb9ysg> downloaden

________________________________
Van: Noah Litov ***@***.***>
Verstuurd: zaterdag 24 juli 2021 04:16
Aan: aws/aws-cdk
Cc: argenstijn; Mention
Onderwerp: Re: [aws/aws-cdk] (ITopic/Queue): sqs.addToResourcePolicy not added when topic.addSubscription is executed ealier. (#15735)


Hey @argenstijn<https://github.com/argenstijn>,

Thanks for reporting this, unfortunately the provided snippets are a little too vague to properly attempt to reproduce. Could you provide a minimum reproduction sample?

😸 😷

**Comment by argenstijn** [comment]
```
 ITopic topic = Topic.fromTopicArn(this, "TOPIC_CONSTRUCT_ID", "[FILL-IN]");
  Queue sourceQueue= Queue.Builder.create(this, "QUEUE_CONSTRUCT_ID")
        .queueName("nlalna") .build();       
    
 SqsSubscription sqsSubscription = SqsSubscription.Builder
        .create(sourceQueue)      
        .rawMessageDelivery(true).build();   

sourceQueue.addToResourcePolicy(
        PolicyStatement.Builder.create()
        .effect(Effect.ALLOW)
        .principals(List.of( ServicePrincipal.Builder.create("lambda.amazonaws.com").build()))
        .actions(List.of("sqs:SendMessage","sqs:GetQueueAttributes","sqs:GetQueueUrl"))
        .resources(List.of(sourceQueue.getQueueArn()))
        .conditions(Map.of("ArnEquals", Map.of("aws:SourceArn","[FILL IN]")))
        .build()
        
        ); 

   //perform later than addToResourcePolicy else the addToResourcePolicy does not work!
    topic.addSubscription(sqsSubscription);   
```

vs
```
 ITopic topic = Topic.fromTopicArn(this, "TOPIC_CONSTRUCT_ID", "[FILL-IN]");
  Queue sourceQueue= Queue.Builder.create(this, "QUEUE_CONSTRUCT_ID")
        .queueName("nlalna") .build();       
    
 SqsSubscription sqsSubscription = SqsSubscription.Builder
        .create(sourceQueue)      
        .rawMessageDelivery(true).build();   

   //perform later than addToResourcePolicy else the addToResourcePolicy does not work!
    topic.addSubscription(sqsSubscription);   
sourceQueue.addToResourcePolicy(
        PolicyStatement.Builder.create()
        .effect(Effect.ALLOW)
        .principals(List.of( ServicePrincipal.Builder.create("lambda.amazonaws.com").build()))
        .actions(List.of("sqs:SendMessage","sqs:GetQueueAttributes","sqs:GetQueueUrl"))
        .resources(List.of(sourceQueue.getQueueArn()))
        .conditions(Map.of("ArnEquals", Map.of("aws:SourceArn","[FILL IN]")))
        .build()
        
        ); 


```

**Comment by njlynch** [comment]
Thanks for the reproduction, @argenstijn !

Unfortunately, even with that, I'm not seeing the behavior you're describing. I synth'ed both of the above examples and compared them. They were exactly identical, except for the order of the actions in the QueuePolicy PolicyDocument.

If you try your own reproduction with a clean CDK app, do you see differences? Perhaps this repro isn't complete.
