### ISSUE TITLE
(aws-eks): Make sure kubectl is compatible with the k8s version

### ISSUE THREAD

**Issue by otaviomacedo** [aws/aws-cdk#15736]
Currently, to update Kubernetes resources, we use `kubectl` version 1.20, [hardcoded in a lambda layer][1]. For now, this works fine, but eventually, as new Kubernetes versions are released, they won't be compatible with the client anymore. Also, it's not an option to always use the latest version of the client, as we [know][2] that `kubectl` version 1.21.0 is not compatible with version 1.20 (and lower) of the server.

[1]: https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/lambda-layer-kubectl/layer/Dockerfile#L8
[2]: https://github.com/aws/aws-cdk/issues/15072

**Comment by robertd** [comment]
cc-ing @pahud to see if he has any thoughts on this. Thanks!

**Comment by scottbisker** [comment]
Is there a status update on this? Any reason why there can't be a different layer version per EKS version?  AWS only supports a given EKS version for 16 months.    1.20 is end of support in approximately 3 months.  Due to the rolling nature of EKS, CDK needs to support matching versions for kubectl.

**Comment by pahud** [comment]
I think we probably have to dynamically create the `kubectl-lambda-layer` with exactly the same k8s version of the cluster. In this case:

1. we need expose the k8s version of the cluster
2. we need allow the [lambda-layer-kubectl](https://github.com/aws/aws-cdk/tree/main/packages/%40aws-cdk/lambda-layer-kubectl) construct accept the version as the optional property and dynamically build the layer accordingly.

any thoughts?

**Comment by jwsomis** [comment]
Really seems crazy there's nothing on the roadmap for this yet.

**Comment by Saberos** [comment]
If/when this is picked up is there any chance this will also be implemented in CDK v1?

**Comment by shcherbak** [comment]
release date of eks 1.22 is April 4, 2022, 1.23 is planned for August, but we still can not upgrade using cdk
eks 1.22 is long awaited release for which people were impatiently waiting for

**Comment by memark** [comment]
With Kubernetes 1.24 recently released, 1.21 is no longer a supported Kubernetes release!

<img width="444" alt="image" src="https://user-images.githubusercontent.com/318504/179355870-0e934d99-8f9a-4437-b122-b4a4cc4aa55c.png">

https://kubernetes.io/releases/patch-releases/#non-active-branch-history

This has now turned into a serious problem for anyone wanting to provision production grade clusters via CDK.

**Comment by otterley** [comment]
@memark Amazon EKS 1.21 is supported through February 2023 per the [official documentation](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar).

**Comment by memark** [comment]
@otterley Thanks, that's good information! I was not aware that AWS backported security patches. Then we're safe until February.

**Comment by shcherbak** [comment]
AWS ERS 1.23 is available, but we can not upgrade even 1.21 using CDK :(

**Comment by Obirah** [comment]
> AWS EKS 1.23 is available, but we can not upgrade even 1.21 using CDK :(

I was so sick and tired of this problem, that I adapted [this workaround](https://github.com/aws/aws-cdk/issues/19843#issuecomment-1094244986) for our environment and have been running and maintaining several 1.22 Clusters with this approach. So far, I can recommend it, it's not a lot of overhead imho.

**Comment by tutunak** [comment]
Have solved this problem in the best way. Imported EKS to Terraform.

**Comment by pahud** [comment]
Now that [kubectlLayer](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_eks.Cluster.html#kubectllayer) is supported, I believe this issue should be closed.
