### ISSUE TITLE
(module name): short issue description

### ISSUE THREAD

**Issue by biffgaut** [aws/aws-cdk#15740]
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-elasticloadbalancingv2.IApplicationLoadBalancer.html
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-elasticloadbalancingv2.ApplicationLoadBalancer.html

These pages show a property called listeners on both ApplicationLoadBalancer and IApplicationLoadBalancer. Looking at application-load-balancer.ts, this property does not exist on either the interface nor the constructs (the term does not appear anywhere in the file). This is one of several properties in the doc not found on IApplicationLoadBalancer. Attempts to reference the property in typescript generate an error.

Am I missing something?

---

This is a 📕 documentation issue

**Comment by jumic** [comment]
Can you please paste a link to the `application-load-balancer.ts` where the property is missing? In IApplicationLoadBalancer, property `listeners` exists:
https://github.com/aws/aws-cdk/blob/774b9ed209558dbb94475ad66d854a907205028a/packages/%40aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-load-balancer.ts#L498

**Comment by biffgaut** [comment]
What I was missing was the latest code. I was compiling against v1.107 and listeners was added in 1.112. Thanks.
