### ISSUE TITLE
cli: report undeleted resources after cdk destroy

### ISSUE THREAD

**Issue by kastork** [aws/aws-cdk#15749]
It would be useful to receive a report of resources that were NOT deleted after running `cdk destroy ...`

### Use Case

During development, it isn't unusual to need to tear down the whole thing and re-deploy. When in this mode, you probably don't care about production level issues (like data preservation).

When you name things yourself...

For example, Dynamodb tables are not deleted (for good reason!), but if you `cdk deploy` after running `cdk destroy` the deploy fails because the table already exists. So the report would be useful to remind one of the things that need to be done manually before (re)deploying a cdk app.

When you don't name things ...

Another example is Cognito user pools where you don't specify a name. In this case the re-deploy doesn't fail, but you accumulate a new user pool every time,  the obsolete ones stick around...

### Proposed Solution

A report that is similar to the listing of stack outputs when you do `cdk deploy`, except the list is the leftover resources that were not deleted.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
Why not set the `removalPolicy` to `DESTROY` when you are in development mode?

**Comment by kastork** [comment]
The DESTROY option might be useful. But I agree there's a can of worms there.

I just want a reminder about the things that didn't go away when I destroyed the CDK app or stack so that I don't find out about them for the first time when a new deploy fails.

**Comment by boillodmanuel** [comment]
I recently had the same concern.

I found 2 workarounds.

## 1. After `cdk destroy`, get the report from cloudformation 

After `cdk detroy`, list all undeleted resources with this command:
```bash
# List all stacks by name(including deleted ones)
aws cloudformation list-stacks --query "StackSummaries[?StackName == 'HelloCdkStack'].[StackId, StackName, StackStatus]"

# List all NOT_DELETED resources of a stack
aws cloudformation list-stack-resources --stack-name "<STACK_ID>" --query  "StackResourceSummaries[?ResourceStatus!='DELETE_COMPLETE'].[ResourceType, PhysicalResourceId, ResourceStatus]"
```

## 2. Add an aspect to list resources that will not be deleted.

Aspect code (file: `removal-policy-report.ts`) :
```ts
import { Stack, Aspects, IAspect, CfnResource, CfnDeletionPolicy, CfnOutput } from "aws-cdk-lib";
import { Construct, IConstruct } from "constructs";

interface RemovalPolicyReportProps {
    /** @default RemovalPolicyReportFilter.NOT_DELETED */
    reportFilter?: RemovalPolicyReportFilter;
}

export class RemovalPolicyReport extends Construct {
    constructor(scope: Stack, id: string, props: RemovalPolicyReportProps = {}) {
        super(scope, id);

        const removalPolicyReportAspect = new RemovalPolicyReportAspect(
            props.reportFilter
        );

        // add the aspect
        Aspects.of(scope).add(removalPolicyReportAspect);

        // add the output
        new CfnOutput(this, "Resources", {
            value: scope.toJsonString(removalPolicyReportAspect.resources),
        });
    }
}

interface RemovalPolicyReportItem {
    name: string;
    logicalId: string;
    deletionPolicy?: CfnDeletionPolicy;
}

export enum RemovalPolicyReportFilter {
    ALL,
    NOT_DELETED,
}

class RemovalPolicyReportAspect implements IAspect {
    public readonly resources: RemovalPolicyReportItem[] = [];
    private found = false;
    private readonly reportFilter: RemovalPolicyReportFilter;

    constructor(
        reportFilter: RemovalPolicyReportFilter = RemovalPolicyReportFilter.NOT_DELETED
    ) {
        this.reportFilter = reportFilter;
    }

    visit(node: IConstruct): void {
        if (node instanceof CfnResource) {
            if (
                this.reportFilter === RemovalPolicyReportFilter.ALL ||
                (node.cfnOptions.deletionPolicy &&
                    node.cfnOptions.deletionPolicy !== CfnDeletionPolicy.DELETE)
            ) {
                this.resources.push({
                    name: node.toString(),
                    logicalId: node.logicalId,
                    deletionPolicy: node.cfnOptions.deletionPolicy,
                });
                this.found = true;
            }
        }
    }

    isFound(): boolean {
        return this.found;
    }
}
```

Add the aspect to your stack (file: `hello-stack.ts`):
```main.ts
import { Stack, StackProps} from "aws-cdk-lib";
import { Construct } from "constructs";
import { RemovalPolicyReport } from "./removal-policy-report";

export class HelloCdkStack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);
    new RemovalPolicyReport(this, "RemovalPolicyReport");
  }
}
```

**Comment by boillodmanuel** [comment]
Opened a new issue for the same purpose: 21806
