### ISSUE TITLE
(aws-eks): Add version 1_21

### ISSUE THREAD

**Issue by cesarpball** [aws/aws-cdk#15758]
At this moment, EKS cluster can be created trought the AWS Console with the latest version available: 1.21

### Use Case

```
 final Cluster eksCluster = Cluster.Builder.create(this,"cluster")
            .vpc(vpc)
            .clusterName(id)
            .version(KubernetesVersion.V1_21)
            .defaultCapacity(0)
            ....
            .build();

```

### Proposed Solution

add Version 1.21

### Other

Issue that I am having right now:

```
cannot find symbol
  symbol:   variable V1_21
  location: class software.amazon.awscdk.services.eks.KubernetesVersion
```
* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by jumic** [comment]
@cesarpball I created a PR for the new version. In the meanwhile, you can use workaround `KubernetesVersion.of("1.21")` instead of `KubernetesVersion.V1_21` to use version 1.21.

**Comment by ryparker** [comment]
Hey @cesarpball :wave:

Thanks for opening this request.

I've marked this as p2 which means that we are unable to work on this immediately. We use +1s to help us prioritize our work, and as always we are happy to take contributions if anyone is interested to pick this up and submit a PR (please make sure to follow our [contribution guidelines](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md).)
🙏
