### ISSUE TITLE
(pipelines): additionalInputs fails for certain repository names

### ISSUE THREAD

**Issue by bodokaiser** [aws/aws-cdk#15753]
It appears to me that the `repository` parameter used with `CodePipelineSource.connection` fails when used in `additionalInputs` of the `CodePipeline` props.

In our production setup, we get the following failure in the CodePipeline:
<img width="609" alt="Screen Shot 2021-07-25 at 13 57 46" src="https://user-images.githubusercontent.com/1780466/126898146-560b6c9f-48c6-483b-90b6-6ee2faf5f78c.png">

I tried [reducing the problem to a minimal example](https://github.com/bodokaiser/cdk-pipeline-invalid-inputs) and get a different error:

```
11 | [Container] 2021/07/25 11:54:01  INSTALL: 1 commands
12 | [Container] 2021/07/25 11:54:01  BUILD: 3 commands
13 | [Container] 2021/07/25 11:54:01 Phase complete: DOWNLOAD_SOURCE State: SUCCEEDED
14 | [Container] 2021/07/25 11:54:01 Phase context status code:  Message:
15 | [Container] 2021/07/25 11:54:01 Entering phase INSTALL
16 | [Container] 2021/07/25 11:54:01 Running command ln -s "$CODEBUILD_SRC_DIR_bodokaiser_cdk-pipeline-invalid-inputs_Source" "some_additional_input"
17 | ln: invalid option -- 'p'
18 | Try 'ln --help' for more information.
```

### Reproduction Steps

Reproduction steps are summarized in the `README.md` of [cdk-pipeline-invalid-inputs](https://github.com/bodokaiser/cdk-pipeline-invalid-inputs)

### What did you expect to happen?

A successful build.

### What actually happened?

In our production environment `CodePipeline` raises an error that the input source name is invalid (containing dashes?) while in the minimal example the synth command fail.

### Environment

  - **CDK CLI Version  :** 1.115.0
  - **Framework Version:** 1.115.0
  - **Node.js Version:** 16.5.0
  - **OS               :** macOS Big Sur
  - **Language (Version):** Typescript (4.3.5)

--- 

This is :bug: Bug Report

**Comment by ryparker** [comment]
Hey @bodokaiser 👋🏻 

I wasn't able to reproduce this with the given code (replaced connection arn and repos).

Is that error throwing on the Source stage? Looking at the error I can see it starts with `Error calling startBuild` this seems like an error thrown by CodeBuild and not CodePipeline.

**Comment by bodokaiser** [comment]
@ryparker 

The error is thrown in the `Synth` `CodeBuild` step right after the Source stage.

Do you repos contain dashes? My hypothesis is that it has something to do with dashes in the repository name which is either not formated correctly or too carefully validated.

In our production setup, the `Synth` `CodeBuild` step has the error:

<img width="609" alt="Screen Shot 2021-07-30 at 06 41 04" src="https://user-images.githubusercontent.com/1780466/127601215-c4ccfd56-97d3-432f-b854-c888825a810e.png">

editing the `Synth` `CodeBuild` step through the web interface reveals the following naming of the input artifacts:

<img width="1422" alt="Screen Shot 2021-07-30 at 06 42 02" src="https://user-images.githubusercontent.com/1780466/127601297-85834044-7942-45b9-8658-b45d06804dc7.png">

I am not exactly sure how this relates to the error I encounter in the minimal repository [cdk-pipeline-invalid-inputs][1]. With that error:

<img width="1120" alt="Screen Shot 2021-07-30 at 06 45 08" src="https://user-images.githubusercontent.com/1780466/127601575-83ec02ce-86f8-4985-801d-4f5f1e1f0474.png">

it appears to me to be indeed related to the presence of dashes in the repository name as the `-pipeline-invalid-inputs` segment of `cdk-pipeline-invalid-inputs` is somewhat interpreted as command line argument `-p"invalid-inputs` or the like.

[1]: https://github.com/bodokaiser/cdk-pipeline-invalid-inputs

**Comment by bodokaiser** [comment]
@ryparker @rix0rrr is there anything else I can do for you to support you on this?
