### ISSUE TITLE
Body property cannot be added to cfnApi

### ISSUE THREAD

**Issue by yogarasu** [aws/aws-cdk#15754]
### The Question

I’m in the process of creating an OpenAPI that can authenticate and approve Cognito.
I added a Body to the API properties,

```
<stack/apiStack.ts:56>
const cfnApi = httpApi.node.defaultChild as CfnApi;
cfnApi.addPropertyOverride('Body', props.openApi);
```

but I get an error stating that there is no Body.
```
edundant fields [name="dev-○○○○○-HttpApi", protocolType="HTTP", corsConfiguration={"allowOrigins":["http://localhost:3000"],"exposeHeaders":[],"allowMethods
":["*"],"allowHeaders":["authorization"]}] provided when either Body or BodyS3Location is not empty (Service: null; Status Code: 0; Error Code: null; Request ID:
null; Proxy: null) (Service: null; Status Code: 404; Error Code: BadRequestException; Request ID: null; Proxy: null)
Does anyone know the cause?
```

The working branch where the phenomenon is occurring is the link below.
https://github.com/yogarasu/todolist/tree/feature/add-api

### Environment

  - **CDK CLI Version:** 1.115.0
  - **Node.js Version:** 14.17.3
  - **OS:**  macOS BigSur 11.2.3
  - **Language (Version):** TypeScript (4.3.5)

**Comment by peterwoodworth** [comment]
How are you creating your HttpApi and what other configuration do you have for it?

**Comment by yogarasu** [comment]
Sorry, I misunderstood that HttpApi supports the body property.
https://github.com/aws/aws-cdk/issues/11373
