### ISSUE TITLE
(aws-ecs-patterns): Add enableExecuteCommand configuration property ApplicationLoadBalancedFargateService

### ISSUE THREAD

**Issue by rcollette** [aws/aws-cdk#15769]
Surface the `enableExecuteCommand` property of a Fargate service as part of the ApplicationLoadBalancedFargateService construct.

### Use Case

To enable debugging of services.

### Other
Related to : #15768 

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by ryparker** [comment]
Hey @rcollette :wave:

Thanks for opening this request.

I'm going to mark this as p2 which means that we are unable to work on this immediately. We use +1s to help us prioritize our work, and as always we are happy to take contributions if anyone is interested to pick this up and submit a PR (please make sure to follow our [contribution guidelines](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md).)
🙏

Here's a workaround that can be used in the mean time:

```ts
const albFargateService = new ApplicationLoadBalancedFargateService(this, 'AlbFargateService', {
	...props
});

const cfnFargateService = albFargateService.service.node;
cfnFargateService.addPropertyOverride('EnableExecuteCommand', true);
```

_see docs on [escape hatches](https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html#Modifying-the-AWS-CloudFormation-resource-behind-AWS-constructs)_ for more info on this workaround.
