### ISSUE TITLE
Eks, KubernetesManifest needs namespace overriding

### ISSUE THREAD

**Issue by gyang-vonage** [aws/aws-cdk#15772]
Helm and Cdk8s do not generate namespace into manifests, it would be nice to be able to add/override namespaces in generated manifests.

**Comment by ryparker** [comment]
Hey @gyang-vonage :wave:

Thanks for opening this request. 

Would you mind providing a more specific use case/scenario for this feature?

By the way we highly encourage feature requests to use [this template](https://github.com/aws/aws-cdk/blob/master/.github/ISSUE_TEMPLATE/feature-request.md) to provide more context and help us prioritize accurately.

For now i'm going to prioritize this as p2 which means that we are unable to work on this immediately. We use +1s to help us prioritize our work, and as always we are happy to take contributions if anyone is interested to pick this up and submit a PR (please make sure to follow our [contribution guidelines](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md).)
🙏
