### ISSUE TITLE
CDK Synth generates different S3 bucket reference for lambda stack

### ISSUE THREAD

**Issue by rsamarakoonfraedom** [aws/aws-cdk#15778]
### The Question
Hi Team, For a stack with lambda,  does CDK synth generate a different reference for the S3 bucket that holds the lambda assets ? This behaviour seems to cause our snapshot test to fail on Github Actions workflow.

### Environment

  - **CDK CLI Version:** 1.111.0
  - **Module Version:** 
  - **Node.js Version:** 
  - **OS:** 
  - **Language (Version):** 

### Other information

![image (1)](https://user-images.githubusercontent.com/40221534/127098438-c182f279-a5d3-4d99-a090-8d24ccb308ec.png)

**Comment by peterwoodworth** [comment]
Hey @rsamarakoonfraedom

What exactly do you mean by "different reference"? What is the difference based on?

**Comment by rsamarakoonfraedom** [comment]
Hi @peterwoodworth,
Please look at the screenshot attached. I have marked it it yellow.
![CDK_Snapshot_Test](https://user-images.githubusercontent.com/40221534/127236119-92967c03-c2fe-42c6-8dcd-a6d113b067fe.JPG)

**Comment by peterwoodworth** [comment]
[This thread](https://github.com/aws/aws-cdk/issues/14555) helps explain some of how the hashes are calculated. Currently, hashes are OS-dependent. That could be the source of this issue

**Comment by peterwoodworth** [comment]
I'm pretty certain that what I linked is the source of the different hashes. Please make sure to comment in that thread or give it a thumbs up if you'd like to see hashes be normalized

**Comment by rsamarakoonfraedom** [comment]
Thank you @peterwoodworth, I will have a look at the thread.

**Comment by peterwoodworth** [comment]
No problem, feel free to ping me if that thread doesn't help you and I can reopen this issue
