### ISSUE TITLE
(function): Using Lambda .currentVersion results in deployment failures

### ISSUE THREAD

**Issue by andrewb1234** [aws/aws-cdk#15788]
In a single application, we are attempting to create lambdas in some stack A and pass them to some stack B to be used in a state machine definition. In the state machine, we are using ```lambdaFunction.currentVersion```, because we have long running workflows and a lambda deployment in the middle could break ongoing executions. 

The problem that we are facing is that since we are using the current version of our lambdas, the output of stack A is not the lambda, but rather the *version* of the lambda. Functionally, this works fine until we try and deploy to Stack A. Because the lambda version is the output, CFN attempts to delete the lambda version and bring up a new one, but fails because the lambda version is in use by Stack B. 

### Reproduction Steps

A basic code path is as follows: 
app.ts : 
```ts
// <import statements>
const stackA = new StackAStack(<parameters>)
const stackB = new StackBStack(<parameters>, stackA.functionA)
```
StackAStack.ts
```ts
// <import statements>
export class StackAStack extends... {
  readonly functionA: Function;
  <... constructor>
}
```
StackBStack.ts 
```ts
// <import statements>
export interface StackBStackProps {
  ...
  readonly functionA: Function;
}
export class StackBStack extends... {
  constructor(props: StackBStackProps, ...) {
       const invoke = new LambdaInvoke ({
             lambdaFunction: props.functionA.currentVersion,
             .....
       }
       const definition = invoke.next(done);
       const stateMachineA = new StateMachine(<some props>, definition))
  }
}
```

### Environment
  - **Node.js Version:** 12.x
  - **OS               :** MacOs
  - **Language (Version):** TypeScript

--- 

This is :bug: Bug Report

**Comment by andrewb1234** [comment]
Updating the question to add some more context.

In the simple example above, I tested using another feature of the lambda, the functionName, in the description as below : 
```
        const invoke = new LambdaInvoke(this, "invoke", {
            lambdaFunction: props.functionA.currentVersion,
            comment: `${props.functionA.functionName}`
        });
```

Rather than exporting the lambda only, we are now exporting the functionVersion and the function itself.

**Comment by BenChaimberg** [comment]
Here is a somewhat finicky way to accomplish your goals of versioned Lambda function execution in a state machine, where the function and the state machine are in different stacks:

```ts
import { CfnDynamicReference, CfnDynamicReferenceService, CfnResource, Construct, RemovalPolicy, Stack, StackProps } from '@aws-cdk/core';
import * as lambda from '@aws-cdk/aws-lambda';
import * as sfn from '@aws-cdk/aws-stepfunctions';
import * as sfntasks from '@aws-cdk/aws-stepfunctions-tasks';
import * as ssm from '@aws-cdk/aws-ssm';

interface DynamicVersionProps {
  readonly versionArnParamName: string;
}

class DynamicVersion extends Construct {
  public readonly version: lambda.IFunction;

  constructor(scope: Construct, id: string, props: DynamicVersionProps) {
    super(scope, id);

    const dynamicVersionArn = new CfnDynamicReference(CfnDynamicReferenceService.SSM, props.versionArnParamName).toString()
    this.version = lambda.Function.fromFunctionArn(this, 'Default', dynamicVersionArn);
  }
}

export class LambdaStack extends Stack {
  public readonly versionArnParamName: string;

  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);

    const lambdaFunction = new lambda.Function(this, 'Function', {
      code: lambda.Code.fromInline('exports.handler = (event) => { console.log(event) }'),
      handler: 'index.handler',
      runtime: lambda.Runtime.NODEJS_12_X,
    });
    const version = lambdaFunction.currentVersion;
    version.applyRemovalPolicy(RemovalPolicy.RETAIN);

    this.versionArnParamName = new ssm.StringParameter(this, 'Version ARN', {
      stringValue: version.functionArn,
    }).parameterName;
  }
}

export interface SfnStackProps extends StackProps {
  readonly versionArnParamName: string;
}
export class SfnStack extends Stack {
  constructor(scope: Construct, id: string, props: SfnStackProps) {
    super(scope, id, props);

    const dynamicVersion = new DynamicVersion(this, 'Dynamic Version', {
      versionArnParamName: props.versionArnParamName,
    });
    const stateMachine = new sfn.StateMachine(this, 'State Machine', {
      definition: new sfntasks.LambdaInvoke(this, 'Lambda Invoke', {
        lambdaFunction: dynamicVersion.version,
      }),
    });
    (stateMachine.node.defaultChild as CfnResource).addMetadata('alwaysUpdate', Date.now().toString())
  }
}
```

A couple of implementation notes:
- `CfnDynamicReference` is used instead of `ssm.StringParameter.valueForStringParameter` or `ssm.StringParameter.fromStringParameterAttributes` to allow for non-versioned dynamic references (there are some bugs in this module that should be addressed)
- Unfortunately, the exporting LambdaStack cannot create the DynamicVersion and expose it as a class property since the scope of the construct created by `lambda.Function.fromFunctionArn` would still be the LambdaStack and would thus create a CFN export/import. This means we have to deal with untyped strings :(. A possible better way would be to expose a `(scope: Construct) => lambda.IFunction` instead but I figured that was a bit complex for this example
- The call to `applyRemovalPolicy` is to ensure that CFN does not delete old function versions when a new version is created
- The call to `addMetadata` is to ensure that the importing SfnStack is *always* deployed, even when there are no other changes to the template. This means that CFN will re-resolve the dynamic reference to the version ARN and ensure that the state machine is updated to point to the current version whenever the stacks are deployed. Without this call, CFN will not update the stack since the change set contains no changes.

**Comment by andrewb1234** [comment]
On your last bullet point : 
This can cause a potential issue though right? If we have new versions being created for lambdas that are not actually updated (i.e. we are trying to share two lambdas from LamdaStack to SfnStack and one of them is updated), then a rollback would do nothing as it'd be rolling back to a version that is equal to currVersion right?

**Comment by BenChaimberg** [comment]
I think your misunderstanding may be how rollback deployments occur in this model. In a word, they are roll *forwards* not roll backs. If I understand the scenario right, here's what would happen:

- You have two functions (F1 and F2) that are both being used in your state machine. They currently are both at version 1 (F1V1 and F2V1) and the state machine definition has resolved to these versions.
- You modify something about F2 and deploy the stacks. A new version for F2 is deployed (F2V2) and no new version for F1 is deployed. The state machine definition resolves to (F1V1, F2V2).
- You discover a bug in F2 and decide to roll back your CDK/application code changes and deploy the stacks. A new version for F2 is deployed (F2V3) that happens to be identical to F2V1 and no new version for F1 is deployed. The state machine definition resolves to (F1V1, F2V3). 

Let me know if you were thinking of something else!

**Comment by andrewb1234** [comment]
Apologies, accidentally deleted the comment that was just responded to. A gist of what : If I have LambdaA and LambdaB being deployed, is there a risk of a rollback not making any changes if we are always updating per `addMetaData`

**Comment by andrewb1234** [comment]
I was able to get this up and tested on my local stack, not sure if it behaves as expected... I made a change to the Lambda Configuration (just updated timeout) to get a new version published (was previously 3, now 4). However, when I look at the StateMachine definition, it is still pointing to the old version of lambda. Additionally, this deployment to lambda did not update Sfn stack (in my code StackB2). 

Code Below : 

```

import {Construct, Duration, RemovalPolicy} from "monocdk";
import {Code, Function, Runtime} from "monocdk/aws-lambda";
import {StringParameter} from "monocdk/aws-ssm";

export class StackA2 extends Stack {
    public readonly versionArnParamName: string;
    constructor(scope: Construct, id: string, props: StackProps) {
        super(scope, id, props);
        const lambdaFunc = new Function(this, "FunctionA2", {
            runtime: Runtime.PYTHON_3_8,
            code: Code.fromInline("print('Hey12345')"),
            handler: "Test",
            functionName: "FunctionA2Name",
            timeout: Duration.seconds(15),
            description: `Generated on : ${new Date().toISOString()}`
        });
        const version = lambdaFunc.currentVersion;
        version.applyRemovalPolicy(RemovalPolicy.RETAIN);

        this.versionArnParamName = new StringParameter(this, 'Version ARN', {
            stringValue: version.functionArn
        }).parameterName;
    }
}
```

```

import {CfnResource, Construct} from "monocdk";
import {DynamicVersion} from "./DynamicVersion";
import {StateMachine, Succeed} from "monocdk/aws-stepfunctions";
import {LambdaInvoke} from "monocdk/aws-stepfunctions-tasks";

export interface StackB2Props extends StackProps {
    readonly versionArnParamName: string;
}
export class StackB2 extends Stack {
    constructor(scope: Construct, id: string, props: StackB2Props) {
        super(scope, id, props);
        const dynamicVersion = new DynamicVersion(this, "dynVers", {
            versionArnParamName: props.versionArnParamName
        });
        const done = new Succeed(this, "Done");
        const invoke = new LambdaInvoke(this, "invoke", {
            lambdaFunction: dynamicVersion.version
        })
        const stateMachine = new StateMachine(this, "StateMachine2", {
            definition: invoke.next(done),
            stateMachineName: "StateMachineB2"
        });
        (stateMachine.node.defaultChild as CfnResource).addMetadata('alwaysUpdate', Date.now.toString())
    }

}
```

StateMachine def : 
```
    "invoke": {
      "Next": "Done",
      "Retry": [
        {
          "ErrorEquals": [
            "Lambda.ServiceException",
            "Lambda.AWSLambdaException",
            "Lambda.SdkClientException"
          ],
          "IntervalSeconds": 2,
          "MaxAttempts": 6,
          "BackoffRate": 2
        }
      ],
      "Type": "Task",
      "Resource": "arn:aws:states:::lambda:invoke",
      "Parameters": {
        "FunctionName": "arn:aws:lambda:us-east-1:698139127880:function:FunctionA2Name:3",
        "Payload.$": "$"
      }
    },
```

Lambda Current Version : 4

**Comment by ryparker** [comment]
:wave: Relabeled this as guidance since this is not breaking CDK functionality. Let me know if you think otherwise.

**Comment by BenChaimberg** [comment]
Can you confirm that you also deployed StackB2?

**Comment by andrewb1234** [comment]
```
StackB2
StackB2: deploying...

 ✅  StackB2 (no changes)
```

I can confirm.

**Comment by BenChaimberg** [comment]
There should *always* be changes to StackB2 because of the `addMetadata`...I'm not sure exactly what's up, but try checking the synthesized template for StackB2 and compare the metadata entry on the state machine with the deployed stack (via console is probably easiest).

**Comment by andrewb1234** [comment]
Figured it out. 
In line 
```
(stateMachine.node.defaultChild as CfnResource).addMetadata('alwaysUpdate', Date.now.toString())
```
Date.now is missing a ().
Changed it to 
```
(stateMachine.node.defaultChild as CfnResource).addMetadata('alwaysUpdate', Date.now().toString())
```
And it worked. Figures.
