### ISSUE TITLE
CompositePrincipal does not support conditions

### ISSUE THREAD

**Issue by Crapatrick** [aws/aws-cdk#1578]
I am trying to reproduces the following Cloudformation Template with CDK:
```
"AssumeRolePolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Action": [
                "sts:AssumeRole"
              ],
              "Principal": {
                "AWS": [
                  "arn:aws:iam::<account>:role/MasterRole",
                  "arn:aws:iam::<account>:role/AccountOwner"
                ]
              }
            },
            {
              "Effect": "Allow",
              "Action": [
                "sts:AssumeRoleWithSAML"
              ],
              "Principal": {
                "Federated": "arn:aws:iam::<account>:saml-provider/SAMLIDP"
              },
              "Condition": {
                "StringEquals": {
                  "SAML:aud": "https://signin.aws.amazon.com/saml"
                }
              }
            }
          ]
        },
```

Either of those (Federated or Arn) work just fine but I am unable to combine them with CompositePrincipal because there is no support for Conditions: [feat(iam): CompositePrincipal and allow multiple principal types #1377](https://github.com/awslabs/aws-cdk/pull/1377)
The Condition is in a different scope so I don't understand why this would be not possible.

```
new iam.CompositePrincipal(new iam.FederatedPrincipal(
        `arn:aws:iam::${props.account.account}:saml-provider/SAMLIDP`, {
          "StringEquals": [{"SAML:aud": "https://signin.aws.amazon.com/saml"}],
        }, "sts:AssumeRoleWithSAML"
      ),
      new iam.ArnPrincipal(`arn:aws:iam::${props.default.rootAccount}:saml-provider/MasterRole`),
      new iam.ArnPrincipal(`arn:aws:iam::${props.default.rootAccount}:saml-provider/AccountOwner`)
)
```

**Comment by rix0rrr** [comment]
We need to change `CompositePrincipal` to emit multiple statements.

**Comment by reillykw** [comment]
I'm also experiencing this issue.  What I need to be able to do is attach multiple actions to a federated policy document, I was hoping composite would help but it would throw an error with conditions. Also would need to see support for multiple federated ARNs, if that is possible.  I don't know if a Composite would achieve that end or not.

**Comment by Cushdrive** [comment]
I have the same use case, and I'm also blocked from fully leveraging the CDK because it can't be used in the same way as the CloudFormation templates I'm trying to replace.

**Comment by rix0rrr** [comment]
Not so easy to fix, actually. Goes together with #3227 as well.

**Comment by cesarpball** [comment]
Any workaround on this topic? I would to work with Federate access with conditions.

**Comment by rix0rrr** [comment]
Escape hatches would be the standard answer
