### ISSUE TITLE
aws-amplify: Cannot change custom rules and have source code provider

### ISSUE THREAD

**Issue by newmana** [aws/aws-cdk#15789]
After creating an Amplify application for the first time subsequent changes throws an exception:

```
Resource handler returned message: "Invalid request provided: There was an issue setting up your repository. Please try again later.({"message":"Validation Failed","errors":[{"resource":"Hook","code":"cu
stom","message":"Hook already exists on this repository"}],"documentation_url":"https://docs.github.com/rest/reference/repos#create-a-repository-webhook"}) (Service: Amplify, Status Code: 400, Request ID
: f97384f4-6f1b-46ed-afcc-ba62c95023c2, Extended Request ID: null)" (RequestToken: d68d7f97-a28c-998d-be8d-b037943e8d3c, HandlerErrorCode: InvalidRequest)
```

It requires the Github webhook to be manually deleted in order for the change to be made.

### Reproduction Steps

1. Create an amplify app with github source code provider

```ts
const githubProvider = new amplify.GitHubSourceCodeProvider({
  owner: GITHUB_OWNER,
  repository: GITHUB_REPOSITORY,
  oauthToken: oauthToken,
});

const amplifyApp = new amplify.App(this, `something`, {
      sourceCodeProvider: githubProvider,
      customRules: [
        {
          source: "/",
          target: "/login",
        }
      ]
});
```

2. Make a small change to the rules:

```ts
const githubProvider = new amplify.GitHubSourceCodeProvider({
  owner: GITHUB_OWNER,
  repository: GITHUB_REPOSITORY,
  oauthToken: oauthToken,
});

const amplifyApp = new amplify.App(this, `something`, {
      sourceCodeProvider: githubProvider,
      customRules: [
        {
          source: "/",
          target: "/login",
          status: amplify.RedirectStatus.REWRITE,
        },
        {
          source: "/redirect",
          target: "/index.html",
          status: amplify.RedirectStatus.REWRITE,
        }
      ]
});
```

### What did you expect to happen?

Makes the small configuration change to Amplify.

### What actually happened?

Fails until you manually delete the github webhook.

### Environment
  - **CDK CLI Version  :** 1.115.0 (build f0ca40f)
  - **Framework Version:** 1.115.0
  - **Node.js Version:** v14.17.3
  - **OS               :** MacOS 11.5
  - **Language (Version):** Typescript 3.9.7

### Other

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Thanks for opening the issue @newmana. Do you happen to know whether this also happens when using Amplify with pure CloudFormation?

I'm basically trying to figure out if this is a CDK problem, or the CloudFormation Amplify support problem.

Thanks,
Adam

**Comment by newmana** [comment]
Thanks Adam for getting back - not sure how to determine this. Do you have steps at my end I can do?

**Comment by newmana** [comment]
The error in cloudformation:
```
2021-07-28 08:28:57 UTC+1000 | XXXX | UPDATE_FAILED | Resource handler returned message: "Invalid request provided: There was an issue setting up your repository. Please try again later.({"message":"Validation Failed","errors":[{"resource":"Hook","code":"custom","message":"Hook already exists on this repository"}],"documentation_url":"https://docs.github.com/rest/reference/repos#create-a-repository-webhook"}) (Service: Amplify, Status Code: 400, Request ID: f97384f4-6f1b-46ed-afcc-ba62c95023c2, Extended Request ID: null)" (RequestToken: d68d7f97-a28c-998d-be8d-b037943e8d3c, HandlerErrorCode: InvalidRequest)
-- | -- | -- | --



```

**Comment by skinny85** [comment]
1. Generate the template in CDK code version `#1` (with one `customRules`) with `cdk synth` - it will be in `cdk.out`.
2. Deploy that template directly through CloudFormation (console is fine).
3. Change the CDK code to version `#2` (with multiple `customRules`). Run `cdk synth` again. Compare the generated template in the `cdk.out` directory from this step to step 1, to make sure the only change is the `customRules`.
4. Deploy that new template again through CloudFormation, and see if the error happens.

**Comment by NGL321** [comment]
Hey @newmana,

Were you able to confirm the Cloudformation behavior? I was unable to reproduce this, but if you are still experiencing this bug and you confirmed it isnt in Cloudformation, I can do a deeper investigation.

**Comment by newmana** [comment]
Hi, I haven't had a chance to reproduce it further - we have definitely made other changes subsequently so I will close it for now and if it does re-occur - I'll come back and go through the steps suggested.
