### ISSUE TITLE
(pipelines): Auto approve steps when there is no diff

### ISSUE THREAD

**Issue by JFox** [aws/aws-cdk#15784]
Version 1.115.0 added the ability to have manual steps that get auto-approved when the `diff --security-only` command returns that there is no diff and only waits for the human action when there is a diff. It would be great to extend this auto-approval functionality not only to security changes but to diffs in general

### Use Case

Big pipelines with many stacks and dependencies and only one of them is updated require a manual approval on each "level" even when there's a diff only on a single stack 

### Proposed Solution

Extend the auto-approval functionality implemented [here](https://github.com/aws/aws-cdk/pull/15441) to "regular" manual approval steps

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by ryparker** [comment]
Hey @JFox :wave:

Thanks for the feature request.

I'm going to mark this issue as p2 which means that we are unable to work on this immediately. We use +1s to help us prioritize our work, and as always we are happy to take contributions if anyone is interested to pick this up and submit a PR (please make sure to follow our [contribution guidelines](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md).)
🙏

**Comment by rix0rrr** [comment]
I don't think it's likely we're going to add this feature, especially given that we have a different direction in the works.

All the tools exist to implement this feature yourself. When you do, please publish it to the internet so it shows up on https://constructs.dev/ and other people can benefit from it as well.
