### ISSUE TITLE
(aws-events-targets): target ECSTask adds incorrect input

### ISSUE THREAD

**Issue by peterb154** [aws/aws-cdk#15785]
When adding a task to an event rule of type ECSTask with no container options, the CfnRule.Targets[x].Input value is "{}". 

This causes the event information not to be passed to the container because according the the cloudformation documentation (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-rule.html) "If Input is specified in the form of valid JSON, then the matched event is overridden with this constant."

It looks like in the ECSTask, input is assigned to  `const input = { containerOverrides };`
https://github.com/aws/aws-cdk/blob/v1.98.0/packages/%40aws-cdk/aws-events-targets/lib/ecs-task.ts#L161

If containerOverrides is undefined (as is the default) input will be `{}`.

Then here https://github.com/aws/aws-cdk/blob/v1.98.0/packages/%40aws-cdk/aws-events-targets/lib/ecs-task.ts#L189 input is returned in the bind() method, causing the value of input to be {}. 
```ts
    return {
      arn,
      role,
      ecsParameters,
      input: events.RuleTargetInput.fromObject(input),
      targetResource: this.taskDefinition,
    };
```

### Reproduction Steps

```ts
import * as core from '@aws-cdk/core';
import * as ECS from '@aws-cdk/aws-ecs'
import * as EVENT from '@aws-cdk/aws-events'
import {EcsTask} from "@aws-cdk/aws-events-targets";

export class EventStack extends core.Stack {
  constructor(scope: core.Construct, id: string, props?: core.StackProps) {
    super(scope, id, props);

    const cluster = new ECS.Cluster(this, "Cluster")
    const taskDefinition = new ECS.FargateTaskDefinition(this, "TaskDefinition");
    const rule = new EVENT.Rule(this, "Rule", {
      eventPattern: {
        source: ["aws.s3"],
        detail: {
          eventSource: ["s3.amazonaws.com"],
          eventName: ["PutObject"],
          requestParameters: {
            bucketName: ["test-bucket"]
          }
        }
      }
    })
   rule.addTarget(new EcsTask({cluster, taskDefinition}))
  }
}

const app = new core.App()
new EventStack(app, "event-stack");
app.synth();
```

### What did you expect to happen?

That the rule.targets[0].input is ABSENT

```json
    "Rule4C995B7F": {
      "Type": "AWS::Events::Rule",
      "Properties": {
         ...
        "Targets": [
          {
            ....
            "Input": "{}",
          }
       ]
      },
```

### What actually happened?

```json
    "Rule4C995B7F": {
      "Type": "AWS::Events::Rule",
      "Properties": {
         ...
        "Targets": [
          {
            ....
          }
       ]
      },
```

### Environment

  - **CDK CLI Version  : 1.98.0

--- 

This is :bug: Bug Report

**Comment by ryparker** [comment]
Hey @peterb154 :wave:

Thanks for bringing this to our attention. 

I'm going to prioritize this as p1 which means it has been prioritized as important. Please keep in mind that we have a large number of issues at the moment. It may be some time before we are able to solve this particular issue. We use +1s to help us prioritize our work, and as always we are happy to take contributions if anyone is interested to pick this up and submit a PR.

**Comment by peterb154** [comment]
@ryparker understood... We are developing a workaround internally for this. Once I confirm that it is indeed working, I'd be happy to share back.

**Comment by rix0rrr** [comment]
I think you've done most of the legwork yourself already. Probably something along these lines:

```ts
const input = containerOverrides ? { containerOverrides } : undefined;
```

Would do it?
