### ISSUE TITLE
(assets): Uploaded file must be a non-empty zip

### ISSUE THREAD

**Issue by patrick-tresp** [aws/aws-cdk#15798]
We are facing the issue, that we can not deploy any environment ( production, staging, development, test ) with `cdk deploy` anymore.

The error that raised:

```
Resource handler returned message: "Uploaded file must be a non-empty zip (Service: Lambda, Status Code: 400, Request ID: 11cbd3f4-e5a4-4b7d-a10a-15da3
58f4b64, Extended Request ID: null)" (RequestToken: a6d89298-48b5-44ce-215a-14bd022bca02, HandlerErrorCode: InvalidRequest)
```

We can see that cdk.out folder is filled with aseets.[assets-id] folders, but no zip folders are created.

Also interesting is the fact, that if we create a fresh account on aws, bootstrap it and deploy there, everything works as expected for exact one time. Any deployment afterwards ( of course with little changes to force an update ) fails with error above.

This happens on local macOS machine as well as previous working github actions with ubuntu/latest OS.

### Reproduction Steps

run `cdk deploy STACKNAME --profile [aws-profile]`

Note: [aws-profile] is set in ' ~/.aws/credentials` 

### What did you expect to happen?

Assets are beeing created in `cdk.out`  folder and zipped for an upload to S3 Bucket to execute Cloudformation deployment.

### What actually happened?

No zip files are created in `cdk.out` folder.

### Environment

  - **CDK CLI Version  :** aws-cli/2.2.21 Python/3.8.8 Darwin/20.5.0 exe/x86_64 prompt/off
  - **Framework Version:**
  - **Node.js Version:** v14.17.3
  - **OS               :** MacOs 11.4
  - **Language (Version):** TypeScript (3.9.7) 

### Other

--- 

This is :bug: Bug Report

**Comment by mattcui** [comment]
I met the similar problem with my golang based lambda function, but I can see the built main file in the asset folder, like cdk.out/asset.08e3e0605a610fe153bcd368387d926e0e5ef54458413fb7232b708045dcaf63/main. And I also can see main file in s3 stage bucket.

**Comment by patrick-tresp** [comment]
@mattcui did you find any solution on that? 
it seems like it brings our whole infrastructure to a sudden stop.

**Comment by mattcui** [comment]
@patrick-tresp not yet, I have been struggling for 2 days, no any progress so far.

**Comment by mattcui** [comment]
@patrick-tresp Today, I retried the deployment, it's successful this time, looked that something was fixed perhaps from server-side. You could have a try.

**Comment by patrick-tresp** [comment]
Hey @mattcui , thanks for the notice.
Unfortunately it still runs into same issue BUT a fresh provisioned account does run into this error.

Will run several deployments now to verify and move resources to that account. :(

**Comment by patrick-tresp** [comment]
Hey @mattcui ,

try this out: empty your s3 bucket from toolkit `cdktoolkit-stagingbucket-xxxxx`.
After emptying this, we could deploy again without running into this error.

We also added this to your github action file with

`aws s3 rm s3://cdktoolkit-stagingbucket-xxxxx --recursive` 

Hope that helps you as well. 

Cheers,
Patrick

**Comment by mattcui** [comment]
@patrick-tresp Thanks, we haven't had this problem for days, I am not sure what caused the problem, and why it disappeared.

**Comment by patrick-tresp** [comment]
AWS Magic …
