### ISSUE TITLE
(pipelines): custom step in Java

### ISSUE THREAD

**Issue by deyceg** [aws/aws-cdk#15791]
Creating a custom step in the new CDK pipelines API in Java throws a `JSIIException`

### Reproduction Steps

Follow the recommended guidelines for implementing a custom step using the new API: https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/pipelines/README.md#arbitrary-codepipeline-actions

```java
public class LambdaStep extends Step implements ICodePipelineActionFactory {

    Function fn;

    public ExecEc2ImagePipelineLambdaStep(Construct scope, @NotNull String id) {
        super(id);

       String fnCode = "exports.handler = async (event) => {console.log('event: ', event)}";
       this.fn = Function.Builder.create(this, "Fn")
                                                               .runtime(Runtime.NODEJS_14_X)
                                                               .handler("index.handler")
                                                               .code(Code.fromInline(fnCode).build()

    }

    @Override
    public @NotNull CodePipelineActionFactoryResult produceAction(@NotNull IStage iStage, @NotNull ProduceActionOptions produceActionOptions) {
        iStage.addAction(new LambdaInvokeAction(
                LambdaInvokeActionProps.builder()
                                       .lambda(this.fn)
                                       .build()));

        return CodePipelineActionFactoryResult.builder().runOrdersConsumed(1).build();
    }
}
```

### What did you expect to happen?

`cdk synth` was successful

### What actually happened?

```
Caused by: software.amazon.jsii.JsiiException: Cannot construct instance of `software.amazon.awscdk.pipelines.ProduceActionOptions` (no Creators, like default constructor, exist): abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information
 at [Source: UNKNOWN; line: -1, column: -1]
```

### Environment

  - **CDK CLI Version  :** 1.115.0
  - **Framework Version:**
  - **Node.js Version:**  16 LTS
  - **OS               :** Linux Mint
  - **Language (Version):**  Java 8

### Other

--- 

This is :bug: Bug Report

**Comment by deyceg** [comment]
Looks like its a serialization issue during `CodePipeline.pipelineStagesAndActionsFromGraph`. I can create an instance of `ProduceActionOptions` in Java just fine, but when creating a custom step (and attaching it as `post`) it will call `factory.produceAction()` based on the node type (which is of `ICodePipelineActionFactory`). I guess because the return type is an interface not a concrete class it can't be new'ed from Java.

**Comment by ryparker** [comment]
Hey @deyceg :wave:

Thanks for bringing this to our attention.

I'm going to mark this as p1 which means it has been prioritized as important, although please keep in mind that we do have a large number of issues at the moment. It may be some time before we are able to solve this particular issue. We use +1s to help us prioritize our work, and as always we are happy to take contributions if anyone is interested to pick this up and submit a PR.

**Comment by deyceg** [comment]
> Hey @deyceg 👋
> 
> Thanks for bringing this to our attention.
> 
> I'm going to mark this as p1 which means it has been prioritized as important, although please keep in mind that we do have a large number of issues at the moment. It may be some time before we are able to solve this particular issue. We use +1s to help us prioritize our work, and as always we are happy to take contributions if anyone is interested to pick this up and submit a PR.

Hey @ryparker I'd be happy to take a look at it over the weekend. I'm pretty sure if I wrote a TypeScript equivalent it would work. Reasonably comfortable with both languages though not so much with JSII architecture. The actual exception message is from Jackson so it needs a hint of the class it should instantiate.

**Comment by rix0rrr** [comment]
We need to pass this on to JSII team. Sorry for the inconvenience.

**Comment by rix0rrr** [comment]
I think `effort/small` might be an underestimation 😏

**Comment by rix0rrr** [comment]
Moved to https://github.com/aws/jsii/issues/2951, further tracking over there.
