### ISSUE TITLE
(aws-cloudtrail, aws-route53, aws-ec2, aws-s3): possible bucket policy racing condition

### ISSUE THREAD

**Issue by fredski-github** [aws/aws-cdk#15808]
### Environment

  - **CDK CLI Version  :** 1.114.0 (build 7e41b6b)
  - **Framework Version:** 
  - **Node.js Version:**  v14.17.0
  - **OS               :** N/A using yaml file from cdk synth
  - **Language (Version):**  3.8.2

### Other

--- 

This is :bug: Bug Report

**Comment by fredski-github** [comment]
Reproduction Steps:

* create bucket with: aws_s3.Bucket
* create VPC and associate with bucket: aws_ec2.Vpc 
* create flowlog and associate with bucket: aws_ec2.CfnFlowLog
* create Trail and associate with bucket: aws_cloudtrail.Trail
* create Resolver and associate with bucket: VPC aws_route53resolver.CfnResolverQueryLoggingConfig and  aws_route53resolver.CfnResolverQueryLoggingConfigAssociation
* deploy the generated CloudFormation yaml file (i have a limitation i can't use cdk deploy for this stack)

What did you expect to happen?
* the CDK to resolve the dependencies and just work

What actually happened?
* about 10% of the time it fails due to insufficient bucket policy for one of the 3 services. here are the error messages:
    * Resource handler returned message: "Access Denied for LogDestination: b9c0dca97-j8ukw1crpqpe. Please check LogDestination permission" (RequestToken: 2bf7ce36-9b27-ccdb-68a1-69721e8bf2b9, HandlerErrorCode: GeneralServiceException)
   * Incorrect S3 bucket policy is detected for bucket: b9c0dca97-1qmnn9i4teu0y (Service: AWSCloudTrail; Status Code: 400; Error Code: InsufficientS3BucketPolicyException; Request ID: 38f531ff-a166-4b90-acf3-59ba761ca874; Proxy: null)

Other
* i am not able to set depends on using the CDK for the trail, vpcflow, and dns logs for the bucket. it is done under the hood.

**Comment by fredski-github** [comment]
i checked the cloudformation template and it does have a DependsOn statement. is it a cloudformation issue?

      TrailName: TheTrail
    DependsOn:
      - BucketLogsPolicy239CFD00

**Comment by rix0rrr** [comment]
Pretty unlikely that this is a CloudFormation bug. I imagine this code path would be well-trodden.

If anything, it could be S3 policy replication latency, but even that seems unlikely.

Can you confirm that in the template the dependencies are added on the right policies etc?

**Comment by fredski-github** [comment]
Bucket policy is correct for CloudTrail: https://github.com/aws-samples/aws-incident-response-playbooks-workshop/blob/main/cdk/cdk.out/CoreStack.yaml#L14

Trail has explicit dependency: https://github.com/aws-samples/aws-incident-response-playbooks-workshop/blob/main/cdk/cdk.out/CoreStack.yaml#L80

VPC Flow does not have explicit dependency: https://github.com/aws-samples/aws-incident-response-playbooks-workshop/blob/main/cdk/cdk.out/CoreStack.yaml#L412

DNS logs does not have explicit dependency: https://github.com/aws-samples/aws-incident-response-playbooks-workshop/blob/main/cdk/cdk.out/CoreStack.yaml#L428

I am puzzled ```delivery.logs.amazonaws.com``` is not in the policy but gets added by CloudFormation during runtime?! It is not in the template but ends up in the S3 Bucket, that is required for VPC Flow and DNS Logs.

thank you so much for looking into this.

**Comment by rix0rrr** [comment]
In that template I only see a bucket policy for the CloudTrail at all. I don't even see statements for the VPC Flow logging and the DNS logging, so I'm mystified how they would even work.

**Comment by fredski-github** [comment]
Those are my hypothesis as well. Because CDK takes care of the S3 Bucket policy related to CloudTrail, I was not able to include the statements for ```delivery.logs.amazonaws.com```, which mysteriously show up in the S3 Bucket during provisioning.

**Comment by rix0rrr** [comment]
I think the answer is in here:

> If the user creating the flow log owns the bucket, has PutBucketPolicy permissions for the bucket, and the bucket does not have a policy with sufficient log delivery permissions, we automatically attach the preceding policy to the bucket. **This policy overwrites any existing policy attached to the bucket.** (emphasis mine)

https://docs.aws.amazon.com/vpc/latest/userguide/flow-logs-s3.html

---------

Scenarios:

1. Bucket has cloudtrail statements
2. Create CloudTrail
3. Create Flow Log (overwrites bucket policy)
4. Success!

or

1. Bucket has cloudTrail statements
2. Create Flow Log (overwrites bucket policy)
3. Create CloudTrail --> FAIL

--------

The solution is to add the right statements also for the other logging targets.

**Comment by fredski-github** [comment]
fixed: https://github.com/aws-samples/aws-incident-response-playbooks-workshop/blob/main/cdk/core_stack.py#L33

many thanks!
