### ISSUE TITLE
(efs): No way to specify FileSystemPolicy for FileSystem

### ISSUE THREAD

**Issue by rectalogic** [aws/aws-cdk#15805]
We need to set a `FileSystemPolicy` on our EFS `FileSystem`
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-efs-filesystem.html#cfn-efs-filesystem-filesystempolicy

Can this only be set via property overrides?

### Environment

  - **CDK CLI Version  :** 2.0.0rc15
  - **Framework Version:** aws_cdk_lib-2.0.0rc15
  - **Node.js Version:** v14.17.1
  - **OS               :** all
  - **Language (Version):** Python 3.8 (also all)

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
Yes, you can use property overrides to set this value.

Marking it as a feature request.

**Comment by MrSyn88** [comment]
Taking a look a this
