### ISSUE TITLE
Backport the build of V2 unstable modules to `master`

### ISSUE THREAD

**Issue by skinny85** [aws/aws-cdk#15828]
In order to keep the `master` and `v2-main` branches as close as possible, we should backport all changes from https://github.com/aws/aws-cdk/pull/15442, https://github.com/aws/aws-cdk/pull/15722 and https://github.com/aws/aws-cdk/issues/15589 to `master` as well.

The reason they are on `v2-main` only today is that the version of the `@aws-cdk/assert` library that is compatible with `aws-cdk-lib`, which we need in order to run unit tests for the unstable modules, is only available on `v2-main`.

The solution we came up with is to migrate the unstable modules to use the `@aws-cdk/assertions` library instead of `@aws-cdk/assert`.

In order to take advantage of this migration in the unstable build, this PR: https://github.com/aws/aws-cdk/issues/15589 needs to be merged first (which in turn has a dependency on https://github.com/aws/aws-cdk/pull/15722).

After the migration is complete, we will need to submit a PR (or more than one of them) moving all of the changes required to build the unstable modules from `v2-main` to `master`.

**Comment by skinny85** [comment]
@nija-at gracefully volunteered to handle the migration of the unstable modules to `@aws-cdk/assertions`. Until that migration is complete, this task is blocked.

**Comment by njlynch** [comment]
Closed via https://github.com/aws/aws-cdk/pull/16401
