### ISSUE TITLE
(ec2/Peer): ability to initialize a Peer from an AWS-managed prefix list

### ISSUE THREAD

**Issue by james-mathiesen** [aws/aws-cdk#15820]
Currently the Peer resource has one integration point with prefix lists:

```java
public static prefixList(prefixListId: string): IPeer
```

However this is not sufficient to construct a Peer from an AWS managed prefix list.  Such prefix lists have predictable names (e.g. `com.amazonaws.us-east-1.dynamodb`) and are marked in the API as owned by AWS but the actual IDs (e.g. `pl-02cd2c6b`) are unpredictable.

### Use Case

AWS currently provides two managed prefix lists, one for DynamoDB and one for S3.

GatewayVpcEndpointAwsService provides instances for DynamoDB and S3 and these instances are not `IConnectable` because the service is exposed via routing rather than via DNS overrides and interface attachment. The AWS managed prefix lists correspond exactly to the IPs on the AWS side of these gateways and are intended to support customers that require deny-by-default egress.

The prefix lists that AWS provides can be located via the raw API (the name corresponds to the GatewayVpcEndpoint name and the owner is AWS) but I have not been able to find a lookup mechanism within the CDK.

### Proposed Solution

1. Add a class method in Peer that supports prefix list lookup by name and owner.

2. Provide some convenience mechanism comparable to GatewayVpcEndpointAwsService.

### Other

The following Python example demonstrates an appropriate prefix list lookup.  The name would normally be `com.amazonaws.us-east-1.dynamodb` or `com.amazonaws.us-east-1.s3`.  These are the same per-region identifiers used by GatewayVpcEndpointAwsService.

```python3
def get_managed_prefix_list_id(name: str) -> str:
    """ Locate an AWS managed prefix list by its name.

        The use of the boto3 client here is a hack, it ought to be
        possible to locate this resource via CDK but I haven't quite
        figured out how...

        Peer.prefix_list_id() cannot locate by name.
    """
    client = boto3.client('ec2')
    response = client.describe_managed_prefix_lists(
        DryRun=False,
        Filters=[
            {
                'Name': 'owner-id',
                'Values': ['AWS']
            },
            {
                'Name': 'prefix-list-name',
                'Values': [name]
            },
        ],
    )
    return response['PrefixLists'][0]['PrefixListId']
```

---

This is a :rocket: Feature Request

**Comment by njlynch** [comment]
Thanks for the feature request and detailed write-up!

I agree this would be a useful feature; however, marking this issue as `p2`, which means that we are unable to work on this immediately.

We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://join.slack.com/t/cdk-dev/shared_invite/zt-mso6p56d-qJp7SOTBvMaQuDrx7R2wHg) to solicit support for reprioritization.
