### ISSUE TITLE
Extract jsii-rosetta samples from the unstable modules

### ISSUE THREAD

**Issue by skinny85** [aws/aws-cdk#15825]
In the current build of unstable modules implemented in https://github.com/aws/aws-cdk/pull/15722, the `rosetta:extract` task is not being executed by the `scripts/transform.sh` script, even if you pass the `--extract` flag to it. That's because the `jsii-rosetta` tool can't be found in the inner monorepo in `packages/individual-packages` for some reason. We need to investigate why, and find a solution that makes it work, and then update `scripts/transform.sh` to execute the `build+test+extract` task on the unstable modules if `--extract` is passed to it.

Things that have been tried, and rejected:
* Adding `jsii-rosetta` as a dependency in `packages/individual-packages/package.json` (doesn't work, the binary still can't be found).
* Adding `jsii-rosetta` as a dependency to each copied unstable module (this works, but @nija-at rejected it, because it requires changing a [`pkglint` rule to allow direct JSII dependencies](https://github.com/aws/aws-cdk/blob/9efd800b4eea3a849edc5710975e4d70ec14a5cd/tools/pkglint/lib/rules.ts#L783-L801)).

**Comment by otaviomacedo** [comment]
Other things that have been tried:

* Adding more packages to lerna.json, so that `jsii-rosetta` would be brought in transitively:
```
    "../../tools/*",
    "../../packages/@aws-cdk/assert-internal",
    "../../packages/@aws-cdk/cfnspec",
    "../../packages/@aws-cdk/cx-api",
    "../../packages/awslint",
    "../../packages/aws-cdk-migration"
```
Doesn't work, the binary still can't be found.
* Same as above, but using yarn workspaces. Doesn't work; yarn looks for packages such as `@aws-cdk/cloudformation-diff` and `@aws-cdk/cloud-assembly-schema` (depended on by tools such as `cdk-integ-tools`). The build fails because yarn can't find these dependencies.

**Comment by otaviomacedo** [comment]
The only solution I could find was to bypass yarn workspaces and lerna and create a symlink to the `.bin` folder where all the executables can be found. Next steps:

* Dive deep and document the problems with the current build system (regarding the dependency graph, monorepos etc).
* Refactor the folder structure: create a folder with a different name than `individual-packages`, include `aws-cdk-lib` inside it and maybe other improvements.

**Comment by skinny85** [comment]
@otaviomacedo can this be closed now that https://github.com/aws/aws-cdk/pull/16112 has been merged?

**Comment by otaviomacedo** [comment]
Yes. Closing.
