### ISSUE TITLE
(aws-certificatemanager): Imminent end of support for Nodejs 10 Lambda functions

### ISSUE THREAD

**Issue by otterley** [aws/aws-cdk#15821]
Support by AWS Lambda for Node.js 10 is ending on August 31, 2021. We should upgrade the Node version in this module to version 14 ASAP after verifying compatibility.

**Comment by KBB99** [comment]
Happy to work on this issue starting Monday.

**Comment by njlynch** [comment]
We upgraded all of our custom resources to use NodeJS 14.x as part of #13488, which was released as part of v1.94.0 in March.

https://github.com/aws/aws-cdk/blob/52553448607c5096aea15a8e4093b95406dd3fe6/packages/@aws-cdk/aws-certificatemanager/lib/dns-validated-certificate.ts#L88-L94

If you're still seeing the version as NodeJS 10, please upgrade to CDK v1.94.0 or above.

I'm going to close this out. Please feel free to comment and @mention me if I've missed something here or if you have any follow-ups.
