### ISSUE TITLE
(core): Stack.exportValue() fails in an inscrutable way when called on a construct

### ISSUE THREAD

**Issue by den-t** [aws/aws-cdk#15834]
Trying to use .exportValue() to temporarily preserve an output from a stack. Met with a circular dependency when running `cdk synth`.

### Reproduction Steps

```ts
import * as cdk from '@aws-cdk/core'
import * as sns from '@aws-cdk/aws-sns'

class SampleStack extends cdk.Stack {
  public readonly snsTopic: sns.Topic

  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    this.snsTopic = new sns.Topic(this, 'SNS Topic', { topicName: 'sample'})
    this.exportValue(this.snsTopic, {
      name: 'sample',
    })
  }
}

const app = new cdk.App();
new SampleStack(app, 'SampleStack');
```

### What did you expect to happen?

Expected the synth command to work and produce CloudFormation output.

### What actually happened?

```zsh
 % cdk synth

/Users/.../cdk-issue/node_modules/@aws-cdk/core/lib/private/resolve.ts:127
    throw new Error('Unable to resolve object tree with circular reference. Path: ' + pathName);
          ^
Error: Unable to resolve object tree with circular reference. Path: /Outputs/${Token[SampleStack.Exportsample.LogicalID.22]}/Value/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host
    at resolve (/Users/../cdk-issue/node_modules/@aws-cdk/core/lib/private/resolve.ts:127:11)
    at Object.resolve (/Users/../cdk-issue/node_modules/@aws-cdk/core/lib/private/resolve.ts:119:77)
    at resolve (/Users/../cdk-issue/node_modules/@aws-cdk/core/lib/private/resolve.ts:230:47)
    at Object.resolve (/Users/../cdk-issue/node_modules/@aws-cdk/core/lib/private/resolve.ts:119:77)
    at resolve (/Users/../cdk-issue/node_modules/@aws-cdk/core/lib/private/resolve.ts:230:47)
    at Object.resolve (/Users/../cdk-issue/node_modules/@aws-cdk/core/lib/private/resolve.ts:119:77)
...
```

### Environment

  - **CDK CLI Version  :** 1.116.0 (build d04661d)
  - **Framework Version:** 1.116.0
  - **Node.js Version:** v14.16.0
  - **OS               :** macOS 11.5 (20G71)
  - **Language (Version):** TypeScript (~3.9.7; resolved to 3.9.10)

### Other

Might be specific to SNS Topic? Haven't tried on other constructs.

--- 

This is :bug: Bug Report

**Comment by jumic** [comment]
You are trying to export the whole SNS topic construct in this line:
```ts
this.exportValue(this.snsTopic, {
```

To resolve the issue, you need to specify which attribute you want to export, e.g. `topicArn`:
```ts
this.exportValue(this.snsTopic.topicArn, {
```

The circular dependency error should disappear after this change.

**Comment by den-t** [comment]
Yep. The issue is that topic is required in the second stack, not just its ARN.

I'm using `lambda.Function.addEventSource(new lambdaEventSources.SnsEventSource(props.snsTopic))`.

```
class SnsEventSource {
  ...
  constructor(topic: sns.ITopic, props?: SnsEventSourceProps);
}
```

There are workarounds. But they are all rather manual and don't follow the simplicity of .exportValue().

**Comment by den-t** [comment]
Taking it back. :) `this.exportValue(this.snsTopic.topicArn)` produces the same output as using the topic property elsewhere would.

My issue is resolved. But how could it be communicated so that confusion like in my previous message is avoided?

Was genuinely expecting that I need to export the same value as used in the second stack. Turns out can export only the ARN?

**Comment by jumic** [comment]
Do both stacks belong to the same CDK app? In this case, you can pass the topic between both stacks as described here:
https://docs.aws.amazon.com/cdk/api/latest/docs/core-readme.html#accessing-resources-in-a-different-stack

CDK does the CloudFormation export/import in the background automatically. You don't have to use `this.exportValue()` in your code.

**Comment by den-t** [comment]
I was working toward making changes after I used the topic in another stack.
Essentially following the next section https://docs.aws.amazon.com/cdk/api/latest/docs/core-readme.html#removing-automatic-cross-stack-references

**Comment by den-t** [comment]
The second stack is using `ITopic` in `new lambdaEventSources.SnsEventSource(props.snsTopic)`.

So I expected that for the first deploy I need to `.exportValue(ITopic)`, not `.exportValue(ITopic.topciArn)`.

**Comment by jumic** [comment]
You don't need to export the whole topic construct in this case. You only have to export the properties, that are used in the second stack.

Please try to use the following:
```ts
this.exportValue(this.snsTopic.topicArn);
```

In folder `cdk.out`, you can check the `Outputs` section of the generated CloudFormation template. You need to make sure that the outputs will not change after you remove the cross-stack-reference. Exporting the topicArn should lead to the same outputs, therefore it should solve your issue.

If it doesn't  solve the issue, please paste your original and new CDK code and the error message from the CloudFormation stack (when you update the stack) while removing the reference.

**Comment by den-t** [comment]
> You don't need to export the whole topic construct in this case. You only have to export the properties, that are used in the second stack.

How do I know which properties are used? I'm only specifying the construct reference, please see below.

> Please try to use the following:
> 
> ```ts
> this.exportValue(this.snsTopic.topicArn);
> ```
> 
> In folder `cdk.out`, you can check the `Outputs` section of the generated CloudFormation template. You need to make sure that the outputs will not change after you remove the cross-stack-reference. Exporting the topicArn should lead to the same outputs, therefore it should solve your issue.

That's what I've done in this [comment](https://github.com/aws/aws-cdk/issues/15834#issuecomment-890117550):
> this.exportValue(this.snsTopic.topicArn) produces the same output as using the topic property elsewhere would.
>
> My issue is resolved.

The confusion is that I'm not using any properties in the second task. Am using the reference to the whole construct.
Please note `.snsTopic`, not `.snsTopic.topicArn` in another stack.
```ts
new lambdaEventSources.SnsEventSource(props.snsTopic)
```

That's why I went with trying to export the whole construct in the first place.
Could we somehow make it clearer, that when we use `ITopic` elsewhere, exporting just the ARN is fine?

**Comment by jumic** [comment]
Sorry, I thought you are still trying to solve the issue.

As far as I know, there is no overview which properties you have to export. If somebody else knows an overview/documentation, please add it here.

I think you have to options how to get the properties that need to be exported:
- Check `Outputs` section of the CloudFormation in folder `cdk.out`. Maybe it's possible to recognize the properties there. This was the approach when I answered to this issue first, I just tried to guess the properties.
- Follow the CDK source code to analyze which property is used. As far as I know, CDK only exports the properties that are referenced in the second stack.

In case of the SNSEventSource, you can follow the code until this line, where the topicArn is read:
https://github.com/aws/aws-cdk/blob/a6fac4974fa17949b836c72d04e1cc4504bc920a/packages/%40aws-cdk/aws-sns/lib/subscription.ts#L111

As mentioned before, if there are other ideas how to get this information, it would be great it could be added here. :)

**Comment by rix0rrr** [comment]
To start with, we should just reject calling `exportValue` on anything that's an object but not a token.

Second, it's a good idea to list all values that are being exported from a stack (probably emitted to metadata) so that users can use this information to write matching `exportValue()` calls.
