### ISSUE TITLE
(function): lambda.currentVersion doesn't reflects version created outside of CFN 

### ISSUE THREAD

**Issue by andrewb1234** [aws/aws-cdk#15843]
Issue is a continuation of : https://github.com/aws/aws-cdk/issues/15788 .

I am running into an odd issue that I do not believe is an expected behavior. I have some lambda (functionA) belonging to stackA and a new version of functionA is created outside of a CFN deployment (unsure why but not important). I then pass functionA's current Version to stackB via a SSM parameter. 

The problem I'm having is that although functionA's currentVersion is updated from V1 to V2, for example, StackA is not detecting any CFN template changes and thus does nothing. Code is below. 

In the below code, for example, our output `FunctionA2CurrentVersion<randomNumbers>` has a physical Id `arn:aws:lambda:us-east-1:<account>:function:functionA:1`, although functionA:2 is the latest version. 

Although not listed below, I have tried updating the version object created from `lambdaFunc.currentVersion` by using `CfnResource.addMetadata` - In this case, the version does perform a metadata update but nothing is changed about the labmdaCurrentVersion object. 
### Reproduction Steps

Stack A2
```ts
// Imports
export class StackA2 extends Stack {
    public readonly versionArnParamName: string;
    constructor(scope: Construct, id: string, props: StackProps) {
        super(scope, id, props);
        const codeRef = <internal code base>
        const lambdaFunc = new Function(<someCode>);
        const version = lambdaFunc.currentVersion;
        version.applyRemovalPolicy(RemovalPolicy.RETAIN);

        this.versionArnParamName = new StringParameter(this, 'Version ARN', {
            stringValue: version.functionArn
        }).parameterName;
    }
}
```
Stack B2 
```ts
// Import

export interface StackB2Props extends StackProps {
    readonly versionArnParamName: string;
}
export class StackB2 extends Stack {
    constructor(scope: Construct, id: string, props: StackB2Props) {
        super(scope, id, props);
        const dynamicVersion = new DynamicVersion(this, "dynVers", {
            versionArnParamName: props.versionArnParamName
        });
        const done = new Succeed(this, "Done");
        const invoke = new LambdaInvoke(this, "invoke", {
            lambdaFunction: dynamicVersion.version
        })
        const stateMachine = new StateMachine(this, "StateMachine2", {
            definition: invoke.next(done),
            stateMachineName: "StateMachineB2"
        });
        (stateMachine.node.defaultChild as CfnResource).addMetadata('alwaysUpdate', Date.now().toString())
    }
}
```
Dynamic Version 
```ts
// Imports
interface DynamicVersionProps {
    readonly versionArnParamName: string;
}
export class DynamicVersion extends Construct {
    public readonly version: IFunction;

    constructor(scope: Construct, id: string, props: DynamicVersionProps) {
        super(scope, id);

        const dynamicVersionArn = new CfnDynamicReference(CfnDynamicReferenceService.SSM, props.versionArnParamName).toString()
        this.version = Function.fromFunctionArn(this, 'Default', dynamicVersionArn);
    }
}
```

### Environment

  - **CDK CLI Version  :**
  - **Framework Version:**
  - **Node.js Version:** 12.x
  - **OS               :** MacOs
  - **Language (Version):** TypeScript

### Other

--- 

This is :bug: Bug Report

**Comment by BenChaimberg** [comment]
Discussed offline – the code value was being supplied to the CfnFunction via CFN parameters which are not updated even if the code changes, so currentVersion did not register a change and thus the template had no changes.
