### ISSUE TITLE
(all Cfn Resources): Enable import_value for Cfn resources

### ISSUE THREAD

**Issue by lony** [aws/aws-cdk#15859]
I want to use cdk.Fn.import_value for ALL elements of a Cfn resource.
For example, I have a security group and want to assign a port as a reference to RDS but can only use numbers.
I operate CDK using Python and would love to have the same flexibility as using CloudFormation directly with troposphere.

```
ec2.CfnSecurityGroupIngress(
    ...
    group_id=cdk.Fn.import_value(
        "-".join(["StackName", "SgARN"])
    ),
    ...
    from_port=5432,
    # TODO use import value when possible
    # from_port=cdk.Fn.import_value(
    #     "-".join(["StackName", "RdsPort"])
    # ),
)
```

### Use Case

- Create CloudFormation resource
- Link values inside stack as using YAML or JSON

### Proposed Solution

Instead of using the limited signature

`to_port: typing.Optional[jsii.Number] = None,`

Introduce import_value and ref as a type for Cfn parameter

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

**Comment by rix0rrr** [comment]
You are looking for [`Token.as_number()`](https://docs.aws.amazon.com/cdk/latest/guide/tokens.html#tokens_encoding)
