### ISSUE TITLE
(aws-lambda): profiling not enabled when `profiling: true` with Python v3.6+ runtime

### ISSUE THREAD

**Issue by ryparker** [aws/aws-cdk#15860]
CodeGuru profiling for Python lambdas is not supported as [the docs describe](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-lambda-readme.html#lambda-with-profiling). CDK supports Java profiling just fine because all that is required on Java lambda’s is to add [two environment variables](https://docs.aws.amazon.com/codeguru/latest/profiler-ug/lambda-custom.html). However for Python lambdas you have to add a [special CodeGuru lambda layer](https://docs.aws.amazon.com/codeguru/latest/profiler-ug/python-lambda-layers.html) which the [CDK does not seem to implement](https://github.com/aws/aws-cdk/blob/58fda9104ad884026d578dc0602f7d64dd533f6d/packages/%40aws-cdk/aws-lambda/lib/function.ts#L612-L635).

There is already an [issue open that relates to implementing a CodeGuru layer resource](https://github.com/aws/aws-cdk/issues/13001) however it does not mention the missing support for Python or the [misleading documentation](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-lambda-readme.html#lambda-with-profiling).

### Reproduction Steps

```ts
import * as cdk from '@aws-cdk/core';
import * as lambda from '@aws-cdk/aws-lambda';

const app = new cdk.App();

class StackA extends cdk.Stack {
  constructor(parent: cdk.Construct, name: string, props?: cdk.StackProps) {
    super(parent, name, props);

    new lambda.Function(this, 'MyFunction', {
      runtime: lambda.Runtime.PYTHON_3_8,
      handler: 'index.handler',
      code: lambda.Code.fromAsset('lambda-handler'),
      profiling: true,
    });
  }
}

new StackA(app, 'stackA');
```

1. Run `tsc && cdk deploy`
2. Open the created Lambda in the AWS console.
3. Open "Configuration" tab.
4. Select "Monitoring and operations tools" sub tab.
5. Look under "Code profiling" to see if it was enabled.

### What did you expect to happen?

CodeGuru profiling to be enabled on the Python lambda.

### What actually happened?

CodeGuru profiling was not enabled on the Python lambda.

### Environment

  - **CDK CLI Version  :** v1.22.10
  - **Framework Version:** 
  - **Node.js Version:** v16.3.0
  - **OS               :** macOs Big Sur v11.4
  - **Language (Version):** all

### Other

To workaround this, you can manually add the necessary layer and env vars. This only works for Python 3.8.

```ts
import * as cdk from '@aws-cdk/core';
import * as lambda from '@aws-cdk/aws-lambda';

const app = new cdk.App();

class StackA extends cdk.Stack {
  constructor(parent: cdk.Construct, name: string, props?: cdk.StackProps) {
    super(parent, name, props);

    new lambda.Function(this, 'MyFunction', {
      runtime: lambda.Runtime.PYTHON_3_8,
      handler: 'index.handler',
      code: lambda.Code.fromAsset('lambda-handler'),
      profiling: true,
      layers: [
        lambda.LayerVersion.fromLayerVersionArn(this, "CodeGuruLayer", `arn:aws:lambda:${this.region}:157417159150:layer:AWSCodeGuruProfilerPythonAgentLambdaLayer:10`
        )
      ],
      environment: {
        AWS_LAMBDA_EXEC_WRAPPER: "/opt/codeguru_profiler_lambda_exec"
      }
    });
  }
}

new StackA(app, 'stackA');

```

--- 

This is :bug: Bug Report

**Comment by ryparker** [comment]
Related SIM #P49919461

**Comment by nija-at** [comment]
Duplicate https://github.com/aws/aws-cdk/issues/13001
