### ISSUE TITLE
(assertions): assertion inversion

### ISSUE THREAD

**Issue by nija-at** [aws/aws-cdk#15868]
Provide the ability to invert the list of assertions - `hasResource()`, `hasResourceProperties()`, etc. - to be inverted or negated, i.e., "does not have resource", "does not have resource with properties", etc.

See https://github.com/aws/aws-cdk/pull/15857#discussion_r681157846

----

Alternatively, the current experience of the following against a template that has no "Foo::Bar" resource will fail with the error "No resource matching Foo::Bar".

```ts
hasResourceProperties('Foo::Bar', Match.not({
  Baz: 'Qux'
}));
```

This needs to be fixed.

---

This is a :rocket: Feature Request

**Comment by indrora** [comment]
Closing as this ticket is stale (over 9 months since last event or relates to the CDKv1). 

If this is still a relevant request in the CDKv2, please open a new ticket.
