### ISSUE TITLE
aws-ecs: EcsOptimizedImage - inferentia type not supported

### ISSUE THREAD

**Issue by zhouxie123** [aws/aws-cdk#15862]
Hi, my team is building a service and setting up our infrastructure through CDK. We are using ECS to deploy and manage our service on EC2 Inferentia inf.6xlarge instances. We are seeking to use ECS-Optimized AMI to build on the instances as documented by ECS team here https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-optimized_AMI.html. However, it seems that inferenia image type is not supported by CDK. https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs.AmiHardwareType.html. Could add the Inferentia support to fill in the gap since ECS is supporting it?

### Use Case

Set up service ECS cluster using with ECS optimized Inferentia AMIs.

### Proposed Solution

Could you add support for inferentia AMI type https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs.AmiHardwareType.html.

### Other

* [x ] :wave: I may be able to implement this feature request
* [x ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by mostafafarzaneh** [comment]
I have the exact same problem. Is this on the AWS roadmap?
Maybe the Inferentia is not the right choice to use in ECS?
