### ISSUE TITLE
CLI: give an error message and return 1 when trying to deploy a non-existent stack

### ISSUE THREAD

**Issue by KTamas** [aws/aws-cdk#15866]
When trying to deploy a stack that does not exist (for example, `cdk deploy thisstackdoesnotexist`), the CDK simply gives no output, even the return code is 0. This is confusing, especially for people new to the CDK.

### Use Case

Use case is people not getting tripped up by this and scratching their heads, especially for people new to the CDK.

### Proposed Solution

Exit with return code 1 and give some sort of error i.e. `Error: stack 'thisstackdoesnotexist' does not exist."` Could implement some sort of fuzzy matching for stack name suggestions, so it could also say `Did you mean [x]?` or something like that.

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
Sounds like a good idea!
