### ISSUE TITLE
(aws-cognito): lambdaConfig.customEmailSender description seems incorrect

### ISSUE THREAD

**Issue by ffxsam** [aws/aws-cdk#15863]
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cognito.CfnUserPool.CustomEmailSenderProperty.html

The docs say `lambdaArn` and `lambdaVersion` are both optional. However, when I specify this in my code:

```ts
  userPool.lambdaConfig = {
    customEmailSender: {
      lambdaArn: props.cognitoEmailSender.functionArn,
    },
  };
```

I get this error upon deployment to CloudFormation:

`
1 validation error detected: Value null at 'lambdaConfig.customEmailSender.lambdaVersion' failed to satisfy constraint: Member must not be null (Service: AWSCognitoIdentityProviderService; Status Code: 400; Error Code: InvalidParameterException; Request ID: 5383d3db-671c-4fa0-b85d-c659dfc3c29a; Proxy: null)
`

So the Lambda version is required?

---

This is a 📕 documentation issue

**Comment by nija-at** [comment]
This property is currently not implemented in CloudFormation - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-customemailsender.html

**Comment by ffxsam** [comment]
Hmm, strange. Let me double-check this, because I seem to remember a conversation with a developer where they said some of these options were marked in the docs as unsupported, yet they still worked.

**Comment by ffxsam** [comment]
It works! I set the config on the user pool like so:

```ts
    customEmailSender: {
      lambdaArn: cognitoEmailSender.functionArn,
      lambdaVersion: 'V1_0',
    },
    kmsKeyId: kmsKey.keyArn,
```

And sure enough, when I create a new user in Cognito, the Lambda gets fired.

**Comment by RatulSaha** [comment]
@ffxsam could you please detail how to achieve `customEmailSender` trigger when creating a user pool? The following does not work:

```
import * as cdk from "@aws-cdk/core";
import * as cognito from "@aws-cdk/aws-cognito";

export class exampleStack extends cdk.Stack {
    constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
        super(scope, id, props);

        // The code that defines your stack goes here
        new cognito.UserPool(this, "example", {
            userPoolName: "examplePool",
            lambdaTriggers: {
                customEmailSender: {
                  lambdaArn: cognitoEmailSender.functionArn,
                  lambdaVersion: 'V1_0',
                },
            } 
            
        });
    }
}

```

**Comment by ffxsam** [comment]
@RatulSaha Sure!

```ts
  const cognitoEmailSender = new sst.Function(stack, 'CognitoEmailSender', {
    functionName: `${stack.stackName}-cognitoEmailSender`,
    handler: 'lambda/auth/cognito-email-sender.main',
  });

  // Allow Cognito to invoke the email sender Lambda
  cognitoEmailSender.grantInvoke(
    new iam.ServicePrincipal('cognito-idp.amazonaws.com')
  );

  const kmsKey = new kms.Key(stack, 'AuthKmsKey', {
    description: 'Required by Cognito',
    removalPolicy:
      stack.stage === 'prod' ? RemovalPolicy.RETAIN : RemovalPolicy.DESTROY,
  });

  (userPool.node.defaultChild as cognito.CfnUserPool).lambdaConfig = {
    customEmailSender: {
      lambdaArn: cognitoEmailSender.functionArn,
      lambdaVersion: 'V1_0',
    },
    kmsKeyId: kmsKey.keyArn,
  };
```

**Comment by RatulSaha** [comment]
Thank you, @ffxsam — really appreciate it!

For anyone stumbling upon later, this is how to add methods that are not part of high level construct, more details at here as well: https://github.com/aws-samples/amazon-cognito-example-for-external-idp/blob/12141c304c715e93302ac9facb369de539fad515/cdk/src/cdk.ts#L129

**Comment by peterwoodworth** [comment]
Seems like this issue can be closed. Let me know if you need this to be reopened
