### ISSUE TITLE
@aws-cdk/aws-ecs: Injecting existing SSM Parameter or Secrets into ECS Task definition (Typescript)

### ISSUE THREAD

**Issue by akshayp-vwits** [aws/aws-cdk#15880]
### The Question
I am trying to pass some existing SSM parameters as environment variables into my ecs task definition, but it gives me error.
Below is my sample code.

### Environment

  - **CDK CLI Version:** 1.108.0
  - **Module Version:** 1.115.0
  - **Node.js Version:** v14.15.0
  - **OS:** 
  - **Language (Version):** Typescript

### Other information

```
const param2 = sm.Secret.fromSecretCompleteArn(this, 'param', 'my_arn_value')
        const container = fargateTaskDefinition.addContainer("WebContainer", {
            image: ecs.RepositoryImage.fromEcrRepository(repository, "latest"),
            memoryLimitMiB: 512,
            environment: {
                SPRING_PROFILES_ACTIVE: "integration",
            },
            secrets:{
                ARTIFACTORY_PASSWORD: ecs.Secret.fromSecretsManager(param2)
            }
        });
```

It does not allow to pass param2, how can i reference a secret which is already present in the SSM or Secrets manager. (in case of AWS console we simple select valueFrom (secret ARN)

**Comment by peterwoodworth** [comment]
I'm unable to reproduce this error, could you tell me what exactly the error you're getting is?

**Comment by akshayp-vwits** [comment]
I was able to solve this issue, all i had to do was is update the module dependency versions.
