### ISSUE TITLE
(@aws-cdk/aws-neptune): Amazon CloudWatch Logs Exports properties not available for class DatabaseCluster in Neptune

### ISSUE THREAD

**Issue by haofeif** [aws/aws-cdk#15888]
### Use Case

It'll be great to add the properties to be able to enable CloudWatch Logs Export in class DatabaseCluster (construct) :
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-neptune.DatabaseCluster.html

### Proposed Solution

Be able to set Cloudwatch logs exports with EnableCloudwatchLogsExports prop :

### Other
Offered by CFN: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-neptune-dbcluster.html

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
The `CfnDBCluster` class is directly taken from CloudFormation: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-neptune-dbcluster.html

If CloudFormation has the feature, we have it. If CloudFormation doesn't, we don't, and there's nothing we can do about it.

**Comment by swapab** [comment]
Thanks @haofeif for raising this issue. I was also looking for this feature in aws-cdk v2.

I believe the proposed feature would enable `Audit Log` Export as shown below.
![image](https://user-images.githubusercontent.com/1291980/181466613-c0a837b6-1f83-43f1-8dd8-304fc96d1906.png)


Do we know if this feature will be available in v2? or should there be a separate request for that?

**Comment by Naumel** [comment]
Duplicate #20248

**Comment by humanzz** [comment]
> Duplicate #20248

Thanks for ur comment on the other issue. I noticed you closed it, but I want to call out that it also mentions a bit about metrics which I don't believe is covered by this issue

**Comment by humanzz** [comment]
@Naumel I've created a PR for the metrics part related to the other issue. I noticed `aws-cdk-owners` is the assigned reviewer so am afraid that might get lost since the issue it's related to is closed. Appreciate if u can have a look at this assignment issue!

**Comment by humanzz** [comment]
And here's one for logs https://github.com/aws/aws-cdk/pull/22004
