### ISSUE TITLE
(aws-config): Add support for ec2-instance-profile-attached managed rule in ManagedRuleIdentifiers class

### ISSUE THREAD

**Issue by zechariahks** [aws/aws-cdk#15898]
Currently [ManagedRuleIdentifiers](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-config.ManagedRuleIdentifiers.html) doesn't support identifier for ec2-instance-profile-attached managed rule (EC2_INSTANCE_PROFILE_ATTACHED). The documentation for this rule is [here](https://docs.aws.amazon.com/config/latest/developerguide/ec2-instance-profile-attached.html)

### Use Case

I should be able to create the ec2-instance-profile-attached managed rule through CDK higher level construct.

### Proposed Solution

Workaround is to use the [CfnConfigRule](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-config.CfnConfigRule.html) construct. 

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
Seems like a matter of adding a new constant. Happy to merge this if someone submits a PR.

**Comment by zechariahks** [comment]
@rix0rrr I will be able to help with adding the new constant. I will make the changes and update the PR here.
