### ISSUE TITLE
(route53): software.amazon.awscdk.services.route53.targets not found

### ISSUE THREAD

**Issue by Dunmord** [aws/aws-cdk#15909]
### Reproduction Steps
Create a new maven project and import

<dependency>
  <groupId>software.amazon.awscdk</groupId>
  <artifactId>route53</artifactId>
  <version>1.116.0</version>
</dependency>

Then in a new java file, try to import the  software.amazon.awscdk.services.route53.targets library.

According to the documentation  here https://docs.aws.amazon.com/cdk/api/latest/java/index.html?software/amazon/awscdk/services/route53/targets/CloudFrontTarget.html, this should be a valid path.

### What did you expect to happen?

Successfully import the library.

### What actually happened?

Library is not found.

### Environment

  - **CDK CLI Version  :*1.116.0*
  - **Framework Version:*1*
  - **Node.js Version:*14.17.0* 
  - **OS               :*Windows*
  - **Language (Version):*Java* 

### Other

--- 

This is :bug: Bug Report

**Comment by njlynch** [comment]
To access the route53.targets package, you need to install the route53-targets package (https://search.maven.org/artifact/software.amazon.awscdk/route53-targets/1.116.0/jar), as well as the route53 target. 

Closing this out; feel free to @mention me if you have any follow-ups.
