### ISSUE TITLE
(aws-cdk): don't let cdk init allow incorrect app names

### ISSUE THREAD

**Issue by Scorpil** [aws/aws-cdk#15901]
### The Issue

`cdk init` does not perform validation on a current directory name, so it may create a broken app.

### Steps to reproduce

```
$ mkdir 1
$ cd 1
$ cdk init app --language python
<... app generate successfully ...>
$ cdk ls
  File "/Users/scorpil/1/app.py", line 12
    from 1.1_stack import 1Stack
            ^
SyntaxError: invalid decimal literal
Subprocess exited with error 1
```

### Expected behavior

Ideally `cdk init` should notify the user that the selected app name is not acceptable instead of generating a broken app.

### Environment

  - **CDK CLI Version:** 1.116.0 (build d04661d)
  - **OS:** MacOS Big Sur
  - **Language (Version):** Python 3.9

**Comment by peterwoodworth** [comment]
Thanks for submitting this issue!

I can confirm the behavior seen here. I'm labelling this as a feature request as p2, which means that we are unable to work on this immediately.

We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://join.slack.com/t/cdk-dev/shared_invite/zt-mso6p56d-qJp7SOTBvMaQuDrx7R2wHg) to solicit support for reprioritization.
