### ISSUE TITLE
CloudFormationStack.template : Cannot read existing template

### ISSUE THREAD

**Issue by blaoueille** [aws/aws-cdk#15907]
Hi,

When I execute a `cdk diff` on my CDK project to get differences with an existing CloudFormation template (that was not initially generated by this project). In fact, it's failing with some stacks and not all of them.
It's really hard to define why as we have no information one the root cause.

I have use the debug mode and verbose mode to have more information, and it's not really helpful.

### Reproduction Steps

My initial  code :

```typescript
const mainStackName: string = "my-stack-01";

  const mainStack = new MyLoaderStack(app, mainStackName, {
    env: {
      region: buildConfig.awsProfileRegion,
      account: buildConfig.awsAccountID
    }
  }, buildConfig);
```

If mainStackName is a CloudFormation that is not existing, it's working in all case, if it exists, it fails for some of them but with a difficult reason to guess...

### What actually happened?

For the CloudFormation that are not working well I have this output:

```sh
Stack my-stack-01
Reading existing template for stack my-stack-01.
Unexpected token A in JSON at position 0
SyntaxError: Unexpected token A in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.deserializeStructure (C:\Users\XXXX\AppData\Roaming\npm\node_modules\aws-cdk\lib\serialize.ts:19:17)
    at CloudFormationStack.template (C:\Users\XXXX\AppData\Roaming\npm\node_modules\aws-cdk\lib\api\util\cloudformation.ts:70:50)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at CdkToolkit.diff (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\aws-cdk\lib\cdk-toolkit.ts:104:33)
    at initCommandLine (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\aws-cdk\bin\cdk.ts:213:9)

```

If I made a test with a stack "my-stack-02", that also exist (ie. already deployed on my AWS account like my-stack-01), it's working well. But as I don't understand this error and what could be wrong.
I checked the remote CloudFormation templates, but I guess if their format was not correct, they will not be deployed on AWS CloudFormation...

### Environment

  - **CDK CLI Version  : 1.116.0
  - **Framework Version: 1.116.0
  - **Node.js Version: v14.17.4
  - **OS               : Windows 10
  - **Language (Version): TypeScript 3.9.7

### Other

`aws synth` is working as expected.

--- 

This is :bug: Bug Report

**Comment by peterwoodworth** [comment]
Hey @blaoueille,

Sorry you're running into this issue. I don't think I have a clear picture of what's happening, some clarification on these would be great:

- You only run into this error when the stack is already deployed, correct?
- How are you first deploying the initial stack?
- What did you do differently between `my-stack-01`  and `my-stack-02`?

Thanks!

**Comment by blaoueille** [comment]
Hi,

Yes it only happens on stack already deployed.

The initial stack was deployed through the AWS CLI commands : `aws cloudformation update-stack --stack-name stack-01 --template-body file://./stack.yaml --parameters file://./params.json --tags file://./tags.json --profile my-profile`. We want to migrate it with AWS CDK without deleting our existing resources (because of secrets etc...).

"my-stack-02" is another stack that is totally different (in fact the diff shows that it will remove everyting and create everything).

Meanwhile, I have found a workaround, for resolving it, if I open the AWS Console and open the CloudFormation template (my-stack-01) in the designer, then select the JSON output, validate the template, save the template in local and update the stack with this template. Normally no structure changes has been done to my stacked resources but then the AWS CDK diff is working well after (ie it is able to make the "diff" command). This is weird.

I don't really know if it's a mistake of AWS commands when we create the initial stack (at least it appears 2 times on 2 different stacks) but it could be useful to have a way to debug it or to see exactly what the CDK tries to parse.

Regards

**Comment by peterwoodworth** [comment]
Have you read our docs on [Migrating existing Cfn templates to CDK?](https://aws.amazon.com/blogs/developer/migrating-cloudformation-templates-to-the-aws-cloud-development-kit/)

**Comment by blaoueille** [comment]
Hi,
Yes but without using this migration feature, it was working well in other templates. I was not thinking it was absolutely mandatory to use the cfn-include in my case.
I was more wondering why it was no able to deserialize the existing stack, there is no real way to debug or to see the output of the retrieved remote template.
However, I have a workaround now (described in my previous post).
Regards,
Bruno
