### ISSUE TITLE
AWS::WAFv2: Undocumented deprecations

### ISSUE THREAD

**Issue by MisterGlass** [aws/aws-cdk#15910]
The README states: `All classes with the Cfn prefix in this module (CFN Resources) are always stable and safe to use.`

The [changelog](https://github.com/aws/aws-cdk/blob/master/CHANGELOG.md) only mentions the WAF once 

Today I am attempting to update CDK and seem to be running into a deprecation. `aws_wafv2.CfnWebACL.StatementOneProperty` worked in my code last night, but after updating from 1.89.0 to 1.117.0, I get the error:
`‘CfnWebACL’ has no attribute ‘StatementOneProperty’

I even went so far as to look at the log of [documentation changes](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html), but I can't find any relevant information.

I did, however, find the property is mentioned in the [archived documentation](https://web.archive.org/web/20210407023955if_/https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-wafv2-webacl-statementone.html) on the wayback machine.

Please provide updated documentation about this property and/or it's replacement.

---

This is a 📕 documentation issue

**Comment by njlynch** [comment]
The statement of stability of the L1/Cfn resources is based on stability of the CloudFormation resource specification itself, which is supposed to retain backwards compatibility; it looks like in this case, a backwards-incompatible change was made to the spec. This shouldn't happen -- I'll follow up internally with the responsible teams.

> The changelog only mentions the WAF once

We typically only capture the L2 changes in the Changelog. For the detailed breakdown of CloudFormation changes, see the separate [cfnspec changelog](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/cfnspec/CHANGELOG.md). The changes were captured under the "CloudFormation Resource Specification v35.0.0" release notes.

I do see notes about this change in the documentation changes log you posted, from April 22, 2021:

> AWS::WAFv2::WebACL
> You can now nest rule statements without using different names for statements at different levels. For example, instead of using AndStatementOne and AndStatementTwo to nest an AND rule statement inside another AND rule statement, you can use AndStatement for both. The new statement properties are AndStatement, NotStatement, OrStatement, RateBasedStatement, and Statement.

It looks like the new style is to use either one of the specific statement types directly (e.g., `ByteMatchStatement`) or combine them via a boolean logic statement (e.g., `AndStatement`).

Again, apologies for the breaking changes. Closing this out; feel free to comment and mention me with any follow-ups.

**Comment by MisterGlass** [comment]
Thanks @njlynch that link was helpful!
So, if I'm reading this right, my python `aws_wafv2.CfnWebACL.StatementOneProperty` was 
 the `AWS::WAFv2::WebACL.StatementOne` that was removed? And I'm guessing that similarly `AWS::WAFv2::WebACL.Statement` turns into `aws_wafv2.CfnWebACL.StatementProperty` in python?

**Comment by njlynch** [comment]
That looks right to me. See https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_wafv2/CfnWebACL.html#statementproperty for the full Python docs for StatementProperty.
