### ISSUE TITLE
aws-msk: ICluster missing bootstrapBrokers attributes

### ISSUE THREAD

**Issue by davidmckenzie** [aws/aws-cdk#15916]
Importing an MSK cluster via fromClusterARN returns an ICluster instead of a Cluster. The ICluster class appears to be missing the attributes such as bootstrapBrokers. Use case for this is importing a cluster managed elsewhere so that you can include the broker list in an ECS task's environment variables.

### Reproduction Steps

```
from aws_cdk import aws_msk as _msk
kafkaCluster = _msk.Cluster.from_cluster_arn(self, 'mskCluster', 'x')
print(kafkaCluster.bootstrap_brokers_tls)
```

### What did you expect to happen?

List of brokers should be printed

### What actually happened?

```
Traceback (most recent call last):
  File "app.py", line 23, in <module>
    EcsStack(app, "x",
  File "/home/x/cdk/.venv/lib/python3.8/site-packages/jsii/_runtime.py", line 83, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/home/x/cdk/lib/ecs.py", line 114, in __init__
    print(kafkaCluster.bootstrap_brokers_tls)
  File "/home/x/cdk/.venv/lib/python3.8/site-packages/jsii/_reference_map.py", line 149, in __getattr__
    raise AttributeError(f"'%s' object has no attribute '%s'" % (type_info, name))
AttributeError: '<class 'aws_cdk.core.Resource'>+<class 'aws_cdk.aws_msk._IClusterProxy'>' object has no attribute 'bootstrap_brokers_tls'
Subprocess exited with error 1
```

### Environment

  - **CDK CLI Version  :** 1.116.0
  - **Framework Version:** 1.116.0
  - **Node.js Version:** v14.16.0
  - **OS               :** WSLv2 (Ubuntu on Windows)
  - **Language (Version):** Python (3.8)

### Other

`print(kafkaCluster.cluster_name)` confirms that it is importing the cluster correctly

--- 

This is :bug: Bug Report

**Comment by otaviomacedo** [comment]
It's worth checking whether we can move the getters for `bootstrapBrokers`, `bootstrapBrokersTls`, `bootstrapBrokersSaslScram` up to `ClusterBase`.

I am unassigning and marking this issue as `p2`, which means that we are unable to work on this immediately.

We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://join.slack.com/t/cdk-dev/shared_invite/zt-mso6p56d-qJp7SOTBvMaQuDrx7R2wHg) to solicit support for reprioritization.

**Comment by ambasta** [comment]
Can we please reopen this?
