### ISSUE TITLE
(certificatemanager): DnsValidatedCertificate breaks during cdk deploy when tokens are taken from the secretsmanager

### ISSUE THREAD

**Issue by piotrekwitkowski** [aws/aws-cdk#15926]
I am trying to build the `IHostedZone` object using the `fromHostedZoneAttributes` method. My `hostedZoneArn` is something like this: `hostedZoneArn arn:${Token[AWS.Partition.5]}:route53:::hostedzone/${Token[TOKEN.107]}`.  However, during deployment, the `hostedZoneId` gets resolved to `{{resolve:secretsmanager:arn:aws:secretsmanager:eu-central-1:123456789012:secret:HOSTED_ZONE_ID:SecretString:::}}` and I get the error: 
```
Received response status [FAILED] from custom resource. Message returned: 1 validation error detected: Value
'{{resolve:secretsmanager:arn:aws:secretsmanager:eu-central-1:123456789012:secret:HOSTED_ZONE_ID:SecretString:::}}'
at 'resourceId' failed to satisfy constraint: Member must have length less than or equal to 32
(RequestId: 018b6b6c-xxxx-xxxx-c877008127b5)
```

### Reproduction Steps

```ts
// inside the stack
// one must have secrets created in the SecretsManager first
const hostedZoneIdSecret = Secret.fromSecretNameV2(this, 'HostedZoneIdSecret', HOSTED_ZONE_ID);
const hostedZoneId = hostedZoneIdSecret.secretValue.toString();
const hostedZoneNameSecret = Secret.fromSecretNameV2(this, 'HostedZoneNameSecret', HOSTED_ZONE_NAME);
const hostedZoneName = hostedZoneNameSecret.secretValue.toString();

const hostedZone = HostedZone.fromHostedZoneAttributes(this, 'HostedZone', {
  hostedZoneId: hostedZoneId,
  zoneName: hostedZoneName
});

console.log('hostedZoneArn', hostedZone.hostedZoneArn);
// hostedZoneArn arn:${Token[AWS.Partition.5]}:route53:::hostedzone/${Token[TOKEN.107]}
console.log('hostedZoneId', hostedZone.hostedZoneId);
// hostedZoneId ${Token[TOKEN.107]}
console.log('zoneName', hostedZone.zoneName);
// zoneName ${Token[TOKEN.109]}

new DnsValidatedCertificate(this, 'Certificate', {
  hostedZone: hostedZone, // <-- this fails
  domainName: domainName
})

```
### What did you expect to happen?

Succesful deployment of the synthesized template.

### What actually happened?

I got the error `'resourceId' failed to satisfy constraint: Member must have length less than or equal to 32`

### Environment

  - **CDK CLI Version :** 2.0.0-rc.16 (build dba3421)
  - **Framework Version:**
  - **Node.js Version:** v14.17.3
  - **OS:** Amazon Linux (CloudDesktop)
  - **Language (Version):** all? I am using TypeScript (4.3.5)

### Other
Similar to my other issue: https://github.com/aws/aws-cdk/issues/15925

--- 

This is :bug: Bug Report

**Comment by piotrekwitkowski** [comment]
Interestingly, the certificate will be created in the Certificate Manager, but the stack deployment fails and rollbacks. The fresh certificate will be orphaned and will not be removed.

**Comment by jumic** [comment]
DnsValidatedCertificate [uses a CustomResource](https://github.com/aws/aws-cdk/blob/a04c017323130cb6f88a530e192e9e0e86fb137a/packages/%40aws-cdk/aws-certificatemanager/lib/dns-validated-certificate.ts#L108) to validate the certificate. The hosted zone id will be passed to this custom ressource.

According to the [CloudFormation documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/dynamic-references.html#dynamic-references-considerations) it's not possible to use the dynamic reference in custom resources:
> Dynamic references for secure values, such as ssm-secure and secretsmanager, aren't currently supported in custom resources.

From my point of view, you can't use the value from Secrets Manager because it is currently not supported by CloudFormation.
