### ISSUE TITLE
(cognito): add adminSetUserPassword() function

### ISSUE THREAD

**Issue by naseemkullah** [aws/aws-cdk#15927]
Please add a function that calls  [adminSetUserPassword](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentityServiceProvider.html#adminSetUserPassword-property) to set a user password (and confirm that user) programatically, after having created it via https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cognito.CfnUserPoolUser.html

### Use Case

Automate test user creation. The test user is then used in synthetic checks (canaries). Want to achieve this 100% in cdk. The test user can be created via https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cognito.CfnUserPoolUser.html but then needs password to be set/account status confirmed.

### Proposed Solution

As per above:

Please add a function that calls [adminSetUserPassword](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentityServiceProvider.html#adminSetUserPassword-property).

### Other

The functionality may need to be added in https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_Cognito.html first, please triage/create dependency issues accordingly.

This functionality may already exist and I am unable to find it? If so please show me!

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by nija-at** [comment]
The CDK is for provisioning infrastructure powered via AWS CloudFormation. Setting a user's password is not provisioning infrastructure. Hence this is not available via CloudFormation or the CDK.

Consider using the AWS CLI or the AWS SDK for calling this API.

**Comment by naseemkullah** [comment]
I beg to differ, a user pool user is a cloud resource and it's password and account status are part of its configuration.

Please look over the use case mentioned, have customer empathy and consider reopening.
