### ISSUE TITLE
aws-cognito: Can not Attach CustomEmailSender

### ISSUE THREAD

**Issue by JustinMiehle** [aws/aws-cdk#15920]
Hi All!

As described here, Cognito supports "CustomEmailSender" triggers:
https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-custom-sender-triggers.html

In CDK, the mechanism for adding one (to my understanding) is either via:
`pool.addTrigger(
            UserPoolOperation.of("CustomEmailSender"),
            func
        );`
or
`lambdaTriggers: {
            customEmailSender: func
}
`

However, the addTrigger method fails to synthesize:
`Expected an object, but received: "arn:aws:lambda:eu-central-1:11111111:function:func".`

This seems like it´s caused by the addTrigger method (https://github.com/aws/aws-cdk/blob/a5d27aabc7cab223f4000946506aa0c06c5f34b5/packages/%40aws-cdk/aws-cognito/lib/user-pool.ts#L804)  ALWAYS setting the trigger to only the function Arn, even though the customEmailSender one expects an Object: 
```
public addTrigger(operation: UserPoolOperation, fn: lambda.IFunction): void {
    if (operation.operationName in this.triggers) {
      throw new Error(`A trigger for the operation ${operation} already exists.`);
    }

    this.addLambdaPermission(fn, operation.operationName);
    (this.triggers as any)[operation.operationName] = fn.functionArn;
  }
```

The Object that it expects is specified here:
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cognito.CfnUserPool.CustomEmailSenderProperty.html

I guess it would need a switch to differentiate between "normal" triggers and the two special ones that require objects? Is there a way to override this to work around it?

### Reproduction Steps
```
const pool = new UserPool(this, "test", {
            userPoolName: "test"
})

let func = Function.fromFunctionArn(this, "TEST", "arn:aws:lambda:eu-central-1:1111111:function:func");

pool.addTrigger(
      UserPoolOperation.of("CustomEmailSender"),
      func
);
```
### What did you expect to happen?

Synth goes through

### What actually happened?

It throws as described above
`Expected an object, but received: "arn:aws:lambda:eu-central-1:11111111:function:func".`

### Environment
Typescript, CDK 1.117.0 (also tried 1.103.0)

**Comment by JustinMiehle** [comment]
Oh wow, i completely missed that! I got confused by the type existing and would not have assumed it to be listed and have a note "Not currently supported by AWS CloudFormation."
I guess i´ll see if there´s an open Request for Cloudformation already, i can´t see it in their roadmap yet :( 
For now i guess we´ll do it after deploy with CDK to add the Lambda Config for the Custom Email Sender.
Thank you for the hint @caleron!

**Comment by nija-at** [comment]
Please re-open a feature request when support for this is added to CloudFormation.
