### ISSUE TITLE
(aws-backup): add support for EnableContinuousBackup in BackupPlanRule

### ISSUE THREAD

**Issue by wiget** [aws/aws-cdk#15922]
Please add support to specify `EnableContinuousBackup` when creating `BackupPlanRule`. EnableContinuousBackup was added to CloudFormation Resource specification v35.0.0

### Use Case

EnableContinuousBackup is required to have point-in-time recovery for RDS, when using only AWS Backup without automatic snapshots on RDS.

### Other
https://aws.amazon.com/blogs/storage/point-in-time-recovery-and-continuous-backup-for-amazon-rds-with-aws-backup/

Currently I'm using escape hatch, but it's fragile solution because it's depends on rules order.
```typescript
const cfBackupPlan = plan.node.defaultChild as backup.CfnBackupPlan;
cfBackupPlan.addPropertyOverride("BackupPlan.BackupPlanRule.0.EnableContinuousBackup", true);
```

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by BenChaimberg** [comment]
Pretty straightforward feature: add a `continuousBackup: boolean` prop to [BackupPlanRuleProps](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-backup/lib/rule.ts) and make the corresponding change in `BackupPlan.addRule` to transfer that to the CFN properties
https://github.com/aws/aws-cdk/blob/4ce318224453cebcf817b7683e5020780ab5df87/packages/%40aws-cdk/aws-backup/lib/plan.ts#L159-L170

I am unassigning myself and marking this issue as `p2`, which means that we are unable to work on this immediately.

We use +1s to help prioritize our work, and are happy to reevaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://join.slack.com/t/cdk-dev/shared_invite/zt-mso6p56d-qJp7SOTBvMaQuDrx7R2wHg) to solicit support for reprioritization.

Please feel free to work on this issue yourself and request my review if you submit a PR! See [CONTRIBUTING.md](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) for guidelines.
