### ISSUE TITLE
cdk diff not picking up differences if old/new value is in format x.y.z

### ISSUE THREAD

**Issue by johfer-bd** [aws/aws-cdk#15935]
"cdk diff" in the current version (1.117.0 / 2.0.0-rc.16) doesn't pick up differences if the old/new value has a number-like format but actually isn't a number (e.g. 0.31.1)

### What did you expect to happen?

I expected the differences are picked up and shown

### What actually happened?

I received "There are no differences"

### Environment

  - **CDK CLI Version  : 2.0.0-rc.16
  - **Node.js Version:** 14.17.0
  - **OS               :** MacOs
  - **Language (Version):** TypeScript (4.1.3)

**Comment by johfer-bd** [comment]
Ok, I looked into this and the culprit is this part in the `deepEqual` function that compares the old and new template:

https://github.com/aws/aws-cdk/blob/a04c017323130cb6f88a530e192e9e0e86fb137a/packages/%40aws-cdk/cloudformation-diff/lib/diff/util.ts#L27

```
// allows a numeric 10 and a literal "10" to be equivalent;
  // this is consistent with CloudFormation.
  if ((typeof lvalue === 'string' || typeof rvalue === 'string') &&
      safeParseFloat(lvalue) === safeParseFloat(rvalue)) {
    return true;
  }
````

In my case `lvalue` and `rvalue` are two version strings like "0.31.1-prod" and "0.31.2-prod" which are both parsed into "0.31" (and hence considered equal).

**Comment by johfer-bd** [comment]
I think this can be handled as edge case in `safeParseFloat` which already makes provisions for things like "0.0" but not for "0.1.something", or "1 something", or whatever is parsed by parseFloat into a (finite) number but actually isn't a number.

Also, the title of the issue should probably be changed to something like "cdk 2.x: cdk diff not picking up differences if old/new value have number-like format but are not numbers" but not sure if it's good practice to change issue titles after a posteriori? Please advise.

**Comment by vincent-turato** [comment]
I would like to submit a PR for this. Should be finished tomorrow.
