### ISSUE TITLE
(core): provide token-aware string manipulation functions

### ISSUE THREAD

**Issue by dz902** [aws/aws-cdk#15941]
I did this because I wanted my subnets to be named as `pub-a`, `pvt-b`, etc.

```typescript
 const azShortName = subnet.availabilityZone.replace(/.+([a-z])$/, '$1'); 

 cdk.Aspects.of(subnet).add(
    new cdk.Tag('Name', `${prefix}-${azShortName}`)
  )
```

However this did not work as availabilityZone is a token which is only known after stack creation.

### Proposed Solution

This has gone silently without errors or warnings. Would be nice to have a warning if someone tries to string-manipulate a token, as most users may not have the correct mental model to realize what went wrong.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
We would if we could. Unfortunately, this is hard to do in general.

What we should be doing instead though is to write a set of common string manipulation functions (like `String.replaceAll()`, or potentially `Fn.replaceAll()` with a special-case for concrete strings), which are token-aware (although those will never be able to do regexes). Repurposing ticket into that.
