### ISSUE TITLE
Delete resources associated with a test stage

### ISSUE THREAD

**Issue by collinarnett** [aws/aws-cdk#15940]
If I'm creating a testing stage for my application in another account, how would I go about deleting the resources associated with the testing stage?
```python
testing_stage = pipeline.add_application_stage(TestingStage(self, "testing"), env={
    "account": "",
    "region": "us-east-1",
})

# How can I delete test stage here?
testing_stage.destroy()

pipeline.add_application_stage(ProductionStage(self, "production"), env={
    "account": "",
    "region": "us-east-1",
})
  ```
  
  Researching the issue only leads answers associated with `cdk destroy` in the command line.

**Comment by peterwoodworth** [comment]
Hey @collinarnett,

You can create a [CloudFormationDeleteStackAction](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-codepipeline-actions.CloudFormationDeleteStackAction.html) and add this action to your testing stage with the [addActions](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_pipelines.CdkStage.html#addwbractionsactions) function.

```ts
testing_stage.addActions(new CloudFormationDeleteStackAction({
  actionProperties: actionProps,
  deploymentRole: role
}))
```

[Link to ActionProperties docs](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-codepipeline.ActionProperties.html)
