### ISSUE TITLE
(aws-cloudwatch) Support cross-account alarms

### ISSUE THREAD

**Issue by faizalsomani** [aws/aws-cdk#15959]
Amazon Cloudwatch just announced [cross account alarms](https://aws.amazon.com/about-aws/whats-new/2021/08/announcing-amazon-cloudwatch-cross-account-alarms/). Account Id can be added to the alarm using the GUI in AWS account. However, cdk does not support use of region and account id when creating the alarm. 

### Reproduction Steps

```
private var metricLine = Metric.Builder.create()
            .metricName("ConcurrentExecutions")
            .namespace("AWS/Lambda")
            .statistic("Maximum")
            .region(<REGION>)
            .account(<ACCOUNT_ID>)
            .build()

// The alarm created here will NOT be for <REGION> and <ACCOUNT_ID>, however it will be created for the account CFN is deployed in
private var alarmWidget = Alarm.Builder.create(scope,<NAME>)
                        .metric(metricLine)
                        .alarmName(<NAME>)
                        .threshold(<THRESHOLD>)
                        .evaluationPeriods(<EVALUATION_PERIOD>)
                        .build()
```

### What did you expect to happen?

Alarm should be created for the `<REGION>` and `<ACCOUNT_ID>` specified in `metricLine`.

### What actually happened?

Alarm created was for the account the CFN was deployed to.

--- 

This is :bug: Bug Report

**Comment by hongbodu** [comment]
+1. Please prioritize

**Comment by lagunex** [comment]
Region should not be included as part of this work. The new feature is only about Cross Account functionality. Not Cross Region.

**Comment by kaizen3031593** [comment]
Yep, I have been looking into this and will be adding cross-account functionality. I neglected to modify the title though.
