### ISSUE TITLE
aws-ecr-assets: too long image tag causes input image exceeds limitation

### ISSUE THREAD

**Issue by phuwin95** [aws/aws-cdk#15968]
Docker images generated by `DockerImageAsset` class from `@aws-cdk/aws-ecr-assets` have really long tags.
![image](https://user-images.githubusercontent.com/60187861/128831081-0217f139-3c41-4b54-8d13-5d8057fd43bb.png)
This causes Fargate Service generation (from `@aws-cdk/aws-ecs-patterns`) to fail because the input Image exceeds 255 characters

### Reproduction Steps
Since it needs lots of other inputs (vpc, loadBalancer, etc) I include what's in our code base:
```

    // Create application docker image
    const image = new DockerImageAsset(this, 'App', {
      directory: join(__dirname, '..', '..', '..'),
    });

    // Create a cluster
    const fargateCluster = new Cluster(this, 'FargateCluster', {
      vpc,
    });

    // Create Fargate Service
    const fargateService = new ApplicationLoadBalancedFargateService(this, 'FargateService', {
      cluster: fargateCluster,
      memoryLimitMiB: 512,
      cpu: 256,
      taskImageOptions: {
        image: ContainerImage.fromEcrRepository(image.repository.repositoryName, image.imageUri),
        environment: {
          ...appEnvVariables,
        },
        taskRole: role,
        executionRole: role,
        logDriver,
        containerPort: 80,
      },
      minHealthyPercent: 100,
      maxHealthyPercent: 200,
      loadBalancer: loadbalancer,
      publicLoadBalancer: !loadbalancer && true,
      assignPublicIp: true, // Required for the ECS/Fargate to have ECR pull access
      listenerPort: 80,
    });
```

### What did you expect to happen?

Fargate Service gets created without an error

### What actually happened?

Fargate Service failed to create.
```
Resource handler returned message: "Invalid request provided: Create TaskDefinition: Container.image should be 255 characters or less.
```

### Environment

  - **CDK CLI Version: 1.116.0**
  - **Framework Version: 1.116.0**
  - **Language (Version): TypeScript (~3.7.2)** 

### Other

Posted originally first in #2663. Then @eladb suggested creating a separate issue because this looks like a bug (https://github.com/aws/aws-cdk/issues/2663#issuecomment-895815258).

--- 

This is :bug: Bug Report

**Comment by eladb** [comment]
@phuwin95 thanks

**Comment by eladb** [comment]
@phuwin95 `image.imageUri` includes the full image URI, not just the tag. So the resulting `Image` of your code will have the repository portion duplicated and therefore exceeds the length limit (and is also incorrect).

Instead, you can use `fromDockerImageAsset()` or `fromAsset()` as described below.

Instead of:

```ts
image: ContainerImage.fromEcrRepository(image.repository.repositoryName, image.imageUri)
```

You should either use:

```ts
image: ContainerImage.fromDockerImageAsset(image)
```

Or:

```ts
image: ContainerImage.fromAsset(join(__dirname, '..', '..', '..'))
```

I am closing this for now. Let me know that this indeed works.

**Comment by phuwin95** [comment]
We tried this:
```
image: ContainerImage.fromDockerImageAsset(image)
```
And it works. 
Thank you.
