### ISSUE TITLE
(stepfunctions): StepFunctionsStartExecution triggers automatic inline policy generation

### ISSUE THREAD

**Issue by andreadisimone** [aws/aws-cdk#15969]
When creating a stepfunction with a StepFunctionsStartExecution task, an inline policy is automatically generated, which grants the role of the parent stepfunction execution rights on the child stepfunction.

This is very convenient when generating the role on the fly, but it should not happen when the user specifies a pre-existing role. I already added the relevant permissions to my role, I don't want anything else added to it.

I am actually forced to deploy from a role that does not even have that kind of IAM access, so this breaks my setup.

Another possible scenario where this breaks is if the role already has inline policies attached to it, with the total character size close to the 10240 characters limit. 

This tampering with externally generated roles should be avoided altogether. If you really want to keep this, please provide a switch to disable it, in case of deployments in environments with strictly controlled IAM access.

### Reproduction Steps
I don't think this requires particular steps to reproduce. It looks to me like this was intended as a feature, without considering the problems that arise in complex scenarios.
In any case, this code creates a parallel task, with two branches, each pointing to a pre-existing SFN in the environment. The top StateMachine is configured to run form a pre-existing role. After deployment, the role will have a new inline policy attached to it.

```
#!/usr/bin/env python3
from aws_cdk import (
    aws_stepfunctions as sfn, core,
    aws_ssm as _ssm,
    aws_stepfunctions_tasks as tasks,
    aws_iam as iam
)
import os
import logging
logging.basicConfig()

logger = logging.getLogger(__file__)
logger.setLevel(os.getenv('LOGLEVEL', 'INFO'))

class TestStack(core.Stack):

    def __init__(self, scope: core.Construct, id_: str, **kwargs) -> None:
        super().__init__(scope, id_, **kwargs)

        parallel_sfn = sfn.Parallel(self, "Execute training in parallel for all usecases")

        task = tasks.StepFunctionsStartExecution(self, f'simple1',
                                                 state_machine=sfn.StateMachine.from_state_machine_arn(self, 'simplesfn1', yourARN))
        parallel_sfn.branch(task)

        task2 = tasks.StepFunctionsStartExecution(self, f'simple2',
                                                 state_machine=sfn.StateMachine.from_state_machine_arn(self,
                                                                                                       'simplesfn2',
                                                                                                       'yourARN2'))
        parallel_sfn.branch(task2)

        role = iam.Role.from_role_arn(self, 'sfnrole', yourRoleARN)

        sfn.StateMachine(self, 'parallel', state_machine_name=f'parallel',
                         definition=parallel_sfn,
                         role=role
                         )

app = core.App(analytics_reporting=False)


test_stack = TestStack(
    app, "test-stack")


app.synth()


```

### What did you expect to happen?
If a user specifies a pre-existing role, CDK should trust them to have added all relevant permissions, rather than doing it itself.

### What actually happened?
CDK tried to add an inline policy to the preexisting role, resulting in an error, since in our setup IAM edits are strictly regulated.

### Environment

 - **CDK CLI Version  :**   - **Framework Version:** 1.117.0
  - **OS               :** linux
  - **Language (Version):** python

--- 

This is :bug: Bug Report

**Comment by BenChaimberg** [comment]
What you are suggesting runs contrary to the philosophy of the CDK, where we attempt to provide as many sensible defaults and take care of as many steps as possible for our users. In other words, we should not "trust [users] to have added all relevant permissions" but should rather add all the necessary permissions so users don't need to know about the specific permissions required to perform a desired task. If you would like to disable this behaviour, you should [re-import the role](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-iam.Role.html#static-fromwbrrolewbrarnscope-id-rolearn-options) and specify it as [immutable](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-iam.FromRoleArnOptions.html#mutable).
