### ISSUE TITLE
rds.DatabaseInstance: update CDK version from 1.59.0 -> 1.115.0 cause the replacement of RDS DB instance resource as property 'PubliclyAccessible' is added.

### ISSUE THREAD

**Issue by fanhongy** [aws/aws-cdk#15965]
Having an issue after updating the CDK version from 1.59.0 -> 1.115.0
Previously, we defined the vpc with public subnet only, a RDS DB instance was created in the VPC. Script like below:
```python
        vpc = ec2.Vpc(self, "vpc", 
            subnet_configuration = [
                ec2.SubnetConfiguration(name="Public", subnet_type=ec2.SubnetType.PUBLIC),
                # ec2.SubnetConfiguration(name="Private", subnet_type=ec2.SubnetType.PRIVATE)
                ]
            )

        instance = rds.DatabaseInstance(self, "Instance",
            engine=rds.DatabaseInstanceEngine.mysql(
                version=rds.MysqlEngineVersion.VER_8_0_19
            ),
            
            instance_type=ec2.InstanceType.of(ec2.InstanceClass.BURSTABLE3, ec2.InstanceSize.SMALL),
            vpc=vpc,
            credentials=rds.Credentials.from_secret(my_user_secret),
            license_model = rds.LicenseModel.GENERAL_PUBLIC_LICENSE
        )
```
However after updating the CDK to the most recent version, we found the RDS will be create in a private subnet if not specify a vpc_subnet parameter.
After adding the vpc_subnets = {"subnet_type": ec2.SubnetType.PUBLIC} to RDS DB instance construct, it automatically add PubliclyAccessible property to CFN template, and that is causing the replacement.

```python
        instance = rds.DatabaseInstance(self, "Instance",
            engine=rds.DatabaseInstanceEngine.mysql(
                version=rds.MysqlEngineVersion.VER_8_0_19
            ),
            
            instance_type=ec2.InstanceType.of(ec2.InstanceClass.BURSTABLE3, ec2.InstanceSize.SMALL),
            vpc=vpc,
            credentials=rds.Credentials.from_secret(my_user_secret),
            # publicly_accessible=False,
            # optional, defaults to m5.large
            vpc_subnets={
                 "subnet_type": ec2.SubnetType.PUBLIC
            },
            subnet_group = my_subnet_group,
            license_model = rds.LicenseModel.GENERAL_PUBLIC_LICENSE
        )
```

### Reproduction Steps
with below code, command `cdk synth` will generate the RDS DB instance with property `PubliclyAccessible`, as in previous version, this property doesn't present, add this property will cause the replacement. 

```python
from aws_cdk import core as cdk
import aws_cdk.aws_rds as rds
import aws_cdk.aws_ec2 as ec2 
import aws_cdk.aws_secretsmanager as secretsmanager

class RdsStack(cdk.Stack):

    def __init__(self, scope: cdk.Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)
        #vpc = ec2.Vpc(self, "vpc")
        vpc = ec2.Vpc(self, "vpc", 
            subnet_configuration = [
                ec2.SubnetConfiguration(name="Public", subnet_type=ec2.SubnetType.PUBLIC),
                ec2.SubnetConfiguration(name="Private", subnet_type=ec2.SubnetType.PRIVATE)
                ]
            )

        my_user_secret = rds.DatabaseSecret(self, "MyUserSecret",
            username="myuser",
            secret_name="my-user-secret" # optional, defaults to a CloudFormation-generated name
        )        
        my_subnet_group = rds.SubnetGroup(self, "RDSSubnetGroup",
            description = "my rds subnet public group",
            vpc = vpc,
            vpc_subnets = {
                "subnet_type": ec2.SubnetType.PUBLIC
            }
        )
        rds_instance = rds.DatabaseInstance(self, "Instance",
            engine=rds.DatabaseInstanceEngine.mysql(
                version=rds.MysqlEngineVersion.VER_8_0_19
            ),
            
            instance_type=ec2.InstanceType.of(ec2.InstanceClass.BURSTABLE3, ec2.InstanceSize.SMALL),
            vpc=vpc,
            credentials=rds.Credentials.from_secret(my_user_secret),
            # publicly_accessible=False,
            # optional, defaults to m5.large
            vpc_subnets={
                 "subnet_type": ec2.SubnetType.PUBLIC
            },
            subnet_group = my_subnet_group,
            license_model = rds.LicenseModel.GENERAL_PUBLIC_LICENSE
        )

```

### What did you expect to happen?

the update of CDK version should not affect critical resource, such as RDS DB instance, replaced.

### What actually happened?

The new version of CDK will try to add `PubliclyAccessible` as long as you set the `subnet_group` parameter in CDK.

### Workaround

```python
        # Add the following to remove the new property. 
        cfn_rds_instance = rds_instance.node.default_child
        cfn_rds_instance.add_property_deletion_override('PubliclyAccessible')
```

### Environment

  - **CDK CLI Version  :** 1.59.0 -> 1.115.0
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :** AL2 
  - **Language (Version):** Python (3.7.3)

--- 

This is :bug: Bug Report

**Comment by fanhongy** [comment]
Current workaround will be using escape hatch to remove the property: 
```python
cfn_rds_instance = rds_instance.node.default_child 
cfn_rds_instance.add_property_deletion_override('PubliclyAccessible')
```

This kind of issue will impact the critical resource. Please fix this with higher priority.

**Comment by njlynch** [comment]
> As you can see, the new code applies a default that the old code did not. The new code should (probably?) not be applying that default, the VPC class has its own defaults.
> njlynch changes this behavior in #10391. Looks to be an oversight, but who knows. Nick?

To be honest, I cannot recall why I decided to default to private subnets here. Likely a security mentality of private === more secure than public, combined with an ignorance of the fact that the VPC class providing its own defaults. Agreed that unfortunately changing it now would require a feature flag.

**Comment by njlynch** [comment]
> As you can see, the new code applies a default that the old code did not. The new code should (probably?) not be applying that default, the VPC class has its own defaults.
> njlynch changes this behavior in #10391. Looks to be an oversight, but who knows. Nick?

To be honest, I cannot recall why I decided to default to private subnets here. Likely a security mentality of private === more secure than public, combined with an ignorance of the fact that the VPC class providing its own defaults. Agreed that unfortunately changing it now would require a feature flag.

**Comment by BenChaimberg** [comment]
> In any case, @fanhongy, to unblock yourself you don't need to resort to overrides. You can just pass `publicly_accessible=False` to the constructor to switch it back off.

I think the reason an override was added is that CFN triggers an update if `PubliclyAccessible` goes from unset to set, regardless of whether the set state is the same as the default state.
