### ISSUE TITLE
pipeline: aws-cdk-lib v2.0.0-r16 for Java does not include the stable pipeline module 

### ISSUE THREAD

**Issue by niqo01** [aws/aws-cdk#15971]
When including the dependency "software.amazon.awscdk:aws-cdk-lib:2.0.0-rc.16" in my project I don't see any of the pipeline module classes (CdkPipeline, CodePipeline, ... from https://docs.aws.amazon.com/cdk/api/latest/docs/pipelines-readme.html)

### Reproduction Steps

1. Create Java project
2. Add "software.amazon.awscdk:aws-cdk-lib:2.0.0-rc.16" as a dependency
3. Notice that none of the stable classes from https://docs.aws.amazon.com/cdk/api/latest/docs/pipelines-readme.html are present

### What did you expect to happen?

I expect the stable pipeline module classes to be present

### Environment

  - **CDK CLI Version  : 2.0.0-rc.16 (build dba3421)
  - **Framework Version: software.amazon.awscdk:aws-cdk-lib:2.0.0-rc.16
  - **Node.js Version: v14.8.0
  - **OS               : Ubuntu 21.04
  - **Language (Version): Java 11

This is :bug: Bug Report

**Comment by nija-at** [comment]
It's available starting in rc.17. Can you check if that works?

**Comment by niqo01** [comment]
@nija-at Works great for me. Thanks.
