### ISSUE TITLE
(aws-cdk/aws-dynamodb): CDKMetadata update causing new dynamodb table creation

### ISSUE THREAD

**Issue by joboscribe** [aws/aws-cdk#15980]
Our stack currently includes a named table that we are not making any changes to via cdk but our deployments are failing with the following Status reason in the AWS Console:
```
The following resource(s) failed to create: [REDACTED TABLE NAME]. The following resource(s) failed to update: [CDKMetadata].
```
I understand that specifying the name for a table rather then letting CDK auto-generate one will cause problems when the table needs to be recreated, my question is why does a new table need to be created at all when we aren't specifying any changes to it? I suppose an alternative would be to let CDK generate a name for the table but then if we want to retain the existing data we would need to set up some porting of data from the old table to the new one, which we would rather avoid outside of extraordinary circumstances like adding a sorting key and not for something as uncontrollable (from our end) as updating the metadata.

### Reproduction Steps

1. create a stack that has a dynamodb table with a specific name
2. deploy the stack again in a way that changes the metadata, perhaps with a different version of CDK

### What did you expect to happen?

I would either expect the CDKMetadata to stay as-is, so as not to necessitate a new table, or perhaps update without needing to recreate the table (i realize that the later is perhaps not possible).

### What actually happened?

In my terminal i see:
```
REDACTED STACK NAME: creating CloudFormation changeset...
5:18:15 PM | CREATE_FAILED        | AWS::DynamoDB::Table            | REDACTED TABLE NAME
REDACTED TABLE NAME already exists
```
And in the Cloudformation console:
```
The following resource(s) failed to create: [REDACTED]. The following resource(s) failed to update: [CDKMetadata].
```

### Environment

  - **CDK CLI Version  : 1.90.0 (build 7edba31)
  - **Framework Version: 1.117.0
  - **Node.js Version: v14.15.5
  - **OS               : MacOS Catalina 10.15.7 (19H1217)
  - **Language (Version): TypeScript (3.8.3)

### Other
--- 
If this is not a bug but rather the exact behavior desired by the project maintainers then i would appreciate any suggestions on how we can navigate around this, i.e. keep our data around and have programmatic access to it.

This is :bug: Bug Report

**Comment by madeline-k** [comment]
HI @joboscribe! Can you please share a minimal stack example that repros this issue? and also share what change you are making to change the CDKMetadata? Which specific version did you upgrade from and to? 

I am not able to reproduce it with the following steps:
- deploy this stack containing only one resource with version 1.90:
```ts
export class ProdSampleAppStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    new dynamodb.Table(this, 'MyTable', {
      partitionKey: {
        name: 'myKey',
        type: dynamodb.AttributeType.STRING
      },
      tableName: 'MyTable',
    });
  }
}
```
- upgrade to version 1.117 
- `cdk diff` shows the the CDKMetadata resource did change. (Please note, this does not change with every version bump!)
- deploy stack again
- no errors

Changes to the CDKMetadata should have no impact on your Dynamodb table. You may want to pursue turning off the CDKMetadata to fix your issue. To do this, synthesize with this flag: `cdk --no-version-reporting synth`. See: https://docs.aws.amazon.com/cdk/latest/guide/cli.html
