### ISSUE TITLE
CDK Cloudfront DistributionVsCloudFrontWebDistribution Resources migration

### ISSUE THREAD

**Issue by dayyehm** [aws/aws-cdk#15998]
## :question: General Issue/Feature
Migrating cdk stack resource for cloudfront distribution that uses the old construct to a new one , the issue the distribution cannot be retained as cloudfront resource in CFN does not support importing existing resources.

Distribution construct allow import existing distribution but in this case distribution was created using the old construct 
 =============================
   const distribution = new cf.CloudFrontWebDistribution(this, `CloudFrontWebDistribution`, {
      defaultRootObject: props.maintenanceMode ? '/index.html' : '',
      loggingConfig: {
        bucket: new s3.Bucket(this, 'LogBucket', {
          bucketName: this.stackName,
          lifecycleRules: [
            {
              enabled: true,
              expiration: cdk.Duration.days(30),
            },
          ],
        }),
        includeCookies: false,
      },
        {

    });
=================================
Seems the only the new construct distribution will allow RemovalPolicy : retain , and allow importing an existing distribution! 
https://github.com/aws/aws-cdk/issues/5607
The use case in order to implement Brotli compression on cloudfront that needed to use the new distribution construct.

This possible to require some feature to allow recognition of resources with different specification , I'm not sure if there's a way to retain the existing distribution as it does not seem to support

https://stackoverflow.com/questions/65933693/when-to-use-aws-cloudfrontwebdistribution-and-when-to-use-aws-cloudfront-distrib

**Comment by cbromberg** [comment]
Hi - I think I have the same question. Both constructs exist, but how do I migrate from CloudFrontWebdistribution to Distribution without losing the identity of the distribution https://stackoverflow.com/questions/68744098/migrate-a-cdk-managed-cloudformation-distribution-from-the-cloudfrontwebdistribu

**Comment by cbromberg** [comment]
I learned at my question on so https://stackoverflow.com/questions/68744098/migrate-a-cdk-managed-cloudformation-distribution-from-the-cloudfrontwebdistribu that this is pretty easy to solve - you need some knowledge of the deployed stack (the logical ID of the distribution)

**Comment by njlynch** [comment]
The linked StackOverflow answer is correct; the simplest way to go about this is to override the logical ID of the new `Distribution` to match the old logical ID of the `CloudFrontWebDistribution`:

```ts
distrubtion.node.defaultChild.overrideLogicalId('OldCFWDLogicalIdGoesHere');
```

Closing this out. Feel free to comment and mention me with any follow-ups!
