### ISSUE TITLE
(cloudfront): Description of CacheHeaderBehavior.behavior is unintelligible

### ISSUE THREAD

**Issue by ffxsam** [aws/aws-cdk#16002]
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cloudfront.CacheHeaderBehavior.html#behavior

> If the no headers will be passed, or an allow list of headers.

Not sure what this is trying to say, but I also noticed the value is a magic string, which isn't good. What are the possible values for this property?

---

This is a 📕 documentation issue

**Comment by njlynch** [comment]
The comment should read:

> If ~the~ no headers will be passed, or an allow list of headers.

Either way, you shouldn't be (and can't!) setting this value yourself. Instead, use the factory methods on the class (`allowList` or `none`) to set the proper value. 

```
CacheHeaderBehavior.none(); // no headers
CacheHeaderBehavior.allowList('MyHeader1', 'Header2');
```

I opened #16067 to fix the typo.
