### ISSUE TITLE
(core): use Aws.STACK_NAME for generated export names

### ISSUE THREAD

**Issue by mschenke** [aws/aws-cdk#16006]
I think it would be best to change the logic for generated stack export names to use Aws.STACK_NAME instead of stack.stackName

### Use Case

CDK can be used to generate templates vs generate and deploy.  In the case where templates are generated for general use this change will ensure the stacks can be deployed multiple times within the same account with different paramters.  This should not break anything for existing stacks deployed with CDK as stackName will match the deployment time StackName ref.

### Proposed Solution

Use Aws.STACK_NAME

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by mschenke** [comment]
Actually, imports keys from other stacks won't be known.  This might be useful for standalone stacks but can't be used when there are interstack dependencies.  Post processing template might be only option.

**Comment by rix0rrr** [comment]
Exactly.
