### ISSUE TITLE
aws-route53: error in function definition for TxtRecord

### ISSUE THREAD

**Issue by kidbrax** [aws/aws-cdk#16010]
At https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_route53/TxtRecord.html, it says there are only 3 named arguments when there should be 5.

More importantly, where can I contribute these fixes? I read the contributing guide and it points to examples in the READMEs but I can't find where to make changes that would update this page. Can you point me to the exact file that would update this page? Then I might see the pattern and be able to fix others as well.

---

This is a 📕 documentation issue

**Comment by peterwoodworth** [comment]
Everything looks good to me too. @kidbrax ping me if you can elaborate on this issue :)
