### ISSUE TITLE
(lambda): Vague documentation for LayerVersion#addPermission

### ISSUE THREAD

**Issue by ffxsam** [aws/aws-cdk#16012]
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-lambda.LayerVersion.html#addwbrpermissionid-permission

`id` parameter is not explained at all. What is this for, and what are valid values?

According to AWS support, the ARN of the layer you want to access goes there. I would've never guessed that from the docs.

---

This is a 📕 documentation issue

**Comment by nija-at** [comment]
Apologies for the poor docs there. Until we fix our docs, the `id` is the same as documented here - https://docs.aws.amazon.com/cdk/latest/guide/constructs.html#constructs_init

**Comment by ffxsam** [comment]
Apologies! Seems like the AWS support rep misspoke, then. Thanks, Niranjan.
