### ISSUE TITLE
(aws-secretsmanager): Imported key's `encryption_key` attribute is empty

### ISSUE THREAD

**Issue by npvisual** [aws/aws-cdk#16022]
An imported key's `encryption_key` attribute doesn't seem to be populated. This is somewhat of an issue when trying to assign read grants to the imported secret since the encryption key (CMK) also needs to a "Decrypt" permission.

### Reproduction Steps

We import a Secret from a given ARN and then try to set a decrypt grant on that secret's key by using the `encryption_key` : 

```python
        shared_db_secret = secrets.Secret.from_secret_arn(
            self,
            "shared-db-secret",
            secret_arn=secret_arn,
        )

        shared_db_secret.encryption_key.grant_decrypt(lambda_container.grant_principal)
```

### What did you expect to happen?

I would have actually expected for the `encryption_key` to provide a reference to the CMK used to encrypt that imported secret.

### What actually happened?

We got the following error : 

```
Traceback (most recent call last):
  File "/codepath/furley/tenant.py", line 34, in <module>
    Silo(
  File "/path/furley-0NV7C4_t-py3.9/lib/python3.9/site-packages/jsii/_runtime.py", line 83, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/codepath/furley/silo/silo.py", line 62, in __init__
    TripperComponents(
  File "/path/furley-0NV7C4_t-py3.9/lib/python3.9/site-packages/jsii/_runtime.py", line 83, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/codepath/furley/silo/app_components.py", line 80, in __init__
    function = TripperLambda(
  File "/path/furley-0NV7C4_t-py3.9/lib/python3.9/site-packages/jsii/_runtime.py", line 83, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/codepath/furley/silo/app_lambda.py", line 136, in __init__
    shared_database_secret.encryption_key.grant_decrypt(lambda_app.grant_principal)
AttributeError: 'NoneType' object has no attribute 'grant_decrypt'
Subprocess exited with error 1
```

### Environment

  - **CDK CLI Version  :** 1.117.0 (build 0047c98)
  - **Framework Version:** 1.117.0
  - **Node.js Version:** v15.8.0
  - **OS               :** macOs 11.4 (20F71)
  - **Language (Version):** Python 3.9.5

### Other

--- 

This is :bug: Bug Report

**Comment by njlynch** [comment]
Hi @npvisual ,

If you need access to the encryption_key as well, the correct method to use is the [`from_secret_attributes`](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_secretsmanager/Secret.html#aws_cdk.aws_secretsmanager.Secret.from_secret_attributes) method, which allows you to specify both the secret ARN and encryption key.

Note that this isn't a [content lookup](https://docs.aws.amazon.com/cdk/latest/guide/context.html) method; that is, it won't automatically read the encryption key from secrets manager. You'll need to provide both values yourself.

If you're looking to track the work to automatically look up the key from the secret, that's being tracked here: #1689.

Hope that helps! Feel free to comment and mention me if you have any follow-ups.
