### ISSUE TITLE
(aws-ecs-patterns): Unable to specify command on ScheduledFargateTask

### ISSUE THREAD

**Issue by ltamrazov** [aws/aws-cdk#16024]
### The Question
Currently the `ScheduledFargateTask` takes either `imageOptions` to create a new task definition or `taskDefinition` to specify an existing one. However, if using `taskDefinition` parameter, its impossible to specify a `command` for the docker image. Our use case is we have a task definition that we want to schedule on a weekly and daily cadence with different commands. Its the same image, and same definition, but we want to use different commands for different schedules. Is this possible with the out of the box pattern?

While the `imageOptions` parameter lets us specify the command, we cannot use it with our flow because we need to reference a `task family` in our CI and also provide other task definition options such as execution role.

### Environment

  - **CDK CLI Version:** 1.17.0
  - **Module Version:** 1.17.0
  - **Node.js Version:** 14.14
  - **OS:** OSX: Linux w/ Docker Alpine
  - **Language (Version):** Typescript

**Comment by ltamrazov** [comment]
My work around for now is something like:

```typescript
        const ecsTarget = new eventTargets.EcsTask({
            taskDefinition,
            cluster: props.cluster,
            role: this.taskExecutionRole,
            containerOverrides: [{
                command: ['w.e.'],
                containerName,
            }],
        });

        const rule = new events.Rule(this, 'scheduledDailyStuff', {
            schedule: events.Schedule.cron({
                minute: '0',
                hour: '0',
            }),
        });

        rule.addTarget(ecsTarget);
    }
```

`containerOverides` is what seems to be missing from the `ScheduledFargateTask` module.

**Comment by peterwoodworth** [comment]
You can use the [`FargateTaskDefinition.addContainer`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs.FargateTaskDefinition.html#addwbrcontainerid-props) method to add a container which allows you to specify [`command`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs.CfnTaskDefinition.ContainerDefinitionProperty.html#command). Does this help you out?

**Comment by ltamrazov** [comment]
> You can use the FargateTaskDefinition.addContainer() method to add a container to your task definition which allows you to specify command. Does this help you out?

@peterwoodworth I'm sorry I missed your reply. This does not fit the use case because this still requires us to specify multiple containers on the same task definition (if we wanted to run multiple commands). Further more, the `ScheduledFargateTask` construct does not allow specifying which container should be run (if we had multiple containers specified). So we still would not be able to use this for running the same task on different schedules with a different command.

Ideally we can specify the command that the underlying `rule` passes to ECS.
