### ISSUE TITLE
(cdk-cli): "*" option to deploy all stacks does not work 

### ISSUE THREAD

**Issue by ikhvostenkov** [aws/aws-cdk#16023]
When executing _cdk_ stacks deployment using npx with _"*"_ option to deploy all stacks, command returns _0_, completed successfully without actually executing anything. Option ```--all``` works correctly.

### Reproduction Steps
Having multiple stacks deployment written with TS. Execute:
```npx cdk -a cdk.out/assembly-Dev --profile my-profile --require-approval never --toolkit-stack-name my-stack-name deploy *```
### What did you expect to happen?
Successful deployment of all stacks included in _cdk_ code.

### What actually happened?
Command exits successfully without starting any deployments.

### Environment

  - **CDK CLI Version  :** 1.115.0
  - **Framework Version:**
  - **Node.js Version:** v12.22.5
  - **OS               :** macOS BigSur
  - **Language (Version):** TS 3.9.7

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
It could be that your stacks are all nested inside other constructs. Try `**`.

**Comment by ikhvostenkov** [comment]
@rix0rrr Thanks for getting back, your solution fixes the problem. Could be closed 👍
