### ISSUE TITLE
(ECS): ability to add SystemControls to Container Definition

### ISSUE THREAD

**Issue by Mayhem93** [aws/aws-cdk#16025]
### The Question

Hello, So I realized that the non-Cfn construct for the ContainerDefinition doesn't have a way to add SystemControls [(SystemControls)](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-systemcontrol.html) to it.

But it is available through `ecs.CfnTaskDefinition.ContainerDefinitionProperty`. Now, I'm mixing Cfn* classes with non-Cfn* classes and it could get a bit messy. I'll be posting my code here and maybe someone already went through this and help me out. 

**ALSO** is there way I can directly access arbitrary properties on resources? I was thinking of adding that SystemControls manually, but I couldn't find the way.

Thanks.

### Environment

  - **CDK CLI Version:** 1.118.0 (build a4f0418)
  - **Module Version:** "@aws-cdk/aws-ecs": "^1.118.0"
  - **Node.js Version:** v14.16.1
  - **OS:** all (Windows 10)
  - **Language (Version):** nodejs v14.16.1

### Other information
```javascript
const cloudwatchLog = new ecs.AwsLogDriver({
	logRetention: awsLogs.RetentionDays.ONE_WEEK,
	streamPrefix: 'activity-service-websockets-fargate-task'
});

const taskExecRole = new iam.Role(this, 'activity-service-task-exec-role', {
	roleName: 'activity-service-task-exec-role',
	assumedBy: new iam.ServicePrincipal('ecs-tasks.amazonaws.com'),
	managedPolicies: [
		iam.ManagedPolicy.fromAwsManagedPolicyName('AmazonSSMFullAccess'),
		iam.ManagedPolicy.fromAwsManagedPolicyName('CloudWatchFullAccess')
	]
});

const taskDefinition = new ecs.CfnTaskDefinition(this, 'pula mea', {
	cpu: config.Environment === 'live' ? 2048 : 512,
	memory: config.Environment === 'live' ? 4096 : 1024,
	taskRoleArn: taskExecRole.roleArn
});

const dockerContainerDef = new ecs.ContainerDefinition(this, 'activity-service-websockets-container', { // this doesn't work
	image: new ecs.AssetImage('./docker'),
	logging: cloudwatchLog,
	environment: {
		LARGE_SCALE_TEST: '1'
	},
	privileged: true,
	taskDefinition // because this is of the Cfn* flavor
});

const cfnDockerContainerDef = dockerContainerDef.renderContainerDefinition();

taskDefinition.containerDefinitions = [ cfnDockerContainerDef ];
cfnDockerContainerDef.systemControls = [
	{
		namespace: 'net.ipv4.tcp_tw_reuse',
		value: '1'
	},
	{
		namespace: 'net.ipv4.tcp_tw_recycle',
		value: '1'
	},
	{
		namespace: 'net.ipv4.tcp_fin_timeout',
		value: '60'
	}
];
```

**Comment by peterwoodworth** [comment]
Hey @Mayhem93,

You won't want to use L1 constructs with L2 constructs. According to our [docs](https://docs.aws.amazon.com/cdk/latest/guide/constructs.html#constructs_l1_using):

> You can't use L2 property types with L1 constructs, or vice versa. When working with L1 constructs, always use the types defined inside the L1 construct you're using. Do not use types from other L1 constructs (some may have the same name, but they are not the same type).

The thing you're looking for is [escape hatches](https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html). You can modify the underlying resource's properties directly and not have to worry about using the L1 constructs.

**Comment by Mayhem93** [comment]
I'll use `construct.node.defaultChild.addOverride` on the container definition.

Thanks.

**Comment by Mayhem93** [comment]
Unfortunately `ecs.ContainerDefinition` doesn't have `node.defaultChild` (it's undefined) :(

**Comment by peterwoodworth** [comment]
@Mayhem93 let me know if this helps you out

**Comment by Mayhem93** [comment]
Hello, I just tried your suggestion but I'm having an issue, I'll post my screenshot here (I've modified cdk.ps1 to add --inspect-brk to node so I can easily debug it)

![image](https://user-images.githubusercontent.com/705289/129782897-be0295a9-b899-4307-9943-cc7459a0e619.png)

Looks like `taskDefinition.node.defaultChild.containerDefinitions[0]` is undefined and I'm not sure what the `x` property/index is that you're referring to.

**Comment by peterwoodworth** [comment]
When you use escape hatches you have to make sure that you cast the default child to the correct class. In this case, thats CfnTaskDefinition.

`const cfnTaskDef = taskDef.node.defaultChild as CfnTaskDefinition`

However... that won't help here. I didn't realize that containerDefinitions is a [Lazy Value](https://docs.aws.amazon.com/cdk/latest/guide/tokens.html#tokens_lazy), which means we can't use escape hatches to modify the properties that aren't exposed to our L2 constructs.

I'll research this more tomorrow

**Comment by peterwoodworth** [comment]
Also, the `CfnTaskDefinition.containerDefinitions` prop is an array of `ContainerDefinitionProperty`. When you use escape hatches with properties that are arrays with values known at creation time, you will want to access the specific element you want to modify. I just put `x` there as a placeholder

**Comment by Mayhem93** [comment]
> When you use escape hatches you have to make sure that you cast the default child to the correct class. In this case, thats CfnTaskDefinition.
> 
> `const cfnTaskDef = taskDef.node.defaultChild as CfnTaskDefinition`
> 

I'm not using typescript, just plain javascript

**Comment by peterwoodworth** [comment]
I've converted this into a feature request. I've been unable to find a workaround for this using L2 resources. 

@Mayhem93 do you need any help with getting this to run still? Instead of using the higher level ContainerDefinition constructs, you'll need to configure that manually in the `CfnTaskDefinition`

**Comment by schuberttobias** [comment]
@peterwoodworth Can you give an estimated date for a CDK CLI release including #16970?

This is currently blocking us from moving workloads to AWS ECS with EC2 launch type.

**Comment by peterwoodworth** [comment]
Thanks for bringing my attention to this @schuberttobias 

it's been approved and should merge soon, so it should be out on the next CDK release
