### ISSUE TITLE
Auto Scaling: support associatePublicIpAddress in Launch Configuration

### ISSUE THREAD

**Issue by mifisignal** [aws/aws-cdk#1603]
I can't seem to figure out how to set the `associatePublicIpAddress` value in the Launch Configuration associated with an Auto Scaling Group.  If it's not currently settable, we should add a way to set it.  

(Currently, Auto Scaling Group instances only receive an public IP address if the subnet they're placed in has the AssociatePublicIPAddress flag enabled.)

**Comment by rix0rrr** [comment]
Does specifying public subnets in `vpcPlacement` not work?

**Comment by otterley** [comment]
@rix0rrr Only if the subnet has the AssociatePublicIPAddress property set to true.  Not all public subnets do, for safety reasons.
