### ISSUE TITLE
(step-functions): Callback sendTaskFailure is not stopping parallel branches

### ISSUE THREAD

**Issue by desoss** [aws/aws-cdk#16033]
According to the documentation of a **Parallel** state If any branch fails, because of an unhandled error or by transitioning to a Fail state, the entire **Parallel** state is considered to have failed and all its branches are stopped. 

Nevertheless, the behaviour generate by a _sendTaskFailure_ is different from the one generated a **Fail** state.

### Reproduction Steps

Create a parallel state, with some parallel branches, define a callback. Wrap the parallel state into another parallel state and catch a `customCatchedError` in the outer parallel state. Send a taskFailure with the catched `customCatchedError`. 

### What did you expect to happen?

The behaviour that I expect is that the internal parallel branches are stopped.

### What actually happened?

What is happening is that all the parallel branches seems to be in in progress.

### Other

In the picture below the step _Wait For `Accept` or `Reject` or `Annul` signal_ is a _waitForTaskToken_ step.  
The _Reject automatically_ step has a lambda invoke that is performing a _sendTaskFailure_.
<img width="657" alt="image" src="https://user-images.githubusercontent.com/10620399/129319483-aea376cf-5732-4a49-b578-b88e84a41caf.png">

As you can see in the picture, the parallel state is wrapped in another parallel state which is catching the error raised by the _sendTaskFailure_. None of the branches seems to be stopped and also the internal parallel step is still in progress.

Nevertheless, if I do something similar catching the error in the callback state and re-throwing it in a **Fail** step, some branches are stopped and the internal parallel step is in a cancel status.
<img width="456" alt="image" src="https://user-images.githubusercontent.com/10620399/129320666-a4b8f019-5519-4fcd-9872-1e7a2df0f0d4.png">

--- 

This is :bug: Bug Report

**Comment by BenChaimberg** [comment]
Unless I'm missing something, this doesn't seem to be a CDK issue, rather a possible issue with the Step Functions service itself. If I have misunderstood, can you please add more detail about what CDK is doing wrong here?

**Comment by desoss** [comment]
I totally confirm this is a step function issue.
