### ISSUE TITLE
(pipelines): expose asset introspection in convenient API

### ISSUE THREAD

**Issue by markusl** [aws/aws-cdk#16032]
We have a corporate requirement for security scanning all ECR images before deployments. To make this as easy as possible for the development teams we have published a CDK construct to do this with the "legacy pipelines".

With the legacy pipelines we use the pipeline API to see which images are being built in `DockerImage` stages and then append custom image scanning actions in the pipeline.

The custom commands are something like this. We use the manifest file to identify the image and then execute the scanner:

```ts
            `aws ecr get-login-password --region eu-central-1 | docker login --username AWS  --password-stdin ${registry-url}`,
            `export CONTAINER_IMAGE=$(cat ${manifestFilePath} | jq -r '.dockerImages[].destinations."${targetAccount}-eu-central-1" | "\\(.repositoryName):\\(.imageTag)"')`,
            `docker pull  ${registry-url}/\${CONTAINER_IMAGE}`,
            `security-scanner [parameters] " ${registry-url}/\${CONTAINER_IMAGE}"`,
```

With the new API it seems that iterating over the `pipeline.waves` does not allow access to the docker image asset information. 

### Proposed API

Ideally, we should be able to achieve the required functionality with an API like this where `dockerAsset` would enable easy access to the image details

```ts

  pipeline.dockerAssets.forEach((dockerAsset) => {
    pipeline.waves.find('Assets')?.addPost(new CustomDockerAssetSecurityScan(scope, dockerAsset, ...));
  });
```
### Environment

  - **CDK CLI Version:** 2.0.0-rc.17 (build fb5dc58)
  - **Module Version:** 2.0.0-rc.17 (build fb5dc58)
  - **Node.js Version:** 14
  - **OS:** all
  - **Language (Version):** TypeScript

**Comment by rix0rrr** [comment]
You could do it inside the asset build by adding commands to the buildspec using `partialBuildSpec`: add commands to `post_build` ?

**Comment by markusl** [comment]
@rix0rrr is there an API for the pipeline that can be used to alter the buildspecs of the assets that have been added to the pipeline?

What we would like to do instead of delivering a bunch of buildspec commands, KMS, and SSM references to dozens of dev teams maintaining container applications, we would like to be able to say "Install this CDK construct as NPM package and use `CustomDockerAssetSecurityScan` construct in your pipeline setup to make it just work".

**Comment by markusl** [comment]
@peterwoodworth @rix0rrr do you have any ideas on how to proceed with this?

Generally, what we would need to do is to be able to get a reference to the ECR image(s) published in the Assets stage and append a security scan stage to the pipeline before any deployments happen. 

With the legacy pipelines we used code similar to this, packaged as a CDK Construct:

```ts
  const dockerActions = assetsStage?.actions.filter((action) => action.actionProperties.actionName.startsWith('Docker')) as pipelines.PublishAssetsAction[];

  const securityScans =
    targetAccounts.map((targetAccount) =>
      dockerActions.filter((action) => includesTargetAccount(action, targetAccount)).map((action) => {
        const manifestFilePath = getAssetManifestFilePath(action, targetAccount);
        const project = createSecurityScan(scope, vpc, targetAccount, manifestFilePath, ...);

        if (!action.actionProperties.inputs || !action.actionProperties.inputs[0]) {
          throw new Error('Could not find artifact from action properties');
        }

        return new codepipeline_actions.CodeBuildAction({
          actionName: `SecurityScan-${targetAccount}`,
          project,
          input: action.actionProperties.inputs[0],
          role: action.actionProperties.role,
          runOrder: 2,
        });
      }));



```

**Comment by rix0rrr** [comment]
Right. The way to achieve this is to go spelunking in the Cloud Assembly.

When you add your stage to the pipeline, you can call `stage.synth()` to get the stage's cloud assembly. You can use the methods on that object to inspect it.

There will be artifacts in there, some of which are `AssetManifestArtifact`s. You can read those, and figure out the container image assets that are in the application, and add your appropiate codebuild actions as desired.

Refs:

- https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/pipelines/lib/private/cloud-assembly-internals.ts
- https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/pipelines/lib/private/asset-manifest.ts
