### ISSUE TITLE
EC2: The deployment of a stack will be cancelled/broken due to the duration/timeout of the creation of a CfnVPNConnection

### ISSUE THREAD

**Issue by ttais2017** [aws/aws-cdk#16030]
The creation of a SiteToSite VPN takes normally 'long' time until it gets the state 'available'.  Using the CDK API and the class CfnVPNConnection, the creation of a SiteToSite takes also a long time. This causes that the deployment of the related stack will be cancelled/broken.

### Reproduction Steps

    // --- site to site VPN resources
    VpnGateway vpg = VpnGateway.Builder.create(this,"vpg")
        .type("ipsec.1")
        .build();

    CfnVPCGatewayAttachment attachment = CfnVPCGatewayAttachment.Builder.create(this, "vpgatt")
        .vpcId(vpc.getVpcId())
        .vpnGatewayId(vpg.getGatewayId())
        .build();

    String cgIp = (String)getNestedStackParent().getNode().tryGetContext("cgIp");
    CfnCustomerGateway cg = CfnCustomerGateway.Builder.create(this, "cg")
        .ipAddress(cgIp)
        .bgpAsn(65000)
        .type("ipsec.1")
        .build();

    CfnVPNConnection.Builder.create(this, "s2s")
        .customerGatewayId(cg.getLogicalId())
        .vpnGatewayId(vpg.getGatewayId())
        .type("ipsec.1")
        .build()
        ;

    // ---

### What did you expect to happen?

The SiteToSite VPN should be created in state 'pending'

### What actually happened?

The Deployment of the Stack which is creating the VPN will be cancelled/broken and will be rolled back. I assume, because after 
a 'timeout' the VPNState is still in 'pending' state and not 'available'.

### Environment

  - **CDK CLI Version: **  1.118.0 (build a4f0418)
  - **Framework Version:**  aws-cli/2.2.18 Python/3.8.8 Windows/10 exe/AMD64 prompt/off
 
--- 

This is :bug: Bug Report

**Comment by njlynch** [comment]
Thanks for the bug report.

In this case, it sounds like something during the CloudFormation deployment is preventing the VPNConnection from establishing the connection. In these cases, I believe looking at the CloudWatch logs would be the best way to gain additional insight. Are there any specific errors in the CloudFormation deployment? Any logs in CloudWatch that point to why it is taking so long to establish the connection? As you're using the "raw" L1/Cfn resources, it is unlikely there's much that can be done from the CDK side to fix this; you would receive the same issue when deploying a CloudFormation template with the same values. However, looking into the logs might provide you with some ideas of why the connection isn't being established.

**Comment by ttais2017** [comment]
Dear Nick, 
thx for your reply. 
The VPN Connection will be created, if I use the AWS Console. It just takes long time to be there (what it's ok).  So if check the Cloud Watch Logs I will not find any issue regarding the VPN, because it was created.  

The issue appears when I'm deploying the Stack with CDK/Cloud Formation.  Due to the creation of the VPN takes (normally looong time) the deployment of the stack will be broken and the whole deployment will be rolled back.   So if I check the logs in Cloud Watch I found, the VPN Object could not be created  (but it's because for sure the first status reported by the creation of the VPN is "pending".  Note here tha the VPN needs long time for getting "available"... in such situation, the deployment was already rolled back.  :\

**Comment by peterwoodworth** [comment]
Hey @ttais2017,

Have you reached out to the CloudFormation team about this issue? Like Nick said, since you're using CfnResources, this error would still be occurring when deploying the same stack just with cloudformation, so there's not much we can do on our end here.

What evidence do you have that the error is because the vpn is `pending` rather than `available`?

**Comment by ttais2017** [comment]
Hi Peter, 
thx for your point of view.  I dont have any other evidence that's the reason (pending/available).  It was the result of my observations creating the same stack manually and with CDK.

I think it's a good idea to contact the CF team. !

KR,
