### ISSUE TITLE
EC2:  The SiteToSite VPN does not allow the use of an elastic IP address 

### ISSUE THREAD

**Issue by ttais2017** [aws/aws-cdk#16031]
The Tunnel Details of a SiteToSiteVPN should allow the use of elastic IP Addresses.  Currently the both tunnel objects are using "Outside IP Address" provided automatic by AWS.

### Use Case

The customer had already configured manually a SiteToSite VPN with AWS.  Its gateway was so configured with the IP Address of the Tunnel 1 of the Site2Site. The VPN is active.    

Now, the customer wants to keep the same SiteToSite VPN Configuration on Premises.  They want a CDK-based Stack with a SiteToSite VPN.  The Outside IP Addresses of the Tunneling within the CfnVPNConnection might be provided (for instance an elastic IP).
 

### Proposed Solution

The Class CfnVPNConnection should provide a method to give the details of the Tunneling Objects (specially the Outside IP Address)

---

This is a :rocket: Feature Request

**Comment by njlynch** [comment]
> The Class CfnVPNConnection should provide a method to give the details of the Tunneling Objects (specially the Outside IP Address)

I'm not sure what you're proposing here.

[CfnVPNConnection](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ec2.CfnVPNConnection.html) provides the `vpnTunnelOptionsSpecifications` property, which is an array of [`VpnTunnelOptionsSpecificationProperty`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ec2.CfnVPNConnection.VpnTunnelOptionsSpecificationProperty.html). This is equivalent to the [same structure](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-vpnconnection-vpntunneloptionsspecification.html) in CloudFormation.

I see several more options listed here: https://docs.aws.amazon.com/vpn/latest/s2svpn/VPNTunnels.html. Is it one of these options that you're looking to set (e.g., Local IPv4 Network CIDR, Remote IPv4 Network CIDR)? If so, then this will require work from CloudFormation to support. We can keep this issue open for tracking purposes, but I think https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/429 is the better issue to track progress.
