### ISSUE TITLE
(core): CfnJson fails not parse token that is properly formatted JSON

### ISSUE THREAD

**Issue by bravogolfgolf** [aws/aws-cdk#16059]
CfnJson fails not parse token that is properly formatted JSON

### Reproduction Steps

import * as cdk from '@aws-cdk/core';
import * as sm from '@aws-cdk/aws-secretsmanager'
import * as cr from "@aws-cdk/custom-resources";
import * as iam from '@aws-cdk/aws-iam';

export class CfnJsonIssueStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const secret = new sm.Secret(this, 'cfn-json-issue-secret',{
      secretName: 'secretName',
      generateSecretString:{
        secretStringTemplate: JSON.stringify({keyName: 'cfn-json-issue-secret'}),
        generateStringKey: 'randomText',
      },
    });

    const secretPartialArn = this.formatArn({
      account: this.account,
      region: this.region,
      resource: 'secret',
      resourceName: secret.secretName,
      service: 'secretsmanager'
    });

    const role = new iam.Role(this, 'cfn-json-issue-secret-role',{
      assumedBy: new iam.AccountPrincipal(this.account)
    })
    const policyStatement = new iam.PolicyStatement();
    policyStatement.addActions('secretsmanager:GetSecretValue')
    policyStatement.addAllResources();
    role.addToPolicy(policyStatement);

    const awsCustomResource = new cr.AwsCustomResource(this, 'cfn-json-issue-secret-lookup', {
      onUpdate: {
        service: 'SecretsManager',
        action: 'getSecretValue',
        parameters: {
          SecretId: secret.secretName
        },
        assumedRoleArn: role.roleArn,
        region: this.region,
        physicalResourceId: cr.PhysicalResourceId.of(Date.now().toString())
      },
      policy: cr.AwsCustomResourcePolicy.fromSdkCalls({resources: [secretPartialArn]})
    });

    const secretString = awsCustomResource.getResponseField('SecretString');
    new cdk.CfnJson(this, 'cfn-json', {
      value: secretString,
    });
  }
}

### What did you expect to happen?

I expect CfnJson to parse the string.

### What actually happened?

When deploying stack:

Received response status [FAILED] from custom resource. Message returned: SyntaxError: Unexpected token r in JSON at position 3
at JSON.parse (<anonymous>)
at cfnJsonHandler (/var/task/index.js:21:25)

### Environment

  - **CDK CLI Version  : 1.118.0 (build a4f0418)**
  - **Framework Version: ? **
  - **Node.js Version: v14.16.0 **
  - **OS               : macOS Big Sur 11.5.2 (20G95)**
  - **Language (Version): TypeScript (3.9.7)**

### Other

I'm using Secret instead of StringParameter to get around StringParameter's account/region limitation. In the sample above the Value of key 'keyName' is something that I would normally store in a StringParameter, if it did not have account/region limitation.

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
`CfnJson` doesn't parse a JSON string, it produces a JSON string. 

You probably want to write a custom resource for this.
