### ISSUE TITLE
(custom-resources): custom resource doesn't have proper permissions when kinesisanalyticsv2 is used with fromSdkCalls

### ISSUE THREAD

**Issue by i05nagai** [aws/aws-cdk#16053]
When `kinesisanalyticsv2` is specified in `service` parameter with `AwsCustomResourcePolicy.fromSdkCalls`, the actions in the role have permissions prefixed with `kinesisanalyticsv2` instead of `kinesisanalytics`. The stack creation fails due to a lack of permissions.

### Reproduction Steps

```ts
import * as cr from '@aws-cdk/custom-resources';
import * as cdk from '@aws-cdk/core';

export class Exmaple1Stack extends cdk.Stack {
  constructor(scope: cdk.App, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const resource = new cr.AwsCustomResource(this, "acr", {
      onCreate: {
        service: "kinesisanalyticsv2",
        action: "describeApplication",
        parameters: {
          ApplicationName: "application-name",
        },
        physicalResourceId: cr.PhysicalResourceId.of(Date.now().toString()),
      },
      policy: cr.AwsCustomResourcePolicy.fromSdkCalls({
        resources: ["*"]
      }),
    });
  }
}
```

Then permission in CF templates contain

```
      PolicyDocument:
        Statement:
          - Action: kinesisanalyticsv2:DescribeApplication
            Effect: Allow
            Resource: "*"
```

### What did you expect to happen?

The role of aws custom resource should have the permission: `kinesisanalytics:DescribeApplication`.

### What actually happened?

The role has permission: `kinesisanalyticsv2:DescribeApplication`. The stack creation fails with the error.

```
Received response status [FAILED] from custom resource. Message returned: User: arn:aws:sts::<account>:assumed-role/<role> is not authorized to perform: kinesisanalytics:DescribeApplication on resource: arn:aws:kinesisanalytics:<region>:<account>:application/<application-name> (RequestId: <request-id>)
```

### Environment

  - **CDK CLI Version  :** 1.110.1 (build 0028d09)
  - **Framework Version:** 1.110.1
  - **Node.js Version:** v12.6.0 
  - **OS               :** OSX
  - **Language (Version):** all 

### Other

According to a document: https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonkinesisanalyticsv2.html, the service prefix is `kinesisanalytics`. 
I believe that [metadata.json](https://github.com/aws/aws-sdk-js/blob/master/apis/metadata.json#L663) needs to have `prefix` as `kinesisanalytics`.  
Then the permission will be given below properly. https://github.com/aws/aws-cdk/blob/1b29ca8e8805fe47eb534d2f564d18ca297e956f/packages/%40aws-cdk/aws-events-targets/lib/aws-api.ts#L140

I'm not sure if I'm supposed to create an issue in AWS SDK JS repo.

--- 

This is :bug: Bug Report

**Comment by Project0** [comment]
I have the same problem with `sns` (even from the example).

```ts
const verifyDomainIdentity = new custom.AwsCustomResource(
      this,
      'SESDomainIdentity',
      {
        onCreate: {
          service: 'SES',
          action: 'verifyDomainIdentity',
          parameters: {
            Domain: props.domain,
          },
          physicalResourceId:
            custom.PhysicalResourceId.fromResponse('VerificationToken'), // Use the token returned by the call as physical id
        },
        onDelete: {
          service: 'SES',
          action: 'deleteIdentity',
          parameters: {
            Identity: props.domain,
          },
        },
        policy: custom.AwsCustomResourcePolicy.fromSdkCalls({
          resources: custom.AwsCustomResourcePolicy.ANY_RESOURCE,
        }),
      }
    )
```

Generates the following policy
```json
          "Statement": [
            {
              "Action": "email:VerifyDomainIdentity",
              "Effect": "Allow",
              "Resource": "*"
            },
            {
              "Action": "email:DeleteIdentity",
              "Effect": "Allow",
              "Resource": "*"
            }
          ],
```

Instead of `email` it should actually be `sns`.

Turns out the prefix mapping is pulled from https://github.com/aws/aws-sdk-js/blob/cf5eb8b95af6ff658d1c22d9d18ef308e7f4b6ef/apis/metadata.json#L372. 
So either the mapping of the upstream is wrong or the logic in the CDK does use not a bullet proof source for this mapping.

**Comment by McDoit** [comment]
@Project0 There is a nice comment about it in the source of the aws custom resource:
```
/**
 * Transform SDK service/action to IAM action using metadata from aws-sdk module.
 * Example: CloudWatchLogs with putRetentionPolicy => logs:PutRetentionPolicy
 *
 * TODO: is this mapping correct for all services?
 */
```
I had an issue with ses permissions as well just now

**Comment by Project0** [comment]
maybe it is not clear for everyone, but the workaround is to set the policy manually, e.g for SES: 
```ts
        policy: custom.AwsCustomResourcePolicy.fromStatements([
          new iam.PolicyStatement({
            actions: ['ses:VerifyDomainIdentity', 'ses:DeleteIdentity'],
            resources: ['*'],
          }),
        ]),
```
