### ISSUE TITLE
(aws-appsync): update cfn resources to include custom authorizer

### ISSUE THREAD

**Issue by joekendal** [aws/aws-cdk#16061]
CloudFormation already supports the [AppSync Lambda Authorizer](https://aws.amazon.com/blogs/mobile/appsync-lambda-auth/) method as shown by the [docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appsync-graphqlapi.html#cfn-appsync-graphqlapi-lambdaauthorizerconfig).

Yet in the latest release of cdk docs, there does not appear to be a Cfn resource for it.

### Use Case

.

### Proposed Solution
At the very least we need a Cfn resource

And ideally also a cdk higher level construct.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by michaelbrewer** [comment]
Would like to see this happen to.

**Comment by otaviomacedo** [comment]
This property is already available in version 1.119.0.
