### ISSUE TITLE
Show stack dependency tree

### ISSUE THREAD

**Issue by atennak1** [aws/aws-cdk#16080]
It would be great if the list command displayed dependencies between stacks, perhaps in a tree-like structure.  We recently made the incorrect assumption that simply declaring a stack inside of another stack (without using `cfn.NestedStack`) would ensure correct deployment order.  We could have used such a feature to validate that assumption.

### Use Case

To verify that stack dependencies are correctly modeled.

### Proposed Solution

if StackA has a dependency on StackB, it would show something like this:
```
.
└── StackA
    └── StackB
```

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by ryparker** [comment]
Hey @atennak1 :wave:

Thanks for the feature request.

I am marking this issue as p2 which means that we are unable to work on this immediately. We use +1s to help us prioritize our work, and as always we are happy to take contributions if anyone is interested to pick this up and submit a PR (please make sure to follow our [contribution guidelines](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md).)
:pray:

**Comment by SimonCMoore** [comment]
This was fixed by https://github.com/aws/aws-cdk/pull/28995 in [v2.132.0]
