### ISSUE TITLE
(aws-eks): Continue on warning (such as API deprecation warning) in add_manifest

### ISSUE THREAD

**Issue by jasonumiker** [aws/aws-cdk#16087]
When using add_manifest to add a YAML manifest to an EKS Cluster it fails to deploy if there is a warning. It throws a warning when submitting manifest with a deprecated API version - but these would be successful and shouldn't be treated like an error. There is a strong argument that it should be allowed to give people time to upgrade their manifests to the new API.

Either the default should be to succeed when there is a warning or at least we should have a parameter to allow people to opt-in to proceeding.

**Comment by ryparker** [comment]
Hey @jasonumiker 👋🏻 

Thanks for opening this request. 

> but these would be successful and shouldn't be treated like an error.

Where exactly would this be successful? CloudFormation?

**Comment by jasonumiker** [comment]
These are the warnings I am talking about. If I submit a manifest using add_manifest on a Cluster (in Python CDK) it errors out and fails. https://kubernetes.io/blog/2020/09/03/warnings/
