### ISSUE TITLE
[aws-eks]:  allow users to specify a custom iam role for cluser. add_service_account and cluster. open_id_connect_provider operations

### ISSUE THREAD

**Issue by XuejiaoZhang** [aws/aws-cdk#16088]
Allow users to specify a custom iam role for cluser. add_service_account and cluster. open_id_connect_provider operations

### Use Case

By default, when running EKS OIDC operation for example  cluser. add_service_account and  cluster. open_id_connect_provider, it will create a role to execute the operations.
But in some cases, only a specific role is allowed to do the operations, for example SCP has some restriction , we need to specify a custom role  to add OIDC provider.

### Proposed Solution

Allow users to specify a custom iam role for cluser. add_service_account and cluster. open_id_connect_provider operations

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by otaviomacedo** [comment]
Thanks for this request, @XuejiaoZhang.

These roles would add more flexibility, for sure. However, we can't work on this immediately.

We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://join.slack.com/t/cdk-dev/shared_invite/zt-mso6p56d-qJp7SOTBvMaQuDrx7R2wHg) to solicit support for reprioritization.
