### ISSUE TITLE
(core): Tape into CDK credentials and parameter

### ISSUE THREAD

**Issue by lony** [aws/aws-cdk#16096]
I have multiple problems using AWS CDK, which are all related to access of its credentials. Is there a way of adding a bridge to CDKs credentials, so they can be used as well with boto3?

### Use Case

* AWS cdk retrieve account number when working with roles https://stackoverflow.com/questions/68564390/aws-cdk-retrieve-account-number-when-working-with-roles
* (cdk + boto3): Use boto3 inside CDK application https://stackoverflow.com/questions/68819386/cdk-boto3-use-boto3-inside-cdk-application

### Proposed Solution

Add a core credentials object which can be used by boto3, enabling use of boto3 from within CDK. This needs an update to the documentation so others know how to use it.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by ryparker** [comment]
Hey @lony 👋🏻 

Thanks for the feature request.

I'm going to mark this as p2 which means that we are unable to work on this immediately. 
We use +1s to help prioritize our work, and as always we are happy to take contributions if anyone is interested to pick this up and submit a PR (please make sure to follow our [contribution guidelines](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) 🙏🏻

**Comment by lony** [comment]
Thanks - I'm not aware how much work it would be, considering TypeScript conversion - but I think it would help build more integrated deployment pipelines.

**Comment by rix0rrr** [comment]
We would prefer you don't make SDK calls from within the CDK app, so we don't do anything to make it easy for you to do that, on purpose.

I think you are looking to implement your own context providers. There is an open discussion/feature request for that here: https://github.com/aws/aws-cdk-rfcs/issues/18

Upvote that to indicate interest, this will affect our planning. Closing this issue.
