### ISSUE TITLE
(aws-cloudtrail): sendToCloudWatchLogs should default to true when cloudWatchLogGroup or cloudWatchLogsRetention is provided.

### ISSUE THREAD

**Issue by javydekoning** [aws/aws-cdk#16092]
Sending events to CloudWatch is not enabled when `cloudWatchLogGroup` or `cloudWatchLogsRetention` property is passed in. You need explicitly set `sendToCloudWatchLogs` to `true`.  If `cloudWatchLogGroup` or `cloudWatchLogsRetention` is passed in, this should be implicit.

### Reproduction Steps

```ts
    const trail = new ct.Trail(this, 'BaseLineCloudWatchTrail', {
      cloudWatchLogGroup: this.cloudTrailLogGroup,
      managementEvents: ct.ReadWriteType.WRITE_ONLY,
      isMultiRegionTrail: false,
    });
```

### What did you expect to happen?

I would expect events to turn up in the provided `cloudWatchLogGroup`. But need to manually turn on `sendToCloudWatchLogs: true` to make this happen.

### Environment

N/A

### Other

https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-cloudtrail/lib/cloudtrail.ts#L238 could be changed to: 

```ts
    if (props.sendToCloudWatchLogs || props.cloudWatchLogGroup || props.cloudWatchLogsRetention) {
```

alternatively we could do: 

```ts
if (props.cloudWatchLogGroup || props.cloudWatchLogsRetention) {
  if (props.sendToCloudWatchLogs == undefined) {
    props.sendToCloudWatchLogs = true
  }
}
```

--- 

This is :bug: Bug Report

**Comment by javydekoning** [comment]
Looks like there is already a PR open for this: https://github.com/aws/aws-cdk/pull/14366/commits/e707ec048ae93e51171f6c00f7736454e302e186

**Comment by rix0rrr** [comment]
I like it! The commit you referenced doesn't seem to belong to a PR anymore, but we would totally accept this change.
