### ISSUE TITLE
(aws-codebuild): option to enable public build access

### ISSUE THREAD

**Issue by trivikr** [aws/aws-cdk#16104]
This is a feature request to add an option to enable public build access in `@aws-cdk/aws-codebuild`
AWS CodeBuild introduced [public builds](https://aws.amazon.com/blogs/devops/introducing-public-builds-for-aws-codebuild/) on 08/12/2021

### Use Case
Add an option to enable public build access in `@aws-cdk/aws-codebuild`

### Proposed Solution

```ts
import * as codebuild from "@aws-cdk/aws-codebuild";
//...
new codebuild.Project(this, 'MyProject', {
  //...
  projectVisibility: codebuild.ProjectVisibility.PUBLIC_READ
  //...
});
```

### Other

CodeBuild docs on [projectVisibility](https://docs.aws.amazon.com/codebuild/latest/APIReference/API_UpdateProjectVisibility.html#API_UpdateProjectVisibility_RequestSyntax)

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by keenangraham** [comment]
This would be great. Manually enabling in the console works temporarily, but gets reset when you deploy any changes to your CodeBuild stack.

Are there any known workaround using the CDK itself?

**Comment by skinny85** [comment]
Probably [escape hatches](https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html) would be your best bet,

We also accept [Pull Requests](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) 😉.

**Comment by keenangraham** [comment]
For reference got this to work using underlying `CfnProject`.

Simply setting [visibility](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_codebuild.CfnProject.html#visibility) to `PUBLIC_READ` is enough to get URL with public build results.
```python
cfn_project = codebuild_project.node.default_child
cfn_project.visibility = 'PUBLIC_READ'
```

However if you click through to view logs for a run you get permission error. 

After looking through docs some more it became apparent that it's also important to set the [resourceAccessRole](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_codebuild.CfnProject.html#resourceaccessrole) with role that has permission to `logs:GetLogEvents` from project's CloudWatch log group (looks like console creates this service role for you automatically):

```python
import aws_cdk as cdk

from aws_cdk.aws_iam import PolicyStatement
from aws_cdk.aws_iam import Role
from aws_cdk.aws_iam import ServicePrincipal

# .... In Stack with CodeBuild project.

# Create new service role.
resource_access_role = Role(
    self,
    'ResourceAccessRole',
    assumed_by=ServicePrincipal(
        'codebuild.amazonaws.com'
    )
)

# Generate log group ARN. 
# Pulled from https://github.com/aws/aws-cdk/blob/f10972081da7232773022affae4a6edba8ec97c0/packages/%40aws-cdk/aws-codebuild/lib/project.ts#L1256-L1263
project_name = codebuild_project.project_name
log_group_arn = cdk.Stack.of(self).format_arn(
    service='logs',
    resource='log-group',
    arn_format=cdk.ArnFormat.COLON_RESOURCE_NAME,
    resource_name=f'/aws/codebuild/{project_name}',
)
log_group_star_arn = f'{log_group_arn}:*'

# Create policy to allow getting log events from log group.
public_log_read_policy = PolicyStatement(
    resources=[
        log_group_star_arn,
    ],
    actions=[
        'logs:GetLogEvents'
    ],
)

# Add policy to service role.
resource_access_role.add_to_principal_policy(
    public_log_read_policy
)

# Pass service role ARN to CfnProject.
cfn_project.resource_access_role = resource_access_role.role_arn
```

After adding this the public URL works, and clicking on log details work.

However I found a useful CloudFormation example [here](https://aws.amazon.com/blogs/devops/introducing-public-builds-for-aws-codebuild/) that shows creating a policy for the `resourceAccessRole` that also has permission to read from an s3 artifact bucket: 

```yml
PublicReadPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: PublicBuildPolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "logs:GetLogEvents"
            Resource:
              - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:${LogGroupName}:*"
          - Effect: Allow
            Action:
              - "s3:GetObject"
              - "s3:GetObjectVersion"
            Resource:
              - !Sub "${ArtifactBucketArn}/*"
```

So if you output artifacts to s3 bucket you also have to add access permission to the role, e.g.:
 ```python
from aws_cdk.aws_codebuild import Artifacts

....

codebuild_artifacts = Artifacts.s3(
    bucket=s3_bucket,
)
artifact_bucket_star_arn = f'{artifact_bucket.bucket_arn}/*'
public_artifact_read_policy = PolicyStatement(
    resources=[
        artifact_bucket_star_arn,
    ],
    actions=[
        's3:GetObject',
        's3:GetObjectVersion',
    ],
)
resource_access_role.add_to_principal_policy(
    public_artifact_read_policy
)
```

As far as PR it seems relatively straightforward to expose parameters for `visibility` and `resourceAccessRole` that get passed down to `CfnProject`. Probably it would make sense to automatically generate a `resourceAccessRole` (if not passed in) with permission to read from log group if `visibility` is public.

I'm not really sure what the default behavior for artifact buckets should be though. Unless there is some way to iterate through all of the artifact buckets maybe the cleanest thing is to have some kind of `grantPublicRead(artifactBucket)` method that people call manually? Seems a little special case though.
