### ISSUE TITLE
sts:AssumeRole permission must be added to CodePipeline for Build stage to complete

### ISSUE THREAD

**Issue by philvarner** [aws/aws-cdk#16105]
This CodePipeline can be found here:
https://github.com/MAAP-Project/mmt/blob/cdk-ecs-pipeline/deployment/cdk/app.py
required adding sts:AssumeRole permission as a code build option to get the pipeline to run successfully. I would not have expected that I needed to add this type of permission to a pipeline that is doing this as part of the generated code.

### Reproduction Steps

The code for this pipeline is here:
https://github.com/MAAP-Project/mmt/blob/cdk-ecs-pipeline/deployment/cdk/app.py

Without adding the "sts:AssumeRole" permission below:
```
code_build_defaults=pipelines.CodeBuildOptions(
                role_policy=[
                    iam.PolicyStatement(
                        actions=["route53:*"], resources=["*"]),
                    iam.PolicyStatement(
                        actions=["sts:AssumeRole"], resources=["*"]),
                ],
```

the pipeline fails in the Build stage with an error message indicating that a role that's generated as part of the CDK build cannot be assumed:

```
> cdk-deploy@0.1.0 cdk /codebuild/output/src320614803/src/deployment
--
current credentials could not be used to assume 'arn:aws:iam::XXXXXXXXXXXX:role/cdk-hnb659fds-lookup-role-XXXXXXXXXXXX-us-west-2', but are for the right account. Proceeding anyway.

[Error at /PipelineStack/mmt-app/dit-maap-mmt] You are not authorized to perform this operation.
```

### What did you expect to happen?

The Build step would complete with the default permissions. 
I understand that the route53 permission must be added to the Build stage because that's something my code is using in synth that's not part of the default permissions, but I would have expected the "sts:AssumeRole" permission to be added automatically, since the Assets stage is doing that "under the hood".

### What actually happened?

The Build step failed because a Role could not be assumed

### Environment

  - **CDK CLI Version  :** 1.118.0
  - **Framework Version:** 1.118.0
  - **Node.js Version:** 14.17.5 (but code is running in CodePipeline)
  - **OS               :** MacOS (but code is running in CodePipeline)
  - **Language (Version):** 3.8.10 (but code is running in CodePipeline)

### Other

n/a

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
The problem is pretty much in the error:

```
current credentials could not be used to assume 'arn:aws:iam::532321095167:role/cdk-hnb659fds-lookup-role-532321095167-us-west-2', but are for the right account. Proceeding anyway.
```

Please investigate why this AssumeRole action fails.

It could be:

* The mentioned role does not exist
* The mentioned role does not have the correct AssumeRolePolicy document
* The CodeBuild execution role does not have the right IAM permissions to assume the role

We will be able to help you better if you tell us which part is failing.

**Comment by philvarner** [comment]
> The mentioned role does not exist

The mentioned role does exist, since it is assumed correctly when I add `iam.PolicyStatement(actions=["sts:AssumeRole"], resources=["*"])`

> The mentioned role does not have the correct AssumeRolePolicy document

This role is automatically generated as part of the plumbing of CDK (it's not even in the synth output), so I would expect this to work automatically. The AssumeRolePolicy for that role is below (with my acct number X'ed):

```
{
  "Version": "2008-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::XXXXXXXXXXXX:root"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
```

> The CodeBuild execution role does not have the right IAM permissions to assume the role

I'm guessing adding the sts:AssumeRole permission to the PipelineBuildSynthCdkBuildProjectRoleDefaultPolicy is what makes this work. That role doesn't have any sts:AssumeRole permissions by default, even though the stage is running with a role that has that policy. I wouldn't expect to need to add that permission explicitly, since the internal CDK code is doing that assume role operation.

**Comment by TomaszSzusterTR** [comment]
I have the same issue here.

**Comment by rix0rrr** [comment]
How did I even miss this in the first place, sorry I must not have been paying attention.

This is by design. Read this: 

https://docs.aws.amazon.com/cdk/api/latest/docs/pipelines-readme.html#context-lookups

**Comment by philvarner** [comment]
@rix0rrr thanks for that link, that perfectly describes what I encountered. While that section does have a thorough description of what to do, I think it is very unlikely a user who doesn't already know that this is the problem and solution is would be able to figure it out based on that documentation. I would highly recommend providing this in an FAQ with exactly the type of error message one would get without the assumerole permission (so that it is googleable) and incorporate this into at least one CDK example. Also putting a note in the Hosted Zone ID lookup function about the need to add this permission with a link to this documentation would be very useful.
