### ISSUE TITLE
(DMS endpoint for RDS ): need the support of  DMS endpoint using RDS

### ISSUE THREAD

**Issue by Charu2601** [aws/aws-cdk#16110]
### The Question
 We want to use the CDK for DMS endpoint setting for databases like Postgresql, MySQL, MongoDB etc, As DMS endpoint currently support for DynamoDBSettings, ElasticSearchSettings, and NeptuneSettings. Could you please provide the support for the mentioned DBs
[2]: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-endpoint.html

### Environment

 
  - **Language (Version):**

**Comment by peterwoodworth** [comment]
Hey @Charu2601,

Our [CfnEndpoint](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-dms.CfnEndpoint.html) has properties for MySql, Postgres, and MongoDB. Our DMS library is completely autogenerated from the [CloudFormation Resource Specification](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html), so if you're on the latest version of the CDK you should be able to use the properties exactly like how they're defined in CloudFormation
