### ISSUE TITLE
(aws-dynamodb): L2 Construct for GlobalTable

### ISSUE THREAD

**Issue by cmckni3** [aws/aws-cdk#16118]
Create an L2 construct for `AWS::DynamoDB::GlobalTable` to abstract away creation details.

Handling the setup of streams, encryption, etc., in the L1 construct can be cumbersome.

### Use Case

DynamoDB replication between regions.

### Proposed Solution

Create L2 construct called `GlobalTable` similar to the `Table` construct.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by madeline-k** [comment]
Link: https://github.com/aws/aws-cdk/issues/15957

**Comment by madeline-k** [comment]
Thanks for opening this feature request! There are a couple of issues open asking for the same thing, will link them here:
#15957, https://github.com/aws/aws-cdk/issues/15258. I am marking this as a p2, which means we won't be able to prioritize it right now. But we always welcome contributions! It looks like there are a few people in the community interested in adding this. Please take a look at our contributing guide: https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md

**Comment by ethanrucinski** [comment]
I have started working on an L2 construct for this. @cmckni3 if you happen to have any specific use cases or requests let me know if it might be possible to share! I'd love any feedback if I'm able to make my way along with this.

**Comment by ethanrucinski** [comment]
Hey do we have an ETA for this construct? We're trying to decide if we should publish our own internally or wait for this to become available

**Comment by barriem** [comment]
Would be awesome to get the new L2 construct, keeping an eye on this ticket!

**Comment by nakedible-p** [comment]
Big question here: are you planning on keeping the current method of just setting `replicationRegions` on a DynamoDB `Table` to create a global table - or are you planning on exposing a different construct `GlobalTable` for global tables as CloudFormation does?

I might able to contribute if this decision is clear.

**Comment by gagipro** [comment]
+1
issue with node JS14.x deprecation on custom resources and not respecting enterprise security rules.
also removing replication through cdk doesn't seem supported.

**Comment by mrgrain** [comment]
Ref: https://github.com/aws/aws-cdk-rfcs/blob/master/text/0510-dynamodb-global-table.md

**Comment by anshu49746** [comment]
Hi,

Any ETA when the Global Table L2 construct will be available for usage?

**Comment by anshu49746** [comment]
@vinayak-kukreja  I see the update mentioned in the below link for L2 construct, but am unable to find it in aws cdk typescript.
Please let me know how to start using it.
https://github.com/aws/aws-cdk-rfcs/blob/master/text/0510-dynamodb-global-table.md
