### ISSUE TITLE
awsiam: Creating a new role is quite a frustrating UX

### ISSUE THREAD

**Issue by kaihendry** [aws/aws-cdk#16128]
<img src="https://s.natalian.org/2021-08-19/1629352997_1918x1047.png">

### The Question

Problem: Just want to create a role for account 1234 to assumerole of arn:aws:iam::aws:policy/CloudWatchReadOnlyAccess

First discovering the API https://pkg.go.dev/github.com/aws/aws-cdk-go/awscdk@v1.119.0-devpreview/awsiam#NewCfnRole was non-trivial.

Then after trying to flesh out the Properties struct, it gets stuck with jsii.Array which I can't find any mention of, upon https://github.com/aws/jsii/

So I chose to author the https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html via CDK to get some discoverability or prompts to fill in the parameters correctly. This was not the experience I was hoping for!

### Environment

  - **CDK CLI Version:** 1.118.0 (build a4f0418)
  - **OS:** Archlinux
  - **Language (Version):** Go https://s.natalian.org/2021-08-19/go.mod

**Comment by peterwoodworth** [comment]
Thanks for sharing your experience @kaihendry, I'm sorry this has been frustrating for you.

Go support for CDK is still in developer preview. As a result, our docs are currently lacking. We're working on providing a better experience for Go CDK developers through providing good documentation and examples.

**Comment by kaihendry** [comment]
Hi Peter,

Forgive my ignorance here, though isn't the point of the CDK is to allow developers to discover Cloudformation API surface area in an IDE-like (auto-complete) experience? Just want to make sure I'm on the same page. =)

And is there a way I could forward with the jsii.Array pickle I have?

**Comment by peterwoodworth** [comment]
You're correct. That's a feature that's still lacking in Go. We're aware of the issue and tracking it here: #15114 

Please share your experience in that thread, and feel free to give mrarnoldpalmer a ping asking for an update on the issue.

As for the array, you don't want to use jsii.Array. You want to declare arrays like so: 
```
&[]_type_{
        element,
        element2
}
```

**Comment by peterwoodworth** [comment]
I hope I helped with your array issue, I'm closing this in favor of #15114.
