### ISSUE TITLE
(module name): credentials issue for cdk synth

### ISSUE THREAD

**Issue by rudpot** [aws/aws-cdk#16127]
Running `cdk synth` with `CDK_DEFAULT_ACCOUNT`, `CDK_DEFAULT_REGION`, context files from previous runs, and without a explicit profile set and no `[default]` section in `~/.aws/config` picks up the wrong region information and fails. 

### Reproduction Steps

Stack definition using `CDK_DEFAULT_ACCOUNT`, `CDK_DEFAULT_REGION`
```ts
const app = new cdk.App();
new AsgCdkTestStack(app, 'FisStackAsg', {
  env: { 
    account: process.env.CDK_DEFAULT_ACCOUNT, 
    region: process.env.CDK_DEFAULT_REGION 
  },
  description: "AWS FIS workshop - EC2/autoscaling group stack. Creates an EC2 autoscaling group and associated CloudWatch dashboards for disruption"
});
```

Resources that require an account lookup or a context file from a prior run:

```ts
    const vpc = ec2.Vpc.fromLookup(this, 'FisVpc', { 
      vpcName: 'FisStackVpc/FisVpc'
    });
```

Environment variables with the region anything other than `us-east-1`:

```sh
$ env | grep CDK
CDK_DEFAULT_ACCOUNT=111122223333
CDK_DEFAULT_REGION=us-west-2
$ env | grep AWS
```

An appropriate context file `cdk.context.json`:

```json
{
  "vpc-provider:account=111122223333:filter.tag:Name=FisStackVpc/FisVpc:region=us-west-2:returnAsymmetricSubnets=true": {
    "vpcId": "vpc-0f6f9b034dcad392e",
    "vpcCidrBlock": "10.0.0.0/16",
...
```

Run `cdk synth` to get an error:

```sh
[Error at /FisStackAsg] Need to perform AWS calls for account 238810465798, but no credentials have been configured
```

### What did you expect to happen?

The `cdk synth` should have read all values from the context file and have succeeded.

### What actually happened?

Received error

```sh
[Error at /FisStackAsg] Need to perform AWS calls for account 238810465798, but no credentials have been configured
```

### Environment

  - **CDK CLI Version  :**  1.115.0 and  1.119.0
  - **Framework Version:** 
  - **Node.js Version:**  v16.6.0
  - **OS               :** macOS and ubuntu
  - **Language (Version):**  tested with
    - npm 7.19.1
    - typecript 4.35 

### Other

Running `cdk synth -v` select output lines:

```sh
$ cdk synth -v
CDK toolkit version: 1.115.0 (build f0ca40f)
Command line arguments: {
...
  defaultAccount: 238810465798,
  defaultRegion: 'us-west-2',
...
Determining if we're on an EC2 instance.
Does not look like an EC2 instance.
Unable to determine AWS region from environment or AWS configuration (profile: "default"), defaulting to 'us-east-1'
Toolkit stack: CDKToolkit
Setting "CDK_DEFAULT_REGION" environment variable to us-east-1
Resolving default credentials
Unable to determine the default AWS account: ProcessCredentialsProviderFailure: Profile default not found
...
env: {
  CDK_DEFAULT_REGION: 'us-east-1',
...
```

Note the issue in the middle.

### Workaround

The issue can be addressed by creating a default profile that only contains region information

```sh
$ aws configure set region us-west-2
$ cat ~/.aws/config
[default]
    region=us-west-2
```

--- 

This is :bug: Bug Report

**Comment by RecGFI** [comment]
Hello, we are a group of researchers developing machine learning techniques to locate issues suitable for newcomers, and our model consider this issue as likely a "good first issue". May we recommend you to label it as "good first issue" so newcomers know where to choose?

Thank you!

**Comment by jumic** [comment]
In my opinion, this is not a bug. The behavior is explained in the [documentation](https://docs.aws.amazon.com/cdk/latest/guide/environments.html):
> ... CDK_DEFAULT_ACCOUNT and CDK_DEFAULT_REGION. These variables are set based on the AWS profile specified using the --profile option, or the default AWS profile if you don't specify one.

CDK sets `CDK_DEFAULT_ACCOUNT` automatically to the account which is configured in your AWS profile (or uses the profile option).

I did a similar example and specified the standard environment variable `CDK_DEFAULT_ACCOUNT` and the custom environment variable `MY_CDK_DEFAULT_ACCOUNT`.

Command `env | grep CDK` shows this output:
```
CDK_DEFAULT_ACCOUNT=111222333
MY_CDK_DEFAULT_ACCOUNT=111222333
```

I logged both variables in the CDK code:
```
console.log(`CDK_DEFAULT_ACCOUNT ${process.env.CDK_DEFAULT_ACCOUNT}`);
console.log(`MY_CDK_DEFAULT_ACCOUNT ${process.env.MY_CDK_DEFAULT_ACCOUNT}`);
```

Result:
```
CDK_DEFAULT_ACCOUNT 9876543210
MY_CDK_DEFAULT_ACCOUNT 111222333
```

That means the value for custom variable `MY_CDK_DEFAULT_ACCOUNT` is available. Variable `MY_CDK_DEFAULT_ACCOUNT` was overwritten by CDK.

**Comment by ryparker** [comment]
Hey @rudpot 👋🏻 

Julian is correct that this is expected behavior. If there is not a default profile set, then `CDK_DEFAULT_REGION` will not be injected with a value.

See [CDK's environment documentation](https://docs.aws.amazon.com/cdk/latest/guide/environments.html) for details.
