### ISSUE TITLE
(pipelines): The new CDK Pipelines should support referencing stack outputs in CodeBuild actions

### ISSUE THREAD

**Issue by markusl** [aws/aws-cdk#16137]
Looking at this code, it seems that referencing stack outputs is only supported with ShellStep, but not for CodeBuild steps https://github.com/aws/aws-cdk/blob/62e2f197a2dd25bcdfc06747d2897f4f29aa1a6c/packages/%40aws-cdk/pipelines/lib/helpers-internal/pipeline-queries.ts#L25

### Use Case

We deploy CodeBuild projects to multiple target accounts and need to run validation / testing steps as part of CI/CD Pipelines.

With "legacy" pipelines, you can use `pipeline.stackOutput(appStack.urlOutput)` but I cannot seem to find a way to do this with the new pipelines API.

```ts
const appStack = new ExampleAppStack(cdkStage, env, ...);

const parameters = {
    SERVICE_URL: pipeline.stackOutput(appStack.urlOutput),
};
const commands = ['curl -v $SERVICE_URL'];
const integTests = new ExampleIntegTestStack(cdkStage, env, {
    name: `LambdaDemoIntegrationTest-${env}`,
    vpcConfig,
    commands,
    useOutputs: parameters,
    additionalArtifacts: [sourceArtifact],
});
const integTestStage = pipeline.addStage(`IntegrationTests-${env}`);
integTestStage.addActions(new codepipeline_actions.CodeBuildAction({
    actionName: 'IntegrationTests',
    input: sourceArtifact,
    extraInputs: [sourceArtifact, pipeline.stackOutput(appStack.urlOutput).artifactFile.artifact],
    project: codebuild.Project.fromProjectName(integTests, 'ImportedProject', integTests.codebuildProject.projectName),
    role: iam.Role.fromRoleArn(integTests, 'ImportedRole', integTests.codebuildRole.roleArn),
}));


```

### Proposed Solution

Could you give an example of how to achieve the same functionality with the new Pipelines API that was possible with the old one?

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by markusl** [comment]
@kaizen3031593 can you confirm this also works for cross-account CodeBuild project? And adds the additional input artifacts accordingly?

**Comment by rix0rrr** [comment]
It no longer works via artifacts, but via CodePipeline variables. And yes, it will also work for cross-account deployments.

**Comment by markusl** [comment]
@rix0rrr We would appreciate it if you could provide an example in the documentation about how to deploy the CodeBuild project to the target account :) I couldn't figure it out because it seems `pipelines.CodeBuildStep` can only be used with CodeBuild projects on the pipeline account.

Please see the feature request about the documentation https://github.com/aws/aws-cdk/issues/16283

**Comment by rix0rrr** [comment]
Oh no, this is pretty much out of scope for our library I think.

You can do it yourself by implementing a custom step. There is an example in the code for a Jenkins step, but you can make it do whatever you want and you can create the CodeBuild project wherever you want.

**Comment by markusl** [comment]
@rix0rrr by looking at the `pipeline-queries.ts` it seems the stack output references only work for classes that are instances of `ShellStep`. Is the recommendation here to extend `ShellStep` or `CodeBuildStep` instead of a `Step` (which is explained in the docs)?
