### ISSUE TITLE
(aws_cdk.lambda): Add Python 3.9 to Lambda Runtime

### ISSUE THREAD

**Issue by kornicameister** [aws/aws-cdk#16144]
According to [this announcment](https://aws.amazon.com/blogs/compute/python-3-9-runtime-now-available-in-aws-lambda/), Lambda supports Python 3.9.

### Use Case

Ability to use Python 3.9 features.

### Proposed Solution

Modify this [file](https://github.com/aws/aws-cdk/blob/e2e008bd19c3ff1b08ccb093dba576551ec73240/packages/%40aws-cdk/aws-lambda/lib/runtime.ts) to include new runtime.

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by niebloomj** [comment]
Yes please!

**Comment by kornicameister** [comment]
Looks like there's a PR already for that.
Ref: #16072

**Comment by michaelbrewer** [comment]
@nija-at  - i added the runtime, but it wants a reference in the readme, but i am not sure where that is referencing.
