### ISSUE TITLE
(pipelines): CodeBuildStep.buildEnvironment.buildImage documentation refers to outdated version LinuxBuildImage.STANDARD_1_0

### ISSUE THREAD

**Issue by markusl** [aws/aws-cdk#16143]
When adding a `CodeBuildStep` in a pipeline the documentation caused a small confusion.

The `CodeBuildStep.buildEnvironment.buildImage` documentation refers to outdated version of the base image: `LinuxBuildImage.STANDARD_1_0`. However, the image used by `CodeBuildStep` by default seems to be `STANDARD_5_0` as one would expect.

https://github.com/aws/aws-cdk/blob/76fb4811bb9f5d5fc1bd340954840032cb23698b/packages/%40aws-cdk/aws-codebuild/lib/project.ts#L564

---

This is a 📕 documentation issue

**Comment by rix0rrr** [comment]
Ha! Good find. Because of the way our docs work this is actually not possible to fix :).

**Comment by AmmarRahman** [comment]
@markusl from what I understand, the buildImage documentation is part of codeBuild documentation which uses STANDARD_1_0 (I assumed not introduce breaking changes) 
https://github.com/aws/aws-cdk/blob/76fb4811bb9f5d5fc1bd340954840032cb23698b/packages/%40aws-cdk/aws-codebuild/lib/project.ts#L1026

It seems that CodeBuildStep is missing documentation for the override `Type: BuildEnvironment (optional, default: No value specified at construction time, use defaults)`
https://github.com/aws/aws-cdk/blob/76fb4811bb9f5d5fc1bd340954840032cb23698b/packages/%40aws-cdk/pipelines/lib/codepipeline/codepipeline.ts#L676

**Comment by markusl** [comment]
@AmmarRahman yep. That's right.

I believe it is not a good practice to default to a completely unmaintained build image (https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-available.html) although some AWS CDK services override the default setting. The problem reported in this ticket is that it's not obvious in the IDE when looking at the documentation that the default is, in fact, changed.

**Comment by AmmarRahman** [comment]
Totally agree with you. We got bitten by that outdated image multiple times. However, I can see how this can be considered a breaking change to a stable construct.
