### ISSUE TITLE
(cdk): provide codemods to transition to v2 syntax

### ISSUE THREAD

**Issue by blimmer** [aws/aws-cdk#16152]
I recently upgraded a few personal projects to the Developer Preview of CDK v2. It took quite a bit of time to manually rewrite all the imports according to [the migration guide](https://docs.aws.amazon.com/cdk/latest/guide/work-with-cdk-v2.html#v2-migrating). 

To ease this transition, it would be great to provide codemods that automatically migrate users existing code to CDK v2.

### Use Case

As a CDK user managing thousands of lines of CDK code, the manual steps to rewrite my CDK source code to be v2 compatible are daunting. This will likely delay my adoption until I have time to do these rewrites. However, if there were an automated codemod that managed this tedious task for me, I'm way more likely to do it sooner. As a freelance engineer, this effort would also save my clients a lot of funds 💸.

Additionally, by providing a codemod during the developer preview, you're likely to get more feedback by a barrier to trying it out.

### Proposed Solution

I formerly worked a lot with [EmberJS](https://emberjs.com/). They were great about providing codemods (see [ember-codemods](https://github.com/ember-codemods)) that made it super-easy for users to upgrade. ReactJS also has an official codemods repo ([react-codemod](https://github.com/reactjs/react-codemod)).

Both of these projects utilized the excellent [jscodeshift](https://github.com/facebook/jscodeshift) project to do the transforms. In addition to TypeScript support, they have a great testing framework to ensure codemods are working properly.

I've started work on codemods in [blimmer/aws-cdk-v2-codemods](https://github.com/blimmer/aws-cdk-v2-codemods). There's a TODO list in the README about the remaining tasks to complete. At the time of writing, I've already got a transform that rewrites the `Construct` import ([src](https://github.com/blimmer/aws-cdk-v2-codemods/blob/main/transforms/rewrite-construct-imports.ts)).

I propose we complete the remaining tasks in that repo (or move them into an official repo) to solve this problem.

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by nija-at** [comment]
Hey @blimmer,

I like that you've started working on an upgrade tool.

We have a very minimal one at the moment called `aws-cdk-migration`. Have you tried this out? It rewrites imports for a javascript or typescript module.

Looks like, besides this, the only additional change is the update to `package.json`. Do you feel we could write this into our existing package? 

I'm not aware of `jscodeshift`. I would love to hear what value we would get out of this toolkit.
Happy to also consider moving `aws-cdk-migration` to `jscodeshift` if that makes sense.

**Comment by blimmer** [comment]
Hey @nija-at, I actually didn't know that `aws-cdk-migration` existed. I didn't see it in the docs or anything. I just looked at the README and it looks pretty straightforward. I can give it a shot with the next migration I work on.

I think there are two things that my proposal would do that the current `aws-cdk-migration` does not handle:
1. Rewriting `Construct` imports to the new `constructs` pacakge.
2. Updating the `package.json` file (as you mentioned).

The traditional benefit of using `jscodeshift` is that it creates an Abstract Syntax Tree (AST) for regular Javascript files. However, I see that the `aws-cdk-migration` task uses TypeScript itself to create the AST. So, I think the biggest reason to use `jscodeshift` over `typescript` is if you wanted to support transitioning regular ol' javascript in addition to TypeScript. I'm not sure how many CDK users are using Javascript without TS, so it might be a moot point? What do you think?

**Comment by nija-at** [comment]
> Rewriting `Construct` imports to the new `constructs` pacakge.

The `aws-cdk-migration` package does support this - https://github.com/aws/aws-cdk/commit/37a4c8d49b6ed1d09eb084088487768e0f2346d0

I would suggest not moving to `jscodeshift` and keeping the migration script as is. Most of our users are typescript users.

**Comment by blimmer** [comment]
Sounds good @nija-at - thanks for the information. I'll go ahead and archive my codemods and link to `aws-cdk-migration`.

Maybe as you get closer to the v2 release, you could update this page to reference the codemods: https://docs.aws.amazon.com/cdk/latest/guide/work-with-cdk-v2.
