### ISSUE TITLE
aws-cloudfront: multiple EdgeFunctions differently scoped cause "There is already a Construct with name..."

### ISSUE THREAD

**Issue by victorlevasseur** [aws/aws-cdk#16151]
When two EdgeFunction are in the same stack and have the same logical id but in different constructs (so different "full paths" within the stack), the synth fails with a duplicate id error for the EdgeFunctions.

### Reproduction Steps

This code reproduces the issue:

```typescript
#!/usr/bin/env node
import 'source-map-support/register';
import * as cdk from '@aws-cdk/core';
import { Construct } from '@aws-cdk/core';
import { EdgeFunction } from '@aws-cdk/aws-cloudfront/lib/experimental';
import { Code, Runtime } from '@aws-cdk/aws-lambda';

// This construct shows the issue when used two times in the same stack.
export class StackBuggy extends Construct {

  constructor(scope: Construct, id: string) {
    super(scope, id);

    // Make the "logical" id dependent on the stack id and it will
    // work with both stacks.
    const edgeLambda = new EdgeFunction(this, "amazing-edge", {
      runtime: Runtime.NODEJS_12_X,
      code: Code.fromInline("export const handler = () => console.log('amazing');"),
      handler: 'index.handler'
    });
  }
}

// This construct works around the issue by tying the EdgeFunction id to the stack id.
export class StackWorkaround extends Construct {

  constructor(scope: Construct, id: string) {
    super(scope, id);

    const edgeLambda = new EdgeFunction(this, "amazing-edge-" + id, {
      runtime: Runtime.NODEJS_12_X,
      code: Code.fromInline("export const handler = () => console.log('amazing');"),
      handler: 'index.handler'
    });
  }
}

export class CdkEdgeFnDuplicateIdsStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    // These won't work because of the bug.
    new StackBuggy(this, 'first');
    new StackBuggy(this, 'second');

    // These are working because the EdgeFunction logical id are tied to the stack id,
    // producing globally unique logical id (which should not be needed, hence this Github issue).
    //new StackWorkaround(this, 'first');
    //new StackWorkaround(this, 'second');
  }
}

const app = new cdk.App();
new CdkEdgeFnDuplicateIdsStack(app, 'CdkEdgeFnDuplicateIdsStack', {
  env: {
    account: '123456789',
    region: 'eu-central-1'
  }
});

```

### What did you expect to happen?

Both EdgeFunctions should not cause an error when synth-ing the stack.

### What actually happened?

The synth fails with the following error:
```
/Users/victorlevasseur/Dev/temp/cdk-edge-fn-duplicate-ids/node_modules/constructs/src/construct.ts:381
      throw new Error(`There is already a Construct with name '${childName}' in ${typeName}${name.length > 0 ? ' [' + name + ']' : ''}`);
            ^
Error: There is already a Construct with name 'amazing-edge' in Stack [edge-lambda-stack-c860ec47f0a5f833d1384a23d682f6153776ef7e5d]
    at Node.addChild (/Users/victorlevasseur/Dev/temp/cdk-edge-fn-duplicate-ids/node_modules/constructs/src/construct.ts:381:13)
    at new Node (/Users/victorlevasseur/Dev/temp/cdk-edge-fn-duplicate-ids/node_modules/constructs/src/construct.ts:58:22)
    at new ConstructNode (/Users/victorlevasseur/Dev/temp/cdk-edge-fn-duplicate-ids/node_modules/@aws-cdk/core/lib/construct-compat.ts:184:24)
    at Object.createNode (/Users/victorlevasseur/Dev/temp/cdk-edge-fn-duplicate-ids/node_modules/@aws-cdk/core/lib/construct-compat.ts:55:11)
    at new Construct (/Users/victorlevasseur/Dev/temp/cdk-edge-fn-duplicate-ids/node_modules/constructs/src/construct.ts:409:26)
    at new Construct (/Users/victorlevasseur/Dev/temp/cdk-edge-fn-duplicate-ids/node_modules/@aws-cdk/core/lib/construct-compat.ts:52:5)
    at new Resource (/Users/victorlevasseur/Dev/temp/cdk-edge-fn-duplicate-ids/node_modules/@aws-cdk/core/lib/resource.ts:68:5)
    at new FunctionBase (/Users/victorlevasseur/Dev/temp/cdk-edge-fn-duplicate-ids/node_modules/@aws-cdk/aws-lambda/lib/function-base.js:17:9)
    at new Function (/Users/victorlevasseur/Dev/temp/cdk-edge-fn-duplicate-ids/node_modules/@aws-cdk/aws-lambda/lib/function.ts:297:5)
    at EdgeFunction.createCrossRegionFunction (/Users/victorlevasseur/Dev/temp/cdk-edge-fn-duplicate-ids/node_modules/@aws-cdk/aws-cloudfront/lib/experimental/edge-function.ts:134:26)
```

### Environment

  - **CDK CLI Version:** 1.119.0
  - **Framework Version:** 1.119.0
  - **Node.js Version:** 16.6.2
  - **OS               :** Mac OS X 11
  - **Language (Version):** TypeScript (3.8.3)

### Other

I think the issue is caused by the `createCrossRegionFunction` in `EdgeFunction` as it creates the `lambda.Function` construct in the cross-region stack using the logical id of the `EdgeFunction` construct without prefixing it with the construct "path" (to make a global id). So if two `EdgeFunction` have the same logical id in two different paths in the same stack, both `lambda.Function` constructs are created with the same logical id in the cross-region stack causing the duplicate logical id error on synth.

The problematic use of `EdgeFunction` logical id is probably here: https://github.com/aws/aws-cdk/blob/82dd2822a86431d0aa0be896550d421810b80c67/packages/%40aws-cdk/aws-cloudfront/lib/experimental/edge-function.ts#L154

--- 

This is :bug: Bug Report

**Comment by njlynch** [comment]
Thanks for the bug report and diagnosis, @victorlevasseur !

I agree with what you've said -- prepending/appending the stack ID to the Function id probably makes sense to prevent this kind of issue. The caveat with that will be checking that the ID doesn't exceed the maximum function name length (64 characters).

Given the workaround, I'm going to mark this as a p2, which means it's not on our immediate backlog. That being said, contributions are welcome, and I'd be happy to take a look at a PR if someone is up to it.

**Comment by victorlevasseur** [comment]
Thanks for the quick answer.
I may have confused the id, but we are talking about the logical id of the Lambda **construct** so it has no limits and it is not related to the function name (or the function name is produced by hashing the end of the logical id). So I think the issue is quite simple to fix and I'll try to propose a merge request.
