### ISSUE TITLE
(assets): Make stack available as an asset

### ISSUE THREAD

**Issue by 0xjjoyy** [aws/aws-cdk#16153]
Make stack available as an asset in another stack, as the synthesized file doesn't exist when the other stack needs it to sythensize it's stack.

### Use Case

AWS Config conformance packs need the cloudformation template
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-config.CfnOrganizationConformancePack.html

### Proposed Solution

Referencing https://github.com/aws/aws-cdk/issues/11896

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by kichik** [comment]
CDK Pipelines do something like that. I believe they use [Stage.synth()](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.Stage.html#synthoptions) which generates a cloud assembly. A cloud assembly contains and gives access to your template and other assets.

**Comment by amirfireeye** [comment]
Here is where that code lives https://github.com/aws/aws-cdk/blob/ebba61830ea7ee73e168099d1cd8e8f4003d595c/packages/%40aws-cdk/pipelines/lib/blueprint/stage-deployment.ts#L46-L80

**Comment by peterwoodworth** [comment]
Thanks for responding guys!

**Comment by 0xjjoyy** [comment]
I'm not sure why this is closed @peterwoodworth ? Is the feature implemented?

**Comment by peterwoodworth** [comment]
Sorry, I'm not sure what makes this feature request distinct from the one that was linked #11896. Are these not the same requests?

**Comment by peterwoodworth** [comment]
@0xjjoyy please ping me again if you can distinguish what's unique about this feature request
