### ISSUE TITLE
`appsync.GraphqlApi.addLambdaDataSource` doesn't strip symbols from `id` name, causing deploy to fail

### ISSUE THREAD

**Issue by jquesada2016** [aws/aws-cdk#16169]
Doing something like the following:
```typesciprt
const api = /* create api */
api.addLambdaDataSource(
      "lambda-name-ds",
      /* lambda */,
    );
```

does not remove the `-` from the id name, causing the deploy to fail with:
```
Property validation failure: [Value for property {/Name} does not match pattern {[_A-Za-z][_0-9A-Za-z]*}]
```

And if we look at the resulting stack.template.json file, we see the error is present:
```json
{
    "lambdadatasourceid": {
        /* ... */
        "Name": "ambda-name-ds"
        /* ... */
    }
}
```

### Reproduction Steps

Just create any appsync GraphQL API and add a lambda datasource that contains `-`. (haven't tested if other symbols also trip it up)

### What did you expect to happen?

I expect the `-` to be stripped out, just like all other id's in the CDK along with the deploy not failing.

### What actually happened?

The deploy fails.

### Environment

  - **CDK CLI Version  :** 1.119.0 (build 2921d64)
  - **Framework Version:** 1.119.0
  - **Node.js Version:** v16.6.1
  - **OS               :** Ubuntu (WSL 2)
  - **Language (Version):** TypeScript ~3.9.7

This is :bug: Bug Report

**Comment by BryanPan342** [comment]
We use the `id` as a fallback name if the name is not specified in the `options`. I believe this is expected behavior and I cant find other packages that clean the name for you.

**Comment by jquesada2016** [comment]
I use '-' for all my id names in all CDK packages, and they always get stripped away. I could provide an example for you, just let me know what you would like because I'm not sure how to demonstrate it besides what I've mentioned. I never specify the name, just let the CDK generate one based off the `id`, and deployment never fails, except for the `appsync` module.

**Comment by BryanPan342** [comment]
Ah i see where the problem.. the data source was implemented as a construct instead of a resource..

**Comment by otaviomacedo** [comment]
We can sanitize the id before assigning it to the data source name:

https://github.com/aws/aws-cdk/blob/2023004cc941a0e7a908bf3c90ad9887c6679564/packages/%40aws-cdk/aws-appsync/lib/data-source.ts#L114

I am unassigning and marking this issue as `p2`, which means that we are unable to work on this immediately.

We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://join.slack.com/t/cdk-dev/shared_invite/zt-mso6p56d-qJp7SOTBvMaQuDrx7R2wHg) to solicit support for reprioritization.

**Comment by readybuilderone** [comment]
I tried to created an S3 bucket using CDK with ID including various unusual characters as following:
![image](https://user-images.githubusercontent.com/53243835/132234775-60b3b589-1ba0-4725-a2e6-bd8481c99d36.png)


I compared the logical id in the aws console of cloudformation, and found all the unusual characters were stripped.
![image](https://user-images.githubusercontent.com/53243835/132234708-6aaa9869-6312-4800-8d26-14700e35709c.png)

By this logical analogy, I think we should stripe all of the characters except [_0-9A-Za-z] instead of just stripe '-' only. What do you think? @otaviomacedo @BryanPan342 @jquesada2016 , if you don't mind, I'd like try to solve this issue.
