### ISSUE TITLE
(@aws-cdk/core): Invalid physical name passed to CloudFormation. Use "this.physicalName" instead

### ISSUE THREAD

**Issue by bravogolfgolf** [aws/aws-cdk#16167]
### Reproduction Steps

```
const secret = new secretsmanager.Secret(this, 'secret', {
  secretName: cdk.PhysicalName.GENERATE_IF_NEEDED,
  generateSecretString: {
    secretStringTemplate: JSON.stringify({username: 'username'}),
    generateStringKey: 'password',
  },
});
const secretValue = cdk.SecretValue.secretsManager(secret.secretName, {
  jsonField: 'username'
}).toString();
new ssm.StringParameter(this, 'string-parameter', {stringValue: secretValue});

```
### What did you expect to happen?

I would expect it not to error.

### What actually happened?

node_modules/@aws-cdk/core/lib/private/physical-name-generator.ts:91
    throw new Error('Invalid physical name passed to CloudFormation. Use "this.physicalName" instead');

### Environment

  - **CDK CLI Version  : 1.118.0**
  - **Framework Version: 1.119.0**
  - **Node.js Version: v14.16.0**
  - **OS: macOS Big Sur 11.5.2 (20G95)**
  - **Language (Version): TypeScript (3.9.7)**
 
### Other

I originally tried literal secretName and received this error:
.../node_modules/@aws-cdk/core/lib/secret-value.ts:19
throw new Error('secret id "${secretId}" is not an ARN but contains ":"');
Issue: #16166

--- 

This is :bug: Bug Report

**Comment by FarrOut** [comment]
yea this is still an issue in CDK v2.93.0 with Python 3.11.4
