### ISSUE TITLE
(cdk-assets): cdk-assets should fail if selection yielded no results

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#16162]
If `cdk-assets` is executed and the asset query matches no assets, I would expect the command to fail and not succeed with no-op.

### Reproduction Steps

Just run `cdk-assets publish` against with an asset query that does not match any asset.

### What did you expect to happen?

I expected the command to fail.

### What actually happened?

I got the following output and the program exited with zero status (success).

```
verbose: Loaded manifest from cdk.out/assembly-EU/EUBucketStack0F6FDF2E.assets.json: 2 assets found
verbose: Applied selection: 0 assets selected.
```

### Environment

  - **CDK CLI Version  :** 1.119.0
  - **Framework Version:** N/A
  - **Node.js Version:**  N/A
  - **OS               :** N/A
  - **Language (Version):**  N/A

### Other

This behavior made it hard to debug an issue with github workflows support for CDK pipelines. In [this workflow run](https://github.com/eladb/cdk-pipelines-github-example/runs/3393339966?check_suite_focus=true), the deployment failed because the CloudFormation template could not be found on S3, but the asset publishing step (no. 5) succeeded.

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
Good idea
