### ISSUE TITLE
(aws-synthetics): provide syn-nodejs-puppeteer-3.2 runtime

### ISSUE THREAD

**Issue by gimyboya** [aws/aws-cdk#16177]
syn-nodejs-puppeteer-3.2 is out and currently we can use it as the `Runtime` class doesn't have it yet.

### Use Case

upgrading my canary construct to use `syn-nodejs-puppeteer-3.2` runtime.

### Proposed Solution

add an additional property to the `Runtime` class to have `SYNTHETICS_NODEJS_PUPPETEER_3_2` runtime

`public static readonly SYNTHETICS_NODEJS_PUPPETEER_3_2 = new Runtime('syn-nodejs-puppeteer-3.2');`

### Other

currently, I am seeing an error `Navigation failed because browser has disconnected!` without any logs or anything. I want to be able to upgrade the runtime as this seems to be a chromium issue.

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by kaizen3031593** [comment]
You can currently specify the new runtime by writing `new synthetics.Runtime('syn-nodejs-puppeteer-3.2')` for the runtime property. As for adding this as a static method, it is part of the open PR #16069.

**Comment by gimyboya** [comment]
Thank you @kaizen3031593 I am closing this
