### ISSUE TITLE
(aws-ecr-assets): Un-closed parentheses in Overview README, typo

### ISSUE THREAD

**Issue by douglasnaphas** [aws/aws-cdk#16171]
https://docs.aws.amazon.com/cdk/api/latest/docs/aws-ecr-assets-readme.html
https://github.com/aws/aws-cdk/blame/v1.119.0/packages/%40aws-cdk/aws-ecr-assets/README.md#L49-L50

Change

> Use `asset.imageUri` to reference the image (it includes both the ECR image URL and tag.

which has an un-closed parentheses, to

> Use `asset.imageUri` to reference the image. It includes both the ECR image URL and tag.

---

This is a 📕 documentation issue

**Comment by eladb** [comment]
Thanks! Contributions are welcome!
