### ISSUE TITLE
aws-synthetics: Navigation failed because browser has disconnected!

### ISSUE THREAD

**Issue by gimyboya** [aws/aws-cdk#16178]
### The Question
My canary was working properly until I started seeing in cloudwatch `No test result returned.Error: Navigation failed because the browser has disconnected!` errors with no screenshots or logs displayed.

I am not exactly sure how I can debug or fix this issue.

I have added the following code in vain:
```ts
// lunching a new (custom) browser
    const defaultOptions = await synthetics.getDefaultLaunchOptions();
    const launchArgs = [
        ...defaultOptions.args, 
        '--disable-features=AudioServiceOutOfProcess',
        '--disable-features=AudioServiceOutOfProcessKillAtHang',
        '--disable-gpu',
        '--disable-software-rasterize',
    ];
    await synthetics.launch({
        args: launchArgs
    });

```

    
Currently opened issue #16177 to be able to upgrade my runtime environment. but I would appreciate some guidance around this issue.

### Environment

  - **CDK CLI Version:** 1.119.0
  - **Module Version:** 1.119.0
  - **Node.js Version:** lts
  - **OS:** mac
  - **Language (Version):** TypeScript (4.3.5)

### Other information
I have referred to [this issue](https://github.com/alixaxel/chrome-aws-lambda/issues/104) hence the provided snippet of what I tried.

**Comment by peterwoodworth** [comment]
Hey @gimyboya, did this issue get resolved?

**Comment by peterwoodworth** [comment]
Seems to me like the issue got resolved based on the issue you linked, so I'll close this. Ping me if I'm mistaken
