### ISSUE TITLE
(ecs-patterns): ScheduledFargateTask target role does not enough permission to launch the task

### ISSUE THREAD

**Issue by sarbajitdutta** [aws/aws-cdk#16181]
ScheduledFargateTask target role(eventsRole) does not enough permission to launch the task. The target task does not have iam:passRole permission to the taskExecutionRole. The default target role only have permission for iam:passRole on only taskdefinitionRole. I have tried creating multiple scheduledFargate task and all have failed citing permission issue. This should be a bug.

### Reproduction Steps

```
//ReCiter-Machine-Learning-Analysis cron job
        reCiterMachineLearningFargateTask = new ScheduledFargateTask(this, "reCiterMachineLearningFargateTask", ScheduledFargateTaskProps.builder()
            .cluster(reCiterCluster)
            .desiredTaskCount(1)
            .schedule(Schedule.cron(CronOptions.builder()
                .hour("3")
                .minute("00")
                .build()))
            .enabled(true)
            .platformVersion(FargatePlatformVersion.LATEST)
            .ruleName("reCiter-machine-learning-analysis-rule")
            .vpc(vpc)
            .subnetSelection(SubnetSelection.builder()
                .onePerAz(true)
                .subnetType(SubnetType.PRIVATE)
                .build())
            .securityGroups(Arrays.asList(reciterClusterSg))
            .scheduledFargateTaskDefinitionOptions(ScheduledFargateTaskDefinitionOptions.builder()
                .taskDefinition(new FargateTaskDefinition(this, "reCiterMachineLearningAnalysisTaskDef", FargateTaskDefinitionProps.builder()
                    .cpu(1024)
                    .memoryLimitMiB(8192)
                    .build()))
                .build())
            .build());
```
### What did you expect to happen?

The scheduled fargate task will run with cloudwatch events.

### What actually happened?

The task run failed citing permission issues.
From Cloudtrail logs - 
```
"sourceIPAddress": "events.amazonaws.com",
"userAgent": "events.amazonaws.com",
"errorCode": "AccessDenied",
"errorMessage": "User: arn:aws:sts::xxxxxxxxxxxx:assumed-role/ReCiterCdkMasterStack-reC-reCiterMachineLearningAn-xxxxxxxxxxx/xxxxxxxxxxx is not authorized to perform: iam:PassRole on resource: arn:aws:iam::xxxxxxxxxxxxxxx:role/ReCiterCdkMasterStack-reC-reCiterMachineLearningAn-xxxxxxxxxxxxx",
```

### Environment

  - **CDK CLI Version:** 1.117.0
  - **Module Version:** 1.117.0
  - **Node.js Version:** 16
  - **OS:** macOS Sierra
  - **Language (Version):** java8

### Other

ScheduledFargateTask target role does not enough permission to launch the task. The target task does not have iam:passRole permission to the taskExecutionRole. The default target role only have permission for iam:passRole on only taskdefinitionRole.
The cdk does not expose the eventsRole through software.amazon.awscdk.services.events.Rule to add the policy. For reference on how the scheduledFargateTask is created see here - [CDK-Repo](https://github.com/wcmc-its/ReCiter-CDK/blob/4c039cd6cddde99486d331be2658f85c2a4967f9/src/main/java/edu/wcm/reciter/ReCiterCDKECSStack.java#L780)

--- 

This is :bug: Bug Report

**Comment by peterwoodworth** [comment]
The ScheduledFargateTask automatically creates an EcsTask here: https://github.com/aws/aws-cdk/blob/026cb8f1aa6b915969e22050968b0719c83aa2a4/packages/%40aws-cdk/aws-ecs-patterns/lib/fargate/scheduled-fargate-task.ts#L130-L137

Inside the EcsTask constructor, it will automatically create a role if there is no role passed in (which there can't be if you're using ScheduledFargateTask, feature request for that [here](https://github.com/aws/aws-cdk/issues/10352)): https://github.com/aws/aws-cdk/blob/7966f8d48c4bff26beb22856d289f9d0c7e7081d/packages/%40aws-cdk/aws-events-targets/lib/ecs-task.ts#L121-L127

The Policy Statements used are generated here: (I specifically linked the part where it attaches `PassRole` https://github.com/aws/aws-cdk/blob/7966f8d48c4bff26beb22856d289f9d0c7e7081d/packages/%40aws-cdk/aws-events-targets/lib/ecs-task.ts#L203-L210

So, you're right. This will only give `PassRole` permission to the task definition role.

You can work around this in the meantime by using [escape hatches](https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html#cfn_layer_resource) to modify the role that is automatically generated to have the permissions you need.

**Comment by sarbajitdutta** [comment]
@peterwoodworth Thanks for looking into this. Glad to know I was right. Do you have an example of how to use escape hatches to modify the default event role created. Will this be fixed in future release?

I am using 1.117.0.

**Comment by sarbajitdutta** [comment]
@peterwoodworth Actually I was able to do it. I am attaching as reference - 
```
final Role reCiterMachineLearningEventsModifiedRule = new Role(this, "reCiterMachineLearningEventsModifiedRule", RoleProps.builder()
            .description("This role will be events role for ReCiter-Machine-Learning-Analysis.")
            .roleName("cdk-reciter-machine-learning-events-role")
            .managedPolicies(Arrays.asList(new ManagedPolicy(this, "reCiterMachineLearningEventsPolicy", ManagedPolicyProps.builder()
            .managedPolicyName("cdk-reciter-machine-learning-events-role-policy")
            .description("This policy allows to run ECS task in cluster.")
            .statements(Arrays.asList(new PolicyStatement(PolicyStatementProps.builder()
                .sid("ecsRunTask")
                .actions(Arrays.asList("ecs:RunTask"))
                .effect(Effect.ALLOW)
                .resources(Arrays.asList(reCiterMachineLearningFargateTask.getTaskDefinition().getTaskDefinitionArn()))
                .conditions(new HashMap<String, Object>(){{
                    put("ArnEquals", new HashMap<String, Object>(){{
                        put("ecs:cluster", reCiterCluster.getClusterArn());
                    }});
                }})
                .build()),
            new PolicyStatement(PolicyStatementProps.builder()
                .sid("iamPassRole")
                .actions(Arrays.asList("iam:PassRole"))
                .effect(Effect.ALLOW)
                .resources(Arrays.asList(reCiterMachineLearningFargateTask.getTaskDefinition().obtainExecutionRole().getRoleArn(), reCiterMachineLearningFargateTask.getTaskDefinition().getTaskRole().getRoleArn()))
                .build())))
            .build())))
            .assumedBy(new ServicePrincipal("events.amazonaws.com"))
            .build());
        
CfnRule eventsRule = (CfnRule)reCiterMachineLearningFargateTask.getEventRule().getNode().getDefaultChild();
eventsRule.setRoleArn(reCiterMachineLearningEventsModifiedRule.getRoleArn());
```

**Comment by peterwoodworth** [comment]
I've marked this issue as a p1 and I'm keeping it open so that someone may fix this issue if they want to. Glad you got the workaround figured out!

**Comment by sarbajitdutta** [comment]
@peterwoodworth I have hit a snag again `CfnRule.setRoleArn(role)` only sets the role for the event itself but not for the target. I have been trying to update it like this but still having problems any help would be appreciated. 
```
CfnRule eventsRule = (CfnRule)reCiterMachineLearningFargateTask.getEventRule().getNode().getDefaultChild();
        eventsRule.setTargets(Arrays.asList(
            new CfnJson(this, "ecsTarget", CfnJsonProps.builder()
                    .value(new HashMap<String, Object>(){{
                        put("Arn", reCiterCluster.getClusterArn());
                        put("Id", "Target0");
                        put("RoleArn", reCiterMachineLearningEventsModifiedRule.getRoleArn());
                        put("EcsParameters", new HashMap<String, Object>(){{
                            put("LaunchType", "FARGATE");
                            put("NetworkConfiguration", new HashMap<String, Object>(){{
                                put("AwsVpcConfiguration", new HashMap<String, Object>(){{
                                    put("AssignPublicIp", "DISABLED");
                                    put("SecurityGroups", Arrays.asList(reciterClusterSg.getSecurityGroupId()));
                                    put("Subnets", Fn.split(",", Fn.importValue("vpcPrivateSubnets")));
                                }});
                            }});
                            put("PlatformVersion", "LATEST");
                            put("TaskCount", 1);
                            put("TaskDefinitionArn", reCiterMachineLearningFargateTask.getTaskDefinition().getTaskRole().getRoleArn());
                        }});
                    }})
                    .build()
                ))
            ); 
```

**Comment by johnslay** [comment]
Hey @sarbajitdutta, I managed to get your code to work by overriding the last part to be:

```
    CfnRule eventsRule = (CfnRule) scheduledFargateTask.getEventRule().getNode().getDefaultChild();

    if (eventsRule != null) {
        eventsRule.addOverride("Properties.Targets.0.RoleArn", modifiedRole.getRoleArn());
    }
```

**Comment by sarbajitdutta** [comment]
@johnslay Thank you for pointing it out. I was able to eventually overcome it by creating the target from scratch. But this way looks much cleaner. I will try it out and let you know if it works in my account. 

This is how I did it now - [eventsRoleEscapeHatch](https://github.com/wcmc-its/ReCiter-CDK/blob/be6a3f62977421bd3016f6e16f1c682206bb26dd/src/main/java/edu/wcm/reciter/ReCiterCDKECSStack.java#L813-L866)
