### ISSUE TITLE
Best way to integrate with webpack

### ISSUE THREAD

**Issue by jogold** [aws/aws-cdk#1620]
Hello,

I'm looking for a way to include a webpack step during deploy. Are there any plans to provide a way to hook in the asset prepare / deploy phase?

**Comment by jogold** [comment]
Hi @RomainMuller,

My use case is the following:
- I want to use babel
- I want to have small bundles containing only the run-time code required by my functions, one bundle per function
- I don't want to write each time a specific build script based on a "known, fixed location" for the lambdas
- I want to have my run-time code close to my constructs, something like this:
```
cdk-project
├── constructs
|   ├── CoolConstruct          # construct with a lambda.Function called `Importer`
|       ├── lib
|           ├── index.js
|           ├── importer
|               ├── index.js   # code for the lambda.Function called `Importer`
```

So far, I came up with the following solution:
- Created a `WebpackFunction` construct like this:
```js
const fs = require('fs');
const { join, dirname } = require('path');
const { Construct } = require('@aws-cdk/cdk');
const lambda = require('@aws-cdk/aws-lambda');

const { replace } = require('ramda');

const fnPath = replace(/\.[^.]+$/, '.js');

class WebpackFunction extends Construct {
  constructor(scope, id, { path, ...props }) {
    super(scope, id);

    const entryKey = fnPath(props.handler);
    const entryValue = `${join(path, entryKey)}`;
    const outputPath = `${join(path, '.webpack')}`;

    // Will be used to build the webpack config entry and output
    // properties by synthesizing the stack and extracting those
    // metadatas
    this.node.addMetadata('webpack:entry:key', entryKey);
    this.node.addMetadata('webpack:entry:value', entryValue);
    this.node.addMetadata('webpack:outputPath', outputPath);

    // In order to be able to synthesize the stack when creating
    // the webpack config the asset path needs to exists because it
    // is checked for a `lambda.Code.asset`. We use the original path
    // first to avoid this issue.
    const targetPath = fs.existsSync(outputPath) ? outputPath : dirname(entryValue);

    const fn = new lambda.Function(this, 'WebpackFunction', {
      code: lambda.Code.asset(targetPath), // Set asset path to webpack output path
      ...props,
    });

    return fn;
  }
}

module.exports = WebpackFunction;
```
- In my `webpack.config.js` I'm requiring the `app`, synthesizing all the stacks and extracting the `webpack:xxx` metadata. I then use this info to generate an array of webpack configurations based on a base webpack config (the whole process could be easily converted to a webpack plugin `cdk-webpack-plugin`, can share my code if you want to have a look at the process)
- I can now run `webpack && cdk deploy`

I wonder if there is a more elegant way to achieve this?

A plugin system with something like a hook during asset preparation would be ideal (an async function that receives some context, the original path and could return a new path?)

**Comment by iDVB** [comment]
Indeed. @jogold I would love that plugin. 
Also, another use-case is for frontend where deploy of API stack needs to happen first so that the generated APIG URL, Cognito URL etc can be *baked into* the frontend webpack stack. 

Usually, I'm doing this with the serverless framework and I [output the above data](https://github.com/sbstjn/serverless-stack-output) as an `.env` file.
Then as a separate CLI command `build` (webpack) and then `deploy` to s3.

What would be **amazing** would be a construct that would handle this all during `cdk deploy` 
Taking in the values of deployed assets and then firing the webpack build and then using the `s3deploy` construct to deploy assets. 

Would LOVE to work on this if someone thinks it's possible and might be able to point me in the direction. My

**Comment by mamaar** [comment]
Hi.
While it's not a plugin, this is how I have solved Webpack bundling during deployment: https://dev.to/mamaar/aws-cdk-4249

**Comment by moltar** [comment]
@jogold:

> synthesizing all the stacks and extracting the webpack:xxx metadata

Do you mind sharing this bit of the code?

Thanks.

**Comment by jogold** [comment]
> @jogold:
> 
> > synthesizing all the stacks and extracting the webpack:xxx metadata
> 
> Do you mind sharing this bit of the code?
> 
> Thanks.

This is issue is old and I stopped exploring with Webpack for the CDK. See `@aws-cdk/aws-lambda-nodejs` of the current recommended approach.

**Comment by alex-unikorny** [comment]
Happy new year!, Just to share my experience with that, I'm using a makefile that lists all my Typescript lambda projects and compiles with Webpack, so on my CDK code I'm pointing the generated lambda source code on dist/lambdas/lambdaName for example.

Structure of my CDK project:
```
cdk-project
├ package.json
├ makefile
├ cloud
|   ├── build-lambda.ts
├ src
|   ├── lambdas
|       ├── my-lambda-typescript-project
|              ├── webpack.config.js
```

You can invoke them adding a script into package.json like "build-lambdas": "make build-lambdas -j" getting the building process in parallel. This example was tested only on Mac systems, but I hope will be inspiring for someone.

makefile example:

```
# Lambda parent dir
build-lambdas: $(eval LAMBDA_BASE_DIR = $(shell echo $$PWD)/src/lambdas)
build-lambdas: $(eval DIRS = $(shell cd $(LAMBDA_BASE_DIR) && find $$PWD/* -type d -maxdepth 0 -execdir basename '{}' ';'))
# Trick to convert directory list to a readable variable
build-lambdas: $(eval lambda-targets = $(addprefix , $(DIRS)))
build-lambdas: $(lambda-targets)

.PHONY = $(lambda-targets)

$(lambda-targets):
	@cd ${LAMBDA_BASE_DIR}/$@ && echo "\033[94mBuilding Lambda $@\033[0m" && npm install && npx webpack
```

Regards!
