### ISSUE TITLE
(@aws-cdk/custom-resources): SecretString from AwsCustomResource in usable form

### ISSUE THREAD

**Issue by bravogolfgolf** [aws/aws-cdk#16207]
## :question: General Issue

```

const secretLookup = new cr.AwsCustomResource(this, 'secret-lookup', {
      onUpdate: {
        service: 'SecretsManager',
        action: 'getSecretValue',
        parameters: {
          SecretId: props.secretName,
        },
        region: props.central.region,
        assumedRoleArn: roleArn,
        physicalResourceId: cr.PhysicalResourceId.of(Date.now().toString()),
      },
      policy: cr.AwsCustomResourcePolicy.fromSdkCalls({resources: [secretArn]}),
    });
    const secretString = secretLookup.getResponseField('SecretString');

```

### The Question

I use the code above to get around the cross-account limitations of StringParameters.

The code above returns a SecretString that looks like this:

"{"randomText":"/];asdf(5;{ASDF=L%UuVxasDFHg`(:l","dbEndPoint":"dbid.abcdefghijkl.region.rds.amazonaws.com"}"

How do you get secretString from AwsCustomResource into a form so I can reference the individual fields like this?

secretString.dbEndPoint

### Environment

  - **CDK CLI Version  : 1.118.0**
  - **Framework Version: 1.119.0**
  - **Node.js Version: v14.16.0**
  - **OS: macOS Big Sur 11.5.2 (20G95)**
  - **Language (Version): TypeScript (3.9.7)**

### Other information

Right now the only solution I have now is inelegant:

const dbEndPoint = cdk.Fn.select(7,cdk.Fn.split('"', secretString));

**Comment by peterwoodworth** [comment]
Hey @bravogolfgolf,

The `getResponseField` method simply returns the response data for the SDK call as a string](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_custom-resources.AwsCustomResource.html#getwbrresponsewbrfielddatapath). Unfortunately, I don't think there's a more elegant solution available here by just using CDK constructs.

Let me know if you have any additional questions

**Comment by bravogolfgolf** [comment]
To get around this I created a CustomResource/CustomResourceProvider Construct that takes the SecretString and key. It returns the key's value.

```
exports.handler = async function (event) {
  const secretString = JSON.parse(event.ResourceProperties.secretString);
  const key = event.ResourceProperties.key;
  const value = secretString[key];
  return {
    Data: {
      Value: value.toString(),
    },
  };
};
```

While this is more elegant and less brittle (it does not depend on the order of keys in SecretString), it seems like there should be a corollary to Stack.toJsonString(obj, space?) that parses a token (in this case the SecretString returned from cr.AwsCustomResource) into an object.

**Comment by peterwoodworth** [comment]
Ah that is a better solution!

> it seems like there should be a corollary to Stack.toJsonString(obj, space?) that parses a token (in this case the SecretString returned from cr.AwsCustomResource) into an object.

I've never used this, and I can do some investigation on this today, but it looks like [getResponseFieldReference](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_custom-resources.AwsCustomResource.html#getwbrresponsewbrfieldwbrreferencedatapath) might do exactly that

**Comment by bravogolfgolf** [comment]
I spent some time looking into getResponseFieldReference, but haven't got anything working...you have any luck?

**Comment by peterwoodworth** [comment]
Hey @bravogolfgolf, I've been unable to work on this. My apologies. I'll try to give an update by the end of the week

**Comment by bravogolfgolf** [comment]
@peterwoodworth Thanks for looking into this. It would be great if there were a native CDK mechanism to parse the secretString returned rather than having to create a custom resource for this use case when I am retrieving Secrets across accounts.

For posterity: `randomText` is something I had to add to the secret because CDK requires `secretStringTemplate` and `generateStringKey` must be specified together. I never use `randomText`.

```
const newSecret = new Secret(this, 'new-secret', {
      generateSecretString: {
        excludePunctuation: true,
        generateStringKey: 'randomText',
        secretStringTemplate: JSON.stringify({
          key: secretValue.toString(),
        }),
      },
      secretName: `${this.stackName}NewSecret`,
    });
```

You can see this requirement if you try to create the Secret with the line: `generateStringKey: 'randomText',` commented out.

**Comment by peterwoodworth** [comment]
Ah I see. Thanks for explaining the random text @bravogolfgolf 

> It would be great if there were a native CDK mechanism to parse the secretString returned

I'm not sure how exactly we'd accomplish this, since the method you're using could return _any_ api call. Feel free to create a feature request for this though, maybe our SDEs can figure something out 😄
