### ISSUE TITLE
(ec2): support throughput option in EBS volume

### ISSUE THREAD

**Issue by jumic** [aws/aws-cdk#16213]
For EBS volumes with volume type GP3, the throughput in MiB/s can be configured. This is currently not supported in CDK.

Workaround: use escape hatches

### Use Case

Set custom value for throughput, impacts performance and pricing.

### Proposed Solution

The property is available in [ebs volume](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-ebs-volume.html#cfn-ec2-ebs-volume-throughput) and [launchtemplate blockdevicemaping](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-blockdevicemapping-ebs.html#cfn-ec2-launchtemplate-blockdevicemapping-ebs-throughput). It should be supported in both constructs.

Check if the property can be added to `EbsDeviceOptionsBase` or only to one of its subclasses (`EbsDeviceOptions` and `EbsDeviceSnapshotOptions`). Nothing specific is mentioned in the documentation.

Display a warning if throughput is defined for a volume type that does not support specifying a throughput. Display an error if a throughput value is specified that is [not supported](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-blockdevicemapping-ebs.html#cfn-ec2-launchtemplate-blockdevicemapping-ebs-throughput).

### Other

Originally mentioned as comment in issue #12020.

* [X] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by njlynch** [comment]
Thanks for the feature request!

We welcome community contributions! If you are able, we encourage you to [contribute](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md). If you decide to contribute, please start an engineering discussion in this issue to ensure there is a commonly understood design before submitting code. This will minimize the number of review cycles and get your code merged faster.

**Comment by jumic** [comment]
@njlynch I would propose the following implementation. Do you have any comments?
Could you please give me a short feedback to my questions? Thanks.

Add new property `throughput` (specified in MiB/s) to [`VolumeProps`](https://github.com/aws/aws-cdk/blob/6e2a3e0f855221df98f78f6465586d5524f5c7d5/packages/%40aws-cdk/aws-ec2/lib/volume.ts#L328) and [`EbsDeviceOptionsBase`](https://github.com/aws/aws-cdk/blob/6e2a3e0f855221df98f78f6465586d5524f5c7d5/packages/%40aws-cdk/aws-ec2/lib/volume.ts#L49).
In Construct LaunchTemplate, `throughput` can be used when a volume is created and when it is restored. I did a short test with LaunchTemplate in combination with `BlockDeviceVolume.ebsFromSnapshot()`. Therefore, it should be correct to add it to interface `EbsDeviceOptionsBase` which is used for creating and restoring volumes.
```ts
readonly throughput?: number;
```

Add validation in [`validateProps()`](https://github.com/aws/aws-cdk/blob/6e2a3e0f855221df98f78f6465586d5524f5c7d5/packages/%40aws-cdk/aws-ec2/lib/volume.ts#L643).
- Throw error if `throughput` is used for EbsDeviceVolumeType != GP3.
- Throw error if value is not in supported range (Minimum value of 125. Maximum value of 1000)

Add validation in [`synthesizeBlockDeviceMappings()`](https://github.com/aws/aws-cdk/blob/6e2a3e0f855221df98f78f6465586d5524f5c7d5/packages/%40aws-cdk/aws-ec2/lib/private/ebs-util.ts#L23).
- Throw error if `throughput` is used for EbsDeviceVolumeType != GP3. **Question**: Should this be an error? For `iops` only a warning is added if it is used for unsupported volume types. However, this behavior is not consistent to `validateProps()`.
- Throw error if value is not in supported range (Minimum value of 125. Maximum value of 1000). **Question**: Should this be validated? The valid ranges for `iops` are not validated in this method. Again, this behavior is not consistent to `validateProps()`.
- Throw error if `throughput` is used in property `BlockDeviceMapping` for EC2 instances. This is currently not supported (see https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/824).

Add unit test cases and create integration tests that show Volume and LaunchTemplate with `throughput` can be deployed.

**Comment by csumpter** [comment]
> Hey, i just stumbled upon this issue while looking for a way of defining the throughput of GP3 volumes. I understand from this PR that it's not currently supported via the `aws_ec2.BlockDeviceVolume.ebs` function.
> 
> Until this feature is merged, is there any workaround for defining it?

You can do something like:

```ts
    interface ExtendedEbsDeviceOptions extends autoscaling.EbsDeviceOptions {
      throughput: number;
    }

    const asg = new autoscaling.AutoScalingGroup(this, "example", {
      blockDevices: [{
        deviceName: "/dev/sda1",
        volume: autoscaling.BlockDeviceVolume.ebs(1, {
         ...
          volumeType: autoscaling.EbsDeviceVolumeType.GP3,
          throughput: 125,
        } as ExtendedEbsDeviceOptions),
      }],
      ...
    })
```

This extends the type to include `throughput` where it will becomes rendered as `Throughput` by the cdk as it transforms that property.

There are other ways to get the throughput property rendered out with the resource but this is probably the easiest.

**Comment by aldredb** [comment]
@csumpter I don't think the workaround works. This is my code:

```
export interface ExtendedEbsDeviceOptions extends EbsDeviceOptions {
    throughput: number;
}
```

```
blockDevices: [{
        deviceName: '/dev/xvda',
        volume: BlockDeviceVolume.ebs(3000, {
            deleteOnTermination: true,
            encrypted: false,
            iops: 16000,
            volumeType: EbsDeviceVolumeType.GP3,
            throughput: 1000,
          } as ExtendedEbsDeviceOptions),
      },
    ]
```

The `throughput` is not translated to CF template

**Comment by aldredb** [comment]
@csumpter Yep i used the 2.54.0 release. The `throughput` property is included in `aws_autoscaling.EbsDeviceOptionsBase` and `aws_ec2.VolumeProps`, but not [aws_ec2.EbsDeviceOptionsBase](https://github.dev/aws/aws-cdk/blob/9f41881be1cca31129078b7839dded480220f060/packages/%40aws-cdk/aws-ec2/lib/volume.ts#L42), which the static function [aws_ec2.BlockDeviceVolume.ebs](https://github.dev/aws/aws-cdk/blob/9f41881be1cca31129078b7839dded480220f060/packages/%40aws-cdk/aws-ec2/lib/volume.ts#L135-L136) takes as an argument.

**Comment by csumpter** [comment]
> 

@aldredb 

You are correct that the `throughput` property is missing from `EbsDeviceOptionsBase`. Let's add a PR for that addition as it was not caught in the PR review, and I did not see that extra static method at the time I was writing the original PR.

In the meantime are you trying to create a EC2 instance in the example you gave?

**Comment by aldredb** [comment]
@csumpter 

Yes. I'm trying to use this: https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ec2.Instance.html#blockdevices

**Comment by csumpter** [comment]
> @csumpter
> 
> Yes. I'm trying to use this: https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ec2.Instance.html#blockdevices

@aldredb I don't believe you can set a `Throughput` property on ebs block devices - see the CFN docs here: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-blockdev-template.html

**Comment by tmokmss** [comment]
I also stumbled on this today. Here's the workaround:

```ts
const instance = new Instance(this, 'Instance', {
  // omitting other required properties
  blockDevices: [
    {
      deviceName: '/dev/xvda',
      volume: ec2.BlockDeviceVolume.ebs(100, {
        volumeType: ec2.EbsDeviceVolumeType.GP3,
      }),
    },
  ],
});
(instance.node.defaultChild as CfnResource).addPropertyOverride("BlockDeviceMappings.0.Ebs.Throughput", 200);
```

You can do similarly also for launch templates.

```ts
const launchTemplate = new ec2.LaunchTemplate(this, 'LaunchTemplate', {
  // omitting other required properties
  blockDevices: [
    {
      deviceName: '/dev/xvda',
      volume: ec2.BlockDeviceVolume.ebs(100, {
        volumeType: ec2.EbsDeviceVolumeType.GP3,
      }),
    },
  ],
});
(launchTemplate.node.defaultChild as CfnResource).addPropertyOverride("LaunchTemplateData.BlockDeviceMappings.0.Ebs.Throughput", 200)
```

But I strongly hope L2 implementation for this property...
