### ISSUE TITLE
(pipelines): Ability to create testing stage with setup and teardown of resources

### ISSUE THREAD

**Issue by 0xjjoyy** [aws/aws-cdk#16222]
Request is for the ability to create a stage with testing specific hooks that will teardown any stacks created at the end of the stage, regardless if the stage succeeds.

Today, we need to use the pre and post codebuild hooks to manually provision stacks that are needed to create testing resources for integration tests. However, if a stage errors, then the post hooks will not run and the testing resources stay active.

### Use Case

Native CDK support for setup and teardown of stacks that create resources for integration tests. The stacks that creating the testing resources should initiate a teardown of any created stacks, regardless if the stage has errors.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
I agree that it's a good idea, but the realities of CodePipeline are that it's not possible. Sorry.
