### ISSUE TITLE
aws-kinesis: Type Duration is not assignable to type Duration

### ISSUE THREAD

**Issue by Alchieus** [aws/aws-cdk#16224]
Type 'import("node_modules/@aws-cdk/core/lib/duration").Duration' is not assignable to 
type 'import(/node_modules/@aws-cdk/aws-kinesis/node_modules/@aws-cdk/core/lib/duration").Duration'.
  Types have separate declarations of a private property 'amount'

### Reproduction Steps

import * as cdk from "@aws-cdk/core";
import * as Kinesis from "@aws-cdk/aws-kinesis";
const stream = new Kinesis.Stream(this, "amp-DirectMailBatch-Stream", {
      streamName: "amp-DirectMailBatch-Stream",
      shardCount: 10,
      retentionPeriod: cdk.Duration.hours(24) // can't set duration because of a type mismatch
    });

### What did you expect to happen?
I would expect Kinesis to reference Duration from Core, and not define it's own Duration internally.

### Environment

  - **CDK CLI Version  :** 1.119.0 (build 2921d64)
  - **Framework Version:** "@aws-cdk/aws-kinesis": "1.119.0",
  - **Node.js Version:** v14.16.0
  - **OS               :** windows 10
  - **Language (Version):** tsc -v:  version 4.1.3

### Other

--- 

This is :bug: Bug Report

**Comment by straygar** [comment]
This type of error (`@aws-cdk/aws-x/Foo version is not compatible with @aws-cdk/aws-y/node_modules/@aws-cdk/aws-x/Foo`) occurs when your CDK dependencies in `package.json` are not the same version.

Can you check whether this is the case? If so - just lining them up, and running `npm i` should solve the issue.
