### ISSUE TITLE
(aws-route53-targets): Cannot use SpecRestApi to create ApiGateway target for ARecord

### ISSUE THREAD

**Issue by AlexStasko** [aws/aws-cdk#16227]
I'm trying to use the `SpecRestApi` to create API Gateway based on the OpenAPI document. To have the ability to use Custom Domain Name I need to create `ARecord`, but `RecordTarget.fromAlias(new ApiGateway(apiGW))` accepts only `RestApi` class.

![image](https://user-images.githubusercontent.com/22001795/130836474-47de380a-f793-4baf-b18d-c36faca17df3.png)

### Reproduction Steps
Code snipet:
```
    const apiGW = new SpecRestApi(this, 'RestApi', {
      apiDefinition: ApiDefinition.fromAsset('open-api.yaml'),
    });
    const record = new ARecord(this, 'Record', {
      zone: HostedZone.fromHostedZoneAttributes(this, 'Route53HostedZone', {
        zoneName: dnsZoneName,
        hostedZoneId: dnsHostedZoneId,
      }),
      target: RecordTarget.fromAlias(new ApiGateway(apiGW)),
    });
```

### What did you expect to happen?

I'm able to create `ARecord` with `SpecRestApi`

### What actually happened?

The compiler shows me error `Argument of type 'SpecRestApi' is not assignable to parameter of type 'RestApi'.`

### Environment

  - **CDK CLI Version  : 1.119.0**
  - **Framework Version: 1.119.0**
  - **Node.js Version: 14.17.0** 
  - **OS               : Ubuntu**
  - **Language (Version): TypeScript (4.3.5)** 

### Other
Suggestion for fix:
on this [line](https://github.com/aws/aws-cdk/blob/b1d69d7b06cd2a2ae8f578e217bdf7fef50a0163/packages/%40aws-cdk/aws-route53-targets/lib/api-gateway-domain-name.ts#L29) need to change `apig.RestApi` to `apig.RestApiBase`

--- 

This is :bug: Bug Report

**Comment by njlynch** [comment]
Thanks for the report, @AlexStasko !

I agree with your suggested fix. In addition, we should add a test to the corresponding [test file](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-route53-targets/test/apigateway-target.test.ts) with a test case using a `SpecRestApi`.

Given the traction this has already gotten, I'm marking this as a `p1`. We welcome community contributions! If you are able, we encourage you to [contribute](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md).
