### ISSUE TITLE
aws-eks: expose max-pods flag for node groups

### ISSUE THREAD

**Issue by trondhindenes** [aws/aws-cdk#16231]
When using CNI Custom Networking (https://docs.aws.amazon.com/eks/latest/userguide/cni-custom-network.html) the current max-pods value is wrong, since the node "loses" an ENI.

There's currently no way to set the max-pods flag when provisioning a nodegroup using CDK. It would be awesome to have this added, as cdk would be the perfect place to perform lookups/calculation to set the correct number 

### Use Case
Provisioning nodes with custom networking using CDK currently results in nodes with a too high max-pods setting, which causes pod scheduling failures.

### Proposed Solution
Implement a "maxPods" int parameter on nodegroups, which is added to the userdata script

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by otaviomacedo** [comment]
Hi, @trondhindenes. Thanks for raising this request. Would you mind expanding on the proposed solution and include an example of the API you would like to use?

**Comment by trondhindenes** [comment]
I'm afraid I don't know too much about the internals of cdk eks. If you create a custom launchconfig I believe you can set this parameter there for the kubelet to pick up. However if CDK nodegroup sits on top of the cloudformation nodegroup resource, I guess there isn't any way to set this.

**Comment by markussiebert** [comment]
Our first attempt was also using the max pods parameter of the bootstrap call. But once you start using several instance types / spot instances this isn't handy anymore. So we create our own [eni-max-pods.txt ](https://github.com/awslabs/amazon-eks-ami/blob/master/files/eni-max-pods.txt)and with this overwrite the one provided by the eks ami. The benefit: this works with mixed instance types in one nodegroup.

So my idea would be to calculate the eni-max-pods for all instances, and "echo" it it via userdata to the eni-max-pods.txt on the server. (Thats what we do and it works...). 
So I can imagine adding a property like:

```ts
eniMaxPodsOverride: {
  eniOffset: -1,  // how much enis could not be used?
  ipV4Offset: 2,  // how much pods don't need an ip address because running on host network
}
```
what do you think @otaviomacedo

**Comment by trondhindenes-nomono** [comment]
any movement here? We're wasting a lot of money on underutilized nodes since max-pods are set at 20 regardless of the actual capacity of our nodes

**Comment by trondhindenes** [comment]
any movement here? We're wasting money on underutilized nodes since max-pods are set at 20 regardless of the actual capacity of our nodes.
I'd be fine with setting max-pods "manually", I'm just looking for a way to set it without having to switch to self-managed node groups.
