### ISSUE TITLE
aws_ec2: Instance logical identifier could not be resolved

### ISSUE THREAD

**Issue by tomas-sezima** [aws/aws-cdk#16233]
Setting `user_data_causes_replacement` attribute of `aws_ec2.Instance` construct to "true" causes underlying logical resource identifier to be suffixed with user data hash. Such identifier could, however, not be reconstructed using Stack's `get_logical_id` method (see [documentation](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.core/Stack.html#aws_cdk.core.Stack.get_logical_id)).

### Reproduction Steps

Create EC2 instance, requesting replacement on user data update:

```
test = aws_ec2.Instance(
  scope=self,
  id="Test",
  vpc=aws_ec2.Vpc(self, "VPC"),
  machine_image=aws_ec2.AmazonLinuxImage(),
  instance_type=aws_ec2.InstanceType.of(
    InstanceClass.BURSTABLE3,
    InstanceSize.SMALL
  ),
  user_data_causes_replacement=True
)
```

Resolve logical resource identifier using Stack's `get_logical_id` method:

```
stack = aws_cdk.core.Stack.of(test)
identifier = stack.get_logical_id(test.instance)
```

### What did you expect to happen?

Yielded `idenfier` matches resource ID, as found in synthesized CloudFormation template.

### What actually happened?

Acquired `identifier` is not suffixed with user data hash; differs from CloudFormation hosted EC2 instance resource ID.

### Environment

  - **CDK CLI Version  : 1.117.0**
  - **Node.js Version: v16.3.0**
  - **OS               : Windows 10**
  - **Language (Version): Python 3.7.3**
--- 

This is :bug: Bug Report

**Comment by peterwoodworth** [comment]
Thanks for reporting this @tomas-sezima, I'm going to close this in favor of the issue you linked. Feel free to leave a comment there with what you've found!
