### ISSUE TITLE
(apigateway): IntergrationOptions cannot set a VpcLink as a stage-variable

### ISSUE THREAD

**Issue by TomBonnerAtDerivitec** [aws/aws-cdk#16239]
When creating an Integration with VpcLink in C# it requires a VpcLink type. However [docs online](https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-api-with-vpclink-cli.html) show that this can be a stage-variable.

### Use Case

We deploy a single API with multiple stages that use stage-variables to set the target environment data flows to.

### Proposed Solution

Update IntegrationOptions to also include a field for VpcLinkId which is allowed to be a variable.

### Other

* [n] :wave: I may be able to implement this feature request
* [n] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by sats17** [comment]
@TomBonnerAtDerivitec do you find any solution for this?

**Comment by sats17** [comment]
Tried this in method integration options and it worked with stage variables.
`
vpcLink: apiGateway.VpcLink.fromVpcLinkId(this, "ImportedVpcLink", "${stageVariables.vpcLinkId}"),
`
Noticed in generated cloud formation that it is not actually importing vpcLink, but just adding this "${stageVariables.vpcLinkId}" against the vpcLink variable.
