### ISSUE TITLE
(Snyk): CodePipeline integration with Snyk

### ISSUE THREAD

**Issue by s1mrankaur** [aws/aws-cdk#16232]
How to use CDK to have Snyk as a target action that is now available as an Action directly in CodePipeline as shown here: https://snyk.io/blog/automate-vulnerability-scanning-in-aws-codepipeline-with-snyk/

**Comment by sholtomaud** [comment]
was there a cdk-sample that documented how to automate this integration with auto key/token regeneration?

**Comment by sholtomaud** [comment]
KickinMhl says "@aws-cdk/aws-codepipeline-actions doesn't seem to have a method to create the action that I am able to create in the console." 
https://stackoverflow.com/questions/71257220/codepipeline-snyk-action-via-cdk

Can we have a CDK action method to match the aws console action method?

**Comment by skinny85** [comment]
@sholtomaud you should be able to create your own Action class that implements this integration. Look for details how to do it in this issue: https://github.com/aws/aws-cdk/issues/2516.

**Comment by sholtomaud** [comment]
Rather than writing a custom action class, is there an AWS native way to do DevSecOps? Snyk looks great but I prefer using 100% aws native options so is there a native option that replaces Snyk that I'm not aware about?
