### ISSUE TITLE
(aws_elasticsearch): Domain fails to create with a permissions error

### ISSUE THREAD

**Issue by Jon-AtAWS** [aws/aws-cdk#16243]
### Reproduction Steps

cdk deploy for the following stack:

### Environment

  - **CDK CLI Version  : 1.119.0 (build 2921d64)
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :** MacOS 10.14.6
  - **Language (Version):** 

### Other

--- 

This is :bug: Bug Report

**Comment by melodyyangaws** [comment]
+1  same issue when deploying the sample [CDK stack](https://github.com/aws-samples/amazon-elasticsearch-service-monitor/blob/main/monitoring_cdk/monitoring_cdk_stack.py)

**Comment by peterwoodworth** [comment]
Have both of you created an [SLR](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-elasticsearch-readme.html#a-note-about-slr)?

**Comment by prashanttct07** [comment]
This issue was related to SLR (Service Linked Role). It has been fixed and stack creation is working fine. It can be closed 
@Jon-AtAWS
