### ISSUE TITLE
(events): Rules are created incorrectly for resources that don't belong to its Stack environment

### ISSUE THREAD

**Issue by skinny85** [aws/aws-cdk#16245]
We allow resources to be imported from a different environment than the Stack they are imported to. Something like:

```ts
import * as cdk from '@aws-cdk/core';
import * as ecr from '@aws-cdk/aws-ecr';

const app = new cdk.App();
const stack = new cdk.Stack(app, 'Stack1', {
  env: { region: 'region1', account: 'stack-account' },
});
const repo = ecr.Repository.fromArn(stack, 'Repo',
  'arn:aws:ecr:us-west-2:012345678901:repository/my-repo');
```

Above, `repo` belongs to a different environment than `stack`.

However, when we use a CloudWatch Events Rule-creating API of a resource like that, like this:

```ts
repo.onCloudTrailImagePushed('SourceEventRule', {
  target: someTargetThatBelongsToStack,
});
```

What happens is that the `Rule` is created in the environment of the `stack`, and **not** the environment of the source (`repo` in this case)!

This means [this logic](https://github.com/aws/aws-cdk/blob/cdee1af03c34a1c08988e672bae6edc2538a8877/packages/%40aws-cdk/aws-events/lib/rule.ts#L176-L190) of determining whether a given Target is cross-environment or not fails for this case.

This was noticed by @fasatrix in https://github.com/aws/aws-cdk/issues/10901#issuecomment-905940853.

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
It's because we're talking about the SOURCE that's in a different account, not the TARGET.

All `onSomething()` methods should be throwing an error for resources in a different `env` from the containing `Stack`. It just cannot be done. More generally, I think we have this issue at various places.

**Comment by fasatrix** [comment]
> It's because we're talking about the SOURCE that's in a different account, not the TARGET. The events the Rule would trigger on are just emitted somewhere completely different.
> 
> All `onSomething()` methods should be changed to throw an error for resources in a different `env` from the containing `Stack`. It just cannot be done.

@rix0rrr thanks for the explanation. However we made that working implementing the following on the stack account. On the ECR account we only have a CloudTrail enabled. 

```
   new CfnEventBusPolicy(this, `EventBusPolicy-${id}`, {
      statementId: `EventBusPolicy-${id}`,
      statement: {
        Effect: 'Allow',
        Action: 'events:PutEvents',
        Resource: EventBus.fromEventBusName(this, `AccountEventBus-${id}`, 'default').eventBusArn,
        Principal: {
          AWS: `arn:aws:iam::${<account where the ECR registry is - different from the stack>}:root`,
        },
      },
    });
```

**Comment by fasatrix** [comment]
@rix0rrr  I saw you guys moved this to a P2. 

As you mentioned above, Is the plan to throw an exception for resources that will be created in  environments different from the containing Stack? 
I hope no as this will break our current implementation and I'd like to be rethought if possible at least for ECR related resources. 
We have an AWS Account that functions as `central` for all other accounts. We use it for all things common such as shared ECR , share KMS , shared anything really.  I cannot be 100% certain but I have a feeling that most organisations could be functioning in a very similar way  and have a similar use case.

Related to this issue we have implemented a workaround which is :

1) `Account A` (hosting ECR)  we created a rule that moves image related events on Account B bus (Hosting CopdePipeline/CodeDeploy)
2) `Account B` (Hosting CopdePipeline/CodeDeploy) we created a bus Policy  like the above to allow events from Account A to be written o this default bus
3) `Account B`  we have an event rule that is listening on ECR events put on this bus  (point 4) and as action will l trigger a codePipeline.

**Comment by skinny85** [comment]
@fasatrix one simple fix that you might try doing is importing the ECR Repository into a Stack that lives in account `A` (instead of into a Stack that lives in account `B`, as you're doing now).

I _think_ that will be enough for CDK to correctly create the bus Policies for you.

**Comment by fasatrix** [comment]
@skinny85 Thanks for your answer. I am not sure I got what you mean but to clarify I have made a diagram.

Context:

1. Several different Application Squads are building and pushing images to a common ECR services under different repos hosted in `Account A` (which belongs to a `DevOps/Infrastructure squad` and hosts all common things Including ECR as a service)
2. These squads own one or more AWS Accounts (Test, PreProd, Prod etc.), and each one of them has codePipeline/CodeDeploy stack with blue/green ECS deployment, deploying images pushed in Step 1 (This is built, tested and pushed with a common Jenkins CI).  After the first Bluegreen deployment (in which a cross account role allows images to be fetched from ECR `Account A`), squads wants to  listen to images changes and then  trigger and auto-deployment if that happens.

To make the above happen we have created the following process:

1. Account A (hosting ECR) a rule that moves image related events to to other Accounts ' bus
2. For each squad  Account (CopdePipeline/CodeDeploy) a bus Policy like the above, trusts account `Account A` events to be written on each of this Account default bus (Trusted principal policy)
3. For each squad Account an event rule has been created that will listen to ECR PUT/Push events that were pushed to this Account bus (by an event Rule in point 1)  and as a action it will l trigger a codePipeline deploy action

This works well we are just worried that if the change goes ahead it will break this current solution and also if there a simpler way to do this.

![image](https://user-images.githubusercontent.com/16127426/133179016-5f69b8ca-a0f7-4d1f-a249-dd3f2a2c976d.png)

**Comment by skinny85** [comment]
I'm saying that, in your code, you're now doing:

```ts
      const imageRepository = Repository.fromRepositoryArn(
        this,
        'ImageRepository',
        `arn:aws:ecr:ap-southeast-2:<MyAWSAccount>:repository/${imageRepoName}`,
      );
```

where `this` belongs to a Stack that is in a different account than `<MyAWSAccount>`.

If you instead imported `imageRepository` into a Stack that belonged to `<MyAWSAccount>`, I _believe_ the bug this ticket has been created will not affect you, and CDK will handle all of the bus permissions for you.

**Comment by shylaharild** [comment]
Is there a solution with CDK on this? I am still experiencing the same issue and my stack scenario is the same as @fasatrix.

I am using CDK version `2.53.0`
