### ISSUE TITLE
(bootstrapping): StagingBucket triggers SecurityHub warning

### ISSUE THREAD

**Issue by ahammond** [aws/aws-cdk#16249]
I want to start using CDK on an account. I ran `npx cdk bootstrap` and it failed because I don't have enough permissions (yet). It left behind a bucket, and the bucket triggered a SecurityHub warning "S3.8 S3 Block Public Access setting should be enabled at the bucket-level"

### What did you expect to happen?

I'm hoping the StagingBucket will be reasonably locked down.

### What actually happened?

The StagingBucket isn't blocking public access.

### Environment

  - **CDK CLI Version  :** v2.0.0-rc.19
  - **Framework Version:** v2.0.0-rc.19
  - **Node.js Version:** v14.17.5
  - **OS               :** MacOS 11.5.2 (20G95)
  - **Language (Version):** TypeScript (4.3.5)

--- 

This is :bug: Bug Report

**Comment by peterwoodworth** [comment]
Hey @ahammond, sorry for the long response time.

I'm not entirely sure what's happening here. Could you please clearly describe the steps you took and the results that followed from those steps? Thanks!
