### ISSUE TITLE
(aws_cdk.aws_ec2): Ability to get stable list of n subnets

### ISSUE THREAD

**Issue by SamStephens** [aws/aws-cdk#16250]
Apologies if there is already a way to do this.

I need a way to select a given number of subnets and know I'll always get the same subnets. I don't want to have to make the consumers of these subnets have to know exactly which subnets are available to achieve this.

### Use Case

For putting an Elasticsearch domain in a VPC, I need to have a certain number of subnets available depending on how many instances are in the domain.

For example, if I have 2 data nodes, I need to specify two subnets.

I can do something like (in Python):

            vpc_subnets=aws_ec2.SubnetSelection(
                subnets=vpc.private_subnets[:2]
            )

To get two subnets from the list of private subnets. However, as far as I can see, I have no ordering guarantee from vpc.private_subnets. So I have the danger at any point that the ordering of the subnets may change, and my Elasticsearch domain end up moving subnets unintentionally.

### Proposed Solution

What I'd really like to be able to do is say something like.

            vpc_subnets=aws_ec2.SubnetSelection(
                subnet_type=SubnetType.PRIVATE,
                subnet_count=2,
            )

And know that as long as the list of subnets matching my selection criteria does not change, I'll always get the same two subnets.

**Comment by indrora** [comment]
> However, as far as I can see, I have no ordering guarantee from vpc.private_subnets 

Correct. If you require specific subnets, you can identify them with `filter(...)` or through static description.

You can also have the CDK generate new VPC subnets purely for your ElasticSearch instances, which is a more suggested route, that way you can guarantee their configuration. 

I'm marking this response-requested to make sure this is still an active issue.

**Comment by SamStephens** [comment]
Commenting to keep this issue open.

@indrora the thing here is that I don't require specific subnets, and I don't want or need to create subnets specifically for my Opensearch instances.

In my case, my VPC only has one set of private subnets; one per AZ in my region. If my VPC has three private subnets, one per AZ, and I want to get a stable set of two subnets from the VPC, I'm going to have to explicitly list which AZs I want the two subnets to belong to. That seems a nasty violation of encapsulation, and is going to open me to problems in the future, if say for example I want to start deploying my stack in another region.

My current workaround is

```
            vpc_subnets=[aws_ec2.SubnetSelection(
                # One availability zone for one data node
                availability_zones=sorted(vpc.availability_zones)[:2],
                subnet_type=aws_ec2.SubnetType.PRIVATE_WITH_NAT,
                one_per_az=True,
            )],
```

Which works, and keeps me independent of the specific list of AZs, but has the problem that as I use this pattern more, my resources will not be evenly distributed through my AZs (as I will over-use the AZs that appear first in the sort order).

**Comment by peterwoodworth** [comment]
> However, as far as I can see, I have no ordering guarantee from vpc.private_subnets. So I have the danger at any point that the ordering of the subnets may change, and my Elasticsearch domain end up moving subnets unintentionally.

I'm not sure why this would occur, could you expand on this?

**Comment by SamStephens** [comment]
> > However, as far as I can see, I have no ordering guarantee from vpc.private_subnets. So I have the danger at any point that the ordering of the subnets may change, and my Elasticsearch domain end up moving subnets unintentionally.
> 
> I'm not sure why this would occur, could you expand on this?

If I say `vpc.private_subnets[:2]`, I select the first two subnets `vpc.private_subnets` returns. However, without an ordering guarantee, it's possible that the ordering of the subnets `vpc.private_subnets` would change, which would mean `vpc.private_subnets[:2]` would return two different subnets, resulting in an update to the subnets my Elasticsearch domain has instances in.

As to why the ordering of `vpc.private_subnets` would change, without an ordering guarantee, I have to assume the order could change for any reason whatever. Possibly the way the list of subnets is generated is non-deterministic. Possibly the ordering depends on API behavior that is not guaranteed, and could change in future. Possibly the CDK team will find a more efficient way to generate this list that changes the ordering - something they are free to do as the ordering is not specified as part of the API contract.

Without an ordering guarantee, the ordering of the subnets `vpc.private_subnets` is an implementation detail, and I have to assume that I cannot rely on it being stable.

What I *really* want here:

* Is a construct allowing me to get N subnets matching certain criteria;
* For the N subnets chosen from the subnets that match my criteria to be random (so that my different Opensearch clusters are distributed across the subnets that match my criteria - that they're not concentrated on subnets at the beginning of the list);
* That once a set of subnets are chosen (e.g. after the first successful deployment), the set of subnets then is stable as long as the criteria doesn't change.

What I want to avoid is a world where I have to explicitly choose AZs for each of my Opensearch clusters to ensure they're not all in the same two AZs.

**Comment by peterwoodworth** [comment]
Thanks for the response @SamStephens, however this doesn't exactly clear up for me why you think there's not an ordering guarantee here. Is there somewhere in our docs that states this? Have you experienced the order changing yourself? Is this specifically when looking up a VPC, creating one in the same stack, or regardless of how it was created?

**Comment by SamStephens** [comment]
> Thanks for the response @SamStephens, however this doesn't exactly clear up for me why you think there's not an ordering guarantee here. Is there somewhere in our docs that states this? Have you experienced the order changing yourself? Is this specifically when looking up a VPC, creating one in the same stack, or regardless of how it was created?

"Is there somewhere in our docs that states this?" The reverse. The documentation does not state that the ordering is guaranteed, therefore it is not part of the specified behavior of `private_subnets`, therefore I cannot rely on it.

**Comment by peterwoodworth** [comment]
Thanks for clearing this up. The ordering should be consistent, unless you make a change that would make the ordering change. This would happen if you adjust the configuration of your Vpc in some obvious ways that would cause a change, but it could also happen if the [context](https://docs.aws.amazon.com/cdk/v2/guide/context.html) were to change. For a VPC created within your stack, it will fetch the availability zones based on the region your stack is in, and it will store them in `cdk.context.json`. Similarly, if you look up a Vpc, the subnets will be looked up and stored in `cdk.context.json`. Once context is stored here, it will not change unless you directly [manage the context](https://docs.aws.amazon.com/cdk/v2/guide/context.html#context_viewing)

I don't believe there's any other scenario where the ordering would change - it's all under user control

**Comment by SamStephens** [comment]
> I don't believe there's any other scenario where the ordering would change - it's all under user control

You're missing my point here. It is the case with the current CDK implementation that the ordering should be consistent, unless I make a change that would make the ordering change. But these are details of the **current implementation**. Unless those ordering guarantees are actually part of the documentation, the CDK is free to change in a way that would change that ordering, and needs to be free to change undocumented behavior.

**Comment by peterwoodworth** [comment]
One of the tenets of CDK apps is that given the same source, they will always produce the same output. If we make a change between versions that would change output like this, it would break that existing contract and we would fix it ASAP. That is our guarantee when it comes to this implementation. If you find this to not be the case, then please create an issue for us.

I've [created a PR](https://github.com/aws/aws-cdk/pull/25446) which explicitly states when AZs will be looked up and stored in context. This should help prevent anyone from making mistakes that would cause the ordering here to change

**Comment by SamStephens** [comment]
> One of the tenets of CDK apps is that given the same source, they will always produce the same output. If we make a change between versions that would change output like this, it would break that existing contract and we would fix it ASAP. That is our guarantee when it comes to this implementation. If you find this to not be the case, then please create an issue for us.
> 
> I've [created a PR](https://github.com/aws/aws-cdk/pull/25446) which explicitly states when AZs will be looked up and stored in context. This should help prevent anyone from making mistakes that would cause the ordering here to change

@peterwoodworth are these tenets documented anywhere? The closest I've come to finding tenets is https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md, which does not mention that tenet.

**Comment by peterwoodworth** [comment]
Hmmm yeah I can't find anywhere where we are _clearly_ publicly stating this. In the [best practices](https://docs.aws.amazon.com/cdk/v2/guide/best-practices.html) page where we describe managing context, we state this:

> Determinism is key to successful AWS CDK deployments. An AWS CDK app should have essentially the same result whenever it is deployed to a given environment.

But I'm not exactly sure what "essentially the same" is supposed to imply here. Since this is in the section relevant to context, I am assuming "essentially the same" means except for the values fetched by context, which is what I was saying earlier in this thread. However, this isn't super clear on what it specifically means, and it's also not in a very visible place either, so I'm not sure it grants you much comfort here.

**Comment by SamStephens** [comment]
> 

@peterwoodworth as I reread this, I don't think this section is documenting CDK behavior. It's talking to us as users about our best practices, that we need to ensure our CDK applications are deterministic, and commit cdk.context.json and use context providers to facilitate the required determinism.

If we knew that `privateSubnets` and similar methods drew on context, we'd be safe relying on that caching preserving ordering. But it appears context is only used for VPC objects generated from `VPC.fromLookup`.

It seems that manual usage of context could actually solve my problem though, using context to persist the original random selection of subnets.
