### ISSUE TITLE
No environments were found when selecting across [\xxxxxxxxxx/eu-central-1\] (available: yyyyyyyy/eu-central-1)

### ISSUE THREAD

**Issue by vtaseski** [aws/aws-cdk#1625]
When i try **cdk bootstrap account/region,** I get 
Removing outdir /tmp/cdkCUQx9Z
Stack name not specified, so defaulting to all available stacks: myStack
No environments were found when selecting across [\xxxxxxxxxx/eu-central-1\] (available: yyyyyyyy/eu-central-1)
Error: No environments were found when selecting across [\xxxxxxxxxxx/eu-central-1\] (available: yyyyyyyy/eu-central-1)
    at Object.globEnvironmentsFromStacks (/codebuild/output/src276023298/src/node_modules/aws-cdk/lib/api/cxapp/environments.ts:17:11)
npm ERR! code ELIFECYCLE

**Comment by RomainMuller** [comment]
It looks like your app's stacks belong to a different account (assuming that is what you represent with `xxxxxxxxxxxx` and `yyyyyyyyyyyy`). The toolkit will only bootstrap environments (account/region pairs) that are used in your application.

**Comment by jderose9** [comment]
If anyone else runs across this, make sure you are passing your profile when running cdk boostrap, as bootstrap writes to an s3 bucket in that account.

```
cdk bootstrap aws://123456789/us-east-1 --profile myprofile
```

**Comment by optinirr** [comment]
This still doesn't work for me.
