### ISSUE TITLE
(stepfunctions-tasks): LambdaInvoke - explicit null is not passed to lambda when using

### ISSUE THREAD

**Issue by TomasChmelik** [aws/aws-cdk#16253]
When I try to pass `null` as some parameter of a lambda, it gets removed from resulting task's parameters.

It might have same result for javascript lambdas, but in Python there is a difference between key not being in input event and key being there with value `null` (or `None` in Python's case).

This issue can be worked around by adding additional checks in the lambda, but that would add additional step needed for migration to CDK.

### Reproduction Steps
```python
from aws_cdk import aws_lambda
from aws_cdk import aws_stepfunctions
from aws_cdk import aws_stepfunctions_tasks


some_lambda = aws_lambda.Function.from_function_arn(scope, 'SomeLambda', 'arn:aws:lambda:eu-central-1:123456789:function:some-lambda')

aws_stepfunctions_tasks.LambdaInvoke(
    scope,
    'Lambda',
    lambda_function=some_lambda,
    payload=aws_stepfunctions.TaskInput.from_object({
        'nullParameter': None,
        'notNullParameter': 'not null'
    }),
    payload_response_only=True,
    retry_on_service_exceptions=False
)
```

### What did you expect to happen?
```json
{
    "Type": "Task",
    "Resource": "arn:aws:lambda:eu-central-1:123456789:function:some-lambda",
    "Parameters": {
        "nullParameter": null,
        "notNullParameter": "not null"
    }
}
```

### What actually happened?
```json
{
    "Type": "Task",
    "Resource": "arn:aws:lambda:eu-central-1:123456789:function:some-lambda",
    "Parameters": {
        "notNullParameter": "not null"
    }
}
```

### Environment

  - **CDK CLI Version  :1.118.0**
  - **Framework Version:???**
  - **Node.js Version:v15.14.0**
  - **OS               :Ubuntu 18.04.5 LTS**
  - **Language (Version):Python 3.7.4**

### Other

--- 

This is :bug: Bug Report

**Comment by TomasChmelik** [comment]
Typescript has `null` and `undefined` which are not strictly equal, so you could use one of them to specify that property is not there (probably `undefined`, since when you try to access property on object which is not there, you will also get an `undefined`) and other one for `null` valued property.

**Comment by BenChaimberg** [comment]
Ah, my bad, glazed over the value in particular. I believe it is this condition within `renderObject` that needs to be fixed. Only `undefined` should be ignored, `null` should be returned.

https://github.com/aws/aws-cdk/blob/d5ca419448e84f0cbb25dbd90d48fb4c407ede5c/packages/%40aws-cdk/aws-stepfunctions/lib/json-path.ts#L108-L109

**Comment by readybuilderone** [comment]
Hi @BenChaimberg , I would like to try to solve this problem, I wonder if you mind?

**Comment by BenChaimberg** [comment]
Please go ahead! We are always happy to take contributions.

**Comment by kaizen3031593** [comment]
@readybuilderone are you still planning on submitting a PR to fix this bug?

**Comment by jaresuth** [comment]
@kaizen3031593 - I am actively working on a fix for this.  Can you assign this issue to me?

**Comment by kaizen3031593** [comment]
@jaresuth are you still working on this?

**Comment by fab-mindflow** [comment]
Bump. Any news on this?
We are also facing the same issue, not able to distinguish `null` from `undefined`.

**Comment by krish00back** [comment]
Is this fixed? We also facing this issue.

**Comment by gakinson** [comment]
We are experiencing this as well.

**Comment by wancaibida** [comment]
I faced a similar error when creating a pass state with null values. A quick solution is using `sfn.JsonPath.stringToJson("")` instead of `null`

```
        const passStateStoreItemLastEvaluatedKey = new sfn.Pass(this, `${resourcePrefix}-pass-store-item`, {
            parameters: {
                "Count.$": "$.Count",
                "EmailResult.$": "$.EmailResult",
                "projectId.$": "$.projectId",
                "ItemResult": {
                    "LastEvaluatedKey": sfn.JsonPath.stringToJson("")
                },
                "walletAddress.$": "$.walletAddress",
                "networkType.$": "$.networkType"
            },
            comment: "Transform store email result"
        });
```

**Comment by mRamzii** [comment]
> I faced a similar error when creating a pass state with null values. A quick solution is using `sfn.JsonPath.stringToJson("")` instead of `null`
> 
> ```
>         const passStateStoreItemLastEvaluatedKey = new sfn.Pass(this, `${resourcePrefix}-pass-store-item`, {
>             parameters: {
>                 "Count.$": "$.Count",
>                 "EmailResult.$": "$.EmailResult",
>                 "projectId.$": "$.projectId",
>                 "ItemResult": {
>                     "LastEvaluatedKey": sfn.JsonPath.stringToJson("")
>                 },
>                 "walletAddress.$": "$.walletAddress",
>                 "networkType.$": "$.networkType"
>             },
>             comment: "Transform store email result"
>         });
> ```

Yup having the same issue here, nice workaround !

**Comment by morrijm4** [comment]
> > I faced a similar error when creating a pass state with null values. A quick solution is using `sfn.JsonPath.stringToJson("")` instead of `null`
> > ```
> >         const passStateStoreItemLastEvaluatedKey = new sfn.Pass(this, `${resourcePrefix}-pass-store-item`, {
> >             parameters: {
> >                 "Count.$": "$.Count",
> >                 "EmailResult.$": "$.EmailResult",
> >                 "projectId.$": "$.projectId",
> >                 "ItemResult": {
> >                     "LastEvaluatedKey": sfn.JsonPath.stringToJson("")
> >                 },
> >                 "walletAddress.$": "$.walletAddress",
> >                 "networkType.$": "$.networkType"
> >             },
> >             comment: "Transform store email result"
> >         });
> > ```
> 
> Yup having the same issue here, nice workaround !

Same issue with me as well, thanks for the workaround!

**Comment by mrgrain** [comment]
Can y'all try `sfn.JsonPath.DISCARD` where you want to pass the `null` value that doesn't exist in Python?

**Comment by mrgrain** [comment]
> Interesting workaround. Not something I would expect `sfn.JsonPath.DISCARD` to do, but it works

Agreed. It's named after [this feature](https://docs.aws.amazon.com/step-functions/latest/dg/input-output-resultpath.html) which at the time might have been the only (known) use case for `null` in ASL.

@paulhcsun is looking into DX improvements on the linked PR.

**Comment by anentropic** [comment]
> Can y'all try `sfn.JsonPath.DISCARD` where you want to pass the `null` value that doesn't exist in Python?

`null` in Python is `None`

it is JS's `undefined` which doesn't exist in Python surely?

`None`s in Python should be treated as explicit `null` values

whereas operations which return `undefined` in JS usually raise an exception in Python

and cases (e.g. default values for function args) where you need to distinguish "not supplied" from "explicit None supplied" would usually use a sentinel object for the _former_ case

e.g.
```python
NOT_SUPPLIED = object()

def myfunc(arg=NOT_SUPPLIED):
    if arg is None:
        ...
    elif arg is NOT_SUPPLIED:
        ...
    else:
        ...
```

using the bizarrely named `sfn.JsonPath.DISCARD` value (discard what? isn't it doing the _opposite_ of discarding the explicit null?) where you want an explicit `null` in the input JSON seems completely back-to-front from conventional practice... even in JS wouldn't it be more normal to treat `null` as an explicit `null`?

contrary to the idea that "`null` value doesn't exist in Python" it feels like real source of the problem must stem from core code mistakenly treating `undefined` vs `null` as the same thing rather than distinct?  why else would you need a special case for "explicitly null" values?

(`sfn.JsonPath.stringToJson("")` returning JSON `null` instead of an error is also a bit weird, but at least the more explicit `sfn.JsonPath.stringToJson("null")` works as expected and makes more sense than `sfn.JsonPath.DISCARD` when reading the code, so I will use that for now)
