### ISSUE TITLE
step-function-tasks: EMR Create cluster support CapacityOptimised

### ISSUE THREAD

**Issue by johsbk** [aws/aws-cdk#16252]
In the launch specification for an instance fleet config, I would like to set allocation strategy to CapacityOptimized for spot instances. This is available in general for job flow configs
### Use Case

I need this feature to avoid EMR failures due to spot instance getting deallocated

### Proposed Solution

simply implement it as defined in https://docs.aws.amazon.com/emr/latest/APIReference/API_RunJobFlow.html

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by BenChaimberg** [comment]
The [docs](https://docs.aws.amazon.com/emr/latest/APIReference/API_SpotProvisioningSpecification.html#EMR-Type-SpotProvisioningSpecification-AllocationStrategy) for this feature state that capacity optimized is the default value for spot instances. Can you confirm that there is some other default value that would necessitate adding this feature to the CDK?

**Comment by johsbk** [comment]
Hi Ben
I realize the docs says it is the default value, however if you don't set
it it will not use any allocation strategy at all. See picture:
[image: image.png]
However clusters configured with regular jobflow using sdk with allocation
strategy set to CapacityOptimized will have allocation strategy enabled:
[image: image.png]

Kind regards
Johs

**Comment by BenChaimberg** [comment]
Interesting, thanks for the confirmation! The `allocationStrategy` prop needs to be added here:
https://github.com/aws/aws-cdk/blob/d5ca419448e84f0cbb25dbd90d48fb4c407ede5c/packages/%40aws-cdk/aws-stepfunctions-tasks/lib/emr/emr-create-cluster.ts#L563
And then it needs to be properly serialized here:
https://github.com/aws/aws-cdk/blob/d5ca419448e84f0cbb25dbd90d48fb4c407ede5c/packages/%40aws-cdk/aws-stepfunctions-tasks/lib/emr/private/cluster-utils.ts#L123

I am unassigning myself and marking this issue as `p2`, which means that we are unable to work on this immediately.

We use +1s to help prioritize our work, and are happy to reevaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://join.slack.com/t/cdk-dev/shared_invite/zt-mso6p56d-qJp7SOTBvMaQuDrx7R2wHg) to solicit support for reprioritization.

Please feel free to work on this issue yourself and request my review if you submit a PR! See [CONTRIBUTING.md](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) for guidelines.
