### ISSUE TITLE
(aws-cdk): CDK Deploy resources totals in status bar are not accurate

### ISSUE THREAD

**Issue by jpSimkins** [aws/aws-cdk#16259]
During deployment, it shows a status bar with the resources being created. This total is rarely correct.

Here is one example where it is on 111 of 101 but it goes up to 187.
```
[██████████████████████████████████████████████████████████] (111/101)
```

While this is nothing serious, I did not see any tickets about this. So I wasn't sure if anyone was aware of it.

This doesn't seem to be a specific resource of the CDK doing this from what I can tell. It happens on numerous packages.

I will work later on adding some code to demonstrate this

### Reproduction Steps

Create many resources, and deploy. Watch the status bar and see it goes over it

### What did you expect to happen?

I expected the total to be accurate

### What actually happened?

It's rarely accurate

### Environment

 - **CDK CLI Version :**  1.117.0 (build 0047c98)
 - **Module Version :**  1.117.0
 - **Node.js Version :**  v14.17.4
 - **OS               :**  `Linux Zeus 5.11.0-27-generic #29~20.04.1-Ubuntu SMP Wed Aug 11 15:58:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
 - **Language (Version):** Typescript (Version 4.1.5)

--- 

This is :bug: Bug Report

**Comment by jpSimkins** [comment]
This is the smallest example I can currently provide of this behavior.

When this is deployed or updated. It says `0/2` but it ends up being `3/2` when it completes.

The initial values I posted above was on a much larger stack so this is the minimal I can show to duplicate the issue.

To duplicate the issue with this code, just change the cron to be `SUN` instead of `SAT` and you will get `3/2`.

Again, this is not a big deal at all. Just something that I've been noticing a lot.

```typescript
import { Construct, RemovalPolicy, Stack, StackProps } from '@aws-cdk/core';
import { CfnLocationEFS, CfnTask } from '@aws-cdk/aws-datasync';
import { LogGroup, RetentionDays } from '@aws-cdk/aws-logs';

/**
 * Efs Sync
 * This setups PROD to STAGE EFS syncing using datasync
 */
export class EfsSyncProdToStage extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);

    // Create log group
    const _logGroup = new LogGroup(this, 'EfsSyncLogGroup', {
      logGroupName: 'efs-sync-prod-to-stage',
      retention: RetentionDays.THREE_MONTHS,
      removalPolicy: RemovalPolicy.DESTROY,
    });

    // Create locations
    const _locationSource = new CfnLocationEFS(this, 'locationProdEfs', {
      ec2Config: {
        securityGroupArns: [
          'arn:aws:ec2:us-east-1:XXXXXXXXXXXX:security-group/sg-00012de844axxxxxx', // bastion sg
        ],
        subnetArn: 'arn:aws:ec2:us-east-1:XXXXXXXXXXXX:subnet/subnet-0227d3eedefxxxxxx', // private subnet
      },
      efsFilesystemArn: 'arn:aws:elasticfilesystem:us-east-1:XXXXXXXXXXXX:file-system/fs-xxxxxxx',
      subdirectory: '/',
    });

    const _locationDestination = new CfnLocationEFS(this, 'locationStageEfs', {
      ec2Config: {
        securityGroupArns: [
          'arn:aws:ec2:us-east-1:XXXXXXXXXXXX:security-group/sg-0450aa63529xxxxxx', // bastion sg
        ],
        subnetArn: 'arn:aws:ec2:us-east-1:XXXXXXXXXXXX:subnet/subnet-0dc94ad10d0xxxxxx', // private subnet
      },
      efsFilesystemArn: 'arn:aws:elasticfilesystem:us-east-1:XXXXXXXXXXXX:file-system/fs-xxxxxxx',
      subdirectory: '/',
    });

    // Create the task
    const _task = new CfnTask(this, 'ProdEfsToStageEfsSync', {
      name: 'efs-sync-PROD-to-STAGE',
      sourceLocationArn: _locationSource.attrLocationArn,
      destinationLocationArn: _locationDestination.attrLocationArn,
      options: {
        posixPermissions: 'PRESERVE',
        transferMode: 'CHANGED',
      },
      cloudWatchLogGroupArn: _logGroup.logGroupArn,
      schedule: {
        scheduleExpression: 'cron(0 4 ? * SAT *)', // Every Saturday at 4am UTC
      },
    });
  }
}

```

**Comment by ryparker** [comment]
Hey @jpSimkins 👋🏻 

Thanks for bringing this to our attention. Also big thank you for the repro code. I worked on this a while back and have noticed it as well. Possibly related to https://github.com/aws/aws-cdk/pull/15207.

Because this is not critical functionality i'm going to label this as p2 which means that we are unable to work on this immediately. We use +1s to help us prioritize our work, and as always we are happy to take contributions if anyone is interested to pick this up and submit a PR (please make sure to follow our [contribution guidelines](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md).) :pray:
