### ISSUE TITLE
API Gateway :- Unable to integrate openapi(SwaggerHub) with API gateway

### ISSUE THREAD

**Issue by sourabhyash** [aws/aws-cdk#16255]
### Environment

  - **CDK CLI Version  :1.120.0
  - **Framework Version:**
  - **Node.js Version:**  12.x
  - **OS               :**
  - **Language (Version):**

**Comment by straygar** [comment]
Could you please add some reproduction steps, what you expected to happen and what actually happened? The title alone is not enough to pinpoint the issue. :)

**Comment by sourabhyash** [comment]
I have tried with giving code 

    const api = new apiGw.SpecRestApi(this.stackScope, 'books-api', {
        apiDefinition: apiGw.ApiDefinition.fromAsset('./openAPIs/open-api-iam-based.yaml')
      });

      // A hack, based on apigateway.SpecRestApi constructor
      // const apiDefConfig = apiGw.ApiDefinition.fromAsset('./openAPIs/open-api-chi-iam-based.yaml').bind(api);
      // (api.node.defaultChild as apiGw.CfnRestApi).bodyS3Location = apiDefConfig.s3Location;
      this.restApi = api.root.addResource('api').addResource('v1');



openapi.yaml file 

openapi: 3.0.1
info:
  x-api-id: 5722d3b6-ee55-4554-9c22-a5da7956c8cd
  x-audience: component-internal
  version: 1.0.0
  title: Cow Health Index APIs
  description: This contains all the APIs build in Cow Health Index IAM Based
  contact:
    name: API Support
    email: sourabh.dhariwal@yash.com
    url: https://delaval.com/support #Sample placeholder URL added for now. Need to be updated before production.
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  termsOfService: https://delaval.com/terms/ # Sample placeholder URL added for now. Need to be updated before production.

servers:
  # Added by API Auto Mocking Plugin
  - url: https://virtserver.swaggerhub.com/API_DeLaval/CowHealthIndexApi/1.0.1
    description: SwaggerHub API Auto Mocking

tags:
  - name: PHD Activation Checklist

paths:
  /execute-activation-checklist:
    get:
      tags:
        - PHD Activation Checklist
      summary: Call to execute Checklist State machine
      description: To call Activation flow
      operationId: PHDActivationCheclistStateMachine
      requestBody:
        description: Model to get the alarmDetails
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ChecklistRequestBody"
      responses:
        200:
          description: "Call PHD Checklist"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ChecklistObject"
        400:
          description: "Bad Request"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequest"
        204:
          description: "No Content"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NoContent"
        401:
          description: "Unauthorized"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Unauthorized"
        500:
          description: "Internal Server Error"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
          .*\"statusCode\":400.*:
            statusCode: "400"
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
          .*\"statusCode\":401.*:
            statusCode: "401"
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
          .*\"statusCode\":500.*:
            statusCode: "500"
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
          .*\"statusCode\":204.*:
            statusCode: "204"
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
        passthroughBehavior: "when_no_templates"
        httpMethod: "POST"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
    options:
      tags:
        - PHD Activation Checklist
      summary: Call to run PHD Activation Checklist flow
      description: To call Activation flow
      operationId: PHDActivationCheclistStateMachineOption
      responses:
        200:
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
        requestTemplates:
          application/json: '{"statusCode": 200}'
        passthroughBehavior: "when_no_match"
        type: "mock"

components:
  schemas:
    ChecklistRequestBody:
      type: object
      properties:
        farm_id:
          type: string
          example: ""
        subscription_id:
          type: string
          example: "9"
    Empty:
      title: "Empty Schema"
      type: "object"
    InternalServerError:
      title: Internal server error occurred
      type: object
      properties:
        message:
          type: string
          example: Internal Server Error
    Unauthorized:
      title: Unauthorized
      type: object
      properties:
        message:
          type: string
          example: Unauthorized
    NoContent:
      title: NoContent
      type: object
      properties:
        message:
          type: string
          example: No Content
    BadRequest:
      title: Invalid input parameters
      type: object
      properties:
        message:
          type: string
          example: Bad Request
    ChecklistObject:
      type: object
      properties:
        message:
          type: string
          example: started state machine
        result:
          type: object
          properties:
            executionArn:
              type: string
              example: Arn
            startDate:
              type: string
              example: "1626344305.547"

**Comment by nija-at** [comment]
Please update the issue description with proper reproduction steps. It seems that you're using CDK in a non-standard way by calling the `bind()` API and using `CfnRestApi`.

Have you tried using `SpecRestApi`? If you have, please provide an explanation on why you are using it in this way.
