### ISSUE TITLE
(aws_cdk.aws_elasticsearch): Set connections defaultPort when enforceHttps is true

### ISSUE THREAD

**Issue by SamStephens** [aws/aws-cdk#16251]
When a VPC is used with an elasticsearch Domain, the resulting connections object does not have a default port. However, when enforceHttps is set, we know communications will be over port 443.

### Use Case

So I don't have to manually specify a port when setting up VPC connections to the Domain.

### Proposed Solution

Include a defaultPort when constructing the connections object if enforceHttps is true.

---

This is a :rocket: Feature Request

**Comment by peterwoodworth** [comment]
Is this still true for opensearch @SamStephens ?

**Comment by peterwoodworth** [comment]
Looks like this is still valid. Would probably need to change here https://github.com/aws/aws-cdk/blob/ea69ad2f51347cf0ecb8f36decc7499f91bcf43a/packages/%40aws-cdk/aws-opensearchservice/lib/domain.ts#L1244

We accept [contributions](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) 🙂

**Comment by SamStephens** [comment]
@peterwoodworth I've had a go at a fix for this, hopefully it suits.
