### ISSUE TITLE
ecs: CfnContainerDefinition has pseudoTerminal parameter, but ContainerDefinition does not

### ISSUE THREAD

**Issue by AWS-MattB** [aws/aws-cdk#16263]
The CDK [`ContainerDefinition` construct](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-ecs/lib/container-definition.ts#L254-L261) lacks a `pseudoTerminal` property that the auto-generated [CfnContainerDefinition has included](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html#ECS-Type-ContainerDefinition-pseudoTerminal) since `cfnspec` [version 6](https://github.com/aws/aws-cdk/commit/27de0a0e887763071a6297649f65296c65e13aba). 

I wasn't able to locate an alternative means of configuring that parameter. 

Without this parameter, `/proc/fd/1` links to `/dev/null` instead of `/dev/console` and it's impossible to get logs from some containers that expect that link to exist.

### Reproduction Steps

```
        const task_def = new TaskDefinition(scope, "TaskDef", {
            compatibility: Compatibility.EC2,
            volumes: [
                {host: {sourcePath: "/sys/fs/cgroup"}, name: "cgroupfs"} //systemd
            ]
        });
        const linux_params = new LinuxParameters(scope, "LinuxParams", {});
        linux_params.addTmpfs({containerPath: "/tmp", size: 100}, {containerPath:"/run", size: 100}); //systemd
        linux_params.addCapabilities(Capability.NET_ADMIN);
        const container = task_def.addContainer("Container", {
            image: ....,
            memoryLimitMiB: props.memory || 1024,
            logging: new AwsLogDriver({streamPrefix: this.node.id}),
            environment: {
                "container": "docker" // Needed by systemd to know it's running in a container
            },
            linuxParameters: linux_params
        });
        container.addMountPoints(
            // Also for systemd
            {containerPath:"/sys/fs/cgroup", readOnly: true, sourceVolume: "cgroupfs"}
        );
```

### What did you expect to happen?

I expected to either be able to include `psuedoTerminal: true` in the properties for `container`, or have there be a setter on the resulting `ContainerDefinition` object that would let me set it to `true`.

### What actually happened?

There is neither a `pseudoTerminal` property nor a setter on the resulting `ContainerDefinition` object.

### Environment

  - **CDK CLI Version  :** 1.119.0
  - **Framework Version:** 1.119.0
  - **Node.js Version:** 12.0
  - **OS               :** AL2
  - **Language (Version):** all

### Other

--- 

This is :bug: Bug Report

**Comment by AWS-MattB** [comment]
It also is not clear if this is possible to work around via an escape hatch, as the containers are rendered lazily:

https://github.com/aws/aws-cdk/blob/f1bf935c47006096b33fb7bf0c847ffab9230870/packages/%40aws-cdk/aws-ecs/lib/base/task-definition.ts#L421

**Comment by peterwoodworth** [comment]
Labelled as a feature request because our L2 constructs aren't necessarily supposed to have all of the properties configurable on their respective L1 constructs.

Thank you for submitting a PR for this already. I'll see if it can get looked at soon
