### ISSUE TITLE
Deploying EC2 ECS using addAsgCapacityProvider not working

### ISSUE THREAD

**Issue by ikelin** [aws/aws-cdk#16260]
## :question: Deploying EC2 ECS using addAsgCapacityProvider: No Container Instances were found in your cluster 

I am attempting to deploy a service using EC2 ECS.  Specifically, using the ecs-pattern's `ApplicationLoadBalancedEc2Service`.  When I use `cluster.addAsgCapacityProvider()` instead of `cluster.addCapacity()`, the EC2 instance is created but never registered with the ECS cluster, causing the CDK deployment to be stuck in step indefinitely.

### To Reproduce

```
const cluster = new ecs.Cluster(this, 'Cluster', {
  vpc: props.vpc,
});

const autoScalingGroup = new as.AutoScalingGroup(this, 'AutoScalingGroup', {
  vpc: props.vpc,
  instanceType: ec2.InstanceType.of(ec2.InstanceClass.BURSTABLE3, ec2.InstanceSize.MICRO),
  machineImage: new ec2.AmazonLinuxImage(),
});

const capacityProvider = new ecs.AsgCapacityProvider(this, 'CapacityProvider', {
  autoScalingGroup,
});

cluster.addAsgCapacityProvider(capacityProvider);

new ecsPatterns.ApplicationLoadBalancedEc2Service(this, 'Ec2Service', {
  cluster,
  cpu: 1024,
  memoryLimitMiB: 512,
  taskImageOptions: {
    image: ecs.ContainerImage.fromRegistry('nginx'),
  },
});
```

When I run `cdk deploy`, it hangs at the step that is creating the ECS Service.  

```
12:41:29 PM | CREATE_IN_PROGRESS   | AWS::ECS::Service                             | Ec2Service/Service/Service
```

When I go to AWS Console -> ECS -> Cluster -> Service -> Event, I see the following message:

```
service <...> was unable to place a task because no container instance met all of its requirements. 
Reason: No Container Instances were found in your cluster. For more information, see the Troubleshooting section.
```

When I go to AWS Console -> ECS -> Cluster -> EC2 Instances, there is no instance registered.  But when I goto AWS Console -> EC2 -> Instances, I see the newly created EC2 in a healthy `Running` state.

### Work around

If I change CDK code to use the deprecated method `.addCapacity()`, the EC2 ECS service is created as expected.

```
const cluster = new ecs.Cluster(this, 'Cluster', {
  vpc: props.vpc,
});

cluster.addCapacity('Capacity', {
  instanceType: ec2.InstanceType.of(ec2.InstanceClass.BURSTABLE3, ec2.InstanceSize.MICRO),
});

new ecsPatterns.ApplicationLoadBalancedEc2Service(this, 'Ec2Service', {
  cluster,
  cpu: 1024,
  memoryLimitMiB: 512,
  taskImageOptions: {
    image: ecs.ContainerImage.fromRegistry('nginx'),
  },
});
```

The EC2 instance is created and registered and I can hit the load balancer to reach nginx without any issue.

Is there a possible bug with using `addAsgCapacityProvider()` or is there an extra step needed to use this method?

### Environment

  - **CDK CLI Version:** `1.118.0 (build a4f0418)`
  - **Module Version:** `"@aws-cdk/aws-ecs-patterns": "1.118.0"`
  - **Node.js Version:** `v16.7.0`
  - **OS:** `OSX Big Sur 11.5.2`
  - **Language:** `TypeScript`

**Comment by anggras** [comment]
Facing same issue

**Comment by zsimjee** [comment]
I followed the above and got a different error - Resource handler returned message: "Out of retries. Last encountered error was: The specified capacity provider is in use and cannot be removed. (Service: AmazonECS; Status Code: 400; Error Code: ResourceInUseException; Request ID: ..."

**Comment by madeline-k** [comment]
@zsimjee, It looks like that error is coming up because the capacity provider needs to be replaced (which is essentially a delete followed by a create), and you already have one deployed. Can you try deleting it and then retrying your deployment? This doc should help with deleting the capacity provider: https://aws.amazon.com/premiumsupport/knowledge-center/ecs-capacity-provider-error/

**Comment by martinreus** [comment]
Still having the same issue, with the same error `No Container Instances were found in your cluster`
