### ISSUE TITLE
(aws-cdk): Add "quickly retry stack operation" feature to CDK

### ISSUE THREAD

**Issue by tbrand** [aws/aws-cdk#16289]
[New for AWS CloudFormation – Quickly Retry Stack Operations from the Point of Failure](https://aws.amazon.com/jp/blogs/aws/new-for-aws-cloudformation-quickly-retry-stack-operations-from-the-point-of-failure/)

Today, CloudFormation allows us to disable rollback so that we can quickly retry stack operation from point the point of failure. This feature reduces the time required to test CloudFormation template in development environment. I really need this feature to CDK as well.

### Use Case

For example, let's think the case we deploy Aurora cluster and other small resources. And assuming the small resources depend on the cluster. If I deploy the resources at the same time by one template, CloudFormation creates the cluster first and then create the small stuff. If the deployment contains a bug about small stuff, CloudFormation would rollback all creation including Aurora cluster even the creation of the cluster takes 10 ~ 20 minutes. For the development environment, especially, we would like to keep the cluster and re-create the small stuff after fixing the bug.

### Proposed Solution

Add an option that supports "Quickly Retry Stack Operations from the Point of Failure".

### Other

- [New for AWS CloudFormation – Quickly Retry Stack Operations from the Point of Failure](https://aws.amazon.com/jp/blogs/aws/new-for-aws-cloudformation-quickly-retry-stack-operations-from-the-point-of-failure/)

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by krzysztof-slowinski** [comment]
How about adding a parameter to stack or app to have more granular control on when this feature would be applied?

**Comment by dannysteenman** [comment]
> How about adding a parameter to stack or app to have more granular control on when this feature would be applied?

+1 for this. I'm using cdk pipelines for the deployment of stacks in different environments. Instead of a cli flag I would like to have granular control per stack.
