### ISSUE TITLE
(aws-kinesisfirehose): Unseted CfnDeliveryStream props `extendedS3DestinationConfiguration.schemaConfiguration.region` leads to AWS Console Error

### ISSUE THREAD

**Issue by jonatansmith** [aws/aws-cdk#16288]
When creating a stack with CfnDeliveryStream, using a Glue Table to convert a record the AWS Kinesis Firehose Configuration Page at AWS Console fails to load with following error if the property `region` in `schemaConfiguration` is not set:

`Kinesis Data Firehose can’t load the section right now because of an issue with the console. Go to the console home page, then try to return to this page later. If the problem persists, go to AWS Support Center .`

### Reproduction Steps

```typescript
new CfnDeliveryStream(this, 'myfirehose', {
...
            extendedS3DestinationConfiguration: {
...
                dataFormatConversionConfiguration: {
                    enabled: true,
                    inputFormatConfiguration: {
                        deserializer: {
                            openXJsonSerDe: {}
                        }
                    },
                    outputFormatConfiguration: {
                        serializer: {
                            parquetSerDe: {}
                        }
                    },
                    schemaConfiguration: {
                        databaseName: 'existing-glue-db-name',
                        roleArn: myfirehooseRole.attrArn,
                        tableName: 'existing-glue-table-name',
                    },
                },
           }
```
### What did you expect to happen?

A workaround for this problem is to add the region:
```typescript
                    schemaConfiguration: {
                        databaseName: 'existing-glue-db-name',
                        roleArn: myfirehooseRole.attrArn,
                        tableName: 'existing-glue-table-name',
                        region: Stack.of(this).region,
                    },
```

Since the property region is optional ([Ref](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-kinesisfirehose.CfnDeliveryStream.SchemaConfigurationProperty.html#region)) , should work properly with missing region property.

### Environment

  - **CDK CLI Version  :1.120.0 (build 6c15150)**
  - **Framework Version:**
  - **Node.js Version:v14.17.4** 
  - **OS               :Windows 10**
  - **Language (Version):TypeScript ** 

--- 

This is :bug: Bug Report

**Comment by otaviomacedo** [comment]
Hi, @jonatansmith. You're right. According to the documentation it should use the current region by default. However, `CfnDeliveryStream` is an L1, which maps directly to the CloudFormation template. So there is nothing we can do on the CDK side.

@peterwoodworth another one for the CloudFormation team?

**Comment by peterwoodworth** [comment]
Tracking: V432302958

**Comment by otaviomacedo** [comment]
@jonatansmith, according to the Kinesis Firehose team, this issue has been fixed and deployed. Can you please confirm?
