### ISSUE TITLE
(aws-events): add replyName field to EventPattern interface

### ISSUE THREAD

**Issue by kovanelly** [aws/aws-cdk#16280]
Add replyName to EventPattern's interface

### Use Case

To be able to create specific rules for events from event bridge archive replies and separate normal events and events from replies as it has the same structure except replyName field

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
Sounds good. We would accept a PR that adds this, shouldn't be too hard.

**Comment by jaresuth** [comment]
@rix0rrr  - Are we looking at adding a replayName not replay?  I was looking at implementing this feature. Thanks.
