### ISSUE TITLE
(pipelines): Cross-account references for stack outputs in CodeBuild projects

### ISSUE THREAD

**Issue by markusl** [aws/aws-cdk#16283]
In https://github.com/aws/aws-cdk/issues/16137 @rix0rrr and @kaizen3031593 explained that it should be possible to use stack outputs in CodeBuild actions that are deployed in other accounts than where the CDK Pipeline is deployed at.

@kaizen3031593 shared a code snippet explaining the usage of `envFromCfnOutputs`. 

```ts
new pipelines.CodeBuildStep('cbs', {
          envFromCfnOutputs: {
            URL: new cdk.CfnOutput(this, 'url', {
              value: 'myUrl',
              
            })
          },
          commands: ['curl -Ssf $URL'],


```

However, it's a bit unclear from this snippet and the Pipelines documentation at https://docs.aws.amazon.com/cdk/api/latest/docs/pipelines-readme.html how to concretely deploy the CodeBuild project to another account and have the stack reference properly in place.

What was possible with the Pipelines "legacy API":

* `Deployment account` contains CodePipeline for doing the deployments
  * Source, Synth, Self-mutate etc..
  * Deploy CloudFormation `Stack A` with API GW in `Dev Account`
  * Deploy Deploy CodeBuild project `Integ-Test` in `Dev Account` that references a variable from the `Stack A`
  * Invoke the CodeBuild project `Integ-Test` to see that the API GW is properly deployed (the CodeBuild project should the pipeline's source artifact to have the testing setup/scripts in place, or alternatively it can be standalone project)
  * Proceed to deploy higher-level environments with the same setup...

In https://github.com/aws/aws-cdk/issues/16137 I shared the relevant code snippets that made this happen with the old CDK Pipelines API. Would you be able to provide a similar functionality with a complete code example with the new CDK Pipelines API?

Best Regards,
Markus

---

This is a 📕 documentation issue

**Comment by rix0rrr** [comment]
> how to concretely deploy the CodeBuild project to another account and have the stack reference properly in place.

A CodeBuild project and a reference to it are like any other cross-account resource. That is: automatic naming won't work, so it must have a physical name (generated or not): https://docs.aws.amazon.com/cdk/latest/guide/resources.html#resources_physical_names

**Comment by markusl** [comment]
@rix0rrr I still think this could be clarified in the documentation, especially when migrating from the legacy pipelines to the "modern" Pipelines.

I got it working now but was misguided by a bunch of things:

* There is no alternative for `pipeline.stackOutput` in the modern Pipelines
* In https://github.com/aws/aws-cdk/issues/16137 @kaizen3031593 suggested using `pipelines.CodeBuildStep ` for cross-account builds which is exactly what *should not* be done
* Tried to replicate usage of `envFromCfnOutputs` which is indeed not needed at all

If anyone else needs to do a similar setup, hope this helps :) 

### Defining the CodeBuild project stack

```ts

export interface ExampleLambdaIntegTestStackProps extends cdk.StackProps {
  readonly vpcConfig: ec2.VpcAttributes;
  readonly urlOutput: cdk.CfnOutput;
}

export class ExampleLambdaIntegTestStack extends cdk.Stack {
  public readonly codebuildRole: iam.Role;
  public readonly codebuildProject: codebuild.PipelineProject;
 
  constructor (scope: Construct, id: string, props: ExampleLambdaIntegTestStackProps) {
    super(scope, id, props);
    addCommonTags(this, 'dev');

    const vpc = ec2.Vpc.fromVpcAttributes(this, `${id}-Vpc`, props.vpcConfig);
    this.codebuildProject = new codebuild.PipelineProject(this, 'Project', {
      projectName: id,
      environment: { buildImage: codebuild.LinuxBuildImage.STANDARD_5_0 },
      vpc,
      buildSpec: codebuild.BuildSpec.fromObject({
        version: '0.2',
        phases: {
          build: {
            commands: [
              'curl -v ' + props.urlOutput.value,
            ],
          },
        },
      }),
    });

    this.codebuildProject.role?.addToPrincipalPolicy(new iam.PolicyStatement({
      actions: ['kms:Decrypt', 'kms:DescribeKey'],
      resources: ['*'],
    }));
    this.codebuildProject.role?.addToPrincipalPolicy(new iam.PolicyStatement({
      actions: ['s3:Get*'],
      resources: ['*'],
    }));
    this.codebuildRole = new iam.Role(this, 'Role', {
      roleName: `${id}-IntegTestsRole`,
      assumedBy: new iam.CompositePrincipal(
        new iam.ServicePrincipal('codebuild.amazonaws.com'),
        new iam.ServicePrincipal('codepipeline.amazonaws.com'),
        new iam.AccountPrincipal(DeployAccount),
      ),
    });
    
    this.codebuildRole.addToPolicy(new iam.PolicyStatement({
      resources: ['*'],
      actions: ['codebuild:*'],
    }));
  }
}

```

### Defining the modern CDK pipeline

```ts
  const lambdaStack = new ExampleLambdaDemoStack(appStage, env, { vpcConfig });

  const integTests = new ExampleLambdaIntegTestStack(appStage, `LambdaDemoIntegrationTest-${env}`, {
    vpcConfig,
    urlOutput: lambdaStack.urlOutput,
  });

  pipeline.addStage(appStage);

  pipeline.addWave(`IntegrationTests-${env}`).addPre(new CodeBuildActionStep(`IntegrationTests-${env}`,
    codebuild.Project.fromProjectName(integTests, 'ImportedProject', integTests.codebuildProject.projectName), 
    sourceFileSet,
    iam.Role.fromRoleArn(integTests, 'ImportedRole', integTests.codebuildRole.roleArn),
  ));
```

### Defining the CodeBuild action step

```ts
import * as cdk from 'aws-cdk-lib';
import {
  aws_codepipeline as codepipeline,
  aws_codebuild as codebuild,
  aws_codepipeline_actions as codepipeline_actions,
  aws_iam as iam,
  pipelines
} from 'aws-cdk-lib';

export class CodeBuildActionStep extends pipelines.Step implements pipelines.ICodePipelineActionFactory {
  constructor (
    id: string,
    private readonly project: codebuild.IProject,
    private readonly sourceFileSet?: pipelines.FileSet,
    private readonly role?: iam.IRole,
    private readonly environmentVariables?: Record<string, cdk.aws_codebuild.BuildEnvironmentVariable>,
  ) {
    super(id);
  }

  public produceAction (stage: codepipeline.IStage, options: pipelines.ProduceActionOptions): pipelines.CodePipelineActionFactoryResult {
    if(!this.sourceFileSet) {
      throw new Error('Missing sourceFileSet');
    }
    stage.addAction(new codepipeline_actions.CodeBuildAction({
      actionName: this.id,
      runOrder: options.runOrder,
      variablesNamespace: this.id,
      input: options.artifacts.toCodePipeline(this.sourceFileSet),
      role: this.role,
      project: this.project,
      environmentVariables: this.environmentVariables,
    }));

    return {
      runOrdersConsumed: 1,
      project: this.project,
    };
  }
}


```
