### ISSUE TITLE
(@aws-cdk/pipelines ): UpdatePipelineAction is not authorised to deploy cross-account-support-stack

### ISSUE THREAD

**Issue by BarkaouiSalma** [aws/aws-cdk#16292]
CdkPipeline is failing when deploying  cross account  in the selfMutation step: **"failed: Error: Could not assume role in target account using current credentials"**
The  problem is that the buildProject of the selfMutation doesn't have the 'sts:AssumeRole' for the other  accounts.
That's why  it can't  deploy the **cross-account-support-stack** in those accounts.

So I tried to add this manually but this is not working because I don't have access the the role of the UpdatePipelineAction. It is always undefined. I tried also to get the build project and update the role but this didn't work either:

            const project = PipelineProject.fromProjectName(this, 'Pipeline-selfMutation', 'SelfMutation');
            project.addToRolePolicy(
                new PolicyStatement({
                    actions: ['sts:AssumeRole'],
                    resources: [ MYRESOURCES]}))

@aws-cdk/codebuild 

### Environment

  - **CDK CLI Version:1.119
  - **Module Version: @aws-cdk/pipelines 1.119
  - **Node.js Version: v14.17.0
  - **Language (Version):TypeScript (3.8.3)

**Comment by rix0rrr** [comment]
UpdatePipeline should only ever need to deploy resources in the same environment. Check out your pipeline stack and see why it's trying to deploy it into a different account or region than the pipeline is in.

I'm going to guess you changed the `env` environment to your pipeline stack and then committed the changes.

**Comment by jrehwaldt** [comment]
Tracked now as feature request in #16374
