### ISSUE TITLE
Dynamo: can't do an in place update from a "Pay Per Request" table to a provisioned one

### ISSUE THREAD

**Issue by DennisSSDev** [aws/aws-cdk#16302]
When attempting to switch a table from a pay-per request to a provisioned one with autoscaling - cloud formation will error out stating that the table already has a scaling target for the read and write. This is happening because for whatever great reason aws creates a default auto-scaling policy from 1 to 40000 RCU/WCU so when CFN tries to create your scaling policy it errors out because AWS already created one smh.

### Reproduction Steps

- Create a pay per request dynamo table with CDK and have it succeed through CFN creation
- Go back to your CDK and switch the provisioning to provisioned and specify the scaling targets
- Have that run through CFN and notice how it fails, because aws creates default scaling 
- Now you're stuck with a dynamo table that you can't rollback for the next 24 hours

### What did you expect to happen?

Trying to switch to a provisioned capacity with autoscaling

### What actually happened?

CFN errored

### Environment

  - **CDK CLI Version  :latest**
  - **Framework Version:latest**
  - **Node.js Version: 14.4.0** 
  - **OS               :MAC OS**
  - **Language (Version):** TypeScript (3.9.7) 

### Other

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hey @DennisSSDev,

thanks for opening the issue. I wonder if it's the same problem as in https://github.com/aws/aws-cdk/issues/15318?

Thanks,
Adam

**Comment by DennisSSDev** [comment]
Yes, seems to be the same problem :/ @skinny85

**Comment by skinny85** [comment]
OK, let's consolidate the conversation there.
