### ISSUE TITLE
add a "like"/"contains" operator to event pattern content based filtering

### ISSUE THREAD

**Issue by AmitFidler** [aws/aws-cdk#16317]
event pattern content based filtering is missing a "like"/"contains" operator 

https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-event-patterns-content-based-filtering.html

### Use Case

wanted to check if one of the properties is an email and check if it contains a '@' property 

### Proposed Solution

add a contains/like configuration that would scan the field input.

This is a :rocket: Feature Request

**Comment by indrora** [comment]
This could be achieved using a lambda that filters messages and rebroadcasts them to a secondary EventBridge. 

Underlying, however, this is a feature request for the AWS EventBridge service. I'm going to pass this on as best I can however.
