### ISSUE TITLE
(@aws-cdk/pipelines): Document how to deploy CDK apps from synth artifact

### ISSUE THREAD

**Issue by Obirah** [aws/aws-cdk#16313]
---
In the [pipelines module's documentation](https://docs.aws.amazon.com/cdk/api/latest/docs/pipelines-readme.html) I cannot find any information on how to deploy a CDK app from an artifact that results from the synth step. Can someone who knows please add that? I would open a PR if I'd know how it works, but I haven't figured how to do what I want so far:

What I want to achieve, is to directly deploy from the cloud assembly that is created by synth instead of explicitly instantiating my stack within a stage because my pipeline app does not have the CDK app code available, hence it shall only be known to the pipeline by pulling from git and synthesizing it. The closest I came was to instantiate a `DeployCdkStackAction` with the cloud assembly output as its input and add it to the pipeline, but this only worked for the same account the pipeline is running and I need to deploy cross-account.

Code example:
```
const source = CodePipelineSource.codeCommit(
    Repository.fromRepositoryName(this, `${app.name}-repository`, app.name),
    app.branch
);

const synth = new ShellStep('Sync', {
    commands: [
       this.cdk('synth', app)
    ],
    input: source,
    installCommands: this.npmInstall
});

const pipeline = new CodePipeline(this, `${app.name}-pipeline`, {
    crossAccountKeys: true,
    ...this.pipelineNetwork,
    pipelineName: `${this.config.accountId}-${app.name}`,
    synth,
    synthCodeBuildDefaults: {
        buildEnvironment: {
            environmentVariables: this.environment // This contains the target account ID and region
        },
        ...this.pipelineNetwork
    }
});
```

Now, I want to deploy what `synth` produces without having to call `new MyStack(...)` within a stage but by simply telling the pipeline to deploy the synth result.

**Comment by MichaelGermino** [comment]
Would a Codebuild action that executes cdk deploy be sufficient? I had a scenario where I wanted my front end stack to pick up the API URL from the backend. This was only possible by running my synth and deploy commands within codebuild actions.

**Comment by rix0rrr** [comment]
This is not really the design target of CDK Pipelines, so there isn't an out-of-the-box way to do it. 

There's possibly a way to make it work if you make a subclass of Stage that overrides `synth`, and return a `CloudAssembly` object that has been loaded from disk. However, I don't think we have classes available to load a CloudAssembly from disk, as that was ALSO not in the design target for CDK (but I might be wrong).

Doing what Michael said is probably the easiest solution.
