### ISSUE TITLE
Cloudfront Function not manipulating Response Headers for Static Site Routes

### ISSUE THREAD

**Issue by zubairzahoor** [aws/aws-cdk#16327]
Cloudfront function is deployed 

```
const cfFunction = new Function(this, "Function", {
            code: FunctionCode.fromFile({
                filePath: `${__dirname}/cloudfrontFn.js`
            })
        });

```
And linked to a distribution
```

originConfigs: [
                {
                    s3OriginSource: {
                        s3BucketSource: siteBucket,
                        originAccessIdentity
                    },
                    behaviors: [
                        {
                            isDefaultBehavior: true,
                            functionAssociations: [
                                {
                                    function: cfFunction,
                                    eventType: FunctionEventType.VIEWER_RESPONSE
                                }
                            ]
                        }
                    ]
                }
            ]

```
The base URL and the URL for all objects in the bucket is returning the manipulated Response Headers. But the different routes like **https://_baseURL/route_** is not returning the same. 

Is it supposed to do this?

**Comment by zubairzahoor** [comment]
<img width="544" alt="Base URL" src="https://user-images.githubusercontent.com/26036402/131717706-6558a6b1-b25e-4df1-890a-f67655a9da15.png">
<img width="534" alt="Route" src="https://user-images.githubusercontent.com/26036402/131717715-a7d84bfc-73d7-4893-9e2a-00ace0ed1ecc.png">

**Comment by njlynch** [comment]
Without a full example, it's a bit hard to comment on what's happening here.

> The base URL and the URL for all objects in the bucket is returning the manipulated Response Headers. But the different routes like https://baseURL/route is not returning the same.

From the above, I only see the S3 bucket origin with the function attached. So you're saying the paths that all correspond to the origin you have configured with the function work fine, and all other paths don't? What are those other paths? Are those effectively 404s, or are those paths to other origins (not shown in your example)? What origin/behavior are you expecting `baseURL/route` to correspond to?

**Comment by NGL321** [comment]
Closing due to lack of response
