### ISSUE TITLE
(apigateway): auto-deployment doesn't work

### ISSUE THREAD

**Issue by rantoniuk** [aws/aws-cdk#16324]
According to AWS CDK Documentation, all ApiGateway changes regarding adding new methods should be by [default automatically deployed to the default prod stage](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-apigateway.RestApi.html#deploy).

This works fine for the case where the ApiGateway is managed in the same CDK stack that the methods/resources are being updated. It seems it doesn't work however when the ApiGateway is imported via `Fn.importValue` by Arn from another stack that is managing it.

In our case, we have the following micro-service repository layout:
1. we have an `infra` repository that contains several CDK stacks, one per directory, that are self-isolated

The purpose of this repository is to hold all "shared" components of the infrastructure (like SQS, DynamoDB, ApiGW) to avoid dependency cycles between the components.
This way we know that the infra changes need to be deployed first if there is a new shared component that is added to the architecture stack.

2. we have per-microservice repositories that have their CDK respective stacks, e.g. MicroserviceXStack, that only deploy Lambda code and rely on shared resources created by the infra stack.

Inside the CDK of that component, the API GW methods are added like this:
```ts
    const restApiId = Fn.importValue('restApiIdOutput');
    const rootId = Fn.importValue('parentIdOutput');

    const restApi = RestApi.fromRestApiAttributes(this, 'ApiGateway', {
      restApiId: restApiId,
      rootResourceId: rootId,
    });

...

 const createDocumentApiConstruct = new ApiConstruct(this, 'createDocument', {
      lambdaHandler: 'document-api-handler.create',
      layerVersion: nodeLayer,
      assetCode: lambdaCode,
      resource: documentResourceConstruct.resource,
      httpMethodName: 'POST',
      methodOptions: { apiKeyRequired: true },
    });
```

where the ApiContruct looks similarly to this:

```ts
export class ApiConstruct extends Construct {

  public method: Method;
  public fn: Function;

public constructor(scope: Construct, id: string, props: ApiConstructProps) {
    super(scope, id);

    const lambdaConstruct = new LambdaConstruct(this, `${id}-service`, {
      lambdaHandler: props.lambdaHandler,
      layerVersion: props.layerVersion,
      assetCode: props.assetCode,
      environment: props.environment,
      timeout: props.timeout,
    });

    this.fn = lambdaConstruct.lambdaFunction;

    let methodOptionsForConstruct: MethodOptions;

    const methodConstruct = new MethodConstruct(this, `${id}-method`, {
      lambdaFunction: this.fn,
      resource: props.resource,
      methodOptions: methodOptionsForConstruct,
      httpMethodName: props.httpMethodName,
      roles: props.roles,
    });

    this.method = methodConstruct.method;
  }

}
```

and MethodConstruct:

```ts
export class MethodConstruct extends Construct {

  public method: Method;

  public constructor(scope: Construct, id: string, props: MethodConstructProps) {
    super(scope, id);

    const lambdaIntegration = new LambdaIntegration(props.lambdaFunction, {
      proxy: true,
    });

    this.method = new Method(this, `${id}-method`, {
      httpMethod: props.httpMethodName,
      resource: props.resource,
      options: props.methodOptions,
      integration: lambdaIntegration,
    });
  }
}

```

### What did you expect to happen?

API Gateway stage to be automatically deployed to /prod.

### What actually happened?

Resources are visible in the ApiGW in the UI, but they are not deployed to /prod stage automatically.

### Environment

CDK 1.119
CodePipelines

Do you have any suggestions how can we debug what is the reason this doesn't work like comparing the generated CF templates?

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
The auto-deployment story, unfortunately, is not true when used with `fromRestApiAttributes()`.

We're tracking this gap https://github.com/aws/aws-cdk/issues/13526 and https://github.com/aws/aws-cdk/issues/12417.

As mentioned in the linked issue, you will need to create your own Deployment and salt its logical id whenever any resource changes. The Deployment should deploy at the end (after all the Resource and Methods are deployed).
