### ISSUE TITLE
(@aws-cdk/aws-batch): JobDefinition construct generates template with deprecated ContainerProperties members (memory & vcpus)

### ISSUE THREAD

**Issue by minhpfg** [aws/aws-cdk#16328]
### The Question

We are getting this warning message in the batch job console, and after digging into it, I believe the JobDefinition construct is generating the template with deprecated [ContainerProperties](https://docs.aws.amazon.com/batch/latest/APIReference/API_ContainerProperties.html) members: "memory" and "vcpus"

![image](https://user-images.githubusercontent.com/76219150/131714782-f4f1bb6d-b451-4385-a28f-cb723c56b1a7.png)

CDK code snippet

```javascript
new JobDefinition(this, 'jobdef', {
    container: {
        image: image,
        vcpus: 2,
        memoryLimitMiB: 4096
    }
})
```

Output template snippet

```json
"JobDef": {
  "Type": "AWS::Batch::JobDefinition",
  "Properties": {
    "Type": "container",
    "ContainerProperties": {
      "Image": omitted,
      "Memory": 4096,
      "Vcpus": 2
    }
  }
}
```

However, the [AWS Batch CloudFormation documentation ](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-batch-jobdefinition-containerproperties.html#cfn-batch-jobdefinition-containerproperties-memory)does not show that those two members are deprecated

Any advice on how to handle this issue?

### Environment

  - **CDK CLI Version:** 1.121.0 (build 026cb8f)
  - **Module Version:** 1.121.0
  - **Node.js Version:** v14.17.4
  - **OS:** macOS Catalina
  - **Language (Version):** TypeScript 4.3.5

**Comment by peterwoodworth** [comment]
Hey @minhpfg,

Have you tried using the [`resourceRequirements` property](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-batch-jobdefinition-containerproperties.html#cfn-batch-jobdefinition-containerproperties-resourcerequirements)?

**Comment by minhpfg** [comment]
Thank you @peterwoodworth for the advice. Is there a way to set the `resourceRequirements` property after initializing the level 2 construct [`JobDefinition`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-batch.JobDefinition.html)?

I've tried via the escape hatch method `node.defaultChild` but the `resourceRequirements` is `readonly`. I would have to fall back to initializing the level 1 construct [`CfnJobDefinition`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-batch.CfnJobDefinition.html) but wanted to avoid that as I'm using CDK's `ContainerImage.fromAsset()` function and that doesn't play well with the level 1 construct.

**Comment by peterwoodworth** [comment]
I'm not sure how to set the `resourceRequirements` property here if the escape hatch method isn't working. I just tried and wasn't able to figure it out either.

I'm going to convert this to a bug report so that we can discuss a fix. 

https://github.com/aws/aws-cdk/blob/fad855e7fb046844258e36e2699234407fbb64ec/packages/%40aws-cdk/aws-batch/lib/job-definition.ts#L429-L462

The source of the issue lies above. I'm not sure if moving the props passed to `resourceRequirements` here would be a breaking change. @madeline-k would this be okay to fix?

**Comment by peterwoodworth** [comment]
CloudFormation has now updated their documentation to say that these members are deprecated. Bumping to p1

**Comment by peterwoodworth** [comment]
oh it's been addressed already and this issue wasn't closed. Nice!
