### ISSUE TITLE
(pipelines): Make max actions per stage configurable

### ISSUE THREAD

**Issue by markusl** [aws/aws-cdk#16336]
In the legacy pipelines, we were able to create a stage that contains over 50 actions.

In the new Pipelines this does not seem to be possible as there is a hard-coded valued used to split it to multiple stages:

https://github.com/aws/aws-cdk/blob/2c1eb08ad174ba56c4f2a0d807a0cb039534d1a9/packages/%40aws-cdk/pipelines/lib/codepipeline/codepipeline.ts#L371-L374

### Reproduction Steps

Create over 50 actions in a stage.

### What did you expect to happen?

It would be good to have the number of actions in a stage as configurable variable as it really is (you can request service limit increase from AWS).

### What actually happened?

Our CloudFormation actions are put into multiple stages. The problem here is that if one of the actions fails, a lot of other actions never run because of this. In the previous setup only the single failed action failed.

### Environment

  - **CDK CLI Version  :** 2.0.0-rc.19 (build d8d6314)
  - **Framework Version:** 2.0.0-rc.19 (build d8d6314)
  - **Node.js Version:** 14
  - **OS               :** macOS
  - **Language (Version):** all

### Other

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
I guess this could be configurable via context. For most users the current behavior is the proper behavior, where the Pipeline ends up workable, even without a limit increase.
