### ISSUE TITLE
(aws-eks): AWSCDK-EKS-HelmChart fails "primary clusterIP can not be unset"

### ISSUE THREAD

**Issue by mrsiejas** [aws/aws-cdk#16338]
When trying to bump the version of [Prometheus Helm chart](https://prometheus-community.github.io/helm-charts) I am getting the following error
```
5:27:24 AM | UPDATE_FAILED        | Custom::AWSCDK-EKS-HelmChart          | Prometheus/Resource/Default
5:27:24 AM | UPDATE_FAILED        | Custom::AWSCDK-EKS-HelmChart          | Prometheus2BCCDD01
Received response status [FAILED] from custom resource. Message returned: Error: b'Error: UPGRADE FAILED: cannot patch "prometheus-kube-state-metrics" with kind Service: Service "prometheus-kube-state-metrics" is invalid: spec.clusterIPs[0]: Invalid value: []string(nil): primary clusterIP can not be unset && cann
ot patch "prometheus-kube-state-metrics" with kind Deployment: Deployment.apps "prometheus-kube-state-metrics" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/name":"kube-state-metrics"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is imm
utable\n'

Logs: /aws/lambda/sandbox-eks-cluster-awscdkawseksKu-Handler886CB40B-bIZejxomCpe9

at invokeUserFunction (/var/task/framework.js:95:19)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
at async onEvent (/var/task/framework.js:19:27)
at async Runtime.handler (/var/task/cfn-response.js:48:13) (RequestId: 9a864af2-6977-420c-be5f-a559183aebf2)

        new CustomResource (/tmp/jsii-kernel-KkVVa0/node_modules/@aws-cdk/core/lib/custom-resource.js:30:25)
        \_ new HelmChart (/tmp/jsii-kernel-KkVVa0/node_modules/@aws-cdk/aws-eks/lib/helm-chart.js:35:9)
        \_ obj._wrapSandboxCode (/tmp/tmppwn1hwel/lib/program.js:8367:58)
        \_ Kernel._wrapSandboxCode (/tmp/tmppwn1hwel/lib/program.js:8795:24)
        \_ Kernel._create (/tmp/tmppwn1hwel/lib/program.js:8367:34)
        \_ Kernel.create (/tmp/tmppwn1hwel/lib/program.js:8108:29)
        \_ KernelHost.processRequest (/tmp/tmppwn1hwel/lib/program.js:9692:36)
        \_ KernelHost.run (/tmp/tmppwn1hwel/lib/program.js:9655:22)
        \_ Immediate.setImmediate [as _onImmediate] (/tmp/tmppwn1hwel/lib/program.js:9656:46)
        \_ runCallback (timers.js:705:18)
        \_ tryOnImmediate (timers.js:676:5)
        \_ processImmediate (timers.js:658:5)
```

I have found following post which I believe is related to this issue: https://github.com/helm/helm/issues/6378#issuecomment-557746499

In short Helm3 uses different approach when patching the object (clusterIp in my case). Helm 2 compares installed version vs version that is being installed, Helm 3 uses current version installed on cluster vs version that is being installed. 

It seems that this behaviour will be fixed in K8s 1.22 but in the meantime I'm looking for a workaround. Users have suggested 2 approaches:

- New chart - set omit flags on specific objects
```
$ helm upgrade --install ingress-test stable/nginx-ingress --set controller.service.omitClusterIP=true --set defaultBackend.service.omitClusterIP=true
```
- Existing chart - remove `--force` option from the cli when running helm update --install

Sadly I do not see a way to apply them to a CDK construct. Could anyone help with finding a temporary workaround to this issue?

### Reproduction Steps
1. Deploy EKS cluster on version 1.19
2. Deploy Prometheus chart version='10.4.0'
3. Update EKS to 1.20
4. Bump Prometheus chart to version='14.6.0'

### What did you expect to happen?
Chart being updated.

### What actually happened?
Update Failed with the error from description. I'm aware it is not caused by CDK but would like have option to apply a helm workaround by passing args to Helm 

### Environment

  - CDK CLI Version  : 1.91
  - Framework Version: 1.91
  - Node.js Version: v16.7.0
  - OS  : MacOS
  - Language (Version): Python  3.8.5

--- 

This is :bug: Bug Report

**Comment by otaviomacedo** [comment]
I am unassigning and marking this issue as `p2`, which means that we are unable to work on this immediately.

We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://join.slack.com/t/cdk-dev/shared_invite/zt-mso6p56d-qJp7SOTBvMaQuDrx7R2wHg) to solicit support for reprioritization.
