### ISSUE TITLE
Amazon.CDK.AWS.Apigatewayv2: missing HttpApi in .NET distribution

### ISSUE THREAD

**Issue by pgolebiowski** [aws/aws-cdk#16334]
This package https://www.nuget.org/packages/Amazon.CDK.Lib does not contain [`HttpApi`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-apigatewayv2.HttpApi.html) in `Amazon.CDK.AWS.Apigatewayv2` (or any other namespace in that package).

### Reproduction Steps

1. Create a new project.
2. Add these dependencies.

```
<PackageReference Include="Amazon.CDK.Lib" Version="2.0.0-rc.20" />
<PackageReference Include="Constructs" Version="[10.0.0,11.0.0)" />
```

3. Create a class which won't compile due to missing `HttpApi` in the package.

```
using Amazon.CDK.AWS.Apigatewayv2;
using Constructs;

internal class HttpApiSetup : Construct
{
    public HttpApiSetup(Construct scope) : base(scope, nameof(HttpApiSetup))
    {
        new HttpApi(this, "HttpApi", new HttpApiProps
        {
        });
    }
}
```

### What did you expect to happen?

I expected `HttpApi` to be in `Amazon.CDK.AWS.Apigatewayv2`. However, that namespace only contains `Cfn*` and `ICfn*` classes.

I checked that that class exists in the "old CDK" in the dedicated package that I can get with `dotnet add package Amazon.CDK.AWS.Apigatewayv2` (and then `HttpApi` is in the namespace `Amazon.CDK.AWS.APIGatewayv2`).

Notice that in one package the namespace is `Amazon.CDK.AWS.APIGatewayv2` and in another it's `Amazon.CDK.AWS.Apigatewayv2` — perhaps you have a casing issue.

--- 

This is :bug: Bug Report

**Comment by pgolebiowski** [comment]
Hello, any thoughts on this one from anyone? 😊

**Comment by nija-at** [comment]
The `apigatewayv2` module is currently experimental. The main artifact of CDKv2 - `aws-cdk-lib` - does not ship with experimental modules. 

We are currently working on making this available. It will not be available via `aws-cdk-lib` but through a different mechanism. 
See https://github.com/aws/aws-cdk-rfcs/blob/master/text/0249-v2-experiments.md for details.

This is expected to be released in the coming weeks.
