### ISSUE TITLE
(cli): Conflicting stack detection

### ISSUE THREAD

**Issue by HariboDev** [aws/aws-cdk#16347]
When using a multi-stack deployment (e.g. DynamoDB, Lambda & API Gateway), a major update to the lowest level stack (e.g. updating the DynamoDB table name), causes the table to be destroyed and a new one to be created in its place. However, because this table ARN is used as an environment variable in Lambda, the `cdk deploy` command fails and issues a rollback. 

Instead of rolling back when a conflict occurs, the CDK will then delete the conflicting stacks(s) and continue deploying the update. Afterwards, it will then redeploy the conflicting stack(s) as the CDK would normally as the stacks are no longer present in CloudFormation.

### Use Case

At the moment, major changes, like updating a DynamoDB table name, cause the stack deployment to fail and rollback. To get around this issue, a manual deletion of the conflicting stack(s) needs to be issued. This could be a long process if you have lots of stacks and takes up possible development time.

Knowing that the CDK would handle this situation for you (assuming you passed the flag), developers can continue developing their applications without having to watch out for stack rollbacks.

### Proposed Solution

Similarly to the [Security-related changes flag](https://docs.aws.amazon.com/cdk/latest/guide/cli.html#cli-security), this feature would allow for a flag to be passed that would automatically delete conflicting stacks in a recursive way. For example, `cdk deploy --delete-conflicting-stack`.

### Other

Links:
- [Security-related changes flag](https://docs.aws.amazon.com/cdk/latest/guide/cli.html#cli-security)

* [x] :wave: I may be able to implement this feature request
* [x] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
This is going to need a lot of design. I'm not sure a flag in the CLI is the best solution (it would not help CI/CD scenario's), I'm not sure deleting downstream stacks is the best solution (it would lead to service interruption), and detecting the situation in the first place is hard and based on a lot of heuristics.

You could be building a tool that does this yourself, today, by reading the CloudFormation templates of CDK and doing a CloudFormation diff or changeset inspection. If it becomes popular, we can reconsider rolling it into the CDK CLI.

In the mean time, this feature has a big implementation cost and I'm not sure it's all that valuable in all that many cases. Most people will be better off learning about resource replacements and `stack.exportValue()` instead.

**Comment by rix0rrr** [comment]
This is going to need a lot of design. I'm not sure a flag in the CLI is the best solution (it would not help CI/CD scenario's), I'm not sure deleting downstream stacks is the best solution (it would lead to service interruption), and detecting the situation in the first place is hard and based on a lot of heuristics.

You could be building a tool that does this yourself, today, by reading the CloudFormation templates of CDK and doing a CloudFormation diff or changeset inspection. If it becomes popular, we can reconsider rolling it into the CDK CLI.

In the mean time, this feature has a big implementation cost and I'm not sure it's all that valuable in all that many cases. Most people will be better off learning about resource replacements and `stack.exportValue()` instead.
