### ISSUE TITLE
(eks): clarify that vpc prop is necessary for subnetSelection prop to work in FargateProfile construct

### ISSUE THREAD

**Issue by peterwoodworth** [aws/aws-cdk#16349]
There's a check in the FargateProfile constructor which only uses the `subnetSelection` prop if the `vpc` prop is defined: https://github.com/aws/aws-cdk/blob/6c151508b00d97aa2549dd64e86b95c9f6a77a44/packages/%40aws-cdk/aws-eks/lib/fargate-profile.ts#L159-L163

However [our docs don't make this clear](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-eks.FargateProfile.html#subnetselection), which lead to customer confusion from having all of their private subnets be selected. We should clarify that the vpc prop also needs to be defined for the subnetSelection prop to work.

Additionally, we could throw an error if the subnetSelection prop is defined and the vpc isn't, but I'm not sure if that would be a breaking change. 

---

This is a 📕 documentation issue

**Comment by peterwoodworth** [comment]
@otaviomacedo let me know if we should do anything in addition to updating the docs here. I can handle the PR

**Comment by otaviomacedo** [comment]
Yes, I'm worried that someone, somewhere left a `subnetSelection` without `vpc` by mistake, which doesn't make sense, but is not affecting them, either. Throwing an error would be a breaking change. But maybe a warning would be a good idea, in addition to the documentation.
