### ISSUE TITLE
awscdk-events:  RuleTargetInput should support using a JSON string as input

### ISSUE THREAD

**Issue by ttais2017** [aws/aws-cdk#16344]
The rules created in AmazonEventBridge with RuleTargetInput.fromObject/fromText are wrong, due to the given JSON Object will be converted in text but scaping the \" sign.

    Rule keepAlive = Rule.Builder.create(this, id4res(stage, "keepalive"))
        .ruleName(id4res(stage, "keepalive"))
        .description("Rule for keeping alive the LDAP Lambda Function")
        .schedule(Schedule.rate(Duration.minutes(FtpFamilyConstants.DEFAULT_LDAP_PING_REFRESH)))
        .build();

    keepAlive.addTarget(LambdaFunction.Builder
        .create(resourcesProperties.getLambdaFunctions().get(FtpFamilyConstants.FunctionType.LDAP))
        .event(RuleTargetInput.fromObject(keepAlivePolicy ()))
        .build());

The method 'keepAlivePolicy' read a file which contains a JSON object.  For example:
{"a": "1", "b": "2"}

As result of executing the CDK block,  a new rule will be created with a JSON object with content as follow:

"{\\"a\\":\\"1": \\"b\\":\\"2\\"}"

### Environment

$ cdk --version
1.120.0 (build 6c15150)

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
Can you please show the relevant snippet of the CloudFormation file in `cdk.out/MyStack.template.json` ?

**Comment by ttais2017** [comment]
"ffms05gammaxclpoststackclkeepalive96802537": {
      "Type": "AWS::Events::Rule",
      "Properties": {
        "Description": "Rule for keeping alive the LDAP Lambda Function",
        "Name": "ff-ms-05-gammax-cl-post-stack-cl-keepalive",
        "ScheduleExpression": "rate(5 minutes)",
        "State": "ENABLED",
        "Targets": [
          {
            "Arn": {
              "Ref": "referencetoffms05gammaXffms05gammaxclresNestedStackffms05gammaxclresNestedStackResource8EA86573Outputsffms05gammaXffms05gammaxclresffms05gammaxclresclldapConnectorFunctionAF564349Arn"
            },
            "Id": "Target0",
            "Input": "\"[\\r\\n  {\\\"Entry\\\": \\\"/\\\", \\\"Target\\\": \\\"/FF_BUCKET_NAME\\\"}\\r\\n]\""
          }
        ]
      },
      "Metadata": {
        "aws:cdk:path": "ff-ms-05-gammaX/ff-ms-05-gammax-cl-post-stack/ff-ms-05-gammax-cl-post-stack-cl-keepalive/Resource"
      }
    }

**Comment by ttais2017** [comment]
unfortunately the chars \\" will be printed/shown in this editbox/html field somehow in other way

**Comment by ttais2017** [comment]
`"ffms05gammaxclpoststackclkeepalive96802537": {
      "Type": "AWS::Events::Rule",
      "Properties": {
        "Description": "Rule for keeping alive the LDAP Lambda Function",
        "Name": "ff-ms-05-gammax-cl-post-stack-cl-keepalive",
        "ScheduleExpression": "rate(5 minutes)",
        "State": "ENABLED",
        "Targets": [
          {
            "Arn": {
              "Ref": "referencetoffms05gammaXffms05gammaxclresNestedStackffms05gammaxclresNestedStackResource8EA86573Outputsffms05gammaXffms05gammaxclresffms05gammaxclresclldapConnectorFunctionAF564349Arn"
            },
            "Id": "Target0",
            "Input": "\"[\\r\\n  {\\\"Entry\\\": \\\"/\\\", \\\"Target\\\": \\\"/FF_BUCKET_NAME\\\"}\\r\\n]\""
          }
        ]
      },
      "Metadata": {
        "aws:cdk:path": "ff-ms-05-gammaX/ff-ms-05-gammax-cl-post-stack/ff-ms-05-gammax-cl-post-stack-cl-keepalive/Resource"
      }
    }`

**Comment by rix0rrr** [comment]
I have a sense that

> The method 'keepAlivePolicy' read a file which contains a JSON object. For example:
> {"a": "1", "b": "2"}

Is not returning the object as an OBJECT (`HashMap` in Java) but as a `String`.

At least, that's what I'm seeing here:

```
 "Input": "\"....
```

That tells me that the top-level thing that's being passed to `Input` is a string.

**Comment by rix0rrr** [comment]
It could be a feature request to use a JSON string as an input -- `fromText()` is not good enough as it will also add the outer quotes.
