### ISSUE TITLE
(aws-cdk): Parameter Name `/cdk-bootstrap/{id}/version` with a different configuration already exists

### ISSUE THREAD

**Issue by robert-pitt-foodhub** [aws/aws-cdk#16352]
Hi, I am experiencing an issue bootstrapping our environment, currently we are reciving the following exception when executing `cdk bootstrap`, I have attached the stack trace and exception further down.

### What did you expect to happen?

Successful upgrade / re-bootstrap of the environment.

### What actually happened?

We are attempting to upgrade our application from `1.121.0` to `v2.0.0-rc.20`, we have migrated our code base and any changes incurred due to changes in feature flags, however we are unable to proceed due to an error being thrown regarding the migration of the CDK Toolkit version parameter within the environment, the current version we have configured in the parameter is `5`.

### Environment

  - **CDK CLI Version : *2.0.0-rc.20 (build d50d087)*
  - **Framework Version:*2.0.0-rc.20*
  - **Node.js Version: *v12.18.3*
  - **OS: *Apple Mac*
  - **Language (Version):*Typescript (4.3.5)*

### Other

1. Result of `cdk bootstrap`
```
:hourglass_flowing_sand:  Bootstrapping environment aws://000000000000/us-east-1...
Trusted accounts for deployment: (none)
Trusted accounts for lookup: (none)
Using default execution policy of 'arn:aws:iam::aws:policy/AdministratorAccess'. Pass '--cloudformation-execution-policies' to customize.
CDKToolkit: creating CloudFormation changeset...
18:47:00 | CREATE_FAILED        | AWS::SSM::Parameter   | CdkBootstrapVersion
ERROR Parameter Name /cdk-bootstrap/hnb659fds/version with a different configuration already exists.

:x:  Environment aws://000000000000/us-east-1 failed bootstrapping: Error: The stack named CDKToolkit failed to deploy: UPDATE_ROLLBACK_COMPLETE
    at Object.waitForStackDeploy (falcon/node_modules/aws-cdk/lib/api/util/cloudformation.ts:307:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Object.deployStack (falcon/node_modules/aws-cdk/lib/api/deploy-stack.ts:294:26)
    at falcon/node_modules/aws-cdk/lib/cdk-toolkit.ts:372:24
    at async Promise.all (index 0)
    at CdkToolkit.bootstrap (falcon/node_modules/aws-cdk/lib/cdk-toolkit.ts:369:5)
    at initCommandLine (falcon/node_modules/aws-cdk/bin/cdk.ts:214:9)
The stack named CDKToolkit failed to deploy: UPDATE_ROLLBACK_COMPLETE
```

Currently configured parameter

<img width="665" alt="Screenshot 2021-09-02 at 18 56 55" src="https://user-images.githubusercontent.com/70318887/131905947-f40a2294-e566-45ff-b783-e947f6e5e1ae.png">

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
If you look in Systems Manager Parameter Store, you will see that there is a parameter with the name `/cdk-bootstrap/hnb659fds/version`.

The bootstrap template is trying to create that same parameter, and it fails because it already exists.

Go through all CloudFormation stacks, and see if any of them have this parameter in their list of **Resources**. Once you find it, figure out why that CloudFormation stack exists in the first place, and see if you want to delete it instead.

If you find no such stack (and only then), it's safe to delete the parameter by hand.
