### ISSUE TITLE
Lambda support for Python 3.9

### ISSUE THREAD

**Issue by bravobravo-au** [aws/aws-cdk#16355]
I see that in the Lambda support for Python 3.9 https://aws.amazon.com/blogs/compute/python-3-9-runtime-now-available-in-aws-lambda/ CDK is listed as supporting this new runtime. However when using CDK Python to create a Python Lambda there are only enums for 2.7,3.6,3.7,3.8. https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_lambda/Runtime.html

I have also tried accessing PYTHON_3_9 enum in case the documentation was lagging the library but that doesn't work.

Will Python 3.9 support be coming soon to the Python CDK?

**Comment by michaelbrewer** [comment]
I have a PR up for it https://github.com/aws/aws-cdk/pull/16072

**Comment by kornicameister** [comment]
Hmm..wonder why that didn't just close.

**Comment by bravobravo-au** [comment]
Great work guys! @michaelbrewer I'm going to use this as soon as it comes out!
