### ISSUE TITLE
aws-cloudwatch: Make Alarm object region-aware

### ISSUE THREAD

**Issue by ancastoica** [aws/aws-cdk#16367]
Make available the creation of cross-region aware Alarms. Metrics are already region aware, I would like to also be able to specify a region when creating an alarm.

### Use Case

My specific use case is that I am deploying a stack that needs to be region aware, this same stack is deployed in several accounts and regions. One of the regions the stack is deployed in is eu-west-1. The stack deploys amongst others some CloudFront distributions (which are global and publish metrics in us-east-1). We need to find a way to set up alarms for the CloudFront distributions - this works fine in us-east-1, but in EU we have the issue where if we specify that the metrics are in US, the alarm creation fails with `Cannot create an Alarm in region 'eu-west-1' based on metric '<MetricName>' in 'us-east-1'`.

### Proposed Solution
The Alarm object should accept an optional region parameter.

Alternatively, alarms could default to the metric's region instead of the deployment region if possible.

### Other

I assume that an alternative would be to create a separate US-only specific stack, or an env-agnostic stack, which would read the first stack's distribution ids and create metrics for them in this US stack, but I find this to be overkill. I don't see moving the distributions in a different stack as a possible solution since our service is already live and we don't want to do any disruptive changes.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by kaizen3031593** [comment]
According to the cloudwatch [docs](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Cross-Account-Cross-Region.html), alarms can be _cross-account_ but not _cross-region_. That is why the alarm creation fails. Until cloudwatch introduces this feature, there is nothing we can do from the CDK.
