### ISSUE TITLE
(synthetics) - Broken Link Checker Blueprint - Additional Features

### ISSUE THREAD

**Issue by gwharton** [aws/aws-cdk#16365]
Would it be possible to implement the following features on a future release of the Broken Link Checker Blueprint

1. Provide an array of internal (on same domain as parent) blacklisted urls (wildcard supporting) which the url checker should not follow.
2. Respect the rel="nofollow" attribute on links. These should not be followed, or there should atleast be an option to not follow.

### Use Case

- I analyse the homepage at domain.com. Lets say we have local analytics running on the webpage that loads an image based tracker https://domain.com/postanalyticsdata?........ on every page view. Currently these links are followed and there is no way to stop it. It would be great to be able to add "https://domain.com/postanalyticsdata*" to a blacklist array to prevent following.
- Admins implement rel=nofollow on links that shouldn't be followed by crawlers. There should be an option to exclude these. e.g sites with complex layered navigation and page content filtering can produce sets of urls running into the millions to cover combinations of all options. The link checker gets lost trying to follow all of these when they should/could easily be excluded if nofollow was respected.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by kaizen3031593** [comment]
This seems to be a feature request for AWS Synthetics, not the AWS CDK.

**Comment by gwharton** [comment]
My apologies. Is there a more appropriate repository to raise the feature request in?

**Comment by kaizen3031593** [comment]
Unfortunately I do not know of any way you can get in contact with the AWS Synthetics team externally as they are not an open-source service.
