### ISSUE TITLE
(aws-elasticache): Auth token is plain text

### ISSUE THREAD

**Issue by jlgre** [aws/aws-cdk#16368]
The auth token accepted by CfnReplicationGroup is a string. Support to use a Secret.SecretValue would be great so that auth tokens do not have to be recorded in plain text anywhere. Even if we generate a random auth token, it is displayed in the synthesized templates.

### Use Case

To enable secure generation of Elasticache auth token

### Proposed Solution

Add support for Secret.SecretValue in the constructor

* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by jumic** [comment]
In the L1 constructs (starting with 'cfn') this feature isn't available by default. You can add +1 in issue #6908 to priorize the L2 construct which will support this feature.

Nevertheless, it should be already possible to specify a password from SecretsManager in your Replication Group. Can you try this example?
```ts
const secret = new secretsmanager.Secret(this, 'MySecret', {
  generateSecretString: {
    secretStringTemplate: JSON.stringify({ username: 'user' }),
    generateStringKey: 'password',
  },
})

new elasticache.CfnReplicationGroup(this, 'replication-group', {
  // ...
  authToken: secret.secretValueFromJson('password').toString(),
});
```

Maybe you have to adjust the password generation in SecretsManager (allow only supported characters).

**Comment by davidahopp** [comment]
I believe this should be re-opened and added as a planned feature. The most recent version of CDK now warns and then requires an "unsafeUnwrap()" of the secret to be able to set the authToken as a string.

`redisCredentialSecret.secretValueFromJson('password').unsafeUnwrap().toString()`
