### ISSUE TITLE
Remove canned metrics and augmented metrics from aws-cdk-lib for alpha modules.

### ISSUE THREAD

**Issue by madeline-k** [aws/aws-cdk#16369]
cfn2ts generates three types of files: the L1s, "Augmentations" (for metrics), and Canned Metrics:

https://github.com/aws/aws-cdk/blob/2023004cc941a0e7a908bf3c90ad9887c6679564/tools/cfn2ts/lib/index.ts#L21-L30 

In the alpha modules, we want to remove the L1s, but keep the Augmentation and Canned Metrics. So, this task describes the work to remove the Augmentation and Canned Metrics from `aws-cdk-lib` for these modules.

**Comment by njlynch** [comment]
Closing this issue out, as there's no direct customer benefit to doing so, or harm for not.
