### ISSUE TITLE
(ec2): allow setting subnet in ec2 constructor by subnet's ID

### ISSUE THREAD

**Issue by tobske** [aws/aws-cdk#16371]
To make the constructor of an ec2 instance more readable and shorter it should be possible to directly set the target subnet via the subnet's ID in the constructor.

### Use Case

I would use this feature to configure an ec2 instance in each private subnet of a VPC.

### Proposed Solution

This is what it would look like:
```ts
    vpc.privateSubnets.forEach((sub, id) => {
      new Instance(this, "Instance" + id, {
        instanceType: instanceType,
        machineImage: machineImage,
        vpc: vpc,
        subnetId: sub.subnetId
      });
    })
```

This is how it has to be done today:
```ts
    vpc.privateSubnets.forEach((sub, id) => {
      new Instance(this, "Instance" + id, {
        instanceType: instanceType,
        machineImage: machineImage,
        vpc: vpc,
        vpcSubnets: vpc.selectSubnets({ subnets: [sub] }),
      });
    })
```

This is a :rocket: Feature Request

**Comment by njlynch** [comment]
Thanks for filing a feature request!

Unfortunately, I don't think this feature is appropriate for this construct. The `vpcSubnets` property is a well-defined and well-used concept across the CDK for a reason. It provides maximum flexibility for the myriad use cases that exist out there in the wild. If we add `subnetId`, it's a slippery slope; next someone will ask for `subnetIds`, and then `subnetNames`, `subnetType`, etc. Each imitating the current behavior of `vpcSubnets`, and needing to override/integrate with each other.
