### ISSUE TITLE
(aws-s3, BucketPolicy): How can I append the extra policyStatement for existing S3. bucket which already had the bucket policy?

### ISSUE THREAD

**Issue by terrificdm** [aws/aws-cdk#16379]
### The Question
Just checked some issues reports in the repo, and didn't find any useful answer for appending the extra policyStatement for existing S3. bucket which already had the bucket policy. And if I just add the policyStatement to the bucket without any policy(or removed the existing policy before the adding), it works properly without any issue. But when I add the policy to the bucket with the policy, it will throw the error "the bucket has the existing bucket policy"... 

So, my question is can I just append the policy to the existing policies without deleting them first, is there any code examples? Thanks.

### Environment

  - **CDK CLI Version:** 
  - **Module Version:** 
  - **Node.js Version:** 
  - **OS:** 
  - **Language (Version):**

**Comment by otaviomacedo** [comment]
Unfortunately not. The CDK cannot get the information about the existing bucket, such as the the policy it has. Removing the existing policy before the adding a new one is the best option in this case.
