### ISSUE TITLE
(aws-neptune): Include `1.0.5.0` in AWS Neptune Engine Version

### ISSUE THREAD

**Issue by rakcy** [aws/aws-cdk#16388]
`1.0.5.0` seems to be missing from the list of AWS Neptune Engine Version

### Use Case

We need this to be able to use the latest AWS Neptune Engine Version

### Proposed Solution
https://github.com/aws/aws-cdk/blob/fc618f97128ab1dc25b735bd634c52f2c47ef457/packages/%40aws-cdk/aws-neptune/lib/cluster.ts#L16-L55

---

This is a :rocket: Feature Request

**Comment by jumic** [comment]
I created a PR for the new version.

It is already possible to use the new version if you specify the version number as a string:
```ts
new neptune.DatabaseCluster(this, 'Database', {
  vpc,
  instanceType: neptune.InstanceType.T3_MEDIUM,
  engineVersion: new neptune.EngineVersion('1.0.5.0'),
});
```
