### ISSUE TITLE
(aws-cloudwatch): Saved queries

### ISSUE THREAD

**Issue by ramonwilkinson** [aws/aws-cdk#16395]
Add the creation of Saved Queries for CloudWatch Log Insights.

### Use Case

Allowing the creation of saved queries with CDK would encourage a software team to define common queries used across multiple accounts. In our team for example, we have separate AWS accounts for each region and stage of our product. Being able to deploy a saved query to many accounts and regions from infrastructure code would simplify the sharing process. 

### Proposed Solution

Feature request only - I'm not proposing a solution concept.

### Other

N/A

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by awsiv** [comment]
Good idea! 

Cloudformation support has recently been added:

https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/615

**Comment by madeline-k** [comment]
Thanks for opening this feature request, @ramonwilkinson! Until L2 CDK support is implemented for this feature, you can use the L1 construct to create saved queries in your CDK app: https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-logs.CfnQueryDefinition.html

**Comment by jerry-shao** [comment]
PR: https://github.com/aws/aws-cdk/pull/18655
