### ISSUE TITLE
(aws-ecs-patterns): Kinesis Stream ECS Fargate Pattern

### ISSUE THREAD

**Issue by leandrodvd** [aws/aws-cdk#16391]
I would like to have a pattern for Kinesis Stream + ECS/Fargate under aws-ecs-patterns package.

It would be similar to QueueProcessingFargateService but instead of a Queue as input, it will have a Kinesis Stream as input.

### Use Case

My actual goal is to have a Dynamo DB -> Kinesis Stream -> Fargate service so that I can easily setup the infrastructure necessary to process updates from DynamoDB with a high throughput (Dynamo don't need to be part of this construct so that I can attach other data generators to the Stream). 

### Proposed Solution

Would create a new construct following the same pattern of QueueProcessingFargateService

- aws-cdk/aws-ecs-patterns/lib/base/stream-processing-fargate-base.ts
- aws-cdk/aws-ecs-patterns/lib/ecs/stream-processing-ecs-service.ts
- aws-cdk/aws-ecs-patterns/lib/fargate/stream-processing-fargate-service.ts

Content of those would be equivalent of the queue processing construct.

Tasks scaling would be based on the Stream Metric GetRecords.IteratorAgeMilliseconds so that it will scale up when it is taking too long to consume stream records.

### Other

I'm willing to make a pull request contributing to this feature.

* [X] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by madeline-k** [comment]
@leandrodvd , thanks for opening this feature request! It would be great to see a pull request from you for this! The proposed solution you have listed seems reasonable to me. Take a look at our [contributing guide](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) to get started, if you haven't already.
