### ISSUE TITLE
(synthetics): documentation of canary schedule expression only supports rate

### ISSUE THREAD

**Issue by mprencipe** [aws/aws-cdk#16392]
According to the CDK reference documentation the Canary schedule expression only supports rate.
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-synthetics.Schedule.html

According to this documentation the scheduling configuration is much more flexible https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Synthetics_Canaries_cron.html

---

This is a 📕 documentation issue

**Comment by kaizen3031593** [comment]
Currently you can use `synthetics.Schedule.expression('cron(0 10 * * ? *)')` to specify a cron expression for canaries. The documentation here should reflect that, I agree.

I also think that we should have a static `cron` method in the schedule class for easier usability though - there are similar methods in `autoscaling` and `application autoscaling`.

**Comment by kaizencc** [comment]
#16402 should have closed this issue
