### ISSUE TITLE
update Function to support CodeDeploy deployments

### ISSUE THREAD

**Issue by sam-goodwin** [aws/aws-cdk#1639]
`Function` or `Alias` should support configuring blue/green deployments via CodeDeploy with sensible defaults such as which alarms to monitor.

* Requires smart hashing of the asset content: https://github.com/awslabs/aws-cdk/issues/1400
* Related aws-codedeploy PR: https://github.com/awslabs/aws-cdk/pull/1628

**Comment by skinny85** [comment]
This has been done. Resolving.
