### ISSUE TITLE
add an example of Lambda with blue/green deployments

### ISSUE THREAD

**Issue by sam-goodwin** [aws/aws-cdk#1640]
Adapt the integration test as an example: https://github.com/awslabs/aws-cdk/pull/1628

May depend on https://github.com/awslabs/aws-cdk/issues/1639 for a higher-level example. Do we want to show an example of using Lambda deployment groups and Function, or just Function?

**Comment by skinny85** [comment]
Done here: https://docs.aws.amazon.com/cdk/latest/guide/codepipeline_example.html

Resolving this one.

**Comment by hk1313** [comment]
@skinny85  In above URL is not lambda blue green example, it's just codepipeline.

**Comment by skinny85** [comment]
@hk1313 this issue is 4 years old 🙂. However, [here's another example](https://github.com/skinny85/cdk-codepipeline-and-local-lambda-guidance/blob/59f7ddaf483515ac450216eda4609cda82d45446/lib/lambda-stack.ts#L16-L35).
