### ISSUE TITLE
(aws_cdk.aws_dynamodb): reading `table_arn` results in `dynamoDb:describeTable` call with `...cfn-exec-role...` role 

### ISSUE THREAD

**Issue by krzysztof-slowinski** [aws/aws-cdk#16400]
There is a deployment role used for the deployment process of the entire infrastructure that is assumed before `cdk deploy` step using `aws sts assume-role`.

After introducing reading `table_arn` property between stacks this process got an error. It turns out that there was a call to `dynamoDb:describeTable` made with an internal CDK role `...cfn-exec-role...` which does not have access permissions and it results in `AccessDenied. User doesn't have permission to call dynamoDb:describeTable` error.

### Reproduction Steps

```python
import aws_cdk.aws_dynamodb as ddb
import aws_cdk.core as cdk


class DynamoDBStack(cdk.Stack):
    def __init__(
        self, scope: cdk.Construct, id: str, **kwargs
    ) -> None:
        super().__init__(scope, id, **kwargs)

        self.table = ddb.Table(
            self, "ddb_table",
            table_name="MyTable",
            partition_key=ddb.Attribute(name="key1", type=ddb.AttributeType("STRING")),
            sort_key=ddb.Attribute(name="key2", type=ddb.AttributeType("STRING")),
        )

    def get_table_arn(self):
        return self.table.table_arn
```

The call from another stack is then enough to cause the issue:

```python
import aws_cdk.core as cdk
from dynamodb import DynamoDBStack
from aws_iam_policies import create_dynamodb_table_read_policy

class IAMStack(cdk.Stack):
    def __init__(
        self, scope: cdk.Construct, id: str, ddb_stack: DynamoDBStack, **kwargs
    ) -> None:
        super().__init__(scope, id, **kwargs)

        create_dynamodb_table_read_policy(scope, ddb_stack.get_table_arn())
```

Contents of the `cdk.json`:

```json
{
  "app": "python3 app.py",
  "context": {
    "@aws-cdk/core:enableStackNameDuplicates": "true",
    "aws-cdk:enableDiffNoFail": "true",
    "@aws-cdk/core:stackRelativeExports": "true",
    "@aws-cdk/aws-ecr-assets:dockerIgnoreSupport": true,
    "@aws-cdk/aws-secretsmanager:parseOwnedSecretName": true,
    "@aws-cdk/aws-kms:defaultKeyPolicies": true,
    "@aws-cdk/aws-s3:grantWriteWithoutAcl": true
  }
}
```

### What did you expect to happen?

Get ARN of DynamoDB table from another stack.

### What actually happened?

`AccessDenied. User doesn't have permission to call dynamoDb:describeTable`

### Environment

  - **CDK CLI Version  :** 1.119.0
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :** Ubuntu-x86_64
  - **Language (Version):**  Python 3.7

### Other

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hey @krzysztof-slowinski ,

thanks for opening the issue. Can you show exactly how you use the `get_table_arn` method? I assume only that usage is causing this error to appear, correct?

Thanks,
Adam

**Comment by skinny85** [comment]
Also, can you show the contents of your `cdk.json` file?

**Comment by krzysztof-slowinski** [comment]
I have now updated the description with both @skinny85

**Comment by skinny85** [comment]
Thanks @krzysztof-slowinski. One more question. You wrote:

> There is a deployment role used for the deployment process of the entire infrastructure that is assumed before `cdk deploy` step using `aws sts assume-role`.

Is this behavior that you added, or do you observe CDK performing that assume Role? Because based on your `cdk.json` file, it should _not_ do that. If it does, can you please show me the output of executing `cdk deploy --verbose` that you get?

**Comment by krzysztof-slowinski** [comment]
The call to assume role is done before deployment explicitly so that the correct role with right privileges is used for the deployment process. I can generate `cdk deploy --verbose` output if needed.

**Comment by skinny85** [comment]
Yes, can you please:

1. Show me how do you perform the AssumeRole (is it in code? Is it "manually" through the AWS CLI before you execute `cdk deploy`? etc.).
2. The full output of `cdk deploy --verbose` when you get this error.

Thanks,
Adam

**Comment by krzysztof-slowinski** [comment]
1. Yes, it is a separate step before `cdk deploy`: `eval $(aws sts assume-role --role-arn $ROLE_ARN --role-session-name "Deployment$ENV" --duration-seconds 3600 | jq -r '.Credentials | @sh "export AWS_SESSION_TOKEN=\(.SessionToken)\nexport AWS_ACCESS_KEY_ID=\(.AccessKeyId)\nexport AWS_SECRET_ACCESS_KEY=\(.SecretAccessKey) "')`
2. Is there any specific part of the output that I should provide, because I will need to clean it up before adding here.

**Comment by skinny85** [comment]
> 2\. Is there any specific part of the output that I should provide, because I will need to clean it up before adding here.

Let's start with the stack trace.

**Comment by krzysztof-slowinski** [comment]
Interestingly enough, when I tried to reproduce the issue running `cdk deploy --verbose` and with version 1.121.0, I was not able to. We can close this issue and reopen it if it ever happens again I guess.

**Comment by skinny85** [comment]
Sounds good @krzysztof-slowinski, let us know if this happens again.
