### ISSUE TITLE
feat(events-targets): Add DLQ support for SQS target

### ISSUE THREAD

**Issue by draftbk** [aws/aws-cdk#16417]
This is an available feature through the AWS Console already. And is supported in many other target but not SQS: [https://github.com/aws/aws-cdk/issues/11612](https://github.com/aws/aws-cdk/issues/11612).

### Use Case

Use ``monocdk/aws-events-targets`` to create DLQ for events-targets as SQS

### Proposed Solution

```
import * as sqs from "@aws-cdk/aws-sqs";
import * as events from "@aws-cdk/aws-events";
import * as targets from "@aws-cdk/aws-events-targets";

const targetSQS = new sqs.Queue(this, 'targetSQS', {
  queueName: 'targetSQS',
});

const rule = new events.Rule(this, 'rule', {
  eventPattern: {
    source: ["aws.ec2"],
  },
});

const myDeadLetterQueue = new sqs.Queue(this, 'myDeadLetterQueue');

rule.addTarget(new targets.SqsQueue(targetSQS, {
  deadLetterQueue: myDeadLetterQueue
}));
```

**Comment by rix0rrr** [comment]
This could easily be copy/pasted from other rule targets that do support DLQs.
