### ISSUE TITLE
@aws-cdk/aws-events: passing data in details field of ScheduleEvent while creating the event using AWS CDK

### ISSUE THREAD

**Issue by anirudhagar13** [aws/aws-cdk#16414]
To pass details maps in the schedule event created using Rule construct in CDK, to trigger a lambda.

### Use Case

The lambda needs to perform different operations based on the context passed in the scheduled events. In this way, different events with different context can be scheduled for same lambda satisfying multiple use-cases.

### Proposed Solution

Replicate details field of the payload of a sample schedule event as given below: 

`{
  "id": "cdc73f9d-aea9-11e3-9d5a-835b769c0d9c",
  "detail-type": "Scheduled Event",
  "source": "aws.events",
  "account": "123456789012",
  "time": "2021-09-10T00:00:00Z",
  "region": "us-east-1",
  "resources": [
    "arn:aws:events:us-east-1:123456789012:rule/ExampleRule"
  ],
  "detail": {
    "key": "value"
  }
}`

### Other

My requirement is to pass some context in a scheduled rule that triggers the lambda. Within the lambda, the trigger is handled by using ScheduleEvent class. It has a .getDetail() method that returns the details map configured for the schedule event. While testing through a sample CloudWatch event created over AWS Lambda console, this works fine. But could not find a prop in the Rule construct to assign value to the details property. Things I have tried are: 

1. Using inputOptions in .addtarget(fun, [inputOptions]) but that is not received as ScheduleEvent in lambda handler.
2. Even tried using EventPatterns *details* prop but still the details map for the event is received as empty.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
You are probably looking to pass an `EventRuleInput` to your lambda target.

From this page: https://docs.aws.amazon.com/cdk/api/latest/docs/aws-events-readme.html#rule

```ts
onCommitRule.addTarget(new targets.SnsTopic(topic, {
  message: events.RuleTargetInput.fromObject(
    {
      DataType: `custom_${events.EventField.fromPath('$.detail-type')}`
    }
  )
}));
```

In your case you will be using `targets.LambdaFunction` and the property is called `event` (instead of `message`) but the pattern looks the same.
