### ISSUE TITLE
(kinesis firehose): add dynamic partitioning

### ISSUE THREAD

**Issue by davidpricedev** [aws/aws-cdk#16418]
Are there any plans yet to implement the ability to configure the firehose dynamic partitioning that was just released/announced (see: https://aws.amazon.com/about-aws/whats-new/2021/08/introducing-dynamic-partitioning-amazon-kinesis-data-firehose/)? 

I believe the only thing that needs to be added is the DynamicPartitioningConfiguration (see: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-kinesisfirehose-deliverystream-dynamicpartitioningconfiguration.html) on the ExtendedS3DestinationConfiguration.

### Use Case

I'd like to be able to use CDK instead of cfn to configure a firehose delivery stream that utilizes the new dynamic partitioning.

### Proposed Solution

I believe the code snippets below would be all that would be needed? I'm uncertain if there are any workarounds for features that aren't implemented yet.

On the ExtendedS3DestinationConfigurationProperty add 
```typescript
readonly dynamicPartitioningConfiguration?: CfnDeliveryStream.DynamicPartitioningConfigurationProperty;
```
and add the two new interfaces:
```typescript
interface DynamicPartitioningConfigurationProperty {
    readonly enabled: boolean;
    readonly retryOptions?: RetryOptionsProperty;
}
interface RetryOptionsProperty {
    readonly durationInSeconds: number;
}
```

### Other

A few other links about this new functionality: 

- https://aws.amazon.com/about-aws/whats-new/2021/08/introducing-dynamic-partitioning-amazon-kinesis-data-firehose/
- https://aws.amazon.com/blogs/big-data/kinesis-data-firehose-now-supports-dynamic-partitioning-to-amazon-s3/
- https://docs.aws.amazon.com/firehose/latest/dev/dynamic-partitioning.html
- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-kinesisfirehose-deliverystream-processorparameter.html

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by davidpricedev** [comment]
I believe this is the workaround: 
```typescript
import * as kinesisfirehose from "@aws-cdk/aws-kinesisfirehose";

const kinesisFirehose = new kinesisfirehose.CfnDeliveryStream(...);
kinesisFirehose.addPropertyOverride(
    "ExtendedS3DestinationConfiguration.DynamicPartitioningConfiguration",
    { Enabled: true, RetryOptions: { DurationInSeconds: 300 } }
)
```

**Comment by otaviomacedo** [comment]
Hi @davidpricedev. Thanks for raising this. Would you like to take a stab at this and implement this feature? I'd be happy to review it. See our [cotributing guide][1].

[1]: https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md

**Comment by ChristophrK** [comment]
I think this Issue is obsolete, since its already mentioned in the [docs](https://docs.aws.amazon.com/firehose/latest/APIReference/API_DynamicPartitioningConfiguration.html). And also in my experience dynamic partitioning can be added to Firehose with CDK.

**Comment by davidpricedev** [comment]
Agreed, closing.
