### ISSUE TITLE
(tools): use of deprecated wmic module windows

### ISSUE THREAD

**Issue by Calkines** [aws/aws-cdk#16419]
Cdk Cli uses WMI (Windows Management Instrumentation) cmdlets ([docs](https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Management/Get-WmiObject?view=powershell-5.1&viewFallbackFrom=powershell-7.1)) that is deprecated since version 3 of Power Shell. Today the cmdlet used is CIM (Common Information Model).

With the WMI the command to init a CDK folder cannot be executed.

> Command failed: wmic path win32_computersystemproduct get uuid
> 'wmic' is not recognized as an internal or external command,
> operable program or batch file.

### Reproduction Steps

Install cdk:

`npm install -g aws-cdk`

Try to initiate a cdk repo like this:

`cdk init`

### What did you expect to happen?

I expected the cdk prepare the first config files in folder.

### What actually happened?

The mentioned error above.

### Environment

* Windows 10 Version 21H1 (OS Build 19043.1165)
* Node version v12.16.3
* Powershell Desktop Edition 5.1.19041.1151
* or Powershell Core Edition 7.0.3

### Other

These links maybe useful:

* [Stack issue](https://stackoverflow.com/questions/54495023/what-library-for-powershell-6-contains-the-get-wmiobject-command)
* [MS Docs](https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Management/Get-WmiObject?view=powershell-5.1&viewFallbackFrom=powershell-7.1)
* [MS DevBlog Post](https://devblogs.microsoft.com/scripting/should-i-use-cim-or-wmi-with-windows-powershell/)

--- 

This is :bug: Bug Report

**Comment by JordanRickman** [comment]
I am getting a different but presumably related error on the same wmic module, also making it impossible to use `cdk init`.
```
> cdk init app --language typescript
Command failed: wmic path win32_computersystemproduct get uuid
ERROR:
Description = Not found
```

**Comment by JordanRickman** [comment]
> I am getting a different but presumably related error on the same wmic module, also making it impossible to use `cdk init`.
> 
> ```
> > cdk init app --language typescript
> Command failed: wmic path win32_computersystemproduct get uuid
> ERROR:
> Description = Not found
> ```

Correction: I cannot do **anything** with cdk, all commands fail with this error.
