### ISSUE TITLE
(pipelines): cross region S3 bucket - block public access

### ISSUE THREAD

**Issue by 0xjjoyy** [aws/aws-cdk#16411]
The cross region S3 bucket that is created should have block public access enabled by default.

Looking at the synthed template, the block public access is not enabled.

### Use Case

Ensure s3 block public access protection at the bucket level.

### Proposed Solution

Include for any cross region s3 buckets.

        "PublicAccessBlockConfiguration": {
          "BlockPublicAcls": true,
          "BlockPublicPolicy": true,
          "IgnorePublicAcls": true,
          "RestrictPublicBuckets": true
        }

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
Sounds good! PR welcome!
