### ISSUE TITLE
Cannot create cross region VPC with code pipelines

### ISSUE THREAD

**Issue by seawatts** [aws/aws-cdk#1642]
I am having trouble creating a vpc in a different region than what my code pipeline is in.

My code pipeline is in us-west-2
My VPC needs to be in us-east-1

I believe the problem is that when it goes to look up the availability zones it uses the region that it is being built in, which is us-west-2 and so it returns us-west-* availability zones.

https://github.com/awslabs/aws-cdk/blob/master/packages/%40aws-cdk/aws-ec2/lib/vpc.ts#L320

Error from executing the cloud formation change set.
```
Value (us-west-2b) for parameter availabilityZone is invalid. Subnets can currently only be created in the following availability zones: us-east-1f, us-east-1e, us-east-1d, us-east-1b, us-east-1c, us-east-1a. 
```

**Comment by eladb** [comment]
@skinny85 is this even possible?

**Comment by skinny85** [comment]
@seawatts how are you using the VPC in the stack that contains your CodePipeline?

**Comment by SomayaB** [comment]
Closing this issue since there hasn't been any activity on it in a while. Feel free to reopen.
