### ISSUE TITLE
S3 Deployment Assets with tokens result in different source object keys for zipped asset.

### ISSUE THREAD

**Issue by OrEisenberg** [aws/aws-cdk#16422]
I'm dynamically rendering a directory using tokens for an S3 deployment. That is, I'm creating a directory which contains files that have tokens embedded within them. I then try to use this directory as an S3 deployment `Source.asset` and everything works (the tokens get rendered upon deployment) but the hash that is used as the name for the source object key for this asset changes upon each deployment. This is presumably because the name of this key is being generated by hashing the directory contents *before* the tokens are resolved and since the (string) tokens, prior to rendering, will have random numbers as substrings (e.g., on one run, the unresolved token will be `${Token[TOKEN.123]}`, but on a subsequent run where none of the code has changed, it will be `${Token[TOKEN.456]}`), the hash generating the name of this key ends up being different. 

### Reproduction Steps

```python
bucket = aws_s3.Bucket(...)
with open('directory/file.txt', 'w') as f:
    f.write(bucket.bucket_name)
other_bucket = aws_s3.Bucket(...)
bucket_deployment = aws_s3_deployment(
    ...,
    sources=[aws_s3_deployment.Source.asset('directory'),
    destination=other_bucket,
    ...
)
```
This results in the following output on runs A & B of `cdk diff` (with no code changed):
```
[~] Custom::CDKBucketDeployment <resource-name>/CustomResource <resource-id>
 └─ [~] SourceObjectKeys
     └─ @@ -1,3 +1,3 @@
        [ ] [
        [-]   "<original hash>.zip"
        [+]   "<new hash A>.zip"
        [ ] ]
```
and
```
[~] Custom::CDKBucketDeployment <resource-name>/CustomResource <resource-id>
 └─ [~] SourceObjectKeys
     └─ @@ -1,3 +1,3 @@
        [ ] [
        [-]   "<original hash>.zip"
        [+]   "<new hash B>.zip"
        [ ] ]
```
Note that that is the *entire* diff.

### Environment

  - **CDK CLI Version:** 1.119.0
  - **Framework Version:** 2.0.0rc18
  - **Node.js Version:** 16.6.1
  - **OS:** macOS Big Sur 11.4
  - **Language (Version):** Python 3.8.11

--- 

This is :bug: Bug Report

**Comment by otaviomacedo** [comment]
Hi, @OrEisenberg. The doc string for `tokenCounter` explains why the token is different at each run:

https://github.com/aws/aws-cdk/blob/bc1293b8062a0792d6d1d9f058f308c72475e778/packages/@aws-cdk/core/lib/private/token-map.ts#L38-L63

In general, tokens are opaque. Depending on their particular value for _anything_ should be avoided.

**Comment by OrEisenberg** [comment]
@otaviomacedo This is very fair and were I creating this hash myself, I would agree that I had made an error. However, having a token embedded in an asset (which CDK then resolves upon upload to yield the crystalized value) is clearly intended behavior. I'm just using this functionality as CDK intended it to be used and because of this non-deterministic token representation you mention, the operation of deploying is *not* idempotent. To be perfectly clear *I am not generating this hash*. CDK is generating this hash by examining the contents of a file which is clearly allowed to have tokens in it (as evidenced by the fact that those tokens are crystalized upon upload)!

**Comment by eladb** [comment]
@OrEisenberg can you provide an example of a token you are using inside your files? I am surprised they get resolved during upload, and not even sure that's possible.

**Comment by or-atnv** [comment]
@eladb You're totally right, that's some hacky stuff we're doing on our end of which I was unaware! My sincerest apologies for wasting your time!

**Comment by OrEisenberg** [comment]
@eladb Ah yes, these tokens were getting resolved due to some hacky stuff on our end of which I was unaware.
!מצטער מאוד על הצרות

**Comment by eladb** [comment]
No worries. In fact the use case of generating content that includes deploy time values is something we are looking into.

https://github.com/aws/aws-cdk/issues/12903
