### ISSUE TITLE
(aws-fsx): can't set compression type in LustreConfiguration

### ISSUE THREAD

**Issue by wttat** [aws/aws-cdk#16431]
### Use Case

I know this  parameters could be set in cfn, but I wanna to use it by cdk natively.

https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_fsx/CfnFileSystem.html#aws_cdk.aws_fsx.CfnFileSystem.LustreConfigurationProperty
https://docs.aws.amazon.com/zh_cn/AWSCloudFormation/latest/UserGuide/aws-properties-fsx-filesystem-lustreconfiguration.html

### Proposed Solution

add support parameters

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by wttat** [comment]
any updates?

**Comment by trondhindenes** [comment]
There's lots of attributes that can't be set. It seems that the entire `LustreConfigurationProperty` is missing, and `LustreConfiguration` only contains a subset of the attributes.
