### ISSUE TITLE
(apigateway): get metrics from a resource

### ISSUE THREAD

**Issue by j-ohara** [aws/aws-cdk#16433]
With API GW CDK it is possible today to easily get metrics at the RestAPI level like this:
```java
RestApi restApi = new RestApi(...);
...
restApi.metricLatency();
restApi.metricServerError();
restApi.metricCount();
```

This is super useful. These metrics are provided by default with API GW. It is possible to get metrics at the resource level if you enable advanced Cloudwatch Metrics on the API. It would be great if we could have similar methods at the Resource level.

### Use Case
If an organization uses one API Gateway RestApi with many resources in it each linked to a unique integrations then the API level metrics are not very useful. When the metrics present a problem then it is unclear which specific resource/integration is the cause of it. Being able to easily get these metrics at the resource level would resolve this. 

### Proposed Solution

```java
IResource resource = new Resource(..);
...
resource.metricLatency();
resource.metricServerError();
resource.metricCount();
```

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by nija-at** [comment]
Hi @j-ohara,

The "Dimensions for metrics" section in the [API Gateway docs](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-metrics-and-dimensions.html) make available metrics for combination of Resource and Stage.
It is not possible to get the metrics for Resource alone.

Does this satisfy your use case? 
If so, in this case, the API will look like - 

```ts
resource.metricXxx(stage); // stage of type IStage
```

**Comment by j-ohara** [comment]
Hey @nija-at , 

That would be the ideal way of using these metrics I think. It would definitely solve my use case while remaining consistent with how it's done elsewhere in CDK.

**Comment by humanzz** [comment]
This is something I've also been looking for. Just adding to @nija-at's comment, the dimensions for this sort of metric also include `Method` so in total they are ApiName, Method, Resource, Stage which might mean the method needs to be passed in as well.
