### ISSUE TITLE
(dynamodb): Documentation around Table encryption

### ISSUE THREAD

**Issue by austevick** [aws/aws-cdk#16436]
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-dynamodb.Table.html#encryption

The documentation for the DynamoDB `Table` class says that by default, server-side encryption is enabled with an AWS owned customer master key. I was extending this class to set some common props my team always uses when I noticed that if `props.encryption` is `undefined`, no encryption is set. 

```ts
export class DynamoDBTable extends Table {
    constructor(scope: Construct, id: string, props: TableProps) {
        super(scope,id,props)
        
    }
}
```

Synthing this would yield a template like this:

```json
{
    "Resources": {
        "TableCD117FA1": {
            "DeletionPolicy": "Retain", 
            "Properties": {
                "AttributeDefinitions": [{"AttributeName": "id", "AttributeType": "S"}], 
                "KeySchema": [{"AttributeName": "id", "KeyType": "HASH"}], 
                "ProvisionedThroughput": {"ReadCapacityUnits": 5, "WriteCapacityUnits": 5}
            }, 
            "Type": "AWS::DynamoDB::Table", 
            "UpdateReplacePolicy": "Retain"
        }
    }
}
```

I was expecting to see `SSESpecification` specified in the Properties for the Table resource but I'm not seeing any encryption related properties set at all.

Should the docs be updated to reflect that by default, no encryption is done?

This was done using version `1.121.0` of `@aws-cdk/aws-dynamodb`

It's also possible I'm just misunderstanding something. In which case I'd be happy to admit I'm an idiot.

---

This is a 📕 documentation issue

**Comment by skinny85** [comment]
Hey @austevick,

thanks for opening the issue. You're right, the documentation is wrong; the default is for the Table to not be encrypted. We need to update the docs.

BTW, we welcome community contributions, so if you would like to submit us a PR changing the docs (they are [here](https://github.com/aws/aws-cdk/blob/36ff73809a37998e15176cb8815c118e7ea0c295/packages/%40aws-cdk/aws-dynamodb/lib/table.ts#L168-L197)), that would be amazing! Here's our "Contributing" guide: https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md.

Thanks,
Adam

**Comment by cokia** [comment]
@austevick If you are not willing to post the PR, can I proceed with the revision of the document? thanks
