### ISSUE TITLE
(core): deprecate the s3-assets and ecr-assets modules

### ISSUE THREAD

**Issue by njlynch** [aws/aws-cdk#16440]
The contents of both the `s3-assets` and `ecr-assets` modules arguably belong in `core`. This issue is to track the deprecation of both modules, along with moving the functionality into `core`. This is being tagged as part of the V2 GA work, so that the deprecated modules can be removed as part of the V2 release.

See https://github.com/aws/aws-cdk/pull/14160 for an attempt at this, which needs to be picked up and finished.

**Comment by madeline-k** [comment]
This obviously did not make it into the v2 release. And, based on #14160, implementation is blocked. Closing this issue, since we are unlikely to implement this. Please re-open if needed.
