### ISSUE TITLE
(codebuild): BuildSpec.fromObjectToYaml() skips conditions

### ISSUE THREAD

**Issue by therealsebo** [aws/aws-cdk#16451]
We´re trying to migrate our complex helm pipelines to CDK. In our current setup we uses AWS conditions without no worry.
In our current setup we use YAML styled buildspecs. Because of that we tried to use the method `fromObjectToYaml()`.
But as we checked the generated Json we saw that our conditional statements are missing. 

:point_right: **Hint** `BuildSpec.fromObject()` generates the "Fn:If"-Statements!

### Reproduction Steps

Here is a short example with just one condition to test. We use multiple conditions in each phase.

```ts
new PipelineProject(this, "PipelineProject", {
      buildSpec: BuildSpec.fromObjectToYaml({
        version: "0.2",
        phases: {
          build: {
            pre_build: {
              ...
            }
            commands: [
              "kubectl version",
              "echo Deploy started on `date`",
              "helm3 version",
              `helm3 repo add "${Fn.ref("HelmRepoName")}" "${Fn.ref("HelmRepoUrl")}"`,
              "helm3 repo update",
              "helm3 inspect chart $HELM_CHART",
              Fn.conditionIf(
                "SeparateTagIntoOwnKey",
                'helm3 upgrade $HELM_DEPLOY_ARGS --timeout "$TIMEOUT"s -f $HELM_VALUES_GLOBAL -f $HELM_VALUES --set $HELM_IMAGE_VALUE_KEY=$REPOSITORY_URI --set $HELM_TAG_VALUE_KEY=$TAG -i $HELM_DEPLOYMENT_NAME --namespace $NAMESPACE $HELM_CHART',
                'helm3 upgrade $HELM_DEPLOY_ARGS --timeout "$TIMEOUT"s -f $HELM_VALUES_GLOBAL -f $HELM_VALUES --set $HELM_IMAGE_VALUE_KEY=$IMAGE_URI -i $HELM_DEPLOYMENT_NAME --namespace $NAMESPACE $HELM_CHART'
              ),
              Fn.sub(
                "aws ecr put-image --repository-name ${CodebuildEcrRepository} --image-tag #{env}-active --image-manifest $MANIFEST"
              ),
            ],
          },
          post_build: {
            ...
          },
        },
      }),
    })
```

### What did you expect to happen?

Condition should be rendered (see  "Fn::If" )

```json
"  build:\n    commands:\n      - kubectl version\n      - echo Deploy started on `date`\n      - helm3 version\n      - helm3 repo add \"",
                {
                  "Ref": "HelmRepoName"
                },
                "\" \"",
                {
                  "Ref": "HelmRepoUrl"
                },
                "\"\n      - helm3 repo update\n      - helm3 inspect chart $HELM_CHART\n",
                {
                  "Fn::If": [
                    "SeparateTagIntoOwnKey",
                    "      - helm3 upgrade $HELM_DEPLOY_ARGS --timeout \"$TIMEOUT\"s -f $HELM_VALUES_GLOBAL -f $HELM_VALUES --set $HELM_IMAGE_VALUE_KEY=$REPOSITORY_URI --set $HELM_TAG_VALUE_KEY=$TAG -i $HELM_DEPLOYMENT_NAME --namespace $NAMESPACE $HELM_CHART\n",
                    "      - helm3 upgrade $HELM_DEPLOY_ARGS --timeout \"$TIMEOUT\"s -f $HELM_VALUES_GLOBAL -f $HELM_VALUES --set $HELM_IMAGE_VALUE_KEY=$IMAGE_URI -i $HELM_DEPLOYMENT_NAME --namespace $NAMESPACE $HELM_CHART\n"
                  ]
                },
                {
                  "Fn::Sub": "      - aws ecr put-image --repository-name ${CodebuildEcrRepository} --image-tag dev-active --image-manifest \"$MANIFEST\"\n"
                },
                "  post_build:\n 
```

### What actually happened?

The conditions are missing in the generated .json file. Instead of the if-condition a placeholder "unresolved-token" was generated
`- <unresolved-token>\n `

### Environment

  - **CDK CLI Version  :** 1.122.0 (build ae09c16) / 2.0.0-rc.21
  - **Framework Version:** 2.0.0-rc.21
  - **Node.js Version:** v16.9.0
  - **OS               :** Mac
  - **Language (Version):** TypeScript 4.4.2
### Other

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Thanks for opening the issue @therealsebo. Can confirm I was able to reproduce this.

The reason this happens is that the `fromObjectToYaml()` doesn't correctly implement Token substitution, which `fromObject()` does (as can be seen [here](https://github.com/aws/aws-cdk/blob/2a629dd7a86cc36c3a503bfc5957880c9edd4d49/packages/%40aws-cdk/aws-codebuild/lib/build-spec.ts#L73-L94)).

Unfortunately, this is a tough bug to fix, because the method used to correctly perform this serialization, `Stack.of(ctx.scope).toJsonString()`, doesn't support YAML, only JSON.
