### ISSUE TITLE
(assets): Code.fromAsset DOCKER ignore exclude '*' does not exclude directories

### ISSUE THREAD

**Issue by revmischa** [aws/aws-cdk#16453]
I want to ignore files when building with docker because I have a big project directory.
When I specify ignore mode = DOCKER and use exclude = `["*", "!foo"]` I would expect to only see `foo` during bundling.
I see all the files though.

### Reproduction Steps

```ts
import * as cdk from "@aws-cdk/core";
import * as lambda from "@aws-cdk/aws-lambda";
import { IgnoreMode } from "@aws-cdk/core";
import { Runtime } from "@aws-cdk/aws-lambda";

export class HelloCdkStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    new lambda.Function(this, "MyFunction", {
      runtime: Runtime.NODEJS_12_X,
      handler: "index.handler",
      code: lambda.Code.fromAsset(__dirname + "/..", {
        exclude: ["*", "!foo"],
        ignoreMode: IgnoreMode.DOCKER,
        bundling: {
          image: Runtime.NODEJS_14_X.bundlingImage,
          command: ["ls", "-l"],
        },
      }),
    });
  }
}
```

### What did you expect to happen?

Expected to see only `foo` listed

### What actually happened?

```
➜  hello-cdk git:(master) ✗ cdk synth
Bundling asset HelloCdkStack/MyFunction/Code/Stage...
total 856
-rw-r--r--   1 501 games      0 Sep 10 14:29 bar
drwxr-xr-x   3 501 games     96 Sep 10 14:28 bin
-rw-r--r--   1 501 games    808 Sep 10 14:28 cdk.json
drwxr-xr-x   8 501 games    256 Sep 10 14:35 cdk.out
-rw-r--r--   1 501 games      0 Sep 10 14:29 foo
-rw-r--r--   1 501 games    157 Sep 10 14:28 jest.config.js
drwxr-xr-x   3 501 games     96 Sep 10 14:35 lib
drwxr-xr-x 374 501 games  11968 Sep 10 14:29 node_modules
-rw-r--r--   1 501 games    583 Sep 10 14:30 package.json
-rw-r--r--   1 501 games 852249 Sep 10 14:30 package-lock.json
-rw-r--r--   1 501 games    543 Sep 10 14:28 README.md
drwxr-xr-x   3 501 games     96 Sep 10 14:28 test
-rw-r--r--   1 501 games    650 Sep 10 14:28 tsconfig.json
```

### Environment

  - **CDK CLI Version  : latest**
  - **Framework Version: 1.122.0**
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):** 

### Other

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
Looks like [AssetStaging](https://github.com/aws/aws-cdk/blob/7cf567668f9c7930d56f8f9fa23439519d68f3da/packages/%40aws-cdk/core/lib/asset-staging.ts#L189-L195) does not honour the `exclude` property when bundling.

Passing this over to @eladb to determine if this is a bug or was intentionally skipped.

**Comment by NGL321** [comment]
Hey @revmischa,

I may be mistaken in this assertion, but I believe that since the `exclude` option is used to exclude files from the bundle and you are concerned about passing files INTO the bundling container, the comparison here is moot.

To echo what jogold said above `fromDockerBuild()` seems to fit your case better. Can you confirm whether this resolves your problem?

😸

**Comment by revmischa** [comment]
Not an issue for me anymore, thanks

**Comment by gshpychka** [comment]
@NGL321 so what does the `exclude` prop do, then? It has no effect for me.
