### ISSUE TITLE
(aws-backup): BackupResource has limited support for Aurora RDS

### ISSUE THREAD

**Issue by james-mathiesen** [aws/aws-cdk#16457]
BackupResource does not support RDS Aurora databases.

```
public static fromRdsDatabaseInstance(instance: IDatabaseInstance): BackupResource
```

however the type IDatabaseInstance does not encompass Aurora databases.  I believe additional methods are
needed to support these additional types:

```
IDatabaseCluster
IServerlessCluster
```

Additionally, `BackupResource::fromConstruct()` ignores Aurora databases even though they are supported by AWS Backup.

### Use Case

There is no obvious way to backup Aurora databases from the CDK even though AWS Backup fully supports them.

The escape-hatch like `BackupResource::fromArn()` is an effective workaround.

**Comment by ahmetsevki** [comment]
> The escape-hatch like BackupResource::fromArn() is an effective workaround.

Plus one that `fromConstruct` doesn't put the cluster into protected resources. However, how do you get the arn of the `DatabaseCluster` to put inside `fromArn`?

**Comment by ahmetsevki** [comment]
I constructed the arn for the cluster via:
```
    const clusterArn = `arn:aws:rds:${process.env.CDK_DEFAULT_REGION}:${process.env.CDK_DEFAULT_ACCOUNT}:clusterIdentifier:${postgresRDSCluster.clusterIdentifier}`
```
And then called 
```
plan.addSelection('BackupPlanSelection', {
      role: backupSelectionRole,
      resources: [BackupResource.fromArn(clusterArn)],
    })
```

But the cloudformation errors with: `Specified 'rds' resource is not supported by AWS Backup.`

What do you pass to `fromArn` part?

**Comment by ahmetsevki** [comment]
I did the following:
```typescript
    const clusterArn = `arn:aws:rds:${process.env.CDK_DEFAULT_REGION}:${process.env.CDK_DEFAULT_ACCOUNT}:cluster:${postgresRDSCluster.clusterIdentifier}`
// ...
    plan.addSelection('BackupPlanSelection2', {
      role: backupSelectionRole,
      resources: [BackupResource.fromArn(clusterArn)],
    })
```
I can see my cluster arn in plan selection, however the protected resources still do not have my cluster.
Did you pass the cluster arn, or the individual database server arns for it to show up in protected resources?

**Comment by jumic** [comment]
I found this note in the [documentation](https://docs.aws.amazon.com/aws-backup/latest/devguide/listing-backups.html#list-by-protected-resources):
> Only resources that have been backed up by AWS Backup are listed under Protected resources.

Did you wait until a backup should be created?
