### ISSUE TITLE
(cli): does not pass command line profile argument to synth

### ISSUE THREAD

**Issue by mariusingjer** [aws/aws-cdk#16473]
cdk synth does not pass --profile argument to the node process which executes the cdk app.

### Use Case

I want to be able to initiate the AWS SDK within the CDK app and not get credentials associated with the default profile.

### Proposed Solution

Extend this method and add --profile argument as an environment variable passed to the node process:

```
/** Invokes the cloud executable and returns JSON output */
export async function execProgram(aws: SdkProvider, config: Configuration): Promise<cxapi.CloudAssembly> {
  const env: { [key: string]: string } = { };

  const context = config.context.all;
  await populateDefaultEnvironmentIfNeeded(aws, env);
```

Configuration.settings already contains this information (which is passed in the above method):

```
const sdkProvider = await SdkProvider.withAwsCliCompatibleDefaults({
    profile: configuration.settings.get(['profile']),
```

* [ ] :wave: I may be able to implement this feature request
* [x] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
We recommend you don't make SDK calls in your CDK app, and therefore we don't make it easy.

See [**Commit cdk.context.json to avoid nondeterministic network lookups
**](https://aws.amazon.com/blogs/devops/best-practices-for-developing-cloud-applications-with-aws-cdk/)

If you definitely know you want to, you know how to achieve it. You can always set `AWS_PROFILE`.
