### ISSUE TITLE
Turn on deprecation warnings for all CDK modules

### ISSUE THREAD

**Issue by otaviomacedo** [aws/aws-cdk#16474]
As part of [RFC 287], we want to make sure that the CDK doesn't use any deprecated elements. Otherwise, users could see their applications fail (see #16471).

For this, we need to globally set the environment variable `DEPRECATED` to `error` so that, by default, all tests that exercise some deprecated element will fail. For Jest tests, for example, this can be accomplished by `setupFilesAfterEnv`, where we set the environment variable, which can be overridden on individual tests where we do want to use deprecated modules.

As part of this task, all tests should be passing at the end, after the necessary replacements of deprecated elements.

[RFC 287]: https://github.com/aws/aws-cdk-rfcs/blob/master/text/287-cli-deprecation-warnings.md

**Comment by nija-at** [comment]
This is now complete - https://github.com/aws/aws-cdk/pull/17328

The forward merge to v2-main is also complete - https://github.com/aws/aws-cdk/pull/17536s
