### ISSUE TITLE
(kinesisfirehose): enable customer-managed server-side encryption on delivery streams by default

### ISSUE THREAD

**Issue by BenChaimberg** [aws/aws-cdk#16487]
Change the default value of [`DeliveryStreamProps.encryption`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-kinesisfirehose.DeliveryStream.html#encryptionspan-classapi-icon-api-icon-experimental-titlethis-api-element-is-experimental-it-may-change-without-noticespan) to be `StreamEncryption.CUSTOMER_MANAGED`. However, if a Kinesis data stream is specified as the source, in which case delivery stream encryption cannot be enabled, the default will be to whatever the data stream encryption is set to (which defaults to customer-managed). This will entail some modifications to the following lines: https://github.com/aws/aws-cdk/blob/9bbfd185c2383612e2be7317a091b72cc5e7a120/packages/%40aws-cdk/aws-kinesisfirehose/lib/delivery-stream.ts#L330-L343

* [X] :wave: I may be able to implement this feature request
* [X] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by skinny85** [comment]
Additionally, let's explain clearly to customers in the docs what's the difference between the `StreamEncryption.AWS_OWNED` and `StreamEncryption.CUSTOMER_MANAGED` options, by linking to [this documentation page](https://docs.aws.amazon.com/streams/latest/dev/costs-performance.html).

This can be done in the ReadMe of the module, in the inline JSDocs responsible for the encryption properties, or both - I leave the details to the discretion of whoever implements this 🙂.
