### ISSUE TITLE
(secretsmanager/rds): addReplicaRegion on Secret created by fromGeneratedSecret 

### ISSUE THREAD

**Issue by davidmckenzie** [aws/aws-cdk#16480]
The ISecret interface that is produced by the RDS `fromGeneratedSecret` method does not implement `addReplicaRegion`. 

### Use Case

DB credentials should always be replicated across regions along with DB snapshots to aid in DR/BC. When creating a new RDS cluster, the auto-generated credentials should be replicated across multiple regions.

### Proposed Solution

Either `fromGeneratedSecret` should allow you to access a full `Secret` object, or `addReplicaRegion` should be added to `ISecret`, in a similar way to `addRotationSchedule`

### Other

I tagged both secretsmanager and rds as I'm not sure which side needs to implement this :)

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by skinny85** [comment]
Hey @davidmckenzie,

thanks for opening the issue. I believe you can add the replica regions right now in RDS by going:

```ts
const cluster = new rds.DatabaseCluster(this, 'Cluster', {
  credentials: rds.fromGeneratedSecret(...
  // ...
});
(cluster.secret as secretsmanager.Secret).addReplicaRegion('us-east-2');
```

But I guess the point is to get rid of the that cast there, and make `addReplicaRegion()` available in `ISecret`, do I understand your feature request correctly...?

Thanks,
Adam

**Comment by davidmckenzie** [comment]
Oh neat, thanks! I'm weak in Typescript, didn't know you could do that :)

But yes, it probably would still make sense for it to be available in ISecret, since I assume you could add replicas to imported secrets as well without danger.

**Comment by jogold** [comment]
How about adding an option to `fromGeneratedSecret()`?

```ts
const cluster = new rds.DatabaseCluster(this, 'Cluster', {
  credentials: rds.fromGeneratedSecret('username', { replicaRegions: [{ region: 'us-east-2' }] }),
  // ...
});
```

`addReplicaRegion()` is not available in `ISecret` because it's not available for an imported secret.
