### ISSUE TITLE
(codepipeline): Snyk action

### ISSUE THREAD

**Issue by movenus** [aws/aws-cdk#16491]
Use a CodePipeline 3P integration action (Snyk) in CDK.

### Use Case

I'd like to create a CodePipeline Pipeline that has a 3P integration stage. I'd like to make this CodePipeline Pipeline in a CDK project. I would also like to connect to GitHub or BitBucket as the source, and model a build stage in CDK.

### Proposed Solution

Use 3P action in CodePipeline CDK.
https://docs.aws.amazon.com/cdk/api/latest/docs/aws-codepipeline-actions-readme.html

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by skinny85** [comment]
Thanks for opening the issue @movenus! Turns out, we already have a request for this integration open here: https://github.com/aws/aws-cdk/issues/16232, so please +1 that issue!
