### ISSUE TITLE
(elasticsearch): Elasticsearch must be authorised to describeSubnets

### ISSUE THREAD

**Issue by miklinson** [aws/aws-cdk#16492]
`Received response status [FAILED] from custom resource. Message returned: Unauthorized Operation: Elasticsearch must be authorised to describeSubnets
(RequestId: f49d7ea9-6d61-4951-98fc-eeda71bb2451)`

### Reproduction Steps
```javascript
const { Domain, ElasticsearchVersion, TLSSecurityPolicy } = require('@aws-cdk/aws-elasticsearch');
const { Role, PolicyStatement, Effect, AnyPrincipal, ArnPrincipal } = require('@aws-cdk/aws-iam');

const esDomain = new Domain(this, 'MyElasticsearchDomain', {
      version: ElasticsearchVersion.V7_10,
      domainName: domainName,
      vpc: vpc, 
      ebs: {
          enabled: true,
          volumeSize: elasticsearchEbsVolume,
      },
      capacity: {
          dataNodeInstanceType: instanceType,
          dataNodes: 2,
      },
      cognitoKibanaAuth: {
          enabled: true,
          identityPoolId: cognitoIdentityPoolId,
          role: Role.fromRoleArn(this, 'CognitoRoleArn', cognitoRoleArn),
          userPoolId: cognitoUserPoolId,
      },
      enforceHttps: true,
      tlsSecurityPolicy: TLSSecurityPolicy.TLS_1_2,
      advancedOptions: {
          'rest.action.multi.allow_explicit_index': 'true',
          'override_main_response_version': 'true',
      },
      accessPolicies: [
          new PolicyStatement({
              effect: Effect.ALLOW,
              actions: ['es:*'],
              principals: [
                  new AnyPrincipal(), // remove this in prod
                  new ArnPrincipal(`arn:aws:sts::${env.account}:assumed-role/${cognitoIdentityPoolAuthRole}/CognitoIdentityCredentials`),
              ],
              resources: [`arn:aws:es:${env.region}:${env.account}:domain/${domainName}/*`],
          })
      ],
      zoneAwareness: {
          enabled: true,
          availabilityZoneCount: 2, // default is 2
      }
});
```

### What did you expect to happen?
Elasticsearch domain to be created.

### What actually happened?
Elasticsearch domain was  created but there's no access policy.

### Environment

  - **CDK CLI Version  : 1.122.0**
  - **Framework Version: 1.122.0**
  - **Node.js Version: v14.17.6** 
  - **OS               : Ubuntu 20.04**
  - **Language (Version): JavaScript** 

### Other
Similar issue in [stackoverflow](https://stackoverflow.com/questions/69184185/cdk-elasticsearch-setting-accesspolicies-property-causes-stack-to-faill)

--- 

This is :bug: Bug Report

**Comment by avishayil** [comment]
I actually encountered the same bug, and I found out that it is caused by the `accessPolicies` proprety, which creates a custom resource that configures the access policy. If you'll remove the `accessPolicies` property the error goes away.

**Comment by miklinson** [comment]
@avishayil that's also my workaround for now. Removing the `accessPolicies` during cdk deploy then manually add it in the Elasticsearch domain after.

**Comment by avishayil** [comment]
You can try to configure the access policy yourself using the custom resource CDK construct that implements AwsSdkCall: https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_custom-resources.AwsSdkCall.html, but it might be complicated because the API call is `UpdateDomainConfig` and you might need to supply all the configuration parameters https://docs.aws.amazon.com/opensearch-service/latest/developerguide/configuration-api.html.

**Comment by prashanttct07** [comment]
There was an issue with Service Linked Role (SLR), which has been fixed and deployed. Please check now and you should not be getting any such error while creating the domain.

**Comment by miklinson** [comment]
@prashanttct07 confirmed. I've successfully created an Elasticsearch domain without any issues. Can you please share the link saying the issue was with with Service Linked Role (SLR) and the confirmation that it has been fixed and deployed. Thanks!

**Comment by miklinson** [comment]
Closing the issue now, the bug seems to be resolved. Also, [Elasticsearch was rebranded to Opensearch](https://github.com/aws/aws-cdk/commit/e6c4ca5e71934e890eabe41190e9c2d0bd42aefb)
