### ISSUE TITLE
(aws_cdk.core): Allow intrinsics in CustomResource and CfnCustomResource parameter service_token

### ISSUE THREAD

**Issue by ddl-denis-parnovskiy** [aws/aws-cdk#16498]
Allow code like this:

```
function = CfnFunction(...)
resource = CfnCustomResource(... service_token=function.get_att('Arn'))
```

Currently CDK only accepts string for both:
```
jsii.errors.JSIIError: Expected a string, got {"$jsii.byref":"@aws-cdk/core.Intrinsic@10092"}
```

### Use Case

When deploying lambda along with the stack, Arn of the lambda is not known and we need a function like `Fn::GetAtt` to get Arn.

No, we do not want to use the middleman Provider class because we do not need any of the functionalities there and do not want additional 5 resources.

### Proposed Solution

Expand intrinsic references in service_token field.

### Other

The previous same Feature Request https://github.com/aws/aws-cdk/issues/15437 was closed with a comment "works as documented".

But this is not a bug, this is a feature request.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
Use `Token.as_string(function.get_att('Arn'))`
