### ISSUE TITLE
(cli): support hotswapping resources in Nested Stacks

### ISSUE THREAD

**Issue by revmischa** [aws/aws-cdk#16508]
Big fan of the work in https://github.com/aws/aws-cdk/pull/15748/files and wish I could use it in my application. I'm building an application of medium size on CDK and I have split it up into nested stacks. Hotswap does not work with nested stacks. It would be terrific if it did, especially as the nested stacks add considerable deployment time as it is.

### Proposed Solution

[tryHotswapDeployment](https://github.com/aws/aws-cdk/pull/15748/files#diff-8258763f4c84d495e36e521cae3924f392f06579c6b77ef365e8ca95cc8aac3cR17) probably needs to be run recursively on nested stacks? Not sure what the most elegant solution is.

---

This is a :rocket: Feature Request

**Comment by skinny85** [comment]
Thanks for opening the issue @revmischa! We definitely plan on supporting this hotswapping resources in Nested Stacks, we just haven't prioritized it yet 🙂.

Note to everyone: feel free to +1 this issue, a high number of upvotes will make it more likely we'll start on this feature earlier 🙂.

**Comment by Lewenhaupt** [comment]
@revmischa I'm doing a workaround myself currently where I use the root stack as the scope for all constructs in my nested stacks. I just toggle this behaviour with a flag passed to the root stack such that I can avoid it when deploying to our staging/production environments. I.e. fast deploys for individual developer environments and better stack structure in prod/staging.
It's definitely not perfect and means that the naming structure of resources won't match between environments etc. But it solves the issue while we're waiting for this.

**Comment by comcalvi** [comment]
pretty sure this has been closed by #18950.
