### ISSUE TITLE
(aws-elasticloadbalancerv2): Unable to add more than one certificate to NLB via CDK

### ISSUE THREAD

**Issue by AbhiramIyer** [aws/aws-cdk#16509]
### The Question

I am unable to synthesize a NetworkListener with multiple ACM certificates. Synthesis with one certificate works as expected. As per the [documentation](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-elasticloadbalancingv2.NetworkListener.html#certificates) this is supported, but during synthesis I get this error: 
" 
`Resource handler returned message: "Up to '1' certificate ARNs can be specified, but '2' were specified (Service: ElasticLoadBalancingV2, Status Code: 400, Request ID: <removed>, Extended Request ID: null)" (RequestToken: <removed>, HandlerErrorCode: ServiceLimitExceeded)`
"

### Environment

  - **CDK CLI Version:** 
   1.120.0
  - **Module Version:** 
   1.120.0
  - **Node.js Version:** 
  14.17.0
  - **OS:** 
   all
  - **Language (Version):** 
  Typescript

### Other information

Code snippet :  
    
    // let certificates = array of ACM certificates

    const listenerCertificates = certificates.map((c) => {
        return ListenerCertificate.fromArn(c.certificateArn);
     });

    loadBalancer.addListener("TlsListener", {
        port: 443,
        protocol: Protocol.TLS,
        certificates: listenerCertificates,        
  });

**Comment by AbhiramIyer** [comment]
As per https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-listener.html -"You must provide exactly one certificate if the listener protocol is HTTPS or TLS". Hence this is not a functional issue. API documentation could be updated to clarify this.

**Comment by peterwoodworth** [comment]
I can update the docs here to make this clear. Thanks for letting us know!
