### ISSUE TITLE
aws_cdk.aws_rds.DatabaseCluster, Set IAM manage role

### ISSUE THREAD

**Issue by evanerwee** [aws/aws-cdk#16514]
## :question: General Issue

Using class aws_cdk.aws_rds.DatabaseCluster I'm unable to find a way to set the RDS Cluster Manage IAM roles. This can be set using the AWS Console, Click on the Cluster Instance under RDS. Select IAM roles to add to this cluster, and add an existing role that have access, to for example Lambda.

### The Question
How do I set the RDS Cluster Manage IAM role in the CDK?

### Environment

  - **CDK CLI Version:** 1.22
  - **Module Version:** 1.22
  - **Node.js Version:** 16.5.0
  - **OS:** Windows 10
  - **Language:** Python 3.9

### Other information
The role is used for Lambda access from the RDS Stored Procedure.

**Comment by skinny85** [comment]
Hey @evanerwee,

thanks for opening the issue. Do you happen to know if this feature is available in CloudFormation? I [went through the docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbcluster.html), but I couldn't find anything about setting the Cluster manage Role.

Thanks,
Adam

**Comment by evanerwee** [comment]
That’s a really good question. I did some more research and it appears to be a service link role.
  

  
 https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-servicelinkedrole.html
  

  
If that is the case I assume I have to go via the IAM path.
  

  
Will investigate tonight and post an update.
  
  
  
    
  

  
  
>

**Comment by skinny85** [comment]
Thanks!

**Comment by evanerwee** [comment]
I do not have a resolution yet, but I have found this: From what I seen below the AssociatedRoles is what I have to set.

{
  "Type" : "AWS::RDS::DBInstance",
  "Properties" : {
      "AllocatedStorage" : String,
      "AllowMajorVersionUpgrade" : Boolean,
      "AssociatedRoles" : [ DBInstanceRole, ... ],
      "AutoMinorVersionUpgrade" : Boolean,
      "AvailabilityZone" : String,
      "BackupRetentionPeriod" : Integer,
      "CACertificateIdentifier" : String,
      "CharacterSetName" : String,
      "CopyTagsToSnapshot" : Boolean,
      "DBClusterIdentifier" : String,
      "DBInstanceClass" : String,
      "DBInstanceIdentifier" : String,
      "DBName" : String,
      "DBParameterGroupName" : String,
      "DBSecurityGroups" : [ String, ... ],
      "DBSnapshotIdentifier" : String,
      "DBSubnetGroupName" : String,
      "DeleteAutomatedBackups" : Boolean,
      "DeletionProtection" : Boolean,
      "Domain" : String,
      "DomainIAMRoleName" : String,
      "EnableCloudwatchLogsExports" : [ String, ... ],
      "EnableIAMDatabaseAuthentication" : Boolean,
      "EnablePerformanceInsights" : Boolean,
      "Engine" : String,
      "EngineVersion" : String,
      "Iops" : Integer,
      "KmsKeyId" : String,
      "LicenseModel" : String,
      "MasterUsername" : String,
      "MasterUserPassword" : String,
      "MaxAllocatedStorage" : Integer,
      "MonitoringInterval" : Integer,
      "MonitoringRoleArn" : String,
      "MultiAZ" : Boolean,
      "OptionGroupName" : String,
      "PerformanceInsightsKMSKeyId" : String,
      "PerformanceInsightsRetentionPeriod" : Integer,
      "Port" : String,
      "PreferredBackupWindow" : String,
      "PreferredMaintenanceWindow" : String,
      "ProcessorFeatures" : [ ProcessorFeature, ... ],
      "PromotionTier" : Integer,
      "PubliclyAccessible" : Boolean,
      "SourceDBInstanceIdentifier" : String,
      "SourceRegion" : String,
      "StorageEncrypted" : Boolean,
      "StorageType" : String,
      "Tags" : [ Tag, ... ],
      "Timezone" : String,
      "UseDefaultProcessorFeatures" : Boolean,
      "VPCSecurityGroups" : [ String, ... ]
    }
}

**Comment by evanerwee** [comment]
See also: https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraMySQL.Integrating.Authorizing.IAM.AddRoleToDBCluster.html

**Comment by skinny85** [comment]
So, I think you need to create a `ParameterGroup`, and then add the parameters from that doc, like `aws_default_s3_role`, `aws_default_lambda_role`, etc., and the values are the ARNs of the Roles?

You can do that today with the CDK.

**Comment by skinny85** [comment]
And, of course, use that `ParameterGroup` for your `DatabaseCluster`.

**Comment by evanerwee** [comment]
I have use the parameter group but learned I also have to   
  
set the RDS:
  

  
 AWS::RDS::DBInstance
  
  
  
    
  
  
  
   AssociatedRoles
  
  

 I see that attribute is not in the CDK it appears but in cloudformation.   

  
Can I write some custom code to set that attribute ?
  
>

**Comment by skinny85** [comment]
That's available through the [`s3ImportRole` and `s3ExportRole` properties of `DatabaseCluster`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-rds.DatabaseCluster.html#s3exportrole).

**Comment by evanerwee** [comment]
Silly question, why the s3? I am confused a bit.

**Comment by skinny85** [comment]
Because that's what the associated Roles are used for (at least today).

**Comment by evanerwee** [comment]
I do not find that method/attribute . Added that attribute to the cluster object and spit out an error.

Could you provide an example.

**Comment by skinny85** [comment]
What error? What code did you add to your CDK app?

I need a lot more info than "it spit out an error" 🙂.

**Comment by evanerwee** [comment]
I will post code a bit later. The property you suggest I can find on the RDS DBCluster. Using the property is not recognized. Hence me asking for a code sample.
  
  
  
    
  

  
  
>

**Comment by skinny85** [comment]
Sure. [Here's an example from CDK unit tests](https://github.com/aws/aws-cdk/blob/1c258363f1e6fb54ad4b995ad16e3d983f44954a/packages/%40aws-cdk/aws-rds/test/cluster.test.ts#L776-L792).

**Comment by evanerwee** [comment]
Code example perfect but this does not set the manage group in RDS Cluster. I have tested. Neither S3 Import nor Export set the property. 

It appears that this can't be automated. I will escalate using our normal channels as an issue. Thank you for all your help.

**Comment by skinny85** [comment]
OK then 🙂.
