### ISSUE TITLE
(ec2): Elastic IPs not released when VPC deploy fails / stack destroyed

### ISSUE THREAD

**Issue by ahammond** [aws/aws-cdk#16518]
I tried to create a VPC in us-east-1 using the following:

```typescript
    const vpc = new aws_ec2.Vpc(this, 'Vpc', {
      cidr: '10.115.0.0/16',
      maxAzs: 999, // we want to be eligible as a default vpc, which requires subnets in every AZ.
      subnetConfiguration: [
        {
          name: 'Public',
          subnetType: aws_ec2.SubnetType.PUBLIC,
          cidrMask: 22,
        },
      ],
    });
```

It failed because it ran out of ElasticIPs. This is a sandbox account, only allows 5 ElasticIPs but cdk wants to allocate 1 per AZ for the public subnets and us-east-1 has 6 AZs. So far so good, but then I went into the console and discovered that there were still 5 EIPs still allocated, even after deleting the stack. Not sure if this is a CDK issue or CFN issue.

### Reproduction Steps

Deploy stack containing VPC with a public subnet. Destroy stack, see Elastic IP remains

### What did you expect to happen?

Resources should be cleaned up when stack is destroyed.

### What actually happened?

Elastic IPs were not released.

### Environment

  - **CDK CLI Version  :**  v2.0.0-rc.21
  - **Framework Version:** v2.0.0-rc.21
  - **Node.js Version:** v14.17.5
  - **OS               :** MacOS 11.6
  - **Language (Version):** TypeScript 4.4.3

--- 

This is :bug: Bug Report

**Comment by njlynch** [comment]
Typically, EIPs are retained if they are still in use. Often, you'll see the reason why an EIP couldn't be deleted when attempting to delete the stack associated with them.

The example you provide above does not allocate EIPs, although the a VPC with all the defaults (`new ec2.Vpc(this, 'Vpc');`) does allocate one per AZ. You should be able to see what the EIP is associated with, either through the console or via the [DescribeAddresses](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeAddresses.html) API.

If you are able to reproduce a case where EIPs are retained that should have been deleted (without any associations), can you post a minimal reproducible sample?
