### ISSUE TITLE
(aws-route53-targets (or aws-route53 or aws-ec2)): No child with id: 'Resource'` when referencing existing vpc endpoint in route 53 arecord

### ISSUE THREAD

**Issue by aherrmann13** [aws/aws-cdk#16544]
### `No child with id: 'Resource'` when referencing existing vpc endpoint in route 53 arecord

getting error `No child with id: 'Resource'` with the code below 

```
// not the actual values
const vpcEndpointId = 'some endpoint id that I have verified exists'
const recordName = 'my record name'

const endpoint = InterfaceVpcEndpoint.fromInterfaceVpcEndpointAttributes(this, "VPCEndpoint", {
    vpcEndpointId: vpcEndpointId,
    port: 443
})
const hostedZone = new PrivateHostedZone(this, "HostedZone", { vpc, zoneName: dependency.dns });

new ARecord(this, `ARecord`, {
    zone: hostedZone,
    target: RecordTarget.fromAlias(new InterfaceVpcEndpointTarget(endpoint)),
    recordName: recordName
});
```
seems to be failing on the line [here](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-route53-targets/lib/interface-vpc-endpoint-target.ts#L11)

this works fine when I create a VPC endpoint but when I reference an existing endpoint it breaks

context on the problem:
there is an external service that takes care of configuring cross region private links, so for same region private links I want to configure in the cdk and for cross region I want to reference the vpc endpoint that was created for me in my aws account

### Environment

  - **CDK CLI Version:** 1.122.0
  - **Module Version:** monocdk 1.72.0
  - **Node.js Version:** 12.22.5
  - **OS:** Windows 10 | macOS Big Sur
  - **Language (Version):** TypeScript (4.4.2)

### Other information
I can't share the source code to make it easier to repro, let me know if you need any more information

**Comment by peterwoodworth** [comment]
Hey @aherrmann13, thanks for submitting this issue. 

This is a bug, an imported resource shouldn't have children. The [InterfaceVpcEndpointTarget](InterfaceVpcEndpointTarget) class should only take in an InterfaceVpcEndpoint instead of an IInterfaceVpcEndpoint. Either that, or the pattern should be reworked to function with imported resources. @njlynch what do you think?
