### ISSUE TITLE
(aws-s3): synth fails with Yarn PnP when autoDeleteObjects is enabled

### ISSUE THREAD

**Issue by asterikx** [aws/aws-cdk#16552]
When `autoDeleteObjects` is set to `true`, `yarn cdk synth` fails when using [yarn with PnP](https://yarnpkg.com/features/pnp). When set to `false` (or omitted), `yarn cdk synth` succeeds.

### Reproduction Steps

```ts
const bucket = new s3.Bucket(this, 'MyBucket', {
  removalPolicy: cdk.RemovalPolicy.DESTROY,
  autoDeleteObjects: true, // <-- this line causes synth to fail
});
```

### What did you expect to happen?

`yarn cdk synth` succeeds regardless of whether `autoDeleteObjects` is enabled or not.

### What actually happened?

`yarn cdk synth` fails if `autoDeleteObjects` is enabled:

```
MYUSER@MyHost some-project % yarn synth
/Users/MYUSER/some-project/.pnp.cjs:64081
  return Object.assign(new Error(`${code}: ${message}`), {
                       ^
Error: EROFS: read-only filesystem, open '/node_modules/@aws-cdk/aws-s3/lib/auto-delete-objects-handler/__entrypoint__.js'
    at makeError (/Users/MYUSER/some-project/.pnp.cjs:64081:24)
    at EROFS (/Users/MYUSER/some-project/.pnp.cjs:64111:10)
    at ZipFS.prepareWriteFile (/Users/MYUSER/some-project/.pnp.cjs:66420:30)
    at ZipFS.writeFileSync (/Users/MYUSER/some-project/.pnp.cjs:66408:14)
    at fallback (/Users/MYUSER/some-project/.pnp.cjs:67250:14)
    at /Users/MYUSER/some-project/.pnp.cjs:67270:18
    at /Users/MYUSER/some-project/.pnp.cjs:67584:58
    at ZipOpenFS.getZipSync (/Users/MYUSER/some-project/.pnp.cjs:67729:14)
    at ZipOpenFS.makeCallSync (/Users/MYUSER/some-project/.pnp.cjs:67584:17)
    at /Users/MYUSER/some-project/.pnp.cjs:67264:19
Subprocess exited with error 1
```

### Environment

  - **CDK CLI Version  : 1.123.0 (build fad855e)**
  - **Framework Version: 1.123.0**
  - **Node.js Version: v14.17.6**
  - **OS               : macOS 11.6**
  - **Language (Version): TypeScript (4.4.3)**

--- 

This is :bug: Bug Report

**Comment by otaviomacedo** [comment]
I don't know much about Yarn with PNP, but from a quick research I've done, there are some things to try:

* Make sure you're using the latest version of Yarn.
* Check your `~/.yarnrc` to make sure that it's not using `/npm-packages-offline-cache` as the local cache directory.

And, just out of curiosity, why do you need to use Yarn in the first place and not just run a globally installed `cdk synth`?

**Comment by jogold** [comment]
With PnP you cannot write to the `node_modules`. The [custom resource provider from `@aws-cdk/core`](https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/core#the-corecustomresourceprovider-class) used for `autoDeleteObjects` tries to write a file in there:

https://github.com/aws/aws-cdk/blob/5aa6ac0008b2bd0556fda021124f6838173274b4/packages/%40aws-cdk/core/lib/custom-resource-provider/custom-resource-provider.ts#L165-L166

This is not specific to `@aws-cdk/aws-s3`. Any node module making use of the same custom resource provider from core would face the same issue.
