### ISSUE TITLE
[CDKv2GA]: Support new @deprecations post-GA

### ISSUE THREAD

**Issue by njlynch** [aws/aws-cdk#16566]
Currently, when we `@deprecate` an API element on `master`, the element is stripped from `v2`. Once we GA v2, we can no longer strip these elements, as they would be breaking changes for v2 APIs.

We need to define and implement a strategy for how to continue to deprecate elements on `master` post-GA release, without stripping these elements from `v2`.

One approach _might_ be a deny-/allow-list of deprecated elements. Other, more creative approaches, welcome.

**Comment by nija-at** [comment]
> update the logic on v2 to only strip @deprecated api elements if they are in the list

How are you going to achieve this? 
Currently, stripping deprecation is a feature in jsii. Are we going to add it there?
If so, worth engaging @RomainMuller early.
