### ISSUE TITLE
(@aws-cdk/aws-apigateway): SpecRestApi: Build correct ARN for Authorizer

### ISSUE THREAD

**Issue by zMeadz** [aws/aws-cdk#16583]
When declaring an API gateway, you must grant the Gateway permissions to invoke the correct Lambda or Authorizer. Currently, the `SpecRestApi` has the `arnForExecuteApi()` method which will generate an ARN which may be used to grant invocation access to a Lambda. However, this ARN is the incorrect format for Authorizers, producing a permission error when trying to invoke the Authorizer (via AWS console > Gateway > Authorizers > Test). It would be useful to have a method called `arnForExecuteAuthorizer()` which could help clear up this confusion.

Specifically, `arnForExecuteApi()` generates an ARN like `arn:aws:execute-api:${region}:${account}:*/*/*`, but Authorizers require the more-specific format `arn:aws:execute-api:${region}:${account}:${gateway.restApiId}/authorizers/*`. 

### Use Case

```typescript
  const apiGateway = new apigateway.SpecRestApi(this.stack, 'MyGateway', {
      apiDefinition: apigateway.ApiDefinition.fromInline(path),
      endpointTypes: [apigateway.EndpointType.REGIONAL],
      restApiName: 'MyGateway',
      deployOptions: {
        description: 'An OpenAPI gateway',
        stageName: 'live',
        loggingLevel: apigateway.MethodLoggingLevel.ERROR,
        metricsEnabled: true,
        dataTraceEnabled: true,
      },
    });

    
    someLambdaWithoutAuthorization.addPermission('NoAuthorizationLambdaPermisson',
      {
        principal: new iam.ServicePrincipal('apigateway.amazonaws.com'),
        action: 'lambda:InvokeFunction',
        sourceArn: apiGateway.arnForExecuteApi(), // Works for Lambdas that are NOT used as Authorizers
      },
    );

    authorizerLambda.addPermission('AuthorizedLambdaPermisson',
      {
        principal: new iam.ServicePrincipal('apigateway.amazonaws.com'),
        action: 'lambda:InvokeFunction',
        sourceArn: apiGateway.arnForExecuteAuthorizer() // Must be arn:aws:execute-api:${region}:${account}:${gateway.restApiId}/authorizers/*
      },
    );
```

### Proposed Solution

See above Use Case

### Other

- It cost me some time to find the reason why API Gateway was not satisfied with the wildcard ending `*/*/*`, but was eventually able to search CloudTrail to compare what was being deployed to what was being changed when granting authorization to an Authorizer Lambda via the console. For screenshots / context, [this issue](https://github.com/aws/chalice/issues/670) is relevant (although is for Chalice) as it's the top result when I was debugging the issue.
- Thanks in advance for looking!

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change
---

This is a :rocket: Feature Request

**Comment by nija-at** [comment]
@zMeadz - can you provide a link to documentation that backs up your case that the ARN for authorizer lambdas are different?

**Comment by shanereid** [comment]
Hi @nija-at, I've encountered this same problem and he is correct.

Documentation outlining the different arn formats can be found at the bottom of [this page](https://docs.aws.amazon.com/apigateway/latest/developerguide/arn-format-reference.html).

- Lambda Authorizer Source ARN format is `arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${SpecRestApiId}/authorizers/*`.
- ARN format generated by `arnForExecuteApi` is `arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${SpecRestApiId}/*/*/*`.

the `/*/*/*` does not match `/authorizers/*`.

I've managed to work around this (in python) with the following:

```
this_stack = cdk.Stack.of(scope)
authorizer_source_arn = cdk.Fn.join(
    "/",
    [
        cdk.Fn.join(
            "",
            [
                f"arn:aws:execute-api:{this_stack.region}:{this_stack.account}:",
                self.api.rest_api_id,
            ],
        ),
        "authorizers/*",
    ],
)

self.lambda_authorizer.function.add_permission(
    "ApiInvokePermission",
    principal=ServicePrincipal("apigateway.amazonaws.com"),
    action="lambda:InvokeFunction",
    source_arn=authorizer_source_arn,
)
```

**Comment by zMeadz** [comment]
@nija-at See @shanereid comment about authorizer ARN format and documentation [here](https://docs.aws.amazon.com/apigateway/latest/developerguide/arn-format-reference.html)

**Comment by mohammadn0man** [comment]
I was facing the same issue for adding Function trigger permission. 
using arn_for_execute_api() does the job for me.
```
apigw_swagger_api.arn_for_execute_api(
    method=method_type,
    path=endpoint_path,
),
```
https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_apigateway/RestApiBase.html#aws_cdk.aws_apigateway.RestApiBase.arn_for_execute_api
