### ISSUE TITLE
(lambda-nodejs): Deploys on NodeJS 12.x are broken, 14.x is OK

### ISSUE THREAD

**Issue by adam-nielsen** [aws/aws-cdk#16595]
It currently appears to be impossible to deploy a working NodeJS function on the NodeJS 12.x runtime if your code uses compiled modules, as the Docker environment CDK uses for bundling uses a different NodeJS version to that used in the Lambda environment.

Upon deploying such a Lambda function, you only get this message in the Cloudwatch logs:

```
2021-09-22T09:08:21.456Z	undefined	ERROR	Uncaught Exception 	
{
    "errorType": "Error",
    "errorMessage": "The module '/var/task/node_modules/netcdf4/build/Release/netcdf4.node'\nwas compiled against a different Node.js version using\nNODE_MODULE_VERSION 83. This version of Node.js requires\nNODE_MODULE_VERSION 72. Please try re-compiling or re-installing\nthe module (for instance, using `npm rebuild` or `npm install`).",
    "stack": [
        "Error: The module '/var/task/node_modules/netcdf4/build/Release/netcdf4.node'",
        "was compiled against a different Node.js version using",
        "NODE_MODULE_VERSION 83. This version of Node.js requires",
        "NODE_MODULE_VERSION 72. Please try re-compiling or re-installing",
        "the module (for instance, using `npm rebuild` or `npm install`).",
        "    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1057:18)",
        "    at Module.load (internal/modules/cjs/loader.js:863:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:702:16)",
        "    at Module.require (internal/modules/cjs/loader.js:887:19)",
        "    at require (internal/modules/cjs/helpers.js:74:18)",
        "    at /var/task/index.js:138:130",
        "        -> /var/asset-input/adfd/extractCDF.js:12:17",
        "    at /var/task/index.js:1:807",
        "    at /var/task/index.js:160:2483",
        "        -> /var/asset-input/adfd/adfdImport.js:18:20",
        "    at /var/task/index.js:1:807",
        "    at Object.<anonymous> (/var/task/index.js:342:289)",
        "        -> /var/asset-input/lambda/pf-dre-ingest-adfd-import.js:7:24"
    ]
}
```

Deploying the CDK stack uses this Docker image:

```
Sending build context to Docker daemon  119.3kB
Step 1/11 : ARG IMAGE=public.ecr.aws/sam/build-nodejs12.x
```

I tried removing the image with `docker rmi public.ecr.aws/sam/build-nodejs12.x` and it re-downloaded it, but nothing changed.

Luckily I was able to change my code to use the NodeJS 14.x runtime which still works, but it would be good to understand why this unexpected failure suddenly happened with no warning.

### Reproduction Steps

1. Use a Lambda function that has a compiled module, such as [sharp](https://github.com/lovell/sharp).
2. Don't have esbuild on your machine, so that Docker is used for bundling.
3. Build and deploy, observe it does not run once deployed.

### Environment

  - **CDK CLI Version  :** npx cdk
  - **Framework Version:** 1.222.0
  - **Node.js Version:** 16.x outside of Docker
  - **OS               :** Linux
  - **Language (Version):** JS

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
Can you provide a full working reproducible sample? See http://sscce.org/.

**Comment by adam-nielsen** [comment]
Hmm, my bad, when I do a minimal sample it works fine.  All I can guess is that because I'm running the code locally, maybe my local compiled version got deployed instead of it being rebuilt?  I tried to reproduce that as well but I could not, so I'm a bit mystified.

Apologies for the noise, next time I will do a reproduction first before opening an issue.
