### ISSUE TITLE
[CDKv2GA]: Create "canaries" for CDKv2

### ISSUE THREAD

**Issue by njlynch** [aws/aws-cdk#16593]
Exactly like the CDKv1 infrastructure, CDKv2 needs to have a regularly scheduled job that downloads and installs the CDK, and uses it to deploy (and delete) a stack. The canary should be monitored and alarmed exactly as the existing v1 canary is today.

**Comment by madeline-k** [comment]
Paused this while I was on-call last week. Resuming today, should have a PR out in a day or so!
