### ISSUE TITLE
(aws-ecs): configFileValue should be optional in FirelensOptions

### ISSUE THREAD

**Issue by dan-lind** [aws/aws-cdk#16594]
configFileValue is defined as a required value in FirelensOptions

### Reproduction Steps
configFileValue  should be marked as optional here
https://github.com/aws/aws-cdk/blob/7966f8d48c4bff26beb22856d289f9d0c7e7081d/packages/%40aws-cdk/aws-ecs/lib/firelens-log-router.ts#L64

### What did you expect to happen?
I expect that a config like this example for Datadog is valid
https://github.com/aws-samples/amazon-ecs-firelens-examples/blob/mainline/examples/fluent-bit/datadog/task-definition.json

### What actually happened?
Above config doesn't work since configFileValue is mandatory.

### Environment
  - **Framework Version: v1.124

--- 

I'd be happy to provide an MR for this

This is :bug: Bug Report

**Comment by PettitWesley** [comment]
Fixed via this: https://github.com/aws/aws-cdk/pull/20636

**Comment by PettitWesley** [comment]
I think it only made it into CDK v2 tho: https://github.com/aws/aws-cdk/releases/tag/v2.34.0

**Comment by PettitWesley** [comment]
@kaizencc Can you close this issue? I lack perms.
