### ISSUE TITLE
translate: add an L2 for AWS Translate

### ISSUE THREAD

**Issue by sarthakchatterjeecvent** [aws/aws-cdk#16600]
We are trying to create a custom terminology using translate.

### Use Case

i am able to import terminology using aws cli like this:

aws translate import-terminology \
    --name name-venue-terminology-en \
    --description "Creating a randomterminology in AWS Translate" \
    --merge-strategy OVERWRITE \
    --data-file /Users/sarthak.chatterjee/Downloads/file.csv \
    --profile=sandbox \
    --region=us-east-1 \
    --terminology-data Format=CSV

### Proposed Solution

need a cdk library for this to be able to use the construct to automate the same in typescript. 

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by ryparker** [comment]
Hey @sarthakchatterjeecvent 👋🏻, thanks for opening the feature request.

This sounds like it will require a new l2 construct to be created with some lookup functionality.

I am marking this issue as p2 which means that we are unable to work on this immediately. We use +1s to help us prioritize our work, and as always we are happy to take contributions if anyone is interested to pick this up and submit a PR (please make sure to follow our [contribution guidelines](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md).) :pray:

**Comment by andreialecu** [comment]
I've been able to use custom resources for this:

Here's some sample code:
```ts

    const physicalResourceId =
      custom_resources.PhysicalResourceId.of("your_terminology_name");

    new custom_resources.AwsCustomResource(this, "TranslateTerminology", {
      policy: custom_resources.AwsCustomResourcePolicy.fromSdkCalls({
        resources: custom_resources.AwsCustomResourcePolicy.ANY_RESOURCE,
      }),
      onUpdate: {
        service: "Translate",
        action: "importTerminology",
        parameters: {
          MergeStrategy: "OVERWRITE",
          Name: physicalResourceId.id,
          TerminologyData: {
            File: readFileSync(
              path.join(
                __dirname,
                "./translate-terminology/custom-terminology.csv"
              ),
              "utf-8"
            ),
            Format: "CSV",
          },
          Description: "Poker on Tour Terminology in AWS Translate",
        },
        physicalResourceId,
      },
      onDelete: {
        service: "Translate",
        action: "deleteTerminology",
        parameters: {
          Name: new custom_resources.PhysicalResourceIdReference(),
        },
      },
    });
```

See: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Translate.html#importTerminology-property
