### ISSUE TITLE
(core) RemovalPolicy DELETE does not exist (should be DESTROY)

### ISSUE THREAD

**Issue by hyooj** [aws/aws-cdk#16605]
The comments for `Resource.applyRemovalPolicy(policy: RemovalPolicy)` makes reference to a RemovalPolicy called `DELETE`, instead it should reference `DESTROY`.

This mistake is replicated to all resources. For example:
* https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cloudwatch.Alarm.html#applywbrremovalwbrpolicypolicy

Code:
* https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/core/lib/resource.ts#L206

> The resource can be deleted (RemovalPolicy.DELETE), or left in your AWS account for data recovery and cleanup later (RemovalPolicy.RETAIN).

should be 

> The resource can be deleted (RemovalPolicy.DESTROY), or left in your AWS account for data recovery and cleanup later (RemovalPolicy.RETAIN).

The same comment could also make reference to `SNAPSHOT` for supporting stateful resources. However, this optional feedback is not the focus of this issue.

---

This is a 📕 documentation issue

**Comment by rix0rrr** [comment]
Thanks for reporting.
