### ISSUE TITLE
(aws_certificate_manager): Failure to delete Cert and Custom Domain name in same cloud formation task create undeleteable certificates

### ISSUE THREAD

**Issue by adipon** [aws/aws-cdk#16608]
When using the Python AWS CDK to create cloud formation stacks, trying to delete a Certificate from ACM and Custom Domains associated with the certificate will lead to a locked certificate. The Custom Domain Name will be deleted, however, the ALB resources that are associated with the Certificate will remain. Their association can only be removed through help by the AWS service team. 

### Reproduction Steps

Multiple cloud formation jobs were executed as outlined below:

1. Create a DnsValidatedCertificate and used it to create a Custom Domain Name in API Gateway, associating it all with a cloud formation stack. 

```
dns_root_zone = route_53.PublicHostedZone.from_lookup(
            self,
            id="dns-root-zone",
            domain_name="example.com",
            private_zone=False
)
cert = acm.Certificate(
            self, 
            'my-cert',
            domain_name = "*.example.com",
            validation=acm.CertificateValidation.from_dns(hosted_zone=dns_root_zone)
)
aws_apigateway.DomainName(
            scope=self,
            id="my-domain-name",
            certificate=cert,
            domain_name="api.example.com",
            endpoint_type=aws_apigateway.EndpointType.REGIONAL,
            security_policy=aws_apigateway.SecurityPolicy.TLS_1_2,
 )
```

2. Delete the Certificate and Custom Domain Name resources and remove any linkages to the cloud formation stack.

### What did you expect to happen?

I expected the Certificate and Custom Domain Name resources to be deleted. 

### What actually happened?

The second build eventually timed out and I saw that the Custom Domain had been deleted but the certificate had not. It showed that it was in use by ALB resources owned by the API Gateway Account. I was unable to disassociate the certificate from the ALBs or delete the certificate. 

### Environment

  - **CDK CLI Version  : 1.118.0**
  - **Framework Version: 1.118.0**
  - **Node.js Version: v14.15.5** 
  - **OS               : AMI Linux**
  - **Language (Version): Python (3.8.8)** 

### Other

There is a workaround to this issue. If you split up the build process for the second build to delete the Custom Domain Name only and leaving the certificate untouched. Then in another build, remove the Certificate. This process will successfully delete both resources. 

--- 

This is :bug: Bug Report

**Comment by shkomg** [comment]
whenever you add custom domain and create a certificate for it - the created certificate gets assigned to 3 load balancers from outside account 392220576650 (this isn't my account)

in my example it was:
`
arn:aws:elasticloadbalancing:us-east-1:392220576650:loadbalancer/app/prod-iad-1-cdtls-1-2-277/b1cb3400e7a9db56
arn:aws:elasticloadbalancing:us-east-1:392220576650:loadbalancer/app/prod-iad-1-cdtls-1-2-759/7d770e82a1215d63
arn:aws:elasticloadbalancing:us-east-1:392220576650:loadbalancer/app/prod-iad-1-cdtls-1-2-974/1d8777e732c08fd2
`

this way that certificate can't be deleted, thus such cdk stack - destroyed.

as mentioned here https://repost.aws/knowledge-center/acm-certificate-resources the current solution to ask aws support to delete that manually. 

how to recreate - just create new certificate:
here is aws cdk javascript code
```
const {
    Certificate,
    CertificateValidation,
} = require("aws-cdk-lib/aws-certificatemanager");

        const certificateAPI = new Certificate(this, "api-example-com", {
            domainName: "api.example.com",
            validation: CertificateValidation.fromDns(hostedZone),
        });
```

to avoid this problem - may need to deploy stack with another name...

keep in mind that aws technical support is paid.... so i don't know how to delete that resource they automatically created...
