### ISSUE TITLE
(aws-codebuild): Cannot modify CodeStar connection on CodeBuild once deployed

### ISSUE THREAD

**Issue by jpSimkins** [aws/aws-cdk#16618]
## :question: General Issue

Ok, this has been a bit interesting for me to figure out what is going on... I did not report this as a bug yet as I am not sure if this is a known limitation or if this is really a bug.

I have identified 2 concerns:

1. Replacing a CodeStar arn for CodeBuild Project is not possible with the CDK 
    - Still uses old connection even after deploying with new connection arn as it only updates the Role with the CodeStar arn policy, no way to update CodeBuild?
2. CodeStar connections still work once deleted (deleted from both AWS and Bitbucket)
    - 30 hours since deletion and still working

### The Question

 1. How can I update the CodeBuild CodeStar connection through the CDK? 
 1. Why is the deleted CodeStar connection still working?

It seems that updating CodeBuild's CodeStar connection is not possible through the CDK. With this setup (this is a source for a pipeline), I am only able to add the CodeStar arn to the Role and I am not sure how CodeBuild even gets the correct connection in the first place. The issue here is that it's impossible (it seems) to update the CodeStar connection. For PROD systems, this is a major concern. Destroying and redeploying is not possible (this is part of a pipeline process for PROD and it would take these systems offline).

### Environment

 - **CDK CLI Version :**  `1.124.0 (build 65761fe)`
 - **Module Version :**  `1.124.0`
 - **Node.js Version :**  `v14.17.4`
 - **OS               :**  `Linux Zeus 5.11.0-34-generic #36~20.04.1-Ubuntu SMP Fri Aug 27 08:06:32 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
 - **Language (Version):** `Typescript (Version 4.1.5)`

### User Scenario:

I deployed a project using my Bitbucket connection (CodeStar arn) instead of the company user's connection. No biggie, after a few days I  just changed the arn and deployed it again (verifying the CodeStar arn replacement during deployment). I also deleted the CodeStar connection and deleted the app authentication in Bitbucket for my user to prevent this from happening in the future.

The deployment updated the role as expected but CodeBuild still uses the old user's connection. After a few days, my CodeBuild projects were failing so I looked in the console for CodeBuild, when editing the Source, I was shown:

![Selection_005](https://user-images.githubusercontent.com/4512118/134233623-08c8eb8d-c618-48e4-ab7c-b9a7a7e5110c.png)

This leads me to believe it is still using my user CodeStar connection that I deleted from AWS and Bitbucket.

From that screen, I had to  remove the connection and create the connection manually. So now Bitbucket has an app authentication for CodeStar and CodeBuild. This should only be for CodeStar but since I had to manually change it in CodeBuild, I now have a separate connection for CodeBuild. Ideally, this is not what I want.

I wrote a test to duplicate this issue, as this is for PROD systems, I wanted to clearly demonstrate what is happening. During testing I noticed that it's still using my deleted user's connection. (I confirmed it was deleted in Bitbucket and in the [console](https://console.aws.amazon.com/codesuite/settings/connections)). This concerned me as I would not expect that behaivor. I searched for BitBucket's OAuth token lifetime and found that it has a [2 hour lifetime](https://support.atlassian.com/bitbucket-cloud/docs/use-oauth-on-bitbucket-cloud/#Refresh-tokens). At this point, I have no idea why that token is still working as it shouldn't be. 

**Test Stack:**

```typescript
import {Construct, RemovalPolicy, Stack, StackProps} from '@aws-cdk/core';
import {
  BuildSpec,
  ComputeType,
  LinuxBuildImage,
  Project,
  FilterGroup,
  EventAction,
  Source,
  Artifacts,
} from '@aws-cdk/aws-codebuild';
import {CompositePrincipal, Effect, PolicyStatement, Role, ServicePrincipal} from '@aws-cdk/aws-iam';
import {Bucket} from '@aws-cdk/aws-s3';

export class DebugStack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);

    // Setup
    const USER_CODESTAR_ARN = 'arn:aws:codestar-connections:us-east-1:XXXXXXXXXXX:connection/xxxxxxxxxxxxxxxxx';
    const COMPANY_CODESTAR_ARN = 'arn:aws:codestar-connections:us-east-1:XXXXXXXXXXX:connection/yyyyyyyyyyyyyyyy';
    const REPO_OWNER = 'comapny-name';
    const REPO_NAME = 'some-repo-name';
    const REPO_BRANCH = 'master';

    /**
     * The idea here is to first deploy with the USER_CODESTAR_ARN.
     *
     * Once deployed, delete the user's CodeStar arn and remove access in BitBucket from app authorization for the user's connection (should be AWS CodeStar).
     *
     * First, you will notice this still works, due to the token lifetime (assumption), not sure why the token still works after deletion but that may be a BitBucket concern.
     *
     * I suggest waiting until the token expires before re-deploying with the COMPANY_CODESTAR_ARN.
     *
     * Once the token is expired, re-deploy it again using the COMPANY_CODESTAR_ARN.
     *
     * You will notice, CodeBuild still says it cannot refreh the token (still using the user's connection).
     * To resolve, you must go into CodeBuild, edit the Source, disconnect BitBucket and then connect it manually.
     * Ideally, this would be done during the deployment and not need to be manually done.
     * By doing this manually in CodeBuild, you are creating another app authentication in BitBucket for CodeBuild which is not desired.
     *
     * This shows that CodeBuild is not being updated with the new CodeStar details when it gets redeployed.
     * It seems only the role is, which makes sense as that is all that is being shown during deployment and all that can be configured.
     */
    // Uncomment and comment the lines when testing
    const _CODESTAR_ARN = USER_CODESTAR_ARN; // Deploy with user CodeStar ARN
    // const _CODESTAR_ARN = COMPANY_CODESTAR_ARN; // Deploy with company CodeStar ARN

    /** Shouldn't need to modify anything past here  */

    // Role used for codebuild
    const _role = new Role(this, 'bugDuplicatorRole', {
      assumedBy: new CompositePrincipal(
        new ServicePrincipal('codestar.amazonaws.com'),
        new ServicePrincipal('codebuild.amazonaws.com'),
      ),
      description: 'Created to identify a bug with Codestar and Codebuild',
      roleName: 'debug-codebuild-bug-duplicator-role',
    });
    // Codestar policy
    const codestarPolicyStatement = new PolicyStatement({
      effect: Effect.ALLOW,
      actions: ['codestar-connections:UseConnection'],
      resources: [_CODESTAR_ARN],
    });
    // Add codestar access to role
    _role.addToPrincipalPolicy(codestarPolicyStatement);

    // Artifacts bucket
    const _artifactsBucket = new Bucket(this, 'bugDuplicatorArtifactsBucket', {
      bucketName: 'debug-codebuild-bug-duplicator-artifacts-bucket',
      removalPolicy: RemovalPolicy.DESTROY,
    });

    // Define Bitbucket source
    const _bbSource = Source.bitBucket({
      cloneDepth: 1,
      fetchSubmodules: true,
      owner: REPO_OWNER,
      repo: REPO_NAME,
      reportBuildStatus: true,
      webhook: true,
      webhookFilters: [
        // Only on PUSH and PR Merged do we build (no support for partial message yet to allow for no builds)
        FilterGroup.inEventOf(EventAction.PUSH, EventAction.PULL_REQUEST_MERGED)
          .andBranchIs(REPO_BRANCH)
          .andCommitMessageIsNot('#NOBUILD'),
      ],
    });

    // Codebuild Project
    const tmp: Project = new Project(this, 'bugDuplicatorProject', {
      badge: true,
      projectName: 'bugDuplicator-SourceArtifact',
      source: _bbSource,
      artifacts: Artifacts.s3({
        bucket: _artifactsBucket,
        path: 'debug',
        includeBuildId: false,
        name: 'bugDuplicatorArtifacts',
      }),
      role: _role,
      description: 'Created to identify a bug with Codestar and Codebuild',
      environment: {
        buildImage: LinuxBuildImage.AMAZON_LINUX_2_3,
        computeType: ComputeType.SMALL,
      },
      buildSpec: BuildSpec.fromObject({
        version: '0.2',
        artifacts: {
          files: ['**/*'],
        },
      }),
    });

  }
}

```

_I could not fully validate my test due to the CodeStar token not expiring (at 30 hours since deleting). Since this is the reason for me finding this issue in the first place, I know it will eventually expire. So I don't feel the need to wait for this before posting this (I will update once I see it expire). I know it will expire because it did when I switched the arns from my user to the company's user. I believe it make take a couple days as that's what happened to me in the first place. I am keeping track of how long this is currently._

**Comment by skinny85** [comment]
Hey @jpSimkins,

thanks for opening the issue. I think you're having problems because connecting to BitBucket is done differently for CodeBuild and CodePipeline, and you're mixing both here.

CodeBuild uses credentials global to a given account and region. They can be set manually, through the console, or using the [`BitBucketSourceCredentials` class](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-codebuild.BitBucketSourceCredentials.html) in CDK (but, again, only one credential is allowed to exist in given account+region combination - any additional ones will fail to be registered. We explain it [in the CDK docs here](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-codebuild-readme.html#credentials)).

CodeBuild does _not_ use the CodeStarConnections way of connecting to BitBucket. That's what CodePipeline uses.

Hope this helps!

Thanks,
Adam

**Comment by jpSimkins** [comment]
Thanks for your response @skinny85 that does help me a lot.
