### ISSUE TITLE
aws-stepfunctions-tasks: Add support for emr-containers

### ISSUE THREAD

**Issue by wojtekwalczak** [aws/aws-cdk#16621]
I wanted to orchestrate my EMR-on-EKS workflow using StepFunctions and I noticed that `emr-containers` integration is not supported in `aws-stepfunctions-tasks` at the moment.

Based on this [blog post](https://aws.amazon.com/blogs/big-data/orchestrate-an-amazon-emr-on-amazon-eks-spark-job-with-aws-step-functions/) I assume that `emr-containers` are supported by Step Functions.

### Use Case

Orchestrate EMR-on-EKS workflows using Step Functions.

### Proposed Solution

If no one is working on this task, I believe I could give it a shot, basing on the implementation of `EMR` integrations in `aws-stepfunctions-tasks`.

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by kaizen3031593** [comment]
Hi @wojtekwalczak! Closing this issue in favor of the duplicate #15234. There is a PR in flight, #15242, however, it does not look like it is being currently worked on anymore. We welcome community contributions and if you think you could give it a shot, take a look at the PR and see if you can draw some inspiration from there!
