### ISSUE TITLE
(aws-elasticloadbalancerv2): Cdk deployment fails when a the certificate resource is updated, but there is an NLB resource that references the certificate resource  

### ISSUE THREAD

**Issue by AbhiramIyer** [aws/aws-cdk#16622]
I have an application wherein I'm creating a certificate resource using the Certificate construct in one stack (A) and passing it on a NLB construct in a different stack (B). Both stacks are deployed to the same account. The initial deployment was successful. However on updating the certificate resource (in my case adding a new SAN entry), deployment of stack A failed with the error that the certificate is still in use by the NLB.

### Reproduction Steps

stack A:

Before 
```
this.certificate = new Certificate(this, "MyAcmCertificate"), {
      "mydomain.com", 
      subjectAlternativeNames: ["mydomain2.com"]
      validation: CertificateValidation.fromDnsMultiZone(record), 
    });
```

After adding one more domain to the SAN
```
this.certificate = new Certificate(this, "MyAcmCertificate"), {
      "mydomain.com", 
      subjectAlternativeNames: ["mydomain2.com", "mydomain3.com"]
      validation: CertificateValidation.fromDnsMultiZone(record), 
    });
```

stack B:

 ```
const loadBalancer = <code to create a NLB>
 
 const listenerCertificate = ListenerCertificate.fromArn(props.certificate.certificateArn);

  loadBalancer.addListener("TlsListener"), {
    port: 443,
    protocol: Protocol.TLS,
    certificates: [listenerCertificate],
    defaultTargetGroups: [defaultTargetGroup],
  });
```

### What did you expect to happen?

I expected the NLB to pick up the new certificate. 

### What actually happened?

deployment of stack A failed with the error that the certificate is still in use by the NLB.

### Environment

 - **CDK CLI Version:** 
   1.120.0
  - **Module Version:** 
   1.120.0
  - **Node.js Version:** 
  14.17.0
  - **OS:** 
   all
  - **Language (Version):** 
  Typescript

### Other

--- 

This is :bug: Bug Report

**Comment by njlynch** [comment]
Hi @AbhiramIyer ,

When you add a new SAN to a certificate, a new certificate must be created, and the old one deleted. As StackA only has knowledge of the certificate (and not the NLB), it deploys the new certificate, and then (as part of cleanup) tries to delete the old one. This fails, as you've seen.

This is a classic example of inter-stack dependencies that are a bit nuanced to get right. A workaround to do what you want would be to first create a new `Certificate` (with the new SANs), and use it as you wish (assign to `this.certificate`, pass to the NLB), but also keep around the old, unmodified `Certificate`. When you deploy both stacks, Stack A will request the new cert and Stack B will get its cert updated. Then you can remove the old `Certificate` and deploy Stack A again, which will remove the old cert.

Hope that helps! I'm going to close this out, as the above should resolve the issue. If you have any follow-ups, feel free to comment and mention me.
