### ISSUE TITLE
aws-ecs: Error - Secrets from ssm parameter for firelens options

### ISSUE THREAD

**Issue by sebdec** [aws/aws-cdk#16624]
It's possible to have now secrets in the options for firelens
I tried to configure it with a secret from ssm parameter.
I got an error:
failed: Error [ValidationError]: Parameters [apiKey] referenced by template have types not supported by CloudFormation.

### Reproduction Steps

```ts
const taskDefinition = new ecs.Ec2TaskDefinition(this, 'TaskDef');
taskDefinition.addContainer('TheContainer', {
  image: ecs.ContainerImage.fromRegistry('example-image'),
  memoryLimitMiB: 256,
  logging: ecs.LogDrivers.firelens({
    options: {
      // ... log driver options here ...
    },
    secretOptions: {
          apikey: ecs.Secret.fromSsmParameter(
            ssm.StringParameter.fromStringParameterAttributes(this, 'apikey', {
              parameterName: 'apikey',
              version: 0,
            }),
          ),
        },
  })
});
```

### What did you expect to happen?

deploy correctly with the configured secret

### What actually happened?

error validation with cdk diff or cdk deploy

### Environment

  - **CDK CLI Version  :** 1.124.0
  - **Framework Version:** 1.124.0
  - **Node.js Version:** 14
  - **OS               :** mac
  - **Language (Version):** ts

--- 

This is :bug: Bug Report

**Comment by sebdec** [comment]
Thanks Peter, I think it's related indeed.

**Comment by ansnoussi** [comment]
- Support for secretOptions should be available now in Firelens log driver ( [Pull request](https://github.com/aws/aws-cdk/pull/15351) ).
- but I had the same issue when providing a parameter id that wasn't created yet in SSM, just make sure you are providing the right id when calling `fromStringParameterAttributes`.
- Also if you are using the secret in more than one place, try to define initialise it once and passing it to where you need it:
```
const secret = ssm.StringParameter.fromStringParameterAttributes(this, 'apikey', {
              parameterName: 'apikey',
              version: 0,
            });
const taskDefinition = new ecs.Ec2TaskDefinition(this, 'TaskDef');
taskDefinition.addContainer('TheContainer', {
  image: ecs.ContainerImage.fromRegistry('example-image'),
  secrets : { ANOTHER_PLACE_FOR_SECRET : ecs.Secret.fromSsmParameter(secret) }
  memoryLimitMiB: 256,
  logging: ecs.LogDrivers.firelens({
    options: {
      // ... log driver options here ...
    },
    secretOptions: {
          apikey: ecs.Secret.fromSsmParameter(secret),
        },
  })
});
```
