### ISSUE TITLE
(cloudfront): custom error pages

### ISSUE THREAD

**Issue by Aijaz12550** [aws/aws-cdk#16641]
I want to create custom error pages for a CloudFront distribution but there is no method in @aws-cdk/aws-cloudfront module to create custom error pages.

 *below is the code example, how I am creating distribution*

import * as cloudfront from "@aws-cdk/aws-cloudfront";
import * as origins from "@aws-cdk/aws-cloudfront-origins";

    let distribution = new cloudfront.Distribution(
      scope,
      `${props.stage}_travelclub_distribution`,
      {
        defaultBehavior: {
          origin: new origins.S3Origin(deployment_bucket as any) as any,
          cachePolicy: cloudfront.CachePolicy.CACHING_OPTIMIZED,
          viewerProtocolPolicy: cloudfront.ViewerProtocolPolicy.REDIRECT_TO_HTTPS
        }
      }
    );

### Use Case

Required to create custom Error pages in a CloudFront distribution.

### Proposed Solution

Add a method to @aws-cdk/aws-cloudfront by which we can create custom error pages to referenced distribution.
We should be able to add custom error pages to already existing distribution by referencing id.
But the priority is the current distribution.

### CloudFormation link to create Error Pages
   1. https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-customerrorresponse.html
   
   Thanks

**Comment by jogold** [comment]
Are you looking for https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cloudfront.Distribution.html#errorresponses maybe?

**Comment by Aijaz12550** [comment]
> Are you looking for https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cloudfront.Distribution.html#errorresponses maybe?

Thanks @jogold
