### ISSUE TITLE
(ecs.FargateTaskDefinition): runtime check for EphemeralStorageGiB makes it incompatible with CfnParameter tokens

### ISSUE THREAD

**Issue by nacitar** [aws/aws-cdk#16648]
https://github.com/aws/aws-cdk/blob/5aa6ac0008b2bd0556fda021124f6838173274b4/packages/%40aws-cdk/aws-ecs/lib/fargate/fargate-task-definition.ts#L134

The check here validates the values, however when using a CfnParameter's ValueAsNumber, you get a value such as:
-1.8881545897087957E+289

This value is, of course, a token.  However, because of this local parameter validation, and it not exempting these token values from the check, you simply cannot use a CfnParameter for this field.  If the check was done on the AWS side it would be fine, as it would know the real value by that point.

### Reproduction Steps

Make a fargate task definition and try to pass in a CfnParameter's ValueAsNumber as the EphemeralStorageGiB, it will throw no matter what default/value it has because it validates the token as if it's the real value.

### What did you expect to happen?

No exception, but rather a failure at deploy time **IFF** the value is out of the valid range.

### What actually happened?

An exception was thrown preventing me from even generating the template in the first place, despite no real value being present to even fail the validation.

### Environment

  - **CDK CLI Version  :** 1.116.0 (build d04661d)
  - **Framework Version:** .NET Core 3.1
  - **Node.js Version:** v14.17.6
  - **OS               :** Windows 10
  - **Language (Version):** C#

--- 

This is :bug: Bug Report

**Comment by nacitar** [comment]
Might be more worthy of a distinct ticket, but the same identical problem exists here:
https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-ecs-patterns/lib/base/application-load-balanced-service-base.ts#L417

That check makes the DesiredCount impossible to express via a CfnParameter.

**Comment by peterwoodworth** [comment]
I've been able to confirm the behavior. Will see about getting a PR up soon
