### ISSUE TITLE
lambda-layer-awscli: doesn't work with newer Python versions

### ISSUE THREAD

**Issue by trondhindenes-nomono** [aws/aws-cdk#16659]
### Reproduction Steps
Create a lambda function using Python 3.8 or 3.9 as the runtime, and include this layer. Calling the "aws" cli inside the lambda will throw an error `/opt/awscli/bin/python: error while loading shared libraries: libpython2.7.so.1.0: cannot open shared object file: No such file or directory`. 

I'm assuming the "root cause" for this bug is https://github.com/aws-samples/aws-lambda-layer-awscli/issues/5, but it seems to have been fixed there, so maybe the CDK package version uses an older version of that layer?

**Comment by milesgranger** [comment]
Bump for this. Ironic especially since 2.7 runtime is long deprecated.
At the very least, if it's _known_ the layer simply won't work, a notice about this, and/or erroring during build time would save people time trying to debug this.

**Comment by TheRealAmazonKendra** [comment]
This should not be an issue on any recent versions of the CDK. If this is still an issue, please re-open an issue with the version you are using so we can investigate further.
