### ISSUE TITLE
BucketDeployment: retainOnDelete not honoured

### ISSUE THREAD

**Issue by binarythinktank** [aws/aws-cdk#16658]
### The Question
I have a cdk project with an s3 bucket, bucket is deployed and has files in it.
i add a bucketdeployment and retainondelete is set to true
I deploy
everything is deleted from the s3 bucket and the deployed files are added.

i wonder if its just because its the first time I'm adding the deploy so I add some files to the s3 bucket and deploy again.
nope, all files deleted again.

conclusion: retainOnDelete is not honoured (or it does not actually work the way the documentation describes it). 

### Environment

  - **CDK CLI Version:** 1.118.0 (build a4f0418)
  - **Module Version:** 1.118.0 
  - **Node.js Version:** v15.10.0
  - **OS:** Ubuntu
  - **Language:** javascript

### Other information
my cdk code:

```ts
const s3system = new s3.Bucket(this, 'S3system', {
    bucketName:process.env.BUCKET_SYSTEM,
    blockPublicAccess: stack.services.s3.BlockPublicAccess.BLOCK_ALL,
    lifecycleRules:[{
      abortIncompleteMultipartUploadAfter:stack.cdk.Duration.days(2),
      enabled:true,
      expiration:stack.cdk.Duration.days(60),
      prefix: "logs/"
    }],
    removalPolicy:stack.cdk.RemovalPolicy.RETAIN
  });

new s3deploy.BucketDeployment(this, "deploySystem", {
    sources: [s3deploy.Source.asset("stack/s3/system/src")],
    destinationBucket: s3system,
    destinationKeyPrefix: "",
    retainOnDelete:true
  });
```

**Comment by binarythinktank** [comment]
Update:
i upgraded node to v16.10.0
and CDK to 1.124.0 (build 65761fe) along with the modules.

but the issue is still happening

**Comment by ryparker** [comment]
Hey @binarythinktank 👋🏻 

Thanks for bringing this to our attention. I'm looking into this on my end and will follow up once i've reproduced the bug.

**Comment by ryparker** [comment]
Ok so I was able to reproduce what you explained, however I think there is a miss-understanding in what the `retainOnDelete` prop is meant to do.

_[`retainOnDelete` prop docs](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-s3-deployment-readme.html#retain-on-delete):_ 
> By default, the contents of the destination bucket will not be deleted when the BucketDeployment resource is removed from the stack or when the destination is changed. You can use the option retainOnDelete: false to disable this behavior, in which case the contents will be deleted.

This is only modifying the delete behavior when you either:
- When you delete the `BucketDeployment` from your CDK code
- When you change the `BucketDeployment`'s `destinationBucket` prop to a different bucket

`retainOnDelete` does not modify any behavior when creating a new `BucketDeployment`.

To prevent files from being deleted when creating a new `BucketDeployment` you'll want to set the [`prune` prop](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-s3-deployment-readme.html#prune) to `false`

_[`prune` prop docs](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-s3-deployment-readme.html#prune):_
> By default, files in the destination bucket that don't exist in the source will be deleted when the BucketDeployment resource is created or updated. You can use the option prune: false to disable this behavior, in which case the files will not be deleted.


Example:

```ts
import { App, Stack, Duration, RemovalPolicy } from '@aws-cdk/core';
import { Bucket, BlockPublicAccess } from '@aws-cdk/aws-s3'
import { BucketDeployment, Source } from '@aws-cdk/aws-s3-deployment';

const app = new App();
const stack = new Stack(app, 'issue-16658');

const bucket = new Bucket(stack, 'issue-16658-test-bucket', {
  bucketName: 'issue-16658-test-bucket',
  blockPublicAccess: BlockPublicAccess.BLOCK_ALL,
  lifecycleRules: [{
    abortIncompleteMultipartUploadAfter: Duration.days(2),
    enabled: true,
    expiration: Duration.days(60),
    prefix: "logs/"
  }],
  removalPolicy: RemovalPolicy.RETAIN,
});

new BucketDeployment(stack, "deploySystem", {
  sources: [Source.asset("assets")],
  destinationBucket: bucket,
  retainOnDelete: true,
  prune: false,
});
```

**Comment by binarythinktank** [comment]
ah my bad! can i suggest we cross-link those 2 parameters in the documentation? with a one-liner about the difference on each?

**Comment by ryparker** [comment]
Sounds good to me 👍🏻. Would you be willing to [open a PR](https://github.com/aws/aws-cdk/blob/7fbf092c613f5618575b9b1a10b9e06fa36abad3/CONTRIBUTING.md)?

**Comment by binarythinktank** [comment]
sure!

**Comment by binarythinktank** [comment]
wait, this would be a change to the doc though: https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-s3-deployment.BucketDeployment.html where do i raise a PR for this?

**Comment by ryparker** [comment]
Our docs are generated from code comments. For example here's the code comment you see on that BucketDeployment page you linked: https://github.com/aws/aws-cdk/blob/7f7be089fa84afd0ab009a7feca2df4315749bc3/packages/%40aws-cdk/aws-s3-deployment/lib/bucket-deployment.ts#L224-L227
