### ISSUE TITLE
(aws-cdk-lib): Document idiomatic approach to using experimental modules

### ISSUE THREAD

**Issue by cuongvo** [aws/aws-cdk#16664]
### The Question

In `aws-cdk-lib` we're explicitly removing access to L2 experimental modules ([see](https://github.com/aws/aws-cdk/blob/master/packages/aws-cdk-lib/scripts/verify-stripped-exp.ts#L1-L4)). What is the proper way of using L2 constructs exposed via experimental modules alongside `aws-cdk-lib`

### Environment

  - **CDK CLI Version:**  2.0.0-rc.23 (build 1e54fb9)
  - **Module Version:**  2.0.0-rc.23 
  - **Node.js Version:**  12.18.0
  - **OS:**  maCOS
  - **Language (Version):**  Typescript (3.9.7)

### Other information

I'm specifically looking to use `apigatewayv2` and only L1 constructs are exposed via `aws-ckd-lib`. Preferably there's a flag in `cdk.json` to enable certain experimental modules. I assume instead I have to bring in the dependencies alongside `aws-cdk-lib`, which removes a lot of the advantages of the mono package approach.

**Comment by cuongvo** [comment]
Actually, after looking at this more, I don't think I can use experimental modules with `aws-cdk-lib`. The differing type declarations embedded in `aws-cdk-lib` clash with the published npm versions. 

I would suggest calling this out more prominently in both the `README.md` and AWS's docs for AWS CDK v2 ([docs](https://docs.aws.amazon.com/cdk/latest/guide/work-with-cdk-v2.html)).

From the AWS docs: 

> Experimental L2/L3 constructs are no longer included in the AWS Construct Library; they will instead be distributed separately with an appropriate semantic version number. Constructs will move into the main AWS Construct Library only after being designated stable, permitting the Construct Library to adhere to strict semantic versioning going forward. We are still finalizing the details of how experimental constructs will be distributed for CDK v2, so initially, CDK v2 does not provide experimental constructs.

Should be

> .... NOTE: Experimental L2/L3 constructs **WILL NOT** work with the `aws-cdk-lib` during this preview.

**Comment by nija-at** [comment]
Actually, we are in the process of publishing experimental modules as separate modules. It should be available soon, and the consumption process will be as documented in the docs you have linked.

cc @njlynch
