### ISSUE TITLE
EFS construct library (pending PR)

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#1667]
We are closing PR #977 by @rhboyd for now until it is picked up at some point. We will keep this issue open so this great work is not completely lost

**Comment by vlence** [comment]
Hello. Can I contribute to this? While building out our infrastructure I ended up writing a very quick implementation of EFS FileSystem as a construct. You can take a look [here](https://gist.github.com/vlence/c387f9f94814363eafe7402821c90de4).

**Comment by rhboyd** [comment]
of course.

**Comment by vlence** [comment]
Great! How do I start though? I would like to start from where the first guy left off.

PS: I'm new to all this. First time contributing to anything.

**Comment by rhboyd** [comment]
We're happy to have you in the community. My contribution was many breaking changes ago and would probably take a lot of time to fix properly. I would start with the [contributing guide](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) and let me know if you have any issues getting your environment set up. There's also a [Gitter](https://gitter.im/awslabs/aws-cdk) for chatting with other devs and a #cdk channel in the AWS Developers Slack.

**Comment by vlence** [comment]
Ah I see. I shall read the contributing guide and join Gitter then.

I think the first thing I'll try is merge your changes with a new fork and see if I can work from there.

Ah this will be interesting!

**Comment by vlence** [comment]
Update.

It's taking me a little longer than expected. I followed the instructions in the contributing guide but just can't get the install and build scripts to run on my Machine. I'm using Windows but I ran all scripts using Git-Bash.

I created a VM some time ago thinking I'll try setting up the project in a Ubuntu image instead. I'll be travelling in the next few days so I'll try and work on this too when I get myself some free time.

**Comment by vlence** [comment]
Oh gosh I'm so sorry I didn't get back earlier. I know my excuse is lame but I had been travelling and quite busy with my day job.

I have been working on the efs construct in my free time if you're all still interested.

Sorry again for not getting back earlier.
