### ISSUE TITLE
(elbv2): ALB target type support for NLB

### ISSUE THREAD

**Issue by pahud** [aws/aws-cdk#16679]
NLB now supports ALB as the target type.

https://aws.amazon.com/tw/about-aws/whats-new/2021/09/application-load-balancer-aws-privatelink-static-ip-addresses-network-load-balancer/

And the cloudformation already has the support.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-targetgroup.html#cfn-elasticloadbalancingv2-targetgroup-targettype

### Use Case

To make ALB as the NLB target with static IP addresses or private link support

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by pahud** [comment]
Hi @njlynch the PR is ready! Please take a look. Thanks.

**Comment by ryparker** [comment]
Hey @pahud 👋🏻 

Thanks for opening the issue and PR!

I'm going to label this as p1 which means it has been prioritized as important, although please keep in mind that we do have a large number of PRs to review. We'll do our best to get your PR reviewed soon.
