### ISSUE TITLE
(@aws-cdk/aws-ec2): WINDOWS_SERVER_2016_ENGLISH_FULL_BASE doesn't come with SSM

### ISSUE THREAD

**Issue by abdirahmanjama** [aws/aws-cdk#16677]
According to the documentation: 

> "AWS Systems Manager Agent (SSM Agent) is preinstalled, by default, on the following Amazon Machine Images (AMIs):
>
> Windows Server 2008-2012 R2 AMIs published in November 2016 or later
>
> Windows Server 2016 and 2019"

However, the version mentioned in the issue does not support SSM. When I create the instance using cdk deploy - it moans about not having it set up. Whereas, other versions i've tried come with it pre-installed. 

--- 

This is :bug: Bug Report

**Comment by ryparker** [comment]
Hey @abdirahmanjama 👋🏻 

Thanks for bringing this to our attention. This sounds like a documentation error that needs correcting. 

I'm labeling this as p1 which means it has been prioritized as important, although please keep in mind that we do have a large number of issues at the moment. It may be some time before we are able to solve this particular issue. We use +1s to help us prioritize our work, and as always we are happy to take contributions if anyone is interested to pick this up and submit a PR.

**Comment by aneeshrelan** [comment]
Is this something I can take up as a small contribution? A quick hint to the docs setup would help for this
