### ISSUE TITLE
Add reference to the S3 construct docs pointing at the aws-s3-deployment construct

### ISSUE THREAD

**Issue by nathanpeck** [aws/aws-cdk#1668]
This will increase visibility to users who want this functionality but don't realize it is broken out into its own construct

**Comment by Doug-AWS** [comment]
What's the use case for aws-s3-deployment?

**Comment by nathanpeck** [comment]
AWS S3 Deployment helps you get static files off your dev computer and into the freshly created S3 bucket. One good use case example would be a static website deployment. You need to upload your CSS, JS, and HTML files into the newly created public. `aws-s3-deployment` adds this feature to CDK

**Comment by Doug-AWS** [comment]
Okay, I'll add a blurb to the S3 package README.md file. Probably tomorrow as I'm trying to get the guide up for review on the public AWS Docs site.

**Comment by SomayaB** [comment]
@rix0rrr I noticed this isn't present in the docs. Does this still need action?

**Comment by rix0rrr** [comment]
I think it would still be good to give a shout out from the S3 package docs to the s3-deployment package, yes.
