### ISSUE TITLE
Get permissions of whatever the CDK just created

### ISSUE THREAD

**Issue by Lilja** [aws/aws-cdk#16688]
### Use Case

When I'm running `cdk deploy` from my own machine, this all works fine and dandy because I'm an administrator/have broad permissions for the AWS account i'm working on.
To enable the same stack to be run in a CICD environment we want to "lock in" the permissions of that codebuild user to only be able to create/view things related to the application.
In our repository, we have CICD CDK which we create a cicd-stack that will run the actual cdk command and deploy it to the aws account it's running on. 
Blindly running `cdk deploy` in a context with no permissions creates a problem since you have to manually find out what permissions is needed to deploy the app and it involves a dance like this:
(App is a lambda, with a secretsmanager secret that it needs to read)
(CICD is a CDK codebuild project that deploys a Docker image to run the app. CICD's role has no permissions)
1. Create a commit that codebuild run
2. CDK complains it has no permissions to get deployments(no s3 permission)
3. Add dependency to cicd, deploy the docker image
4. New permission issue, maybe no `cloudformation:Whatever` access
5. Add dependency to cicd, deploy the docker image
6. New permission issue, can't create a role because `iam:CreateUser`  is not allowed.
7. Add dependency to cicd, deploy the docker image
8. And so on and so forth.

### Proposed Solution

A flag to `cdk deploy` that lists all the permissions used to create the stack. Perhaps an extra file that is a JSON policy like IAM uses, easy to convert from whatever CDK language you are using.

---
* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by indrora** [comment]
If this is still an issue for you: The CDK generates a series of roles that are used to deploy a stack. You can re-use these for your own purposes or create more refined roles based on your needs and specify them in your synthesis and deployment configuration. 

For information, see the [Bootstrapping](https://docs.aws.amazon.com/cdk/v2/guide/bootstrapping.html) section of the AWS CDK v2 Guide.
