### ISSUE TITLE
(bootstrap): Expose bootstrapping as a construct

### ISSUE THREAD

**Issue by raajheshkannaa** [aws/aws-cdk#16685]
Expose the cdk bootstrapping process as a library/construct, so that we can use that to codify bootstrapping multiple accounts at scale.

### Use Case

This will tremendously help with bootstrapping 100s of accounts under the Organization so that we can build cdk pipelines and deploy to n number of accounts at scale.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by peterwoodworth** [comment]
@rix0rrr do you know if is a feasible feature to implement?

**Comment by rix0rrr** [comment]
It can probably be made easier, but you could do this today already by taking this file:

https://github.com/aws/aws-cdk/blob/master/packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml

And deploying it via a StackSet: https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cloudformation.CfnStackSet.html

Only L1 support for now, so some assembly required, but it should work.

**Comment by raajheshkannaa** [comment]
I'm doing a bit of python fu with subprocess and couple boto3 api calls right now to bootstrap all accounts under an Organization. Quick and dirty, but get's the job done.

https://github.com/raajheshkannaa/cdk-booty-strappin

**Comment by raajheshkannaa** [comment]
> It can probably be made easier, but you could do this today already by taking this file:
> 
> https://github.com/aws/aws-cdk/blob/master/packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml
> 
> And deploying it via a StackSet: https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cloudformation.CfnStackSet.html
> 
> Only L1 support for now, so some assembly required, but it should work.

**Comment by raajheshkannaa** [comment]
> It can probably be made easier, but you could do this today already by taking this file:
> 
> https://github.com/aws/aws-cdk/blob/master/packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml
> 
> And deploying it via a StackSet: https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cloudformation.CfnStackSet.html
> 
> Only L1 support for now, so some assembly required, but it should work.

The template is a good idea. Ideally, we could use that to run as a pipeline in the Organization Account triggered on a new account creation, so that accounts are bootstrapped along with the usual setup of a new account.

**Comment by raajheshkannaa** [comment]
> It can probably be made easier, but you could do this today already by taking this file:
> 
> https://github.com/aws/aws-cdk/blob/master/packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml
> 
> And deploying it via a StackSet: https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cloudformation.CfnStackSet.html
> 
> Only L1 support for now, so some assembly required, but it should work.

The template is a good idea. Ideally, we could use that to run as a pipeline in the Organization Account triggered on a new account creation, so that accounts are bootstrapped along with the usual setup of a new account.
