### ISSUE TITLE
[cloudformation][aws-ecs][aws-secretsmanager]: retrieve secret value from secret name

### ISSUE THREAD

**Issue by g3kr** [aws/aws-cdk#16700]
### The Question

I have 2 questions. I am deploying this through Cloudformation.

1. I am trying to retrieve a secretmanager secretstring which is a json in my ECS task definition. The secret ARN now includes 6 random characters in the ARN which changes if the version of the secret changes. Is there a way I can retrieve the secret just from the secret name?

Below code block fails with `failed to fetch`

 ```
      
   Secrets:
            - Name: MySecret
              ValueFrom: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:my-secret-name
       
```

what it expects is 

 ```
  Secrets:
            - Name: MySecret
              ValueFrom: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:my-secret-name-7G8UI3
```

2. Will using dynamic reference (as below) work in Secrets block when deploying through CloudFormation?

```
Secrets:
    - Name: MySecret
      ValueFrom: !Join [ '', [ '{{resolve:secretsmanager:',my-secret-name, ':SecretString:UserName}' ] ]
```

### Environment

  - **CDK CLI Version:** 
  - **Module Version:** 
  - **Node.js Version:** 
  - **OS:** 
  - **Language (Version):**

**Comment by peterwoodworth** [comment]
Hey @g3kr,

Are you using the CDK? Or writing a CloudFormation template. I'm not sure which level you're developing on based on the post

**Comment by g3kr** [comment]
@peterwoodworth I am using CloudFormation template.

**Comment by peterwoodworth** [comment]
So, this is the repository specifically for the CDK. Which, while it does make use of CloudFormation under the hood, it's not a support repo for CloudFormation issues.

Here's the documentation which describes exactly what you need to do in cloudformation: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/dynamic-references.html#dynamic-references-secretsmanager

If you want to try using the CDK to help you write your CloudFormation templates, I highly recommend that as it makes many things easier! Check out our [getting started page](https://docs.aws.amazon.com/cdk/latest/guide/getting_started.html)
