### ISSUE TITLE
(aws-lambda-nodejs): esbuild watch mode

### ISSUE THREAD

**Issue by alexedwardjones** [aws/aws-cdk#16708]
During development being able to enable the [esbuild watch mode](https://esbuild.github.io/api/#watch) would be very beneficial.

### Use Case

Testing a lambda locally using the SAM CLI by running `sam local start-api` works but in order to reflect any subsequent changes, you have to rerun `cdk synth`.

### Proposed Solution

Adding a boolean `watch` property to the bundling options to enable the esbuild watch mode.

```
new lambda.NodejsFunction(this, 'my-handler', {
  bundling: {
    watch: process.env.IS_LOCAL ? true : false
  },
});
```
### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by chrisandrewcl** [comment]
I was about to post something similar, so I will just chime in here.

Adding a watch prop to the construct seems odd. 

Instead, similar to the watch toggle added to the deploy cli comand, I suggest the same to be added to the synth command.

**Comment by skinny85** [comment]
@chrisandrewcl curious, are you also using the SAM CLI? What benefit does running just `cdk synth` bring? Are the changes reflected in the Function without running any other command, automatically somehow?

**Comment by chrisandrewcl** [comment]
@skinny85 Yes, I am also using SAM CLI. 

The `sam local start-api` command watch for changes in the loaded lambda, but it is actually watching the built asset code inside cdk.out, which we don't change directly. As @alexedwardjones said, running `cdk synth` again rebuild the asset resulting in the SAM CLI picking up the changes. If we had a out-of-the-box `cdk synth --watch` we would't need to run it manually (or by other means).

Stretching this a little further, I would argue that even a `cdk diff --watch` can be useful to quick visualize changes. Watching for changes is a useful productivity tool, so it makes sense to have it on other features of the cdk tool box, not only when deploying changes.
