### ISSUE TITLE
(core): AssetStaging skips stacks with custom `stackName` specified

### ISSUE THREAD

**Issue by mpuhacz** [aws/aws-cdk#16713]
The `stackName` property is used to determine whether asset bundling should run. This is not a valid behavior since `BUNDLING_STACKS` (`aws:cdk:bundling-stacks`) is based on the stack ID (to be confirmed).

https://github.com/aws/aws-cdk/blob/d6afdaf4620948aecd8ed312bc98fb724e0f306c/packages/%40aws-cdk/core/lib/asset-staging.ts#L191-L192

### Reproduction Steps
This is the code I used for testing. If one specifies the `stackName` and uses the `--exclusively` flag, the lambda fn will not be bundled.

1. Create a simple stack. The stack contains a single `NodejsFunction` that should be bundled using esbuild.
```ts
import * as lambda from "@aws-cdk/aws-lambda-nodejs";
import * as cdk from "@aws-cdk/core";

class TestStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    new lambda.NodejsFunction(this, "fn", {
      entry: "./bin/test-lambda.ts"
    });
  }
}

const app = new cdk.App();
new TestStack(app, "TestStack", { stackName: "CustomName" });

```
2. Run 
```sh
cdk deploy --app 'npx ts-node bin/test.ts' -e TestStack
```
3. Remove the `stackName` property from `props`
```ts
new TestStack(app, "TestStack");
```
4. Run the command below. You will not see outputs from esbuild.
```sh
cdk deploy --app 'npx ts-node bin/test.ts' -e TestStack
```

5. This time you will see output from the bundler:
```sh
Bundling asset TestStack/fn/Code/Stage...

  cdk.out/bundling-temp-db9b7e173e25a00996e460b8358fe4aa08c4f2fbcf24ad4ac70c8b440a20de3e/index.js  502b

⚡ Done in 6ms
```

### Environment

 * **CDK CLI Version  :** 1.124.0
 * **Framework Version:** 1.124.0
 * **Node.js Version:**  v14.14.0
 * **OS               :** osx
 * **Language (Version):**  TypeScript

--- 

This is :bug: Bug Report

**Comment by m90** [comment]
Is there any way to work around this while the fix is still pending? We'd save a whole lot of time with this one.

**Comment by polothy** [comment]
bump

**Comment by rv2673** [comment]
It looks like the related closed PR(#16714) contains reference to other PR( #17210)  which contained similar change to fix similar issue(s).  #12898(closed) #15346(closed)

So this issue might possible be closed if it no longer can be reproduced.

**Comment by reecefenwick** [comment]
A workaround I posted on a similar issue that might work here https://github.com/aws/aws-cdk/issues/12898#issuecomment-1945520163

**Comment by sumupitchayan** [comment]
I am unable to reproduce this bug - I created a sample app locally with the same code as described in the repo steps and ran  `cdk deploy --app 'npx ts-node bin/test.ts' -e TestStack` with and without the `stackName` property being set; both times I ran `cdk deploy`, the lambda asset was bundled.
