### ISSUE TITLE
(aws-batch): Wrong service role is used for Fargate compute environment

### ISSUE THREAD

**Issue by poretti** [aws/aws-cdk#16717]
The default service role used for a compute environment is [`service-role/AWSBatchServiceRole`](https://github.com/aws/aws-cdk/blob/v1.124.0/packages/%40aws-cdk/aws-batch/lib/compute-environment.ts#L409).

I was trying to create a Fargate compute environment, but my jobs kept getting stuck in `runnable`. I then manually created a Fargate env through the console so I could compare to the CDK one.

The Batch console used the role `aws-service-role/batch.amazonaws.com/AWSServiceRoleForBatch`.

My jobs could run after updating my service-role to that one:
```
new ComputeEnvironment(this, 'FargateCompute', {
    computeResources: {
        type: ComputeResourceType.FARGATE,
        vpc,
    },
    // Overriding the service role fixed the problem
    serviceRole: Role.fromRoleArn(this, 'ComputeRole', `arn:aws:iam::${accountId}:role/aws-service-role/batch.amazonaws.com/AWSServiceRoleForBatch`),
});
```

### Reproduction Steps

Create a minimal Fargate compute environment in CDK, and compare it to a console created version. 

### What did you expect to happen?

I expected the CDK-created Fargate compute environment to mirror the console created one. Specifically for the service role.

### What actually happened?

CDK used a different service-role, with different permissions, causing submitted jobs to get stuck in `runnable`

### Environment

  - **CDK CLI Version  :** 1.122.0 (build ae09c16)
  - **Framework Version:** 1.124.0
  - **Node.js Version:** v16.9.1
  - **OS               :** MacOS 10.15.7
  - **Language (Version):** TypeScript (3.9.10)

### Other

--- 

This is :bug: Bug Report

**Comment by madeline-k** [comment]
@poretti, thanks for opening this issue! Can you please provide the minimum deployable stack including your vpc,  `JobDefinition` and `JobQueue` that reproduces this issue? 

I deleted all the AWS Batch roles in my account and then deployed the fargate compute environments and corresponding job definition and job queue from the [integration test](https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-batch/test/integ.batch.ts) And I was not able to reproduce the issue. When submitting a job after deploying that, I submitted a job, and it made it past the RUNNABLE state just fine.

**Comment by madeline-k** [comment]
It's strange that Batch has two IAM policies for this same purpose, from looking at the docs you linked, @peterwoodworth, they look like they have quite a lot of overlapping permissions.

The managed policy that goes with AWSServiceRoleForBatch is called "BatchServiceRolePolicy" (ARN is arn:aws:iam::aws:policy/aws-service-role/BatchServiceRolePolicy) and we could considered adding this one to the `serviceRole` as well as the existing "AWSBatchServiceRole" policy that is already there. I wouldn't want to remove the existing one in case there are permissions in that one that are not present in "BatchServiceRolePolicy" and then it breaks customers.
