### ISSUE TITLE
(ApiGatewayV2): detecting drift after a fresh deploy

### ISSUE THREAD

**Issue by moltar** [aws/aws-cdk#16724]
## :question: General Issue

After a deployment, a drift is detected in the `AWS::ApiGatewayV2::DomainName` resource type.

![screenshot-20210930T120215-uhXBwSPF](https://user-images.githubusercontent.com/491247/135390587-7a984976-44a9-41fb-b1b6-e701ec620fc3.png)

Not sure if this is CDK related, or CF related though.

### The Question

- Is this normal?
- Is this safe?

### Environment

  - **CDK CLI Version:** 1.124.0 (build 65761fe)
  - **Module Version:** N/A
  - **Node.js Version:** v16.7.0
  - **OS:** macOS
  - **Language (Version):** TypeScript

### Other information

N/A

**Comment by peterwoodworth** [comment]
You've likely made a modification to the resource directly on the console. Drift is simply a resource not having the configuration defined by the cloudformation stack. So, this isn't a CDK related issue.

I suggest reading through the [CloudFormation docs on drift](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-stack-drift.html) to learn more about it, and what you can do about it

**Comment by moltar** [comment]
> You've likely made a modification to the resource directly on the console. Drift is simply a resource not having the configuration defined by the cloudformation stack. So, this isn't a CDK related issue.
> 
> 
> 
> I suggest reading through the [CloudFormation docs on drift](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-stack-drift.html) to learn more about it, and what you can do about it

I didn't make any modifications in the console.
