### ISSUE TITLE
SecretString from SecretsManager should be a valid cdk.Secret

### ISSUE THREAD

**Issue by hoegertn** [aws/aws-cdk#1672]
Given the following code:
```
const githubAccessToken = new SecretString(this, 'GithubToken', {secretId: 'GitHub'});
```

it should be valid to use it directly in a SourceAction for Codepipeline. 

Instead I have to write it like `new Secret(githubAccessToken.jsonFieldValue('Token'))`

**Comment by eladb** [comment]
I guess that name of the JSON field is additional information you'll need to supply (in your case `Token`).

How about something like `toSecret`:

```ts
githubAccessToken.toSecret('Token')
```

Would that be more convinient/discoverable?

**Comment by rix0rrr** [comment]
I guess `jsonFieldValue` should always have returned a `Secret`, actually, no?

A fragment of a Secret is still a Secret.

**Comment by rix0rrr** [comment]
Don't close this please, I think it's still relevant. We have to hash out the right API though.

**Comment by njlynch** [comment]
Closing this out, as the SecretString interface was removed in #2161 (in CDK version 0.28.0!). The interfaces of `Secret`, `cdk.SecretValue`, and others have been dramatically altered since then, so hard to say if there's still any relevance.
