### ISSUE TITLE
(ecs): specify the Firelens container image version

### ISSUE THREAD

**Issue by tai-acall** [aws/aws-cdk#16733]
I hope to specific which version of the fluent-bit image I use but I couldn't find any options to do this.

### Use Case

A DNS Resolver bug inside the Fluent Bit v1.8.3 breaks function for transferring logs from ECS(Fargate) to the Datadog.

the only way to resolve this is specific which fluent-bit image version I use to, but I can not find any options to do this in CDK.

more detail about this issue.
https://github.com/aws/aws-for-fluent-bit/issues/233

the following version of fluent-bit should be fine.
public.ecr.aws/aws-observability/aws-for-fluent-bit:2.19.0

### Proposed Solution

Add an option to specific fluent-bit image url.

### Other

https://github.com/fluent/fluent-bit/issues/4050

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by tai-acall** [comment]
I notice that the fluent-bit image set as `latest`, setting as `stable` might be better.

https://github.com/aws/aws-for-fluent-bit/issues/233#issuecomment-931364866

**Comment by peterwoodworth** [comment]
Thanks for reporting this issue @tai-acall

The root of the issue has already been reported and there's a PR open to fix the issue. [This PR changes the default from `latest` to `stable`](https://github.com/aws/aws-cdk/pull/16439)

I'll make sure our SDEs take a look at the PR. I'm going to close this issue in favor of https://github.com/aws/aws-cdk/issues/16403, so please go there for any further updates :)
