### ISSUE TITLE
(aws-lambda): Docker image lambdas are redeployed on every deploy

### ISSUE THREAD

**Issue by FredrikMeyer** [aws/aws-cdk#16741]
## :question: General Issue
We run `cdk deploy` from a CodeBuild instance, and on every deploy, the function code is changed (and the Docker image built). The building takes quite a lot of time, and it would be very useful to for example specify a source hash) as with other types of assets.

This only happens on the CI system, not locally, which I guess is because the Docker layers are cached.  The code is roughly like this:

```python
        self.api_function = _lambda.DockerImageFunction(
            self,
            "APIEndpointLambda",
            code=_lambda.DockerImageCode.from_image_asset(
                directory=str(Path(".").absolute().parent.parent / "python_packages"),
                file="api/Dockerfile",
            ),
        )
```

### The Question

I guess this is a combined feature request and question.

Is there a way to tell CDK to use the *source code*  of the directory as hash when building Docker lambdas instead of using the Docker layer cache? (which doesn't exist on the build instance)

Thanks!

### Environment

  - **CDK CLI Version:** 1.124.0 (build 65761fe)
  - **Module Version:** 1.124.0
  - **Node.js Version:** 16.8.0
  - **OS:**  macOS + CodeBuild AWS Linux
  - **Language (Version):** Python 3.8

**Comment by jogold** [comment]
@FredrikMeyer the hash is based on the content of the Docker context (usually the directory containing your Dockerfile).

What's in `str(Path(".").absolute().parent.parent / "python_packages")`?

**Comment by FredrikMeyer** [comment]
@jogold  Thanks for the answer!

I did some digging in the code, and it turns out that the error might have been on my side: The whole code is this:

```python
            code=_lambda.DockerImageCode.from_image_asset(
                directory=str(Path(".").absolute().parent.parent / "python_packages"),
                file="api/Dockerfile",
                build_args={"XAL_PACKAGE_VERSION": get_global_version()},
            ),
```

And the function `get_global_version()` gives a new value on every deploy. I will set this to a constant, and hope that the issue resolves.

**Comment by FredrikMeyer** [comment]
@jogold  To answer the question: the lambda depends on code in the parent directory, which is quite big (I have some ignore-options, but I'm not sure if the Docker ignore options is included in the calculated hash?)

**Comment by jogold** [comment]
> And the function `get_global_version()` gives a new value on every deploy. I will set this to a constant, and hope that the issue resolves.

Yes, your build args are included in the hash so you should stabilize this value.

> I have some ignore-options, but I'm not sure if the Docker ignore options is included in the calculated hash?

Files that are excluded do not impact the hash.

**Comment by peterwoodworth** [comment]
Thank you very much @jogold for helping out here

@FredrikMeyer feel free to close the issue out if you don't have any more questions

**Comment by FredrikMeyer** [comment]
@jogold @peterwoodworth 

Thank you for the help! Appears the reason was the changing configuration. I'm not sure if the docs mention that the hash is computed with the configuration as well, though.

But thanks!
