### ISSUE TITLE
sqs: PolicyDocuments without an "Id" are not valid

### ISSUE THREAD

**Issue by rix0rrr** [aws/aws-cdk#1675]
We should either validate the existing policies, or better, automatically insert Ids to make the policies valid.

The console will not accept a PolicyDocument without "Id", "SId" might also be required, trying to figure that out now.

**Comment by rix0rrr** [comment]
Yep it's just "Id"

**Comment by rix0rrr** [comment]
Soo, the SQS console doesn't like a policy without an "Id", but the actual problem was that I had a missing "Resource" in a policy statement. I'm going to add additional validation so that this doesn't happen anymore.

**Comment by TomerzZzZ** [comment]
Is there a solution for that? I dont see an option in the queue constructor to add a policy ID

**Comment by rix0rrr** [comment]
I guess this is still worth fixing.

Adding the missing policy document "Id" will be the way to go.
