### ISSUE TITLE
(aws-glue): failed to create L2 Job

### ISSUE THREAD

**Issue by mgabs** [aws/aws-cdk#16767]
### What is the problem?

tried a switch to the L2 - got this
"service":"AWSGlue","statusCode":400,"errorCode":"EntityNotFoundException","requestId":"8b148762-2a85-4b0a-bfb7-499ab470356e","errorMessage":"Job with name: batchFiltersJob not found.","type":"AwsServiceError"}

### Reproduction Steps

Constructor
```
    const glueJob = new glue.Job(this, props.name, {
      executable: glue.JobExecutable.pythonEtl({
        glueVersion: glue.GlueVersion.V3_0,
        pythonVersion: glue.PythonVersion.THREE,
        script: glue.Code.fromBucket(
          props.bucket,
          `assets-glueJobs/${props.script}`
        ),
      }),
      description: `A batchJob for ${props.name}`,
      workerType: glue.WorkerType.G_1X,
      maxRetries: 1,
      timeout: Duration.seconds(2880),
      role: props.job_role,
       defaultArguments: {
         "--TempDir": "s3://glue.zenlist.com/staging",
         "--job-bookmark-option": "job-bookmark-enable",
         "--job-language": "python",
       },
 });
```

### What did you expect to happen?

Successful creation of a Glue job

### What actually happened?

Creation failed with error message
```
service":"AWSGlue","statusCode":400,"errorCode":"EntityNotFoundException","requestId":"8b148762-2a85-4b0a-bfb7-499ab470356e","errorMessage":"Job with name: batchFiltersJob not found.","type":"AwsServiceError"}
```

### CDK CLI Version

 cdk version 1.125.0 (build 67b4921)

### Node.js Version

v14.17.0

### OS

arch linux

### Language

Typescript

### Language Version

Version 4.4.3

**Comment by kaizen3031593** [comment]
Can you provide your L1 code along with your L2 code? Hopefully that will help me get to the bottom of this.
