### ISSUE TITLE
(lambda): support provided Graviton runtime

### ISSUE THREAD

**Issue by nuvanti** [aws/aws-cdk#16762]
### Description

See recent release: https://aws.amazon.com/blogs/aws/aws-lambda-functions-powered-by-aws-graviton2-processor-run-your-functions-on-arm-and-get-up-to-34-better-price-performance/

I don't see any support for it in CDK? Can you please add it? Supposedly Pulumi has already added it, really would expect CDK to support it as well.

### Use Case

Lambda on Graviton

### Proposed Solution

Add support for it.

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by skinny85** [comment]
It is supported already: https://github.com/aws/aws-cdk/releases/tag/v1.125.0.
