### ISSUE TITLE
(cdk deploy): cdk deploy can NOT identify a resource manually deleted and can NOT generate it again.

### ISSUE THREAD

**Issue by jackiecheng2008** [aws/aws-cdk#16769]
### What is the problem?

CDK is out of sync in case of manually deletion after it provisions the resources
Therefore, how CDK remain safe against such failures? CDK is unaware about its own resources changes after deployment.

### Reproduction Steps

Below steps can be repeated:
CDK deploy -> provisions a Lambda function;
CloudFormation -> Lambda was created successfully;
AWS console -> manually deleted above Lambda;
CloudFormation -> can not identify the deletion;
CDK deploy -> no changeset -> no deployment at all.
This issue also applies to other resources such as SQS queues. 

### What did you expect to happen?

CDK deploy will identify resources based on real resources themselves; the changeset should be smart enough to re-generate the resources in case of deletion.

### What actually happened?

Below is the output from "cdk deploy":
creating CloudFormation changeset...

 ✅  sample-travelers-cdk-app-latest (no changes)

### CDK CLI Version

1.105.0

### Node.js Version

v14.15.4

### OS

Amazon Linux

### Language

Typescript

**Comment by jackiecheng2008** [comment]
The only way to get the deleted Lambda/SQS resources back is: 
cdk destroy and then cdk deploy again.
Which means: cdk diff is not checking the actual resources at all.

**Comment by nija-at** [comment]
We use CloudFormation under the hood, and this is how CloudFormation works. It does not keep track of resources that were adjusted out of band.

Here are the details - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-stack-drift.html
