### ISSUE TITLE
(description@aws-cdk/aws-apigatewayv2): HttpApi does not seem to exist in CDK v2 (2.0.0-rc.23)

### ISSUE THREAD

**Issue by glenvillabey** [aws/aws-cdk#16768]
### What is the problem?

HttpApi does not seem to exist in CDK v2 (2.0.0-rc.23)

### Reproduction Steps

1. Install latest CDK v2 via npm i aws-cdk@next

2. Try and add a HttpApi construct to your stack or construct
[shared-services-stack.zip](https://github.com/aws/aws-cdk/files/7272783/shared-services-stack.zip)

### What did you expect to happen?

Create a stack or construct that used Http ApiGateway using CDK v2

### What actually happened?

The construct was not found and therefore building the CDK stack failed

### CDK CLI Version

2.0.0-rc.23

### Framework Version

2.0.0-rc.23

### Node.js Version

v14.17.6

### OS

Windows 10

### Language

Typescript

### Language Version

TypeScript (3.9.7)

**Comment by dan-lind** [comment]
This is not a bug. If you check the v1 API docs, you will see that the higher level constructs for the `aws-apigatewayv2`  are designated as Experimental. (https://docs.aws.amazon.com/cdk/api/latest/docs/aws-apigatewayv2-readme.html)

Per https://docs.aws.amazon.com/cdk/latest/guide/work-with-cdk-v2.html, under the section "Changes in AWS CDK v2" you can read the following

---
**Experimental L2/L3 constructs are no longer included in the AWS Construct Library**; they will instead be distributed separately with an appropriate semantic version number. Constructs will move into the main AWS Construct Library only after being designated stable, permitting the Construct Library to adhere to strict semantic versioning going forward. **We are still finalizing the details of how experimental constructs will be distributed for CDK v2, so initially, CDK v2 does not provide experimental constructs.**

So there is currently no way to use these constructs with CDKv2
