### ISSUE TITLE
(aws-sagemaker): Support for Amazon Linux 2 (notebook-al2-v1)

### ISSUE THREAD

**Issue by mattiamatrix** [aws/aws-cdk#16775]
### Description

Sagemaker [now](https://aws.amazon.com/blogs/machine-learning/amazon-sagemaker-notebook-instance-now-supports-amazon-linux-2/) supports Amazon Linux 2 but this is not yet available in CloudFormation/CDK.

### Use Case

Create Sagemaker Notebook instances with **Platform identifier**  `notebook-al2-v1`

### Proposed Solution

Add `platformIdentifier` parameter in CfnNotebookInstance/CfnNotebookInstanceProps.

### Other information

This is linked to https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/942

### Acknowledge

- [x] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by peterwoodworth** [comment]
we support platformIdentifier now 🙂
