### ISSUE TITLE
(Arn): Arn.format with ArnFormat.NO_RESOURCE_NAME should ignore resourceName

### ISSUE THREAD

**Issue by mrmilosz** [aws/aws-cdk#16772]
### What is the problem?

When parsing, `ArnFormat.NO_RESOURCE_NAME` will put everything after the last colon into the `resource` part, which makes the sentence
> This represents a format where there is no 'resourceName' part.

in the documentation accurate.

Conversely, when formatting, it should cause `resourceName` to be ignored if specified.

### Reproduction Steps

Inside a method of a class that implements `cdk.Construct`:

```ts
cdk.Stack.of(this).formatArn({
  account: "123456789012",
  arnFormat: cdk.ArnFormat.NO_RESOURCE_NAME,
  region: "",
  resource: "role",
  service: "iam",
  resource: "root",
  resourceName: "some_garbage",
});
```

### What did you expect to happen?

ARN: `arn:aws:iam::123456789012:root`

### What actually happened?

ARN: `arn:aws:iam::123456789012:root/some_garbage`

### CDK CLI Version

1.125.0 (build 67b4921)

### Node.js Version

12.18.4

### OS

macOS

### Language

Typescript

### Language Version

3.9.7

### Other information

This came up when I was trying to convert an existing role ARN into a root ARN like this:

```ts
stack.formatArn({
  ...stack.parseArn(roleArn),
  arnFormat: cdk.ArnFormat.NO_RESOURCE_NAME,
  resource: "root",
});
```

I ended up needing to add `resourceName: undefined` to get it to work as expected (at which point `arnFormat: cdk.ArnFormat.NO_RESOURCE_NAME` became redundant.)

**Comment by skinny85** [comment]
Hey @mrmilosz,

thanks for opening the issue. I wonder, what's the scenario when you ran into this?

I'm a little wary in just ignoring inputs like that, I feel like it could lead to surprising behavior... Maybe we should error out instead?

@rix0rrr what do you think?

Thanks,
Adam

**Comment by mrmilosz** [comment]
@skinny85 

> thanks for opening the issue. I wonder, what's the scenario when you ran into this?

I snuck that in at the end of my post; it was just a little function for converting the ARN of an IAM role into the ARN of the root IAM resource for that account, which meant converting something that has a `resourceName` into something that doesn't. This is not critical issue though, as setting `resourceName` to `undefined` is just as many lines of code as setting the ARN format. I just figured the behavior of the format might be inconsistent here.

> I'm a little wary in just ignoring inputs like that, I feel like it could lead to surprising behavior... Maybe we should error out instead?

Actually this would be a good solution too! It would force the programmer to be more explicit.
