### ISSUE TITLE
Codebuild: partialBuildSpec is not usable

### ISSUE THREAD

**Issue by strowk** [aws/aws-cdk#16784]
### What is the problem?

I have added following to CodeBuildStep :

```ts
    partialBuildSpec: codebuild.BuildSpec.fromObject({
      phases: {
        install: {
          runtimeVersions: {
            nodejs: '14.x',
          },
        },
      },
    }),
```

and I receive this error: `Can only merge buildspecs created using BuildSpec.fromObject()` 

### Reproduction Steps

Something like this should cause it:

```
new pipelines.CodeBuildStep('Synth', {
    input: pipelines.CodePipelineSource.s3(
      bucket,
      `${serviceName}/${triggerFile}`,
      { trigger: codepipeline_actions.S3Trigger.EVENTS },
    ),
    commands: ['npm i npm -g', 'npm ci', 'npm run build'],
    partialBuildSpec: codebuild.BuildSpec.fromObject({
      phases: {
        install: {
          runtimeVersions: {
            nodejs: '14.x',
          },
        },
      },
    }),
  });
```

### What did you expect to happen?

Wanted to modify runtimeVersion on already deployed code build project.

### What actually happened?

Receive this error: `Can only merge buildspecs created using BuildSpec.fromObject()` 

### CDK CLI Version

1.124.0 (build 65761fe)

### Node.js Version

v14.17.6

### OS

Ubuntu 20.04

### Language

Typescript

### Language Version

4.4.2

**Comment by skinny85** [comment]
Hey @strowk,

apologies for the late reply here.

I think there are a few issues with your buildspec, according to the [CodeBuild docs](https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html):

1. You're missing the `version` key.
2. The key is `runtime-versions`, not `runtimeVersions`.

Can you try the following code, and see if that helps?

```ts
    partialBuildSpec: codebuild.BuildSpec.fromObject({
      version: '0.2',
      phases: {
        install: {
          'runtime-versions': {
            nodejs: '14.x',
          },
          commands: ['some-command-here'],
        },
      },
    }),
```

Thanks,
Adam
