### ISSUE TITLE
Region Info: Cound not insert new fact from a Java process

### ISSUE THREAD

**Issue by RomainMuller** [aws/aws-cdk#16786]
### What is the problem?

Attempting to register new `Fact` instances into the region info database is very inconvenient in Java, as a full-on implementation of an interface has to be rolled out (where a Struct would have been enough), and it also does not appear to work.

### Reproduction Steps

Attempted to add a new custom class as an `IFact` implementation to the region info database - it did not appear to work.

### What did you expect to happen?

Expected the fact to be registered and the behavior of the app to change according to that.

### What actually happened?

The behavior of the app did not change.

### CDK CLI Version

1.122.0

### Node.js Version

12.x

### OS

Linux

### Language

Java

### Language Version

8

**Comment by RomainMuller** [comment]
So it turns out the reason why the custom fact was not used is because the stack that used it was likely "region-agnostic", so it could not use a registered fact and instead used the default value.

In this case, the proper avenues to address this are:
- https://github.com/aws/aws-cdk/pull/4131
- https://github.com/aws/aws-cdk-rfcs/issues/58

**Comment by rix0rrr** [comment]
Closing this then.
