### ISSUE TITLE
(lambda-nodejs): Cannot use handler from layer

### ISSUE THREAD

**Issue by guydunton** [aws/aws-cdk#16795]
### Description

I would like to be able to specify a handler from a file other than the entry point

### Use Case

Externally instrumenting a lambda using New Relic cannot properly be done using a `NodejsFunction`. The [documentation](https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/instrument-your-own/#console) for their instrumentation requires using an entry point in an eternal layer which then calls the lambdas true handler (using env vars).

Currently when I try to use `NodejsFunction` I can set `handler` in the props but it will always prepend `index.` to it so instead of getting a handler of `newrelic-lambda-wrapper.handler` I get `index.newrelic-lambda-wrapper.handler`. 

### Proposed Solution

It might be helpful for this use case to have an alternative prop such as `externalHandler` for this use case which doesn't get prepended with `index.`.

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by nija-at** [comment]
The `lambda-nodejs` module is not intended for this use case. 
Use standard `Function` construct from the `aws-lambda` module for this.
