### ISSUE TITLE
(Assertions): CDK V2 Does not include assertions module.

### ISSUE THREAD

**Issue by keepler-ivanmarques** [aws/aws-cdk#16797]
### What is the problem?

CDK V2 Does not include old assertions module.

### Reproduction Steps

test_assertions.py
```
from aws_cdk import assertions 
```

### What did you expect to happen?

The test should have import the assertions module

### What actually happened?

Error:

```
ImportError: cannot import name 'assertions' from 'aws_cdk' 
```

### CDK CLI Version

2.0.0-rc.23

### Framework Version

2.0.0-rc.23

### Node.js Version

v14.18.0

### OS

MacOS 11.6

### Language

Python

### Language Version

Python (3.8.9)

### Other information

Is it in the same aws-cdk-lib module or is it in a separate module?

**Comment by keepler-ivanmarques** [comment]
As said in issue [15824](https://github.com/aws/aws-cdk/issues/15824), will be the assertions module in a separate package?

If so, there's any release date for that package in pypi?

**Comment by njlynch** [comment]
Hi @keepler-ivanmarques !

As the `assertions` module is still experimental (the APIs have not yet been finalized and stabilized), it cannot be bundled within the main (`aws-cdk-lib`) release. Instead, we will be releasing it as an independent module.

The work to do this release is ongoing, but we've hit some snags in our build + release infrastructure preventing the publishing. We expect assertions to be available in PyPI (and all other package managers we support) Very Soon. I can't give a specific date at this time, but we're actively working on it. You can track the status via https://github.com/aws/aws-cdk/issues/16432. Closing this issue in favor of that one.

**Comment by keepler-ivanmarques** [comment]
Great! thanks!
