### ISSUE TITLE
(pipelines): Enable KMS Key rotation for pipeline

### ISSUE THREAD

**Issue by xeroxnir** [aws/aws-cdk#16813]
### Description

CodePipeline supports key rotation with enableKeyRotation prop.

Would be great to have the same property on the [pipeline construct](https://github.com/aws/aws-cdk/blob/2a629dd7a86cc36c3a503bfc5957880c9edd4d49/packages/%40aws-cdk/pipelines/lib/codepipeline/codepipeline.ts#L340). 

### Use Case

Enable rotation security best practice (also fix cfn_nag findings)

### Proposed Solution

Pass enableKeyRotation prop to the CodePipeline construct (similar to crossAccountKey).

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by rix0rrr** [comment]
For now, construct your own `codepipeline.Pipeline`, configure it as you wish, and pass that into the `CodePipeline`.

In general, not sure if this case wouldn't be better served by a mechanism like proposed here: https://github.com/aws/aws-cdk-rfcs/issues/25
