### ISSUE TITLE
(aws-appmesh): priority cannot be configured in gateway routes 

### ISSUE THREAD

**Issue by desoss** [aws/aws-cdk#16821]
### What is the problem?

Even if the AWS console allows to specify the gateway route priority in the gateway route configuration this is not possible in CDK.

### Reproduction Steps

Here I've no way to specify the priority of a gateway route.

```
virtualGateway.addGatewayRoute('trial-route', {
    gatewayRouteName: 'trial-route',
    routeSpec: appmesh.GatewayRouteSpec.http({
        match: {
            path: HttpGatewayRoutePathMatch.startsWith('/'),
            rewriteRequestHostname: false,
        },
        routeTarget: props.targetService,
    })
});
```

### What did you expect to happen?

I expect to be able to configure the gateway route priority as in the console:

![image](https://user-images.githubusercontent.com/10620399/136210664-1eab4a85-64ae-439f-8853-adab5f18346c.png)

### What actually happened?

Currently, the priority cannot be configured in the gateway routes. 

### CDK CLI Version

1.126.0

### Node.js Version

 16.4.1

### OS

macOS

### Language

Typescript

**Comment by Seiya6329** [comment]
@desoss - thank you very much for reporting the issue and I am very sorry for the inconvenience you are facing.

I am taking a looking a look at this issue we will respond by end of today with updates.

**Comment by Seiya6329** [comment]
I am confirming CDK is currently not allowing Gateway Route to configure `Priority`. 

I verified that the App Mesh console as well as [AWS CLI](https://docs.aws.amazon.com/cli/latest/reference/appmesh/create-gateway-route.html) does allow configuring Gateway Route with `Priority`.

However, https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-appmesh-gatewayroute-gatewayroutespec.html does not contain a field for `Priority`.

I am further getting confirmation if this is the bug.

**Comment by Seiya6329** [comment]
**Quick update:** We are deploying changes to CloudFormation to include `Priority` field. 

I think we are looking at end of November as a target for full CDK update completion.

**Comment by Seiya6329** [comment]
`Priority` field is now available in CloudFormation.
It should be becoming available for CDK L1 this week.

For CDK L2 support, we are still at end of November.

**Comment by Seiya6329** [comment]
Submitted the PR for supporting Gateway Route `Priority` in CDK L2 construct: https://github.com/aws/aws-cdk/pull/17694

**Comment by Seiya6329** [comment]
@desoss - we have pushed the support with the gateway route priority. This feature should become available on 12/16 (Thu).
