### ISSUE TITLE
(aws-efs): failed to create location when filesystem is still creating

### ISSUE THREAD

**Issue by DerkSchooltink** [aws/aws-cdk#16826]
### What is the problem?

Creating a filesystem with an EFS location in the same stack fails to create because directly after creating the filesystem it attempts to create the location, which does not work because the filesystem is still status=creating.

### Reproduction Steps

```
const fileSystem = new FileSystem(this, 'FileSystem', {
    vpc: vpc,
});

const efsLocation = new CfnLocationEFS(this, 'efsloc', {
    efsFilesystemArn: fileSystem.fileSystemArn,
    ec2Config: {
        ...
    },
});
```
Deploying this in a stack will cause this error.

### What did you expect to happen?

It might be difficult to find a good solution for this. I assume there is no way to let CDK await deployment of the location until after the filesystem is fully up and running. This is probably a Cloudformation limitation(?). 

Nonetheless, CDK has the ability to do more stuff that is not possible with native Cloudformation alone. Perhaps there might be a way to build this dependency on top of Cloudformation using CDK. Although I must admit I am not knowledgable enough to come up with a good idea.

### What actually happened?

The error I'm receiving:

`Invalid request provided: No available mount targets for <fs ID> found in <subnet ID>. Found the following mount targets in unavailable lifecycle states: <fs ID>=creating.`

Self-explanatory, I'd say. Creating the location is done too quick, the filesystem is not created yet.

### CDK CLI Version

1.126.0

### Node.js Version

v16.10.0

### OS

MacOS Big Sur v11.6

### Language

Typescript

### Language Version

3.9.7

### Other information

Perhaps this is issue is premature, considering the EFS module does not have a high-level construct yet. But it might be a cool feature to ship with the implementation of it. I upvoted #7546 at least. 😄

**Comment by peterwoodworth** [comment]
You can have resources depend on one another using the [`addsDependOn()`](https://docs.aws.amazon.com/cdk/api/latest/docs/core-readme.html#resource-options) method. This will cause resource B to start creation after resource A

**Comment by smislam** [comment]
I am experiencing the same issue and wondering if we should re-open or log a new ticket.  When I run my Stack, I get the following error (values obfuscated).

**Language: TypeScript
Node: v18.16.0
CDK: 2.94.0 (build 987c329)**

`MyEfsStack | 18/64 | 12:51:17 PM | CREATE_FAILED        | AWS::DataSync::LocationEFS            | ds-efs-1 (dsefs1) Resource handler r
eturned message: "Invalid request provided: No available mount targets for fs-****** found in subnet-******. Found th
e following mount targets in unavailable lifecycle states: fsmt-05aa93f8c3bbbe4ac=creating, fsmt-05aa93f8c3bbbe4ac=creating. (Service: Data
Sync, Status Code: 400, Request ID: ******-cd57-4806-bbdd-******)" (RequestToken: ******-c946-2c9b-3f9e-******, HandlerErro
rCode: InvalidRequest)`
