### ISSUE TITLE
rds.Credentials: cannot generate secret even having lots of characters excluded

### ISSUE THREAD

**Issue by gerardsegarra** [aws/aws-cdk#16824]
### What is the problem?

We are getting this error in cloudformation when trying to create a Postgres instance
```
Reason: The parameter MasterUserPassword is not a valid password. Only printable ASCII characters besides '/', '@', '"', ' ' may be used. (Service: AmazonRDS; Status Code: 400; Error Code: InvalidParameterValue; Request ID: d463b57c-d017-415a-abd6-454db4b08d84)
```
but we have added all the possible character we could think of in the except. Being quick before cloudformation rolledback the secret, we could see all the secret contained were regular characters.

### Reproduction Steps

This is how we generate the credentials
```
credentials = rds.Credentials.from_generated_secret(
            username=GENERIC_USERNAME,
            secret_name=secret_name,
            # Excluding chars by PSQL url restrictions
            exclude_characters="^ %+~`#$&*()|[]{}:;,-<>?!'/\\\",="
        )
```

### What did you expect to happen?

Create the master password for postgres

### What actually happened?

It couldn't create it

### CDK CLI Version

1.125.0

### Node.js Version

The one used by codepipeline

### OS

The one used by codepipeline

### Language

Python

### Other information

We are having this problem deploying from local and running a codepipeline deploying the cdk.

**Comment by peterwoodworth** [comment]
I wasn't able to reproduce this using the same `exclude_characters` configuration here

**Comment by gerardsegarra** [comment]
I cannot remove the exclude_characters because the service that connects to rds does not accept some characters and it's a third party service.

It's hard to reproduce because this only happens some times and not every time. 

This is the code for the whole class:
```
from aws_cdk import aws_rds as rds, aws_ec2 as ec2, core as cdk
from eks_commons import environment_helper

from modules.config.config import APPLICATION_NAME, DatabaseProps, GENERIC_USERNAME


class TDatabase(cdk.Stack):
    def __init__(
        self,
        scope: cdk.Construct,
        construct_id: str,
        configuration: DatabaseProps,
        allow_from: ec2.IPeer,
        env: cdk.Environment
    ) -> None:
        super().__init__(scope, construct_id, env=env)

        if configuration.instance_identifier:
            secret_name = environment_helper.build_secret_manager_path(
                APPLICATION_NAME,
                configuration.instance_identifier
            )
        else:
            raise RuntimeError("Database has not instance_identifier set")

        credentials = rds.Credentials.from_generated_secret(
            username=GENERIC_USERNAME,
            secret_name=secret_name,
            # Excluding chars by PSQL url restrictions
            exclude_characters="^ %+~`#$&*()|[]{}:;,-<>?!'/\\\",="
        )

        self.db = self._create_postgresql(
            configuration=configuration, credentials=credentials, allow_from=allow_from
        )

    def _create_postgresql(
        self,
        configuration: DatabaseProps,
        credentials: rds.Credentials,
        allow_from: ec2.IPeer,
    ) -> rds.DatabaseInstance:
        config_dict = configuration.dict()

        if configuration.instance_identifier and configuration.vpc:
            return rds.DatabaseInstance(
                self,
                "DB",
                credentials=credentials,
                security_groups=[
                    self._create_security_group(
                        "{}-sg".format(configuration.instance_identifier),
                        configuration.port,
                        configuration.vpc,
                        allow_from,
                    )
                ],
                **config_dict,
            )
        else:
            raise ValueError("Database name or vpc is not set")

    def _create_security_group(
        self, name: str, port: int, vpc: ec2.IVpc, allow_from: ec2.IPeer
    ) -> ec2.SecurityGroup:
        sg = ec2.SecurityGroup(self, "SecurityGroup", vpc=vpc, security_group_name=name)
        sg.add_ingress_rule(allow_from, ec2.Port.tcp(port))
        return sg
```

**Comment by klang** [comment]
It can be a bit difficult to construct the list of characters to exclude in a way that CloudFormation will accept.

`
import string
exclude_characters=string.printable
  .replace(string.ascii_letters, "")
  .replace(string.digits, "")
  .replace(string.whitespace, " ")
  .replace('#', "")
  .replace("$", "")
  .replace("_", "")

rds.DatabaseInstance(self, "Oracle",
   engine=rds.DatabaseInstanceEngine.oracle_ ...
   ...
   credentials=rds.Credentials.from_generated_secret(username="admin", exclude_characters=exclude_characters),
   ...
`

**Comment by skinny85** [comment]
@klang did you try to customize the set before? How did you do it, and what error did you get? Does the above code work?

**Comment by klang** [comment]
@skinny85 I used the `exclude_characters` line above, but adjusted it to fit the Oracle password rules

```exclude_characters="^ %+~`$&*()|[]{}:;,-<>?!'/\\\",="```

Oracle has some, [specific rules about passwords](https://gist.github.com/klang/6399e8d6d9db3a3157066d64bbc0b38d) but still got this error:

```The parameter MasterUserPassword is not a valid password. Only printable ASCII characters besides '/', '@', '"', ' ' may be used. (Service: AmazonRDS; Status Code: 400; Error Code: InvalidParameterValue; ```

my version of `exclude_characters` evaluate to
```my_version='!"%&\'()*+,-./:;<=>?@[\\]^`{|}~ '```

These two sets of characters are the same. `set(my_version) - set(exclude_characters) == set()`.

The only thing I can see, that might cause problems for me is the placement of the `^` .. if regexps are used somewhere in the chain, then we do have a general rule that says that ^ will negate the some of the pattern. 

```
         exclude_characters=string.printable.replace(string.ascii_letters, "").replace(string.digits, "").replace(string.whitespace, " ").replace('#', "").replace("$", "").replace("_", "")
         exclude_characters='!"%&\'()*+,-./:;<=>?@[\\]^`{|}~ '
+        exclude_characters="^ %+~`$&*()|[]{}:;,-<>?!'/\\\",="
         self._rds=rds.DatabaseInstance(self, "Oracle",
             database_name="{}".format(stage_name)[0:8],
             character_set_name="AL32UTF8",
 ```
 
 this doesn't work (it's the pattern you have above.
 
 changing the pattern to ```exclude_characters=" ^%+~`$&*()|[]{}:;,-<>?!'/\\\",="```, i.e. not having `^` as the first character, fixes the problem.
 
 So my crazy theory about the use of regexp character classes somewhere in the chain seems to be correct?

**Comment by skinny85** [comment]
@klang what error did you get when using the default `excludeCharacters` set that CDK uses?

**Comment by klang** [comment]
@skinny85 If I understand correctly, the default set is used when `excludeCharacters` is simply left out like this:

`credentials=rds.Credentials.from_generated_secret(username="admin")`

That's how I defined my database on the first run.

It did not produce any errors from CDK, but did make Oracle complain about an "invalid password".

**Comment by skinny85** [comment]
What version of the CDK did you use for this?

**Comment by klang** [comment]
```
(.venv) ➜  infrastructure git:(master) ✗ cdk version
2.17.0 (build f9cd009)
```

**Comment by skinny85** [comment]
That's the CDK CLI - can you show the output of `pip list | grep cdk`?

**Comment by klang** [comment]
```
(.venv) ➜  infrastructure git:(master) ✗ pip list | grep cdk
aws-cdk-lib       2.16.0
```

**Comment by skinny85** [comment]
Thanks. Could you open us a separate issue about this then? It seems like our [default exclude set](https://github.com/aws/aws-cdk/blob/1fdf1223304e15d905723553a40640b8bcb0ec56/packages/%40aws-cdk/aws-rds/lib/private/util.ts#L13-L21) is still not good enough for Oracle.

**Comment by klang** [comment]
@skinny85 I'lll open a separate issue. 

I actually only commented on this old issue, because I wanted "the next person" to have a slightly easier way to fix the problem :-)

There are two problems: 
1. the default exclude set isn't good enough for oracle
2. "^" can not be the first character in the exclude set.

**Comment by surdu** [comment]
Having the same issue, but with mariaDB and passing the pattern to `secretsmanager.Secret` instead (as I need to also add a secret rotation schedule).

Even with the suggested solution pattern (` ^%+~`$&*()|[]{}:;,-<>?!'/\\\",=`) doesn't fix the problem.

My code:

```ts
const dbSecret = new secretsmanager.Secret(this, "DBSecret", {
	secretName: "TestDB-Credentials",
	generateSecretString: {
		secretStringTemplate: JSON.stringify({ username: "my-user" }),
		generateStringKey: "password",
		excludeCharacters: " ^%+~`$&*()|[]{}:;,-<>?!'/\\\",=",
	},
});
```

**Comment by adyachok** [comment]
I would suggest:

const dbSecret = new secretsmanager.Secret(this, "DBSecret", {
	secretName: "TestDB-Credentials",
	generateSecretString: {
		secretStringTemplate: JSON.stringify({ username: "my-user" }),
		generateStringKey: "password",
		excludePunctuation: true,
                includeSpace: false
	},
});

**Comment by klang** [comment]
@surdu you can ad` the rotation schedule directly on `rds.DatabaseInstance` with `add_rotation_single_user`. 

```
oracle = rds.DatabaseInstance(self, "Oracle",
   engine=rds.DatabaseInstanceEngine.oracle_ ...
   ...
   credentials=rds.Credentials.from_generated_secret(
     username="admin", 
     exclude_characters=exclude_characters,
   ),
   ...)

oracle.add_rotation_single_user(automatically_after=Duration.days(7),exclude_characters=exclude_characters)
```

CDK will take care of the rest.

@adyachok in the case of oracle, I couldn't rely on the defaults for password generation, hence the issue.
