### ISSUE TITLE
(aws_eks): python type checking is incomplete

### ISSUE THREAD

**Issue by jaybocc2** [aws/aws-cdk#16839]
### What is the problem?

`aws_eks.Cluster(...,version=aws_eks.KubernetesVersion.V1_21,...)` results in a type checking error similar to https://github.com/aws/jsii/issues/1262 and https://github.com/aws/aws-cdk/issues/7143

note: CDK synths, bootstraps and deploys fine, this is purely a language and type checking annoyance.

### Reproduction Steps

```    3
    4 from aws_cdk.core import App, Construct, Stack, Environment
    5 from aws_cdk import aws_eks, aws_ec2
    6
    7
    8 class Sandbox(Stack):
    9     def __init__(self, scope: Construct, id: str, vpc_id: str, **kwargs):
   10         super().__init__(scope, id, **kwargs)
   11         vpc = aws_ec2.Vpc.from_lookup(self, "VPC", vpc_id=vpc_id)
>> 12         eks = aws_eks.Cluster(
>> 13             self, id, version=aws_eks.KubernetesVersion.V1_21, vpc=vpc
   14         )
   15
```

### What did you expect to happen?

no lint / typechecker / LSP errors

### What actually happened?

received error:

```
[Pyright reportGeneralTypeIssues] [E] Argument of type "(cls: KubernetesVersion) -> KubernetesVersion" cannot be assigned to parameter "version" of type "KubernetesVersion" in function "__init__"
  "object" is incompatible with "KubernetesVersion"
```

### CDK CLI Version

1.126.0

### Node.js Version

16.8.0

### OS

mac os

### Language

Python

### Language Version

python 3.9.6

**Comment by otaviomacedo** [comment]
Hi @jaybocc2. Just to confirm: in your setup.py, are all the CDK construct libraries pointing to the exact same version?
