### ISSUE TITLE
(aws-cloudwatch-actions): Add the possibility to have SSM OpsItem Action

### ISSUE THREAD

**Issue by vportascarta** [aws/aws-cdk#16861]
### Description

In addition to these actions : ApplicationScalingAction, AutoScalingAction, Ec2Action, Ec2InstanceAction, SnsAction, add an SystemManagerAction to be able to create OpsItem in SSM in a CW alarm.

### Use Case

We need this to group and prioritize all our alarm triggers into OpsCenter instead of using SNS notification.

### Proposed Solution

Add an action that build and add the arn into the alarm `"arn:aws:ssm:<region>:<account_id>:opsitem:<severity>#CATEGORY=<category>"`
Maybe use enum for severity and category

### Other information

On AWS Console UI
![image](https://user-images.githubusercontent.com/19411748/136456474-2a12a586-0226-4bc2-8a28-25cdff7bf9b0.png)

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by madeline-k** [comment]
Thanks for opening this feature request, @vportascarta! I think this would be a great feature to have. To implement, we need to add another action in the `aws-cloudwatch-actions` module here: https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/aws-cloudwatch-actions/lib.
If you are willing to open a PR that would be great! Take a look at our [contributing guide](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) to get started.

In the meantime, you can add the action arn to an Alarm using an [escape hatch](https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html). Your code could look something like this, where `scope` is the relevant scope, it probably would be `this`:
```
  const cfnAlarm = Node.of(alarm).defaultChild as cloudwatch.CfnAlarm;
  cfnAlarm.alarmActions?.push(`arn:aws:ssm:${Stack.of(scope).region}:${Stack.of(scope).account}:opsitem:<severity>#CATEGORY=<category>`);

```

**Comment by vportascarta** [comment]
Hi @madeline-k, the PR is already done #16923.
Please let me know if it needs something else to implement this feature.

**Comment by madeline-k** [comment]
Thanks for the PR, @vportascarta! Sorry I completely missed that when I was looking at this issue yesterday.
