### ISSUE TITLE
@aws-cdk/aws-memorydb: MemoryDB Cluster creation is error

### ISSUE THREAD

**Issue by SpringMT** [aws/aws-cdk#16867]
### What is the problem?

I try to create a MemoryDB Cluster using `@aws-cdk/aws-memorydb`,  `Error [ValidationError]: Template format error: Unrecognized resource types: [AWS::MemoryDB::Cluster]` happens.

AWS region is `ap-northeast-1`.

### Reproduction Steps

Reproduction code : https://github.com/SpringMT/memorydb-cdk

1. git clone git@github.com:SpringMT/memorydb-cdk.git
2. cd memorydb-cdk
3. cdk deploy

### What did you expect to happen?

Creat MemoryDB Cluster

### What actually happened?

` MemorydbCdkStack failed: Error [ValidationError]: Template format error: Unrecognized resource types: [AWS::MemoryDB::Cluster]` error happens.

### CDK CLI Version

1.126.0 (build f004e1a)

### Node.js Version

v16.8.0

### OS

macOS

### Language

Typescript

### Language Version

TypeScript (3.9.10)

**Comment by SpringMT** [comment]
Thank you for comments!
I'll wait for CloudFormation support for MemoryDB in `ap-northeast-1`.

**Comment by hayashier** [comment]
Now CloudFormation supports for MemoryDB in ap-northeast-1.
https://aws.amazon.com/jp/about-aws/whats-new/2021/11/amazon-memorydb-redis-aws-cloudformation/
