### ISSUE TITLE
Top-level L2 resources should have unmangled logical IDs

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#1687]
Customers expect that when they add L2 resources directly to the `Stack`, the `id` they provide for the L2 will be the logical ID of the underlying L1 resource. This will also clean up the logical IDs of deCDK resource (#1618).

Aside from this being a huge breaking change, and we should probably allow people to disable this behavior for backwards compat. I don't see why we shouldn't implement this heuristic.

Change logical ID to "Default" (or ".") and then `defaultChild` (#2290) should be the way to access these resources.

@rix0rrr @RomainMuller @sam-goodwin what do you guys think?

**Comment by rix0rrr** [comment]
I like it, but this will be a MASSIVE breaking change.

Easy fix is to disregard `"Resource"` path part, just like `"Defafult"` currently is.

**Comment by eladb** [comment]
This is something we should consider for v2.0 (added to the v2.0 issue)
