### ISSUE TITLE
core: add a lazy getter for `TagManager`

### ISSUE THREAD

**Issue by rittneje** [aws/aws-cdk#16899]
### Description

We would like to be able to add tags to a `core.CustomResource`, and have these tags be passed as one of the properties to the backing provider.

### Use Case

In our particular case, we have a `core.CustomResource` that is inserting records into a DynamoDB table. For auditing/debugging purposes, it would be extremely helpful to be able to record the stack tags into this record.

Currently we are working around this by sub-classing `core.Construct`, having it implement `core.ITaggable` by adding a `core.TagManager` property named `tags`, and then assigning the output of `tags.render_tags()` to a property value via a custom `core.IResolvable` implementation. However, this is pretty awkward.

### Proposed Solution

1. Update the `core.CustomResource` constructor to take `core.TagType` as a parameter, defaulting to `core.TagType.NOT_TAGGABLE`.
2. Create a mechanism for referencing the rendered tags within the properties, similar to `custom_resources.PhysicalResourceIdReference`. Alternatively, have the tags passed automatically.

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by rittneje** [comment]
@rix0rrr We tried with `Lazy` but it led to an inscrutable stack trace from jsii, so we could not use it at all.

@jamesorlakin Thanks for pointing that out. Curiously, that specific change is not mentioned in the release notes, but from the source code I can see it was added in 1.130.0 as part of #17029. @rix0rrr Can you amend the release notes?

**Comment by rix0rrr** [comment]
I guess we don't mention every code change in the release notes. Sorry for not tagging you back in here though, must have slipped my mind.

I don't think there's a lot of value in adding this note back in after the fact.
