### ISSUE TITLE
@aws-cdk/aws-secretsmanager.Secret.import context provider helper

### ISSUE THREAD

**Issue by RomainMuller** [aws/aws-cdk#1689]
When importing existing secrets, it is highly inconvenient to have to track which EncryptionKey should be used (you have to import the secret AND it's key, otherwise permission grants are not going to be managed for the key).

A context provided could assist in looking up the imported secret's KMS key so one does not have to manually do this.

**Comment by rix0rrr** [comment]
Still relevant
