### ISSUE TITLE
Ability to attach bare CfnInstances to classic load balancers

### ISSUE THREAD

**Issue by imajinos** [aws/aws-cdk#1691]
I've learned we can attach CfnInstances to elbv2 load balancers via InstanceTarget, but I've not found a way to attach bare CfnInstances to a classic load balancer. Docs suggest you need an auto-scaling group.

**Comment by rix0rrr** [comment]
I think that is correct. The only other way is is to have an instance register itself on startup (using a LaunchConfiguration), as described here: https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-deregister-register-instances.html

What is preventing you from using an AutoScalingGroup with 1 instance in it?

**Comment by imajinos** [comment]
What is preventing me...   ...  For this exercise I was attempting to replicate an existing environment so we could use the CDK to create new stacks,hopefully in the same form and style as existing. A distinct problem is updating our stack to use autoscaling groups and other features.

**Comment by StanSvec** [comment]
Is this planned to be added anytime soon?

**Comment by rix0rrr** [comment]
It seems like a bad idea to me to have a naked instance started using CDK, without the protection of an AutoScalingGroup of size 1. If the instance dies, it will not be replaced. Given that the AutoScalingGroup is safer and has the benefit of having the feature that is requested, I would recommend that approach, so we will not invest time into making this scenario work.

Someone from the community is free to step and contribute it though.

There looks to be no good way to do it in CloudFormation. I believe the usual approach is to write userdata scripts (or cfn-init scripts) that register and deregister the intance from the CLB.

**Comment by rix0rrr** [comment]
Closing this, unlikely to be something we'll work on.

**Comment by ncrothe** [comment]
A use case for this is when you need persistent storage and thus have a separate volume you want to attach. That is super-painful to do for an instance in an ASG.

**Comment by mackensen** [comment]
I agree that this is an uncommon use case but it does come up and there are times when you want the benefits of load balancing and CDK but an ASG is inappropriate. Registering from the instance does work, here's an example:

```typescript
ec2UserData.addCommands('aws elb register-instances-with-load-balancer --load-balancer-name ' + this.lb.loadBalancerName + ' --instances $(ec2-metadata --instance-id | cut -d " " -f 2)');
```

Note that the EC2 instance will need the `elasticloadbalancing:RegisterInstancesWithLoadBalancer` IAM permission on the load balancer.
