### ISSUE TITLE
aws-lambda: tag update triggered new lambda version and create failed

### ISSUE THREAD

**Issue by xinguaws** [aws/aws-cdk#16913]
### What is the problem?

My CDK app has applied a set of tags, during an update, one of the tag value was changed, in my CDK app, there is a lambda function which is referenced `myLambdaFunction.currentVersion` so when I ran cdk diff, it shows it will destroy current version and generate a new version, this caused new version creation failed because there is no configuration change for the lambda: "A version for this Lambda function exists ( 1 ). Modify the function to create a new version." 

### Reproduction Steps

```javascript
const cdk = require('@aws-cdk/core');
cdk.Tags.of(app).add(tag, value);
```
 

### What did you expect to happen?

CDK shouldn't try to generate a new Lambda version if there is just tag values being changed. This is definitely a bug. 

what we had to do is to remove that tag or prevent that tag value to change to avoid this error

### What actually happened?

cdk update failed

### CDK CLI Version

1.126

### Node.js Version

14

### OS

Linux

### Language

Typescript

**Comment by nija-at** [comment]
We are aware of this bug and have introduced a fix for this. Unfortunately, we cannot roll out this fix for everyone by default and needs to be opted in.

See https://docs.aws.amazon.com/cdk/api/latest/docs/aws-lambda-readme.html#currentversion-updated-hashing-logic

Can you confirm that this fixes the problem for you?
