### ISSUE TITLE
Ability to get cdk.SSMParameterProvider values for use in stack names

### ISSUE THREAD

**Issue by jasonthomasgray** [aws/aws-cdk#1692]
We would like to use values from `cdk.SSMParameterProvider` in our stack names to help us follow our naming conventions across environments.

Something like the following is what we would like to do:
```ts
const app = new cdk.App();
const envCode = new cdk.SSMParameterProvider(
    app,
    { parameterName: 'envCode' }
  ).parameterValue();
new Stack(app, `cfs-${envCode}-stack`);
app.run();
```
but this gives us the error:
`Cannot find a Stack parent for 'App'`
which is true as App is not a valid stack.

Hopefully this is something that is workable as a change/improvement.

We have a current workaround of using the aws-sdk to query for these parameters and use those, but it would be convenient if this was possible purely with CDK.

**Comment by eladb** [comment]
This is an interesting use case, which we should definitely explore.

One of the reasons you need a stack scope when defining an SSMParameterProvider is that it needs to know which environment (account/region) it needs to query. If you had multiple stacks in your app, each targeting a different account/region, then the SSM parameter value would have been potentially different.

**Comment by rix0rrr** [comment]
An escape hatch of sorts is we decouple the stack name from the ID (in progress in the "App" PR), and then make it mutable (that's not in). Then you could do this work.
