### ISSUE TITLE
(aws-ecs): cdk deploy did not update tags on existing IAM role

### ISSUE THREAD

**Issue by tsingh2k15** [aws/aws-cdk#16924]
### General Issue

cdk deploy did not update tags on existing IAM role

### The Question

**Scenario:**

Updating resource tags on existing CDK stack via cdk deploy command

**Expected outcome:**
Expecting that the tags will be applied to all child resources.

**Observed outcome:**
Tags did get apply to pretty much all ECS resources except IAM roles (task role and execution role).

**Question:**
I could not find further information from docs. I am not sure if this is intended behavior? Why did tags not apply on existing IAM roles.

### CDK CLI Version

aws-cdk@1.127.0

### Framework Version

aws-cdk@1.127.0

### Node.js Version

v14.18.0

### OS

Linux

### Language

Typescript

**Comment by peterwoodworth** [comment]
Hey @tsingh2k15,

How are you trying to apply the tags?

**Comment by peterwoodworth** [comment]
Glad you got it figured out @tsingh2k15!
