### ISSUE TITLE
Unable to update assume role policy of existing iam role.

### ISSUE THREAD

**Issue by sainath-everest** [aws/aws-cdk#16947]
### What is the problem?

Unable to update assume role policy of existing iam role.We are able to do through aws cli using **update-assume-role-policy** but there is no support in cdk.

### Reproduction Steps

- Create iam role
- update the assumed role policy of that role

### What did you expect to happen?

we should able to update assumed role policy of existing role.

### What actually happened?

Unable to update assume role policy of existing iam role.

### CDK CLI Version

1.116.0

### Framework Version

N/A

### Node.js Version

v12.22.6

### OS

linux

### Language

Python

### Language Version

Python 3.8

**Comment by peterwoodworth** [comment]
Hey @sainath-everest,

This is because you cannot actually modify imported resources. See our documentation [here](https://docs.aws.amazon.com/cdk/latest/guide/resources.html#resources_importing) on imported resources. Specifically:

> Although you can use an imported resource anywhere, you cannot modify the imported resource. For example, calling addToResourcePolicy (Python: add_to_resource_policy) on an imported s3.Bucket does nothing.
