### ISSUE TITLE
RDS: support passing PreferredMaintenanceWindow to Cluster database instances

### ISSUE THREAD

**Issue by cpaton** [aws/aws-cdk#16954]
### Description

When creating a DatabaseCluster it should be possible to specify PreferredMaintenanceWindow property for the database instances as per https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html#cfn-rds-dbinstance-preferredmaintenancewindow

### Use Case

Control maintenance window for database instances so maintenance is performed outside of production use hours e.g. minor version upgrades

### Proposed Solution

Add preferredMaintenanceWindow property to InstanceProps when creating a DatabaseCluster.  This value should be copied onto the underlying CfnDatabaseInstance object

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by skinny85** [comment]
Thanks for opening the issue @cpaton. This should be a relatively simple feature to implement - it means adding the `preferredMaintenanceWindow` property to the [`InstanceProps` interface](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-rds.InstanceProps.html), and then passing it [here](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-rds.InstanceProps.html).

Would you consider opening us a PR adding this feature? Here's our "Contributing guide": https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md.

Thanks,
Adam

**Comment by ronocod** [comment]
If anyone else is running into this, you can synchronize the DBInstance maintenance windows with the DBCluster window using this:
```typescript
function setInstanceMaintenanceWindows(cluster: rds.DatabaseCluster) {
  const clusterNode = cluster.node.children.find(
    (c) => c instanceof rds.CfnDBCluster
  ) as rds.CfnDBCluster;
  cluster.node.children.forEach((c) => {
    if (c instanceof rds.CfnDBInstance) {
      const temp = c;
      temp.preferredMaintenanceWindow = clusterNode.preferredMaintenanceWindow;
    }
  });
}

//  setInstanceMaintenanceWindows(this.cluster);

**Comment by keisukekomeda** [comment]
Can also use cdk.Aspects to set node property.

```ts
cdk.Aspects.of(cluster).add({
  visit: (node) => {
    if (node instanceof rds.CfnDBInstance) {
      node.addPropertyOverride(
        "PreferredMaintenanceWindow",
        "web:19:00-wed:19:30",
      );
    }
  },
});
```
