### ISSUE TITLE
(aws-lambda-nodejs): deploy failed while over 40+ lambda functions in a same stack

### ISSUE THREAD

**Issue by tai-acall** [aws/aws-cdk#16971]
### What is the problem?

CDK Deploy failed if I create a stack with over 40+ lambda functions build with aws-lambda-nodejs module.

The root cause is too many lambda function in a same stack and trigger the limit of CloudFormation API.

The only way to deploy this large stack is comment-out about half of lambda function code then retry.

This shouldn't happen if we know there is a limit rate of CloudFormation API, breaking down to several small stack or just decrease the deployment rate behind scenes.

### Reproduction Steps

1. create a stack.
2. just create a simple lambda function like hello-world.
3. copy and paste it over 40 times.

### What did you expect to happen?

Deploy successfully.

### What actually happened?

Deploy failed with a CloudFormation Error, but the error message is not helpful.

### CDK CLI Version

1.53.0 (build 6c326cb)

### Node.js Version

v15.13.0

### OS

MacOS 10.14.6

### Language

Typescript

**Comment by peterwoodworth** [comment]
Hey @tai-acall, I'm going to relabel this as a feature request, seeing as everything here is working as intended.

Can you clarify what exactly you mean here?

> This shouldn't happen if we know there is a limit rate of CloudFormation API, breaking down to several small stack or just decrease the deployment rate behind scenes.

Thanks
