### ISSUE TITLE
(aws-cloudfront): Can't create a cache policy that forwards Authorization header and disabled cache

### ISSUE THREAD

**Issue by Dzhuneyt** [aws/aws-cdk#16977]
### What is the problem?

```
11:41:21 AM | UPDATE_FAILED        | AWS::CloudFront::CachePolicy
| FrontendCachePolicyFE1BF1A8
Resource handler returned message: "Invalid request provided: AWS::CloudFront::Ca
chePolicy" (RequestToken: 97090027-0f18-5818-dcee-5912876f4bd3, HandlerErrorCode:
InvalidRequest)
```

This is the error that I get when I try to define a `cachePolicy` for a Custom Origin behavior of a CloudFront Distribution, using code like the one below.

I'm already aware of the `cloudfront.CachePolicy.CACHING_DISABLED` (https://github.com/aws/aws-cdk/issues/12461) option but unfortunately this doesn't fit all use cases. For example, if the Custom Origin is an API Gateway, to which I want to forward the "Authorization" header - it doesn't forward it. With the custom CachePolicy I have the possibility to whitelist the Authorization header, so it's forwarded, but at the same time I want to disable cache.

The only solution I have found is to increase `defaultTtl` to an arbitrary value larger than zero, e.g. 1 seconds, but I find this to be not an ideal solution for scenarios where API endpoints (hidden behind a CloudFront), might be called rapidly in sub-1-second intervals.

In summary, this doesn't disable the cache, it just reduces it to 1 second. I want to disable it.

### Reproduction Steps

```
 cachePolicy: new CachePolicy(this, 'CachePolicy', {
      headerBehavior: CacheHeaderBehavior.allowList(
          'Authorization',
      ),
      cookieBehavior: CacheCookieBehavior.none(),
      queryStringBehavior: CacheQueryStringBehavior.all(),
      enableAcceptEncodingBrotli: true,
      enableAcceptEncodingGzip: true,
      minTtl: Duration.seconds(0),
      maxTtl: Duration.seconds(0),
      defaultTtl: Duration.seconds(0),
  }),
```

### What did you expect to happen?

Cache Policy for the origin is configured and CloudFront doesn't cache any requests to the Origin AND sends the Authorization header to the Origin always.

### What actually happened?

Deployment fails with `defaultTtl=0 seconds` OR deployment succeeds with `defaultTtl=1 seconds` but this caches response in CloudFront for 1 second

### CDK CLI Version

1.127.0 (build 0ea309a)

### Node.js Version

14

### OS

MacOS

### Language

Typescript

**Comment by njlynch** [comment]
This configuration (no cache, but forward the Authorization header) does not appear to be supported by CloudFront.

https://aws.amazon.com/premiumsupport/knowledge-center/cloudfront-authorization-header/

I believe the recommendation here would be to set a maximum TTL of 1 second, but a default/minimum of 0. This won't necessary mean all request are cached for 1 second; this depends on whether or not your origin returns proper caching headers. See https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Expiration.html for a more detailed explanation.

Closing out. Feel free to mention me/Peter will any follow-ups.

**Comment by Tehnix** [comment]
> AllViewerExceptHostHeader comes from https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/using-managed-origin-request-policies.html, cdk-lib hasn't included this policy yet. hopefully soon.

For anyone coming here later, it has been added to cdk-lib as `cloudfront.OriginRequestPolicy.ALL_VIEWER_EXCEPT_HOST_HEADER` :)
