### ISSUE TITLE
(lambda-nodejs): esbuild command not found

### ISSUE THREAD

**Issue by aaronce** [aws/aws-cdk#16988]
### What is the problem?

when using `@aws-cdk/aws-lambda-nodejs` and defining the "entry" property, then running `cdk synth` fails

### Reproduction Steps

fails with the following terminal output:
```
$ cdk synth
Bundling asset CdkStack/Resolver/Code/Stage...
yarn run v1.22.4
warning package.json: No license field
$ C:\Users\user\apps\cdk-static-site\cdk-static-site\cdk\node_modules\.bin\esbuild --bundle C:\Users\user\apps\cdk-static-site\cdk-static-site\cdk\lib\cdk-stack.Resolver.ts --target=node14 --platform=node --outfile=C:\Users\user\apps\cdk-static-site\cdk-static-site\cdk\cdk.out\bundling-temp-af512e5a80ff7fab10e40f99f3bd28a3c602ce57982205cb1560d68521ac3206\index.js --external:aws-sdk
/usr/bin/bash: C:Usersuserappscdk-static-sitecdk-static-sitecdknode_modules.binesbuild: command not found
←[2K←[1G←[31merror←[39m Command failed with exit code 127.
←[2K←[1G←[34minfo←[39m Visit ←[1mhttps://yarnpkg.com/en/docs/cli/run←[22m for documentation about this command.
Failed to bundle asset CdkStack/Resolver/Code/Stage, bundle output is located at C:\Users\user\apps\cdk-static-site\cdk-static-site\cdk\cdk.out\bundling-temp-af512e5a80ff7fab10e40f99f3bd28a3c602ce57982205cb1560d68521ac3206-error: Error: cmd exited with status 127
Subprocess exited with error 1
```

Stack code is as follows:
```
export class CdkStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const lambdaResolver = new lambdaNodejs.NodejsFunction(this, "Resolver", {
      entry: path.resolve('lib/cdk-stack.Resolver.ts'),
    });
  }
}
```

Project structure looks like this:
- lib/
-- cdk-stack.ts
-- cdk-stack.Resolver.ts

### What did you expect to happen?

Expected that the "entry" property would be able to specify the file and compile with esbuild correctly.  

If I update pathing and manually run :
```
$ ./node_modules/.bin/esbuild --bundle C:/Users/user/apps/cdk-static-site/cdk-static-site/cdk/lib/cdk-stack.Resolver.ts --target=node14 --platform=node --outfile=C:/Users/user/apps/cdk-static-site/cdk-static-site/cdk/cdk.out/bundling-temp-af512e5a80ff7fab10e40f99f3bd28a3c602ce57982205cb1560d68521ac3206/index.js
```
then run:
`cdk synth` it works as expected 

### What actually happened?

received error as described above 

### CDK CLI Version

1.127.0 (build 0ea309a)

### Framework Version

1.127.0

### Node.js Version

v14.18.0

### OS

windows 10

### Language

Typescript

### Language Version

3.9.7

### Other information

occurs when using yarn or npm

**Comment by jogold** [comment]
Cannot reproduce on Windows 10.

How is `esbuild` installed and which version?

**Comment by aaronce** [comment]
I've managed to get this working by upgrading to the latest yarn version. Seems older versions (1.xx) were the issue in this case.
