### ISSUE TITLE
(vpc): cant reference a default sg when choosing a existing vpc

### ISSUE THREAD

**Issue by wttat** [aws/aws-cdk#16989]
### General Issue

cant reference a default sg when choosing a existing vpc

### The Question

This is my cdk code:

```

        # choose or create a vpc
        if use_default_vpc == 1:
            self.vpc = ec2.Vpc.from_lookup(self, 'VPC', is_default = True) 
        elif vpc_id != "":
            self.vpc = ec2.Vpc.from_lookup(self, 'VPC', is_default = False,vpc_id = vpc_id) 
        else:
            self.vpc = ec2.Vpc(self, "VPC",
            max_azs=1, # single AZ
            subnet_configuration=[
                {"name":"public","subnetType":ec2.SubnetType.PUBLIC},
                {"name":"private","subnetType":ec2.SubnetType.PRIVATE}
                ]
            )


        # create fsx for lustre, if we use 2.4T storage, then must apply LZ4 compression, but not found in cdk?

        self.file_system = fsx.LustreFileSystem(
            self,'FSX',
            lustre_configuration={"deployment_type": fsx.LustreDeploymentType.PERSISTENT_1,
                                    "per_unit_storage_throughput":100}, # 
            vpc = self.vpc,
            vpc_subnet=self.vpc.public_subnets[0],
            storage_capacity_gib = 4800,

            ##### 
            removal_policy=cdk.RemovalPolicy.DESTROY,
            security_group = ec2.SecurityGroup.from_security_group_id(
                                self,"FSXSG",
                                security_group_id=self.vpc.vpc_default_security_group
                            ),
        )

```

the sg of fsx works fine when creating a new vpc, but when it comes to using the default vpc or manually choosing a vpc via vpcid, got error for:

**cdk synth**
```
Traceback (most recent call last):
  File "app.py", line 36, in <module>
    vpc_stack = EC2VPCCdkStack(app, "EC2VPCCdkStack",
  File "/Users/twuam/Library/Python/3.8/lib/python/site-packages/jsii/_runtime.py", line 86, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/twuam/Desktop/AWSome Builder/2&3/af2-batch-cdk/af2_batch_cdk/vpc_ec2.py", line 106, in __init__
    self, "default_security_group", self.vpc.vpc_default_security_group
  File "/Users/twuam/Library/Python/3.8/lib/python/site-packages/jsii/_reference_map.py", line 149, in __getattr__
    raise AttributeError(f"'%s' object has no attribute '%s'" % (type_info, name))
AttributeError: '<class 'aws_cdk.core.Resource'>+<class 'aws_cdk.aws_ec2._IVpcProxy'>' object has no attribute 'vpc_default_security_group'
Subprocess exited with error 1
```

how am I supposed to solve this?

### CDK CLI Version

1.128.0 (build 1d3883a)

### Language

Python

**Comment by peterwoodworth** [comment]
Hey @wttat,

Looking up a VPC will return an [IVpc](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ec2.IVpc.html), which doesn't contain any information about the VPC's security groups. You will want to look up a security group independently using the [`SecurityGroup.fromLookup()`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ec2.SecurityGroup.html#static-fromwbrlookupscope-id-securitygroupid) method

**Comment by wttat** [comment]
> Hey @wttat,
> 
> Looking up a VPC will return an [IVpc](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ec2.IVpc.html), which doesn't contain any information about the VPC's security groups. You will want to look up a security group independently using the [`SecurityGroup.fromLookup()`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ec2.SecurityGroup.html#static-fromwbrlookupscope-id-securitygroupid) method

thx for the explanation.
Just one more question, I am need to choose the default security group from the vpc, but if the IVpc does not contain that info, and the SecurityGroup.fromLookup() method need the SG id from the beginning. is there any solution for me to manually select a vpc then get it default SG?

**Comment by peterwoodworth** [comment]
Thanks for the response @jumic 

I'll try to get your proposed solution gets looked at soon, this is highly desired by customers so it should be high priority :)
