### ISSUE TITLE
msk: CDK doesn't allow a cluster with multiple authentication methods

### ISSUE THREAD

**Issue by nlongton** [aws/aws-cdk#16980]
### General Issue

We want to use IAM auth but this is only for Java so we also need TLS for python etc.

### The Question

We want to use IAM auth but this is only for Java so we also need TLS for python etc.
When i use the AWS Console to create a MSK cluster I can select none, TLS and IAM and get multiple connection string. eg:

TLS:
b-1.***.$$$$.kafka.us-west-2.amazonaws.com:9094,b-2.***.$$$$.kafka.us-west-2.amazonaws.com:9094
IAM:
b-1.***.$$$$.kafka.us-west-2.amazonaws.com:9098,b-2.***.$$$$.kafka.us-west-2.amazonaws.com:9098
Plaintext:
b-1.***.$$$$.kafka.us-west-2.amazonaws.com:9092,b-2.***.$$$$.kafka.us-west-2.amazonaws.com:9092

However the logic in the cluster.ts prevents creating a dual TLS and IAM credential properties class, and even if it did then this logic only acts on one type

> 
>     let clientAuthentication;
>     if (props.clientAuthentication?.saslProps?.iam) {
>       clientAuthentication = {
>         sasl: { iam: { enabled: props.clientAuthentication.saslProps.iam } },
>       };
>     } else if (props.clientAuthentication?.saslProps?.scram) {
>       clientAuthentication = {
>         sasl: {
>           scram: {
>             enabled: props.clientAuthentication.saslProps.scram,
>           },
>         },
>       };
>     } else if (
>       props.clientAuthentication?.tlsProps?.certificateAuthorities !== undefined
>     ) {
>       clientAuthentication = {
>         tls: {
>           certificateAuthorityArnList: props.clientAuthentication?.tlsProps?.certificateAuthorities.map(
>             (ca) => ca.certificateAuthorityArn,
>           ),
>         },
>       };
>     }
> 

Is this constraint imposed by the SDK - havent had time to look there - and how does the console manage it?

### CDK CLI Version

1.123.0

### Framework Version

1.127.0

### Node.js Version

14.17.0

### OS

any

### Language

Typescript

### Language Version

3.9.7

**Comment by ldecaro** [comment]
I wonder whether this is related to old codebase. According to [this](https://aws.amazon.com/about-aws/whats-new/2021/09/amazon-msk-multiple-authentication-modes-tls-encryption-settings/) release, MSK recently added the ability to handle a combination of authentication modes.

**Comment by otaviomacedo** [comment]
> I wonder whether this is related to old codebase. According to [this](https://aws.amazon.com/about-aws/whats-new/2021/09/amazon-msk-multiple-authentication-modes-tls-encryption-settings/) release, MSK recently added the ability to handle a combination of authentication modes.

Yes, I believe that's the issue. I'm marking this as a `p2` feature request. We welcome contributions from the community. If you can submit with a PR to resolve this, I'll be happy to review it.

**Comment by nlongton** [comment]
I’ll see If I can work out how to do it – would you want this in v1 or v2 of the CDK?

**Comment by dberry-trip** [comment]
any update on when this is going to be fixed?

the workaround of setting up one auth in the cdk, and then turning on the another auth in the console doesn't really work in an IAC (infrastructure as code) context where you're not allowed to use the console in production, hence the reliance on cdk.

fix in cdk v2 please.

**Comment by gmuslia** [comment]
@otaviomacedo I have added this initial PR to address this feature request: https://github.com/aws/aws-cdk/pull/22041 Looking forward to push this feature into CDK.
