### ISSUE TITLE
QuickSight: possibility to schedule the SPICE refresh via the CDK

### ISSUE THREAD

**Issue by LucianP84** [aws/aws-cdk#16998]
### Description

Hello,

At present time we can do this manually. Would it be possible to include the possibility in the CDK for this? 
![2021-10-15 13_33_24-Home](https://user-images.githubusercontent.com/58596880/137480633-8c390ef1-d569-4900-947c-322ffb6f74bd.jpg)

### Use Case

To automatize as much as possible the QuickSight dataset creation.

### Proposed Solution

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-quicksight-dataset.html#cfn-quicksight-dataset-importmode

...
 importMode: 'SPICE',
**refreshSchedule: // CRON expression here //**
...

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by LucianP84** [comment]
Thank You,

I will do that.

**Comment by LucianP84** [comment]
We got in touch with your colleagues and decided to reopen this while we wait for the implementation on their side(Case ID 9210942081).

Thank You,

**Comment by rantoniuk** [comment]
Last update in #9210942081 is that it was raised as internal PFR - I just checked and I can see the case fine in AWS Console.

**Comment by jorgepulidoibm** [comment]
Hi, is there any news with this? I even tried using the properties override but the validation blocks it.

**Comment by LucianP84** [comment]
Hi back, I am not checking actively if this was implemented. I need to check the status and read the new release documentations.

**Comment by rubenfonseca** [comment]
Just pinging for visibility here.

**Comment by LucianP84** [comment]
Working as expected. Thank You!
