### ISSUE TITLE
(@aws-cdk/aws-lambda-go): how to add source code to the .zip file

### ISSUE THREAD

**Issue by joekendal** [aws/aws-cdk#17007]
### link to reference doc page

https://docs.aws.amazon.com/cdk/api/latest/docs/aws-lambda-go-readme.html

### Describe your issue?

Seeking guidance for usage with bundling source code inside the .zip. 

Currently the documentation shows before and after hooks but is not clear how to add source code to the .zip file.

For example, say we want to build it as usual but then add the source files to the zip (in order to get source mappings for Sentry) (https://docs.sentry.io/platforms/go/serverless/), 

Then we need to modify the zip command specifically:
```
zip -r handler.zip bin/main main.go
```

**Comment by ryparker** [comment]
Hey @joekendal 👋🏻 

> Currently the documentation shows before and after hooks but is not clear how to add source code to the .zip file.
>
> For example, say we want to build it as usual but then add the source files to the zip (in order to get source mappings for Sentry

You could use the `outputDir` parameter that is available to the `commandHooks` to locate the archive after bundling. This should allow you to modify the archive like so:

```ts
new lambda.GoFunction(this, 'handler', {
  bundling: {
    commandHooks: {
	 // Add source code to archive
      afterBundling(inputDir: string, outputDir: string): string[] {
        return [`zip -r ${outputDir}/*.zip bin/main main.go`];
      },
      // ...
    },
  },
});
```
_modified snippet from ["Command hooks" CDK docs](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-lambda-go-readme.html#command-hooks)_

⚠️ Keep in mind:
> The commands will run in the environment in which bundling occurs: inside the container for Docker bundling or on the host OS for local bundling.

_["Command hooks" CDK docs](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-lambda-go-readme.html#command-hooks)_
