### ISSUE TITLE
(assertions): Capture captures value from last resource with matching type, not matched props

### ISSUE THREAD

**Issue by poWer4aiX** [aws/aws-cdk#17009]
### What is the problem?

I used `Template.findResources()` to filter for one resource in a stack, by type and value of the `Name` tag. For one property I used a `Capture()`. My expectation was that the captured value will be the one of the resource found, which was not the case. Instead, it was the value from the resource in the stack matching just the given type.

### Reproduction Steps

```ts
test('capture', () => {
	const capture = new Capture();
	const resources = {
		Resources: {
			res1: { Type: 'res', Name: 'a', Prop: 1 },
			res2: { Type: 'res', Name: 'b', Prop: 2 }
		}
	}
	const template = Template.fromJSON(resources)
	const res = template.findResources('res', {
		Name: 'a', Prop: capture
	})
	// filtered resource is the correct one.
	console.log(JSON.stringify(res, null, 4))
	// fails, as the value (2) of the last 'Prop' from all resources is
	// captured, not the one of the last matching resource (1).
	expect(capture.asNumber()).toEqual(1);
})
```

### What did you expect to happen?

The captured value should be the value from the last resource being filtered (i.e. by type and optional attributes). In the example code given above this should be 1 instead of 2.

### What actually happened?

The captured value is the one of the attribute from the last resource of the resource type, independent if this one matched or not.

### CDK CLI Version

1.128.0

### Framework Version

1.128.0

### Node.js Version

14.17.4

### OS

Ubuntu 20.04, running in an WSL on Windows 10

### Language

Typescript

### Language Version

3.9.7

**Comment by nija-at** [comment]
_Originally posted by @nija-at in https://github.com/aws/aws-cdk/pull/17012#pullrequestreview-799107631_

First, we need to decide what is the correct behaviour if `Capture` is used when there are multiple matching entries. There are two options -

(1) return all of them in a series such as

```ts
captured.asString(); // "Foo"
captured.next().asString(); // "Bar"
...
```

or 
(2) throw an error in such a case.


In either case, the solution should be in the `Capture` class to hold state of all values that has flown through it, and finally decide how to handle them.
