### ISSUE TITLE
(CDK Pipelines): Ability to have CDK Pipelines as events target

### ISSUE THREAD

**Issue by raajheshkannaa** [aws/aws-cdk#17014]
### Description

We have existing capability to add `Codepipeline` as a target for an cloudwatch event or event bridge event, however we can't do the same for `CDK Pipelines` yet.

### Use Case

`Codepipeline` and `CDK pipelines` differ in various use cases and is preferred over each other for different reasons, with self mutation being the biggest advantage.

### Proposed Solution

Similar method as we add a target for the `Codepipeline` construct, I'd like to use CDK Pipelines as a target `aws_events_targets` for an `aws_events` event.

### Other information

Right now we get the error, when trying to follow the same `rule.add_target(targets.CodePipeline(pipeline))` with CDK Pipelines

```
jsii.errors.JavaScriptError: 
  Error: Resolution error: Supplied properties not correct for "CfnRuleProps"
    targets: element 0: supplied properties not correct for "TargetProperty"
      arn: required but missing.
```

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by rix0rrr** [comment]
You can use `targets.CodePipeline(pipeline.pipeline)` (which is actually a `codepipeline.CodePipeline` object, not a `pipelines.CodePipeline` object)

https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_pipelines.CodePipeline.html#pipeline
