### ISSUE TITLE
(aws-elasticloadbalancingv2): NetworkTargetGroupProps does not expose connection_termination attribute

### ISSUE THREAD

**Issue by Avinm** [aws/aws-cdk#17010]
### Description

CDK does not expose a mechanism to set `deregistration_delay.connection_termination.enabled` property for NLB targets.

> **deregistration_delay.connection_termination.enabled** - Indicates whether the load balancer terminates connections at the end of the deregistration timeout. The value is true or false. The default is false. 

Docs: https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_TargetGroupAttribute.html

### Use Case

To customize the value for `connection_termination` attribute when defining NLB via CDK.

### Proposed Solution

Expose a mechanism to set a value for `connection_termination.enabled` possibly via  `NetworkTargetGroupProps`

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by njlynch** [comment]
Thanks for the feature request.

In the interim, as a workaround, you can use [escape hatches](https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html) to set the attribute.

We welcome community contributions! If you are able, we encourage you to [contribute](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md).

**Comment by yeti-g** [comment]
The absence of this attribute causes a warning in the AWS console.

<img width="430" alt="Screen Shot 2022-01-19 at 11 04 59 AM" src="https://user-images.githubusercontent.com/95112011/150168946-413a61d6-7a7c-4bf6-b059-198a3454dcc4.png">

**Comment by yeti-g** [comment]
@njlynch please share an escape hatch example for a Fargate task's target group.
