### ISSUE TITLE
pipelines: unable to create dynamo global table

### ISSUE THREAD

**Issue by maletor** [aws/aws-cdk#17013]
### General Issue

Cannot use reference architecture to deploy Lambda and Dynamo Global Table

### The Question

This architecture (see: below), is impossible to model on aws-cdk with pipelines, so far as I can tell. 

One issue is you can't reference the dbStack from within the ComputeStack cross region.

The other issue is you don't want to deploy the DatabaseStack twice. It's just one deploy (with multiple regions) Is this understanding correct?

So how do you implement the reference architecture with CDK pipelines?

```ts
class ProductionApplication extends Stage {
  constructor(scope: Construct, id: string, props?: StageProps) {
    super(scope, id, props);

    const dbStack = new DatabaseStack(this, "DatabaseStack", env: { region: "us-west-1" });

    new ComputeStack(this, "ComputeWestStack", { dbStack, env: { region: "us-west-1" } });
    new ComputeStack(this, "ComputeEastStack", { dbStack, env: { region: "us-east-2" });
  }
}
```

![Screen Shot 2021-10-15 at 8 41 20 PM](https://user-images.githubusercontent.com/138785/137572398-6fa02b4c-f718-488c-9277-686532c98dbd.png)

https://d1.awsstatic.com/events/reinvent/2019/REPEAT_1_Best_practices_for_building_multi-region,_active-active_serverless_applications_SVS337-R1.pdf

### CDK CLI Version

2.0

### Language

Typescript

**Comment by rix0rrr** [comment]
> One issue is you can't reference the dbStack from within the ComputeStack cross region.

Correct. We currently have no way to reference generated resource names cross-environment, so you will have to give your resources a physical name.

Using `tableName: PhysicalName.GENERATE_IF_NEEDED` will work and is probably the simplest solution: https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.PhysicalName.html
