### ISSUE TITLE
(cloud9): Add support for SSM connection type

### ISSUE THREAD

**Issue by otterley** [aws/aws-cdk#17027]
### Description

Add support for SSM connection type as per https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloud9-environmentec2.html#cfn-cloud9-environmentec2-connectiontype

### Use Case

This will make it easier for customers to install their Cloud9 environments into private subnets while still allowing access to the IDE via the console.

### Proposed Solution

Add a new property for the connection type. The property can be an enumerated type whose valid values can be either `SSH` or `SSM`. It might also be helpful to default to SSM automatically if the provided subnet types are private.

### Other information

Workaround:

```ts
cloud9env.node.defaultChild as cloud9.CfnEnvironmentEC2).connectionType = 'CONNECT_SSM';
```

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by skinny85** [comment]
Thanks for opening the issue @otterley! We encourage community contributions, so if you'd like to open us a Pull Request adding this feature, that would be fantastic! Our "Contributing" guide: https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md.

Thanks,
Adam
