### ISSUE TITLE
(@aws-cdk/assert): toMatchInlineSnapshot raises dependency error (for prettier)

### ISSUE THREAD

**Issue by invke** [aws/aws-cdk#17030]
### What is the problem?

The `@aws-cdk/assert` has a dependency on `prettier` when using `toMatchInlineSnapshot()`. I only really used the method to see the matched output when working with someone. Not really a critical issue but I thought it'd be good to capture.

### Reproduction Steps

Run a snapshot test using `toMatchInlineSnapshot()` when `prettier` is not listed as a direct dependency of the project (e.g. if you use `eslint`).

### What did you expect to happen?

The test to run and the inline snapshot generated.

### What actually happened?

The test failed and the inline snapshot was not generated.

```
$ yarn test
yarn run v1.22.15
warning package.json: No license field
$ jest
 FAIL  spec/constructs/api-application.spec.ts
  ● Test suite failed to run

    Cannot find module 'prettier' from 'node_modules/jest-jasmine2/build/setup_jest_globals.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)

 PASS  spec/constructs/network.spec.ts

Test Suites: 1 failed, 1 passed, 2 total
Tests:       4 passed, 4 total
Snapshots:   0 total
Time:        1.587 s, estimated 2 s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### CDK CLI Version

1.127.0

### Node.js Version

16.3.0

### OS

macOS 11.2.3

### Language

Typescript

### Language Version

3.9.7

**Comment by kaizen3031593** [comment]
Hey @invke, similar to your other question can you try snapshot testing using the modern [Assertions](https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/assertions) library? The README claims that snapshot testing is supported in jest so let me know if that's not the case!

**Comment by invke** [comment]
Hey @kaizen3031593, shifting to use #17031 works fine. The `@aws-cdk/assert` library does support snapshot tests fine, just if you try use the `toMatchInlineSnapshot` method without having explicitly declared `prettier` as a dependency in your `package.json` then you get this error. Not a particularly big deal, as I imagine most would use the `toMatchSnapshot` method.
