### ISSUE TITLE
(CloudTrail): ability to import Trail

### ISSUE THREAD

**Issue by adsimone-aws** [aws/aws-cdk#17033]
### General Issue

get existing trail from environment

### The Question

I am trying to include a trail in a stack. The issue is that, in some aws accounts, the trail may already exist. In this case, I want the stack to include the trail from the environment (pretty much the same as I can do already with an s3 Bucket or an IAM role). We have some automated testing in place that checks things like how many resources of each type the stack contains, so it is important to make sure a trail is always there, even if not newly created.

Contrary to s3 buckets and iam roles, I could not find an obvious way of referencing a trail from the environment.
Is this by design, or just something nobody else needed up to now? Or maybe I am overlooking something?

Thanks for your help,

Andrea.

### CDK CLI Version

1.123.0

### Language

Python

**Comment by mrpackethead** [comment]
This is an issue for me, so adding my +1.  I want to be able to use it to add data events to an exisiting cloudtrail. ( for use with cdkpipelines )..    Given i have 100's of pipelines in my account, it is not possible to create a new cloudtrail for every one. 

at the point, it looks like the workaround will likely be a custom resource, to call an API
