### ISSUE TITLE
(aws-ec2): SubnetType.PRIVATE_WITH_NAT selection with imported VPC also returns isolated subnet(s)

### ISSUE THREAD

**Issue by encron** [aws/aws-cdk#17035]
### What is the problem?

When a vpc is imported via f.e.:

```
const vpc = Vpc.fromLookup(this, 'MyVpc', {
            tags: {
                Name: 'my-vpc',
            },
        });
```

and the subnets are fetched using the `selectSubnets` function with the `PRIVATE` or `PRIVATE_WITH_NAT` type, subnets without a NAT route will also be included in the selection.

### Reproduction Steps

1. Create a VPC with both private subnets that have a route to a NAT gateway/instance and one or more private subnets with only a local route.

2. Import the VPC

```
const vpc = Vpc.fromLookup(this, 'MyVpc', {
            tags: {
                Name: 'my-vpc',
            },
        });
```

3. Select the private subnets with a NAT route

```
vpc.selectSubnets({subnetType: SubnetType.PRIVATE_WITH_NAT}
```

### What did you expect to happen?

Only private subnets with a route to a NAT gateway/instance should be returned.

### What actually happened?

All private subnets were returned, also the subnets with only a local route.

### CDK CLI Version

1.127.0

### Node.js Version

v16.9.1

### OS

MacOS and Debian

### Language

Typescript

### Other information

My `cdk.context.json` file also contains the isolated subnet(s) in the entry for `Private` subnets in the `subnetGroups` field.

I'm not sure how it is determined which subnets are `Private` or `Isolated` but I would expect it to check for the presence of a NAT route.

I found https://github.com/aws/aws-cdk/blob/74066ca5c19509b60d95fc35ac7f732f44c6d8ae/packages/aws-cdk/lib/context-providers/vpcs.ts#L67-L71
where it seems that there is no check for an isolated subnet type and where the type gets set to `SubnetType.Private` if there is no IGW route and/or it does not have the `MapPublicIpOnLaunch` property. 

This wrong selection causes for components that require internet access to be deployed into a subnet without any internet connectivity.

**Comment by peterwoodworth** [comment]
Hey @encron, thanks for reporting this issue.

I understand why there's confusion here. The name seems to imply that it does check for a NAT route, but this isn't the case. Read the description of [this pr](https://github.com/aws/aws-cdk/pull/16348) for more context behind the naming convention.

**Comment by njlynch** [comment]
EC2 doesn't actually have a distinction between a `PRIVATE_ISOLATED` and `PRIVATE_WITH_NAT` subnet; this is a CDK-created concept and as such, there's not a single flag on the subnet itself to determine the correct answer.

I think what we'd need to do is introduce a `describeNatGateways` call to this lookup, and determine if a NAT exists inside the subnet or not. We welcome community contributions! If you are able, we encourage you to [contribute](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md).
