### ISSUE TITLE
(codepipeline): conditional stage

### ISSUE THREAD

**Issue by rantoniuk** [aws/aws-cdk#17042]
### Description

Support CloudFormation conditions in aws-codepipeline.

### Use Case

There is a pipeline consisting of multiple stages aka environments, e.g. TEST -> LOAD -> PROD.
I would like to be able to by default deploy to all those ENVs but from occasionally to skip deploying to one of the environments, e.g. TEST -> LOAD (skipped) -> PROD.

### Proposed Solution

As described here, it seems that CloudFormation [supports conditional stages](https://stackoverflow.com/questions/65106790/how-can-i-skip-a-codepipeline-stage).

How the condition can be added in CDK? Should this be via the Variable mechanism or this is not supported yet?

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by straygar** [comment]
Not sure if reviving a dead thread is the best, but it should be now possible with the new [ability for pipeline variables to control whether to enter a stage or not](https://docs.aws.amazon.com/codepipeline/latest/userguide/rule-reference-VariableCheck.html).
