### ISSUE TITLE
(aws-lambda-python): standard pattern for Lambda unit tests

### ISSUE THREAD

**Issue by SamStephens** [aws/aws-cdk#17048]
### Description

It'd be great to have official guidance/patterns as to how to do unit tests of the code a Python lambda contains. I've failed to find any official guidance for either aws-lambda-python or aws-lambda in general. It's hard to find bloggers who have solved this challenge also.

### Use Case

So I can solve this problem in a standard way other CDK developers will know how to work with. So that the CDK has parity with other frameworks that make unit testing Lambda code easy.

### Proposed Solution

An example application in an examples repository with a link from the documentation.

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by nija-at** [comment]
As mentioned above, unit testing Python lambda handler code is like unit testing any python code. 
`pytest` would probably be my go to, but I don't regularly work on Python and so someone with more Python experience may point to better tools.

**Comment by SamStephens** [comment]
There's a lot more to unit testing Python lambda handler code than choosing `pytest` as the framework. Here are just a few of the decisions and challenges needed to get to the point where you are able to run a single command and unit test your Lambdas, as you need really as part of a build pipeline, or whatever CI/CD you're doing:

* Generally a Python lambda is simply a collection of *.py files. However (unless there's something I'm missing) pytest requires the code it is testing to be installed as a module using `pip install`, with a `setup.py` file etc.
  *  Do you have a setup.py file for each Lambda function, treating each as a completely standalone package?
  * Or do you have a single setup.py file for all your Lambdas, treating each lambda as a module within a single package for all your Lambdas?
* How do you deal with installing dependencies from requirements.txt?
* How do you deal with Lambdas that receive their dependencies from Lambda Layers?
* How do you actually layout the folder structure for your Lambdas and associated unit tests?
* How does your script iterate through each Lambda to test?
* How do you unit test code that is in Lambda Layers, not Lambda Functions?
* Do you use Docker to ensure unit tests are run in a clean room environment?

Once you look at this problem in more detail, it's not at all simple. I've put together a framework for unit testing my CDK python Lambdas, but it's not robust enough I'd share it as any kind of best practice.

This is why I am requesting a standard pattern. At the moment, anyone who wants to unit test their Python Lambdas with the CDK has to solve these non-trivial problems. I suspect there's people who are not unit testing their CDK Python Lambdas who would be if there was standard guidance for them to draw upon.

It'd be nice if one person solved this problem well, rather than every CDK Python Lambda development team solving this problem poorly, or not at all.

**Comment by nija-at** [comment]
Thanks for the detailed explanation @SamStephens.

All of these are valid considerations and solving this in a single effort would be very valuable to Python users.

However, none of these seem specific to the AWS CDK. This will apply to any Python project that is modeling Lambda handlers. So this might be the wrong forum for this.

If you feel passionately about solving this problem, there are a couple of options.
The AWS SAM team might be interested in supporting such a use case - https://github.com/aws/serverless-application-model.
Alternatively, if you put together a Github project or a set of instructions on how to achieve these, we'll happily link to them from our READMEs for other Python customers to benefit from.
