### ISSUE TITLE
Quicksight CfnDataSource - mandatory parameters

### ISSUE THREAD

**Issue by stuartgraham** [aws/aws-cdk#17057]
### link to reference doc page

https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_quicksight/CfnDataSource.html#

### Describe your issue?

Based on 1.128.0 testing, the following parameters are mandatory, not optional:
- aws_account_id
- data_source_id
- type

**Comment by peterwoodworth** [comment]
They're aware of the issue and it's in their backlog to address, the ticket I opened has been resolved
