### ISSUE TITLE
(pipelines): CodePipeline modern api - control over underlying resources

### ISSUE THREAD

**Issue by federicobarera** [aws/aws-cdk#17058]
### Description

In the constructor properties of modern `@aws-cdk/pipelines` CodePipeline, allow more control over associated artifacts buckets, crossRegion artifact buckets, and code build configurations.

Providing the underlying pipeline object as here (https://github.com/aws/aws-cdk/pull/10148/files) is cumbersome.

### Use Case

When creating and deleting multiple cross region pipelines a day, on deletion, artifacts and cross region supports s3 buckets are not automatically removed, quickly reaching maximum allowed number of s3 buckets per account.

Associated (self mutate, artifacts upload) codebuild logs are also not removed adding to cost and management overhead.

### Proposed Solution

Allow passing artifact bucket and cross region artifact buckets to constructor properties, so to allow the creation of a self removal bucket.
Allow passing codebuild project configuration inside of `codeBuildDefaults`, `assetPublishingCodeBuildDefaults` and `selfMutationCodeBuildDefaults` to modify log policies

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by rix0rrr** [comment]
> Providing the underlying pipeline object as here (https://github.com/aws/aws-cdk/pull/10148/files) is cumbersome.

Nevertheless, this is how it's intended to work.
