### ISSUE TITLE
(aws-frauddetector): Documented field "defaultValue" requirement does not match actual requirement

### ISSUE THREAD

**Issue by sekrupke** [aws/aws-cdk#17073]
### link to reference doc page

http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-frauddetector-detector-eventvariable.html#cfn-frauddetector-detector-eventvariable-defaultvalue

### Describe your issue?

The documentation of the Fraud Detector (CfnDetector) says that the field "defaultValue" of a EventVariable is **not** required:
![requirement_doc](https://user-images.githubusercontent.com/85117378/138098036-81f0ef71-3a87-4a6e-8369-a6ea51c0d046.png)

Anyway, creating the Event Variables **without** "defaultValue" set via AWS CDK (aws-frauddetector) shows an validation error:
`
14:50:30 | CREATE_FAILED        | AWS::FraudDetector::Detector | FraudDetector
Missing required parameter in input: "defaultValue"" (RequestToken: xxx, HandlerErrorCode: InternalFailure)
`

I assume that the documentation may be false here.

**Comment by peterwoodworth** [comment]
Thanks again for reporting this @sekrupke,

They have this item in their backlog to address. There's no need to track it here anymore so I'll be closing it out. Hope they get to it soon!
