### ISSUE TITLE
pipelines.CodeBuildStep: Support role parameter in underlying aws_codepipeline_actions.CodeBuildAction call

### ISSUE THREAD

**Issue by anorth848** [aws/aws-cdk#17077]
### Description

The default behavior of `aws_codepipeline_actions.CodeBuildAction` when you do not pass in parameter `role` is `Default: a new Role will be generated`. This parameter is not exposed through pipelines.CodeBuildStep, so a new role is created for CodePipeline to assume in order to execute each action added to the pipeline. This is leading to many roles being created and a very verbose cloudformation template. Template size limits and policy length limits are easily reached. 

### Use Case

To avoid hitting policy and template size limits, and reduce the number of roles being created. Should be able to create one action role for the CodePipeline role to assume and then assign it for every action.

### Proposed Solution

Add additional parameters to [CodeBuildStep](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/pipelines/lib/codepipeline/codebuild-step.ts#L90) and [_codebuild-factory](https://github.com/aws/aws-cdk/blob/403d3ce3bc0f4e30e9694e5c20743f0032009464/packages/%40aws-cdk/pipelines/lib/codepipeline/_codebuild-factory.ts#L304) to be passed to underlying API

Call it with some parameter like `action_role`
```
pipelines.CodeBuildStep(
  id='PreProdBuildStep1',
  project_name='Integ1',
  input=pipeline.cloud_assembly_file_set,
  commands=[
    'pip install -r requirements.txt',
    'pytest integtests',
  ],
  role=cb_role,  #  This is the role code build assumes when it runs
  action_role=a_role #  This is the new role code pipeline assumes to execute the action 
)
```

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by rix0rrr** [comment]
I'd like to get more into the actual use case, and see if we can't address it in a better way than just adding new "tweak this tweak that" properties all over the place. 

What does your pipeline do, what kind of roles are you seeing too many of, how exactly do you propose to use this new property once it exists to solve your problem?
