### ISSUE TITLE
(aws-amplify): make customHeaders configurable.

### ISSUE THREAD

**Issue by hedrall** [aws/aws-cdk#17084]
### Description

Configuring customHeaders in Amplify is possible in CloudFormation, but not yet supported in the construct library.

> CF: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-amplify-app.html#cfn-amplify-app-customheaders

### Use Case

Configure custom headers of application. (ex: security headers). We also can configure with `customHeaders.yml` file on root directory of git repository, but in this case, we cannot switch easily for each environments.

### Proposed Solution

Make configurable in App construct class.

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by ayush987goyal** [comment]
@skinny85 @ryparker Is it okay to take a dependency on [`js-yaml`](https://www.npmjs.com/package/js-yaml) package to add this feature with better customer experience? Currently the CFN spec for amplify app only allows a string to be passed for custom headers and that can get pretty cumbersome for customers to pass as string ([ref](https://docs.aws.amazon.com/amplify/latest/userguide/custom-headers.html))

Eg: `"customHeaders:\n- pattern: '**/*'\n  headers:\n  - key: 'foo'\n    value: 'updated'\n"`

If we use the above package, we can provide a better API for the customer that accepts an array of objects with the required details.
