### ISSUE TITLE
(rds): set allocatedStorage with DatabaseInstanceReadReplica

### ISSUE THREAD

**Issue by peterwoodworth** [aws/aws-cdk#17083]
### Description

When setting `iops` on a `DatabaseInstanceReadReplica`, there should be an easy way to also set `allocatedStorage` so that we can avoid CloudFormation deploy-time error 

> You must specify both the storage size and iops when modifying the storage size or iops on a DB instance that has iops. 

Currently the only way to set storage size is with escape hatches

### Use Case

See #16934 for full details

### Proposed Solution

CDK should feature a synth-time check for both values in addition to supporting the `allocatedStorage` prop with either an error message or warning. The deploy time necessary to debug this issue is frustratingly long

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by npvisual** [comment]
Seeing the same issue as described in #16934. Also validated the suggested [fix](https://github.com/aws/aws-cdk/issues/16934#issuecomment-948062070) (in python however) and was able to deploy the replica without that error message.
