### ISSUE TITLE
(ssm): can not import parameter name from another stack

### ISSUE THREAD

**Issue by mariusingjer** [aws/aws-cdk#17094]
### What is the problem?

cdk generates input parameters in a stack when importing parameter store values.

### Reproduction Steps

```ts
    configSqs = (scope: cdk.Construct) =>
        ssm.StringParameter.fromStringParameterAttributes(
            scope,
            'import-sqs-string-param',
            {
                simpleName: true,
                parameterName: cdk.Fn.importValue('some-exported-value-holding-the-param-name'),
            }
        );

        const sqsConfig = configSqs(this);
        sqsConfig.grantRead(this.ingestLambda);

```

This renders perfectly in terms of IAM:

```json
            {
              "Action": [
                "ssm:DescribeParameters",
                "ssm:GetParameters",
                "ssm:GetParameter",
                "ssm:GetParameterHistory"
              ],
              "Effect": "Allow",
              "Resource": {
                "Fn::Join": [
                  "",
                  [
                    "arn:",
                    {
                      "Ref": "AWS::Partition"
                    },
                    ":ssm:eu-west-1:123456789012:parameter/",
                    {
                      "Fn::ImportValue": "some-exported-value-holding-the-param-name"
                    }
                  ]
                ]
              }
            }
```

But i also generates a parameter construct in the stack (I have no idea why):

```json
  "Parameters": {
    "importsqsstringparamParameter": {
      "Type": "AWS::SSM::Parameter::Value<String>",
      "Default": {
        "Fn::ImportValue": "some-exported-value-holding-the-param-name"
      }
    },
```

### What did you expect to happen?

CDK not to create input parameters on the CF-stack, Why does it create an input parameter to the cloudformation stack?

PS

I know you can explicity reference the parameter cross stack, but then you get into the automagically creation of exports problem

### What actually happened?

CDK creates input parameters on the CF-stack which breaks when deploying with: "Template format error: Every Default member must be a string".

### CDK CLI Version

1.124.0

### Node.js Version

12

### OS

ubuntu

### Language

Typescript

**Comment by toby-lego** [comment]
This is also causing problems when trying to use the output of "CfnMapping.findInMap" as the parameter name

**Comment by amcappelli** [comment]
I am also running into this issue, using cdk v2.44.0. Would really appreciate a fix!

**Comment by tmokmss** [comment]
I also encountered the same error on a different situation (code below).
I suspect if `parameterName` contains any token, it always results in the same error.

```ts
    const keyPair = new ec2.CfnKeyPair(this, 'KeyPair', {
      keyName: 'someKey',
    });
    const privateKey = ssm.StringParameter.fromStringParameterAttributes(
      this,
      'KeyParam',
      {
        parameterName: `/ec2/keypair/${keyPair.attrKeyPairId}`,
        simpleName: false,
      }
    );
// this will result in the error:
//     ValidationError: Template format error: Every Default member must be a string
```

**Comment by StackTrac3** [comment]
I had this issue when I was using `fromStringParameterAttributes` instead of `fromSecureStringParameterAttributes` for a Secure String.
