### ISSUE TITLE
(ecs_patterns): Ability to set entrypoint and command within ApplicationLoadBalancedFargateServiceProps 

### ISSUE THREAD

**Issue by danw-mpl** [aws/aws-cdk#17092]
### Description

I'd like to set the entrypoint and command with `ApplicationLoadBalancedFargateServiceProps `.

### Use Case

To avoid having to do this:

```typescript
const cfnTaskDef = fargateService.taskDefinition.node.defaultChild as ecs.CfnTaskDefinition;
cfnTaskDef.addOverride('Properties.ContainerDefinitions.0.EntryPoint', ['/custom_entrypoint.sh'])
```

### Proposed Solution

Expose entrypoint and command on  `ApplicationLoadBalancedFargateServiceProps `.

```typescript
const fargateService = new ecs_patterns.ApplicationLoadBalancedFargateService(this, 'FargateService', {
    entrypoint: ["my_entrypoint.sh"],
    command: ["command"]
}
```

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by ryparker** [comment]
Hey @danw-mpl 👋🏻 

Thanks for opening this feature request. I understand that using escape hatches is not ideal.

I'm labeling this as p2 which means that we are unable to work on this immediately. We use +1s to help us prioritize our work, and as always we are happy to take contributions if anyone is interested to pick this up and submit a PR (please make sure to follow our [contribution guidelines](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md).)
🙏
