### ISSUE TITLE
@aws-cdk/aws-cloudwatch: addWidgets not working

### ISSUE THREAD

**Issue by adriangabardo** [aws/aws-cdk#17109]
### What is the problem?

I believe `Dashboard.addWidgets()` is not working as intended. When I do `new Dashboard({ widgets: [...] })` any widgets inside that array are created. When I created a `const dashboard = new Dashboard({})` and `dashboard.addWidgets(...widgets)` the dashboard is deployed with an empty `widgets` array.

I have found this behaviour in every scenario I tried: 
* Simple `TextWidget` or more complex `GraphWidget` and `AlarmWidget`
* Within the same stack
* Referenced by separate stacks

### Reproduction Steps

Create an empty dashboard with `widgets: []` in the props. Then reference the dashboard and call `addWidgets()`.

### What did you expect to happen?

The widgets inserted via `addWidgets()` would appear on deployed dashboard.

### What actually happened?

The dashboard on the AWS GUI is empty. Looking at its sources, `widgets` was empty as `[]`

### CDK CLI Version

`1.127.0 (build 0ea309a)`

### Node.js Version

`v14.16.1`

### OS

Windows 10

### Language

Typescript

### Language Version

`Version 4.4.3`

### Other information

`"@aws-cdk/aws-cloudwatch": "1.122.0",`

**Comment by madeline-k** [comment]
Hello @adriangabardo , I tried what you've described here, and I'm not able to reproduce this issue. Can you please share your cdk app code and the synthesized Cloudformation template for your stack?
