### ISSUE TITLE
FargateTaskDefinition: UDP PortMapping not working as intended due to non-matching cases used for Python and Javascript Protocol Enums. 

### ISSUE THREAD

**Issue by peterhessey** [aws/aws-cdk#17115]
### What is the problem?

When attempting to set up a Fargate service from a Docker image that exposes and receives traffic on a single UDP port, adding a target to the load balancer listener fails (i.e. calling `service.load_balancer_target()`). This is as the `PortMapping` defined for the container's UDP port is not recognised as a valid `PortMapping` when calling that function. As far as we can tell, this is due to the python `Protocol` Enum defining UDP as `"udp"` but in the Javascript it is defined as `"UDP"`. TCP does not throw the same error as it is the default protocol.

### Reproduction Steps

Given the following CDK project:

```
.
├── app.py
├── cdk.json
├── Dockerfile
└── udp_server.py
```

 `app.py` specifies a stack that loads a docker image `udp-test` and attempts to create a Fargate service using it, along with the appropriate resources (Network Load Balancer, Listeners, etc.) needed to expose the UDP port to the internet:

```

from aws_cdk import core as cdk
from aws_cdk.aws_elasticloadbalancingv2 import NetworkLoadBalancer
from aws_cdk.aws_ecs import (
    ContainerImage, FargateTaskDefinition, FargateService, Cluster, PortMapping, Protocol, LogDrivers
)
from aws_cdk.aws_ec2 import (
    SubnetConfiguration, SubnetSelection, SubnetType, Vpc, Port
)
from pathlib import Path
app = cdk.App()


class MainTaskDefinition(FargateTaskDefinition):
    def __init__(
        self,
        scope: cdk.Construct,
        id: str,
        **kwargs
    ):
        super().__init__(scope, id, **kwargs)
        self.add_container(
            "MainContainer",
            image=ContainerImage.from_registry("udp-test"),
            logging=LogDrivers.aws_logs(stream_prefix="ecs"),
            port_mappings=[  # this port mapping is the one not recognised
                PortMapping(protocol=Protocol.UDP, container_port=7700),
            ],
        )


class MainInstance(cdk.Construct):
    def __init__(
        self, scope: cdk.Construct,
        id: str,
        **kwargs
    ):
        super().__init__(scope, id, **kwargs)

        self.vpc = Vpc(
            self, "Vpc",
            subnet_configuration=[
                SubnetConfiguration(
                    name="FargateCluster",
                    subnet_type=SubnetType.PRIVATE,
                ),
                SubnetConfiguration(
                    name="LoadBalancer",
                    subnet_type=SubnetType.PUBLIC,
                ),
            ],
            max_azs=1,
        )

        self.cluster = Cluster(
            self, "Cluster",
            vpc=self.vpc
        )

        self.task_definition = MainTaskDefinition(
            self, "TaskDefinition",
        )

        self.service = FargateService(
            self, "Service",
            cluster=self.cluster,
            task_definition=self.task_definition,
            vpc_subnets=SubnetSelection(
                subnets=self.vpc.select_subnets(subnet_group_name="FargateCluster",).subnets
            )
        )

        self.service.connections.allow_from_any_ipv4(Port.udp(7700))

        self.load_balancer = NetworkLoadBalancer(
            self, "LoadBalancer",
            vpc=self.vpc,
            internet_facing=True,
            cross_zone_enabled=True,
        )
        self.listener = self.load_balancer.add_listener(
            "Listener",
            protocol=Protocol.UDP, 
            port=7700,
        )

        self.target_group = self.listener.add_targets(
            "TargetGroup",
            targets=[
                self.service.load_balancer_target(  # this function throws the error
                    container_name="MainContainer",
                    protocol=Protocol.UDP,  # changes the error but doesn't fix it
                ),
            ],
            protocol=Protocol.UDP,
            port=7700,
        )


class MainStack(cdk.Stack):
    def __init__(self, scope: cdk.Construct, id: str, **kwargs):
        super().__init__(scope, id, **kwargs)

        self.ecs_instance = MainInstance(
            self,
            'MainInstance',
        )

MainStack(app, "Main")

if __name__ == "__main__":
    app.synth()
```

An example Dockerfile is given below (however any valid Dockerfile would suffice):

```
FROM python:3

COPY udp_server.py udp_server.py

EXPOSE 7700/udp

CMD ["python", "./udp_server.py"]
```

Where `udp_server.py` contains the following code for setting up a UDP socket:

```
import socket
UDP_PORT = 7700

sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
sock.bind(("", UDP_PORT))

while True:
    msg, address = sock.recvfrom(1024)
    print(msg)

```

To trigger the error, ensure npm, CDK and Docker are all set up correctly. Then, add all the above files to the same working directory. Next, call `docker build -t udp-test .` to add the Docker image to the registry. Then call `cdk synth`. 

### What did you expect to happen?

We expected valid CloudFormation to be produced, suitable for deploying a Fargate service to AWS.

### What actually happened?

The following error occurs:

```
jsii.errors.JSIIError: Container 'MainStack/MainInstance/TaskDefinition/MainContainer' has no mapping for port 7700 and protocol UDP. Did you call "container.addPortMappings()"?
```

Despite the fact that the port mapping is clearly defined in the task definition.

### CDK CLI Version

1.128.0 (build 1d3883a)

### Node.js Version

v16.10.0

### OS

WSL Ubuntu 20.04

### Language

Python

### Language Version

Python 3.8.10

### Other information

As mentioned in the title and introductory paragraph, we believe this problem is caused by non-matching Enums for the `Protocol` class in Python and Javascript.  

In the `/home/$USER/.local/share/virtualenvs/<venv_id>/lib/python3.8/site-packages/aws_cdk/aws_ecs/__init__.py` file,  the Protocol Class is defined as follows:

```
@jsii.enum(jsii_type="@aws-cdk/aws-ecs.Protocol")
class Protocol(enum.Enum):
    '''Network protocol.'''
    TCP = "TCP"
    '''TCP.'''
    UDP = "UDP"
    '''UDP.'''

```

Whereas in the file `container_definition.js` (located in our virtual env at `/home/$USER/.local/share/virtualenvs/<venv_id>/lib/python3.8/site-packages/aws_cdk/aws_ecs/_jsii/package/lib/container-definition.js`, after uncompressing the .`tgz` file containing the JavaScript files), the `Protocol` object is defined like so:

```
var Protocol;
(function (Protocol) {
    Protocol["TCP"] = "tcp";
    Protocol["UDP"] = "udp";
}
```

This causes the function `findPortMapping()` (located in the same file) to fail:

```
    findPortMapping(containerPort, protocol) {
        for (const portMapping of this.portMappings) {
            const p = portMapping.protocol || Protocol.TCP;
            const c = portMapping.containerPort;
            if (c === containerPort && p === protocol) {
                return portMapping;
            }
        }
        return undefined;
    }
```
as `protocol` is assigned the value `"UDP"` but `p` is assigned the value `"udp"`, and causes the function to return `undefined` and trigger this error in the `_validateTarget()` function in `task-definition.js` (located for us at ` /home/$USER/.local/share/virtualenvs/<venv_id>/lib/python3.8/site-packages/aws_cdk/aws_ecs/_jsii/package/lib/base/task-definition.js`.

To bypass this error we manually changed the definition of the Javascript Enum to be upper-case. However this could potentially cause errors with other language interfaces in the future so is likely not a suitable fix for a permanent solution.

**Comment by rix0rrr** [comment]
`UDP = "UDP"` might actually be correct.

Enums are supposed to be serialized like this: `@aws-cdk/aws-ecs.Protocol/UDP`, according to https://aws.github.io/jsii/specification/2-type-system/#enum-serialization

If you run `env JSII_DEBUG=1 cdk synth` you should see a giant amount of tracing printed. Can you suss out whether the enum value is being serialized properly or not? If you cannot, please paste the log somewhere I can find it.

But looking at this code, I think the issue might actually be around here:

![2021-11-22 at 15 08](https://user-images.githubusercontent.com/524162/142875932-e4a42ee3-7f8c-44d6-b917-0263247fbfbc.png)

I'm thinking some of these are supposed to be `elbv2.Protocol`s instead of `ecs.Protocol`s... ?

**Comment by rix0rrr** [comment]
It might actually not matter
