### ISSUE TITLE
(aws-aps): Created Workspace does not have stack-level tags with the prefix aws:

### ISSUE THREAD

**Issue by Kirchen99** [aws/aws-cdk#17139]
### What is the problem?

We create Amazon Prometheus Workspace using aws-cdk. We expect to see a workspace created with stack-level tags with the prefix `aws:`. But we see a workspace created without `aws:` tags instead.

I think this is a bug because In this [docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-resource-tags.html) it is described that CloudFormation automatically creates the following stack-level tags with the prefix `aws:`:

- aws:cloudformation:logical-id
- aws:cloudformation:stack-id
- aws:cloudformation:stack-name

And all stack-level tags, including automatically created tags, are propagated to resources that CloudFormation supports.

### Reproduction Steps

Create a Cloudformation Stack with an Amazon Prometheus Workspace:

```
import * as cdk from '@aws-cdk/core';
import { CfnWorkspace } from '@aws-cdk/aws-aps';

export class HelloCdkStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);
    this.createWorkspace()
  }
  
  private createWorkspace(): void {
      const aliasName = `alias-name`
      new CfnWorkspace(this, `SomeWorkspace`, {
          alias: aliasName
      })
  }
  
}
```

### What did you expect to happen?

A workspace created with stack-level tags with the prefix `aws:`

```
aws:cloudformation:logical-id

aws:cloudformation:stack-id

aws:cloudformation:stack-name

```

### What actually happened?

A workspace created without `aws:` tags.

### CDK CLI Version

1.129.0

### Node.js Version

v16.8.0

### OS

macOS 11.6

### Language

Typescript

**Comment by madeline-k** [comment]
Thanks for opening this issue, @Kirchen99! I am pretty sure this is a Cloudformation issue, so I've opened up an issue over there: https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/985.
