### ISSUE TITLE
(cdk documentation): typescript documentation gone with new release

### ISSUE THREAD

**Issue by Demli** [aws/aws-cdk#17136]
### link to reference doc page

https://github.com/aws/aws-cdk/releases

### Describe your issue?

the typescript documentations seems to be missing in the new release.
Was this intended?
It also can´t be found on the official website: https://docs.aws.amazon.com/cdk/api/latest/docs/aws-construct-library.html

**Comment by guidobit** [comment]
@peterwoodworth I used to be able to search for 'DomainName' and the left pane would be filtered for all the resources containing that search query. It would show me instantly that there is the concept of DomainName in both @aws-cdk/aws-apigatewayv and @aws-cdk/aws-apigatewayv2. This was part of the Typescript documentation. Removing the Typescript documentation has removed this search functionality.

**Comment by peterwoodworth** [comment]
Thanks for the feedback, that is unfortunate to lose. Please make sure to give the feature request to make this part of the API ref a thumbs up - I'd love to have this functionality as well. https://github.com/aws/aws-cdk/issues/5634
