### ISSUE TITLE
(HelmChart): "Response object is too long" when adding additional values

### ISSUE THREAD

**Issue by floknip** [aws/aws-cdk#17137]
### What is the problem?

I'm using the `HelmChart` construct to deploy a chart to eks.

```TS
const helmChart = new HelmChart(this, `${serviceName}HelmChart`, {
          repository: "<linkToPubicHelmChart>",
          chart: "theName",
          version: "theVersion", 
          release: releaseName,
          cluster: props.cluster,
          namespace: "theNamespace",
          createNamespace: true, 
          values,
        });
```

extending the values object by adding new entries causes the helmchart construct to fail on `cdk deploy` with "Response object is too long". (cdk diff work and recognizes the change in the values object)

### Reproduction Steps

The problem occurs during the deployment after adding new entries to the values object at state where the chart with the previous values is already deployed.

**IMPORTANT NOTE**: Deployment with the new values runs through if I destroy the stack in advance and redeploy. (not an acceptable scenario for production)

### What did you expect to happen?

Stack should deploy and implement just the additional defined values to the existing deployment

### What actually happened?

This error: Response object is too long

```sh
08:30:53 | UPDATE_FAILED        | Custom::AWSCDK-EKS-HelmChart         | xxxchart129HelmChart8AB82367
Response object is too long.

        new CustomResource (/Users/user/github/yyy/tmp3/ccc/deployment/cdk/node_modules/@aws-cdk/core/lib/custom-resource.ts:36:21)
        \_ new HelmChart (/Users/user/github/yyyy/tmp3/cccs/deployment/cdk/node_modules/@aws-cdk/aws-eks/lib/helm-chart.ts:69:5)
        \_ new xxxHelmStack (/Users/user/github/yyy/tmp3/ccc/deployment/cdk/src/stacks/xxx/sn-platform/xxx-helm-stack.ts:191:31)
        \_ Object.<anonymous> (/Users/user/github/yyy/tmp3/cccc/deployment/cdk/src/bin/xxx-deployment.ts:96:25)
        \_ Module._compile (internal/modules/cjs/loader.js:1137:30)
        \_ Module.m._compile (/Users/user/github/yyy/tmp3/ccc/deployment/cdk/node_modules/ts-node/src/index.ts:1056:23)
        \_ Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
        \_ Object.require.extensions.<computed> [as .ts] (/Users/user/github/yyy/tmp3/cccc/deployment/cdk/node_modules/ts-node/src/index.ts:1059:
12)
        \_ Module.load (internal/modules/cjs/loader.js:985:32)
        \_ Function.Module._load (internal/modules/cjs/loader.js:878:14)
        \_ Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
        \_ main (/Users/user/github/yyy/tmp3/ccc/deployment/cdk/node_modules/ts-node/src/bin.ts:198:14)
        \_ Object.<anonymous> (/Users/user/github/yyy/tmp3/ccc/deployment/cdk/node_modules/ts-node/src/bin.ts:288:3)
        \_ Module._compile (internal/modules/cjs/loader.js:1137:30)
        \_ Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
        \_ Module.load (internal/modules/cjs/loader.js:985:32)
        \_ Function.Module._load (internal/modules/cjs/loader.js:878:14)
        \_ Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
        \_ /Users/user/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/libnpx/index.js:268:14


 ❌ xxxHelmStackchart129 failed: Error: The stack named xxxHelmStackchart129 failed to deploy: UPDATE_ROLLBACK_COMPLETE
    at Object.waitForStackDeploy (/Users/user/.nvm/versions/node/v12.18.3/lib/node_modules/aws-cdk/lib/api/util/cloudformation.ts:307:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at prepareAndExecuteChangeSet (/Users/user/.nvm/versions/node/v12.18.3/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:352:26)
    at CdkToolkit.deploy (/Users/user/.nvm/versions/node/v12.18.3/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:189:24)
    at initCommandLine (/Users/user/.nvm/versions/node/v12.18.3/lib/node_modules/aws-cdk/bin/cdk.ts:225:9)
The stack named xxxHelmStackchart129 failed to deploy: UPDATE_ROLLBACK_COMPLETE
```

### CDK CLI Version

1.128.0 

### Node.js Version

12.18.3

### OS

MacOs BigSur 11.6

### Language

Typescript

### Language Version

4.4.4

### Other information

Tried to increase memory for kubectl. --> no effect

```ts
const cluster = new Cluster(this, `${serviceName}Cluster`, {
        ....
        kubectlMemory: Size.gibibytes(4),
    });

```

**Comment by otaviomacedo** [comment]
The problem here is that CloudFormation imposes a limit of 4096 bytes to responses coming from custom resources. In this case, it seems that the call is returning an error whose message exceeds this limit. The custom resource then embeds that message into and error and throws it:

https://github.com/aws/aws-cdk/blob/82dd2822a86431d0aa0be896550d421810b80c67/packages/@aws-cdk/aws-eks/lib/kubectl-handler/helm/__init__.py#L98-L99

We need to understand what error is being thrown in this case and how can we shorten the output message. One approach is to implement something similar to what was done in the `AwsCustomResource`, in which it filters specific paths of the output. Another, more blunt solution, is to simply truncate the response at the 4096th byte.

**Comment by djtje12** [comment]
This is happening quite often lately when deploying the kube-prometheus-stack helm chart ([is related to the following bug](https://github.com/prometheus-community/helm-charts/issues/1041)).
[Output when you run it locally](https://pastebin.com/uzvjx5tm).
