### ISSUE TITLE
ec2: Add a bastion host construct

### ISSUE THREAD

**Issue by rix0rrr** [aws/aws-cdk#1713]
Bastion hosts are a typical requirement for everyone that run EC2 capacity in a private subnet (but still want to SSH into their hosts).

We can probably make a great and seamless experience for them.

A good start: https://docs.aws.amazon.com/quickstart/latest/linux-bastion/welcome.html

**Comment by hoegertn** [comment]
@rix0rrr is this still of interest? I am building this within the next days and could create a PR here instead of putting it into my construct library.

**Comment by eladb** [comment]
Sure!
