### ISSUE TITLE
(neptune): Instances cannot be added to Aurora Serverless clusters

### ISSUE THREAD

**Issue by revmischa** [aws/aws-cdk#17145]
### What is the problem?

```
Instances cannot be added to Aurora Serverless clusters. (Service: AmazonNeptune; Status Code: 400; Error Code: InvalidParameterValue; Request ID: 61eb5973-c14e-4e16-883d-dc706225a4bd; Proxy: null)
--
```

### Reproduction Steps

```ts
new DatabaseCluster(this, 'NDB', {
        vpc,
        instanceType: InstanceType.T3_MEDIUM,
        dbClusterName: `foo`,
        iamAuthentication: true,
})
```

### What did you expect to happen?

Create DB cluster

### What actually happened?

The above error

### CDK CLI Version

1.127.0 (build 0ea309a)

### Node.js Version

14

### OS

macOS

### Language

Typescript

**Comment by njlynch** [comment]
I have not been able to reproduce this with the sample given. It is a bit odd that the error message refers to Aurora Serverless (RDS) but the service message says Neptune. Which service were you using when you gave the above error?

For comparison, here is how I attempted to reproduce:

```ts
import { RemovalPolicy, Stack, StackProps, aws_ec2 as ec2 } from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as neptune from '@aws-cdk/aws-neptune-alpha';

export class Issue17145Stack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);

    const vpc = ec2.Vpc.fromLookup(this, 'VPC', { /* ... */ });

    new neptune.DatabaseCluster(this, 'NDB', {
      vpc,
      instanceType: neptune.InstanceType.T3_MEDIUM,
      dbClusterName: `foo`,
      iamAuthentication: true,
      removalPolicy: RemovalPolicy.DESTROY,
    });
  }
}
```

The above built successfully without error. Can you share a reproducible sample, or correct what I'm missing above?

**Comment by revmischa** [comment]
I don't know what's wrong, sorry, not getting this anymore
