### ISSUE TITLE
(aws-cloudfront): Using Distribution construct OAI is not associated from S3Origin

### ISSUE THREAD

**Issue by AbendGithub** [aws/aws-cdk#17153]
### What is the problem?

Trying to implement a Cloudfront distribution to access a private website bucket. Using `Distribution` construct with `S3Origin` is not associating the distribution with the OAI. This makes impossible to access the private bucket.

### Reproduction Steps

Using this code:

```Typescript
       const bucket = new S3.Bucket(this, `${PREFIX}${props.stage}LandingPageBucket`, {
            bucketName: `${PREFIX}-${props.stage}-${LANDING_PAGE_BUCKET_NAME_SUFFIX}`.toLowerCase(),
            websiteIndexDocument: "index.html",
            websiteErrorDocument: '404.html',
            autoDeleteObjects: true,
            publicReadAccess: false,
            blockPublicAccess: S3.BlockPublicAccess.BLOCK_ALL,
            removalPolicy: cdk.RemovalPolicy.DESTROY,
            enforceSSL: true,
        });

        const cloudfrontOAI = new cf.OriginAccessIdentity(this, `${PREFIX}LandingPageCloudfrontOAI`, {
            comment: `Cloudfront OAI for the landing page`
        });

        bucket.grantRead(cloudfrontOAI);

        // Value exported from Global Stack. Ideally HostedZone.fromLookup() method should be used instead but
        // cannot be used until this bug is solved: https://github.com/aws/aws-cdk/issues/4651
        const rootHostedZoneId = cdk.Fn.importValue('RootHostedZoneId');

        const rootHostedZone = r53.HostedZone.fromHostedZoneAttributes(this, `${PREFIX}RootHostedZone`, {
            hostedZoneId: rootHostedZoneId,
            zoneName: SITE_DOMAIN
        });

        const certificate = new acm.Certificate(this, `${PREFIX}LandingPageAcmCertificate`, {
            domainName: SITE_DOMAIN,
            subjectAlternativeNames: [`www.${SITE_DOMAIN}`],
            validation: acm.CertificateValidation.fromDns(rootHostedZone)
        });
        
        const distribution = new cf.Distribution(this, `${PREFIX}${props.stage}LandingPageDistribution`, {
            defaultBehavior: {
                origin: new origins.S3Origin(bucket, {
                    originAccessIdentity: cloudfrontOAI
                }),
                viewerProtocolPolicy: cf.ViewerProtocolPolicy.REDIRECT_TO_HTTPS
            },
            domainNames: [SITE_DOMAIN, `www.${SITE_DOMAIN}`],
            certificate: certificate,
            enableLogging: false,
            comment: "Distribution for Vicinia's Landing page",
        });
```

The distribution and the rest of the resources are created just fine, but the OAI is not associated to the Distribution provoking 403 forbidden errors.

Using exactly the same code as above but replacing the `Distribution` construct by `CloudFrontWebDistribution` works just as expected:

```Typescript
        const distribution = new cf.CloudFrontWebDistribution(this, 'Distribution', {
            originConfigs: [{
                behaviors: [{
                    isDefaultBehavior: true,
                    compress: true,
                    viewerProtocolPolicy: ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
                }],
                s3OriginSource: {
                    s3BucketSource: bucket,
                    originAccessIdentity: cloudfrontOAI,
                },
            }],
            viewerCertificate: cf.ViewerCertificate.fromAcmCertificate(
                certificate,
                {
                    aliases: [SITE_DOMAIN, `www.${SITE_DOMAIN}`],
                    securityPolicy: cf.SecurityPolicyProtocol.TLS_V1_2_2021,
                    sslMethod: cf.SSLMethod.SNI,
                },
            ),
            comment: "Distribution for Vicinia's Landing page",
        });
```

### What did you expect to happen?

Distribution is created with the OAI associated.

### What actually happened?

Distribution is created with no OAI associated.

### CDK CLI Version

1.128

### Node.js Version

v14.18.0

### OS

Windows 10

### Language

Typescript

### Language Version

3.9.10

**Comment by marco-streng** [comment]
Same issue here. The origins created with the `Distribution` construct are from type `Custom Origin` instead of type `S3` like with `CloudFrontWebDistribution`

**Comment by claudioc** [comment]
Same here!

**Comment by njlynch** [comment]
The `S3Origin` class treats S3 buckets differently depending on their setup. From [the docs](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-cloudfront-readme.html#from-an-s3-bucket):

> The above will treat the bucket differently based on if IBucket.isWebsite is set or not. If the bucket is configured as a website, the bucket is treated as an HTTP origin, and the built-in S3 redirects and error pages can be used. Otherwise, the bucket is handled as a bucket origin and CloudFront's redirect and error handling will be used. In the latter case, the Origin will create an origin access identity and grant it access to the underlying bucket. This can be used in conjunction with a bucket that is not public to require that your users access your content using CloudFront URLs and not S3 URLs directly.

Slightly translated, if you set up your bucket as a website -- by configuring the `websiteIndexDocument` and/or `websiteErrorDocument` properties -- CloudFront treats the bucket as an HTTP origin, at the URL `http://bucket-name.s3-website-region.amazonaws.com`. This is in line with the guidance from the CloudFront docs (https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/DownloadDistS3AndCustomOrigins.html#concept_S3Origin_website).

In your example, you've set up your bucket to as a website origin, but blocked access to the bucket (via `blockPublicAccess`). So CloudFront is attempting to access the bucket via HTTP (`http://bucket-name.s3-website-region.amazonaws.com`) but getting blocked. With this method of access, the OAI has no effect.

There are two options:

1. Configure the S3 bucket as a non-website bucket origin. Simply remove the `websiteIndexDocument` and `websiteErrorDocument` configurations, and move that configuration to the `Distribution.defaultRootObject` and `Distribution.errorResponses` properties, respectively. This would be my recommendation.

2. Alternatively -- if this approach is acceptable -- you can drop the `blockPublicAccess`, which will allow CloudFront to communicate with the S3 bucket over the HTTP interface.

**Comment by AbendGithub** [comment]
Thanks @njlynch for your response. My question would be, shouldn't `Distribution` construct be able to access private website buckets in the same way as the `CloudFrontWebDistribution` does? 

Both approaches you mentioned have different problems:

> Configure the S3 bucket as a non-website bucket origin. Simply remove the websiteIndexDocument and websiteErrorDocument configurations, and move that configuration to the Distribution.defaultRootObject and Distribution.errorResponses properties, respectively. This would be my recommendation.

In this case I will not be able to get the advantages of having a bucket configured as website.

> Alternatively -- if this approach is acceptable -- you can drop the blockPublicAccess, which will allow CloudFront to communicate with the S3 bucket over the HTTP interface.

If I allow public access my bucket will be exposed to the internet with all the issues it involves.

**Comment by njlynch** [comment]
> In this case I will not be able to get the advantages of having a bucket configured as website.

What advantages are those? What functionality will you miss that can't be replicated with the Distribution properties I mentioned?

**Comment by AbendGithub** [comment]
Redirection support and the ability of accessing the index document directly basically. It abstracts of a normal bucket behavior.

**Comment by njlynch** [comment]
Redirection support is covered by `Distribution.errorResponses` and accessing the index document is covered by `Distribution.defaultRootObject`, as I mentioned above. Try it out and I'm sure you'll find that this functionality is identical to what you're looking for.

**Comment by AbendGithub** [comment]
@njlynch `originAccessIdentity` in `S3Origin` should be deprecated then?

**Comment by njlynch** [comment]
Not at all -- the OAI works great for normal (non-website) bucket setups.

**Comment by rboelen** [comment]
> Redirection support is covered by `Distribution.errorResponses` and accessing the index document is covered by `Distribution.defaultRootObject`, as I mentioned above. Try it out and I'm sure you'll find that this functionality is identical to what you're looking for.

Redirection is only covered on distribution level. If I would have a behaviour with path /assets/* serving images it is not acceptable to just send index.html on 404 status. 
WIth redirection on the bucket this would not be a problem.

We have these behaviours in a distribution:
0 - /assets/* to  s3 bcuket serving images, on 404 do nothing
1 - Default(*) to s3 bucket service static website, on 404 redirect to index.html

With CloudFrontWebDistribution  this worked, with the new Distribution construct not anymore.
