### ISSUE TITLE
aws_kinesisanalytics: Configuring a vpc

### ISSUE THREAD

**Issue by JoeKodsi-Idealworks** [aws/aws-cdk#17159]
### Description

Hey,

I have looked thoroughly through aws cdk documentation but couldn't find any way to configure a Kinesis Data Analytics Application with a VPC.

Is there a way to configure the networking of a Kinesis Data Analytics Application (adding vpc + subnets + security group)?

### Use Case

This feature is needed in our use case to allow access for the Flink java application to access resources within our VPC.
Say we needed to communicate with AmazonMQ that resides in a private subnet, how would our Kinesis Data Analytics Application reach the queue server?

### Proposed Solution

I am not sure how this could be implemented but as an end goal I could see a parameter within the aws_kinesisanalytics.CfnApplicationV2.ApplicationConfigurationProperty Object as such:

networking_configuration_property of type:

```python
aws_kinesisanalytics.CfnApplicationV2.NetworkingConfigurationProperty
```

that accepts the follwing:

```python
vpc:ec2.VPC,
subnets:[ec2.Subnet],
security_group:ec2.SecurityGroup
```

### Other information

I am not certain this is relevant but:
I am using Python: 3.6.8
cdk: 1.129.0 (build fb43f89)
the issue I based my work upon: https://github.com/aws/aws-cdk/issues/12407
The PR that addressed the above issue: https://github.com/aws/aws-cdk/pull/12464

related to the above but on another note:
I found a bug in a generated example under the following construct:

```python
aws_cdk.aws_kinesisanalytics_flink
_# Example automatically generated without compilation. See https://github.com/aws/jsii/issues/826
import aws_cdk.aws_kinesisanalytics_flink as flink

flink_app = flink.Application(self, "Application",
    # ...
    property_groups=PropertyGroups(
        FlinkApplicationProperties={
            "input_stream_name": "my-input-kinesis-stream",
            "output_stream_name": "my-output-kinesis-stream"
        }
    )
)_
```

In Python 'PropertyGroups' is an abstract class that doesn't accept any params:
https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_kinesisanalytics_flink/PropertyGroups.html

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by JoeKodsi-Idealworks** [comment]
Hey @peterwoodworth , hope all is good on your end. Do you have any input for me regarding my last comment?
A simple acknowledgement if this is a bug or not would suffice me to know how to proceed with regards to creating a ```aws-cdk/aws-kinesisanalytics-flink.Application```.

Thanks again and I hope this doesn't turn out to be a waste of time for you!

**Comment by peterwoodworth** [comment]
Hey @JoeKodsi-Idealworks, thanks for reminding me to look at this again

I was able to reproduce what you found - and wasn't able to figure out how to use the PropertyGroups interface in python. I'm not entirely sure if it's a bug, since I don't typically use Python, but it does seem to me like something weird is going on here.

We should document this in a separate issue. I'll do that by the end of today

**Comment by peterwoodworth** [comment]
I've created a new issue for this in the jsii repo, let's see what they say

**Comment by JoeKodsi-Idealworks** [comment]
> 
> 
> I've created a new issue for this in the jsii repo, let's see what they say

Hey @peterwoodworth great to hear! I guess then this feature-request/issue can be closed and one could follow the outcome here: https://github.com/aws/jsii/issues/3154

If you agree, this ticket can be closed when you see fit.

Thanks again for all the support
Cheers!
