### ISSUE TITLE
aws_elasticloadbalancingv2: RedirectConfigProperty using #{host}, #{path} or #{query}

### ISSUE THREAD

**Issue by daknhh** [aws/aws-cdk#17165]
### What is the problem?

When i want to use either  `#{host}`, `#{path}` or `#{query}` in the RedirectConfigProperty the cdk is throwing an exception: 

```
Value did not match any type in union: Value did not match any type in union: Value did not match any type in union: Wire struct type '@aws-cdk/aws-elasticloadbalancingv2.CfnListener.RedirectConfigProperty' does not match expected '@aws-cdk/aws-elasticloadbalancingv2.CfnListenerRule.RedirectConfigProperty', 
Expected object reference, got {"$jsii.struct":{"fqn":"@aws-cdk/aws-elasticloadbalancingv2.CfnListener.RedirectConfigProperty","data":{"statusCode":"HTTP_301","host":"#{host}","path":"#{path}","port":"443","protocol":"HTTPS","query":"#{query}"}}}, 
Expected object reference, got {"$jsii.struct":{"fqn":"@aws-cdk/aws-elasticloadbalancingv2.CfnListenerRule.ActionProperty","data":{"type":"redirect","authenticateCognitoConfig":null,"authenticateOidcConfig":null,"fixedResponseConfig":null,"forwardConfig":null,"order":null,"redirectConfig":{"$jsii.struct":{"fqn":"@aws-cdk/aws-elasticloadbalancingv2.CfnListener.RedirectConfigProperty","data":{"statusCode":"HTTP_301","host":"#{host}","path":"#{path}","port":"443","protocol":"HTTPS","query":"#{query}"}}},"targetGroupArn":null}}}, 
Expected object reference, got [{"$jsii.struct":{"fqn":"@aws-cdk/aws-elasticloadbalancingv2.CfnListenerRule.ActionProperty","data":{"type":"redirect","authenticateCognitoConfig":null,"authenticateOidcConfig":null,"fixedResponseConfig":null,"forwardConfig":null,"order":null,"redirectConfig":{"$jsii.struct":{"fqn":"@aws-cdk/aws-elasticloadbalancingv2.CfnListener.RedirectConfigProperty","data":{"statusCode":"HTTP_301","host":"#{host}","path":"#{path}","port":"443","protocol":"HTTPS","query":"#{query}"}}},"targetGroupArn":null}}}]### 
```

### Reproduction Steps

Use  `#{host}`, `#{path}` or `#{query}` in the RedirectConfigProperty and use this RedirectConfig in CfnListenerRule. 

### What did you expect to happen?

Creation of an RedirectConfigProperty

### What actually happened?

Error

### CDK CLI Version

1.124.0

### Node.js Version

v14.17.6

### OS

macOS 11.6 (20G165)

### Language

Python

### Language Version

Python 3.9

**Comment by njlynch** [comment]
Can you share a reproducible example of the code that triggers this?

Here's a working example:

```python
        cfn_listener = elbv2.CfnListener(self, "MyCfnListener",
                                         default_actions=[
                                           elbv2.CfnListener.ActionProperty(
                                             type="redirect",
                                             redirect_config=elbv2.CfnListener.RedirectConfigProperty(
                                               status_code="200",
                                               host='example.com',
                                               path="/",
                                               query='foo=bar',
                                             ),
                                           )],
                                         load_balancer_arn="loadBalancerArn",
                                         )
```

**Comment by daknhh** [comment]
Sure neither:

`        cfn_listener = elbv2.CfnListener(self, "MyCfnListener",
                                         default_actions=[
                                           elbv2.CfnListener.ActionProperty(
                                             type="redirect",
                                             redirect_config=elbv2.CfnListener.RedirectConfigProperty(
                                               status_code="200",
                                               host="""#{host}""",
                                               path="""#{path}""",,
                                               query="""#{query}""",,
                                             ),
                                           )],
                                         load_balancer_arn="loadBalancerArn",
                                         )
`
nor:

`        cfn_listener = elbv2.CfnListener(self, "MyCfnListener",
                                         default_actions=[
                                           elbv2.CfnListener.ActionProperty(
                                             type="redirect",
                                             redirect_config=elbv2.CfnListener.RedirectConfigProperty(
                                               status_code="200",
                                               host="""#{{host}}""",
                                               path="""#{{path}}""",,
                                               query="""#{{query}}""",,
                                             ),
                                           )],
                                         load_balancer_arn="loadBalancerArn",
                                         )
`
is working

**Comment by peterwoodworth** [comment]
@daknhh why are you using """#{}""" syntax?
