### ISSUE TITLE
(aws-ec2): Extend BastionHostLinux to support CloudFormationInit

### ISSUE THREAD

**Issue by mpvosseller** [aws/aws-cdk#17161]
### Description

It would be helpful if the `BastionHostLinux` constructor accepted optional `CloudFormationInit` and  `ApplyCloudFormationInitOptions` arguments to be passed to the ​underlying `Instance`. This would enable full CloudFormation ​initialization of the instance like installing files.

```typescript
   ​/**
    ​* Apply the given CloudFormation Init configuration to the instance at startup.
    ​*
    ​* @default - no CloudFormation init
    ​* @stability stable
    ​*/
   ​readonly init?: CloudFormationInit;
   ​/**
    ​* Use the given options for applying CloudFormation Init.
    ​*
    ​* Describes the configsets to use and the timeout to wait
    ​*
    ​* @default - default options
    ​* @stability stable
    ​*/
   ​readonly initOptions?: ApplyCloudFormationInitOptions;
```

### Use Case

In my case I want to install files and run a command at initialization time.

### Proposed Solution

Add two optional arguments `init` and `initOptions` to `BastionHostLinuxProps`. In `BastionHostLinux` pass these arguments to the `Instance` constructor when creating the underlying instance.    

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by njlynch** [comment]
Sure, that seems like a reasonable request. We welcome community contributions!

**Comment by jkuek** [comment]
Thanks, looking forward to this change!

**Comment by cmazuc** [comment]
Appreciate the work on this so far, are there plans to support cfn-hup?

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-hup.html

Right now the generated UserData doesn't configure cfn-hup so any updates to the AWS::CloudFormation::Init resource aren't picked up without a host replacement.
