### ISSUE TITLE
(@aws-cdk/pipelines 1.129.0): API: s3:PutPublicAccessBlock Access Denied

### ISSUE THREAD

**Issue by jc1518** [aws/aws-cdk#17177]
### Description

Hello, when I was trying to create a new pipeline via "cdk deploy", I received the error " API: s3:PutPublicAccessBlock Access Denied".  I guess it is for enabling the BlockPublicAcess setting against the new artifact bucket. I am wondering is there a way to choose not to change it? Something similar to the option "--public-access-block-configuration false" in the "cdk bootstrap"?   

### Use Case

Some organizations' policy denies s3:PutPublicAccessBlock.

### Proposed Solution

Add an option, something like "--public-access-block-configuration false"

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by rix0rrr** [comment]
I don't think we're going to add this property. 

In the short term, you could do one of:

* Use escape hatches and/or Aspects to mutate the `CfnBucket` in place.
* Pass in a custom pipeline with custom buckets with the property disabled.

In the long term, this would be covered by something like: https://github.com/aws/aws-cdk-rfcs/issues/25
