### ISSUE TITLE
aws_rds: username is confused with database name in rds cdk

### ISSUE THREAD

**Issue by HeskethGD** [aws/aws-cdk#17182]
### What is the problem?

When attempting to use a custom username for a serverless rds cluster with aurora postgres, connections throw an error message that say 
`"BadRequestException: An error occurred (BadRequestException) when calling the ExecuteStatement operation: FATAL: database "<MY_CUSTOM_USERNAME>" does not exist; SQLState: 3D000"`
The parameter it claims is the database is in fact the username. When checking the secret that is created in secrets manager and checking the rds cluster both display the correct database name and the secret also displays the correct username. To overcome this issue it is necessary to specify the database name in the request but this is not normally required when allowing the cdk to autogenerate the database secret.

### Reproduction Steps

Below is some python cdk code I was using to override the default username of the cluster. It was based on [this post](https://github.com/aws/aws-cdk/issues/8984#issuecomment-718543852)

```python
 # Database secret with customised username retrieved at run time
  db_username = sm.Secret.from_secret_attributes(self, "my_db_username", 
      secret_complete_arn=params["db_username_arn"]
  )
  db_secret = rds.DatabaseSecret(self, 'MY_DB_Secret', 
      username=db_username.secret_value.to_string(),
      secret_name='MY_DB_SECRET_POSTGRES'
  )

  # Serverless database cluster with data api
  aurora_cluster = rds.ServerlessCluster(self, f"MY_CUSTOM_NAME_{env_name}",
      cluster_identifier=f"my_cluster_{env_name}",
      default_database_name=f'MY_CUSTOM_DATABSE_NAME_{env_name}',
      engine=rds.DatabaseClusterEngine.AURORA_POSTGRESQL,
      credentials=rds.Credentials.from_secret(db_secret),
      parameter_group=parameter_group,
      vpc=database_vpc,
      scaling=rds.ServerlessScalingOptions(
          auto_pause=cdk.Duration.minutes(10), 

      ),
      enable_data_api=True,
      security_groups=[
          my_security_group1,
          my_security_group2
      ]
  )
```

### What did you expect to happen?

I expected to be able to connect to the database using the secret_arn and the cluster_arn only, using e.g. the boto3 rds-data package, that is, I would expect cdk to provide the same behaviour when auto-generating the secret as it does when the user overrides it with a custom username. In the below code without custom username (not passing credentials) this is not an issue:
```python
# Serverless database cluster with data api
  aurora_cluster = rds.ServerlessCluster(self, f"MY_CUSTOM_NAME_{env_name}",
      cluster_identifier=f"my_cluster_{env_name}",
      default_database_name=f'MY_CUSTOM_DATABSE_NAME_{env_name}',
      engine=rds.DatabaseClusterEngine.AURORA_POSTGRESQL,
      parameter_group=parameter_group,
      vpc=database_vpc,
      scaling=rds.ServerlessScalingOptions(
          auto_pause=cdk.Duration.minutes(10), 

      ),
      enable_data_api=True,
      security_groups=[
          my_security_group1,
          my_security_group2
      ]
  )
```

### What actually happened?

The previously mentioned error was thrown.

### CDK CLI Version

1.124.0 (build 65761fe)

### Node.js Version

v14.17.4

### OS

ubuntu

### Language

Python

**Comment by skinny85** [comment]
I'm closing this one due to inactivity. @HeskethGD please comment if you still need help on this issue.

**Comment by chittasec** [comment]
Same issue still happening. Why the issue was closed ?

**Comment by skinny85** [comment]
@chittasec can you share your code that's causing you this problem?

**Comment by chittasec** [comment]
I am using the tutorial specified at below link exactly .

https://aws.amazon.com/getting-started/hands-on/inventory-system-for-gaming-app-with-amazon-aurora-serverless/

I get the error database "adminpostgres"  does not exist. I have "adminpostgres" as the user specified in the Secrets manager . But the error says it is considered as DB name . Either some steps missing in this tutorial or some other issue .

**Comment by skinny85** [comment]
@chittasec not sure I follow. That tutorials is not a CDK tutorial, right? You create the database following it using the console, not CDK. So I don't see what a CDK change could accomplish to make that experience better...?
