### ISSUE TITLE
(@aws-cdk/aws-s3): Use pre-defined role for `autoDeleteObjects`

### ISSUE THREAD

**Issue by TheJoshuaEvans** [aws/aws-cdk#17198]
### Description

When creating an S3 bucket with `autoDeleteObjects` set to true, CDK will generate a bespoke Lambda function that handles deletion of any S3 Objects. Can the properties of this bespoke function be modified? Specifically, can a pre-defined IAM Role be provided to the S3 constructor for use in the auto delete Lambda?

### Use Case

I work for a vendor working with a larger company. We are working in their AWS account, but for security reasons we are not allowed to create or modify IAM roles (I am aware that permission boundaries exist to handle this specific problem... we are working on it). We can just disable this feature to get by, but I would prefer if we didn't have to

### Proposed Solution

For backwards compatibility, could add an additional construct prop, something like `autoDeleteObjectsRoleArn` that takes the ARN of the desired role:
```js
const bucket = new Bucket(this, 'Bucket', {
  removalPolicy: RemovalPolicy.DESTROY,
  autoDeleteObjects: true,
  autoDeleteObjectsRoleArn: `arn:aws:iam::${accountId}:role/${resourceId}`
});
```

### Other information

To be even more specific, the following IAM actions are banned:
```
iam:CreateRole
iam:AttachRolePolicy
iam:PassRole
iam:DetachRolePolicy
iam:DeleteRole
```

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by rix0rrr** [comment]
I don't think we're going to add this property. 

In the short term, you could do one of:

* Use escape hatches and/or Aspects to mutate the `CfnFunction` in place.
* Disable the feature, and make your own Custom Resource that picks up the difference -- you could get started by copy/pasting our code and making the modifications you need.

In the long term, this would be covered by something like: https://github.com/aws/aws-cdk-rfcs/issues/25

Does that give you enough to go on?

**Comment by TheJoshuaEvans** [comment]
Yeah, I think we found a workaround. I was kinda hoping that this functionality was already in place and easy to use, and I was just missing it somehow :)

Thanks!

**Comment by TheJoshuaEvans** [comment]
I believe our work around was... To not use the auto-delete functionality :(
