### ISSUE TITLE
(aws-ec2): "The VPN Gateway has already been enabled" with existing vpc

### ISSUE THREAD

**Issue by DanMHammer** [aws/aws-cdk#17193]
### What is the problem?

[ec2.vpc].enableVpnGateway always throws the error "The VPN Gateway has already been enabled" after the VPN Gateway has been enabled for the first time when importing an existing VPC. Removing it from the stack to avoid the error will of course destroy the VPN Gateway. There are no options available to prevent the error.

### Reproduction Steps

```javascript
const cdk = require(`@aws-cdk/core`);
const VPNNetwork = require(`./stacks/vpn-network`);

const app = new cdk.App();

class VPNNetwork extends cdk.Stack {
  constructor(app, id, stackProps) {
    super(app, id, stackProps);

    const vpnNetwork = new ec2.Vpc(this, `VPNNetwork`, {  
           vpcId: <existing-vpc-id>,
     });

    vpnNetwork.enableVpnGateway({
      vpnRoutePropagation: vpnNetwork.privateSubnets,
    });
  }
}

new VPNNetwork(app, `VPNNetworkProduction`, {
  env: {
    account: <aws-account>,
    region: <aws-region>,
  },
});

app.synth();
```

Run twice:

`cdk synth VPNNetworkProduction`

### What did you expect to happen?

The first run should generate the cloud formation template that adds the VPN Gateway with the proper Route Propagation. 

Every subsequent run should, like most other cdk objects, synth without issue and generate a proper diff to not recreate the VPN Gateway.

### What actually happened?

Instead, after the first run, you get `Error: The VPN Gateway has already been enabled.`

### CDK CLI Version

1.129.0

### Node.js Version

v14.16.0

### OS

macOS 12.0

### Language

Typescript

### Other information

This error seems to be triggered any time there's already a vpn gateway Id on the existing VPC, which means that you can successfully deploy once and then the stack will fail every time after that.

Making this conditional will work around the error but will also mean that the vpn gateway will alternate between being created and destroyed every time the stack is deployed.

Ex: 
```javascript
...
if(!vpnNetwork.vpnGatewayId) {
    vpnNetwork.enableVpnGateway({
        vpnRoutePropagation: vpnNetwork.privateSubnets,
     });
}
```

See: https://github.com/aws/aws-cdk/blob/06838e66db0c9a48e2aa7da1e7707fda335bb62c/packages/%40aws-cdk/aws-ec2/lib/vpc.ts#L428

**Comment by baer** [comment]
Thank you for having a look at this! Right now, the only work-around I have thought of is to delete the VPNGateway every time I deploy a change, then re-add it. Do you have any other suggestions while this is being investigated?

**Comment by njlynch** [comment]
I've been unable to reproduce this so far, although it could be from me misinterpreting the reproduction steps. The description states that this occurs "when importing an existing VPC", but the reproduction code looks closer to the creation of a new VPC.

That being said, I tried this setup:

```ts
    const vpc = ec2.Vpc.fromLookup(this, 'VPC', { vpcName: 'myVpcName' });

    vpc.enableVpnGateway({
      type: 'ipsec.1',
      vpnRoutePropagation: [{ subnetType: ec2.SubnetType.PRIVATE_WITH_NAT }],
    });
```

I synthed and deployed this once. After, `cdk diff` came up clean, and a `cdk deploy` showed no changes.

@DanMHammer , @baer  - Can you help me find a reproducible example?
