### ISSUE TITLE
pipelines: Error when constructing EcrDockerCredential (Python)

### ISSUE THREAD

**Issue by FreeWillaert** [aws/aws-cdk#17216]
### What is the problem?

EcrDockerCredential constructor assumes that repository URI of repo is always populated while it's not

### Reproduction Steps

I'm using the Python CDK to create a DockerCredential for an ECR repo:

```
repo = Repository.from_repository_arn(self,'myrepo', repository_arn="arn:aws:ecr:eu-west-1:123456789012:repository/myrepo") 
credential = DockerCredential.ecr([repo], usages=[DockerCredentialUsage.ASSET_PUBLISHING])
```

but get the following error

```
> npx cdk synth -q

jsii.errors.JavaScriptError: 
  TypeError: Cannot read property 'split' of undefined
      at Function.split (/private/var/folders/_s/x4yx8f957b332y_tqk50mljw0000gn/T/jsii-kernel-iuD8qq/node_modules/@aws-cdk/core/lib/cfn-fn.js:106:27)
      at new EcrDockerCredential (/private/var/folders/_s/x4yx8f957b332y_tqk50mljw0000gn/T/jsii-kernel-iuD8qq/node_modules/@aws-cdk/pipelines/lib/docker-credentials.js:119:61)
      at Function.ecr (/private/var/folders/_s/x4yx8f957b332y_tqk50mljw0000gn/T/jsii-kernel-iuD8qq/node_modules/@aws-cdk/pipelines/lib/docker-credentials.js:51:16)
...
```

### What did you expect to happen?

ECR DockerCredential should be created.

### What actually happened?

  TypeError: Cannot read property 'split' of undefined

### CDK CLI Version

1.127

### Node.js Version

12.18.4

### OS

MacOS Catalina

### Language

Python

### Other information

This repo was in the same AWS account as the pipeline, but it could be in a different account as well.

**Comment by rix0rrr** [comment]
Does not reproduce for me. 

The following does not throw:

```python
from aws_cdk.core import App, Construct, Stack
from aws_cdk.aws_ecr import Repository
from aws_cdk.pipelines import DockerCredential, DockerCredentialUsage

class TestStack(Stack):
    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        repo = Repository.from_repository_arn(self,'myrepo', repository_arn="arn:aws:ecr:eu-west-1:123456789012:repository/myrepo")

        # Does not throw here
        credential = DockerCredential.ecr([repo], usages=[DockerCredentialUsage.ASSET_PUBLISHING])


app = App()
TestStack(app, "TestStack")
app.synth()
```

Can you post a minimal repro?

**Comment by FreeWillaert** [comment]
OMG - I'm really sorry.

I was accidentally using the _CodeCommit_ Repository :(
Really don't know how I missed that.

Thanks for looking into it, if I can somehow buy you a beer let me know :)
