### ISSUE TITLE
(pipelines.CodePipeline): unable to use additional_inputs

### ISSUE THREAD

**Issue by KnowSQL** [aws/aws-cdk#17224]
### What is the problem?

No matter what name I supply for the additional inputs directory, it fails at:
```
[Container] 2021/10/28 23:30:47 Running command [[ ! -d "blah-1234" ]] || { echo 'additionalInputs: "blah-1234" must not exist yet. If you want to merge multiple artifacts, use a "cp" command.'; exit 1; } && ln -s -- "$CODEBUILD_SRC_DIR_blahblah_blahblah_Source" "blah-1234"
```
followed by:
```
/codebuild/output/tmp/script.sh: 4: [[: not found
```
followed by:
```
additionalInputs: "blah-1234" must not exist yet. If you want to merge multiple artifacts, use a "cp" command.
```
followed by:
```
[Container] 2021/10/28 23:30:47 Command did not exit successfully [[ ! -d "blah-1234" ]] || { echo 'additionalInputs: "blah-1234" must not exist yet. If you want to merge multiple artifacts, use a "cp" command.'; exit 1; } && ln -s -- "$CODEBUILD_SRC_DIR_vblahblah_blahblah_Source" "blah-1234" exit status 1
```
causing the build to fail.

### Reproduction Steps

My code simply looks like:
```
        source0 = CodePipelineSource.connection("blahblah/blahblah", "master",
            connection_arn="arn:aws:codestar-connections:us-east-1:<123456789012>:connection/<some-uuid>"
        )

        pipeline = CodePipeline(self, "Abcdef",
            synth=ShellStep("Synth",
                input=CodePipelineSource.connection("blablah/blahblah0", "master",
                    connection_arn="arn:aws:codestar-connections:us-east-1:<123456789012>:connection/<some-uuid>"
                ),
                additional_inputs={
                    "blah-1234": source0,
                },
                commands=[
                    "npm install -g aws-cdk",
                    "pip install -r requirements.txt",
                    "cdk synth"
                ]
            )
        )
```
I've put `blah` etc in place of real github sources are they are all private repositories. The code is pulled in fine, but the build/synth step fails for `source0` above.

I've tried various combinations like `../blah-1234` (to create it in a sibling directory) etc. but all fail with similar error messages.

I'm suspicious of:
```
/codebuild/output/tmp/script.sh: 4: [[: not found
```
and think it's something in the aws script that's failing somewhere?

### What did you expect to happen?

I expected the build to pass

### What actually happened?

The build failed

### CDK CLI Version

1.129.0

### Node.js Version

N/A

### OS

Arch Linux

### Language

Python

**Comment by NGL321** [comment]
Hey @ustulation,

It looks from your comments like you have figured out the problem independently. Can we consider this resolved, or does it still need attention from a team member?

**Comment by ustulation** [comment]
I'll leave that to yous but I would consider this to be a bug. The fact that `ShellStep` does not set the codebuild env to use bash but then creates a bash construct thus failing shell execution at runtime means it's unusable for `additional_inputs`

**Comment by AbendGithub** [comment]
I experimented this error and ended downgrading to version 1.128. I needed to move forward with another change and could not verify why this was happening.

**Comment by HansFalkenberg-Visma** [comment]
I came here after googling the error message. Although the issue as originally reported has been fixed, the documentation on how to properly use additionalInputs could be better. I'll create a new issue for that.

**Comment by dennisvang** [comment]
@rix0rrr In a CodeBuildStep running a powershell script, using a `codebuild.WindowsBuildImage.WIN_SERVER_CORE_2019_BASE_3_0` env, I'm seeing a similar issue:

```none
...
[Container] 2024/09/09 12:04:08.605419 Running command [ ! -d "../my-content" ] \|\| { echo 'additionalInputs: "../my-content" must not exist yet. If you want to merge multiple artifacts, use a "cp" command.'; exit 1; } &#38;&#38; ln -s -- "$CODEBUILD_SRC_DIR_fs_processing_Source" "../my-content"
...
```
The additional input is a codecommit source, in this case.

Looks like it's trying to run bash commands in powershell.

Any ideas what I'm doing wrong?
