### ISSUE TITLE
ACM Certificate with alternative names

### ISSUE THREAD

**Issue by gaffo** [aws/aws-cdk#1722]
When creating an ACM cert with multiple subjectAlternativeNames and DNS validation requires you to create a dns entry for the main domainName, and one for each additional field. Currently the system only spits ou tthe main dns record on the command line. I know this is what CFN console does. However it'd be great to see all of them.

Seperately, as a follow on to #605, you'd want to be able to auto-validate these other names as well in one go.

**Comment by rix0rrr** [comment]
Still relevant

**Comment by njlynch** [comment]
Just circling back around to this issue. @gaffo  - Can you clarify what exactly you're looking for? Is it easier retrieval of the DNS records for validation? Have any of the improvements in the validation process in the last few months helped with this issue (e.g., built-in automatic DNS validation)?
