### ISSUE TITLE
[aws-redshift]: NodeType and ClusterType using wrong values

### ISSUE THREAD

**Issue by marksarnold** [aws/aws-cdk#17220]
### What is the problem?

NodeTypes and ClusterTypes defined in the respective enumerations are not using the correct names and/or values expected by CloudFormation

Example: both name and value of redshift.NodeType.DC2_LARGE are 'DC2_LARGE'.
Thus, the generated CloudFormation template fails because it expects something like 'dc2.large' - lowercase and period instead of underscore.

The same thing happens for ClusterType: name and value for redshift.ClusterType.MULTI_NODE are MULTI_NODE, but CloudFormation expects 'multi-node'.

This makes the defined enumerations unusable, unless I use a fix like redshift.NodeType.DC2_LARGE.value.lower().replace('_', '.') , but then I might as well just hard-code it...

What I am trying to do (and what I think the purpose of those classes is) is something like this :

```
        pocCluster = redshift.CfnCluster(
            self
...
            , node_type = redshift.NodeType.DC2_LARGE.value
            , cluster_type = redshift.ClusterType.MULTI_NODE.value
...

```

### Reproduction Steps

```
from aws_cdk import aws_redshift as redshift

print ( 'value: {}, name: {}'.format(
    redshift.NodeType.DC2_LARGE.value
    , redshift.NodeType.DC2_LARGE.name
    ))

print ( 'value: {}, name: {}'.format(
    redshift.ClusterType.MULTI_NODE.value
    , redshift.ClusterType.MULTI_NODE.name
    ))

```

### What did you expect to happen?

Either name or value (probably the latter?) should reflect a version of the string that will work with CloudFormation (e.g. "dc2.large")

### What actually happened?

Neither name nor value are accepted by CloudFormation

### CDK CLI Version

1.129.0 (build fb43f89)

### Node.js Version

v14.18.1

### OS

Windows 10

### Language

Python

### Language Version

Python 3.10.0

**Comment by ayush987goyal** [comment]
@marksarnold The behavior is correct. In the above snippet, you are trying to use the `NodeType` and `ClusterType` enums with the L1 `redshift.CfnCluster` construct instead of the L2 `redshift.Cluster` construct. These enums are only meant to be used with the L2 construct and are defined with the correct values: [Ref](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-redshift/lib/cluster.ts#L18)

@njlynch This issue can be closed.

**Comment by marksarnold** [comment]
Yes, I was trying to use it with L1 constructs. I did notice that it works with L2.
