### ISSUE TITLE
elasticloadbalancingv2: capital case DNS name

### ISSUE THREAD

**Issue by csgyuri** [aws/aws-cdk#17230]
### General Issue

Application load balancer has capital case dns name which causes issues with load balancer controller

### The Question

I have created an internal ApplicationLoadBalancer without specifying the name property to avoid running into the limitations that providing resource name may create as documented. 

What I have observed is that the DNS name of the load balancer is like this: internal-<load balancer name>-<a numeric value>-<region>-elb.amazonaws.com. The generated load balancer name however contains capital letters and when I try to add this dns name to Route53, then it translates it into lower case letters and I also get an error messages from the load balancer controller: 
```
{"level":"error","ts":1635507753.6659174,"logger":"controller-runtime.manager.controller.ingress","msg":"Reconciler error","name":"<group name>","namespace":"","error":"failed to update ingress status: default/<ingress name>: Ingress.extensions \"<ingress name>\" is invalid: status.loadBalancer.ingress[0].hostname: Invalid value: \"internal-eks-c-ekscl-1LYDFGU1DZKIY-<a numeric value>.<region>.elb.amazonaws.com\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')"}
```

I would like to ask if this is the expected behavior and if not then how can I circumvent it without specifying the load balancer name?

### CDK CLI Version

1.128.0

### Node.js Version

14.16.1

### OS

Windows 10

### Language

Java

### Language Version

11.0.11

**Comment by peterwoodworth** [comment]
This is a limitation enforced by Kubernetes - relabeling as a bug. 

Are you able to share your CDK code? That would be helpful for reproduction

**Comment by csgyuri** [comment]
@peterwoodworth Thank you for looking into this topic. I added the load balancer class to this comment az a zip. 

The subnets are created as part of this app in a separate stack and passed in having the AZ as string as key and the Subnet object as value. The Vpc value is looked up from an existing VPC based on a VPC id passed in as context value to the App.

[LoadBalancer.zip](https://github.com/aws/aws-cdk/files/7467451/LoadBalancer.zip)

**Comment by njlynch** [comment]
The load balancer controller that is throwing the error -- is that coming from the CDK or from Kubernetes itself? We can't control the output of the application load balancer; this value comes straight from the service team and CloudFormation, and there are no built-in intrinsic functions to downcase a value.

**Comment by csgyuri** [comment]
@njlynch Thanks for looking into this, and sorry for the late response. The load balancer controller is deployed using CDK, and it runs inside the EKS cluster as a controller. The ALB is also created through CDK.
