### ISSUE TITLE
How to disable metadata for L1 constructs when synthesizing template

### ISSUE THREAD

**Issue by LazzariPaolo** [aws/aws-cdk#17231]
### General Issue

L1 constructs should NOT include metadata by default

### The Question

The [AWS CDK documentation](https://docs.aws.amazon.com/zh_cn/cdk/latest/guide/constructs.html) states:

> L1 constructs are exactly the resources defined by AWS CloudFormation—no more, no less.

This is false, because MetaData is being added to the resource by default.

If I create this resource only:

```python
bucket = s3.CfnBucket(self, "MyBucket", bucket_name="MyBucket")
```

then the output of:

`cdk synth --json --version-reporting false` 

creates:

```json
{
  "Resources": {
    "MyBucket": {
      "Type": "AWS::S3::Bucket",
      "Properties": {
        "BucketName": "MyBucket"
      },
      "Metadata": {
        "aws:cdk:path": "HelloCdkStack/MyBucket"
      }
    }
  }
}
```

Why is the metadata there?

### CDK CLI Version

1.129.0

### Language

Python

**Comment by LazzariPaolo** [comment]
Hey @peterwoodworth 

I'm already using:

```bash
cdk synth --json --version-reporting false
```

what else do I need to add to remove the metadata?

**Comment by peterwoodworth** [comment]
You will also need to use the `--path-metadata false` option, sorry for not catching that earlier :)

**Comment by LazzariPaolo** [comment]
Thanks, that worked.

**Comment by peterwoodworth** [comment]
Since the CDK is a tool which uses AWS CloudFormation under the hood, we wouldn't have a way to gather data on how most people are using the CDK (especially compared to CloudFormation) if we didn't add the metadata for tracking. Having the metadata as default is necessary so that we gather enough data, which helps us figure out how to build more features for the CDK. They're important for us, and they also don't affect the functionality of your resources, plus they're easy to remove. Given this, they should stay being added by default.

I'm curious, is there any reason in particular you don't want this metadata on your resources?

**Comment by LazzariPaolo** [comment]
Thank you for your explanation @peterwoodworth , it makes sense

**Comment by jbschooley** [comment]
Found this thread while searching for a way to disable metadata.

I understand the purpose and do agree that it should be the default. However, there are good reasons to disable it sometimes. I am trying to replace my Amplify stack with CDK, and I need my generated stacks to be as similar as possible to what Amplify generates. All the metadata being added to everything clogs up my `cdk diff` and I miss other things being removed/added that shouldn't be there. 

@peterwoodworth

**Comment by ViktorCosenza** [comment]
> I had the same issue before. You can use `analyticsReporting: false` inside of `stackProps` to disable `AWS::CDK::METADATA` Also, if you want to disable the hard rule for bootstrap, you can define the `synthesizer` to turn off the version rule inside of `stackProps`.
> 
> ```
> synthesizer: new DefaultStackSynthesizer({
>                 // remove hard requirement for bootstrap before create the stack
>                 generateBootstrapVersionRule: false
>             }) 
> ```

This worked nicely, thanks. My issue with the metadata is that is bloats the generated json.
