### ISSUE TITLE
(aws-cloudtrail): extraneous forward slash in objectPrefix

### ISSUE THREAD

**Issue by rantoniuk** [aws/aws-cdk#17232]
### What is the problem?

There is an inconsistency of treating S3 prefixes between `Trail()` and other CDK constructs:

```ts
const s3key = '/test.zip';
const trail = new Trail(this, 'Trail');
trail.addS3EventSelector(
    [
        {
            bucket: props.bucket,
            objectPrefix: s3key,
        },
    ],
    {
        readWriteType: ReadWriteType.WRITE_ONLY,
    },
);
```

results in:
```
~] AWS::CloudTrail::Trail 
 └─ [~] EventSelectors
     └─ @@ -11,7 +11,7 @@
        [+]       "//test.zip"
```

Above adds a second `/` while it should not, comparing to other places, like:
```ts
new Rule(this, 'rule', {
            eventPattern: {
                source: ['aws.s3'],
                detailType: ['AWS API Call via CloudTrail'],
                detail: {
                    eventSource: ['s3.amazonaws.com'],
                    eventName: ['CopyObject', 'PutObject', 'CompleteMultipartUpload'],
                    requestParameters: {
                        bucketName: 'bucketname',
                        key: [s3key],
                    },
                },
            },
            targets: [new CodePipelineTarget(pipeline)],
        });


[~] AWS::Events::Rule
 └─ [~] EventPattern
     └─ [~] .detail:
         └─ [~] .requestParameters:
             └─ [~] .key:
                 └─ @@ -1,3 +1,3 @@
                    [ ] [
                    [+]   "/test.zip"
                    [ ] ]

```

### Reproduction Steps

Above.

### What did you expect to happen?

Explained above.

### What actually happened?

Extra forward slash added for objectPrefix in `trail.addS3EventSelector()`

### CDK CLI Version

1.129.0

### Node.js Version

12.20.0

### OS

MacOS

### Language

Typescript

**Comment by rix0rrr** [comment]
I feel it's unusual for any key to START with a `/`. 

I have to say I'm not sure whether or not it's possible for object keys to start with a `/`, and how S3 will treat that.

When bucket and key are in different fields it's pretty easy:

```
{ Bucket: 'mybucket', Key: '/file.zip' }
```

Obviously encodes a key that starts with a `/`.

But if you combine both fields into one string:

```
s3://mybucket/file.zip
```

Is that the file `/file.zip` in `mybucket`, or the file `file.zip` in `mybucket`? The only possible solution must be `file.zip`. But that means that if you meant to indicate `/file.zip`, then you must write 

```
s3://mybucket//file.zip
```

Of course, it could be that S3 simply does not allow (and for convenience silently drops) `/` at the start of key names, in which case the discussion is moot.  In that case, writing `/file.zip` is incorrect, but that will not matter in practice.

Would be helpful if someone could tell me what the right answer is here.

**Comment by rantoniuk** [comment]
Hi @rix0rrr,
Thanks for the reply. There is a misunderstanding though - I don't want the objects to start `/`.

The problem is that Trail `trail.addS3EventSelector( [ { bucket: props.bucket,  objectPrefix: 'whatever.zip', ... } ]`
will result in CDK output of `/whatever.zip` instead of `whatever.zip`.
However, if you try the same in other places, e.g. `Rule` then it is added "as is" so as `whatever.zip`, not `/whatever.zip` - this is only a matter of consistency between modules.
