### ISSUE TITLE
(aws-rds): DatabaseClusterFromSnapshot construct should support storage encryption

### ISSUE THREAD

**Issue by stephenwiebe** [aws/aws-cdk#17241]
### General Issue

DatabaseClusterFromSnapshot construct should support storage enryption

### The Question

I need to enable encryption on an Aurora database cluster that already exists, and it appears the way to do this is to take a snapshot, and restore it to a new database cluster with the Storage Encrypted option enabled (and an encryption key specified):

> You can't convert an unencrypted DB cluster to an encrypted one. However, you can restore an unencrypted snapshot to an encrypted Aurora DB cluster. To do this, specify a KMS key when you restore from the unencrypted snapshot.

I've verified that I can do this manually through the AWS console. I also see that this `StorageEncrypted` option exists for the underlying CFN resource `AWS::RDS::DBCluster`, and also for the non-snapshotted `DatabaseCluster` CDK construct. **However**, the option for the CDK construct `DatabaseClusterFromSnapshot` **should** exist, but doesn't.

It looks like the fix for this is to move the properties `storageEncrypted` and `storageEncryptionKey` at https://github.com/aws/aws-cdk/blob/v1.130.0/packages/@aws-cdk/aws-rds/lib/cluster.ts#L460-L473 from DatabaseClusterProps to DatabaseClusterBaseProps.

### CDK CLI Version

1.130.0

### Language

Typescript

**Comment by peterwoodworth** [comment]
Hey @stephenwiebe, thanks for submitting this

According to [CloudFormation documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbcluster.html#cfn-rds-dbcluster-storageencrypted), this would be redundant. 

> If you specify the SnapshotIdentifier or SourceDBClusterIdentifier property, don't specify this property. The value is inherited from the snapshot or source DB instance.

Let me know if you don't find this to be the case

**Comment by stephenwiebe** [comment]
Thanks for the quick reply! Yes, I haven't found that to be the case. Namely because it's impossible to convert/copy an unencrypted snapshot of a cluster to an encrypted snapshot (this does work for a non-clustered instance, but not for an Aurora cluster). This is called out here: https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Overview.Encryption.html#Overview.Encryption.Limitations. The only way to encrypt an unencrypted cluster is:

> However, you can restore an unencrypted snapshot to an encrypted Aurora DB cluster. To do this, specify a KMS key when you restore from the unencrypted snapshot.

So I believe the portion you quoted above does apply when the source DB snapshot is already encrypted, but if it's not already encrypted, then this property must be specified.

**Comment by peterwoodworth** [comment]
Thanks for the explanation, I'm going to relabel this as a feature request. Contributions are welcome 😃
