### ISSUE TITLE
(aws_ecs and aws_ecs_patterns): Windows Fargate Support

### ISSUE THREAD

**Issue by jasonumiker** [aws/aws-cdk#17245]
### Description

Now that there is Windows support in ECS Fargate it would be nice if we could see equivalent support for it in the CDK to Linux Fargate.

### Use Case

Run Windows containers via ECS Fargate with the CDK

### Proposed Solution

Mirror as closely as possible the existing CDK constructs for Linux Fargate to do Windows fargate also or instead.

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by peterwoodworth** [comment]
@jasonumiker is this issue related to [this one?](https://github.com/aws/aws-cdk/issues/17242) I'm not super familiar with what's been added, what all do you think would need to be done to satisfy this feature request?

**Comment by pahud** [comment]
Hi, @jasonumiker 

Actuall @neilkuan is working on the PR now and related to https://github.com/aws/aws-cdk/issues/17242. I will help him create the PR draft ASAP and welcome to review.

**Comment by peterwoodworth** [comment]
Thanks pahud,

closing this issue as duplicate
