### ISSUE TITLE
(aws-ecs): support RuntimePlatform Property at TaskDefinition class for create windows OperatingSystem

### ISSUE THREAD

**Issue by neilkuan** [aws/aws-cdk#17242]
### Description

support `RuntimePlatform` Property at `TaskDefinition` class for create windows OperatingSystem.

### Use Case

Windows support for AWS Fargate on Amazon ECS on 28 OCT 2021 .
https://aws.amazon.com/tw/blogs/containers/running-windows-containers-with-amazon-ecs-on-aws-fargate/

### Proposed Solution

support RuntimePlatform Property at TaskDefinition class.

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by peterwoodworth** [comment]
Thanks for submitting this feature request @neilkuan,

The underlying taskDefinition doesn't get created with this property. https://github.com/aws/aws-cdk/blob/9c094aef07ecf99c6a151a27daeacdbe17d83236/packages/%40aws-cdk/aws-ecs/lib/base/task-definition.ts#L420-L448

[CloudFormation docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-taskdefinition.html#cfn-ecs-taskdefinition-runtimeplatform) on RuntimePlatform

To work around this before we officially support it, you should be able to use an [escape hatch](https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html#cfn_layer_resource) to apply this property as needed. 

Contributions are welcome as well 😃

**Comment by neilkuan** [comment]
yes, I already did that :).
```ts
const vpc = ec2.Vpc.fromLookup(this, 'VPC', { isDefault: true });
    const cluster = new ecs.Cluster(this, 'Cluster', {
      vpc,
      enableFargateCapacityProviders: true,
    });
    const taskdef = new ecs.TaskDefinition(this, 'TaskDef', { compatibility: ecs.Compatibility.FARGATE, memoryMiB: '2048', cpu: '1024' });
    taskdef.addContainer('Container', {
      logging: ecs.LogDriver.awsLogs({ streamPrefix: 'win-iis-on-fargate' }),
      portMappings: [{ containerPort: 80 }],
      image: ecs.ContainerImage.fromRegistry('mcr.microsoft.com/windows/servercore/iis:windowsservercore-ltsc2019'),
    });
    (taskdef.node.defaultChild as ecs.CfnTaskDefinition).addPropertyOverride('RuntimePlatform', {
      OperatingSystemFamily: 'WINDOWS_SERVER_2019_CORE',
    });
    const fargateWindowsService = new ecs.FargateService(this, 'Service', {
      taskDefinition: taskdef,
      cluster,
      assignPublicIp: true,
    });
    ecs.WindowsOptimizedVersion.SERVER_2019;
    fargateWindowsService.connections.allowFrom(ec2.Peer.ipv4(`${process.env.MYIP}/32`), ec2.Port.tcp(80));
```

**Comment by pahud** [comment]
Looks like v46 spec has the `RuntimePlatform` property. Let's wait until the https://github.com/aws/aws-cdk/pull/17223 being merged.

**Comment by alisade** [comment]
also for graviton 
https://aws.amazon.com/blogs/aws/announcing-aws-graviton2-support-for-aws-fargate-get-up-to-40-better-price-performance-for-your-serverless-containers/

**Comment by suresh26k** [comment]
For python, we can do the same

```python
   task_definition = ecs.TaskDefinition(
        .....
    )

    # Import resource as cfn resource
    cfn_task_definition = task_definition.node.find_child("Resource")
    # Override cfn resource property
    cfn_task_definition.add_override(
        "Properties.RuntimePlatform.OperatingSystemFamily", "WINDOWS_SERVER_2019_CORE")
```

**Comment by suresh26k** [comment]
> Thanks for submitting this feature request @neilkuan,
> 
> The underlying taskDefinition doesn't get created with this property.
> 
> https://github.com/aws/aws-cdk/blob/9c094aef07ecf99c6a151a27daeacdbe17d83236/packages/%40aws-cdk/aws-ecs/lib/base/task-definition.ts#L420-L448
> 
> [CloudFormation docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-taskdefinition.html#cfn-ecs-taskdefinition-runtimeplatform) on RuntimePlatform
> 
> To work around this before we officially support it, you should be able to use an [escape hatch](https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html#cfn_layer_resource) to apply this property as needed.
> 
> Contributions are welcome as well 😃

@peterwoodworth

Could you please share any docs to help me start contributing.

**Comment by peterwoodworth** [comment]
Thanks for your interest @suresh26k, please check out [CONTRIBUTING.md](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md). Let me know if you have any further questions 🙂

**Comment by enricopesce** [comment]
@flavioleggio you can prepare a task definition with the architecture you want and assign it to ApplicationLoadBalancedFargateService
