### ISSUE TITLE
@aws-cdk/aws-lambda-nodejs: Esbuild bundling option to disable sourcesContent 

### ISSUE THREAD

**Issue by suds-sky** [aws/aws-cdk#17256]
### Description

With the `NodeJsFunction` construct, We have observed that the source code is included as part of the source maps. For production builds, We do not need this as we are not going to debug the lambda. 

### Use Case

For production lambdas, it is desirable to omit the source code in source maps generated by esbuild through `NodeJsFunction` construct

### Proposed Solution

In `esbuild`, there is an option we can set to disable this to not to include the source code as per `esbuild` docs -https://esbuild.github.io/api/#sources-content 

We can add a property (sourcesContent) to `BundlingOptions` type and allow the function to enable/disable the inclusion of sourcesContent into the source map generated.

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by peterwoodworth** [comment]
Thanks for submitting this issue, contributions are welcome!

I think you know what you need to do, but I'll share what I've found on a quick look.

Like you said, we'll want to add a prop to BundlingOptions https://github.com/aws/aws-cdk/blob/9c094aef07ecf99c6a151a27daeacdbe17d83236/packages/%40aws-cdk/aws-lambda-nodejs/lib/types.ts#L6

These end up getting passed here
https://github.com/aws/aws-cdk/blob/9c094aef07ecf99c6a151a27daeacdbe17d83236/packages/%40aws-cdk/aws-lambda-nodejs/lib/function.ts#L106-L113

And ultimately I think you'll want to add something here
https://github.com/aws/aws-cdk/blob/9c094aef07ecf99c6a151a27daeacdbe17d83236/packages/%40aws-cdk/aws-lambda-nodejs/lib/bundling.ts#L186-L204
