### ISSUE TITLE
Slack link on cdk.dev is busted

### ISSUE THREAD

**Issue by iamtheworstdev** [aws/aws-cdk#17253]
### What is the problem?

The slack link on cdk.dev is expired

### Reproduction Steps

click the link

### What did you expect to happen?

Get an invite to slack

### What actually happened?

got "This link is no longer active"

### CDK CLI Version

2

### Node.js Version

14

### OS

Windows

### Language

Typescript

**Comment by mbonig** [comment]
I'm on it...

**Comment by mbonig** [comment]
Link updated. Thank you.

**Comment by peterwoodworth** [comment]
@mbonig is this good to resolve?
