### ISSUE TITLE
(core): consumer._toCloudFormation is not a function when using CfnRefElement 

### ISSUE THREAD

**Issue by LazzariPaolo** [aws/aws-cdk#17257]
I want to create a template where the user can select a key name and a subnet, and I want to use whatever was chosen to start an EC2 instance.

I am using `core.CfnParameter` for the parameters:

```python
# Define parameters
ssh_key_name = core.CfnParameter(self, "SSHKeyName", type="AWS::EC2::KeyPair::KeyName")
subnet = core.CfnParameter(self, "Subnet", type="AWS::EC2::Subnet::Id")
```

then I'm using `core.CfnRefElement` to get a `ref` to those resources:

```python
# Convert parameters to ref
ref_ssh_key_name = core.CfnRefElement(ssh_key_name,id="MyKey").ref
ref_subnet_id = core.CfnRefElement(subnet,id="MySubnet").ref
```

then I'm using `ec2.CfnInstance` to create the ec2 instance:

```python
instance = ec2.CfnInstance(self, "MyEC2Instance",key_name=ref_ssh_key_name, subnet_id=ref_subnet_id)
```

when I try to synth the template, I see this error:

> Traceback (most recent call last):
  File "app.py", line 18, in <module>
    app.synth()
  File "E:\devel\hello-cdk\.venv\lib\site-packages\aws_cdk\core\__init__.py", line 16433, in synth
    return typing.cast(aws_cdk.cx_api.CloudAssembly, jsii.invoke(self, "synth", [options]))
  File "E:\devel\hello-cdk\.venv\lib\site-packages\jsii\_kernel\__init__.py", line 143, in wrapped
    return _recursize_dereference(kernel, fn(kernel, *args, **kwargs))
  File "E:\devel\hello-cdk\.venv\lib\site-packages\jsii\_kernel\__init__.py", line 359, in invoke
    args=_make_reference_for_native(self, args),
  File "E:\devel\hello-cdk\.venv\lib\site-packages\jsii\_kernel\providers\process.py", line 359, in invoke
    return self._process.send(request, InvokeResponse)
  File "E:\devel\hello-cdk\.venv\lib\site-packages\jsii\_kernel\providers\process.py", line 326, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: consumer._toCloudFormation is not a function

### CDK CLI Version

1.129.0

### Node.js Version

v12.14.1

### OS

Windows

### Language

Python

**Comment by LazzariPaolo** [comment]
`aws-lambda` is the wrong tag for this

**Comment by peterwoodworth** [comment]
Thanks for opening this @LazzariPaolo, I was able to reproduce this on Python.

I tried messing around with this on Typescript as well, and I can't really figure out how the CfnRefElement class is supposed to be used.

You can't create a new object of this type, because it throws this error: `Cannot create an instance of an abstract class.`

But using it any other way will throw this: `Value of type 'typeof CfnRefElement' is not callable. Did you mean to include 'new'?`

I think the issue here is that the user isn't meant to directly use the `CfnRefElement` class. There are a couple classes of ours that extend the class though. Does [CfnMapping](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.CfnMapping.html) work for you here?

**Comment by peterwoodworth** [comment]
> I think the issue here is that the user isn't meant to directly use the CfnRefElement class

@rix0rrr is this accurate? Either way, the [initializer](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.CfnRefElement.html#initializer) is inaccurate. If the user is meant to be able to extend the class I think that should be clearer

**Comment by LazzariPaolo** [comment]
Thanks for your message @peterwoodworth 

Unfortunately I don't think `CfnMapping` here is going to help me, since that is for mappings.

I want to be able to create the template in such a way that the resource (the ec2 instance) will use as key-pair and subnet whatever is chosen as parameters. This is basically the equivalent of the `Ref` construct in native CloudFormation. From reading the documentation, it seems that CfnRefElement is what I should be using to achieve this; however I've been unable to do so successfully.

**Comment by peterwoodworth** [comment]
See our documentation on [CfnParameters](https://docs.aws.amazon.com/cdk/api/latest/docs/core-readme.html#parameters), you can simply use the `valueAsXxx` method on `ssh_key_name` and `subnet` rather than going through any additional trouble.

If you do this:

```py
instance = ec2.CfnInstance(self, "MyEC2Instance",key_name=ssh_key_name.value_as_string, subnet_id=subnet.value_as_string)
```

It will output this:
```yaml
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName:
        Ref: SSHKeyName
      SubnetId:
        Ref: Subnet
```

**Comment by LazzariPaolo** [comment]
Thank you @peterwoodworth , that worked!

**Comment by peterwoodworth** [comment]
Great @LazzariPaolo! 

I'm curious what lead you to believe this:

> From reading the documentation, it seems that CfnRefElement is what I should be using to achieve this;

I agree our documentation regarding the purpose of CfnRefElement is a bit unclear and I'd like to clarify it, but I'm curious how you decided to try and use it.

**Comment by LazzariPaolo** [comment]
@peterwoodworth By working with the different `Cfn` components (e.g. `CfnSecurityGroup`), I noticed that they all seem to have the **ref** property. This however didn't seem true for the parameter component `CfnParameter`; so my assumption was that `CfnParameter` was a special case the **ref** of which needed to be somehow evaluated with a different resource, and that's when I stumbled across the `CfnRefElement` doc, which says:

> These constructs are things like Conditions and Parameters, can be referenced by taking the .ref attribute.

I thought this was confirming my thesis and therefore decided to try it.

**Comment by peterwoodworth** [comment]
Ah I see where the confusion is.

If we look at the previous sentence of what you quoted, it puts the next sentence in the right context

> Base class for referenceable CloudFormation constructs which are not Resources.
> These constructs are things like Conditions and Parameters, can be referenced by taking the .ref attribute.

Essentially, this is saying that `CfnRefElement` is a base class which constructs like `CfnParameter` and `CfnCondition` can build off of. This is necessary for all constructs which can be referenced by `.ref`, with the exception of Resources which extend from a different base class. So, having the class `CfnParameter` extend `CfnRefElement` allows the former to have a .ref property

Our documentation on how to use parameters can be found [here](https://docs.aws.amazon.com/cdk/api/latest/docs/core-readme.html#parameters)
