### ISSUE TITLE
`pipelines.ShellStep` or `pipelines.CodeBuildStep` input props Bug

### ISSUE THREAD

**Issue by williamputraintan** [aws/aws-cdk#17254]
### What is the problem?

`pipelines.ShellStep` or `pipelines.CodeBuildStep` does not detect input from the source stage of Pipeline from the  [codePipeline](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_pipelines.CodePipeline.html#codepipeline) props.

### Reproduction Steps

Setup: 
- Initiated [codepipeline.Pipeline](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-codepipeline.Pipeline.html), and added a source stage to the pipeline. 
 - Create [pipelines.CodePipeline](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_pipelines.CodePipeline.html) and reference to the [codepipeline.Pipeline](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-codepipeline.Pipeline.html) initiated.
 - Use `pipelines.ShellStep` or `pipelines.CodeBuildStep` at [pipelines.CodePipeline](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_pipelines.CodePipeline.html) in the [Synth prop](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_pipelines.CodePipeline.html#synth) where the input is left empty (as it is optional) and assuming it will use the source stage at the [codepipeline.Pipeline](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-codepipeline.Pipeline.html) as the input.

        # Create S3 bucket for artifacts
        pipeline_artifact_bucket = s3.Bucket(
            ...Some props to create s3bucket,
        )
        source_artifact = codepipeline.Artifact(
            artifact_name="pipeline_artifact",
        )

        # Fetch github repository for changes
        code_star_action = codepipeline_actions.CodeStarConnectionsSourceAction(
            connection_arn=codestar_arn,
            output=source_artifact,
            action_name="Source",
            trigger_on_push=True,
            ...some additional props for CodeStarConnectionsSourceAction
        )

        # Create a pipeline from codepipeline
        codepipeline_Pipeline = codepipeline.Pipeline(
            self,
            "CodePipelineInit",
            artifact_bucket=pipeline_artifact_bucket,
            restart_execution_on_update=True,
            cross_account_keys=False,
            pipeline_name="codepipeline_Pipeline"
        )

        # Source Stage
        codepipeline_Pipeline.add_stage(
            stage_name="Source",
            actions=[code_star_action]
        )

        # Create A pipeline for cdk stack
        _ = pipelines.CodePipeline(
            self,
            "CodePipelineSelfMutate",
            code_pipeline=codepipeline_Pipeline,
            synth=pipelines.ShellStep(
                "CDKShellScript",
                commands=[
                    "cdk synth"
                ],
                primary_output_directory="cdk/cdk.out"
            )
        )

### What did you expect to happen?

pipelines.ShellStep uses input from the pipeline source stage

### What actually happened?

`jsii.errors.JSIIError: CodeBuild action 'CDKShellScript' requires an input (and the pipeline doesn't have a Source to fall back to). Add an input or a pipeline source.
`
### CDK CLI Version

1.122.0 (build ae09c16)

### Node.js Version

N/A

### OS

Windows

### Language

Python

### Other information
A similar StackOverflow question [AWS CDK Pipelines using with an existing codepipeline](https://stackoverflow.com/questions/68800264/aws-cdk-pipelines-using-with-an-existing-codepipeline)

**Comment by peterwoodworth** [comment]
This is confusing, I wish our docs described this better since you're not the first person to have trouble with this

per Rico from #16488:

> Use [`CodePipelineFileSet`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_pipelines.CodePipelineFileSet.html) to turn the CodePipeline `sourceOutput` into a `FileSet` you can pass into the `synth` step:
> 
> ```ts
>     const sourceFileSet = CodePipelineFileSet.fromArtifact(sourceOutput);
> 
>     const cdkPipeline = new pipelines.CodePipeline(this, "CDKPipeline", {
>       codePipeline: pipeline,
>       synth: new pipelines.ShellStep("Synth", {
>         input: sourceFileSet,
>         commands: ["yarn install --frozen-lockfile", "npx cdk synth"],
>       }),
>     });
> ```

Please go to the original issue and give it a thumbs up if you'd like this to be better documented!
