### ISSUE TITLE
add support for using ParameterMapping in LambdaProxyIntegration

### ISSUE THREAD

**Issue by yip-anthony-principal** [aws/aws-cdk#17255]
### Description

it seems the new `ParameterMapping` function only support `HttpAlbIntegration`. If I understand correctly it is not possible to add parameter mapping to `LambdaProxyIntegration`, if so is there any workaround for this?

### Use Case

it's configurable on the AWS API Gateway website but not configurable on the AWS CDK

### Proposed Solution

add support for it, like https://github.com/aws/aws-cdk/pull/15630

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by dan-lind** [comment]
This shouldn't be a problem really, there are unit tests in place for LambdaProxyIntegration as well.

```
new LambdaProxyIntegration({
    handler: fooFunction(stack, 'Fn'),
    parameterMapping: new ParameterMapping()
      .appendHeader('header2', MappingValue.requestHeader('header1'))
      .removeHeader('header1'),
}),
```

**Comment by yip-anthony-principal** [comment]
Thanks for the quick response, I got ts-error on the above example

```typescript
```

**Comment by yip-anthony-principal** [comment]
you are correct, thanks.
