### ISSUE TITLE
(cli): improve asset publishing / deploy --hotswap performance

### ISSUE THREAD

**Issue by Chriscbr** [aws/aws-cdk#17266]
### Description

A project we are working on has over a dozen Lambda functions, each with its own bundle. `deploy --hotswap` makes it a lot easier to deploy a Lambda and test it out -- however, because of the number of Lambda's in our project, it still takes 20-30 seconds even if I only want to update the code for a single Lambda function.

When I look at the log (by calling `--verbose`) it appears that most of the time is being spent checking if the bundled files already exist in S3 to determine whether they need to be re-uploaded (see log below).

### Use Case

To improve development iteration speed with `cdk deploy --hotswap`.

### Proposed Solution

Even though I am experiencing this with `--hotswap`, it's possible most of the performance improvements that could be made are in the CDK assets module. Without further knowledge of the performance bottlenecks, it might be helpful to profile what steps are taking up the most time.

An additional observation is that in many common cases, the assets module may be re-assuming the same AWS role many times - is it possible to batch the operations so that the role only needs to be assumed once per deployment?

### Other information

Sample log (abbreviated)...
```
[0%] start: Publishing <ASSET1>:012345678901-us-east-1
Retrieved account ID 012345678901 from disk cache
Assuming role 'arn:aws:iam::012345678901:role/cdk-hnb659fds-file-publishing-role-012345678901-us-east-1'.
[0%] check: Check s3://cdk-hnb659fds-assets-012345678901-us-east-1/<ASSET1>.zip
[0%] found: Found s3://cdk-hnb659fds-assets-012345678901-us-east-1/<ASSET1>.zip
[4%] success: Published <ASSET1>:012345678901-us-east-1
[4%] start: Publishing <ASSET2>:012345678901-us-east-1
Retrieved account ID 012345678901 from disk cache
Assuming role 'arn:aws:iam::012345678901:role/cdk-hnb659fds-file-publishing-role-012345678901-us-east-1'.
[4%] check: Check s3://cdk-hnb659fds-assets-012345678901-us-east-1/<ASSET2>.zip
[4%] found: Found s3://cdk-hnb659fds-assets-012345678901-us-east-1/<ASSET2>.zip
[9%] success: Published <ASSET2>:012345678901-us-east-1
...
```

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by rix0rrr** [comment]
Pretty sure it's going to be the assume-role that is going to impact you. The S3 checks should be cheap enough that I'd be surprised if they mattered.

**Comment by Chriscbr** [comment]
Closing in favor of #19193
