### ISSUE TITLE
(aws-ecr-assets): Authenticate to ECR source repositories

### ISSUE THREAD

**Issue by athewsey** [aws/aws-cdk#17268]
### Description

There should be some native CDK way to authenticate with (ECR) source repositories referenced in `FROM` clauses, when building container images with `DockerImageAsset`.

This request was previously mentioned at #12977 specifically in the context of Docker Hub (to deal with their public rate limit), but in my case I'm deriving child containers `FROM` parents hosted in regional ECR repositories (*not* ECR Public).

### Use Case

My app is deriving customized container images from the [AWS Deep Learning Containers](https://github.com/aws/deep-learning-containers) and other public SageMaker containers e.g. [SKLearn](https://github.com/aws/sagemaker-scikit-learn-container), which are hosted in publicly-accessible ECR repositories.

Today, running `cdk deploy` produces an error as below on pull, because the docker build doesn't try to authenticate with the source ECR repository referenced by the Dockerfile's `FROM` line:

```
------
 > [internal] load metadata for 121021644041.dkr.ecr.ap-southeast-1.amazonaws.com/sagemaker-scikit-learn:0.23-1-cpu-py3:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: unexpected status code [manifests 0.23-1-cpu-py3]: 403 Forbidden
```

I can work around it by [authenticating to ECR manually via CLI first](https://docs.aws.amazon.com/AmazonECR/latest/userguide/getting-started-cli.html#cli-authenticate-registry), but that's a confusing extra step for any new users of the app - and feels like it should be unnecessary since `cdk deploy` is already running in an AWS IAM context.

### Proposed Solution

Ideally, CDK/`DockerImageAsset` should automatically detect when the build references ECR repositories and transparently log in to them using the current AWS credentials.

If auto-detection is hard, perhaps the user could provide the list of required ECR source repositories as an additional parameter.

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by eladb** [comment]
@rix0rrr @otaviomacedo is this handled in pipelines?

**Comment by minhster99** [comment]
Hello, the workaround mentioned above does not work as of v2.89.0

When I log into ECR, I can pull the image required (docker pull xxx) but when I execute cdk deploy it fails with 403. Subsequent attempts to pull the image with docker pull also fails. So cdk is somehow clearing the authentication details to docker upon execution.

**Comment by niraj-at-travelopia** [comment]
Facing same issue
I have to manually add a `docker pull` step before `cdk deploy` step
