### ISSUE TITLE
cdk-pipelines: deploy outputs not usable if only referenced from stack step

### ISSUE THREAD

**Issue by bmmin** [aws/aws-cdk#17272]
### What is the problem?

When using deploy outputs in a shell script that is a stackStep, then the deploy action does not declare a namespace, as such the pipeline deployment fails with the following error:

```
2:40:31 PM | CREATE_FAILED        | AWS::CodePipeline::Pipeline | Pipeline9850B417
Valid format for a pipeline execution variable reference is a namespace and a key separated by a period (.). The following pipeline exe
cution variables are referencing a namespace that does not exist.
StageName=[stage], ActionName=[integTest], ActionConfigurationKey=[EnvironmentVariables], VariableReferenceText=[stage-app.out] (Servic
e: AWSCodePipeline; Status Code: 400; Error Code: InvalidActionDeclarationException; Request ID: 60b6cbb3-bf5d-49a9-9a4c-0e55be10397a;
Proxy: null)
```

### Reproduction Steps
```typescript
import { Repository } from "@aws-cdk/aws-codecommit";
import { CfnOutput, Construct, Stack, Stage } from "@aws-cdk/core";
import { CodePipeline, CodePipelineSource, ShellStep } from "@aws-cdk/pipelines";

export class PipelineStack extends Stack {
    constructor(scope: Construct, id: string) {
        super(scope, id);

        const repository = Repository.fromRepositoryName(this, "Repository", "repo");
        const codeSource = CodePipelineSource.codeCommit(repository, "main");

        const pipeline = new CodePipeline(this, "Pipeline", {
            synth: new ShellStep("Synth", {
                commands: [ "echo hi" ],
                input: codeSource,
            })
        });
        const stage = new AppStage(this, "stage");
        pipeline.addStage(stage, {
            stackSteps: [{
                stack: stage.stack,
                post: [new ShellStep("integTest", {
                    commands: [ "echo hi" ],
                    envFromCfnOutputs: { "INPUT": stage.stack.output },
                })]
            }]
        });
    }
}

class AppStage extends Stage {
    public readonly stack: AppStack;
    constructor(scope: Construct, id: string) {
        super(scope, id);
        this.stack = new AppStack(this, "app"); 
    }
}

class AppStack extends Stack {
    public readonly output: CfnOutput;
    constructor(scope: Construct, id: string) {
        super(scope, id);
        this.output = new CfnOutput(this, "out", { value: "hi" });
    }
}
```
### What did you expect to happen?

no errors on deployment

### What actually happened?

deployment fails, since the deploy step does not define a variable namespace for the pipeline

### CDK CLI Version

1.130.0

### Node.js Version

v12.20.0

### OS

Mac 10.15.7

### Language

Typescript

### Language Version

TS: 4.4.4

### Other information

bug is in https://github.com/aws/aws-cdk/blob/73eb185ab7c11b50511c671e02cf2039c297bd61/packages/%40aws-cdk/pipelines/lib/helpers-internal/pipeline-queries.ts#L20
it ignores the stackSteps

**Comment by bmmin** [comment]
I wanted to send in a pull request, but the current source code fails on 
> @aws-cdk/aws-applicationautoscaling: FAIL test/schedule.test.js (11.287 s)
@aws-cdk/aws-applicationautoscaling:   ● at › test using at with a specific Date
@aws-cdk/aws-applicationautoscaling:     expect(received).toEqual(expected) // deep equality
@aws-cdk/aws-applicationautoscaling:     Expected: "at(2021-11-26T00:00:00)"
@aws-cdk/aws-applicationautoscaling:     Received: "at(2021-11-25T23:00:00)"
@aws-cdk/aws-applicationautoscaling:       66 | describe('at', () => {
@aws-cdk/aws-applicationautoscaling:       67 |   test('test using at with a specific Date', () => {
@aws-cdk/aws-applicationautoscaling:     > 68 |     expect(appscaling.Schedule.at(new Date(2021, 10, 26)).expressionString).toEqual('at(2021-11-26T00:00:00)');
@aws-cdk/aws-applicationautoscaling:          |                                                                             ^
@aws-cdk/aws-applicationautoscaling:       69 |   });
@aws-cdk/aws-applicationautoscaling:       70 | });
@aws-cdk/aws-applicationautoscaling:       71 |
@aws-cdk/aws-applicationautoscaling:       at Object.<anonymous> (test/schedule.test.ts:68:77)

I assume it is related to the dst changes recently, but nothing to do with this issue.

**Comment by rix0rrr** [comment]
Feel free to send in the PR nevertheless! (And don't forget to add a test)

Thanks!

**Comment by bmmin** [comment]
I did send a PR, is there anything else I need to follow up on?

**Comment by bmmin** [comment]
@rix0rrr any other action needed from my side?
