### ISSUE TITLE
(aws-iam): AmazonDMSVPCManagementRole does not exist or is not attachable

### ISSUE THREAD

**Issue by jpSimkins** [aws/aws-cdk#17278]
### What is the problem?

When trying to add the AWS managed policy `AmazonDMSVPCManagementRole` to a user, I am given this error:
```
12:08:58 PM | CREATE_FAILED        | AWS::IAM::User     | User00B015A1
Policy arn:aws:iam::aws:policy/AmazonDMSVPCManagementRole does not exist or is not attachable. (Service: AmazonIdentityManagement; Status Code: 404; Error Code: NoSuchEntity; Request ID: f934b59c-dcdd-4275-b3f9-ee3841752fa7; Proxy:
null)
```

### Reproduction Steps

```typescript
import { App, Stack, StackProps, Tags } from '@aws-cdk/core';
import { ManagedPolicy, User } from '@aws-cdk/aws-iam';

export class ExampleUser extends Stack {
  /**
   * The user object
   */
  public readonly user: User;

  constructor(scope: App, id: string, props?: StackProps) {
    super(scope, id, props);
    this.user = new User(this, 'User', {
      userName: `example-user`,
    });
    // Attach managed policies
    this.user.addManagedPolicy(
      ManagedPolicy.fromAwsManagedPolicyName('AmazonDMSVPCManagementRole'),
    );
  }
}

```

### What did you expect to happen?

I expected the role to be attached to the user

### What actually happened?

```
12:08:58 PM | CREATE_FAILED        | AWS::IAM::User     | User00B015A1
Policy arn:aws:iam::aws:policy/AmazonDMSVPCManagementRole does not exist or is not attachable. (Service: AmazonIdentityManagement; Status Code: 404; Error Code: NoSuchEntity; Request ID: f934b59c-dcdd-4275-b3f9-ee3841752fa7; Proxy:
null)
```

### CDK CLI Version

1.124.0 (build 65761fe)

### Framework Version

1.124.0

### Node.js Version

v14.17.4

### OS

`Linux Zeus 5.11.0-34-generic #36~20.04.1-Ubuntu SMP Fri Aug 27 08:06:32 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

### Language

Typescript

### Language Version

Typescript (Version 4.1.5)

**Comment by rix0rrr** [comment]
> Some managed policy names start with "service-role/", some start with "job-function/", and some don't start with anything. Include the prefix when constructing this object.

[source](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-iam.ManagedPolicy.html#static-fromwbrawswbrmanagedwbrpolicywbrnamemanagedpolicyname)

Try:

```ts
ManagedPolicy.fromAwsManagedPolicyName('service-role/AmazonDMSVPCManagementRole')
```

**Comment by jpSimkins** [comment]
Thanks @rix0rrr . This is the first time I ran into this issue so I was not aware. Thanks for your help. I did get it working using the arn but I like your way better.
