### ISSUE TITLE
Code.fromAsset generate UnhandledPromiseRejectionWarning when stack run in async function

### ISSUE THREAD

**Issue by guilhemeyraud** [aws/aws-cdk#17289]
### What is the problem?

When `Code.fromAsset` is used to load an asset that do not exist in a Stack run in an async function, the Stack do not fail but print a `UnhandledPromiseRejectionWarning` and continue the deployment. This ultimately result with the complete deletion of the stack.

### Reproduction Steps

You can reproduce with the following code
```javascript
import * as cdk from '@aws-cdk/core';
import { Code, Function, Runtime } from "@aws-cdk/aws-lambda";

class TestCdkStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props: cdk.StackProps) {
    super(scope, id, props);

    new Function(this, "randomLambdaFunction", {
      functionName: `randomLambdaFunction`,
      code: Code.fromAsset("randomLambdaFunction"),
      handler: 'LambdaEntryPoint::handleRequest',
      runtime: Runtime.JAVA_8,
    });

  }
}

async function async_run(){ // Do not fail when it should 
  const app = new cdk.App();
  new TestCdkStack(app, 'TestCdkStack', { env: { region: 'us-east-1', account: process.env.CDK_DEFAULT_ACCOUNT } });
}
function run(){// Fail as expected with
  const app = new cdk.App();
  new TestCdkStack(app, 'TestCdkStack', { env: { region: 'us-east-1', account: process.env.CDK_DEFAULT_ACCOUNT } });
}

async_run() 

```

### What did you expect to happen?

I need to fetch data asynchronously before running the stack, i expect the stack to fail if any error occur.

### What actually happened?

the stack deployment continued with an empty stack and removed all resources previously deployed.

### CDK CLI Version

1.118.0

### Node.js Version

v14.14.0 

### OS

MacOS Monterey

### Language

Typescript

### Language Version

TypeScript (3.9.7)

**Comment by peterwoodworth** [comment]
Hey @guilhemeyraud, thanks for submitting this

I'm not able to reproduce this, I still receive a failure during synth following your exact steps. Are you able to reproduce this consistently from a fresh build?

**Comment by peterwoodworth** [comment]
Also - the details of what you're doing that's async isn't clear. Could you explain that for me a little bit?

**Comment by guilhemeyraud** [comment]
upgrading to node16 fixed the issue.
I tried with a new clean install and still got the issue with node < 15.

**Comment by peterwoodworth** [comment]
great, glad that fixed your problem!
