### ISSUE TITLE
[sns] support encrypted topics

### ISSUE THREAD

**Issue by brianmlima** [aws/aws-cdk#1729]
TopicProps.builder() should have a withKmsMasterKeyId(String keyArn) method for setting the KmsMasterKeyId property. This would add support encrypted topics.

Currently the work around is to drop into the Resource and set the property but this was very hard to get to when first learning how to use the library. 
```
    public static void setKmsMasterKeyId(final Topic topic, final EncryptionKey encryptionKey){
        Resource cfnTopic = (Resource) topic.getNode().findChild("Resource");
        cfnTopic.addPropertyOverride("KmsMasterKeyId", encryptionKey.getKeyArn());
    }
```
Adding the property to TopicProps.builder() woule eliminate the need to drop into the Resource and make it easier to get off the ground for users new to the tool.

**Comment by jackm-ts** [comment]
@nija-at Any update on this?

**Comment by nija-at** [comment]
@jackm-ts - I haven't had a chance to work on this. 

However, this can be something you or someone else can send us a PR on.
This would need a change to add another property to [`TopicProps`](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-sns/lib/topic.ts#L8) of type `IKey` and use this when creating the [`CfnTopic`](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-sns/lib/topic.ts#L53)
