### ISSUE TITLE
nodejs downgraded to v12

### ISSUE THREAD

**Issue by rittneje** [aws/aws-cdk#17309]
### What is the problem?

We are upgrading from v1.118.0 to v1.130.0. We noticed as part of the upgrade that some of the implicit lambdas were downgraded from the nodejs 1.14 runtime to the 1.12 runtime. In particular, this is happening for the CertificateRequestorFunction lambda created via `aws_certificatemanager.DnsValidatedCertificate`, and the framework-onEvent lambda created via `custom_resources.Provider`.

I don't know which module is responsible for these lambda runtimes.

### Reproduction Steps

1. Deploy a stack with `aws_certificatemanager.DnsValidatedCertificate` and `custom_resources.Provider` using CDK v1.118.0.
2. Deploy the stack again with CDK v1.130.0 and look at the diff.

### What did you expect to happen?

The lambda runtime should have remained at nodejs 14.

### What actually happened?

It downgraded to nodejs 12.

### CDK CLI Version

1.130.0

### Node.js Version

16.13.0

### OS

Alpine 3.14

### Language

Python

### Language Version

3.9

**Comment by peterwoodworth** [comment]
This was done intentionally because some regions don't support v14 yet, so this allows for wider range of coverage https://github.com/aws/aws-cdk/pull/16818

Do you have any problems with this?

**Comment by peterwoodworth** [comment]
This wasn't detected as part of the changelog because it was labeled as a chore. So the submitter of that PR didn't think that our end users would need to know about this change. I assume you disagree, has this change affected you?

**Comment by rittneje** [comment]
It affects us because we evaluate the CDK diff during each upgrade to make sure it is expected. Since this change was not mentioned, it was very surprising behavior.

**Comment by peterwoodworth** [comment]
I see, thank you for the feedback @rittneje, it's much appreciated

I'm not sure there's much, if anything we can do about this particular change now, but I'll discuss this with the team to let them know changes like these are wanted to be seen in the changelog

**Comment by markusl** [comment]
@peterwoodworth this is also an issue for us as we are in the progress of moving to officially supported NodeJs versions (as mandated by company policy).

Do you know exactly which regions do not support NodeJs 14 (released in 2019) and what would be the schedule for updating the AWS CDK to NodeJs 14?

Br,
Markus

**Comment by peterwoodworth** [comment]
I'm not sure what the schedule for that is - but if you need to use 14 here you can use [escape hatches](https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html) on the constructs which create these lambdas to modify the lambda.

**Comment by gkumar7** [comment]
Stumbled on this issue as I see the latest cdk version is still using [NodeJS 12.x](https://github.com/aws/aws-cdk/blob/cea1039e3664fdfa89c6f00cdaeb1a0185a12678/packages/%40aws-cdk/aws-certificatemanager/lib/dns-validated-certificate.ts#L102). With NodeJS v12.x EOL, could we at least add a parameterized way to update DnsValidatedCertificate to use NodeJS 14.x?

**Comment by peterwoodworth** [comment]
You aren't linking to the latest code @gkumar7. It uses v14, we don't use v12 anymore in any of our functions https://github.com/aws/aws-cdk/blob/0f002e2009bbab2e10c08cdf908c5091ba61b754/packages/%40aws-cdk/aws-certificatemanager/lib/dns-validated-certificate.ts#L110
