### ISSUE TITLE
(assertions): assertions are not present for v1.130.0

### ISSUE THREAD

**Issue by frak** [aws/aws-cdk#17310]
### What is the problem?

 I am trying to follow the [advanced topics in the CDK workshop](https://cdkworkshop.com/30-python/70-advanced-topics/100-construct-testing/1000-assertion-test.html) and am running into a problem similar to issue #16797

When I try to add the assertions module and run pytest it fails as `assertions` is no longer part of the module. I understand that this has been moved out for v2 of the CDK, but that shouldn't affect v1.130 should it?

### Reproduction Steps

Create a test file as per the docs...
```python
from aws_cdk import (
        core,
        aws_lambda as _lambda,
        assertions
    )
from cdk_workshop.hitcounter import HitCounter
import pytest


def test_dynamodb_table_created():
    stack = core.Stack()
    HitCounter(stack, "HitCounter",
            downstream=_lambda.Function(stack, "TestFunction",
                runtime=_lambda.Runtime.NODEJS_14_X,
                handler='hello.handler',
                code=_lambda.Code.from_asset('lambda')),
    )
    template = assertions.Template.from_stack(stack)
    template.resource_count_is("AWS::DynamoDB::Table", 1)
```
Run `pytest`

### What did you expect to happen?

Test to pass

### What actually happened?

```shell
___________________ ERROR collecting tests/unit/test_cdk_workshop_stack.py ____________________
ImportError while importing test module '/path/to/dev/cdk_workshop/tests/unit/test_cdk_workshop_stack.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/test_cdk_workshop_stack.py:1: in <module>
    from aws_cdk import (
E   ImportError: cannot import name 'assertions' from 'aws_cdk' (unknown location)
```

### CDK CLI Version

1.130.0 (build 9c094ae)

### Node.js Version

v16.13.0

### OS

Ubuntu Budgie 20.04

### Language

Python

### Language Version

3.8.10

**Comment by peterwoodworth** [comment]
Hey @frak,

You have to install the assertions module independently. `pip install aws-cdk.assertions` will allow you to use the assertions module

**Comment by peterwoodworth** [comment]
We will update the workshop to make this more clear, thank you for letting us know about this oversight :)

**Comment by peterwoodworth** [comment]
workshop is updated, thanks again!
