### ISSUE TITLE
(servicecatalog): Optional fields for `CloudFormationProduct` do not synth in template for python

### ISSUE THREAD

**Issue by arcrank** [aws/aws-cdk#17315]
### What is the problem?

According to the generated docs for python (and also the analogous ts experience) , we should be able to create a product like so: 

``` python
# Example automatically generated. See https://github.com/aws/jsii/issues/826
product = servicecatalog.CloudFormationProduct(self, "MyFirstProduct",
    product_name="My Product",
    owner="Product Owner",
    product_versions=[{
        "product_version_name": "v1",
        "cloud_formation_template": servicecatalog.CloudFormationTemplate.from_url("https://raw.githubusercontent.com/awslabs/aws-cloudformation-templates/master/aws/services/ServiceCatalog/Product.yaml")
    }
    ]
)
```

The `product_versions` field takes a list of these dict objects.  The fields `product_version_name` and `product_version_description` are both optional.  However, if even if you include them they do not appear in the synthed template: 

``` yaml
      ProvisioningArtifactParameters:
          DisableTemplateValidation: false
          Info:
            LoadTemplateFromURL: https://www.google.com
```

Somehow in these fields being optional they are getting cast to `None`  somewhere.  There is a workaround which is to initialize background class `CloudFormationProductVersion` directly like so:

``` python
product_versions=[
  sc.CloudFormationProductVersion(
    cloud_formation_template = sc.CloudFormationTemplate.from_url('https://www.example.com/file.yaml'),
    product_version_name = 'test',
    description = 'test_description',
  ),
]
```

Need to figure out why the optional fields are somehow being discarded from the template so that passing in fields works as expected.  

### Reproduction Steps

Included above, but copy from the README example:

``` python
# Example automatically generated. See https://github.com/aws/jsii/issues/826
product = servicecatalog.CloudFormationProduct(self, "MyFirstProduct",
    product_name="My Product",
    owner="Product Owner",
    product_versions=[{
        "product_version_name": "v1",
        "cloudFormationTemplate": servicecatalog.CloudFormationTemplate.from_url("https://raw.githubusercontent.com/awslabs/aws-cloudformation-templates/master/aws/services/ServiceCatalog/Product.yaml")
    }]
)
```

Will not include the name field in template

### What did you expect to happen?

Expected `product_version_name` and `product_version_description` fields to be reflected in the generated template

### What actually happened?

The fields did not generate in the template at all. 

### CDK CLI Version

1.130.0

### Node.js Version

12.22.3

### OS

Mac

### Language

Python

### Language Version

3.7

**Comment by peterwoodworth** [comment]
The workaround you mention here is actually the intended way to do things! [According to our docs](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_servicecatalog/CloudFormationProductProps.html#aws_cdk.aws_servicecatalog.CloudFormationProductProps.product_versions), the `product_versions` property wants a list of `CloudFormationProductVersion`s. 

Our docs in the module readme get generated incorrectly here, and I see you've already made a comment on the relevant issue so thank you. I got confused on this last month as well as another customer

Is there anything else you need help with here? I think your comment being left on the other issue is sufficient, but let me know if there's anything else that you think can be done beyond fixing the automatically generated docs

**Comment by arcrank** [comment]
I don't think this is the intended behavior though is it?  We want objects that are exposed to end users to usually translate directly to a construct/resource in the downstream template.  The `CloudFormationProductVersion` is mainly just an interface to assist with type checking the various fields. Is this something that is sort of lost in python since we don't have interfaces? 

Is there an explanation for why in the jsii generated python code the optional fields seem to become nullified?

**Comment by arcrank** [comment]
@peterwoodworth   I noticed in new versions the documentation is correct, not sure if this is from just jsii improvements?  My one question though is that if it's a rule that documentation is not compiled for experimental branches and only stable ones.  Knowing why/when docs are autogenerated would help us in being cognizant of discrepancies.

**Comment by peterwoodworth** [comment]
Sorry for not getting back to you @arcrank, JSII and our non-typescript languages aren't something I've spent much time in. 

@skinny85 I'd appreciate if you could chime in here

**Comment by skinny85** [comment]
Sample code is translated for all modules, both stable and experimental ones.

**Comment by skinny85** [comment]
@arcrank are we good here, or is there anything else to do on this issue?

**Comment by arcrank** [comment]
Yeah we can close this, the newer docs have correct syntax.
