### ISSUE TITLE
(aws-eks): support bottlerocket managed nodegroup

### ISSUE THREAD

**Issue by pahud** [aws/aws-cdk#17324]
### Description

EKS managed nodegroup now supports bottlerocket in AMD64 and ARM64.

https://aws.amazon.com/tw/blogs/containers/amazon-eks-adds-native-support-for-bottlerocket-in-managed-node-groups/

### Use Case

Allow user to create bottlerocket MNG.

### Proposed Solution

update the AmiType enum.

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by jasonumiker** [comment]
With the EKS Managed AMI you can specify/pin a version so that triggering a mangaed node group upgrade is deliberate. Is there a way to pin a particular version with this? https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-eks.Nodegroup.html#releaseversion
