### ISSUE TITLE
(certificatemanager): stack loses track of DnsValidatedCertificate

### ISSUE THREAD

**Issue by williamputraintan** [aws/aws-cdk#17349]
### What is the problem?

After `aws_certificatemanager.DnsValidatedCertificate` has been deployed and modifying `aws_certificatemanager.DnsValidatedCertificate` while it still has a `pending` status it will just create a new one and old ones are being forgotten. As a result, a lot of certificates are created but does not belong to a cdk stack

### Reproduction Steps

1. Construct `aws_certificatemanager.DnsValidatedCertificate` with a pending status (Reason for this, it needs manual validation from a different account, typo on alternative domain name)
2. Modify the `aws_certificatemanager.DnsValidatedCertificate` (for example add a new alternative domain name, or fix typo domain name)

### What did you expect to happen?

The previous certificate is deleted and is replaced with the new certificate with the new configuration. Or at least a warning of the previous certificate is not deleted.

### What actually happened?

New certificates keep on regenerating with the old one is not tracked with the cdk anymore.

### CDK CLI Version

1.130.0 (build 9c094ae)

### Node.js Version

N/A

### OS

Windows

### Language

Python

**Comment by njlynch** [comment]
Thanks for this bug report. It does indeed look like the custom resource handler always requests a new certificate (for a create/update), without deleting any existing certificates. Given each update -- sans metadata like tags -- _requires_ a new certificate, this is a likely scenario and should probably be addressed.

In the meantime, I always strongly recommend you use the `Certificate` construct if you can; the only valid reason to use `DnsValidatedCertificate` is for cross-region use cases.

**Comment by ChrisLane** [comment]
@njlynch A lot of people use `DnsValidatedCertificate` over `Certificate` because of the extra properties available for the construct.
It didn't seem clear to me in the docs that `Certificate` should be preferred.
