### ISSUE TITLE
(aws-lambda): DockerImageCode hash changes on every deploy when using AssetStaging as code source

### ISSUE THREAD

**Issue by FredrikMeyer** [aws/aws-cdk#17355]
### General Issue

AssetStaging uses whole path to make hash

### The Question

We have a CDK app that uses the AssetStaging construct to move relevant folders to a staging folder, and then we use DockerImageCode to create a lambda function referencing the copied folder. So something like this:

```python
        self.assets= AssetStaging(
            self,
            "CopiedAsset",
            source_path=str(Path(".").absolute().parent.parent / "python_packages"),
            exclude=[
                "exclude_1/**/*",
                "exclude_2/**/*",
        )

        self.lambda = _lambda.DockerImageFunction(
            self,
            "Lambda",
            code=_lambda.DockerImageCode.from_image_asset(
                directory=self.assets.absolute_staged_path,
                file="lambda/Dockerfile",
                cmd=["/var/task/lambda/handler.handler"],
                exclude=docker_exclude_dirs,
            ),
        )
```

However, from the source code of CDK ([here][1]), it looks like the path name of the staged directory (`self.assets.absolute_staged_path`) is part of the source hash from the `DockerImageFunction`, meaning that the Docker image is redeployed on every deploy (since the directory name of `self.assets` is random)

Is there any way around this?

  [1]: https://github.com/aws/aws-cdk/blob/ab627c69e9edac82b1fd07d2c9ee1b05f7dc3166/packages/%40aws-cdk/core/lib/fs/fingerprint.ts#L28

### CDK CLI Version

1.130

### OS

Amazon Linux (running on CodeBuild)

### Language

Python

### Language Version

Python 3.8

### Other information

(I made a question on Stackoverflow (https://stackoverflow.com/questions/69708386/dockerimagecode-hash-changes-on-every-deploy-when-using-assetstaging-as-code-sou), but it didn't get any attention)

**Comment by peterwoodworth** [comment]
Hey @FredrikMeyer, thanks for opening this issue. I haven't seen this kind of hashing inconsistency before

> since the directory name of `self.assets` is random

Can you clarify what you mean by this? Thanks

**Comment by FredrikMeyer** [comment]
@peterwoodworth Sorry for the late reply.

> Can you clarify what you mean by this? Thanks

I might be wrong. I tried to recreate this issue locally, but am unable to at the moment.

What happens though, is that whenever we do some changes, all the Docker lambdas are updated in CodeBuild, even though there are no code changes.

Our setup is something like this:

```python
class TempStack(cdk.Stack):
    def __init__(self, scope: Construct, construct_id: str, stage: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        api_endpoint_code = AssetStaging(
            self,
            "APIEndpointAsset",
            source_path=str(Path(".").absolute().parent.parent / "python_packages"),
            exclude=[
                "ignored_1/**/*",
                "ignored_2/**/*",
                "ignored_3/**/*",
                "**/*/docs/**/*",
                "**/*/tests/**/*",
                ".mypy_cache",
                ".pytest_cache",
            ],
        )

        temp_func = _lambda.DockerImageFunction(
            self,
            "APIEndpointLambda",
            code=_lambda.DockerImageCode.from_image_asset(
                directory=api_endpoint_code.absolute_staged_path,
                file="rest_api/Dockerfile",
                build_args={"PACKAGE_VERSION": "0.0.1"},
                ignore_mode=IgnoreMode.GLOB,
            ),
            memory_size=500,
            timeout=Duration.minutes(1),
            environment={
                "POWERTOOLS_SERVICE_NAME": "audio_api",
                "LOG_LEVEL": "INFO",
            }
        )
```

It seems that whatever is changed in the Python-packages directory, the lambda function is built and deployed again.

Could it be related to Docker caching on CodeBuild? Should we cache the cdk.out directory?

We do the deploy by running `cdk deploy MyStack` in a CodeBuild instance.

**Comment by FredrikMeyer** [comment]
Some more context on this one @peterwoodworth 

I did some more digging, and it seems like the problem is that the Docker image is different for each build, and it happens already in the `COPY` stage. Our Dockerfile looks something like this:

```
FROM public.ecr.aws/lambda/python:3.8 as build-image

COPY . ./packages/

RUN pip3 install \
    --no-cache-dir \
    --target ${LAMBDA_TASK_ROOT} \
    ./packages/package_1 \
    ./packages/package_2 \
    ./packages/package_3

COPY ./package_1/main.py ${LAMBDA_TASK_ROOT}

# Enable Lambda Container Insights
# https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Lambda-Insights-Getting-Started-docker.html
RUN curl -O https://lambda-insights-extension.s3-ap-northeast-1.amazonaws.com/amazon_linux/lambda-insights-extension.rpm && \
    rpm -U lambda-insights-extension.rpm && \
    rm -f lambda-insights-extension.rpm

CMD ["main.handler"]
```

I guess one probably can get around this by setting up some Docker layer caching on the CodeBuild instance, but that feels like a workaround.

**Comment by peterwoodworth** [comment]
Sorry for the delay in response here @FredrikMeyer, and thanks for following up.

I'm honestly not too familiar with how the CDK handles hashing - @jogold @eladb do you guys have any input here?

**Comment by jogold** [comment]
@FredrikMeyer you shouldn't use the `AssetStaging` class here because this leads to a "double" staging of your asset. Can you detail why you are not directly referencing your asset in `from_image_asset()`?

**Comment by FredrikMeyer** [comment]
The folder where the Python packages are contain a lot of unnecessary packages, so I was experimenting with building the Docker image in a context where no unnecessary packages are.

However, I ended up removing the AssetStaging step after I made this issue.

So now the whole thing looks like this:
```python 
exclude_list = [
    "package_2/**/*",
    "package_3/**/*",
    "**/*/docs/**/*",
    "**/*/tests/**/*",
    ".mypy_cache",
    ".pytest_cache",
]

self.my_lambda = _lambda.DockerImageFunction(
            self,
            "MyLambda",
            code=_lambda.DockerImageCode.from_image_asset(
                directory=str(Path(".").absolute().parent.parent / "python_packages"),
                file="some_python_package/Dockerfile",
                cmd=["/var/task/some_python_package/main.handler"],
                ignore_mode=IgnoreMode.GLOB,
                exclude=exclude_list,
            )
        )
```

And Dockerfile
```dockerfile
FROM public.ecr.aws/lambda/python:3.8 as build-image

# Enable Lambda Container Insights
# https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Lambda-Insights-Getting-Started-docker.html
RUN curl -O https://lambda-insights-extension.s3-ap-northeast-1.amazonaws.com/amazon_linux/lambda-insights-extension.rpm && \
    rpm -U lambda-insights-extension.rpm && \
    rm -f lambda-insights-extension.rpm

COPY ./ ./packages/

RUN pip3 install \
    --no-cache-dir \
    --target ${LAMBDA_TASK_ROOT} \
    ./packages/some_dep \
    ./packages/some_package

```
It is hard to guess which Docker layer is different from the logs in CodeBuild. It always seem to push two layers, so my guess is that it is the COPY stage that causes the invalidation.

**Comment by jogold** [comment]
The hash of your Docker asset is calculated based on the Docker context: Dockerfile and directory content (excludes taken into account). If something changes there the hash changes and CDK will issue a `docker build` in your CI.

You should make sure that the content of `str(Path(".").absolute().parent.parent / "python_packages")` "minus" `exclude_list` is the same locally and in CI.

**Comment by FredrikMeyer** [comment]
Thanks for your answer.

Hmm, I'm not sure if that is true. Even if no changes has been made in the `python_packages` directory, the lambdas are rebuilt. (for example, when someone only changes documentation (which is a directory parallell to the `python_packages` directory)

This only happens in the CI, btw. On my Mac, it only builds once. Also, we have a few lambdas that are not Docker containers, and they are only redeployed on source changes, as expected.

**Comment by jogold** [comment]
Here's the code calculating the hash https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/core/lib/fs/fingerprint.ts

What's in `python_packages`?

**Comment by FredrikMeyer** [comment]
`python_packages` look like this

```
.
|-package_1
|-package_2
```

Where all are Python packages. And so on. 

Though this problem only happens when using `DockerImageFunction`, not when using regular Python lambdas.

How does the cdk check the previous hash for changes? Is it stored somewhere?

**Comment by jogold** [comment]
> `python_packages` look like this

and what's in `package_1` then? what type of content?

> How does the cdk check the previous hash for changes? Is it stored somewhere?

it checks if the same hash exists in ECR (for Docker asset) or S3 (for S3 assets).

Docker https://github.com/aws/aws-cdk/blob/b284ebae0117960dfc9ad10ea0b6c51f81443b69/packages/cdk-assets/lib/private/handlers/container-images.ts#L105-L108
S3 https://github.com/aws/aws-cdk/blob/b284ebae0117960dfc9ad10ea0b6c51f81443b69/packages/cdk-assets/lib/private/handlers/files.ts#L43-L46

**Comment by FredrikMeyer** [comment]
Thank for your question, it led me to Google stuff. It miiight be that the problem is that `pip install .` creates a build directory on every build (see f.ex https://github.com/pypa/pip/issues/8165) and also a `package_1.egg-info` directory, which contains a `PKG-INFO` file:
```
>> cat PKG-INFO
Metadata-Version: 2.1
Name: connector-api
Version: 0.14.54
Summary: sdfghj sfgdf 
Home-page: UNKNOWN
Author: XAL
License: UNKNOWN
Platform: UNKNOWN
Provides-Extra: test

UNKNOWN
```
Here `Version` changes on every deploy...

So maybe if I also ignore `build` and this directory, there shouldnt be any more things that changes on every build.

So I guess adding 
```
    "**/*.egg-info/**",
    "**/build/**",
```
two my list of ignored globs miiight fix the issue. I'll try and report soon.

**Comment by FredrikMeyer** [comment]
@jogold So an update on this: basically your question led me to learn that `pip install .` creates files on build (and we that before running `cdk deploy` in the CI.

Ignoring those extra folders helped.

So thanks a lot for the hint at what to look for, and sorry for your time spent. 

I will close this issue (and again, thanks for the help!).
