### ISSUE TITLE
Feature request: alias `cdk` binary to `aws-cdk`.

### ISSUE THREAD

**Issue by ccurrie-amzn** [aws/aws-cdk#1735]
I don't install the `aws-cdk` package globally to avoid version conflicts. To create a new project, I use `npx`, but because the binary doesn't match the package name, the command is more complicated:

```
npx -p aws-cdk cdk init ...
```

If the binary name was `aws-cdk` , then I could run:

```
npx aws-cdk init ...
```

and NPM would figure it out for me.

A separate `create-cdk-app` tool (as per #871) would be preferable, but this would be a quick and dirty workaround.

**Comment by eladb** [comment]
Sounds good to me. Should be easy to add

**Comment by eladb** [comment]
You should be able to just use `npx cdk`. We've aliased the npm module "cdk" with "aws-cdk".
