### ISSUE TITLE
(aws-rds): DB Backups not supported on a read replica for engine postgres

### ISSUE THREAD

**Issue by zarr12steven** [aws/aws-cdk#17356]
### General Issue

based on #16934 

### The Question

This issue-based on #16934 

I just want to upgrade my instance type from `instanceType: ec2.InstanceType.of(ec2.InstanceClass.T3, ec2.InstanceSize.SMALL)` to `instanceType: ec2.InstanceType.of(ec2.InstanceClass.T3, ec2.InstanceSize.LARGE)`, and not workable.

probably if I want to change to other different instance types, it maybe will show the same error messages too.

### CDK CLI Version

1.130.0 (build 9c094ae)

### Framework Version

1.130.0 (build 9c094ae)

### Node.js Version

v14.18.0

### OS

Ubuntu 20.04.3 LTS

### Language

Typescript

### Language Version

typescript@3.9.10

**Comment by skinny85** [comment]
Hey @zarr12steven,

thanks for opening the issue. Would you mind showing your CDK code?

1. First, in the state that you first deployed your Stack.
2. Then, if you could show the change to your CDK that makes the deployment fail with that error?

Thanks,
Adam

**Comment by zarr12steven** [comment]
Hi @skinny85 

thanks for reply this issue, Would you please check this  [gist](https://gist.github.com/zarr12steven/bf3e0c2a928463dbd72f6c904b9dad4d), you can get the all detail, thanks.

**Comment by zarr12steven** [comment]
I use same cdk code  to build the RDS instance type for `instanceType: ec2.InstanceType.of(ec2.InstanceClass.T3, ec2.InstanceSize.SMALL`   it's not work too.

**Comment by jogold** [comment]
@zarr12steven In RDS, backups are not supported for read replicas.

> Don't set the `BackupRetentionPeriod`, `DBName`, `MasterUsername`, `MasterUserPassword`, and `PreferredBackupWindow` properties. The database attributes are inherited from the source DB instance, and backups are disabled for read replicas.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html#cfn-rds-dbinstance-sourcedbinstanceidentifier

![image](https://user-images.githubusercontent.com/12623249/140752654-0a430cca-78dd-410a-af97-3b77bd2a5594.png)

The issue for CDK: the prop `backupRetention` should not be present in `DatabaseInstanceReadReplicaProps`.

**Comment by skinny85** [comment]
@jogold PR deprecating the property, and throwing an error if it was passed? 😃

**Comment by zarr12steven** [comment]
> https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html#cfn-rds-dbinstance-sourcedbinstanceidentifier


Hi, @jogold   I have already tried to follow your suggestion and remove `backupRetention`  in the RDS replica instance, but it seems to still not working. you can see below.

```typescript
    // Create RDS

    const master = new rds.DatabaseInstance(this, 'RDS', {
      instanceIdentifier: 'master,
      vpc,
      vpcSubnets: {
        subnetType: ec2.SubnetType.PRIVATE_WITH_NAT
      },
      engine,
      instanceType: ec2.InstanceType.of(ec2.InstanceClass.T3, ec2.InstanceSize.LARGE),
      securityGroups: [ rdsSG ],
      credentials: rds.Credentials.fromGeneratedSecret('pgadmin'),
      multiAz: false,
      availabilityZone: vpc.availabilityZones[0],
      deletionProtection: false,
      storageType: rds.StorageType.IO1,
      allocatedStorage: 100,
      maxAllocatedStorage: 1000,
      performanceInsightRetention: rds.PerformanceInsightRetention.DEFAULT,
      backupRetention: Duration.days(7),
      storageEncrypted: true,
      copyTagsToSnapshot: true,
    });

    // Create minion RDS of reading replication from a master

    const minion = new rds.DatabaseInstanceReadReplica(this, 'ReadReplica', {
      instanceIdentifier: 'minion',
      vpc,
      vpcSubnets: {
        subnetType: ec2.SubnetType.PRIVATE_WITH_NAT
      },
      sourceDatabaseInstance: master,
      instanceType: ec2.InstanceType.of(ec2.InstanceClass.T3, ec2.InstanceSize.LARGE),
      securityGroups: [ rdsSG ],
      multiAz: false,
      availabilityZone: vpc.availabilityZones[1],
      deletionProtection: false,
      storageType: rds.StorageType.IO1,
      enablePerformanceInsights: true,
      performanceInsightRetention: rds.PerformanceInsightRetention.DEFAULT,
      // backupRetention: Duration.days(7),
      storageEncrypted: true,
 
    });

    // Reference: https://github.com/aws/aws-cdk/issues/17083

    const cfnDb = minion.node.defaultChild as CfnDBInstance
    cfnDb.allocatedStorage = '100';
```

**Comment by jogold** [comment]
It seems that backup are supported after all but only for some engines (https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_ReadRepl.html#USER_ReadRepl.Overview.Differences). It's not supported for PostgreSQL.

Can you try?

```ts
const cfnDb = minion.node.defaultChild as CfnDBInstance
cfnDb.backupRetentionPeriod= 0;
```

maybe it's incorrectly inherited from the source instance by CloudFormation.

**Comment by zarr12steven** [comment]
> It seems that backup are supported after all but only for some engines (https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_ReadRepl.html#USER_ReadRepl.Overview.Differences). It's not supported for PostgreSQL.
> 
> Can you try?
> 
> ```ts
> const cfnDb = minion.node.defaultChild as CfnDBInstance
> cfnDb.backupRetentionPeriod= 0;
> ```
> 
> maybe it's incorrectly inherited from the source instance by CloudFormation.

Hi @jogold  thanks for your reply and help, I already tried it and it works.

```typescript
    // Create RDS

    const master = new rds.DatabaseInstance(this, 'AMS-RDS', {
      instanceIdentifier: 'ams-db-master-1',
      vpc,
      vpcSubnets: {
        subnetType: ec2.SubnetType.PRIVATE_WITH_NAT
      },
      engine,
      instanceType: ec2.InstanceType.of(ec2.InstanceClass.T3, ec2.InstanceSize.LARGE),
      securityGroups: [ rdsSG ],
      credentials: rds.Credentials.fromGeneratedSecret('idtech'),
      multiAz: false,
      availabilityZone: vpc.availabilityZones[0],
      deletionProtection: false,
      storageType: rds.StorageType.IO1,
      allocatedStorage: 100,
      maxAllocatedStorage: 1000,
      performanceInsightRetention: rds.PerformanceInsightRetention.DEFAULT,
      backupRetention: Duration.days(7),
      storageEncrypted: true,
      copyTagsToSnapshot: true,
    });

    // Create minion RDS of reading replication from a master
    const minion = new rds.DatabaseInstanceReadReplica(this, 'ReadReplica', {
      instanceIdentifier: 'ams-db-minion-2',
      vpc,
      vpcSubnets: {
        subnetType: ec2.SubnetType.PRIVATE_WITH_NAT
      },
      sourceDatabaseInstance: master,
      instanceType: ec2.InstanceType.of(ec2.InstanceClass.T3, ec2.InstanceSize.LARGE),
      securityGroups: [ rdsSG ],
      multiAz: false,
      availabilityZone: vpc.availabilityZones[1],
      deletionProtection: false,
      storageType: rds.StorageType.IO1,
      enablePerformanceInsights: true,
      performanceInsightRetention: rds.PerformanceInsightRetention.DEFAULT,
      // backupRetention: Duration.days(7),
      storageEncrypted: true,
 
    });

    // Reference: https://github.com/aws/aws-cdk/issues/17083

    const cfnDb = minion.node.defaultChild as CfnDBInstance
    cfnDb.allocatedStorage = '100';
    cfnDb.backupRetentionPeriod = 0; 
```

**Comment by jogold** [comment]
OK, this means that it should also work with `backupRetention: Duration.days(0)`?

**Comment by zarr12steven** [comment]
Hi @jogold

Yes, it works.

```typescript
    // Create RDS

    const master = new rds.DatabaseInstance(this, 'AMS-RDS', {
      instanceIdentifier: 'master-1',
      vpc,
      vpcSubnets: {
        subnetType: ec2.SubnetType.PRIVATE_WITH_NAT
      },
      engine,
      instanceType: ec2.InstanceType.of(ec2.InstanceClass.T3, ec2.InstanceSize.LARGE),
      securityGroups: [ rdsSG ],
      credentials: rds.Credentials.fromGeneratedSecret('pgadmin'),
      multiAz: false,
      availabilityZone: vpc.availabilityZones[0],
      deletionProtection: false,
      storageType: rds.StorageType.IO1,
      allocatedStorage: 100,
      maxAllocatedStorage: 1000,
      performanceInsightRetention: rds.PerformanceInsightRetention.DEFAULT,
      backupRetention: Duration.days(7),
      storageEncrypted: true,
      copyTagsToSnapshot: true,
    });

    // Create minion RDS of reading replication from a master
    const minion = new rds.DatabaseInstanceReadReplica(this, 'ReadReplica', {
      instanceIdentifier: 'minion-1',
      vpc,
      vpcSubnets: {
        subnetType: ec2.SubnetType.PRIVATE_WITH_NAT
      },
      sourceDatabaseInstance: master,
      instanceType: ec2.InstanceType.of(ec2.InstanceClass.T3, ec2.InstanceSize.LARGE),
      securityGroups: [ rdsSG ],
      multiAz: false,
      availabilityZone: vpc.availabilityZones[1],
      deletionProtection: false,
      storageType: rds.StorageType.IO1,
      enablePerformanceInsights: true,
      performanceInsightRetention: rds.PerformanceInsightRetention.DEFAULT,
      backupRetention: Duration.days(0),
      storageEncrypted: true,
 
    });

    // Reference: https://github.com/aws/aws-cdk/issues/17083

    const cfnDb = minion.node.defaultChild as CfnDBInstance
    cfnDb.allocatedStorage = '100';
    // cfnDb.backupRetentionPeriod = 0; 
```

**Comment by jogold** [comment]
OK I'm not sure what the CDK can do here...

To summarize:
* When left unspecified, the back up retention defaults to 1 day (CF default not CDK)
* Since read replica backups are not supported for PostgreSQL, it fails.
* The `backupRetention` prop is defined in the `DatabaseInstanceNewProps` interface, used both for new and read replica instances
* Changing the default for this prop would be breaking and doesn't make sense.

@skinny85 what do you think? improve doc string?

**Comment by skinny85** [comment]
Can we add a concept of "this engine supports setting backup retention", and make it `true` for all engines except Postgres, and this way validate this at build time?

**Comment by jogold** [comment]
> Can we add a concept of "this engine supports setting replica backups", and make it `true` for all engines except Postgres, and this way validate this at build time?

How about having a special default value of `Duration.days(0)` for Postgres read replicas for `backupRetention`? This way if at some point RDS adds automatic backups for Postgres users won't be blocked with code throwing?

**Comment by skinny85** [comment]
> > Can we add a concept of "this engine supports setting replica backups", and make it `true` for all engines except Postgres, and this way validate this at build time?
> 
> How about having a special default value of `Duration.days(0)` for Postgres read replicas for `backupRetention`? This way if at some point RDS adds automatic backups for Postgres, users won't be blocked with code throwing?

Not sure I understand exactly what you're proposing (where is that `Duration.days(0)` returned from? Are we supposed to check for `Duration(0)` ourselves (it's a "magic value"), or just pass it on to the template? etc.), but sure 🙂. If you want to propose the solution in a PR, I think we can discuss there.

**Comment by jogold** [comment]
> Not sure I understand exactly what you're proposing (where is that `Duration.days(0)` returned from? Are we supposed to check for `Duration(0)` ourselves (it's a "magic value"), or just pass it on to the template? etc.), but sure 🙂. If you want to propose the solution in a PR, I think we can discuss there.

@skinny85  I mean adding a `supportsReadReplicaBackups` prop in `IInstanceEngine` and use it to set the default for backup retention to 0.

But... @zarr12steven actually I cannot reproduce your issue with the following code:
```ts
const vpc = new Vpc(this, 'Vpc');
const instanceType = InstanceType.of(InstanceClass.T4G, InstanceSize.MEDIUM);
const source = new rds.DatabaseInstance(this, 'Source', {
  engine: rds.DatabaseInstanceEngine.postgres({ version: rds.PostgresEngineVersion.VER_13 }),
  backupRetention: Duration.days(5),
  instanceType,
  vpc,
});
new rds.DatabaseInstanceReadReplica(this, 'Replica', {
  sourceDatabaseInstance: source,
  instanceType,
  vpc,
});
```
The backup retention doesn't get inherited from the source instance.
