### ISSUE TITLE
(aws-stepfunction-tasks): dynamoQuery missing/not implemented

### ISSUE THREAD

**Issue by bharrell-rsc** [aws/aws-cdk#17367]
### Description

Stepfunction-tasks exposes Dynamo delete-item, get-item, put-item, update-item, but does not include query. Step-functions clearly support query, because I can create a query task in the AWS web console, but CDK does not have code for it.

### Use Case

I want to use CDK to deploy a step-function which uses a dynamo query task.

### Proposed Solution

Implement a dynamodb query stepfunction task.

### Other information

Not sure if this missing feature was an oversight, or left out due to some technical limitation. I'm not sure where to begin attempting to add this feature myself, but will look into it if time permits.

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by peterwoodworth** [comment]
I can't find documentation for this anywhere; I only see the currently implemented tasks documented.

https://docs.aws.amazon.com/step-functions/latest/dg/connect-ddb.html
https://docs.aws.amazon.com/step-functions/latest/dg/dynamo-iam.html

Regardless of the documentation - I assume that we can do this. You would want to create a new file [here](https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/aws-stepfunctions-tasks/lib/dynamodb) for the new task. I'm not familiar with ASL (or how our stepfunctions module works) so I can't offer much more advice without looking more into it

**Comment by rogerchi** [comment]
In the visual Step Function designer, when you add a DynamoDB Query, it is adding a AWS SDK integration calling the Query API, so this is already possible with the existing module: https://docs.aws.amazon.com/cdk/api/latest/docs/aws-stepfunctions-tasks-readme.html#aws-sdk

**Comment by bharrell-rsc** [comment]
Thank you @rogerchi! Apologies. I'm very new to working with the CDK and was unaware this was a thing. I don't know if an "optimized" integration is still needed, but after reading the docs you linked, I was able to use tasks.CallAwsService() to create the query task in my stepfunction, which covers my needs. I had read that page before, but was only looking at the dynamo section, which omitted query. 
I'll close this issue.
