### ISSUE TITLE
(core): Arn.split behavior on CfnParameter

### ISSUE THREAD

**Issue by dscpinheiro** [aws/aws-cdk#17366]
### General Issue

Odd behavior when the value passed to `Arn.split` is a `CfnParameter.valueAsString`

### The Question

I'm trying to extract the resource name from an Amazon MSK cluster ARN (which follows this format - `arn:${Partition}:kafka:${Region}:${Account}:cluster/${ClusterName}/${UUID}`), and I'm seeing a difference in the `cdk.Arn.split` method if the value comes from a parameter (compared to a `const` string).

Here's what I get if passing the ARN directly:
```typescript
import * as cdk from '@aws-cdk/core';
import * as s3 from '@aws-cdk/aws-s3';

export class MyAppStack extends cdk.Stack {
    constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
        super(scope, id, props);

        new s3.Bucket(this, 'Bucket');

        const clusterArn = `arn:aws:kafka:us-east-1:111122223333:cluster/cluster-name/cluster-uuid`;
        const components = cdk.Arn.split(clusterArn, cdk.ArnFormat.SLASH_RESOURCE_NAME);
        new cdk.CfnOutput(this, 'account', { value: components.account || 'N/A' });
        new cdk.CfnOutput(this, 'arnFormat', { value: components.arnFormat || 'N/A' });
        new cdk.CfnOutput(this, 'partition', { value: components.partition || 'N/A' });
        new cdk.CfnOutput(this, 'region', { value: components.region || 'N/A' });
        new cdk.CfnOutput(this, 'resource', { value: components.resource });
        new cdk.CfnOutput(this, 'resourceName', { value: components.resourceName || 'N/A' });
        new cdk.CfnOutput(this, 'service', { value: components.service });
    }
}
```

| Output key | Output value |
| --- | --- |
| `account` | 111122223333 |
| `arnFormat` | arn:aws:service:region:account:resource/resourceName |
| `partition` | aws |
| `region` | us-east-1 |
| `resource` | cluster |
| `resourceName` | cluster-name/cluster-uuid |
| `service` | kafka |

---

However, if I try to use a parameter, the `resourceName` is incorrect (it doesn't include the `/cluster-uuid`):

> I passed `arn:aws:kafka:us-east-1:111122223333:cluster/cluster-name/cluster-uuid` (same value as previous example) to this stack.

```typescript
import * as cdk from '@aws-cdk/core';
import * as s3 from '@aws-cdk/aws-s3';

export class MyAppStack extends cdk.Stack {
    constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
        super(scope, id, props);

        new s3.Bucket(this, 'Bucket');

        const clusterArn = new cdk.CfnParameter(this, 'ClusterArn', {
            type: 'String',
            allowedPattern: 'arn:(aws[a-zA-Z0-9-]*):([a-zA-Z0-9\\-])+:([a-z]{2}(-gov)?-[a-z]+-\\d{1})?:(\\d{12})?:(.*)',
            constraintDescription: 'Cluster ARN must be in the following format: arn:${Partition}:kafka:${Region}:${Account}:cluster/${ClusterName}/${UUID}'
        });

        const components = cdk.Arn.split(clusterArn.valueAsString, cdk.ArnFormat.SLASH_RESOURCE_NAME);
        new cdk.CfnOutput(this, 'account', { value: components.account || 'N/A' });
        new cdk.CfnOutput(this, 'arnFormat', { value: components.arnFormat || 'N/A' });
        new cdk.CfnOutput(this, 'partition', { value: components.partition || 'N/A' });
        new cdk.CfnOutput(this, 'region', { value: components.region || 'N/A' });
        new cdk.CfnOutput(this, 'resource', { value: components.resource });
        new cdk.CfnOutput(this, 'resourceName', { value: components.resourceName || 'N/A' });
        new cdk.CfnOutput(this, 'service', { value: components.service });
    }
}
```

| Output key | Output value |
| --- | --- |
| `account` | 111122223333 |
| `arnFormat` | arn:aws:service:region:account:resource/resourceName |
| `partition` | aws |
| `region` | us-east-1 |
| `resource` | cluster |
| `resourceName` | cluster-name |
| `service` | kafka |

### CDK CLI Version

1.130.0 (build 9c094ae)

### Node.js Version

v14.17.6

### Language

Typescript

**Comment by peterwoodworth** [comment]
This function is where it creates the arn if it's a token

https://github.com/aws/aws-cdk/blob/9c094aef07ecf99c6a151a27daeacdbe17d83236/packages/%40aws-cdk/core/lib/arn.ts#L345-L350

I'll investigate why this might be happening here

**Comment by peterwoodworth** [comment]
Sorry for the delay here, I've been able to find the cause of this.

https://github.com/aws/aws-cdk/blob/9c094aef07ecf99c6a151a27daeacdbe17d83236/packages/%40aws-cdk/core/lib/arn.ts#L377-L380

The function simply ignores everything after the second slash. There's a warning which alerts us to the fact that the function can't properly handle certain formats, and uses a UUID as an example

https://github.com/aws/aws-cdk/blob/9c094aef07ecf99c6a151a27daeacdbe17d83236/packages/%40aws-cdk/core/lib/arn.ts#L338-L340

This should at the very least be noted in the documentation. It would be best if the `arn.split()` method treated everything after the first slash as the resource name, even if there are additional slashes after that one, but I'm not sure what the limitations are here since I don't know why the function can't handle certain arn formats as tokens

**Comment by ldecaro** [comment]
This is no longer a bug. Instead of using cdk.ArnFormat.SLASH_RESOURCE_NAME you should be using ArnFormat.SLASH_RESOURCE_SLASH_RESOURCE_NAME.
