### ISSUE TITLE
(custom-resources): Permit caller to override the AwsCustomResource Singleton UUID

### ISSUE THREAD

**Issue by micrictor** [aws/aws-cdk#17387]
### Description

When users create an instance of the AwsCustomResource, they should optionally be able to override the default Singleton UUID, effectively allowing them to create multiple Singletons.

### Use Case

If multiple AwsCustomResources are used in a single stack, the individual invocations of the Lambda function can warm-start from a previous invocation.

This can cause issues with permissions if some AwsCustomResources have calls with `assumedRoleArn` specified, as [the global AWS.config.credentials object is modified to attempt to assume the role](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/custom-resources/lib/aws-custom-resource/runtime/index.ts#L173).

In effect, this means that if an invocation `Y` warm-starts from a previous invocation `X` that had an `assumedRoleArn`, invocation `Y` will be running with the credentials for the role specified for invocation `X`.

### Proposed Solution

An optional property `singletonUuid` can be added to [AwsCustomResourceProps](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/custom-resources/lib/aws-custom-resource/aws-custom-resource.ts#L220), with a default value of [`679f53fa-c002-430c-b0da-5b7982bd2287`](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/custom-resources/lib/aws-custom-resource/aws-custom-resource.ts#L364).

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by nicolai-shape** [comment]
The proposed solution seems like the wrong way to go, rather we should fix the underlying issue which is that assumed role credentials are not cleared properly, as discussed in https://github.com/aws/aws-cdk/issues/15425

**Comment by micrictor** [comment]
Makes sense to me, I’ll close this out
