### ISSUE TITLE
(aws-rds): unsupported SqlServerEngineVersion value

### ISSUE THREAD

**Issue by iliapolo** [aws/aws-cdk#17394]
### What is the problem?

Looks like the `SqlServerEngineVersion.VER_14_00_3192_2_V1` is no longer supported? 

I discovered this while trying to run the [`s3-instance`](https://github.com/aws/aws-cdk/blob/v1.130.0/packages/@aws-cdk/aws-rds/test/integ.instance-s3.ts) integration test.

To get passed the problem in our pipeline I switched the test to use `SqlServerEngineVersion.VER_14`, but we should still figure out what's happening here since it seems we are currently offering unsupported version strings. 

### Reproduction Steps

Run this integ test: https://github.com/aws/aws-cdk/blob/v1.130.0/packages/@aws-cdk/aws-rds/test/integ.instance-s3.ts

Make sure to use the `1.130.0` tag and not the latest one, since the test was already changed.

### What did you expect to happen?

Expected the integ test to successfully deploy.

### What actually happened?

Deployment failure:

```console
aws-cdk-rds-instance-s3-integ | 20/34 | 1:18:47 PM | CREATE_FAILED        | AWS::RDS::DBInstance                        | Database (DatabaseB269D8BB) Cannot find version 14.00.3192.2.v1 for sqlserver-se (Service: AmazonRDS; Status Code: 400; Error Code: InvalidParameterCombination; Request ID: 6278edb3-d5c6-4424-9f5c-10ab853d4810; Proxy: null)
        new DatabaseInstance (/Users/epolon/dev/src/github.com/aws/aws-cdk/packages/@aws-cdk/aws-rds/lib/instance.js:386:26)
        \_ Object.<anonymous> (/Users/epolon/dev/src/github.com/aws/aws-cdk/packages/@aws-cdk/aws-rds/test/integ.instance-s3.js:12:1)
        \_ Module._compile (internal/modules/cjs/loader.js:1138:30)
        \_ Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
        \_ Module.load (internal/modules/cjs/loader.js:986:32)
        \_ Function.Module._load (internal/modules/cjs/loader.js:879:14)
        \_ Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
        \_ internal/main/run_main_module.js:17:47
```

### CDK CLI Version

1.130.0

### Framework Version

1.130.0

### Node.js Version

v12.17.0

### OS

Mac OS Mojave

### Language

Typescript, Python, .NET, Java, Go

### Language Version

ALL

### Other information

This is what I could find for a list of supported SQLServer versions in RDS:

https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_SQLServer.html#SQLServer.Concepts.General.VersionSupport

**Comment by skinny85** [comment]
Maybe the version was deprecated by RDS...? We for sure deployed it at some point in the past 🙂.

We need to deprecate this field.
