### ISSUE TITLE
(log): New ResourcePolicy construct not exported from index.js

### ISSUE THREAD

**Issue by matthias-pichler-warrify** [aws/aws-cdk#17402]
### What is the problem?

when importing

```ts
import * as logs from "@aws-cdk/aws-logs";

new logs.ResourcePolicy(...)
```

fails with something like: `logs` does not have property `ResourcePolicy`

And indeed when inspecting the [PR that added it](https://github.com/aws/aws-cdk/pull/17015) the `lib/index.ts` file wasn't updated with the new export 

### Reproduction Steps

```ts
import * as logs from "@aws-cdk/aws-logs";

new logs.ResourcePolicy(this, "Policy");
```

### What did you expect to happen?

The new construct should be export just like others

### What actually happened?

The export was forgotten

### CDK CLI Version

1.131.0

### Framework Version

1.131.0

### Node.js Version

16.9.0

### OS

macOS

### Language

Typescript

**Comment by ryparker** [comment]
Hey @matthias-pichler-warrify 👋🏻 

Thanks for bringing this to our attention.

PR here: https://github.com/aws/aws-cdk/pull/17403
