### ISSUE TITLE
(aws-rds): vpc should be optional in ServerlessCluster

### ISSUE THREAD

**Issue by CorentinDoue** [aws/aws-cdk#17401]
### Description

A VPC is not mandatory to create a AWS Aurora serverless cluster. In [`CfnDBCluster`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-rds.CfnDBCluster.html#construct-props),`DBSubnetGroupName` and `VpcSecurityGroupIds` are optional.

But a VPC is required to create a [`ServerlessCluster`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-rds.ServerlessCluster.html)

The VPC attribute should be optional.

### Use Case

When the `DataAPI` is enabled, it's possible to have a project without any direct access to the Cluster. The cluster don't need to be in a VPC (or if it's in VPC we don't need to know it). It's especially useful for serverless projects which tend to get rid of VPCs.

I wish I could simply write
```ts
const cluster = new rds.ServerlessCluster(this, 'AnotherCluster', {
  engine: rds.DatabaseClusterEngine.AURORA_MYSQL,
  enableDataApi: true,
});

declare const code: lambda.Code;
const fn = new lambda.Function(this, 'MyFunction', {
  runtime: lambda.Runtime.NODEJS_14_X,
  handler: 'index.handler',
  code,
  environment: {
    CLUSTER_ARN: cluster.clusterArn,
    SECRET_ARN: cluster.secret!.secretArn,
  },
});
cluster.grantDataApiAccess(fn);
```

### Proposed Solution

Make the `vpc` parameter optional. When it's `undefined`, don't create any subnet or security group and don't set `DBSubnetGroupName` and  `VpcSecurityGroupIds`

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by skinny85** [comment]
Thanks for opening the issue @CorentinDoue! We encourage community contributions, so if you'd like to open us a Pull Request adding this feature, that would be fantastic - it should be a relatively straightforward change. Our "Contributing" guide: https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md.

Thanks,
Adam
