### ISSUE TITLE
Documentation on required IAM permissions for bootstrapping

### ISSUE THREAD

**Issue by adriangabardo** [aws/aws-cdk#17408]
### Describe your issue?

I am currently working with an Enterprise client where IAM user permissions broadening requires a process of listing out the specific required permissions and reasoning for needing them. 

This makes getting permissions for CDK bootstrapping difficult, as there is no proper documentation listing out the actual permissions needed to bootstrap a new requirement, especially with the newer bootstrapping that needs not only S3 but other permissions such as KMS and SSM.

It would be much appreciated if there could be documentation on what permissions a user is required to have so that they can run `cdk bootstrap...`

**Comment by rix0rrr** [comment]
I'm sure you've by now already gone through the effort of finding this out for yourself.

Can you post your results here?
