### ISSUE TITLE
(@aws-cdk/aws-events-targets): doesn't provide @aws-cdk/assets, breaking dependency of @aws-cdk/aws-codebuild

### ISSUE THREAD

**Issue by okko** [aws/aws-cdk#17416]
### What is the problem?

```
➤ YN0000: @aws-cdk/aws-events-targets@npm:1.130.0 [3a4b1] doesn't provide @aws-cdk/assets, breaking the following requirements:
➤ YN0000: @aws-cdk/aws-codebuild@npm:1.130.0 [f53f9] → 1.130.0 ✘
```

### Reproduction Steps

```
mkdir foobar
cd foobar
npm i -g yarn@berry
yarn set version latest
yarn init
yarn add --dev  @aws-cdk/aws-events-targets
```

### What did you expect to happen?

No warnings on dependencies.

### What actually happened?

aws-events-targets:
  dependencies:
        "@aws-cdk/aws-codebuild": "1.131.0",

aws-codebuild:
  peerDependencies:
    "@aws-cdk/assets": "1.131.0",

but aws-events-targets doesn't list aws-cdk/assets as as a dependency or a peerDependency.

### CDK CLI Version

command not found: cdk

### Node.js Version

v14.18.1

### OS

MacOS

### Language

Typescript

### Language Version

TypeScript

### Other information

"Some packages may have been specified incorrectly with regard to their dependencies - for example with one dependency being missing, causing Yarn to refuse it the access. The packageExtensions fields offer a way to extend the existing package definitions with additional information. If you use it, consider sending a PR upstream and contributing your extension to the plugin-compat database."
https://yarnpkg.com/configuration/yarnrc#packageExtensions

**Comment by ryparker** [comment]
Hey @okko 👋🏻 

Thanks for bringing this to our attention.

PR open here: https://github.com/aws/aws-cdk/pull/17435
