### ISSUE TITLE
(cdk): `npm` publish order

### ISSUE THREAD

**Issue by dehli** [aws/aws-cdk#17422]
### What is the problem?

Recently ran into a bug w/ `cdk` where it was referencing a version that hadn't been published to `npm` yet. I just waited a few minutes and then was able to get around the issue but figured I'd create a ticket in case it's straight forward to change the publish order. 

![image](https://user-images.githubusercontent.com/5856011/140942158-4917d53e-6b0e-4d0b-b57e-489aa5cb0fad.png)

The specific issue seems to be due to the fact that https://www.npmjs.com/package/cdk was published before https://www.npmjs.com/package/aws-cdk.

![image](https://user-images.githubusercontent.com/5856011/140944567-d5191860-2539-4a00-9402-30ebf0792abd.png)

![image](https://user-images.githubusercontent.com/5856011/140944749-4f99b356-697e-4c73-b3e3-3f320512ec3c.png)

### Reproduction Steps

Call `npx cdk` after a new `cdk` version is published but before `aws-cdk` is published.

### What did you expect to happen?

I expect `npx cdk` to not throw the above error. 

### What actually happened?

The error was thrown. 

### CDK CLI Version

1.132.0

### Node.js Version

v16.11.0

### OS

Linux

### Language

Typescript

**Comment by ryparker** [comment]
Hey @dehli 👋🏻 

Thanks for bringing this to our attention. 

This is an interesting problem. I can see how this would cause a headache for a team, especially when using a CD pipeline to automatically install and execute CDK commands. Although this may be a rare scenario, it is a reproducible problem that will continue to affect users.

One workaround for this would be to use `npx aws-cdk <command>` instead.

I've marked this issue as p2 which means that we are unable to work on this immediately however i've marked this for further discussion with the team. We use +1s to help us prioritize our work, and as always we are happy to take contributions if anyone is interested to pick this up and submit a PR (please make sure to follow our [contribution guidelines](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md).) :pray:
