### ISSUE TITLE
(s3-assets): CDK Asset does not include all files by default

### ISSUE THREAD

**Issue by flo-mair** [aws/aws-cdk#17447]
### What is the problem?

When creating a S3 asset, not all files / folders are included.
Example __pycache__

### Reproduction Steps
```python
flink_code_asset = s3_assets.Asset(
            self, 'mskFlinkCodeAsset',
            path=os.path.join('./consumer/flink')
        )
```
### What did you expect to happen?

Including all files

### What actually happened?

Not all files included

### CDK CLI Version

1.127

### Node.js Version

17.0.1

### OS

macOS

### Language

Python

**Comment by otaviomacedo** [comment]
Hi @flo-mair. I'll need more details to be able to reproduce this issue. I created a `BucketDeployment`, using a Python project as the source and everything was uploaded as expected, including the `__pycache__/` folder (I presume this is what you're referring to).
