### ISSUE TITLE
(assets): Non-intrusively adding code to Lambda during CDK Synth

### ISSUE THREAD

**Issue by Dgarc359** [aws/aws-cdk#17462]
### General Issue

Modifying the Asset directory in cdk.out does not deploy changes to Lambda

### The Question

I have been in touch with AWS support / read through much of the documentation in order to find an answer to this question.

**My Use Case**
I have an IAspect which visits each node on a construct and looks for lambdas. I am able to find the reference to the asset which will be deployed to AWS, however, adding code to the the Asset folder in the cdk.out directory does not deploy the added code to the Lambda. This is because during the synthesis process, the lambda's code directory is ran through a hash to check for changes in the bundle that will be sent up, since the code is added post-hash, the bundle sees no changes as being made and doesn't modify the code that will be deployed to the lambda. I haven't found a non-intrusive way to add code to a lambda's bundle without actually modifying the source code. By non-intrusive, I mean, the source code does not need to be touched, the aspect, since it's visiting the node, would somehow be able to add a file to the code bundle that's being created in the cdk.out so that the added code can appear in the Lambda, but doesn't have to manually be added in the source code.

**My Workaround**
My workaround requires synthesis to occur twice (which happens naturally if following the recommended practice of cdk synth -> cdk deploy)
During synth 1: The files are added to the source code
During synth 2: The hash of the asset is re-calculated and the changes are reflected in the deployed bundle

This isn't good enough, because I'm looking for a non-intrusive way to add code to the bundle that will be shipped for the lambda function to use during a single cdk synth, and ideally, this code would not even have to be placed in the source code. I have not been able to find a way to do something like this.

### CDK CLI Version

1.131.0

### Language

Typescript

**Comment by jogold** [comment]
Maybe a use case for asset bundling?

https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/aws-s3-assets#asset-bundling
https://aws.amazon.com/blogs/devops/building-apps-with-aws-cdk/

**Comment by Dgarc359** [comment]
It looks like the asset-bundling behavior gives the control over packaging that I would want. However, due to the constraints of my use case, I don't think that I would be able to implement something like this. I'm attempting to leverage the `.visit()` method provided by IAspects, 

see: https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.IAspect.html

In order to locate all nodes that fit certain criteria (in this case, lambda CfnFunctions and Functions). 

To elaborate on my constraints, I'm trying to make as little modifications to actual source code as possible, currently, only one line to add the aspect I've created is necessary. If possible, I would like to limit any modifications to the nodes within the App to the `.visit()` method provided by the Aspect. Anything that can be done within there is fair game. 

I think I'm hitting a wall on the limitations of this method though. There's no explicit way to modify the code that is being bundled, try as I may. I have been able to find references to where the asset directory is, and have been able to locate the handler source code and add to the directory by processing the node's metadata, but this requires a double synthesis so that the hash can be recalculated, and it is pretty intrusive.

I've testing a little bit with the asset bundling you linked, but can't find a way to modify it inside of the Aspect's visit method. Perhaps my knowledge in implementing this is lacking though.

**Comment by eladb** [comment]
Yes, indeed aspects are executed after the tree is initialized, and assets hash calculation happens during initialization, so you are "too late" if you use aspects to modify the files or control bundling. Generally, aspects are better used to _enforce_ something rather than mutate.

Question - is it possible/practical in your use case to require that users will go through some factory that you provide when they specify the lambda asset location? Something like this:

```ts
import { SpecialCode } from 'your-library';

new lambda.Function(this, 'MyFunction', {
  code: new SpecialCode(__dirname + "/my-handler"),
  // ...
});
```

Then, you can inject your logic up front even before the asset is being initialized. 

In your `bind()` method, you can add a little marker to the `scope` object that you can later use an aspect to enforce that your SpecialCode class was used.

Here's a sketch:

```ts
const marker = Symbol.for("SpecialCode");

export class SpecialCode extends lambda.Code {
  private constructor(dir: string) {
    // mutate index
    const index = readFileSync(dir + "/index.js", "utf-8");
    writeFileSync(dir + "/index.js", "// preamble\n" + index);
  }

  public bind(scope: Construct) {
    Object.defineProperty(scope, marker, { value: true });
  }
}

export class SpecialCodeEnforcement implements IAspect {
  public visit(node: IConstruct) {
    if (node instanceof lambda.Function) {
      if (!(marker in node)) {
        throw new Error('All lambda functions must use SpecialCode because I said so');
      }
    }
  }
}
```

**Comment by eladb** [comment]
I hope my sketch above can help address this use case, @Dgarc359 let me know if now. Closing for now.

**Comment by Dgarc359** [comment]
@eladb I appreciate the response. Your suggestion is more intrusive than what I had in mind, but better than what I ended up implementing. I don't think it can get much better than that with the constraints of the cdk framework. Thank you!
