### ISSUE TITLE
(aws-ec2): Reference VPC Prefix Lists in AWS::EC2::Route

### ISSUE THREAD

**Issue by adriantaut** [aws/aws-cdk#17468]
### Description

Hello guys,

We are trying to add a Route into a subnet that has as `Destination` a VPC Prefix List. This is possible from AWS Console, however it seems not to be available in CDK.

```ts
      const route = new ec2.CfnRoute(this, `route-igw-cloudflare-${index}`, {
        routeTableId: subnet.routeTable.routeTableId,
        gatewayId: '<internet-gateway-id>',
        destinationCidrBlock: 'pl-xxxxxxxx',
      });
```

It gracefully fails with:
```
Value (pl-0666a7c1984caaa8a) for parameter destinationCidrBlock is invalid. This is not a valid CIDR block
```

Any idea if this possible somehow from CDK?

Thanks a lot!

### Use Case

Reference a single Prefix List with a bunch of CIDR ranges that can be automatically updated, instead of adding rules one by one.

### Proposed Solution

The `destinationIpv6CidrBlock` string parameter could also accept prefix lists strings that start with `pl-*`, perhaps?

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by njlynch** [comment]
Hi @adriantaut ,

It looks like CloudFormation doesn't currently support this feature: https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/572. Once the linked issue is resolved (the feature has been added to CloudFormation), support will be automatically included in the CDK in the next release.

**Comment by adriantaut** [comment]
thank you, @njlynch !

**Comment by chasepo** [comment]
@njlynch 

Should this be re-opened? DestinationPrefixListId has been added to [CFN](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-route.html#cfn-ec2-route-destinationprefixlistid), but not seeing it automatically in CDK yet.

**Comment by adriantaut** [comment]
@chasepo it is available in the most recent versions of CDK: https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ec2.CfnRoute.html#destinationprefixlistid and we are successfully using it 💯

**Comment by chasepo** [comment]
Thanks @adriantaut - I searched the github repo for `destinationPrefixListId` but nothing came back for `CfnRoute`. I don't think i'll ever really understand how the cdk-lib code is broken up! Sorry for not looking harder, i'll update locally and try again!
