### ISSUE TITLE
Add support for Cognito Schema

### ISSUE THREAD

**Issue by schof** [aws/aws-cdk#1747]
Add CDK support so that [Schema](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpool.html#cfn-cognito-userpool-schema) information can be configured for UserPools. This allows one to specify additional attributes that are allowed/required for new users.

**Comment by schof** [comment]
Here is a temporary workaround for anybody looking to solve the problem now:

```typescript
import { App, Stack, StackProps, Token } from '@aws-cdk/cdk'
import { CfnUserPool, CfnUserPoolClient } from '@aws-cdk/aws-cognito'

export class CognitoStack extends Stack {
  constructor(scope: App, id: string, props?: StackProps) {
    super(scope, id, props)
    /**
     * Use CfnUserPool until support is added for Schema attribute
     * https://github.com/awslabs/aws-cdk/issues/1747
     */
    const userPool = new CfnUserPool(this, 'Resource', {
      userPoolName: 'helloamplify',
      usernameAttributes: [new Token('email')],
      autoVerifiedAttributes: [new Token('email')],
      schema: [
        {
          attributeDataType: 'String',
          name: 'phone_number',
          mutable: true,
          required: true
        },
        {
          attributeDataType: 'String',
          name: 'email',
          mutable: false,
          required: true
        }
      ]
    })

    // tslint:disable:no-unused-expression
    new CfnUserPoolClient(this, 'helloamplify', {
      userPoolId: userPool.userPoolId,
      clientName: 'hello-amplify-client'
    })
  }
}
```

**Comment by sankeyraut** [comment]
Token constructor is private in version 0.39. Import needs to be corrected.

**Comment by sankeyraut** [comment]
Would this be a correct option 

```
import { CfnUserPool, CfnUserPoolClient } from '@aws-cdk/aws-cognito'
import { Token } from '@aws-cdk/core'; 
```

```
const userPool = new CfnUserPool(this, 'Resource', {
      userPoolName: 'helloamplify',
      usernameAttributes: ['email'],
      autoVerifiedAttributes: ['email'],
      schema: [
        {
          attributeDataType: 'String',
          name: 'phone_number',
          mutable: true,
          required: true
        },
        {
          attributeDataType: 'String',
          name: 'email',
          mutable: false,
          required: true
        }
      ]
    });
    const user_client = new CfnUserPoolClient(this, 'helloamplify', {
      userPoolId: userPool.logicalId,
      clientName: 'helloamplifyClient'
    });
```

**Comment by moofish32** [comment]
We also have hit this limitation and would like to be able to add schema as well. We went for overrides for now instead of the suggested work around above.

**Comment by nija-at** [comment]
I have a proposal to re-work Cognito's APIs - https://github.com/aws/aws-cdk-rfcs/pull/91 that addresses this issue. 

The RFC is in the comments period. If you'd like to see how the API is going to look and propose changes, this is your chance.

**Comment by 0xdevalias** [comment]
> I have a proposal to implement CDK APIs for Congito - [aws/aws-cdk-rfcs#91](https://github.com/aws/aws-cdk-rfcs/pull/91) - that addresses this issue.

Just wanted to link to the higher level 'tracking issue' for this PR for easier cross-reference:

- https://github.com/aws/aws-cdk-rfcs/issues/95
