### ISSUE TITLE
(aws-ec2): Amazon EC2 Mac Support and Dedicated Hosts In-General

### ISSUE THREAD

**Issue by trevorrobertsjr** [aws/aws-cdk#17489]
### Description

The current EC2 class does not have a construct for dedicated host allocation, which is a prerequisite to launching an Amazon EC2 Mac instance. Currently, users must allocate the dedicated host with another tool such as the GUI, CLI, CloudFormation, Terraform, etc. before the EC2 class can be used to deploy the Mac instance.

### Use Case

As a customer, I would like to use CDK for all provisioning steps required to launch an Amazon EC2 Mac instance, including the dedicated host allocation step without using custom CloudFormation code.

### Proposed Solution

Please either extend the EC2 class to support dedicated host lifecycle management, or create a class specifically for managing dedicated hosts. In addition, please extend the functionality of the [License Manager](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-licensemanager-readme.html) class to include Host Resource Group management. HRG's are a prerequisite for autoscaling dedicated hosts.

### Other information

Amazon EC2 Mac dedicated hosts require a [minimum 24-hour allocation](https://aws.amazon.com/ec2/instance-types/mac/#Pricing) per Apple's Software License Agreement. The CDK library will need to gracefully handle errors related to releasing the dedicated host before the 24-hour period expires. 

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by njlynch** [comment]
It looks like there is CloudFormation support for dedicated hosts, which is mirrored in the CDK classes:
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ec2.CfnHost.html
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ec2.CfnInstance.html#hostid

I believe you should be able to use these lower-level classes to achieve what you need.

That being said, we certainly can create higher-level constructs to make this easier to manage, and add the types of sanity checks you've noted.

**Comment by tcutts** [comment]
I think this would be a useful feature to add to the L2 construct.  It could just be a boolean flag added to the props, couldn't it?
