### ISSUE TITLE
(aws-cloudfront): Python `aws_cloudfront.FunctionCode.from_file()` does not produce `FunctionAssociation` `FunctionARN`

### ISSUE THREAD

**Issue by ppena-LiveData** [aws/aws-cdk#17494]
### What is the problem?

The [aws_cdk.aws_cloudfront documentation](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_cloudfront/README.html#cloudfront-function) shows this example (NOTE: this example has [another issue](https://github.com/aws/aws-cdk/issues/17493), which doesn't really seem related to this issue):
```python
cloudfront.Distribution(stack, "distro",
    default_behavior={
        "origin": origins.S3Origin(s3_bucket),
        "function_associations": [{
            "function": cf_function,
            "event_type": cloudfront.FunctionEventType.VIEWER_REQUEST
        }]
    }
)
```

The documentation goes on to say, "Additionally, you can load the function’s code from a file using the FunctionCode.fromFile() method."

Unfortunately, if I do try to use [aws_cloudfront.FunctionCode.from_file()](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_cloudfront/FunctionCode.html#aws_cdk.aws_cloudfront.FunctionCode.from_file), the resulting CloudFormation template's [FunctionAssociation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-functionassociation.html) is missing a `FunctionARN`. CDK tries to deploy, and CloudFormation returns this error when it tries to create the `AWS::CloudFront::Distribution`:
> Resource handler returned message: "Invalid request provided: 1 validation error detected: Value null at 'distributionConfigWithTags.distributionConfig.defaultCacheBehavior.functionAssociations.items.1.member.functionARN' failed to satisfy constraint: Member must not be null (Service: CloudFront, Status Code: 400, Request ID: 4aa9a2b7-1914-42a0-86cb-b406fdc4c8e7, Extended Request ID: null)" (RequestToken: 1703cc05-0ee8-41af-37ab-4d1e2d69fca2, HandlerErrorCode: InvalidRequest)

### Reproduction Steps

Reproduced using the [CloudFront Function example in the aws_cdk.aws_cloudfront documentation](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_cloudfront/README.html#cloudfront-function), but substituting `FunctionCode.from_file()` instead of `FunctionCode.from_inline()`.

### What did you expect to happen?

should work without error

### What actually happened?

CloudFormation returned a `CREATE_FAILED` error when trying to create the `AWS::CloudFront::Distribution`

### CDK CLI Version

1.132.0 (build 5c75891)

### Framework Version

Python aws-cdk.aws-cloudfront==1.132.0

### Node.js Version

v16.11.1

### OS

Linux

### Language

Python

### Language Version

Python 3.9.7

**Comment by njlynch** [comment]
Hmm.. both methods (`from_file` and `from_inline`) are identical, sans one reads from a file first. There shouldn't be any difference in how the association is made. 

Can you share a reproducible minimal example?

**Comment by ppena-LiveData** [comment]
Here's a simple example. This file I called `function_code.js`:
```javascript
function handler(event) {
    var request = event.request;
    return {
        statusCode: 302,
        statusDescription: 'Found',
        headers: {
            'location': {'value': 'http://example.com'}
        }
    };
}
```

and here's `app.py` that references that file:
```python
import aws_cdk.aws_cloudfront as cloudfront
import aws_cdk.aws_cloudfront_origins as origins
from aws_cdk import core as cdk

FUNCTION_CODE_PATH = 'function_code.js'

class MyStack(cdk.Stack):
    def __init__(self, scope: cdk.Construct, id: str, **kwargs):
        super().__init__(scope, id, **kwargs)

        # cf_function = cloudfront.Function(
        #     self, 'CloudFrontFunction',
        #     code=cloudfront.FunctionCode.from_inline(open(FUNCTION_CODE_PATH).read()),
        #     # name is needed to prevent gratuitous distribution changes, see https://github.com/aws/aws-cdk/issues/15523
        #     function_name='Issue17494',
        # )

        distribution = cloudfront.Distribution(
            self, 'CfDistribution',
            default_behavior={
                # we'll never hit the origin, so just using an arbitrary domain name
                'origin': origins.HttpOrigin('livedata.com'),
                'function_associations': [cloudfront.FunctionAssociation(
                    # function=cf_function,
                    function=cloudfront.FunctionCode.from_file(file_path=FUNCTION_CODE_PATH),
                    event_type=cloudfront.FunctionEventType.VIEWER_REQUEST
                )],
            })

        cdk.CfnOutput(self, 'CloudFrontDistributionDomainName', value=distribution.distribution_domain_name)


app = cdk.App()
MyStack(app, 'Issue17494')
app.synth()
```

If you use the `from_file()`, `cdk synth` will not have a `AWS::CloudFront::Function` and the `AWS::CloudFront::Distribution` will have a `FunctionAssociations` w/out a `FunctionARN`. If you uncomment the `cf_function` code to use that instead, then there won't be any problems.

**Comment by njlynch** [comment]
Ah, I see.

In your above example, you're doing this:

```python
function=cloudfront.FunctionCode.from_file(file_path=FUNCTION_CODE_PATH),
```

[`cloudfront.FunctionCode.from_file`](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_cloudfront/FunctionCode.html#aws_cdk.aws_cloudfront.FunctionCode.from_file) returns a `FunctionCode`. `FunctionAssociation.function` needs a `Function`. 

The equivalent calls are either:

```python
        # From inline
        cf_function = cloudfront.Function(
            self, 'CloudFrontFunction',
            code=cloudfront.FunctionCode.from_inline(open(FUNCTION_CODE_PATH).read()),
            function_name='Issue17494',
        )
        # From file
        cf_function = cloudfront.Function(
            self, 'CloudFrontFunction',
            code=cloudfront.FunctionCode.from_file(FUNCTION_CODE_PATH),
            function_name='Issue17494',
        )
```

`from_file` is literally just a convenience method for skipping the `open().read()` calls.

**Comment by ppena-LiveData** [comment]
Oooh, that makes sense. Thanks.
