### ISSUE TITLE
(aws-cloudfront): Python `aws_cloudfront.Distribution.default_behavior.function_associations` cannot use dicts

### ISSUE THREAD

**Issue by ppena-LiveData** [aws/aws-cdk#17493]
### What is the problem?

The [aws_cdk.aws_cloudfront documentation](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_cloudfront/README.html#cloudfront-function) shows this example:
```python
cloudfront.Distribution(stack, "distro",
    default_behavior={
        "origin": origins.S3Origin(s3_bucket),
        "function_associations": [{
            "function": cf_function,
            "event_type": cloudfront.FunctionEventType.VIEWER_REQUEST
        }]
    }
)
```

but if you try using that, you get this error (I'm only showing the end of the traceback):
```
  File "/proj/.venv/lib/python3.9/site-packages/aws_cdk/aws_cloudfront/__init__.py", line 12075, in __init__
    jsii.create(self.__class__, self, [scope, id, props])
  File "/proj/.venv/lib/python3.9/site-packages/jsii/_kernel/__init__.py", line 290, in create
    response = self.provider.create(
  File "/proj/.venv/lib/python3.9/site-packages/jsii/_kernel/providers/process.py", line 345, in create
    return self._process.send(request, CreateResponse)
  File "/proj/.venv/lib/python3.9/site-packages/jsii/_kernel/providers/process.py", line 326, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: Missing required properties for @aws-cdk/aws-cloudfront.FunctionAssociation: eventType
```

When I print out the `request: CreateRequest` that is being sent, I see that `functionAssociations` (whose name was correctly mapped from "function_associations") has this, which shows that `jsii._kernel._make_reference_for_native()` returned a `$jsii.map` instead of a `jsii.struct`:
```python
[{'$jsii.map': {
    'function': <aws_cdk.aws_cloudfront._FunctionCodeProxy object at 0x7ff08ac36a30>,
    'event_type': {'$jsii.enum': '@aws-cdk/aws-cloudfront.FunctionEventType/VIEWER_REQUEST'}}}]
```

### Reproduction Steps

Reproduced using the [CloudFront Function example in the aws_cdk.aws_cloudfront documentation](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_cloudfront/README.html#cloudfront-function).

### What did you expect to happen?

should work without error

### What actually happened?

`jsii.errors.JSIIError: Missing required properties for @aws-cdk/aws-cloudfront.FunctionAssociation: eventType`

### CDK CLI Version

1.132.0 (build 5c75891)

### Framework Version

Python aws-cdk.aws-cloudfront==1.132.0

### Node.js Version

v16.11.1

### OS

Linux

### Language

Python

### Language Version

Python 3.9.7

**Comment by njlynch** [comment]
Thanks for the report, @ppena-LiveData !

We've addressed some bugs in the underlying documentation generation, and it looks like now the example you linked to shows the correct code as expected: https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_cloudfront/README.html#cloudfront-function

```python
cloudfront.Distribution(self, "distro",
    default_behavior=cloudfront.BehaviorOptions(
        origin=origins.S3Origin(s3_bucket),
        function_associations=[cloudfront.FunctionAssociation(
            function=cf_function,
            event_type=cloudfront.FunctionEventType.VIEWER_REQUEST
        )]
    )
)
```
