### ISSUE TITLE
(Amazon.CDK.AWS.ElasticLoadBalancingV2.NetworkTargetGroup): NetworkTargetGroup doesn't allow specifying sticky sessions

### ISSUE THREAD

**Issue by nacitar** [aws/aws-cdk#17491]
### What is the problem?

NetworkTargetGroup doesn't allow you to specify to use sticky sessions.  In cloudformation you can set these values and they work just fine... but CDK doesn't expose them.

The ApplicationTargetGroup does expose these settings: https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-elasticloadbalancingv2.ApplicationTargetGroup.html
On that page you can see stickinessCookieDuration and stickinessCookieName.

The NLB equivalent NetworkTargetGroup does not expose these settings:
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-elasticloadbalancingv2.NetworkTargetGroup.html
On that page you can see there is no setting for either stickinessCookieDuration or stickinessCookieName and there's no other setting relevant either.

### Reproduction Steps

Try to specify a stickinessCookieDuration.  You can't because there's no such member in the props.

### What did you expect to happen?

I expect there to be members in the props for all possible settings, including the stickiness cookie related settings.

### What actually happened?

I was forced to use an ALB for something that required a sticky session when I could have simply used a NLB, but because it needed to be done with CDK I had no real choice.

### CDK CLI Version

1.124.0 (build 65761fe)

### Framework Version

.NET Core 3.1

### Node.js Version

v14.17.6

### OS

Windows 10

### Language

.NET

**Comment by ryparker** [comment]
Hey @nacitar 👋🏻 

Although the `NetworkTargetGroup` does not have the same `.stickiness*()` API as `ApplicationTargetGroup`, you should be able to achieve this by utilizing `NetworkTargetGroup.setAttribute(key, value)`. See the [CloudFormation docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticloadbalancingv2-targetgroup-targetgroupattribute.html) for a list of possible `stickiness.*` attributes you can configure.

i.g.
```ts
networkTagetGroup.setAttribute('stickiness.app_cookie.duration_seconds', 1800);
```

Here's the list of stickiness attributes from the [CFN docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticloadbalancingv2-targetgroup-targetgroupattribute.html):

- stickiness.app_cookie.cookie_name - Indicates the name of the application-based cookie. Names that start with the following prefixes are not allowed: AWSALB, AWSALBAPP, and AWSALBTG; they're reserved for use by the load balancer.

- stickiness.app_cookie.duration_seconds - The time period, in seconds, during which requests from a client should be routed to the same target. After this time period expires, the application-based cookie is considered stale. The range is 1 second to 1 week (604800 seconds). The default value is 1 day (86400 seconds).

- stickiness.lb_cookie.duration_seconds - The time period, in seconds, during which requests from a client should be routed to the same target. After this time period expires, the load balancer-generated cookie is considered stale. The range is 1 second to 1 week (604800 seconds). The default value is 1 day (86400 seconds).

**Comment by nacitar** [comment]
A roundabout **workaround** existing does not make this cease to be a bug.  Thanks for pointing out the workaround, but your removal of "bug" and addition of "closing soon" without any action is misplaced.  There's a pattern with AWS tickets where, to the point of absurdity, people try to pretend that bugs aren't bugs.  It's a bug.  I shouldn't have to dig through cloudformation APIs to hack together a solution.  The props are **clearly** deficient and in need of an actual fix.

**Comment by ryparker** [comment]
I understand that it can be a major pain when you're expecting an API to look and work one way but find out it's not quite what you expected, then boom there goes another hour of work. Your frustration is valid. 

Fortunately this is an open source project developed by both open source contributors and AWS engineers. For the sake of rapid improvement things will be inconsistent from time to time. This is not a bug though. The APIs you're looking for never existed in the `NetworkTargetGroup`. Perhaps there is a reason why the APIs are not consistent? Either way this does not qualify as breaking functionality. However this **would** qualify as a **feature request** and I've modified this issue as such so that we can collect community feedback.

I encourage you to consider contributing the change yourself, otherwise adding 👍🏻  on the issue description will help us prioritize.
