### ISSUE TITLE
[aws-ec2]: CfnInstance autoAssignPublicIp error: "Attribute: PublicIp was not found for resource"

### ISSUE THREAD

**Issue by mainframenzo** [aws/aws-cdk#17516]
### General Issue

Deploy / Documentation Issue

### The Question

I am coming from Terraform and trying to match functionality using your higher level EC2 instance constructs. I am encountering issues with matching Terraform's [associate_public_ip_address](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#associate_public_ip_address) abstraction to the CDK's.

Background: I have a pre-existing VPC with a public subnet that does NOT [map public IPs on launch](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-subnet.html#cfn-ec2-subnet-mappubliciponlaunch) (no control over this VPC and subnet), and I want an EC2 instance to be launched in that public subnet with a public IP _without using an Elastic IP_. It seems since I can not configure the generated network interface in the higher level `EC2.Instance` construct that I must use the escape hatch `EC2.CfnInstance` construct. I am running into this error during deployment:

    Attribute: PublicIp was not found for resource: i-xxxxxxxxxxxxxx

I seem to be missing something! Here is an example of what I'm doing:

```
import * as EC2 from '@aws-cdk/aws-ec2';
import * as CDK from '@aws-cdk/core';

// ...

new EC2.CfnInstance(this, 'EC2Instance', {
  tags: [{ key: 'Name', value: 'has public ip' }],
  instanceType: 'g4dn.xlarge',
  imageId: 'ami-0aff2dd81d2a3ae78',
  monitoring: true,
  blockDeviceMappings: [{
    deviceName: '/dev/sda1',
    ebs: {
      encrypted: true,
      volumeSize: 900,
      deleteOnTermination: true
    }
  }],
  ebsOptimized: true,
  networkInterfaces: [{
    associatePublicIpAddress: true,
    subnetId: 'subnet-xxxx', // public subnet with MapPublicIpOnLaunch set to false
    deviceIndex: '0'
  }]
});
 ```
 
 Any ideas why this is happening?
 
 Cheers!

### CDK CLI Version

1.129.0 (build fb43f89)

### Node.js Version

v14.17.3

### OS

MacOS 11.6

### Language

Typescript

### Language Version

TypeScript (3.8.3)

**Comment by peterwoodworth** [comment]
Hmm, I'm not able to reproduce this on my first try. All I've set up so far is a subnet with `MapPublicIpOnLaunch` set to false, and I'm able to create an instance in that subnet with `associatePublicIpAddress` set to true. 

Where in deployment are you receiving that error message?
