### ISSUE TITLE
Does CodeStarConnectionsSourceAction support filters like webhooks??

### ISSUE THREAD

**Issue by kounteya29** [aws/aws-cdk#17512]
### General Issue

Does CodeStarConnectionsSourceAction support filters like webhooks??

### The Question

Hi , 

I do have  git hub repo like mono-repo which is having multiple folders for which we created multiple pipelines.  I can able to trigger  the respective pipeline(when there is a change particular folder level) using git hub webhook filters . Now the direction is to use CDK with codestar connection but i didn't find a way to trigger  the pipeline at subfolder level using codestart connection .

Is there any i can acheive or i need to use github1 with webhooks ?  Please help out here 

### CDK CLI Version

1.124.0

### Language

Python

### Language Version

3.8

**Comment by skinny85** [comment]
Hey @kounteya29,

thanks for opening the issue. Can you show the code you are using right now to do the filtering, based on the directory?

Thanks,
Adam

**Comment by kounteya29** [comment]
![image](https://user-images.githubusercontent.com/77369602/141840285-405f6e57-c312-4d28-b16f-0b03183037ad.png)

**Comment by kounteya29** [comment]
Please check the abovce code snippet

**Comment by kounteya29** [comment]
Reopening the issue

**Comment by skinny85** [comment]
Got it. Unfortunately, looking at [the docs](https://docs.aws.amazon.com/codepipeline/latest/userguide/action-reference-CodestarConnectionSource.html), I don't think the CodeStar Connections support anything that granular.

I think you need to stick with the `GitHubSourceAction` if you want that functionality.

Thanks,
Adam

**Comment by skinny85** [comment]
Same in the [CodeStar Connections docs](https://docs.aws.amazon.com/dtconsole/latest/userguide/connections-create-github.html).

**Comment by kounteya29** [comment]
As per AWS documentation it is recommending to use The GitHub version 2 action (Github app-based authentication) instead of GitHub version 1 action. is there any feature request for the same ?

**Comment by skinny85** [comment]
If you have Premium Support, you can raise this issue as a feature request to the CodeStar Connections team.

**Comment by coayscue** [comment]
I think this works: 
https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_codebuild.FilterGroup.html
See "andFilePathIs(pattern)".

**Comment by skinny85** [comment]
@coayscue that's for a CodeBuild Source, which unfortunately works differently than a CodePipeline Source.
