### ISSUE TITLE
(core): `cdk synthesize` starts by printing "fatal: no tag exactly matches '[commit ID]'"

### ISSUE THREAD

**Issue by l0b0** [aws/aws-cdk#17517]
### What is the problem?

When running `cdk synthesize` it prints an ominous but possibly irrelevant message:

> fatal: no tag exactly matches '153eaf98900bcd1ebf8fac6e40804a767b37393a'

It looks like CDK is [running a Git command](https://stackoverflow.com/q/57562335/96588) just prior to building the "amazon/aws-sam-cli-build-image-python3.7" Docker image.

### Reproduction Steps

1. Check out [this commit](https://github.com/linz/geostore/commit/153eaf98900bcd1ebf8fac6e40804a767b37393a) (not tested on other commits)
2. Run `cdk synth`

### What did you expect to happen?

Synthesizing should not print any error messages.

### What actually happened?

```
$ cdk synthesize
fatal: no tag exactly matches '153eaf98900bcd1ebf8fac6e40804a767b37393a'
Sending build context to Docker daemon  7.168kB
Step 1/9 : ARG IMAGE=amazon/aws-sam-cli-build-image-python3.7
Step 2/9 : FROM $IMAGE
 ---> 6e90d1df1f5d
[…]
```

### CDK CLI Version

1.130.0 (build 9c094ae)

### Framework Version

aws-cli/1.19.53 Python/3.8.9 Linux/5.10.77 botocore/1.20.53

### Node.js Version

v16.13.0

### OS

NixOS 21.05

### Language

Python

### Language Version

Python 3.8.9

**Comment by rix0rrr** [comment]
Can you give us a link to your CDK project that is showing this behavior?

**Comment by l0b0** [comment]
> Can you give us a link to your CDK project that is showing this behavior?

I linked to it above; you could also try https://github.com/linz/geostore/commit/a1330ec5f9fb19e7661f5a0c32516fdcd97b236b which has the same behaviour.

**Comment by l0b0** [comment]
It does seem to be related to my local configuration in some way, because I don't see this error message in the CI output ([example](https://github.com/linz/geostore/runs/4259938553?check_suite_focus=true), step "Deploy copy of production AWS stacks in to CI environment")

**Comment by rix0rrr** [comment]
I checked your project out but I don't know how to run it.

**Comment by l0b0** [comment]
> I checked your project out but I don't know how to run it.

If you have CDK and Poetry installed it should be enough to run `poetry install && poetry run cdk synthesize`.

**Comment by rix0rrr** [comment]
I'm looking at commit `a1330ec5f9fb19e7661f5a0c32516fdcd97b236b` of https://github.com/linz/geostore and when I run those commands:

```
$ poetry run python3 app.py
Traceback (most recent call last):
  File "/Users/huijbers/Temp/geostore/app.py", line 4, in <module>
    from aws_cdk.core import App, Tag
ModuleNotFoundError: No module named 'aws_cdk'
```

It seems that `aws-cdk` is not installed by `poetry install`.

```
$ ls .venv/lib/python3.9/site-packages/ | grep cdk
$ cat poetry.toml
cat poetry.toml
[virtualenvs]
in-project = true
```

**Comment by l0b0** [comment]
Oh right, you also need to `npm install`:

```console
$ git checkout a1330ec5f9fb19e7661f5a0c32516fdcd97b236b
$ export CDK_DEFAULT_ACCOUNT=default
$ poetry install
$ npm i
$ poetry run cdk synthesize
fatal: no tag exactly matches 'a1330ec5f9fb19e7661f5a0c32516fdcd97b236b'
```

**Comment by l0b0** [comment]
Please reopen.
