### ISSUE TITLE
(iam):  Modify tags for imported users

### ISSUE THREAD

**Issue by kornicameister** [aws/aws-cdk#17523]
### Description

I would like to import `iam.User` construct into my stack and change its tags (add, remove). 
In short, users are not tracked by IAC and they just already exist but I would like to have any further changes made to them done via CDK.

### Use Case

- change tags for existing users
- be able to use IAC to generate tags in code and use those tags in other place for IAM policies' conditions

### Proposed Solution

N/A

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by rix0rrr** [comment]
This is not possible using CloudFormation. You could build a Custom Resource to do this if you wanted to. CDK will not deliver this feature out of the box.
