### ISSUE TITLE
(redshift): expose User.secret as property

### ISSUE THREAD

**Issue by Ahmed-Hussein93** [aws/aws-cdk#17520]
### Description

Currently there is no way to access the secret created by Redshift User construct and that make it difficult to use method addRotationMultiUser to rotate the user credentials.
https://github.com/aws/aws-cdk/blob/v1.132.0/packages/@aws-cdk/aws-redshift/lib/user.ts#L150
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-redshift.User.html

### Use Case

1. The secret needed to allow redshift cluster rotating the credentials, function addRotationMultiUser accept only secret.
2. The secret ARN is needed by other services, for example creating IAM Policy and need to scope down the resources only to this secret.

### Proposed Solution

The solution to add Property called secret that will return the secret created https://github.com/aws/aws-cdk/blob/v1.132.0/packages/@aws-cdk/aws-redshift/lib/user.ts#L150

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by Ahmed-Hussein93** [comment]
This should be labeled `@aws-cdk/aws-redshift`

**Comment by njlynch** [comment]
Sure, this seems reasonable. We welcome community contributions! If you are able, we encourage you to [contribute](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md).

**Comment by manmartgarc** [comment]
Is there a reason why this method was not also defined in the `IUser` interface?
