### ISSUE TITLE
(aws_ec2): python module missing new SubnetType enum values

### ISSUE THREAD

**Issue by Aloisius** [aws/aws-cdk#17531]
### What is the problem?

SubnetType.ISOLATED and SubnetType.PRIVATE are being deprecated in favor of SubnetType.PRIVATE_ISOLATED and SubnetType.PRIVATE_WITH_NAT, however neither PRIVATE_ISOLATED nor PRIVATE_WITH_NAT are exposed in Python.

### Reproduction Steps

```python
import aws_cdk.aws_ec2 as ec2

# error
ec2.SubnetType.PRIVATE_ISOLATED
```

### What did you expect to happen?

It to succeed.

### What actually happened?

Exception thrown.

### CDK CLI Version

1.32.0

### Node.js Version

16.3.0

### OS

MacOS Monterey

### Language

Python

### Language Version

3.9.7

**Comment by peterwoodworth** [comment]
I can confirm this. Not sure why this would be happening, they work fine on TypeScript https://github.com/aws/aws-cdk/blob/5c758919e6751f31143fa0979fdc1e040a6c6d11/packages/%40aws-cdk/aws-ec2/lib/vpc.ts#L166

@njlynch @RomainMuller any ideas here?

**Comment by Aloisius** [comment]
Ahh. This is probably a duplicate of #16443.

It appears #14059 is also related to the same issue.

https://github.com/aws/jsii/issues/2782 appears to be a jsii bug report about it.

**Comment by peterwoodworth** [comment]
you're right - this is a duplicate. Closing in favor of #16443
