### ISSUE TITLE
(core): Add note in Cloutwatch Alarm documentation to mention format difference in CDK

### ISSUE THREAD

**Issue by Floocs** [aws/aws-cdk#17534]
### link to reference doc page

https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/aws-cloudwatch#alarms

### Describe your issue?

When using the CLI, standard metric alarms and (metric math / cross account) alarms have two different structures.

- Standard metric alarms would have the metric definition at top level of the `Trigger`:
`
"Trigger": {
    "MetricName": "Errors",
    "Namespace": "AWS/Lambda",
    "StatisticType": "Statistic",
    "Statistic": "SUM",
    "Unit": null,
    "Dimensions": [
        {
            "value": "myFunction",
            "name": "FunctionName"
        }
    ],
    "Period": 60,
    "EvaluationPeriods": 1,
    "ComparisonOperator": "GreaterThanOrEqualToThreshold",
    "Threshold": 0.0,
    "TreatMissingData": "",
    "EvaluateLowSampleCountPercentile": ""
}
`
- Metric math and cross account metric alarms would have metric definition under `"Metrics": []`
`"Trigger": {
    "Period": 60,
    "EvaluationPeriods": 1,
    "ComparisonOperator": "GreaterThanThreshold",
    "Threshold": 1.0,
    "TreatMissingData": "- TreatMissingData: notBreaching",
    "EvaluateLowSampleCountPercentile": "",
    "Metrics": [
        {
            "Id": "m1",
            "MetricStat": {
                "Metric": {
                    "Dimensions": [
                        {
                            "value": "myFunction",
                            "name": "FunctionName"
                        }
                    ],
                    "MetricName": "Errors",
                    "Namespace": "AWS/Lambda"
                },
                "Period": 60,
                "Stat": "Sum"
            },
            "ReturnData": true
        }
    ]
}`

But, all alarms created through CDK are being created with the structure of a metric math / cross account alarm, so the metric configuration would be under `"Metrics": []` even for an alarm which is a standard metric alarm (with only one metric)

This is something that users should be aware of when they are moving standard metric alarms to CDK. The content of SNS notification will change, the content of Cloudwatch events messages will change as well. ([documentation of different message formats for Cloudwatch Events](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch-and-eventbridge.html))

This can break some automation that the users might already have in place, so it could be mentioned as a note in the Alarm section.

**Comment by rix0rrr** [comment]
Resolved by https://github.com/aws/aws-cdk/pull/17538
