### ISSUE TITLE
pipelines: Add ConfirmPipelineUpdate action similar to ConfirmPermissionsBroadening

### ISSUE THREAD

**Issue by nakedible-p** [aws/aws-cdk#17541]
### Description

The basic usage of CDK pipelines is to have multiple application stages in a row, for different environments such as test and production. If going by the principle of least privilege, test and production environments will likely live in separate accounts, which means that the account that contains the pipeline (I will call it "pipeline account" from here onwards) needs to be able to assume a deployment role in these accounts. For additional security, a manual approval step may be inserted before the production stage - and this step may be limited so that not every developer has the permission to deploy to production, but all developers that can make git changes can deploy to the test environment. In this case, it is obvious that developers cannot have admin access to the "pipeline account" directly, or they could make production changes by assuming a role through the "pipeline account".

However, this method to limit access to production does not work, because the developer can simply change the pipeline to omit the approval action before production. To solve this, there would need to be a separate approval action also for the pipeline update stage (the self-update stage), which would require manual approval only if the pipeline definition stack has been modified. This would be very similar to the currently existing `ConfirmPermissionsBroadening` action which asks for manual approval if security permissions are broadened in the change in question - but it is only applicable to application stages, not the pipeline update stage.

### Use Case

I want to require manual approval for every change that modifies the pipeline itself. I want to prevent developers who have only have git access from being able to bypass manual approval actions required for deployments to the production environments. This is also useful as a separate review step, just like `ConfirmPermissionsBroadening`, even if there is no strict security requirement.

### Proposed Solution

- Use https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/pipelines/lib/private/application-security-check.ts as a basis for the implementation.
- Generalize `cdkDiffProject` so that the `--security-only` flag is optional, and confirm that `UpdatePipeline` stage `SelfMutate` action can be gated
- Add a `confirm-pipeline-update.ts` based on https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/pipelines/lib/codepipeline/confirm-permissions-broadening.ts, using the same private `application-security-check` library with some different parameters.

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by rix0rrr** [comment]
I can see why you might want this. CDK Pipelines currently prevents you from making mistakes, it is not designed to withstand attacks from within your own developer team.

I'm not sure the proposed solution is the end-all for this, but it might be a good step.

I don't think we're going to include this into CDK Pipelines anytime soon, but I'd encourage you to write your own `Step` class that implements this, and publish it to https://constructs.dev/ for other people to reuse.

**Comment by lexhl** [comment]
This is a total cop-out. What if a developer account is compromised? I must have some way to prevent the attacker from escalating their privileges to the maximum.
