### ISSUE TITLE
add method to get current accountId and region

### ISSUE THREAD

**Issue by jesterhazy** [aws/aws-cdk#1754]
cdk should provide a way to lookup the aws accountId and region that the cdk app is run under.

the current methods (e.g. `cdk.Stack.find(this).accountId` or `stack.region`) only return the values if they were set explicitly in the stack environment. otherwise they return tokens that won't resolve until deploy. I can't use these values in my cdk code to check if the account or region matches certain known combinations, which is something I need to do to vary a few details of my stack depending on where it gets deployed. 

`stack.requireRegion` and `stack.requireAccountId` currently provide the desired behavior, but this conflicts with the api docs for these methods, which say that they will throw an Error if the values weren't explicitly set in the environment.

A little more color on the scenario I'm working with... When I'm working on the cdk code I test in a transient account and would like cdk to create the entire stack. But when the stack is deployed in the real target account, there are some existing resources that need to be imported instead of created.

**Comment by skinny85** [comment]
Hey @jesterhazy ,

can you elaborate a little on this:

> `stack.requireRegion` and `stack.requireAccountId` currently provide the desired behavior, but this conflicts with the api docs for these methods, which say that they will throw an Error if the values weren't explicitly set in the environment.

Are you saying they currently *don't* throw an exception if the values were not set?

Thanks,
Adam

**Comment by rix0rrr** [comment]
I agree these methods currently aren't great.

There's also `stack.env.region` and `stack.env.account`, which  will more closely map to what you need (a value or `undefined`).

**Comment by jesterhazy** [comment]
@skinny85 yes, in a stack created without any environment parameter, `stack.requireRegion` and `stack.requireAccountId` are returning actual values that match the credentials and default region in my  aws config/credentials file. They do not throw an exception. This is exactly what I need, but definitely not what the docs say these methods are supposed to do.

**Comment by jesterhazy** [comment]
there appears to be another useful workaround. I've replaced my calls to `requireRegion` and `requireAccountId` with this function:

```
    current_env(construct: cdk.Construct): cdk.Environment {
        return {
            account: construct.node.getContext('aws:cdk:toolkit:default-account'),
            region: construct.node.getContext('aws:cdk:toolkit:default-region')
        }
    }
```

this seems to work fine when called with top-level `app` as parameter.

it would be great if these could be exposed through some friendlier app or context property.

**Comment by Kent1** [comment]
`Stack.of(this).getRegion()` ?

**Comment by isubuz** [comment]
There is also the `Aws` class in `core` which gives the pseudo parameter values. 

In python - 

```python
from aws_cdk.core import Aws
print(Aws.Region}
```

**Comment by eladb** [comment]
The recommended way is: `Stack.of(this).account` and `Stack.of(this).region`. Closing for now. Feel free to reopen.

**Comment by brianfoody** [comment]
Python: `self.account` and `self.region`
TypeScript: `this.account` and `this.region`

**Comment by massimoselvi** [comment]
const { accountId, region } = new cdk.ScopedAws(this);

**Comment by fredski-github** [comment]
@isubuz +1

adding documentation references: the core.Aws class has properties mapping to CloudFormation pseudo parameters.

https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.Aws.html -> https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/pseudo-parameter-reference.html

example:
in the stack use `core.Aws.ACCOUNT_ID`, it will generate `Ref: AWS::AccountId` in the CloudFormation template found in cdk.out

It works with python specifically.

**Comment by praveen-fiserv** [comment]
'stack.account' works for me and its getting the current account ID.

**Comment by anentropic** [comment]
In v2: https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.Aws.html
