### ISSUE TITLE
(aws-eks): EksdemoStack | 11/14 | 下午2:21:22 | CREATE_FAILED 

### ISSUE THREAD

**Issue by louisleo234** [aws/aws-cdk#17556]
### General Issue

Nodegroup ClusterNodegroupDefaultCapa-cSKLvWa4Tbo3 failed to stabilize:

### The Question

```sh
11/14 Currently in progress: EksdemoStack, ClusterNodegroupDefaultCapacityDA0920A3, ClusterAwsAuthmanifestFE51F8AE
EksdemoStack | 11/14 | 下午2:21:22 | CREATE_FAILED        | AWS::EKS::Nodegroup                   | Cluster/NodegroupDefaultCapacity (ClusterNodegroupDefaultCapacityDA0920A3) Nodegroup ClusterNodegroupDefaultCapa-cSKLvWa4Tbo3 failed to stabilize: [{Code: NodeCreationFailure,Message: Instances failed to join the kubernetes cluster,ResourceIds: [i-02d2213bead380a29, i-0917ddef8f04b94b8]}]
        new Nodegroup (C:\Users\182558\eksdemo\node_modules\@aws-cdk\aws-eks\lib\managed-nodegroup.ts:201:22)
        \_ Cluster.addNodegroupCapacity (C:\Users\182558\eksdemo\node_modules\@aws-cdk\aws-eks\lib\cluster.ts:889:12)
        \_ new Cluster (C:\Users\182558\eksdemo\node_modules\@aws-cdk\aws-eks\lib\cluster.ts:822:14)
        \_ new EksdemoStack (C:\Users\182558\eksdemo\lib\eksdemo-stack.ts:22:21)
        \_ Object.<anonymous> (C:\Users\182558\eksdemo\bin\eksdemo.ts:13:1)
        \_ Module._compile (node:internal/modules/cjs/loader:1101:14)
        \_ Module.m._compile (C:\Users\182558\eksdemo\node_modules\ts-node\src\index.ts:1056:23)
        \_ Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
        \_ Object.require.extensions.<computed> [as .ts] (C:\Users\182558\eksdemo\node_modules\ts-node\src\index.ts:1059:12)
        \_ Module.load (node:internal/modules/cjs/loader:981:32)
        \_ Function.Module._load (node:internal/modules/cjs/loader:822:12)
        \_ Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
        \_ main (C:\Users\182558\eksdemo\node_modules\ts-node\src\bin.ts:198:14)
        \_ Object.<anonymous> (C:\Users\182558\eksdemo\node_modules\ts-node\src\bin.ts:288:3)
        \_ Module._compile (node:internal/modules/cjs/loader:1101:14)
        \_ Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
        \_ Module.load (node:internal/modules/cjs/loader:981:32)
        \_ Function.Module._load (node:internal/modules/cjs/loader:822:12)
        \_ Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
        \_ node:internal/main/run_main_module:17:47
EksdemoStack | 11/14 | 下午2:21:23 | CREATE_FAILED        | Custom::AWSCDK-EKS-KubernetesResource | Cluster/AwsAuth/manifest/Resource/Default (ClusterAwsAuthmanifestFE51F8AE) Resource creation cancelled
        new CustomResource (C:\Users\182558\eksdemo\node_modules\@aws-cdk\core\lib\custom-resource.ts:36:21)
        \_ new KubernetesManifest (C:\Users\182558\eksdemo\node_modules\@aws-cdk\aws-eks\lib\k8s-manifest.ts:49:5)
        \_ new AwsAuth (C:\Users\182558\eksdemo\node_modules\@aws-cdk\aws-eks\lib\aws-auth.ts:30:5)
        \_ Cluster.get awsAuth [as awsAuth] (C:\Users\182558\eksdemo\node_modules\@aws-cdk\aws-eks\lib\cluster.ts:898:23)
        \_ new Cluster (C:\Users\182558\eksdemo\node_modules\@aws-cdk\aws-eks\lib\cluster.ts:806:10)
        \_ new EksdemoStack (C:\Users\182558\eksdemo\lib\eksdemo-stack.ts:22:21)
        \_ Object.<anonymous> (C:\Users\182558\eksdemo\bin\eksdemo.ts:13:1)
        \_ Module._compile (node:internal/modules/cjs/loader:1101:14)
        \_ Module.m._compile (C:\Users\182558\eksdemo\node_modules\ts-node\src\index.ts:1056:23)
        \_ Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
        \_ Object.require.extensions.<computed> [as .ts] (C:\Users\182558\eksdemo\node_modules\ts-node\src\index.ts:1059:12)
        \_ Module.load (node:internal/modules/cjs/loader:981:32)
        \_ Function.Module._load (node:internal/modules/cjs/loader:822:12)
        \_ Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
        \_ main (C:\Users\182558\eksdemo\node_modules\ts-node\src\bin.ts:198:14)
        \_ Object.<anonymous> (C:\Users\182558\eksdemo\node_modules\ts-node\src\bin.ts:288:3)
        \_ Module._compile (node:internal/modules/cjs/loader:1101:14)
        \_ Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
        \_ Module.load (node:internal/modules/cjs/loader:981:32)
        \_ Function.Module._load (node:internal/modules/cjs/loader:822:12)
        \_ Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
        \_ node:internal/main/run_main_module:17:47
```

### CDK CLI Version

up to date

### Node.js Version

up to date

### OS

winwodws10_x64

### Language

Typescript

### Language Version

py3.10

**Comment by louisleo234** [comment]
11/14 Currently in progress: EksdemoStack, ClusterAwsAuthmanifestFE51F8AE
EksdemoStack | 11/14 | 下午3:21:45 | DELETE_FAILED        | Custom::AWSCDK-EKS-KubernetesResource | Cluster/AwsAuth/manifest/Resource/Default (ClusterAwsAuthmanifestFE51F8AE) CloudFormation did not receive a response from your Custom Resource. Please check your logs for requestId [e74807a4-5bcc-4bde-b858-bc3f11c72c25]. If you are using the Python cfn-response module, you may need to update your Lambda function code so that CloudFormation can attach the updated version.
        new CustomResource (C:\Users\182558\eksdemo\node_modules\@aws-cdk\core\lib\custom-resource.ts:36:21)
        \_ new KubernetesManifest (C:\Users\182558\eksdemo\node_modules\@aws-cdk\aws-eks\lib\k8s-manifest.ts:49:5)
        \_ new AwsAuth (C:\Users\182558\eksdemo\node_modules\@aws-cdk\aws-eks\lib\aws-auth.ts:30:5)
        \_ Cluster.get awsAuth [as awsAuth] (C:\Users\182558\eksdemo\node_modules\@aws-cdk\aws-eks\lib\cluster.ts:898:23)
        \_ new Cluster (C:\Users\182558\eksdemo\node_modules\@aws-cdk\aws-eks\lib\cluster.ts:806:10)
        \_ new EksdemoStack (C:\Users\182558\eksdemo\lib\eksdemo-stack.ts:22:21)
        \_ Object.<anonymous> (C:\Users\182558\eksdemo\bin\eksdemo.ts:13:1)
        \_ Module._compile (node:internal/modules/cjs/loader:1101:14)
        \_ Module.m._compile (C:\Users\182558\eksdemo\node_modules\ts-node\src\index.ts:1056:23)
        \_ Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
        \_ Object.require.extensions.<computed> [as .ts] (C:\Users\182558\eksdemo\node_modules\ts-node\src\index.ts:1059:12)
        \_ Module.load (node:internal/modules/cjs/loader:981:32)
        \_ Function.Module._load (node:internal/modules/cjs/loader:822:12)
        \_ Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
        \_ main (C:\Users\182558\eksdemo\node_modules\ts-node\src\bin.ts:198:14)
        \_ Object.<anonymous> (C:\Users\182558\eksdemo\node_modules\ts-node\src\bin.ts:288:3)
        \_ Module._compile (node:internal/modules/cjs/loader:1101:14)
        \_ Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
        \_ Module.load (node:internal/modules/cjs/loader:981:32)
        \_ Function.Module._load (node:internal/modules/cjs/loader:822:12)
        \_ Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
        \_ node:internal/main/run_main_module:17:47
EksdemoStack | 11/14 | 下午3:21:47 | DELETE_IN_PROGRESS   | AWS::SSM::Parameter                   | Cluster/KubectlReadyBarrier (ClusterKubectlReadyBarrier200052AF)    
EksdemoStack | 11/14 | 下午3:21:47 | DELETE_IN_PROGRESS   | AWS::IAM::Role                        | Cluster/NodegroupDefaultCapacity/NodeGroupRole (ClusterNodegroupDefaultCapacityNodeGroupRole55953B04) 
EksdemoStack | 11/14 | 下午3:21:47 | DELETE_IN_PROGRESS   | AWS::CloudFormation::Stack            | @aws-cdk--aws-eks.KubectlProvider.NestedStack/@aws-cdk--aws-eks.KubectlProvider.NestedStackResource (awscdkawseksKubectlProviderNestedStackawscdkawseksKubectlProviderNestedStackResourceA7AEBA6B) 
EksdemoStack | 11/14 | 下午3:21:47 | DELETE_IN_PROGRESS   | AWS::IAM::Role                        | AdminRole (AdminRole38563C57)
EksdemoStack | 10/14 | 下午3:21:48 | DELETE_COMPLETE      | AWS::IAM::Role                        | AdminRole (AdminRole38563C57)
EksdemoStack |  9/14 | 下午3:21:49 | DELETE_COMPLETE      | AWS::IAM::Role                        | Cluster/NodegroupDefaultCapacity/NodeGroupRole (ClusterNodegroupDefaultCapacityNodeGroupRole55953B04)
EksdemoStack |  8/14 | 下午3:21:49 | DELETE_COMPLETE      | AWS::SSM::Parameter                   | Cluster/KubectlReadyBarrier (ClusterKubectlReadyBarrier200052AF)    
 8/14 Currently in progress: EksdemoStack, awscdkawseksKubectlProviderNestedStackawscdkawseksKubectlProviderNestedStackResourceA7AEBA6B
EksdemoStack |  7/14 | 下午3:41:52 | DELETE_COMPLETE      | AWS::CloudFormation::Stack            | @aws-cdk--aws-eks.KubectlProvider.NestedStack/@aws-cdk--aws-eks.KubectlProvider.NestedStackResource (awscdkawseksKubectlProviderNestedStackawscdkawseksKubectlProviderNestedStackResourceA7AEBA6B) 
EksdemoStack |  7/14 | 下午3:41:53 | DELETE_IN_PROGRESS   | Custom::AWSCDK-EKS-Cluster            | Cluster/Resource/Resource/Default (Cluster9EE0221C) 
 7/14 Currently in progress: EksdemoStack, Cluster9EE0221C
EksdemoStack |  6/14 | 下午3:43:08 | DELETE_COMPLETE      | Custom::AWSCDK-EKS-Cluster            | Cluster/Resource/Resource/Default (Cluster9EE0221C) 
EksdemoStack |  6/14 | 下午3:43:09 | DELETE_IN_PROGRESS   | AWS::IAM::Policy                      | Cluster/Resource/CreationRole/DefaultPolicy (ClusterCreationRoleDefaultPolicyE8BDFC7B)
EksdemoStack |  6/14 | 下午3:43:09 | DELETE_IN_PROGRESS   | AWS::EC2::SecurityGroup               | Cluster/ControlPlaneSecurityGroup (ClusterControlPlaneSecurityGroupD274242C)
EksdemoStack |  6/14 | 下午3:43:09 | DELETE_IN_PROGRESS   | AWS::CloudFormation::Stack            | @aws-cdk--aws-eks.ClusterResourceProvider.NestedStack/@aws-cdk--aws-eks.ClusterResourceProvider.NestedStackResource (awscdkawseksClusterResourceProviderNestedStackawscdkawseksClusterResourceProviderNestedStackResource9827C454) 
EksdemoStack |  5/14 | 下午3:43:09 | DELETE_COMPLETE      | AWS::IAM::Policy                      | Cluster/Resource/CreationRole/DefaultPolicy (ClusterCreationRoleDefaultPolicyE8BDFC7B)
EksdemoStack |  4/14 | 下午3:43:09 | DELETE_COMPLETE      | AWS::EC2::SecurityGroup               | Cluster/ControlPlaneSecurityGroup (ClusterControlPlaneSecurityGroupD274242C)
EksdemoStack |  4/14 | 下午3:43:10 | DELETE_IN_PROGRESS   | AWS::IAM::Role                        | Cluster/Role (ClusterRoleFA261979)
EksdemoStack |  3/14 | 下午3:43:11 | DELETE_COMPLETE      | AWS::IAM::Role                        | Cluster/Role (ClusterRoleFA261979)
 3/14 Currently in progress: EksdemoStack, awscdkawseksClusterResourceProviderNestedStackawscdkawseksClusterResourceProviderNestedStackResource9827C454
EksdemoStack |  2/14 | 下午3:44:10 | DELETE_COMPLETE      | AWS::CloudFormation::Stack            | @aws-cdk--aws-eks.ClusterResourceProvider.NestedStack/@aws-cdk--aws-eks.ClusterResourceProvider.NestedStackResource (awscdkawseksClusterResourceProviderNestedStackawscdkawseksClusterResourceProviderNestedStackResource9827C454) 
EksdemoStack |  2/14 | 下午3:44:11 | DELETE_IN_PROGRESS   | AWS::IAM::Role                        | Cluster/Resource/CreationRole (ClusterCreationRole360249B6) 
EksdemoStack |  1/14 | 下午3:44:12 | DELETE_COMPLETE      | AWS::IAM::Role                        | Cluster/Resource/CreationRole (ClusterCreationRole360249B6) 
EksdemoStack |  1/14 | 下午3:44:13 | ROLLBACK_FAILED      | AWS::CloudFormation::Stack            | EksdemoStack The following resource(s) failed to delete: [ClusterAwsAuthmanifestFE51F8AE].

Failed resources:
EksdemoStack | 下午2:21:22 | CREATE_FAILED        | AWS::EKS::Nodegroup                   | Cluster/NodegroupDefaultCapacity (ClusterNodegroupDefaultCapacityDA0920A3) Nodegroup ClusterNodegroupDefaultCapa-cSKLvWa4Tbo3 failed to stabilize: [{Code: NodeCreationFailure,Message: Instances failed to join the kubernetes cluster,ResourceIds: [i-02d2213bead380a29, i-0917ddef8f04b94b8]}]
        new Nodegroup (C:\Users\182558\eksdemo\node_modules\@aws-cdk\aws-eks\lib\managed-nodegroup.ts:201:22)
        \_ Cluster.addNodegroupCapacity (C:\Users\182558\eksdemo\node_modules\@aws-cdk\aws-eks\lib\cluster.ts:889:12)
        \_ new Cluster (C:\Users\182558\eksdemo\node_modules\@aws-cdk\aws-eks\lib\cluster.ts:822:14)
        \_ new EksdemoStack (C:\Users\182558\eksdemo\lib\eksdemo-stack.ts:22:21)
        \_ Object.<anonymous> (C:\Users\182558\eksdemo\bin\eksdemo.ts:13:1)
        \_ Module._compile (node:internal/modules/cjs/loader:1101:14)
        \_ Module.m._compile (C:\Users\182558\eksdemo\node_modules\ts-node\src\index.ts:1056:23)
        \_ Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
        \_ Object.require.extensions.<computed> [as .ts] (C:\Users\182558\eksdemo\node_modules\ts-node\src\index.ts:1059:12)
        \_ Module.load (node:internal/modules/cjs/loader:981:32)
        \_ Function.Module._load (node:internal/modules/cjs/loader:822:12)
        \_ Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
        \_ main (C:\Users\182558\eksdemo\node_modules\ts-node\src\bin.ts:198:14)
        \_ Object.<anonymous> (C:\Users\182558\eksdemo\node_modules\ts-node\src\bin.ts:288:3)
        \_ Module._compile (node:internal/modules/cjs/loader:1101:14)
        \_ Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
        \_ Module.load (node:internal/modules/cjs/loader:981:32)
        \_ Function.Module._load (node:internal/modules/cjs/loader:822:12)
        \_ Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
        \_ node:internal/main/run_main_module:17:47
EksdemoStack | 下午3:21:45 | DELETE_FAILED        | Custom::AWSCDK-EKS-KubernetesResource | Cluster/AwsAuth/manifest/Resource/Default (ClusterAwsAuthmanifestFE51F8AE) CloudFormation did not receive a response from your Custom Resource. Please check your logs for requestId [e74807a4-5bcc-4bde-b858-bc3f11c72c25]. If you are using the Python cfn-response module, you may need to update your Lambda function code so that CloudFormation can attach the updated version.
        new CustomResource (C:\Users\182558\eksdemo\node_modules\@aws-cdk\core\lib\custom-resource.ts:36:21)
        \_ new KubernetesManifest (C:\Users\182558\eksdemo\node_modules\@aws-cdk\aws-eks\lib\k8s-manifest.ts:49:5)
        \_ new AwsAuth (C:\Users\182558\eksdemo\node_modules\@aws-cdk\aws-eks\lib\aws-auth.ts:30:5)
        \_ Cluster.get awsAuth [as awsAuth] (C:\Users\182558\eksdemo\node_modules\@aws-cdk\aws-eks\lib\cluster.ts:898:23)
        \_ new Cluster (C:\Users\182558\eksdemo\node_modules\@aws-cdk\aws-eks\lib\cluster.ts:806:10)
        \_ new EksdemoStack (C:\Users\182558\eksdemo\lib\eksdemo-stack.ts:22:21)
        \_ Object.<anonymous> (C:\Users\182558\eksdemo\bin\eksdemo.ts:13:1)
        \_ Module._compile (node:internal/modules/cjs/loader:1101:14)
        \_ Module.m._compile (C:\Users\182558\eksdemo\node_modules\ts-node\src\index.ts:1056:23)
        \_ Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
        \_ Object.require.extensions.<computed> [as .ts] (C:\Users\182558\eksdemo\node_modules\ts-node\src\index.ts:1059:12)
        \_ Module.load (node:internal/modules/cjs/loader:981:32)
        \_ Function.Module._load (node:internal/modules/cjs/loader:822:12)
        \_ Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
        \_ main (C:\Users\182558\eksdemo\node_modules\ts-node\src\bin.ts:198:14)
        \_ Object.<anonymous> (C:\Users\182558\eksdemo\node_modules\ts-node\src\bin.ts:288:3)
        \_ Module._compile (node:internal/modules/cjs/loader:1101:14)
        \_ Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
        \_ Module.load (node:internal/modules/cjs/loader:981:32)
        \_ Function.Module._load (node:internal/modules/cjs/loader:822:12)
        \_ Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
        \_ node:internal/main/run_main_module:17:47

 ❌  EksdemoStack failed: Error: The stack named EksdemoStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_FAILED (The following re
source(s) failed to delete: [ClusterAwsAuthmanifestFE51F8AE]. )
    at Object.waitForStackDeploy (C:\Users\182558\AppData\Roaming\npm\node_modules\aws-cdk\lib\api\util\cloudformation.ts:307:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at prepareAndExecuteChangeSet (C:\Users\182558\AppData\Roaming\npm\node_modules\aws-cdk\lib\api\deploy-stack.ts:337:26)
    at CdkToolkit.deploy (C:\Users\182558\AppData\Roaming\npm\node_modules\aws-cdk\lib\cdk-toolkit.ts:194:24)
    at initCommandLine (C:\Users\182558\AppData\Roaming\npm\node_modules\aws-cdk\bin\cdk.ts:267:9)
The stack named EksdemoStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_FAILED (The following resource(s) failed to delete: [ClusterAwsAuthmanifestFE51F8AE]. )

**Comment by ryparker** [comment]
Can you investigate the CloudWatch logs of the EKS provider handler Lambdas? Specifically the `onEvent` and `isComplete` handlers. There should be 2 of each, one with a `ProviderFramework` prefix and one without. Look out for network request failures & timeouts.

Also does the subnet your EKS cluster is in have access to the internet? I.e. are you using isolated subnets?
