### ISSUE TITLE
(aws-codepipeline-actions): Support cross-account ECS deployments with codepipeline actions

### ISSUE THREAD

**Issue by kartickvijayakumar** [aws/aws-cdk#17558]
### General Issue

Cross Account & Cross Region ECS

### The Question

What is the recommended approach from CDK for cross account ECS deployments through codepipeline at present?

We have a code pipeline that needs to deploy a fargate service into multiple AWS accounts and regions. 

The few things we considered were:
1. Multi-stack approach where we have a pipeline stack with a `CodeBuildAction` that builds the actual service, pushes the container image to ECR and outputs an `imageTag`. Another `CodeBuildAction` does a `cdk synth` for the service stack and outputs its template. We then use `TagParameterContainerImage` with a `CloudFormationCreateUpdateStackAction` to deploy this template with the appropriate `imageTag`  - An ECR resource policy issue described in #15070 blocks this approach to do this cross-account.
2. Single stack with multiple stages in a code-pipeline with instances of `EcsDeployAction` that takes `account` and `region` as parameters and a `role' with appropriate cross-account and cross-region permissions - Something similar to this has been discussed in #11199 but the issue has been closed with a pull request (https://github.com/aws/aws-cdk/pull/15944/) without clarity on the final approach.

Is there any elegant way of doing this today? Probably @skinny85 who has been active in most of these issues and discussions can help us with this.

### CDK CLI Version

1.132.0

### Language

Typescript

**Comment by skinny85** [comment]
Hey @kartickvijayakumar,

the recommended CDK-team solution is to use the [CDK Pipelines module](https://docs.aws.amazon.com/cdk/api/latest/docs/pipelines-readme.html) for these cross-account deployments.

Thanks,
Adam

**Comment by trefore-iakbar** [comment]
Is there any sample code on how to use the CDK Pipelines module to do this?

**Comment by stockf** [comment]
I'm also interested in how exactly you would do this with @aws-cdk/pipelines. I've tried to solve this for a while now and it is really tricky. I endet up with an additional S3 source with my image tag that I want to deploy and a context-variable for the tag that I overwrite in the build phase.

**Comment by skinny85** [comment]
@stockf there's a pretty detailed explanation on how to achieve this by @tobytipton in https://github.com/aws/aws-cdk/pull/17917#issuecomment-993853634.

**Comment by stockf** [comment]
@skinny85 thank you for the reference. Maybe I missed something. But as far as I can see @tobytipton does not use the `@aws-cdk/pipelines` module at all.

**Comment by stockf** [comment]
Thx @tobytipton that is a helpful example.
