### ISSUE TITLE
(ec2): InstanceClass missing G4AD type

### ISSUE THREAD

**Issue by adonisd** [aws/aws-cdk#17565]
### What is the problem?

Per the title, the enum for `ec2.InstanceClass`  is missing the G4AD types

### Reproduction Steps

```
   const instanceType = ec2.InstanceType.of(
      ec2.InstanceClass.G4DN,
      ec2.InstanceSize.XLARGE
    );
```
Try to enum InstanceClass, G4AD is not there.

### What did you expect to happen?

for G4AD to be there

### What actually happened?

It wasn't there :)

### CDK CLI Version

1.132.0

### Node.js Version

14

### OS

Linux

### Language

Typescript

**Comment by jumic** [comment]
@adonisd Would you like to add the missing value to the enum and open a PR? You will find more information in the [contributing guide](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md). I'm sure the CDK team will accept a PR.

Otherwise please let me know. Then I can create the PR.

**Comment by adonisd** [comment]
@cokia thanks for doing this. I just saw that the PR is failing because the title is not "semantic" 
Can you edit the PR title by adding a semantic prefix like fix: or feat: or any other conventional commit type. (https://github.com/zeke/semantic-pull-requests)
