### ISSUE TITLE
aws_lambda: how to use Permission construct

### ISSUE THREAD

**Issue by rittneje** [aws/aws-cdk#17567]
### link to reference doc page

https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_lambda/Permission.html

### Describe your issue?

The documentation for aws_lambda.Permission mentions that it can be passed to the `addToResourcePolicy` method. However, there is no such method on aws_lambda.Function. https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_lambda/Function.html

Am I missing something?

**Comment by kaizen3031593** [comment]
Hi @rittneje! Thanks for reporting! This looks like a typo in the docs, and the actual function you should be looking for is `addPermission`. Quick fix incoming.
