### ISSUE TITLE
(lambda): insights arm64 region-agnostic support

### ISSUE THREAD

**Issue by huntharo** [aws/aws-cdk#17563]
### Description

The statically initialized Insights Versions currently specify only the X64 architecture layer only when creating an ARM64 Lambda:

```typescript
import * as lambda from '@aws-cdk/aws-lambda';
import * as lambdaNodejs from '@aws-cdk/aws-lambda-nodejs';

const someFunc = new lambdaNodejs.NodejsFunction(
  this,
  'some-func',
  {
    functionName: lambdaFuncIndexWriterName,
    architecture: lambda.Architecture.ARM_64,
    insightsVersion: lambda.LambdaInsightsVersion.VERSION_1_0_98_0, // <--- this is only the X64 layer ARN
  });
```

This can by worked around as described in Use Case.

### Use Case

The static versions on `LambaInsightsVersion` use the `region-info` package to provide the region-specific ARNs that vary by account number and layer version per region in a non-trivial way that must be statically specified as facts.

Currently, LambdaInsights for ARN can only be enabled by replicating the `region-info` functionality into a consuming code base and specifying the correct ARN per region for arm64, such as, for US-East-1:

```
insightsVersion: lambda.LambdaInsightsVersion.fromInsightVersionArn(
  'arn:aws:lambda:us-east-1:580247275435:layer:LambdaInsightsExtension-Arm64:1',
),
```

### Proposed Solution

The LambdaInsights version was architecture-agnostic when there was only X64, and, as such, `LambdaInsightsVersion.fromInsightsVersion()` returns an object of type `LambdaInsightsVersion` which has a single architecture-specific ARN property, `layerVersionArn`.

While X64 has many versions of Lambda Insights layers, there appears to be only version `1` of the layer for arm64 for version `1.0.98.0`.  Currently, the `configureLambdaInsights` function makes no attempt to validate that the specified version has an ARN available for the architecture of the lambda function (which is fine since this capability did not previously exist).

I have a partial PR put together for this and would like to try to finish it up with some guidance.

# Proposal
- `packages/@aws-cdk/region-info/build-tools/fact-tables.ts`
  - Add `CLOUDWATCH_LAMBDA_INSIGHTS_ARM_ARNS`
  - Single version in map `1.0.98.0`
- `packages/@aws-cdk/region-info/build-tools/generate-static-data.ts`
  - Add `checkRegionsSubMap(CLOUDWATCH_LAMBDA_INSIGHTS_ARM_ARNS)`
  - Loop through the new map and `registerFact(region, ['cloudwatchLambdaInsightsArmVersion', version], CLOUDWATCH_LAMBDA_INSIGHTS_ARM_ARNS[version][region]);`
- `packages/@aws-cdk/region-info/lib/fact.ts`
  - Add `public static cloudwatchLambdaInsightsArmVersion(version: string)`
  - The comments says this returns an ARN... but it looks like it actually returns a fact name?
  - Return new fact name of the format `\`cloudwatch-lambda-insights-version-arm:${version.split('.').join('_')}\``
- `packages/@aws-cdk/region-info/lib/region-info.ts`
  - Add `public cloudwatchLambdaInsightsArmArn(insightsVersion: string): string | undefined`
  - Copy of `cloudwatchLambdaInsightsArn` but looks at the ARM fact
- `packages/@aws-cdk/aws-lambda/lib/lambda-insights.ts`
  - Make `layerVersionArn` optional and document it as a user-supplied Arn override
  - Add `layerVersionArnArm` and `layerVersionX64Arm` public readonly optional properties to `LambdaInsightsVersion`
  - Modify `private static fromInsightsVersion(insightsVersion: string): LambdaInsightsVersion` to lookup both the X_64 ARN and the ARM_64 ARN, allowing for the ARM_64 ARN to be missing
    - No longer set `layerVersionArn` in this function but instead set only the two arch-specific arn fields
 - `packages/@aws-cdk/aws-lambda/lib/function.ts`
   - Modify `private configureLambdaInsights(props: FunctionProps): void` to select the `layerVersionArnArm` if `props.architecture` is `ARM_64`

# Trouble Spots
- Copying one line functions seems wrong but also right?
- Creating `CLOUDWATCH_LAMBDA_INSIGHTS_ARM_ARNS` seems to be the only current way to specify another fact set - Is this acceptable or strictly prohibited?
- `LambdaInsightsVersion.layerVersionArn` is problematic as the statically initialized values today are all for `X64`, but when a consumer calls `fromInsightVersionArn` today they can pass the ARM arn which will get exposed on the `layerVersionArn` property
  - We cannot assume that existing usage is always specifying an X64 ARN as I've already got code that is specifying the ARM_64 arn (unless we are ok with making a breaking change quickly)
  - Proposed path forward:
    - Leave `layerVersionArn` but make it optional - When `fromInsightsVersionArn` is called, set `layerVersionArn` and assume that the caller got the architecture correct to match their function
    - Add `layerVersionArmArn` and `layerVersionX64Arn` (all 3 would be optional)
    - Modify `configureLambdaInsights` to use `layerVersionArn` if specified, falling through to use the `props.architecture` to select either `layerVersionArmArn` or `layerVersionX64Arn` and to throw if the selected field is undefined

### Other information

Partial branch for comparison here: https://github.com/aws/aws-cdk/compare/master...huntharo:huntharo/armLambdaInsights?expand=1

### Acknowledge

- [X] I may be able to implement this feature request
- [X] This feature might incur a breaking change

**Comment by nija-at** [comment]
@corymhall - assigning this to you since you have a PR open in this area.

**Comment by corymhall** [comment]
This was addressed in https://github.com/aws/aws-cdk/pull/17665
