### ISSUE TITLE
(sns): Allow delivery retry policy configuration of HTTPS subscription on SNS topic

### ISSUE THREAD

**Issue by kunalshah** [aws/aws-cdk#17576]
### Description

While creating HTTPS Subscription on SNS topic, there's no way to configure the retry policy.

### Use Case

I am creating SNS topic and HTTPS subscription using CDK and want to provide custom delivery retry policy.

### Proposed Solution

Update UrlSubscriptionProps interface to provide deliveryRetryPolicy as well.

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by njlynch** [comment]
Thanks for the feature request.

While you're waiting for the feature, you can use [escape hatches](https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html) to set the underlying Cloudformation properties. (In this case, it looks like the Subscription `DeliveryPolicy`).

Relevant docs on the feature for reference: https://docs.aws.amazon.com/sns/latest/dg/sns-message-delivery-retries.html#creating-delivery-policy

**Comment by fertrevino** [comment]
I just came across this use case, it would be neat it implemented

**Comment by dannellyz** [comment]
Also working this for being able to set the HTTP/S Content Header type via the topic CDK creation for those that have subscribers of multiple types. Thanks!
