### ISSUE TITLE
RDS: change parameterGroup prop for `DatabaseInstanceReadReplica`

### ISSUE THREAD

**Issue by marcmoy** [aws/aws-cdk#17580]
### Description

I would like to apply a different database parameter group to the replica instance that is different than the source database instance.

### Use Case

The source and replica instances may have different clients who may require different database parameter group settings.

### Proposed Solution

Add a new `parameterGroup` option for `DatabaseInstanceReadReplicaProps` when creating a new `DatabaseInstanceReadReplica` instance.

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by skinny85** [comment]
Thanks for opening the issue @marcmoy!

@jogold do you know if is this actually supported by RDS? I assume `DatabaseInstanceReadReplicaProps` not having a `parameterGroup: ParameterGroup` property is not a coincidence 😜.

Thanks,
Adam

**Comment by jogold** [comment]
> is not a coincidence 😜.

not a coincidence, a mistake I think 😄 

It looks like it is supported.
