### ISSUE TITLE
(bootstrap): Enable ECR ScanOnPush by default

### ISSUE THREAD

**Issue by xeroxnir** [aws/aws-cdk#17581]
### Description

Hello,

Enable ScanOnPush (no additional charge) for [CDK bootstrap default ECR Registry](https://github.com/aws/aws-cdk/blob/master/packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml#L203). [See related resource definition](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecr-repository.html)

### Use Case

Building containers using DockerImageAsset, would be important to have visibility into their security vulnerabilities. 

### Proposed Solution

```ContainerAssetsRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName:
        Fn::If:
          - HasCustomContainerAssetsRepositoryName
          - Fn::Sub: "${ContainerAssetsRepositoryName}"
          - Fn::Sub: cdk-${Qualifier}-container-assets-${AWS::AccountId}-${AWS::Region}
       ImageScanningConfiguration: 
         ScanOnPush: true
```

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by rix0rrr** [comment]
I'd love to do this, before before we do it I have an open question to ECR team if there are any downsides to enabling this feature for everyone. I would like to hear back from them before we move on this.

**Comment by Hi-Fi** [comment]
Seems that this is closed already with #17994

**Comment by jeffshep** [comment]
Is there some regression on this feature? It doesn't appear to be in the [latest version of the bootstrap CloudFormation file](https://github.com/aws/aws-cdk/blob/v2.55.1/packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml)?

**Comment by TheRealAmazonKendra** [comment]
Removed in https://github.com/aws/aws-cdk/pull/21342

**Comment by TheRealAmazonKendra** [comment]
Given the comment on that PR about scanning at the repo level being deprecated, is this still a valid issue?

**Comment by jeffshep** [comment]
From my perspective it felt like an out-of-the-box configuration that should have been enabled. However, given the constraints described about applying this globally in [#21342](https://github.com/aws/aws-cdk/pull/21342) , I'd agree it doesn't fit here

**Comment by madeline-k** [comment]
Closing as it looks like this issue is no longer needed. If you think this issue was closed in error, please open a new issue! We will not see any further comments on this one.
