### ISSUE TITLE
(glue): add support for partition indexes

### ISSUE THREAD

**Issue by fs111** [aws/aws-cdk#17589]
### Description

Glue supports partition indexes on tables to speed up queries, but the CDK has no support for creating them. I can manually create them via the AWS cli or in the console afterwards but would prefer to manage them via the CDK.

### Use Case

Managing glue tables via the CDK and benefiting from increased query speed due to partition indexes.

### Proposed Solution

N/A

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by kaizen3031593** [comment]
This isn't something that can be done via cloudformation right? If so, please link me to the corresponding cloudformation resource as I did not find any. 

It still can be done in the CDK however, though it requires use of a `custom resource` to make the correct API call.

**Comment by fs111** [comment]
I could not find anything in cloudformation docs, no. 
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-table.html
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-table-tableinput.html 

Is there a good tutorial for doing that via a custom resource?

**Comment by kaizen3031593** [comment]
To unblock yourself, take a look at the documentation for [`AwsCustomResource`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_custom-resources.AwsCustomResource.html). And I believe the necessary sdk call you want to make is `create-partition-index`.

This particular issue is on my radar and if we're lucky I'll be able to submit a PR for it this week.
