### ISSUE TITLE
(cli): cdk init tries to use names starting with a number as identifier

### ISSUE THREAD

**Issue by ghost** [aws/aws-cdk#17598]
### What is the problem?

Since `cdk init` uses the name of the current directory to build identifiers in the init template, if the current directory starts with a number, this will result in invalid identifiers in the resulting project, since no supported programming languages allows identifiers to start with a number.

I have had customer feedback on the Developer Guide where this was the issue.

### Reproduction Steps

```
mkdir 1example
cd 1example
cdk init --language typescript
tsc
```

The TypeScript compiler gives you 15 errors.

### What did you expect to happen?

`cdk init` should detect the initial numeric character and prefix it with something that makes it a valid identifier. (For example, `cdk`.) Underscore is probably a bad idea because it may have semantic implications, particularly in languages like Python. Alternatively, prompt the user for a new name, or throw an error.

### What actually happened?

`cdk init` went ahead and created a project that cannot work.

### CDK CLI Version

1.132.0

### Framework Version

1.132.0

### Node.js Version

16.7.0

### OS

Windows 10

### Language

Typescript, Python, .NET, Java, Go

### Other information

I may be able to make a PR for this, but probably not within the next month.

**Comment by Jerry-AWS** [comment]
I'm prepared for the answer to "Doc, it hurts when I do this!" to be "Then don't do that." :-)
