### ISSUE TITLE
(module core): how to generate only template file when running app.synth?

### ISSUE THREAD

**Issue by LazzariPaolo** [aws/aws-cdk#17595]
### General Issue

How to generate only template file when running app.synth?

### The Question

Going through the quickstart:
https://docs.aws.amazon.com/cdk/latest/guide/hello_world.html

I'm running:

```python
app = core.App()
HelloCdkStack(app, "HelloCdkStack")
app.synth()
```

this create the following files:

```bash
HelloCdkStack.template
cdk.out
manifest.json
tree.json
```

I only want to generate `HelloCdkStack.template`. How can I disable the generation of the other files?

**Comment by rix0rrr** [comment]
You cannot. Delete them afterwards by any other means.
