### ISSUE TITLE
(cli): cdk deploy with explicit named profile does not support web identity token file

### ISSUE THREAD

**Issue by longility** [aws/aws-cdk#17604]
### General Issue

cdk deploy with explicit named profile does not support web identity token file

### The Question

I'm trying to do a cdk deploy with explicit named profile (e.g. `npx cdk deploy --profile dev`) where the profile looks like the following

~/.aws/config
```
[profile dev]
role_arn = REDACTED
web_identity_token_file = REDACTED
```

However, I'm getting an error to where I narrowed down to `ProcessCredentialsProviderFailure: Profile dev did not include credential process`. I looked through the source code in `aws-sdk` and `aws-cdk` and from my analysis, I think we are not supporting this scenario, is that right?

I need this scenario to be able to chain assumed role. See the bottom section of this: https://github.com/awsdocs/amazon-eks-user-guide/blob/master/doc_source/iam-roles-for-service-accounts-technical-overview.md#cross-account-iam-permissions

### CDK CLI Version

1.132.0

### Language

Typescript

**Comment by rix0rrr** [comment]
It's very probably that the AWS SDK for JS (v2) does not support this authentication method, and therefore neither does the CDK CLI.

**Comment by Console32** [comment]
Please implement some kind of `hint` when this is used. Looking up this error takes hours.
