### ISSUE TITLE
aws-ec2: Cannot create VPC Endpoint using existing VPC & Subnets if cdk.context.json is missing VPC information

### ISSUE THREAD

**Issue by sdobberstein** [aws/aws-cdk#17600]
### What is the problem?

If you have a stack where you need to look up an existing VPC (using `VPC.fromLookup`) and add a VPC Interface Endpoint to it using a subnet selection, it will fail if the `cdk.context.json` file does not exist or does not contain information about that VPC already.

### Assumptions:
- Referencing VPC & Subnets that already exist

### Steps to Reproduce:
1. Populate Account,  Subnet Ids, and VPC Id
2. Ensure `cdk.context.json` either doesn't exist, or at least does not contain information matching your VPC
2. Run `cdk ls`
3. Verify error occurs

        Cannot create a VPC Endpoint with no subnets
        Subprocess exited with error 1

### Workaround:
1. Comment out VPC Interface Endpoint code
2. Run `cdk ls` which should create/update the `cdk.context.json`
3. Uncomment out VPC Interface Endpoint code
4. Run `cdk ls` and it should work

### Code:
```typescript
#!/usr/bin/env node
import 'source-map-support/register';
import * as cdk from '@aws-cdk/core';
import {Construct, Stack, StackProps} from "@aws-cdk/core";
import {InterfaceVpcEndpointAwsService, SubnetFilter, Vpc} from "@aws-cdk/aws-ec2";

const app = new cdk.App();

interface MyStackProps extends StackProps {
  readonly subnetIds: string[];
  readonly vpcId: string;
}

class MyStack extends Stack {
  constructor(scope: Construct, id: string, props: MyStackProps) {
    super(scope, id, props);

    const vpc = Vpc.fromLookup(this, 'Vpc', {
      vpcId: props.vpcId,
    });

    const secretsManagerEndpoint = vpc.addInterfaceEndpoint('SecretsManagerEndpoint', {
      service: InterfaceVpcEndpointAwsService.SECRETS_MANAGER,
      subnets: {
        subnetFilters: [SubnetFilter.byIds(props.subnetIds)],
      },
    });
    secretsManagerEndpoint.connections.allowDefaultPortFromAnyIpv4();
  }
}

new MyStack(app, 'MyStack', {
  env: {
    account: 'xxx',
    region: 'us-east-1',
  },
  subnetIds: [
    'xxx',
    'xxx'
  ],
  vpcId: 'xxx'
});

```

### What did you expect to happen?

I should be able to run CDK commands without an error occurring and without having to comment out portions of my stack in order to generate/update the `cdk.context.json` file.

### What actually happened?

All CDK commands fail with an error and the `cdk.context.json` file is not generated/updated.

### CDK CLI Version

1.132.0

### Node.js Version

v14.17.5

### OS

macOS 11.5.1

### Language

Typescript

### Language Version

TypeScript (3.9.10)

### Other information

The error that you will see after running any CDK command is:

```
Cannot create a VPC Endpoint with no subnets
Subprocess exited with error 1
```

Reference implementation: https://github.com/sdobberstein/cdk-vpc-issue

**Comment by mcivino** [comment]
Hello, this issue is still happening.

Any update on the fix?

**Comment by jonyzp** [comment]
![image](https://github.com/aws/aws-cdk/assets/17963924/881f8f94-5693-437b-ad3d-6cf08e8874e9)
Same error

**Comment by gshpychka** [comment]
> ![image](https://user-images.githubusercontent.com/17963924/250473673-881f8f94-5693-437b-ad3d-6cf08e8874e9.png) Same error

That is not the same error
