### ISSUE TITLE
(custom-resources): cannot find response data key

### ISSUE THREAD

**Issue by greg5123334** [aws/aws-cdk#17613]
### General Issue

Cannot find custom resource reponse data key

### The Question

I am trying to deploy a custom resource via CDK (Typescript). After having tried several approaches I cannot seem to find a way to get it working as expected.

I have checked the Lambda logs to confirm that the response object does indeed contain the ReponseData element with the keys as expected. However, upon deployment this line...

`resource.getAtt('ExpectedData').toString();`

is encountering the following error.

> CustomResource attribute error: Vendor response doesn't contain ExpectedData key in object

================

To confirm whether this is an issue with CDK or with myself, I deployed an official [sample](https://github.com/aws-samples/aws-cdk-examples/tree/master/typescript/custom-resource), which works just fine. However, what i noticed is that this sample still uses the [@aws-cdk/aws-cloudformation](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-cloudformation-readme.html) module, which is seemingly deprecated. I had therefore tried to use the _[custom-resources](https://docs.aws.amazon.com/cdk/api/latest/docs/custom-resources-readme.html)_ module, which does not seem to work. 

**I am kindly submitting the report to confirm if there is perhaps an issue on CDK's side in the _custom-resources_ module, or if am perhaps doing something wrong on my end?**

Please find snippets of my testing application below, and please let me know if any more info is needed and I'll be happy to share it.

### CDK CLI Version

1.133.0 (build 2dea31a)

### Node.js Version

v16.13.0

### OS

Microsoft Windows 10 Enterprise 10.0.18363 Build 18363

### Language

Typescript

### Other information

lib\MyCustomResource.ts
```

import * as cdk from '@aws-cdk/core';
import * as lambda from '@aws-cdk/aws-lambda';
import { CustomResource, Construct, Stack } from '@aws-cdk/core';
import * as logs from '@aws-cdk/aws-logs';
import * as cr from '@aws-cdk/custom-resources';
import { AwsCustomResource, AwsCustomResourcePolicy, PhysicalResourceId } from '@aws-cdk/custom-resources';
import fs = require('fs');

export interface MyCustomResourceProps extends cdk.StackProps{

}

export class MyCustomResource extends cdk.Construct {

    constructor(scope: cdk.Construct, id: string, props?: MyCustomResourceProps) {
        super(scope, id);

        const fn = new lambda.Function(this, 'MyFunction', {
          runtime: lambda.Runtime.NODEJS_14_X,
          handler: 'index.handler',
          code: new lambda.InlineCode(fs.readFileSync('assets/custom_function.js', { encoding: 'utf-8' })),
        });

        const singleton_fn = new lambda.SingletonFunction(this, 'SingletonFunction', {
            uuid: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx',
            code: new lambda.InlineCode(fs.readFileSync('assets/custom_function.js', { encoding: 'utf-8' })),
            handler: 'index.handler',
            runtime: lambda.Runtime.NODEJS_14_X,
        });

        const myProvider = new cr.Provider(this, 'MyProvider', {
            onEventHandler: fn,
            logRetention: logs.RetentionDays.ONE_DAY,
        });

        const resource = new cdk.CustomResource(this, 'MyCustomResource', {
          resourceType: 'Custom::MyCustomResource',
          serviceToken: myProvider.serviceToken,
          properties: props });

        var responseData = resource.getAtt('ExpectedData').toString();
        new cdk.CfnOutput(this, 'Response', { value: responseData })
    }
}


```

assets/custom_function.ts
```

var response = require('cfn-response');

exports.handler = function (event, context) {
    console.log('REQUEST RECEIVED:\n' + JSON.stringify(event));

    if (event.RequestType === 'Create') {
        console.log('CREATE!');
        var responseData = { 'Message': 'Resource creation successful!', 'ExpectedData': 'ifyouseethisitsworking' }

        response.send(event, context, response.SUCCESS, responseData);
    }
    else if (event.RequestType === 'Update') {
        console.log('UDPATE!');
        response.send(event, context, response.SUCCESS, { 'Message': 'Resource update successful!', 'ExpectedData': 'ifyouseethisitsworking' });
    } else if (event.RequestType === 'Delete') {
        console.log('DELETE!');
        response.send(event, context, response.SUCCESS, { 'Message': 'Resource deletion successful!', 'ExpectedData': 'ifyouseethisitsworking' });
    }
     else {
        console.log('FAILED!');
        response.send(event, context, response.FAILED);
    }
};

```

**Comment by rix0rrr** [comment]
If you are using the `custom-resources` module, you should not be using `response.send()` method. Instead, you return an object like this:

https://github.com/aws/aws-cdk/blob/2d81a0b6fbc32909b8830d4430f18e9c3a3ea132/packages/%40aws-cdk/custom-resources/test/provider-framework/integration-test-fixtures/s3-file-handler/index.ts#L49-L55

The Provider will take care of sending the response back to CloudFormation.

See here for examples: https://docs.aws.amazon.com/cdk/api/latest/docs/custom-resources-readme.html#provider-framework-examples

Using `cfn-response.send()` directly is appropriate for "naked" Custom Resources without a Provider.
