### ISSUE TITLE
`@aws-cdk/core`: The `Construct.prepare()` method's description is vague

### ISSUE THREAD

**Issue by parzhitsky** [aws/aws-cdk#17612]
### link to reference doc page

https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.Construct.html#protected-prepare

### Describe your issue?

I've been trying (and failing so far) to use AWS CDK without defining everything in a class constructor, like [in this example app](https://github.com/aws-samples/aws-cdk-examples/blob/master/typescript/api-cors-lambda-crud-dynamodb/index.ts#L9-L92).

Recently I've found this method on constructs, `prepare()` (and its alias `onPrepare()`). Its high-level description suggests that this is what I might need to break the horrible pattern of doing _literally everything_ in the constructor:

> This method can be implemented by derived constructs in order to perform final changes before synthesis. prepare() will be called after child constructs have been prepared.

But later on, it adds:

> This is an advanced framework feature. Only use this if you understand the implications.

&hellip; and these "implications" are nowhere to be found.

May I ask to improve the method's description? Specifically, what exactly is meant by "advanced framework", what are the other features of this framework, which ones are advanced, which ones are not, and where does `prepare()` fits into this picture?

**Comment by rix0rrr** [comment]
I think the most important implication is constructs you add during the execution of this method will themselves not be `prepare`d (so you shouldn't be adding any constructs that rely on that happening).

`prepare` is a method of last resort, for constructs to fix up their own state just before rendering in some conditions (for example, to render default values if certain mutator methods did *not* get called).

`prepare()` is deprecated and will be removed in v2. I would not suggest relying on it.

----

I understand you might have psychological aversion to doing a lot of work in the constructor. Try to see construct definitions like a set of declarations that just happen to produce an initialized object (where our Stack *definitely* has a `Table` and the compiler can verify that this member got assigned in the constructor so we can rely on this in the rest of the program).

You are of course free to write constructs like this:

```ts
class MyStack extends Stack {
  public readonly bucket: Bucket | undefined;
  
  public initializeMe() {
    this.bucket = new Bucket(this, 'Bucket');
  }
}

// ...

const stack = new MyStack(this, 'MyStack');
stack.initializeMe();
```
