### ISSUE TITLE
(module name): short issue description

### ISSUE THREAD

**Issue by kamipatel** [aws/aws-cdk#17616]
### General Issue

cdk - cfn.CustomResource deprecation message

### The Question

Hi,

In my following Javascript CDK, I am getting deprecation error message for  cfn.CustomResource and cfn.CustomResourceProvider. what is the alternative?  Thanks!

    const crResource = new cfn.CustomResource(this, 'Resource', {
      provider: cfn.CustomResourceProvider.lambda(crHandler),
      properties: props
  });

### CDK CLI Version

aws-cli/2.1.27

### OS

mac

### Language

Typescript

### Language Version

Javascript

### Other information

Hi,

In my following Javascript CDK, I am getting deprecation error message for  cfn.CustomResource and cfn.CustomResourceProvider. what is the alternative?  Thanks!

    const crResource = new cfn.CustomResource(this, 'Resource', {
      provider: cfn.CustomResourceProvider.lambda(crHandler),
      properties: props
  });

**Comment by rix0rrr** [comment]
It's `CustomResource` in the `core` library:

![image](https://user-images.githubusercontent.com/524162/142835731-c0ea0e07-c628-434c-aa81-55145b0ab16c.png)


https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cloudformation.CustomResource.html
