### ISSUE TITLE
(cli): bootstrapping for CDK v2

### ISSUE THREAD

**Issue by trondhindenes** [aws/aws-cdk#17611]
### General Issue

SSM parameter /cdk-bootstrap/hnb659fds/version not found. Has the environment been bootstrapped?

### The Question

I'm starting to plan upgrading to cdk v2. I noticed this error when I upgraded one of our sample apps to cdk v2:
```
SSM parameter /cdk-bootstrap/hnb659fds/version not found. Has the environment been bootstrapped?
```
We have multiple cdk apps running in the same aws account and are unable to upgrade these to cdk v2 simultaneously.
I checked the https://docs.aws.amazon.com/cdk/latest/guide/work-with-cdk-v2.html guide, and while it mentions that re-bootstrapping is a required prerequisite for cdk v2, it says nothing about interop between v1 and v2 stacks. This guide: https://aws.amazon.com/about-aws/whats-new/2021/04/aws-cloud-development-kit-aws-cdk--v2-and-go-cdk-is-now-available-for-developer-preview/ mentions "...for most projects, can be accomplished with a one-time, safe re-bootstrapping of your AWS accounts" but it doesn't specify what it's safe _from_. Like, why wouldn't it be safe?

So my question: Will cdk v2 support a mix of v1 and v2-based stacks in the same aws account? Some more documentation around this topic would be very helpful

### CDK CLI Version

2.0.0-rc.30 (build 6051e07)

### Language

Python

**Comment by peterwoodworth** [comment]
Hey @trondhindenes 

From the docs you linked: this part in particular sticks out to me:

>CDK v2 requires that the environments you deploy into be boostrapped using the modern bootstrap stack; the legacy stack is no longer supported. CDK v2 furthermore requires a new version of the modern stack. Simply re-bootstrap the affected environments to upgrade them. It is not necessary to set any feature flags or environment variables to specify the modern bootstrap stack.

If we go to the [bootstrapping docs](https://docs.aws.amazon.com/cdk/latest/guide/bootstrapping.html#bootstrapping-templates), we'll find that it says this:

> In AWS CDK version 2, the modern template will be the default bootstrapping template. In version 1, manually select the modern template when bootstrapping by setting the CDK_NEW_BOOTSTRAP environment variable.

So essentially, I'm pretty sure v2 just uses the modern bootstrapping template. One of the differences listed between the legacy and modern templates is the presence of an `SSM parameter for versioning`.

Since you're running into an error saying the parameter hasn't been found, your application probably isn't using the right synthesizer (see the bootstrapping docs for more info). The docs gives advice on how to avoid these kinds of errors:
> Tip
>We recommend always setting CDK_NEW_BOOTSTRAP when you want to bootstrap using the modern template. The context key is supported to make sure you bootstrap correctly if your app uses the DefaultStackSynthesizer, but relies on you being in an app's directory when bootstrapping.
Hope this helped! Let me know if you have any other questions

**Comment by trondhindenes** [comment]
Thanks! I'm just trying to get a definitive answer to:

is it supported to use v1-based stacks with a v2-bootstrapped account?
I'm sure this will affect how many current cdk users plan to perform the v2 upgrade, so calling it out clearly in the documentation would be really good.

**Comment by peterwoodworth** [comment]
Yes - V1 based stacks support using the modern bootstrapping template, so you will still be able to deploy v1 based stacks in an account bootstrapped for v2.

To put it another way - if you `cdk bootstrap` with the modern template on the latest version of v1, and then bootstrap on v2, the second bootstrap will say that no changes have been made.

**Comment by trondhindenes** [comment]
thanks for confirming!

**Comment by peterwoodworth** [comment]
No problem, I've made the note that this should be more clear. Thank you for the feedback!

**Comment by Almenon** [comment]
I ran into the same error. I _thought_ I bootstrapped the account for the very first time, but turns out it had already been bootstrapped a long time ago. Deleting the bootstrap cloudformation stack and re-bootstrapping fixed it.
