### ISSUE TITLE
(apigateway): Tokens in ApiDefinition.fromInline improperly handled

### ISSUE THREAD

**Issue by asvarga** [aws/aws-cdk#17640]
### What is the problem?

Using CDK [Tokens](https://docs.aws.amazon.com/cdk/latest/guide/tokens.html) in an OpenAPI model read by [ApiDefinion.fromInline](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-apigateway.ApiDefinition.html#static-fromwbrinlinedefinition) seems to be supported. For example, putting something like "${Token[TOKEN.123]}" returned by `foo_role.roleArn` in a model might expand to CloudFormation yaml like: 

```yaml
Fn::GetAtt:
  - FooRole1A2B3C4D
  - Arn
```

However this expansion is problematic when done inside of certain intrinsic functions like [`Fn::Sub`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-sub.html). For example, something like `{ "Fn::Sub": "${Token[TOKEN.123]}" }` in the model might expand to:

```yaml
Fn::Sub:
  Fn::GetAtt:
    - FooRole1A2B3C4D
    - Arn
```

This is malformed because `Fn::Sub` can only contain a string or list of string and parameters. In this case we can simply remove the `Fn::Sub`, but this isn't possible when a string contains both pseudo-parameters like "${AWS::Region}" as well as tokens like "${Token[TOKEN.123]}".

### Reproduction Steps

Include something like the following in a stack:

```ts
const model = {..., 
  { "Fn::Sub": foo_role.roleArn },
...};
ApiDefinion.fromInline(model);
```

### What did you expect to happen?

Produce well-formed CloudFormation template.

### What actually happened?

Gives error: "Template error: One or more Fn::Sub intrinsic functions don't specify expected arguments. Specify a string as first argument, and an optional second argument to specify a mapping of values to replace in the string"

### CDK CLI Version

1.132.0

### Node.js Version

v12.22.7

### OS

Amazon Linux 2

### Language

Typescript

### Language Version

4.0.5

### Other information

I was able to work around the issue with some code to rewrite model objects.

**Comment by nija-at** [comment]
> Using CDK Tokens in an OpenAPI model read by ApiDefinion.fromInline seems to be supported

This is not supported.
