### ISSUE TITLE
(eks): Unable to use Bottlerocket for managed nodegroup

### ISSUE THREAD

**Issue by juissi-t** [aws/aws-cdk#17641]
### What is the problem?

I'm trying to set up a new nodegroup which uses Bottlerocket. It fails with the following error:

```
Error: The specified AMI does not match the instance types architecture, either specify AL2_x86_64 or dont specify any
```

### Reproduction Steps

```typescript
import { App, Stack } from '@aws-cdk/core';
import { InstanceType } from '@aws-cdk/aws-ec2';
import { Cluster, KubernetesVersion, NodegroupAmiType } from '@aws-cdk/aws-eks';

const cluster = new Cluster(new Stack(new App()), 'eks-test-cluster', {
  version: KubernetesVersion.V1_21,
});
cluster.addNodegroupCapacity('bottlerocket', {
  instanceTypes: [new InstanceType('m5a.xlarge')],
  amiType: NodegroupAmiType.BOTTLEROCKET_X86_64,
});
```

### What did you expect to happen?

I should not get an error and the nodegroup should be able to use Bottlerocket.

### What actually happened?

I get the error mentioned above.

### CDK CLI Version

1.133.0 (build 2dea31a)

### Node.js Version

v16.13.0

### OS

Linux

### Language

Typescript

### Language Version

4.0.5

### Other information

Looks like https://github.com/aws/aws-cdk/blob/v1.133.0/packages/@aws-cdk/aws-eks/lib/managed-nodegroup.ts#L367 checks that the given AMI type matches the expected AMI type. `getAmiType` calls `getAmiTypeForInstanceType`, which only lists `NodegroupAmiType.AL2_X86_64` as the default version, and not the Bottlerocket enums at all.

**Comment by jtnz** [comment]
Same here on `1.134.0` (all libs version `1.134.0`).

**Comment by pahud** [comment]
Looking into this.

**Comment by pahud** [comment]
OK I think it's now difficult to guess the `amiType` simply from the instance type provided as we not only support AL2 but also Bottlerocket now(line 364).

Maybe we should remove the expected AMI check?

https://github.com/aws/aws-cdk/blob/2dea31a581e7e066195eee30aa93616b123c2ee4/packages/%40aws-cdk/aws-eks/lib/managed-nodegroup.ts#L362-L370

**Comment by pahud** [comment]
I will cut a PR for this today.
