### ISSUE TITLE
CDK deploy: (Cloud assembly schema version mismatch: Maximum schema version supported is 14.0.0, but found 15.0.0)

### ISSUE THREAD

**Issue by mattiLeBlanc** [aws/aws-cdk#17674]
### What is the problem?

Since upgrading to v1.134 I am getting this error when running a CDK Deploy:
(Cloud assembly schema version mismatch: Maximum schema version supported is 14.0.0, but found 15.0.0)

I get it locally on my new MacBook M1Max but also in Bitbucket Pipelines using `image: node:12.16.1`.
v1.133 did not throw that error.

Locally I am running node 16 which gave me issues deploying my single page app to s3 (all files where empty) whilst running v1.68, hence the upgrade to 133. However with 134 I get this new error.

Overall, should I be running Node 14 or 16? 

### Reproduction Steps

Run node 14, try a deploy of Appsync API with s3 etc, and I am getting this error .

### What did you expect to happen?

No error

### What actually happened?

Error

### CDK CLI Version

1.134.0 (build dd5e12d)

### Framework Version

nodejs

### Node.js Version

16

### OS

osx

### Language

Typescript

### Other information

On bitbucket pipeline is running node 12.

**Comment by mattiLeBlanc** [comment]
Actually downgrading to 133 now also gives that same error `(Cloud assembly schema version mismatch: Maximum schema version supported is 14.0.0, but found 15.0.0)`

**Comment by mattiLeBlanc** [comment]
I found out that `aws-cdk`was having a mismatch. It was easy to not see that this package was not in sync since all the other packages start with `@aws-cdk..`

**Comment by gladykov** [comment]
> I found out that `aws-cdk`was having a mismatch. It was easy to not see that this package was not in sync since all the other packages start with `@aws-cdk..`

But what was acutal fix?

**Comment by oorobets** [comment]
@gladykov Install the same version of cdk as your `aws-cdk` packages.
For dependencies:
```
  "dependencies": {
    "@aws-cdk/aws-apigateway": "^1.154.0",
    "@aws-cdk/aws-route53-targets": "^1.154.0"
}
```
Install `npm -g install aws-cdk@1.154.0`
