### ISSUE TITLE
CDK Deploy issue node 16, cdk 134. Stuck at Custom::CDKBucketDeployment

### ISSUE THREAD

**Issue by mattiLeBlanc** [aws/aws-cdk#17676]
### What is the problem?

Since I got my new macbook with M1Max, and node 16, I had issues deploying my single page apps via CDK deploy to the cloud.
After upgrading to CDK 133 it resolved for on stack, but another stack gets stuck at `Custom::CDKBucketDeployment: CREATE_IN_PROGRESS`
and then in the end I just get a `Received response status [FAILED] from custom resource. Message returned: Command '['/opt/awscli/aws', 's3', 'sync', '--delete', '/tmp/tmpao24rzuq/contents', 's3://earnr-mattijs-signup/']' died with <Sig
nals.SIGKILL: 9>. (RequestId: 8ddc8a69-b63c-48c3-b656-c9f6ea654e97)`.

When I try on my other macbook with Intel processor and Node 14, I can deploy. 
Am I looking at a node 16 issue, or an M1/Rosetta issue?

The 2 s3 buckets where created but I only see a couple of files and folders uploaded and some files are 0 bytes.

### Reproduction Steps

Try a S3 bucket deployment a node 16 platform on an Apple M1 Max

### What did you expect to happen?

Normal deploy

### What actually happened?

Signal timeout, unfinished upload of s3 files

### CDK CLI Version

1.134.0 (build dd5e12d)

### Node.js Version

16

### OS

osx

### Language

Typescript

**Comment by otaviomacedo** [comment]
Hi @mattiLeBlanc. How big is the directory or zip file you're uploading?

**Comment by mattiLeBlanc** [comment]
![image](https://user-images.githubusercontent.com/5285035/143452011-1dfe8e7a-2bb3-4860-9f5b-4b8707fef675.png)

**Comment by otaviomacedo** [comment]
Ok, so it's not a problem files/directories being too large.

>  Am I looking at a node 16 issue, or an M1/Rosetta issue?

I don't have access to an M1 to try this out, but I guess the next step to answer this question is to isolate the variables. What happens with the combinations (M1, Node 14) and (Intel, Node 16)?

**Comment by mattiLeBlanc** [comment]
Hmm, I removed my whole stack from cloud fromage :) and it seem to have resolved the issue for now. Not sure how or why but I am keeping an eye on it.
Closing issue for now.

**Comment by ReidWeb** [comment]
@mattiLeBlanc out of interest did this same stack work on node 16 with your intel mac?

**Comment by mattiLeBlanc** [comment]
I haven't updated my intel machine to node 16 yet.
And I also noticed that the issue is not consistently happening. I think removing my stack did seem to help.
I will keep an eye on it.

**Comment by mattiLeBlanc** [comment]
@otaviomacedo  I am having the issue again in Bitbucket, but also locally:

<img width="1011" alt="Image" src="https://github.com/user-attachments/assets/bdf633db-471a-473f-87c9-88809df4db33" />

eventually it will fail (my dev stack did )

<img width="1122" alt="Image" src="https://github.com/user-attachments/assets/b4d28402-d26d-47fe-81ba-48ecad32931f" />

the message is:
CloudFormation did not receive a response from your Custom Resource. Please check your logs for requestId [a37c224f-86c0-4ab7-bf90-61bf61e0456f]. If you are using the Python cfn-response module, you may need to update your Lambda function code so that CloudFormation can attach the updated version.

What can I do about this other than destroying my stack which Is not an option everytime.
