### ISSUE TITLE
(dynamodb): Changes made to DynamoDB Table capacity are not reflected in global replicas

### ISSUE THREAD

**Issue by rix0rrr** [aws/aws-cdk#17682]
### What is the problem?

(This request came in via internal ticket system, ref V475085540)

We have a dynamo table deployed in us-east-1 with three replica regions using the Table construct. When increasing the read and write autoscale capacity of the table only the table in us-east-1 is updated. We are unable to scale our replicas and are experiencing throttling. 

The replica regions are created as type Custom::DynamoDBReplica in cdk.out, while the table in us-east one is type AWS::DynamoDB::Table. Cloudformation does not update the replica objects. Any guidance on how to scale our replica regions for a global table?

### Reproduction Steps

See above

### What did you expect to happen?

See above

### What actually happened?

See above

### CDK CLI Version

-

### Node.js Version

-

### OS

-

### Language

Typescript

### Other information

Note by @rix0rrr: the custom resource probably needs to be invalidated by making sure properties on the CR change when properties on the base table change (if the CR would even propagate the updates in the first place).

**Comment by skinny85** [comment]
Apologies for missing this one, it somehow fell through the cracks 😕.

I guess what we would have to do here is call the [`UpdateTableReplicaAutoScaling` operation](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_UpdateTableReplicaAutoScaling.html) from our Custom Resource that manages these Tables.

**Comment by Nikhil-Saboo** [comment]
This issue is still not fixed

**Comment by pahud** [comment]
Hi @Nikhil-Saboo if you believe this issue still exists. Please create a new one and link to this one. Thank you.
