### ISSUE TITLE
(opensearch): Unable to create Domain with only one AZ and one subnet

### ISSUE THREAD

**Issue by robertofd1995** [aws/aws-cdk#17697]
### What is the problem?

I am trying to create a domain for opensearch service that is in only one AZ, according to the documentation

 vpc_subnets : The specific vpc subnets the domain will be placed in. You must provide one subnet for each Availability Zone that your domain uses. For example, you must specify three subnet IDs for a three Availability Zone domain. Only used if ``vpc`` is specified. Default: - All private subnets.

vpc_subnets param requests as many subnets as az, but it fails with an array of 1 subnet for 1 az

But if I provide one list with one item it crash in the deploy phase with the following error:

Resource handler returned message: "Invalid request provided: **You must specify exactly one subnet.** (Service: OpenSearch, Status Code: 400, Request ID: 1663c586-064e-4474-9e1e-f9691bdcd191, Extended Request ID: null)" (RequestToken: f08082c2-57ee-32dd-9c81-97e597c4dd76, HandlerErrorCode: InvalidRequest)

### Reproduction Steps

In my case I tried the following:

```python
      vpc = ec2.Vpc(
            self, 
            "VPC",
            # We can host a total of 4,096 IPs inside this VPC,
            # calculator https://www.ipaddressguide.com/cidr
            cidr="10.2.0.0/20",
            # We limit the amount of subnets that we will spawn to use 2 availability zones (AZ)
            max_azs=2,
            subnet_configuration=[
                ec2.SubnetConfiguration(
                    name="Public",
                    subnet_type=ec2.SubnetType.PUBLIC
                ),
                ec2.SubnetConfiguration(
                    name="Private",
                    subnet_type=ec2.SubnetType.PRIVATE
                ),
                ec2.SubnetConfiguration(
                    name="Isolated",
                    subnet_type=ec2.SubnetType.ISOLATED
                )
            ]
        )


        elastich_search_cluster = search. \
            Domain(self, 'ElasticSearchDomain',
                   vpc=vpc,
                   vpc_subnets=[vpc.private_subnets[0]],  # Notice a list with only 1 subnet
                   version=search.EngineVersion.ELASTICSEARCH_6_8,
                   enable_version_upgrade=True,
                   encryption_at_rest=search.EncryptionAtRestOptions(enabled=True),
                   node_to_node_encryption=True,
                   fine_grained_access_control=search.AdvancedSecurityOptions(
                       master_user_name=os.getenv('ELASTIC_SEARCH_USER_MASTER_NAME'),
                       master_user_password=os.getenv('ELASTIC_SEARCH_USER_MASTER_PASSWORD')
                   ),
                   ebs=search.EbsOptions(volume_size=50),
                   capacity=search.CapacityConfig(
                       data_nodes=1,
                       data_node_instance_type="m5.large.search",
                       master_nodes=3,
                       master_node_instance_type="m5.large.search"
                   )
                   ) 
```

I also tried with the zone_awareness explicitly to False, but I get same results as before:

```python
        elastich_search_cluster = search. \
            Domain(self, 'ElasticSearchDomain',
                   vpc=vpc,
                   vpc_subnets=[vpc.private_subnets[0]],
                   zone_awareness=search.ZoneAwarenessConfig(enabled=False),  # We only use one region
                   version=search.EngineVersion.ELASTICSEARCH_6_8,
                   enable_version_upgrade=True,
                   encryption_at_rest=search.EncryptionAtRestOptions(enabled=True),
                   node_to_node_encryption=True,
                   fine_grained_access_control=search.AdvancedSecurityOptions(
                       master_user_name=os.getenv('ELASTIC_SEARCH_USER_MASTER_NAME'),
                       master_user_password=os.getenv('ELASTIC_SEARCH_USER_MASTER_PASSWORD')
                   ),
                   ebs=search.EbsOptions(volume_size=50),
                   capacity=search.CapacityConfig(
                       data_nodes=1,
                       data_node_instance_type="m5.large.search",
                       master_nodes=3,
                       master_node_instance_type="m5.large.search"
                   )
                   )
```

I also tried this:

```python
        elastich_search_cluster = search. \
            Domain(self, 'ElasticSearchDomain',
                   vpc=vpc,
                   vpc_subnets=vpc.private_subnets[0],  # Notice only 1 subnet
                   version=search.EngineVersion.ELASTICSEARCH_6_8,
                   enable_version_upgrade=True,
                   encryption_at_rest=search.EncryptionAtRestOptions(enabled=True),
                   node_to_node_encryption=True,
                   fine_grained_access_control=search.AdvancedSecurityOptions(
                       master_user_name=os.getenv('ELASTIC_SEARCH_USER_MASTER_NAME'),
                       master_user_password=os.getenv('ELASTIC_SEARCH_USER_MASTER_PASSWORD')
                   ),
                   ebs=search.EbsOptions(volume_size=50),
                   capacity=search.CapacityConfig(
                       data_nodes=1,
                       data_node_instance_type="m5.large.search",
                       master_nodes=3,
                       master_node_instance_type="m5.large.search"
                   )
                   ) 
```

But it breaks in the synth phase

### What did you expect to happen?

To be able to create the opensearch domain using one subnet

### What actually happened?

It fails in the deployment phase with the following error:

I provide one list with one item it crash in the deploy phase with the following error:

Resource handler returned message: "Invalid request provided: **You must specify exactly one subnet.** (Service: OpenSearch, Status Code: 400, Request ID: 1663c586-064e-4474-9e1e-f9691bdcd191, Extended Request ID: null)" (RequestToken: f08082c2-57ee-32dd-9c81-97e597c4dd76, HandlerErrorCode: InvalidRequest)

### CDK CLI Version

1.132.0 (build 5c75891)

### Node.js Version

v14.16.1

### OS

Mac Os Mojave

### Language

Python

### Language Version

3.9.0

**Comment by kaizen3031593** [comment]
Hi @robertofd1995! Try this for me. The type of `Domain.vpc_subnets` is `ec2.subnet_selection[]`. However the type of `[vpc.private_subnets[0]]` is `ec2.i_subnet[]`. This type mismatch may be your issue here. I suggest you do something like this for `vpc_subnets`: 

```py
vpc_subnets=[{
  subnets=vpc.private_subnets[0],
}]
```

As that looks like it will fit in a type `ec2.subnet_selection[]` (please excuse me if that code does not work as is, I'm basically translating from typescript). Link to source code: https://github.com/aws/aws-cdk/blob/df970f296bb24539f263c2fea81d3148089e6bff/packages/%40aws-cdk/aws-ec2/lib/vpc.ts#L252

Also note that the default if you do not set `vpc_subnets` is that the CDK will take all private subnets, which would work for you in this example as well, since you only have 1 private subnet.

Not calling this a bug unless you come back to me with more difficulties!

**Comment by kristianpaul** [comment]
Having similar issue

**Comment by dmsolutionz** [comment]
Having pretty much a similar but related problem.

We have multiple vpcSubnets so we do want to take them all, however the synth will fail with "Resource handler returned message: "Invalid request provided: You must specify exactly one subnet." this is against the documentation that states:

> @default
> - All private subnets.

So we have to have a singular subnet? I'm having to specify like the above like: `privateSubnets[0]` 

Seems like a gap in documentation? Im confused mostly, why can't we keep the defaults and specify a VPC we already have.

**Comment by meniluca** [comment]
As suggested by @kaizencc I tried with the following (but the result was the same)
```
vpc_subnets=[{
    'subnets': [vpc.private_subnets[0]],
}],
```

**Comment by gm-socius** [comment]
Same issue here.
