### ISSUE TITLE
Toolkit: Context in a CI/CD pipeline with restricted developer access

### ISSUE THREAD

**Issue by rix0rrr** [aws/aws-cdk#1769]
In order to have stable context (to make sure AMIs and AZs don't change out from under you when you're making unrelated changes), we're saving retrieved context values to `cdk.json`.

The expectation is that the context will be read on a developer workstation, committed, and then pushed to a CI/CD server which will do networkless synth.

----

However, what if the environment is locked down in such a way that developers don't have access to the production environment(s), but the build server does? 

The devs can't create `cdk.json`; the result of which being that the server will re-read the context every time but will not be able to commit it, so in effect the context becomes "unstable" again.

We should probably support persisting context to different storage mechanisms, such as SSMPS.

**Comment by eladb** [comment]
Interesting, so the idea is that admins will retrieve the context, push it to somewhere and let developers have read access to it. Maybe we can just allow `cdk.json` to be also read from an S3 bucket (given permissions).

**Comment by rix0rrr** [comment]
That could also be a workflow I suppose, but the one I was imagining was where the build server would retrieve and cache the context, so at least it's stable from that point onwards (until it's cleared).

I was thinking SSM Parameter Store is kinda the point for these kinds of values, but I guess S3 would work too.
