### ISSUE TITLE
(iot): TopicRule action for Step Functions in AWS IoT

### ISSUE THREAD

**Issue by yamatatsu** [aws/aws-cdk#17698]
### Description

The CDK has no support to trigger Step Functions via AWS IoT Rule.

### Use Case

Adding the action that triggers Step Functions to AWS IoT topic rule.

### Proposed Solution

Implementing action class.

Probably, following PRs help coding.

- https://github.com/aws/aws-cdk/pull/17503
- https://github.com/aws/aws-cdk/pull/17466
- https://github.com/aws/aws-cdk/pull/17307

### Other information

Follofing documentation will be help.

- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-iot-topicrule-stepfunctionsaction.html

It will be good first issue for learning implement feature in CDK!

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by sholtomaud** [comment]
any update on this issue? Has the feature been implemented in v2?

**Comment by yamatatsu** [comment]
@sholtomaud Nope yet. But you can use escape-hatch as following:

```ts
import * as iot from '@aws-cdk/aws-iot-alpha';

const stateMachine = new new sfn.StateMachine(this, 'StateMachine', {
  definition,
});

const role = new iam.Role(this, 'MyRole', {
  assumedBy: new iam.ServicePrincipal('iot.amazonaws.com'),
});
stateMachine.grantStartExecution(role);

new iot.TopicRule(this, 'TopicRule', {
  sql: iot.IotSql.fromStringAsVer20151008("SELECT topic(2) as device_id FROM 'device/+/data'"),
  actions: [
    {
      bind: () => ({
        configuration: {
          stepFunctions: {
            stateMachineName: stateMachine.stateMachineName,
            executionNamePrefix: "myExecution", // optional
            roleArn: role.roleArn,
          }
        },
      }),
    },
  ],
});
```

This example needs to install `@aws-cdk/aws-iot-alpha` if you are using aws-cdk v2.

**Comment by sholtomaud** [comment]
Ok, looks interesting.

**Comment by Bakhoj** [comment]
Is there a dirty fix when using python?
