### ISSUE TITLE
(opensearch): expose generated security group as part of Domain object

### ISSUE THREAD

**Issue by jeffb4** [aws/aws-cdk#17693]
### Description

The opensearch.Domain object does not currently expose the SecurityGroup that it creates by default

### Use Case

I would like to add rules to the security group created by the `opensearch.Domain` constructor, without having to create a security group, add the rules, and provide the sg during the domain constructor call

### Proposed Solution

new property `Domain.security_group`

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by kaizen3031593** [comment]
We would have to expose a list of security groups rather than a single one as `Domain` allows for multiple security groups.

**Comment by jeffb4** [comment]
Can this be reopened?
