### ISSUE TITLE
(iot): TopicRule action for CloudWatch alarms in AWS IoT

### ISSUE THREAD

**Issue by yamatatsu** [aws/aws-cdk#17705]
### Description

The CDK has no support to put CloudWatch alarm status via AWS IoT Rule.

### Use Case

Adding the action that puts CloudWatch alarm status to AWS IoT topic rule.

### Proposed Solution

Implementing action class.

Probably, following PRs help coding.

- https://github.com/aws/aws-cdk/pull/17503
- https://github.com/aws/aws-cdk/pull/17466
- https://github.com/aws/aws-cdk/pull/17307

### Other information

Follofing documentation will be help.

- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-iot-topicrule-cloudwatchalarmaction.html

It will be good first issue for learning implement feature in CDK!

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by peterwoodworth** [comment]
Thanks for the feature requests! Hopefully with these up, people will be able to chip down on adding these actions

**Comment by jerry-shao** [comment]
I would like to implement this :D

**Comment by jerry-shao** [comment]
PR: https://github.com/aws/aws-cdk/pull/18021
