### ISSUE TITLE
(iot): TopicRule action for HTTP in AWS IoT

### ISSUE THREAD

**Issue by yamatatsu** [aws/aws-cdk#17704]
### Description

The CDK has no support to post HTTP request via AWS IoT Rule.

### Use Case

Adding the action that posts HTTP requests to AWS IoT topic rule.

### Proposed Solution

Implementing action class.

Probably, following PRs help coding.

- https://github.com/aws/aws-cdk/pull/17503
- https://github.com/aws/aws-cdk/pull/17466
- https://github.com/aws/aws-cdk/pull/17307

### Other information

Follofing documentation will be help.

- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-iot-topicrule-httpaction.html

It will be good first issue for learning implement feature in CDK!

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by nanofaroque** [comment]
Any update on this feature delivery date?

**Comment by yamatatsu** [comment]
@nanofaroque 
There is no set delivery date as far as I know.

If you wanna use httpAction soon, you can use following escape hatch: 
```ts
new iot.TopicRule(this, "TopicRule", {
  sql: iot.IotSql.fromStringAsVer20160323("SELECT * FROM 'device/+/data'"),
  actions: [
    {
      bind: () => ({
        configuration: {
          http: {
            url: "",
          },
        },
      }),
    },
  ],
});```
