### ISSUE TITLE
(core/aws-lambda-nodejs/cli): Assets are not built for deploys with glob patterns (e.g. "*/Stack1") with --exclusively option

### ISSUE THREAD

**Issue by slaskowski-transactionlink** [aws/aws-cdk#17717]
### What is the problem?

CDK skips bundling for some stacks for complex paths and glob patterns like `cdk deploy -e "*/Stack*"`

### Reproduction Steps

```ts
// bin/app.ts
import * as lambda from "@aws-cdk/aws-lambda-nodejs";
import * as cdk from '@aws-cdk/core';

const production = new cdk.Stack(new cdk.App(), "prod");
const app = new cdk.Stack(production, "app");
new lambda.NodejsFunction(app, 'handler',  {});
```

```ts
// bin/app.handler.ts
export const handler = () => {}

```

Now run `cdk deploy -e "*/app"`

### What did you expect to happen?

I expected stack stack to was successfully deployed 

### What actually happened?

CDK deploys  my entire project instead of bundled code of lambda

### CDK CLI Version

134.0 (build dd5e12d)

### Node.js Version

v14.17.5

### OS

Mac OS X 11.2.3

### Language

Typescript

**Comment by jogold** [comment]
The fix from #17210 is not included in v1.134.0.

**Comment by slaskowski-transactionlink** [comment]
@jogold can i test it on 1.135 somehow? Ive seen the merged pr and i dont see it fixing this one.

**Comment by jogold** [comment]
v1.135.0 is not released yet but you can patch v1.134.0 if you don't want to wait.

If I change `Stage/Stack1` with `*/Stack1` in my test here https://github.com/aws/aws-cdk/blob/8191f1f1d4072feeba74844a31c942909cee7d83/packages/%40aws-cdk/core/test/staging.test.ts#L869 the test still passes. So I expect this to work with `*/Stack1`, no?

And then if I test with `*/Stack*` both assets are bundled.

**Comment by slaskowski-transactionlink** [comment]
@jogold tahnk you i will setup the project locally later and make sure tests pass for my use cases and then close the issue if it does

**Comment by peterwoodworth** [comment]
Thanks for the help here @jogold, appreciated as always
