### ISSUE TITLE
(aws-rds): Cannot change removal policy of DatabaseInstance's admin secret

### ISSUE THREAD

**Issue by mskrip** [aws/aws-cdk#17728]
### What is the problem?

It's not possible to change the default DatabaseInstance.secret removal policy. The instance of the secret does have a `apply_removal_policy` method bound to it (I can see it when printing `dir(secret)`), but calling it makes no difference.

### Reproduction Steps

Create a `rds.DatabaseInstance` and the master secret will have a default removal policy `DELETE` with no way to change it (even if changing the removal policy of the instance).

### What did you expect to happen?

I would expect, that calling `rds_instance.secret.apply_removal_policy` would apply the removal policy.

### What actually happened?

It doesn't

### CDK CLI Version

1.134.0 (build dd5e12d)

### Framework Version

1.134.0

### Node.js Version

v16.12.0

### OS

Arch Linux 5.15.4-arch1-1

### Language

Python

### Language Version

3.9.7

**Comment by peterwoodworth** [comment]
I believe this is because the secret is declared as an `ISecret`, which doesn't have the `applyRemovalPolicy()` function. I'm not sure if this is something that we can change

To work around this and apply the removal policy you want to the secret, you can use an [escape hatch](https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html)!

Here's an example for TypeScript, let me know if you need one for Python.

```ts
    const db = new DatabaseInstance(this, 'db', {
      vpc: vpc,
      engine: dsb.DatabaseInstanceEngine.postgres({version: dsb.PostgresEngineVersion.VER_13_4})
    });

    const secret = db.node.children[2] as DatabaseSecret
    secret.applyRemovalPolicy(RemovalPolicy.RETAIN)
```

**Comment by skinny85** [comment]
Hey @mskrip,

thanks for opening the issue. Looks like the [`Resource` class already has `applyRemovalPolicy()` method](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.Resource.html#applywbrremovalwbrpolicypolicy), so this should just be a matter of adding that same method to the [`IResource` interface](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.IResource.html).

[PRs are very welcome](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md)! 🙂

Thanks,
Adam

**Comment by mskrip** [comment]
@skinny85 Unfortunately, the #17746 did not really fix the underlying issue here, since `rds_instance.secret` is not the `Secret` resource but `SecretTargetAttachment`. Therefore, I still have to use the escape hatch here.

**Comment by skinny85** [comment]
That's a fair point @mskrip. I'm re-opening this one.

I'm wondering what should be correct behavior be here? Should calling `applyRemovalPolicy()` on the `SecretTargetAttachment` also change the retention policy of the `Secret` it's pointing to?

**Comment by mskrip** [comment]
@skinny85 Yes, that makes sense. Maybe it would be useful if `SecretTargetAttachment` had a reference to the `Secret` resource it's attaching so the policies can be applied explicitly. But that might be too much of a change to the interface so I'm not sure.
