### ISSUE TITLE
Support adding custom attributes on ECS container instances

### ISSUE THREAD

**Issue by SoManyHs** [aws/aws-cdk#1772]
Currently, the ECS Cluster construct does not support adding [custom attributes](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_Attribute.html#ECS-Type-Attribute-targetType) on container instances. These would be necessary for for specifying a `memberOf` placement constraint. using the cluster query language for custom attributes. https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-placement-constraints.html

**Comment by rix0rrr** [comment]
Still relevant

**Comment by allisaurus** [comment]
Looks like setting custom attributes needs to be done at registration time by setting [`ECS_INSTANCE_ATTRIBUTES`](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-config.html#ecs-instance-attributes) via user data, similar to how [cluster name and spot draining is configured](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-ecs/lib/cluster.ts#L198-L210).

Two concerns with this:
1. setting via user data means adding/changing them will require replacing the instances :/
2. you can add up to 10 attributes to an instance, and generating/interpolating that into a user data string like we're doing for cluster names seems rather clunky. May want to instead leverage whatever solution is found for https://github.com/aws/aws-cdk/issues/1711

**Comment by allisaurus** [comment]
Since this will be possible after https://github.com/aws/aws-cdk/issues/1711 is addressed, closing as a duplicate.
