### ISSUE TITLE
(elbv2): LoadBalancer.logAccessLogs results in breached S3.6 security best practice

### ISSUE THREAD

**Issue by brammiedemaatos** [aws/aws-cdk#17726]
### What is the problem?

NetworkLoadBalance.log_access_logs method results in major Security reporting s3.6 due to too liberal policy creation. 
See links below:
https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_elasticloadbalancingv2/NetworkLoadBalancer.html?highlight=log_access_logs#aws_cdk.aws_elasticloadbalancingv2.NetworkLoadBalancer.log_access_logs
https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#s3-6-remediation

### Reproduction Steps

Spin up a AWS NetworkLoadBalancer instance using the python CDK and add access log logging with the log_access_logs method.

### What did you expect to happen?

S3 bucket policy as specified in the AWS method docs referenced in NetworkLoadBalance.log_access_logs of the CDK :
https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-access-logs.html#enable-disable-access-logging

### What actually happened?

policies added had an extra suffix (*) whcih causes the s3.6 Major security warning

### CDK CLI Version

1.3x.x

### Framework Version

Python 1.33.0

### Node.js Version

nodejs-current

### OS

alpine:3.14.0

### Language

Python

### Language Version

3.9.7-r4

### Other information

We deploy in Docker

**Comment by peterwoodworth** [comment]
Here's where the policy is set: https://github.com/aws/aws-cdk/blob/dd5e12d43231d991971de3121928377569b2dd63/packages/%40aws-cdk/aws-elasticloadbalancingv2/lib/shared/base-load-balancer.ts#L253-L258

According to the S3.6 error:

> This control checks whether the S3 bucket policy prevents principals from *other AWS accounts* from performing denied actions on resources in the S3 bucket.

Is the bucket you're trying to use here from a different account?

**Comment by brammiedemaatos** [comment]
The bucket is within the same account in AWS but the logs are being populated from a different Level 1 account. the documentation also states the * is not needed for this. So I believe the suffix "/*" should not be here in the code you linked above. 

Anyway the different account is being set through this method. you can find the reason why in this documentation section (this section was also present at some point in time for the networkloadbalancer): https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-access-logs.html

This results in this policy being added through the method: 
![image](https://user-images.githubusercontent.com/31007923/143838199-aa3229dd-36c4-4381-a12a-af036f31bdb6.png)

**Comment by njlynch** [comment]
> The bucket is within the same account in AWS but the logs are being populated from a different Level 1 account.
> Anyway the different account is being set through this method.

Ah. You're describing the fact that policy grants access to the ELB account with (according to your screenshot above) the `PutObject*` policy, which includes the `PutObjectAcl` action. This isn't about the `*` in the *resource*, it's about the `*` in the *action*.

This is because `bucket.grantWrite()` _used to_ grant `PutObject*` rather than `PutObject`. The behavior was fixed in #12391 back in January, but due to potential breaking changes it was placed under a feature flag. If you set `@aws-cdk/aws-s3:grantWriteWithoutAcl` to `true` in your `cdk.context.json`, the policy will change to remove the asterisk. That will resolve the security best practice.

Closing out. Feel free to comment mentioning me or Peter if you have any follow-ups.

**Comment by brammiedemaatos** [comment]
Ah yes indeed, that screenshot was only in my original discussion comment. Should have added it earlier, i found it weird i ran into this but could not find it with some reason. Thanks, I will add the @aws-cdk/aws-s3:grantWriteWithoutAcl.
