### ISSUE TITLE
(@aws-cdk/aws-ecs): Fargate with ARM architecture

### ISSUE THREAD

**Issue by Smotrov** [aws/aws-cdk#17732]
### Description

It would be good to have [Graviton2](https://aws.amazon.com/blogs/aws/announcing-aws-graviton2-support-for-aws-fargate-get-up-to-40-better-price-performance-for-your-serverless-containers/) support in CDK for Fargate tasks. 

### Use Case

It is supposed to delivers up to 40 percent better price-performance for our high-load tasks.

### Proposed Solution

Could be something like in FargateTaskDefinitionProps: 
```javascript
const taskDefinition = new ecs.FargateTaskDefinition(this, `task-definition`, {
      architecture: ARM,
});
```

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by peterwoodworth** [comment]
Thanks for opening this feature request @Smotrov 

We currently have something similar for this up, I'll close this issue in favor of that one #17732
