### ISSUE TITLE
core: optionally don't clean up docker image used for bundling

### ISSUE THREAD

**Issue by multimeric** [aws/aws-cdk#17743]
### Description

Allow an option to not clean up the temporary docker images involved in bundling.

### Use Case

When the bundling fails for an unclear reason, it is very difficult to debug. For instance, I am getting "Error: Bundling did not produce any output. Check that content is written to /asset-output.". However when I run the same commands in a docker container myself I successfully get output in that directory. Therefore I need the ability to investigate the bundling in more detail.

If we could restart the same container used for debugging, we could look at the filesystem, and run commands interactively, in order to do this.

### Proposed Solution

* Add a CLI flag such as `--keep-docker`. 
* Then, when this flag is used, the docker containers are not removed (ie the `--rm` flag or equivalent is not used) when issuing the `docker run` commands.

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by rix0rrr** [comment]
This should not be a CLI feature, it should go into the construct library that does bundling directly. The CLI is not involved with bundling at all.

We should probably be setting context to pass that information to the construct library.
