### ISSUE TITLE
(cdk-cfnFlow) : Mapping Tasks and Upserted Fields not showing on Appflow

### ISSUE THREAD

**Issue by ManashJy** [aws/aws-cdk#17748]
### General Issue

Mapping Tasks and Upserted Fields not showing on Appflow

### The Question

**The Problem -** When creating a Flow from S3 bucket to Salesforce via  cfnFlow, the mapping tasks and upserted idFieldNames appears as blank in aws appflow console. 

No errors were given in cdk when using `cdk synth` and `cdk deploy`

The cfnflow code - 

     new appflow.CfnFlow(this, 's3tosf-cdk', {
      
      description: "AppFlow from S3 to Salesforce",
      destinationFlowConfigList: [
        {
          "connectorProfileName": "test_s3_to_sf",
          "connectorType": "Salesforce",
          "destinationConnectorProperties": {
            "salesforce": {
              "errorHandlingConfig": {
                "bucketName": "s3tosf-flow-bucket",
                "bucketPrefix": "error_logs",
              },
              "idFieldNames": [
                "Name"
              ],
              "object": "s3tosfdemo_sf__c",
              "writeOperationType": "UPSERT"
            }
          }
        }
      ],
      flowName: "s3tosf-cdk",
      sourceFlowConfig: {
        "connectorProfileName": "test_s3_to_sf",
        "connectorType": "S3",
        "sourceConnectorProperties": {
          "s3": {
            "bucketName": "s3tosf-flow-bucket",
            "bucketPrefix": "root/"
          }
        }
      },
      
      tasks: [
        {
          "taskType":"Map",
          "sourceFields": [
              "RecordTypeId"
            ],
          "taskProperties": [
              {
                "key":"SOURCE_DATA_TYPE",
                "value":"Text"
              },
              {
                "key":"DESTINATION_DATA_TYPE",
                "value":"Text"
            }
            ],
          "destinationField": "Name",
          "connectorOperator": {
            "salesforce":"NO_OP"
          }
        },
        {
          "taskType":"Map",
          "sourceFields": [
              "Account__c"
            ],
          "taskProperties": [
            {
                "key":"SOURCE_DATA_TYPE",
                "value":"Text"
              },
              {
                "key":"DESTINATION_DATA_TYPE",
                "value":"Text"
            }
            ],
          "destinationField": "Account_c__c",
          "connectorOperator": {
            "salesforce":"NO_OP"
          }
        },
        {
          "taskType":"Map",
          "sourceFields": [
            "allergies__c",
            ],
          "taskProperties": [
              {
                "key":"SOURCE_DATA_TYPE",
                "value":"Text"
              },
              {
                "key":"DESTINATION_DATA_TYPE",
                "value":"Text"
            }
            ],
          "destinationField": "allergies_c__c",
          "connectorOperator": {
            "salesforce":"NO_OP"
          }
        },
        {
          "taskType":"Map",
          "sourceFields": [
            "contact_info_address__c"
          ],
          "taskProperties": [
              {
                "key":"SOURCE_DATA_TYPE",
                "value":"Text"
              },
              {
                "key":"DESTINATION_DATA_TYPE",
                "value":"Text"
            }
            ],
          "destinationField": "contact_info_address_c__c",
          "connectorOperator": {
            "salesforce":"NO_OP"
          }
        },
        {
          "taskType":"Map",
          "sourceFields": [
              "contact_info_bestphone__c"
            ],
          "taskProperties": [
              {
                "key":"SOURCE_DATA_TYPE",
                "value":"Text"
              },
              {
                "key":"DESTINATION_DATA_TYPE",
                "value":"Text"
            }
            ],
          "destinationField": "contact_info_bestphone_c__c",
          "connectorOperator": {
            "salesforce":"NO_OP"
          }
        },
        {
          "taskType":"Map",
          "sourceFields": [
              "contact_info_bestphone_type__c"
            ],
          "taskProperties": [
              {
                "key":"SOURCE_DATA_TYPE",
                "value":"Text"
              },
              {
                "key":"DESTINATION_DATA_TYPE",
                "value":"Text"
            }
            ],
          "destinationField": "contact_info_bestphone_type_c__c",
          "connectorOperator": {
            "salesforce":"NO_OP"
          }
        },
        {
          "taskType":"Map",
          "sourceFields": [
              "contact_info_city__c"
            ],
          "taskProperties": [
              {
                "key":"SOURCE_DATA_TYPE",
                "value":"Text"
              },
              {
                "key":"DESTINATION_DATA_TYPE",
                "value":"Text"
            }
            ],
          "destinationField": "contact_info_city__c",
          "connectorOperator": {
            "salesforce":"NO_OP"
          }
        },
      ],
      triggerConfig: {
        "triggerType": "OnDemand"
      },
    }

The output in aws appflow console - 
![image](https://user-images.githubusercontent.com/95225530/143873289-d7280c2a-b899-4a77-9fe4-4d4fe1fb6644.png)

Also there is no specific way to upload mapped csv file via cdk, so i had to to manual mapping which eventually led to this problem.

**What  should i do to make the mapping tasks appear in appflow?**

### CDK CLI Version

1.110.1

### Node.js Version

14.17.6

### OS

Windows 10

### Language

Typescript

### Language Version

3.9.7

**Comment by peterwoodworth** [comment]
@ManashJy can you check your `cdk synth` output to verify that it synths properly?

**Comment by ManashJy** [comment]
> @ManashJy can you check your `cdk synth` output to verify that it synths properly? Additionally, are you able to provide the arn for this stack?
> 
> Since this is an L1 resource, this would be an issue with cloudformation. I can report the issue to them once you verify that your stack properly synths, and having an arn is helpful for them :)

@peterwoodworth This is the output of `cdk synth` - 
    Resources:
  s3tosfcdk:
    Type: AWS::AppFlow::Flow
    Properties:
      DestinationFlowConfigList:
        - ConnectorProfileName: test_s3_to_sf
          ConnectorType: Salesforce
          DestinationConnectorProperties:
            Salesforce:
              ErrorHandlingConfig:
                BucketName: s3tosf-flow-bucket
                BucketPrefix: error_logs
              IdFieldNames:
                - Name
              Object: s3tosfdemo_sf__c
              WriteOperationType: UPSERT
      FlowName: s3tosf-cdk
      SourceFlowConfig:
        ConnectorProfileName: test_s3_to_sf
        ConnectorType: S3
        SourceConnectorProperties:
          S3:
            BucketName: s3tosf-flow-bucket
            BucketPrefix: root/
      Tasks:
        - ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: Name
          SourceFields:
            - RecordTypeId
          TaskProperties:
            - Key: SOURCE_DATA_TYPE
              Value: Text
            - Key: DESTINATION_DATA_TYPE
              Value: Text
          TaskType: Map
        - ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: Account_c__c
          SourceFields:
            - Account__c
          TaskProperties:
            - Key: SOURCE_DATA_TYPE
              Value: Text
            - Key: DESTINATION_DATA_TYPE
              Value: Text
          TaskType: Map
        - ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: allergies_c__c
          SourceFields:
            - allergies__c
          TaskProperties:
            - Key: SOURCE_DATA_TYPE
              Value: Text
            - Key: DESTINATION_DATA_TYPE
              Value: Text
          TaskType: Map
        - ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: contact_info_address_c__c
          SourceFields:
            - contact_info_address__c
          TaskProperties:
            - Key: SOURCE_DATA_TYPE
              Value: Text
            - Key: DESTINATION_DATA_TYPE
              Value: Text
          TaskType: Map
        - ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: contact_info_bestphone_c__c
          SourceFields:
            - contact_info_bestphone__c
          TaskProperties:
            - Key: SOURCE_DATA_TYPE
              Value: Text
            - Key: DESTINATION_DATA_TYPE
              Value: Text
          TaskType: Map
        - ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: contact_info_bestphone_type_c__c
          SourceFields:
            - contact_info_bestphone_type__c
          TaskProperties:
            - Key: SOURCE_DATA_TYPE
              Value: Text
            - Key: DESTINATION_DATA_TYPE
              Value: Text
          TaskType: Map
        - ConnectorOperator:
            Salesforce: NO_OP
          DestinationField: contact_info_city__c
          SourceFields:
            - contact_info_city__c
          TaskProperties:
            - Key: SOURCE_DATA_TYPE
              Value: Text
            - Key: DESTINATION_DATA_TYPE
              Value: Text
          TaskType: Map
      TriggerConfig:
        TriggerType: OnDemand
      Description: AppFlow from S3 to Salesforce
    Metadata:
      aws:cdk:path: S3TosfStack/s3tosf-cdk

The stack arn is like this -  arn:aws:cloudformation:<region>:<account-id>:stack/S3TosfStack/*

**Comment by peterwoodworth** [comment]
I've reported this internally, I'll provide any updates for you here.

ticket: P55925874

**Comment by ManashJy** [comment]
@peterwoodworth is there any new updates on the issue?

**Comment by peterwoodworth** [comment]
Yes @ManashJy, I received a response on the ticket this morning.

They're asking for a confirmation of behavior; What happens when you try to `aws appflow describe-flow --flow-name s3tosf-cdk`?

**Comment by ManashJy** [comment]
@peterwoodworth This is the output of this command - 
```
{
    "flowArn": "arn:aws:appflow:us-east-1:088533290808:flow/s3tosf-cdk",
    "description": "AppFlow from S3 to Salesforce",
    "flowName": "s3tosf-cdk",
    "kmsArn": "arn:aws:kms:us-east-1:088533290808:key/99a59fe5-f0cc-49ae-93c8-53386bd64aa4",
    "flowStatus": "Active",
    "sourceFlowConfig": {
        "connectorType": "S3",
        "connectorProfileName": "test_s3_to_sf",
        "sourceConnectorProperties": {
            "S3": {
                "bucketName": "s3tosf-flow-bucket",
                "bucketPrefix": "root/"
            }
        }
    },
    "destinationFlowConfigList": [
        {
            "connectorType": "Salesforce",
            "connectorProfileName": "test_s3_to_sf",
            "destinationConnectorProperties": {
                "Salesforce": {
                    "object": "s3tosfdemo_sf__c",
                    "idFieldNames": [
                        "Name"
                    ],
                    "errorHandlingConfig": {
                        "failOnFirstDestinationError": false,
                        "bucketPrefix": "error_logs",
                        "bucketName": "s3tosf-flow-bucket"
                    },
                    "writeOperationType": "UPSERT"
                }
            }
        }
    ],
    "triggerConfig": {
        "triggerType": "OnDemand",
        "triggerProperties": {}
    },
"tasks": [
        {
            "sourceFields": [
                "RecordTypeId"
            ],
            "connectorOperator": {
                "S3": "NO_OP"
            },
            "destinationField": "Name",
            "taskType": "Map",
            "taskProperties": {
                "DESTINATION_DATA_TYPE": "Text",
                "SOURCE_DATA_TYPE": "Text"
            }
        },
        {
            "sourceFields": [
                "Account__c"
            ],
            "connectorOperator": {
                "S3": "NO_OP"
            },
            "destinationField": "Account_c__c",
            "taskType": "Map",
            "taskProperties": {
                "DESTINATION_DATA_TYPE": "Text",
                "SOURCE_DATA_TYPE": "Text"
            }
        },
{
            "sourceFields": [
                "allergies__c"
            ],
            "connectorOperator": {
                "S3": "NO_OP"
            },
            "destinationField": "allergies_c__c",
            "taskType": "Map",
            "taskProperties": {
                "DESTINATION_DATA_TYPE": "Text",
                "SOURCE_DATA_TYPE": "Text"
            }
        },
{
            "sourceFields": [
                "contact_info_address__c"
            ],
            "connectorOperator": {
                "S3": "NO_OP"
            },
            "destinationField": "contact_info_address_c__c",
            "taskType": "Map",
            "taskProperties": {
                "DESTINATION_DATA_TYPE": "Text",
                "SOURCE_DATA_TYPE": "Text"
            }
        },
{
            "sourceFields": [
                "contact_info_bestphone__c"
            ],
            "connectorOperator": {
                "S3": "NO_OP"
            },
            "taskProperties": {
                "DESTINATION_DATA_TYPE": "Text",
                "SOURCE_DATA_TYPE": "Text"
            }
        },
{
            "sourceFields": [
                "contact_info_bestphone_type__c"
            ],
            "connectorOperator": {
                "S3": "NO_OP"
            },
            "destinationField": "contact_info_bestphone_type_c__c",
            "taskType": "Map",
            "taskProperties": {
                "DESTINATION_DATA_TYPE": "Text",
                "SOURCE_DATA_TYPE": "Text"
            }
        },
{
            "sourceFields": [
                "contact_info_city__c"
            ],
            "connectorOperator": {
                "S3": "NO_OP"
            },
            "destinationField": "contact_info_city__c",
            "taskType": "Map",
            "taskProperties": {
                "DESTINATION_DATA_TYPE": "Text",
                "SOURCE_DATA_TYPE": "Text"
            }
        }
    ],
    "createdAt": "2021-11-30T04:37:36.800000+00:00",
    "lastUpdatedAt": "2021-11-30T04:37:36.800000+00:00",
    "createdBy": "arn:aws:iam::088533290808:user/cdk3",
    "lastUpdatedBy": "arn:aws:iam::088533290808:user/cdk3",
    "tags": {}
}
```

**Comment by peterwoodworth** [comment]
So it seems to be that this is an issue with the appflow console. The right people are looking at it, but I don't have an ETA for you at the moment. I'll let you know if there's any updates

**Comment by peterwoodworth** [comment]
The Appflow team should address this in the near future, thank you for your patience

**Comment by ManashJy** [comment]
@peterwoodworth Sure thing, please keep me posted about the same.

**Comment by peterwoodworth** [comment]
I don't have any updates for you in the past week. Give me a ping again if you'd like me to bump the issue internally

**Comment by ManashJy** [comment]
@peterwoodworth Yes, if possible please check with the issue internally.

**Comment by peterwoodworth** [comment]
I've reached out to the team which can fix this, I would expect this to be fixed in a month or two 🙂

**Comment by peterwoodworth** [comment]
If you're still running into this issue, can you please provide the screenshot of Appflow console page together with the Network tab, which include the response from "describe-flows"? That would be very helpful for helping service team to figure this out.

e.g.
<img width="871" alt="Screen Shot 2022-02-21 at 3 56 33 PM" src="https://user-images.githubusercontent.com/44349620/156255059-bb1ff46a-2278-41a6-8e8f-585f43e152f3.png">

**Comment by shaoyingdong** [comment]
Hi, if you can still see the issue, try adding one more task whose type is "Filter", operator is "PROJECTION", and list all source fields in the task.
Please refer to the sample code in documentation https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appflow-flow.html

**Comment by peterwoodworth** [comment]
Please ping me if anyone has more details or is still running into this issue 🙂

**Comment by lauragalera** [comment]
I am running into an issue when adding the filter task and operator PROJECTION before mapping the values. The error I am facing is 

`[Task Validation Error: The operator NO_OP is not valid for filtering tasks.  The task sourceConnectorType is FILTERING and the task operator is NO_OP]`

However, the operator is PROJECTION. Here the task:
```
    {
      "sourceFields": [
          "owner_id",
          "account_management_id",
          "num_medias_and_projects",
          "num_assignments",
          "num_eo_medias",
          "num_video_uploads",
          "num_registered_teachers",
          "num_activated_teachers",
          "num_upgraded_teachers",
          "execution_date",
          "tracking_date",
          "weekly_constant",
          "num_teachers_t1",
          "num_teachers_t2",
          "num_teachers_t3",
          "num_teachers_t6",
          "num_teachers_t9",
          "num_teachers_t12",
          "num_student_questions_answered_t1",
          "num_student_questions_answered_t3",
          "num_student_questions_answered_t6",
          "num_student_questions_answered_t9",
          "num_student_questions_answered_t12",
          "num_video_submissions_t1",
          "num_video_submissions_t3",
          "num_video_submissions_t6",
          "num_video_submissions_t9",
          "num_video_submissions_t12",
          "students_time_spent_watching_videos_t1",
          "students_time_spent_watching_videos_t3",
          "students_time_spent_watching_videos_t9",
          "students_time_spent_watching_videos_t12",
          "num_screen_recordings_attempts",
          "num_verified_teachers",
          "students_time_spent_watching_videos_t6"
      ],
      "connectorOperator": {
          "S3": "PROJECTION"
      },
      "taskType": "Filter",
      "taskProperties": []
  }
```

but after running `cdk synth`, it is not added:

```
Tasks:
        - ConnectorOperator: {}
          SourceFields:
            - owner_id
            - account_management_id
            - num_medias_and_projects
            - num_assignments
            - num_eo_medias
            - num_video_uploads
            - num_registered_teachers
            - num_activated_teachers
            - num_upgraded_teachers
            - execution_date
            - tracking_date
            - weekly_constant
            - num_teachers_t1
            - num_teachers_t2
            - num_teachers_t3
            - num_teachers_t6
            - num_teachers_t9
            - num_teachers_t12
            - num_student_questions_answered_t1
            - num_student_questions_answered_t3
            - num_student_questions_answered_t6
            - num_student_questions_answered_t9
            - num_student_questions_answered_t12
            - num_video_submissions_t1
            - num_video_submissions_t3
            - num_video_submissions_t6
            - num_video_submissions_t9
            - num_video_submissions_t12
            - students_time_spent_watching_videos_t1
            - students_time_spent_watching_videos_t3
            - students_time_spent_watching_videos_t9
            - students_time_spent_watching_videos_t12
            - num_screen_recordings_attempts
            - num_verified_teachers
            - students_time_spent_watching_videos_t6
          TaskProperties: []
          TaskType: Filter```
