### ISSUE TITLE
(ecs): AwsLogDriver ignores log group's region

### ISSUE THREAD

**Issue by gshpychka** [aws/aws-cdk#17747]
### What is the problem?

ECS supports cross-region logging with awslogs with the `awslogs-region` option.
When I pass a cross-region `LogGroup` (constructed from an arn), the `awslogs-region` option in the resulting template is always the current region, ignoring the log group's region.

### Reproduction Steps

Create a cross-region log group and pass it to `ecs.AwsLogDriver`:

```python
log_group = logs.LogGroup.from_log_group_arn(f"arn:aws:logs:eu-west-2:{self.account}:log-group:my_log_group")

container = ecs.ContainerDefinition(self, "container", 
    ...
    logging=ecs.AwsLogDriver(stream_prefix="my_prefix", log_group=log_group)
)
```

### What did you expect to happen?

The logs are written to the specified log group.

### What actually happened?

The task execution role is given the correct permissions for the log group (including the correct region).

But the `awslogs-region` option in the container definition is always the same as the container's region.

Task fails to start.

### CDK CLI Version

1.134

### Node.js Version

17.1.0

### OS

Linux

### Language

Typescript, Python, .NET, Java, Go

### Other information

I'm resorting to escape hatches to override `Properties.ContainerDefinitions.0.LogConfiguration.Options.awslogs-region` on the task definition, but this doesn't work if there are multiple containers.

**Comment by gshpychka** [comment]
This is the line that causes the bug: https://github.com/aws/aws-cdk/blob/171cbc14166b360b0c2739de44f1b1ef220d55f9/packages/%40aws-cdk/aws-ecs/lib/log-drivers/aws-log-driver.ts#L130

**Comment by gshpychka** [comment]
@ryparker do you need any more info? I'd gladly help here, the needed fix seems trivial, but I have never written any TS code. What do you think the proper way would be here - we could parse the log group's ARN and get the region from there.

**Comment by kornicameister** [comment]
I am playing around with this issue. If I managed to find something out, I will let you know.

**Comment by kornicameister** [comment]
@gshpychka @ryparker `region` can be obtained via `logGroup.env.region` but that does not resolve to correct region when running the code. Wonder if there's any way to force resolution of stack.

**Comment by gshpychka** [comment]
@kornicameister woud parsing the log group ARN be too hacky?

**Comment by kornicameister** [comment]
Best to my knowledge I would say that it is not needed. Documentation says that `region` set on `ResourceEnvironment` is enough because it points to region from which resource was imported from. That being said either I am setting the test in incorrect way or something else happens.

**Comment by gshpychka** [comment]
If `LogGroup.env.region` resolves to an incorrect region, that's probably a bug and worth opening an issue for.

**Comment by skinny85** [comment]
It's a bug in the `LogGroup.fromLogGroupArn()` method - you can see [here](https://github.com/aws/aws-cdk/blob/0fd80e13846442aa982fd1d9335cfdd813b548c5/packages/%40aws-cdk/aws-logs/lib/log-group.ts#L358-L358) that the region is not passed from the ARN to the returned Resource, like it should be ([here's](https://github.com/aws/aws-cdk/blob/0fd80e13846442aa982fd1d9335cfdd813b548c5/packages/%40aws-cdk/aws-servicecatalog/lib/portfolio.ts#L313-L315) a working example).

**Comment by kornicameister** [comment]
Alright @skinny85 , I will submit my PR in such case and will submit/search for the issue regarding region for log group.

**Comment by kornicameister** [comment]
I have submitted my fix for log group's region: https://github.com/aws/aws-cdk/pull/18215
