### ISSUE TITLE
(package/tools): Cannot cause deprecations to be errors

### ISSUE THREAD

**Issue by SamStephens** [aws/aws-cdk#17742]
### What is the problem?

I am having trouble tracking down usage of some deprecated features in a CDK stack. I want to be able to run with deprecations throwing errors rather than causing warnings, so I can see where the deprecated features are being used (from the stack trace).

https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.core/Annotations.html talks about setting the CDK_BLOCK_DEPRECATIONS environment variable to cause deprecations to be errors, and then it talks about passing in the --strict flag to cause warnings to be errors. I've tried passing both things to `cdk diff`, and I don't see a failure.

### Reproduction Steps

Set up a simple stack that uses something deprecated, such as putting the period on the alarm, rather than the metric being alarmed on.

```python
from aws_cdk import core as cdk, aws_cloudwatch

class TestStack(cdk.Stack):
    def __init__(self, scope: cdk.Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        aws_cloudwatch.Metric(
            scope=self,
            id="Metric",
            metric_name="Test",
            namespace="Test",
        ).create_alarm(
            scope=self,
            id="Alarm",
            evaluation_periods=1,
            period=cdk.Duration.minutes(1),
            threshold=0,
        )
```

Run

```sh
CDK_BLOCK_DEPRECATIONS=error cdk diff --profile ecor1-dev-admin --require-approval never --strict
```

### What did you expect to happen?

I'd expect synthesis to fail, with the exception thrown where the deprecated feature is used.

### What actually happened?

Synthesis succeeds with warning messages as per usual.

### CDK CLI Version

1.134.0

### Node.js Version

14.17.0

### OS

Windows 10 Professional: 10.0.19043 Build 19043

### Language

Python

### Language Version

3.9.7

### Other information

It'd be great if this was better documented; it's not clear to me whether this is a bug in the CDK, or whether I've not understood how to cause deprecations to fail.

**Comment by rix0rrr** [comment]
I think it's

```
env JSII_DEPRECATED=fail  cdk diff --profile ecor1-dev-admin --require-approval never --strict
```

**Comment by rix0rrr** [comment]
Ah there are 2 different kinds of deprecations. That's confusing.

**Comment by TheRealAmazonKendra** [comment]
Per the linked issue, it looks like this has been resolved. I'm going to go ahead and close this issue. If you are still believe this was closed in error, please feel free to open a new issue.
