### ISSUE TITLE
(stepfunctions): Can't create two Step Functions with steps with the same name

### ISSUE THREAD

**Issue by m-radzikowski** [aws/aws-cdk#17750]
### What is the problem?

You can't create two Step Functions in the same stack with steps with the same names.

### Reproduction Steps

```ts
class MyStack extends Stack {
    constructor(app: App, id: string) {
        super(app, id);

        new StateMachine(this, 'FirstSF', {
            stateMachineName: 'first',
            definition: new Pass(stack, 'My Step'),
        });

        new StateMachine(this, 'SecondSF', {
            stateMachineName: 'second',
            definition: new Pass(stack, 'My Step'),
        });
    }
}
```

### What did you expect to happen?

Two Step Functions should be created with steps with the same names.

### What actually happened?

```
Error: There is already a Construct with name 'My Step' in MyStack
```

This is because the Construct ID must be unique in the stack, and at the same time Step Construct ID is used as a step name.

### CDK CLI Version

1.134.0 (build dd5e12d)

### Framework Version

1.134.0

### Node.js Version

14.18.1

### OS

macOS 12.0.1

### Language

Typescript

### Language Version

TypeScript (4.4.4)

### Other information

Making an exception for the Steps Constructs so the ID does not have to be unique may be hard. Easier solution would be to add "name" parameter to Step, so you can override the step name:

```ts
new Pass(stack, 'SF2 My Step', {name: "My Step"})
```

**Comment by kaizen3031593** [comment]
@m-radzikowski This seems normal to me. A `Pass` extends `Construct` and all constructs must have unique IDs. This is not something we can change. The ID is a requirement of the CDK and not of stepfunctions, unfortunately.

**Comment by m-radzikowski** [comment]
@kaizen3031593 yes, I understand this. But the ID is used as a Step name and cannot be overridden. As a result, you can't have two Step Functions with steps with the same names, which is something that happens only with CDK. Apart from CDK, the only restriction is the steps must be unique in the scope of a single SF.
