### ISSUE TITLE
Add defaultCacheBehavior CloudFrontWebDistribution props 

### ISSUE THREAD

**Issue by emmapatterson** [aws/aws-cdk#17755]
### Description

Add `defaultCacheBehavior` with `responseHeadersPolicyId` prop to CloudFrontWebDistribution to allow setting response headers directly in the CloudFrontWebDistribution.

### Use Case

To easily set up http response headers in the cloud front distribution

### Proposed Solution

```
private cloudFrontWebDistribution = new CloudFrontWebDistribution(this, "CloudfrontDistribution", {
    defaultCacheBehavior:  {responseHeadersPolicyId: "responseHeadersPolicyId", ...}
    ...
})
```

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by robertd** [comment]
@emmapatterson Howdy. Response Header Policy feature (https://github.com/aws/aws-cdk/pull/17359) landed in the new `Distribution` construct and should be released in `1.135.0`. Have you considered moving away from the old `CloudFrontWebDistribution` construct to the new `Distribution` construct?

**Comment by emmapatterson** [comment]
Ahh great! Thanks! Will take a look!
What’s the benefit to move to Distribution over CloudFrontWebDistribution? 
Or will CloudFrontWebDistribution eventually be deprecated?

**Comment by robertd** [comment]
`Distribution` was a complete rewrite done by @njlynch. My guess is that `CloudFrontWebDistribution` will be deprecated at some point (maybe v2) as `Distribution` is getting more and more features which are not being back-ported to `CloudFrontWebDistribution`. `Distribution` has a better separation/logic behind origins (ELB vs s3) and is a second take on `CloudFrontWebDistribution` construct... done right :).

**Comment by emmapatterson** [comment]
Sounds great! Will have a look at switching it out then! Thanks for your help!
