### ISSUE TITLE
(servicecatalog): TagOptions cannot be shared among portfolios in the same account

### ISSUE THREAD

**Issue by avanderm** [aws/aws-cdk#17753]
### What is the problem?

Specifying TagOptions and sharing them with two separate ServiceCatalog portfolios in different stacks in the same AWS account will fail because it leads to a duplicate creation of TagOption resources (they are created alongside the TagOptionAssocation).

### Reproduction Steps

```ts
export class TagOptionsStack extends cdk.Stack {
  public readonly tagOptions: TagOptions;

  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    this.tagOptions = new TagOptions({
      'testtag': ['test'],
    });
  }
}

interface PortfolioOneStackProps extends cdk.StackProps {
  tagOptions: TagOptions;
}

export class PortfolioStackOne extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props: PortfolioOneStackProps) {
    super(scope, id, props);

    new Portfolio(this, 'PortfolioOne', {
      displayName: 'Portfolio 1',
      providerName: 'provider',
      tagOptions: props.tagOptions,
    });
  }
}

interface PortfolioTwoStackProps extends cdk.StackProps {
  tagOptions: TagOptions;
}

export class PortfolioStackTwo extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props: PortfolioTwoStackProps) {
    super(scope, id, props);

    new Portfolio(this, 'PortfolioTwo', {
      displayName: 'Portfolio 2',
      providerName: 'provider',
      tagOptions: props.tagOptions,
    });
  }
}
```

### What did you expect to happen?

I expected the TagOptions class to implement the Construct interface so that TagOptions would be created and that passing the TagOptions class to a portfolio would only create the assocations. For my use case I'll simple add the portfolios in one stack. However I can imagine in other teams, where portfolios are created by different teams, this would not be possible. Or we'd need to resort to the L1 classes.

### What actually happened?

The code will synthesize, but the deployment will fail when the second portfolio is being deployed, because the TagOption already exists in the first Portfolio stack. The TagOptions in the TagOptionsStack will not create TagOption in that stack, since the TagOptions class is not a construct.

### CDK CLI Version

1.122.0 (build ae09c16)

### Node.js Version

v16.13.0

### OS

Fedora

### Language

Typescript

### Language Version

TypeScript (3.9.7)

**Comment by arcrank** [comment]
Thanks for detailed issue.  You're correct that currently we don't surface `TagOptions` directly as a cdk construct, they are just an interface and when added to a resource it will create the underlying L1.  It's interesting use case though having tag options specifically in their own stack.  Will provide an update shortly.

**Comment by dponzo** [comment]
We will be implementing `TagOptions` as their own L2 Constructs shortly. Will update with the PR when its up.
