### ISSUE TITLE
(aws-lambda-nodejs): support additional esbuild configurations(main-fields)

### ISSUE THREAD

**Issue by AllanZhengYP** [aws/aws-cdk#17768]
### Description

Currently only a subset of esbuild configs are exposed to users via BundlerOptions:https://github.com/aws/aws-cdk/blob/29039e8bd13a4fdb7f84254038b3331c179273fd/packages/%40aws-cdk/aws-lambda-nodejs/lib/types.ts#L6

However there are much more configs supported by esbuild: https://esbuild.github.io/api/

A good example is [`main-fields`](https://esbuild.github.io/api/#main-fields): by default esbuild will prefer `main` entry of package.json for Node.js app. However, this is usually the entry point for CommonJS module, thus, esbuild cannot treeshake it well. If we specify the esbuild to prefer the module entry point, the function bundle can be reduced more with tree shaking.

### Use Case

If `main-fields` is specified for AWS SDK v3, the SDK size can be further reduced by more than 50% with tree shake enabled. 

### Proposed Solution

Even though this request is asking `main-fields` config explicitly, CDK can also expose interface for arbitrary esbuild config. Just like `buildArgs` for the image building step: https://github.com/aws/aws-cdk/blob/29039e8bd13a4fdb7f84254038b3331c179273fd/packages/%40aws-cdk/aws-lambda-nodejs/lib/types.ts#L210

There are 2 alternatives for it:
1. Expose additional options in `BundlingOptions` like `{ esbuildConfigs: { [key: string]: string } }`. This alternative may requires validating the duplicated options with other existing esbuild configs.
2. Expose a path option for users to provide custom `esbuild.js` file, which calls the esbuild JS API. This will ignore all other esbuild configs. The advantage is that it supports all the future esbuild configs.

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by alexbaileyuk** [comment]
@AllanZhengYP this looks really useful for our needs. Do you have any idea on how we can get a second approval so this can move forward.

@jogold I see you had a comment on the PR but it looks like it's been resolved. Any chance you can pick it back up?

The use case for this is that we want to use the SDK V3 in our functions. Without tree shaking it adds several MB and with tree shaking it's <500kb. Also, by specifying our own SDK version, we can be sure that the version running in production is the same one we tested against. With no word fro AWS regarding a Node 16 runtime or what SDK will be bundled, I think it would be great to get some movement on this issue (especially when the issue seems to have a working PR).

**Comment by jogold** [comment]
> @jogold I see you had a comment on the PR but it looks like it's been resolved. Any chance you can pick it back up?

It looks good but I had the following comment https://github.com/aws/aws-cdk/pull/17788#discussion_r760895291

**Comment by alexbaileyuk** [comment]
I see the comment now. Would it be wrong to just suggest users enter an empty string for flags without arguments?

**Comment by alexbaileyuk** [comment]
> > @jogold I see you had a comment on the PR but it looks like it's been resolved. Any chance you can pick it back up?
> 
> It looks good but I had the following comment [#17788 (comment)](https://github.com/aws/aws-cdk/pull/17788#discussion_r760895291)

I see the comment now. Would it be wrong to just suggest users enter an empty string for flags without arguments?

**Comment by jogold** [comment]
> I see the comment now. Would it be wrong to just suggest users enter an empty string for flags without arguments?

With the current implementation it would lead to `--my-option=` which will make esbuild throw an error because of the trailing `=`.

**Comment by alexbaileyuk** [comment]
> > I see the comment now. Would it be wrong to just suggest users enter an empty string for flags without arguments?
> 
> With the current implementation it would lead to `--my-option=` which will make esbuild throw an error because of the trailing `=`.

Ah you are correct. I didn't think about that. @ryparker are you able to take a look at that? If not are you happy for me to take a look at it?

**Comment by ryparker** [comment]
Thanks for the ping. I'll give this a look.

**Comment by ryparker** [comment]
Updated the PR and left my thoughts on the [comment in question](https://github.com/aws/aws-cdk/pull/17788#discussion_r823120888).

**Comment by alexbaileyuk** [comment]
> Updated the PR and [left my thoughts on the comment in question](https://github.com/aws/aws-cdk/pull/17788#discussion_r823120888).

Fantastic. I see it has been merged as well which is great. Thanks for the quick turn around!
