### ISSUE TITLE
(module name): cdk.CfnOutput doesn't output URL with correct AWS hostname for AWS China

### ISSUE THREAD

**Issue by kunalshah** [aws/aws-cdk#17769]
### What is the problem?

cdk.CfnOutput doesn't print the right URL for AWS China.

The hostname of the URL output by cdk.CfnOutput is "console.aws.amazon.com".  In AWS China, hostname should be "console.amazonaws.cn"

Current output:
https://console.aws.amazon.com/cloudwatch/home?region=cn-northwest-1#dashboards:name=myDashboardWatchful

Expected output: 
https://console.aws.amazon.com/cloudwatch/home?region=cn-northwest-1#dashboards:name=myDashboardWatchful

### Reproduction Steps

    // Get Elastic IP 
    vpc.publicSubnets.forEach((subnet, index) => {
      // Find the Elastic IP
      const EIP = subnet.node.tryFindChild('EIP') as ec2.CfnEIP
      new cdk.CfnOutput(this, `output-eip-${index}`, { value: EIP.ref });
    })

### What did you expect to happen?

print correct hostname (console.amazonaws.cn) for AWS China

### What actually happened?

printed wrong hostname (console.aws.amazon.com) of AWS Global

### CDK CLI Version

1.134.0 (build dd5e12d)

### Node.js Version

v17.0.1

### OS

MacOS Catalina

### Language

Typescript

### Language Version

4.5.2

**Comment by njlynch** [comment]
What service/module/resource are you referencing that is outputting the console URL? The reproduction steps mention `EIP.ref`. According to the documentation, the EIP reference [returns](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-eip.html#aws-properties-ec2-eip-return-values) the elastic IP address, not any URL.

**Comment by kunalshah** [comment]
I misunderstood this issue. It is the cdk-watchful module printing incorrect hostname in the URL and not aws-cdk itself.
I'll close this issue now. 
Apologies for the inconvenience.
