### ISSUE TITLE
(aws-cdk/aws-appsync): Union type definition fields suffixed with "id"

### ISSUE THREAD

**Issue by fab-mindflow** [aws/aws-cdk#17771]
### What is the problem?

Union type definition is generated with a weird "id" suffix. Maybe there is a reason?

https://github.com/aws/aws-cdk/blob/283ed02c64f827161edba3e11c3cead3b54b7ee9/packages/%40aws-cdk/aws-appsync/lib/schema-intermediate.ts#L384

Consequently, some of our union type are generated in GraphQL (as we have an advanced code first pre-processing using CDK AppSync) like this:

```ts
input UpdatePayloadInput {
  Type1id: Type1Input
  Type2id: Type2Input
}
```

### Reproduction Steps

Build a Union type:

```ts
    const TypeUnion = new appsync.UnionType("TypeUnion", {
      definition: [
        Type1,
        Type2,
      ],
    })


   console.log(TypeUnion.definition)
```

This gives out:
```ts
{
  Type1id: GraphqlType {
    type: 'INTERMEDIATE',
    // ...
    }
  },
  Type2id: GraphqlType {
    type: 'INTERMEDIATE',
    // ...
    }
  }
}
```

### What did you expect to happen?

Definition does not contain the "id" suffix.

### What actually happened?

"id" is appended to the union type definition.

### CDK CLI Version

1.134.0

### Node.js Version

16.13.0

### OS

macOS 12.0.1 (Monterey)

### Language

Typescript

### Language Version

4.4.3

**Comment by otaviomacedo** [comment]
@BryanPan342 do you remember what was the reason for this suffix?

**Comment by BryanPan342** [comment]
Hm quite frankly i can't remember why i added the 'id' suffix. I think it might have tried to serve as a catchall if the field didnt exists.. but that doesnt make sense because i made a check beforehand. I dont see any problem changing it to remove the suffix. 

Also i didnt really think about people using the definition function so this is actuall pretty interesting.

**Comment by fab-mindflow** [comment]
> Also i didnt really think about people using the definition function so this is actuall pretty interesting.

To be honest, that's because we are doing uncommon usage of this module by generating a lot of GraphQL stuff (applying Relay best pratiques to the generated GraphQL such as input types, payload types, pagination, etc... For now we have just filtered the output from definition.

Hope the module to go out from experimental soon (it works pretty well for our code first usage btw).
