### ISSUE TITLE
(cli): I think `cdk watch` should deploy first

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#17776]
### Description

`cdk watch` should start with a `cdk deploy` to make sure my account and my source code are in sync before watching for changes.

### Use Case

The point of `cdk watch` is to keep a developer account in sync with your source code as you develop. To that end, I expected that the CLI will first deploy the current version to my account before beginning to monitor files.

This surprising behavior is emphasized when running `cdk deploy --watch` (which even sends a stronger semantic signal that I want to deploy).

### Proposed Solution

Just kick off a `cdk deploy` before watching.

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by skinny85** [comment]
I thought of this too. The counter-argument I've had is that it's very easy to trigger a deploy with `watch` without any big change (for example, just add an empty line, or a comment), so it's not a huge deal that it doesn't start with a deployment.

Thoughts on this?
