### ISSUE TITLE
(cli): `cdk watch` triggers twice on a single change

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#17777]
### What is the problem?

`cdk watch` is trigger happy.

### Reproduction Steps

I am making a single save to `src/foo.lambda.ts` but it seems like `cdk watch` thinks there were two changes. This results in an unwanted additional deployment.

```
Detected change to 'src/foo.lambda.ts' (type: change). Triggering 'cdk deploy'
Detected change to 'src/foo.lambda.ts' (type: change) while 'cdk deploy' is still running. Will queue for another deployment after this one finishes
```

### What did you expect to happen?

I expected a single file write to result in a single deployment.

### What actually happened?

There were two deployments.

### CDK CLI Version

1.134.0 (build dd5e12d)

### Framework Version

1.134.0 (build dd5e12d)

### Node.js Version

17.0

### OS

Mac

### Language

Typescript

### Language Version

4.5.2

**Comment by skinny85** [comment]
@eladb can you provide some reproduction steps? Maybe a quick video, or GIF? 🙂 I wasn't able to reproduce this.

**Comment by skinny85** [comment]
@eladb ping 🙂

**Comment by eladb** [comment]
Here's a screen recording of the issue.


https://user-images.githubusercontent.com/598796/145983196-73aa2de1-9685-486c-8a26-d349f7f21cd8.mov


Basically, it looks related to how VSCode handles CTRL+S, which is anecdotal. But:

1. Many of our users are using VSCode
2. It should be possible to implement logic that will handle these cases quite nicely

Basically, we can just stop watching for 1sec before we handle it.

Here's a simple implementation which basically pauses the listener for 1s before listening again.

```js
const fs = require('fs')

const watch = fs.watch('dir');

function listener(event, filename) {
  console.log({ event, filename });

  // pause watch
  watch.removeListener('change', listener);
  setTimeout(() => {
    // REDEPLOY HERE

    // resume watch
    watch.addListener('change', listener);
  }, 1000);
};

watch.addListener('change', listener);
```

**Comment by skinny85** [comment]
Thanks for the video @eladb!

**Comment by eladb** [comment]
This is not reproducing in AWS CDK CLI v2.2.0, so I am closing for now.
