### ISSUE TITLE
@aws-cdk: Copy/Clone cdk Project

### ISSUE THREAD

**Issue by rpattcorner** [aws/aws-cdk#17781]
### Description

After conversation with AWS CDK support, it appears that cdk currently does not have the capability to copy an existing deployed cdk application to a new directory on the deploying machine, then modify the copy and redeploy without affecting the original.

Instead the copied application retains its connection to the CFN stack deployed by the original application, and will affect it if changed and redeployed.

I know.  It sounds hard to believe.  But support confirms it.

### Use Case

One often preferred style of development involves incrementally modifying an application until it reaches a desired state.

Sometimes, fairly often, the old and new apps need to diverge to create a different application

However the apparently invisible tight binding between the cdk code and its corresponding CFN stack and deployed artifacts is currently unbreakable according to AWS support.

### Proposed Solution

One ideal solution would be a `cdk clone` or `cdk copy` command.

This command would have knowledge of the linkages between the initial undeployed CDK code and the eventually deployed CFN and AWS artifacts, and be able to break the linkages and produce a new CDK application in a new directory without deployment links.

Another solution would be to clearly identify a process that could be applied to a directory-copy of a deployed application that would return it to a predeployment state, so that when deployed it would be a clean slate.

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by peterwoodworth** [comment]
I don't think I fully understand what's happening - you are copying your CDK application files so that you are essentially creating two different workspaces, correct? At this point these two different workspaces are completely independent from one another.

If you make modifications to one of these applications and deploy it to the same environment without renaming the stacks, then that would cause you to modify your existing stacks rather than creating new ones, but that is expected.

Could you elaborate on what you mean exactly by modifying the original with the copied project?

**Comment by peterwoodworth** [comment]
CDK is powerful enough to support b/g deployments however the user wants to implement them all in the same app. See [this repo](https://github.com/aws-samples/aws-cdk-spa-bg-deployment) for an example of a CDK app which uses b/g deployment

> Indeed it is expected, and in some situations desirable, but not in the use case I'm outlining

There's no working around deploying the same named stack to the same environment. That's just how cloudformation works. 
You could instead rename the stack to create an entirely separate stack. You could utilize parameters here as well
