### ISSUE TITLE
(aws-cdk-lib): `aws-cdk-lib` should export `construct`

### ISSUE THREAD

**Issue by ghost** [aws/aws-cdk#17783]
### Description

Although the `construct` type is now defined in a separate module from the CDK proper, `aws-cdk-lib` consumes it and unless I have all my TypeScript wires completely crossed, `aws-cdk-lib` could easily export it. This would mean one less change for customers migrating to v2.

(Can you tell I have spent the last few days adding `import { Construct } from 'constructs'` to a lot of code snippets?)

### Use Case

Simplify documentation and migration.

### Proposed Solution

Export `construct` from `aws-cdk-lib`.

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by ChristopheBougere** [comment]
I've just started migrating to v2 and I had the exact same thought.
Having `construct` in a separated package doesn't prevent it, AFAIK, to expose it in `aws-cdk-lib` for simplicity purpose :)

**Comment by eladb** [comment]
There are currently limitations in JSII that prevent us from doing that. @RomainMuller can chime in.

**Comment by Jerry-AWS** [comment]
Yeah, I can see how having to translate it into a bunch of other languages might complicate things.
