### ISSUE TITLE
(aws-ecs-patterns): MultipleTargetGroupsFargateService - Unable to define configurations (e.g. protocol) for listeners and target groups

### ISSUE THREAD

**Issue by Nico-DB** [aws/aws-cdk#17798]
### Description

I am trying to set up an NetworkMultipleTargetGroupsFargateService for my application. The application is exposing two ports (25 for smtp, 80 for http).

When setting up the loadbalancers I am only able to define the name and the port. The same goes for the targetGroups.
I need define more then this. For example one of the listeners should listen on tcp / 25. The other need to listen on TLS / 443.

For the target groups I need to define health check configuration and so on.

Even on the load balancer I need to define more. E.g. stickiness or access logs.

### Use Case

When setting up fargate services I still need the possibllity to define all configurations a networkloadblancer including listener and target group offers.

This is true for every construct within the aws-ecs-patterns

### Proposed Solution

Please extend NetworkLoadBalancerProps, NetworkLoadBalancerProps and NetworkLoadBalancerProps so I can define every configuration which a Loadbalancer, Listener and Target Group offers.

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by indrora** [comment]
This appears to have already been covered: https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ecs_patterns.NetworkMultipleTargetGroupsFargateService.html#targetgroups-1

**Comment by khushail** [comment]
@Nico-DB , looks like the FR has been implemented in this construct -https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ecs_patterns.NetworkMultipleTargetGroupsFargateService.html#targetgroups-1

 Please verify and let us know if this does not fulfill your ask. Would re-open the request.
