### ISSUE TITLE
PythonLayerVersion does not update 3rd party dependency to the LATEST 

### ISSUE THREAD

**Issue by tomeszmh** [aws/aws-cdk#17799]
### What is the problem?

We have a requirements.txt file with a 3rd party package in it managed by our team. We created a PythonLayerVersion instance attached to the lambdas to be able to create a common layer package. Everything is working well except when we are updating the 3rd party lib. If there is a newer version available from that package, our layer ignores to update it from the requirements file and cdk deploy has no effect on the resources.  I tried to adjust requirements.txt to force an upgrade but the layer doesn't seem to be updated.  As we noticed if we change something in requirements.txt the layer is updating... 

### Reproduction Steps

Have a requirements.txt with a 3rd party in it, with a simple PythonLayerVersion instance. 
for example: 

requirements.txt:

```txt
requests
--install-option "--upgrade"
```

Layer:

```python
class CommonLayer(PythonLayerVersion):

    def __init__(self, scope):
        dirname = os.path.dirname(__file__)
        path = os.path.join(dirname, 'requirements')

        super().__init__(
            scope,
            id="common-layer",
            entry=path,
            compatible_runtimes=[lambda_.Runtime.PYTHON_3_8],
            description="Common python packages",
        )
```

### What did you expect to happen?

Layer checks for 3rd party updates, then has affect on AWS Resources.

### What actually happened?

cdk deploy has no affect on the layer. 

### CDK CLI Version

1.134.0

### Node.js Version

8.1.4

### OS

Mac OS 11.6

### Language

Python

### Language Version

Python 3.7.3

**Comment by joel-aws** [comment]
Ran into the same issue today and temporarily cleared it by going into CDK's toolkit bucket and deleting the non-updating asset.

For a more lasting fix, we're using [`Code.from_asset`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-lambda.Code.html#static-fromwbrassetpath-options) and setting the [AssetHashType](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.AssetHashType.html) to OUTPUT (the default is SOURCE and likely the same in the PythonLayerVersion).
