### ISSUE TITLE
(aws-elasticache): `CfnUserGroup` couldn't infer implicit dependency on `CfnUser`

### ISSUE THREAD

**Issue by khangly** [aws/aws-cdk#17804]
### What is the problem?

When I tried to create a `CfnUser` and a `CfnUserGroup` that has that user, I got an error because the group can't infer dependency on user.

### Reproduction Steps

```typescript

const secret = new Secret(this, "user-secret", {
  generateSecretString: {
    secretStringTemplate: JSON.stringify({ username: "default" }),
    generateStringKey: "password",
  },
});

const rbacUser = new elasticache.CfnUser(this, "rbac-user", {
  engine: "redis",
  userName: "default",
  accessString: "on ~* +@all",
  userId: "user",
  passwords: [
    secret.secretValueFromJson("password").toString(),
  ],
});

const rbacGroup = new elasticache.CfnUserGroup(this, "rbac-group", {
  engine: "redis",
  userGroupId: "admin",
  userIds: [rbacUser.userId],
});
# Explicit dependency to fix: rbacGroup.addDependsOn(rbacUser);
```

### What did you expect to happen?

`CfnUser` and `CfnUserGroup` are created successfully.

### What actually happened?

```
Resource handler returned message: "User user not found. (Service: ElastiCache, Status Code: 404, Request ID: 46a58ddb-76d2-47da-9aaf-6b06978ce5f3, Extended Request ID
: null)" (RequestToken: 168d44ee-a06a-7443-4214-a8cf6468b25c, HandlerErrorCode: GeneralServiceException)
```

### CDK CLI Version

1.130.0 (build 9c094ae)

### Node.js Version

12.22.7

### OS

Amazon Linux 2

### Language

Typescript

### Language Version

TypeScript (3.8.0)

### Other information

Adding explicit dependency fixes it.

**Comment by otaviomacedo** [comment]
Hi, @khangly.

In the CDK, all constructs starting with `Cfn` are what we call "level 1 constructs" (L1s, for short). L1s expose the same interface that CloudFormation does, only in an imperative language, but without any additional logic. They are automatically generated from the CloudFormation specification.

Things like automatic dependencies between constructs are achieved by level 2 constructs, which are manually written. Unfortunately, there are no L2 constructs for elasticache. So defining the dependency explicitly is the way to go, for now.

Of course, if you are interested, we welcome community contributions. Check our [contributing guide](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) on how to submit code to the CDK.
