### ISSUE TITLE
(aws-stepfunctions-tasks): can typing be improved for CallAwsServiceProps.parameters?

### ISSUE THREAD

**Issue by rogerchi** [aws/aws-cdk#17801]
### Description

Currently, CallAwsServiceProps.parameters is typed as { [key: string]: any }.  We ran into an issue where we were passing in a bucket class object instead of bucket.bucketName as a value for one of the parameters, and the synth blew up with an ambiguous error message about JavaScript heap out of memory with no pointers to where the error was originating from.  The linting didn't catch this error due to the any type for the parameter values.

### Use Case

Improve the typing so that errors like this can be caught in the static analysis.

### Proposed Solution

Maybe use this as the type instead of any:
```
type JSONValue =
    | string
    | number
    | boolean
    | { [x: string]: JSONValue }
    | Array<JSONValue>;
```

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by kaizen3031593** [comment]
I'm not convinced that this is something we need. I see the `parameters` property as use-at-your-own-risk and we want to literally support "any" kind of parameter there is. 

I see your point about it needing to be a "JSONValue", but we model all our JSON values as `{ [key: string]: any }`, not just in `CallAwsService`. Moreover, this would be a breaking change to a stable module so we wouldn't want that.
