### ISSUE TITLE
(code_pipeline_actions): Access to variables in CodeStarConnectionsSourceAction

### ISSUE THREAD

**Issue by kornicameister** [aws/aws-cdk#17807]
### Description

Ability to use `variables` similarly to what is now available in [GithubSourceAction](cpa.CodeStarConnectionsSourceAction).

### Use Case

Using bitbucket and recommended CodeStarConnectionsSourceAction I'd like access commit id of the particular source and use it to tag AMI build further down in the pipeline.

### Proposed Solution

?

### Other information

cdk-version: 1.134.0

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by kornicameister** [comment]
It works using syntax from documentation, but would certainly be nicer to have common interface.

**Comment by skinny85** [comment]
Yep, agreed @kornicameister, thanks for opening the issue!

Would you consider contributing this as a PR? It should be relatively straightforward I think if you look how the existing source Actions implement variables (for example, [here's the code for the `GitHubSourceAction`](https://github.com/aws/aws-cdk/blob/b60dc63f99ede0cfaa859cdef33a6f4ddd2d1d25/packages/%40aws-cdk/aws-codepipeline-actions/lib/github/source-action.ts#L116-L127)).

Our contributing guide: https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md

Thanks,
Adam

**Comment by kornicameister** [comment]
I will certainly try but I cannot give any ETA on this so if anyone can jump in, all the better.

**Comment by kewur** [comment]
Is there a workaround to get the commitId from CodeStarConnectionsAction in the meantime?

**Comment by skinny85** [comment]
> Is there a workaround to get the commitId from CodeStarConnectionsAction in the meantime?

Yep. Just pass the `variableNamespace` property when creating the `CodeStarConnectionsAction`, and then use the syntax `"#{MyVariableNamespace}.CommitID"` in another Action's definition (like CodeBuild Action's environment variable).

**Comment by kornicameister** [comment]
That's exactly the workaround I've used.

**Comment by kornicameister** [comment]
@skinny85 I already have part of the code, one little test is not passing but I should be able to submit the PR by the end of the week.

**Comment by skinny85** [comment]
Awesome @kornicameister, thanks for working on this!

**Comment by kornicameister** [comment]
Alright @skinny85 , change submitted. Hope I followed guidelines correctly.
