### ISSUE TITLE
(ElastiCache): Unable to  create secondary cluster to a GlobalReplicationGroup using CDK

### ISSUE THREAD

**Issue by pwangdue** [aws/aws-cdk#17808]
### link to reference doc page

https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-elasticache.CfnGlobalReplicationGroup.html

### Describe your issue?

Not able create to create a secondary cluster to a GlobalReplicationGroup using CDK.

Tried different ways to have the Secondary cluster set up using CDK - All failed
1. Tried adding the globalReplicationGroupId parameter on creating Secondary cluster - Did not work
2. Tried adding the secondary cluster in the GlobalReplicationGroup members - Did not work
3. Tried with having the another stack for us-west-2 and followed the above strategy - Did not work

Document wasn't so clear on CDK part. Please let me know if this is possible in CDK or not I have tried many ways and reached out to AWS support but still couldn't get useful document or guide to achieve this.

**Comment by otaviomacedo** [comment]
Hi, @pwangdue. 

Have you tried setting the `globalReplicationGroupIdSuffix` property?

**Comment by pwangdue** [comment]
Hi @otaviomacedo I could create the secondary cluster using this property but not using the members property in the GlobalReplicationGroup

**Comment by otaviomacedo** [comment]
But does it solve your problem? I see how the documentation is not clear, but these are L1 constructs. The documentation is generated automatically from the CloudFormation specification.

**Comment by pwangdue** [comment]
yes it solved the problem. But I think documentation can be updated
