### ISSUE TITLE
(@aws-cdk/events): Lambda Scheduled events cannot be run in fractions of a minute

### ISSUE THREAD

**Issue by mwithington** [aws/aws-cdk#17814]
### link to reference doc page

https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-events.Rule.html#schedule

### Describe your issue?

The CDK documentation states that when creating a new instance of the [Rule class](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-events/lib/rule.ts) and utilizing the [Schedule](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/core/lib/duration.ts) constructor property. If the user is choosing to leverage the [static method rate](https://github.com/aws/aws-cdk/blob/dd5e12d43231d991971de3121928377569b2dd63/packages/%40aws-cdk/aws-events/lib/schedule.ts#L19) it accepts ANY valid [Duration](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/core/lib/duration.ts) value. However this method will throw and it is expected to throw if that value is not a whole number of minutes. Currently it is expected of the user to click on and read [this documentation](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-event-patterns.html). The aforementioned documentation link that is provided does not immediately discuss this limitation it is better defined [here](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-create-rule-schedule.html) to understand that this is not a possibility. I think this would provide some clarity to new users interfacing with Rules for the first time.

**Comment by Ayan-web** [comment]
hey everyone.
I want to  make my first contribution to this project
thank you

**Comment by Yash621** [comment]
@mwithington can I work on this ?
