### ISSUE TITLE
(aws-cdk-api-reference): allow searching in the ref

### ISSUE THREAD

**Issue by Lewenhaupt** [aws/aws-cdk#17813]
### Describe your issue?

We've just started trying to move from cloudformation templates to aws-cdk in our org and it immediately struck me as odd that I cannot search in https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_rds.CfnDBInstance.html ? This makes it much harder to find what a user is looking for unless they know exactly where to look.

Not sure of the technical feasibility of this but I just needed to bring it up at least.

**Comment by jonniedarko** [comment]
:+1:  for this

**Comment by peterwoodworth** [comment]
Closing as duplicate of https://github.com/aws/aws-cdk/issues/5634
