### ISSUE TITLE
(aws-cdk-migration): Construct imports not rewritten

### ISSUE THREAD

**Issue by bmacher** [aws/aws-cdk#17826]
### What is the problem?

When migrating CDK imports with `aws-cdk-migration` then the `Construct` class is imported from `aws-cdk-lib`. However, `aws-cdk-lib` does not export `Construct` but `constructs` does.

### Reproduction Steps

```ts
import { App, Construct, Stage } from '@aws-cdk/core';
```

### What did you expect to happen?

```ts
import { App, Stage } from 'aws-cdk-lib';
import { Construct } from 'constructs';
```

### What actually happened?

```ts
import { App, Construct, Stage } from 'aws-cdk-lib';
```

### CDK CLI Version

2.0.0

### Framework Version

2.0.0

### Node.js Version

14.16.1

### OS

macOS

### Language

Typescript

### Language Version

^4.3.2

**Comment by NGL321** [comment]
I have confirmed this behavior, but have not yet confirmed what causes it.

**Comment by bmacher** [comment]
I assume, that it is just not considered. Only the part after `from` is migrated currently, which is fine in any other case.

**Comment by njlynch** [comment]
This was a known gap in the tool leading up to launch; it should have been more clearly documented that we had not (yet) handled this case.

I'll take a look at it this week and see if we can't make some progress.
