### ISSUE TITLE
(aws-cdk.aws-lambda): old constructs dependency in Python

### ISSUE THREAD

**Issue by andreiaugustin** [aws/aws-cdk#17821]
### What is the problem?

Using cdk 2.0.0 (build 4b6ce31) on Intel macOS 12.0.1 with python 3.8, starting a new project with cdk init --language python creates a requirements with:

aws-cdk-lib==2.0.0
constructs>=10.0.0,<11.0.0

However, if you then want to pip install aws-cdk.aws-lambda, we get aws-cdk.aws-lambda 1.134.0 with a constructs dependency of version >=3.3.69,<4.0.0, whilst aws-cdk-lib requires a newer version - this is also mentioned when installing aws-lambda:

ERROR: aws-cdk-lib 2.0.0 has requirement constructs<11.0.0,>=10.0.0, but you'll have constructs 3.3.161 which is incompatible.

In the end, cdk synth fails with the following trace log:

Traceback (most recent call last):
  File "app.py", line 4, in <module>
    import aws_cdk as cdk
  File "/Users/andreiaugustin/Desktop/Development/omnis_aws_demo/cdk_lambda/.venv/lib/python3.8/site-packages/aws_cdk/__init__.py", line 21457, in <module>
    from . import aws_apigateway
  File "/Users/andreiaugustin/Desktop/Development/omnis_aws_demo/cdk_lambda/.venv/lib/python3.8/site-packages/aws_cdk/aws_apigateway/__init__.py", line 1239, in <module>
    from ..aws_certificatemanager import ICertificate as _ICertificate_c194c70b
  File "/Users/andreiaugustin/Desktop/Development/omnis_aws_demo/cdk_lambda/.venv/lib/python3.8/site-packages/aws_cdk/aws_certificatemanager/__init__.py", line 187, in <module>
    from ..aws_cloudwatch import (
  File "/Users/andreiaugustin/Desktop/Development/omnis_aws_demo/cdk_lambda/.venv/lib/python3.8/site-packages/aws_cdk/aws_cloudwatch/__init__.py", line 495, in <module>
    from ._jsii import *
  File "/Users/andreiaugustin/Desktop/Development/omnis_aws_demo/cdk_lambda/.venv/lib/python3.8/site-packages/aws_cdk/aws_cloudwatch/_jsii/__init__.py", line 11, in <module>
    import aws_cdk.aws_iam._jsii
  File "/Users/andreiaugustin/Desktop/Development/omnis_aws_demo/cdk_lambda/.venv/lib/python3.8/site-packages/aws_cdk/aws_iam/__init__.py", line 484, in <module>
    from ._jsii import *
  File "/Users/andreiaugustin/Desktop/Development/omnis_aws_demo/cdk_lambda/.venv/lib/python3.8/site-packages/aws_cdk/aws_iam/_jsii/__init__.py", line 11, in <module>
    import aws_cdk.core._jsii
  File "/Users/andreiaugustin/Desktop/Development/omnis_aws_demo/cdk_lambda/.venv/lib/python3.8/site-packages/aws_cdk/core/__init__.py", line 6297, in <module>
    class ConstructNode(metaclass=jsii.JSIIMeta, jsii_type="@aws-cdk/core.ConstructNode"):
  File "/Users/andreiaugustin/Desktop/Development/omnis_aws_demo/cdk_lambda/.venv/lib/python3.8/site-packages/aws_cdk/core/__init__.py", line 6477, in ConstructNode
    runtime_info: typing.Optional[aws_cdk.cx_api.RuntimeInfo] = None,
AttributeError: partially initialized module 'aws_cdk' has no attribute 'cx_api' (most likely due to a circular import)
Subprocess exited with error 1

### Reproduction Steps

mkdir test

cd !$

cdk init --language python

.source .venv/bin/activate

cdk synth 

pip install -r requirements.txt

pip install aws-cdk.aws-lambda

cdk synth

### What did you expect to happen?

I would expect aws-cdk.aws-lambda to be installed without any issues on a fresh project and the ability to start using it right away.

### What actually happened?

Installing the aws-cdk.aws-lambda broke cdk synth due to dependency incompatibility.

### CDK CLI Version

2.0.0 (build 4b6ce31)

### Node.js Version

v16.13.0

### OS

macOS 12.0.1 Monterey 

### Language

Python

### Language Version

Python (3.8.3)

### Other information

Traceback (most recent call last):
  File "app.py", line 4, in <module>
    import aws_cdk as cdk
  File "/Users/andreiaugustin/Desktop/Development/omnis_aws_demo/cdk_lambda/.venv/lib/python3.8/site-packages/aws_cdk/__init__.py", line 21457, in <module>
    from . import aws_apigateway
  File "/Users/andreiaugustin/Desktop/Development/omnis_aws_demo/cdk_lambda/.venv/lib/python3.8/site-packages/aws_cdk/aws_apigateway/__init__.py", line 1239, in <module>
    from ..aws_certificatemanager import ICertificate as _ICertificate_c194c70b
  File "/Users/andreiaugustin/Desktop/Development/omnis_aws_demo/cdk_lambda/.venv/lib/python3.8/site-packages/aws_cdk/aws_certificatemanager/__init__.py", line 187, in <module>
    from ..aws_cloudwatch import (
  File "/Users/andreiaugustin/Desktop/Development/omnis_aws_demo/cdk_lambda/.venv/lib/python3.8/site-packages/aws_cdk/aws_cloudwatch/__init__.py", line 495, in <module>
    from ._jsii import *
  File "/Users/andreiaugustin/Desktop/Development/omnis_aws_demo/cdk_lambda/.venv/lib/python3.8/site-packages/aws_cdk/aws_cloudwatch/_jsii/__init__.py", line 11, in <module>
    import aws_cdk.aws_iam._jsii
  File "/Users/andreiaugustin/Desktop/Development/omnis_aws_demo/cdk_lambda/.venv/lib/python3.8/site-packages/aws_cdk/aws_iam/__init__.py", line 484, in <module>
    from ._jsii import *
  File "/Users/andreiaugustin/Desktop/Development/omnis_aws_demo/cdk_lambda/.venv/lib/python3.8/site-packages/aws_cdk/aws_iam/_jsii/__init__.py", line 11, in <module>
    import aws_cdk.core._jsii
  File "/Users/andreiaugustin/Desktop/Development/omnis_aws_demo/cdk_lambda/.venv/lib/python3.8/site-packages/aws_cdk/core/__init__.py", line 6297, in <module>
    class ConstructNode(metaclass=jsii.JSIIMeta, jsii_type="@aws-cdk/core.ConstructNode"):
  File "/Users/andreiaugustin/Desktop/Development/omnis_aws_demo/cdk_lambda/.venv/lib/python3.8/site-packages/aws_cdk/core/__init__.py", line 6477, in ConstructNode
    runtime_info: typing.Optional[aws_cdk.cx_api.RuntimeInfo] = None,
AttributeError: partially initialized module 'aws_cdk' has no attribute 'cx_api' (most likely due to a circular import)
Subprocess exited with error 1

**Comment by kaizen3031593** [comment]
Hi @andreiaugustin! I'm not sure why you need to install `aws-cdk.aws-lambda` here. The point of cdk v2 (`aws-cdk-lib`) is that we bundle all modules into a single package, removing the pain point in v1 where you had to import each individual module. Here's the v2 [dev guide](https://docs.aws.amazon.com/cdk/v2/guide/migrating-v2.html).

An example of v2 imports in Python:

```python
from constructs import Construct
from aws_cdk import App, Stack                   # core constructs
from aws_cdk import aws_lambda as lambda_        # stable module, imported from `aws-cdk-lib`
import aws_cdk.aws_codestar_alpha as codestar    # experimental modules need to be installed and are not a part of `aws-cdk-lib`.
```

Let me know if this helps, or if I'm totally missing your problem here! It looks to me like you are mixing v1 imports (aws-lambda) with v2, which is causing your dependency issue.

**Comment by andreiaugustin** [comment]
Hello @kaizen3031593, you're totally right! I should have RTFM instead of going by the AWS CDK presentation at re:Invent from 2018 I had found on YouTube and trying to do the equivalent in Python.

Thanks a lot for your help, sorry to have wasted your time!

**Comment by trobert2** [comment]
> Hi @andreiaugustin! I'm not sure why you need to install `aws-cdk.aws-lambda` here. The point of cdk v2 (`aws-cdk-lib`) is that we bundle all modules into a single package, removing the pain point in v1 where you had to import each individual module. Here's the v2 [dev guide](https://docs.aws.amazon.com/cdk/v2/guide/migrating-v2.html).
> 
> An example of v2 imports in Python:
> 
> ```python
> from constructs import Construct
> from aws_cdk import App, Stack                   # core constructs
> from aws_cdk import aws_lambda as lambda_        # stable module, imported from `aws-cdk-lib`
> import aws_cdk.aws_codestar_alpha as codestar    # experimental modules need to be installed and are not a part of `aws-cdk-lib`.
> ```
> 
> Let me know if this helps, or if I'm totally missing your problem here! It looks to me like you are mixing v1 imports (aws-lambda) with v2, which is causing your dependency issue.

I am facing a similar issue right now trying to deploy a python lambda function. I am confused.

So we have ```
$ cdk version
2.9.0
```
I now do a `cdk init` to start my project.
Next up I want to deploy a python AWS lambda function.
where I should be getting `aws_cdk.aws_lambda_python` if not to pip install it? what is the `v2` equivalent? `aws_cdk.aws_lambda_python_alpha` seems to be the one. OK, let's try to install it.

```
pip install aws_cdk.aws_lambda_python_alpha
Collecting aws_cdk.aws_lambda_python_alpha
  Downloading aws_cdk.aws_lambda_python_alpha-2.9.0a0-py3-none-any.whl (55 kB)
     |████████████████████████████████| 55 kB 1.2 MB/s 
Requirement already satisfied: aws-cdk-lib<3.0.0,>=2.9.0 in ./.venv/lib/python3.8/site-packages (from aws_cdk.aws_lambda_python_alpha) (2.9.0)
Requirement already satisfied: jsii<2.0.0,>=1.52.1 in ./.venv/lib/python3.8/site-packages (from aws_cdk.aws_lambda_python_alpha) (1.52.1)
Requirement already satisfied: publication>=0.0.3 in ./.venv/lib/python3.8/site-packages (from aws_cdk.aws_lambda_python_alpha) (0.0.3)
Collecting constructs<11.0.0,>=10.0.0
  Using cached constructs-10.0.46-py3-none-any.whl (50 kB)
Requirement already satisfied: python-dateutil in ./.venv/lib/python3.8/site-packages (from jsii<2.0.0,>=1.52.1->aws_cdk.aws_lambda_python_alpha) (2.8.2)
Requirement already satisfied: attrs~=21.2 in ./.venv/lib/python3.8/site-packages (from jsii<2.0.0,>=1.52.1->aws_cdk.aws_lambda_python_alpha) (21.4.0)
Requirement already satisfied: cattrs<1.11,>=1.8; python_version >= "3.7" in ./.venv/lib/python3.8/site-packages (from jsii<2.0.0,>=1.52.1->aws_cdk.aws_lambda_python_alpha) (1.10.0)
Requirement already satisfied: typing-extensions<5.0,>=3.7 in ./.venv/lib/python3.8/site-packages (from jsii<2.0.0,>=1.52.1->aws_cdk.aws_lambda_python_alpha) (4.0.1)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.8/site-packages (from python-dateutil->jsii<2.0.0,>=1.52.1->aws_cdk.aws_lambda_python_alpha) (1.16.0)
ERROR: aws-cdk-core 1.139.0 has requirement constructs<4.0.0,>=3.3.69, but you'll have constructs 10.0.46 which is incompatible.
ERROR: aws-cdk-aws-ssm 1.139.0 has requirement constructs<4.0.0,>=3.3.69, but you'll have constructs 10.0.46 which is incompatible.
ERROR: aws-cdk-aws-sqs 1.139.0 has requirement constructs<4.0.0,>=3.3.69, but you'll have constructs 10.0.46 which is incompatible.
ERROR: aws-cdk-aws-signer 1.139.0 has requirement constructs<4.0.0,>=3.3.69, but you'll have constructs 10.0.46 which is incompatible.
ERROR: aws-cdk-aws-s3 1.139.0 has requirement constructs<4.0.0,>=3.3.69, but you'll have constructs 10.0.46 which is incompatible.
ERROR: aws-cdk-aws-s3-assets 1.139.0 has requirement constructs<4.0.0,>=3.3.69, but you'll have constructs 10.0.46 which is incompatible.
ERROR: aws-cdk-aws-logs 1.139.0 has requirement constructs<4.0.0,>=3.3.69, but you'll have constructs 10.0.46 which is incompatible.
ERROR: aws-cdk-aws-lambda 1.139.0 has requirement constructs<4.0.0,>=3.3.69, but you'll have constructs 10.0.46 which is incompatible.
ERROR: aws-cdk-aws-lambda-python 1.139.0 has requirement constructs<4.0.0,>=3.3.69, but you'll have constructs 10.0.46 which is incompatible.
ERROR: aws-cdk-aws-kms 1.139.0 has requirement constructs<4.0.0,>=3.3.69, but you'll have constructs 10.0.46 which is incompatible.
ERROR: aws-cdk-aws-iam 1.139.0 has requirement constructs<4.0.0,>=3.3.69, but you'll have constructs 10.0.46 which is incompatible.
ERROR: aws-cdk-aws-events 1.139.0 has requirement constructs<4.0.0,>=3.3.69, but you'll have constructs 10.0.46 which is incompatible.
ERROR: aws-cdk-aws-efs 1.139.0 has requirement constructs<4.0.0,>=3.3.69, but you'll have constructs 10.0.46 which is incompatible.
ERROR: aws-cdk-aws-ecr 1.139.0 has requirement constructs<4.0.0,>=3.3.69, but you'll have constructs 10.0.46 which is incompatible.
ERROR: aws-cdk-aws-ecr-assets 1.139.0 has requirement constructs<4.0.0,>=3.3.69, but you'll have constructs 10.0.46 which is incompatible.
ERROR: aws-cdk-aws-ec2 1.139.0 has requirement constructs<4.0.0,>=3.3.69, but you'll have constructs 10.0.46 which is incompatible.
ERROR: aws-cdk-aws-codeguruprofiler 1.139.0 has requirement constructs<4.0.0,>=3.3.69, but you'll have constructs 10.0.46 which is incompatible.
ERROR: aws-cdk-aws-cloudwatch 1.139.0 has requirement constructs<4.0.0,>=3.3.69, but you'll have constructs 10.0.46 which is incompatible.
ERROR: aws-cdk-aws-autoscaling-common 1.139.0 has requirement constructs<4.0.0,>=3.3.69, but you'll have constructs 10.0.46 which is incompatible.
ERROR: aws-cdk-aws-applicationautoscaling 1.139.0 has requirement constructs<4.0.0,>=3.3.69, but you'll have constructs 10.0.46 which is incompatible.
ERROR: aws-cdk-assets 1.139.0 has requirement constructs<4.0.0,>=3.3.69, but you'll have constructs 10.0.46 which is incompatible.
Installing collected packages: constructs, aws-cdk.aws-lambda-python-alpha
  Attempting uninstall: constructs
    Found existing installation: constructs 3.3.201
    Uninstalling constructs-3.3.201:
      Successfully uninstalled constructs-3.3.201
Successfully installed aws-cdk.aws-lambda-python-alpha-2.9.0a0 constructs-10.0.46
```

If this is the way it is supposed to be installed then:
1) why are those errors there in the output?
2) why are all the libraries generated by the v2 CLI `v1.139.0` (even `v1.141.0` is out BTW) and not `v2.9.0` so that it matches https://docs.aws.amazon.com/cdk/api/v2/docs/@aws-cdk_aws-lambda-python-alpha.PythonFunction.html
3) why is the original issue still there?

so finally I wonder how do I get going with a new project, if following the getting started guide is not the way to go?
