### ISSUE TITLE
(aws-cloudfront) - 504 when using S3's website endpoint

### ISSUE THREAD

**Issue by bobstanton** [aws/aws-cdk#17835]
### What is the problem?

When pointing CloudFront to an S3 bucket's **website** endpoint using ``bucketWebsiteDomainName``, CloudFront returns a **504 ERROR The request could not be satisfied.** error message when navigating to the distribution domain name. 

If you use the bucket's ``bucketRegionalDomainName``, CloudFront is able to retrieve objects from the S3 bucket, however you lose out on the functionality provided with the website endpoint.

After deploying this stack, if you edit the origin in the console and click into the origin domain select box without actually making any changes, then hit save changes, everything works. If you do not open the origin domain select box, save changes does not do anything. If you deploy the stack again, cdk does not detect changes to apply. It seems like there is something different between how the console and cdk apply the origin domain name. 

### Reproduction Steps

```
const { Stack, Duration } = require('aws-cdk-lib');
const s3 = require('aws-cdk-lib/aws-s3');
const cloudfront = require('aws-cdk-lib/aws-cloudfront');
const s3deploy = require('aws-cdk-lib/aws-s3-deployment');
const iam = require('aws-cdk-lib/aws-iam');

class StaticSiteStack extends Stack {
  /**
   *
   * @param {Construct} scope
   * @param {string} id
   * @param {StackProps=} props
   */
  constructor(scope, id, props) {
    super(scope, id, props);

    const siteBucket = new s3.Bucket(this, 'SiteBucket', {
      bucketName: 'staticsitestackbucket',
      websiteIndexDocument: 'index.html',
      websiteErrorDocument: 'error.html',
    });

    siteBucket.addToResourcePolicy(new iam.PolicyStatement({
      actions: ['*'],
      resources: [siteBucket.arnForObjects('*')],
      principals: [new iam.AnyPrincipal()]
    }));
 
    new s3deploy.BucketDeployment(this, 'SiteBucketDeployment', {
      sources: [s3deploy.Source.asset('./site-contents')],
      destinationBucket: siteBucket,
    });

    const distribution = new cloudfront.CloudFrontWebDistribution(this, 'SiteDistribution', {
      originConfigs: [
        {
          customOriginSource: {
            domainName: siteBucket.bucketWebsiteDomainName,
          },
          behaviors: [{
            isDefaultBehavior: true,
            compress: true,
            allowedMethods: cloudfront.CloudFrontAllowedMethods.GET_HEAD_OPTIONS,
          }],
        }
      ]
    });



  }
}

module.exports = { StaticSiteStack }

```

### What did you expect to happen?

I expect CloudFront to return content from S3 when using the S3 bucket's website endpoint as an custom origin domain. I also expect cdk to save the custom origin domain name in the same way that the console does. 

### What actually happened?

504 ERROR
The request could not be satisfied.
CloudFront attempted to establish a connection with the origin, but either the attempt failed or the origin closed the connection. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.

Generated by cloudfront (CloudFront)
Request ID: WP-KeGihiQK5YI1cZ_JMA9JICRD-ibjtvO5pBlUwcgD1mllXQ_sQXA==

### CDK CLI Version

2.0.0 (build 4b6ce31)

### Node.js Version

16.13.1

### OS

macOS 12.0.1

### Language

Typescript

### Other information

[static-site.zip](https://github.com/aws/aws-cdk/files/7651252/static-site.zip)

**Comment by robertd** [comment]
@bobstanton Have you tried using `Distribution` construct instead? That's the new way of doing CloudFront distributions.

**Comment by bobstanton** [comment]
I see exactly the same behavior with the ``Distribution`` construct, however I am not using the ``OriginAccessIdentity`` approach as that bypasses ``S3``'s static website hosting benefits (default object redirects in subfolders without having to use a ``CloudFront Function`` to rewrite the URL, ability to use redirects). 

```
const { Stack, Duration } = require('aws-cdk-lib');
const s3 = require('aws-cdk-lib/aws-s3');
const cloudfront = require('aws-cdk-lib/aws-cloudfront');
const origins = require('aws-cdk-lib/aws-cloudfront-origins');
const s3deploy = require('aws-cdk-lib/aws-s3-deployment');
const iam = require('aws-cdk-lib/aws-iam');

class StaticSiteStack extends Stack {
  /**
   *
   * @param {Construct} scope
   * @param {string} id
   * @param {StackProps=} props
   */
  constructor(scope, id, props) {
    super(scope, id, props);

    const siteBucket = new s3.Bucket(this, 'SiteBucket', {
      bucketName: 'staticsitestackbucket',
      websiteIndexDocument: 'index.html',
      websiteErrorDocument: 'error.html',
    });

    siteBucket.addToResourcePolicy(new iam.PolicyStatement({
      actions: ['*'],
      resources: [siteBucket.arnForObjects('*')],
      principals: [new iam.AnyPrincipal()]
    }));
 
    new s3deploy.BucketDeployment(this, 'SiteBucketDeployment', {
      sources: [s3deploy.Source.asset('./site-contents')],
      destinationBucket: siteBucket,
    });

    const distribution = new cloudfront.Distribution(this, 'SiteDistribution', {
      defaultBehavior: {
        origin: new origins.HttpOrigin(siteBucket.bucketWebsiteDomainName, {
          originPath: "", 
        })
      }
    });


  }
}

module.exports = { StaticSiteStack }

```

**Comment by njlynch** [comment]
> After deploying this stack, if you edit the origin in the console [...] everything works.

Very strange!

Could you repeat this experiment, and capture the output of [`get-distribution-config`](https://docs.aws.amazon.com/cli/latest/reference/cloudfront/get-distribution-config.html) before and after? Obviously, the console is making an update behind the scenes, and I'd be quite curious to know what it's doing.

> If you deploy the stack again, cdk does not detect changes to apply.

This how CloudFormation -- which cdk relies on under the hood -- works. Any changes made outside of CloudFormation aren't detected automatically, meaning the cdk diff/deploy is only every looking at the last template CloudFormation knows about versus the current template. However, a CloudFront Distribution is one of the resources that supports [drift detection](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-import-supported-resources.html). You can use the console or [`detect-stack-drift`](https://docs.aws.amazon.com/cli/latest/reference/cloudformation/detect-stack-drift.html) API call to detect the changes (as an alternative/additive to calling `get-distribution-config` before/after).

**Comment by bobstanton** [comment]
Good call, the difference was in the ``OriginProtocolPolicy``, I didn't realize the default was https, setting ``ProtocolPolicy = OriginProtocolPolicy.HTTP_ONLY`` on the ``Origin`` resolves this. Thanks!
