### ISSUE TITLE
[v2] apigatewayv2: Missing higher level constructs for HTTP APIs

### ISSUE THREAD

**Issue by kensukesaito** [aws/aws-cdk#17843]
### Description

In v1, "@aws-cdk/aws-apigatewayv2" has higher level constructs for HTTP APIs ("HttpApi").
https://docs.aws.amazon.com/cdk/api/latest/docs/aws-apigatewayv2-readme.html

But in v2, "aws-cdk-lib/aws_apigatewayv2" does not have them (has only low-level constructs "Cfn*").
https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_apigatewayv2-readme.html

### Use Case

I would like to construct HTTP APIs in API Gateway using AWS CDK v2.

https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api.html

### Proposed Solution

Provide higher level constructs for HTTP APIs in "aws-cdk-lib/aws_apigatewayv2" of AWS CDK v2.

### Other information

```json
  "dependencies": {
    "aws-cdk-lib": "^2.0.0",
    "constructs": "^10.0.9",
    "source-map-support": "^0.5.21"
  },
  "devDependencies": {
    "aws-cdk": "^2.0.0",
  }
```

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by bobstanton** [comment]
It looks like these have been moved to an Alpha module:

https://docs.aws.amazon.com/cdk/api/v2/docs/@aws-cdk_aws-apigatewayv2-alpha.HttpApi.html

**Comment by kensukesaito** [comment]
@bobstanton 
Thank you, Bob. You helped me a lot.

Experimental construct libraries are now available in AWS CDK v2 | AWS Developer Tools Blog
https://aws.amazon.com/jp/blogs/developer/experimental-construct-libraries-are-now-available-in-aws-cdk-v2/
