### ISSUE TITLE
snapshot test example isn't actually a snapshot test

### ISSUE THREAD

**Issue by jesterhazy** [aws/aws-cdk#17846]
### link to reference doc page

https://docs.aws.amazon.com/cdk/latest/guide/testing.html#testing_snapshot

### Describe your issue?

The [snapshot test](https://docs.aws.amazon.com/cdk/latest/guide/testing.html#testing_snapshot) section of the developer guide includes an example, but the example isn't actually a snapshot test. 

The example should be replaced with a real snapshot test so people can see how to write this kind of test.

**Comment by Jerry-AWS** [comment]
I've added this to the Developer Guide backlog and so I'll close this.

https://github.com/awsdocs/aws-cdk-guide/issues/374
