### ISSUE TITLE
(assert): there should be something like ```haveManifest(...)``` and ```haveHelmChart```  or a matcher like ```k8sobjectlike``` that allow unit tests for kubernetes objects

### ISSUE THREAD

**Issue by markussiebert** [aws/aws-cdk#17854]
### Description

It would be nice if we could write unit tests for eks components like helmcharts and manifests. These resources contain JSON objects (the kubernetes manifests or helmchart values) that are stringified via:

```ts
/**
   * Convert an object, potentially containing tokens, to a JSON string
   */
public toJsonString(obj: any, space?: number): string {
  return CloudFormationLang.toJSON(obj, space).toString();
}
```

It would be nice if this would be parsed and then could be used with matchers like objectLike or arrayWith

### Use Case

I want to create unit tests for constructs that contain kubernetes resources. At the moment it's not possible or I didn't found the docs how to do this. 

I only find examples that do something like:

```ts
expect(stack).toHaveResource(KubernetesManifest.RESOURCE_TYPE, {
  Manifest: JSON.stringify([
    {
      apiVersion: 'v1beta',
      kind: 'Foo',
      metadata: {
        labels: {
          'aws.cdk.eks/prune-c89a5983505f58231ac2a9a86fd82735ccf2308eac': '',
        },
      },
    },
  ]),
  PruneLabel: 'aws.cdk.eks/prune-c89a5983505f58231ac2a9a86fd82735ccf2308eac',
});
```

but I would like to have something like:

```ts
expect(stack).toHaveManifest('SomeIdentifier?', {
  Manifest: arrayWith(
    {
      apiVersion: 'v1beta',
      kind: 'Foo',
      ...
      anything: objectLike({
        some: 'value'
      }
    },
  ]),
...
});
```

### Proposed Solution

I have no Idea at the moment... somehow we have to JSON parse the stringified k8s objects

### Other information

no

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by kaizen3031593** [comment]
Hi @markussiebert! Have you tried using the new Assertions library, specifically [`Match.serializedJson()`](https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/assertions#serialized-json)?

**Comment by markussiebert** [comment]
Looks perfect! Will give it a try tomorrow!

**Comment by kaizen3031593** [comment]
Going to close this issue for now. Feel free to re-open it if you still feel like there's something missing!

**Comment by markussiebert** [comment]
only for others who stumble over this: works like a charm!
