### ISSUE TITLE
(ec2.SubnetConfiguration): Use list comprehensions created twice the expected number of subnets.

### ISSUE THREAD

**Issue by the-exile-110** [aws/aws-cdk#17852]
### General Issue

(ec2.SubnetConfiguration): Use list comprehensions created twice the expected number of subnets.

### The Question

Like the example code, 
when I generate SubnetConfiguration using list derivative and deploy it, 6 subnets are actually created.
What is the reason for this? And how can I improve him?

        public_subnet_count = 3

        subnets = [
            ec2.SubnetConfiguration(
                cidr_mask=24,
                name=f'{vpc_name}-public-{i}-',
                subnet_type=ec2.SubnetType.PUBLIC,  # PRIVATE_ISOLATED | PRIVATE_WITH_NAT | PUBLIC
            ) for i in range(public_subnet_count)
        ] 
        
        print(f'Creating VPC {vpc_name} with {len(subnets)} subnets')

        vpc = ec2.Vpc(
            self, 'example-vpc',
            cidr='10.0.0.0/16',
            max_azs=3,
            subnet_configuration=subnets,
            nat_gateways=nat_gateway_count if nat_gateway_count > 0 else None,
        )

--- 

```
➜  cdk diff 
Creating VPC example-vpc with 3 subnets
Stack example-vpc-stack
Parameters
[+] Parameter BootstrapVersion BootstrapVersion: {"Type":"AWS::SSM::Parameter::Value<String>","Default":"/cdk-bootstrap/hnb659fds/version","Description":"Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]"}

Resources
[+] AWS::EC2::VPC example-vpc examplevpcA94D7A64 
[+] AWS::EC2::Subnet example-vpc/example-vpc-public-0-Subnet1/Subnet 
[+] AWS::EC2::RouteTable example-vpc/example-vpc-public-0-Subnet1/RouteTable 
[+] AWS::EC2::SubnetRouteTableAssociation example-vpc/example-vpc-public-0-Subnet1/RouteTableAssociation 
[+] AWS::EC2::Route example-vpc/example-vpc-public-0-Subnet1/DefaultRoute 
[+] AWS::EC2::Subnet example-vpc/example-vpc-public-0-Subnet2/Subnet 
[+] AWS::EC2::RouteTable example-vpc/example-vpc-public-0-Subnet2/RouteTable 
[+] AWS::EC2::SubnetRouteTableAssociation example-vpc/example-vpc-public-0-Subnet2/RouteTableAssociation 
[+] AWS::EC2::Route example-vpc/example-vpc-public-0-Subnet2/DefaultRoute 
[+] AWS::EC2::Subnet example-vpc/example-vpc-public-1-Subnet1/Subnet 
[+] AWS::EC2::RouteTable example-vpc/example-vpc-public-1-Subnet1/RouteTable 
[+] AWS::EC2::SubnetRouteTableAssociation example-vpc/example-vpc-public-1-Subnet1/RouteTableAssociation 
[+] AWS::EC2::Route example-vpc/example-vpc-public-1-Subnet1/DefaultRoute 
[+] AWS::EC2::Subnet example-vpc/example-vpc-public-1-Subnet2/Subnet 
[+] AWS::EC2::RouteTable example-vpc/example-vpc-public-1-Subnet2/RouteTable 
[+] AWS::EC2::SubnetRouteTableAssociation example-vpc/example-vpc-public-1-Subnet2/RouteTableAssociation 
[+] AWS::EC2::Route example-vpc/example-vpc-public-1-Subnet2/DefaultRoute 
[+] AWS::EC2::Subnet example-vpc/example-vpc-public-2-Subnet1/Subnet 
[+] AWS::EC2::RouteTable example-vpc/example-vpc-public-2-Subnet1/RouteTable 
[+] AWS::EC2::SubnetRouteTableAssociation example-vpc/example-vpc-public-2-Subnet1/RouteTableAssociation 
[+] AWS::EC2::Route example-vpc/example-vpc-public-2-Subnet1/DefaultRoute 
[+] AWS::EC2::Subnet example-vpc/example-vpc-public-2-Subnet2/Subnet 
[+] AWS::EC2::RouteTable example-vpc/example-vpc-public-2-Subnet2/RouteTable 
[+] AWS::EC2::SubnetRouteTableAssociation example-vpc/example-vpc-public-2-Subnet2/RouteTableAssociation 
[+] AWS::EC2::Route example-vpc/example-vpc-public-2-Subnet2/DefaultRoute 
[+] AWS::EC2::InternetGateway example-vpc/IGW examplevpcIGW4D98DF86 
[+] AWS::EC2::VPCGatewayAttachment example-vpc/VPCGW examplevpcVPCGW8EED3424 
```

### CDK CLI Version

v2

### Framework Version

python3.9

### OS

ubuntu 20.04

### Language

Python

### Language Version

python3.9

**Comment by peterwoodworth** [comment]
This is probably working as intended - According to our docs on [SubnetConfiguration](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ec2.Vpc.html#subnetconfiguration):

> Each entry in this list configures a Subnet Group; each group will contain a subnet for each Availability Zone.

So, you're likely creating one of each subnet in two different availability zones.

**Comment by the-exile-110** [comment]
@peterwoodworth 

Thank you, after I tried again and again I found that the number of subnets created depends on the parameter max_azs, I changed the following code and now it works as expected


        vpc_name = 'example-vpc'
        cidr = '10.0.0.0/16'
        subnet_cidr_mask = 24
        max_azs = 1
        enable_public_subnet = True
        enable_private_subnet = True
        nat_gateway_count = 0

        public_subnets = [
            ec2.SubnetConfiguration(
                cidr_mask=subnet_cidr_mask,
                name=f'{vpc_name}-public-',
                subnet_type=ec2.SubnetType.PUBLIC,  # PRIVATE_ISOLATED | PRIVATE_WITH_NAT | PUBLIC
            )
        ] if enable_public_subnet else []

        private_subnets = [
            ec2.SubnetConfiguration(
                cidr_mask=subnet_cidr_mask,
                name=f'{vpc_name}-private-is-olated-',
                subnet_type=ec2.SubnetType.PRIVATE_ISOLATED,
            )
        ] if enable_private_subnet else []

        private_subnets_with_nat = [
            ec2.SubnetConfiguration(
                cidr_mask=subnet_cidr_mask,
                name=f'{vpc_name}-private-with-nat-',
                subnet_type=ec2.SubnetType.PRIVATE_WITH_NAT,
            )
        ] if nat_gateway_count > 0 else []

        subnets = public_subnets + private_subnets + private_subnets_with_nat

        vpc = ec2.Vpc(
            self, vpc_name,
            cidr=cidr,
            max_azs=max_azs,
            subnet_configuration=subnets if len(subnets) > 0 else None,
            nat_gateways=nat_gateway_count if nat_gateway_count > 0 else None,
        )
        [tags.add(vpc, key, value) for key, value in tags.items()]
        return vpc
