### ISSUE TITLE
cloudfront.distribution: No outputs

### ISSUE THREAD

**Issue by automartin5000** [aws/aws-cdk#17856]
### What is the problem?

When creating a CloudFront distribution, there's no output for the domain name in the stack outputs. I'm filing this as a bug, because when I create it with a nested stack, it seems to output the domain name as expected.

### Reproduction Steps

Add cloudfront.Distribution construct to app. No stack output for domain name

### What did you expect to happen?

Add cloudfront.Distribution construct to app. Get stack output for distribution domain name as well as the Route53 CNAME attached to it (if one exists).

### What actually happened?

No stack outputs for cloudfront.Distribution

### CDK CLI Version

2

### Framework Version

2

### Node.js Version

16.10.0

### OS

Mac OS 12.0.1

### Language

Python

### Language Version

3.9

**Comment by njlynch** [comment]
> When creating a CloudFront distribution, there's no output for the domain name in the stack outputs.

How are you outputting the domain name? Can you share a reproducible example?

**Comment by automartin5000** [comment]
Oh sorry, I should've clarified that I'm not explicitly outputting the domain name. I would've called this a feature request that I thought it should be output by default, but then I noticed that it was being output if the resource is in a nested stack. So I thought it might be a bug that it works in nested stack constructs but not standard stack constructs?

**Comment by njlynch** [comment]
It sounds like you are likely using the domain value outside of the nested stack. This automatically creates an Output so that value can be used. See our [documentation](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib-readme.html#nested-stacks):

> Resources references across nested/parent boundaries (even with multiple levels of nesting) will be wired by the AWS CDK through CloudFormation parameters and outputs. When a resource from a parent stack is referenced by a nested stack, a CloudFormation parameter will automatically be added to the nested stack and assigned from the parent; when a resource from a nested stack is referenced by a parent stack, a CloudFormation output will be automatically be added to the nested stack and referenced using Fn::GetAtt "Outputs.Xxx" from the parent.

We don't otherwise automatically create outputs for arbitrary properties of constructs. If you want to have the domain outputted yourself, simply use a [CfnOutput](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.CfnOutput.html) to to do so.

Hope that helps!
