### ISSUE TITLE
(add_cdk8s_chart): Ignores namespace provided with "helm_flags"

### ISSUE THREAD

**Issue by Alon-Katz** [aws/aws-cdk#17863]
### What is the problem?

Trying to install a helm chart defined in cdk8s, then providing the chart to cdk function "add_cdk8s_chart", results in the helm chart installed on the default namespace.

### Reproduction Steps

Helm chart in cdk8s:

```
from constructs import Construct
import cdk8s

class NginxIngressControllerChart(cdk8s.Chart):
    def __init__(self, scope: Construct, chart_id: str):
        super().__init__(scope, chart_id)
        cdk8s.Helm(self, id='nginx', chart='ingress-nginx/ingress-nginx', release_name="nginx", helm_flags=['--namespace', 'nginx', '--version', 'v3.3.0'])
```

Then in cdk:

```
nginx_ingress_chart = NginxIngressControllerChart(cdk8s.App(), "nginx-ingress")
self.cluster.add_cdk8s_chart("nginx-ingress", nginx_ingress_chart)

```

### What did you expect to happen?

Chart installed in "nginx" namespace

### What actually happened?

Chart installed in "default" namespace

### CDK CLI Version

1.134.0 (build dd5e12d)

### Node.js Version

14

### OS

Mac

### Language

Python

### Language Version

3.6.5

### Other information

What is the correct way to this at the moment?

**Comment by Alon-Katz** [comment]
Fixed it with namespace attribute:
`super().__init__(scope, chart_id, namespace="nginx")`

Still, it feels like the namespace attribute in the helm_flags should work in case the helm chart needs to be deployed in a different namespace than the whole chart.

**Comment by NGL321** [comment]
Hey @Alon-Katz,

It looks like you got this figured out but are not entirely satisfied with the implementation, is that right? In that case we can turn this issue into a feature-request to have the adjustment review. It seems its a cdk8s issue though, so my recommendation is to create a new issue on that repo and link here.

Please let me know if I can help with this.
