### ISSUE TITLE
aws-wafv2: Not able to provision IPSetReferenceStatement in CfnRuleGroup

### ISSUE THREAD

**Issue by daknhh** [aws/aws-cdk#17864]
### What is the problem?

When ever i try to provision a IPSetReferenceStatement in CfnRuleGroup and i just enter a Arn for the IPSet the following error message occur:

`Resource handler returned message: "Error reason: You have used none or multiple values for a field that requires exactly one value., field: STATEMENT, parameter: Statement (Service: Wafv2, Status Code: 400, Request ID: f87bda08-81fc-447a-a44a-20245a1bebab, Extended Request ID: null)" (RequestToken: 1d533c05-6c13-09b3-63c8-2715db81cace, HandlerErrorCode: InvalidRequest)
[cdkdeploy] 	new PlattformWafv2CdkAutomationStack (/Users/davidkrohn/Documents/git/Clients/*/plattform-wafv2-cdk-automation/lib/plattform-wafv2-cdk-automation-stack.ts:251:27)
[cdkdeploy] 	\_ /Users/davidkrohn/Documents/git/Clients/*/plattform-wafv2-cdk-automation/bin/plattform-wafv2-cdk-automation.ts:208:5
[cdkdeploy] 	\_ processTicksAndRejections (internal/process/task_queues.js:95:5)`

### Reproduction Steps

Create a IPSetReferenceStatement in CfnRuleGroup and just enter Arn as Parameter

### What did you expect to happen?

IPSetReferenceStatement will be created

### What actually happened?

An empty Statement will occur in the cfn template

### CDK CLI Version

1.124.0

### Node.js Version

v14.17.6

### OS

macOS 12.0.1 (21A559)

### Language

Typescript

**Comment by peterwoodworth** [comment]
I've seen this error before and I was unable to reproduce it. I'll give it another go

**Comment by peterwoodworth** [comment]
aha! I've been able to reproduce it - and also fix it!

All you'll need to do is specify the `action` property on the rule that's throwing the error https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-wafv2-rulegroup-rule.html#cfn-wafv2-rulegroup-rule-action

**Comment by daknhh** [comment]
Hi @peterwoodworth even when i add action to the rulegroup its not working - here is a example statement

```
        "Statement": {
          "IPSetReferenceStatement": {
            "ARN": "XXXXXXX"
          }
        },
        "Action": {
          "Allow": {}
        },
        "VisibilityConfig": {
          "SampledRequestsEnabled": true,
          "CloudWatchMetricsEnabled": true
        }
```

"Error reason: You have used none or multiple values for a field that requires exactly one value., field: STATEMENT, parameter: Statement (Service: Wafv2, Status Code: 400, Request ID: 548792be-7e58-41a7-8fe4-4beddf7a174e, Extended Request ID: null)" (RequestToken: 9f8d2c28-00c2-be9a-e78e-31bacdf6cd18, HandlerErrorCode: InvalidRequest)

**Comment by daknhh** [comment]
Working now.
