### ISSUE TITLE
(cloudfront): Migration from CloudFrontWebDistribution to WebDistribution

### ISSUE THREAD

**Issue by DarshanAwachat** [aws/aws-cdk#17869]
### General Issue

General Issue

### The Question

I had the following code for CloudFrontWebDistribution

```
const webDistribution = new cloudfront.CloudFrontWebDistribution(this, 'MyCfnDistribution', {
    // ...
});
```
Converted it to support the Distribution Class

```
const webDistribution =new cloudfront.Distribution(this, 'MyCfnDistribution', {
    // ...
});
const distributionCfn = webDistribution.node.defaultChild as cloudfront.CfnDistribution;
distributionCfn.overrideLogicalId('LogicalId')
```
When I deployed this new code I got the following error:
```
Invalid request provided: The parameter globPattern is too small or empty. (Service: CloudFront, Status 
Code: 400
```
How Do I Solve this? Are there Any Other ways to Migrate to Distribution Construct?

### CDK CLI Version

1.126.0

### OS

Windows

### Language

Typescript

**Comment by peterwoodworth** [comment]
Hey @DarshanAwachat, 

I'm looking into this. Are you able to share the difference in synth output from before the migration and now?

**Comment by peterwoodworth** [comment]
There doesn't seem to be a direct way to not include the pathPattern, but you can override the CDK output for pathpattern on the additional behaviors with an escape hatch!

`distributionCfn.addPropertyDeletionOverride('DistributionConfig.CacheBehaviors.0.PathPattern')`

This will remove the `PathPattern` from your template for the first additional behavior you add. Simply change the number `0` to change which behavior you're modifying in the template

**Comment by DarshanAwachat** [comment]
Hi, Thanks @peterwoodworth It worked. I also wanted to know, are there issues in maitaining LogicalId's in codebase. Doing override like this
`distributionCfn.overrideLogicalId('LogicalId')`

**Comment by peterwoodworth** [comment]
Hey @DarshanAwachat, sorry I missed this

I'm not entirely sure what you're asking here, but you shouldn't run into any issues down the line just for overriding a logical ID. That should be stable 🙂
