### ISSUE TITLE
(@aws-cdk/aws-lambda): DockerImageFunction - Add an option to build Dockerfile without cache

### ISSUE THREAD

**Issue by kobakeiara** [aws/aws-cdk#17877]
### Description

When building a Dockerfile using DockerImageFunction, please add an option not to use cache like "docker-compose build --no-cache".

### Use Case

To keep packages, source files, dictionary files, etc. up to date.

### Proposed Solution

Please add an option not to use cache.

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by kirintwn** [comment]
Can use [`DockerImageAssetInvalidationOptions`](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-ecr-assets.DockerImageAssetInvalidationOptions.html) for this purpose.

E.G.
```ts
new lambda.DockerImageFunction(this, 'AssetFunction', {
  code: lambda.DockerImageCode.fromImageAsset(path.join(__dirname, 'docker-handler'), {
    invalidation: {
      file: true,
    },
  }),
});
```

**Comment by kobakeiara** [comment]
@kirintwn thank you for your advice.
