### ISSUE TITLE
(batch): AWS Step function batch submit

### ISSUE THREAD

**Issue by sandeepkumar2810** [aws/aws-cdk#17890]
### General Issue

How to get multiple values from the Jsonpath for container_overrides environment property

### The Question

Hi, i am trying to create a batch job using CDK inside AWS Step function and i am having issues getting multiple values from the Jsonpath to the container_overrides environment properties.
This works fine if we just have a single value.
Do we know how we can have BATCH_SCRIPT_PARAMS get multiple values from JsonPath like an array of string with a combination of dynamic value and fixed value like:
```
"BATCH_SCRIPT_PARAMS.$": " '$.param1' '$.param2'  'fixed_value1' 'fixed_value2', 'fixed_value3')"
job_prompts = "$.BillingCycleStartDate $.BillingCycleEndDate BillingType dbuser1 dbuser2"
```
Here `$.BillingCycleStartDate` and `$.BillingCycleEndDate` are the dynamic values which needs to be get from the `Jsonpath` of the payload, and rest of the values (BillingType dbuser1 dbuser2) are constants
```py
task = sfn_tasks.BatchSubmitJob(self, id,
    job_definition_arn=self.job_definition.job_definition_arn,
    job_name=id,
    job_queue_arn=self.job_queue.job_queue_arn,
    container_overrides={
      "environment":
        {
            "BATCH_FILE_S3_URL": step['ScriptLocation'],
            "BATCH_FILE_TYPE": step['ScriptFileType'],
            "BATCH_SCRIPT_PARAMS": sfn.JsonPath.string_at(job_prompts)
        },
        "command": job_to_run
    }
)
```

### CDK CLI Version

1.126.0 

### Language

Python

**Comment by peterwoodworth** [comment]
The Batch API for ContainerOverrides asks for an array of key value pairs for the environment parameter. https://docs.aws.amazon.com/batch/latest/APIReference/API_ContainerOverrides.html

I'm not aware of any ways to work around this, but I'm not super familiar with these services. I can look into this more
