### ISSUE TITLE
EKS : Applying Permissions boundary when ServiceAccount nested stack is created.

### ISSUE THREAD

**Issue by harshadbhatia** [aws/aws-cdk#17897]
### What is the problem?

When creating a service account in EKS. It creates OIDC provider custom resources such CfnUtils etc when used with Aspects to apply permission boundary. The role is not updated to include PermissionsBoundary.

### Reproduction Steps

- Have an AWS account which has Permissions Boundary policy in place for stopping role creation.
- Create an EKS cluster
- Add service account with no role or permissions in EKS.
- Using aspects update the stack to include permissions boundary.
- You will see any other IAM role will have permission boundary set except the CfnUtilsProvider and other Resources created when serviceAccount is called.

```
export class PermissionsBoundaryAspect implements IAspect {
  readonly permissionsBoundaryArn: string;
  constructor() {
    this.permissionsBoundaryArn = `arn:aws:iam::${Aws.ACCOUNT_ID}:policy/RolePermissionBoundary`;
  }
  visit(node: IConstruct): void {
    if (node instanceof Role) {
      const roleResource = node.node.findChild("Resource") as CfnRole;
      roleResource.addPropertyOverride("PermissionsBoundary", this.permissionsBoundaryArn);
    }
  }
}
```

### What did you expect to happen?

All IAM roles should have permissions boundary set as per code above.

### What actually happened?

All role created in stack has permissions boundary role except CfnUtilsProviderRole which is created only when calling cluster.addServiceAccount method.

### CDK CLI Version

2.0.0

### Node.js Version

16.3.1

### OS

Linux

### Language

Typescript

**Comment by robertd** [comment]
@harshadbhatia Can you please test with this code snipped? I've used to use your current implementation a while ago and there were some scenarios where PB wouldn't apply properly (see commented out code and links below). Second implementation of `visit` method there has been working for me flawlessly ever since. Let me know...

```
import cdk = require('aws-cdk-lib');
import iam = require('aws-cdk-lib/aws-iam');
import { IConstruct } from 'constructs';

export class PermissionsBoundary implements cdk.IAspect {
  private readonly permissionsBoundaryArn: string;

  constructor(permissionBoundaryArn: string) {
    this.permissionsBoundaryArn = permissionBoundaryArn;
  }

  // Initial permissions boundary workaround introduced in https://github.com/aws/aws-cdk/issues/3242#issuecomment-509530635
  // This workaround doesn't work in all cases as mentioned in https://github.com/aws/aws-cdk/issues/3242#issuecomment-561064190

  // public visit(node: cdk.IConstruct): void {
  //   if (node instanceof iam.Role) {
  //     const roleResource = node.node.findChild('Resource') as iam.CfnRole;
  //     roleResource.addPropertyOverride('PermissionsBoundary', this.permissionsBoundaryArn);
  //   }
  // }

  // Alternate workaround mentioned in https://github.com/aws/aws-cdk/issues/3242#issuecomment-561064190
  public visit(node: IConstruct): void {
    if (cdk.CfnResource.isCfnResource(node) && node.cfnResourceType === 'AWS::IAM::Role') {
      node.addPropertyOverride('PermissionsBoundary', this.permissionsBoundaryArn);
    }
  }
}

**Comment by otaviomacedo** [comment]
Another thing to try is to compare with `IRole` instead of `Role`:

```ts
...
visit(node: IConstruct): void {
    if (node instanceof IRole) {
...
```
