### ISSUE TITLE
(stepfunctions-tasks): add SourceLocationOverride property to CodeBuildStartBuild

### ISSUE THREAD

**Issue by saste** [aws/aws-cdk#17908]
### Description

It would be useful to pass the `SourceLocationOverride` as defined [here](https://docs.aws.amazon.com/codebuild/latest/APIReference/API_StartBuild.html) when starting a build with a [CodeBuildStartBuild](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_stepfunctions_tasks/CodeBuildStartBuild.html) task.

As a workaround it is still possible to use a `stepfunctions.CustomState`, but it would be neater to add the missing bindings to the API to be able to use a stepfunctions task.

### Use Case

We need to use the source provided by another task, so we need to define the source location override when calling the codebuild task.

Current workaround:
```
build_project = stepfunctions.CustomState(
     self, f"Build Project",
     state_json={
         "Type": "Task",
         "ResultPath": "$.result",
         "Resource": "arn:aws:states:::codebuild:startBuild.sync",
         "Parameters": {
               "ProjectName": codebuild_project.project_name,
               "EnvironmentVariablesOverride": environment_variables_override,
               "SourceLocationOverride.$": "$.download.Artifacts.Location"
            }
      }
 )
 ```
 

### Proposed Solution

It would be neater (and especially more expected) to use something as:
```
build_project = stepfunctions_tasks.CodeBuildStartBuild(
    self, f"Build Project",
    result_path="$.result",
    project=codebuild_project,
    environment_variables_override: environment_variables_override,
    source_location_override="$.download.Artifacts.Location"
)
```

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by kaizen3031593** [comment]
We do the same for `environmentVariablesOverride` so it seems relatively simple to add it in. However, there are a ton of possible overrides and we don't need to support them all. I think this is a question of how useful this particular override is, what the use case is for, and how many people need it (which we measure with +1s).
