### ISSUE TITLE
Auto-detect supported AWS Regions of the CDK

### ISSUE THREAD

**Issue by marcotesch** [aws/aws-cdk#1791]
Hi,

Is there a list which AWS regions are supported by the CDK at the moment?
As I'm experiencing deployment issues in the eu-north-1 region at the moment.

**Comment by rix0rrr** [comment]
Depending on the issues, you can get around those by adding `--no-version-reporting` to your `cdk` command probably.

**Comment by marcotesch** [comment]
In eu-north-1 it reports that AWS::CDK::METADATA is not supported as a resource, if that can be obtained by using --no-version-reporting im pleased with that solution.

Hence I think this would be nice if the Framework would handle such things internally for the actual AWS regions.

**Comment by eladb** [comment]
This is already supported #3149
