### ISSUE TITLE
(aws_s3_assets): unable to define bundling with local (python)

### ISSUE THREAD

**Issue by andrewjroth** [aws/aws-cdk#17928]
### link to reference doc page

https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_s3_assets/README.html#asset-bundling

### Describe your issue?

The documentation has an example which is not syntactically correct for Python:

```python
assets.Asset(self, "BundledAsset",
    path="/path/to/asset",
    bundling={
        "local": {
            def try_bundle(self, output_dir, options):
                if can_run_locally:
                    # perform local bundling here
                    return True
                return False
        },
        # Docker bundling fallback
        "image": DockerImage.from_registry("alpine"),
        "entrypoint": ["/bin/sh", "-c"],
        "command": ["bundle"]
    }
)
```

The value for 'bundling' isn't correct Python code.  You can't define a function in the middle of a dictionary.

I've attempted to determine how to correctly define this value, but haven't been able to come up with the correct syntax.  Based on the documentation, specific types are expected, so I tried constructing those types ahead of time:

```python
class JinjaLocalBundling(ILocalBundling):
    def try_bundle(self, output_dir, options, *args, **kwargs) -> bool:
        print("Local Jinja2 Render:", self, output_dir, options, args, kwargs)
        return False

JinjaBundling = BundlingOptions(
    local=JinjaLocalBundling,
    image=DockerImage.from_registry("python3"),
    command=["python3 -m pip install jinja2"]
)
```

Then, including it in the Asset creation:

```python
Asset(self, "BundleTest", path=os.path.join(dirname, "configure.jinja"),
      bundling=JinjaBundling)
```

This results in an error: 

`TypeError: Don't know how to convert object to JSON: <class 'test_app.test_stack.JinjaLocalBundling'>`

There is very little documentation on how to do this correctly.  Can someone demonstrate the correct way to use the `bundling` option for Asset definitions?

**Overall Goal**: I want to render a script to be executed as part of the EC2 User Data by replacing variables in the script with values from the stack.  For example, I have a script which syncs data from an S3 bucket, but the S3 bucket name needs to be injected into the script.  Something like this to replace `{{ bucketname }}` with the bucket defined by the CDK app:

```shell
aws s3 sync s3://{{ bucketname }}/path/ /tmp/path/
```

If there is an easier way to do this, please let me know.  (but also fix the doc since it really doesn't work)

Thanks!!

**Comment by otaviomacedo** [comment]
Can you try:

```python
@jsii.implements(ILocalBundling)
class JinjaLocalBundling()
    def try_bundle(...)
```

and then pass the instance of this class to `BundlingOptions`:

```python
JinjaBundling = BundlingOptions(
    local=JinjaLocalBundling(),
    ...
```

**Comment by andrewjroth** [comment]
Thanks for the suggestion, but that doesn't seem to work for me...

```python
@jsii.implements(ILocalBundling)
class JinjaLocalBundling(ILocalBundling):
    def try_bundle(self, output_dir, options, *args, **kwargs) -> bool:
        print("Local Jinja2 Render:", self, output_dir, options, args, kwargs)
        return False

JinjaBundling = BundlingOptions(
    local=JinjaLocalBundling(),
    image=DockerImage.from_registry("python3"),
    command=["python3 -m pip install jinja2"]
)
```

Within Stack class:
```python
asset = Asset(self, "ConfigureBundle", path=os.path.join(dirname, "configure.sh"),
                   bundling=JinjaBundling)
```

Result of `cdk synth`:
```
TypeError: Don't know how to convert object to JSON: <app.app_stack.JinjaLocalBundling object at 0x7fb8eb2aba90>
```

It seems that JSII wants to convert the `local` parameter to `BundlingOptions` to JSON for some reason.  If so, I'm not sure what JSON I could provide to match the signature and define the `try _bundle` function.

Again, the documentation needs to have a valid example.

**Comment by rix0rrr** [comment]
Try replacing:

```python
@jsii.implements(ILocalBundling)
class JinjaLocalBundling(ILocalBundling):
```

with

```python
@jsii.implements(ILocalBundling)
class JinjaLocalBundling:
```

?

**Comment by alexpulver** [comment]
@rix0rrr the `aws_s3_assets` [package overview documentation](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_s3_assets/README.html#asset-bundling) for Python generates the following signature for `try_bundle` method:
```python
def try_bundle(self, output_dir, *, image, entrypoint=None, command=None, volumes=None, environment=None, workingDirectory=None, user=None, local=None, outputType=None, securityOpt=None, network=None):
```

Per my test and TypeScript [documentation](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_s3_assets-readme.html#asset-bundling), it should be:
```python
def try_bundle(self, output_dir, options):
```

**Should I open a separate issue, or would you like to reopen this one?**

Full working example:
```python
import aws_cdk.aws_s3_assets as assets
import jsii
from aws_cdk import BundlingOptions, DockerImage, ILocalBundling

@jsii.implements(ILocalBundling)
class MyBundle:
    def try_bundle(self, output_dir, options):
        can_run_locally = True  # replace with actual logic
        if can_run_locally:
            # perform local bundling here
            return True
        return False

assets.Asset(
    self, "BundledAsset",
    path=str(pathlib.Path(__file__).parent.parent.joinpath("docs").resolve()),
    bundling=BundlingOptions(
        local=MyBundle(),
        # Docker bundling fallback
        image=DockerImage.from_registry("alpine"),
        entrypoint=["/bin/sh", "-c"],
        command=["bundle"]
    )
)
```
