### ISSUE TITLE
(appsync): 2.1.0 breaks deployment

### ISSUE THREAD

**Issue by Simon-TechForm** [aws/aws-cdk#17925]
### What is the problem?

After upgrading from 2.0.0 to 2.1.0 we are no longer able to deploy, receiving:
```TTL value cannot be smaller than 1 second and larger than 3600 seconds. (Service: AWSAppSync; Status Code: 400; Error Code: BadRequestException```

This seems to be caused by #17815, that introduces cachingConfig to appsync resolvers.

Despite the [Cloudformation documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appsync-resolver.html#cfn-appsync-resolver-cachingconfig) specifying both the `CachingConfig` and its two Properties `CachingKeys` & `Ttl` as optional, our tests show that when `CachingConfig` is set, `Ttl` must be as well.

Current state of v2.1.0:
Not specifying any `cachingConfig` fails.
Specifying a `cachingConfig` including only `cachingKeys` fails.
Specifying a `cachingConfig` including only `ttl` succeeds.
Specifying a `cachingConfig` with both `cachingKeys` and `ttl` succeeds.

So it seems like `ttl` cannot be optional, and we need to check if `cachingConfig` is passed before adding it to the cfnResolver at [line 117 in resolver.ts](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-appsync/lib/resolver.ts#L117)

@kylevillegas93 Are you able to look into this? I'm happy to help, but also quite busy until next year, and it would be nice to have a fix before then.

### Reproduction Steps

Deploy a stack with any appsync resolver, without specifying `cachingConfig`.

### What did you expect to happen?

Deployment to succeed without any errors.

### What actually happened?

Deployment fails with: `TTL value cannot be smaller than 1 second and larger than 3600 seconds. (Service: AWSAppSync; Status Code: 400; Error Code: BadRequestException`

### CDK CLI Version

2.1.0

### Framework Version

2.1.0

### Node.js Version

14.18.2

### OS

macOS 11.6.1

### Language

Typescript

**Comment by seanWLawrence** [comment]
Can confirm the same experience. I removed the `CachingConfig: {}` from my template and it deployed just fine. Related to: https://github.com/aws/aws-cdk/commit/52b535bda5f26b07377fcdfca63a75c62eb5f883

**Comment by otaviomacedo** [comment]
The PR linked above makes `cachingConfig` actually optional. 

The CloudFormation team has been notified about the mismatch in the specification.

**Comment by seanWLawrence** [comment]
> The PR linked above makes `cachingConfig` actually optional.
> 
> The CloudFormation team has been notified about the mismatch in the specification.

Ah, so the  `CachingConfig: {}` that's generated now by the construct is valid Cloudformation and the bug is with Cloudformation?

**Comment by otaviomacedo** [comment]
@seanWLawrence  `CachingConfig: {}` is valid according to the current CloudFormation spec. But the spec is incorrect and does not match the validation done by the AppSync control plane. Once CloudFormation fixes this bug, `CachingConfig: {}` will no longer be valid. Also, the `ttl` property will have to be made required in the CDK. So brace yourselves for another breaking change.

**Comment by bodokaiser** [comment]
What is the workaround for this?

**Comment by kylevillegas93** [comment]
My bad - happy to help if there are any other changes that need to be made but looks like they are all covered - just lemme know.

**Comment by manumaki** [comment]
2.2.0 has same issue

**Comment by Simon-TechForm** [comment]
> 2.2.0 has same issue

We just deployed successfully after upgrading from 2.0.0 to 2.2.0.

**Comment by manumaki** [comment]
OK our stack doesn't actually use Appsync. I'll try to figure out what's the problem and create separate issue :) We get the same error though.
