### ISSUE TITLE
(aws_ec2): No example for use of interface SubnetSelection for vpcSubnets

### ISSUE THREAD

**Issue by andrewjroth** [aws/aws-cdk#17933]
### link to reference doc page

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ec2.SubnetSelection.html

### Describe your issue?

The example given for `aws-cdk-lib » aws_ec2 » SubnetSelection` (**interface SubnetSelection**) on this page does not actually show _SubnetSelection_ anywhere.

A [search of the example code](https://github.com/aws-samples/aws-cdk-examples/search?l=TypeScript&q=SubnetSelection) has only one result in [neptune-with-vpc/neptune-with-vpc-stack.ts](https://github.com/aws-samples/aws-cdk-examples/blob/a887085be90e898d435024f80153bf59996ee3c7/typescript/neptune-with-vpc/neptune-with-vpc-stack.ts):

```typescript
const neptuneVpc = new ec2.Vpc(...)

var neptuneIsolatedSubnets = neptuneVpc.isolatedSubnets;

// Create Subnet group list to be used with Neptune.
const neptuneSubnets: ec2.SubnetSelection = { subnets: neptuneIsolatedSubnets };
```

Here is my attempt to replicate this:

```typescript
const vpc = ec2.Vpc.fromLookup(this, 'Vpc', {
  isDefault: true,
});
new ec2.Instance(this, 'Instance', {
  vpc,
  vpcSubnets: ec2.SubnetSelection = { subnets: vpc.publicSubnets },
});
```

This results in an error:

```
error TS2339: Property 'SubnetSelection' does not exist on type 'typeof import("./node_modules/aws-cdk-lib/aws-ec2/index")'.
```

The documentation needs to have a proper example.  How does one implement this?

Thank you!

**Comment by robertd** [comment]
```ts
new ec2.Instance(this, 'Instance', {
  vpc,
  vpcSubnets: {
    subnetType: SubnetType.PUBLIC,
  },
});
```

Not sure which IDE you're using, but `vscode` has a great intellisense feature.

![image](https://user-images.githubusercontent.com/31543/145668342-8220c85a-b302-4291-bd94-02b9f1362a13.png)

**Comment by andrewjroth** [comment]
That seems to work, thank you!
