### ISSUE TITLE
(aws-cdk-api-reference): v2 is not the latests

### ISSUE THREAD

**Issue by jonniedarko** [aws/aws-cdk#17932]
### link to reference doc page

https://docs.aws.amazon.com/cdk/api/versions.html

### Describe your issue?

the CDK site links to older version for `latest` version

This is confusing and leads to bad search results via google or similar

**Comment by tmokmss** [comment]
I guess this issue will also fix https://github.com/aws/aws-cdk/issues/17963

**Comment by corymhall** [comment]
@jonniedarko we've removed the `latest` version in favor of specific version tags (`v1` and `v2`)

https://docs.aws.amazon.com/cdk/api/versions.html
