### ISSUE TITLE
(cdk-integ-tool): make cdk-integ-tools accessible outside cdk

### ISSUE THREAD

**Issue by markussiebert** [aws/aws-cdk#17937]
### Description

I would like to test my own constructs the same way it's done in this repo. I like the way the cdk constructs are integration tested and like the cdk-integ-tool approach. It would be nice, to make this accessible outside this repo (or at least I was not able to install it or access it from the cdk packages).

### Use Case

I would like to structure my tests the same way as it's done inside this project for cdk constructs.

### Proposed Solution

no idea? maybe there is nothing to do, maybe some documentation, ...

### Other information

no

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by jumic** [comment]
Do you use projen to develop your own constructs? Projen already has a feature for implementing [integration snapshot tests](https://github.com/projen/projen/blob/main/docs/awscdk.md#integration-snapshot-tests) similar to CDK.

**Comment by markussiebert** [comment]
Thank you for your input. I will try this, as we are already using projen. But I think not every one wants to use projen (I still don't know today whether I like it or not). But this feature is already implemented here, and maybe it could be exposed...

**Comment by tim-finnigan** [comment]
Linking related RFC: https://github.com/aws/aws-cdk-rfcs/issues/31

**Comment by corymhall** [comment]
We've released two new tools as replacements

[integ-runner](https://www.npmjs.com/package/@aws-cdk/integ-runner)
and
[integ-tests](https://www.npmjs.com/package/@aws-cdk/integ-tests-alpha)
