### ISSUE TITLE
@aws-cdk/aws-rds: Expose DbiResourceId as part of the DbInstance property

### ISSUE THREAD

**Issue by tuladhp** [aws/aws-cdk#17946]
### Description

Currently the class Amazon.CDK.AWS.RDS.DatabaseInstance does not expose **DbiResourceId** which is needed for IAM authentication. However this property is available in AWS SDK api. 

It is needed for an IAM based database authentication where an IAM policy needs to provide this DbiResourceId as part of the IAM policy. This functionality would be very useful for several customers using RDS IAM authentication instead of writing your own custom resource policy

### Use Case

general use case for any RDS using IAM authetication

### Proposed Solution

Expose DbiResourceId as part of DBInstance class

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by skinny85** [comment]
Hey @tuladhp, thanks for opening the issue. We're tracking it here already: https://github.com/aws/aws-cdk/issues/11851, let's keep the conversation there.

Thanks,
Adam
