### ISSUE TITLE
(RDS Database Instance): Getting error when creating RDS instance with "Error: There are no subnet groups with name 'foobar' in this VPC."

### ISSUE THREAD

**Issue by romelBen** [aws/aws-cdk#17951]
### General Issue

I have referenced StackOverflow but to nothing has helped.

### The Question

Hello everyone. I am having issues in creating an RDS Instance and I am baffled as to why RDS is not recognizing my subnet group when I create it in the service and separately. Here is my code to get a better idea:

```
    // Import VPC to be used.
    let mainVPC = ec2.Vpc.fromVpcAttributes(this, "InfraJumpVPC", {
      vpcId: props.vpcId,
      availabilityZones: ["us-east-1a", "us-east-1b", "us-east-1c"],
    });

    // Private subnet 1c
    const privateSubnet1C = new ec2.CfnSubnet(this, 'foobar', {
      availabilityZone: props.availabilityZones[2],
      cidrBlock: props.cidr + '.3.3/28',
      vpcId: props.vpcId,
      tags: [{
        key: 'Name',
        value: props.availabilityZones[2] + "." + "private" + '.' + "foo" + "." + "bar" + "." + 'dev'
        }]
    });

    // Subnet Group creation for PostgreSQL RDS
    const foobarDBSubnetGroup = new rds.CfnDBSubnetGroup(this, "foobar", {
      dbSubnetGroupDescription: "foo Postgres DB",
      subnetIds: [privateSubnet1A.ref,privateSubnet1B.ref,privateSubnet1C.ref],
      dbSubnetGroupName: "foobar"
    })

    // Creates postgreSQL RDS instance for foobar use:
    const foobarDBInstance = new rds.DatabaseInstance(this, "foobarDBInstance", {
      vpc: mainVPC,
      vpcSubnets: {
        subnetGroupName: "foobar", // Error lies here
      },
      engine: rds.DatabaseInstanceEngine.postgres({
        version: rds.PostgresEngineVersion.VER_13_4,
      }),
      instanceType: ec2.InstanceType.of(
        ec2.InstanceClass.BURSTABLE3,
        ec2.InstanceSize.SMALL,
      ),
      credentials: rds.Credentials.fromGeneratedSecret('postgres'),
      securityGroups: [dbSG],
      multiAz: false,
      allocatedStorage: 100,
      maxAllocatedStorage: 1000,
      allowMajorVersionUpgrade: false,
      autoMinorVersionUpgrade: true,
      backupRetention: cdk.Duration.days(0),
      deleteAutomatedBackups: true,
      removalPolicy: cdk.RemovalPolicy.DESTROY,
      deletionProtection: false,
      databaseName: "gitlab_db_" + props.envStage,
      publiclyAccessible: false,
    });
```

I always have issues when I import a VPC over but pretty much what I wanted to do is import my VPC, create a private subnet, then use those subnets and attach them to a DB Subnet Group. Finally, I would reference it in the `rds.databaseinstance` module but does not work. Is there a simplier way of doing this, or am I missing something here? I would greatly appreciate any help. Been wracking my head over this for some time.

### CDK CLI Version

1.127.0

### Language

Typescript

### Language Version

4.2.3

**Comment by peterwoodworth** [comment]
I believe the reason for this is the same as in [this issue](https://github.com/aws/aws-cdk/issues/17883#issuecomment-990397226). You're creating the resources you need in your Vpc, but the Vpc object in your code will not recognize that the Subnet or SubnetGroup you've created belongs to it. 

To get around this, you can declare the Subnet and SubnetGroup in the Vpc stack (or another stack that you deploy before this stack), so when you import the Vpc in this stack it will have the proper context. (found in `cdk.context.json`)

**Comment by romelBen** [comment]
So would I have to create the DB Subnet Group manually? The VPC stack that I am referencing too does not have an AWS CDK/CloudFormation stack to update on my side which is a bummer. I would really like this to be straight forward using AWS CDK but this is understandable. Let me try this this out @peterwoodworth.

**Comment by peterwoodworth** [comment]
It doesn't have to be manually @romelBen, you could create the Subnet and SubnetGroup in one stack, then create the instance and import the vpc in another stack.

**Comment by romelBen** [comment]
Hmmm, let me check this out @peterwoodworth. Will contact you back on the fix.

**Comment by peterwoodworth** [comment]
Oh and a piece of advice - before you deploy the dbinstance stack, make sure your context is up to date: https://docs.aws.amazon.com/cdk/latest/guide/context.html#context_viewing

If you already have the `cdk.context.json` file because of your imported VPC, the CDK won't try to look up the VPC again.

**Comment by romelBen** [comment]
@peterwoodworth Ok Peter I contemplated your advice and referenced the VPC again. This successfully built and is working! Here is the code I added/modified:

    let dataVPC = ec2.Vpc.fromVpcAttributes(this, "ImportDataVPC", {
      vpcId: props.vpcId,
      availabilityZones: ["us-east-1a", "us-east-1b", "us-east-1c"],
      privateSubnetIds: [privateSubnet1A.ref,privateSubnet1B.ref,privateSubnet1C.ref]
    });

    // Creates postgreSQL RDS instance for foobar use:
    const foobarDBInstance = new rds.DatabaseInstance(this, "foobarDBInstance", {
      vpc: dataVPC, // Changed mainVPC to dataVPC which incorporates the private subnets from above
      vpcSubnets: {
        availabilityZones: props.availabilityZones,
        subnetType: ec2.SubnetType.PRIVATE_WITH_NAT //
      },
      engine: rds.DatabaseInstanceEngine.postgres({
        version: rds.PostgresEngineVersion.VER_13_4,
      }),
      instanceType: ec2.InstanceType.of(
        ec2.InstanceClass.BURSTABLE3,
        ec2.InstanceSize.SMALL,
      ),
      credentials: rds.Credentials.fromGeneratedSecret('postgres'),
      securityGroups: [dbSG],
      multiAz: false,
      allocatedStorage: 100,
      maxAllocatedStorage: 1000,
      allowMajorVersionUpgrade: false,
      autoMinorVersionUpgrade: true,
      backupRetention: cdk.Duration.days(0),
      deleteAutomatedBackups: true,
      removalPolicy: cdk.RemovalPolicy.DESTROY,
      deletionProtection: false,
      databaseName: "foobar" + props.envStage,
      publiclyAccessible: false,
    });

**Comment by peterwoodworth** [comment]
Glad to hear it! Feel free to ping me if you have any more questions
