### ISSUE TITLE
Cleanse output of `cdk doctor` from known/probable credentials

### ISSUE THREAD

**Issue by RomainMuller** [aws/aws-cdk#1795]
The output of `cdk doctor` will list all environment variables with a name starting with `AWS_` as those might influence the workings of the application.

We need to redact the values for the environment variables known to be used for credentials, as well as probably any environment variable name that looks passwords-y (contains "password", or "pass", or "passwd", for example).

**Comment by shivlaks** [comment]
#2357 redacted the AWS_ACCESS_KEY.

Still outstanding: 
* redacting keys that have a name which might be secrets-ish
