### ISSUE TITLE
(applicationautoscaling): AWS CDK Autoscaling Feature Update : TargetTrackingScaling Policy Fails on CDK update

### ISSUE THREAD

**Issue by aritranagnordcloud** [aws/aws-cdk#17956]
### General Issue

Autoscaling Feature Update : TargetTrackingScaling Policy Fails on CDK update

### The Question

We have CDK code which generates the CF code for creating new autoscaling target policy for an ECS cluster.
Here is the code written in java 
```java
        new TargetTrackingScalingPolicy(this, "TargetTrackingScalingPolicy", TargetTrackingScalingPolicyProps.builder()
        .scalingTarget(iScalableTarget)
        .targetValue(stackProps.getAutoScalingTargetValue())
        .policyName("policy/".concat(service.getServiceName()).concat("/autoscaling").concat(CdkUtils.generateRandomString(3)))
        .predefinedMetric(PredefinedMetric.ECS_SERVICE_AVERAGE_CPU_UTILIZATION)
        .scaleInCooldown(Duration.seconds(10))
        .scaleOutCooldown(Duration.seconds(10))
        .build());
}
```

While initiating the code for the first time and running the CF command , it works absolutely fine.
However, if we try to update the stack without any  changes in the code as well. it fails.
The error which generates results in the role back of the stack.
**Only one TargetTrackingScaling policy for a given metric specification is allowed**

Please help us in fixing this issue by providing any relevant solution for this.
Is there any way we can check the autoscaling present for the component.

### CDK CLI Version

1.134.0 

### OS

mac

### Language

Java

### Language Version

Java (8)

**Comment by aritranagnordcloud** [comment]
Here is the error which gets generated on the CDK update : Only one TargetTrackingScaling policy for a given metric specification is allowed. (Service: AWSApplicationAutoScaling; Status Code: 400; Error Code: ValidationException; Request ID: b5d49413-09ae-4e15-b719-4b46709c0825; Proxy: null)

**Comment by peterwoodworth** [comment]
What resource is the stack attempting to create/modify when this error occurs?

Can you check the `cdk diff` output to make sure you haven't made any changes to your resource?

**Comment by aritranagnordcloud** [comment]
This is happening when we try to update the existing stack with no visible changes. 
` new TargetTrackingScalingPolicy(this, "TargetTrackingScalingPolicy", TargetTrackingScalingPolicyProps.builder()
        .scalingTarget(iScalableTarget)
        .targetValue(stackProps.getAutoScalingTargetValue())
        .policyName("policy/".concat(service.getServiceName()).concat("/autoscaling").concat(CdkUtils.generateRandomString(3)))
        .predefinedMetric(PredefinedMetric.ECS_SERVICE_AVERAGE_CPU_UTILIZATION)
        .scaleInCooldown(Duration.seconds(10))
        .scaleOutCooldown(Duration.seconds(10))
        .build());
}`

This above code snippet is showing error whenever the whole stack is trying to update.
In the Cloudformation console, it suggests that "Requested update requires the creation of a new physical resource; hence creating one."
While creating the stack the first time, it works absolutely fine. But when updating it from the code. it fails to update the stack.

Also, while doing cdk diff. it shows the list of all the resources that was created and trying to modify them.

**Comment by aritranagnordcloud** [comment]
This issue is similar one described in the following : https://www.reddit.com/r/aws/comments/on8eec/investigating_stack_drift_issue_in_cdk_with_cdk/

**Comment by aritranagnordcloud** [comment]
Even changing the Autoscaling code as the following does not work 
`        ScalableTaskCount scaling = service.autoScaleTaskCount(EnableScalingProps.builder()
        .maxCapacity(stackProps.getMaxContainer())
        .minCapacity(stackProps.getMinContainer()).build());
        
        scaling.scaleOnCpuUtilization("CPUSScaling", CpuUtilizationScalingProps.builder()
        .policyName("policy/".concat(service.getServiceName()).concat("/autoscaling").concat(CdkUtils.generateRandomString(3)))
        .scaleInCooldown(Duration.seconds(10))
        .scaleOutCooldown(Duration.seconds(10))
        .targetUtilizationPercent(stackProps.getAutoScalingTargetValue())
        .build());
`

**Comment by peterwoodworth** [comment]
> Also, while doing cdk diff. it shows the list of all the resources that was created and trying to modify them.

By "all the resources" do you mean your entire stack?

**Comment by aritranagnordcloud** [comment]
We have an existing CF code which needs to be translated to CDK code.


`  AutoScalingTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MinCapacity: !Ref MinContainers
      MaxCapacity: !Ref MaxContainers
      ResourceId: !Join ['/', [service, !ImportValue {'Fn::Sub': '${ExampleStack}-ECSCluster'}, !GetAtt AppServiceDefinition.Name]]
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs
      # "The Amazon Resource Name (ARN) of an AWS Identity and Access Management (IAM) role that allows Application Auto Scaling to modify your scalable target."
      RoleARN: !GetAtt AutoScalingRole.Arn

  AutoScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: !Join ['', [!Ref Service, AutoScalingPolicy]]
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref AutoScalingTarget
      TargetTrackingScalingPolicyConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageCPUUtilization
        ScaleInCooldown: 10
        ScaleOutCooldown: 10
        # Keep things at or lower than 50% CPU utilization, for example
        TargetValue: !Ref AutoScalingTargetValue
`


How do we convert this to CDK and ensure the CDK is able to recognise even if we don't update the Autoscaling policy it won't try to recreate them.

**Comment by aritranagnordcloud** [comment]
> > Also, while doing cdk diff. it shows the list of all the resources that was created and trying to modify them.
> 
> By "all the resources" do you mean your entire stack?

Yes all the resources it seems to be getting updated

**Comment by peterwoodworth** [comment]
Ah I see, the issue is with importing a CloudFormation stack to CDK.

We have a helpful guide on the topic written by our very own Adam. https://aws.amazon.com/blogs/developer/migrating-cloudformation-templates-to-the-aws-cloud-development-kit/

We also have a docs page on the topic: https://docs.aws.amazon.com/cdk/latest/guide/use_cfn_template.html

Be sure to give these a read; They should help you migrate your resources to CDK without making any changes to your resources.

**Comment by aritranagnordcloud** [comment]
Thanks Peter, I will definitely go through the document. I feel if we cannot resolve the above issue programmatically this is the only option.

But i also had a doubt on creating the autoscaling policies on ECS Service. For the target tracking policy , if we generate the CDK code and perform CDK deploy.  It creates a Scalable Target and also a Scaling Policy. However, on updating the same stack without many any changes (simply running cdk diff and cdk deploy) breaks the CF stack(saying update impossible) citing the above command. Do we have any provision in CDK to identify stack drifts and skip the update specially for these autoscaling policies and targets( DynamoDB , ECS ) etc.

**Comment by aritranagnordcloud** [comment]
I checked the code again and it seems there was a bug in the implementation. As part of generating a new log group every time the CDK code has added a unique string generator which was changing the whole behaviour. Removing the same fixed the problem 🗡️  

Thanks for the help and sharing the documentation
