### ISSUE TITLE
(aws-s3-deployment): lambda function timeouted with huge bucket.

### ISSUE THREAD

**Issue by from20020516** [aws/aws-cdk#17979]
### What is the problem?

- CloudFormation stack status never change from `UPDATE_IN_PROGRESS` when deploying.

### Reproduction Steps

- Reproduce only with a huge bucket. (in my case, 10TB+/10million+ objects exists.)

```ts
import { Construct } from 'constructs'
import {
  aws_s3 as s3,
  aws_s3_deployment as s3d,
} from 'aws-cdk-lib'
import * as path from 'path'

...
    const bucket = new s3.Bucket(this, 'Bucket', {
      autoDeleteObjects: false,
      versioned: true
    })

    // try to add.
    new s3d.BucketDeployment(this, 'BucketDeployment', {
      sources: [s3d.Source.asset(path.join(__dirname, 's3'))], // 2 small json files.
      destinationBucket: bucket,
      prune: false,
      memoryLimit: 10240, // max limit
    })
```

### What did you expect to happen?

- complete deployment with `UPDATE_COMPLETE` CloudFormation stack status.

### What actually happened?

- stack status never change from `UPDATE_IN_PROGRESS`.

```sh
FluctAnalyticsStack: creating CloudFormation changeset...
[█████████████████████▊····································] (6/16)

7:55:55 AM | UPDATE_IN_PROGRESS   | AWS::CloudFormation::Stack                  | FluctAnalyticsStack
7:57:27 AM | CREATE_IN_PROGRESS   | Custom::CDKBucketDeployment                 | BucketDeployment/C...e-10240MiB/Default
```

- looks like `CustomCDKBucketDeployment` lambda function exec timeouted.

`/aws/lambda/FluctAnalyticsStack-CustomCDKBucketDeployment8693B-0odU1sUBEgZF`

> REPORT RequestId: 0162fe3f-70f8-42e9-82c8-9eaf29bf1288	Duration: 900102.09 ms	Billed Duration: 900000 ms	Memory Size: 10240 MB	Max Memory Used: 169 MB	Init Duration: 669.32 ms	

![image](https://user-images.githubusercontent.com/26649687/145775512-3d06af24-9d90-4980-bfa2-6ca4b6230972.png)

### CDK CLI Version

2.1.0

### Framework Version

2.1.0

### Node.js Version

14.18.0

### OS

macOS

### Language

Typescript

**Comment by peterwoodworth** [comment]
Thanks for taking the time to report this @from20020516 

This is a known limitation - closing in favor of https://github.com/aws/aws-cdk/issues/7950
