### ISSUE TITLE
(aws-iot): CfnProvisioningTemplate Template with name already exists

### ISSUE THREAD

**Issue by anjum-ali** [aws/aws-cdk#17989]
### What is the problem?

npm package version : 1.132.0 & 1.135.0 (tried with these two)

when creating a iot Provisioning Template using cdk, the following error is thrown:

```
Template with name provisioningtemplate_JAoF84L77Jaf already exists (Service: Iot, Status Code: 409, Request ID: 60a18fc4-8778-4f73-b5d2-9589e37f3d43, Extended Request ID: null)` 
```

**N.B.** it does not matter if we provide a template name or let cdk choose a name as seen above
**N.B.**  the stack is being newly created and so there is NO provisioning template existing whatsoever

### Reproduction Steps

use similar code as:

```ts
import * as iam from '@aws-cdk/aws-iam';
import * as iot from '@aws-cdk/aws-iot';

    const provisioningRole = new iam.Role(this, 'provisioning-role-arn', {
      assumedBy       : new iam.ServicePrincipal('iot.amazonaws.com'),
      description     : 'Role assumed by provisioning template to bulk provision devices by claim',
      roleName        : `ProvisioningByClaimRole`,
      managedPolicies : [iam.ManagedPolicy.fromAwsManagedPolicyName('service-role/AWSIoTThingsRegistration')],
    });

    const provisioningTemplate = new iot.CfnProvisioningTemplate(this, 'provisioning-template', {
      provisioningRoleArn : provisioningRole.roleArn,
      templateBody        : JSON.stringify(provisioningTemplateBody),
      description         : 'provision by claim template for guard devices that use certificates for authentication',
      enabled             : false,
      preProvisioningHook : {
        targetArn      : preProvisioningHookLambda.functionArn,
        payloadVersion : '2020-04-01',
      },
    });
```

can ignore the preprovisioning hook lambda and template if needed

### What did you expect to happen?

since the current stack is the one initiating the creation of the provisioning template, then it should create the template resource without error

### What actually happened?

the stack ACTUALLY  creates the iot provisioning template resource completely but then throws the name conflict error and fails. Meaning after the stack completes the rollback, there is the new provisioning templete resource in iot.

### CDK CLI Version

1.135.0

### Node.js Version

14.18.1

### OS

macOS Big Sur 11.6.1

### Language

Typescript

### Language Version

4.3.2

**Comment by skinny85** [comment]
Hey @anjum-ali,

thanks for opening the issue. Can you explain exactly what are you doing to get this error?

Thanks,
Adam

**Comment by anjum-ali** [comment]
Hi @skinny85 ,
I am trying to create an aws IoT Provisioning Template resource. As far as i can tell, I am not doing anything specific, a 1000ft view of what I did would be:
1. Define in cdk a lambda which would be the pre provisioning hook
2. Define in cdk a role to be assigned to provisioning template 
3. Define in cdk a provisioning template resource, use the role and lambda arn in the definition

that is about it. when running cdk deploy, the process fails while creating the Provisioning Template resource with the above mentioned error. As noted previously, if we provide a specific name or let cdk choose a name for the template, the result is the same.
There is not error in the template body either, and actually the template is successfully created in the background too. Just that the cdk process fails and rolls back the stack.

let me know if I have answered your question.

Best
Anjum

**Comment by skinny85** [comment]
@anjum-ali would you mind showing your `provisioningTemplateBody`? I want to reproduce the issue, but I'm having trouble getting a correct template body through the service validation.

**Comment by anjum-ali** [comment]
@skinny85 
sure.
here is the template body
`
const provisioningTemplateBody = {
      Parameters : {
        SerialNumber : {
          Type : 'String'
        },
        ApplianceId : {
          Type : 'String'
        },
        ThingGroups : {
          Type : 'String'
        },
        ThingName : {
          Type : 'String'
        },
        ThingTypeName : {
          Type : 'String'
        },
        BillingGroup : {
          Type : 'String'
        },
        'AWS::IoT::Certificate::Id' : {
          Type : 'String'
        }
      },
      Resources : {
        certificate : {
          Properties : {
            CertificateId : {
              Ref : 'AWS::IoT::Certificate::Id'
            },
            Status : 'ACTIVE'
          },
          Type : 'AWS::IoT::Certificate'
        },
        policy : {
          Properties : {
            PolicyName : fleetIoTPolicy.policyName
          },
          Type : 'AWS::IoT::Policy'
        },
        thing : {
          OverrideSettings : {
            AttributePayload : 'MERGE',
            ThingGroups      : 'REPLACE',
            ThingName        : 'REPLACE',
            ThingTypeName    : 'REPLACE',
            BillingGroup     : 'REPLACE'
          },
          Properties : {
            AttributePayload : {
              version       : 'v1',
              serial_number : { Ref: 'SerialNumber' }
            },
            ThingGroups   : [{ Ref: 'ThingGroups' }],
            ThingName     : { Ref: 'ApplianceId' },
            ThingTypeName : { Ref: 'ThingTypeName' },
            BillingGroup  : { Ref: 'BillingGroup' }
          },
          Type : 'AWS::IoT::Thing'
        }
      }
    }
`
the `fleetIoTPolicy` is an instance of CfnPolicy

**Comment by skinny85** [comment]
Hey @anjum-ali,

this `cdk deploy`s for me without any errors:

```ts
        const provisioningRole = new iam.Role(this, 'provisioning-role-arn', {
            assumedBy       : new iam.ServicePrincipal('iot.amazonaws.com'),
            description     : 'Role assumed by provisioning template to bulk provision devices by claim',
            roleName        : `ProvisioningByClaimRole`,
            managedPolicies : [iam.ManagedPolicy.fromAwsManagedPolicyName('service-role/AWSIoTThingsRegistration')],
        });

        const provisioningTemplate = new iot.CfnProvisioningTemplate(this, 'provisioning-template', {
            provisioningRoleArn: provisioningRole.roleArn,
            templateBody: JSON.stringify({
                Parameters: {
                    'AWS::IoT::Certificate::Id': {
                        Type: 'String',
                    },
                },
                Resources: {
                    certificate: {
                        Properties: {
                            CertificateId: {
                                Ref: 'AWS::IoT::Certificate::Id',
                            },
                            Status: 'ACTIVE',
                        },
                        Type: 'AWS::IoT::Certificate',
                    },
                },
            }),
            description: 'provision by claim template for guard devices that use certificates for authentication',
            enabled: false,
        });
```

Can you try locally yourself, and see what happens when you `cdk deploy` this code?

Thanks,
Adam

**Comment by anjum-ali** [comment]
@skinny85 
I am at a loss for words. I can't reproduce the issue either. Tried various combinations of template Props and all is green now.

Thanks
Anjum

**Comment by skinny85** [comment]
No worries @anjum-ali, glad you're unblocked! 🙂

I'm resolving this one, let us know if you need anything else from our side for this issue.
