### ISSUE TITLE
Add Go to AWS CDK Reference Documentation

### ISSUE THREAD

**Issue by MrArnoldPalmer** [aws/aws-cdk#17999]
### link to reference doc page

https://docs.aws.amazon.com/cdk/api/latest/docs/aws-construct-library.html

### Describe your issue?

Add links to relevant pages on pkg.go.dev for constructs on the cdk api reference documentation.

**Comment by RomainMuller** [comment]
We now have documentation linking to `pkg.go.dev` for `aws-cdk-lib`. It looks like the best we can do for now.
