### ISSUE TITLE
`yarn cdk destroy` does not complain or warn when the stack name doesn't match an existing stack

### ISSUE THREAD

**Issue by alexandervandekleutab** [aws/aws-cdk#17991]
### What is the problem?

If you do `yarn cdk destroy` and the stack name doesn't match a stack that has been deployed, it tells you that it successfully deleted the stack.

### Reproduction Steps

Deploy a stack. Change its name. Delete the stack via `yarn cdk destroy`.

### What did you expect to happen?

Complain that the stack was not found.

### What actually happened?

Stack claims to have been deleted.

### CDK CLI Version

1.124

### Node.js Version

14

### OS

MacOS Big Sur

### Language

Typescript

**Comment by peterwoodworth** [comment]
What exactly do you mean by "stack claims to have been deleted"? This is my output:

```
yarn run v1.22.10
warning package.json: No license field
$ cdk destroy agsdg
Are you sure you want to delete:  (y/n)? y
✨  Done in 7.80s.
```

Contrast this to a successful `yarn cdk destroy` command:
```
yarn run v1.22.10
warning package.json: No license field
$ cdk destroy
Are you sure you want to delete: GeneralStack (y/n)? y
GeneralStack: destroying...
 ✅  GeneralStack: destroyed
✨  Done in 31.77s.
```

If this is the same thing you're seeing, I can see a feature request here for throwing an error when a stack with the specified name (or any stack at all) isn't found when calling `cdk destroy`.
