### ISSUE TITLE
(aws-s3): Lifecycle rules: "Number of newer versions to retain" option missing from CDK

### ISSUE THREAD

**Issue by ffxsam** [aws/aws-cdk#17996]
### Description

I noticed today that this option is missing from the lifecycle rule options.

![CleanShot 2021-12-13 at 16 10 43](https://user-images.githubusercontent.com/12532733/145898144-66d4dc00-90dd-41f8-a715-58df3a08b878.png)

### Use Case

It exists in the AWS Console, so it should be covered by CDK.

### Proposed Solution

N/A

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by RigoIce** [comment]
+1 
Bothered me as well and I was searching intensely whether it might be a different construct or so. But it is just missing. The bucket's noncurrentVersionTransitionProperty already covers this and CloudFormation as well. Would make me happy to have this in CDK very soon. 

By the way, I was always keen on stepping into contributing to the CDK development but was always a bit daunted by the complexity CDK already has. So, this issue sounds rather 'easy' and probably someone of the team could give me some guidance whether this issue could be a good starting point.

**Comment by otaviomacedo** [comment]
@RigoIce we welcome community contributions! You can get started by reading our [contributing] guide.

[contributing]: https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md

**Comment by RigoIce** [comment]
Thx @otaviomacedo, I'll have a look to the guide asap.

**Comment by ffxsam** [comment]
> By the way, I was always keen on stepping into contributing to the CDK development but was always a bit daunted by the complexity CDK already has. So, this issue sounds rather 'easy' and probably someone of the team could give me some guidance whether this issue could be a good starting point. 

While I think it's up to each person to decide if they want to contribute, the bottom line is that AWS is a paid service, and we as paying customers expect AWS to maintain and keep their tools up to date. This is not the same as a free, open source tool that's maintained by the public. It's a commercial tool.

It's great that there are people who want to help develop AWS tools in their free time, but many of us are too busy to do so. I think it would be a cool idea if AWS offered credits to customers who make significant contributions to their tooling.

**Comment by RigoIce** [comment]
> > By the way, I was always keen on stepping into contributing to the CDK development but was always a bit daunted by the complexity CDK already has. So, this issue sounds rather 'easy' and probably someone of the team could give me some guidance whether this issue could be a good starting point. 
> 
> While I think it's up to each person to decide if they want to contribute, the bottom line is that AWS is a paid service, and we as paying customers expect AWS to maintain and keep their tools up to date. This is not the same as a free, open source tool that's maintained by the public. It's a commercial tool.
> 
> It's great that there are people who want to help develop AWS tools in their free time, but many of us are too busy to do so. I think it would be a cool idea if AWS offered credits to customers who make significant contributions to their tooling.

I think CDK needs to be distinguished from AWS. We pay for AWS and not for CDK. There are alternatives like Terraform or Serverless with the business model you described. And the full fledged versions are somehow rather expensive - especially if you are not deploying at different providers. But you could also use frameworks like troposphere in Python or write directly CloudFormation templates (which is a pain). 

Having the open-source CDK driven by AWS makes my life easier and the viable community makes it to a living framework. I discovered a major bug in a release some time in the past and it was fixed over night! A complete contrast to some proprietary frameworks where I reported a bug and after a year, nothing happened. 

As always, I think there is light and shadow. And for sure I'd love to earn credits while contributing. But in fact, I fixed your issue as it was important for me as well. And so, we will have that fixed quite soon. For me it was fun and there is no obligation to contribute. 

What makes this strong development  community so exceptional is the developers reporting, the developers contributing and the AWS developers with all their insights. I'm pretty sure this mixture is absolutely powerful and worth supporting - no matter whether with reports or ideas or with contributions.

**Comment by ffxsam** [comment]
I totally get where you're coming from. And yes, it's nice that sometimes the community can quickly fix or add something and it helps everyone!

I think engineers just need to be careful about helping to set a precedent where huge companies with billions of dollars start outsourcing their development to the general public, at no cost to them. Does it really make sense for a company paying AWS $5,000/mo to also contribute their time to fix AWS's tools? I don't think so, no. Again, it's great if some developers have the time to fix and improve these tools, but some of us are running a business and have to dedicate 99% of our time to that. I have no problem taking a few hours to open a PR for a truly free & open-source tool, but the line becomes a bit blurry when you're performing work for free for a commercial platform. It's an ethical conundrum for me, personally. Would I attempt to fix something I needed urgently? Most likely, yeah - especially since it helps me and it helps other people.

The only part I disagree with you about is the idea of CDK being separate from AWS. I don't think it is, as evidenced by AWS Business Support having CDK as an option in their support choices (see below). At that point, they're effectively acknowledging that CDK is indeed an AWS service that they provide and support. Not to mention all the [help docs](https://docs.aws.amazon.com/cdk/v2/guide/home.html) they've written!

Anyway, this is more of a philosophical/ethical discussion, and I realize developers are divided in their opinion on this. 🙂 I appreciate the fix, @RigoIce!

<img width="666" alt="CleanShot 2021-12-30 at 13 32 59" src="https://user-images.githubusercontent.com/12532733/147782916-7860c3cc-3ef4-4e6e-a6a5-5c8563bc3d2a.png">
