### ISSUE TITLE
(@aws-cdk/aws-apigatewayv2): using an aws-apigatewayv2 as shared resource does not add any route

### ISSUE THREAD

**Issue by fbrv** [aws/aws-cdk#18006]
### What is the problem?

I have the following scenario: two stacks with shared resources (one with a vpc and the other one with an HttpApi coming from `@aws-cdk/aws-apigatewayv2`) and N stacks containing lambda functions. I want that the lambda functions use the resources inside the shared stacks (already created running the command `cdk deploy VpcStack ApiGatewayStack`). For the vpc there is no problem but for the api-gateway the `cdk deploy ALambdaStack` does not update the api-gateway route nor add any trigger to it. To add the route I need to rerun the `cdk deploy ApiGatewayStack`

### Reproduction Steps

VpcStack
```
import * as cdk from "@aws-cdk/core";
import * as ec2 from "@aws-cdk/aws-ec2";

export class VpcStack extends cdk.Stack {
  public readonly vpc: ec2.Vpc;
  constructor(scope: cdk.App, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    // assign a VPC to the class property SharedInfraStack
    this.vpc = new ec2.Vpc(this, 'my-vpc', {
      cidr: '10.0.0.0/16',
      natGateways: 1,
      maxAzs: 3,
      subnetConfiguration: [
        {
          name: 'private-subnet-1',
          subnetType: ec2.SubnetType.PRIVATE_WITH_NAT,
          cidrMask: 20,
        },
        {
          name: 'public-subnet-1',
          subnetType: ec2.SubnetType.PUBLIC,
          cidrMask: 20,
        },
        {
          name: 'isolated-subnet-1',
          subnetType: ec2.SubnetType.PRIVATE_ISOLATED,
          cidrMask: 20,
        },
      ],
    });
    
  }
}
```
ApiGatewayStack
```
import {CorsHttpMethod, HttpApi } from '@aws-cdk/aws-apigatewayv2';
import * as cdk from '@aws-cdk/core';

export class ApiGatewayStack extends cdk.Stack {
  public apigw: HttpApi;

  constructor(scope: cdk.App, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    this.apigw = new HttpApi(this, 'my-http-api', {
      corsPreflight: {
        allowHeaders: [
          'Content-Type',
          'X-Amz-Date',
          'Authorization',
          'X-Api-Key',
        ],
        allowMethods: [
          CorsHttpMethod.OPTIONS,
          CorsHttpMethod.GET,
          CorsHttpMethod.POST,
          CorsHttpMethod.PUT,
          CorsHttpMethod.PATCH,
          CorsHttpMethod.DELETE,
        ],
        allowCredentials: true,
        allowOrigins: [
          'https://example.com:3000',
      ],
      },
    });

    new cdk.CfnOutput(this, 'apiUrl', {
      value: this.apigw.url!,
    });

  }
}
```
StackProps interface 
```
import * as cdk from '@aws-cdk/core';
import * as ec2 from "@aws-cdk/aws-ec2";
import { HttpApi } from '@aws-cdk/aws-apigatewayv2';

export interface FunctionProps extends cdk.StackProps {
    vpc: ec2.Vpc;
    apigw: HttpApi;
}
```
Example of LambdaStack
```
import {HttpMethod} from '@aws-cdk/aws-apigatewayv2';
import {LambdaProxyIntegration} from '@aws-cdk/aws-apigatewayv2-integrations';
import * as lambda from '@aws-cdk/aws-lambda';
import * as cdk from '@aws-cdk/core';
import * as ec2 from "@aws-cdk/aws-ec2";
import * as path from 'path';

import {FunctionProps} from './props';


export class UserStack extends cdk.Stack {
  constructor(scope: cdk.App, id: string, props?: FunctionProps) {
    super(scope, id, props);

    const whoAmILambda = new lambda.Function(this, 'who-am-i', {
        runtime: lambda.Runtime.NODEJS_14_X,
        handler: 'index.main',
        code: lambda.Code.fromAsset(path.join(__dirname, 'path/to/function')),
        vpc: props?.vpc,
        vpcSubnets: {
            subnetType: ec2.SubnetType.PRIVATE_ISOLATED,
        }
      });
      props?.apigw.addRoutes({
        path: '/whoami',
        methods: [HttpMethod.GET],
        integration: new LambdaProxyIntegration({
          handler: whoAmILambda,
        }),
      });
  }
}
```
main.ts
```
import * as cdk from "@aws-cdk/core";
import { ApiGatewayStack } from "./src/api-gateway/api-gateway";
import { UserStack } from "./src/functions/user";
import { VpcStack } from "./src/vpc/vpc-stack";

const env = {
    account: process.env.ACCOUNT_NUMBER,
    region: process.env.AWS_REGION
}
const app = new cdk.App();

const vpcStack = new VpcStack(app, 'VpcStack', {env});
const apigwStack = new ApiGatewayStack(app, 'ApiGatewayStack', {env});

new UserStack(app, 'UserStack', {
    env,
    vpc: vpcStack.vpc,
    apigw: apigwStack.apigw,
})
```
Command to deploy the shared resources and the UserStack (in order):
```
cdk deploy VpcStack
cdk deploy ApiGatewayStack
cdk deploy UserStack
```

### What did you expect to happen?

I'm expecting that the shared resources are created and then the stack that uses the shared resources creates the entry in the api-gateway previously created.  

### What actually happened?

The shared resources are created as expected, the lambda function is also configured in the proper vpc using the proper set of subnets but no entry is added in the api-gateway, I double-checked using also the dashboard console but nothing is added.  
To add a new entry in the api-gateway I need to rerun the command ```cdk deploy ApiGatewayStack``` increasing the continuos deployment time

### CDK CLI Version

2.1.0 (build f4f18b1)

### Framework Version

1.134.0

### Node.js Version

v14.17.0

### OS

macos 

### Language

Typescript

### Language Version

Typescript

**Comment by Dreamescaper** [comment]
You can use HttpRoute construct for this purpose, I've mentioned it here:
https://github.com/aws/aws-cdk/issues/12337#issuecomment-991092668

**Comment by otaviomacedo** [comment]
Hi, @fbrv. That's just how CloudFormation works. If you run `cdk synth`, you'll see that the template for `ApiGatewayStack` has been changed to include the new route. But until you deploy that template, CloudFormation will hold on to the version of the template that was last deployed.

Taking a step back, is there a strong reason to keep each lambda function in its own stack rather than having a single stack with the HTTP API + all functions?
