### ISSUE TITLE
core: unable to import Stack

### ISSUE THREAD

**Issue by jeromevdl** [aws/aws-cdk#18010]
### What is the problem?

I have a similar problem to issue #17950 with Python. When migrating to cdk 2.0.0/2.1.0

Tried with:

```
from aws_cdk import Stack

class MyStack(Stack):
```

Got `ImportError: cannot import name 'Stack' from 'aws_cdk' (unknown location)`

Also tried with:

```
import aws_cdk as core

class MyStack(core.Stack):
```

Got `AttributeError: module 'aws_cdk' has no attribute 'Stack'`

(using python 3.8.9, cdk 2.1.0)

### Reproduction Steps

Add `aws-cdk-lib==2.1.0` in requirements.txt

Try to import Stack from core

### What did you expect to happen?

The import should work...

### What actually happened?

2 different errors with 2 different ways to import the class.

### CDK CLI Version

2.1.0

### Node.js Version

17.0.1

### OS

macOs BigSur M1

### Language

Python

### Language Version

Python 3.8.9

**Comment by peterwoodworth** [comment]
Hey @jeromevdl, I'm unable to reproduce this. Are you using the virtual environment?

**Comment by jeromevdl** [comment]
I'm in a virtual env yes. In visual studio, things are correctly imported, and I can browse to the CDK code. But I have the errors above when running tests. And I have this when running `cdk synth`:

Traceback (most recent call last):
  File "/.../cdk/cdk-pipelines-demo/app.py", line 11, in <module>
    pipeline = PipelineStack(app, 'PipelineStack', env={
  File "/.../cdk/cdk-pipelines-demo/.env/lib/python3.9/site-packages/jsii/_runtime.py", line 86, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/.../cdk/cdk-pipelines-demo/pipelines_webinar/pipeline_stack.py", line 19, in __init__
    pipeline = pipelines.CodePipeline(
  File "/.../cdk/cdk-pipelines-demo/.env/lib/python3.9/site-packages/jsii/_runtime.py", line 86, in __call__
    inst = super().__call__(*args, **kwargs)
TypeError: __init__() missing 2 required positional arguments: 'scope' and 'id'

the code is the following one:

```
# from aws_cdk import App
import aws_cdk as core

from pipelines_webinar.pipeline_stack import PipelineStack

PIPELINE_ACCOUNT = '123456789012'

#app = App()
app = core.App()
pipeline = PipelineStack(app, 'PipelineStack', env={
  'account': PIPELINE_ACCOUNT,
  'region': 'eu-central-1',
})

class PipelineStack(Stack):
  def __init__(self, scope: Construct, id: str, **kwargs):
    super().__init__(scope, id, **kwargs)
    # ...
```

**Comment by AymanZahran** [comment]
I faced the same issue here, it is solved by init new project in a different directory and moving the files to the new project. Also, make sure to specify the same stable versions for aws-cdk packages in requirements.txt

Version=1.83.0 is working fine

What is the version you are using?

**Comment by rix0rrr** [comment]
The code you gave doesn't work for reasons other than the error you cited, and you didn't give any commands.

If we cannot reproduce the problem, we cannot fix it. Please share instructions to reproduce from a clean state.

I did the following and this did not exhibit the problem:

```
$ python3 -m venv .env
$ source .env/bin/activate.fish
$ pip install aws-cdk-lib==2.2.0
$ cat - > app.py
# from aws_cdk import App
from constructs import Construct
from aws_cdk import App, Stack

class PipelineStack(Stack):
  def __init__(self, scope: Construct, id: str, **kwargs):
    super().__init__(scope, id, **kwargs)
    # ...

PIPELINE_ACCOUNT = '123456789012'

app = App()
pipeline = PipelineStack(app, 'PipelineStack', env={
  'account': PIPELINE_ACCOUNT,
  'region': 'eu-central-1',
})
app.synth()
<Ctrl-D>

$ /path/to/global/cdk -a 'python3 app.py' synth
(outputs CFN template)
```

I can only conclude there is something on your system that is causing what you are seeing.

**Comment by rob-saffell** [comment]
I recreated this issue.
It appears that the problem is that you are using aws-cdk.core (or a similar old version) and have not installed aws-cdk-lib.
Removing aws-cdk.core with `python3 -m pip uninstall aws-cdk.core`
And then installing the new major release with `python -m pip install aws-cdk-lib` should resolve your issue.
