### ISSUE TITLE
@aws-cdk/aws-s3-deployment: Support configuring AWS_CA_BUNDLE

### ISSUE THREAD

**Issue by willyg302** [aws/aws-cdk#18019]
### Description

We make use of [BucketDeployment](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-s3-deployment.BucketDeployment.html) to manage content in an S3 bucket as part of our stack. Behind the scenes, this creates a custom CloudFormation resource Lambda function to perform the transfer from the S3 deployment bucket to the desired S3 location.

Currently, the Lambda function [uses the AWS CLI from a Lambda layer](https://github.com/aws/aws-cdk/blob/73e5fec36cb149cf666320afbe63308c968c62dd/packages/%40aws-cdk/aws-s3-deployment/lib/lambda/index.py#L204). We'd like the ability to [set the certificate bundle](https://docs.aws.amazon.com/sdkref/latest/guide/setting-global-ca_bundle.html) used by the CLI.

### Use Case

We deploy to environments that require a custom certificate bundle, and in which the S3 CLI commands will fail without it being set.

### Proposed Solution

No strong opinions, but I suppose another prop could be added to `BucketDeployment` that would be threaded through to the [`environment` prop](https://github.com/aws/aws-cdk/blob/73e5fec36cb149cf666320afbe63308c968c62dd/packages/%40aws-cdk/aws-s3-deployment/lib/bucket-deployment.ts#L295) of the custom resource.

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by nikioftime** [comment]
+1 also seeing issues deploying to environments that require a custom certificate bundle that would be relieved by this option
