### ISSUE TITLE
(core): Not all userConfig not read from ~/.cdk.json

### ISSUE THREAD

**Issue by r0b0ji** [aws/aws-cdk#18015]
### What is the problem?

I have this content in my ~/.cdk.json

```
{
    "hosted-zone:account=518975620996:domainName=deenayak.item-knowledge.catalog.amazon.dev:region=us-west-2": {
        "Id": "/hostedzone/Z08554674HUC2O0GNWFJ",
        "Name": "deenayak.item-knowledge.catalog.amazon.dev."
    },
    "dev-allegiance-vpce-endpoint": "vpce-073abd9d08406dbb0-yitfxijf.vpce-svc-097eb489da615fc9e.us-west-2.vpce.amazonaws.com",
    "key1": "value1",
    "key2": "value2"
}

```

In my stack, I can get the value of HostedZone Id from this ~/.cdk.json when I do 
```
PublicHostedZone.fromLookup(this, "PrimaryHostedZone", {
     domainName: props.serviceEndpointName
});
```

But when I try to do `this.node.tryGetContext("dev-allegiance-vpce-endpoint")` I don't get the value defined in my user context, similarly for `key1` and `key2`. In [settings.ts I see the default of readUserContext is true
](https://github.com/aws/aws-cdk/blob/af61b7f2fec17d4f817e78db21d09d471d8e2baf/packages/aws-cdk/lib/settings.ts#L116) and HostedZoneId is actually read from my user context, but not sure why other context are not getting picked up.

What is the right way to read other userContext.

### Reproduction Steps

1. Add some userContext in ~/.cdk.json
2. Create an Stack and try to use `this.node.tryGetContext("some_key")`
3. For context lookup for some standard resources works, but not for custom key-value

### What did you expect to happen?

I expect that any key-value in ~/.cdk.json should be able to read by using `this.node.tryGetContext(...)`

### What actually happened?

The context key-value not getting read from ~/.cdk.json

### CDK CLI Version

1.134.0

### Node.js Version

16.9.1

### OS

Mac

### Language

Typescript

### Language Version

TypeScript (4.0.5)

**Comment by peterwoodworth** [comment]
Hey @r0b0ji,

For context to be read from your context file, you need to have the data under the `context` key, like so:
```
{
  context: {
    "hosted-zone:account=518975620996:domainName=deenayak.item-knowledge.catalog.amazon.dev:region=us-west-2": 
      {
        "Id": "/hostedzone/Z08554674HUC2O0GNWFJ",
        "Name": "deenayak.item-knowledge.catalog.amazon.dev."
      },
    "dev-allegiance-vpce-endpoint": "vpce-073abd9d08406dbb0-yitfxijf.vpce-svc-097eb489da615fc9e.us-west-2.vpce.amazonaws.com",
    "key1": "value1",
    "key2": "value2"
}
```

Your `fromLookup` example isn't actually reading any data from your context file - the cdk is fetching data from your aws account and storing it in `cdk.context.json`. 

[Here's](https://docs.aws.amazon.com/cdk/latest/guide/context.html) our documentation page on the topic. Let me know if you need more help!
