### ISSUE TITLE
lambda-nodejs: corrupt zip archive asset produced when using node v14.18.2 and CDK v2.1.0

### ISSUE THREAD

**Issue by bicatu** [aws/aws-cdk#18025]
### What is the problem?

When trying to deploy a simple CDK app using NodeJsFunction it gives error message of empty .zip

CREATE_FAILED        | AWS::Lambda::Function           | Router16807C72  | Resource handler returned message: "Uploaded file must be a non-empty zip (Service: Lambda, Status Code: 400

### Reproduction Steps

Stack definition

import { Stack, StackProps } from 'aws-cdk-lib';
import { Construct } from 'constructs';
import { NodejsFunction } from 'aws-cdk-lib/aws-lambda-nodejs';
import { SqsEventSource } from 'aws-cdk-lib/aws-lambda-event-sources';
import { Queue } from 'aws-cdk-lib/aws-sqs';

export class CdkSamStack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);

    const queue = new Queue(this, 'Queue', {
     queueName: 'cdk-sam-queue' 
    });

    const router = new NodejsFunction(this, 'Router', {
      functionName: 'cdk-sam-router',
      entry: './src/router.ts',
      handler: 'handler',
      environment: {
      },
    });

    router.addEventSource(new SqsEventSource(queue));
  }
}

The actual code of the router.ts

import { v4 as uuidv4 } from 'uuid';

const handler = (event: any) => {

    console.log(event);
    

    return {
        statusCode: 200,
        body: JSON.stringify({
            message: uuidv4()
        })
    }
}

### What did you expect to happen?

deployment to be successful with the lambda being available.

### What actually happened?

some resources were created but the deployment failed.

### CDK CLI Version

2.1.0

### Node.js Version

14.18.2

### OS

Linux

### Language

Typescript

### Language Version

3.9.10

### Other information

I already tried to remove the cdk.out and the assets on the s3 bucket prior to testing again. same results.

**Comment by kirintwn** [comment]
May be related to #17976

**Comment by corymhall** [comment]
@bicatu at least based on the example you provided, it looks like the issue is that you are not exporting the handler function. If you change it to this it should work. The reason is that `NodejsFunction` uses `esbuild` to do the bundling and esbuild produces an empty `index.js` file when there are no exports.

```ts
import { v4 as uuidv4 } from 'uuid';

export const handler = (event: any) => {

  console.log(event);

  return {
    statusCode: 200,
    body: JSON.stringify({
        message: uuidv4()
    })
  }
}
```

**Comment by mariobittencourt** [comment]
it worked. thanks.

I wish the message was clearer.

**Comment by peterwoodworth** [comment]
The error message produced comes from CloudFormation - so we can't do anything about that error message. However, I wonder if it's possible to catch these types of errors ahead of time (before deployment). @corymhall @kaizen3031593 are there any solutions here to make debugging easier on the customer?

**Comment by corymhall** [comment]
I think CloudFormation is the appropriate place to catch this error message. In this case it's actually the service that is throwing the error that CloudFormation is reporting. The Lambda service has some requirements on what a deployment bundle looks like and I'm not sure we should try and replicate that client side. We could check for empty directories, but what if bundling produces an empty file in the directory (like in this case), or we could check for an empty file in the directory, but what if bundling produces multiple files and just one of them is empty (and maybe that is fine).

**Comment by bicatu** [comment]
thank you. that worked.
