### ISSUE TITLE
(secretsmanager): SecretRotation causes circular dependency with target SecurityGroup

### ISSUE THREAD

**Issue by radarcg** [aws/aws-cdk#18026]
### What is the problem?

A lengthy discussion of this issues provides the best context, https://github.com/aws/aws-cdk/issues/1654#issuecomment-829493022. This describes the best practice of always calling in the 'to' direction rather than the 'from' direction when setting up rules (ingress or egress) which will mitigate or avoid this circular dependency issue. 

However, when creating a SecretRotation from the same stack as its 'target' parameter (likely a Database* instance), which takes  a securityGroup created from another stack, the cyclic reference is created. 

Pardon the lack of code in this ticket. As a java developer, I wouldn't do the typescript source any favors or justice. I'll reference source where I can. 

### Reproduction Steps

1. Create Stack A with a SecurityGroup.
2. Create Stack B with a DatabaseInstance db, taking as input the aforementioned SecurityGroup. 
3. synth / deploy - all is well
4. add SecretRotation to Stack B, with 'target' db 
5. synth fails on the cyclic reference

### What did you expect to happen?

A SecretRotation should be a valid resource to create within the same stack as the target db which uses a securitygroup from another stack. 

### What actually happened?

A cyclic reference is created. 

### CDK CLI Version

2.1.0

### Framework Version

2.1.0

### Node.js Version

8.1.4

### OS

Mac

### Language

Typescript, Java

### Language Version

Java 11

### Other information

One would assume from the lengthy discussion referenced above that changing this line of code:

https://github.com/aws/aws-cdk/blob/0745193e4c18ecb118ba3330a380f7474b527a2b/packages/%40aws-cdk/aws-secretsmanager/lib/secret-rotation.ts#L288

from:
`props.target.connections.allowDefaultPortFrom(securityGroup);`

to:
`securityGroup.allowDefaultPortTo(props.target.connections);`

may be the solution.

**Comment by njlynch** [comment]
Thanks for the bug report! These circular dependency issues are always a bit tricky. Your proposed solution _may_ work, but we (or a member of the community who's free to contribute!) will need to test a few use cases to ensure this isn't a breaking solution for other users (e.g., creating a circular dependency in a different use case).
