### ISSUE TITLE
Allow declarative/CLI method to import pre-existing resources

### ISSUE THREAD

**Issue by RichiCoder1** [aws/aws-cdk#18022]
### Description

Attempting to transition existing resources from non-CloudFormation (even existing CloudFormation) into the CDK currently is a relatively complicated and manual process that requires synthesizing the stack and going through an error prone process via the CFN CLI or Console.

### Use Case

To greatly simplify moving existing resources into the CDK stacks when transitioning from other IaC (or manual) methods of creating resources.

### Proposed Solution

In theory, some declarative way like `.importResource(<resource-identifier>)` on [supported resources](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-import-supported-resources.html) which gets automatically translated to the appropriate import change set upon either A) a newly created stack or B) if the CDK detects that an import statement is present and there's no underlying resources for a given logical resource in a stack.

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by rix0rrr** [comment]
It's not going to be declarative, but @tomas-mazak is cooking something up here: https://github.com/aws/aws-cdk/pull/17666
