### ISSUE TITLE
@aws-ses: Getting issue while creating Configuration Set

### ISSUE THREAD

**Issue by devendra-kumar1** [aws/aws-cdk#18031]
### General Issue

Getting issue while creating Configuration Set

### The Question

I am creating a ConfigurationSet under SES. Getting below error while doing cdk-deploy.
 **Error [ValidationError]: Template format error: Unrecognized resource types: [AWS::SES::ConfigurationSetEventDestination]**

Code: 

const cfnConfigurationSet = new ses.CfnConfigurationSet(this, 'MyCfnConfigurationSet',  {
      name: 'Test-CdkConfigSet',
    });

    const cfnConfigurationSetEventDestination = new ses.CfnConfigurationSetEventDestination(this, 'MyCfnConfigurationSetEventDestination', {
      configurationSetName: 'Test-CdkConfigSet',
      eventDestination: {
        matchingEventTypes: ['open','click','send'],
        enabled: true,
        kinesisFirehoseDestination: {
          deliveryStreamArn: <ARN of kinesis firehose>,
          iamRoleArn: <IAM role arn which has relevant permission>,
        },
        name: 'Test-Cdk-Config-Event-Destination',
      },
    });

### CDK CLI Version

2.1.0

### Framework Version

1.134.0

### Node.js Version

14.0.23

### OS

Windows

### Language

Typescript

### Language Version

Typescript(4.5.2)

### Other information

Region i trying to deploy is : **ap-south-1**

**Comment by otaviomacedo** [comment]
Apparently, this is not supported in all regions yet: https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/326
