### ISSUE TITLE
(aws-cdk-lib): improve loading time for monopackage library

### ISSUE THREAD

**Issue by rix0rrr** [aws/aws-cdk#18036]
The loading time of the `aws-cdk-lib` library is quite bad, encouraging import styles that will avoid loading the entire library (or saddling people who don't know JS very well with poor performance).

2 things we should be doing to the `aws-cdk-lib` build:

* Bundle and minify each submodule, to reduce the amount of files loaded and amount of characters scanned
  * The above will only help `node` runtime performance, not `tsc` compilation performance. We would need to do the same to the `.d.ts` files in order to help the TypeScript compiler along as well.
* Extract sourcemaps out into their own files
  * This will reduce amount of bytes scanned on each load operation
  * This probably doesn't require an action: it will probably come for free from doing the previous step

### Framework Version

2

**Comment by njlynch** [comment]
Status of this issue after the above (#18091):
* Minify each submodule (`.js` files) ✅ 
* Bundle each submodule into a single file (`.js` files) ❌ 
* Bundle and minify `.d.ts` files as well, to improve `tsc` performance ❌ 
* Extract sourcemaps out into their own files ✅ 

Bunding was attempted, but several issues were encountered and the effort was (for now) abandoned. No off-the-shelf solutions for bundling `.d.ts` files was found.
