### ISSUE TITLE
Appsync: Add support for custom domains

### ISSUE THREAD

**Issue by alextriaca** [aws/aws-cdk#18040]
### Description

Appsync has recently added support for custom domains. The cloudformation for this can be found here (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appsync-domainname.html)

### Use Case

Currently Appsync assigns a random URL when creating the API. If for some reason the API is ever deleted this URL is lost and a new and random URL is assigned. This means that you always have to consider updating those components that are dependent on the API as you cannot rely on the URL remaining the same. This change will remove that dependancy and allow users to create a custom URL that doesn't change even if the underlying API is rebuilt.

### Proposed Solution

API Gateway already supports this and so a similar implementation would seem sensible. Something like:

```python
domain_name = "test.my_domain.com"

certificate = Certificate(
    self,
    "certificate",
    domain_name=domain_name,
    subject_alternative_names=[domain_name],
    validation_method=ValidationMethod.DNS,
)

domain_name_options = DomainNameOptions(
    certificate=certificate, domain_name=domain_name
)

api = aws_appsync.GraphqlApi(
    self,
    "my_api",
    name="my_api",
    schema=aws_appsync.Schema.from_asset("resources/schema.graphql"),
    domain_name=domain_name_options,
)
```

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by joekendal** [comment]
+1

**Comment by samueldervis** [comment]
Currently doing it this way via CDK (v2)

```typescript

        const appsyncDomain = new CfnDomainName(this, 'AppsyncDomainName', {
            certificateArn: 'your arn',
            domainName: 'api.example.com',
            description: 'Domain name for AppSync Api',
        })
        new CfnDomainNameApiAssociation(this, 'AppsyncDomainNameApiAssociation', {
            apiId: this.api.attrApiId,
            domainName: appsyncDomain.attrDomainName,
        });

        const hostedZoneId = 'ZONE ID HERE'
       const zoneName = 'example.com'

        const zone = HostedZone.fromHostedZoneAttributes(this, `HostedZone`, {
            hostedZoneId,
            zoneName,
        });
        new CnameRecord(this, `LicorneAuthRecord`, {
            recordName: api,
            zone,
            domainName: appsyncDomain.attrAppSyncDomainName
        });


```

**Comment by daveharig** [comment]
+1
