### ISSUE TITLE
@aws-cdk/assertions: add Match.stringLike method

### ISSUE THREAD

**Issue by fractionalJoe** [aws/aws-cdk#18051]
### Description

It would be helpful to be able to match string property values with a regex rather than a string literal.

### Use Case

I would like to be able to perform a test like this:

``` typescript
  it.each`
          i
          ${1}  
          ${2}
      `("isolated Subnet $i has valid Route properties",
    ({ i }) => {
      // then
      template.hasResourceProperties("AWS::EC2::Route", {
        RouteTableId: {
          Ref: Match.stringLike`VPCisolatedsubnetSubnet${i}RouteTable.*`,
        },
        DestinationCidrBlock: "0.0.0.0/0",
        TransitGatewayId: "tgw-0b4c3ce049074911e",
      });
    });
```

### Proposed Solution

The proposed method signature would be  `Match.stringLike(pattern:  RegExp): boolean`

Returns true if the pattern is found in the string, otherwise false.

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by kaizen3031593** [comment]
Happy to take a community contribution on this!
