### ISSUE TITLE
(core): CustomResourceProvider entrypoint does not pass Lambda context object

### ISSUE THREAD

**Issue by Shaangor** [aws/aws-cdk#18055]
### What is the problem?

As of CDKv2, the `CustomResourceProvider` class significantly changed its API. In v1, you separately instantiated a Lambda function, then created a `CustomResourceProvider` via `CustomResourceProvider.fromLambda()`. In v2, `CustomResourceProvider` now wraps the Lambda on your behalf, and you specify a code directory to bundle. This is done because an `__entrypoint__.js` is injected into that bundle, that wraps your custom Lambda code. `__entrypoint__.js` is generated from `packages/@aws-cdk/core/lib/custom-resource-provider/nodejs-entrypoint.ts`. Line 41 `require`s your Lambda handler and line 42 calls it. Currently however the only argument being passed is the `event`.

https://github.com/aws/aws-cdk/blob/2b6c2dadc039f7c4255f6864386ba1dd28b6fc4f/packages/%40aws-cdk/core/lib/custom-resource-provider/nodejs-entrypoint.ts#L37-L42

This breaks any `CustomResourceProvider` handlers that rely on properties or methods from the `context` object that is normally an argument for Lambda handlers.

### Reproduction Steps

1. Write a `CustomResourceProvider` with Lambda code referencing `context` (e.g. `context.getRemainingTimeInMillis()`).
2. Write a resource using that `CustomResourceProvider`.
2. Deploy your CDK stack.
3. The Lambda will error with a `TypeError: Cannot read property 'getRemainingTimeInMillis' of undefined` and the stack will rollback.

### What did you expect to happen?

I expected my stack to deploy successfully as it did with CDKv1.

### What actually happened?

Custom resource Lambda threw `TypeError: Cannot read property 'getRemainingTimeInMillis' of undefined` and stack rollback or fails to deploy.

### CDK CLI Version

2.1.0

### Node.js Version

16.13.1

### OS

Windows 10

### Language

Typescript

### Language Version

4.5.4

### Other information

This restricts other packages from migrating to CDKv2, such as https://github.com/udondan/aws-cloudformation-custom-resource.

**Comment by rix0rrr** [comment]
You were using [@aws-cdk/aws-cloudformation.CustomResourceProvider](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-cloudformation.CustomResourceProvider.html#static-fromwbrlambdahandlerspan-classapi-icon-api-icon-deprecated-titlethis-api-element-is-deprecated-its-use-is-not-recommended%EF%B8%8Fspan), which has been deprecated for a year now.

The replacement is to use [CustomResource](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.CustomResource.html#servicetoken) and pass the ARN of your Lambda as serviceToken.
