### ISSUE TITLE
[aws-ec2] Add way to filter VPC subnets by tags #10366

### ISSUE THREAD

**Issue by jc1518** [aws/aws-cdk#18063]
### Description

Suggesting to reopen  #10366

### Use Case

As the other user mentioned that the situation where the VPC was not created by CDK. And there are multiple same subnet types, but for different purposes. e.g isolated for application, isolated for database.

### Proposed Solution

Add capability to select subnets by tags. e.g. vpc.selectSubnets({tags: { "subnet-tier": "Application" }});

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by njlynch** [comment]
Thanks for raising this. I'll reopen the original issue.
