### ISSUE TITLE
(aws-s3): adding prop to enable EventBridge in S3 BucketProps

### ISSUE THREAD

**Issue by mickychetta** [aws/aws-cdk#18076]
### Description

We can now use Amazon S3 Event Notifications with EventBridge to create new event driven applications after this [announcement](https://aws.amazon.com/about-aws/whats-new/2021/11/amazon-s3-event-notifications-amazon-eventbridge-build-advanced-serverless-applications/).

In order to take advantage of this feature, S3 must have enable EventBridge in the properties sections:
![image](https://user-images.githubusercontent.com/45010053/146595630-f52f235c-dc33-4876-a9a4-fde40a84ae56.png)

It is a resource in [CloudFormation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-notificationconfig-eventbridgeconfig.html) but not a resource in CfnBucket yet. 

### Use Case

In Solutions Constructs, we have a construct aws-s3-stepfunctions that uses S3 Event Notifications to send to EventBridge then trigger a state machine. At the moment we are using escape hatches to override the prop.

` cfnBucket.addPropertyOverride('NotificationConfiguration.EventBridgeConfiguration.EventBridgeEnabled', true);`

It is in CloudFormation but not yet in the CDK, It would a nice feature to have a prop to enable EventBridge.

### Proposed Solution

Add an optional prop to the CDK S3 `BucketProps` called `eventBridgeEnabled: boolean`. The resource is currently missing in CfnBucket and i'm not sure how to approach this but any pointers would be great so I can start working on it.

Another feature up for discussion is if it can be changed for an existing bucket? If it can, then will probably want an enableEventBridge() method on Bucket and IBucket.

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by otaviomacedo** [comment]
We could do that. But if it is in the CliudFormation spec, it should be available in `CfnBucket` in the next release of the CDK.

**Comment by michaelbrewer** [comment]
Oops, i did not see https://github.com/aws/aws-cdk/pull/18150 when i started https://github.com/aws/aws-cdk/pull/18236 

Hopefully @yerzhan7  your PR is reviewed and approved :)

**Comment by marciocadev** [comment]
This props doesn't show when we create a new bucket

I'm using CDK version 2.19.0

![image](https://user-images.githubusercontent.com/67694075/161400068-be8c4b07-a897-4367-8849-d3f7463d1dd0.png)

![image](https://user-images.githubusercontent.com/67694075/161400088-b55746d7-4343-4702-b37e-7b7699ab2e30.png)
