### ISSUE TITLE
@aws-cdk/aws-sqs: Add readonly deadLetter property to Queue

### ISSUE THREAD

**Issue by markmansur** [aws/aws-cdk#18083]
### Description

Add a `readonly` property to `Queue` to access the dead letter queue (if configured)

### Use Case

Sometimes I want access to a queues dead letter queue. For example say I'm building a separate monitoring stack which provisions CloudWatch dashboards/alarms for many SQS queues.

It would be much easier to have a dead letter queue property on each queue versus having to maintain code that maps each queue to it's dead letter queue. 

For example

```typescript
// Create deadletter queue
const deadletterQueue = new sqs.Queue(this, 'MyDeadLetterQueue');

// create SQS queue
const queue = new sqs.Queue(this, 'MySQSQueue', {
  deadLetterQueue: {
    queue: deadletterQueue,
    maxReceiveCount: 3
  }
});

// Want to be able to access dead letter queue as a property
const dlq = queue.deadLetterQueue;

```

### Proposed Solution

Add an optional readonly property to the `Queue` class to access the dead letter queue config, if one is configured

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by njlynch** [comment]
Sure, this sounds reasonable. I would start just adding it to `Queue`, and determine if there's a reasonable use case for adding to `IQueue` as a follow-up.

We welcome community contributions! If you are able, we encourage you to [contribute](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md).
