### ISSUE TITLE
cfnspec: AWS::ECS::Cluster advertises Tags property but it doesn't actually work

### ISSUE THREAD

**Issue by rix0rrr** [aws/aws-cdk#1808]
Reported on Gitter:

-----

CurtisEppel
@CurtisEppel
Feb 19 01:19

Hi, i've been updating my constructs to 0.24 so that I can use tagging on a stack. When I apply tags to my stack I'm getting an error where it tries to add tags to an ECS Cluster, but tagging is not supported in Cloudformation for ECS Clusters.

```
 1/31 | 11:00:40 AM | CREATE_FAILED        | AWS::ECS::Cluster                         | API/Cluster (Cluster57C9A150) Encountered unsupported property Tags
```

I'm not sure how CDK decides what resources to tags but I think it should not be trying to tag this resource? Is there anyway to remove a tag from a particular resource?

CurtisEppel
@CurtisEppel
Feb 19 01:31

Ok I found the docs for Tagging - https://awslabs.github.io/aws-cdk/refs/_aws-cdk_cdk.html
You can exclude resources using

```ts
new cdk.Tag('asset', 'api', {excludeResourceTypes: ['AWS::ECS::Cluster']})
```
Is this still a possible issue though?

-----

The problem is that our aspects will tag the cluster because it advertises itself to be taggable, but the CloudFormation schema doesn't match reality.

**Comment by SoManyHs** [comment]
From what I understand, support for ECS tags in CFN has been delayed, though can't say concretely until when.

**Comment by eladb** [comment]
Should we add some synth-time validation in the meantime to reduce grief?

**Comment by rix0rrr** [comment]
I think we should patch Tags out of the CFN spec.

**Comment by pkandasamy91** [comment]
Tagging support for CFN is launched as of June 13, 2019: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html. This is no longer an issue, and can be resolved. @rix0rrr
