### ISSUE TITLE
(aws-cdk): python installation is not working when following getting started

### ISSUE THREAD

**Issue by loicmarie** [aws/aws-cdk#18094]
### What is the problem?

When following the python [getting started](https://docs.aws.amazon.com/cdk/latest/guide/work-with-cdk-python.html) guide, the deployment will fail after any aws-cdk dependency installation

### Reproduction Steps

Follow the getting started steps.
`mkdir my-project && cd my-project && cdk init app --language python`
Activate the environment:
`source .venv/bin/activate`
Install dependencies:
`python -m pip install -r requirements.txt`
Then, `cdk deploy` will work.
Now install a dependency, like:
`python -m pip install aws-cdk.aws-s3`
Now `cdk deploy` will fail with error:
`AttributeError: partially initialized module 'aws_cdk' has no attribute 'cx_api' (most likely due to a circular import)`

### What did you expect to happen?

The deployment should work

### What actually happened?

`cdk deploy` fails with error:
`AttributeError: partially initialized module 'aws_cdk' has no attribute 'cx_api' (most likely due to a circular import)`

### CDK CLI Version

2.2.0

### Framework Version

2.2.0

### Node.js Version

14.17.4

### OS

Ubuntu 20.04.1 LTS

### Language

Python

### Language Version

3.9.5

### Other information

We can observe an error at `aws-cdk-lib` dependencies resolution at `pip install`:
`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
aws-cdk-lib 2.2.0 requires constructs<11.0.0,>=10.0.0, but you have constructs 3.3.167 which is incompatible.`

**Comment by loicmarie** [comment]
Ok I juste realised `aws_s3` has been moved into `aws_cdk` in 2.0.
So no need to `pip install aws-cdk.aws-s3` anymore, juste `from aws_cdk import aws_s3 as s3`.
Don't know if it is the case for all cdk packages though.

I think this is an important information that is not in the doc, but I can be wrong

**Comment by peterwoodworth** [comment]
You're reading the docs for v1 - Here are the docs for v2 https://docs.aws.amazon.com/cdk/v2/guide/work-with-cdk-python.html

Also, here's the guide for migrating to v2 https://docs.aws.amazon.com/cdk/v2/guide/migrating-v2.html

**Comment by loicmarie** [comment]
Yes I fixed it by finding the v2 doc. So this can be closed I think.
But still, I find it surprising that the getting started guide, that is the first entrypoint for cdk python beginners, is not working when following it step by step.

**Comment by peterwoodworth** [comment]
Thanks for the feedback @loicmarie, it's appreciated 🙂
