### ISSUE TITLE
(aws_kinesisfirehose): AmazonopensearchserviceDestinationConfigurationProperty missing in aws_kinesisfirehose.CfnDeliveryStream

### ISSUE THREAD

**Issue by imatw4r** [aws/aws-cdk#18099]
### link to reference doc page

https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_kinesisfirehose/CfnDeliveryStream.html#amazonopensearchservicedestinationconfigurationproperty

### Describe your issue?

In my company we were using `AmazonopensearchserviceDestinationConfigurationProperty` from `aws_kinesisfirehose.CfnDeliveryStream`, however after an updated to the most recent version (`1.136.0`) this option is gone (pretty much any version `>0.122.0` - perhaps even lower doesn't have that anymore). 

I am not sure if it's documentation that's outdated or if this is a bug because I was unable to found any mention of it in the aws-cdk [CHANGELOG](https://github.com/aws/aws-cdk/blob/master/CHANGELOG.md). Please can you tell me if I should use `ElasticsearchDestinationConfigurationProperty` instead from now on (as documented [here](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_kinesisfirehose/CfnDeliveryStream.html#elasticsearchdestinationconfigurationproperty)) and/or why previous option was removed?

**Comment by peterwoodworth** [comment]
I'm not entirely sure what you mean by "`AmazonopensearchserviceDestinationConfigurationProperty` is gone". I can still use this property normally. What errors are you running into?

**Comment by imatw4r** [comment]
@peterwoodworth 
>  pip freeze | grep aws-kinesis                                                                 ✔  nel 3.9.4   12:45:37  
aws-cdk.aws-kinesis==1.122.0
aws-cdk.aws-kinesisfirehose==1.122.0

Then I copy-paste example from the docs [here](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_kinesisfirehose/CfnDeliveryStream.html#amazonopensearchservicedestinationconfigurationproperty):

```
import aws_cdk.aws_kinesisfirehose as kinesisfirehose

amazonopensearchservice_destination_configuration_property = kinesisfirehose.CfnDeliveryStream.AmazonopensearchserviceDestinationConfigurationProperty(...)
```

And i get an error: `AttributeError: type object 'CfnDeliveryStream' has no attribute 'AmazonopensearchserviceDestinationConfigurationProperty'`

**Comment by imatw4r** [comment]
Ach, ok. I found the reason: 
![image](https://user-images.githubusercontent.com/22574645/146939833-b8f10da8-fc29-4f8c-b91b-8dc533c5d8f9.png)

Sorry for the inconvenience.
