### ISSUE TITLE
(aws-cdk-lib): ConcreteDependable is not exported from aws-cdk-lib

### ISSUE THREAD

**Issue by ChrisSargent** [aws/aws-cdk#18095]
### What is the problem?

Despite still existing in `@aws-cdk/core`, `ConcreteDependable` is not exported from `aws-cdk-lib` and we couldn't find any documentation about this change.

As I understand it, we should no longer need to include or import directly from `@aws-cdk/xxx` modules

### Reproduction Steps

```ts
import * as cdk from 'aws-cdk-lib';

new cdk.ConcreteDependable()
```

### What did you expect to happen?

To be able to access `ConcreteDependable` on `cdk`.

### What actually happened?

Error:
```
Property 'ConcreteDependable' does not exist on type 'typeof import("/Users/chrissargent/Sites/noah-main/packages/noah-infra/node_modules/aws-cdk-lib/index")'.ts(2339)
```

### CDK CLI Version

2.1.0 (build f4f18b1)

### Node.js Version

14

### OS

MacOS

### Language

Typescript

**Comment by kylelaker** [comment]
I have found using [`DependencyGroup` from `constructs`](https://docs.aws.amazon.com/cdk/api/v2/docs/constructs.DependencyGroup.html) works in place of `ConcreteDependable`.

**Comment by NGL321** [comment]
Hey @ChrisSargent,

Thank you for reporting this! While this may not be a bug, it is very helpful to know that this caused confusion.

Unless I am very much mistaken, `ConcreteDependable` no longer exists in `cdk-v2`. The confusion may come from the fact that we have published API-references for both v1 and v2 up at the moment, and there are few visual distinguishers. After searching through the v2 docs, I cannot find a reference to `ConcreteDependable`.

@kylelaker was right on the money. `DependencyGroup` fills the role of the former class exactly, and `IDependable`-related constructs have all moved to the `constructs` library.

I realize this may not be a satisfactory answer, but here is the link to the [CDK V2.x.x](https://docs.aws.amazon.com/cdk/api/v2/) docs, and the latest [CDK V1.x.x](https://docs.aws.amazon.com/cdk/api/v1/) docs.

Please let me know if this does not help.

**Comment by ChrisSargent** [comment]
@NGL321 & @kylelaker - thanks so much for your answers and understood. I thought we would have found this change in the changelog / release notes - also didn't even find any commits mentioning it (probably why its not in the changelog!).

All good now though, thanks for the quick reply.

**Comment by peterwoodworth** [comment]
The docs on [migrating from v1 to v2](https://docs.aws.amazon.com/cdk/v2/guide/migrating-v2.html) call this out -

> The Construct class has been extracted from the AWS CDK into a separate library, along with related types, to support efforts to apply the Construct Programming Model to other domains. If you are writing your own constructs or using related APIs, you must declare the construct module as a dependency and make minor changes to your imports. If you are using advanced features, such as hooking into the CDK app lifecycle, more changes may be needed. [See the RFC](https://github.com/aws/aws-cdk-rfcs/blob/master/text/0192-remove-constructs-compat.md#release-notes) for full details.
