### ISSUE TITLE
(cdk api): changeset names should default to stack name

### ISSUE THREAD

**Issue by markussiebert** [aws/aws-cdk#18096]
### Description

When cdk creates changesets, their name defaults to "cdk-deploy-change-set"
https://github.com/aws/aws-cdk/blob/e828c2229394fdf29699fd167c380bc229ea48e3/packages/aws-cdk/lib/api/deploy-stack.ts#L287

```
arn:aws:cloudformation:some-region-number:123456789:changeSet/cdk-deploy-change-set/som-uu-id
```

But this makes it hart to limit iam permissions to them. It would be nice, if the changeset name could match the stack name...

### Use Case

It would be easier to limit changeset iam permissions  

### Proposed Solution

let the default be the same as the stack name

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by rix0rrr** [comment]
Can you please describe your proposed use of this feature in a little more detail?
