### ISSUE TITLE
CDK V2 for .NET displays warning for -p usage from .NET 6 SDK

### ISSUE THREAD

**Issue by sjbthfc2** [aws/aws-cdk#18092]
### General Issue

Running CDK synth or deploy shows a warning from the .NET 6 SDK

### The Question

Please could the following warning be dealth with when running CDK commands for V2 and .NET:

`Warning NETSDK1174: The abbreviation of -p for --project is deprecated. Please use --project.`

Looks like this should be using `--project` instead of `-p`.

Thanks

### CDK CLI Version

Warning NETSDK1174: The abbreviation of -p for --project is deprecated. Please use --project.

### Framework Version

2.0

### Language

.NET

### Language Version

6.0

**Comment by njlynch** [comment]
Looks like this is coming from the `cdk.template.json` files. This is a pretty easy fix, good first issue for anyone.

Example:
https://github.com/aws/aws-cdk/blob/34f88cd308a283539458d5c5d7eb9a19626d3da0/packages/aws-cdk/lib/init-templates/v2/sample-app/csharp/cdk.template.json#L2

**Comment by dineshraj01** [comment]
I would like to take this up.

**Comment by peterwoodworth** [comment]
@dineshraj01 would you still like to take this up? Please check out [CONTRIBUTING.md](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) to get started, and let me know if you have any questions 🙂
