### ISSUE TITLE
(@aws-cdk/aws-certificatemanager): Is there way to get all issued acm certificates in CDK

### ISSUE THREAD

**Issue by jayPJ** [aws/aws-cdk#18111]
### General Issue

Is there way to get all issued acm certificates using CDK as in Python boto3

### The Question

Issue : I am unable to find a way to fetch all the acm certificates of a specific domain or region using CDK, what I want is as in python using boto3 we can retrieve issued/pending certificates by just passing region of aws account , I want to do same using CDK. Please suggest for same. 

Point to be noted : Don't want to import certificates using arn
Example in python
    *Get all existing certificates first
    acm=boto3.client('acm', region_name='us-east-1')
    paginator = acm.get_paginator('list_certificates')
    iterator = paginator.paginate(CertificateStatuses=['ISSUED'])

### CDK CLI Version

1.110.1

### OS

Windows 10

### Language

Typescript

### Language Version

3.9.7

**Comment by peterwoodworth** [comment]
The CDK is used to define your infrastructure - so functionality where the CDK will look up info from your account is very limited.

The CDK only offers an import for your Certificate - this doesn't look up info on your account however https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-certificatemanager.Certificate.html#static-fromwbrcertificatewbrarnscope-id-certificatearn

If you need to look up information from your AWS account - you should use an SDK. 

The exceptions to this are the methods on this page - [these methods](https://docs.aws.amazon.com/cdk/v2/guide/context.html#context_methods) are CDK methods which *do* look up info from your AWS account
