### ISSUE TITLE
Toolkit: build related docker images

### ISSUE THREAD

**Issue by rix0rrr** [aws/aws-cdk#1811]
Feature request from Nathan Peck: build two container assets where the second one is based on the first.

What needs to happen:

* Sequencing of the builds
* Pipe the image ID of the first build into the second in some way so that the second Dockerfile can do `FROM firstbuild...`

**Comment by sonofachamp** [comment]
Do [multi-stage builds](https://docs.docker.com/develop/develop-images/multistage-build/) cover this request, or is this a different use case?

**Comment by eladb** [comment]
Is this still relevant?
