### ISSUE TITLE
(cli): commands output Cloud Assembly to console

### ISSUE THREAD

**Issue by joel-aws** [aws/aws-cdk#18128]
### What is the problem?

When running `cdk ls` (or `synth`/`diff`) with CDK 1.137.0, what looks like Cloud Assembly is outputted to the console. This was tested with <1.137.0 and it did not occur.

Example Output:
```
{
  principal: <ref *1> ServicePrincipal {
    grantPrincipal: [Circular *1],
    principalAccount: undefined,
    assumeRoleAction: 'sts:AssumeRole',
    service: 'apigateway.amazonaws.com',
    opts: {}
  },
  scope: <ref *2> Method {
    node: ConstructNode { host: [Circular *2], _actualNode: [Node] },
    stack: Stack {
      node: [ConstructNode],
      _missingContext: [],
      _stackDependencies: {},
      templateOptions: {},
      _logicalIds: [LogicalIDs],
      account: '99999999999',
      region: 'us-east-1',
      environment: 'aws://99999999999/us-east-1',
      terminationProtection: undefined,
      _stackName: 'My-Stack',
      tags: [TagManager],
      artifactId: 'MyStackABCDE',
      templateFile: 'MyStackDEFGH.template.json',
      _versionReportingEnabled: true,
      synthesizer: [LegacyStackSynthesizer],
      [Symbol(@aws-cdk/core.DependableTrait)]: [Object],
      [Symbol($__jsii__objid__$)]: 'monocdk.Stack@10003',
      [Symbol($__jsii__interfaces__$)]: undefined
    },
```

### Reproduction Steps

run `cdk ls`

### What did you expect to happen?

The Cloud Assembly to not be outputted.

### What actually happened?

See: What is the problem.

### CDK CLI Version

1.137.0

### Node.js Version

v16.3.0

### OS

macOS 11.5.1

### Language

Python

**Comment by amaury-s** [comment]
Same error for me.
# CDK CLI Version
1.137.0

# Node.js Version
v16.8.0

# OS
macOS 11.4

# Language
Typescript

**Comment by rix0rrr** [comment]
Pretty sure that was this: https://github.com/aws/aws-cdk/pull/18136
