### ISSUE TITLE
(pipelines): ECS Deploy Step

### ISSUE THREAD

**Issue by tobytipton** [aws/aws-cdk#18121]
### Description

Have a ECSDeployStep which will create a step which can be added to the Modern CDK Pipeline, so there is a good way to add the [EcsDeployAction](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-codepipeline-actions.EcsDeployAction.html) to the pipeline. 

### Use Case

Deploying to ECS Deploy right now requires writing your own [Step](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_pipelines.Step.html) extension implementing [ICodePipelineActionFactory](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_pipelines.ICodePipelineActionFactory.html).  It would be ideal to have a step which is already defined which could be leveraged to add this to the pipeline.

### Proposed Solution

Solution would provide a class which can be leveraged to call the `EcsDeployAction` across account and across region.
This would require the `serviceArn` to get the account and region which the service is associated with.

### Other information

While researching this I also found the `clusterName` appears like it should exist in the `serviceArn` based on https://docs.aws.amazon.com/AmazonECS/latest/userguide/ecs-account-settings.html however that doesn't appear to be taken into account with the current CDK implementation.  Is this known?

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by tobytipton** [comment]
This would also be changes related tests which are being added in #18042.

**Comment by rix0rrr** [comment]
CDK Pipelines is built the notion that we deploy everything via CloudFormation.  It's an opinionated library, and not intended to model every single deployment pipeline.

You can build the exact pipeline you want using the CodePipeline L2 library, or by extending CDK Pipelines yourself if you want.

But as this feature is not in line with the CDK Pipelines vision, we are not going to merge this upstream.
