### ISSUE TITLE
(rds): simpler way to configure parameters for instance or cluster

### ISSUE THREAD

**Issue by hoegertn** [aws/aws-cdk#18124]
### Description

Instead of creating a new ParameterGroup and referencing it in the props, add a new field `readonly parameters?: { [key: string]: string };` to the instance and cluster props that is used to create a ParameterGroup under the hood.

### Use Case

Easier way to configure parameters. The parameters field is the only field that is necessary to create a group so it could be provided directly instead of forcing the user to create a group.

### Proposed Solution

Add `readonly parameters?: { [key: string]: string }; ` to DatabaseInstanceNew properties and create ParameterGroup internally.

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by skinny85** [comment]
@hoegertn already committed to working in this one 😉.
