### ISSUE TITLE
JS CDK: mismatch between documented (10.13.0) and actual (14.15.0) minimum Node.js version

### ISSUE THREAD

**Issue by tkalliom** [aws/aws-cdk#18130]
### General Issue

The Node.js version requirements in README.md and the engines section of package.json differ

### The Question

README.md states
> Node.js ≥ 10.13.0

However, in 9527bfa the Node.js version required in the `engines` section of `package.json`s was bumped to 14.15.0. One of these two is not correct.

### CDK CLI Version

2.2.0

### Language

Typescript

**Comment by peterwoodworth** [comment]
Hey @tkalliom, can you link me to where it states in the readme that the required node version is >= 10.13.0?

**Comment by tmokmss** [comment]
I also found the statement [here](https://docs.aws.amazon.com/cdk/v2/guide/getting_started.html#getting_started_prerequisites)

> All AWS CDK developers, even those working in Python, Java, or C#, need Node.js 10.13.0 or later.

**Comment by peterwoodworth** [comment]
I've created a PR to update this in the repo.

Thanks @tmokmss, I'll forward this to our docs writer

**Comment by peterwoodworth** [comment]
The Node version changing in `package.json`'s `Engines` section doesn't actually do anything other than produce a warning (since engine-strict isn't set) - so I'm not sure if this is something we want to update. @corymhall can you take a look at this?
