### ISSUE TITLE
@aws-cdk/aws-elasticloadbalancing: Request for a fromLookup method to look up existing classic load balancers

### ISSUE THREAD

**Issue by jfly** [aws/aws-cdk#18141]
### Description

(I asked about how to do this [over on SO](https://stackoverflow.com/questions/69714978/how-can-i-lookup-an-existing-classic-load-balancer-clb-via-the-arn-with-the-aw/69737160), and it looks like this isn't possible, so I'm filing a request here to add this feature.)

`@aws-cdk/aws-elasticloadbalancingv2` has [various `from*` lookup methods](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_elasticloadbalancingv2/README.html#looking-up-load-balancers-and-listeners), but I don't see anything like that over in [`@aws-cdk/aws-elasticloadbalancing`](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_elasticloadbalancing/README.html). Am I just missing it, or is this really a missing feature?

### Use Case

As for why we're using classic load balancers instead of newer application load balancers: we aren't actually creating new classic ELBs, but we've taken the stance that we'd like all new infrastructure to be managed via CDK, and sometimes that requires referencing existing infrastructure that was created by hand. That's what I'm trying to do here: set up a new CNAME in Route 53 to point at an existing (very old) classic ELB.

### Proposed Solution

We'd like something like this [`fromLookup` method](https://github.com/aws/aws-cdk/blob/ed30c4459666840a5c0396e943916e67c76b7135/packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-load-balancer.ts#L63-L70), but for classic load balancers.

Alternatively, it might work for us to instead be able to import the existing classic load balancer into our CDK stack. Is https://medium.com/@visya/how-to-import-existing-aws-resources-into-cdk-stack-f1cea491e9 the best tutorial to follow for that?

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by njlynch** [comment]
Can you provide a bit more details about the use case(s) for the lookup? I see the classic load balancer is an odd one out in terms of not even having an `ILoadBalancer` interface and "normal" import methods (e.g., `fromLoadBalancerArn`) that would allow you to reference the LoadBalancer without needing to do a full lookup.

If the use case is purely for creating the A Record, you can work around this in the mean time.

```ts
  const lbTarget: route53.IAliasRecordTarget = {
    bind(_r: route53.IRecordSet, _z?: route53.IHostedZone): route53.AliasRecordTargetConfig {
      return {
        hostedZoneId: 'ABCDEF123456',
        dnsName: 'dualstack.my-load-balancer-1234567890abcdef.elb.us-east-2.amazonaws.com',
      };
    },
  };
  new route53.ARecord(zone, 'Alias', {
    zone,
    target: route53.RecordTarget.fromAlias(lbTarget),
  });
```

**Comment by jfly** [comment]
Thanks @njlynch. Yeah, we actually already have a similar workaround implemented. I just wanted to file an issue since this does feel like a gap/asymmetry in the cdk api and thought y'all might want to know!

**Comment by okassov** [comment]
Thanks @njlynch. I have the same problem but my code is written in python. Can you please explain how to implement this in python or give an example?

**Comment by jfly** [comment]
@quintonn does the workaround [mentioned above](https://github.com/aws/aws-cdk/issues/18141#issuecomment-1003060592) work for you?

**Comment by quintonn** [comment]
@jfly If I hard code the hosted zone yes, but in my CDK code a classic load balancer is created by Kubernetes, and I am only able to obtain a load balancer DNS name.
And I can't seem to obtain the hosted zone ID from the load balancer DNS name.
It's not really feasible to have to hard code the zone id.
The only reason I have it is because I have already deployed my stack. 
For a new environment, this would mean I need to run the deployment step twice and for the second instance update the code.
I would like to have the code dynamic as possible

**Comment by zachariahtimothy** [comment]
> @jfly If I hard code the hosted zone yes, but in my CDK code a classic load balancer is created by Kubernetes, and I am only able to obtain a load balancer DNS name. And I can't seem to obtain the hosted zone ID from the load balancer DNS name. It's not really feasible to have to hard code the zone id. The only reason I have it is because I have already deployed my stack. For a new environment, this would mean I need to run the deployment step twice and for the second instance update the code. I would like to have the code dynamic as possible

I have the exact same challenge. In pulumi I simply ran 
```const lbPromise = aws.elb.getLoadBalancer({
    name: lbName,
  });
```
but there does not seem to be an equivalent in CDK. Did you find a workaround?

**Comment by alexey-bondarovitch-idt** [comment]
Another option/workaround similar to [this](https://github.com/aws/aws-cdk/issues/18141#issuecomment-1003060592):

    const loadBalancer: any = {
        loadBalancerCanonicalHostedZoneId: 'ABCDEF123456',
        loadBalancerDnsName: 'my-load-balancer-1234567890abcdef.elb.us-east-2.amazonaws.com'
    };
    const domain = 'my.lovely.domain';

    const record = new cdk.aws_route53.ARecord(zone, 'a-record', {
        zone,
        recordName: domain,
        target: cdk.aws_route53.RecordTarget.fromAlias(new cdk.aws_route53_targets.LoadBalancerTarget(loadBalancer))
    });
