### ISSUE TITLE
(pipelines): upgrade to v2 results in pipelines no longer working

### ISSUE THREAD

**Issue by ekeyser** [aws/aws-cdk#18162]
### What is the problem?

Upgrade to v2 from v1 of cdk results in broken pipelines.

### Reproduction Steps

from constructs import Construct
from aws_cdk import App, Stack
from aws_cdk import (
                     aws_codepipeline as cp,
                     aws_codepipeline_actions as cpa,
                     pipelines as pipelines,
                     aws_sns as sns,
                     aws_sns_subscriptions as subs,
                     aws_events as events,
                     aws_events_targets)

cloud_assembly_artifact = cp.Artifact()
original_pipeline = pipelines.CdkPipeline(self, "Pipeline",
    self_mutating=False,
    cloud_assembly_artifact=cloud_assembly_artifact
)

### What did you expect to happen?

To work as it did prior to upgrade from v1

### What actually happened?

AttributeError: module 'aws_cdk.pipelines' has no attribute 'CdkPipeline'

### CDK CLI Version

2.3.0 (build beaa5b2)

### Node.js Version

v14.18.1

### OS

Linux/Ubuntu 20.04

### Language

Python

### Language Version

3.8.10

**Comment by rix0rrr** [comment]
The `CdkPipeline` class has been deprecated for about half a year now, replaced by the `CodePipeline` class.

Read a migration guide here: https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/pipelines/ORIGINAL_API.md

**Comment by ekeyser** [comment]
Update the docs. https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.pipelines/README.html still shows CdkPipeline.
