### ISSUE TITLE
(lambda-nodejs): add support for monorepos

### ISSUE THREAD

**Issue by mikestopcontinues** [aws/aws-cdk#18175]
### What is the problem?

Rolling my codebase up in a monorepo, I found that trying to build a `NodejsFunction`, I get the following error:
```
Usage Error: Couldn't find a script named "esbuild".
```

I'm using the following settings in `.yarnrc.yml`, which hoists all my node_modules to my monorepo root:
```yaml
nmMode: hardlinks-global
nodeLinker: node-modules
```

### Reproduction Steps

Here's a [repro](https://github.com/mikestopcontinues/cdk-mono-yarn-esbuild-issue).

### What did you expect to happen?

I expected it to work.

### What actually happened?

```
Usage Error: Couldn't find a script named "esbuild".
```

### CDK CLI Version

2.3.0 (build beaa5b2)

### Framework Version

2.3.0

### Node.js Version

v14.18.1

### OS

OSX 12.0.1 (21A559)

### Language

Typescript

### Language Version

4.5.4

### Other information

Happy holidays! 😁

**Comment by blimmer** [comment]
I've encountered this error before, as well. It's a bit confusing, but you need to have `esbuild` in your **root** `package.json` file, not in your `packages/aws/package.json` file. I tested this on your repro repository and it works (see https://github.com/mikestopcontinues/cdk-mono-yarn-esbuild-issue/pull/1).

**Comment by blimmer** [comment]
Proposed documentation update here: https://github.com/aws/aws-cdk/pull/18216

**Comment by mikestopcontinues** [comment]
Really awesome, @blimmer. Thanks!

Gonna leave this open, as I think it still qualifies as a bug.

**Comment by corymhall** [comment]
I am unassigning and marking this issue as `p2`, which means that we are unable to work on this immediately.

We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://join.slack.com/t/cdk-dev/shared_invite/zt-mso6p56d-qJp7SOTBvMaQuDrx7R2wHg) to solicit support for reprioritization.

**Comment by mikestopcontinues** [comment]
@vleandersson It would take a little too long to gut the private stuff while preserving the useful bits. I don't use CDK pipelines because I started before they existed. I can offer some tips though:

1. Create a package for shared CDK-related utils, structs, config, and types. Some of these should be the `const` names of stack outputs.
2. Create a package that deploys shared infra. Output using your shared config constants
3. Create packages for each of your apps with their own CDK deployments. Reference shared infra using those constants.

I'm happy to answer any other questions you have!

**Comment by vleandersson** [comment]
@mikestopcontinues what I am struggling with at the moment is that `NodejsFunction` is requiring a separate `.lock` file per `package.json`. Using `Yarn v3` only one `.lock` file is created in the root folder instead of within each package in the monorepo. Is this something you came across and got a solution for?

**Comment by blimmer** [comment]
I added info about the single lockfile to the docs: https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda_nodejs-readme.html#reference-project-architecture

From my experience, this works great for yarn monorepos!

**Comment by vleandersson** [comment]
Related issue: https://github.com/evanw/esbuild/issues/884

**Comment by vleandersson** [comment]
Issue raised with aws https://github.com/aws/aws-cdk/issues/21161

**Comment by blimmer** [comment]
With yarn PnP see also #19452

**Comment by vleandersson** [comment]
@blimmer yeah, I saw that. Great insights. Thanks! Sadly `nodeLinker: node-modules` will turn off pnp, but I guess we got to live with that till we get pnp support added 🤷

**Comment by madeline-k** [comment]
Hi all, from this issue, it's not clear what the ask is for supporting monorepos with `lambda-nodejs`. They already are supported (at least to some extent). Closing this issue, just because it is not actionable in it's current state. Please open a new issue if you have requests for monorepo support.
