### ISSUE TITLE
aws_rds: Unable to read credentials from secret

### ISSUE THREAD

**Issue by dre2004** [aws/aws-cdk#18198]
### What is the problem?

I am creating a database secret with an auto generated password, I was expecting to be able to get the credentials from this secret in order to create an RDS instance but I can't get this to work.

### Reproduction Steps

```python
  db_secret = rds.DatabaseSecret(self, f"db_secret",
                                 username="dbadmin",
                                 secret_name=f"db_secret",
                                 exclude_characters="{}[]()'\"/\\")
  db_credentials = rds.Credentials.from_secret(self, db_secret)
```

### What did you expect to happen?

I expected that the credentials would be populated from the secret so I can use them when creating an RDS cluster

### What actually happened?

I then run `cdk list` and I get the following error

```
jsii.errors.JavaScriptError: 
  Error: Expected a string, got {"$jsii.byref":"aws-cdk-lib.aws_rds.DatabaseSecret@10022"}
      at Object.deserialize (/tmp/tmpefvbus3p/lib/program.js:9145:31)
      at Kernel._toSandbox (/tmp/tmpefvbus3p/lib/program.js:8783:69)
      at /tmp/tmpefvbus3p/lib/program.js:8831:42
      at Array.map (<anonymous>)
      at Kernel._boxUnboxParameters (/tmp/tmpefvbus3p/lib/program.js:8831:27)
      at Kernel._toSandboxValues (/tmp/tmpefvbus3p/lib/program.js:8817:29)
      at /tmp/tmpefvbus3p/lib/program.js:8269:136
      at Kernel._wrapSandboxCode (/tmp/tmpefvbus3p/lib/program.js:8860:24)
      at /tmp/tmpefvbus3p/lib/program.js:8269:87
      at Kernel._ensureSync (/tmp/tmpefvbus3p/lib/program.js:8841:28)
```

### CDK CLI Version

2.3.0 (build beaa5b2)

### Framework Version

aws-cdk-lib 2.1.0 

### Node.js Version

v14.18.2

### OS

Linux Mint

### Language

Python

### Language Version

3.8.3

**Comment by peterwoodworth** [comment]
The `fromSecret()` method [takes in a Secret, and a string](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-rds.Credentials.html#static-fromwbrsecretsecret-username). You currently have it filled with `(self, Secret)`
