### ISSUE TITLE
(module name): short issue description

### ISSUE THREAD

**Issue by awstomburge** [aws/aws-cdk#18196]
### General Issue

Atuoscaling Launch Configuration Support for Cloudformation Init

### The Question

I have CloudFormation templates that use AWS::CloudFormation::Init on AWS::AutoScaling::LaunchConfiguration resources.

I see that the EC2 module has some CloudFormation Init support. Does the Autoscaling Module support CloudFormation Init as well or is it UserData only.

If there is no support today, is it on the backlog for being added in?

Templates that use it can be found in quickstarts like this:

https://github.com/aws-quickstart/quickstart-atlassian-jira/blob/main/templates/quickstart-jira-dc.template.yaml

Lines 1093-1221

### CDK CLI Version

2.3

### Language

Python

### Language Version

3.7.3

**Comment by peterwoodworth** [comment]
Hey @awstomburge,

We have a feature request open for this - https://github.com/aws/aws-cdk/issues/6734 Here's where we're tracking it
