### ISSUE TITLE
(logs): Importing log group ignores region

### ISSUE THREAD

**Issue by kornicameister** [aws/aws-cdk#18214]
### What is the problem?

Per [this](https://github.com/aws/aws-cdk/issues/17747#issuecomment-1002725887) comment

> It's a bug in the `LogGroup.fromLogGroupArn()` method - you can see [here](https://github.com/aws/aws-cdk/blob/0fd80e13846442aa982fd1d9335cfdd813b548c5/packages/%40aws-cdk/aws-logs/lib/log-group.ts#L358-L358) that the region is not passed from the ARN to the returned Resource, like it should be ([here's](https://github.com/aws/aws-cdk/blob/0fd80e13846442aa982fd1d9335cfdd813b548c5/packages/%40aws-cdk/aws-servicecatalog/lib/portfolio.ts#L313-L315) a working example).

Blocks: #17747 

### Reproduction Steps

Same as in #

### What did you expect to happen?

When imported log group's region is referenced incorrect region is taken into account. A region coming from log group's ARN ought to be taken into account instead of region of the stack.

### What actually happened?

Region of the stack where log group is imported in is taken into account.

### CDK CLI Version

1.134

### Node.js Version

17.1.0

### OS

Linux

### Language

Typescript, Python, .NET, Java, Go

**Comment by NGL321** [comment]
Hey @kornicameister,

Thank you for reporting this, and thank you for submitting a fix!

Before someone takes a look at your PR, I see the listed CLI version is 1.134. Have you confirmed your published fix with the v2 library?

😸 😷

**Comment by kornicameister** [comment]
Actually, I haven't thought about that. I just copied details from an issue we ( or more like @skinny85 who confirmed that issue exists) found this one in.
What exactly should I do to cover that fix is published to V2?

**Comment by kornicameister** [comment]
@NGL321 apart from the fact I have submitted a PR against master I don't know how to publish a change against v2.
Would that be sufficient?

**Comment by skinny85** [comment]
> @NGL321 apart from the fact I have submitted a PR against master I don't know how to publish a change against v2. Would that be sufficient?

The change will make it to v2 automatically - we have an automated job that merges `master` to `v2-main` periodically. So, no need to do anything to get this in v2.
