### ISSUE TITLE
(aws-codepipelines-actions): Cannot set region on LambdaInvokeAction

### ISSUE THREAD

**Issue by jhoscar1** [aws/aws-cdk#18228]
### What is the problem?

`LambdaInvokeAction` does not accept region as a parameter. I have a CodePipeline that needs to invoke a function in a different region. I was hitting errors due to the LambdaInvokeAction assuming the region is the same as the CodePipeline, but it worked when I manually set the region in the action configuration in the AWS console. According to the [documentation](https://docs.aws.amazon.com/codepipeline/latest/userguide/action-reference-Lambda.html) this property can be defined in Cloudformation so it’s not clear why it’s not supported in CDK. I noticed that `LambdaInvokeActionProps` extends the `CommonActionProps` interface rather than the `ActionProperties` interface which does include the `region` field.

### Reproduction Steps

Created a Codepipeline stack in `us-west-2` with a stage containing a `LambdaInvokeAction` that needed to invoke a function in `us-east-1`.

### What did you expect to happen?

I expected to be able to define the region for the action to invoke the lambda.

### What actually happened?

The action had a region of us-west-2 and I could only change the region manually in the console.

### CDK CLI Version

1.108.0

### Node.js Version

14.16.1

### OS

Mac OS Big Sur (11.6)

### Language

Typescript

### Language Version

4.5.2

**Comment by ryparker** [comment]
PR: https://github.com/aws/aws-cdk/pull/18229

**Comment by skinny85** [comment]
Thanks for opening the issue @jhoscar1. Can you show the CDK code you are using to create your Lambda invoke CodePipeline Action?

Thanks,
Adam

**Comment by jhoscar1** [comment]
@skinny85 will post when back at work on Monday. Commenting to prevent auto close

**Comment by jhoscar1** [comment]
Here's a simplified version of the code we're running to create the action:

`
export class CodePipelineStack extends cdk.Stack {
  public readonly devPipelineOutput: cdk.CfnOutput;
​
  constructor(scope: cdk.Construct, id: string, props: CodePipelineStackProps) {
    super(scope, id, props);
​
    const appNameLambda = lambda.Function.fromFunctionAttributes(this, "AppNameLambda", {
      functionArn: cdk.Arn.format(
        { service: "lambda", resource: "function:AppName", account: "[**DIFFERENT ACCOUNT THAN PIPELINE**]" },
        cdk.Stack.of(this)
      ),
    });
​
    const lambdaInvokeAction = new codepipeline_actions.LambdaInvokeAction({
      actionName: `AppNameInvoke`,
      lambda: appNameLambda,
      userParameters: {
        param1: "value",
      },
      role: iam.Role.fromRoleArn(
        this,
        `crossAccountRole`,
        "arn:aws:iam::[**SAME ACCOUNT AS LAMBDA**]:role/app-name-cross-account-invoke"
      ),
    });
​
    const devPipeline = new codepipeline.Pipeline(this, "DevPipeline", {
      stages: [
        {
          stageName: "FetchDynamicValues",
          actions: [lambdaInvokeAction],
        },
      ],
    });
​
    this.devPipelineOutput = new cdk.CfnOutput(this, "DevPipelineOutput", {
      value: devPipeline.pipelineName,
    });
  }
}
`

**Comment by jhoscar1** [comment]
Here's a simplified version of the code we're running to create the action:

`
export class CodePipelineStack extends cdk.Stack {
  public readonly devPipelineOutput: cdk.CfnOutput;
​
  constructor(scope: cdk.Construct, id: string, props: CodePipelineStackProps) {
    super(scope, id, props);
​
    const appNameLambda = lambda.Function.fromFunctionAttributes(this, "AppNameLambda", {
      functionArn: cdk.Arn.format(
        { service: "lambda", resource: "function:AppName", account: "[**DIFFERENT ACCOUNT THAN PIPELINE**]" },
        cdk.Stack.of(this)
      ),
    });
​
    const lambdaInvokeAction = new codepipeline_actions.LambdaInvokeAction({
      actionName: "AppNameInvoke",
      lambda: appNameLambda,
      userParameters: {
        param1: "value",
      },
      role: iam.Role.fromRoleArn(
        this,
        "crossAccountRole",
        "arn:aws:iam::[**SAME ACCOUNT AS LAMBDA**]:role/app-name-cross-account-invoke"
      ),
    });
​
    const devPipeline = new codepipeline.Pipeline(this, "DevPipeline", {
      stages: [
        {
          stageName: "FetchDynamicValues",
          actions: [lambdaInvokeAction],
        },
      ],
    });
​
    this.devPipelineOutput = new cdk.CfnOutput(this, "DevPipelineOutput", {
      value: devPipeline.pipelineName,
    });
  }
}
`

**Comment by skinny85** [comment]
Yep, I see the problem. We need to pass the region from the ARN [here](https://github.com/aws/aws-cdk/blob/7df4a587daadbd46c9355097523b39342fafe5c2/packages/%40aws-cdk/aws-cloudfront/lib/function.ts#L135-L141).

I'll prepare a PR fixing this.
