### ISSUE TITLE
(DynamoDB): Cloudwatch Alarms are missing

### ISSUE THREAD

**Issue by driverpt** [aws/aws-cdk#18223]
### Description

Using `DynamoDBMetrics` static factories, i noticed that not all events for DynamoDb are here:

The ones that we want to use are:
- WriteThrottleEvents
- ReadThrottleEvents

But all should be added, 

### Use Case

Because we track Throttles individually

### Proposed Solution

https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/metrics-dimensions.html

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by skinny85** [comment]
Thanks for opening the issue @driverpt. Looks like we need to update metrics definition we get from CloudWatch Explorer [here](https://github.com/aws/aws-cdk/blob/7df4a587daadbd46c9355097523b39342fafe5c2/packages/%40aws-cdk/cfnspec/lib/canned-metrics/services.json#L4425).

**Comment by skinny85** [comment]
This should have been solved by https://github.com/aws/aws-cdk/pull/18233. Will be published in the next CDK release (`1.138.0`) this week.
