### ISSUE TITLE
(aws-kinesis): fails to deploy on-demand stream | Python CDK

### ISSUE THREAD

**Issue by SH953700** [aws/aws-cdk#18247]
### What is the problem?

I am not able to create a kinesis stream with on_demand mode. 

datastream = kinesis.Stream(self, f"stream_construct_id",
                                                  stream_mode=kinesis.StreamMode.ON_DEMAND)

It is throwing the error ShardCount is not expected when StreamMode=ON_DEMAND"
Internally somewhere it is setting up the shard_count value to 1

### Reproduction Steps

datastream = kinesis.Stream(self, f"stream_construct_id",
                                                  stream_mode=kinesis.StreamMode.ON_DEMAND)

### What did you expect to happen?

A on_demand kinesis stream is created.

### What actually happened?

the cdk deployment failed with the below message:

 **ife-streamife-dynamo-table (ifestreamifedynamotableD6DA59B6) Resource handler returned message: "ShardCount is not expected when StreamMode=ON_DEMAND"**

### CDK CLI Version

2.3.0

### Node.js Version

v10.22.1

### OS

Windows/Mac

### Language

Python

### Language Version

3.8.0

**Comment by peterwoodworth** [comment]
I've submitted a fix for this @SH953700 

In the meantime you can remove the unwanted shardCount property using [escape hatches](https://docs.aws.amazon.com/cdk/v2/guide/cfn_layer.html#cfn_layer_raw)

**Comment by peterwoodworth** [comment]
Hey @SH953700, 

This has been merged in, and this issue was a duplicate of #18139
