### ISSUE TITLE
(cloudfront.CfnDistribution): The parameter Origin DomainName does not refer to a valid S3 bucket

### ISSUE THREAD

**Issue by jayPJ** [aws/aws-cdk#18241]
### General Issue

Resource handler returned message: "Invalid request provided: The parameter Origin DomainName does not refer to a valid S3 bucket. (Service: CloudFront, Status Code: 400)

### The Question

When I am trying to create a cloudfront distribution and in origin domain I am passing the bucket as the origin it's giving errir "Invalid request provided: The parameter Origin DomainName does not refer to a valid S3 bucket. Given below is the origin code which I am trying to execute.
  origins:[
          {
          domainName:"[bucketName].s3.amazonaws.com",
          id:"123",
          originPath: "",
          // s3OriginConfig : origin['S3OriginConfig'],
          customOriginConfig: {
          originProtocolPolicy: 'http-only',
          httpPort:80,
          httpsPort:443,
          originSslProtocols: ["TLSv1", "TLSv1.1", "TLSv1.2"]
      }}],

I am not able to get, what I am doing wrong in this, I have also disabled static webhosting in bucket.

### CDK CLI Version

1.110.1

### OS

Windows 10

### Language

Typescript

### Language Version

3.9.7

**Comment by jumic** [comment]
According to the [documentation](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/distribution-web-values-specify.html#DownloadDistValuesDomainName
), the name has to be specified in the following format:

> Amazon S3 bucket – `DOC-EXAMPLE-BUCKET.s3.us-west-2.amazonaws.com`

Does this solve your issue?

Is there a reason why you are using the L1 construct (beginning with `Cfn`)? If not, I would recommend to use the L2 construct (see [`Distribution`](https://docs.aws.amazon.com/cdk/api/v1/docs/aws-cloudfront-readme.html#creating-a-distribution) in CloudFront CDK documentation). It provides a higher-level API and is easier to use.

**Comment by jayPJ** [comment]
No, it did not still receiving same issue after passing bucket format you suggested. Nevertheless I have done using L2 construct and it's working, thanks for the suggestion.
 origins:[
          {
          domainName:"bucket.s3.us-east-1.amazonaws.com",
          id:origin['Id'],
          originPath: "",
          // s3OriginConfig : origin['S3OriginConfig'],
          customOriginConfig: {
          originProtocolPolicy: 'http-only',
          httpPort:80,
          httpsPort:443,
          originSslProtocols: ["TLSv1", "TLSv1.1", "TLSv1.2"]
      }}],

**Comment by njlynch** [comment]
Hi @jayPJ ,

It sounds like you have everything working now with the `Distribution` construct. Just to follow up on the original issue:

> [...] I have also disabled static webhosting in bucket.

If you have static webhosting disabled on the bucket, then you need to use an `s3OriginConfig` rather than the `customOriginConfig`. The latter is only used for S3 buckets when webhosting is enabled, and then the domain name must point to the bucket's webhosting URL.

I'm going to close this out, as it sounds like you're set now, but feel free to mention me in a reply if you have a follow-up.
