### ISSUE TITLE
Input secrets through CloudFormation parameters

### ISSUE THREAD

**Issue by spg** [aws/aws-cdk#1825]
I'm wondering what would be the best solution to adapt my team’s current workflow to the CDK.

The current deployment workflow we use in our team (we don’t use CDK yet) is to authour our own Yaml CloudFormation templates by hand.

In some cases, the stack we want to create will require the use of a secret. For example, if we want to provision a RDS instance, a master DB password will be required.

What we usually do is we use a CloudFormation parameter (for instance, `DBPassword`) and set `NoEcho: true`. In the same stack, we provision a `AWS::SecretsManager::Secret` (`DBPasswordSecret`) that will contain the database’s password. We then input the password into the `AWS::RDS::DBInstance`:
```
MasterUserPassword: !Ref DBPassword
```

Using this approach has the following benefits:
* Not every member in our team needs to know the master DB password. Only the creator of the CFn stack has to input the value for `DBPassword` upon stack creation. For all future updates of the stack, we leave the “Use existing value” checkbox checked. This is important for us, as we want to limit the number of persons in our team who can retrieve the password’s value.
* Storing the password’s value in a `AWS::SecretsManager::Secret` allows us to restrict (using IAM policies) who in our company can retrieve the DB password.
* Also, storing the password’s value in  `AWS::SecretsManager::Secret` allows authorized IAM users to retrieve the secret’s value, if needed. Otherwise, the password’s value would be lost (since we’re using `NoEcho: true` on the `DBPassword` CFn parameter)

Now, I’m having trouble replicating the same workflow using the cdk (I had similar issues with Serverless framework, which motivated me to look at the cdk).
Having looked at https://docs.aws.amazon.com/CDK/latest/userguide/passing_in_data.html , it seems like values can only be passed from outside the cdk app.
For example, using an environment variable (e.g, `DB_PASSWORD`) or a context variable would not fit our workflow, because every developer in our team will need to know the password’s value in order to set `DB_PASSWORD` when running `DB_PASSWORD=“the password" cdk deploy`. 

Storing this password in a local config file also does not cut it, as we don’t want to put that config file (thus, the password) in Git.

Furthermore, I would not want to have to provision 2 stacks to achieve this goal:
* a first stack (e.g. `SecretsStack`) that provisions a `AWS::SecretsManager::Secret` containing the DB password
* then, a second stack which references the `AWS::SecretsManager::Secret` created in `SecretsStack`
This approach would allow members in the team to update the 2nd stack without having to know the DB password or risking overwriting the CFn parameter in the 1st stack.
Unfortunately, I find this approach the be a bit cumbersome, as every CFn stack that needs secrets will require a “sidecar” CFn stack containing secrets.
In a ideal world, both the secrets and the app’s resources could be colocated in the same CFn stack.

This is a pain point that has been bugging me for a while with the Serverless framework. Passing secrets through CFn parameters is impossible using the Serverless Framework, as they get overwritten on each deployment. I would very much appreciate if the cdk came to the rescue and made this process possible.

Thanks!

**Comment by rix0rrr** [comment]
You've landed on the solution: the recommended way of doing this is through secrets manager secrets.

If you want to reuse the same secret among multiple stacks, you have two options:

* Provision a secret by hand, import into CDK.
* Split up into two stacks, as you mentioned.

I don't think there are any other options, I'm sorry.
