### ISSUE TITLE
aws-dynamodb: Global table replicas aren't getting tags set

### ISSUE THREAD

**Issue by tgigsigniant** [aws/aws-cdk#18251]
### General Issue

Replicas created through the CDK Table construct inherit all properties of the table, except the tags. We were wondering if this is expected? If not would it be possible to fix this, since it seems like a useful feature?

### The Question

Can we fix the Table construct to add tags to the replica tables created by the `replicationRegions` param?

https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-dynamodb.Table.html#replicationregions

### CDK CLI Version

1.134.0

### Language

Typescript

**Comment by skinny85** [comment]
Hey @tgigsigniant,

thanks for opening the issue. We already have an an existing issue dealing with this: https://github.com/aws/aws-cdk/issues/14943, let's keep the conversation there.

Thanks,
Adam

**Comment by tgigsigniant** [comment]
Hey @skinny85, FYI the issue wasn't indexed on Google will keep in mind to search GitHub separately as well next time.

Thank you for the quick response.
