### ISSUE TITLE
(core): Release process v1 vs v2

### ISSUE THREAD

**Issue by chris-smith-zocdoc** [aws/aws-cdk#18267]
### link to reference doc page

https://github.com/aws/aws-cdk/blob/v2.3.0/docs/release.md

### Describe your issue?

What is the release process for the v1 branch vs v2? 

https://github.com/aws/aws-cdk/releases/tag/v1.138.0 was published a few hours ago but I don't see a corresponding 2.x release

I was hoping to use a recently (~5 days ago) merged feature https://github.com/aws/aws-cdk/commit/7d0680a5a858633f92aeb78353cac22b9a391fa7

**Comment by rix0rrr** [comment]
We are aware and working on it, thanks for getting in touch.
