### ISSUE TITLE
`cdk bootstrap --force` does not create a bucket when the `cdktoolkit-stagingbucket` bucket is missing

### ISSUE THREAD

**Issue by adamnovak** [aws/aws-cdk#18261]
As noted in the referenced comment, the CDK can be gotten into a state where the CloudFormation template exists, but the staging bucket does not. In this state, it will appear un-bootstrapped when you try to deploy stuff, but it won't be able to finish the bootstrapping process.

I would expect the `--force` option to force the creation of the missing bucket, but it does not. It ought to.

>### **PLEASE HELP**
>I manually deleted cdktoolkit-stagingbucket-xxx and now I tried to create another project and deploy.
>
>Its successfully bootstrapping but it fails to deploy with following error.
>
>`[100%] fail: No bucket named 'cdktoolkit-stagingbucket-xxx'. Is account {account#} bootstrapped?`
>
>And here is when I `cdk bootsrap` again.
>
>```
> ⏳  Bootstrapping environment aws://{account#}/eu-west-1...
> ✅  Environment aws://{account#}/eu-west-1 bootstrapped (no changes).
>```
>
>Again when I deploy it fails with error above
>
>## Solved
>Just delete `CDKToolkit` named cloudformation stack from that region and bootstrap again. It worked. 
>Never going to manually delete anything. I almost got locked out of region for CDK.
>
_Originally posted by @apoorvmote in https://github.com/aws/aws-cdk/issues/986#issuecomment-666919935_

**Comment by peterwoodworth** [comment]
Hey @adamnovak,

the `--force` option is specifically for bootstrapping a region that is already bootstrapped on a _higher_ version. The note on the help menu says this for the description:

> Always bootstrap even if it would downgrade template version [boolean] [default: false]

The functionality you desire isn't something the CDK has control over unfortunately. This is a consequence of making a call to deploy an existing stack which has [drifted](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-stack-drift.html#what-is-drift)
