### ISSUE TITLE
(API Gateway): support adding a model to a method after creation

### ISSUE THREAD

**Issue by thomasstep** [aws/aws-cdk#18260]
### Description

Currently a model must be created and passed to a method during creation through the [Method Options](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_apigateway.MethodOptions.html). I would like to instead be able to add a model to a method after the method has been created.

### Use Case

I have a construct that is relied on that creates an API Gateway and its necessary methods and Lambda integrations. Rigging something up that can inject a model into a method in the middle of the construct's constructor would most likely be extremely difficult and dirty.

### Proposed Solution

I have not dug into the code too much nor do I completely understand the code that makes CDK run. Is it possible to call something like `method.addModel()` and call [`renderRequestModels`](https://github.com/aws/aws-cdk/blob/73f0f0ef765ceed4dbd4be7e797a744511ff10a8/packages/%40aws-cdk/aws-apigateway/lib/method.ts#L327) again?

### Other information

I would be more than happy to help in any way with the code changes required for this. If someone can add the feature quicker than me that's probably for the best though since I imagine it will take me a while to understand what's going on with everything in this code base.

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by otaviomacedo** [comment]
Hi, @thomasstep. Thanks for bringing up this use case and for volunteering to help implement this feature.

> I have not dug into the code too much nor do I completely understand the code that makes CDK run. Is it possible to call something like method.addModel() and call renderRequestModels again?

Yes, it's possible. We would just need to add some `Lazy.any()` in some places to postpone the rendering until the construct has all the models to render. But before moving on with the implementation, can you share a more complete example of how the interface would look like, in your opinion?
