### ISSUE TITLE
There is no search field in API reference documents

### ISSUE THREAD

**Issue by makemefeelgr8** [aws/aws-cdk#18287]
### link to reference doc page

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-construct-library.html

### Describe your issue?

Happy NY yall!
Lemme demonstrate ya my use case.
Let's say there's a CDK feature called `ApplicationListenerRule` I'm interested in. So, I open CDK v2 API docs:
https://docs.aws.amazon.com/cdk/api/v2/docs/aws-construct-library.html

Where do I type `ApplicationListenerRule` in to get more info about it? I've tried using CTRL+F but it doesn't find the thing I need.
Really? How come there's no search field in API reference?

Lemme just show ya how your competitors do it:
https://docs.microsoft.com/en-us/rest/api/azure/
Guys from Microsoft made not just 1, but 2 search fields! The 1st one allows you to search the whole website, while the 2nd one allows you to quickly filter categories by title.

Come on guys! I totally love the CDK and the stuff you do. But that CDK API page definitely needs some love. You could just slap a `Filter by title` field at the very least.
Thanks!

**Comment by peterwoodworth** [comment]
Hey, thanks for this feature request!

I'd love to see this too, and in fact we already have a feature request open for this! Please add your comment to [this issue](https://github.com/aws/aws-cdk/issues/5634) and leave a thumbs up
