### ISSUE TITLE
(cfnSpec): Attributes returned as integers output dummy values instead of calling getAtt

### ISSUE THREAD

**Issue by naxxster** [aws/aws-cdk#18282]
### What is the problem?

I can't make output value from attrClusterEndpointPort property of memorydb.CfnCluster.
The generated CloudFormation template show hardcoded number value rather than reference value from AWS::MemoryDB::Cluster resource.

```
  "Outputs": {
    "MemoryDBEndpointAddress": {
      "Value": {
        "Fn::GetAtt": [
          "MemoryDBCluster",
          "ClusterEndpoint.Address"
        ]
      }
    },
    "MemoryDBEndpointPort": {
      "Value": "-1.888154589708829e+289"
    },
```

### Reproduction Steps

```
import { Stack, StackProps, CfnOutput } from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as ec2 from 'aws-cdk-lib/aws-ec2';
import * as iam from 'aws-cdk-lib/aws-iam';
import * as memorydb from 'aws-cdk-lib/aws-memorydb';
import * as elasticache from 'aws-cdk-lib/aws-elasticache';

export class BenchmarkVsElasticacheRedisStack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);

    const vpc = new ec2.Vpc(this, 'VPC');

    const dbSecurityGroup = new ec2.SecurityGroup(this, 'DB Security Group', {
      vpc
    });

    const subnets = vpc.selectSubnets({
      subnetType: ec2.SubnetType.PRIVATE_WITH_NAT
    });

    const memoryDBSubnetGroup = new memorydb.CfnSubnetGroup(this, 'MemoryDB Subnet Group', {
      subnetGroupName: 'memorydb-test-subnet-group',
      subnetIds: subnets.subnetIds,
    });

    const memoryDBCluster = new memorydb.CfnCluster(this, 'Memory DB Cluster', {
      clusterName: 'memorydb-test',
      nodeType: 'db.r6g.large',
      aclName: 'open-access',
      subnetGroupName: memoryDBSubnetGroup.subnetGroupName,
      securityGroupIds: [ dbSecurityGroup.securityGroupId ],
      tlsEnabled: false
    });
    memoryDBCluster.node.addDependency(memoryDBSubnetGroup, dbSecurityGroup);

    new CfnOutput(this, 'Memory DB Endpoint Address', {
      value: memoryDBCluster.attrClusterEndpointAddress
    });
    new CfnOutput(this, 'Memory DB Endpoint Port', {
      value: memoryDBCluster.attrClusterEndpointPort.toString()
    });
  }
}
```

### What did you expect to happen?

The output value of memorydb cluster's port number should be the reference of the resource.

### What actually happened?

The output value of memorydb cluster's port number is hardcoded number value.

### CDK CLI Version

2.3.0 (build beaa5b2)

### Framework Version

2.3.0

### Node.js Version

v16.13.1

### OS

MacOS

### Language

Typescript

### Language Version

TypeScript (3.9.10)

**Comment by peterwoodworth** [comment]
Thanks for reporting this @naxxster, I'm finding the same behavior with the other attributes which end up as integers. (Such as `Lightsail::Disk.Iops`)

Before this is fixed, you can create the `getAtt` reference with the [`Fn.getAtt()`](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_core.Fn.html#static-getwbrattlogicalnameofresource-attributename) function.

```
Fn.getAtt('MyCluster', 'ClusterEndpointPort)
```

**Comment by rix0rrr** [comment]
Here is the problem:

```ts
value: memoryDBCluster.attrClusterEndpointPort.toString()
```

You can't stringify number tokens in this way. You should be calling [`Tokenization.stringifyNumber()`](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.Tokenization.html#static-stringifywbrnumberx)... but I agree this is a bit of a bother, and we might be able to do the detection automatically instead.

**Comment by naxxster** [comment]
I can workaround the error with following code:
```typescript
      value: Token.asString(memoryDBCluster.getAtt('ClusterEndpoint.Port'))
```

I suggest to make the code consistent with `elasticache.CfnReplicationGroup.attrPrimaryEndPointPort` or `rds.CfnDBCluster.attrEndpointPort`, which translate token as string with `Token.asString`.

**Comment by rix0rrr** [comment]
We should add validation.

**Comment by otaviomacedo** [comment]
Fixed by https://github.com/aws/aws-cdk/pull/19578.
