### ISSUE TITLE
(aws-ec2): Missing enum entries for ec2.SubnetType in CDK-1.x

### ISSUE THREAD

**Issue by anon-44** [aws/aws-cdk#18292]
### What is the problem?

CDK-1.122.0 introduced new entries in the SubnetType enum, while marking a few old ones as deprecated - https://github.com/aws/aws-cdk/commit/2023004cc941a0e7a908bf3c90ad9887c6679564

While the documentation includes the deprecation notice and recommendations for using the new entries, the new entries aren't actually present in the enum.
Docs - https://docs.aws.amazon.com/cdk/api/v1/java/index.html?software/amazon/awscdk/services/ec2/SubnetType.html

CDK-2.x has the entries present(likely because the old entries are removed altogether), but the provided example still references the old entries from CDK-1.x. See https://docs.aws.amazon.com/cdk/api/v2/java/index.html?software/amazon/awscdk/services/ec2/SubnetType.html

### Reproduction Steps

N/A

### What did you expect to happen?

CDK-1.x should include the suggested new entries in the SubnetType enum along with the old deprecated entries.

### What actually happened?

CDK-1.x does not include the suggested new entries in the SubnetType enum.

### CDK CLI Version

cdk-1.131.0

### Node.js Version

14

### OS

MacOS-11.6

### Language

Java

### Language Version

Java-8

**Comment by peterwoodworth** [comment]
Hey @anon-44, thanks for reporting this

This is a known issue for some of our non-TypeScript libraries. The source of this issue is due to JSII and the issue is [here](https://github.com/aws/jsii/issues/2782). It's not fixed yet, but as you've found, the issue isn't present in v2.

**Comment by anon-44** [comment]
So is the recommendation here to upgrade to v2? Will this not be fixed in v1 releases?

**Comment by peterwoodworth** [comment]
There's no ETA for the fix in v1, so you should upgrade to v2 if you don't want to deal with the warnings or use any workarounds. 

I recommend upgrading to v2 anyway, I find it a much nicer experience overall. Here's [our docs](https://docs.aws.amazon.com/cdk/v2/guide/migrating-v2.html) on how to upgrade 🙂
