### ISSUE TITLE
(pipeline): primaryOutputDirectory doesn't work

### ISSUE THREAD

**Issue by byongwu** [aws/aws-cdk#18294]
### What is the problem?

I coded just as mentioned about [primaryOutputDirectory](https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/pipelines#:~:text=to%20adjust%20the-,primaryOutputDirectory,-to%20match%3A), but it fails to work.
This is my code snippet.
```
    // The basic pipeline declaration. This sets the initial structure
    // of our pipeline
    const cdk_infra_path = "packages/cdk-infra";
    const cdk_infra_path_back = "../..";
    const cdk_out_path = "cdk.out";
    const steps = new pipelines.ShellStep("Synth", {
      input: pipelines.CodePipelineSource.codeCommit(repo, "master"),
      commands: [
        "cd " + cdk_infra_path,
        "npx lerna bootstrap --ci",
        "npx lerna run build",
        "npx cdk synth",
        "cd " + cdk_infra_path_back,
        "ln -s " + cdk_infra_path + "/" + cdk_out_path + " " + cdk_out_path,
      ],
      primaryOutputDirectory: cdk_infra_path + "/" + cdk_out_path,
    });

    const pipeline = new pipelines.CodePipeline(this, "Pipeline", {
      pipelineName: SrvConfig.PIPELINE_NAME,
      synth: steps,
    });
  }
```

However, it fails me at the end with this CodeBuild log output.

```
< snip >
      Source:
        BuildSpec: |-
          {
            "version": "0.2",
            "phases": {
              "build": {
                "commands": [
                  "cd packages/cdk-infra",
                  "npx lerna bootstrap --ci",
                  "npx lerna run build",
                  "npx cdk synth",
                  "cd ../..",
                  "ln -s packages/cdk-infra/cdk.out cdk.out"
                ]
              }
            },
            "artifacts": {
              "base-directory": "packages/cdk-infra/cdk.out",  <=====
              "files": "**/*"
            }
          }
        Type: CODEPIPELINE
< snip >
[Container] 2022/01/06 18:37:12 Phase complete: BUILD State: SUCCEEDED
[Container] 2022/01/06 18:37:12 Phase context status code:  Message: 
[Container] 2022/01/06 18:37:12 Entering phase POST_BUILD
[Container] 2022/01/06 18:37:12 Phase complete: POST_BUILD State: SUCCEEDED
[Container] 2022/01/06 18:37:12 Phase context status code:  Message: 
[Container] 2022/01/06 18:37:12 Expanding base directory path: cdk.out  <=====
[Container] 2022/01/06 18:37:12 Assembling file list
[Container] 2022/01/06 18:37:12 Expanding cdk.out
[Container] 2022/01/06 18:37:12 Skipping invalid file path cdk.out
[Container] 2022/01/06 18:37:12 Phase complete: UPLOAD_ARTIFACTS State: FAILED
[Container] 2022/01/06 18:37:12 Phase context status code: CLIENT_ERROR Message: no matching base directory path found for cdk.out
```
The whole log: [log-events-viewer-result (1).csv](https://github.com/aws/aws-cdk/files/7824089/log-events-viewer-result.1.csv)

My two cents on this. Maybe this code (https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/pipelines/lib/main/pipeline-base.ts#L62) is reverting the path to `cdk.out`?

Please help. I need my CDK v2 + CodePipeline working for my customer.

### Reproduction Steps

* Enable CDK v2 + CodePipeline as mentioned in https://docs.aws.amazon.com/cdk/v2/guide/cdk_pipeline.html#cdk_pipeline_define
* Move the CDK folder to `packages/cdk-infra`
* Keep it working with CDK v2 + CodePipeline but it will fail on CodeBuild stage.

### What did you expect to happen?

CDK v2 + CodePipeline + `primaryOutputDirectory` working in my CDK infra's subdirectory of `packages/cdk-infra`.

### What actually happened?

Failed at CodeBuild with the log mentioned above.

### CDK CLI Version

2.4.0 (build 993f14d)

### Framework Version

2.4.0

### Node.js Version

v14.17.5

### OS

MacOS

### Language

Typescript

### Language Version

Version 4.1.3

**Comment by byongwu** [comment]
I also tried https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.pipelines.ShellStep.html#primarywbroutputwbrdirectorydirectory method but it didn't work.

**Comment by rix0rrr** [comment]
The combination of the things you pointed to with arrows:

```
              "base-directory": "packages/cdk-infra/cdk.out",  <=====
```

and 

```
[Container] 2022/01/06 18:37:12 Expanding base directory path: cdk.out  <=====
```

Is simply not possible. What that tells me is that one of these things does not reflect reality.

The log probably DOES reflect reality, which means the snippet you showed where `base-directory` is something else probably does not. I'm going to guess that:

* The snippet you showed is the BuildSpec in the CloudFormation template produced by a local `cdk synth`
* The CodeBuild project in the actual pipeline never got updated to the new BuildSpec, and is therefore running the old one (where the artifact directory was still `cdk.out`)
* Since the pipeline doesn't synth and self-update successfully anymore, no change to the source code is going to ever end up reflecting in the actual infrastructure. You need to do a one-time `cdk deploy` to get the BuildSpec updated, and then the pipeline will start flowing again

------------

As an aside:

You need EITHER the `ln -s` call (to make the `cdk.out` directory appear in the working directory), OR the updating of the `primaryOutputDirectory` (to tell the CodeBuild project that `cdk.out` lives elsewhere).

You do not need to do both.

**Comment by makemefeelgr8** [comment]
I can confirm it doesn't work on 2.5.0.

**Comment by byongwu** [comment]
> You need EITHER the ln -s call (to make the cdk.out directory appear in the working directory), OR the updating of the primaryOutputDirectory (to tell the CodeBuild project that cdk.out lives elsewhere).

Thanks for the feedback. Somehow `ln -s` call did not get executed. Just to let you know that, after the synth call `npx cdk synth`, CodeBuild came out with failure like above. Regardless of adding/removing symlink, it didn't work out for me.

> I can confirm it doesn't work on 2.5.0. I had to run `cdk bootstrap` to fix the issue. Though it said there were no changes, it actually helped.

Good information. I will try with CDK 2.5.0 with the fresh new bootstrapping. FYI, this is the bootstrapping method I am using as [CDK v2 + CodePipeline](https://docs.aws.amazon.com/cdk/v2/guide/cdk_pipeline.html) page informed.
```
export CDK_NEW_BOOTSTRAP=1 
< full >
npx cdk bootstrap aws://ACCOUNT-NUMBER/REGION --profile ADMIN-PROFILE \ --cloudformation-execution-policies arn:aws:iam::aws:policy/AdministratorAccess \ aws://ACCOUNT-ID/REGION
< simple >
cdk bootstrap --cloudformation-execution-policies arn:aws:iam::aws:policy/AdministratorAccess
```

**Comment by byongwu** [comment]
> I can confirm it doesn't work on 2.5.0. I had to run `cdk bootstrap` to fix the issue. Though it said there were no changes, it actually helped.

Awesome. I tried the fresh CDK 2.5.0 and it resolved my issue and correctly got this output.

**Comment by byongwu** [comment]
Thank you, @makemefeelgr8 and @rix0rrr for your time. Case resolved.
