### ISSUE TITLE
IAM scrutiny table column order - proposal

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#1830]
I am proposing that we change the order of the column from:

```
Resource, Effect, Action, Principal, Condition
```

To:

```
Effect, Principal, Action, Resource, Condition
```

To me it reads better: "<allow> <principal> to perform <actions> on <resource> in <condition>"

**Comment by eladb** [comment]
@rix0rrr thoughts?

**Comment by rix0rrr** [comment]
Sounds good.

There is some formatting logic in there which gets rid of horizontal lines for rows in which the `Resource` column is the same. Consider what you want that logic to be and don't forget to adjust the column number.
