### ISSUE TITLE
(cli): Support hotswap for Docker Image Lambda function

### ISSUE THREAD

**Issue by tmokmss** [aws/aws-cdk#18302]
### Description

Support hotswap for [DockerImageFunction](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-lambda.DockerImageFunction.html) code.

### Use Case

Just like normal lambda functions, we can quickly update DockerImageFunction code.

### Proposed Solution

tbw

### Acknowledge

- [x] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by skinny85** [comment]
Thanks for opening the issue @tmokmss! That is indeed a great use case for hotswapping that I totally missed!

**Comment by tmokmss** [comment]
Hi @skinny85, I'm happy to implement this feature but please let me know if you're already working on it. Thanks!

**Comment by skinny85** [comment]
That is great to hear @tmokmss!

Fair word of warning: this will probably be a more complex change than an average Construct Library PR. For reference, take a look at a few PRs that implemented hotswapping for various resources ([here's the original Lambda one](https://github.com/aws/aws-cdk/pull/15748), [here's StepFunctions State Machines](https://github.com/aws/aws-cdk/pull/16489), [here's CodeBuild Projects](https://github.com/aws/aws-cdk/pull/18161)).

Let me know if you'd still be interested in giving this a shot, and if you are, we are happy to leave this one for you 🙂.

Thanks,
Adam

**Comment by tmokmss** [comment]
@skinny85  Thank you for the kind offer! I submitted a PR above. (btw it now also supports InlineCode hotswap for feature completeness 👍 .) 

Although I checked basic behavior in my local env, please teach me if I'm missing any consideration.  I'll add unit tests later.

**Comment by skinny85** [comment]
That's awesome @tmokmss, thanks so much for doing that! I'll check out the PR today.
