### ISSUE TITLE
(aws-rds): Python typing issue with EngineVersion

### ISSUE THREAD

**Issue by blimmer** [aws/aws-cdk#18312]
### What is the problem?

There is a typing error with RDS EngineVersions in the Python version of the CDK.

```
Expected type 'AuroraMysqlEngineVersion', got '() -> AuroraMysqlEngineVersion' instead 
```

I copied this code directly from the example in the docs: https://docs.aws.amazon.com/cdk/api/v1/python/aws_cdk.aws_rds/README.html

### Reproduction Steps

1. Clone https://github.com/blimmer/cdk-bug-reports
2. Check out the `python-db-type-issue` branch
3. Open the code in a Python IDE (e.g., PyCharm)
4. Open the `python_cdk/python_cdk_stack.py` file.

You'll see the type error:

![Screen Shot 2022-01-07 at 10 39 54 AM](https://user-images.githubusercontent.com/630449/148584456-1342b3cb-9f17-4f21-b5c7-768f760d05e1.png)

### What did you expect to happen?

I expected the example from the official documentation (https://docs.aws.amazon.com/cdk/api/v1/python/aws_cdk.aws_rds/README.html) to not have any errors.

### What actually happened?

A type error was displayed:

```
Expected type 'AuroraMysqlEngineVersion', got '() -> AuroraMysqlEngineVersion' instead 
```

### CDK CLI Version

1.138.1 (build 595dee1)

### Framework Version

1.138.1

### Node.js Version

16.x

### OS

MacOS

### Language

Python

### Language Version

Python 3.9

**Comment by peterwoodworth** [comment]
Hey @blimmer, I'm taking a look at this

**Comment by blimmer** [comment]
Thanks @peterwoodworth - I'm around in case you need any more information. I appreciate you having a look!

**Comment by peterwoodworth** [comment]
Hey, I'm not able to reproduce this from cloning your repo. I believe some of your cdk packages may be misaligned; Try resetting your virtual environment/reinstalling your packages

**Comment by skinny85** [comment]
In my experience, `pip` sometimes refuses to update the version of a package used, even if you update it in `requirements.txt` / `setup.py`. You might try running `pip install --upgrade --force`.

**Comment by blimmer** [comment]
Hmm, it looks like the installed versions are all the latest:

```
> pip install --upgrade --force -r requirements.txt
Successfully installed attrs-21.4.0 aws-cdk.assets-1.138.1 aws-cdk.aws-acmpca-1.138.1 aws-cdk.aws-apigateway-1.138.1 aws-cdk.aws-applicationautoscaling-1.138.1 aws-cdk.aws-autoscaling-common-1.138.1 aws-cdk.aws-certificatemanager-1.138.1 aws-cdk.aws-cloudformation-1.138.1 aws-cdk.aws-cloudfront-1.138.1 aws-cdk.aws-cloudwatch-1.138.1 aws-cdk.aws-codeguruprofiler-1.138.1 aws-cdk.aws-codestarnotifications-1.138.1 aws-cdk.aws-cognito-1.138.1 aws-cdk.aws-ec2-1.138.1 aws-cdk.aws-ecr-1.138.1 aws-cdk.aws-ecr-assets-1.138.1 aws-cdk.aws-efs-1.138.1 aws-cdk.aws-elasticloadbalancing-1.138.1 aws-cdk.aws-elasticloadbalancingv2-1.138.1 aws-cdk.aws-events-1.138.1 aws-cdk.aws-globalaccelerator-1.138.1 aws-cdk.aws-iam-1.138.1 aws-cdk.aws-kms-1.138.1 aws-cdk.aws-lambda-1.138.1 aws-cdk.aws-logs-1.138.1 aws-cdk.aws-rds-1.138.1 aws-cdk.aws-route53-1.138.1 aws-cdk.aws-route53-targets-1.138.1 aws-cdk.aws-s3-1.138.1 aws-cdk.aws-s3-assets-1.138.1 aws-cdk.aws-sam-1.138.1 aws-cdk.aws-secretsmanager-1.138.1 aws-cdk.aws-signer-1.138.1 aws-cdk.aws-sns-1.138.1 aws-cdk.aws-sqs-1.138.1 aws-cdk.aws-ssm-1.138.1 aws-cdk.aws-stepfunctions-1.138.1 aws-cdk.cloud-assembly-schema-1.138.1 aws-cdk.core-1.138.1 aws-cdk.custom-resources-1.138.1 aws-cdk.cx-api-1.138.1 aws-cdk.region-info-1.138.1 cattrs-1.10.0 constructs-3.3.182 jsii-1.52.0 publication-0.0.3 python-dateutil-2.8.2 six-1.16.0 typing-extensions-4.0.1
```

@peterwoodworth what IDE are you using? Interestingly, PyCharm is erroring:

<img width="1100" alt="Screen Shot 2022-01-07 at 3 49 27 PM" src="https://user-images.githubusercontent.com/630449/148617189-8f1c5ca7-ed51-481e-823e-3662392fae6e.png">

but VsCode seems to be happy:

<img width="1293" alt="Screen Shot 2022-01-07 at 3 49 46 PM" src="https://user-images.githubusercontent.com/630449/148617217-3c8b671f-cb6e-4e5b-b403-ccf03ac88ac0.png">

This is using the same venv and everything 🤔

**Comment by peterwoodworth** [comment]
Hm, that's strange. I'm using VSCode, I've never used PyCharm before 😬

**Comment by skinny85** [comment]
@blimmer does `cdk synth` fail, or succeed with this code?

**Comment by blimmer** [comment]
It looks to pass. I'm not a python expert, but I think typings only appear in the IDE and don't actually matter at runtime, right?

**Comment by skinny85** [comment]
Can you try the old "Restart + Clear cache" trick, and see if that helps? 🙂

**Comment by blimmer** [comment]
Sadly, I'm still getting the same issue even with that change. My colleague actually brought this issue up in a PR on a separate repository and I reproduced it with a newly `cdk init`-ed application, too. So it feels like this issue is consistent at least in PyCharm.

**Comment by peterwoodworth** [comment]
Everything here is good on our end, so this is probably a Pycharm specific issue. Given that, I'm not sure there's much we can do here to help. Is there anything else you'd like from us here?

**Comment by blimmer** [comment]
Sounds good - I'll close this. Thanks!
