### ISSUE TITLE
(cli): presence of go.work file (Go 1.18 workspaces) leads to error `unknown block type: directory`

### ISSUE THREAD

**Issue by christian-korneck** [aws/aws-cdk#18320]
### What is the problem?

When using Go 1.18 workspaces by creating a `go.work` the CDK cli breaks.

### Reproduction Steps

I'm using Go 1.18 beta 1, which has support for go [multi-module workspaces](https://go.googlesource.com/proposal/+/master/design/45713-workspace.md) (`go.work` file).

I have a project root dir that contains
- a `go.work` file
- a subdir for a CDK go project, bootstrapped with `cdk init --language=go --generate-only`
- a subdir with some other Go code (here: a lambda function referenced in the CDK project via the path `../lambda-func/echo`).

The project root dir does not contain a `go.mod` file. There are two `go.mod` files (in the two subdirs).

```
projectroot
├── go.work
├── cdk-app
│   ├── cdk.json
│   ├── go.mod
│   ├── go.sum
│   ├── snack.go
│   └── snack_test.go
└── lambda-func
    └── echo
        ├── go.mod
        ├── go.sum
        └── main.go
```

The `go.work` file looks like:
```
go 1.18

directory (
    ./cdk-app
    ./lambda-func/echo
)
```

With the presence of this `go.work` file, I can open the project root dir i.e. in Visual Studio Code and don't get any gopls errors, etc because of multiple `go.mod` files in the workspace. (Which is the goal of this project layout).

However, it seems to break the `cdk` cli:

```
$ cd cdk-app
$ cdk synth
reading go.work: /path/to/projectroot/go.work:3: unknown block type: directory
Subprocess exited with error 1
```

Removing `go.work` leads to regular behaviour (but, of course, breaks Go workspaces in the toolchain/IDE).
```
$ mv ../go.work ../go.work.backup
$ cdk synth
< ... regular output ... >
```

I'm currently helping myself with an alias in my .bashrc like below, but that's a really incomplete and problematic one (while a cdk synth runs my IDE's starts to show errors due to the missing `go.work` file)
```bash
cdkw() {
    mv ../go.work ../go.work.backup 2>/dev/null
    cdk $@
    cdkexitcode=$?
    mv ../go.work.backup ../go.work 2>/dev/null
    return $cdkexitcode

```

### What did you expect to happen?

That CDK CLI doesn't break with Go workspaces.

### What actually happened?

```
$ ls ../go.work
go.work
$ cdk synth
reading go.work: /path/to/projectroot/go.work:3: unknown block type: directory
Subprocess exited with error 1
```

### CDK CLI Version

2.4.0 (build 993f14d)

### Node.js Version

v14.17.6

### OS

macOS 12.0.1 build 21A559

### Language

Go

### Language Version

Go 1.18 beta1

### Other information

-

**Comment by RomainMuller** [comment]
What is generating this error (`reading go.work: /path/to/projectroot/go.work:3: unknown block type: directory`)? Is this somehow `go`? Or is `cdk` somehow trying to process this file for some reason?
