### ISSUE TITLE
(cli): replace colors.js with chalk

### ISSUE THREAD

**Issue by blimmer** [aws/aws-cdk#18329]
### Description

A recent publish of `colors.js` is causing problems for a lot of software projects, including aws-cdk (see https://github.com/aws/aws-cdk/issues/18322, https://github.com/aws/aws-cdk/issues/18323, and https://github.com/aws/aws-cdk/pull/18324). The author of colors.js seems to be in crisis right now, and relying on their projects is risky.

Migrating from colors.js to [chalk](https://github.com/chalk/chalk) is probably a good idea to reduce risk for aws-cdk users.

### Use Case

For folks who do not pin `aws-cdk` (e.g., those who install globally or use `npx` to run), they could accidentally get one of the broken versions of colors.js.

### Proposed Solution

`colors` is replaced with `chalk` and remove from `dependencies` of `aws-cdk/package.json`

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by fourhundredfour** [comment]
I completely agree that the change should be made, however, it is not as critical as it is portrayed here.

There is a `yarn.lock` file in which among other things the hash is locked as well as the version number.

Also a hotfix was published. See https://github.com/aws/aws-cdk/pull/18324

**Comment by jumic** [comment]
colors.js was replaced with chalk in #18363.
@peterwoodworth I think this issue can be closed. Thanks.
