### ISSUE TITLE
(aws-cdk/lib): change init template file extensions

### ISSUE THREAD

**Issue by strongishllama** [aws/aws-cdk#18332]
### Description

Currently, the init templates for the Golang sample app are being picked up by various tools, ```gopls``` and ```gosec``` for example. I believe this is because the file extension ends in ```.go```.

### Use Case

This is a (minor) issue because for every project that uses these tools you have to configure them all individually to ignore the directory that contains these files.

### Proposed Solution

Would it be possible to change it to something else, ```.tmpl``` or ```.template``` for example?

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by njlynch** [comment]
Can you provide a bit more detail? When working with a CDK Go project, the included template files from within the CDK itself are being flagged? Is that correct?

We _could_ theoretically change all of the init templates to end in `.template` instead of `.template.ext`; some research would need to be done to ensure none of the rest of the init code relies on the file extension for anything else.

**Comment by strongishllama** [comment]
@njlynch Sorry I should have given a better explanation. So a typical folder structure might look like this.
```
├── .github/
├── bin/
├── go.mod
├── internal/
├── lambdas/
├── lib/
├── node_modules/
└── package.json
```
You have the standard CDK ```bin/```,  ```lib/``` and ```node_modules/``` directories. Then ```internal/``` and ```lambdas/``` contain the Golang code for the Lambda functions. There is also a ```go.mod``` file at the top level so all the Lambdas can share the same dependencies.

The issue arises when you run commands like ```go test```, ```gopls``` or ```gosec``` from the root of the project because it will also traverse down the ```node_modules/``` directory and pickup the template Golang CDK files because they have the ```.go``` extension. Then because these files aren't valid Golang the tools throw errors.

Some of these tools there are work arounds such as ignoring specific directories, but other tools don't have this ability.
