### ISSUE TITLE
(assertions): Add ability to read Annotations

### ISSUE THREAD

**Issue by dontirun** [aws/aws-cdk#18347]
### Description

Add the ability to read and validate against Annotations with the the assertions

### Use Case

The `@aws-cdk/assert` module has the ability to read messages of stack using `SynthUtils`. This is helpful when trying to validate that there are no errors/warnings in the stack, especially when using Aspects to apply annotations

```typescript
test('Example', () => {
  const stack = new Stack();
  // Aspects.of(stack).add(new MyAspect());
  Annotations.of(stack).addError('MyError')
  const messages = SynthUtils.synthesize(stack).messages;
  expect(messages).not.toContainEqual(
    expect.objectContaining({
      entry: expect.objectContaining({
        data: expect.stringContaining(
          'MyError',
        ),
      }),
    }),
  );
});

```

### Proposed Solution

It would be nice to have something like
`assertions.Annotations.of(stack)`   
`assertions.Annotations.of(app)`

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by kaizen3031593** [comment]
Labeling this as p2 for now, going to wait and see if this is something users want. As always we measure interest via +1s.
