### ISSUE TITLE
(opensearch): domain should throw error if both accessPolicies and useUnsignedBasicAuth are set

### ISSUE THREAD

**Issue by qoomon** [aws/aws-cdk#18343]
### General Issue

security concern DomainProps.useUnsignedBasicAuth implicitly negate accessPolicies

### The Question

Following code, to create an OpenSearch `Domain`, will result in two accessPolicies. First one is explicitly defined with an `aws:SourceIp` condition, the second one is created implicitly by `useUnsignedBasicAuth: true`, however this will negate the explicitly  defined policy. 
```js
new Domain(this, 'Domain', {
            version: EngineVersion.OPENSEARCH_1_0,
            useUnsignedBasicAuth: true,
            accessPolicies: [new PolicyStatement({
                effect: Effect.Allow,
                actions: ['es:ESHttp*'],
                resources: ['*'],
                principals: [new ArnPrincipal('*')],
                conditions: {
                   IpAddress: {
                        'aws:SourceIp': TRUSTED_IP_CIDR
                    }
                }
            })],
        })
```

I think this is a security issue, because this behaviour negates DomainProps.accessPolicies and leads to allow access for everyone.

### Solution Proposal
If `accessPolicies` is not empty do not concat `unsignedAccessPolicy` see [@aws-cdk/aws-opensearchservice/lib/domain.ts:1658](https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-opensearchservice/lib/domain.ts#L1658)

### CDK CLI Version

2.5.0

### Language

Typescript

**Comment by kaizen3031593** [comment]
From the [README](https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-opensearchservice/README.md#L20):

>For convenience, the domain can be configured to allow unsigned HTTP requests
that use basic auth. Unless the domain is configured to be part of a VPC this
means anyone can access the domain using the configured master username and
password.
>
>To enable unsigned basic auth access the domain is configured with an access
policy that allows anyonmous requests, HTTPS required, node to node encryption,
encryption at rest and fine grained access control.
>
>If the above settings are not set they will be configured as part of enabling
unsigned basic auth. If they are set with conflicting values, an error will be
thrown.

I don't see a security issue here. Setting `useUnsignedBasicAuth` to true means everyone can access.
At best, it might make sense to throw an error if `DomainProps.accessPolicies` is set, so there's no confusion.
Repurposing this issue into that.

**Comment by qoomon** [comment]
> Setting useUnsignedBasicAuth to true means everyone can access.
That might be a good default, however how to setup an unsigned access for just a subset of `es:ESHttp*` actions or with a condition like `IpAddress` filter (see my example). Therefore I think there should be at least an option to prevent adding this default `unsignedAccessPolicy`
