### ISSUE TITLE
(cli): optionally use current AWS credentials with new-style synthesis

### ISSUE THREAD

**Issue by joel-aws** [aws/aws-cdk#18350]
### Description

Add the ability to use the current AWS credentials with new-style stack synthesis instead of assuming the roles created by the Modern Bootstrapping Template.

I can get this behavior by setting ARNs in a custom [`DefaultStackSynthesizer`](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_core.DefaultStackSynthesizer.html) to non-assumable/existent roles, which then defaults to the current credentials. This, however, does not work for the `CloudFormationExecutionRole`; the work-around there is to set the role to `undefined` in `aws-cdk/lib/api/cloudformation-deployments.ts`. Clearly, this is not ideal.

### Use Case

In some enterprise environments, roles are created and scoped for tasks. Those roles are not always allowed to perform other actions, like creating roles that can create roles (e.g., `CloudFormationExecutionRole` would try to create additional roles while deploying resources).

This feature would enable local-development/deployments to continue with CDK v2, like in v1. It should be noted, though, that such a configuration would **not** work with advanced features like CDK Pipelines.

### Proposed Solution

Being able to use a [custom Synthesizer](https://docs.aws.amazon.com/cdk/v2/guide/bootstrapping.html#bootstrapping-custom-synth), like below, where one could set the ARNs of roles to `None` (or something else?) to use the current AWS credentials instead of the roles created by the Modern Bootstrapping Template.

```python
from monocdk import DefaultStackSynthesizer

def get_custom_stack_synthesizer() -> DefaultStackSynthesizer:
    return DefaultStackSynthesizer(
        [...]
        deploy_role_arn=None,
        file_asset_publishing_role_arn=None,,
        image_asset_publishing_role_arn=None,
        cloud_formation_execution_role=None,
    )
```

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by skinny85** [comment]
@rix0rrr this is needed for some edge cases in the isolated/restricted regions.

**Comment by rix0rrr** [comment]
I will try and make this nicer. In the mean time, [`LegacyStackSynthesizer`](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.LegacyStackSynthesizer.html) will probably give you what you need
