### ISSUE TITLE
(aws-ec2): Nat Instance & Elastic IP association

### ISSUE THREAD

**Issue by geoff192** [aws/aws-cdk#18353]
### General Issue

Unable to Associate NAT Instance with Elastic IP

### The Question

I believe there's a limitation to associate Elastic IPs with NAT Instances.

### Documentation Link

https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-ec2.NatProvider.html#static-instanceprops

### Issue

I created a NAT instance using AWS CDK.

```
const nat_instance_provider = ec2.NatProvider.instance({
    instanceType: new ec2.InstanceType('t3.micro')
});
```

Then I created an elastic IP.

```
const elastic_ip = new ec2.CfnEIP(this, "elastic_ip");
```

Now I need to associate the EC2 instance with the Elastic IP.

```
let ec2Assoc = new ec2.CfnEIPAssociation(this, "Ec2Association", {
   eip: elastic_ip.ref,
   instanceId: <EC2 ID> ???
});
```

The issue I'm facing is that so far I couldn't find a way to get the instance ID and I feel this is a limitation or missing documentation but I might be missing something.

### CDK CLI Version

1.131.0 (build 7560c79)

### Language

Typescript

**Comment by peterwoodworth** [comment]
Hey @geoff192,

The [configuredGateways](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-ec2.NatInstanceProvider.html#configuredgateways) prop on `nat_instance_provider` should return the instance id on the `gatewayId` property of each instance it created. Have you tried this out?

**Comment by WinterYukky** [comment]
It's just as @peterwoodworth described it.

This is my solution.
```typescript
const natGatewayProvider = new ec2.NatInstanceProvider({ /** your props */})

const vpc = new ec2.Vpc(this, 'VPC', {
  natGatewayProvider,
})
   
// you can add EIP after give VPC the NAT Instance
natGatewayProvider.configuredGateways.map(
  (nat, index) =>
    new ec2.CfnEIP(this, `NatEIP${index + 1}`, {
      instanceId: nat.gatewayId,
      tags: [
        { key: 'Name', value: `NatInstanceEIP${index + 1}` },
      ],
    })
)
```
