### ISSUE TITLE
msk: add bootstrapBrokersSaslIam

### ISSUE THREAD

**Issue by jfpolly** [aws/aws-cdk#18355]
### Description

Currently @aws-cdk/aws-msk-alpha package supports:
* `bootstrapBrokers`
* `bootstrapBrokersTls`
* `bootstrapBrokersSaslScram`

Please add support for a new property
* `bootstrapBrokersSaslIAM`

### Use Case

In the case where the Kafka cluster is configured using Sasl with IAM, e.g.:

```ts
new msk.Cluster(this, `${tenantName}KafkaCluster`, {
      clusterName: "MyKafkaCluster",
      kafkaVersion: msk.KafkaVersion.V2_8_1,
      vpc: vpc,
      instanceType: new aws_ec2.InstanceType("t3.small"),
      clientAuthentication: msk.ClientAuthentication.sasl({ iam: true })
    });
```

It is currently not possible to access the bootstrap brokers directly as a property of the Kafka cluster.

### Proposed Solution

The `Cluster` class of `aws-msk-alpha` contains a private method `_bootstrapBrokers`. The other public bootstrapBroker* functions are defined in relation to this function:

```ts
    get bootstrapBrokers() {
        return this._bootstrapBrokers('BootstrapBrokerString');
    }
// ...
    get bootstrapBrokersTls() {
        return this._bootstrapBrokers('BootstrapBrokerStringTls');
    }
// ...
    get bootstrapBrokersSaslScram() {
        return this._bootstrapBrokers('BootstrapBrokerStringSaslScram');
    }
// ...
```

A similar function can be defined for SaslIam:

```ts
    get bootstrapBrokersSaslIam() {
        return this._bootstrapBrokers('BootstrapBrokerStringSaslIam');
    }
```

### Other information

When accessing the bootstrap brokers of a cluster configured with property 

```ts 
clientAuthentication: msk.ClientAuthentication.sasl({ iam: true })
```

One can access the bootstrap brokers from the command line:

```bash
aws kafka get-bootstrap-brokers --cluster-arn <ClusterArn>
```

This will return an object:

```json
{
    "BootstrapBrokerStringSaslIam": "..."
}
```

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by epretha** [comment]
Hi,
     Can someone confirm if this feature is implemented for msk ?
Because, today when I ran the command 
`aws kafka get-bootstrap-brokers --cluster-arn <myclusterArn>`
it returns nothing. 
Though in the AWS Management Console, under "View client information", I could see some broker URLs with the Authentication Type set to IAM.

Thanks.

**Comment by svyatogor** [comment]
I just ran today:

```
aws kafka get-bootstrap-brokers --cluster-arn arn:aws:kafka:eu-central-1:******:cluster/msk/******** --region eu-central-1
{
    "BootstrapBrokerStringSaslIam": "****:9098,*****:9098"
}
```
