### ISSUE TITLE
@aws-cdk/aws-s3: EventType does not contain enums for s3:ObjectTagging:*

### ISSUE THREAD

**Issue by cvwjensen** [aws/aws-cdk#18362]
### What is the problem?

EventType does not contain enums for s3:ObjectTagging:* making it impossible to trigger Lambda when an object is tagged.

The documentation states that this should be possible: https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-s3.EventType.html#object_tagging_put

### Reproduction Steps

N/A

### What did you expect to happen?

I can use EventType.OBJECT_TAGGING like I use EventType.OBJECT_CREATED

### What actually happened?

enum not available

### CDK CLI Version

1.138.2 (build 0dea806)

### Node.js Version

all

### OS

all

### Language

Typescript

### Language Version

all

**Comment by RigoIce** [comment]
Hi all. I just checked that and I'm pretty sure it was introduced in the course of #18013 as the object tagging is available for me in CDK 1.37.0 and 2.4.

@cvwjensen could you please check your project's dependencies in the package.json to have at least 1.37.0 configured and installed? This could differ from the CDK CLI version. Maybe this already solves the problem for you quickly. :-)

**Comment by cvwjensen** [comment]
I'm SO sorry for raising false alarm. I forgot to upgrade my package.json from 1.131.0 to 1.38.2. In 1.138.2 it is present.
