### ISSUE TITLE
(redshift): tags not applied to cluster

### ISSUE THREAD

**Issue by njlynch** [aws/aws-cdk#18360]
### What is the problem?

(Copied from https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/999 on behalf of @xdiegoro):

When creating for Redshift cluster via CDK , the CFN template is not getting the tags. Tags are applied when using native cfn but not when using CDK.

In the cdk stack (CDK v2.1) a redshift-subnetgroup, redshift-parametergroup and a redshift-cluster are created ( using @aws-cdk/aws-redshift-alpha library). The tags defined in the cdk-stack are to found after deployment on the cloudformation stack itself, on the redshift parametergroup and on the redshift subnetgroup, but not on the redshift cluster.

### Reproduction Steps

TBD

### What did you expect to happen?

The cluster is tagged.

### What actually happened?

The cluster was not.

### CDK CLI Version

2.1.0

### Node.js Version

?

### OS

?

### Language

Typescript

### Other information

Copied from https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/999

**Comment by njlynch** [comment]
@xdiegoro and @pepdekpd -- 

Can you please provide a reproducible example for the above? I so far have been unable to reproduce; the cluster is tagged appropriately in each instance.

As an example:

```ts
    new redshift.Cluster(this, 'Cluster', {
      vpc: vpc,
      vpcSubnets: {
        subnetType: ec2.SubnetType.PUBLIC,
      },
      masterUser: {
        masterUsername: 'admin',
      },
      defaultDatabaseName: 'tmp_foo',
    });
    Tags.of(this).add('myTagName', 'myTagValue');
```

**Comment by pepdekpd** [comment]
Passing tags to cfn like this:
```
const tags: any = {
  Example: "ExampleValue"
};

// ----- VPC Stack
const vpcDemoStack = new VpcStack(app, `${NamePrefix}vpc-${environmentAbbr}`, {
  description: "Creates a vpc to host a redshift cluster",
  env: env,
  tags: tags,
  stage: stage,
});

// ----- Redshift Stack
const redshiftDemoStack = new RedshiftClusterStack(app, `${NamePrefix}redshift-${environmentAbbr}`, {
  description: "Creates a redshift subnetgroup, parametergroup and cluster",
  env: env,
  vpc: vpcDemoStack.vpc,
  tags: tags,
  stage: stage,
});
```

and here is the code for RedshiftClusterStack
```
import * as cdk from "aws-cdk-lib";
import { Construct } from "constructs";
import { aws_ec2 as ec2 } from "aws-cdk-lib";
import { aws_iam as iam } from "aws-cdk-lib";
import { aws_redshift as redshift } from "aws-cdk-lib";
import * as redshift_alpha from "@aws-cdk/aws-redshift-alpha";

export interface RedshiftClusterStackProps extends cdk.StackProps {
  description: string;
  vpc: ec2.IVpc;
  stage: string;
}

export class RedshiftClusterStack extends cdk.Stack {
  
  constructor(scope: Construct, id: string, props: RedshiftClusterStackProps) {
    super(scope, id, props);

    const tags = this.tags.renderTags() as { Key: string; Value: string }[];

    const resourcePrefix = 'demo-';

    //    const resourcePrefix = `${resourcePrefixOrg}producer-` as string;
    const environmentAbbr = 'dev';
    const database = 'dev';
    const clusterType = 'single-node';
    const nodeType = 'dc2.large';
    const numberOfNodes = 1;
    const portNumber = 5439;
    const snapshotRetention = 1;
    const clusterName = `${resourcePrefix}` + `${environmentAbbr}`;


    //no dash "-" in redshift username allowed, replace with underscore "_"
    const rootUserName = `${resourcePrefix}`.replace("-", "_") + "admin_" + `${environmentAbbr}`;

    // ---- create a custom cluster parametergroup
    const customRedshiftClusterParameterGroup = new redshift_alpha.ClusterParameterGroup(
      this,
      `${resourcePrefix}` + "parametergroup-" + `${environmentAbbr}`,
      {
        parameters: {
          // enable auditting
          enable_user_activity_logging: "false",
          // enable ssl_mode
          require_ssl: "true",
        },
        description: "parametergroup for cluster: " + `${clusterName}`,
      }
    );



    const redshiftSubnets = props.vpc.selectSubnets({ onePerAz: true, subnetType: ec2.SubnetType.PRIVATE_ISOLATED });

    // ---- Create a clustersubnetgroup
    const clusterSubnetGroup = new redshift_alpha.ClusterSubnetGroup(
      this,
      `${resourcePrefix}` + "redshift-subnetgroup-" + `${environmentAbbr}`,
      {
        description: `"Cluster subnetgroup for "${clusterName}`,
        vpc: props.vpc,
        vpcSubnets: redshiftSubnets,
        removalPolicy: cdk.RemovalPolicy.DESTROY,
      }
    );

    // ---- create a cluster security group
    const clusterSecurityGroup = new ec2.SecurityGroup(
      this,
      `${resourcePrefix}` + "redshift-securitygroup-" + `${environmentAbbr}`,
      {
        allowAllOutbound: true,
        vpc: props.vpc,
        securityGroupName: `${resourcePrefix}` + "redshift-securitygroup-" + `${environmentAbbr}`,
      }
    );

      // ---- Create role for redshift, and use the same for redshift scheduler
      const redshiftServiceRole = new iam.Role(this, `${resourcePrefix}` + "redshift-" + `${environmentAbbr}`, {
        roleName: `${resourcePrefix}` + "redshift-" + `${environmentAbbr}`,
        assumedBy: new iam.CompositePrincipal(
          new iam.ServicePrincipal("redshift.amazonaws.com"),
          new iam.ServicePrincipal("scheduler.redshift.amazonaws.com")
        )
      });


    // ---- redshift cluster properties
    const clusterProps: any = {
      masterUser: {
        masterUsername: `${rootUserName}`,
      },
      clusterName: `${clusterName}`,
      clusterType: `${clusterType}`,
      defaultDatabaseName: `${database}`,
      encrypted: true,
      automatedsnapshotretentionperiod: snapshotRetention,
      nodeType: nodeType,
      numberOfNodes: numberOfNodes,
      parameterGroup: customRedshiftClusterParameterGroup,
      port: portNumber,
      publiclyAccesible: false,
      removalPolicy: cdk.RemovalPolicy.DESTROY,
      roles: [redshiftServiceRole],
      subnetGroup: clusterSubnetGroup,
      securityGroups: [clusterSecurityGroup],
      vpc: props.vpc,
    };

    // ---- Create a redshift cluster
    const cluster = new redshift_alpha.Cluster(this, `${resourcePrefix}` + `${environmentAbbr}`, clusterProps);


    /**
     * Stack outputs
     */

    new cdk.CfnOutput(this, `${resourcePrefix}` + "cfn-username-" + `${environmentAbbr}`, {
      description: `${clusterName}` + " redshift cluster username",
      value: rootUserName,
    });

    new cdk.CfnOutput(this, `${resourcePrefix}` + "cfn-database-" + `${environmentAbbr}`, {
      description: `${clusterName}` + " redshift cluster database",
      value: database,
    });

    new cdk.CfnOutput(this, `${resourcePrefix}` + "cfn-parametergroup-" + `${environmentAbbr}`, {
      description: "parameterGroup",
      value: customRedshiftClusterParameterGroup.toString(),
    });

    new cdk.CfnOutput(this, `${resourcePrefix}` + "cfn-cluster-endpoint-host-" + `${environmentAbbr}`, {
      description: "clusterEndpointHost",
      value: cluster.clusterEndpoint.hostname,
    });

    new cdk.CfnOutput(this, `${resourcePrefix}` + "cfn-cluster-endpoint-address-" + `${environmentAbbr}`, {
      description: "clusterEndpointAddress",
      value: cluster.clusterEndpoint.socketAddress,
    });
  }
}
```

This will result in a redshift subnetgroup and paametergroup with the appropiate tag, but the cluster itself is without tags.

Kind Regards,

Pepijn

**Comment by njlynch** [comment]
Thanks for the reproduction code, @pepdekpd .

I'm not seeing where in the above example you're actually tagging your resources.

I see you passing tags to the stack:

```ts
// ----- Redshift Stack
const redshiftDemoStack = new RedshiftClusterStack(app, `${NamePrefix}redshift-${environmentAbbr}`, {
  description: "Creates a redshift subnetgroup, parametergroup and cluster",
  env: env,
  vpc: vpcDemoStack.vpc,
  tags: tags,
  stage: stage,
});
```

... and you referencing those tags within the stack:
```ts
const tags = this.tags.renderTags() as { Key: string; Value: string }[];
```

But that `tags` variable appears completely unused in your above reproduction. At some point, somewhere, you should be doing something like `Tags.of(this).add(...)` to add the tags to a specific scope/construct. I'm not seeing that anywhere in your reproduction.

**Comment by pepdekpd** [comment]
Thank @Njlynch for looking into this. You need to bare a little patience with me, I am not very experienced, as you saw...
The funny thing though is that the tags are created on redshift subnetgroup and redshift parametergroup which in my opinion are created in exactly the same manner as the redshift cluster in the same example code.So I was thinking that they weren't on the cluster was wrong. So why are the tags created there? Is that a fluke?

**Comment by njlynch** [comment]
> The funny thing though is that the tags are created on redshift subnetgroup and redshift parametergroup which in my opinion are created in exactly the same manner as the redshift cluster in the same example code.So I was thinking that they weren't on the cluster was wrong. So why are the tags created there? Is that a fluke?

I honestly have no idea. Is it possible the Tags were added by some other part of the code, or manually?

I tried reproducing with your above code, and the tags passed into the stack do not appear anywhere in the output of `cdk synth`; there is nothing in the RedshiftStack that is tagging anything, so the tags must have been added somewhere/somehow else.

In any case, if you add the code above (e.g., `Tags.of(this).add(...)`) to the stack, it will tag everything (that's taggable) within the stack. 

Closing this out, but feel free to comment and mention me if you have follow-ups.

**Comment by pepdekpd** [comment]
> > The funny thing though is that the tags are created on redshift subnetgroup and redshift parametergroup which in my opinion are created in exactly the same manner as the redshift cluster in the same example code.So I was thinking that they weren't on the cluster was wrong. So why are the tags created there? Is that a fluke?
> 
> I honestly have no idea. Is it possible the Tags were added by some other part of the code, or manually?
> 
> I tried reproducing with your above code, and the tags passed into the stack do not appear anywhere in the output of `cdk synth`; there is nothing in the RedshiftStack that is tagging anything, so the tags must have been added somewhere/somehow else.
> 
> In any case, if you add the code above (e.g., `Tags.of(this).add(...)`) to the stack, it will tag everything (that's taggable) within the stack.
> 
> Closing this out, but feel free to comment and mention me if you have follow-ups.

@njlynch I think it has to do with this:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-resource-tags.html

The tag is created on the cloudformation stack itself and then automatically propagated to the subnetgroup and parametergroup resources in the stack. But apparently the cluster resource is not (yet?) supported as a tag propagation resource, as I read here not all resources are supported:
"
All stack-level tags, including automatically created tags, are propagated to resources *that CloudFormation supports*. "

That might also explain why this issue started as a cloudformation issue after I created a support ticket for it.

Learning a lot today...
