### ISSUE TITLE
(pipelines): v1 Cloud Assembly Schema version bumps break pipelines until v2 CDK CLI is released

### ISSUE THREAD

**Issue by misterjoshua** [aws/aws-cdk#18370]
### What is the problem?

v1.139.0 synthesizes Cloud Assembly Schema Version 16.0.0, but the latest CLI doesn't support it. In CDK Pipelines, without explicitly setting `cliVersion: '1'`, the self-mutation step currently fails.

![image](https://user-images.githubusercontent.com/644092/149074980-574d1991-91aa-4896-b072-4d37a77b1c86.png)

I'm sure that v2's CLI will be released soon, but given that the latest CLI may continue to be released out of step with (and later than) v1 schema version bumps, I wonder if many Pipelines users will get caught by this issue whenever v1 gets the schema bump first, like until the user sets cliVersion explicitly.

### Reproduction Steps

https://cdk-dev.slack.com/archives/C018XT6REKT/p1641967038204400?thread_ts=1641940855.193800&cid=C018XT6REKT

### What did you expect to happen?

Pipelines should use CDK CLI v1 to self-mutate.

### What actually happened?

Pipelines used CDK CLI v2 (latest) which doesn't yet support the latest Cloud Assembly Schema Version, so it threw an error.

### CDK CLI Version

2.5.0

### Framework Version

1.139.0

### Node.js Version

N/A

### OS

Linux

### Language

Typescript

### Language Version

TypeScript (4.5.4)

### Other information

Would it make the user's life easier if the Pipelines construct defaulted cliVersion to "1" rather than blank when synthesizing a v1 app? The changes would be here:

https://github.com/aws/aws-cdk/blob/e23b63fc106c4781e3dd39a16d4a3e3c81bdd874/packages/%40aws-cdk/pipelines/lib/codepipeline/codepipeline.ts#L606

https://github.com/aws/aws-cdk/blob/e23b63fc106c4781e3dd39a16d4a3e3c81bdd874/packages/%40aws-cdk/pipelines/lib/codepipeline/codepipeline.ts#L652

**Comment by polothy** [comment]
@rix0rrr and CDK team friends - it would be helpful to make it clear if CDK CLI v2 is supposed to work with CDK v1 Apps. When I read the "CDK Toolkit compatibility" section of the [migration doc](https://docs.aws.amazon.com/cdk/v2/guide/migrating-v2.html), I thought CDK CLI v2 could work with either v1 or v2 CDK apps (I could be totally wrong 😄).  Thanks for you help on this! 🍻

**Comment by rix0rrr** [comment]
Yes, CLIv2 works with v1 apps. It's just that the way our release train works, the statement "the CLI must have equal version or higher" becomes a bit inscrutable. 

This situation is an artifact of us still supporting (and developing on) v1 for the next 6 months. Once we drop support for v1, all future changes will go into v2 directly and any inconsistency windows will disappear.

![image](https://user-images.githubusercontent.com/524162/149303416-68ab6c1d-a71f-4f79-8b3a-e2ddfd1bbaac.png)
