### ISSUE TITLE
Feature request - specify cfn service role in stack properties instead of just by CLI

### ISSUE THREAD

**Issue by akdor1154** [aws/aws-cdk#1838]
Currently I can do
`cdk deploy stack --role-arn [role arn]`.

It would be more useful for my use case if I could instead specify this when the stack is defined in an app:
`new Stack(app, 'stack id', {env: {...}, role_arn: [role arn]});`

My use case involves a fair bit of cross account stuff, and having to work out what account I am in before the CLI (to compute the service role arn) is called is not desirable.

Would this be considered?

**Comment by rix0rrr** [comment]
It's a good point, and something we've definitely considered for environments.

At least one other ticket about this is https://github.com/awslabs/aws-cdk/issues/290.
