### ISSUE TITLE
(aws-cdk-lib): h2 and h3s in comment break auto-docs

### ISSUE THREAD

**Issue by douglasnaphas** [aws/aws-cdk#18388]
### link to reference doc page

https://docs.aws.amazon.com/cdk/api/v2//docs/aws-cdk-lib.Stack.html#example-1

### Describe your issue?

There is a method comment for `Stack.exportValue`. It has an example. The method comment introduces the example with an h2 `## Example` and h3s `### Deployment 1: break the relationship` and `### Deployment 2: remove the bucket resource`. This makes the docs come out wrong. Because, I believe, the process of translating method comments into docs puts _Methods_ at an h2 level, the docs show the example for `Stack.exportValue` at the same level as the methods for the whole Stack class. So the document structure is wrong, as can be seen in the attached screenshots.

![Screen Shot 2022-01-12 at 4 57 10 PM](https://user-images.githubusercontent.com/5433410/149229998-1937d93e-3ad9-436d-b6ec-d54b57dec376.png)

![Screen Shot 2022-01-12 at 5 09 25 PM](https://user-images.githubusercontent.com/5433410/149230944-b04656f2-9d25-47be-99bb-fd5db3ccc211.png)

Notice how _Example_ is at the same level in the tree as _Methods_, when really _Example_ should be beneath `exportValue`, or not shown at all in the document tree.

This might be fixed by changing `## Example` [here](https://github.com/aws/aws-cdk/blob/77144f5a1072feea7409b4222fbc80bd2bc86e71/packages/%40aws-cdk/core/lib/stack.ts#L863) to `#### Examples`, so that it's properly shown beneath [`exportValue`](https://github.com/aws/aws-cdk/blob/77144f5a1072feea7409b4222fbc80bd2bc86e71/packages/%40aws-cdk/core/lib/stack.ts#L891), and then changing [`### Deployment 1: break the relationship`](https://github.com/aws/aws-cdk/blob/77144f5a1072feea7409b4222fbc80bd2bc86e71/packages/%40aws-cdk/core/lib/stack.ts#L875) to `##### Deployment 1: break the relationship` and [`### Deployment 2: remove the bucket resource`](https://github.com/aws/aws-cdk/blob/77144f5a1072feea7409b4222fbc80bd2bc86e71/packages/%40aws-cdk/core/lib/stack.ts#L885) to `##### Deployment 2: remove the bucket resource`.

**Comment by njlynch** [comment]
Thanks for pointing this out! I agree we could either downlevel the headings, but it's probably better to just replace the markdown-style headings with something else entirely, so we don't conflict with the generated docs' overall layout. 

We welcome community contributions! If you are able, we encourage you to [contribute](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md).

**Comment by comcalvi** [comment]
Looks like this has been fixed
