### ISSUE TITLE
stack: inline markdown headers introduces misleading "Example" section in right-side navigation 

### ISSUE THREAD

**Issue by tranhl** [aws/aws-cdk#18401]
### link to reference doc page

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.Stack.html#example-1

### Describe your issue?

Problem as per title describes. Screenshot provided for reference. Notice how there's an "Example" section halfway through the "Methods" section, and then two more subsections after "Example" ("Deployment 1: break the relationship"
 & "Deployment 2: remove the bucket resource"). I believe this to be caused by incorrect markdown header levels in the docs.

![Screenshot 2022-01-13 at 21-40-09 class Stack (construct) · AWS CDK](https://user-images.githubusercontent.com/24240419/149315247-5b4041ea-fde2-4ed5-8ebb-68865f2a0226.png)

**Comment by otaviomacedo** [comment]
Re-assigning to @rix0rrr, who has more context on this.
