### ISSUE TITLE
aws-iam: Wrong type for conditions

### ISSUE THREAD

**Issue by tebatalla** [aws/aws-cdk#18415]
### What is the problem?

The type for `conditions` in [`policy-statement`](https://github.com/aws/aws-cdk/blob/a684ff47d56038a94c82cdbad9588da939963351/packages/%40aws-cdk/aws-iam/lib/policy-statement.ts#L582) does not correctly narrow valid types. Per that type, the following two types are valid per the typescript checker:

```ts
type Condition = { [key: string]: any }

const isCondition: Condition = [
           {
             ArnEquals: {
               "aws:SourceArn": "xyz",
             },
           },
         ];

const alsoValidCondition: Condition = 
           {
             ArnEquals: {
               "aws:SourceArn": "xyz",
             },
           };
 ```
 
 Per cloudformation docs, the array should not be valid input: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/conditions-section-structure.html#conditions-section-structure-syntax
 
 Typescript playground [example](https://www.typescriptlang.org/play?#code/C4TwDgpgBAwg9gOwCYEtgsVAvFA3lAbQGsIQAuKAZ2ACcUEBzAXQoEMEQoBfAKB4GNE1KCkrxkaDAgrjU6TDgI8oK1WrzL1WqAEEaCAKIBHAK6sANpQq5N2rQCJWAdysBlOCZr8IehPYr2AB4gAF72ADS2dipckdExcXZMANx8ggjCFpRwAGoWKEiykogyiHJS2FBR2jbxqr7GZpbW1fGOLmTunt6+-lBBoRGt2rHDalzJQA)

### Reproduction Steps

 Typescript playground [example](https://www.typescriptlang.org/play?#code/C4TwDgpgBAwg9gOwCYEtgsVAvFA3lAbQGsIQAuKAZ2ACcUEBzAXQoEMEQoBfAKB4GNE1KCkrxkaDAgrjU6TDgI8oK1WrzL1WqAEEaCAKIBHAK6sANpQq5N2rQCJWAdysBlOCZr8IehPYr2AB4gAF72ADS2dipckdExcXZMANx8ggjCFpRwAGoWKEiykogyiHJS2FBR2jbxqr7GZpbW1fGOLmTunt6+-lBBoRGt2rHDalzJQA)

### What did you expect to happen?

I expect the typescript parser to cause an error.

### What actually happened?

Typescript parser did not error and got runtime error when deploying to cloudformation.

### CDK CLI Version

1.128.0

### Node.js Version

14

### OS

Mac & Linux

### Language

Typescript

### Other information

Narrowing to this type would solve the issue:

```
type Condition = { [key: string]: { [key: string]: any } }
```

**Comment by rix0rrr** [comment]
You are very correct. I don't understand why the second type precludes the array but the first one doesn't.  I suppose it has to be the array's methods?

This is actually an issue everywhere we use `Record<string, X>` (which we do in quite a lot of places), and pretty sure we can't change this anymore anyway because of jsii concerns. 

I'm going to close this and say the type declaration serves as human documentation moreso than an enforcement. Disappointing, I know.
