### ISSUE TITLE
(aws_cdk.aws_lambda): The python typing has errors for almost all of the cdk examples, pycharm lights up like a christmas tree of type errors

### ISSUE THREAD

**Issue by mcsheehan** [aws/aws-cdk#18417]
### What is the problem?

There are a number of items in the python cdk, which have incorrect typing information, which is flagged immediately upon opening the examples in pycharm. https://github.com/aws-samples/aws-cdk-examples/tree/master/python 

Just load in the api-cors-lambda example and see pycharm light up with type errors:
https://github.com/aws-samples/aws-cdk-examples/blob/master/python/api-cors-lambda/app.py

### Reproduction Steps

Paste pretty much anything from the CDK examples https://github.com/aws-samples/aws-cdk-examples/tree/master/python into pycharm, and watch as solar panels light up in orbit from the sheer volume of incandescing yellow light from the myriad type issues:

```        event_producer_lambda = _lambda.Function(self, "eventProducerLambda",
                                                 runtime=_lambda.Runtime.PYTHON_3_8,
                                                 handler="event_producer_lambda.lambda_handler",
                                                 code=_lambda.Code.from_asset("lambda")
                                                 )
```
Taking a snippet from two different samples
![image](https://user-images.githubusercontent.com/673566/149384506-d316b8c2-67e7-4c24-8aa4-9bc73c87edb6.png)
![image](https://user-images.githubusercontent.com/673566/149384832-97b36627-c90a-46fd-9010-2a81312d7ffd.png)

### What did you expect to happen?

The type information to be correct or not present, not warnings everywhere when supplying the types from the aws examples.

### What actually happened?

Type errors everywhere, followed by tears.

### CDK CLI Version

2.7.0 (build cfb09d5)

### Node.js Version

v16.13

### OS

Windows

### Language

Python

### Language Version

Python 3.8

**Comment by kornicameister** [comment]
Pycharm is quite opinionated when it comes to setup, I often found it to differ greatly in opinion with `mypy`. Not to mention that `mypy` differs from `pyright`. It is a matter of preference obviously but I stopped using Pycharm because it often conflicted with `mypy` or `flake8` or `yapf` or even `black`. 

PS. I don't have your sorts of issues when running my code via `neovim` with `mypy` intergration.

![image](https://user-images.githubusercontent.com/1029674/149395135-ac346684-9c23-4dbb-8660-23d44f7f67e8.png)

**Comment by ryparker** [comment]
@mcsheehan This doesn't sound like a bug with CDK. As mentioned by kornicameister linters like Pycharm are opinionated and the CDK examples repo doesn't have any requirement to match `Pycharm` formatting. 

You could always open a feature request in the CDK examples repo requesting for a `Pycharm` configuration and updated example projects. Contributions are always welcome.

[Create a new issue in the CDK examples repo](https://github.com/aws-samples/aws-cdk-examples/issues/new/choose)
