### ISSUE TITLE
(aws-eks): IPv6 support for EKS Clusters

### ISSUE THREAD

**Issue by youngjeong46** [aws/aws-cdk#18423]
### Description

I'm requesting IPv6 support for EKS Clusters provisioned with CDK.

### Use Case

AWS recently announced support for IPv6 on EKS, focused on resolving the IP exhaustion problem, which is constrained by the limited size of the IPv4 address space, a significant concern as many scale their EKS applications. `eksctl` already supports cluster creation with IPv6

### Proposed Solution

Current eks.Cluster construct prop includes `serviceIpv4Cidr?` parameter. Replace that parameter with these:

- `ipv4`: `boolean` - if true, then IPv4; if false, then IPv6
- `serviceCidr?` - The CIDR block to assign Kubernetes service IP addresses from. Should catch errors for invalid set (ipv4 should be provided with ipv4 range, and ipv6 with ipv6 range)

### Acknowledge

- [x] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by jagu-sayan** [comment]
Hello :)

Maybe do the same that [EKS API](https://docs.aws.amazon.com/eks/latest/APIReference/API_KubernetesNetworkConfigRequest.html#AmazonEKS-Type-KubernetesNetworkConfigRequest-ipFamily) and CloudFormation ?

According to the API, we can't specify a custom IPv6 CIDR block.

**Proposed Solution**:
```typescript
  /**
   * Specify which IP family is used to assign Kubernetes pod and service IP addresses.
   *
   * @default - ipv4
   * @see https://docs.aws.amazon.com/eks/latest/APIReference/API_KubernetesNetworkConfigRequest.html#AmazonEKS-Type-KubernetesNetworkConfigRequest-ipFamily
   */
   readonly ipFamily?: string;
```

If both `ipFamily` and `serviceIpv4Cidr`are defined, we throw an error.
