### ISSUE TITLE
EC2.VPC: incorrect subnet calculation

### ISSUE THREAD

**Issue by arian-saliu** [aws/aws-cdk#18436]
### What is the problem?

VPC resource disregards the maxAz variable. I want to create subnets spanning across the whole AWS region. 
I came across other similar bugs where the resolution was: 

`env: { account: '12345678912', region: 'eu-central-1' },`

This is set for my environment but does not resolve my problem.

### Reproduction Steps

```
subnetConfiguration:[
    {
      subnetType: ec2.SubnetType.PUBLIC,
      name: 'public',
      cidrMask: 24
    },
    {
      subnetType: ec2.SubnetType.PRIVATE_WITH_NAT,
      name: 'private',
      cidrMask: 24
    },
    {
      subnetType: ec2.SubnetType.PRIVATE_ISOLATED,
      name: 'data',
      cidrMask: 24
    },
    {
      subnetType: ec2.SubnetType.PRIVATE_ISOLATED,
      name: 'transit',
      cidrMask: 24
    },
  ],
```

### What did you expect to happen?

I expected subnets created in all of 3 AZs.

### What actually happened?

Subnets got provisioned only in 2 availability zones

### CDK CLI Version

1.137.0 (build bfbdf64)

### Node.js Version

v16.13.1

### OS

macOS 12.1

### Language

Typescript

### Language Version

TypeScript 4.4.4

**Comment by njlynch** [comment]
Hi @arian-saliu ,

Here's a few troubleshooting steps to try:
1. Run `cdk context --clear` (or remove the `cdk.context.json` file). If this file has the wrong value cached, this could be causing the problem.
2. Ensure the account and region specified are correct, and your current credentials have access to perform the EC2 DescribeAvailabilityZones API.

If you have appropriate permissions and clear any stale context, you should see all 3 AZs being properly populated. Here's an example stack, and what my cdk.context.json looks like after running `cdk synth`:

```ts
    new ec2.Vpc(this, 'VPC', {
      maxAzs: 3,
      subnetConfiguration:[
        {
          subnetType: ec2.SubnetType.PUBLIC,
          name: 'public',
          cidrMask: 24
        },
        {
          subnetType: ec2.SubnetType.PRIVATE_WITH_NAT,
          name: 'private',
          cidrMask: 24
        },
        {
          subnetType: ec2.SubnetType.PRIVATE_ISOLATED,
          name: 'data',
          cidrMask: 24
        },
        {
          subnetType: ec2.SubnetType.PRIVATE_ISOLATED,
          name: 'transit',
          cidrMask: 24
        },
      ],
    });
```

**cdk.context.json**:
```
{
  "availability-zones:account=123456789012:region=eu-central-1": [
    "eu-central-1a",
    "eu-central-1b",
    "eu-central-1c"
  ]
}
```
