### ISSUE TITLE
(v2 docs): Link to source code broken in v2 docs

### ISSUE THREAD

**Issue by ulf5** [aws/aws-cdk#18438]
### What is the problem?

The link to the source code from the documentation is incorrect.

### Reproduction Steps

Go here:
https://docs.aws.amazon.com/cdk/api/v2//docs/aws-cdk-lib.LegacyStackSynthesizer.html
Press "source" next to TypeScript.

### What did you expect to happen?

See source code

### What actually happened?

Page not found.

### CDK CLI Version

2

### Node.js Version

?

### OS

Any?

### Language

Typescript

**Comment by cmorgia** [comment]
Anyone, any update on this?

**Comment by TheRealAmazonKendra** [comment]
Looks like this has been fixed. I just clicked on `source` and it took me straight to the line of code. I'm going to go ahead and close this issue. If you are still experiencing it on your end and/or believe that this has been closed in error, please feel free to open a new issue.
