### ISSUE TITLE
(aws_kms): outdated reference to defaultKeyPolicies

### ISSUE THREAD

**Issue by lschierer** [aws/aws-cdk#18446]
### link to reference doc page

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_kms-readme.html

### Describe your issue?

The API reference instructs users to use either the '@aws-cdk/aws-kms:defaultKeyPolicies' feature flag or to set trustAccountIdentities to true in the Key Policies section.  The former yields

```
Error: Unsupported feature flag '@aws-cdk/aws-kms:defaultKeyPolicies'. This flag existed on CDKv1 but has been removed in CDKv2. CDK will now behave as the same as when the flag is enabled.
    at FeatureFlags.isEnabled (/home/schierer/luke/src/TCGInfrastructure/node_modules/aws-cdk-lib/core/lib/feature-flags.ts:18:15)
    at new Key (/home/schierer/luke/src/TCGInfrastructure/node_modules/aws-cdk-lib/aws-kms/lib/key.ts:409:68)
```

during cdk synth.

The latter yields errors during npm run build.    

What is the correct approach to set a default policy the way I did in CDK v1?

**Comment by njlynch** [comment]
The `kms:defaultKeyPolicies` flag is set to true by default in V2. You don't need to do anything to enable the behavior.

Closing out; let me know if you have any follow ups!
