### ISSUE TITLE
aws-opensearchservice: specify multiple subnets allowed in CDK, but fails in deployment

### ISSUE THREAD

**Issue by jdotw** [aws/aws-cdk#18449]
### What is the problem?

The vpcSubjects property is defined as ec2.SubnetSelection[]. This indicates that an array of (i.e multiple) subnets can be defined under the domain. However, specifying more than one subnet in that array results in a deployment failure "You must specify exactly one subnet"

### Reproduction Steps

    const prodDomain = new opensearch.Domain(this, "Domain", {
      version: opensearch.EngineVersion.OPENSEARCH_1_0,
      capacity: {
        masterNodes: 2,
        masterNodeInstanceType: "t3.small.search",
        dataNodes: 1,
        dataNodeInstanceType: "t3.small.search",
      },
      ebs: {
        volumeSize: 20,
      },
      logging: {
        slowSearchLogEnabled: true,
        appLogEnabled: true,
        slowIndexLogEnabled: true,
      },
      enforceHttps: true,
      nodeToNodeEncryption: true,
      encryptionAtRest: {
        enabled: true,
      },
      fineGrainedAccessControl: {
        masterUserName: "master-user",
      },
      vpc: vpc.vpc,
      vpcSubnets: [
        {
          subnetType: ec2.SubnetType.PUBLIC,
        },
        {
          subnetType: ec2.SubnetType.PRIVATE_WITH_NAT,
        },
      ],
    });

### What did you expect to happen?

Successful deployment with domain in both public and private subnets.

### What actually happened?

OpenSearchStack: creating CloudFormation changeset...
12:28:25 pm | CREATE_FAILED        | AWS::OpenSearchService::Domain      | Domain66AC69E0
Resource handler returned message: "Invalid request provided: You must specify exactly one subn
et. (Service: OpenSearch, Status Code: 400, Request ID: 6b1452fe-fd0c-4a0c-bec7-75a3e3c7afed, E
xtended Request ID: null)" (RequestToken: 7f367a71-1ff4-a912-8f22-d9f8c3fbfc30, HandlerErrorCod
e: InvalidRequest)

### CDK CLI Version

2.8.0 (build 8a5eb49)

### Node.js Version

v16.13.2

### OS

macOS Monterey 12.1

### Language

Typescript

**Comment by peterwoodworth** [comment]
Hey @jdotw,

You're only specifying the subnet types for your Vpc Subnets, so your Domain will have the total number of public and private subnets that your vpc has. So, even if you only specify one of these types, there could be multiple subnets that meet that criteria. [Here are our docs on how SubnetSelection works](https://docs.aws.amazon.com/cdk/api/v1/docs/aws-ec2-readme.html#choosing-subnets-for-resources)

Additionally, you can have multiple subnets for a Domain! Specifically, [you want the same number of subnets as AZs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticsearch-domain-vpcoptions.html#cfn-elasticsearch-domain-vpcoptions-subnetids)

**Comment by starodubtsevconsulting** [comment]
same issue. no logical explantin. the link to the doc did not help.. so far

**Comment by starodubtsevconsulting** [comment]
this is how to make it work:             
vpcSubnets: [{
                subnetType: ec2.SubnetType.PRIVATE_ISOLATED
            }]
