### ISSUE TITLE
(aws-synthetics): add cleanup lambda

### ISSUE THREAD

**Issue by RichiCoder1** [aws/aws-cdk#18448]
### Description

Currently, when you delete a synthetic it leaves behind a massive set of detrius. This includes CW resources, buckets, lambdas, and other resources. This is a limitation of the Synthetics API where it will not explicitly delete resources left behind.

### Use Case

To fully cleanup resources upon stack deletion.

### Proposed Solution

Similar to S3, provision an additional lambda that fires upon Canary deletion and removes all the associated Canary resources.

### Acknowledge

- [X] I may be able to implement this feature request
- [X] This feature might incur a breaking change

**Comment by kaizen3031593** [comment]
I like the idea! Seems doable with a custom resource like s3.

**Comment by RichiCoder1** [comment]
For this, s3 has an option like `autoDeleteObjects`. Would in this case it be a prop like `autoDeleteCanaryResources`? Can't think of a better name.

The end result behavior would be like S3 Auto Delete where it'll apply a tag, and on deletion of said tagged resource the CR will invoked to cleanup the underlying Lambda. Do/should we cleanup CloudWatch stuff? I don't think anything else does.
Also assuming that if a bucket isn't provided, the auto created bucket with have `autoDeleteObjects` set to the same value as `autoDeleteCanaryResources`.

**Comment by kaizencc** [comment]
Looks like canaries can now be set with a `DeleteLambdaResourcesOnCanaryDeletion` [property](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-synthetics-canary.html#cfn-synthetics-canary-deletelambdaresourcesoncanarydeletion). I haven't tested it, but by the sound of the property it looks like the lambda resources at least can be auto-deleted. We can add that property into the L2 and be slightly better off than we were before.

**Comment by RichiCoder1** [comment]
Yup, that's correct! Thank goodness too.
