### ISSUE TITLE
IAM/Secrets Manager/ECS: Consolidate IAM policies under path

### ISSUE THREAD

**Issue by automartin5000** [aws/aws-cdk#18458]
### Description

Best practice of Secrets Manager recommends the use of using an `env/` path pattern for secrets naming. CDK should detect the use of this pattern and consolidate IAM policies under `env/*`, especially when using the `aws_ecs.secret` construct.

### Use Case

Simplify IAM policies, but also to solve this bug: https://github.com/aws/aws-cdk/issues/18457

### Proposed Solution

Switch from inline policies to managed policies: https://github.com/aws/aws-cdk/issues/7448

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by rix0rrr** [comment]
We will consider it, but this might be hard to implement in practice: to control the prefix of a secret name, we have to eject from CloudFormation automatic naming and control the whole secret name (which in turn brings other downsides).

**Comment by ebosveld** [comment]
We have the same issue. I tried creating my own ExecutionRole and add a grant for wildcard secrets, but the `ContainerDefinition` construct will automatically grant read as well. Could a workaround be to add a flag so the construct doesn't grant the read but relies on the user to do this @rix0rrr?
