### ISSUE TITLE
IAM: Maximum policy size of 10240 bytes exceeded for role..

### ISSUE THREAD

**Issue by automartin5000** [aws/aws-cdk#18457]
### What is the problem?

Our app has a lot of resources (mostly a lot of secrets). This is causing the auto-generated inline policy max combined size to be exceeded. Even though this bug is technically covered by [this feature request](https://github.com/aws/aws-cdk/issues/7448) since using Managed Policies is probably the primary fix, I thought I should formally file this issue.

### Reproduction Steps

Grant a lot of permissions to a resource that exceeds a total of 10240 bytes.

### What did you expect to happen?

Policy consolidation, see [this feature request](https://github.com/aws/aws-cdk/issues/18458), or the use of [managed policies](https://github.com/aws/aws-cdk/issues/7448) enables more than 10240 of policies.

### What actually happened?

CloudFormation error: `Maximum policy size of 10240 bytes exceeded for role...`

### CDK CLI Version

2.7.0 (build cfb09d5)

### Node.js Version

16.13.1

### OS

Mac OS 12.1

### Language

Python

### Possible solutions:
https://github.com/aws/aws-cdk/issues/7448
https://github.com/aws/aws-cdk/issues/18458

**Comment by mrpackethead** [comment]
Related

https://github.com/aws/aws-cdk/issues/18167
https://github.com/aws/aws-cdk/issues/18293
https://github.com/aws/aws-cdk/issues/16350
https://github.com/aws/aws-cdk/issues/9243

**Comment by automartin5000** [comment]
> Related
> 
> #18167 #18293 #16350 #9243

I saw that, but those issues were related to Pipelines and the fixes all seemed to be specific to Pipelines. Whereas I was hoping this issue could cover a broader set of use cases.

**Comment by sisyphushappy** [comment]
@automartin5000 I've run into this same issue (also with secrets). Have you figured out a scalable solution to this?

**Comment by automartin5000** [comment]
> @automartin5000 I've run into this same issue (also with secrets). Have you figured out a scalable solution to this?
> 
> 
> 
> 

Nothing scalable. Just realized I was adding the secrets to the task role (which already had a bunch of policies) when they're only needed on the execution role. That made both role policies small enough for now. 

If I hit the limit again, I'll probably strip all the secrets out of the task definition, grant the task permissions to get secrets on `<env>/*`, and make the task retrieve the secrets itself.

**Comment by sisyphushappy** [comment]
Good to know, thanks. I will probably opt for a similar approach if required.
