### ISSUE TITLE
(cli): cdk watch shows "...messages supressed..." logs infinitely

### ISSUE THREAD

**Issue by tmokmss** [aws/aws-cdk#18451]
### What is the problem?

Hi team, thank you very much for releasing the cool feature to monitor Lambda logs #18159!
I tried it and it's working fantastic, but noticed that it sometimes shows invalid logs infinitely. Details are below.

Could you check it when you get a chance? Thanks. 

### Reproduction Steps

Deploy a function with `cdk watch`, and invoke it.

### What did you expect to happen?

Only valid logs are displayed.

### What actually happened?

After several valid logs, `...messages supressed...` logs continuously appears (say, 1 line per 2-3 seconds per function).

```sh
[/aws/lambda/BackendStack-Handler2AD178334-hzcv8uEytk3K] 1:08:39 PM REPORT RequestId: c680698d-dd1a-4c64-a387-a507203ad9ac      Duration: 493.33 ms      Billed Duration: 494 ms Memory Size: 128 MB     Max Memory Used: 79 MB
[/aws/lambda/BackendStack-Handler2AD178334-hzcv8uEytk3K] 1:08:39 PM (...messages supressed...)
[/aws/lambda/BackendStack-Handler1EB1BC6C8-StOYX6oimaCD] 1:08:38 PM (...messages supressed...)
[/aws/lambda/BackendStack-Handler1EB1BC6C8-StOYX6oimaCD] 1:08:38 PM (...messages supressed...)
[/aws/lambda/BackendStack-Handler1EB1BC6C8-StOYX6oimaCD] 1:08:38 PM (...messages supressed...)
[/aws/lambda/BackendStack-Handler1EB1BC6C8-StOYX6oimaCD] 1:08:38 PM (...messages supressed...)
[/aws/lambda/BackendStack-Handler1EB1BC6C8-StOYX6oimaCD] 1:08:38 PM (...messages supressed...)
[/aws/lambda/BackendStack-Handler2AD178334-hzcv8uEytk3K] 1:08:39 PM (...messages supressed...)
[/aws/lambda/BackendStack-Handler1EB1BC6C8-StOYX6oimaCD] 1:08:38 PM (...messages supressed...)
[/aws/lambda/BackendStack-Handler2AD178334-hzcv8uEytk3K] 1:08:39 PM (...messages supressed...)
[/aws/lambda/BackendStack-Handler1EB1BC6C8-StOYX6oimaCD] 1:08:38 PM (...messages supressed...)
[/aws/lambda/BackendStack-Handler2AD178334-hzcv8uEytk3K] 1:08:39 PM (...messages supressed...)
# ... continues infinitely
```

### CDK CLI Version

2.8.0

### Framework Version

2.8.0

### Node.js Version

16

### OS

macOS

### Language

Typescript

### Other information

Considering [this document](https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_FilterLogEvents.html), there is a case that `nextToken` is returned but the response is empty.

> This operation can return empty results while there are more log events available through the token.

Maybe we need to check the length of `response.events` here: (I'm not entirely sure though

https://github.com/aws/aws-cdk/blob/626e6aa1a27feffe7ce60a46a6fdcf26f317eaef/packages/aws-cdk/lib/api/logs/logs-monitor.ts#L200-L209

**Comment by peterwoodworth** [comment]
We've put in a fix for this, should be merged shortly. Thanks for the bug report 🙂
