### ISSUE TITLE
Secrets-Manager: Verify imported secrets

### ISSUE THREAD

**Issue by automartin5000** [aws/aws-cdk#18452]
### What is the problem?

When using `secretsmanager.Secret.from_secret_name_v2`, I would expect that CDK synth would be verifying the existence of the secrets in the target account and throwing an error if they don't exist. But it doesn't seem to do that. Instead, my deployments make it all the way to ECS trying (and failing) to launch new tasks with secrets that don't exist.

### Reproduction Steps

Import a secret with `secretsmanager.Secret.from_secret_name_v2` that doesn't actually exist. 

### What did you expect to happen?

`cdk synth` throws an error that the secret doesn't exist in Secrets Manager

### What actually happened?

`cdk synth` succeeds. Then subsequent deployments fail because the secrets are missing.

### CDK CLI Version

2.7.0

### Node.js Version

16.13.1

### OS

Mac OS 12.1

### Language

Python

### Language Version

3.10

### Other information

I tried to write my own little verification utility to handle this problem, but for some reason it doesn't look like the code that runs inside the cdk app gets the temporary credentials from the assumed `lookup` roles. I'm guessing that's because the roles are being assumed by the JS SDK? Is there a way I can find out the role names on my own and assume them myself?

Here's the code I wrote, FWIW.
```python
import boto3

secrets_client = boto3.client('secretsmanager')
caller_identity = boto3.client('sts').get_caller_identity()

print(caller_identity)
aws_account_id = caller_identity.get('Account')

def get_all_the_secrets_in_secrets_manager(secrets=[], next_token={}):

    secrets_list_response = secrets_client.list_secrets(**next_token)
    next_token_response = secrets_list_response.get('NextToken')
    if next_token_response:
        next_token['NextToken'] = next_token_response
    secrets.extend(secrets_list_response['SecretList'])
    if next_token_response:
        return get_all_the_secrets_in_secrets_manager(secrets, next_token)
    else:
        return secrets
        
def verify_secrets(imported_secrets=[]):
    full_secrets_response = get_all_the_secrets_in_secrets_manager()
    active_secrets = dict()

    for s in full_secrets_response:
        # Ignore secrets that have been deleted, even though the list_secrets API call doesn't seem to return those
        if not s.get("DeletedDate"):
            active_secrets[s['Name']] = s['ARN']

    verified_secrets = dict()

    for d in imported_secrets:
        if d not in active_secrets.keys():
            raise ValueError(f"'{d}' has not been provisioned in secrets manager in AWS account: {aws_account_id}")
        else:
            verified_secrets[d.split("/")[-1]] = active_secrets[d]
    num_of_secrets = len(verified_secrets.keys())
    print(f"{num_of_secrets} secret(s) have been verified for account {aws_account_id}")
    return verified_secrets
```

**Comment by peterwoodworth** [comment]
Hey @automartin5000,

This is how most of our imports work in CDK. With the exception of the `fromLookup()` method and a [couple others](https://docs.aws.amazon.com/cdk/v2/guide/context.html#context_methods) (none of these are featured on the Secret construct), our methods which import resources don't actually communicate with your account at all. Imported resources in this case are instead mock constructs, which essentially contain just the data you provide. These mock constructs are necessary so that you can pass in either an existing resource or a newly created resource of the same type to another construct. So, since these imported constructs are essentially just another way to pass data to another construct, you'll end up running into the error on deployment if the resource you specify doesn't exist.

> I tried to write my own little verification utility to handle this problem, but for some reason it doesn't look like the code that runs inside the cdk app gets the temporary credentials from the assumed lookup roles. I'm guessing that's because the roles are being assumed by the JS SDK? Is there a way I can find out the role names on my own and assume them myself?

I'm a little confused at what the exact issue you're dealing with is. Are you having credential issues when using boto within your CDK app?

**Comment by automartin5000** [comment]
> Hey @automartin5000,
> 
> This is how most of our imports work in CDK. With the exception of the `fromLookup()` method and a [couple others](https://docs.aws.amazon.com/cdk/v2/guide/context.html#context_methods) (none of these are featured on the Secret construct), our methods which import resources don't actually communicate with your account at all. Imported resources in this case are instead mock constructs, which essentially contain just the data you provide. These mock constructs are necessary so that you can pass in either an existing resource or a newly created resource of the same type to another construct. So, since these imported constructs are essentially just another way to pass data to another construct, you'll end up running into the error on deployment if the resource you specify doesn't exist.
> 

That's actually what I thought, but then I saw that the Bootstrap's "Lookup Role" has `secretsmanager:List` and `secretsmanager:Describe` permissions and thought maybe it was meant to do it. But looking at it again, I now realize it's just a standard ReadOnly Amazon Managed policy. Sorry, I digress. This would be a nice feature though!
 
> > I tried to write my own little verification utility to handle this problem, but for some reason it doesn't look like the code that runs inside the cdk app gets the temporary credentials from the assumed lookup roles. I'm guessing that's because the roles are being assumed by the JS SDK? Is there a way I can find out the role names on my own and assume them myself?
> 
> I'm a little confused at what the exact issue you're dealing with is. Are you having credential issues when using boto within your CDK app?

Yeah I was thinking I could take advantage of the credentials provided by the Lookup Role when cdk synth is executing to do my own lookup, but in thinking about it some more, I realized that those are actually provided the JS SDK and not available in the Python environment, so I think I'm on my own there. Is the name of the Lookup Role a convention I can use to try to assume it myself?

**Comment by peterwoodworth** [comment]
The lookup role should have a consistent name/arn. Assuming you haven't made modifications to the bootstrap stack, it should look like this:

Arn: `arn:aws:iam::123456789012:role/cdk-QUALIFIER-lookup-role-123456789012-REGION` Name: `cdk-QUALIFIER-lookup-role-123456789012-us-east-1` (the qualifier is `hnb659fds` by default)

**Comment by automartin5000** [comment]
Thanks, I did just come across that qualifier in the docs. So is that a stable qualifier I can use for a convention?

**Comment by peterwoodworth** [comment]
Yes, that's a stable qualifier for all CDK users unless specified otherwise. see [--qualifier](https://docs.aws.amazon.com/cdk/v2/guide/bootstrapping.html#bootstrapping-customizing)

**Comment by automartin5000** [comment]
Got it, thanks @peterwoodworth!
