### ISSUE TITLE
Unable to assign responseHeadersPolicy to my Distribution

### ISSUE THREAD

**Issue by ubergeoff** [aws/aws-cdk#18463]
### What is the problem?

Unable to assign `responseHeadersPolicy` within my `Distribution` when using `aws-cdk-lib/aws-cloudfront`

Error seen is:

```
Property validation failure: 
[Encountered unsupported properties in {/DistributionConfig/DefaultCacheBehavior}: [ResponseHeadersPolicyId]] 
```

### Reproduction Steps

Assign a `responseHeadersPolicy` to the distribution:

```
const distribution = new Distribution(this, 'Distribution', {
            domainNames: [siteDomain],
            defaultRootObject: 'index.html',
            defaultBehavior: {
                origin: myOrigin,
                responseHeadersPolicy: myPolicy,
```

### What did you expect to happen?

I expect that the Response Header Policy is assigned to the correct cache Behavior. i.e. should be assigned to my `defaultBehavior`

### What actually happened?

And error is thrown:

```
Property validation failure: 
[Encountered unsupported properties in {/DistributionConfig/DefaultCacheBehavior}: [ResponseHeadersPolicyId]
``` 

CloudFormation output is similar to:

```
"DefaultCacheBehavior": {
            "AllowedMethods": [
              "GET",
              "HEAD"
            ],
            "CachePolicyId": "658777ea-f89d-4fab-a63d-7e77639e58f6",
            "Compress": true,
            "ResponseHeadersPolicyId": {
              "Ref": "ResponseHeadersResponseHeadersPolicy77F37E77"
            },
            "TargetOriginId": "StacksitStaticSiteDistributionOrigin1CEDB7729",
            "ViewerProtocolPolicy": "redirect-to-https"
          },
```

### CDK CLI Version

2.8.0

### Node.js Version

14.17.1

### OS

Windows

### Language

Typescript

### Language Version

TypeScript (3.9.10)

### Other information

If I just create the `ResponseHeadersPolicy` without assigning it to the `Distribution` - then the `ResponseHeadersPolicy` is created without any issues.  i.e. there are no issues with the actual Response Headers Policy itself.

it is just not assigned to my `Distribution`

**Comment by peterwoodworth** [comment]
I'm unable to reproduce this @ubergeoff, is this happening at the very beginning of deployment? Which region are you deploying into?

**Comment by ubergeoff** [comment]
Hi there 

We are deploying within the `af-south1` region. Could this make a difference ..?

More info: Tried a couple of things, including: Deploying the CloudFormtion template file via the AWS cli

```
aws cloudformation deploy --template-file MyStack-sit.template.json --stack-name MyStack-sit
```

The same error occurs

**Comment by reece2208** [comment]
We tried to deploy the same template in 2 regions now, it passes in eu-west-2 and fails in af-south-1 with the same error.

**Comment by peterwoodworth** [comment]
Yeah, the issue here is that CloudFormation doesn't support `ResponseHeadersPolicyId` in the `af-south-1` region (and possibly others). This is defined in the CloudFormation [resource specs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html)

Unfortunately, this is out of our control. The best thing to do would be to go submit an issue on the [CloudFormation coverage Roadmap](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues) to ask for support for this in your desired region.

**Comment by peterwoodworth** [comment]
Just kidding found an open issue for it https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/969
