### ISSUE TITLE
(cloudwatch): Row class to use list of widgets

### ISSUE THREAD

**Issue by TomaszSzusterTR** [aws/aws-cdk#18466]
### Description

Can class Row accepts list of widgets or maybe implement a method for adding new widgets?

Now we need to explicitly write all widgets when defining a  new row as below:
`cloudwatch.Row(widget1, widget2, widgetN)`

### Use Case

To generate widgets in a loop and add them in batch in a programmatic way.

### Proposed Solution

Thus there is no option to add a generated list of widgets or add widgets in a loop
* `cloudwatch.Row(widget_list=[])`
* `cloudwatch.Row().add_widget(widget)`

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by madeline-k** [comment]
@TomaszSzusterTR I like this idea! I am labelling as a p2 for now, which means the CDK team will not be able to prioritize this right now. However, we always welcome contributions! Take a look at the [contributing guide](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) to get started. 

I think we should do both: accepting an array of widgets in the `Row` constructor, and adding an `addWidget()` helper method to `Row`.

**Comment by flavioleggio** [comment]
Hi @TomaszSzusterTR,

In typescript you can actually work around your issue by passing your generated array of widgets to the constructor with the spread operator `...`.

```ts
declare widgets: IWidget[]; // suppose that you built widgets as a IWidget[] in a previous loop

const row = new cloudwatch.Row(...widgets);
```

In the lib's typescript source code there is no simple and clean way to overload the constructor to support both variadic and array arguments, thus I think that the `addWidget()` helper method would be enough. I submitted a pull request that implements this method.

I think that this could be useful also for the `Column` class. @madeline-k what's your opinion? Can you take a look to my draft PR that is already implementing the solution for the `Row` class?

**Comment by TomaszSzusterTR** [comment]
@flavioleggio the addWidget() will also be sufficient :)

**Comment by nimrax** [comment]
Hi  @TomaszSzusterTR,
Love your idea, i also felt a need for such a helper method and luckily stumbled here! @flavioleggio and similarly maybe we can use `[:]` for the same effect in python. 
I think `cloudwatch.Row().add_widget(widget) ` will be a great solution, as it is also optimal in terms of space complexity. Whereas, passing the whole array to the constructor, seems like a good idea but enforces all widgets to be present in an array at a time and requires certain amount of space which can be avoided with the `addWidget()` proposal.
