### ISSUE TITLE
aws-ecs: Support MaxSwap and Swappiness in LinuxParameters

### ISSUE THREAD

**Issue by joelchen** [aws/aws-cdk#18460]
### Description

Please support MaxSwap (https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/000_official/000_AWS_ECS.json#L975) and Swappiness (https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/000_official/000_AWS_ECS.json#L987) in LinuxParameters (https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-ecs/lib/linux-parameters.ts).

### Use Case

Using swap allows the container to write excess memory requirements to disk when the container has exhausted all the RAM that is available to it.

### Proposed Solution
```
export interface LinuxParametersProps {
  /**
   * Specifies whether to run an init process inside the container that forwards signals and reaps processes.
   *
   * @default false
   */
  readonly initProcessEnabled?: boolean;

  /**
   * The value for the size (in MiB) of the /dev/shm volume.
   *
   * @default No shared memory.
   */
  readonly sharedMemorySize?: number;

  /**
   * The total amount of swap memory (in MiB) a container can use.
   *
   * @default No swap.
   */
  readonly maxSwap?: number;

  /**
   * This allows you to tune a container's memory swappiness behavior.
   *
   * @default 60
   */
  readonly swappiness?: number;
}

constructor(scope: Construct, id: string, props: LinuxParametersProps = {}) {
  super(scope, id);

  this.sharedMemorySize = props.sharedMemorySize;
  this.initProcessEnabled = props.initProcessEnabled;
  this.maxSwap = props.maxSwap;
  this.swappiness = props.swappiness;
}
```

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by mjgp2** [comment]
Example workaround:

```
// https://github.com/aws/aws-cdk/issues/18460
export class LinuxParams extends LinuxParameters {

  renderLinuxParameters(): ecs.CfnTaskDefinition.LinuxParametersProperty {
      const p = super.renderLinuxParameters() as any;
      p.maxSwap = 5e3;
      p.swappiness = 0;
      return p;
  }
}
```

**Comment by joelchen** [comment]
@mjgp2 Thank you, it got registered in repository's template.json and tree.json. However after deployment, `docker inspect` the running container of bottlerocket-os shows MemorySwap as 0.

**Comment by mjgp2** [comment]
@joelchen - you probably need to enable some swap space on the EC2 host instance.
