### ISSUE TITLE
No documentation in intellisense when using CDK for .NET

### ISSUE THREAD

**Issue by mabead** [aws/aws-cdk#1846]
When I use the CDK in TypeScript, I get the documentation directly in the IDE:

![image](https://user-images.githubusercontent.com/4930754/53294115-8400e880-37ae-11e9-8a64-d8475e577efc.png)

But when I use the CDK in .NET, I have no documentation in my IDE:

![image](https://user-images.githubusercontent.com/4930754/53294140-fd004000-37ae-11e9-99ea-395a08ae5e9a.png)

Could you please include the documentation in the xml doc of the CDK nuget packages so that it is displayed in the IDE?

Thanks!

**Comment by eladb** [comment]
@costleya

**Comment by costleya** [comment]
We can definitely do this when we start doing some work on the generator. We'll try to schedule to do this work sometime in April or May.

**Comment by fulghum** [comment]
This just requires updating the .NET generator to include the documentation in NDoc format, right?  Or is there more involved (like building/shipping a doc archive)?

**Comment by costleya** [comment]
I have spoken with the team. We are working on a fix.

**Comment by assyadh** [comment]
Will be fixed by https://github.com/aws/jsii/pull/772
