### ISSUE TITLE
(ec2): aws-cdk 2.1.0 results in empty subnet lists

### ISSUE THREAD

**Issue by l0b0** [aws/aws-cdk#18477]
### What is the problem?

I've got a (private, sorry) project which works with CDK 2.0.0 but not with 2.1.0 or any more recent versions up to and including 2.8.0. The VPC is fetched like this: `vpc = aws_ec2.Vpc.from_lookup(self, "vpc", tags={"foo": "yes"})`. I then use the VPC in two ways:

```python
aws_ec2.BastionHostLinux(
    [other parameters],
    vpc=vpc,
    subnet_selection=aws_ec2.SubnetSelection(subnet_type=aws_ec2.SubnetType.PRIVATE)
)
```

and

```python
vpc.private_subnets[0].subnet_id
```

After upgrading to 2.1.0 I got the following error message related to the first snippet above:

> jsii.errors.JSIIError: There are no 'Private' subnet groups in this VPC. Available types: Isolated

This seems to be caused by #17496. I fixed that by changing the subnet selection to `aws_ec2.SubnetSelection(subnet_type=aws_ec2.SubnetType.ISOLATED)`.

At this point I got a different error message related to the second snippet:

> IndexError: list index out of range

That is, there are no private subnets. This is expected, since the subnet type detection seems to have changed between these releases. I tried changing that snippet to `vpc.isolated_subnets[0].subnet_id`, equivalent to the way I changed the first snippet, but that did not help. Where have the subnets gone?

The VPC is deployed separately, and deployments using CDK 2.0.0 still work, so the subnets definitely exist.

### Reproduction Steps

See above.

### What did you expect to happen?

See above.

### What actually happened?

See above.

### CDK CLI Version

2.1.0 (build f4f18b1)

### Framework Version

2.8.0

### Node.js Version

v14.17.6

### OS

NixOS 21.11

### Language

Python

### Language Version

Python 3.8.11

**Comment by peterwoodworth** [comment]
From the PR you linked, fetching the context for your VPC slightly changed. Are you making sure to [reset the context](https://docs.aws.amazon.com/cdk/v2/guide/context.html#context_viewing) between deployments? The CDK won't fetch new context if existing context already exists for your construct

**Comment by l0b0** [comment]
@peterwoodworth I'm not version controlling `cdk.context.json`, so I don't think that's the issue.

**Comment by peterwoodworth** [comment]
When you synth the stack above version 2.1.0, what does your `cdk.context.json` look like? Also, what are all the subnets you're expecting to be available on your Vpc?

Additionally, make sure you're using `SubnetType.PRIVATE_WITH_NAT` for private subnets, and `SubnetType.PRIVATE_ISLOATED` for isolated subnets. The values `SubnetType.PRIVATE` and `SubnetType.ISOLATED` are no longer present in v2.
