### ISSUE TITLE
(aws-glue): CfnTable name does not resolve correctly in CloudFormation template

### ISSUE THREAD

**Issue by nguyen-tran** [aws/aws-cdk#18475]
### What is the problem?

I am trying to pass a table name to a function that creates a Glue table using the L1 construct CfnTable because I need to also set parameters (see: https://github.com/aws/aws-cdk/issues/7826). However, when I run `cdk synth MyStack`, the table name resolves as `${token[token.206]}` in the outputted CloudFormation template:

```
  GlueTable:
    Type: AWS::Glue::Table
    Properties:
      CatalogId: "MyAccountID"
      DatabaseName:
        Ref: GlueDB8556644B
      TableInput:
        Name: ${token[token.206]}
```

Passing a static string does not have this issue.

### Reproduction Steps

1. Create a resource in the same stack. In my case this is a DynamoDB table:
2. Create a Glue CfnTable that references one of the created resource's attributes as the table name.
3. Run `cdk synth` and observe the resulting Glue table's name to be similar to `${token[token.206]}`

```
import { AttributeType, Table } from '@aws-cdk/aws-dynamodb';
import { CfnTable, Database } from '@aws-cdk/aws-glue';

const domain = 'beta';
const accountId = '';

const ddbTable: Table = new Table(this, 'RecordsTable', {
  tableName: `Records-${domain}`,
  partitionKey: { name: 'id', type: AttributeType.NUMBER },
  sortKey: { name: 'recordedAt', type: AttributeType.STRING },
});

const glueDatabase: Database = new Database(this, 'GlueDB', {
  databaseName: 'gluedb',
  locationUri: 'dynamo-db-flag',
});

new CfnTable(this, 'GlueTable', {
  catalogId: accountId,
  databaseName: glueDatabase.databaseName,
  tableInput: {
    name: ddbTable.tableName.toLowerCase(),
    parameters: {
      classification: 'dynamodb',
      sourceTable: ddbTable.tableName,
      columnMapping: 'id=id,recordedat=recordedAt',
      typeOfData: 'table',
      compressionType: 'none',
    },
    storageDescriptor: {
      columns: [{ name: 'id', type: 'bigint' }, { name: 'recordedat', type: 'string' }],
      location: ddbTable.tableArn,
      parameters: {
        classification: 'dynamodb',
      },
    },
  },
});
```

### What did you expect to happen?

The resulting Glue table name should properly be set to `records-prod` (the DynamoDB table name)

### What actually happened?

The Glue table name was set to `${token[token.206]}`

### CDK CLI Version

2.8.0 (build 8a5eb49)

### Node.js Version

16.3.0

### OS

macOS

### Language

Typescript

### Language Version

TypeScript 4.5.4

**Comment by peterwoodworth** [comment]
[Table.tableName](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-dynamodb.Table.html#tablename-1) is already a `string`, it's passed as a token because it directly references the table name on the CloudFormation resource. So, if you `.toString()` a token, you'll turn it into a string that says token rather than allowing it to function as a token.

This is what correct output should look like when you don't use `toString()`
```
        "TableInput": {
          "Name": {
            "Ref": "RecordsTableF6A7F330"
          },
```

See our docs page to read more about [tokens](https://docs.aws.amazon.com/cdk/v2/guide/tokens.html) if you're interested 🙂
