### ISSUE TITLE
(tools): Could not find any VPCs matching

### ISSUE THREAD

**Issue by jayPJ** [aws/aws-cdk#18484]
### What is the problem?

The problem is that  I am creating 3 stacks consecutively
Stack 1 : Creating some logs and bucket
Stack 2: Creating vpc
Stack 3 : Implemented cdkpipeline to create rest of the stacks(bjs is a stack added as an application stage in cdkpipeline that imports vpc and creates lambda function) 
so when I do cdk synth  , it throws error mentioned  below, although execution does not stop as all 3 stacks are created using a bash file. Why is that happening that fromLookup is throwing error although stack 3 will run only after stack 2(vpc) will be created.
Error : [Error at /ltkrtest10-pipeline-stack/ltkrtest10/bjs] Could not find any VPCs matching {"account":"*","region":"us-east-1","filter":{"tag:Name":"ltkrtest10"},"returnAsymmetricSubnets":true,"lookupRoleArn":"arn:aws:iam::*:role/cdk-hnb659fds-lookup-role-*-us-east-1"}

### Reproduction Steps

 const myVpc = ec2.Vpc.fromLookup(this, "external-vpc", {
      vpcName:INFRA,
    });

### What did you expect to happen?

Something seems wrong here… though stack importing vpc will run only after vpc is created, when I run bash file it gives error.

### What actually happened?

It's trying to synth stack 3 first which has cdkpipeline implemented.

### CDK CLI Version

1.110.1

### Node.js Version

14.17.6

### OS

Windows 10

### Language

Typescript

### Language Version

3.9.7

**Comment by hermanmedsleuth** [comment]
Similar behavior has been observed when I have attempted to create a new infrastructure as well. Interestingly the error disappears on any subsequent invocations of the `create.sh` script.

**Comment by peterwoodworth** [comment]
When you run `cdk deploy --all` or `cdk synth --all`, the CDK will synthesize all stacks at the beginning before starting deployment. A consequence of this is that you can't perform from one of these stacks to another before deployment. 

You can do a couple things here. One is to deploy the stack that contains your VPC first (`cdk deploy StackName`), then deploy the rest of your stacks (`cdk deploy --all`)
Another option is to use `fromVpcAttributes()` instead of `fromLookup()`. The latter will make a call to your AWS account, while the former doesn't. However, this approach may be flawed depending on how much information you need from your Vpc

Let me know if you have any follow up questions

**Comment by jayPJ** [comment]
* fromVpcAttributes() can not be used as I want to import vpc in a dynamic way using name and not with the ID.
* Secondly I am using a bash file where I am running stacks consecutively and was doing same thing as you suggested above , like deploying vpc stack before stacks importing vpc.

![image](https://user-images.githubusercontent.com/89519652/150302065-65d9fcfc-cc49-420d-ac0b-5766738caa93.png)

**Comment by hermanmedsleuth** [comment]
This general problem seems to be endemic in the AWS environment. Many differing types of resources exhibit some latency upon access, and are not available immediately upon creation. 

It is useful to poll and check for availability prior to attempting to access, although in many cases checking for availability entails attempting to access. In those cases well bounded repetitive access attempts, with reasonable delays, may be required.

**Comment by peterwoodworth** [comment]
Interesting, when _exactly_ is the error occurring during the scrupt @jayPJ?

**Comment by hermanmedsleuth** [comment]
I believe that this is an important issue, and that resolution of it is required for success of this project.

@jayPJ can you try using `fromVpcAttributes()`, instead of `fromLookup()`, as @peterwoodworth proposed?

**Comment by jayPJ** [comment]
> I believe that this is an important issue, and that resolution of it is required for success of this project.
> 
> @jayPJ can you try using `fromVpcAttributes()`, instead of `fromLookup()`, as @peterwoodworth proposed?



> Interesting, when _exactly_ is the error occurring during the script @jayPJ?

Error is coming as soon as command  **cdk synth ${INFRA}-main --require-approval never** runs.

**Comment by jayPJ** [comment]
Error is coming as soon as command cdk synth ${INFRA}-main --require-approval never runs.

**Comment by jayPJ** [comment]
> I believe that this is an important issue, and that resolution of it is required for success of this project.
> 
> @jayPJ can you try using `fromVpcAttributes()`, instead of `fromLookup()`, as @peterwoodworth proposed?
Yes I will trying that too.

**Comment by jayPJ** [comment]
After using fromVpcAttributes() , I don't see that error anymore, but for using fromVpcAttributes() I had to change code to this , and adding interface for sharing resources between stacks.
  
  * const myVpc = ec2.Vpc.fromVpcAttributes(this, 'vpcdev', {
    vpcId:props.vpc.ref,
    availabilityZones: [cdk.Stack.of(this).region],
    privateSubnetIds: [props.subnet1.ref],
    publicSubnetIds: [props.subnet2.ref],
    publicSubnetRouteTableIds:[props.routeTable.ref],
    privateSubnetRouteTableIds:[props.privateRtable.ref]
    });

**Comment by peterwoodworth** [comment]
I'm glad you were able to move forward with `fromVpcAttributes()` 🙂 

However, I'm still interested in why the script is throwing an error when attempting to synth only the first stack. I'll try to reproduce and investigate this at some point this week

**Comment by jayPJ** [comment]
Yes, sure and I think it has something to do with cdk.context.json, #3654 , don't know if I am right or not.

**Comment by Preg-replaceconfirmation** [comment]
> Similar behavior has been observed when I have attempted to create a new infrastructure as well. Interestingly the error disappears on any subsequent invocations of the `create.sh` script.





https://visual-composer.github.io/P216kkFpO2QF8eL7oSCYnpbCcM0JIFbz4V8X13SJ/
