### ISSUE TITLE
(core) - multiple stack with same name only deploy first stack listed

### ISSUE THREAD

**Issue by andrei-cdl** [aws/aws-cdk#18493]
### What is the problem?

for example if I have an `infrastructure.ts` like the following

```
import * as cdk from '@aws-cdk/core';
import { AppStack } from '../lib/app/AppStack';

const app = new cdk.App();

new AppStack(app, "DevStack", {
  env: { account: '***********', region: 'us-east-2' },
  deploymentEnv: 'dev'
});

// this will never get used
new AppStack(app, "StagingStack", {
  env: { account: '************', region: 'us-east-2' },
  deploymentEnv: 'staging'
});

```

I'm under the assumption from other docs and tutorial that it's valid to supply the same stack with different configurations and resource name.

if I run `cdk deploy StagingStack` it will still use `DevStack` and not pass in the staging `deploymentEnv`. If I move the staging stack above the dev stack it will execute staging every time etc. It seems it's not respecting the stack name.

### Reproduction Steps

have multiple stacks with same name but different prop values

### What did you expect to happen?

the specified deploy stack to deploy

### What actually happened?

it used the first stack configuration listed in infrastructure.ts

### CDK CLI Version

1.134

### Node.js Version

14

### OS

Arch Linux

### Language

Typescript

### Language Version

4.5.2

**Comment by peterwoodworth** [comment]
I'm not finding the same behavior here @andrei-cdl. `cdk synth/deploy StackName` is only operating on the stack name I've specified. Is there any other context you have that may be affecting things here?

**Comment by andrei-cdl** [comment]
I just want to verify this is using the same CDK version 1.134? There's some changes in latest of 1.139.0 around apigatewayv2 that is stopping me from using it until those issues are resolved.



It's a standard cdk project; even the stack itself being empty results in the same behavior it really only involves `infrastructure.ts` and those 3 apps listed (I omitted but I also have a prod stack) that follows the same convention.

cdk.json if this helps or gives you any other results.
```
{
  "app": "npx ts-node --prefer-ts-exts bin/infrastructure.ts",
  "context": {
    "@aws-cdk/aws-apigateway:usagePlanKeyOrderInsensitiveId": true,
    "@aws-cdk/core:enableStackNameDuplicates": "true",
    "aws-cdk:enableDiffNoFail": "true",
    "@aws-cdk/core:stackRelativeExports": "true",
    "@aws-cdk/aws-ecr-assets:dockerIgnoreSupport": true,
    "@aws-cdk/aws-secretsmanager:parseOwnedSecretName": true,
    "@aws-cdk/aws-kms:defaultKeyPolicies": true,
    "@aws-cdk/aws-s3:grantWriteWithoutAcl": true,
    "@aws-cdk/aws-ecs-patterns:removeDefaultDesiredCount": true,
    "@aws-cdk/aws-rds:lowercaseDbIdentifier": true,
    "@aws-cdk/aws-efs:defaultEncryptionAtRest": true,
    "@aws-cdk/aws-lambda:recognizeVersionProps": true
  }
}

```

**Comment by comcalvi** [comment]
I'm unable to reproduce this on the latest CDK, deploying with `--all` attempts to deploy both stacks.
