### ISSUE TITLE
(aws-iam): TypeScript error when using IGrantable

### ISSUE THREAD

**Issue by stekern** [aws/aws-cdk#18495]
### What is the problem?

I'm getting a TypeScript error when using `cdk.Stack.of` to get current AWS account ID and region on an `iam.IGrantable`.

The error appeared after upgrading from CDK v1 to v2. I'm not sure if this is a bug in v2 or if we've been relying on some kind of undocumented CDK v1 functionality that has been removed in v2 and that the error is actually valid.

I've seen other TypeScript issues reported in this repository, but they've mostly been related to version mismatches when using CDK v1, which should not be the issue here.

I've recreated `node_modules` and `package-lock.json`, which seem to be a typical fix, but the issue still remains when using CDK v2. The issue does not appear when using CDK v1.

### Reproduction Steps

Below is a contrived example to reproduce the error. 

A minimal `package.json`:
```json
{
  "name": "igrantable-type-issue",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "aws-cdk": "2.8.0",
    "ts-node": "10.4.0",
    "typescript": "4.5.4"
  },
  "dependencies": {
    "aws-cdk-lib": "2.8.0",
    "constructs": "10.0.37"
  }
}
```

Example code:
```typescript
import * as iam from "aws-cdk-lib/aws-iam"
import * as cdk from "aws-cdk-lib"
import * as constructs from "constructs"

const describeGrantable = (grantable: iam.IGrantable) => {
  return {
    account: cdk.Stack.of(grantable).account,
    region: cdk.Stack.of(grantable).region
  }
}
```

### What did you expect to happen?

I would expect no errors from TypeScript for the code in question, as that is the behavior I get when using CDK v1.

### What actually happened?

I'm getting the following error:
```
[tsserver 2345] [E] Argument of type 'IGrantable' is not assignable to parameter of type 'IConstruct'.
  Property 'node' is missing in type 'IGrantable' but required in type 'IConstruct'.
```

### CDK CLI Version

2.8.0

### Node.js Version

14.17.6

### OS

MacOS

### Language

Typescript

### Language Version

4.5.4

**Comment by peterwoodworth** [comment]
There is no `aws-cdk-lib/core` package, just use `aws-cdk-lib`!

```
import * as cdk from "aws-cdk-lib";

cdk.Stack.of(...)
```

I hope that this would fix it

**Comment by stekern** [comment]
@peterwoodworth Typo on my end. Issue remains when changing the import to `aws-cdk-lib`.

**Comment by peterwoodworth** [comment]
Ah, I see what the issue is. You're trying to use `Stack.of` on an `IGrantable`. You're required to pass in something which implements `IConstruct`. You will be able to pass in constructs which implement `IGrantable`, the variable which you pass in to `Stack.of` can't be declared as just an `IGrantable` however.

**Comment by stekern** [comment]
The main reason for raising this issue is that I am upgrading a CDK codebase from v1 to v2. I am not getting any errors for  code using `IGrantable` in a similar manner in v1, and the cloud assembly is synthesized without issues, while I'm getting the aforementioned errors in v2. In v2 I can ignore type checking for the offending lines, and the region and account ID will be available in the synthesized cloud assembly without issues -- even though, as you say, `Stack.of` shouldn't work for `IGrantable`.

This may be a Typescript issue, but given that the only change between the two scenarios I describe is a change in the major CDK version, this leads me to believe this might be a bug either in v1 (i.e., errors should have been reported, but are not) or in v2 (i.e., errors should not have been reported, but are).

**Comment by peterwoodworth** [comment]
Ah when I responded last night I had forgotten you said this worked for you in v1. I've been able to reproduce this behavior, it's strange to me, I feel like TS should've prevented that from happening in v1. Not sure what would have changed from v1 to v2 to enforce this

Either way, the behavior seen in v2 is for the best, and is likely expected from the SDEs. I agree with your hypothesis that this was probably a bug in v1 and errors should have been reported. And I also agree with using an intersection typing here 🙂 Thanks for the report! Feel free to ping me with any followup questions you may have
