### ISSUE TITLE
(EC2): Latest Image not pulled unless stack is recreated

### ISSUE THREAD

**Issue by rileysea** [aws/aws-cdk#18506]
### What is the problem?

```MachineImage.latestWindows(WindowsVersion.``` method is not generating the latest image for my CDK stack unless I entirely redeploy the stack that is using this method.

### Reproduction Steps

Use the following AMI lookup as an example:

```
{ami: MachineImage.latestWindows(WindowsVersion.WINDOWS_SERVER_2016_ENGLISH_FULL_BASE).getImage(this).imageId },
```

For my existing CDK stack, during CDK Synth no differences were detected & the following AMI was reflected: `ami-086652868369ff3f5`

However, after redeploying the stack, I am seeing the following AMI: `ami-0d63b0df59309cf3f`

### What did you expect to happen?

Any time I deploy an existing stack that has the following construct + method, I should be receiving the latest AMI from that lookup instead of keeping the existing AMI that was used before for creating AutoScaling Groups.

```MachineImage.latestWindows(WindowsVersion.```

### What actually happened?

I get the same legacy AMI set in my CDK stack until I redeploy the entire stack, which includes EC2 AutoScaling Groups + Launch Configuration.

### CDK CLI Version

1.122.0 (build ae09c16)

### Node.js Version

16.4.13

### OS

Amazon Linux 2

### Language

Typescript

### Language Version

4.0.8

### Other information

Using monocdk.

**Comment by peterwoodworth** [comment]
Have you tried resetting the context? View this note in our [docs](https://docs.aws.amazon.com/cdk/api/v1/docs/aws-ec2-readme.html#machine-images-amis):

>NOTE: The AMIs selected by MachineImage.lookup() will be cached in cdk.context.json, so that your AutoScalingGroup instances aren't replaced while you are making unrelated changes to your CDK app.
>To query for the latest AMI again, remove the relevant cache entry from cdk.context.json, or use the cdk context command. For more information, see [Runtime Context](https://docs.aws.amazon.com/cdk/latest/guide/context.html) in the CDK developer guide.
