### ISSUE TITLE
docs(cloudwatch): MetricProps lists "dimensions" but type definition lists "dimensionsMap"

### ISSUE THREAD

**Issue by IamFlowZ** [aws/aws-cdk#18503]
### link to reference doc page

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_cloudwatch.Metric.html#dimensions

### Describe your issue?

discrepancy between docs and type defs for Metric props in Cloudwatch

**Comment by madeline-k** [comment]
Thanks for opening this issue @IamFlowZ. In CDK v1, there are two properties for dimensions: `dimensions` (which is actually deprecated, but this is not showing correctly in the docs) and `dimensionsMap`. In v2, there is only `dimensionsMaps`.  

The docs are incorrect here, thanks for pointing this out! The prop you should be using is `dimensionsMap`

**Comment by madeline-k** [comment]
Hey @IamFlowZ , please disregard my earlier comment. The `dimensions` property of the `Metric` class is correct in the documentation here: https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_cloudwatch.Metric.html#dimensions. This is referring to a public property of the `Metric` class, and not a constructor property. 

The constructor props for `Metric` are documented in the `MetricProps` interface here: [v1 link](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-cloudwatch.MetricProps.html), [v2 link](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_cloudwatch.MetricProps.html)
