### ISSUE TITLE
(aws_lambda_nodejs module): projectRoot should default to process.cwd

### ISSUE THREAD

**Issue by bestickley** [aws/aws-cdk#18514]
### Description

I've got a mono repo setup like so:
- back-end/
- front-end/
- package.json
- pnpm-lock.yaml
- pnpm-workspace.yaml

esbuild is listed as a dependency in back-end/package.json. I've got a NodejsFunction construct in back-end that when I deploy gives me an error "esbuild not found" unless I install esbuild within the root package.json. The script that's deploying the stack looks something like this:
```ts
execSync(
      `cdk --app "node --loader ts-node/esm src/app.ts" deploy back-end-stack`,
      {
        cwd: "back-end",
        stdio: "inherit",
      }
    );
```

### Use Case

To easily deploy NodejsLambda functions in a monorepo.

### Proposed Solution

Change [this line](https://github.com/aws/aws-cdk/blob/15a19364c4aea7e6d12d1401b458ee09816d8a33/packages/%40aws-cdk/aws-lambda-nodejs/lib/bundling.ts#L99) to `this.projectRoot = props.projectRoot || process.cwd();`. This makes more sense to me than defaulting to root of project. There may be other use cases that are more likely than mine though, so I'd appreciate the opinion of someone who has worked on this.

### Acknowledge

- [X] I may be able to implement this feature request
- [X] This feature might incur a breaking change

**Comment by corymhall** [comment]
@bestickley I might close this in favor of #18175. It sounds like we really just need to have a way of better handling monorepo setups.
