### ISSUE TITLE
s3/kms: grant account users to decrypt

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#1852]
When encrypting an S3 bucket with KMS, it should be possible to grant account users to use the key to decrypt when used via the S3 service:

```ts
    encryptionKey.addToResourcePolicy(new iam.PolicyStatement()
      .addAction('kms:Decrypt')
      .addResource('*')
      .addAwsPrincipal('*')
      .addCondition('StringEquals',{
        'kms:ViaService': `s3.${this.env.region}.amazonaws.com`,
        'kms:CallerAccount': this.env.account
      }));
```

**Comment by RomainMuller** [comment]
Need to verify this is sufficient though (@skinny85 seems to have some evidence that it also requires the user to have "direct" `kms:Decrypt` permissions, although his tests were focused on cross-account scenarios).

**Comment by skinny85** [comment]
It's not enough in the CodePipeline cross-account case, but if it works in others, I don't see an issue with adding it.

**Comment by eladb** [comment]
Still relevant
