### ISSUE TITLE
CDK Synth: Running raw cloud formation instructions

### ISSUE THREAD

**Issue by ralphmr** [aws/aws-cdk#18534]
### General Issue

How do I run the raw underlying cfn produced by CDK Synth?

### The Question

I have a stack and ran `cdk synth -o MyStack` to synthesize the underlying CloudFormation template.
I then want to publish this CloudFormation template elsewhere (I don't want my users to have to install CDK etc to launch my solution). So essentially I wish to share the newly generated `MyStack` directory with users.
I go into the `MyStack` directory and run `aws cloudformation create-stack --stack-name clitest --template-body MyStack/mystack.template.json`
I get the following error:
```bash
An error occurred (ValidationError) when calling the CreateStack operation: Parameters: 
[AssetParameters32a1ad119e932bb8e9cce983807f848131317a310191d2ae3e39b6b89c49242dArtifactHash20335C7F, 
AssetParametersc691172cdeefa2c91b5a2907f9d81118e47597634943344795f1a844192dd49cS3BucketEAC9DD43, 
AssetParametersc691172cdeefa2c91b5a2907f9d81118e47597634943344795f1a844192dd49cS3VersionKeyDD9AE9E7, 
AssetParametersc691172cdeefa2c91b5a2907f9d81118e47597634943344795f1a844192dd49cArtifactHash627DAAA7, 
AssetParameterse4077f2fa03d753c57a4550b77113a47aa6a17a7b6561328453a0c27d6233d86S3VersionKey7B5B6DB7, 
AssetParameterse4077f2fa03d753c57a4550b77113a47aa6a17a7b6561328453a0c27d6233d86S3Bucket6917682F, 
AssetParameters32a1ad119e932bb8e9cce983807f848131317a310191d2ae3e39b6b89c49242dS3Bucket1483F172, 
AssetParametersc1d5fd9982309c1ca4f9f4c91e9030a9df4f9f894bc074c3c8c5412f012ff369S3Bucket875EF32E, 
AssetParametersc1d5fd9982309c1ca4f9f4c91e9030a9df4f9f894bc074c3c8c5412f012ff369S3VersionKeyB9E96CB5, 
AssetParameters32a1ad119e932bb8e9cce983807f848131317a310191d2ae3e39b6b89c49242dS3VersionKey08116A80, 
AssetParametersc1d5fd9982309c1ca4f9f4c91e9030a9df4f9f894bc074c3c8c5412f012ff369ArtifactHash452212AC, 
AssetParameterse4077f2fa03d753c57a4550b77113a47aa6a17a7b6561328453a0c27d6233d86ArtifactHash6E7DE471] 
must have values
```

How do I successfully launch the underlying CFN stack that was synthesized by CDK without requiring CDK any more?

### CDK CLI Version

1.122.0

### Language

Python

**Comment by peterwoodworth** [comment]
Hey @ralphmr,

The issue you're running into is that your app has assets that it needs to upload. The CDK does this as part of the deploy command, before deploying your stack. [Read here](https://docs.aws.amazon.com/cdk/v2/guide/assets.html#assets_details) to learn in depth about our asset uploading process. I'd like to specifically call out this section:

> the AWS CDK CLI first prepares and publishes them to Amazon S3 or Amazon ECR, and only then deploys the stack. The AWS CDK specifies the locations of the published assets as AWS CloudFormation parameters to the relevant stacks, and uses that information to enable referencing these locations within an AWS CDK app.

So unfortunately, this whole process is built to work together. If you end up going down the path of having your customers upload assets then deploying the template, it would almost certainly be easier to have them just deploy the CDK app.

So, maybe there's another way to do that. The CDK will output your [Cloud Assembly](https://docs.aws.amazon.com/cdk/v2/guide/apps.html#apps_cloud_assembly)  to the `cdk.out` directory. This will contain your assets and all other files required for your app to be deployed to the cloud. The docs call out that you don't have to have the CDK installed to run this, but rather
> any tool that can read the cloud assembly format can be used to deploy your app.
In all honesty, I don't know an example of another tool that can read cloud assembly format. But there is a potential solution here

However, even if you were to easily have customers deploy your cloud assembly, their environments would still need to be [properly bootstrapped](https://docs.aws.amazon.com/cdk/v2/guide/bootstrapping.html), which brings you back to square one.

I don't think I've seen questions related to the portability of our CDK output before. @eladb do you have any thoughts here?
