### ISSUE TITLE
Feature request: enable feature flags when running tests

### ISSUE THREAD

**Issue by jfly** [aws/aws-cdk#18535]
### Description

Right now, feature flags in `cdk.json` take effect when inside of a `cdk synth`, but are *not* picked up when in tests. @nija-at says that [this is intentional](https://github.com/aws/aws-cdk/issues/17553#issuecomment-982783755).

### Use Case

I don't think this is a very sane default for users of cdk: I can totally see why people *working* on cdk would not want feature flags to automagically get enabled in tests, but IMO that's not appropriate behavior for *users* of cdk. For example, we recently started getting warnings like this when running `cdk synth`:

> [WARNING] @aws-cdk/aws-kms.KeyProps#trustAccountIdentities is deprecated.
redundant with the @aws-cdk/aws-kms:defaultKeyPolicies feature flag
This API will be removed in the next major release.

This felt pretty silly to us, because even though we had the `@aws-cdk/aws-kms:defaultKeyPolicies` enabled in our `cdk.json` file, we could not remove this `trustAccountIdentities` parameter without breaking tests.

### Proposed Solution

I'd love to see cdk.json feature flags handled the same way between `cdk synth` and unittests.

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by njlynch** [comment]
When invoking the cdk CLI, the CLI itself takes care of loading the `cdk.json` file and parsing out the context; however, it's difficult to provide a one-size-fits-all solution to enable that context while running inside any given test runner in all of the languages we support.

That being said, the solution in any given language + test runner is fairly trivial; you simply need to pass the `context` from `cdk.json` and pass it into your `App` creation. Here's an example for Typescript + Jest:

```ts
let app: cdk.App;
let context: { [key: string]: any };
beforeAll(async () => { context = JSON.parse((await fs.readFile('cdk.json', 'utf8'))).context; });
beforeEach(() => { app = new cdk.App({ context }); });
```

I hope that helps.
