### ISSUE TITLE
(CDK v2 Synth/Deploy): deploy always needs bootstrapped env despite docs claiming otherwise

### ISSUE THREAD

**Issue by PieterVanEde** [aws/aws-cdk#18553]
### What is the problem?

I have an application consisting of multiple stacks. Some stacks include lambda functions or files in a S3 bucket. When running synth, they use assets and hence require the target region to be bootstrapped. Those stacks are all located in eu-central-1.

However, I also have a stack for defining a cloudfront distribution located in us-east-1 (it is backed by a s3 bucket in another stack located in eu-central-1). My company has set up a permission model which forbids using resources that hold data (databases, s3, etc) outside of european regions, so I cannot bootstrap in us-east-1 as that involves creating a S3 bucket.

On CDK v1 this works nicely, because the cloudfront stack uses no assets and produces a fairly small cloudformation template (~ 2 kB). This is well below the threshold of 50 kB, so it does not need a bootstrapped environment.

Now when upgrading to CDK v2, I get errors during deploy that the us-east-1 environment is not bootstrapped. I also see that the CDK synth commands generated a *.assets.json for this (and every other) stack. Perhaps this is the reason why it's complaining about needing a bootstrapped environment.

Reading the docs for CDK v2 at https://docs.aws.amazon.com/cdk/v2/guide/bootstrapping.html I would have expected that a small stack without assets would not require bootstrapping.
I'm not sure what's going wrong here, but it seems either:

- CDK v2 Synth incorrectly generates assets for templates that don't need assets (opening them it is just for storing the cloudformation template in a s3 bucket)
- CDK v2 Deploy incorrectly tries to use a bootstrap stack for stacks that don't need that
- I'm doing something wrong. I've searched for a flag that sort of says 'only use assets when you absolutely have to'  but I couldn't find a flag like that. Perhaps it's just me overlooking something.

I would appreciate some pointers on how to get a simple stack not needing assets to deploy without requiring a bootstrap stack, just like it did in v1 and how it should be possible according to the v2 docs.

### Reproduction Steps

Create a small stack that does not need assets and try to deploy it without bootstrapping the environment.

### What did you expect to happen?

It would deploy without problem.

### What actually happened?

It complained about the evironment not being bootstrapped. The other regions that I did bootstrap ran fine, and so did this same stack on v1.

### CDK CLI Version

2.8.0

### Framework Version

2.8.0

### Node.js Version

14

### OS

Amazon linux

### Language

Typescript

**Comment by PieterVanEde** [comment]
Looking a bit around in the source code, I see that the default synthesizer [always adds the template file as an asset](https://github.com/aws/aws-cdk/blob/455d0b3ec254a3ae37ff705b8e0e5615efb8a0a3/packages/%40aws-cdk/core/lib/stack-synthesizers/default-synthesizer.ts#L471). As a result, all stacks require bootstrapping, [contrary to what the docs say](https://docs.aws.amazon.com/cdk/v2/guide/bootstrapping.html).

There is an alternative bootstrapless synthesizer, but it seems this is [only used within cdk-codepipeline](https://github.com/aws/aws-cdk/blob/455d0b3ec254a3ae37ff705b8e0e5615efb8a0a3/packages/%40aws-cdk/aws-codepipeline/lib/pipeline.ts#L664).

**Comment by PieterVanEde** [comment]
I've tried fiddling around a bit more, and when I specify the BootstraplessSynthesizer, I see the <stack>.assets.json is no longer generated by cdk synth. However, it then complains during deploy about not being able to assume the cfn-exec role. Of course that role isn't there, because the env was not bootstrapped. Anybody got an idea how to get around this?

**Comment by rix0rrr** [comment]
Docs have been updated.

**Comment by onebytegone** [comment]
@rix0rrr Do you have a link to the docs that were updated? The bootstrapping docs in the CDK guide haven't been changed since 2022/02/15 ([last change](https://github.com/awsdocs/aws-cdk-guide/commit/4c83259af44b702414e9320725bbc47d414159f5#diff-c0305750bf9f9c8e0a7245897f7de1b2087384f8d7d2b60453e6f5c6dc71f974)) and I'm not seeing any changes in this repo that are related. This issue is causing me problems as well. I am very curious to know the official stance on whether bootstrapping is required. Thanks!

**Comment by NGL321** [comment]
It seems our [docs](https://docs.aws.amazon.com/cdk/v2/guide/bootstrapping.html) on this matter have not been sufficiently updated. Reopening for now

_Additional report: P64150129_

**Comment by peterwoodworth** [comment]
Can someone provide the exact quote that is causing confusion? The docs do explicitly state that bootstrap resources are required with the default stack synthesizer
