### ISSUE TITLE
(api gateway-lambda) CDK  create Incorrect lambda trigger

### ISSUE THREAD

**Issue by grl-wang** [aws/aws-cdk#18566]
### What is the problem?

* we use the apigateway.LambdaIntegration for api gateway to integration with lambda
* when we deploy our code to different aws account for different stage, we found some lambda triggers create incorrectly with the the stage as `test-invoke-stage`, not the correctly one with the stage as `beta` or `pre-prod`
*  Besides, in different stage, it randomly create the incorrect lambda trigger

### Reproduction Steps

The code for api gateway to integrate with the lambda is similar as following:
```
    const rootRsc = api.root.addResource('rootresources');
    const batchCreateRsc = rootRsc.addResource('batchCreate');
    batchCreateRsc.addMethod(
        'POST',
        new apigateway.LambdaIntegration(this.batchCreateLambdaFunction)
    );

    const rootresourceIdRsc = rootRsc.addResource('{rootresourceid}');
    const updateRsc = rootresourceIdRsc.addResource('update');
    updateRsc.addMethod(
        'PUT',
        new apigateway.LambdaIntegration(this.updateLambdaFunction)
    );

    const listRsc = rootResourceRsc.addResource('list');
    listRsc.addMethod(
        'POST',
        new apigateway.LambdaIntegration(this.listLambdaFunction)
    );

```

### What did you expect to happen?

we expect the lambda trigger configured with stage as service stage e.g. `beta` and `pre-prod` stage, not the `test-invoke-stage`

### What actually happened?

* when we deploy our code to different aws account for different stage, we found some lambda triggers create incorrectly with the the stage as `test-invoke-stage`, not the correctly one with the stage as `beta` or `pre-prod`
*  Besides, in different stage, it randomly create the incorrect lambda trigger    
     * for example we deployed the resource in beta account, it create the beta stage in api gateway: the `listLambda` trigger is correctly with beta stage, but the the `updateLambda` trigger is incorrectly with `test-invoke-stage`
    * when we deploy the same cdk code to `beta` stage: the `listLambda` trigger is incorrectly incorrectly with `test-invoke-stage` stage, but the the `updateLambda` trigger is correctly with `pre-prod` stage

### CDK CLI Version

CDKBuild = 3.x;

### Node.js Version

N/A

### OS

N/A

### Language

Java

### Language Version

java 8

**Comment by LukvonStrom** [comment]
hi @grl-wang,
the creation of a `test-invoke-stage` is expected, when `allowTestInvoke` is not explicitly set to false (see here: https://github.com/aws/aws-cdk/blob/5436ce27a39499d019d45c0f2bb523d5e9d17607/packages/%40aws-cdk/aws-apigateway/lib/integrations/lambda.ts#L17) when creating the Lambda Integration.

Could you please verify that:
1.  the bug "disappears" when you turn `allowTestInvoke` off
2. the original stages are created for the LambdaIntegration as well?
