### ISSUE TITLE
ec2.BastionHostLinux: No easy way to pass in keyName to ssh in from this class

### ISSUE THREAD

**Issue by rbarcia** [aws/aws-cdk#18565]
### What is the problem?

```ts
  const host = new ec2.BastionHostLinux(this, 'cdk-bastion', {
    vpc,
    instanceName: 'cdk-bastion',
    instanceType: ec2.InstanceType.of(ec2.InstanceClass.T3, ec2.InstanceSize.MICRO),
    machineImage: machineImage,
    securityGroup: public_sg,
    subnetSelection: {subnets:[vpc.publicSubnets[0]]}
  });
```
I expected keyName to be a top level property at construction.  If i want to create a Bastion with ssh Key, then I have to use regular Image class since it is a construct prop.  

I am using Typecript.  

### Reproduction Steps
```ts
import { Stack, StackProps } from 'aws-cdk-lib';
import { Construct } from 'constructs';
 import * as ec2 from 'aws-cdk-lib/aws-ec2';
import { Peer, Port } from 'aws-cdk-lib/aws-ec2';

export class CdkVpcStack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);
    const vpc = new ec2.Vpc(this, 'cdk-vpc', {
      cidr: "10.0.0.0/16",
      enableDnsHostnames: true,
      enableDnsSupport: true,
      subnetConfiguration: [
        {
          cidrMask: 24,
          name: 'cdk-sb-public',
          subnetType: ec2.SubnetType.PUBLIC,
        },
        {
          cidrMask: 20,
          name: 'cdk-sb-private',
          subnetType: ec2.SubnetType.PRIVATE_ISOLATED,
        }

      ] 
   });

  const public_sg = new ec2.SecurityGroup(this, 'cdk-public-sg', {
    vpc: vpc,
  });
 
  public_sg.addIngressRule(Peer.anyIpv4(),Port.tcp(22),"SSH Bastion",false);
  public_sg.addEgressRule(Peer.anyIpv4(),Port.allTraffic(),"SSH Bastion",false);

  const machineImage = ec2.MachineImage.latestAmazonLinux();

  const host = new ec2.BastionHostLinux(this, 'cdk-bastion', {
    vpc,
    instanceName: 'cdk-bastion',
    instanceType: ec2.InstanceType.of(ec2.InstanceClass.T3, ec2.InstanceSize.MICRO),
    machineImage: machineImage,
    securityGroup: public_sg,
    subnetSelection: {subnets:[vpc.publicSubnets[0]]}
  });
  
}

   
}
```
### What did you expect to happen?

Simple property to add keyName.

### What actually happened?

keyName cannot be set cause Image is private

### CDK CLI Version

2.8.0

### Framework Version

2.8.0

### Node.js Version

v16.13.1

### OS

Mac OS

### Language

Typescript

### Language Version

3.9.7

**Comment by joel-aws** [comment]
Can you [set the property via its CloudFormation](https://docs.aws.amazon.com/cdk/v2/guide/cfn_layer.html#cfn_layer_resource)?

**Comment by jumic** [comment]
`Instance` has already support for property `keyName`. If we want to support it in `BastianHost`, we could add it in [`BastionHostLinuxProps`](https://github.com/aws/aws-cdk/blob/d71b931e374c1cb4682de07a2be9e6ddc675b6d6/packages/%40aws-cdk/aws-ec2/lib/bastion-host.ts#L20) and pass it to [`Instance`](https://github.com/aws/aws-cdk/blob/d71b931e374c1cb4682de07a2be9e6ddc675b6d6/packages/%40aws-cdk/aws-ec2/lib/bastion-host.ts#L167).

Workaround using escape hatches as propsed by @joel-aws:
```ts
const host = new ec2.BastionHostLinux(this, 'BastionHost', {
  vpc,
  subnetSelection: { subnetType: ec2.SubnetType.PUBLIC },
});

const instance = host.node.defaultChild as ec2.Instance;
const cfnInstance = instance.node.defaultChild as ec2.CfnInstance;
cfnInstance.keyName = 'MyCustomKeyName';
```

**Comment by NGL321** [comment]
Hey, I have converted this to a feature-request since it seems to be more of a gap in offerings than something wrong with what exists (that said, feel free to correct me on this).
That said, this does seem like an important feature, so I kept the priority high.

For fastest implementation, you may want to try cutting a PR yourself, or solicit community help, otherwise keep upvoting this issue and one of the devs will look into this as time allows.

😸

**Comment by hoegertn** [comment]
Not adding the keyName was a decision when writing this construct.

1. The recommended way to connect to this bastion host is to use session manager and not use SSH, that is why there is also no ingress rule for port 22 by default
2. Using the keyName prop of an instance means that there is ONE key to connect which normally is not what you want as you want to have personalized keys for people connecting to this box.

As the BastionHost is a level 2.5 construct it is opinionated as does not solve all use cases somebody might have

**Comment by NGL321** [comment]
@hoegertn @njlynch,

If this was an intentional design consideration, should we suspend further conversation about adjusting the construct?

**Comment by MrArnoldPalmer** [comment]
Since this is a higher level construct and has some opinions embedded as @hoegertn mentioned, I'm going to close this now as I don't think it's something we plan on implementing at the moment. I think using `Instance` or writing your own construct for a bastion instance are good ways to implement this if you need.

Closing this but glad to keep discussing if this is something people feel strongly about.

**Comment by rantoniuk** [comment]
For people looking for an actual solution:

```
  bastion.instance.instance.addPropertyOverride('KeyName', `my-bastion-key`);
```

Using SSM is indeed the recommended way, but in order to have SCP access, you need to have a KeyPair assigned, at least temporarily.
