### ISSUE TITLE
(S3): inline documentation about `Bucket.import` is outdated

### ISSUE THREAD

**Issue by ahtsan** [aws/aws-cdk#18575]
### link to reference doc page

https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-s3/lib/bucket.ts#L360

### Describe your issue?

`Bucket.import` is no longer valid, it should be either `Bucket.fromBucketArn` or `Bucket.fromBucketName`

**Comment by peterwoodworth** [comment]
Wow this is _really_ old! Check out [the commit](https://github.com/aws/aws-cdk/commit/41f747ddbecab98a90455e639ac1a51c9a368121) this is from. I never knew about the `export` function. Thanks for pointing this out, I'll get this cleaned up tomorrow
