### ISSUE TITLE
(aws-route53): HealthCheckConfigProperty missing RoutingControlArn

### ISSUE THREAD

**Issue by gjmveloso** [aws/aws-cdk#18570]
### What is the problem?

The `CfnHealthCheck.HealthCheckConfigProperty` is missing the `RoutingControlArn` property.

According to [Route 53 docs](https://docs.aws.amazon.com/Route53/latest/APIReference/API_HealthCheckConfig.html), the `HealthCheckConfig` contains a `RoutingControlArn` property

### Reproduction Steps

```typescript
new r53.CfnHealthCheck(this, 'HealthCheck', {
            healthCheckConfig: {
                type: 'RECOVERY_CONTROL',
                inverted: true,
                routingControlArn: routingControl.attrRoutingControlArn // causes error
            }
        });
```

### What did you expect to happen?

Cfn* constructs generated from CloudFormation directly should be always stable and updated accordingly.

### What actually happened?

```
TSError: ⨯ Unable to compile TypeScript:
lib/route53-arc.ts:132:17 - error TS2322: Type '{ type: string; inverted: true; routingControlArn: string; }' is not assignable to type 'IResolvable | HealthCheckConfigProperty'.
  Object literal may only specify known properties, and 'routingControlArn' does not exist in type 'IResolvable | HealthCheckConfigProperty'.

routingControlArn: routingControl.attrRoutingControlArn,
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  node_modules/@aws-cdk/aws-route53/lib/route53.generated.d.ts:99:14
    readonly healthCheckConfig: CfnHealthCheck.HealthCheckConfigProperty | cdk.IResolvable;
             ~~~~~~~~~~~~~~~~~
    The expected type comes from property 'healthCheckConfig' which is declared here on type 'CfnHealthCheckProps'
```

### CDK CLI Version

2.8.0 (build 8a5eb49)

### Framework Version

1.139.0

### Node.js Version

v16.13.2

### OS

macOS 12.1

### Language

Typescript

### Language Version

4.5.5

**Comment by njlynch** [comment]
This structure is weird. Route53 used to model this explicitly in the CloudFormation spec, and then reverted and modeled it as just a JSON string. We made the decision to re-create the existing model, but that means our custom solution isn't automatically kept up to date with the rest of the CloudFormation spec (as there isn't an official spec for it). Instead, we get to manually update a patch file when a new field is added.

That being said, I've created the patch.
