### ISSUE TITLE
(pipelines): A guidance to writing programatic smoke test

### ISSUE THREAD

**Issue by kornicameister** [aws/aws-cdk#18580]
### General Issue

How to get a proper permission (assume role) to launch integration test

### The Question

In short, I am looking on a problem of defining a test after a stage deployment that utilized said stage outputs and runs integration/smoke tests using Python's `pytest` + `boto3`. Now I am using `ShellStep` as `post` stage step and `envFromCfnOutputs` feature to get ahold of couple of ARNs and more importantly a role's ARN that allows to access deployed resources. 
Question is: how I assume said role? Obviously the role created by CDK backing `ShellStep`'s `CodeBuild` is not accessible to me. What can I do?

### CDK CLI Version

1.139.0

### Language

Python

### Language Version

3.10.1

### Other information

Looking for guidance ;-)

**Comment by kornicameister** [comment]
I am bit worried that it might be quite hard to pull it off. Inside a code build action we are dealing with assumed role so if I were to create my test role to allow being assumed by code build I would have to specify full ARN as defined in documentation for IAM principal:

![image](https://user-images.githubusercontent.com/1029674/150475368-37fc10f0-475d-4d51-a876-6b588b510500.png)

**Comment by kornicameister** [comment]
What I have done now was to do:

1. set assume statement for code build roles to require `my-tag: my-value` on role that is assumed
```
            code_build_defaults=pipelines.CodeBuildOptions(
                role_policy=[
                    iam.PolicyStatement(
                        actions=['sts:AssumeRole'],
                        resources=['*'],
                        conditions={
                            'StringEquals': {
                                'iam:ResourceTag/my-tag': 'my-value',
                            },
                        },
                    ),
                ],
            ),

```

2. Create a test role in test stack with principal like so:
```
        test_role = iam.Role(
            self,
            'TestRole',
            assumed_by=iam.CompositePrincipal(
                # setting a full ARN to assume here is impossible because we do
                # know a details like a code build action project running shell
                # step behind smoke test and there is also an assumed role
                # there which we cannot reference because we have to know full
                # ARN of it
                # TODO(kornicameister) make it more secure
                iam.AnyPrincipal().with_conditions({
                    'StringEquals': {
                        'aws:PrincipalTag/my-tag': 'my-value',
                    },
                    'StringLike': {
                        'sts:RoleSessionName': 'my-smoke-test',
                    },
                }),
			   # redacted principal
            ),
        )

```

3. And inside the integration test I am using `boto3` to assume a role with `RoleSessionName=my-smoke-test`.

I would appreciate an opinion on this setup ;)

**Comment by BDeus** [comment]
I have the same kind of issue with executing a ShellStep to call aws cli on a addPost().
I don't know which is the best method to add policy to the current shellstep execution role.

**Comment by kornicameister** [comment]
The current one is not exposed I believe.
My idea was based on tagging roles created in step/stage so that any post steps happening can assume said roles.

To follow least privileged pattern in code build defaults I enforce assumed role tag with `iam:ResourceTag` condition that's value matches a tag assigned to a role created in step. Second part of security was specific session name that anything running within a step (code, cli) must present.

**Comment by gshpychka** [comment]
To control the role used in a ShellStep, you should switch to `CodeBuildStep`. It exposes `role` and you can add statements to the policy directly.

**Comment by BDeus** [comment]
Thank you @gshpychka, strugle with this for hours.

**Comment by kornicameister** [comment]
@gshpychka you mean that as drop-in replacement for `ShellStep` ?

**Comment by kornicameister** [comment]
Wonder if it makes sense to write some sort of example somewhere? Like to aws-cdk-examples maybe?

**Comment by gshpychka** [comment]
> @gshpychka you mean that as drop-in replacement for `ShellStep` ?

yes

**Comment by peterwoodworth** [comment]
Just an FYI, we do have this documented in our readme for the `pipelines` module [here](https://docs.aws.amazon.com/cdk/api/v1/docs/pipelines-readme.html#customizing-codebuild-projects). Having an example for this in the examples repo wouldn't hurt though 🙂 Feel free to submit a PR or feature request on the examples repo if you'd like to see that

**Comment by kornicameister** [comment]
@peterwoodworth I was thinking about creating an example that shows how one can utilize pipelines to create gate-like step that tests if deployment is legit and infrastructure meets the hopes one has for it.

**Comment by kornicameister** [comment]
Still, I do feel like this topic has been exhausted. @gshpychka has given a good idea and I was able to confirm that it does work without giving permissions to each possible code build step.

**Comment by peterwoodworth** [comment]
Thanks for opening the feature request there 🙂
