### ISSUE TITLE
(s3-deployment): avoid asking for IAM Statement Changes every time

### ISSUE THREAD

**Issue by hugomallet** [aws/aws-cdk#18591]
### Description

Hi,

Each time I deploy a static website using the BucketDeployment construct, I have to validate the IAM Statement Changes.
It's quite annoying and I would prefer to not use "--require-approval NEVER" because it would not ask for other security changes.
Is there any solution to allow only the changes required by the bucketdeployment ?

Thanks,

### Use Case

I'd like to deploy without checking for IAM changes every time.

### Proposed Solution

Use the same bucket for each deployment ?
Or being able to allow by default some IAM changes without allowing every one ?

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by otaviomacedo** [comment]
Hi, @hugomallet. What are you changing between deployments? Are you using dynamic IDs for the bucket, by any chance?

**Comment by hugomallet** [comment]
```js
const bucket = new Bucket(this, 'Bucket', {
	websiteIndexDocument: 'index.html',
 	websiteErrorDocument: 'index.html',
	removalPolicy: RemovalPolicy.DESTROY,
});

// ...

new BucketDeployment(this, 'BucketDeployment', {
	sources: [
		Source.asset('./build/'),
	],
	destinationBucket: bucket,
	distribution: cloudfrontDist,
	distributionPaths: ['/*'],
});
```

**Comment by otaviomacedo** [comment]
I can't reproduce it. If I change the contents of the file, it re-deploys the assets. If I change any attribute in any resource, it re-deploys the stack. But it never asks me to confirm IAM changes. In your case, what changes is it asking you to confirm?

**Comment by hugomallet** [comment]
![image](https://user-images.githubusercontent.com/1888705/150805791-a1f26626-ba8b-4e1e-bbd7-f35cb00e3e1a.png)

**Comment by otaviomacedo** [comment]
The ARN of the bucket is changing. That shouldn't happen if you use a bucket created with `new Bucket(this, 'ImmutableBucketId', ...);`

And if the bucket is changing, the CLI needs to confirm that you want to apply this policy to the target bucket, which is expected.

**Comment by hugomallet** [comment]
The asset parameter value is equal to the "cdktoolkit-stagingbucket" bucket name. This bucket exists since a long time. So it's only the name of parameter that changes.

**Comment by jumic** [comment]
Which CDK version are you using?

If you are using CDK 1.x:
Are you using the `DefaultSynthesizer` (`@aws-cdk/core:newStyleStackSynthesis` feature flag enabled in `cdk.json`)?

As far as I remember, I have seen a similar behavior in my projects. However, I couldn't reproduce it at the moment (example project with CDK 2).

**Comment by jumic** [comment]
I can reproduce the behavior. It occurs if you are using the legacy bootstrapping.
You should enable the [modern bootstrapping template](https://docs.aws.amazon.com/cdk/v1/guide/bootstrapping.html#bootstrapping-templates) / `@aws-cdk/core:newStyleStackSynthesis` in your project. Then the approval is no longer required.

**Comment by hugomallet** [comment]
Fixed ! Many thanks
