### ISSUE TITLE
(aws_apigatewayv2): cannot import HttpApi in nodejs using aws-cdk-lib

### ISSUE THREAD

**Issue by endosama** [aws/aws-cdk#18597]
### General Issue

Cannot import aws_apigatewayv2.HttpApi using cdk v2

### The Question

I've recently migrated my project to CDK v2.
I'm not able to import the HttpApi construct from
`import { aws_apigatewayv2 as apigatewayv2 } from "aws-cdk-lib";`
and the linting give me the following issue
`Property 'HttpApi' does not exist on type 'typeof ..node_modules/aws-cdk-lib/aws-apigatewayv2/index`
This is my current version of the package:
`"aws-cdk-lib": "^2.8.0",`
Is the class exported at all?

### CDK CLI Version

1.91.0

### Node.js Version

16.13.1

### OS

Windows 10

### Language

Typescript

### Language Version

3.9.7

**Comment by peterwoodworth** [comment]
Hey @endosama,

Our ApiGwV2 libraries are still in "experimental" state. Our packages that aren't considered fully stable need to be installed independently in v2

`npm install @aws-cdk/aws-apigatewayv2-alpha`
```
import * as apigw from '@aws-cdk/aws-apigatewayv2-alpha'
new apigw.HttpApi(this, 'httpapi')
```

Our second bullet point in the [Migrating to V2 guide](https://docs.aws.amazon.com/cdk/v2/guide/migrating-v2.html) fully describes the lifecycle of an experimental package if you're interested 🙂

**Comment by endosama** [comment]
Sorry, I missed that 😅
Thanks a lot!
