### ISSUE TITLE
(eks): better report when resources are "complete"

### ISSUE THREAD

**Issue by ethanresnick** [aws/aws-cdk#18603]
### Description

I'd like CDK Kubernetes resources (i.e., `Custom::AWSCDK-EKS-KubernetesResource` resources) to support an optional `isComplete` handler. That way, the CDK won't show the resource as having been provisioned if something fails within the cluster. The `isComplete` handler would be powered by `kubectl wait`, with a wait condition being provided by the user (as a property on the custom resource). The CDK lib could also inspect the manifest and set a default wait condition for some resource types, to be a bit more intelligent. For example, if the resource is a Kubernetes deployment, the `isComplete` handler might wait until at least one pod in the deployment is running.

### Use Case

If my newly-updated kubernetes Deployment can't start its pods for some reason, I want to know, so I can fix it ASAP. This has happened occasionally, e.g., because of configuration issues (can't pull image from ECR), not enough cluster capacity, or some name clash.  

Right now, I suppose I could somehow add monitoring within the cluster, and propagate those errors out. But I'm already watching for errors on my CDK deployment pipeline, so it would be much more convenient if a failure within the kubernetes cluster were accurately reflected in CDK's record of the deployment, which would then lead the pipeline to fail.

My second, independent reason for wanting this is to actually be able to sequence pipeline steps more precisely. E.g., I want to have a pipeline step that runs some end-to-end tests against my app once the new deployment is live but, right now, the pipeline would move on to the test step before the new deployment is actually running.

### Proposed Solution

See above.

### Acknowledge

- [x] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by indrora** [comment]
Closing as this ticket is stale (over 9 months since last event or relates to the CDKv1). 

If this is still a relevant request in the CDKv2, please open a new ticket.
