### ISSUE TITLE
Logs: Subscription Filter with existing cross-account destination

### ISSUE THREAD

**Issue by automartin5000** [aws/aws-cdk#18600]
### Description

Not sure if this is a documentation issue or feature request, but according to [the docs](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_logs/SubscriptionFilter.html), there doesn't seem to be  a way to just use a string ARN to reference and existing cross-account Logs destination (could've been created by another CDK stack). And the CrossAccountDestination construct, doesn't support importing an existing one either, [according to the docs](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_logs/CrossAccountDestination.html).

It seems like we need a way to either import an existing CrossAccountDestination, or just pass SubscriptionFilter a [string directly](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-subscriptionfilter.html#cfn-cwl-subscriptionfilter-destinationarn).

### Use Case

Enable SubscriptionFilters with existing Logs Destinations

### Proposed Solution

Add import method to CrossAccountDestination or enable a new param to `SubscriptionFilter` that accepts a string

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by comcalvi** [comment]
have you tried doing this?

```
const function = lambda.fromFunctionArn(this, 'myLambda', 'lambdaFunctionArn');

new logs.SubscriptionFilter(this, 'Subscription', {
  logGroup,
  destination: new destinations.LambdaDestination(function),
  filterPattern: logs.FilterPattern.allTerms("ERROR", "MainThread"),
});
```
