### ISSUE TITLE
(bootstrap): Cannot use customized bootstrap bucket name

### ISSUE THREAD

**Issue by emetwall** [aws/aws-cdk#18618]
### What is the problem?

cdk deploy command fails if the bootstrapping command used a custom bucket name. 

--- Steps to reproduce -----------------

1) npx cdk bootstrap aws://111111111/us-east-1 --profile PROFILE     --cloudformation-execution-policies arn:aws:iam::aws:policy/AdministratorAccess  --change-set-name Changeset --bootstrap-bucket-name BUCKETNAME

2) cdk deploy
-------------------------------------------

Already tried the following:

a) cdk deploy -b BUCKETNAME
b) cdk deploy  --bootstrap-bucket-name BUCKETNAME
c) cdk deploy --toolkit-stack-name CDKToolkit

==> Same error. 

----Environment info-------------------
 cdk --version: 2.8.0 (build 8a5eb49)
aws --version: aws-cli/2.4.10 Python/3.8.8 Darwin/20.6.0 exe/x86_64 prompt/off
----------------------------------------

Please advice,

### Reproduction Steps

1) npx cdk bootstrap aws://111111111/us-east-1 --profile PROFILE     --cloudformation-execution-policies arn:aws:iam::aws:policy/AdministratorAccess  --change-set-name Changeset --bootstrap-bucket-name BUCKETNAME

2) cdk deploy

### What did you expect to happen?

Using the custom s3 bucket created in step 1. 

### What actually happened?

 [100%] fail: Bucket named x exists, but not in account 111111111111. Wrong account?

### CDK CLI Version

 2.8.0 (build 8a5eb49)

### Node.js Version

6.14.15

### OS

Mac

### Language

Typescript

**Comment by peterwoodworth** [comment]
Are you providing a [synthesizer](https://docs.aws.amazon.com/cdk/v2/guide/bootstrapping.html#bootstrapping-synthesizers) to your stack? Read our docs about it [here](https://docs.aws.amazon.com/cdk/v2/guide/bootstrapping.html#bootstrapping-custom-synth). You'll need to provide a custom synthesizer to tell your stack what the names of your customized bootstrapped resources are.
