### ISSUE TITLE
(aws-lambda-go): go binary in Docker image is compiled without CGO making it impossible to run local tests using sqlite

### ISSUE THREAD

**Issue by bodokaiser** [aws/aws-cdk#18611]
### Description

When using go modules which bind to C code using CGO in `GoFunction`, the compilation inside the Docker bundling fails with, e.g.,

```
Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub
```

### Use Case

While my actual `GoFunction` does not use a module which requires CGO, I run local tests before bundling
```typescript
const lambda = new GoFunction(this, 'Lambda', {
  entry: path.join(__dirname, '...'),
  bundling: {
    commandHooks: {
      beforeBundling(inputDir: string): string[] {
        return ['go test ./... -v']
      },
      afterBundling: () => [],
    },
  },
})
```

which require [`mattn/go-sqlite3`][https://github.com/mattn/go-sqlite3], a pretty common package.

### Proposed Solution

Actually, the problem is more part of the Docker image used by `GoFunction` as it hosts a `go` binary which is compiled without `CGO`.
Amending the Dockerfile to install a `go` binary with `CGO` enabled should solve the problem.

I believe the Dockerfiles used by `GoFunction` are hosted at [lambci/docker-lambda](https://github.com/lambci/docker-lambda) but the exact relation to aws-cdk is unclear to me.
Please let me know if I should open a PR at that repo.

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by corymhall** [comment]
@bodokaiser does this work if you set `cgoEnabled` to `true`?


```ts
const lambda = new GoFunction(this, 'Lambda', {
  entry: path.join(__dirname, '...'),
  bundling: {
    cgoEnabled: true,
    ...
  },
})
```

**Comment by bodokaiser** [comment]
@corymhall that worked perfectly. Great thanks :)
