### ISSUE TITLE
(pipelines): Migrating from "original" to "modern" pipelines API

### ISSUE THREAD

**Issue by plumdog** [aws/aws-cdk#18625]
### link to reference doc page

https://docs.aws.amazon.com/cdk/api/v1/docs/pipelines-readme.html

### Describe your issue?

The linked docs say:

> This module contains two sets of APIs: an original and a modern version of CDK Pipelines. The modern API has been updated to be easier to work with and customize, and will be the preferred API going forward. The original version of the API is still available for backwards compatibility, but we recommend migrating to the new version if possible.

I have recently upgraded one of our projects to a CDK version that generates deprecation warnings for use of `CdkPipeline`, which is why I've found this. I'm eager to work out what is involved in migrating (especially as the "original" API is gone in CDK v2).

On the one hand, I think this ought to be achievable without much grief, as I could just throw away the pipeline and start over, everything precious lives in the stacks deployed by the pipeline, not in the pipeline. That said, I still see plenty of scope for getting something wrong, namely in making sure the config that is "baked into" the pipeline (in my case, using `SimpleSynthAction.standardNpmSynth` and `copyEnvironmentVariables`, see https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_pipelines.StandardNpmSynthOptions.html#copyenvironmentvariablesspan-classapi-icon-api-icon-deprecated-titlethis-api-element-is-deprecated-its-use-is-not-recommended%EF%B8%8Fspan) still works and that the source branch is correct (in my case, using `GitHubSourceAction`.

The answer might just be "start over and build a logically equivalent pipeline using the new API", which is what I intend to do, but it would be extremely helpful if the docs could offer more guidance on this.

**Comment by stekern** [comment]
Not sure if you've already seen this, but there is a short migration guide available here: https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/pipelines/ORIGINAL_API.md.

If you haven't used a lot of custom configuration in your pipeline, you should be able to do the upgrade using the guide above and manually inspecting the diff between the old and new CloudFormation templates you get from `cdk synth` before deploying the changes.

**Comment by plumdog** [comment]
Aha! Not sure how I missed that, but that is definitely going to be useful.

**Comment by hsg777** [comment]
> Not sure if you've already seen this, but there is a short migration guide available here: https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/pipelines/ORIGINAL_API.md.
> 
> If you haven't used a lot of custom configuration in your pipeline, you should be able to do the upgrade using the guide above and manually inspecting the diff between the old and new CloudFormation templates you get from `cdk synth` before deploying the changes.

This is helpful. Thanks!
