### ISSUE TITLE
(aws-lambda-python): Command Hook support

### ISSUE THREAD

**Issue by tmokmss** [aws/aws-cdk#18621]
### Description

It would be great if `PythonFunction` also supports command hook feature, which is already supported by  [`NodeJsFunction`](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda_nodejs.BundlingOptions.html#commandhooks) and [`GoFunction`](https://docs.aws.amazon.com/cdk/api/v2/docs/@aws-cdk_aws-lambda-go-alpha.BundlingOptions.html#commandhooksspan-classapi-icon-api-icon-experimental-titlethis-api-element-is-experimental-it-may-change-without-noticespan).

### Use Case

e.g. downloading other dependent binaries during bundling a python function.

### Proposed Solution

tbw

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by corymhall** [comment]
I am unassigning and marking this issue as `p2`, which means that we are unable to work on this immediately.

We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://join.slack.com/t/cdk-dev/shared_invite/zt-mso6p56d-qJp7SOTBvMaQuDrx7R2wHg) to solicit support for reprioritization.

**Comment by tmokmss** [comment]
It still should be open.

**Comment by madeline-k** [comment]
This is already supported in the aws-lambda-python module: https://docs.aws.amazon.com/cdk/api/v2/docs/@aws-cdk_aws-lambda-python-alpha.BundlingOptions.html#commandhooksspan-classapi-icon-api-icon-experimental-titlethis-api-element-is-experimental-it-may-change-without-noticespan 

There is an example in the readme as well: https://docs.aws.amazon.com/cdk/api/v2/docs/aws-lambda-python-alpha-readme.html#command-hooks

Please go try it out! And open new issues if you experience problems with it, or if you have additional feature requests.

**Comment by madeline-k** [comment]
Shoutout to @webratz who contributed this recently! https://github.com/aws/aws-cdk/pull/23330 🎉

**Comment by tmokmss** [comment]
Cool, thanks!
