### ISSUE TITLE
aws-cdk-lib: Property 'node' does not exist on type 'App'.

### ISSUE THREAD

**Issue by alex-hladun** [aws/aws-cdk#18627]
### General Issue

aws-cdk-lib: Property 'node' does not exist on type 'App' when using app.node.tryGetContext

### The Question

Currently trying to migrate to aws-cdk-lib v2.8.0, and am having a problem retrieving the build context. 

Current implementation

```
import * as cdk from "aws-cdk-lib";
import { configurations } from "./configurations";
import { MyStack } from "./my-stack";

const app = new cdk.App();
const buildEnvironment = (app.node.tryGetContext("env") || "dev").trim().toLowerCase();
new MyStack(app, "website" + buildEnvironment, configurations[buildEnvironment]);

```

I am getting TS error on line 6, _Property 'node' does not exist on type 'App'_
Is there something i'm doing wrong? This is straight out of the docs
https://docs.aws.amazon.com/cdk/v2/guide/get_context_var.html

Note: Trying to access within the class constructor throws the same warning.
`const env = this.node.tryGetContext("env");`

### CDK CLI Version

2.8.0

### Node.js Version

14.15.5

### Language

Typescript

### Language Version

TS 3.9.0

**Comment by alex-hladun** [comment]
solved by using `process.env.ENV` as part of our build pipeline

**Comment by peterwoodworth** [comment]
Check your package.json to make sure all cdk versions are the same, and try reinstalling your node packages for good measure. This error usually shows up due to something like that 🙂

**Comment by guledmahdi** [comment]
adding https://www.npmjs.com/package/constructs to my application resolved this.
`npm i constructs`
