### ISSUE TITLE
(cdk.Fn.importValue): Error while importing outputs in stacks

### ISSUE THREAD

**Issue by jayPJ** [aws/aws-cdk#18646]
### General Issue

Error while importing outputs in stacks

### The Question

When Trying to import **ServiceEndpoint** value in stack 1 using **cdk.Fn.importValue(INFRA+"ServiceEndpoint"))** ,kind of value which is received doing cdk synth is different from what expected. I am receiving value **"https://${Token[TOKEN.102]}.execute-api.us-east-1.${Token[AWS.URLSuffix.6]}/${Token[TOKEN.120]}/"**, which should be a simple service endpoint, because of this I am unable to use API in creating cfnBasePathMapping.

* Output of stack 2

```ts
    new cdk.CfnOutput(this, "ServiceEndpoint", {
      description: "URL of the service endpoint",
      value: api.url,
      exportName:INFRA + "ServiceEndpoint",
    });
```

### CDK CLI Version

1.110.1

### Node.js Version

14.17.6

### OS

Windows 10

### Language

Typescript

**Comment by jayPJ** [comment]
Please respond.

**Comment by skinny85** [comment]
Hey @jayPJ,

thanks for opening the issue. Can you show your entire code, not just the part that defines the output? We'll try to reproduce the issue.

Thanks,
Adam

**Comment by jayPJ** [comment]
Yes sure, I have attached below portion code which will help you to reproduce issue.
* When doing cdk synth getting "https://${Token[TOKEN.102]}.execute-api.us-east-1.${Token[AWS.URLSuffix.6]}/${Token[TOKEN.120]}/" as output of console.log
* Code snippet
**Stack which has export function**

import { Stack, StackProps, Construct, Fn } from "@aws-cdk/core";
import * as cdk from "@aws-cdk/core";
import * as ssm from "@aws-cdk/aws-ssm";
import apigateway = require("@aws-cdk/aws-apigateway");
import { EndpointType } from "@aws-cdk/aws-apigateway";
import { CfnParameter } from "@aws-cdk/core";

export class B3Infra extends Stack {
  constructor(scope: Construct, id: string, props: StackProps = {}) {
    super(scope, id, props);
    
    const api = new apigateway.RestApi(this, "b3", {
      deploy: true,
      deployOptions: {
        stageName: "INFRA",
      },
      defaultCorsPreflightOptions: {
        allowHeaders: [
          "Content-Type",
          "X-Amz-Date",
          "Authorization",
          "X-Api-Key",
        ],
        allowMethods: apigateway.Cors.ALL_METHODS,
        allowCredentials: true,
        allowOrigins: apigateway.Cors.ALL_ORIGINS,
        statusCode: 200,
      },
      endpointConfiguration: {
        types: [EndpointType.EDGE],
      },
    });

    new cdk.CfnOutput(this, "ServiceEndpoint", {
      description: "URL of the service endpoint",
      value: api.url,
      exportName: "ServiceEndpoint",
    });
  }
}

**Stack which has import function** 

import * as cdk from "@aws-cdk/core";
import { Stack, StackProps, Construct, Fn } from "@aws-cdk/core";
export class Route53Stack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props: cdk.StackProps = {}) {
    super(scope, id, props);
    const API_URL = cdk.Fn.importValue("ServiceEndpoint");
    console.log("url..............." + API_URL);
  }
}

**Comment by peterwoodworth** [comment]
@jayPJ this is because ImportValue returns a token, which represents a value that can't be immediately determined at runtime. Please read more about tokens [here](https://docs.aws.amazon.com/cdk/v2/guide/tokens.html) 🙂 

I'm not sure what the exact problem you're seeing is with this, let me know and I'll try to help
