### ISSUE TITLE
(@aws-cdk/aws-lambda-event-sources): Allow for more control over the lambda service role

### ISSUE THREAD

**Issue by flosky** [aws/aws-cdk#18643]
### Description

When I do this: `myLambda.function.addEventSource(new SqsEventSource(eventQueue));` then this will automatically add the permissions to the lambda service role for this queue, see [here](https://github.com/aws/aws-cdk/blob/9ed263cde0b41959ff267720c0978bfe7449337a/packages/%40aws-cdk/aws-lambda-event-sources/lib/sqs.ts#L79)

I am proposing to allow to skip this so I can add my own permissions to the lambda service role.

### Use Case

I wanted to have two sub-stacks in my project, one for shared resources and one for the lambda functions and triggers. So I created the lambda service role in the shared stack and imported it into the lambda stack to be attached to all the lambda functions. This went well until I added an sqs event trigger to my lambda. After that I got a circular dependency issue. This is because the role is imported from my shared stack into my lambda stack, but since the role needs to be updated, it is also imported from the lambda stack into the shared stack (circle complete).

If would prefer to set up my role as I need it, including the rights to access sqs and just attach it to my lambdas.

### Proposed Solution

I see two options:

1. Check before adding the sqs rights if that is even necessary. So if the role already has enough access rights, there is no need to update the permissions
2. Allow for control for this when calling `function.addEventSource()`. So adding a config property where I can set `updateLambdaServiceRole: false`

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by kaizen3031593** [comment]
Of the two proposed solutions, I feel like 1) is more promising, but is likely a breaking change. 2) i suppose we can do, but I cant think of comparable situations elsewhere in the cdk where we do this.

**Comment by flosky** [comment]
@kaizen3031593 Thanks for your input on this. Maybe I am just not getting the way you have envisioned how a good cdk project should be structured. In general I like the idea of you taking care of the iam permissions, as they can get really tricky. But I hope you see my point. If I want to go your way, I would create a separate role per lambda instead of having one shared role across all lambdas in my project/service. Is that something you would recommend?

With a service that would use Api Gateway and Lambda to implement a REST API, it is likely that there are many request handlers, so many lambdas and then also many roles. This can lead to problems with the amount of resources per stack.
