### ISSUE TITLE
(Code Pipeline): GitHub connection is not triggering on push 

### ISSUE THREAD

**Issue by AlessandroVol23** [aws/aws-cdk#18656]
### What is the problem?

I've added a GitHub connection with CodeStar and added the connection in the input step of the pipeline:

```ts
    const githubConnection = pipelines.CodePipelineSource.connection(
      "org/repo",
      "main",
      {
        connectionArn: ARN
        triggerOnPush: true,
      }
    );
```

```ts
    const pipeline = new pipelines.CodePipeline(this, "CdkPipeline", {
      synth: new pipelines.ShellStep("Synth", {
        input: githubConnection,
        installCommands: ["yarn install --frozen-lockfile"],
        commands: ["npx cdk synth"],
      }),
    });
```

The pipeline works if I execute it manually but it doesn't work if I push to the repository. The app is installed in GitHub and I gave it rights to all repositories and tried giving it just permissions for one as well.

### Reproduction Steps

```ts
    const githubConnection = pipelines.CodePipelineSource.connection(
      "org/repo",
      "main",
      {
        connectionArn: ARN
        triggerOnPush: true,
      }
    );
```

```ts
    const pipeline = new pipelines.CodePipeline(this, "CdkPipeline", {
      synth: new pipelines.ShellStep("Synth", {
        input: githubConnection,
        installCommands: ["yarn install --frozen-lockfile"],
        commands: ["npx cdk synth"],
      }),
    });
```

In a CDK Stack 

### What did you expect to happen?

I expect that for every push on the branch `main` the pipeline will be triggered

### What actually happened?

When I push to the GitHub repository the pipeline won't be triggered. 

### CDK CLI Version

2.8.0 (build 8a5eb49)

### Node.js Version

v14.18.2

### OS

Mac OS Latest

### Language

Typescript

### Language Version

3.9.7

### Other information

Slack thread: https://cdk-dev.slack.com/archives/C017RG58LM8/p1643178957068279

**Comment by rob3c** [comment]
@AlessandroVol23 I know it's  counterintuitive, but have you tried it without the triggerOnPush setting?

I only set the ARN and don't set triggerOnPush explicitly (I think it's a default behavior), and I have multiple pipelines that'll trigger on any push to any repo set using the input and additionalInputs properties. They're all explicitly allowed in the GitHub app.

(Also, you have a typo and are missing a comma after ARN, but I suspect that's not in your actual code or typescript would complain.)

**Comment by AlessandroVol23** [comment]
Yes I tried that as well because it should be by default `true`. 

Missing comma is not in the actual code that's true. I think I don't see the typo 😃

**Comment by AlessandroVol23** [comment]
TIL: Organization name or account name is case-sensitive (of course)
