### ISSUE TITLE
(custom-resources): expose OnEventRequest and OnEventResponse from provider-framework 

### ISSUE THREAD

**Issue by dbartholomae** [aws/aws-cdk#18666]
### Description

Expose `OnEventRequest` and `OnEventResponse` for usage in custom-resource lambdas directly on `aws-cdk-lib/custom-resources` instead of `aws-cdk-lib/custom-resources/lib/provider-framework/types`.

### Use Case

When writing Custom resource lambdas in TypeScript, it would be great to be able to rely on parameter and return types.

### Proposed Solution

Expose `OnEventRequest` and `OnEventResponse` for usage in custom-resource lambdas directly on `aws-cdk-lib/custom-resources` instead of `aws-cdk-lib/custom-resources/lib/provider-framework/types`.

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by rix0rrr** [comment]
Unfortunately, these cannot be exposed because they are not jsii compatible. You can copy/paste the definitions though.

**Comment by girotomas** [comment]
```
import {
  OnEventRequest,
  OnEventResponse,
} from 'aws-cdk-lib/custom-resources/lib/provider-framework/types'
```
