### ISSUE TITLE
 no lambda.OutputFormat.ESM for aws-lambda-nodejs

### ISSUE THREAD

**Issue by smaud** [aws/aws-cdk#18674]
### What is the problem?

(aws-lambda-nodejs-readme)[https://docs.aws.amazon.com/cdk/api/v1/docs/aws-lambda-nodejs-readme.html] documents an output format for ESBUILD, however  there is no lambda.OutputFormat.ESM 

### Reproduction Steps

* install cdk v2.8.0
* create simple lambdanodejs function in cdk for -l=typescript app
* try and set lambda.OutputFormat to ESM
* nothing in the types helper

### What did you expect to happen?

expected lambda.OutputFormat.ESM 

### What actually happened?

no lambda.OutputFormat.ESM 

### CDK CLI Version

 2.8.0

### Node.js Version

16

### OS

Ubuntu

### Language

Typescript

**Comment by jogold** [comment]
The prop is named `format` (under `bundling`) and accepts a `OutputFormat` enum (exported by `aws-lambda-nodejs`. 

See https://github.com/aws/aws-cdk/tree/v2.8.0/packages/%40aws-cdk/aws-lambda-nodejs#configuring-esbuild.

It should be there in V2.8.0.

**Comment by smaud** [comment]
“Should”!==”is”

You’re a coder, you should know this.

**Comment by jogold** [comment]
> “Should”!==”is”

Well it **is** there, see content of the published package at https://unpkg.com/browse/aws-cdk-lib@2.8.0/aws-lambda-nodejs/lib/types.d.ts

![image](https://user-images.githubusercontent.com/12623249/151453644-17ddace9-0416-40f1-aaae-77e85d2997fb.png)
![image](https://user-images.githubusercontent.com/12623249/151453674-ba1c0029-e901-4b75-9578-b5efeccbdd16.png)

**Comment by smaud** [comment]
And you’re using the same version of CDK as that in the ticket? Because it doesn’t work in my version of CDK.

**Comment by jogold** [comment]
Yes, `aws-cdk-lib` v2.8.0.

Check your node modules/installation.

**Comment by smaud** [comment]
I did that before raising the ticket.

I’ll upgrade to 2.9 see if that fixes it, if not I’ll re-open the ticket.

**Comment by peterwoodworth** [comment]
It's present for me on both 2.8.0 and 2.9.0
