### ISSUE TITLE
CodePipeline: CodeBuildAppStack' depends on 'CodePipelineAppStack'  cyclic reference 

### ISSUE THREAD

**Issue by AreebSiddiqui** [aws/aws-cdk#18671]
### What is the problem?

I have two stacks.
One for CodeBuild and another for CodePipeline. I have been passing CodeBuild Stack into the CodePipeline Stack.
```
const codebuildStack = new CodeBuildStack(app, 'CodeBuildAppStack');

new CodePipeline(app, 'CodePipelineAppStack', codebuildStack);
```

This Gives me an error: 

> /node_modules/aws-cdk-lib/core/lib/stack.ts:395
>       throw new Error(`'${target.node.path}' depends on '${this.node.path}' (${cycle.join(', ')}). Adding this dependency (${reason}) would create a cyclic reference.`);

The CodeBuildStacks works fine alone but once I pass this stack in CodePipelineStack the error pops up.

### Reproduction Steps

CodePipeline.ts

```ts
export class CodePipeline extends Stack {
  public readonly SourceStage: codepipeline.IStage;
  public readonly BuildStage: codepipeline.IStage;
  public readonly DeployStage: codepipeline.IStage;
  public readonly codePipelineRole: iam.Role;

  constructor(scope: Construct, id: string, codeBuild: CodeBuildStack, props?: StackProps) {
    super(scope, id, props)
    this.codePipelineRole = new iam.Role(this, `CodePipelineRole`, {
      roleName: `CodePipelineRole`,
      assumedBy: new iam.ServicePrincipal('codebuild.amazonaws.com'),
      managedPolicies: [
        iam.ManagedPolicy.fromAwsManagedPolicyName(
          'AmazonEC2ContainerRegistryPowerUser',
        ),
      ]
    });
    
    const pipeline = new codepipeline.Pipeline(this, `MyCodePipeline`, {
      pipelineName: 'my-codepipeline',
      role:this.codePipelineRole,
      crossAccountKeys: false,
    });
    
    const sourceOutput = new codepipeline.Artifact();

    this.SourceStage = pipeline.addStage({
      stageName: 'Source',
      actions: [
        new codepipelineActions.CodeStarConnectionsSourceAction({
          actionName: 'Source',
          owner: `onwername`,
          repo: 'reponame',
          connectionArn:'my-arn',
          triggerOnPush:true,
          output: sourceOutput
        })
      ],
    })


    this.BuildStage = pipeline.addStage({
      stageName: 'Build',
      placement: {
        justAfter: this.SourceStage
      },
      actions: [
        new codepipelineActions.CodeBuildAction({
          actionName:'CodeBuild',
          input:sourceOutput,
          project: codeBuild.projectABC
        })
      ]
    })
  }
}
```

### What did you expect to happen?

I am trying to use codebuild stack inside codepipeline stack. 

### What actually happened?

This Gives me an error: 

> /node_modules/aws-cdk-lib/core/lib/stack.ts:395
>       throw new Error(`'${target.node.path}' depends on '${this.node.path}' (${cycle.join(', ')}). Adding this dependency (${reason}) would create a cyclic reference.`);

### CDK CLI Version

2.8.0 (build 8a5eb49)

### Node.js Version

v16.6.2

### OS

Ubuntu 20.04.1 LTS (fossa-beric-tgl X40)

### Language

Typescript

**Comment by skinny85** [comment]
Hey @AreebSiddiqui,

is the problem you're experiencing the same as in https://github.com/aws/aws-cdk/issues/3300?

Thanks,
Adam

**Comment by AreebSiddiqui** [comment]
Yes, but a little different I am not targetimg to deploy both stack in different accounts.

I need to deploy both stacks in same account.
@skinny85

**Comment by skinny85** [comment]
I don't think cross-account is the crux of the problem in that issue either.

I'll close this as a duplicate, and let's move the conversation to https://github.com/aws/aws-cdk/issues/3300 - if you could post there, I would appreciate it.
