### ISSUE TITLE
(aws-eks): external dns deployment

### ISSUE THREAD

**Issue by Hunter-Thompson** [aws/aws-cdk#18688]
### Description

Just like the AWS LB Controller deployment is a part of the eks module, external DNS should be too. These 2 go hand in hand.

### Use Case

Without external DNS a cluster is not fully operational.

### Proposed Solution

```
externalDnsController: {
    version: ...
    policy: ...
    containerArgs: ...
},
```

External DNS helm chart can be deployed by CDK.

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Notes

I will create a draft PR in a few days.

**Comment by otaviomacedo** [comment]
Hi, @Hunter-Thompson. Just curious: can't you use `cluster.addHelmChart()`?

**Comment by Hunter-Thompson** [comment]
hey, @otaviomacedo, we currently do exactly that. Since the CDK v2, I saw that there was a construct added to deploy the AWS load balancer controller as a part of the EKS module. Which is a step in the right direction.

So I thought I could whip up a quick PR to also add the external DNS controller. Since both of these go hand in hand.

Is this something the CDK team would be willing to have in the eks module?

**Comment by otaviomacedo** [comment]
> Is this something the CDK team would be willing to have in the eks module?

Yes. I'd be happy to review your PR.

**Comment by peterwoodworth** [comment]
@Hunter-Thompson have you been able to get to this?

**Comment by runev-admin** [comment]
> @Hunter-Thompson have you been able to get to this?

Yup, 2 years later. I wish EKS get more love than this.
