### ISSUE TITLE
(cdk-events): RuleTargetInput.fromText inserts escape characters when it should not

### ISSUE THREAD

**Issue by Martin521** [aws/aws-cdk#18695]
### What is the problem?

When creating a scheduled `Events.Rule` for a `Events.Targets.LambdaFunction` with `Events.RuleTargetInput`, `Events.RuleTargetInput.FromText mytext` puts double quotation marks around mytext and escapes double quotation marks in mytext. This modified string is passed on to the event target and is also visible in the EventBridge console.

This means `Events.RuleTargetInput.FromText mytext` cannot be used to pass json to a lambda function. Which I thought was its intended purpose.

### Reproduction Steps

Sorry, the below is dotnet F#. But it should be straightforward to reproduce it in other languages.

1. Create a lambda function and an event rule by the following code:
```
    let request = """{"Action": "Test"}"""
    let ruleLambdaProps = Events.Targets.LambdaFunctionProps (Event = Events.RuleTargetInput.FromText request)
    let ruleProps = Events.RuleProps (
        Schedule = Events.Schedule.Cron(Events.CronOptions(Minute = "0")),
        Targets = [|Events.Targets.LambdaFunction (testLambda, ruleLambdaProps)|])
    do Events.Rule (this, "TestRule", ruleProps) |> ignore

```
2. Check TestRule in the EventBridge console.

### What did you expect to happen?

In the EventBridge console, when I edit the rule, under "Configure input", I expect to see `{"Action": "Test"}`

### What actually happened?

I do see `"{\"Action\": \"Test\"}"`

### CDK CLI Version

2.8.0

### Framework Version

2.8.0

### Node.js Version

v16.13.1

### OS

Windows 11

### Language

.NET

### Language Version

dotnet (6)

**Comment by rix0rrr** [comment]
> This means Events.RuleTargetInput.FromText mytext cannot be used to pass json to a lambda function. Which I thought was its intended purpose.

Can you please tell me where you read that? We need to change it.


![image](https://user-images.githubusercontent.com/524162/151803507-8a780621-1e5c-4205-86c3-161091790ccb.png)

https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-events.RuleTargetInput.html#static-fromwbrobjectobj

**Comment by Martin521** [comment]
I read it from the method signature `public static fromText(text: string): RuleTargetInput`.
What else would the method do?

**Comment by richardnagle** [comment]
See https://stackoverflow.com/questions/64893782/creating-a-rule-with-a-constant-json-parameter-in-aws-cdk-c for workaround

**Comment by ericljiang** [comment]
I'm confused, this seems to be a bug regardless of whether the text happens to be JSON or not, right? If I use
```ts
RuleTargetInput.fromText("foo")
```
with an SQS target, when I retrieve the message body, I get `"\"foo\""` instead of `"foo"`
