### ISSUE TITLE
(lambda-event-sources): Lambda event source is not removed when deploying CDK application

### ISSUE THREAD

**Issue by dbadami** [aws/aws-cdk#18706]
### What is the problem?

I've recently upgrade to CDK 1.140.0 from 1.119.0 and decided to take advantage of the native support for adding an SQS event source to a Lambda function. To do so I deleted the existing EventSourceMapping in code in favor of the native solution but when deploying the application I encountered the following the error:

 >***Stack: creating CloudFormation changeset... 4:50:32 AM | CREATE_FAILED | AWS::Lambda::EventSourceMapping | ***..ry69C3A26D4B0792A0 Resource handler returned message: "An event source mapping with SQS arn (" arn:aws:sqs:*** ") and function (" ***V21AE54-asmVruavSRPT ") already exists. Please update or delete the existing mapping with UUID 2e1ba402-c92c-4d6f-97b8-c 0acfdc4bc3f
 
 *Resources names and ARNs have been redacted.*

### Reproduction Steps

Output of `git diff`:
```
-    // Until reportBatchItemFailures is supported natively
-    new lambda.EventSourceMapping(this, "SourceMapping", {
-      target: lambdaFunction,
-      eventSourceArn: this.queue.queueArn,
-      reportBatchItemFailures: true,
-    });
+    lambdaFunction.addEventSource(
+      new lambdaSources.SqsEventSource(this.queue, {
+        reportBatchItemFailures: true,
       })
     );
```

### What did you expect to happen?

For the application to successfully deploy.

### What actually happened?

The deployment failed because there was already an existing event source mapping for the same queue ARN and Lambda function name/ARN/identifier. 

### CDK CLI Version

1.140.0

### Node.js Version

v.14.18.3

### OS

Amazon Linux 2

### Language

Typescript

### Language Version

TypesScript(3.9.7)

### Other information

Potentially related issue:
https://github.com/aws/serverless-application-model/issues/1320

**Comment by ryparker** [comment]
You'll likely need to deploy your stack without the old resources to properly delete them from AWS. Then you should be able to deploy the updated/new CDK resources.

The updated CDK code must not be 1 for 1 with what you had before. Try running `cdk diff` to see the proposed CloudFormation changes. This might bring clarity as to why you'll need to destroy the old resource beforehand.

**Comment by dbadami** [comment]
Output of `cdk diff`:
```
Resources
[-] AWS::Lambda::EventSourceMapping ***317457A9 destroy // old mapping
[+] AWS::Lambda::EventSourceMapping ***/***/SqsEventSource:***69C3A26D ***V2SqsEventSource***Stack***69C3A26D4B0792A0 // new mapping
```
I'd expect this not to be in the diff because there isn't anything changing but the fact that CF treats these as two different resources, however unexpected, this behaviour makes sense to me.
