### ISSUE TITLE
[aws-ec2] file exceeding PyCharms idea.max.intellisense.filesize default value

### ISSUE THREAD

**Issue by crane-denny** [aws/aws-cdk#18711]
### What is the problem?

PyCharm is not able to generate autocompletion, type hints, etc for `aws_ec2` 

### Reproduction Steps

Open a current project with PyCharm and try using autocompletion for anything within `aws_ec2`.

### What did you expect to happen?

To use my smart IDE features. Otherwise I could stay with `vim`.

### What actually happened?

Nothing. PyCharm is not aware of anything within this module

### CDK CLI Version

2.9.0

### Node.js Version

v16.13.2

### OS

macOS 

### Language

Python

### Other information

PyCharm (and other JetBrains IDEs) has an advanced option called `idea.max.intellisense.filesize`. The purpose of the option is:

```
Sets the maximum size of files (in kilobytes) for which PyCharm provides code assistance. Code assistance for large files can decrease editor performance and increase memory consumption.
```
[1]

The init file of the module `aws_ec2` has grown that much in size that it's exceeding the default value of `2500`. This results in lacking features like autocompletion, type hinting, etc for this module. So basically everything why people choose modern IDEs over basic `vim`. :)

To get everything working again I set the value to `5000` following the instructions here[2].

My suggestions would be:

1. Update the docs that people using JetBrains IDEs are aware of this and know how to workaround.
2. Split modules into smaller files to stay below the default value. (long term fix)

Shout out to JetBrains and their support which helped me to identify the problem and the workaround.

[1] https://www.jetbrains.com/help/pycharm/file-idea-properties.html
[2] https://www.jetbrains.com/help/objc/configuring-file-size-limit.html#file-length-limit

**Comment by njlynch** [comment]
Thanks for filing this issue, and sorry for the inconvenience.

It sounds like the best plan (for now) is to update the Dev Guide Python section (https://docs.aws.amazon.com/de_de/cdk/v2/guide/work-with-cdk-python.html) with this specific guidance. 

We'll work with our docs team to get that updated.

**Comment by RomainMuller** [comment]
Yes - at least short term, adding guidance in the documentation is the only thing we can do.

I had looked into breaking down into smaller files, however this is far from trivial as it's very easy to get into import cycles when doing so. There might be something we can do so we don't have to tune advanced parameters of JetBrains IDEs (and perhaps others, too), but that's probably going to take a while before it materializes.

**Comment by RomainMuller** [comment]
I created an issue on `aws/jsii` to track the long term fix: https://github.com/aws/jsii/issues/3365

**Comment by frankwese** [comment]
Just for reference and to help others, that found this issue via a search engine:
For changing this property in IntelliJ Idea refer to:
https://www.jetbrains.com/help/idea/tuning-the-ide.html#common-platform-properties
- Go to Help | Edit Custom Properties 
I had to set `idea.max.intellisense.filesize` to more than 6000
