### ISSUE TITLE
CodeBuildAction: Adding outputs creates an error

### ISSUE THREAD

**Issue by VXConsulting** [aws/aws-cdk#18710]
### What is the problem?

When I add more than one outputs artefact in the CodeBuildAction, the codebuild step in codepipeline is on error:
"Invalid input: identifier must contain only alphanumeric characters and underscores and be less than 128 characters in length"

### Reproduction Steps

```ts
const BuildArtefact1 = new Artifact('artifact1');
const BuildArtefact2 = new Artifact('artifact2');

        new CodeBuildAction({
            actionName: `Build`,
            project: cdkBuild,
            input: sourceInput,
            outputs: [BuildArtifact1, BuildArtifact2],
        });
```
### What did you expect to happen?

The step cannot be on error because first, it is not an input error and second, we must be able to store the artifacts separately.

### What actually happened?

"Invalid input: identifier must contain only alphanumeric characters and underscores and be less than 128 characters in length"

### CDK CLI Version

2.9

### Node.js Version

14.17.3

### OS

Ubuntu 20.04

### Language

Typescript

### Language Version

Typescript 4.5.4

**Comment by skinny85** [comment]
Hey @VXConsulting,

thanks for opening the issue. Can you show more of your code. I just tried this, and it synthesizes without issues:

```ts
        const BuildArtifact1 = new codepipeline.Artifact('artifact1');
        const BuildArtifact2 = new codepipeline.Artifact('artifact2');

        new cpactions.CodeBuildAction({
            actionName: `Build`,
            project: codebuild.Project.fromProjectName(this, 'Project', 'my-project'),
            input: new codepipeline.Artifact(),
            outputs: [BuildArtifact1, BuildArtifact2],
        });
```

(Also, your code doesn't compile; you have variables `BuildArtefact1` and `BuildArtefact2`, but you reference `BuildArtifact1` and `BuildArtifact2`)

Thanks,
Adam

**Comment by VXConsulting** [comment]
Hello,
Thanks for your answer.
The problem is not to synthesize or to build. 

The problem is when it is deployed, Codepipeline raises and error which has no sense.
 I declare 2 outputs and I have an error : "invalid input ..."

But, I suspect that it is not a CDK problem but a Codepipeline one.

Kind Regards

**Comment by skinny85** [comment]
Again, without seeing your entire pipeline code, not just a tiny snippet, it's hard for me to say what might be the problem 🙂.
