### ISSUE TITLE
(dynamodb): add support for Table Class in Table construct

### ISSUE THREAD

**Issue by arjanschaaf** [aws/aws-cdk#18718]
### Description

DynamoDB offers two table classes designed to help you optimize for cost. The DynamoDB Standard table class is the default, and is recommended for the vast majority of workloads. The DynamoDB Standard-Infrequent Access (DynamoDB Standard-IA) table class is optimized for tables where storage is the dominant cost.
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.TableClasses.html

Support already exists in CloudFormation, but hasn't been implemented in CDK.

### Use Case

To create new tables or update existing tables to use the new DynamoDB Standard-IA table class.

### Proposed Solution

Extending the Table construct implementation to include this CloudFormation attribute.

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by nathanagez** [comment]
Hi @skinny85, any idea on when you will be able to merge the PR ? :)

**Comment by joekendal** [comment]
+1
