### ISSUE TITLE
(all): API docs version switcher doesn't work on mobile

### ISSUE THREAD

**Issue by alexpulver** [aws/aws-cdk#18735]
### link to reference doc page

https://docs.aws.amazon.com/cdk/api/v1/docs/pipelines-readme.html

### Describe your issue?

If I try to follow the link for switching to v2 documentation, the website redirects me to the main page.

**Comment by njlynch** [comment]
Hi Alex,

Can you clarify what happens vs what you expect? For me, the version switcher is operating the same on both mobile and desktop; clicking on it links to the version page. Choosing a version then takes you to the main page for that version. Is that what you're seeing?

**Comment by alexpulver** [comment]
Hi Nick,

I could record the video of this behavior. You can see that for the first time, clicking on v2 documentation switches the version and stays on the module page. But if I go back and try again, it switches to v2 main documentation page, and doesn't stay on the module page. Initially the latter was the consistent behavior for me, but now I see that it's random.

Hope this helps :).

https://user-images.githubusercontent.com/4362270/152103151-9afe617a-3a84-44b3-b1be-40e2f594a009.mp4

**Comment by alexpulver** [comment]
On the desktop, I also see this behavior randomly. To note, switching to v2 and staying on the module page is an extremely useful feature. Consider my flow - I am searching for "cdk pipelines docs", and land on v1 documentation. But I am actually interested in v2 documentation. Having this link switch versions and stay on the module page doesn't require me to search for the CDK Pipelines module again in v2 documentation.

**Comment by alexpulver** [comment]
Okay, now I see what happens. On the initial page load, the URL default is to v2 main documentation page. Waiting for a second, it is updated to v2 module documentation page (with double `/`). 

![Screen Shot 2022-02-02 at 8 25 47](https://user-images.githubusercontent.com/4362270/152104807-eeaf9218-6185-4642-87ac-ba3d4480994a.png)

![Screen Shot 2022-02-02 at 8 26 30](https://user-images.githubusercontent.com/4362270/152104809-cbe398e8-37cf-43a2-b272-5616891f739b.png)

**Comment by njlynch** [comment]
Ah, you're talking about the "Click here to view the v2 documentation" link, rather than the version number (what I'd call the version switcher) in the upper-lefthand corner. The video was actually really useful! :)

I believe @corymhall did that implementation; re-assigning to him to take a look.

**Comment by corymhall** [comment]
@alexpulver the double `//` issues should be fixed now. Can you let me know if that fixed the issue for you?

**Comment by alexpulver** [comment]
@corymhall the `//` issue is fixed, thanks! It still renders the top level API documentation page URL first though. I need to wait a second or more in order for the URL to get updated and take me to the documentation of the module for v2.

**Comment by alexpulver** [comment]
@corymhall I tried https://docs.aws.amazon.com/cdk/api/v1/docs/pipelines-readme.html and I see the behavior as you described it (website and mobile). Thank you! 😃
