### ISSUE TITLE
(core): CDK Diff GetTemplate doesn't include ChangeSet resources?

### ISSUE THREAD

**Issue by gwright99** [aws/aws-cdk#18738]
### What is the problem?

Hello, I am a new user of CDK and Localstack. I'm not sure if this is a bug but it seems like it so I'm opening a ticket.

I am following this [cdkworkshop tutorial](https://cdkworkshop.com/30-python/30-hello-cdk/100-cleanup.html) and am not able to replicate the same  `diff` behaviour in my own environment:

* When I run `diff` locally, my implementation never shows resources that will be deleted, only added.
* If the tutorial is to be believed, I should see currently-deployed resources flagged with [-] if they are no longer present in my CDK code.

##### Sample app code used for first deployment
```python
from constructs import Construct
from aws_cdk import (
    Duration,
    Stack,
    aws_iam as iam,
    aws_sqs as sqs,
    aws_sns as sns,
    aws_sns_subscriptions as subs,
)

class MyFirstCdkStack(Stack):

    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        queue = sqs.Queue(
            self, "MyFirstCdkQueue",
            visibility_timeout=Duration.seconds(300),
        )

        topic = sns.Topic(
            self, "MyFirstCdkTopic"
        )

        topic.add_subscription(subs.SqsSubscription(queue))
```
Result from diff:
```bash
$ cdklocal diff
Stack my-first-cdk
IAM Statement Changes
┌───┬────────────────────────┬────────┬─────────────────┬───────────────────────────┬────────────────────────────────────────────────────────┐
│   │ Resource               │ Effect │ Action          │ Principal                 │ Condition                                              │
├───┼────────────────────────┼────────┼─────────────────┼───────────────────────────┼────────────────────────────────────────────────────────┤
│ + │ ${MyFirstCdkQueue.Arn} │ Allow  │ sqs:SendMessage │ Service:sns.amazonaws.com │ "ArnEquals": {                                         │
│   │                        │        │                 │                           │   "aws:SourceArn": "${MyFirstCdkTopic}"                │
│   │                        │        │                 │                           │ }                                                      │
└───┴────────────────────────┴────────┴─────────────────┴───────────────────────────┴────────────────────────────────────────────────────────┘
(NOTE: There may be security-related changes not in this list. See https://github.com/aws/aws-cdk/issues/1299)

Resources
[+] AWS::SQS::Queue MyFirstCdkQueue MyFirstCdkQueue8D02FB05
[+] AWS::SQS::QueuePolicy MyFirstCdkQueue/Policy MyFirstCdkQueuePolicy552A29F8
[+] AWS::SNS::Subscription MyFirstCdkQueue/myfirstcdkMyFirstCdkTopic8692486F MyFirstCdkQueuemyfirstcdkMyFirstCdkTopic8692486FBEFC9D06
[+] AWS::SNS::Topic MyFirstCdkTopic MyFirstCdkTopic10E6401F

Other Changes
[-] Unknown ChangeSetName: cdk-deploy-change-set
[-] Unknown StackName: my-first-cdk
```

##### Sample app code used for second deployment (no other changes made other than commented line) 
```python
from constructs import Construct
from aws_cdk import (
    Duration,
    Stack,
    aws_iam as iam,
    aws_sqs as sqs,
    aws_sns as sns,
    aws_sns_subscriptions as subs,
)


class MyFirstCdkStack(Stack):

    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        queue = sqs.Queue(
            self, "MyFirstCdkQueue",
            visibility_timeout=Duration.seconds(300),
        )

        topic = sns.Topic(
            self, "MyFirstCdkTopic"
        )

        #topic.add_subscription(subs.SqsSubscription(queue))
```
Result from diff:
```bash
$ cdklocal diff
Stack my-first-cdk
Resources
[+] AWS::SQS::Queue MyFirstCdkQueue MyFirstCdkQueue8D02FB05
[+] AWS::SNS::Topic MyFirstCdkTopic MyFirstCdkTopic10E6401F

Other Changes
[-] Unknown ChangeSetName: cdk-deploy-change-set
[-] Unknown StackName: my-first-cdk
```

I believe the problem is due to the CDK pushing deployments via ChangeSets, but only specifying the StackName when retrieving the currently-deployed template against which the local code is compared. 

##### Localstack log resulting from a `cdklocal deploy` command

`localstack_main | 2022-01-29T19:21:49.891:DEBUG:localstack.services.edge: IN(cloudformation): "POST /" - headers: {'Remote-Addr': '172.17.0.1', 'User-Agent': 'aws-sdk-nodejs/2.1059.0 linux/v16.13.2 aws-cdk/2.9.0 promise', 
'Content-Type': 'application/x-www-form-urlencoded; charset=utf-8', ---- REMOVED CREDENTIAL_STUFF_HERE ----  
'x-localstack-edge': 'http://localhost:4566'} - data: b'Action=CreateChangeSet&Capabilities.member.1=CAPABILITY_IAM&Capabilities.member.2=CAPABILITY_NAMED_IAM&Capabilities.member.3=CAPABILITY_AUTO_EXPAND&ChangeSetName=cdk-deploy-change-set&ChangeSetType=UPDATE&Description=CDK%20Changeset%20for%20execution%20297a723c-ecf9-47c1-95b6-b45acac60b6b&Parameters.member.1.ParameterKey=BootstrapVersion&Parameters.member.1.UsePreviousValue=true&RoleARN=arn%3Aaws%3Aiam%3A%3A000000000000%3Arole%2Fcdk-hnb659fds-cfn-exec-role-000000000000-us-east-1&StackName=my-first-cdk&Tags=&TemplateURL=https%3A%2F%2Fs3.us-east-1.amazonaws.com%2Fcdk-hnb659fds-assets-000000000000-us-east-1%2Fa4c7e5e5caa3e19d90ea64705c4b3f51eefa84ce8f929cd4450f6157ef4ce382.json&Version=2010-05-15'`

##### Localstack log resulting from a `cdklocal diff` command

`localstack_main | 2022-01-29T19:21:55.606:DEBUG:localstack.services.edge: IN(cloudformation): "POST /" - headers: {'Remote-Addr': '172.17.0.1', 'User-Agent': 'aws-sdk-nodejs/2.1059.0 linux/v16.13.2 aws-cdk/2.9.0 promise', 'Content-Type': 'application/x-www-form-urlencoded; charset=utf-8', 'Content-Length': '63', 'Host': 'localhost:4566', 'X-Amz-Date': '20220129T192155Z', ---- REMOVED CREDENTIAL_STUFF_HERE ---- , 'Connection': 'close', 'X-Forwarded-For': '172.17.0.1, localhost:4566', 'x-localstack-edge': 'http://localhost:4566'} -  data: b'Action=GetTemplate&StackName=my-first-cdk&TemplateStage=Original&Version=2010-05-15'`

### Localstack Consideration
As a result of this investigation, I found a bug in the localstack code and submitted a [PR to fix it](https://github.com/localstack/localstack/pull/5394). In short:
* `awslocal cloudformation get-template --stack-name my-first-cdk` seems to return only bare bones CF which I believe is generated as part of the bootstrapping process.
* `awslocal cloudformation get-template --stack-name my-first-cdk --change-set-name cdk-deploy-change-set` returns the bare bones details PLUS all the Resources deployed by the latest `cdk deploy` action.

Am I doing something wrong here? This behaviour is literally one of the first commands run during the AWS tutorial but I've spent a few days Googling and troubleshooting, and haven't seen anybody else complaining about this issue. Am I doing something wrong, or is this actually a bug?

Thank you for your assistance!

### Reproduction Steps

Steps:
1. Invoke a docker-compose instance of `localstack/localstack:latest`  (ensure no IAM enforcement)
2. `mkdir my-first-cdk && cd my-first-cdk`
3. `cdklocal init sample-app --language python`
2. `awslocal ssm put-parameter --name "/cdk-bootstrap/hnb659fds/version" --value "8" --type "String"`
3. `cdklocal bootstrap`
4. `cdklocal deploy`
5. Confirm resources were successfully deployed.
6. Comment out 1 or more Resources in _my_first_cdk_stack.py_.
7. `cdklocal diff`

### What did you expect to happen?

I expect `cdklocal diff` to identify when currently deployed Resources will be destroyed in my next deployment due to their removal from my CDK code.

### What actually happened?

Deletions are never identified. I'm only ever shown that all the resources in my CDK code will be added.

### CDK CLI Version

2.9.0 (build a69725c)

### Node.js Version

v16.13.2

### OS

Ubuntu 20.04.3 LTS (via WSL 2)

### Language

Python

### Language Version

3.10.0

### Other information

As mentioned above, I found I a bug in the Localstack code and submitted a [PR to fix it](https://github.com/localstack/localstack/pull/5394) on January 29, 2022. 

While waiting for the PR to be merged, I've been using my fix by mounting a modified Python file into my localstack container.

**Comment by gwright99** [comment]
Update: I was able to get the `cdk diff` command to now show additions and subtractions. 

I had to further modify the localstack [`get_template`](https://github.com/localstack/localstack/blob/master/localstack/services/cloudformation/cloudformation_api.py#L933) function to check if the returned Stack object had an associated ChangeSetId. If a change set was found, the localstack GetTemplate function was re-invoked with the original **StackName** provided by CDK and the ChangeSetId I resolved inside the function.

![image](https://user-images.githubusercontent.com/1309341/151709210-1cb15a72-0913-4e05-971f-b36d7ad7df9d.png)

**Comment by rix0rrr** [comment]
It seems the bug report is in essence:

> When using LocalStack, `cdk diff` shows an unexpected result

I'm going to assume this is because LocalStack behaves differently than AWS CloudFormation does. If so, that is a LocalStack issue and not a CDK issue.

We will accept this as a CDK issue if you can reproduce the same behavior with AWS CloudFormation. Please file a new issue with reproduction steps if you do.
