### ISSUE TITLE
Improvements for cdk init typescript

### ISSUE THREAD

**Issue by rantoniuk** [aws/aws-cdk#18743]
### General Issue

Improvements for cdk init typescript

### The Question

After running `cdk init app --language=typescript` and checking how the project is set up, I can see the following that could be improved:

- `@aws-cdk` dependencies are pinned, while they could (should?) use `^1.141.0`
- `typescript` major version is 3.x, could be bumped to `~4.4.4`
- `import 'source-map-support/register';` line doesn't seem to be needed

tsconfig.json
- add `"outDir": "dist"` and `dist` to `exclude` section to keep the workspace clean 

Happy to provide PR if the above make sense, please let me know where to look though.

### CDK CLI Version

1.141.0

### Node.js Version

14

### OS

MacOS

### Language

Typescript

**Comment by peterwoodworth** [comment]
Hey @rantoniuk,

Our init templates can be found [here](https://github.com/aws/aws-cdk/tree/7966f8d48c4bff26beb22856d289f9d0c7e7081d/packages/aws-cdk/lib/init-templates)

I don't think we'll want to pin dependencies or remove source map support, but I think we'd like to have the TS version upgraded 🙂 

I'm unsure if we'll want to make the tsconfig change either

**Comment by rantoniuk** [comment]
Hi @peterwoodworth 

- TS version [is pinned](https://github.com/aws/aws-cdk/blob/7966f8d48c4bff26beb22856d289f9d0c7e7081d/packages/aws-cdk/lib/init-templates/v1/sample-app/typescript/package.template.json#L21) and needs to be pinned because of incompatibility warning.
- I can see [%cdk-version%](https://github.com/aws/aws-cdk/blob/ca208058256703759ae5e35d04194edbdc6b1756/packages/aws-cdk/lib/init-templates/v1/sample-app/typescript/package.template.json#L14) but I can't find where it is defined/how it is computed. The resulting version should contain `~` or `^` instead of pinning specific cdk version.

I cannot react to the other two responses, since they do not contain any reason/explanation.
I will just wait then for a specific answer before creating any PRs in order not to waste time on both sides :)

**Comment by hoegertn** [comment]
For CDK v1 the version needs to be pinned as it will explode with version incompatibilities otherwise

**Comment by rantoniuk** [comment]
It will not explode if package-lock is used and all packages are upgraded when new packages are added.
We are using it this way and it works fine (indeed, we had the exploding problem indeed if not using `npm upgrade` after adding new packages).

**Comment by rantoniuk** [comment]
> A package-lock.json will not help you when adding new versions though.

`package-lock.json` together with `npm upgrade` and `^` modifier works perfectly fine.
Indeed, if you don't want to promote the usage of the lockfile (which is a bad practice not only for CI), then sure, that will cause problems.

> The TypeScript version is dictated by the [JSII version](https://github.com/aws/jsii) we use.

Surely it should not be dictated up to a pinned version, but to a compatible version - i.e. it should use at least `~` to be able to get security fixes.

**Comment by TheRealAmazonKendra** [comment]
Thank you for your suggestions here. Given that we are unable to upgrade TypeScript at this time, need the `source-map-support/register`, and no longer use individual imports on v2, I think this issue should be closed at this time. If there are further improvements you'd like to propose on our v2 templates and/or believe this issue was closed in error, please feel free to open a new issue.
