### ISSUE TITLE
(cloudwatch): Add dashboard_arn property to dashboard

### ISSUE THREAD

**Issue by kornicameister** [aws/aws-cdk#18744]
### Description

I would like to be able to construct, use cloud watch dashboard ARN in my policies.
Having a property would make it easier and align resource to other resources that expose the ARN property.

### Use Case

Building IAM policies to enable dashboard access.

### Proposed Solution

Add a property to `Dashboard` resource that produces ARN based on `arn:${Partition}:cloudwatch::${Account}:dashboard/${DashboardName}` called `dashboardArn`.
Property will be readonly.

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by kornicameister** [comment]
In the same time I don't see a possibility to get back `dashboard_name`, so might be an idea here as well.

**Comment by TheRealAmazonKendra** [comment]
Resolved by #20059 and #17721.
