### ISSUE TITLE
(sns): default .fifo suffix for FIFO topics

### ISSUE THREAD

**Issue by skyrpex** [aws/aws-cdk#18740]
### Description

https://github.com/aws/aws-cdk/issues/12386 introduced a requirement to add a topic name whenever a FIFO topic is created.

Do you think it's a good idea to generate a default name if it isn't provided by the user? All of the other CDK resources are named consistently using something similar to what `cdk.Names.nodeUniqueId(node)` does, ie `MyStack2EC66409Topic.fifo`, which prevents name collisions.

### Use Case

Remove the need to manually define a topic name. 

### Proposed Solution

This is my current implementation:

```ts
import * as cdk from "aws-cdk-lib"
import { Construct, Node } from "constructs"

export class Topic extends cdk.aws_sns.Topic {
  public constructor(
    scope: Construct,
    id: string,
    properties?: cdk.aws_sns.TopicProps,
  ) {
    super(scope, id, {
      ...properties,
      topicName:
        properties?.topicName ?? properties?.fifo
          ? buildFifoName(scope.node, id)
          : undefined,
    })
  }
}

export function buildFifoName(node: Node, id: string) {
  const uniqueId = cdk.Names.nodeUniqueId(node)
  const suffix = `${id}.fifo`
  // Make sure that the name fits within the CFN's 80 character limit
  return `${uniqueId.slice(0, Math.max(0, 80 - suffix.length))}${suffix}`
}
```

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by njlynch** [comment]
It looks like CloudFormation has it on their roadmap to fix this so a topic name _doesn't_ need to be input at creation; however, there's not been on update on the issue in over a year:
https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/681

The above proposal -- to autogenerate a name and suffix the '.fifo' if a name is not provided -- sounds reasonable to me. Contributions welcome!

**Comment by mjsztainbok** [comment]
There is an issue with the code above. If you at SQS (for example), the names are generated using the stack name as the prefix. In this case though it looks like `Names.uniqueId()` just uses the ID's of the stack for the prefix of the ID which causes issues if you have mutltiples of the same stack but with different stack names (which is what we are doing so that we can have individual stacks for development and CI/CD test purposes).

I modified the code as follows to correct this:
```typescript
 private static replaceStackId(scope: Construct, id: string): string {
    const stack = cdk.Stack.of(scope);

    // Replace the stack ID in the identifier with the stack name
    return id.replace(stack.node.id, stack.stackName);
  }

  // TODO: Added temporarily until https://github.com/aws/aws-cdk/issues/18740 is released in a new CDK release
  // The code is taken from the issue to be consistent for when it gets released
  private static buildFifoName(scope: Construct, id: string) {
    const uniqueId = this.replaceStackId(
      scope,
      cdk.Names.uniqueId(scope)
    );
    const suffix = `${id}.fifo`;
    // Make sure that the name fits within the CFN's 80 character limit
    return `${uniqueId.slice(0, Math.max(0, 80 - suffix.length))}${suffix}`;
  }

```

**Comment by dreamorosi** [comment]
I think this issue could be closed. The PR with the fix has been merged and the new behavior has been released yesterday
