### ISSUE TITLE
(route53): ability to create cross region alias to VPC interface endpoint

### ISSUE THREAD

**Issue by pawelzebrowski** [aws/aws-cdk#18758]
### Description

There doesn't appear to be any way to create a route53 alias targeting an Interface Endpoint in a different region

### Use Case

1. A Private Link endpoint is created in a VPC vpc-us-east-1 in us-east-1.  The private link is only exposed in this region.
2. A VPC vpc-us-west-2 is created in us-west-2 and peered with vpc-us-east-1.  All routing is set up.
3. A Private Zone needs to be created for vpc-us-west-2 with an alias record targeting the private link endpoint in vpc-us-east-1.  This doesn't seem possible through CDK today (though possible through console).

### Proposed Solution

Any viable solution that doesn't require aws-sdk or console.  Some guesses:

Add `region` to `ec2.InterfaceVpcEndpoint.fromInterfaceVpcEndpointAttributes` (though i think `fromInterfaceEndpointAttributes` may not be compatible with `new targets.InterfaceVpcEndpointTarget`:
```
    new route53.ARecord(this, `new-record`, {
      zone: some-zone,
      recordName: 'some-record',
      target: route53.RecordTarget.fromAlias(
        new targets.InterfaceVpcEndpointTarget(
          ec2.InterfaceVpcEndpoint.fromInterfaceVpcEndpointAttributes(
            this,
            'some-interface-endpoint',
            {
              port: 443,
              vpcEndpointId: 'vpce-xxxxx',
              region: 'us-east-1'
            }
          )
        )
      ),
    });
```

Similar approach with bind():
```
    new route53.ARecord(this, `new-record`, {
      zone: some-zone,
      recordName: 'some-record',
      target: route53.RecordTarget.fromAlias({
        bind() {
          return {
            dnsName: 'private-link-endpoint-url',
            hostedZoneId: 'private-link-endpoint-hosted-zone',
          };
        },
      }),
    });
```

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by peterwoodworth** [comment]
Working on a similar request here https://github.com/aws/aws-cdk/pull/20530

Would love it if you could help contribute this use case!

**Comment by shikha372** [comment]
@pawelzebrowski we could use below approach in CDK to create a route53 alias targeting an interface endpoint in different region : 
` 
#Detail of first VPC hosting the endpoint
    const vpc2 = Vpc.fromVpcAttributes( this,
        'vpcregion1-test2',
        {
            vpcId: 'vpcid',
            availabilityZones: ['us-west-1b'],
            region: 'us-west-1',
        }
    ); 

#Assuming this a first VPC with hosted zone that needs to refer to vpc endpoint
const testzone = new HostedZone(this, 'private-zone', {
        vpcs: [vpc1], #VPC not hosting the endpoint
        zoneName: 'TestVpcPeeredZone',
    });

#This will add vpc of another region to existing 
    testzone.addVpc(vpc2); #another region vpc hosting the endpoint can be added using fromLookup() or fromVpcAttributes() specifying region

        new ARecord(this, `new-record`,{
        zone: testzone,
        recordName: 'some-record',
        target: RecordTarget.fromAlias({
            bind() {
                return {
                    dnsName: 'EndpointDNSName',
                    hostedZoneId: 'ZoneIDforEndpointDNS',
                };
            },
    }),
});
    `
