### ISSUE TITLE
AWS SSO: Throttling issue while deploying permission-sets via aws-cdk

### ISSUE THREAD

**Issue by emJeay** [aws/aws-cdk#18750]
### What is the problem?

We've recently adopted AWS SSO and creating Permission-sets using aws-cdk. The cdk-deploy fails with the below error when we try to create more than 100 permission-sets per deploy.

`Internal Failure (RequestToken: <xxxx>)`

Based on the discussion we had with AWS premium support for our org, this is a throttling issue with AWS SSO. They told me that AWS SSO throttles requests when the limit of 20 transactions per second (TPS) is breached. However, since we are building the AWS SSO components via aws-cdk, ideally CDK should be aware of this limit and make the APIs call with the dependency in place.

### Reproduction Steps

We have an application build using AWS CDK that creates AWS SSO permission-sets and assignments for all accounts in our organisation. So permission-sets are created at an account level since they inherit some complex intrinsic functions, so essentially creating ~100+ resources per permission. 
When we trigger 'cdk deploy' AWS CDK appears to trigger the "RESOURCE CREATION" for all the ~100+ resource at the same time. Cloudformation then fails with an "Internal Failure" error that we've explained above. So, ideally if AWS SSO has a TPS limit (20 TPS/sec), AWS CDK should be restricting itself to just make API calls within that limit. It would be really hard for us to bootstrap the 'dependency' mechanism in the app as this is more of a platform dependency that the development-kit should be able to handle. 

### What did you expect to happen?

AWS CDK to deploy ~100+ AWS SSO components without any failure.

### What actually happened?

AWS CDK failed with the below error:

`Internal Failure (RequestToken: <xxxx>)`

### CDK CLI Version

v2.10.0

### Node.js Version

v14.14.0

### OS

linux, mac os

### Language

Python

### Language Version

Python v3.8.6

### Other information

**Please note:** we have already raised this with AWS Support and was directed to raise it in this forum. We can email the case ID separately if required.

**Comment by skinny85** [comment]
Hi @emJeay,

thanks for opening the issue. Would you mind showing your CDK code creating the SSO resources?

Unfortunately , since CDK uses CloudFormation for deployments, I'm not sure we can do much here. But, this might be a good issue to report to the CloudFormation team.

Thanks,
Adam
