### ISSUE TITLE
Ability to lookup up a web socket api gateway statically

### ISSUE THREAD

**Issue by dtabuenc** [aws/aws-cdk#18755]
### Description

Web Socket Api gateway is missing any static lookup `from*` type methods similar to HttpApi such as  `HttpApi.fromHttpApiAttributes`

This makes it very difficult to reference the web socket gateway from another stack.

### Use Case

With Http API we have some setups where we define a single api gateway and then add routes and authorizers from other stacks in other repositories, allowing different microservice repositories to manage their own routes on a shared gateway/domain. We want to do something ismilar with WebSocketApi.

### Proposed Solution

I imagine something similar to what is currently don in HttpApi.

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by vincent-turato** [comment]
I would like to work on a PR for this
