### ISSUE TITLE
(ecs): Deployment hangs when creating FargateService with assign_public_ip = false, but all VPC subnets are public

### ISSUE THREAD

**Issue by crane-denny** [aws/aws-cdk#18766]
### What is the problem?

When all subnets within the VPC are public and the `FargateService` is constructed with the default value of `assign_public_ip`which is `False` then it hangs there forever.

### Reproduction Steps

Create vpc with only public subnets
Start a FargateService where we use the default of `assign_public_ip`.

### What did you expect to happen?

An error that only public subnets are available
or
a warning that only public subnets are available and he will set `assign_public_ip` to `True`
or
none of the above and just proceeding and using the default of the subnet to assign or not assign a public IP

### What actually happened?

Hangs forever, I killed it after 20min

### CDK CLI Version

2.9.0

### Node.js Version

v16.13.2

### OS

macOS

### Language

Python

**Comment by madeline-k** [comment]
Thanks for opening this issue @crane-denny , can you please provide the minimal amount of your CDK code that reproduces the issue?
