### ISSUE TITLE
cannot import name 'BootstrapRole' from 'aws_cdk.cloud_assembly_schema'

### ISSUE THREAD

**Issue by DHANYAV20** [aws/aws-cdk#18761]
### What is the problem?

while creating vpc 
`$cdk ls `
it shows 
```
Traceback (most recent call last):
  File "app.py", line 3, in <module>
    from aws_cdk import core
  File "D:\gitconnected\vpc\.env\lib\site-packages\aws_cdk\__init__.py", line 1014, in <module>
    from .cloud_assembly_schema import (
ImportError: cannot import name 'BootstrapRole' from 'aws_cdk.cloud_assembly_schema' (D:\gitconnected\vpc\.env\lib\site-packages\aws_cdk\cloud_assembly_schema\__init__.py)
```

### What did you expect to happen?

To create vpc using cdk

### Node.js Version

V16.13.2

### OS

Windows 10

### Language

Python

### Language Version

Python 3.10

**Comment by ryparker** [comment]
This is not enough information. Can you provide some code to help us reproduce this?

**Comment by peterwoodworth** [comment]
Try deleting and reinstalling your packages, and if you're still using v1 make sure that all of your cdk packages are the same version 🙂

**Comment by ravyshankar** [comment]
> ### What is the problem?
> while creating vpc `$cdk ls ` it shows
> 
> ```
> Traceback (most recent call last):
>   File "app.py", line 3, in <module>
>     from aws_cdk import core
>   File "D:\gitconnected\vpc\.env\lib\site-packages\aws_cdk\__init__.py", line 1014, in <module>
>     from .cloud_assembly_schema import (
> ImportError: cannot import name 'BootstrapRole' from 'aws_cdk.cloud_assembly_schema' (D:\gitconnected\vpc\.env\lib\site-packages\aws_cdk\cloud_assembly_schema\__init__.py)
> ```
> 
> ### What did you expect to happen?
> To create vpc using cdk
> 
> ### Framework Version
> _No response_
> 
> ### Node.js Version
> V16.13.2
> 
> ### OS
> Windows 10
> 
> ### Language
> Python
> 
> ### Language Version
> Python 3.10
> 
> ### Other information
> _No response_

Hi,
How did you resolve this issue? I have the same problem. 

I installed CDK and imported AWS construct library modules few minutes back following the first 2 links below. 
Step1: https://docs.aws.amazon.com/cdk/v2/guide/work-with.html#work-with-prerequisites
Step 2: https://docs.aws.amazon.com/cdk/v2/guide/work-with-cdk-python.html
Step 3: https://docs.aws.amazon.com/cdk/v2/guide/hello_world.html
I am currently at step3 issuing "cdk ls" command and I get an error "ImportError: cannot import name 'AssetManifestOptions' from 'aws_cdk.cloud_assembly_schema' (C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aws_cdk\cloud_assembly_schema_init_.py)"

I am a newbie to CDK, Coding, IaC. First time doing this. Could you please share the steps to resolve the problem? 

```
PS C:\Users\user\Documents\hello-cdk> python --version
Python 3.11.2

PS C:\Users\user\Documents\hello-cdk> cdk --version
2.67.0 (build b6f7f39)

PS C:\Users\user\Documents\hello-cdk> cat .\requirements.txt
aws-cdk-lib==2.67.0
constructs>=10.0.0,<11.0.0

PS C:\Users\user\Documents\hello-cdk> aws --version
aws-cli/2.9.23 Python/3.9.11 Windows/10 exe/AMD64 prompt/off
```
