### ISSUE TITLE
(aws-cdk-lib): Aspects doesn't pick up resources that have been symlinked

### ISSUE THREAD

**Issue by bestickley** [aws/aws-cdk#18778]
### What is the problem?

Aspects doesn't pick up resources that have been symlinked

### Reproduction Steps

Follow steps in README here: https://github.com/bestickley/cdk-aspects-error

### What did you expect to happen?

Aspects should throw error picking up bucket

### What actually happened?

Aspects doesn't throw error picking up bucket.

### CDK CLI Version

2.10.0

### Framework Version

2.10.0

### Node.js Version

16.13.2

### OS

macOS

### Language

Typescript

### Language Version

3.9.7

**Comment by apriceaws** [comment]
Hi, I recently ran into this problem and conducted a very similar test:

`class AspectTest implements cdk.IAspect {
    public visit(node: any): void {
        if(node.hasOwnProperty("cfnResourceType")){
            console.log(`${node instanceof CfnResource} ${node.cfnResourceType} ${node.node.path}`)
        }
    }
}`

I've discovered that the Aspect does actually visit all resources, but the 'instanceof' always evals to false if the construct was created in another library in my lerna monorepo.

**Comment by apriceaws** [comment]
I was able to successfully run my test with expected results (node instanceof CfnResource evals to true) by pushing my shared libs from my mono repo into proper NPM packages (instead of relying on symlinks created by lerna bootstrap).

**Comment by bestickley** [comment]
This works now for me!
