### ISSUE TITLE
(apigateway): put-rest-api mode not working

### ISSUE THREAD

**Issue by ghourtonb-myhotel** [aws/aws-cdk#18775]
### What is the problem?

We are using the following script to upload several resources to an API and then deploy each of them in different stages.
The problem is that even though we give it mode --overwrite it does what it wants (sometimes it takes the overwrite and sometimes the merge)

I leave an example of the line we use:

aws apigateway put-rest-api --rest-api-id $apigateway_id --mode overwrite --body file://API-public.yaml --profile $aws_profile --no-cli-pager --generate-cli-skeleton

Thanks!

### Reproduction Steps

using put-rest-api with mode

aws apigateway put-rest-api --rest-api-id $apigateway_id --mode overwrite --body file://API-public.yaml --profile $aws_profile --no-cli-pager --generate-cli-skeleton

### What did you expect to happen?

It should perform the action with the method that is specified

### What actually happened?

Use a ramdon method (sometimes it works with overwrite and sometimes with merge), since all calls are with overwrite

### CDK CLI Version

aws-cli/2.4.5 Python/3.9.9 Darwin/21.2.0 source/x86_64 prompt/off

### Node.js Version

v17.2.0

### OS

macOs

### Language

Python

**Comment by ryparker** [comment]
This looks like an issue with AWS CLI not AWS CDK (Cloud Development Kit).

Here's a link to create an issue for the CLI: https://github.com/aws/aws-cli/issues/new/choose

**Comment by ghourtonb-myhotel** [comment]
my bad, so sorry

**Comment by ryparker** [comment]
No problem 👍🏻
