### ISSUE TITLE
(aws-cdk-lib/aws-ec2): CDK v1.120.0+ generates inconsistent logical IDs & aws:cdk:path values for VPC Endpoints

### ISSUE THREAD

**Issue by damnhandy** [aws/aws-cdk#18798]
### What is the problem?

Prior to [CDK 1.120.0](https://github.com/aws/aws-cdk/releases/tag/v1.120.0), VPC Endpoints would have a consistent logical ID and `aws:cdk:path` value in the synthesized CloudFormation template. Starting with [CDK 1.120.0](https://github.com/aws/aws-cdk/releases/tag/v1.120.0) and beyond, CDK will generate new logical ID and `aws:cdk:path` values every time the project is synthesized. If one is applying the stack to update to an existing deployment, the `cdk deploy` phase will always fails as it's attempting to replace the existing VPC endpoint. 

### Reproduction Steps

There is a detailed test case here that demonstrates the issue:

https://github.com/damnhandy/cdk-vpc-endpoint-issue

There are 3 test cases:

  - [vpc-endpoints-initial](https://github.com/damnhandy/cdk-vpc-endpoint-issue/blob/main/vpc-endpoints-initial/): Uses CDK 1.119.0 and expresses the expected state of the resource names. The test case will pass in this project. 
  - [vpc-endpoints-latest-cdk1](https://github.com/damnhandy/cdk-vpc-endpoint-issue/blob/main/vpc-endpoints-latest-cdk1/): The same code as `vpc-endpoints-initial`, but uses the latest version of the CDK 1.x series. At the time of this writing it `1.142.0`. The test case will fail in this project.  
  -  [vpc-endpoints-latest-cdk2](https://github.com/damnhandy/cdk-vpc-endpoint-issue/tree/main/vpc-endpoints-latest-cdk2): The same code as `vpc-endpoints-initial`, but uses the latest version of the CDK 2.x series. At the time of this writing it `2.10.0`. The code has been modified slightly to reflect the changes in CDK2, but otherwise the same. The test case will fail in this project. 
  
This page has the full details of the issue we're seeing in CDK 1.142.0: 

https://github.com/damnhandy/cdk-vpc-endpoint-issue/blob/main/vpc-endpoints-latest-cdk1/README.md

### What did you expect to happen?

In versions of CDK version `1.119.0` and lower, logical IDs were consistently generated for VPC Endpoints. Given a VPC logical ID of `Vpc` for the VPC resource, a Cloud Watch Logs VPC Endpoint Resource would be synthesized like the following:

```json
 "Vpclogs2AF248A8": {
      "Type": "AWS::EC2::VPCEndpoint",
      "Properties": {
      ...
      "Metadata": {
        "aws:cdk:path": "VpcEndpointsStack/Vpc/logs/Resource"
      }
      ...
```  
As long as the resource itself hasn't changed significantly, subsequent `cdk synth` commands would always generate the same logical ID and a consistent `aws:cdk:path` value. Thus, a `cdk diff` against a previously deployed version of the stack would not attempt to replace the exiting VPC endpoint.

### What actually happened?

Starting [CDK 1.120.0](https://github.com/aws/aws-cdk/releases/tag/v1.120.0), CDK generates very different results:

```json
 "Vpc11118F9CFEB": {
      "Type": "AWS::EC2::VPCEndpoint",
      "Properties": {
      ...
      "Metadata": {
        "aws:cdk:path": "VpcEndpointsStack/Vpc/111]}/Resource"
      }
      ...
```  
Subsequent `cdk synth` executions will consistently yield different logical IDs and `aws:cdk:path` values. It changes on every call to `cdk synth` and `cdk deploy` will ALWAYS attempt to replace the VPC endpoint. However, this will always fail as Cloudformation there's now a DNS conflict. This is what you will see on a subsequent deployments with versions greater than `v1.120.0`:

```
VpcEndpointsStack: deploying...
VpcEndpointsStack: creating CloudFormation changeset...
10:22:57 AM | CREATE_FAILED        | AWS::EC2::VPCEndpoint                 | Vpc11254D247BB
private-dns-enabled cannot be set because there is already a conflicting DNS domain for logs.us-east-1.amazonaws.com in the VPC vpc-02320065bbc98001a (Service: AmazonEC2; Status Code: 400; Error Code: InvalidParameter; Request ID: 07119
69c-bf25-4697-a15a-dde9981b0da9; Proxy: null)
```

### CDK CLI Version

1.142.0, 2.10.0

### Framework Version

1.142.0, 2.10.0

### Node.js Version

16.13.0

### OS

macOS 12 and CentOS 7

### Language

Typescript

### Language Version

3.9.7

**Comment by corymhall** [comment]
@damnhandy It looks like your issue is due to the `InterfaceVpcEndpointAwsService` being updated to use [Tokens](https://docs.aws.amazon.com/cdk/v2/guide/tokens.html). Now the `InterfaceVpcEndpointAwsService.CLOUDWATCH_LOGS` will look something like this.

```
InterfaceVpcEndpointAwsService {                                                                                                                                                                                      
  privateDnsDefault: true,                                                                                                                                                                                            
  name: '${Token[TOKEN.113]}.${Token[TOKEN.112]}.logs${Token[TOKEN.114]}',                                                                                                                                            
  port: 443                                                                                                                                                                                                           
} 
```

You'll either need to update your `addInterfaceEndpoints` function to take into account the Tokens or you can try to resolve them like this.

```ts
 addInterfaceEndpoints(...services: InterfaceVpcEndpointAwsService[]): void {
    for (const service of services) {
      const resolvedService = cdk.Stack.of(this).resolve(service);
      const serviceId = resolvedService.name.split(".").pop() as string;
      this.vpc.addInterfaceEndpoint(serviceId, {
        service: service
      });
    }
  }
```

**Comment by damnhandy** [comment]
@corymhall that solution worked like a champ! In order for this to work reliably, the account ID and region must be set. This is fine for my use case, but more work needed if one were to define a generic stack. Thanks again for the assist!
