### ISSUE TITLE
(aws-cdk) Version of Lambda already exists when Migrate to aws-cdk 2.0

### ISSUE THREAD

**Issue by DarshanAwachat** [aws/aws-cdk#18797]
### General Issue

(aws-cdk) Version of Lambda already exists when Migrate to aws-cdk 2.0

### The Question

After Migrating to aws-cdk 2.0. Getting this error when trying to deploy 
`A version for this Lambda function exists ( n ). Modify the function to create a new version.`

### CDK CLI Version

2.10.0

### Language

Typescript

**Comment by argenstijn** [comment]
Could somebody look at this problem. I have the same problem. In CDK v1 this was solved by using a feature @aws-cdk/aws-lambda:recognizeVersionProps.

Is this still needed in CDK v2?

**Comment by argenstijn** [comment]
Still not working even when using:

    "@aws-cdk/aws-lambda:recognizeVersionProps": true,

**Comment by DarshanAwachat** [comment]
I got rid of the issue by changing the description of the Lambda? But do we need do this every time if the hash gets changed I am to figure out.

**Comment by argenstijn** [comment]
That should not be necessary. Worked in CDK 1 should still work in CDK 2

**Comment by argenstijn** [comment]
Using CDK diff i saw that the version hash is different between CDK v1 and v2. So the lambda is not changed but the version is. That is causing this problem.  So adding something to the lambda like a description will fix this problem. 

[-] AWS::Lambda::Version awsLambdaiapidevnlpmasterlambdaCurrentVersionAEE4D9EFad0cf1a93d35b2242b40aa7dc6aa5305 destroy
[+] AWS::Lambda::Version awsLambda/iapi-dev-nlp-master-lambda/CurrentVersion awsLambdaiapidevnlpmasterlambdaCurrentVersionAEE4D9EFf30f0bf075604a777d4724e95de7a764

**Comment by peterwoodworth** [comment]
Yes, making a trivial change here is the recommended guidance 🙂
