### ISSUE TITLE
(cdk-cli): cdk deploy always synth the stack

### ISSUE THREAD

**Issue by daknhh** [aws/aws-cdk#18790]
### Description

In order to use cdk deploy in a CI/CD with a cdk diff before it would be nice to have a --no-synth parameter for the cdk deploy because otherwise you are synth the stack twice. 

### Use Case

In order to use cdk deploy in a CI/CD with a cdk diff before it would be nice to have a --no-synth parameter for the cdk deploy because otherwise you are synth the stack twice. 

### Proposed Solution

Add --no-synth for cdk deploy

### Acknowledge

- [ ] I may be able to implement this feature request
- [X] This feature might incur a breaking change

**Comment by hoegertn** [comment]
For this you execute cdk like `cdk --app cdk.out deploy` and it uses the already created cloud assembly in the specified folder instead of running synth.

**Comment by rix0rrr** [comment]
Thanks @hoegertn for chiming in :)
