### ISSUE TITLE
(opensearch): Trying to enable useUnsignedBasicAuth fails cdk deploy with totally unrelated error message

### ISSUE THREAD

**Issue by stefan-enev** [aws/aws-cdk#18807]
### What is the problem?

I'm working on an Amplify project which has a custom CDK stack. CDK stack contains an opensearch instance configured inside a VPC. I need to restore a dump on that instance and for that reason am trying to enable unsigned basic auth following the documentation here https://docs.aws.amazon.com/cdk/api/v1/docs/aws-opensearchservice-readme.html#using-unsigned-basic-auth

https://docs.aws.amazon.com/opensearch-service/latest/developerguide/vpc.html#vpc-architecture

### Reproduction Steps

Using:
* amplify-cli 7.6.14
* @aws-cdk/aws-opensearchservice: 1.142.0

Here's the OpenSearch construct being used:
```ts
export interface OpenSearchProps {
  domain: string
  vpc: Vpc
  securityGroup: SecurityGroup
}

export class OpenSearch extends Construct {
  constructor(scope: Construct, id: string, props: OpenSearchProps) {
    super(scope, id)

    const slr = new iam.CfnServiceLinkedRole(this, 'Service Linked Role', {
      awsServiceName: 'es.amazonaws.com',
    })

    const domain = new opensearch.Domain(this, props.domain, {
      version: opensearch.EngineVersion.OPENSEARCH_1_1,
      useUnsignedBasicAuth: true,
      capacity: {
        masterNodeInstanceType: 't3.small.search',
        dataNodeInstanceType: 't3.small.search',
      },
      vpc: props.vpc,
      securityGroups: [props.securityGroup],
      vpcSubnets: [{ subnets: [props.vpc.publicSubnets[0]] }],
      ebs: {
        volumeSize: 10,
      },
      logging: {
        slowSearchLogEnabled: false,
        appLogEnabled: false,
        slowIndexLogEnabled: false,
      },
    })
  }


}
```

### What did you expect to happen?

I expect the deployment to succeed and basic auth to be enabled. In case something is wrong with my configuration, I would expect an error message indicating what the problem is. I definitely do not expect the cdk deploy to suddenly start missing its fundamental parameters which indicates an internal crash.

### What actually happened?

Deploying that fails with:
```sh
UPDATE_FAILED               <name-redacted>       AWS::CloudFormation::Stack Thu Feb 03 2022 09:40:33 GMT+0200 (Eastern European Standard Time) Parameters: [AssetParameters70893b631249dc61260989e92e90d60ae94fbbec490a1e065680d77383084d8dS3VersionKey46386A78, AssetParameters70893b631249dc61260989e92e90d60ae94fbbec490a1e065680d77383084d8dArtifactHash6BDDF757, AssetParameters70893b631249dc61260989e92e90d60ae94fbbec490a1e065680d77383084d8dS3BucketF0537962] must have values
```

### CDK CLI Version

1.142.0

### Node.js Version

14.18.1

### OS

Mac OS

### Language

Typescript

### Language Version

TypeScript (4.2.4)

### Other information

I have tried creating new OpenSearch instance from scratch simplifying it as much as possible, like 
```ts
const domain = new opensearch.Domain(this, props.domain, {
      version: opensearch.EngineVersion.OPENSEARCH_1_1,
      useUnsignedBasicAuth: true,
    })
``` 
but it still fails in the same way.

**Comment by kaizen3031593** [comment]
I was able to create a domain successfully using the simple implementation:

```ts
    const domain = new opensearch.Domain(this, 'opensearch', {
      version: opensearch.EngineVersion.OPENSEARCH_1_1,
      useUnsignedBasicAuth: true,
    });
```

I'm not convinced this error has to do with `useUnsignedBasicAuth`. I feel like this has to do with updating an existing domain versus creating a new one. can you try deleting your original domain and re-creating?

**Comment by stefan-enev** [comment]
It seems to me the problem is in Amplify Custom CDK module integration. Where would you recommend I should raise this issue?

**Comment by kaizen3031593** [comment]
Hi @stefan-enev, I don't actually know what the Amplify Custom CDK module integration is. Can you link me to what/where you are using that? 

I see that you are using amplify-cli, and you can submit an issue to them [here](https://github.com/aws-amplify/amplify-cli/issues/new/choose). It's a long shot, but maybe they have a better idea of what you're using.
