### ISSUE TITLE
(aws-lambda): CodeGuru profiling not enabling in Java

### ISSUE THREAD

**Issue by dcowan-e-courier** [aws/aws-cdk#18813]
### What is the problem?

The profiling groups get created, but the profiling flag on the lambda does not get enabled.  I see nothing in the cdk synth output to show that its added to the lambda or layer

### Reproduction Steps

```java
Tracing tracing = Tracing.ACTIVE;
boolean lambdaProfiling = true;
LambdaInsightsVersion lambdaInsightsVersion = LambdaInsightsVersion.VERSION_1_0_89_0;

Function functionWhoAmI = new Function(
		this,
		"WhoAmI",
		FunctionProps.builder().runtime(Runtime.JAVA_11).description("WhoAmIAsset").code(Code.fromAsset("../",
						AssetOptions.builder()
								.bundling(builderOptions.command(functionWhoAmIPackagingInstructions).build()).build()))
				.handler("com.test.WhoAmIHandler").memorySize(1024).timeout(Duration.seconds(10))
				.logRetention(RetentionDays.ONE_WEEK).tracing(tracing).profiling(lambdaProfiling)
				.insightsVersion(lambdaInsightsVersion).build());
```

### What did you expect to happen?

Profiler enabled in lambda

### What actually happened?

Profiler was not enabled in lambda

### CDK CLI Version

2.10.0

### Framework Version

2.10.0

### Node.js Version

6.14.15

### OS

CDK Pipeline Linux

### Language

Java

### Language Version

Java (11)

**Comment by kaizen3031593** [comment]
HI @dcowan-e-courier! Can you explain what you were expecting to see for 'profiler enabled in lambda'? 

After `cdk synth`, you wont be able to find profiling enabled in the template because that is a CDK abstraction, and the synth output is a CloudFormation template. If the profiling groups are getting created, I think that is what we expect here. 
What you should be able to see is the profiling group arn added as an environment variable to the lambda. That is how lambda knows you have attached a profiling group.

If that doesn't help see if you can attach the template you're getting and we can make sense of what is going on.

**Comment by dcowan-e-courier** [comment]
The profiling groups are created, but the flag is not enabled in the lambda settings and also the layer is not enabled on the lambda, which should look something like this.  

"arn:aws:lambda:us-east-1:157417159150:layer:AWSCodeGuruProfilerJavaAgentLayer:5"

I also believe the role policy is missing the code guru profiler managed policy

"arn:aws:iam::aws:policy/AmazonCodeGuruProfilerAgentAccess"

**Comment by kaizen3031593** [comment]
> the flag is not enabled in the lambda settings

Are you talking about what you see in the AWS console? I'm not sure what you mean by this. Can you share your template? 

Here's the code where the magic happens. 

https://github.com/aws/aws-cdk/blob/3a39f6bf34eb428c527db1c614ed682c582821fb/packages/%40aws-cdk/aws-lambda/lib/function.ts#L658-L667

Looks like we are adding publish access to the profiling group for the lambda role, and that access entails granting `'codeguru-profiler:ConfigureAgent', 'codeguru-profiler:PostAgentProfile'`, which is consistent with the [docs](https://docs.aws.amazon.com/codeguru/latest/profiler-ug/auth-and-access-control-iam-identity-based-access-control.html).

unrelated, are you not affected by https://github.com/aws/aws-cdk/issues/18789?

**Comment by peterwoodworth** [comment]
@dcowan-e-courier can you share your template please?

**Comment by deki** [comment]
Facing the same issue, it seems CDK is assuming the agent is enabled via code as described in: https://docs.aws.amazon.com/codeguru/latest/profiler-ug/enabling-the-agent-with-code.html

However I was assuming to have `JAVA_TOOL_OPTIONS` set to `-javaagent:/opt/codeguru-profiler-java-agent-standalone.jar` and the layer `arn:aws:lambda:us-west-2:157417159150:layer:AWSCodeGuruProfilerJavaAgentLayer:10` added.
