### ISSUE TITLE
(aws-lambda-nodejs): environment not being passed to `commandHooks`

### ISSUE THREAD

**Issue by multimeric** [aws/aws-cdk#18810]
### What is the problem?

If you have a command hook defined in the bundler for a `NodejsFunction`, it will not be run with the same environment that you provided as a `NodejsFunction` prop.

### Reproduction Steps

```ts
import * as cdk from 'aws-cdk-lib';
import { CdkStack } from '../lib/cdk-stack';
import { Stack, StackProps } from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as lambda from "aws-cdk-lib/aws-lambda-nodejs";
import * as cdk from "aws-cdk-lib"

export class CdkStack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);

    new lambda.NodejsFunction(this, 'discordInteractions', {
      bundling: {
        environment: {foo: "bar"}
        commandHooks: {
          afterBundling: (inputDir, outputDir) => ([
            `env`,
          ]),
          beforeBundling: (inputDir, outputDir) => ([]),
          beforeInstall: (inputDir, outputDir) => ([])
        },
      },
    });
  }
}

const app = new cdk.App();
new CdkStack(app, 'CdkStack', {});
```

### What did you expect to happen?

`FOO=BAR` to be printed.

### What actually happened?

Nothing was printed.

### CDK CLI Version

2.10.0 (build e5b301f)

### Framework Version

2.10.0 (build e5b301f)

### Node.js Version

v16.13.2

### OS

Ubuntu 21.04

### Language

Typescript

### Language Version

Version 4.5.2

**Comment by corymhall** [comment]
@multimeric can you provide more information on your build environment? Are you performing docker bundling or local bundling? I've tried to reproduce using both and I see the environment variable printed.
