### ISSUE TITLE
(aws-cdk-lib/aws_ecs): taskDefinition constructor prop for FargateService construct doesn't use interface

### ISSUE THREAD

**Issue by mdforbes500** [aws/aws-cdk#18815]
### What is the problem?

When trying to create a FargateService construct using the Typescript implementation of aws-cdk, the construct prop `taskDefinition` requires a type of `TaskDefinition` - which precludes the use of the `FargateTaskDefinition` and throws the error:
```sh
TypeError: Cannot read property 'containerName' of undefined
```

### Reproduction Steps

This doesn't work because of the type.
```ts
declare const vpc: ec2.Vpc;

const cluster = new ecs.Cluster(this, 'FargateCPCluster', {
  vpc,
  enableFargateCapacityProviders: true,
});

const taskDefinition = new ecs.FargateTaskDefinition(this, 'TaskDef');

taskDefinition.addContainer('web', {
  image: ecs.ContainerImage.fromRegistry('amazon/amazon-ecs-sample'),
});

new ecs.FargateService(this, 'FargateService', {
  cluster,
  taskDefinition,
});
```

### What did you expect to happen?

cdk would synth correctly

### What actually happened?

```sh
/cdk/node_modules/aws-cdk-lib/aws-ecs/lib/base/base-service.ts:636
      containerName: this.taskDefinition.defaultContainer!.containerName,
                                                           ^
TypeError: Cannot read property 'containerName' of undefined
```

### CDK CLI Version

2.9.0 (build a69725c)

### Node.js Version

v14.17.6

### OS

Ubuntu 20.04.3 LTS

### Language

Typescript

### Language Version

~3.9.7

### Other information

I think this can be solved by setting the FargateService's construct prop for `taskDefintion` to the type `ITaskDefinition` (or `IFargateTaskDefinition` to be type-restrictive) so that way anything that can implement those classes can be used

**Comment by ryparker** [comment]
Hey @mdforbes500 👋🏻 

I'm having trouble reproducing this. This may be a problem with your tsconfig. I'll share mine:

```json
{
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "outDir": "./build/js",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true
  }
}
```

See if you notice a difference. If not you may want to try deleting your node_modules folder and reinstalling deps.

**Comment by mdforbes500** [comment]
Sorry guys, the problem ended up being on my side - mea culpa
