### ISSUE TITLE
(@aws-cdk/aws-sns-subscriptions): Nested stack cannot depend on a parent stack error when trying to add SNS subscription

### ISSUE THREAD

**Issue by eoromb** [aws/aws-cdk#18829]
### What is the problem?

I got the error that nested stack cannot depend on a parent stack when trying to add SNS subscription to topic from parent stack in nested one.

### Reproduction Steps

Parent stack:
```
  const topic = new Topic(this, 'topic', ...);
  this.nestedStack = new SomeNestedStack(this,...);
```

Some Nested stack:
```
constructor(scope: ParentStack, ...) {
   ...;  
  const queue = new Queue(...);  
  scope.topic.addSubscription(new SqsSubscription(queue, ...  ));  
}
```

### What did you expect to happen?

Probably should not get this error.

### What actually happened?

Got the following error: 
Error: Nested stack 'nestedStack' cannot depend on a parent stack 'parentStack': undefined
    at Object.addDependency (/builds/xymatic/bouncr/infra/node_modules/@aws-cdk/core/lib/deps.ts:73:11)
    at stackName.addDependency (/builds/xymatic/bouncr/infra/node_modules/@aws-cdk/core/lib/stack.ts:271:5)
    at SqsSubscription.bind (/builds/xymatic/bouncr/infra/node_modules/@aws-cdk/aws-sns-subscriptions/lib/sqs.ts:55:24)

### CDK CLI Version

1.143.0

### Framework Version

1.143.0

### Node.js Version

14.18.1

### OS

Linux

### Language

Typescript

### Other information

It seems that related changes were made in `3cd8d481906fc4e3abdd1211908844e5b8bd2509` commit in `@aws-cdk/aws-sns-subscriptions/lib/lambda.ts` line 39.

**Comment by jeffreyyoung** [comment]
A hacky workaround for this issue, is to create a `new Topic.fromTopicArn`, and add the subscription to the newly created topic.

So change this:

```
scope.topic.addSubscription(new SqsSubscription(queue, ...  ));  
```
to something like this:
```
const topicFromArn = new Topic.fromTopicArn(scope, 'topic-from-arn', scope.topic.topicArn);
topicFromArn.addSubscription(new SqsSubscription(queue, ...  )); 
```

**Comment by eoromb** [comment]
@jeffreyyoung thanks for the proposed solution.

Just interesting if it is a bug or was intentionally done like this.

**Comment by jeffreyyoung** [comment]
Yeah, I'm not sure! Also not sure if the workaround I mentioned would cause other problems. 🤷‍♂️

**Comment by kaizen3031593** [comment]
I _feel_ like this is a true circular dependency. Nested stacks cannot depend on their parents, so we can't depend on the topic existing in the nested stack. However, I feel like something like this should work, though I'm not very familiar with nested stacks:

Parent stack:
```ts
const topic = new Topic(this, 'topic', ...);
const nestedStack = new SomeNestedStack(this,...);
topic.addSubscription(new SqsSubscription(nestedStack.queue, ...));
```

Nested stack:
```ts
readonly queue: Queue;
constructor(scope: ParentStack, ...) {
   ...;  
  this.queue = new Queue(...);  
}
```

But this runs into the same error as above. @corymhall is this a use case that was considered in https://github.com/aws/aws-cdk/pull/17273? I don't have a strong understanding of our nested stack model; perhaps what i'm describing isn't possible either.

**Comment by aramfe** [comment]
I have the same issue. Not sure how to finde an elegant solution for this
