### ISSUE TITLE
(cdk deploy): hangs when taking relative path to Dockerfile from root in yarn workspaces project

### ISSUE THREAD

**Issue by ilovett** [aws/aws-cdk#18844]
### What is the problem?

I have a project using `yarn workspaces`, and I am trying to build an image where the Dockerfile exists at `${rootDir}/apps/api` , I have cdk at `${rootDir}/cdk` — my stack lives at `${rootDir}/cdk/lib/my-stack.ts`

It tries to setup the image using root dir and relative path to the dockerfile:

```ts
    const repoRootDir = join(__dirname, '..', '..');
    const relativeDockerFilePath = join('apps', 'api', 'Dockerfile');
    const image = ContainerImage.fromAsset(repoRootDir, { file: relativeDockerFilePath });

    // this will log
    console.log({ image });

    // hangs here
    const backendService = new ApplicationLoadBalancedFargateService(this, 'backendService', {
      cluster: cluster,
      memoryLimitMiB: 1024,
      cpu: 512,
      desiredCount: 1,
      taskImageOptions: {
        image,
      }
   );
```

I have to do it this way because my `Dockerfile` wants the `yarn.lock` from the root dir so we can install deps with `--frozen-lockfile`

So normally I would run `docker build -t api -f apps/api/Dockerfile .` from the `${rootDir}`, and this will build properly.

Here's the `Dockerfile`

```dockerfile
# add root level deps
ADD ./package.json /app/package.json
ADD ./yarn.lock /app/yarn.lock

# add the api
ADD ./apps/api/package.json /app/apps/api/package.json
ADD ./apps/api/tsconfig.json /app/apps/api/tsconfig.json
ADD ./apps/api/src /app/apps/api/src

# build from root level yarn.lock
RUN yarn install --frozen-lockfile
RUN yarn build:api
```

I am also open to changes in how to build this image.  Also wondering if would just be easier to build and publish in a separate step and cdk only refers to the published image from repository?

### Reproduction Steps

project structure

```
cdk
apps
  api
    Dockerfile
yarn.lock
```

And in the stack scipt:

```ts
    const repoRootDir = join(__dirname, '..', '..');
    const relativeDockerFilePath = join('apps', 'api', 'Dockerfile');
    const image = ContainerImage.fromAsset(repoRootDir, { file: relativeDockerFilePath });

    console.log('made it past image', { image });

    const backendService = new ApplicationLoadBalancedFargateService(this, 'backendService', {
      cluster: cluster,
      memoryLimitMiB: 1024,
      cpu: 512,
      desiredCount: 1,
      taskImageOptions: {
        image,
      }
   });

   console.log('never gets here...');
```

### What did you expect to happen?

I expect it to behave like `cd rootDir; docker build -t my-image:latest -f apps/api/Dockerfile .`

### What actually happened?

It hangs at 

```
    const backendService = new ApplicationLoadBalancedFargateService(this, 'backendService', {
      cluster: cluster,
      memoryLimitMiB: 1024,
      cpu: 512,
      desiredCount: 1,
      taskImageOptions: {
        image,
      }
   });
```

### CDK CLI Version

2.10.0 (build e5b301f)

### Node.js Version

v16.13.0

### OS

mac osx

### Language

Typescript

### Language Version

4.5.5

**Comment by TikiTDO** [comment]
@ilovett I had a very similar use-case a while back, and I saw something similar to what you describe. Eventually I found that my `.dockerignore` file was not excluding the cdk build directory, so docker was trying to pull in a huge amount of temp files which caused all sorts of problems. Not sure if this you're experiencing the same problem, but it might be worth a look.

**Comment by ilovett** [comment]
Thanks @TikiTDO adding `.dockerignore` with `cdk` listed indeed fixed the hanging process!  Cheers

**Comment by kateile** [comment]
Hey @ilovett when using `ContainerImage.fromAsset` does cdk invoke docker build itself?
