### ISSUE TITLE
(all): @link appears raw in documentation

### ISSUE THREAD

**Issue by huonw** [aws/aws-cdk#18846]
### link to reference doc page

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_autoscaling.EbsDeviceOptions.html#iops

### Describe your issue?

The documentation uses `{@link ...}` to seemingly try to create a hyperlink to another entity within the docs. This is currently not working, with the `{@link ...}` text coming through raw, e.g. on the linked page:

![image](https://user-images.githubusercontent.com/1203825/152711972-30e8f839-ca1b-46dc-a2d3-1de373d10c65.png)

This appears to be universal.

(Fixes here should be aware of #18845)

**Comment by comcalvi** [comment]
pinging @rix0rrr because he recently led work on docs

**Comment by comcalvi** [comment]
pinging @rix0rrr because he recently led work on docs

**Comment by tim-finnigan** [comment]
This appears to only affect v1 docs: https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-autoscaling.EbsDeviceOptions.html#iops. For v2 I see: 

<img width="633" alt="image" src="https://user-images.githubusercontent.com/87778557/214946268-cb2b0a4d-04c1-4cc6-a340-0443dd42adcd.png">

**Comment by mrgrain** [comment]
@tim-finnigan Only v1 because @rix0rrr has cleaned up V2 recently.
https://github.com/aws/aws-cdk/pull/23572

Candidate for closing?
