### ISSUE TITLE
(custom-resource): unable to get output data from custom reso

### ISSUE THREAD

**Issue by nlang** [aws/aws-cdk#18856]
### What is the problem?

I have a custom resource defined that is backed by a lambda function:

```
const resource = new CustomResource(this, "some-id", {
    resourceType: "Custom::SomeName",
    serviceToken: provider.serviceToken,
    properties: {
        someProp: "someValue",
    },
});
```

The lambda gets called, does it's thing and returns

```
{
  Status: 'SUCCESS',
  ....
  Data: {
    CertificateArn: 'someArn'
  }
}
```

When I try to get 'CertificateArn'
```
resource.getAttString("CertificateArn")
```

I get the follwing error:
```
CustomResource attribute error: Vendor response doesn't contain CertificateArn key in object...
```

### Reproduction Steps

- Create a `CustomResource` backed by a Lambda provider that returns some values in the Data property of the response
- try to access the property by using getAtt/getAttString on the `CustomResource` instance

### What did you expect to happen?

I expected to get the value I returned in the custom resource lambda.

### What actually happened?

The error I described above occured

### CDK CLI Version

2.10.0

### Framework Version

2.10.0

### Node.js Version

14.16.1

### OS

MacOS 12.1

### Language

Typescript

**Comment by nlang** [comment]
While Googling for advice, I found another issue in the `aws-cdk-example` repository that seems to reference the same issue: https://github.com/aws-samples/aws-cdk-examples/issues/561

**Comment by rix0rrr** [comment]
Can you show the code that creates the `provider`?

**Comment by nlang** [comment]
@rix0rrr here is the code. The lambda is called and works flawless, the problem is that I'm unable to access the value(s) in the `Data` property of the result. Thanks!
```
const handler = new NodejsFunction(this, "cognito-custom-domain-certificate-resource-handler", {
            functionName: "cognito-cert-custom-resource-handler",
            runtime: lambda.Runtime.NODEJS_14_X,
            timeout: Duration.seconds(900),
            memorySize: 1024,
            logRetention: RetentionDays.FIVE_DAYS,
            bundling: {
                minify: false,
                sourceMap: true,
                sourceMapMode: SourceMapMode.INLINE,
                sourcesContent: false,
                target: "es2020",
                keepNames: true,
            },
            entry: "lib/cognito/custom-domain/certificate-custom-resource-handler.ts",
            handler: "handler",
        });

const provider = new Provider(this, "cognito-custom-domain-certificate-resource-provider", {
    onEventHandler: handler,
});
```

**Comment by stowns** [comment]
Are you positive you're returning the data from the handler? I've made this mistake in the past of having the a `switch` statement in the handler which routes to `onCreate()` `onUpdate()` etc. The methods return the correct payload but the switch statement in `handler()` wasn't returning.

ie)
```
export async function handler(event: any, context: any) {
  console.log(JSON.stringify(event));
  let ret;
  switch (event.RequestType as string) {
    case 'Create':
      ret = await onCreate(event, context);
      break;
    case 'Update':
      ret = await onUpdate(event, context);
      break;
    case 'Delete':
      ret = await onDelete(event);
      break;
    default:
      throw new Error('Unsupported RequestType');
  }

  return ret; // MAKE SURE TO DO THIS
}
```

**Comment by nlang** [comment]
@stowns thanks for your suggestion, that's a good point actually. I'm sending what I expect to get returned as body in the PUT request to S3 and expected that to be the returned data. I will try that out and give feedback.

**Comment by nlang** [comment]
Thanks @stowns to point me in the right direction. I figured that I didn't even to upload the response to S3 myself (what I did) but just return it. That's why the Custom Resource itself generally worked, but without having the return values available in the stack. Closing this issue.
