### ISSUE TITLE
(aws-ecs-patterns): Enable autoscaling with ApplicationLoadBalancedEc2Service

### ISSUE THREAD

**Issue by 5nafu** [aws/aws-cdk#18868]
### General Issue

I would like to use an `ApplicationLoadBalancedEc2Service` together with autoscaling of EC2 instances.

### The Question

I would like to use an `ApplicationLoadBalancedEc2Service` together with an EC2 ASG. To enable autoscaling of the ECS instances, I would need to apply the `capacity_provider_strategies` parameter.
The L2 `@aws-cdk/aws-ecs.Ec2Service` already supports this option, but the L3 construct does not.

Unfortunately the `EC2Service` does not allow to add this strategy later to the finished service either.

### CDK CLI Version

2.10.0

### Node.js Version

16.3.0

### OS

OSX

### Language

Typescript

**Comment by peterwoodworth** [comment]
Hey @5nafu,

While you can't directly set this property on the L3 construct, you can use escape hatches to apply this property to the underlying service.

```ts
    const l3 = new ApplicationLoadBalancedFargateService(this, 'ALBFargateService', {
      memoryLimitMiB: 1024,
      taskImageOptions: {
        image: ContainerImage.fromRegistry('test'),
        environment: {
          TEST_ENVIRONMENT_VARIABLE1: "test environment variable 1 value",
          TEST_ENVIRONMENT_VARIABLE2: "test environment variable 2 value",
        },
      },
      desiredCount: 2,
    });

    const l2 = l3.node.findChild('Service') as Ec2Service;

    const l1 = l2.node.defaultChild as CfnService;

    const cpsprops = {
      base: 2,
      weight: 2,
      capacityProvider: 'capacityProvider'
    }

    l1.addPropertyOverride('CapacityProviderStrategy', cpsprops);
```

**Comment by 5nafu** [comment]
Hi @peterwoodworth ,

thanks for the quick response. Unfortunately the above code results in a `Specifying both a launch type and capacity provider strategy is not supported.` (Adding the required `[]`around `cpsprops` on the last line).

I needed to add `l1.addPropertyDeletionOverride('LaunchType')` to make it work.

So the complete code would be (adding as reference for future google searches):
```ts
    const l3 = new ApplicationLoadBalancedEc2Service(this, 'ALBFargateService', {
      memoryLimitMiB: 1024,
      taskImageOptions: {
        image: ContainerImage.fromRegistry('test'),
        environment: {
          TEST_ENVIRONMENT_VARIABLE1: "test environment variable 1 value",
          TEST_ENVIRONMENT_VARIABLE2: "test environment variable 2 value",
        },
      },
      desiredCount: 2,
    });

    const l1 = l3.service.node.defaultChild as CfnService;

    const cpsprops = [{
      base: 2,
      weight: 2,
      capacityProvider: 'capacityProvider'
    }];

    l1.addPropertyOveride('CapacityProviderStrategy', cpsprops);
    l1.addPropertyDeletionOverride('LaunchType');

```

That said, I would like to request the addition of the `capacity_provider_strategies` parameter to the EC2-LB pattern `ApplicationLoadBalancedEc2Service` as using autoscaling groups with an EC2 based ECS cluster seems to be the standard use case, and instances-autoscaling does not work without this setting (at least in our tests).

Cheers and thanks again for the hint with the escape hatches.

**Comment by peterwoodworth** [comment]
Thanks for cleaning the code up, I only synthesized my code 🙂 

I'll convert this to a feature request. Since this has a relatively easy workaround we don't have a timeline for it, but we happily accept community contributions. Check out [our contributing guide](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) if you're interested

**Comment by gshpychka** [comment]
If I may, I would suggest that if you're running into issues like this, it's time to switch from L3 to L2 constructs. L3 are very opinionated and limit the available options by design, to make it easy for newcomers to spin up complex solutions. Once you're comfortable with it and are in need of deeper configuration, I'd go with L2 to have full control.

**Comment by peterwoodworth** [comment]
@gshpychka thank you for the input, I tend to agree here, and directly implementing the prop just for the L2 construct wouldn't help with the abstraction the L3 is trying to offer. However, I believe there's a case for somehow abstracting the ability to autoscale the instances created 🙂
