### ISSUE TITLE
(assertions): Annotations should support `hasNoXxx()` APIs

### ISSUE THREAD

**Issue by fitzoh** [aws/aws-cdk#18874]
### Description

Add `has_no_error`, `has_no_warning`, and `has_no_info` methods to the Annotations assertions toolkit.

### Use Case

I'm testing some EC2 constructs and lettings users pass in block volumes, adding errors if any volumes are unencrypted.

The test for something that produces an error is easy:
```python    
Annotations.from_stack(stack).has_error("*", "unencrypted volume /dev/sda1")
```

The test for a value that doesn't produce an error is awkward:
```python
    errors = Annotations.from_stack(stack).find_error(
        "*", Match.string_like_regexp(".*")
    )
    assert not errors
```    

I would like to easily assert that there are no errors in the stack

### Proposed Solution

Add a `has_no_error` method next to the `has_error` and `find_error` methods (as well as `info` and `warning` variants).

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by kaizen3031593** [comment]
This would be helpful. I agree the workaround is a bit awkward.
