### ISSUE TITLE
(aws-config): Add support for s3-bucket-level-public-access-prohibited managed rule in ManagedRuleIdentifiers class

### ISSUE THREAD

**Issue by sringel** [aws/aws-cdk#18888]
### Description

Currently [ManagedRuleIdentifiers](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-config.ManagedRuleIdentifiers.html) doesn't support identifier for s3-bucket-level-public-access-prohibited managed rule (S3_BUCKET_LEVEL_PUBLIC_ACCESS_PROHIBITED). The documentation for this rule is [here](https://docs.aws.amazon.com/config/latest/developerguide/s3-bucket-level-public-access-prohibited.html)

### Use Case

I should be able to create the s3-bucket-level-public-access-prohibited managed rule through CDK higher level construct.

### Proposed Solution

Add constant to packages/@aws-cdk/aws-config/lib/rule.ts

```
  /**
   * Checks if Amazon Simple Storage Service (Amazon S3) buckets are publicly accessible. This rule is
   * NON_COMPLIANT if an Amazon S3 bucket is not listed in the excludedPublicBuckets parameter
   *  and bucket level settings are public.
   * @see https://docs.aws.amazon.com/config/latest/developerguide/s3-bucket-level-public-access-prohibited.html
   */
  public static readonly S3_BUCKET_LEVEL_PUBLIC_ACCESS_PROHIBITED = 'S3_BUCKET_LEVEL_PUBLIC_ACCESS_PROHIBITED';
```

**Comment by ArchitGajjar** [comment]
Hi @sringel  - is this issue still open ? can I work on this issue ? this will be my first contribution to AWS :)

**Comment by sringel** [comment]
This issue has been resolved by https://github.com/aws/aws-cdk/pull/18890
