### ISSUE TITLE
(vpc): vpc.fromLookup throwing error for subnets without subnetGroupNameTag 

### ISSUE THREAD

**Issue by tessmanjonathan** [aws/aws-cdk#18883]
### General Issue

Should we be requiring all subnets in a vpc to have the tag specified in subnetGroupNameTag?

### The Question

It seems like in a recent change that was deployed in version 1.143.0, PR #18714 is requiring all subnets in a vpc to have all the same tags if you are using subnetGroupNameTag.

Example -
subnet-1: tags = _No tags_
subnet-2: tags = infra-group-tag

If we use:
`ec2.Vpc.fromLookup(this, 'DefaultVPC', { subnetGroupNameTag: 'infra-group-tag' });` 

we are receiving the error:
Invalid subnetGroupNameTag: Subnet arn:aws:ec2:us-east-1:#####:subnet/subnet-1 does not have an associated tag with Key='infra-group-tag'

Should this be requiring subnet-1 to now have a tag called infra-group-tag?

Changing back and pinning aws-cdk to 1.142.0 allows us to deploy successfully.

### CDK CLI Version

1.143.0

### Language

Python

**Comment by peterwoodworth** [comment]
Yes, if you're using `subnetGroupNameTag` to help look up your vpc, then that tag should be present on all subnets 🙂 Seems this wasn't working properly before the PR you linked was merged

**Comment by 3oris** [comment]
Can this please be fixed?
