### ISSUE TITLE
(@aws-cdk/aws-sqs): existing queues are purged on deploy

### ISSUE THREAD

**Issue by shellscape** [aws/aws-cdk#18901]
### What is the problem?

I have several queues previously deployed with CDK in the same stack. There have been no modifications to the stack, only code updates in accompanying lambdas. On deployment of the stack, the queues are purged. 

### Reproduction Steps

I've verified this a number of times by adding several million messages to the queues programmatically, and then running deployments soon after. Note that there is no physical way the event source lambda for these queues could process all of the messages in the queue in any short amount of time, as batch size is set to 1 and delivery delay is 5 minutes. 

### What did you expect to happen?

I expected the previously deployed queue to retain the messages that were sent to it. 

### What actually happened?

The queue appears to have been purged

### CDK CLI Version

2.10.0 (build e5b301f)

### Framework Version

1.143.0

### Node.js Version

14.15.3

### OS

MacOS Big Sur

### Language

Typescript

**Comment by rix0rrr** [comment]
This is for Lambda event triggers, probably. Maybe the queues are getting recreated because their logical ID changes.

**Comment by moofish32** [comment]
I can't reproduce this. Here is what I tried:

```ts
import { App, Duration, Stack, StackProps } from 'aws-cdk-lib';
import { Code, Function, Runtime } from 'aws-cdk-lib/aws-lambda';
import { Queue } from 'aws-cdk-lib/aws-sqs';
import { SqsEventSource } from 'aws-cdk-lib/aws-lambda-event-sources';
import { Construct } from 'constructs';

export class MyStack extends Stack {
  constructor(scope: Construct, id: string, props: StackProps = {}) {
    super(scope, id, props);
    const fn = new Function(this, 'MyFunction', {
      handler: 'index.handler',
      code: Code.fromInline(`
    exports.handler = async (event) => {
      console.log('event: ', event)
    };
  `),
      runtime: Runtime.NODEJS_14_X,
    });
    const queue = new Queue(this, 'MyQueue', {
      visibilityTimeout: Duration.seconds(20),
    });
    const eventSource = new SqsEventSource(queue, {
      batchSize: 1,
    })
    fn.addEventSource(eventSource);
  }
}

// for development, use account/region from cdk cli
const devEnv = {
  account: process.env.CDK_DEFAULT_ACCOUNT,
  region: process.env.CDK_DEFAULT_REGION,
};

const app = new App();

new MyStack(app, 'my-stack-dev', { env: devEnv });
// new MyStack(app, 'my-stack-prod', { env: prodEnv });

app.synth();

```

I then went into the lambda and throttled it so the lambda would not take any messages from the queue. I sent in messages using the CLI

```bash
 aws sqs send-message --queue-url https://<omit>/my-stack-dev-MyQueueE6CA6235-mfszcGlG27g9 --message-body "Information about the largest city in Any Region."
```

After verifying 5 messages in the queue I redeployed the stack.  All 5 messages remained in the queue.

After that I modified the function code above to print 2 times and deployed. The messages still remained in the queue.

After removing the throttle the queue was cleared by the function. @shellscape is my test valid? Do you have any reproduction code?

**Comment by shellscape** [comment]
This was likely due to a property change that forced queue recreation. We haven't been able to reproduce it outside of a single stack. Solution was to nuke the stack, issue vanished
