### ISSUE TITLE
(@aws-cdk/aws-appsync): support for GraphQL documentation

### ISSUE THREAD

**Issue by fab-mindflow** [aws/aws-cdk#18907]
### Description

It looks like there is no support in code first approach to add documentation (block strings) to generated GraphQL schemas.

### Use Case

Generated GraphQL would contain documentation on fields and types.
Tools can then use introspection queries to display documentation from GraphQL schemas generated by @aws-cdk/aws-appsync (we have the use case for our platform).

### Proposed Solution

Add an attribute to `FieldOptions`, `IntermediateTypeOptions` and more to allow documenting types and fields.
```
const demo = new appsync.ObjectType('Demo', {
  description: "THIS IS SOME DOCUMENTATION",
  interfaceTypes: [ node ],
  definition: {
    version: appsync.GraphqlType.string({ isRequired: true }),
  },
});
```

That would result in GraphQL schema:
```
"""THIS IS SOME DOCUMENTATION"""
type demo {
  id: String!
  version: String!
}
```

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by otaviomacedo** [comment]
It seems that AppSync doesn't support this feature yet: https://github.com/aws/aws-appsync-community/issues/38.
