### ISSUE TITLE
Support Environment property in SageMakerCreateTrainingJob

### ISSUE THREAD

**Issue by tlinford39** [aws/aws-cdk#18919]
### Description

Add support for the Environment property in the [aws_stepfunctions_tasks.SageMakerCreateTrainingJob](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_stepfunctions_tasks.SageMakerCreateTrainingJob.html) class.

### Use Case

The Environment property is supported in the [CreateTrainingJob API reference](https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_CreateTrainingJob.html).

### Proposed Solution

I cannot implement this myself, but the property is supported by the [aws_stepfunctions_tasks.SageMakerCreateTransformJob](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_stepfunctions_tasks.SageMakerCreateTransformJob.html) class. For someone with a better understanding, it may just be a case of copying the implementation from this class.

### Other information

-

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by kaizen3031593** [comment]
Fixed by #18919.
