### ISSUE TITLE
(ec2): Passing PhysicalName.GENERATE_IF_NEEDED to a VPC results in an error

### ISSUE THREAD

**Issue by gshpychka** [aws/aws-cdk#18912]
### What is the problem?

If `PhysicalName.GENERATE_IF_NEEDED` is passed to the Vpc constructor in `vpc_name`, it fails to synth.

### Reproduction Steps

```
import aws_cdk as cdk
from aws_cdk import aws_ec2 as ec2

class MyVPC(cdk.Stack):
    def __init__(self, scope, id, **kwargs):
        super().__init__(scope, id, **kwargs)
        ec2.Vpc(self, "vpc", vpc_name=cdk.PhysicalName.GENERATE_IF_NEEDED)

app = cdk.App()

MyVPC(app, "MyVPC")

app.synth()
```

### What did you expect to happen?

Successful synth.

### What actually happened?

`jsii.errors.JSIIError: Resolution error: Resolution error: Resolution error: Invalid physical name passed to CloudFormation. Use "this.physicalName" instead...`

### CDK CLI Version

2.12.0

### Framework Version

2.10.0

### Node.js Version

17.3.0

### OS

ArchLinux

### Language

Python

### Language Version

Python 3.9.10

**Comment by skinny85** [comment]
Hey @gshpychka,

thanks for opening the issue. Unfortunately, VPCs do not have physical names in the sense that CDK understands that term. Yes, there's `vpcName`, but that's not actually a physical name; it's just a label that's shown in the console.

To reference the VPC, and to construct its ARN, which CDK needs to be able to do for cross-environment access, you need to specify the VPC ID, and that is automatically-generated when the VPC is created - there's no way to control what it is before creating the VPC. For that reason, VPCs don't really have physical names as far as the CDK is concerned.

This is not unique to VPCs - a few other AWS resources also don't allow setting its physical name (KMS Keys are the most commonly encountered other example).

Hope this clears this up!

Thanks,
Adam

**Comment by gshpychka** [comment]
Thanks for clarifying. Do you think it'd be a good idea to clarify the VPC docs regarding this? The `vpcName` parameter does suggest that it's a physical name.
