### ISSUE TITLE
(software.amazon.awscdk.services.codebuild): CodeBuild ARM (aarch64) images/architecture is not fully supported by CDK

### ISSUE THREAD

**Issue by codemeddler** [aws/aws-cdk#18916]
### What is the problem?

CodeBuild module does not support using arch 64 images due to missing ComputeType enum options. You can observe the aarch64 compute options are different than the default linux options in the console, but there doesn't seem to be a way to set to one in CDK.

### Reproduction Steps

Create a CodeBuild project in a stack like this:

```java
Repository repo = Repository.Builder.create(this, "Repository")
          .description("description")
          .repositoryName("repositoryName")
          .build();
CodeCommitSourceProps props = CodeCommitSourceProps.builder()
          .branchOrRef("dev")
          .repository(repo)
          .build();
ISource source = Source.codeCommit(props);
BuildEnvironment env = BuildEnvironment.builder()
          .buildImage(LinuxBuildImage.fromCodeBuildImageId("aws/codebuild/amazonlinux2-aarch64-standard:2.0"))
          .computeType(ComputeType.MEDIUM) // NOTE: No ComputeType will deploy successfully
          .build();
Project buildProject = Project.Builder.create(this, "BuildProject")
          .description("description")
          .environment(env)
          .projectName("projectName")
          .source(source)
          .build();
```

### What did you expect to happen?

Stack deploys successfully.

### What actually happened?

AWS CodeBuild curated image aws/codebuild/amazonlinux2-aarch64-standard:2.0 is not supported for projects with environment type LINUX_CONTAINER and compute type BUILD_GENERAL1_SMALL (Service: AWSCodeBuild; Status Code: 400; Error Code: InvalidInputException; Request ID: fce423e8-0d42-472e-9733-816b8055778c; Proxy: null)

### CDK CLI Version

2.12.0 (build c9786db)

### Node.js Version

v16.10.0

### OS

MacOS 12.2

### Language

Java

### Language Version

Java (8)

### Other information

Even when omitting the compute type, the default value prevents deployment.

**Comment by codemeddler** [comment]
My guess is this is the part of code that needs updating:
https://github.com/aws/aws-cdk/blob/6855dfefb15e72623e4ec5bfae169d8d8c15982a/packages/%40aws-cdk/aws-codebuild/lib/project.ts#L1505

Not sure what the available options are or where to find them, but should be a quick and easy fix.

**Comment by codemeddler** [comment]
Okay, had some time to poke around the code a bit more. Found a working combination:
```
 BuildEnvironment env = BuildEnvironment.builder()
          .buildImage(LinuxBuildImage.AMAZON_LINUX_2_ARM_2)
          .build();
```
It seems using the constant, the image gets the class ArmBuildImage and the deployment is successful. The ArmBuildImage class is not exported and using the fromCodeBuildImageId with the arm images fails, so it's a bit of a gotcha.

**Comment by skinny85** [comment]
Hey @codemeddler,

thanks for opening the issue. First of all, did you unblock yourself? Or is there something else you need our help with?

Also, can you show me a screenshot of the options you see for the ARM image in the CodeBuild AWS Console?

Thanks,
Adam

**Comment by codemeddler** [comment]
Hi @skinny85,
I was able to unblock myself so far, but as the build image constants are not mentioned anywhere in the docs, I imagine someone else might run into this issue as well. I can see few ways to fix or improve the situation, but not sure what or which would be the best option:

1) The LinuxBuildImage.fromCodeBuildImageId("aws/codebuild/amazonlinux2-aarch64-standard:2.0") should be modified to map to the ArmBuildImage the same way the constant maps.
2) Remove the fromCodeBuildImageId function and use the constants as the way to use the official CodeBuild images.
3) Export the ArmBuildImage and leave sorting out images and classes to the user, adding the ARM ComputeTypes as options.
4) Update the documentation examples to show the use of the constants for ARM.
5) Add an architecture property that can be set. This would also allow a compile time check if the chosen image and architecture match instead of erroring in deploy.

You can find the "constants" I am talking about in the same file, around line 1700. As you can see, using a constant such as LinuxBuildImage.AMAZON_LINUX_2_ARM_2, an ArmBuildImage is created in the background, which seems to resolve the incompatibility problem.
https://github.com/aws/aws-cdk/blob/6855dfefb15e72623e4ec5bfae169d8d8c15982a/packages/%40aws-cdk/aws-codebuild/lib/project.ts#L1713

I also attached a screenshot below of the ARM computing options from the console. It seems the ArmBuildImage class works with some compute constants (and defaults to a large instance), but I haven't had time to investigate the code how that mapping works. My hunch is that the ArmBuildImage vs LinuxBuildImage is the deciding factor whether the ComputeType constants work with a certain image or not.

<img width="241" alt="Screen Shot 2022-02-11 at 11 26 51 AM" src="https://user-images.githubusercontent.com/91956246/153569106-71557844-d0cc-4dd9-a11b-145cf6fd2d1a.png">

### Final note
I imagine I might run into related issues once I reach the next stage, which is using a custom ARM image. I imagine I will be unable to set the build machine type to ARM since I would be using the LinuxBuildImage.fromECRImage instead of a constant. This would imply option 3 or 5 would at a minimum be the way to go.

But this is just an educated guess as of now.

**Comment by codemeddler** [comment]
@skinny85 I agree, secret option number 6 sounds like a good path forward. Will the AWS team tackle this or should I look into the contribution guide and see to it myself?

**Comment by skinny85** [comment]
@codemeddler if you could contribute a PR for this, that would be fantastic 🙂. The contribution guide is here: https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md.

Thanks,
Adam

**Comment by skinny85** [comment]
I actually link calling the class `LinuxArmBuildImage` is a good idea, instead of just `ArmBuildImage` (there might be Windows ARM images in the future, who knows? 🙂).

I would probably not do _everything_ in `LinuxArmBuildImage`. Let's start with the two constants, and `fromEcrRepository()`. We can add stuff later to it as needed.

**Comment by codemeddler** [comment]
Presumptuously already added it to the description of this PR 🙂. Not sure if it needs to be added elsewhere too to be picked up correctly? Both issues seem to link on the side panel at least.
