### ISSUE TITLE
(pipelines): `versionReporting` and `--no-version-reporting` not respected for support stacks

### ISSUE THREAD

**Issue by gshpychka** [aws/aws-cdk#18933]
### What is the problem?

The pipeline is adding `AWS::CDK::Metadata` resource to the support stacks regardless of the `versionReporting` value and even if the synth command is `cdk --no-version-reporting synth`.

### Reproduction Steps

1. Have `"versionReporting": false` in `cdk.json`
2. Alternatively, specify the synth command as `cdk --no-version-reporting synth` in the Synth step
3. Deploy the pipeline. Verify that the support stacks do not have the `AWS::CDK::Metadata` resource. 
4. Wait for the pipeline to self-mutate the first time

### What did you expect to happen?

No changes to the support stacks.

### What actually happened?

The self-mutate action adds the `AWS::CDK::Metadata` to the support stacks.

If I do a `cdk deploy` from my local machine again, the resource will be deleted.

### CDK CLI Version

2.12.0

### Framework Version

2.12.0

### Node.js Version

17.3.0

### OS

ArcLinux

### Language

Python

### Language Version

3.9.10

**Comment by gshpychka** [comment]
@NGL321 Why is nobody assigned this? Shouldn't the inability to disable telemetry be P1?

**Comment by NGL321** [comment]
@gshpychka thank you for bringing this to our attention! 
That was a good observation, I definitely under-prioritized this.
