### ISSUE TITLE
(cli): use the cli to execute an app's state machine by its path

### ISSUE THREAD

**Issue by misterjoshua** [aws/aws-cdk#18949]
### Description

I'd like to execute Step Functions state machines in my app with the CDK CLI.

### Use Case

When working on CDK apps, I often need to perform repetitive tasks to poke and prod the parts of my app. These tasks may include inserting an item into a queue, executing a lambda function with a given payload, putting an event into an event bus, starting a Fargate task from a task definition, or executing a state machine.

I can complete these repetitive tasks using the AWS Console, the AWS CLI, or the AWS SDK. But all cases require manual steps or code that discovers the names of resources in the stack to interact with them. However, these use cases can also be generalized into ASL definitions and run through AWS Step Functions State Machines.

For these tasks, I prefer to use Step Functions because I can define them inside small apps living next to whatever construct I'm working on at the time, they don't take much manual work to run, and they're comparatively low code compared to writing custom scripts to do the same. But, they could be more convenient to run if the CDK provided a command that, given a Construct path, could locate the appropriate physical resource for the State Machine and execute it.

### Proposed Solution

For the app below, the user could type `cdk exec my-thing/TaskRunner` to execute the step function, which in turn executes a Fargate Task, exiting when the state machine execution finishes:

```ts
import { App, Stack } from 'aws-cdk-lib';
import { Cluster, ContainerImage, FargateTaskDefinition } from 'aws-cdk-lib/aws-ecs';
import { IntegrationPattern, StateMachine } from 'aws-cdk-lib/aws-stepfunctions';
import { EcsFargateLaunchTarget, EcsRunTask } from 'aws-cdk-lib/aws-stepfunctions-tasks';

const app = new App();
const stack = new Stack(app, 'my-thing');

const taskDefinition = new FargateTaskDefinition(stack, 'TaskDefinition', {
  cpu: 256,
  memoryLimitMiB: 512,
});

taskDefinition.addContainer('true', {
  image: ContainerImage.fromRegistry('bash'),
  command: ['true'],
});

const cluster = new Cluster(stack, 'Cluster');

// Execute this state machine by running `cdk exec my-thing/TaskRunner`
new StateMachine(stack, 'TaskRunner', {
  definition: new EcsRunTask(stack, 'EcsRunTask', {
    cluster,
    taskDefinition,
    launchTarget: new EcsFargateLaunchTarget(),
    integrationPattern: IntegrationPattern.RUN_JOB,
  }),
});

app.synth();
```

If the Step Function requires input, we could allow a command line argument `cdk exec <path> --input "JSON HERE"`

### Acknowledge

- [x] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by atkinsonm** [comment]
My initial impression is "this is a real pain point for sure and we want to make it easy to do quick, iterative development cycles, but the CDK CLI might not be the right place for this". The scope of the CDK is to define the resource graph (to borrow from Ben Kehoe's [recent article](https://www.lastweekinaws.com/blog/the-cdks-most-fundamental-flaw-is-fixable/). Asking CDK to support invoking functions seems outside of that scope and that it might "open the floodgates" for other types of actions that are more about application events than resource configurations.

Mark McCulloh:
> ^ I felt the same way at first, but then I thought: where else would this go? Other than a standalone tool I suppose, but fragmentation like that has downsides as well

The AWS CLI can be used to invoke functions. Perhaps there could be a better way for the AWS CLI to discover resources defined in a CDK.
This `cdk exec` command also assumes that the role used with CDK has those permissions, which ideally is not the case. In restrictive environments for example, build/CI system workers may only have permissions to call the CloudFormation API. For CI system purposes, I wouldn't even want the CDK CLI to have this capability; I'd rather it be a separate module so I can choose whether to install it.

**Comment by MarkMcCulloh** [comment]
> The scope of the CDK is to define the resource graph

The CDK toolkit already does more than that, so I think the floodgates are already open.

> may only have permissions to call the CloudFormation API

This is like saying we shouldn't have hotswapping in the CDK cli because in certain circumstances you shouldn't have the permission to use it.

I don't fully disagree that this exec feature may be outside of the scope of the CDK cli, but the reasoning for that seems much more ideological than practical.

**Comment by mrpackethead** [comment]
I can see the use-case and how it could be useful, but to me, it fits in a category of 'other really useful things that I use'..  Once installed it woud'tn make much difference if its part of cdk or something external?

**Comment by atkinsonm** [comment]
> This is like saying we shouldn't have hotswapping in the CDK cli because in certain circumstances you shouldn't have the permission to use it.

I also think the hotswapping feature is solving the right problem in the wrong way. I'd have rather seen some improvement so that `cdk deploy` is not so time-consuming. I think CDK hotswapping can and will be misused and will eventually cause someone's production system to topple over despite the "never use this in production" warnings.

My opinions may be unpopular but at least I'm consistent 😄

**Comment by atkinsonm** [comment]
> Once installed it woud'tn make much difference if its part of cdk or something external?

As a developer I want to choose what I install and install only the minimum dependencies to accomplish my specific task. THere's no harder lesson learned here than the Log4j CVE. It was a vulnerable piece of software that was bolted on to a logging package as a convenience feature that was non-essential for the majority of users.

**Comment by misterjoshua** [comment]
> My initial impression is "this is a real pain point for sure and we want to make it easy to do quick, iterative development cycles, but the CDK CLI might not be the right place for this".

Agreed that it's a pain point, and yes this feature does indeed help quicken iterative development cycles.

> The scope of the CDK is to define the resource graph (to borrow from Ben Kehoe's [recent article](https://www.lastweekinaws.com/blog/the-cdks-most-fundamental-flaw-is-fixable/)).

I could agree here with respect to everything you find starting from the CDK app, but the CDK CLI has always done far more than simply define the graph. Whether Kehoe agrees or not, it seems clear that developer-friendly, SDK-enabled features have been added in many recent CDK CLI releases, supporting the legitimacy of the case for adding another similarly-abled CLI DX enhancement.

> Asking CDK to support invoking functions seems outside of that scope and that it might "open the floodgates" for other types of actions that are more about application events than resource configurations.

Same as above. It seems this ship has already sailed.

> The AWS CLI can be used to invoke functions. Perhaps there could be a better way for the AWS CLI to discover resources defined in a CDK.

Yes, perhaps. If the AWS CLI could support this in reasonable time, it would satisfy the ask.

But it seems there are practical problems in integrating the AWS CLI with the assembly. Correct me if I'm wrong, but:

- It's written in a different language and unless the AWS CLI is willing to embed/require node to access the cxapi package, they'll have to find another way to integrate with CDK apps. 

- The assembly schema bumps a major version (e.g., v15.0.0 -> v16.0.0) every time the CDK team regenerates it, which seems a semi regular occurrence. It makes supporting the assembly a moving target.

What are your suggestions here?

> This `cdk exec` command also assumes that the role used with CDK has those permissions, which ideally is not the case. In restrictive environments for example, build/CI system workers may only have permissions to call the CloudFormation API.

True, but this feature doesn't target that use case. Even if one tries to use this feature in such an environment, they'll get the same error as any other script that might try to access the API. I agree with Mark's hotswap comments. Further,  following this reasoning, we also wouldn't have gotten watch mode or Lambda log stream tailing, both of which were welcome DX enhancements, the same as this exec feature.

> For CI system purposes, I wouldn't even want the CDK CLI to have this capability; I'd rather it be a separate module so I can choose whether to install it.

I get your point, especially in light of log4j, but the benefits of this feature are clear, the associated PR doesn't introduce any external dependencies, and the CDK CLI doesn't typically tag along with a CDK app - it lives primarily in restrictive build environments and developer workstations, the latter being the beneficiaries of the feature.


In the end, all I want is the feature. It doesn't matter to me how I get it, but it seems most practical to add a CDK-related feature closest to the CDK, even if there's some ideological potential for overlap with other AWS tools.

I hope this all makes sense.

**Comment by atkinsonm** [comment]
Agree with all of your comments. In absence of a demonstrably better place for this, this is the place. It's ultimately up to the CDK CLI team as to whether they want to accept and maintain this feature.

**Comment by rix0rrr** [comment]
Man, this is a tough one. On the one hand, I 100% see how a feature like this would be *extremely* useful. On the other hand, we already cannot really keep up with the influx of work into CDK as it is, and I'm very hesitant to add more surface area to the CDK to support features like these. 

I love the idea, but I'd like to see it have some bake time as a community tool first. We may still choose to adopt the functionality upstream once baked and proven and most of the important bugs and usability issues have been shaken out. At it stands, I'm not prepared to commit current and near future brain space to the stream of addition and change requests that are undoubtedly about to come out of a feature like this.

> The assembly schema bumps a major version (e.g., v15.0.0 -> v16.0.0) every time the CDK team regenerates it, which seems a semi regular occurrence. It makes supporting the assembly a moving target.

For the record: yes this happens, but this doesn't mean you cannot write a tool to do a very targeted thing yourself here. The tool you need to be writing could, at least in its infancy, perfectly well consume the cloud assembly and work separately from the CDK CLI.

The meaning of a Cloud Assembly bump is: the framework is advertising a new feature that it needs the CLI to support. In order for the framework to be able to deliver on this feature, it needs to know that the CLI recognizes the new fields and so will support the feature, and therefore we have a fairly strict versioning requirement here.

However, in the case of the tool you are proposing, the framework does not advertise a feature that it needs the CLI to provide. Instead, the tool advertises a feature that it needs the framework to provide some information for.

So your tool should in fact assert that the Cloud Assembly schema has a *minimum* version (to make sure it has the information your tool needs). Future updates will not invalidate this, we won't remove information from the CX schema.

**Comment by rix0rrr** [comment]
How about SAM CLI? Won't it do something like this?

**Comment by rix0rrr** [comment]
I wonder if there is a case to be made for a git-like subcommand system (`cdk-exec`)

**Comment by skinny85** [comment]
I like the idea. In fact, we actually discussed something like this internally a while back, except not for StepFunctions State Machines, but for Lambda Functions - something like `cdk invoke MyStack` (usability feature - if there's only one Function in a Stack, always call that!).

But, like Rico said, it's not something that we're exploring right this second.

I think Rico's "Git executables" idea is pretty great - it would allow delivering this as a library used alongside the main `aws-cdk` package.
