### ISSUE TITLE
(custom-resources): action name validation failed due to unexpended symbols in generated string

### ISSUE THREAD

**Issue by bhavishya-singh** [aws/aws-cdk#18941]
### What is the problem?

I am facing a bug/issue in using aws-cdk for creating Amazon Lex Bot V2 through CDK AwsCustomResource.
While building the AwsSdkCall for the same. I m getting an error because the Action created through the MonoCDK is Invalid.

Error: Action 'models.lex.v2:CreateBot' is invalid. An action string consists of a service namespace, a colon, and the name of an action. Action names can include wildcards.

After deep diving into the code i see it is failed in validation step.
https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-iam/lib/policy-statement.ts#L76

As the awsSdkToIamAction formed from the AwsSdkMetadata is :  models.lex.v2:CreateBot.

And as the "." is not present in the Regex the validation is failing. 

### Reproduction Steps

Using : 

    "constructs": "^3.3.94",
    "monocdk": "^1.100.0"

AWSCDKCall: 

```
const sdkCall: AwsSdkCall = {
            service: 'LexModelsV2',
            action: 'createBot',
            parameters: {
                botName: 'EinsteinLexBot',
                dataPrivacy: {
                    childDirected: false
                },
                idleSessionTTLInSeconds: 1800, /* 30 Minutes */
                roleArn: props.botRoleArn,
                botTags: {
                },
                description: 'SWA - Shipper Support Bot Engine',
                testBotAliasTags: {
                }
            },
            region: props.regionalConfig.region,
            physicalResourceId: PhysicalResourceId.of(physicalResourceId)
        };
```

### What did you expect to happen?

Succesful Build

### What actually happened?

Build failure

### CDK CLI Version

1.140.0

### Node.js Version

14.x

### OS

Mac

### Language

Typescript

**Comment by gshpychka** [comment]
You seem to have forgotten to provide a title for the issue.

**Comment by jogold** [comment]
@bhavishya-singh this is because the action is incorrectly extracted from the SDK metadata for this service.

You can unblock yourself with `AwsCustomResourcePolicy.fromStatements()`:

```ts
policy: cr.AwsCustomResourcePolicy.fromStatements([
  new iam.PolicyStatement({
    actions: ['lex:CreateBot'],
    resources: ['*'],
  }),
]),
```

Note also that there is CF support for LexV2 now (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_Lex.html) so you could use the `Cfn` construct https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-lex.CfnBot.html

**Comment by NGL321** [comment]
It seems like @jogold has clarified here, thank you! 😁 

@bhavishya-singh did that help you resolve your issue?
