### ISSUE TITLE
(aws-cognito): *verified* email cannot be used for SES (Email address is not verified.)

### ISSUE THREAD

**Issue by alexandervandekleutab** [aws/aws-cdk#18964]
### What is the problem?

I cannot use a verified email in SES with the `email` property of a `CognitoUserPool`.

### Reproduction Steps

I have a verified email identity set up in SES. The SES account is out of sandbox mode. The SES account is in `us-east-1`.

When I go to create a cognito userpool in my CDK stack
```typescript
const clientUserPool = new cognito.UserPool(
      this,
      'userpool',
      {
        ...
        selfSignUpEnabled: true,
        email: cognito.UserPoolEmail.withSES({
          fromEmail: '<my-verified-email>'
          sesRegion: 'us-east-1',
        }),
      }
```

### What did you expect to happen?

I expect that the user pool will be able to use the verified SES identity, and not tell me that is is not verified.

### What actually happened?

I get the following error when I deploy:
`Cognito received the following error from Amazon SES when attempting to send email: Email address is not verified. The following identities failed the check in region US-EAST-1: arn:aws:ses:us-east-1:<accountId>:identity/<my-verified-email>(Service: AWSCognitoIdentityProviderService; Status Code: 400; Error Code: InvalidParameterException; Request ID: <requestId>; Proxy: null)`

When I try to do the equivalent in the AWS Console, it works fine.
1. Navigate to user pool
2. Go to "Messaging"
3. Configure user pool to use SES with the email `<my-verified-email>`.

### CDK CLI Version

1.134.0

### Framework Version

1.134.0

### Node.js Version

14

### OS

MacOS

### Language

Typescript

**Comment by corymhall** [comment]
@alexandervandekleutab When you go to the SES console does the ARN of the verified identity match the identity ARN in the error message? If not then we might be generating the identity ARN incorrectly.

**Comment by DManavi** [comment]
I have the same problem with us-west-2 region. Although both email address and domain are verified in us-west-2, the same error message appear on the AWS CDK output (in console). However, creating user pool using AWS console with the same configuration works fine.

**Comment by samkelleher** [comment]
I have the same issue.

* The same ARN is being displayed in Cognito UI and in SES
* In SES, it shows as verified
* It appears in the dropdown of verified senders in Cognito
* Sending the email results in the `Amazon SES when attempting to send email: Email address is not verified. ` error.
* The SES account is not in sandbox
* It was working fine for months but has stopped suddenly without changes

**Comment by samkelleher** [comment]
After investigation, there is a bug in the SES Console where an email is marked as verified when it is not.  If you run the SDK command `aws ses get-identity-verification-attributes --identities "user1@example.com"` you'll see a `Pending` status instead of verified.

Check the inbox for a verification email, or re-trigger it via the API/SDK.

Once I re-validated, normal operation resumed.

**Comment by alexandervandekleutab** [comment]
I asked for technical support from AWS and got this response:

> Checking your account from backend, we found out that Domain "<my_domain>" Ownership is verified. However, ownership verification for "<my_email@my_domain>" shows as failed. This is because of the following behavior of SES:

> In SES V1 API, the status of email address would be pending/failed if the email verification is not completed. In SES V2 API, the status of email address would be verified if the domain is successfully verified regardless of the email verification status.
> Since AWS Cognito does not support SES V2, this makes customers confused because Cognito doesn't recognize verified email addresses (in SES V2).

> To use this email with Cognito you should have received an email verification request from AWS to your email "<my_email@my_domain>". You would act on the email to confirm that you are authorized to use this email address within 24 hours after your original verification request. You can recreate this identity if its now past 24 hours and check for any email from AWS that you will need to act on to authorize the use of the email.

> You can use following CLI command to update Email.
```sh
$ aws cognito-idp update-user-pool --user-pool-id YOURPOOLID --email-configuration "SourceArn=arn:aws:ses:YOURREGION:YOURACCOUNTNO:identity/YOURDOMAIN,EmailSendingAccount=DEVELOPER,From=useruser@YOUR_DOMAIN"
```

**Comment by cody-pope** [comment]
@alexandervandekleutab I checked and looks like verifying the email (by clicking the verification link that was sent to the email - even though it shows as verified in SES) fixes it for me!  Thank you!

**Comment by corymhall** [comment]
@alexandervandekleutab it sounds like you were able to get it to work after verifying the email so I'll go ahead and close the issue.
