### ISSUE TITLE
support deploying to specific API gateway stage in CDK CLI

### ISSUE THREAD

**Issue by mrl24730** [aws/aws-cdk#18966]
### Description

deploy to specific API gateway stage using CDK CLI

### Use Case

if there are three stages `dev`, `qa`, `prod` . I would like to deploy to `qa` using `cdk deploy` command.

### Proposed Solution

add support for it.

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by rix0rrr** [comment]
You would do this by instantiating the same stack 3 times, once for every stage, and picking which one to deploy using the `cdk deploy` command:

```
cdk deploy QAStack
```
