### ISSUE TITLE
(ecs-patterns): support QueueProcessingTaskImageOptions for more advanced configuration in Queue constructs

### ISSUE THREAD

**Issue by automartin5000** [aws/aws-cdk#18961]
### Description

I need to add `DockerLabels` to a `QueueProcessingFargateService`.

### Use Case

We're using Datadog which recommends Docker Labels for tagging services for monitoring

### Proposed Solution

Add a `docker_lables` parameter to the `QueueProcessingFargateService` construct

### Other information

I tried using escape hatches to make the changes I needed to the constructs, but it seems that since `ContainerDefinitions` aren't a real resource, that it's not possible. This seems similar to [this issue](https://github.com/aws/aws-cdk/issues/16025) .

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by peterwoodworth** [comment]
Hey, you should actually be able to access this by using the `add_override` or `add_property_override` methods. I was wrong in the original thread, these methods will work even for lazily calculated values like ContainerDefinitions

```ts
    const cfnTaskDef = queueFargateService.taskDefinition.node.defaultChild as CfnTaskDefinition;
    cfnTaskDef.addPropertyOverride('ContainerDefinitions.0.DockerLabels', dockerLabels)
```

We probably won't accept a feature like this for the Ecs Patterns constructs, since they are supposed to be higher level abstractions from details like these. But at the least you still have control over the final template 🙂

**Comment by automartin5000** [comment]
> Hey, you should actually be able to access this by using the `add_override` or `add_property_override` methods. I was wrong in the original thread, these methods will work even for lazily calculated values like ContainerDefinitions
> 
> ```ts
>     const cfnTaskDef = queueFargateService.taskDefinition.node.defaultChild as CfnTaskDefinition;
>     cfnTaskDef.addPropertyOverride('ContainerDefinitions.0.DockerLabels', dockerLabels)
> ```
> 
> We probably won't accept a feature like this for the Ecs Patterns constructs, since they are supposed to be higher level abstractions from details like these. But at the least you still have control over the final template 🙂

That worked! Thanks! 

As for the feature request, why do the [other](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_ecs_patterns/NetworkLoadBalancedTaskImageOptions.html#aws_cdk.aws_ecs_patterns.NetworkLoadBalancedTaskImageOptions)  L3 [constructs](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_ecs_patterns/ApplicationLoadBalancedTaskImageOptions.html#aws_cdk.aws_ecs_patterns.ApplicationLoadBalancedTaskImageOptions)  get `TaskImageOptions` that support `DockerLabels` (among other things), but not the `QueueProcessingFargateService`? I bet it's feeling lonely 😄

**Comment by peterwoodworth** [comment]
Ah you're right, that's definitely something we can do 🙂 Thanks for calling that out. I'm going to change the title of the issue

**Comment by DahShahar** [comment]
I'm not sure if it is too late to re-open this, but I'm pretty sure that the mention for the PR that "fixes" this doesn't actually exist. And what's worse, the documentation now states:

> The task definition to use for tasks in the service. TaskDefinition or TaskImageOptions must be specified, but not both.

However, TaskImageOptions doesn't actually exist here.
