### ISSUE TITLE
(aws-cdk): cdk deploy fails when using custom toolkit stack

### ISSUE THREAD

**Issue by leoneperdigao** [aws/aws-cdk#18975]
### What is the problem?

I defined a custom toolkit names as `CustomCDKToolkit` with the qualifier `custom`.

When I try to use it in another CDK App, by specifying the custom qualifier and the custom toolkitStackName in the cdk.json, the synthesis shows the qualifier was used properly. 

When `cdk deploy` is executed is possible to see the correct IAM Roles being assumed (cdk-custom-*), but then it fails afterwards, expecting the default `/cdk-bootstrap/hnb659fds/version` parameter.

### Reproduction Steps

Create a simple CDK app, like so:

const app = new cdk.App();
new MyStack(app, 'MyStack');

Configure the custom qualifier and toolkit:

```json
{
  "app": "npx ts-node --prefer-ts-exts bin/my-app.ts",
  "toolkitStackName": "CustomCDKToolkit",
  "requireApproval": "never",
  "watch": {
    "include": [
      "**"
    ],
    "exclude": [
      "README.md",
      "cdk*.json",
      "**/*.d.ts",
      "**/*.js",
      "tsconfig.json",
      "package*.json",
      "yarn.lock",
      "node_modules",
      "test"
    ]
  },
  "context": {
    "@aws-cdk/core:bootstrapQualifier": "custom",
    "@aws-cdk/aws-apigateway:usagePlanKeyOrderInsensitiveId": true,
    "@aws-cdk/core:stackRelativeExports": true,
    "@aws-cdk/aws-rds:lowercaseDbIdentifier": true,
    "@aws-cdk/aws-lambda:recognizeVersionProps": true,
    "@aws-cdk/aws-cloudfront:defaultSecurityPolicyTLSv1.2_2021": true,
    "@aws-cdk-containers/ecs-service-extensions:enableDefaultLogDriver": true,
    "@aws-cdk/core:target-partitions": [
      "aws",
      "aws-cn"
    ]
  }
}
```

Execute deployment:

```
cdk deploy
```

### What did you expect to happen?

Successful deployment with cdk deploy

### What actually happened?

Synth OK (showing the custom qualifier)

Deployment fails:

```bash
Call failed: createChangeSet({"StackName":"MyStack","ChangeSetName":"cdk-deploy-change-set","ChangeSetType":"UPDATE","Description":"CDK Changeset for execution 7998c3db-7408-4e5c-966b-57f2124e3150","TemplateURL":"https://s3.eu-west-1.amazonaws.com/cdk-custom-assets-***-eu-west-1/57e22e084eb6e984de336c66e059b07cceeabdff0c0f7bc73ce7605adfb33fc7.json","Parameters":[{"ParameterKey":"BootstrapVersion","UsePreviousValue":true}],"RoleARN":"arn:aws:iam::***:role/cdk-custom-cfn-exec-role-***-eu-west-1","Capabilities":["CAPABILITY_IAM","CAPABILITY_NAMED_IAM","CAPABILITY_AUTO_EXPAND"]}) => Unable to fetch parameters [/cdk-bootstrap/hnb659fds/version] from parameter store for this account. (code=ValidationError)
```

❌  MyStack failed: Error [ValidationError]: Unable to fetch parameters [/cdk-bootstrap/hnb659fds/version] from parameter store for this account.

### CDK CLI Version

2.8.0 (build 8a5eb49)

### Node.js Version

v14.15.4

### OS

MacOs Monterey 12.0.1 (21A559)

### Language

Typescript

### Other information

If the rule is disabled, then the CustomCDKToolkit is used correctly without complaining about the default parameter.

```
new MyStack(app, 'MyStack', {
  tags,
  synthesizer: new DefaultStackSynthesizer({
    generateBootstrapVersionRule: false, 
  }),
});
```

**Comment by peterwoodworth** [comment]
Have you passed in [stack synthesizers](https://docs.aws.amazon.com/cdk/v2/guide/bootstrapping.html#bootstrapping-custom-synth) to your stacks? You will need to do this to tell your stacks what the names of toolkit are. 
`bootstrapStackVersionSsmParameter` is one of them, it is probably trying to fetch a parameter that doesn't exist since it's using the default one and also attempting to verify bootstrap version

**Comment by leoneperdigao** [comment]
Hi @peterwoodworth , I'm defining the custom toolkit in the cdk.json as I described. In this toolkit I have the parameter /cdk-bootstrap/custom/version. In the cdk.json I'm setting the `"toolkitStackName": "LpeCDKToolkit"` and `"@aws-cdk/core:bootstrapQualifier": "custom"`.

Like I described, CDK is being able to use the toolkit since the cdk-${Qualifier}-* roles are being used. It is also possible to see the correct parameter in the synthesized template:

```json
"Parameters": {
    "BootstrapVersion": {
      "Type": "AWS::SSM::Parameter::Value<String>",
      "Default": "/cdk-bootstrap/custom/version",
      "Description": "Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]"
    }
  },
  "Rules": {
    "CheckBootstrapVersion": {
      "Assertions": [
        {
          "Assert": {
            "Fn::Not": [
              {
                "Fn::Contains": [
                  [
                    "1",
                    "2",
                    "3",
                    "4",
                    "5"
                  ],
                  {
                    "Ref": "BootstrapVersion"
                  }
                ]
              }
            ]
          },
          "AssertDescription": "CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI."
        }
      ]
    }
  }
```

However the deploy still fails. Furthermore, setting up the stack as below makes no difference:

```typescript
new MyStack(app, 'MyStack', {
  tags,
  synthesizer: new DefaultStackSynthesizer({
    qualifier: 'custom',
    bootstrapStackVersionSsmParameter: '/cdk-bootstrap/custom/version',
  }),
});
```

**Comment by leoneperdigao** [comment]
Hello again, so actually the problem is slightly different. If you configure part on cdk.json and part on the DefaultStackSynthesizer, it won't work:

```json
{
  "app": "...",
  "toolkitStackName": "CustomCDKToolkit",
  "context": {
    "@aws-cdk/core:bootstrapQualifier": "custom"
  }
}
```

Then, omit the qualifier in the DefaultStackSynthesizer, as below, the deploy won't work.

```typescript
new MyStack(app, 'MyStack', {
  tags,
  synthesizer: new DefaultStackSynthesizer({
    bootstrapStackVersionSsmParameter: '/cdk-bootstrap/custom/version',
  }),
});
```

However, if you define the qualifier in the DefaultStackSynthesizer, it works fine. Maybe then, there is a problem while merging the configuration? With the debug or verbose option, it is possible to see all the values in the merged configuration, however the deploy mix it up somehow.

If there is no problem and that is the expected behaviour, I would suggest clarifying that on the docs [aws-cdk docs](https://github.com/aws/aws-cdk/tree/master/packages/aws-cdk) and the [synth docs](https://docs.aws.amazon.com/cdk/v2/guide/bootstrapping.html#bootstrapping-custom-synth) because it can lead to a mistake like mine.

**Comment by peterwoodworth** [comment]
I wonder if you've ran into the same issue as here https://github.com/aws/aws-cdk/issues/18453#issuecomment-1028000558

If so, then we should definitely clarify this in the docs somewhere. Let me know if these steps work for you?

**Comment by leoneperdigao** [comment]
It is not the same case. In summary, we have an app responsible for bootstrapping the environments. All the others make use of this custom bootstrap, and they never run the `cdk bootstrap` as part of their deployment.

So, we didn't have a previous deployment with another qualifier.

`cdk deploy --no-previous-parameters` makes no difference.

**Comment by peterwoodworth** [comment]
I'm not sure what could be causing this if not for previous parameters, I have been unable reproduce what you're experiencing without previous parameters getting in the way. I can use any combination of specifying the qualifier in `cdk.json` and/or the stack synthesizer.

I wonder what could cause the issue you've been experiencing here. Are you able to reproduce this on a fresh build?
