### ISSUE TITLE
Custom Resource Java SDK is out of sync with Lambda SDK

### ISSUE THREAD

**Issue by george-y** [aws/aws-cdk#1897]
Using the Java SDK and the classes don't match up (seems like custom resources API is getting pretty old). The latest versions available in Maven Central:
lambda: 0.24.1
custom-resources: 0.8.1

https://mvnrepository.com/artifact/software.amazon.awscdk/custom-resources
https://mvnrepository.com/artifact/software.amazon.awscdk/lambda

I'm setting up a table in DynamoDB and want to trigger a lambda which will populate the table. I'm trying to do that last bit by using a Custom Resource SingletonLambda but the APIs are out of sync. 

Are you getting rid of customer resources? Appreciate any alternatives on running a lambda/injecting dynamoDB data as part of cdk deploy.

**Comment by eladb** [comment]
We need to deprecate the `custom-resource` module. Thanks for reporting

**Comment by george-y** [comment]
I figured as much. Any ideas for more suitable ways to populate a dynamodb
table as part of a cdk stack?

**Comment by eladb** [comment]
Custom resources are still supported, just moved to @aws-cdk/aws-cloudformation

**Comment by RomainMuller** [comment]
Well Maven central does not support package deprecation in any form or way... So I don't know that there is anything we can do here...
