### ISSUE TITLE
(ec2): hpc6a instances type not working (ec2.InstanceClass.HIGH_PERFORMANCE_COMPUTING6_AMD)

### ISSUE THREAD

**Issue by jialechan** [aws/aws-cdk#18987]
### What is the problem?

eks add asg with c6a but response error msg: "Resource handler returned message: "The specified instance type hpc6a.xlarge is not valid"

Also, when I modify the local sdk 'hpc6a' to 'c6a', I can indeed deploy successfully, but I found that the newly started c6a instance cannot be added to eks

### Reproduction Steps

```typescript
const myAsg = cluster.addAutoScalingGroupCapacity('myasg', {
      instanceType: ec2.InstanceType.of(ec2.InstanceClass.HIGH_PERFORMANCE_COMPUTING6_AMD, ec2.InstanceSize.XLARGE),
      ...
}
```

### What did you expect to happen?

add c6a to asg and eks

### What actually happened?

receive error msg

### CDK CLI Version

2.12.0

### Node.js Version

v16.14.0

### OS

mac

### Language

Typescript

**Comment by peterwoodworth** [comment]
According to the [CloudFormation docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-instancetype), `hpc6a.48xlarge` is the only valid instance type with this instance class. So `hpc6a.xlarge` should get rejected during deployment

**Comment by jialechan** [comment]
> According to the [CloudFormation docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-instancetype), `hpc6a.48xlarge` is the only valid instance type with this instance class. So `hpc6a.xlarge` should get rejected during deployment

Thank you for your reply. That is to say, cloudformant does not support c6a.xlarge yet. We can use cdk to deploy this type after it is supported.
