### ISSUE TITLE
Improve error message when unable to fetch context

### ISSUE THREAD

**Issue by RomainMuller** [aws/aws-cdk#1898]
When the context providers make AWS service calls to determine information (such as the list of availability zones), the user credentials are currently blindly assumed to have permissions to make the required calls, and the error message is opaque (`You are not authorized to perform this operation`) and does not give any indication of what permission is missing.

Example:
```
Some context information is missing. Fetching...
Reading AZs for REDACTED:us-east-1
Using default AWS SDK credentials for account REDACTED:us
You are not authorized to perform this operation.
UnauthorizedOperation: You are not authorized to perform this operation.
 at Request.extractError (/usr/local/share/.config/yarn/global/node_modules/aws-sdk/lib/services/ec2.js:50:35)
```

**Comment by CaerusKaru** [comment]
At the very least, I think it would be helpful to document which resources are going to be using the AWS SDK, and when to expect these errors.

**Comment by eschulma** [comment]
This has been open almost a year. I am running into this, very painfully, and have to keep looking at CloudWatch (which is rather delayed).

**Comment by jordanst3wart** [comment]
The best source is still where @RomainMuller mentioned it in the gitter channel

https://gitter.im/awslabs/aws-cdk?at=5c767f19f44f3e0887817eb1

**Comment by jordanst3wart** [comment]
The implicit context is a real killer in a CI pipeline in a different AWS account

**Comment by jordanst3wart** [comment]
I still had issues with these permissions:
```
ec2:DescribeAvailabilityZones
ec2:GetAvailabilityZones
```

It worked with:
```
ec2:Describe*
ec2:Get*
```
Which are still read-only permissions

**Comment by mimozell** [comment]
I'm experiencing the same in a new project. I'm only creating a VPC at this point and I have the rights to create the VPC, so it's really unclear what the problem is.

**Comment by mimozell** [comment]
Using --verbose with cdk synth helped me find the issue. In my case it was:
`Call failed: describeAvailabilityZones(undefined) => You are not authorized to perform this operation.`

**Comment by ValiDraganescu** [comment]
> Using --verbose with cdk synth helped me find the issue. In my case it was:
> `Call failed: describeAvailabilityZones(undefined) => You are not authorized to perform this operation.`

Godlike!
