### ISSUE TITLE
diff: asset hash bucket parameter change not in diff

### ISSUE THREAD

**Issue by rittneje** [aws/aws-cdk#18992]
### What is the problem?

One of our developers ran the cdk v2 bootstrap. This changed the S3 bucket that cdk uses to store lambda function code. Afterwards, cdk diff reported no changes for any stack, but then cdk deploy started making changes because of the modified stack parameter.

cdk diff should include such parameter changes.

### Reproduction Steps

1. Deploy the v1 bootstrap.
2. Deploy a stack with cdk v1 that includes a lambda function.
3. Deploy the v2 bootstrap.
4. Deploy the same (unchanged) stack with cdk v1.

### What did you expect to happen?

I expected cdk diff to say there are no changes if and only if cdk deploy will be a no-op.

### What actually happened?

cdk diff and cdk deploy did not agree with each other.

### CDK CLI Version

1.140.0

### Node.js Version

16.13.2

### OS

Alpine 3.15

### Language

Python

### Language Version

3.9.10

**Comment by rix0rrr** [comment]
This is unfortunate, but true. There is no change to the template: the only difference will be in parameter values, and `cdk diff` does not check those (currently).

This may change if we ever change our approach to diffing, but for now this is the way it is and there are no plans to address this issue in isolation.
