### ISSUE TITLE
(aws_cdk): Import of module takes ~17 seconds (Python)

### ISSUE THREAD

**Issue by kbakk** [aws/aws-cdk#19000]
### What is the problem?

I noticed that simple commands such as `cdk ls` would take very long (sometimes above 20 seconds, rarely much less) to complete. This in a project created using `cdk init sample-app --language python`. 

### Reproduction Steps

```shell
# setup:
$ cdk init sample-app --language python
$ source .venv/bin/activate
$ pip install -r requirements.txt
# reproducing issue:
$ time python -c "import aws_cdk as cdk"
python -c "import aws_cdk as cdk"  5.74s user 4.20s system 58% cpu 17.113 total
```

### What did you expect to happen?

A simple import should not take longer than 1 second (ideally even less, but there are constrains that make that diffucult here I understand). 

### What actually happened?

As seen above, it takes ~17 seconds. This is quite consistent, however first or second time after initing the project, it can take 20-25 seconds.

### CDK CLI Version

2.12.0 (build c9786db)

### Framework Version

-

### Node.js Version

v16.14.0

### OS

MacOS 11.6.2 (20G314) - Intel Macbook

### Language

Python

### Language Version

Python (3.8.9, 3.9.10)

### Other information

To better understand where the time went, I debugged the issue with some print statements:

```
❯ time python -c "import aws_cdk as cdk"
process.py start: 0.00
self._process.args=['node', '--max-old-space-size=4069', '/var/folders/9j/cszr_w557ns8q4bk2ctzygx40000gp/T/tmp9_s6gne5/bin/jsii-runtime.js']
>>> b'{"hello":"@jsii/runtime@1.54.0"}\n'
process.py before self._next_message(): 0.25
>>> b'{"ok":{"assembly":"constructs","types":10}}\n'
process.py after self._next_message(): 0.33
process.py before self._next_message(): 0.33
>>> b'{"ok":{"assembly":"aws-cdk-lib","types":7639}}\n'
process.py after self._next_message(): 12.95
python -c "import aws_cdk as cdk"  5.72s user 4.21s system 58% cpu 16.923 total
```

The offending method seems to be (from Python's point of view) `jsii/_kernel/providers/process.py: _NodeProcess.send`

I understand that this communicates with a node process, so I assume it to be something going on there that takes very long.

**Comment by peterwoodworth** [comment]
Our libraries, with the exception of our TypeScript library, are generated automatically by [jsii](https://github.com/aws/jsii). This means that other languages can take a while to do things (especially on less powerful machines 😔), since lots of magic has to happen. 

Working on our build time is something that's always being worked on 🙂

**Comment by rix0rrr** [comment]
Moved to https://github.com/aws/jsii/issues/3389. Nothing we can do about it here.
