### ISSUE TITLE
Be able to differentiate which subnets are in a availability zone.

### ISSUE THREAD

**Issue by rob-gonz** [aws/aws-cdk#1901]
### Preface
_Yes, this is an edge case situation_

## Description
When using `@aws-ec2/ec2`,  I would like to be able to have some way to know which Subnets are within which availability zones. Currently, `publicSubnets`, `privateSubnets`, `isolatedSubnets`, and `availabilityZones` are stored ad the same interface within a couple VPC related interfaces (VPCNetworkBase, VPCNetworkImportProps, IVpcNetwork).

Since there is no way to know which availability zones host which subnets it can make bringing up some resources a bit tricky.  Particularly, when you only need one resource per AZ but the resource input is a subnet.

### EFS Mounting Targets

Only 1 mounting target should be created per availability zone.  The input for creating an EFS Mounting Target is a subnet.  With the current storage structure of the availability zones and subnets, it makes it difficult to ensure only one per AZ is created.

## Conclusion
Yes, there are workarounds. This typically won't be an issue for a VPC created using best practices and the CDK to create it.  But, this can become an issue in some environments where the VPC and subnets are pre-existing and are imported into the CDK app.

I believe it is important to have acess to this hierarchy (VPC -> AZ -> Subnet) simply becasue of the way things may need to be constructed or configured.

**Comment by rix0rrr** [comment]
Interesting. We have that information, so it makes sense to surface it as an attribute on `ISubnet`.

**Comment by rix0rrr** [comment]
Still relevant
