### ISSUE TITLE
addApplicationVpcConfiguration  interface is not supported in AWS CDK-Typescript or Cloudformation for connecting Kinesis Data Analytics -flink application to VPC

### ISSUE THREAD

**Issue by sunil-morya** [aws/aws-cdk#19029]
### Description

addApplicationVpcConfiguration  interface is not supported in AWS CDK-Typescript or Cloudformation for connecting Kinesis Data Analytics -flink application to VPC.

My team is using AWS CDK for AWS Infrastructure provisioning and it seems this interface is not supported in CDK.  

Because of this we have to launch Kinesis Data Analytics as public instance then open the AWS Management Console. Select Kinesis Data Analytics Service and then open Configuration -> look for VPC option-->Select  the Private Subnet of VPC and apply update.

Kinesis Data analytics restarts and there is down time because of this.

Can you please help me on this.

### Use Case

Launching Kinesis Data Analytics in a Private Subnet of a VPC for security enhancements and best practices

### Proposed Solution

Support in AWS CDK in typescript for addApplicationVpcConfiguration

### Other information

Please let me know when can we get the solution for this.

### Acknowledge

- [ ] I may be able to implement this feature request
- [X] This feature might incur a breaking change

**Comment by otaviomacedo** [comment]
Hi, @sunil-morya. Can you provide more details? Where should `addApplicationVpcConfiguration()` belong?
