### ISSUE TITLE
(aws-cdk-lib/aws-ec2): Update MachineImage.latestAmazonLinux generation

### ISSUE THREAD

**Issue by rdbatch02** [aws/aws-cdk#19055]
### Description

Using `MachineImage.latestAmazonLinux()` will currently default to the latest version of the original "Amazon Linux 1", which is now in a maintenance support phase and is no longer recommended for new applications. https://aws.amazon.com/amazon-linux-ami/

### Use Case

For new CDK users who are likely implementing newer functionality or looking to take advantage of new EC2 features (such as Graviton), they are going to get an "old" AMI out of the box using `MachineImage.latestAmazonLinux()` which may not support their needs. For these users, they will likely be expecting Amazon Linux 2 to be chosen since Amazon Linux is not "latest".

Existing CDK users are likely expecting Amazon Linux 2 to be considered the "latest" version, and those who are explicitly looking to use the older Amazon Linux will need to override the default in this case to support this need. Ex: `MachineImage.latestAmazonLinux({generation: AmazonLinuxGeneration.AMAZON_LINUX})`

### Proposed Solution

Update the default for the `generation` flag in `AmazonLinuxImageProps` to `AMAZON_LINUX_2` so that users get the currently supported latest version of Amazon Linux 2.

### Acknowledge

- [X] I may be able to implement this feature request
- [X] This feature might incur a breaking change

**Comment by corymhall** [comment]
This was fixed in #25083
