### ISSUE TITLE
(aws-ec2): AddRouteOptions does not include RouterType for Transit Gateway and other types

### ISSUE THREAD

**Issue by lukevo247** [aws/aws-cdk#19057]
### General Issue

Users are unable to specify transit gateway as a routertype when specifying a route for vpc subnets. As well as a variety of other types available through the AWS console.

### The Question

I want to be able to provision routes to my transit gateway. As it stands, not all of the ***router_type*** are available via CDK.

The console allows users to specify a variety of options not yet available in CDK: Transit Gateway, Virtual Private Gateway, Outposts Local Gateway, etc.

None of the existing options work, including aws_ec2.RouterType.GATEWAY which specifies an Internet Gateway.

Example:
```
for subnet in range(len(vpc.private_subnets)):
                (vpc.private_subnets[subnet]).add_route("StaticRoute",
                router_id=tgw_id,
                router_type=aws_ec2.RouterType.GATEWAY,
                destination_cidr_block="10.0.0.0/24"
                )
```
Is there a way around this to add a route to a transit gateway to my route table?
Link to documentation: https://docs.aws.amazon.com/cdk/api/v1/python/aws_cdk.aws_ec2/RouterType.html#aws_cdk.aws_ec2.RouterType

### CDK CLI Version

1.140.0

### Framework Version

1.140.0

### Node.js Version

8.1.2

### OS

macOS 12.2.1

### Language

Python

### Language Version

Python 3.9.10

### Other information

This appears to be a missing feature/bug in all of the languages across CDK v1 and v2.

**Comment by peterwoodworth** [comment]
We currently don't support this, however this should be a pretty simple fix. We accept contributions 🙂 

In the meantime, you can use [escape hatches](https://docs.aws.amazon.com/cdk/v2/guide/cfn_layer.html#cfn_layer_resource) to set the [transitGatewayId](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-route.html#cfn-ec2-route-transitgatewayid) property on the underlying CfnRoute created by addRoute.

**Comment by bearrito** [comment]
I'm not familiar with using the escape hatches. What would this look like for TGW?
