### ISSUE TITLE
cdk assert: implement 'haveOutput' assertion

### ISSUE THREAD

**Issue by Obirah** [aws/aws-cdk#1906]
Hi all,

I have a proposal for an enhancement in cdk assert: one could implement an 'haveOutput' assertion similar to the existing 'haveResource' assertion.

This functionality is especially interesting when you are developing CDK stacks that have a lot of outputs on which other CloudFormation stacks depend. With such an assertion every unit test run would assure that all outputs are correct without having to match a full template.

I imagine it looking something like this:
```
expect(stack).to(haveOutput('my-exported-output-name', {
     'Fn::GetAtt' : [
         'LogicalIdOfTheCorrespondingResource',
         'Arn']
}));
```

Opinions?

**Comment by rix0rrr** [comment]
Yep, that sounds useful!

**Comment by ilya-v-trofimov** [comment]
As interim solution, I use following utility. Might be helpful for someone:
```
import {Assertion, StackInspector} from "@aws-cdk/assert";

class HasOutputAssertion extends Assertion<StackInspector>{
    constructor(private readonly outputName: string) {
        super();
    }

    public get description(): string {
        return `output '${this.outputName}'`
    }

    assertUsing(inspector: StackInspector): boolean {
        return ('Outputs' in inspector.value) && (this.outputName in inspector.value.Outputs)
    }
}

export function hasOutput(outputName: string): Assertion<StackInspector> {
    return new HasOutputAssertion(outputName);
}
```

**Comment by RomainMuller** [comment]
Hey @ilya-v-trofimov - would you mind bending this into a PR? Sounds like you've very much done the job here...

**Comment by ilya-v-trofimov** [comment]
Hi @RomainMuller , my solution above only caters for asserting 'output name' in the stack. It requires further update to be able to assert 'output value' and 'output export name'.
I'll try to book some of my time and implement the rest.
