### ISSUE TITLE
(AppSync): Cannot return null for non-nullable type: 'ID' within parent or unable to convert to object

### ISSUE THREAD

**Issue by Blu3Parr0t** [aws/aws-cdk#19061]
### General Issue

Calling $util.toJson($myMap) doesn't return my object.

### The Question

I've been trying to get AppSync to return an object, but I keep getting this error:
"Cannot return null for non-nullable type: 'ID' within parent 'User' (/getUserByHandleName/id)"

These are the cloud logs:
Begin Request
\ GraphQL Query: query MyQuery {
  getUserByHandleName(handleName: "TestUser800") {
    id
  }
}
, Operation: MyQuery, Variables: {}
Begin Execution - Type Name: Query and Field Name: getUserUserByHandleName
{
  "logType": "RequestMapping",
  "path": [
    "getUserByHandleName"
  ],
  "fieldName": "getUserUserByHandleName",
  "resolverArn": "arn:aws:appsync:us-east-XXX/types/Query/resolvers/getUserByHandleName",
  "requestId": "XXX",
  "context": {
    "arguments": {
      "handleName": "TestUser800"
    },
    "stash": {},
    "outErrors": []
  },
  "fieldInError": false,
  "errors": [],
  "parentType": "Query",
  "graphQLAPIId": "XXXXX",
  "transformedTemplate": "\n            {\n                \"version\": \"2018-05-29\",\n                \"operation\": \"Query\",\n                \"index\": \"profile-by-handlename\",\n                \"query\": {\n                    \"expression\": \"handleName = :handleName\",\n                    \"expressionValues\": {\n                        \":handleName\": {\"S\":\"TestUser800\"}\n                    }\n                },\n                \"filter\": {\n                    \"expression\": \"begins_with(#id, :hyu)\",\n                    \"expressionNames\": {\n                        \"#id\": \"id\"\n                    },\n                    \"expressionValues\": {\n                        \":hyu\": {\"S\":\"hyu#\"}\n                    }\n                }\n            }\n            "
}
{
  "logType": "ResponseMapping",
  "path": [
    "getUserUserByHandleName"
  ],
  "fieldName": "getUserUserByHandleName",
  "resolverArn": "arn:aws:appsync:us-east-xxxx/types/Query/resolvers/getUserByHandleName",
  "requestId": "XXXXX",
  "context": {
    "arguments": {
      "handleName": "TestUser800"
    },
    "result": {
      "items": [
        {
          "owner": "xxxxxx",
          "lastName": "Silva",
          "createdAt": "2/16/2022, 4:05:30 PM",
          "firstName": "Simba",
          "handleName": "TestUser800",
          "id": "hyu#40858fef-c790-465e-b4f2-5694eb9cab59",
          "age": 11
        }
      ],
      "scannedCount": 3
    },
    "stash": {},
    "outErrors": []
  },
  "fieldInError": false,
  "errors": [],
  "parentType": "Query",
  "graphQLAPIId": "xxxxxx",
  "transformedTemplate": "\n            {\n                                                                                                                                        \"payload\": {\"id\":\"hyu#40858fef-c790-465e-b4f2-5694eb9cab59\",\"firstName\":\"Simba\",\"lastName\":\"Silva\",\"age\":11,\"handleName\":\"TestUser800\",\"interest\":null,\"images\":null,\"connectionTime\":null,\"homeTown\":null,\"greeting\":null,\"favLocations\":null,\"createdAt\":\"2/16/2022, 4:05:30 PM\",\"owner\":null}\n            }\n            "
}
xxxxxxxx End Field Execution
{
  "duration": 38942288,
  "logType": "ExecutionSummary",
  "requestId": "xxxxxxx",
  "startTime": "2022-02-21T03:48:03.750602Z",
  "endTime": "2022-02-21T03:48:03.789544Z",
  "parsing": {
    "startOffset": 28839,
    "duration": 22200
  },
  "version": 1,
  "validation": {
    "startOffset": 65624,
    "duration": 35001
  },
  "graphQLAPIId": "xxxxxxxxxx"
}
xxxxxxxx Begin Tracing
{
  "duration": 38714841,
  "logType": "Tracing",
  "path": [
    "getUserByHandleName"
  ],
  "fieldName": "getUserByHandleName",
  "startOffset": 84337,
  "resolverArn": "arn:aws:appsync:us-east-xxxxx/types/Query/resolvers/getUserByHandleName",
  "requestId": "xxxxx",
  "parentType": "Query",
  "returnType": "User",
  "graphQLAPIId": "xxxxxx"
}
{
  "duration": 6140,
  "logType": "Tracing",
  "path": [
    "getUserByHandleName",
    "id"
  ],
  "fieldName": "id",
  "startOffset": 38817638,
  "requestId": "xxxxx",
  "parentType": "User",
  "returnType": "ID!",
  "graphQLAPIId": "xxxxxxxxxx"
}
17766412-2f26-4231-9b7a-9a6b814e3017 End Tracing
{
  "logType": "RequestSummary",
  "requestId": "xxxxxxxxxxxxx",
  "graphQLAPIId": "xxxxxxxxxxxx",
  "statusCode": 200,
  "latency": 71341000
}
Tokens Consumed: 1
End Request

VTLs:
 

```
requestMappingTemplate: MappingTemplate.fromString(`
            {
                "version": "2018-05-29",
                "operation": "Query",
                "index": "profile-by-handlename",
                "query": {
                    "expression": "handleName = :handleName",
                    "expressionValues": {
                        ":handleName": $util.dynamodb.toDynamoDBJson($context.arguments.handleName)
                    }
                },
                "filter": {
                    "expression": "begins_with(#id, :hyu)",
                    "expressionNames": {
                        "#id": "id"
                    },
                    "expressionValues": {
                        ":hyu": $util.dynamodb.toDynamoDBJson("hyu#")
                    }
                }
            }
           `),
            responseMappingTemplate: MappingTemplate.fromString(`
            {
                #if($ctx.error)
                    $util.error($ctx.error.message, $ctx.error.type)
                #else
                    #if(!$ctx.result.items.isEmpty())
                        #foreach( $item in $ctx.result.items)
                            #set ($myResponse = {
                                    'id': $item.id,
                                    'firstName': $item.firstName,
                                    'lastName': $item.lastName,
                                    'age': $item.age,
                                    'handleName': $item.handleName,
                                    'interest': $item.interest,
                                    'images': $item.images,
                                    'connectionTime': $item.connectionTime,
                                    'homeTown': $item.homeTown,
                                    'greeting': $item.greeting,
                                    'favLocations': $item.favLocations,
                                    'createdAt': $item.createdAt,
                                    'owner': $null
                                })
                        #end
                    #else
                        $util.error("No results found", $util.toJson($ctx.results.items.size().toString()))
                    #end
                #end
                "payload": $util.toJson($myResponse)
            }
            `)
```

### CDK CLI Version

2.4.0 (build 993f14d)

### Language

Typescript

**Comment by Blu3Parr0t** [comment]
To anyone that may encounter something similar in the future. The answer to this is really easy. Simply put the arguments you expect straight into the key you need for your schema. I was over complicating the problem. For reference this is my working response VTL:
```
            responseMappingTemplate: MappingTemplate.fromString(`
            {
                #if($ctx.error)
                    $util.error($ctx.error.message, $ctx.error.type)
                #else
                    #if(!$ctx.result.items.isEmpty())
                        #foreach( $item in $ctx.result.items)
                            "id": $utils.toJson($item.id),
                            "firstName": $utils.toJson($item.firstName),
                            "lastName":$utils.toJson($item.lastName),
                            "age": $utils.toJson($item.age),
                            "handleName": $utils.toJson($item.handleName),
                            "interest": $utils.toJson($item.interest),
                            "images": $utils.toJson($item.images),
                            "connectionTime": $utils.toJson($item.connectionTime),
                            "homeTown": $utils.toJson($item.homeTown),
                            "greeting": $utils.toJson($item.greeting),
                            "favLocations": $utils.toJson($item.favLocations),
                            "createdAt": $utils.toJson($item.createdAt),
                            "owner": $utils.toJson($null)
                        #end
                    #else
                        $util.error("No results found", $util.toJson($ctx.results.items.size().toString()))
                    #end
                #end
            }
            `)


```

**Comment by Blu3Parr0t** [comment]
https://docs.aws.amazon.com/appsync/latest/devguide/tutorial-dynamodb-resolvers.html#setting-up-the-allpost-resolver-dynamodb-scan

Documents state it under "Setting Up the allPostResolver(DynamoDB Scan). Good luck and happy coding!

**Comment by peterwoodworth** [comment]
Thanks for posting a follow up here @Blu3Parr0t, glad you got it working!
