### ISSUE TITLE
aws_rds: from_serverless_cluster_attributes does not work

### ISSUE THREAD

**Issue by mostafafarzaneh** [aws/aws-cdk#19060]
### What is the problem?

I would need to get the existing RDS serverless cluster and add a security group to its original security group. Deploying the stack caused no change to the RDS security group list.

### Reproduction Steps

 Here is the code snippet:

```python
        sg = ec2.SecurityGroup(self, "UserSecurityGroup4RDS2", vpc=self.vpc)
        sg.add_ingress_rule(ec2.Peer.security_group_id(user_sg.security_group_id), ec2.Port.tcp(RDS_PORT))

        rds_database = rds.ServerlessCluster.from_serverless_cluster_attributes(self, "RDS2", "database-1")
        rds_database.connections.add_security_group(sg)
```

I do not receive any errors. 

### What did you expect to happen?

I expect to see the newly created security group in the RDS cluster security group list.

### What actually happened?

Executing the "cdk deploy" makes no changes to the RDS cluster security group list.

### CDK CLI Version

2.13.0

### Node.js Version

v16.14.0

### OS

Debian

### Language

Python

**Comment by mostafafarzaneh** [comment]
There is a similar issue: #12140

**Comment by skinny85** [comment]
Hey @mostafafarzaneh,

thanks for opening the issue. Unfortunately, CDK doesn't support modifying imported resources created outside the CDK. That's why the `add_security_group()` method doesn't have any effect here.

Thanks,
Adam

**Comment by mostafafarzaneh** [comment]
@skinny85 Dose the same applies to #12140 ?

**Comment by skinny85** [comment]
#12140 is a little bit different, because there you can just pass the object between Stacks, which I believe you can't in your case.
