### ISSUE TITLE
(s3): cannot override properties of existing S3 bucket

### ISSUE THREAD

**Issue by sudopla** [aws/aws-cdk#19078]
### What is the problem?

When I try to import an existing bucket with `s3.Bucket.fromBucketAttributes` or `s3.Bucket.fromBucketName` and then try to update a property using the Cfn object I get the error `TypeError: Cannot read properties of undefined (reading 'addPropertyOverride')`

Does anyone know if this is not supported?? Thanks

### Reproduction Steps

```
const bucket = s3.Bucket.fromBucketName(this, 'Bucket', props.bucketName)
const cfnBucket  = bucket.node.defaultChild as s3.CfnBucket
cfnBucket.addPropertyOverride('NotificationConfiguration.EventBridgeConfiguration.EventBridgeEnabled', true)
```

### What did you expect to happen?

I thought I could modify properties of existing resources, S3 bucket in this case. 

### What actually happened?

```
cfnBucket.addPropertyOverride('NotificationConfiguration.EventBridgeConfiguration.EventBridgeEnabled', true)
              ^
TypeError: Cannot read properties of undefined (reading 'addPropertyOverride')
```

### CDK CLI Version

2.13.0

### Node.js Version

16.3

### OS

macOS Monterey 

### Language

Typescript

**Comment by ryparker** [comment]
This is actually expected. You can't modify imported resources using CDK.

> Although you can use an imported resource anywhere, you cannot modify the imported resource. For example, calling addToResourcePolicy (Python: add_to_resource_policy) on an imported s3.Bucket does nothing.
_https://docs.aws.amazon.com/cdk/v2/guide/resources.html#resources_importing_
