### ISSUE TITLE
(aws-ecr-assets): Build and push images without deploying stacks

### ISSUE THREAD

**Issue by enricopesce** [aws/aws-cdk#19072]
### General Issue

Help

### The Question

I'm looking for a way to generate exclusively assets, build docker images and push those to ECR, at this moment I can do this only with the command

`cdk deploy`

I'm very interested in this feature because sometimes I need to create the Docker images before the deployment of all infrastructure, an example: using the same images to launch tests or scan the images with compliance tools, etc..

Some guys advise me to use 

`cdk synth`

But in my case no docker builds start, I can give only the CF template from the output.

An example of my asset implementation

```
    const web_asset = new aws_ecr_assets.DockerImageAsset(this, 'web_asset', {
      directory: path.join(__dirname, '../../../'),
      file: 'docker/nginx/Dockerfile'
    });
```

### CDK CLI Version

2.13.0

### Framework Version

2.13.0

### OS

Darwin Kernel Version 21.3.0

### Language

Typescript

### Language Version

TypeScript 3.9.7

**Comment by peterwoodworth** [comment]
I don't think this is possible. Looks to me like our asset publishing function [only gets used when `deploy` is ran](https://github.com/aws/aws-cdk/search?q=publishAssets)

Publishing assets is really only uploading files to S3/ECR. You could use the AWS CLI commands for those

**Comment by enricopesce** [comment]
Hi @peterwoodworth I think that is very useful to use the same metadata and names and not create manual push\names\etc but using the same semantic. 

Is very common to generate the asset using it and reusing it in the same CI environment, I'm looking to reuse an image for example, not rebuild the same image with different tools, I can use CDK to produce the image and push it automatically why not using it?

**Comment by peterwoodworth** [comment]
Have you tried using the [`fromEcrRepository()`](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-ecs.ContainerImage.html#static-fromwbrecrwbrrepositoryrepository-tag) method? Since you're publishing the asset to an ECR repository, you will be able to access this asset.

Additionally, I want to note that the hashing is based on the contents, size, etc of the file. So the hash should be consistent assuming you're using the same file in different locations.
