### ISSUE TITLE
(codepipeline): Error: The 'account' property must be a concrete value (action: 'ActionName')

### ISSUE THREAD

**Issue by mathewlk** [aws/aws-cdk#19090]
### What is the problem?

I'm adding a `LambdaInvokeAction` to CodePipeline, using CDK in C#. 

The lambda function itself is from a separate stack that I pull in using `Function.FromFunctionArn()`. Both stacks get passed the `Environment` field with explicit account ids. But when I try to synthesize the pipeline stack, it fails with the error above.

I'm not quite sure where I'm supposed to add this `account` field (which construct)?

### Reproduction Steps

Create a CodePipeline in CDK, add a stage to the pipeline, and add a LambdaInvokeAction, using a lambda from a different stack, but same Environment info.

### What did you expect to happen?

The synthesis should succeed. Or at least have a field in the `LambdaInvokeAction` construct to pass in an account like the error says.

### What actually happened?

```sh
Unhandled exception. Amazon.JSII.Runtime.JsiiException: The 'account' property must be a concrete value (action: 'CliMetadataUploadBeta')
   at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
   at Amazon.JSII.Runtime.Services.Client.Invoke(InvokeRequest request)
   at Amazon.JSII.Runtime.Services.Client.Invoke(ObjectReference objectReference, String method, Object[] arguments)
   at Amazon.JSII.Runtime.Deputy.DeputyBase.<InvokeMethodCore>g__GetResult|18_0[T](<>c__DisplayClass18_0`1& )
   at Amazon.JSII.Runtime.Deputy.DeputyBase.InvokeMethodCore[T](JsiiMethodAttribute methodAttribute, Object[] arguments, Func`3 beginFunc, Func`3 invokeFunc)
   at Amazon.CDK.AWS.CodePipeline.Pipeline.AddStage(IStageOptions props)
   at BP.CaaS.Application.Infrastructure.Stacks.ControlPlane.Pipelines.CliPipelineStack.AddDeployAndUploadStages(PipelineStackProps props, Pipeline codePipeline, IStage prevStage, IRole lambdaRole, IFunction cliMetadataUploadLambda, Boolean isProd) 
[cutting rest of stack trace]
Subprocess exited with error 134
``` 

### CDK CLI Version

2.8.0

### Framework Version

.NET 3.1

### Node.js Version

N/A

### OS

MacOS 10.15.7

### Language

.NET

**Comment by mathewlk** [comment]
Hmm one interesting thing is when I `Console.WriteLine` lambdaInvokeAction.ActionProperties.Account, it seems to be null...but the property is only readable, not writeable.

**Comment by skinny85** [comment]
Hi @mathewlk,

can you show the code that you use for the `Function.FromFunctionArn()` call?

Thanks,
Adam

**Comment by mathewlk** [comment]
Hi Adam, sure it's something like this:

```
IFunction lambda = Function.FromFunctionArn(
                this,
                "my-lambda",
                CdkHelper.GetSsmStringParameterValue(
                    this,
                    "/Platform/Lambda/Export/MyLambdaArn"
                ));
```

`GetSsmStringParameterValue()` is a helper method that just pulls the arn from the SSM parameter store. When I try to print out the account number from the resulting `IFunction`, it's blank. If I use `.FromFunctionAttributes()`, the account number is a CDK token. 

The only way that seems to work is passing in the lambda function directly as an argument to the stack (it's created in another stack). But we're trying to avoid that route as it breaks some other things with the other patterns we're using. Seems like there should be a way to pull in the lambda and use it in our LambdaInvokeAction.

**Comment by skinny85** [comment]
Yes, so I see the problem. The ARN of the Function is a dynamic (deploy-time only) value. Because of that, the CDK cannot figure out whether the Function and the Pipeline are in the same account/region, or not.

You said:

> Both stacks get passed the Environment field with explicit account ids. But when I try to synthesize the pipeline stack, it fails with the error above.

Is there any chance you can remove that explicit `env` property from the Stack, and see if that helps?

Thanks,
Adam

**Comment by mathewlk** [comment]
We ended up switching to L1 constructs for this piece (we're working with an external customer who prefers that over other potential solutions). Thanks for your help here.
