### ISSUE TITLE
(aws-stepfunctions-tasks): MalformedPolicyDocument on RoleDefaultPolicy

### ISSUE THREAD

**Issue by jeckscolari** [aws/aws-cdk#19106]
### What is the problem?

Trying to provision a simple state machine, CloudFormation complains about a malformed policy (_Policy statement must contain resources._) which turns out to be attached to the default role assigned to the step function.

The relevant template created by cdk is:

```json
"StepFunctionRoleDefaultPolicyF0CC7D9B": {
        "Type": "AWS::IAM::Policy",
        "Properties": {
            "PolicyDocument": {
                "Statement": [
                    {
                        "Action": "lambda:InvokeFunction",
                        "Effect": "Allow"
                    }
                ],
                "Version": "2012-10-17"
            },
            "PolicyName": "StepFunctionRoleDefaultPolicyF0CC7D9B",
            "Roles": [
                {
                    "Ref": "StepFunctionRoleEFA7D72E"
                }
            ]
        }
    }
```

### Reproduction Steps

The (relevant) stack definition is:

```python
import aws_cdk as core
from aws_cdk import (
    aws_stepfunctions as sfn,
    aws_stepfunctions_tasks as tasks,
)


class StepFunction(core.Stack):

    def __init__(self, scope: core.Stack, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        ...

        start = tasks.LambdaInvoke(
            self,
            "Start",
            lambda_function=lambda_function,
            output_path="$.Payload"
        )

        definition = start

        state_machine = sfn.StateMachine(
            self,
            "StepFunction",
            definition=definition
        )
```

### What did you expect to happen?

The generated policy statement should be something like:

```json
"Statement": [
        {
            "Action": "lambda:InvokeFunction",
            "Effect": "Allow",
            "Resource": "*"
        }
    ]
```

### What actually happened?

_Resource_ field is missing from the policy statement.

### CDK CLI Version

2.13.0 (build b0b744d)

### Framework Version

aws-cdk-lib@2.13.0, constructs@10.0.70

### Node.js Version

v16.4.1

### OS

debian buster (4.19.0-17-amd64)

### Language

Python

### Language Version

Python (3.7.3)

**Comment by kaizen3031593** [comment]
Hi @jeckscolari. This is weird because the source code shows that it is providing the lambda function arn as a resource:

https://github.com/aws/aws-cdk/blob/52128cf19ec9c35f1b79d7e6cc9088dd95bfde76/packages/%40aws-cdk/aws-stepfunctions-tasks/lib/lambda/invoke.ts#L120-L125

I created a similar app and on `cdk synth` got this resource document:

```json
          "Statement": [
            {
              "Action": "lambda:InvokeFunction",
              "Effect": "Allow",
              "Resource": {
                "Fn::GetAtt": [
                  "SubmitLambda513452FC",
                  "Arn"
                ]
              }
            }
          ],
```

This leads me to believe this is not a bug. Can you clear your `cdk.out` folder and rerun `cdk synth`? Alternatively, is it possible that your `lambda_function` somehow doesn't exist yet?
