### ISSUE TITLE
(@aws-cdk/aws-stepfunctions-tasks): Not possible to use a json as the name of the databrew StartJobRun

### ISSUE THREAD

**Issue by kakinox** [aws/aws-cdk#19108]
### What is the problem?

The name cannot be a JSON entry only a string. But stepfunctions supports name as a json

### Reproduction Steps

Try to create a databrew StartJobRun with this parameter
"Name.$" : "$.Name"

### What did you expect to happen?

I should be able to define a json name

### What actually happened?

It creates an error telling me this is not a string

### CDK CLI Version

1.145

### Node.js Version

16.10

### OS

MacOS Monterreu

### Language

Typescript

**Comment by ryparker** [comment]
Hey @kakinox 👋🏻 Thanks for bringing this to our attention.

Would you mind sharing some of the CDK code you're using for the step-function?

**Comment by kakinox** [comment]
This is a sample code. 

`import * as cdk from '@aws-cdk/core';
import * as sfn from '@aws-cdk/aws-stepfunctions';
import * as sfntask from '@aws-cdk/aws-stepfunctions-tasks';
import * as iam from '@aws-cdk/aws-iam';

export const stateMachine = (
    scope: cdk.Stack,
  ) => {

const databrewJob = new sfntask.GlueDataBrewStartJobRun(scope, 'Task', {
    name: 'databrew-job',
    integrationPattern: sfn.IntegrationPattern.RUN_JOB,
  });

  const definition = databrewJob;
  const etlStateMachine = new sfn.StateMachine(scope, 'StateMachine', {
    definition,
    tracingEnabled: true,
  });

  etlStateMachine.addToRolePolicy(new iam.PolicyStatement({
    actions: ['databrew:StartJobRun', 'iam:PassRole'],
    resources: ['*']
  }
  ));

}`

In my case, I want to create a job in the step before with an AwsCallService (working) and then use this name of this new job (passed in the state). In the class GlueDataBrewStartJobRun, I would like to define the parameter name like this 'Name.$': '$.Recipe.Name' (cf example below)

`import * as cdk from '@aws-cdk/core';
import * as sfn from '@aws-cdk/aws-stepfunctions';
import * as sfntask from '@aws-cdk/aws-stepfunctions-tasks';
import * as iam from '@aws-cdk/aws-iam';

export const stateMachine = (
    scope: cdk.Stack,
  ) => {
  const recipeJob = new sfntask.CallAwsService(scope, 'Define Databrew Recipe Job', {
    service: 'databrew',
    action: 'createRecipeJob',
    parameters: {
      ...
    },
    iamResources: [...],
    resultPath: '$.Recipe'
  });

  const databrewJob = new sfntask.GlueDataBrewStartJobRun(scope, 'Task', {
    'Name.$': '$.Recipe.Name',
    integrationPattern: sfn.IntegrationPattern.RUN_JOB,
  });

  const definition = recipeJob.next(databrewJob);
  const etlStateMachine = new sfn.StateMachine(scope, 'StateMachine', {
    definition,
    tracingEnabled: true,
  });

  etlStateMachine.addToRolePolicy(new iam.PolicyStatement({
    actions: ['databrew:StartJobRun', 'iam:PassRole'],
    resources: ['*']
  }
  ));

}`

**Comment by kakinox** [comment]
in order to be complete, I can use a JSON ('Name.$': '$.Recipe.Name') as a parameter  in the console and by using the sdk

```
  const databrewJobState = new sfntask.CallAwsService(scope, 'Start Recipe Job', {
    service: 'databrew',
    action: 'startJobRun',
    parameters: {
      'Name.$': '$.Recipe.Name',
    },
    iamResources: [...]
  });
```

**Comment by kaizen3031593** [comment]
You should use the [`JsonPath`](https://github.com/aws/aws-cdk/tree/52128cf19ec9c35f1b79d7e6cc9088dd95bfde76/packages/%40aws-cdk/aws-stepfunctions#accessing-state-the-jsonpath-class) class for this I believe. Something like this:

```ts
const databrewJob = new sfntask.GlueDataBrewStartJobRun(scope, 'Task', {
    name: sfn.JsonPath.stringAt('$.Recipe.Name'),
    integrationPattern: sfn.IntegrationPattern.RUN_JOB,
  });
```
