### ISSUE TITLE
(s3-deployment): detect changes within declared asset folder

### ISSUE THREAD

**Issue by NGL321** [aws/aws-cdk#19101]
### Description

Currently when a folder is declared as an asset, the asset hash is a checksum of the entire folder so individual file changes are not registered (ie. if a declared source has 30 files and only one is changed, the next deployment will reupload ALL 30 files rather than detecting and only uploading).

It would be useful to have an optional property that will evaluate the checksum of each file in the asset folder separately in order to reduce the number of files that are updated.

### Use Case

This feature would substantially decrease the time required for asset uploading and can avoid potential issues if the version of the individual files in the bucket need to be independently tracked.

In particular when individual file size is large, this will substantially improve performance.

### Proposed Solution

Add a construct prop in `BucketDeployment` or `Source.asset()` to enable individual file hashing.

### Other information

_Based on internal ticket request: P58403266_

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by mvoitko** [comment]
Very relevant feature

**Comment by of13tch** [comment]
Would love to see this feature

**Comment by ALFmachine** [comment]
Would like this also

**Comment by JZubero** [comment]
Me too
