### ISSUE TITLE
(aws-autoscaling): Lambda autoscaling example uses an alias to latestVersion, which doesn't work

### ISSUE THREAD

**Issue by schipono** [aws/aws-cdk#19103]
### link to reference doc page

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda.AutoScalingOptions.html

### Describe your issue?

When following the example in the docs to setup auto-scaling provisioned concurrency on a lambda function, the docs explicitly state in the example to first add an alias on the lambda function's `latestVersion`. I followed the example, setup an alias to `latestVersion`, added a basic `scaleOnUtilization` target, and then deployed the stack. The deploy went through without errors.  

After deploy, I checked the lambda in the AWS Console and noticed there was no provisioned concurrency setup for it. I drilled down into the alias associated with the lambda that I created from the example and promptly saw:

![image](https://user-images.githubusercontent.com/8990195/155265769-551cb85f-c6b1-4950-a131-548dc94601f2.png)

Did I misunderstand something in the docs or is this a bad example? Looking at the docs for `Version` I see it's example uses the `Function` method `addVersion` - and the `addVersion` method docs tell me is deprecated and points me to use `function.currentVersion`. If this is not a misunderstanding on my part, can these be updated to whatever the current best practice for setting up basic provisioned concurrency auto-scaling on the most recently deployed lambda version is?

**Comment by peterwoodworth** [comment]
This is how it looks in the readme https://github.com/aws/aws-cdk/blob/v1.159.0/packages/%40aws-cdk/aws-lambda/README.md#autoscaling

This is just a bad example. The integration test linked right below has a good example. Would you be willing to help us fix this up? Check out our [contributing guide](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) to get started.

**Comment by kaizencc** [comment]
This was fixed by https://github.com/aws/aws-cdk/pull/20034
