### ISSUE TITLE
(iam): from_role_name is missing in python

### ISSUE THREAD

**Issue by magicpotion** [aws/aws-cdk#19116]
### General Issue

from_role_name is missing in python

### The Question

`self.role = aws_iam.Role.from_role_name(
            self, id='role',
            role_name='ExampleRole' )`

AttributeError: type object 'Role' has no attribute 'from_role_name'

https://docs.aws.amazon.com/cdk/api/v1/python/aws_cdk.aws_iam/Role.html#aws_cdk.aws_iam.Role.from_role_name

### CDK CLI Version

2.8.0

### Language

Python

**Comment by peterwoodworth** [comment]
This feature is new to `v2.13.0`. You'll have to update to this version if you want to use this feature 🙂

**Comment by magicpotion** [comment]
Thanks,
May I know where is it specified in changelog?
https://github.com/aws/aws-cdk/releases/tag/v2.13.0

and where is it noted in documentation, which method is available since which version?

**Comment by peterwoodworth** [comment]
It was added in #14225 as part of another feature, so this is understandably tricky to find :)

Unfortunately, I don't think there's a super quick or user friendly way to check became available in which version if the change isn't directly called out in the changelog. 

What I did was I checked the `git blame` of the function in the source code https://github.com/aws/aws-cdk/blob/v1.145.0/packages/@aws-cdk/aws-iam/lib/role.ts#L283
I checked the commit which created it, and saw it was merged only 8 days ago. So it was pretty easy to figure out it's only on the most recent version. 

however if the change is a lot older, you can check this by viewing the version tags on the commit which created the functionality you're checking.
