### ISSUE TITLE
(custom-resources): use lambda.Runtime.NODEJS_14_X by default in Provider

### ISSUE THREAD

**Issue by pkwarren** [aws/aws-cdk#19117]
### Description

Similar to #13225, we should update to latest supported Node.js runtime for the custom-resources lambda prior to Node 12 going out of service.

https://github.com/aws/aws-cdk/blob/4e82d362fa1fa90de20f07d3a11f368ece4ab957/packages/%40aws-cdk/custom-resources/lib/provider-framework/provider.ts#L214

### Use Case

All lambdas created by aws-cdk internally should be updated prior to EOL.

### Proposed Solution

Update to `NODEJS_14_X` when creating lambda in custom-resources.

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by rix0rrr** [comment]
Can you share or link the communication you've gotten from Lambda? I can't seem to find any easily.

**Comment by pkwarren** [comment]
We've not gotten communication from AWS Lambda yet but we've in the process of updating all of our existing CDK projects because of Node 10.x no longer being supported: https://docs.aws.amazon.com/lambda/latest/dg/runtime-support-policy.html

Since Node 12.x is no longer receiving security updates this spring (https://nodejs.org/en/about/releases/) it felt like a good preventative change to keep ahead of these and use the latest supported Node runtime.

**Comment by JeeZeh** [comment]
> We've not gotten communication from AWS Lambda yet

This week we've received the following guidance from AWS:

---

> Hello,
>
> We are contacting you as we have identified that your AWS Account currently has one or more Lambda functions using Node.js 12 runtime.
>
> We are ending support for Node.js 12 in AWS Lambda. This follows Node.js 12 End-Of-Life (EOL) reached on April 30, 2022 [1].
>
> As described in the Lambda runtime support policy [2], end of support for language runtimes in Lambda happens in two stages. Starting November 14, 2022, Lambda will no longer apply security patches and other updates to the Node.js 12 runtime used by Lambda functions, and functions using Node.js 12 will no longer be eligible for technical support. In addition, you will no longer be able to create new Lambda functions using the Node.js 12 runtime. Starting December 14, 2022, you will no longer be able to update existing functions using the Node.js 12 runtime.
>
> We recommend that you upgrade your existing Node.js 12 functions to Node.js 16 before November 14, 2022.

**Comment by TakahiroImanishi** [comment]
Hi.

I think this problem is solved by #20297 .
I also checked the implementation.

https://github.com/aws/aws-cdk/issues/20297

**Comment by JeeZeh** [comment]
> Hi.
> 
> I think this problem is solved by #20297 .
> I also checked the implementation.
> 
> https://github.com/aws/aws-cdk/issues/20297

Unless I misunderstand, this only resolves the issue for a Route 53 construct which uses custom resources right? The proposed change here is to set it as the default runtime for the custom resource framework itself.

**Comment by TakahiroImanishi** [comment]
Thank you.
I understand #20297 is for a Route53 constrcut.

But,I read a source code, the code is fixed now.

https://github.com/aws/aws-cdk/blob/b8708e9ad476d12d0654ce34ae296f9c737c804d/packages/%40aws-cdk/custom-resources/lib/provider-framework/provider.ts#L210

**Comment by TakahiroImanishi** [comment]
Sorry, I may be misunderstanding the FIX Issue. 
I don't read past issues.
Whichever, I think it is fixes this issue now.

**Comment by keisukekomeda** [comment]
Provider-framework lambda functions which were created before the PR  #20595 seem to remain Node.js 12.x, even if the custom resources are redeployed.
It might be confusing for you and others.

If there's a way to update the existing provider-framework lambda function, it helps.

**Comment by peterwoodworth** [comment]
This has been fixed, live code shows node 14

**Comment by vibshukl** [comment]
Could this be updated again to version 18? Node 14 is not supported in lambda.
