### ISSUE TITLE
(vpc): creating third vpc subnet in (us-west-1) region

### ISSUE THREAD

**Issue by alamathe1** [aws/aws-cdk#19127]
### What is the problem?

We are provided a property called `maxAzs: 2` looking at manifest.json from CDK output, we see Vpc/PublicSubnet3/Subnet created but it is causing failure.

```ts
class VpcStack extends AbstractHerbieStack {
  readonly vpcA: SecureVpc;

  constructor(
    scope: Construct,
    id: string,
    options: StackOptions,
  ) {
    super(scope, id, options);
    const commonSecureVpcProps: SecureVpcProps = {};
    if (options.env.region === Region.US_WEST_1) {
      Object.assign(commonSecureVpcProps, { maxAzs: 2 });
    }
    this.vpcA = new SecureVpc(this, `${id}-vpcA`, {
      ...commonSecureVpcProps,
    });
  }
}
```

### Reproduction Steps

CDK deploy with the above code.

### What did you expect to happen?

Entires in manifest.json of cdk.out to not be present "/<REDACTED>Release/Vpc/PublicSubnet3/Subnet

### What actually happened?

Subnet3 created under release stack, even though VPC does not have it.

### CDK CLI Version

1.143.0

### Node.js Version

12.22.9

### OS

macos

### Language

Typescript

**Comment by ryparker** [comment]
Hey @alamathe1 👋🏻 

I'm not able to reproduce your issue using the code you provided. Are you sure that your condition is passing? Could you share some of the code for `SecureVpc`?

**Comment by alamathe1** [comment]
Closing the ticket as this issue was due to a bug on our side.
