### ISSUE TITLE
[aws-stepfunctions-tasks]: Allow SqsSendMessage messageGroupId param to be dynamic from input

### ISSUE THREAD

**Issue by jacques-** [aws/aws-cdk#19125]
### Description

Allow tasks.SqsSendMessage to accept sfn.TaskInput for the messageGroupId property. This would allow the messageGroupId to be set from input.

### Use Case

Setting the messageGroupId is fairly important when you are sending to a fifo queue, the use-cases for groupId in fifo queues are as per developer docs.

### Proposed Solution

When building a state like this:

```
state = aws_stepfunctions_tasks.SqsSendMessage(
            self,
            "sqs_send",
            message_body=aws_stepfunctions.TaskInput.from_json_path_at("$.message_body"),
            message_group_id="$.message_group_id",
            queue=my_queue,
        )
```

it produces a definition string like this:

```
"sqs_send": {
            "End": true,
            "Type": "Task",
            "Resource": "arn::states:::sqs:sendMessage",
            "Parameters": {
                "QueueUrl": "my_queue_url",
                "MessageBody.$": "$.message_body",
                "MessageGroupId": "$.message_group_id"
            }
        }
```

Suggest we allow it to function similar to MessageBody, and output a `MessageGroupId.$` key instead.

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by jacques-** [comment]
This is very similar to https://github.com/aws/aws-cdk/issues/14552

**Comment by kaizen3031593** [comment]
Have you tried using `jsonPath.stringAt('$.MessageGroupId')?` I think `jsonPath` is what you are looking for here. Read more here: https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-stepfunctions-tasks/README.md#L198. 

Let me know if this isn't what you're looking for, and I'll reopen the issue.
