### ISSUE TITLE
@aws-cdk/pipelines: LambdaInvocationStep support

### ISSUE THREAD

**Issue by ifitzsimmons** [aws/aws-cdk#19120]
### General Issue

CodePipeline does not support adding actions to stages

### The Question

It looks like the ability to add actions to a stage no longer exists with new [CodePipeline](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_pipelines.CodePipeline.html) API. 

I want to add a LambdaInvoke action to a stage in order to test my service like so:

```typescript
const synthStep = new ShellStep('Synth', {
  input: pipelineTrigger,
  commands: [
    'npm ci',
    'npm run test:lambda',
    'npm run build',
    'npx cdk synth'
  ]
});

const appStage = new AppStage(this, 'test', {
  env: {
    account: '928182438953',
    region: 'us-west-2',
  }
});

const pipeline = new CodePipeline(this, 'Pipeline', {
  pipelineName: 'MyPipeline',
  selfMutation: true,
  synth: synthStep,
});

pipeline.addStage(appStage);

const appStageAction = new LambdaInvokeAction({
  actionName: 'TestThumbnailCreation',
  lambda: someLambda
});

pipeline.addAction(appStageAction);
```

The `pipeline` no longer has a method to `addAction`. Is there a work around for this? I know that I can add a `post` step, which I'd like to do, but I don't see a construct for a LambdaInvocation `Step`. 

### CDK CLI Version

2.13.0

### Language

Typescript

**Comment by peterwoodworth** [comment]
You can add actions to your stages!

The [`addStage()`](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_pipelines.CodePipeline.html#addwbrstagestage-options) method on `CodePipeline` returns a [`StageDeployment`](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_pipelines.StageDeployment.html). StageDeployment comes with [`addPost()` and `addPre()`](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_pipelines.StageDeployment.html#addwbrpoststeps) methods which take in steps

If the type of step you want doesn't exist, then you can [add in any arbitrary action yourself](https://docs.aws.amazon.com/cdk/api/v1/docs/pipelines-readme.html#arbitrary-codepipeline-actions).

**Comment by ifitzsimmons** [comment]
Is there a plan to support LambdaInvocation actions through the CDK like before?

It's not really an arbitrary action because it is support natively by Pipelines. It feels weird to hack that together as a temporary workaround.

**Comment by peterwoodworth** [comment]
I'm not aware of any plans right now for the new API to directly support codepipeline actions - Based on the arbitrary action documentation existing, I think it's safe to assume it's not on our short term plan.

That said, we very much welcome [contributions](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md)

**Comment by ifitzsimmons** [comment]
I'd actually love to take a stab at this. How would you envision the feature? Would it be split into incremental features to add native Pipeline actions as steps?

**Comment by peterwoodworth** [comment]
@skinny85 will be the best one to address any design questions 😄

**Comment by skinny85** [comment]
> @skinny85 or @rix0rrr will be the best ones to address any design questions 😄

Definitely Rico is the better person to ask here 😃.

**Comment by ifitzsimmons** [comment]
Hey @rix0rrr ,

I was pretty tempted to ping you on slack but didn't want to bother you at work lol. I'd love to pitch in here if possible. If you have an idea about how this should be implemented I'd love to hear it. If not, I can just start working on it and go through the usual PR process.

**Comment by rix0rrr** [comment]
You can implement this yourself, so there is not necessarily a strict need to upstream it into the library: https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.pipelines-readme.html#arbitrary-codepipeline-actions

I can see how it might be helpful to have this built-in. It will be a CodePipeline engine-specific step then, just like `CodeBuildStep`.
