### ISSUE TITLE
aws-cdk: Issue with custom cdk deploy command

### ISSUE THREAD

**Issue by AndreeaIugaTR** [aws/aws-cdk#19135]
### What is the problem?

I'm working on a project which is an extension to the existing cdk cli toolkit. When I migrated it to cdk v2, I ran into a dependency mismatch error. 

### Reproduction Steps

```ts 

        let stack = new CustomStack(app, `custom-stack`) 

        stack.init(); 

        const assembly = app.synth(); 

        const stackArtifact = assembly.stacks[0] 

        const { configuration, sdkProvider, cloudFormation } = await deploymentConfig(args); 

  

        await cloudFormation.deployStack({ 

            stack: stackArtifact, 

            deployName: toolkitStackName, 

            roleArn: args.roleArn, 

            toolkitStackName: toolkitStackName, 

            tags: configuration.settings.get(['tags']), 

            execute: args.execute, 

            force: args.force, 

            progress: configuration.settings.get(['progress']), 

        }) 

    } 

}
``` 

### What did you expect to happen?

Deploy a custom stack 

### What actually happened?

error TS2741: Property 'name' is missing in type 'import("/../node_modules/aws-cdk-lib/cx-api/lib/artifacts/cloudformation-artifact").CloudFormationStackArtifact' but required in type '[import("/../node_modules/aws-cdk/node_modules/@aws-cdk/cx-api/lib/artifacts/cloudformation-artifact").CloudFormationStackArtifact](mailto:import(%22/../node_modules/aws-cdk/node_modules/@aws-cdk/cx-api/lib/artifacts/cloudformation-artifact%22).CloudFormationStackArtifact)'. 

  

56             stack: stackArtifact, 

               ~~~~~ 

  [node_modules/aws-cdk/node_modules/@aws-cdk/cx-api/lib/artifacts/cloudformation-artifact.d.ts:64:14](mailto:node_modules/aws-cdk/node_modules/@aws-cdk/cx-api/lib/artifacts/cloudformation-artifact.d.ts:64:14) 

    64     readonly name: string; 

                    ~~~~ 

    'name' is declared here. 

  node_modules/aws-cdk/lib/api/cloudformation-deployments.d.ts:56:5 

    56     stack: cxapi.CloudFormationStackArtifact; 

           ~~~~~ 

    The expected type comes from property 'stack' which is declared here on type 'DeployStackOptions'

### CDK CLI Version

2.13.0 

### Node.js Version

14.19.0 

### OS

All

### Language

Typescript

**Comment by rix0rrr** [comment]
It's hard to say exactly what's wrong, because this is probably a version/dependency mismatch somewhere but you haven't posted any of the code that shows how your dependencies and versions (i.e. `package.json`).

What you are doing is not supported though, and it's great that it worked for you in the past but we don't commit to support using the CDK like this, and may break at any moment. The CLI is intended to be used as a subprocess, not linked directly to its libraries. I'd recommend writing a wrapper around `subprocess.spawn()`.
