### ISSUE TITLE
(aws-lambda): Add support for dotnet 6

### ISSUE THREAD

**Issue by hastarin** [aws/aws-cdk#19148]
### Description

Dotnet 6 has been released. 

https://aws.amazon.com/about-aws/whats-new/2022/02/aws-lambda-adds-support-net6/

Can the Runtime class be updated to support this?

### Use Case

To be able to use CDK to deploy dotnet 6 Lambdas.

### Proposed Solution

Add support to the Runtime class along with any other required changes.

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by napalm684** [comment]
Possible workaround

```
import * as lambda from 'aws-cdk-lib/aws-lambda';
new lambda.Runtime('dotnet6')```
