### ISSUE TITLE
(module name): short issue description

### ISSUE THREAD

**Issue by A-ndy-git** [aws/aws-cdk#19158]
### What is the problem?

Installing `@aws-cdk/aws-apprunner-alpha` leads to an error:

`npm i @aws-cdk/aws-apprunner-alpha
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: atp@0.1.0
npm ERR! Found: aws-cdk-lib@2.10.0
npm ERR! node_modules/aws-cdk-lib
npm ERR!   aws-cdk-lib@"2.10.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer aws-cdk-lib@"^2.14.0" from @aws-cdk/aws-apprunner-alpha@2.14.0-alpha.0
npm ERR! node_modules/@aws-cdk/aws-apprunner-alpha
npm ERR!   @aws-cdk/aws-apprunner-alpha@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.`

N.B - apologies. This dosen't want to format correctly.

### Reproduction Steps

Perform `npm i @aws-cdk/aws-apprunner-alpha`

### What did you expect to happen?

Package would install correctly

### What actually happened?

Error thrown and package now installed

### CDK CLI Version

2.14.0 (build 762d71b)

### Node.js Version

v14.16.1

### OS

Mac

### Language

Typescript

### Language Version

Typescript (3.9.7)

**Comment by A-ndy-git** [comment]
Resolved by appending `--force`.

**Comment by skinny85** [comment]
@A-ndy-git the error message tells you that the `@aws-cdk/aws-apprunner-alpha` module in version `2.14.0-alpha.0` requires `aws-cdk-lib` in version `2.14.0` (or later), while you're using `2.10.0` currently.

Instead of using `--force`, which might result in runtime errors, I would suggest upgrading your `aws-cdk-lib` version to `2.14.0`. That should be a safe upgrade.

**Comment by A-ndy-git** [comment]
Thank you @skinny85, much appreciated!
