### ISSUE TITLE
CDK Pipelines: cross-account ECS CodeDeploy Action

### ISSUE THREAD

**Issue by ldecaro** [aws/aws-cdk#19163]
### What is the problem?

Hi team, I have two AWS accounts. In one account, _pipeline-account_, there is a pipeline and in the other account, _target-account_, I have a CodeDeploy already configured. I want to trigger the deployment in the _target-account_ from the _pipeline-account_ using CodeDeploy.

My use case requires that I use the `CodeDeployEcsDeployAction` to trigger a cross-account deployment. Not sure how to leverage the `EcsDeploymentGroup.fromEcsDeploymentGroupAttributes` to reference the environment of the target-account. 

According to the #5312 I tried executing the `EcsDeploymentGroup.fromEcsDeploymentGroupAttributes` from inside a stack that is deployed in the target-account and passed the reference to the action but, in the end, CodeDeploy still tries to invoke the DeploymentGroup inside the pipeline-account. 

@skinny85 mentioned he might know what could be causing this behavior.

### Reproduction Steps

As per #5312 I'm creating the `IEcsDeploymentGroup` using `fromEcsDeploymentGroupAttributes` within a stack that is deployed in the _target-account_ and I'm using that reference to configure the action.

```java
    private class CodeDeployStep extends Step implements ICodePipelineActionFactory{

        FileSet fileSet;
        Role codeDeployRole;
        IEcsDeploymentGroup dg;

        public CodeDeployStep(String id, FileSet fileSet, Role codeDeployRole, IEcsDeploymentGroup dg){
            super(id);
            this.fileSet    =   fileSet;
            this.codeDeployRole =   codeDeployRole;
            this.dg =   dg;
        }

        @Override
        public @NotNull CodePipelineActionFactoryResult produceAction(@NotNull IStage stage, @NotNull ProduceActionOptions options) {

            Artifact artifact   =   options.getArtifacts().toCodePipeline(fileSet);

            stage.addAction(CodeDeployEcsDeployAction.Builder.create()
                .actionName("Deploy")
                .role(codeDeployRole)
                .appSpecTemplateInput(artifact)
                .taskDefinitionTemplateInput(artifact)
                .runOrder(options.getRunOrder())
                .containerImageInputs(Arrays.asList(CodeDeployEcsContainerImageInput.builder()
                    .input(artifact)
                    .taskDefinitionPlaceholder("IMAGE1_NAME")
                    .build()))
                .deploymentGroup(dg)
                .variablesNamespace("deployment")
                .build());

            return CodePipelineActionFactoryResult.builder().runOrdersConsumed(1).build();
        }
        
    }
```
You can see below how I create the DeploymentGroup. I placed this code in several different locations, so the variable _this_ could refer to different constructs, including the Custom Action class, the stack deploying in the target-account, the stage.

```
        IEcsDeploymentGroup dg  =   EcsDeploymentGroup.fromEcsDeploymentGroupAttributes(
            this, 
            appName+"-ecsdeploymentgroup", 
            EcsDeploymentGroupAttributes.builder()
                .deploymentGroupName( appName )
                .application(EcsApplication.fromEcsApplicationName(
                    this, 
                    appName+"-ecs-deploy-app", 
                    appName))                                            
                .build());
```

### What did you expect to happen?

I would expect CodeDeploy to trigger a deployment in the _target-account_.

### What actually happened?

According to #5312 I was expecting CDK to trigger a deployment using CodeDeploy in the _target-account_

### CDK CLI Version

2.14.0 (build 762d71b)

### Node.js Version

v16.11.1

### OS

AmazonLinux

### Language

Java

### Language Version

Java8

**Comment by skinny85** [comment]
Hey @ldecaro,

thanks for opening the issue. Can you show the code that creates the `dg`? I think that will be the key to this problem.

Thanks,
Adam

**Comment by ldecaro** [comment]
@skinny85 I updated the issue with the constructor of the DeploymentGroup.
@rix0rrr thank you for the guidance and the heads up. I'm using CDK container assets and I wanted to have the ability to leverage the self-mutating feature of the Pipeline.

**Comment by skinny85** [comment]
@ldecaro so, did you try importing the Deployment Group into a Stack that is in the account and region that the Deployment Group is in (_not_ the Pipeline)? And can you tell me what happens when you try that?

**Comment by ldecaro** [comment]
@skinny85 Yes, I did. I created the IEcsDeploymentGroup from within a Stack that executes in the target-account. I then used a reference to the same object to configure the Action with the dg.

This is how I create the Deploy Stage. I pass the remoteStack to the CodeDeployStep and I use the IEcsDeploymentGroup created inside that stack..


```
DeployECS s = new DeployECS(this, 
            "Deploy", 
            appName,  
            StageProps.builder()
                .env(props.getEnvTarget())
                .build());
StageDeployment stage = pipeline.addStage(s);
stage.addPre(codeBuildPre);
stage.addPost(new CodeDeployStep("codeDeploy", appName, codeBuildPre.getPrimaryOutput(), codeDeployRole, s.getECSStack()));
```

```
    private class CodeDeployStep extends Step implements ICodePipelineActionFactory{

        String appName;
        FileSet fileSet;
        Role codeDeployRole;
        Stack remoteStack;

        public CodeDeployStep(String id, String appName, FileSet fileSet, Role codeDeployRole, Stack remoteStack){
            super(id);
            this.appName    =   appName;
            this.fileSet    =   fileSet;
            this.codeDeployRole =   codeDeployRole;
            this.remoteStack    =   remoteStack;
        }

        @Override
        public @NotNull CodePipelineActionFactoryResult produceAction(@NotNull IStage stage, @NotNull ProduceActionOptions options) {

            Artifact artifact   =   options.getArtifacts().toCodePipeline(fileSet);

            IEcsDeploymentGroup dg = ((ECSStack)this.remoteStack).getDG();

            stage.addAction(CodeDeployEcsDeployAction.Builder.create()
                .actionName("Deploy")
                .role(codeDeployRole)
                .appSpecTemplateInput(artifact)
                .taskDefinitionTemplateInput(artifact)
                .runOrder(options.getRunOrder())
                .containerImageInputs(Arrays.asList(CodeDeployEcsContainerImageInput.builder()
                    .input(artifact)
                    .taskDefinitionPlaceholder("IMAGE1_NAME")
                    .build()))
                .deploymentGroup( dg )
                .variablesNamespace("deployment")
                .build());

            return CodePipelineActionFactoryResult.builder().runOrdersConsumed(1).build();
        }
        
    }
```

My Deploy stage looks like this:

<img width="748" alt="image" src="https://user-images.githubusercontent.com/1972755/156080189-40e63b92-84d2-47a3-b421-f1d4fbca04a7.png">

and the error message I get is the one below. The action tries to find the application in the pipeline-account and not in the _target-account_.

<img width="449" alt="image" src="https://user-images.githubusercontent.com/1972755/156080238-78224635-d53c-4638-9c67-106b341cbba9.png">

**Comment by skinny85** [comment]
Hmm. Is there any chance you can try using the `App` as the parent of `DeployECS` (which I assume is the Stack that contains the imported Deployment Group - you haven't shown me that part of the code).

I assume `this` in your code refers to the pipeline Stack (again, you didn't show me that part, so I can't be certain), and I wonder whether that is tripping up the cross-environment resolution algorithm.

**Comment by ldecaro** [comment]
My apologies. I uploaded the code to this gist: https://gist.github.com/ldecaro/65f1dc965eaa10dd0c1d238ba28dd8a9
The variable _this_ from the `IEcsDeploymentGroup` refers to the `ECSStack` since it is created inside the `ECSStack`. Should I try using a different scope?

**Comment by skinny85** [comment]
Actually, I think I realized what is happening.

What is `codeDeployRole`? You created it in the Pipeline Stack, correct?

If that's true, this is the problem - you're using a Deployment Group from one account, but the Role in the pipeline account.

The Role needs to be in the same account as the resource of the Role. That's why the Action looks for the deployment group in the pipeline account.

Remove the Role from the created `CodeDeployEcsDeployAction`, and see if that helps.

**Comment by ldecaro** [comment]
@skinny85 it works like a charm. It also adds into the bucket policy and kms policy the references to the remote account.
@rix0rrr thanks for the guidance with regards to the expected use of CDK Pipelines.
