### ISSUE TITLE
(@aws-cdk/aws-lambda-python): handler parameter is wrong when bundling.output_path_suffix is specified

### ISSUE THREAD

**Issue by DariusKunce** [aws/aws-cdk#19161]
### What is the problem?

When I specify an output_path_suffix in the bundling options of the PythonFunction construct, handler parameter is resolved to a value that does not work in the deployed instance of the function. 

### Reproduction Steps

1. Define PythonFunction as follows: 

```python
func = python_lambda.PythonFunction(self, "AppProjectFunction",
    entry='app/hello_world_api', 
    runtime=aws_lambda.Runtime.PYTHON_3_9,  
    index='index.py', 
    handler='handler',
    bundling=python_lambda.BundlingOptions(
        output_path_suffix='app/hello_world_api'
    ),
)
```

2. run `cdk deploy`.
3. invoke the lambda function.

### What did you expect to happen?

Lambda function execution to succeed.

### What actually happened?

Lambda execution failed. 

### CDK CLI Version

2.12.0

### Framework Version

1.145.0

### Node.js Version

v14.18.0

### OS

MacOS 10.15.7

### Language

Python

### Other information

Problem is in this line of code: https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-lambda-python/lib/function.ts#L70

Deployed version of the Lambda function is as follows:
* code is stored in a folder specified in the bundling.output_path_suffix parameter
* handler parameter is `index.handler`. Instead, it should be `app.hello_world_api.index.handler`.

I am able to make it work with the following addition to the code:

```python
handler_namespace = f"{bundling.output_path_suffix.replace('/', '.')}.{index.replace('.py', '')}.{handler}"

func.node.default_child.add_property_override('Handler', handler_namespace)
```

**Comment by corymhall** [comment]
I am unassigning and marking this issue as `p2`, which means that we are unable to work on this immediately.

We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://join.slack.com/t/cdk-dev/shared_invite/zt-mso6p56d-qJp7SOTBvMaQuDrx7R2wHg) to solicit support for reprioritization.
