### ISSUE TITLE
(aws-ec2): Support configuring credit specification on NAT instance

### ISSUE THREAD

**Issue by leftiness** [aws/aws-cdk#19166]
### Description

Support configuring credit specification on NAT instance.

### Use Case

I want to deploy a NAT instance with standard credit specification. The default for t4g.nano is unlimited.

### Proposed Solution

Pass a creditSpecification property from NatInstanceProvider down to CfnInstance.

### Other information

idea

* Add a creditSpecification property to NatInstanceProps for NatInstanceProvider.
* Add a creditSpecification property to InstanceProps for Instance.
* Use the existing creditSpecification property on CfnInstanceProps for CfnInstance.

links

* https://github.com/aws/aws-cdk/blob/v2.14.0/packages/@aws-cdk/aws-ec2/lib/nat.ts#L303
* https://github.com/aws/aws-cdk/blob/v2.14.0/packages/@aws-cdk/aws-ec2/lib/instance.ts#L371

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by corymhall** [comment]
I am unassigning and marking this issue as `p2`, which means that we are unable to work on this immediately.

We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://join.slack.com/t/cdk-dev/shared_invite/zt-mso6p56d-qJp7SOTBvMaQuDrx7R2wHg) to solicit support for reprioritization.
