### ISSUE TITLE
(pipelines): CodeBuildStep.exportedVariable does not work: Output for step CodeBuildStep(Produce) not configured. Either the step is not in the pipeline, or this engine does not support Outputs for this step..

### ISSUE THREAD

**Issue by markusl** [aws/aws-cdk#19173]
### What is the problem?

Using `exportedVariable` does not work when using it in a CodePipeline.

### Reproduction Steps

Basically, using `exportedVariable` as an input for `LambdaInvokeAction` does not work and causes an error `Output for step CodeBuildStep(Produce) not configured. Either the step is not in the pipeline, or this engine does not support Outputs for this step.. `.

See https://github.com/aws/aws-cdk/pull/19156/files for a full code sample:

```ts


class TestLambdaAction extends cdkp.Step implements cdkp.ICodePipelineActionFactory {
  constructor (
    private readonly scope: Construct,
    id: string,
    private readonly userParameters?: { [key: string]: any }) {
    super(id);
  }

  public produceAction (stage: codePipeline.IStage, _options: cdkp.ProduceActionOptions): cdkp.CodePipelineActionFactoryResult {
    const lambdaPrefix = `arn:aws:lambda:${Stack.of(this.scope).region}:${Stack.of(this.scope).account}`;
    const lambdaf = lambda.Function.fromFunctionArn(this.scope, 'Lambda', `${lambdaPrefix}:function:TestLambda`);
    stage.addAction(new actions.LambdaInvokeAction({
      actionName: 'TestAction',
      lambda: lambdaf,
      userParameters: this.userParameters,
    }));
    return { runOrdersConsumed: 1 };
  }
}
  const producer = new cdkp.CodeBuildStep('Produce', {
    commands: ['export MY_VAR=hello'],
  });

  const consumer = new TestLambdaAction(pipelineStack, 'TestLambda', {
    THE_VAR: producer.exportedVariable('MY_VAR'),
  });
```

### What did you expect to happen?

I would expect to be able to use output in a pipeline step as an input for another pipeline step.

### What actually happened?

Error `Output for step CodeBuildStep(Produce) not configured. Either the step is not in the pipeline, or this engine does not support Outputs for this step.. `.

### CDK CLI Version

2.14.0

### Node.js Version

14

### OS

macOS

### Language

Typescript

### Language Version

4

**Comment by rix0rrr** [comment]
This is not as well-documented as it could be, your custom step implementation also needs to call:

```ts
this.discoverReferencedOutputs(this.userParameters)
```

in the constructor

**Comment by markusl** [comment]
Is it so that now basically every 3rd party CDK construct that implements pipeline steps needs to call `discoverReferencedOutputs` "just in case" if any of the input parameters happens to be a pipeline output? Is there any way this could be done automatically by the CDK Pipelines library?

**Comment by rix0rrr** [comment]
> Is there any way this could be done automatically by the CDK Pipelines library?

No. By the time `produceAction` gets called on the consuming step it's too late: we should already have had the information before (to calculate dependencies, and have added a `Namespace` to the the producing step, which has already been created and added at this point).

**Comment by micsafi** [comment]
I was able to reproduce this same error even with with simple CodeCommit source step. I am here creating a simple CfnOutput (just for debugging purposes), but I the goal is to pass the source attribute `CommitId` to a deployment stage.

````
  const appInput = pipelines.CodePipelineSource.codeCommit(appRepo, branchName);
  new CfnOutput(scope, 'CommitId', {
    value: appInput.sourceAttribute('CommitId')
  });

````
Error:

```
     throw new Error(`Output for step ${this.step} not configured. Either the step is not in the pipeline, or this engine does not support Outputs for this step.`);
            ^
Error: Resolution error: Output for step CodeCommitSource(application-repo) not configured. Either the step is not in the pipeline, or this engine does not support Outputs for this step..
```

This is with CDK 2.14.0 in macOS.
