### ISSUE TITLE
(stepfunctions-tasks):  `CallAwsService` produces invalid `.sync` Resource Arn (`codebuild.startBuild` action)

### ISSUE THREAD

**Issue by fedonev** [aws/aws-cdk#19174]
### What is the problem?

A `CallAwsService` task with a CodeBuild `startBuild` action and `IntegrationPattern.RUN_JOB` fails on deploy with `SCHEMA_VALIDATION_FAILED: The resource provided arn:aws:states:::aws-sdk:codebuild:startBuild.sync is not recognized.` 

An equivalent `CodeBuildStartBuild` task deploys as expected.  Note the `aws-sdk:` portion of the ARN, which appears to be invalid State Machine syntax for the `RUN_JOB` pattern:

| Task Construct      | Pattern          | CDK-generated Resource Arn Stub                      | Deploys? |
| ------------------- | ---------------- | ---------------------------------------------------- | -------- |
| CallAwsService      | RUN_JOB          | `arn:aws:states:::aws-sdk:codebuild:startBuild.sync` | ❌       |
| CallAwsService      | REQUEST_RESPONSE | `arn:aws:states:::aws-sdk:codebuild:startBuild`      | ✅       |
| CodeBuildStartBuild | RUN_JOB          | `arn:aws:states:::codebuild:startBuild.sync`         | ✅       |
| CodeBuildStartBuild | REQUEST_RESPONSE | `arn:aws:states:::codebuild:startBuild`              | ✅       |

 

### Reproduction Steps

Two equivalent constructs to start a CodeBuild build:

```typescript
const callAwsTask = new tasks.CallAwsService(this, 'CallAwsTask', {
  integrationPattern: sfn.IntegrationPattern.RUN_JOB,
  service: 'codebuild',
  action: 'startBuild',
  parameters: {
    ProjectName: project.projectName,
  },
  iamResources: [project.projectArn],
});

const startBuildTask = new tasks.CodeBuildStartBuild(this, 'StartBuildTask', {
  integrationPattern: sfn.IntegrationPattern.RUN_JOB,
  project,
});
```

### What did you expect to happen?

Expected the two constructs to deploy successfully.

### What actually happened?

The `CallAwsService` task fails to deploy with `RUN_JOB` integration.

`SCHEMA_VALIDATION_FAILED: The resource provided arn:aws:states:::aws-sdk:codebuild:startBuild.sync is not recognized.`

### CDK CLI Version

2.14.0

### Node.js Version

14

### OS

macos

### Language

Typescript

### Language Version

4.5.5

**Comment by jogold** [comment]
The `RUN_JOB` integration pattern is not supported for AWS SDK service integration.

See https://docs.aws.amazon.com/step-functions/latest/dg/supported-services-awssdk.html

The code should throw in this case.

**Comment by fedonev** [comment]
@jogold Thanks for the quick response.  Having dug deeper, my current understanding is: 

- `CallAwsService` implements [AWS SDK service integrations](https://docs.aws.amazon.com/step-functions/latest/dg/supported-services-awssdk.html).  Resource ARNs start with `arn:aws:states:::aws-sdk:`
- Other `aws_stepfunctions_tasks`implement [Optimised Integrations](https://docs.aws.amazon.com/step-functions/latest/dg/connect-supported-services.html).  Resource ARNs start with `arn:aws:states:::`

I did not previously see this correspondence.  But I now see your PR adding `CallAwsService` is literally titled _"feat(stepfunctions-tasks): AWS SDK service integrations"_ (thanks!).  What led me astray is that the two Step Function terms-of-art -- "AWS SDK service integrations" and "Optimized Integrations" -- do not seem to appear in the CDK docs.

Is my understanding correct?

**Comment by jogold** [comment]
@fedonev yes, you are correct.

You can find the term "AWS SDK integration" in the tasks doc at https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/aws-stepfunctions-tasks#aws-sdk.

The term "optimized" is indeed nowhere to be found.
