### ISSUE TITLE
pipelines.CodePipelineSource.sourceAttribute(): How and when to invoke?

### ISSUE THREAD

**Issue by micsafi** [aws/aws-cdk#19184]
### link to reference doc page

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.pipelines.CodePipelineSource.html#sourcewbrattributename

### Describe your issue?

Class `pipelines.CodePipelineSource` has method `sourceAttribute()` which should enable the CDK Pipeline application to access current source revision attributes within the pipeline, but there is absolutely no examples / documentation that in which part of the pipeline or stages this can be called.

**Comment by rix0rrr** [comment]
This line is supposed to explain that:

> These values can be passed into the environment variables of pipeline steps, so your steps can access information about the source revision.

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.pipelines.CodePipelineSource.html#sourcewbrattributename

Can you explain what part of this sentence was unclear to you?

**Comment by micsafi** [comment]
I guess some sample code would be helpful here, to demonstrate how to pass the source attribute values to the environment variables. Maybe something like this, this is for ECR source but same principle applies for other source types.

```
  const ecrInput = pipelines.CodePipelineSource.ecr(ecrRepo, {
    imageTag: `latest-mybranch`
  });


  const pipeline = new pipelines.CodePipeline(scope, 'MyPipeline', {
    synth: new pipelines.ShellStep('Synth', {
      input: ecrInput,
      commands: [
        'npm ci',
        'npm run build',
        'npx cdk synth',
      ],
      env: {
        'IMAGE_TAG': ecrInput.sourceAttribute('ImageTag'),
        'IMAGE_DIGEST': ecrInput.sourceAttribute('ImageDigest')
      }
    })
  });

```
