### ISSUE TITLE
(aws-redshift): Redshift construct is missing the  elasticIp property

### ISSUE THREAD

**Issue by rnsaway** [aws/aws-cdk#19191]
### What is the problem?

The aws-redshift-alpha cluster construct as spec'd here:

https://constructs.dev/packages/@aws-cdk/aws-redshift-alpha/v/2.14.0-alpha.0/api/Cluster?lang=typescript

is missing the elasticIp property on the CfnCluster resource.  

### Reproduction Steps

instantiate a new Cluster resource.  elasticIp prop is missing.

### What did you expect to happen?

the elasticIp property needs to be available or the construct is not able to associate an elastic IP.

### What actually happened?

elasticIp property is missing.

### CDK CLI Version

2.14

### Node.js Version

v16.14.0

### OS

macOS

### Language

Typescript

**Comment by NGL321** [comment]
Hey @rnsaway,

Since this is a missing feature in an experimental library, I have adjusted this to report as a feature-request with an implementation provided. This will help us prioritize your PR.

😸
