### ISSUE TITLE
(assets): publish Assets in parallel

### ISSUE THREAD

**Issue by skinny85** [aws/aws-cdk#19193]
### Description

Right now, we publish the Assets serially. This is slow if the customer's App contains many Assets (it's visible with as little Assets as 10).

### Use Case

CDK Apps with many (10+) Assets.

### Proposed Solution

We should switch to publishing the Assets in parallel, instead of serially. The tricky part of this will be making sure the Asset publishing progress messages are handled correctly.

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by misterjoshua** [comment]
In my project, I observed these timings:

**11 assets (10 functions):**
Synth time: 11.66s
Deployment time: 18.49s
Total time: 30.15 seconds

**3 assets (10 functions):**
Synth time: 11.47s
Deployment time: 6.61s
Total time: 18.08s

In aggregate, all assets are under 28MB.

**Comment by misterjoshua** [comment]
I was fiddling with a toy implementation. Here's a hot-swap comparison on 60 assets for 60 functions:

**Sequential**
https://user-images.githubusercontent.com/644092/158005926-5892c83e-15f6-4ebe-9158-643314cd6e68.mp4

**Parallel Asset Publishing**
https://user-images.githubusercontent.com/644092/158005966-ff40d9e3-543a-45d8-8f21-88b0a9976295.mp4

**Comment by neilkuan** [comment]
Sequential (57 seconds)

https://user-images.githubusercontent.com/46012524/158006744-d2b49b63-fbbd-4854-878d-c4bb8ab8a81d.mp4


<br> </br>

Parallel Asset Publishing (18 seconds)

https://user-images.githubusercontent.com/46012524/158006769-a27a63bd-98f9-417a-9b03-c9908543533a.mp4


cc @misterjoshua  :)
