### ISSUE TITLE
(aws-cdk-automation): `aws-cdk-lib` missing from v2 release assets

### ISSUE THREAD

**Issue by kylelaker** [aws/aws-cdk#19217]
### What is the problem?

For v1.x.x releases, such as [v1.147.0](https://github.com/aws/aws-cdk/releases/tag/v1.147.0) the created assets include the _entire_ CDK library because everything lives under `@aws-cdk/*`; however, for v2.x.x, the only attached packages are the _unstable_ packages as those are the ones under `@aws-cdk/*`. There is not a release zip of `aws-cdk-lib` available; for example, see [v2.15.0](https://github.com/aws/aws-cdk/releases/tag/v2.15.0)

### Reproduction Steps

1. Navigate to https://github.com/aws/aws-cdk/releases/tag/v2.15.0
2. View the assets
3. See that there is not any way to get a zip of `aws-cdk-lib`

### What did you expect to happen?

There would be an asset available `aws-cdk-lib-{{ version }}.zip`.

### What actually happened?

There was not an `aws-cdk-lib-{{ version }}.zip` Only docs and `aws-cdk-{{ version }}.zip` which contains only alpha modules

### CDK CLI Version

v2.x.x

### Node.js Version

N/A

### OS

N/A

### Language

Typescript

### Other information

This technically may not be an issue within the CDK repo itself (as far as I am aware) since it's part of the actual automation process. I didn't see the code for attaching/creating the actual GitHub releases within `tools/@aws-cdk` (since `create-release` seems more focused on creating `CHANGELOG.md`), `scripts/`, or `.github/workflows`. I'd be happy to take a swing at a PR if that code is available somewhere.

**Comment by madeline-k** [comment]
Hello @kylelaker, can you share a screenshot of what you're seeing? When I download [aws-cdk-2.15.0.zip](https://github.com/aws/aws-cdk/releases/download/v2.15.0/aws-cdk-2.15.0.zip), I see an `aws-cdk-lib@2.15.0.jsii.tgz` archive in the `js` directory.

**Comment by kylelaker** [comment]
You're absolutely right... I'm not sure how I missed that. Thanks and sorry for the noise.
