### ISSUE TITLE
(sns): Creating a subscription using addSubscription does not have any way of getting the subscription ARN

### ISSUE THREAD

**Issue by mjsztainbok** [aws/aws-cdk#19215]
### Description

When creating an SNS subscription using `addSubscription` on the topic object, there is no way to currently retrieve the subscription ARN for the newly created subscription

### Use Case

Most API's related to modifying a subscription or retrieving information about it require the subscription ARN and it is a good value to put as an output from CDK

### Proposed Solution

The Subscribe SNS API (https://docs.aws.amazon.com/sns/latest/api/API_Subscribe.html) returns the subscription ARN so it should be possible to get the ARN when the subscription is created

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by kaizen3031593** [comment]
Doesn't look like Cloudformation returns the subscription arn, so this might not be as easy as you think. Cloudformation [ref](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sns-subscription.html). For reference, cloudformation does return an arn for topic, which can be seen [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sns-topic.html#aws-properties-sns-topic-return-values).
