### ISSUE TITLE
(core): Add IncludeNestedStacks option to createChangeSet

### ISSUE THREAD

**Issue by konstantinj** [aws/aws-cdk#19224]
### Description

As @rectalogic points out here https://github.com/aws/aws-cdk/issues/5722#issuecomment-789146277 a year ago it is helpful to see the exact changes of nested stacks in the aws console. Without that option you only see that a nested stack will change. With that option you'll get a link in the console to the changeset of the nested stacks. This would be very helpful for me. I even think setting `IncludeNestedStacks: true` as default does not harm.

### Use Case

It's currently impossible to see changes of nested stacks even when using changesets.

### Proposed Solution

You need to add `IncludeNestedStacks: true` here: https://github.com/aws/aws-cdk/blob/bd4141d864612974829c95d530085d4f18bdfeb8/packages/aws-cdk/lib/api/deploy-stack.ts#L298

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by rectalogic** [comment]
https://github.com/aws/aws-cdk/pull/17396 does this

**Comment by konstantinj** [comment]
ok thanks. Unfortunately #19044 happened.

**Comment by konstantinj** [comment]
So is there a plan to bring this option back in?

**Comment by madeline-k** [comment]
Re-opening this issue since the change did not make it to release. It was reverted a few times due to causing failures in our CI integration tests.

**Comment by nicou** [comment]
Any updates on this? I'm currently working on migrating my project to aws-cdk v2, and getting a reliable diff on nested stack resources would be really useful 😅

**Comment by aaa-khoa** [comment]
I'm getting s3 access errors on my nested stack whenever I do cross-account deploys and was wondering if this was the issue

**Comment by diranged** [comment]
Just chiming in here... it's been a while, but this would be hugely helpful. Without this, we're hesitant to make too much use of nested stacks

**Comment by konstantinj** [comment]
still no action here? Unfortunately my workaround doesn't work anymore:

```shell
sed -i "s/ChangeSetName: changeSetName,/ChangeSetName: changeSetName,IncludeNestedStacks: true,/g" node_modules/aws-cdk/lib/api/deploy-stack.js
sed -i "s/ChangeSetName: changeSetName,/ChangeSetName: changeSetName,IncludeNestedStacks: true,/g" node_modules/aws-cdk/lib/index.js
```

doing that did the trick for me. But it looks like something has changed in the recent versions. I am on 2.70.0 now and I don't get the netested changes anymore.

Will investigate that later. It sucks not knowing what might change in a nested stack exactly.

**Comment by gagipro** [comment]
I discover this and it's a bit kind of show stopper because I was planning to use --no-execute to review changes but if cannot see what changes there are in a changeset, I really don't understand.

**Comment by gagipro** [comment]
> ```shell
> sed -i "s/ChangeSetName: changeSetName,/ChangeSetName: changeSetName,IncludeNestedStacks: true,/g" node_modules/aws-cdk/lib/api/deploy-stack.js
> sed -i "s/ChangeSetName: changeSetName,/ChangeSetName: changeSetName,IncludeNestedStacks: true,/g" node_modules/aws-cdk/lib/index.js
> ```

I don't understand 

this code is working perfectly : 
        const changeSet = await this.cfn.createChangeSet({
            StackName: this.stackName,
            ChangeSetName: changeSetName,
            ChangeSetType: this.options.resourcesToImport ? 'IMPORT' : this.update ? 'UPDATE' : 'CREATE',
            IncludeNestedStacks: true,
            ResourcesToImport: this.options.resourcesToImport,
            Description: `CDK Changeset for execution ${this.uuid}`,
            ClientToken: `create${this.uuid}`,

just need to add the IncludeNestedStacks: true,

why do we should have to patch with sed.

thanks @konstantinj

**Comment by peterwoodworth** [comment]
As mentioned above, this was merged and reverted before release because it was causing errors in our CI. I'm not sure why this caused errors in our CI before, maybe @madeline-k or someone else knows about that, all I can see is that it caused an error unexpectedly in one of our CLI integ tests https://github.com/aws/aws-cdk/pull/19618. I'm not sure what investigation, if any, has continued here. 

We would probably take another look at this sooner than later if someone helps us by submitting a PR for this

**Comment by gagipro** [comment]
> As mentioned above, this was merged and reverted before release because it was causing errors in our CI. I'm not sure why this caused errors in our CI before, maybe @madeline-k or someone else knows about that, all I can see is that it caused an error unexpectedly in one of our CLI integ tests #19618. I'm not sure what investigation, if any, has continued here.
> 
> We would probably take another look at this sooner than later if someone helps us by submitting a PR for this

Ok, in the meantime I'm using the Sed workaround and this review changeset feature is a must have for us.

I also opened a support ticket with enterprise support.

Thanks,
Regards

**Comment by gagipro** [comment]
> still no action here? Unfortunately my workaround doesn't work anymore:
> 
> ```shell
> sed -i "s/ChangeSetName: changeSetName,/ChangeSetName: changeSetName,IncludeNestedStacks: true,/g" node_modules/aws-cdk/lib/api/deploy-stack.js
> sed -i "s/ChangeSetName: changeSetName,/ChangeSetName: changeSetName,IncludeNestedStacks: true,/g" node_modules/aws-cdk/lib/index.js
> ```
> 
> doing that did the trick for me. But it looks like something has changed in the recent versions. I am on 2.70.0 now and I don't get the netested changes anymore.
> 
> Will investigate that later. It sucks not knowing what might change in a nested stack exactly.

        "sed -i 's/            ResourcesToImport: this.options.resourcesToImport,/            IncludeNestedStacks: true,\\n            ResourcesToImport: this.options.resourcesToImport,/g' /usr/local/lib/node_modules/aws-cdk/lib/api/deploy-stack.js",
        "sed -i 's/ResourcesToImport:this.options.resourcesToImport,/IncludeNestedStacks:true,ResourcesToImport:this.options.resourcesToImport,/g' /usr/local/lib/node_modules/aws-cdk/lib/index.js"

**Comment by gagipro** [comment]
I encounter this issue now that we intensively use CDK with Nested Stack. everytime there's no change in a stack it creates a failed changeset in the Nested that you cannot even delete.

https://github.com/aws/aws-cli/issues/4534

Only way to remove them is to create a change that updates the Nested Stack...

we are close from the show stopper in production with all those defects.

**Comment by rix0rrr** [comment]
This is currently being done already.
