### ISSUE TITLE
ELB V1 Search Custom Context

### ISSUE THREAD

**Issue by mjosephd** [aws/aws-cdk#1922]
We are using jenkins x CLI "jx" to generate an EKS cluster along with the required ec2 nodes. These also create a set of loadbalancers. From what I have seen so far a V2 ELB (ALB) for the kubernetes default gateway and a V1 ELB (Classic LB) for istio. (We are currently using istio, so we rely on the Classic LB for now at least).

As a result these resources are not created via our CDK app. So for example when creating a CloudFront distribution we want to find and set the V1 ELB as an origin. And in order to do so we need to create a custom context.

**Comment by SomayaB** [comment]
Closing this issue since there hasn't been any activity on it in a while. Feel free to reopen.
