### ISSUE TITLE
(aws-s3-notifications): Missing event type equivalent to  s3:ObjectRestore:Delete

### ISSUE THREAD

**Issue by mhtrinhLIC** [aws/aws-cdk#19223]
### Description

I am trying to get notified when an object that been restored but get expired, thus go back to GLASSIER class. 
I could not find the equivalent of  [s3:ObjectRestore:Delete](https://docs.aws.amazon.com/AmazonS3/latest/userguide/notification-how-to-event-types-and-destinations.html#supported-notification-event-types)  on https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-s3.EventType.html

Did I missed something ?

### Use Case

Get notification when a restored object is expired

### Proposed Solution

I am not expert enough but it may be simple as restore post and restore completed already exist.

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by otaviomacedo** [comment]
Yes, it's missing. But it should be just a matter of adding a new value to the [`EventType`](https://github.com/aws/aws-cdk/blob/02dfa4f1e320442adfbf510959440678b8e1c69f/packages/@aws-cdk/aws-s3/lib/bucket.ts#L2183) enum.
