### ISSUE TITLE
(aws-ecs-patterns): ApplicationLoadBalancedEc2ServiceProps is missing placement strategies 

### ISSUE THREAD

**Issue by IhnatKlimchuk** [aws/aws-cdk#19225]
### Description

I created an `ApplicationLoadBalancedEc2Service` service. Unfortunately, I found that service was not balanced properly against availability zones and creating 3 out of 3 tasks in 1 AV, causing worst service availability in outage case. 

### Use Case

You need to create ApplicationLoadBalancedEc2Service with custom placement strategies.

### Proposed Solution

Update `ApplicationLoadBalancedEc2ServiceProps` with ability to pass `placementStrategies?: PlacementStrategy[];` to `Ec2ServiceProps`.

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by peterwoodworth** [comment]
We accept contributions! Check out [our contributing guide](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) to get started
