### ISSUE TITLE
(ECS): Why Volumes are not supported in ECS Anywhere (ExternalTaskDefinition)

### ISSUE THREAD

**Issue by tomhol** [aws/aws-cdk#19259]
### General Issue

Local Volume support in ECS Anywhere

### The Question

Python code here:
https://github.com/aws/aws-cdk/blame/e0f863a4c56041860e14c75b9aa5a6d35860fae6/packages/%40aws-cdk/aws-ecs/lib/external/external-task-definition.ts#L78-L83

It seems the Volumes are not supported in ExternalTaskDefinition.

But according to documentation https://docs.aws.amazon.com/AmazonECS/latest/developerguide/docker-volumes.html
```
...
Docker volumes are only supported when using the EC2 launch type or external instances.
..
```

It seems it _should_ be supported for External Task Definitions.
What is the situation here? Is it a missout or a thing planned for future?
(asking because I'd like to use this feature ;))

Or am I missing something and another method should be used to configure external task with volumes?2.15.0

Thanks, Tomas.

### CDK CLI Version

2.15.0

### Language

Typescript

**Comment by peterwoodworth** [comment]
You're right, I can successfully deploy and attach a volume to an external ECS task definition. Seems to me like the addVolume function shouldn't have been overridden.

Until we support this, you can work around this with escape hatches. Here's the sample workaround code:

```ts
    const volumes = [
      {
        "EfsVolumeConfiguration": {
          "FileSystemId": "fs-g298hf293hrf"
        },
        "Name": "mydatavolume"
      }
    ];

    const externalTaskDef = new ExternalTaskDefinition(this, 'external');
    const cfnExtTaskDef = externalTaskDef.node.defaultChild as CfnTaskDefinition;
    cfnExtTaskDef.addPropertyOverride('Volumes', volumes)

    externalTaskDef.addContainer('MyContainer', {
      image: ContainerImage.fromRegistry('amazon/amazon-ecs-sample'),
      secrets: { 
        TestSecret: ecsSecret.fromSecretsManager(testSecret)
      },
      memoryLimitMiB: 1024
    });
```

**Comment by tomhol** [comment]
> ...
> Until we support this, you can work around this with escape hatches. Here's the sample workaround code: ...

Thanks a lot. It saves my day today :)
My use case is even simpler - no EFS but just local volume to share logs with a CloudWatch log forwarder sidecar container.
Feel free to close this issue or use it track the CDK code change.
Tom
