### ISSUE TITLE
(aws-apigateway): StepFunctionsIntegration failure response is not a valid json payload

### ISSUE THREAD

**Issue by rogerchi** [aws/aws-cdk#19252]
### What is the problem?

Currently, the failure response for an API Gateway REST API Step Functions Integration is not valid JSON.  It is missing a comma between the `error` and `cause` properties.

### Reproduction Steps

Use a `StepFunctionsRestApi` and have it return a Fail in the synchronous express step function.

### What did you expect to happen?

A valid JSON payload should be returned:
```
{ 
  "error": "error",
  "cause": "cause"
}
```

### What actually happened?

Invalid JSON payload is returned, missing a comma:
```
{ 
  "error": "error"
  "cause": "cause"
}
```

### CDK CLI Version

2.15.0

### Node.js Version

v14.18.1

### OS

MacOS

### Language

Typescript

**Comment by NGL321** [comment]
Thanks for the report and fix! I have published a review to merge.
