### ISSUE TITLE
appsync lambda authorizer deployed. but request returns BadRequestException

### ISSUE THREAD

**Issue by matart15** [aws/aws-cdk#19258]
### General Issue

My Issue got closed without a solution. can't reopen the closed issue. Creating new one

### The Question

AppSync returns this error.

```JSON
{
  "errors": [
    {
      "errorType": "BadRequestException"
    }
  ]
}
```

Details are on the previous issue: https://github.com/aws/aws-cdk/issues/19239

@otaviomacedo suggested me solution. But it's not [working](https://github.com/aws/aws-cdk/issues/19239#issuecomment-1059382670). O maybe I am missing something. But can't quite figure it out.

### CDK CLI Version

cdk version 2.15.0 (build 151055e)

### Language

Typescript

**Comment by matart15** [comment]
Let me just mention, It is working if I use API_KEY or Cognito auth. But lambda auth fails

![Screen Shot 2022-03-07 at 8 58 50](https://user-images.githubusercontent.com/17027219/156948043-e98a2d8f-1dc8-4b85-a7d2-6b5fa2359a16.png)

**Comment by diegoacosta-sage** [comment]
Same here... It's driving me crazy 😆 

Seems like it's a permissions problem. My lambda authorizer never receives the request to authorize it. The policy being added to the Lambda Role doesn't seem to make effect. It's like if AppSync wasn't able to invoke the lambda authorizer.

I'm using almost the same code (we're problably coming from the same [article](https://levelup.gitconnected.com/appsync-lambda-authorizers-via-new-amplify-custom-resources-5a32f41a6332)?) except that in the allowAppSyncPolicyStatement, the ARN you have commented, I have not as I understand this is how AppSync gets to invoke the authorizer?

Any help would be much appreciated.
Thanks,
Diego

**Comment by matart15** [comment]
@diegoacosta-sage 
Thank you.  At least, Now I know it's not me alone.

Hoping the cdk-team will look at it.

**Comment by diegoacosta-sage** [comment]
Hi @NGL321 @ryparker @peterwoodworth,

I've created a small repo to reproduce the issue we are facing: https://github.com/diegoacosta-sage/appsync-lambda-auth-issue

Hope it helps!
Thanks in advance,
Diego

**Comment by peterwoodworth** [comment]
Thanks for the ping and the work in creating a reproduction case for us @diegoacosta-sage 

I'm going to close this issue in favor of the original issue which I've reopened 🙂 #19239

**Comment by joshpauline** [comment]
I am getting the same error'
