### ISSUE TITLE
(aws-backup): Helper function support for FSx filesystems.

### ISSUE THREAD

**Issue by a-bigelow** [aws/aws-cdk#19269]
### Description

A `BackupResource` helper function for FSx filesystems, similar to `BackupResource.fromEfsFilesystem()`.

Additionally, the `BackupableResourcesCollector` should recognize and correctly push `fsx.CfnFileSystem` resources. 

### Use Case

The AWS-Backup module contains helper functions for other resource types, i.e.:

- `BackupResource.fromDynamoDbTable`
- `BackupResource.fromEc2Instance`
- `BackupResource.fromEfsFilesystem`
- `BackupResource.fromConstruct`

Currently there is no helper function for FSx filesystems, and the `fromConstruct` function doesn't end up adding anything to the `resources` array for the `BackupSelection` object. This leads to a runtime error from Cloudformation since either `Resources` or `ListOfTags` must be provided, and the `fromConstruct` function provides neither when you supply it an FSx filesystem.

### Proposed Solution

using the `BackupResource.fromArn()` function works with FSx filesystem Arns, so my proposed solution is the following:

For [resource.ts](https://github.com/aws/aws-cdk/blob/v2-main/packages/%40aws-cdk/aws-backup/lib/resource.ts):

A near copy of `fromEfsFilesystem`, since the properties and ARN formatting are the same:

```ts
  /**
   * An FSX file system
   */
  public static fromFsxFileSystem(fileSystem: fsx.IFileSystem) {
    return BackupResource.fromArn(Stack.of(fileSystem).formatArn({
      service: 'fsx',
      resource: 'file-system',
      resourceName: fileSystem.fileSystemId,
    }));
  }
```

For [backupable-resources-collector.ts](https://github.com/aws/aws-cdk/blob/v2-main/packages/%40aws-cdk/aws-backup/lib/backupable-resources-collector.ts):

```ts
    if (node instanceof fsx.CfnFilesystem) {
      this.resources.push(Stack.of(node).formatArn({
        service: 'fsx',
        resource: 'file-system',
        resourceName: node.ref,
      }));
    }
```

### Other information

It may also be beneficial to surface an error if the `Construct` provided to `BackupResource.fromConstruct` doesn't contain any "backupable" child nodes.

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by peterwoodworth** [comment]
Hey @a-bigelow, I am marking this issue as p2, which means that we are unable to work on this immediately.

We will happily accept community contributions, check out [our contributing guide](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) to get started 🙂
