### ISSUE TITLE
Tracking: Policy-generation creates oversized templates

### ISSUE THREAD

**Issue by NGL321** [aws/aws-cdk#19276]
### Overview

A number of customers in separate issues (as well as internal tickets) have reported problems with automatic policy generation executed by the CDK for various services. The most recurrent and problematic of those are the oversized policies generated that exceed maximum size.

This issue is to aggregate and track those separate issues and resolve once system has been revamped/revised.

### Link to the service’s CDK Construct Library API reference page.

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_iam-readme.html

### Maturity: CloudFormation Resources Only

Stable

## PRs
- [fix(iam): IAM Policies are too large to deploy by rix0rrr · Pull Request #19114 · aws/aws-cdk · GitHub](https://github.com/aws/aws-cdk/pull/19114)
- [fix(codepipeline): large cross-region pipelines exceed IAM policy size limit by skinny85 · Pull Request #16350 · aws/aws-cdk · GitHub](https://github.com/aws/aws-cdk/pull/16350)
- [feat(iam): session tagging by rix0rrr · Pull Request #17689 · aws/aws-cdk · GitHub](https://github.com/aws/aws-cdk/pull/17689)

## Reports
- [(aws-iam): changes in #17689 increase assume role policy size · Issue #18564 · aws/aws-cdk · GitHub](https://github.com/aws/aws-cdk/issues/18564)
- [ECS: Task role default policies race condition · Issue #18675 · aws/aws-cdk · GitHub](https://github.com/aws/aws-cdk/issues/18675)
- [IAM: Maximum policy size of 10240 bytes exceeded for role.. · Issue #18457 · aws/aws-cdk · GitHub](https://github.com/aws/aws-cdk/issues/18457)
- [aws-codepipeline: cross region support creates huge inline policy document for the pipeline role · Issue #16244 · aws/aws-cdk · GitHub](https://github.com/aws/aws-cdk/issues/16244)
- [(iam) Role policies are frequently exceeding 10kB · Issue #14261 · aws/aws-cdk · GitHub](https://github.com/aws/aws-cdk/issues/14261)
- [ECS Secrets from SSM ParamStore exceeds IAM Policy size · Issue #8435 · aws/aws-cdk · GitHub](https://github.com/aws/aws-cdk/issues/8435)
- [How to avoid zillions of conditional policy statements? · Issue #7732 · aws/aws-cdk · GitHub](https://github.com/aws/aws-cdk/issues/7732)
- [aws-cdk_pipelines: Maximum policy size of 10240 bytes exceeded for role · Issue #18531 · aws/aws-cdk · GitHub](https://github.com/aws/aws-cdk/issues/18531)
- [CodePipeline: Maximum policy size of 10240 bytes exceeded for role xxx · Issue #19243 · aws/aws-cdk · GitHub](https://github.com/aws/aws-cdk/issues/19243)
- [(aws_ecs): CDK insists on Modifying the ECS Execution/Task Role with duplicate permissions, resulting policy Is too big to deploy · Issue #18926 · aws/aws-cdk · GitHub](https://github.com/aws/aws-cdk/issues/18926)
- [(IAM Role) : Maximum policy size of 10240 bytes exceeded for role · Issue #12403 · aws/aws-cdk · GitHub](https://github.com/aws/aws-cdk/issues/12403)
- [[cdk-pipelines] Pipeline template grows very fast reaching the 460,800 bytes limit from CloudFormation · Issue #9225 · aws/aws-cdk · GitHub](https://github.com/aws/aws-cdk/issues/9225)
- [[@aws-cdk/pipelines] Maximum policy size of 10240 bytes exceeded for role · Issue #9316 · aws/aws-cdk · GitHub](https://github.com/aws/aws-cdk/issues/9316)
- [CodePipeline/CodeBuild: Maximum policy size of 10240 bytes exceeded for role xxx-role · Issue #4465 · aws/aws-cdk · GitHub](https://github.com/aws/aws-cdk/issues/4465)
- [(aws-cdk/pipelines): mutates role even if `withoutPolicyUpdates()` is passed · Issue #18167 · aws/aws-cdk · GitHub](https://github.com/aws/aws-cdk/issues/18167)
- [(@aws-cdk/aws-apigatewayv2-alpha): After adding around 30 routes to a http api, I got policy PolicyLengthExceededException](https://github.com/aws/aws-cdk/issues/19535#)
- [APIGateway LambdaIntegration: Add option to create a single trigger/permission with wildcards only instead of one for each ApiGateway Resource](https://github.com/aws/aws-cdk/issues/9327#)
- [CodePipeline: still getting 'Maximum policy size of 10240 bytes exceeded for role' for cross-account pipeline](https://github.com/aws/aws-cdk/issues/19835#)

## Potential Workarounds/Suggestions
- [CDK Grants into AWS Managed Policy · Issue #7448 · aws/aws-cdk · GitHub](https://github.com/aws/aws-cdk/issues/7448)
- [IAM/Secrets Manager/ECS: Consolidate IAM policies under path · Issue #18458 · aws/aws-cdk · GitHub](https://github.com/aws/aws-cdk/issues/18458)
- [(aws-s3): supply custom role when adding bucket notifications · Issue #13241 · aws/aws-cdk · GitHub](https://github.com/aws/aws-cdk/issues/13241)
- [[iam] iam.Group should check if inline policy exceeds maximum size · Issue #11562 · aws/aws-cdk · GitHub](https://github.com/aws/aws-cdk/issues/11562)
- [lambda policy size exceeds limit when used with multiple RestApi methods · Issue #5774 · aws/aws-cdk · GitHub](https://github.com/aws/aws-cdk/issues/5774)
- [(iam): how to create combined managed policy? · Issue #12111 · aws/aws-cdk · GitHub](https://github.com/aws/aws-cdk/issues/12111)
- [(aws-iam): policy document optimization · Issue #14713 · aws/aws-cdk · GitHub](https://github.com/aws/aws-cdk/issues/14713)

**Comment by peterwoodworth** [comment]
Reopening due to a number of customers still experiencing this issue

**Comment by rix0rrr** [comment]
SPecifically for CDK Pipelines:


https://github.com/aws/aws-cdk/issues/19939
https://github.com/aws/aws-cdk/issues/19835
