### ISSUE TITLE
(Triggers):  Permissions race condition: not authorized to perform: lambda:InvokeFunction

### ISSUE THREAD

**Issue by deuscapturus** [aws/aws-cdk#19272]
### What is the problem?

Trigger stack creations succeed, but updates fails with error:

```
12:37:55 PM | UPDATE_FAILED        | Custom::Trigger       | PublishDevOpsDashboardMetrics
Received response status [FAILED] from custom resource. Message returned: AccessDeniedException: User: arn:aws:sts::000000000000:assumed-role/search-test-trigger-delet-AWSCDKTriggerCustomResou-1WJNIVYDBY6D2/search-test-trigger-delet-AWS
CDKTriggerCustomResou-pOS3k3dmifGe is not authorized to perform: lambda:InvokeFunction on resource: arn:aws:lambda:us-west-2:000000000000:function:search-test-trigger-delet-PublishDevOpsDashboardMe-h7bTtHL1pu4B:2 because no identity-bas
ed policy allows the lambda:InvokeFunction action
```

This Trigger lambda publishes change notifications.  The dynamic parts of this notification as passed to the lambda in the `Environment`.  This however forces an update of the Lambda resource and IAM role policy allowing `lambda:InvokeFunction`.  I believe a race condition is occurring where the IAM role policy is not updated in time for the custom resource Lambda invocation.

### Reproduction Steps

Create the example construct below

```
import { Stack, StackProps } from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as triggers from 'aws-cdk-lib/triggers'
import * as lambda from 'aws-cdk-lib/aws-lambda';

export class CdkTriggerStack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);

    const trigger = new triggers.Trigger(this, "PublishDevOpsDashboardMetrics", { 
      handler: new lambda.Function(this, "PublishDevOpsDashboardMetricsLambda", {
        code: new lambda.InlineCode(`#!/usr/bin/python3\nimport os\ndef handler(event, context):\n  print(event, os.getenv('DEPLOYMENT_VERSION'))`),
        handler: 'index.handler',
        runtime: lambda.Runtime.PYTHON_3_9,
        environment: {
            DEPLOYMENT_VERSION: "1",
        }
      })
    })
  }
}
```

Update environment DEPLOYMENT_VERSION to `2` and update the stack.  This fails every time for me, but may not fail every time if this is a race condition.

### What did you expect to happen?

no error

### What actually happened?

 AccessDeniedException error

### CDK CLI Version

2.15.0

### Node.js Version

v14.17.0

### OS

Fedora

### Language

Typescript

### Other information

I think the Triggers implementation is flawed.  It would be better to have a one Lambda for the custom resource and allow parameters to be passed via resource parameters.  This way the Lambda resources doesn't need to update with each deploy.

I recommend not using Triggers and instead implementing your own custom resource.

**Comment by tenjaa** [comment]
Ran into this issue today.
As you recommend an own custom resource, do you have an example to get some inspiration?

**Comment by rix0rrr** [comment]
Adding a dependency on the permissions should be good enough

**Comment by rix0rrr** [comment]
Amazing that this hasn't come up in all this time this package has been out

**Comment by tenjaa** [comment]
Anyone working on this?
I tried but failed to get the project running locally which made it hard to fix the snapshots.

**Comment by pgarbe** [comment]
I just used Trigger the first time and came across this issue. This is my workaround:

```ts
const trigger = new cdk.triggers.Trigger(this, 'Trigger', {
    handler: lambda,
});

// Add explicit dependency to provider
const p = this.node.findChild('AWSCDK.TriggerCustomResourceProviderCustomResourceProvider');
trigger.node.addDependency(p);
```

**Comment by victorsmirnov** [comment]
When I change the lambda function, I get this issue with permissions; the trigger does not have permission to execute the new version of the lambda function.

As a workaround, I do the following steps. First, allow any lambda function to execute my lambda. Second, add my lambda function as a dependency for the trigger. Please check the code below.

```
const changePwdFunction = new NodejsFunction(stack, "ChangePwdFunction", {
    // Skipped function definition
    timeout: Duration.seconds(60), // In my case it might take 10-30 seconds to warm up the function.
    vpc,
});
/**
 * Step 1: Grant permission to anyone to execute the lambda.
 */
changePwdFunction.grantInvoke(new ServicePrincipal("lambda.amazonaws.com"));
changePwdFunction.currentVersion.grantInvoke(new ServicePrincipal("lambda.amazonaws.com"));

const trigger = new Trigger(stack, "ChangePwdTrigger", {
    executeAfter: [databaseCluster],
    handler: changePwdFunction,
    executeOnHandlerChange: true,
});
/**
 * This is a workaround for the issue https://github.com/aws/aws-cdk/issues/19272
 * Step 2: Make sure we finish lambda changes (including permissions) before dealing with the trigger.
 */
trigger.node.addDependency(changePwdFunction);
```

Please let me know if you see any issues with this approach.

**Comment by Chriscbr** [comment]
I also ran into this issue. Workaround from @pgarbe worked for me

**Comment by TeejMonster** [comment]
Also confirming that the @pgarbe workaround was the ticket for me.

**Comment by srinivas-kini** [comment]
This issue still persists in the latest CDK version `2.37.1 (build f15dee0)`. I had to use the fix recommended by @pgarbe

**Comment by AmizerAWS** [comment]
Also in 2.38.1 When you define two triggerFunctions and run them one by one, Custom resource provider defined for them will only have the lambda invoke function permissions for the first one, resulting in access denied when trying to run the second one

**Comment by dossy** [comment]
This issue is still not fixed, can it be re-opened?

**Comment by jjtindale** [comment]
> Also in 2.38.1 When you define two triggerFunctions and run them one by one, Custom resource provider defined for them will only have the lambda invoke function permissions for the first one, resulting in access denied when trying to run the second one

@AmizerAWS This just caught me out. The solution I found was to reference the custom resource `.grantPrincipal` instead of the role:

``` diff 
const fn = new NodejsFunction(...);

const customResourceRole = new Role(this, 'custom-resource-role', {
    assumedBy: new ServicePrincipal('lambda.amazonaws.com')
});

const customResource = new AwsCustomResource(this, "custom-resource", {
    ...
    role: customResourceRole,
});

- fn.grantInvoke(customResourceRole);
+ fn.grantInvoke(customResource.grantPrincipal);
```

See here: https://github.com/aws/aws-cdk/issues/13601
