### ISSUE TITLE
(Lambda) DynamoDB to Lambda trigger batch size limit is just 1000 for CDK

### ISSUE THREAD

**Issue by pratik-g16** [aws/aws-cdk#19285]
### What is the problem?

While creating a trigger for Lambda using DynamoDB Streams as source, the CDK allows only 1000 to be set as the maximum batch size. However in the documentation and using the console, we can create a trigger with a maximum batch size of 10000 records. 

 

### Reproduction Steps

handler.addEventSource(
      new DynamoEventSource(table, {
        startingPosition: lambda.StartingPosition.LATEST,
        batchSize: 10000 })
    );

### What did you expect to happen?

By this code i was expecting that a trigger will be created from DynamoDB to Lambda with a batch size of 10k records. 

### What actually happened?

Error: Maximum batch size must be between 1 and 1000 inclusive (given 10000)
<img width="1044" alt="error" src="https://user-images.githubusercontent.com/66935686/157280974-768b56a4-7b3c-4ac0-bd7d-c6daba1345ab.png">

### CDK CLI Version

2.15.0

### Node.js Version

v16.14.0

### OS

Mac Os

### Language

Typescript

### Language Version

4.6.2

**Comment by peterwoodworth** [comment]
The documentation in CloudFormation, which we are limited by, is incorrect (likely outdated, like this code)

You can work around this for now until we fix it with escape hatches

```ts
    for (const child of handler.node.children) {
      if (child instanceof EventSourceMapping) {
        let map = child as EventSourceMapping;
        let cfnmap = map.node.defaultChild as CfnEventSourceMapping
        cfnmap.addPropertyOverride('BatchSize', 10000)
      }
    }
```
