### ISSUE TITLE
(aws_cdk/core) creating folder called "constructs" in the root folder interferes with importing constructs library

### ISSUE THREAD

**Issue by goudhabuddha** [aws/aws-cdk#19301]
### What is the problem?

After running cdk synth or cdk ls, I get this error. I have not tested the other commands.
``` python
Traceback (most recent call last):
  File "/Users/redacted/Documents/Code/myrepo/myproject/app.py", line 3, in <module>
    from aws_cdk.core import App, Environment
  File "/Users/redacted/Documents/Code/myrepo/myproject/.venv/lib/python3.10/site-packages/aws_cdk/core/__init__.py", line 978, in <module>
    from ._jsii import *
  File "/Users/redacted/Documents/Code/myrepo/myproject/.venv/lib/python3.10/site-packages/aws_cdk/core/_jsii/__init__.py", line 14, in <module>
    import constructs._jsii
ModuleNotFoundError: No module named 'constructs._jsii'
```
Note: replaced actual repo and project name with myrepo and myproject

### Reproduction Steps

Init a cdk python project, create the venv, install the requirements into the venv
``` txt
python-dotenv
aws-cdk.core>=1.147.0
aws-cdk.aws-s3>=1.147.0
aws-cdk.aws-lambda>=1.147.0
aws-cdk.aws-dynamodb>=1.147.0
aws-cdk.aws-ecs>=1.147.0
aws-cdk.aws-ecr>=1.147.0
aws-cdk.aws-stepfunctions>=1.147.0
aws-cdk.aws-stepfunctions-tasks>=1.147.0
aws-cdk.aws-sqs>=1.147.0
aws-cdk.aws-iam>=1.147.0
aws-cdk.aws-sns>=1.147.0
aws-cdk.aws-secretsmanager>=1.147.0
aws-cdk.aws-rds>=1.147.0
```
``` python
# app.py
import os
from aws_cdk.core import App, Environment
from myproject.platform import dynamo

account_id = os.environ["CDK_DEFAULT_ACCOUNT"]
region = os.environ["CDK_DEFAULT_REGION"]

environment = Environment(
    account=account_id,
    region=region
)

app = App()

dynamo.DynamoStack(app, "CdkAppPythonStack", #
    env=environment
)

app.synth()
```

I am not sure if any of the code after the import has anything to do with the error. Let me know if more information is needed than the bare necessities I pasted.

Finally, run `cdk synth` and it results in the error.

### What did you expect to happen?

I expected cdk synth to run and output a simple stack with a Dynamo table in it.

### What actually happened?

An unexpected error was raised, seemingly out of my control.

### CDK CLI Version

1.147.0 (build f9b35cf)

### Node.js Version

8.5.3

### OS

macOS Monterey 12.0.1

### Language

Python

### Language Version

3.10.0

### Other information

pip freeze
``` text
attrs==21.4.0
aws-cdk.assets==1.147.0
aws-cdk.aws-acmpca==1.147.0
aws-cdk.aws-apigateway==1.147.0
aws-cdk.aws-applicationautoscaling==1.147.0
aws-cdk.aws-autoscaling==1.147.0
aws-cdk.aws-autoscaling-common==1.147.0
aws-cdk.aws-autoscaling-hooktargets==1.147.0
aws-cdk.aws-certificatemanager==1.147.0
aws-cdk.aws-cloudformation==1.147.0
aws-cdk.aws-cloudfront==1.147.0
aws-cdk.aws-cloudwatch==1.147.0
aws-cdk.aws-codebuild==1.147.0
aws-cdk.aws-codecommit==1.147.0
aws-cdk.aws-codeguruprofiler==1.147.0
aws-cdk.aws-codestarnotifications==1.147.0
aws-cdk.aws-cognito==1.147.0
aws-cdk.aws-dynamodb==1.147.0
aws-cdk.aws-ec2==1.147.0
aws-cdk.aws-ecr==1.147.0
aws-cdk.aws-ecr-assets==1.147.0
aws-cdk.aws-ecs==1.147.0
aws-cdk.aws-efs==1.147.0
aws-cdk.aws-eks==1.147.0
aws-cdk.aws-elasticloadbalancing==1.147.0
aws-cdk.aws-elasticloadbalancingv2==1.147.0
aws-cdk.aws-events==1.147.0
aws-cdk.aws-globalaccelerator==1.147.0
aws-cdk.aws-iam==1.147.0
aws-cdk.aws-kinesis==1.147.0
aws-cdk.aws-kms==1.147.0
aws-cdk.aws-lambda==1.147.0
aws-cdk.aws-logs==1.147.0
aws-cdk.aws-rds==1.147.0
aws-cdk.aws-route53==1.147.0
aws-cdk.aws-route53-targets==1.147.0
aws-cdk.aws-s3==1.147.0
aws-cdk.aws-s3-assets==1.147.0
aws-cdk.aws-sam==1.147.0
aws-cdk.aws-secretsmanager==1.147.0
aws-cdk.aws-servicediscovery==1.147.0
aws-cdk.aws-signer==1.147.0
aws-cdk.aws-sns==1.147.0
aws-cdk.aws-sns-subscriptions==1.147.0
aws-cdk.aws-sqs==1.147.0
aws-cdk.aws-ssm==1.147.0
aws-cdk.aws-stepfunctions==1.147.0
aws-cdk.aws-stepfunctions-tasks==1.147.0
aws-cdk.cloud-assembly-schema==1.147.0
aws-cdk.core==1.147.0
aws-cdk.custom-resources==1.147.0
aws-cdk.cx-api==1.147.0
aws-cdk.lambda-layer-awscli==1.147.0
aws-cdk.lambda-layer-kubectl==1.147.0
aws-cdk.lambda-layer-node-proxy-agent==1.147.0
aws-cdk.region-info==1.147.0
cattrs==1.10.0
constructs==3.3.237
jsii==1.54.0
publication==0.0.3
python-dateutil==2.8.2
python-dotenv==0.19.2
six==1.16.0
typing_extensions==4.1.1
```

I have tried removing all modules, reinstalling with no-cache-dir, nuking the venv and starting from scratch. I tried using a "last known good" version: 1.134.0 and same result. I have other cdk projects to reference, that are working, and I could not spot any key differences. The pip versions match the installed CDK version. Initially. I suspected it was a version mismatch causing the problem but it appears not to be the case. I also edited cdk.json and tried replacing "python3 app.py" with "python app.py" to no avail.

**Comment by peterwoodworth** [comment]
Usually these errors are caused by version mismatches, in fact I'm not sure I've ever seen an issue like this that wasn't due to something like that. 

I hate to tell you that it's still probably that after all you've tried, but since you can work on other projects just fine and I can't reproduce it, I can't help but feel something is just slightly misconfigured somewhere

**Comment by peterwoodworth** [comment]
by the way, is there anything preventing you from updating to v2? These issues are much less common in v2 due to the monopackage 🙂

**Comment by goudhabuddha** [comment]
> by the way, is there anything preventing you from updating to v2? These issues are much less common in v2 due to the monopackage 🙂

Our cloud platform team is investigating the impact of the new V2 bootstrap process. It interferes with other things, apparently, so I am stuck using V1 until that mess gets sorted out.

> I hate to tell you that it's still probably that after all you've tried, but since you can work on other projects just fine and I can't reproduce it, I can't help but feel something is just slightly misconfigured somewhere

Do you have any further recommendations of action I can take? I have tried uninstalling CDK from npm, uninstalling all requirements, making sure there are no weird conflicts between the venv and the global python modules on my system by uninstalling all global cdk modules, deleting the venv, reinstalling CDK == 1.147.0, reinstating the venv and reinstalling cdk modules == 1.147.0 and I still face the same error. Does the project need to be re-initialized completely?

**Comment by goudhabuddha** [comment]
I think I found the problem. It was not package mismanagement. If you create a folder called "constructs" in the root folder of the project (in my case, my_project/constructs) it will somehow interfere with importing constructs._jsii

I had a folder called "constructs" in my root project folder and renamed it to "my_constructs" and the issue is fixed, cdk synth is working as expected.

Can this be classified as a bug? I don't think people should have to worry about a naming conflict between a folder they create in the root level of the application and a module buried in the venv.

**Comment by rix0rrr** [comment]
Unfortunately there's not much we can do about this. 

This may have to do with the layout of your project. If your entire application is in a package, a `constructs` folder inside *that* will not interfere because it will not be considered the top-level package `constructs`.
