### ISSUE TITLE
(aws-eks): Can't enable control plane logging for fargate cluster

### ISSUE THREAD

**Issue by dza89** [aws/aws-cdk#19302]
### What is the problem?

 [This MR](https://github.com/aws/aws-cdk/pull/18112) added the ability to enable control plane logging for eks clusters. This doesn't work for a fargate cluster because the ClusterProps interface is not included in FargateCluster. 

Can I make an MR where I move ClusterLogging to ClusterOptions? Also open to other solutions of course.
I thought I would ask and wait for your input first.

### Reproduction Steps

Try to add 

```ts
const cluster = new eks.FargateCluster(this, 'Cluster', {
  // ...
  version: eks.KubernetesVersion.V1_21,
  clusterLogging: [
    eks.ClusterLoggingTypes.API,
    eks.ClusterLoggingTypes.AUTHENTICATOR,
    eks.ClusterLoggingTypes.SCHEDULER,
  ],
});
```

and see if it works.

### What did you expect to happen?

Enabling logging for fargate clusters would be possible as well

### What actually happened?

Nothing.

### CDK CLI Version

2.14

### Node.js Version

16.13.2

### OS

MacOs

### Language

Typescript

### Language Version

4.6.2

**Comment by otaviomacedo** [comment]
> Can I make an MR where I move ClusterLogging to ClusterOptions? Also open to other solutions of course.
I thought I would ask and wait for your input first.

Sounds good.
