### ISSUE TITLE
FlowLog: add support for `log_format` parameter

### ISSUE THREAD

**Issue by charbyzard** [aws/aws-cdk#19316]
### Description

It would be nice if passing a value for the VPC FlowLog `logFormat` parameter was exposed through the higher-level [FlowLog](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ec2.FlowLog.html) construct. Currently, the only way to use this feature seems to be through the lower level [CfnFlowLog](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ec2.CfnFlowLog.html#logformat-1) construct.

It seems like the L2 construct for FlowLogs was introduced before this feature came out and simply never got updated.

### Use Case

The current default is to use log only the values defined in the `v2` specification, which excludes a lot of useful information (such as the `tcp_flags` parameter, which indicates if a given packet was `SYN/ACK/SYN-ACK/RST/FIN`). The only way to specify a custom log format that includes desirable information is to use the lower level CloudFormation wrapper construct, which is more cumbersome to work with.

### Proposed Solution

Update the [FlowLog](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-ec2.FlowLog.html) module to support the `logFormat` property.

### Other information

Reference documentation: [Logging IP traffic with VPC Flow Logs](https://docs.aws.amazon.com/vpc/latest/userguide/flow-logs.html#flow-logs-fields)

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by corymhall** [comment]
@charbyzard we currently have an open PR to implement this functionality.

https://github.com/aws/aws-cdk/pull/16279

**Comment by xavierbuspatrol** [comment]
@charbyzard I won't have time to work on https://github.com/aws/aws-cdk/pull/16279 for a while so don't hesitate if you want to contribute

**Comment by watany-dev** [comment]
Yes, I will continue to work on this.
