### ISSUE TITLE
(@aws-cdk/core): addDeletionOverride throws .addDeletionOverride is not a function during synthesis

### ISSUE THREAD

**Issue by chrisgray-vertex** [aws/aws-cdk#19310]
### What is the problem?

Within an aspect, I'm attempting to use the escape hatch to remove a DependsOn which is automatically added, but needs to be removed for my use case.  I'm using ```addDeletionOverride('DependsOn')``` which builds fine.  However, during synthesis an error is thrown.  

The error produced is ```TypeError: cfnLaunchConfiguration.addPropertyOverride is not a function```

### Reproduction Steps

Use this aspect from typescript module in a CDK stack that contains an EC2 based ECS cluster.

```
export class LaunchConfigIamRoleAspect implements cdk.IAspect {
  private readonly expression: cdk.ICfnConditionExpression;

  public constructor(expression: cdk.ICfnConditionExpression) {
    this.expression = expression;
  }

  public visit(node: cdk.IConstruct): void {
    const isConditionalType = 'AWS::AutoScaling::LaunchConfiguration';

    if (isConditionalType) {
      const cfnLaunchConfiguration = node as CfnLaunchConfiguration;
      cfnLaunchConfiguration.iamInstanceProfile = this.expression.toString();
      cfnLaunchConfiguration.addDeletionOverride('DependsOn'); //TODO: this should work according to the docs, but it throws an error
    }
  }
}
```

### What did you expect to happen?

The LaunchConfiguration resource should have its DependsOn attribute removed.

### What actually happened?

The error ```TypeError: cfnLaunchConfiguration.addPropertyOverride is not a function``` is produced during synthesis.

### CDK CLI Version

2.11.0

### Node.js Version

v16.14.0

### OS

macOS 12.2

### Language

Typescript

**Comment by peterwoodworth** [comment]
I'm pretty sure by looking at your aspect that there's a minor bug in your code

```ts
if (isConditionalType) {
  ...
```

You will want to check if the node you're visiting is an instance of the conditional type

```ts
if (node instanceof isConditionalType) {
  ...
```

**Comment by chrisgray-vertex** [comment]
Yes, that was it.  :flushed:

Thank you very much.
