### ISSUE TITLE
(ec2): Enable Instance access to CfnNetworkInterface

### ISSUE THREAD

**Issue by stmee** [aws/aws-cdk#19326]
### Description

I would like to be able to access network interface properties from the instance construct.  

### Use Case

I want to add secondary private IP addresses to an instance.

### Proposed Solution

cdk.aws_ec2.InstanceProps have a networkDevices or similar prop to access secondaryPrivateIpAddressCount

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by corymhall** [comment]
I am unassigning and marking this issue as `p2`, which means that we are unable to work on this immediately.

We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://join.slack.com/t/cdk-dev/shared_invite/zt-mso6p56d-qJp7SOTBvMaQuDrx7R2wHg) to solicit support for reprioritization.

**Comment by victoravr** [comment]
yes, please allow to add secondary private IP addresses to an instance via CDK

**Comment by adminy** [comment]
+1
