### ISSUE TITLE
(ecr-assets): DockerImageAsset remote build

### ISSUE THREAD

**Issue by Nintorac** [aws/aws-cdk#19339]
### Description

Allow for remote building of docker images

### Use Case

My internet is slow and I'm trying to build a large image (tensorflow-gpu image ~4gb), 8gb total for down and up ends up taking quite a long time while the context is only around 100mb

### Proposed Solution

```
const asset = new DockerImageAsset(this, 'MyBuildImage', {
  directory: path.join(__dirname, 'my-image'),
  remote_build: true,
  networkMode: NetworkMode.HOST,
})
```

When `remote_build` is true the docker context from the path is archived and uploaded to s3, a lambda is then initiated that runs the build and pushes the image from within the cloud.

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by madeline-k** [comment]
Thanks for opening this feature request, @Nintorac. This is a really cool idea! I am triaging it as p2, which means we realistically will not be getting to implement this anytime soon. But, we always welcome PRs! Checkout the [contributing guide](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) to get started. 

Also, have you considered synthesizing and deploying your CDK apps from a remote environment? You could use [CDK Pipelines](https://aws.amazon.com/blogs/developer/cdk-pipelines-continuous-delivery-for-aws-cdk-applications/), [CodePipeline](https://docs.aws.amazon.com/cdk/api/v1/docs/aws-codepipeline-readme.html) or [CodeBuild](https://docs.aws.amazon.com/cdk/api/v1/docs/aws-codebuild-readme.html).

**Comment by misteliy** [comment]
I think this would be beneficial for us as well. We are having our CI/CD pipeline in gitlab but it would be nice to “offload” the container creation to AWS natively without the need to switch to codepipeline…

**Comment by Rizxcviii** [comment]
There is currently a construct [here](https://github.com/AlexTech314/TokenInjectableDockerBuilder) that handles this, it does seem to be somewhat restricting on some stuff, but it's trying to get the work done, nonetheless
