### ISSUE TITLE
(aws-codepipeline): Artifacts in parameter overrides are not providing correct values.

### ISSUE THREAD

**Issue by FaresKi** [aws/aws-cdk#19348]
### General Issue

 Trying to pass CodeBuild Artifacts as parameters to my cross-account deployment action.

### The Question

Hi,
I'm currently deploying cross-account stacks, and one of my resources (a REST API Gateway) requires an API definition that I have stored in a CodeBuild artifact, from the Build stage.
However, when I look at the ParameterOverrides, all work but apiBucketName and apiBucketKey.
I'm using CDK and this is the relevant code snippet:
```ts
const lambdaLayer = new Artifact("LayerArtifact")
const openAPI = new Artifact("OpenAPIArtifact")
const cdkBuildOutput = new Artifact("CdkBuildOutput")
...
const businessAssetAPIStackDeployAction = new CloudFormationCreateUpdateStackAction({
      runOrder: 2,
      actionName: "Deploy-NonProd-BusinessAPI",
      templatePath: cdkBuildOutput.atPath("BusinessAssetAPIStack.template.json"),
      stackName: "BusinessAPIStack",
      adminPermissions: true,
      parameterOverrides: {
        ...props.apiStack.lambdaCode.assign(lambdaBuildOutput.s3Location), // this works
        ...props.apiStack.layerCode.assign(lambdaLayer.s3Location), // this works
        "apiBucketName": openAPI.bucketName, // this doesn't
        "apiBucketKey": openAPI.objectKey // this neither
      },
      deploymentRole: nonProdDeploymentRole,
      role: nonProdCrossAccountRole,
      extraInputs: [lambdaBuildOutput, lambdaLayer],
    })
```
The error I get is the following:
```
Action execution failed
Cannot find input artifact OpenAPIArtifact
```
The main issue, I believe, is that the value isn't being passed, and I don't know why.
Am I missing something?
Thanks in advance,
Fares

### CDK CLI Version

1.140.0

### Framework Version

N/A

### Node.js Version

v14.17.6

### OS

MacOS 11.6

### Language

Typescript

### Other information

When I check the synthed template thru CDK, I notice that for the parameter overrides that pass thru the "`props.<stackName>.<prop>.assign`" logic, there's a token that's provided, however, for simple "overrides", only the Artifact name is passed.

**Comment by skinny85** [comment]
> Turns out I had forgotten to provide `openAPI` in the `extraInputs` field.

Yep 🙂.
