### ISSUE TITLE
lambda: Missing dotnet 6 runtime

### ISSUE THREAD

**Issue by wjax** [aws/aws-cdk#19344]
### General Issue

Missing dotnet 6 runtime in lambda

### The Question

Lambda already supports net6 both in image and zip format, however, when creating a lambda function in cdk, net6 runtime is missing

### CDK CLI Version

2.15.0

### Framework Version

2.15.0

### Node.js Version

16.13.2

### OS

Windows

### Language

.NET

### Language Version

All

**Comment by peterwoodworth** [comment]
This feature was merged in earlier today. Expect it to be part of the next release 🙂 

https://github.com/aws/aws-cdk/pull/19144
