### ISSUE TITLE
(aws-ec2): Ability to enable "Detailed Monitoring" for EC2 instance

### ISSUE THREAD

**Issue by Dzhuneyt** [aws/aws-cdk#19346]
### Description

The current ec2.Instance() construct does not expose the "monitoring" prop that the underlying CfnInstance does.

### Use Case

I want to create EC2 instances with Detailed Monitoring enabled.

### Proposed Solution

```typescript
new ec2.Instance(this, 'Instance', {
   ...
   monitoring: true|false,
   ...
});
```

### Other information

https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-ec2/lib/instance.ts#L371

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by corymhall** [comment]
I am unassigning and marking this issue as `p2`, which means that we are unable to work on this immediately, but contributions are definitely welcome.

We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://join.slack.com/t/cdk-dev/shared_invite/zt-mso6p56d-qJp7SOTBvMaQuDrx7R2wHg) to solicit support for reprioritization.

**Comment by Dzhuneyt** [comment]
@corymhall I've tried to solve this with the above PR. Let me know if you have any concerns.
