### ISSUE TITLE
aws-cdk: Session expiration is not handled gracefully

### ISSUE THREAD

**Issue by jonathanmorley** [aws/aws-cdk#19359]
### What is the problem?

During a deployment, the AWS session could expire. Subsequent API calls from the CLI would fail and cause errors.

This is primarily a problem for:
1. Long deployments
2. Deployments using role chaining (e.g. from a general deployer role to the CDK Deployment Role from the bootstrap stack)

However, a user could set their session duration to a very low value and be affected by average length deployments

While CloudFormation deploys will continue in the background, this still causes issues in the following areas (at least):
1. We cant reliably chain things after `cdk deploy`
2. The deployment status may be red even in a good deploy
3. Missing logs
4. Failure to deploy dependent stacks

### Reproduction Steps

Run `cdk deploy` against a template that takes longer to deploy than the session duration

### What did you expect to happen?

The command should complete successfully

### What actually happened?

The command will fail

### CDK CLI Version

1.137.0

### Node.js Version

14.18.2

### OS

macos 12.2

### Language

Typescript

### Other information

This is currently theoretical, and has not been verified by me.

See https://cdk-dev.slack.com/archives/C018XT6REKT/p1647029832626189 for a discussion in slack

This may also be a problem for asset uploads

**Comment by jonathanmorley** [comment]
We should generally handle credential expiry, and if necessary, re-assume the role

**Comment by rix0rrr** [comment]
Please show me an example how to configure AssumeRole credentials (in `~/.aws/config`) where the roles aren't automatically re-assumed.
