### ISSUE TITLE
AwsCustomResource: automatic policy fails if API call name is different from IAM name

### ISSUE THREAD

**Issue by caojoshua** [aws/aws-cdk#19355]
### What is the problem?

By default, `AwsCustomResource` sdk calls for `(get|put)BucketLifecycleConfiguration` grants the executor role `s3:(Get|Put)BucketLifecycleConfiguration`. The correct permissions should be `s3:(get|put)LifecycleConfiguration` permissions (notice the lack of `Bucket`). I believe that the error is from [this code](https://github.com/aws/aws-cdk/blame/69a50f10eb74370d00a3b4c850cfd42e5dc391e5/packages/%40aws-cdk/custom-resources/lib/aws-custom-resource/aws-custom-resource.ts#L509).

### Reproduction Steps

```ts
new AwsCustomResource(this, physicalId, {                                    
            policy: AwsCustomResourcePolicy.fromSdkCalls({ resources: AwsCustomResourcePolicy.ANY_RESOURCE }),
            onUpdate: {
                service: 'S3',
                action: '(get|put)BucketLifecycleConfiguration',
                parameters: {
                    ...
                },
                physicalResourceId: PhysicalResourceId.of(physicalId),
            },
});
```

This custom resource will get a `AccessDenied` response. As a workaround, we can specify a policy that explicitly gives the correct permissions `(get|put)LifecycleConfiguration`.

```ts
policy: AwsCustomResourcePolicy.fromStatements([
              new iam.PolicyStatement({
                sid: 'foo',
                effect: iam.Effect.ALLOW,
                actions: ['s3:(Get|Put)LifecycleConfiguration'],
                resources: ['bar'],
              }),
            ]),
```

### What did you expect to happen?

SDK calls should work as normal.

### What actually happened?

Access Denied response.

### CDK CLI Version

1.145.0

### Node.js Version

v14.19.0

### OS

Amazon Linux

### Language

Typescript

**Comment by rix0rrr** [comment]
p2 as this issue has a workaround: provide the policy statement yourself (in this case, automatically deriving the IAM policy from the calls does not work)

**Comment by rix0rrr** [comment]
The only way to fix this is to build an inventory of API calls and their deviating IAM policy names. Unlikely to be picked up by us anytime soon.
