### ISSUE TITLE
(aws-cdk-lib): ReadMe Overview contains example using (removed) ConcreteDependable

### ISSUE THREAD

**Issue by cameroncf** [aws/aws-cdk#19352]
### link to reference doc page

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib-readme.html#construct-dependenciesme.html

### Describe your issue?

[Dependencies > Construct Dependencies](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib-readme.html#construct-dependencies)

The example here uses `ConcreteDependable`, which no longer exists in CDK v2. This example should be updated to use `DependencyGroup ` instead.

More in #18095

**Comment by madeline-k** [comment]
Thanks for raising this inaccuracy in the docs @cameroncf!
