### ISSUE TITLE
(aws-dms): How to get ARNs from Cfn Resources?

### ISSUE THREAD

**Issue by alexandervandekleutab** [aws/aws-cdk#19360]
### General Issue

To create a complete DMS system (endpoints, replication instance, and task) you need to pass ARNs between CfnResources that don't export them.

### The Question

I want to create a DMS to migrate my DocumentDB database to S3 for further processing and easier accessibility. I want to use CDK to create the necessary DMS resources. Below is a snippet from my current approach:

```typescript

    const documentDbEndpoint = new dms.CfnEndpoint(
      this,
      generateName('document-db-endpoint'),
      {
        endpointType: 'source',
        engineName: 'docdb',
        certificateArn: <certificatArn>,
        databaseName: '<name>',
        endpointIdentifier: generateName('document-db-endpoint'),
        username: <username>,
        password: <password>,
        port: 27017,
        serverName: <serverName>,
        sslMode: 'verify-full',
      }
    )

    // Target

    const migrationBucketAccessRole = new iam.Role(
      this,
      generateName('migration-bucket-access-role'),
      {
        assumedBy: new iam.ServicePrincipal('dms.amazonaws.com'),
        managedPolicies: [
          iam.ManagedPolicy.fromAwsManagedPolicyName('AmazonS3FullAccess'),
        ],
      }
    )

    const s3Endpoint = new dms.CfnEndpoint(this, generateName('s3-endpoint'), {
      endpointType: 'target',
      engineName: 's3',
      endpointIdentifier: generateName('s3-endpoint'),
      s3Settings: {
        bucketName: generateName('migration-bucket'),
        dataFormat: 'csv',
        encryptionMode: 'SSE_S3',
        serviceAccessRoleArn: migrationBucketAccessRole.roleArn,
      },
    })

    // replication instance
    const replicationInstance = new dms.CfnReplicationInstance(
      this,
      generateName('replication-instance'),
      {
        replicationInstanceClass: 'dms.c4.large',
        replicationInstanceIdentifier: generateName('replication-instance'),
        replicationSubnetGroupIdentifier: generateName(
          'replication-subnet-group'
        ),
      }
    )

    // replication task
    const replicationTask = new dms.CfnReplicationTask(
      this,
      generateName('replication-task'),
      {
        migrationType: 'full-load',
        replicationInstanceArn: `arn:aws:dsm:${this.region}:${this.account}:rep:${replicationInstance.replicationInstanceIdentifier}`,
        sourceEndpointArn: `arn:aws:dms:${this.region}:${this.account}:endpoint:${documentDbEndpoint.endpointIdentifier}`,
        targetEndpointArn: `arn:aws:dms:${this.region}:${this.account}:endpoint:${s3Endpoint.endpointIdentifier}`,
        tableMappings: JSON.stringify({
          rules: [
            {
              'rule-type': 'selection',
              'rule-id': '031493139',
              'rule-name': '031493139',
              'object-locator': {
                'schema-name': '%',
                'table-name': '%',
              },
              'rule-action': 'include',
              filters: [],
            },
          ],
        }),
      }
    )
```

The issue is that the `CfnReplicationTask` requires the `replicationInstanceArn`, `sourceEndpointArn` and `targetEndpointArn`. Since those resources are Cfn resources, they do not expose an ARN attribute. I have tried constructing it manually, but the `endpointIdentifier` is just the name I specify when I create it above, and the `resourceIdentifier` is `undefined.` I've also tried `getAtt('Arn')` which doesn't work either.

Is there any way to accomplish this? Or do I have to deploy the endpoints and replication instance resources in one stack and then manually copy their ARNs back into another stack containing the replication task?

### CDK CLI Version

1.144.0

### Framework Version

1.144.0

### Node.js Version

14.17

### OS

macOs

### Language

Typescript

**Comment by peterwoodworth** [comment]
Our CfnResources are exactly the CloudFormation resources described on CloudFormation's docs.

[ReplicationInstance](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-replicationinstance.html#aws-resource-dms-replicationinstance-return-values) and [Endpoint](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-endpoint.html#aws-resource-dms-endpoint-return-values) return their arn with their Ref function.

In the CDK you can reference the Ref function of CfnResources with the [Ref](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-dms.CfnReplicationInstance.html#ref) property
