### ISSUE TITLE
(security groups, load balancer): Auto add allow-all inbound rule to SG when add a listener to LB

### ISSUE THREAD

**Issue by lioaslan** [aws/aws-cdk#19377]
### What is the problem?

I created an ALB with a security group that just allows access from Cloudfront (I use AWS managed prefix-list `com.amazonaws.global.cloudfront.origin-facing`) and add a listener that forward to a target group. However, after creating the stack, the security group show 2 inbound rules
- Port 80 from `0.0.0.0`
- Port 80 from `pl-31a34658`  (`com.amazonaws.global.cloudfront.origin-facing`)

I tried removing the add-listener section and the security group have only 1 inbound rule: Port 80 from `pl-31a34658`  

### Reproduction Steps

Code: 
```typescript
const STACK_NAME = 'TestAwsManagedPL';

// =============VPC===============
const vpc = aws_ec2.Vpc.fromLookup(this, 'Default', {
  vpcId: 'vpc-21d8cd46',
  isDefault: true
});

//===============Load Blancer===============

const targetGroup = new aws_elasticloadbalancingv2.ApplicationTargetGroup(
  this,
  `${STACK_NAME}TG`,
  {
    vpc,
    port: 80,
    protocol: aws_elasticloadbalancingv2.ApplicationProtocol.HTTP,
    targetType: aws_elasticloadbalancingv2.TargetType.IP
  }
);

const subnets = ['subnet-d9b34abf', 'subnet-de0de396', 'subnet-e33683ba'];

const lbSecurityGroup = new aws_ec2.SecurityGroup(
  this,
  `${STACK_NAME}LBSG`,
  { vpc }
);

const cloudfrontPl = 'pl-31a34658';
lbSecurityGroup.addIngressRule(Peer.prefixList(cloudfrontPl), Port.tcp(80));

const lb = new aws_elasticloadbalancingv2.ApplicationLoadBalancer(
  this,
  `${STACK_NAME}LB`,
  {
    vpc,
    vpcSubnets: {
      subnets: subnets.map((subnet) =>
        aws_ec2.Subnet.fromSubnetId(this, subnet, subnet)
      )
    },
    securityGroup: lbSecurityGroup,
    internetFacing: true
  }
);

const listener = lb.addListener('listener', {
  port: 80,
  defaultAction: ListenerAction.forward([targetGroup])
});
```

### What did you expect to happen?

The security group doesn't have the inbound rule with source from `0.0.0.0`

### What actually happened?

 Tthe security group show 2 inbound rules
- Port 80 from `0.0.0.0`
- Port 80 from `pl-31a34658`  (`com.amazonaws.global.cloudfront.origin-facing`)

### CDK CLI Version

2.15.0 (build 151055e)

### Node.js Version

v12.22.8

### OS

Linux Mint 20.1

### Language

Typescript

**Comment by corymhall** [comment]
@lioaslan you should be able to control this via the [open](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationListener.html#open) parameter on the `ApplicationListener`. This is `true` by default when the load balancer is public facing which adds the `0.0.0.0/0` rule to the security group.

**Comment by lioaslan** [comment]
Thanks
