### ISSUE TITLE
(awscdkapigatewayv2alpha): CfnRoute equivalent missing in CDK v2

### ISSUE THREAD

**Issue by fynnfluegge** [aws/aws-cdk#19370]
### General Issue

CfnRoute equivalent with target parameter is missing.

### The Question

I am trying to migrate a CDK construct consisting of a HttpApi with an Eventbridge to CDK v2 as I did here:
[https://github.com/fynnfluegge/aws-serverless-cdk-go-templates/blob/main/httpapi-eventbridge/http-api-eventbridge.go](https://github.com/fynnfluegge/aws-serverless-cdk-go-templates/blob/main/httpapi-eventbridge/http-api-eventbridge.go)
```
awsapigatewayv2.NewCfnRoute(stack, jsii.String("myEventRoute"), &awsapigatewayv2.CfnRouteProps{
		ApiId:    httpApi.HttpApiId(),
		RouteKey: jsii.String("POST /"),
		Target:   jsii.String("integrations/" + *eventbridgeIntegration.Ref()),
	})
```

I searched through the documentation but cannot find a solution how to integrate the Eventbridge into a http Route of the HttpApi or a substitute for CfnRoute.

### CDK CLI Version

2.14.0

### OS

Mac OS

### Language

Go

**Comment by peterwoodworth** [comment]
This is called out at the top of our [migrating to v2 devguide](https://docs.aws.amazon.com/cdk/v2/guide/migrating-v2.html)

**Comment by fynnfluegge** [comment]
Thank you very much, I'm fine now! ​🙏​
