### ISSUE TITLE
(nested-stack): impossible to manually set Nested Stack Name

### ISSUE THREAD

**Issue by amir-faliam** [aws/aws-cdk#19371]
### Description

I want to be able to manually set the name of a NestedStack but currently there is no way to do so.

### Use Case

I'm migrating my infrastructure from Amplify over to CDK and my strategy for refactoring the management of the resources is to maintain the stack/resource names when I recreate them in CDK. 

All of the other resources (i.e. root stack,  Cognito, Dynamodb, etc) haven't been an issue, but nested stack seems to be the only thing we can't manually set the name on.

It seems weird that we can define stack names for root stack but not for nested stacks. 

### Proposed Solution

introduce stack name as a parameter for NestedStackProps similar to how it's done for normal Cloudformation Stacks

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by rix0rrr** [comment]
It does not seem to be possible:

![image](https://user-images.githubusercontent.com/524162/162206044-98edb06c-ba58-4157-9828-2b5b93b9e8b4.png)

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-stack.html

**Comment by flyingImer** [comment]
@rix0rrr 
the nested stack name is auto generated from its logical id by CFN, currently the logical id is authored by CDK in the format of `<nested-stack-id>NestedStack<nested-stack-id>NestedStackResources`, which is not that readable, I feel

it would be great to let CDK user to provide the logical id, which may be close to the request

**Comment by gavihs** [comment]
@amir-faliam - not sure if you have fixed this challenge

CDK provides a wonderful interface called IAspect; this helps in renaming resources
In general a nested stack will have the prefix of the parent stack that functionality cannot be changed - this is inherent in cloudformation 

however your specific challenge of "NestedStack" and "Resource" can be eliminated

I have a code for Python
```

import logging
import jsii
from constructs import Construct, IConstruct

from aws_cdk import (
    IAspect,
    CfnResource,
)

logger = logging.getLogger()

@jsii.implements(IAspect)
class MyAspect:

    def visit(self, node: IConstruct ):
        # print("Visited:", node.node.path)
        if isinstance(node, CfnResource):
            if node.cfn_resource_type == "AWS::CloudFormation::Stack":
                orig_name = node.stack.resolve(node.logical_id)
                new_name = orig_name.split("NestedStack")[0]
                logger.info("stack name => {s}, New Name => {n}".format(n=new_name, s=orig_name))
                node.override_logical_id(new_name)

```

Once you have this Interface defined

To the main stack code you add aspects

`
rename_nested_stackname = MyAspect()
Aspects.of(<mainStack>).add(rename_nested_stackname
`
