### ISSUE TITLE
(aws-ecs): stuck on creating Ec2Service

### ISSUE THREAD

**Issue by anwarjaved** [aws/aws-cdk#19379]
### What is the problem?

I am trying to create ECS Service and point Application Balancer to it but it just stuck on creating Ec2Service

```ts
const cluster = new Cluster(this, `TestCluster`, {
        vpc: vpc,
        clusterName: `TestCluster`,
    });
    // Add capacity to it
    const autoScalingGroup = new AutoScalingGroup(this, 'ASG', {
        vpc,
        instanceType: new InstanceType('t2.micro'),
        machineImage: EcsOptimizedImage.amazonLinux2(),
        minCapacity: 1,
        maxCapacity: 2,
      });
    const capacityProvider = new AsgCapacityProvider(this, 'AsgCapacityProvider', {
        autoScalingGroup,
      });
     const dockerFile = `./build/auth/`;
     const dockerImageAsset = new DockerImageAsset(stackRef, `authDockerImage`, {
    directory: dockerFile,
});

   // create task defination
    const taskDefinition = new Ec2TaskDefinition(stackRef, `authTaskDefination`, {
    networkMode: NetworkMode.AWS_VPC
});

//add container
const container = taskDefinition.addContainer('AuthContainer', {
    image: ContainerImage.fromDockerImageAsset(dockerImageAsset),
    memoryLimitMiB: 512,
    
    logging: LogDrivers.awsLogs({
        streamPrefix: `authService`,
        logRetention: RetentionDays.ONE_DAY
    }),
    containerName: `auth`,
    portMappings: [{
        containerPort: 80
    }],

});

//create taskService
const service =new Ec2Service(stackRef, `${taskName}TaskService`, {
    cluster: cluster,
    taskDefinition: taskDefinition
});
```

### Reproduction Steps

run  cdk deploy command with above code.

### What did you expect to happen?

I expect a cluster to be created with a service with 2 load balancer one is private and another public. 

### What actually happened?

It stuck on creating EC2 service. It seems it container task never got deployed on ec2 container.

### CDK CLI Version

2.16.0 (build 4c77925)

### Framework Version

Typescript Version 4.6.2

### Node.js Version

v14.17.5

### OS

Windows

### Language

Typescript

### Language Version

Typescript(4.6.2)

**Comment by ryparker** [comment]
Hey @anwarjaved 👋🏻  Thanks for opening an issue.

Have you checked for failures in the ECS task logs? The Dockerfile you're referencing may not be reaching a healthy status this can cause your ECS deployment to timeout. If you open ECS in the AWS console you should be able to navigate to the cluster that's deploying and see it's tasks/logs.

**Comment by anwarjaved** [comment]
Its was memory releated issue after changes it deployed successfully

**Comment by ddutka-creatision** [comment]
For me it was the health status codes. 

It was checke `/` path and it was returning `401` which was not in the list of accepted healthy statuses . 

This is why it never finished.
