### ISSUE TITLE
(eks): EKS tags do not update if edited after initial deploy

### ISSUE THREAD

**Issue by NGL321** [aws/aws-cdk#19388]
### What is the problem?

When attempting to add tags to an already-deployed EKS cluster, tags never get added to resource. There is no issue when adding tags in the initial resource creation, so this can be worked around by either destroying and redeploying the stack, or by adding tags using the AWS SDKs.

This is likely related to the [fix](https://github.com/aws/aws-cdk/pull/18109) for the previously reported [issue](https://github.com/aws/aws-cdk/issues/4995).

### Reproduction Steps

1. Deploy below resource 
```typescript
const cluster = new eks.Cluster(this, 'eks3', {
    defaultCapacity: 0,
    version: eks.KubernetesVersion.V1_21,
    vpc,
    //tags: {
    //    "test": "123"
    //}
});
```

2. Remove comment of `tags` then redeploy

### What did you expect to happen?

Tags that were not created for first deployment should have been created in the update.

### What actually happened?

No tags were added to Cluster resource.

### CDK CLI Version

2.16.0

### Framework Version

2.16.0

### Node.js Version

16.9.1

### OS

OSX Sierra

### Language

Typescript

### Other information

Best current workaround is to add tags via the [SDK `tagResource()`](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/EKS.html#tagResource-property) property, but this does not exist within the CDK, so is unideal.

_Reported internally in ticket P59680747_

**Comment by spksoft** [comment]
My team and I got this issue too ☹️

**Comment by diranged** [comment]
Chiming in - this has been open for a while and is an outstanding issue. Can someone prioritize fixing this?

**Comment by shcherbak** [comment]
No Assignees for more then a year?

**Comment by jtdroste** [comment]
The issue seems to be here: https://github.com/aws/aws-cdk/blob/v2.99.1/packages/aws-cdk-lib/aws-eks/lib/cluster-resource-handler/cluster.ts#L317

Mainly around `analyzeUpdate` not identifying a change in the tags, resulting in a update not processing.

**Comment by cablekevin** [comment]
Any updates on this issue? It's been almost 2 years now.
