### ISSUE TITLE
(codedeploy): Incorrect codedeploy service principal for isolated regions

### ISSUE THREAD

**Issue by mattphan8264** [aws/aws-cdk#19399]
### General Issue

Incorrect CodeDeploy service principal for isolated regions (`us-iso-east-1` and `us-isob-east-1`).

### The Question

Code deploy service role is being set to `codedeploy.us-isob-east-1.amazonaws.com` and `codedeploy.us-iso-east-1.amazonaws.com` for LCK and DCA regions.

It should be `codedeploy.amazonaws.com`.

Output we are getting:

```json
    "ApiLambdaCodeDeployDeploymentDeploymentGroupServiceRole45D217E3": {
      "Type": "AWS::IAM::Role",
      "Properties": {
        "AssumeRolePolicyDocument": {
          "Statement": [
            {
              "Action": "sts:AssumeRole",
              "Effect": "Allow",
              "Principal": {
                "Service": "codedeploy.us-isob-east-1.amazonaws.com"
              }
            }
          ],
          "Version": "2012-10-17"
        },
        "ManagedPolicyArns": [
          {
            "Fn::Join": [
              "",
              [
                "arn:",
                {
                  "Ref": "AWS::Partition"
                },
                ":iam::aws:policy/service-role/AWSCodeDeployRoleForLambdaLimited"
              ]
            ]
          }
        ]
      },
      "Metadata": {
        "aws:cdk:path": "GammaLCK/ApiLambda/CodeDeployDeployment/DeploymentGroup/ServiceRole/Resource"
      }
    },
```

### CDK CLI Version

2.10.0 (build e5b301f)

### Language

Typescript

**Comment by peterwoodworth** [comment]
The convention for standard regions seems to have the region included - if this isn't true for LCK/DCA regions then you can work around this with [escape hatches](https://docs.aws.amazon.com/cdk/v2/guide/cfn_layer.html) to override the `service` property set by CDK

```ts
    const ldg = new LambdaDeploymentGroup(this, 'LDG', {
      alias,
    })

    const cfnRole = ldg.role.node.defaultChild as CfnRole;
    cfnRole.addPropertyOverride('AssumeRolePolicyDocument.Statement.0.Principal.Service', 'codedeploy.amazonaws.com')
```

**Comment by peterwoodworth** [comment]
Ping me if you have any more concerns

**Comment by peterwoodworth** [comment]
@skinny85 I have nothing against that! I'm curious if there's any precedent for doing something like this - I can't say I've seen any piece of code ever take restricted regions into consideration

**Comment by rix0rrr** [comment]
This where the magic happens:

https://github.com/aws/aws-cdk/blob/9541de7c7beb61914c6883de0640d7664b2c8327/packages/%40aws-cdk/region-info/lib/default.ts#L37

It's hard though. Too many `if`s on the dance floor...

**Comment by skinny85** [comment]
> This where the magic happens:
> 
> https://github.com/aws/aws-cdk/blob/9541de7c7beb61914c6883de0640d7664b2c8327/packages/%40aws-cdk/region-info/lib/default.ts#L37
> 
> It's hard though. Too many `if`s on the dance floor...

Thanks @rix0rrr! Super helpful. I was able to submit https://github.com/aws/aws-cdk/pull/19729 thanks to your tip.
