### ISSUE TITLE
(core): CDK 2.16 Cross stack output removed regardless of stackRelativeExports flag setting

### ISSUE THREAD

**Issue by rcollette** [aws/aws-cdk#19396]
### What is the problem?

Stack A creates an IAM user, assigns an access key to the user and provides the AccessKey as a property of the Stack. 

Stack B creates a Fargate task with environment variables set to the AccessKey.ref and AccessKey.secretAccessKey that were created in Stack A.

Pre CDK2, the appropriate outputs and references would be created in the CloudFormation templates.  Post CDK 2 upgrade, the outputs are being removed as well as the references.

### Reproduction Steps

Full cdk application examples are located here:
https://github.com/rcollette/CDK1-Outputs-Issue-SCCE
https://github.com/rcollette/CDK2-Outputs-Issue-SCCE

Output templates are attached.
[CDK1Templates.zip](https://github.com/aws/aws-cdk/files/8248810/CDK1Templates.zip)
[cdk2templates.zip](https://github.com/aws/aws-cdk/files/8248815/cdk2templates.zip)

### What did you expect to happen?

An output should be created for the accessKey in Stack A and the output should be referenced in Stack B

### What actually happened?

CDK is removing the outputs and references that were present in CDK 1.x

```shell
Stack pdx-PdxApi-users-dev
Parameters
[+] Parameter BootstrapVersion BootstrapVersion: {"Type":"AWS::SSM::Parameter::Value<String>","Default":"/cdk-bootstrap/hnb659fds/version","Description":"Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]"}

Outputs
[-] Output ExportsOutputRefDeliveriesSignerAccessKey4F197D7B: {"Value":{"Ref":"DeliveriesSignerAccessKey"},"Export":{"Name":"pdx-PdxApi-users-dev:ExportsOutputRefDeliveriesSignerAccessKey4F197D7B"}}
[-] Output ExportsOutputFnGetAttDeliveriesSignerAccessKeySecretAccessKey55F19EC7: {"Value":{"Fn::GetAtt":["DeliveriesSignerAccessKey","SecretAccessKey"]},"Export":{"Name":"pdx-PdxApi-users-dev:ExportsOutputFnGetAttDeliveriesSignerAccessKeySecretAccessKey55F19EC7"}}


Stack pdx-PdxApi-dev
IAM Statement Changes
┌───┬────────────────────────┬────────┬────────────────┬─────────────────────────────────┬───────────┐
│   │ Resource               │ Effect │ Action         │ Principal                       │ Condition │
├───┼────────────────────────┼────────┼────────────────┼─────────────────────────────────┼───────────┤
│ + │ ${PdxApi-TaskRole.Arn} │ Allow  │ sts:AssumeRole │ Service:ecs-tasks.amazonaws.com │           │
└───┴────────────────────────┴────────┴────────────────┴─────────────────────────────────┴───────────┘
(NOTE: There may be security-related changes not in this list. See https://github.com/aws/aws-cdk/issues/1299)

Parameters
[+] Parameter BootstrapVersion BootstrapVersion: {"Type":"AWS::SSM::Parameter::Value<String>","Default":"/cdk-bootstrap/hnb659fds/version","Description":"Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]"}

Resources
[-] AWS::IAM::Role TaskRole30FC0FBB destroy
[+] AWS::IAM::Role PdxApi-TaskRole PdxApiTaskRole3B6A8344 
[~] AWS::ElasticLoadBalancingV2::TargetGroup PdxApiLB/PublicListener/ECSGroup PdxApiLBPublicListenerECSGroup2F538E86 
 └─ [+] TargetGroupAttributes
     └─ [{"Key":"stickiness.enabled","Value":"false"}]
[~] AWS::ECS::TaskDefinition PdxApi/TaskDef PdxApiTaskDef6E809282 replace
 ├─ [~] ContainerDefinitions (requires replacement)
 │   └─ @@ -147,18 +147,6 @@
 │      [ ]         ]
 │      [ ]       ]
 │      [ ]     }
 │      [-]   },
 │      [-]   {
 │      [-]     "Name": "DeliveriesBucketConfiguration__SignerAccessKey",
 │      [-]     "Value": {
 │      [-]       "Fn::ImportValue": "pdx-PdxApi-users-dev:ExportsOutputRefDeliveriesSignerAccessKey4F197D7B"
 │      [-]     }
 │      [-]   },
 │      [-]   {
 │      [-]     "Name": "DeliveriesBucketConfiguration__SignerSecretAccessKey",
 │      [-]     "Value": {
 │      [-]       "Fn::ImportValue": "pdx-PdxApi-users-dev:ExportsOutputFnGetAttDeliveriesSignerAccessKeySecretAccessKey55F19EC7"
 │      [-]     }
 │      [ ]   }
 │      [ ] ],
 │      [ ] "Essential": true,
 └─ [~] TaskRoleArn (requires replacement)
     └─ [~] .Fn::GetAtt:
         └─ @@ -1,4 +1,4 @@
            [ ] [
            [-]   "TaskRole30FC0FBB",
            [+]   "PdxApiTaskRole3B6A8344",
            [ ]   "Arn"
            [ ] ]

```

### CDK CLI Version

2.16.0 (build 4c77925)

### Framework Version

2.15

### Node.js Version

16.14.0

### OS

macOS 12.1

### Language

Typescript

### Language Version

4.6.2

### Other information

The pre-upgrade CDK version is 1.106.1

**Comment by rcollette** [comment]
At the moment it seems my only workaround is to add a protected method in the base class, which is called before stack constructs are created, enabling the inheriting class to augment stack properties before they are utilized.

I don't recall seeing any major release number documentation that discussed a breaking change that would make these configuration properties immutable.  Unfortunately this impacts every fargate stack in my environment.

An example of the workaround is in this diff.
https://github.com/rcollette/CDK2-Outputs-Issue-SCCE/compare/85ff8d19669e1a1e3db5cf2cc8e348158573cfed...45a7388248073f912d019c558b97d2ec249be60d

And branch
https://github.com/rcollette/CDK2-Outputs-Issue-SCCE/tree/immutable_stack_configuration_workaround

**Comment by gshpychka** [comment]
I don't see how this could have worked, since you're modifying the property after it's passed to the service. But I don't know TS enough to be sure.

**Comment by rix0rrr** [comment]
As @gshpychka said, I don't understand why this works in V1, but I generally wouldn't rely on the mutability of data structures being reflected in the output.

Either do this:

```ts
export class FargateStack extends FargateStackBase<IFargateStackProps> {
  constructor(scope: Construct, id: string, fargateStackProps: IFargateStackProps) {
    super(scope, id, {
      ...fargateStackProps,
      environment: {
        ...fargateStackProps.environment,
        DeliveriesBucketConfiguration__SignerAccessKey: fargateStackProps.signerAccessKey.ref,
        DeliveriesBucketConfiguration__SignerSecretAccessKey: fargateStackProps.signerAccessKey.attrSecretAccessKey
      },
    });
  }
}
```

Or use methods to apply after-the-fact mutation:

```ts
export class FargateStack extends FargateStackBase<IFargateStackProps> {
  constructor(scope: Construct, id: string, fargateStackProps: IFargateStackProps) {
    super(scope, id, fargateStackProps);

    const container = this.loadBalancedFargateService.taskDefinition.defaultContainer;
    container?.addEnvironment('DeliveriesBucketConfiguration__SignerAccessKey', fargateStackProps.signerAccessKey.ref);
    container?.addEnvironment('DeliveriesBucketConfiguration__SignerSecretAccessKey', fargateStackProps.signerAccessKey.attrSecretAccessKey);
  }
}
```

**Comment by rcollette** [comment]
@rix0rrr - Shouldn't a new behavior such as this be documented in the breaking changes log at the very least?

**Comment by gshpychka** [comment]
> @rix0rrr - Shouldn't a new behavior such as this be documented in the breaking changes log at the very least?

I believe the answer here is "no", because if it worked, it was by accident. This was never documented behaviour.
