### ISSUE TITLE
AppSync: CDK Lambda Authorizer is not set 

### ISSUE THREAD

**Issue by samasama** [aws/aws-cdk#19391]
### What is the problem?

I have a cdk stack with `GraphqlApi` using a lambda authorizer. Though the `lambdaAuthorizerConfig` has `handler` set to the authorizer function, after synthesis and the authorizer function is set but no permission is added to the lambda so that AppSync can execute it

### Reproduction Steps

```ts
const api = new GraphqlApi(this, apiId, {
      name: `${getStackId(this)}-${apiId}`,
      schema: Schema.fromAsset(path.join(__dirname, '../graphql/call-monitoring-schema.graphql')),
      authorizationConfig: {
        defaultAuthorization: {
          authorizationType: AuthorizationType.LAMBDA,
          lambdaAuthorizerConfig: {
            handler: this.authorizerFunction
          }
        },
        additionalAuthorizationModes: [{
          authorizationType: AuthorizationType.IAM
        }]
      },
      xrayEnabled: true,
      logConfig: {
        fieldLogLevel: FieldLogLevel.ALL
      }
    })
```

### What did you expect to happen?

Expect the authorizer function to be set as the authorizer and permission is added to the lambda for AppSync

### What actually happened?

The authorizer function is set  but the permission is not set for AppSync

### CDK CLI Version

1.148.0

### Node.js Version

14.17.3

### OS

Windows 10

### Language

Typescript

**Comment by samasama** [comment]
In the Api settings page the lambda is not selected and does not show up in the drop down either trying to set it, however switching to enter urn manually, the correct lambda urn shows up but the api still fails
It did not work until I deleted every other graphql api there then it showed up. It seems graphql api lambda authorizer settings has a cross-talk across  the api causing this setting to be filled only for a single api

**Comment by indrora** [comment]
Closing as this ticket is stale (over 9 months since last event or relates to the CDKv1). 

If this is still a relevant request in the CDKv2, please open a new ticket.
