### ISSUE TITLE
(aws-rds): `SnapshotCredentials` does not accept imported `ISecret` type

### ISSUE THREAD

**Issue by revmischa** [aws/aws-cdk#19409]
### What is the problem?

Any way to import an existing DB secret and use it with an RDS ServerlessCluster?
If I use `secretsmanager.Secret.fromSecretNameV2()` it returns an `ISecret` but `SnapshotCredentials.fromSecret(secret) `[wants a](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_rds.SnapshotCredentials.html#static-fromwbrsecretsecret) Secret

Seems like I can't import a secret and use it as credentials for a DB created from snapshot.

I did this:
```ts
          const dbSecret = SnapshotCredentials.fromGeneratedSecret("postgres");
          db = new DatabaseFromSnapshot(this, "DB", {
            ...dbProps,
            engine: DatabaseClusterEngine.AURORA_POSTGRESQL,
            snapshotIdentifier: dbSnapshotName,
            credentials: dbSecret,
          });
```

And it seems like it generates a new password for me at random times when I deploy. Not really what I want at all.

### Reproduction Steps

See above code

### What did you expect to happen?

Be able to use an existing secret with a DB from snapshot.

### What actually happened?

![image](https://user-images.githubusercontent.com/245131/158452826-962f72ac-fcff-4594-8668-ba2cad7ea163.png)

### CDK CLI Version

2.7.0

### Framework Version

2.7.0

### Node.js Version

14

### OS

MacOS

### Language

Typescript

### Language Version

4.6

**Comment by ryparker** [comment]
You'll want to use the following API:

[`Secret.fromSecretNameV2()`](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_secretsmanager.Secret.html#static-fromwbrsecretwbrnamewbrv2scope-id-secretname) - Imports a secret by secret name. _A secret with this name must exist in the same account & region._
[`SnapshotCredentials.fromSecret()`](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_rds.SnapshotCredentials.html#static-fromwbrsecretsecret) - Update the snapshot login with an existing password from a Secret. _The Secret must be a JSON string with a password field._

For example if I have an existing Secret named 'postgres' and it's value is:

```json
{
   "password": "secret-db-password",
}
```

Then you should be able to retrieve this value and pass it into the SnapshotCredentials like so:

```ts
const postgresSecret = Secret.fromSecretNameV2(this, 'PostgresSecret', 'postgres')
const dbCredentials = SnapshotCredentials.fromSecret(postgresSecret)
db = new DatabaseFromSnapshot(this, "DB", {
	...dbProps,
	engine: DatabaseClusterEngine.AURORA_POSTGRESQL,
	snapshotIdentifier: dbSnapshotName,
	credentials: dbCredentials,
})
```

**Comment by ryparker** [comment]
Hey @revmischa  👋🏻 

Thanks for opening this issue. It does look like this is a bug with the `SnapshotCredentials`. The `SnapshotCredentials.fromSecret()` should accept the `ISecret` type. We implemented a fix for this on the `Credentials.fromSecret()`  however the fix was not applied to this `SnapshotCredentials` variant.

Related Issue that fixed this for `Credentials` : https://github.com/aws/aws-cdk/issues/11015
The merged fix for the `Credentials` issue: https://github.com/aws/aws-cdk/pull/11033

**Comment by ryparker** [comment]
Full repro code:

```ts
import { App, Stack } from 'aws-cdk-lib';
import {
    DatabaseClusterEngine, ServerlessClusterFromSnapshot, SnapshotCredentials
} from 'aws-cdk-lib/aws-rds';
import { Secret } from 'aws-cdk-lib/aws-secretsmanager';

const app = new App();
const stack = new Stack(app, "sample");

const postgresSecret = Secret.fromSecretNameV2(
  stack,
  "PostgresSecret",
  "postgres-secret-demo"
);
const dbCredentials = SnapshotCredentials.fromSecret(postgresSecret);
const db = new ServerlessClusterFromSnapshot(stack, "DB", {
  engine: DatabaseClusterEngine.AURORA_POSTGRESQL,
  snapshotIdentifier: "snapshot-of-my-postgres-db",
  credentials: dbCredentials,
});
```
