### ISSUE TITLE
(kinesisfirehose): Support dynamic partitioning and parquet conversion for firehose in cdk 2.16

### ISSUE THREAD

**Issue by scumpah** [aws/aws-cdk#19413]
### General Issue

Dynamic partitioning in kinesisfirehose 

### The Question

I'm currently using https://www.npmjs.com/package/@aws-cdk/aws-kinesisfirehose-alpha latest version and using https://www.npmjs.com/package/@aws-cdk/aws-kinesisfirehose-destinations-alpha to have S3 as destination.

I want to enable dynamic partitioning and convert JSON to parquet before storing data in S3 destination. There seems to be a way to work around for cd v1.148

```
const firehose = new kinesisfirehose.CfnDeliveryStream(...);
firehose.addPropertyOverride(
    "ExtendedS3DestinationConfiguration.DynamicPartitioningConfiguration",
    { Enabled: true, RetryOptions: { DurationInSeconds: 300 } }
)
```

How can I achieve the same by using the above npm modules? Or is there any other workaround for this?

### CDK CLI Version

2.16.0

### Language

Typescript

**Comment by peterwoodworth** [comment]
Our alpha package doesn't directly support this yet I don't think. But, you can use the same `propertyOverride` method with the packages you've linked. You'll only have to add another step which is accessing the underlying CloudFormation resource generated by the CDK construct

```ts
const deliveryStream = new DeliveryStream(this, ...);
const firehose = deliveryStream.node.defaultChild as CfnDeliveryStream;
firehose.addPropertyOverride(...);
...
```

Let me know if you have any more concerns 🙂
