### ISSUE TITLE
(ec2): Allow passing existing route table to new subnets

### ISSUE THREAD

**Issue by markussiebert** [aws/aws-cdk#19424]
### Description

At the moment every subnet creates it's own route table and route table association. It should be possible to reuse route tables.

At the moment I have to do some casting, propertyOverride and removeResource ... that's not great.

### Use Case

Sometimes you don't want a new route table for every subnet you create, or you don't have permissions to create route tables on your own.

### Proposed Solution

Allow passing an IRouteTable would be great!

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by japerwu** [comment]
I wish this is implemented!!!!
