### ISSUE TITLE
(aws-tools): CLI `--hotswap` -> ` We don't support attributes of the 'AWS::DynamoDB::Table' resource`

### ISSUE THREAD

**Issue by kbakk** [aws/aws-cdk#19421]
### What is the problem?

When using nested stacks, and a DynamoDB table is created in the parent stack, `--hotswap` will not work.

### Reproduction Steps

<details>
<summary>Python reproducer</summary>

Initialize project with `cdk init sample-app --language python` and create/change:

`app.py`

```py
import aws_cdk as cdk

from cdk_py_workshop.cdk_py_workshop_stack import ApiStack, DatabaseStack


app = cdk.App()
parent = DatabaseStack(app, "cdk-py-workshop-database")
ApiStack(parent, "cdk-py-workshop-api", table=parent.table)

app.synth()
```

`cdk_py_workshop/cdk_py_workshop_stack.py`

```py
from constructs import Construct
from aws_cdk import (
    Stack,
    NestedStack,
    aws_lambda as _lambda,
    aws_apigateway as apigw,
    aws_dynamodb as ddb
)

class DatabaseStack(Stack):
    def __init__(self, scope: Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)
        self.table = ddb.Table(
            self, 'Hits',
            partition_key={'name': 'path', 'type': ddb.AttributeType.STRING}
        )

class ApiStack(NestedStack):

    def __init__(self, scope: Construct, id: str, table, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)
        my_lambda = _lambda.Function(
            self, 'HelloHandler',
            runtime=_lambda.Runtime.PYTHON_3_7,
            code=_lambda.Code.from_asset('lambda'),
            handler='hello.handler',
            environment={"TABLE": table.table_name}
        )
        table.grant_read_write_data(my_lambda)
        apigw.LambdaRestApi(
            self, 'Endpoint',
            handler=my_lambda,
        )

```

`lambda/hello.py`

```py
def handler(event, context):
    print(f'request: {event}')
```
</details>

Run `cdk deploy` once, then modify `lambda/hello.py` (e.g. add another `print`). Try to run `cdk deploy --hotswap`. 	

### What did you expect to happen?

Super fast hotswap of my lambda function and an output like `✨  Total time: 10.97s` (or less 🤩 )

### What actually happened?

I'm getting this message:

```
✨  Synthesis time: 7.16s

⚠️ The --hotswap flag deliberately introduces CloudFormation drift to speed up deployments
⚠️ It should only be used for development - never use it for your production Stacks!
cdk-py-workshop-database: deploying...
[ ... removed ... ]
Could not perform a hotswap deployment, because the CloudFormation template could not be resolved: We don't support attributes of the 'AWS::DynamoDB::Table' resource. This is a CDK limitation. Please report it at https://github.com/aws/aws-cdk/issues/new/choose
Falling back to doing a full deployment
cdk-py-workshop-database: creating CloudFormation changeset...

 ✅  cdk-py-workshop-database

✨  Deployment time: 70.7s

Stack ARN:
arn:aws:cloudformation:eu-west-1:012345678900:stack/cdk-py-workshop-database/fc7aeb10-a530-11ec-81af-0a3d49828e3b

✨  Total time: 77.86s
```

And CDK runs a full deployment.

### CDK CLI Version

2.16.0 (build 4c77925)

### Node.js Version

v16.14.0

### OS

Debian GNU/Linux 11

### Language

Python

### Language Version

Python 3.9.10

**Comment by hoegertn** [comment]
What attributes of a table should be hotswappable? I am afraid we might open Pandora's box if we allow hotswapping for too many resources.

**Comment by mmeylan** [comment]
What do you think of allowing developers to still use hotswapp for resources that are hot swappable (lambda, ecs, etc), even if there is not supported resources in the stack ?

Hear me out:

In our case for instance, the need for hotswap is quite high. Full deployments take ~10 minutes.  Hotswapping would reduce dev deployments dramatically, hence increase our DX tremendously. But, because we're using RDS (same problem as for Dynamo users), we can't use hotswapp. But, I'd be more than happy to use hotswapp **without** RDS support. I could always use a full deployment when I need to update the DB.

**Comment by kbakk** [comment]
@skinny85 Hi, did you see the expandable section "Python reproduce" in the description? Is there anything in addition that's wanted here?

**Comment by skinny85** [comment]
> @skinny85 Hi, did you see the expandable section "Python reproduce" in the description?

I in fact it _not_ see it 😃. Thanks, I think that's all I need!

**Comment by skinny85** [comment]
I was able to reproduce this - working on a fix!
