### ISSUE TITLE
(aws-ec2): InterfaceVpcEndpointAwsService - auto-scaling endpoints missing

### ISSUE THREAD

**Issue by Obirah** [aws/aws-cdk#19420]
### What is the problem?

The class `InterfaceVpcEndpointAwsService` does not contain the auto-scaling endpoints (`autoscaling`, `application-autoscaling` and `autoscaling-plans`).

### Reproduction Steps

Look at the static fields of `InterfaceVpcEndpointAwsService`, said endpoints are missing.

### What did you expect to happen?

I expected to be able to use the auto-scaling endpoints in this fashion: `InterfaceVpcEndpointAwsService.AUTOSCALING`

### What actually happened?

I need to create the endpoint like this: `new InterfaceVpcEndpointAwsService('autoscaling')`

### CDK CLI Version

2.16.0

### Node.js Version

16.x

### OS

Linux

### Language

Typescript

### Language Version

4.6.2

**Comment by awalker125** [comment]
I could use this as well

**Comment by TheRealAmazonKendra** [comment]
This has now been completed.
