### ISSUE TITLE
Rename logged backwards

### ISSUE THREAD

**Issue by CarsonF** [aws/aws-cdk#1945]
Renaming the stack logs the names reversed. Unless I have the command backwards, I assumed the `rename` option was the old name and that seems to be true based on what the deployment does.

```
$ cdk deploy new-name --rename old-name
```
Outputs:
```
old-name: deploying... (was new-name)
old-name: creating CloudFormation changeset...
```

CDK 0.24.1 (build 67fcf6d)

---- 
Edit: Hmm it seems that rename option didn't rename the stack. I'm probably confused on the functionality.

**Comment by robertd** [comment]
It worked for me. However, files on the disk are still w/ old name.

```
cdk deploy --rename NewStackName
NewStackName: deploying... (was OldStackName)
Updated: lambda/bash (zip)
NewStackName: creating CloudFormation changeset...
...
```

**Comment by rix0rrr** [comment]
@CarsonF you do have the command backwards.

And @robertd, renames don't affect everything yet, just the name under which stacks are deployed while running `cdk deploy`.
