### ISSUE TITLE
CHANGELOG markdown not rendered

### ISSUE THREAD

**Issue by rantoniuk** [aws/aws-cdk#19461]
### Describe your issue?

https://github.com/aws/aws-cdk/blob/master/CHANGELOG.md is not rendered anymore because of large file size. Probably needs to be re-factored/split into smaller pieces (e.g. 1.x and 2.x)?

**Comment by peterwoodworth** [comment]
Thanks for reporting this! 

we're aware of the issue and still trying to figure out the best path forward 🙂

Tracking here https://github.com/aws/aws-cdk/issues/19063#event-6110248629
