### ISSUE TITLE
(awscdkapigatewayv2integrationsalpha): Response headers missing

### ISSUE THREAD

**Issue by fynnfluegge** [aws/aws-cdk#19472]
### General Issue

The response headers of an HTTP-API with Lamba Non-Proxy Integration are missing. 

### The Question

I guess a ran into the same issue as described here [https://github.com/aws/aws-cdk/issues/17924](https://github.com/aws/aws-cdk/issues/17924) with no final solution.

I am trying to set up an Http Api with a Lambda Integration by using _awscdkapigatewayv2integrationsalpha.NewHttpLambdaIntegration_ as below
```
httpApi.AddRoutes(&awscdkapigatewayv2alpha.AddRoutesOptions{
		Path: jsii.String("/test"),
		Authorizer: awscdkapigatewayv2alpha.HttpAuthorizer_FromHttpAuthorizerAttributes(stack, jsii.String("MyHttpAuthorizer4Test"), &awscdkapigatewayv2alpha.HttpAuthorizerAttributes{
			AuthorizerId:   authorizer.AuthorizerId(),
			AuthorizerType: jsii.String("JWT"),
		}),
		Methods:     &[]awscdkapigatewayv2alpha.HttpMethod{awscdkapigatewayv2alpha.HttpMethod_GET},
		Integration: awscdkapigatewayv2integrationsalpha.NewHttpLambdaIntegration(jsii.String("MyHttpLambdaIntegration"), getHandler, &awscdkapigatewayv2integrationsalpha.HttpLambdaIntegrationProps{}),
	})
```

and the Http Api as below
```
httpApi := awscdkapigatewayv2alpha.NewHttpApi(stack, jsii.String("MyHttpApi"), &awscdkapigatewayv2alpha.HttpApiProps{
		ApiName: jsii.String("MyHttpApi"),
		CorsPreflight: &awscdkapigatewayv2alpha.CorsPreflightOptions{
			AllowOrigins: jsii.Strings("*"),
			AllowHeaders: jsii.Strings("*"),
			AllowMethods: &[]awscdkapigatewayv2alpha.CorsHttpMethod{
				awscdkapigatewayv2alpha.CorsHttpMethod_OPTIONS,
				awscdkapigatewayv2alpha.CorsHttpMethod_GET,
				awscdkapigatewayv2alpha.CorsHttpMethod_POST,
			},
		},
	})
```

Now the response from my Http Api is blocked in my Web App by the Browser because of CORS. The OPTIONS Request works as intended but the response to the GET request has no headers. Adding the headers in the lambda function as mentioned here [https://github.com/aws/aws-cdk/issues/17924#issuecomment-1001789282](https://github.com/aws/aws-cdk/issues/17924#issuecomment-1001789282) is no solutiuon, since they are ignored due to non-proxy.
Now I am ending up by mixing aws cdk _awsapigatewayv2_ and _awscdkapigatewayv2alpha_ to define a ResponseIntegration. But the _awscdkapigatewayv2integrationsalpha.NewHttpLambdaIntegration_ don't provides an Id to pass it to _awsapigatewayv2.NewCfnIntegrationResponse_. It is very confusing. I hope I am missing something to set up the Response headers for my Http Api. 

Btw it is weird, when I change the path of my Route to "/" instead of "/test" the Access-Control-Allow-Origin Header is included in the response. But I need different routes on my API. 

Thanks for every kind of help!

### CDK CLI Version

2.14.0

### Language

Go

### Language Version

1.16

**Comment by fynnfluegge** [comment]
As mentioned here [https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-parameter-mapping.html](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-parameter-mapping.html) the request and response headers can be configured. But it is said there that Access-Control-* header ist reserved and not configurable.  So I have no idea how to set the headers for my lambda integration on different paths properly.

**Comment by fynnfluegge** [comment]
solved it. was a mistake on my implementation.

**Comment by stevemer** [comment]
ok, but what was the mistake?

**Comment by fynnfluegge** [comment]
I had a slash "/" at the end of my api url call. Instead of not found error chrome signals a CORS error, so I thought it was a CORS issue.
