### ISSUE TITLE
(aws_sam): requestModel and requestParameters are missing in ApiEventProperty class

### ISSUE THREAD

**Issue by alexpulver** [aws/aws-cdk#19477]
### What is the problem?

AWS Serverless Application Model (AWS SAM) latest specification includes `RequestModel` and `RequestParameters` properties in [AWS::Serverless::Function.Events.Api](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-api.html) object. These properties are missing in [aws-cdk-lib.aws_sam.ApiEventProperty](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_sam.CfnFunction.ApiEventProperty.html) interface on the AWS CDK side.

### Reproduction Steps

This is a lack of properties issue, so no steps to reproduce - see links to documentation in problem description.

### What did you expect to happen?

`ApiEventProperty` to have `requestModel` and `requestParameters` properties according to AWS SAM latest specification.

### What actually happened?

`ApiEventProperty` doesn't have `requestModel` and `requestParameters` properties.

### CDK CLI Version

2.17.0 (build f9cd009)

### Node.js Version

v14.16.1

### OS

macOS Catalina

### Language

Typescript, Python, .NET, Java, Go

**Comment by ryparker** [comment]
Hey @alexpulver 👋🏻

Thanks for opening the issue and for linking the documentation. I'm going to convert this into a feature-request as these new props are not currently supported in the `ApiEventProperty` struct. This would be a great first issue if anyone is interested to pick this up and submit a PR (please make sure to follow our [contribution guidelines](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md?rgh-link-date=2022-03-21T22%3A05%3A50Z).) 🙏

Meanwhile if you're in need of a workaround you can define the corrected type like so:

e.g.
```ts
import { CfnFunction } from "aws-cdk-lib/aws-sam";
...

// Workaround until issue #19477 is resolved.
export type RequestModel = {
   Model: String
  Required: Boolean
  ValidateBody: Boolean
  ValidateParameters: Boolean
}
export type RequestParameter = {
  Caching: Boolean
  Required: Boolean
}
export type ApiEventProperty = CfnFunction.ApiEventProperty & {
  RequestModel?: RequestModel
  RequestParameters?: String | RequestParameter
}

const apiEventProperty: ApiEventProperty = {
	...
}
```

**Comment by ryparker** [comment]
Hey @alexpulver 👋🏻

Thanks for opening the issue and for linking the documentation. 

A dev will pick up this bug in order of priority. This is marked as p1 which means it has been prioritized as important, although please keep in mind that we do have a large number of issues at the moment. It may be some time before we are able to solve this particular issue. We use +1s to help us prioritize our work, and as always we are happy to take contributions if anyone is interested to pick this up and submit a PR.

**Comment by alexpulver** [comment]
Thanks @ryparker! For others stumbling into this, below is an example of workaround using escape hatch (Python):
```python
from aws_cdk import aws_sam as sam

sam_api: sam.CfnApi = ...
sam_api.models = {"User": "..."}

sam_function: sam.CfnFunction = ...
sam_function.events = {
    "ApiEvent": sam.CfnFunction.EventSourceProperty(
        properties=sam.CfnFunction.ApiEventProperty(
            method="GET",
            path="/",
            rest_api_id=sam_api.logical_id,
        ),
        type="Api",
    )
}

sam_function.add_property_override(
    "Events.ApiEvent.Properties.RequestModel",
    {
        "Model": "User",
        "Required": "true",
        "ValidateBody": "true",
    }
)
```
