### ISSUE TITLE
(core): allow to add custom TagFormatter

### ISSUE THREAD

**Issue by webratz** [aws/aws-cdk#19507]
### Description

The `TagManager` allows to set different pre-defined TagFormatters. It should be possible to implement an own `ItagFormatter` and supply it to get a custom format of the tags.

### Use Case

For a custom (in this case datadog) resource i need another tag format besides the provided ones.
As I also need it to be lazily rendered to make sure all tags are included i didn't find another way on how that would be possible.

#### Option A
allow to pass in a custom tag formatter that implements `ItagFormatter` to `TagManager`.
This is the most generic solution, but would probably change the current interface.

#### Option B
Implement a Datadog Custom formatter and ship it with cdk.
This is probably the simplest, but of course this would be very specific format and therefore probably should not be directly in cdk core. (i have a draft of this ready)

### Other information

I might be able to implement both Options, but would need some guidance / help on how to integrate it with the existing code so it complies to the stability requirements of the interfaces.

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by rix0rrr** [comment]
I'd prefer Option A. `ITagFormatter` is not currently public, so changing the interface should not be a problem.

Curious: why does it need to be changed?

**Comment by webratz** [comment]
The Tags of the DataDog resources require a different format. This would help to implement a proper tagger for it.
See https://github.com/DataDog/datadog-cloudformation-resources/blob/master/datadog-monitors-monitor-handler/datadog-monitors-monitor.json#L183
I didn't find a good workaround to avoid this.
