### ISSUE TITLE
TopicRule action for firehose in AWS IoT

### ISSUE THREAD

**Issue by sholtomaud** [aws/aws-cdk#19501]
### What is the problem?

I have two IoT Rule Actions in the one Rule. 

A) Lambda
B) Firehose to s3

It all seems to work, Lambda works, and Firehose can write to s3 on various manual tests.

The problem is that the IoTRule does not trigger the firehose action. 

The IoTRule DOES trigger the Lambda but not the firehose.

### Reproduction Steps

Build IoTRule stack with two actions. A) Lambda, B) firehose.

### What did you expect to happen?

I expected the IoTRUle to trigger the Firehose to write to s3 

### What actually happened?

IoTRule only triggered Lambda not Firehose

### CDK CLI Version

2

### Node.js Version

14.x

### OS

osx

### Language

Typescript

### Language Version

3.8.3

**Comment by yamatatsu** [comment]
Maybe you use `batchMode: true`?
If use it, the SQL of TopicRule must be evaluated as multiple records.

For example, set the SQL as:
```sql
SELECT VALUE dataList FROM 'foo/bar'
```
and send a message as following:

```sh
aws iot-data publish --topic 'foo/bar' --payload (echo '{"dataList":[{"id":1},{"id":2},{"id":3}]}' | base64)
```

Or you can get error logs of TopicRule by setting `errorAction` as following:
```ts
new TopicRule(this, 'rule', {
  ...
  errorAction: new actions.CloudWatchLogsAction(new logs.LogGroup(this, 'logGroup')),
})
```

**Comment by skinny85** [comment]
Hey @sholtomaud,

thanks for opening the issue. Can you show your CDK code?

Thanks,
Adam

**Comment by sholtomaud** [comment]
Hi @skinny85 and @yamatatsu, I think @yamatatsu is right, that ```batchMode: true``` was the culprit. After offline chats with @yamatatsu (👍 ) we were able to get it working.

**Comment by sholtomaud** [comment]
Fixed if `batchMode: false` setting is used.

**Comment by skinny85** [comment]
@yamatatsu you are a star. Thank you so much for jumping on this one and solving it so quickly!
