### ISSUE TITLE
cdk cli: export stack arn to a file

### ISSUE THREAD

**Issue by StevePotter** [aws/aws-cdk#19528]
### Description

I have to export the stack arn and outputs from `cdk deploy` into another system.  `cdk deploy --outputs-file outputs.json` gives me the outputs, which is great, but there is no way to get the arn than to parse the `cdk deploy` output.  I'd love another command line parameter that outputted stack information to a json file.

### Use Case

I need to get the generated stack arn and stack outputs and export them to a system that tracks deployments.

### Proposed Solution

A new CLI parameter that will output the stack info (name, arn) to a JSON, much like the existing `--outputs-file` parameter

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by indrora** [comment]
This issue is very old and the pull request for it is abandoned. I am going to close it. If you think this was in error, open a new ticket.
