### ISSUE TITLE
(aws-ec2): vpcIpv6CidrBlocks missing from interface IVpc

### ISSUE THREAD

**Issue by 5nafu** [aws/aws-cdk#19525]
### What is the problem?

When looking up an existing VPC with `Vpc.fromLookup(this, 'VPCexample', { vpcName: 'foobar' })`, there appears not to be any way to actually get the IPv6 CIDR blocks associated with the VPC as the interface `IVpc` is missing the appropiate property `vpcIpv6CidrBlocks` that is available in the `Vpc` construct.

The `vpcCidrBlock` property only contains IPv4 addresses.

We tried to use an escape hatch with
```
const cfnVPC = VPC as CfnVPC
```
but this was unsuccessful  as there is not enough overlap:
> Conversion of type 'IVpc' to type 'CfnVPC' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Type 'IVpc' is missing the following properties from type 'CfnVPC': attrCidrBlock, attrCidrBlockAssociations, attrDefaultNetworkAcl, attrDefaultSecurityGroup, and 34 more.

### Reproduction Steps

* (Manually) Create a VPC with an (Amazon managed) IPv6 CIDR Block attached
* Lookup the VPC with:
  `const VPC = Vpc.fromLookup(this, 'exampleVPC', { vpcName: '<whatever>' }) `
* Get the IPv6 CIDR blocks with 
  `console.log(VPC.vpcIpv6CidrBlocks)`-> This fails
* Get the CIDR Blocks with
  `console.log(VPC.vpcCidrBlock)`-> This only shows IPv4

### What did you expect to happen?

I did expect to find out the attached IPv6 CIDR block of a VPC.

### What actually happened?

See above Reproduction steps.

### CDK CLI Version

2.15.0 (build 151055e)

### Node.js Version

16.11.26

### OS

Linux & OSX

### Language

Typescript

**Comment by corymhall** [comment]
I think this should be easy to add. We will just need to add this to the vpc context provider.

I am unassigning and marking this issue as `p2`, which means that we are unable to work on this immediately.

We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://join.slack.com/t/cdk-dev/shared_invite/zt-mso6p56d-qJp7SOTBvMaQuDrx7R2wHg) to solicit support for reprioritization.

**Comment by ykethan** [comment]
reopening this issue as this still does appear to be valid request.

**Comment by pahud** [comment]
Yes this is still relevant. Please help us prioritize with 👍
