### ISSUE TITLE
(@aws-cdk/aws-apigatewayv2-alpha): Cannot get API Gateway to trigger connect or disconnect

### ISSUE THREAD

**Issue by brucegl** [aws/aws-cdk#19532]
### What is the problem?

Not sure if the problem is with my code, the documentation or the implementation. After deploying the stack, the AWS console correctly displays an API Gateway trigger at the page Lambda>Functions>connect>Configuration>Triggers, however, the following is also displayed:

API Gateway:
arn:aws:execute-api:eu-west-1:1234567890:7sfj6g3ekl/*/*$connect
x The API with ID 7sfj453ekl doesn’t include a route with path /* having an integration arn:aws:lambda:eu-west-1:1234567890:function:process_connect_requests.

If I'm doing something wrong, it's probably in the following lines:

```ts
    const webSocketConnectIntegration = new WebSocketLambdaIntegration("ConnectIntegration", connectFunction);
    const webSocketDisconnectIntegration = new WebSocketLambdaIntegration("DisconnectIntegration", disconnectFunction);

    const webSocketApi = new apigwv2.WebSocketApi(this, "WebSocket API", {
      apiName: "webSocket",
      routeSelectionExpression: "$request.body.action",
      connectRouteOptions: { integration: webSocketConnectIntegration },
      disconnectRouteOptions: { integration: webSocketDisconnectIntegration },
    });
```

### Reproduction Steps

```ts
import { Duration, RemovalPolicy, Stack, StackProps } from "aws-cdk-lib";
import { Construct } from "constructs";
import * as dynamodb from "aws-cdk-lib/aws-dynamodb";
import * as lambda from "aws-cdk-lib/aws-lambda";
import * as path from "path";
import * as apigwv2 from "@aws-cdk/aws-apigatewayv2-alpha";
import { WebSocketLambdaIntegration } from "@aws-cdk/aws-apigatewayv2-integrations-alpha";

export class ApigwStack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);

    const webSocketTableName = "WebSocketConnections";

    const connectFunction = new lambda.Function(this, "Connect Function", {
      functionName: "process_connect_requests",
      runtime: lambda.Runtime.NODEJS_14_X,
      handler: "index.handler",
      code: lambda.Code.fromAsset(path.join(__dirname, "../functions/connect")),
      timeout: Duration.seconds(5),
      environment: {
        TABLE_NAME: webSocketTableName,
      },
    });

    const disconnectFunction = new lambda.Function(this, "Disconnect Function", {
      functionName: "process_disconnect_requests",
      runtime: lambda.Runtime.NODEJS_14_X,
      handler: "index.handler",
      code: lambda.Code.fromAsset(path.join(__dirname, "../functions/disconnect")),
      timeout: Duration.seconds(5),
      environment: {
        TABLE_NAME: webSocketTableName,
      },
    });

    const webSocketLogTable = new dynamodb.Table(this, "WebSocket Log Table", {
      tableName: webSocketTableName,
      partitionKey: { name: "ConnectionId", type: dynamodb.AttributeType.STRING },
      removalPolicy: RemovalPolicy.DESTROY, // not recommended for production
    });
    webSocketLogTable.grantReadWriteData(connectFunction);
    webSocketLogTable.grantReadWriteData(disconnectFunction);

    const webSocketConnectIntegration = new WebSocketLambdaIntegration("ConnectIntegration", connectFunction);
    const webSocketDisconnectIntegration = new WebSocketLambdaIntegration("DisconnectIntegration", disconnectFunction);

    const webSocketApi = new apigwv2.WebSocketApi(this, "WebSocket API", {
      apiName: "webSocket",
      routeSelectionExpression: "$request.body.action",
      connectRouteOptions: { integration: webSocketConnectIntegration },
      disconnectRouteOptions: { integration: webSocketDisconnectIntegration },
    });

    const webSocketStage = new apigwv2.WebSocketStage(this, "Production Stage", {
      webSocketApi: webSocketApi,
      stageName: "prod",
      autoDeploy: true,
    });
  }
}
```
Please use the typical example connect/disconnect code

### What did you expect to happen?

Something like the following to be displayed in Lambda>Functions>connect>Configuration>Triggers

API Gateway: [WSM](https://eu-west-1.console.aws.amazon.com/apigateway/main/api-detail?region=eu-west-1&api=coau633tqf)
arn:aws:execute-api:eu-west-1:1234567890:cogh633tqf/*/$connect
API endpoint: https://cogh633tqf.execute-api.eu-west-1.amazonaws.com/prod/
Details
API type: WEBSOCKET
Authorization: NONE
Method: $connect
Stage: prod

### What actually happened?

wscat cannot connect

### CDK CLI Version

2.17.0 (build f9cd009)

### Node.js Version

v16.13.0node.js

### OS

Linux Mint

### Language

Typescript

**Comment by brucegl** [comment]
Typescript version is 4.5.5

**Comment by brucegl** [comment]
A bit of an update... if I remove the (dis)connectRouteOptions, I can add these routes using the AWS console as a workaround.

**Comment by ryparker** [comment]
Hey @brucegl 👋🏻 

Thanks for opening the issue with us. I was able to reproduce this and i've uploaded the full code with documentation to this [repo](https://github.com/ryparker/aws-cdk-sample-apigatewayv2-alpha-trigger).

This might be a bug in the AWS console. Have you noticed any functional problems that might be caused be related to this?

**Comment by ryparker** [comment]
Here's a screenshot of the error:

![error-screenshot](https://user-images.githubusercontent.com/17558268/160185676-15ba5704-a7ba-49ef-b457-bb3f89094de6.png)

**Comment by brucegl** [comment]
Hi @ryparker, I think the issue goes beyond the AWS console as I was also unable to wscat -c to the endpoint.

**Comment by Spider-ant** [comment]
If you view (through console) the websocket api route integration request (see screenshot) you will see the lambda function is set to the lambda function name. If the websocket integration applied the function arn instead it would likely fix the issue. (see warning in the screenshot)
![Screen Shot 2022-05-13 at 12 56 52 PM](https://user-images.githubusercontent.com/64494098/168332449-d622a2f9-8a97-4d38-a91e-7e5a4cecef27.png)

**Comment by brucegl** [comment]
Thanks @Spider-ant, I'll see if I can codify it with the lambda urn next time I build a stack

**Comment by bcutler2919** [comment]
Have there been any recent updates on this? I'm running into the same error on the lambda trigger but not seeing the issue @Spider-ant is referring to.

**Comment by oyatrides** [comment]
any updates on this ? having the same error

**Comment by TanjaBayer** [comment]
Same here, the generated template as the following permissions:

`
"websocketapitestwebsocketapiconnectRoutedefaultwebsocketroutePermissionD7AA3922": {
   "Type": "AWS::Lambda::Permission",
   "Properties": {
    "Action": "lambda:InvokeFunction",
    "FunctionName": {
     "Fn::GetAtt": [
      "websocketapiMyLambda9DA088A9",
      "Arn"
     ]
    },
    "Principal": "apigateway.amazonaws.com",
    "SourceArn": {
     "Fn::Join": [
      "",
      [
       "arn:",
       {
        "Ref": "AWS::Partition"
       },
       ":execute-api:us-east-2:*********:",
       {
        "Ref": "websocketapitestwebsocketapi4A0E7CD2"
       },
       "/*/*$connect"
      ]
     ]
    }
   }
`

I think one of the /* before the $connect should not be there

**Comment by astroalek** [comment]
Same problem here with version 2.86

**Comment by katzrkool** [comment]
Same problem in CDK v1.

**Comment by ashishpandey001** [comment]
this issue has been open for 16 months, are there no plans to resolve this and make the L2 construct usable?

If not, can we mark the construct as broken so people don't waste their time using it over the L1 constructs?

**Comment by WillDelish** [comment]
I am also experiencing this issue and have wasted a bit of time troubleshooting my lambda when it never triggers to begin with due to this bug. Will switch to a different construct, but its unfortunate this has been open for so long without marking the construct as broken
