### ISSUE TITLE
(lambda): deprecated methods mentioned in Alias class reference

### ISSUE THREAD

**Issue by ghost** [aws/aws-cdk#19533]
### link to reference doc page

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda.Alias.html

### Describe your issue?

The example in this page uses a deprecated method `addVersion()` which isn't in CDK v2 anymore. The `version` prop description also mentions `eddVersion()`

The `latestVersion` description on this page refers to `currentVersion` which is also deprecated and not present in CDK v2.

I can put in a PR for this soon, but as it was reported by a customer I wanted to get it on record.

**Comment by indrora** [comment]
This is no longer the case.
