### ISSUE TITLE
(pipelines): SelfMutate loads notices by default

### ISSUE THREAD

**Issue by Kruspe** [aws/aws-cdk#19542]
### What is the problem?

When using the SelfMutate step it calls `cdk -a ${toPosixPath(embeddedAsmPath(this.pipeline))} deploy ${pipelineStackIdentifier} --require-approval=never --verbose`. With the new cdk release this fetches notices. If the SelfMutate runs in a private subnet without internet connection the step takes really long until the request times out. (Build times go up from 2 minutes to 16 minutes).

### Reproduction Steps

Create a pipeline which uses the SelfMutate option and runs in a private subnet.

### What did you expect to happen?

For the SelfMutate I do not think that it is necessary to fetch the notices.

### What actually happened?

The deploy step tries to fetch the notices.

### CDK CLI Version

2.17.0

### Node.js Version

16.14.0

### OS

MacOS Monetery 12.3

### Language

Typescript

I think it would suffice to add the `--no-notices` flag to the cdk deploy command.

**Comment by Kruspe** [comment]
If you agree with my assumptions I can provide a PR to fix this.

**Comment by Kruspe** [comment]
Yeah I see that problem. What we could do is a version check.

We are not providing a cliVersion so we are using the latest version (2.17.0). I saw the PR but it does not seem to be picked up.

**Comment by otaviomacedo** [comment]
Hi, @Kruspe.

How does npm install the latest version when it doesn't have access to the internet? Are you using CodeBuild? Can you please confirm the version by looking at the debug output? It's the first line.

**Comment by Kruspe** [comment]
We are using a proxy to download the necessary things and are providing a list of whitelisted urls. NPM is Part of it but the notices endpoint is not.
The version being downloaded is the latest one. It was 2.17.0 and now it is 2.18.0.

**Comment by Kruspe** [comment]
@rix0rrr & @otaviomacedo any thoughts on this?
