### ISSUE TITLE
(aws-cdk-lib/aws_s3_assets): The ouput of s3ObjectUrl is different between V1 and V2 of CDK. V2 version does not return with S3 format

### ISSUE THREAD

**Issue by knihit** [aws/aws-cdk#19565]
### What is the problem?

When using the `s3ObjectUrl` attribute from the Asset class as below

```ts
const etl_asset = new s3assets.Asset(this, "scriptlocation", {
            path: `etl/transform.py`,
          }).s3ObjectUrl,
```

returns different outputs with CDK v1 and v2.

With CDK v1.146.0 it returns an S3 format url with tokens. But with CDK v2.10.0 this attribute returns only the token (without the s3 formatted url).
![image (1)](https://user-images.githubusercontent.com/24500178/160160504-53bd9c06-80c5-4f42-9127-cf517dc5e266.png)
![image](https://user-images.githubusercontent.com/24500178/160160508-d1c4fa0f-b0f0-4e23-ad52-c69ee29f70bf.png)

Look under the `watch` section of the two screen shots for the value of the variable _scriptLocation

### Reproduction Steps

Take the following code, it works well with V1 but not with V2.

The entire project can be found here - https://github.com/awslabs/aws-solutions-constructs/tree/main/source/use_cases/aws-custom-glue-etl. 

```ts
import * as glue from '@aws-cdk/aws-glue';
import * as s3assets from '@aws-cdk/aws-s3-assets';
import * as cdk from '@aws-cdk/core';
import { CfnOutput } from '@aws-cdk/core';
import { KinesisstreamsToGluejob } from '@aws-solutions-constructs/aws-kinesisstreams-gluejob';

export class AwsCustomGlueEtlStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const fieldSchema: glue.CfnTable.ColumnProperty [] = [{
      "name": "ventilatorid",
      "type": "int",
      "comment": ""
    },
    {
      "name": "eventtime",
      "type": "string",
      "comment": ""
    },
    {
      "name": "serialnumber",
      "type": "string",
      "comment": ""
    },
    {
      "name": "pressurecontrol",
      "type": "int",
      "comment": ""
    },
    {
      "name": "o2stats",
      "type": "int",
      "comment": ""
    },
    {
      "name": "minutevolume",
      "type": "int",
      "comment": ""
    },
    {
      "name": "manufacturer",
      "type": "string",
      "comment": ""
    }];

    const customEtlJob = new KinesisstreamsToGluejob(this, 'CustomETL', {
      glueJobProps: {
        command: {
          name: 'gluestreaming',
          pythonVersion: '3',
          scriptLocation: new s3assets.Asset(this, 'ScriptLocation', {
            path: `${__dirname}/../etl/transform.py`
          }).s3ObjectUrl
        }
      },
      fieldSchema: fieldSchema
    });

    new CfnOutput(this, 'KinesisStreamName', {
      value: customEtlJob.kinesisStream.streamName
    });

    new CfnOutput(this, 'GlueJob', {
      value: customEtlJob.glueJob.ref
    });

    new CfnOutput(this, 'JobRole', {
      value: customEtlJob.glueJobRole.roleArn
    });
  }
}
```

### What did you expect to happen?

The following call should return an S3 format url string based on the documentation. But does not in the case of CDK V2.

```ts
new s3assets.Asset(this, 'ScriptLocation', {
            path: `${__dirname}/../etl/transform.py`
          }).s3ObjectUrl
        }
```

### What actually happened?

The following code only returns the token. See attached screenshot (value of _scriptLocation under the `watch` section)

![image](https://user-images.githubusercontent.com/24500178/160161312-de6d85fb-d63b-4016-82e3-399e11706a39.png)

```ts
new s3assets.Asset(this, 'ScriptLocation', {
            path: `${__dirname}/../etl/transform.py`
          }).s3ObjectUrl
        }
```

### CDK CLI Version

2.10.0

### Node.js Version

17.7.0

### OS

12.3

### Language

Typescript

### Language Version

4.6.2

### Other information

Referencing the documentation for the asset class (look at the attributes section).

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_s3_assets-readme.html

**Comment by knihit** [comment]
To give some more perspective on this one. Here is V2 code block.

```
import { Stack, StackProps } from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as s3a from 'aws-cdk-lib/aws-s3-assets';

export class S3AssetBugStack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);

    let newAsset = new s3a.Asset(this, 'scriptlocation', {
      path: `lambda/index.js`,
    });

    console.log(`*****Asset url: ${newAsset.s3ObjectUrl}`);

  }
}
```
Results from V2:
*******Asset url: ${Token[TOKEN.202]}**


Here is the V1 code block for the same scenario:
```
import  { Stack, Construct, StackProps } from '@aws-cdk/core';
import * as s3a from '@aws-cdk/aws-s3-assets';

export class V1ClientStack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);

    let newAsset = new s3a.Asset(this, 'scriptlocation', {
      path: `lambda/index.js`,
    });

    console.log(`*****Asset url: ${newAsset.s3ObjectUrl}`);


  }
}
```
Results from V1:
*******Asset url: s3://${Token[TOKEN.12]}/${Token[TOKEN.15]}${Token[TOKEN.17]}**

**Comment by ryparker** [comment]
Hey @knihit 👋🏻 

Thanks for opening the issue and for providing repro code. Even though the unresolved value is different do they resolve to the same value? If so, then could you elaborate on what the use case is for needing the old v1 token format?

**Comment by knihit** [comment]
Hi @ryparker 

To your point, yes I tried the following code

```
    const jobRole = new iam.Role(this, "JobRole", {
      assumedBy: new iam.ServicePrincipal("glue.amazonaws.com"),
      description:
        "Service role that Glue custom ETL jobs will assume for exeuction",
    });

    const etl_code_asset = new s3assets.Asset(this, "scriptlocation", {
      path: path.join(__dirname, "../etl/transform.py"),
    });

    new glue.CfnJob(this, "custom-etl", {
      command: {
        name: "gluestreaming",
        pythonVersion: "3",
        scriptLocation: etl_code_asset.s3ObjectUrl,
      },
      role: jobRole.roleArn,
    });

    etl_code_asset.grantRead(jobRole);
```

and it seems to synthesize correctly.

I have a custom construct for Glue ETL Jobs (https://github.com/awslabs/aws-solutions-constructs/tree/main/source/patterns/%40aws-solutions-constructs/aws-kinesisstreams-gluejob) where I was slicing the object url (https://github.com/awslabs/aws-solutions-constructs/blob/beadb00c0f58b98469a8d7267b6b02615eed1a0d/source/patterns/%40aws-solutions-constructs/core/lib/glue-job-helper.ts#L229). 

Using the sliced information, I was generate an S3 L2 Construct object instance to grant read permissions to Glue Job Service Principal.

**### Question**: If I pass `etl_code_asset.s3ObjectUrl` is there a way to create a Bucket L2 Construct instance? The problem is that CfnJobProps accepts an S3 url as script location but not Asset.
