### ISSUE TITLE
(aws-lex): `CloudWatch` missing from `TextLogDestinationProperty`

### ISSUE THREAD

**Issue by chokevin-aws** [aws/aws-cdk#19571]
### The Problem

`CloudWatch` is missing from `TextLogDestinationProperty`.

- In [CFN doc](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lex-botalias-textlogdestination.html): AWS::Lex::BotAlias TextLogDestination contains a property CloudWatch
- In [CDK doc](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lex.CfnBotAlias.TextLogDestinationProperty.html):  TextLogDestinationProperty turns out to be empty

I noticed that this inconsistency might be caused by a [patch](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/cfnspec/spec-source/specification/000_cfn/1002_Lex_BotAlias_TextLogDestination_patch.json) which removed the property CloudWatch from TestLogDestination.

### Other Information

As part of the AWS::Lex::BotAlias field there seems to have been a patch in the past which removed the problematic TextLogDestinationProperty from a previous build. We should have made appropriate fixes to the documentation since then so we are requesting the removal of the patch found [here](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/cfnspec/spec-source/specification/000_cfn/1002_Lex_BotAlias_TextLogDestination_patch.json) 

### CDK CLI Version

2.17.0

### Language

Typescript, Python, .NET, Java, Go

**Comment by peterwoodworth** [comment]
PR has been linked to fix 🙂
