### ISSUE TITLE
(aws_iot): How to download a certificate pem

### ISSUE THREAD

**Issue by brucegl** [aws/aws-cdk#19577]
### General Issue

I'm struggling to work out how to download a certificate pem. Help appreciated

### The Question

I have created a cert with:
```
    const iotCertificate = new iot.CfnCertificate(this, "IoT Certificate", {
      status: "ACTIVE",
      certificateSigningRequest: fs.readFileSync(
        path.resolve("../iot-certs/cert.req"),
        "utf8"
      ),
    });
```
How do I download the pem in the context of CDK? This is as far as I got (not very far because it doesn't wait for iotCertificate to be created):
```
    var data: string = "-----Failed to load certificate-----";
    if (iotCertificate.certificatePem) {
      data = iotCertificate.certificatePem;
    }
    fs.writeFileSync(path.resolve("../iot-certs/cert.pem"), data, { encoding: "utf8" });
```

### CDK CLI Version

2.17.0 (build f9cd009)

### Node.js Version

v16.13.0

### OS

Linux Mint

### Language

Typescript

### Language Version

Version 4.5.5

**Comment by peterwoodworth** [comment]
Hey @brucegl,

There's no way to download the `certificatePem` property, or anything else through CDK for that manner. The CDK for the most part generates CloudFormation templates to provision and organize your infrastructure. Interacting with that infrastructure is best done with the APIs after you create the infrastructure with CDK.

In this case, the `certificatePem` property will only be defined if you defined that property yourself in the construct props of the Certificate. No communication with AWS is done for this resource beyond creating it in the synthesized CloudFormation template.

Hope this helps clear things up 🙂

**Comment by brucegl** [comment]
Thanks @peterwoodworth, I'll use the CLI for now
