### ISSUE TITLE
(aws-lambda-nodejs): short issue description

### ISSUE THREAD

**Issue by revmischa** [aws/aws-cdk#19580]
### What is the problem?

Fails to bundle, apparently parsing my tsconfig and looking for a module to import in `extends` looks in the wrong path.

I am using npm workspaces in a monorepo.

### Reproduction Steps

Create npm workspace
Create tsconfig.json with
```json
{
  "extends": "@tsconfig/node14/tsconfig.json",
}
```
Create NodejsFunction

### What did you expect to happen?

Used to bundle just fine in 2.7.0

### What actually happened?

```
Error: Cannot find module '/Users/cyber/dev/platform/@tsconfig/node14/tsconfig.json'
Require stack:
- /Users/cyber/dev/platform/node_modules/aws-cdk-lib/aws-lambda-nodejs/lib/util.js
- /Users/cyber/dev/platform/node_modules/aws-cdk-lib/aws-lambda-nodejs/lib/package-installation.js
- /Users/cyber/dev/platform/node_modules/aws-cdk-lib/aws-lambda-nodejs/lib/bundling.js
- /Users/cyber/dev/platform/node_modules/aws-cdk-lib/aws-lambda-nodejs/lib/function.js
- /Users/cyber/dev/platform/node_modules/aws-cdk-lib/aws-lambda-nodejs/lib/index.js
- /Users/cyber/dev/platform/node_modules/aws-cdk-lib/aws-lambda-nodejs/index.js
- /Users/cyber/dev/platform/node_modules/aws-cdk-lib/index.js
- /Users/cyber/dev/platform/node_modules/@serverless-stack/resources/dist/App.js
- /Users/cyber/dev/platform/node_modules/@serverless-stack/resources/dist/index.js
- /Users/cyber/dev/platform/packages/infra/.build/run.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at extractTsConfig (/Users/cyber/dev/platform/node_modules/aws-cdk-lib/aws-lambda-nodejs/lib/util.ts:196:56)
    at extractTsConfig (/Users/cyber/dev/platform/node_modules/aws-cdk-lib/aws-lambda-nodejs/lib/util.ts:202:12)
    at extractTsConfig (/Users/cyber/dev/platform/node_modules/aws-cdk-lib/aws-lambda-nodejs/lib/util.ts:202:12)
    at Object.getTsconfigCompilerOptions (/Users/cyber/dev/platform/node_modules/aws-cdk-lib/aws-lambda-nodejs/lib/util.ts:149:27)
    at Bundling.createBundlingCommand (/Users/cyber/dev/platform/node_modules/aws-cdk-lib/aws-lambda-nodejs/lib/bundling.ts:162:31)
    at new Bundling (/Users/cyber/dev/platform/node_modules/aws-cdk-lib/aws-lambda-nodejs/lib/bundling.ts:133:34)
```

It should be looking in `node_modules`

### CDK CLI Version

2.15.0 (build 151055e)

### Node.js Version

14

### OS

macos

### Language

Typescript

**Comment by revmischa** [comment]
Maybe related: if I remove the `extends` bit I can at least get farther, but now my `index.d.ts` files are not being included anymore and I get this sort of error:

```
packages/infra/lib/cognitoOidc/crypto.ts(1,22): error TS7016: Could not find a declaration file for module 'json-web-key'. '/Users/cyber/dev/platform/node_modules/json-web-key/lib/jwk.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/json-web-key` if it exists or add a new declaration (.d.ts) file containing `declare module 'json-web-key';`
```

Even if I have `declare module 'json-web-key';` in an `index.d.ts` file and `"files": ["./index.d.ts"],` in my tsconfig.json.
How can I include `.d.ts` files now with NodejsFunction?

**Comment by revmischa** [comment]
Also it seems to no longer be looking at the correct tsconfig.json for the package it's building (I'm in a monorepo)
And it's about 10x slower to build my functions
😢

**Comment by revmischa** [comment]
Disabling `preCompilation: true` seemed to solve my problems though

**Comment by corymhall** [comment]
@revmischa I know that there were some issues with `preCompilation` that were fixed pretty recently
so it may have been that it was working for you because `preCompilation` wasn't actually being run.

I believe the currently implementation just parses the `tsconfig.json` file and does not support
resolving any `extends`.

If you are not using any new experimental features that are only supported by `tsc` then
`preCompilation` is not needed.

**Comment by revmischa** [comment]
Okay thanks! Yeah I think I had it enabled and it wasn't actually being used until I upgraded.
