### ISSUE TITLE
UserData and Metadata fields are not getting populated properly

### ISSUE THREAD

**Issue by CloudDevBe** [aws/aws-cdk#1958]
I am using CDK version 0.20.0 (build cbeea75). I created a json template(application.template) which works fine, creates cloud formation stack and run application properly
I am trying to convert that template into cdk code
Right now I am facing issue with userdata and metadata fields. They are not getting properly populated in template section of Cloud formation stack.
I am trying to add/update metadata and userdata fields using autoscaling groups adduserdata() and addMetaData() methods. Attaching following files for reference.
1) Generatedcloudformationcdk.template: Generated template after deploying CDK application.
2) application.template: I am trying to extract userdata and metadata fields from this file.
3) Java files.

Please tell me, how to add/update userdata and metadata fields so that it will get properly populated in the template section of the cloud formation stack and application will run properly.

[cdk issue.zip](https://github.com/awslabs/aws-cdk/files/2932853/cdk.issue.zip)

**Comment by skinny85** [comment]
Gist with the code: https://gist.github.com/CloudDevBe/93d6be8011edd197f2357a4cc1c47cce

**Comment by sam-goodwin** [comment]
Can you try shrinking down your example to a small re-producible snippet demonstrating what you are trying to achieve? There's too much going for me to understand. For example, you seem to be doing a lot of json/yaml and including templates etc.

You can add user data to your launch config by calling addUserData:

https://github.com/awslabs/aws-cdk/blob/615ecd4f428d77dbb830e7f39b7f9a5d4dc804cd/packages/%40aws-cdk/aws-autoscaling/lib/auto-scaling-group.ts#L339-L345

**Comment by CloudDevBe** [comment]
@sam-goodwin There are few fields like userdata, metadata,etc. which I want to extract from the json template. So, to maintain consistency with all fields, I didn’t add userdata directly and extracted it from json template. Also, Userdata didn’t get populated in json format in template section of Cloud formation stack. So, I converted it to yaml format as shown below and added it by calling addUserData().
`
Fn::Base64:
  Fn::Join:
  - "\n"
  - - "#!/bin/bash -ex"
    - "yum install -y aws-cfn-bootstrap"
    - Fn::Join:
      - " "
      - - "/opt/aws/bin/cfn-init"
        - "--verbose"
        - "--stack"
        - Ref: "AWS::StackName"
        - "--region"
        - Ref: "AWS::Region"
        - "--resource"
        - "EcsInstanceLc"
`
I was expecting it to be in above format but same extra fields are automatically created (Please refer Generatedcloudformationcdk.template)
Also, please check metadata field.

**Comment by sam-goodwin** [comment]
I understand you're having a problem with the user/meta data for ASGs, but your gist is too large and complicated for me to debug, sorry. Please create a small, simple snippet illustrating just the part you're confused about (strip out all the noise like reading files, parsing json/yaml, creating other resources etc.).

Ideally, you'd provide a small java sample containing *only* the code you're having a problem with and a JSON/YAML snippet containing *only* the section of the template that is wrong.

**Comment by CloudDevBe** [comment]
//Created Autoscaling group
AutoScalingGroup autoScalingG = new AutoScalingGroup(this, "EcsInstanceLc", AutoScalingGroupProps.builder().withMinSize(minsize).withMaxSize(maxsize).withKeyName("betestuser").withInstanceType(it) .withAllowAllOutbound(true).withMachineImage((IMachineImageSource) gi).withDesiredCapacity(instancecount).withVpc(vpc).build());
       
 //jsonAsYaml is userdata in yaml format which is shown in previous comment. 
      String jsonAsYaml = new YAMLMapper().writeValueAsString(jsonNodeTree);
      
    //Added userdata via addUserData(jsonAsYaml)
       autoScalingG.addUserData(jsonAsYaml);    

We expected same userdata(mentioned in previous comment) to be populated in template section of Cloud formation stack but after deploying, it shows following:

UserData:
        Fn::Base64:
          Fn::Join:
            - ""
            - - |-
                #!/bin/bash
                ---
                Fn::Base64:
                  Fn::Join:
                  - "\n"
                  - - "#!/bin/bash -ex"
                    - "yum install -y aws-cfn-bootstrap"
                    - Fn::Join:
                      - " "
                      - - "/opt/aws/bin/cfn-init"
                        - "--verbose"
                        - "--stack"
                        - Ref: "AWS::StackName"
                        - "--region"
                        - Ref: "AWS::Region"
                        - "--resource"
                        - "EcsInstanceLc"

                echo ECS_CLUSTER=
              - Ref: EcsCluster97242B84
              - >-2
                 >> /etc/ecs/ecs.config
                sudo iptables --insert FORWARD 1 --in-interface docker+ --destination 169.254.169.254/32 --jump DROP

                sudo service iptables save

                echo ECS_AWSVPC_BLOCK_IMDS=true >> /etc/ecs/ecs.config

**Comment by SoManyHs** [comment]
Related: #1711

**Comment by SoManyHs** [comment]
This is pretty closely related to https://github.com/aws/aws-cdk/issues/1711, so I'll close this one as a dupe for now and we'll track it there. Feel free to comment if you have any thing more specific @CloudDevBe !
