### ISSUE TITLE
aws_lambda: Version documentation contains non-existant `addVersion` API reference

### ISSUE THREAD

**Issue by murphm8** [aws/aws-cdk#19594]
### link to reference doc page

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda.Version.html

### Describe your issue?

The example in this document uses `function.addVersion` which no longer exists in the `Function` API.  What is the alternative way to create a new version of a Function manually?

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda.Version.html

**Comment by peterwoodworth** [comment]
According to the V1 docs, we will want to use `function.currentVersion` to represent the version of that function.

https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-lambda.Function.html#addwbrversionname-codesha256-description-provisionedexecutions-asyncinvokeconfigspan-classapi-icon-api-icon-deprecated-titlethis-api-element-is-deprecated-its-use-is-not-recommended%EF%B8%8Fspan

Thanks for letting us know our docs are using a deprecated method, we'll get that fixed up 🙂
