### ISSUE TITLE
(aws-cognito): `UserPool` constructor adds an incorrect Lambda permission

### ISSUE THREAD

**Issue by Tietew** [aws/aws-cdk#19604]
### What is the problem?

When I specify `lambdaTriggers` in `UserPool`, the function's lambda permission should have a `SourceArn` condition with the UserPool's ARN.

But `UserPool` constructor adds a lambda permisson without `SourceArn` condition.
`UserPool.addTrigger` method adds a correct permission with `SourceArn`.

This seems to be caused that the constructor code calls `addLambdaPermission` before assigning `this.userPoolArn`.

### Reproduction Steps

``` typescript
const handler = new lambda.Function(this, 'Handler', { ... });
new cognito.UserPool(this, 'UserPool', {
  lambdaTriggers: {
    postConfirmation: handler,
  },
  ...
});
```

### What did you expect to happen?

Following `Lambda::Permission` resource is created:
``` json
    "HandlerPostConfirmationCognitoXXXXXXXX": {
      "Type": "AWS::Lambda::Permission",
      "Properties": {
        "Action": "lambda:InvokeFunction",
        "FunctionName": {
          "Fn::GetAtt": [
            "HandlerXXXXXXXX",
            "Arn"
          ]
        },
        "Principal": "cognito-idp.amazonaws.com",
        "SourceArn": {
          "Fn::GetAtt": [
            "UserPoolXXXXXXXX",
            "Arn"
          ]
        }
      },
      "Metadata": {
        "aws:cdk:path": "..."
      }
    },
```

### What actually happened?

Following `Lambda::Permission` resource was created:
``` json
    "HandlerPostConfirmationCognitoXXXXXXXX": {
      "Type": "AWS::Lambda::Permission",
      "Properties": {
        "Action": "lambda:InvokeFunction",
        "FunctionName": {
          "Fn::GetAtt": [
            "HandlerXXXXXXXX",
            "Arn"
          ]
        },
        "Principal": "cognito-idp.amazonaws.com"
      },
      "Metadata": {
        "aws:cdk:path": "..."
      }
    },
```

### CDK CLI Version

2.18.0

### Node.js Version

14.19.0

### OS

Linux

### Language

Typescript

**Comment by corymhall** [comment]
It looks like the solution might be to use `Lazy` with the `sourceArn`.

It seems like this issue impacts a significant number of customers, and I've tagged it as P1, which means it should be on our near-term roadmap.

We welcome community contributions! If you are able, we encourage you to [contribute](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) a bug fix or new feature to the CDK. If you decide to contribute, please start an engineering discussion in this issue to ensure there is a commonly understood design before submitting code. This will minimize the number of review cycles and get your code merged faster.
