### ISSUE TITLE
(aws_s3): serverAccessLogsBucket should use Bucket Policy instead of Bucket ACL

### ISSUE THREAD

**Issue by ikendoit** [aws/aws-cdk#19603]
### Description

Hello AWS-CDK developers,

I have a question about CDK implementation for setting up serverAccessLogsBucket
According to this doc: https://docs.aws.amazon.com/AmazonS3/latest/userguide/enable-server-access-logging.html

AWS recommends using Bucket Policy, rather than bucket ACL
However, when our team used aws-cdk to define bucket A as target-access-log-bucket for bucket B, we learned that the CDK is modifying bucket ACL on bucket A

Tracing the cdk code, that is indeed the case:
https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-s3/lib/bucket.ts#L2060

Tracking the history, that code was added in 2020, while AWS's recommendation to use Bucket Policy was put in place in December 2021. 

My question is: Is there a plan from aws-cdk-team to update the aws-cdk s3 to use Bucket Policy instead of Bucket ACL?

### Use Case

Our system has strict SCP that blocks s3:PutBucketACL, so learning that this behaviour requires that action causes inconvenience for us.

### Proposed Solution

One way can be: 
A. Update the [props of `Bucket` Construct](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-s3/lib/bucket.ts#L1650) to accept a new property `serverAccessLogsUsePolicy: boolean` 
      By default, `serverAccessLogsUsePolicy = true` ( to follow best practice recommendation from AWS )

B. Update [`Bucket.allowLogDelivery()` method](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-s3/lib/bucket.ts#L2055) to accept new parameters `serverAccessLogsUsePolicy`, `sourceBucketName`, `logFilePrefix` 
B-1. If `serverAccessLogsUsePolicy` is false, continue using ACL like how the module currently works 
B-2.1. Else, continue with setting Bucket Policy flow: Set up the Policy on `props.serverAccessLogsBucket` bucket instance using method parameters `sourceBucketName` and `logFilePrefix` to build up a statement that resembles the one in https://docs.aws.amazon.com/AmazonS3/latest/userguide/enable-server-access-logging.html#grant-log-delivery-permissions-bucket-policy 
B-2.2. Use `Bucket.addToResourcePolicy(iam.PolicyStatement)` to add the new generated statement in previous step. 

I suspect there will be problems of migrations where users want to migrate existing bucket from using ACL to Policy. Those problems are out of scopes of this proposed solution.

Additionally, setting `serverAccessLogsUsePolicy = true` by default can cause disturbance to existing users, so there needs to be more thoughts to see whether we want it true by default. We will definitely want to start off with setting it to false if users impact are too considerable. 

### Acknowledge

- [X] I may be able to implement this feature request
- [X] This feature might incur a breaking change

**Comment by bsweeney-gingerio** [comment]
Until a proper fix is provided, there is a workaround in TypeScript to override private methods. Optionally, extend the `aws_s3.Bucket` class. Then, override the [`allowLogDelivery`](https://github.com/aws/aws-cdk/blob/fd306ee05cfa7ebaa8d997007500d89d62868897/packages/%40aws-cdk/aws-s3/lib/bucket.ts#L2066-L2078) method:

```typescript
export class BaseS3Bucket extends Bucket {
  constructor(scope: Construct, id: string, props?: BucketProps) {
    super(scope, id, {
      ...props,
      objectOwnership: ObjectOwnership.BUCKET_OWNER_ENFORCED,
    )
  }
}

(BaseS3Bucket.prototype as any)["allowLogDelivery"] = function (
  this: BaseS3Bucket
) {
  return null;
};
```

The method does not take any arguments, so I don't see a way to add to the resource policy based on the source bucket. This will get past the error on failure to modify the ACL, though.

**Comment by otaviomacedo** [comment]
Unfortunately, we have to keep the ACL and the bucket ownership in place because at least one service ([CloudFront]) needs these things. Closing for now, but feel free to reopen if CloudFront catches up.

[CloudFront]: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/AccessLogs.html#access-logs-choosing-s3-bucket
