### ISSUE TITLE
(aws_backup): enableContinuousBackup ts(2345) error

### ISSUE THREAD

**Issue by axelra82** [aws/aws-cdk#19611]
### What is the problem?

The following code from [2.18.0 aws_backup overview documentation](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_backup-readme.html)
```
declare const plan: backup.BackupPlan;
plan.addRule(new backup.BackupPlanRule({
  enableContinuousBackup: true,
  deleteAfter: Duration.days(14),
}));
```

produces the following error

```
Argument of type '{ enableContinuousBackup: boolean; deleteAfter: Duration; }' is not assignable to parameter of type 'BackupPlanRuleProps'.
  Object literal may only specify known properties, and 'enableContinuousBackup' does not exist in type 'BackupPlanRuleProps'.ts(2345)
```

![code](https://user-images.githubusercontent.com/986301/160650313-c9ee9d7e-2414-4142-821d-c0cf8ab68121.png)

### Reproduction Steps

Stack

```
import {
	aws_backup as backup,
	Stack,
	StackProps,

} from 'aws-cdk-lib';
import { Construct } from 'constructs';

declare const plan: backup.BackupPlan;
export default class ClientStack extends Stack {
	constructor(
		scope: Construct,
		id: string,
		props: StackProps,
	) {
		super(scope, id, props);

		plan.addRule(
			new backup.BackupPlanRule({
				enableContinuousBackup: true, // TS error
				deleteAfter: Duration.days(14),
			}),
		);
	}
}
```

### What did you expect to happen?

To be able to configure continuous backup and point-in-time restores (PITR) as per [2.18.0 aws_backup overview documentation](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_backup-readme.html) 

### What actually happened?

Using example code provided in [2.18.0 aws_backup overview documentation](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_backup-readme.html) , TypeScript shows error:

```
Argument of type '{ enableContinuousBackup: boolean; deleteAfter: Duration; }' is not assignable to parameter of type 'BackupPlanRuleProps'.
  Object literal may only specify known properties, and 'enableContinuousBackup' does not exist in type 'BackupPlanRuleProps'.ts(2345)
```

### CDK CLI Version

2.18.0 (build 75c90fa)

### Node.js Version

16.13.1

### OS

macOS Monterey 12.2.1 (21D62)

### Language

Typescript

### Language Version

TypeScript (4.5.4)

**Comment by peterwoodworth** [comment]
I can't reproduce this @axelra82,

[Our docs](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_backup.BackupPlanRuleProps.html#enablecontinuousbackup) show that this property exists on the latest version

Make sure you don't have any cdk modules in your `context.json` other than `aws-cdk-lib` as a dependency and `aws-cdk` as a dev dependency, and that they're the same version `2.18.0`. Reinstall your packages for good measure once you've verified this is the case

**Comment by axelra82** [comment]
I feel silly now 😅 I only ran the `npm install -g aws-cdk` as per terminal instructions (when running `cdk` commands) and completely forgot about updating `package.json`.

I know it's not an excuse, I've just had to much on my plate lately... Apologies for any inconvenience!
