### ISSUE TITLE
(DockerImage Build): Bundling is Not Skipped During List or When Excluded by `--exclusively`

### ISSUE THREAD

**Issue by joel-aws** [aws/aws-cdk#19615]
### What is the problem?

When running `cdk ls` or `cdk synth my-specific-stack --exclusively`, stacks that use `DockerImage.from_build` are bundled, which can add a lot of time for complex docker builds, even if cached.

### Reproduction Steps

Run:
* `cdk ls`
* `cdk synth stack-one --exclusively --quiet`

`app.py`:
```python
from aws_cdk import (
    App,
    Duration,
    Stack,
    Stage,
    BundlingOptions,
    DockerImage,
    aws_s3 as s3,
    aws_s3_deployment as s3_deploy,
    aws_sns as sns,
    aws_sqs as sqs,
    aws_sns_subscriptions as subs,
)

from constructs import Construct

app = App()


class StackOne(Stack):
    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        queue = sqs.Queue(
            self,
            "DelMeNowQueue",
            visibility_timeout=Duration.seconds(300),
        )

        topic = sns.Topic(self, "DelMeNowTopic")

        topic.add_subscription(subs.SqsSubscription(queue))


class StackTwo(Stack):
    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        bucket = s3.Bucket(self, "bucket")

        s3_deploy.BucketDeployment(
            self,
            "ui-deployment",
            retain_on_delete=False,
            sources=[
                s3_deploy.Source.asset(
                    asset_hash="abc",
                    path=f"docker",
                    bundling=BundlingOptions(
                        image=DockerImage.from_build(
                            path="docker",
                        ),
                        command=[
                            "/bin/bash",
                            "-c",
                            " &&".join(
                                [
                                    "printenv > env.txt",
                                    "cp env.txt /asset-output",
                                ]
                            ),
                        ],
                    ),
                )
            ],
            destination_bucket=bucket,
            memory_limit=1024,
        )


StackOne(app, "stack-one")
StackTwo(app, "stack-two")

app.synth()
```

`docker/Dockerfile`:
```dookerfile
FROM public.ecr.aws/sam/build-nodejs14.x
RUN sleep 10 # Change this and the contents won't be cached
```

### What did you expect to happen?

I expected assets to not be bundled during an `ls` and when not included in a `synth` that excludes the stack with the resource via `--exclusively`.

### What actually happened?

Docker output is clearly seen in the console during an `ls` and `synth` that excludes it.

### CDK CLI Version

2.18.0

### Node.js Version

v16.3.0

### OS

macOS 11.6.5

### Language

Python

**Comment by peterwoodworth** [comment]
Hey @joel-aws, we're tracking this issue here https://github.com/aws/aws-cdk/issues/6743

Seems it hasn't got much attention unfortunately, please add a comment there and give a thumbs up reaction to the issue as that helps us decide what to work on.

**Comment by joel-aws** [comment]
@peterwoodworth -- thanks for pointing that ticket out. I think there's two parts to this:
* The issue you identified, where all Stacks need to exists (#6743 looks into this)
* The issue where Bundling is done during a `ls` or if excluded during a `synth` -- I don't think the ticket you linked attempts to address this, right?

**Comment by peterwoodworth** [comment]
Thanks for letting me know I didn't address all your concerns.

[This comment describes](https://github.com/aws/aws-cdk/issues/19157#issuecomment-1051422878) why asset bundling is done during synth (and thus `ls`, because `ls` needs to synthesize to know which stacks there are). So currently, I think those issues you have are not possible for us to address
