### ISSUE TITLE
(aws-apigatewayv2-alpha): Set route throttling with HttpStage

### ISSUE THREAD

**Issue by TkinterinShanghai** [aws/aws-cdk#19626]
### What is the problem?

Unlike the module `aws_apigateway` where I would just do
```javascript
const api = new apigateway.RestApi(this, 'hello-api');
const plan = api.addUsagePlan('UsagePlan', {
  name: 'Easy',
  throttle: {
    rateLimit: 10,
    burstLimit: 2
  }
});
```
there doesnt seem to be an equivalent way of doing this in `aws-apigatewayv2-alpha`.  

### Reproduction Steps

I created an HTTP Api 

```javascript
export class APIConstruct extends Construct {
  public api: HttpApi;
  constructor(scope: Construct, id: idType, authorizer: HttpUserPoolAuthorizer) {
    super(scope, id);
    const throtting = new UsagePlan(this, "Throttling", {
      throttle: { burstLimit: 999, rateLimit: 99 },
    });
    this.api = new HttpApi(this, id, {
      apiName: id,
      defaultAuthorizer: authorizer,
    });
  }
}
```

and tried to just add throttling in the same scope, hoping that it would automatically apply to the only api gateway specified

```javascript
const throtting = new UsagePlan(this, "TypiRateLimiting", { throttle: { burstLimit: 999, rateLimit: 99 } });
```

### What did you expect to happen?

Have a method `.addUsagePlan` on the Http Api class or having a field in `props` that allows me to link the `UsagePlan` to the Api.

### What actually happened?

Throttling was not configured for Api

### CDK CLI Version

2.17.0

### Node.js Version

16.12

### OS

Windows

### Language

Typescript

**Comment by peterwoodworth** [comment]
Hey @TkinterinShanghai,

The UsagePlan option is available in the apigateway package and not v2 because [CloudFormation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_ApiGatewayV2.html) makes the distinction between v1 and v2 here. CloudFormation has a UsagePlan resource for v1, and no such resource for V2. So there's not much we can do here

**Comment by peterwoodworth** [comment]
I'm not too familiar with these services, but I believe there is no usage plan construct because the functionality lies somewhere else in v2, see [here](https://github.com/serverless/serverless/issues/8617).

If you still believe there should be a UsagePlan construct for CloudFormation, then I recommend opening an issue [with the CloudFormation coverage roadmap](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues)

**Comment by TkinterinShanghai** [comment]
I just don't see the Option to add a Usage Plan/Throttling at all. I'd be happy with any way of doing this as long as it's feasible. I think adding a method to the Api, the Stage or having a Construct by itself would all be intuitive ways of implementing this. If adding throttling to the Http Api Gateway is possible via the website, I would expect Cdk v2 to also be able to handle that. I still haven't found that option. Maybe it's just well hidden and I'm not aware it exists

**Comment by TkinterinShanghai** [comment]
Thanks, you put me on the right track. This worked: 

```javascript
const cfnStage = api.defaultStage?.node.defaultChild as CfnStage; // api is of type HttpApi
cfnStage.addPropertyOverride("DefaultRouteSettings", {ThrottlingBurstLimit: 1500, ThrottlingRateLimit: 1000});
```

But it would be nice if this could be incorporated into ApiGatewayV2, as I think it is a somewhat important missing feature and this way of doing it is pretty hacky

**Comment by peterwoodworth** [comment]
I hear you @TkinterinShanghai, I've created a PR for this feature 🙂

**Comment by TkinterinShanghai** [comment]
This seems to be a bug elsewhere but creating a stage doesnt work because "Stage already exists", even when setting createDefaultStage to false in the HttpApi class. But this bug affects this fix, because the fix relies on the Stage working. So I think additionally having a method such as createDefaultThrottling on the HttpApi or  a setThrottling method on the HttpStage would work even with the current bug.
