### ISSUE TITLE
(aws-lambda-nodejs): Export Bundling class for esbuild functions

### ISSUE THREAD

**Issue by mlkirkpatrick** [aws/aws-cdk#19632]
### Description

Since #17707, deep imports are no longer allowed. Since the `Bundling` class is not exported, a large portion of the esbuild bundling logic is inaccessible for users unless they consume/extend `NodejsFunction` directly. Exporting this class would give users more control.

### Use Case

When developing a construct library, one may want to extend lambda functionality. A simple example would be a construct which takes an `esbuild` flag as a prop. If the flag is true, use esbuild bundling; otherwise, use `Code.fromAsset` or similar. 

Extending `NodejsFunction` won't work because there is no way to prevent esbuild bundling and use different bundling logic.
Extending `lambda.Function` won't work because the esbuild logic is not accessible.

Therefore, the current setup requires nested properties or two constructs to achieve similar functionality. Exporting the Bundling class would allow construct developers to create a single construct which handles both scenarios.

### Proposed Solution

Update [aws-lambda-nodejs/lib/index.ts](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-lambda-nodejs/lib/index.ts) to include new export:

```
export * from './function';
export * from './types';
export * from './bundling';
```

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by corymhall** [comment]
@mlkirkpatrick i'm not sure this is something we want to do. The bundling feature is an
implementation detail and not something we want to expose as it's own API.

I would recommend looking at a separate library like [@mrgrain/cdk-esbuild](https://constructs.dev/packages/@mrgrain/cdk-esbuild/v/3.3.0?lang=typescript)

**Comment by martinnabhan** [comment]
I can confirm using cdk-esbuild works fine!

Changing
```typescript
import { Bundling } from 'aws-cdk-lib/lib/aws-lambda-nodejs/lib/bundling.js';

code: Bundling.bundle({
  architecture: Architecture.X86_64,
  depsLockFilePath: `${__dirname}/../../package-lock.json`,
  entry: `${__dirname}/../functions/basicAuth.ts`,
  projectRoot: `${__dirname}/../../`,
  runtime: Runtime.NODEJS_14_X,
}),
```
to
```typescript
import { TypeScriptCode } from '@mrgrain/cdk-esbuild';

code: new TypeScriptCode('src/functions/basicAuth.ts', {
  buildOptions: {
    minify: true,
  },
}),
```
did the trick!

**Comment by Samrose-Ahmed** [comment]
This was requested here too: https://github.com/aws/aws-cdk/issues/14215. Why is Bundling considered an implementation detail?

**Comment by hugomallet** [comment]
+1
