### ISSUE TITLE
(ECS): Blue-green deployment using CDK

### ISSUE THREAD

**Issue by jayPJ** [aws/aws-cdk#19645]
### General Issue

How to implement blue green deployment using cdk , as we do using aws console selecting deploy to be ecs(blue/green)

### The Question

How to implement blue green deployment using cdk , as we do using aws console selecting deploy to be ecs(blue/green)

### CDK CLI Version

1.110.1

### Node.js Version

14.17.6

### OS

Windows 10

### Language

Typescript

**Comment by peterwoodworth** [comment]
hey @jayPJ,

the long story short is that the CDK doesn't really support this yet. This is a very highly requested feature, but really tricky for us to implement. Please see [this thread](https://github.com/aws/aws-cdk/issues/1559) for more information and take further concerns there. Thanks, and sorry for the experience here

**Comment by jayPJ** [comment]
Thanks for the reply.
