### ISSUE TITLE
aws-lambda: FunctionProps's Environment is map of any

### ISSUE THREAD

**Issue by jasdel** [aws/aws-cdk#1964]
The aws-lambda module's [FuncitonProp's Environment property](https://github.com/awslabs/aws-cdk/blob/master/packages/%40aws-cdk/aws-lambda/lib/function.ts#L67-L73) is defined as a map of any. I think this is incorrect type for a property that is used for users to specify the environment variables. 

I think FunctionProp.Environment property should be a map of string. Nearly all OS environment variable values are always string type, and map of any is confusing for users of language bindings generated from the CDK's source.

I suggest changing the type of this any similar parameters to be map of string.

**Comment by sam-goodwin** [comment]
I think this is a relic of when we supported both `string` and `cdk.Token`. Since `cdk.Token` is passed around stringified, it should be safe to adjust this to `{[key: string]: string}`. It also more accurately models environment variables which are always consumed as strings.

**Comment by nija-at** [comment]
This has been long fixed. The environment property type is now `{ [key: string]: string }`
