### ISSUE TITLE
aws-lambda Code.Asset static method name is awkward

### ISSUE THREAD

**Issue by jasdel** [aws/aws-cdk#1965]
The `Asset` static method in aws-lambd module's `Code` class is a little awkward. From the name of the method its not clear/obvious that this static method constructs a Code from a Asset's folder. It would be more clear if the `Asset` method was named to something more similar to `FromDirectory`.  

This naming change would also be consistent with other aspects of the CDK such as aws-ecs module's `ContainerImage` Class's static method `FromDockerHub`.

**Comment by sam-goodwin** [comment]
I agree - the generic 'asset' can be confusing. 

We are working on an overhaul of the assets system (https://github.com/awslabs/aws-cdk/pull/1954, https://github.com/awslabs/aws-cdk/pull/1884, https://github.com/awslabs/aws-cdk/pull/1895) which will also incorporate builds of the function source code into an asset. Now would be a good time to consider re-naming these methods to be more descriptive and consistent.

**Comment by jansony1** [comment]
aggree
