### ISSUE TITLE
Allow setting removal policy for BucketNotificationsHandler Lambda log group

### ISSUE THREAD

**Issue by toxygene** [aws/aws-cdk#19726]
### Describe the feature

I would like the ability to specify a log stream, or the removal_policy for the log stream, that is used by the BucketNotificationsHandler.

### Use Case

If I understand it correctly, in order to add an S3 bucket event notification, CDK has to create a Lambda function. That Lambda automatically creates a log group. The log group does not have a removal policy, so `cdk destroy` does not remove it. I would like to be able to remove them automatically.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.17.0

### Environment details (OS name and version, etc.)

Darwin ML11085 19.6.0 Darwin Kernel Version 19.6.0: Thu Jan 13 01:26:33 PST 2022; root:xnu-6153.141.51~3/RELEASE_X86_64 x86_64

**Comment by rix0rrr** [comment]
The Log Group is not created by CDK, but by Lambda, so this is potentially hard.

**Comment by toxygene** [comment]
It appears that, if a Log Stream with a name of `/aws/lambda/{lambda function name}` already exists, the Lambda will use it for logging. I have seen other services (eg [Serverless Framework](https://www.serverless.com/)) use this detail to create Log Groups with custom settings, such as removal policies and retention periods. I've tested this myself with CloudFormation and confirmed it works as of this writing.

I'm not certain that this is documented behavior, so using it could be potentially risky, but it is an option currently.

([I sure would be nice if it was supported by CF](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/147))
