### ISSUE TITLE
aws_dynamodb: allow point_in_time_recovery to be IResolvable

### ISSUE THREAD

**Issue by rittneje** [aws/aws-cdk#19748]
### Describe the feature

The `point_in_time_recovery` field passed to the aws_dynamodb.Table constructor should also permit an `IResolvable` to be passed.

The underlying `CfnTable` resource already allows an `IResolvable` for `point_in_time_recovery_enabled`. https://docs.aws.amazon.com/cdk/api/v1/python/aws_cdk.aws_dynamodb/CfnTable.html#aws_cdk.aws_dynamodb.CfnTable.PointInTimeRecoverySpecificationProperty

### Use Case

We want to use an Aspect to check that developers either enable point-in-time recovery for our production account, or explicitly disable it for all accounts. Currently, this is not feasible for two reasons:
1. We cannot distinguish explicit disable from implicit disable.
2. We cannot just hard-code `True` because it is contingent upon the account.

Instead, we want to make two implementations of `IResolvable`. Then the Aspect can simply check that `point_in_time_recovery_enabled` is set to an instance of once of these two classes.

### Proposed Solution

Fix the `Table` constructor to allow for `IResolvable` for `point_in_time_recovery`. If provided, it will generate the corresponding `PointInTimeRecoverySpecificationProperty` instance.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

1.140.0

### Environment details (OS name and version, etc.)

Alpine 3.15

**Comment by skinny85** [comment]
Hi @rittneje,

thanks for opening the issue. I don't think that's something we can do though (we don't allow `IResolvable` properties in our Layer 2 constructs).

I wonder - why can't do distinguish an explicit disable from an implicit one? One is `undefined`, and the other is the `PointInTimeRecoverySpecificationProperty` with the `pointInTimeRecoveryEnabled` set to `false`, right?

Thanks,
Adam

**Comment by rittneje** [comment]
@skinny85 When testing I believe we found they came out to be the same in L1. And regardless, I don't really feel comfortable relying on what CDK chooses to do implicitly. Like if tomorrow it decided that not setting `point_in_time_recovery` translated to explicitly setting it to `False`, our check would be moot.

**Comment by skinny85** [comment]
@rittneje what if the code in question in `Table` here:  https://github.com/aws/aws-cdk/blob/1fdf1223304e15d905723553a40640b8bcb0ec56/packages/%40aws-cdk/aws-dynamodb/lib/table.ts#L1186-L1186

was changed to be

```ts
      pointInTimeRecoverySpecification: props.pointInTimeRecovery === undefined ? { pointInTimeRecoveryEnabled: props.pointInTimeRecovery } : undefined,
```

Would that make it possible to write your Aspect, using the L1?

**Comment by rittneje** [comment]
It would certainly help, in that we would be able to distinguish explicit `False` from "unset".

However, I think a more robust solution would be for `point_in_time_recovery` to be deprecated, and instead allow us to pass an interface similar to `PointInTimeRecoverySpecificationProperty`. There should also be a getter for this property. Then we can just implement that interface, and our Aspect just verifies that the Table is either using an instance of our class, or the "disabled" implementation that CDK would presumably provide.

**Comment by skinny85** [comment]
I feel like hinder usability a little too much, to cater to this pretty-specific use case.

Let's start with the change I mentioned, and see if it unblocks you: https://github.com/aws/aws-cdk/pull/19757

Thanks,
Adam

**Comment by rittneje** [comment]
I'm not sure that wanting to enable PITR only in production is a particularly unusual use case.

**Comment by skinny85** [comment]
I meant the fact that you want to distinguish between "explicitly disabled" and "not set at all" - that's the unusual part here.

**Comment by rittneje** [comment]
@skinny85 Thinking about this more, your change will not help with this use case ("enable PITR in prod only") at all.

Even if our Aspect sees that it was explicitly set to `False`, it cannot tell what logic went into that. It is possible that the stack author tried to implement "prod only" themselves, but we would have no way of verifying that this logic was written properly.

The only workable solution is what I described earlier. We need to be able to pass our "strategy" to the Table constructor, so our Aspect can then verify that you are using one of the two approved strategies. It's gaps like this that force people to make L3 constructs, even though this is discouraged.

Until then, there are two workarounds I can see.
1. Implement `IResolvable` and force developers to set the field in the L1. Then the Aspect confirms that it is set to one of our two classes.
2. Create two additional Aspects - one for each "strategy" - and apply exactly one to the Table itself. Then our checker Aspect modifies the L1 table to set `point_in_time_recovery_specification` as per the "strategy" Aspect.

**Comment by skinny85** [comment]
Can you explain why this simple solution won't work for you?

1. In your production Stacks, check whether `point_in_time_recovery_specification` is set (to `true`), and fail if it's not.
2. In the non-production Stacks, do the opposite - fail if `point_in_time_recovery_specification` is set to `true` or `undefined`, pass if it's explicitly set to `false` (https://github.com/aws/aws-cdk/pull/19757 will allow you to do this).

I feel like this satisfies your original requirements - but I could definitely be missing something.

**Comment by rittneje** [comment]
@skinny85 We have one cdk.py, which is deployed to both the lower test account, as well as production. We do not want to wait until we are deploying to production to have the check fail, so even when we are deploying to the lower account, it needs to be able to "predict" what is going to happen in prod, and gate accordingly.

With your change, we can now tell whether they bothered to explicitly pass `point_in_time_recovery` to the constructor at all. However, since this is just a boolean, it cannot convey general intent. If the Aspect sees `False`, it still cannot distinguish an intentionally hard-coded `False` (meaning "no PITR in any account") from an improperly implemented conditional that was supposed to mean "prod only" but ends up disabling it there too.

Also, it is not the case that _all_ tables should have PITR enabled in prod. There are legitimate cases where it is unnecessary. So we can't enforce "if prod then enabled" in the Aspect anyway.

**Comment by skinny85** [comment]
In your `cdk.py`, do you have separate Stacks for test, and production (which is a [good idea](https://www.endoflineblog.com/cdk-tips-05-have-a-stack-instance-per-deployed-stack)), or do you have one Stack for both?

If the latter, how does your Aspect know whether it's in production, or in test?

**Comment by rittneje** [comment]
Since test and production are completely separate accounts, there is a single Stack instance in cdk, but it is either configured for the test account, or the prod account. The link you shared does not make sense to me, and actually seems like poor practice, because the deployment job for the test account does not have production credentials (nor should it), To have CDK actually define two stacks will not work, because then `cdk deploy` would try to deploy to production.

The Aspect knows based upon the Stack's `account` (which you can get via `core.Stack.of`). This in turn is derived from the deployment job already knowing which account it is for.

**Comment by skinny85** [comment]
> Since test and production are completely separate accounts, there is a single Stack instance in cdk, but it is either configured for the test account, or the prod account. The link you shared does not make sense to me, and actually seems like poor practice, because the deployment job for the test account does not have production credentials (nor should it).

Nobody says it should.

> To have CDK actually define two stacks will not work, because then `cdk deploy` would try to deploy to production.

You do the deployment by invoking `cdk deploy TestStack` or `cdk deploy ProdStack`. This is explained in the article.

> The Aspect knows based upon the Stack's `account` (which you can get via `core.Stack.of`). This in turn is derived from the deployment job already knowing which account it is for.

Then I don't understand what's the issue.

1. If it's a prod account, and `pointInTimeRecovery` should be set for it, but it's not: fail.
2. If it's not prod, and `pointInTimeRecovery` is set: fail.

Again, in my opinion, you'll have all of the information you need once https://github.com/aws/aws-cdk/pull/19757 lands. Deprecating `pointInTimeRecovery` and changing it to an interface to cater to this use case is not realistic, I'm afraid.

**Comment by rittneje** [comment]
> You do the deployment by invoking cdk deploy TestStack or cdk deploy ProdStack.

This is not a realistic way to deploy, once you have multiple (actual) stacks. At that point, you have to do `cdk deploy '*'`, and will encounter the issues I mentioned. Consequently, that article seems like pretty bad advice.

> Then I don't understand what's the issue.

I already explained why the approach you are outlining here is not desirable or workable for this use case. https://github.com/aws/aws-cdk/issues/19748#issuecomment-1089205109

> Deprecating pointInTimeRecovery and changing it to an interface to cater to this use case is not realistic, I'm afraid.

Ultimately that is the CDK team's decision to make I guess. All I can tell you is without this change, we have no choice but to drop down to L1. Your change in #19757 alone unfortunately is not of use.

**Comment by skinny85** [comment]
> > You do the deployment by invoking cdk deploy TestStack or cdk deploy ProdStack.
> 
> This is not a realistic way to deploy, once you have multiple (actual) stacks. At that point, you have to do `cdk deploy '*'`, and will encounter the issues I mentioned. Consequently, that article seems like pretty bad advice.

You can invoke `cdk deploy TestStack1 TestStack2`, you can invoke just `cdk deploy TestStack1` if `TestStack1` depends on `TestStack2` (very common), you can invoke `cdk deploy TestStack*` (the command accepts wildcards), you can invoke `ckd deploy MyStage/*` if you're using [the `Stage` class](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.pipelines-readme.html#at-a-glance), etc.

This is the idiomatic way of using CDK. Just dismissing it as "bad advice" is doing yourself a disservice.

**Comment by skinny85** [comment]
Can you show the code of your Aspect, and how are developers using it in their one `Stack` instance?

**Comment by rittneje** [comment]
> You can invoke cdk deploy TestStack1 TestStack2, you can invoke just cdk deploy TestStack1 if TestStack1 depends on TestStack2 (very common), you can invoke cdk deploy TestStack* (the command accepts wildcards), you can invoke ckd deploy MyStage/* if you're using [the Stage class](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.pipelines-readme.html#at-a-glance), etc.

This is a giant maintenance headache. Every time a developer adds a new stack, they must also add it to the list of parameters to `cdk deploy`. If they don't, it will "mysteriously" not deploy.

And all of that business aside, defining all the stacks for all accounts like that is very inflexible. To deploy to a new account, I now have to make yet another copy of every stack in cdk.py.

> This is the idiomatic way of using CDK. Just dismissing it as "bad advice" is doing yourself a disservice.

I think you and I are never going to agree on this point, sorry. From personal experience, this is bad advice that only works for really trivial use cases, and doesn't scale at all.

> Can you show the code of your Aspect, and how are developers using it in their one Stack instance?

The checker Aspect is applied to the whole App, not individual Stacks (directly). This is done so there is no chance a developer forgets to add it to their Stack.

The visit method says if the node is of type `aws_dynamodb.Table`, then look at `node.node.default_child.point_in_time_recovery_specification` and verify that it matches one of our two approved strategies (either "always disable" or "enable in prod"). The code for this is still in progress, so I can't post it here.

**Comment by skinny85** [comment]
> > You can invoke cdk deploy TestStack1 TestStack2, you can invoke just cdk deploy TestStack1 if TestStack1 depends on TestStack2 (very common), you can invoke cdk deploy TestStack* (the command accepts wildcards), you can invoke ckd deploy MyStage/* if you're using [the Stage class](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.pipelines-readme.html#at-a-glance), etc.
> 
> This is a giant maintenance headache. Every time a developer adds a new stack, they must also add it to the list of parameters to `cdk deploy`. If they don't, it will "mysteriously" not deploy.

No. I literally gave 3 different ways that do not involve any changes when adding a new Stack.

> And all of that business aside, defining all the stacks for all accounts like that is very inflexible. To deploy to a new account, I now have to make yet another copy of every stack in cdk.py.

Again, no. See the `Stage` class example. You can also write a loop. There are a million ways to remove this duplication.

> > Can you show the code of your Aspect, and how are developers using it in their one Stack instance?
> 
> The checker Aspect is applied to the whole App, not individual Stacks (directly). This is done so there is no chance a developer forgets to add it to their Stack.
> 
> The visit method says if the node is of type `aws_dynamodb.Table`, then look at `node.node.default_child.point_in_time_recovery_specification` and verify that it matches one of our two approved strategies (either "always disable" or "enable in prod"). The code for this is still in progress, so I can't post it here.

OK. I think we've exhausted the discussion here. I really tried, but I can't help more without seeing the code.

You obviously have some very strong opinions on how you want to structure your CDK code. I wish you luck, and I hope you manage to satisfy your requirements.

**Comment by skinny85** [comment]
I've thought about it some more, and I think the answer is a custom Construct that wraps the CDK L2 `Table` construct.

This way, you can deal with setting `pointInTimeRecovery` to whatever you want by getting the `CfnTable` underlying the `Table` (using the `Node.defaultChild` helper) - you probably want to use an `Fn::If` CloudFormation function, and possibly a Mapping too. This way, your developers will never have to know the details, and everything will happen automatically for them.

Your Aspect can then validate that all DynamoDB Tables used in the App were created using your library, and not the `Table` class directly (here you can check for your magical `IResolvable` subclass).
