### ISSUE TITLE
(cli): Run `cdk deploy` with explicit IAM Role doesn't work

### ISSUE THREAD

**Issue by adriantaut** [aws/aws-cdk#19755]
### Describe the bug

Hello CDK team,

We have a bunch of sensitive CDK Stacks within our AWS Accounts, including the `CDKToolkit` Stack. In order to prevent unfortunate changes to these stacks have an AWS SCP in place that ensures changes can be made by a single team within our company.

```json
      {
        "Sid": "CloudAutomationStacksDeny",
        "Effect": "Deny",
        "Action": [
          "cloudformation:*"
        ],
        "Resource": [
          "arn:aws:cloudformation:*:*:stack/CiCdInfraStack/*",
          "arn:aws:cloudformation:*:*:stack/CDKToolkit/*"
        ],
        "Condition": {
          "ArnNotLike": {
            "aws:PrincipalARN": [
              "arn:aws:iam::*:role/infra-admin"
            ]
          }
        }
      }
```

We used to run `cdk deploy` commands by assuming the `infra-admin` IAM Role in each of our AWS account. The `cdk deploy` command was executed with the assumed role.

Now we are migrating towards CDK 2.0 and we noticed `cdk deploy` uses the `cdk-hnb659fds-deploy-role-<account_no>-<region>` IAM Role for actual deployment of the CDK Stacks. This automatically fails with the following error:

```
 ❌  CiCdInfraStack-infra-dev (CiCdInfraStack) failed: AccessDenied: User: arn:aws:sts::<account_no>:assumed-role/cdk-hnb659fds-deploy-role-<account_no>-<region>/<session_name> is not authorized to perform: cloudformation:DeleteChangeSet on resource: arn:aws:cloudformation:eu-west-1:<account_no>:stack/CiCdInfraStack/011eec90-3bc6-11ec-b7f8-02852bd071e7 with an explicit deny in a service control policy
```

Unfortunately couldn't find a way of explicitly specifying the IAM Role to be used when executing Change Sets, is there any?

PS: Allowing the `cdk-hnb659fds-deploy-role-<account_no>-<region>` role to execute ChangeSets from SCP is not an option as any CDK Stack that gets deployed is using the very same IAM Role.

### Expected Behavior

`cdk deploy` command is able to execute the ChangeSet using a user-specified IAM Role.

### Current Behavior

always the `cdk-hnb659fds-deploy-role-<account_no>-<region>` IAM Role is assumed while deploying CDK Stacks.

### Reproduction Steps

Explained in the bug description.

### CDK CLI Version

2.19.0

### Node.js Version

v17.6.0

### OS

MacOS

### Language

Typescript

### Language Version

4.5.5

**Comment by rix0rrr** [comment]
You are probably looking for the [LegacyStackSynthesizer](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib-readme.html#stack-synthesizers)
