### ISSUE TITLE
aws-iam: iam:minimizePolicies not working

### ISSUE THREAD

**Issue by shotty1** [aws/aws-cdk#19751]
### Describe the bug

I wanted to try the new flag iam:minimizePolicies but it does not seem to be working. Policies are not minimised.

In particular I am using ecrrepo.grantPullPush in a loop over a number of repositories for one iam user. The resulting policy for the user still has one block per repository which could be minimised to a single block with multiple resources.

### Expected Behavior

Policy should be minimised.

### Current Behavior

Policy has one block per resource

### Reproduction Steps

Example code:

```typescript
import * as ecr from 'aws-cdk-lib/aws-ecr'
import * as iam from 'aws-cdk-lib/aws-iam'

const myUser = new iam.User(this, 'myUser')

const repoList = [
  'repoName1',
  'repoName2',
  'repoName3',
]
// Repository creation
repoList.forEach( repoName =>{
  const repo = new ecr.Repository(this, `${repoName}Repo`, {
    imageScanOnPush: true,
    repositoryName: repoName,
  })
  // Grant pull access for all the workload stages
  repo.grantPullPush(myUser)
})
```

### Additional Information/Context

I am using projen
The stack in question is part of a cdk pipeline

### CDK CLI Version

2.19.0

### Node.js Version

17.8.0

### OS

macOS 12.3.1

### Language

Typescript

**Comment by rix0rrr** [comment]
After investigation, turns out that minimization *is* happening... just not as far as possible.

**Comment by shotty1** [comment]
just tested it with the new version/ Works like a charm. Thanks a lot for the quick fix!
