### ISSUE TITLE
Add support for Kubernetes objects, e.g. pods, deployments, services, etc. 

### ISSUE THREAD

**Issue by jicowan** [aws/aws-cdk#1976]
Feature request: Extend the CDK support Kubernetes objects

**Comment by SomayaB** [comment]
Hi @jicowan, sorry this has gone so long without response. It looks like this feature has since been implemented, see [docs](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-eks-readme.html).

I will close this issue but feel free to reopen it if this didn't address your concern.
