### ISSUE TITLE
(S3): Cannot specify number of noncurrent versions to retain in LifeCycle rule without transitioning the StorageClass

### ISSUE THREAD

**Issue by KomaGR** [aws/aws-cdk#19784]
### Describe the bug

Using the `lifecycleRules` configuration of a versioned bucket, I cannot specify how many noncurrent versions to retain without triggering any storage transition. (I want the objects to stay in STANDARD tier but that is also not available under `s3.StorageClass`.)

**What I'm trying to achieve**
I want to delete all object versions older than one day but I want to keep the five latest versions for each object (in the same storage tier). I don't want the older versions to transition to another tier since I also want to delete them after a single day if, i.e., another batch of 5 versions comes through.

### Expected Behavior

The Console seems to allow exactly what I'm going after:
![image](https://user-images.githubusercontent.com/22573447/161948878-ec3606dc-9864-4e81-a98b-9fc327f71407.png)

### Current Behavior

Currently, the option for how many noncurrent versions to retain `noncurrentVersionsToRetain` is under the `noncurrentVersionTransitions` configuration option, which forces to specify `transitionAfter` and `storageClass`. The Console UI (see above) suggests that I would not need to specify these and only need specify `noncurrentVersionExpiration`.
```ts
{
    enabled: true,
    prefix: "usr_",
    noncurrentVersionExpiration: Duration.days(1),
    expiredObjectDeleteMarker: true,
    abortIncompleteMultipartUploadAfter: Duration.days(1),
    noncurrentVersionTransitions: [
        {
            transitionAfter: Duration.days(1),
            noncurrentVersionsToRetain: 5,
            storageClass: /* Side issue: There is no s3.StorageClass.STANDARD */
        }
    ]
}
```

### Reproduction Steps

Here is the Object I'm trying to create with the `noncurrentVersionTransitions` config option commented out:
```ts
new s3.Bucket(this, 'bugBucket', {
            versioned: true,
            lifecycleRules: [
                {
                    enabled: true,
                    prefix: "prefix",
                    noncurrentVersionExpiration: Duration.days(1),
                    expiredObjectDeleteMarker: true,
                    abortIncompleteMultipartUploadAfter: Duration.days(1),
//                    noncurrentVersionTransitions: [
//                        {
//                            transitionAfter: Duration.days(1),
//                            noncurrentVersionsToRetain: 5,
//                            storageClass: /*  */
//                        }
//                    ]
                }
            ]
        });
```

### Possible Solution

Judging by the UI, it looks like `noncurrentVersionsToRetain` should be a property of the Lifecycle rule and not nested into `noncurrentVersionTransitions`.

### CDK CLI Version

2.19.0 (build e0d3e62)

### Framework Version

aws-cdk-lib@2.8.0

### Node.js Version

v16.13.2

### OS

Ubuntu 20.04

### Language

Typescript

**Comment by NGL321** [comment]
Hey @KomaGR,

Thank you for reporting this. I have converted the issue to a feature-request since it seems that rather than broken function this is a suggestion for improvement (or rather, covering a specific case that was missed). The fix itself seems reasonable.

**Comment by KomaGR** [comment]
Hi @NGL321,

thanks for taking a look at this. I dug a bit deeper in the links you shared and I think there might be more to this. 

It looks like the L1 construct supports retaining a specific number of versions for both expiration and transition actions:
```js
    noncurrentVersionExpiration: {
      noncurrentDays: 123,

      // the properties below are optional
      newerNoncurrentVersions: 123,    // <- This field
    },
    noncurrentVersionTransition: {
      storageClass: 'storageClass',
      transitionInDays: 123,

      // the properties below are optional
      newerNoncurrentVersions: 123,    // <- This field
    },
```
The way I interpret this is that the user can:
1. use `noncurrentVersionTransition.newerNoncurrentVersions` to retain a number of versions to not be  _not transitioned_ by the rule, and
2. use `noncurrentVersionExpiration.newerNoncurrentVersions` to retain a number of versions to not be _not expired_ by the rule.

The realization that both these support a `newerNoncurrentVersions` option is confirmed by the [linked documentation page](https://docs.aws.amazon.com/AmazonS3/latest/userguide/intro-lifecycle-rules.html#intro-lifecycle-rules-actions) where under both "NoncurrentVersionTransition action element" and "NoncurrentVersionExpiration action element" it says:

> In addition to the number of days, you can also provide a maximum number of noncurrent versions to retain.

(The point is that the above is found two separate times in the doc page.)

Setting these two retention numbers separately is possible to do from the Console.

### In conclusion
The `noncurrentVersionTransitions.noncurrentVersionsToRetain` option seems to not be misplaced. At the same time, it looks like there needs to be an option for the expiration that goes with `noncurrentVersionExpiration`. Name could be `noncurrentVersionsToNotExpire` if not nested. Alternatively, you can make `noncurrentVersionExpiration` a nested configuration (similar to `noncurrentVersionTransitions`) to reflect the underlying L1 construct options.

### Example with expiration only (what I'm trying to achieve)
Since I have done this through the Console as a demonstration, here is what the Lifecycle rule configuration JSON looks like when I set the number of versions retain not-expired:
```json
{
    "Rules": [
        {
            "Expiration": {
                "ExpiredObjectDeleteMarker": true
            },
            "ID": "<redacted>",
            "Filter": {
                "Prefix": "prefix"
            },
            "Status": "Enabled",
            "NoncurrentVersionExpiration": {
                "NoncurrentDays": 1,
                "NewerNoncurrentVersions": 5
            },
            "AbortIncompleteMultipartUpload": {
                "DaysAfterInitiation": 1
            }
        }
    ]
}
```
and here is the interpretation of this from the Console:
<img width="382" alt="image" src="https://user-images.githubusercontent.com/22573447/162143826-4659c11b-ba48-4825-b5d5-4ab1713e371e.png">


### Example with transition and then expiration
Here is what the configuration looks like with **both** transition and expiration configured (had to increase the days due to STANDARD-IA constraints):
```json
{
    "Rules": [
        {
            "Expiration": {
                "ExpiredObjectDeleteMarker": true
            },
            "ID": "<redacted>",
            "Filter": {
                "Prefix": "prefix"
            },
            "Status": "Enabled",
            "NoncurrentVersionTransitions": [
                {
                    "NoncurrentDays": 30,
                    "StorageClass": "STANDARD_IA",
                    "NewerNoncurrentVersions": 5
                }
            ],
            "NoncurrentVersionExpiration": {
                "NoncurrentDays": 31,
                "NewerNoncurrentVersions": 5
            },
            "AbortIncompleteMultipartUpload": {
                "DaysAfterInitiation": 1
            }
        }
    ]
}
```
and here is the interpretation of this from the Console:
<img width="395" alt="image" src="https://user-images.githubusercontent.com/22573447/162143718-3a507134-c182-4c74-b96a-82b31556c62c.png">

**Comment by rix0rrr** [comment]
We need a `noncurrentVersionsToRetain` property, which renders into the [CloudFormation `NoncurrentVersionExpiration` object](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-lifecycleconfig-rule.html#cfn-s3-bucket-lifecycleconfig-rule-noncurrentversionexpiration).

PRs welcome.
