### ISSUE TITLE
(aws-lambda): Add support for Function URLs

### ISSUE THREAD

**Issue by ayush987goyal** [aws/aws-cdk#19798]
### Describe the feature

Add support for creating function URLs through AWS CDK Lambda module: https://docs.aws.amazon.com/lambda/latest/dg/urls-configuration.html#urls-cfn

### Use Case

Need an easy way to create Function URLs.

### Proposed Solution

1. `FunctionUrl` should be added as a new resource under lambda module
2. A helper method of `addUrl` or `configureUrl` should be added to the `Function`
3. A configuration for function urls in the props to `Function`  should be added to create URL at the time of creating `Function`

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.x

### Environment details (OS name and version, etc.)

All

**Comment by ayush987goyal** [comment]
The feature is currently not a part of the AWS CFN spec: https://d1uauaxba7bl26.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json

Would need to wait for the spec to get updated (and available in CDK) before progressing on adding this feature.

**Comment by kaizen3031593** [comment]
I'll be on the lookout for the CFN update!

**Comment by illahi** [comment]
This AWS blog seems to indicate it's already available: https://aws.amazon.com/blogs/aws/announcing-aws-lambda-function-urls-built-in-https-endpoints-for-single-function-microservices/. Confusing.

> You can start configuring Lambda Function URLs directly in your IaC templates today using AWS CloudFormation, AWS SAM, and AWS Cloud Development Kit (AWS CDK).

**Comment by capaj** [comment]
@ayush987goyal it seems to be added now:
```
  "Attributes": {
        "FunctionArn": {
          "PrimitiveType": "String"
        },
        "FunctionUrl": {
          "PrimitiveType": "String"
        }
      }
```

**Comment by ayush987goyal** [comment]
@capaj Already WIP :D
