### ISSUE TITLE
(aws_rds): addRotationMultiUser secrets missing engine on bootstrap

### ISSUE THREAD

**Issue by ahammond** [aws/aws-cdk#19794]
### Describe the bug

When I addRotationMultiUser with a DatabaseSecret, 

```ts
const secret = new aws_rds.DatabaseSecret(this, 'Secret', {
  username: 'a_user_name',
  encryptionKey,
  secretName: 'aUserName',
  masterSecret: cluster.secret,
});
cluster.addRotationMultiUser('aUserName', { secret });
```

the rotation lambda fails with

```
[ERROR] KeyError: "Database engine must be set to 'postgres' in order to use this rotation lambda" Traceback (most recent call last):   File "/var/task/lambda_function.py", line 77, in lambda_handler     create_secret(service_client, arn, token)   File "/var/task/lambda_function.py", line 113, in create_secret     current_dict = get_secret_dict(service_client, arn, "AWSCURRENT")   File "/var/task/lambda_function.py", line 451, in get_secret_dict     raise KeyError("Database engine must be set to 'postgres' in order to use this rotation lambda")
```

### Expected Behavior

It should work.

### Current Behavior

It doesn't work.

### Reproduction Steps

```ts
import { App, Stack, StackProps, aws_ec2, aws_rds } from 'aws-cdk-lib';
import { Construct } from 'constructs';

export class MyStack extends Stack {
  constructor(scope: Construct, id: string, props: StackProps = {}) {
    super(scope, id, props);

    const vpc = aws_ec2.Vpc.fromLookup(this, 'VPC', {
      tags: { TheVpc: 'Default' }, // or whatever.
    });

    const cluster = new aws_rds.DatabaseCluster(this, 'MyCluster', {
      credentials: {
        username: 'manager',
      },
      engine: aws_rds.DatabaseClusterEngine.auroraPostgres({
        version: aws_rds.AuroraPostgresEngineVersion.VER_12_8,
      }),
      instanceProps: {
        instanceType: aws_ec2.InstanceType.of(
          aws_ec2.InstanceClass.T3,
          aws_ec2.InstanceSize.MEDIUM
        ),
        vpc,
      },
      instances: 1, // be cheap
    });
    cluster.addRotationSingleUser();

    const secret = new aws_rds.DatabaseSecret(this, 'ReaderSecret', {
      username: 'reader',
      masterSecret: cluster.secret,
    });

    cluster.addRotationMultiUser('ReaderRotation', { secret });
  }
}

// for development, use account/region from cdk cli
const devEnv = {
  account: process.env.CDK_DEFAULT_ACCOUNT,
  region: process.env.CDK_DEFAULT_REGION,
};

const app = new App();

new MyStack(app, 'my-stack-dev', { env: devEnv });

app.synth();
```

Chase down the substack for the multi-rotation, find the lambda, find it's execution logs. Lo and behold, an error message appears!

### Possible Solution

`aws_rds.DatabaseSecret()` should be bootstrapping the secret with basics from the `masterSecret`.

### CDK CLI Version

2.18.0 (build 75c90fa)

### Framework Version

same

### Node.js Version

v16.13.1

### OS

Darwin Kernel Version 21.2.0: Sun Nov 28 20:29:10 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T8101 arm64

### Language

Typescript

### Language Version

    "typescript": "^4.6.3"

**Comment by ahammond** [comment]
I've tried pushing the 
```
engine: postgres
```
key into the secrets to help the bootstrap. Will update if that's a sufficient workaround.

**Comment by ahammond** [comment]
That got me further, now the error is
```
[ERROR] KeyError: 'host key is missing from secret JSON'Traceback (most recent call last):  File "/var/task/lambda_function.py", line 77, in lambda_handler    create_secret(service_client, arn, token)  File "/var/task/lambda_function.py", line 113, in create_secret    current_dict = get_secret_dict(service_client, arn, "AWSCURRENT")  File "/var/task/lambda_function.py", line 454, in get_secret_dict    raise KeyError("%s key is missing from secret JSON" % field) | [ERROR] KeyError: 'host key is missing from secret JSON' Traceback (most recent call last):   File "/var/task/lambda_function.py", line 77, in lambda_handler     create_secret(service_client, arn, token)   File "/var/task/lambda_function.py", line 113, in create_secret     current_dict = get_secret_dict(service_client, arn, "AWSCURRENT")   File "/var/task/lambda_function.py", line 454, in get_secret_dict     raise KeyError("%s key is missing from secret JSON" % field)
```

So... I'll hack that in and see if that (finally) gets things working.

**Comment by ahammond** [comment]
I can confirm that manually setting the `engine` and `host` gets this working, however I was commenting out the 
``` ts
cluster.addRotationMultiUser('ReaderRotation', { secret });
```
deploying and then uncommenting and deploying to force things.

I see in the logs for the instance we have deployed that these lambdas are getting re-run occasionally. And that one of them has run since I added the `engine` entry. What triggers the running of these lambdas and how can I manually cause them to run?

**Comment by skinny85** [comment]
Thanks for opening the issue @ahammond!

> I can confirm that manually setting the `engine` and `host` gets this working,

Can you clarify where did you have to set `engine` and `host`, and to what value?

> I see in the logs for the instance we have deployed that these lambdas are getting re-run occasionally. And that one of them has run since I added the `engine` entry. What triggers the running of these lambdas and how can I manually cause them to run?

That I don't know. I assume there's some rotation schedule, and maybe rotations are re-tried if they failed?

**Comment by ahammond** [comment]
@skinny85 thank you for the attention!!!

I set these keys in the SecretsManager secret created by `aws_rds.DatabaseSecret()` (not the database superuser secret).

 ```
 engine: postgres
 host: ${{ cluster.clusterEndpoint }} // you'll have to look this up. Easiest way is to just look at the database manager / superuser secret.
 ```

**Comment by skinny85** [comment]
Hmm, interesting! And did that fix it?

**Comment by ahammond** [comment]
Looks like it did, at least in sscce. I'm working on reproducing the fix in the pre-prod environment where I discovered it. So... this is probably a workaround, but... yuck.

**Comment by ahammond** [comment]
The rotation lambda succeeds, but... it doesn't create a user in the DB. Do... we have to do that manually? Because... gross.

**Comment by skinny85** [comment]
When you say "lambda sample code stuff", what exactly are you referring to? (Maybe I'm not remembering some details from the `excludeCharacters` change)

**Comment by ahammond** [comment]
@skinny85 from what I recall, instead of just inlining the lambdas in the `aws-cdk-lib` repo, the password rotation stuff deploys a SAM application based on https://github.com/aws-samples/aws-secrets-manager-rotation-lambdas stuff. Which... is admirable for a code reuse pattern, but man oh man it took forever to get the PR on that repo accepted.

**Comment by ahammond** [comment]
Yup. https://github.com/aws/aws-cdk/pull/10110/files was the update to pull the new version of the SAM stuff.

**Comment by skinny85** [comment]
Ah, got it. I mean, yeah, if the rotation application has some bug, then yes, it needs to be fixed upstream.

Note that the current rotation applications are also very old - maybe the problem has been fixed in newer versions already. We have an open issue about it (https://github.com/aws/aws-cdk/issues/18249), you can use this workaround: https://github.com/aws/aws-cdk/issues/18249#issuecomment-1005121223 for now if you want to try updating the application to the latest version, and seeing if that helps.

**Comment by skinny85** [comment]
@ahammond any news here? Did you try the updated rotation applications, and did that fix the problem?

**Comment by ahammond** [comment]
@skinny85 https://github.com/time-loop/cdk-aurora was what we ended up doing instead. You'll see there's a custom resource there which creates users (etc). As near as I can tell, there is no clean and elegant way to provision users in the database without adding a custom resource.

**Comment by ahammond** [comment]
@skinny85 this part specifically https://github.com/time-loop/cdk-aurora/blob/main/src/aurora.provisioner.ts#L332..L354 I think should already be happening in the rotation applications. Because... they're never going to work without them.

**Comment by skinny85** [comment]
Did you submit an issue about it to the rotation applications?

**Comment by ahammond** [comment]
https://github.com/aws-samples/aws-secrets-manager-rotation-lambdas/issues/84 submitted. Thank you for the reminder!

**Comment by skinny85** [comment]
Sweet. I guess we'll ned to ingest the new version of the rotation Lambdas as part of https://github.com/aws/aws-cdk/issues/18249 once that is fixed.

I'm resolving this one, let me know if you need anything else from our side.

**Comment by ahammond** [comment]
To be clear, this isn't fixed. I just worked around the obvious bug.

**Comment by xplsek03** [comment]
@ahammond not sure about aws_rds, but in cf i am passing engine/host using AWS::SecretsManager::SecretTargetAttachment, maybe its same (?)

**Comment by ahammond** [comment]
@xplsek03 i think it was because I didn't attach the secret.
