### ISSUE TITLE
Add support for Aurora postgres version 12.9 and other latest version in CDK construct 

### ISSUE THREAD

**Issue by vikassingla85** [aws/aws-cdk#19803]
### Describe the feature

Add support for Aurora postgres version 12.9 and other latest version in CDK construct 
https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-rds/lib/cluster-engine.ts#L491

### Use Case

We need to upgrade Aurora cluster as 12.9 is the only LTS supported by AWS for Aurora 12, we want to target that. All our stacks are currently using 12.4 and written in CDK.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

V1

### Environment details (OS name and version, etc.)

Mac/Linux

**Comment by skinny85** [comment]
Thanks for opening the issue @vikassingla85! We encourage community contributions, so if you'd like to open us a Pull Request adding this feature, that would be fantastic! Our "Contributing" guide: https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md.

Until this feature is implemented, you can use the [`AuroraPostgresEngineVersion.of()` method](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_rds.AuroraPostgresEngineVersion.html#static-ofaurorapostgresfullversion-aurorapostgresmajorversion-aurorapostgresfeatures) to construct any version that you need.

Thanks,
Adam
