### ISSUE TITLE
(aws-cloudwatch): (alarm being fired every 15 mins)

### ISSUE THREAD

**Issue by alamathe1** [aws/aws-cdk#19813]
### Describe the bug

We have the following code that is used to create for canary hydra testing:

```
  private createCanaryMonitor(options: MonitoringStackOptions) {
    this.monitoring.monitorHydra({
      alarmFriendlyName: 'IntegrationTests',
      humanReadableName: 'IntegrationTests',
      requester: options.canary.hydraSeries.cfnSeries.ref,
      testVertical: 'CANARY',
      suiteName: 'HydraTestSuite', // Hard-coded at https://code.amazon.com/packages/HydraTestPlatformNodeBaseLib/blobs/623ed9f1ffefcdc62d96696f7620ab664275bbd3/--/lib/cloudwatch-reporter.ts#L13
      addFailureCountAlarm: {
        Critical: {
          severity: TicketSeverity.SEV_3,
          maxErrorCount: 1,
          treatMissingData: TreatMissingData.BREACHING,
          datapointsToAlarm: 1,
        },
      },
    });
  }
}
```

The canary is configured to run once 1 every 15 minute. The test suite takes < 1 minute to complete and when the suite is not running, alarm is raised which we think is due to the property `treatMissingData: TreatMissingData.BREACHING`. Cutting this ticket to ensure how to handle this scenario? Do we have a property that would alert us if the canary is down / data is missing for certain period such as 60 mins and then possibly flag that missing data as breaching. This would help us identify if the data is actually missing or not due to service failure, etc.

### Expected Behavior

Alarm to be not fired.

### Current Behavior

Alarm fired every 15 min - which is canary running interval time.

### Reproduction Steps

The code mentioned in description should be run.

### CDK CLI Version

1.110.0

### Node.js Version

14.17.6

### OS

macos

### Language

Typescript

**Comment by NGL321** [comment]
As this is regarding AWS internal CDK deployments, it should be tracked internally. I have created a ticket on your behalf to do so: P62531801
