### ISSUE TITLE
Add a --delete-bucket switch to cdk bootstrap to override default retain behavior

### ISSUE THREAD

**Issue by philasmar** [aws/aws-cdk#19828]
### Describe the feature

The default `cdk bootstrap` CloudFormation template retains the S3 bucket created. If the bootstrap fails or the user tries to delete the CDKToolkit stack, we need the cdk to cleanup the resources automatically. Instead of us modifying the cdk bootstrap template, keeping it up to date, and passing it to `cdk bootstrap`, we want a command line switch to be added to the `cdk bootstrap --delete-bucket` that changes the default retain behavior to delete.

### Use Case

The AWS .NET SDK team is working on a tool that uses the CDK on the backend. The tool offers users the ability to deploy their application in a very quick and friendly way. We generate automatically the cdk project and run `cdk bootstrap` before running `cdk deploy`. If users don't have enough permissions initially, `cdk bootstrap` fails and tries to rollback while leaving behind an S3 bucket. After the user elevates their permissions and runs `cdk bootstrap` again, they get an error that a bucket already exists. This leaves them stuck and not able to proceed. We need to be able to change the retain behavior to delete without needing to manually modify the CF template and worry about keeping it up to date.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.13.0

### Environment details (OS name and version, etc.)

Any

**Comment by rix0rrr** [comment]
As a workaround you can do:

```shell
cdk bootstrap --show-template > template.json
# Modify the template.json using code to change RETAIN to DESTROY
cdk bootstrap --template template.json
# Final deploy flipping back to RETAIN
cdk bootstrap  
```

Agreed that it's not as nice as when we make this easy for you, but it's by no means impossible to achieve yourself or forcing you to keep up with the bootstrap template changes.
