### ISSUE TITLE
Plus ("+") in URL is replaced with space (" ")

### ISSUE THREAD

**Issue by softchef-kevin** [aws/aws-cdk#19827]
### Describe the bug

In the query string, plus ("+") will be replaced by space (" ").
similar problems have happened on .net. https://github.com/aws/aws-lambda-dotnet/issues/237

### Expected Behavior

The plus sign can be passed into the lambda handler via the query string.

### Current Behavior

It appears the lambda hosting code replaces plus ("+") with space (" "). 
i call:
```
GET /applications/announced?sort=-+createdAt
```

then i printed out the event and observed it in cloudwatch log:
```
2022-04-08T12:34:19.071Z	ea93b6d1-b5a4-4609-bab7-xxxxxxxxx	INFO	event 
{
    "resource": "/applications/announced",
    "path": "/applications/announced",
    "httpMethod": "GET",
    "queryStringParameters": {
        "sort": "- createdAt"
    },
    "multiValueQueryStringParameters": {
        "sort": [
            "- createdAt"
        ]
    },
    "pathParameters": null,
    ...
}
```

### Reproduction Steps

This can be reproduced with any javascript lambdas fronted by a proxy apigateway. Simple issue a request with a plus ("+") in the url i.e. GET https://example.com/applications/announced?sort=-+createdAt

### CDK CLI Version

2.17.0 (build f9cd009)

### Node.js Version

v16.14.2

### OS

windows 10

### Language

Typescript

**Comment by NGL321** [comment]
Hey @softchef-kevin,

I am uncertain as to what CDK components you are concerned about failing here, without direct reproduction code, we cannot evaluate this bug. Could you please provide a more explicit example of the cdk stack that causes this problem?
