### ISSUE TITLE
Feature Request: Allow the Lambda function code property to directly use a ZipDirectoryAsset

### ISSUE THREAD

**Issue by aecollver** [aws/aws-cdk#1983]
Each time I use Lambda's AssetCode, I end up with a tuple of CloudFormation input parameters (bucket + key). I'd like to create multiple Lambda functions where each uses a different handler, but they share the same build artifact (so a single tuple of CloudFormation input parameters). The example below shows how I do this today and a proposal to make this less verbose. The "why" behind this pattern is because I don't want to update my [CodePipeline] pipeline (specifically the configured CloudFormation input parameters that reference the build artifact) each time I add or remove a Lambda function in my application.

```typescript
    const myApplication = new cdkAssets.ZipDirectoryAsset(this, 'foo', {
      path: 'build'
    });
    const testFunction = new lambda.Function(this, 'bar', {
      runtime: lambda.Runtime.NodeJS810,
      handler: 'lib/application/application.handler',
      // Current:
      code: new lambda.S3Code(myApplication.s3BucketName, myApplication.s3ObjectKey)
      // Proposed:
      code: myApplication
    });
```

**Comment by nija-at** [comment]
As part of our GA launch, we've launched the `Code.fromAsset()` API in the [lambda module](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-lambda-readme.html#handler-code) that what's being asked here.
