### ISSUE TITLE
(ec2): VpnTunnelOption.preSharedKey should take in a Secret.Value instead of a string

### ISSUE THREAD

**Issue by madeline-k** [aws/aws-cdk#19832]
### Describe the feature

[This property](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-ec2.VpnTunnelOption.html#presharedkey) should take in a Secret.Value instead of a string.

### Use Case

Using a SecretValue makes it possible to not expose the token in text in the template. 

### Proposed Solution

Deprecate `preSharedKey` and create a a new property. Suggested name: `preSharedKeySecret`

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

v1 & v2

### Environment details (OS name and version, etc.)

All

**Comment by corymhall** [comment]
One thing to not about using `Secret.Value` in this case is that this specific field does not
support secrets manager secrets. We would need to validate that the user is specifying a ssm value.

**Comment by MrArnoldPalmer** [comment]
Looks like this was resolved in https://github.com/aws/aws-cdk/pull/19543
