### ISSUE TITLE
aws_iam: Cannot find AWSLambdaBasicExecutionRole

### ISSUE THREAD

**Issue by robertofd1995** [aws/aws-cdk#19830]
### Describe the bug

I am trying to attach the following aws manage policy (arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole) to a role

### Expected Behavior

Attach the aws Manage policy (arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole) to the new role

### Current Behavior

Error on Cloud formation when creating the resource: CREATE_FAILED

Policy arn:aws:iam::aws:policy/AWSLambdaBasicExecutionRole does not exist or is not attachable. (Service: AmazonIdentityManagement; Status Code: 404; Error Code: NoSuchEntity; Request ID: 3dcc7ccc-83f6-494a-bc19-67905523e038; Proxy: null)

### Reproduction Steps

```python
from constructs import Construct
from aws_cdk import (
    Stack,
    aws_iam as iam
)


class Example(Stack):

    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        iam.Role(self, "example_role",
                 role_name="example_role",
                 description="Role needed to execute KnoxMediaHub transcodes service "
                             "to call S3 APIs and API Gateway on your behalf.",
                 assumed_by=iam.CompositePrincipal(
                     iam.ServicePrincipal(service="mediaconvert.amazonaws.com"),
                     iam.ServicePrincipal(service="lambda.amazonaws.com")
                 ),
                 managed_policies=[
                     iam.ManagedPolicy.from_aws_managed_policy_name("AmazonS3FullAccess")
                 )
```

### CDK CLI Version

2.15.0 (build 151055e)

### Node.js Version

v14.16.1

### OS

Mac Os Mojave

### Language

Python

### Language Version

Python 3.9.5

**Comment by rix0rrr** [comment]
![2022-04-08 at 18 16](https://user-images.githubusercontent.com/524162/162481773-568fe462-7d4e-48d8-ac33-e2b8f8ba5421.png)

https://docs.aws.amazon.com/cdk/api/v1/python/aws_cdk.aws_iam/ManagedPolicy.html#aws_cdk.aws_iam.ManagedPolicy.from_aws_managed_policy_name

![2022-04-08 at 18 16](https://user-images.githubusercontent.com/524162/162481859-f934b73a-ebbd-4e03-bc4e-7ac48ede25a4.png)
