### ISSUE TITLE
Fails to update existing ECS non-loadbalanced service when adding to load balancer

### ISSUE THREAD

**Issue by Voyen** [aws/aws-cdk#19842]
### Describe the bug

When there is an existing ECS service which is not initially configured with a load balancer, and a change is made to add this service to a target group for an ALB, the CFN change performed is an UPDATE. 
However this is not possible since ALB assignment can only be done to an ECS service during creation.

### Expected Behavior

In this scenario the change should recreate the service resource rather than update it.

### Current Behavior

Update fails with the following message:

```
Resource handler returned message: "Invalid request provided: UpdateService error: Health check grace period is only valid for services configured to use load balancers (Service: AmazonECS; Status Code: 400; Error Code: InvalidParameterException; Request ID: xxxyyyzzz; Proxy: null)"
```

### Reproduction Steps

1. Create a `FargateService` which is not backed by a load balancer.
2. Deploy
3. Add the service from step 1 as a target to an ALB's listener
4. Deploy

### Possible Solution

Rather than making the change as an update, it should recreate the service resource in order to assign the ALB correctly.

### CDK CLI Version

2.20.0 (build 738ef49)

### Node.js Version

v17.8.0

### OS

Ubuntu 21.10 (5.17.0-051700-generic)

### Language

Typescript

### Language Version

4.6.2

**Comment by peterwoodworth** [comment]
I've looked into this a bit @Voyen,

You're right - following your steps I get the same error as you. However what was interesting to me was that the error message was about health check grace period.

Checking the CDK diff between adding the ALB, you see that the LoadBalancers property on the ECS Service gets added, but the `HealthCheckGracePeriod` property _also_ gets added. I wondered if maybe removing this property first would somehow make this work. It didn't - the CloudFormation deployment timed out after getting stuck modifying the service.

I believe the fix here would be CloudFormation changing update on [`Service.LoadBalancers`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-service.html#cfn-ecs-service-loadbalancers) from No Interruption to Resource Replacement. I'll create a ticket for them, let's see what they say 🙂

**Comment by jaecktec** [comment]
```
(service.node.defaultChild as CfnService).healthCheckGracePeriodSeconds = undefined;
```
works for me

**Comment by stoicad** [comment]
Facing the same issue when having 2 ECS services and I want to set an ELB on top of them. Had to comment out the ECS services, run CDK deploy (to remove the ECS services) remove the comments and run the ELB & ECS generation together.

**Comment by jackkitley** [comment]
Facing the same issue adding a listener and target to an existing ALB.



 ❌  WebStack failed: Error: The stack named WebStack failed to deploy: UPDATE_ROLLBACK_COMPLETE: Resource handler returned message: "Invalid request provided: UpdateService error: Health check grace period is only valid for services configured to use load balancers (Service: AmazonECS; Status Code: 400; Error Code: InvalidParameterException; Request ID: ...; Proxy: null)" (RequestToken: ..., HandlerErrorCode: InvalidRequest)
    at prepareAndExecuteChangeSet (/usr/local/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:385:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at CdkToolkit.deploy (/usr/local/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:209:24)
    at initCommandLine (/usr/local/lib/node_modules/aws-cdk/lib/cli.ts:341:12)

The stack named WebStack failed to deploy: UPDATE_ROLLBACK_COMPLETE: Resource handler returned message: "Invalid request provided: UpdateService error: Health check grace period is only valid for services configured to use load balancers (Service: AmazonECS; Status Code: 400; Error Code: InvalidParameterException; Request ID: ....; Proxy: null)" (RequestToken: ...., HandlerErrorCode: InvalidRequest)

**Comment by Stazz-Sphinx** [comment]
AWS CDK version 1.139.0

 Got the same issue when tried attach ECS service to the existed TG on ALB. 
Diff showed me that `HealthCheckGracePeriodSeconds` is going to be created

`[~] AWS::ECS::Service public-gateway-service/Service publicgatewayserviceService111111111 
 ├─ [+] HealthCheckGracePeriodSeconds
 │   └─ 60
 └─ [+] LoadBalancers
     └─ [{"ContainerName":"envoy","ContainerPort":9080,"TargetGroupArn":"arn:aws:elasticloadbalancing:ap-southeast-2:1234567890987:targetgroup/dev-pub-virtual-gateway/1q2w3e4r5t6y7u8"}]

`

**Comment by corymhall** [comment]
This is not something we should fix in CDK. Created issue with CloudFormation https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1313

**Comment by bvtujo** [comment]
AFAICT this is now working in CFN. Here's my successful stack where I attempt to replicate the bug conditions. 

```typescript
import { App, Duration, Stack, StackProps } from 'aws-cdk-lib';
import { Cluster, ContainerImage, FargateService, FargateTaskDefinition } from 'aws-cdk-lib/aws-ecs';
import { ApplicationLoadBalancer, ApplicationProtocol, ListenerAction } from 'aws-cdk-lib/aws-elasticloadbalancingv2';
import { Construct } from 'constructs';

export interface MyStackProps {
  readonly addTarget: boolean;
}
export class MyStack extends Stack {
  constructor(scope: Construct, id: string, props: MyStackProps, stackProps?: StackProps) {
    super(scope, id, stackProps);
    const cluster = new Cluster(this, 'Cluster');
    const taskDefinition = new FargateTaskDefinition(this, 'taskdef', {
      cpu: 256,
      memoryLimitMiB: 512,
    });
    taskDefinition.addContainer('container', {
      image: ContainerImage.fromRegistry('nathanpeck/name'),
      environment: {
        PORT: '80',
      },
      portMappings: [
        {
          containerPort: 80,
        },
      ],
    });
    const svc = new FargateService(this, 'Service', {
      cluster,
      taskDefinition,
      healthCheckGracePeriod: props.addTarget ? Duration.seconds(120) : undefined,
      desiredCount: 5,
    });

    const alb = new ApplicationLoadBalancer(this, 'alb', {
      vpc: cluster.vpc,
    });
    const listener = alb.addListener('httplistener', {
      open: true,
      protocol: ApplicationProtocol.HTTP,
      defaultAction: ListenerAction.fixedResponse(404, {
        messageBody: 'Nothing here. No services added to listener',
      }),
    });
    if (props.addTarget) {
      listener.addTargets('svctarget', {
        targets: [svc],
        port: 80,
      });
    }
  }

}

const app = new App();

new MyStack(app, 'stack', { addTarget: false });

app.synth();
```

You can deploy this to create all the setup resources. 

Then, flip `addTarget` to `true` and redeploy:

```typescript
new MyStack(app, 'stack', { addTarget: true });
```

That boolean adds the healthCheckGracePeriod field and registers the service as a target to the ALB, which used to trigger the failure. 

With this stack, the observed behavior is that the service is updated cleanly and does not throw any errors. I'd love if someone else could check this too.

**Comment by bvtujo** [comment]
Closing this as resolved. Feel free to reopen if you notice this bug persists under other configurations.

**Comment by TheRealAmazonKendra** [comment]
From @bvtujo's comments it sounds like this issue is resolved. I'm going to go ahead and close this. If you believe this was closed in error, please feel free to open a new ticket.
