### ISSUE TITLE
aws-eks: Cannot add new nodegroup because new nodegroup trying to launch instance before aws-auth manifest update 

### ISSUE THREAD

**Issue by dtitenko-dev** [aws/aws-cdk#19845]
### Describe the bug

When I tried to add a new node group to the eks cluster, cloudformation tried to create a new node group before aws-auth manifest was updated. Creation of new node group fails with error.

### Expected Behavior

Successfully create node group. 

### Current Behavior

Node group creation fails with error
```Resource handler returned message: "[Issue(Code=NodeCreationFailure, Message=Instances failed to join the kubernetes cluster, ResourceIds=[<ids-of-instances>])] (Service: null, Status Code: 0, Request ID: null, Extended Request ID: null)" (RequestToken: <request-token>, HandlerErrorCode: GeneralServiceException)```

### Reproduction Steps

Add new node group to existing eks cluster

### Possible Solution

Add [here](https://github.com/aws/aws-cdk/blob/738ef49a9f6535cd8df8987d4388f74c1946aa54/packages/%40aws-cdk/aws-eks/lib/managed-nodegroup.ts#L435) a dependency of node group resource on cluster's aws-auth manifest.

### CDK CLI Version

v2.20.0

### Framework Version

v2.20.0

### Node.js Version

v14.16.1

### OS

Darwin

### Language

Python

### Language Version

3.9.11

**Comment by pahud** [comment]
Can you provide more detailed steps and minimal code snippets for me to reproduce it? Sounds like you have created a cluster and the first nodegroup in your initial cdk deployment and you update your cdk to add additional nodegroup, deploying again and it fails. Is it correct?
