### ISSUE TITLE
Generalize IResourceWithPolicy interface to enable detection of resources that support resource policies

### ISSUE THREAD

**Issue by Gtofig** [aws/aws-cdk#19846]
### Describe the feature

Make all resources that support resource policies implement [IResourceWithPolicy](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_iam.IResourceWithPolicy.html) interface, with `addToResourcePolicy` method.

### Use Case

When creating generic permission utility methods or aspects in CDK, it is often useful to know if resource has resource policies, so that they can be checked for specific security constraints. For example, I might want to create an aspect that ensures that all resources that support resource policies have specific security conditions applied to their statements.

Another example, is if I want to create a permission utility that tests if a resource grants particular principal access, but to implement this I need to know if this resource has resource policies or not.

### Proposed Solution

I assume this change requires:
- Extract [IResourceWithPolicy](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_iam.IResourceWithPolicy.html) from IAM into a core location
- Ensuring that all constructs that currently implement `addToResourcePolicy` extend this new interface.

### Other Information

Alternatively, add a helper method that returns `true` if passed construct contains resource policies.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### CDK version used

2.20.0

### Environment details (OS name and version, etc.)

Any

**Comment by rix0rrr** [comment]
Thanks for the request and the use case. I agree this would be useful. It's not in our scope right now and unlikely to be soon, but I will keep this open to collect discussion and upvotes.
