### ISSUE TITLE
aws_events_targets: Java fluent builder for ApiDestinationBuilder with scope and id missing

### ISSUE THREAD

**Issue by dcowan-e-courier** [aws/aws-cdk#19863]
### Describe the bug

ApiDestination.Builder.create(this, "AppSyncApiDestination") construct is missing.  

Method signature in 2.20 is

public static Builder create(final software.amazon.awscdk.services.events.IApiDestination apiDestination)

No other create method signature exists.

### Expected Behavior

Create call with scope and id.

### Current Behavior

Not available

### Reproduction Steps

ApiDestination.Builder.create(this, "AppSyncApiDestination").build();

### CDK CLI Version

2.20

### Node.js Version

6.14.15

### OS

Linux

### Language

Java

### Language Version

Java (11)

**Comment by rix0rrr** [comment]
This is a case of the example code being confusing because there are 2 different classes with the same name:

![2022-05-23 at 16 26](https://user-images.githubusercontent.com/524162/169842074-748cb710-f0cb-4385-b59e-e9d6212f6b42.png)

**Comment by rix0rrr** [comment]
Reported in jsii: https://github.com/aws/jsii/issues/3559
