### ISSUE TITLE
sam: SAMPolicyTemplateProperty missing SSMParameterReadPolicy

### ISSUE THREAD

**Issue by danikenan** [aws/aws-cdk#19872]
### Describe the bug

The `sam.CfnFunction` `policies` props has an option to specify `sam.CfnFunction.SAMPolicyTemplateProperty` which is a sam template policy as one of the policies, e.g `snsPublishMessagePolicy` but lacks other expected template policies, namely `ssmParameterReadPolicy`.

### Expected Behavior

The `sam.CfnFunction.SAMPolicyTemplateProperty` should include a `SSMParameterReadPolicy` member with a `ParameterName` child.

### Current Behavior

No such member exists

### Reproduction Steps

```ts
import { CfnFunction } from 'aws-cdk-lib/aws-sam';

new CfnFunction('', {
   policies: [

        // First two work just fine

        'AWSLambdaVPCAccessExecutionRole',
        {
          sqsSendMessagePolicy: {queueName: 'MyQueu'} 
        },

        //
        // following line will cause a compilation error as this policy is missing
        //
 
       {
           ssmParameterReadPolicy: {parameterName: 'MyParamName'}
        },
   ]

};)
```

### CDK CLI Version

2.20.0 (build 738ef49)

### Node.js Version

14

### OS

macos

### Language

Typescript

**Comment by peterwoodworth** [comment]
this is available
