### ISSUE TITLE
core: Cloudformation stack pseudo parameters are not untokenized as tag values

### ISSUE THREAD

**Issue by kmonihen** [aws/aws-cdk#19882]
### Describe the bug

When applying a tag with a value of `cdk.Aws.STACK_NAME` or `cdk.Fn.ref("AWS::StackName")`, or `cdk.Aws.STACK_ID` or `cdk.Fn.ref("AWS::StackId")` to a stack, the values stay tokenized rather than resolving to a value. This also happens to any custom resource roles deployed in the stack and causes a validation error.

### Expected Behavior

When you set a value of a tag using the StackId or StackName pseudo parameters, the values should resolve to the stack ID and stack name.

### Current Behavior

When you set a value of a tag using the StackId or StackName pseudo parameters, the values stay tokenized on the stack. Resulting in tags like:
```
stack_id	${Token[AWS.StackId.12]}
stack_name	${Token[TOKEN.29]}
```

When you set a value of a tag using the StackId or StackName pseudo parameters on a stack with a custom resource role, the untokenized values cause a validation error like:
```
CustomS3AutoDeleteObjectsCustomResourceProviderRole3B1BD092 (AWS::IAM::Role)
CREATE_FAILED
validation errors detected: Value '${Token[AWS.StackId.7]}' at 'tags.3.member.value' failed to satisfy constraint: Member must satisfy regular expression pattern: [\p{L}\p{Z}\p{N}_.:/=+\-@]*; Value '${Token[TOKEN.35]}' at 'tags.5.member.value' failed to satisfy constraint: Member must satisfy regular expression pattern: [\p{L}\p{Z}\p{N}_.:/=+\-@]* (Service: AmazonIdentityManagement; Status Code: 400; Error Code: ValidationError; Request ID: 1c40fa28-a883-4bdb-a3eb-a1b0574359ed; Proxy: null)
```

### Reproduction Steps

This code results in a stack named `testing-stack-tags` that has untokenized tags:

```
from aws_cdk import core as cdk, aws_s3

app = cdk.App()
stack = cdk.Stack(app, "testing-stack-tags")

aws_s3.Bucket(stack, "TestBucket")

cdk.Tags.of(stack).add("stack_id", cdk.Aws.STACK_ID)
cdk.Tags.of(stack).add("stack_name", cdk.Fn.ref("AWS::StackName"))

app.synth()
```

This code results in a CloudFormation validation error because the custom resource role from the bucket has an untokenized tag:

```
from aws_cdk import core as cdk, aws_s3

app = cdk.App()
stack = cdk.Stack(app, "testing-stack-tags")

aws_s3.Bucket(stack, "TestBucket", removal_policy=cdk.RemovalPolicy.DESTROY, auto_delete_objects=True)

cdk.Tags.of(stack).add("stack_id", cdk.Aws.STACK_ID)
cdk.Tags.of(stack).add("stack_name", cdk.Fn.ref("AWS::StackName"))

app.synth()
```

### CDK CLI Version

2.20.0 (build 738ef49)

### Framework Version

1.152.0

### Node.js Version

14.17.0

### OS

Linux

### Language

Python

### Language Version

Python (3.8.5)

**Comment by otaviomacedo** [comment]
@kmonihen FWIW, CloudFormation already [does that][1] for you:

> In addition to any tags you define, CloudFormation automatically creates the following stack-level tags with the prefix `aws:`:
>
>   `aws:cloudformation:logical-id`
>   `aws:cloudformation:stack-id`
>   `aws:cloudformation:stack-name`

When you look at the console, you won't see these tags in the "Tags" section, but they will be propagated to whatever resources propagation is allowed.

Does this solve your problem?

[1]: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-resource-tags.html

**Comment by kmonihen** [comment]
Thanks, but this is still a bug isn't it?

> they will be propagated to whatever resources propagation is allowed

I'm trying to use this as a way to tag resources that do not allow propagation.

**Comment by otaviomacedo** [comment]
> Thanks, but this is still a bug isn't it?

@kmonihen The problem is: CloudFormation does not allow you to apply tags to a stack _in the template_. It has to be sent as a parameter in API calls. This means that any potential token present in the tags would have to be resolved to their final value (not an implicit CloudFormation reference, but the actual account number, for example) before being sent to the CloudFormation service. This is not the responsibility of the CDK CLI, but of CloudFormation itself.
