### ISSUE TITLE
(ec2): Create a SecurityGroup object in stack, by ID, without any call to AWS

### ISSUE THREAD

**Issue by florian-thoni-sonarsource** [aws/aws-cdk#19892]
### Describe the feature

Currently, if you make a `classmethod from_security_group_id`, whatever it is mutable or not, it will fetch AWS to retrieve the igress rules.
We should have a function to add an existing SG , by ID, to the stack without any call to AWS.

### Use Case

When you create a lambda function for instance, you need a SG object, but if you import it you don’t need the igress or egress rules and then call to AWS is useless.

### Proposed Solution

Create a new static method, like for VPC the fromVpcAttributes method that will create the object immutable without any call to AWS.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

1 and 2 for Python

### Environment details (OS name and version, etc.)

Any

**Comment by corymhall** [comment]
@florian-thoni-sonarsource can you provide an example of the CDK code you are using and the results
you are getting / expecting?

**Comment by florian-thoni-sonarsource** [comment]
Let imagine you do:

```python
        function = aws_lambda.Function(
            stack,
            self.keyword,
            code=aws_lambda.Code.from_asset(
                LambdaFunctionCodePackager(
                    source_path=self.source_path
                ).get_packaged_code_path()
            ),
            description=self.description,
            environment=self.environment_variables,
            function_name=self.function_name,
            handler=self.handler,
            runtime=aws_lambda.Runtime.PYTHON_3_9,
            timeout=core.Duration.seconds(self.timeout_s),
            vpc=vpc,
            vpc_subnets=vpc_subnets,
            security_groups=security_groups,
        )
```

The vpc and security_groups have to be real objects, not ids.

But if they are from another stack, you may want to be able to synthesize the app without fetching the reality of what is in the account and take your own responsibility on the fact it exist or not.

But this is not possible, because whatever the case, with the constructor and factories existing for security groups, unlike vpcs, you don’t have any option to create it without querying aws at all.

**Comment by corymhall** [comment]
@florian-thoni-sonarsource Can you provide a more complete code example, including how you are
importing the security group? If you are doing something like this, it shouldn't be making any API
calls.

```ts
ec2.SecurityGroup.fromSecurityGroupId(this, 'ImportedSg', 'sg-xxxxx');
```

**Comment by florian-thoni-sonarsource** [comment]
Hi @corymhall, thank you for the answer!

I’m doing the following:
```
aws_ec2.SecurityGroup.from_security_group_id(
                    self.lambda_vpc_stack, 
                    f"{self.lambda_keyword}sg{index}",
                    security_group_id,
                    mutable=False,
                )
```
And it queries aws to get the ingress rules. The egress rules are not queried, except if you request it, but the ingress they are.

But in some context even the ingress rule, we don’t need them (example for the case I showed here with lambda).

![image](https://user-images.githubusercontent.com/98598207/165555663-e91f4e1d-2f75-4cef-88e3-167f9335f635.png)

**Comment by corymhall** [comment]
@florian-thoni-sonarsource I'm still not sure I understand what is happening. Can you provide a more
complete example including the CloudFormation template that is produced? If I import a security
group via `from_security_group_id` I don't see any ingress rules being created.
