### ISSUE TITLE
(aws-eks): EKS Cluster's Private subnets are resolved but not the Security Group

### ISSUE THREAD

**Issue by youngjeong46** [aws/aws-cdk#19900]
### Describe the bug

I created an EKS cluster within a stack and need to tag its resources. I am trying to use an AwsSdkCall to tag private subnets and cdk.Tags to tag Cluster Security group.

When I use the cluster.vpc.privateSubnets, I am able to resolve a list of private subnets; however, when I use cluster.clusterSecurityGroup, I am not. What could be an issue here?

### Expected Behavior

I'd expect to be able to tag both Private subnets and Cluster Security group.

### Current Behavior

Private subnets are tagged successfully, but the Cluster Security Group cannot be tagged because the token is unresolved.

### Reproduction Steps

```typescript
const subnets = cluster.vpc.privateSubnets;
const securityGroup = cluster.clusterSecurityGroup; //THIS RESULTS IN UNRESOLVED TOKEN

// THIS WORKS
if (subnetTags){
    Object.entries(subnetTags).forEach(
          ([key, value]) => {
              tagSubnets(cluster.stack, subnets, key, value);
      });
}

// THIS DOES NOT WORK
if (securityGroupTags) {
    Object.entries(securityGroupTags).forEach(
        ([key, value]) => {
            Tags.of(securityGroup).add(key,value);
        }
    );
}
```

### CDK CLI Version

2.17.0

### Node.js Version

v16.13.2

### OS

MacOS 10.15.7

### Language

Typescript

### Language Version

4.1.2

**Comment by pahud** [comment]
As this issue has been a while. Just FYI that eks.Cluster now supports [tags](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_eks.Cluster.html#tags) prop.

And you should consider using [Tags](https://docs.aws.amazon.com/cdk/v2/guide/tagging.html) class to tag all supported resources.

Let me know if it works for you.
