### ISSUE TITLE
Add kms encryption key as argument for cdk bootstrap for ECR

### ISSUE THREAD

**Issue by tenjaa** [aws/aws-cdk#19913]
### Describe the feature

When bootstrapping an account there is always an ECR repository created. I want to be able to encrypt it with a customer managed KMS key.

### Use Case

We have the requirement to encrypt everything with a CMK.

### Proposed Solution

It is already possible for the S3 bucket and could be solved in a similar way.
https://github.com/aws/aws-cdk/issues/2203

### Acknowledgements

- [x] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.20.0

### Environment details (OS name and version, etc.)

OSX

**Comment by lennart-land** [comment]
I am interested in creating a Pull Request to resolve this.
My question is, should i reuse the existing Key which was implemented in the issue @tenjaa mentioned or should it be a separate key?

**Comment by lennart-land** [comment]
Hi @skinny85 
we had a closer look at the bootstrap and found it hard to provide a good solution without a breaking change.
In the current implementation there seem to be some conflicting namings.

There is `bootstrap-kms-key-id` and `bootstrap-customer-key` but only the key-id is part of the collection `toolkitBucket`. This indicates that `bootstrap-customer-key` is a general flag and when set should create a key for everything, not just the bucket. But the description of that option contradicts that.
Our idea was to have `bootstrap-kms-s3-key-id` and `bootstrap-kms-ecr-key-id` but reuse `bootstrap-customer-key`. Though this would be a breaking change. What do you think?

Another point we struggled with is in the bootstrap.yaml template. The resource name of the cmk which is created refers to the bucket but the alias has a generic `cdk-...-assets` name. Should we use this key for the ECR too? Renaming the resource name would be a breaking change but is also not really necessary. When not it would be also possible to just rename the alias and create a second key.

We dont really want to run in the wrong direction, so some guidance would be appreciated! :)

**Comment by skinny85** [comment]
Hey @lennart-land! Thanks a lot for your interest in opening us a PR with this feature.

As for answering your questions:

1. The difference between `--bootstrap-kms-key-id` and `--bootstrap-customer-key` is that the former uses an already existing Key, while the latter creates a new Key.

    Let's maybe go with just `--bootstrap-ecr-key`, and make it optionally take a string argument, which is a KMS Key ID. If the ID is provided, we will use that Key; if it was not provided, we'll create a new Key.

2. Yes, I would use the same Key (and Alias) for the ECR repository as the S3 Bucket. The reason is that each Key costs $1/month. So, I would avoid using two different ones.

    So, again: if `--bootstrap-ecr-key` was passed, use the new KMS Key for the ECR Repository (unless the customer passed an option to `--bootstrap-ecr-key`, in which case use a Key with that ID/ARN).

Hope this helps!

**Comment by skinny85** [comment]
@rix0rrr will probably have some opinions here too 🙂.

**Comment by lennart-land** [comment]
Hi @skinny85,

thanks for the response! I like your idea of having only an additional `--bootstrap-ecr-kms-key-id` argument. 
However using the `--bootstrap-customer-key` for the assets bucket and the ecr repository will break already bootstrapped ecr repositories cause they will be encrypted with the `FileAssetsBucketEncryptionKey` which is only possible via replacement of the resource.

**Comment by DavidSchwarz2** [comment]
Hey @skinny85,

I created a Pull-Request. Manual tests with the new option by bootstrapping a new environment were successful.

**Comment by madeline-k** [comment]
Closing this issue for the same reasoning as @rix0rrr described in the linked PR: https://github.com/aws/aws-cdk/pull/20192#issuecomment-1254737198. If you are still interested in discussing this with the CDK team and community, please open a [discussion](https://github.com/aws/aws-cdk/discussions).
