### ISSUE TITLE
(aws-kms): grant permission not working for kms keys imported from alias name

### ISSUE THREAD

**Issue by dannysteenman** [aws/aws-cdk#19914]
### Describe the bug

When I import the kms key from alias name e.g.
`const snsKeyAlias = kms.Alias.fromAliasName(this, 'awsSnsKeyAlias', 'awsSnsTopicKey');`

and want to grant my ecs task role km decrypt permission e.g.

`snsKeyAlias.grantEncryptDecrypt(purchaseService.taskDefinition.taskRole);`

The policy of the task role isn't updated with the kms decrypt permission.

### Expected Behavior

I expect it to add the permission to the policy. For example, when I import the key from arn it works e.g.

const snsKeyArn = kms.Key.fromKeyArn(this, 'awsSnsKey', 'arn:aws:kms:eu-west-1:012345678901:key/<key_id>');

Then grant permission like so:
`snsKeyArn.grantDecrypt(purchaseService.taskDefinition.taskRole);`

### Current Behavior

.

### Reproduction Steps

Run the examples I supplied in the previous two paragraphs.

### CDK CLI Version

2.18.0

### Node.js Version

v16.14.2

### OS

MacOS

### Language

Typescript

### Language Version

4.6.3

**Comment by skinny85** [comment]
Hi @dannysteenman,

thanks for opening the issue. This most likely stems from the fact that you can't use Aliases in IAM Policies - only the Key can be used in those.

Thanks,
Adam

**Comment by dannysteenman** [comment]
Thanks for the response! I understand that you can't use an alias in a policy but it would be nice if cdk can translate it and turn it into an arn for the policy since cdk knows the arn  of the imported keyalias.

The reason for this request is the following:
I got multiple stages where I deploy kms keys and I'm adding a predictable keyalias for each stage so I can easily import it in another cdk app and apply conditions to my code to choose the proper key based on the stage.

Now I need to copy the arn of each stage and put it in the code which makes it way more cumbersome and less human readable. If you need an example, please let me know.

**Comment by skinny85** [comment]
Unfortunately, I don't think there's anything we can do here. Remember that CDK doesn't do any service calls when using methods like `fromAliasName()`, so there's no way to find out the ARN of the Key just based on the Alias.

Any reason you need to share the Keys between multiple CDK apps? If you managed the Keys in the same app as uses them, you wouldn't run into this problem.

**Comment by skinny85** [comment]
I'm resolving this one, please comment if you need anything else from our side.

**Comment by kamzil** [comment]
How is this resolved? Why can't this code  
```
const keyAlias = Alias.fromAliasName(this, 'my-key-alias', 'my/key/alias')
keyAlias.grantDecrypt(lambdaFunc)
```
function as a short-hand for:

```
lambdaFunc.role?.addToPrincipalPolicy(
  new PolicyStatement({
    actions: [
      "kms:Decrypt",
    ],
    resources: ['*'],
    conditions: {
      StringEquals: {
        "kms:RequestAlias": "my/key/alias",
      },
    },
  }),
)
```
?

Why would this need any service calls?

**Comment by skinny85** [comment]
@kamzil you can't do that, because you cannot use Key aliases in IAM policies. Only Key ARNs.

**Comment by bruecktech** [comment]
This information may be outdated. It is possible to use `kms:ResourceAlias` now. See the docs [here](https://docs.aws.amazon.com/kms/latest/developerguide/alias-authorization.html#alias-auth-resource-aliases).  
It allows controlling access to KMS keys based on the alias configured on the key no matter how the key is accessed (alias, arn, ID). So it would be great if `keyAlias.grant...` would translate to the respective policies including the conditions.

**Comment by avoidik** [comment]
could you please consider to reopen this issue?
