### ISSUE TITLE
dynamodb: DeletionPolicy and UpdateReplacePolicy

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#1992]
`dynamo.Table` should set `DeletionPolicy` and `UpdateReplacePolicy` by default

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-updatereplacepolicy.html

**Comment by skinny85** [comment]
Still relevant (although might be considered backwards-compatibility breaking...).

**Comment by skinny85** [comment]
Sorry - this was done already: http://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-dynamodb/lib/table.ts#L258-L258 . Resolving.
