### ISSUE TITLE
(stepfunctions): add Parameters field on Parallel Step

### ISSUE THREAD

**Issue by lucaslra** [aws/aws-cdk#19933]
### Describe the feature

Add the `parameters` field to the Parallel step on CDK (already usable on the States language)

### Use Case

I would like to be able to use the "parameters" field on a parallel state through CDK in the same way I do with the step functions editor

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

1.140.0

### Environment details (OS name and version, etc.)

MacOS

**Comment by kaizen3031593** [comment]
For reference: https://docs.aws.amazon.com/step-functions/latest/dg/input-output-inputpath-params.html#input-output-parameters

Is this specific to parallel states or can other states have parameters as well? Not necessarily asking you to add more to the PR, just curious.
