### ISSUE TITLE
@aws-events: Cross account Rule tries to create a EventBusPolicy which fails with ValidationException

### ISSUE THREAD

**Issue by sahilpalvia** [aws/aws-cdk#19941]
### Describe the bug

When trying to upgrade past version 1.150 we ran into ValidationException while trying to create a EventBusPolicy cross account. This failure is probably happening because of the following line

```
statementId: `Allow-account-${sourceAccount}-${this.node.addr}`,
```

It can be found here: https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-events/lib/rule.ts#L400.

### Expected Behavior

Expectation was nothing to change with regard to the statement id, or even if it did the code should just work and not cause CFN to throw a ValidationException (400).

### Current Behavior

This is the error you will see

```
1 validation error detected: Value 'Allow-account-ACCOUNT-NODE_ADDR' at 'statementId' failed to satisfy constraint: Member must have length less than or equal to 64 (Service: AWSEvents; Status Code: 400; Error Code: ValidationException; Request ID: REQUEST_ID; Proxy: null)
```

### Reproduction Steps

Try to create a rule that works cross account.

### Possible Solution

Validate the length of the statement id and strip any characters after 64 characters.

### CDK CLI Version

1.152.0

### Node.js Version

14

### OS

CodeBuild Standard 5.0

### Language

Typescript

### Language Version

4.6.3

**Comment by comcalvi** [comment]
Please provide detailed reproduction information. What constructs are in what account? How is this Rule used in a different account? If you can, please provide stacks that reproduce this issue.
