### ISSUE TITLE
Customer feedback via AWS Twitter

### ISSUE THREAD

**Issue by aualdrid** [aws/aws-cdk#19972]
### Describe the feature

TypeScript CDK Release

### Use Case

Hi I'm from AWS social media support team and I'm reaching out because a customer reached out via Twitter and provided feedback that we thought might interest you, 

Link to Tweet: https://twitter.com/ofhouse/status/1516454707287539727?s=20&t=P3Cmo85xYQvz4RtVe2k_Vg

"Bit frustrating that CDK was not a launch partner of this feature while numerous third party were."

We replied to customer and let them know their feedback had been heard. 

Question
Is the feedback possible or in the works? 
If it is not in the works, is it possible? 

If a public announcement about the feedback is made, we like to show are customer obsession by following up with the customer. 

Please feel free to re-assign or recommend a more appropriate path for the feedback. 

Thanks

### Proposed Solution

no suggestion provided by customer

### Acknowledgements

- [X] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### CDK version used

unknown

### Environment details (OS name and version, etc.)

unknown

**Comment by peterwoodworth** [comment]
We appreciate the feedback @aualdrid.

This feature will be part of the next CDK release (link to [feature](https://github.com/aws/aws-cdk/pull/19817)) which will likely be some time this week. The customer seems to be aware of this given their specific wording of "looking forward to the next release"

Customer's feedback about us not supporting this at the launch of the feature is valid. In the future we will try to be more in sync with AWS services as they launch new features.

Thanks, 
Peter
