### ISSUE TITLE
Add require_imdsv2 parameter to add_nodegroup_capacity method

### ISSUE THREAD

**Issue by rollufie** [aws/aws-cdk#19984]
### Describe the feature

Add require_imdsv2 parameter to add_nodegroup_capacity method.
Currently this is not possible to remediate IMDSv2 in a simple manner.

### Use Case

We have to do a workaround through MetaDataOptions for launch_template_spec while it could be a simple parameter in the method

### Other Information

Add require_imdsv2 parameter to add_nodegroup_capacity method.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

1.145.0

### Environment details (OS name and version, etc.)

al2

**Comment by samhopwell** [comment]
Appreciate this is quite old however it still remains an issue. Is there any update on this?

**Comment by peterwoodworth** [comment]
It would be a good first issue to contribute. Check out our [contributing guide](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md), the team won't have time to get to this soon so we'll rely on customer contribution

**Comment by venkivijay** [comment]
[CfnNodeGroup](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-eks-nodegroup.html) doesn't accept any configuration related to IMDSV2. And the LT or ASG created internally for MNG is not exposed anywhere. I think CfnNodeGroup support for IMDSV2 is required to implement this feature. Please correct me if I am wrong.
