### ISSUE TITLE
(eks): CfnCluster property type changed from primitiveType Json to ProviderProperty

### ISSUE THREAD

**Issue by erayit** [aws/aws-cdk#19991]
### Describe the bug

After updating to CDKLib v2.20.0 our EKS Cluster Stacks are failing to deploy with the following error message: "CloudFormation cannot update a stack when a custom-named resources requires replacing"   

The root cause appears to be related to the CfnClusterProps --> EncryptionConfiguration property which is no longer being synthesized correctly, v2.20.0 is omitting the Encryption provider section in the CF template.

Downgrading to a version <= 2.19.0 corrects the issue

### Expected Behavior

When using CfnClusterProps with the EncryptionConfig set to the following:

```
EncryptionConfig = new[]
                    {
                        new EncryptionConfigProperty
                        {
                            Provider = new Dictionary<string, string>
                            {
                                {
                                    "KeyArn", "ARN HERE")
                                }
                            },
                            Resources = new[] { "secrets" }
                        }
                    }
```
The expected output in the CF template should be:
```
  "EncryptionConfig": [
          {
            "Provider": {
              "KeyArn": "ARN HERE"
            },
            "Resources": [
              "secrets"
            ]
          }
        ]
```
### Current Behavior

After upgrading to CDK v2.20.0 and using CfnClusterProps with the EncryptionConfig set to the following:
```
EncryptionConfig = new[]
                    {
                        new EncryptionConfigProperty
                        {
                            Provider = new Dictionary<string, string>
                            {
                                {
                                    "KeyArn", "ARN HERE")
                                }
                            },
                            Resources = new[] { "secrets" }
                        }
                    }
```
The template is generated without the provider
```
  "EncryptionConfig": [
     {
      "Resources": [
       "secrets"
      ]
     }
    ]
```
### Reproduction Steps

1. Generate an EKS cluster using the following configuration:
```
new CfnCluster(
                this,
                "my-cluster-id",
                new CfnClusterProps
                {
                    Name = "my-cluster-name",
                    ResourcesVpcConfig = new ResourcesVpcConfigProperty
                    {
                        SubnetIds = new[] {"subnet1", "subnet2"},
                        SecurityGroupIds = new[] { "security-group-1" }
                    },
                    EncryptionConfig = new[]
                    {
                        new EncryptionConfigProperty
                        {
                            Provider = new Dictionary<string, object>
                            {
                                {
                                    "KeyArn", "ARN HERE"
                                }
                            },
                            Resources = new[] { "secrets" }
                        }
                    },
                    RoleArn = "ClusterRole ARN HERE",
                    Version = "1.21",
                    Logging = new LoggingProperty
                    {
                        ClusterLogging = new ClusterLoggingProperty
                        {
                            EnabledTypes = new[]
                            {
                                new LoggingTypeConfigProperty { Type = "api" },
                                new LoggingTypeConfigProperty { Type = "audit" },
                                new LoggingTypeConfigProperty { Type = "authenticator" },
                                new LoggingTypeConfigProperty { Type = "controllerManager" },
                                new LoggingTypeConfigProperty { Type = "scheduler" },
                            }
                        }
                    }
                }
            );
```
2. Configure the project to use CDK <= v2.19.0
3. Run cdk synth
4. Check the template for EncrytionConfiguration, Provider section
5. Configure the project to use CDK v2.20.0
6. Run cdk synth
7. Check the template for EncryptionConfiguration, Provider section (will be missing)

### CDK CLI Version

2.20.0 (build 738ef49)

### Node.js Version

v16.9.0

### OS

OSX Monterey 12.2.1

### Language

.NET

### Language Version

dotnet 3.1

**Comment by peterwoodworth** [comment]
As of [patch 2.20](https://github.com/aws/aws-cdk/releases/tag/v2.20.0) we integrated the most recent [CloudFormation specs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html). One of the changes made in [spec 63.0.0](https://github.com/aws/aws-cdk/pull/19679/files#) was updating the type of EncryptionConfig.Provider from a Json primitive type to a [Provider](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-eks.CfnCluster.ProviderProperty.html) type

The [.NET docs page on CfnCluster](https://docs.aws.amazon.com/cdk/api/v1/dotnet/api/Amazon.CDK.AWS.EKS.CfnCluster.html) has a generated example showing how to use the new property 🙂 

Apologies for the experience here

**Comment by erayit** [comment]
@peterwoodworth - Thank you very much, sorry I missed that.  We will refactor and re-test.

**Comment by erayit** [comment]
This resolved the issue, thanks again.
