### ISSUE TITLE
custom_resources: Node version 12 out of support

### ISSUE THREAD

**Issue by sholtomaud** [aws/aws-cdk#19992]
### Describe the bug

custom_resources builds a NodeJs lambda @ v12 of node which is out of support in 11 days.

### Expected Behavior

custom_resources should track LTS

### Current Behavior

tracks maintenance/deprecated version

### Reproduction Steps

use module

### CDK CLI Version

all

### Framework Version

all

### Node.js Version

12

### OS

all

### Language

Typescript

### Language Version

3.8.3

**Comment by Naumel** [comment]
Two updates on this:
- a PR was submitted (#20531)
- there is a blocker with regards to the [runtime's](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html) [region availability](https://aws.amazon.com/about-aws/whats-new/2022/05/aws-lambda-adds-support-node-js-16/)
> The Node.js 16 runtime is available in all [Regions where Lambda is available](https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/), except for the AWS China Region (Beijing) Region, operated by Sinnet and AWS China (Ningxia) Region, operated by NWCD"s.
