### ISSUE TITLE
`--hotswap` does not see `CfnOutput` change

### ISSUE THREAD

**Issue by ppena-LiveData** [aws/aws-cdk#19998]
### Describe the bug

`cdk deploy --hotswap` should notice if any non-Lambda changes need to be deployed, but it fails to see when there has been a `CfnOutput` change, e.g. a different output name.

### Expected Behavior

`cdk deploy --hotswap` would see that a `CfnOutput` changed and deploy the changes instead of hotswapping.

### Current Behavior

If a `CfnOutput`'s name changes, `cdk deploy --hotswap` thinks it only needs to hostswap, so the `CfnOutput`'s name does not change.

### Reproduction Steps

1. `cdk deploy` a stack that includes a `CfnOutput`
2. make an edit to the `CfnOutput`'s name
3. run `cdk deploy --hotswap`
4. *Expected behavior*: `CfnOutput`'s name should change
   *Actual behavior*: `✨ hotswapping resources:` is printed and the `CfnOutput`'s name does not change

### CDK CLI Version

2.20.0

### Node.js Version

v14.16.0

### OS

Windows 10

### Language

Python

**Comment by skinny85** [comment]
Thanks for opening the issue @ppena-LiveData. You are correct - right now, we are only taking into account resource changes for hotswapping (code is [here](https://github.com/aws/aws-cdk/blob/aa834be09aaf87dded7736e85de8cd1b37250ee1/packages/aws-cdk/lib/api/hotswap-deployments.ts#L71-L71)).

We should update that to simply skip hotswapping completely if we detect any non-resource changes.
