### ISSUE TITLE
(lambda-event-sources): Add HttpApiEventSource

### ISSUE THREAD

**Issue by Dreamescaper** [aws/aws-cdk#20018]
### Describe the feature

Currently you can write `lambdaFunction.AddEventSource(new ApiEventSource("GET", "/details"));`, but it works with RestApi only. It would be great to have similar for HttpApi.

### Use Case

Define lambda and corresponding route in a single place, using HttpApi.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.2.0

### Environment details (OS name and version, etc.)

dotnet6

**Comment by kaizen3031593** [comment]
This sounds like something we'd want to support but I'm going to prioritize this as `p2` for now, which means we aren't going to work on it currently and are waiting to see community response (via +1s) on whether this is highly desirable.

At the moment, I think you could implement what you want yourself by implementing the `IEventSource` interface:

```ts
export class HttpsApiEventSource implements lambda.IEventSource {
  constructor(private readonly method: string, private readonly path: string, private readonly options: HttpsApiEventSourceOptions) {
  }

  public bind(target: lambda.IFunction): void {
    // this is the important function to implement
  }
}
```
