### ISSUE TITLE
cdk_rds: PostgresEngineVersion attribute `VER_13_6` not found.

### ISSUE THREAD

**Issue by Mat-moran** [aws/aws-cdk#20037]
### Describe the bug

`PostgresEnginVersion` has not attribute `VER_13_6`

### Expected Behavior

this version should be available as has been implemented by https://github.com/aws/aws-cdk/pull/19500 . 

### Current Behavior

```
Traceback (most recent call last):
  File "app.py", line 52, in <module>
    test_stack = OdooTestStack(
  File "/Users/amadeomoranguerrero/Library/Python/3.8/lib/python/site-packages/jsii/_runtime.py", line 86, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/amadeomoranguerrero/GitHub/dm-integrations/awscdk-odoo-infrastructure/awscdk_odoo_infrastructure/odoo_test_stack.py", line 78, in __init__
    version=rds.PostgresEngineVersion.VER_13_6
AttributeError: type object 'PostgresEngineVersion' has no attribute 'VER_13_6'

Subprocess exited with error 1
```

![image](https://user-images.githubusercontent.com/4810013/164696842-ac0c8464-550d-4b8a-991b-e57a6ace4bc0.png)

### Reproduction Steps

Create e new cdk app by invoking `cdk init app --language python` and change the file `testing_cdk_stack.py` for the content below:

```python
from aws_cdk import (
    # Duration,
    Stack,
    # aws_sqs as sqs,
)
from constructs import Construct
import aws_cdk.aws_rds as rds


class TestingCdkStack(Stack):
    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        # The code that defines your stack goes here

        #######################################################################
        # RDS db instance
        db_engine = rds.DatabaseInstanceEngine.postgres(
            version=rds.PostgresEngineVersion.VER_13_6
        )
```

execute `cdk diff` and you should see the error:
```
Traceback (most recent call last):
  File "app.py", line 10, in <module>
    TestingCdkStack(app, "TestingCdkStack",
  File "/Users/user/Library/Python/3.8/lib/python/site-packages/jsii/_runtime.py", line 86, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/user/kk/testing-cdk/testing_cdk/testing_cdk_stack.py", line 19, in __init__
    version=rds.PostgresEngineVersion.VER_13_6
AttributeError: type object 'PostgresEngineVersion' has no attribute 'VER_13_6'

Subprocess exited with error 1

```

### CDK CLI Version

2.20.0 (build 738ef49)

### Node.js Version

17.3.1

### OS

macOS Monterey 12.3.1 (21E258)

### Language

Python

### Language Version

Python 3.8

**Comment by peterwoodworth** [comment]
I can't reproduce this @Mat-moran, are you sure the packages installed in your project are actually `v2.20.0`? I suggest reinstalling your packages 🙂 
<img width="303" alt="Screen Shot 2022-04-22 at 1 10 25 PM" src="https://user-images.githubusercontent.com/44349620/164787041-b7a8ed09-ac41-4f84-868e-fe9bcea824fd.png">

**Comment by skinny85** [comment]
Running `pip list | grep cdk` should help 🙂.

**Comment by Mat-moran** [comment]
You are correct I was using `aws-cdk-lib       2.13.0`.
Now I updated to `aws-cdk-lib       2.21.1` and did not fail .

Thanks yo very much!! @skinny85 @peterwoodworth
