### ISSUE TITLE
aws-lambda: Missing `cdk.out` directory causes EACCES: permission denied

### ISSUE THREAD

**Issue by scotthasse** [aws/aws-cdk#20061]
### Describe the bug

When deploying a lambda.Function that uses lambda.Code.fromAsset to include an external `.zip` file, if the `cdk.out` directory does not exist the deploy operation fails with `Error: EACCES: permission denied, copyfile`. 

### Expected Behavior

The deploy should succeed.

### Current Behavior

The deploy fails with the following error:
```sh
Error: EACCES: permission denied, copyfile '<path>/build/distributions/lambda-0.1.0-SNAPSHOT.zip' -> '<path>/cdk.out/asset.cf9a19d668025cf5457c96d8de9c4d5918528040fbbee0870689f58bdaf41ad2.zip'
    at Object.copyFileSync (node:fs:2804:3)
    at AssetStaging.stageAsset (<path>/node_modules/aws-cdk-lib/core/lib/asset-staging.ts:382:10)
    at AssetStaging.stageByCopying (<path>/node_modules/aws-cdk-lib/core/lib/asset-staging.ts:279:10)
    at stageThisAsset (<path>/node_modules/aws-cdk-lib/core/lib/asset-staging.ts:190:35)
    at Cache.obtain (<path>/node_modules/aws-cdk-lib/core/lib/private/cache.ts:24:13)
    at new AssetStaging (<path>/node_modules/aws-cdk-lib/core/lib/asset-staging.ts:213:44)
    at new Asset (<path>/node_modules/aws-cdk-lib/aws-s3-assets/lib/asset.ts:131:21)
    at AssetCode.bind (<path>/node_modules/aws-cdk-lib/aws-lambda/lib/code.ts:2:20)
    at new Function (<path>/node_modules/aws-cdk-lib/aws-lambda/lib/function.ts:699:29)
    at new LambdaStack (<path>/lambda/lib/lambda-stack.ts:10:21)
```

### Reproduction Steps

1. After initializing a basic CDK environment, create this lambda-stack.ts:

```ts
import { Duration, Stack, StackProps } from 'aws-cdk-lib';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

export class LambdaStack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);

    // defines an AWS Lambda resource
    const handler = new lambda.Function(this, 'Handler', {
      functionName: process.env.CDK_QUALIFIER + '-HelloWorldLambda',
      runtime: lambda.Runtime.JAVA_11,  // execution environment
      code: lambda.Code.fromAsset('build/distributions/lambda-0.1.0-SNAPSHOT.zip'),
      handler: 'Handler::handleRequest',
      memorySize: 1024,
      timeout: Duration.seconds(30)
    });
  }
}
```
reference an external .zip file that already exists.

2. Delete the `cdk.out` directory and attempt a deploy.

### Possible Solution

The `cdk.out` directory is typically created ahead of time, but is explicitly excluded from being stored in git by the generated `.gitignore`. This means that if you check the repo into source control and check it out elsewhere and attempt to run, you will encounter this issue.  Ideally, the deploy process should check that the `cdk.out` directory exists and create it if it does not exist. Alternatively, `cdk.out` should not be fully excluded from revision control, but rather the directory included but no contents.

### CDK CLI Version

2.20.0 (build 738ef49)

### Framework Version

?

### Node.js Version

v16.14.2

### OS

Ubuntu 20.04.4 LTS

### Language

Typescript

### Language Version

TypeScript (~3.9.7)

**Comment by enniomara** [comment]
I have also encountered this issue, in my case when running `cdk synth`. In my case, I mount the source code inside a docker container and try to run `cdk synth` there (i.e. the container runs as uid=0 but the files have another owner).

The dockerfile below hopefully reproduces this bug, note that the chown is done to simulate volume mounting. 

```
FROM debian:stable-slim
RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y --no-install-recommends \
        curl \
        npm \
    && rm -rf /var/lib/apt/lists

RUN npm install -g n && n v16.17
RUN npm install -g aws-cdk@2.39.1

WORKDIR app
RUN cdk init app --language=typescript

RUN chown -R 10001:10001 /app

RUN cdk synth
```

**Comment by codermarcos** [comment]
If someone is experiencing this issue while using Visual Studio Code (VS Code), I've noticed that the problem is likely related to VS Code: kkkkkcry 🥲
https://stackoverflow.com/questions/60853873/eaccess-error-when-installing-packages-on-wsl

**Comment by pahud** [comment]
I can't reproduce this in cdk 2.150.0 now using the provided code snippets with `cdk.out` deleted before `cdk deploy`.

This could have been fixed. Is this still relevant?
