### ISSUE TITLE
(cli): Resulting Stack ARN is output at the wrong time

### ISSUE THREAD

**Issue by philasmar** [aws/aws-cdk#20075]
### Describe the bug

From the command line, I redeployed my application to an existing Stack (Beanstalk Environment). When the deploy completed, it did not output the actual stack ARN underneath the "Stack ARN:" heading. 

**Logs**

```
  2/4 | 10:40:59 AM | DELETE_COMPLETE      | AWS::ElasticBeanstalk::ApplicationVersion | Recipe/ApplicationVersion (RecipeApplicationVersion145C922C)
  3/4 | 10:41:00 AM | UPDATE_COMPLETE      | AWS::CloudFormation::Stack                | MyAspNetCoreAppBs1

 ✅  MyAspNetCoreAppBs1
arn:aws:cloudformation:us-west-2:xxxxx:stack/MyAspNetCoreAppBs1/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

Stack ARN:


Resources
---------
Application Endpoint:
        Id: xxxxxxx-dev
        Type: AWS::ElasticBeanstalk::Environment
        Endpoint: http://xxxxxxx.us-west-2.elasticbeanstalk.com/
```

**Environment (please complete the following information):**
 - CLI Version: 0.34.5+7b97884b91
 - OS Info: Windows 10

### Expected Behavior

Notice how "arn:aws:cloudformation:us-west-2:xxxxx:stack/MyAspNetCoreAppBs1/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" did not get written underneath "Stack ARN:"

### Current Behavior

The stack arn is printed before "Stack ARN:"

### Reproduction Steps

Create an application that deploys to beanstalk. The resulting Stack ARN should be printed in the incorrect place.

### CDK CLI Version

2.13.0

### Node.js Version

10

### OS

Any

### Language

.NET

**Comment by rix0rrr** [comment]
Is this behavior consistent? It would surprise me if it had anything to do with ElasticBeanstalk.

**Comment by philasmar** [comment]
Yes, this behavior is consistent. All beanstalk deployments experience this issue/misalignment.
