### ISSUE TITLE
@aws-cdk/aws-s3-notifications: in SqsDestination it is not possible to provide an encrypted queue with an imported kms

### ISSUE THREAD

**Issue by noastern** [aws/aws-cdk#20070]
### Describe the bug

in SqsDestination it is not possible to provide an encrypted queue with an imported kms. 

### Expected Behavior

an s3-notifications should be created.

### Current Behavior

I get this error:

```sh
Error: Unable to add statement to IAM resource policy for KMS key: {"Fn::ImportValue":"hereIsThekeyArn"}
```

### Reproduction Steps

```ts
    const keyArn = Fn.importValue( ...);
    const key = Key.fromKeyArn(this,  'key' , keyArn);

    const bucket = new Bucket(this, `Bucket`, {...});

    const queue = new sqs.Queue(this, `queue`, {
      queueName: `queue`,
      encryption: sqs.QueueEncryption.KMS,
      encryptionMasterKey: key
    });

    bucket.node.addDependency(queue);

    bucket.addObjectCreatedNotification(new SqsDestination(queue)); // in this line I get an error.
```

### CDK CLI Version

1.133.0 (build 2dea31a)

### Node.js Version

v12.16.2

### OS

mac

### Language

Typescript

**Comment by indrora** [comment]
Closing as this ticket is stale (over 9 months since last event or relates to the CDKv1). 

If this is still a relevant request in the CDKv2, please open a new ticket.
