### ISSUE TITLE
CfnStack: Incorrect stack name

### ISSUE THREAD

**Issue by t-brown** [aws/aws-cdk#20088]
### Describe the bug

When using `CfnStack` to create a ParallelCluster API endpoint, the stack name returned by `.stack_name` is incorrect. Which means trying to use this stack elsewhere fails. For example the app:

### Expected Behavior

In the `S3Stack` the variable `purl` should contain the correct stack name created by `CfnStack`.

### Current Behavior

The `S3Stack` fails as the names of the Parallel Cluster API stack are incorrect.

The Parallel Cluster API stack name is:
```
WX-parallelclusterapiNestedStackparallelclusterapiNestedStackResource0BDAF-APITemplate-1XJ3GPYF0ESQ8-ParallelClusterApiInvokeUrl
```

While the value of `purl` is:

```
WX-parallelclusterapiNestedStackparallelclusterapiNestedStackResource0BDAF745-RN0MT305AFKH-ParallelClusterApiInvokeUrl
```

The error message received is:

```
Embedded stack arn:aws:cloudformation:us-east-2:XXXXX:stack/WX-s3NestedStacks3NestedStackResource4EAEB761-RA9QXBEPAAYU/bb0af8f0-c565-11ec-b12b-025dbee0d176 was not successfully created: No export named WX-parallelclusterapiNestedStackparallelclusterapiNestedStackResource0BDAF745-RN0MT305AFKH-ParallelClusterApiInvokeUrl found
```

As can be seen in the following screenshots.

![Toplevel stack error message](https://user-images.githubusercontent.com/3876306/165325118-e0aa4ab7-b4a2-46b7-aad1-d1b4c82a7e06.png)

![Parallel Cluster API outputs](https://user-images.githubusercontent.com/3876306/165325288-b31fb35e-f208-496f-b785-1388dd07d5a3.png)

### Reproduction Steps

The `app.py`:

```python
#!/usr/bin/env python3
import os

import aws_cdk as cdk

from test.network import VpcStack
from test.bucket import S3Stack
from test.pclusterapi import ParallelClusterApiStack

app = cdk.App()
wx = cdk.Stack(app, 'WX', env={'region': 'us-east-2'})
vpc = VpcStack(wx, "vpc", props)
pcluster_api = ParallelClusterApiStack(wx, "parallel-cluster-api", vpc.outputs)
pcluster_api.add_dependency(vpc)
s3 = S3Stack(wx, "s3", vpc.outputs, pcluster_api.outputs)
s3.add_dependency(vpc)
s3.add_dependency(pcluster_api)
```

The use of `CfnStack` to create a Parallel Cluster API endpoint. This is `wx/pclusterapi.py`

```python
from aws_cdk import (
        Aws,
        CfnOutput, CfnStack, NestedStack
)
from constructs import Construct

class ParallelClusterApiStack(NestedStack):

    def __init__(self, scope: Construct, construct_id: str, vpc, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)
        region = Aws.REGION
        version = "3.1.2"
        template_url = f"https://{region}-aws-parallelcluster.s3.{region}.amazonaws.com/parallelcluster/{version}/api/parallelcluster-api.yaml"
        params = {
                "ApiDefinitionS3Uri": f"s3://{region}-aws-parallelcluster/parallelcluster/{version}/api/ParallelCluster.openapi.yaml",
                "EnableIamAdminAccess": "true",
                }

        self.api = CfnStack(self, "APITemplate",
                template_url=template_url,
                parameters=params)

        CfnOutput(self, "pcaid", value=self.api.logical_id)

    @property
    def outputs(self):
        return {"stack": self.api,
                "stack_name": self.api.stack.stack_name,
                }
```

Then trying to use it in `wx/bucket.py`:

```python
from aws_cdk import (
    aws_lambda as _lambda,
    aws_ec2 as ec2,
    aws_s3 as _s3,
    aws_s3_assets as assets,
    aws_s3_notifications,
    Aws, CfnOutput, Fn, NestedStack
)
from constructs import Construct
class S3Stack(NestedStack):

    def __init__(self, scope: Construct, construct_id: str, vpc, pcluster_api, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        purl = Fn.import_value(f"{pcluster_api['stack_name']}-ParallelClusterApiInvokeUrl")
        lfunc = _lambda.Function(self, "lambda_function",
                                    runtime=_lambda.Runtime.PYTHON_3_7,
                                    handler="create-cluster.main",
                                    code=_lambda.Code.from_asset("./wx"),
                                    environment={"PCLUSTER_API_URL": purl}
                                    )
        s3 = _s3.Bucket(self, "test-bucket")
        notification = aws_s3_notifications.LambdaDestination(lfunc)
        s3.add_event_notification(_s3.EventType.OBJECT_CREATED, notification)

        CfnOutput(self, "s3id", value=s3.bucket_name)
```

### CDK CLI Version

2.20.0 (build 738ef49)

### Node.js Version

8.5.5

### OS

macOS

### Language

Python

### Language Version

3.9.12

**Comment by peterwoodworth** [comment]
Hey @t-brown,

I believe you're getting caught up by the [`CfnStack.stack` property](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_core.CfnStack.html#stack). This property isn't a property which returns the nested stack created by this construct. Instead, it returns the parent stack. (i.e. The stack in which you've defined the `CfnStack`)

So, this
```
"stack_name": self.api.stack.stack_name
```
will not return the stack name of the `api` nested stack. This will return the stack name of your `ParallelClusterApiStack` stack.

The value you want - the one that's being passed as an output is `api.logicalId`. This will return the name of your nested stack.

Additionally, to import a `CfnOutput` value from another stack, you will want to define the [`exportName`](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_core.CfnOutput.html#exportname-1) prop on the `CfnOutput` you intend to access in another stack.

Here's a couple sample stacks I created to demonstrate how this all works, using our [`NestedStack` construct](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_core.NestedStack.html), which creates a `CfnStack` under the hood:

Stack with nested stack and CfnOutput:
```ts
export class OutputStack extends Stack {
    constructor(scope: Construct, id: string, props?: StackProps) {
        super(scope, id, props);

        const nestedStack = new NestedStack(this, 'CfnStack');
        if (nestedStack.nestedStackResource) { // nestedStack.nestedStackResource is a CfnStack
            new CfnOutput(this, "NestedStackOutput", {
                value: nestedStack.nestedStackResource.logicalId,
                exportName: 'MyNestedStackName',
            });
        }
    }
}
```

Stack which imports the `CfnOutput` value and then also outputs that value as a `CfnOutput`:
```ts
export class FnInputStack extends Stack {
    constructor(scope: Construct, id: string, props?: StackProps) {
        super(scope, id, props);

        const nestedStackId = Fn.importValue('MyNestedStackName');
        new CfnOutput(this, 'SuccessfulOutput', {value: nestedStackId})
    }
}
```

When I CfnOutput `cfnStack.stack.stack_name` this is what the CfnOutput is:
> GeneralStack

And when I CfnOutput `cfnStack.logicalId` this is what the CfnOutput is:
> CfnStackNestedStackCfnStackNestedStackResource8C741FFE

**Comment by t-brown** [comment]
Hi @peterwoodworth, thanks for the insightful explanation.

**Comment by t-brown** [comment]
The returned `ref` value is actually what I am after.

```
self.api = CfnStack(self, "APITemplate",
                template_url=template_url,
                parameters=params)

        CfnOutput(self, "ref", value=self.api.ref)
```

This produces the following ARN

```
arn:aws:cloudformation:us-east-2:XXX:stack/WX-parallelclusterapiNestedStackparallelclusterapiNestedStackResource0BDAF-APITemplate-1R37KPVBOKIXS/e4570cc0-c656-11ec-bef7-0aa5c1e614d4
```

Which I want to import the `outputs` from it. I can't seem to figure out how. The deploy fails when I try and split the string as I am assuming it is just a token until the stack has been fully deployed.
```
p = self.api.ref.split("/")[1]
IndexError: list index out of range 
```

Would you happen to know if that is possible at all?

**Comment by peterwoodworth** [comment]
A `ref` creates a [CloudFormation ref](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-ref.html)

Here's what it looks like passing the ref as a CfnOutput:
```json
  "NestedStackOutput": {
   "Value": {
    "Ref": "CfnStackNestedStackCfnStackNestedStackResource8C741FFE"
   },
   "Export": {
    "Name": "MyNestedStackName"
   }
  }
```

So, there's no way to parse the arn before deployment like you're trying to do. However, there's still a way to work around this.

The `NestedStack` resource I mentioned above has a [property `stackName`](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_core.NestedStack.html#stackname) which represents the true stack name. Here's how the CDK builds it: https://github.com/aws/aws-cdk/blob/9a7e599e593e932a40ad0c6766fad260cdea9b47/packages/%40aws-cdk/core/lib/nested-stack.ts#L148

The outputted template would look like this for my example when outputting `NestedStack.stackName`:
```
  "NestedStackOutput": {
   "Value": {
    "Fn::Select": [
     1,
     {
      "Fn::Split": [
       "/",
       {
        "Ref": "CfnStackNestedStackCfnStackNestedStackResource8C741FFE"
       }
      ]
     }
    ]
   },
   "Export": {
    "Name": "MyNestedStackName"
   }
  }
```

When I deploy this, the output will be this, which is what I believe you're after
> OutputStack-CfnStackNestedStackCfnStackNestedStackResource8C741FFE-1PR7VL5CPAOXU

Hope this answers your question @t-brown

**Comment by peterwoodworth** [comment]
More information on [CloudFormation intrinsic functions](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference.html) and the [CDK API for intrinsic CFN functions](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_core.Fn.html)

**Comment by t-brown** [comment]
Thanks @peterwoodworth .

To close this out, I ended up doing the following to get the output from the `CfnStack` call:

```

    CfnOutput(self, "ParallelClusterApiInvokeUrl",
              value=Fn.get_att(self.api.logical_id, "Outputs.ParallelClusterApiInvokeUrl").to_string(),
              export_name="ParallelClusterApiInvokeUrl")
```
