### ISSUE TITLE
(pipelines) CDK CodePipeline should be triggerable by CodeArtifact events 

### ISSUE THREAD

**Issue by lestephane** [aws/aws-cdk#20099]
### Describe the feature

Given that CDK prides itself of being multi language capable, people will write CDK templates in one of the languages supported by CodeArtifact:

- JVM languages through maven packaging
- Javascript transpiled languages through npm packaging
- CLR languages through NuGet packages
- Python through PyPI packages.

It follows that events such as the release of a package on a CodeArtifact repository should be able to trigger a CDK CodePipeline. 

### Use Case

I want to release my infrastructure-as-code as package to CodeArtifact, and have it deployed to the target environment(s).

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.21.1

### Environment details (OS name and version, etc.)

Ubuntu 20.04

**Comment by rix0rrr** [comment]
I like the intent, but it's not entirely clear how this should work out of the box.

* Clearly, the solution should also work for repositories that are not in your AWS account (or even AWS altogether, like NPMJS and Maven Central). EventBridge events are therefore not sufficient by themselves.
* Lockfiles should take care of triggering the changes, and have the added advantage of traceability: `package-lock.json`, `yarn.lock`, `pom.xml` as it is usually written, `poetry.lock`, `packages.lock.json` all serve as a deterministic and traceable source of dependency versions, and have the advantage that they will trigger a commit (and hence the pipeline) when the file is committed.

I would therefore be inclined to say: prefer a job that automatically bumps your dependency versions in version control (in the lockfile), either on a cron job or whenever you release library updates, over "start all pipes when a package is released, have all builds pick up whatever version is current when they install, and end up in prod with no idea of what version is actually running".

Leaving this open for future discussion.
