### ISSUE TITLE
aws-cdk-core: Tags.of().add fails with `INVALID TAG` error for `CfnInsightRule` resource

### ISSUE THREAD

**Issue by prabhaganesh** [aws/aws-cdk#20103]
### Describe the bug

I'm adding Tags to all taggable resources in my stack via 
```
Tags.of(stack).add(name, value)
```
However this fails when I define `CfnInsightRule` resource in the stack.

Failure in Cloudformation deployment
```
PutInsightRule for <insight-rule-name> failed; INVALID_TAGS: Tags are invalid. (Service: AmazonCloudWatch; Status Code: 400; Error Code: InvalidParameterValue; Request ID: <request-id>; Proxy: null)
```

while the Tags were added successfully to all other resources.

The generated Cloudformation template has Insights Rule with tags (they look right and similar to the [official documentation](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-cloudwatch.CfnInsightRule.html))
```
"Tags": [
          {
            "Key": "TagName",
            "Value": "TagValue"
          }
        ]
```

I tried adding the Tags manually on a InsightRule in the Console and that works.

### Expected Behavior

`Tags.of(stack).add(name, value)` adds the tag to all resources in the stack including `CfnInsightRule`

### Current Behavior

`Tags.of(stack).add(name, value)` fails Cloudformation deployment on `CfnInsightRule` resource

```
PutInsightRule for <insight-rule-name> failed; INVALID_TAGS: Tags are invalid. (Service: AmazonCloudWatch; Status Code: 400; Error Code: InvalidParameterValue; Request ID: <request-id>; Proxy: null)
```

### Reproduction Steps

`Tags.of(stack).add(name, value)`
where `stack` is `App` containing at least one resource of type `CfnInsightRule`

### Possible Solution

I suspect `Tags.of(stack).add(name, value)` is adding the tags to `CfnInsightRule` in the wrong format?

As a workaround I'm excluding InsightRule resources from being tagged
```
Tags.of(scope).add(
            name,
            value,
            TagProps.builder().excludeResourceTypes(listOf("AWS::CloudWatch::InsightRule")).build()
        )
```

### CDK CLI Version

1.150.0 (build 7ca8212)

### Node.js Version

14.x

### OS

Amazon Linux 2

### Language

Java

### Language Version

Java 11

**Comment by rix0rrr** [comment]
The documentation doesn't say what format the tags need to be in (only says "key/value pairs"): https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudwatch-insightrule-tags.html

**Comment by Jacco** [comment]
It is strange how different the Tags property is described here:

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudwatch-metricstream.html

I'm guessing it expects key/value pairs like SAM resources. So in yaml:

```yaml
  Tags:
    TagKey: TagValue
```

Are there any other CloudFormation resources that have Tags specified this way?

**Comment by miloszwatroba** [comment]
This issue is still relevant. It's not possible to use Tags.of() with CfnInsightRule.
