### ISSUE TITLE
(cloudwatch): Unit.NONE does not mean "No unit"

### ISSUE THREAD

**Issue by kyhau** [aws/aws-cdk#20112]
### Describe the bug

In CDK it states `Unit.NONE` means "No unit", but it results in "None" instead of "No unit"  (and no data is returned when Unit == None) .

### Expected Behavior

The documentation states `Unit.NONE` means "No unit", so it is expected that when using `Unit.NONE` in CDK stack for alarm, the unit will be "No unit".

### Current Behavior

In CDK it states `Unit.NONE` means "No unit"

![image](https://user-images.githubusercontent.com/5346476/165641961-3595e2b7-f62e-44f3-bb22-eaf88bfced52.png)

The following screenshot shows the deployed alarm having Unit "None" instead of "No unit"  (and no data is returned when Unit == None).

![image](https://user-images.githubusercontent.com/5346476/165642041-dd4cbb0b-12a2-4345-a79b-6ffd62fc48e1.png)

### Reproduction Steps

1. Use `Unit.NONE` for an alarm.
2. Deploy the CDK stack.
3. Check the alarm, you will see the Unit is None, not No Unit.

### Possible Solution

Either fixed the documentation Unit.NONE != No Unit,  or make Unit.NoUnit an option.

### CDK CLI Version

2.21.1 (build a6ee543)

### Node.js Version

v16.14.2

### OS

Ubuntu 20.04.4

### Language

Typescript

### Language Version

Version 4.6.3

**Comment by kaizencc** [comment]
Hi @kyhau! I agree that the documentation for `Unit.NONE` is misleading. And while I see "no unit" is an option on the console screenshot you shared, I don't see that as an option under "unit" in the [API reference](https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_MetricDatum.html). Don't think we'd be able to add that option if it's not part of the api reference, but we should change the documentation to avoid misunderstanding.
