### ISSUE TITLE
(aws-eks): incorrect version of the ALB controller helm chart installed

### ISSUE THREAD

**Issue by chrisshyi** [aws/aws-cdk#20118]
### Describe the bug

Despite being able to specify the ALB controller application version in the constructor of the `eks.Cluster` construct, the helm chart version is fixed at `1.2.7`, and results in issues such as [this](https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2479).

### Expected Behavior

We expected the correct version of the ALB controller helm chart, corresponding to a specific application version, to be installed. For example, application version v2.4.1 should correspond to helm chart version v1.4.1.

### Current Behavior

The helm chart that was installed is fixed at version `1.2.7`, which does not contain some of the fixes to CRDs and other resources introduced in later versions.

<img width="1413" alt="image" src="https://user-images.githubusercontent.com/24416618/165715137-5d5724e9-de1a-46a0-bf7e-19798a161875.png">

### Reproduction Steps

```ts
    this.cluster = new eks.Cluster(this, 'MyEksCluster', {
      version: props.version,
      albController: {
        version: eks.AlbControllerVersion.V2_4_1,
      },
      clusterName: props.clusterName,
      mastersRole: mastersRole,
      clusterLogging: props.clusterLogging,
      coreDnsComputeType: eks.CoreDnsComputeType.EC2,
      defaultCapacity: props.defaultCapacity,
      defaultCapacityInstance: props.defaultInstanceType,
      serviceIpv4Cidr: props.serviceIpv4Cidr,
      vpc: clusterVpc,
      vpcSubnets: props.vpc?.subnets,
      endpointAccess: props.endPointAccessCidrs.length > 0 ? eks.EndpointAccess.PUBLIC_AND_PRIVATE.onlyFrom(...props.endPointAccessCidrs) : undefined,
    });
```

### Possible Solution

Create a mapping between the ALB controller application versions and helm chart versions, and create the `HelmChart` construct within the `AlbController` class using that mapping.

```ts
export class AlbController extends CoreConstruct {
    public constructor(scope: Construct, id: string, props: AlbControllerProps) {
            const chart = new HelmChart(this, 'Resource', {
             // ......
             version: mapAppVersionToChartVersion[props.version.version],
            }
    }
}
```

### CDK CLI Version

1.152.0 (build 9487b39)

### Node.js Version

v14.19.1

### OS

macOS 12.3.1

### Language

Typescript

### Language Version

TypeScript (3.9.10)

**Comment by pahud** [comment]
current helm chart version is `1.4.1` now.
https://github.com/aws/aws-cdk/blob/070f5ecebfba8a3f9b5771b251ee9b584aa89b67/packages/%40aws-cdk/aws-eks/lib/alb-controller.ts#L234

I am closing this issue for now. If you still need to have a feature request for version mapping, feel free to create a new issue.

Thanks.
