### ISSUE TITLE
cli: Cloud assembly schema version mismatch with latest versions

### ISSUE THREAD

**Issue by adam-kiss-sg** [aws/aws-cdk#20121]
### Describe the bug

After upgrading everything to latest versions (python libs: 1.154.0, cli version: 2.22.0 (build 1db4b16)), i get the following error:

```
This CDK CLI is not compatible with the CDK library used by your application. Please upgrade the CLI to the latest version.
(Cloud assembly schema version mismatch: Maximum schema version supported is 17.0.0, but found 18.0.0)
```

### Expected Behavior

No error.

### Current Behavior

Getting error after updating everything to latest.

### Reproduction Steps

1. mkdir cdk-repro
2. cd cd cdk-repro/
3. cdk init app --language python
4. rm -rf .venv/
5. python3 -m venv .venv
6. edit requirements.txt to use aws cdk v1:
    ```
    aws_cdk.core
    ```
7. edit app.py to use aws cdk v1:
    ```
    #!/usr/bin/env python3
    import os

    from aws_cdk import core as cdk

    ...

    ```
8. edit cdk_repro_stack.py:
    ```
    from aws_cdk import core as cdk

    class CdkReproStack(cdk.Stack):

        def __init__(self, scope: cdk.Construct, construct_id: str, **kwargs) -> None:
            super().__init__(scope, construct_id, **kwargs)
    ```
9. python -m pip install -r requirements.txt
10. cdk synth

### CDK CLI Version

2.22.0 (build 1db4b16)

### Framework Version

1.154.0

### Node.js Version

v16.13.0

### OS

ubuntu (windows wsl)

### Language

Python

### Language Version

Python 3.8.10

**Comment by mitchboulay** [comment]
Found a workaround. If you are using a requirements.txt file to install your modules, specify the core version to be 1.153.1.0 and it will work, still using the latest 2.22.0 for CDK.

`aws-cdk.core==1.153.1.0`
`aws-cdk.assertions==1.153.1.0`

**Comment by mickael-caro-sonarsource** [comment]
Same here, had to revert to 1.153.0 for my code, CLI remained on the latest version.

**Comment by stelund** [comment]
It's broken in our CI too, and my local computer. I really don't understand why this has got the label needs-reproduction.

I've found that another workaround is to use `npx aws-cdk@1.x` instead of `cdk` as command to force use cdk 1.x.

**Comment by adam-kiss-sg** [comment]
Another possible "workaround" is to update to cdk v2, that's what i did, considering it was on the roadmap anyway.

**Comment by mitchboulay** [comment]
@adam-kiss-sg what did you do to upgrade to v2?

**Comment by estrudels** [comment]
I am also encountering the issue when I upgrade from using @aws-cdk/.... NPM packages version 1.153.1 to 1.154.0

```
This CDK CLI is not compatible with the CDK library used by your application. Please upgrade the CLI to the latest version.
(Cloud assembly schema version mismatch: Maximum schema version supported is 17.0.0, but found 18.0.0)
```

**Comment by Orenef11** [comment]
The best solution is to downgrade the CDK version to the latest cdkv1 version.
```shell
npm i -g aws-cdk@latest-1
```

**Comment by rix0rrr** [comment]
We had a mistake in our release process, which caused a difference in commits between the latest v1 and v2 to be released. Our apologies.

2.23.0 supports the latest cloud assembly format.
