### ISSUE TITLE
Documentation uses deprecated SecretStringValueBeta1

### ISSUE THREAD

**Issue by kbakk** [aws/aws-cdk#20122]
### Describe the issue

Example shown in https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_iam.AccessKey.html:

```
// Creates a new IAM user, access and secret keys, and stores the secret access key in a Secret.
const user = new iam.User(this, 'User');
const accessKey = new iam.AccessKey(this, 'AccessKey', { user });
const secretValue = secretsmanager.SecretStringValueBeta1.fromToken(accessKey.secretAccessKey.toString());
new secretsmanager.Secret(this, 'Secret', {
   secretStringBeta1: secretValue,
});
```

This will raise a deprecation warning, as https://github.com/aws/aws-cdk/pull/19543 deprecated the `SecretStringValueBeta1` method. 

(Side-note: I'm curious on how to solve this properly using `cdk.SecretValue`.)

### Links

* https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_iam.AccessKey.html

**Comment by kylelaker** [comment]
Some sample code on using this with the new API would be:

```ts
    const user = new iam.User(this, `User`);
    const accessKey = new iam.AccessKey(this, `AccessKey`, { user });
    const secret = new secrets.Secret(this, `Secret`, {
      secretStringValue: accessKey.secretAccessKey,
    });
```

Not sure exactly how the "Example" gets generated (that code snippet seems to come from the `aws-secretsmanager` package, not `aws-iam`), otherwise I'd open a PR to fix.

**Comment by kbakk** [comment]
Thanks!

> There isn't a need to construct a `cdk.SecretValue` yourself in this case as [`secretAccessKey`](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_iam.AccessKey.html#secretaccesskey) is already a `SecretValue`.

This gotcha was what I struggled with. 🙂

**Comment by skinny85** [comment]
Thanks for opening the issue @kbakk. I guess we need to fix the example code here: https://github.com/aws/aws-cdk/blob/7fd542c1af19abd2a580961df1a8cf556588aee8/packages/%40aws-cdk/aws-secretsmanager/lib/secret.ts#L234

**Comment by triqp** [comment]
Looking at making my first contribution. Is @kylelaker recommended code change appropriate?

**Comment by skinny85** [comment]
@triqp yes, it is 🙂.

Check out the "Contributing" guide: https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md.
