### ISSUE TITLE
cloudwatch metrics: expression warning too simplistic

### ISSUE THREAD

**Issue by robjongbloed** [aws/aws-cdk#20136]
### Describe the bug

CDK displays a warning for metrics expressions that are valid.

Specifically, it is trying to check that all variables used in the expression are defined, bit it does not deal with the SEARCH function, and likely not the METRICS either.

### Expected Behavior

Not display a warning for valid expressions.

### Current Behavior

```
Warning at /realtime-chime-meeting-local-997654549727-us-east-1-rjongbloed/Mon/Dash] Math expression '100 * SEARCH('{AWS/ApiGateway,ApiName,Method,Resource,Stage} ApiName=my-api MetricName=("4XXError" OR "5XXError")', 'Average', 60)' references unknown identifiers: piGateway, piName, ethod, esource, tage, piName, realtime, chime, meeting, local, rjongbloed, etricName, rror, rror, verage. Please add them to the 'usingMetrics' map.
```

### Reproduction Steps

Create a metric using SEARCH function.

### Possible Solution

- Parse the complex expression including functions, quotes, parentheses etc.
- Don't do the check if the expression has "SEARCH" or "METRICS" in it.
- Remove the warning completely.

### CDK CLI Version

2.22.0 (build 1db4b16)

### Framework Version

1.153.1

### Node.js Version

v16.15.0

### OS

MacOS

### Language

Typescript, Python

**Comment by gavllew** [comment]
For reference, the warnings were added in #19825.

**Comment by Litee** [comment]
I understand why IDs generation is useful, but are "non-existing identifiers" warnings that useful? If we cannot do proper AST analysis for expressions, maybe we should revert that regexp-based solution? @rix0rrr

**Comment by priyajeet** [comment]
Curious, would it be better just to have a new SearchExpression?

**Comment by Litee** [comment]
As far as I understand, expressions can be complex, like `m1 + SUM(SEARCH(...))`.

**Comment by ilya40umov** [comment]
Does anybody know if there is at least a way to suppress these specific warning somehow? (E.g. judging by this issue #15079 it's currently not supported, especially with Java where `metadata` is an immutable collection, and so we can't even apply the suggested workaround). We have updated our cdk version and getting tons of these due to SEARCH expressions.

**Comment by Litee** [comment]
I would revert this feature, TBH. Its implementation did not take into account some scenarios.

**Comment by rpmcginty** [comment]
Hi, I see this issue has been assigned and the priority increased, but May 2022 was the last update. Is there a rough ETA for when this might be picked up?
