### ISSUE TITLE
(docs) Clarify differences between CDK Pipeline APIs and CodePipeline module

### ISSUE THREAD

**Issue by Jerry-AWS** [aws/aws-cdk#20130]
### Describe the issue

Customers are confused about this; it looks like there are three separate APIs to do the same thing. Let's add some content to the READMEs to clear this up.

### Links

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_codepipeline-readme.html

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.pipelines-readme.html

**Comment by rix0rrr** [comment]
I feel the CDK Pipelines README has a good intro explaining what it's for. Agreed that we just add something to the CodePipeline README then?
