### ISSUE TITLE
(aws-eks) Managed Node Group propagate  the tags to Auto Scaling Group

### ISSUE THREAD

**Issue by yws-ss** [aws/aws-cdk#20133]
### Describe the feature

Currently, there have no solution can add the tags to Auto Scaling Group which managed by Managed Node group through CDK construct.  The tags on Auto Scaling Group can be used in many place, such as: Cluster AutoScaler or billing organization.

### Use Case

There have a scenario need this feature. Per Cluster Autoscaler [document](https://docs.aws.amazon.com/eks/latest/userguide/autoscaling.html) mentioned, if the node group want to scale up from 0, we need to add the resources tags on the auto scaling group to let Cluster Autoscaler discover them. Such as:

```
Key: k8s.io/cluster-autoscaler/node-template/resources/$RESOURCE_NAME
Value: 5
Key: k8s.io/cluster-autoscaler/node-template/label/$LABEL_KEY
Value: $LABEL_VALUE
Key: k8s.io/cluster-autoscaler/node-template/taint/$TAINT_KEY
Value: NoSchedule
```

Base on current ["NodeGroup"](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-eks.Nodegroup.html) construct [2], we could not apply tags from it because managed node group tags currently cannot bring to auto scaling group. Also, "NodeGroup" construct would not return any auto scaling group information which could let us use other function such as ["Tags"](https://docs.aws.amazon.com/cdk/v2/guide/tagging.html) to directly add tag to auto scaling group.

### Proposed Solution

Currently, eksctl use AWS API at the backend to propagate the managed node group to auto scaling group [#5002.](https://github.com/weaveworks/eksctl/pull/5002)  and provide the parameter in [YAML configuration.](https://eksctl.io/usage/schema/#managedNodeGroups-tags)

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

latest

### Environment details (OS name and version, etc.)

Linux

**Comment by yws-ss** [comment]
CC @pahud

**Comment by pahud** [comment]
Thanks @yws-ss for the detailed description. I believe this is a very common scenario for managed nodegroup with the [Kubernetes Cluster Autoscaler](https://docs.aws.amazon.com/eks/latest/userguide/autoscaling.html) capabilities and eksctl has already built in the tags propagation via the SDK call under the hood.

It seems to me that we might make it a default or optional behavior for the tags propagation through a CDK custom resource for the hack. 

wdyt @otaviomacedo ?

If you agree maybe I can invite someone from the community for the PR.

**Comment by otaviomacedo** [comment]
@pahud Yes, it seems the only way to solve this is with a custom resource.

**Comment by jpmcb** [comment]
Is there any update on this? I'm running into something similar with the GO cdk:

```go
        myCluster.AddNodegroupCapacity(jsii.String("my-nodegroup"), &eks.NodegroupOptions{
		InstanceTypes: &[]ec2.InstanceType{
			ec2.NewInstanceType(jsii.String("m5.xlarge")),
		},
		MinSize:  jsii.Number(5),
		AmiType:  eks.NodegroupAmiType_BOTTLEROCKET_X86_64,
		NodeRole: nodeRole,
	})

        // Further down with the entire stack
        awscdk.Tags_Of(stack).Add(jsii.String("Name"), jsii.String("my-custom-nodes"), &awscdk.TagProps{
                ApplyToLaunchedInstances: jsii.Bool(true),
        })
```

This tag is not propagated to the instances that get launched through the node-groups auto-scaling group.

**Comment by pahud** [comment]
This is still a feature request of EKS

https://github.com/aws/containers-roadmap/issues/1657
https://github.com/aws/containers-roadmap/issues/1541

**Comment by pahud** [comment]
closing in favor of https://github.com/aws/aws-cdk/issues/29280#issuecomment-1967683280
