### ISSUE TITLE
@aws-cdk/cloudfront: OriginAccessIdentity mixes up id and name

### ISSUE THREAD

**Issue by dbartholomae** [aws/aws-cdk#20141]
### Describe the bug

`OriginAccessIdentity.fromOriginAccessIdentityName` asks for the OAI __name__, but actually needs the OAI __id__.

Set up the following bucket with a Cloudfront OAI __name__ from a different account:

```
const bucket = new Bucket(this, "Bucket");
const originAccessIdentity =
  OriginAccessIdentity.fromOriginAccessIdentityName(
    this,
    "OriginAccessIdentity",
    "<add-OAI-name-here>"
  );

bucket.grantRead(originAccessIdentity);
```

Then deploy.

### Expected Behavior

The deployment should work.

### Current Behavior

The deployment fails because what is needed is actually the OAI id, not the OAI name. This makes `OriginAccessIdentity.fromOriginAccessIdentityName` quite a misnomer.

### Reproduction Steps

See above.

### Possible Solution

Rename the method and internal properties to `OriginAccessIdentity.fromOriginAccessIdentityId`.

### Additional Information/Context

Not sure if this bug is CDK-specific or a general CloudFormation problem.

### CDK CLI Version

2.20.0

### Node.js Version

16

### OS

Windows 11

### Language

Typescript

**Comment by peterwoodworth** [comment]
You're right @dbartholomae, good find. The AWS console ends up showing the [comment](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-cloudfrontoriginaccessidentity-cloudfrontoriginaccessidentityconfig.html#cfn-cloudfront-cloudfrontoriginaccessidentity-cloudfrontoriginaccessidentityconfig-comment) as the OAI "Name", and the OAI "Id" is the correct value to use according to the console.

This method, and the [`originAccessIdentityName`](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-cloudfront.OriginAccessIdentity.html#originaccessidentityname) property both should be named `id`. [CloudFormation ref](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudfront-cloudfrontoriginaccessidentity.html#aws-resource-cloudfront-cloudfrontoriginaccessidentity-return-values) [CloudFront ref](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-restricting-access-to-s3.html#private-content-granting-permissions-to-oai)

I think the best way to address this would be to add the new method and prop which end in `Id`, and implement them identically to the current method and prop. Then, deprecate the prop and method which reference the OAI name, and have them reference the new method/prop.

**Comment by dbartholomae** [comment]
Happy to provide a PR if fthat makes sense - I might need some guidance on all places I need to change for documentating the new function and deprecating the old one.

**Comment by peterwoodworth** [comment]
We'd love your contribution here!

Our API reference docs are actually autogenerated based on the code files and comments. If you follow exactly how `fromOriginAccessIdentityName()` is structured, you'' see that the comments above each class, method, and property are the actual descriptions seen on our API ref.

You can deprecate a method by adding the @ deprecated flag - just make sure to leave a comment explaining which method to use instead!

Example here https://github.com/aws/aws-cdk/blob/74318c7d22bfc00de9e005f68a0a6aaa58c7db39/packages/%40aws-cdk/aws-elasticsearch/lib/domain.ts#L135

[Appearance in docs](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-elasticsearch.CapacityConfig.html)

**Comment by dbartholomae** [comment]
I've created a PR: #20772
