### ISSUE TITLE
Separate cdk diff and cdk deploy roles

### ISSUE THREAD

**Issue by mek88** [aws/aws-cdk#20142]
### Describe the feature

Separate the role assumed when running cdk diff vs cdk deploy. The diff role should be scoped to allow creation of change sets (and thus diffs) but not to affect deployed infrastructure.

### Use Case

It appears that the `cdk diff` command assumes the same boostrap stack role as `cdk deploy`. This role includes actions like CreateStack, DeleteStack, etc. This is far too empowered for a diff, which is an operation I would like our development teams to execute so as to see the potential impact of code changes. Allowing our teams to run a diff grants them access to a role that includes permissions that could allow creation or destruction of resources (e.g. deploy).

The same goes for our CI/CD pipeline system. Because the role to diff and deploy is the same, it's difficult (perhaps impossible) to lock down deployment permissions to a fenced portion of our CI/CD pipeline system.

### Proposed Solution

Have the boostrap stack create a new, more limited role and tell the cdk to use it when running `cdk diff`.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.20.0

### Environment details (OS name and version, etc.)

OS X, Win

**Comment by corymhall** [comment]
@mek88 `cdk diff` should be using the lookup role and only if the lookup role is not available will it fall back to the deploy role. If this is not the case for you, can you provide the verbose output from a `cdk diff -v`?
