### ISSUE TITLE
Synthetics Canary - CDK2

### ISSUE THREAD

**Issue by nomadme** [aws/aws-cdk#20145]
### Describe the bug

There is not Canary class in Synthetics in CDK2, and it looks like it was removed in the CDK2.

Can someone from the team provide migration guidance from CDK1 to CDK2 for the Canary implementation?

### Expected Behavior

Canary class should be available in CDK2

### Current Behavior

Canary class is removed from the CDK2

### Reproduction Steps

Use CDK2

### CDK CLI Version

2.20.0

### Node.js Version

16.10

### OS

Mac

### Language

Typescript

**Comment by kaizencc** [comment]
Hi @nomadme! The structural change of cdk v1 versus v2 is that experimental modules are pulled out into their own separate packages. `synthetics` is an experimental module, so its v2 version lives as `@aws-cdk/aws-synthetics-alpha`.

I suggest you read our [migration guide](https://docs.aws.amazon.com/cdk/v2/guide/migrating-v2.html) for more details and code snippets on how to add these experimental modules to your project.
