### ISSUE TITLE
(lambda): grantInvoke errors when only specifying sourceArn condition

### ISSUE THREAD

**Issue by kjpgit** [aws/aws-cdk#20146]
### Describe the bug

This works in web console, but fails in cdk:

     func.grantInvoke(new iam.ServicePrincipal("apigateway.amazonaws.com").withConditions(
      { "ArnLike": { "aws:SourceArn": "arn:aws:execute-api:us-west-2:111111111111:*" } }
    ))

### Expected Behavior

.

### Current Behavior

TypeError: Cannot read properties of undefined (reading 'aws:SourceAccount')

### Reproduction Steps

.

### Possible Solution

give up on cdk and use web console

### CDK CLI Version

2.22.0 (build 1db4b16)

### Node.js Version

.

### OS

linux

### Language

Typescript

**Comment by kaizencc** [comment]
Hi @kjpgit! This looks like a bug, and an ugly one at that. I will fix this as part of #19975.
