### ISSUE TITLE
`cdk ls` doesn't work on windows powershell

### ISSUE THREAD

**Issue by imbilltucker** [aws/aws-cdk#20156]
### Describe the bug

cdk doesn't seem to work on windows terminal.  

`cdk ls` takes a long time, and eventual says "Module not found"

### Expected Behavior

cdk would provide a list of installed code:
```
❯ cdk ls
CdkExampleStack

```

### Current Behavior

```
❯ cdk ls
Module Not Found
```

### Reproduction Steps

From a windows powershell terminal:

```
npm install -g aws-cdk
mkdir reproduce_cdk_error
cd reproduce_cdk_error
cdk init
.venv\Scripts\activate
pip install -r requirements.txt
cdk ls
```
This last command takes a long time, and then fails with an error of "Module Not Found"

### Possible Solution

```
cp .venv\Scripts\python.exe .venv\Scripts\python3.exe
cdk ls
```
Then everything works:
```
❯ cdk ls
CdkExampleStack
```

### CDK CLI Version

2.22.0 (build 1db4b16)

### Node.js Version

8.5.5

### OS

Windows10

### Language

Python

### Language Version

3.8.9

**Comment by matt9ucci** [comment]
@imbilltucker It works now on my machine. Try the following commands:

```powershell
mkdir works_on_windows_powershell
cd works_on_windows_powershell
cdk init -l python
.\.venv\bin\Activate.ps1
pip install -r requirements.txt
cdk ls

<#
The output is WorksOnWindowsPowershellStack
#>
```

`cdk --version`: 2.83.1 (build 006b542)
`$PSVersionTable.PSVersion`: 5.1.22621.963
`node --version`: v18.12.1
`python --version`: Python 3.10.5

**Comment by khushail** [comment]
@imbilltucker , could you please run the commands mentioned here - https://github.com/aws/aws-cdk/issues/20156#issuecomment-1584542965 and revert back if that works for you
