### ISSUE TITLE
eks: Changing EKS attribute caused failed rollback state..

### ISSUE THREAD

**Issue by sblackstone** [aws/aws-cdk#20157]
### Describe the bug

I attempted to add a role to an existing EKS cluster that has a specific physical name.   

I understand why it rolled back, but while attempting to do so, it was unable to complete the rollback and I ended up in an `UPDATE_ROLLBACK_FAILED` state...

![image](https://user-images.githubusercontent.com/131382/166129149-58b17cf2-5292-45d6-ad8a-53e11e968fab.png)

### Expected Behavior

It should be able to roll back correctly.

### Current Behavior

It can't roll back correctly.

### Reproduction Steps

Create an EKS cluster with a `clusterName`
Add a Role to it and re-deploy.

### CDK CLI Version

2.10.0

### Node.js Version

14.19

### OS

OSX

### Language

Typescript

**Comment by pahud** [comment]
Can you provide a minimal working CDK code to help us reproduce this issue?
