### ISSUE TITLE
[aws-batch] missing launchTemplateId in LaunchTemplateSpecification

### ISSUE THREAD

**Issue by AlJohri** [aws/aws-cdk#20163]
### Describe the feature

Add support for `launchTemplateId` when attaching a launchTemplate to a Batch Compute environment. Currently it requires using a launchTemplateName.

```
new batch.ComputeEnvironment(this, 'ComputeEnv', {
  computeResources: {
    launchTemplate: {
      launchTemplateName: myLaunchTemplate.launchTemplateName as string, //or simply use an existing template name
    },
    vpc,
  }
});
```

This should be supported: https://docs.aws.amazon.com/batch/latest/APIReference/API_LaunchTemplateSpecification.html

### Use Case

I would like to stop naming resources explicitly as per CDK best practice and let CDK handle naming the launch template.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

1.153.1

### Environment details (OS name and version, etc.)

Amazon Linux 2

**Comment by indrora** [comment]
@TheRealAmazonKendra @madeline-k Looks like there's a PR that addresses this. Can we get review on that?
