### ISSUE TITLE
(iot-actions) Add support for the dynamodbv2 action

### ISSUE THREAD

**Issue by bobveringa** [aws/aws-cdk#20162]
### Describe the feature

AWS CDK has no support for the dynamoDBv2 riot rule action.

### Use Case

I am working on implementing a solution that requires this rule. Using couldformation resources would be possible, but adding in support would be a lot easier.

### Proposed Solution

It seems like this would be a small addition with a low effort. There are already similar rules implemented.

It would add a rule called `DynamoDBv2PutAction` that takes a `dynamodb.ITable` as argument.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.20

### Environment details (OS name and version, etc.)

windows 10

**Comment by skinny85** [comment]
Thanks for the feature request, and the PR @bobveringa!
