### ISSUE TITLE
(msk) Add low level construct for AWS::KafkaConnect::Connector

### ISSUE THREAD

**Issue by deuscapturus** [aws/aws-cdk#20179]
### Describe the feature

Please provide a `CfnConnector` L1 construct for [AWS::KafkaConnect::Connector](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kafkaconnect-connector.html)

### Use Case

All Cloudformation resources should have L1 constructs.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

*

### Environment details (OS name and version, etc.)

*

**Comment by peterwoodworth** [comment]
[This is already a construct we support](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-kafkaconnect.CfnConnector.html) 🙂
