### ISSUE TITLE
Support envelope Encryption of Kubernetes Secrets for existing clusters

### ISSUE THREAD

**Issue by J11522** [aws/aws-cdk#20187]
### Describe the feature

With https://github.com/aws/aws-cdk/pull/9438 support for enabling envelope encryption upon cluster creation was added.
According to the comment by @eladb https://github.com/aws/aws-cdk/pull/9438#pullrequestreview-462211039 it was not possible at the time to change this after the cluster was created.
Now, according to the docs this is possible: https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html#enable-kms
It would be great if CDK could support this.

### Use Case

Under a production workload it is not feasible to shutdown and re-create the cluster

### Proposed Solution

Support this change on existing clusters.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

latest

### Environment details (OS name and version, etc.)

-

**Comment by indrora** [comment]
Closing as this ticket is stale (over 9 months since last event or relates to the CDKv1). 

If this is still a relevant request in the CDKv2, please open a new ticket.
