### ISSUE TITLE
(cognito): UserPoolDomain `baseUrl` is incorrect in `us-gov-west-1`

### ISSUE THREAD

**Issue by kylelaker** [aws/aws-cdk#20182]
### Describe the bug

In the `us-gov-west-1` region, the Cognito Hosted UI always uses the fips endpoint (`<domain-prefix>.auth-fips.<region>.amazoncognito.com`). The [`UserPoolDomain.baseUrl`](https://github.com/aws/aws-cdk/blob/443fb2a7b55f24087e8c638f48c4d8803b629244/packages/%40aws-cdk/aws-cognito/lib/user-pool-domain.ts#L156) function assumes the endpoint is always `<prefix>.auth.<region>.amazoncognito.com`. This results in a value that does not work in `us-gov-west-1`.

### Expected Behavior

I expected calling `baseUrl` to return a URL that works in my current region.

### Current Behavior

Calling `baseUrl()` returns a URL that does not work in `us-gov-west-1`.

### Reproduction Steps

```ts
import 'source-map-support/register';
import * as cdk from "aws-cdk-lib";
import * as cognito from "aws-cdk-lib/aws-cognito";

const UNIQUE_PREFIX = "sample";

const app = new cdk.App();
const stack = new cdk.Stack(app, "DomainBroken");
const userPool = new cognito.UserPool(stack, "UserPool");
const domain = userPool.addDomain("domain", {
  cognitoDomain: {
    domainPrefix: UNIQUE_PREFIX,
  },
});
new cdk.CfnOutput(stack, "Domain", { value: domain.baseUrl() });

```

Change the `UNIQUE_PREFIX` constant to actually contain a unique value and deploy this stack to `us-gov-west-1` and try to navigate to the URL contained in the `DomainBroken.Domain` output. The name does not resolve.

Because I understand that not everyone has access to GovCloud, I have deployed a sample stack setting `UNIQUE_PREFIX` to `govrepro`. The CDK returns `https://govrepro.auth.us-gov-west-1.amazoncognito.com`; however, that does not resolve. `https://govrepro.auth-fips.us-gov-west-1.amazoncognito.com` does.

### Adding a parameter to `baseUrl`
This could be fixed by adding an optional `fips?: boolean` parameter to `baseUrl` (that defaults to false). The nice side effect here is that you'd be able to get FIPS URLs for Hosted UIs in US East/West and other regions that support it; the downside is that users may pass `true` in regions that do not support FIPS endpoints.

<details>
<summary>Code for adding FIPS parameter</summary>

```diff
diff --git a/packages/@aws-cdk/aws-cognito/lib/user-pool-domain.ts b/packages/@aws-cdk/aws-cognito/lib/user-pool-domain.ts
index b201b3153..a9859b7c5 100644
--- a/packages/@aws-cdk/aws-cognito/lib/user-pool-domain.ts
+++ b/packages/@aws-cdk/aws-cognito/lib/user-pool-domain.ts
@@ -152,10 +152,13 @@ export class UserPoolDomain extends Resource implements IUserPoolDomain {
 
   /**
    * The URL to the hosted UI associated with this domain
+   *
+   * @param fips whether to return the fips variant of the hosted UI
    */
-  public baseUrl(): string {
+  public baseUrl(fips?: boolean): string {
     if (this.isCognitoDomain) {
-      return `https://${this.domainName}.auth.${Stack.of(this).region}.amazoncognito.com`;
+      const authBase = 'auth' + (fips ? '-fips' : '');
+      return `https://${this.domainName}.${authBase}.${Stack.of(this).region}.amazoncognito.com`;
     }
     return `https://${this.domainName}`;
   }

```
</details>

### Using a `CfnCondition`

Because this only impacts a single region (for now), it's possible `baseUrl` could return a CloudFormation condition but that scales poorly and adds a condition in the stack.

<details>
<summary>Code for using a CloudFormation condition</summary>

```diff
diff --git a/packages/@aws-cdk/aws-cognito/lib/user-pool-domain.ts b/packages/@aws-cdk/aws-cognito/lib/user-pool-domain.ts
index b201b3153..dc958f01f 100644
--- a/packages/@aws-cdk/aws-cognito/lib/user-pool-domain.ts
+++ b/packages/@aws-cdk/aws-cognito/lib/user-pool-domain.ts
@@ -1,5 +1,5 @@
 import { ICertificate } from '@aws-cdk/aws-certificatemanager';
-import { IResource, Resource, Stack, Token } from '@aws-cdk/core';
+import { CfnCondition, Fn, IResource, Resource, Stack, Token } from '@aws-cdk/core';
 import { AwsCustomResource, AwsCustomResourcePolicy, AwsSdkCall, PhysicalResourceId } from '@aws-cdk/custom-resources';
 import { Construct } from 'constructs';
 import { CfnUserPoolDomain } from './cognito.generated';
@@ -154,10 +154,17 @@ export class UserPoolDomain extends Resource implements IUserPoolDomain {
    * The URL to the hosted UI associated with this domain
    */
   public baseUrl(): string {
-    if (this.isCognitoDomain) {
-      return `https://${this.domainName}.auth.${Stack.of(this).region}.amazoncognito.com`;
+    if (!this.isCognitoDomain) {
+      return `https://${this.domainName}`;
     }
-    return `https://${this.domainName}`;
+    const isGovCondition = new CfnCondition(this, "IsGovWest", {
+      expression: Fn.conditionEquals(Stack.of(this).region, "us-gov-west-1")
+    });
+    return Fn.conditionIf(
+      isGovCondition.logicalId,
+      `https://${this.domainName}.auth-fips.${Stack.of(this).region}.amazoncognito.com`,
+      `https://${this.domainName}.auth.${Stack.of(this).region}.amazoncognito.com`
+    ).toString();
   }
 
   /**
```
</details>

### Using `region-info`

This also feels like a good use case for a `region-info` in some ways, though, `us-gov-west-1` is really the only "special" region I am aware of. The service is not yet available in other US government regions nor are User Pools available yet in `aws-cn`.

### Adding Documentation

It would also be possible to just add documentation saying that the function doesn't work in GovCloud and to provide a workaround.

<details>
<summary>Documentation patch</summary>

```diff
diff --git a/packages/@aws-cdk/aws-cognito/lib/user-pool-domain.ts b/packages/@aws-cdk/aws-cognito/lib/user-pool-domain.ts
index b201b3153..5f71fdf25 100644
--- a/packages/@aws-cdk/aws-cognito/lib/user-pool-domain.ts
+++ b/packages/@aws-cdk/aws-cognito/lib/user-pool-domain.ts
@@ -152,6 +152,10 @@ export class UserPoolDomain extends Resource implements IUserPoolDomain {
 
   /**
    * The URL to the hosted UI associated with this domain
+   *
+   * The URL returned by this method will not work in us-gov-west-1 as it does not return
+   * a FIPS-compliant endpoint URL. Instead, build the URL manually using a format such as:
+   * `https://${domain.domainName}.auth-fips.${Stack.of(domain).region}.amazoncognito.com`.
    */
   public baseUrl(): string {
     if (this.isCognitoDomain) {
```
</details>

### Additional Information/Context

The Amazon Cognito service in AWS GovCloud (US) [does not support custom domains](https://docs.aws.amazon.com/govcloud-us/latest/UserGuide/govcloud-cog.html#govcloud-cog-diffs), so the only available option is a prefixed Cognito domain.

[FIPS endpoints are available](https://aws.amazon.com/compliance/fips/) but not required in `us-east-1`, `us-east-2`, `us-west-1`, and `us-west-2`.

### CDK CLI Version

2.22.0

### Node.js Version

16.14.1

### OS

Fedora

### Language

Typescript

### Other information

I am happy to help implement a fix for this issue.

**Comment by corymhall** [comment]
@kylelaker I think that I'm fine with the solution of adding a fips flag to `baseUrl`, I can't
really think of a better one.

We do already have an issue tracking this so I'm going to close this issue in favor of #12500

**Comment by kylelaker** [comment]
Thanks! Opened #20200 to resolve this.
