### ISSUE TITLE
eks: java aws-cdk-lib 2.22.0 KubernetesVersion missing v1.22

### ISSUE THREAD

**Issue by thatapplefreak** [aws/aws-cdk#20198]
### Describe the bug

Updating the aws-cdk-lib package from 2.21.0 to 2.22.0 removed KubenetesVersion.V1_22 from software.amazon.awscdk.services.eks.KubernetesVersion

### Expected Behavior

Value exists

### Current Behavior

Value missing

### Reproduction Steps

Using:
```xml
<dependency>
    <groupId>software.amazon.awscdk</groupId>
    <artifactId>aws-cdk-lib</artifactId>
    <version>2.22.0</version>
</dependency>
```
Results in KubernetesVersion.V1_22 to be removed

### CDK CLI Version

2.22.0 (build 1db4b16)

### Node.js Version

v14.19.0

### OS

Linux x64 (Pop!_OS)

### Language

Java

### Language Version

openjdk 17.0.2

**Comment by thatapplefreak** [comment]
Issue is still present in cdk version 2.23.0

**Comment by rushndr** [comment]
I just found this commit https://github.com/aws/aws-cdk/commit/d38a9e44af184e6e7fa8cde14a84ff2c72cec5f9

The v1.22 support is incomplete at the moment, you can read more details in the commit message.

**Comment by peterwoodworth** [comment]
Yes, we've decided to remove this since we cannot support it for now without spending a lot of time coming up with a solution. This is on our radar [here](https://github.com/aws/aws-cdk/issues/19843) 

Thanks for reporting this 🙂
