### ISSUE TITLE
Typo on examples for some aws_ecs_patterns documentation page 

### ISSUE THREAD

**Issue by henriquesantanati** [aws/aws-cdk#20206]
### Describe the issue

A few documentation pages are with typo related to the example.

It is showing `memory_limit_mi_b` instead of `memory_limit_mib`. It is just the example. All the other references are correct. 

Please, check if there are other pages with similar issue. 

### Links

https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_ecs_patterns/ApplicationLoadBalancedFargateService.html

https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_ecs_patterns/ApplicationLoadBalancedFargateServiceProps.html

https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_ecs_patterns/ApplicationLoadBalancedEc2Service.html

https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_ecs_patterns/ApplicationLoadBalancedEc2ServiceProps.html

**Comment by peterwoodworth** [comment]
Hey henrique, 

I've posted this issue on the JSII repo https://github.com/aws/jsii/issues/3516
Let's see what they say 🙂

**Comment by TheRealAmazonKendra** [comment]
Given that this is a jsii issue and a ticket has been opened over there, I'm going to close this issue.
