### ISSUE TITLE
aws-cognito: cdk diff always picks up changes when there are none with "EmailBody"

### ISSUE THREAD

**Issue by kewur** [aws/aws-cdk#20212]
### Describe the bug

Hi, 

this is more of an annoyance rather than a blocker. However when we're using an external file with C# CDK called "verification_email.html" and we set the UserVerificationConfig as such

```
new UserPool(this, "UserPool", new UserPoolPros { 
                                                         UserVerification = new UserVerificationConfig
                                                               {
                                                                   EmailSubject = "Confirm your email",
                                                                   EmailBody    = File.ReadAllText("Resources/Cognito/verification_email.html"),
                                                                   SmsMessage   = "Your temporary password for is {####}",
                                                                   EmailStyle   = VerificationEmailStyle.CODE
                                                               }
}); 

```

### Expected Behavior

I expect "cdk diff" to return 

```
Stack CognitoStack
There were no differences
```

### Current Behavior

```
└─ [~] VerificationMessageTemplate
     └─ [~] .EmailMessage:
         ├─ [-] <!DOCTYPE html>

<html>
message
</html>
```

```
         └─ [+] <!DOCTYPE html>

<html>
message
</html>
```

### Reproduction Steps

Create a new stack and define a userpool. create a new html file and use "File.ReadAllText("path/to/verification.html");

### Possible Solution

the strings should be the same, idk what it checks to determine they are different.

### CDK CLI Version

2.1.0

### Node.js Version

v14.17.4

### OS

Linux

### Language

.NET

### Language Version

.net 6

**Comment by corymhall** [comment]
My hunch would be that this is due to https://github.com/aws/aws-cdk/issues/10523
