### ISSUE TITLE
Quicksight: cannot create data-set from another data-set

### ISSUE THREAD

**Issue by pt-kojoa** [aws/aws-cdk#20229]
### Describe the bug

As the title suggests, AWS CDK Quicksight module won't allow creating data-set with source like 
```
    "Source": {
        "DataSetArn": "arn:aws:quicksight:eu-central-1:123451234512345:dataset/some_other_data_source"
    }
```

I consider this as a bug as AWS CLI Quicksight module allows such to be created, so why not CDK?

### Expected Behavior

AWS CDK should be able to handle Quicksight data-set creation like AWS CLI does.

### Current Behavior

AWS CDK is not able to handle Quicksight data-set creation like AWS CLI does. See bug description.

### Reproduction Steps

Can provide such steps as CDK source and documentation is missing the required implementation.

### Possible Solution

Only way around this is to get rid of AWS CDK and do required changes through AWS CLI manually.

### CDK CLI Version

2.20.0 (build 738ef49)

### Framework Version

2.23.0

### Node.js Version

v14.19.1

### OS

MacOs

### Language

Typescript

**Comment by comcalvi** [comment]
`DataSource` has a prop, `attrArn`, that allows you to pass another data source ARN. See https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-quicksight.CfnDataSource.html for details.

**Comment by pt-kojoa** [comment]
> `CfnDataSource` has a prop, `attrArn`, that allows you to pass another data source ARN. Does that provide the capability you need? See https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-quicksight.CfnDataSource.html for details.

Unfortunately this doesn't help. Data-source is different thing than data-set. I need to build data-set that uses multiple other data-sets as a source. Data-source uses data from one place only and can't do join's etc.

**Comment by comcalvi** [comment]
ahh I see. Could you please provide the full CLI command that imports it correctly, including the flag you passed?

**Comment by pt-kojoa** [comment]
Sure. Minimal CLI usage would be something like this:

`aws quicksight create-data-set --region eu-central-1 --cli-input-json file://./data-set-in-data-set.json`

and then the contents of the input json:

```
{

    "DataSetId": "dataset_using_another_dataset",
    "Name": "dataset_using_another_dataset",
    "AwsAccountId": "123451234512345",
    "PhysicalTableMap": {},
    "LogicalTableMap": {
        "942d9155-e98f-480c-8add-d3441981b093": {
            "Alias": "the_another_dataset",
            "DataTransforms": [
                {
                    "ProjectOperation": {
                        "ProjectedColumns": [
                            "id1",
                            "name1"
                        ]
                    }
                }
            ],
            "Source": {
                "DataSetArn": "arn:aws:quicksight:eu-central-1:123451234512345:dataset/the_another_dataset"
            }
        }
    },

    "ImportMode": "DIRECT_QUERY"

}

```

**Comment by pt-kojoa** [comment]
and in case of multiple data-sets in one data-set, the JSON would become something like this:

```
{

    "DataSetId": "dataset_using_another_dataset",
    "Name": "dataset_using_another_dataset",
    "AwsAccountId": "123451234512345",
    "PhysicalTableMap": {},
    "LogicalTableMap": {
        "942d9155-e98f-480c-8add-d3441981b093": {
            "Alias": "the_another_dataset",
            "DataTransforms": [
                {
                    "ProjectOperation": {
                        "ProjectedColumns": [
                            "id1",
                            "name1"
                        ]
                    }
                }
            ],
            "Source": {
                "DataSetArn": "arn:aws:quicksight:eu-central-1:123451234512345:dataset/the_another_dataset"
            }
        },
        "942d9155-e98f-480c-8add-d3441981b094": {
            "Alias": "yet_another_dataset",
            "DataTransforms": [
                {
                    "ProjectOperation": {
                        "ProjectedColumns": [
                            "id1",
                            "name1"
                        ]
                    }
                }
            ],
            "Source": {
                "DataSetArn": "arn:aws:quicksight:eu-central-1:123451234512345:dataset/yet_another_dataset"
            }
        }
    },

    "ImportMode": "DIRECT_QUERY"

}

```

**Comment by comcalvi** [comment]
Looking at CloudFormation docs, I see this: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-quicksight-dataset.html

that has all of the properties you showed in the CLI JSON. Can you try creating a `CfnDataSet` in CDK? The CDK Docs for this resource have an example that should be similar to what you're trying to do: https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-quicksight.CfnDataSet.html#example

**Comment by pt-kojoa** [comment]
I have already tried it, that's how I found out it doesn't work. The interface is missing DataSetArn:

```
    interface LogicalTableSourceProperty {
        /**
         * Specifies the result of a join of two logical tables.
         *
         * @link http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-quicksight-dataset-logicaltablesource.html#cfn-quicksight-dataset-logicaltablesource-joininstruction
         */
        readonly joinInstruction?: CfnDataSet.JoinInstructionProperty | cdk.IResolvable;
        /**
         * Physical table ID.
         *
         * @link http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-quicksight-dataset-logicaltablesource.html#cfn-quicksight-dataset-logicaltablesource-physicaltableid
         */
        readonly physicalTableId?: string;
    }
```

**Comment by comcalvi** [comment]
In the CLI command you showed, you passed the ARN like this:

```
    "LogicalTableMap": {
        "942d9155-e98f-480c-8add-d3441981b093": {
            // ...
            "Source": {
                "DataSetArn": "arn:aws:quicksight:eu-central-1:123451234512345:dataset/the_another_dataset"
            }
        }
    },
```

The property `LogicalTableMap` in a `CfnDataSet` is a Map of `LogicalTable`. The documentation for the `LogicalTable` type is found here: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-quicksight-dataset-logicaltable.html

That `LogicalTable` has a `Source` prop, which is documented here: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-quicksight-dataset-logicaltablesource.html

that `Source` has a `PhysicalTableId` prop. The `PhysicalTableId` prop should allow you to pass the arn; that is, it should be equivalent to the `DataSetArn` prop in the CLI.

**Comment by pt-kojoa** [comment]
> that `Source` has a `PhysicalTableId` prop. The `PhysicalTableId` prop should allow you to pass the arn; that is, it should be equivalent to the `DataSetArn` prop in the CLI.
> 
> In the interface you showed, `physicalTableId` should be equivalent to the `DataSetArn` prop of the CLI.

Believe it or not, I have already tried this too with CDK. There are at least two problems here:

 - PhysicalTableMap can't be empty even though in the CLI it can
 - PhysicalTableId can't be in arn format as there are validations that prevent it (also documented in the Cloudformation docs)

```
UPDATE_ROLLBACK_COMPLETE: Properties validation failed for resource fubar with message:
#/PhysicalTableMap: minimum size: [1], found: [0]
#/LogicalTableMap/fubar/Source/PhysicalTableId: expected maxLength: 64, actual: 67
```

But I guess this is wrong place to try and get this fixed as the problem is actually with Cloudformation and not CDK directly. And there probably is no way of getting the Cloudformation part fixed anyway.

**Comment by comcalvi** [comment]
Have you tried using the dataset's name instead of it's ARN? Can you try using an empty PhysicalTableMap?

**Comment by pt-kojoa** [comment]
> Have you tried using the dataset's name instead of its ARN? Can you try using an empty PhysicalTableMap? You can submit an issue to the cloudformation roadmap, and they will take a look at it: https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

Thank you for pointing me to that repository.

**Comment by peterwoodworth** [comment]
Closing this because this is a CloudFormation related issue
