### ISSUE TITLE
(cli) There should be some way to pass non-string context values

### ISSUE THREAD

**Issue by Jerry-AWS** [aws/aws-cdk#20245]
### Describe the feature

Context values passed via `--context` are received as strings in the CDK app. But other types are supported via e.g. `cdk.json`.  This can lead to type inconsistencies depending on where the value comes from. There should be some way to pass JSON objects using the CLI. (This would also allow true int/float/bool values, as these are valid JSON documents.)

### Use Case

Currently the burden is on the CDK app to rectify this situation. E.g. if the result of `tryGetContext()` is supposed to be a number, the app needs to detect that it's a string and parse it. And it must do this for every context value.

### Proposed Solution

I propose adding a way to pass JSON values as context, either using a new flag like `--context-json` or else by changing the behavior of `--context` so that it attempts to parse the context value as JSON and returns the original string if this fails.

An alternative would be to enhance `tryGetContext()` to do the parsing, either with a new method, a new flag parameter, or the "try and fall back" approach described above. I think the CLI is the right place to put it, though, since `tryGetContext()` is arguably doing the right thing.

I also prefer to avoid the "try and fall back" approach as there may be situations where a string containing a JSON object is the intended value, and there may be code depending on this, which such a change would break.

### Other Information

If we can collectively decide on the correct approach, I will implement this feature.

### Acknowledgements

- [X] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### CDK version used

2.23.0

### Environment details (OS name and version, etc.)

Windows 10

**Comment by Jerry-AWS** [comment]
Got some feedback recently from a customer who stumbled over this in the documentation. I updated the Context topic to indicate what they needed to do, but it would be best if they didn't need to.

**Comment by rix0rrr** [comment]
I like the solution of overloading `--context` to accept both JSON and strings best. However, we should consider really long and hard if we'd get into undesirable edge cases. The following identifiers:

```
true
false
null
```

Would produce a completely different value. 

We can't know if someone today is passing:

```
cdk synth --context foo=false
```

And expects that to come out as `"false"`. I'd wager chances are slim, but you never know...

**Comment by Jerry-AWS** [comment]
Yeah, I like the simplicity of overloading `--context` but am leery of the edge cases. That's what I was trying to avoid with using a new flag. Maybe keep using `--context` but add a new flag to set the parsing behavior? That seems complicated.

**Comment by Jerry-AWS** [comment]
Feature flag perhaps?

**Comment by rix0rrr** [comment]
How about the following:

* We parse as JSON if we can
* We special-case the current words that would be interpreted differently (there aren't that many)
  * If we encounter any of those, we still parse it as the original string, and print a big warning along the lines of:

```
WARNING: --context yourFlag=false is currently interpreted as the string "false". We will soon change this to be interpreted as the boolean value false. To keep the current behavior, pass --context 'yourFlag="false"' instead. If you want object to this change, let us know at https://github.com/aws/aws-cdk/issues.
```

And then 2 or 3 months later, we make the actual change.
