### ISSUE TITLE
(cfnspec): AppConfig tags not recognized by cfn model

### ISSUE THREAD

**Issue by UlaJiang** [aws/aws-cdk#20247]
### Describe the bug

Tags are not getting applied via Tags.of() to Appconfig resource (L1 aws_appconfig.CfnApplication construct)
```
        cfn_application = appconfig.CfnApplication(self, "MyCfnApplication",
            name="name",
            description="description"
        )
        
       Tags.of(cfn_application).add("key11", "value11")  <--- won't apply any Tag to the 'cfn_application' resource
```

### Expected Behavior

when I run 'cdk synth', expected  CLoudFormation Template it generated with Tags on this resource:
```
Resources:
  MyCfnApplication:
    Type: AWS::AppConfig::Application
    Properties:
      Name: name
      Description: description
      Tags:              <---- expected Tags on this resource
        - Key: key11
          Value: value11
```

### Current Behavior

when I run 'cdk synth', the CLoudFormation Template it generated is like below (no Tags on this resource):
```
Resources:
  MyCfnApplication:
    Type: AWS::AppConfig::Application
    Properties:
      Name: name
      Description: description
```

### Reproduction Steps

code snippet
```
        cfn_application = appconfig.CfnApplication(self, "MyCfnApplication",
            name="name",
            description="description"
        )
        
       Tags.of(cfn_application).add("key11", "value11")  <--- won't apply any Tag to the 'cfn_application' resource
```

### Possible Solution

apply Tag directly in resource:
```
        cfn_application = appconfig.CfnApplication(self, "MyCfnApplication",
            name="name",
            description="description",
            tags=[appconfig.CfnApplication.TagsProperty(    <-----
                key="key",
                value="value"
            )]
        )
```

### CDK CLI Version

2.19.0 (build e0d3e62)

### Node.js Version

node: '16.14.2'

### OS

Linux/UNIX  (I am using cloud9, ec2 with ami-0aaed5ce26cecddf2)

### Language

Python

### Language Version

Python 3.7.10

**Comment by rix0rrr** [comment]
The `AppConfig` module declares its own `Tags` type, instead of reusing the global type. This is probably why the L1s are not being recognized as taggable.
