### ISSUE TITLE
neptune: add monitoring props and utility methods 

### ISSUE THREAD

**Issue by humanzz** [aws/aws-cdk#20248]
### Describe the feature

Update the Neptune `DatabaseCluster` construct to improve the monitoring experience
1. Update props to enable configuring CloudWatch Logs
   - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-neptune-dbcluster.html
   - It seems like the only supported log type at the moment is `audit`
     - https://docs.aws.amazon.com/neptune/latest/userguide/cloudwatch-logs.html
     - https://docs.aws.amazon.com/neptune/latest/userguide/auditing.html
3. Expose `metricsXxx` utility methods 
   - https://docs.aws.amazon.com/neptune/latest/userguide/cw-metrics.html
   - https://docs.aws.amazon.com/neptune/latest/userguide/cw-dimensions.html  

### Use Case

Improving the monitoring experience for Neptune Clusters

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.21.1

### Environment details (OS name and version, etc.)

macOS

**Comment by indrora** [comment]
Setting up logs appears to require AWS SDK access. Unless something Terribly Weird is going on with their Parameter configuration, setting up CloudWatch logs involves a custom integration added into the AWS CLI.

**Comment by humanzz** [comment]
@indrora Setting up logs does not require AWS SDK access. There are 2 steps involved
1. A parameter needs to be setup in the parameter group to enable audit logs https://docs.aws.amazon.com/neptune/latest/userguide/auditing.html#auditing-enable
2. A config needs to be set on the cluster to enable exporting the logs to cloudwatch logs

As such
1. a prop can be exposed to allow configuring https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-neptune-dbcluster.html#cfn-neptune-dbcluster-enablecloudwatchlogsexports on the cluster
2. This is where things get interesting as I wonder if in the presence of the prop above, should there be any checks on the input parameter groups, or even creating a default one or should that simply be left for the construct user to do the right thing

**Comment by indrora** [comment]
Ah, I see now. Thanks. 

yeah this is a gap in the CloudFormation coverage.

**Comment by humanzz** [comment]
I came across https://github.com/aws/aws-cdk/issues/15888 which seems to be asking for the same thing as 1 above

**Comment by Naumel** [comment]
@humanzz Good eye!

I will close this issue in favor of the older one.

An extra 👍 on the [feature request](https://github.com/aws/aws-cdk/issues/15888#issue-960202328) will make it easier for the team to gauge interest.

Additionally, thank you for the detailed inputs you have provided, it always appreciated!

**Comment by kaizencc** [comment]
Reopening this one to trackt he request for `metricsXxx` utility methods.

**Comment by humanzz** [comment]
Thanks @kaizencc 
I just hope someone is able to start reviewing it soon :)
