### ISSUE TITLE
(aws-batch): (Property 'jobDefinitionArn' does not exist on type 'CfnJobDefinition')

### ISSUE THREAD

**Issue by coding-chris-kao** [aws/aws-cdk#20253]
### Describe the bug

When using `aws-cdk-lib/aws-events-targets`, we need to input Arn for jobQueue and jobDefinition.
However, you can not find the arn property int the class `CfnJobDefinition`

![image](https://user-images.githubusercontent.com/23354506/167299337-9a191c52-7fd5-4fba-acb6-66e7e625fcf7.png)

### Expected Behavior

`CfnJobDefinition.jobDefinitionArn` should be accessible

### Current Behavior

Property 'jobDefinitionArn' does not exist on type 'CfnJobDefinition'

### Reproduction Steps

```typescript
import * as batch from 'aws-cdk-lib/aws-batch';
import * as events from 'aws-cdk-lib/aws-events';
import * as targets from 'aws-cdk-lib/aws-events-targets';
...

    const jobDefinition = new batch.CfnJobDefinition(this, 'job-definition', {
      jobDefinitionName,
      type: 'Container',
    });

    const jobQueue = new batch.CfnJobQueue(this, 'job-queue', {
      jobQueueName,
      priority: 1,
      state: 'ENABLED',
      computeEnvironmentOrder: [],
    });

    const rule = new events.Rule(this, 'event-rule', {
      schedule: events.Schedule.cron({ hour: '0', minute: '30' }),
    });

    rule.addTarget(
      new targets.BatchJob(
        jobQueue.attrJobQueueArn,
        jobQueue,
        jobDefinition.jobDefinitionArn,
        jobDefinition
      )
    );
```

### CDK CLI Version

2.23.0 (build 50444aa)

### Node.js Version

v16.15.0

### OS

Windows 10

### Language

Typescript

### Language Version

3.9.7

**Comment by peterwoodworth** [comment]
Our `Cfn` constructs are autogenerated from CloudFormation. So, they are identical to their respective CloudFormation resource. We cannot add any additional functionality that isn't given to us by Cfn.

Thankfully in this case, the [JobDefinition returns its arn](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-batch-jobdefinition.html#aws-resource-batch-jobdefinition-return-values). You can access this with `jobDefinition.ref`
