### ISSUE TITLE
aws-cdk boostrap: Security Hub MEDIUM severity findings for CDK v2 Bootstrap resources

### ISSUE THREAD

**Issue by einstein-aws** [aws/aws-cdk#20265]
### Describe the bug

Security Hub is throwing `MEDIUM` severity findings for CDK v2 -generated:

- Roles (`KMS.2` IAM principals should not have IAM inline policies that allow decryption actions on all KMS keys)
- S3 buckets (`S3.10` S3 buckets with versioning enabled should have lifecycle policies configured)
- ECR repos (`ECR.3` ECR repositories should have at least one lifecycle policy configured).

Perhaps, this is some you would want to address in the future releases. Cheers! 👋

### Expected Behavior

The above bootstrap-generated resources and components should satisfy security standards and should not trigger Security Hub rules.

### Current Behavior

Security Hub is throwing `MEDIUM` severity findings for CDK v2 -generated roles (`KMS.2 `IAM principals should not have IAM inline policies that allow decryption actions on all KMS keys), S3 buckets (`S3.10` S3 buckets with versioning enabled should have lifecycle policies configured) and ECR repos (`ECR.3` ECR repositories should have at least one lifecycle policy configured).

### Reproduction Steps

Bootstrap CDK v2 into any account.

### CDK CLI Version

2.23.0 (build 50444aa)

### Node.js Version

v16.15.0

### OS

Mac OS Monterey 12.3.1

### Language

Typescript

### Language Version

4.6.4

**Comment by rix0rrr** [comment]
Duplicate of #19380
