### ISSUE TITLE
Consider adding TSLint completed-docs rule

### ISSUE THREAD

**Issue by jogold** [aws/aws-cdk#2026]
See https://palantir.github.io/tslint/rules/completed-docs/

I see a lot of PR comments/change requests about JSDoc...

**Comment by rix0rrr** [comment]
This is probably a low-effort fix. I feel the correct long-term solution solution is to put this into jsii, so that we can also require the correct doc comment annotations.

**Comment by eladb** [comment]
+1 about adding to Jsii

**Comment by rix0rrr** [comment]
Of course it's never so easy. Tried to enable the TSLint rule, the build choked on the very first package with a 100+ errors. jsii is going to be the only place where we can put this and not be annoying about it.

**Comment by eladb** [comment]
We can initially add it as a Jsii warning

**Comment by NGL321** [comment]
@rix0rrr does this still need attention?

**Comment by jogold** [comment]
Closed by #4645
