### ISSUE TITLE
(eks): support latest EKS engine version v1.22

### ISSUE THREAD

**Issue by mburket** [aws/aws-cdk#20263]
### Describe the bug

We just updated the CDK version from 2.20 to 2.23 and we are using the latest EKS 1.22 version. Looks like the EKS 1.22 is removed from 2.22+. 

Error from npm build: "error TS2551: Property 'V1_22' does not exist on type 'typeof KubernetesVersion'. Did you mean 'V1_20'?"

### Expected Behavior

EKS v1.22 should not be removed.

### Current Behavior

EKS v1.22 is not supported.

### Reproduction Steps

Specify Kubernete version of V1_22 when create an EKS cluster using CDK 2.22+.

### CDK CLI Version

2.23

### Node.js Version

14

### OS

Mac

### Language

Typescript

**Comment by robertd** [comment]
@mburket See #20000 for why `v1.22` was reverted.

**Comment by kaizencc** [comment]
Echoing what @robertd mentioned above. We're working on reducing the module size to allow multiple versions of kubectl lambda layers, but at this time, we can't support `v1.22`.

**Comment by sdenardi** [comment]
Hi @robertd and @kaizencc. Now that `v1.21` is [EOL](https://kubernetes.io/releases/patch-releases/#non-active-branch-history), is there any progress on bringing `v1.22` support to the `cdk`?

The question came up on my team because one of the apps we use recently dropped support for `v1.21` in a recent release. We prefer using the `cdk` to manage our resources, so are hesitant to perform an update to `v1.22` through the AWS Console and have our `cdk` code out of sync with the cluster.

We completely get the reasons for [reverting support](https://github.com/aws/aws-cdk/pull/20000), and appreciate yall's transparency and consideration for users. Thank you for all you do.

**Comment by kaizencc** [comment]
@sdenardi We are actively working on this via the Reduce Module Size [RFC](https://github.com/aws/aws-cdk-rfcs/pull/430). In particular, @madeline-k is working on the lambda layer aspect of the RFC that will unlock the ability to create new layers (without massively increasing package size). I don't want to commit to a timeline atm, but this is in development and hopefully we can share further updates with y'all as they arise.

**Comment by robertd** [comment]
@kaizencc Are we doing the same thing in #20596, that @madeline-k is currently investigating?

**Comment by tutunak** [comment]
@kaizencc are you serious? People want to use AWS CDK instead of terraform, and you don't have any resources for supports a new version of software that available in CloudFormation, terraform, Pulumi, by API. Kubernetes 1.22 was released 4 months ago. Great! Looks like you will never beat terraform.

**Comment by AnitaErnszt** [comment]
@kaizencc that RFC you mentioned seems abandoned, the last comment on it was over 3 weeks ago.

I would absolutely love to put EKS forward as the IaC tool for our EKS setup (we currently using terraform for most things..), but the fact that CDK only supports the end-of-time V1.21 makes it impossible.
AWS is due to release V1.23 this month, is it safe to presume we not gonna get this version in CDK anytime soon either?

Reading the comment on the roll-back, it seems like your issue is to support <= V.1.20 whilst supporting the new version. V1.18 && V1.19 are now officially deprecated and V.20 is due to be deprecated in November.
Are you planning to wait until November to resolve this issue?

**Comment by shcherbak** [comment]
AWS EKS 1.23 is available, but we can not upgrade even 1.21 using CDK :(

**Comment by shcherbak** [comment]
starting migration to terraform next monday
sick and tired of this problem

**Comment by sdenardi** [comment]
I'm not quite ready to abandon CDK, as it fits nicely with our other tooling and have served our needs well up to this point.

It is a bit frustrating to not get any updates, while at the same time getting emails from AWS with the subject line:

> Install EBS CSI driver before upgrading to EKS version 1.23

**Comment by watany-dev** [comment]
I have a problem that I can't version up eks for cdk, but here is my understanding
- EKS can be started from v1.23 to v1.20.
- kubectl is in scope for one version before and after.
- lambda-layer-kubectl is currently v1.20.
- EKS v1.19 will be out of support on 2022/08/01.
https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html

Therefore, we believe we can adopt at least v1.22 by taking the following actions. 
1. upgrade lambda-layer-kubectl to v1.21
2. deprecate aws-eks up to v1.19. Newly support v1.22.

Frankly, I don't think it is appropriate to prevent the deployment of eks clusters for the sake of downward compatibility with lambda-layer-kubectl, so either add the ability to specify the version of lambda-layer-kubectl or truncate support for the oldest version. EKS is a version or two behind k8s, and we believe that there are many users who would like to increase their EKS version as much as possible.

**Comment by WinterYukky** [comment]
I agree with @watany-dev's https://github.com/aws/aws-cdk/issues/20263#issuecomment-1213571723 .
I know that I am currently blocking PR regarding the lambda layer. (because they are working on package size improvements for the lambda layer). I know that comment is a breaking and exceptional change, but I still think it is well worth it.

If we make this change, there will be a grace period before the next support expires. If [RFC](https://github.com/aws/aws-cdk-rfcs/pull/430) is merged in the meantime, it would be possible to support multiple versions of lambda-layer.

**Comment by gkaskonas** [comment]
Any ETA on this? AWS is already pushing v1.23 and we can't upgrade

**Comment by msessa** [comment]
Thanks for the update @cgarvis, looking forward to the official solution.

Meanwhile, for anyone interested, this is a workaround to enable updating EKS to 1.22/1.23.

The idea is to build a kubectl/helm/awcli lambda layer at synth time with a version of kubectl matching the cluster.

Usage:
1- Import [this construct](https://gist.github.com/msessa/096fd19a0f0c6ba7cd2b5fa02f016583) in your app codebase
2- Provision your cluster with something like this:
```typescript
const kubeVersion = KubernetesVersion.of('1.23');
const layer = new KubeClientUtilsLayer(scope, 'KubeClientUtils', {
  kubectlVersion: `${kubeVersion.version}.0`,
});
const cluster = new Cluster(this, 'Cluster', {
  version: kubeVersion,
  kubectlLayer: layer,
});
```

**Comment by cgarvis** [comment]
Update:  Having some issues with #21481 that is delayeing @kaizencc.  Still on track for mid September but not sooner.

**Comment by fspaniol** [comment]
Any updates on this? :(

**Comment by shcherbak** [comment]
we are waiting for this fix from april

**Comment by misterjacko** [comment]
Any updates for us @cgarvis or @kaizencc ?

**Comment by kaizencc** [comment]
This is coming! We have a new repository set up that will soon expose assets from multiple kubectl versions (including 1.22) and @madeline-k is working on dynamically loading that asset into aws-cdk-lib when necessary.

**Comment by nilroy** [comment]
@kaizencc Thanks for the update. Can we expect it this month?

**Comment by shapirov103** [comment]
AWS CDK team: this issue prevents any customer from leveraging CDK to provision and maintain EKS clusters. We are relying on this support for [CDK EKS Blueprints](https://github.com/aws-quickstart/cdk-eks-blueprints) for example, which is used to build production ready clusters.  This may be the reason why some customers (based on the comments above) are considering moving off the CDK. 
The issue has been pending long enough to reassess if this tooling is the right choice for EKS. 
I understand that it is a question of priorities and engineering work, so if there is firm ETA, please share.

**Comment by cgarvis** [comment]
We don't have a firm ETA. But we are targeting next week's release.  We will know by the end of the week if we can hit that target.

**Comment by nilroy** [comment]
@cgarvis Do you know if you are able to release this next week?

**Comment by David-Tamrazov** [comment]
@cgarvis @kaizencc hey team, are there any updates for when this fix will land?

**Comment by shcherbak** [comment]
mid September -> mid November

**Comment by nilroy** [comment]
@cgarvis @kaizencc this issue is really biting us. Please set some ETA so that we can plan accordingly. Right now everything seems to be in air.

**Comment by vumdao** [comment]
@cgarvis  how many `end of the week` should we keep waiting for?

**Comment by misterjacko** [comment]
I have advocated for the adoption of CDK over Terraform for new projects in my company and our new EKS stacks were our trial run. I am finally ready to admit defeat and swallow the sunk cost and begin the work importing the stack into Terraform. 

We are ~4 months away from end of support for EKS 1.21 and unable to update.  This unacceptable level of support for EKS from the CDK is a risk I can't recommend my company continue to accept.

**Comment by nilroy** [comment]
@cgarvis @kaizencc What kind of support is this? If you guys are not gonna fix it in reasonable time then just share it.. Why keep us waiting for something that has no guarantee of arrival?

**Comment by nilroy** [comment]
We had put substantial effort on building the IaC using cdk and I would not like to ditch everything for a stupid issue. I satrted to feel that this issue will not be solved in anytime soon. Probably we have to build our own lambda layers ourselves

**Comment by softmates** [comment]
we don't want to go through this again.please skip 1.22 and support v1.23 directly.

**Comment by Obirah** [comment]
> we don't want to go through this again.please skip 1.22 and support v1.23 directly.

If (I know, I know - this is a big if though) they solve it correctly, any version will be supported immediately, because they'll have automation to create separate lambda layers for each k8s version and the CDK constructs will automatically use the correct layer depending on which k8s version is passed.

We adopted [this approach](https://github.com/aws/aws-cdk/issues/19843#issuecomment-1094244986) several months ago and had no problems to update to 1.22 and later 1.23 with the CDK.

**Comment by cgarvis** [comment]
Hi all, we have hit some snags in our implementation that would require breaking changes for non JS users.  We met internal yesterday to discuss our options.  We have decided to backing out of our current implementation and have come up with fix that we think we can get done this week.  We will know on Friday if this will get in for next week's release.  The approach should solve this issue once and  for all so we won't have to go through this again.  

We did discuss with the EKS team, and it seems that you should be able to upgrade your EKS cluster while still using the 1.20 kubectl lambda layer.  If you are worried about timelines, I would suggestion trying to upgrade.

**Comment by johnnyhuy** [comment]
We used the L1 CDK Construct [`CfnCluster`](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_eks.CfnCluster.html) to provision our EKS cluster to support later versions.

We then handled [AWS auth mapping](https://github.com/rustrial/aws-eks-iam-auth-controller) and other bootstrapping processes later in the process via Helm or Kubectl once logged into the cluster.

The only snag we encountered was EKS cluster bootstrap assigned `kubernetes-master` to the CDK exec role #16888 👀

**Comment by pahud** [comment]
@johnnyhuy do you have slack ID on cdk.dev? Would love to discuss more details with you offline. Thanks.

**Comment by PavanMudigondaTR** [comment]
Have been struggling with this error for the last two days! Just today noticed this issue log. I would appreciate if AWS can provide solution. for mean time i will destroy my 1.23 stack and deploy with 1.21. I hope that works !

**Comment by nilroy** [comment]
@cgarvis I tried upgrading the eks version with the current kubectl lambda layer. I kind of succeeded upgrading the cluster from 1.21 to 1.22 and then to 1.23. But once I try adding a new Fargate profile I encounter the same issue as in  [here](https://github.com/aws/aws-cdk/issues/19843)

**Comment by NinoSkopac** [comment]
> @cgarvis is it going to make it in this week's release?

Of course not

**Comment by cgarvis** [comment]
So we got 1.22 merged into main.  We are holding the release this week until we can get 1.23 (#22638).  If things go well, you should see a new version out tomorrow.

**Comment by David-Tamrazov** [comment]
Thank you for the hard work and quick pivot after the [blocker](https://github.com/aws/aws-cdk/issues/20263#issuecomment-1282638086) came up @cgarvis @madeline-k @kaizencc ! Really appreciate it 🙏

**Comment by nilroy** [comment]
Thank you @cgarvis @madeline-k @kaizencc for this! It is a much needed feature.

**Comment by kaizencc** [comment]
So Kubernetes 1.22 support is released in 2.48.0, which is out now.
Kubernetes 1.23 support is a part of 2.49.0, which if all goes well is out tonight.

Cheers!

**Comment by David-Tamrazov** [comment]
@kaizencc do you know what the plan will be for 1.24 and 1.25? will it be supported with similar patches or is there a different solution in progress?

**Comment by kaizencc** [comment]
1.24 isn't scheduled to be released until November 2022: https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar

At that time, we'll create a new lambda layer, `@aws-cdk/asset-kubectl-v24`, which you will be able to send in as a `kubectlLayer` (we actually already have this for 1.24: https://github.com/cdklabs/awscdk-asset-kubectl).

We'll also add a static method in the eks module for ease-of-use, and run the integ tests to update the snapshots. This isn't a blocker however; you can always specify your kubectl version with `eks.KubernetesVersion.of('1.24')`, and then send in the corresponding lambda layer via the `kubectlLayer` prop.

All this is to say, this is our permanent solution, and there isn't anything to block you on the CDK side. The blocker here is that Amazon EKS support isn't expected until November.

**Comment by David-Tamrazov** [comment]
Great! Thanks for clarifying.

**Comment by bryan-aguilar** [comment]
Was there a reason a different naming scheme was chosen? `@aws-cdk/asset-kubectl-v**` vs `@aws-cdk/lambda-layer-kubectl-v**`?
