### ISSUE TITLE
(stepfunctions-tasks) support SageMaker serverless inference

### ISSUE THREAD

**Issue by zxkane** [aws/aws-cdk#20270]
### Describe the feature

[SageMaker Serverless Inference][1] already is official general available. 

Support creating serverless inference endpoint via StepFunctions workflow.

[1]: https://docs.aws.amazon.com/sagemaker/latest/dg/serverless-endpoints.html

### Use Case

create serverless inference to save cost

### Proposed Solution

add new [ServerlessConfig][1] to class https://github.com/aws/aws-cdk/blob/d60368049119db4075a30a561617f9b9de3657bd/packages/%40aws-cdk/aws-stepfunctions-tasks/lib/sagemaker/base-types.ts#L752

[1] : https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_ProductionVariantServerlessConfig.html

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.23.0

### Environment details (OS name and version, etc.)

linux

**Comment by kaizencc** [comment]
This will require an integ test for sure, if you want to contribute this. Given that there are other production variants that we don't support either, I'm looking for confirmation that this is something everybody wants first. Marking as `p2` for now, will circle back if there's significant community interest.

Workaround as always is a custom task to do whatever you want that the native tasks do not support.

**Comment by zxkane** [comment]
@kaizencc thanks for your reply. There is a simpler way to workaround like below,

```ts
    const createEndpointConfigTask = new class extends SageMakerCreateEndpointConfig {
      public toStateJson(): object {
        const json:{[key: string]: any} = {
          ...super.toStateJson(),
        };
        json.Parameters.ProductionVariants[0]['ServerlessConfig'] = {
          MaxConcurrency: 200,
          MemorySizeInMB: 2048,
        };
        delete json.Parameters.ProductionVariants[0].InitialInstanceCount;
        delete json.Parameters.ProductionVariants[0].InstanceType;
        return json;
      }
    }(this, 'Create endpoint config', {
      integrationPattern: IntegrationPattern.REQUEST_RESPONSE,
      endpointConfigName: TaskInput.fromJsonPathAt('$.trainingJobOutput.TrainingJobName').value,
      productionVariants: [{
        initialInstanceCount: 1,
        instanceType: InstanceType.of(InstanceClass.C5, InstanceSize.XLARGE4),
        modelName: TaskInput.fromJsonPathAt('$.trainingJobOutput.TrainingJobName').value,
        variantName: 'c5-4x',
      }],
      resultPath: '$.endpointConfigOutput',
      resultSelector: {
        'EndpointConfigArn.$': '$.EndpointConfigArn',
      },
    })
```

I'm wondering if you/your team has review bandwidth if a PR with required unit tests & integration tests is submitted. It makes it goes or not.

**Comment by zxkane** [comment]
As the straight implementation, just add `ServerlessConfig` property to `ProductionVariant`, then validate it at synth-time. It's quite intuitive to map the CloudFormation spec of `ProductionVariant`.

Splitting the `ProductionVariant` to serverless and instance should be a good idea, it will bring isolation to different endpoint types. +1 for it.

**Comment by kaizencc** [comment]
Yep. As part of developing an L2 for sagemaker we're running into this decision as well. But in the L2, we have the luxury of designing the API, so I'm advocating for `ProductionVariant.Serverless` and `ProductionVariant.Instance`. But here, it looks like the only sensible thing to do is to add the `serverlessConfig` to `ProductionVariant`.

I'm happy to review a PR that does that. Perhaps it would be nice to do some synth time checking to make sure someone doesn't configure both serverless and instance-based config. @zxkane
