### ISSUE TITLE
aws_lambda_python: ModuleNotFoundError: No module named 'aws_cdk.aws_lambda_python_alpha'

### ISSUE THREAD

**Issue by jhettler** [aws/aws-cdk#20295]
### Describe the bug

Hi everyone, 
I would like to create Python lambda layer with **PythonLayerVersion**, but if I try to import from `aws_cdk.aws_lambda_python_alpha` described in API reference [here](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_lambda_python_alpha/PythonLayerVersion.html?highlight=pythonlayerversion)  I get `No module named 'aws_cdk.aws_lambda_python_alpha'.`

### Expected Behavior

It should be possible to import `aws_cdk.aws_lambda_python_alpha`.

### Current Behavior

ModuleNotFoundError: No module named 'aws_cdk.aws_lambda_python_alpha'

### Reproduction Steps

python -m venv test_venv
source test_venv/bin/activate
python -c "from aws_cdk.aws_lambda_python_alpha import PythonLayerVersion"

### CDK CLI Version

2.23.0

### Node.js Version

v16.15.0

### OS

Dokcer image mcr.microsoft.com/vscode/devcontainers/python:0-3.10-bullseye

### Language

Python

### Language Version

3.10

**Comment by tezz-io** [comment]
Make sure you have installed the lambda-python construct for python. You can do that using:
`python -m pip install aws-cdk.aws-lambda-python-alpha`
After doing that, run 
`python -c "from aws_cdk.aws_lambda_python_alpha import PythonLayerVersion"`
again to verify if the ModuleNotFoundError persists.

**Comment by jhettler** [comment]
Aaaa sorry, I didn't realize the concept, that those *-alpha packages are not a part of aws-cdk-lib. Installing the proper package solved the issue.
