### ISSUE TITLE
(route53): Use lambda.Runtime.NODEJS_14_X in CrossAccountZoneDelegationRecord

### ISSUE THREAD

**Issue by psoares-resilient** [aws/aws-cdk#20297]
### Describe the feature

It currently uses a custom cloudformation resource which is a lambda running on NODEJS_12_X

### Use Case

Make sure we are using the latest available node for that purpose

### Proposed Solution

Single config change in CrossAccountZoneDelegationRecord inside route53 package:

```
const provider = CustomResourceProvider.getOrCreateProvider(this, CROSS_ACCOUNT_ZONE_DELEGATION_RESOURCE_TYPE, {
      codeDirectory: path.join(__dirname, 'cross-account-zone-delegation-handler'),
      runtime: CustomResourceProviderRuntime.NODEJS_14_X,
    });
```

### Other Information

Maybe related to this issue: https://github.com/aws/aws-cdk/issues/19117

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.23.0

### Environment details (OS name and version, etc.)

macOs

**Comment by comcalvi** [comment]
Pretty sure this is closed recently: https://github.com/aws/aws-cdk/blob/v1.160.0/packages/@aws-cdk/aws-route53/lib/record-set.ts#L688
