### ISSUE TITLE
aws-ec2: VPC fromLookup error out when the previous CFN stack with same resource just destroyed

### ISSUE THREAD

**Issue by TingDaoK** [aws/aws-cdk#20303]
### Describe the bug

I have a CDK stack that create a new VPC and added a tags via 
``` ts
const vpc = new ec2.Vpc(this, 'VPC', {
    enableDnsSupport: true,
    enableDnsHostnames: true
})

cdk.Tags.of(vpc).add('S3BenchmarkResources', 'DashboardVPC');
```
I tried to redeploy the stack. The other stack failed to find the VPC via `fromLookup`:
```
const vpc = ec2.Vpc.fromLookup(this, 'VPC', {
  tags: { 'S3BenchmarkResources': 'DashboardVPC' }
});
```

Error reported:
```
<span><span>

Failed resources:
--
</span></span><span><span><span class="ace_error">BenchmarksStack-aws-crt-java-instance-1 | 11:10:37 PM | CREATE_FAILED        | AWS::EC2::SecurityGroup   | BenchmarksStack/SecurityGroup (SecurityGroupDD263621) The vpc ID 'vpc-0336ee4495e566c38' does not exist (Service: AmazonEC2; Status Code: 400; Error Code: InvalidVpcID.NotFound; Request ID: ffbe8291-4136-4fc0-9dca-b2e3f3f6a909; Proxy: null)</span></span></span>
```

I saw the VPC with the tags was successfully created from console.

### Expected Behavior

The other stack can allocate the VPC via tag correctly. 

### Current Behavior

ec2.Vpc.fromLookup failed even though the VPC with the tag can be found from console.

### Reproduction Steps

Have stack create a VPC via
``` ts
const vpc = new ec2.Vpc(this, 'VPC', {
    enableDnsSupport: true,
    enableDnsHostnames: true
})

cdk.Tags.of(vpc).add('S3BenchmarkResources', 'DashboardVPC');
```

- Deploy the stack and then destroy the stack.
- Deploy the stack again.
- When another stack try to find the VPC via 
```
const vpc = ec2.Vpc.fromLookup(this, 'VPC', {
      tags: { 'S3BenchmarkResources': 'DashboardVPC' }
    });
```

I saw failure like:
```
<span><span>

Failed resources:
--
</span></span><span><span><span class="ace_error">BenchmarksStack-aws-crt-java-instance-1 | 11:10:37 PM | CREATE_FAILED        | AWS::EC2::SecurityGroup   | BenchmarksStack/SecurityGroup (SecurityGroupDD263621) The vpc ID 'vpc-0336ee4495e566c38' does not exist (Service: AmazonEC2; Status Code: 400; Error Code: InvalidVpcID.NotFound; Request ID: ffbe8291-4136-4fc0-9dca-b2e3f3f6a909; Proxy: null)</span></span></span>
```

### CDK CLI Version

2.23.0

### Node.js Version

v17.9.0

### OS

AL2

### Language

Typescript

**Comment by corymhall** [comment]
@TingDaoK this is probably due to the VPC information being saved in `cdk.context.json`. When CDK
performs a `fromLookup` it will only lookup the information from AWS the first time, and then it
will cache the information in `cdk.context.json`. You will probably have to clear out the context
and then try again.

https://docs.aws.amazon.com/cdk/v2/guide/context.html#context_viewing

**Comment by TingDaoK** [comment]
Aha, got it. Thanks!
