### ISSUE TITLE
(core): Provide way to tell that a Lambda has been added to my stack by CDK to handle custom resource events

### ISSUE THREAD

**Issue by varnenec** [aws/aws-cdk#20306]
### Describe the feature

Some custom resources, for example `aws-route53.CrossAccountZoneDelegationRecord`, are backed by Lambda functions that respond to create/update/etc events. I would like the ability to tell, while inspecting my construct tree (before synthesis), whether a Lambda function backs a custom resource. Perhaps more generally, I'd like a way of distinguishing between Lambdas I define myself via CDK, vs Lambdas that get defined *for* me, e.g. when using custom resources.

### Use Case

I use CDK aspects to make sure that various resources in my applications' stacks obey certain rules. For Lambda functions, one of those rules is that `FunctionName` is provided, so I can add relevant execution metrics for that function to a CloudWatch dashboard. This works fine for the Lambdas I define explicitly, but fails when it encounters custom resource Lambdas, since `FunctionName` is left unset for those (e.g. per the current implementation of `core.CustomResourceProvider`).

I understand `FunctionName` is optional, so I'm not necessarily requesting that you come up with some sort of dummy name. I just need some way to know I'm dealing with a custom resource Lambda, so that my `IAspect`s can skip it while `visit`ing the node tree, rather than complain that it doesn't look like my other "rule-compliant" Lambdas.

### Proposed Solution

I was initially looking at `Tag`s, but it seems those are not something I can retrieve from a construct node pre-synthesis. I also looked at context key-values, but those need to be added before any child nodes are added (per the docs). I suppose metadata is an option? Or, as a poorer alternative, the Lambda's `Description` field? I'm sorry I don't have a more fully worked-out suggestion.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

1.154.0

### Environment details (OS name and version, etc.)

Amazon Linux 2

**Comment by varnenec** [comment]
A somewhat hacky workaround would be to look at the `.path` of an `IConstruct.node` and check that `Custom::` is a substring - at least that would work for some of the custom resources that ship with CDK. I suppose it wouldn't work for custom resources defined using the `custom-resources` module, but I'm not 100% sure.

**Comment by varnenec** [comment]
@rix0rrr with what exists currently, would a more accurate check be something along the lines of "this Lambda's ARN is the `serviceToken` for some custom resource?" With the understanding that that's a somewhat expensive check esp. in a stack with many resources.

**Comment by rix0rrr** [comment]
Mmm. To be honest, I'm not quite sure how I would write this query myself. What you said seems perfectly sensible. You might try something like:

```
visit(c) {
  if (isCustomResource(c)) {
    this.serviceTokensUsed.add(getServiceToken(c));
  }
  if (isFunction(c)) {
   this.lambdasDefined.add(getLambdaArn(c));
  }

  if (isStack(c)) {
    const unused = setDifference(this.lambdasDefined, this.serviceTokensUsed):
    if (unused.size > 0) { throw new Error('oh no'); }
  }
}
```

I suppose we could make the built-in custom resource handlers add metadata, but if you're doing validation there's always the question of trust. Anyone could be adding that same metadata and evading the checks that way

**Comment by rix0rrr** [comment]
I feel there is a bigger feature request here, but I'm having trouble teasing out what it is. We could take this a number of ways:

* Zoom in on the use case, monitoring: automatic monitoring of all functions (probably requires Weak References to be implemented first).
* Zoom in on the metadata request: add metadata to custom resources, potentially put in some effort to prevent it from being falsified easily.
* Zoom in on the generic use case: think about arbitrary queries on the construct tree.

By the way, I wonder if [cfn-guard](https://github.com/aws-cloudformation/cloudformation-guard) isn't expressive enough to express the query you are trying to build.

**Comment by varnenec** [comment]
Thanks @rix0rrr for replying! IMO adding the metadata to custom resource handlers is an incrementally valuable step. We just ran into another use case where a custom resource handler Lambda created through a different CDK codepath had a name CloudWatch didn't like. I'm not too worried about someone trying to spoof that metadata - all it would say is "this is a custom resource handler", which is an indicator, rather than a guarantee of validity of some sort. My applications primarily rely on the public CDK, plus some construct libraries of our own making, and we wouldn't try to intentionally make our own lives harder.

Just a question - would I be able to inspect the metadata from inside an `IAspect`'s `visit` method? IIRC the answer is yes, but wanted to confirm.

**Comment by rix0rrr** [comment]
> Just a question - would I be able to inspect the metadata from inside an IAspect's visit method? IIRC the answer is yes, but wanted to confirm.

I'm pretty sure yes.

I agree, let's start pragmatically. We don't really have the capacity to implement this ourselves now, but I'm open to PRs adding this metadata.
