### ISSUE TITLE
(logs): Policy Limit Reached for LogGroup ResourcePolicies

### ISSUE THREAD

**Issue by badaldavda8** [aws/aws-cdk#20313]
### Describe the bug

After resolution of #17544 A new issue has turned up if you tend to create multiple ECS tasks referring multiple log groups.

`Resource handler returned message: "Resource limit exceeded. (Service: CloudWatchLogs, Status Code: 400, Request ID: 25bec134-657e-43c3-ae85-810a0ce56fa0)" (RequestToken: 948dab8b-fac6-2903-695d-f9d825eaea90, HandlerErrorCode: ServiceLimitExceeded)
`
This is because Default [quota for resource policies](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/cloudwatch_limits_cwl.html)
<html><head></head><body>

Resource policies | Up to 10 CloudWatch Logs resource policies per Region per account. This quota 								can't be changed.
-- | --

</body></html>

### Expected Behavior

No error after 10th ECS Task/service

### Current Behavior

Each ECS task creates a new log group finally exhausting this limit.

### Reproduction Steps

Create 10 log groups for ecs and you will start to face this.

### Possible Solution

Let us avoid creating not create Resource Policies for CW Logs until this issue is resolved. I understand this defeats the purpose of lowest privilege, but causes issues.

### WorkAround
separate logGroup if created within taskDefinition and add following in the code for now.

`logGroup.node.tryRemoveChild('Policy')`

### CDK CLI Version

2.24.0

### Node.js Version

v17.9.0

### OS

macOS

### Language

Typescript

**Comment by badaldavda8** [comment]
Hi Any update on this?

**Comment by badaldavda8** [comment]
Any update on this?

**Comment by brignolij** [comment]
Hi,
Any update on this? i'm facing the same issue.

**Comment by FOZAEL23** [comment]
Same problem please take a look at this @comcalvi

**Comment by aaa-khoa** [comment]
im facing the same issue, any update on this? I've tried using L1 constructs and it still creates a resource policy whenever a log group is attached to a pipeline project, is there a workaround for this?

**Comment by xmatusmic** [comment]
Same issue!

**Comment by jaredcnance** [comment]
LogGroups do not support ResourcePolicies being attached directly. The only use case for ResourcePolicies today is to enable vended data (see [this](https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutResourcePolicy.html)). I don't think CDK should be creating these policies at all unless the customer is trying to enable vended data, which is not the case for ECS.

**Comment by kevinswarner** [comment]
I believe this issue is causing problems for our attempts to deploy Fargate ECS tasks. I have not seen a resolution yet and am wondering if anyone has advice. We are simply defining our Fargate tasks like this...

```
taskDefinition.addContainer("SampleContainer", {
  image: aws_ecs.RepositoryImage.fromEcrRepository(repository, commitHash),
  essential: true,
  logging: aws_ecs.LogDriver.awsLogs({
    streamPrefix: "sample-container-prefix",
  }),
});
```

We have several (probably more than 10 or 15) tasks spread across different Fargate instances. We are now getting the following CDK error when attempting to deploy...

```
indexing-gc-dev-error-worker | 1/7 | 4:48:36 PM | CREATE_FAILED |
AWS::Logs::ResourcePolicy | ErrorWorkerTaskDefinition/ErrorWorkerContainer/
LogGroup/Policy/ResourcePolicy (ErrorWorkerTaskDefinitionErrorWorkerContainerLog
GroupPolicyResourcePolicy402AEAF5) Resource handler returned message: "Resource 
limit exceeded. (Service: CloudWatchLogs, Status Code: 400, Request ID: 
333b2ee5-001e-4a15-9ea55a7b726a4cde)" (RequestToken: 
faeb374a-d7a0-1850-e977-6cc73706e858, HandlerErrorCode: ServiceLimitExceeded)
```

If I remove the "logging" property from the config object, we are able to deploy. But, I was under the impression that adding the logging is necessary to get logs to be delivered to CloudWatch.

I appreciate any help with this.

**Comment by xmatusmic** [comment]
Hi, what we do and it works is:
`        log_group = logs.LogGroup(
            self,
            f'log-group-name',
            log_group_name=f'/ecs/log-group-name',
            removal_policy = RemovalPolicy.DESTROY
        )
log_group.node.try_remove_child("Policy")
`

**Comment by xmatusmic** [comment]
> I believe this issue is causing problems for our attempts to deploy Fargate ECS tasks. I have not seen a resolution yet and am wondering if anyone has advice. We are simply defining our Fargate tasks like this...
> 
> ```
> taskDefinition.addContainer("SampleContainer", {
>   image: aws_ecs.RepositoryImage.fromEcrRepository(repository, commitHash),
>   essential: true,
>   logging: aws_ecs.LogDriver.awsLogs({
>     streamPrefix: "sample-container-prefix",
>   }),
> });
> ```
> 
> We have several (probably more than 10 or 15) tasks spread across different Fargate instances. We are now getting the following CDK error when attempting to deploy...
> 
> ```
> indexing-gc-dev-error-worker | 1/7 | 4:48:36 PM | CREATE_FAILED |
> AWS::Logs::ResourcePolicy | ErrorWorkerTaskDefinition/ErrorWorkerContainer/
> LogGroup/Policy/ResourcePolicy (ErrorWorkerTaskDefinitionErrorWorkerContainerLog
> GroupPolicyResourcePolicy402AEAF5) Resource handler returned message: "Resource 
> limit exceeded. (Service: CloudWatchLogs, Status Code: 400, Request ID: 
> 333b2ee5-001e-4a15-9ea55a7b726a4cde)" (RequestToken: 
> faeb374a-d7a0-1850-e977-6cc73706e858, HandlerErrorCode: ServiceLimitExceeded)
> ```
> 
> If I remove the "logging" property from the config object, we are able to deploy. But, I was under the impression that adding the logging is necessary to get logs to be delivered to CloudWatch.
> 
> I appreciate any help with this.

try this
Hi, what we do and it works is:
       
```
log_group = logs.LogGroup(
          self,
          f'log-group-name',
          log_group_name=f'/ecs/log-group-name',
          removal_policy = RemovalPolicy.DESTROY)

log_group.node.try_remove_child("Policy")
```

**Comment by xmatusmic** [comment]
> logGroup.node.tryRemoveChild("Policy");
it will work, move this line to the bottom of your code

**Comment by xmatusmic** [comment]
> Thanks @xmatusmic That seems to work. I think the reason this works (but I am guessing a little here) is that the "addContainer" call with the logging property is adding the policy, so you have to place the "tryRemoveChild" call after the "addContainer" call. Would be great for someone from the CDK team to provide even more insight into this. But, I at least can now deploy multiple Fargate tasks / services.

good :) yeah, its exactly what you said, it has to be done after you add log to the container.
