### ISSUE TITLE
[aws_cdk.aws_eks] Clusters created via CDK should show kube-proxy, CoreDNS and Amazon VPC CNI in console's AddOns tab

### ISSUE THREAD

**Issue by duemerz** [aws/aws-cdk#20315]
### Describe the feature

I am using AWS CDK to provision EKS clusters for my organization and we're starting to slowly increase our use of the service. I am am using the Cluster construct and allowing it to provision a managed node group. When it provisions, it automatically rolls out the kube-proxy and CoreDNS resources in my cluster, which I like. 

I am trying to work through a good upgrade strategy for managing new versions of Kubernetes, the node AMI, and all of the various cluster add ons like kube-proxy and CoreDNS. When I provision a cluster manually through the console or via AWS CLI, the add ons are available for me upgrade via AWS APIs (i.e. for example in AWS CLI: aws eks update-addon --cluster-name .... --addon-name ...). 

However, when I provision clusters via the CDK, the add ons--like kube-proxy and CoreDNS--don't show up in the add ons tab in the AWS console. Unless you're aware of a better way, it doesn't look like these are accessible via AWS APIs to upgrade. 

As I increase the number of clusters that I manage, I want add ons to be accessible via AWS APIs so I can develop an automated script to upgrade the cluster, nodes, and add-ons all in one. 

Example - Cluster Provisioned with AWS CDK - Configuration >> Add Ons Tab: 

<img width="765" alt="image" src="https://user-images.githubusercontent.com/59853747/168124537-3c71db7b-093a-4efb-a3e0-0b4d99856a6d.png">

Example - Cluster Provisioned with AWS CDK - Resources Tab:
![image](https://user-images.githubusercontent.com/59853747/168126996-ca338806-9440-4423-af3e-5733ce18c99e.png)

Example - Cluster Provisioned from AWS Console - Configuration >> Add Ons Tab:
<img width="765" alt="image" src="https://user-images.githubusercontent.com/59853747/168127164-513c6af7-33d6-4bbd-9bb3-bf4c58e2b625.png">

Here is a snippet of the code that I am using to provision the EKS cluster: 

```
        #Create the EKS Cluster
        self.eks_cluster = eks.Cluster(
            self,
            id=f'eks-cluster-{environment}-{deployment_name}',
            version=eks.KubernetesVersion.V1_20,
            endpoint_access=eks.EndpointAccess.PRIVATE,
            alb_controller=eks.AlbControllerOptions(
                version=eks.AlbControllerVersion.V2_3_1
            ),
            cluster_logging=[
                eks.ClusterLoggingTypes.API,
                eks.ClusterLoggingTypes.AUTHENTICATOR,
                eks.ClusterLoggingTypes.SCHEDULER,
                eks.ClusterLoggingTypes.AUDIT,
                #eks.ClusterLoggingTypes.CONTROLLER_MANAGER
            ],
            default_capacity=2,
            default_capacity_instance=ec2.InstanceType.of(ec2.InstanceClass.STANDARD5, ec2.InstanceSize.LARGE),
            vpc=vpc_lookup,
            vpc_subnets=private_subnets
        )
```
 

### Use Case

I am looking to use this functionality to develop an automated upgrade strategy using AWS APIs for EKS. 

### Proposed Solution

Register add ons--minimally  kube-proxy, CoreDNS and Amazon VPC CNI--in the AWS Console's AddOns tab so they are accessible via AWS APIs. 

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.24.0 (build b8d8b9a)

### Environment details (OS name and version, etc.)

MacOS Monterrey Version 12.3.1

**Comment by peterwoodworth** [comment]
I'm pretty certain we will be able to implement this, since we already create clusters with custom resources (making direct API calls)

I'm not sure if this will work exactly how we want it to, but there are [L1 CfnAddon](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-eks.CfnAddon.html) resources available in our EKS library. Maybe those could be utilized

**Comment by nielstenboom** [comment]
Anyone landing here wondering how to add addons to EKS through CDK because the list seems empty in the console, this is what we did and seemed to work well!

This was needed because our upgrade from v1.24 -> v1.25 was a bit bumpy due to add-ons not being updated automatically is our guess. The `aws-node` pods would go into CrashLoopBackoff after the update.

Below is the Typescript code snippet that added the addons and solved our issues 👍 

```typescript
    const clusterName="my-cluster"
    const cluster = new eks.Cluster(this, "MainCluster", {
      clusterName: clusterName,
     // rest of your cluster config
    });
    new eks.CfnAddon(this, "KubeProxyAddOn", {
      addonName: "kube-proxy",
      clusterName: clusterName,
      resolveConflicts: "OVERWRITE",
    });
    new eks.CfnAddon(this, "CoreDNSAddOn", {
      addonName: "coredns",
      clusterName: clusterName,
      resolveConflicts: "OVERWRITE",
    });
```
