### ISSUE TITLE
(aws-cdk-lib): remove source maps from published v2 module

### ISSUE THREAD

**Issue by kaizencc** [aws/aws-cdk#20320]
### Describe the feature

Version 2 of the CDK is too large, so we are implementing this [RFC](https://github.com/aws/aws-cdk-rfcs/pull/430/files) to reduce it.

Currently, source maps account for 22% of the module size, and in its current state are unusable. The source maps are meant to map `.js` files back to the `.ts` source code, but we do not ship `.ts` files as part of the `aws-cdk-lib` package. Instead, we inline the source code encoded in base64 inside the `.js` file. This is supposed to work, but does not. My hypothesis is that somewhere along the line jsii is applying some transforms to the `.js` file which causes the source maps to go out of sync.

No one can currently utilize the source maps as part of their debugging process. We could try to fix the source maps, but not being able to see the `.ts` source hasn't been a hindrance to using CDK, so an easier thing to do is to simply drop the maps altogether.

### Use Case

Source maps are there to allow mapping the executed javascript code back to the typescript source code when debugging. There is no use case for them when the typescript source code is unavailable. 

I also tested this with a symlinked repository, and the debugger was able to access the `.ts` source code with the maps and without. Either way, we don't plan on optimizing for this niche case.

However, if you are reading this and feel strongly that this is not the case, please comment and let us know what your use case is!

### Proposed Solution

Remove source maps from the package altogether.

### Other Information

This is part of the reduce module size [RFC](https://github.com/aws/aws-cdk-rfcs/pull/430/files)

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.20.0

### Environment details (OS name and version, etc.)

MacOs

**Comment by lestephane** [comment]
> but not being able to see the .ts source hasn't been a hindrance to using CDK,

@kaizencc I beg to differ, hence I'm writing here.

> I also tested this with a symlinked repository, and the debugger was able to access the `.ts` source code with the maps and without.

I'm not a TypeScript guru, can you explain how you do that? This is what I see in Intellij, and I dearly, dearly want to view the TypeScript code, all the time, because I need to go down the rabbit hole to figure out cdk defaults that might be 2, 3 levels deeps (no, documentation is not enough for me, I need to see what I'm dealing with).

And sorry if this just so self-explanatory to others, again, this tech is TypeScript native, and so I want to use the TypeScript version as opposed to the JVM adapter. But this kind of stone in the shoe makes me think it's painful whichever tech I choose (no debugging at all with a JVM language, and, well..., no debugging at all with TypeScript, by default). Thanks.

![image](https://user-images.githubusercontent.com/5460884/170812089-9e6e74b0-1002-4690-bf24-5fc13918bda9.png)

**Comment by kaizencc** [comment]
Hi @lestephane, thanks for voicing your concerns. First of all, I want to point out that the decision to remove the source maps is a two-way door and we can always add it back. However, it seems like you were never using the source maps to begin with, as they did not work with how jsii compiles things.

I agree that having the TS source code to see what you're dealing with is extremely helpful, but our eventual solution to that may be different. For example, here is a potential idea that comes from the reduce module size [RFC](https://github.com/aws/aws-cdk-rfcs/pull/430/files):


```
2. Releasing an additional 2.X.Y-debug package with every release, that will
   contain the source maps and source files. In addition to reducing the size of
   the aws-cdk-lib package, we want to reduce the volume of artifacts we publish
   to npm and other package managers in total. This would be in direct conflict
   with that goal by doubling the amount of content that is published on each
   release. And, there is currently no demonstrated customer need for a debug
   package like this.
```

We haven't really heard from any customers that this is something that is important to prioritize, but I suppose we also have not been directly looking for customer input either. I've opened a separate [issue](#20561) that can track the need for something like this, and we'll see what kind of traction it gets.
