### ISSUE TITLE
pipelines: Missing props unused check for CodePipeline

### ISSUE THREAD

**Issue by simonkarman** [aws/aws-cdk#20334]
### Describe the bug

In [the constructor of pipelines.CodePipeline](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/pipelines/lib/codepipeline/codepipeline.ts#L357) checks are done to verify that `pipelineName` and `crossAccountKeys` are not set if a pipeline is already provided through the props. However this check is missing for the `reuseCrossRegionSupportStacks` property.

### Expected Behavior

Providing both the `reuseCrossRegionSupportStacks` parameter and the `codePipeline` parameter to a pipelines.CodePipeline _should_ fail.

### Current Behavior

However, right now: Providing both the `reuseCrossRegionSupportStacks` parameter and the `codePipeline` parameter to a pipelines.CodePipeline _does not_ fail, although it should.

### Reproduction Steps

The following _should_ fail.
```
    import { aws_codepipeline as cp, pipelines } from 'aws-cdk-lib';
    new pipelines.CodePipeline(scope, 'CodePipeline', {
      reuseCrossRegionSupportStacks: true,
      codePipeline: new cp.Pipeline(scope, 'Pipeline'),
      synth: new pipelines.ShellStep('Synth', { commands: ['ls'] }),
    });
```

### Possible Solution

Add the following piece of code to line 357 of the CodePipeline.
```
      if (this.props.reuseCrossRegionSupportStacks !== undefined) {
        throw new Error('Cannot set \'reuseCrossRegionSupportStacks\' if an existing CodePipeline is given using \'codePipeline\'');
      }
```

### CDK CLI Version

2.16.0 (build 4c77925)

### Node.js Version

v14.18.0

### OS

MacOS

### Language

Typescript

### Language Version

3.9.7

**Comment by NGL321** [comment]
Hey @simonkarman,

Thank you for reporting this! This seems like a simple fix, but it wont be high on the priority list (since even small fixes would require testing). Since you already have a good grasp on the solution, feel free to create a PR to resolve this following the Contribution guidelines and send it my way for review.
If you are unable to or don't have time, someone should address this eventually.
