### ISSUE TITLE
aws-cloudfront: re-use existing lambda@edge functions

### ISSUE THREAD

**Issue by alexandervandekleutab** [aws/aws-cdk#20336]
### Describe the feature

I want to be able to create one lambda@edge function and then import it or use it in other CDK stacks for use with cloudfront. I could not find a way to do this without manually constructing an object that implements the `IVersion` interface, which is more work than it should be. Any suggestions on how to achieve this in a simpler way?

### Use Case

I have many different cloudfront distributions serving different web applications, but I want to add the same security headers to every response. Rather than copying and pasting the lambda source code and creating a new lambda@edge for every cloudfront distribution, I want to create it once in one CDK stack and make use of it elsewhere.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

1.144

### Environment details (OS name and version, etc.)

macos

**Comment by comcalvi** [comment]
have you tried importing the lambda function arn using `fromFunctionArn()`?

**Comment by peterwoodworth** [comment]
@alexandervandekleutab have you tried the above suggestion? If you have, could you explain more what exactly this feature request would do differently?
