### ISSUE TITLE
aws-cdk-lib/aws-rds/DatabaseInstance: Get log group of cloudwatchLogsExports

### ISSUE THREAD

**Issue by Korbi10** [aws/aws-cdk#20358]
### Describe the feature

As software developer I would like to get the new created log group of an DatabaseInstance if the DatabaseInstance has the cloudwatchLogsExport property set, so that I can build metric filter based on that log group and I do not have to calculate the naming behavior like AWS does

### Use Case

Currently in our database stack we get the log group of the DatabaseInstance by calculating the name by ourself which looks for the Metric filter Like this:

new MetricFilter(this, 'SomeID', {
      logGroup: LogGroup.fromLogGroupName(this, 'SomeID', `/aws/rds/instance/${this.databaseInstance.instanceIdentifier}/postgresql`),
      filterPattern: FilterPattern.anyTerm('ERROR', 'Caused by', 'error'),
      metricName: logMetrics.metricName,
      metricNamespace: logMetrics.namespace,
      defaultValue: 0,
      metricValue: '1',
    });

this indicates, that we always knew the DatabaseInstance identifier and the used engine. Also we rely here on the naming convention of AWS. This seems dangerous to me.

### Proposed Solution

The DatabaseInstance has a method or Property which contains the log group name or ARN so that we can get it in other services.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.23.0

### Environment details (OS name and version, etc.)

Windows 10, Typescript

**Comment by peterwoodworth** [comment]
Currently you could access these log groups through escape hatches, by selecting the proper child from the `DatabaseInstance.node.findChild()`. I would suggest looking at the synthesized construct tree (`cdk.out/tree.json`) to know which log groups you want to access

We create the log groups here https://github.com/aws/aws-cdk/blob/83f166817cf85064b118a7a672ca2d96641d3bbb/packages/%40aws-cdk/aws-rds/lib/instance.ts#L765-L775

I don't see why we couldn't expose these directly from the DatabaseInstance. Leaving this up as a good first issue for anyone to submit a PR for 🙂

**Comment by GavinZZ** [comment]
I noticed that the previous PR was closed due to inactivity. Going to give it another attempt to address this issue.

**Comment by GavinZZ** [comment]
This is now supported (pending release), detail usage can be found in [README](https://github.com/aws/aws-cdk/pull/28676/files#diff-1a359c7a2c303cf2f3d6f0075f067f380a9313e17fb329dc87f321e2e7cc2816)
