### ISSUE TITLE
(aws-lambda-event-sources): Partial Batch Response for SQS event sources

### ISSUE THREAD

**Issue by hongnan0512** [aws/aws-cdk#20355]
### Describe the feature

when messages on an SQS queue fail to process, Lambda marks a batch of records in a message queue as partially successful and allows reprocessing of only the failed records. By processing information at a record-level instead of batch-level, AWS Lambda has removed the need of repetitive data transfer, increasing throughput and making Amazon SQS message queue processing more efficient. 

### Use Case

When there is partial batch process failure, instead of reprocessing all the batch, we only reprocess failed messages. 

### Proposed Solution

Add FunctionResponseTypes to event source mapping 

Add FunctionResponseTypes to L1 event source mapping classes
Add FunctionResponseTypes to L2 event source mapping classes

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

v2

### Environment details (OS name and version, etc.)

any

**Comment by kaizencc** [comment]
@hongnan0512 can you confirm what feature you're looking for in this request? Looks like partial reporting exists.
