### ISSUE TITLE
custom_resources: getResponseField does not function properly when the output is a list, not a key-value pair

### ISSUE THREAD

**Issue by menendezjaume** [aws/aws-cdk#20352]
### Describe the bug

When using the getResponseField method in a custom resource, and the output is a list and not a key-value pair, it doesn't work

### Expected Behavior

That if we input something like this `DkimTokens.0` and it truly is a unique value, to return it.

### Current Behavior

Error:
```
CustomResource attribute error: Vendor response doesn't contain DkimTokens.0 in objects...
```
### Reproduction Steps

1. Create a custom resource that calls the `ses:verifyDomainDkim` action
2. Attempt to iterate over the output, which should be something like this according to the docs:
```json
{
   "DkimTokens": [
       "EXAMPLEq76owjnks3lnluwg65scbemvw",
       "EXAMPLEi3dnsj67hstzaj673klariwx2",
       "EXAMPLEwfbtcukvimehexktmdtaz6naj"
   ]
}
```

Here is the code:
```ts
const verifyDomainDkim = new cdk.custom_resources.AwsCustomResource(
      this,
      "VerifyDomainDkim",
      {
        onCreate: {
          service: "SES",
          action: "verifyDomainDkim",
          parameters: {
            Domain: "exampledomain.com",
          },
          physicalResourceId: cdk.custom_resources.PhysicalResourceId.of(
            Date.now().toString()
          ), // Update physical id to always fetch the latest version
        },
        // TODO fix when https://github.com/aws/aws-cdk/issues/4533 is done
        policy: cdk.custom_resources.AwsCustomResourcePolicy.fromStatements([
          new cdk.aws_iam.PolicyStatement({
            resources: ["*"],
            actions: ["ses:VerifyDomainDkim"],
          }),
        ]),
      }
    );
    // output the Verification Domain Idendity VerificationToken
    new cdk.CfnOutput(this, "dkim.record.0", {
      value: verifyDomainDkim.getResponseField("DkimTokens.0"),
      description: "The Verification DKIM token 0",
    });
```

### Possible Solution

If the "iterator" of the getResponseField is at the end, assume the response is a string and not a key-value pair.

### CDK CLI Version

2.24.1 (build 585f9ca)

### Node.js Version

v16.14.0

### OS

Ubuntu 20.04.4 LTS

### Language

Typescript

### Language Version

3.9.7

**Comment by jogold** [comment]
@menendezjaume what do you see in the logs of the Lambda function? Can you look for `Responding` followed by the body sent back to CloudFormation?

https://github.com/aws/aws-cdk/blob/a0b29e9f29775bfd94307a8975f5ba3a8faf05fa/packages/%40aws-cdk/custom-resources/lib/aws-custom-resource/runtime/index.ts#L233-L236

**Comment by menendezjaume** [comment]
Thanks very much, @jogold .

It does indeed work. My was that I had assumed the API `verifyDomainDkim` would return all the records every time it's called. It didn't, and therefore the response was empty if the resource existed. I can see now that my issue is that I need an `OnUpdate` section where I called something like `get-identity-dkim-attributes`, and my issue is therefore related to https://github.com/aws/aws-cdk/issues/13827.

Thanks very much for your help! :)
