### ISSUE TITLE
(aws-msk): Add support for MSK Serverless

### ISSUE THREAD

**Issue by raginjason** [aws/aws-cdk#20362]
### Describe the feature

 It appears [MSK Serverless was released 2022-04-28](https://aws.amazon.com/blogs/aws/amazon-msk-serverless-now-generally-available-no-more-capacity-planning-for-your-managed-kafka-clusters/). However, there do not seem to be any CDK constructs to use this. This is a feature request for a MSK Serverless construct to be created.

### Use Case

I would like to be able to work with MSK Serverless in CDK.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

1.148.0

### Environment details (OS name and version, etc.)

OSX

**Comment by peterwoodworth** [comment]
I don't think that CloudFormation currently has any options to support this https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-msk-cluster.html

On a quick search I can't find it in the [CloudFormation roadmap either](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap). If you're interested in this feature, please create a request in that repository. We can continue tracking this here and implement it on the CDK side once CloudFormation enables this feature.

**Comment by raginjason** [comment]
@peterwoodworth:

> If you're interested in this feature, please create a request in that repository.

Sure, I can do that. However, I'm not clear where the actual CloudFormation repo is. When I look at https://github.com/aws-cloudformation, there are 100+ repos. Do you have any guidance on which of those repos I should make this request?

**Comment by peterwoodworth** [comment]
Cfn isn't open source so there's no real repo to cut requests against

**Comment by rcollette** [comment]
https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1266

**Comment by jumic** [comment]
CloudFormation support for MSK serverless is available now:
[Amazon MSK Serverless is now integrated with AWS CloudFormation and Terraform](https://aws.amazon.com/about-aws/whats-new/2022/08/amazon-msk-serverless-integrated-aws-cloudformation-terraform/)

**Comment by parodoTS** [comment]
@jumic 
> CloudFormation support for MSK serverless is available now

Example in CDK:

```javascript
    const  clusterMSKServerless = new cdk.CfnResource(stack, 'MSKserverless', {
        type: "AWS::MSK::ServerlessCluster",
        properties : {
            ClientAuthentication : {
              Sasl: {
                Iam: {
                  Enabled: true,
                }
              }
            },
            ClusterName : "MSKserverless",
            VpcConfigs : [{
              SecurityGroups: [SecurityGroup.securityGroupId],
              SubnetIds: VPC.selectSubnets({subnetType: ec2.SubnetType.PRIVATE_ISOLATED}).subnetIds
            }]
          }
      })
```
Using previous VPC and SecurityGroup

**Comment by peterwoodworth** [comment]
Thanks for the update @jumic and @parodoTS, I think we can close this issue out now 🙂

**Comment by raginjason** [comment]
@peterwoodworth I see the example that @parodoTS posted for use with CDK. Correct me if I’m wrong, but shouldn’t there be at least a L1 Cfn construct for this? Is that something that is automatically generated in the next CDK release?

**Comment by peterwoodworth** [comment]
@raginjason we already have an l1 construct for this https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_msk.CfnServerlessCluster.html 🙂

**Comment by raginjason** [comment]
@peterwoodworth oh gotcha! Thanks!
