### ISSUE TITLE
(aws-cloudwatch): MathExpression warns about missing metric identifiers for SEARCH expression 

### ISSUE THREAD

**Issue by ben51** [aws/aws-cdk#20367]
### Describe the bug

Hi,

When creating a MathExpression for a search, the class will return warnings that not all identifiers were declared in the `usingMetrics` property. I don't believe this is a correct behavior for a search expression since there is no metric to be declared.

### Expected Behavior

No warning should be shown for a MathExpression representing a SEARCH.

### Current Behavior

CDK code:

```
new cw.MathExpression({
    expression: "SEARCH('{MyService,Site,Service}  MetricName=\"MyMetric\"', 'Minimum', 300)",
    label: " ",
    period: undefined,
    usingMetrics: {},
}),
```

Raises following warning:

```
[Warning at /MyService12346789123/Dashboard/Dashboard] Math expression 'SEARCH('{MyService,Site,Service}  MetricName="MyMetric"', 'Minimum', 300)' references unknown identifiers: yService, ite, ervice, etricName, yMetric, inimum. Please add them to the 'usingMetrics' map.
```

### Reproduction Steps

```
new cw.MathExpression({
    expression: "SEARCH('{MyService,Site,Service}  MetricName=\"MyMetric\"', 'Minimum', 300)",
    label: " ",
    period: undefined,
    usingMetrics: {},
}),
```

### Possible Solution

Find a better way to identify missing metric identifier.

### CDK CLI Version

2.23.0 (build 50444aa)

### Node.js Version

14

### OS

Linux

### Language

Typescript

**Comment by peterwoodworth** [comment]
Hey @ben51, thanks for reporting this.

I believe this is the same issue seen [here](https://github.com/aws/aws-cdk/issues/20136). Ping me if you disagree 🙂
