### ISSUE TITLE
High level API for outputs?

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#2036]
I am wondering if we should provide a higher level API for outputs, now that https://github.com/awslabs/aws-cdk/pull/1960 is merged. Maybe something like `stack.addOutput()`?

Related #2012

**Comment by cpmech** [comment]
Any suggestions on how to accomplish this currently?

**Comment by iRoachie** [comment]
@eladb I'd like to work on this. 

- Would the props and API be the same as CfnOutput?
- Do we need an L2 for `CfnCondition` first? I'd assume so since the `condition` would be in the public API of Output

**Comment by eladb** [comment]
> Would the props and API be the same as CfnOutput?

I would assume, perhaps with some stronger typing when possible.

> Do we need an L2 for CfnCondition first.

Probably.



----

How about use this issue as a mini-RFC for this feature? The best way would be to "work backwards from the README". Add a comment in this issue with a proposal for the future README section. This way, we can agree on the right API first.
