### ISSUE TITLE
ec2: CfnVPC   cidrBlock parameter is not optional.

### ISSUE THREAD

**Issue by mrpackethead** [aws/aws-cdk#20365]
### Describe the bug

in ec2.CfnVPC,  cidrBlock is not optional, despite the underlying CFN resource ( AWS::EC2::VPC ) having a  conditional cidrBlock.. ( you need to specify a cidrBlock OR a ipv4IPAM Pool Id ), but not both..   

I am trying to use the ipv4IPAM Pool. 

Seems CDK is enforcing the cidrBlock to be required

/home/ec2-user/customers/moe/PROD/network/node_modules/aws-cdk-lib/core/lib/runtime.ts:338
    throw new Error(`${context.toString()} is missing required property: ${name}`);
          ^
Error: NetworkStack/Vpc{id} [AWS::EC2::VPC] is missing required property: cidrBlock

### Expected Behavior

The cidrBlock should be an optional.

### Current Behavior

/home/ec2-user/customers/moe/PROD/network/node_modules/aws-cdk-lib/core/lib/runtime.ts:338
    throw new Error(`${context.toString()} is missing required property: ${name}`);
          ^
Error: NetworkStack/Vpc{id} [AWS::EC2::VPC] is missing required property: cidrBlock

### Reproduction Steps

props = yaml.load('
 tags:
  - key: Name 
    value: webservices_delivery
  enableDnsHostnames: True
  enableDnsSupport: True
  ipv4IpamPoolId: ipam-pool-08f78xxxxxxxx
  ipv4NetmaskLength: 23
');

var network = new ec2.CfnVPC(this, `Vpc{id}`,
        prop)
  

### Possible Solution

Not sure!

### CDK CLI Version

2.20

### Node.js Version

16.6.1

### OS

Linux

### Language

Typescript

**Comment by mrpackethead** [comment]
the type defintiion is coming from ec2.generated.d.ts, so i'm guessing that what we have here is a problem with what is being provided by Cloudformation

**Comment by Jacco** [comment]
Trying to figure out what the source of the *.generated.ts is but in the CloudFormation specification json from:

https://d1mta8qj7i28i2.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json

both properties are specified as not required:

```json
    "AWS::EC2::VPC": {
      "Documentation": "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpc.html",
      "Properties": {
        "CidrBlock": {
          "Documentation": "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpc.html#cfn-ec2-vpc-cidrblock",
          "UpdateType": "Immutable",
          "Required": false,
          "PrimitiveType": "String"
        },
        ...
        "Ipv4IpamPoolId": {
          "Documentation": "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpc.html#cfn-ec2-vpc-ipv4ipampoolid",
          "UpdateType": "Immutable",
          "Required": false,
          "PrimitiveType": "String"
        },
        ...
      },
     ...
    },
```

**Comment by Jacco** [comment]
`packages/@aws-cdk/cfnspec/build-tools/update.sh` contains the path from where the spec is downloaded.

Slightly different url, but I checked it is the one from us-east-1 (I think I chose a european one).

Inside though it also has CidrBlock and IPv4IpamPoolId as *not* required.

I guess the spec just needs an update :-)

**Comment by corymhall** [comment]
@mrpackethead it looks like `cidrBlock` was changed from required to optional in the CloudFormation
spec very recently. It was merged as part of the [v69.0.0](https://github.com/aws/aws-cdk/pull/20240/) version last week and should be in this
weeks CDK release.

**Comment by mrpackethead** [comment]
@corymhall , thanks muchly.  Being able to use the IpamPools is really cool.

**Comment by mrpackethead** [comment]
the lastest version resolved this issue
