### ISSUE TITLE
aws-s3: wrong code example for Bucket construct

### ISSUE THREAD

**Issue by vgkowski** [aws/aws-cdk#20374]
### Describe the issue

The code example published in S3 module documentation is wrong and pointing to CodeBuild Project construct example

### Links

https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-s3.Bucket.html
https://docs.aws.amazon.com/cdk/api/v1/python/aws_cdk.aws_s3/Bucket.html

**Comment by peterwoodworth** [comment]
Thanks for reporting this @vgkowski,

Our examples are automatically pulled from code snippets found in our various readme files. Though, we do have the choice to create our own example if the linked example isn't a very good one. We can create a new example here 🙂 Check out the [contributing guide](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) to get started if you're interested

**Comment by jogold** [comment]
> Our examples are automatically pulled from code snippets found in our various readme files.

This looks more like a bug in the generated doc... have a look at the link. All construct have a generated example and here it is a CodeBuild example in the S3 doc.

**Comment by peterwoodworth** [comment]
This happens because the S3 bucket doesn't have an associated example. We have a process that searches for a representative code sample across the code base and then automatically includes it

We can work around this specifically by adding in an `@example` tag to the class's docstring, and then writing the example there

**Comment by peterwoodworth** [comment]
Correct. However I'm fairly certain it will opt to use an existing example that features the class, if one exists in the code base

**Comment by daschaa** [comment]
@peterwoodworth Sorry for the dumb question, but how can i build the documentation to see if the example is rendered correctly? I'm currently working on this, but I didn't find a way to check if the example is rendered like expected. 😅

**Comment by peterwoodworth** [comment]
That's not a dumb question because I'm not sure about that myself, if there even is a way 😅 

Feel free to submit the PR and we'll be able to tell from that if it will render as expected 🙂
