### ISSUE TITLE
Add a type-safe alternative to constructing the `buildspec`

### ISSUE THREAD

**Issue by skinny85** [aws/aws-cdk#2039]
Right now, the `buildspec` is an `any`, which means it's created completely free-form:

```ts
  buildspec: {
    version: '0.2',
    phases: {
      install: {
        commands: 'npm install',
      },
      build: {
        commands: [
          'npm run test',
          'npm run build',
        ],
      },
    },
  },
  // ...
```

This is fine, however has some downsides:

* It requires pretty intimate knowledge of the CodeBuild YAML format - the code itself does not give any hints on how to create this object correctly.
* The experience in non-JS based languages like Java is not great.

We should add a way to have a more-type safe way to create these. At the same time, we should most likely keep the free-form API as well, so that we don't block customers from accessing new features of the `buildspec` (like version `0.3`) before we update our CDK code.

A possible solution, inspired a little bit by [Lambda's `code` API](https://github.com/awslabs/aws-cdk/blob/master/packages/%40aws-cdk/aws-lambda/README.md#handler-code):

```ts
  buildspec: Buildspec.freeform({
    version: '0.2',
    phases: {
      install: {
        commands: 'npm install',
      },
      build: {

  // ...

  buildspec: Buildspec.version02()
    .addBuildCommands('npm run test', 'npm run build')
    .addInstallCommand('npm install'),
```

Of course, that's just a suggestion - details of the design are up to the implementer.

**Comment by rix0rrr** [comment]
I like it!

But I'm finding myself trending more and more towards objects that take an interface as argument, rather than fluid interfaces. So if we can somehow model it that way, that'd be even better (or a combination of the two).

**Comment by skinny85** [comment]
Care to add a snippet with some example code @rix0rrr illustrating what you mean? Thanks!

**Comment by rix0rrr** [comment]
I mean I think I'd rather have something that starts from:

```ts
BuildSpec.version02({
  buildCommands: ['npm run test', 'npm run build'],
  // ...
})
```

etc. wherever possible

**Comment by rix0rrr** [comment]
There is a proto-version of this here:

https://github.com/awslabs/aws-delivlib/pull/90/files#diff-e624c3b6a4aa21fd0facab04f698fc8e

Modeling of primary/secondary artifacts, and keeping buildspecs mergeable, is the biggest design challenge.

Integration of SecretsManager secrets would be great, is currently completely missing.

**Comment by rix0rrr** [comment]
If we start with a `BuildSpec.fromLiteral()` and nothing else we at least have a GA-safe extension point.

**Comment by brianfoody** [comment]
Have to say I really like the.from API you were leaning towards @skinny85

**Comment by skinny85** [comment]
Care to open us a PR with your proposal @brianfoody ? 🙂

https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md

**Comment by moltar** [comment]
Why was this issue closed? Seems like a useful thing to have

**Comment by skinny85** [comment]
Fair enough @moltar. I just want to emphasize that [contributions](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) for this functionality are very much welcome 🙂.

**Comment by moltar** [comment]
Is there a JSON Schema for buildspec?

Maybe we can use something like that to codegen a type?
