### ISSUE TITLE
EKS: Pull helm/chart using oci

### ISSUE THREAD

**Issue by mburket** [aws/aws-cdk#20402]
### Describe the bug

Hi,

I am trying to install helm/chart from the AWS ECR, but ran into error when the kubectl_handler pulls the helm/chart. Looks like it is reading the entire ecr login and helm pull commands as a file name. Please see error below (I masked our aws account id and the repo name):

[ERROR] FileNotFoundError: [Errno 2] No such file or directory: 'aws ecr get-login-password --region us-east-1 | helm registry login --username AWS --password-stdin xxx.dkr.ecr.us-east-1.amazonaws.com; helm pull oci://xxx.dkr.ecr.us-east-1.amazonaws.com/xxx --version 0.1.0 --untar': 'aws ecr get-login-password --region us-east-1 | helm registry login --username AWS --password-stdin xxx.dkr.ecr.us-east-1.amazonaws.com; helm pull oci://xxx.dkr.ecr.us-east-1.amazonaws.com/xxx --version 0.1.0 --untar'
Traceback (most recent call last):
  File "/var/task/index.py", line 17, in handler
    return helm_handler(event, context)
  File "/var/task/helm/__init__.py", line 85, in helm_handler
    chart_dir = get_chart_from_oci(tmpdir.name, release, repository, version)
  File "/var/task/helm/__init__.py", line 126, in get_chart_from_oci
    output = subprocess.check_output(cmnd, stderr=subprocess.STDOUT, cwd=tmpdir, env=env)
  File "/var/lang/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/var/lang/lib/python3.7/subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/var/lang/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/var/lang/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)

### Expected Behavior

helm/chart pull and installation should work when chart is stored in AWS ECR.

### Current Behavior

kubectl_handler throws FileNotFoundError.

### Reproduction Steps

Add a helm/chart as below in code:

new eks.HelmChart(scope, 'xxx', {
        cluster: cluster,
        chart: 'xxx',
        release: 'xxx',
        repository: `oci://${accountId}.dkr.ecr.${region}.amazonaws.com/xxx`,
        namespace: 'kube-system',
        version: '0.1.0'
    });

### Possible Solution

A good discussion from stackoverflow: https://stackoverflow.com/questions/24306205/file-not-found-error-when-launching-a-subprocess-containing-piped-commands

### CDK CLI Version

2.21.1

### Node.js Version

1.14

### OS

MacOs

### Language

Typescript

**Comment by calebpalmer** [comment]
I'm also seeing this same error.

**Comment by hbhatia-demyst** [comment]
I wrote the first implementation after testing the changes. Which was reverted by this PR https://github.com/aws/aws-cdk/pull/19778

I have raised some comments with author to clarify. @mburket , feel free to raise PR if you like. Otherwise, i will put PR for reverting that change.

**Comment by harshadbhatia** [comment]
I wrote the first implementation after testing the changes. Which was patched by this PR https://github.com/aws/aws-cdk/pull/19778

I have raised some comments with author to clarify. @mburket , feel free to raise PR if you like. Otherwise, i will put PR for reverting that change.

**Comment by hbhatia-demyst** [comment]
@otaviomacedo , have put a PR to fix this and also support public ECR as well. #20724

**Comment by craigjam** [comment]
is this working for anyone? 
In 2.30.0, which should contain the PR above, I get the following error - but this command runs fine standalone:
[ERROR] FileNotFoundError: [Errno 2] No such file or directory: 'aws ecr get-login-password --region us-west-2 | helm registry login --username AWS --password-stdin account.dkr.ecr.us-west-2.amazonaws.com; helm pull oci://account.dkr.ecr.us-west-2.amazonaws.com/my-helm-app --version v0.1.0 --untar': 'aws ecr get-login-password --region us-west-2 | helm registry login --username AWS --password-stdin account.dkr.ecr.us-west-2.amazonaws.com; helm pull oci://account.dkr.ecr.us-west-2.amazonaws.com/my-helm-app --version v0.1.0 --untar'

**Comment by harshadbhatia** [comment]
I personally have been waiting for it merged. Is this a private or a public repository which you are using ?

If you stack was previously created i.e. prior to cdk version upgrade you will notice that CDK doesnt actually update the lambda code, so you might have to recreate the stack.

**Comment by craigjam** [comment]
private repository (but I also can't get it to work with public), and I destroyed and recreated the stack as I suspected that might be the case!

**Comment by AntonAIT** [comment]
Hey everyone!
I experienced the same issue on version 1.65.0. I saw that the bug was resolved on version 2.21.0 but at v1 it's just not...
Once I added Shell=True it works but it's a manual process. Please fix the bug on v1 too.

**Comment by Obirah** [comment]
I'm witnessing another weird behavior: when I try to pull a Helm Chart from an OCI repo (aws-cdk 2.33.0), instead of doing the pull, Helm only prints its help in the kubectl-layer as if the issued command only was `helm` and after that the Chart deployment of course fails because there are no Chart files..

**Comment by pahud** [comment]
As https://github.com/aws/aws-cdk/pull/20724 has been merged, I presume this should be fixed. I'm closing it for now. Feel free to re-open if it's still relevant.
