### ISSUE TITLE
PolicyPrincipal assumeRoleAction should support multiple actions

### ISSUE THREAD

**Issue by reillykw** [aws/aws-cdk#2041]
currently, assumeRoleAction for PolicyPrincipals in the iam package doesn't support multiple actions and is defined as a string.  Some orgs require assumeRole and assumeRoleWithSAML and this currently isn't possible.  This type should support ```string | Array<string>```

**Comment by rix0rrr** [comment]
Still relevant.

**Comment by reillykw** [comment]
So I submitted a PR months ago and it was rejected due to L2 construct attribute rules.  Without modifying that attribute, I'm uncertain how this would be achieved.  Any tips would be helpful.

**Comment by reillykw** [comment]
So I was looking at the CompositePrincipal class and it's still limited because it inherits from PrincipalBase where the assumeRoleAction is a string type. Wouldn't accepting an array for the action type allow multiple actions on a single principal and at least close this issue out? I'm trying to catch up on how all of these objects interact with the synthesizer (how they actually get translated into json cloudformation) as well, so if you could direct me to where that takes place I can read up on the code.  I'm digging through the repo now.

**Comment by miekassu** [comment]
still relevant
