### ISSUE TITLE
(docs): API ref uses underscore in typescript package names

### ISSUE THREAD

**Issue by kevinvaningen** [aws/aws-cdk#20411]
### Describe the issue

There is a typo in the docs on ReceiptRuleSet. It refers to the import as `aws-cdk-lib » aws_ses » ReceiptRuleSet` while it is actually `aws-ses`, so not an underscore but a hyphen. 

I could not find where to make a pr to correct this, unfortunately. 

### Links

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ses.ReceiptRuleSet.html

**Comment by daschaa** [comment]
I had a look on this and it seems like in every package is this typo. I think the documentation generation has to be changed to fix this. 🤔

**Comment by peterwoodworth** [comment]
We actually accept either import method

```
import { aws_dynamodb } from 'aws-cdk-lib';
```
This will work just fine 🙂 

This method is shown in our [migrating to v2 devguide](https://docs.aws.amazon.com/cdk/v2/guide/migrating-v2.html#migrating-v2-v1-uppgrade)

Let me know if there are more concerns
