### ISSUE TITLE
core: support editing CfnResource and Stack dependencies

### ISSUE THREAD

**Issue by jusdino** [aws/aws-cdk#20418]
### Describe the feature

Currently, a user has the ability to use `CfnResource.addDependsOn()` to neatly add explicit dependencies between resources within or across stack boundaries. The catch is that, `Node.tryRemoveChild()` can then render a CFT completely invalid, since it can remove the referenced resource from a template entirely but a lingering `DependsOn` value remains set to a logical id that no longer exists. `Node.tryRemoveChild()` is, of course, in the 'escape hatch' api space, so I wouldn't expect it to gracefully search out any existing dependency references and remove them for me. However, since there is no visibility into already-set dependencies or any ability to gracefully remove individual dependencies, once a depended-on resource is removed, it becomes impossible for a user to salvage the template through the public API, short of something extreme like blindly adding DependsOn overrides to every resource they think might have a reference to the removed resource, possibly causing a lot more damage in the process. Adding some new methods that give a user the visibility and edit-ability to dependencies would be very powerful in a situation like this.

### Use Case

Let's say a user has some code:
```TypeScript
let foo = CfnResource(this, 'Foo', ...);
let bar = CfnResource(this, 'Bar', ...);
// We need bar deployed first
foo.addDependsOn(bar);
```
But then they use some construct/aspect/whatever that needs to recreate `Bar` for some reason:
```TypeScript
const stack = Stack.of(this);
stack.node.tryRemoveChild('Bar');
const barReplacement = CfnResource(stack, 'BarReplacement', <some alternate properties or something>);
```
At this point, the construct that replaced `Bar` has no way of knowing that it has just irrevocably invalidated the template, because it has no way of seeing that `Foo` has a `DependsOn` reference to `Bar`, and the only possible way to rectify the template is to add `foo.addOverride('DependsOn', ...)`, possibly squashing some other dependencies in the process.

### Proposed Solution

Add some new methods to `CfnResource` that makes it possible to look into the dependency relationships and edit them if they really need to:
```TypeScript
foo = stack.tryFindChild('Foo');
if (foo.obtainDependsOn().contains(bar)) {
  foo.removeDependsOn(bar);
fi
foo.addDependsOn(barReplacement);
```
 These new `CfnResource.obtainDependsOn()` and `CfnResource.removeDependsOn()` would have to gracefully traverse the resource and assembly dependencies to mirror the behavior of `CfnResource.addDependsOn()`, for an intuitive user experience.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

any

### Environment details (OS name and version, etc.)

any

**Comment by comcalvi** [comment]
Closed by #23383
