### ISSUE TITLE
aws-ecs: Python3.6 EOL

### ISSUE THREAD

**Issue by guidobit** [aws/aws-cdk#20410]
### Describe the bug

According to an email sent by the friendly people from no-reply, Python3.6 will reach EOL.

Quote from email:

```
We are contacting you as we have identified that your AWS Account currently has one or more Lambda functions using Python 3.6 runtime.

We are ending support for Python 3.6 in AWS Lambda. This follows Python 3.6 End-Of-Life (EOL) reached on December 23, 2021 [1].

As described in the Lambda runtime support policy [2], end of support for language runtimes in Lambda happens in two stages. Starting July 18, 2022, Lambda will no longer apply security patches and other updates to the Python 3.6 runtime used by Lambda functions, and functions using Python 3.6 will no longer be eligible for technical support. In addition, you will no longer be able to create new Lambda functions using the Python 3.6 runtime. Starting August 17, 2022, you will no longer be able to update existing functions using the Python 3.6 runtime.

We recommend that you upgrade your existing Python 3.6 functions to Python 3.9 before August 17, 2022.
```

### Expected Behavior

Deployments using this runtime version do not break starting from July 18th.

### Current Behavior

Python3.6 is still used in aws-cdk.

Example:
https://github.com/aws/aws-cdk/blob/0367fe850af419d0d9e39d9b84e2b22abd4d1250/packages/%40aws-cdk/aws-ecs/lib/drain-hook/instance-drain-hook.ts#L70

### Reproduction Steps

Not really applicable.

### Possible Solution

Update runtime in cdk framework to 3.9, deprecate the 3.6 version in valid runtimes.

### CDK CLI Version

not applicable

### Framework Version

any

### Node.js Version

not applicable

### OS

not applicable

### Language

Python

### Language Version

3.6

**Comment by peterwoodworth** [comment]
Hey, we're currently working on this 🙂 Tracking at #20085 and PR here #19988
