### ISSUE TITLE
(aws-codepipeline): Cross-account KMS key is incorrectly documented.

### ISSUE THREAD

**Issue by youngjeong46** [aws/aws-cdk#20420]
### Describe the issue

According to [the API doc](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_codepipeline.Pipeline.html#crossaccountkeys), Cross Account KMS Keys for Pipeline is defaulted to true. 

However, the [code](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-codepipeline/lib/pipeline.ts#L163) suggest it is defaulted to false. 

Creating a test pipeline without cross account key provided results in the key error in multi-account deployment, suggesting that the doc should be changed.

### Links

[API DOC](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_codepipeline.Pipeline.html#crossaccountkeys)

[Github code](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-codepipeline/lib/pipeline.ts#L163)

**Comment by daschaa** [comment]
Hey! I think you slipped in the line. The code which is linked is the default for the `enableKeyRotation` property. [A few lines higher is the `crossAccountKeys` property.
](https://github.com/aws/aws-cdk/blob/01708bc7cf842eab7e1d1fc58bf42e4724624c0a/packages/%40aws-cdk/aws-codepipeline/lib/pipeline.ts#L153)

[To be sure that the JSDoc is correct, i have looked in the code:](https://github.com/aws/aws-cdk/blob/01708bc7cf842eab7e1d1fc58bf42e4724624c0a/packages/%40aws-cdk/aws-codepipeline/lib/pipeline.ts#L384)
```javascript
    this.crossAccountKeys = props.crossAccountKeys ?? true;
    this.enableKeyRotation = props.enableKeyRotation;
```

**Comment by TheRealAmazonKendra** [comment]
@daschaa is correct, `crossAccountKeys` defaults to `true` while `enableKeyRotation` defaults to `false`. I believe there is no issue here but please open a new issue if you believe this is incorrect. Closing this for now.
