### ISSUE TITLE
ApplicationMultipleTargetGroupsFargateService: Avoid opening port 80 to everyone

### ISSUE THREAD

**Issue by ss-ravi** [aws/aws-cdk#20444]
### Describe the feature

When I was using `ApplicationLoadBalancedFargateService` I could just use `openListener: false`, But now that I need 3 targets and 3 listeners, I changed to `ApplicationMultipleTargetGroupsFargateService`.

The MultipleTarget version doesn't have the `openListener`. It automatically adds a rule that opens all inbound traffic in port 80 to everyone.

### Use Case

I need to have my own security group. allowing only my company's IP as an ingress rule.

### Proposed Solution

allow passing my own security group to the construct.
or at least an option to avoid it automatically opening the port 80.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.20.0

### Environment details (OS name and version, etc.)

Mac OS Monterey v12.3

**Comment by peterwoodworth** [comment]
Our higher level constructs found in the ecs-patterns module are generally supposed to abstract away finer details like these. However, they should still be configurable without escape hatches. If you're willing, would you be willing to create a PR for this and the team can discuss with you from there?

**Comment by ss-ravi** [comment]
@peterwoodworth 
Thank you for the response. Unfortunately I wont be able to contribute on this issue, but I will leave my workaround for people with the same problem.

I actually stopped using the ecs_patterns and use just the L2 Constructs individually..
it looks something like this:

```typescript
let scope: Construct;
let vpc: ec2.IVpc;
let cluster: ecs.ICluster;
let taskDefinition: ecs.TaskDefinition;
let containerName: string;
const prepareService = () => {
  const alb = new elbv2.ApplicationLoadBalancer(scope, 'ALB', {
    vpc,
    internetFacing: true,
  });

  const listener = alb.addListener(`Listener`, {
    open: false,
  });

  const fargateService = new ecs.FargateService(scope, 'FargateService', {
    cluster,
    taskDefinition,
  });

  fargateService.registerLoadBalancerTargets({
    containerName,
    newTargetGroupId: 'my-target-group-id',
    listener: ecs.ListenerConfig.applicationListener(listener, {
      protocol: elbv2.ApplicationProtocol.HTTP,
    }),
  });
};
``` 

doing it like this makes it a lot more customizable, and you can add multiple targets with no problem.

I still think that the ecs_patterns feature should be added, so I'll leave this open.
But since its not a priority for me anymore, feel free to close it if necessary.
