### ISSUE TITLE
(cli): run custom code after CDK has finished deploying a stack

### ISSUE THREAD

**Issue by misterjoshua** [aws/aws-cdk#20455]
### Describe the feature

I'd like the CDK to allow me to run custom asynchronous code after each stack has been deployed.

### Use Case

I'd like to write a CDK plugin that reports on how long it takes to do each resource create / update during a deployment by sending info from `DescribeStackEvents` to an opentelemetry collector whenever the AWS CDK deploys a stack. The idea here is to get more visibility into what's taking my stacks so long to deploy.

### Proposed Solution

Perhaps we could add an experimental `registerPostDeployHookAlpha()` method to `PluginHost` and add logic to run all registered hooks in the appropriate section of the CDK CLI.

### Other Information

The opentelemetry idea belongs to @aidansteele https://twitter.com/__steele/status/1528288888456101889.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

N/A

### Environment details (OS name and version, etc.)

N/A

**Comment by rix0rrr** [comment]
That's a very interesting idea! 

Feels like this wouldn't really need to be integrated into the CDK CLI though? EventBridge + a Lambda would be able to do the same job, and would have the advantage it would also work when not deploying via the CLI?

**Comment by misterjoshua** [comment]
Sure, it's possible to do it that way too. We'll find another way to do this. Thanks.
