### ISSUE TITLE
aws-ecs: DrainECSHookFunction Lambda runtime version. Update to v3.9

### ISSUE THREAD

**Issue by mp365** [aws/aws-cdk#20465]
### Describe the feature

The aws-ecs module creates a Lambda called [DrainECSHookFunction](https://github.com/aws/aws-cdk/tree/master/packages/@aws-cdk/aws-ecs/lib/drain-hook). The Lambda runtime for this module is currently set at 3.6 on [L70](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-ecs/lib/drain-hook/instance-drain-hook.ts#L70).

Python 3.6 was made EOL in December 2021 and AWS have emailed customers to recommend upgrading existing Python 3.6 functions to Python 3.9 before August 17, 2022. more info is available in the [Lambda Support policy](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html#runtime-support-policy).

### Use Case

To maintain an up to date Lambda runtime and ensure continued support of the full deployed stack. 

### Proposed Solution

Update the Lambda runtime ([L70](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-ecs/lib/drain-hook/instance-drain-hook.ts#L70)) for the DrainECSHookFunction to version 3.9. 

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

1.56.1

### Environment details (OS name and version, etc.)

Amazon Linux 2

**Comment by kaizencc** [comment]
#19988 closed this issue
