### ISSUE TITLE
cdk: npm run synth is broken

### ISSUE THREAD

**Issue by ilyash-b** [aws/aws-cdk#20463]
### Describe the bug

`npm run cdk synth >template.yaml` results invalid YAML file.

### Expected Behavior

Valid YAML in the output file.

### Current Behavior

The top of the file has:
```

> proj1@0.1.0 cdk
> cdk "synth"

```

followed by valid YAML

```
$ npm --version
8.5.5
```

### Reproduction Steps

`npm run cdk synth >template.yaml`

### CDK CLI Version

2.25.0 (build ae1cb4b)

### Node.js Version

v16.15.0

### OS

MacOS

### Language

Typescript

### Language Version

3.9.10

**Comment by rix0rrr** [comment]
Can you be more specific about the last time this used to work for you, and what has changed since then?

**Comment by ilyash-b** [comment]
I don't remember when or if I tried that at all in the past, I just tried today.

**Comment by rix0rrr** [comment]
This is just NPM's behavior. If you do not want NPM to add its banner, use `npx`: `npx cdk synth`
