### ISSUE TITLE
dotnet: Could not determine JSON object type for type Amazon.JSII.Runtime.Deputy.EnumValue

### ISSUE THREAD

**Issue by andersgodballe** [aws/aws-cdk#2048]
When trying to create a Regional LambdaRestApi, `cdk synth` fails with `Unhandled Exception: Amazon.JSII.Runtime.JsiiException: System.ArgumentException: Could not determine JSON object type for type Amazon.JSII.Runtime.Deputy.EnumValue.`
See stack trace below

CDK Version: 0.25.3

CDK Example:
```
var myRestApi = new LambdaRestApi(this, "MyRestAPI", new LambdaRestApiProps
{
    Handler = myLambdaFunction,
    Options = new RestApiProps
    {
        EndpointTypes = new EndpointType[] { EndpointType.Regional }
    }
});
```

Stacktrace:

> Unhandled Exception: Amazon.JSII.Runtime.JsiiException: System.ArgumentException: Could not determine JSON object type for type Amazon.JSII.Runtime.Deputy.EnumValue.
>    at Newtonsoft.Json.Linq.JValue.GetValueType(Nullable`1 current, Object value)
>    at Newtonsoft.Json.Linq.JContainer.CreateFromContent(Object content)
>    at Newtonsoft.Json.Linq.JContainer.AddInternal(Int32 index, Object content, Boolean skipParentCheck)
>    at Amazon.JSII.Runtime.Services.Converters.FrameworkToJsiiConverter.TryConvertArray(IReferenceMap referenceMap, TypeReference elementType, Object value, Object&result)
>    at Amazon.JSII.Runtime.Services.Converters.ValueConverter.TryConvert(TypeReference typeReference, IReferenceMap referenceMap, Object value, Object& result)
>    at Amazon.JSII.Runtime.CallbackExtensions.InvokeCallback(Callback callback, IReferenceMap referenceMap, IFrameworkToJsiiConverter converter, String& error)
>    at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
>    at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
>    at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
>    at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
>    at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
>    at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
>    at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
>    at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
>    at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
>    at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
>    at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
>    at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
>    at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
>    at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
>    at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
>    at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
>    at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
>    at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
>    at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
>    at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
>    at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
>    at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
>    at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
>    at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
>    at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
>    at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
>    at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
>    at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
>    at Amazon.JSII.Runtime.Deputy.DeputyBase..ctor(DeputyProps props)

**Comment by rix0rrr** [comment]
@costleya any quick idea what this might be?

**Comment by drch-** [comment]
This also occurs with CDK 0.23.0

**Comment by assyadh** [comment]
Needs repro with the new generator.

**Comment by andersgodballe** [comment]
Just testet this with AWS CDK 1.12.0 and it seems to work with a small modification to the example above.

```
var myRestApi = new LambdaRestApi(this, "MyRestAPI", new LambdaRestApiProps
{
    Handler = myLambdaFunction,
    EndpointTypes = new EndpointType[] { EndpointType.REGIONAL }
});
```

Thank you :)
