### ISSUE TITLE
aws-events/Rule: Cannot create an EventBridge rule with a filter on resource

### ISSUE THREAD

**Issue by rcalme** [aws/aws-cdk#20486]
### Describe the bug

EventBridge rules allow for [content filtering](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-event-patterns-content-based-filtering.html#eb-filtering-anything-but). One type is `{"anything-but": ...}`.

I want to create an EventBridge Rule with CDK that specifies an `anything-but` filter for the rule's `resources` block. The [EventPattern of the CDK Rule construct](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_events.EventPattern.html#resources) requires that `resources` be a `string[]`, assuming ARN(s) are the only kinds of values that might be used.

Can the CDK `EventPattern` construct be changed such that `resources` (and any others that can accept content filters via CFN) are `any`-typed, so that they can be used as fluently as raw CFN allows?

### Expected Behavior

CDK `Rule` and `EventPattern` constructs should allow the specification of content filters, as [documented here](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-event-patterns-content-based-filtering.html).

### Current Behavior

If I use:
```
new events.Rule(this, "Trigger", {
  description: "...",
  eventPattern: {
    source: ["aws.dataexchange"],
    detailType: ["Revision Published To Data Set"]
    // All subscribed ADX data sets EXCEPT this one
    resources: [{"anything-but": "aae4c2cd145a48454f9369d4a4db5c66"}
  },
  targets: [new targets.SqsQueue(...)]
});
```

Then an error is thrown, that:
```
error TS2322: Type '{ "anything-but": string; }' is not assignable to type 'string'.
```

Understandable. The CDK `EventPattern` construct is too strictly typed, and should probably be `any[]` instead.

## Workaround:
I tried to use the escape hatch, and set the same in the `CfnRule` construct:
```
(rule.node.defaultChild as events.CfnRule).eventPattern["resources"] = [
  {"anything-but": "aae4c2cd145a48454f9369d4a4db5c66"}
] 
```

But it seems to have no effect on the generated CFN.

Trying it this way throws errors about the `EventPattern` being a `LazyAny` and fails to compile:
```
const cfnRule = rule.node.defaultChild as events.CfnRule
  cfnRule.eventPattern = {
    ...cfnRule.eventPattern,
    resources: [{"anything-but": "aae4c2cd145a48454f9369d4a4db5c66"}]
  }
```

This solution finally worked:
```
(rule.node.defaultChild as events.CfnRule).addPropertyOverride(
  "EventPattern.resources",
  [{"anything-but": "aae4c2cd145a48454f9369d4a4db5c66"}]
);
```

And generated the intended CFN that gets the desired effect when deployed.

### CDK CLI Version

2.x

### Node.js Version

14.x

### OS

macOS

### Language

Typescript

**Comment by hrenod** [comment]
A simpler workaround could be to override the type `as any[]`
```
resources: [{"anything-but": "aae4c2cd145a48454f9369d4a4db5c66"}] as any[]
```

**Comment by adrian-skybaker** [comment]
I think this issue is broader - it doesn't appear possible to define expressions on any of the built in fields (`source|account|region|resources|detail-type|time|version`). 

So far I'm also not able to workaround in the Java SDK using unchecked casts.
