### ISSUE TITLE
Transit Gateway: Construct for accepting Transit Gateway <-> VPC attachment request

### ISSUE THREAD

**Issue by digven** [aws/aws-cdk#20493]
### Describe the feature

We have construct available for submitting Transit Gateway <-> VPC attachment. But there is no construct available to accept that request.

Need a CDK construct for approving Transit Gateway <-> VPC attachment request

### Use Case

I do know there is a way to auto approve these requests when creating the attachment. But there are lot of use cases/scenarios where we need the approval stage

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.25.0

### Environment details (OS name and version, etc.)

Linux

**Comment by corymhall** [comment]
There are currently no CloudFormation resources that allow you to accept an attachment request. That  being said, you  could accomplish this in two ways.

1. Use the [autoAcceptSharedAttachments](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ec2.CfnTransitGateway.html#autoacceptsharedattachments) on the `CfnTransitGateway`
2. Use a [custom resource](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.custom_resources-readme.html#custom-resources-for-aws-apis) to make the [accept-transit-gateway-vpc-attachment](https://docs.aws.amazon.com/cli/latest/reference/ec2/accept-transit-gateway-vpc-attachment.html) api call.

In the future if we create L2s for TransitGateway resources this could be part of that work, but I don't think we should track this separately from https://github.com/aws/aws-cdk/issues/17528.

**Comment by peterwoodworth** [comment]
Closing in favor of #17528
