### ISSUE TITLE
Lambda props does not allow you to bring your own Role

### ISSUE THREAD

**Issue by rclark** [aws/aws-cdk#205]
I don't know how to attach my own role to a Lambda function -- the props won't accept one, and the `.role` attribute is read-only. I usually write a dedicated role to associate with any Lambda function, or reference one that has been created independently. '@aws-cdk/lambda' `Lambda` seems to be hard-wired to provide its own service role?

**Comment by bgdnlp** [comment]
For others that arrive here looking for how to create the IRole object needed, use the [from_role_arn](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_iam/Role.html#aws_cdk.aws_iam.Role.from_role_arn) method of the Role class in aws_cdk.aws_iam.

Example Python code:
```
from aws_cdk import aws_iam

role = aws_iam.Role.from_role_arn(self, 'role_id', 'arn:aws:iam::123456789012:role/myrole')
```
will create an IRole object that can be passed as a parameter to Lambda Function.

**Comment by SILVERSPASE** [comment]
I didn't managed to add role during lambda creation, but next code adds to lambda external role, created in another CDK:
`    lambdaFn.addToRolePolicy(new iam.PolicyStatement({
      effect: iam.Effect.ALLOW,
      actions: [ "sts:AssumeRole" ],
      resources: [externalRoleArn]
    }))`

**Comment by fatihaslantas** [comment]
whoever come to solve circular reference issue, Role.FromRoleArn function will solve your issue.
