### ISSUE TITLE
(synthetics): Add new runtime SYNTHETICS_NODEJS_PUPPETEER_3_6

### ISSUE THREAD

**Issue by lukehedger** [aws/aws-cdk#20502]
### Describe the feature

<img width="1434" alt="image" src="https://user-images.githubusercontent.com/1913316/170462540-7120c1f6-633a-40c7-9146-fc9efa897e64.png">

### Use Case

Ability to upgrade canaries to latest runtime

### Proposed Solution

Add new constant [here](https://github.com/aws/aws-cdk/issues/aws-synthetics/lib/runtime.ts) called SYNTHETICS_NODEJS_PUPPETEER_3_6 with value new Runtime('syn-nodejs-puppeteer-3.6', RuntimeFamily.NODEJS);

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2

### Environment details (OS name and version, etc.)

n/a

**Comment by mrgrain** [comment]
Closed by https://github.com/aws/aws-cdk/pull/22374
