### ISSUE TITLE
(rds): (combination of postgres version and instance type)

### ISSUE THREAD

**Issue by entest-hai** [aws/aws-cdk#20501]
### Describe the bug

CDK not able to suggest a correct combination between postgres version and instance type. CDK synth show no error. For example 
```tsx
 engine: aws_rds.DatabaseInstanceEngine.postgres({
          version: aws_rds.PostgresEngineVersion.VER_13_5,
        }),
      instanceType: aws_ec2.InstanceType.of(
        aws_ec2.InstanceClass.BURSTABLE2,
        aws_ec2.InstanceSize.SMALL
      ),
```

### Expected Behavior

CDK synth should show error that postgres 13.5 is not able to be combined with aws_ec2.InstanceSize.SMALL 

### Current Behavior

CDK synth does not show error. CDK deploy later on show error 

### Reproduction Steps

const rds = new aws_rds.DatabaseInstance(
      this,
      "RdsIntance",
      {
        removalPolicy: RemovalPolicy.DESTROY,
        databaseName: props.dbName,

       // some auto-suggested versions are not found, not available in aws console
        engine: aws_rds.DatabaseInstanceEngine.postgres({
          version: aws_rds.PostgresEngineVersion.VER_13_5,
        }),
        instanceType: aws_ec2.InstanceType.of(
          aws_ec2.InstanceClass.BURSTABLE2,
          aws_ec2.InstanceSize.SMALL
        ),
        vpc,
        vpcSubnets: {
          // production => private subnet
          subnetType: aws_ec2.SubnetType.PRIVATE_WITH_NAT,
        },

        // db credentials generated and stored in SM
        credentials: aws_rds.Credentials.fromGeneratedSecret(
          "postgres",
          {
            secretName: "postgres-secrete-name",
          }
        ),
      }
    );

### CDK CLI Version

2.20

### Framework Version

typescript 

### Node.js Version

16.14.2

### OS

ubuntu

### Language

Typescript

### Language Version

3.9.7

**Comment by corymhall** [comment]
This is an interesting problem, and I'm not sure how we would go about solving it. This doc explains how you can determine what instance types are supported for which db engines in which regions https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.DBInstanceClass.html#Concepts.DBInstanceClass.RegionSupport.

We would need to create and maintain a full list of each engine version X regions X supported instance types. I don't think this is something  we will take on anytime soon (and we may never) so I am going to label this as a `p2` priority.
