### ISSUE TITLE
apigateway.BasePathMapping: How to set mapping correctly with custom domain?

### ISSUE THREAD

**Issue by xwnor** [aws/aws-cdk#20518]
### Describe the issue

Hi,

I'd like to set a custom domain and stage mapping for my `apigateway.RestApi`. The console path is: API Gateway -> Custom domain names -> API mappings.

Say the default API endpoint is: `https://abcdefg.execute-api.ap-northeast-1.amazonaws.com/dev` (stage is `dev` in this case). I want to have the `example.com` domain to map to `https://abcdefg.execute-api.ap-northeast-1.amazonaws.com/dev`

So that:
`https://abcdefg.execute-api.ap-northeast-1.amazonaws.com/dev`
and 
`https://example.com` return the same result.

## What I did

```ts
const domainNameString = 'example.com'

const apiCertificate = new acm.DnsValidatedCertificate(this, 'ApiCertificate', {
    domainName: domainNameString,
    hostedZone,
});

const api = new apigateway.RestApi(this, 'PublicGateway', {
    restApiName: 'name',
    deploy: false,
    endpointConfiguration: {
        types: [apigateway.EndpointType.REGIONAL],
    },
    domainName: {
        domainName: domainNameString,
        certificate: apiCertificate,
        securityPolicy: apigateway.SecurityPolicy.TLS_1_2,
    }
});

new route53.ARecord(this, 'AliasRecord', {
    recordName: domainNameString,
    zone: hostedZone,
    target: route53.RecordTarget.fromAlias(new route53Targets.ApiGateway(api))
});


new apigateway.CfnBasePathMapping(this, 'BasePathMapping', {
    domainName: domainNameString,
    restApiId: api.restApiId,
    stage: 'dev'
});
```

## What I got

> Resource handler returned message: "Base path already exists for this domain name  (Service: ApiGateway, Status Code: 409, Request ID: <UUID>)" (RequestToken: <UUID>, HandlerErrorCode: AlreadyExists)

Could you have a look? Looking forward to your reply.

### Links

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_apigateway.BasePathMapping.html

**Comment by BwL1289** [comment]
Just to add: make sure that `deploy` is set to `false` in `RestApi` (as it is above), and do not use the `add_domain_name` method as it automatically creates a `mapping`to the RestApi under the hood and you will get the ```Resource handler returned message: "Base path already exists for this domain name (Service: ApiGateway, Status Code: 409, Request ID: )" (RequestToken: , HandlerErrorCode: AlreadyExists)``` error still.
