### ISSUE TITLE
aws-cdk: cloud-assembly-schema version mismatch?

### ISSUE THREAD

**Issue by skeadr** [aws/aws-cdk#20537]
### Describe the bug

- aws-cdk@2.25.0 doesn't work with the newest aws-cdk packages, e.g. @aws-cdk/aws-apigatewayv2@1.158.0

### Expected Behavior

I'd expect to work with both in their newest versions.

### Current Behavior

`This CDK CLI is not compatible with the CDK library used by your application. Please upgrade the CLI to the latest version.
(Cloud assembly schema version mismatch: Maximum schema version supported is 19.0.0, but found 20.0.0)`

This is the current outcome of a `cdk diff`

### Reproduction Steps

diff/deploy a project which is using 1.158.0 packages with aws-cdk 2.25.0

### Additional Information/Context

`aws-cdk 2.25.0` is using `cloud-assembly-schema@2.25.0` which has schema version `19.0.0`
`@aws-cdk/aws-apigatewayv2@1.58.0` is using `cloud-assembly-schema@1.58.0` which has schema version `20.0.0`

### CDK CLI Version

2.25.0

### Node.js Version

v16.13.1

### OS

Mac

### Language

Typescript

**Comment by arikgo** [comment]
hey, looking into the cloud-assembly-schema version, I had 1.158 installed, checking the latest (pip index versions aws-cdk-cloud-assembly-schema I see that version 2.25.0 is available) 
running install with the latest version fixed this for me. 
pip install aws-cdk-cloud-assembly-schema==2.25.0

**Comment by florian-thoni-sonarsource** [comment]
I confirm the bug. I’m trying to update aws-cli to 2.26. However even if this work, it means that for few hours, there have been an existing mismatch. Can please someone from project confirm that, and provide guidance for users to avoid being block by this kind of mismatch?

**Comment by nemmison** [comment]
This happened a couple of weeks ago as well https://github.com/aws/aws-cdk/issues/20135

**Comment by hypeofpipe** [comment]
I've had the same issue. Fixed that by checking package-lock's version of `cdk` package, and applying the same version to `npx cdk`
