### ISSUE TITLE
cdk Tag issue : Tags not getting created with cdk typescript

### ISSUE THREAD

**Issue by anuprana** [aws/aws-cdk#20549]
### Describe the bug

Hi Team,

I am facing an issue creating the tags for the stack using cdk - typescript library.
We are trying to create a stack that create AppMesh resources - Virtual Service,Virtual Route,Add GatewayRoute.

1.Interface is created which extends StackProps (interface provided by cdk lib).
2.Main stack uses the interface as the props in the constructor.
3.While instantiating the main stack, tags Value is passed with in the props which should attach the tags to the AWS Resources.

The same method has been used on the other stack which works for  the tags.
Not sure if the cdk has limitation to create the tags for the AWS App Mesh resources.

CDK Version : 2.14
Language : Typescript

### Expected Behavior

While deploying the stack it should create the stack with the tag values.

### Current Behavior

No tags created.

### Reproduction Steps

1. Create an interface extending StackProps.StackProps has the attribute tags.
   e.g : export interface TagsProps extends StackProps {
   }
2. Add TagsProps in the constructor for the Stack.
 e.g: export class TagsStack extends Stack {
           constructor(scope: Construct, id: string, props: TagsProps) {
           .....
           .....
           .....
           }
  }
3.Calling the TagsStack 
  e.g: 
         new TagsStack(app,stackName,{
             tags: {
                'tag1': tagValue1,
                 'tag2':tagValue2,
             }
         }
 

### CDK CLI Version

2.14.0

### Node.js Version

6.14.12

### OS

Linux

### Language

Typescript

**Comment by peterwoodworth** [comment]
Hey @anuprana,

This is something we know about and are blocked on - since it relies on how CloudFormation resources are specified.

See [this comment](https://github.com/aws/aws-cdk/issues/14127#issuecomment-1023304411) for more info, and please continue discussion on linked thread if desired.
