### ISSUE TITLE
How to use aws-logs feature when using ecs.LoadBalancedEc2Service class?

### ISSUE THREAD

**Issue by JoHuang** [aws/aws-cdk#2054]
Hi

I can't find a way to pass it into ecs.LoadBalancedEc2Service class.

Thanks,
Jo

**Comment by rix0rrr** [comment]
@SoManyHs should we just get rid of the `LoadBalancedXxxService` classes?

**Comment by JoHuang** [comment]
Does that means I should not use `LoadBalancedXxxService`, but use task definition, service, load balancer, and then connect them together by myself?

**Comment by rix0rrr** [comment]
I think that will be best for now.

**Comment by pkandasamy91** [comment]
The LoadBalancedFargateService as well as all ecs-patterns constructs will now accept a LogDriver as input: #3550. @JoHuang is this what you were looking for?

**Comment by JoHuang** [comment]
I built my own combined services because I did have that options before.

Haven't tested the new options, but I guess so.

**Comment by pkandasamy91** [comment]
Changes merged in https://github.com/aws/aws-cdk/pull/3550
