### ISSUE TITLE
aws-autoscaling: tag `AmazonECSManaged` added to AutoScalingGroups by CDK outside CFN template  and causing a CFN drift

### ISSUE THREAD

**Issue by rgoltz** [aws/aws-cdk#20544]
### Describe the bug

Currently we implementing our ECS Cluster (backed by EC2-instances) using CDK. We are using construct `new autoscaling.AutoScalingGroup`. We deployed our Cluster via CDK successfully.

Afterwards we running **CloudFormation (CFN) drift detection** on this stack: CFN drift detection reporting `AmazonECSManaged` as "added outside of CloudFormation" - hence, the stack is reported as DRIFTED.

Further researching regarding this tag, we see in [AWS-doc](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/cluster-auto-scaling.html) mentioned this tag is used for ECS to manage the ASG and should not be removed.

### Expected Behavior

CDK should add this (AWS-needed) tag `AmazonECSManaged` to CFN template generated by CDK. Accordingly stack generated by CDK is in state SYNC once we are trigger CFN drift detection.

### Current Behavior

Currently CDK doesn't add the tag `AmazonECSManaged` to CFN template yaml, hence the CFN drift detection reporting a drift. Following CloudTrail events, we can see this tag has been added by CDK:

> EventName: CreateOrUpdateTags
> Role: arn:aws:iam::<AcccountId>:role/cdk-XX-cfn-exec-role-XX-eu-central-1
> Resource: ElokECS-sandbox-Cluster-ASG
> Parameter: tag key: AmazonECSManaged

Below the CFN drift summary in AWS Console, which showing the drift:
![screencapture-eu-central-1-console-CFN-Drift-ASG-detail-github](https://user-images.githubusercontent.com/16392819/171021067-523281de-7597-4f8c-86bf-d1f51fadee4f.jpg)

### Reproduction Steps

For now, I'm sharing to "full code", since this would fit best suitable for CFN drift output screenshot. In case of need, I can try to simplify the current code-details.

```
export class ElokASG extends Construct {
  readonly autoScalingGroup: autoscaling.AutoScalingGroup;

  constructor(scope: Stack, id: string, props: ElokASGProps) {
    super(scope, id);

    this.autoScalingGroup = new autoscaling.AutoScalingGroup(this, props.name, {
      autoScalingGroupName: props.name,
      instanceType: new ec2.InstanceType(props.instanceType),
      machineImage: ec2.MachineImage.fromSsmParameter(`/ecs/${props.clusterEnvironment}-ami`, {
        os: ec2.OperatingSystemType.LINUX,
      }),
      vpc: props.vpc,
      healthCheck: {
        type: 'EC2',
        gracePeriod: Duration.seconds(300),
      },
      vpcSubnets: {
        subnets: props.vpc.selectSubnets({
          subnetFilters: [
            ec2.SubnetFilter.containsIpAddresses(props.instanceSubnetIPs),
          ],
        }).subnets,
      },
      minCapacity: props.minimumInstanceCount,
      maxCapacity: props.maximumInstanceCount,
      notifications: [
        {
          topic: sns.Topic.fromTopicArn(this, 'ASG-Topic', `arn:aws:sns:${props.region}:${props.accountId}:${props.topicName}`),
          scalingEvents: autoscaling.ScalingEvents.ERRORS,
        },
      ],
      keyName: props.sshKeyName,
      role: props.instanceRole,
      securityGroup: ec2.SecurityGroup.fromSecurityGroupId(this, 'XXXGroup', Fn.importValue('XXX')),
      init: ec2.CloudFormationInit.fromElements(
        ec2.InitFile.fromString('/etc/ecs/ecs-dummy.config', 'emptyline'),
      ),
      userData: props.instanceUserData,
      signals: autoscaling.Signals.waitForMinCapacity({
        timeout: Duration.minutes(5),
      }),
      updatePolicy: autoscaling.UpdatePolicy.rollingUpdate({
        maxBatchSize: 1,
        minInstancesInService: props.minimumInstanceCount,
      }),
      groupMetrics: [new autoscaling.GroupMetrics(autoscaling.GroupMetric.IN_SERVICE_INSTANCES)],
    });

    this.autoScalingGroup.addSecurityGroup(asgSecGroup);

    new CfnOutput(this, `${props.clusterEnvironment}-ASGSecurityGroupExport`, {
      value: asgSecGroup.securityGroupId,
      exportName: `elok-ecs-${props.clusterEnvironment}-asgSecGroup`,
    });

    this.autoScalingGroup.node.children.forEach(construct => {
      const launchConfig = construct as autoscaling.CfnLaunchConfiguration;
      if (launchConfig !== undefined) {
        launchConfig.placementTenancy = props.instanceTenancy;
      }
    });

    Tags.of(this.autoScalingGroup).add('distribution', 'AMZNLINUX2');
  }
}

```

### Possible Solution

The tag `AmazonECSManaged` should be part of the CFN output/stack generated by CDK. In CDK, there might be some operations outside of pure CFN stack deployment that added this tag to the ASG but eventually caused this issue. Maybe this tag is created within some high level CDK classes and it should have logic to not consider this as drift.

Input from CDK team is welcome here.

### CDK CLI Version

2.24.1

### Node.js Version

v16.3.0

### OS

Linux

### Language

Typescript

**Comment by peterwoodworth** [comment]
If you include the line 
```
Tags.of(autoScalingGroup).add('AmazonECSManaged', 'dummyvalue', {includeResourceTypes: ['AWS::AutoScaling::AutoScalingGroup']});
``` 
You can add this tag yourself and be able to get around ECS adding it themselves. However, I'm not 100% sure if this wouldn't break the service... Doesn't seem to in my case.

However, you are forced to supply a value for the tag. using escape hatches to remove the value field from the tag altogether results in error on deployment. Supplying an empty string for the value field will cause the value field to be removed from the template altogether and will result in drift.

Unless we add a tag to the resource ourselves in CDK code when necessary and supply a dummy value, I think we are blocked from implementing this. If having an actual value for this tag doesn't break the functionality, then I think this would be acceptable to fix

**Comment by rgoltz** [comment]
Hi @peterwoodworth - Thanks a lot for taking a look into this issue. 🥇 

To set the explicit tag-key `AmazonECSManaged` to some dummy tag-value within our CDK, it's something we can do "locally" for now. Since CDK already "understand" that we is an ECS-related-ASG/LaunchConfig, I have the feeling that we should check on other options: CDK currently seems to trigger a implizit API call to set the tag `AmazonECSManaged`. Since CFN template for his kind of service is able to set a tag, we (in terms of CDK) should think about to add this tag via "CFN-way" (hence in the template generated by CDK = hence, there is no drift afterwards) and drop the API-call outside of CFN.

I fully understood that you flag this issue for p2. As a TypeScript beginner, it's seems (for now) quite tough to provide this fix straight away for this pattern change.

**Comment by peterwoodworth** [comment]
I can't find any evidence that CDK is causing the tag to get added. The only way CDK would be able to do this is through the template, or if we were using a custom resource (which we aren't in this case)

This is an inherent issue in how CloudFormation and ECS work together to add this tag on deployment of the resource without preventing drift. I believe the best CDK can do here is to use the workaround by providing a value to the tag (again, if that actually ends up not messing the service up. Let me know if you try it!)

**Comment by rgoltz** [comment]
Hi @peterwoodworth - It's Robert here. Just to sync up on some steps done on our side: We enabled the workaround on CDK level to add this tag explicitly in our code. As far we can see, the ECS Capacity Provider/ASG is still working. Drift-Detection is fine now as expected (since tag is now part of the CFN template generated by CDK).

I did my best to bring the involved AWS ServiceTeams together (hence, ECS, CFN, CDK). I hope (following the conversation with Israel, James and Jenade) that the internal discussion is ongoing, what is the next best option here. Feel free to correct, if I'm wrong. In the meantime, I'm going to add some further clarification catched from different cases from different teams:

> When using ECS Capacity Providers, the "AmazonECSManaged" tag is added to manage the scaling of your Auto Scaling group. This tag is added when creating the capacity provider by the IAM user or role who initiated the Capacity Provider creation (in this case, the IAM role used by the CFN stack):
> https://docs.aws.amazon.com/AmazonECS/latest/developerguide/cluster-auto-scaling.html#cluster-auto-scaling-considerations
> 
>     When using capacity providers with Auto Scaling groups, the IAM user who creates the capacity providers, needs the autoscaling:CreateOrUpdateTags permission because Amazon ECS adds a tag to the Auto Scaling group when it associates it with the capacity provider.
> 
> This tag being added is thus expected from the ECS side. Currently issue with CDK/CFN has been acknowledged and is being investigated by the CloudFormation team. 

We going to wait for further updates here in the issue (and maybe we can remove our workaround soon). Cheers!

**Comment by peterwoodworth** [comment]
Thanks @abenetad, much appreciated 🙂
