### ISSUE TITLE
pipelines: Allow specifying custom action role for S3SourceOptions

### ISSUE THREAD

**Issue by lewtds** [aws/aws-cdk#20556]
### Describe the feature

[`CodePipelineSource.s3()`](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_pipelines.CodePipelineSource.html#static-s3bucket-objectkey-props) currently doesn't allow any method to inject a custom role or modifying the auto-generated action role.

### Use Case

This is needed, for example, to allow the source action to use KMS to decrypt the bucket.

### Proposed Solution

Add an `eventRole?: iam.IRole` field to `S3SourceOptions` then pass it through to `S3SourceAction`.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.26.0

### Environment details (OS name and version, etc.)

macOS 11.3.1

**Comment by rix0rrr** [comment]
Sounds good. I would call the properly `role`.
