### ISSUE TITLE
aws-ecr-assets: docker image build with no-cache option

### ISSUE THREAD

**Issue by cloneluke** [aws/aws-cdk#20555]
### Describe the feature

We use DockerImageAsset to build an ECR image via aws cdk. I would like to force a build using --no-cache, (we have side scripts that change so we do want the docker build to start completely fresh)
It doesn't look like there is a way to do this so I was thinking of opening a github feature request
https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ecr_assets.DockerImageAsset.html

docker build --no-cache option: https://docs.docker.com/engine/reference/commandline/build/

### Use Case

Able to force a full rebuild due to changes not detected by docker.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.22.0

### Environment details (OS name and version, etc.)

windows client, debian container

**Comment by indrora** [comment]
You can manually specify additional flags to `docker build` using the `buildArgs` property.

**Comment by indrora** [comment]
I take that back: buildArgs are not passed directly to Docker build, upon closer inspection.

**Comment by seruminar** [comment]
`buildArgs` produces 
- `docker build --build-arg --no-cache=` 
and we want 
- `docker build --no-cache`

**Comment by austinmw** [comment]
Any update on this?
