### ISSUE TITLE
(aws-events): Attaching >10 targets to a Rule causes resource limit exceeded error

### ISSUE THREAD

**Issue by greg5123334** [aws/aws-cdk#20567]
### Describe the bug

When attaching more than 10 [Targets](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_events_targets-readme.html#log-an-event-into-a-loggroup) to a Rule results in stack deployment failing with "resource limit exceed error".

### Expected Behavior

Attaching more than 10 targets to a Rule should be deployeable.

### Current Behavior

Deployment of Rule with more than 10 [Targets](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_events_targets-readme.html#log-an-event-into-a-loggroup) attached results in...

> Received response status [FAILED] from custom resource. Message returned: Resource limit exceeded.

on each of the [Custom::CloudwatchLogResourcePolicy](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-events-targets/lib/log-group-resource-policy.ts#L35) resources.

---

```
CREATE_FAILED        | Custom::CloudwatchLogResourcePolicy | EventsLogGroupPolicyLabStackeventrule11D9DFaaaE9/Resource/Default (EventsLogGroupPolicyLabStackeventr
ule11D9DF5aaaaA7157) Received response status [FAILED] from custom resource. Message returned: Resource limit exceeded.
```

### Reproduction Steps

The following snippet and corresponding test values can be used to replicate this behavior.

**Test dataset:**
max =
5: Works
6: Works
7: Works
8: Works
9: Works
10: Works
**11: FAILS !!**
5: Works

```
        const CaptainsLogGroup = new LogGroup(this, `logs`);
        const LogGroupTarget = new CloudWatchLogGroup(CaptainsLogGroup);


        let max = ??????????;
        for (let i = 1; i <= max; i++) {
            let dynamicName = String(i)

            const rule = new Rule(this, `event-rule-${dynamicName}`, {
                ruleName: `event-rule-${dynamicName}`,
            });

            rule.addEventPattern({
                "source": ["aws.glue"],
                "detail": {
                    "state": ["FAILED"],
                    "jobName": [`GlueJob`]
                }
            });

            rule.addTarget(LogGroupTarget);
        }
```

### Possible Solution

As this is a hard-limit, perhaps explicitly handle and throw this as an exception case. Or even better, refactor the custom construct to automatically apply any possible workarounds to this hard-limit 

### Additional Information/Context

Relevant limit:

> Resource policies | Up to 10 CloudWatch Logs resource policies per Region per account. This quota can't be changed.

[CloudWatch Logs quotas](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/cloudwatch_limits_cwl.html)

### CDK CLI Version

2.26.0 (build a409d63)

### Node.js Version

v16.15.0

### OS

Windows 10

### Language

Typescript

### Language Version

TypeScript

### Other information

Code responsible for creating *Custom::CloudwatchLogResourcePolicy*
https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-events-targets/lib/log-group-resource-policy.ts#L35

its Caller...
https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-events-targets/lib/log-group.ts#L39

**Comment by greg5123334** [comment]
because it seems that i cannot read :/

i have overlooked this particular detail, but now i know! thanks for pointing this out @rix0rrr ...nevermind.

**Comment by greg5123334** [comment]
hey @rix0rrr , pardon the resurrection, it seems i had misunderstood previously.

looking at the code again, we are only adding **one** target to a rule...one target per rule, yet it seems that CDK is creating the additional resource policies itself, hitting the aforementioned hard-limit.

please do correct me if i am wrong, and feel free to reach me directly if you like to discuss it further..

**Comment by peterwoodworth** [comment]
I'm not sure what we can do here. There's no way to work around this given the hard limit set by the service. Additionally, the "Resource limit exceeded" error thrown by our custom resource named `CloudwatchLogResourcePolicy` is pretty clear about what the issue is imo.

**Comment by greg5123334** [comment]
agreed. thanks for checking again Peter.
