### ISSUE TITLE
[codedeploy] Add ECSApplication types

### ISSUE THREAD

**Issue by allisaurus** [aws/aws-cdk#2056]
Currently, [server](https://github.com/awslabs/aws-cdk/tree/master/packages/%40aws-cdk/aws-codedeploy/lib/server) and [lambda](https://github.com/awslabs/aws-cdk/tree/master/packages/%40aws-cdk/aws-codedeploy/lib/lambda) application constructs are available, however ECS is also a supported application type. Adding this construct (and it's child constructs) will facilitate setup of deployment actions to ECS, including Blue/Green deployments (#1559).

**Comment by skinny85** [comment]
Unfortunately, this is not modeled in CloudFormation yet :(

**Comment by mmoulton** [comment]
@skinny85 can you clarify what is not yet supported by CF? Is it that `AWS::CodeDeploy::Application` does not yet accept a `computePlatform` of `ECS` despite the docs alluding to it?

Also, do you know if this is the responsibility of the containers team or the CF team to implement the missing support?

**Comment by steven-cuthill-otm** [comment]
this has been talked about for months now ... trying to get the ECS / CF team to implement this is proving to be taxing.

**Comment by skinny85** [comment]
@mmoulton yes, it's present in the API for CodeDeploy, and that's where the documentation points to, but still not in CloudFormation unfortunately.

**Comment by sarojgharat** [comment]
Yes. Need the cloudformation support. Waiting since a long time

**Comment by mmoulton** [comment]
Thanks all. @skinny85 do you happen to know if it's the codedeploy team, the containers team, or the larger CF team that needs to do the implementation? Since the containers team has already integrated with codedeploy, it makes me think that the CodeDeploy CF resources are where the work is still left to be done, but I'm not sure. It would be helpful to know when I'm asking my reps.

**Comment by ChrisLahaye** [comment]
How do you guys tackle deployments to ECS? Creating the pipeline and codedeploy project manually?

**Comment by skinny85** [comment]
We use the [ECS deploy Action](https://github.com/awslabs/aws-cdk/tree/master/packages/%40aws-cdk/aws-codepipeline-actions#ecs) that does rolling (instead of blue-green) deployments.

**Comment by ChrisLahaye** [comment]
> We use the [ECS deploy Action](https://github.com/awslabs/aws-cdk/tree/master/packages/%40aws-cdk/aws-codepipeline-actions#ecs) that does rolling (instead of blue-green) deployments.

How do you use it? Seems like that action isn't part of the 0.28 release on npmjs

**Comment by skinny85** [comment]
Ah yes, my apologies. It's still very fresh. It will be present in our next release, `0.29.0`.

**Comment by skinny85** [comment]
Here's the ticket tracking this functionality in the newly open-sourced CloudFormation public roadmap: https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/37

Feel free to pile on with +1 in that issue to get it prioritized!

**Comment by strax** [comment]
Even if blue/green deployments might not be supported via CloudFormation, it seems to be possible to define an `AWS::CodeDeploy::Application` resource with ECS as the compute platform: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codedeploy-application.html#aws-resource-codedeploy-application-properties; it also worked when I created one through CF.

**Comment by gbooth27** [comment]
any news on this?

**Comment by clareliguori** [comment]
EcsApplication construct is done:
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-codedeploy.EcsApplication.html

There is also an EcsDeploymentGroup class, but it is only for importing an existing CodeDeploy deployment group created outside of CloudFormation:
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-codedeploy.EcsDeploymentGroup.html

And there is a CodePipeline action for ECS-CodeDeploy deployments:
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-codepipeline-actions.CodeDeployEcsDeployAction.html

**Comment by jewelsjacobs** [comment]
Looks like CF just added support for a CODE_DEPLOY AWS::ECS::Service DeploymentController Type:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-service-deploymentcontroller.html

**Comment by tbrand** [comment]
Any updates for this?

**Comment by skinny85** [comment]
Yes, this was done in #4600.
