### ISSUE TITLE
(iam): Document the new @aws-cdk/aws-iam:minimizePolicies feature flag

### ISSUE THREAD

**Issue by alexpulver** [aws/aws-cdk#20573]
### Describe the issue

AWS CDK 2.26.0 includes the following pull request: [fix(iam): Role policies cannot grow beyond 10k](https://github.com/aws/aws-cdk/pull/20400). It introduces a new `@aws-cdk/aws-iam:minimizePolicies` feature flag. Currently, CDK v2 [Feature flags](https://docs.aws.amazon.com/cdk/v2/guide/featureflags.html) documentation doesn't include it. Neither does the [aws-cdk-lib.aws_iam](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_iam-readme.html) module API reference. I think the latter is important for the discoverability of this capability.

### Links

https://docs.aws.amazon.com/cdk/v2/guide/featureflags.html
https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_iam-readme.html

**Comment by peterwoodworth** [comment]
We should update the dev guide as well, not just the API reference. Thanks for calling this out!
