### ISSUE TITLE
(Construct): (Removing reference in another stack, is causing removal in original stack)

### ISSUE THREAD

**Issue by CliveBennett** [aws/aws-cdk#20579]
### Describe the bug

I have a StringParameter in a Stack

```
RuleCreation = new StringParameter(this, "param-rule-creation", new StringParameterProps()
            {
                ParameterName = $"{DeploymentPrefix}-rulecreation",
                Description = "Rule Creation Enabled",
                StringValue = ruleCreation
            });
```

This is being used in another Construct  in a NetworkLoadBalancedTaskImageOptions()          
            like this
```
 Secrets = new Dictionary<string, Secret> {
                        { "Logging:LogLevel:Default" ,Secret.FromSsmParameter(props.BaseResources.LogLevel) },
                        { "RuleCreation", Amazon.CDK.AWS.ECS.Secret.FromSsmParameter(props.BaseResources.RuleCreation) },
```

After it has been deployed, if I REMOVE the "RuleCreation" String Parameter from the "Secrets" dictionary and do a 
Cdk diff

It shows as it being removed from the Stack, even though it is still in the Stack.
and hence I can not cdk deploy the change to remove, as the deploy of the Stack complains that I can not remove "RuleCreation" as it is used in the Construct.

### Expected Behavior

I should be able to remove the "Secret" from the Construct, and it should remain in the Stack

### Current Behavior

cdk diff/deploy attempts to remove the StringParameter from the Stack, when it should leave it

It should only have removed the reference in the Construct

### Reproduction Steps

```RuleCreation = new StringParameter(this, "param-rule-creation", new StringParameterProps()
            {
                ParameterName = $"{DeploymentPrefix}-rulecreation",
                Description = "Rule Creation Enabled",
                StringValue = ruleCreation
            });
```

### CDK CLI Version

cdk 2.2.26

### Framework Version

core 3.1

### Node.js Version

16.15.0

### OS

Windows

### Language

.NET

### Language Version

.net 3.1

**Comment by gshpychka** [comment]
`cdk diff` is probably showing the _import_ being removed in the consumer, and the _export_ being removed in the producer.

Since the producer is deployed before the consumer and it tried to remove the export, the deploy fails because an export cannot be updated or removed if it's in use by other stacks.

The solution is to break the change up into two steps:
1. Remove the reference in the consumer stack. Add a `cdk.Stack.of(self).export_value(ruleCreation.parameter_arn)` in the producer stack to preserve the output even though the consumer doesn't need it anymore. This is in Python, you can find the correct syntax in your language. Deploy.
2. Remove the `export_value` call and deploy again. This time, the export can be removed because the import has been deleted.

All in all, this is not a bug.

**Comment by peterwoodworth** [comment]
Thanks for the response @gshpychka. I'm not sure if this is exactly what is happening in @CliveBennett's issue - but it sounds plausible.

I'm a bit confused here myself - based on my understanding, you have: a `StringParameter` in **Stack A**, and you are referencing this parameter in another stack with `Secret.FromSsmParameter` and passing that into a `NetworkLoadBalancedService` in **Stack B**.

Based on my understanding here are you reporting that deleting the reference in **Stack B** is causing the removal of the actual `StringParameter` in **Stack A**?

**Comment by CliveBennett** [comment]
Hi, yes that's right, if I do a

cdk diff  there are no changes reported.

if I purely remove from StackB (ie remove Secret.FromSsmParameter)
and do a cdk diff

It shows it will be removed from STACK A
and if I do a cdk deploy
It complains I cant remove this from Stack A as its used by Stack B

**Comment by peterwoodworth** [comment]
That's interesting, I'm not seeing the same thing happen to me. When I do this, I'm only seeing a difference in Stack B - however I'm using TypeScript. This doesn't seem like a JSII issue though, I'm completely stumped as to how you could be seeing this behavior

**Comment by gshpychka** [comment]
Van you post the result of cdk diff? I still believe my comment is correct and you're confusing the output with the actual resource.

**Comment by CliveBennett** [comment]
'''cdk diff prod-api
Including dependency stacks: prod-base-resources
Stack prod-base-resources
There were no differences
Stack prod-api
There were no differences'''

Then removing commenting out the param from prod-api stack

'''
cdk diff prod-api
Including dependency stacks: prod-base-resources
Stack prod-base-resources
Outputs
[-] Output ExportsOutputRefparamrulecreationDE08749D810057F8: {"Value":{"Ref":"paramrulecreationDE08749D"},"Export":{"Name":"prod-base-resources:ExportsOutputRefparamrulecreationDE08749D810057F8"}}

Stack prod-api
IAM Statement Changes
┌───┬────────────────────────────────────────────────────────────────────────┬────────┬─────────────────────────────────────────────────────────────────────────┬──────────────────────────┬───────────┐
│   │ Resource                                                               │ Effect │ Action                                                                  │ Principal                │ Condition │
├───┼────────────────────────────────────────────────────────────────────────┼────────┼─────────────────────────────────────────────────────────────────────────┼──────────────────────────┼───────────┤
│ - │ arn:${AWS::Partition}:ssm:ap-southeast-2:xxx:parameter/{"Fn:: │ Allow  │ ssm:DescribeParameters                                                  │ AWS:${api/api-task-role} │           │
│   │ ImportValue":"prod-base-resources:ExportsOutputRefparamrulecreationDE0 │        │ ssm:GetParameter                                                        │                          │           │
│   │ 8749D810057F8"}                                                        │        │ ssm:GetParameterHistory                                                 │                          │           │
│   │                                                                        │        │ ssm:GetParameters                                                       │                          │           │
└───┴────────────────────────────────────────────────────────────────────────┴────────┴─────────────────────────────────────────────────────────────────────────┴──────────────────────────┴───────────┘
(NOTE: There may be security-related changes not in this list. See https://github.com/aws/aws-cdk/issues/1299)

Resources
[~] AWS::IAM::Policy api/api-task-role/DefaultPolicy apiapitaskroleDefaultPolicy17525DE4
 └─ [~] PolicyDocument
     └─ [~] .Statement:
         └─ @@ -214,30 +214,6 @@
            [ ]         },
            [ ]         ":ssm:ap-southeast-2:xxx:parameter/",
            [ ]         {
            [-]           "Fn::ImportValue": "prod-base-resources:ExportsOutputRefparamrulecreationDE08749D810057F8"
            [-]         }
            [-]       ]
            [-]     ]
            [-]   }
            [-] },
            [-] {
            [-]   "Action": [
            [-]     "ssm:DescribeParameters",
            [-]     "ssm:GetParameters",
            [-]     "ssm:GetParameter",
            [-]     "ssm:GetParameterHistory"
            [-]   ],
            [-]   "Effect": "Allow",
            [-]   "Resource": {
            [-]     "Fn::Join": [
            [-]       "",
            [-]       [
            [-]         "arn:",
            [-]         {
            [-]           "Ref": "AWS::Partition"
            [-]         },
            [-]         ":ssm:ap-southeast-2:xxx:parameter/",
            [-]         {
            [ ]           "Fn::ImportValue": "prod-base-resources:ExportsOutputRefparamunderwritingapi04F77F920B98CF39"
            [ ]         }
            [ ]       ]
[~] AWS::ECS::TaskDefinition api/api-service/TaskDef apiapiserviceTaskDefC5BE0E23 replace
 └─ [~] ContainerDefinitions (requires replacement)
     └─ @@ -170,24 +170,6 @@
        [ ]   }
        [ ] },
        [ ] {
        [-]   "Name": "RuleCreation",
        [-]   "ValueFrom": {
        [-]     "Fn::Join": [
        [-]       "",
        [-]       [
        [-]         "arn:",
        [-]         {
        [-]           "Ref": "AWS::Partition"
        [-]         },
        [-]         ":ssm:ap-southeast-2:xxx:parameter/",
        [-]         {
        [-]           "Fn::ImportValue": "prod-base-resources:ExportsOutputRefparamrulecreationDE08749D810057F8"
        [-]         }
        [-]       ]
        [-]     ]
        [-]   }
        [-] },
        [-] {
        [ ]   "Name": "UnderwritingApiUrl",
        [ ]   "ValueFrom": {
        [ ]     "Fn::Join": [

'''

**Comment by CliveBennett** [comment]
Thanks, sorry I don't fully understand, I see this in the first prod-base-resources stack at the top of the CDK Diff

'''Outputs
[-] Output ExportsOutputRefparamrulecreationDE08749D810057F8: {"Value":{"Ref":"paramrulecreationDE08749D"},"Export":{"Name":"prod-base-resources:ExportsOutputRefparamrulecreationDE08749D810057F8"}}
'''

Which to me indicates its trying to remove the Parameter from the Stack ? is that not the case?

**Comment by peterwoodworth** [comment]
When you create a new `StringParameter`, you're using CloudFormation's [AWS::SSM::Parameter](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ssm-parameter.html). This resource should still be in your template

The output that is getting removed is the export that @gshpychka mentioned in his first comment. his steps to resolution should help you out here 🙂

**Comment by gshpychka** [comment]
> Which to me indicates its trying to remove the Parameter from the Stack ? is that not the case?

No, as you can see, it's an `Output`. As mentioned above, you're confusing the output with the actual parameter resource..

**Comment by CliveBennett** [comment]
All good, ill see if I can follow your tip above, otherwise ill just drop the stacks and recreate, as I cant just remove the reference as it complains. There's something subtle going  on that I just don't understand :(

Thanks for the help.

**Comment by indrora** [comment]
If this was resolved, that's great; otherwise, a simple response saying this is still an issue outside of destroy/redeploy. 

This does unfortunately look like one of those situations where that is a better choice. @rix0rrr or @cgarvis what do you think?

**Comment by CliveBennett** [comment]
Hi, for me the only solution was to destroy/deploy, I never ended up being clear if it was supposed to work like this, or what the issue was, to me it still feels like an issue.

**Comment by peterwoodworth** [comment]
Were you able to reproduce this @indrora? i didn't find that anything out of the ordinary was happening, and that @gshpychka was spot on.
