### ISSUE TITLE
aws-cdk-lib: Names.uniqueId should take IConstruct instead of Construct as parameter

### ISSUE THREAD

**Issue by schabe77** [aws/aws-cdk#20584]
### Describe the feature

Names.uniqueId only accepts Constructs. The method internally only works with Construct's nodes which can also be determined for IConstructs (Node.of). So it should be o.k. to pass an IConstruct.

### Use Case

I use the Java-CDK and want to create a uniqueId of an  IOpenIdConnectProvider, which is an IConstruct but no Construct.
In Java it's impossible to do compile that, in TypeScript it works without problems.

### Proposed Solution

change the parameter type from Construct to IConstruct

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.26.0

### Environment details (OS name and version, etc.)

Windows / Linux

**Comment by peterwoodworth** [comment]
I don't see why this wouldn't work - thanks for the feature request! Check out our [contributing guide](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) if you're interested - there's a low chance the team will be able to address this soon but we'd be happy to review a PR 🙂
