### ISSUE TITLE
(aws-ec2): Support Textract VPC Endpoint Service

### ISSUE THREAD

**Issue by J11522** [aws/aws-cdk#20586]
### Describe the feature

Currently the `InterfaceVpcEndpointAwsService` doesn't support Textract.
It should support creating an endpoint service for both textract and textract-fips, similar to rekognition.

### Use Case

We want to use a vpc endpoint service for textract, currently we have to manually create this.

### Proposed Solution

Add 
```
  public static readonly TEXTRACT = new InterfaceVpcEndpointAwsService('textract');
  public static readonly TEXTRACT_FIPS = new InterfaceVpcEndpointAwsService('textract-fips');
```
to https://github.com/aws/aws-cdk/blob/main/packages/@aws-cdk/aws-ec2/lib/vpc-endpoint.ts

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.26.0

### Environment details (OS name and version, etc.)

Mac

**Comment by corymhall** [comment]
@J11522 we would definitely welcome a PR if you are willing. It looks like a simple addition.

I am unassigning and marking this issue as `p2`, which means that we are unable to work on this immediately.

We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://join.slack.com/t/cdk-dev/shared_invite/zt-19nwray07-px8F1A_Ubf5~TsKHUgbL1w) to solicit support for reprioritization.

**Comment by daschaa** [comment]
Can this issue be closed? :)
