### ISSUE TITLE
(modupdated my CDK version from 1.149.0 --> 2.0.0 now build is failingule name): (short issue description)

### ISSUE THREAD

**Issue by shadhav** [aws/aws-cdk#20620]
### Describe the issue

Hi Team,
I'm having an issue with CDK that I'm not sure how to resolve.
I updated my CDK version from 1.149.0 --> 2.0.0
The I deployed and for some of my stacks the CDKMetadata changed so the deployment failed.
I don't know how can I resolve this without having to delete my stacks
I know read here: https://docs.aws.amazon.com/cdk/v2/guide/migrating-v2.html
That it could happen if you were using a version below 1.85 which is my case but it does not say how to solve it if you already deployed with the 2.0.0

### Links

https://docs.aws.amazon.com/cdk/v2/guide/migrating-v2.html

**Comment by peterwoodworth** [comment]
What exact error did you run into @shadhav ?
