### ISSUE TITLE
(assertions): Jest v28 breaks tests

### ISSUE THREAD

**Issue by krdev** [aws/aws-cdk#20622]
### Describe the bug

When using apigatewayv2_alpha.HttpAuthorizer and running tests I get the following error:

Cannot find module 'aws-cdk-lib/.warnings.jsii.js' from 'node_modules/@aws-cdk/aws-apigatewayv2-authorizers-alpha/.warnings.jsii.js'

I'm new to typescript/JS - setting NODE_PATH does not help either. I see that you have require("aws-cdk-lib/.warnings.jsii.js") to  access a file (not module), if i change that to require("../../aws-cdk-lib/.warnings.jsii.js") everything works.

I used jest to run tests as so:
npm test

### Expected Behavior

Should not throw the "cannot find module" error.

### Current Behavior

Cannot find module 'aws-cdk-lib/.warnings.jsii.js' from 'node_modules/@aws-cdk/aws-apigatewayv2-authorizers-alpha/.warnings.jsii.js'

### Reproduction Steps

APP_CONFIG=config/config.json npm test test/test-stack.test.ts

### Possible Solution

        const adminUserPool = new cognito.UserPool(this, 'admin-user-pool', {
            userPoolName: stackConfig.AdminUserPoolDomainPrefix,
            removalPolicy: cdk.RemovalPolicy.DESTROY,
        })

        const adminAuthorizer = new apiGatewayAuthorizers.HttpUserPoolAuthorizer('admin-authorizer-id-2',
            adminUserPool, {
                identitySource: ['$request.header.Authorization']
        })

### Additional Information/Context

When running any test to test the above code, I get the following error:

---
    Cannot find module 'aws-cdk-lib/.warnings.jsii.js' from 'node_modules/@aws-cdk/aws-apigatewayv2-authorizers-alpha/.warnings.jsii.js'

      20 |         })
      21 |
    > 22 |         const adminAuthorizer = new apiGatewayAuthorizers.HttpUserPoolAuthorizer('admin-authorizer-id-2',
         |                                 ^
      23 |             adminUserPool, {
      24 |                 identitySource: ['$request.header.Authorization']
      25 |         })

      at Resolver._throwModNotFoundError (node_modules/jest-resolve/build/resolver.js:491:11)
      at Object._aws_cdk_aws_apigatewayv2_authorizers_alpha_HttpUserPoolAuthorizerProps (node_modules/@aws-cdk/aws-apigatewayv2-authorizers-alpha/.warnings.jsii.js:7:13)
      at new HttpUserPoolAuthorizer (node_modules/@aws-cdk/aws-apigatewayv2-authorizers-alpha/lib/http/user-pool.js:25:37)
      at new TestStack (infra/apigw/test-stack.ts:22:33)
---

### CDK CLI Version

2.23.0 (build 50444aa)

### Node.js Version

8.11.0

### OS

Mac ProductName:	macOS ProductVersion:	12.4 BuildVersion:	21F79

### Language

Typescript

**Comment by relm923** [comment]
Seeing this specifically with various alpha packages and Jest 28

**Comment by wilhen01** [comment]
I'm also seeing this error with Jest 28 and `@aws-cdk/aws-synthetics-alpha` (`2.30.0-alpha.0`).

Downgrading to jest 27 appears to have resolved the issue. Would be nice to have this fixed though.

**Comment by jplauri** [comment]
> I'm also seeing this error with Jest 28 and `@aws-cdk/aws-synthetics-alpha` (`2.30.0-alpha.0`).
> 
> Downgrading to jest 27 appears to have resolved the issue. Would be nice to have this fixed though.

Facing the same issue with `@aws-cdk/aws-lambda-python-alpha` (2.31.0-alpha.0).

**Comment by peterwoodworth** [comment]
This is because we cannot use Jest 28 - as it depends on a version of TypeScript that we cannot support due to JSII.

Pinning jest version to 27 should work here - we won't be able to guarantee that anything above version 27 works

This should be called out in our docs

**Comment by bitfrost** [comment]
> This is because we cannot use Jest 28 - as it depends on a version of TypeScript that we cannot support due to JSII.
> 
> Pinning jest version to 27 should work here - we won't be able to guarantee that anything above version 27 works
> 
> This should be called out in our docs

Are we saying the CDK won't be supporting typescript past a certain version?

**Comment by joshlartz** [comment]
This doesn't appear to (directly) have anything to do with Typescript. Are you referring to how you compile the packages?

Here's a broken example with pure JS.

package.json
```
"dependencies": {
    "@aws-cdk/aws-apigatewayv2-alpha": "2.40.0-alpha.0",
    "@aws-cdk/aws-apigatewayv2-integrations-alpha": "2.40.0-alpha.0",
    "aws-cdk-lib": "^2.40.0",
    "constructs": "^10.1.95"
},
"devDependencies": {
    "jest": "^28"
}
```

test.js
```
const api = require('@aws-cdk/aws-apigatewayv2-alpha');
const cdk = require('aws-cdk-lib');
const ec2 = require('aws-cdk-lib/aws-ec2');
const elbv2 = require('aws-cdk-lib/aws-elasticloadbalancingv2');
const int = require('@aws-cdk/aws-apigatewayv2-integrations-alpha');

test('should pass', () => {
  // setup
  const stack = new cdk.Stack(undefined, 'Stack');
  const vpc = new ec2.Vpc(stack, 'Vpc');
  const alb = new elbv2.ApplicationLoadBalancer(stack, 'Alb', { vpc });
  const albListener = alb.addListener('Listener', { port: 80 });
  const vpcLink = new api.VpcLink(stack, 'VpcLink', { vpc });

  // should succeed
  new api.HttpApi(stack, 'Api', {
    defaultIntegration: new int.HttpAlbIntegration('DefaultIntegration', albListener, { vpcLink }),
  });
});
```

Error
```
Cannot find module 'aws-cdk-lib/.warnings.jsii.js' from 'node_modules/.pnpm/@aws-cdk+aws-apigatewayv2-alpha@2.40.0-alpha.0_fj352lrcfmlfnj3qklqlxd47kq/node_modules/@aws-cdk/aws-apigatewayv2-alpha/.warnings.jsii.js'
```

**Comment by joshlartz** [comment]
This looks to be the root cause https://github.com/lukeed/resolve.exports/issues/19

**Comment by niebloomj** [comment]
I'm using jest 28 in my packages without any issues...

**Comment by ErikMikkelson** [comment]
Adding this to our jest.config.json worked for us:

`json
    "moduleNameMapper": {
        "^aws-cdk-lib/.warnings.jsii.js$": "<rootDir>/node_modules/aws-cdk-lib/.warnings.jsii.js"
    },
`

**Comment by vumdao** [comment]
If you use [projen](https://github.com/projen/projen) and want to use the above workaround, add following to `.projenrc.ts` 
```
  jestOptions: {
    jestConfig: {
      moduleNameMapper: {
        ['^aws-cdk-lib/.warnings.jsii.js$']: '<rootDir>/node_modules/aws-cdk-lib/.warnings.jsii.js',
      },
    },
  },
```

**Comment by vaughngit** [comment]
> If you use [projen](https://github.com/projen/projen) and want to use the above workaround, add following to `.projenrc.ts`
> 
> ```
>   jestOptions: {
>     jestConfig: {
>       moduleNameMapper: {
>         ['^aws-cdk-lib/.warnings.jsii.js$']: '<rootDir>/node_modules/aws-cdk-lib/.warnings.jsii.js',
>       },
>     },
>   },
> ```

you be my boy blue!!!!

**Comment by TheRealAmazonKendra** [comment]
This issue is now resolved since upgrading typescript and jsii.
