### ISSUE TITLE
ec2: Insufficient validation of service endpoint name

### ISSUE THREAD

**Issue by Alexander-D-Jensen** [aws/aws-cdk#20644]
### Describe the bug

When creating InterfaceVpcEndpoint for a service, the InterfaceVpcEndpoint doesn't (sufficiently, at least) validate the given name. CDK and Cfn doesn't protest this particular wrong name, and only during deploy an error is received from EC2 on trying to create the network resource.

### Expected Behavior

I had hoped that cdk synth or cdk diff would have caught the wrong name and rejected before trying to deploy.

### Current Behavior

All went through until the deploy, where the error then surfaced, causing a rollback.

### Reproduction Steps

``` python
from constructs import Construct
from aws_cdk import App, Stack, aws_ec2 as ec2

class VPCStack(Stack):

    def __init__(self, scope: Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        self.network = ec2.Vpc(
            self,
            "network",
            cidr="10.1.0.0/16",
            subnet_configuration=[
                ec2.SubnetConfiguration(
                    subnet_type=ec2.SubnetType.PUBLIC, name="Public", cidr_mask=24
                ),
                ec2.SubnetConfiguration(
                    subnet_type=ec2.SubnetType.PRIVATE_WITH_NAT,
                    name="Private",
                    cidr_mask=24,
                ),
            ],
            nat_gateways=2,
        )

        for service in [
            {"endpoint": '".ecr.api"', "private_dns_enabled": True}, #Notice the double quotes encased in single quotes on endpoint
            {"endpoint": '".ecr.dkr"', "private_dns_enabled": True}, #Notice the double quotes encased in single quotes on endpoint
            {"endpoint": '".logs"', "private_dns_enabled": False}, #Notice the double quotes encased in single quotes on endpoint
        ]:
            ec2.InterfaceVpcEndpoint(
                self,
                f"VPC Endpoint - {service['endpoint']}",
                vpc=self.network,
                service=ec2.InterfaceVpcEndpointService(
                    f"com.amazonaws.eu-west-1{service['endpoint']}" # This is where the issue occurs, because the name isn't checked
                ),
                private_dns_enabled=service["private_dns_enabled"],
            )
app = App()
VPCStack(app, "Testing")
app.synth()

```

### Possible Solution

I see 2 immediate options:
Validate the name in CloudFormation/CDK, or:

Create enums for the various services that cna be used for endpoints, and use those to construct instead of a freeform string as input to ec2.InterfaceVpcEndpointService.

### CDK CLI Version

2.15.0

### Node.js Version

v14.16.1

### OS

Linux/KDE Neon (Kernel 5.13.0

### Language

Python

### Language Version

3.8.10

**Comment by indrora** [comment]
Definitely looks like we should do a quick validation on that. 

I'd usually label this "wontfix" but this is the kind of data validation error that is easy enough to catch: Going in should be a (backwards) FQDN.

**Comment by Alexander-D-Jensen** [comment]
Sorry to have missed that - this seems exactly what I was looking for. Thank you 👍🏻
