### ISSUE TITLE
aws-sns: return Subscription when calling ITopic.addSubscription 

### ISSUE THREAD

**Issue by jonnekaunisto** [aws/aws-cdk#20657]
### Describe the feature

return Subscription when calling ITopic.addSubscription 

### Use Case

I want to make the SQS policy deploy before the Subscription gets created so that SNS doesn't fail to deliver messages.

### Proposed Solution

Currently the subscription that is created is not returned: https://github.com/aws/aws-cdk/blob/v1.159.0/packages/%40aws-cdk/aws-sns/lib/topic-base.ts#L80

Adding a return would solve the problem.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2

### Environment details (OS name and version, etc.)

Mac OS

**Comment by peterwoodworth** [comment]
I don't see any reason we can't do this. Would you be willing to contribute this? Check out our [contributing guide](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) for more info 🙂
