### ISSUE TITLE
API Gateway: Lambda authorizer function with the AWS WebSockets API Gateway yields error in AWS console

### ISSUE THREAD

**Issue by tzvii** [aws/aws-cdk#20655]
### Describe the bug

We've created a Websocket API through AWS Gateway that connects to a Lambda function, but in order to authorize the connection/API-request we need to create a lambda authorizer that is hit before the Lambda function. For now, this is the only option that AWS gives to authorize requests via gateway websocket connection. 
The authorizer has all the necessary permissions. I tried to conduct a simple sanity test and log the event that was being passed in, but the lambda authorizer is being completely ignored. Aside from the Lambda authorizer, the websocket API and Lambda function work together without any issues. There only problem is reaching the lambda authorizer.
![Screen Shot 2022-06-07 at 1 07 34 PM](https://user-images.githubusercontent.com/89325152/172492312-adc0e207-2a6a-4d1e-b859-b435db8d2a53.png)

### Expected Behavior

For the basic test, I expected for the event to simply be logged, but the authorizer wasn't being hit.

### Current Behavior

The AWS console is reporting an error that doesn't make any sense since the authorizer is attached to the `$connect` route.
![Screen Shot 2022-06-07 at 1 13 58 PM](https://user-images.githubusercontent.com/89325152/172492701-53fa828d-f685-434f-97c1-0d68cd6bb91b.png)

### Reproduction Steps

Create a websocket API through gateway. Hookup the API to a lambda function. Create a separate lambda function (lambda authorizer) and use it as the lambda authorizer for the `$connect` route. Then, click on gateway trigger on the lambda authorizer page. You should then see the console error.

### CDK CLI Version

2.1116.0

### Node.js Version

16.0

### OS

Mac OS 11.6.4

### Language

Typescript

**Comment by peterwoodworth** [comment]
Can you share your code where you declare these resources? It's not clear here how this is related to CDK
