### ISSUE TITLE
Race condition between SQS QueuePolicy and SNS Subscription

### ISSUE THREAD

**Issue by jonnekaunisto** [aws/aws-cdk#20665]
### Describe the bug

For the [SqsSubscription](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-sns-subscriptions.SqsSubscription.html) currently the QueuePolicy can get deployed before or after the Subscription. If the queue policy deploys afterwards, it will cause failures to send messages from SNS to SQS.

### Expected Behavior

QueuePolicy will deploy before  Subscription.

### Current Behavior

QueuePolicy can sometimes deploy after Subscription.

### Reproduction Steps

Create a SqsSubscription and it will generate a template where there is no dependency between the Queue Policy and Subscription.

### Possible Solution

Not sure how, the code for this is complicated since the queue is passed into this: https://github.com/aws/aws-cdk/blob/v1.159.0/packages/@aws-cdk/aws-sns-subscriptions/lib/sqs.ts#L35

but the subscription is created here: https://github.com/aws/aws-cdk/blob/v1.159.0/packages/%40aws-cdk/aws-sns/lib/topic-base.ts#L80

### CDK CLI Version

3

### Node.js Version

16

### OS

Mac OS

### Language

Typescript

**Comment by peterwoodworth** [comment]
Thanks for reporting this @jonnekaunisto!

I'll try to look more into this later to see if I can confirm this is happening, and then would provide a fix if possible. But I or someone else on the team may not be able to get to this soon - in that case we accept [contributions](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md)!

**Comment by jonnekaunisto** [comment]
I would be happy to contribute. But I think there are 2 issues that need to be solved first.

1. How do we get access to the queue in the [addSubscription](https://github.com/aws/aws-cdk/blob/v1.159.0/packages/%40aws-cdk/aws-sns/lib/topic-base.ts#L80) function? The queue is accessible through the [subscriberScope](https://github.com/aws/aws-cdk/blob/v1.159.0/packages/@aws-cdk/aws-sns-subscriptions/lib/sqs.ts#L71), but is it ok to have dual meaning for that field?
2. How do we get access to the queue policy, since it is a [private field](https://github.com/aws/aws-cdk/blob/v1.159.0/packages/%40aws-cdk/aws-sqs/lib/queue-base.ts#L135)? Can we just make this public? You can already technically access this by calling [addToResourcePolicy](https://github.com/aws/aws-cdk/blob/v1.159.0/packages/%40aws-cdk/aws-sqs/lib/queue-base.ts#L151).

**Comment by jonnekaunisto** [comment]
Any thoughts on the above @peterwoodworth?
