### ISSUE TITLE
S3 Bucket: bucket not deleted although autoDeleteObjects is set to true

### ISSUE THREAD

**Issue by trks1970** [aws/aws-cdk#20660]
### Describe the bug

We have a KMS encrypted bucket as a destination for firehose, created with:
`.removalPolicy(RemovalPolicy.DESTROY) .autoDeleteObjects(true)`

We create four DirectPut deliveryStreams, each using the bucket.

### Expected Behavior

When the Kinesis Stack is deleted, the S3 Bucket should be deleted as well.

### Current Behavior

We get the following error in CloudFormation:

`The bucket you tried to delete is not empty (Service: Amazon S3; Status Code: 409; Error Code: BucketNotEmpty; Request ID: G414G0X7S6D79N2C; S3 Extended Request ID: /XuG6xxhpZdz+4UxBvWJYnlAMTbsGT0S9uKRGR0nVZDg/spFKcIiBCis3irsCqHcTZM6WIDJtsA=; Proxy: null)`

### Reproduction Steps

`
class KinesisStack(
    scope: Construct,
    config: StageConfig,
    props: StackProps
) : Stack(scope, Stacks.ABEO_KINESIS, props) {

    init {
        val bucketName = config.kinesis.bucketName.replace("ENV", config.name)

        val kmsKey = Key.Builder.create(this,"${this.stackName}-key")
            .removalPolicy(RemovalPolicy.DESTROY)
            .pendingWindow(Duration.days(7))
            .enableKeyRotation(false)
            .alias("${this.stackName}-key")
            .build()
        val traceBucket = Bucket.Builder.create(this, "${this.stackName}-bucket")
            .removalPolicy(RemovalPolicy.DESTROY)
            .autoDeleteObjects(true)
            .publicReadAccess(false)
            .bucketName(bucketName)
            .blockPublicAccess(BlockPublicAccess.BLOCK_ALL)
            .encryption(BucketEncryption.KMS)
            .encryptionKey(kmsKey)
            .versioned(false)
            .lifecycleRules(
                listOf(
                    LifecycleRule.builder()
                        .enabled(true)
                        .expiration(Duration.days(90))
                        .build()
                )
            )
            .build()
        val firehoseRole = Role.Builder.create(this, "firehoseRole")
            .assumedBy(ServicePrincipal("firehose.amazonaws.com"))
            .description("Firehose role")
            .build()
        traceBucket.grantWrite(firehoseRole)
        config.kinesis.traceStreams.forEach {
            createDeliveryStream(it,traceBucket,firehoseRole, kmsKey)
                .node
                .addDependency(firehoseRole)
        }
    }

    private fun createDeliveryStream(streamName:String, bucket: IBucket, firehoseRole: Role, kmsKey: IKey) =
        CfnDeliveryStream.Builder.create(this, streamName,)
            .deliveryStreamName(streamName)
            .deliveryStreamType("DirectPut")
            .deliveryStreamEncryptionConfigurationInput(
                CfnDeliveryStream.DeliveryStreamEncryptionConfigurationInputProperty.builder()
                    .keyType("CUSTOMER_MANAGED_CMK")
                    .keyArn(kmsKey.keyArn)
                    .build()
            )
            .s3DestinationConfiguration(S3DestinationConfigurationProperty.builder()
                .bucketArn(bucket.bucketArn)
                .roleArn(firehoseRole.roleArn)
                .prefix("trace/$streamName/")
                .compressionFormat("UNCOMPRESSED")
                .encryptionConfiguration(CfnDeliveryStream.EncryptionConfigurationProperty.builder()
                    .kmsEncryptionConfig(CfnDeliveryStream.KMSEncryptionConfigProperty.builder()
                        .awskmsKeyArn(kmsKey.keyArn)
                        .build())
                    .build())
                .bufferingHints(CfnDeliveryStream.BufferingHintsProperty.builder()
                    .sizeInMBs(128)
                    .intervalInSeconds(900)
                    .build())
                .build())
            .build()

}
`

### CDK CLI Version

2.27.0 (build 8e89048)

### Framework Version

software.amazon.awscdk:aws-cdk-lib:2.24.1

### Node.js Version

v16.15.1

### OS

Codepipeline/Win/MacOS

### Language

Java

### Language Version

11 (Kotlin)

**Comment by peterwoodworth** [comment]
I'm not able to reproduce this @trks1970,

We utilize a custom resource to handle this upon deletion. Do you have a lambda function in your stack which gets deleted first? It should have a description which starts with `Lambda function for auto-deleting objects`

**Comment by trks1970** [comment]
Yes, the lambda gets create and is also deleted before the bucket.
```
<html>
<body>
<!--StartFragment-->

2022-06-09 14:47:21 UTC+0200 | sandboxabeobackendkinesisbucket5E2A07E8 | DELETE_FAILED | The bucket you tried to delete is not empty (Service: Amazon S3; Status Code: 409; Error Code: BucketNotEmpty; Request ID: 06QYVVQ3J0SQTET3; S3 Extended Request ID: 9DKbc2P46EQT5E22av7UDERTg3uAEbIOf6RCctuFqj1oGduxn+fjPuHjeWB9qv4VihnOmEXDNVk=; Proxy: null)
-- | -- | -- | --
2022-06-09 14:47:21 UTC+0200 | firehoseRoleE5891AF8 | DELETE_IN_PROGRESS | -
2022-06-09 14:47:21 UTC+0200 | sandboxabeobackendkinesisbucket5E2A07E8 | DELETE_IN_PROGRESS | -
2022-06-09 14:47:20 UTC+0200 | firehoseRoleDefaultPolicy27F13165 | DELETE_COMPLETE | -
2022-06-09 14:47:19 UTC+0200 | firehoseRoleDefaultPolicy27F13165 | DELETE_IN_PROGRESS | -
2022-06-09 14:47:18 UTC+0200 | kdsweldlog | DELETE_COMPLETE | -
2022-06-09 14:47:17 UTC+0200 | alarm | DELETE_COMPLETE | -
2022-06-09 14:47:17 UTC+0200 | historian | DELETE_COMPLETE | -
2022-06-09 14:47:13 UTC+0200 | sandboxabeobackendkinesiskeyAlias2D5A91DD | DELETE_COMPLETE | -
2022-06-09 14:46:45 UTC+0200 | kdsparameterelektrode | DELETE_COMPLETE | -
2022-06-09 14:46:44 UTC+0200 | conveyorbelt | DELETE_COMPLETE | -
2022-06-09 14:46:31 UTC+0200 | CustomS3AutoDeleteObjectsCustomResourceProviderRole3B1BD092 | DELETE_COMPLETE | -
2022-06-09 14:46:29 UTC+0200 | CustomS3AutoDeleteObjectsCustomResourceProviderRole3B1BD092 | DELETE_IN_PROGRESS | -
2022-06-09 14:46:28 UTC+0200 | CustomS3AutoDeleteObjectsCustomResourceProviderHandler9D90184F | DELETE_COMPLETE

<!--EndFragment-->
</body>
</html>
```

CustomS3AutoDeleteObjectsCustomResourceProviderHandler9D90184F is the lambda.

**Comment by Naumel** [comment]
Hi, jumping into the conversation, could the following be happening in your scenario?

> If there are a large number of objects in the bucket, those objects might continue to appear in the Amazon S3 console for a few days. This condition applies especially to Amazon S3 buckets that have versioning enabled. If the bucket has versioning enabled, [delete markers](https://docs.aws.amazon.com/AmazonS3/latest/dev/DeleteMarker.html) are created after the current version of an object is deleted. After the delete markers are at least one day old, the lifecycle rules then also clean up the delete markers. It might take a few days for the delete markers to age past one day old and for the lifecycle rules to detect their age and remove them.

> After the objects are fully deleted (including delete markers), you can [delete the bucket](https://docs.aws.amazon.com/AmazonS3/latest/user-guide/delete-bucket.html).

**Comment by trks1970** [comment]
No, that is not the case. As you can see from the cdk scripts, versioning is not enabled, and there not a huge number of objects in the bucket.
But, what I have noticed is:
We are creating five streams in the bucket:
trace/alarm
trace/kdsweldlog
trace/kdsparameterelektrode
trace/historian
trace/conveyorbelt

As you can see above from the events, everything below "trace" is deleted, but the prefix "trace" is not deleted by the lambda, which is prorbaly causing the issue with bucket deletion.

**Comment by trks1970** [comment]
We found the issue.
It was the order, how we deleted stacks.
The stack writing to kinesis and kinesis itself were deleted in parallel, and this caused a race condition.
Although the lambda deleted the objects, but some were immediately recreated by the the writer stack,

Our fault.
I am closing the issue.
Thanks for your support
