### ISSUE TITLE
(iam): Statements seem to randomly change order with overflow policies

### ISSUE THREAD

**Issue by polothy** [aws/aws-cdk#20667]
### Describe the bug

I don't have a lot to go on here with root cause, but I have some very large policies on an IAM role.  I'm using the new feature where it splits the policies over multiple managed policies (overflow policies).

I'm seeing, rather randomly and somehow low frequency, that some IAM statements will swap positions from the default inline policy to the overflow policy.  I'm fairly certain that on my side, the policies are consistently ordered because I never had this problem before the overflow policies feature.

But, I also looked through the policy [splitting code](https://github.com/aws/aws-cdk/tree/main/packages/%40aws-cdk/aws-iam/lib/private) and cannot find anything that might be randomly sorted (lists seem to be used everywhere it counts).

I'm also using the `@aws-cdk/aws-iam:minimizePolicies` feature flag. Perhaps this does some sorting or re-arranging of statements?

The only thing that I've noticed is that the policies that switch have these for `Actions`:

- sns:*
- s3:*

Which makes me think it could be a sorting issue and the number is randomly throwing it off?  I don't actually see where statements are sorted by action names in the code though.  But I have also only see it happen with these statements (this project generates >150 stacks/pipelines so it's a lot of different policies being generated and I have only seen these specific statements swap on like 2 pipelines).

Sorry this is a crap bug report, because I'm not even sure how to reproduce the problem. Just trying to see if this rings any bells that could be investigated.

### Expected Behavior

Statements do not swap positions.

### Current Behavior

These specific two statements swap positions from the inline policy and the overflow policy.

### Reproduction Steps

I don't know right now, sorry.  Just trying to see if any more ideas come up.

### Possible Solution

Don't know enough yet.

### CDK CLI Version

2.26.0

### Framework Version

2.26.0

### Node.js Version

14

### OS

macOS

### Language

Python

### Language Version

3.9

**Comment by polothy** [comment]
Seems like I can reproduce with `@aws-cdk/aws-iam:minimizePolicies` on or off.

**Comment by polothy** [comment]
Minor nitpicky thing: in the [_estimateSize](https://github.com/aws/aws-cdk/blob/74b2abdbf36ba8a921593ce00b2c6ed5fc6f6335/packages/%40aws-cdk/aws-iam/lib/policy-statement.ts#L573) - if an Action, Resources, etc has a length of 1, it renders without brackets.  EG: `Action: "foo"` instead of `Action: ["foo"]`. Maybe doesn't matter and being more cautious about the estimate.

**Comment by polothy** [comment]
So, I turned off `@aws-cdk/aws-iam:minimizePolicies` and synthed my app to a custom output directory.  Then I synthed it 10 more times, each time comparing it to the first one. 8/10 were identical and 2 were different in the exact same way.

Head scratcher... 🤔

**Comment by peterwoodworth** [comment]
When you're running into this, are you changing your app at all between synthesis? Or are no changes required for this to vary

**Comment by polothy** [comment]
No changes, I'm running this:

```
repeat 10 { cdk synth && diff -U 100 --recursive baseline.cdk.out cdk.out }
```

And don't touch anything.

**Comment by polothy** [comment]
Spent the morning trying to reproduce in CDK tests.  I modified [this test](https://github.com/aws/aws-cdk/blob/c2e6d8956d1190fd9aa94ed8b952a5b10b352eb0/packages/%40aws-cdk/aws-iam/test/role.test.ts#L685) to save a snapshot. Then ran the test 20 times to see if the policy statements changed order.  They haven't so far.  Makes me think the problem is elsewhere - either my code, Python... not sure. I've been running diffs on before/after on just about every change to my project though and haven't seen this until recently.  That's why I was thinking it was something in CDK.

I'll see if I can think of anything else to reproduce/test.  Running low on ideas though hah.

**Comment by polothy** [comment]
I'm sort of sweeping this issue under the rug in my project.  The way I'm sort of getting around the issue is that I noticed that the `_estimateSize` function looks for any token in the policy resources and if one is found, use the max size for resource ARNs. Almost all of my resources have the AWS Partition token in them.  I put the real partition value in and this eliminated all of the overflow policies except for one.  I then re-ran CDK synth 20 times, comparing it against a baseline output and there were no changes between synths.

Still feel like there is a problem somewhere here, but without a good way to reproduce, I think it's safe to close this issue.

**Comment by peterwoodworth** [comment]
Thanks for your updates @polothy, let me know if you can find a way to consistently reproduce this
