### ISSUE TITLE
(eks): (update of lambda function code)

### ISSUE THREAD

**Issue by hbhatia-demyst** [aws/aws-cdk#20679]
### Describe the bug

Lambda's which provide kubectl / helm access do not get updated when underlying code is upgraded by the lib.

### Expected Behavior

New code should be reflected when EKS stack is updated.

### Current Behavior

Code referenced is still the version which it was first created with.

### Reproduction Steps

1. Install aws-cdk some old version.
2. Create an EKS cluster and install helm chart.
3. Now upgrade to latest cdk which preferably has changes to helm code.
4. Inspect lambda code after the changes are deployed.

### Possible Solution

Have some versioning when deploying lambda code to enforce deployment. 

### CDK CLI Version

2.27

### Node.js Version

16

### OS

linux

### Language

Typescript

**Comment by otaviomacedo** [comment]
Hi, @hbhatia-demyst. I'm not sure what you mean by "Lambda's which provide kubectl / helm access". Are you referring to the [lambda-layer-kubectl] module? If so, whenever the version of `kubectl` or `helm` is updated, a new version of the layer is generated and becomes available in the next release of the CDK.

[lambda-layer-kubectl]: https://github.com/aws/aws-cdk/tree/main/packages/%40aws-cdk/lambda-layer-kubectl
