### ISSUE TITLE
rds: DB instance allocated storage units "specified in gigabytes (GB)", while AWS reports in gibibytes (GiB)

### ISSUE THREAD

**Issue by l0b0** [aws/aws-cdk#20676]
### Describe the bug

The documentation in `aws_rds.DatabaseInstance` and `aws_rds.DatabaseInstanceFromSnapshot` both document the storage size as follows:

```python
:param allocated_storage: The allocated storage size, specified in gigabytes (GB). Default: 100
```

One gigabyte is 10⁹ or 1,000,000,000 bytes. AWS, however, reports the storage allocation of DB instances and snapshots in GiB (2³⁰ or 1,073,741,824 bytes). I assume the documentation is simply wrong, otherwise there would have to be some funky conversion going on inside CDK.

### Expected Behavior

The units in the documentation and functionality should line up with the units used in AWS itself.

### Current Behavior

As above.

### Reproduction Steps

N/A

### CDK CLI Version

2.27.0 (build 8e89048)

### Node.js Version

v14.18.1

### OS

NixOS

### Language

Python

### Language Version

3.9.6

**Comment by peterwoodworth** [comment]
This is probably because Cfn docs say the same thing https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html#cfn-rds-dbinstance-allocatedstorage

Have you confirmed that Cfn treats this number as if it's in GB or GiB?

**Comment by l0b0** [comment]
@peterwoodworth The documentation you linked is internally inconsistent. It says "gigabytes" but then uses "GiB" everywhere, with no "GB" in sight. I've sent [feedback](https://docs.aws.amazon.com/forms/aws-doc-feedback?hidden_service_name=RDS&topic_url=https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html#cfn-rds-dbinstance-allocatedstorage) to them about this issue. In the meantime, would it be OK to update the CDK docs to honor the "GiB" in the Cfn docs?

**Comment by peterwoodworth** [comment]
Yes, feel free to submit a PR for it 🙂

**Comment by l0b0** [comment]
FYI, from AWS:

> Based on your feedback, I corrected the documentation to specify that the storage is in gibibytes (GiB).
