### ISSUE TITLE
aws-lambda-nodejs: During precompilation, set false flags for tsc compiler options

### ISSUE THREAD

**Issue by villecoder** [aws/aws-cdk#20670]
### Describe the bug

Given the following tsconfig.json:
```json
{
    "lib": ["ESNext"],
    "moduleResolution": "node",
    "module": "commonjs",
    "target": "ES2020",
    "allowSyntheticDefaultImports": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "outDir": "dist",
    "rootDir": "./",
    "strict": true,
    "noImplicitAny": false,
    "strictNullChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "removeComments": true,
    "sourceMap": true,
    "strictPropertyInitialization": false
  }
```

Any option that is set to false is omitted from the tsc command line options. This results in failed compilations during cdk synthesis whereas building directly with tsc does not fail.

### Expected Behavior

Command line options should be (newlines added for readability):
```bash
--lib ESNext
--moduleResolution node 
--module commonjs 
--target ES2020 
--baseUrl . 
--allowSyntheticDefaultImports
--experimentalDecorators
--emitDecoratorMetadata
--esModuleInterop
--skipLibCheck
--outDir ./ 
--rootDir ./ 
--strict
--noImplicitReturns
--noFallthroughCasesInSwitch
--removeComments
--sourceMap
--noImplicitAny false
--strictNullChecks false
--noUnusedLocals false
--noUnusedParameters false
```

### Current Behavior

Command line options are (newlines added for readability):
```bash
--lib ESNext
--moduleResolution node 
--module commonjs 
--target ES2020 
--baseUrl . 
--allowSyntheticDefaultImports
--experimentalDecorators
--emitDecoratorMetadata
--esModuleInterop
--skipLibCheck
--outDir ./ 
--rootDir ./ 
--strict
--noImplicitReturns
--noFallthroughCasesInSwitch
--removeComments
--sourceMap
```

### tsconfig.json
```json
{
  "compilerOptions": {
    "lib": ["ESNext"],
    "moduleResolution": "node",
    "strictPropertyInitialization": false
  }
}
```

## person.ts
```typescript
export class Person {
  name: string;
  email: string;

  constructor(name: string) {
    this.name = name;
  }
}
```

### index.ts

```typescript
import { Person } from 'person';
const Jeff = new Person("Jeff");
console.log('Hello ' + Jeff.name);
```

### Possible Solution

Change:
https://github.com/aws/aws-cdk/blob/5696c5da865c2461121ac12754eb53c5a9024e51/packages/%40aws-cdk/aws-lambda-nodejs/lib/util.ts#L176-L178

to 
```typescript
if (value) {
  compilerOptionsString += option + " "
} else {
  compilerOptionsString += option + " false "
}
```

### CDK CLI Version

2.27.0 (build 8e89048)

### Node.js Version

v18.2.0

### OS

Ubuntu 22.04 LTS

### Language

Typescript

### Language Version

Typescript (4.7.2)

**Comment by peterwoodworth** [comment]
Thanks for submitting this bug report, we accept contributions! Check out our [contributing guide](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) if you're interested - there's a low chance the team will be able to address this soon but we'd be happy to review a PR 🙂

**Comment by villecoder** [comment]
I'm quite lost and need help here. I'm at the point where I am ready to contribute unit tests to verify my changes work. I understand where to change the code, and I understand where I can contribute a unit test. However, I'm unclear how the tests are being run and where they are being run from. Specifically, I'm looking for the `tsconfig.json` file referenced in the unit test file.

https://github.com/aws/aws-cdk/blob/5696c5da865c2461121ac12754eb53c5a9024e51/packages/%40aws-cdk/aws-lambda-nodejs/test/util.test.ts#L185

I'd like to know if that file already has any false flag options and if I should extend it to include them. Running 'yarn test' from the command line in the module's folder just gives me `Tests successful. Total time (0.0s)` which leads me to believe that no tests were actually run.

Any help would be appreciated.

**Comment by hassanazharkhan** [comment]
@villecoder Thanks for describing the issue comprehensively, this has helped a lot!

**Comment by hassanazharkhan** [comment]
@villecoder Thanks for describing the issue comprehensively, this has helped a lot!
