### ISSUE TITLE
(aws-cloudfront): (fromLookupOriginAccessIdentity)

### ISSUE THREAD

**Issue by guilhermebc** [aws/aws-cdk#20686]
### Describe the feature

Thinking about dynamic infrastructure solutions where some resources are reused, such as a bucket to serve several cloudfront distributions permissioned via OriginAccessIdentity, the need was found to have a method for reading OriginAccessIdentities already created.

### Use Case

I always get frustrated when I need to read or create dynamic CDNs and link to a unique bucket.
I cant do this with only aws-cdk.

I had to make an adaptation using `@aws-cdk/client-*`.

### Proposed Solution

```ts
static fromLookupOriginAccessIdentity(scope, id, { options... })

[IOriginAccessIdentity](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-cloudfront.IOriginAccessIdentity.html)
**Reads** a OriginAccessIdentity by providing the OriginAccessIdentityName.
```

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.27.0

### Environment details (OS name and version, etc.)

MacOS 12.2.1

**Comment by peterwoodworth** [comment]
What functionality would this feature provide that our current [oai import method](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-cloudfront.OriginAccessIdentity.html#static-fromwbroriginwbraccesswbridentitywbrnamescope-id-originaccessidentityname) doesn't?

**Comment by guilhermebc** [comment]
> What functionality would this feature provide that our current [oai import method](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-cloudfront.OriginAccessIdentity.html#static-fromwbroriginwbraccesswbridentitywbrnamescope-id-originaccessidentityname) doesn't?

` fromOriginAccessIdentityName` doesn't import an existent, it creates a new OAI.
```
static fromOriginAccessIdentityName(scope, id, originAccessIdentityName)
public static fromOriginAccessIdentityName(scope: Construct, id: string, originAccessIdentityName: string): IOriginAccessIdentity
Parameters

[IOriginAccessIdentity](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-cloudfront.IOriginAccessIdentity.html)
```
**Creates a OriginAccessIdentity by providing the OriginAccessIdentityName.**

**Comment by peterwoodworth** [comment]
It doesn't create a new OAI - It imports an existing one to use in your stack.

**Comment by guilhermebc** [comment]
> It doesn't create a new OAI - It imports an existing one to use in your stack.

There is something wrong, I tried with existing OAI and always return message error.

**Comment by peterwoodworth** [comment]
what exact error are you running into when passing existing name?

Could you post your full code block where you create the oai and then use it?

**Comment by guilhermebc** [comment]
> what exact error are you running into when passing existing name?
> 
> Could you post your full code block where you create the oai and then use it?

returns with `...its not valid name`

**Comment by guilhermebc** [comment]
> what exact error are you running into when passing existing name?
> 
> Could you post your full code block where you create the oai and then use it?
![Screen Shot 2022-06-10 at 21 28 09](https://user-images.githubusercontent.com/14234175/173165378-af6db445-daac-4cf6-882e-4fdd975ae5bf.png)

But the OAI exists.

**Comment by peterwoodworth** [comment]
Are you passing in the OAI ID? The name fromOriginAccessIdentityName is actually a misnomer. See [here](https://github.com/aws/aws-cdk/issues/20141)

**Comment by guilhermebc** [comment]
> Are you passing in the OAI ID? The name fromOriginAccessIdentityName is actually a misnomer. See [here](https://github.com/aws/aws-cdk/issues/20141)

So can we get IOriginAccessIdentity by comment? I need get OAI Ids dynamically to build my infra.

**Comment by guilhermebc** [comment]
fromOriginAccessIdentityName passing OAI Id works.
