### ISSUE TITLE
aws_elasticache: cluster_name set to None in CDKv2

### ISSUE THREAD

**Issue by ajoseph-godaddy** [aws/aws-cdk#20691]
### Describe the bug

When attempting to setup alarms it was found that if we do not explicitly set the "cluster_name" property of elasticache that when we later to go setup an alarm we get a None back for cluster_name. 

### Expected Behavior

Expected behavior would be to return the actual cluster name based on logical ID as the documentation states. 
```cluster_name (Optional[str]) – A name for the cache cluster. If you don’t specify a name, AWSCloudFormation generates a unique physical ID and uses that ID for the cache cluster. For more information, see [Name Type](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-name.html) . The name must contain 1 to 50 alphanumeric characters or hyphens. The name must start with a letter and cannot end with a hyphen or contain two consecutive hyphens.```

### Current Behavior

None is returned when attempting to return the Cluster Name

### Reproduction Steps

Attempt to get the cluster name from the elasticache stack. 

### CDK CLI Version

2.27.0 (build 8e89048)

### Node.js Version

16

### OS

Mac

### Language

Python

**Comment by peterwoodworth** [comment]
Our elasticache module is all L1s - that is, they are exactly copies of the CloudFormation elasticache resources with no additional or missing functionality.

note for the cachecluster, if you want to return the cluster name, the [ref](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticache-cache-cluster.html#aws-properties-elasticache-cache-cluster-return-values) will return that.

in CDK, you can reference this simply with `.ref` as you would `.clusterName`

Hope this helps!
