### ISSUE TITLE
(aws-certificatemanager): DnsValidatedCertificate created without tags from Stack

### ISSUE THREAD

**Issue by ChrisLane** [aws/aws-cdk#20698]
### Describe the bug

Unlike all my other resources ,when I create a certificate using `DnsValidatedCertificate` tags from the stack are not added to the certificate.

### Expected Behavior

Tags from the parent stack should be added to certificates created with `DnsValidatedCertificate`

### Current Behavior

Tags from the parent stack are not currently added to certificates created with `DnsValidatedCertificate`

### Reproduction Steps

Create a certificate with `DnsValidatedCertificate` in a Stack that has tags.

### CDK CLI Version

2.27.0 (build 8e89048)

### Node.js Version

v18.3.0

### OS

Linux 5.18.2-zen1-1-zen

### Language

Typescript

**Comment by corymhall** [comment]
@ChrisLane can you provide a reproducible example? `DnsValidatedCertificate` does have support for adding tags.
