### ISSUE TITLE
DockerImageAsset is not always pushed into ECR when image changed

### ISSUE THREAD

**Issue by alex-berger** [aws/aws-cdk#2070]
When applying small changes to a Docker image `calculateImageFingerprint` might return unchanged hash and the Image is not pushed to ECR as CDK assumes it is already pushed. The image's ID is different (as is its content), but the fingerprint returned from `calculateImageFingerprint` remains unchanged.

### Expected Behavior

Every time the image changes it must be pushed to ECR repository.

### Observed Behavior 

Image changes are not always detected, as CDK does not use the image's ID but uses `calculateImageFingerprint` instead. As a result the image is not pushed to ECR repository.

Our team spent several days hunting down this bug, and we are working on a pull request to propose a fix.

**Comment by rix0rrr** [comment]
We went with a "whitelisting instead of blacklisting" approach in calculateFingerprint.

**Comment by rix0rrr** [comment]
Oopsie

**Comment by alex-berger** [comment]
Note sure, but deleting some attributes while keeping all the others looks more like "blacklisting" to me (see excerpt below). However, from our findings this is not the cause of the problem, so far we figured out that the only way to ensure correct behavior is to remove all (premature) optimizations and by using Docker's image ID instead. I will open a (WIP) PR, which I hope will make my point a bit better understandable :-).

```JavaScript
async function calculateImageFingerprint(imageId: string) {
  const manifestString = await shell(['docker', 'inspect', imageId], { quiet: true });
  const manifest = JSON.parse(manifestString)[0];

  // Id can change
  delete manifest.Id;

  // Repository-based identifiers are out
  delete manifest.RepoTags;
  delete manifest.RepoDigests;

  // Metadata that has no bearing on the image contents
  delete manifest.Created;

  // We're interested in the image itself, not any running instaces of it
  delete manifest.Container;
  delete manifest.ContainerConfig;

  // We're not interested in the Docker version used to create this image
  delete manifest.DockerVersion;

  // On some Docker versions Metadata contains a LastTagTime which updates
  // on every push, causing us to miss all cache hits.
  delete manifest.Metadata;

  // GraphDriver is about running the image, not about the image itself.
  delete manifest.GraphDriver;

  return crypto.createHash('sha256').update(JSON.stringify(manifest)).digest('hex');
}
```

**Comment by rix0rrr** [comment]
You are right, I meant to say the opposite.

**Comment by eladb** [comment]
@rix0rrr what do you think about this?

**Comment by eladb** [comment]
@alex-berger we have changed the fingerprinting of images to use the *source* instead of the built artifact. This should address your concern I believe. Can you confirm?

**Comment by alex-berger** [comment]
@eladb I am sorry, but I lost track of this issue and we moved away from cdk for the affected project. From my point of view we can close this issue.

**Comment by eladb** [comment]
OK, closing for now.

**Comment by devinivy** [comment]
I think I may have determined part of the issue here: the `exclude` patterns provided to `assets.Staging` ultimately match against absolute filenames, but should actually be matching against filenames relative to the source directory.  This can easily cause the whole project to be excluded if it happens to be within a directory matching one of these patterns.  Would it be possible to re-open this issue?
