### ISSUE TITLE
[aws_ecs]: FargateTaskDefinition container definitions order

### ISSUE THREAD

**Issue by nlucero** [aws/aws-cdk#20732]
### Describe the issue

I'm working on setting up a new `FargateTaskDefinition` with multiple containers (the main container plus two additional secondary containers for log shipping). My main container is added first (thus becoming the task `defaultContainer`) and the two others are added after.
From what I see on the docs, I was under the impression whatever container is the `defaultContainer` in the `cdk` construct, it would end up being the _first_ (and main) container in the resulting task definition, but that doesn't seem to be the case. The task `defaultContainer` would end up in the second place which breaks other parts of my setup (I'm using an external plugin that assume the [main container is always the first one](https://github.com/jenkinsci/amazon-ecs-plugin/blob/a3cffcb9d7f8b2aa79e758a0422e6535311e3ad0/src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSService.java#L418-L421)).

Are there any other non-documented factors that could impact the resulting order of those containers? For example, if I remove a set `memoryReservationMiB` on the main container, it will end up in the first place as expected, but this seems too random to me. Can the containers order by defined more explicitly? Otherwise, I feel like my setup is too fragile and any change in the task def that might affect the order of the containers will produce a broken deploy.

A simplified version of my code:

```ts
this.taskDef = new ecs.FargateTaskDefinition(this, 'worker-task-def', {
      cpu: 1024,
      memoryLimitMiB: 2048,
      executionRole: this.executionRole,
      taskRole: this.taskRole,
});
this.taskDef.addContainer('worker-container', {
      image: ecs.ContainerImage.fromDockerImageAsset(image),
      // Commenting this line makes it end up in the first place (?)
      // memoryReservationMiB: 1024,
      logging: new FireLensLogDriver({ ... })
});
this.taskDef.addContainer('dd-agent', {
      image: ecs.ContainerImage.fromRegistry('gcr.io/datadoghq/agent:latest'),
      ...
});
this.taskDef.addFirelensLogRouter('firelens', {
      image: obtainDefaultFluentBitECRImage(
        this.taskDef,
        this.taskDef.defaultContainer?.logDriverConfig
      ),
      ...
});
```

### Links

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ecs-readme.html#task-definitions

**Comment by peterwoodworth** [comment]
Looking at the code, it seems to me that the order of containers in the rendered definition will be the order in which they were added to the task, which won't necessarily be the defaultContainer. Though, based on your description, it sounds like the first container you're adding is not the first one to be rendered in the template? I'm finding with your condensed example that the containers are showing up in the template in the same order they were added to the task definition

**Comment by nlucero** [comment]
> Looking at the code, it seems to me that the order of containers in the rendered definition will be the order in which they were added to the task, which won't necessarily be the defaultContainer. Though, based on your description, it sounds like the first container you're adding is not the first one to be rendered in the template? I'm finding with your condensed example that the containers are showing up in the template in the same order they were added to the task definition

That doesn't seem to be the case in my case so I'm trying to determine what other factors end up affecting the order in which those containers are _rendered_ in the final Task Definition. For example, as I pointed out in the example, adding a fixed `memoryReservationMiB` to the first container makes it effectively end up in the first place, which makes little sense to me.
I've tried going over several pages of `AWS` documentation and I couldn't find anything about this.

**Comment by peterwoodworth** [comment]
Yeah disabling `memoryReservationMiB` doesn't swap the order things were rendered in when I try to reproduce this. The only thing that seems to determine the order for me when I mess around with this is the order in which they are declared in the stack. 

Let me know if you can isolate anything that might otherwise determine the order
