### ISSUE TITLE
aws_iam: Add addToPolicy method to IUser

### ISSUE THREAD

**Issue by tl24** [aws/aws-cdk#20749]
### Describe the feature

addToPolicy is implented on imported users but not exposed through the IUser interface.  Related to #10913

### Use Case

I want to attach policies to externally managed users.
Example use case:
```
const user = iam.User.fromUserName(this, 'user', 'some_user_name')
const role = new iam.Role(this, 'role', {
  assumedBy: user,
  description: 'Example role...',
});
user.addToPolicy(new iam.PolicyStatement({
        actions: ["iam:PassRole", "sts:AssumRole"],
        resources:[ role.roleArn ]
}))
```

### Proposed Solution

Add the following to IUser
```
export interface IUser extends IIdentity {
     addToPolicy(statement: PolicyStatement): boolean;
}
```

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.28.0

### Environment details (OS name and version, etc.)

Ubuntu 20.04

**Comment by peterwoodworth** [comment]
We accept contributions, feel free to submit a PR for this and we can take a look at it 🙂 

Check out our [contributing guide](https://github.com/aws/aws-cdk/blob/v1-main/CONTRIBUTING.md) if you're interested

**Comment by aamielsan** [comment]
@peterwoodworth I raised a PR for this change, can you check? It's my first PR for aws-cdk, so comments/suggestions will be highly appreciated

**Comment by peterwoodworth** [comment]
Thanks for following up here @aamielsan, really appreciate it!
