### ISSUE TITLE
efs.AccessPoint: Not possible to tag construct using Tags.of(...)

### ISSUE THREAD

**Issue by fredbonin** [aws/aws-cdk#20743]
### Describe the bug

If you try to tag an efs.AccessPoint construct using Tags.of(...) , the tag won't be applied.

### Expected Behavior

I would expect the tag to be applied

### Current Behavior

Tag specified using Tags.of is never assigned and no error messages are seen in the console

### Reproduction Steps

Here is a sample code that reproduces the issue : 

```
        let accessPoint = new efs.AccessPoint(this, "EfsAP", {
                fileSystem: fileSystem,
                createAcl : {
                    ownerUid : "1000",
                    ownerGid : "1000",
                    permissions : "755"
                },
                path: "/myPath",
                posixUser: {
                    gid: "1000",
                    uid: "1000",
                    secondaryGids : []
                }
            }
        );
        Tags.of(accessPoint).add('Name', 'my-tag'); // BUG : Tag won't be applied
```

### Possible Solution

A workaround is to use this CfnConstruct (this is a possible workaround, but it would be better to use L2 construct) : 

```
      new CfnAccessPoint(this, 'Resource', {
            accessPointTags: [{
              key : "Name",
              value : "my-tag"
            }],
            fileSystemId: fileSystem.fileSystemId,
            rootDirectory: {
                creationInfo: {
                    ownerGid: "1000",
                    ownerUid: "1000",
                    permissions: "755",
                },
                path: "/myPath",
            },
            posixUser: {
                uid: "1000",
                gid: "1000",
                secondaryGids: [],
            },
        });
```

### CDK CLI Version

2.27.0 (build 8e89048)

### Node.js Version

v16.14.0

### OS

MacOS 12.4

### Language

Typescript

### Language Version

~3.9.7

**Comment by corymhall** [comment]
It looks like this should be an easy fix. We just need to add `AccessPointTags` to here

https://github.com/aws/aws-cdk/blob/c262034afd2468c5bcf1cf47c45a70116c378d3e/packages/%40aws-cdk/cfnspec/lib/schema/resource-type.ts#L31-L39

**Comment by ymhiroki** [comment]
@corymhall

Hi!
I created a pull request for this issue, however, tags are not generated correctry.
I would appreciate it if you could give me some advice.
