### ISSUE TITLE
ssm: StringParameter example is wrong

### ISSUE THREAD

**Issue by SC-CTS** [aws/aws-cdk#20763]
### Describe the issue

On the StringParamter documentation page it has an example for a Vpc which only tangentially mentions the StringParameter. I'd expect the example to be more focused on the StringParameter.

### Links

- https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ssm.StringParameter.html
- https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_ssm.html

**Comment by peterwoodworth** [comment]
Thanks for reporting this @SC-CTS,

Our examples are automatically pulled from code snippets found in our various readme files. Though, we do have the choice to create our own example if the linked example isn't a very good one. We can create a new example here 🙂 Check out the [contributing guide](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) to get started if you're interested

**Comment by peterwoodworth** [comment]
Check out this thread for more information @SC-CTS https://github.com/aws/aws-cdk/issues/20374

Basically, what we want to do is declare our own example exactly where StringParameter is declared. We can do this with an `@example` in the docstring you see right above `StringParameter` here https://github.com/aws/aws-cdk/blob/de59b897ca0faf52afb9f05796364ca0134b5771/packages/%40aws-cdk/aws-ssm/lib/parameter.ts#L329-L333

**Comment by josephedward** [comment]
@peterwoodworth sorry to bug you, here is another doc fix I worked on

https://github.com/aws/aws-cdk/pull/20906

**Comment by josephedward** [comment]
https://github.com/aws/aws-cdk/pull/21127 @peterwoodworth new PR with correct branch name
