### ISSUE TITLE
@aws-cdk/aws-appsync-alpha: Issue defining resolver caching keys

### ISSUE THREAD

**Issue by SchollSimon** [aws/aws-cdk#20773]
### Describe the bug

I enabled PER_RESOLVER_CACHING for my appsync graphql api. I tried to defined a caching config for `new Resolver`, but the cachingKeys are not getting deployed.

```
const resolver = new Resolver(scope, `Resolver`,
  {
    ...config,
    api: this,
    cachingConfig: {
      ttl: Duration.seconds(3600),
      cachingKeys: ['$context.identity.claims.https://domain:prop'],
    },
  }
);
```

### Expected Behavior

The resolver gets deployed as i have a valid cachingKey defined
`$context.identity.claims.https://domain:prop`

### Current Behavior

Deployment of stack crashes with Error
Caching keys need to start with $context.args, $context.arguments, $context.identity, or $context.source. (Service: AWSAppSync; Status Code: 400; Error Code: BadRequestException; Request ID: 37982d8a-0e08-4a7c-b4b5-35be0a001569; Proxy: null)

### Reproduction Steps

Just try to define a resolver like i did.

### CDK CLI Version

2.25.0

### Framework Version

2.25.0

### Node.js Version

v16.13.1

### OS

Windows 10

### Language

Typescript

### Language Version

4.5.4

### Other information

Same issue reported here
https://github.com/aws/aws-appsync-community/issues/202

**Comment by otaviomacedo** [comment]
Hi, @SchollSimon. I couldn't find any documentation for this, but I think AppSync only allows alphanumeric characters in the keys (plus `.` to separate the levels).

**Comment by SchollSimon** [comment]
@otaviomacedo okay i already feared that something like this would be the case. Exactly this is a custom claim from our token. Any solution you can suggest or best practice? Yeah the documentation ... is very sparse on this topic. 

Do you know if i can use the whole claim object as a caching key? Or do those claims have to point on prop level?

**Comment by otaviomacedo** [comment]
Can you give me more details about what you're trying to achieve? What's the structure of your `claims` object?

**Comment by SchollSimon** [comment]
@otaviomacedo Thy for the fast answer and sure. Here is a sample of our complete token (auth0):
`eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InJBZzU0R3lNLTZBS0MxZlFHcGx3VSJ9.eyJodHRwczovL3JlbGxpZnk6dXNlcklkIjoiNGU4ZTc4ZDEtOWUwOC00YTkzLWE1NDMtOGEzODhmOTFlYTFkIiwiaHR0cHM6Ly9yZWxsaWZ5Om9yZ0lkIjoiN2E1ZDg1NDktMTg4Yy00MDQ5LTgyMmItY2YzYmMzYjA1YTk5IiwiaHR0cHM6Ly9yZWxsaWZ5OmF1dGgwcm9sZSI6IkFkbWluIiwiaXNzIjoiaHR0cHM6Ly9kZXYtcmVsbGlmeS51cy5hdXRoMC5jb20vIiwic3ViIjoiYXV0aDB8NjBjMzA5M2E4YmM3M2QwMDcwMDUwMmVlIiwiYXVkIjpbImh0dHBzOi8vZ3JhcGhxbC5yZWxsaWZ5LmRldi8iLCJodHRwczovL2Rldi1yZWxsaWZ5LnVzLmF1dGgwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE2NTcyNTk5MTIsImV4cCI6MTY1NzM0NjMxMiwiYXpwIjoiQlhDdVl4QTNUSzllMHhUQjhhYkd4QlJjV05HSW1KZEkiLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIG9mZmxpbmVfYWNjZXNzIiwib3JnX2lkIjoib3JnX2xGbEFkaTRJRUlXeVA1ZnEifQ.CqBYr292mT3KAsrRBdE9ZzgSWR_a40tXxdu0BKj34XWQ42tsIoS9G0ODLGzCTGKg4kAM1RP5kTrl55zDd1T-2yBy2WFW4d6jqFD7kozCnkdlNInFWI_XPVLaanmiQq_ww0KtNHTo_kzdCmlQw-2vVeFFl5evdB_KyhhW7nca9PWCB2zxpRyz5xG2aOGdaeUIzNVyGUjkmLBfElNLbAyBzlA8pxOvU_kn_KttuxcB1vBpsowC9e8CmtTO1cbxOfl2meQh3EdvfnVZ5rkltjg0ZkQCbqgbdsKlcncZUF5GWZeMLKxs24j-EibdTCVecvO_Eco4dguJ3vi-PBiA49fzWw`

You can content here: https://jwt.io/

The claims contain the whole payload:
`{
  "https://rellify:userId": "4e8e78d1-9e08-4a93-a543-8a388f91ea1d",
  "https://rellify:orgId": "7a5d8549-188c-4049-822b-cf3bc3b05a99",
  "https://rellify:auth0role": "Admin",
  "iss": "https://dev-rellify.us.auth0.com/",
  "sub": "auth0|60c3093a8bc73d00700502ee",
  "aud": [
    "https://graphql.rellify.dev/",
    "https://dev-rellify.us.auth0.com/userinfo"
  ],
  "iat": 1657259912,
  "exp": 1657346312,
  "azp": "BXCuYxA3TK9e0xTB8abGxBRcWNGImJdI",
  "scope": "openid profile email offline_access",
  "org_id": "org_lFlAdi4IEIWyP5fq"
}`


Most important for us regarding caching:
` "https://rellify:userId": "4e8e78d1-9e08-4a93-a543-8a388f91ea1d",
  "https://rellify:orgId": "7a5d8549-188c-4049-822b-cf3bc3b05a99",`

**Comment by otaviomacedo** [comment]
Got it. I haven't tried, but the documentation seems to suggest that caching the entire `claims` object would work.

**Comment by SchollSimon** [comment]
Sry for my late answer :). Yep i also thought of that, but the problem is if you want to cache like on an organitation level that is not gonna work sadly :/.
