### ISSUE TITLE
aws_codepipeline_actions: CodeDeployLambdaDeployAction

### ISSUE THREAD

**Issue by schuster-eb** [aws/aws-cdk#20782]
### Describe the feature

Request a CodePipeline action to CodeDeploy Lambdas.

### Use Case

I haven't been able to get `CodeDeployServerDeployAction` or `CodeDeployEcsDeployAction` to successfully deploy a Lambda. 

* CodeDeployEcsDeployAction: asks for an ECS task definition
* CodeDeployServerDeployAction: only accepts an artifact `input` for properties. However, it won't pick up the `appspec` file I have defined in the artifact and there are no properties to define the path 

### Proposed Solution

I think `CodeDeployServerDeployAction` may work, either it needs to automatically grab an `appspec.json` or add the prop to specify the path `artifact.atPath('appspec.json')`

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.23.0

### Environment details (OS name and version, etc.)

Mac OS

**Comment by indrora** [comment]
Deploying a lambda is documented as an example: https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_codepipeline_actions-readme.html#lambda-deployed-through-codepipeline

It's a bit convoluted at the moment (involves a Stack Update call), but works.

**Comment by gregmagdits** [comment]
> Deploying a lambda is documented as an example: https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_codepipeline_actions-readme.html#lambda-deployed-through-codepipeline
> 
> It's a bit convoluted at the moment (involves a Stack Update call), but works.

Unless I am mistaken, this does not create a pipeline with a code-deploy action at the end, but a cloud formation createUpdateStack which has the intended effect of deploying a new LambdaFunction, but does not actually use the CodeDeploy service at all. 
Creating a pipeline utilizing CodeDeploy to deploy to a lambda type application is possible in the AWS console, so it should be possible to create it in the CDK, however this does not seem to be the case. 
What the original poster was suggesting makes sense to me... if there is already a CodeDeployServerDeployAction and a CodeDeployEcsDeployAction, naturally there should be a CodeDeployLambdaDeployAction, but this class seems to be missing

**Comment by lehigh123** [comment]
Is there still no support for using CodeDeploy to update a lambda via a code pipeline defined in CDK?

**Comment by jarrodlilkendey** [comment]
This would be a useful feature to have. Could this be added to the CDK?
