### ISSUE TITLE
aws-rds: Lambda invocation role support in DBCluster

### ISSUE THREAD

**Issue by brachna9** [aws/aws-cdk#20792]
### Describe the feature

RDS Cluster supports [associating a lambda invocation role](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraMySQL.Integrating.Authorizing.IAM.AddRoleToDBCluster.html). However, [DatabaseCluster](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-rds.DatabaseCluster.html) construct supports only associating S3 import/export and monitoring roles only. 

### Use Case

Right now, it is not possible to associate lambda role with database cluster using DatabaseCluster construct. A user may have to associate the role manually using CLI or using CfnDBCluster construct as a workaround.

### Proposed Solution

Add another prop in [DatabaseClusterProps](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_rds.DatabaseClusterProps.html) like monitoringRole, s3ImportRole or s3ExportRole - say lambdaRole which can associate a lambda role with DatabaseCluster.

### Other Information

As a workaround [CfnDBCluster](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_rds.CfnDBCluster.html) construct can be used.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.18.1

### Environment details (OS name and version, etc.)

MacOs - issue applicable to all.

**Comment by corymhall** [comment]
@brachna9 it looks like we had an issue for this which had been closed for being too old. I went ahead and reopened it. The issue also has a comment with a workaround that can be used until the feature is implemented.

I'm going to close this one so we can use the other issue to track.

https://github.com/aws/aws-cdk/issues/14751
