### ISSUE TITLE
aws-cdk-lib/aws-route53resolver: Missing L2  constructs for route53 resolver

### ISSUE THREAD

**Issue by cccristi07** [aws/aws-cdk#20802]
### Describe the feature

CDKv2 is missing route53resolver L2 constructs, provides only low level Cfn* classes.

### Use Case

CDKv1 offered a convenient way of creating route53resolver resources:

```ts
const rg = new route53resolver.FirewallRuleGroup(...)

rg.addRule(...)

```

CDKv2 on the other hand only allows L1 constructs

```ts
const rg new route53resolver.CfnFirewallRuleGroup(
      ...
)
// :(
```

Is there any plan to add route53resolver L2 constructs to CDKv2?

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.27.0

### Environment details (OS name and version, etc.)

Linux,

**Comment by jogold** [comment]
It's still experimental and hence published as an alpha module in v2: https://docs.aws.amazon.com/cdk/api/v2/docs/aws-route53resolver-alpha-readme.html

See also https://aws.amazon.com/blogs/developer/experimental-construct-libraries-are-now-available-in-aws-cdk-v2/ and https://docs.aws.amazon.com/cdk/v2/guide/migrating-v2.html

**Comment by peterwoodworth** [comment]
Thanks jogold! Hope this helped @cccristi07
