### ISSUE TITLE
(aws-appsync-alpha): Hotswap VTL Files when using cdk watch

### ISSUE THREAD

**Issue by ghost** [aws/aws-cdk#20818]
### Describe the feature

Hi,

Just like to say I'm really enjoying developing appsync with cdk. I also really enjoy using the cdk watch command, which is especially nice with lambdas as it takes only a few seconds to get the assets swapped out.

It would be really nice if cdk watch could hotswap vtl resolvers in the same way. No idea how big an ask that is but thought I'd propose it.

### Use Case

I use cdk watch during development and it would be very helpful to have vtl resolvers hotswap with dev environment when they are saved.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.28.1

### Environment details (OS name and version, etc.)

Mac OS

**Comment by nitesout** [comment]
Forgot to mention I'm using the MappingTemplate.fromFile() functionality

**Comment by nitesout** [comment]
Just noticed it already does this, awesome!
