### ISSUE TITLE
servicecatalog: Constraints must depend on AWS::ServiceCatalog::PortfolioProductAssociation

### ISSUE THREAD

**Issue by pergardebrink** [aws/aws-cdk#20810]
### Describe the bug

When adding a TagConstraint or LaunchConstraint to a Service Catalog product, there seems to be an issue with CloudFormation that ends up with a ResourceNotFound exception intermittently (it seems to happen more frequently in eu-west-1). 

I raised a ticket with AWS Support which came back to me suggesting that I needed to add a DependsOn to the `AWS::ServiceCatalog::PortfolioProductAssociation`. After doing this, it seems to work as it should (I added the DependsOn by iterating over all children to the Portfolio construct and added a dependency on this from the constraint).

I would argue that this is a bug in the Service Catalog CloudFormation provider for Service Catalog and not an issue in CDK, but not sure that will be fixed ever, so I think the CDK construct should track the dependency and add a DependsOn to the association when you add a constraint to the product/portfolio.

### Expected Behavior

When adding a tag constraint to a product, it should create the constraint

### Current Behavior

When deploying the stack, it fails intermittently with "ResourceNotFound"

![cloudformation](https://user-images.githubusercontent.com/8502070/174745661-c16f4b83-036a-4f07-bc59-f29e3755a38f.png)

### Reproduction Steps

Example stack (Python)
```
from aws_cdk import Stack, aws_servicecatalog as servicecatalog
from constructs import Construct

class ServiceCatalogBugStack(Stack):
    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        portfolio = servicecatalog.Portfolio(
            self,
            "Portfolio",
            display_name="PortfolioDisplay",
            provider_name="PortfolioProvider",
        )

        product = servicecatalog.CloudFormationProduct(
            self,
            "Product",
            product_name="Product",
            owner="Owner",
            product_versions=[
                servicecatalog.CloudFormationProductVersion(
                    cloud_formation_template=servicecatalog.CloudFormationTemplate.from_url("https://s3-external-1.amazonaws.com/cloudformation-templates-us-east-1/LAMP_Single_Instance.template")
                )
            ],
        )

        portfolio.add_product(product)

        constraint = servicecatalog.CfnResourceUpdateConstraint(
            self,
            "TagConstraint",
            portfolio_id=portfolio.portfolio_id,
            product_id=product.product_id,
            tag_update_on_provisioned_product="ALLOWED",
        )       
```

### Possible Solution

The portfolio construct should add a "DependsOn" to the `AWS::ServiceCatalog::PortfolioProductAssociation` created.

My workaround that seems to work is iterating the children:

```
for child in portfolio.node.children:
    constraint.node.add_dependency(child)
```

### CDK CLI Version

2.27

### Node.js Version

v16.13.2

### OS

Windows/Linux

### Language

Python

### Language Version

3.10

### Other information

Case ID with AWS Support (if needed): 10225546351

**Comment by arcrank** [comment]
You are using the L1 Construct which is just the autogen CfnHandler.

Use the L2, see docs here: https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_servicecatalog/Portfolio.html#aws_cdk.aws_servicecatalog.Portfolio.constrain_tag_updates

We have `dependsOn` added for all constraints, e.g. https://github.com/aws/aws-cdk/blob/fb5ebdd697b64db746670918f11446889cd3b994/packages/%40aws-cdk/aws-servicecatalog/lib/private/association-manager.ts#L53

**Comment by pergardebrink** [comment]
Oh, now I totally get that! Not sure why I didn't look closer to find the L2 construct there!

I will try that instead, sorry for the confusion on my side! Thank you very much!

I will close this issue now!
