### ISSUE TITLE
@aws-cdk/aws-s3-notifications: Support for S3 Event Notifications with EventBridge

### ISSUE THREAD

**Issue by aknight023** [aws/aws-cdk#20817]
### Describe the bug

Doesn't seem like there is currently cdk v2 support for using Amazon S3 Event Notifications with Event bridge 
as noted in this blog post

https://aws.amazon.com/about-aws/whats-new/2021/11/amazon-s3-event-notifications-amazon-eventbridge-build-advanced-serverless-applications/

### Expected Behavior

Do be able to have support for using @aws-cdk/aws-s3-notifications module for event brige. Simlair how Topics, Queues or Lambdas are currently done in @aws-cdk/aws-s3-notifications module

### Current Behavior

No Support currently

### Reproduction Steps

see above

### CDK CLI Version

2.28.0

### Node.js Version

14

### OS

macos

### Language

Typescript

### Language Version

4.5.4

**Comment by otaviomacedo** [comment]
[Support] for EventBridge notifications already exists in the S3 module.

[Support]: https://github.com/aws/aws-cdk/tree/main/packages/%40aws-cdk/aws-s3#user-content-eventbridge-notifications
