### ISSUE TITLE
(pipelines): Allow to make deployments directly without first creating changeset.

### ISSUE THREAD

**Issue by Hi-Fi** [aws/aws-cdk#20827]
### Describe the feature

Currently Pipelines creates first Changeset, and makes the actual deployment by executing it. If everything goes fine, this is OK and increases the execution time just a bit.

If there's some failure, that is random (e.g. some service used produces timeout, or custom resources in general fail), whole pipeline needs to be rerun as Changeset can't be executed twice.

This would help with e.g. #11995

### Use Case

Currently we run database migrations and trigger test runs (that need to run on target account) as custom resource, but in both of those failure (especially in latter environments) is really time consuming due the need to rerun whole pipeline again.

### Proposed Solution

As Graph implementation offers way to do deployment without prepare -step (https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/pipelines/lib/helpers-internal/pipeline-graph.ts#L28-L34), it would be nice that pipelines would support that (https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/pipelines/lib/codepipeline/codepipeline.ts#L378-L381) same way as Github (https://github.com/cdklabs/cdk-pipelines-github/blob/902e38503e2a5809154cfb574b2a5c7e1798d4af/src/pipeline.ts#L224-L228) does. Preferably with some props, and best would be possibility to define that way per stage or stack.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.28.1

### Environment details (OS name and version, etc.)

Debian GNU/Linux 11 (bullseye)

**Comment by rix0rrr** [comment]
It could be an opt-in feature, but skipping changesets disables a number of CloudFormation features your app might use, like dynamic references.
