### ISSUE TITLE
aws-ec2: Vpc construct does not deploy in aws-cn partition

### ISSUE THREAD

**Issue by girotomas** [aws/aws-cdk#20828]
### Describe the bug

with the version monocdk = 1.155.0

The error with a VPC and addFlowLogs(...) does not deploy in aws-cn.

The Loggroup cannot be deployed with error:

```
"Model validation failed (#: extraneous key [Tags] is not permitted)" 
```

Our resource:

```
 "VPCFlowLogLogGroup03CD7A70": {
      "Type": "AWS::Logs::LogGroup",
      "Properties": {
        "RetentionInDays": 731
      },
      "UpdateReplacePolicy": "Retain",
      "DeletionPolicy": "Retain",
      "Metadata": {
        "aws:cdk:path": "gamma-cn-north-1-vpc-cell-0/VPC/FlowLog/LogGroup/Resource"
      }
    },
```

### Expected Behavior

Deployed correctly.

### Current Behavior

The Loggroup cannot be deployed with error:

```
"Model validation failed (#: extraneous key [Tags] is not permitted)" 
```

### Reproduction Steps

Deploy a VPC in cn-north-1

const vpc = new ec2.Vpc(this, 'TheVPC', {
   cidr: "10.0.0.0/16"
})

vpc.addFlowLog('Log')

### Possible Solution

The root cause is that tags are not yet available in cn-north-1

### CDK CLI Version

monocdk = 1.155.0

### Node.js Version

Node v14.0.0

### OS

Amazon Linux 2

### Language

Typescript

**Comment by corymhall** [comment]
@girotomas are you adding tags via the [Tags](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.Tags.html) aspect?
