### ISSUE TITLE
(@aws-cdk/aws-glue-alpha): Add partition_filtering.enabled support

### ISSUE THREAD

**Issue by atsaki** [aws/aws-cdk#20825]
### Describe the feature

[Table](https://docs.aws.amazon.com/cdk/api/v2/docs/@aws-cdk_aws-glue-alpha.Table.html)  construct support partition indexes. However, the feature to set `partition_filtering.enabled: true`  to enable partition filtering is missing.

https://docs.aws.amazon.com/athena/latest/ug/glue-best-practices.html#glue-best-practices-partition-index

It would be nice if Table construct provide the way to set `partition_filtering.enabled` property. 

### Use Case

I always manually add `partition_filtering.enabled: true` after creating the table.
It would helpful if I can add the property with Table construct.

### Proposed Solution

How about adding a `partitionFilteringEnable` prop to TableProps and setting parameters like `classification` and `has_encrypted_data`?

```
        parameters: {
          classification: props.dataFormat.classificationString?.value,
          has_encrypted_data: this.encryption !== TableEncryption.UNENCRYPTED,
          'partition_filtering.enabled': props.partitionFilteringEnabled,
        },
```

https://github.com/aws/aws-cdk/blob/74318c7d22bfc00de9e005f68a0a6aaa58c7db39/packages/%40aws-cdk/aws-glue/lib/table.ts#L304-L307

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.28.1

### Environment details (OS name and version, etc.)

Windows

**Comment by kaizencc** [comment]
The proposed solution is good. I would be happy to take a contribution on this. I'd call the prop `enablePartitionFiltering`. @atsaki do you want to work on this?

**Comment by atsaki** [comment]
@kaizencc Yes, I would like to try it!
