### ISSUE TITLE
cdk deploy show me: ENOENT: no such file or directory, mkdtemp

### ISSUE THREAD

**Issue by oren** [aws/aws-cdk#2083]
## Step to reproduce
```
mkdir hello-cdk
cd hello-cdk
cdk init app --language=typescript
cdk deploy
```
ENOENT: no such file or directory, mkdtemp '/home/oren/t/cdkMDNeAB'

## Useful information

I use Ubuntu in Windows (Windows Subsystem for Linux)

cat /etc/lsb-release
```
Ubuntu 18.04.1 LTS
```

node -v
```
v10.15.3
```

cdk --version
```
0.26.0 (build e6f3f48)
```

**Comment by rix0rrr** [comment]
You missed `npm run build`. Where did you find the instructions you were following?

**Comment by oren** [comment]
I am following https://docs.aws.amazon.com/CDK/latest/userguide/hello_world_tutorial.html and you are correct. I missed that command. 

Now I am getting the same error when running the command `cdk ls`.

**Comment by SomayaB** [comment]
Hi, I apologize for the late reply. Are you still having this issue?

**Comment by oren** [comment]
The issue was resolved. Thank you
