### ISSUE TITLE
serviceCatalog: Incorrect service in arn generation

### ISSUE THREAD

**Issue by joostvdwsd** [aws/aws-cdk#20849]
### Describe the bug

The generated portfolio arn is using service "servicecatalog". However, arns of service catalog have the service "catalog":
arn:aws:**catalog**:<<region>>:<<accountid>>:portfolio/<<portfolioid>>

https://github.com/aws/aws-cdk/blob/2f6dd3730a14edbd3fa41b33183f5d98d62cc4cd/packages/%40aws-cdk/aws-servicecatalog/lib/portfolio.ts#L331

### Expected Behavior

Use the correct service in the generated arn

### Current Behavior

Incorrect generated arn resulting in permission errors i.e. when used in a policy statement

### Reproduction Steps

const portfolio = new servicecatalog.Portfolio(this, 'Portfolio', {
  displayName: 'My Portfolio',
  providerName: 'AWS',
});

console.log(portfolio.portfolioArn)

### Possible Solution

https://github.com/aws/aws-cdk/blob/2f6dd3730a14edbd3fa41b33183f5d98d62cc4cd/packages/%40aws-cdk/aws-servicecatalog/lib/portfolio.ts#L331

change into:
cdk.Stack.of(this).formatArn({
    service: 'catalog',
    resource: 'portfolio',
    resourceName: this.portfolioId,
  })

### CDK CLI Version

latest

### Node.js Version

any

### OS

any

### Language

Typescript

**Comment by mackalex** [comment]
Hi @joostvdwsd, thank you for raising this issue. This is certainly a valid bug and I will reproduce it locally and determine the most appropriate next steps. Based on your included possible solution, I suspect that this will be a relatively trivial fix.

**Comment by indrora** [comment]
There are two ARN services that are defined in Service Catalog - both servicecatalog and catalog. Why? Who knows.

It's documented where each is used in different places: https://docs.aws.amazon.com/service-authorization/latest/reference/list_awsservicecatalog.html#awsservicecatalog-resources-for-iam-policies
