### ISSUE TITLE
route53: Custom::DeleteExistingRecordSet fails to create

### ISSUE THREAD

**Issue by nicolai-shape** [aws/aws-cdk#20847]
### Describe the bug

I'm trying to use the new Route53 feature added in v2.29.0, for deleting existing records, on an existing stack, but when deploying the stack I get an error.

### Expected Behavior

The deployment to complete successfully.

### Current Behavior

The deployment fails with an error from the custom resource `Custom::DeleteExistingRecordSet`:

The stack named [...] failed to deploy: UPDATE_ROLLBACK_COMPLETE: Received response status [FAILED] from custom resource. Message returned: InvalidInput: Invalid XML ; cvc-complex-type.2.4.b: The content of element 'ResourceRecords' is not complete. One of '{"https://route53.amazonaws.com/doc/2013-04-01/":ResourceRecord}' is expected.

This is an example that triggers the issue, from my code base:
```typescript
new route53.ARecord(this, 'Record', {
  zone: hostedZone,
  target: route53.RecordTarget.fromAlias(
    new route53Targets.LoadBalancerTarget(loadBalancer)
  ),
  recordName: '...',
  deleteExisting: true // issue appears when this is set
})
```

### Reproduction Steps

Create a record with `deleteExisting: true`

### CDK CLI Version

2.29.0

### Framework Version

2.29.0

### Node.js Version

v16.13.1

### OS

Mac

### Language

Typescript

### Language Version

4.7.2

**Comment by jogold** [comment]
Hi @nicolai-shape,

Can you share some code? On what kind of record are you trying to use the feature?

**Comment by nicolai-shape** [comment]
@jogold It's an A record to a load balancer. I updated the issue with a record that triggers the issue for me.

**Comment by jogold** [comment]
OK, it's https://github.com/aws/aws-sdk-js/issues/3411

Will fix this.
