### ISSUE TITLE
aws-cdk-ec2: document @aws-cdk/aws-ec2:uniqueImdsv2TemplateName feature flag

### ISSUE THREAD

**Issue by aws-painec** [aws/aws-cdk#20851]
### Describe the bug

I am trying to enforce IMDSv2 metadata on my team's infrastructure packages. I have so far tried two methods for doing so using built-in methods of the CDK, both with unsatisfactory results that I believe can be traced to the same root cause.

We have a slightly unorthodox setup where we use a CDK application to define a testing environment and deploy several copies of that stack with different software versions and so on; the stacks include EC2 instances, all of which need to enforce using IMDSv2 metadata.

First, I tried using the `requireImdsv2` property on the Instance directly.

Second, I used the InstanceRequireImdsv2Aspect applied to an entire stack to enforce the requirement at the stack level.

In both cases I was able to deploy a single stack as expected, but issues arose when trying to deploy another copy of that same stack to the same account.

### Expected Behavior

Applying the option to require IMDSv2 metadata at either the instance level or stack level should not affect the user's ability to launch additional copies of that stack in the same account.

### Current Behavior

Deploying a second stack resulted in errors like this:

```
InstanceLaunchTemplate already exists in stack arn:aws:cloudformation:us-west-2:...
```

### Reproduction Steps

```
const stack1 = new Stack(this, "Stack1")
Aspects.of(stack1).add(new InstanceRequireImdsv2Aspect())

const stack2 = new Stack(this, "Stack2")
Aspects.of(stack2).add(new InstanceRequireImdsv2Aspect())

new Instance(stack1, "Instance1", props)
new Instance(stack2, "Instance2", props)
```

### Possible Solution

Looking at the CloudFormation template synthesized by my app, it looks like adding the IMDSv2 option--whether at the instance level or the stack level--is creating a LaunchTemplate and applying it to the instance. But that launch template is created with a hard-coded name, "InstanceLaunchTemplate" which I cannot find any escape-hatch or other means of modifying for deployment. When another stack is created with the option enabled, it tries to create another LaunchTemplate with the same name, and errors.

### Additional Information/Context

A current workaround that seems serviceable is to create your own LaunchTemplate with the option enabled and apply it to the instance like so:

```
        this.launchTemplate = new LaunchTemplate(this, "LaunchTemplate", {
            requireImdsv2: true
        });

        this.instance = new Instance(this, "Instance", props);

        this.instance.instance.addPropertyOverride("LaunchTemplate", {
            "LaunchTemplateId": this.launchTemplate.launchTemplateId,
            "Version": this.launchTemplate.latestVersionNumber
        })
        this.instance.instance.addDependsOn(this.launchTemplate.node.defaultChild as CfnLaunchTemplate)
```

### CDK CLI Version

2.23.0 (build 50444aa)

### Node.js Version

v16.14.0

### OS

Amazon Linux 2

### Language

Typescript

**Comment by corymhall** [comment]
@aws-painec I think you should be able to solve this by using the
`@aws-cdk/aws-ec2:uniqueImdsv2TemplateName` feature flag.

Add this to your `cdk.json` file:

```json
{
  "context": {
	  "@aws-cdk/aws-ec2:uniqueImdsv2TemplateName": true
	}
}
```

It doesn't look like this feature flag is documented anywhere so I'm going to leave this open to
track the issue of adding docs.

**Comment by GrahamLea** [comment]
Just hit this myself.
I have the problem that after setting the global property CDK wants to rename the launch template of an existing instance, which in turn wants to replace the EC2 instance, which I don't want to do. 😒
Is it still the case that the global flag is the only workaround apart from the explicit launch template demonstrated by the OP?

**Comment by tim-finnigan** [comment]
The feature flag has been added to the documentation here: https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/cx-api/FEATURE_FLAGS.md (accessible from the [Feature flags](https://docs.aws.amazon.com/cdk/v2/guide/featureflags.html) page in the User Guide). For guidance related to using this we recommend creating creating a [discussion](https://github.com/aws/aws-cdk/discussions).
