### ISSUE TITLE
apigateway: ClassCastException

### ISSUE THREAD

**Issue by Dunmord** [aws/aws-cdk#20859]
### Describe the bug

Hi team,

I am working with the Java CDK and when I do the following:

```
private UsagePlan getUsagePlan(final String stage) {
    return (UsagePlan)
        UsagePlan.fromUsagePlanId(this, String.format("DefaultUsagePlan-%s", stage), "v12ejn");
  }
```

I get the error:

```
java.lang.ClassCastException: class software.amazon.awscdk.services.apigateway.IUsagePlan$Jsii$Proxy cannot be cast to class software.amazon.awscdk.serv
ices.apigateway.UsagePlan (software.amazon.awscdk.services.apigateway.IUsagePlan$Jsii$Proxy and software.amazon.awscdk.services.apigateway.UsagePlan are
 in unnamed module of loader 'app')
```

Why is the case not working if its using the interface? And why isn't it able to implicitly figure out the type cast?

Let me know if there are any other questions.

Thanks!

### Expected Behavior

It should be able to do implicit type casting since its using the interface.

### Current Behavior

Throws an exception

```
java.lang.ClassCastException: class software.amazon.awscdk.services.apigateway.IUsagePlan$Jsii$Proxy cannot be cast to class software.amazon.awscdk.serv
ices.apigateway.UsagePlan (software.amazon.awscdk.services.apigateway.IUsagePlan$Jsii$Proxy and software.amazon.awscdk.services.apigateway.UsagePlan are
 in unnamed module of loader 'app')
```

### Reproduction Steps

Just call the UsagePlan.getUsagePlanId method from the Java CDK SDK and try to cast it to a software.amazon.awscdk.services.apigateway.UsagePlan

### CDK CLI Version

2.20.0 (build 738ef49)

### Node.js Version

v14.17.0

### OS

Windows 10

### Language

Java

### Language Version

openjdk 11.0.12 2021-07-20

**Comment by otaviomacedo** [comment]
Because the concrete implementation of `IUsagePlan` returned by `fromUsagePlanId` is not `UsagePlan`. 

Why do you need to type cast at all? Can't you work with `IUsagePlan`?

**Comment by Dunmord** [comment]
Thats odd. In Java interfaces are completely abstract and cannot be used because they don't have methods defined. So you are saying in CDK you made the interfaces not abstract and can be dereferenced directly? Also, why would a method that gets a usage plan not return a usage plan type?

**Comment by peterwoodworth** [comment]
[Imported resources are inherently limited](https://docs.aws.amazon.com/cdk/v2/guide/resources.html#resources_external). If you have more questions, please open a discussion
