### ISSUE TITLE
(neptune): add engine version 1.1.1.0

### ISSUE THREAD

**Issue by adamlbo** [aws/aws-cdk#20869]
### Describe the feature

Add new Neptune engine version 1.1.1.0
https://docs.aws.amazon.com/neptune/latest/userguide/doc-history.html

### Use Case

Support for Gremlin version: 3.5.2

### Proposed Solution

Similar to this PR - https://github.com/aws/aws-cdk/pull/17669

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.29.1

### Environment details (OS name and version, etc.)

macOS

**Comment by jumic** [comment]
Will you add the new version yourself and create a pull request? (You have selected option "I may be able to implement this feature request").

If you want someone else to add the new version, write a short comment here.
