### ISSUE TITLE
deploy: not deploying to hard-coded region in CDK app

### ISSUE THREAD

**Issue by Rabadash8820** [aws/aws-cdk#20880]
### Describe the bug

CDK does not seem to honor hard-coded regions in the `StackProps.env` properties passed to my stacks. 

### Expected Behavior

I could hard-code a region name in the `StackProps.env.region` property passed to my stacks in the CDK app, and `cdk deploy` would deploy the stacks to that region, even when using an AWS CLI profile with a different default region.

### Current Behavior

`cdk deploy` ignores the hard-coded region name in my CDK app, and deploys stacks to the default region of whatever AWS CLI profile I use. Obviously I can set my AWS CLI profile to whatever region I need and deploy stacks by region, but I was hoping to mix hard-coded regions and `process.env.CDK_DEFAULT_REGION` in the same CDK app and deploy with one call to `cdk deploy --all`.

### Reproduction Steps

1. Define the following CDK app in `app.ts`:

    ```ts
    export class DerpStack extends Stack {
        constructor(scope: Construct, id: string, props: StackProps) {
            super(scope, id);

            if (props.env?.region !== "us-east-1")
                throw new Error("Stack must be defined in us-east-1 region.");
        }
    }

    const app = new cdk.App();

    new DerpStack(app, `DerpStack`, {
        env: {
            account: process.env.CDK_DEFAULT_ACCOUNT,
            region: "us-east-1",    // Some resources require this region
        },
        description: `Resources for redirecting the derp domain to the organization website`,
    });
    ```

2. Configure an AWS CLI profile with default region set to something _other_ than `us-east-1` (e.g., `aws --profile <profile> configure get region` should return something other than `us-east-1`).
3. Run `cdk synth --profile <profile> && cdk deploy --profile <profile>`
4. Observe that the custom error message in `DerpStack` is not raised during `cdk synth`, but `DerpStack` is still deployed to the region configured in the AWS CLI profile, rather than the hard-coded `us-east-1`.

### CDK CLI Version

2.29.1

### Node.js Version

16.15.1

### OS

Linux (Debian bullseye)

### Language

Typescript

### Language Version

3.9.7

### Other information

Technically running in a WSL container on Windows 11 Pro

**Comment by nicolai-shape** [comment]
You have to forward the `StackProps` to the `Stack` resource, ie: this `super(scope, id, props)` instead of `super(scope, id)`.

**Comment by Rabadash8820** [comment]
Yep, that was it. Thanks @nicolai-shape, I knew it would be some newb mistake on my end. 😅
