### ISSUE TITLE
import: asks for multiple resource identifiers at once

### ISSUE THREAD

**Issue by Rabadash8820** [aws/aws-cdk#20895]
### Describe the bug

I am trying to use the `cdk import` command to update a CDK-managed stack with existing AWS resources. The stack is for DNSSEC resources for a domain, and I'm trying to import an `AWS::Route53::KeySigningKey`. Unfortunately, the command seems to be asking for two resource identifiers at once, so I am unable to import the KeySigningKey.

### Expected Behavior

Running `cdk import` on a stack with an `AWS::Route53::KeySigningKey` would ask for the `HostedZoneId` and `Name` identifiers of the KeySigningKey one at a time, then importing would succeed.

### Current Behavior

`cdk import` instead gives me this prompt (where `HostedZoneId,Name` is all in blue, like a single identifier):

> (AWS::Route53::KeySigningKey): enter `HostedZoneId,Name` to import (empty to skip):

I've tried providing just the KeySigningKey's `HostedZoneId`, just its `Name`, or both separated by a comma as the prompt suggests. In all cases, the `import` command returns the following error message (where `<StackName>` is the actual name of the CDK stack into which I'm `import`ing):

```log
❌  <StackName> failed: Error [ValidationError]: Invalid resource identifier for resource type AWS::Route53::KeySigningKey. Expected [HostedZoneId, Name]
    at Request.extractError (/usr/local/share/nvm/versions/node/v16.15.1/lib/node_modules/cdk/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/usr/local/share/nvm/versions/node/v16.15.1/lib/node_modules/cdk/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/local/share/nvm/versions/node/v16.15.1/lib/node_modules/cdk/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/local/share/nvm/versions/node/v16.15.1/lib/node_modules/cdk/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/usr/local/share/nvm/versions/node/v16.15.1/lib/node_modules/cdk/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/share/nvm/versions/node/v16.15.1/lib/node_modules/cdk/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/share/nvm/versions/node/v16.15.1/lib/node_modules/cdk/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/share/nvm/versions/node/v16.15.1/lib/node_modules/cdk/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/share/nvm/versions/node/v16.15.1/lib/node_modules/cdk/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/usr/local/share/nvm/versions/node/v16.15.1/lib/node_modules/cdk/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'ValidationError',
  time: 2022-06-28T07:12:59.479Z,
  requestId: '6772576d-59db-4210-a6f9-af7eaf776d38',
  statusCode: 400,
  retryable: false,
  retryDelay: 645.4810660286106
}

Invalid resource identifier for resource type AWS::Route53::KeySigningKey. Expected [HostedZoneId, Name]
```

Adding the `--debug` flag does not provide any additional information.

### Reproduction Steps

1. Provision the following resources in an AWS account:
    - KMS Key set up for DNSSEC
    - Route53 HostedZone with KeySigningKey
3. Define a CDK app with a single, empty stack.
4. Deploy the app with `cdk deploy`
5. Add a KeySigningKey resource to the stack as follows, filling in the `<value>`s:
    ```ts
    new route53.CfnKeySigningKey(this, "KeySigningKey", {
        hostedZoneId: "<hostedZoneId>",
        keyManagementServiceArn: "<keyArn>",
        name: "key_signing_key",
        status: "ACTIVE"
    });
    ```
6. Run `cdk import`
7. Follow the prompts and observe the messages from above

### Additional Information/Context

The CDK logic to ask for resource identifiers for `cdk import` is in [`import.ts`](https://github.com/aws/aws-cdk/blob/74318c7d22bfc00de9e005f68a0a6aaa58c7db39/packages/aws-cdk/lib/import.ts) file. The `resourceIdentifiers` are read from some CloudFormation [GetTemplateSummary](https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_GetTemplateSummary.html) response. Using another stack with KeySigningKeys in my account as an example, I found that the `ResourceIdentifierSummaries` array in the GetTemplateSummary response included this object:

```json
{
    "ResourceType": "AWS::Route53::KeySigningKey",
    "LogicalResourceIds": [
        "KeySigningKey"
    ],
    "ResourceIdentifiers": [
        "HostedZoneId,Name"
    ]
},
```

Note the `HostedZoneId,Name` identifier. I'm not sure if this is a bug with Route53 or what, but it doesn't seem like any resource type should include a comma-delimited identifier in `ResourceIdentifiers`, since that field is already a string array. This may have something to do with the fact that the default `Fn::Ref` return value for a KeySigningKey is an [identifier](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-route53-keysigningkey.html#aws-resource-route53-keysigningkey-return-values) that has the format `<HostedZoneId>|<Name>`. I tried passing a string with this format to `cdk import` but still got the above error message.

### CDK CLI Version

2.29.1 (build c42e961)

### Node.js Version

v16.15.1

### OS

Debian bullseye

### Language

Typescript

### Language Version

3.9.10

### Other information

Technically running Debian in a WSL container on Windows 11 Pro

**Comment by Rabadash8820** [comment]
Awesome, thanks for the workaround @saltman424!

**Comment by peterwoodworth** [comment]
I'm not sure if the bug that's been described here is related to CDK or CDK import - the resource that is getting created here is a Cfn resource, which means it's exactly the same resource that [CloudFormation gives us](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-route53-keysigningkey.html). Since the API call to CloudFormation is what gives us this response, it's likely on CloudFormation's end

I can report this to CloudFormation internally - ping me again tomorrow if I don't update this comment with an internal ticket number
