### ISSUE TITLE
[AWS SSO] SSO credentials expired, but error message saids unable to resolve AWS account

### ISSUE THREAD

**Issue by TiansuYu** [aws/aws-cdk#20896]
### Describe the bug

When trying to deploy stacks through `cdk deploy`, if your local aws sso crendentials has expired, cdk CLI will prompt the following message: 
```
Unable to resolve AWS account to use. It must be either configured when you define your CDK Stack, or through the environment
```
which leads users to debug their CLI configurations (either through `cdk ... --profile xxx` or set env var such as `AWS_PROFILE` and `CDK_DEFAULT_PROFILE`.) But the real issue I had was that my AWS SSO session has expired, I just need to do `aws sso login` again. 

I think this error message is misleading in this situation and needs to be improved. 

### Expected Behavior

When your AWS SSO session has expired, cdk CLI should prompt you with error message such as `The SSO session associated with profile $<some-profile> has expired or is otherwise invalid. To refresh this SSO session run aws sso login with the corresponding profile.`

### Current Behavior

CDK CLI cannot tell the difference between an expired AWS SSO credential and your AWS profile is unset with regard to CDK. 

### Reproduction Steps

Point CDK CLI to an expired AWS SSO profile, and have a local dummy stack definition. Then run `cdk deploy`. 

### CDK CLI Version

2.28.1 (build d035432)

### Node.js Version

18.2.0

### OS

MacOS 12.4

### Language

Typescript

**Comment by peterwoodworth** [comment]
Thanks for submitting this, we accept contributions! Check out our [contributing guide](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) if you're interested - there's a low chance the team will be able to address this soon but we'd be happy to review a PR 🙂

**Comment by TiansuYu** [comment]
I am not a typescript expert but will take a look and see what I can do about it.

**Comment by TheRealAmazonKendra** [comment]
We will improve this error message as a part of https://github.com/aws/aws-cdk/pull/31702

**Comment by TheRealAmazonKendra** [comment]
From the testing I've done, this error message is now clear when these credentials have expired.
