### ISSUE TITLE
all: Link to source code is broken

### ISSUE THREAD

**Issue by jonnekaunisto** [aws/aws-cdk#20891]
### Describe the issue

One the documentation page there is a link to view the source: [example](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda.Function.html).

This link for the v2 documentation is wrong as it points to: [https://github.com/aws/aws-cdk/blob/v2.29.1/packages/@aws-cdk-lib/aws-lambda/lib/function.ts#L394](https://github.com/aws/aws-cdk/blob/v2.29.1/packages/@aws-cdk-lib/aws-lambda/lib/function.ts#L394)

When in reality the page is at: [https://github.com/aws/aws-cdk/blob/v2.29.1/packages/%40aws-cdk/aws-lambda/lib/function.ts#L394](https://github.com/aws/aws-cdk/blob/v2.29.1/packages/%40aws-cdk/aws-lambda/lib/function.ts#L394)

### Links

All

**Comment by peterwoodworth** [comment]
Thanks for reporting this @jonnekaunisto,

We're already aware of this and tracking it [here](https://github.com/aws/aws-cdk/issues/18438) It's something we're going to fix eventually, but isn't super high priority right now
