### ISSUE TITLE
aws-ecs: used python version 3.6 for drain-hook is end of support

### ISSUE THREAD

**Issue by froxart** [aws/aws-cdk#20902]
Community Note

> Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
> 
> Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
> 
> If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Describe the feature

The used version of Python 3.6 in the [Autoscaling / instance-drain-hook.ts](https://github.com/aws/aws-cdk/blob/a7d314c73b9473208d94bac29ad9bd8018e00204/packages/%40aws-cdk/aws-ecs/lib/drain-hook/instance-drain-hook.ts#L70) is end of support since [may 2022](https://aws.amazon.com/de/blogs/developer/python-support-policy-updates-for-aws-sdks-and-tools/) and should be upgraded as soon as possible to a newer version.

Maybe >= 3.8, because 3.7 will be end of support next year too.

> AWS Blog Post: On May 30, 2022, the AWS SDK for Python (Boto3 and Botocore) and the AWS Command Line Interface (AWS CLI) v1 will no longer support Python 3.6.

**Comment by indrora** [comment]
Looks like there's nothing in that lambda handler that would be hurt by moving it to the latest version.

**Comment by froxart** [comment]
That's correct, updating to the v2.28.0 was fixing the issue for us.
