### ISSUE TITLE
(aws-ec2): Missing instance type classes

### ISSUE THREAD

**Issue by TokyoQ** [aws/aws-cdk#20924]
### Describe the feature

The following instance types aren't currently supported:

- m6gd
- m6id
- c7g
- c6id
- r6id
- u-3tb1
- p4de (still in preview)
- p3dn
- dl1
- g3s

### Use Case

We use some of the missing instance types, specifically ones with attached instance storage.

### Proposed Solution

Add the missing types to the list.

### Other Information

Taken list from https://aws.amazon.com/ec2/instance-types

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.29.1 (build c42e961)

### Environment details (OS name and version, etc.)

MacOS

**Comment by corymhall** [comment]
@TokyoQ Thanks for bringing these up as missing! Until these are added to the InstanceClass enum,
they can be used by doing:

```ts
new InstanceType('m6gd.large');
```

This issue has been classified as *p2*. That means a workaround is available or it is deemed a nice-to-have feature. Given the amount of work there is to do and the relative priority of this issue, the CDK team is unlikely to address it. That does not mean the issue will never be fixed! If someone from the community submits a PR to fix this issue, and the PR is small and straightforward enough, and meets the quality bars to be reviewed and merged with little effort we will accept that PR. PRs that do not build or need complex or multiple rounds of reviews are unlikely to be merged and will be closed to keep our backlog manageable. 

In the mean time, remember that you can always use the escape hatch (https://docs.aws.amazon.com/cdk/v2/guide/cfn_layer.html) mechanism to have fine control over the CloudFormation output you want. We will keep the issue open for discoverability, to collect upvotes, and to facilitate discussion around this topic.

We use +1s *on this issue* to help prioritize our work, and are happy to re-evaluate the prioritization of this issue based on community feedback. You can reach out to the cdk.dev community on Slack (https://cdk.dev/) to solicit support for reprioritization.

**Comment by jumic** [comment]
The following instance type classes already exists, no action is necessary:
- [m6gd](https://github.com/aws/aws-cdk/blob/6b4f92f2437c7ff782c88ce23925a04168728d7c/packages/%40aws-cdk/aws-ec2/lib/instance-types.ts#L754)
- [c7g](https://github.com/aws/aws-cdk/blob/6b4f92f2437c7ff782c88ce23925a04168728d7c/packages/%40aws-cdk/aws-ec2/lib/instance-types.ts#L379)

I will submit a PR for the following instance classes:
- u-3tb1
- m6id
- c6id
- r6id
- p3dn
- dl1
- g3s

Open (because in preview) - must be added later:
- p4de (still in preview)

**Comment by daschaa** [comment]
@jumic Can this issue be closed for now? :)

**Comment by jumic** [comment]
@corymhall Instance type p4de from the initial list is still open because it is in developer preview. Should we keep this PR? Or should we close it? @TokyoQ Can open a new feature request when the instance type will be released.

**Comment by corymhall** [comment]
@jumic I think I'm fine with adding instance types that are in developer preview. I think we can just note that as part of the docstring.
