### ISSUE TITLE
@aws-cdk/aws-appsync-alpha: Enhanced subscription filter not working anymore

### ISSUE THREAD

**Issue by SchollSimon** [aws/aws-cdk#20926]
### Describe the bug

After AWS released this blog post
https://docs.aws.amazon.com/appsync/latest/devguide/aws-appsync-real-time-enhanced-filtering.html

we implemented the enhanced server side filters they were working now they are not anymore. After that we implement the sample from the blogpost, this also not working anymore. (I don't know if something flipped through qa on AWS side)

Our application includes a mutation which looks like that
```
mutation MyMutation {
  onArticleUpdateMutation(input: {userId: "f1090929-8937-4551-9421-8fbdb08f3489", pk1: "Article#7a5d8549-188c-4049-822b-cf3bc3b05a99", name: "Test subscription filter", id: "7a5d8549-188c-4049-822b-cf3bc3b05a99#10c948d0-b899-4ff5-98e1-fb4f4a1b6f9f#478b007b-bc70-430f-9658-6b240a412762_v0"}) {
    pk1
    userId
    id
    name
  }
}
```

And a subscription which looks like that
```
subscription MySubscription {
  onArticleUpdate(pk1: "Article#7a5d8549-188c-4049-822b-cf3bc3b05a99", userId: "f1090929-8937-4551-9421-8fbdb08f3489") {
    pk1
    userId
    id
    name
  }
}
```

Both use a local resolver with a NoneDataSource, the subscription response mapping template looks like:
```
$extensions.setSubscriptionFilter({
    "filterGroup": [
        {
           "filters" : [
                {
                    "fieldName" : "id",
                    "operator" : "beginsWith",
                    "value" : "7a5d8549-188c-4049-822b-cf3bc3b05a99"
                }
           ]
        }
    ]
})
$util.toJson($context.result)
```

### Expected Behavior

SubsciptionFilters applied in the vtl response template should be applied before returning data via ws connection.

### Current Behavior

The subscription filter is ignored, the whole response mapping template is neither evaluated when using/activating the subscription neither when data is returned.

### Reproduction Steps

Try the sample from blogpost
https://docs.aws.amazon.com/appsync/latest/devguide/aws-appsync-real-time-enhanced-filtering.html

### CDK CLI Version

2.29.1

### Framework Version

2.29.1

### Node.js Version

v16.13.1

### OS

Windows

### Language

Typescript

### Language Version

TypeScript (4.5.4)

**Comment by otaviomacedo** [comment]
Hi, @SchollSimon. Without more information, it's hard for me to tell whether this is a problem with the CDK (an incorrectly generated template) or with CloudFormation/Appsync control plane. Can you please share the template you're deploying (look for a `*.template.json` in `cdk.out`).

**Comment by SchollSimon** [comment]
@otaviomacedo  Thank you for your response, i can not provide the file out of several reasons, it contains confidental information and contains around 3000 lines mostly not related to this specific issues, so i think this will add no benefit. 

I provided everything for you so you can test the AWS sample yourself within 5 minutes. I described we use local none datasource resolvers, and the only specific non template based vtl syntax is the one i mentioned above. You can test the minimum sample from the blog post with the subscription and mutation i provided.

For us this looks like a service related issue

**Comment by SchollSimon** [comment]
I can shed some light the issue we experienced after talking 4 weeks with AWS support, they finally came up with the solution 

>  Looking at the resolver mapping template for the subscription is
> 
> { 
> "version": "2017-02-28"
> }
> 
> Can you please change to the following: 
> 
> {
>     "version": "2017-02-28",
>     "payload": {}
> }

I don't want to judge, but it worked without the payload property before and it was/is not mentioned in any related documentation that this can cause errors like this.

The ticket can be closed, sry for the salt.
