### ISSUE TITLE
(api-gateway): allow configuration of deployment description

### ISSUE THREAD

**Issue by rix0rrr** [aws/aws-cdk#20934]
### Describe the feature

Currently, the above is not possible as the text is hardcoded here https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-apigateway/lib/restapi.ts#L557

### Use Case

Customer has a pipeline that deploys an api gateway holding multiple resources. They would like to be able to set the description (check the attached screenshot) per deployment. From inside their pipeline, they could get the commit hash / commit message, timestamp, custom text, and other git-related metadata that they would like to set as description. 

### Proposed Solution

Make description configurable

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

-

### Environment details (OS name and version, etc.)

-

**Comment by josephedward** [comment]
@peterwoodworth  I started working on this (https://github.com/aws/aws-cdk/pull/21207), but I wasn't sure where to edit a test - `_configureDeployment` and `RestApiBaseProps` do not seem to be present in the /test folder in aws-cdk/packages/@aws-cdk/aws-apigateway ?
