### ISSUE TITLE
custom-resources: AwsCustomResource error in Lambda API call does not cause a "FAILED" response in CloudFormation

### ISSUE THREAD

**Issue by Sevi7** [aws/aws-cdk#20933]
### Describe the bug

AwsCustomResource implementing an AwsSdkCall to Lambda Service invoke action. If the lambda function throws an error, it does not cause a "FAILED" response to be submitted to CloudFormation and the deployment continues and it is successful.

### Expected Behavior

A "FAILED" response in CloudFormation so the deployment fails.

### Current Behavior

You can see that the response of the lambda function is an error and the deployment was still successful. 
```
 ✅  RdsInitExample

✨  Deployment time: 98.78s

Outputs:
RdsInitExample.RdsInitFnResponse = {"status":"ERROR","err":{},"message":"hola is not defined"}
Stack ARN:
[...]

✨  Total time: 102.34s
```
Also, the [aws-sample](https://github.com/aws-samples/amazon-rds-init-cdk) is following a special format for the error response that I think it is not documented. And it may be contradictory to the [docs](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.custom_resources-readme.html#handling-custom-resource-errors) that mentions it needs an error and in the example we are catching it, so no error is thrown. I tried also without catching the error and the deployment was still successful.

### Reproduction Steps

The aws-sample itself after introducing some code that produces an error.
https://github.com/aws-samples/amazon-rds-init-cdk

### Possible Solution

An error thrown by the lambda function should cause a "FAILED" response in CloudFormation. If a special response format is needed, it should be well documented and easily accessible.

### CDK CLI Version

1.161.0 and 2.29.1

### Node.js Version

v14.19.0 and v16.15.1

### OS

macOS 12.4

### Language

Typescript

**Comment by rix0rrr** [comment]
So far this looks to me like a bug in https://github.com/aws-samples/amazon-rds-init-cdk, and should be reported there.

If you think this is a bug in the CDK, please produce a reproducing sample that involves just the CDK, not a 3rd-party construct.

Also please note that `AwsCustomResource` just calls `lambda:Invoke`, and the documentation for `Invoke` says that an error inside the called function does not lead the call to `Invoke` to fail (as in, `Invoke` successfully calls a function that happens to fail):

> The status code in the API response doesn't reflect function errors. Error codes are reserved for errors that prevent your function from executing,

https://docs.aws.amazon.com/lambda/latest/dg/API_Invoke.html

**Comment by mccauleyp** [comment]
> So far this looks to me like a bug in https://github.com/aws-samples/amazon-rds-init-cdk, and should be reported there.
> 
> If you think this is a bug in the CDK, please produce a reproducing sample that involves just the CDK, not a 3rd-party construct.
> 
> Also please note that `AwsCustomResource` just calls `lambda:Invoke`, and the documentation for `Invoke` says that an error inside the called function does not lead the call to `Invoke` to fail (as in, `Invoke` successfully calls a function that happens to fail):
> 
> > The status code in the API response doesn't reflect function errors. Error codes are reserved for errors that prevent your function from executing,
> 
> https://docs.aws.amazon.com/lambda/latest/dg/API_Invoke.html

@rix0rrr Is it possible to fail the `AwsCustomResource` create/update operation if the Lambda invocation response indicates an error? I stumbled on this thread because I'm trying to make that happen for an unrelated reason. I see lots of examples on how to use custom resources to invoke Lambdas, but I'm not seeing any that discuss what happens if the invocation succeeds but the response is a failure (and thus you might want the deployment to fail).

**Comment by deleugpn** [comment]
I'm currently facing something similar here. My Lambda is being invoked synchronously and it fails. I wish the AWS Custom Resource would fail because of that

**Comment by Sevi7** [comment]
I could manage to make the deployment fail if the lambda function throws an error using [Provider framework](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.custom_resources-readme.html#provider-frameworkl) (Lambda Function + Provider + CustomResource) instead of AwsCustomResource

**Comment by manmartgarc** [comment]
Same boat here. Is it not possible to inspect the response from `Invoke` at build time? I see it being logged by the custom resource.

**Comment by manmartgarc** [comment]
The solution is to use a [CustomResource](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.CustomResource.html) (note it being different from a [AwsCustomResource](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.custom_resources.AwsCustomResource.html). On top of this, the Lambda itself has to respond via [cfnresponse](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-lambda-function-code-cfnresponsemodule.html) depending on the response status, the build will fail.
