### ISSUE TITLE
fix: Make DnsValidatedCertificate cross-region with additional prop

### ISSUE THREAD

**Issue by sthulb** [aws/aws-cdk#2095]
CDK currently has a custom resource to create new ACM certs, but ACM is only available in one region.

DnsValidatedCertificate should be a cross region call, made optional though props

**Comment by otterley** [comment]
ACM is, in fact, a regional service that is available in many supported regions.  However, for certain purposes such as associating certificates with CloudFormation distributions, one must provision the certificate in the [us-east-1 region](https://docs.aws.amazon.com/acm/latest/userguide/acm-regions.html).
