### ISSUE TITLE
aws-codebuild: Support for Standard (6.0) and Amazon Linux (4.0) images

### ISSUE THREAD

**Issue by mikelhamer** [aws/aws-cdk#20960]
### Describe the feature

AWS CodeBuild Standard (6.0) and Amazon Linux (4.0) images are now available with this release
https://github.com/aws/aws-codebuild-docker-images/releases/tag/22.06.30

### Use Case

To use the latest versions of Code Build Standard and Amazon Linux

### Proposed Solution

Make the following IBuildImage properties available in LinuxBuildImage

STANDARD_6_0
AMAZON_LINUX_2_4 

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.3.0

### Environment details (OS name and version, etc.)

Linux

**Comment by npvisual** [comment]
@daschaa / @mikelhamer : is it possible to get this for CDK v1 ? I am looking at 1.169.0 and STANDARD_6_0 isn't available there.

**Comment by daschaa** [comment]
@npvisual As far as I know CDK v1 is in maintenance mode since June 2022. I doubt that there will be updates for v1. But that's a question for a member of the AWS Team.
@TheRealAmazonKendra @peterwoodworth
