### ISSUE TITLE
aws-cdk: init python is not working

### ISSUE THREAD

**Issue by Rukeith** [aws/aws-cdk#20967]
### Describe the bug

I just generate a init python cdk template and run the commands from README, but it's not working at all.

### Expected Behavior

Synthesize the CloudFormation template from the init code from CDK

### Current Behavior

Got this error message

```
Traceback (most recent call last):
  File "/project/aws-cdk/app.py", line 6, in <module>
    from aws_cdk.aws_cdk_stack import AwsCdkStack
  File "/project/aws-cdk/aws_cdk/aws_cdk_stack.py", line 1, in <module>
    from aws_cdk import (
ImportError: cannot import name 'Stack' from 'aws_cdk' (/project/aws-cdk/aws_cdk/__init__.py)

Subprocess exited with error 1
```

### Reproduction Steps

1. Run `cdk init --language python` in an empty folder
2. Run `source .venv/bin/activate` to go into virtual environment
3. Run `pip install -r requirements.txt` to install packages
4. Run `cdk synth` to generate Cloud formation, but this step got error like this

### Possible Solution

The folder name is the same as the CDK python package naming. It makes python get the wrong folder. So I changed the folder name which CDK generates, then it was fixed.
I think the `cdk init` should fix this.

### CDK CLI Version

2.30.0

### Node.js Version

18.4.0

### OS

macOS 12.4

### Language

Python

### Language Version

Python (3.10)

**Comment by jashgala** [comment]
I tried reproducing this issue with Python v3.9.13 and Node v18.4.0 and CDK CLI v2.30.0, but the CLI seems to be working fine and it synthesizes the Cloudformation template as expected.

Will try to see if I can reproduce with Python 3.10.

**Comment by jashgala** [comment]
Unable to reproduce this with Python v3.10 as well. Did you try running these instructions in a fresh new directory?

**Comment by Rukeith** [comment]
@jashgala Yes, this is my first time using CDK. In an empty folder initial this.

**Comment by jashgala** [comment]
I believe you are right, when I initialize the Python CDK inside a folder named "aws-cdk" it results in the same failure like the one that you mentioned.

**Comment by MrArnoldPalmer** [comment]
Yeah this is essentially a naming collision as the local python module being named the same as the aws_cdk package prevents you from correctly importing without aliasing the dependency to something else. I'm not sure if there is a simple workaround if you really wanted to name your python package `aws_cdk` (like aliasing the dependency to something else) but for now using a different directory/package name is the best solution.

ty @jashgala !
