### ISSUE TITLE
pipelines: 'Prepare' is not available in region 'CN_NORTH_1'

### ISSUE THREAD

**Issue by Hephyr** [aws/aws-cdk#20987]
### Describe the bug

I'm using [CDK Piepeline](about:blankCDK%20Piepeline) to create a self-mutating CodePipeline in BJS, I flow [this blog](https://aws.amazon.com/blogs/developer/cdk-pipelines-continuous-delivery-for-aws-cdk-applications/) to create it and works in global region. But when I deploy it in BJS  it raise error `ActionType (Category: 'Deploy', Provider: 'CloudFormation', Owner: 'AWS', Version: '1') in action 'Prepare' is not available in region 'CN_NORTH_1' (Service ` . It seems like CN CodePipeline not support deploy CloudFormation.

### Expected Behavior

Deploy success as same as global region.

### Current Behavior

`cdk deploy` output
```
CdkpipelinesDemoPipelineStack: creating CloudFormation changeset...
21:39:47 | UPDATE_FAILED        | AWS::CodePipeline::Pipeline | Pipeline9850B417
ActionType (Category: 'Deploy', Provider: 'CloudFormation', Owner: 'AWS', Version: '1') in action 'Prepare' is not available in region 'CN_NORTH_1' (Service
: AWSCodePipeline; Status Code: 400; Error Code: InvalidActionDeclarationException; Request ID: 5deeb8e4-c7a7-49ef-bb07-368c0fedd328; Proxy: null)


 ❌  CdkpipelinesDemoPipelineStack failed: Error: The stack named CdkpipelinesDemoPipelineStack failed to deploy: UPDATE_ROLLBACK_COMPLETE: ActionType (Category: 'Deploy', Provider: 'CloudFormation', Owner: 'AWS', Version: '1') in action 'Prepare' is not available in region 'CN_NORTH_1' (Service: AWSCodePipeline; Status Code: 400; Error Code: InvalidActionDeclarationException; Request ID: 5deeb8e4-c7a7-49ef-bb07-368c0fedd328; Proxy: null)
    at prepareAndExecuteChangeSet (/Users/x/.nvm/versions/node/v16.14.0/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:385:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at CdkToolkit.deploy (/Users/x/.nvm/versions/node/v16.14.0/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:209:24)
    at initCommandLine (/Users/x/.nvm/versions/node/v16.14.0/lib/node_modules/aws-cdk/lib/cli.ts:341:12)

The stack named CdkpipelinesDemoPipelineStack failed to deploy: UPDATE_ROLLBACK_COMPLETE: ActionType (Category: 'Deploy', Provider: 'CloudFormation', Owner: 'AWS', Version: '1') in action 'Prepare' is not available in region 'CN_NORTH_1' (Service: AWSCodePipeline; Status Code: 400; Error Code: InvalidActionDeclarationException; Request ID: 5deeb8e4-c7a7-49ef-bb07-368c0fedd328; Proxy: null)
```

### Reproduction Steps

I used the code in the [aws official blog](https://aws.amazon.com/blogs/developer/cdk-pipelines-continuous-delivery-for-aws-cdk-applications/). Only changed the region to `cn-north-1`.
``` typescript
export class CdkpipelinesDemoPipelineStack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);

    const repo = new codecommit.Repository(this, "Repository", {
      repositoryName: "cdkpipelines-demo",
    });

    const pipeline = new CodePipeline(this, "Pipeline", {
      // The pipeline name
      pipelineName: "MyServicePipeline",

      // How it will be built and synthesized
      synth: new ShellStep("Synth", {
        // Where the source can be found
        input: CodePipelineSource.codeCommit(repo, "master"),

        // Install dependencies, build and run cdk synth
        commands: ["npm ci", "npm run build", "npx cdk synth"],
      }),
    });

    pipeline.addStage(
      new CdkpipelinesDemoStage(this, "Dev", {
        env: { account: "123456789123", region: "cn-north-1" },
      })
    );
  }
}
```

### CDK CLI Version

2.30.0

### Node.js Version

v16.14.0

### OS

macOS 12.3.1

### Language

Typescript

**Comment by peterwoodworth** [comment]
I'm sorry you're running into this issue @Hephyr,

Unfortunately this isn't something we can handle, since we depend on the underlying services, like CloudFormation and CodePipeline. If you need support for this in this region, you could ask AWS support if you have it, or you could potentially find an answer on the [CloudFormation Coverage Roadmap](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues), though I'm not sure that would lead anywhere if the responsibility for supporting this region is on CodePipeline

**Comment by YuechenLuo** [comment]
Hi, I'm running into the same issue.
Found this post: https://www.amazonaws.cn/en/new/2022/amazon-codepipeline-available-china-regions/ saying codepipeline is available in China (Beijing region) now.
Wondering if there's a fix for that if the document is accurate?

**Comment by peterwoodworth** [comment]
Since this is a service blocked issue, there's no action we can take here on CDK's end.
