### ISSUE TITLE
elasticloadbalancingv2: ApplicationListener.fromLookup is inconsistent with docs

### ISSUE THREAD

**Issue by michailw** [aws/aws-cdk#20996]
### Describe the bug

I'm using the example too lokup for ALB Listener:
https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationListenerLookupOptions.html

It contains such a payload:
```
{
  loadBalancerArn: 'arn:aws:elasticloadbalancing:us-east-2:123456789012:loadbalancer/app/my-load-balancer/1234567890123456',
  listenerProtocol: elbv2.ApplicationProtocol.HTTPS,
  listenerPort: 443,
}
```

Unfortunately, it's restricted by the code:
https://github.com/aws/aws-cdk/blob/v2-release/packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-listener.ts#L137-L140
```
if (Token.isUnresolved(options.listenerArn)) {
  throw new Error('All arguments to look up a load balancer listener must be concrete (no Tokens)');
}
```

I'm pushed to set `listenerArn`, although contract says it's optional.

### Expected Behavior

I should be able to lookup without specifying listenerArn

### Current Behavior

CDK throws exception: `'All arguments to look up a load balancer listener must be concrete (no Tokens)'`

### Reproduction Steps

Try to lookup for any ALB Listener without specifying `listenerArn`

### Possible Solution

Please make `listenerArn` optional, as it stands in docs.

### CDK CLI Version

2.30

### Node.js Version

17

### OS

MacOS

### Language

Typescript

### Language Version

3.9.7

**Comment by gshpychka** [comment]
> I'm pushed to set listenerArn, although contract says it's optional.

I don't think that's true. The issue is that one of the value you're supplying is a deploy-time token, not a concrete value that's available at synth-time.

**Comment by peterwoodworth** [comment]
We don't require this property @michailw, as said above you're likely supplying a deploy-time token. This method is working fine for me without declaring the listenerArn.

Please share a reproducible sample, that will help us figure out what's going wrong 🙂

**Comment by napalm684** [comment]
I would like to advocate re-opening this issue. I am providing a value from a CloudFormation output on another stack and it is unable to resolve the string of the load balancer arn to lookup the actual resource using the `fromLookup()` method.

**Comment by andershal** [comment]
Experiencing the same as the original poster, trying to use example from https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationListenerLookupOptions.html but doesn't get pass the https://github.com/aws/aws-cdk/blob/v2-release/packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-listener.ts#L137-L140 check either.

@michailw did you find a solution?
