### ISSUE TITLE
Inline node.js Lambda documentation should mention 3rd party dependency constraints

### ISSUE THREAD

**Issue by rclark** [aws/aws-cdk#210]
It would be a good idea for the documentation to make it clear that when you use the inline lambda construct, you still can't `require()` 3rd party modules that aren't automatically included in the Lambda nodejs runtime. 

That would be some pretty cool ✨magic ✨ if you could (CDK would have to traverse the require tree and bundle your dependencies into the string some such craziness), but for now I think its just worth mentioning the constraint.

**Comment by sadhikay** [comment]
Any update on this?
