### ISSUE TITLE
(cli): tags with an equals sign in the value only use the value of the string prior to the equals sign

### ISSUE THREAD

**Issue by peterwoodworth** [aws/aws-cdk#21003]
### Describe the bug

If you need a tag with a key value pair such as

Key : MyKey
Value : MyValue=Something

The stack will have a key value pair that shows

Key: MyKey
Value: MyValue

### Expected Behavior

I would expect the value of the tag to be MyValue=Something

### Current Behavior

Doesn't read the full tag value

### Reproduction Steps

Try to create a stack with a tag that has an equals sign in the value

### Possible Solution

The code which parses tags in the command line will split when it sees an equals sign, and will only use the second split value as the tag value, when it should be everything after the first split

https://github.com/aws/aws-cdk/blob/a7e3eab8f96f896f4f72bf4b14a366e9953a86e7/packages/aws-cdk/lib/settings.ts#L327-L348

### CDK CLI Version

.

### Node.js Version

.

### OS

.

### Language

Typescript

**Comment by nvcaine** [comment]
Hi Peter,

I encountered the same problem while attempting to tag the resources created in the bootstrapping phase of the deployment process, specifically the S3 bucket created by CDK prior to actually deploying the stack(s).

Here is a workaround:

First, a custom name is used for the bootstrap the bucket. That can be done with the following command:

`cdk bootstrap aws://{ACCOUNT}/{REGION} --toolkit-bucket-name {CUSTOM BUCKET NAME}`

Now that the bucket has a name, its ARN can be determined. Finally the AWS `resourcegroupstaggingapi` can be used to tag resources:

`aws resourcegroupstaggingapi tag-resources --cli-input-json file://{PATH TO TAGS FILE}.json --region {REGION}`

We found the most convenient way is to use a JSON file with the following structure:
```
{
    "ResourceARNList": ["arn:aws:s3:::{CUSTOM BUCKET NAME}"],
    "Tags": {
        "{TAG KEY}": "{SOME FIELD}={SOME VALUE}",
        ...
    }
}
```

This approach works for preserving values which contain `=`, but you have to do the bootstrapping phase in two steps.

Have a good day,
Romi

**Comment by yaki3355** [comment]
Hey,

why my pr #21059 failed?

**Comment by seungholee-dev** [comment]
Hi, @peterwoodworth 
I am a new contributor to this project and can I try working on this?
