### ISSUE TITLE
aws_wafv2.CfnLoggingConfiguration: Error when trying to deploy logging config pointed to S3 bucket

### ISSUE THREAD

**Issue by jordanivy** [aws/aws-cdk#21015]
### Describe the bug

Hi AWS CDK team,

I am currently trying to deploy the **aws_wafv2.CfnLoggingConfiguration** construct in my CDK project with the logDestinationConfigs property set to an S3 bucket ARN.

Here is what my code looks like:
```
new CfnLoggingConfiguration(this, "LoggingConfiguration", {
  logDestinationConfigs: [props.logsBucket.s3Bucket.bucketArn],
  resourceArn: webAcl.attrArn,
});

```

On the deployment step of the stack that this resource is associated with, the following error is received:

`Error reason: The ARN isn't valid. A valid ARN begins with arn: and includes other information separated by colons or slashes., field: LOG_DESTINATION, parameter: arn:aws:s3:::<bucket-name> (Service: Wafv2, Status Code: 400...`

I have removed the bucketName for security reasons and replaced with <bucket-name> above. We have verified that the bucket included in this resource does exist and that the ARN that is being reported as "invalid" exists and is correct in the account where this resource is being deployed.

### Expected Behavior

Per the documentation which indicates that an S3 bucket ARN is a valid logging destination, we expect for this resource to deploy successfully and not report any errors since the ARN for the bucket is valid.

### Current Behavior

On the deployment step of the stack that this resource is associated with, the following error is received:

`Error reason: The ARN isn't valid. A valid ARN begins with arn: and includes other information separated by colons or slashes., field: LOG_DESTINATION, parameter: arn:aws:s3:::<bucket-name> (Service: Wafv2, Status Code: 400...`

### Reproduction Steps

```
new CfnLoggingConfiguration(this, "LoggingConfiguration", {
  logDestinationConfigs: [props.logsBucket.s3Bucket.bucketArn],
  resourceArn: webAcl.attrArn,
});

```

### Additional Information/Context

The bucket is being passed in as a property of the stack and that resource is created in another stack. The stack which requires this bucket is set to depend on the stack where the bucket is created.

### CDK CLI Version

2.28.0

### Node.js Version

16.14.0

### OS

Linux

### Language

Typescript

### Language Version

TypeScript 3.9.7

### Other information

[Documentation for waf_v2.CfnLoggingConfiguration](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_wafv2.CfnLoggingConfiguration.html)

**Comment by peterwoodworth** [comment]
Could you share the part of your template where the bucket arn should be appearing? You can modify the data such that it doesn't reveal any confidential information

**Comment by jordanivy** [comment]
Hi Peter (@peterwoodworth),

Thanks for the fast response. One of my teammates was able to identify the issue in another piece of documentation provided by AWS:

[Amazon Simple Storage Service: Naming requirements and syntax](https://docs.aws.amazon.com/waf/latest/developerguide/logging-s3.html#logging-s3-naming)

We needed to add 'aws-waf-logs-' to the front of our S3 bucket name for it to work as expected.

It looks like there is a similar requirement for the log groups: 

[Amazon CloudWatch Logs: Log group naming](https://docs.aws.amazon.com/waf/latest/developerguide/logging-cw-logs.html#logging-cw-logs-naming)

If possible, could this please be moved to a **Documentation Update** request for the [waf_v2.CfnLoggingConfiguration page](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_wafv2.CfnLoggingConfiguration.html)? I think it would be beneficial if this explicit requirement was called out in the [property section for logDestinationConfigs](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_wafv2.CfnLoggingConfiguration.html#logdestinationconfigs).

We really appreciate all of the hard work the AWS CDK team is putting into this product!

**Comment by peterwoodworth** [comment]
Our L1 constructs are actually autogenerated, as well as our documentation for them. They're actually exact copies of CloudFormation resources!

If you have any docs suggestions, I would recommend using the "Provide Feedback" button on the relevant CloudFormation docs page https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-wafv2-loggingconfiguration.html. The docs changes will then be propagated to CDK once CFN has made the changes
