### ISSUE TITLE
(aws-cdk-lib.aws_ecs_patterns): "Set capacityProviderStrategies for QueueProcessingEc2Service" shows a snippet of QueueProcessingFargateService

### ISSUE THREAD

**Issue by its-mirus-lu** [aws/aws-cdk#21027]
### Describe the issue

Navigate to the following section https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ecs_patterns-readme.html#set-capacityproviderstrategies-for-queueprocessingec2service

... and you'll find the heading **Set capacityProviderStrategies for QueueProcessingEc2Service** ...

... the example is clearly for configuring a **QueueProcessingFargateService**

### Links

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ecs_patterns-readme.html#set-capacityproviderstrategies-for-queueprocessingec2service

**Comment by peterwoodworth** [comment]
Thanks for reporting this @its-mirus-lu,

This should be a pretty simple fix. Open for anyone to take! Check out our [Contributing guide](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) for info on how to contribute 🙂
