### ISSUE TITLE
(stepfunctions-tasks): support parameters in StepFunctionsInvokeActivity

### ISSUE THREAD

**Issue by eiva** [aws/aws-cdk#21020]
### Describe the bug

You already closed same ticket in CDK1 and probably because of this ignorance to customer pain never added it to v2.

Here is a ticket: https://github.com/aws/aws-cdk/issues/1480

It is not even feature request - it is already a bug in cdk 2 as with dropping arbitrary Task class you actually made impossible to have this parameter specified for Activities.

I know that this ticket will be auto closed as many others as usual.

But this is a nonsense. 

Or at least spent some of your time to provide workaround if supporting something what here for years is too hard for the CDK team.

### Expected Behavior

software.amazon.awscdk.services.stepfunctions.tasks.StepFunctionsInvokeActivity should have parameters.

### Current Behavior

software.amazon.awscdk.services.stepfunctions.tasks.StepFunctionsInvokeActivity does not have parameters

Task is deprecated. You make things impossible for migration.

### Reproduction Steps

It is not even required to run anything.

Just go and try to use parameters for software.amazon.awscdk.services.stepfunctions.tasks.StepFunctionsInvokeActivity

### Possible Solution

Will really appreciate if you provide any.

### CDK CLI Version

2

### Node.js Version

16

### OS

linux

### Language

Typescript

**Comment by kaizencc** [comment]
There is always a `CustomState` where you can drop down into raw json and provide whatever you want:

https://github.com/aws/aws-cdk/blob/main/packages/@aws-cdk/aws-stepfunctions/README.md#custom-state

There is no regression here. Repurposing this issue as a feature request.

**Comment by dlegezo** [comment]
There is a dramatic difference between State and Task in V1:
When you used task there was an ability to create instance and than you still able to get metrics, addCatch, addNext and so on.
With State class you suggest - this all is impossible so the only way that you need to assemble all state machines in completely different way. When you have dozens of SFs with many-many activities it become impossible as will require to re-implement this all from scratch. Literally if this is not a regression in system - I dont know how to call it.

And it is not a feature. You should being use base interface for all things derived from task to not miss such things and still leave ability to interact with generated json for tasks as well rather creating huge amount of specific tasks with no proper class hierarchy.

**Comment by kaizencc** [comment]
You can always extend `TaskStateBase` yourself if you want to use the methods associated with it:

```ts
import { Stack, StackProps } from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as iam from 'aws-cdk-lib/aws-iam';
import * as sfn from 'aws-cdk-lib/aws-stepfunctions';

export class CustomStack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);

    const task = new CustomTask(this, 'id', {});
    task.addCatch(new sfn.Fail(this, 'fail'));
    const machine = new sfn.StateMachine(this, 'machine', {
      definition: task.next(new sfn.Succeed(this, 'success')),
    });
  }
}

interface CustomProps extends sfn.TaskStateBaseProps {}

class CustomTask extends sfn.TaskStateBase {
  protected readonly taskMetrics?: sfn.TaskMetricsConfig;
  protected readonly taskPolicies?: iam.PolicyStatement[];
  
  constructor(scope: Construct, id: string, private readonly props: CustomProps) {
    super(scope, id, props);
  }
  
  protected _renderTask(): any {
    return {};
  }
}
```
