### ISSUE TITLE
[aws-elasticloadbalancingv2]: ApplicationLoadBalancer deployment fails when adding ApplicationListener

### ISSUE THREAD

**Issue by tuipopenoe** [aws/aws-cdk#21048]
### Describe the bug

Creating an ApplicationLoadBalancer and then adding an ApplicationListener as described in the documentation fails as instantiating a new `ApplicationLoadBalancer` creates a default ApplicationListener on port 80

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationLoadBalancer.html
```
const lb = new elbv2.ApplicationLoadBalancer(this, 'lb', { vpc });
const listener = lb.addListener('listener', { port: 80 });
```

```
EcsStack | 9:56:12 PM | CREATE_FAILED        | AWS::ElasticLoadBalancingV2::Listener     | ALB/IALB-Listener-http (ALBListenerhttp) Resource handler returned message: "A listener already exists on this port for this load balancer 'arn:aws:elasticloadbalancing:us-east-1:<account-no>:loadbalancer/app/<app-no>' (Service: ElasticLoadBalancingV2, Status Code: 400, Request ID: <request-id>, Extended Request ID: null)" (RequestToken: <request-token>, HandlerErrorCode: AlreadyExists)
```

This makes it impossible to add an ASG as a target of the listener, as the default created ApplicationListener is not accessible in 

```
lb.listeners
```

What is the expected method to add an ASG as a target of the default listener, or override the default listener with a new listener on port 80?

### Expected Behavior

ApplicationLoadBalancer to be created, and then able to add an ApplicationListener on port 80.

### Current Behavior

Exception occurs during deployment, stating that a listener already exists on port 80 and cannot be added. ApplicationLoadBalancer creates a default ApplicationListener on port 80, that cannot have targets added to it. 

### Reproduction Steps

```
const lb = new elbv2.ApplicationLoadBalancer(this, 'lb', { vpc });
const listener = lb.addListener('listener', { port: 80 });
```

### CDK CLI Version

2.27.0 (build 8e89048)

### Node.js Version

v18.3.0

### OS

Mac OS 12.4

### Language

Typescript

**Comment by corymhall** [comment]
@tuipopenoe I haven't been able to reproduce this on a new project. I've tried both creating a load
balancer with the listener _and_ creating the load balancer first and then creating the listener and
I was able to create successfully. Is there anything else in your app?

**Comment by tuipopenoe** [comment]
Setup a brand new stack and was unable to replicate, ALB was created successfully. Closing this as no issue.

**Comment by tuipopenoe** [comment]
The issue was we were using an ApplicationLoadBalancedFargateService (https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ecs_patterns.ApplicationLoadBalancedFargateService.html) that creates a PublicListener on port 80 by default. Accessing the listener to change the TargetGroup causes an error, so in the end we switched to manually creating an ALB and attaching it to a FargateService, resolving this error.

**Comment by yamatatsu** [comment]
I encountered the same problem as tuipopenoe and I solved it by temporarily not using `redirectHTTP: true`.
After deploying it, I added `redirectHTTP: true` back again.
