### ISSUE TITLE
(aws-cdk.aws-globalaccelerator): (Failing installation of aws-cdk.aws-globalaccelerator==1.163.0 on AL2)

### ISSUE THREAD

**Issue by EddyMM** [aws/aws-cdk#21057]
### Describe the bug

Hello,

- An `aws-cdk.aws-globalaccelerator` installation issue was noted while investigating this ticket: [At pcluster installation on AL2 there is a missing dependency](https://github.com/aws/aws-parallelcluster/issues/4180)
- Installing `aws-cdk.aws-globalaccelerator==1.163.0` fails when installing on latest AL2 instance
  - AMI ID: `ami-0d71ea30463e0ff8d`
  - AMI Name: `amzn2-ami-kernel-5.10-hvm-2.0.20220606.1-x86_64-gp2`

### Expected Behavior

- Installation of `aws-cdk.aws-globalaccelerator==1.163.0` using `pip` should work with the latest AL2 instance.
- If `aws-cdk.aws-globalaccelerator==1.163.0` has specific requirements for the `pip` and `setuptools` version it should be specified in the package dependencies setup/requirements

### Current Behavior

- Installation of `aws-cdk.aws-globalaccelerator==1.163.0` fails with the latest AL2 instance.

### Reproduction Steps

- Create an AL2 instance. For the tests below, the instance had these properties:
  - AMI ID: `ami-0d71ea30463e0ff8d`
  - AMI Name: `amzn2-ami-kernel-5.10-hvm-2.0.20220606.1-x86_64-gp2`
- List of python packages under pip:
```
[ec2-user@ip-172-31-27-84 ~]$ python3 -m pip list
Package           Version
----------------- -------
aws-cfn-bootstrap 2.0
docutils          0.14
lockfile          0.11.0
pip               20.2.2
pystache          0.5.4
python-daemon     2.2.3
setuptools        49.1.3
simplejson        3.2.0
```

- Attempting to install `aws-cdk.aws-globalaccelerator==1.163.0`
```
[ec2-user@ip-172-31-27-84 ~]$ python3 -m pip install aws-cdk.aws-globalaccelerator==1.163.0 --upgrade --user

ERROR: Could not find a version that satisfies the requirement aws-cdk.aws-globalaccelerator==1.163.0 (from versions: 1.42.0, 1.42.1, 1.43.0, 1.44.0, 1.45.0, 1.46.0, 1.47.0, 1.47.1, 1.48.0, 1.49.0, 1.49.1, 1.50.0, 1.51.0, 1.52.0, 1.53.0, 1.54.0, 1.55.0, 1.56.0, 1.57.0, 1.58.0, 1.59.0, 1.60.0, 1.61.0, 1.61.1, 1.62.0, 1.63.0, 1.64.0, 1.64.1, 1.65.0, 1.66.0, 1.67.0, 1.68.0, 1.69.0, 1.70.0, 1.71.0, 1.72.0, 1.73.0, 1.74.0, 1.75.0, 1.76.0, 1.77.0, 1.78.0, 1.79.0, 1.80.0, 1.81.0, 1.82.0, 1.83.0, 1.84.0, 1.85.0, 1.86.0, 1.87.0, 1.87.1, 1.88.0, 1.89.0, 1.90.0, 1.90.1, 1.91.0, 1.92.0, 1.93.0, 1.94.0, 1.94.1, 1.95.0, 1.95.1, 1.95.2, 1.96.0, 1.97.0, 1.98.0, 1.99.0, 1.100.0, 1.101.0, 1.102.0, 1.103.0, 1.104.0, 1.105.0, 1.106.0, 1.106.1, 1.107.0, 1.108.0, 1.108.1, 1.109.0, 1.110.0, 1.110.1, 1.111.0, 1.112.0, 1.113.0, 1.114.0, 1.115.0, 1.116.0, 1.117.0, 1.118.0, 1.119.0, 1.120.0, 1.121.0, 1.122.0, 1.123.0, 1.124.0, 1.125.0, 1.126.0, 1.127.0, 1.128.0, 1.129.0, 1.130.0, 1.131.0, 1.132.0, 1.133.0, 1.134.0, 1.135.0, 1.136.0, 1.137.0, 1.138.0, 1.138.1, 1.138.2, 1.139.0, 1.140.0, 1.141.0, 1.142.0, 1.143.0, 1.144.0, 1.145.0, 1.146.0, 1.147.0, 1.148.0, 1.149.0, 1.150.0, 1.151.0, 1.152.0, 1.153.0, 1.153.1, 1.154.0, 1.155.0, 1.156.0, 1.156.1, 1.157.0, 1.158.0, 1.159.0, 1.160.0, 1.161.0, 1.162.0)
ERROR: No matching distribution found for aws-cdk.aws-globalaccelerator==1.163.0
```

After upgrading `pip==22.1.0` and `setuptools==62.1.0`, the installation works
```
[ec2-user@ip-172-31-17-229 ~]$ python3 -m pip list
Package           Version
----------------- -------
aws-cfn-bootstrap 2.0
docutils          0.14
lockfile          0.11.0
pip               22.1.2
pystache          0.5.4
python-daemon     2.2.3
setuptools        62.1.0
simplejson        3.2.0

[ec2-user@ip-172-31-17-229 ~]$ python3 -m pip install aws-cdk.aws-globalaccelerator==1.163.0 --user
Collecting aws-cdk.aws-globalaccelerator==1.163.0
...

[ec2-user@ip-172-31-17-229 ~]$ python3 -m pip list | grep -i "aws-cdk.aws-globalaccelerator"
aws-cdk.aws-globalaccelerator      1.163.0
```

### CDK CLI Version

2.31.0 (build b67950d)

### Node.js Version

v16.16.0

### OS

Amazon Linux 2

### Language

Python

### Language Version

Python 3.7.10

**Comment by peterwoodworth** [comment]
I'm not able to reproduce this on the same versions of pip and setuptools that you're on. This is likely a bug just with the instance environment, which I don't think is something we can fix on our end

**Comment by EddyMM** [comment]
Hello @peterwoodworth , did you use an AL2 instance to reproduce the issue?

**Comment by EddyMM** [comment]
I was able to reproduce the issue on Mac last week. It seems the installation is working now.
I've tested it on AL2 as well and the installation works.

```
[ec2-user@ip-172-31-19-172 ~]$ python3 -m pip list
Package           Version
----------------- -------
aws-cfn-bootstrap 2.0
docutils          0.14
lockfile          0.11.0
pip               20.2.2
pystache          0.5.4
python-daemon     2.2.3
setuptools        49.1.3
simplejson        3.2.0

[ec2-user@ip-172-31-19-172 ~]$ python3 -m pip install aws-cdk.aws-globalaccelerator==1.163.0
Collecting aws-cdk.aws-globalaccelerator==1.163.0
...
Installing collected packages: aws-cdk.aws-globalaccelerator
Successfully installed aws-cdk.aws-globalaccelerator-1.163.0

```

I'm not sure what caused the `No matching distribution` error but since it can't be reproduced, we can close the issue for now.
