### ISSUE TITLE
[aws_autoscaling]: Cron expression invalid

### ISSUE THREAD

**Issue by slawek-survicate** [aws/aws-cdk#21055]
### Describe the bug

`autoscaling.Schedule.cron({ minute: "*" })` produces expression that is not wrapped in `cron(...)` as in aws-cdk v1.

### Expected Behavior

`ScheduleExpression` should be wrapped in `cron(...)`. It worked in v1.

### Current Behavior

Produces resource with invalid `ScheduleExpression` prop:
```js
{
 "Resources": {
  "ruleF2C1DCDC": {
   "Type": "AWS::Events::Rule",
   "Properties": {
    "ScheduleExpression": "* * * * *",
    "State": "ENABLED"
   },
   "Metadata": {
    "aws:cdk:path": "TestStack/rule/Resource"
   }
  }
 },
/// ....
```

### Reproduction Steps

Following code:

```js
#!/usr/bin/env ts-node

import * as cdk from 'aws-cdk-lib';
import { aws_autoscaling as autoscaling } from 'aws-cdk-lib';
import { aws_events as events } from 'aws-cdk-lib';


const app = new cdk.App();
const scope = new cdk.Stack(app, "TestStack")

const expression = autoscaling.Schedule.cron({ minute: "*" });

const rule = new events.Rule(scope, 'rule', { schedule: expression });
```

Produces resource with invalid `ScheduleExpression` prop:
```js
{
 "Resources": {
  "ruleF2C1DCDC": {
   "Type": "AWS::Events::Rule",
   "Properties": {
    "ScheduleExpression": "* * * * *",
    "State": "ENABLED"
   },
   "Metadata": {
    "aws:cdk:path": "TestStack/rule/Resource"
   }
  }
 },
/// ....
```

### CDK CLI Version

2.31.0 (build b67950d)

### Node.js Version

v16.14.0

### OS

Mac OS 12.3

### Language

Typescript

**Comment by peterwoodworth** [comment]
This is happening because you're trying to use the [`Schedule`](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-autoscaling.Schedule.html) class found in the `autoscaling` module, when our `Events.Rule` construct asks for the [`Schedule`](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-events.Schedule.html) class found in our `Events` module. 

We should prevent the user from using the wrong class if possible

**Comment by arewa** [comment]
Hi @peterwoodworth, I prepared the PR with check for the [Schedule](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-events.Schedule.html) class is from the `Events` module. I hope it would help to prevent the issue.

**Comment by TheRealAmazonKendra** [comment]
I know the naming isn't ideal but I don't actually think this is something we should be handling for. As long as it's clearly documented, which I believe it is, it is the users responsibility to ensure they're importing the correct version of a class. If we tried to do this for every instance of a class that shares a name in a different module, it would be extremely messy.

**Comment by peterwoodworth** [comment]
In that case I think we can close this issue out, since I believe this is documented properly.
