### ISSUE TITLE
(aws-stepfunctions-tasks): insert JSON object into dynamodb / marhsall data

### ISSUE THREAD

**Issue by florianbepunkt** [aws/aws-cdk#21078]
### Describe the feature

I would like to use a step function to transform input with a map / pass state and write the results to Dynamodb in one transaction. however this is not possible atm (I believe since the input data is an unmarshalled JSON object.

Given the following input

```
{
  "transactionItems": [
    {
      "Put": {
        "TableName": "eventstore-development",
        "ConditionExpression": "attribute_not_exists(version)",
        "Item": {
          "data": {
            "foo": "bar"
          },
          "id": "TEST-0123",
          "rev": "1.0.0",
          "source": "test",
          "streamId": "test-stream-1",
          "timestamp": 9999,
          "type": "TestExecuted",
          "version": 1
        }
      }
    }
  ]
}
```
and this step function task..

```ts
    const persistEvents = new sfnt.CallAwsService(this, "Persist events to DynamoDB", {
      service: "dynamodb",
      action: "transactWriteItems",
      parameters: { "TransactItems.$": "$.transactionItems" },
      iamResources: [eventsTable.tableArn],
      resultPath: "$.writeResult",
    });

```

This will give the following error

```
An error occurred while executing the state 'Persist events to DynamoDB' (entered at the event id #10). The Parameters '{"TransactItems":[{"Put":{"TableName":"eventstore-development","ConditionExpression":"attribute_not_exists(version)","Item":{"data":{"foo":"bar"},"id":"TEST-0123","rev":"1.0.0","source":"test","streamId":"test-stream-1","timestamp":9999,"type":"TestExecuted","version":1}}}]}' could not be used to start the Task: [The field "foo" is not supported by Step Functions]
```

### Use Case

The input is an event with a valid JSON but otherwise arbitrary structure. This looks like a rather trivial use case, but maybe I am missing something..

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.31.1 (build 42432c6)

### Environment details (OS name and version, etc.)

OSX 11.6.7

**Comment by indrora** [comment]
Could you please provide the appropriate AWS SDK call that would do what you're looking to do?
