### ISSUE TITLE
(redshift): document the resizing operation

### ISSUE THREAD

**Issue by corymhall** [aws/aws-cdk#21103]
### Describe the issue

We should add a section to the README that explains how to resize a cluster using CloudFormation. There are two methods, `elastic` and `classic` which both have implications. There are also different scenarios where you would want to use one vs the other.

Useful docs:
https://aws.amazon.com/premiumsupport/knowledge-center/redshift-troubleshoot-elastic-resize/
https://docs.aws.amazon.com/redshift/latest/mgmt/managing-cluster-operations.html#rs-resize-tutorial

### Links

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-redshift-alpha-readme.html

**Comment by msambol** [comment]
@peterwoodworth Please assign this to me.

**Comment by peterwoodworth** [comment]
Thanks again!
