### ISSUE TITLE
aws-rds: ParameterGroup engine major version update has no effect 

### ISSUE THREAD

**Issue by Okonos** [aws/aws-cdk#21100]
### Describe the bug

Changing the major version of the `ParameterGroup` engine does not update the family of the resource. Changing this property requires resource replacement, but the CFN logs only show an update happening, which apparently does nothing.

`cdk diff` correctly detects the replacement (see "Reproduction Steps" for code):

```
Resources
[~] AWS::RDS::DBClusterParameterGroup pg pg749EE6ED replace
 ├─ [~] Description (requires replacement)
 │   ├─ [-] Cluster parameter group for aurora-postgresql12
 │   └─ [+] Cluster parameter group for aurora-postgresql13
 └─ [~] Family (requires replacement)
     ├─ [-] aurora-postgresql12
     └─ [+] aurora-postgresql13
```

### Expected Behavior

Parameter group should be recreated with family property updated.

### Current Behavior

Parameter group is updated in-place without apparent effect. The family stays the same.

### Reproduction Steps

```ts
import * as cdk from 'aws-cdk-lib';
import {
    AuroraPostgresEngineVersion,
    DatabaseClusterEngine,
    ParameterGroup,
} from "aws-cdk-lib/aws-rds";

export class SandboxStack extends cdk.Stack {
  constructor(scope: cdk.App, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const version = AuroraPostgresEngineVersion.VER_12_8; // updated to VER_13_4;
    const engine = DatabaseClusterEngine.auroraPostgres({ version });
    const parameterGroup = new ParameterGroup(this, 'pg', {
        engine,
        parameters: {
            log_rotation_age: '120',
        },
    });
    parameterGroup.bindToCluster({});
  }
}
```

### Additional Information/Context

Might be related to https://github.com/aws/aws-cdk/issues/9741

### CDK CLI Version

2.28.1 (build d035432)

### Node.js Version

v16.15.1

### OS

Ubuntu

### Language

Typescript

**Comment by corymhall** [comment]
@Okonos it looks like this may be expected behavior for this resource. The Cfn docs have a note that
says "The DB cluster parameter group family can't be changed when updating a DB cluster parameter
group.".

It looks like you will have to create a new parameter group and delete the old one. I think we
should document this behavior in the README.

**Comment by Okonos** [comment]
@corymhall I've tested it with raw CloudFormation and that's indeed the case. Sorry for bothering you.
