### ISSUE TITLE
(mwaa): what should I pass to the plugins_s3_object_version parameter?

### ISSUE THREAD

**Issue by psyking841** [aws/aws-cdk#21114]
### Describe the issue

I am creating an MWAA cluster using [CfnEnvironment](https://docs.aws.amazon.com/cdk/api/v1/python/aws_cdk.aws_mwaa/CfnEnvironment.html). There is a parameter, plugins_s3_object_version, which by default is None. Now, in my use case whenever there is an updated version of plugins.zip getting pushed to s3 bucket from my CI/CD, I would like to update this parameter with it pointing to the latest plugins.zip, but what value I should pass to it? An object creation timestamp, or the version ID of the object, or maybe something else? The documentation above says: "The version of the plugins.zip file on your Amazon S3 bucket." Does that imply the Version ID? If so, how can I get the version ID of an object using [BucketDeployment](https://docs.aws.amazon.com/cdk/api/v1/python/aws_cdk.aws_s3_deployment/BucketDeployment.html)? My CI/CD pipeline is using BucketDeployment to deploy the plugins.zip to s3 bucket.

Thanks!

### Links

https://docs.aws.amazon.com/cdk/api/v1/python/aws_cdk.aws_mwaa/CfnEnvironment.html

**Comment by deuscapturus** [comment]
I have this same issue.  BucketDeployment doesn't return object versions, and the object for regular s3 file assets is created before the asset is ever uploaded to s3 (and can therefore never return the object version.)

It's important to specify an object version for the requirements.txt file in MWAA, otherwise MWAA is incredibly slow to update the environment when the requirements.txt changes.

I think the answer is either create a new single object BucketDeployment asset construct; Or, add object versions somehow to the existing BucketDeployment.

**Comment by psyking841** [comment]
Thank you for your reply. I also want to share my findings and what I ended up doing. 

So yes, the plugins_s3_object_ version should be supplied with the object version id.

Every time I updated my plugins.zip I supplied its version id to that parameter in the CDK code then the CDK pipeline will trigger an update on the cluster.

Now, how do I get the version id? I ended up creating a lambda to do so. In CDK, I used a custom resource to trigger the lambda and get the latest version id. 

I hope this helps to people who are also consumed about this parameter.

I also agreed that the bucket deployment should return version id for the object deployed.

**Comment by psyking841** [comment]
@rix0rrr See my comment.

**Comment by psyking841** [comment]
I need to reopen this because I just found that the object version won't help to update the plugin.zip in MWAA.
In snapshot 1 - I have versioning on on the plugins.zip object. And I pass it in to the construct by
```
managed_airflow = mwaa.CfnEnvironment(
...
plugins_s3_path='plugins.zip',
plugins_s3_object_version=plugins_object_version,
...
)
```
But in snapshot 2 the environment is not picking up the latest plugins.zip.

**Comment by psyking841** [comment]
Closed it again. It turned out I had to append the a random UUID chars to the custom resource that triggers my lambda.
```
get_plugin_version_resource_logic_name = f"CdkMwaaGetPlubinsVersionLambdaTrigger{str(uuid.uuid4())[:8]}"
custom_resource = cdk.CustomResource(self, get_plugin_version_resource_logic_name, ...)
```
