### ISSUE TITLE
(aws-eks): HelmChart rollback / deletion leaves namespace behind

### ISSUE THREAD

**Issue by jaredhancock31** [aws/aws-cdk#21126]
### Describe the bug

When adding HelmCharts with `CreateNamespace: true`, if something fails and has to rollback OR if I decide to remove the chart from my stack and deploy the delta, the namespace still exists. Rollback/Update state is successful.

### Expected Behavior

Namespace should get deleted	

### Current Behavior

Namespace still exists

### Reproduction Steps

* Add a HelmChart to the stack with `CreateNamespace: true`. 

```go
awseks.NewHelmChart(stack, jsii.String("FluxCharts"), &awseks.HelmChartProps{
		Repository: jsii.String("https://charts.fluxcd.io/"),
		Release:    jsii.String("flux"),
		Chart:      jsii.String("flux"),
		Namespace:  jsii.String("flux"),
		Version:    jsii.String("1.13.1"),
		Cluster:    cluster,
		CreateNamespace: jsii.Bool(true),
	})
```

* Deploy it successfully (`cdk deploy`)
* Remove the chart, and `cdk deploy` again. Observe that the chart is uninstalled and state == update_successful.
* `k get ns | grep flux` and it's still there.

You could also purposefully fail the deployment of the helm chart somehow and still see the same issue

### CDK CLI Version

2.28.1

### Node.js Version

16.13.2

### OS

MacOS

### Language

Go

### Language Version

1.17

**Comment by indrora** [comment]
This is an underlying behavior of Helm: https://github.com/helm/helm/issues/1464
