### ISSUE TITLE
(core): (tags in StackProps are not applied to Custom Resources implementing ITaggable)

### ISSUE THREAD

**Issue by Saigonen** [aws/aws-cdk#21121]
### Describe the bug

While adding support for tags in my custom resource library, I noticed that tags provided in StackProps are not propagated down to custom resources. I implemented the tagging support according to docs in [TagManager](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.TagManager.html).

Tags added via `Tags.of(stack).add('key', 'value');` work just fine. But according to [docs](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.Stack.html) the tags provided in StackProps should be applied to all taggable resources too. 

The bug can be circumvented in custom resource code with:
```ts
Stack.of(this).tags.renderTags()?.forEach((tag: any) => {
  this.tags.setTag(tag.Key, tag.Value);
});
```

### Expected Behavior

Tags provided in StackProps to be available in custom resources implementing ITaggable when using `this.tags.renderedTags`.

### Current Behavior

Only tags added with `Tags.of().add()` are set when using `this.tags.renderedTags` in a custom resource.

### Reproduction Steps

```ts
import { App, CustomResource, ITaggable, Resource, Stack, TagManager, Tags, TagType } from 'aws-cdk-lib';
import { Code, Function, Runtime } from 'aws-cdk-lib/aws-lambda';
import { Provider } from 'aws-cdk-lib/custom-resources';
import { Construct } from 'constructs';

class MyCustomResource extends Resource implements ITaggable {
  readonly tags: TagManager;
  constructor(scope: Construct, id: string) {
    super(scope, id);
    this.tags = new TagManager(TagType.KEY_VALUE, 'Custom::MyCustomResource');
    // Currently we have to fetch StackProps tags ourself
    // Stack.of(this).tags.renderTags()?.forEach((tag: any) => {
    //   this.tags.setTag(tag.Key, tag.Value);
    // });
    const handler = new Function(this, 'MyHandler', {
      runtime: Runtime.NODEJS_16_X,
      handler: 'index.handler',
      code: Code.fromInline(`
        exports.handler = async (event) => { console.log('Tags: ', event.ResourceProperties.Tags); };
    `),
    });
    const provider = new Provider(this, 'MyProvider', { onEventHandler: handler });
    new CustomResource(this, 'MyCustomResource', {
      serviceToken: provider.serviceToken,
      resourceType: 'Custom::MyCustomResource',
      properties: {
        Tags: this.tags.renderedTags,
      },
    });
  }
}

const app = new App();
const stack = new Stack(app, 'MyStack', { tags: { 'stack-props-tag': 'value1' } });
const resource = new MyCustomResource(stack, 'MyCustomResource');
Tags.of(stack).add('stack-tag', 'value2');
Tags.of(resource).add('resource-tag', 'value3');
```

Deploying this we can see in the cloudwatch logs that only `stack-tag` and `resource-tag` are in place. The `stack-props-tag` is missing. (We can see this from the synthesized template too, but I included this example because StackProps tags are normally present only in the manifest.json).

Logs show:
`INFO Tags: [ { Value: 'value3', Key: 'resource-tag' }, { Value: 'value2', Key: 'stack-tag' } ] `

What it should be:
`INFO Tags: [ { Value: 'value3', Key: 'resource-tag' }, { Value: 'value2', Key: 'stack-tag' }, { Value: 'value1', Key: 'stack-props-tag' } ] `

### Possible Solution

It seems that neither the Stack nor TagManager constructor is using Tags class or the Aspect framework to set the tags.

### Additional Information/Context

Full implementation of the custom construct library where I encountered this behavior: [cdk-secure-string-parameter](https://github.com/saigonen/cdk-secure-string-parameter).

### CDK CLI Version

2.31.1

### Node.js Version

v16.15.1

### OS

Ubuntu

### Language

Typescript

### Language Version

Typescript (4.7.4)

**Comment by peterwoodworth** [comment]
This happens because tags are [only applied to taggable resources](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cfn-customresource.html) - [Custom Resources are not taggable](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_core.Stack.html#tags) as far as I'm aware

Any tags you wish to pass into your custom resource must be explicitly defined in the set of tags you pass to the custom resource

**Comment by Saigonen** [comment]
A direct quote from the [docs](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.TagManager.html):

> TagManager facilitates a common implementation of tagging for Constructs.
>
> Normally, you do not need to use this class, as the CloudFormation specification will indicate which resources are taggable. 
> However, sometimes you will need this to make custom resources taggable. Used tagManager.renderedTags to obtain a value 
> that will resolve to the tags at synthesis time.

So with TagManager and having your Custom Resource implementing ITaggable you can make your custom resource taggable. Of course you need custom code to actually then handle those tags in your custom resource implementation.

And besides, like the example I posted shows, tags which are set using `Tags.of(scope).add()` are already working. Only tags which are set in Stack constructor StackProps are not applied. And they should be. Even according to Stack [docs](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.Stack.html):

> tags?
> Type: { [string]: string } (optional, default: {})
> Stack tags that will be applied to all the taggable resources and the stack itself.

**Comment by peterwoodworth** [comment]
The tags property for Stack will only apply the tags to resources that CloudFormation knows is taggable - which doesn't include CustomResources. Creating a wrapper class that implements `ITaggable` doesn't do anything here - the underlying CloudFormation resources inside your wrapper class still won't have the tags property. You will want to use aspects until CloudFormation includes the tags property on custom resources, which I'm not sure can happen due to the nature of custom resources

**Comment by Aeolun** [comment]
This does not seems like a response? And the thing is still a problem. Making a new construct that implements the ITaggable interface should make that construct be taggable, but the tags are never applied to it's tagmanager.

**Comment by pahud** [comment]
Hi @Aeolun The last comment before this issue being closed was in 2022 and it's been a long time. Let's create a new one if you are still having the issue. Thanks.
