### ISSUE TITLE
UserPoolClient does not not expose a method to get the client secret

### ISSUE THREAD

**Issue by sdelamo** [aws/aws-cdk#21139]
### Describe the feature

I would like to be able to retrieve the Client secret of a `UserPoolClient` via CDK

Currently, it is possible to get the ClientID (`UserPoolClient:.getUserPoolClientId`) but not the secret. see:

https://github.com/sdelamo/micronauttodo.com/blob/master/infra/src/main/java/com/micronauttodo/AppStack.java#L179

### Use Case

I would like to be able to create the `UserPoolClient` and expose the secret as an environment variable to a lambda function. 

### Proposed Solution

Add a method to `Optional<String> getUserPoolClientSecret()` to `UserPoolClient`

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.31.1

### Environment details (OS name and version, etc.)

MacOS Montery

**Comment by corymhall** [comment]
@sdelamo it looks like we already have a request for this, see #7225. That issue has some
workarounds that can be used. I'm going to close this issue and we can continue to track on the
original issue.
