### ISSUE TITLE
aws_cdk.pipelines: v1.158.0 creates excessive asset overflow policies. 

### ISSUE THREAD

**Issue by consegna-davis** [aws/aws-cdk#21151]
### Describe the bug

When synthesising a stack with >10 glue jobs where py code is sourced from the local file system the role associated with the job has an excessive number of overflow policies attached with it.

### Expected Behavior

Excessive overflow policies with the same content not being associated with IAM roles attached to glue jobs. 

### Current Behavior

When more than 10 glue jobs are created using local files for the glue.JobExecutable:
`                job_exe = glue.JobExecutable.python_etl(
                    glue_version=glue.GlueVersion.of(
                        etl_config.get('GlueVersion', '3.0')
                    ),
                    script=glue.Code.from_asset(path=job_file),
                    python_version=etl_config.get(
                        'PyVersion',
                        glue.PythonVersion.THREE
                    ),
                    extra_jars=extra_jars,
                    extra_python_files=extra_pys
                )
`
the role associated with the job has an excessive number of overflow policies attached with it, which causes the following warning message:
"[Warning at /DataLake-prod-glue-jobsRole] Policy large: 20 exceeds 10 managed policies attached to a Role, this requires a quota increase"

When synched locally, the role gets one overflow policy per glue job script. These are all duplicates of the default policy attached to the role which gives S3 read only permissions to the asset bucket.

Bug was confirmed by synthesising the stack with cdk v1.157 and not having the issue. Upgrading to v1.158 and confirming this behaviour.

Similar pipelines using cdk v2.24.1 don't have this problem.  

### Reproduction Steps

Bug was confirmed by synthesising the stack with cdk v1.157 and not having the issue. Upgrading to v1.158 and confirming this behaviour.

### Possible Solution

Similar pipelines using cdk v2.24.1 don't have this problem.

### CDK CLI Version

2.31.2 (build 091f0d8)

### Framework Version

1.158.0

### Node.js Version

18.0.0

### OS

macOS 12.4

### Language

Python

### Language Version

3.10.3

### Other information

Upgrading to latest CDK 1 version (1.163.2) doesn't resolve the issue. Staying at v1.157 is a viable work around.

**Comment by peterwoodworth** [comment]
This is probably a feature flag related issue. This change was hidden behind a feature flag, but I'm not entirely sure if feature flags are backwards compatible at all with v2. This change is enabled with the IAM_MINIMIZE_POLICIES feature flag set

cc @TheRealAmazonKendra

**Comment by TheRealAmazonKendra** [comment]
v2 feature flags would not have backward compatibility as the two versions have now diverged. The solution here is to use v2. We are now in maintenance mode for v1 so we are no longer working on any issues only impacting v1 unless they are a p0 or a security issue.

**Comment by peterwoodworth** [comment]
Closing since we don't plan to fix this v1-specific bug
