### ISSUE TITLE
CDK Bootstrap: We need multiple bootstrap stack with isolated policies

### ISSUE THREAD

**Issue by abhineetsbhamra** [aws/aws-cdk#21154]
### Background
We built our AWS Environment using Terraform, but now we are moving towards CDK. 
We run two Github runners per AWS Account and restrict the IAM policies on each to only allow access to certain AWS resources.
`App Runner; Deploys ECS Services, Lambda, API Gateway, Dynamo, RDS, S3`
`Infra Runner; Deploys MSK, VPC, SSO`
We then configure certain Github Repositories to deploy platform IaC using the Infra runner and service repos to use the App Runner(separation of concerns). 
Our approach to bootstrapping CDK has been to deploy two toolkits per AWS Account + Region. Each toolkit would then map to a type of Github runner. Eg InfraRunner uses InfraCDKToolkit, with exec policies to deploy MSK, VPC and AppCDKToolkit will be used by the App Runners.

### Use Case
We’ve found a way to use the desired qualifier stack via the github workflow by using `cdk deploy --context "@aws-cdk/core:bootstrapQualifier"="thequalifier"` the only problem is that this can be overwritten in the CDK code using
```
synthesizer: new DefaultStackSynthesizer({
   qualifier: 'hnb659fds'
 }),
```
Is there a way we can make this more fool proof?

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.27.0

### Environment details (OS name and version, etc.)

Amazon Linux2

**Comment by rix0rrr** [comment]
If you configure your GitHub runner to only be able to assume one role or the other, it doesn't matter that devs can override your qualifier in code: it won't properly deploy anyway if they do, so there's no motivation to mess with it.

If both GitHub runners can assume both roles and this is your only protection, then locking it down even more does not work anyway. CDK users can write arbitrary JavaScript code with all power that entails, and do something like:

```ts
app.synth();
fs.writeFileSync('cdk.out/manifest.json', {
  // ...
    deployRoleArn: 'arn:aws:iam::123456789012:role/cdk-ESCAPE-deploy-role',
   // ...
});
```

There is no protecting against that by taking away the "nice" way to set the qualifier

**Comment by abhineetsbhamra** [comment]
Thanks a ton @rix0rrr for taking out time and replying. What you just mention is inline with our internal discussions and iI reckon we may take that route going forward. Thanks again :)
