### ISSUE TITLE
aws-sns: 'autoCreatePolicy' for the imported topic is set to false,

### ISSUE THREAD

**Issue by gokendra1** [aws/aws-cdk#21158]
### Describe the feature

Since  the 'autoCreatePolicy' for the imported topic is set to false by default, Hence we need to add the policy explicitly. 

### Use Case

The basic requirement is that I have an SNS Topic created in one App (Core App) and I need to access it in another App (Jobs App).
I have one stack per app.

The issue is:
1. If I use ITopic in Jobs app, CDK does not update the access policy of the SNS Topic to allow Event bridge to put a message.
2. If I acess the Core App and then its SNS Topic in Jobs app (both in Java), I get the error message that  'Cannot reference across apps. Consuming and producing stacks must be defined within the same CDK app.'

### Proposed Solution

If possible make the property 'autoCreatePolicy' configurable or allow user to set it to true/false as per the use case.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.31.2

### Environment details (OS name and version, etc.)

macOS 12.3.1

**Comment by peterwoodworth** [comment]
I think we should be able to support this, as the arn is the only information required to be able to create a new TopicPolicy.

**Comment by rix0rrr** [comment]
It's not safe to add an `AWS::SNS::TopicPolicy` to referenced Topics (that is to say, `AWS::SNS::Topic` and `AWS::SNS::TopicPolicy` must be in the same Stack, and the only way to guarantee that is to have access to a `Topic` class, not an `ITopic` interface).

Your problem might be with the definition of your CDK app. If you put all your Stacks into the same App, it should work as intended.
