### ISSUE TITLE
(aws-events): Can't specify Input parameters on RuleTarget

### ISSUE THREAD

**Issue by indrora** [aws/aws-cdk#21153]
### Describe the bug

Rule Targets (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-events-rule-target.html) have Input parameters. These are sometimes exposed by the L2 constructs. They should be exposed by all constructs that return a RuleTarget

### Expected Behavior

I can specify the Input on a Lambda invocation from a rule

### Current Behavior

I can't because there is no way to set it. 

### Reproduction Steps

```ts


const fn = new lambda.Function(this, 'MyFunc', {
  runtime: lambda.Runtime.NODEJS_14_X,
  handler: 'index.handler',
  code: lambda.Code.fromInline(`exports.handler = handler.toString()`),
});

const rule = new events.Rule(this, 'rule', {
  eventPattern: {
    source: ["aws.ec2"],
  },
});

rule.addTarget(new targets.LambdaFunction(fn, {
  input: {"Bananas":"its🍌bananas🍌what🍌I🍌can🍌do"}
}));
```

### CDK CLI Version

2.27

### Node.js Version

18

### OS

Darwin64

### Language

Typescript, Python, .NET, Java, Go

**Comment by otaviomacedo** [comment]
@indrora in the case of Lambda function targets, the property name is `event`:


```ts
const fn = new lambda.Function(this, 'MyFunc', {
  runtime: lambda.Runtime.NODEJS_14_X,
  handler: 'index.handler',
  code: lambda.Code.fromInline(`exports.handler = handler.toString()`),
});

const rule = new events.Rule(this, 'rule', {
  eventPattern: {
    source: ["aws.ec2"],
  },
});

rule.addTarget(new targets.LambdaFunction(fn, {
  event: RuleTargetInput.fromObject({"Bananas":"its🍌bananas🍌what🍌I🍌can🍌do"})
}));
```
