### ISSUE TITLE
cli: bootstrap fails on IAM role existing

### ISSUE THREAD

**Issue by Gamecock** [aws/aws-cdk#21172]
### Describe the bug

Bootstrap a region, delete most resources, but not IAM roles.
Rerun bootstrap.   Bootstrap fails.

### Expected Behavior

Expected it to succeed.  I was surprised because re bootstrapping had fixed a missing CloudFormationExecutionRole.

### Current Behavior

$ cdk bootstrap
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
 ⏳  Bootstrapping environment aws://<account>/us-east-1...
Trusted accounts for deployment: (none)
Trusted accounts for lookup: (none)
Using default execution policy of 'arn:aws:iam::aws:policy/AdministratorAccess'. Pass '--cloudformation-execution-policies' to customize.
CDKToolkit: creating CloudFormation changeset...
CDKToolkit |  0/12 | 1:16:26 PM | REVIEW_IN_PROGRESS   | AWS::CloudFormation::Stack | CDKToolkit User Initiated
CDKToolkit |  0/12 | 1:16:34 PM | CREATE_IN_PROGRESS   | AWS::CloudFormation::Stack | CDKToolkit User Initiated
CDKToolkit |  0/12 | 1:16:39 PM | CREATE_IN_PROGRESS   | AWS::S3::Bucket       | StagingBucket
CDKToolkit |  0/12 | 1:16:40 PM | CREATE_IN_PROGRESS   | AWS::ECR::Repository  | ContainerAssetsRepository
CDKToolkit |  0/12 | 1:16:40 PM | CREATE_IN_PROGRESS   | AWS::IAM::Role        | CloudFormationExecutionRole
CDKToolkit |  0/12 | 1:16:40 PM | CREATE_IN_PROGRESS   | AWS::SSM::Parameter   | CdkBootstrapVersion
CDKToolkit |  0/12 | 1:16:40 PM | CREATE_IN_PROGRESS   | AWS::IAM::Role        | ImagePublishingRole
CDKToolkit |  0/12 | 1:16:40 PM | CREATE_IN_PROGRESS   | AWS::IAM::Role        | FilePublishingRole
CDKToolkit |  0/12 | 1:16:40 PM | CREATE_IN_PROGRESS   | AWS::IAM::Role        | LookupRole
CDKToolkit |  0/12 | 1:16:40 PM | CREATE_IN_PROGRESS   | AWS::S3::Bucket       | StagingBucket Resource creation Initiated
CDKToolkit |  0/12 | 1:16:41 PM | CREATE_FAILED        | AWS::IAM::Role        | ImagePublishingRole cdk-hnb659fds-image-publishing-role-<account>-us-east-1 already exists
CDKToolkit |  0/12 | 1:16:41 PM | CREATE_FAILED        | AWS::IAM::Role        | FilePublishingRole cdk-hnb659fds-file-publishing-role-<account>-us-east-1 already exists
CDKToolkit |  0/12 | 1:16:41 PM | CREATE_FAILED        | AWS::IAM::Role        | CloudFormationExecutionRole Resource creation cancelled
CDKToolkit |  0/12 | 1:16:41 PM | CREATE_FAILED        | AWS::S3::Bucket       | StagingBucket Resource creation cancelled
CDKToolkit |  0/12 | 1:16:41 PM | CREATE_FAILED        | AWS::IAM::Role        | LookupRole Resource creation cancelled
CDKToolkit |  0/12 | 1:16:41 PM | CREATE_FAILED        | AWS::ECR::Repository  | ContainerAssetsRepository Resource creation cancelled
CDKToolkit |  0/12 | 1:16:41 PM | CREATE_FAILED        | AWS::SSM::Parameter   | CdkBootstrapVersion Resource creation cancelled
CDKToolkit |  0/12 | 1:16:42 PM | ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack | CDKToolkit The following resource(s) failed to create: [ImagePublishingRole, FilePublishingRole, CdkBootstrapVersion, LookupRole, StagingBucket, CloudFormationExecutionRole, ContainerAssetsRepository]. Rollback requested by user.
CDKToolkit |  1/12 | 1:16:59 PM | DELETE_COMPLETE      | AWS::IAM::Role        | ImagePublishingRole
CDKToolkit |  2/12 | 1:16:59 PM | DELETE_COMPLETE      | AWS::IAM::Role        | FilePublishingRole
CDKToolkit |  3/12 | 1:17:00 PM | DELETE_COMPLETE      | AWS::IAM::Role        | CloudFormationExecutionRole
CDKToolkit |  4/12 | 1:17:00 PM | DELETE_COMPLETE      | AWS::IAM::Role        | LookupRole
CDKToolkit |  5/12 | 1:17:00 PM | DELETE_COMPLETE      | AWS::ECR::Repository  | ContainerAssetsRepository
CDKToolkit |  6/12 | 1:17:00 PM | DELETE_COMPLETE      | AWS::SSM::Parameter   | CdkBootstrapVersion
CDKToolkit |  6/12 | 1:17:00 PM | DELETE_SKIPPED       | AWS::S3::Bucket       | StagingBucket
CDKToolkit |  7/12 | 1:17:01 PM | ROLLBACK_COMPLETE    | AWS::CloudFormation::Stack | CDKToolkit

Failed resources:
CDKToolkit | 1:16:41 PM | CREATE_FAILED        | AWS::IAM::Role        | ImagePublishingRole cdk-hnb659fds-image-publishing-role-<account>-us-east-1 already exists
CDKToolkit | 1:16:41 PM | CREATE_FAILED        | AWS::IAM::Role        | FilePublishingRole cdk-hnb659fds-file-publishing-role-<account>-us-east-1 already exists
 ❌  Environment aws://<account>/us-east-1 failed bootstrapping: Error: The stack named CDKToolkit failed creation, it may need to be
 manually deleted from the AWS console: ROLLBACK_COMPLETE: cdk-hnb659fds-image-publishing-role-<account>-us-east-1 already exists, cdk-hnb659fds-file-publishing-role-<account>-us-east-1 already exists
    at prepareAndExecuteChangeSet (C:\Users\2259252\AppData\Roaming\npm\node_modules\aws-cdk\lib\api\deploy-stack.ts:386:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at C:\Users\2259252\AppData\Roaming\npm\node_modules\aws-cdk\lib\cdk-toolkit.ts:577:24
    at async Promise.all (index 0)
    at CdkToolkit.bootstrap (C:\Users\2259252\AppData\Roaming\npm\node_modules\aws-cdk\lib\cdk-toolkit.ts:574:5)
    at initCommandLine (C:\Users\2259252\AppData\Roaming\npm\node_modules\aws-cdk\lib\cli.ts:345:12)
****************************************************
*** Newer version of CDK is available [2.32.0]   ***
*** Upgrade recommended (npm install -g aws-cdk) ***
****************************************************

The stack named CDKToolkit failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: cdk-hnb659fds-image-publishing-role-<account>-us-east-1 already exists, cdk-hnb659fds-file-publishing-role-<account>-us-east-1 already exists

### Reproduction Steps

Bootstrap region
Delete assets, but not IAM roles (Have not confirmed if it's a specific asset or all)
rerun bootstrap.

### Additional Information/Context

Account is in a corporate account.  Deletions occurred as part of lab cleanup.  Bucket was deleted first when cleaning S3, then stack was deleted.  There were some errors, engineer doing cleanup did not capture the errors, logged out and back in again and stack was no longer showing.

### CDK CLI Version

2.31.1 (build 42432c6)

### Node.js Version

v16.15.1

### OS

Windows10 Version 1803 OS Build 17134.2208

### Language

Typescript

### Other information

I have seen various  other behaviors.  If I can capture other logs, should I include here, or if the effects are different as separate bugs?
1) run to finish with missing bucket, but fail to recreate it.
2) Successfully fix missing IAM role in order to delete entire stack.

**Comment by kurosukee** [comment]
The same error occurred.
I temporarily solved the problem with the following
1. Delete temporary stack in CloudFormation.
2. Delete temporary buckets in S3.
3. Temporarily attach AdministratorAccess in IAM.

**Comment by Stazz-Sphinx** [comment]
Hi @kurosukee  is it safety delete CF stack CDKToolkit  if I have already built more resources by use CDK?  
The reason why I ask, it's after migrate CDK to ver 2, and migrate to new bootstrap version, my cdk deployment failed with access permission error. 

```
current credentials could not be used to assume 'arn:aws:iam::1234567890:role/cdk-hnb659fds-deploy-role-1234567890-ap-southeast-2', but are for the right account. Proceeding anyway.
[0%] start: Publishing b78d53a4e13604c990990d071559d16689ce158c2dfc2a01824190f31228a3bc:current_account-current_region
current credentials could not be used to assume 'arn:aws:iam:: 1234567890:role/cdk-hnb659fds-file-publishing-role-1234567890-ap-southeast-2', but are for the right account. Proceeding anyway.
[100%] fail: Bucket named 'cdk-hnb659fds-assets-1234567890-ap-southeast-2' exists, but not in account 1234567890. Wrong account?

```

**Comment by rix0rrr** [comment]
This is the current behavior and it's extremely hard to change. This behavior is enforced by CloudFormation and we are currently dependent on them to deploy anything.
