### ISSUE TITLE
aws-chatbot: ISlackChannelConfiguration should include addNotificationTopic() method

### ISSUE THREAD

**Issue by polastre** [aws/aws-cdk#21171]
### Describe the feature

#15588  and #16643 added the method `addNotificationTopic()` to the `SlackChannelConfiguration` construct. This allows the SNS topic to be added to an existing configuration.

For an existing slack channel, it can be imported with `SlackChannelConfiguration. fromSlackChannelConfigurationArn`. This returns `SlackChannelConfiguration`.

If you create a new `SlackChannelConfiguration` construct, then you can use `addNotificationTopic` since it returns that construct object. If you use `fromSlackChannelConfigurationArn`, then you get `ISlackChannelConfiguration` which does not have `addNotificationTopic`.

The request to is add `addNotificationTopic` to `ISlackChannelConfiguration` so that it can used with existing slack channel configurations.

### Use Case

A stack where the slack channel configuration is already defined, and the stack seeks to add notification topics to that existing slack channel configuration.

### Proposed Solution

Add `addNotificationTopic` to the interface in https://github.com/xykkong/aws-cdk/blob/master/packages/@aws-cdk/aws-chatbot/lib/slack-channel-configuration.ts#L109

### Acknowledgements

- [X] I may be able to implement this feature request
- [x] This feature might incur a breaking change

### CDK version used

2.32.0

### Environment details (OS name and version, etc.)

typescript

**Comment by kaizencc** [comment]
This sounds reasonable @polastre! Are you interested in contributing this?

**Comment by daschaa** [comment]
@kaizencc I tried working on this but I'm not sure how to properly test this. Do you have an idea/hint how to do it?

**Comment by debnon** [comment]
I implemented this change, but when unit testing realized that adding an SNS topic to a Slack Config retrieved by ARN from another stack doesn't actually seem to add it to the existing Slack Config. 

Does it go against best practices to modify one stack from another like this, and if not, is there an established way to trigger the changes to Cloudformation after calling the method to add SNS topics? Thanks.

**Comment by sercantor** [comment]
I also had the same thing @debnon, when I added the method and tried to use it, it created the sns topics, but they weren't in slack channel topics. can anyone show an example similar to this so we can just add it?

**Comment by zentavr** [comment]
Is there any workaround to use shared stack which creates slack notifications and attach the new SNS topics inside?

**Comment by larskinder** [comment]
@zentavr that you can do.            
```
slack_bot = chatbot.SlackChannelConfiguration(
    chatbot.SlackChannelConfiguration.from_slack_channel_configuration_arn(
        self,
        "SlackNotifications",
        slack_channel_configuration_arn=(
            f"arn:aws:chatbot::{account}:chat-configuration/slack-channel/test-channel-config"
        ),
    )
)

slack_bot.add_notification_topic(some_sns_topic)
slack_bot.add_notification_topic(another_sns_topic)
```

**Comment by ben-buitendijk** [comment]
@larskinder 
That is Python, right? I'm using Typescript and it seems like the construct doesn't have that method...

<img width="657" alt="image" src="https://user-images.githubusercontent.com/110386453/233563075-7602ad10-6e9f-4ff0-ba7c-975063d860ea.png">

Also it doesn't show in the documentation: 
https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_chatbot.ISlackChannelConfiguration.html

**Comment by larskinder** [comment]
Sry, re-added my previous post, that you were referencing to.

This is how you can add SNS topics to an existing Slack config.

```
slack_bot = chatbot.SlackChannelConfiguration(
    chatbot.SlackChannelConfiguration.from_slack_channel_configuration_arn(
        self,
        "SlackNotifications",
        slack_channel_configuration_arn=(
            f"arn:aws:chatbot::{account}:chat-configuration/slack-channel/test-channel-config"
        ),
    )
)

slack_bot.add_notification_topic(sns_topic)
slack_bot.add_notification_topic(another_sns_topic)
```

**Comment by ben-buitendijk** [comment]
That is the page when you create a new SlackChannelConfiguration, but the construct when you import it from an ARN doesn't have that method

**Comment by MayconFrr** [comment]
Bump

**Comment by GithubWikiRealty** [comment]
I think this is already implemented by now 

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_chatbot.SlackChannelConfiguration.html#addwbrnotificationwbrtopicnotificationtopic

but now i am wondering if there is a way to obtain the SlackChannelConfiguration topics? so somehow get the list of subscribed topics fro a given SlackChannelConfiguration using CDK or the CLI!

**Comment by luiscastillocr** [comment]
I think this is already implemented by now

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_chatbot.SlackChannelConfiguration.html#addwbrnotificationwbrtopicnotificationtopic

but now i am wondering if there is a way to obtain the SlackChannelConfiguration topics? so somehow get the list of subscribed topics fro a given SlackChannelConfiguration using CDK or the CLI!

**Comment by sercantor** [comment]
@luiscastillocr I don't think it's been added, look at the last commits. https://github.com/aws/aws-cdk/commits/26dcc1e11a07d93681145049aa06d80a7d2114b9/packages/aws-cdk-lib/aws-chatbot/lib/slack-channel-configuration.ts

not sure even if it's possible, the resource is created, we'd be wanting to manipulate the resource we created in one stack in another stack.

an alternative to this would be to do Alarms -> SNS -> Lambda (provide your webhook url & stuff, write your custom message) -> Slack

**Comment by luiscastillocr** [comment]
hey @sercantor you are right, i was looking at the `SlackChannelConfiguration` construct when you actually were talking about the `ISlackChannelConfiguration ` contructor, my apologies, in my case as a workaround i decided to create my own SlackConfiguration from CDK along with a custom Topic so I can have the ARN to send custom notifications from codebuild using the aws CLI

```
const events = [
            // actions
            'codepipeline-pipeline-action-execution-failed',
            'codepipeline-pipeline-action-execution-canceled',

            // stages
            'codepipeline-pipeline-stage-execution-resumed',
            'codepipeline-pipeline-stage-execution-canceled',
            'codepipeline-pipeline-stage-execution-failed',

            // pipeline
            'codepipeline-pipeline-pipeline-execution-failed',
            'codepipeline-pipeline-pipeline-execution-canceled',
            'codepipeline-pipeline-pipeline-execution-started',
            'codepipeline-pipeline-pipeline-execution-resumed',
            'codepipeline-pipeline-pipeline-execution-succeeded'
        ];

const slackChannelConfigurationTopic = new sns.Topic(this, slackChannelTopicName);

const slackChannelConfiguration = new chatbot.SlackChannelConfiguration(this, slackChannelConfigurationName, {
            slackChannelConfigurationName: slackChannelConfigurationName,
            slackWorkspaceId: slackChatbotWorkspaceId,
            slackChannelId: slackChannelId,
            notificationTopics: [snsTopic]
        });

const notificationRule = new code_star_notifications.NotificationRule(this,
            codestarNotificationRuleName,
            {
                events: events,
                source: pipeline.pipeline,
                targets: [slackChannelConfiguration]
            }
        );

notificationRule.node.addDependency(pipeline);
```

then i can do something like this in a CodeBuildStep command
```
aws sns publish --topic-arn "${SLACK_TOPIC_ARN}" --message file://cdk/lib/slack-msg.json
```
😉

**Comment by luiscastillocr** [comment]
well looks like I am going to need this method after all, happen that there are co-workers that have their slack channel pre-configured in their sanboxes so if someone have it pointing to the same slack channel ID, the SlackChannelConfiguration will throw an error saying the channel is already configured.

> Sry, re-added my previous post, that you were referencing to.
> 
> This is how you can add SNS topics to an existing Slack config.
> 
> ```
> slack_bot = chatbot.SlackChannelConfiguration(
>     chatbot.SlackChannelConfiguration.from_slack_channel_configuration_arn(
>         self,
>         "SlackNotifications",
>         slack_channel_configuration_arn=(
>             f"arn:aws:chatbot::{account}:chat-configuration/slack-channel/test-channel-config"
>         ),
>     )
> )
> 
> slack_bot.add_notification_topic(sns_topic)
> slack_bot.add_notification_topic(another_sns_topic)
> ```

@larskinder I don't think this is possible in NodeJS since you have to mandatory pass the `SlackChannelConfigurationProps` along with a name, so i think i am back to the waiting room for this feature!

**Comment by larskinder** [comment]
Hey, sorry for not getting back to you sooner. About your last question, I only tried it back in the day with Python, sadly never with TS. :( 
I believe other ppl in this channel, when they write that it is not possible in TS. Out of curiosity and because I have to work with TS soon again, I might still take another look at it. ^^

**Comment by vaughan-rich** [comment]
+1

**Comment by YotillaAntoni** [comment]
Same issue here.

**Comment by GavinZZ** [comment]
After team discussion, we are not able to support this feature. 

`fromSlackChannelConfigurationArn` will import an existing slack channel configuration that was created using any other means (i.e. from another stack, or manual creation, or etc.). If we now add `addNotificationTopic` method, it is essentially trying to modify this resource.

If this resource is created/managed using CloudFormation, this will cause CloudFormation stack drift, which is not allowed. If this resource is not managed by CloudFormation, it's impossible to modify the property. 

In CDK, resources referenced via `fromAbc` method are read-only. The interfaces can only have methods that are *read-only* or that are creating/modifying a *different* resource.

**Comment by YotillaAntoni** [comment]
I guess as a workaround one could instead import a topic connected to the slack channel configuration with `Topic.fromArn` into CDK

**Comment by tallpaul-embark** [comment]
I understand not wanting to support the addNotificationTopic in some ways, but if that is the case I feel like we should not be locking down the new slack channel configuration to a channel only being allowed to be used once.
