### ISSUE TITLE
(aws-stepfunctions-tasks): CallApiGatewayHttpApiEndpoint with IAM auth fails with 403

### ISSUE THREAD

**Issue by florianbepunkt** [aws/aws-cdk#21182]
### Describe the bug

CallApiGatewayHttpApiEndpoint with `authType: sfnt.AuthType.IAM_ROLE,` fails with a 403 error for the default stage.

### Expected Behavior

The call should be made with the correct permissions.

### Current Behavior

The task output is 403 `{ "message": "Forbidden" }`

### Reproduction Steps

```ts
const authorizer = new HttpIamAuthorizer();
const mongoDbDataProxyApi = new HttpApi(this, "MongoDB Events Data Api Proxy");
const integration = new HttpUrlIntegration("EventStoreMongoIntegration", MONGO_DATA_API_URI);
mongoDbDataProxyApi.addRoutes({ path: "/{proxy+}", methods: [HttpMethod.POST], integration, authorizer });

const callDataApi = new sfnt.CallApiGatewayHttpApiEndpoint(this, "Persist to Mongo Data API", {
      apiId: mongoDbDataProxyApi.apiId,
      apiStack: cdk.Stack.of(mongoDbDataProxyApi),
      method: sfnt.HttpMethod.POST,
      apiPath: "/find",
      authType: sfnt.AuthType.IAM_ROLE,
    });
```

### CDK CLI Version

2.32.0 (build 00e0c2d)

### Node.js Version

v16.10.0

### OS

Mac OS

### Language

Typescript

**Comment by indrora** [comment]
Your example doesn't grant invocation privileges to the IAM role you're using to access the API endpoint. More information can be found [in the CallApiGatewayHttpEndpoint documentation](https://docs.aws.amazon.com/cdk/api/v1/docs/aws-apigatewayv2-authorizers-readme.html#iam-authorizers).
