### ISSUE TITLE
Manual Installation Instructions are outdated

### ISSUE THREAD

**Issue by cmclaughlin** [aws/aws-cdk#2118]
https://github.com/awslabs/aws-cdk/blob/master/MANUAL_INSTALLATION.md mentions a `bin` directory in the release zip file. But in the latest release (0.27.0) it's not there.

**Comment by craigjam** [comment]
same problem here - is there any alternative to using npm install?

**Comment by NGL321** [comment]
@rix0rrr @Jerry-AWS I just looked into this. The docs need some help in one way or another

**Comment by rix0rrr** [comment]
This doc is still around from our beta period. It is completely inaccurate.
