### ISSUE TITLE
IAM: SLR creation fails if SLR already exists

### ISSUE THREAD

**Issue by rudpot** [aws/aws-cdk#21183]
### Describe the bug

Creating FIS SLR will only work in pristine account. All subsequent attempts of updating or re-creating the stack fail because the SLR already exists with "different description". 

### Expected Behavior

If the SLR already exists this should succeed.

### Current Behavior

After creating FIS SLR with this

```
    const slr = new iam.CfnServiceLinkedRole(this, 'FisRoleSlr', {
      awsServiceName: 'fis.amazonaws.com',
    });
```

subsequent stack updates fail. Even deleting and re-creating the stack fails. Error message from CFN:

```
SLR [AWSServiceRoleForFIS] already exists but has a different description: [Role to enable AWS FIS to manage monitoring and resource selection for experiments.]. Please verify your SLR use case. If you are sure the use case is correct please modify your CloudFormation template and keep SLR description consistent.
```

### Reproduction Steps

Update failure

* create stack with FIS SLR
* update stack (something other than SLR)

Rip and replace failure

* create stack with FIS SLR
* update stack (something other than SLR)
* create stack with FIS SLR

Workaround

* create stack with FIS SLR
* delete stack with FIS SLR
* delete FIS SLR
* pray that no other process is running and re-creating SLR
* create stack with FIS SLR

### Possible Solution

SLR creation should succeed if SLR already exists and has minimum SLR _permissions_, not matching _description_.

### CDK CLI Version

2.15

### Node.js Version

v18.2.0

### OS

OSX

### Language

Typescript

**Comment by rix0rrr** [comment]
This is the behavior enforced by CloudFormation and one that we cannot change.

**Comment by rudpot** [comment]
> This is the behavior enforced by CloudFormation and one that we cannot change.

**This is NOT true. The problem exists in in CDK.**

CloudFormation [docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-servicelinkedrole.html#cfn-iam-servicelinkedrole-customsuffix) stipulate that if you want to create the SLR from multiple stacks then you need to add a `CustomSuffix`. However, if you don't and the role already exists, then the error message is about the missing CustomSuffix which is different from the problem observed here.

Since some services like FIS will auto-create an SLR on first invocation, this is a bug in CDK because it is possible for a CDK stack with an included SLR role to fail on _first_ invocation. 

A workaround for this problem would be for the CDK stack to create a unique CustomSuffix. However, this is fragile because that suffix would likely be stored in cdk.out and if the cdk.out was removed, the CustomSuffix could not be re-created. 

A less desirable solution to the problem would be to make the CustomSuffix field _mandatory_ in the CDK invocation and fix the [documentation](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-iam.CfnServiceLinkedRole.html) to show this.
