### ISSUE TITLE
aws-glue-alpha: specify secret manager secret arn

### ISSUE THREAD

**Issue by adikari** [aws/aws-cdk#21190]
### Describe the issue

I am trying to create glue connection using cdk. The connection is to the aurora database inside vpc. I have gotten connection setup and working via the AWS console and currently trying to automate it with cdk. I am getting stuck in the part where have to specify connection properties and its not well documented on at properties need to be passed.

Here is what I got working and deployed to aws

![image](https://user-images.githubusercontent.com/1757714/179432203-a5e7f9ae-46aa-4524-a973-1972b895e68f.png)

However, I want to replace the `username` and `password` with the secret from AWS Secret Manager. When I setup the RDS cluster, I am using `Credentials.fromGeneratedSecret` which seem to create secret in secret manager. I looked around for documentation on how to specify the secret manager secret arn in cdk but could not figure out how.

This is possible via the AWS console. Please see the screenshot below.

<img width="871" alt="image" src="https://user-images.githubusercontent.com/1757714/179432288-068a33c0-d2ad-462d-a89f-945b8282ff04.png">

### Links

https://docs.aws.amazon.com/cdk/api/v2/docs/@aws-cdk_aws-glue-alpha.Connection.html#propertiesspan-classapi-icon-api-icon-experimental-titlethis-api-element-is-experimental-it-may-change-without-noticespan

**Comment by WinterYukky** [comment]
Thanks @adikari for opening this issue!

You can use `DatabaseCluster.secret.secretName` for `SECRET_ID`. Please refer to the following code.
```ts
declare const db: DatabaseCluster;
new glue.Connection(this, "RdsVpcConnection", {
  type: glue.ConnectionType.JDBC,
  securityGroups: [secrityGroup],
  subnet,
  properties: {
    JDBC_CONNECTION_URL: `jdbc:${protocol}://${db.clusterEndpoint.socketAddress}/${name}`,
    JDBC_ENFORCE_SSL: "false",
    SECRET_ID: db.secret?.secretName!,
  },
});
 ```

Note that this is a common use case and needs to be documented.
I will open a PR later.

Ref: 
- https://docs.aws.amazon.com/glue/latest/dg/aws-glue-api-catalog-connections.html#aws-glue-api-catalog-connections-Connection

**Comment by peterwoodworth** [comment]
Thanks for the explanation! Are you still able to open a PR for this @WinterYukky?

**Comment by WinterYukky** [comment]
Thanks for reminding me, @peterwoodworth !
I opened PR #21905.
