### ISSUE TITLE
aws_kms: You can create only one replica of each primary key in each AWS Region.

### ISSUE THREAD

**Issue by Dgarc359** [aws/aws-cdk#21203]
### Describe the bug

I have created a cfnReplicaKey construct in an aws CDK project, and on updating the stack, update fails and rolls back, due to the error:
You can create only one replica of each primary key in each AWS Region.

### Expected Behavior

Similar to other aws cdk constructs, if the stack is merely being updated, the resource shouldn't be attempted to be created again.

### Current Behavior

Deploying a cdk update leads to failed deploy past initial deploy due to attempting to make a new replica key.
This issue makes updating cdk cloudformation stacks impossible. I must now tear down my whole stack just to properly update it.

### Reproduction Steps

create a cfnReplicaKey in a new stack and try to deploy an update **after** you have deployed the stack with the replica key

### CDK CLI Version

2.24.0

### Node.js Version

16.13.1

### OS

Mac

### Language

Typescript

**Comment by Dgarc359** [comment]
Errr, apologies, it seems that the issue might be that the stack properties got updated and it was attempting to make a whole brand new stack, as opposed to updating the old one. Sorry for the confusion

**Comment by Dgarc359** [comment]
Reopening this issue, I found that my diagnosis of the problem is incorrect, my original issue still stands

**Comment by Dgarc359** [comment]
I'd like to add this also makes development hard because of how deleting KMS keys work, if I delete the stack, and add a deletion policy to the keys, then the lowest time frame I'd be able to delete them out is 7 days. If I'm working on a prototype solution, this is way too much time to have to wait before I can deploy a fresh stack that would create a new replica key.

**Comment by peterwoodworth** [comment]
Sorry for the long response time @Dgarc359,

Unfortunately this is just how CloudFormation works in tandem with the KMS limitation of one replica per region. If you make a change to a resource that requires resource replacement then the resource will have a copy created before the original is destroyed. This leads to two keys existing at the same time which is not possible. The best way to resolve this is unfortunately to delete the stack/resource

**Comment by FireAndIceFrog** [comment]
this has basically disabled our deployment. I tried to delete the stack and re-create it but it has only flagged the key as being deleted. 

Its not a viable solution to delete and recreate the stack when this is the case, you will have to wait a week if not more for the same key to exist.
