### ISSUE TITLE
Japanese strings are garbled by the cdk diff command.

### ISSUE THREAD

**Issue by kawaji** [aws/aws-cdk#2121]
Japanese strings are garbled by the cdk diff command.
The character code used is UTF-8.

The case I am checking
Cognito's [Message customizations]
Other than that
It is lambda deployed with Custom Resource.

If you run cdk diff immediately after cdk deploy, it will be garbled.

cdk --version
0.27.0 (build 7638a58)

**Comment by SomayaB** [comment]
Hi, I apologize for the late reply. Are you still experiencing this issue?

**Comment by SomayaB** [comment]
Closing this issue since there hasn't been activity on it in a while. Feel free to reopen if you are still experiencing this issue.
