### ISSUE TITLE
(cognito): Support for all SES regions

### ISSUE THREAD

**Issue by ludimax** [aws/aws-cdk#21245]
### Describe the feature

Currently sesRegion property only support regions 'us-east-1', 'us-west-2', or 'eu-west-1'. See also documentation https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-cognito.UserPoolSESOptions.html. It should be possible to use all available Cognito SES regions. Via the console this is already possible. 

### Use Case

Enable SES in Cognito in other regions as well (for example eu-central-1)

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

1.165.0

### Environment details (OS name and version, etc.)

n/a

**Comment by peterwoodworth** [comment]
We don't have any checks to ensure you're typing in a valid region. I think you should be able to deploy this successfully now if you ignore the documentation
