### ISSUE TITLE
Feature Request: Leverage GetAzs for VPC creation

### ISSUE THREAD

**Issue by cpollard0** [aws/aws-cdk#2124]
If you're using the cdk synth function to generate CloudFormation which contains a VPC where AZs haven't been explicitly set, would it be better to generate: 

`AvailabilityZone: !Select [0, !GetAZs '']`

instead of what gets generated:

`AvailabilityZone: us-east-1a`

**Comment by eladb** [comment]
So the proposal is to only use a single AZ for such VPCs (or maybe 2...). @PaulMaddox I am curious what you think about this... I think the current implementation heavily relies on this knowledge but I might be wrong.

**Comment by PaulMaddox** [comment]
cpollard@ can you provide a bit more context here on what you’re trying to do?

**Comment by cpollard0** [comment]
If I’m using CdK to synth CloudFormation that I want to be flexible for multiple regions using the GetAz functionality seems more flexible than hard coding the AZ. 

This isn’t recommending one AZ; us-east-1b would grab index 1 of the GetAz return and so on. 

Also, this provides some consistency between the CloudFormation that CdK synthesizes and what cfn-lint recommends for best practices. Right now, there is a warning on the AZ call outs.

**Comment by eladb** [comment]
How many subnets would you define for such as VPC? You don't really know how many AZs are available in each region?

**Comment by SomayaB** [comment]
@eladb What was the resolution on this issue? Can we close it or are we still considering it?

**Comment by eladb** [comment]
This is resolved. Environment-agnostic stacks will automatically use the first 2 AZs and users can also override `Stack.availablilityZones` to return whatever they want.
