### ISSUE TITLE
[stepfunctions] : Pass Multiple Parameters in ContainerOverride Command of EcsRunTask

### ISSUE THREAD

**Issue by SanyuktaAgrawal** [aws/aws-cdk#21242]
### Describe the bug

According to [this](https://github.com/aws/aws-cdk/issues/9253) closed bug, I am trying to pass json value arguments in array in `containerOverrides` of `ECSRunTask`. I am using `JsonPath.ListAt` method for the same. But it is giving me error at the time of deployment `The value for the field 'Command.$' must be a valid JSONPath or a valid intrinsic function call`

### Expected Behavior

The solution should deploy and passed arguments x,y,z should be visible inside Fargate while running the task inside step function

### Current Behavior

Current solution is giving me error at the time of deployment `The value for the field 'Command.$' must be a valid JSONPath or a valid intrinsic function call`

### Reproduction Steps

```
const vpc = ec2.Vpc.fromLookup(this, 'Vpc', {
  isDefault: true,
});

const cluster = new ecs.Cluster(this, 'FargateCluster', { vpc });

const taskDefinition = new ecs.TaskDefinition(this, 'TD', {
  memoryMiB: '512',
  cpu: '256',
  compatibility: ecs.Compatibility.FARGATE,
});

const containerDefinition = taskDefinition.addContainer('TheContainer', {
  image: ecs.ContainerImage.fromRegistry('foo/bar'),
  memoryLimitMiB: 256,
});

const riTask = new tasks.EcsRunTask(this, 'The task', {
      integrationPattern: IntegrationPattern.RUN_JOB,
      cluster: cluster,
      taskDefinition: taskDefinition,
      containerOverrides: [{
        containerDefinition: containerDefinition,
        command: JsonPath.listAt("$.States.Array('/app/appName', $.x, $.y, $.z)"),
      }],
      launchTarget: new tasks.EcsFargateLaunchTarget(),
    });
```

### CDK CLI Version

 2..8.0

### Node.js Version

v16.16.0

### OS

Platform independent

### Language

Typescript

**Comment by kaizencc** [comment]
Hi @SanyuktaAgrawal, have you tried using `JsonPath.array()`? I believe that is the API you are going for.

**Comment by MieladN** [comment]
> Hi @SanyuktaAgrawal, have you tried using `JsonPath.array()`? I believe that is the API you are going for.

Using a JsonPath.Array() will not work in this instance. For some reason, you can do JsonPath.ListAt, but not JsonPath.Array

If you do that, you'll get

"Type 'string' is not assignable to type 'string[]'"
