### ISSUE TITLE
(module name): (short issue description)

### ISSUE THREAD

**Issue by pkengne** [aws/aws-cdk#21246]
### Describe the bug

I integrated a angular package to my cdk package in order to deploy a static website, but the build of the angular package returns an empty zip file 

### Expected Behavior

Deploying the zip file in the asset bucket

### Current Behavior

[50%] fail: 🚨 WARNING: EMPTY ZIP FILE 🚨
[50%] fail: 
[50%] fail: Zipping this asset produced an empty zip file. We do not know the root cause for this yet, and we need your help tracking it down.
[50%] fail: 
[50%] fail: Please visit https://github.com/aws/aws-cdk/issues/18459 and tell us:
[50%] fail: Your OS version, Nodejs version, CLI version, package manager, what the asset is supposed to contain, whether
[50%] fail: or not this error is reproducible, what files are in your cdk.out directory, if you recently changed anything,
[50%] fail: and anything else you think might be relevant.
[50%] fail: 
[50%] fail: The deployment will continue, but it may fail. You can try removing the cdk.out directory and running the command
[50%] fail: again; let us know if that resolves it.
[50%] fail: 
[50%] fail: If you meant to produce an empty asset file on purpose, you can add an empty dotfile to the asset for now
[50%] fail: to disable this notice.

### Reproduction Steps

static-web-site-stack.ts
import {Construct} from "constructs";
import {BrazilPackage, DeploymentStack, DeploymentStackProps, LambdaAsset} from "@amzn/pipelines";
import {CopyMode, IStaticWebsiteDistributionProps, StaticWebsite} from "@amzn/cdk-bones";
import {Bucket} from "aws-cdk-lib/aws-s3";
import {PolicyStatement} from "aws-cdk-lib/aws-iam";
import {CloudFrontAllowedMethods} from "aws-cdk-lib/aws-cloudfront";

import * as path from "path"

const fs = require('fs')

export interface staticwebsiteProps extends DeploymentStackProps {
    readonly stage: string;
    readonly domainName: string;
}

export class websiteStack extends DeploymentStack {
    constructor(scope: Construct, id: string, readonly props: staticwebsiteProps) {
        super(scope, id, props);

        // This makes the BATS transform emit a single zip file that contains the build folder.
        const websiteAsset = LambdaAsset.fromBrazil({
            //componentName: "websiteAsset",
            componentName: "amazon-rde-ui",
            brazilPackage: BrazilPackage.fromString ('AmazonPsrImproveCopyPKG')
        }).bind(this)

        // Use additionalPolicyStatements to grant the static website copier access to BARS artifacts.
        const additionalPolicyStatements = [];
        const barsKeyArn = this.deploymentEnvironment.barsEnvironment.kmsImportedKeyArn;
        if (barsKeyArn) {
            additionalPolicyStatements.push(new PolicyStatement({
                actions: ['kms:Decrypt'],
                resources: [barsKeyArn],
            }));
        }

        if (!websiteAsset.s3Location) {
            throw new Error("website Asset doesn't have an S3 location");
        }

        // Tell StaticWebsite where to find the BARS artifacts and how to copy them
        const distributionProps: IStaticWebsiteDistributionProps = {
            artifactCopyConfiguration: {
                copyMode: CopyMode.ROOT,
                sourceBucket: Bucket.fromBucketName(this, 'DeploymentBucket', websiteAsset.s3Location.bucketName),
                sourceKey: websiteAsset.s3Location.objectKey,
                additionalPolicyStatements,
            },
        };

        // Read 403.html file for CloudFrontSigner redirect on 403 errors
        const forbiddenErrorFile = fs.readFileSync(path.join(__dirname, "..", "src", "error", "403.html"), {
            encoding: "utf8"
        });

        // Finally, build the StaticWebsite construct
        new StaticWebsite(this, 'Website', {
            dns: {
                hostedZoneName: props.domainName,
            },
            website: {
                ...distributionProps,
                artifactCopyConfiguration: {
                    ...distributionProps.artifactCopyConfiguration,
                    injectedArtifacts: [
                        {
                            path: "/error/403.html",
                            content: forbiddenErrorFile
                        }
                    ],
                    zipSubfolder: "app",

                    settings: {
                        "apiEndpoint": "https://0rz8ufdak8.execute-api.us-west-2.amazonaws.com/beta",
                        "cognitoPoolId": "us-west-2:2463b77f-9f95-4955-8ec9-ec0b7ee4bf43",
                        "region": "us-west-2"
                    }

                },
                behaviors: [
                    {
                        isDefaultBehavior: true,
                        allowedMethods: CloudFrontAllowedMethods.GET_HEAD,
                        /*
                        trustedSigners: [
                            "076938169600"
                        ]

                         */
                    }
                ],
                invalidationKey: this.packagingAggregateIdParameter.value,
                invalidationPaths: ["/*"],
                singlePageWebapp: true,
                additionalErrorHandlers: [
                    {
                        errorCode: 403,
                        responseCode: 403,
                        responsePagePath: "/error/403.html"
                    }
                ]
            },
        });
    }
}

app.ts

import {
  BrazilPackage,
  SoftwareType,
  DependencyModel,
  BakeTimeApprovalWorkflowStep,
  CodeReviewVerificationApprovalWorkflowStep,
  DeploymentEnvironmentFactory,
  DeploymentPipeline, DogmaTagsOptions,
  Platform,
  Stage
} from '@amzn/pipelines'

import {App} from 'aws-cdk-lib';

import {anamzonRDEInfrastructureCoreStack} from "./stacks/Infrastructure-core-stak";
import {amazonRDEStaticWebSite} from "./stacks/s3-static-website-stack";
import {amazonRDEWaf} from "./stacks/waf";

import {apigwlambdastack} from "./stacks/apigwlambda-stack2";
import {cognito_apigw_lambda_Stack} from "./stacks/cognito-apigw-lambda-stack";
import {websiteStack} from "./stacks/static-website-stack";

// Set up your CDK App
const app = new App();

// const pipelineId = '4302582';
const region = 'us-east-2';

const devAccount = '424975656753';
const integAccount = '281368221808';
const prodAccount = '359643179693';
const pipelineId = '4302582';

const betaCertificateArn = ''
    // 'arn:aws:acm:us-east-1:979309758703:certificate/e96d23f5-5fca-4851-93bb-d2e5569b7ef5';
const prodCertificateArn = ''
    // 'arn:aws:acm:us-east-1:110083584031:certificate/ea455ad4-ada7-446e-9643-20bc00909693';

const devDomainName = 'app.psrscandev.robotics.a2z.com'
const integDomainName = 'app.psrscanuat.robotics.a2z.com'
const prodDomainName = 'app.psrscan.robotics.a2z.com'

const applicationAccount = integAccount;

const domainName = integDomainName;

const pipeline = new DeploymentPipeline(app, 'Pipeline', {
  account: applicationAccount,
  pipelineName: 'AmazonRDEImprovement',
  //versionSet: 'AmazonRDEImprovement/development', // The version set you created
  versionSet: {
    name: 'AmazonRDEImprovement/development', // The version set you created
    dependencyModel: DependencyModel.BRAZIL,
  },
  versionSetPlatform: Platform.AL2_X86_64,
  trackingVersionSet: 'live', // Or any other version set you prefer
  bindleGuid: 'amzn1.bindle.resource.bu2345z74uhhz5fkxe2q',
  description: 'Simple CDK Pipeline',
  pipelineId: pipelineId,
  selfMutate: true,
});

[
  'AmazonPsrImproveCopyPKG'
].map(pkg => pipeline.addPackageToAutobuild(BrazilPackage.fromString(pkg)));

const stageName = 'uat';
const alphaStage = pipeline.addStage(stageName, { isProd: false });
const deploymentGroup = alphaStage.addDeploymentGroup({
  name: `alphaApplication`
});

const websitestack = new websiteStack(app, `amazonRDEImproveCDK1-staticwebsite-${stageName}`, {
  ...deploymentProps,
  domainName: 'kengnbpi.people.amazon.dev'

});
deploymentGroup.addStacks(websitestack);

### CDK CLI Version

2.23

### Node.js Version

14.0

### OS

amazon linux 2

### Language

Typescript

**Comment by peterwoodworth** [comment]
As the error message says, could you please share this in #18459 where we're tracking this? Thanks 🙂
