### ISSUE TITLE
npm package: aws-cdk@1.165.0 release is not published to npm registry

### ISSUE THREAD

**Issue by teddified** [aws/aws-cdk#21247]
### Describe the bug

aws-cdk@1.165.0 release is not published to npm registry

### Expected Behavior

should not throw an error when running `npm ci`

### Current Behavior

when running `npm ci` this error is thrown `No matching version found for aws-cdk@1.165.0.`. 
in my package.json I tried both: 

`"@aws-cdk/core": "^1.165.0"`
`"@aws-cdk/core": "^1.163.0"`

in combination with `"aws-cdk": "^1.163.0"`
and still get the same error message.

I checked all peerDependencies of all packages and none is using the 1.165.0 version.

### Reproduction Steps

the package.json should include both

`"@aws-cdk/core": "^1.163.0"`
and `"aws-cdk": "^1.163.0"`

then run `npm ci`.

### Possible Solution

publish aws-cdk@1.165.0 to npm registry

### CDK CLI Version

1.165.0

### Node.js Version

16.13.1

### OS

macOS

### Language

Typescript

**Comment by corymhall** [comment]
@teddified this should now be resolved. Let me know if you still see any issues
