### ISSUE TITLE
(route53): `CrossAccountZoneDelegationRecord` does not remove old NS records when the `zoneName` changes

### ISSUE THREAD

**Issue by moltar** [aws/aws-cdk#21249]
### Describe the bug

When changing the `zoneName` value of the `PublicHostedZone` the old NS entries in the delegated zone are not removed.

I think this is because when the logical ID did not change, the custom resource event type is still `UPDATE` and judging by the handler code, it does not handle this edge case.

https://github.com/aws/aws-cdk/blob/cea1039e3664fdfa89c6f00cdaeb1a0185a12678/packages/%40aws-cdk/aws-route53/lib/cross-account-zone-delegation-handler/index.ts#L25-L51

### Expected Behavior

Old NS records to be removed.

### Current Behavior

NS records remain in the delegated (parent) zone.

### Reproduction Steps

Deploy:

```ts
    const hostedZone = new PublicHostedZone(this, 'PublicZone', {
      zoneName: 'abc.example.com',
    })

    new CrossAccountZoneDelegationRecord(this, 'Delegate', {
      delegationRole: 'arn...',
      delegatedZone: hostedZone,
      parentHostedZoneId: 'xyz',
    })
```

Then change `zoneName` value to `abc2.example.com` and deploy again.

Observe that NS records for `abc.example.com` remain.

### Possible Solution

Compare `zoneName` values with the existing resource and delete it when the name chagnes.

### CDK CLI Version

2.29.1 (build c42e961)

### Framework Version

TS

### Node.js Version

v14.19.3

### OS

macOS

### Language

Typescript

### Language Version

TS 4.7.4

**Comment by ayush987goyal** [comment]
Yeah seems like a bug to me. We might need a separate handler for the UPDATE case perhaps and some corresponding refactoring. One callout is that the current implementation should technically work since it would still add the nameservers for the new hosted zone name.

**Comment by garciparedes** [comment]
Hi! I would like to come this issue alive again as I'm also being affected by the same issue.

As @moltar described, if the `zoneName` changes the current implementation will insert the new `NS` record on the parent Hosted Zone but will keep the old one so it leaves a dangling `NS` record which MUST be removed manually. If it is not removed, it may allow an attacker to control the subdomain and serve content in your name.

**Comment by QwerTech** [comment]
Looks like the issue is still present, and it's currently reproducing for me with CDK 2.40.0 (build 56ba2ab).
Checked the PR https://github.com/aws/aws-cdk/pull/25285, and it seems it was closed without merging. I hope @garciparedes you can republish your PR to finally fix the issue.

**Comment by garciparedes** [comment]
I've just republished the #27523 CR adding the missing integration tests from previous one.
