### ISSUE TITLE
How to specify stack creation and rollback timeout?

### ISSUE THREAD

**Issue by BerndWessels** [aws/aws-cdk#2125]
Very often (especially with CustomResources) Cloudformation fails to create the stack - BUT it takes about **1 hour** for Cloudformation to recognize this and then **another hour** to rollback. This is **incredibly frustrating** if you try to get things done!

Is there a way to set a `timeout` to lets say 5 minutes for stack creation and rollback to speed up trial and error development and deployment?

**Comment by eladb** [comment]
It’s a great idea but sadly unsupported by CloudFormation. We are trying to look for ways to make it easier to author custom resources. For example, a common reason for those to hang the stack is if they don’t submit a response when an exception is thrown. Maybe we can integrate with a framework for custom resources that will make it easier to implement without making those mistakes.

**Comment by amoraes** [comment]
There is support for timeout in the CloudFormation (see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-console-add-tags.html) but I can't find how to use this in CDK.
I am interested in this feature as well, waiting that much for a rollback is painful.

**Comment by zxkane** [comment]
Same here. This feature will be useful when composing CDK and deploying stack for testing.

**Comment by zxkane** [comment]
Add CF `WaitCondition` in your stack could configure the timeout of stack,

```ts
 const waitHandle = new cfn.CfnWaitConditionHandle(this, 'WaitConditionHandle');
    const waitCondition = new cfn.CfnWaitCondition(this, 'WaitCondition', {
      count: 1,
      handle: waitHandle.ref,
      timeout: '600'
    });
 scope.node.addDependency(waitCondition);
```

**Comment by eladb** [comment]
Resolved by #4572

**Comment by BerndWessels** [comment]
@eladb hello,
I'm not sure if I understand, how it that fixing the issue?
Could you please provide a short example here?
Thanks

**Comment by aripalo** [comment]
@BerndWessels I was baffled by this too, but after looking at #4572 PR realized I should use `Provider` from `@aws-cdk/custom-resources` (instead of `cloudformation.CustomResourceProvider`).

See: https://docs.aws.amazon.com/cdk/api/latest/docs/custom-resources-readme.html#timeouts

**Comment by damnhandy** [comment]
@eladb this absolutely does not address the issue. What folks are really looking for is the CDK equivalent to [`--timeout-in-minutes`](https://docs.aws.amazon.com/cli/latest/reference/cloudformation/create-stack.html) that is part of the AWS CLI today. Even if this was something that is set from the CDK CLI that would be more than acceptable.

**Comment by antonfelich** [comment]
+1 to @damnhandy that's exactly what I'm currently looking for

**Comment by wcheek** [comment]
+1 Currently waiting an inordinate amount of time for a rollback to complete.

**Comment by joeyvmason** [comment]
+1 This is really painful and makes it hard to use CDK for production apps

**Comment by dilunika** [comment]
+1 this is really annoying specially with Fargate

**Comment by BrunoHenrique00** [comment]
+1 please add equivalent to [--timeout-in-minutes](https://docs.aws.amazon.com/cli/latest/reference/cloudformation/create-stack.html) that is part of the AWS CLI today. Wasting a lot of time when building stacks

**Comment by alecswan** [comment]
+1 i had to wait several hours for ECS stack to rollback

**Comment by will-rs** [comment]
+1 The need for a fix of this issue is blazingly apparent when deploying Fargate services whose containers exit unexpectedly. It takes _way_ too long for Fargate to realize the service will not become stable. If anyone is in need for a quick fix, just go into the console and select `Stack actions` -> `Cancel update stack`

Obviously, this does not work if you are deploying the stack for the first time.

**Comment by TheKnightCoder** [comment]
+1 Please fix this

**Comment by marcelosousa** [comment]
+1 I'm about to give up using CDK in production because of this issue. It's totally unrealistic to expect people to wait hours for rollbacks when you're using Fargate.

**Comment by mrgrain** [comment]
This issue was close because it was interpreted to be related to Custom Resources - which was fixed.

For a `--timeout` flag, please pile on to https://github.com/aws/aws-cdk/issues/24792 or create a new issue.
