### ISSUE TITLE
(assertions): match properties against *all* resources of a given type

### ISSUE THREAD

**Issue by joel-aws** [aws/aws-cdk#21269]
### Describe the feature

Given a Stack with resources of the same type (e.g., `AWS::S3::Bucket`), easily apply assertions against all of those resources.

Currently, `has_resource_properties()` (and similar methods) returns `True` if a single resource matches, even if other resources don't match.

### Use Case

Given a stack with two S3 Buckets:

```python
s3.Bucket(self, "aes", encryption=s3.BucketEncryption.S3_MANAGED)
s3.Bucket(self, "no-aes", encryption=s3.BucketEncryption.UNENCRYPTED)
```

When a `has_resource_properties` assertion is run against `AWS::S3::Bucket` resources:

```python
template.has_resource_properties(
    type="AWS::S3::Bucket",
    props={
        "BucketEncryption": {
            "ServerSideEncryptionConfiguration": [
                {"ServerSideEncryptionByDefault": {"SSEAlgorithm": "AES256"}}
            ]
        }
    },
)
```

Then the test will fail, as only one of the Buckets has SSE enabled. As is implemented now, the test passes.

### Proposed Solution

* Add a boolean property, like: `has_resource_properties(match_all_resources=True)`, such that all resources of a given type must match the `props`, else it will return `False`.
* Implement a new method like `has_resources_properties()` that applies to all resources of a given type.

Also:
* Make it very obvious in the documentation that `has_resource_properties` (and similar methods) will return `True` if a single match is found.

### Other Information

cc: @mrgrain 

### Acknowledgements

- [ ] I may be able to implement this feature request
- [x] This feature might incur a breaking change

### CDK version used

2.33.0

### Environment details (OS name and version, etc.)

MacOS 11.6.7

**Comment by kaizencc** [comment]
`Match.allResources()` is something we could implement.
