### ISSUE TITLE
aws-events: Archive construct does not have defaultChild set

### ISSUE THREAD

**Issue by Gtofig** [aws/aws-cdk#21263]
### Describe the bug

Archive construct has defaultChild as `undefined` instead of an instance of `CfnArchive`

### Expected Behavior

I expect `archive.node.defaultChild` to return instance of `CfnArchive`, but it is currently undefined

### Current Behavior

`archive.node.defaultChild` returns undefined

### Reproduction Steps

```ts
const app = new App();
const stack = new Stack(app);
const eventBus = new EventBus(stack, 'eventbus', {
      eventBusName: 'EventBus',
    });
const archive = new Archive(eventBus, 'archive', {
      sourceEventBus: eventBus,
      eventPattern: {
        source: ['test'],
      },
    });
const cfnArchive = archive.node.defaultChild as CfnArchive; // This fails
```

### CDK CLI Version

2.20.0

### Node.js Version

14.19.1

### OS

Ubuntu 18

### Language

Typescript

### Language Version

4.4.4

**Comment by rix0rrr** [comment]
That's unfortunate. Someone must have used the wrong construct id.
