### ISSUE TITLE
core: Please implement .editorconfig

### ISSUE THREAD

**Issue by kellertk** [aws/aws-cdk#21273]
### Describe the feature

Sometimes when I'm editing CDK, it's difficult to enforce a consistent style, even with linters like eslint, etc.

### Use Case

I'm constantly doing things like putting spaces at the end of lines or forgetting a newline at the end of a file when developing on CDK. Mostly this is caught at `yarn build` but it's annoying to have to go back and fix. Admittedly, this is something a linter plugin could catch too.

### Proposed Solution

Implement `.editorconfig`. From the [editorconfig page](https://editorconfig.org/)

> EditorConfig helps maintain consistent coding styles for multiple developers working on the same project across various editors and IDEs. The EditorConfig project consists of a file format for defining coding styles and a collection of text editor plugins that enable editors to read the file format and adhere to defined styles. EditorConfig files are easily readable and they work nicely with version control systems.

Editorconfig plugins are available for vscode and a lot of other IDEs.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

aws/aws-cdk@main

### Environment details (OS name and version, etc.)

N/A

**Comment by rix0rrr** [comment]
Since our rules are defined in `eslint`, the best way to make sure you are compliant with the rules is to have eslint checked in your editor.

For example, I use this one: https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint
