### ISSUE TITLE
CLI: Bootstrapping fails when adding tags to existing KMS key

### ISSUE THREAD

**Issue by Obirah** [aws/aws-cdk#21281]
### Describe the bug

When re-bootstrapping an existing CDKToolkit stack that contains a customer managed KMS key, the update fails if tags are added.

### Expected Behavior

The stack update should be successful and the tags should be applied to the existing resources.

### Current Behavior

The stack update fails because the file bucket encryption key lacks the `kms:TagResource` permission.

### Reproduction Steps

* Bootstrap without tags:
  * `cdk bootstrap --bootstrap-customer-key  aws://<account-id>/<region>`
* Update with tags:
  * `cdk bootstrap --bootstrap-customer-key  aws://<account-id>/<region> --tags foo=bar`
  * Update fails with the error `"Access denied for operation 'TagResource'."`

### Possible Solution

Add the permissions for KMS tagging/untagging to the customer key.

### CDK CLI Version

2.33.0

### Node.js Version

16.x

### OS

MacOS 12.4

### Language

Typescript

**Comment by peterwoodworth** [comment]
I think this should be a simple fix - just adding UntagResource and TagResource permissions should do the trick. @rix0rrr is there any reason we can't add these permissions to the template?

**Comment by adrianmace** [comment]
As mentioned in the linked issue, we have an internal tool that uses CDK under the hood.

Due to this bug we cannot easily bump the CDK version in use, as it attempts to bootstrap with the newer version and fails.

**Comment by weijiany** [comment]
After we use CDK 2.30.0, we can no longer upgrade the bootstrap version of CDK. 
For now, the CDK's latest version is 2.43.0, We're 13 minor versions behind it. 😢

**Comment by forward2you** [comment]
Hi team, is there any update on this issue?
We are blocked with this issue for 4 months and cannot use the latest CDK version. :pensive:

**Comment by rix0rrr** [comment]
>  I think this should be a simple fix - just adding UntagResource and TagResource permissions should do the trick. @rix0rrr is there any reason we can't add these permissions to the template?

Yes there is. The User or Role doing the bootstrapping is not itself in the template. The policy we are talking about is whatever User or Role the customer (you) chooses to do their bootstrapping with.

That means the customer (you) is in full control of the policy, and can choose to add `kms:TagResource` permissions to the policy. There is nothing for us to do here, as we don't control the IAM policy of the user you choose to use.

![image](https://user-images.githubusercontent.com/524162/211518855-b06f89ab-db4e-45ff-9d05-c204a6e0f036.png)

**Comment by adrianmace** [comment]
@rix0rrr The IAM policy does allow TagResource, but the KMS key policy does not allow tags to be updated or removed from the key. Please see [this PR](https://github.com/aws/aws-cdk/pull/21975/files#diff-4fdac38426c4747aa17d515b01af4994d3d2f12c34f7b6655f24328259beb7bfR109) where I have fixed this issue, but it was closed automatically because I was able to test it successfully (a limitation of my own knowledge).

I don't believe this issue should be closed.

**Comment by rix0rrr** [comment]
Ah, my mistake! I'm very sorry. I keep on forgetting that KMS keys are different than all other AWS resources in how they handle policies 😔
