### ISSUE TITLE
(dynamodb): DeletionPolicy & UpdateReplacePolicy tests fail erroneously

### ISSUE THREAD

**Issue by tlindsay42** [aws/aws-cdk#21300]
### Describe the bug

Jest tests for `template.hasResource('AWS::DynamoDB::Table', {DeletionPolicy: 'Delete', UpdateReplacePolicy: 'Delete' });` for a table with `removalPolicy: RemovalPolicy.DESTROY` set fails due to finding `Retain`, even though it is set correctly to `Delete` in the CloudFormation template. 

This logic works correctly for other resources, such as a S3 bucket.

### Expected Behavior

Tests should detect UpdateReplace & Deletion policy Delete values and pass.

### Current Behavior

Tests detect UpdateReplace & Deletion policy Retain values and fail- even though the resultant CloudFormation template has the policies set correctly.

### Reproduction Steps

Using the [CDK workshop](https://cdkworkshop.com/) as an example of the issue, the [cleanup step](https://cdkworkshop.com/20-typescript/60-cleanups.html) adds `removalPolicy: RemovalPolicy.DESTROY` to the DynamoDB table, but the output near the bottom of the [assertion test step](https://cdkworkshop.com/20-typescript/70-advanced-topics/100-construct-testing/1000-assertion-test.html) shows `"UpdateReplacePolicy": "Retain", "DeletionPolicy": "Retain"`.

The deployed CloudFormation template has these values set correctly, but cdk isn't detecting it for some reason.

#### CloudFormation excerpt

```json
 "HelloHitCounterHits7AAEBF80": {
   "Type": "AWS::DynamoDB::Table",
...
   "UpdateReplacePolicy": "Delete",
   "DeletionPolicy": "Delete",
   "Metadata": {
    "aws:cdk:path": "HelloCdkStack/HelloHitCounter/Hits/Resource"
   }
  },
```

#### Example HitCounter test

```typescript
  test('Create DynamoDB table', () => {
    template.hasResource('AWS::DynamoDB::Table', {
      DeletionPolicy: 'Delete',
      UpdateReplacePolicy: 'Delete',
    });
  });
```

#### Example `npm test run` output

```sh
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> hello-cdk@0.0.1 test
> jest --testPathIgnorePatterns=ignore "run"

 FAIL  test/hitcounter.test.ts (10.154 s)
  ● HitCounter › Create DynamoDB table
                                                                                                                                                                     
    Template has 1 resources with type AWS::DynamoDB::Table, but none match as expected.                                                                             
    The closest result is:                                                                                                                                           
      {                                                                                                                                                              
        "Type": "AWS::DynamoDB::Table",                                                                                                                              
...
        "UpdateReplacePolicy": "Retain",
        "DeletionPolicy": "Retain"
      }
    with the following mismatches:
        Expected Delete but received Retain at /DeletionPolicy (using objectLike matcher)
        Expected Delete but received Retain at /UpdateReplacePolicy (using objectLike matcher)

      42 |
      43 |   test('Create DynamoDB table', () => {
    > 44 |     template.hasResource('AWS::DynamoDB::Table', {
         |              ^
      45 |       DeletionPolicy: 'Delete',
      46 |       UpdateReplacePolicy: 'Delete',
      47 |     });

      at Template.hasResource (node_modules/aws-cdk-lib/assertions/lib/template.js:1:1590)
      at Object.<anonymous> (test/hitcounter.test.ts:44:14)
```

Using the [CDKv2 Getting Started example](https://docs.aws.amazon.com/cdk/v2/guide/hello_world.html#hello_world_tutorial_modify) as an example of this working properly for a S3 resource, the [Modifying your app step](https://docs.aws.amazon.com/cdk/v2/guide/hello_world.html#hello_world_tutorial_modify) adds `removalPolicy: RemovalPolicy.DESTROY` to the S3 bucket, and adding a test for it succeeds as expected.

#### Example S3 bucket test

```typescript
  test('Create S3 bucket', () => {
    template.hasResource('AWS::S3::Bucket', {
      DeletionPolicy: 'Delete',
      UpdateReplacePolicy: 'Delete',
    });
  });
```

#### Example `npm test run` output

```sh
√ Create S3 bucket (2 ms) 
```

### Possible Solution

Tests for CDK generated DynamoDB resources should be able to detect the configured `UpdateReplacePolicy` and `DeletionPolicy` values.

### CDK CLI Version

2.33.0 (build 859272d)

### Node.js Version

v16.16.0

### OS

Windows 11

### Language

Typescript

### Language Version

4.7.4

**Comment by MrArnoldPalmer** [comment]
@tlindsay42 I think the issue here may be usage of `hasResourceProperties` vs `hasResource` from the assertions library. IE, if you are asserting against a resources `Properties` object you can use the `hasResourceProperties` shorthand, but you can't check `DeletionPolicy` or `UpdateReplacePolicy` because these are properties one level higher in the CFN template.

As far as I can tell, `hasResourceProperties` works correctly to assert against these properties on a DDB Table.
<details>
<summary>My code that works</summary>

```ts
    new ddb.Table(this, "MyTable", {
      tableName: 'MyTable',
      partitionKey: {
        name: 'id',
        type: ddb.AttributeType.STRING,
      },
      removalPolicy: cdk.RemovalPolicy.DESTROY,
    });
```
test
```ts
test('Dynamo Table With Delete', () => {
  const app = new cdk.App();
    // WHEN
  const stack = new Issue21300.Issue21300Stack(app, 'MyTestStack');
    // THEN
  const template = Template.fromStack(stack);

  template.hasResource('AWS::DynamoDB::Table', {
    Properties: { 
      TableName: 'MyTable',
    },
    DeletionPolicy: "Delete",
    UpdateReplacePolicy: "Delete",
  });
});
```
</details>

**Comment by MrArnoldPalmer** [comment]
Since this seems to be working as expected, I'm gonna close but reopen if I'm missing something. Thanks @tlindsay42
