### ISSUE TITLE
(core): Allow changing default `removal_policy` behaviour globally

### ISSUE THREAD

**Issue by acm19** [aws/aws-cdk#21303]
### Describe the feature

Having the possibility to adjust the value of `removal_policy` globally for all resources that support it.

### Use Case

The default behaviour of the CDK differs from CloudFormation. Making it harder to reason about when using both. When a similar behaviour to CloudFormation's default is required (or just a change of the default behaviour in general) you need to remember to add `removal_policy` to all the relevant resources. Consistency is hard to obtain as one might forget to add it to a single resource. Changing the behaviour globally would be great for those wanting to have it closer to CloudFormation. Ideally it should be possible to apply it to the bootstrap stack as well.

### Other Information

Example documentation for  OpenSearch Doman (I'd like to change it to `DESTROY` consistently for all my resources):

> :param removal_policy: Policy to apply when the domain is removed from the stack. Default: RemovalPolicy.RETAIN

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

Python (aws-cdk-lib==2.32.1)

### Environment details (OS name and version, etc.)

Ubuntu 20.04.4 LTS

**Comment by rix0rrr** [comment]
You can write an Aspect to apply a global removal policy. The default in CDK is RETAIN for stateful resources because that is a safe default.

**Comment by acm19** [comment]
@rix0rrr safety is relative, innit? From the cost perspective `RETAIN` is the least safe default. It's also counter intuitive to remove a stack and by default leave orphan resources. Not to mention it's different to the default of the actual tool CFN and the underlying API. I still think support for this behaviour change should be first class citizen of the CDK.

When it comes to the Aspect workaround, do you have an example of it that you can share?

**Comment by praneetloke** [comment]
I think having a default `RETAIN` for resources is confusing. Deleted stacks silently leave resources that are hard to track down and delete. I understand the reasoning behind leaving it intact but it should have been opt-in, in my opinion. I think it takes away one of the benefits of using automation to provision resources. But rather than changing the default which will catch users by surprise, having a configurable global default for the removal policy would be great. I think it's also the simplest option for CDK users.

**Comment by bigbohne** [comment]
+1 for this issue. This would solve the problem for us to check in every construct if it is part of a "ephemeral" stack and setting the `removal_policy` accordingly
