### ISSUE TITLE
CDK CLI: No documentation for SSO credential support

### ISSUE THREAD

**Issue by HenrikStanley** [aws/aws-cdk#21314]
### Describe the issue

Since AWS SSO credential support has been merged in issue https://github.com/aws/aws-cdk/pull/19454
There is no documentation in any of the docs explaining how this should work.

We have multiple different options with no explanation on what takes precedence, how it should be debugged etc.

For example do you use `$AWS_PROFILE`, `$CDK_DEFAULT_PROFILE` or the `--profile` feature flag? Which takes precedence over the other?

This should be clearly documented and kept up to date as this is something that is really difficult to search for due to the long history of lacking SSO support + the various workaround solutions dominating any type of search result.

### Links

CDK v2 getting started guide explicitly states that SSO is not supported:
https://docs.aws.amazon.com/cdk/v2/guide/getting_started.html
`AWS CDK does not natively support Single Sign-On (SSO). To use SSO with the CDK, use a tool such as yawsso.`

Other getting started guides such as
https://aws.amazon.com/getting-started/guides/setup-environment/module-three/

And the Workshop:
https://cdkworkshop.com/15-prerequisites/200-account.html

**Comment by TheRealAmazonKendra** [comment]
Thanks for the feedback on this. We will include these documentation updates with https://github.com/aws/aws-cdk/pull/31702
