### ISSUE TITLE
(lambda): timeout property should always be available

### ISSUE THREAD

**Issue by sekhavati** [aws/aws-cdk#21312]
### Describe the bug

The TypeScript definitions for the `timeout` property of Lambda Functions (see [here](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda.Function.html#timeout-1)) state its **_optional_**.  

This would appear incorrect. When a user doesn't explicitly set a timeout at initialisation then it will be configured with the default timeout of 3 seconds, see [here](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda.Function.html#timeout). So it would seem `timeout` is always set to something.

### Expected Behavior

[`timeout` property](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda.Function.html#timeout-1) should **_not_** be optional. Rather it should return the default value of 3 seconds or whatever was set by the user at initialisation.

### Current Behavior

[`timeout` property](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda.Function.html#timeout-1) is optional

### Reproduction Steps

```
import * as lambda from "aws-cdk-lib/aws-lambda";

const example = new lambda.Function(this, "example", {
  handler: "index.handler",
  runtime: lambda.Runtime.NODEJS_16_X,
  code: lambda.Code.fromAsset("../build"),
})
    
example.timeout // => Duration | undefined
```

### CDK CLI Version

2.33.0 (build 859272d)

### Node.js Version

16

### OS

MacOS

### Language

Typescript

**Comment by kaizencc** [comment]
See: https://github.com/aws/aws-cdk/pull/17594 which links to https://github.com/aws/aws-cdk/pull/17000#discussion_r739116360. We've discussed this, leaving this as is simply because others before me have already made that decision.
