### ISSUE TITLE
(cli): add CLI flag to disable ECR image scanning in bootstrap template

### ISSUE THREAD

**Issue by corymhall** [aws/aws-cdk#21317]
### Describe the feature

In the v2 bootstrap template ECR image scanning is turned on by default. There should be an option to disable this.

https://github.com/aws/aws-cdk/blob/82bd3f54aa84db3e0cd5b34c0d0a642322946f29/packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml#L206-L207

### Use Case

Image scanning is a nice to have feature that is not required for CDK to operate, and it is not always available across all regions. Allowing the ability to turn this off would allow teams to still use the default bootstrap template in those regions.

### Proposed Solution

Maybe add a cli flag `--ecr-image-scanning`/`--no-ecr-image-scanning`

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

v2

### Environment details (OS name and version, etc.)

All

**Comment by rix0rrr** [comment]
We should probably make this a CFN `Condition` and 100% stop accepting "please change the default that my organization requires" type of changes to the bootstrap template

**Comment by corymhall** [comment]
closed in https://github.com/aws/aws-cdk/pull/21342
