### ISSUE TITLE
(BootstraplessSynthesizer): no way to add s3 assets bucket to BootstraplessSynthesizer

### ISSUE THREAD

**Issue by justin-masse** [aws/aws-cdk#21315]
### Describe the bug

Currently it looks like BootstraplessSynthesizer extends from DefaultStackSynthesizer but the constructor props do not. 

When synthing large templates that grow beyond ~50kb with Bootstrapless they are uploaded to an s3 bucket. This causes `cdk deploy` to fail if your CFN execution role does not have adequate permissions to the s3 bucket these assets are uploaded to. 

With **DefaultStackSynthesizer** it's possible to define an s3 bucket where the synth assets are uploaded 
 with: `fileAssetsBucketName: 'my-s3-bucket-name,` but this is not possible with BootstraplessSynthesizer and the only option is to use the `cdk-<qualifier>-assets-<acocunt>-<region>` which could potentially change due to an aws-cdk-lib update in the future causing your IAM CFN execution role to fall out of sync with the bucket names when using least privilege.

### Expected Behavior

Allow defining of s3 bucket so that I may build this into my my execution role to prevent future failures.

### Current Behavior

cdk deploy returns error:

`Call failed: createChangeSet({"StackName":"myStackName","ChangeSetName":"cdk-deploy-change-set","ChangeSetType":"UPDATE","Description":"CDK Changeset for execution some guid here","TemplateURL":"https://cdk-hnb659fds-assets-<account>-us-east-1.s3.us-east-1.amazonaws.com/cdk/common-myStackName/<asset hash>.yml","Parameters":[],"RoleARN":"arn:aws:iam::<account>:role/my-cfn-execution-role","Capabilities":["CAPABILITY_IAM","CAPABILITY_NAMED_IAM","CAPABILITY_AUTO_EXPAND"]}) => S3 error: Access Denied`

### Reproduction Steps

1. Have a large template (~50kb or bigger once synthed)
2. Use BootstraplessSynthesizer
3. Don't include s3 permissions on your deployRole (because you don't need to except in this edge case)
4. Run cdk deploy
5. Creating the CFN changeset fails because it's attempting to publish the synthed template asset to default s3 bucket

### Possible Solution

Allow defining the s3 bucket for the BootstraplessSynthesizer class props just like it's parent class.

### CDK CLI Version

2.22.0 (build 1db4b16)

### Node.js Version

14

### OS

macos

### Language

Typescript

**Comment by peterwoodworth** [comment]
The bootstrapless synthesizer isn't intended to be used with assets, being able to add an assets bucket isn't within the design of this synthesizer. Consider using `CliCredentialsStackSynthesizer` or `DefaultStackSynthesizer` instead depending on your use case 🙂
