### ISSUE TITLE
(aws_ec2): (add batch to InterfaceVpcEndpointAwsService)

### ISSUE THREAD

**Issue by shimi7o** [aws/aws-cdk#21338]
### Describe the feature

My request is to add batch to InterfaceVpcEndpointAwsService.

```typescript
    declare const vpc: ec2.Vpc;

    new ec2.InterfaceVpcEndpoint(
      this,
      'VpcEndpoint',
      {
        vpc: vpc,
        service: ec2.InterfaceVpcEndpointAwsService.Batch,  // Currently, I can't
      }
    );
```

### Use Case

Currently, I must be written as below.

```typescript
    declare const vpc: ec2.Vpc;

    new ec2.InterfaceVpcEndpoint(
      this,
      'VpcEndpoint',
      {
        vpc: vpc,
        service: new ec2.InterfaceVpcEndpointService(
          `com.amazonaws.${region}.batch` // not good
        )
      }
    );
```

### Proposed Solution

My idea is to add one line in aws-cdk/packages/@aws-cdk/aws-ec2/lib/vpc-endpoint.ts

```typescript
export class InterfaceVpcEndpointAwsService implements IInterfaceVpcEndpointService {
  public static readonly BATCH = new InterfaceVpcEndpointAwsService('batch');  
```

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.33.0

### Environment details (OS name and version, etc.)

Debian10.12

**Comment by corymhall** [comment]
This issue has been classified as *p2*. That means a workaround is available or it is deemed a nice-to-have feature. Given the amount of work there is to do and the relative priority of this issue, the CDK team is unlikely to address it. That does not mean the issue will never be fixed! If someone from the community submits a PR to fix this issue, and the PR is small and straightforward enough, and meets the quality bars to be reviewed and merged with little effort we will accept that PR. PRs that do not build or need complex or multiple rounds of reviews are unlikely to be merged and will be closed to keep our backlog manageable. 

In the mean time, remember that you can always use the escape hatch (https://docs.aws.amazon.com/cdk/v2/guide/cfn_layer.html) mechanism to have fine control over the CloudFormation output you want. We will keep the issue open for discoverability, to collect upvotes, and to facilitate discussion around this topic.

We use +1s *on this issue* to help prioritize our work, and are happy to re-evaluate the prioritization of this issue based on community feedback. You can reach out to the cdk.dev community on Slack (https://cdk.dev/) to solicit support for reprioritization.

**Comment by TheRealAmazonKendra** [comment]
This has now been completed.
