### ISSUE TITLE
aws-cdk-lib: Changing logical ID(human readable part) of AppSync resolver result in error upon deploy (CDK)

### ISSUE THREAD

**Issue by RadoslavMarinov** [aws/aws-cdk#21350]
### Describe the bug

When I change the `id` of AppSync Resolver and deploy (`cdk deploy`) I receive an error 

_**Only one resolver is allowed per field. (Service: AWSAppSync; Status Code: 400; Error Code: BadRequestException; Request ID: fd68b0ff-38a5-4149-a797-138baf6a836c; Proxy: null**_

### Expected Behavior

I would expect the resolver with the new ID to be attached to the GraphQL field(operation)

### Current Behavior

The deploy fails with error:

> Only one resolver is allowed per field. (Service: AWSAppSync; Status Code: 400; Error Code: BadRequestException; Request ID: fd68b0ff-38a5-4149-a797-138baf6a836c; Proxy: null

### Reproduction Steps

Create a new resolver

` new appsync.Resolver(this.scope, "SuperResolver", {...})`

then change just the `id` of the resolver from "SuperResolver" to "GreatResolver":

` new appsync.Resolver(this.scope, "GreatResolver", {...})`

and deploy.
You should get the same/similar error: **_Only one resolver is allowed per field_**

### Additional Information/Context

Appsync library: "@aws-cdk/aws-appsync-alpha": "^2.29.1-alpha.0"
CDK library: "aws-cdk-lib": "2.29.1",

### CDK CLI Version

2.29.1

### Node.js Version

16

### OS

Linux Ubunty 

### Language

Typescript

**Comment by peterwoodworth** [comment]
Thanks for reporting this @RadoslavMarinov, 

Right now the only workaround is to remove the resolver resources, deploy that to the stack, then add them back and redeploy. We're aware of this issue and tracking it [here](https://github.com/aws/aws-cdk/issues/13269), please bring your concerns to that thread 🙂
