### ISSUE TITLE
(lambda): native module throws error when lambda initialises

### ISSUE THREAD

**Issue by brinsleylogic** [aws/aws-cdk#21352]
### Describe the bug

After deploying my lambda, I try to execute it and get an error prior to the function executing.

```
2022-07-28T09:10:32.862Z	undefined	ERROR	Uncaught Exception 	
{
    "errorType": "Error",
    "errorMessage": "/var/task/node_modules/bignum/build/Release/bignum.node: invalid ELF header",
    "code": "ERR_DLOPEN_FAILED",
    "stack": [
        "Error: /var/task/node_modules/bignum/build/Release/bignum.node: invalid ELF header",
        "    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1189:18)",
        "    at Module.load (node:internal/modules/cjs/loader:981:32)",
        "    at Function.Module._load (node:internal/modules/cjs/loader:822:12)",
        "    at Module.require (node:internal/modules/cjs/loader:1005:19)",
        "    at require (node:internal/modules/cjs/helpers:102:18)",
        "    at bindings (/var/task/node_modules/bindings/bindings.js:112:48)",
        "    at Object.<anonymous> (/var/task/node_modules/bignum/index.js:1:30)",
        "    at Module._compile (node:internal/modules/cjs/loader:1105:14)",
        "    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)",
        "    at Module.load (node:internal/modules/cjs/loader:981:32)"
    ]
}
```

### Expected Behavior

Lambda executes as expected.

### Current Behavior

Lambda throws an error prior to execution.

### Reproduction Steps

`npm i node-djiparsetxt`

In my function definition I've got:

```ts
        bundle: {
            nodeModules: [ "node-djiparsetxt" ]
        },
```

### Additional Information/Context

In the dependency tree for my lambda there's a dependency on the `bignum` module, which requires node-gyp to build. I've got  the parent dependency named in the `bundle.nodeModules` property for my lambda function so as far as I can tell the lambda environment should be handling the install of that module and its dependencies.

This works on my local machine (Windows) as I've obviously got the dependencies already built from the local install. It's just when it's running in AWS that I get the above error.

### CDK CLI Version

2.24.0

### Node.js Version

14, 16

### OS

Amazon Linux

### Language

Typescript

### Language Version

4.7.4

**Comment by brinsleylogic** [comment]
Is anyone looking in to this?

**Comment by kaizencc** [comment]
Hi @brinsleylogic! I unfortunately can't do much to help you with the lambda runtime code. Do you have a question regarding your CDK code and if so, would you mind sharing your relevant CDK code?

**Comment by brinsleylogic** [comment]
I totally forgot I raised this. Can't remember how I resolved this in the end but I'm pretty sure it ended up being a runtime thing.

Had initially raised it here as it seemed like it was dying prior to actually hitting any code inside the lambda so was thinking it could be something in tue Lambda env. causing issues.
