### ISSUE TITLE
(aws-appmesh): App Mesh Routes with a weight of 0 are being auto-assigned a weight of 1

### ISSUE THREAD

**Issue by srinivas-kini** [aws/aws-cdk#21365]
### Describe the bug

I am creating an App Mesh route spec. where one virtual node (VN) has a weight of 100 (or 1 in relative terms), and the other virtual node has a weight of 0. 

However, once the CDK deployment is done, the route with the weight 0 is being changed to 1 automatically. This is regardless of the relative weight of the other route. 

For example, VN1 has a weight of 1 and VN2 has a weight of 0, it becomes 1 for both. Which means the traffic is split 50/50.
If VN1 has a weight of 100 and VN2 has a weight of 0, it becomes 100,1. In the case the traffic is split 99/1.

<img width="1361" alt="image" src="https://user-images.githubusercontent.com/68226496/181620393-097e8d95-abc3-4115-891e-fff5923181c7.png">

<img width="883" alt="image" src="https://user-images.githubusercontent.com/68226496/181620472-c6a24cae-8086-4ec3-b4f4-86df7cb07b27.png">

The weight has to be manually changed to 0  in the AWS Console UI.

### Expected Behavior

Routes with targets of weight 0 should not change to 1 automatically.

### Current Behavior

Routes with targets of weight 0 are being changed to 1 automatically.

### Reproduction Steps

Provision a mesh that has 2 virtual nodes. Add the virtual nodes to a virtual router as targets, and assign one node a weight of 0.

```c
this.virtualRouter = new appmesh.VirtualRouter(this, `${this.stackName}VritualRouter`, {
      mesh: this.mesh,
      virtualRouterName: "ColorTellerVirtualRouter",
      listeners: [appmesh.VirtualRouterListener.http(80)],
    });

    this.route = new appmesh.Route(this, `${this.stackName}BackendRoute`, {
      mesh: this.mesh,
      virtualRouter: this.virtualRouter,
      routeName: "ColorTellerRoute",
      routeSpec: appmesh.RouteSpec.http({
        weightedTargets: [
          {
            virtualNode: this.virtualNodeWhite,
            weight: 100,
          },
          {
            virtualNode: this.virtualNodeGreen,
            weight: 0,
          },
        ],
      }),
    });
```

### CDK CLI Version

2.27.0 (build 8e89048)

### Node.js Version

v18.3.0

### OS

macOS Monterey (12.4)

### Language

Typescript

### Language Version

3.9.7

**Comment by srinivas-kini** [comment]
To add some context, The weights are being calculated dynamically based on `cdk --context`.

```c
let meshUpdateChoice = this.node.tryGetContext("mesh-update");
...


const greenVnWeight: number = meshUpdateChoice ? 50 : 0;
const whiteVnWeight: number = greenVnWeight == 0 ? 100 : 50;
```

I have added the weights directly in the 'Reproduction Steps' sections for ease of use. [Link to entire code](https://github.com/srinivas-kini/aws-app-mesh-examples/blob/cdk-howto-file-based-tls/walkthroughs/cdk-examples/howto-tls-file-provided/lib/stacks/mesh-components.ts#L34)

**Comment by peterwoodworth** [comment]
Looks like you're right. [CloudFormation docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-appmesh-route-weightedtarget.html) state that you can pass in a value of 0

However this is how we render the weight https://github.com/aws/aws-cdk/blob/83f166817cf85064b118a7a672ca2d96641d3bbb/packages/%40aws-cdk/aws-appmesh/lib/route-spec.ts#L591

This will result in 1 when 0 is passed because 0 is a falsy value.

We accept contributions! This should be a pretty simple fix 🙂 Let me know if you'd like to [contribute](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md)

**Comment by Xcalizorz** [comment]
@peterwoodworth can I take this up? I would add a PR tomorrow.

**Comment by peterwoodworth** [comment]
@Xcalizorz of course! all you 🙂
