### ISSUE TITLE
aws-cdk-lib/aws-msk: unable to update tags in MSK cluster

### ISSUE THREAD

**Issue by yongzhang8** [aws/aws-cdk#21367]
### Describe the bug

Getting following error when updating tag in MSK cluster:

KafkaStack: creating CloudFormation changeset...
4:55:16 PM | UPDATE_FAILED        | AWS::MSK::Cluster  | kafkaCluster
Internal Failure

 ❌  KafkaStack failed: Error: The stack named KafkaStack failed to deploy: UPDATE_ROLLBACK_COMPLETE: Internal Failure
    at prepareAndExecuteChangeSet (/opt/homebrew/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:386:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at CdkToolkit.deploy (/opt/homebrew/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:210:24)
    at initCommandLine (/opt/homebrew/lib/node_modules/aws-cdk/lib/cli.ts:347:12)

The stack named KafkaStack failed to deploy: UPDATE_ROLLBACK_COMPLETE: Internal Failure

### Expected Behavior

When create MSK cluster, I set tag appVersion to 1.0, I should be able to change tag to 2.0 in CDK

### Current Behavior

Getting error: KafkaStack failed: Error: The stack named KafkaStack failed to deploy: UPDATE_ROLLBACK_COMPLETE: Internal Failure

### Reproduction Steps

if you change 1.0 to 2.0 at line: Tags.of(kafkaStack).add('appVersion', '1.0');
You will get error when do cdk deploy --all

Code:

msk.ts:
#!/usr/bin/env node
import 'source-map-support/register';
import * as cdk from 'aws-cdk-lib';
import { MskStack } from '../lib/msk-stack';
import {VpcStack} from "../lib/vpc-stack";
import { Tags } from 'aws-cdk-lib';

const app = new cdk.App();

let vpcStack = new VpcStack(app, 'VpcStack');

let kafkaStack = new MskStack(vpcStack, app, 'KafkaStack');
Tags.of(kafkaStack).add('appVersion', '1.0');
kafkaStack.addDependency(vpcStack);

lib/msk-stack.ts:
import * as cdk from 'aws-cdk-lib';
import * as msk from 'aws-cdk-lib/aws-msk';
import * as ec2 from 'aws-cdk-lib/aws-ec2'
import { Construct } from 'constructs';

import {VpcStack} from "./vpc-stack";
import { RemovalPolicy } from 'aws-cdk-lib';

export class MskStack extends cdk.Stack {
    public kafkaCluster: msk.CfnCluster;

    constructor(vpcStack: VpcStack, scope: Construct, id: string, props?: cdk.StackProps) {
        super(scope, id, props);
        this.kafkaCluster = new msk.CfnCluster(this, "kafkaCluster", {
            brokerNodeGroupInfo: {
                securityGroups: [vpcStack.kafkaSecurityGroup.securityGroupId],
                clientSubnets: [...vpcStack.vpc.selectSubnets({
                    subnetType: ec2.SubnetType.PUBLIC
                }).subnetIds],
                instanceType: "kafka.t3.small",
                storageInfo: {
                    ebsStorageInfo: {
                        volumeSize: 5
                    }
                }
            },
            clusterName: "TransactionsKafkaCluster",
            kafkaVersion: "2.8.0",
            numberOfBrokerNodes: 2
        });
    }
}

lib/vpc-stack.ts:
import * as cdk from "aws-cdk-lib";
import * as ec2 from "aws-cdk-lib/aws-ec2";
import { Construct } from 'constructs';

export class VpcStack extends cdk.Stack {
    public vpc: ec2.Vpc;
    public kafkaSecurityGroup: ec2.SecurityGroup;

    constructor(scope: Construct, id: string, props?: cdk.StackProps) {
        super(scope, id, props);

        this.vpc = new ec2.Vpc(this, 'vpc');

        this.kafkaSecurityGroup = new ec2.SecurityGroup(this, 'kafkaSecurityGroup', {
            securityGroupName: 'kafkaSecurityGroup',
            vpc: this.vpc,
            allowAllOutbound: true
        });
    }
}

### CDK CLI Version

2.33.0

### Node.js Version

v18.3.0

### OS

macOS 11.6.7

### Language

Typescript

### Language Version

4.7.4

**Comment by peterwoodworth** [comment]
I can reproduce this, thanks for reporting!

This is an issue with CloudFormation, I'll submit a ticket to them to see what they say

**Comment by peterwoodworth** [comment]
There's a feature request up internally for this. I don't have an ETA, but it's been supposedly coming soon for a little bit now so hopefully i'll have good news to share soon

**Comment by peterwoodworth** [comment]
Closing this as it is being tracked internally and there's no action items for us

**Comment by jaredtbates** [comment]
Hi @peterwoodworth, has there been any update on this? We are encountering this in our environment when adding tags to the MSK cluster:
`Cluster (ClusterXXXXX) Requested update requires the creation of a new physical resource; hence creating one.`
Not sure why adding tags would require a new cluster.

**Comment by peterwoodworth** [comment]
@jaredtbates unfortunately not, the date has kept getting pushed back with little communication from the service team, so I don't have any updates I feel confident sharing in public
