### ISSUE TITLE
(cfnspec): descriptions for CfnResource properties differ from descriptions found in CloudFormation docs

### ISSUE THREAD

**Issue by kiwibel** [aws/aws-cdk#21368]
## New report

The descriptions for the properties of CloudFormation resources differ from what is found in CloudFormation docs, which is leading to some unclear documentation. 

Example, in the [CDK docs](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-sso.CfnPermissionSet.html#managedpolicies) for `SSO.CfnPermissionSet.managedPolicies`, the description reads:
> A structure that stores the details of the IAM managed policy.

While the [CloudFormation docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sso-permissionset.html#cfn-sso-permissionset-managedpolicies) reads:
> A structure that stores the details of the AWS managed policy.

This is leading to unclear or incomplete information which leads to incorrect use, as seen below in the original report.

### Describe the bug

- I am trying to create an SSO permission set with a managed policy attached.
- Using `sso.CfnPermissionSet` construct and passing a manage policy arn.
- This leads to a validation error for the policy arn.

The regex in the error message doesn't include account id and the slash character is not escaped.

```
this.ssoPermissionSet = new sso.CfnPermissionSet(
  this,
  'TestCfnPermissionSet',
  {
    instanceArn: 'arn:aws:sso:::instance/XXX
    name: 'TestPermissionSetCdk',
    description: 'test sso permission set',
    managedPolicies: ['arn:aws:iam::XXXXXXXXXXXX:policy/test-sso-cdk-policy',
    ],
    sessionDuration: 'PT1H',
  }
)
```

```
>cdk deploy --require-approval never
16:14:27 | CREATE_FAILED        | AWS::SSO::PermissionSet | TestCfnPermissionSet
Resource handler returned message:
"1 validation error detected: Value 'arn:aws:iam::XXXXXXXXXXXX:policy/test-sso-cdk-policy'
at 'managedPolicyArn' failed to satisfy constraint: Member must satisfy regular expression pattern:
arn:(aws|aws-us-gov|aws-cn|aws-iso|aws-iso-b):iam::aws:policy/[\p{L}\p{M}\p{Z}\p{S}\p{N}\p{P}]+
(Service: SsoAdmin, Status Code: 400, Request ID:XX)" (RequestToken: , HandlerErrorCode: InvalidRequest)
```

### Expected Behavior

SSO Permission set with managed policy created when running `cdk deploy`.

### Current Behavior

Validation error for managed policy arn.

### Reproduction Steps
```
ssoPermissionSet = new sso.CfnPermissionSet(
  this,
  'TestCfnPermissionSet',
  {
    instanceArn: 'arn:aws:sso:::instance/XXX
    name: 'TestPermissionSetCdk',
    description: 'test sso permission set',
    managedPolicies: ['arn:aws:iam::XXXXXXXXXXXX:policy/test-sso-cdk-policy',
    ],
    sessionDuration: 'PT1H',
  }
)
```
### Possible Solution

Use inline policy in permission set.

### Additional Information/Context

The issue is consistent with `sso-admin` api behaviour which is probably the root cause 🙁

```
>aws sso-admin create-permission-set --name TestPermissionSetCdk
--description "test sso permission set"
--instance-arn "arn:aws:sso:::instance/XXX"
--session-duration: "PT1H"

An error occurred (ValidationException) when calling the AttachManagedPolicyToPermissionSet operation:
1 validation error detected: Value 'arn:aws:iam::XXXXXXXXXXXX:policy/test-sso-cdk-policy'
at 'managedPolicyArn' failed to satisfy constraint:
Member must satisfy regular expression pattern:
arn:(aws|aws-us-gov|aws-cn|aws-iso|aws-iso-b):iam::aws:policy/[\p{L}\p{M}\p{Z}\p{S}\p{N}\p{P}]+
```

### CDK CLI Version

2.33.0 (build 859272d)

### Node.js Version

14.19.1

### OS

macOS Monterey v 12.3.1 (Apple M1)

### Language

Typescript

### Language Version

3.9.10

**Comment by peterwoodworth** [comment]
I think this is happening because the fields are expecting an AWS managed policy, whereas you're passing in a customer managed policy. CloudFormation docs specifically say 

> A structure that stores the details of the AWS managed policy.

There is a [separate API call](https://docs.aws.amazon.com/singlesignon/latest/APIReference/API_AttachCustomerManagedPolicyReferenceToPermissionSet.html) for attaching customer managed policies to permission sets. It doesn't seem that Cfn or CLI are making use of this however.

Since you're using an L1 construct, we can't take any action on this. I would recommend submitting an issue to the [Cfn Coverage Roadmap](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues), and the CLI repo.

**Comment by kiwibel** [comment]
Thanks for looking into it @peterwoodworth

It is not clear from the cdk docs which `managed` policy is expected -- can [this](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-sso.CfnPermissionSet.html#managedpolicies) be updated?
In addition, I'm going to open an issue for Cfn/CLI as you suggested.

Thanks again!

**Comment by peterwoodworth** [comment]
These docs are autogenerated based off the descriptions found in CloudFormation. I'm not sure why this would differ between here and the CloudFormation docs... It's possible that we might not keep up to date with the latest docs changes? Most of the descriptions seem to differ slightly. Thanks for bringing this up, I hope you don't mind if i repurpose this issue to track that

**Comment by mrgrain** [comment]
We had an issue with syncing the CloudFormation docs to our repo. This is resolved now.
