### ISSUE TITLE
ecs: register_load_balancer_targets missing wrapped parameters for ecstarget type

### ISSUE THREAD

**Issue by jdix531** [aws/aws-cdk#21383]
### Describe the issue

Hi,

This link: https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_ecs/Ec2Service.html#aws_cdk.aws_ecs.Ec2Service.register_load_balancer_targets
(and this one: https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_ecs/EcsTarget.html#aws_cdk.aws_ecs.EcsTarget)

Shows
```python
# cluster: ecs.Cluster
# task_definition: ecs.TaskDefinition
# vpc: ec2.Vpc

service = ecs.FargateService(self, "Service", cluster=cluster, task_definition=task_definition)

lb = elbv2.ApplicationLoadBalancer(self, "LB", vpc=vpc, internet_facing=True)
listener = lb.add_listener("Listener", port=80)
service.register_load_balancer_targets(
    container_name="web",
    container_port=80,
    new_target_group_id="ECS",
    listener=ecs.ListenerConfig.application_listener(listener,
        protocol=elbv2.ApplicationProtocol.HTTPS
    )
)
```

But it should be

```python
# cluster: ecs.Cluster
# task_definition: ecs.TaskDefinition
# vpc: ec2.Vpc

service = ecs.FargateService(self, "Service", cluster=cluster, task_definition=task_definition)

lb = elbv2.ApplicationLoadBalancer(self, "LB", vpc=vpc, internet_facing=True)
listener = lb.add_listener("Listener", port=80)
service.register_load_balancer_targets(
    ecs.EcsTarget(
        container_name="web",
        container_port=80,
        new_target_group_id="ECS",
        listener=ecs.ListenerConfig.application_listener(listener,
            protocol=elbv2.ApplicationProtocol.HTTPS
        )
    )
)
```

Pretty sure, at least that's how I got it working! The code hints also have this issue though I assume they're related.

### Links

https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_ecs/Ec2Service.html#aws_cdk.aws_ecs.Ec2Service.register_load_balancer_targets

https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_ecs/EcsTarget.html#aws_cdk.aws_ecs.EcsTarget

**Comment by peterwoodworth** [comment]
Thanks for the report, this is something we're aware of that get mistranslated from TypeScript to Python (as our docs are all autogenerated and translated from TypeScript), so we are tracking this in the JSII repo to ensure that structs get explicitly declared in Python

**Comment by tgeo-cambrian** [comment]
@peterwoodworth  since this is going on for like 3 months now, you could at least add a manual warning/link/something in the documentation page. I wasted time troubleshooting and investigating to arrive at the same solution as @jdix531 and then found this thread.

Thank you.

**Comment by eth-limo** [comment]
I just ran into this as well. Documentation is still incorrect.

Using the CDK has probably been one of the worst user experiences so far.

**Comment by mat-savage** [comment]
This documentation is still incorrect, @peterwoodworth.
