### ISSUE TITLE
(cli): (2.34.0 parses AWS account ID as a number)

### ISSUE THREAD

**Issue by ilazakis** [aws/aws-cdk#21381]
### Describe the bug

[This change](https://github.com/aws/aws-cdk/commit/ec2d68a933342bd1ce0601ab25e677806e1ec4bd) in `2.34.0` forces parsing AWS account ids as numbers.

This breaks code like the following:

```go
func LoadContextValue(scope constructs.Construct, key string) (value string) {
	value = fmt.Sprintf("%s", scope.Node().TryGetContext(jsii.String(key)))
	log.Printf("%s", value)
	if value == "" {
		log.Fatalf("FATAL ERROR: missing '%s' context argument", key)
	}
	return
}
```

If I run a CDK command e.g. `cdk diff -v --context accountID=111111111111` the log output is `%!s(float64=1.11111111111e+11)`.

### Expected Behavior

If I run a CDK command e.g. `cdk diff -v --context accountID=111111111111`, I expect the log output to be `111111111111`.

### Current Behavior

In `2.33.0`, if I run a CDK command e.g. `cdk diff -v --context accountID=111111111111`, the log output is `111111111111` and I can diff/deploy/destroy stacks successfully.

### Reproduction Steps

Run any CDK command that expects a number to be parsed as a string.

In my case, I run `cdk diff -v --context accountID=111111111111`, but the same issue exists for any CDK command e.g. `deploy`, `destroy` etc.

### Possible Solution

I suspect [this change in 2.34.0](https://github.com/aws/aws-cdk/commit/ec2d68a933342bd1ce0601ab25e677806e1ec4bd) causes the issue.

### CDK CLI Version

2.34.0

### Node.js Version

v16.13.1

### OS

macOS 12.4

### Language

Go

### Language Version

Go 1.18

**Comment by efwahl** [comment]
This seems to be a general issue that TryGetContext in 2.34 is running the result through a json parser so that rather than returning strings as it did with previous versions, it will return objects (int, dict, etc) if the result is parsable as json. Is that an intentional change with 2.34, or something that will be reverted? If that's a permanent change, we're going to need to update code in quite a few places to be compatible.

**Comment by akuma12** [comment]
I just ran into this consequence myself. Typecasting the `try_get_context` call as a string fixed it for now, but I think this had more consequences than intended. A quick fix would be to typecast the `account` parameter in the `Environment` class to a string.

**Comment by ilazakis** [comment]
@akuma12 That’s indeed a valid workaround.

In our case the workaround was using a Generic version of the affected function that wraps `TryGetContext`; that allows the caller to define what type they expect to get. But it also forces the all call sites to change.

Beyond workarounds, the more important issue here is that this is effectively a breaking change; the same command and cdk code that were succeeding up until 2.34.0, are now failing.

**Comment by iliapolo** [comment]
Should be fixed in https://github.com/aws/aws-cdk/releases/tag/v2.34.2
