### ISSUE TITLE
(aws-cdk-lib/ aws_cloudfront): (Replacing my instance with new instance when migrated to V2 )

### ISSUE THREAD

**Issue by Shankureddy** [aws/aws-cdk#21397]
### Describe the bug

I have updated my cdk V1 app which creates a cloudfront to cdk V2 by following the migration guide. also updated my code according to V2 modules and updated the cdk.json for feature flags as mentioned in migration guide, but when I do cdk diff on my stack it's replacing my old cloudfront with new one by deleting.

### Expected Behavior

Changes to logical IDs (causing replacement of resources) are not expected.)
Changes to the CDKMetadata resource
Updated asset hashes
Changes related to the new-style stack synthesis, if your app used the legacy stack synthesizer in v1 (CDK v2 does not support the legacy stack synthesizer)
The addition of a CheckBootstrapVersion rule

### Current Behavior

Resources
**[-] AWS::CloudFront::Distribution tstitinerarytstitineraryumappedcomfrontCFDistributionAC176D4B destroy**
[+] AWS::CloudFront::CachePolicy tst-itinerary-myCachePolicy tstitinerarymyCachePolicy4FB23746 
[+] AWS::CloudFront::CachePolicy tst-itinerary-myCachePolicy2 tstitinerarymyCachePolicy28095353D 
[+] AWS::CloudFront::CloudFrontOriginAccessIdentity tst-itinerary-tst-itinerary.umapped.com-front/Origin1/S3Origin tstitinerarytstitineraryumappedcomfrontOrigin1S3Origin93C4885D 
[+] AWS::CloudFront::CloudFrontOriginAccessIdentity tst-itinerary-tst-itinerary.umapped.com-front/Origin2/S3Origin tstitinerarytstitineraryumappedcomfrontOrigin2S3Origin91774ABB 

**[+] AWS::CloudFront::Distribution tst-itinerary-tst-itinerary.umapped.com-front tstitinerarytstitineraryumappedcomfront153C86FD** 

[~] AWS::S3::BucketPolicy tst-itinerary/Policy tstitineraryPolicy5FE33CC2 

### Reproduction Steps

 code in V1

`const webFront = new cfnt.CloudFrontWebDistribution(this, `${id}-${fullDomain}-front`, {
        defaultRootObject: 'index.html',
        aliasConfiguration: {
          names: [fullDomain],
          acmCertRef: cert.certificateArn,
        },

        comment: `${fullDomain} distribution for stack: ${id}`,
        originConfigs: [{
          s3OriginSource: {
            s3BucketSource: itineraryBucket,
            originAccessIdentity: identity
          },
          behaviors: [

            {
              allowedMethods: cfnt.CloudFrontAllowedMethods.GET_HEAD,
              cachedMethods: cfnt.CloudFrontAllowedCachedMethods.GET_HEAD,
              pathPattern: '/v2/*',
              compress: true,
              defaultTtl: cdk.Duration.hours(1)
            }
          ],
        },
        {
          s3OriginSource: {
            s3BucketSource: polymerBucket,
            originAccessIdentity: identity

          },
          behaviors: [
            {
              isDefaultBehavior: true,
              compress: false,
              defaultTtl: cdk.Duration.hours(1), //10min by default but TODO: move this to config
            }   
          ]
          },
       
        ],
        errorConfigurations: [
          {
            errorCode: 403,
             responseCode: 200,
             errorCachingMinTtl:10,
            responsePagePath: '/v2/index.html'
           },
           {
             errorCode: 404,
             errorCachingMinTtl:10,
            responseCode: 200,
            responsePagePath: '/v2/index.html'
        }
         ],

        httpVersion: cfnt.HttpVersion.HTTP2,
        viewerProtocolPolicy: cfnt.ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
        

        loggingConfig: {
          bucket: logBucket,
          prefix: `${fullDomain}`
        },
      });`

### Additional Information/Context

modified code in V2

` const myCachePolicy = new cfnt.CachePolicy(this, `${id}-myCachePolicy`, {
        cachePolicyName: `${id}-cache-policy`,
        comment: 'A default policy',
        defaultTtl: Duration.hours(1),
        minTtl: Duration.minutes(1),
        maxTtl: Duration.hours(1),
        cookieBehavior: cfnt.CacheCookieBehavior.all(),
        
        enableAcceptEncodingGzip: true,
        enableAcceptEncodingBrotli: true,
      });

      const myCachePolicy2 = new cfnt.CachePolicy(this, `${id}-myCachePolicy2`, {
        cachePolicyName: `${id}-cache-policy-default`,
        comment: 'A default policy',
        cookieBehavior: cfnt.CacheCookieBehavior.all(),
        enableAcceptEncodingGzip: false,
        enableAcceptEncodingBrotli: false,
      });

      const webFront = new cfnt.Distribution(this, `${id}-${fullDomain}-front`, {
        
        defaultBehavior: {
          origin: new origins.S3Origin(itineraryBucket),
          allowedMethods: cfnt.AllowedMethods.ALLOW_ALL,
          viewerProtocolPolicy: cfnt.ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
          cachePolicy:myCachePolicy2
        
        },
        
        additionalBehaviors: {
          '/v2/*': {
            origin: new origins.S3Origin(polymerBucket),
            allowedMethods: cfnt.AllowedMethods.ALLOW_ALL,
            viewerProtocolPolicy: cfnt.ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
            cachePolicy: myCachePolicy,
            
          }
        },

        certificate: cert,
        domainNames: [fullDomain],
        defaultRootObject: 'index.html',
        logBucket: logBucket,
        logFilePrefix: `${fullDomain}`,
        errorResponses:[
         {
            httpStatus: 403,
            responseHttpStatus: 200,
            responsePagePath:'/v2/*'
                 
          },
          {
            httpStatus: 404,
            responseHttpStatus: 200,
            responsePagePath:'/v2/*'
          }
         ],
        
        httpVersion:cfnt.HttpVersion.HTTP2
        

      })

      
      // Lookup for Hosted Zone record
      if (cfDist.createSubdomain) {
        const hostedZone = r53.HostedZone.fromLookup(this, `${id}-${fullDomain}-zone`, {
          domainName: cfDist.domain,
        });

        new r53.ARecord(this, `${id}-${fullDomain}-alias`, {
          recordName: `${fullDomain}`,
          comment: `${fullDomain} for stack ${id}`,
          zone: hostedZone,
          target: r53.RecordTarget.fromAlias(new r53targets.CloudFrontTarget(webFront)),
          ttl: cdk.Duration.hours(1)
        });
      }
    }`

### CDK CLI Version

2.28.1 (build d035432)

### Node.js Version

v16.4.0

### OS

Mac

### Language

Typescript

**Comment by Shankureddy** [comment]
I have rechecked my code and I didn't add any new features to my cloudfront compared to V1 but still it's replacing it

**Comment by MightySepp666** [comment]
@Shankureddy this is probably not related to the upgrade of version 2, but to the migration from `CloudFrontWebDistribution` to `Distribution`. This behavior is actually documented in the migration guide: https://github.com/aws/aws-cdk/blob/main/packages/@aws-cdk/aws-cloudfront/README.md#migrating-from-the-original-cloudfrontwebdistribution-to-the-newer-distribution-construct

You need to use an escape hatch to preserve the logical ID of the CloudFormation resource to avoid a replacement.
