### ISSUE TITLE
(ec2): add codeartifact api and respository to InterfaceVpcEndpointAwsService

### ISSUE THREAD

**Issue by michaeldrey** [aws/aws-cdk#21402]
### Describe the feature

I would like to add the following to the InterfaceVpcEndpointAwsService:
```
    declare const vpc: ec2.Vpc;

    new ec2.InterfaceVpcEndpoint(
      this,
      'VpcEndpoint',
      {
        vpc: vpc,
        service: ec2.InterfaceVpcEndpointAwsService.CODEARTIFACT_API,  // Does not exist
      }
    );
```
OR
```
    declare const vpc: ec2.Vpc;

    new ec2.InterfaceVpcEndpoint(
      this,
      'VpcEndpoint',
      {
        vpc: vpc,
        service: ec2.InterfaceVpcEndpointAwsService.CODEARTIFACT_REPOSITORIES,  // Does not exist
      }
    );
```

### Use Case

I have to write out each of these endpoints separately from the existing ones, like so:
```
    this.vpc.addInterfaceEndpoint('AWSEndpointCodeArtifact', {
      service: {
        name: 'com.amazonaws.us-west-2.codeartifact.repositories',
        port: 443,
      },
      privateDnsEnabled: true,
    });
```

```
    this.vpc.addInterfaceEndpoint('AWSEndpointCodeArtifactApi', {
      service: {
        name: 'com.amazonaws.us-west-2.codeartifact.api',
        port: 443,
      },
      privateDnsEnabled: true,
    });
```

### Proposed Solution

I have opened a PR for this feature #21401

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

^2.21.0

### Environment details (OS name and version, etc.)

MacOS 12.5

**Comment by corymhall** [comment]
This issue has been classified as *p2*. That means a workaround is available or it is deemed a nice-to-have feature. Given the amount of work there is to do and the relative priority of this issue, the CDK team is unlikely to address it. That does not mean the issue will never be fixed! If someone from the community submits a PR to fix this issue, and the PR is small and straightforward enough, and meets the quality bars to be reviewed and merged with little effort we will accept that PR. PRs that do not build or need complex or multiple rounds of reviews are unlikely to be merged and will be closed to keep our backlog manageable.

In the mean time, remember that you can always use the escape hatch (https://docs.aws.amazon.com/cdk/v2/guide/cfn_layer.html) mechanism to have fine control over the CloudFormation output you want. We will keep the issue open for discoverability, to collect upvotes, and to facilitate discussion around this topic.

We use +1s *on this issue* to help prioritize our work, and are happy to re-evaluate the prioritization of this issue based on community feedback. You can reach out to the cdk.dev community on Slack (https://cdk.dev/) to solicit support for reprioritization.
