### ISSUE TITLE
aws_ec2:First time deployment of SubnetType PRIVATE_WITH_NAT fails due to lack of IGW

### ISSUE THREAD

**Issue by jeyabalajis** [aws/aws-cdk#21404]
### Describe the bug

Deployment of a VPC with subnet configuration of PRIVATE_WITH_NAT and PUBLIC across two availability zones (i.e. a total of four subnets) fails _first time_ during deploy, since when the NAT Gateway is getting deployed in the public subnet, the Internet Gateway is still not ready.

Error: 'NatGateway nat-0b703f7cbb0328343 is in state failed and hence failed to stabilize. Detailed failure message: Network vpc-04566cd0440b61b36 has no Internet gateway attached'."  

**Workaround:**
1. Deploy VPC with PRIVATE_ISOLATED and PUBLIC.
2. Change code and modify the configuration for the private subnet from PRIVATE_ISOLATED to PRIVATE_WITH_NAT 

**Sample Code:**

```
    String accountNumber = Objects.requireNonNull(props.getEnv()).getAccount();
    String vpcCidr = AccountVpcCidrMap.getAccountVpcCidrMap().get(accountNumber);
    int vpcCidrMask = Integer.parseInt(vpcCidr.split("/")[1]);

    // The subnets are created across two AZs. Hence adding+2 on VPC CIDR Mask to distribute CIDRs across 4 subnets in total.
    SubnetConfiguration privateSubnetWithNat =
        SubnetConfiguration.builder()
            .name("sample-vpc-private-with-nat")
            .subnetType(SubnetType.PRIVATE_WITH_NAT)
            .cidrMask(vpcCidrMask+2)
            .build();

    SubnetConfiguration publicSubnet =
        SubnetConfiguration.builder()
            .name("sample-vpc-public-subnet")
            .subnetType(SubnetType.PUBLIC)
            .cidrMask(vpcCidrMask+2)
            .build();

    List<SubnetConfiguration> subnetConfigurationList = new LinkedList<>();
    subnetConfigurationList.add(privateSubnetWithNat);
    subnetConfigurationList.add(publicSubnet);

    assert accountNumber != null;
    Vpc mlOpsVpc =
        Vpc.Builder.create(this, "mlops-vpc-".concat(accountNumber))
            .cidr(vpcCidr)
            .vpcName("sample-vpc-".concat(accountNumber))
            .natGateways(Constants.NUMBER_OF_NAT_GATEWAYS)
            .maxAzs(Constants.MAX_AZS)
            .enableDnsSupport(Constants.ENABLE_DNS_SUPPORT)
            .enableDnsHostnames(Constants.ENABLE_DNS_HOST_NAME)
            .subnetConfiguration(subnetConfigurationList)
            .build();
```

### Expected Behavior

There needs to be a way of setting up Internet Gateway as a dependency for NAT Gateway.

### Current Behavior

- First time deploy of private subnet with PRIVATE_WITH_NAT and PUBLIC fails
- Workaround: Deploy first with PRIVATE_ISOLATED and change to PRIVATE_WITH_NAT

### Reproduction Steps

- Deploy a VPC with a combination of PRIVATE_WITH_NAT and PUBLIC subnet configuration.

### Possible Solution

**Workaround:**
1. Deploy VPC with PRIVATE_ISOLATED and PUBLIC.
2. Change code and modify the configuration for the private subnet from PRIVATE_ISOLATED to PRIVATE_WITH_NAT 

### CDK CLI Version

2.33.0 (build 859272d)

### Node.js Version

v16.14.0

### OS

Windows 10

### Language

Java

### Language Version

Java 8

**Comment by corymhall** [comment]
@jeyabalajis I am unable to reproduce this using a basic example.

There must be something specific to your configuration that is causing this. Can you provide a
reproducible example that I can deploy?

```ts
    new aws_ec2.Vpc(this, 'Vpc', {
      maxAzs: 2,
      subnetConfiguration: [
        {
          name: 'Private',
          subnetType: aws_ec2.SubnetType.PRIVATE_WITH_NAT,
        },
        {
          name: 'Public',
          subnetType: aws_ec2.SubnetType.PUBLIC,
        },
      ]
    })
