### ISSUE TITLE
QueryExecutionContext: query string can't handle comments

### ISSUE THREAD

**Issue by alondvir** [aws/aws-cdk#21416]
### Describe the bug

When running a query using QueryExecutionContext, all new lines are being ignored, which causes comments to exceed their line.

### Expected Behavior

New line characters shouldn't be ignored.

### Current Behavior

Creating a table from boto3 using QueryExecutionContext ignores new lines, and causes comments to exceeed end of line.

### Reproduction Steps

I Ran the code:
`    boto3.client("athena", region_name="eu-central-1").start_query_execution(
        QueryString="""
            CREATE EXTERNAL TABLE IF NOT EXISTS `TEST_TABLE`
            (
                INT_FIELD INT,
                -- comment that will ruin next lines
                FIELD_AFTER_COMMENT INT
                )
             LOCATION 's3://doesnt-really-exist/'
        
        """,
        QueryExecutionContext={
            'Database': 'default',
            'Catalog': 'AwsDataCatalog'
        },
        ResultConfiguration={
            'OutputLocation': 's3://doesnt-really-exist2/',
        },
    )`

And looked at the console. Actually executed query was (new lines ignored, which caused the comment to overflow):

> CREATE EXTERNAL TABLE IF NOT EXISTS `TEST_TABLE` ( INT_FIELD INT, -- comment that will ruin next lines FIELD_AFTER_COMMENT INT ) LOCATION 's3://doesnt-really-exist/'

### CDK CLI Version

boto3==1.20.24

### Node.js Version

0

### OS

Windows

### Language

Python

### Language Version

python 3.9

**Comment by peterwoodworth** [comment]
Hey, I'm not sure how this is related to CDK. Did you want to report this to the [Boto](https://github.com/boto/boto3) repository instead?
