### ISSUE TITLE
(aws_cdk.ICfnResourceOptions): (Typo `noramlly` should be `normally`)

### ISSUE THREAD

**Issue by rzmk** [aws/aws-cdk#21412]
### Describe the issue

There is a typo under the `condition?` property where it says `noramlly` instead of `normally`.

![image](https://user-images.githubusercontent.com/30333942/182216232-1f784966-b51c-450c-83d9-e2a1afa2a6f8.png)

### Links

- [Documentation page](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.ICfnResourceOptions.html)
- [Direct link to highlight](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.ICfnResourceOptions.html#:~:text=legacy%20templates%2C%20but-,noramlly,-there%20is%20no)

**Comment by peterwoodworth** [comment]
Thanks for the report, I'll get this fixed up
