### ISSUE TITLE
(Python No module named 'aws_elasticloadbalancingv2_targets'): (can not be installed)

### ISSUE THREAD

**Issue by alexelshamouty** [aws/aws-cdk#21425]
### Describe the bug

When using cdk in python and trying to install 'aws_elasticloadbalancingv2_targets' I get an error that it expects constructs library of the following versions 
>=3.3.69,<4.0.0

However, I am using constructs 10.1.64 because I am using aws-cdk-lib.

The documentation does not state what should be used when using aws-cdk-lib and it's not clear how to call the targets module when using CdkV2

Documentation link https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_elasticloadbalancingv2_targets/IpTarget.html

### Expected Behavior

The aws_elasticloadbalancingv2_targets should install and use constructs versions above 10

### Current Behavior

Installation of the package fails because aws-cdk.aws-elasticloadbalancingv2-targets (1.166.1) depends on constructs (>=3.3.69,<4.0.0)

### Reproduction Steps

I am using poetry

Those are the library versions I am using
constructs = "^10.1.64"
aws-cdk-lib = "^2.34.2"

### CDK CLI Version

2.34.1 (build ab3bb71)

### Node.js Version

v18.7.0

### OS

Macos

### Language

Python

### Language Version

3.10

**Comment by corymhall** [comment]
@alexelshamouty since you are using CDK v2 the aws_elasticloadbalancingv2_targets package exists as
part of `aws-cdk-lib`.

```python
from aws_cdk import (
    aws_elasticloadbalancingv2_targets as elbv2_targets,
)
```

**Comment by alexelshamouty** [comment]
could you please point me out then to the right documentation to use? I
could not find this anywhere

Op wo 3 aug. 2022 om 14:06 schreef Cory Hall ***@***.***>:

**Comment by corymhall** [comment]
Our developer guide references that all stable modules are part of aws-cdk-lib https://docs.aws.amazon.com/cdk/v2/guide/work-with-cdk-python.html#python-managemodules. There are also some examples that include the import statement in our API documentation

https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_elasticloadbalancingv2_targets/AlbArnTarget.html

Let me know if you think there is a better place we should put this information.
