### ISSUE TITLE
docs: wrong install commands in documentation

### ISSUE THREAD

**Issue by jumic** [aws/aws-cdk#21427]
### Describe the issue

The AWS CDK v2 documentation contains wrong installation commands.

**CodeBuild and SSM (stable constructs):**
Example: CodeBuild
> npm i @aws-cdk/aws-codebuild

This package contains the v1 version. In v2 it is not necessary anymore to install this package.

**IoT and IoT Events (experimental constructs):**
Example: IoT
> npm i @aws-cdk/aws-iot

Correct command: `npm i @aws-cdk/aws-iot-alpha`

--> Should we remove the installation sections from the documentations? Other CDK modules don't contain the installation section. I found them only the four README files which I referenced below. That's why I'm wondering if we can just delete them.

### Links

Stable constructs
- [CodeBuild](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_codebuild-readme.html#installation)
- [SSM](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ssm-readme.html#installation)

Experimental constructs
- [IoT](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-iot-alpha-readme.html#installation)
- [IoT Events](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-iotevents-alpha-readme.html#installation)

**Comment by TheRealAmazonKendra** [comment]
Yeah, we should update these. Thanks for catching it. I'm classifying this as a p2, which means we won't likely have time to do this fix but we welcome contributions for it!

**Comment by watany-dev** [comment]
This certainly looks unnecessary. I will remove the install section as it seems to be a quick fix.
