### ISSUE TITLE
ImageBuilder: Image (CfnImage) do not clean generated AMI on destroy

### ISSUE THREAD

**Issue by mhtrinhLIC** [aws/aws-cdk#21431]
### Describe the bug

AMI (and snapshots) generated using CfnImage are left after the stack is destroyed. 

### Expected Behavior

The AMI is deleted after the stack is detroyed. 

### Current Behavior

NA

### Reproduction Steps

NA

### Possible Solution

Is there any way to specify removal policy  ? 
I tried 
``` python
cfn_image.node.find_child("Resource").cfn_options.deletion_policy = cdk.CfnDeletionPolicy.DELETE
```

But got error : 
```
jsii.errors.JSIIError: No child with id: 'Resource'
```

### CDK CLI Version

2.33.0

### Node.js Version

v16.16.0

### OS

Ubuntu

### Language

Python

### Language Version

3.8

**Comment by peterwoodworth** [comment]
Sorry for the long response time, 

You don't need to find the child of a `cfn_image`. That is already the cfn resource you need to access. So, the following should work.

```
cfn_image.cfn_options.deletion_policy = cdk.CfnDeletionPolicy.DELETE
```

If not, please post the full reproduction code

**Comment by mhtrinhLIC** [comment]
> Sorry for the long response time,
> 
> You don't need to find the child of a `cfn_image`. That is already the cfn resource you need to access. So, the following should work.
> 
> ```
> cfn_image.cfn_options.deletion_policy = cdk.CfnDeletionPolicy.DELETE
> ```
> 
> If not, please post the full reproduction code
> 
> Ping me, or open a discussion to continue this conversation

@peterwoodworth : I opened an discussion here: https://github.com/aws/aws-cdk/discussions/23360
Not sure if this is what I am suppose to do ?
