### ISSUE TITLE
(core): No ability to explicitly set OutputKey for CfnOutput

### ISSUE THREAD

**Issue by SamStephens** [aws/aws-cdk#21432]
### Describe the feature

I would expect [https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk/CfnOutput.html](CfnOutput] to provide a `key` or `output_key` parameter, that would allow me to override the automatically generated OutputKey with one I explicitly provide.

This would parallel many other constructs, such as [aws_lambda.LambdaFunction](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_lambda/Function.html) which provides a `function_name` parameter to allow you to override the automatically generated FunctionName.

### Use Case

In order to programmatically work with stack outputs, I need a well known identifier for each output.

At the moment I'm being forced to provide an ExportName name for the output, even though I don't use the output in any other stack. This means I have to worry about the account wide (or is it region wide?) namespace of export names, rather than the stack wide namespace of stack output names.

### Other Information

This issue is touched upon by https://github.com/aws/aws-cdk/issues/1773

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.35.0, Python

### Environment details (OS name and version, etc.)

Ubuntu 20.04 on WSL 2 within Windows 10.0.19044

**Comment by rix0rrr** [comment]
```ts
const  output = new CfnOutput(this, 'Output', ...);
output.overrideLogicalId('xyz');
```

**Comment by SamStephens** [comment]
@rix0rrr I'd have appreciated an opportunity to comment before this was closed.

It's great that `overrideLogicalId` provides this capability, but the documentation does not make that clear at all.

Could you please consider reopening this issue, and using it as an umbrella for updating the documentation of the `overrideLogicalId` method of `CfnOutput` to make it clear the logicalId is what drives the name of the Output?

Or is the problem here actually because this is a Level 1 construct, and that the best way to address this confusion is to add a Level 2 `Output` construct that provides a clearer interface to the Level 1 construct?
