### ISSUE TITLE
(aws-ec2): MetadataOptionsProperty.instanceMetadataTags is not precisely auto-generated in ec2.generated.d.ts.

### ISSUE THREAD

**Issue by kuzukami** [aws/aws-cdk#21434]
### Describe the bug

see the source 'ec2.generated.d.ts' L.7222 in 2.34.2 (build 7abcbc6)
```
        readonly httpTokens?: string;
        /**
         * Set to `enabled` to allow access to instance tags from the instance metadata. Set to `disabled` to turn off access to instance tags from the instance metadata. For more information, see [Work with instance tags using the instance metadata](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Tags.html#work-with-tags-in-IMDS) .
         *
         * Default: `disabled`
         *
         * @link http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-launchtemplatedata-metadataoptions.html#cfn-ec2-launchtemplate-launchtemplatedata-metadataoptions-instancemetadatatags
         */
        readonly ?: string;
```

**'readonly ?: string;'** is apparently broken.

### Expected Behavior

**'readonly instanceMetadataTags?: string;'** is generated.

### Current Behavior

**'readonly ?: string;'** is generated.

### Reproduction Steps

see the source 'ec2.generated.d.ts' L.7222 in 2.34.2 (build 7abcbc6)

### Possible Solution

Please configure the parameter for cfn2ts.

### CDK CLI Version

2.34.2 (build 7abcbc6)

### Node.js Version

v16.16.0

### OS

Ubuntu 20.04

### Language

Typescript

**Comment by corymhall** [comment]
@kuzakami can you try removing node_modules and installing again? I can't reproduce this issue.

**Comment by kuzukami** [comment]
Thanks. That's solved. I got recovered after clear&reinstall node_module.
