### ISSUE TITLE
(aws-ec2): LaunchTemplate miss TagsSpecifications itself

### ISSUE THREAD

**Issue by BDeus** [aws/aws-cdk#21440]
### Describe the feature

When specifying a launchtemplate inside an AutoScalingGroup,
the LaunchTemplate itself does not have any tags

According to CFN, `TagsSpecifications` field in root (not in `LaunchTemplateData`) is missing in the template generation in CDK
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-launchtemplate.html

### Use Case

Missing tags on the LaunchTemplate resource itself

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.30.0

### Environment details (OS name and version, etc.)

linux

**Comment by corymhall** [comment]
It looks like we need to implement the same sort of logic for the LaunchTemplate tags that we have for the tags within
 `launchTemplateData`
 https://github.com/aws/aws-cdk/blob/main/packages/@aws-cdk/aws-ec2/lib/launch-template.ts#L565-L589

 This issue has been classified as *p2*. That means a workaround is available or it is deemed a nice-to-have feature. Given the amount of work there is to do and the relative priority of this issue, the CDK team is unlikely to address it. That does not mean the issue will never be fixed! If someone from the community submits a PR to fix this issue, and the PR is small and straightforward enough, and meets the quality bars to be reviewed and merged with little effort we will accept that PR. PRs that do not build or need complex or multiple rounds of reviews are unlikely to be merged and will be closed to keep our backlog manageable.

 In the mean time, remember that you can always use the escape hatch (https://docs.aws.amazon.com/cdk/v2/guide/cfn_layer.html) mechanism to have fine control over the CloudFormation output you want. We will keep the issue open for discoverability, to collect upvotes, and to facilitate discussion around this topic.

 We use +1s *on this issue* to help prioritize our work, and are happy to re-evaluate the prioritization of this issue based on community feedback. You can reach out to the cdk.dev community on Slack (https://cdk.dev/) to solicit support for reprioritization.
