### ISSUE TITLE
(aws-cdk): cdk bootstrap prints YAML template even when using --json option

### ISSUE THREAD

**Issue by rantoniuk** [aws/aws-cdk#21456]
### Describe the bug

OK, I'm either stupid and I'm missing something obvious or the command --show-template doesn't behave like it should.
The below commands are always printing the same template for me:
```sh
$ cdk bootstrap --show-template > x
$ cdk bootstrap --show-template --bootstrap-kms-key-id=AWS_KEY_MANAGED > x2
$ cdk bootstrap --show-template --bootstrap-customer-key > x3
$ cdk bootstrap --show-template --bootstrap-customer-key asd > x4
$ cdk bootstrap --show-template --json > x5

$ diff x* 
$
(no output, same files)
```

Why? There is no `--dry-run- `option, so I expect to be able to see the template modified with the CLI options to validate before actual deployment. Instead, even `-j` does not have any effect whatsoever for me. Am I missing something?

Also, in the template I see that it's possible to use AWS_MANAGED_KEY for `FileAssetsBucketKmsKeyId`. 
Shouldn't this be possible to enable this via CLI (and be documented in cdk bootstrap -h) ?

I even tried to do the following:
1. `cdk bootstrap --show-template > template`
1. (edited the template file and set FileAssetsBucketKmsKeyId to AWS_MANAGED_KEY
1. `cdk bootstrap --cloudformation-execution-policies arn:aws:iam::aws:policy/AdministratorAccess aws://XXX/eu-west-1 --template template --no-execute`

Result:
- `CDKToolkit: creating CloudFormation changeset... Environment bootstrapped (no changes).`
- CloudFormation shows an empty and FAILED changeset.

### CDK CLI Version

2.35.0 (build 5c23578)

### Node.js Version

v14.19.3

### OS

MacOS

### Language

Typescript

**Comment by rantoniuk** [comment]
I was able to effectively re-bootstrap (update) the bucket by using `cdk bootstrap --bootstrap-kms-key-id arn:aws:kms:eu-west-1:.....` command, but without review. 
The changeset that was created with `--no-execute` was either empty or it contained "modify" on some resources but I was unable to see how the resources are going to be modified (which is the purpose of the ChangeSet review right?)

**Comment by peterwoodworth** [comment]
These options aren't going to show changes because they make use of CloudFormation parameters. Supplying a different parameter will not show a difference in the template.

The `--json` option isn't working here because that option is a global option showing for all our commands, but it isn't actually enabled for the `bootstrap` command. Could be changed here where it gets printed https://github.com/aws/aws-cdk/blob/cf3bb6e9ced5e3d18e782e7144858078c70cdcf9/packages/aws-cdk/lib/api/bootstrap/bootstrap-environment.ts#L38

**Comment by arewa** [comment]
Hi @peterwoodworth and @rantoniuk , I prepared a fix and it was already merged, perhaps we could resolve this issue.
