### ISSUE TITLE
(rds): Support PostgreSQL v14 with AuroraPostgresEngineVersion  

### ISSUE THREAD

**Issue by bernardomichel** [aws/aws-cdk#21454]
### Describe the feature

PostresEngineVersion is not supporting the latest version of PostgreSQL

### Use Case

I want to deploy the latest version of PostgreSQL on my aws account

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.35

### Environment details (OS name and version, etc.)

macos

**Comment by corymhall** [comment]
For now the workaround would be to use

```ts
AuroraPostgresEngineVersion.of('14.3', '14', { s3Import: true, s3Export: true });
```

This issue has been classified as *p2*. That means a workaround is available or it is deemed a nice-to-have feature. Given the amount of work there is to do and the relative priority of this issue, the CDK team is unlikely to address it. That does not mean the issue will never be fixed! If someone from the community submits a PR to fix this issue, and the PR is small and straightforward enough, and meets the quality bars to be reviewed and merged with little effort we will accept that PR. PRs that do not build or need complex or multiple rounds of reviews are unlikely to be merged and will be closed to keep our backlog manageable.

In the mean time, remember that you can always use the escape hatch (https://docs.aws.amazon.com/cdk/v2/guide/cfn_layer.html) mechanism to have fine control over the CloudFormation output you want. We will keep the issue open for discoverability, to collect upvotes, and to facilitate discussion around this topic.

We use +1s *on this issue* to help prioritize our work, and are happy to re-evaluate the prioritization of this issue based on community feedback. You can reach out to the cdk.dev community on Slack (https://cdk.dev/) to solicit support for reprioritization.
