### ISSUE TITLE
aws-events: EventBus no longer generates a name if needed 

### ISSUE THREAD

**Issue by vgkowski** [aws/aws-cdk#21469]
### Describe the bug

When creating an EventBus using `cdk.physicalName.GENERATE_IF_NEEDED` as the Event Bus name, cdk fails

### Expected Behavior

`cdk.physicalName.GENERATE_IF_NEEDED` should generate a name if required by `CfnEventBus`

### Current Behavior

CDK fails with the following error
`CfnSynthesisError: Resolution error: Supplied properties not correct for "CfnEventBusProps"`

### Reproduction Steps

```
import { PhysicalName, Stack, StackProps } from 'aws-cdk-lib';
import { EventBus } from 'aws-cdk-lib/aws-events';
import { Construct } from 'constructs';

export class MyStack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);

    new EventBus(this, 'myEventBus', {
      eventBusName: PhysicalName.GENERATE_IF_NEEDED,
    });
  }
}
```

### CDK CLI Version

2.35.0 (build 5c23578)

### Node.js Version

v16.15.1

### OS

macos 12.4

### Language

Typescript

**Comment by peterwoodworth** [comment]
When you say in the title that this no longer generates a name if needed, does that mean this code used to work on previous versions?

`PhysicalName.GENERATE_IF_NEEDED` is meant for cross-environment scenarios, if all you desire is for the name to be autogenerated then CloudFormation will do that for you here
