### ISSUE TITLE
Amazon.CDK.AWS.EC2.LaunchTemplate does not have Tags property

### ISSUE THREAD

**Issue by icelava** [aws/aws-cdk#21502]
### Describe the bug

Using Amazon.CDK.Lib 2.35.0 in Visual Studio 2022 and LaunchTemplate does not have Tags property to manipulate with.

### Expected Behavior

Tags property object available for adding tags.

### Current Behavior

Tags object unavailable for use.

### Reproduction Steps

Create new LaunchTemplate() object; access its .Tags property (unavailable).

### CDK CLI Version

2.35.0

### Framework Version

.NET Core 3.1

### Node.js Version

NA

### OS

Windows

### Language

.NET

### Language Version

C# 8

**Comment by ItielOlenick** [comment]
I've been searching all over.
There is no way in CDK (typescript or any other wrapper) to add a tag to a newly created spot fleet request that uses "launchTemplateConfigs" instead of "launchSpecifications", where the latter does have 'tagSpecifications'.

This makes it a headache when having multiple requests generated at one - there is no way to differentiate.

reference: https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_ec2/CfnSpotFleet.html?highlight=cfnspotfleet

**Comment by corymhall** [comment]
You should be able to add tags by doing this:

```ts
Tags.of(this).add('SomeTagKey', 'SomeTagValue').
```

Where `this` is the scope that contains the `LaunchTemplate`. Or to just apply it to the launch
template.

```ts
const lt = new LaunchTemplate();
Tags.of(lt).add('SomeTagKey', 'SomeTagValue');
```

This will add tags to the `instances` and `volumes` created by the launch template as well as the
launch template itself (added in #21445)

**Comment by ItielOlenick** [comment]
> You should be able to add tags by doing this:
> 
> ```ts
> Tags.of(this).add('SomeTagKey', 'SomeTagValue').
> ```
> 
> Where `this` is the scope that contains the `LaunchTemplate`. Or to just apply it to the launch template.
> 
> ```ts
> const lt = new LaunchTemplate();
> Tags.of(lt).add('SomeTagKey', 'SomeTagValue');
> ```
> 
> This will add tags to the `instances` and `volumes` created by the launch template as well as the launch template itself (added in #21445)

Thanks, that is what I did.
But there still is the issue I wrote about where you can't tag the spot fleet request (created in the CDK).
Even if it uses the launch template that is tagged

**Comment by corymhall** [comment]
@ItielOlenick it looks like that is because `LaunchTemplate`s do not support tagging spot fleet requests. https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-tagspecification.html#aws-properties-ec2-launchtemplate-tagspecification-properties

**Comment by ItielOlenick** [comment]
> @ItielOlenick it looks like that is because `LaunchTemplate`s do not support tagging spot fleet requests. https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-tagspecification.html#aws-properties-ec2-launchtemplate-tagspecification-properties

Exactly. So there is NO way to tag a spot fleet requests that uses launch template.
That is a crucial property that is missing.

If for example I create 5 spot fleet requests in the CDK, there is no way for me to determine which is which.

FYI can use launch configuration that does have tag properties as we need to use on demand instances as well.

**Comment by corymhall** [comment]
@ItielOlenick that is a limitation with CloudFormation (which the CDK uses). I would recommend creating an issue on the [cloudformation-coverage-roadmap](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap) to add coverage for spot fleet. Once CloudFormation adds support it can be added to CDK.

**Comment by ItielOlenick** [comment]
@corymhall will do. Thanks

**Comment by corymhall** [comment]
@icelava let me know if I answered your question.

**Comment by icelava** [comment]
The Tags.Of() method works. Thanks.
