### ISSUE TITLE
aws-codedeploy: Many Lambda deployment groups in a stack cause rate exceeded errors

### ISSUE THREAD

**Issue by MarkRobbo** [aws/aws-cdk#21516]
### Describe the bug

When deploying many lambda deployment groups at once (15 in a stack is enough to trigger this issue) with custom deployment configuration [as per the documentation](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_codedeploy.LambdaDeploymentGroup.html), rate exceeded errors are thrown by CodeDeploy due to throttling on the `createDeploymentConfig` action

### Expected Behavior

Expected the deployment to succeed by backing off and still creating the resources

### Current Behavior

The deployment fails with `rate exceeded` errors

### Reproduction Steps

Code here is the example code from https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_codedeploy.LambdaDeploymentGroup.html with a loop around it:

```
for (i=0; i<17;i++) {
  const config = new codedeploy.CustomLambdaDeploymentConfig(this, 'CustomConfig' + i, {
    type: codedeploy.CustomLambdaDeploymentConfigType.CANARY,
    interval: Duration.minutes(1),
    percentage: 5,
  });
  
  declare const application: codedeploy.LambdaApplication;
  declare const alias: lambda.Alias;
  const deploymentGroup = new codedeploy.LambdaDeploymentGroup(this, 'BlueGreenDeployment' + i, {
    application,
    alias,
    deploymentConfig: config,
  });
}
```

### Possible Solution

Many custom resources are deployed at once (https://github.com/aws/aws-cdk/blob/main/packages/@aws-cdk/aws-codedeploy/lib/lambda/custom-deployment-config.ts#L109) calling the `createDeploymentConfig` operation. A backoff could be implemented in CDK or different mechanism of configuring Lambda Deployment Groups used which has such a backoff.

### Additional Information/Context

Possible workaround is to add dependencies between deployment groups to artificially stagger deployments but this is not a good customer experience

### CDK CLI Version

1.128.0

### Node.js Version

14.x

### OS

Linux

### Language

Typescript

**Comment by indrora** [comment]
The CDKv1 is in maintenance mode; Please confirm that this behavior still exists in the CDKv2. 

Additionaly, you should update your version of Node. Node14 is not guaranteed to be supported in the future and a current LTS (18 will be as of 2022-10-25, in just over 1 month) is recommended.

**Comment by TheRealAmazonKendra** [comment]
Yes to @indrora's point, but also, is getting a rate limit increase from code deploy an option?

**Comment by peterwoodworth** [comment]
Feel free to leave a comment and ping us if you wish to continue this discussion

Typically rate limit errors in CDK thrown by services are worked around by adding dependencies to slow down the rate at which resources are created. I suggest doing this if getting a rate limit increase isn't possible
