### ISSUE TITLE
(aws-cloudfront): ResponseHeadersPolicy policy name can exceed maximum

### ISSUE THREAD

**Issue by blimmer** [aws/aws-cdk#21524]
### Describe the bug

The auto-generated `Name` for a CloudFront `ResponseHeadersPolicy` can be longer than the (unpublished) maximum of 129 characters. These very long stack names are common when using CDK Pipelines.

### Expected Behavior

I expected CDK to truncate the auto-generated name to be shorter than the maximum allowed policy name.

### Current Behavior

When the name field is too long, it produces this very opaque error message:

```
1:43:29 PM | CREATE_FAILED        | AWS::CloudFront::ResponseHeadersPolicy | ResponseHeadersPolicy
Resource handler returned message: "Invalid request provided: AWS::CloudFront::ResponseHeadersPolicy"
(RequestToken: d86fa560-67f9-db71-29af-402e0fdee080, HandlerErrorCode: InvalidRequest)
1:43:30 PM | ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack             | AVeryLongCdkBugRep...eAct
uallyQuiteLong
The following resource(s) failed to create: [ResponseHeadersPolicy13DBF9E0]. Rollback requested by use
r.
1:43:30 PM | ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack             | AVeryLongCdkBugRep...eAct
uallyQuiteLong
The following resource(s) failed to create: [ResponseHeadersPolicy13DBF9E0]. Rollback requested by use
r.
```

I was able to determine the `Name` field was too long by trying to create a policy in via the UI with the same name. The UI gave me back a much better error message:

> The parameter Name is too big.

![Screen Shot 2022-08-09 at 13 49 21](https://user-images.githubusercontent.com/630449/183748237-0d550e31-9f57-4096-9d50-5cc4908eefcf.png)

### Reproduction Steps

https://github.com/blimmer/cdk-bug-reports/commit/2e519b8ba962b09276a71fa26344d1a2d457a572

This commit shows the problem. This is a fresh repo generated by `cdk init` with just the changes indicated in the diff.

### Possible Solution

There are lots of examples scattered throughout the code where a name is restricted in length, e.g.: 

https://github.com/aws/aws-cdk/blob/74318c7d22bfc00de9e005f68a0a6aaa58c7db39/packages/%40aws-cdk/aws-codeguruprofiler/lib/profiling-group.ts#L197-L203

The character limit isn't defined explicitly in the [CFN docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-responseheaderspolicy-responseheaderspolicyconfig.html#cfn-cloudfront-responseheaderspolicy-responseheaderspolicyconfig-name) or in the API docs:

```
Name -> (string)
  A name to identify the response headers policy.

  The  name  must  be unique for response headers policies in this
  Amazon Web Services account.
```

From trial and error in the console, it appears the limit is 129 characters.

### CDK CLI Version

2.36.0 (build 7cde279)

### Node.js Version

16.14.0

### OS

macOS

### Language

Typescript

**Comment by peterwoodworth** [comment]
I'm unable to reproduce this, because I'm failing deployment with a short name and I'm not sure why... I'm receiving the same error message. Have you successfully deployed this resource with a name below 129 characters where just changing the name to be more than 128 characters will fail deployment? Or was all your testing done in the console

**Comment by blimmer** [comment]
Yep, I can deploy < 129 characters while failing with > 129. I tested with the linked repro from the ticket (as well as the console).

**Comment by peterwoodworth** [comment]
Thanks, I've reported this internally to CloudFormation to implement better error messages for this resource so that we can get to the bottom of all these errors
