### ISSUE TITLE
(aws-waf): Construct coverage for AWS Shield Advanced

### ISSUE THREAD

**Issue by greg5123334** [aws/aws-cdk#21531]
### Describe the feature

Currently, there is no official Cloudformation nor CDK support for [AWS Shield](https://docs.aws.amazon.com/waf/latest/developerguide/enable-ddos-prem.html). It would be nice.

### Use Case

Currently, users are required to [Subscribe to AWS Shield Advanced](https://docs.aws.amazon.com/waf/latest/developerguide/enable-ddos-prem.html) manually (e.g via console), and have no supported methods of enabling and configuring AWS Shield Advanced in an automated or declarative fashion.

### Proposed Solution

Whilst there is already an enhancement request open on Cloudformation's coverage roadmap to implement a [AWS::Shield::ProectionAssociation](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/677) resource type, it may be worth exploring from a CDK's side as well to implement an L2 or L3 construct to abstract this process for user's to be able to conveniently provision Shield Advanced resources.

My initial thoughts are to implement this by means of a Step Functions state machine encapsulated by a custom L3 construct, but i am open and eager to hear other suggestions as well. Please let me know if i can clarify anything.

### Other Information

No constructs in CDK API docs
[aws_waf](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_waf-readme.html)
[aws_wafv2](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_wafv2-readme.html)

Nothing in [Constructs hub](https://constructs.dev/search?q=shield&offset=0)

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.36.0 (build 7cde279)

### Environment details (OS name and version, etc.)

N/A

**Comment by peterwoodworth** [comment]
You've noted that this isn't supported by CloudFormation yet - Our L2 and L3 resources are (for the most part) built on top of L1 constructs given to us by CloudFormation. This would have to be implemented with custom resources, and I don't think that's something we'd want to do for this feature.

**Comment by greg5123334** [comment]
hey Peter, thanks for the feedback. understood...so it seems we would need to wait for a new resource type to be considered by the Cfn team?...anyway, thanks for taking a look.

**Comment by peterwoodworth** [comment]
Yeah we will need support from CloudFormation here. The best thing to do here is to show your support for this feature on the linked issue in the coverage roadmap

**Comment by fknittel** [comment]
FYI: CloudFormation support is now available: https://aws.amazon.com/about-aws/whats-new/2023/05/aws-shield-advanced-cloudformation/

**Comment by xavi-bean** [comment]
@greg5123334 There is now Cloudformation support for Shield Advance. Any plans of creating the CDK module for it?
Thanks
