### ISSUE TITLE
(codebuild): ReportGroup grants test permissions when set to CODE_COVERAGE

### ISSUE THREAD

**Issue by ghdoergeloh** [aws/aws-cdk#21534]
### Describe the bug

grantWrite on a ReportGroup only applies `'codebuild:CreateReport', 'codebuild:UpdateReport', 'codebuild:BatchPutTestCases'`. If you use a ReportGroup with type: "CODE_COVERAGE" it still sets those actions as allowed, but misses the `'codebuild:BatchPutCodeCoverages'`.

### Expected Behavior

`new ReportGroup(...,{type: ReportGroupType.TEST} ).grantWrite(codeBuildStep)`
should add a policy statement with `'codebuild:CreateReport', 'codebuild:UpdateReport', 'codebuild:BatchPutTestCases'`

while

`new ReportGroup(...,{type: ReportGroupType.CODE_COVERAGE} ).grantWrite(codeBuildStep)`
should add a policy statement with `'codebuild:CreateReport', 'codebuild:UpdateReport', 'codebuild:BatchPutCodeCoverages'`

### Current Behavior

`new ReportGroup(...,{type: ReportGroupType.CODE_COVERAGE} ).grantWrite(codeBuildStep)`
adds a policy statement with `'codebuild:CreateReport', 'codebuild:UpdateReport', 'codebuild:BatchPutTestCases'`

### Reproduction Steps

```ts
    const testReports = new ReportGroup(this, 'TestReports', {
      type: ReportGroupType.TEST,
    });
    const coverageReports = new ReportGroup(this, 'CoverageReports', {
      type: ReportGroupType.CODE_COVERAGE,
    });

    const buildAndTestStep = new CodeBuildStep('BuildAndTestStep', {
    ...
      partialBuildSpec: BuildSpec.fromObject({
      ...
        reports: {
          [coverageReports.reportGroupArn]: {
            'file-format': 'CLOVERXML',
            files: ['coverage/clover.xml'],
          },
          [testReports.reportGroupArn]: {
            'file-format': 'JUNITXML',
            files: ['**/junit.xml'],
          },
        },
      }),
    });
    ...
    const pipeline = new CodePipeline(this, 'Pipeline', {
      synth: buildAndTestStep,
    });
    
    pipeline.buildPipeline();

    testReports.grantWrite(buildAndTestStep);
    coverageReports.grantWrite(buildAndTestStep);
 ```

### CDK CLI Version

2.37.0

### Node.js Version

16.15.1

### OS

Ubuntu 22.04 LTS (Linux 5.15.0-43)

### Language

Typescript

### Language Version

4.7.4

**Comment by peterwoodworth** [comment]
Yeah it looks like this got overlooked when we added the code coverage option. We can adjust the grantwrite method to consider what type of ReportGroup is getting created here https://github.com/aws/aws-cdk/blob/16c0c988fe47dc8962ebbccc5755613735fedd28/packages/%40aws-cdk/aws-codebuild/lib/report-group.ts#L42-L51

I'm marking this as p2, which means we won't be able to get to this issue soon, but are willing to review any PRs for this issue 🙂

**Comment by daschaa** [comment]
@peterwoodworth Since I introduced this bug, I will take care of it. 🤕

**Comment by peterwoodworth** [comment]
Thanks a bunch @daschaa 🙂
