### ISSUE TITLE
(aws_ec2): (VPC network interfaces are not tagged by default)

### ISSUE THREAD

**Issue by S3ky** [aws/aws-cdk#21536]
### Describe the bug

Hi,

while creating resources (VPC interface endpoint, VPC gateway endpoint, EC2, Network load balancer etc.) from ec2 module none of network interfaces, which were created were tagged.

### Expected Behavior

All network interfaces to be tagged.

### Current Behavior

No tags for all VPC network interfaces.

### Reproduction Steps

Minimal snippet:

endpoint = aws_ec2.InterfaceVpcEndpoint(self.stack, 'id',
                                                service=service.service,
                                                vpc=vpc, private_dns_enabled=True, security_groups=security_groups,
                                                subnets=aws_ec2.SubnetSelection(subnets=subnet_endpoints))

Tags.of(endpoint).add(key='Test', value='test')

// For all other (not just EC2 related) resources it's tagging properly, however for all network interfaces (not just for endpoints) created this way, tags are not applicable to these AWS network interfaces.

### CDK CLI Version

2.34.2

### Node.js Version

v18.7.0

### OS

Archlinux

### Language

Python

### Language Version

Python (3.9)

**Comment by peterwoodworth** [comment]
Tags are only applied to resources which are considered taggable. The [EC2::VpcEndpoint](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcendpoint.html) lacks a `tags` attribute, so the tags aspect cannot be applied here.

If you desire to see this resource become taggable, I suggest opening up an issue in the [Cfn Coverage Roadmap repository](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues) if one doesn't already exist for this. Once this is implemented in Cfn it will work in CDK automatically. Unfortunately there's no action CDK team can take to fix this

**Comment by S3ky** [comment]
@peterwoodworth, thank you, you are right. Indeed there are several open issues (top 2: https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/196 and https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/350)

**Comment by csbrown** [comment]
@peterwoodworth it looks like Elastic Network Interfaces can now be tagged?  At least, the AWS console lets me tag the interface that was created by CDK, but did not get a tag from CDK.

Is this something that we can reopen now that tagging of ENIs is supported?

**Comment by peterwoodworth** [comment]
@csbrown the issue wasn't that they couldn't be tagged at all - it's that CloudFormation doesn't offer it. It's still the case that it's unsupported by CloudFormation. When it is supported, we will automatically support that in CDK once the change propagates to us. Please view the links posted above to track their progress in being added to cloudformation

**Comment by mircea97** [comment]
Any updates? It's still not working for ENI.
