### ISSUE TITLE
(aws-cdk-lib/aws-kinesisanalyticsv2): (CfnApplication could not find code asset in S3)

### ISSUE THREAD

**Issue by tiansu-yu-idealo** [aws/aws-cdk#21552]
### Describe the bug

I am trying to deploy an Flink Java application through KDA v2 (L1 construct). In the configuration `CfnApplication.applicationConfiguration.applicationCodeConfiguration.codeContent` part, I tried to use `aws-s3-asset` to upload the `mvn package`ed jar file into a bucket, and reference it inside the `codeContent` properties. 

But each time I `cdk deploy` the stack, I got the error message: 
```
CREATE_FAILED        | AWS::KinesisAnalyticsV2::Application | flinkApp
Resource handler returned message: "Please check the role provided or validity of S3 location you provided. 
We are unable to get the specified fileKey: <hash-string>.jar in the specified bucket:
cdk-<some-string>-assets-<accountId>-eu-central-1 
(Service: KinesisAnalyticsV2, Status Code: 400, Request ID: <id>)" (RequestToken: <token>, HandlerErrorCo
de: InvalidRequest)
```
But through `aws s3 ls cdk-<some-string>-assets-<accountId>-eu-central-1 | grep .jar` I could find the exact file. 

This is the configuration for code content:
```
applicationCodeConfiguration: {
        codeContent: {
          s3ContentLocation: {
            bucketArn: flinkAppJarAsset.bucket.bucketArn,
            fileKey: flinkAppJarAsset.s3ObjectKey
          }
        },
        codeContentType: "ZIPFILE"
      },
```
This is the setup for the code asset: 
```
const flinkAppJarAsset = new Asset(this, "flinkAppJarAsset", {
      path: path.join(__dirname, `../../../target/${jarFileName}`)
    })
```

### Expected Behavior

CDK deploy should be able to reach the jar file and continue the synth. 

### Current Behavior

CDK deploy stops at the step where the Flink App stack tries to reach the jar file. 

### Reproduction Steps

This is an abducted version of the stack: 
```
import {CfnOutput, CfnTag, Stack, StackProps} from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as iam from 'aws-cdk-lib/aws-iam';
import * as kda from 'aws-cdk-lib/aws-kinesisanalyticsv2';
import {Asset} from "aws-cdk-lib/aws-s3-assets";
import * as path from "path";

const flinkAppConfig = {
  name: "someName",
  description: "someDescription",
  runtime: "FLINK-1_11",
}

export class FlinkAppStack extends Stack {

  readonly flinkApp: kda.CfnApplication

  readonly flinkAppExecutionRole: iam.Role

  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);

    const flinkAppJarAsset = new Asset(this, "flinkAppJarAsset", {
      path: path.join(__dirname, `../../../target/${jarFileName}`)
    })

    this.flinkAppExecutionRole = new iam.Role(this, "flinkAppExecutionRole", {
      assumedBy: new iam.ServicePrincipal("kinesisanalytics.amazonaws.com")
    })

    flinkAppJarAsset.grantRead(this.flinkAppExecutionRole)

    this.flinkApp = new kda.CfnApplication(this, 'flinkApp', {
      runtimeEnvironment: flinkAppConfig.runtime,
      serviceExecutionRole: this.flinkAppExecutionRole.roleArn,
      applicationConfiguration: {
        applicationCodeConfiguration: {
          codeContent: {
            s3ContentLocation: {
              bucketArn: flinkAppJarAsset.bucket.bucketArn,
              fileKey: flinkAppJarAsset.s3ObjectKey
            }
          },
          codeContentType: "ZIPFILE",
        },
      applicationName: flinkAppConfig.name,
      applicationDescription: flinkAppConfig.description,
    });
  }
}
```

### CDK CLI Version

2.37.0

### Node.js Version

v18.2.0

### OS

MacOS12.4

### Language

Typescript

**Comment by peterwoodworth** [comment]
I was able to reproduce this, and fix the issue.

This is happening because the policy granting S3 permissions which needs to be added to the role is not getting created before the Application is getting created. All you need to do is add a depends on statement from the application for the policy -

```
      this.flinkApp = new kda.CfnApplication(...);

      const policy = this.flinkAppExecutionRole.node.findChild('DefaultPolicy') as iam.Policy
      const cfnpolicy = policy.node.defaultChild as iam.CfnPolicy;
      this.flinkApp.addDependsOn(cfnpolicy)
```

**Comment by tiansu-yu-idealo** [comment]
Thanks for the response. This is first time I wrote L1 construct. In the end, I have realized  the same thing, namely, construct dependencies on L1 does not resolve by itself. Like you have mentioned `node.addDependsOn` must be stated in order for them to be synthed in the right order. 
Thanks a lot. ;)

**Comment by dave4988** [comment]
Is there a reason this was closed without being solved? Sure there is a workaround, but this should not be expected behavior.
