### ISSUE TITLE
(aws-ec2): Drift occurs when adding ingress rule with security group as peer

### ISSUE THREAD

**Issue by abjoshi2785** [aws/aws-cdk#21558]
### Describe the bug

The SecurityGroup does not inlines ingress rules when peer is a SecurityGroup. It seems like this has been done to prevent a cyclic reference. But the CFT produced always goes into a drift.

### Expected Behavior

No drift in cloud formation template being generated.

### Current Behavior

The template goes into drift.

### Reproduction Steps

CFT with connections from another security group.

### CDK CLI Version

1.167.0

### Node.js Version

v18.2.0

### OS

MAC

### Language

Python

**Comment by corymhall** [comment]
@abjoshi2785 can you provide a reproducable example?

**Comment by abjoshi2785** [comment]
`{
 "Resources": {
  "saleswebsg": {
   "Type": "AWS::EC2::SecurityGroup",
   "Properties": {
    "GroupDescription": "web instance security group",
    "GroupName": "sales-web-sg",
    "SecurityGroupEgress": [
     {
      "CidrIp": "0.0.0.0/0",
      "Description": "Allow all outbound traffic by default",
      "IpProtocol": "-1"
     }
    ],
    "SecurityGroupIngress": [
     {
      "CidrIp": "10.0.0.0/8",
      "Description": "allow 443 from intelligent hub",
      "FromPort": 443,
      "IpProtocol": "tcp",
      "ToPort": 443
     },
     {
      "CidrIp": "10.206.0.0/20",
      "Description": "Allow 3389 From Shared Services Account Bastion",
      "FromPort": 3389,
      "IpProtocol": "tcp",
      "ToPort": 3389
     }
    ],
    "VpcId": "vpc-test"
   },
   "Metadata": {
    "aws:cdk:path": "sample-test--security-groups-sales/sales-web-sg/Resource"
   }
  },
  "saleswebsgfromsampletestsecuritygroupssalessalesmgmtsgE645B026443B86BCF95": {
   "Type": "AWS::EC2::SecurityGroupIngress",
   "Properties": {
    "IpProtocol": "tcp",
    "Description": "from sampletestsecuritygroupssalessalesmgmtsgE645B026:443",
    "FromPort": 443,
    "GroupId": {
     "Fn::GetAtt": [
      "saleswebsg",
      "GroupId"
     ]
    },
    "SourceSecurityGroupId": {
     "Fn::GetAtt": [
      "salesmgmtsg",
      "GroupId"
     ]
    },
    "ToPort": 443
   },
   "Metadata": {
    "aws:cdk:path": "sample-test--security-groups-sales/sales-web-sg/from sampletestsecuritygroupssalessalesmgmtsgE645B026:443"
   }
  },
  "salesappapssg": {
   "Type": "AWS::EC2::SecurityGroup",
   "Properties": {
    "GroupDescription": "app-aps-sg instance security group",
    "GroupName": "sales-app-aps-sg",
    "SecurityGroupEgress": [
     {
      "CidrIp": "0.0.0.0/0",
      "Description": "Allow all outbound traffic by default",
      "IpProtocol": "-1"
     }
    ],
    "SecurityGroupIngress": [
     {
      "CidrIp": "10.0.0.0/8",
      "Description": "allow 443 from intelligent hub",
      "FromPort": 443,
      "IpProtocol": "tcp",
      "ToPort": 443
     },
     {
      "CidrIp": "10.0.0.0/8",
      "Description": "allow 443 from intelligent hub",
      "FromPort": 9080,
      "IpProtocol": "tcp",
      "ToPort": 9080
     },
     {
      "CidrIp": "10.0.0.0/8",
      "Description": "allow 443 from intelligent hub",
      "FromPort": 9085,
      "IpProtocol": "tcp",
      "ToPort": 9085
     },
     {
      "CidrIp": "10.206.0.0/20",
      "Description": "Allow 3389 From Shared Services Account Bastion",
      "FromPort": 3389,
      "IpProtocol": "tcp",
      "ToPort": 3389
     }
    ],
    "VpcId": "vpc-test"
   },
   "Metadata": {
    "aws:cdk:path": "sample-test--security-groups-sales/sales-app-aps-sg/Resource"
   }
  },
  "salesappapssgfromsampletestsecuritygroupssalessaleswebsg91630DB1443B742531C": {
   "Type": "AWS::EC2::SecurityGroupIngress",
   "Properties": {
    "IpProtocol": "tcp",
    "Description": "from sampletestsecuritygroupssalessaleswebsg91630DB1:443",
    "FromPort": 443,
    "GroupId": {
     "Fn::GetAtt": [
      "salesappapssg",
      "GroupId"
     ]
    },
    "SourceSecurityGroupId": {
     "Fn::GetAtt": [
      "saleswebsg",
      "GroupId"
     ]
    },
    "ToPort": 443
   },
   "Metadata": {
    "aws:cdk:path": "sample-test--security-groups-sales/sales-app-aps-sg/from sampletestsecuritygroupssalessaleswebsg91630DB1:443"
   }
  },
  "salesappapssgfromsampletestsecuritygroupssalessaleswebsg91630DB19080D89CCCAF": {
   "Type": "AWS::EC2::SecurityGroupIngress",
   "Properties": {
    "IpProtocol": "tcp",
    "Description": "from sampletestsecuritygroupssalessaleswebsg91630DB1:9080",
    "FromPort": 9080,
    "GroupId": {
     "Fn::GetAtt": [
      "salesappapssg",
      "GroupId"
     ]
    },
    "SourceSecurityGroupId": {
     "Fn::GetAtt": [
      "saleswebsg",
      "GroupId"
     ]
    },
    "ToPort": 9080
   },
   "Metadata": {
    "aws:cdk:path": "sample-test--security-groups-sales/sales-app-aps-sg/from sampletestsecuritygroupssalessaleswebsg91630DB1:9080"
   }
  },
  "salesappapssgfromsampletestsecuritygroupssalessaleswebsg91630DB19085DE06A16B": {
   "Type": "AWS::EC2::SecurityGroupIngress",
   "Properties": {
    "IpProtocol": "tcp",
    "Description": "from sampletestsecuritygroupssalessaleswebsg91630DB1:9085",
    "FromPort": 9085,
    "GroupId": {
     "Fn::GetAtt": [
      "salesappapssg",
      "GroupId"
     ]
    },
    "SourceSecurityGroupId": {
     "Fn::GetAtt": [
      "saleswebsg",
      "GroupId"
     ]
    },
    "ToPort": 9085
   },
   "Metadata": {
    "aws:cdk:path": "sample-test--security-groups-sales/sales-app-aps-sg/from sampletestsecuritygroupssalessaleswebsg91630DB1:9085"
   }
  },
  "salesappapssgfromsampletestsecuritygroupssalessalesmgmtsgE645B026443A8FE7FBF": {
   "Type": "AWS::EC2::SecurityGroupIngress",
   "Properties": {
    "IpProtocol": "tcp",
    "Description": "from sampletestsecuritygroupssalessalesmgmtsgE645B026:443",
    "FromPort": 443,
    "GroupId": {
     "Fn::GetAtt": [
      "salesappapssg",
      "GroupId"
     ]
    },
    "SourceSecurityGroupId": {
     "Fn::GetAtt": [
      "salesmgmtsg",
      "GroupId"
     ]
    },
    "ToPort": 443
   },
   "Metadata": {
    "aws:cdk:path": "sample-test--security-groups-sales/sales-app-aps-sg/from sampletestsecuritygroupssalessalesmgmtsgE645B026:443"
   }
  },
  "salesmgmtsg": {
   "Type": "AWS::EC2::SecurityGroup",
   "Properties": {
    "GroupDescription": "mgmt security group",
    "GroupName": "sales-mgmt-sg",
    "SecurityGroupEgress": [
     {
      "CidrIp": "0.0.0.0/0",
      "Description": "Allow all outbound traffic by default",
      "IpProtocol": "-1"
     }
    ],
    "SecurityGroupIngress": [
     {
      "CidrIp": "10.0.0.0/8",
      "Description": "allow 443 from intelligent hub",
      "FromPort": 443,
      "IpProtocol": "tcp",
      "ToPort": 443
     },
     {
      "CidrIp": "10.206.0.0/20",
      "Description": "Allow 3389 From Shared Services Account Bastion",
      "FromPort": 3389,
      "IpProtocol": "tcp",
      "ToPort": 3389
     },
     {
      "CidrIp": "10.206.0.0/20",
      "Description": "Allow 3389 From Shared Services Account Bastion",
      "FromPort": 22,
      "IpProtocol": "tcp",
      "ToPort": 22
     },
     {
      "CidrIp": "10.156.102.128/26",
      "Description": "from 10.156.102.128/26:5985-5986",
      "FromPort": 5985,
      "IpProtocol": "tcp",
      "ToPort": 5986
     },
     {
      "CidrIp": "10.156.102.192/26",
      "Description": "from 10.156.102.192/26:5985-5986",
      "FromPort": 5985,
      "IpProtocol": "tcp",
      "ToPort": 5986
     },
     {
      "CidrIp": "10.156.103.0/26",
      "Description": "from 10.156.103.0/26:5985-5986",
      "FromPort": 5985,
      "IpProtocol": "tcp",
      "ToPort": 5986
     }
    ],
    "VpcId": "vpc-test"
   },
   "Metadata": {
    "aws:cdk:path": "sample-test--security-groups-sales/sales-mgmt-sg/Resource"
   }
  }
 }
}`

**Comment by abjoshi2785** [comment]
@corymhall Please find above the cft

**Comment by corymhall** [comment]
Can you also provide the CDK code that produces this?

**Comment by abjoshi2785** [comment]
@corymhall Please find below some of the functions that are used to create the cft attached above.

`security_group.add_ingress_rule(
                                    peer=allowed_group,
                                    connection=ec2.Port.tcp_range(tcp_start, tcp_end),
                                    description=tcp_range_description,
                                )

security_group.add_ingress_rule(
                                    peer=allowed_group,
                                    connection=ec2.Port.udp_range(udp_start, udp_end),
                                    description=udp_range_description,
                                )
                                
                                security_group.add_ingress_rule(
                                    peer=allowed_group, connection=ec2.Port.tcp(port)
                                )`

**Comment by peterwoodworth** [comment]
What exactly is going into drift here, by that I mean, what does the Cfn console say? I am unable to reproduce this with the snippets given here

**Comment by abjoshi2785** [comment]
Hi @peterwoodworth, the cft attached above will help you replicate the drift. After the cft deployment the inbound rules that are added by ref are moved inside the sg (the deploy works correctly) but the cft fails to understand that and shows the diff in whats deployed and whats in cft.

**Comment by abjoshi2785** [comment]
Attaching the sample code to replicate the issue

`from aws_cdk import (
    # Duration,
    Stack,
    aws_ec2 as ec2
    # aws_sqs as sqs,
)

from constructs import Construct

class SecurityGroupStack(Stack):

    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        vpc_id= "vpc-ddb153bb"

        vpc = ec2.Vpc.from_vpc_attributes(
            scope=self,
            id="DefaultVPC",
            vpc_id=vpc_id,
            availability_zones=["us-west-1a","us-west-1b"]
        )

        # Creating the security groups

        web_security_group = ec2.SecurityGroup(
            self,
            id="websg",
            vpc=vpc,
            security_group_name="web-sg",
            description="Web security group",
            allow_all_outbound=True,
        )

        app_security_group = ec2.SecurityGroup(
            self,
            id="appsg",
            vpc=vpc,
            security_group_name="app-sg",
            description="App security group",
            allow_all_outbound=True,
        )


        mgmt_security_group = ec2.SecurityGroup(
            self,
            id="mgmtsg",
            vpc=vpc,
            security_group_name="mgmt-sg",
            description="Mgmt security group",
            allow_all_outbound=True,
        )


        # Adding the ingress rules

        # Web
        web_security_group.add_ingress_rule(
            peer=ec2.Peer.ipv4("10.0.0.0/8"),
            connection=ec2.Port.tcp(443),
            description="Allow 443 from 10.0.0.0/8",
        )

        web_security_group.add_ingress_rule(
            peer=ec2.Peer.ipv4("10.206.0.0/20"),
            connection=ec2.Port.tcp(443),
            description="Allow 443 from 10.206.0.0/20",
        )

        web_security_group.add_ingress_rule(
            peer=mgmt_security_group,
            connection=ec2.Port.tcp(443),
            description="Allow 443 from Mgmt security group",
        )

        # App
        app_security_group.add_ingress_rule(
            peer=ec2.Peer.ipv4("10.0.0.0/8"),
            connection=ec2.Port.tcp(443),
            description="Allow 443 from 10.0.0.0/8",
        )

        app_security_group.add_ingress_rule(
            peer=ec2.Peer.ipv4("10.206.0.0/20"),
            connection=ec2.Port.tcp(443),
            description="Allow 443 from 10.206.0.0/20",
        )

        app_security_group.add_ingress_rule(
            peer=web_security_group,
            connection=ec2.Port.tcp(443),
            description="Allow 443 from Mgmt security group",
        )

        app_security_group.add_ingress_rule(
            peer=mgmt_security_group,
            connection=ec2.Port.tcp(443),
            description="Allow 443 from Mgmt security group",
        )

        # Mgmt
        mgmt_security_group.add_ingress_rule(
            peer=ec2.Peer.ipv4("10.0.0.0/8"),
            connection=ec2.Port.tcp(443),
            description="Allow 443 from 10.0.0.0/8",
        )

        mgmt_security_group.add_ingress_rule(
            peer=ec2.Peer.ipv4("10.206.0.0/20"),
            connection=ec2.Port.tcp(443),
            description="Allow 443 from 10.206.0.0/20",
        )

        mgmt_security_group.add_ingress_rule(
            peer=ec2.Peer.ipv4("10.156.102.128/26"),
            connection=ec2.Port.tcp(3389),
            description="Allow 3389 from 10.156.102.128/26",
        )

        mgmt_security_group.add_ingress_rule(
            peer=ec2.Peer.ipv4("10.156.102.192/26"),
            connection=ec2.Port.tcp(3389),
            description="Allow 3389 from 10.156.102.192/26",
        )


`

**Comment by abjoshi2785** [comment]
@peterwoodworth @corymhall Any updates?

**Comment by abjoshi2785** [comment]
@peterwoodworth @corymhall Any updates?

**Comment by corymhall** [comment]
@abjoshi2785 I copied the code you provided into a new project, deployed it, and then ran diff several times and I don't see any drift. Have you tried this on a new project with only this code?

**Comment by abjoshi2785** [comment]
<img width="1656" alt="Drift" src="https://user-images.githubusercontent.com/71033560/186251482-31a53d1f-39ec-4a72-a29a-944692a90028.png">
@corymhall Please find attached the drift details.

**Comment by corymhall** [comment]
@abjoshi2785 ah ok I assumed you were talking about `cdk diff` and not the `CloudFormation drift` feature. I was able to reproduce the _drift_ with the code you provided. It looks like this is an issue with CloudFormation drift since it is reporting a false positive.

Based on the [CFN docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-stack-drift.html?icmpid=docs_cfn_console#drift-considerations) this should be handled correctly, but seems like a false positive I would recommend following the instructions on submitting a false positive

_"If you encounter any false positive, send us your comments using the feedback link in the CloudFormation console, or reach out to us through the AWS forums at https://forums.aws.amazon.com/."_
