### ISSUE TITLE
(cdk-cli): (context says it requires --app but it doesn't)

### ISSUE THREAD

**Issue by codermpl** [aws/aws-cdk#21564]
### Describe the bug

The context sub cammand in cdk cli says it requests the --app parameter, but it doesn't.

Help Command:
`cdk context help`

Output:
```
cdk context

Manage cached context values

Options:
  -a, --app                REQUIRED: command-line for executing your app or a
                           cloud assembly directory (e.g. "node bin/my-app.js")
                                                                        [string]
```

Context Command:
`cdk context --json`

Output:
```
{
 "myKey": "MyValue"
}
```

### Expected Behavior

Either --app should be required or the help should say it's optional

### Current Behavior

--app is optional but the help says its required

### Reproduction Steps

cdk context --json

### CDK CLI Version

2.31.1

### Node.js Version

14

### OS

AL2

### Language

Typescript

### Language Version

typescript (4.0)

**Comment by peterwoodworth** [comment]
The `--app` parameter can also be filled in with `cdk.json`, which is likely what is happening by default if you are in a CDK app. If you run a CDK command outside of a CDK directory, it should throw an error about not having an app supplied.

However, for this specific command (and bootstrapping, maybe others as well), no app is actually required and you can successfully run this command outside of a CDK app directory. However, I'm not sure why you would do this, nor do I see why you would have a context file or `cdk.json` outside of a CDK app. Regardless, we can improve the documentation by modifying the message here https://github.com/aws/aws-cdk/blob/cf3bb6e9ced5e3d18e782e7144858078c70cdcf9/packages/aws-cdk/lib/cli.ts#L58
