### ISSUE TITLE
@aws-cdk/aws-lambda-nodejs: Extended config for TSC precompilation does not support Node.js style resolution

### ISSUE THREAD

**Issue by mikebroberts** [aws/aws-cdk#21567]
### Describe the bug

With `NodejsFunction` if `preCompilation: true` is set in `bundling`, and the relevant tsconfig file contains an `extends` property, then this doesn't work if the value of the `extends` property - i.e. the location of the extended configuration - is set to a module path (e.g. `"@tsconfig/node16/tsconfig.json"`)

Current workaround is to use a file system path in tsconfig (e.g. "./node_modules/@tsconfig/node16/tsconfig.json")

### Expected Behavior

If a module path is used then the pre-compile step should successfully load the extended configuration from node_modules

### Current Behavior

Error message: `Error: Cannot find module '/.../my-project-directory/@tsconfig/node16/tsconfig.json'

### Reproduction Steps

* Set `preCompilation: true` in `bundling` of `NodejsFunctionProps`
* Set this property in tsconfig.json: `"extends": "@tsconfig/node16/tsconfig.json"`
* Include this in devDependencies in package.json: `"@tsconfig/node16": "1.x",`

### Possible Solution

According the Typescript documentation for "extends" (https://www.typescriptlang.org/tsconfig#extends) (emphasis mine): 

> The value of extends is a string which contains a path to another configuration file to inherit from. **The path may use Node.js style resolution.**

The current behavior is sufficient when the path points directly to a file system path, but not if it's a module path.

I.e. a current workaround is to change `extends` to `"./node_modules/@tsconfig/node16/tsconfig.json"`

The problem is in the `extractTsConfig` function, here: https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/aws-lambda-nodejs/lib/util.ts#L205 . The function needs to handle the case that the path is either a file system path directly, or a location in `node_modules`.

### Additional Information/Context

The reason this came up is that I'd like to perform type checking of code before transpiling it. So I'm actually using preCompilation solely as type checking - not to actually generate any output (I'm setting `noEmit` to `true` in my tsconfig).

If there was an alternative to running type checking I wouldn't need this.

Further, this was discussed in the CDK Slack here - https://cdk-dev.slack.com/archives/C018XT6REKT/p1660243363352259 - and I'd like to acknowledge @elthrasher for finding the location of the bug and for their help!

An alternative workaround is to **not** perform type checking as part of NodejsFunction, and instead set a 'build' property at cdk configuration level that runs tsc.

### CDK CLI Version

2.37.1

### Node.js Version

16

### OS

Mac OS 12.5

### Language

Typescript

**Comment by corymhall** [comment]
@jogold @hassanazharkhan do you know the background on why we parse the tsconfig.json into CLI arguments instead of just pointing to the tsconfig.json?

**Comment by hassanazharkhan** [comment]
There are libraies that relies on TypeScript's [emitDecoratorMetadata](https://www.typescriptlang.org/tsconfig#emitDecoratorMetadata) setting. This does not work with `esbuild` because it requires a type system to function, and [replicating TypeScript's type system within esbuild is out of scope due to complexity](https://esbuild.github.io/content-types/#no-type-system). 

One workaround is to run tsc first to convert .ts files into .js files and then run esbuild on the resulting .js files, to run a tsc we need read users `tsconfig` settings that's why we are parsing tsconfig into CLI arguments.

You can find more info in [this](https://github.com/evanw/esbuild/issues/1597) issue

**Comment by corymhall** [comment]
@hassanazharkhan is there a reason we can't just do `tsc -p ./path/to/tsconfig.json`?

**Comment by hassanazharkhan** [comment]
@corymhall initially, we thought to do this but it's quite unexpected to identify where the resulting `.js` are in the project, so @jogold and I [decided](https://github.com/aws/aws-cdk/pull/16543#discussion_r718489772) to set `--rootDir ./ --outDir ./` so the resultoing `.js` will always endup next `.ts` files.

**Comment by mikebroberts** [comment]
To emphasize a point I made in the "additional context" section - I am **not** using tsc to output any js files, I'm only using it for type checking (i.e. "noEmit") . So in my particular case there wouldn't be any resulting js files to locate.

Maybe adding an extra option to NodejsFunction -- `typeCheckWithTSC` -- which when true does in fact just run `tsc --noEmit` with the same tsconfig would work better here?

**Comment by hassanazharkhan** [comment]
@mikebroberts Adding a separate option just for type checking would be good for `NodejsFunction`, and will potentially solve your issue as well, however the actual bug will exist while parsing CLI arguments.

@corymhall WDYT?

**Comment by mikebroberts** [comment]
Added a new workaround. I hadn't realized before that the cdk 'build' property will run for all synth-related activities, and so instead of using 'preCompilation' in NodejsFunction I can instead set a 'build' property that will run tsc before NodejsFunction's logic is called.

**Comment by tim-finnigan** [comment]
It looks like this issue overlaps with https://github.com/aws/aws-cdk/issues/21168, this comment may be helpful: https://github.com/aws/aws-cdk/issues/21168#issuecomment-1319856712. Please let us know if so, or if there any distinctions you want to make between these issues.
