### ISSUE TITLE
bootstrap: KMS key tags cannot be updated.

### ISSUE THREAD

**Issue by adrianmace** [aws/aws-cdk#21571]
### Describe the bug

`kms:UntagResource` and `kms:TagResource` are missing from the key policy, which means I cannot use an IAM role to update the bootstrap stack if I have stack tags configured.

https://github.com/aws/aws-cdk/blob/3f5d6d89a63f9904f23df0cfc5733d338fea8879/packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml#L95-L112

### Expected Behavior

Updating the bootstrap stack using an IAM role that has sufficient permissions proceeds without issue.

### Current Behavior

Cloudformation stack events records the following:
```
The following resource(s) failed to update: [FileAssetsBucketEncryptionKey].
Resource handler returned message: "Access denied for operation 'UntagResource'." 
```

### Reproduction Steps

1. Deploy an old version of the CDK Bootstrap template with stack tag `aws-cdk:version` and random value.
2. Create an IAM role that has permissions to do everything (`kms:*`).
3. Deploy a new version of the CDK bootstrap template with the same stack tag, but a new value.
4. Observe it fail to update.

### Possible Solution

Grant `kms:TagResource` and `kms:UntagResource` on the key policy.

### CDK CLI Version

v2.30.0

### Node.js Version

N/A

### OS

N/A

### Language

Python

### Language Version

3.10.6

**Comment by peterwoodworth** [comment]
Hey @adrianmace, thanks for reporting this.

We have another issue that's tracking this #21281, let's take discussion to that thread 🙂
