### ISSUE TITLE
AutoScalingGroupProps.AssociatePublicIpAddress has no effect

### ISSUE THREAD

**Issue by icelava** [aws/aws-cdk#21576]
### Describe the bug

https://docs.aws.amazon.com/cdk/api/v2/dotnet/api/Amazon.CDK.AWS.AutoScaling.AutoScalingGroupProps.html#Amazon_CDK_AWS_AutoScaling_AutoScalingGroupProps_AssociatePublicIpAddress

Setting property to false still results in instances launched with public IP address.

### Expected Behavior

Launched instances should not assign public IP address.

### Current Behavior

Launched instances get public IP address.

### Reproduction Steps

```ts
this.asg = new AutoScalingGroup(this, this.asgName, new AutoScalingGroupProps
{
	AutoScalingGroupName = this.asgName,
	LaunchTemplate = lt,
	Vpc = this._props.Vpc,
	VpcSubnets = this._props.AppSubnets,
	AssociatePublicIpAddress = false,
	MinCapacity = this._props.MinCapacity,
	MaxCapacity = this._props.MaxCapacity,
	DesiredCapacity = this._props.DesiredCapacity
});
```

### Possible Solution

That property should cause a change in the resultant CloudFormation template.

### CDK CLI Version

2.35.0

### Framework Version

.NET Core 3.1

### Node.js Version

NA

### OS

Windows

### Language

.NET

### Language Version

C# 8

**Comment by peterwoodworth** [comment]
We're passing this prop directly to the LaunchTemplate resource - You can see a more full description of the underlying behavior of this prop [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-autoscaling-launchconfiguration.html#cfn-autoscaling-launchconfiguration-associatepublicipaddress)

> That property should cause a change in the resultant CloudFormation template.

Does this mean that if you alternate this value between true and false that you aren't seeing a difference in the resulting template?

**Comment by icelava** [comment]
Yeap it was originally not set, so defaulted to true. When I set it to false, no change in the resulting CloudFormation template.

**Comment by peterwoodworth** [comment]
This property isn't supposed to be used when passing in your own launch template to a new ASG. We are supposed to throw an error here, but there's a bug in the logic which prevents that. I've made a PR which updates the documentation for all props which can't be used when specifying a launch template, as well as ensures an error gets thrown when this prop is set to false

**Comment by icelava** [comment]
Hmmm but the LaunchTemplate does not feature such a property?
