### ISSUE TITLE
(bootstrap): Bootstrapping a C# language fails when only Arm64 SDK is installed in M1 Max environment

### ISSUE THREAD

**Issue by Tak1wa** [aws/aws-cdk#21589]
### Describe the bug

Bootstrapping a C# language project with only Arm64 SDK installed in the M1 Max environment fails.
Installing the x64 SDK in addition to Arm64 should now succeed.

### Expected Behavior

works without x64

### Current Behavior

Requires additional installation of x64 .NET SDK

### Reproduction Steps

1. Install .NET SDK (Arm64) only. do not install x64
2. cdk init
3. cdk bootstrap

### Possible Solution

- change to work on x64
- Add necessary steps to documentation

### CDK CLI Version

2.37.1

### Node.js Version

v18.0.0

### OS

macOS Monterey Ver 12.5 (Apple M1 Max)

### Language

.NET

**Comment by peterwoodworth** [comment]
@Jerry-AWS should this be added to the devguide [here](https://docs.aws.amazon.com/cdk/v2/guide/work-with-cdk-csharp.html)?

**Comment by tim-finnigan** [comment]
@peterwoodworth and @Tak1wa is this a confirmed issue? I haven't seen any other reports related to this. I'm not sure if a dev guide update is needed.

**Comment by atrakic** [comment]
@Tak1wa thx. It took me forever to figure this one out, so I needed to install x86 version as well. 
Can someone pls take a look into this?

My setup:
```
$ dotnet --list-sdks
6.0.405 [/usr/local/share/dotnet/sdk]
7.0.102 [/usr/local/share/dotnet/sdk]
```  

Than I run:
```
$ dotnet new globaljson --sdk-version 6.0.405 --force
````
