### ISSUE TITLE
(cli): add `cdk watch --concurrency N`

### ISSUE THREAD

**Issue by misterjoshua** [aws/aws-cdk#21597]
### Describe the feature

I'd like the new `--concurrency` option from #20345 to support `cdk watch` mode.

### Use Case

In watch mode, I'd like my multi-stack apps to deploy stacks concurrently.

### Proposed Solution

I have opened #21598.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

N/A

### Environment details (OS name and version, etc.)

N/A

**Comment by peterwoodworth** [comment]
Thanks for the PR submission, we'll try to give a review for it soon 🙂
