### ISSUE TITLE
need support for aws blockchain

### ISSUE THREAD

**Issue by johndavis15** [aws/aws-cdk#2159]
aws blockchain - hyperledger fabric, we'd like to do standup using cloudformation via cdk

**Comment by sam-goodwin** [comment]
aws blockchain is still in preview and it doesn't appear to have CFN support yet.

**Comment by sam-goodwin** [comment]
You could develop a custom resource to patch the gap in the meantime. See https://github.com/awslabs/aws-cdk/tree/master/packages/%40aws-cdk/aws-cloudformation

**Comment by SomayaB** [comment]
Hi @johndavis15, I apologize for the late reply. Is [this](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-managedblockchain-readme.html) what you were looking for?
Will close this issue if no response.

**Comment by SomayaB** [comment]
Closing this issue since there hasn't been any activity on it in a while. Feel free to reopen.
