### ISSUE TITLE
aws-eks: Windows EKS support

### ISSUE THREAD

**Issue by olga-mir** [aws/aws-cdk#21600]
### Describe the feature

I would like to be able to provision [Windows EKS clusters](https://docs.aws.amazon.com/eks/latest/userguide/windows-support.html) in AWS-CDK. There is no Windows AMI Type available for node groups: https://github.com/aws/aws-cdk/blob/cea1039e3664fdfa89c6f00cdaeb1a0185a12678/packages/%40aws-cdk/aws-eks/lib/managed-nodegroup.ts#L19-L45

### Use Case

Deploy Windows containers on EKS. 

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

v2.37.1

### Environment details (OS name and version, etc.)

21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64

**Comment by olga-mir** [comment]
I should re-phrase my question, according to the EKS documentation Windows nodegroups must be self-managed:

`You can't deploy Windows managed nodes. You can only create self-managed Windows nodes` https://docs.aws.amazon.com/eks/latest/userguide/windows-support.html

`You can't specify a Windows AMI ID because Windows can't be used in managed node groups.` https://docs.aws.amazon.com/eks/latest/userguide/launch-templates.html

Is there a way to create self-managed nodegroups then? I am new to AWS CDK, but I can see only managed nodegroups.

**Comment by olga-mir** [comment]
It's probably supported after all, self-managed node groups are known as `AutoScalingGroupCapacity` in the aws-cdk world: https://github.com/aws/aws-cdk/tree/main/packages/%40aws-cdk/aws-eks#self-managed-nodes

**Comment by supera74** [comment]
> supported

sorry for opening this again. Have you be able to implement self-managed Windows node group?

**Comment by supera74** [comment]
solved it in my way. If someone wants some inspiration
https://gist.github.com/supera74/ec6156992d234d8f2cb334e5b2b61420
