### ISSUE TITLE
(CDK): (Approach Refinement)

### ISSUE THREAD

**Issue by resistdesign** [aws/aws-cdk#21614]
### Describe the feature

Having challenges with the approach.

### Use Case

Creating any stack.

### Proposed Solution

Support:

1. Documentation links in docs.
2. Allow configuration of any properties in a resource.
3. Typed resources based on selected Resource Type value.
4. Include a modular system for creating packs and applying patches.
5. Supply premade packs for common combinations of stack resources.
6. Include a lightweight CLI that converts TypeScript to a standard CloudFormation YAML Template for easy and standardized CI.
7. Supply easy methods for chaining packs and patches to quickly create a comprehensive stack.
8. Supply easy methods and utils for creating stack Parameters in Parameter Groups with a trivially assigned Group property.

Like this: https://github.com/resistdesign/aws-cf-builder/blob/main/workspaces/example/src/iac.ts

### Acknowledgements

- [X] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### CDK version used

All

### Environment details (OS name and version, etc.)

N/A

**Comment by peterwoodworth** [comment]
Your package looks really cool! However, I'm not sure what exactly you're requesting of us. Could you clarify what exactly this issue is about?

**Comment by resistdesign** [comment]
@peterwoodworth Thank you ☺️
I'm suggesting that this package should move in that direction. I'm happy to maintain my project but it could just as easily be this one that supports all of those types of features. At the very least some inspiration could be pulled from it ☺️

**Comment by peterwoodworth** [comment]
I think there are multiple feature requests in here. Some of the things you listed I believe we already support - if there are any specific parts of this that you think should be part of CDK, I would open a feature request for each individual thing you want to be improved/reworked/added. There's a lot to keep track of here, and I think each feature is worthy of a full length description and description of possible solution within our existing codebase.
