### ISSUE TITLE
custom-resources: Add endpoint override to AWS custom resource

### ISSUE THREAD

**Issue by jonnekaunisto** [aws/aws-cdk#21612]
### Describe the feature

Add the ability to override the endpoint in the AWS custom resource: https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_custom-resources.AwsCustomResource.html

### Use Case

Our team has to create resources in the gamma stages of some services. This could be done with the AWS custom resource if the endpoint can be overriden

### Proposed Solution

Could be solved by adding a prop for endpoint override and by using the value here: https://github.com/aws/aws-cdk/blob/v1.168.0/packages/%40aws-cdk/custom-resources/lib/aws-custom-resource/runtime/index.ts#L183

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

N/A

### Environment details (OS name and version, etc.)

N/A

**Comment by rix0rrr** [comment]
This feature is useful to you, and probably other Amazonians, but not to most CDK users.

At this point, you are better off writing your own custom resource.
