### ISSUE TITLE
Api Gatway: Adding method to existing resource issue

### ISSUE THREAD

**Issue by jsonpj3wt** [aws/aws-cdk#21623]
### Describe the bug

When adding a method to an existing resource, the lambda ArnLike path is incomplete.
I understand the idea behind creating another stack, but one of these approaches should work as expected.

### Expected Behavior

The lambda ArnLike path should be the full path: `.../v1/address`.

### Current Behavior

The lambda ArnLike path does not contain the full path: `.../address`.

### Reproduction Steps

Here is an example that "works" however, the lambda gets the wrong target path:

```typescript

const gtwy = apigateway.RestApi.fromRestApiAttributes(this, 'apiAddressGtwy', {
    restApiId: process.env.CDK_API_GATEWAY_REST_API_ID,
    rootResourceId: process.env.CDK_API_V1_RESOURCE_ID,
});
const addressResource = new apigateway.Resource(this, 'addressResource', {
    parent: gtwy.root,
    pathPart: 'address',
});

const gtwyAddressMethod = addressResource?.addMethod(
    'POST',
    new apigateway.LambdaIntegration(lambdaFunction, { proxy: true }),
    {
        authorizer: {
            authorizerId: process.env.CDK_API_GATEWAY_AUTHORIZER_ID || '',
            authorizationType: apigateway.AuthorizationType.CUSTOM,
        },
        apiKeyRequired: false,
    },
);
```
This approach does create the proper methods in the right spot. However, the lambda target ArnLike is `.../address` instead of the expected full path of `.../v1/address`.

Let's say I start at the root (/):

```typescript

const gtwy = apigateway.RestApi.fromRestApiAttributes(this, 'apiAddressGtwy', {
    restApiId: process.env.CDK_API_GATEWAY_REST_API_ID,
    rootResourceId: process.env.CDK_API_ROOT_RESOURCE_ID,
});
const addressResource = new apigateway.Resource(this, 'addressResource', {
    parent: gtwy.root.getResource('/v1'), // Returns undefined
    pathPart: 'address',
});

const gtwyAddressMethod = addressResource?.addMethod(
    'POST',
    new apigateway.LambdaIntegration(lambdaFunction, { proxy: true }),
    {
        authorizer: {
            authorizerId: process.env.CDK_API_GATEWAY_AUTHORIZER_ID || '',
            authorizationType: apigateway.AuthorizationType.CUSTOM,
        },
        apiKeyRequired: false,
    },
);
```
Will fail because the `getResource('/v1')` is undefined.  If I change it to have `gtwy.root.resourceForPath('/v1')`, the proper target path for the lambda is set but will not complete with the following error: `Another resource with the same parent already has this name`.

### CDK CLI Version

2.33.0

### Node.js Version

18.6.0

### OS

MacOS M1

### Language

Typescript

### Language Version

3.9.7

### Other information

Reference to similar issue: https://github.com/aws/aws-cdk/issues/12755

**Comment by jsonpj3wt** [comment]
After trying a few different variations, the following does work:

```typescript
const gtwy = apigateway.RestApi.fromRestApiAttributes(this, 'apiScreenGtwy', {
    restApiId: process.env.CDK_API_GATEWAY_REST_API_ID || '',
    rootResourceId: process.env.CDK_API_V1_RESOURCE_ID || '',
});
const screenResource = apigateway.Resource.fromResourceAttributes(this, 'ScreenResource', {
    restApi: gtwy,
    resourceId: process.env.CDK_API_SCREEN_RESOURCE_ID || '',
    path: '/screen',
});

const addressResource = new apigateway.Resource(this, 'addressResource', {
    parent: screenResource,
    pathPart: 'address',
});

 const gtwyAddressMethod = new apigateway.Method(this, 'ApiGWAddressPostMethodArn', {...});
```

**Comment by stevehaneytrailblazer** [comment]
@jsonpj3wt thanks for sharing that example.  I'm about 4 days new into CDK and was going nuts with this issue.  Did you find that when you got it working that the stage wasn't reflecting the new resources?  Thats the last piece of the puzzle I'm trying to figure out.  I see the resources updated but not my stage.  I am adding a new deployment and see that in Deployment history so I'm not sure what the issue might be.

**Comment by stevehaneytrailblazer** [comment]
@jsonpj3wt thanks for the fast reply.  Yeah I'm not sure what I'm doing wrong but I have this as my last line of my stack (after adding the api gw methods).  Still seems to just show the orig shell resources.

The Api is created in Terraform and I create the stage in a base stack, separate from the stack adding a set of service lambda endpoints.  I have caching enabled on the Stage.  Its quite puzzling.

```
const deployment = new Deployment(this, 'rest-api-deployment', { api: api });
        deployment.addToLogicalId(new Date().toISOString());
        (deployment as any).resource.stageName = props.stage;
```
