### ISSUE TITLE
GitHub Workflow Runner Image

### ISSUE THREAD

**Issue by Simonl9l** [aws/aws-cdk#21629]
### Describe the feature

It seem that currently the maintainers of the GitHub Workflow runner do not see the value in preinstalling the CDK CLI along side all the other but in tools , including the core AWS CLI.

It seem that ti might be quite valuable to many than having to install the cdk cli each time.

please see the issue - https://github.com/actions/runner-images/issues/6088 

### Use Case

It's frustrating when building GitHub workflows to have to add steps to install the CDK Cli each time.

### Proposed Solution

collaborate with the GitHub runner maintainer to include the CDK CLI in this [list](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu1804-Readme.md) along side the other AWS CLI's Including:

- AWS CLI 2.7.20
- AWS CLI Session manager plugin 1.2.339.0
- AWS SAM CLI 1.53.0 

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.33.0

### Environment details (OS name and version, etc.)

All

**Comment by hoegertn** [comment]
Can you elaborate on why you want the CDK CLI to be installed globally? 

I prefer to use the CLI that comes with my node_modules as it always has the correct version and I do not rely on version matches from the image.

**Comment by peterwoodworth** [comment]
Based on the response from the maintainer on the issue you posted in their repo I'm doubtful there's anything we could do on our end to add the CDK CLI to Github Workflow runner images. I'm not exactly sure how we would start a collaboration on this front

Additionally, as @hoegertn mentioned, using `npx` when running cdk commands helps to avoid version mismatches

**Comment by Simonl9l** [comment]
@hoegertn 
1) we're using C# as our CDK language, so don't have any "node_modules", but on the basis that environment has node/npx installed that option may be viable.
2) we're also using [Nuke](https://nuke.build/docs/introduction/) as our build orchestrator - that generate the GitHub workflow Yaml, with in the we can reference customer tools (via path or specific location) but the need to pre-exist. 

I'm curious as to why for example the AWS SAM CLI is part of the default image, but CDK has pushback from the GitHub runner maintainers. A nudge from yourselves might help - if you see the value?

@peterwoodworth it seems they do allow pull requests into the runner image projects.

**Comment by peterwoodworth** [comment]
I appreciate this feature request, however there's nothing we can do to act on this so it should be closed.
