### ISSUE TITLE
@aws-cdk/aws-apigatewayv2-alpha: Property 'node' does not exist on type 'HttpRoute'.

### ISSUE THREAD

**Issue by gimyboya** [aws/aws-cdk#21651]
### Describe the bug

With CDK 1 I had the following snippet of code in my stack
```ts
private static authorizeRoute(route: HttpRoute, authorizer: CfnAuthorizer) {
    const cfnRootRoute = route.node.defaultChild as CfnRoute;
    cfnRootRoute.authorizationType = 'CUSTOM';
    cfnRootRoute.authorizerId = authorizer.ref;
  }
```
But when I tried to upgrade to CDK 2 I started getting this error `Property 'node' does not exist on type 'HttpRoute'.`

Note that `HttpRoute` is imported from `@aws-cdk/aws-apigatewayv2-alpha`

### Expected Behavior

the property `node` object should be present in `HttpRoute`

### Current Behavior

Property 'node' does not exist on type 'HttpRoute'.

### Reproduction Steps

```ts
const api = new HttpApi(this, 'API', {
      createDefaultStage: true,
      corsPreflight: {
        allowCredentials: false,
        allowHeaders: ['Authorization'],
        allowMethods: [
          CorsHttpMethod.GET,
          CorsHttpMethod.OPTIONS,
          CorsHttpMethod.POST,
        ],
        allowOrigins: ['*'],
        maxAge: Duration.days(10),
      },
    });
   
const authRoutes: HttpRoute[] = [];

authRoutes.push(
      ...api.addRoutes({
        path: '/context',
        methods: [HttpMethod.GET, HttpMethod.POST],
        integration: new HttpLambdaIntegration(
          'ContextIntegration',
          this.apiHandler
        ),
      })
    );
 
 authRoutes.forEach((route) =>
      console.log(route.node) // <----- the property `node` object should be present in `HttpRoute`
    );
``` 

### CDK CLI Version

2.23.0

### Node.js Version

14.19.0

### OS

Mac

### Language

Typescript

### Language Version

typescript 4.7.3

**Comment by gimyboya** [comment]
I can see that in the reference docs the `node` property should be present in the `HttpRoute` construct 
https://docs.aws.amazon.com/cdk/api/v2/docs/@aws-cdk_aws-apigatewayv2-alpha.HttpRoute.html#nodespan-classapi-icon-api-icon-experimental-titlethis-api-element-is-experimental-it-may-change-without-noticespan

**Comment by tcutts** [comment]
I've just tried to reproduce this with the current CDK (2.38.0) and I cannot.  The following cdk stack, based on yours, synthesizes fine and logs the structures to the console:

```ts
import * as cdk from 'aws-cdk-lib';
import * as apigw from '@aws-cdk/aws-apigatewayv2-alpha';
import * as apiint from '@aws-cdk/aws-apigatewayv2-integrations-alpha';
import * as lambda from 'aws-cdk-lib/aws-lambda-nodejs';
import { Construct } from 'constructs';

export class GwprobsStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const api = new apigw.HttpApi(this, 'API', {
      createDefaultStage: true,
      corsPreflight: {
        allowCredentials: false,
        allowHeaders: ['Authorization'],
        allowMethods: [
          apigw.CorsHttpMethod.GET,
          apigw.CorsHttpMethod.OPTIONS,
          apigw.CorsHttpMethod.POST,
        ],
        allowOrigins: ['*'],
        maxAge: cdk.Duration.days(10),
      },
    });
   
    const authRoutes: apigw.HttpRoute[] = [];

    const func = new lambda.NodejsFunction(this, 'ContextHandler');

    authRoutes.push(
      ...api.addRoutes({
        path: '/context',
        methods: [apigw.HttpMethod.GET, apigw.HttpMethod.POST],
        integration: new apiint.HttpLambdaIntegration(
          'ContextIntegration',
          func
        ),
      })
    );
 
 authRoutes.forEach((route) =>
      console.log(route.node) // <----- the property `node` object should be present in `HttpRoute`
    );
  }
}
```

**Comment by gimyboya** [comment]
Thank you for getting back to me @tcutts, so I have tried with `2.28.0` and i am still facing the same problem. here are things I tried:
- Uninstalled all old CDK 1 deps
- Deleted `node_modules` folder
- Re-Installed all deps
- Restarted TS server in VsCode
- Refreshed the window in VsCode
- Finally restarted VsCode altogether

I am still getting the same error

**Comment by peterwoodworth** [comment]
@gimyboya have you made sure that the aws-cdk-lib version and the alpha package versions are all the same version?

**Comment by gimyboya** [comment]
@peterwoodworth yes, here is what i have in my `package.json`:

```json
"aws-cdk-lib": "2.38.0",
"@aws-cdk/aws-apigatewayv2-alpha": "2.38.0-alpha.0",
"@aws-cdk/aws-apigatewayv2-integrations-alpha": "2.38.0-alpha.0",
```

**Comment by peterwoodworth** [comment]
I see you've said you deleted the node_modules folder, but have you also deleted `package-lock` and the cdk.out directory before reinstalling?

**Comment by gimyboya** [comment]
@peterwoodworth Yes, I have gone and done that as well. same problem I. At this point, I am not sure what else can be done.

**Comment by gimyboya** [comment]
Solved this by installing the [`constructs`](https://www.npmjs.com/package/constructs) dependency. Not sure if this was mentioned anywhere in the Docs/Refs but I discovered it my chance when I was diving deep into the code.
