### ISSUE TITLE
CDKv2 Python IDatabaseInstance: apply_removal_policy doesn't work

### ISSUE THREAD

**Issue by abhangu-signet** [aws/aws-cdk#21659]
### Describe the bug

I am using CDKv2 / Python.

My relevant CDK code:

I used aws_rds.DatabaseInstance.from_database_instance_attribute to get the IDatabaseInstance object it returns.

I then attempting to use IDatabaseInstance.apply_removal_policy(RemovalPolicy.RETAIN) to set a removal policy as per:
https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_rds/IDatabaseInstance.html#aws_cdk.aws_rds.IDatabaseInstance

The error:

jsii.errors.JSIIError: Cannot apply RemovalPolicy: no child or not a CfnResource. Apply the removal policy on the CfnResource directly.

### Expected Behavior

I expected to be able to use apply_removal_policy on the IDatabaseInstance object as per the documentation.

### Current Behavior

The deployment errors out and fails.

### Reproduction Steps

database_instance = rds.DatabaseInstance.from_database_instance_attributes(self,
                                                                         "instance",
                                                                         instance_endpoint_address = rds_endpoint,
                                                                         instance_identifier = rdsCluster.instance_identifiers[1],
                                                                         security_groups = [rds_sg],
                                                                         port = rds_port,
                                                                         )
database_instance.apply_removal_policy(RemovalPolicy.RETAIN)

### Possible Solution

Correct documentation 

### CDK CLI Version

2.27.0 (build 8e89048)

### Node.js Version

n/a

### OS

win10

### Language

Python

**Comment by peterwoodworth** [comment]
You can only modify the removal policy of resources which are created within your stack. Since you're importing this resource, [you cannot modify it in any way](https://docs.aws.amazon.com/cdk/v2/guide/resources.html#resources_importing). You will need to apply the removal policy within the stack which creates this resource

**Comment by peterwoodworth** [comment]
Let me know if you have any additional concerns
