### ISSUE TITLE
[APIGateway]: stage resource support additional custom access log settings

### ISSUE THREAD

**Issue by sparkyfen** [aws/aws-cdk#21650]
### Describe the feature

This is a feature request for additional custom access log settings.
Cloud Formation is supported custom access log settings for api gateway stage. But High level construct is not implemented for some of the context fields since it was originally implemented.

Docs: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apigateway-stage-accesslogsetting.html

An example of one is `$context.integrationErrorMessage` but there is no method for it.

### Use Case

```
new apigateway.RestApi(this, 'books', {
  deployOptions: {
        accessLogDestination: new apigateway.LogGroupLogDestination(logGroup),
        accessLogFormat: apigateway.AccessLogFormat.custom(JSON.stringify({
          requestId: apigateway.AccessLogField.contextRequestId(),
          caller: apigateway.AccessLogField.contextIdentityCaller(),
          callerAccountId: apigateway.AccessLogField.contextAccountId(),
          user: apigateway.AccessLogField.contextIdentityUser(),
          requestTime: apigateway.AccessLogField.contextRequestTime(),
          httpMethod: apigateway.AccessLogField.contextHttpMethod(),
          resourcePath: apigateway.AccessLogField.contextResourcePath(),
          status: apigateway.AccessLogField.contextStatus(),
          protocol: apigateway.AccessLogField.contextProtocol(),
          responseLength: apigateway.AccessLogField.contextResponseLength(),
          message: apigateway.AccessLogField.contextErrorMessage(),
          validationError: apigateway.AccessLogField.contextErrorValidationErrorString(),
          // Additional fields here.
        })),
      }
});
```

### Proposed Solution

Add missing context fields.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.34.2 (build 7abcbc6)

### Environment details (OS name and version, etc.)

Mac OSX 12.3.1

**Comment by peterwoodworth** [comment]
Thanks for submitting this request, we accept contributions! Check out our [contributing guide](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) if you're interested - there's a low chance the team will be able to address this soon but we'd be happy to review a PR 🙂

You can modify the template [with escape hatches](https://docs.aws.amazon.com/cdk/v2/guide/cfn_layer.html) to pretty easily make use of any properties not directly supported by our abstractions before we implement this feature
