### ISSUE TITLE
s3: autoDeleteObjects fails on deploy with "NoSuchKey" error

### ISSUE THREAD

**Issue by suttonsp0** [aws/aws-cdk#21662]
### Describe the bug

When I deploy a bucket with these properties:
```
this.s3LoggingBucket = new Bucket(this, 'LogBucket', {
      accessControl: BucketAccessControl.LOG_DELIVERY_WRITE,
      blockPublicAccess: BlockPublicAccess.BLOCK_ALL,
      encryption: BucketEncryption.S3_MANAGED,
      removalPolicy: props.retainBucket ? RemovalPolicy.RETAIN : RemovalPolicy.DESTROY,
      autoDeleteObjects: props.retainBucket ? false : true
    });
```
I get this error on CloudFormation:
```
Resource handler returned message: "Error occurred while GetObject. S3 Error Code: NoSuchKey. S3 Error Message: 
The specified key does not exist. (Service: Lambda, Status Code: 400, Request ID: 56fa2b2d-6744-4ad4-83c2-6925555bca43)"
 (RequestToken: db358bda-6dde-d5b2-01a6-99af8a104ff5, HandlerErrorCode: InvalidRequest)
```
Which happens on a resource named: `CustomS3AutoDeleteObjectsCustomResourceProviderHandler9D90184F`

The property `retainBucket` is set to False.

### Expected Behavior

I expect it to deploy the stack successfully. I haven't been able to test that it will tear down the bucket successfully because it won't deploy.

### Current Behavior

I get the error described above

### Reproduction Steps

If you create a stack with the bucket code I have above, using params with ternary operators, you should be able to reproduce the same problem.

### Possible Solution

For some reason, the lambda created by the autoDeleteObjects param is querying the bucket before it's even created. 

### CDK CLI Version

2.30.0

### Node.js Version

14

### OS

Linux

### Language

Typescript

**Comment by peterwoodworth** [comment]
I'm not able to reproduce this on a new stack @suttonsp0 - is there any other context that might be helpful to know?

**Comment by mttwise** [comment]
@peterwoodworth 
I am having a similar issue to this.  

![image](https://user-images.githubusercontent.com/24458226/194103856-495e9a48-e0d5-406a-b616-a9eb08aba8c1.png)
<img width="1087" alt="image" src="https://user-images.githubusercontent.com/24458226/194103887-16a9125d-294d-4b5c-bda2-285259da52af.png">
