### ISSUE TITLE
install.sh does not fulfill all pre-requisits

### ISSUE THREAD

**Issue by evildani** [aws/aws-cdk#2166]
In order to build the source, the following procedure is supposed to be followed:
```
./install.sh
./build.sh
./pack.sh
```

Where install.sh is supposed to download and install all dependancies, at least in my case wheel was not installed by install.sh, so pack failed.
`pip install wheel` (or pip3) resolved the issue, so I wonder if my understanding on what install.sh does is incorrect, or its missing something?

**Comment by sam-goodwin** [comment]
I've also ran into this issue, except with other dependencies such as sphinx. I believe `./install.sh` is primarily used to install and link the node modules (`lerna bootstrap`), so `./build.sh` will work, but `./pack.sh` will fail.

It should install everything required to build and pack the repository. .

**Comment by sam-goodwin** [comment]
According to the [CONTRIBUTING guide](https://github.com/awslabs/aws-cdk/blob/master/CONTRIBUTING.md):

> install.sh: installs all external dependencies and symlinks internal dependencies (using lerna link).

**Comment by SomayaB** [comment]
Hi, I apologize for the late reply. Is this still an issue? If so, filling out our new issue template would be of great help in order for us to understand your concerns better.

**Comment by SomayaB** [comment]
```md
<!-- NOTE:📕 If issue regarding developer guide, please create issue [here](https://github.com/awsdocs/aws-cdk-guide/issues) -->

## :bug: Bug Report

### What is the problem?
<!--
Describe in as much detail as possible the problem that you have identified.
Please identify clearly what construct the problem relates to, or indicate
what part of the core cdk codebase is causing problems.
-->

### Reproduction Steps
<!--
Whenever possible, add reference to the minimal reproduction of the issue, as
this will greatly help with identifying the root cause of the problem, and
ensuring a candidate fix is working.

If your minimal reprodiction is large, you may provide references to a [gist][1]
or any other publicly viewable location.
-->

### Verbose Log
<!--
If the output is very large, you may store it in a [gist][1]. In any case,
please review the contents of the log you are about to submit and edit any
confidential information out.

[1]: https://gist.github.com
-->

### Environment

  - **CDK CLI Version:** <!-- Output of `cdk version` -->
  - **Module Version:** <!-- Version of the module in question -->
  - **OS:** <!-- [all | Windows 10 | OSX Mojave | Ubuntu | etc... ] -->
  - **Language:** <!-- [all | TypeScript | Java | Python ] etc... ] -->


### Other information
<!-- e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc -->
```
