### ISSUE TITLE
cdk-lib: cloudformation output contains duplicate identifiers for a stack with different parameters supplied

### ISSUE THREAD

**Issue by strachg** [aws/aws-cdk#21672]
### Describe the bug

When using a stack with parametrized values, the cloud-formation output looks to contain non-unique identifiers.

This seems to have caused a circumstance in EKS where K8s namespace with identical CDK identifiers and "aws.cdk.eks/prune-..." label get removed from the cluster during seemingly un-relate operations.

In one case a service account was created via "this.cluster.addServiceAccount" added a service account and removed another namespace that wasn't mentioned in the CDK at all

### Expected Behavior

cloud-formation output from CDK would receive unique CDK identifiers and k8s object "aws.cdk.eks/prune-..." labels when the content isn't identical to ensure cloud-formation didn't touch things it isn't supposed to.

### Current Behavior

cloud-formation output from CDK receive identical CDK identifiers and k8s object "aws.cdk.eks/prune-..." labels when the content isn't identical causing cloud-formation to touch things it isn't supposed to, intermittently.

### Reproduction Steps

Because this issue is due to interaction with an entire EKS cluster it would be very hard to make a quick sample to reproduce the problem we are seeing.

### Possible Solution

Write CDK code in a way that changes the CDK identifier enough between stack iteration to force the change.

### CDK CLI Version

2.33.0 (build 859272d)

### Node.js Version

v18.6.0

### OS

21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000 arm64

### Language

Typescript

**Comment by peterwoodworth** [comment]
I don't understand what the issue is exactly here, could you please share reproduction steps and show an example of what exactly you are encountering?
