### ISSUE TITLE
(core): CDK creates unsupported list outputs from cross-stack references

### ISSUE THREAD

**Issue by gshpychka** [aws/aws-cdk#21682]
### Describe the bug

When doing cross-stack references that point to a list value, CDK creates a CfnOutput with the list as its value. Cloudformation does not support outputting list values - it only supports strings. So this fails either during synth (if you explicitly pass a list), or during template validation (if you do a `cdk.Fn.select` and pass that to another stack).

### Expected Behavior

Cross-stack references with list values work properly

### Current Behavior

Cross-stack references with list values generate a synth-time error when passed explicitly:
`jsii.errors.JSIIError: Resolution error: Resolution error: Found an encoded list token string in a scalar string context. Use 'Fn.select(0, list)' (not 'list[0]') to extract elements from token lists...`
or a deploy-time validation error when doing a `cdk.Fn.select`:
`Template format error: The Value field of every Outputs member must evaluate to a String.`

### Reproduction Steps

Here's a repro that produces both the synth-time and deploy-time errors. Uncomment `ConsumerSynthTimeError` to get a synth-time error.

```python
from aws_cdk import aws_ec2 as ec2, aws_ssm as ssm
import aws_cdk as cdk
from constructs import Construct

app = cdk.App()

class Producer(cdk.Stack):
    def __init__(self, scope: Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        vpc = ec2.Vpc(self, "vpc")
        self.endpoint = ec2.InterfaceVpcEndpoint(
            self,
            "endpoint",
            vpc=vpc,
            service=ec2.InterfaceVpcEndpointAwsService.SECRETS_MANAGER,
        )
        self.single_dns_entry = cdk.Fn.select(0, self.endpoint.vpc_endpoint_dns_entries)

class ConsumerSynthTimeError(cdk.Stack):
    def __init__(
        self, scope: Construct, id: str, vpc_endpoint_dns_entries: list[str], **kwargs
    ) -> None:
        super().__init__(scope, id, **kwargs)

        ssm.StringListParameter(
            self, "parameter", string_list_value=vpc_endpoint_dns_entries
        )

class ConsumerDeployTimeError(cdk.Stack):
    def __init__(
        self, scope: Construct, id: str, vpc_endpoint_dns_entry: str, **kwargs
    ) -> None:
        super().__init__(scope, id, **kwargs)

        ssm.StringParameter(self, "parameter", string_value=vpc_endpoint_dns_entry)

producer = Producer(app, "producer")

# ConsumerSynthTimeError(
#     app,
#     "consumerSynthTime",
#     vpc_endpoint_dns_entries=producer.endpoint.vpc_endpoint_dns_entries,
# )

ConsumerDeployTimeError(
    app,
    "consumer",
    vpc_endpoint_dns_entry=producer.single_dns_entry,
)

app.synth()
```

### Possible Solution

`cdk.Fn.select` should be placed in the producer stack instead of the consumer, and the result should be passed the output.

In cases where a whole list has to be passed, CDK could do a `cdk.Fn.join` in the producer, output that, and a `cdk.Fn.split` in the consumer.

### CDK CLI Version

2.38.1

### Framework Version

2.38.1

### Node.js Version

18.7.0

### OS

Linux

### Language

Python

### Language Version

3.10

**Comment by comcalvi** [comment]
We've fixed this in one region with #22873, but it doesn't work for cross-account / region.

**Comment by gshpychka** [comment]
My issue was about CloudFormation outputs, so single-environment by definition. Not sure whether the new cross-env references are relevant here as well.

**Comment by comcalvi** [comment]
Closing this down, I don't think this applies to cross-env references.
