### ISSUE TITLE
(ec2): cannot provide availabilityZones to VPC 

### ISSUE THREAD

**Issue by peterwoodworth** [aws/aws-cdk#21690]
### Describe the bug

I cannot use the availabilityZones prop for VPC without it throwing an error about my stack not being able to use those AZs. I can only use `dummy1a` etc.

Error message:
```
Given VPC 'availabilityZones' us-east-1a must be a subset of the stack's availability zones dummy1a,dummy1b,dummy1c
```

The [docs](https://docs.aws.amazon.com/cdk/api/v1/docs/aws-ec2-readme.html#control-over-availability-zones) state that:
> The number of Availability Zones that are available depends on the region and account of the Stack containing the VPC. If the [region and account are specified](https://docs.aws.amazon.com/cdk/latest/guide/environments.html) on the Stack, the CLI will [look up the existing Availability Zones](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html#using-regions-availability-zones-describe) and get an accurate count.

However, specifying the environment on the stack will not force a lookup for viable AZs even when supplying AZs to the availabilityZones prop

The described workaround overriding `get availabilityZones()` works, however that should not be necessary to be able to specify the AZs to use in a new VPC

### Expected Behavior

VPC to use supplied AZs

### Current Behavior

Throws error because the usable Stack AZs are dummy values

### Reproduction Steps

Specify a new VPC

```
    new Vpc(this, 'vpc', {
      availabilityZones: ['us-east-1a']
    })
```

In the stack I've supplied an account number as well as the region. Interestingly enough, _not_ supplying the environment to the stack will lead to successful synth

### Possible Solution

The context lookup is not triggered for Stack.availabilityZones, but it should be triggered in this case, or there should be no check to make sure that the availability zones are valid.

### Additional Information/Context

The issue goes away if you specify the availability zones based off the availability zones from the stack

```
    const vpc = new ec2.Vpc(this, 'TestVPC', {
      cidr: '10.0.0.0/16',
      availabilityZones: cdk.Stack.of(this).availabilityZones.sort().slice(0,1)
    })
```

This will ensure a lookup occurs

### CDK CLI Version

2.38

### Node.js Version

.

### OS

.

### Language

Typescript

**Comment by pradoz** [comment]
Unable to reproduce with this:
```typescript
    const vpc = new ec2.Vpc(this, 'test_vpc', {
        availabilityZones: ['us-east-1a']
    });
```
or this:
```typescript
    const vpc = new ec2.Vpc(this, 'test_vpc', {
        availabilityZones: ['us-east-1a', 'us-east-1b']
    });
```

And I've also tried not supplying an environment, using the default environment, and using an explicit environment:
```typescript
  env: { account: process.env.CDK_DEFAULT_ACCOUNT, region: process.env.CDK_DEFAULT_REGION }, // default
  env: { account: '123456789012', region: 'us-east-1' }, // explicit
```

**Comment by gumonet** [comment]
Maybe the context file was not created: https://docs.aws.amazon.com/cdk/v2/guide/context.html 

Try to create a file called: `cdk.contect.json` on your root directory project, and something like this.
Note: Change the {{account_id}} for your account id.
```
{
    "availability-zones:account={{account_id}}:region=us-east-1": [
      "us-east-1a",
      "us-east-1b",
      "us-east-1c",
      "us-east-1d",
      "us-east-1e",
      "us-east-1f"
    ]
  }

```

**Comment by peterwoodworth** [comment]
@gumonet you're right that the context file isn't getting created, the issue is that this is occurring during _synth_ and no lookup is occurring at all for some reason. If a lookup were actually happening this wouldn't be an issue, but I and some others have been encountering this issue so there is some inconsistency somewhere which is preventing a lookup from occurring.

@pradoz thanks for looking into this, but I can still reproduce this on latest version. It's possible you already have the context file in your testing environment

Steps to reproduce:
1. `cdk init` in new folder
2. Supply environment variables
3. Add env to stack (both explicit and using env variables creates error)
4. Add Vpc to stack 
```ts
    new Vpc(this, 'vpc', {
      availabilityZones: ['us-east-1a']
    })
```
5. `cdk synth`

**Comment by gumonet** [comment]
@peterwoodworth yeah, this error is very weird, but would fix creating the context file manually, is the only way that I found to fix the issue :cry:

**Comment by kennu** [comment]
I'm observing the same problem. Maybe worth mentioning that in my case, the Stack contains a NestedStack which contains a Construct that defines the VPC. Same error from cdk synth, cdk diff and cdk deploy commands:

```
Error: Given VPC 'availabilityZones' us-east-1a,us-east-1b,us-east-1c must be a subset of the stack's availability zones dummy1a,dummy1b,dummy1c
```

Manually creating cdk.context.json with all the availability zones is a workaround. However, we need to deploy this stack to multiple accounts and regions and it's not feasible to define all of them in the context.

**Comment by kennu** [comment]
I was also able to work around by adding this method to the NestedStack that contains the VPC construct (TypeScript):

```
get availabilityZones() {
  return this.customAvailabilityZones;
}
```

I set this.customAvailabilityZones in the NestedStack constructor and it seems to work.

**Comment by karrth** [comment]
> I was also able to work around by adding this method to the NestedStack that contains the VPC construct (TypeScript):
> 
> ```
> get availabilityZones() {
>   return this.customAvailabilityZones;
> }
> ```
> 
> I set this.customAvailabilityZones in the NestedStack constructor and it seems to work.

This also helped me create VPCs in a nested stack with cross account deploys, where the nested stack was unable to resolve the availability zones in the second account.  Adding this function and providing the data from the parent stack as an argument made it work as expected.

I was also able to resolve this problem by manually adding the availability zones for the second account in the context file, but I'd like to avoid that manual step as much as possible

**Comment by blade2005** [comment]
Running into this same issue. It would look like the cli is simply not doing the fetch for availablity zones.

**Comment by LajosPolya** [comment]
I am seeing this issue in `"aws-cdk": "2.76.0"`

**Comment by dxmxnlord** [comment]
Ran into the same issue, is there anybody with an idea of a temporary fix for the Java CDK ? ( without modifying the context file since I am clearing it every time pre deployment )

**Comment by Zappatta** [comment]
Here's how I managed to work around this problem:

I commented the line that declares the availability zone:

```python
        vpc = ec2.Vpc(
            self,
            'my awesome vpc',
            cidr='172.31.0.0/16',
            nat_gateways=2,
            # availability_zones=env_data.availability_zones,
        )
```
I then ran `cdk diff`, which ran OK and updated the `cdk.context.json` file with the availability new zones 
Then uncommented the file, and it worked well

**Comment by luber2000** [comment]
I solved it after configuring my aws cli credentials
