### ISSUE TITLE
Change documentation to use composition rather than inheritance

### ISSUE THREAD

**Issue by pauldraper** [aws/aws-cdk#21696]
### Describe the feature

> In general, composition is preferred over inheritance when developing AWS CDK constructs.

I suggest the same should be true of AWS CDK stacks.

Would you rather [(source)](https://docs.aws.amazon.com/cdk/v2/guide/apps.html):

```py
class MyFirstStack(Stack):

    def __init__(self, scope: Construct, id: str, **kwargs):
        super().__init__(scope, id, **kwargs)

        s3.Bucket(self, "MyFirstBucket")
```

or 

```py
def my_first_stack(stack: Stack):
  s3.Bucket(stack, "MyFirstBucket")
```

Not to mention the complexity if you start needing to introduce your own kwargs.

### Use Case

Cleaner code is better code.

Let's encourage people to write cleaner code.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2

### Environment details (OS name and version, etc.)

N/A

**Comment by peterwoodworth** [comment]
Thanks for the suggestion Paul,

Both our constructs and stack documentation show and recommend creating reusable and sharable pieces of infrastructure, and as projects grow I think that's best done by declaring a new class which you can create instances of. This is a design choice that some people may disagree with - if you prefer to do this functionally that's great 🙂 However I don't think our recommendation here is going to change.
