### ISSUE TITLE
(aws-cdk-lib): Slow Python import times

### ISSUE THREAD

**Issue by pauldraper** [aws/aws-cdk#21695]
### Describe the bug

`import aws_cdk` takes a long time.

### Expected Behavior

I expected importing to take less than 2s.

Comparisons:

`python -c 'import boto3'` takes ~200ms.

`node -e 'require("aws-cdk-lib")'` takes ~850ms.

### Current Behavior

`python -c 'import aws_cdk'` takes 5s.

### Reproduction Steps

```
time python -c 'import aws_cdk'

real	0m5.290s
user	0m5.562s
sys	0m0.659s
```

### Possible Solution

Remove the dozens of imports from `__init__.py`, most of which are unnecessary for most users.

### Additional Information/Context

This makes even the simplest commands like `cdk list` bizarrely slow even for small projects.

### CDK CLI Version

2.37.0

### Node.js Version

18

### OS

Ubuntu 20.04

### Language

Python

### Language Version

Python 3.8

**Comment by peterwoodworth** [comment]
Sorry about the length of time this takes,

> Remove the dozens of imports from __init__.py, most of which are unnecessary for most users

Which imports do you think are unnecessary?

**Comment by pauldraper** [comment]
More details here: https://github.com/aws/jsii/issues/3389#issuecomment-1225625101

**Comment by peterwoodworth** [comment]
Thanks for linking this issue, this is a jsii issue so that existing issue will be the best place to track this. Thanks again

**Comment by bafonso** [comment]
We are just now starting to use CDK v2 and the workflow is abysmally slow. AWS-CDK developers really need to re-think if packaging everything makes sense. Almost half a year later and no solution in sight, we are now forced to re-consider using terraform. Sorry for venting but I wonder how this slowness is not problematic for most python developers, assuming there were enough testers involved during aws-cdk v2 development.
