### ISSUE TITLE
(aws-ec2): Private subnets without Nat Gateway

### ISSUE THREAD

**Issue by jmortlock** [aws/aws-cdk#21697]
### Describe the feature

Allow for more flexible subnet configuration; with regard to networking solutions not involving nat gateways.

### Use Case

To allow a three tier subnet structure where the private subnet has egress with Transit Gateway.

Currently a private subnet must have egress with NAT gateways.

https://github.com/aws/aws-cdk/blob/62cbcde1a2e6a72685a31cab1350f653fbde652f/packages/%40aws-cdk/aws-ec2/lib/vpc.ts#L2207

### Proposed Solution

Add a new subnet type `PRIVATE_WITH_EGRESS` which does not require the natgateway check. For all other intents and purposes it behaves like `PRIVATE_WITH_NAT`

### Other Information

https://github.com/aws/aws-cdk/issues/21189

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.38.1

### Environment details (OS name and version, etc.)

Linux; Ubuntu

**Comment by corymhall** [comment]
@jmortlock I am going to close this in favor of tracking #21189.

I saw you created a PR. I'll try to get to a review later this week.
