### ISSUE TITLE
CfnRoute: Unable to find route table

### ISSUE THREAD

**Issue by SGFGOV** [aws/aws-cdk#21694]
### Describe the bug

Unable to find route table when the two vpcs are in different regions, and when one is referenced by lookup while the other is created by the cdk

### Expected Behavior

should work just as it does when both are in the same region. 

### Current Behavior

Throws error during deployment. 

The routeTable ID 'rtb-XXXXXXXXX' does not exist (Service: AmazonEC2; Status Code: 400; Error Code: InvalidRouteTableID.NotFound; Request ID: ebcdfdc3-168c-4d5e-a6ce-733364958421; Proxy: null)

where rtb-XXXXXXXX is the default route table of vpc1

### Reproduction Steps

```ts
/*

vpc1 and vpc2 are in differenter rgions
*/
this.vpc1 = ec2.Vpc.fromLookup(this, `vpc1`, {
      vpcId: VpcId,
      region: props.VpcRegion
      
    });


this.vpc1.publicSubnets.map((subnet,index)=>{
         const route = new ec2.CfnRoute(
          this,
          `${id}-${index}`,
          {
            destinationCidrBlock: this.vpc2.vpcCidrBlock,
            routeTableId: subnet.routeTable.routeTableId,
            vpcPeeringConnectionId: this.vpcPeeringConnection.ref,
          }
        );
        route.applyRemovalPolicy(RemovalPolicy.DESTROY); 
        })
```

### CDK CLI Version

2.38.1

### Node.js Version

16

### OS

linux

### Language

Typescript

**Comment by corymhall** [comment]
@SGFGOV is the stack that this code is part of created in the same region where the route table exists?

For example this will not work. Looking up the vpc1 in `us-east-2` and then creating the route in `us-east-1`.
```ts
class MyStack extends Stack {
  constructor(scope: Construct, id: string) {
    super(scope, id);
	 this.vpc1 = ec2.Vpc.fromLookup(this, `vpc1`, {
	      vpcId: VpcId,
	      region: props.VpcRegion
	   });


		this.vpc1.publicSubnets.map((subnet,index)=>{
         const route = new ec2.CfnRoute(
          this,
          `${id}-${index}`,
          {
            destinationCidrBlock: this.vpc2.vpcCidrBlock,
            routeTableId: subnet.routeTable.routeTableId,
            vpcPeeringConnectionId: this.vpcPeeringConnection.ref,
          }
        );
        route.applyRemovalPolicy(RemovalPolicy.DESTROY); 
        })

	})
}
new MyStack(app, 'Stack', {
  env: { region: 'us-east-1' },
  VpcRegion: 'us-east-2',
});
```

**Comment by SGFGOV** [comment]
Hi, thanks for your help
Figured that out, worked around by creating a wrapper stack for the vpc in other region.

**Comment by kissrin** [comment]
@SGFGOV  Facing the same issue, could you share your code snippet which worked for you if possible?

**Comment by SGFGOV** [comment]
you just need to create a second stack in the app with environment region set to the same as that of the vpc region you intend to use. and then add routes accordingly between the regions..

**Comment by kissrin** [comment]
Yeah, I was able to figured that, it worked. Thank you!!!

**Comment by SGFGOV** [comment]
you just need to create a second stack in the app with environment region set to the same as that of the vpc region you intend to use. and then add routes accordingly between the regions..
