### ISSUE TITLE
(lambda): bundling options is not picking custom directory for building AWS lambda package

### ISSUE THREAD

**Issue by kpalaparthi** [aws/aws-cdk#21705]
### Describe the bug

Bundling options is not picking custom directory  from the project subfolders for building AWS lambda package. When I give default project home path it is working as expected.
Error when given custom path for asset.

    Failed to bundle asset id/CustomResourceFunction/Code/Stage, bundle output is located at /private/var/folders/wf/1xhc8l4957g83_vs18gjqrsc0000gp/T/cdk.outvhrmAu/asset.45d1623d93da69bf0ca90a8fb657a919dd1ec4adf5a0d93765fa103c61c9a47c-error: Error: docker exited with status 1

      37 |     });
      38 |
    > 39 |     const onEvent = new lambda.Function(scope, 'CustomResourceFunction', {
         |                     ^
      40 |       runtime: lambda.Runtime.JAVA_11,
      41 |       handler: props.lambdaHandler ? props.lambdaHandler : 'com.up.kafka.topic.lambda.Handler::handleRequest',
      42 |       code: lambda.Code.fromAsset(props.directoryName, { bundling: props.bundlingOptions }),

### Expected Behavior

It should work with the custom path  from the project subfolders 

### Current Behavior

it is not working with the custom path  from the project subfolders 

### Reproduction Steps

provide custom path from the project subfolders when building asset from bundling options while creating aws lambda

### CDK CLI Version

2.31.0

### Node.js Version

18.2.0

### OS

mac os

### Language

Typescript

### Language Version

4.7.4

**Comment by kaizencc** [comment]
@kpalaparthi can you share your CDK code that throws the error, along with the code that is working as expected?

**Comment by kpalaparthi** [comment]
Can you please let me know whether we can pass custom path apart from the default path I.e project path

**Comment by kaizencc** [comment]
@kpalaparthi without your code for `bundlingOptions` I will have a hard time helping you. You should be able to pass a custom path.
