### ISSUE TITLE
(ec2): Make it easy/possible to create persistent UserData on a Windows instance.

### ISSUE THREAD

**Issue by ddneilson** [aws/aws-cdk#21708]
### Describe the feature

By default, EC2 UserData is run once when an instance is first started after being provisioned. However, it is possible to persist that userdata so that it is run on every instance start. This is a request to expose that functionality in the UserData class for the CDK; specifically, for Windows.

On Linux systems, this persistence is achieved via multipart userdata as in this [knowledgebase article](https://aws.amazon.com/premiumsupport/knowledge-center/execute-user-data-ec2/). However, on Windows the persist flag must be set as a decorator to the userdata script itself -- outside of the <powershell> tags (see [the <persist> tag](https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/ec2-windows-user-data.html#user-data-scripts)).

Right now, the only way to achieve this on Windows is through the use of an escape hatch with code that looks something like:
```python
fleet = AutoScalingGroup(...)
 
# Grab the user data from the fleet and add the persist flags as a new string
fleet_user_data = fleet.user_data.render()
new_user_data = f"{fleet_user_data}<persist>true</persist>"
 
# Find the CfnLaunchConfiguration child of the ASG
launch_config = fleet.node.find_child('LaunchConfig')
 
# Replace the user_data property on the CfnLaunchConfiguration
launch_config.user_data = Fn.base64(new_user_data)
```

This is extremely non-obvious for anyone that isn't a fairly expert user of the CDK; just creating this code involved digging into the depths of the implementation of the ASG L2 construct.

### Use Case

Anyone dynamically attaching their Windows instance to an Active Directory (AD) during instance startup needs this functionality; connecting to an AD involves rebooting the instance while running startup scripting both before and after that reboot.

### Proposed Solution

I have a PR prepared and will be posting it momentarily.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.38.1

### Environment details (OS name and version, etc.)

Any

**Comment by corymhall** [comment]
@ddneilson thanks for the feature request and the PR! It looks like someone from the team is reviewing the PR.
