### ISSUE TITLE
aws-eks: lambda functions provisioned by cdk use end-of-life node.js version

### ISSUE THREAD

**Issue by trondhindenes** [aws/aws-cdk#21718]
### Describe the bug

As far as I can see, the "helper functions" provisioned by cdk's eks module are configured to use NodeJs version 12. AWS has started notifying users that support for this version is ending ("We recommend that you upgrade your existing Node.js 12 functions to Node.js 16 before November 14, 2022."). 

### Expected Behavior

Lambda functions should be provisioned using a newer NodeJS version

### Current Behavior

Lambda functions should be provisioned using an outdated NodeJS version

### Reproduction Steps

see above

### CDK CLI Version

2.30.0

### Framework Version

2.21.1

### Node.js Version

v16.16.0

### OS

Ubuntu 22.04

### Language

Python

### Language Version

3.9.7

**Comment by ayozemr** [comment]
Got same notification for certificate-manager lambdas that manage certificate validation

**Comment by peterwoodworth** [comment]
I can't find any instances in our codebase where we still use Node 12 in our functions. EKS specifically has certainly been addressed https://github.com/aws/aws-cdk/blob/a5ced21ef98420f5e76ca41a1a9a29a6c40bcdb2/packages/%40aws-cdk/aws-eks/lib/cluster-resource-provider.ts#L11

Could you please link to any function generated in our codebase that still uses node 12? Thanks

**Comment by TheRealAmazonKendra** [comment]
The update was made in 2.28.0. You just need to update to a newer version.

**Comment by trondhindenes** [comment]
Ah, thanks. I see it now. I scanned the release notes for "eks" but I see the change is logged under "lambda". Thank you!
