### ISSUE TITLE
(website): https://docs.aws.amazon.com/cdk/api/latest/ goes to incorrect target

### ISSUE THREAD

**Issue by ddneilson** [aws/aws-cdk#21720]
### Describe the bug

https://docs.aws.amazon.com/cdk/api/latest/

That URL redirects to the CDK v1 API documentation. Seems like a bug... the CDK v2 APIs are the actively developed library, with the v1 APIs being maintenance mode.

### Expected Behavior

https://docs.aws.amazon.com/cdk/api/latest/

redirects to https://docs.aws.amazon.com/cdk/api/v2/

### Current Behavior

https://docs.aws.amazon.com/cdk/api/latest/

redirects to https://docs.aws.amazon.com/cdk/api/v1/

### Reproduction Steps

Navigate to https://docs.aws.amazon.com/cdk/api/latest/ in your web browser.

### CDK CLI Version

2.38.1

### Node.js Version

Any

### OS

Any

### Language

Typescript, Python, .NET, Java, Go

**Comment by peterwoodworth** [comment]
I'm curious where you're getting this link from @ddneilson

**Comment by ddneilson** [comment]
> I'm curious where you're getting this link from @ddneilson

It was in the autocomplete URL bar in my web browser, so I don't recall precisely where I got that link in the first place. However, the Wayback Machine definitely knows about it as well: https://web.archive.org/web/20220000000000*/https://docs.aws.amazon.com/cdk/api/latest/

If you click back a year or so you'll see that it was the original URL for https://docs.aws.amazon.com/cdk/api/v1/, and then became a redirect to https://docs.aws.amazon.com/cdk/api/v1/.

My guess, as an external observer, is that when the CDK first came out the URL https://docs.aws.amazon.com/cdk/api/latest/ was created to link to the API reference (you'll notice that the URL for the developer guide on the API landing page is currently also a 'latest' version: https://docs.aws.amazon.com/cdk/latest/guide). Then, some time later the CDK team decided that there was going to be a CDKv2; when that happened someone created the https://docs.aws.amazon.com/cdk/api/v1/ URL (you'll notice that it didn't exist in the wayback machine prior to 2022). Since then no one has gone back to update the https://docs.aws.amazon.com/cdk/api/latest/ redirect to the v2 API docs after CDKv2 released -- hence this ticket.

**Comment by TheRealAmazonKendra** [comment]
I thought we fixed this a while back, but I noticed this recently too. I forgot to open an issue, though.

**Comment by khushail** [comment]
@ddneilson , looks like this link https://docs.aws.amazon.com/cdk/api/latest/  is now being mapped to https://docs.aws.amazon.com/cdk/api/v2/ which is correctly pointing to the expected link. So I am closing this issue. Please feel free to reopen if you encounter this again.
