### ISSUE TITLE
(trigger): Missing Lambda invoke permissions if more than one function trigger is defined

### ISSUE THREAD

**Issue by AmizerAWS** [aws/aws-cdk#21723]
### Describe the bug

When initiating two trigger based function, only first one gets executed and second one is missing lambdainvoke permissions.

AWSCDK.TriggerCustomResourceProviderCustomResourceProvider/Role only allows for single lambda Invoke.
When i remove first function and leave the second one - it will update the role and allow trigger to execute ok.
When i add first function again, prior deployment it will warn me that it will remove invoke permissions for second and add to the first.

### Expected Behavior

Both triggers are executed succesfully

### Current Behavior

Second trigger returns error:
Access Denied - no identity-based policy allows the lambda:InvokeFunction action

### Reproduction Steps

```
import aws_cdk.triggers as trigger

first_lambda=trigger.TriggerFunction(self, "Test Lambda",runtime=trigger.Runtime.PYTHON_3_9,handler='main.lambda_handler', code=lmb.Code.from_asset(<PATH TO RESOURCES>))
second_lambda=trigger.TriggerFunction(self, "Test Lambda2",runtime=trigger.Runtime.PYTHON_3_9,handler='main.lambda_handler', code=lmb.Code.from_asset(<PATH TO OTHER RESOURCES>))
```

### CDK CLI Version

2.38.1

### Node.js Version

18.6.0

### OS

MacOS Montarey 12.4

### Language

Python

### Language Version

3.10

**Comment by indrora** [comment]
Can you provide a minimal example and its CloudFormation output? 

What version of the Python CDK library are you using?
