### ISSUE TITLE
cdk deploy -y

### ISSUE THREAD

**Issue by awhillas** [aws/aws-cdk#21729]
### Describe the feature

Have a `-y` option that answers `yes` to "Do you wish to deploy these changes (y/n)?" 

### Use Case

So when i start a deploy and forget that that question is asked and go and get coffee (and a muffin, or maybe an afghan biscuits... or whatever) I don't come back after 20 minutes to find "daaaah, Are you sure you want to deploy? (y/n)".
YES I'm SURE thats why I ran the command?!?

### Proposed Solution

command line flag that just answers yes to all questions

### Other Information

yeah i know about the `-f` option but the semantics are not the same

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.37.1 (build f15dee0)

### Environment details (OS name and version, etc.)

Ubuntu 20.04

**Comment by nicolai0** [comment]
`--require-approval never`?

**Comment by peterwoodworth** [comment]
As @nicolai0 said, `--require-approval` is the option you're looking for here
