### ISSUE TITLE
(rds): unable to alter master user password when using DatabaseClusterFromSnapshot with snapshotCredentials

### ISSUE THREAD

**Issue by MitchWijt** [aws/aws-cdk#21730]
### Describe the bug

About 2 months ago a this [PR](https://github.com/aws/aws-cdk/pull/20504) got merged, which states that we should be able to alter the master user password of the snapshot using the `snapshotCredentials` prop. However when using this prop CDK creates a new secret in Secrets Manager, but the master user password still remains unchanged. It seems like the DatabaseSecret that is created is not being used. 

Looking at the code of the PR, the `masterUserPassword` gets changed in the `cfnDbCluster` while also having the `snapshotIdentifier` prop. However the docs state to NOT use the `masterUserPassword` prop together with the `snapshotIdentifier` prop. 

### Expected Behavior

When using the `snapshotCredentials` property with `rds.SnapshotCredentials.fromGeneratedSecret()` inside the `DatabaseClusterFromSnapshot` construct. I expect the master user password to be changed to the password that is generated in Secrets Manager. 

### Current Behavior

A DatabaseSecret is created inside Secrets Manger, however the master user password of the snapshot remains unchanged.

### Reproduction Steps

1. Create a RDS DB using Aurora Serverless using the `DatabaseCluster` construct in CDK
2. Create snapshot
3. Add `DatabaseClusterFromSnapshot` construct to CDK using the `snapshotCredentials` with `SnapshotCredentials.fromGeneratedSecret()`, and remove the `DatabaseCluster` construct from CDK
4. Try logging in the DB as master user using the generated DatabaseSecret that is created from the `DatabaseClusterFromSnapshot`

### CDK CLI Version

2.27.0

### Node.js Version

16

### OS

Linux

### Language

Typescript

**Comment by corymhall** [comment]
@MitchWijt can you provide an example that I can deploy to reproduce? We have an integration test that tests this scenario and I tried to reproduce using this test and was unable to.

https://github.com/aws/aws-cdk/blob/main/packages/@aws-cdk/aws-rds/test/integ.cluster-snapshot.ts

One thing I noticed is that all DB instances have to be created before the password is updated to the new generated password.

**Comment by MitchWijt** [comment]
@corymhall The problem seems to be in the secret rotation. We have Permissions Boundary Aspects on our stack. However CDK tries to create a role for the rotating lambda function without these Aspects. Which is the reason it fails. 

Its mentioned in this [issue](https://github.com/aws/aws-cdk/issues/19649) 

But I do not see a solution for it at the moment. 

As a sidenote. Since by default the `DatabaseClusterFromSnapshot` copies the master username and master password from the original cluster. Wouldn't it be more logical if the secret property returned from `DatabaseClusterFromSnapshot` would contain the correct `DatabaseSecret` with the same password and username as from the original cluster, unless `snapshotCredentials` is being used? 

Currently the secret returned is unreliable since it can't be used to login to the Cluster that is created

**Comment by MitchWijt** [comment]
Should a rotation be needed in order for the password to be updated to the new generated password? If not, then the password is not being updated on my end. 

Example: 
**1. Deploy this:** 
`new rds.DatabaseCluster(this, `DatabaseCluster`, 
{
            defaultDatabaseName: "postgres",
            engine: rds.DatabaseClusterEngine.auroraPostgres({
                version: AuroraPostgresEngineVersion.VER_13_6,
            }),
            instances: 1,
            backup: {
                retention: Duration.days(7)
            },
            removalPolicy: RemovalPolicy.RETAIN,
            instanceProps: {
                vpc: vpc,
                instanceType: CustomInstanceType.SERVERLESS as unknown as ec2.InstanceType,
                autoMinorVersionUpgrade: true,
                publiclyAccessible: false,
                vpcSubnets: {
                    subnets: vpc.isolatedSubnets
                },
            },
            cloudwatchLogsExports: ["postgresql"],
        }
)`

**2. Create Snapshot**

**3. Create cluster from Snapshot and deploy**
`new rds.DatabaseClusterFromSnapshot(this, `DatabaseClusterFromSnapshot`, {
                ...samePropsAsStep1,
                snapshotCredentials: rds.SnapshotCredentials.fromGeneratedSecret('postgres', {
                    excludeCharacters: '`+{}[]()\'"/\\'
                }),
                snapshotIdentifier: props.snapshotIdentifier
            })`

**Comment by jogold** [comment]
I redeployed the integration test just now and indeed it doesn't work anymore... very strange. I can assure that when #20504 was merged it worked.

I now have to check if the behavior has also changed for DB instances created from snapshots.

I think the solution could be to use a custom resource to make a [`ModifyDBCluster`](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_ModifyDBCluster.html) call to update the master password.

**Comment by corymhall** [comment]
Should we not even try to update the password? I think if CloudFormation does not support this functionality that we should not try to hack around it.

**Comment by MitchWijt** [comment]
@corymhall I do agree with you. If it's indeed not supported, there is probably a reason for it. However, currently the secret that is returned from the snapshot has an incorrect password, even when not using the `snapshotCredentials` props. It should at-least help I think. If a secret gets created that has the old password which is then returned from the cluster as the secret. 

Example: 
1. Cluster + Secret gets created
2. Snapshot is made 
3. Cluster from snapshot gets created with snapshotIdentifier + new Secret (which contains the original password)

This way users can rely on the `.secret` prop that is being returned from the cluster and use that in their other processes. At the moment the secret that is returned can't be used for anything, since it's incorrect.

**Comment by corymhall** [comment]
Yeah we should expose the original secret if we can, and if we can't then `undefined`. You may be creating a cluster from a cluster that was created via CDK and has a secret, but you also might be creating a cluster from a manually created cluster that doesn't have the password stored in a secret.

**Comment by amcquistan** [comment]
This cross referenced issue provides a minimally scoped reproducable v2 CDK project. https://github.com/aws/aws-cdk/issues/22199

**Comment by ryparker** [comment]
It seems like the current implementation of `snapshotCredentials` relies on an expectation that Cfn will automatically change the DB cluster password to the newly generated secret shortly after the DB cluster is restored from snapshot. From my testing this is not the case and I cannot find any Cfn documentation that states that this should be the expected behavior. Based on my testing you cannot restore a DB cluster and replace the DB password in a single deploy. I tested this with both `SnapshotCredentials.fromGeneratedSecret()` and `SnapshotCredentials.fromPassword()`. However if you apply the `snapshotCredentials` **after** deploying the `DatabaseClusterFromSnapshot` then the DB password will update as expected.

> Yeah we should expose the original secret if we can, and if we can't then `undefined`. 

I don't know of a way to expose the original secret when restoring from a snapshot. My understanding is that the original secret is never recreated when restoring from a snapshot. It's up to the user to remember the password, keep the original secret from being deleted, or change the database password using AWS console/RDS API.

Solutions:

A.) File this as an issue with Cfn. This will require evidence that Cfn supports restoring a DB cluster and updating the password in a single deploy.

B.) Update documentation to inform the user that they must deploy the `DatabaseClusterFromSnapshot` first before providing  a new password via the `snapshotCredentials` prop.

C.) We create and maintain a custom resource that changes the DB password for the user shortly after the DB cluster is restored. Which as Cory [mentioned](https://github.com/aws/aws-cdk/issues/21730#issuecomment-1242176924) is not ideal.

I'm leaning towards B. Any other ideas?

**Comment by MitchWijt** [comment]
@ryparker 
needing 2 deploys for a piece of your infra to be setup correctly seems like an anti-pattern to me. Since there are also events being pushed out whenever a cluster is created successfully, as you can see here: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_Events.Messages.html#USER_Events.Messages.cluster 

This means whenever other services depend on these events, for example event 005 which is `DB instance created` that they will all fail whenever a deploy finished of `DatabaseClusterFromSnapshot` because the password that it receives is incorrect. 

in my eyes option A seems like a more viable solution that would also be and feel more intuitive for users using these constructs.

**Comment by scottbisker** [comment]
What's completely bizarre  is that `DatabaseInstanceFromSnapshot`  works as expected when providing the `snapshotCredentials` property.   Even though Cfn clearly states that setting the master username or password is not supported  https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbinstance.html#cfn-rds-dbinstance-dbsnapshotidentifier .   Seems like a Cfn inconsistency to me.    This event excerpt is from CloudTrail immediately after the DBInstance is created.    

The Event Type is  ModifyDBInstance

"eventTime": "2023-01-12T22:48:04Z",
    "eventSource": "rds.amazonaws.com",
    "eventName": "ModifyDBInstance",
    "awsRegion": "us-west-2",
    "sourceIPAddress": "cloudformation.amazonaws.com",
    "userAgent": "cloudformation.amazonaws.com",
    "requestParameters": {
        "dBInstanceIdentifier": "xxxxxxxxxxxx",
        "allocatedStorage": 1000,
        "applyImmediately": true,
        "masterUserPassword": "****",
        "engineVersion": "8.0.28",
        "allowMajorVersionUpgrade": false,
        "iops": 3500
    },

There is no such event after a DBClusterFromSnapshot is created.

**Comment by atali** [comment]
I am trying to restore a snapshot from prod db to my dev db, and I need to reset the password of the db with a new generated password and be saved into secretsmanager. I am stuck until this bug is fixed

**Comment by ryparker** [comment]
> I've not looked too much into this yet, but RDS just announced a new integration with secretsmanager [aws.amazon.com/about-aws/whats-new/2022/12/amazon-rds-integration-aws-secrets-manager](https://aws.amazon.com/about-aws/whats-new/2022/12/amazon-rds-integration-aws-secrets-manager/)

Tested this today:
1.) Created a new DBCluster with `ManageMasterUserPassword: true`
2.) Viewed the DBCluster's managed credentials secret in secret manager and copied the password.
3.) Created a snapshot
4.) Deleted the cluster (this also deleted the managed secret as documented)
5.) Restored from the cluster snapshot (the secret was not recreated)
6.) Logged in using the original password from step #2. (this worked)

What's strange about this behavior is that the managed secret is never recreated so it's not clear if/how it will be rotated as documented:

> Aurora manages the settings for the secret and rotates the secret every seven days by default. You can modify some of the settings, such as the rotation schedule. If you delete a DB cluster that manages a secret in Secrets Manager, the secret and its associated metadata are also deleted.

[_Overview of managing master user passwords with AWS Secrets Manager (for Aurora)_](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/rds-secrets-manager.html#rds-secrets-manager-overview)

Another thing to note is that when `ManageMasterUserPassword` is enabled, you cannot provide a custom password.

> Constraints: Can't manage the master user password with AWS Secrets Manager if MasterUserPassword is specified.

[_DBCluster's ManageMasterUserPassword prop docs_](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbcluster.html#cfn-rds-dbcluster-managemasteruserpassword)

**Comment by ryparker** [comment]
I've created a Cfn issue for the desired behavior: https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1500

**Comment by pflueras** [comment]
It seems this bug is fixed for me. I'm using the following code:
`const mainRdsCluster = new rds.DatabaseClusterFromSnapshot(this, 'testRdsCluster', {
      snapshotIdentifier: 'testRdsSnapshot',
      ...
      snapshotCredentials: rds.SnapshotCredentials.fromGeneratedSecret('admin_user'),
      ...
}`
Please confirm or inform above information.
Thank you in advance!

**Comment by MitchWijt** [comment]
@pflueras Are you able to use that secret to login to the cluster that was created from snapshot?

**Comment by pflueras** [comment]
Before: the actual master password of the cluster was given by the RDS snapshot. The password of the newly created secret (SnapshotCredentials.fromGeneratedSecret) was incorrect. I had to fix the password from the secret to get the secret functional.

After: the actual master password is given by the newly created secret (SnapshotCredentials.fromGeneratedSecret). The secret is fully functional.

I am not sure I answered to your question..

**Comment by scottbisker** [comment]
@pflueras Did you confirm in Cloudtrail that Cloudformation actually reset the cluster password after it was restored?  From my experience, when restoring a DBCluster from a snapshot the original snapshot master password is retained and Cloudformation never attempts to reset the password once the cluster is restored.

**Comment by colifran** [comment]
@pflueras I've been investigating this and it seems from some initial testing that the bug is fixed for me too. I'm going to continue testing this today with some different variations, but I'm wondering if anyone else has had a chance to retry this with success too. @MitchWijt would you be able to retry on your end to see if this is now working for you?

**Comment by tim-finnigan** [comment]
Linking related issue: https://github.com/aws/aws-cdk/issues/21730
