### ISSUE TITLE
aws-apigateway: Custom log format account ID gets translated incorrectly

### ISSUE THREAD

**Issue by LiMuBei** [aws/aws-cdk#21731]
### Describe the bug

I want to set up custom log format for API Gateway:

```typescript
new RestApi(this, "myapi", {
  deployOptions: {
    accessLogFormat: AccessLogFormat.custom(JSON.stringify({
      accountId: AccessLogField.contextAccountId(),
      ...
    })
  })
```

### Expected Behavior

According to the definition of `AccessLogField.contextAccountId()` this should return `The API owner's AWS account ID.` After synthesizing the template, this should then get translated to `$context.accountId`.

### Current Behavior

`AccessLogField.contextAccountId()` gets translated to `$context.identity.accountId` which would return the account ID of the caller.

### Reproduction Steps

Setup a `RestApi` with custom log format and use `AccessLogField.contextAccountId()`.

### CDK CLI Version

2.38.1 (build a5ced21)

### Node.js Version

v16.17.0

### OS

macOS

### Language

Typescript

**Comment by rix0rrr** [comment]
That's a documentation mistake.

I would recommend deprecating the current method, and adding `contextCallerAccountId()` and `contextOwnerAccountId()` to avoid the confusion in the future.
