### ISSUE TITLE
(module name): (short issue description)

### ISSUE THREAD

**Issue by layqnovo** [aws/aws-cdk#21739]
### Describe the bug

Using a SecretValue (github token) to deploy a stack with an Amplify app gives the following error:
![secretError](https://user-images.githubusercontent.com/100163734/186451580-0b4ae271-b392-437d-baa5-eea41d3764bd.png)

This is the code that triggers the error (no error when leaving this out at deploy):
![secretCode](https://user-images.githubusercontent.com/100163734/186453541-7725983c-b1b0-40d9-89dd-c46e6cb1e518.png)

The "github-token" secret is stored and updated in AWS.

### Expected Behavior

Amplify app is created from the github repository after successful deployment.

### Current Behavior

I get a confusing error saying that I can't use the SecretValue for this.

### Reproduction Steps

Save a github token in secrets manager and try to use it when deploying a stack with an Amplify App based on a github repository.

### CDK CLI Version

2.30.0

### Node.js Version

v16.14.2

### OS

Windows 10

### Language

Python

### Language Version

3.10.4

**Comment by pradoz** [comment]
Have you tried the suggested workaround in the error message? It says that you can call `secretValue.unsafeUnwrap()` if you understand and accept the risk of exposing your GitHub token in plaintext

**Comment by peterwoodworth** [comment]
This error is thrown so that you can know when your secret may be at risk of being exposed. You can disable this check by removing the `@aws-cdk/core:checkSecretUsage` in `cdk.json`, or by using `unsafeUnwrap()` to verify that you're ok with the risks involved

**Comment by layqnovo** [comment]
Can someone explain the purpose and intended use of the AWS Secrets Manager if this is not it? The error message indicates that I'm doing something unsafe by using it this way, so what would be the correct and safe way in this situation?
