### ISSUE TITLE
init app: defaults added to cdk.json should be customisable

### ISSUE THREAD

**Issue by mrgum** [aws/aws-cdk#21732]
### Describe the feature

some settings added to cdk.json by default are not ideal for example.

@aws-cdk/core:target-partitions has "aws-cn" added which I think I'll never use and do not want there.

is there a way to tell cdk not to add this when I init an app?

### Use Case

I have to edit cdk.json in a repetitive manner for every new app 

### Proposed Solution

a cdk config file or set of environment values to change the default behaviour

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.38.1 (build a5ced21)

### Environment details (OS name and version, etc.)

Mac Monterey 12.5 21.6.0 Darwin Kernel Version 21.6.0

**Comment by rix0rrr** [comment]
I don't think we want to maintain a configuration mechanism for a feature like this. If you don't like the default behavior and you need to `cdk init` an app so often that the manual editing becomes a burden, I can recommend:

* Another project template generator, like perhaps https://github.com/cookiecutter/cookiecutter
* Wrapping `cdk init` in a script that runs `jq`

**Comment by mrgum** [comment]
@rix0rrr  fair enough, thanks I'll look into cookie cutter

one thing that might be nice is to have cdk scan for services used and remove the service specific setting for those that are not used. e.g. remove "@aws-cdk/aws-rds:lowercaseDbIdentifier": true, when rds is not used
