### ISSUE TITLE
AWS Batch: Need support for more JobDefinition attributes

### ISSUE THREAD

**Issue by rjuengling-hf** [aws/aws-cdk#21740]
### Describe the feature

Support more JobDefinition attributes in the AWS Batch CDK module.

In particular, I need to be able to set the [propagateTags](https://docs.aws.amazon.com/batch/latest/APIReference/API_JobDefinition.html#Batch-Type-JobDefinition-propagateTags) attribute.

### Use Case

Attribution of costs and real-time monitoring.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.38.0-alpha.0

### Environment details (OS name and version, etc.)

CentOS 7

**Comment by peterwoodworth** [comment]
Thanks for reporting this request,

You can currently set this with [escape hatches](https://docs.aws.amazon.com/cdk/v2/guide/cfn_layer.html) by accessing the generated L1 CfnJobDefinition and setting any properties seen [here](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-batch.CfnJobDefinition.html)

We accept contributions! Check out our [contributing guide](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) if you're interested - there's a low chance the team will be able to address this soon but we'd be happy to review a PR 🙂
