### ISSUE TITLE
aws-cdk-lib: SplunkLogDriverProps does not accept token value

### ISSUE THREAD

**Issue by karlkranich** [aws/aws-cdk#21744]
### Describe the bug

When trying to provide a token to the SplunkLogDriver, I would like to provide the token as a string value as I did with CDKv1.  CDK 2.38.1 internal errors say "Please provide either token or secretToken" and that if "secretToken" is not provided, that "token" will be used.  But if token is provided, it says," 'token' does not exist in type 'SplunkLogDriverProps' ".

### Expected Behavior

Should be able to provide "token" or "secretToken" in SplunkLogDriver props.

### Current Behavior

If "token" is provided, get: Object literal may only specify known properties, and 'token' does not exist in type 'SplunkLogDriverProps'.

### Reproduction Steps

Provide a token to SplunkLogDriver, and do not provide secretToken.

### Possible Solution

Allow specifying "token" as with CDK v1.

### CDK CLI Version

2.38.1

### Node.js Version

16.16.0

### OS

macOS 12.5.1

### Language

Typescript

### Language Version

TypeScript 4.7.4

**Comment by peterwoodworth** [comment]
Are you making use of the `secretToken` prop? The `token` prop doesn't exist anymore on v2. Could you share reproduction code?

**Comment by karlkranich** [comment]
I’m trying to use “token” because the error messages say that token will be used if secretToken is not specified. If that’s not the case, the messages should be updated.

**Comment by peterwoodworth** [comment]
I've created a PR for this @karlkranich

**Comment by karlkranich** [comment]
Thank you!
