### ISSUE TITLE
(aws_events/Python): (Non-existent resource appears as if it exists when using aws_events.EventBus.from_event_bus_arn)

### ISSUE THREAD

**Issue by nixenos** [aws/aws-cdk#21752]
### Describe the bug

Hi! My company tried to develop application with multiple environments on the same account and region with some of the resources being shared between multiple stacks. For that we need to check whether event buses are present on the deployment region and if they are, import them to CDK to not create them twice as this causes conflict (and we cannot create separate buses for every environment because we reach hard quota for them with only 2 envs). If there are no needed buses we create them. 

Issue begins with how to check for existing buses: we used boto3 to check for those, but when using CodePipeline we would need to use some workarounds to perform cross-account deployments. We tried to use aws_events.EventBus.from_event_bus_arn() function, but unfortunately when there are no resources that match specified ARN, CDK "imports" them as if they are present, so when CloudFormation template is generated, those resources are not specified there and are not created. There's no exception or null value returned by that function, so there's no way for us to tell whether to create or not the needed resource.

This is how we try to import existing resource and create it if it's not present:

```{.py}
           event_bus = None
            try:
                event_bus = aws_events.EventBus.from_event_bus_arn(id=f"{environment_name}_event_bus", event_bus_arn=f"arn:aws:events:{REGION_NAME}:{ACCOUNT}:event-bus/{event_bus_name}", scope=self)
            except Exception as e:
                event_bus = None
            if not event_bus:
                event_bus = aws_events.EventBus(self, f"event_bus_{environment_name}", event_bus_name=event_bus_name)
```

I don't think this is expected behavior, but please correct me if I'm wrong.

### Expected Behavior

aws_events.EventBus.from_event_bus_arn() returns None or throws an exception when there's no resource to be imported

### Current Behavior

aws_events.EventBus.from_event_bus_arn() continues normally when there's no resource to be imported

### Reproduction Steps

Try to import non-existent event bus using aws_events.EventBus.from_event_bus_arn()

### CDK CLI Version

2.37.1 (build f15dee0)

### Node.js Version

v16.16.0

### OS

Ubuntu 20.04 LTS

### Language

Python

### Language Version

Python 3.8.10

**Comment by peterwoodworth** [comment]
The CDK doesn't do any checks when doing basic imports, it assumes you've passed in values that are accurate to an existing resource. If you need to verify that a resource actually exists during synth time, I'm not sure there's a great way to do that. I think better methods would be dynamically passing in values as parameters, or dynamically retrieving existing values during deploy time with a custom resource

**Comment by nixenos** [comment]
Ah okay, we implemented other solution now, but maybe adding such functionality isn't a bad idea? It for sure would make easier to make such deployments and be less confusing

**Comment by peterwoodworth** [comment]
It takes a lot of effort to implement, test, and maintain new API calls; this is something we do in more special cases when it's useful to grab a wider context of the particular resource. So we almost certainly won't be implementing lookups for event buses since [custom resources](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.custom_resources.AwsCustomResource.html) are perfectly viable options in these cases

Glad you've got it working!
