### ISSUE TITLE
CDK Bootsrap: subprocess exited with error 3221225506

### ISSUE THREAD

**Issue by NoIdeawhatIamdoing123** [aws/aws-cdk#21757]
### Describe the bug

I've got no idea what the bug is, someone would have to investigate the code to understand.

### Expected Behavior

I would not expect an error, but if I did get one then it needs to be useful

### Current Behavior

subprocess exited with error 3221225506

### Reproduction Steps

cdk bootstrap --profile {Profile Name}

### CDK CLI Version

2.38.1 (build a5ced21)

### Framework Version

No idea, would be good to have instructions

### Node.js Version

No idea, would be good to have instructions

### OS

Windows

### Language

.NET

### Language Version

running cdk boostrap, so assume fully aws code?

### Other information

The error is all that is returned

**Comment by peterwoodworth** [comment]
Hey, I've never seen this error before, and it's not the type of error we throw in CDK. I did a google of this error message and it seems to be related to Windows OS, not specifically to cdk. I recommend installing the latest updates for your machine if you haven't already. Beyond that, unfortunately I don't think there's much we can do to help.

Ping me if you have reason to suspect this is related to CDK
