### ISSUE TITLE
(aws-ec2): ClientVpnEndpoint not recognizing tag_specifications argument

### ISSUE THREAD

**Issue by juweeks** [aws/aws-cdk#21755]
### Describe the bug

getting unexpected keyword argument error when adding tag_specifications to ec2.ClientVpnEndpoint

### Expected Behavior

tags created on vpn endpoint

### Current Behavior

`TypeError: __init__() got an unexpected keyword argument 'tag_specifications'`

### Reproduction Steps

create client vpn endpoint with tag_specifications 

### CDK CLI Version

2.38.1 (build a5ced21)

### Node.js Version

16.15.1

### OS

macOS v12.4

### Language

Python

### Language Version

3.8.9

**Comment by corymhall** [comment]
@juweeks can you please add some code that we can use to reproduce?

**Comment by juweeks** [comment]
looks like the `tag_specifications` property was removed from documentation for v2.39.0. Which would make that kwarg missing error make sense if it wasn't yet implemented. Closing.
