### ISSUE TITLE
[AWS EKS]: CDK Support for Helm Values File for EKS Helm Charts

### ISSUE THREAD

**Issue by blakeromano** [aws/aws-cdk#21766]
### Describe the feature

I'd like to see it where instead of being forced in AWS CDK to specify values in an object like this 

```typescript
eksCluster.addHelmChart("kiam", {
      chart: "kiam",
      repository: "https://uswitch.github.io/kiam-helm-charts/charts/",
      namespace: "kube-system",
      release: "kiam",
      values: {
        "agent.host.iptables": true,
        "agent.host.interface": "!eth0",
        "agent.host.port": 8881,
        "agent.prometheus.servicemonitor.enabled": false,
        "agent.image.tag": "v4.0",
        "agent.resources.limits.cpu": "1000m",
        "agent.resources.requests.cpu": "200m",
        "agent.allowRouteRegexp": ".*",
        "server.deployment.enabled": true,
      }
```

That I could have an additional field to the Helm Chart Options called `valueFile` Where I could point it at a relative directory to where I am. For example
```typescript
eksCluster.addHelmChart("kiam", {
      chart: "kiam",
      repository: "https://uswitch.github.io/kiam-helm-charts/charts/",
      namespace: "kube-system",
      release: "kiam",
      valueFile: "../kiam/values.yaml"
 }
```

Where it would use the values in that specified file to deploy the helm chart.

### Use Case

I am super frustrated that I have to do a work around to either read a yaml file and parse it into the proper syntax or have a massive object specifying all the values.

### Proposed Solution

Please read above

### Other Information

The other option would be to allow me to read a yaml file for example

```yaml
foo:
  bar:
    thing:
      - "test"
      - "anotherTest"
```
And pass that instead of having to manually trying to convert that into the dot notation where there is also nuances like if there is a dot within the name of the parameter where I have to escape the dot.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.38.1

### Environment details (OS name and version, etc.)

Any

**Comment by otaviomacedo** [comment]
I may be missing something, but isn't it as easy as:

```ts
eksCluster.addHelmChart("kiam", {
  /*...*/
  values: yaml.parse(path.join(__dirname, "../kiam/values.yaml"))
});
```

**Comment by blakeromano** [comment]
I don't believe that'd work because the yaml.parse would put it into a json object which I don't believe that'd accept. Regardless letting helm deal with the parsing by just providing it the file makes the most sense to me.

**Comment by blakeromano** [comment]
For an example that I made.

```typescript
const YAML = require('yaml')
const path = require("path");
const fs = require("fs");

const file = fs.readFileSync(path.join(__dirname, "./test.yaml"), "utf8");
const data = YAML.parse(file);

console.log(data);
```
and with a test.yaml being
```yaml
foo:
  bar:
    thing:
      - "test"
      - "anotherTest"
```
That logs this out to the console.

```
{ foo: { bar: { thing: [Array] } } }
```

**Comment by blakeromano** [comment]
Any update on this? @otaviomacedo

**Comment by otaviomacedo** [comment]
Let's assume a scenario in which you already had the values in memory, in a JavaScript object. You would be able to pass those values to `addHelmChart` using the `values` property, wouldn't you? That's exactly what this property is for.

Now, you don't have them in memory; they are in a file. But you can load the file in memory and parse it, to get to the scenario above.

Again, I may be missing something obvious (happens a lot), but have you tried deploying it this way?

**Comment by blakeromano** [comment]
I was mistaken that did work. Thank you 😵‍💫
