### ISSUE TITLE
(aws-codepipeline): Pipeline tries to mutate cross-account roles 

### ISSUE THREAD

**Issue by rantoniuk** [aws/aws-cdk#21760]
### Describe the bug

When a pipeline is created like this:

```ts

   this.pipeline = new Pipeline(this, "TestPipeline", {
      pipelineName: `MyTestPipeline`,
      artifactBucket: this.artifactBucket,
      restartExecutionOnUpdate: true,
      role: this.devOpsPipelineRole, // a static role from Role.fromRoleArn()
    });

    const testDeployRole = Role.fromRoleArn(
      this,
      "testRole",
      `arn:aws:iam::${Accounts.TEST}:role/cdk-${DefaultStackSynthesizer.DEFAULT_QUALIFIER}-deploy-role-${Accounts.TEST}-eu-west-1`,
    );

     this.pipeline.addStage({
      stageName: "Deployment-DEV",
      actions: [
        new CloudFormationCreateUpdateStackAction({
          runOrder: 1,
          actionName: "DeployCF",
          stackName: "TestStack",
          adminPermissions: false,
          role: testDeployRole, 
          deploymentRole: testCfnExecRole, 
          templatePath: build.artifact.atPath("TestStack.template.json"),
          cfnCapabilities: [CfnCapabilities.NAMED_IAM, CfnCapabilities.AUTO_EXPAND],
        }),
      ],
    });

```

When doing `cdk deploy`, error is thrown that:

```
 The stack named PipelineStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: The role with name cdk-hnb659fds-deploy-role-XXX-eu-west-1 cannot be found.
```

Where XXX is the _target_ account role. This is obviously wrong and is visible in the generated CF template, that it tries to add policies to a role in the target deployment account which it does not permission to do - since deployment of the pipeline is done in the pipeline dedicated account.

If `{ mutable: false}` is added, then problem is fixed - it looks like there is a missing condition which should not try to modify cross-account roles that are passed as `CloudFormationCreateUpdateStackAction` arguments.

### Expected Behavior

As above

### Current Behavior

Exception is thrown during deployment.

### Reproduction Steps

As above.

### CDK CLI Version

2.38.1

### Node.js Version

14

### OS

MacOS

### Language

Typescript

**Comment by indrora** [comment]
This is by design. The CDK will attempt to add the permissions it needs in order to complete the requested actions. Importing roles via `FromRoleArn` implies you can modify that role.

You're correct that `immutable` is the setting you want if you want the CDK to not touch the role.
