### ISSUE TITLE
apigatewayv2: HttpLambdaAuthorizer doesn't grant permission to invoke Lambda

### ISSUE THREAD

**Issue by BorntraegerMarc** [aws/aws-cdk#21775]
### Describe the bug

When adding a `HttpLambdaAuthorizer` then the API Gateway is not automatically granted invoke permission for that Lambda. Makes the integration not very useful.

### Expected Behavior

CDK should automatically grant permission to API Gateway to invoke the referenced Lambda.

### Current Behavior

<img width="1175" alt="Screen Shot 2022-08-26 at 11 49 04" src="https://user-images.githubusercontent.com/7549295/186877845-401884a6-1c61-4292-a30f-9d75ba4fd4a6.png">

### Reproduction Steps

```js
const httpApi = new HttpApi(this, "MyAPI");

const getProtectedResourceFunction = new Function(this, "getProtectedResource", {
  functionName: "getProtectedResource",
  handler: "index.handler",
  runtime: Runtime.NODEJS_16_X,
  architecture: Architecture.ARM_64,
  code: new InlineCode(`
exports.handler = () => {
  return {
    statusCode: 200,
    body: JSON.stringify("Hello from Lambda!"),
  }; 
};`),
});

const oAuth2AuthorizerFunction = new Function(this, "oAuth2Authorizer", {
  functionName: "oAuth2Authorizer",
  runtime: Runtime.NODEJS_16_X,
  architecture: Architecture.ARM_64,
  handler: "index.handler",
  code: Code.fromAsset(path.join(__dirname, "../src/oAuth2Authorizer")),
});

httpApi.addRoutes({
  path: "/",
  methods: [HttpMethod.GET],
  integration: new HttpLambdaIntegration("getProtectedResource", getProtectedResourceFunction),
  authorizer: new HttpLambdaAuthorizer("oAuth2Authorizer", oAuth2AuthorizerFunction, {
    responseTypes: [HttpLambdaResponseType.SIMPLE],
  }),
});
```

### Additional Information/Context

Any workaround would be appreciated

### CDK CLI Version

2.38.1 (build a5ced21)

### Node.js Version

16.x.x

### OS

MacOS

### Language

Typescript

### Language Version

~3.9.7

**Comment by BorntraegerMarc** [comment]
Never mind... I re-created the Stack and now it works...

**Comment by timturnerwhcc** [comment]
@otaviomacedo I'm able to reproduce this with the 2.81.0 (build bd920f2) CDK still. I would expect [this code](https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/aws-apigatewayv2-authorizers-alpha/lib/http/lambda.ts#L106-L115) to set up the permissions as we expect, but I don't see a Resource Policy created on my authorizer lambda as I would expect.

**Comment by peterwoodworth** [comment]
You can set the `sameEnvironment` prop when importing [`fromFunctionAttributes()`](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda.FunctionAttributes.html#sameenvironment) to manually enable the ability to create permissions. This only works if the Lambda actually is in the same account, otherwise, that doesn't seem to be supported by the service.
