### ISSUE TITLE
S3 Logging not exposed

### ISSUE THREAD

**Issue by gaffo** [aws/aws-cdk#2177]
Not sure if this is being tracked or if I'm just missing the setting. I see the logging configuration in the CFN layer. I don't see any TODOs on s3

**Comment by eduardohki** [comment]
I'm also with the same need, using Python here.

**Comment by cmckni3** [comment]
Was this solved in https://github.com/aws/aws-cdk/pull/5072 @SomayaB?

**Comment by iliapolo** [comment]
@cmckni3 [S3 Bucket Logging Configuration](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-loggingconfig.html) was indeed added as part of https://github.com/aws/aws-cdk/pull/5072.

If this is what you meant when opening this issue, it should be available. 

Can you share the non-working python code you are using? We might have to turn this issue to a `bug` :)

**Comment by cmckni3** [comment]
I’ll leave that to @gaffo.

I am using TypeScript with CDK 1.19.0 for projects right now.

**Comment by SomayaB** [comment]
@gaffo @eduardohki Are you still experiencing this issue?

**Comment by SomayaB** [comment]
Closing for now since there hasn't been a response in a while. Feel free to reopen.
