### ISSUE TITLE
DnsValidatedCertificate: Cap domainName to 64 Characters at Compile Time

### ISSUE THREAD

**Issue by cowsandmilk** [aws/aws-cdk#21777]
### Describe the feature

If you provide a domainName that is longer than 64 characters, DnsValidatedCertificate will fail to create the certificate.

This is documented in https://docs.aws.amazon.com/acm/latest/APIReference/API_RequestCertificate.html (technically, the limit is 64 octets. The limit actually comes from [RFC 5280](https://www.rfc-editor.org/rfc/rfc5280), so it is not expected to change.

Pain can be removed by having this check as part of cdk build rather than occurring when the lambda function calls the RequestCertificate API.

### Use Case

I've been caught by this in adding more verbose subdomains and not seeing the issue until the cloudformation deploy.

### Proposed Solution

throw an error if the length is too long. There is probably also a minimum length that can be checked.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.31.2

### Environment details (OS name and version, etc.)

N/A

**Comment by peterwoodworth** [comment]
Thanks for the feature request, this is something that would be pretty simple to check. Adding a line here https://github.com/aws/aws-cdk/blob/4303dca8ab1f690147d6a64d333118ac90297035/packages/%40aws-cdk/aws-certificatemanager/lib/dns-validated-certificate.ts#L88 
and around here https://github.com/aws/aws-cdk/blob/4303dca8ab1f690147d6a64d333118ac90297035/packages/%40aws-cdk/aws-certificatemanager/lib/certificate.ts#L214
to check for the length provided should work just fine

We accept contributions! Check out our [contributing guide](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) if you're interested - there's a low chance the team will be able to address this soon but we'd be happy to review a PR 🙂

**Comment by josephedward** [comment]
Hey @peterwoodworth could you check and see if this PR (https://github.com/aws/aws-cdk/pull/21807) is sufficient? Still somewhat new to contributing here so I wasn't certain how to classify, I included tests for each module (certificate and dns-validated-certificate) but I'm not certain if they need to be modified.

**Comment by peterwoodworth** [comment]
closed by pr merge #21807
