### ISSUE TITLE
pipelines: wrong runOrder for Arbitrary CodePipeline action

### ISSUE THREAD

**Issue by bmmin** [aws/aws-cdk#21784]
### Describe the bug

When adding an [Arbitrary CodePipeline action](https://docs.aws.amazon.com/cdk/api/v1/docs/pipelines-readme.html#arbitrary-codepipeline-actions) in a stage, the runOrder is incorrectly calculated.

### Expected Behavior

Step is placed in the correct spot within the stage. (runOrder=4)

### Current Behavior

runOrder is set to 1.

### Reproduction Steps

Below is  `pipelines.ts`.
you need `aws-cdk@1`, `ts-node`, `monocdk` and `typescript`.
Run 
`npx cdk --app "ts-node pipeline.ts" synth`
Then you can see the generated steps with
`jq '.Resources | to_entries[] | select(.value.Type=="AWS::CodePipeline::Pipeline") | .value.Properties.Stages[] | select(.Name=="stage") | .Actions[] | {runOrder:.RunOrder, Name:.Name}' cdk.out/PipelineStack.template.json` 

```typescript
import { Construct, StackProps, Stage, StageProps } from "monocdk";
import { Stack } from "monocdk";
import { Repository } from "monocdk/aws-codecommit";
import { IStage } from "monocdk/lib/aws-codepipeline";
import { ManualApprovalAction } from "monocdk/lib/aws-codepipeline-actions";
import { CodeBuildStep, CodePipeline, CodePipelineActionFactoryResult, CodePipelineSource, ICodePipelineActionFactory, ProduceActionOptions, StackSteps, Step } from "monocdk/pipelines";
import { App } from "monocdk";


class PipelineStack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);
    const repoInput = CodePipelineSource.codeCommit(Repository.fromRepositoryName(this, "Repository", "repo"), "mainline");
    const synthStep = new CodeBuildStep("Synth", {
      installCommands: [],
      commands: [],
      input: repoInput,
    });

    const pipeline = new CodePipeline(this, "Pipeline", {
      pipelineName: "Repro",
      synth: synthStep,
      crossAccountKeys: true,
    });

    const wave = pipeline.addWave("test");
    const stage = new TestStage(this, "stage");
    wave.addStage(stage, { stackSteps: stage.steps });
  }
}

class TestStage extends Stage {
    public steps: StackSteps[];
    constructor(scope: Construct, id: string, props?: StageProps) {
        super(scope, id, props);
        const be = new BeStack(this, "be");
        const integTests = new CodeBuildStep("integTests", { commands: ["echo test"] });
        const e2eTests = new CodeBuildStep("e2eTests", { commands: ["echo test"] });
        const fe = new FeStack(this, "fe");
        const customFeDeployment = new CustomFeDeploymentStep(scope, "customFeDeployment");
        //const customFeDeployment = new CodeBuildStep("customFeDeployment", { commands: ["echo test"] });
        this.steps = [
            {stack: be, post: [integTests, e2eTests]},
            { stack: fe, post: [customFeDeployment]}
        ];
        customFeDeployment.addStepDependency(integTests);
        e2eTests.addStepDependency(customFeDeployment);
    }    
}

class CustomFeDeploymentStep extends Step implements ICodePipelineActionFactory {
    constructor(scope: Construct, id: string) {
        super(id);
        this.discoverReferencedOutputs({ });
    }

    produceAction(stage: IStage, options: ProduceActionOptions): CodePipelineActionFactoryResult {
        stage.addAction(new ManualApprovalAction({actionName: "customFeDeployment" })); // anything
        return { runOrdersConsumed: 1 };
    }
}

class BeStack extends Stack {
    constructor(scope: Construct, id: string, props?: StackProps) {
        super(scope, id, props);
    }
}

class FeStack extends Stack {
    constructor(scope: Construct, id: string, props?: StackProps) {
        super(scope, id, props);
    }
}

const app = new App();
new PipelineStack(app, "PipelineStack");
app.synth();
```

### Possible Solution

Interestingly, if I use a CodeBuildStep, the runOrder is correct. Just swap the comments on the 2 lines with `const customFeDeployment=`

### Additional Information/Context

I have a stage, a frontend and a backend stack. Backend stack is validated by integ and end to end tests. Frontend stack just deploys some code to s3. I have a custom step (here just a manual action, but it is a step functions workflow actually) that does the actual front end deployment. I want to deploy frontend once backend passes integ tests, then run e2e tests with the new frontend.

### CDK CLI Version

1.169.0

### Node.js Version

v16.15.1

### OS

macOs 12.5.1

### Language

Typescript

### Language Version

TypeScript  (4.7.4)

**Comment by peterwoodworth** [comment]
Thanks for the reproduction code and for the bug report, I've been able to reproduce this. However, I'm not super sure why this is occurring, I'm suspicious of this function though 🤔 https://github.com/aws/aws-cdk/blob/e36bfe5fe17d8e4e4a31903c95c9482346cf99ba/packages/%40aws-cdk/pipelines/lib/codepipeline/codepipeline.ts#L414

**Comment by bmmin** [comment]
Hmm, based on the link you provided, it seems that CodeBuildAction [sets the runorder](https://github.com/aws/aws-cdk/blob/e36bfe5fe17d8e4e4a31903c95c9482346cf99ba/packages/%40aws-cdk/pipelines/lib/codepipeline/private/codebuild-factory.ts#L346) inside the createAction. Doing the same for the given example also works. Looking back at the example, it does mention to copy over the runorder and the name from the options. I missed that since I did not want to do a Jenkins Step, so deleted that part straight away. My bad, sorry for the time wasted on me not rtfm :(
