### ISSUE TITLE
(EMR): (Allow loading configuration json from s3)

### ISSUE THREAD

**Issue by rwmason** [aws/aws-cdk#21783]
### Describe the feature

When creating an EMR cluster through the AWS EMR console, it is possible through the advanced configuration setting to load in a configuration JSON file from s3 (Shown in screenshot)
![Screen Shot 2022-08-26 at 12 05 00 PM](https://user-images.githubusercontent.com/97305823/186956891-052a82e6-7504-4e10-b6c1-a0dbf4624f7e.png)

In CDK (and CFN as well since EMR currently only has L1 constructs), there is no option to load this file from s3, instead the configuration settings need to be hard-coded. There aren't any L2 constructs yet for EMR in CDK, so this FR would be to have this feature present in in the L2 constructs whenever they are released

### Use Case

The purpose of this FR to to help bring the functionality for creating and configuring EMR resources in-parity with what can be done through the CLI or the Console.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.38.0

### Environment details (OS name and version, etc.)

N/A

**Comment by peterwoodworth** [comment]
We won't be able to support this if it isn't supported on the CloudFormation resource. I recommend creating an issue on the [CloudFormation coverage roadmap](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues) if one doesn't already exist for this request.

Additionally, if you would like to see an L2 for EMR, we will need an [approved RFC](https://github.com/aws/aws-cdk-rfcs) before development can begin
