### ISSUE TITLE
ShellStepProps: Support for Secrets Manager environment variables

### ISSUE THREAD

**Issue by mikelhamer** [aws/aws-cdk#21796]
### Describe the feature

Currently when specifying environment variables for an AWS CDK Pipeline ShellStep I only see the option to specify `env: Record<string, string>` values, which get translated to PLAINTEXT environment variables in CodeBuild.

I would like a way to define Secrets Manager environment variables

### Use Case

Passing sensitive info such as passwords, keys, etc.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.31

### Environment details (OS name and version, etc.)

Linux

**Comment by gshpychka** [comment]
`ShellStep` is an abstraction that has to support various backends, not just AWS CodeBuild and/or Secrets Manager. If you want AWS-specific features, you can use a less abstract `CodeBuildStep`, it includes this functionality.

**Comment by mikelhamer** [comment]
> `ShellStep` is an abstraction that has to support various backends, not just AWS CodeBuild and/or Secrets Manager. If you want AWS-specific features, you can use a less abstract `CodeBuildStep`, it includes this functionality.

Wow, I had no idea. Thank you!!!
