### ISSUE TITLE
(iam): policy statement action is not validated if added post instantiation 

### ISSUE THREAD

**Issue by iliapolo** [aws/aws-cdk#21821]
### Describe the bug

There is inconsistent behavior between construction and post construction API's of the `PolicyStatement` class.

```ts
new iam.PolicyStatement({ resources: ['*'], actions: ['DescribeDBLogFiles'] });
``` 

The code above throws an error: `Action 'DescribeDBLogFiles' is invalid. An action string consists of a service namespace, a colon, and the name of an action. Action names can include wildcards.` This is expected because the action is missing the `rds:` prefix.

This code however, does not throw an error and synthesizes an invalid template:

```ts
const statement = new iam.PolicyStatement({ resources: ['*'] });
statement.addActions('DescribeDBLogFiles');
```

### Expected Behavior

The `addActions` method should throw the same error as the constructor given the same input.

### Current Behavior

The `addActions` method allows adding invalid statements

### Reproduction Steps

Reproduction code provided above

### Possible Solution

Move the validation logic to the `addActions` method. 

### CDK CLI Version

2.35.0 (build 5c23578)

### Framework Version

2.35.0

### Node.js Version

v14.18.1

### OS

Mac OS Mojave

### Language

Typescript, Python, .NET, Java, Go

**Comment by peterwoodworth** [comment]
Should also do this for `addNotActions` as well https://github.com/aws/aws-cdk/blob/56ba2ab2c2d9240b76ece17c3296488a63f0b232/packages/%40aws-cdk/aws-iam/lib/policy-statement.ts#L90-L101

**Comment by VarunWachaspati** [comment]
Raised [a PR](https://github.com/aws/aws-cdk/pull/21906) #21906 trying to fix this issue. 
But need some guidance in fixing the following unit test which is failing in the above PR #21906.

https://github.com/aws/aws-cdk/blob/1a37331cbdaf19937369b42c7e5cd72270f28993/packages/%40aws-cdk/aws-iam/test/policy-document.test.ts#L324-L336

As per my understanding, `Lazy.list(...)` token should evaluate to `true` when passed to `cdk.Token.isUnresolved()`, but for some unknown reason it is evaluating to `false` instead. Thus causing the above unit test to fail.
https://github.com/aws/aws-cdk/blob/1a37331cbdaf19937369b42c7e5cd72270f28993/packages/%40aws-cdk/aws-iam/lib/policy-statement.ts#L232

Is this is a bug `Token.isUnresolved()` method by any chance?
