### ISSUE TITLE
aws-kinesis Stream: StreamModeDetails is set even when not specified

### ISSUE THREAD

**Issue by nagmesh** [aws/aws-cdk#21829]
### Describe the bug

This is my Kinesis Stream
```
const logsKinesisStream = new cdk.aws_kinesis.Stream(this, 'KinesisStream', {
      retentionPeriod: cdk.Duration.days(1),
      shardCount: 1,
    });
```
When I synth out the template, it gives
```
"KinesisStream46752A3E": {
   "Type": "AWS::Kinesis::Stream",
   "Properties": {
    "RetentionPeriodHours": 24,
    "ShardCount": 1,
    "StreamEncryption": {
     "Fn::If": [
      "AwsCdkKinesisEncryptedStreamsUnsupportedRegions",
      {
       "Ref": "AWS::NoValue"
      },
      {
       "EncryptionType": "KMS",
       "KeyId": "alias/aws/kinesis"
      }
     ]
    },
    "StreamModeDetails": {
     "StreamMode": "PROVISIONED"
    }
   }
  }
  ```

### Expected Behavior

Since `StreamModeDetails` is optional, I expected that `StreamMode` will not be defined or used.

### Current Behavior

`StreamModeDetails` and `StreamMode` show up on the synthesized template

### Reproduction Steps

In any sample CDK typescript app, add this code block and synth it out

```
new cdk.aws_kinesis.Stream(this, 'KinesisStream', {
      retentionPeriod: cdk.Duration.days(1),
      shardCount: 1,
    });
```

### Possible Solution

Do not specify `StreamModeDetails` and `StreamMode` if its not specified in the CDK construct.

### Additional Information/Context

There are regions outside standard AWS partitions where `StreamModeDetails` and `StreamMode`  are not available. This feature parity breaks the deployments with  error

```
Encountered unsupported property StreamModeDetails
```

We can L1 construct or escape hatch for now but a simpler solution would be to not include these key values when `cdk synth ` is run.

### CDK CLI Version

2.28

### Node.js Version

14

### OS

macOS

### Language

Typescript

### Language Version

4.5.2

**Comment by peterwoodworth** [comment]
[Our documentation](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-kinesis.Stream.html#streammode) states that this will be the default, so it's not unexpected to see this in synthesis. However, if you use an escape hatch to remove this property you can see in the console that the default of a Stream is still `provisioned`, so defining this by default seems to be unnecessary.

We accept contributions! Check out our [contributing guide](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) if you're interested - there's a low chance the team will be able to address this soon but we'd be happy to review a PR 🙂

This is where the code will need to change https://github.com/aws/aws-cdk/blob/f188fac89f0c73ab636bb0c5a35f949f340a4e94/packages/%40aws-cdk/aws-kinesis/lib/stream.ts#L759
