### ISSUE TITLE
DynamoDB: Import table from S3

### ISSUE THREAD

**Issue by LeeroyHannigan** [aws/aws-cdk#21825]
### Describe the feature

To import data into DynamoDB, your data must be in an Amazon S3 bucket in CSV, DynamoDB JSON, or Amazon Ion format. Data can be compressed in ZSTD or GZIP format, or can be directly imported in uncompressed form. Source data can either be a single Amazon S3 object or multiple Amazon S3 objects that use the same prefix.

[CFN ImportSpecification](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html#cfn-dynamodb-table-importsourcespecification)

[DynamoDB S3DataImport](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/S3DataImport.HowItWorks.html)

### Use Case

Feature parity with CFN for newly created feature.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.38.1

### Environment details (OS name and version, etc.)

Mac OS 12.5

**Comment by LeeroyHannigan** [comment]
This issue can be assigned to me, will work on adding the feature.

**Comment by jarnohenneman** [comment]
Any process been made on this?

**Comment by LeeroyHannigan** [comment]
Currently running tests. Should be pushed by end of the month.

**Comment by jarnohenneman** [comment]
Morning @LeeroyHannigan. Any update for us?

**Comment by jarnohenneman** [comment]
@LeeroyHannigan apologies for the second ping on this. Any update on the release for this?

**Comment by upstartjohnvandivier** [comment]
@peterwoodworth @LeeroyHannigan any update?

**Comment by jeremyforan** [comment]
.................any updates? I am asking for @jarnohenneman......and myself.

**Comment by sakurai-ryo** [comment]
I'll take this.
