### ISSUE TITLE
aws_cognito: Client has write permissions for customAttribute even if the list is empty

### ISSUE THREAD

**Issue by miquelvir** [aws/aws-cdk#21835]
### Describe the bug

I create a user pool with a custom attribute. I create a client and specify the WriteAttributes (without including the custom attribute). The client is created with write access to the custom attribute.

### Expected Behavior

The client is created without write access to the custom attribute.

### Current Behavior

The client is created without write access to the custom attribute.

### Reproduction Steps

```
/* COGNITO USER POOL */
    const userPool = new cognito.UserPool(this, 'UserPool'), {
      userPoolName: 'UserPool',
      selfSignUpEnabled: false,
      autoVerify: {
        email: true,
      },
      standardAttributes: {
        
      },
      customAttributes: {
        centerId: new cognito.StringAttribute({ mutable: true, minLen: 36, maxLen: 36 })
      },
      passwordPolicy: {
        minLength: 6,
        requireLowercase: true,
        requireDigits: true,
        requireUppercase: false,
        requireSymbols: false,
      },
      accountRecovery: cognito.AccountRecovery.EMAIL_ONLY,
      removalPolicy: isDev? RemovalPolicy.DESTROY: RemovalPolicy.RETAIN,
    });

    const clientWriteAttributes = (new cognito.ClientAttributes()).withStandardAttributes({ username: true });  // todo not working must manually remove edit privileges
    const clientReadAttributes = (new cognito.ClientAttributes()).withStandardAttributes({ username: true, email: true, emailVerified: true }).withCustomAttributes('centerId');

    const client = userPool.addClient('app-client', {
      readAttributes: clientReadAttributes,
      writeAttributes: clientWriteAttributes,
      supportedIdentityProviders: [
        cognito.UserPoolClientIdentityProvider.COGNITO,
      ],
    });
```

### CDK CLI Version

2.39.0 (build e36bfe5)

### Node.js Version

v16.16.0

### OS

Ubuntu (WSL)

### Language

Typescript

**Comment by peterwoodworth** [comment]
We don't have a property `username` [that you can use in `withStandardAttributes({})`](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_cognito.StandardAttributesMask.html), I'm surprised you're not running into runtime errors here. If you remove the username prop, or rename it to something else, does this work? It seems to output a valid template for me with the appropriate options set

**Comment by miquelvir** [comment]
I removed the username property and nothing changed (reproduced the same bug) To be clear, the producer CF is correct (empty WriteAttributes list):

```
"ReadAttributes": [
     "custom:centerId",
     "email",
     "email_verified"
    ],
    "WriteAttributes": []
```

But the client is still created with write access:
![image](https://user-images.githubusercontent.com/41950283/187612526-1e024ff6-a263-49aa-833f-9372fa37e8e1.png)

**Comment by peterwoodworth** [comment]
I am unable to reproduce this still @miquelvir, my console shows that my client has no write access if I specify no properties, and also if I don't specify the `writeAttributes` prop at all on `addClient`.

**Comment by peterwoodworth** [comment]
Actually I just tried switching to the "new console", and the new console displays that all the attributes are writable except email_verified and phone_verified. This is likely a bug in cognito's new console, but the underlying functionality should be that the attributes are not writable

**Comment by miquelvir** [comment]
True! For future reference, I have created a bug in the new client UI for them to check it.

**Comment by peterwoodworth** [comment]
Thanks a bunch @miquelvir!
