### ISSUE TITLE
(assets): support drop-in docker replacements

### ISSUE THREAD

**Issue by misterjoshua** [aws/aws-cdk#21836]
### Describe the feature

I'd like the ability to change the docker command used when building/publishing assets.

### Use Case

I'd like to use [Depot](https://depot.dev/)'s Docker shim as a drop-in replacement for the `docker` command so I can take advantage of their faster docker builds.

### Proposed Solution

We could obtain a user-specified override from an environment variable named `CDK_DOCKER` here:

https://github.com/aws/aws-cdk/blob/7472fa484e45cc5dd05c10e4998c02d28f60da65/packages/cdk-assets/lib/private/docker.ts#L134

Environment variables would be nice because these are easy to add to the build/deploy environment without changing customers' apps. There's precedence for this in core with `CDK_DOCKER`, but that environment variable only applies to bundling and not to docker image asset builds/publishing.

https://github.com/aws/aws-cdk/blob/3e55092fb70e0ec74ee7c4144d6e39a29d8757ae/packages/%40aws-cdk/core/lib/bundling.ts#L523

### Other Information

I've attempted to add this feature in #21838

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

N/A

### Environment details (OS name and version, etc.)

Linux

**Comment by peterwoodworth** [comment]
Thanks for the pr @misterjoshua, someone from the team will try to take a look soon 🙂
