### ISSUE TITLE
(lambda_nodejs): Allow passing parameter store values to bundling environment variables

### ISSUE THREAD

**Issue by drodil** [aws/aws-cdk#21845]
### Describe the feature

When creating bundling with lambda_nodejs the only way to pass environment variables is through key-value pairs (strings). If you need to add a SecureString value as environment variable (for example npm_config__auth) it's not possible except by using the CodeBuild environment variables through process.env. For example

```js
new lambda_nodejs.NodejsFunction(this, 'my-lambda', {
  entry: 'src.ts',
  bundling: {
    environment: {
      'npm_config_registry': process.env.NPM_CONFIG_REGISTRY ?? '',
      'npm_config__auth': process.env.NPM_CONFIG__AUTH ?? '',
    },
  }
});
```

### Use Case

I'm frustrated that I cannot pass ParameterStore secure values to bundling container that would work both locally and in CodeBuild during the synth without adding additional environment variables locally.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.39.1

### Environment details (OS name and version, etc.)

macOS 12.5

**Comment by corymhall** [comment]
@drodil are you saying that you want to be able to pass in a reference to a ssm parameter instead of an environment variable and the CDK should automatically look it up?

something like this?
```ts
new lambda_nodejs.NodejsFunction(this, 'my-lambda', {
  entry: 'src.ts',
  bundling: {
    environment: {
      'npm_config_registry': fromSSMParam('npmconfig'),
      ...
    },
  }
});
```

**Comment by drodil** [comment]
@corymhall yes exactly. If using string values from SSM it can be done with https://docs.aws.amazon.com/cdk/v2/guide/get_ssm_value.html but for secret strings it's more complicated but sometimes necessary like in this case. After thinking this over night, I am not sure if this is after all good idea security wise but would make it more usable.
