### ISSUE TITLE
aws-apigateway: The resource policy does not get deleted correctly

### ISSUE THREAD

**Issue by LamarrD** [aws/aws-cdk#21840]
### Describe the bug

When an API Gateway with a resource policy is deployed with cdk, and then the resource policy _code_ is removed, the actual resource policy is not removed.

### Expected Behavior

The expected behavior is that when the resource policy is deleted in the code, it is also removed from the API Gateway resource.

### Current Behavior

The actual behavior is that the resource policy stays.

### Reproduction Steps

Below is a produceable example:

1. Deploy the stack with the `policy`.
2. View the api in the API Gateway console and confirm that it does have the resource policy.
3. Remove the `policy` and re-deploy.
4. Examine the resource policy in AWS and you'll see that the resource policy remains unchanged.

lib/stack.js
```
const { Stack, Duration } = require("aws-cdk-lib");
const apigateway = require("aws-cdk-lib/aws-apigateway");
const lambda = require("aws-cdk-lib/aws-lambda");
const iam = require("aws-cdk-lib/aws-iam");

class ApigwTestStack extends Stack {
  /**
   *
   * @param {Construct} scope
   * @param {string} id
   * @param {StackProps=} props
   */
  constructor(scope, id, props) {
    super(scope, id, props);
    const api = new apigateway.RestApi(this, "testApi", {
      cloudWatchRole: false,
      deployOptions: {},
      policy: new iam.PolicyDocument({
        statements: [
          // Substrate Dev and Substrate Prod
          new iam.PolicyStatement({
            actions: ["execute-api:Invoke"],
            resources: [`arn:aws:execute-api:us-east-1:*:*/*/*`],
          }),
        ],
      }),
    });

    const testLambda = new lambda.Function(this, "testLambda", {
      code: lambda.Code.fromAsset("./src"),
      functionName: "lambdaNode",
      handler: "index.handler",
      memorySize: 1024,
      runtime: lambda.Runtime.NODEJS_14_X,
      timeout: Duration.seconds(300),
    });
    const testLambdaIntegration = new apigateway.LambdaIntegration(testLambda);
    const testLambdaResource = api.root.addResource("test");
    testLambdaResource.addMethod("GET", testLambdaIntegration);
  }
}

module.exports = { ApigwTestStack };
```

src/index.js
```
exports.handler = async function (event) {
  return {
    statusCode: 200,
    headers: { "Content-Type": "text/json" },
    body: JSON.stringify({ message: "Hello from my Lambda node!" }),
  };
};
```

### Additional Information/Context

Interestingly, it updates do seem to work, just not deletes.

### CDK CLI Version

2.27.0 (build 8e89048)

### Node.js Version

v14.17.0

### OS

MacOS arm

### Language

Typescript

**Comment by peterwoodworth** [comment]
This is a bug with either CloudFormation or ApiGateway. The output we have in the template is accurate, CloudFormation just isn't updating the actual policy. Do you have premium support so that you can raise this issue with those services? If not, you could try creating an issue on the [CloudFormation Coverage Roadmap](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues). 

Another thing I've noticed that's interesting is that modifying the policy in the console isn't detectable with CloudFormation drift detection. You can modify the policy however you like, or remove it altogether, without drift being detected

**Comment by LamarrD** [comment]
That makes sense, yes we have Enterprise AWS support and I can raise a request there. Thanks for looking into this 🤝
