### ISSUE TITLE
(aws-cdk): (CDK generates ECR repositories that don't adhere to Security Hub compliance packs)

### ISSUE THREAD

**Issue by meghannoelle** [aws/aws-cdk#21869]
### Describe the bug

CDK provisioned ECR repositories cause the following finding in Security Hub:
`ECR.2 ECR private repositories should have tag immutability configured`
(https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#ecr-2-remediation)

### Expected Behavior

I expected CDK-provisioned ECR repositories to have tag immutability configured by default.

### Current Behavior

CDK-provisioned ECR repositories don't have tag immutability configured and are breaching Security Hub's AWS  foundational security best practices.  

### Reproduction Steps

Deploy an ECR repo and note the new security finding in Security Hub.

### CDK CLI Version

2.35.0 (build 5c23578)

### Node.js Version

v14.18.1

### OS

MacOS

### Language

Typescript

**Comment by peterwoodworth** [comment]
We don't necessarily support Security Hub guidelines by default. [Here's some discussion](https://github.com/aws/aws-cdk-rfcs/issues/25) around potential way we may be able to accomplish this in the future easily, but for now you can configure this with [`imageTagMutability` prop ](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-ecr.Repository.html#imagetagmutability)
