### ISSUE TITLE
aws-events-targets: retryAttempts = 0 does not work as intended

### ISSUE THREAD

**Issue by sunhyung** [aws/aws-cdk#21864]
### Describe the bug

Hi team,

I am working on EventBridge via CDK and got an issue with retryAttempts property.
After creating a rule, I tried to set a target with retryAttempts = 0 but CDK has set retryAttempts as default value instead of 0.

### Expected Behavior

```
      myRule.addTarget(
        new targets.LambdaFunction(myLambda, {
          retryAttempts: 0,
          ...
```
This code should set retryAttempts value as 0.

### Current Behavior

Instead of setting 0, the code set retryAttempts as default value which is 185.

### Reproduction Steps

1. Create a rule.
2. Set a target with retryAttempts = 0.
3. Deploy a stack.

### CDK CLI Version

2.39.1

### Node.js Version

16.13.1

### OS

MS Windows 10

### Language

Typescript

### Language Version

TypeScript (3.9.10)

**Comment by peterwoodworth** [comment]
The culprit is right here https://github.com/aws/aws-cdk/blob/c607ca51be1042f091b4e4419f20bec75863055c/packages/%40aws-cdk/aws-events-targets/lib/util.ts#L54-L59

0 is a falsy value, but still a valid one in this case. Need to account for this

**Comment by peterwoodworth** [comment]
We accept contributions! Check out our [contributing guide](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) if you're interested - there's a low chance the team will be able to address this soon but we'd be happy to review a PR 🙂

**Comment by VarunWachaspati** [comment]
I ran into the same issue few days ago while experimenting with CDK. Raised [a pull request](https://github.com/aws/aws-cdk/pull/21900) #21900 to fix the issue.
