### ISSUE TITLE
neptune: support latest engine major version 1.2

### ISSUE THREAD

**Issue by humanzz** [aws/aws-cdk#21877]
### Describe the feature

AWS Neptune has released a new major version in 1.2 in https://docs.aws.amazon.com/neptune/latest/userguide/engine-releases-1.2.0.0.html which is not supported in [EngineVersion](https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/aws-neptune/lib/cluster.ts#L16) enum.

Additionally, parameters e.g https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/aws-neptune/lib/parameter-group.ts#L84 seems to assume `family: 'neptune1'` without exposing a prop for setting that.

### Use Case

Use the latest MV 1.2 of Neptune

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.38.1

### Environment details (OS name and version, etc.)

macOs

**Comment by peterwoodworth** [comment]
Thanks for the request @humanzz,

We accept contributions! Check out our [contributing guide](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) if you're interested - there's a low chance the team will be able to address this soon but we'd be happy to review a PR 🙂

**Comment by humanzz** [comment]
@peterwoodworth it's ready for a review 😀
