### ISSUE TITLE
(s3): bucket doesn't require SSL requests by default

### ISSUE THREAD

**Issue by dzenana-s** [aws/aws-cdk#21876]
### Describe the bug

CDK deployed S3 buckets result in the following Security Hub finding: `S3.5 S3 buckets should require requests to use Secure Socket Layer`. This leads to many findings existing in Security Hub and not a great way to centralize controlling it. 

### Expected Behavior

S3 buckets created by the CDK to not result in this Security Hub finding. 

### Current Behavior

All S3 buckets created with the CDK automatically result in this Security Hub Finding. 

### Reproduction Steps

- Deploy
```
import * as s3 from 'aws-cdk-lib/aws-s3';
import * as cdk from 'aws-cdk-lib';

export class CdkStarterStack extends cdk.Stack {
  constructor(scope: cdk.App, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const s3Bucket = new s3.Bucket(this, 's3-bucket')
  }
}
```
- Go to Security Hub and see an issue created about SSL not being required for requests made on the S3 bucket

### CDK CLI Version

2.35.0

### Node.js Version

v16.15.1

### OS

MacOS

### Language

Typescript

**Comment by peterwoodworth** [comment]
You can [supply your own bucket policy](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_s3.BucketPolicy.html) as well as [adjust the settings on your bucket with bucketProps](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_s3.BucketProps.html). You should be able to meet security hub standards with some slight configurations

**Comment by iamgabeortiz** [comment]
@peterwoodworth Does that apply to the CDK Toolkit Staging bucket?  Mine has no policy at all and is being flagged by AWS Security Hub.

**Comment by dzenana-s** [comment]
@iamgabeortiz the current template should have the policy attached to the bucket (see https://github.com/aws/aws-cdk/blob/74318c7d22bfc00de9e005f68a0a6aaa58c7db39/packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml#L193). Are you up to date with the latest template? 

There will be some findings in Security Hub from the current template - you can modify the bootstrap template to fulfill the findings you determine valuable.
