### ISSUE TITLE
aws_rds (python): rds.DatabaseInstance.from_database_instance_attributes() doesn't fail

### ISSUE THREAD

**Issue by marcodb-join** [aws/aws-cdk#21875]
### Describe the bug

If you call:
```
rdsInstance = rds.DatabaseInstance.from_database_instance_attributes(self, "rdsInstanceTest",
            instance_endpoint_address="",
            instance_identifier="",
            port=0,
            security_groups=[],
        )
```
(note that the empty strings are as-is in the code, they're not placeholders for some text)

the call succeeds and returns some object. As one might expect, after that call `rdsInstance.vpn` is `None` and `rdsInstance.node.default_child` is `None`.

Is this expected behavior? If so, how should I validate that `rdsInstance` is invalid?

For context, I was trying to create an `rdsInstance` mapped to an existing RDS instance in my AWS account, because I'd need to attached a new (extra) security group to it. I thought I was passing the right arguments, but I kept on getting an object with `rdsInstance.vpn = None` and `rdsInstance.node.default_child = None`. Given the behavior at the top of this section, I can't tell if I'm passing the right arguments and the function is not working, or if I'm passing the wrong arguments.

### Expected Behavior

```
rdsInstance = rds.DatabaseInstance.from_database_instance_attributes(self, "rdsInstanceTest",
            instance_endpoint_address="",
            instance_identifier="",
            port=0,
            security_groups=[],
        )
```
this call should fail, either by setting `rdsInstance = None`, or (preferred) by raising an exception because the requested RDS instance can't be found.

### Current Behavior

```
rdsInstance = rds.DatabaseInstance.from_database_instance_attributes(self, "rdsInstanceTest",
            instance_endpoint_address="",
            instance_identifier="",
            port=0,
            security_groups=[],
        )
```
This call succeeds and leaves me with an `rdsInstance` that I'm not able to use.

The only validation that seems to be in place is the logic to validate that the keyword arguments are present. If you omit one, you'll get an error.

### Reproduction Steps

Call rds.DatabaseInstance.from_database_instance_attributes() with invalid attributes.

### CDK CLI Version

2.39.1

### Node.js Version

v18.7.0

### OS

Ubuntu WSL 22.04

### Language

Python

### Language Version

3.9.13

### Other information

aws-cdk-lib v2.39.1

**Comment by peterwoodworth** [comment]
CDK doesn't actually look up context from your AWS account except with certain methods, usually denoted with the word `lookup` - if you use one of the `fromAttributes`, `fromArn`, `fromXxxName` then no lookup occurs. The user is expected to pass in the information accurately

See [this page](https://docs.aws.amazon.com/cdk/v2/guide/resources.html#resources_referencing) for more info
