### ISSUE TITLE
AWS CDK: Deploying stack via CDK errors with "Not found service catalog product" and there is no issue via deploying with CFT 

### ISSUE THREAD

**Issue by yaminir** [aws/aws-cdk#21871]
### Describe the bug

AWS CDK deploy stack returns the below error even if the product is existing in the service catalog. If deployed via CFT, there is no issue. 

Resource handler returned message: "Product with name KMS CMK not found (Service: ServiceCatalog, Status Code: 400, Request ID: fc35ff40-31ce-4660-8868-78c7fbd026c1)" (RequestToken: 52da828f-ca06-c92a-e314-8a1f3d501e87, HandlerErrorCode: GeneralServiceException)

### Expected Behavior

Expected to find the service catalog product and deploy 

### Current Behavior

Error generated saying the service catalog product is not found

### Reproduction Steps

Deploy via CDK 

### CDK CLI Version

latest

### Node.js Version

latest

### OS

windows 

### Language

Typescript

**Comment by peterwoodworth** [comment]
Can you please provide more information including reproduction code, and more information on your stack contents and what you're trying to achieve?

**Comment by yaminir** [comment]
@peterwoodworth Here is the code: 
const kmsProductConfig =
props!.config.pagerDutyTopicStack.kmsProvisionedProducts[
props?.env!.region!
];
const product = new service_catalog.CfnCloudFormationProvisionedProduct(
this,
`${props!.config.deltaEnvironment}-kms-provisioned-product`,
{
productName: `${kmsProductConfig.productName}`,
// productId: `prod-i4qwdb6qlrmha`,
// pathId: `lpv2-j3t36tvmfiup6`,
// pathName: `Self Service`,
provisionedProductName: `${props!.config.deltaEnvironment}-${
kmsProductConfig.provisionedProductName
}`,
provisioningArtifactId: `${kmsProductConfig.productVersion}`,
provisioningParameters: [
{
key: `KEYNAME`,
value: `${kmsProductConfig.aliasName}`,
},
{
key: `KEYACCESS1`,
value: `${kmsProvisioningRole.roleName}`,
},
{
key: `KEY1PERMISSIONS`,
value: `Both`,
},
{
key: `KEY1GRANT`,
value: `False`,
},
{
key: `SERVICENAME`,
value: `cloudwatch.amazonaws.com`,
},
],
}
);

**Comment by yaminir** [comment]
Basically just need to have a service catalog product that you try to provision. This one is producing a KMS Key
Please let us know the permissions that are needed.

**Comment by peterwoodworth** [comment]
All of our L1 constructs are autogenerated and identical to their respective CloudFormation resources. You'll need to review [CloudFormation docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-servicecatalog-cloudformationprovisionedproduct.html) on this resource and the docs for this service to know how to properly use it and fill out its properties

If you think this is a bug with CDK, please identify the difference between this template and the template you've deployed via CFT.

**Comment by yaminir** [comment]
There is no difference in the template, however it pops up an error. Is there any issue with permissions ?

**Comment by corymhall** [comment]
@yaminir my hunch would be that you are running into permissions issues. Assuming you are using the default CDK setup, when you run `cdk deploy` it will use a `cfn-exec` CloudFormation execution role to provision the product. That role will need to be granted permissions to the Service Catalog product.

On a separate note, you might want to check out [cdk-import](https://github.com/cdklabs/cdk-import) which allows you to generate L1 constructs for Service Catalog products.

**Comment by yaminir** [comment]
Thank you for your inputs, I did validate cfn-exec role permissions and we used the same role permissions to deploy via CFT. To summarize, the permissions policy worked fine via CFT.

**Comment by corymhall** [comment]
@yaminir just to confirm, did you grant the `cfn-exec` role access to the service catalog portfolio? https://docs.aws.amazon.com/servicecatalog/latest/adminguide/getstarted-deploy.html

**Comment by peterwoodworth** [comment]
Please respond with requested information to keep this issue open
