### ISSUE TITLE
(aws-cdk): (CDK provisioned S3 buckets with versioning don't have lifecycle policies configured)

### ISSUE THREAD

**Issue by meghannoelle** [aws/aws-cdk#21872]
### Describe the bug

CDK provisioned S3 buckets cause the following finding in Security Hub:
`S3.10 S3 buckets with versioning enabled should have lifecycle policies configured`
(https://docs.aws.amazon.com/console/securityhub/S3.10/remediation)

### Expected Behavior

I expected CDK to provision S3 buckets with versioning enabled to have lifecycle policies configured by default.  

### Current Behavior

CDK-provisioned S3 buckets with versioning don't have lifecycle policies configured by default and are breaching Security Hub's AWS foundational security best practices.

### Reproduction Steps

Deploy a versioned S3 bucket and note the above finding in Security Hub.

### CDK CLI Version

2.35.0 (build 5c23578)

### Node.js Version

v14.18.1

### OS

MacOS

### Language

Typescript

**Comment by peterwoodworth** [comment]
duplicate of https://github.com/aws/aws-cdk/issues/21868
