### ISSUE TITLE
triggers: Cannot define a Trigger when using BootstraplessSynthesizer

### ISSUE THREAD

**Issue by billyjbryant** [aws/aws-cdk#21881]
### Describe the bug

I am attempting to build a stack that includes a Custom Trigger for a Lambda Function; however, when attempting to `synth` the stack, I am presented with the error `Error: Cannot add assets to a Stack that uses the BootstraplessSynthesizer`

### Expected Behavior

I expected the template to synthesize 

### Current Behavior

```
Error: Cannot add assets to a Stack that uses the BootstraplessSynthesizer
    at BootstraplessSynthesizer.addFileAsset (/Users/billybryant/github/crowdstrike/node_modules/aws-cdk-lib/core/lib/stack-synthesizers/bootstrapless-synthesizer.js:1:1007)
    at new CustomResourceProvider (/Users/billybryant/github/crowdstrike/node_modules/aws-cdk-lib/core/lib/custom-resource-provider/custom-resource-provider.js:1:2068)
    at CustomResourceProvider.getOrCreateProvider (/Users/billybryant/github/crowdstrike/node_modules/aws-cdk-lib/core/lib/custom-resource-provider/custom-resource-provider.js:1:4321)
    at new Trigger (/Users/billybryant/github/crowdstrike/node_modules/aws-cdk-lib/triggers/lib/trigger.js:1:695)
    at new CrowdStrikeStack (/Users/billybryant/github/crowdstrike/lib/crowdstrike-stack.js:172:31)
    at Object.<anonymous> (/Users/billybryant/github/crowdstrike/bin/crowdstrike.js:14:1)
```

After digging into it, I found that `aws-cdk-lib/core/lib/custom-resource-provider/custom-resource-provider.js` contains a reference to `asset = stack.synthesizer.addFileAsset` as it appears to be building a temporary directory to house the Lambda assets in for building the trigger. 

#### ../lib/crowdstrike-stack.js
```js
const { Stack, triggers, aws_lambda: lambda } = require('aws-cdk-lib');

class CrowdStrikeStack extends Stack {
  /**
   *
   * @param {Construct} scope
   * @param {string} id
   * @param {StackProps=} props
   */
  constructor(scope, id, props) {
    super(scope, id, {
      ...props,
      deploymentEnvironment: 'staging' | 'production'
    });
    const lambdaDocsSetupFn = new lambda.Function(this, 'LambdaDocsSetup', {
      functionName: `${stackName}-docs-setup-fn`,
      runtime: lambda.Runtime.PYTHON_3_7,
      timeout: Duration.seconds(120),
      memorySize: 128,
      code: lambda.Code.fromBucket(S3Bucket, 'lambda_ssm_setup.zip'),
      handler: 'lambda_ssm_setup.lambda_handler',
      layers: [lambdaLayer],
      environment: {
        aws_region: region,
        ssm_automation_doc_name: StackParams.DocumentName.valueAsString,
        s3bucket: S3Bucket.bucketName,
        document_name: StackParams.PackageName.valueAsString
      },
      role: lambdaRole
    });

    const createDocsTrigger = new triggers.Trigger(
      this,
      'TriggerCreateDocsLambda',
      {
        handler: lambdaDocsSetupFn,
        executeAfter: lambdaDocsSetupFn
      }
    );
  }
}

module.exports = { CrowdStrikeStack };
```

### Possible Solution

Migrate custom resources to using ephemeral variables and supplying the code inline to the lambda function instead of creating temporary files and requiring the loading of assets unbeknownst to the developer. 

### CDK CLI Version

2.40.0 (build 56ba2ab)

### Node.js Version

v18.7.0

### OS

MacOS Monterrey

### Language

Typescript

**Comment by billyjbryant** [comment]
I was able to leverage `cdk.CustomResource` to create my Trigger. Seems that if `cdk.CustomResource` is able to create a `custom::` resource in the CFN template without making use of assets, then `cdk.triggers` should be able to do the same.

**Comment by peterwoodworth** [comment]
Thanks for the request, 

Deploying lambda functions with inline code has some drawbacks. Most importantly, it has a strict size limitation, and it reduces readability & organization of both our code and customer templates. Not being able to deploy assets is an inherent drawback to using the bootstrapless synthesizer, so I don't think we'll end up implementing this.
