### ISSUE TITLE
init templates for csharp/fsharp/java are in wrong category

### ISSUE THREAD

**Issue by garnaat** [aws/aws-cdk#2188]
The current init templates provided for `csharp`, `fsharp`, and `java` are actually `sample-app`s but show up in the `app` category.

The `app` category is meant to be a _Template for a CDK Application_, basically a blank project.  These examples should really be in the `sample-app` category which is described as _Example CDK Application with some constructs_.

**Comment by shivlaks** [comment]
related issue #4418

**Comment by shivlaks** [comment]
Java templates addressed in #5059

**Comment by shivlaks** [comment]
stale issue. init templates have been harmonized a few months ago.
feel free to re-open if i missed something!
