### ISSUE TITLE
aws_events.CfnRule does not put events into AWS CloudWatch Log Group

### ISSUE THREAD

**Issue by entest-hai** [aws/aws-cdk#21890]
### Describe the bug

I am doing a simple EventBridge rule using L1 construct - aws_events.CfnRule but it does not put events into the CloudWatch Log Group as expected. I already provided a roleArn with sufficient permission.

```tsx
// l1 event rule
    const role = new cdk.aws_iam.Role(
      this,
      "AllowEventBridgeWriteToLogs",
      {
        roleName: "AllowEventBridgeWriteToLogs",
        assumedBy: new cdk.aws_iam.ServicePrincipal(
          "events.amazonaws.com"
        ),
      }
    );

    role.addToPolicy(
      new cdk.aws_iam.PolicyStatement({
        effect: Effect.ALLOW,
        resources: ["*"],
        actions: ["*"],
      })
    );

    new cdk.aws_events.CfnRule(this, "L1Rule", {
      name: "L1Rule",
      roleArn: role.roleArn,
      eventPattern: {
        source: ["entest.io"],
      },
      targets: [
        {
          arn: log.logGroupArn,
          id: log.logGroupName,
        },
      ],
    });
```

 When I change to L1 construct aws_events.Rule and addTarget(logGroup), then it works but an additional lambda function added automatically to my stack. 

```
 const rule = new cdk.aws_events.Rule(
   this,
   "WriteToEventLogRule",
   {
    ruleName: "WriteToEventLogRule",
    eventPattern: {
    source: ["entest.io"],
  },
   enabled: false,
}
);
rule.addTarget(
  new cdk.aws_events_targets.CloudWatchLogGroup(log)
);
```

### Expected Behavior

Events should be put into the log group 

### Current Behavior

Events are not put in to the log group

### Reproduction Steps

```tsx
import * as cdk from "aws-cdk-lib";
import { Construct } from "constructs";
import { Effect } from "aws-cdk-lib/aws-iam";
import { Duration } from "aws-cdk-lib";
import * as path from "path";
import * as fs from "fs";

export class EventbridgeBidirectionStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    // lambda send event
    new cdk.aws_lambda.Function(this, "SendEventFunction", {
      functionName: "SendEventFunction",
      code: cdk.aws_lambda.Code.fromInline(
        fs.readFileSync(
          path.resolve(__dirname, "./../lambda/index.py"),
          { encoding: "utf-8" }
        )
      ),
      handler: "index.handler",
      runtime: cdk.aws_lambda.Runtime.PYTHON_3_7,
      timeout: Duration.seconds(10),
      initialPolicy: [
        new cdk.aws_iam.PolicyStatement({
          effect: Effect.ALLOW,
          resources: ["*"],
          actions: ["events:PutEvents"],
        }),
      ],
    });

    // cloudwatch loggroup
    const log = new cdk.aws_logs.LogGroup(
      this,
      "LogGroupEventBridge",
      {
        logGroupName: `EventBridgeLogGroupDemo`,
      }
    );

    // l2 construct - this will work event rule
    //    const rule = new cdk.aws_events.Rule(
    //      this,
    //      "WriteToEventLogRule",
    //      {
    //        ruleName: "WriteToEventLogRule",
    //        eventPattern: {
    //          source: ["entest.io"],
    //        },
    //        enabled: false,
    //      }
    //    );
    //
    //    rule.addTarget(
    //      new cdk.aws_events_targets.CloudWatchLogGroup(log)
    //    );

    // l1 event rule
    const role = new cdk.aws_iam.Role(
      this,
      "AllowEventBridgeWriteToLogs",
      {
        roleName: "AllowEventBridgeWriteToLogs",
        assumedBy: new cdk.aws_iam.ServicePrincipal(
          "events.amazonaws.com"
        ),
      }
    );

    role.addToPolicy(
      new cdk.aws_iam.PolicyStatement({
        effect: Effect.ALLOW,
        resources: ["*"],
        actions: ["*"],
      })
    );

    new cdk.aws_events.CfnRule(this, "L1Rule", {
      name: "L1Rule",
      roleArn: role.roleArn,
      eventPattern: {
        source: ["entest.io"],
      },
      targets: [
        {
          arn: log.logGroupArn,
          id: log.logGroupName,
        },
      ],
    });
  }
}

```

### CDK CLI Version

2.38.1

### Node.js Version

v16.17.0

### OS

Amazon Linux 2

### Language

Typescript

### Language Version

3.9.7

**Comment by rix0rrr** [comment]
As you yourself are saying, you are using the L1 layer. You are effectively writing CloudFormation and are responsible for knowing what to put in the CloudFormation. I myself don't know what the right answer is here, but unless you can point me to 

* The CloudFormation output you know is correct and you expected to get
* How CDK makes it impossible for you to achieve the CloudFormation output you need

There's nothing to do here for us.

I looked at the code of `aws_events_targets.CloudWatchLogGroup` and it does not add a Lambda function to your stack. If that works, I suggest you use it.

**Comment by entest-hai** [comment]
> As you yourself are saying, you are using the L1 layer. You are effectively writing CloudFormation and are responsible for knowing what to put in the CloudFormation. I myself don't know what the right answer is here, but unless you can point me to
> 
>     * The CloudFormation output you know is correct and you expected to get
> 
>     * How CDK makes it impossible for you to achieve the CloudFormation output you need
> 
> 
> There's nothing to do here for us.
> 
> I looked at the code of `aws_events_targets.CloudWatchLogGroup` and it does not add a Lambda function to your stack. If that works, I suggest you use it.

Thank you, 

1) You are correct, when using L1, I should have grant permission via resource base policy so eventbride can write to a cloudwatch log group. 

2) About the L2, aws_events_targets.CloudWatchLogGroup will automatically create a lambda function, you will see the generated lambda function from aws console, not from the code. 

Anyway, thank you
