### ISSUE TITLE
aws-sns: grantPublish should add generateDataKey and decrypt policy for kms key

### ISSUE THREAD

**Issue by ghdoergeloh** [aws/aws-cdk#21892]
### Describe the bug

If I grant access to a encrypted SNS Topic the key is ignored. It does not add permission for the key.

There is also no `readonly encryptionMasterKey?: kms.IKey;` like in SQS Queue to do a workaround. Everywhere I use the topic, I need to supply the key, too.

### Expected Behavior

- `grantPublish` should add permission (kms:generateDataKey and kms:decrypt) to grantee's (e.g. a lambda) role to really allow the granted actions.

### Current Behavior

no permission for the key is added anywhere, and cannot be added because it is not stored as a property of the topic.

### Reproduction Steps

```typescript
    const stack = new Stack();

    const topic = new Topic(stack, 'Topic', {
      masterKey: new Key(stack, 'Key'),
    });
    topic.grantPublish(lambda);
```

### Possible Solution

Same behavior (different policies) as `sqs.Queue.grantSendMessages`.

### CDK CLI Version

2.39.1

### Node.js Version

16.15.1

### OS

Ubuntu 22.04 LTS (Linux 5.15.0-43)

### Language

Typescript

### Language Version

4.8.2

**Comment by peterwoodworth** [comment]
Thanks for the report, we're already tracking this in #18387 as you've noticed, so I'm going to close this out in favor of that issue 🙂
