### ISSUE TITLE
aws_secretsmanager: Creating secret does not work when adding secret_object_value parameter

### ISSUE THREAD

**Issue by bnclark07** [aws/aws-cdk#21895]
### Describe the bug

When creating a new secret with aws_secretsmanager, the Secret Class is failing when secret_object_value is added as a parameter. The secret_object_value parameter creates the key/value and plaintext in the secretsmanager service. 

### Expected Behavior

Expecting the cdk to create the secret key/value and plan text in secretsmanager
![image](https://user-images.githubusercontent.com/83967179/188167994-2bdb38a2-6bdc-4a74-b6b5-2b56910d77ee.png)
![image](https://user-images.githubusercontent.com/83967179/188168060-e7b5a9c0-3030-4d98-9721-38bd312f6a32.png)

### Current Behavior

Currently, cdk deploy fails with this error message:
`File "/jsii/_runtime.py", line 86, in __call__
    inst = super().__call__(*args, **kwargs)
TypeError: Secret.__init__() got an unexpected keyword argument 'secret_object_value'`

### Reproduction Steps

This example is from the [documentation](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_secretsmanager/Secret.html)
`secretsmanager.Secret(stack, "Secret",
    secret_object_value={
        "username": SecretValue.unsafe_plain_text(user.user_name),
        "database": SecretValue.unsafe_plain_text("foo"),
        "password": access_key.secret_access_key
    }
)`

### Additional Information/Context

The parameter worked about 15 days ago. We currently have a process that worked with the parameter.

Stack contents -> The only content in my stack is the aws_secretsmanager.Secret class

Trying to achieve-> Need to be able to create a secret in secrets manger with key/value

### CDK CLI Version

2.40.0

### Node.js Version

latest

### OS

Mac

### Language

Python

### Language Version

Python3.9

**Comment by peterwoodworth** [comment]
I can't reproduce this, this parameter works for me on the latest version

> The parameter worked about 15 days ago

Did this stop working when you upgraded versions?

**Comment by bnclark07** [comment]
Hello. Yes

**Comment by bnclark07** [comment]
I reinstalled aws-cdk right before I tested this

**Comment by peterwoodworth** [comment]
Can you share the exact code snippet you're trying to use @bnclark07? Without more information I don't think I'll be able to reproduce this

**Comment by bnclark07** [comment]
Yep. I'm literally running this code right here
```
from aws_cdk import (
    # Duration,
    Stack,
    SecretValue,
    aws_secretsmanager as secretsmanager
)
from constructs import Construct

class CdkStuffStack(Stack):

    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        secretsmanager.Secret(self, "Secret", secret_object_value={ "username": "test", "database": "tes", "password": "test"} )
```

I got a new Mac and had to reinstall cdk. Since then, I've been receiving this error
`TypeError: Secret.__init__() got an unexpected keyword argument 'secret_object_value'`

**Comment by gshpychka** [comment]
This is an environment issue - you're somehow using a CDK version that doesn't support this. What's the output of `pip freeze | grep cdk`?

**Comment by peterwoodworth** [comment]
Alternatively, try reinstalling latest version of CDK again and seeing if this is still occurring on a new project. This is certainly an environment/versioning issue

**Comment by bnclark07** [comment]
Yep! That was the issue. Thank you!
