### ISSUE TITLE
(config):  Make available the latest list of AWS Config managed rules as of 08/2022

### ISSUE THREAD

**Issue by watany-dev** [aws/aws-cdk#21896]
### Describe the feature

Some of the managed rules listed in the url cannot be used, so we will update them
https://docs.aws.amazon.com/config/latest/developerguide/managed-rules-by-aws-config.html

### Use Case

When you want to use that managed rule in L2.

### Acknowledgements

- [X] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### CDK version used

2.40.0

### Environment details (OS name and version, etc.)

any

**Comment by watany-dev** [comment]
i am working on this. Just checked, there are 25 rules, and it seems that there will be more.

**Comment by peterwoodworth** [comment]
What are you planning to do here? I'm not familiar with this service to be honest, but it seems to me that we can pass in any arbitrary [serciveIdentifier](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_config.ManagedRule.html#identifier) of these managed rules you've linked the documentation for.

**Comment by watany-dev** [comment]
I would like to bring up-to-date the managed rules that can be selected with [`ManagedRuleIdentifiers`](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-config.ManagedRuleIdentifiers.html). With this modification, users will not have to look up ambiguous managed rule names, but can enter them via IDE or other completion.
