### ISSUE TITLE
(rds): DBInstances that are part of DBCluster incorrectly have EngineVersion set

### ISSUE THREAD

**Issue by rittneje** [aws/aws-cdk#21899]
### Describe the bug

We have a DatabaseCluster in our stack. It in turn contains two instances. We have specified the engine version on the cluster but not in the InstanceProps. However, CDK incorrectly generates a template where the EngineVersion is specified in each AWS::RDS::DBInstance. In turn, due to a CloudFormation bug (and maybe also an RDS bug), this template is accepted and deploys successfully. However, if we attempt to upgrade the engine version in a subsequent deployment, CloudFormation then tries to update the individual instances, which fails because RDS does not allow updating the version of an instance that is part of a cluster.

### Expected Behavior

Only the AWS::RDS::DBCluster should have the engine version specified so we can properly update it.

### Current Behavior

It violates RDS's rules and the stack deployment fails. Also the stack rollback fails.

> The specified DB Instance is a member of a cluster. Modify the DB engine version for the DB Cluster using the ModifyDbCluster API

### Reproduction Steps

```python
db_engine = rds.DatabaseClusterEngine.aurora_postgres(
    version=rds.AuroraPostgresEngineVersion.VER_12_8
)

instance_props = rds.InstanceProps(
    instance_type=ec2.InstanceType(db_instance_identifier),
    vpc=vpc,
    vpc_subnets=ec2.SubnetSelection(
        subnet_type=ec2.SubnetType.PUBLIC,
        one_per_az=True
    ),
    security_groups=[self._security_group],
    publicly_accessible=True,
    parameters={
        "tcp_keepalives_count": "3",
        "tcp_keepalives_idle": "30",
        "tcp_keepalives_interval": "30",
        "idle_in_transaction_session_timeout": "120000"
    )
)

rds.DatabaseCluster(
    scope,
    id=f"{id_}-cluster",
    default_database_name=database_name,
    engine=db_engine,
    instance_props=instance_props,
    storage_encrypted=True,
    port=5432,
    cluster_identifier=db_cluster_identifier,
    backup=rds.BackupProps(
        retention=aws_cdk.Duration.days(7),
        preferred_window="13:00-01:00",
    )
)
```

### CDK CLI Version

2.20.0

### Node.js Version

v16.15.1

### OS

Alpine 3.15

### Language

Python

### Language Version

3.9.12

**Comment by blimmer** [comment]
Thanks @rittneje - I updated #21758 to remove the language about major versions. With that change, I think we can close this issue as a dupe?

**Comment by rittneje** [comment]
closing in favor of #21758
