### ISSUE TITLE
aws-stepfunctions-tasks: Enable creation of 'sync' states for AWS optimized integrations

### ISSUE THREAD

**Issue by lucascott** [aws/aws-cdk#21915]
### Describe the feature

For integrated services such as AWS Batch and Amazon ECS, Step Functions can wait for a request to complete before progressing to the next state. To have Step Functions wait, specify the "Resource" field in your task state definition with the .sync suffix appended after the resource URI.

https://docs.aws.amazon.com/step-functions/latest/dg/connect-to-resource.html#connect-sync

This feature is not yet available in CDK.

### Use Case

Creating synchronized state machines

### Proposed Solution

Add `syncronized` property of type `boolean` to all optimized integration tasks that support it.
If set, the resource key for the task will concatenate the `.sync` suffix at the end of the value.

Example: 

from `"Resource": "arn:aws:states:::batch:submitJob"` to (with `syncronized: true`) `"Resource": "arn:aws:states:::batch:submitJob.sync"`,

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.40.0 (build 56ba2ab)

### Environment details (OS name and version, etc.)

Ubuntu 20.04.4 LTS

**Comment by kaizencc** [comment]
As always, we can use `customState` as a workaround. Would be happy to accept a contribution for this!

**Comment by psalvaggio-dl** [comment]
+1 on this issue. This would be a big help!

**Comment by lucascott** [comment]
From further research, the feature is already available yet not well documented. The way to define synchronous optimized integration steps (for those steps that support it) in CDK is by specifying the integration pattern property.

See https://github.com/aws/aws-cdk/blob/74318c7d22bfc00de9e005f68a0a6aaa58c7db39/packages/%40aws-cdk/aws-stepfunctions/lib/states/task-base.ts#L93

```ts
import {IntegrationPattern} from "aws-cdk-lib/aws-stepfunctions";
// ...
{
// ...other params
integrationPattern: IntegrationPattern.RUN_JOB
}
```

**Comment by lauragalera** [comment]
I've tried `IntegrationPattern.RUN_JOB` and it seems to be ignored on my GlueStartJobRun() construct. Code example on this [other issue ](https://github.com/aws/aws-cdk/issues/8599)
