### ISSUE TITLE
(lambda-nodejs): Unable to use `nodeModules` with pnpm

### ISSUE THREAD

**Issue by cecheta** [aws/aws-cdk#21910]
### Describe the bug

The `nodeModules` prop in `bundling` does not work with pnpm for two reasons:

- pnpm uses symlinks, meaning that only direct dependencies are put in the `node_modules` directory. This means that when `nodeModules` is bundled, it only includes direct dependencies and not sub-dependencies.
- When using pnpm workspaces, the install command does not install any modules into the local directory, as the install takes place in the workspace's `node_modules` not in the local directory

### Expected Behavior

Bundled node_modules includes dependencies as listed in `nodeModules`, as well as their own sub-dependencies

### Current Behavior

- `node_modules` only contains direct dependencies
- If using pnpm workspaces, there is no `node_modules` at all

### Reproduction Steps

- `cdk init app --language typescript`
- Delete `node_modules` and `package-lock.json`
- Run `pnpm install` (`npm install -g pnpm` to install pnpm)
- Install package that has at least one sub-dependency (i.e. `pnpm add axios`)
- `pnpm add esbuild`
- Add nodeJs lambda function to the stack

```ts
import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as nodejs from 'aws-cdk-lib/aws-lambda-nodejs';
import { Runtime } from 'aws-cdk-lib/aws-lambda';
import * as path from 'path';

export class PnpmStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    new nodejs.NodejsFunction(this, 'function', {
      entry: path.join(__dirname, 'index.ts'),
      runtime: Runtime.NODEJS_16_X,
      bundling: {
        nodeModules: ['axios'],
      },
    });
  }
}
```

- Create `index.ts` file
- `cdk synth`
- Inspect the `node_modules` directory inside the asset in the `cdk.out` directory
  - At the top level, it only contains axios and not any of axios' dependencies

---
- Remove `cdk.out`
- Create `pnpm-workspace.yaml`

```yaml
packages:
  - '!**'
```

- `cdk synth`

- The asset in the `cdk.out` directory has no `node_modules` directory

### Possible Solution

- `--shameless-hoist` can be used when running `pnpm install` to ensure that all dependencies are at the top level in `node_modules`
- Creating a `pnpm-workspace.yaml` file inside the local directory when running the install means any higher `pnpm-workspace.yaml` files will be ignored

### CDK CLI Version

2.40.0

### Node.js Version

16.15.0

### OS

Mac OS

### Language

Typescript

### Language Version

3.9.10

**Comment by corymhall** [comment]
This issue has been classified as *p2*. That means a workaround is available or it is deemed a nice-to-have feature. Given the amount of work there is to do and the relative priority of this issue, the CDK team is unlikely to address it. That does not mean the issue will never be fixed! If someone from the community submits a PR to fix this issue, and the PR is small and straightforward enough, and meets the quality bars to be reviewed and merged with little effort we will accept that PR. PRs that do not build or need complex or multiple rounds of reviews are unlikely to be merged and will be closed to keep our backlog manageable.

In the mean time, remember that you can always use the escape hatch (https://docs.aws.amazon.com/cdk/v2/guide/cfn_layer.html) mechanism to have fine control over the CloudFormation output you want. We will keep the issue open for discoverability, to collect upvotes, and to facilitate discussion around this topic.

We use +1s *on this issue* to help prioritize our work, and are happy to re-evaluate the prioritization of this issue based on community feedback. You can reach out to the cdk.dev community on Slack (https://cdk.dev/) to solicit support for reprioritization.

**Comment by kenberkeley** [comment]
Please allow me to add my quick workaround to @cecheta 's aforementioned *Possible Solution*:

- Use `npm install` directly in [`bundling.commandHooks.afterBundling`](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda_nodejs-readme.html#command-hooks) ⬇️

```ts
new Lambda.NodejsFunction(this, "Lambda", {
  entry: "path/to/entry.js",
  runtime: LambdaRuntime.NODEJS_16_X,
  bundling: {
    nodeModules: ["swagger-ui-express", "express"], // These are the modules I have to install after bundling
    commandHooks: {
      beforeBundling: () => [],
      beforeInstall: (inputDir, outputDir) => [`rm ${outputDir}/pnpm-lock.yaml`],
      afterBundling: () => ["npm i"],
    },
  }
})
```
