### ISSUE TITLE
(aws-ec2): CDK creates default UserData in the synthesized CFN template?

### ISSUE THREAD

**Issue by maximillianus** [aws/aws-cdk#21912]
### Describe the bug

I wonder why `cdk` creates a default UserData in the template when synthesized? Is this normal behavior or is there something wrong with my `cdk`?

This is a snippet of my code. I did not configure anything else aside from importing default VPC, securityGroup, and Role.
```
const ec2Instance = new ec2.Instance(this, "my-ec2-instance", {
      vpc,
      vpcSubnets: {
        subnetType: ec2.SubnetType.PUBLIC
      },
      instanceType: new ec2.InstanceType("t3a.micro"),
      machineImage: new ec2.GenericLinuxImage({
        "ap-southeast-1": "ami-04ff9e9b51c1f62ca"
      }),
      // securityGroup: webServerSG,
      // role: ec2Role
    });
```

The generated CFN template always have this although I did not specify any userData:
```
UserData:
  Fn::Base64: "#!/bin/bash"
```

### Expected Behavior

If no user data is specified, cdk **should not** synthesized any UserData property in EC2 Resources.

### Current Behavior

CDK synthesized UserData property in EC2 resources. I vaguely remember that it does not do this previously, but CMIIW.

### Reproduction Steps

Just do `cdk synth` in the CDK typescript code above.

### CDK CLI Version

2.39.0

### Node.js Version

18.8.0

### OS

MacOS

### Language

Typescript

### Language Version

3.9.9

**Comment by corymhall** [comment]
@maximillianus it looks like this has been the behavior for a very long time. I _think_ the reason
for always including it is to make it easier to work with user data. If we didn't create a base user
data by default then whenever you wanted to add some you would first need to check whether user
data exists or not (and what type of OS).

Have you noticed any downsides to this behavior?

**Comment by maximillianus** [comment]
Noted if that is the normal behavior. I did not see this in the documentation either so I didn't know if this is the normal behavior. No particular downside just that the additional CFN Resource property leads me to think if I added something in my CDK which generates that. 

This can be closed if that is the expected behavior
