### ISSUE TITLE
(pipelines): asset error, cannot deploy stack with CloudFormationCreateUpdateStackAction

### ISSUE THREAD

**Issue by samarkumar1** [aws/aws-cdk#21924]
### Describe the bug

Can't deploy a lambda function through CodeDeploy. CloudFormationCreateUpdateStackAction  

Can't deploy apigateway with openapi specthrough CodeDeploy. CloudFormationCreateUpdateStackAction, getting below error. 

Parameters: [AssetParameterseae86da7923b190696271f094217d3734f4fdc1221279023bafeb50d2531fe9aS3BucketFF349268, AssetParameterseae86da7923b190696271f094217d3734f4fdc1221279023bafeb50d2531fe9aArtifactHashEC763873, AssetParameterseae86da7923b190696271f094217d3734f4fdc1221279023bafeb50d2531fe9aS3VersionKeyA8E0A3CC] must have values (Service: AmazonCloudFormation; Status Code: 400; Error Code: ValidationError; Request ID: 0affa786-d391-4c76-8d64-11d6f7673435; Proxy: null)### 

### Expected Behavior

I am able to deploy Lambda but when i try to deploy Apigateway with open api spec i am getting an error. 

### Current Behavior

Getting below error: 
Parameters: [AssetParameterseae86da7923b190696271f094217d3734f4fdc1221279023bafeb50d2531fe9aS3BucketFF349268, AssetParameterseae86da7923b190696271f094217d3734f4fdc1221279023bafeb50d2531fe9aArtifactHashEC763873, AssetParameterseae86da7923b190696271f094217d3734f4fdc1221279023bafeb50d2531fe9aS3VersionKeyA8E0A3CC] must have values (Service: AmazonCloudFormation; Status Code: 400; Error Code: ValidationError; Request ID: 0affa786-d391-4c76-8d64-11d6f7673435; Proxy: null)

### Reproduction Steps

I am trying to deploy Lambda and Apigateway from code pipeline, using following stage. 

        // Deploy App 
        pipeline.addStage({
            stageName: 'DeployAppLambda',
            actions: [
                // Deploy App Lambda
                new CodePipelineAction.CloudFormationCreateUpdateStackAction({
                    actionName: 'Lambda_CFN_Deploy',
                    templatePath: cdkBuildOutput.atPath('LambdaStack-v1.template.json'),
                    stackName: 'PasLambdaDeploymentStack-v1',
                    adminPermissions: true,
                    parameterOverrides: {
                        ...props.lambdaCode.assign(lambdaBuildOutput.s3Location),
                    },
                    extraInputs: [lambdaBuildOutput],
                    
                }),
            ],
        })

then in Lambda stack i am using following code 

  //Apigateway 
  const apigwdev = new apigateway.SpecRestApi(this, 'pasapigwdev', {
    restApiName: "pasapigwdev",
    apiDefinition: apigateway.ApiDefinition.fromAsset(`appresource/openapi-qa.json`),
    endpointTypes: [apigateway.EndpointType.REGIONAL],
    deployOptions: {
      stageName: "dev",
      tracingEnabled: true,
      accessLogDestination: new apigateway.LogGroupLogDestination(apiloggroup),
      metricsEnabled: true,
      loggingLevel: apigateway.MethodLoggingLevel.INFO,
      dataTraceEnabled: false,
    },
    deploy: true
  });

### CDK CLI Version

2.37.1

### Node.js Version

v18.0.0

### OS

MAC Os 12.5.1

### Language

Typescript

### Language Version

4.8.2

**Comment by peterwoodworth** [comment]
Seems to me like you haven't specified parameter values for some parameters that require values to be set. Your template you're trying to supply here should have a parameters section where you can see what needs to be passed in. You can set these parameters with the [`templateConfiguration` prop](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-codepipeline-actions.CloudFormationCreateUpdateStackActionProps.html#templateconfiguration)
