### ISSUE TITLE
cdk cli/plugin formatting of cloudformation output to file or callback

### ISSUE THREAD

**Issue by puttyman** [aws/aws-cdk#2193]
After a successful stack deployment cdk outputs the stack details to stdout. 

It would be great to have cdk cli or plugin support to have output values of the cf stack to a file or for further processing through a callback function.

**Comment by rix0rrr** [comment]
Do you mean stack ARN and outputs?

**Comment by iDVB** [comment]
Similar to this... https://github.com/sbstjn/serverless-stack-output but for CDK.
Googling around trying to find something like this or an example of a plugin so I might attempt at creating one.

**Comment by shivlaks** [comment]
support for specifying a file to store stack outputs to a file when deploying a stack was added in #7020
