### ISSUE TITLE
(aws-logs-destination): missing dependency to Policy created by LambdaDestination

### ISSUE THREAD

**Issue by joel-aws** [aws/aws-cdk#21941]
### Describe the bug

When creating a `SubscriptionFilter` with to a `LambdaDestination`, two resources are created: A Lambda::Permission and a Logs::Subscription; there are no dependencies or references between the two. This means that a Subscription can be created before the Permission, leading to permissions errors.

Related to #21827.

### Expected Behavior

the Logs::Subscription has a `DependsOn` to the Lambda::Permission.

### Current Behavior

CFn will spit an error about the inability to invoke the destination Lambda function.

### Reproduction Steps

Create a SubscriptionFilter to a LambdaDestination.

```python
subscription = SubscriptionFilter(
    self,
    f"log-subscription",
    log_group=source_function.log_group,
    destination=LambdaDestination(self.dest_function),
    filter_pattern=FilterPattern.any(
        FilterPattern.string_value("$.service", "=", "thing"),
    ),
)
```

### Possible Solution

Not a permanent fix, but we're using the following to force a dependency:

```python
subscription = SubscriptionFilter(
    self,
    f"log-subscription",
    log_group=source_function.log_group,
    destination=LambdaDestination(self.dest_function),
    filter_pattern=FilterPattern.any(
        FilterPattern.string_value("$.service", "=", "thing"),
    ),
)

permission: CfnPermission = subscription.node.find_child("CanInvokeLambda")
filter: CfnSubscriptionFilter = subscription.node.default_child
filter.add_depends_on(permission)
```

### CDK CLI Version

2.33.0

### Node.js Version

v16.3.0

### OS

macOS 11.6.5

### Language

Python

**Comment by marciocadev** [comment]
I believe the problem is that you are trying to use the lambda log as a LogGroup to filter logs from the lambda itself

if you do that it works

```py
log_group = LogGroup(self, 'LG');

subscription = SubscriptionFilter(
    self,
    f"log-subscription",
    log_group=log_group,
    destination=LambdaDestination(self.function),
    filter_pattern=FilterPattern.any(
        FilterPattern.string_value("$.service", "=", "thing"),
    ),
)
```

**Comment by joel-aws** [comment]
You're right, my example was poorly done: the destination lambda was meant to be different than the `log_group`. (I sanitized my source too well 😓.)

Edited. Thanks!

**Comment by peterwoodworth** [comment]
Thanks for the report and explanation @joel-aws,

The SubscriptionFilter construct calls the bind method of the destination, I think we could make some modifications here to ensure the proper dependencies are set https://github.com/aws/aws-cdk/blob/56ba2ab2c2d9240b76ece17c3296488a63f0b232/packages/%40aws-cdk/aws-logs-destinations/lib/lambda.ts#L24

I am marking this issue as p2, which means that we are unable to work on this immediately.

We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://join.slack.com/t/cdk-dev/shared_invite/zt-mso6p56d-qJp7SOTBvMaQuDrx7R2wHg) to solicit support for reprioritization.

Check out our [contributing guide](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) if you're interested in contributing yourself - there's a low chance the team will be able to address this soon but we'd be happy to review a PR 🙂

**Comment by marciocadev** [comment]
I think this can be closed, it's not a bug right?

**Comment by marciocadev** [comment]
@peterwoodworth It's really a bug?

That code use the lambda log as a LogGroup to filter logs from the lambda itself

**Comment by peterwoodworth** [comment]
@marciocadev it seems to me that OP @joel-aws has two different lambda functions - I don't see why the log group originating from one lambda couldn't have a separate lambda destination

**Comment by lenonestrella** [comment]
If anyone is facing issues because of this, like I was facing "Could not execute the lambda function. Make sure you have given CloudWatch Logs permission to execute your function" as the subscription was being created before the lambda permission, I managed to explicit define the dependency and fix it:



```
var subscription = new SubscriptionFilter(stack,
                       $"Subscription",
                       new SubscriptionFilterProps
                       {
                           LogGroup = logGroup,
                           Destination = new LambdaDestination(lambdaFn),
                           FilterPattern = FilterPattern.AllEvents()
                       });

var permission = subscription.Node.TryFindChild("CanInvokeLambda");
if (permission is not null)
{    subscription.Node.AddDependency(permission);
}
```

**Comment by rix0rrr** [comment]
If it's missing a dependency, we should be able to add it
