### ISSUE TITLE
PolicyStatement: Circular Dependency

### ISSUE THREAD

**Issue by K-Everhart** [aws/aws-cdk#21952]
### Describe the bug

Unable to resolve object tree with circular reference.

### Expected Behavior

Generation of policy for KMS::Key 

`
{
  "Id": "key-policy",
  "Version": "2010-10-17",
  "Statement": [
    {
      "Sid": "Deny",
      "Effect": "Deny",
      "Resource": "*",
      "Condition": {
        "ArnNotLike": {
          "aws:PrincipalArn": "arn:aws:iam::ACCOUNT_ID:role/ROLE_NAME"
        }
      },
      "Action": [
        "kms:*"
      ]
    }
  ]
}
'

### Current Behavior

Currently getting a circular dependency issue as part of the cdk synth process

Example code can be found here: https://github.com/K-Everhart/aws-cdk-ts-app-example/tree/feature/first-cdk-app

Error:
`
Error: Resolution error: Resolution error: Resolution error: Unable to resolve object tree with circular reference. Path: /Resources/${Token[cdk-stack.my-kms-key.Resource.LogicalID.224]}/Properties/keyPolicy/Statement/0/Condition/0/ArnNotLike/aws:PrincipalArn/0/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal.
`

### Reproduction Steps

1) Clone Repo
2) npm install OR yarn
3) cdk synth

### CDK CLI Version

2.40.0

### Framework Version

2.40.0

### Node.js Version

v16.15.0

### OS

MacOS Monterey Version 12.5.1 (21G83)

### Language

Typescript

### Language Version

4.6.3

**Comment by peterwoodworth** [comment]
This is happening because you're trying to create and reference a `ServicePrincipal` class inside `conditions` where this isn't meant to be done. 

```
              'ArnNotLike': {
                'aws:PrincipalArn': [new iam.AccountRootPrincipal()],
```

You should probably do something like
```
'aws:PrincipalArn': [new iam.AccountRootPrincipal().arn],
```
instead 🙂
