### ISSUE TITLE
CodePipeline: Unable to add conditional to a CodePipeline stage with CDK 

### ISSUE THREAD

**Issue by emcfins** [aws/aws-cdk#21953]
### Describe the bug

I'm trying to move my team's existing YAML CloudFormation templates to CDK. We have a few stages that use an `If` conditional, that allows us to enable our users to deploy different configurations of our pipelines from Service Catalog, similar to this example:

[https://stackoverflow.com/questions/41752007/conditionally-create-codepipeline-actions-based-on-cloudformation-conditions/53728633#53728633](https://stackoverflow.com/questions/41752007/conditionally-create-codepipeline-actions-based-on-cloudformation-conditions/53728633#53728633)

but when I do, I receive errors that conditional expressions are not allowed in `StageOptions`.

I have tried creating a conditional around my stage, like this:

```
    const stageCondition = new CfnCondition(this, 'StageCondition', {
      expression: Fn.conditionEquals(createStage, 'true')
    });
    const conditionalStageAdd = Fn.conditionIf(createStage.logicalId,
     {
        stageName: 'ConditionalStage',
        actions: [stageAction]
      },
      Aws.NO_VALUE
    );

testPipeline.addStage(conditionalStageAdd);
```

But when I add that to my pipeline stages list, I get the error:

`Argument of type 'ICfnRuleConditionExpression' is not assignable to parameter of type 'StageOptions'.
  Property 'stageName' is missing in type 'ICfnRuleConditionExpression' but required in type 'StageOptions'.`

I'm not sure where to go next, the CloudFormation AWS::CodePipeline::Pipeline type allows `If` conditionals when defining stages.

Any guidance to documentation that explains how to do this would be appreciated.

### Expected Behavior

I would expect to be able to have optional stages based on Parameter values provided by users.

### Current Behavior

The CDK throws an error when trying to add a stage wrapped in a conditional to a `Pipeline`.

When I add that to my pipeline stages list, I get the error:

`Argument of type 'ICfnRuleConditionExpression' is not assignable to parameter of type 'StageOptions'.
  Property 'stageName' is missing in type 'ICfnRuleConditionExpression' but required in type 'StageOptions'.`

### Reproduction Steps

```
import {Aws, Fn, CfnCondition, CfnParameter} from 'aws-cdk-lib';
import {Pipeline } from 'aws-cdk-lib/aws-codepipeline';
import { CodeBuildAction } from 'aws-cdk-lib/aws-codepipeline-actions';

const createStage = new CfnParameter(this, 'CreateStageParameter', {
      type: 'String',
      description: 'Flag to create given CodePipeline stage',
      default: 'false',
      allowedValues: ['false', 'true']
    });

const testApp = new Artifact();
    const testAction = new CodeBuildAction({
      actionName: 'TestAction',
      project: Project.fromProjectName(this, 'ExsitingTestCodeBuildProject', 'TestCodeBuildProjectName'),
      input: previousStageOutput,
      outputs: [testApp],
     });
     
 const testCondition = new CfnCondition(this, 'StageCondition', {
      expression: Fn.conditionEquals(createStage, 'true')
    });
 
const conditionalStageAdd = Fn.conditionIf(createStage.logicalId,
     {
        stageName: 'ConditionalStage',
        actions: [testAction]
      },
      Aws.NO_VALUE
    );   

    const testPipeline = new Pipeline(this, `TestPipeline`, {
      pipelineName: 'TestPipelineName,
      artifactBucket,
    });

testPipeline.addStage(conditionalStageAdd);
```

### Possible Solution

Add an validation for argument of type 'ICfnRuleConditionExpression' to be assignable to parameter of type 'StageOptions'.

### CDK CLI Version

2.38.1 (build a5ced21)

### Node.js Version

v16.17.0

### OS

OSX

### Language

Typescript

**Comment by peterwoodworth** [comment]
We have a [short section in our docs](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib-readme.html#intrinsic-functions-and-condition-expressions) about this - you will have to apply these on the CloudFormation layer, not in the higher level constructs. For more information on operating on the Cfn layer, or L1, see our docs on [escape hatches](https://docs.aws.amazon.com/cdk/v2/guide/cfn_layer.html)

It seems to me like you're trying to use intrinsic Cfn conditions to decide how exactly you're setting the properties on our L2 abstractions. This won't directly work for L2 properties since those are likely abstracted from the properties of the generated resources.

I think what you most want to do in this case is to first create a stage no matter what, then add a condition to the created stage (created from `addStage`) by doing something similar to the example in the first link I posted. This condition will toggle whether the stage gets created or not

**Comment by emcfins** [comment]
Thanks for the guidance, @peterwoodworth 

I'm running into an issue where the stage is an attribute/value of a Resource and not the Resource itself. 

If I try to do the following:

```
const conditionalStage = {
        stageName: 'ConditionalStage',
        actions: [testAction]
      };

const createStageCondition = new CfnCondition(this, 'ToCreateStage', {
      expression: Fn.conditionEquals('true', createStage)
    });

const conditionalAddStage = featurePipeline.addStage(conditionalStage);

const featurePipelineCfnResource = <CfnPipeline>featurePipeline.node.defaultChild;

featurePipelineCfnResource.stages.cfnOptions.condition = conditionalAddStage
```
I get an error:

`Property 'cfnOptions' does not exist on type 'IResolvable | (StageDeclarationProperty | IResolvable)[]'.
  Property 'cfnOptions' does not exist on type 'IResolvable'`

I'm unable to convert the `conditionalAddStage` to an L1, as it's an attribute rather than a Resource.
```
const conditionalAddStage = featurePipeline.addStage(conditionalStage);

const cfnStageResource =  conditionalAddStage.node.defaultChild as CfnResource
 ```
produces the error:

```
Property 'node' does not exist on type 'IStage'.
```

I can add the conditional, like in the example, to the `featurePipelineCfnResource` but then that wraps all of the stages in a single conditional, not an individual stage in a conditional.

I'm going to explore using `addPropertyOverride` next to see if I can create the stage with `addStage` and then overwrite it with a conditional before adding the rest of the CodePipeline stages.

**Comment by emcfins** [comment]
I've run into some additional strangeness.

I created all the stages I need and synthesized the template and found the index of the stage I wanted to update (4, in this case).

I tried to just do add property override:
```
testPipelineCfnResource.addPropertyOverride('Stages.4', Fn.conditionIf( createStage.logicalId, 
    conditionalStage, 
    Aws.NO_VALUE
)); 
```

But that adds the condition to the existing object, rather than overwrite it (which is what I was expecting):
```
        - Actions:
            - ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
                <...snip...>
          Name: PublicECRStage
          Fn::If:
            - ConditionalStage
            - Actions:
                - ActionTypeId: 
```
I have tried deleting the whole stage and deleting the `Actions` and `Name` but pairing the `addPropertyDeletionOverride('Stages.4.Name');`, `addPropertyDeletionOverride('Stages.4.Actions');`
with the `addPropertyOverride('Stages.4', <...snip...>)` produces the same result as above, the keys `Actions` and `Name` do not get removed.

**Comment by peterwoodworth** [comment]
A foolproof way of knowing exactly how to use escape hatches to get to the right L1 resource is to look at the `cdk.out/tree.json` file. It will show the construct tree in a pretty clear manner 🙂
