### ISSUE TITLE
(aws-dynamodb): metricThrottledRequestsForOperation is not part of the ITable interface.

### ISSUE THREAD

**Issue by Sunilkby17** [aws/aws-cdk#21963]
### Describe the bug

[ITable](https://github.com/aws/aws-cdk/blob/ab7668197b1d7d7d08654d49df0c5ad9cb61b960/packages/%40aws-cdk/aws-dynamodb/lib/table.ts#L367) interface doesn't contain [metricThrottledRequestsForOperation](https://github.com/aws/aws-cdk/blob/ab7668197b1d7d7d08654d49df0c5ad9cb61b960/packages/%40aws-cdk/aws-dynamodb/lib/table.ts#L877) but instead contains deprecated [metricThrottledRequests](https://github.com/aws/aws-cdk/blob/ab7668197b1d7d7d08654d49df0c5ad9cb61b960/packages/%40aws-cdk/aws-dynamodb/lib/table.ts#L538) which has an issue and doesn't provide any metrics at all. By just having metricThrottledRequests in ITable interface is hiding the fact that it's deprecated and not allowing the recommended metricThrottledRequestsForOperation to use for users who declare the objects with ITable as type.

### Expected Behavior

ITable interface should contain metricThrottledRequestsForOperation declaration

### Current Behavior

ITable interface contains [metricThrottledRequests](https://github.com/aws/aws-cdk/blob/ab7668197b1d7d7d08654d49df0c5ad9cb61b960/packages/%40aws-cdk/aws-dynamodb/lib/table.ts#L538) declartion which is providing invalid metrics or not providing any metircs at all. So there is a new method (metricThrottledRequestsForOperation) provided as alternative and recommended according to documentation but it's not part of the ITable interface. If an object is declared with ITable type then the recommended method can't be accesed.

```

  /**
   * How many requests are throttled on this table
   *
   * Default: sum over 5 minutes
   *
   * @deprecated Do not use this function. It returns an invalid metric. Use `metricThrottledRequestsForOperation` instead.
   */
  public metricThrottledRequests(props?: cloudwatch.MetricOptions): cloudwatch.Metric {
    return this.metric('ThrottledRequests', { statistic: 'sum', ...props });
  }

  /**
   * How many requests are throttled on this table, for the given operation
   *
   * Default: sum over 5 minutes
   */
  public metricThrottledRequestsForOperation(operation: string, props?: cloudwatch.MetricOptions): cloudwatch.Metric {
    return new cloudwatch.Metric({
      ...DynamoDBMetrics.throttledRequestsSum({ Operation: operation, TableName: this.tableName }),
      ...props,
    }).attachTo(this);
  }
```

### Reproduction Steps

if an object is declared with `ITable` as type then only `getThrottledMetrics` can be accessed and not `metricThrottledRequestsForOperation`

```
export class DynamoDBTableMetricGenerator {

    private readonly dynamoDbTable: ITable;

    constructor(dynamoDbTable: ITable) {
        this.dynamoDbTable = props.dynamoDbTable;
    }

    /**
     * Returns metircs for throttled requests on the table for all the operations passed
     */
    getThrottledMetrics(operations: strings[], props: MetricOptions): Metric[] {
         operations.forEach((operation) => {
                this.dynamoDbTable.metricThrottledRequests({
                    label: operation,
                    period: Duration.minutes(1),
                    dimensions: {
                        TableName: this.dynamoDbTable.tableName,
                        Operation: operation,
                    },
                }),
            });
        }
    }
```

### Possible Solution

If `metricThrottledRequestsForOperation` is added to the `ITable` interface then the object can access it and use accordingly

```
export class DynamoDBTableMetricGenerator {

    private readonly dynamoDbTable: ITable;

    constructor(dynamoDbTable: ITable) {
        this.dynamoDbTable = props.dynamoDbTable;
    }

    /**
     * Returns metircs for throttled requests on the table for all the operations passed
     */
    getThrottledMetrics(operations: strings[], props: MetricOptions): Metric[] {
         operations.forEach((operation) => {
                this.dynamoDbTable.metricThrottledRequestsForOperation(operation, {
                    label: operation,
                    period: Duration.minutes(1),
                    dimensions: {
                        TableName: this.dynamoDbTable.tableName,
                        Operation: operation,
                    },
                }),
            });
        }
    }
```

### CDK CLI Version

3

### Node.js Version

14.x

### OS

GNU/Linux

### Language

Typescript

**Comment by marciocadev** [comment]
I want to take that but I have some questions

I saw the method `metricThrottledRequestsForOperation` and there's two inputs, than I saw `metricSystemErrorsForOperations` and that method have only one with a proper interface `SystemErrorsForOperationsMetricOptions` who extends Cloudwatch `MetricOptions` and add `Operation[]`

I think will be good if we change some thinks in this file like

```ts
export interface SystemErrorsForOperationsMetricOptions extends cloudwatch.MetricOptions {
```
change to 
```ts
export interface OperationsMetricOptions extends cloudwatch.MetricOptions {
```

<hr/>

```ts
metricSystemErrorsForOperations(props?: SystemErrorsForOperationsMetricOptions): cloudwatch.IMetric;
```
change to 
```ts
metricSystemErrorsForOperations(props?: OperationsMetricOptions ): cloudwatch.IMetric;
```

<hr/>

```ts
metricThrottledRequestsForOperation(operation: string, props?: cloudwatch.MetricOptions): cloudwatch.Metric;
```
change to 

```ts
metricThrottledRequestsForOperation(props?: OperationsMetricOptions ): cloudwatch.Metric;
```

That way we can remove the `metricThrottledRequests` from `ITable` and `TableBase` and try to remove more deprecated fields in `table.ts`

**Comment by VarunWachaspati** [comment]
Raised a [PR](https://github.com/aws/aws-cdk/pull/22000) to add the recommended method `metricThrottledRequestsForOperation()` to the ITable interface.
