### ISSUE TITLE
(aws-s3): Cannot enable bucket key for SSE-KMS with AWS managed key

### ISSUE THREAD

**Issue by TymoteuszGach** [aws/aws-cdk#21961]
### Describe the bug

I'm trying to enable bucket key for a bucket with KMS_MANAGED encryption (SSE-KMS with AWS managed key), but stack synthesis fails.

### Expected Behavior

I would expect CDK to accept setting bucket key for a bucket with KMS_MANAGED encryption. You can do that in AWS console:

<img width="758" alt="image" src="https://user-images.githubusercontent.com/7798607/189054087-4f15631d-0192-449e-a104-18b669bd63b8.png">

### Current Behavior

Stack synthesis fails with the following error message:
`Error: bucketKeyEnabled is specified, so 'encryption' must be set to KMS (value: MANAGED)`

### Reproduction Steps

Create a new bucket with the following configuration and synthesise the stack.

`
new Bucket(scope, "Bucket", {
        bucketName: "my-bucket",
        encryption: BucketEncryption.KMS_MANAGED,
        bucketKeyEnabled: true,
});
`

### CDK CLI Version

2.29.1

### Node.js Version

v14.19.0

### OS

macOS Monterey 12.5.1

### Language

Typescript

### Language Version

TypeScript (4.5.5)

**Comment by indrora** [comment]
* Update to a recent version of the CDK, please
* When using `encryption: KMS_MANAGED`, you don't set `bucketKeyEnabled`. 

See https://docs.aws.amazon.com/cdk/api/v1/docs/aws-s3-readme.html#encryption for examples.

**Comment by TymoteuszGach** [comment]
@alekasw I also don't know why it has been closed. I thought that maybe I'm not getting something...

I workaround it using raw override, what produces a correct CloudFormation resource:

`const bucket = new Bucket(this, "my-bucket", {
        bucketName: "my-bucket",
        encryption: BucketEncryption.KMS_MANAGED,
});

const cfnBucket = bucket.node.defaultChild as CfnBucket;
cfnBucket.addPropertyOverride("BucketEncryption.ServerSideEncryptionConfiguration.0.BucketKeyEnabled", true);`
