### ISSUE TITLE
aws-cdk-lib 2.41.0: throws aws-cdk-lib.cx_api.CloudAssembly error

### ISSUE THREAD

**Issue by marcin2x4** [aws/aws-cdk#21966]
### Describe the bug

When running `cdk synth` in my project I'm getting an error:

![obraz](https://user-images.githubusercontent.com/71531928/189146885-44ea0aca-56b2-4f8f-82ce-422d65f11e1d.png)

### Expected Behavior

`cdk synth` works correctly

### Current Behavior

`ValueError: Unknown type: aws-cdk-lib.cx_api.CloudAssembly` is thrown.

### Reproduction Steps

Build any generic CDK project with listed dependencies below and run `cdk synth`.

### Possible Solution

Workaround: downgrade `pip install aws-cdk-lib==2.35.0` fixed the issue.

### CDK CLI Version

2.41.0

### Node.js Version

14.20.0

### OS

WSL2 on Windows 10

### Language

Python

**Comment by marcin2x4** [comment]
@corymhall , below are my resources:

`app.py`

```
from aws_cdk import App, Aspects, Tags
from db.db import CdkAppStack
from db.stack_configuration import CloudFormationStackConfiguration
from swa_cdk_core import LmGlobalDenyAspect

app = App()
stack_configuration = CloudFormationStackConfiguration(app)
CdkAppStack(app, stack_configuration.stack_name)

Aspects.of(app).add(LmGlobalDenyAspect())

app.synth()
```

`db.py`
```

from aws_cdk import (
    aws_ec2 as ec2,
    aws_glue as glue,
    aws_iam as iam,
    aws_kms as kms,
    Stack,
)
from constructs import Construct

from db.stack_configuration import CloudFormationStackConfiguration
from db.resources import Resources


class CdkAppStack(Stack):
    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        stack_configuration = CloudFormationStackConfiguration(self)
        lm_resources = Resources(self, "Resources")
```

`resources.py`

```
from constructs import Construct

from swa_cdk_core import (
    AccountCustomResource,
    SubnetCustomResource,
    VPCCustomResource,
)

from db.stack_configuration import (
    CloudFormationStackConfiguration,
)


class LmResources(Construct):
    def __init__(self, scope: Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        stack_configuration = CloudFormationStackConfiguration(self)

        self.account = AccountCustomResource(
            self,
            "Account"
        )
```

`stack_config.py`

```
import aws_cdk
from db.bamboo_pipeline_properties import CloudForgeProperties


class CloudFormationStackConfiguration(CloudForgeProperties):
    def __init__(self, app: aws_cdk.App):
        super().__init__(app)

        self.stack_name = f"{self.artifact_key}-{self.environment_key}"
```

**Comment by peterwoodworth** [comment]
I can't reproduce this either, some of the reproduction code you've provided seem to use your own custom modules or some other modules. Is there any way you can share a minimal reproduction with only classes from CDK package?

**Comment by marcin2x4** [comment]
I'll try to prepare working example.

**Comment by pjhavariotis** [comment]
I have the same issue.
CDK version = **2.50.0 (build 4c11af6)**
Python version = **Python 3.10.7**

**Comment by peterwoodworth** [comment]
There's likely something going wrong in each of your individual environments. We can't reproduce this as-is, so we'll need a way to consistently reproduce this in any environment to be able to help out
