### ISSUE TITLE
Release notes: Broken links

### ISSUE THREAD

**Issue by jhockett** [aws/aws-cdk#21969]
### Describe the issue

Broken links for recent 1.x [release notes](https://github.com/aws/aws-cdk/releases) => https://github.com/aws/aws-cdk/blob/bump/1.172.0/CHANGELOG.md

### Links

https://github.com/aws/aws-cdk/releases
https://github.com/aws/aws-cdk/blob/bump/1.172.0/CHANGELOG.md
https://github.com/aws/aws-cdk/blob/bump/1.171.0/CHANGELOG.md

**Comment by peterwoodworth** [comment]
Thanks for letting us know we have a broken link in our release notes @jhockett 

V1 is in maintenance mode and not receiving any new features or fixes aside from highly critical fixes, so it's possible we won't have the time nor necessity to fix this. Regardless, we'll get to it if we can!
