### ISSUE TITLE
aws-sns: Support setting of delivery status logging with the CDK

### ISSUE THREAD

**Issue by DanielBauman88** [aws/aws-cdk#21971]
### Describe the feature

[This](https://docs.aws.amazon.com/sns/latest/dg/sns-topic-attributes.html) does not appear to be supported right now.

This does not currently seem to be supported by cloudformation but the same custom resource workaround used for log retention policy could unblock cdk support.

### Use Case

This lack of functionality is particularly frustrating because security hub notifies about this issue but then customers have no way to easily comply in an automated fashion using cdk/cfn (the best practice tools for deploying infra).

https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#fsbp-sns-2

### Proposed Solution

Best option: Get cloudformation support and natively support setting this property on the topic
Second best option: Support this via a custom resource built into the cdk

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

any

### Environment details (OS name and version, etc.)

any

**Comment by kaizencc** [comment]
Thanks for opening the feature request, @DanielBauman88! I agree with both proposed solutions. Using a custom resource would work, but I'm wary of introducing more custom resources to the CDK without being sure of their necessity. Lets wait and see if this issue gets more support and/or wait and see if CloudFormation will come through.

**Comment by DanielBauman88** [comment]
Here is a CloudFormation issue tracking the same: https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/66

As this is required to comply with security-hub I think it is a pretty strong case for its necessity.

**Comment by kaizencc** [comment]
Great! As soon as this is in CloudFormation I'm happy to support this in the CDK.

**Comment by ZackKanter** [comment]
> Great! As soon as this is in CloudFormation I'm happy to support this in the CDK.

Now that [this has CloudFormation support](https://aws.amazon.com/about-aws/whats-new/2023/12/amazon-sns-configuring-delivery-status-logging-aws-cloudformation/), it would be great to get this into CDK.
