### ISSUE TITLE
ImportError: cannot import name 'BootstrapRole' from 'aws_cdk.cloud_assembly_schema'

### ISSUE THREAD

**Issue by jh-ecomp** [aws/aws-cdk#21985]
### Describe the bug

When i tried to synthesize an empty stack that ImportError occurred

### Expected Behavior

I should see output beginning with YAML code

### Current Behavior

An ImportError ocurred.
```
Traceback (most recent call last):
  File "C:\Users\joao\Documentos\cdk_projects\test1\app.py", line 4, in <module>
    import aws_cdk as cdk
  File "C:\Python310\lib\site-packages\aws_cdk\__init__.py", line 1135, in <module>
    from .cloud_assembly_schema import (
ImportError: cannot import name 'BootstrapRole' from 'aws_cdk.cloud_assembly_schema' (C:\Python310\lib\site-packages\aws_cdk\cloud_assembly_schema\__init__.py)
Subprocess exited with error 1
```

### Reproduction Steps

Open the project directory in VSCode, in terminal type:

```
cdk init --language python
.\source.bat
pip install -r requirements.txt
cdk synth
```

### CDK CLI Version

2.41.0 (build 6ad48a3)

### Node.js Version

v16.17.0

### OS

Windows 10 Enterprise

### Language

Python

### Language Version

3.10.7

### Other information

I just followed what was in the documentation to create a serverless application from AWS itself [Creating a serverless application using the AWS CDK](https://docs.aws.amazon.com/pt_br/cdk/v2/guide/serverless_example.html)

**Comment by rix0rrr** [comment]
Does not reproduce for me if I run these commands:

```
npx cdk@2.41.0 init --language python
source .venv/bin/activate.fish
pip install -r requirements.txt
npx cdk@2.41.0 synth
```

That's not *exactly* the same, but it does the same things on my system, and this error should not be OS-dependent.

-------

Looking at your error message, you seem to have a global install of CDK:

```
  File "C:\Python310\lib\site-packages\aws_cdk\__init__.py", line 1135, in <module>
                         ^^^^^^^^^^^^^^^^^^^^^^^ ----- there
```

Which might be fighting with a virtual-env local install (the versions are probably different).

You should probably get rid of your global version and do virtual-env version management only.
