### ISSUE TITLE
@aws-cdk_aws-ec2.CfnRoute: Add region support

### ISSUE THREAD

**Issue by Chompetto** [aws/aws-cdk#21983]
### Describe the feature

Be able to provide an additional region parameter to the creation of Routes via new CfnRoute(....) from the CfnRouteProps type.
If not provided it will default to the current region it is executing in.

### Use Case

When creating a new Route you can only create it for the region you are working in.  This is detrimental when working with Vpc Peering Connections since you will only be able to create the appropriate routes in the region you initiate it.  being able to perform this action in one stack would be the ideal solution.

### Proposed Solution

```
new CfnRoute(this, "Id", new CfnRouteProps
{
    RouteTableId = "rtb-Id",
    VpcPeeringConnectionId = "pcx-Id",
    //Proposed change.   This will lookup "rtb-Id" in us-west-2 instead of the current region.
    Region = "us-west-2"  
});
```

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.40.0 (build 56ba2ab)

### Environment details (OS name and version, etc.)

N/A

**Comment by corymhall** [comment]
@Chompetto the `Cfn***` (i.e. L1) constructs are generated directly from the CloudFormation resource specification which means that this is a limitation in CloudFormation. I would recommend creating an issue on the [CloudFormation roadmap](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/)
