### ISSUE TITLE
(aws-lambda): Add property to delete older lambda versions 

### ISSUE THREAD

**Issue by ranjith-jagadeesh** [aws/aws-cdk#21998]
### Describe the feature

1. During every deployment, lambda create's a new version and publishes the same.
2. After 20 or 30 deployments, we have 20 or 30 versions sitting in our lambda, which we don't need.
3. Need an option delete the older versions, such as retain last five versions and delete the remaining 

The feature is more or less like a prune plugin option in serverless
https://www.serverless.com/plugins/serverless-prune-plugin

### Use Case

If we keep on deploying the new version without deleting the older versions, in sometime we may run out of 75GB memory allocated for lambda code storage for every accounts.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.39.1

### Environment details (OS name and version, etc.)

Mac 11.3.1

**Comment by peterwoodworth** [comment]
It's difficult for CDK to introduce a feature like this because the previous versions aren't controlled by CDK/CloudFormation anymore. We would need to use a custom resource to implement this feature and be able to delete previous versions.

What is the advantage to controlling this through CDK rather than deleting previous unused versions through other means?

**Comment by mt-jmccarthy** [comment]
> What is the advantage to controlling this through CDK rather than deleting previous unused versions through other means?

Could you provide an example of what "other means" you are referring to? 

This doesn't seem so much as an "advantage" but a basic feature for the cdk. The cdk enables other key necessities such as aliasing for gradual deployments/reversions. This is starkly contrasted with having the cdk only support an "all-or-nothing" strategy when managing lambda version history.

**Comment by peterwoodworth** [comment]
Well, I'm not sure how this state is being achieved in the first place. Using our `currentVersion` prop will ensure that previous versions get removed and deleted upon update to the function. Unless you specify `RETAIN` on a `Lambda::Version` resource's retain policy, I'm not sure how the versions will pile up. Could someone explain how this state of having 20+ versions is reached with normal CDK usage?

> Could you provide an example of what "other means" you are referring to?

Like I said above, a custom resource _will_ be necessary if the resource(s) are no longer controlled by your CDK app and you want to delete old versions through CDK.

**Comment by ranjith-jagadeesh** [comment]
Commenting to reopen the issue again

**Comment by elhedran** [comment]
This should be fixed or addressed somehow - CDK leaves old versions of lambda functions behind - Trusted advisor creates critical warnings for runtimes of old lambda versions that are never used.  Between the two of them one of them should be changed to acknowledge the behavior of the other and not create otherwise avoidable work for the customer.

**Comment by karantan** [comment]
I achieved this by checking out the old version I wanted to delete using Git and then running the command `sls remove`. This may not be the best option, but it's still better than manually clicking through the AWS web UI.

**Comment by jaksky** [comment]
We use Retain on older version with current_verssion usage as we are using it with combination of API GW where we want to use a canary release feature together with connected lambda behind it. Deleting old versions or set a retention policy on lambda version would be highly desirable feature and it is funny that this capablity is missing!

**Comment by ogescalante** [comment]
This is highly desirable !
