### ISSUE TITLE
(redshift-alpha): reboot Clusters for Parameter updates

### ISSUE THREAD

**Issue by dontirun** [aws/aws-cdk#22009]
### Describe the feature

Add an optional  `rebootForParameterChanges` property to  Redshift `Cluster`s that reboots the cluster when there are changes to the Parameter group

### Use Case

In most cases existing Clusters [must be rebooted]( https://docs.aws.amazon.com/redshift/latest/mgmt/working-with-parameter-groups.html) to apply parameter changes.  It would be nice to automatically reboot the Cluster instead of having to manually do it through the CLI or console 

### Proposed Solution

1. Add an optional  `rebootForParameterChanges` property 
2.  Create a [Trigger](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.triggers-readme.html)  and a Custom Resource Singleton Lambda to reboot the cluster if the associated Parameter Group changes
3. The Lambda function only performs actions for Custom Resource `On Create` and `On Update` actions
4. The Lambda function checks the [parameterApplyStatus](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/securityhub/model/AwsRedshiftClusterClusterParameterStatus.Builder.html#parameterApplyStatus-java.lang.String-) of the Parameter Group
    - If the Status is `in-sync` do nothing
    - If the Status is `applying` wait and recheck
    - If the Status is `pending-reboot` reboot the cluster

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

N/A

### Environment details (OS name and version, etc.)

N/A

**Comment by peterwoodworth** [comment]
Thanks for the request @dontirun, this is a great feature request that I think we should have!

We accept contributions - Check out our [contributing guide](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) if you're interested - there's a low chance the team will be able to address this soon but we'd be happy to review a PR 🙂
