### ISSUE TITLE
(lambda-nodejs): Documentation confusingly imports as `lambda`

### ISSUE THREAD

**Issue by kylelaker** [aws/aws-cdk#22003]
### Describe the issue

In many projects, `@aws-cdk/aws-lambda` gets imported as `lambda`; this makes the code examples at https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda_nodejs-readme.html confusing as users may expect that the existing import they have for the `aws-lambda` package will work.

The documentation is not incorrect if you have your imports the same as in the [`default.ts-fixture`](https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/aws-lambda-nodejs/rosetta/default.ts-fixture) file, doing

```ts
import * as lambda from '@aws-cdk/aws-lambda-nodejs';
``` 

But I'd argue that's an unlikely way for users to use this package (as they'll often still need other exported values from `aws-lambda`). 

I'd be happy to open a PR to rename this to something like:

```ts
import * as lambdaNodejs from '@aws-ckd/aws-lambda-nodejs';
```

and to make corresponding updates to the README etc; but I wanted to open an issue to discuss before implementing.

### Links

- https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda_nodejs-readme.html#externals

**Comment by peterwoodworth** [comment]
I think this makes a lot of sense @kylelaker, I agree with your claim that this is an unlikely way to use the package. We'd be happy to accept a PR to change our documentation to make this distinct from the lambda package! I'm not sure what the best name for the new import variable would be though, we could use what you've proposed for now and see if we can think of something better during the review of the PR
