### ISSUE TITLE
(route53): cross account zone delegation: unable to remove root hosted zone when delegated records are in place

### ISSUE THREAD

**Issue by moltar** [aws/aws-cdk#22001]
### Describe the bug

When the root (parent) zone contains records created via delegation, then it becomes impossible to delete said zone.

Error is raised by CF:

> The specified hosted zone contains non-required resource record sets and so cannot be deleted.

### Expected Behavior

Ability to remove the zone.

### Current Behavior

The zone removal fails with error:

> The specified hosted zone contains non-required resource record sets  and so cannot be deleted.

### Reproduction Steps

1. created root zone
2. created a delegated record
3. try to destroy the stack with the root zone

### Possible Solution

Not sure if anything is even possible here, as I understand that the root zone has no awareness of which records are delegated, and whether or not it is safe to remove them. Some state needs to be maintained somewhere about which records are delegated. And there is no way to tag a specific record.

### Additional Information/Context

N/A

### CDK CLI Version

N/A

### Framework Version

2.39.1

### Node.js Version

16

### OS

macOS

### Language

Typescript

### Language Version

N/A

### Other information

N/A

**Comment by moltar** [comment]
Ping @ayush987goyal, @phoefflin

**Comment by gshpychka** [comment]
I wouldn't want this to work any other way, to be honest. The consumer stack (the one that created the records) would be broken and it wouldn't know it. You shouldn't be able to remove a dependency before removing its dependents, and those records depend on the zone (and aren't managed by the current stack, so cannot be removed).

**Comment by peterwoodworth** [comment]
Yeah this isn't up to us, and I don't know how else it would work. Thanks for submitting the issue, but there's no action we can take here
