### ISSUE TITLE
(aws-cdk v1.116.0): (Issue with AWS Elasticsearch Domain deployment)

### ISSUE THREAD

**Issue by gagg0412** [aws/aws-cdk#22018]
### Describe the bug

I am trying to deploy  AWS::Elasticsearch::Domain with aws cdk version 1.116.0 and m getting the below error after enabling the custom endpoint and enableinternet access.
I guess it was working before with previous deployments but suddenly the issue comes with below error.

`5:37:59 pm | CREATE_FAILED        | AWS::Elasticsearch::Domain |
You must enable EnforceHTTPS in the domain endpoint options to use advanced security. (Service: AWSElasticsearch; Status Code: 400; Error Code: ValidationException; Re
quest ID: d14ee2a0-9580-49a4-a247-759e5f7f4c73; Proxy: null)

	exports.Kernel._create (/tmp/jsii-java-runtime13923705977621654634/lib/program.js:5592:179)
	\_ exports.Kernel.create (/tmp/jsii-java-runtime13923705977621654634/lib/program.js:5400:29)
	\_ exports.KernelHost.processRequest (/tmp/jsii-java-runtime13923705977621654634/lib/program.js:6618:36)
	\_ exports.KernelHost.run (/tmp/jsii-java-runtime13923705977621654634/lib/program.js:6592:48)
	\_ Immediate._onImmediate (/tmp/jsii-java-runtime13923705977621654634/lib/program.js:6593:46)
	\_ processImmediate (internal/timers.js:464:21)
`

### Expected Behavior

It should create the ES Domain with custom endpoint

### Current Behavior

Getting error while creating the ES Domain.

`5:37:59 pm | CREATE_FAILED        | AWS::Elasticsearch::Domain | ciboltdev
You must enable EnforceHTTPS in the domain endpoint options to use advanced security. (Service: AWSElasticsearch; Status Code: 400; Error Code: ValidationException; Re
quest ID: d14ee2a0-9580-49a4-a247-759e5f7f4c73; Proxy: null)

	exports.Kernel._create (/tmp/jsii-java-runtime13923705977621654634/lib/program.js:5592:179)
	\_ exports.Kernel.create (/tmp/jsii-java-runtime13923705977621654634/lib/program.js:5400:29)
	\_ exports.KernelHost.processRequest (/tmp/jsii-java-runtime13923705977621654634/lib/program.js:6618:36)
	\_ exports.KernelHost.run (/tmp/jsii-java-runtime13923705977621654634/lib/program.js:6592:48)
	\_ Immediate._onImmediate (/tmp/jsii-java-runtime13923705977621654634/lib/program.js:6593:46)
	\_ processImmediate (internal/timers.js:464:21)
`

### Reproduction Steps

Use Aws-cdk version 1.116.0
Trying to create the stack using yaml file.
`---
environmentName: xxxxx
region: us-east-1
accountID: xxxxxxx

networkConfig:
   enableInternetAccess: true
   vpc: xxxxx
   subnetIds:
      - xxxx
      - xxxx
      - xxxx

opensearchConfig:
   domainName: xxx
   stackName: xxxx
   availabilityZoneCount: 3
   version: 7.10
   enableVersionUpgrade: true
   masterNodeCount: 3
   masterInstanceType: m6g.large.elasticsearch
   dataNodeCount: 3
   dataInstanceType: m6g.large.elasticsearch
   dataNodeDiskSize: 300
   ultraWarmEnabled: true
   ultraWarmNodeCount: 2
   ultraWarmInstanceType: ultrawarm1.medium.elasticsearch
   appLogsEnabled: true
   slowLogsEnabled: true
   indexSlowLogsEnabled: true
   auditLogsEnabled: false
   appLogsCWLogGroupRetention: 7
   slowLogsCWLogGroupRetention: 7
   indexSlowLogsCWLogGroupRetention: 7
   auditLogsCWLogGroupRetention: 7
   securityGroupConfig:
      id: xxxx
      name: xxxx
      description: Security group for Opensearch xxxx
   customEndpointConfig:
      enabled: true
      endpoint: 
      certificateArn: 
   opensearchSecurityOptions:
      enabled: true
      masterCredentialsConfig:
         enabled: true
         lookup: false
         masterPasswordSecretName:
         masterUserName: 
         masterUsePassword: 
`

### CDK CLI Version

1.116.0

### Node.js Version

v14.20.0

### OS

Ubuntu

### Language

Java

**Comment by peterwoodworth** [comment]
@gagg0412 CDK v1 is in maintenance mode, meaning we aren't fixing any issues with v1 aside from major bugs (i.e. regressions). This version of v1 came out before v2 launched, and it also uses ElasticSearch which is a deprecated service. Please try upgrading to v2 and using OpenSearch instead of ElasticSearch, and see if your issues still persist. Thanks!
