### ISSUE TITLE
CLI: --require-approval=never doesn't work without tty

### ISSUE THREAD

**Issue by JanLikar** [aws/aws-cdk#22032]
### Describe the bug

--require-approval=never doesn't seem to work.

### Expected Behavior

The deploy sub-command should respect the `--require-approval` flag.

### Current Behavior

When invoking cdk with `npm exec cdk deploy --require-approval=never` I encountered the following error:

`Error: "--require-approval" is enabled and stack includes security-sensitive updated, but terminal (TTY) is not attached so we are unable to get a confirmation from the user.`

Oddly enough, `npm exec cdk deploy --require-approval never` (space instead of `=`) gives `No stacks match the name(s) never`.

### Reproduction Steps

`npm exec cdk deploy --require-approval=never` with a changeset that requires approval and without a TTY attached.

### CDK CLI Version

2.41.0

### Node.js Version

16.17.0

### OS

Ubuntu

### Language

Python

**Comment by peterwoodworth** [comment]
When I test with a TTY, i don't have to submit my approval. Do you know the best way to test this without a TTY?

**Comment by JanLikar** [comment]
Maybe you can try this: https://superuser.com/questions/1430872/how-to-simulate-a-shell-without-tty

**Comment by rix0rrr** [comment]
Please run again with `-v` and paste the log here. There must be something wrong with argument parsing then, because the logic seems correct:

https://github.com/aws/aws-cdk/blob/78c5834884f13b6aa59d760150f67373b855935b/packages/aws-cdk/lib/cdk-toolkit.ts#L207

**Comment by JanLikar** [comment]
Oddly enough, I can't reproduce.

It could have been a glitch in the Matrix, a high energy particle that got lost on his way to Grandma or (unimaginably) I somehow managed to overlook a typo multiple times in a row. We might never know.
