### ISSUE TITLE
Error [ValidationError]: Template error: instance of Fn::GetAtt references undefined resource

### ISSUE THREAD

**Issue by argarinpauljohn** [aws/aws-cdk#22046]
### Describe the bug

I'm new to CDK.

I'm using `glue.CfnConnection` construct as seen below. Furthermore, it uses the `glue.CfnConnection.PhysicalConnectionRequirementsProperty` property inside.

When `cdk deploy` is executed, I get this error: ** Template error: instance of Fn::GetAtt references undefined resource** on the `network_stack.glue_security_group.security_group_id` resource.

`network_stack` is a separate stack. Checking the CloudFormation JSON output, `Fn::GetAtt` is produced instead of `Fn::ImportValue` that is used in cross-stack referencing.

Outside the `glue.CfnConnection`, for example the Redshift cluster, `network_stack.glue_security_group.security_group_id` gets referenced via `Fn::ImportValue` which is the expected behavior.

Would you be able to help me with this?

```
glue.CfnConnection(
            self,
            "GlueConnection",
            catalog_id=self.account,
            connection_input=glue.CfnConnection.ConnectionInputProperty(
                connection_type="JDBC",
                connection_properties=json.dumps(
                    {
                        "JDBC_URL": jdbc_url,
                        "USERNAME": db_password.secret_value_from_json("username").to_string(),
                        "PASSWORD": db_password.secret_value_from_json("password").to_string(),
                    }
                ),
                description="Redshift cluster Glue connection",
                name="glue_connection",
                physical_connection_requirements=glue.CfnConnection.PhysicalConnectionRequirementsProperty(
                    availability_zone="ap-northeast-1a",
                    security_group_id_list=[network_stack.glue_security_group.security_group_id],
                    subnet_id=network_stack.vpc.select_subnets(
                        subnet_group_name=network_stack.GENERAL_PRIVATE_SUBNETS
                    ).subnet_ids[0],
                ),
            ),
        )
```

### Expected Behavior

Produce `Fn::ImportValue` when referencing cross-stack resource inside `glue.CfnConnection`.

### Current Behavior

Produces `Fn::GetAtt` when referencing cross-stack resource inside `glue.CfnConnection`.

### Reproduction Steps

Create a security group in a different stack then reference it inside a new stack in `glue.CfnConnection` construct.

### CDK CLI Version

2.41.0 (build 6ad48a3)

### Node.js Version

v16.17.0

### OS

MacOS Monterey v 12.2.1, Apple M1

### Language

Python

**Comment by yukinakanaka** [comment]
Same here. ✋

**Comment by argarinpauljohn** [comment]
It is worth mentioning that the current workaround is to use the experimental (`aws_cdk.aws_glue_alpha.Connection`)[https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_glue_alpha/Connection.html].

**Comment by peterwoodworth** [comment]
I'm not able to reproduce this using the Cfn construct @argarinpauljohn, it produces the `Fn::ImportValue` just fine for me when passing in a security group from another stack and referencing its security group ID in `Connection.connectionInput.physicalConnectionRequirements`. I'm curious how you have things set up beyond the stack which is referencing this value

**Comment by argarinpauljohn** [comment]
Hi @peterwoodworth! Thanks for the response.

In a separate stack, same level as stack that references the security group:

```
        self.glue_security_group = SecurityGroup(self, "RedshiftGlueSG", vpc=self.vpc, allow_all_outbound=True)
        self.glue_security_group.add_ingress_rule(
            peer=Peer.ipv4(self.vpc.vpc_cidr_block), connection=Port.tcp(5439)
        )
        self.glue_security_group.connections.allow_from(
            other=self.redshift_glue_security_group, port_range=Port.all_tcp()
        )
```
inside a `Stack` instance

**Comment by peterwoodworth** [comment]
This is similar to what I did, but I copied what you've done just in case and I still can't reproduce this behavior 😞 

Inside the stack where you create the connection, how are you defining the `network_stack` object?

**Comment by argarinpauljohn** [comment]
@peterwoodworth 

Like this: `from .network_stack import NetworkStack`

and then inside the another stack:

```
class Data(Stack):
    def __init__(
        self,
        scope: Construct,
        env_name: str,
        network_stack: NetworkStack
        ...
```

**Comment by peterwoodworth** [comment]
I'll need someone to put up a repo which I can easily clone and run to reproduce this behavior, I don't have enough information here to be able to do so myself
