### ISSUE TITLE
pipelines: Add logging options to codeBuildDefaults property

### ISSUE THREAD

**Issue by Voyen** [aws/aws-cdk#22045]
### Describe the feature

Add logging options to the codeBuildDefaults nested property of the pipelines.CodePipeline construct.

### Use Case

At my company we just enabled AWS Config and SecurityHub has generated a rule 'securityhub-codebuild-project-logging-enabled-abcxyz'.
This rule states that all CodeBuild projects must have at least one logging option enabled.

However the Build and Synth steps from the pipeline are always failing this check since the pipelines module doesn't allow specifying logging options on the nested CodeBuild projects.

### Proposed Solution

Add logging options to codeBuildDefault the same way that aws-codebuild.Project allows you to.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.35.0 (build 5c23578)

### Environment details (OS name and version, etc.)

Ubuntu 22.04.1 LTS (Jammy Jellyfish)

**Comment by rix0rrr** [comment]
Sounds reasonable, should be fairly easy to add.
