### ISSUE TITLE
(integ-tests): Can't make two awsApiCall for the same service and api in a given context 

### ISSUE THREAD

**Issue by dontirun** [aws/aws-cdk#22043]
### Describe the bug

While fumbling around with integration tests I received the following error

`Error: There is already a Construct with name 'AwsApiCallRedshiftdescribeClusters' in Stack [DeployAssert]`

I believe this is because I had two calls for the same service and api

### Expected Behavior

I can make two calls to the same service API combo

### Current Behavior

I can't make two calls to the same service API combo

### Reproduction Steps

```ts
import * as integ from '@aws-cdk/integ-tests';
import * as cdk from '@aws-cdk/core';

const app = new cdk.App();
const stack = new cdk.Stack(app, 'aws-cdk-redshift-cluster-database');


const test = new integ.IntegTest(app, 'aws-cdk-redshift-reboot-test', {
  testCases: [stack],
  stackUpdateWorkflow: true,
  diffAssets: true,
});


const describe = test.assertions.awsApiCall('Redshift', 'describeClusters', {
  ClusterIdentifier: cluster.clusterName,
});

const describe2 = test.assertions.awsApiCall('Redshift', 'describeClusters', {
  ClusterIdentifier: cluster.clusterName,
});

```

### Possible Solution

https://github.com/aws/aws-cdk/blob/1f03e8c40a682a3b5aae90560c84017cfe62762e/packages/%40aws-cdk/integ-tests/lib/assertions/private/deploy-assert.ts#L53

Maybe something like this?

```ts
  private static serviceAPICounter = new Map<string, number>();

...

  public awsApiCall(service: string, api: string, parameters?: any): IAwsApiCall {
    let combo = `AwsApiCall${service}${api}`
    const count = (DeployAssert.serviceAPICounter.get(combo) ?? 0) + 1
    DeployAssert.serviceAPICounter.set(combo, count)
    return new AwsApiCall(this.scope, `${combo}${count}`, {
      api,
      service,
      parameters,
    });
  }
```

### CDK CLI Version

2.41.0

### Node.js Version

v16.16.0

### OS

OsX

### Language

Typescript

**Comment by peterwoodworth** [comment]
Thanks for the report @dontirun,

We could either change how the logical id is built altogether (which would change the logical id for existing instances so we'd likely need a feature flag), or what's more preferable is to somehow detect if the same API call has already been used, and then adjusting the logical ID from there if that's the case. However I'm not sure how feasible the latter is without looking more into it

**Comment by misterjoshua** [comment]
I'm working around this right now by importing from `DeployAssert`:

```typescript
import { AwsApiCall, IntegTest } from '@aws-cdk/integ-tests-alpha';
import { DeployAssert } from '@aws-cdk/integ-tests-alpha/lib/assertions/private/deploy-assert';

// ...

declare const integTest: IntegTest;

const deployAssert = integTest.assertions;
if (!DeployAssert.isDeployAssert(deployAssert)) {
  throw new Error('Expected DeployAssert');
}

// Extract the assertion scope from the DeployAssert because upstream
// implementation fails to allow multiples of the same aws api call
// due to insufficient uniqueness in the logical ids.
const assertionScope = deployAssert.scope;

const assertion1 = new AwsApiCall(assertionScope, 'First', {
  service: 'TheService',
  api: 'theApi',
  parameters: { /* ... */ },
});

const assertion1 = new AwsApiCall(assertionScope, 'Second', {
  service: 'TheService',
  api: 'theApi',
  parameters: { /* ... */ },
});
```

**Comment by misterjoshua** [comment]
> Thanks for the report @dontirun,
> 
> We could either change how the logical id is built altogether (which would change the logical id for existing instances so we'd likely need a feature flag), or what's more preferable is to somehow detect if the same API call has already been used, and then adjusting the logical ID from there if that's the case. However I'm not sure how feasible the latter is without looking more into it

@peterwoodworth perhaps `DeployAssert` could maintain and increment an internal counters.

https://github.com/aws/aws-cdk/blob/1162746d35f2e9bba0036ba9974c1e4e3b3701ed/packages/%40aws-cdk/integ-tests-alpha/lib/assertions/private/deploy-assert.ts#L62

```diff
+private awsApiCallCounter = 0;
 public awsApiCall(service: string, api: string, parameters?: any, outputPaths?: string[]): IApiCall {
     let hash = '';
     try {
       hash = md5hash(this.scope.resolve(parameters));
     } catch {}
+    const counterPart = this.awsApiCallCounter >= 1 ? this.awsApiCallCounter : '';
+    this.apiApiCallCounter++;
 
-    return new AwsApiCall(this.scope, `AwsApiCall${service}${api}${hash}`, {
+    return new AwsApiCall(this.scope, `AwsApiCall${service}${api}${hash}${counterPart}`, {
       api,
       service,
       parameters,
       outputPaths,
     });
   }
```
