### ISSUE TITLE
How to import existing access keys to cdk stack?

### ISSUE THREAD

**Issue by jatinmehrotra** [aws/aws-cdk#22044]
### Describe the bug

I have an existing user which has access keys associated with it, I want to manage ( key rotation ) this existing key with cdk, instead of managing existing key, it add secondary key.
How to manage/import existing keys to cdk.

### Expected Behavior

The existing key should be rotated and managed by cdk.

### Current Behavior

An alternate key is being added with existing access key.

### Reproduction Steps

- Create a user with access keys 
- Try to update keys by increasing `serial`, it will add new key to user and following deployment with increasing number of serial will result in rotation of the keys added by cdk but not existing keys.

 ```
import { CfnOutput, Duration, Stack, StackProps } from 'aws-cdk-lib';
import { Construct } from 'constructs';
import { aws_iam as iam } from 'aws-cdk-lib';
import { AccessKeyStatus, User } from 'aws-cdk-lib/aws-iam';


export class CdkStackoverflowStack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);
    const existingUserFromName = User.fromUserName(this, 'user-from-name-id', 'cdk-stackoverflow')
    const cfnAccessKey = new iam.AccessKey(this, 'MyCfnAccessKey', {
      user: existingUserFromName,
      // the properties below are optional
      serial: 2,
      status: AccessKeyStatus.ACTIVE,
    })
    new CfnOutput(this, 'accessSecretKey', { value: cfnAccessKey.secretAccessKey.unsafeUnwrap().toString() })
    new CfnOutput(this, 'accessKeyID', { value: cfnAccessKey.accessKeyId.toString() })
  }
}
```

### CDK CLI Version

2.40

### Node.js Version

16.17.0

### OS

macosx

### Language

Typescript

**Comment by rix0rrr** [comment]
Keys added by hand can never be removed by CDK. Remove them by hand.

At next rotation time the old key will be deleted.
