### ISSUE TITLE
(integ-tests): awsApiCall `Response object is too long`

### ISSUE THREAD

**Issue by dontirun** [aws/aws-cdk#22059]
### Describe the bug

When using `assertions.awsApiCall` my response object was too large and caused the integration test stack to fail deployment.

### Expected Behavior

I can limit the `outputPath` of the api call  like done here #https://github.com/aws/aws-cdk/issues/2825

### Current Behavior

I can't limit the output and get around the 4k response limit for CloudFormation

### Reproduction Steps

`integ.reproduction.ts`

```ts
import * as ec2 from '@aws-cdk/aws-ec2';
import { App, Stack, StackProps } from '@aws-cdk/core';
import * as integ from '@aws-cdk/integ-tests';
import { Construct } from 'constructs';
import * as redshift from '../lib';

class RedshiftEnv extends Stack {
  readonly cluster: redshift.Cluster

  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);

    const vpc = new ec2.Vpc(this, 'VPC');

    this.cluster = new redshift.Cluster(this, 'Cluster', {
      vpc: vpc,
      vpcSubnets: {
        subnetType: ec2.SubnetType.PUBLIC,
      },
      masterUser: {
        masterUsername: 'admin',
      },
    });
  }
}

const app = new App();
const stack = new RedshiftEnv(app, 'redshift-integ');
const test = new integ.IntegTest(app, 'LoggingBucketInteg', {
  testCases: [stack],
});

test.assertions.awsApiCall('Redshift', 'describeClusters', {
  ClusterIdentifier: stack.cluster.clusterName,
});

app.synth();
```

### Possible Solution

Implement an `outputPath` feature like done here #https://github.com/aws/aws-cdk/issues/2825 to limit the response object

### CDK CLI Version

2.41.0

### Node.js Version

v16.16.0

### OS

OsX

### Language

Typescript

**Comment by corymhall** [comment]
I'm working on an update where the assertions are done in the same handler instead of passing the data to another resource. Hopefully that will fix this issue.

**Comment by dontirun** [comment]
@corymhall I saw that https://github.com/aws/aws-cdk/pull/22238 was merged, but it didn't seem to fix the issue. Perhaps an easy way to fix the issue would be to use the bootstrap assets bucket as a proxy.

1. Make API Call
2. Upload Output of API Call JSON to the CDK Assets Bucket
3. Output S3 object Key
4. Assertion reads in and downloads the JSON from the Bucket
5. Nice to have: Another resource deletes all the uploaded objects after the tests

**Comment by corymhall** [comment]
Currently `awsApiCall` can serve two roles.

1. Make an API call in order to return a value that can be referenced elsewhere in the template
2. Make an API call and assert the results (don't need to return anything).

In order to accommodate the second we first flatten the results (if we need to) and then perform assertions and then return everything. What I want to do is change this around a little. We should perform assertions on the response (without flattening) and then if we also need to return a value we can flatten if needed and then _only_ return the value that is needed.
