### ISSUE TITLE
aws-rds: Generated RDS secret should include the r/o endpoint of a cluster

### ISSUE THREAD

**Issue by kpawar** [aws/aws-cdk#22050]
### Describe the feature

The RDS generated secret includes the host but there is no separate entry created for reader instance in the secret. It will be really helpful to include the reader instance host entry in the secret so that we don't have to separately create an ssm parameter to read the reader host from.

I can see this was previously raised under https://github.com/aws/aws-cdk/issues/11517 but the issue was closed without any resolution.

### Use Case

When a application can make use of read replicas, it would be awesome to have the reader endpoint in the secret.

### Proposed Solution

Currently the generated secret looks like this:
{
  "dbClusterIdentifier": "some-database-xyz987",
  "password": "somepass",
  "dbname": "theDbName",
  "engine": "postgres",
  "port": 5432,
  "host": "some-database-xyz987.cluster-abc123.eu-central-1.rds.amazonaws.com",
  "username": "aUserName"
}

Proposed solution would be to add an extra key for readerHost as given below:
{
  "dbClusterIdentifier": "some-database-xyz987",
  "password": "somepass",
  "dbname": "theDbName",
  "engine": "postgres",
  "port": 5432,
  "host": "some-database-xyz987.cluster-abc123.eu-central-1.rds.amazonaws.com",
   // notice the included `-ro`
  "readerHost": "some-database-xyz987.cluster-ro-abc123.eu-central-1.rds.amazonaws.com",
  "username": "aUserName"
}

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.41.0

### Environment details (OS name and version, etc.)

aws-cdk, cloudformation

**Comment by corymhall** [comment]
@kpawar the linked issue was closed because the content of the secret is managed by the
`AWS::SecretsManager::SecretTargetAttachment` resource.

I would suggest creating an issue on the [CloudFormation coverage roadmap](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap)
