### ISSUE TITLE
aws-cdk-lib/aws-dynamodb: Impossible to delete replica table

### ISSUE THREAD

**Issue by cartmanez** [aws/aws-cdk#22069]
### Describe the bug

Updating `Table` construct with some replication regions removed throws AccessDenied error. Stack update kind of succeeds but replica tables need to be removed manually

### Expected Behavior

Updating `Table` construct with some replication regions removed should actually remove replica table(s) and no errors should be thrown

### Current Behavior

Replica table(s) not removed because of access denied errors.

### Reproduction Steps

1. Deploy the following stack
```
class DynamoDbReplicaAccessDeniedDemo extends Stack {

    constructor(scope: Construct, id: string, props?: StackProps) {
        super(scope, id, props);

        new Table(this, 'DemoTable', {
            partitionKey: {
                name: 'keyA',
                type: AttributeType.STRING
            },
            replicationRegions: ['us-west-1', 'us-west-2']
        })
    }
}

new DynamoDbReplicaAccessDeniedDemo(app, 'ddb-replica-access-denied-demo', {
    env: {
        region: 'us-east-1'
    }
});
```

2. Then deploy updated version
```

class DynamoDbReplicaAccessDeniedDemo extends Stack {

    constructor(scope: Construct, id: string, props?: StackProps) {
        super(scope, id, props);

        new Table(this, 'DemoTable', {
            partitionKey: {
                name: 'keyA',
                type: AttributeType.STRING
            },
            replicationRegions: ['us-west-1'] //!!!! us-west-2 removed from here
        })
    }
}

new DynamoDbReplicaAccessDeniedDemo(app, 'ddb-replica-access-denied-demo', {
    env: {
        region: 'us-east-1'
    }
});

```
3. Observe the error in cloudformation events:
> Received response status [FAILED] from custom resource. Message returned: User: arn:aws:sts::<account-id>:assumed-role/ddb-replica-access-denied-OnEventHandlerServiceRol-AAAAAAAAAAAA/ddb-replica-access-denied-d-OnEventHandlerBBBBBBBBBB-CCCCCCCCCC is not authorized to perform: dynamodb:DeleteTableReplica on resource: arn:aws:dynamodb:us-west-2:<account-id>:table/ddb-replica-access-denied-demo-DemoTableAAAAAAAA-BBBBBBB because no identity-based policy allows the dynamodb:DeleteTableReplica action

4. Replica table in us-west-2 still present after stack update is complete

### CDK CLI Version

2.38.1

### Node.js Version

v14.20.0

### OS

GNU/Linux

### Language

Typescript

### Language Version

4.7.4

**Comment by rix0rrr** [comment]
Needs investigation, but the most likely cause is a missing dependency between the `dynamodb:*` policy and the CR

**Comment by alexandervandekleutab** [comment]
Also encountering this. Production stack is now stuck. Happened unpredictably... only on our environment with lots of data
