### ISSUE TITLE
(aws-stepfunctions): Add missing intrinsic function `States.JsonMerge`

### ISSUE THREAD

**Issue by gkkachi** [aws/aws-cdk#22068]
### Describe the feature

Support for the intrinsic function `States.JsonMerge` .
AWS Documentation: https://docs.amazonaws.cn/en_us/step-functions/latest/dg/amazon-states-language-intrinsic-functions.html#asl-intrsc-func-json-manipulate

### Use Case

Obvious

### Proposed Solution

Add `JsonPath.jsonMerge()` here:
https://github.com/aws/aws-cdk/blob/main/packages/@aws-cdk/aws-stepfunctions/lib/fields.ts

### Other Information

We could use `States.JsonMerge` like below, but syntax check fails when running `cdk deploy` .
We have to change some code to make it passed.

```
TaskInput.fromJsonPathAt('States.JsonMerge($.json1, $.json2, false)')
```

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.41.0

### Environment details (OS name and version, etc.)

macOS Big Sur 11.5

**Comment by kaizencc** [comment]
Hi @gkkachi, would be happy to accept a contribution for this. Labeling as `p2` just because we probably don't have bandwidth to pick this up right now, but would be happy to review a community contribution.
