### ISSUE TITLE
SSM: StringParameter.valueFromLookup should return undefined if SSM parameter not available

### ISSUE THREAD

**Issue by astef** [aws/aws-cdk#22064]
### Describe the feature

When using `ssm.StringParameter.valueFromLookup`, it crashes (not sure, but error is not catchable), when the parameter doesn't exist. It makes it unusable for scenarios with a fallback parameter.

### Use Case

For a short-lived infrastructure it's both important to be configurable (create a parameter & deploy), and have a nice fallback value (just deploy). SSM parameter is a perfect solution, since it can be resolved at synth time. It's very unfortunate, that currently it's impossible not to crash, when the value doesn't exist.

### Proposed Solution

Return undefined, instead of crashing, or expose a better API, with multiple fallback parameter names to check.

### Other Information

This issue was also discussed here: https://github.com/aws/aws-cdk/issues/7259

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2

### Environment details (OS name and version, etc.)

Any

**Comment by mascur** [comment]
Thank you for the ticket, I've labeled this as both a bug and feature-request since it seems to be a bit of both. One approach you could take would be to use a custom resource as mentioned here: https://github.com/aws/aws-cdk/issues/7259#issuecomment-612198184 to handle fallback values.

**Comment by sammcj** [comment]
We just got hit by this as well, it certainly seems like a bug.

**Comment by otaviomacedo** [comment]
@astef Just to clarify, when you say "it crashes", do you mean that the CLI prints an error message like this:

```
[Error at /MyStack] SSM parameter not available in account 12345689, region us-east-1: foo

Found errors
```

and returns exit code 1?

If that's the case, the template is still generated. To know whether the parameter exists at runtime, check whether the value starts with "dummy-value-for-".

**Comment by andrew-glenn** [comment]
@otaviomacedo Thanks - but that doesn't solve the `exit code 1` problem when dealing with automation.

**Comment by tyrauber** [comment]
This `exit code 1` is a problem for SST. 

It prevents conditionally creating resources by testing whether an ssm value exists.

Take a look as the [aws-cdk-lib ssm documentation #lookup-existing-parameters](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ssm-readme.html#lookup-existing-parameters).

```
const arnLookup = ssm.StringParameter.valueFromLookup(this, '/my/topic/arn');
sns.Topic.fromTopicArn(this, 'Topic', arnLookup);
```
> Initially arnLookup will be equal to dummy-value-for-/my/topic/arn which will cause Topic.fromTopicArn to throw an error indicating that the value is not in arn format.

This is no longer true. In actuality, `.valueFromLookup` throws the exit code 1 **itself** preventing further use. Take for example the following code built with SST.

```
import * as cdk from 'aws-cdk-lib';
import * as iam from "aws-cdk-lib/aws-iam";
import * as ssm from 'aws-cdk-lib/aws-ssm';

import { StackContext, attachPermissionsToRole  } from 'sst/constructs';

export function Role({ stack, app }: StackContext) {
  let role;
  let parameterName = `/${app.name}/Config/RoleArn`;
  let roleArn = ssm.StringParameter.valueFromLookup(stack, parameterName);

  stack.addOutputs({
    ROLEARN: role?.roleArn
  });

  return { role };
}

```

Just looking up the value with `valueFromLookup` throws an exit code 1 causing SST deployment to fail.

> Error: Could not resolve context values for ssm:account=00000000000:parameterName=/sst-iam/Config/RoleArn:region=us-east-1
 > LIFECYCLE  Command failed with exit code 1.

**Comment by T-Guerrero** [comment]
> This is no longer true. In actuality, .valueFromLookup throws the exit code 1 itself preventing further use. Take for example the following code built with SST.

Wrong, this remains true. In your case, I think the issue is that SSM is not being able to fetch your stack scope properly. From the method description:
```
     * Reads the value of an SSM parameter during synthesis through an
     * environmental context provider.
     *
     * Requires that the stack this scope is defined in will have explicit
     * account/region information. Otherwise, it will fail during synthesis.
```

**Comment by tyrauber** [comment]
Ah, thank you for the correction / clarification, @T-Guerrero.
