### ISSUE TITLE
cloudformation-include: Unable to include SAM template with cyclic dependencies

### ISSUE THREAD

**Issue by rix0rrr** [aws/aws-cdk#22071]
### Describe the bug

It's possible (and even semi-common) to have SAM templates with cyclic dependencies. When the transform expands the SAM template into multiple resources in a CloudFormation template, the cyclic dependencies disappear and everything works as desired.

Unfortunately, trying to include those kinds of templates using `cloudformation_include` doesn't work, since that depends on being to initialize resources in dependency order (which is not possible in templates with a cycle).

Upshot is that people with SAM templates with cyclic dependencies are unable to migrate to CDK. Previous advice was to download the processed template and use that, but this is not really feasible at scale and in a complex migration, especially when text-based template preprocessors are involved as well.

### Expected Behavior

Be able to `cloudformation_include` all input templates that are possible to deploy.

### Current Behavior

An exception is thrown.

### Reproduction Steps

(Volunteers needed for an example of a useful template with a cyclic dependency here!)

### CDK CLI Version

-

### Framework Version

-

### Node.js Version

-

### OS

-

### Language

Typescript

**Comment by AlexanderADietrich** [comment]
Example for repro from original issue (https://github.com/aws/aws-cdk/issues/16654): 

"AWSTemplateFormatVersion": "2010-09-09"
"Resources":
  "APIGatewayExecutionRole":
    "Properties":
      "AssumeRolePolicyDocument":
        "Statement":
        - "Action":
          - "sts:AssumeRole"
          "Effect": "Allow"
          "Principal":
            "Service":
            - "apigateway.amazonaws.com"
        "Version": "2012-10-17"
      "Policies":
      - "PolicyDocument":
          "Statement":
          - "Action":
            - "lambda:Invoke*"
            "Effect": "Allow"
            "Resource":
              "Fn::Join":
              - ""
              - - "Fn::GetAtt": "LambdaFunction.Arn"
                - "*"
          "Version": "2012-10-17"
        "PolicyName": "apigInvokeLambda"
    "Type": "AWS::IAM::Role"
  "LambdaAPIDefinition":
    "DependsOn": "APIGatewayAccount"
    "Properties":
      "DefinitionBody":
        "basePath": "/"
        "info":
          "description": "api"
          "title": "api"
          "version": "2017-07-25"
        "paths":
          "/api":
            "options":
              "consumes":
              - "application/json"
              "produces":
              - "application/json"
              "responses":
                "200":
                  "description": "Default response for CORS method"
                  "headers":
                    "Access-Control-Allow-Headers":
                      "type": "string"
                    "Access-Control-Allow-Methods":
                      "type": "string"
                    "Access-Control-Allow-Origin":
                      "type": "string"
              "x-amazon-apigateway-integration":
                "requestTemplates":
                  "application/json": "{\"statusCode\":200}"
                "responses":
                  "default":
                    "responseParameters":
                      "method.response.header.Access-Control-Allow-Headers": "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Amz-Content-Sha256,X-Amz-User-Agent'"
                      "method.response.header.Access-Control-Allow-Methods": "'POST'"
                      "method.response.header.Access-Control-Allow-Origin": "'*'"
                    "statusCode": "200"
                "type": "mock"
            "post":
              "consumes":
              - "application/json"
              "operationId": "api"
              "parameters":
              - "description": "api"
                "in": "body"
                "name": "api"
                "required": !!bool "true"
              "produces":
              - "application/json"
              "responses":
                "200":
                  "description": "api"
                "400":
                  "description": "api 400"
              "security":
              - "sigv4": []
              "x-amazon-apigateway-integration":
                "credentials":
                  "Fn::GetAtt":
                  - "APIGatewayExecutionRole"
                  - "Arn"
                "httpMethod": "POST"
                "passthroughBehavior": "NEVER"
                "responses":
                  "default":
                    "statusCode": "200"
                "type": "aws_proxy"
                "uri":
                  "Fn::Sub":
                  - "arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaArn}${LambdaAlias}/invocations"
                  - "LambdaAlias": ":live"
                    "LambdaArn":
                      "Fn::GetAtt":
                      - "LambdaFunction"
                      - "Arn"
  "LambdaFunction":
    "Properties":
      "AutoPublishAlias": "apilambda"
      "Events":
        "APIG":
          "Properties":
            "Method": "ANY"
            "Path": "/"
            "RestApiId":
              "Ref": "LambdaAPIDefinition"
          "Type": "Api"
      "Handler": "foo.bar::handleRequest"
      "MemorySize": !!int "2048"
      "Runtime": "java8"
      "Timeout": !!int "30"
    "Type": "AWS::Serverless::Function"

**Comment by AlexanderADietrich** [comment]
Hi @peterwoodworth, 

Thank you for labeling this issue for more accurate prioritization! Since this issue has been upgraded to p1, am I correct in thinking that the PR should also be upgraded to P1?

Thanks again,
Alexander.
