### ISSUE TITLE
stepfunctions: make Fail status able to specify input context in error and cause

### ISSUE THREAD

**Issue by saste** [aws/aws-cdk#22076]
### Describe the feature

At the moment we can specify the `error` and `cause` parameter as strings in a `Fail` state:
>cause (Optional[str]) – A description for the cause of the failure. Default: No description
>
>comment (Optional[str]) – An optional description for this state. Default: No comment
>
>error (Optional[str]) – Error code used to represent this failure. Default: No error code

https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_stepfunctions.html

### Use Case

It might be useful to reference the input context in the cause and error, for example with something as:
```
        pipeline_failed = stepfunctions.Fail(
            self, f"{project_name} Pipeline Failed",
            contextual_cause="$.jsonEncodedInput", contextual_error="$.error", contextual_comment="$.comment"
        )
```

For example, when a Codebuild execution fails you have a JSON containing the codebuild input in cause, making it possible to extract some content from the error message (for example for notification purposes). So you can add a handler to a parallel state and handle it later (but still the Codebuild execution task state will be marked as failed).

Consider for example a parallel state with several branches, each of one can fail. It would be good to be able to spot visually what state branches failed (and later collect and aggregate this information for a notification).

### Proposed Solution

One possible solution is to add some new parameters which are expanded depending on the input context (`contextual_*`), but probably there is a more idiomatic way to do this.
Or you introduce a new special `ContextualFail` object accepting the `$.` syntax.

### Other Information

I can workaround this by not explicitly failing, and putting the success/fail result in the output, and fail later. Still with an explicit failure (e.g. within a parallel step), it's easier to spot the failure visually since the failing state will be explicitly marked as failed and rendered in red.

Yet another solution would be to move the failure in a child state machine and use a callback mechanisms, but this would significantly complicate the design.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.41 (python)

### Environment details (OS name and version, etc.)

not relevant

**Comment by indrora** [comment]
Can you give an example (or better, link to documentation for) doing this in CloudFormation?
