### ISSUE TITLE
aws-cdk/aws-applicationautoscaling:ServiceNameSpace Neptune is missing

### ISSUE THREAD

**Issue by sennetheunisporphy** [aws/aws-cdk#22078]
### Describe the feature

I can't seem to find the option to select ServiceNameSpace Neptune in the enum, can this be added?

### Use Case

I need it to setup autoscaling for a neptune cluster

### Proposed Solution

add NEPTUNE to ServiceNamespace enum

### Acknowledgements

- [x] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2

### Environment details (OS name and version, etc.)

Linux

**Comment by sennetheunisporphy** [comment]
https://github.com/aws/aws-cdk/pull/22092

**Comment by peterwoodworth** [comment]
Thanks for the request and PR, we'll give a full review after the initial issues with the PR are fixed like the title 🙂
