### ISSUE TITLE
(aws cdk eks docs): (cdk8s-charts not included in navigation)

### ISSUE THREAD

**Issue by NinoSkopac** [aws/aws-cdk#22073]
### Describe the issue

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_eks-readme.html#cdk8s-charts doesn't exist in right side affixed navigation (it goes from OCI Charts to Patching Kubernetes Resources)

![Screenshot 2022-09-16 at 12 48 43](https://user-images.githubusercontent.com/1783732/190622663-1a6cd117-4149-4423-bcb9-ecf53f0a8c3d.png)

### Links

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_eks-readme.html#cdk8s-charts

**Comment by bun913** [comment]
Ok. I want to fix this. I open PR today.
