### ISSUE TITLE
S3 Deploy:  AWS Lambda end of support for Node.js 12

### ISSUE THREAD

**Issue by wascou** [aws/aws-cdk#22089]
### Describe the bug

Well, I received this message :  AWS Lambda end of support for Node.js 12

> Hello,
> 
> We are contacting you as we have identified that your AWS Account currently has one or more Lambda functions using Node.js 12 runtime.
> 
> We are ending support for Node.js 12 in AWS Lambda. This follows Node.js 12 End-Of-Life (EOL) reached on April 30, 2022 [1].
> 
> As described in the Lambda runtime support policy [2], end of support for language runtimes in Lambda happens in two stages. Starting November 14, 2022, Lambda will no longer apply security patches and other updates to the Node.js 12 runtime used by Lambda functions, and functions using Node.js 12 will no longer be eligible for technical support. In addition, you will no longer be able to create new Lambda functions using the Node.js 12 runtime. Starting December 14, 2022, you will no longer be able to update existing functions using the Node.js 12 runtime.
> 
> We recommend that you upgrade your existing Node.js 12 functions to Node.js 16 before November 14, 2022.
> 
> End of support does not impact function execution. Your functions will continue to run. However, they will be running on an unsupported runtime which is no longer maintained or patched by the AWS Lambda team.
> 
> The following command shows how to use the AWS CLI [3] to list all functions in a specific region using Node.js 12. To find all such functions in your account, repeat this command for each region:
> 
> aws lambda list-functions --function-version ALL --region us-east-1 --output text --query "Functions[?Runtime=='nodejs12.x'].FunctionArn"
> 
> If you have any concerns or require further assistance, please contact AWS Support [4].
> 
> [1] https://nodejs.org/en/blog/release/v12.22.12/
> [2] https://docs.aws.amazon.com/lambda/latest/dg/runtime-support-policy.html
> [3] https://aws.amazon.com/cli/
> [4] https://aws.amazon.com/support
> 
> Sincerely,
> Amazon Web Services

Deep diving a bit, all my lambdas are in NodeJS 16 and the one causing trouble is the one shipped with S3Deploy.
May you upgrade to NodeJS 16 ?

Cheers.

W

### Expected Behavior

NodeJS above 12

### Current Behavior

NodeJS 12

### Reproduction Steps

The lambda shipped with S3 is used for auto deletion of elements inside the bucket.
Just use the sample from S3 Deployment :
https://docs.aws.amazon.com/cdk/api/v1/docs/aws-s3-readme.html#bucket-deletion
The node version is 12.

### CDK CLI Version

2.41.0 (build 6ad48a3)

### Node.js Version

12

### OS

Windows

### Language

Typescript

**Comment by ctrepka** [comment]
Seconding this, but in my case the outdated lambdas are deployed via the aws_eks.Eks construct. Should I create a separate Issue for the aws_eks constructs?

**Comment by peterwoodworth** [comment]
Similar to [this issue and comment](https://github.com/aws/aws-cdk/issues/21718#issuecomment-1224600143), this has been addressed a bit ago. Could you please link to any functions in our codebase which are still configured to use node 12? thanks

**Comment by wascou** [comment]
@peterwoodworth 
After 2 minutes of long deep dive, it seems that issue is located here:
https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/aws-s3/lib/bucket.ts#L2241
It's related to the S3 Construct feature.

**Comment by peterwoodworth** [comment]
The line you linked specifies Node 14, not Node 12, am I missing something here?

**Comment by wascou** [comment]
Well, I have a current live project. and re bootstraping or  delivering again the project did not upgrade the AutoDelete Lambda from 12 to 14. I changed some ids in the stack to force the delivery but it was not taken in account.

**Comment by wascou** [comment]
Ok, i found a quick solution: deploy with auto delete to false, then deploy again with auto delete to true.
It enforces the new engine spec to be taken in account.
I guess it should be managed by the construct btw.

**Comment by peterwoodworth** [comment]
I can't reproduce this behavior @wascou, if I toggle between the versions before and after we upgraded this function to node 14 it always produces the expected version. You're referring to the generated function with a name similar to `CustomS3AutoDeleteObjectsCustomResourceProviderHandler` right?

**Comment by wascou** [comment]
Arg, I found it, my cdk version was in 2.8.0 :(
So, first update the cdk version then cdk deploy.
Sorry for the noise.

**Comment by gopinaath** [comment]
I get error `The runtime parameter of nodejs14.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs20.x) while creating or updating functions. (Service: Lambda, Status Code: 400`

`
$ cdk version
2.149.0 (build c8e5924)
`

**Comment by yutaro-sakamoto** [comment]
@gopinaath 
I got the same error in my environment.
I ran `yarn upgrade --latest` in order to upgrade the dependencies specified in `package.json`, and the error was resolved.
