### ISSUE TITLE
(core): Hash calculated inconsistently

### ISSUE THREAD

**Issue by jd-carroll** [aws/aws-cdk#22094]
### Describe the bug

When calculating a hash for an asset with bundle, a raw javascript object is passed to the hash:
https://github.com/aws/aws-cdk/blob/ce277899e9df2ae9d69e94bdaa931e130cd4c95a/packages/%40aws-cdk/core/lib/asset-staging.ts#L496-L499

### Expected Behavior

The object passed to the hashing function should be sorted so as to produce a consistent hash

### Current Behavior

There is no guarantee of the order of key names within a raw javascript object

### Reproduction Steps

Anything that uses bundling

### Possible Solution

Pass the bundle options to the sort function:
https://github.com/aws/aws-cdk/blob/ce277899e9df2ae9d69e94bdaa931e130cd4c95a/packages/%40aws-cdk/core/lib/asset-staging.ts#L553-L565

### CDK CLI Version

2.42.0

### Node.js Version

16.13.1

### OS

MacOS

### Language

Typescript

**Comment by rix0rrr** [comment]
Hi @jd-carroll. NodeJS maintains key order for objects, so while this could be a problem in theory you didn't mention how this affects you in real life.

What code did you write that produces inconsistent object ordering?

**Comment by jd-carroll** [comment]
Admittedly I've been trying to do something I probably shouldn't... I am trying to conditionally update code in an edge lambda function for a CloudFront distribution (think AB test lambda which assigns a buildId [key in S3] based on basic characteristics from request).

So I was playing around with assigning an `assetHash` on the bundling for a lambda function and going pretty deep into the internals which is where I saw this "issue".

Before starting to assign an `assetHash` I had run a number of tests around how the hash was calculated (and thereby to know when the lambda code would be updated with a new S3 key).  I was having a hard time understanding when the S3 Key was being updated (after reverting a change in the function code I expected it to return to the previous hash, it didn't) and thought the referenced "issue" could explain everything.

Today I learned ES6 introduced deterministic object keys! 😄 

I ended up moving to an entirely different approach using a CustomResource to compile / deploy the function, so this change is not necessary either way.  Happy to close since it does not seem to be of concern to the team.

**Comment by jd-carroll** [comment]
Here is something else which contributes to me thinking there's an issue:

I just redeployed my stacks and in the output I saw:
```
MarketingSiteStack: creating CloudFormation changeset...
MarketingSiteStack | 0/3 | 2:22:27 PM | UPDATE_IN_PROGRESS   | AWS::CloudFormation::Stack      | MarketingSiteStack User Initiated
MarketingSiteStack | 0/3 | 2:22:37 PM | UPDATE_IN_PROGRESS   | AWS::Lambda::Function           | MarketingSiteStack.us-west-2/dynamic-origin-deployer (dynamicorigindeployer0D59317E) 
MarketingSiteStack | 1/3 | 2:22:46 PM | UPDATE_COMPLETE      | AWS::Lambda::Function           | MarketingSiteStack.us-west-2/dynamic-origin-deployer (dynamicorigindeployer0D59317E) 
MarketingSiteStack | 2/3 | 2:22:52 PM | UPDATE_COMPLETE_CLEA | AWS::CloudFormation::Stack      | MarketingSiteStack 
MarketingSiteStack | 3/3 | 2:22:53 PM | UPDATE_COMPLETE      | AWS::CloudFormation::Stack      | MarketingSiteStack 
 ✅  MarketingSiteStack.us-west-2 (MarketingSiteStack)
```

However, I made absolutely no changes to that code. So why did it deploy?  My real question is, how can I figure that out? (I don't expect you to be able to answer for me)

I'm certain if I had done a diff of the "MarketingSiteStack.us-west-2", I would have seen a difference with the lambda function which updated above.  More specifically, if I looked at the raw json output, we would have seen a different S3 bucket key for the code which caused the deployment above.

But without any code change, why did this happen?  There can only be two options:
1. `esbuild` will have inconsistent output when bundling
2. There is something else inconsistent during the bundling / hash calculation process

And this is the real reason I thought to open this issue.

**Comment by peterwoodworth** [comment]
Could you share a reproducible sample of code? I've never experienced what you're describing in your last comment

**Comment by jd-carroll** [comment]
Tried creating a consistent reproducible case and have not been able to.  Closing for now.
