### ISSUE TITLE
iam: SamlConsolePrincipal does not work in China

### ISSUE THREAD

**Issue by ganhuang** [aws/aws-cdk#22091]
### Describe the bug

While creating the SAML federation principal as below, the SAML attribute is hardcoded with `https://signin.aws.amazon.com/saml`, which breaks in `aws-cn` partition since the SAML attribute should be changed to `https://signin.amazonaws.cn/saml` in AWS CN partition.

```
  const principal = new iam.SamlConsolePrincipal(provider);
```

### Expected Behavior

The construct `SamlConsolePrincipal` should allow to customize the SAML attribute for this case. This could be an option to change it.

### Current Behavior

Currently it's hardcoded and can't be customized while using the construct.

### Reproduction Steps

```
  const principal = new iam.SamlConsolePrincipal(provider);
```

### CDK CLI Version

2.39.0

### Node.js Version

v16.16.0

### OS

Mac

### Language

Typescript

**Comment by rix0rrr** [comment]
Looks like this information needs to be encoded into `region-info`.
