### ISSUE TITLE
(dynamodb): more than 10 global tables in a single stack causes deploy failure

### ISSUE THREAD

**Issue by VarunWachaspati** [aws/aws-cdk#22101]
### Describe the bug

CDK creates a custom resource provider nested stack to enable cross region replication for a DynamoDB table. The current implementation attaches a managed IAM policy for each table/index to the DynamoDB service replication IAM role. 
If a CDK stack has more than 10 tables with replication enabled, then IAM throws an error as an IAM role can only have a maximum of 10 managed policies attached to it. ([AWS IAM Limits documentation](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_iam-quotas.html))

### Expected Behavior

Throwing the error during `cdk synth` step itself might be better instead of throwing an error while deployment.

Looks like there was a fix done for this issue via this PR - https://github.com/aws/aws-cdk/pull/14054
But this fix seems to be reverted by this PR - https://github.com/aws/aws-cdk/pull/15339

Given that the error is still reproducible should we add the original fix back?

### Current Behavior

Currently, we get the following error if try to deploy the above mentioned CDK stack -
```
TestCdkStack: creating CloudFormation changeset...
4:12:45 PM | CREATE_FAILED        | AWS::IAM::ManagedPolicy    | cdktestReplica11Ta...le7805392AFE6A5094
Cannot exceed quota for PoliciesPerRole: 10 (Service: AmazonIdentityManagement; Status Code: 409; Error Code:LimitExceeded; Request

 ❌  TestCdkStack failed: Error: The stack named TestCdkStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE
    at waitForStackDeploy (/usr/local/lib/node_modules/aws-cdk/lib/api/util/cloudformation.ts:311:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at prepareAndExecuteChangeSet (/usr/local/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:376:26)
    at CdkToolkit.deploy (/usr/local/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:209:24)
    at initCommandLine (/usr/local/lib/node_modules/aws-cdk/lib/cli.ts:342:12)
```

### Reproduction Steps

Sample CDK Stack Code for reproducing the bug
```javascript
const cdk = require('aws-cdk-lib');
const dynamodb = require('aws-cdk-lib/aws-dynamodb');

class TestCdkStack extends cdk.Stack {
  /**
   * @param {cdk.App} scope
   * @param {string} id
   * @param {cdk.StackProps=} props
   */
  constructor(scope, id, props) {
    super(scope, id, props);
    for (let i = 0; i<11; i++) {
      new dynamodb.Table(this, `cdk-test-Replica-Table-${i}`, {
        partitionKey: { name: 'id', type: dynamodb.AttributeType.STRING },
        replicationRegions: ['us-east-1', 'us-west-2'],
        billingMode: dynamodb.BillingMode.PAY_PER_REQUEST,
      });

    }
  }
}

module.exports = { TestCdkStack }

```
When try to deploy the above stack, it fails because of the IAM limits.

### CDK CLI Version

2.20.0

### Node.js Version

v14.17.1

### OS

MacOS Monterey 12.5

### Language

Typescript

**Comment by peterwoodworth** [comment]
Yeah this was reverted, though it's unclear to me why from looking at the PRs. @jogold were you aware this was reverted?

**Comment by jogold** [comment]
@peterwoodworth here is more context: https://github.com/aws/aws-cdk/pull/15256#issue-927449581 and https://github.com/aws/aws-cdk/pull/15245#issue-927046454

**Comment by peterwoodworth** [comment]
Ah I see, thanks jogold!

To state it here: this was reverted because this is a "soft limit", and can be increased by requesting to increase your AWS Service Limit for Customer Managed Policies.

I've made a PR to add the note back to our readme
