### ISSUE TITLE
(triggers): unable to use Trigger for more than one function

### ISSUE THREAD

**Issue by cecheta** [aws/aws-cdk#22110]
Related to #19272 

### Describe the bug

When using the `Trigger` construct, it only has permissions to invoke a single lambda function, meaning it cannot invoke more than one without receiving an access denied error.

### Expected Behavior

Both lambda functions are invoked.

### Current Behavior

Access denied exception

### Reproduction Steps

```ts
import * as lambda from 'aws-cdk-lib/aws-lambda';
import * as triggers from 'aws-cdk-lib/triggers';

...

new triggers.TriggerFunction(this, 'One', {
  runtime: lambda.Runtime.NODEJS_16_X,
  handler: 'index.handler',
  code: lambda.Code.fromInline('exports.handler = function() { console.log("One"); };'),
});
    
new triggers.TriggerFunction(this, 'Two', {
  runtime: lambda.Runtime.NODEJS_16_X,
  handler: 'index.handler',
  code: lambda.Code.fromInline('exports.handler = function() { console.log("Two"); };'),
});
```

### Possible Solution

The CustomResourceProvider should use `addToRolePolicy` rather than creating the policy in the constructor

### CDK CLI Version

2.42.0

### Node.js Version

16.15.0

### OS

Mac OS

### Language

Typescript

**Comment by peterwoodworth** [comment]
Thanks for the report and PR, we'll try to take a look at it soon 🙂
