### ISSUE TITLE
Subnet CIDR as security group rule source

### ISSUE THREAD

**Issue by ababra** [aws/aws-cdk#2211]
How can you get the CIDR for a subnet created by the same stack and add it to a security group rule? 
```ts
    const vpc = new ec2.VpcNetwork(this, 'VPC', {
      subnetConfiguration: [
        {
          cidrMask: 28,
          subnetType: SubnetType.Public,
        },
        {
          cidrMask: 24,
          subnetType: SubnetType.Private,
        }
      ],
    });

  // Something similar to this?
  publicSecurityGroup.connections.allowFrom(vpc.publicSubnets[0].cidr, new ec2.TcpPort(443), 'HTTPS ingress from private SG to public SG');
```

**Comment by rix0rrr** [comment]
Also needs to consider imported subnets

**Comment by Cloudrage** [comment]
++
Even when importing Subnets, you don't have the **(ipv4)CidrBlock** :
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ec2.Subnet.html#properties

**Comment by karthikns16** [comment]
I am in same state as this. I have a VPC which is created with subnets (public and private) in 2 AZ's. I want the CIDR block of the subnet which I was trying to get using this simple logic
`
for subnet in self.vpc.isolated_subnets:
      subnet.cidrblock
`
only to find out the .cidrblock is not a property that is exposed.

**Comment by lutojames** [comment]
```
const vpcIsolatedSubnets = vpc.selectSubnets({
  subnetType: ec2.SubnetType.ISOLATED
});

vpcIsolatedSubnets.subnets.forEach((subnet, index) => {
  console.log(`cidr=${subnet.ipv4CidrBlock}`);
});
```

**Comment by russd2357** [comment]
> ```
> const vpcIsolatedSubnets = vpc.selectSubnets({
>   subnetType: ec2.SubnetType.ISOLATED
> });
> 
> vpcIsolatedSubnets.subnets.forEach((subnet, index) => {
>   console.log(`cidr=${subnet.ipv4CidrBlock}`);
> });
> ```

@lutojames I tried that. It doesn't work. The ipv4CidrBlock property is not exposed.

**Comment by christophegrall** [comment]
Hello @rix0rrr, 

In the subnetGroupToSubnets function in https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-ec2/lib/vpc.ts#L1888

the ipv4CidrBlock attribute is missing : 

```typescript
private subnetGroupToSubnets(subnetGroup: cxapi.VpcSubnetGroup): ISubnet[] {
    const ret = new Array<ISubnet>();
    for (let i = 0; i < subnetGroup.subnets.length; i++) {
      const vpcSubnet = subnetGroup.subnets[i];
      ret.push(Subnet.fromSubnetAttributes(this, `${subnetGroup.name}Subnet${i + 1}`, {
        availabilityZone: vpcSubnet.availabilityZone,
        subnetId: vpcSubnet.subnetId,
        routeTableId: vpcSubnet.routeTableId,
  
       //  Add this to fix 
       ipv4CidrBlock: vpcSubnet.cidr
       //

      }));
    }
    return ret;
  }

```

**Comment by christophegrall** [comment]
https://github.com/aws/aws-cdk/issues/11821

**Comment by corymhall** [comment]
Closing this since it is now possible subnets now have [ipv2cidrblock](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-ec2.Subnet.html#ipv4cidrblock)
