### ISSUE TITLE
SQS: CDK Deploy by default adding Amazon SQS key(SSE-SQS) encryption

### ISSUE THREAD

**Issue by sats17** [aws/aws-cdk#22137]
### Describe the bug

SQS constructor for CDK v2 by default adding encryption of Amazon SQS key(SSE-SQS) encryption. As mentioned in the description of the encryption variable below.
**"
Whether the contents of the queue are encrypted, and by what type of key.
Be aware that encryption is not available in all regions, please see the docs for current availability details.
@default
Unencrypted
"**
It should not add any encryption in SQS.

### Expected Behavior

On SQS AWS Console Encryption should be disabled.

### Current Behavior

On SQS AWS Console Encryption is enabled with  Amazon SQS key(SSE-SQS).
CDK Code =
` 
new sqs.Queue(this, 'test-queue', {
        queueName: "test-queue-name"
      });
`
Generated CFT Template = 
`Resources:
  testqueueA58C838B:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: test-queue-name
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: test-stack/test-queue/Resource
`

CDK Dependencies -
"aws-cdk-lib": "2.37.0",
"aws-cdk": "2.37.0"

### Reproduction Steps

1. Create new SQS in the sample project without adding any properties
2. After creation observe in AWS Console SQS will be created with Encryption as Amazon SQS key(SSE-SQS)

### CDK CLI Version

2.37.0

### Node.js Version

16.15.0

### OS

Windows

### Language

Typescript

### Language Version

3.9.7

**Comment by sats17** [comment]
Even if I explicitly mention it in the constructor it still creating queue with encryption.
`  
new sqs.Queue(this, 'test-queue', {
        queueName: "test-queue",
        encryption: cdk.aws_sqs.QueueEncryption.UNENCRYPTED
      });`

**Comment by kurtismash** [comment]
It appears the default when deploying a stack via CloudFormation is to now enable the `SqsManagedSseEnabled` property but as this property isn't supported by CDK (#17770) we have no way to disable this behaviour.

**Comment by TheLargeCactus** [comment]
Yeah, this issue is impacting CDKv1 as well.

**Comment by TheLargeCactus** [comment]
If you have access to the AWS cli, you can do something similar to the following (I use zsh):
```
for url in $(aws sqs list-queues --output text --query QueueUrls); aws sqs set-queue-attributes --attributes SqsManagedSseEnabled=false --queue-url $url
```

A smarter query can be used to filter the queues you want to target.

**Comment by chrisandrewcl** [comment]
Until the new property is added to the queue construct, this can still be worked around within CDK using a scape hatch:

```javascript
const cfnQueue = queue.node.defaultChild as CfnResource;

cfnQueue.addOverride('Properties.SqsManagedSseEnabled', false)
```

**Comment by miguelcss** [comment]
It is my understanding that this PR: https://github.com/aws/aws-cdk/pull/21591 will fix the mentioned behaviour

**Comment by jumic** [comment]
As mentioned by @kurtismash the default behaviour in CloudFormation has changed. The following snipped creates an encrypted SQS queue.
```yaml
AWSTemplateFormatVersion: "2010-09-09"
Resources: 
  MyQueue: 
    Type: AWS::SQS::Queue
```

Result in AWS Console:
![image](https://user-images.githubusercontent.com/15660169/193451118-bcc8e30f-cd52-4b95-ad2e-8a1d3c23708a.png)

The [documentation](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-configure-sse-existing-queue.html) describes the now logic:

> To protect the data in a queue’s messages, Amazon SQS has server-side encryption (SSE) enabled by default for all newly created queues.


If I create a new SQS queue manually in the AWS console, SSE-SQS is also selected by default.
<img width="811" alt="image" src="https://user-images.githubusercontent.com/15660169/193451114-024cb898-d7ca-4fe0-b964-947da9d402ae.png">

PR #21591 doesn't disable encryption if `UNENCRYPTED` is used. I will submit another PR.
