### ISSUE TITLE
aws-cloudwatch: support Gauge type on graphWidget

### ISSUE THREAD

**Issue by damiendurant** [aws/aws-cdk#22136]
### Describe the feature

Currently GraphWidget only support BAR, Tinesweries and Pie views :

```
export enum GraphWidgetView {
  /**
   * Display as a line graph.
   */
  TIME_SERIES = 'timeSeries',
  /**
   * Display as a bar graph.
   */
  BAR = 'bar',
  /**
   * Display as a pie graph.
   */
  PIE = 'pie',
}
```

Graph widget could also be a Gauge.

### Use Case

Gauge widget are usefull to monitor quota.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.33.0

### Environment details (OS name and version, etc.)

WSL2 Ubuntu 22.04.

**Comment by indrora** [comment]
Thanks! This looks like it's the result of having to define this by hand.
