### ISSUE TITLE
(aws-rds): Can't destroy a stack with a database that has `removalPolicy` property set to `RemovalPolicy.RETAIN`

### ISSUE THREAD

**Issue by maxd** [aws/aws-cdk#22141]
### Describe the bug

I have a stack that creates a database with parameters group:

```ts
const parameterGroup = new ParameterGroup(this, 'ParameterGroup', {
    ...
}

const database = new DatabaseInstance(this, 'DatabaseInstance', {
    parameterGroup: parameterGroup,
    removalPolicy: RemovalPolicy.RETAIN,
    ...
})
```

As you can see the database has `removalPolicy` property set to `RETAIN` because I want to leave the database after destroying this stack.

When I destroy this stack I see the following errors:

```
2:04:24 PM | DELETE_FAILED        | AWS::RDS::DBParameterGroup                  | ParameterGroup5E32DECB
One or more database instances are still members of this parameter group xxx-database-parametergroup5e32decb-daetrwpaqpgw, so the group cannot be deleted (Service: Rd
s, Status Code: 400, Request ID: 389b18db-ea82-482b-a0e6-f64887da6f82)

2:19:21 PM | DELETE_FAILED        | AWS::EC2::SecurityGroup                     | DatabaseInstanceSecurityGroup8BDF0112
resource sg-0bfc8aacb3d3e3d4a has a dependent object (Service: AmazonEC2; Status Code: 400; Error Code: DependencyViolation; Request ID: 1eac5393-83df-48cf-bd75-41f25abb04
7a; Proxy: null)
```

As I understand the CF leaves the database but tries to destroy `ParameterGroup` and `SecurtyGroup`. I suppose this is the wrong behavior and CF should leave related `ParameterGroup` and `SecurityGroup` too.

I can create a custom `SecurityGroup` and change it remove policy use the `applyRemovalPolicy` method:

```
    const securityGroup = new SecurityGroup(this, 'SecurityGroup', {
      vpc: props.vpc,
      allowAllOutbound: true,
    })
    securityGroup.applyRemovalPolicy(removalPolicy(SecurityGroup))
```

BUT I can't change the removal policy for a `ParameterGroup` in the same way because `parameterGroup.applyRemovalPolicy(RemovalPolicy.RETAIN)` raises the following error:

```
Error: Cannot apply RemovalPolicy: no child or not a CfnResource. Apply the removal policy on the CfnResource directly.
    at ParameterGroup.applyRemovalPolicy (/Users/user/Projects/work/my-project/node_modules/aws-cdk-lib/core/lib/resource.js:1:2872)
    at Database.createDatabase (/Users/user/Projects/work/my-project/src/stacks/billfold/database/index.ts:78:20)
    at new Database (/Users/user/Projects/work/my-project/src/stacks/billfold/database/index.ts:36:27)
    at new Billfold (/Users/user/Projects/work/my-project/src/stages/billfold.ts:66:22)
    at Object.<anonymous> (/Users/user/Projects/work/my-project/src/apps/billfold.ts:10:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module.m._compile (/Users/user/Projects/work/my-project/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/user/Projects/work/my-project/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
```

### Expected Behavior

I can destroy a stack with a database that has `removalPolicy` property set to `RemovalPolicy.RETAIN` and has a relation to a parameter and security groups.

### Current Behavior

The CF leaves the database but tries to destroy the related parameter group and security group and fails with the errors:

```
2:04:24 PM | DELETE_FAILED        | AWS::RDS::DBParameterGroup                  | ParameterGroup5E32DECB
One or more database instances are still members of this parameter group billfold-database-parametergroup5e32decb-daetrwpaqpgw, so the group cannot be deleted (Service: Rd
s, Status Code: 400, Request ID: 389b18db-ea82-482b-a0e6-f64887da6f82)

2:19:21 PM | DELETE_FAILED        | AWS::EC2::SecurityGroup                     | DatabaseInstanceSecurityGroup8BDF0112
resource sg-0bfc8aacb3d3e3d4a has a dependent object (Service: AmazonEC2; Status Code: 400; Error Code: DependencyViolation; Request ID: 1eac5393-83df-48cf-bd75-41f25abb04
7a; Proxy: null)
```

### Reproduction Steps

1. Create a stack with database and parameter group using the following template:

```ts
const parameterGroup = new ParameterGroup(this, 'ParameterGroup', {
    ...
}

const database = new DatabaseInstance(this, 'DatabaseInstance', {
    parameterGroup: parameterGroup,
    removalPolicy: RemovalPolicy.RETAIN,
    ...
})
```
2. Deploy this stack
3. Destroy this stack

### Possible Solution

I suppose:
1) The `DatabaseInstance` and `DatabaseInstanceFromSnapshot` constructs should propagate the removal policy to the related parameters and security groups.
2) The `ParametersGroup#applyRemovalPolicy` method should work and doesn't raise the error.

### CDK CLI Version

2.39.0 (build e36bfe5)

### Node.js Version

v16.15.1

### OS

macOS 12.4 (21F79)

### Language

Typescript

### Language Version

4.7.4

### Other information

Looks like the https://github.com/aws/aws-cdk/issues/20649 issue is similar to this.

**Comment by corymhall** [comment]
It looks like `applyRemovalPolicy` fails on `ParameterGroup` because there is no `defaultChild` set.

The solution is to set the defaultChild in both the [bindToCluster](https://github.com/aws/aws-cdk/blob/6840bc39a1d80ceb45da8f60c6e6b5c1243c31f8/packages/@aws-cdk/aws-rds/lib/parameter-group.ts#L136) and [bindToInstance](https://github.com/aws/aws-cdk/blob/6840bc39a1d80ceb45da8f60c6e6b5c1243c31f8/packages/@aws-cdk/aws-rds/lib/parameter-group.ts#L151) methods

i.e.

```ts
this.node.defaultChild = this.clusterCfnGroup;
```

**Comment by maxd** [comment]
@corymhall Thank you for you quick response. But I don't think that this solution will work because:

1. Look at this example:

    ```
    const parameterGroup = new ParameterGroup(this, 'ParameterGroup', {
        ...
    }
    parameterGroup.applyRemovalPolicy(cdk.RemovalPolicy.RETAIN)

    const database = new DatabaseInstance(this, 'DatabaseInstance', {
        parameterGroup: parameterGroup,
        removalPolicy: RemovalPolicy.RETAIN,
        ...
    })
    ```

    As you can see I can call `applyRemovalPolicy` before binging it to a DB instance or a DB cluster.

1. I've found the following [test](https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/aws-rds/test/parameter-group.test.ts#L72-L90):

    ```
    test('creates 2 parameter groups when bound to a cluster and an instance', () => {
    ...
    ```

    Looks like `ParameterGroup` can be binded to DB instance an cluster simultaneously but node can have only one `defaultChild`. Right?

How about the following solution?:

1. We can add `removalPolicy` property to the `ParameterGroupProps` class
2. Then we can save value from `ParameterGroupProps#removalPolicy` to the `removalPolicy` filed in the constructor
3. After that we can use value from `removalPolicy` filed to set removal policy in `bindToCluster` and `bindToInstance` methods e.g.:
    ```
    ...
    this.instanceCfnGroup.applyRemovalPolicy(this.removalPolicy);
    ...
    ```
4. And we should override `ParameterGroup#applyRemovalPolicy` method something like this:

    ```
    public applyRemovalPolicy(policy: cdk.RemovalPolicy): void {
        this.removalPolicy = policy;
        if (this.clusterCfnGroup) {
            this.clusterCfnGroup.applyRemovalPolicy(policy);
        }
        if (this.instanceCfnGroup) {
            this.instanceCfnGroup.applyRemovalPolicy(policy);
        }
    }
    ```

    As you can see this overrode method will update `removalPolicy` field and resources if they are already exists. 

So, what do you think?

**Comment by corymhall** [comment]
> So, what do you think?

Looks good to me!

**Comment by mowemcfc** [comment]
Hi @corymhall @maxd does this issue still exist? I'm happy to pick it up if so as I have encountered the same in my project.

**Comment by maxd** [comment]
I suppose it still exists.

**Comment by ChrisLane** [comment]
It would be great to have this fixed.
I just came across this issue in my use-case where I want to create a database via CDK and then immediately orphan it so that it can be maintained manually via AWS management console; this bug is stopping me from being able to continue.

**Comment by chris-allen** [comment]
I experience the same behavior even when the database has a `removalPolicy` of `RemovalPolicy.SNAPSHOT`.

My only solution has been to manually update the database to use a default parameter group and delete the one to be cleaned up.

**Comment by GavinZZ** [comment]
Going to implement a fix to this problem as @maxd described in this [comment](https://github.com/aws/aws-cdk/issues/22141#issuecomment-1252718446).
