### ISSUE TITLE
AWS CDK : aws-ecs-pattern queueprocessingfargate service generates an runtime error: divide by zero 

### ISSUE THREAD

**Issue by jatinmehrotra** [aws/aws-cdk#22162]
### Describe the bug

Till now there wasn't any of this problem but recently QueueProcessingFargateService is generating an _Runtime error (func=(main), adr=10): Divide by zero_

### Expected Behavior

Ideally everything is correct in my configuration, it should not raise any error 

### Current Behavior

Irregularly it is generating this error 

Field | Value
-- | --
@ingestionTime | xxxxxxx
@log | xxxxxx:/aws/fargate/xxxxxxxService-1/FargateService
@logStream | FargateService/QueueProcessingContainer/xxxxxx
@message | Runtime error (func=(main), adr=10): Divide by zero
@timestamp | xxxxxx

### Reproduction Steps

```
const deadLetterQueue = new sqs.Queue(this, 'DeadLetterQueue')
    deadLetterQueue
      .metricApproximateNumberOfMessagesVisible()
      .createAlarm(this, 'DeadLetterQueueAlarm', {
        threshold: 0,
        evaluationPeriods: 1,
        comparisonOperator: cw.ComparisonOperator.GREATER_THAN_THRESHOLD,
      })
      .addAlarmAction(new actions.SnsAction(props.targetTopic))

    const queue = new sqs.Queue(this, 'Queue', {
      deadLetterQueue: {
        maxReceiveCount: 3,
        queue: deadLetterQueue,
      },
    })
this.service = new patterns.QueueProcessingFargateService(
      this,
      'QueueProcessingFargateService',
      {
        logDriver: ecs.AwsLogDriver.awsLogs({
          logGroup: new CloudWatchLogs(this, 'CloudWatchLogs', {
            logGroupName: `/aws/fargate/${Stack.of(this).stackName}/${id}`,
          }).logGroup,
          streamPrefix: this.id,
        }),
        queue,
        ...props.serviceProps,
        environment: {
          ...props.serviceProps.environment,
          QUEUE_NAME: queue.queueName,
        },
      }
    )
```

constructor file 

```
const fargateService = new QueueProcessingFargateService(
      this,
      'FargateService',
      {
        serviceProps: {
          cluster,
          image: ecs.ContainerImage.fromEcrRepository(
            ecr.Repository.fromRepositoryName(
              this,
              'Repository',
              'book-repackaging'
            ),
            imageTag.stringValue
          ),
          cpu: 2048,
          memoryLimitMiB: 4096,
          environment: {
            BOOK_PACKAGE_BUCKET_NAME: bookPackageBucket.bucketName,
            DTS_TABLE: dtsTable.tableName,
          },
          minScalingCapacity,
          maxScalingCapacity,
          platformVersion: ecs.FargatePlatformVersion.VERSION1_4,
        },
        targetTopic: props.targetTopic,
      }
    ).service
```

### CDK CLI Version

2.40

### Node.js Version

16.17

### OS

macOS

### Language

Typescript

**Comment by peterwoodworth** [comment]
Is this happening during synth or deploy time? Or after deploy and when you're running your application?

**Comment by jatinmehrotra** [comment]
After deploy when our application is running

**Comment by peterwoodworth** [comment]
How do you know this is an error with CDK and not your container image? CDK can only configure your infrastructure so I'm not certain we'll be able to help you from our end unless there's a specification we made that you think is causing this

**Comment by jatinmehrotra** [comment]
maybe its our container image, is there a way, we can find logs or reason why this is happening because I couldn't find as to why this is happening

**Comment by tim-finnigan** [comment]
Hi @jatinmehrotra I think we still need more information regarding the error. Where is that coming from and when specifically does it occur? It does seem like it could be related to your container as suggested earlier.
