### ISSUE TITLE
VpcEndpoint: define VPC ID

### ISSUE THREAD

**Issue by caojoshua** [aws/aws-cdk#22165]
### Describe the feature

Allow users to define the VPC ID through CDK. `VpcId` is a valid field in cloud formation [[source](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcendpoint.html)]. I don't see this option in [InterfaceVpcEndpoint](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ec2.InterfaceVpcEndpoint.html#construct-props) docs for CDK. VPC ID can also be specified through aws cli [create-vpc-endpoint](https://docs.aws.amazon.com/cli/latest/reference/ec2/create-vpc-endpoint.html)

### Use Case

If the VPC Endpoint is not specified, it can change during cloud formation deployments. These VPC endpoints should have the option to be constant.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

1.172

### Environment details (OS name and version, etc.)

Amazon Linux 5.4 kernel

**Comment by gshpychka** [comment]
This is a high-level (L2) construct, so it does it in a more abstract way - it accepts an entire `Vpc` object instead. If you for some reason need to only specify the vpc ID, you can use the low-level `CfnVpcEndpoint`.

>If the VPC Endpoint is not specified, it can change during cloud formation deployments. These VPC endpoints should have the option to be constant.

Can you clarify what you mean by this?

**Comment by caojoshua** [comment]
I should say `If the VCP Endpoint ID is not speificied...`. In my case, I refactored my CDK code a little. The configuration of the VPC endpoint was the same, but I changed the CDK ID (the second argument thats always after the `App` argument). This resulted in the VPC endpoint changing when I deployed to Cloud Formation. This VPC Endpoint ID was already approved by an external service, and now I need to talk to those service owners again.

Having the option to hardcode a VPC Endpoint ID would prevent this from happening. I will try `CfnVpcEndpoint`. Thank you.

**Comment by gshpychka** [comment]
Oh, the Endpoint ID isn't something you control - it's generated automatically.

>This resulted in the VPC endpoint changing when I deployed to Cloud Formation. This VPC Endpoint ID was already approved by an external service, and now I need to talk to those service owners again.

Yes, changing the logical ID always results in resource replacement with all CDK constructs.

>Having the option to hardcode a VPC Endpoint ID would prevent this from happening.

It wouldn't, but this isn't possible anyway.

**Comment by jonberthet** [comment]
I agree with @gshpychka - using the low-level `CfnVpcEndpoint`. I used it successfully with a config that looks like this:


`                      vpc_endpoints=[ec2.CfnVPCEndpoint(self, 
                                                                                      <VPC_ENDPOINT_ID> 
                                                                                      vpc_id=<VPC_ID>,
                                                                                      service_name="com.amazonaws.us-east-1.execute-api",
                                                                                      vpc_endpoint_type="Interface")])
`
