### ISSUE TITLE
(cli): allow asset publishing (or at least the asset generation) to run in sequence

### ISSUE THREAD

**Issue by huyphan** [aws/aws-cdk#22179]
### Describe the feature

Currently, the CDK CLI always publishes assets in parallel. I would like to be able to change this behaviour via a command line parameter so that they run in sequence. This behaviour is actually configurable via the `publishInParallel` prop of the `AssetPublishing` class 

https://github.com/aws/aws-cdk/blob/74318c7d22bfc00de9e005f68a0a6aaa58c7db39/packages/cdk-assets/lib/publishing.ts#L33

but when it is used, the value is hard-coded to `true` 

https://github.com/aws/aws-cdk/blob/5cc0d3514dd6c1bedd8233ec48074257b003fed0/packages/aws-cdk/lib/util/asset-publishing.ts#L47

### Use Case

In our CDK packages, assets are configured to be generated during publishing step using the `source.executable` property. Example of a manifest file:

```
{
  "version": "20.0.0",
  "files": {
    "<artifact-name>": {
      "source": {
        "executable": ['some', 'internal', 'command']
      },
      "destinations": {
        "<s3-bucket>": {
          "bucketName": "...",
          "objectKey": "...",
          "region": "us-west-2"
        }
      }
    }
  },
  "dockerImages": {}
}
```

If we have more than one assets, their publishing steps are run in parallel, the generation steps are also executed in the same fashion. Our internal tool has a unavoidable limitation where it can fail when running in parallel in some edge cases. We need the ability to tell CDK to run the asset publishing steps (or at least the asset generation steps) in sequence.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

N/A

### Environment details (OS name and version, etc.)

N/A

**Comment by misterjoshua** [comment]
Agreed that `publishInParallel` could be easily configurable. The CLI arg sounds like a good idea, but I wonder whether we should consider a `cdk.json` option as well.

**Comment by huyphan** [comment]
`cdk.json` works too!

**Comment by rix0rrr** [comment]
Fixed in https://github.com/aws/aws-cdk/pull/22579
