### ISSUE TITLE
aws-rds: Updating engine version on DBInstances that are part of a cluster causes an error

### ISSUE THREAD

**Issue by joshlartz** [aws/aws-cdk#22180]
### Describe the bug

When AWS::RDS::DBInstance resources are part of a AWS::RDS::DBCluster, trying to update their engine version results in an error.

### Expected Behavior

The CloudFormation update should succeed with the engine version update.

### Current Behavior

`The specified DB Instance is a member of a cluster. Modify the DB engine version of the DB Cluster using the ModifyDbCluster API`

### Reproduction Steps

Using `rds.DatabaseCluster` sets the engine version on the cluster as well as all of the instances it creates. 

### Possible Solution

Do not set engine version on the instances, only the cluster.

### CDK CLI Version

2.40.0

### Node.js Version

16.10

### OS

MacOS

### Language

Typescript

**Comment by joshlartz** [comment]
Willing to fix

**Comment by joshlartz** [comment]
https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/847

**Comment by corymhall** [comment]
@joshlartz it looks like this is the same issue that was reported in
https://github.com/aws/aws-cdk/issues/21758. I'll close this one, but if you are willing to submit a
fix that would be awesome!

**Comment by joshlartz** [comment]
@corymhall the PR to fix it was already attached to this issue. Can you give that a review so we can get it merged?
