### ISSUE TITLE
(elbv2): Health check interval should be longer than timeout

### ISSUE THREAD

**Issue by riita10069** [aws/aws-cdk#22200]
### Describe the feature

Hi Team!!
I would like to add the ALB health check validation.
What I felt needed support was the relationship between timeout and interval. The interval should be longer than the timeout.

Otherwise, timeout must be between 2 seconds and 120 seconds.
Interval must be at least 5 seconds but not more than 300 seconds.

![image](https://user-images.githubusercontent.com/42636694/191897862-641e4c0f-f8a0-4a31-a871-2ceada8f7e48.png)

### Use Case

It is undesirable that the value set in CDK is not detected as an error until it is deployed, since exceptions should be found at the synth stage.
As an example, we found health checks.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.43.0

### Environment details (OS name and version, etc.)

Mac OS

**Comment by rix0rrr** [comment]
Sounds good. Is this purely about the health check?

**Comment by colifran** [comment]
I reviewed #24197 and it looks like the work done there resolves this issue.
