### ISSUE TITLE
diff: cdk diff does not handle non-latin characters correctly

### ISSUE THREAD

**Issue by igormukhin** [aws/aws-cdk#22203]
### Describe the bug

If the deployed version of your CF template has non-latin characters in it, the `cdk diff` does not understand those characters. 

### Expected Behavior

`cdk diff` should correctly handle non-latin characters in the deployed version of CF template.

### Current Behavior

non-latic characters in the deployed version of CF template are seen as question marks `?`.

### Reproduction Steps

Use:
```typescript
const app = new cdk.App();
const bugStack = new Stack(app, 'non-latin-in-diff-bug');
new secMan.Secret(bugStack, 'secret', {
    secretName: 'secret',
    description: 'привет öäüß',
});
```

Run: `cdk deploy non-latin-in-diff-bug`
Then run: `cdk diff non-latin-in-diff-bug`

The output will be: 
```
Stack non-latin-in-diff-bug
Resources
[~] AWS::SecretsManager::Secret secret secret4DA88516 
 └─ [~] Description
     ├─ [-] ?????? ????
     └─ [+] привет öäüß
```

### CDK CLI Version

2.43.0 (build 487870a)

### Framework Version

2.43.0

### Node.js Version

v16.15.1

### OS

Windows 10

### Language

Typescript

### Language Version

4.8.3

**Comment by peterwoodworth** [comment]
I'm pretty certain that unfortunately, CloudFormation's [`GetTemplate`](https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_GetTemplate.html) API call, which we utilize under the hood to make diff possible, messes up certain characters in a way that is non recoverable, and there's nothing we can do about it. This may be something you will want to report in the [CloudFormation Coverage Roadmap](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues)
