### ISSUE TITLE
core: unable to deploy stage. Got "No stack found in the main cloud assembly"

### ISSUE THREAD

**Issue by boillodmanuel** [aws/aws-cdk#22202]
### Describe the bug

Hi,

I have the following structure:
```yaml
- App:
  - Stage:
    - Stack1
    - Stack2
```

When I list the stacks with `cdk ls`, the 2 stacks are displayed.

But when I try to **deploy the stage with `cdk deploy --all`, I got the following error**: `No stack found in the main cloud assembly` (see [source code](https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk/lib/api/cxapp/cloud-assembly.ts#L125)).

I'm still able to deploy a single stack with `cdk deploy stage/Stack1`.

I'm not sure about how to use the `Stage` construct as there are very few documentation (or no doc).

### Expected Behavior

I expect to be able to deploy all the stage

### Current Behavior

Got `No stack found in the main cloud assembly` error

### Reproduction Steps

You can reproduce the issue with the following `./bin/bug.ts`
```ts
#!/usr/bin/env node
import 'source-map-support/register';
import { Construct } from "constructs";
import * as cdk from 'aws-cdk-lib';

export class MyStage extends cdk.Stage {
  
  constructor(scope: Construct, id: string) {
    super(scope, id);

    new cdk.Stack(this, 'stack1');
    new cdk.Stack(this, 'stack2');
  }
}


const app = new cdk.App();
new MyStage(app, 'stage')
```

### CDK CLI Version

2.43.0

### Node.js Version

v16.15.0

### OS

windows 10

### Language

Typescript

### Language Version

3.9.7

**Comment by peterwoodworth** [comment]
You can only directly deploy top level stacks within your CDK app; if stacks are defined within a stage then they are not top level.

A way to achieve what you're looking for is to do this:

```
cdk synth
cdk deploy --app cdk.out/assembly-stage --all
```

cdk synth will produce a cloud assembly for your stage which cdk deploy can deploy if you tell it to deploy the stage directory in cdk.out
