### ISSUE TITLE
pipelines: ShellStepProps envFromCfnOutput needs CfnOutput not StackOutputReference

### ISSUE THREAD

**Issue by jnawk** [aws/aws-cdk#22219]
### Describe the issue

According to the documentation, cdk.pipelines.ShellStepProps.envFromCfnOutputs needs a Record<string, cdk.pipelines.StackOutputReference>, while according to the code, it needs a Record<string, cdk.CfnOutput>

### Links

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.pipelines.ShellStep.html#envfromcfnoutputs

**Comment by peterwoodworth** [comment]
You're looking at the property of the ShellStep construct, not the parameter in [ShellStepProps](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.pipelines.ShellStepProps.html#envfromcfnoutputs) which specifies CfnOutput 🙂

**Comment by jnawk** [comment]
Fair enough.  I'm used to reading documentation where the inputs are not indirected off to another page. 
Perhaps take that feedback?   Too much clicking.

**Comment by tim-finnigan** [comment]
Thanks for the feedback. I don't think there are any plans to restructure the docs at this time but please let the team know if you have any suggestions for alternative approaches.
