### ISSUE TITLE
(glue): Flex execution option

### ISSUE THREAD

**Issue by joekendal** [aws/aws-cdk#22224]
### Describe the feature

Following the release of [AWS Glue Flex](https://aws.amazon.com/about-aws/whats-new/2022/08/aws-glue-supports-flex-execution-option/) it would be good if CDK/CFN could support this 

### Use Case

To save costs

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.41.0

### Environment details (OS name and version, etc.)

Prefer not to say

**Comment by peterwoodworth** [comment]
CloudFormation will need to support this before we can on our L1 or L2 constructs. I suggest raising an issue with them on the [CloudFormation coverage roadmap](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues) if one doesn't exist already.

Currently you should be able to achieve this with an [AwsCustomResource](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.custom_resources.AwsCustomResource.html) until CloudFormation supports this directly

**Comment by hunt3ri** [comment]
The CloudFormation property appears to be available now, it's listed here as **execution_class** where it can be set to a string "FLEX" if I understand correctly

[https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_glue/CfnJob.html](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_glue/CfnJob.html)
