### ISSUE TITLE
API Gateway: Too Many Requests Error 

### ISSUE THREAD

**Issue by besh0y** [aws/aws-cdk#22229]
### Describe the bug

Request to re-visit the issue mentioned in [#15573](https://github.com/aws/aws-cdk/issues/15573).

When creating a stack with many API Gateway resources, deployment fails returning too many requests error. 

### Expected Behavior

I expect that CDK conforms to API Gateway's rate limits in the internal communication between cloud formation and API Gateway and that deployments go through smoothly.

### Current Behavior

I get 429 - too many requests error.

### Reproduction Steps

I've created this: [repository](https://github.com/besh0y/cdk-rest-api), that consistently replicates the issue, please feel free to check it out.

The code creates a REST API with a large number of endpoints and methods, all created in multiple nested stacks.
Deployment of those stacks always fails, returning a too many requests error, also rollback fails for the same reason.

### CDK CLI Version

2.43.0

### Node.js Version

v16.15.1

### OS

macOS

### Language

Typescript, Python

**Comment by peterwoodworth** [comment]
Thanks for opening this issue @besh0y, I've reopened the linked issue so that the discussion there is more visible, and I'll be closing this issue to consolidate discussion in the old issue. Thanks 🙂
