### ISSUE TITLE
(step-functions): (taskInput from jsonPath not working)

### ISSUE THREAD

**Issue by YTvW** [aws/aws-cdk#22246]
### Describe the bug

when specifying a task input from jsonPathAt it get transformed into a parameters field which causes the input to the task to be the jsonPath string instead of the expected value at the specified path

### Expected Behavior

I expected the input to be the object at the jsonPath and not the path itself

### Current Behavior

![Schermafbeelding 2022-09-27 om 09 01 02](https://user-images.githubusercontent.com/11088846/192456055-3a429462-24c4-4fc5-b0d0-db97

instead of an input path

### Reproduction Steps

` const test = new LambdaInvoke(this, 'test', {
        lambdaFunction: TestFn,
        payload: TaskInput.fromJsonPathAt('$.test'),
      });`

### Additional Information/Context

![Schermafbeelding 2022-09-27 om 09 01 02](https://user-images.githubusercontent.com/11088846/192456055-3a429462-24c4-4fc5-b0d0-db97c49a3aee.png)

### CDK CLI Version

2.28.1 (build d035432)

### Node.js Version

v14.20.0

### OS

MacOs

### Language

Typescript

**Comment by peterwoodworth** [comment]
Hey, thanks for opening an issue with us.

I'm not too certain what exactly it is you're experiencing that's unexpected, and what the correct output would look like. The attachment you tried to link under `Current Behavior` doesn't work unfortunately. Also, what exactly are you trying to accomplish, could you give full reproduction steps please?
