### ISSUE TITLE
ApplicationTargetGroup / FargateService: Modifies ALB SG Outbound Rules to only allow Fargate SG 

### ISSUE THREAD

**Issue by phancox** [aws/aws-cdk#22262]
### Describe the bug

ALB already has SG with default outbound rules of 0.0.0.0/0 and ::/0, supporting multiple target groups each with its own destination SG.

CDK uses the following construct to add target group for new fargate service:
```        
        const targetGroup = new ApplicationTargetGroup(this, 'TargetGroup', {
            targetGroupName: this.stackName,
            targetType: TargetType.IP,
            vpc: vpc,
            port: 80,
            targets: [fargateService],
            healthCheck: {path: '/'}
        });

        const listenerRule = new ApplicationListenerRule(this, 'ListenerRule', {
            priority: 3,
            listener: listener,
            conditions: [ListenerCondition.hostHeaders(props.hostHeaders)],
            action: ListenerAction.forward([targetGroup])
        });

```

Following deployment all existing ALB targets start failing health checks as ALB SG outbound rules have been replaced with explicit rule allowing only the fargate service SG a as destination.

### Expected Behavior

When modifying ALB SG outbound rules, the rule to allow outbound traffic to the fargate service SG should be merged or added to the ALB SG instead of replacing them.

### Current Behavior

Existing ALB SG outbound rules are replaced with rule that only allows outbound traffic to the new service.

### Reproduction Steps

Create an ALB with multiple target groups and a SG with default outbound rules (in our case this was done with cloudformation JSON not cdk).

Deploy a fargate service and attach it the existing ALB listener using:
```
        const fargateService = new FargateService ..... (nothing special here)

        const listener = ApplicationListener.fromLookup(this, 'Listener', {
            listenerArn: props.listenerArn
        });
 
        const targetGroup = new ApplicationTargetGroup(this, 'TargetGroup', {
            targetGroupName: this.stackName,
            targetType: TargetType.IP,
            vpc: vpc,
            port: 80,
            targets: [fargateService],
            healthCheck: {path: '/'}
        });

        const listenerRule = new ApplicationListenerRule(this, 'ListenerRule', {
            priority: 3,
            listener: listener,
            conditions: [ListenerCondition.hostHeaders(props.hostHeaders)],
            action: ListenerAction.forward([targetGroup])
        });
```

### CDK CLI Version

2.43.1 (build c1ebb85)

### Framework Version

2.43.1

### Node.js Version

v16.14.2

### OS

Linux

### Language

Typescript

### Language Version

TypeScript (4.8.3)

**Comment by corymhall** [comment]
It looks like we already have an open issue for this #22140. I'll close this one and we can track
via that issue.
