### ISSUE TITLE
(aws-cloudtrail): isOrganizationTrail attaches insufficient permissions to bucket

### ISSUE THREAD

**Issue by danilobuerger** [aws/aws-cdk#22267]
### Describe the bug

When using a Trail with `isOrganizationTrail: true`, the bucket policy contains insufficient permissions and the stack creation fails with:

```
Invalid request provided: Incorrect S3 bucket policy is detected for bucket: ...
```

The Trail attaches the following permissions:

https://github.com/aws/aws-cdk/blob/c425e8ca1a3d296eb6a7fd7e005d07c1eadd16aa/packages/%40aws-cdk/aws-cloudtrail/lib/cloudtrail.ts#L226-L241

However, it is missing:

```
"Action": "s3:PutObject",
"Resource": "arn:aws:s3:::myOrganizationBucket/AWSLogs/o-exampleorgid/*"
```

as described here: https://docs.aws.amazon.com/awscloudtrail/latest/userguide/create-s3-bucket-policy-for-cloudtrail.html#org-trail-bucket-policy

### Expected Behavior

It creates an organization trail.

### Current Behavior

It fails with
```
Invalid request provided: Incorrect S3 bucket policy is detected for bucket: ...
```

### Reproduction Steps

```
const bucket = new Bucket(this, "Bucket");
new Trail(this, 'Trail', { bucket, isOrganizationTrail: true });
```

### Possible Solution

Adding the permission as outlined above.

### CDK CLI Version

2.43.1

### Node.js Version

18.9.0

### OS

macOS

### Language

Typescript

**Comment by peterwoodworth** [comment]
Thanks for reporting this @danilobuerger,

I can reproduce this just with this snippet

```ts
    new Trail(this, 'Trail', {
      isOrganizationTrail: true
    });
```

@daschaa did you ever run into this error? It's suspicious to me that the integration test you submitted with this PR works if I can't get it to deploy now here

**Comment by daschaa** [comment]
@peterwoodworth That's very strange. The integration tests should have failed in the pull request.
I'm sorry that I forgot to adjust the permissions!

The challenge that we will now face is, that we have to pass/retrieve the belonging organization id to construct the correct permission statement. @peterwoodworth Afaik there is no way to get the organization id from the props that are passed when instantiating a trail. Do you know if this is possible?

**Comment by danilobuerger** [comment]
@daschaa a few ideas:
1) pass the organization id as a prop
2) use a custom resource to fetch it: https://docs.aws.amazon.com/organizations/latest/APIReference/API_DescribeOrganization.html
3) Tighten the policy via `aws:SourceArn` instead, but allowing a wider s3 prefix:
```json
"Principal": {
  "Service": [
    "cloudtrail.amazonaws.com"
  ]
},
"Action": "s3:PutObject",
"Resource": "arn:aws:s3:::myOrganizationBucket/AWSLogs/*",
"Condition": {
  "StringEquals": {
    "s3:x-amz-acl": "bucket-owner-full-control",
    "aws:SourceArn": "arn:aws:cloudtrail:region:111111111111:trail/trailName"
  }
}
```

**Comment by daschaa** [comment]
@danilobuerger Thanks for the good hints. ❤️ 
I like the idea to pass in a prop with the organization id. The challenge will be then to bind the flag `isOrganizationTrail` to the mandatory property `organizationId`. It's doable, but maybe not that clean.
An option would be to introduce a `OrganizationTrail`, which inherits all the stuff from a `Trail` but has a mandatory parameter `organizationId`. Then the boolean flag is no longer needed and from a user experience it is clear why an organization id is needed.

At the first glance the third option you mentioned would maybe be the easiest to implement and it would not introduce big changes to the current implementation. But I'm not sure if that would violate the principle of least privilege.

@danilobuerger What is the best option in your opinion?

**Comment by sionelt** [comment]
I recently ran into the same issue and had to attach the missing organization policy to the bucket to make it work. 

I hope I'm not putting in, but I do like the suggestion to have a new construct `OrganizationTrail` that extends the `Trail`, a much better design than the current `isOrganizationTrail` boolean.  And requiring `organizationId` to narrow now the policy makes for better security.

**Comment by paulhcsun** [comment]
Hey @beniusij, a fix is in the works but for now I've found this workaround from a duplicate issue opened in 2020: https://github.com/aws/aws-cdk/issues/11602#issuecomment-1519104217.
