### ISSUE TITLE
aws-cdk-lib/aws-codepipeline-actions: S3DeployActionProps is missing KMSEncryptionKeyARN

### ISSUE THREAD

**Issue by KSSLR** [aws/aws-cdk#22266]
### Describe the bug

The S3 deploy action supports a KMS encryption key that the action uses to encrypt objects uploaded to a bucket. The CloudFormation resource Action inside a Stage inside a AWS::CodePipeline::Pipeline carries a configuration property "KMSEncryptionKeyARN" that indicates the KMS key to use (https://docs.aws.amazon.com/codepipeline/latest/userguide/action-reference-S3Deploy.html). This property is missing in aws-cdk-lib » aws_codepipeline_actions » S3DeployActionProps (https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_codepipeline_actions.S3DeployActionProps.html).

### Expected Behavior

I expected the S3DeployActionProps interface to have a KMSEncryptionKeyARN and the S3DeployAction class to emit this property to the CloudFormation template.

### Current Behavior

Neither S3DeployActionProps nor S3DeployActionProps support KMSEncryptionKeyARN

### Reproduction Steps

`const deployAction = new S3DeployAction({
                                actionName: 'SomeActionName',
                                input: codePipelineArtifact,
                                bucket: s3BucketWithEncryption,
                                role: deploymentRole
                            }`

### Possible Solution

In S3DeployActionProps:
`readonly kmsEncryptionKeyArn?: string;`

In S3DeployAction
`return {
      configuration: {
        BucketName: this.props.bucket.bucketName,
        Extract: this.props.extract === false ? 'false' : 'true',
        ObjectKey: this.props.objectKey,
        CannedACL: acl ? toKebabCase(acl.toString()) : undefined,
        CacheControl: this.props.cacheControl && this.props.cacheControl.map(ac => ac.value).join(', '),
        KMSEncryptionKeyARN: this.props.kmsEncryptionKeyArn
      },`

### CDK CLI Version

2.24.1

### Node.js Version

18.7.0

### OS

macOS Monterey 12.6

### Language

Typescript

### Language Version

4.4.4

**Comment by peterwoodworth** [comment]
Thanks for submitting this request @KSSLR, I believe we'd want to eventually render this under the [Configuration property](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codepipeline-pipeline-stages-actions.html#cfn-codepipeline-pipeline-stages-actions-configuration)

I am marking this issue as p2, which means that we are unable to work on this immediately.

We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://join.slack.com/t/cdk-dev/shared_invite/zt-mso6p56d-qJp7SOTBvMaQuDrx7R2wHg) to solicit support for reprioritization.

Check out our [contributing guide](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) if you're interested in contributing yourself - there's a low chance the team will be able to address this soon but we'd be happy to review a PR 🙂

**Comment by tam0ri** [comment]
This feature was already released by #24536

**Comment by peterwoodworth** [comment]
Thanks @tam0ri!
