### ISSUE TITLE
(synthetics): Canary code building similar to aws-cdk-lib/aws-lambda-nodejs/NodejsFunction

### ISSUE THREAD

**Issue by kogitant** [aws/aws-cdk#22271]
### Describe the feature

The developer experience of writing Cloudwatch Synthetics canary scripts would be much nicer if support was provided for "packaging" the script code in a similar manner to NodejsFunction available when implementing lambda functions using typescript or javascript. 

Adopting the same mechanism for canary scripts would 
* allow writing the code in typescript or javascript, 
* define a package.json with developmentDependencies etc. 

This would also allow developers to not know or care about the internals of  Cloudwatch Synthetics runtime and the need for having the canary scripts under nodejs/node_modules directory.

### Use Case

Needing to place canary javascript files under node_modules directory makes script development quite painful. The need to package them under nodejs/node_modules is a runtime detail that shouldn't affect how  the source code is organized during development. One could of course use something like Gulp to implement the "packaging" and potential typescript compilation of canary scripts into a directory with the required nodejs/node_modules structure. But this seems like something that CDK could solve for all by applying the same mechanisms used in aws-cdk-lib/aws-lambda-nodejs/NodejsFunction

### Proposed Solution

Copy-paste of aws-cdk-lib/aws-lambda-nodejs/NodejsFunction into something that accepts nodejs and typescript source in any directory structure the developer desires and deploys the javascript canary scripts in whatever directory structure the Cloudwatch Synthetics service requires.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.43.0

### Environment details (OS name and version, etc.)

macOs Monterey

**Comment by kaizencc** [comment]
I feel like, if we had the chance to change things, L3 libraries like `NodejsFunction` would live separately from the core libraries. I encourage you to write a L3 `NodejsCanary` library and publish it to construct hub. That is the likely path forward for this feature request.

**Comment by kaizencc** [comment]
Since #26291 is merged, that is the most that we are going to do in CDK-land to support bundling canary code. We will support bundled code if it is self-rolled. Any additional abstraction should be its own 3rd party construct. 

Here's a good option: https://github.com/mrgrain/cdk-esbuild#amazon-cloudwatch-synthetics-canary-monitoring
