### ISSUE TITLE
cdk-assets usage example with aws-codepipeline pipeline

### ISSUE THREAD

**Issue by rantoniuk** [aws/aws-cdk#22273]
### Describe the issue

So I see now there is this experimental CLI command [cdk-assets](https://www.npmjs.com/package/cdk-assets) tool, that allows to manually deploy all the assets that are generated after doing `cdk synth` - that would finally address #20609 and #13940.

What I am missing is an example on the best way to add it to the `Pipeline()` from `aws-cdk-lib/aws-codepipeline`.
Note that I don't want to migrate to using `CodePipelines()` construct that does this under the hood. What I would like is to manually add a deployment step in the pipeline definition that would deploy the assets in the bootstrap bucket of the target account. 

Does this mean that before the  `CloudFormationCreateUpdateStackAction()` for each target IAM account (e.g. TEST/ACC) I would need to add a CodeBuildProject that:
- would get the zipped cdk.out/**/* artifacts
- execute `cdk-assets publish`  using the target IAM account role 
?

That would mean creating extra CodeBuildProject(s) for each of the target environments (which seems to me like a bit of an overhead), so I'm making sure that I haven't missed any relevant CDK helper for this (apart from migrating to CodePipeline of course).

Thanks in advance for support.

### Links

https://www.npmjs.com/package/cdk-assets
https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.pipelines-readme.html

**Comment by indrora** [comment]
Thank you for your documentation request. 

If my understanding is correct (I believe @TheRealAmazonKendra or @rix0rrr can explain better), you're correct that unless you're migrating to the full CodePipelines stack, you'll need to build a CodeBuildProject that is configured to your application's specific current configuration (e.g. Test/Prod/etc).
