### ISSUE TITLE
aws-s3: cannot set EncryptionKey for IBucket  /  fromBucketArn

### ISSUE THREAD

**Issue by tamerin-tech** [aws/aws-cdk#22285]
### Describe the feature

When importing existing S3 resource (using Bucket.fromBucketArn) there is no direct way to specify the custom KMS key used for it.
This leads later to some issues when trying to use the imported bucket for deployment in pipelines, since in our case we have to enforce encryption for each upload:

```
{
  "Version": "2012-10-17",
  "Id": "PutObjectPolicy",
  "Statement": [
    {
      "Sid": "DenyIncorrectEncryptionHeader",
      "Effect": "Deny",
      "Principal": "*",
      "Action": "s3:PutObject",
      "Resource": "arn:aws:s3:::mybucketname/*",
      "Condition": {
        "StringNotEquals": {
          "s3:x-amz-server-side-encryption": "aws:kms"
        }
      }
    },
    {
      "Sid": "DenyUnencryptedObjectUploads",
      "Effect": "Deny",
      "Principal": "*",
      "Action": "s3:PutObject",
      "Resource": "arn:aws:s3:::mybucketname/*",
      "Condition": {
        "Null": {
          "s3:x-amz-server-side-encryption": "true"
        }
      }
    }
  ]
}
```

the **encryptionKey** property of IBucket is readonly _(Cannot assign to 'encryptionKey' because it is a read-only property.ts(2540))_

We are currently using the following workaround:
const bucket = s3.Bucket.fromBucketArn(scope, resourceId, bucketARN);
(bucket as any).encryptionKey = kms.Key.fromKeyArn(scope, resourceId + '-KmsKey', KeyArn);

### Use Case

importing an existing bucket with custom KMS encryption key

### Proposed Solution

extend Bucket.fromBucketArn(...) to allow importing also existing encryption key

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.34.2

### Environment details (OS name and version, etc.)

VSCode / Windows 10

**Comment by peterwoodworth** [comment]
Hey @tamerin-tech, thanks for this request

I suggest using the [`Bucket.fromBucketAttributes()`](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_s3.Bucket.html#static-fromwbrbucketwbrattributesscope-id-attrs) method 🙂 You'll be able to [supply the encryption key directly](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_s3.BucketAttributes.html) and still import the bucket from its arn

The `fromBucketArn()` method is meant to be simple without additional configuration, so when you need additional configuration when importing a bucket try using `fromBucketAttributes()`. Thanks!
