### ISSUE TITLE
(aws_sagemaker): Unresolved Dependencies Referencing Bucket From Parent Stack

### ISSUE THREAD

**Issue by RLashofRegas** [aws/aws-cdk#22299]
### Describe the bug

When using the `aws_sagemaker` package to deploy a `CfnPipeline` object I get an "Unresolved resource dependencies" error when referencing a bucket from the parent stack in the pipeline definition.

### Expected Behavior

Stack should create successfully and should be able to reference buckets from the parent stack.

### Current Behavior

Received Error: "Template format error: Unresolved resource dependencies [abalonebucket8FE5F34C] in the Resources block of the template (Service: AmazonCloudFormation; Status Code: 400; Error Code: ValidationError; Request ID: XXXXXXX; Proxy: null)"

### Reproduction Steps

My parent stack creates a basic `aws_s3.Bucket` resource and passes it to the stack that defines by `CfnPipeline`. In the child stack I use `my_bucket.s3_url_for_object(...)` to create (for example) paths to input data using `sagemaker.workflow.parameters.ParameterString`. I can see in the generated template after `cdk synth` that the CDK has successfully added a `Fn::Join` node to join parts of the pipeline definition with references to CFN resouces. However, the references are not correctly handling the fact that the bucket is in the parent stack. I see something like `"Ref": "abalonebucket8FE5F34C"`, whereas the `aws_iam.Role` that is created in the same stack correctly references the bucket like this: `"Fn::ImportValue": "AppDeploymentStage-CdkSagemakerPipelineApp:ExportsOutputFnGetAttabalonebucket8FE5F34CArn0140B6D8"`. 

### CDK CLI Version

2.42.0 (build 7d8ef0b)

### Node.js Version

v16.17.0

### OS

macOS Monterey Apple M1

### Language

Python

### Language Version

3.8.10

**Comment by peterwoodworth** [comment]
Could you please post the full reproduction code which demonstrates this @RLashofRegas? I'm not sure exactly what it is you're trying to do in the second stack 🙂
