### ISSUE TITLE
RequestAuthorizer construct cannot be created

### ISSUE THREAD

**Issue by lhuang61** [aws/aws-cdk#22300]
### Describe the bug

When trying to create a RequestAuthorizer, it throws error `Resolution error: Authorizer must be attached to a RestApi`. But props for the `RequestAuthorizer` construct does not allow a `RestApiId` to be passed in.

### Expected Behavior

There should be a way to attach a API Gateway REST API via props.

### Current Behavior

error `Resolution error: Authorizer must be attached to a RestApi`

### Reproduction Steps

```
this.apiGatewayAuthorizer = new api.RequestAuthorizer(this, 'LambdaRequestAuthorizer', {
            handler: this.authoriserLambda,
            identitySources: [api.IdentitySource.header('Authorization')]
        });

this.apiGateway.methods.forEach((apiMethod) => {
            const child = apiMethod.node.findChild('Resource') as api.CfnMethod;

            child.addPropertyOverride('RestApiId', { Ref: this.apiGateway.restApiId });
            child.addPropertyOverride('AuthorizationType', 'CUSTOM');
            child.addPropertyOverride('AuthorizerId', { Ref: this.apiGatewayAuthorizer.authorizerId });
        });
```

### CDK CLI Version

2.41.0

### Node.js Version

v18.2.0

### OS

macOS Monterey

### Language

Typescript

**Comment by peterwoodworth** [comment]
Is there anything preventing you from passing in the authorizer to [`Method.options`](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_apigateway.MethodOptions.html) on creation of the Method?
