### ISSUE TITLE
RDS: Changing instance type only updated reader instance

### ISSUE THREAD

**Issue by sblackstone** [aws/aws-cdk#22306]
### Describe the bug

Using the following code, I updated InstanceSize.SMALL to InstanceSize.MEDIUM and ended up in a state where the reader instance was upgraded but the writer instance was not.

```
    this.database = new DatabaseCluster(this, 'Database', {
      engine: DatabaseClusterEngine.auroraMysql({version: AuroraMysqlEngineVersion.VER_2_10_1}),
      instances: 1,
      credentials: Credentials.fromGeneratedSecret('admin'),
      removalPolicy: RemovalPolicy.DESTROY,
      defaultDatabaseName: props.databaseName,
      instanceProps: {
        instanceType: InstanceType.of(InstanceClass.BURSTABLE3, InstanceSize.SMALL), // Changed this to MEDIUM!
        vpc: props.vpc,
        vpcSubnets: {
          subnets: props.vpc.publicSubnets
        },
        publiclyAccessible: true
      },
    });
```

### Expected Behavior

Writer instance should also be upgraded 

### Current Behavior

Writer instance was not upgraded.

### Reproduction Steps

deploy stack with component as above and then redeploy with InstanceSize.MEDIUM

### CDK CLI Version

2.044

### Node.js Version

14.19

### OS

OSX

### Language

Typescript

**Comment by corymhall** [comment]
@sblackstone the code that you provided only provisions a single instance. Did you create a separate
instance outside of CDK?
