### ISSUE TITLE
aws-cdk-go: Example of how to use Integ-Runner?

### ISSUE THREAD

**Issue by diranged** [aws/aws-cdk#22329]
### Describe the issue

There are a number of articles, blogs and documentation posts about how to write integration test with the AWS CDK in Typescript. However, I am not finding any examples of how to use it with other languages like Python, Go or Java. In particular, I am looking for an example repo that shows a full integration test suite for the CDK in Go.

I am aware of https://www.go-on-aws.com/testing-go/integration/integ_infra/ - which discusses using `github.com/megaproaktiv/cit/citlambda`... but that is very lightly written, and ultimately points to docs like https://aws-blog.com/2021/05/cit-build-cdk-infrastructure-testing-part-1-terratest-and-the-integrated-integration.html which are again written in typescript.

I think in particular, the most confusing part for me is that documentation at https://pkg.go.dev/github.com/aws/aws-cdk-go/awscdkintegtestsalpha/v2#section-readme clearly shows example test/validation code in Go, but they do not discuss how to actually run the tests.

Making things more confusing, the docs have a circular link when they point you to the `integ-runner` CLI docs:
![image](https://user-images.githubusercontent.com/768067/193616623-0cc36412-06b8-45c5-a80b-e103d44d214f.png)

The `integ-runner` link refers to https://pkg.go.dev/github.com/aws/aws-cdk-go/awscdkintegtestsalpha/v2#readme- ... which is the doc that we're already on.

### Links

https://pkg.go.dev/github.com/aws/aws-cdk-go/awscdkintegtestsalpha/v2#section-readme

**Comment by indrora** [comment]
Please be aware that the two articles you've linked to are not affiliated with AWS. 

Due to what I can only but assume is an error in the pkg.go.dev renderer, the link was mis-rendered. The proper URL is https://github.com/aws/aws-cdk/tree/main/packages/%40aws-cdk/integ-runner

There is an example of how to run the integration test runner there. I hope this helps.
