### ISSUE TITLE
(integ-tests): Set environment for Deploy Assert Stack

### ISSUE THREAD

**Issue by dontirun** [aws/aws-cdk#22332]
### Describe the feature

Allow setting the AWS environment (account/region) for the deploy assert stack

### Use Case

I have a construct that uses ELBv2 access logging. ELBv2 access logging requires setting the region for the cdk environment. As showcased by this error

`Error: Region is required to enable ELBv2 access logging`

After setting the environment, I received the following error when I attempted to pass a reference to an Api Call in the Integ Test

`Error: Stack "foo/DefaultTest/DeployAssert" cannot consume a cross reference from stack "bar". Cross stack references are only supported for stacks deployed to the same environment or between nested stacks and their parent stack`

### Proposed Solution

Allow setting the cdk environment in [IntegTestProps](https://github.com/aws/aws-cdk/blob/v1-main/packages/%40aws-cdk/integ-tests/lib/test-case.ts#L116)

### Acknowledgements

- [x] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.41.0

### Environment details (OS name and version, etc.)

Osx

**Comment by corymhall** [comment]
@dontirun can you provide an example of the integ test where you see the behavior?

**Comment by dontirun** [comment]
```ts
import * as cdk from 'monocdk';
import * as ec2 from 'monocdk/aws-ec2';
import * as elbv2 from 'monocdk/aws-elasticloadbalancingv2';
import * as s3 from 'monocdk/aws-s3';
import * as integ from 'monocdk/integ-tests';


const app = new cdk.App();

const stack = new cdk.Stack(app, 'stack',
    {
        env: { region: 'us-west-2' }
    })

const nlb = new elbv2.NetworkLoadBalancer(stack, 'nlb', { vpc: new ec2.Vpc(stack, 'vpc') })
// requires region to be set
nlb.logAccessLogs(new s3.Bucket(stack, 'logbucket'))


const test = new integ.IntegTest(app, 'integ', {
    testCases: [stack],
    regions: ['us-west-2'],
});

test.assertions.awsApiCall('Elbv2', 'describeLoadBalancers', {
    Names: [nlb.loadBalancerName]
});

app.synth();
```

`Error: Stack "integ/DefaultTest/DeployAssert" cannot consume a cross reference from stack "stack". Cross stack references are only supported for stacks deployed to the same environment or between nested stacks and their parent stack`

**Comment by corymhall** [comment]
@dontirun thanks for the example, the makes perfect sense and we should definitely add this.
