### ISSUE TITLE
(secretsmanager): support sealed secrets

### ISSUE THREAD

**Issue by misterjoshua** [aws/aws-cdk#22333]
### Describe the feature

I want to store an encrypted secret value in my source code so that when deployed to a Secrets Manager Secret, the plaintext value is stored inside Secrets Manager. In effect, I want a feature similar to [Bitnami's Sealed Secrets](https://github.com/bitnami-labs/sealed-secrets), used by many in the Kubernetes community for GitOps.

### Use Case

I often find myself in situations where I must manually populate the values for AWS Secrets Manager Secrets. However, I find managing out-of-band updates to these secrets error-prone.

### Proposed Solution

```ts
// The key used to decrypt the sealed secret's ciphertext.
declare const kmsKey: aws_kms.IKey;

// Creates a secret and then uses a custom resource to decrypt the given
// ciphertext, populating the secret with the plaintext value.
new aws_secretsmanager.SealedSecret(stack, 'SealedSecret', {
  // Provide the ciphertext
  encryptedValue: '1234567890abcdef...',
  // Provide the key to decrypt the ciphertext.
  kmsKey,
});
```

### Acknowledgements

- [x] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

N/A

### Environment details (OS name and version, etc.)

N/A

**Comment by jumic** [comment]
Do you know [secretsmanager-versioning](https://github.com/taimos/secretsmanager-versioning) based on [SOPS](https://github.com/mozilla/sops)? Maybe this already solves your problem.

**Comment by hoegertn** [comment]
Or even better integrated with CDK: https://github.com/markussiebert/cdk-sops-secrets

**Comment by misterjoshua** [comment]
@jumic @hoegertn Great suggestions! I'll give those SOPS-based solutions a try.
