### ISSUE TITLE
[aws-eks]: deploying helmcharts doesn't work when repository name has slash in ECR

### ISSUE THREAD

**Issue by psemeniuk** [aws/aws-cdk#22340]
### Describe the bug

helm-charts/pet-service - which points to helm charts of pet-service
pet-service - which points to docker container images of pet-service

Of course we can use something like `pet-service-chart` but then it forces us to add this suffix to the Chart.yaml (because of how helm push works).

### Expected Behavior

Ability to deploy charts from ECR repositories which names contains slashes.

### Current Behavior

Lambda fails on:
`[ERROR]	2022-10-03T11:52:34.168Z	69bf2909-81a0-40ac-ab3e-b5006fb8dcca	OCI repository format not recognized, falling back to helm pull
`

### Reproduction Steps

1. Create repository named helm-charts/pet-service in private/public ECR
2. Put some chart there
3. Try to install it by eg.
```
aws_eks.HelmChart(
            scope=self.scope,
            id="pet-service",
            cluster="some-cluster",
            chart="pet-service",
            repository='oci://xxx.dkr.ecr.us-east-1.amazonaws.com/helm-charts/pet-service',
            release='pet-service',
            version='1.0.0'
        )
```

### Possible Solution

Take into account repository names with slashes, when extracting registry from repository property. Probably in this line: `registry = repository.rsplit('/', 1)[0].replace('oci://', '')`

### CDK CLI Version

2.38.1 (build a5ced21)

### Node.js Version

v16.14.0

### OS

CentOS

### Language

Python

### Language Version

Python 3.8.5

**Comment by pahud** [comment]
@psemeniuk I am trying to reproduce this error. Do you have or know any existing OCI images from ECR that I can test with?

**Comment by psemeniuk** [comment]
Hi,
unfortunately no - i reproduced this on private ECR

**Comment by psemeniuk** [comment]
fyi - possibly i'll have some time in next weeks, so i can try to contribute to solve these issues.
