### ISSUE TITLE
(integ-runner): Hooks do not follow spawnSync argument requirements

### ISSUE THREAD

**Issue by iriskraja77** [aws/aws-cdk#22344]
### Describe the bug

Currently the integration test command hooks are not working. 

spawnSync requires the main command and its arguments to be split into two arguments. For example, to run `npm run test`, the command specified to the spawnSync should be:

`spawnSync('npm', 'run test', {....})`

However, using the chain function, will simply provide the full command as: `spawnSync('npm run test', {....})` which simply does not work with spawn.

### Expected Behavior

Commands defined in the hooks argument would work.

### Current Behavior

Impossible to use hooks. 

### Reproduction Steps

Simply provide a command as part of the preDestroy hook. 

e.g. `echo hi` 

Will throw an error: ` spawnSync <command> ENOENT`

### Possible Solution

Fix the chain function to support spawn.

### CDK CLI Version

2.41.0

### Node.js Version

16.15.1

### OS

MacOS

### Language

Typescript

**Comment by corymhall** [comment]
@iriskraja77 thanks for reporting this bug! We shouldn't be using chain at all since exec expects a list and the hooks already provide a list.

**Comment by arewa** [comment]
Hi guys, @iriskraja77, @corymhall I prepared a PR with the fix, could you review it? I reworked the call to `exec` avoiding using `chain`.
