### ISSUE TITLE
[aws-eks]: deploying helmcharts doesn't work with ECR when release-name is different than chart-name

### ISSUE THREAD

**Issue by psemeniuk** [aws/aws-cdk#22341]
### Describe the bug

When in OCI flow lambda creates temporary directory and tries to download chart by `helm pull` with --untar flag. Then it tries to access that chart under `tmpDir/releaseName` which is incorrect, because `helm pull` already downloaded artifact to `tmpDir/chartName`. When chartName is different than releaseName it leads us to incorrect patch to downloaded chart.

### Expected Behavior

I can configure release property whatever i want without any issues

### Current Behavior

Lambda fails with:
`[ERROR] Exception: b'Error: path "/tmp/tmpqazlu281/pet-service" not found\n'`

### Reproduction Steps

1. Create repository named pet-service in ECR
2. Put some chart there
3. Try to install it by eg.
```
aws_eks.HelmChart(
            scope=self.scope,
            id="pet-service",
            cluster="some-cluster",
            chart="pet-service",
            repository='oci://xxx.dkr.ecr.us-east-1.amazonaws.com/pet-service',
            release='pet-service-latest',
            version='1.0.0'
        )
```

### Possible Solution

Get the last part from repository url, which typically is a chart name. Note the "last part" - helm pull handles repository names which contains slashes so eg. pulling from `oci://xxx.dkr.ecr.us-east-1.amazonaws.com/helm-charts/pet-service` will download artifact to pet-service/ subdirectory.

### CDK CLI Version

2.38.1 (build a5ced21)

### Node.js Version

v16.14.0

### OS

CentOS

### Language

Python

### Language Version

Python 3.8.5

**Comment by pahud** [comment]
Hi @psemeniuk 

Do you have any existing ECR images or chart I can test for this issue? And before we identify it, are you interested to submit a PR for this?

**Comment by psemeniuk** [comment]
fyi - possibly i'll have some time in next weeks, so i can try to contribute to solve these issues.
