### ISSUE TITLE
aws-cdk-lib/aws-lambda-nodejs: Using dockerImage - entrypoint broken

### ISSUE THREAD

**Issue by SchollSimon** [aws/aws-cdk#22357]
I wanted to extend my NodeJSLambda contruct with another docker base image. So i put everything together

- functionFolder
  - index.ts
  - Dockerfile

When creating the construct i pass this options and bundling options
```
  const lambda = new NodejsFunction(scope, 'BriefExportAsPdfAsync', config, {
    entry: 'pathToLambdaHandler',
    memorySize: 3096,
    architecture: Architecture.X86_64,
    timeout: Duration.seconds(180),
    environment: {
      BUCKET: uploadBucket.bucketName,
      GET_BRIEF_EXPORT_AS_DOCX_ARN: exportLambda.functionArn,
      FONTCONFIG_FILE: '/opt/fonts.conf',
      FONTCONFIG_PATH: '/opt/fonts',
      HOME: '/tmp',
    },
    layers: [fontsLayer],
    bundling: {
      //nodeModules: ['@shelf/aws-lambda-libreoffice'],
      dockerImage: DockerImage.fromBuild('pathToFolderContainingDocker'), 
      forceDockerBundling: true,
    },
  });
```

My docker file is pretty simple
```
FROM public.ecr.aws/shelf/lambda-libreoffice-base:7.4-node16-x86_64	

COPY . ${LAMBDA_TASK_ROOT}/

ENTRYPOINT ["/lambda-entrypoint.sh", "index.handler"] 
```

### Expected Behavior

Everything works the docker image is build as expected. And

`lambda-entrypoint.sh` 

inside the docker picks up the arguments provided by

ENTRYPOINT ["/lambda-entrypoint.sh", "index.handler"] 

### Current Behavior

On buildtime (cdk synth) i get the error:
`entrypoint requires the handler name to be the first argument`

So i opened an image container and looked into the `/lambda-entrypoint.sh` shell script

```
#!/bin/sh
# Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.

if [ $# -ne 1 ]; then
  echo "entrypoint requires the handler name to be the first argument" 1>&2
  exit 142
fi

export _HANDLER="$1"

RUNTIME_ENTRYPOINT=/var/runtime/bootstrap
if [ -z "${AWS_LAMBDA_RUNTIME_API}" ]; then
  exec /usr/local/bin/aws-lambda-rie $RUNTIME_ENTRYPOINT
else
  exec $RUNTIME_ENTRYPOINT
fi
```

I added some outputs 
```
#!/bin/sh
# Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.

echo $# $1 $2 $3

if [ $# -ne 1 ]; then
  echo "entrypoint requires the handler name to be the first argument" 1>&2
  exit 142
fi

export _HANDLER="$1"

RUNTIME_ENTRYPOINT=/var/runtime/bootstrap
if [ -z "${AWS_LAMBDA_RUNTIME_API}" ]; then
  exec /usr/local/bin/aws-lambda-rie $RUNTIME_ENTRYPOINT
else
  exec $RUNTIME_ENTRYPOINT
fi
```

And modified my dockerfile
```
FROM public.ecr.aws/shelf/lambda-libreoffice-base:7.4-node16-x86_64	

COPY lambda-entrypoint.sh /

RUN chmod +x /lambda-entrypoint.sh

COPY . ${LAMBDA_TASK_ROOT}/

ENTRYPOINT ["/lambda-entrypoint.sh", "index.handler"] 
```

then i run cdk synth again and saw that my `echo` produced `4 index.handler bash -c` it seems that this is the reason the cdk synth crashes. 

### Reproduction Steps

Just test the contruct with the mentioned configuration.

### CDK CLI Version

2.44.0

### Framework Version

2.41.0

### Node.js Version

v16.13.1

### OS

Windows 10

### Language

Typescript

### Language Version

4.5.4

**Comment by Pavel-Chernikov** [comment]
Have you figured this out? I'm running into the same issue while doing cdk synth to build the lambda image.

**Comment by SchollSimon** [comment]
> Have you figured this out? I'm running into the same issue while doing cdk synth to build the lambda image.

Hey @Pavel-Chernikov @rix0rrr sry for my late answer i had a tight development schedule. I was not able to solve the problem. In the end i moved on to the DockerImageFunction construct with a node runtime. That works.

**Comment by Pavel-Chernikov** [comment]
Thanks @SchollSimon
