### ISSUE TITLE
aws_s3 encryption=

### ISSUE THREAD

**Issue by alekasw** [aws/aws-cdk#22366]
### Describe the bug

When using the S3.Bucket L2 construct and setting the property `encryption=s3.BucketEncryption.KMS_MANAGED` the resulting bucket created does not display the AWS KMS key ARN when viewing the bucket properties via the AWS Console.

### Expected Behavior

Should display the AWS KMS key ARN.

### Current Behavior

The bucket created successfully, and encryption seems to be working but the AWS Key Arn field does not display the ARN of the key being used for encryption. Also, trying to enable Bucket Keys throws an error and deploy: Error: bucketKeyEnabled is specified, so 'encryption' must be set to KMS (value: MANAGED)

### Reproduction Steps

**Crate stack with below resource:**

        cv_ingress_zone = s3.Bucket(self, "cv_ingress_zone", 
            bucket_name= f"cv-ingress-zone-{account_id}",
            versioned=False,
            removal_policy=RemovalPolicy.DESTROY,
            encryption=s3.BucketEncryption.KMS_MANAGED,
            event_bridge_enabled=True
        )

**Login to the console and navigate to AWS S3 Console and click on the newly created bucket.**

**Click Properties**

**Scroll down to Encryption section. Notice that AWS Key ARN is not displayed:**

![Capture1](https://user-images.githubusercontent.com/70331690/194063311-8c20d20c-16bf-4a40-a82e-7e5b76ab1802.PNG)

**Click Edit view the actual properties:**

![Capture2](https://user-images.githubusercontent.com/70331690/194063333-bd1322e5-1dcd-47e3-9cd1-f1c1b1aecd20.PNG)

### CDK CLI Version

2.43.0

### Node.js Version

16.3.2

### OS

Windows

### Language

Python

### Language Version

3.9.7

### Other information

Although their is no AWS KMS key ARN displayed in the console. Encryption seems to be working, and when you click the Edit button on Default Encryption it does show that the correct KMS key is being used:

arn:aws:kms:us-east-1:123456789012:alias/aws/s3

**Comment by alekasw** [comment]
In addition to the above problem the below code fails with:

cv_analytics_zone = s3.Bucket(self, "cv_analytics_zone", 
            bucket_name= f"cv-analytics-zone-{account_id}",
            versioned=False,
            removal_policy=RemovalPolicy.DESTROY,
            bucket_key_enabled=True,
            encryption=s3.BucketEncryption.KMS_MANAGED
        )

Error: bucketKeyEnabled is specified, so 'encryption' must be set to KMS (value: MANAGED)

**Comment by otaviomacedo** [comment]
Hi, @alekasw 

The first issue has nothing to do with the CDK. This is a UI design choice made by the team that owns the console experience.

For the second one, please update the construct library to the latest version. That bug has already been fixed.

**Comment by peterwoodworth** [comment]
Please see the above comment, thanks
