### ISSUE TITLE
(integ-tests): awsApiCall will call the API twice in deletion as well

### ISSUE THREAD

**Issue by iriskraja77** [aws/aws-cdk#22361]
### Describe the bug

**integTest.assertions.awsApiCall** will call the specified API Call twice: once on stack creation, and another time on stack deletion. 
This can be a problem for API Calls with write actions. 

### Expected Behavior

The specified API is only called once on stack creation. 

### Current Behavior

The specified API is called twice, on stack deletion as well.

### Reproduction Steps

Simply specify any API and monitor CloudWatch Logs of the integ-test provider function. 

### Possible Solution

Only call the API in cloudformation stack creation event.

### CDK CLI Version

2.41.0

### Framework Version

2.41.0

### Node.js Version

16.15.1

### OS

MacOS

### Language

Typescript

**Comment by corymhall** [comment]
@iriskraja77 this was recently fixed in https://github.com/aws/aws-cdk/pull/22238 so it should be released in the next version of CDK which should release in the next couple of days.
