### ISSUE TITLE
(pipelines): double execution when only change to a pipeline is tags

### ISSUE THREAD

**Issue by ahammond** [aws/aws-cdk#22373]
### Describe the bug

We updated our all our stacks to include a bunch of compliance tags. When these commits were merged to main, the associated cdk pipelines ran all the way up to the self-mutate step and then both continued AND triggered a restart of the pipeline.

### Expected Behavior

The pipeline should either continue from the self-mutate step or stop and be triggered to restart as part of the pipeline

### Current Behavior

The entire pipeline gets run twice.

### Reproduction Steps

Create a cdk pipeline.

Update the stack which hosts the pipeline to add a tag.

### Possible Solution

Before triggering a restart or a new execution when the self-mutate sees a change happened, it should explicitly cancel the current execution.

### CDK CLI Version

2.44.0

### Node.js Version

16.13.1

### OS

Mac

### Language

Typescript

**Comment by rix0rrr** [comment]
Unfortunately this is all CodePipeline behavior, and not something CDK can do anything about. I can report the issue upstream, but that's about it.

**Comment by rix0rrr** [comment]
Hmm. In the process of trying to replicate this to report it upstream I find it doesn't reproduce. Or at least not trivially. The following pipeline tags itself while it's running, but it doesn't restart:

```ts
import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as cp from 'aws-cdk-lib/aws-codepipeline';
import * as cpa from 'aws-cdk-lib/aws-codepipeline-actions';
import * as cb from 'aws-cdk-lib/aws-codebuild';
import { Asset } from 'aws-cdk-lib/aws-s3-assets';
import { PolicyStatement } from 'aws-cdk-lib/aws-iam';

export class TestpipeStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const pipelineName = 'TestTaggingPipeline';
    const pipelineArn = this.formatArn({
      service: 'codepipeline',
      resource: pipelineName,
    });

    const source = new cp.Artifact();

    const asset = new Asset(this, 'Asset', {
      path: __dirname,
    });

    const taggingProject = new cb.PipelineProject(this, 'TaggingProject', {
      environment: {
        buildImage: cb.LinuxBuildImage.STANDARD_6_0,
      },
      buildSpec: cb.BuildSpec.fromObject({
        version: '0.2',
        phases: {
          build: {
            commands: [`aws codepipeline tag-resource --resource-arn ${pipelineArn} --tags "key=SomeTag,value=$(date)"`],
          }
        }
      }),
    });
    taggingProject.role?.addToPrincipalPolicy(new PolicyStatement({
      actions: ['codepipeline:TagResource'],
      resources: ['*'],
    }));

    // The code that defines your stack goes here
    const pipe = new cp.Pipeline(this, 'MyPipeline', {
      pipelineName,
      restartExecutionOnUpdate: true,
      stages: [
        {
          stageName: 'Source',
          actions: [
            new cpa.S3SourceAction({
              actionName: 'Source',
              bucket: asset.bucket,
              bucketKey: asset.s3ObjectKey,
              output: source,
            }),
          ],
        },
        {
          stageName: 'Build',
          actions: [
            new cpa.CodeBuildAction({
              actionName: 'TaggingProject',
              input: source,
              project: taggingProject,
            }),
          ],
        },
        {
          stageName: 'Post',
          actions: [
            new cpa.CodeBuildAction({
              actionName: 'SomethingElse',
              input: source,
              project: new cb.PipelineProject(this, 'AfterProject', {
                environment: {
                  buildImage: cb.LinuxBuildImage.STANDARD_6_0,
                },
                buildSpec: cb.BuildSpec.fromObject({
                  version: '0.2',
                  phases: {
                    build: {
                      commands: [`echo This should run only the 2nd time.`],
                    }
                  }
                }),
              }),
            }),
          ],
        },
      ],
    });
  }
}
```

**Comment by rix0rrr** [comment]
If you find this happening again, can you give us a sense of the diff that caused this behavior?

**Comment by rix0rrr** [comment]
Aha I found the culprit. It is the CloudFormation resource handler for `AWS::CodePipeline::Pipeline` that triggers a `StartPipelineExecution` whenever *anything* about the pipeline changes, even if it it doesn't change the structure.

Cut a ticket to that team, internal reference D59490531.

Nothing else for us to do here unfortunately.

**Comment by ahammond** [comment]
Thank you @rix0rrr !!!

**Comment by rix0rrr** [comment]
Reported this to the CloudFormation team. They said it's expected behavior. Pipelines are restarted on **any** change, including description and tags. This is intentional. Nothing we can do, unfortunately.
