### ISSUE TITLE
aws_s3_deployment module: Prune set to false, but deletes destination contents upon source content changes.

### ISSUE THREAD

**Issue by kushalmehta13** [aws/aws-cdk#22401]
### Describe the bug

According to the [documentation](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_s3_deployment-readme.html#prune) - By default, files in the destination bucket that don't exist in the source will be deleted when the BucketDeployment resource is created or updated. You can use the option prune: false to disable this behavior, in which case the files will not be deleted.

```
declare const destinationBucket: s3.Bucket;
new s3deploy.BucketDeployment(this, 'DeployMeWithoutDeletingFilesOnDestination', {
  sources: [s3deploy.Source.asset(path.join(__dirname, 'my-website'))],
  destinationBucket,
  prune: false,
});
```

However, if source is updated to add new files or change existing file names, then all the contents of the destination get deleted and is replaced with only source files.

### Expected Behavior

Upon changing the contents of the Source at any time, the destination bucket contents should not be deleted when `prune: false`. The following is the expected behavior

Destination:
```
Folder1/File1.txt
Folder1/File2.txt
```
Source changed to:
```
Folder1/newFile.txt
```

run `cdk deploy`

Destination should have:
```
Folder1/File1.txt
Folder1/File2.txt
Folder1/newFile.txt
```

### Current Behavior

**Scenario 1: Working Case**  :white_check_mark:
Destination bucket contains the following
```
Folder1/File1.txt
Folder1/File2.txt
```
Source contains the following
```
Folder1/File1.txt
```

Upon `cdk deploy`, the destination contains the following 
```
Folder1/File1.txt
Folder1/File2.txt
```

**Scenario 2: Buggy** :x:
Consider the same contents in the destination as above. But the source is now changed

Source now contains the following:
```
Folder1/newFile.txt
```

Upon `cdk deploy`, the destination contains the following
```
Folder1/newFile.txt
```

The older files have magically disappeared!

### Reproduction Steps

1. Deploy the source contents
2. Add some files into the destination after deployment
3. Modify the source contents
4. Deploy the source contents
5. Check if files added in step 2 are still present.

### CDK CLI Version

2.14.0

### Node.js Version

14.x

### OS

MacOS

### Language

Typescript

**Comment by peterwoodworth** [comment]
I wasn't able to reproduce this @kushalmehta13, here were the steps I took:

1. Create new bucket in S3 console. Populate with `File1.txt` and `File2.txt`
2. Create CDK app. Import bucket created from S3 console. Set this bucket to be the destination bucket. Source contains modified `File1.txt`
3. Deploy this app. Destination bucket now contains both modified `File1.txt` and `File2.txt`
4. Adjust source to only contain `Newfile.txt`. Deploy
5. Destination bucket now contains `Newfile.txt`, `File1.txt`, and `File2.txt`.

However on step 5 I would have expected based on this bug report for the original two files to have disappeared. Is there something I missed here or are there any other variables that might be at play?
