### ISSUE TITLE
CloudTrail: isOrganizationTrail does not exist in type "TrailProps"

### ISSUE THREAD

**Issue by ratkorle** [aws/aws-cdk#22412]
Hi,
I wanted to create a trail for the whole organisation and I saw that this is possible in the documentation but on cdk synth this fails.
I am using AWS-CDK 2.45.0 and this is my Constructor

```
import { Construct } from "constructs";
import * as cloudtrail from "aws-cdk-lib/aws-cloudtrail";
import * as logs from "aws-cdk-lib/aws-logs";

export class Trails extends Construct {
  public readonly organisationTrail: cloudtrail.Trail;

  constructor(scope: Construct, id: string, props?: any) {
    super(scope, id);

    const { logGroups, buckets } = props;

    this.organisationTrail = new cloudtrail.Trail(this, "organisationTrail", {
      trailName: `my-organisation-trail`,
      isMultiRegionTrail: true,
      isOrganizationTrail: true,
      sendToCloudWatchLogs: true,
      enableFileValidation: true,
      cloudWatchLogGroup: logGroups.cloudTrailOrganisationLogGroup,
      cloudWatchLogsRetention: logs.RetentionDays.FOUR_MONTHS,
      bucket: buckets.logsBucket,
    });
  }
}
```

But this is the error I am getting:
<img width="1484" alt="image" src="https://user-images.githubusercontent.com/33107251/194523533-36648471-f03f-49da-a282-65637b4cccd8.png">

This is how is documented in the documentation:
<img width="1484" alt="image" src="https://user-images.githubusercontent.com/33107251/194523731-e60ed3df-ddc7-41c1-8927-29dfd76f546d.png">

Please give us update when this option is available in the new cdk versions

### Links

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_cloudtrail.Trail.html#isorganizationtrail

**Comment by indrora** [comment]
Please verify that all your runtime dependency libraries are also up to date. This change was added in https://github.com/aws/aws-cdk/commit/f5a10574308b9193cba32d398a08fe61b5d15aa3

Please list the versions of your runtime and cdk libraries that you're using.
