### ISSUE TITLE
apigatewayv2: can't rename API Gateway instance attached to domainName

### ISSUE THREAD

**Issue by alexandervandekleutab** [aws/aws-cdk#22416]
### Describe the bug

When creating an API Gateway instance with a domain mapping to a custom domain, you cannot rename the API gateway instance. The main problem is that it tries to create the new API gateway instance and domain mapping at the (currently used) path before deleting the old one, leading to a conflict.

### Expected Behavior

The old API and domain name mapping should get deleted first (along with the path mapping) and **then** the new one can be created, avoiding the conflict.

### Current Behavior

Instead, it **first** tries to create the new API gateway with attachment to the (currently used) domain name at the same `pathMapping`. 

### Reproduction Steps

Here is a basic example of a Stack constructor body:

```typescript
    super(scope, id, props)
    this.environmentName = environmentName
    this.baseStackName = baseStackName

    const certificate: acm.ICertificate = this.getCertificate()
    const hostedZone: route53.IHostedZone = this.getHostedZone()
    const subdomain = 'custom-domain-api'
    const domainName = `${subdomain}.${hostedZone.zoneName}`

    const apiDomainName = new apigw.DomainName(this, 'DomainName', {
      domainName: domainName,
      certificate: certificate,
    })

    const apiName = 'CustomDomainApi'
    const api = new apigw.HttpApi(this, apiName, {
      defaultDomainMapping: {
        domainName: apiDomainName,
      },
    })
```

Deploy a stack with this body. Then, change the `apiName` to be something like `NewCustomDomainApi`. This will prompt the deletion of the old API and domain mapping, and the creation of the new API and domain mapping. `cdk diff` shows as much.

However, when deploying, first it tries to create the new `HttpApi` and `domainMapping`, which leads to the conflict.

### Possible Solution

I can somewhat get around this adding a `pathMapping` like `temp` to the `defaultDomainMapping`. Deploy, thus removing the old path mapping and creating a new one for the new API. Then, remove the `pathMapping` and re-deploy. 

The main problem with this is that it induces downtime and I have some APIs defined on large stacks that take upwards of 20 minutes to deploy. This would cause downtime on all of those APIs.

### Additional Information/Context

This might be a cloudformation bug. Is there any way to tell it to destroy resources before creating new ones?

### CDK CLI Version

1.124.0

### Framework Version

1.144.0

### Node.js Version

14.7.0

### OS

MacOS

### Language

Typescript

**Comment by peterwoodworth** [comment]
This is how CloudFormation handles it when [replacing resources.](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html) Not much we can really do about it unfortunately, though cases exactly like this where just the name is changed is a documented problem and the suggested workaround is to delete and recreate the stack. 

Apologies for not being able to provide a better answer for you
