### ISSUE TITLE
AWS IoT Core: Enable Fleet Indexing through CDK

### ISSUE THREAD

**Issue by ssasoglu** [aws/aws-cdk#22415]
### Describe the feature

Currently there is no way to enable IoT Fleet Indexing through CDK. (if there is a way and we missed it, please feel free to redirect us to the documentation). It is possible to create Fleet Metrics using `CfnFleetMetric`, but a deployment would fail if indexing is not enabled.

### Use Case

All our infrastructure is defined as code with CDK. Not having the option to enable IoT Fleet Indexing forces us to workarounds like executing cli commands on pipeline or creating custom resources (enabling IoT Fleet Indexing requires a complex code under the hood where you need to create dependencies between API calls and wait for them to succeed).

Having this functionality would greatly help reduce complexity.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.23.0

### Environment details (OS name and version, etc.)

Linux

**Comment by indrora** [comment]
Since CloudFormation doesn't support this action natively, and instead depends on an AWS SDK call afterwards, the best that the CDK can do is a Custom Resource. 

Custom resources are lambda functions that run on your behalf as part of the AWS CDK deployment stage. A custom resource isn't bound to limitations of CloudFormation, only of what the deployment role is able to do.

**Comment by alan-alvarenga-telus** [comment]
Snippet to enable fleet indexing through customer resource. 

```ts
   const role = new Role(this, "iot-fleet-indexer", {
      roleName: "iot-fleet-indexer",
      assumedBy: new ServicePrincipal('lambda.amazonaws.com'),
    });

    const policy = new ManagedPolicy(this, "fleet-indexer-policy", {
      roles: [role],
      managedPolicyName: "ota-fleet-indexer-policy",
      statements: [
        new PolicyStatement({
          actions: ["iot:*"],
          resources: ["*"]
        })
      ],
    })
   // read https://docs.aws.amazon.com/iot/latest/developerguide/managing-index.html#enable-index
    const fleetIndexing = new AwsCustomResource(this, "fleet-indexing-resource", {
      onCreate: {
        service: "@aws-sdk/client-iot",
        action: "UpdateIndexingConfigurationCommand",
        parameters: {
          "thingIndexingConfiguration": {
            "thingIndexingMode": "REGISTRY",
          }
        },
        physicalResourceId: PhysicalResourceId.of("fleet-indexing-resource"),
      },
      role: role,
    })

```
