### ISSUE TITLE
How to bind apigateway as AliasRecordTarget to Route53

### ISSUE THREAD

**Issue by yuanchieh-cheng** [aws/aws-cdk#2243]
version: 0.28.0

Hi there, 

I am trying to add target of AliasRecord pointing to Apigateway.  
But I cannot found any Apigateway method to support asAliasRecordTarget interface.  

Anyway to do this ?

Thanks

**Comment by yamatatsu** [comment]
I used gluecodes like this:
```ts
const apiDomainName = new apigateway.CfnDomainName(/* params */)

new route53.AliasRecord(this, 'MyRoute53', {
  zone,
  recordName: 'foo.example.com',
  target: {
    bind: () => ({
      hostedZoneId: apiDomainName.domainNameDistributionHostedZoneId,
      dnsName: apiDomainName.domainNameDistributionDomainName,
    }),
  },
})
```

In v0.33.0, apigataway Custom Domain without 'Cfn' prefix has not implemented.
I guess that become smooth if it is implemented.

**Comment by eladb** [comment]
Working on it

**Comment by nija-at** [comment]
I believe the [custom domains feature](https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/aws-apigateway#custom-domains) satisfied this ask.

Please re-open if you think there's something amiss.
