### ISSUE TITLE
monocdk/aws_s3_deployment: fails to deploy s3 configuration when objects aren't already present

### ISSUE THREAD

**Issue by huiepatr** [aws/aws-cdk#22461]
### Describe the bug

`aws_s3_deployment` fails to deploy source assets to the specified bucket when the bucket is empty.

### Expected Behavior

Successful deployment of source assets to the specified s3 bucket

### Current Behavior

Deploy the stack with the deployment resource - it will fail with:
    
```
   10:02:18 AM | CREATE_FAILED        | AWS::Lambda::LayerVersion   | DeployConfigAwsCliLayer82EC2BC1
Error occurred while GetObject. S3 Error Code: NoSuchKey. S3 Error Message: The specified key does not exist. (Service: AWSLambdaInte
rnal; Status Code: 400; Error Code: InvalidParameterValueException
```
    

If you import `aws_s3_deployment` from `aws-cdk-lib`, and perform the same actions, the deployment is successful .

### Reproduction Steps

In one stack, create an s3 bucket:
```
        const s3LambdaConfigBucket = new s3.CfnBucket(this, 'BucketThree', {
            versioningConfiguration: {
                status: "Enabled"
            },
            bucketName: `sample-bucket-name`,
        });
```

In another stack, create the deployment resource:

```
import { aws_s3_deployment as s3deploy } from 'monocdk';

        const importedConfigBucket = s3.Bucket.fromBucketName(this,
            'imported-bucket-from-name',
            'sample-bucket-name')

        const bucketDeployment = new s3deploy.BucketDeployment(this, 'DeployConfig', {
            sources: [s3deploy.Source.asset('./configuration/')],
            destinationBucket: importedConfigBucket,
            destinationKeyPrefix: 'global'
        });

```

Deploy the stack with the deployment resource - it will fail with the error above.

### Possible Solution

A `GetObject` call is happening that should not in the case the bucket is empty (I'd argue this call should not happen in any case - you can call `PutObject` without checking for the state of any objects in the bucket). 

### CDK CLI Version

2.43.1

### Node.js Version

v14.5.0

### OS

MacOS

### Language

Typescript

### Language Version

TypeScript (4.0.5)

### Other information

Monocdk version 1.128.0

**Comment by peterwoodworth** [comment]
I wasn't able to reproduce this, this is a pretty common use case so I think something else might have caused this for you. Our BucketDeployment handler doesn't make any GetObject calls.

Let me know if you have any other information, thanks!
