### ISSUE TITLE
(aws-iam): Cannot add managed policy to imported User

### ISSUE THREAD

**Issue by ozeebee** [aws/aws-cdk#22482]
### Describe the bug

I want to attach a managed policy to an imported (existing) IAM user.
CDK throws an error during synthesis with message: `Cannot add managed policy to imported User`.
I can attach an inline policy but it looks like it's not implemented for managed policies: https://github.com/aws/aws-cdk/blob/74318c7d22bfc00de9e005f68a0a6aaa58c7db39/packages/%40aws-cdk/aws-iam/lib/user.ts#L222

Any reasons for this ?
Is it a bug, not feasible or simply not implemeted yet ;) ?

### Expected Behavior

The managed policy is attached to the imported user.

### Current Behavior

CDK throws an error: `Cannot add managed policy to imported User`

### Reproduction Steps

```typescript
const iamUser = iam.User.fromUserName(this, 'MyUser', 'myuser')
iamUser.addManagedPolicy(iam.ManagedPolicy.fromAwsManagedPolicyName('AmazonEC2FullAccess'))
```

### CDK CLI Version

2.45.0 (build af1fb7c)

### Node.js Version

v16.17.0

### OS

macOS 12.6

### Language

Typescript

### Language Version

4.8.4

**Comment by peterwoodworth** [comment]
We don't do this intentionally. Imported resources are just proxies and so they don't have an underlying CloudFormation resource. This means CDK cannot alter the resource like you can most resources by modifying its properties on the underlying CloudFormation resource. The only way to specify a ManagedPolicy on a user in CloudFormation is to specify it on the user, with no way to reference the user to attach when creating a ManagedPolicy. So this means we can only add a managed policy to a User if we have the real User which has control over the CfnUser. See [this page](https://docs.aws.amazon.com/cdk/v2/guide/resources.html#resources_referencing) for more information on importing resources.

You could still achieve this with CDK however, with a Custom Resource!. Use [AwsCustomResource](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.custom_resources.AwsCustomResource.html) and specify Iam [AttachUserPolicy](https://docs.aws.amazon.com/IAM/latest/APIReference/API_AttachUserPolicy.html) as your Api call and you can attach a managed policy to your user with CDK 🙂

**Comment by xgt001** [comment]
@ozeebee as a workaround, you can create a group, attach the policies to the group and lastly add your imported user to this group. This works
