### ISSUE TITLE
(ci): (set-output in Github Actions to be deprecated)

### ISSUE THREAD

**Issue by k1rnt** [aws/aws-cdk#22483]
### Describe the feature

replace deprecated set-output command with GITHUB_OUTPUT

### Use Case

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
As per this URL, set-output of Github Actions is deprecated.

### Proposed Solution

`echo "::set-output name=dir::$(yarn cache dir)"`
replace to
`echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT`

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.45.0

### Environment details (OS name and version, etc.)

macOS 12.4

**Comment by peterwoodworth** [comment]
this has been addressed, thanks for the report!
