### ISSUE TITLE
docs(servicecatalogappregistry): ApplicationAssociator requires either applicationName or applicationArnValue

### ISSUE THREAD

**Issue by alexpulver** [aws/aws-cdk#22486]
### Describe the issue

`applicationName` construct prop for `Application` and `ApplicationAssociator` constructs appears as optional in docs. When synthesizing the stack, AWS CDK shows the following error:
> Please provide either ARN or application name.

Example code snippet that caused the error (Python):
```python
appregistry_application = appregistry_alpha.ApplicationAssociator(
    app,
    constants.APP_NAME + "Application",
    stack_props=cdk.StackProps(
        stack_name=constants.APP_NAME + "Application",
        env=cdk.Environment(account="123456789012", region="eu-west-1")
    )
)
```

### Links

https://docs.aws.amazon.com/cdk/api/v2/docs/@aws-cdk_aws-servicecatalogappregistry-alpha.Application.html#applicationnamespan-classapi-icon-api-icon-experimental-titlethis-api-element-is-experimental-it-may-change-without-noticespan

https://docs.aws.amazon.com/cdk/api/v2/docs/@aws-cdk_aws-servicecatalogappregistry-alpha.ApplicationAssociator.html#applicationnamespan-classapi-icon-api-icon-experimental-titlethis-api-element-is-experimental-it-may-change-without-noticespan

**Comment by kaizencc** [comment]
Looks like we need to add in a synth-time check for this error, to make sure that an arn or application name exists. OR, we should be creating an application name for the user if none is specified.

**Comment by alexpulver** [comment]
I saw the former approach elsewhere in CDK, and I think it is more explicit and easier to grasp. I can't recall the construct that followed that approach, but what they did is document having either in the parameter documentation. So each parameter still appears as optional, but the documentation for each parameter is very explicit on this.

**Comment by jcbmarqz** [comment]
This seems to be the expected behavior.

`applicationName` is required for the `Application` construct and that's consistent with the API [create-application](https://docs.aws.amazon.com/cli/latest/reference/servicecatalog-appregistry/create-application.html)

`applicationName` is optional in the `ApplicationAssociator` because you can either provide the `The name or ID of the application` according to the [associate-resource docs](https://docs.aws.amazon.com/cli/latest/reference/servicecatalog-appregistry/associate-resource.html). So the `ApplicationAssociator` is not requiring one in particular but it's validating at least 1 is provided [here](https://github.com/aws/aws-cdk/blob/v2.49.1/packages/@aws-cdk/aws-servicecatalogappregistry/lib/application-associator.ts#L61-L70)

**Comment by alexpulver** [comment]
This is indeed the expected behavior. My ask is (sorry that I didn't clarify that) to document this in each of the [ApplicationAssociator](https://docs.aws.amazon.com/cdk/api/v2/docs/@aws-cdk_aws-servicecatalogappregistry-alpha.ApplicationAssociator.html) `applicationArnValue` and `applicationName` props. See [aws_efs.FileSystemAttributes](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_efs.FileSystemAttributes.html) as an example of this.

**Comment by alexpulver** [comment]
Also, what do you think about shortening the prop name for the application ARN to `applicationArn`? It seems to be the approach in other AWS CDK modules (see `FileSystemAttributes` above + [aws_certificatemanager.Certificate](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_certificatemanager.Certificate.html#static-fromwbrcertificatewbrarnscope-id-certificatearn))

**Comment by santanugho** [comment]
Starting `vv2.5540-alpha.0`, we have changed the `ApplicationAssociator` construct to accept input from a factory implementation.

For customers who wants to create a new application and need to supply `applicationName` can now use `TargetApplication.createApplicationStack` for which `applicationName` is mandatory.

For customers who wants to import an existing application can now use `TargetApplication.existingApplicationFromArn` for which `applicationArnValue` is mandatory.

[Documentation](https://github.com/aws/aws-cdk/tree/main/packages/%40aws-cdk/aws-servicecatalogappregistry) has been update accordingly.
Please do let us know your feedback on this approach.

**Comment by santanugho** [comment]
As discussed, the following message in the [construct definition](https://docs.aws.amazon.com/cdk/api/v2/docs/@aws-cdk_aws-servicecatalogappregistry-alpha.ApplicationAssociator.html) needs to be clear by mentioning that the name uniqueness is enforced at the account level **per region**.

```
The application name must be unique at the account level and it's immutable
```

**Comment by alexpulver** [comment]
Thanks @santanugho! These changes should address this issue.
