### ISSUE TITLE
(aws-iot): Add a custom resource to provide iot endpoints

### ISSUE THREAD

**Issue by Pearcekieser** [aws/aws-cdk#22498]
### Describe the feature

I would like to add an L2 (L2.5) resource that will make IoT endpoint strings for a given account available via CDK.  The TPS limits for the [IoT DescribeEndpoint API](https://docs.aws.amazon.com/iot/latest/apireference/API_DescribeEndpoint.html#API_DescribeEndpoint_RequestSyntax) make it so I cannot dynamically look up the endpoint on lambda init.  I need to hard code the API for every AWS account I use, which is a bit of a pain.  

I'd like to add a 'Resource' to CDK that preforms that lookup once and allow me to use its result while configuring my lambda environment variables etc.

I already have a [sample implementation of this using AwsCustomResource](https://github.com/aws/aws-cdk/commit/6636d1b701e6801456e85f0406f516bcf18bcfc7).  But I wanted to check in to make sure this is something your interested in accepting before spending more time on it.

### Use Case

I use AWS IoT with Lambda in a code pipeline that deploys across many aws accounts.  My lambda's need to know the IoT endpoint to communicate.  

Right now I hard code this value in code and provide it as an environment variable to my lambda in my CDK configuration.  I have tried using the IoT API to look up the endpoint during lambda init but we ran into throttling issues because that API has a hard limit of 10TPS [ref](https://docs.aws.amazon.com/general/latest/gr/iot-core.html).  

I'd prefer to have this endpoint information resolved as part of the cloud formation process, so I don't have to look up and hard code the endpoint for every new account we use.

### Proposed Solution

Searching around our team found https://stackoverflow.com/a/65591581/11799646 which fit our needs nicely.  

```
const getIoTEndpoint = new customResource.AwsCustomResource(this, 'IoTEndpoint', {
            onCreate: {
              service: 'Iot',
              action: 'describeEndpoint',
              physicalResourceId: customResource.PhysicalResourceId.fromResponse('endpointAddress'),
              parameters: {
                "endpointType": "iot:Data-ATS"
              }
            },
            policy: customResource.AwsCustomResourcePolicy.fromSdkCalls({resources: customResource.AwsCustomResourcePolicy.ANY_RESOURCE})
          });

const IOT_ENDPOINT = getIoTEndpoint.getResponseField('endpointAddress')
```

I'd like to get a solution like into `@aws-cdk/aws-iot` so it can be more accessible to our customers. 

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

main

### Environment details (OS name and version, etc.)

macOS 12.5

**Comment by indrora** [comment]
This sort of contribution would be best served by being a module in the Construct Hub before it was introduced directly into the CDK. 

I'm closing this as "not planned... _for now_" -- Again, I would encourage you to flesh out the higher level API and structure in an independent construct first, then see if it would work well being integrated into the CDK proper.
