### ISSUE TITLE
Missing license in child dependency cli-color

### ISSUE THREAD

**Issue by kbradl16** [aws/aws-cdk#2249]
[json-diff](https://github.com/andreyvit/json-diff/blob/master/package.json#L21) dependency uses cli-color (0.1.7) which does not have a license. Remediate missing license or switch dependencies.

**Comment by sam-goodwin** [comment]
According to its [npm](https://www.npmjs.com/package/cli-color) and [github](https://github.com/medikoo/cli-color) pages, it uses the [ISC License](https://opensource.org/licenses/ISC)

**Comment by kbradl16** [comment]
While I do see that the npm and github pages do include a license, we have to look at the version being used. The license was added after the current version being used. The ISC license was added on Aug 20, 2018; previously it was MIT from Feb 21, 2017; and copyright? license from Nov 24, 2014. 

The version being used (0.1.7) was last updated 7 years ago which would put the time around 2012. So I do not think any of the license(s) apply.

**Comment by NGL321** [comment]
It looks like every version of cli-color since inception was licensed with the ISC license and every version of json-diff uses the MIT license.

Closing out this issue

**Comment by kbradl16** [comment]
@NGL321 I don't think you've done proper due diligence on this issue. Please look into it more closely. It 100% has not been licensed correctly from inception. The version being used contains no license... 

If you look at this link: https://github.com/medikoo/cli-color/blob/ebeb2e81a0c984047a71c392cf81897e34ad5b8a/package.json you will not see any license in the repo at this node version (0.1.7) of "cli-color" package. As stated in my previous comment.
