### ISSUE TITLE
ECS Cluster ASG drain hook uses python 3.6 runtime which will not be supported by AWS soon.

### ISSUE THREAD

**Issue by indrora** [aws/aws-cdk#22490]
### Discussed in https://github.com/aws/aws-cdk/discussions/20194

<div type='discussions-op-text'>

<sup>Originally posted by **baraksalomon** May  3, 2022</sup>
Hello,

The Lambda created as part of the drain hook for ECS ASG uses python 3.6 runtime:
https://github.com/aws/aws-cdk/blob/v1.154.0/packages/@aws-cdk/aws-ecs/lib/drain-hook/instance-drain-hook.ts
is there a plan to change it to a supported python runtime version?

Thanks,
       Barak.</div>

**Comment by pallymore** [comment]
Looks like this has been updated to 3.9 recently https://github.com/aws/aws-cdk/commit/c8f5cd24c3b52b55eea1b19e71bdc1b8eae68627 

could you try to update your AWS CDK packages?

**Comment by pahud** [comment]
Yes it has. https://github.com/aws/aws-cdk/blob/42160fc2e5532acfb6b97652f6ad0e3354b32baa/packages/%40aws-cdk/aws-ecs/lib/drain-hook/instance-drain-hook.ts#L66

**Comment by baraksalomon** [comment]
I asked the question in May, it was already resolved in June.
Thanks for looking into it.

**Comment by peterwoodworth** [comment]
Resolved, closing
