### ISSUE TITLE
(aws_s3_deployment): (unexpected keyword argument 'extract')

### ISSUE THREAD

**Issue by udochief007** [aws/aws-cdk#22511]
### Describe the bug

when using the extract=False parameter to keep uploaded files zipped, i get the following error 
unexpected keyword argument 'extract'

### Expected Behavior

keep files zipped post upload 

### Current Behavior

(.env) test@IT-test-D9N4 cdk % cdk ls -c env=app    
/Users/test/github/drift-notify/cdk/cdk.out/DriftNotifyStack.template.json
Traceback (most recent call last):
  File "/Users/test/github/drift-notify/cdk/app.py", line 12, in <module>
    StackSet(app, "stack-set-DriftNotifyStack", env=aws_env, synthesizer=cdk.DefaultStackSynthesizer(generate_bootstrap_version_rule=False))
  File "/Users/test/github/drift-notify/cdk/.env/lib/python3.10/site-packages/jsii/_runtime.py", line 100, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/test/github/drift-notify/cdk/drift_notify/stack_set.py", line 84, in __init__
    deployment.BucketDeployment(self, "upload zip to s3",
  File "/Users/test/github/drift-notify/cdk/.env/lib/python3.10/site-packages/jsii/_runtime.py", line 100, in __call__
    inst = super().__call__(*args, **kwargs)
TypeError: BucketDeployment.__init__() got an unexpected keyword argument 'extract'

### Reproduction Steps

        deployment.BucketDeployment(self, "upload zip to s3",
            sources=[deployment.Source.asset(f"{base_path}/lambda/send-drift-email/send-drift-email.zip")],
            destination_bucket=bucket,
            prune=False,
        )

### CDK CLI Version

2.45.0 (build af1fb7c)

### Node.js Version

v16.15.1

### OS

mac

### Language

Python

### Language Version

3.10.5

**Comment by UlaJiang** [comment]
I can replicate the same in my account. internal SIM cut also (P73475531)

CDK CLI Version: 2.39.1 (build f188fac)
OS: Cloud9 - Amazon Linux 2 (recommended) - t2.micro (1 GiB RAM + 1 vCPU)
Language (Version): Python 3.7.10
==========================
CDK code replicate on my end:
==========================
------------------------------------------------------------------------------------------------------------------
from constructs import Construct
from aws_cdk import (
    Duration,
    Stack,
    aws_s3_deployment as deployment,
    aws_s3 as s3
)

class CdkWorkshopStack(Stack):
    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)
        
        website_bucket = s3.Bucket(self, "WebsiteBucket",
            website_index_document="index.html",
            public_read_access=False
        )
        deployment.BucketDeployment(self, "upload zip to s3",
            sources=[deployment.Source.asset(f"./sample-test-linux-restart.yml.zip ")],
            destination_bucket=website_bucket,
            prune=False,
            extract=False   <<<--- without this line, I can deploy the stack successfully , with this line, I will get below error when doing 'cdk ls' or 'cdk deploy' or 'cdk synth'
        )
------------------------------------------------------------------------------------------------------------------

==========================
'cdk deploy' error message:
==========================
------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "app.py ", line 9, in <module>
    CdkWorkshopStack(app, "cdk-workshop")
  File "/home/ec2-user/environment/cdk_workshop/.venv/lib64/python3.7/site-packages/jsii/_runtime.py", line 86, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/home/ec2-user/environment/cdk_workshop/cdk_workshop/cdk_workshop_stack.py", line 25, in __init__
    extract=False
  File "/home/ec2-user/environment/cdk_workshop/.venv/lib64/python3.7/site-packages/jsii/_runtime.py", line 86, in __call__
    inst = super().__call__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'extract'
------------------------------------------------------------------------------------------------------------------

Can you please help us check if there is something we missed when using 'extract'?  Thanks

**Comment by peterwoodworth** [comment]
I can't reproduce this @udochief007. Please ensure you've actually installed the latest node packages to your CDK project since `v2.44.0` as that is when we released this feature. Thanks!

**Comment by udochief007** [comment]
@peterwoodworth did you use the extract=False parameter ?
