### ISSUE TITLE
Appsync Lambda Go: failed: Error: The stack named Example-Stack failed to deploy: UPDATE_ROLLBACK_COMPLETE: No data source found named graphql-go-function (Service: AWSAppSync; Status Code: 404; Error Code: NotFoundException;

### ISSUE THREAD

**Issue by ThomasP1988** [aws/aws-cdk#22517]
### Describe the bug

When trying to deploy an appsync api with a lambda as a resolver, it tells me that its not found.

 failed: Error: The stack named Example-Stack failed to deploy: UPDATE_ROLLBACK_COMPLETE: No data source found named graphql-go-function (Service: AWSAppSync; Status Code: 404; Error Code: NotFoundException;

### Expected Behavior

create appsync with lambda function as resolver

### Current Behavior

error message

 failed: Error: The stack named Example-Stack failed to deploy: UPDATE_ROLLBACK_COMPLETE: No data source found named graphql-go-function (Service: AWSAppSync; Status Code: 404; Error Code: NotFoundException;

### Reproduction Steps

Packages i use for it:
	github.com/aws/aws-cdk-go/awscdk/v2 v2.46.0
	github.com/aws/aws-cdk-go/awscdkappsyncalpha/v2 v2.46.0-alpha.0
	github.com/aws/aws-cdk-go/awscdklambdagoalpha/v2 v2.46.0-alpha.0
	

```
lambda := awscdklambdagoalpha.NewGoFunction(stack, jsii.String("lambda-GraphQL"), &awscdklambdagoalpha.GoFunctionProps{
		Entry: jsii.String("../../lambda/appsync"),
		InitialPolicy: &[]awsiam.PolicyStatement{
			awsiam.NewPolicyStatement(&awsiam.PolicyStatementProps{
				Effect: awsiam.Effect_ALLOW,
				Actions: jsii.Strings(
					"logs:*",
					"cognito-idp:AdminGetUser",
				),
				Resources: jsii.Strings("*"),
			}),
		},
		Environment: &map[string]*string{
			"stage": jsii.String(string(stage)),
		},
	})
```

and adding it that way

`lambdaSource := (*api).AddLambdaDataSource(jsii.String("graphql-go-function"), lambda, &awscdkappsyncalpha.DataSourceOptions{})`

### Possible Solution

 i downgraded to 2.45 (go and typescript) and I dont have the problem anymore.

### CDK CLI Version

2.45.0 (build af1fb7c)

### Node.js Version

v18.9.0

### OS

macos

### Language

Go

### Language Version

1.19.1

**Comment by peterwoodworth** [comment]
We introduced a change in `2.46` which changes how we're supplying the physical name https://github.com/aws/aws-cdk/pull/22378/files

This means when upgrading you're running into the issues related to the topics [here](https://docs.aws.amazon.com/cdk/v2/guide/resources.html#resources_physical_names) and [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-name.html), please read through these docs to understand why you're running into this error and how to get out of it. Thanks!

> Assigning physical names to resources has some disadvantages in AWS CloudFormation. Most importantly, any changes to deployed resources that require a resource replacement, such as changes to a resource's properties that are immutable after creation, will fail if a resource has a physical name assigned. If you end up in that state, the only solution is to delete the AWS CloudFormation stack, then deploy the AWS CDK app again

This is an alpha module so breaking changes like these are to be expected from time to time. As a result, this isn't something that needs fixing on our end.
