### ISSUE TITLE
(aws-cloudwatch): GraphWidget.to_json returns tokenised Json 

### ISSUE THREAD

**Issue by rahuldeverani** [aws/aws-cdk#22514]
### Describe the issue

cloudwatch GraphWidget.to_json() returns Json that cannot be used directly with SDK to put dashboard body to dashboard. 

Steps to reproduce:

    metric_1 = cloudwatch.Metric(
                       metric_name="metric-1", namespace="my-metrics"
                   )
    
    widget = cloudwatch.GraphWidget(
                       left=[
                           metric_1
                       ],
                       period=core.Duration.minutes(1),
                       title="My Widgets"
                   )
     print(widget.to_json())

[{'type': 'metric', 'width': 6, 'height': 6, 'properties': {'view': 'timeSeries', 'title': 'My Widgets', 'region': '${Token[AWS.Region.5]}', 'metrics': [<jsii._reference_map.InterfaceDynamicProxy object at 0x7eff7a893e10>], 'yAxis': {}, 'period': 60}}]

Use case: Dashboard is created in other stack which is not part of current cdk app, and would like to generate Widget Json which could be used with sdk to put the dashboard body for the dashboard which are created in other stacks.

this also does not produce the required Json : self.resolve(widget))(https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/CloudWatch-Dashboard-Body-Structure.html)  :  

Similar issues: 
https://github.com/aws/aws-cdk/issues/5735
https://github.com/aws/aws-cdk/issues/15222

The documentation mentions 'Return the widget JSON for use in the dashboard.' : https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_cloudwatch.GraphWidget.html#towbrjson
 
The above statement gives an idea that JSON can be generated during synth without tokens/references .

### Links

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_cloudwatch.GraphWidget.html#towbrjson

**Comment by indrora** [comment]
You'll need to pass the JSON to a custom resource that adds your dashboard post-deployment. The JSON cannot be fully resolved until the CloudFormation stack has been deployed. 

I would suggest a CloudFormation Output and a post-deployment script.
