### ISSUE TITLE
(aws-s3): S3-Event-Notification Triggers Clash with EventBridge Triggers

### ISSUE THREAD

**Issue by EyeBallin** [aws/aws-cdk#22522]
### Describe the bug

Backstory: We had found that, inconsistently, some of our Lambdas were not having their S3-Event-Notification Triggers being correctly added by the CDK, despite there being seemingly no reason as to why they shouldn't be. An AWS Support ticket was raised, and after confirming that the S3-Event-Notifications could be added manually, we were guided to making an issue report here.

Another test last week showed some different behaviour, however: All Lambdas had their S3-Event-Notification Triggers correctly added, but our EventBridges for the relevant source Buckets were turned off.

### Expected Behavior

S3-Event-Notification Triggers and EventBridge Triggers should be able to co-exist when both pointing to the same source Bucket (but with each of the two Triggers doing different things).

### Current Behavior

The S3-Event-Notifications become inconsistent with regards to whether they correctly attach to their specific Lambdas and Buckets or not.

### Reproduction Steps

Currently there is no direct code or repo that I can provide, but these are the steps we took to test the results:

Test Overview:
1. Disable S3 Lambda Trigger in CDK
2. Deploy & Observe CloudTrail Logs
3. Enable S3 Lambda Trigger in CDK
4. Deploy Again & Observe CloudTrail Logs
5. Check Previously-Existing EventBridge Triggers

Test Details:
1. Disable S3 Lambda Trigger in CDK: `cdk-diff` shows that it will remove S3-Event-Notifications for the 3 Buckets that have been showing this issue.
2. Deploy: S3-Event-Notifications removed, verified in CloudTrail logs in `PutBucketNotification` event type.
3. Enable S3 Lambda Trigger in CDK: `cdk-diff` shows that it will enable S3-Event-Notifications for the 3 Buckets that have been showing this issue.
4. Deploy Again: S3-Event-Notifications added by CDK for all 3 Buckets, verified in CloudTrail logs in `PutBucketNotification` event type.
5: Check Previously-Existing EventBridge Triggers: The EventBridge Triggers previously observable on these Buckets are now disabled.

### Possible Solution

The proposed theory is that the CDK does not support EventBridge Triggers and S3-Event-Notification Triggers at the same time, from the same bucket.

### CDK CLI Version

1.134.0 (build dd5e12d)

### Node.js Version

v16.3.0

### OS

macOS Monterey, v12.6 (21G115)

### Language

Typescript

### Language Version

~4.4.4

**Comment by peterwoodworth** [comment]
Some reproduction code would be really helpful @EyeBallin. It doesn't even have to be working, it can just be pseudocode. It will be really helpful for us debugging and getting to the bottom of this
