### ISSUE TITLE
Amazon EventBridge: Creation of Rule with an existing role is not working

### ISSUE THREAD

**Issue by gizembicer** [aws/aws-cdk#22543]
### Describe the bug

I am trying to create a scheduled event from CDK whose target is an API destination. I want to use an existing role for this target. But when I deploy the CDK, it wants to add a new policy to my existing role even if I the role that I gave has the same policies.

### Expected Behavior

Creation of rule successfully without adding a new policy to the given role

### Current Behavior

when I write cdk synth new template has a part like below:

_Name_ApiDestinationRolePolicy8DD9DCE3:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: events:InvokeApiDestination
            Effect: Allow
            Resource:
              Fn::GetAtt:
                -_Name_DestinationApiDestination3345A56D
                - Arn
        Version: "2012-10-17"
      PolicyName: _Name_ApiDestinationRolePolicy8DD9DCE3
      Roles:
        - EventBridgeApiDestinationRole **_--->(my role which I gave to the target of the rule)_**
    Metadata:
      aws:cdk:path: _Name_/ApiDestinationRole/Policy/Resource

### Reproduction Steps

const apiDestinationRole = Role.fromRoleName(
	this,
	"ApiDestinationRole",
	"roleName",
);

const connection = new Connection(this, "Connection", {
	connectionName: `connectionName`,
	authorization: Authorization.basic(props.username, props.password),
	description: "Connection To Back-End API",
});

const destination = new ApiDestination(this, "Destination", {
	apiDestinationName: `apiDestinationName`,
	connection,
	endpoint: `_URL_`,
	description: "Calling Back-End Service",
});

new Rule(this, "everydayAt00Rule", {
	ruleName: `ruleName`,
	schedule: Schedule.expression("cron(1 0 ? * * *)"),
	targets: [
		new targets.ApiDestination(destination, {
			eventRole: apiDestinationRole,
		}),
	],
});

YAML for creation of role
EventBridgeApiDestinationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: 'EventBridgeApiDestinationRole'
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: events.amazonaws.com
        Version: "2012-10-17"      
  EventBridgeApiDestinationPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: 'EventBridgeApiDestinationPolicy'
      PolicyDocument:
        Statement:
          - Action:
              - events:*
            Effect: Allow
            Resource:
              - !Sub arn:aws:events:*:${AWS::AccountId}:api-destination/*
        Version: "2012-10-17"
      Roles:
        - Ref: EventBridgeApiDestinationRole

### Additional Information/Context

My AWS account is not authorized to add or delete IAM roles or policies so I cannot deploy my stack. I have to use existing roles and policies.

### CDK CLI Version

2.46.0

### Node.js Version

8.1.0

### OS

Windows 10

### Language

Typescript

**Comment by peterwoodworth** [comment]
You can set a role to be immutable (in other words, prevent policies from being added to it) when importing it with the fourth options parameter. See [here](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_iam.FromRoleNameOptions.html#mutable)!

Does this work for you?

**Comment by gizembicer** [comment]
It worked, thank you
