### ISSUE TITLE
codeguruprofiler: Invalid profilingGroupName on resource import

### ISSUE THREAD

**Issue by openwebsolns** [aws/aws-cdk#22546]
### Describe the bug

When importing a ProfilingGroup by either name or ARN, the resulting construct uses the wrong value for profiling group name.

### Expected Behavior

```js
import * as codeguru from "aws-cdk-lib/aws-codeguruprofiler";

const pf = codeguru.ProfilingGroup.fromProfilingGroupName(
  scope,
  "ProfilingGroupId",
  "NameOfProfilingGroup"
);

console.log(pf.profilingGroupName); // "NameOfProfilingGroup"
```

### Current Behavior

Output of above is instead the hard-coded value `profilingGroup`.

### Reproduction Steps

```js
// import * as codeguru from "aws-cdk-lib/aws-codeguruprofiler";

const pf = codeguru.ProfilingGroup.fromProfilingGroupName(
  scope,
  "ProfilingGroupId",
  "NameOfProfilingGroup"
);

console.log(pf.profilingGroupName); // "NameOfProfilingGroup"
```

### Possible Solution

Replace [resource when importing](https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/aws-codeguruprofiler/lib/profiling-group.ts#L157) for `resourceName`.

### CDK CLI Version

2.44.0

### Node.js Version

14.17.0

### OS

Linux

### Language

Typescript

### Language Version

4.8.4

**Comment by mascur** [comment]
Hi @openwebsolns,

Thank you for reporting this issue. I've confirmed that this is an issue and that your proposed solution would likely work. In the meantime I would suggest using [`fromProfilingGroupArn()`](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-codeguruprofiler.ProfilingGroup.html#static-fromwbrprofilingwbrgroupwbrarnscope-id-profilinggrouparn).

I've marked this issue as a `p2`. We most likely won't be able to get to this issue. However, if you or another community member would like to submit a PR we would be able to review that. You can refer to the [Contribution Guide here](https://github.com/aws/aws-cdk/blob/v1-main/CONTRIBUTING.md) to get started.
