### ISSUE TITLE
aws-redshift-alpha: add functionality for default IAM role

### ISSUE THREAD

**Issue by sean-beath** [aws/aws-cdk#22551]
### Describe the feature

Allow users to define a default IAM role for the cluster being created.

### Use Case

I'm always frustrated when I need to deploy my cluster and then go through the console to add a default IAM role on the cluster.

### Proposed Solution

Have a post-deployment Lambda that uses boto3 to define the role as being the default role.
Example code of how this could be implemented:
```
       import sys
            import os
            import json
            import cfnresponse
            import logging
            from pip._internal import main

            main(['install', 'boto3', '--target', '/tmp/'])
            sys.path.insert(0,'/tmp/')

            import boto3
            from botocore.exceptions import ClientError

            def lambda_handler(event, context):

                print(boto3.__version__)

                if event['RequestType'] == 'Delete':
                    cfnresponse.send(event, context, cfnresponse.SUCCESS, {'Data': 'Delete complete'})
                else:
                    try:
                        client = boto3.client('redshift')
                        response = client.modify_cluster_iam_roles(
                            ClusterIdentifier=os.environ['RedshiftClusterIdentifier'],
                            DefaultIamRoleArn=os.environ['RedshiftClusterRole']
                        )
                        print(response)
                    except Exception as e:
                        logger.error(e)
                        cfnresponse.send(event, context, cfnresponse.FAILED, {'Data': 'Create failed'})

                cfnresponse.send(event, context, cfnresponse.SUCCESS, {'Data': 'Create complete'})

                return {
                    'statusCode': 200,
                    'body': json.dumps('Deployed Default Role')
                }
```

### Other Information

There is currently no way to define a default role using CFN.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.43.1

### Environment details (OS name and version, etc.)

MacOS Monterey 12.5

**Comment by peterwoodworth** [comment]
You could create an [AwsCustomResource](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.custom_resources.AwsCustomResource.html) in your stack to easily make [the API call](https://docs.aws.amazon.com/redshift/latest/APIReference/API_ModifyClusterIamRoles.html) you need to.

I would recommend doing that for now. Reach out and create an issue on the [CloudFormation coverage roadmap](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues) if you'd like to see this be done automatically through CFN without the need to use a custom resource
