### ISSUE TITLE
Cannot create an IAM Role in .NET CDK

### ISSUE THREAD

**Issue by dkwgit** [aws/aws-cdk#22574]
### Describe the bug

The one file app below throws an exception: Unhandled exception. Newtonsoft.Json.JsonSerializationException: Error converting value "@jsii/kernel.SerializationError" to type 'Amazon.JSII.JsonModel.Api.Response.ErrorResponseName'. Path 'name'.
 ---> System.ArgumentException: Requested value '@jsii/kernel.SerializationError' was not found.

BEGIN FILE
using Amazon.CDK;
using Amazon.CDK.AWS.IAM;
using Constructs;

namespace MyApp
{
    sealed class Program
    {
        public static void Main(string[] args)
        {
            var app = new App();
            new MyAppStack(app, "MyAppStack", new StackProps
            {

                // For more information, see https://docs.aws.amazon.com/cdk/latest/guide/environments.html
            });
            app.Synth();
        }
    }

    public class MyAppStack : Stack
    {
        internal MyAppStack(Construct scope, string id, IStackProps props = null) : base(scope, id, props)
        {
            IRole role = new Role(this, "Role", new RoleProps());
        }
    }
}

### Expected Behavior

No Exception should be thrown

### Current Behavior

cdk synth causes Exception to be thrown

### Reproduction Steps

1. create a new csharp cdk project in a folder called MyApp: cdk init --language=csharp
2. Replace file Program.cs, with the file I put in the bug description. Delete MyAppStack.cs from the project, so that you have a one source file project.
3. do a cdk synth. Exception

Versions of things:
Node v16.18.0
npm v.8.19.2
cdk aws-cdk@2.46.0
dotnet 6.0.402
Visual Studio 22 (17.3.6)
Windows 11 Pro 22H2
C# 10.0

### Possible Solution

I don't know of one

### CDK CLI Version

2.46.0 (build 5a0595e)

### Node.js Version

v16.18.0

### OS

Windows 11 Pro

### Language

.NET

### Language Version

C# 10, .NET 6

**Comment by jwwg** [comment]
RoleProps needs at least assumedBy. The error message is the result of the exception throwing an exception when it is serialized.

This exception is caused by the Serialization error not being in the enum in ErrorReponse.cs in JSII 
```
    public enum ErrorResponseName
    {
        [EnumMember(Value = "@jsii/kernel.Fault")]
        JsiiError,
        [EnumMember(Value = "@jsii/kernel.RuntimeError")]
        RuntimeException,
    }
````
-probably just needs another enum?
(Same issue happens for all serialization errors thrown so could be helpful to get a better error message)

**Comment by dkwgit** [comment]
That explains it. Duh. I agree a better error message would be very helpful. But I’m closing this as user error (my error).

**Comment by dkwgit** [comment]
That explains it. Duh. I agree a better error message would be very helpful. But I’m closing this as user error (my error).
