### ISSUE TITLE
How to use aws cdk with springboot

### ISSUE THREAD

**Issue by VikasJindal84** [aws/aws-cdk#2257]
Hi,

Can you please share some example where aws infra is build using aws cdk and application code is done by java lib like spring boot.

Actually we want to use spring boot as application logic and aws cdk for creating aws infra.

**Comment by skinny85** [comment]
Another simple example from me: https://github.com/skinny85/test-code-build-deploy-spring-boot-project/blob/master/buildspec.yml

Do you need anything else from here @VikasJindal84 ?

**Comment by SomayaB** [comment]
Closing this issue since there hasn't been a response in a while. Feel free to reopen.
