### ISSUE TITLE
(ec2):  Adding a vpc endpoint in the wrong way

### ISSUE THREAD

**Issue by watany-dev** [aws/aws-cdk#22576]
### Describe the bug

I am afraid that the correction method implemented in https://github.com/aws/aws-cdk/pull/22481/ was a mistake.

In this PR, if you just add a property, the following error will be output, so comments are added to each line as a suppressive measure
```bash
error: [awslint:docs-public-apis:@aws-cdk/aws-ec2.InterfaceVpcEndpointAwsService.APPLICATION_MIGRATION_SERVICE] Public API element must have a docstring
```

However, in this similar PR the properties appear to be set in `aws-ec2/package.json`.
https://github.com/aws/aws-cdk/pull/22558/

Should I remove the comment and add the content to package.json?

### Expected Behavior

None

### Current Behavior

judging by looking at the code

### Reproduction Steps

I don't think it affects operation.

### CDK CLI Version

any

### Node.js Version

any

### OS

any

### Language

Typescript

**Comment by corymhall** [comment]
@watany-dev yeah it might be best to just add the exceptions to `package.json`.
