### ISSUE TITLE
Typescript or java for aws cdk

### ISSUE THREAD

**Issue by VikasJindal84** [aws/aws-cdk#2259]
Hi,

Which is preferred language typescript or java for aws cdk ? Does both have equal number of features or typescript cdk lib has more features that java cdk lib ?

**Comment by NGL321** [comment]
Hey @VikasJindal84,

So sorry no one got back to you on this. The CDK is written in Typescript, and we have language bindings for it in Python that are general availability.
Java and .NET are in developer preview still, but should have a large degree of the features implemented and functional.

Please @ me if you return to this and have any other questions.
