### ISSUE TITLE
aws_ssm: valueForSecureStringParameter is deprecated and the alternative isn't clearly documented

### ISSUE THREAD

**Issue by trondhindenes** [aws/aws-cdk#22593]
### Describe the issue

From here:
https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ssm.StringParameter.html#static-valuewbrforwbrsecurewbrstringwbrparameterscope-parametername-versionspan-classapi-icon-api-icon-deprecated-titlethis-api-element-is-deprecated-its-use-is-not-recommended%EF%B8%8Fspan

This text, for `valueForSecureStringParameter`:
> Deprecated: Use SecretValue.ssmSecure() instead, it will correctly type the imported value as a SecretValue and allow importing without version.

There's no mention of what `SecretValue.ssmSecure()` is, which module it belongs to or how to use it. The documentation should point properly point to a non-deprecated alternative.

### Links

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ssm.StringParameter.html#static-valuewbrforwbrsecurewbrstringwbrparameterscope-parametername-versionspan-classapi-icon-api-icon-deprecated-titlethis-api-element-is-deprecated-its-use-is-not-recommended%EF%B8%8Fspan

**Comment by MG-hynesnd** [comment]
Hi, noting that this is still an issue and that use of `SecretValue.ssmSecure()` as a replacement for `valueForSecureStringParameter` is still not clearly documented.

The cdk documentation page on getting SSM values, [here](https://docs.aws.amazon.com/cdk/v2/guide/get_ssm_value.html) doesn't mention that `valueForSecureStringParameter` is deprecated. So this doesn't become clear until attempting to use it and finding it marked `deprecated`.

I'm struggling to find any documentation of how to properly use `SecretValue`:
- The API reference page for `valueForSecureStringParameter` does not link to the recommended CDK v2 replacement `SecretValue.ssmSecure()`.
- Googling `SecretValue.ssmSecure()` leads to a CDK v1 API reference page.
- This page contains a link to the CDK v2 version of `SecretValue`. But this page is a bit light on context for how to properly adopt and use it.
- No usage example for fetching a secure SSM parameter.

**Comment by damolaobaleke** [comment]
Same, still not properly documented. Struggling to find any documentation on `SecretValue` and what module its coming from

**Comment by damolaobaleke** [comment]
Actually I've figured it out so its in the `@aws-cdk/core` module. @trondhindenes @MG-hynesnd 

Usage:
```
const awscdkCore = require('@aws-cdk/core');
const secret = awscdkCore.SecretValue.ssmSecure('SECRET_VALUE', 'version')
```

You can check out this link for the class and its methods within it. 
https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_core.SecretValue.html#static-ssmwbrsecureparametername-version

**Comment by Zishanwang1992** [comment]
I would like to work on this issue as my first issue. 

It looks like we can add a link to reference the recommended CDK v2 replacement SecretValue.ssmSecure(). Here is the [link](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.SecretValue.html#static-ssmwbrsecureparametername-version) that I found.

Let me know if there is any concern or suggestion!
