### ISSUE TITLE
Support for aws data lake

### ISSUE THREAD

**Issue by VikasJindal84** [aws/aws-cdk#2260]
HI ,

How can i create aws data lake (https://aws.amazon.com/big-data/datalakes-and-analytics/what-is-a-data-lake/ ) using cdk ?

**Comment by NGL321** [comment]
Hi @VikasJindal84,

Again, I apologize that no one responded to this sooner. AWS has a number of services that can be utilized to implement a data lake model. That stack can absolutely be implemented with the CDK!

I recommend you start by reading [this](https://docs.aws.amazon.com/solutions/latest/data-lake-solution/welcome.html)

😸
