### ISSUE TITLE
(aws-cdk-lib/aws-sns & aws-cdk-lib/aws-kms): kms aws managed key not importing through cdk

### ISSUE THREAD

**Issue by nathanberry97** [aws/aws-cdk#22605]
### Describe the bug

When deploying a sns topic through the cdk using a kms aws managed key if the kms aws managed key isn't present in the aws account it doesn't import it automatically. 

Here is some example code:

```typescript
    const myKeyAlias = kms.Alias.fromAliasName(this, 'defaultKey', 'alias/aws/sns');

    const topic = new sns.Topic(this, 'topic', {
        displayName: 'example topic',
        masterKey: myKeyAlias
    });
```

- What happens is that when deployed if the aws managed key (aws/sns) isn't already present within the account it won't import the key into kms 
- I can't find any mentation in [Key construct documentation](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_kms.Key.html) about importing aws managed keys

### Expected Behavior

When deployed automatically import the aws managed key in kms so when you look at the sns topic Encryption the following section is following:

Customer master key (CMK)
(Default) alias/aws/sns

### Current Behavior

It currently deploys the sns topic and the Encryption section points towards the following key:

Customer master key (CMK)
arn:aws:kms:{region}:{accountNum}:alias/aws/sns

This is due to the cdk not importing the aws managed key into kms

### Reproduction Steps

imports:

```typescript
import * as sns from 'aws-cdk-lib/aws-sns';
import * as kms from 'aws-cdk-lib/aws-kms';
```

Example code to create the topic and key:

```typescript
    const myKeyAlias = kms.Alias.fromAliasName(this, 'defaultKey', 'alias/aws/sns');

    const topic = new sns.Topic(this, 'topic', {
        displayName: 'example topic',
        masterKey: myKeyAlias
    });
```

If the aws managed key isn't already in the aws account the sns encryption is set to:
Customer master key (CMK)
arn:aws:kms:{region}:{accountNum}:alias/aws/sns

But the encryption should be:
Customer master key (CMK)
(Default) alias/aws/sns

### CDK CLI Version

2.43.1

### Node.js Version

16.17.0

### OS

Ubuntu 20.04.5 LTS

### Language

Typescript

**Comment by kornicameister** [comment]
I might be wrong but not every managed key is in every region. I was also using managed keys against topics used for alarms and simply switched later to the same key I use to encrypt rest of the stack. But then again I had an option to do so. 
Long story short...not sure if key being managed means it just should be there. Check `alias/AWS/sns` across various regions for example.

**Comment by nathanberry97** [comment]
Hi Tomasz, I hope you are well.

I'm deploying in eu-west-2 and the key is available in that region as if I make a sns topic manually it imports the aws managed key into kms (alias/AWS/sns) and then when I use the cdk it works fine from then on due to it already being in the account. 

But due to the cdk needing to be deployed in x amount of accounts I would then need to check each account and manually make a temp sns topic just to import the key for the cdk to work as expected, which isn't too practical

**Comment by kornicameister** [comment]
So that means that you can make key popup in the target account/region pair if you create topic manually via console forcing managed key to be imported into region?

**Comment by nathanberry97** [comment]
If you follow the documentation on the sns topic to the [AWS KMS key ID](https://docs.aws.amazon.com/sns/latest/dg/sns-server-side-encryption.html) heading.

Within the note it mentations that the key won't be imported until the first publish of the SNS topic, so it is working as expected. 

But if you deploy it within the management console it will create the key straight away 

Thanks for your help anyway Tomasz

**Comment by kornicameister** [comment]
Not sure how much I helped 🤔.
It just looks as if you need custom resource of sort to do that in IAC, right?
