### ISSUE TITLE
aws-globalaccelerator: Template for Global Accelerator shows Internal Error

### ISSUE THREAD

**Issue by jinspark-lab** [aws/aws-cdk#22602]
### Describe the bug

When I deploy AWS Global Accelerator using CDK, it works well, but it fails in test.

`
        const listener = accelerator.addListener('agaListener', {
            portRanges: [
                { fromPort: 80 },
            ]
        });
        listener.addEndpointGroup('EndpointGroup', {
            endpoints: [new ga_endpoints.NetworkLoadBalancerEndpoint(elb)]
        });
`

In the above code, I can find error in "listener.addEndpointGroup". It works fine with "cdk deploy". However it goes fail when it is called from "Template.fromStack".

Here is the error case :

`
    const app = new cdk.App();
    const stack = new Accelerator.AcceleratorStack(app, 'MyTestStack');
    const template = Template.fromStack(stack);
`

Template.fromStack returns error like:

`
    Resolution error: Supplied properties not correct for "CfnEndpointGroupProps"
      endpointConfigurations: element 0: supplied properties not correct for "EndpointConfigurationProperty"
        endpointId: required but missing.

      at ValidationResult.assertSuccess (node_modules/aws-cdk-lib/core/lib/runtime.js:1:2727)
      at cfnEndpointGroupPropsToCloudFormation (node_modules/aws-cdk-lib/aws-globalaccelerator/lib/globalaccelerator.generated.js:1:7093)
      at CfnEndpointGroup.renderProperties (node_modules/aws-cdk-lib/aws-globalaccelerator/lib/globalaccelerator.generated.js:1:12468)
      at PostResolveToken.Resources (node_modules/aws-cdk-lib/core/lib/cfn-resource.js:1:5164)
      at PostResolveToken.postProcess (node_modules/aws-cdk-lib/core/lib/util.js:1:1648)
      at Object.postProcess (node_modules/aws-cdk-lib/core/lib/private/resolve.js:1:1329)
      at DefaultTokenResolver.resolveToken (node_modules/aws-cdk-lib/core/lib/resolvable.js:1:1402)
      at resolve (node_modules/aws-cdk-lib/core/lib/private/resolve.js:1:2743)
      at Object.resolve (node_modules/aws-cdk-lib/core/lib/private/resolve.js:1:1203)
      at resolve (node_modules/aws-cdk-lib/core/lib/private/resolve.js:1:3007)
`

### Expected Behavior

Template Module creates template from Stack without an error.

### Current Behavior

It returns an error, so it is impossible to implement test code for AWS Global Accelerator

### Reproduction Steps

1. Create Global Accelerator CDK Stack

2. Add Endpoint Group to listener without "endpointId", such as importing existing ELB.

3. Run Test code using "Template.fromStack(stack)

### Possible Solution

I think required template should be updated for AWS Global Accelerator.

### CDK CLI Version

2.46.0

### Node.js Version

16.17.0

### OS

Mac

### Language

Typescript

**Comment by pahud** [comment]
@jinspark-lab Apparently the [EndpointId](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-globalaccelerator-endpointgroup-endpointconfiguration.html#cfn-globalaccelerator-endpointgroup-endpointconfiguration-endpointid) is required yet missing. When you add an NLB endpoint to the endpoint group, you should see the NLB ARN as the EndpointId. No?

**Comment by jinspark-lab** [comment]
@pahud I am not sure I understand the context. Yes. I am trying to add NLB into AWS Global Accelerator like this :
`
        const elb = elb.NetworkLoadBalancer.fromNetworkLoadBalancerAttributes(this, 'elb', {
            loadBalancerArn: this.node.tryGetContext('targetEndpoint')
        });
`
In this case, there is no endpointId as parameter. It works well when I try CDK deploy, but it only fails in the test code.

`
const template = Template.fromStack(stack);
`

**Comment by pahud** [comment]
I can't reproduce it in my environment.

My full code below:

```ts
import {
  App, Stack,
  aws_ecs_patterns as ecs_patterns,
  aws_ecs as ecs,
  aws_ec2 as ec2,
  aws_globalaccelerator as ga,
  aws_globalaccelerator_endpoints as endpoints,
  assertions,
} from 'aws-cdk-lib';

test('demo test', () => {
  // GIVEN
  const app = new App();
  const stack = new Stack(app, 'test-stack');
  const vpc = new ec2.Vpc(stack, 'Vpc', { natGateways: 1 });

  const service = new ecs_patterns.NetworkLoadBalancedFargateService(stack, 'NLBService', {
    vpc,
    taskSubnets: { subnetType: ec2.SubnetType.PUBLIC },
    assignPublicIp: true,
    taskImageOptions: {
      image: ecs.ContainerImage.fromRegistry('public.ecr.aws/pahudnet/nyancat-docker-image:latest'),
      containerPort: 80,
    },
  });

  // WHEN
  const accelerator = new ga.Accelerator(stack, 'Accelerator', {
    enabled: true,
  });
  const listener = accelerator.addListener('agaListener', { portRanges: [{ fromPort: 80 }] }); listener.addEndpointGroup('EndpointGroup', { endpoints: [new endpoints.NetworkLoadBalancerEndpoint(service.loadBalancer)] });

  const template = assertions.Template.fromStack(stack);

  // THEN
  template.resourceCountIs('AWS::ElasticLoadBalancingV2::LoadBalancer', 1);
});
```
And I can pass the `yarn test`

<img width="1087" alt="image" src="https://user-images.githubusercontent.com/278432/197912425-c5ef09df-1f11-4fba-991a-e1a9feb6435a.png">

**Comment by jinspark-lab** [comment]
Hmm.. It is strange. I have passed my test also in Cloud9 Environment.

![image](https://user-images.githubusercontent.com/6311805/197913698-9054cd8a-5412-4859-9a23-d77187a0081c.png)

Same CDK version & Different npm version (Cloud9 - 8.19.2, Dev Machine - 8.15.0).

This may be issue in system env, not CDK lib.

**Comment by peterwoodworth** [comment]
@jinspark-lab I can't reproduce this either. I do suspect it is some issue regarding your system env (these types of issues usually are). Let us know if you find any evidence that CDK is doing something wrong!

**Comment by jinspark-lab** [comment]
No problem! Not happened in my team mates environment. I think it is just my system env error as you mentioned. I think this can be closed.
