### ISSUE TITLE
(ci): pr-linter.yml (validate-pr) doesn't validate PRs that come from forks

### ISSUE THREAD

**Issue by Youssef1313** [aws/aws-cdk#22624]
### Describe the bug

When a PR base branch is from a fork, the checkout step is checking out the `main` branch and doesn't really validate the PR.

### Expected Behavior

The PR should be correctly validated.

### Current Behavior

When a PR base branch is from a fork, the checkout step is checking out the `main` branch and doesn't really validate the PR.

### Reproduction Steps

See https://github.com/aws/aws-cdk/pull/22622
I'm introducing an error but validate-pr doesn't fail.

The previous checkout step is checking out the `main` branch.

**Comment by TheRealAmazonKendra** [comment]
Changes to the linter can't be tested from a fork. That's intentional and ensures that random contributors can't make changes that escalate privileges or things like that. This isn't an issue, it's working as intended.
