### ISSUE TITLE
cloudfront: encrypted bucket for access logs

### ISSUE THREAD

**Issue by jangolano** [aws/aws-cdk#22627]
### Describe the feature

When trying to assign an encrypted bucket to access logs we aren't able to do so using higher level constructs.

The encryption key needs to grant access to the cloudfront distribution, however the cloudfront distribution is created at the same time the bucket is assigned for logging.

### Use Case

We need to use encrypted buckets for cloudwatch access logs.  It would be nice to have a way to setup this up with higher level cdk constructs.

### Proposed Solution

Allow logging to be associated to a distribution after it has been created.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.47.0

### Environment details (OS name and version, etc.)

MacOS 12.6 Monterey

**Comment by comcalvi** [comment]
Could you provide a minimal CDK stack that reproduces the issue?
