### ISSUE TITLE
(synthetics): expose lifecycle rules for generated artifacts bucket

### ISSUE THREAD

**Issue by mackensen** [aws/aws-cdk#22634]
### Describe the feature

Allow passing Lifecycle Rules to the generated ArtifactsBucketLocation S3 bucket.

### Use Case

If you do not specify an `ArtifactsBucketLocation` for a `Canary` an S3 bucket is created for you and cannot be changed afterward. This bucket sets props for encryption and forcing SSL but does not expose lifecycle rules, nor are lifecycle rules set in relation to the `failureRetentionPeriod` and `successRetentionPeriod` props on the Canary. The S3 bucket will grow indefinitely unless you manually specify lifecycle rules from the interface or CLI.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.43.1

### Environment details (OS name and version, etc.)

macOS Monterey 12.6

**Comment by kaizencc** [comment]
@mackensen this sounds like something reasonable to support. Would be happy to review a PR submitted by the community on this.
