### ISSUE TITLE
dynamodb: How to get the TableName for a generated CfnGlobalTable?

### ISSUE THREAD

**Issue by alexandervandekleutab** [aws/aws-cdk#22639]
### Describe the bug

I am not sure how to get the `TableName` from a `CfnGlobalTable`. The property is available on the resource but is of type `string | undefined` and when I try to access it, it's always `undefined`.

### Expected Behavior

The table name should be either a string (if passed in) or a token (if generated) as far as I can tell.

### Current Behavior

The table name is `undefined`.

### Reproduction Steps

```typescript
    this.table = new dynamodb.CfnGlobalTable(this, 'MetadataTable', {
      attributeDefinitions: [
        {
          attributeName: 'pkey',
          attributeType: 'S',
        },
      ],
      keySchema: [
        {
          attributeName: 'pkey',
          keyType: 'HASH',
        },
      ],
      replicas: [
        {
          region: Stack.of(this).region,
        },
      ],

      billingMode: 'PAY_PER_REQUEST',
      streamSpecification: {
        streamViewType: 'NEW_AND_OLD_IMAGES',
      },
    })
```

I tried accessing the table name via
```typescript
this.table.tableName // undefined
```

and
```typescript
new CfnOutput(this, 'TableName', {
      exportName: 'TableName',
      value: this.table.getAtt('TableName').toString(),
    })
```

Neither of these worked.

### CDK CLI Version

2.46.0

### Framework Version

2.46.0

### Node.js Version

14/17

### OS

MacOS

### Language

Typescript

**Comment by alexandervandekleutab** [comment]
I struggled with this for a good half hour and then immediately solved it like this:
```typescript
new CfnOutput(this, 'TableName', {
      exportName: 'TableName',
      value: Fn.select(1, Fn.split('/', this.table.attrArn)),
    })
```

**Comment by babakc** [comment]
I'm not completely against this solution, but it seems like a bit of a workaround. Is there a reason TableName is returned undefined?
