### ISSUE TITLE
Lambda: CDK Deployment Fails

### ISSUE THREAD

**Issue by jjasca** [aws/aws-cdk#22643]
### Describe the bug

Receives the following error intermittently when deploying a Lambda function using a custom rust runtime usingCDK as part of a CI/CD pipeline

fork/exec /var/task/bootstrap: permission denied
Runtime.InvalidEntrypoint

This is occurring in multiple regions and multiple accounts

### Expected Behavior

The function can be executed without error

### Current Behavior

When the  CI/CD pipeline is run, the CDK application should deploy the function with the correct OS level permissions so the function can execute successfully. 

### Reproduction Steps

Run CI/CD pipeline which contains cdk deploy results in error however running the CI/CD pipeline once more results in function being deployed successfully. 

### CDK CLI Version

2.47.0

### Framework Version

4.8.4

### Node.js Version

16.18.0

### OS

Ubuntu 20.04.5 LTS

### Language

Typescript

**Comment by corymhall** [comment]
@jjasca how is the `bootstrap` binary being created? The CDK will take that file and upload it to S3, but it won't mess with the permissions on the file. My hunch would be that there is a build script that creates `bootstrap` and it needs to set the correct permissions.

**Comment by jjasca** [comment]
The custom rust runtime is created earlier in the CI/CD pipeline and is tested to ensure it is working as expected and then once all tests pass proceeds through to the CDK phase which involves using lambda.Code.fromAsset pointing to the directory of the custom runtime rust binary that was created earlier in the CI/CD pipeline.T o deploy the Lambda function to two AWS regions (us-east-1, us-west-2. 

There are reports that the above permission error would occur for example when the same rust binary that is created earlier in the pipeline is deployed to us-east-1 it would succeed but fail in us-west-2 or vice versa or it would fail in a test environment but not staging or fail in production and not staging for example.

**Comment by corymhall** [comment]
@jjasca it is impossible for us to troubleshoot this without the code that is used. It sounds like there is _a lot_ going outside of CDK that could be causing this issue. For example, if the same asset is used for a function in two different regions, the CDK just stores that as a single asset and copies it to each S3 bucket. The fact that it works in one region an not in another indicates that there is something else going on.

One thing I would check is to make sure the asset hash is changing. It could be that the `bootstrap` asset was generated _without_ execute permissions and uploaded to S3. Then if all that was changed was execute permissions were granted, the asset hash may have remained the same and CDK would not upload the new file.
