### ISSUE TITLE
aws-applicationautoscaling, aws-autoscaling: Scheduled actions missing support to specify timezone property

### ISSUE THREAD

**Issue by ShadowDog007** [aws/aws-cdk#22645]
### Describe the feature

Scheduled actions for both applicationautoscaling ScalableTarget and autoscaling support specifying the timezone property.

This should be exposed from CDK apis.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-as-scheduledaction.html#cfn-as-scheduledaction-timezone

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-applicationautoscaling-scalabletarget-scheduledaction.html#cfn-applicationautoscaling-scalabletarget-scheduledaction-timezone

### Use Case

Supporting scaling actions which adjust for daylight savings

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.47.0

### Environment details (OS name and version, etc.)

n/a

**Comment by peterwoodworth** [comment]
Yes, we should be able to support this. Thanks for the request.

@bora-7 do you want to work on this?

**Comment by ShadowDog007** [comment]
@bora-7 just FYI #17330 added timeszone to `aws-autoscaling` but it's still missing from `aws-applicationautoscaling`

**Comment by sothawo** [comment]
A pity. This is now one year old, and CDK still does not support timezones in aws-applicationautoscaling.

**Comment by neilferreira** [comment]
It looks like @bora-7 had a crack at this but it was never meged

**Comment by neilferreira** [comment]
nevermind - this was actioend in 2.97.1 with the new Schedule class! https://github.com/aws/aws-cdk/releases/tag/v2.97.1

This can be closed.

**Comment by sothawo** [comment]
I am using aws-cdk 2.115.0. I am creating an ECS service
```
            const scaledTask = loadBalancedFargateService.service.autoScaleTaskCount({
                maxCapacity: props.ecsService.maxScaledContainerCount,
                minCapacity: props.ecsService.desiredContainerCount,
            })
```
and then when trying to set a schedule
```
            scaledTask.scaleOnSchedule("sched1", {
                startTime: someTime,
                endTime: someTime,
                // no timezone here
            })
```
there still is no possibility to set the timezone

**Comment by saudansari** [comment]
This was brought in version 2.97.1 but then it was taken out. Now I'm stuck at 2.97 and unable to move forward without the timezone capability for my fargate ecs tasks.
