### ISSUE TITLE
(stepfunctions): athena-start-query-execution tasks generate invalid S3 ARNs

### ISSUE THREAD

**Issue by aaronatbissell** [aws/aws-cdk#22650]
### Describe the bug

When using an athena start-query-execution task, the CDK generates a default policy including some permissions for the S3 buckets used as an output location. This S3 bucket policy includes the S3 bucket ARN as a resource, but the auto-generated ARN includes region and account ID as described [here](https://docs.aws.amazon.com/AmazonS3/latest/userguide/s3-arn-format.html). When trying to deploy, you end up with an error that looks like this:

> Error: The stack failed to deploy: UPDATE_ROLLBACK_COMPLETE: Resource arn:aws:s3:us-east-1:_accountId_:bucket/export can not contain region information.

I believe this bug was introduced in PR  #22314 

### Expected Behavior

Auto-generated policy includes s3 bucket without region or account ID

### Current Behavior

Deployment failure

### Reproduction Steps

packages/@aws-cdk/aws-stepfunctions-tasks/test/athena/start-query-execution.test.ts
Test Name: "bucket arn is formatted as expected in generated policy"

This test is currently incorrect. It includes the region and account ID on the S3 bucket ARN

### Possible Solution

Revisit PR #22314 

### CDK CLI Version

2.43.0

### Node.js Version

16.15.1

### OS

macOS 12.6

### Language

Typescript

### Language Version

4.7.3

**Comment by kaizencc** [comment]
Thanks for the report, @aaronatbissell. Do you have time to contribute a fix for this?

**Comment by aaronatbissell** [comment]
OK - I can take a stab at it if you'd like. Just let me know!

**Comment by aaronatbissell** [comment]
@kaizencc - I created the PR, let me know what you think!

**Comment by TheRealAmazonKendra** [comment]
Looks like the fix for this was already merged.
