### ISSUE TITLE
aws-opensearchservice: Creating a domain fails for imported vpc/subnets when zone awareness is enabled

### ISSUE THREAD

**Issue by stijnbrouwers** [aws/aws-cdk#22651]
### Describe the bug

Creating a domain fails for imported vpc/subnets when zone awareness is enabled and the cdk context is cleared.
When the CDK context is already retrieved and the VPC is in the context, the deployment works.

### Expected Behavior

a Domain to be created when using an imported (fromLookUp) VPC.

### Current Behavior

An error is thrown stating:
```
When providing vpc options you need to provide a subnet for each AZ you are using
```

### Reproduction Steps

- clear the context (```cdk context --clear```)
- Import a VPC with Vpc.fromLookUp
- select subnets from the VPC
- Create a new Domain with the imported VPC and selected subnets
- Deploy the stack

### Possible Solution

Check if there are subnets provided in the DomainProps that have ```isPendingLookup === true```

### CDK CLI Version

2.47.0

### Node.js Version

6.14.16

### OS

macOS Monterey

### Language

Typescript

**Comment by pahud** [comment]
Thank you for your issue report and PR submission!!

**Comment by khushail** [comment]
Hey @stijnbrouwers , I see that your PR,addressing the current issue is merged and there are no pending changes. So I am closing this issue. Please feel free to reopen if some part of your issue request is still erroneous.
