### ISSUE TITLE
globalaccelerator: Cannot create listeners on same ports for different protocols to match NLB endpoint TCP_UDP

### ISSUE THREAD

**Issue by eugene-screenmeet** [aws/aws-cdk#22656]
### Describe the bug

I am using an NLB as an end-point, and the NLB is configured for TCP_UDP protocol. However, the global accelerator listener does not have this option, it's only UDP or TCP.

When creating resources manually from the console, I am allowed to create 2 listeners on the same port, one for UDP and one for TCP, for which I can then bind the same NLB which listens as TCP_UDP.

If I try to create a global accelerator with 2 listeners which listen on the same port, but one on UDP and one on TCP, I get the following error during stack deployment:

Resource handler returned message: "Invalid port range PortRange(fromPort=443, toPort=443), which overlaps with port range PortRange(fromPort=443, toPort=443) taken by listener arn:aws:globalaccelerator::******

(update: this error only strikes when modifying an existing resource - if old listener is being deleted and new one is created, appears that a race condition is created)

### Expected Behavior

Should be allowed to create a listener for each protocol on the same port, as the console UI allows me to.

### Current Behavior

Produces an error during deployment:

Resource handler returned message: "Invalid port range PortRange(fromPort=443, toPort=443), which overlaps with port range PortRange(fromPort=443, toPort=443) taken by listener

### Reproduction Steps

Attach 2 listeners with the same fromPort but different protocols. Sample code:

      const listener_udp = GA.addListener(`listen-udp`, {
        portRanges: [
          { fromPort: 443 }
        ],
        protocol: aws_ga.ConnectionProtocol.UDP,
        listenerName: `group-udp`
      });
  
      listener_udp.addEndpointGroup(`group-udp`, {
        endpoints: [new ga_endpoints.NetworkLoadBalancerEndpoint(loadBalancedFargateService.loadBalancer)]
      });
  
      const listener_tcp = GA.addListener(`listen-tcp`, {
        portRanges: [
          { fromPort: 443 }
        ],
        protocol: aws_ga.ConnectionProtocol.TCP,
        listenerName: `listener-tcp`
      });
  
      listener_tcp.addEndpointGroup(`group-tcp`, {
        endpoints: [new ga_endpoints.NetworkLoadBalancerEndpoint(loadBalancedFargateService.loadBalancer)]
      });

### Possible Solution

Several possible solutions here:

1. Fix this error/validation and allow different protocol listeners on the same port
2. Add TCP_UDP as an option to the Global Accelerator listener to match the NLB listener type.

### CDK CLI Version

2.47.0 (build 3528e3d)

### Node.js Version

14.20.1

### OS

MacOS

### Language

Typescript

**Comment by eugene-screenmeet** [comment]
Addendum: This only seems to strike when modifying an existing resource, some kind of a race condition with deleting the old listener and creating new one. When creating a new resource this seemed to have work fine.

**Comment by rix0rrr** [comment]
I think you probably changed the construct ID of your `TCP` listener when you added the `UDP` listener.

Did you change:

```ts
 const listener_tcp = GA.addListener(`listener`, {
    portRanges: [
      { fromPort: 443 }
    ],
    protocol: aws_ga.ConnectionProtocol.TCP,
  });
```

into:

```ts
 const listener_tcp = GA.addListener(`listen-tcp`, {
  // ...
```

?

If so, what happens in practice is that CloudFormation will create the new listener first before deleting the old one. But it can't create the new listener because the port+protocol combination is already taken by the old one (which hasn't been deleted yet).
