### ISSUE TITLE
(aws-certificate-manager): (cannot create certificate due to internal failure)

### ISSUE THREAD

**Issue by jiayuasu** [aws/aws-cdk#22663]
### Describe the bug

I am using AWS CDK to request a certificate from aws-certificate-manager, in my stack. It was working fine before. But today when I re-deploy my stack and request the certificate, it keeps giving me internal error.

![image](https://user-images.githubusercontent.com/10948864/198212156-0e2492b2-13ab-4838-822a-e9b62285753f.png)

### Expected Behavior

Successfully issue the certificate

### Current Behavior

Failed and show me "internal error"

### Reproduction Steps

```
        Certificate ecsCertificate = Certificate.Builder.create(this, "EcsCertificate")
                .domainName(applicationName + "." + hostedZone.getZoneName())
                .validation(CertificateValidation.fromDns(hostedZone)).build();
```

### CDK CLI Version

2.45.0 (build af1fb7c)

### Node.js Version

I am using Java CDK

### OS

MacOS 12.6

### Language

Java

### Language Version

Java 11

**Comment by seyfer** [comment]
I got the same error today, spent 4 hours debugging and cannot deploy.
`12:15:13 PM | CREATE_FAILED        | AWS::CertificateManager::Certificate      | PDFCert1430A16F`

**Comment by maxd** [comment]
Looks like this problem was fixed. I managed to deploy my certificate.

**Comment by peterwoodworth** [comment]
Based on all the reports here it seems this was a temporary service error that has since been resolved. Please post here if you continue to run into this error, thanks!
