### ISSUE TITLE
(AmazonApiGatewayV2): (ApiMapping key already exists for this domain name)

### ISSUE THREAD

**Issue by Eric-Jalal** [aws/aws-cdk#22660]
### Describe the bug

Hello,

I have a custom domain name and set in my CDK app and also an `ApiMappingKey` for my function.

When I try to redeploy it throws a 409 error:
`Error: The stack named <api-name> failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: ApiMapping key already exists for this domain name (Service: AmazonApiGatewayV2; Status Code: 409; Error Code: ConflictException; Request ID: 298d3f36-5dd5-4b8c-ab8c-04f05004ea64; Proxy: null)`

### Expected Behavior

It should try to check and if the resource doesn't exist, create if it matches the existing nothing to do.

### Current Behavior

It fails to 409 error.

### Reproduction Steps

This is the cdk app code I have:

```java
    var domainName =
        DomainName.fromDomainNameAttributes(
            this,
            "api-gw-domain-name",
            DomainNameAttributes.builder()
                .name("domain.com")
                .regionalDomainName("whatever")
                .regionalHostedZoneId("whatever")
                .build());

    DomainMappingOptions domainMappingOptions =
        DomainMappingOptions.builder()
            .domainName(domainName) 
            .mappingKey("api/device)
            .build();
```

### CDK CLI Version

2.47.0

### Node.js Version

8.19.0

### OS

Linux

### Language

Java

**Comment by hero-kieran** [comment]
@Jerilok Did you find a solution to this issue?

I have the same issue where I am defining the `AWS::ApiGatewayV2::ApiMapping` and getting the same result ` ApiMapping key already exists for this domain name`

**Comment by apatriz** [comment]
Same here, why is this issue closed?

**Comment by renatoargh** [comment]
Same problem here. My stack used to work but stopped suddenly with this error. In my case I first created the mapping via CDK like this:

```typescript
const apiDomain = `${params.subDomain}.${params.hostedZone.zoneName}`;
const domainName = new apigwv2.DomainName(scope, upperFirst(params.name) + 'HttpAPIDomainName', {
  domainName: apiDomain,
  certificate: params.certificate,
});

const defaultAuthorizer = new HttpJwtAuthorizer(upperFirst(params.name) + 'HttpApiDefaultAuthorizer', params.jwtIssuer, {
  jwtAudience: params.jwtAudience,
});

this.apiId = upperFirst(params.name) + 'HttpApi';
this.api = new apigwv2.HttpApi(scope, this.apiId, {
  apiName: prefixer(params.name),
  disableExecuteApiEndpoint: true,
  defaultDomainMapping: { domainName },
  defaultAuthorizer,
  corsPreflight: {
    allowHeaders: [
      'authorization',
      'content-type',
      'accept',
    ],
    exposeHeaders: [
      'x-trace-id',
    ],
    allowMethods: [
      apigwv2.CorsHttpMethod.GET,
      apigwv2.CorsHttpMethod.HEAD,
      apigwv2.CorsHttpMethod.OPTIONS,
      apigwv2.CorsHttpMethod.POST,
      apigwv2.CorsHttpMethod.PATCH,
      apigwv2.CorsHttpMethod.DELETE,
    ],
    allowOrigins: params.allowOrigins,
    maxAge: Duration.days(1),
  },
});
```

**Comment by kristof-kasa** [comment]
Any updates on this? I have the same issue.

**Comment by c88lopez** [comment]
@Eric-Jalal Having the same issue here - why did you close it ?

**Comment by JoergStrebel** [comment]
Same issue using terraform.

**Comment by jeff1evesque** [comment]
Same problem today with SAM template generated from CDK.

**Comment by pahud** [comment]
Per the provided sample,

`domainName` is defined by referencing an existing one using `fromDomainNameAttributes()`, this means CDK would not know if that domain name has a domainMapping and what the mapping key is.

Now if you create a mapping for that using a mapping key which might already exists but not created by CDK. It could happen and CDK won't know that unless query all existing keys using SDK calls.

It's just like you are trying to create a s3 bucket with a specific name but that bucket name actually has been used by another bucket created out of CDK.

Is this the case we are discussing here?

```
   var domainName =
        DomainName.fromDomainNameAttributes(
            this,
            "api-gw-domain-name",
            DomainNameAttributes.builder()
                .name("domain.com")
                .regionalDomainName("whatever")
                .regionalHostedZoneId("whatever")
                .build());

    DomainMappingOptions domainMappingOptions =
        DomainMappingOptions.builder()
            .domainName(domainName) 
            .mappingKey("api/device)
            .build();
```

**Comment by rohanmaheshwari430** [comment]
This issue is still happening in terraform aws provider 3.0 

```
│ Error: error creating API Gateway v2 API mapping: ConflictException: ApiMapping key already exists for this domain name │ │ with
```
The terraform plan actually suggests the correct thing that it needs to update the ApiMapping, but instead of doing a modification, it tries to create one first, even if it decided it could delete it before creating a new one this would not be an issue, but it seems the terraform module is not trying and update/modification transaction.

**Comment by kaihendry** [comment]
I'm hitting this problem right now: https://github.com/kaihendry/go-cdk2-hello/actions/runs/13486590236/job/37678515132

How come cdk isn't smart enough to know a resource is about to replace it?
