### ISSUE TITLE
aws_s3_deployment: BucketDeployment is deleted if custom resource lambda fails during update

### ISSUE THREAD

**Issue by rittneje** [aws/aws-cdk#22670]
### Describe the bug

We have an aws_s3_deployment.BucketDeployment with `retain_on_delete=False`. Recently, when updating the files in the deployment, the custom resource lambda failed while invaliding the CloudFront distribution due to some transient issue. Due to a bug in the lambda, it incorrectly sent back a bogus physical resource id to CloudFormation, which caused CloudFormation to conclude it had done an update replacement, so then it tried to roll back by deleting the new physical resource id. Since the custom resource lambda does not consider the physical resource id, it just decided to delete the whole deployment, resulting in data loss.

The source of the issue is here:
https://github.com/aws/aws-cdk/blob/74318c7d22bfc00de9e005f68a0a6aaa58c7db39/packages/%40aws-cdk/aws-s3-deployment/lib/lambda/index.py#L238

If an exception is thrown and caught, no `physicalResourceId` is passed, so it defaults to the log stream name, which is different from the real uuid-based physical resource id.

### Expected Behavior

It should not have sent back a new bogus physical resource id, so CloudFormation would just do a normal reverse update during rollback instead of a delete.

### Current Behavior

data loss

### Reproduction Steps

Since the original failure was due to some transient CloudFront issue, I don't know how to reliably reproduce this. Our CDK construct looks like this:
```python
        aws_s3_deployment.BucketDeployment(
            self,
            "deployment",
            sources=[aws_s3_deployment.Source.asset(asset_path)],
            destination_bucket=bucket,
            destination_key_prefix=path_prefix,
            distribution=distribution,
            retain_on_delete=False
        )
```

### CDK CLI Version

2.39.1 (build f188fac)

### Node.js Version

v16.17.0

### OS

Alpine 3.16

### Language

Python

### Language Version

3.10.6

**Comment by rittneje** [comment]
cc @peterwoodworth

**Comment by rittneje** [comment]
ping @otaviomacedo @peterwoodworth

**Comment by rittneje** [comment]
@peterwoodworth Are there plans to fix this bug? It can result in unexpected data loss.

**Comment by peterwoodworth** [comment]
@rittneje sorry it's taken so long for you to get a response here. We take data loss seriously and will address this soon.

The behavior you're running into is described [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/crpg-ref-responses.html) under `PhysicalResourceId`

I'm not super familiar with this custom resource, so I'm not immediately sure why we are setting the PhysicalResourceId to be different in circumstances, or how we can fix this without breaking previous behavior. We'll look into this

**Comment by garyaparker** [comment]
@peterwoodworth any update on this issue?  We appear to have experienced data lost twice this week due to the combination of this bug and an outage of the CloudFront API.

Is my understanding of the issue correct in that we can set retain_on_delete=True as a temporary fix until the root cause is resolved?
