### ISSUE TITLE
@aws-cdk/aws-redshift-alpha: Add comments for redshift tables construct 

### ISSUE THREAD

**Issue by ksco92** [aws/aws-cdk#22682]
### Describe the feature

Currently we have this construct:

https://docs.aws.amazon.com/cdk/api/v2/docs/@aws-cdk_aws-redshift-alpha.Table.html

In order to be able to fully utilize CI/CD for tables and generate version controlled documentation, we need to be able to add table descriptions through code. A simple `description` attribute like in Glue tables should be enough:

https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-glue.Table.html

### Use Case

The current table construct allows the programmatic creation and modification of tables, however,  in real life,  comments for documentation are critical in any big data use case for automated documentation.

This addition will bring CDK one step closer to being able to fully manage a Redshift's table table structure and documentation.

### Proposed Solution

Add a `description` attribute to the table construct.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.45

### Environment details (OS name and version, etc.)

AmazonLinux2

**Comment by peterwoodworth** [comment]
For the Glue table we are able to make use of the [CloudFormation Glue Table description property](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-table-tableinput.html#cfn-glue-table-tableinput-description). However for Redshift we make use of [a custom resource](https://github.com/aws/aws-cdk/tree/v2.49.0/packages/%40aws-cdk/aws-redshift/lib/private/database-query-provider) which I'm personally not too familiar with. But this custom resource gives us quite a bit of freedom, if there's any way to create comments with the Redshift API then we should be able to support this 🙂
