### ISSUE TITLE
(@aws-cdk/aws-iot): CfnLocationAction asks for Date type despite spec wanting Timestamp type

### ISSUE THREAD

**Issue by dreamorosi** [aws/aws-cdk#22732]
### Describe the bug

The `iot.CfnTopicRule` construct now supports an action called `LocationAction` ([link to CloudFormation docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-iot-topicrule-locationaction.html)).

The `LocationAction` entity has a property called [`Timestamp`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-iot-topicrule-action.html#cfn-iot-topicrule-locationaction-timestamp) which [according to the CloudFormation docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-iot-topicrule-timestamp.html) is supposed to be of type `AWS::IoT::TopicRule Timestamp` and have shape:

```json
{
  "Unit": String,
  "Value": String
}
```

At present, in version `1.179.0` the property has incorrect type of `Date`, which causes the synth step to fail.

### Expected Behavior

The resource should have the correct type and allow to deploy correctly.

### Current Behavior

Error:
```
cdk-stack.ts(114,17): error TS2322: Type '{ value: string; unit: string; }' is not assignable to type 'Date | IResolvable'.
  Object literal may only specify known properties, but 'value' does not exist in type 'Date | IResolvable'
```

![Screenshot 2022-11-01 at 15 26 20](https://user-images.githubusercontent.com/7353869/199256932-6e0d7cc9-17af-4698-924e-55cb73711ef8.png)

### Reproduction Steps

```ts
import * as cdk from "@aws-cdk/core";
import * as iot from "@aws-cdk/aws-iot";
import * as iam from "@aws-cdk/aws-iam";

export class cdkStack extends cdk.Stack {
  constructor(
    scope: cdk.Construct,
    id: string,
    props?: cdk.StackProps,
  ) {
    super(scope, id, props);

    const role = new iam.Role(this, "iot-tracker-role", {
      assumedBy: new iam.ServicePrincipal("iot.amazonaws.com"),
      description: "IAM Role that allows IoT Core to update a Tracker",
      inlinePolicies: {
        allowTracker: new iam.PolicyDocument({
          statements: [
            new iam.PolicyStatement({
              resources: [
                `arn:aws:geo:${cdk.Stack.of(this).region}:${
                  cdk.Stack.of(this).account
                }:tracker/tracker_location_workshop`,
              ],
              actions: ["geo:BatchUpdateDevicePosition"],
            }),
          ],
        }),
      },
    });

    // Create an IoT Topic Rule that will send the location updates to Location Service
    const topicRule = new iot.CfnTopicRule(this, "TopicRule", {
      ruleName: "assetTrackingRule",
      topicRulePayload: {
        sql: `SELECT * FROM 'iot/trackedAssets'`,
        awsIotSqlVersion: "2016-03-23",
        actions: [
          {
            location: {
              deviceId: "${deviceID}",
              latitude: "${longitude}",
              longitude: "${latitude}",
              roleArn: role.roleArn,
              timestamp: {
                value: "${timestamp()}",
                unit: "MILLISECONDS",
              },
              trackerName: "tracker_location_workshop",
            },
          }
        ],
      },
    });
  }
}
```

### Possible Solution

Change the type to the correct one.

### Additional Information/Context

Adding this manual override to the resource allows to deploy correctly, proving that the resource is mistyped in CDK:
```ts
topicRule.addOverride("Properties.TopicRulePayload.Actions.0", {
      Location: {
        DeviceId: "${deviceID}",
        Latitude: "${longitude}",
        Longitude: "${latitude}",
        RoleArn: role.roleArn,
        Timestamp: {
          Value: "${timestamp()}",
          Unit: "MILLISECONDS",
        },
        TrackerName: "tracker_location_workshop-ok",
      },
    });
```

### CDK CLI Version

2.41.0

### Node.js Version

16.15.0

### OS

Linux / macOS

### Language

Typescript

**Comment by peterwoodworth** [comment]
Thanks for reporting this @dreamorosi,

This has been recently added to our cfnspec and the cfnspec itself looks good, so I think the issue is that we are messing up the conversion from the spec to the type. I wonder if this is because we have Timestamp as a Primitive Type in the Cfnspec, this could be overriding something somewhere? https://github.com/aws/aws-cdk/blob/74318c7d22bfc00de9e005f68a0a6aaa58c7db39/packages/%40aws-cdk/cfnspec/lib/schema/base-types.ts#L12

**Comment by sthuber90** [comment]
@peterwoodworth I'd be happy to take over or support in fixing this. I assume removing the Timestamp from the primitive types is not an option? 😅 Can you help me and tell me how the files in packages/aws-cdk-lib/aws-iot/lib get build?

**Comment by peterwoodworth** [comment]
I don't think I know how we _should_ fix this - but I can provide you with some direction to get the ball rolling on fixing this 🙂 

> I assume removing the Timestamp from the primitive types is not an option?

Correct, this will not be the way to go.

Our Cfn resources get built based off the CfnSpec. We ingest this specification file, and create types and classes from it which model the actual CloudFormation resources. We split up the spec [by each service](https://github.com/aws/aws-cdk/tree/main/packages/%40aws-cdk/cfnspec/spec-source/specification/000_cfn/000_official). What you see here is basically what you're going to get, but you can see [in this folder](https://github.com/aws/aws-cdk/tree/main/packages/%40aws-cdk/cfnspec/spec-source/specification/000_cfn) we have a bunch of patches that override the specification before we start creating classes and types based on the spec. I anticipate that we _could_ fix this by slightly renaming the Timestamp associated with Iot through a patch file - however I don't have a better solution. Maybe someone else from the team, or you might have one 🙂

**Comment by sthuber90** [comment]
The overall problem seems to be that here the complex and primitive types get mixed. 
https://github.com/aws/aws-cdk/blob/a0ad49df7b2536d800b4890ae0116e6ce26e6c55/tools/%40aws-cdk/cfn2ts/lib/spec-utils.ts#L77

Therefore, we can no longer differentiate between a timestamp reflecting a date and a timestamp as a complex type, such as it is the case here. 

After some testing it seems that this would require a very big rewrite which I'm not able to do myself. Therefore, I'm following @peterwoodworth's approach and try to patch the resource.
