### ISSUE TITLE
CDK Event Rule Target: Cannot set EventRule Target to Lambda Alias

### ISSUE THREAD

**Issue by sowston** [aws/aws-cdk#22736]
### Describe the bug

Please reopen : https://github.com/aws/aws-cdk/issues/12522

This issue is not resolved. I have attempted the following:
const eventTarget = new awsEventsTargets.LambdaFunction(lambdaAlias, { event: awsEvents.RuleTargetInput.fromObject(meetingSyncEvent) });

This still targets the lambda and not the alias.

I have also attempting trying to set an "alias" Property of the EventRule using the methodology suggested above:

lambda_event_rule = _events.Rule( self, id=args["rule_name"], event_bus=_events.EventBus.from_event_bus_name(scope=self, id=args["event_bus_id"], event_bus_name=args["event_bus_name"]), rule_name=args["rule_name"], event_pattern=args["event_rule_patterns"][0], targets= [_targets.LambdaFunction(self.function, max_event_age=Duration.hours(2), retry_attempts=2 )], alias=self.alias.fromAliasAttributes() )
The rule gets created but never sets the "configure version/alias Option of the Rule, it still is generated as "Default" option.

The event rule will trigger, but the lambda is never invoked. If I manually change the alias rule option to the name of the alias in the UI, the rule will then invoke the lambda.

The request is is to please enable the "version" and/or "alias" options above as requested and please provide a working code sample.

### Expected Behavior

I expect to be able to set the alias and/or version properties of the Event Rule and the Event rule will be created targeting the appropriate lambda version or alias.

### Current Behavior

The event rule always targets the latest version of the lambda.

### Reproduction Steps

lambda_event_rule = _events.Rule(
                self,
                id=args["rule_name"],
                event_bus=_events.EventBus.from_event_bus_name(scope=self, id=args["event_bus_id"], event_bus_name=args["event_bus_name"]),
                rule_name=args["rule_name"],
                event_pattern=args["event_rule_patterns"][0],
                targets= [_targets.LambdaFunction(self.function,
                            max_event_age=Duration.hours(2),
                            retry_attempts=2
                )],
                alias=self.alias.fromAliasAttributes()
            )

### Possible Solution

add the:

version
alias

properties to the Rule.  If either is set, use them to set the rules Lambda "configure version/alias" property

### CDK CLI Version

2

### Framework Version

python

### Node.js Version

13

### OS

Mac

### Language

Python

### Language Version

3.7.3

**Comment by mascur** [comment]
Hi @sowston, if you want to target a version/alias of a lambda function with the rule then you'll need to pass in the version/alias instead of the function itself. I've changed the code you've provided to show what I mean. Notice instead of `self.function` you would use `self.alias`. You could also use a version.

```python3
lambda_event_rule = _events.Rule(
    self,
    id=args["rule_name"],
    event_bus=_events.EventBus.from_event_bus_name(scope=self, id=args["event_bus_id"],             
    event_bus_name=args["event_bus_name"]),
    rule_name=args["rule_name"],
    event_pattern=args["event_rule_patterns"][0],
    targets= [
        _targets.LambdaFunction(self.alias, max_event_age=Duration.hours(2), retry_attempts=2)
    ]
)
```

**Comment by affanc** [comment]
Hi @mascur Cx came back and they said, This does NOT work.  If I target the alias, the created lambda STILL targets the lambda, not the alias.  I can never get it to target the alias.

**Comment by affanc** [comment]
Hi @mascur I do not have a reproducible code for testing

**Comment by mascur** [comment]
Hi @affanc,

The solution/workaround I provided above works as expected. Where are you seeing the created lambda target the lambda and not the alias? Have you checked eventbridge on the console to see what arn the rule is targeting? I would need reproducible code in order to further assist you.

**Comment by affanc** [comment]
@mascur Here is the code Cx have shared with me on the Support case, i hope this works for testing purposes

if "create_event_rules" in args:
            # there is a bug that the alias cannot be properly targeted
            # I have sumbitted the following issue: https://github.com/aws/aws-cdk/issues/22736 
            # TODO: implement a resolution to this when a resolution is provided
            ev_function = self.alias if self.has_alias else self.function
            lambda_event_rule = _events.Rule(
                self,
                id=args["rule_name"],
                event_bus=_events.EventBus.from_event_bus_name(scope=self, id=args["event_bus_id"], event_bus_name=args["event_bus_name"]),
                rule_name=args["rule_name"],
                event_pattern=args["event_rule_patterns"][0],
                targets= [_targets.LambdaFunction(ev_function,
                            max_event_age=Duration.hours(2),
                            retry_attempts=2
                )],
                alias=self.alias.fromAliasAttributes()
            )

**Comment by peterwoodworth** [comment]
You're specifying `ev_function` inside the `LambdaFunction`. you need to specify the alias here if you want to target the alias. Also, there's no `alias` property on the Rule construct
