### ISSUE TITLE
aws-certificatemanager: DnsValidatedCertificate docs say that the default validation method is email

### ISSUE THREAD

**Issue by plumdog** [aws/aws-cdk#22739]
### Describe the issue

Documentation for the props for`DnsValidatedCertificate` say:

> validation?
>
> Type: [CertificateValidation](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_certificatemanager.CertificateValidation.html) (optional, default: CertificateValidation.fromEmail())
>
> How to validate this certificate.

which is obviously wrong, because its DNS validated.

I think this is just because `interface DnsValidatedCertificateProps extends CertificateProps`, and presumably this is a reasonable option in `CertificateProps`.

Solutions I can think of:
- use some `Omit<>` to remove `validation` from `DnsValidatedCertificateProps`
- set `validation: never` on `DnsValidatedCertificateProps`
- factor out some `BaseCertificateProps` from `CertificateProps` that doesn't include `validation` and have `DnsValidatedCertificateProps` extend that instead.

### Links

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_certificatemanager.DnsValidatedCertificate.html#validation

**Comment by peterwoodworth** [comment]
The documentation is generated from our codebase - the line which this is coming from is here https://github.com/aws/aws-cdk/blob/4c11af6067b35125781aa590bb33c7990078d1ed/packages/%40aws-cdk/aws-certificatemanager/lib/certificate.ts#L77

As far as I can tell the validation prop isn't needed at all on `DnsValidatedCertificate`, it would be nice to not have props that do nothing. I think your third proposed solution would work well if it doesn't break anything 🙂 

> factor out some BaseCertificateProps from CertificateProps that doesn't include validation and have DnsValidatedCertificateProps extend that instead.

I am marking this issue as p2, which means that we are unable to work on this immediately.

We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://cdk.dev) to solicit support for reprioritization.

Check out our [contributing guide](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) if you're interested in contributing yourself - there's a low chance the team will be able to address this soon but we'd be happy to review a PR 🙂

**Comment by plumdog** [comment]
@peterwoodworth have had a go at this in #22809

**Comment by madeline-k** [comment]
This has been addressed by https://github.com/aws/aws-cdk/pull/21982. Please open a new issue, if there is still documentation or features missing from the new construct: https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_certificatemanager.Certificate.html
