### ISSUE TITLE
Add context parameter and PermissionBoundary aspect

### ISSUE THREAD

**Issue by corymhall** [aws/aws-cdk#22745]
Add a new context variable that the user can set with the permission boundary name. We can then use that value to apply the permission boundary (using Aspects).

cdk.json

```json
{
  "context": {
    "@aws-cdk/core:permissionBoundaryName": "my-permission-boundary"
  }
}
```

Apply the permission boundary somewhere based on a context variable. This should take stages into account. For example, the user may need to apply different permissions boundaries based on the stage. 

```ts
const pbName = stack.node.tryGetContext('@aws-cdk/core:permissionBoundaryName');
if (pbName) {
    iam.PermissionBoundary.of(stack).apply(
        iam.ManagedPolicy.fromManagedPolicyName(stack, 'PermissionBoundary', pbName);
    );
} 
```

**Comment by constantintaivan** [comment]
Hi @corymhall 

I'm following the above setup but the deployment (cdk deploy) does not work.
I have installed on Windows the latest version for CDK and AWS CLI. 
Bootstrapping was fixed and deployed successfully by using this resource: https://aws.amazon.com/blogs/mt/how-to-deploy-cdk-v2-to-an-account-that-requires-boundary-policies/

e.g.,
 const boundary = iam.ManagedPolicy.fromManagedPolicyArn(this, 'Boundary', 'arn:aws:iam::xxx:policy/DenyServicesSecurityStuff-policy');
iam.PermissionsBoundary.of(this).apply(boundary)

Error: 

MyTask/TaskRole (MyTaskTaskRole560858C4) Encountered a permissions error performing a tagging operation, please add required tag permissions. See https://repost.aws/knowledge-center/cloudformation-tagging-permission-error for how to resolve. Resource handler returned message: "User: arn:aws:sts::xxx:assumed-role/cdk-hnb659fds-cfn-exec-role-xx-eu-central-1/AWSCloudFormation is not authorized to perform: iam:CreateRole on resource: arn:aws:iam::xxx:role/SqsFargateServiceStack-MyTaskTaskRole560858C4-CUjtntvC38J4 with an explicit deny in a permissions boundary (Service: Iam, Status Code: 403, Request ID: 52393d51-805e-4bee-86d8-a49072c0f03e)"

Thanks
Constantin
