### ISSUE TITLE
(cloudfront): (custom originId handling issue for multiple behaviours with same origin)

### ISSUE THREAD

**Issue by patricksuter** [aws/aws-cdk#22758]
### Describe the bug

When setting custom `originId`s for CloudFront origins und the new `Distribution` construct there is an issue when using the same origin for multiple behaviours. The first behaviour uses the correct custom `originId` as `TargetOriginId` but every behaviour after that use the auto-generated `originId` instead of the correct custom `originId`.

### Expected Behavior

The custom `originId` is used for every usage of the origin in the behaviors in the `TargetOriginId` property.

### Current Behavior

Only the first behaviour using a given origin uses the correct custom `originId` in the `TargetOriginId` property. Every behaviour after that uses the auto-generated id.

### Reproduction Steps

Create origin with custom `originId` and use it in at least two behaviours. 

### Possible Solution

Prepared the following fix: https://github.com/aws/aws-cdk/pull/22756

### CDK CLI Version

2.50.0

### Node.js Version

v14.19.1

### OS

OSX

### Language

Typescript

**Comment by peterwoodworth** [comment]
Thanks for reporting and submitting a fix @patricksuter, we'll try to take a look at your PR soon
