### ISSUE TITLE
(aws_lambda ): DockerImageFunction.fromImageAsset fails to include image assets

### ISSUE THREAD

**Issue by mvs5465** [aws/aws-cdk#22770]
### Describe the bug

In a construct library repo, if you create a lambda function using `DockerImageFunction.fromImageAsset` and then run `npm run build`, neither the Dockerfile nor the lambda function code is included in the packaged lib directory.

If you then import and use this construct in a different repo, you get a file not found error as the Dockerfile and lambda function code is not present in the build directory (`lib`) of the construct library.

The error is:
```
Error: Cannot find image directory at /Path/to/my/repo/lib/function
```

### Expected Behavior

When running `npm run build` (or in my case `npx projen build`) the Dockerfile and Python files should be included in the "compiled" `lib` directory. 

### Current Behavior

The image assets are not included in the "compiled" `lib` directory and so when trying to use the construct in a stack results in a file-not-found error.

### Reproduction Steps

In my construct library repository I define a lambda function construct and reference a local directory containing the assets for the lambda function.
```
.
├── MyLambda.ts
└── function
    ├── Dockerfile
    ├── README.md
    ├── WorkerFunction.py
    └── requirements.txt
```

where in MyLambda.ts the lambda function is defined like this:

```
    const workerFunction = new lambda.DockerImageFunction(this, 'worker-function', {
      functionName: 'lambda_handler',
      code: lambda.DockerImageCode.fromImageAsset(path.join(__dirname, 'function'),
        {
          cmd: ['WorkerFunction.lambda_handler'],
          entrypoint: ['/lambda-entrypoint.sh'],
        }),
      memorySize: 128,
      role: assumeFunctionRole,
      timeout: Duration.seconds(60),
    });
```

However if you then run `npm run build` on this construct library, the following gets built into the `lib` directory and we can see that the Dockerfile, python code, requirements.txt, and README.md are all missing. 

```
    ├── MyLambda.d.ts
    └── MyLambda.js
```

Then you can attempt to use this construct in a different CDK project by linking them using npm:
```
cd ../my-other-repo
npm link ../my-construct-repo
```

Then if you attempt to reference the MyLambda construct and run `cdk synth myLambdaStack` you get a file-not-found error:

```
Error: Cannot find image directory at /Path/to/my/repo/lib/function
```

### Possible Solution

A possible solution that I haven't tried yet is separately defining the image separately using [ecr assets](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ecr_assets-readme.html) and then referencing ECR repo image/tag in the Lambda function construct using the `DockerImageFunction.fromEcr` method.

### CDK CLI Version

2.50.0 (build 4c11af6)

### Node.js Version

v16.14.0

### OS

MacOS Catalina 10.15.7

### Language

Typescript

### Language Version

TypeScript (4.8.4)

**Comment by mvs5465** [comment]
This is also happening to me using other local asset files, such as a yml file I am using to store a bunch of AWS Config rules. That setup worked when I previously had the construct in the same repository as my deployment stack, so I think this is probably something specific to how `npm link` works.

**Comment by pahud** [comment]
Hi @mvs5465 ,

Did you generate the construct lib repo with `projen`? This seems to be the behavior how projen builds and bundles assets into the lib directory?

**Comment by mvs5465** [comment]
Hi @pahud! Yes, I am using projen. Do you know if there is a way to use projen and still package assets?

**Comment by pahud** [comment]
@mvs5465  I am not very sure but AFAIK projen would compile and copy typescript files under src to lib and leave everything outsides of src untouched. I would prefer having the lambda directories out of src like this

```
.
├── LICENSE
├── README.md
├── cdk.context.json
├── lambda
│   └── index.py
├── package.json
├── src
│   └── main.ts
├── test
│   └── main.test.ts
├── tsconfig.dev.json
└── yarn.lock
```

And have your lambda function code assets path point to the upper lambda directory like:

```
code: lambda.DockerImageCode.fromImageAsset(path.join(__dirname, '../lambda'),
```

I hope this would be helpful but definitely worth a ticket in https://github.com/projen/projen/issues to bring their attention for recommended practice. As this issue is not related to AWS CDK I am closing it for now but feel free to reopen it if you think it is still relevant to AWS CDK.
