### ISSUE TITLE
cli: better indicate why a deployment couldn't be hotswapped

### ISSUE THREAD

**Issue by echeung-amzn** [aws/aws-cdk#22784]
### Describe the feature

When attempting a hotswap deployment, it can fail to do so and fallback to a full deployment with a message like:

```
Could not perform a hotswap deployment, as the stack <YourStackName> contains non-Asset changes
Falling back to doing a full deployment
```

However, it does not actually indicate _what_ the non-Asset changes are that are preventing a hotswap deployment from working. It can be quite challenging to grok through a stack to narrow down what the issue is.

Since there's [already logic to find the non-hotswappable changes](https://github.com/aws/aws-cdk/blob/69981ac07b40ce3f690f6c1ad0010b51f29103a6/packages/aws-cdk/lib/api/hotswap-deployments.ts#L95), it'd be nice if the CLI either outputted the list of resource by default, or behind a flag.

### Use Case

I'd love to use a hotswap deployment to save time when testing changes in a Lambda function's code assets. Having it fallback to full deployments every time introduces a frustrating amount of churn in the development cycle.

### Proposed Solution

Perhaps behind a verbose logging flag, be able to list out the non-hotswappable changes when a hotswap deployment is attempted but fails.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.46.0

### Environment details (OS name and version, etc.)

macOS 12.6 but not relevant

**Comment by peterwoodworth** [comment]
We will throw this when we detect a change in the template that is one of 

1. the removal or addition of a resource to the template
2. a resource had its type changed

If you encounter this error and then run `cdk diff` you should be able to find one of these quickly. But you're not wrong that we could be printing this information anyway.

I am marking this issue as p2, which means that we are unable to work on this immediately.

We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://cdk.dev) to solicit support for reprioritization.

Check out our [contributing guide](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) if you're interested in contributing yourself - there's a low chance the team will be able to address this soon but we'd be happy to review a PR 🙂

**Comment by rix0rrr** [comment]
@comcalvi is working on something that may also address this, assigning and cc'ing for visibility.
