### ISSUE TITLE
aws_cloudwatch.CompositeAlarm: Wrong details on argument type in add_*_action(*actions) methods

### ISSUE THREAD

**Issue by yairst** [aws/aws-cdk#22801]
### Describe the issue

In all 3 methods for adding action to `CompositeAlarm` the details on the type of the `*actions` argument are "Typically the ARN of an SNS topic or ARN of an AutoScaling policy". However, the required argument type should be `IAlarmAction`, as documented in the Parameters section. Hence, a suggested correction could be "Typically `SnsAcion` or `AutoScalingAction`".

### Links

[CompositeAlarm](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_cloudwatch/CompositeAlarm.html)
[add_alarm_action(*actions)](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_cloudwatch/CompositeAlarm.html#aws_cdk.aws_cloudwatch.CompositeAlarm.add_alarm_action)
[add_insufficient_data_action(*actions)](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_cloudwatch/CompositeAlarm.html#aws_cdk.aws_cloudwatch.CompositeAlarm.add_insufficient_data_action)
[add_ok_action(*actions)](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_cloudwatch/CompositeAlarm.html#aws_cdk.aws_cloudwatch.CompositeAlarm.add_ok_action)

**Comment by indrora** [comment]
That's correct, these should be clearly defined.
