### ISSUE TITLE
(aws-msk): addUser secrets with '\' in password breaks Lambda Kafka event source

### ISSUE THREAD

**Issue by pjoe** [aws/aws-cdk#22813]
### Describe the bug

When using `addUser` to create credentials for MSK cluster, it can happen that the generated secret has password with `\`. However this doesn't work with the Lambda Kafka event source. This is e.g. used when wanting to consume events from a different account as the native MSK event source currently doesn't work cross account.

### Expected Behavior

The generated secret password work with Lambda event source for Kafka

### Current Behavior

Lambda Kafka event source gives cryptic error because of password containing `\`

### Reproduction Steps

- Create MSK cluster with SASL/SCRAM authentication in account A
- Add credentials by calling `addUser`
- Share generated secret and KSM key with account B
- In account B setup Lambda with Kafka event source using shared secret

### Possible Solution

Would be good to default the secret generated to exclude `\`, but could also make sense to expose parameters giving more control over the secret or return the secret(s) from `addUser` for further customization.

### CDK CLI Version

2.50.0

### Framework Version

2.47.0-alpha.0

### Node.js Version

v16.17.1

### OS

macos

### Language

Typescript

**Comment by pjoe** [comment]
Also noticed issues with other characters: `/` and `"`

**Comment by peterwoodworth** [comment]
@pjoe I'm interested in how/why you know that there's an issue with these particular characters. Is there some documentation or error message you found that describes this limitation?

**Comment by pjoe** [comment]
@peterwoodworth had this reported from a customer and then validated by experimenting. The error shows up on the Lambda Self Managed Kafka trigger as either: "PROBLEM: SASL authentication failed." or "PROBLEM: Lambda internal error. Please contact Lambda customer support."

Been trying out different character combinations by editing the Secret in the console and then disabling/re-enabling the trigger. Not 100% sure which combination of special characters trigger the issue, but seen it with at least `"`, `/` and `\`.

Might also be good to expose options for the generated secret, but guessing that could be a breaking change, maybe something like:
```typescript
public addUser(secretStringGenerator secretmanager.SecretStringGenerator={},
    ...usernames: string[]): secretsmanager.Secret[]
```

**Comment by zabrip** [comment]
This is no longer an issue, Lambda now correctly encodes the credentials so special characters work as expected

**Comment by khushail** [comment]
> This is no longer an issue, Lambda now correctly encodes the credentials so special characters work as expected
@pjoe , could you please confirm what has been mentioned by @zabrip ?
