### ISSUE TITLE
stepfunctions-tasks: Add documentation and validation for `PutEvents`

### ISSUE THREAD

**Issue by arcrank** [aws/aws-cdk#22822]
### Describe the issue

Eventbridge PutEvents API has a fairly conservative limit of 10 events per invocation.  I noticed that in CDK we do not have any documentation nor validation on this.

Here is the relevant API information: https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_PutEvents.html#API_PutEvents_RequestSyntax

I am proposing that the documentation be updated, and just wanted to confirm that validation is not possible since these events do not necessarily exist at build time.  Although for those cases, we could check the length of the list just in case.  Please let me know thoughts and I can draft a PR if appropriate.

### Links

https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_PutEvents.html#API_PutEvents_RequestSyntax

**Comment by indrora** [comment]
This seems outside the scope of the CDK; can you provide a situation where the CDK would create CloudFormation templates which cause a single batch if >10 events to be added by a single API call? 

I don't think the CDK calls `EventBridge:PutEvents`, for that matter.

**Comment by arcrank** [comment]
Not sure I follow, the cdk construct takes in a list for `entries`, and iterates over it.  The API in general takes a list.  You could add check [here](https://github.com/aws/aws-cdk/blob/97e3c5957e2bb087aac99be862497ebcfe6d7831/packages/%40aws-cdk/aws-stepfunctions-tasks/lib/eventbridge/put-events.ts#L148) where it's checking if it's empty.

**Comment by peterwoodworth** [comment]
@indrora customers can frequently encounter scenarios like this, and it is [definitely something we should document when possible](https://github.com/aws/aws-cdk/pull/22154)

@arcrank we won't want to make a check in the code in case customers increase their limit (haven't checked if that's possible for this limit), or the limit might change forcing us to update the code (probably late) which is a maintaining cost not worth what it provides. We've included checks in the code previously and had customers be blocked by these overly restrictive checks that might not apply to every scenario
