### ISSUE TITLE
aws-msk-alpha: Invalid Monitoring Level

### ISSUE THREAD

**Issue by timcosta** [aws/aws-cdk#22837]
### Describe the bug

https://github.com/aws/aws-cdk/blob/4c11af6067b35125781aa590bb33c7990078d1ed/packages/%40aws-cdk/aws-msk/lib/cluster.ts#L200 states that there's a monitoring level called `PER_TOPIC_PER_PARTITION` however that is not a supported value in the Cfn docs https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-msk-cluster.html#cfn-msk-cluster-enhancedmonitoring

### Expected Behavior

I expected `PER_TOPIC_PER_PARTITION` to not be available if it wasnt a valid option.

### Current Behavior

Setting to `PER_TOPIC_PER_PARTITION` was accepted and appeared to be applied, but had no effect.

### Reproduction Steps

```typescript
this.cluster = new mskAlpha.Cluster(this, 'Default', {
      clusterName: Names.uniqueResourceName(this, {
        maxLength: 64,
      }),
      kafkaVersion: KafkaVersion.V2_8_1,
      ...snip...
      monitoring: {
        clusterMonitoringLevel: mskAlpha.ClusterMonitoringLevel.PER_TOPIC_PER_BROKER,
      },
    });
```

the above construct compiles and deploys, but monitoring is not enabled and there's no error/messaging about why.

### CDK CLI Version

2.47.0

### Node.js Version

14 LTS

### OS

MacOS

### Language

Typescript

### Language Version

4.3.5

**Comment by peterwoodworth** [comment]
I'm not able to reproduce this @timcosta, when I set the monitoring configuration, I can see that it is set to the appropriate setting no matter which setting I set it to, including `PER_TOPIC_PER_PARTITION`. This is just not documented in CloudFormation (feel free to submit a feedback button on that cloudformation docs page!), it works perfectly fine.
<img width="675" alt="Screen Shot 2022-11-11 at 4 15 31 PM" src="https://user-images.githubusercontent.com/44349620/201446784-a6889625-7814-404f-b56a-078a39b92c92.png">
