### ISSUE TITLE
(core): corssRegionReferences weak reference

### ISSUE THREAD

**Issue by Tietew** [aws/aws-cdk#22842]
### Describe the feature

corssRegionReferences is awesome feature.

I want a *weak* reference which can be updated or deleted even if it's used.

### Use Case

Lambda@Edge requires Version ARN which is modified when the code is modified.

When I use crossRegionReferences with Lambda@Edge, updating code is rejected by ExportsWriter:
> Exports cannot be updated: at throwIfAnyInUse

Example stacks:

``` ts
#!/usr/bin/env node
import 'source-map-support/register';
import * as cdk from 'aws-cdk-lib';
import * as lambda from 'aws-cdk-lib/aws-lambda'
import * as nodejs from 'aws-cdk-lib/aws-lambda-nodejs'

const app = new cdk.App();
const us = new cdk.Stack(app, 'CdkTest1', {
  env: { account: process.env.CDK_DEFAULT_ACCOUNT, region: 'us-east-1' },
  crossRegionReferences: true,
});
const ja = new cdk.Stack(app, 'CdkTest2', {
  env: { account: process.env.CDK_DEFAULT_ACCOUNT, region: 'ap-northeast-1' },
  crossRegionReferences: true,
});

// Lambda@Edge function in us-east-1
const func = new nodejs.NodejsFunction(us, 'Func', {
  entry: 'lib/func.ts',
  currentVersionOptions: { removalPolicy: cdk.RemovalPolicy.RETAIN },
});

// CloudFront distribution in ap-northeast-1
new cdk.CfnOutput(ja, 'FuncArn', {
  value: func.currentVersion.edgeArn,
});
```

When `lib/func.ts` is not modified, the stack CdkTest2 will be updated successfully.

When `lib/func.ts` is modified, `func.currentVersion` is modified.
The deployment of CdkStack1 (us-east-1) will be failed.

### Proposed Solution

Skip check in ExportsWriter when weak reference.

ALL cross-region exports are weak:
```ts
new Stack(app, 'ExportStack', { crossRegionWeakReferences: true });
```

Only specific resources are weak:
```ts
class ExportStack extends Stack {
  constructor(...) {
    const func = new lambda.Function(this, ...);
    this.weakReference(func);
  }
}
```

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.50.0

### Environment details (OS name and version, etc.)

Linux

**Comment by rix0rrr** [comment]
Good call! Thanks for testing it out! We'll have to noodle a bit on how this is going to integrate into a bigger proposal for weak references, but we'll get back to it.

**Comment by MrArnoldPalmer** [comment]
Closing as a duplicate, we are tracking this in the RFC here https://github.com/aws/aws-cdk-rfcs/issues/82
