### ISSUE TITLE
CodeBuild: when linking existing IAM roles with codebuild steps/stages no error is returned for existing policies with the same name

### ISSUE THREAD

**Issue by vsarris** [aws/aws-cdk#22840]
### Describe the bug

I have two cloudformation stacks that create codepipeline pipelines defining codebuild actions that are performed by the same IAM role.
My stacks are created through the python cdk 2.X

the one stack links an existing IAM role declared like this to a aws_codebuild.PipelineProject
`        
code_build_role = iam.Role.from_role_arn(self, "CodeBuildRole", "arn:aws:iam::"+account_id+":role/MyRoleWhatever")
`

And the other stack similarly links the same role to a aws_cdk.pipeline.CodeBuildStep
`        
        cicd_role = iam.Role.from_role_arn(self, "CodeBuildRole",
                               "arn:aws:iam::" + account_id + ":role/MyRoleWhatever")`

So the cloudformation template file created creates for the first stack something like this
`
{
 "Resources": {
  "CodeBuildRolePolicy0442214A": {
   "Type": "AWS::IAM::Policy",
  ...
`
and for the second one again
`
{
 "Resources": {
  "CodeBuildRolePolicy0442214A": {
   "Type": "AWS::IAM::Policy",
....
`

This had as a result that the existing IAM role had attached the same policy by the two stacks so the latest generated stack creation would replace the first applied policy.

**Ofc** I can pick different names which is a solution I could do when I found this issue(didn't figure out the exact issue early enough so I have just created a copy role for the latter stack) 
The issue is that for example if you create different stacks that define the same name for pipelines you have an error saying  that the pipeline exists so you know you have to change it.

The same issue would have happen for this case: The `cdk deploy` should tell you `this IAM role has already this policy defined.`

### Expected Behavior

When trying to create resources with `cdk deploy` and attaching a policy with the same name to an existing IAM role it should warn you or throw an error saying `this policy with this name already exists` so that you know and change it/fix it.

### Current Behavior

IAM roles declared in the cdk code with the same name in different stacks produce the same policy name and when the resources are created with a cdk deploy the last policy is the one that remains in the role.

### Reproduction Steps

 
       code_build_role = iam.Role.from_role_arn(self, "CodeBuildRole", "arn:aws:iam::"+account_id+":role/MyRoleWhatever")
            project_dev_deploy = aws_codebuild.PipelineProject(self, "job_dev",
                                                           project_name="job_dev",
                                                           build_spec=codebuild.BuildSpec.from_source_filename("buildspec.yml"),
                                                           role=code_build_role,
                                                           environment={
                                                                "build_image": codebuild.LinuxBuildImage.STANDARD_5_0,
                                                                "privileged": True
                                                            }
                                                           )
     
        deploy_dev_action = codepipeline_actions.CodeBuildAction(
            action_name="BuildCopyJar",   
            project=project_dev_deploy,
            input=source_artifact, 
            execute_batch_build=False,
            variables_namespace = 'DevVariables'
        )

And in another stack

        cicd_role = iam.Role.from_role_arn(self, "CodeBuildRole",
                               "arn:aws:iam::" + account_id + ":role/MyRoleWhatever")

        step= CodeBuildStep("Update with latest version production",
                             env={"SYNTH_BUCKET_NAME": bucket_name,
                                  "GIT_VERSION": git_version,
                                  "TYPE": pipeline_type,
                                  "BUILD_NO": build_no
                                  },
                             commands=[
                                       "echo $GIT_VERSION $TYPE $BUILD_NO > live_status",
                                       "aws s3 cp live_status s3://${SYNTH_BUCKET_NAME}/versions/live.status.PRODUCTION.txt --acl bucket-owner-full-control"],
                             role=cicd_role
                             )

### Possible Solution

I would throw an error if an IAM role has an existing policy with the same name as the one a cdk deployment tries to attach.

### CDK CLI Version

2.49.0 (build 793dd76)

### Node.js Version

v16.15.0

### OS

macos

### Language

Python

**Comment by peterwoodworth** [comment]
This appears to be the same issue as https://github.com/aws/aws-cdk/issues/23080, ping me if you disagree!

**Comment by vsarris** [comment]
Hey Peter indeed its the same :) thank you
