### ISSUE TITLE
aws-cognito: authSessionValidity listed in docs but not available on CfnUserPoolClient

### ISSUE THREAD

**Issue by papiro** [aws/aws-cdk#22868]
### Describe the bug

`authSessionValidity` is listed as a property for `CfnUserPoolClient` [in the CDK docs](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_cognito.CfnUserPoolClient.html#authsessionvalidity) but is not accounted for [in the code](https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/aws-cognito/lib/user-pool-client.ts#L209).

### Expected Behavior

Property should be accepted and used.

### Current Behavior

Property is not recognized.

### Reproduction Steps

Try to use the property in a new project.

### CDK CLI Version

2.50.0

### Node.js Version

16.17.0

### OS

MacOS

### Language

Typescript

**Comment by papiro** [comment]
Same issue as #22854

**Comment by peterwoodworth** [comment]
Closing this out as a duplicate, thanks for reporting!
