### ISSUE TITLE
Cognito : UserPoolIdentityProvider Google only accepts client secret as String

### ISSUE THREAD

**Issue by saleco** [aws/aws-cdk#22872]
### Describe the feature

Hello guys,
Would be nice to have the possibility to set client secret using SecretValue on UserPoolIdentityProvider

### Use Case

When creating an user pool identity provider for Google I got the error below when deploying cdk.

Error: Resolution error: Resolution error: Resolution error: Synthing a secret value to Resources/${Token[EmployeeBenefitsDashboardCdkStackDev.BenefitsAPIDev.BenefitsUserPoolIdentityProvider.Resource.LogicalID.292]}/Properties/providerDetails/client_secret. Using a SecretValue here risks exposing your secret. Only pass SecretValues to constructs that accept a SecretValue property, or call AWS Secrets Manager directly in your runtime code. Call 
'secretValue.unsafeUnwrap()' if you understand and accept the risks..

### Proposed Solution

Change current client secret data type to SecretValue

### Acknowledgements

- [x] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### CDK version used

2

### Environment details (OS name and version, etc.)

Windows 11

**Comment by peterwoodworth** [comment]
Hey @saleco, thanks for the feature request. I think it makes sense to pass in a `SecretValue` here.

We can implement this pretty easily by making sure to unwrap the secret here after converting the prop to a SecretValue. https://github.com/aws/aws-cdk/blob/4c11af6067b35125781aa590bb33c7990078d1ed/packages/%40aws-cdk/aws-cognito/lib/user-pool-idps/google.ts#L46

However, this would be a breaking change if we were to change the type of `clientSecret` from a string to a `SecretValue`. If we are to change this, it would need to be by deprecating the old prop and/or implementing a feature flag.

Currently, before we allow you to directly pass in a SecretValue, you can use `SecretValue.unsafeUnwrap()` to pass the secret in to `clientSecret`. This is likely what would end up being done under the hood anyway 🙂 

I am marking this issue as p2, which means that we are unable to work on this immediately.

We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://cdk.dev) to solicit support for reprioritization.

Check out our [contributing guide](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) if you're interested in contributing yourself - there's a low chance the team will be able to address this soon but we'd be happy to review a PR 🙂

**Comment by saleco** [comment]
Hi @peterwoodworth, thanks for the advice.
I have created the [PR ](https://github.com/aws/aws-cdk/pull/22885) but I'm struggling to accomplish the integration test snapshot step. 
Any help would be appreciated.
