### ISSUE TITLE
CLI: Add progress info to CDK deploy command

### ISSUE THREAD

**Issue by AlexGurtoff** [aws/aws-cdk#22879]
### Describe the feature

Add place in the order of the stack that’s currently being deployed, like `StackName Deploying... [4/45]` to `cdk deploy` command

### Use Case

Currently, this is hard to define how many stacks remain to the app will be fully deployed. For example, we have more than 50 stacks in our app, and the deployment process takes 60-180 minutes, so, if you don't remember the exactly deploy order of CDK it is impossible to know how many stacks are left to estimate the remaining time properly

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.50.0

### Environment details (OS name and version, etc.)

MacOs 12.4

**Comment by peterwoodworth** [comment]
Thanks for the FR and PR @AlexGurtoff, it's always nice to make things more clear in the CLI 🙂 We will try to take a look at the PR when we can!
