### ISSUE TITLE
CLI: Add deploy order info before deploying stacks

### ISSUE THREAD

**Issue by AlexGurtoff** [aws/aws-cdk#22882]
### Describe the feature

Add the sorted list of stacks which will be deployed. Example:
```
Deploy order:
1 - StackA
2 - StackB
3 - StackC
4 - StackE
...
```

### Use Case

It is difficult to determine when a particular stack will be deployed without knowing the deployment order. This can be useful when you need to instantly test a newly deployed feature while the deployment of the entire application is still ongoing.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.50.0

### Environment details (OS name and version, etc.)

MacOs 12.4

**Comment by peterwoodworth** [comment]
This would be nice to have too @AlexGurtoff, Thanks for these ideas to improve our CLI output

**Comment by mrgrain** [comment]
`cdk list` already displays stack in order of deployment.
