### ISSUE TITLE
aws-apprunner-alpha: Incorrect validation of length for AccessRoleArn

### ISSUE THREAD

**Issue by newbeb** [aws/aws-cdk#22888]
### Describe the bug

When creating a stack with the app-runner alpha constructs, the SourceConfiguration/AuthenticationConfiguration/AccessRoleArn length is being invalidated incorrectly (by CloudFormation). The maximum length is supposed to be 1024 [per the CloudFormation documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apprunner-service-authenticationconfiguration.html). The maximum length being allowed is 102 characters. It seems like someone forgot the 4 in the 1024 in the validation rule.

This only happens when the serviceName (generated or actual) is long and we are using a docker asset from a private ECR repository.

### Expected Behavior

The app-runner Service should have deployed cleanly without a validation error.

### Current Behavior

When deploying an AWS CDK stack with an apprunner Service with an id of 'apprunner-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' the following error is generated during deployment:

```
Deployment failed: Error: Stack Deployments Failed: Error: The stack named TestAppsyncStack failed to deploy: UPDATE_ROLLBACK_COMPLETE: Properties validation failed for resource apprunneraaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa98841DBD with message:
#/SourceConfiguration/AuthenticationConfiguration/AccessRoleArn: expected maxLength: 102, actual: 108
```

### Reproduction Steps

With a stack like the following:

```typescript
import * as cdk from 'aws-cdk-lib';
import { DockerImageAsset } from 'aws-cdk-lib/aws-ecr-assets';
import * as apprunner from '@aws-cdk/aws-apprunner-alpha';
import { CfnOutput } from 'aws-cdk-lib';

import { Construct } from 'constructs';

export class TestAppsyncStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    let dockerAsset = new DockerImageAsset(this, "app-docker-asset", {
      directory: __dirname
    })

    let appRunner = new apprunner.Service(this, 'apprunner-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', {
      source: apprunner.Source.fromAsset({
        imageConfiguration: { port: 3000 },
        asset: dockerAsset,
      }),
    });
    new CfnOutput(this, "apprunner-url", {
      value: appRunner.serviceUrl
    })

  }
}
```

### Possible Solution

I think this will need to be a bug filed against the appsync team building out the CloudFormation resource providers to fix the validation logic at the CloudFormation level.

The workaround is making sure that the appsync Service name is short.

### CDK CLI Version

2.50.0 (build 4c11af6)

### Framework Version

2.50.0

### Node.js Version

v16.17.0

### OS

macos

### Language

Typescript

### Language Version

TypeScript (4.8.4)

**Comment by peterwoodworth** [comment]
I wasn't able to reproduce this @newbeb, but I don't doubt you ran into it.

There's a few ways we can move forward:

a) Share a stack arn here which reproduced this error, and I can report it internally.

b) provide a _full_ reproduction which will work in any arbitrary account (just copy+paste, clone, etc)

c) Report to premium support yourself if you have it

**Comment by peterwoodworth** [comment]
Service has reported this was fixed!
