### ISSUE TITLE
(Aspects): Limited when constructs render with Lazy

### ISSUE THREAD

**Issue by deuscapturus** [aws/aws-cdk#22902]
### Describe the bug

Aspect applications are limited when Construct tree values are of type Lazy.any().  Aspects run during the prepare phase, but Lazy.any() runs later during the synth phase.

The Aspect that I am working on is meant to modify a ecs [ContainerDefinition](https://github.com/aws/aws-cdk/blob/280b876d426522fd043f13ff0b188e29acaa0fbf/packages/%40aws-cdk/aws-ecs/lib/base/task-definition.ts#L454) `entryPoint` and `command`, to wrap them with security monitoring tooling.  The problem: When the Aspect visits the `CfnTaskDefinition` the value of `containerDefinitions` is Lazy.any() and cannot be modified.  A possible solution would be to mutate a public non-private property of the construct, which would then be read by the Lazy function, but this [is frowned upon](https://github.com/aws/aws-cdk/pull/22871#pullrequestreview-1178236768) for reasons I do not understand :shrug: 

It seems that Lazy values are untouchable by Aspect applications, which shouldn't be the case.

Is there another solution I do not see?  Why must construct properties be private?

### Expected Behavior

It should be possible to modify values rendered with Lazy.any() in Aspect applications.

### Current Behavior

By convention, construct properties are private which is the only path to modifying values rendered with Lazy.any()

### Reproduction Steps

See integration test:
https://github.com/aws/aws-cdk/pull/22871/files#diff-79248b315d8a5e21d820caa64ec5b678532d5c5ce26b0f31d8350aa1ed78ae7c

### Possible Solution

Allow construct properties to be public when they are read by Lazy.
https://github.com/aws/aws-cdk/pull/22871

### CDK CLI Version

2.43.1

### Node.js Version

v16.14.0

### OS

Linux

### Language

Typescript

**Comment by corymhall** [comment]
@deuscapturus you can `resolve` the tokens yourself inside the aspect. For example, to accomplish your specific use case you should be able to do something like.

```ts
    Aspects.of(this).add({
      visit(node: IConstruct) {
        if (node instanceof ecs.TaskDefinition) {
          const cfnTaskDef = (node.node.defaultChild as ecs.CfnTaskDefinition);
          const containerDefs = cfnTaskDef.containerDefinitions;
          const resolvedContainerDefs = cdk.Stack.of(node).resolve(containerDefs) as ecs.CfnTaskDefinition.ContainerDefinitionProperty[];
          cfnTaskDef.containerDefinitions = resolvedContainerDefs.map(def => {
            if (def.name === 'web') {
              return {
                ...def,
                entryPoint: ['/security-monitor', ...def.entryPoint ?? []],
                command: ['/security-monitor', ...def.command ?? []],
              }
            }
            return def;
          })
        }
      }
    });
```

**Comment by deuscapturus** [comment]
This works.  Thank you
