### ISSUE TITLE
CfnKey: Unable to create key Policy for CfnKey & Replica Key

### ISSUE THREAD

**Issue by MetadelDes** [aws/aws-cdk#22909]
### Describe the bug

Unable to resolve Construct at keyPolicy/node

### Expected Behavior

Generation of policy for AWS::KMS::Key

### Current Behavior

Currently getting the following error as part of the cdk synth process when I try to create principal and replica key.

Example code can be found here: https://github.com/MetadelDes/aws-cdk-keypolicy/tree/testing 

Error:                      ^
Error: Resolution error: Resolution error: Trying to resolve() a 
Construct at /Resources/${Token[cdk-stack.MyCfnReplicaKey.LogicalID.365]}/Properties/keyPolicy/node..
    at resolve (C:\personal project\aws-cdk-keypolicy\node_modules\aws-cdk-lib\core\lib\private\resolve.js:1:2754)
    at Object.resolve (C:\personal project\aws-cdk-keypolicy\node_modules\aws-cdk-lib\core\lib\private\resolve.js:1:1121)
    at resolve (C:\personal project\aws-cdk-keypolicy\node_modules\aws-cdk-lib\core\lib\private\resolve.js:1:2925)
    at Object.resolve (C:\personal project\aws-cdk-keypolicy\node_modules\aws-cdk-lib\core\lib\private\resolve.js:1:1121)
    at resolve (C:\personal project\aws-cdk-keypolicy\node_modules\aws-cdk-lib\core\lib\private\resolve.js:1:2925)
    at Object.resolve (C:\personal project\aws-cdk-keypolicy\node_modules\aws-cdk-lib\core\lib\private\resolve.js:1:1121)
    at RememberingTokenResolver.resolveToken (C:\personal project\aws-cdk-keypolicy\node_modules\aws-cdk-lib\core\lib\resolvable.js:1:1279)
    at RememberingTokenResolver.resolveToken (C:\personal project\aws-cdk-keypolicy\node_modules\aws-cdk-lib\core\lib\private\resolve.js:1:4058)
    at resolve (C:\personal project\aws-cdk-keypolicy\node_module

### Reproduction Steps

1) Clone Repo
2) npm install OR yarn
3) cdk synth

### CDK CLI Version

2.40.0

### Framework Version

2.40.0

### Node.js Version

v16.13.0

### OS

Microsoft Windows 10 enterprise 

### Language

Typescript

### Language Version

4.6.3

**Comment by peterwoodworth** [comment]
Hey @MetadelDes,

This error is occurring when you are creating the `CfnReplicaKey`. Here is the code you have in your repo:

```ts
      new CfnReplicaKey(this, 'MyCfnReplicaKey', {
        keyPolicy: policy,
        primaryKeyArn: key.attrArn,
      });
```

The `keyPolicy` parameter wants you to pass in json, however you are currently passing in an L2 [Policy](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_iam.Policy.html) resource directly to the parameter.

The `CfnReplicaKey` isn't able to parse this L2 construct, and will need the policy statement directly. See [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kms-key.html#cfn-kms-key-keypolicy) for some examples on how to do this. 

Ping me if you have any more questions, thanks!

**Comment by MetadelDes** [comment]
@rix0rrr Thanks! is there a way to parse L2 policy resources to JSON? I wanted to build multiple policy methods based on allowed action and utilize them when needed in the code. Instead of hard coding all the action in the Json like this. 
{
    "Id": "key-consolepolicy-3",
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Enable IAM User Permissions",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::Account:root"
            },
            "Action": "kms:*",
            "Resource": "*"
        },
        {
            "Sid": "Allow access for Key Administrators",
            "Effect": "Allow",
            "Principal": {
                "AWS": [
                    "arn:aws:iam::account:role/role"
                ]
            },
            "Action": [
                "kms:Create*",
                "kms:Describe*",
                "kms:Enable*",
                "kms:List*",
                "kms:Put*",
                "kms:Update*",
                "kms:Revoke*",
                "kms:Disable*",
                "kms:Get*",
                "kms:Delete*",
                "kms:TagResource",
                "kms:UntagResource",
                "kms:ScheduleKeyDeletion",
                "kms:CancelKeyDeletion",
                "kms:ReplicateKey",
                "kms:UpdatePrimaryRegion"
            ],
            "Resource": "*"
        },
        {
            "Sid": "Allow use of the key",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::account:role/hhghg"
            },
            "Action": [
                "kms:Encrypt",
                "kms:Decrypt",
                "kms:ReEncrypt*",
                "kms:GenerateDataKey*",
                "kms:DescribeKey"
            ],
            "Resource": "*"
        },
        {
            "Sid": "Allow attachment of persistent resources",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::account:role/role"
            },
            "Action": [
                "kms:CreateGrant",
                "kms:ListGrants",
                "kms:RevokeGrant"
            ],
            "Resource": "*",
            "Condition": {
                "Bool": {
                    "kms:GrantIsForAWSResource": "true"
                }
            }
        }
    ]
}

**Comment by peterwoodworth** [comment]
You can output the entire policy document as json like so:

```
policy.document.toJSON()
```

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_iam.Policy.html#document-1
https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_iam.PolicyDocument.html#towbrjson
