### ISSUE TITLE
cdk cli synth: Erroneous error - CDK bootstrap stack version 6 required

### ISSUE THREAD

**Issue by mcqj** [aws/aws-cdk#22907]
### Describe the bug

When creating a very simple stack using `cdk init`, `cdk synth` fails with the error message shown below.

```
AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI
```

However, retrieving the version from parameter store shows bootstrap version 14.

`cdk deploy` does correctly deploy the stack, so the problem is only with synth.

### Expected Behavior

`cdk synth` should create Cloudformation template

### Current Behavior

'cdk synth` errors out, expecting a specific (and old) version of bootstrap.

### Reproduction Steps

Create a new stack with

```
cdk init app --language javascript
```

Bootstrap with

```
cdk bootstrap
```

Try to synthesize with

```
cdk synth
```

### Possible Solution

Update the version check in cdk synth

### CDK CLI Version

2.50.0

### Framework Version

2

### Node.js Version

16.18.0

### OS

Macos Monterey

### Language

Typescript

### Language Version

Using Javascript

**Comment by peterwoodworth** [comment]
Hey @mcqj,

I wasn't able to reproduce this following your reproduction steps. 

I suspect that because this is occurring during synth, that you might be performing some lookups such as `Vpc.fromLookup`. Are you making any lookup calls in your CDK application?

Additionally, can you verify the account + region you are synthesizing in, and make sure that that region is the region that has been bootstrapped with version 14?

**Comment by robin-cruk** [comment]
I have exactly this problem, using the stack generated with `cdk init -l typescript` from CDK v2.53.0. Node v18.12.1 on macOS Ventura 13.0.1.

Parameter Store has /cdk-bootstrap/xxx/version → 14, everything is in us-east-1

**Comment by kr0ggg** [comment]
I have also received this exact problem using **cdk version: 2.70.0 (build c13a0f1)** this week.  

I am just running the basic **_cdk init_** template stack as shown below.   **cdk deploy** works.

```
import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as sqs from 'aws-cdk-lib/aws-sqs';

export class CdkWorkshopStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    // The code that defines your stack goes here

    // example resource
     const queue = new sqs.Queue(this, 'CdkWorkshopQueue', {
       visibilityTimeout: cdk.Duration.seconds(300),
       queueName: 'AddSongQueue'
     });
  }
}
```

**Comment by romulous75** [comment]
I also have this issue:

`# cdk --version
2.85.0 (build 4e0d726)`

`cdk bootstrap
✅  Environment aws://xxxxxxxxxxxxx/xxxxxxxxxxxx bootstrapped (no changes).`

`cdk synth
AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.`

**Comment by buchananta** [comment]
For anyone else who stumbles across this. It looks like this isn't actually an error, but a [terrible UI design](https://github.com/aws/aws-cdk/issues/17942#issuecomment-1238901584)

**Comment by mat01** [comment]
Is it unreasonable to expect AWS to fix it, so that people (particularly beginners) are not concerned by 'error messages' that seem to mean nothing?
