### ISSUE TITLE
Cannot import name 'AssetManifestOptions' from 'aws_cdk.cloud_assembly_schema (AWS-CDK) 

### ISSUE THREAD

**Issue by Aabhas2u** [aws/aws-cdk#22925]
### Overview

I am getting this error when I am trying 'cdk ls'. looks like some issue with the package but still not ableto get the root cause.
I am using virual env in python for this app.
ANy help would be really heplful

Exception :

ImportError: cannot import name 'AssetManifestOptions' from 'aws_cdk.cloud_assembly_schema' (C:\cdk_final\venv\Lib\site-packages\aws_cdk\cloud_assembly_schema\__init__.py)

### Link to the service’s CDK Construct Library API reference page.

https://docs.aws.amazon.com/cdk/v2/guide/work-with-cdk-python.html

### Maturity: CloudFormation Resources Only

Experimental

### Implementation

`from aws_cdk import (aws_ec2 as ec2,
                    aws_autoscaling as autoscaling,
                    Stack,
                    Duration as duration
                    )

from constructs import Construct
import aws_cdk.aws_cloudwatch as cloudwatch 

class AutoScalingStack(Stack):
    def __init__(self, scope:Construct, id: str, **kwargs) -> None:
        super().__init__(scope,**kwargs)

        template = ec2.LaunchTemplate(self, "LaunchTemplate",
            machine_image=ec2.MachineImage.latest_amazon_linux(),
            instance_type= ec2.InstanceType.of(ec2.InstanceClass.T2, ec2.InstanceSize.MICRO),
            launch_template_name="Abhas-cdk-LaunchTemplate",
            detailed_monitoring=False
        )

        metric = cloudwatch.Metric(
            namespace='AWS/EC2',
            metric_name='CPUUtilization',
            period= duration.minutes(5)

        )

        asg = autoscaling.AutoScalingGroup(self, 'ASG',
            vpc= ec2.Vpc(self,'MyVpc'),
            launch_template=template,
            auto_scaling_group_name= "Abhas-ASG",
            max_capacity=4
        )

        alarm = cloudwatch.Alarm(self, 'Alarm',
            metric= metric,
            comparison_operator=cloudwatch.ComparisonOperator.GREATER_THAN_OR_EQUAL_TO_THRESHOLD,
            threshold=10,
            evaluation_periods=3,
            datapoints_to_alarm=2        
        )

        step_scale_policy= autoscaling.StepScalingPolicy(self, 'MyStepScalePolicy',
            auto_scaling_group=asg,
            metric= metric,
            scaling_steps=[autoscaling.ScalingInterval(upper=10, change=-1),
                autoscaling.ScalingInterval(upper=30, change=+1),
                autoscaling.ScalingInterval(upper=70, change=+3)
                ],
            adjustment_type= autoscaling.AdjustmentType.CHANGE_IN_CAPACITY,
            estimated_instance_warmup=duration.seconds(300),
            evaluation_periods=4,
            metric_aggregation_type=autoscaling.MetricAggregationType.Average
        )
    

`

### Issue list

- [ Getting import error]

**Comment by peterwoodworth** [comment]
I suspect you're having the same issue described [here](https://github.com/aws/aws-cdk/issues/21985#issuecomment-1251004815). Every time I've seen this issue it has to do with mismatched installed versions

**Comment by ravyshankar** [comment]
> I suspect you're having the same issue described [here](https://github.com/aws/aws-cdk/issues/21985#issuecomment-1251004815) or [here](https://github.com/aws/aws-cdk/issues/18761). Every time I've seen this issue it has to do with mismatched installed versions

Hi, 
The link in your reply says that it might be due to incompatible version's and I should get rid of global version. Which product version are we referring to? How should I get rid of my **global version** and do a virtual-env version? 

I installed CDK and imported AWS construct library modules few minutes back following the link below. Wondering why is there a incompatibility in a fresh install. 
Step1: https://docs.aws.amazon.com/cdk/v2/guide/work-with.html#work-with-prerequisites
Step 2: https://docs.aws.amazon.com/cdk/v2/guide/work-with-cdk-python.html
Step 3: https://docs.aws.amazon.com/cdk/v2/guide/hello_world.html 
I am currently at step3 issuing "cdk ls" command and I get an error "ImportError: cannot import name 'AssetManifestOptions' from 'aws_cdk.cloud_assembly_schema' (C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aws_cdk\cloud_assembly_schema\__init__.py)"

I am a newbie to CDK, Coding, IaC. First time doing this. Could you please guide the steps to **"get rid of the global version"**

```
PS C:\Users\cravi\Documents\hello-cdk> python --version
Python 3.11.2

PS C:\Users\user\Documents\hello-cdk> cdk --version
2.67.0 (build b6f7f39)

PS C:\Users\user\Documents\hello-cdk> cat .\requirements.txt
aws-cdk-lib==2.67.0
constructs>=10.0.0,<11.0.0

PS C:\Users\user\Documents\hello-cdk> aws --version
aws-cli/2.9.23 Python/3.9.11 Windows/10 exe/AMD64 prompt/off
```

**Comment by Aabhas2u** [comment]
Are you setting up virtual environment? For working in python?

**Comment by Aabhas2u** [comment]
I would suggest you to create virtual environment first, and then install all the dependencies their and form virtual env try to run the cdk commands.

Let me know if this helped you...

Cheers!!

**Comment by ravyshankar** [comment]
> 
my outcome is I am trying to practice creating a webapp thru IaC. (i.e: create EC2 behind ALB, Cloud Distribution, SSL Cert etc.,) So as part of the initial setup installed python, aws cli, then pip install cdk etc., 

After CDK, followed the link to setup python and its env, are you referring to virtual env as in activating the virtual env which is described in this link? https://docs.aws.amazon.com/cdk/v2/guide/work-with-cdk-python.html

```
snippet from the link above
To work with the new project, activate its virtual environment. This allows the project's dependencies to be installed locally in the project folder, instead of globally.
source .venv/bin/activate
Note
You may recognize this as the Mac/Linux command to activate a virtual environment. The Python templates include a batch file, source.bat, that allows the same command to be used on Windows. The traditional Windows command, .venv\Scripts\activate.bat, works, too
```


```
PS C:\Users\user\Documents> cd .\hello-cdk\
PS C:\Users\user\Documents\hello-cdk> .venv\Scripts\activate.bat
after issuing the 2nd cmd, there is no output. 
```

**Comment by ravyshankar** [comment]
```
PS C:\Users\user\Documents\hello-cdk> cat .\requirements.txt
aws-cdk-lib==2.67.0
constructs>=10.0.0,<11.0.0
PS C:\Users\user\Documents\hello-cdk>
```

**Comment by Aabhas2u** [comment]
Yes I m mentioning that only.... 
Create a new project..
Create virtual environment
Then install all the dependencies.
Then try to execute cdk commands

**Comment by ravyshankar** [comment]
Create a new project.. --> do you mean that I run the cmd's below first? 
mkdir my-project
cd my-project
cdk init app --language python

Create virtual environment.  --> How do I create a virtual env without installing CDK? 

Then install all the dependencies. --> Do you mean I do this install -g aws-cdk?
Then try to execute cdk commands.

Sorry, need some hand holding as I am totally a newbie. Kindly help!!

**Comment by ford-at-aws** [comment]
Having this same issue. Experienced CDK user. Might be consequence of bad dependencies from from the CDK sample app.

**Comment by lucasfariaslf** [comment]
@ravyshankar If you haven't found a solution yet and do not depend on cdk v2 for any specific reason, a temporary workaround would be to uninstall you current you cdk v2 version, install the latest v1 and proceed from there. Keep in mind tho: support for v1 will end on June 1, 2023.

**Comment by MarcosRibeiroJesus** [comment]
I'm having the same error with CDK version 2.72.0. I've downgraded to version 2.71.0, and it worked.

**Comment by NathanSkilton** [comment]
@ravyshankar 

https://docs.aws.amazon.com/cdk/v2/guide/hello_world.html

cdk init app --language python
source .venv/bin/activate
python -m pip install -r requirements.txt
cdk ls

Virtual environments are part of Python.
https://www.geeksforgeeks.org/python-virtual-environment/

**Comment by isaacrayAZ** [comment]
If you end up here, the solution (or cause of the issue, at least) is that it seems like the most recent version of Node (20 as of this writing) causes this issue when you install the CDK. When I downgraded to Node 16, the issue resolved. Node 16 has reached EOL though, so I don't know the best course of action at this point.

**Comment by radiantone** [comment]
Yeah, same here. Seems to be stuck in limbo until they make it compatible with node 20 (before IT reaches EOL). So this stuff isn't ready for production. Lots of compatibility issues

**Comment by SumanthShetty** [comment]
Any solutions for this?

**Comment by amila-ku** [comment]
bump, ran into the sam issue.

**Comment by pahud** [comment]
This issue was closed for staleness in 2022. If you are still having relevant issues like this, do not comment in this closed one and please create a new one. We'd be happy to look into. Thanks.
