### ISSUE TITLE
(cloudfront): Flag on Distribution L2 to enable publishing additional CloudWatch metrics

### ISSUE THREAD

**Issue by straygar** [aws/aws-cdk#22922]
### Describe the feature

The CloudFront UI and API lets you [enable more granular metrics per-distribution](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/monitoring-using-cloudwatch.html), at an additional (fixed) cost.

There is an L1 construct that lets you do this, which can be easily integrated into the L2 construct and enabled via a prop.

### Use Case

I want to create a dashboard of data like origin latency, Lambda@Edge error rate etc. and alarm on these metrics.

### Proposed Solution

An additional prop for `cloudfront.Distribution`:
```
new Distribution(this, 'Distro', {
    ...,
    publishAdditionalMetrics: true,  // default: false
});
```

If this is set to `true` a `CfnMonitoringSubscription` instance is created:
```
new CfnMonitoringSubscription(nextJsDeployment.distribution, 'MonitoringSubscription', {
    distributionId: nextJsDeployment.distribution.distributionId,
    monitoringSubscription: {
        realtimeMetricsSubscriptionConfig: {
            realtimeMetricsSubscriptionStatus: 'Enabled',
        }
    }
});
```

Also, we probably want to expose these metrics via `distro.metricsXyz()` methods (should probably throw, if `publishAdditionalMetrics` is set to false.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.50.0

### Environment details (OS name and version, etc.)

n/a

**Comment by peterwoodworth** [comment]
Thanks for the feature request @straygar,

I am marking this issue as p2, which means that we are unable to work on this immediately.

We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://cdk.dev) to solicit support for reprioritization.

Check out our [contributing guide](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) if you're interested in contributing yourself. Before you start contributing, you will probably want to spend some time discussing the best direction to go with someone on the team. There aren't any L2s for CfnMonitoringSubscription yet, it's possible we'd want to tackle that first before this feature.

**Comment by straygar** [comment]
@peterwoodworth Alright, thanks! I'd like to contribute, but I'm not sure what discussion is to be had there. `CfnMonitoringSubscription` is currently just a boolean flag wrapped in some objects, I reckon creating an L2 might be overkill. Happy to be challenged though.

My suggestion above was just a `publishAdditionalMetrics`/`publishRealtimeMetrics` flag, but we can also make that a `monitoringSubscriptions: { realtimeMetrics: RealtimeMetrics.ENABLED/DISABLED } }` object.

In any case, what is the best way to involve somebody from the CDK team to discuss this?
