### ISSUE TITLE
cli: overrideTemplate is stored in working directory rather than assembly directory (i.e. import does not work)

### ISSUE THREAD

**Issue by saltman424** [aws/aws-cdk#22928]
### Describe the bug

Recently, I have had issues using `cdk import` that seem to stem from the overridden template being generated in my working directory rather than the assembly directory. Obviously, when `deploy` tries to use the generated template, it is expecting it to come from my assembly directory. Please see the Possible Solution section below for details.

### Expected Behavior

`cdk import` should work without any issues

### Current Behavior

Error message from `cdk import`:

```
[0%] start: Building and publishing 04926632678b4ce87690ab5dff6a51bed012b313a6dbc96b8be43c23aba2a6b1:current
[100%] fail: ENOENT: no such file or directory, open 'C:\Users\Me\my-repo\cdk.out\assembly-MyStage\MyStack1234ABCD.template.json-04926632678b4ce87690ab5dff6a51bed012b313a6dbc96b8be43c23aba2a6b1.yaml'

 ❌  MyStage/MyStack (MyStack) failed: Error: Failed to publish one or more assets. See the error messages above for more information.
```

Note that the `MyStack1234ABCD.template.json-04926632678b4ce87690ab5dff6a51bed012b313a6dbc96b8be43c23aba2a6b1.yaml` file is added to my working directory just before it gets to this stage of the process.

### Reproduction Steps

I don't have a simple repo to reproduce the issue, but in the Possible Solution section below, I believe I identified the line of code that needs to be updated.

### Possible Solution

I believe this line:
https://github.com/aws/aws-cdk/blob/8b20446aeccc787de1511f01dd27cc590d57ce89/packages/aws-cdk/lib/api/deploy-stack.ts#L595

Should be changed to:
```typescript
 await fs.writeFile(path.join(stack.assembly.directory, templateFile), templateJson, { encoding: 'utf-8' }); 
```

### Additional Information/Context

For some reason, I did not used to get this issue. I have been using `cdk import` since shortly after it was released and only recently did I start having issues. I update cdk regularly, so I don't know exactly what version introduced the issue, or if there is something different in my configuration that is causing the issue to surface, but I know that when I go back to 2.46.0 I still have the issue. Also, when I go into `node_modules` and manually update the line mentioned above, everything works as it is supposed to.

### CDK CLI Version

2.50.0 (build 4c11af6)

### Framework Version

2.50.0

### Node.js Version

16.15.1

### OS

Windows 10 Enterprise

### Language

Typescript

### Language Version

4.8.4

**Comment by peterwoodworth** [comment]
Thanks for reporting this @saltman424,

I'm unsure what is causing you to run into this. I'm also unable to reproduce this. However, I wonder if it has something to do with the stack being in a stage, or if you're on windows. I'm going to leave this open, it would be really helpful if we have clear reproduction steps if anyone else runs into this in the future.

**Comment by tlrdstd** [comment]
I am also experiencing this issue, running on Amazon Linux 2. CDK version `2.53.0 (build 7690f43)`.

I confirm this only started recently - worked fine ~2 months ago, and without changing anything specific, it's stopped working.

My stacktrace below. I tried briefly to use the  fix suggested above, but the error references a non-existent `.ts` file, and editing the `.js` equivalent at `node_modules/aws-cdk/lib/api/deploy-stack.js` didn't seem to help. So I just created a symlink from the package build directory back up to my current working directory where the override template was incorrectly created:

```
ln -s $PWD/AmiBuilderBaseStack.template.json-ffefca5f96d16aad7d75e248477cf23371def5c11773d7e4bc776c297f618f66.yaml /workplace/me/MyPackageCDK/src/MyPackageCDK/build/cdk.out/AmiBuilderBaseStack.template.json-ffefca5f96d16aad7d75e248477cf23371def5c11773d7e4bc776c297f618f66.yaml
```

```
AmiBuilderBaseStack
AmiBuilderBaseStack/RegionalRpmBucket/RegionalRpmBucket-RpmBucket/Resource (AWS::S3::Bucket): import with BucketName=my-regional-bucket-name (yes/no) [default: yes]? y
AmiBuilderBaseStack/RegionalRpmBucket/RegionalRpmBucket-RpmBucket/Policy/Resource: unsupported resource type AWS::S3::BucketPolicy, skipping import.
AmiBuilderBaseStack: importing resources into stack...
[0%] start: Building and publishing ffefca5f96d16aad7d75e248477cf23371def5c11773d7e4bc776c297f618f66:current
[100%] fail: ENOENT: no such file or directory, open '/workplace/me/MyPackageCDK/src/MyPackageCDK/build/cdk.out/AmiBuilderBaseStack.template.json-ffefca5f96d16aad7d75e248477cf23371def5c11773d7e4bc776c297f618f66.yaml'

 ❌  AmiBuilderBaseStack failed: Error: Failed to publish one or more assets. See the error messages above for more information.
    at publishAssets (/workplace/me/MyPackageCDK/src/MyPackageCDK/node_modules/aws-cdk/lib/util/asset-publishing.ts:60:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at deployStack (/workplace/me/MyPackageCDK/src/MyPackageCDK/node_modules/aws-cdk/lib/api/deploy-stack.ts:297:3)
    at ResourceImporter.importResources (/workplace/me/MyPackageCDK/src/MyPackageCDK/node_modules/aws-cdk/lib/import.ts:130:22)
    at CdkToolkit.import (/workplace/me/MyPackageCDK/src/MyPackageCDK/node_modules/aws-cdk/lib/cdk-toolkit.ts:485:5)
    at initCommandLine (/workplace/me/MyPackageCDK/src/MyPackageCDK/node_modules/aws-cdk/lib/cli.ts:364:12)
```

**Comment by saltman424** [comment]
@tlrdstd in order to update it in `node_modules` you actually need to update it in `node_modules/aws-cdk/lib/index.js` since that seems to be a bundled file. In my current version, the line that needs to be modified is `943611`. You can search for `if (overrideTemplate) {`.

@peterwoodworth is it possible that CDK previously changed the working directory to the assembly directory, but is no longer doing so?

**Comment by alFReD-NSH** [comment]
I had the same issue as well and the mentioned fix worked for me as well.

**Comment by thake** [comment]
Ran into the same issue. I called it using the following arguments:
`npx cdk import my-stack -c environment=develop -f`. CDK version was 2.125.0.
