### ISSUE TITLE
(aws-lambda): (event source mapping, unnecessary validation of input)

### ISSUE THREAD

**Issue by nikovirtala** [aws/aws-cdk#22932]
### Describe the bug

`SelfManagedKafkaEventSource` tries to validate the input value of `consumerGroupId` which is generally good behavior, but if the user wants to pass a value that gets resolved while synth, it is not possible.

### Expected Behavior

`SelfManagedKafkaEventSource` should not validate `consumerGroupId` value, if the value is unresolved `Token`.

### Current Behavior

While synthesizing the code CDK throws an error: `Error: kafkaConsumerGroupId contain ivalid characters. Allowed values are "[a-zA-Z0-9-/*:_+=.@-]"`

### Reproduction Steps

- Create Lambda Function, e.g. with `NodejsFunction`
- Use `.addEventSource` method to add the new `SelfManagedKafkaEventSource`
- For `SelfManagedKafkaEventSource` give `consumerGroupId` that is a unresolved `Token`, e.g. Lambda Function, `.functionName`

### Possible Solution

@RomainMuller suggested disabling the validation for unresolved tokens.

### CDK CLI Version

2.50.0 (build 4c11af6)

### Node.js Version

v16.18.1

### OS

macOS 13.1 Beta (22C5044e)

### Language

Typescript

**Comment by peterwoodworth** [comment]
Thanks for reporting this, we've had similar bugs in the past so this makes sense. Based on your PR it looks like you got it 🙂 Hopefully it won't be too long until we're able to give a proper review for your PR
