### ISSUE TITLE
OpenSearch: Add support for OpenSearch 2.3

### ISSUE THREAD

**Issue by agusti-t** [aws/aws-cdk#22942]
### Describe the feature

AWS Launched the support for Amazon OpenSearch Service 2.3 as per the announcement here: https://aws.amazon.com/about-aws/whats-new/2022/11/amazon-opensearch-service-supports-opensearch-version-2-3/

AWS CDk does not support the latest version yet, and having issue launching the OpenSearch cluster with CDK using 2.3

### Use Case

I would like to launch latest OpenSearch version using CDK

### Proposed Solution

Created a PR with a proposed solution: https://github.com/aws/aws-cdk/pull/22943

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.50.0

### Environment details (OS name and version, etc.)

MacOS 12.3

**Comment by peterwoodworth** [comment]
Thanks for the quick PR for this new feature!

**Comment by bmcclellan-cu** [comment]
Are any 2.X opensearch engine versions available in the CDK? All I see is 1.3 in https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_opensearchservice/EngineVersion.html

**Comment by prashanttct07** [comment]
Team, 
Any update as when this could be merged and added for OpenSearch 2.3?

**Comment by dblock** [comment]
I PRed something smaller for just adding the version in https://github.com/aws/aws-cdk/pull/23621.

**Comment by ferngus** [comment]
While that is not reviewed, a quick workaround is to make use of CDK OpenSearch Custom Version. 

```
# Example with CDK Python
# https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_opensearchservice/EngineVersion.html
OPENSEARCH_VERSION = "2.3"
# Amazon OpenSearch Domain
aos_domain = cdk_opensearch.Domain(
            self, "OpensearchDemoDomain",
            version=cdk_opensearch.EngineVersion.open_search(
                OPENSEARCH_VERSION), ...
```
