### ISSUE TITLE
(aws-lambda-nodejs): AWS SDK v2 is not available for node18.x runtime

### ISSUE THREAD

**Issue by gkkachi** [aws/aws-cdk#22976]
### Describe the bug

According to [this comment](https://github.com/aws/aws-lambda-base-images/issues/47#issuecomment-1292011841), node18.x image includes the AWS SDK not v2 but v3.
The AWS SDK v2 is not included in bundles as `aws-sdk` is specified in `externalModules` by default, so sccripts which use `aws-sdk` will fail when using node18.x runtime.

### Expected Behavior

`extenalModules` for node18.x runtime should be `@aws-sdk/*` .

### Current Behavior

```
{
  "errorType": "Error",
  "errorMessage": "Cannot find module 'aws-sdk'\nRequire stack:\n- /var/task/index.js\n- /var/runtime/index.mjs",
  "trace": [
    "Error: Cannot find module 'aws-sdk'",
    "Require stack:",
    "- /var/task/index.js",
    "- /var/runtime/index.mjs",
    "    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)",
    "    at Module._load (node:internal/modules/cjs/loader:841:27)",
    "    at Module.require (node:internal/modules/cjs/loader:1061:19)",
    "    at require (node:internal/modules/cjs/helpers:103:18)",
    "    at Runtime.handler (/var/task/index.js:28:3)",
    "    at Runtime.handleOnceNonStreaming (file:///var/runtime/index.mjs:1089:29)"
  ]
}
```

### Reproduction Steps

Deploy a node18.x lambda function whose handler contains `require('aws-sdk')` and run it.

### Possible Solution

Edit here:

https://github.com/aws/aws-cdk/blob/2c614059c44939e00c93c924ff2f0aa7a22a2a6e/packages/%40aws-cdk/aws-lambda-nodejs/lib/bundling.ts#L116

### CDK CLI Version

2.51.0

### Node.js Version

v16.18.0

### OS

Ubuntu 22.04 LTS

### Language

Typescript

**Comment by o-alexandrov** [comment]
It's not a bug, [it was announced](https://github.com/aws/aws-lambda-base-images/issues/47#issuecomment-1292011841) that aws-sdk v3 is added by default.

**Comment by trivikr** [comment]
The fix in CDK should be to ignore all `@aws-sdk/*` dependencies when Node.js version is 18, and ignore `aws-sdk` dependency for prior Node.js versions, as pointed out in possible solution.

https://github.com/aws/aws-cdk/blob/2c614059c44939e00c93c924ff2f0aa7a22a2a6e/packages/%40aws-cdk/aws-lambda-nodejs/lib/bundling.ts#L116

**Comment by yamatatsu** [comment]
I try to fix it https://github.com/aws/aws-cdk/pull/22989 .

And workaround of this issue is setting empty array to extenalModules.

**Comment by juztinlazaro** [comment]
Hi @yamatatsu whats the fix for this issue?

**Comment by yamatatsu** [comment]
Hi @juztinlazaro 
I've fixed it so that nodejs 18 and above will not bundle sdkv3 instead of sdkv2. Also, nodejs 16 and below will not bundle sdkv2 as before.
https://github.com/aws/aws-cdk/pull/22989/files#diff-cd86fbd4f2bbefcbcffc2143adccabafa1debe5981edbcdfcc766b5a705fe770
