### ISSUE TITLE
servicecatalogappregistry: Use cdk.App as scope for TargetApplication application

### ISSUE THREAD

**Issue by alexpulver** [aws/aws-cdk#22973]
### Describe the feature

Use `stackId` [prop](https://docs.aws.amazon.com/cdk/api/v2/docs/@aws-cdk_aws-servicecatalogappregistry-alpha.CreateTargetApplicationOptions.html#stackidspan-classapi-icon-api-icon-experimental-titlethis-api-element-is-experimental-it-may-change-without-noticespan) value verbatim in `TargetApplication` class, with no prefix.

Update the `stackId` [prop](https://docs.aws.amazon.com/cdk/api/v2/docs/@aws-cdk_aws-servicecatalogappregistry-alpha.CreateTargetApplicationOptions.html#stackidspan-classapi-icon-api-icon-experimental-titlethis-api-element-is-experimental-it-may-change-without-noticespan) description to align with the definition in [Identifiers](https://docs.aws.amazon.com/cdk/v2/guide/identifiers.html) documentation:
_“The id of a stack is also the identifier that you use to refer to it in the [AWS CDK Toolkit (cdk command)](https://docs.aws.amazon.com/cdk/v2/guide/cli.html).”_

### Use Case

As a user, I want to have full control over the stack ID, to maintain a naming convention when using AWS CDK Toolkit. AWS CDK Construct Library v2.51.0 allows to set the stack ID for `TargetApplication`, but prefixes the name with the containing construct ID, which I think it shouldn’t.

For an example, the following example code snippet:
```python
application = appregistry_alpha.TargetApplication.create_application_stack(
    application_name=constants.APP_NAME,
    stack_id=constants.APP_NAME + "AppRegistryApplication",
    env=cdk.Environment(
        account=APPREGISTRY_APPLICATION_ACCOUNT,
        region=APPREGISTRY_APPLICATION_REGION,
    ),
)
appregistry_application_associator = appregistry_alpha.ApplicationAssociator(
    app, "AppRegistryApplicationAssociator", applications=[application]
)
```

Produces the following stack ID for the AppRegistry application (I define the other stacks elsewhere):
```bash
Supply a stack id (AppRegistryApplicationAssociator/UserManagementBackendAppRegistryApplication, UserManagementBackendSandbox, UserManagementBackendToolchain) to display its template. 
```

I expected the behavior to be:
```bash
Supply a stack id (UserManagementBackendAppRegistryApplication, UserManagementBackendSandbox, UserManagementBackendToolchain) to display its template. 
```

### Proposed Solution

Update `this` to `scope` in 
https://github.com/aws/aws-cdk/blob/2c614059c44939e00c93c924ff2f0aa7a22a2a6e/packages/%40aws-cdk/aws-servicecatalogappregistry/lib/application-associator.ts#L45 (thanks @rohitagg0807!)

### Acknowledgements

- [ ] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### CDK version used

2.51.0

### Environment details (OS name and version, etc.)

macOS Monterey 12.6.1

**Comment by peterwoodworth** [comment]
Thanks @rohitagg0807 for the PR. 

I'm not certain if this is a direction we'll want to take, but I can see the reasoning. If we do want to take this direction, we'll be able to make this change even though it's breaking as the module not yet considered stable

**Comment by rohitagg0807** [comment]
Yes this is the direction we want to take and move forward.

**Comment by alexpulver** [comment]
@rohitagg0807 thank you! It looks much better now from user experience perspective 😄
