### ISSUE TITLE
Documentation: How to translate TypeScript samples to Python, .NET, Java

### ISSUE THREAD

**Issue by ccfife** [aws/aws-cdk#2298]
Most samples are in TypeScript only and many developers want to start from example code. This section helps people convert TS samples to the language of their choice.

**Comment by Doug-AWS** [comment]
We're talking about this section: https://docs.aws.amazon.com/cdk/latest/guide/multiple_languages.html
It has how to:
- Import a package
- Create a new object

In:
- C#
- Java
- JavaScript
- Python

**Comment by Jerry-AWS** [comment]
We now have Python but lack C# and Java. I've added this task to the CDK Guide project. 

https://github.com/awsdocs/aws-cdk-guide/issues/97

This can be closed.
