### ISSUE TITLE
(apprunner): (apprunner observability configuration support)

### ISSUE THREAD

**Issue by Brass-Perkins** [aws/aws-cdk#22985]
### Describe the feature

Support for Apprunner's Observability Configuration support: https://aws.amazon.com/about-aws/whats-new/2022/04/aws-app-runner-x-ray-support/

### Use Case

Support for configuration of Observability

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.51.0

### Environment details (OS name and version, etc.)

N/A

**Comment by pahud** [comment]
Thanks for your report. It seems like we need to add the `ServiceObservabilityConfiguration` L2 prop support to the Apprunner Service construct. Before we add the L2 prop support, you can use [ServiceObservabilityConfigurationProperty](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_apprunner.CfnService.ServiceObservabilityConfigurationProperty.html) to define the  `ServiceObservabilityConfiguration` and add use [escape hatches](https://docs.aws.amazon.com/cdk/v2/guide/cfn_layer.html) to override the property like:

```ts

const service = new apprunner.Service(...);

const serviceObservabilityConfigurationProperty: CfnService.ServiceObservabilityConfigurationProperty = {
  observabilityEnabled: false,
  observabilityConfigurationArn: 'observabilityConfigurationArn',
};

(service.node.defaultChild as CfnService).addPropertyOverride('ObservabilityConfiguration', serviceObservabilityConfigurationProperty);
```

I am marking this issue as p2, which means that we are unable to work on this immediately.

We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://cdk.dev/) to solicit support for reprioritization.

Check out our [contributing guide](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) if you're interested in contributing yourself - there's a low chance the team will be able to address this soon but we'd be happy to review a PR 🙂

**Comment by mazyu36** [comment]
I'm working on it.
