### ISSUE TITLE
(aws-amplify): add missing properties platform and framework on app and branch

### ISSUE THREAD

**Issue by fabienfleureau** [aws/aws-cdk#22987]
### Describe the bug

Hello,
In the AWS Cloud formation documentation for Amplify there are 2 properties defined that are missing in cdk:

### 1 - [AWS::Amplify::App](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-amplify-app.html)
**Platform** is missing

Description:
>  The platform for the Amplify app. For a static app, set the platform type to WEB. For a dynamic server-side rendered (SSR) app, set the platform type to WEB_COMPUTE. For an app requiring Amplify Hosting's original SSR support only, set the platform type to WEB_DYNAMIC.

### 2 - [AWS::Amplify::Branch](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-amplify-branch.html)
**Framework** is missing

Description:
>  The framework for the branch. 

For this one i don't know the valid values.

### Expected Behavior

By using CDK, I can deploy an Amplify Hosting with:
Platform=WEB_COMPUTE
and Framework=Next.js - SSR

### Current Behavior

The properties are not available.
The default values are:
Platform=WEB
Framework=EMPTY

### Reproduction Steps

```
        App app = App.Builder.create(this, "amplify")
            .sourceCodeProvider(
                GitHubSourceCodeProvider.Builder.create()
                    .repository(GITHUB_REPOSITORY)
                    .owner(GITHUB_OWNER)
                    .oauthToken(SecretValue.secretsManager("GITHUB_OAUTH_TOKEN"))
                    .build())
            .platform("WEB_COMPUTE") // This property does not exist
            .build();
        app.addBranch("main",
            BranchOptions.builder()
                .framework("Next.js - SSR") // This property does not exist
                .build());
```

### CDK CLI Version

2.50.0

### Node.js Version

16

### OS

Ubuntu

### Language

Java

**Comment by peterwoodworth** [comment]
We stay up to date with CloudFormation automatically, however there can be a delay of a couple weeks. We have a PR open right now for this https://github.com/aws/aws-cdk/pull/22970/files#diff-7fd952d0d05a6c1558b624ecb8d33da2bcc0b7daa1074bbb1c0d0c4c0cf31e03
