### ISSUE TITLE
aws-s3-deployment): BucketDeployment fails for files larger than 2GB 

### ISSUE THREAD

**Issue by kissrin** [aws/aws-cdk#22988]
### Describe the bug

I'm using BucketDeployment to upload my build artifacts. it was working fine till the individual file sizes were less than 2GB, when one of the files size got increased from 1.7 GB to 2.4 GB. We started seeing the below error. 

`RangeError [ERR_FS_FILE_TOO_LARGE]: File size (2467895811) is greater than 2 GB`

The error seems like it's due to Nodejs buffer limit size being 2GB.  is this expected to fail? if so, what are the alternatives we can use apart from BucketDeployment? I couldn't find any option to do multii-part upload etc.

This is my code

```
new BucketDeployment(this, "CloudStreamingCustomBuildS3Deployment", {
   sources: [Source.asset(pathWithPkgDetails)],
   destinationBucket: this.defaultPackagingBucket,
   role: this.s3DeploymentRole,
    prune: false, // Don't delete elements which are not present in source
    memoryLimit: 10000, // Lambda uses ~5.5GB memory, hence using 10GB as upper limit
    ephemeralStorageSize: Size.gibibytes(10), // /tmp directory space used by Lambda.
    destinationKeyPrefix: "Solution",
  });
```

### Expected Behavior

The bucket deployment should happen successfully. 

### Current Behavior

It fails with error RangeError [ERR_FS_FILE_TOO_LARGE]: File size (2467895811) is greater than 2 GB

### Reproduction Steps

Create an asset file with size higher than 2GB and try BucketDeployment and notice the behaviour.

### CDK CLI Version

2.47.0 (build 3528e3d)

### Node.js Version

14

### OS

Linux

### Language

Typescript

**Comment by peterwoodworth** [comment]
Thanks for reporting, there's a similar issue open [here](https://github.com/aws/aws-cdk/issues/15723). Be sure to add your thumbs up to let us know how to prioritize this, thanks!

**Comment by pahud** [comment]
I believe this is related to https://github.com/aws/aws-cdk/issues/24569 which is due to the node buffer size limit.
