### ISSUE TITLE
(stepfunctions-tasks): support newly released cross-account capabilities

### ISSUE THREAD

**Issue by humanzz** [aws/aws-cdk#22994]
### Describe the feature

StepFunctions has recently released new cross-account capabilities as can be seen in
- https://aws.amazon.com/about-aws/whats-new/2022/11/simplify-cross-account-access-aws-services-step-functions/
- https://aws.amazon.com/blogs/compute/introducing-cross-account-access-capabilities-for-aws-step-functions/
- https://docs.aws.amazon.com/step-functions/latest/dg/concepts-access-cross-acct-resources.html
- https://docs.aws.amazon.com/step-functions/latest/dg/amazon-states-language-task-state.html#task-state-fields
- https://docs.aws.amazon.com/step-functions/latest/dg/amazon-states-language-task-state.html#task-state-example-credentials

This is a request to update the relevant tasks to provide the props necessary to set the

```
"Credentials": {
  "RoleArn": "..."
}
```

which allows the task execution to be done via State Machine role assumption to the role provided above

### Use Case

One of the main use cases is the usage of `sfntasks.CallAwsService` to do cross-account calls to resources that do not support resource policies - i.e. requires the other account to provide a role to be assumed

### Other Information

I've asked the SFN team about what types of tasks support `Credentials` as it was not clear from documentation
1. Their answer: Lambda tasks and all service integrations (both optimized and AWS SDK) support the new Credentials field. Only activity tasks do not
2. They will work to clarify that over public documentation

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

3.51.0

### Environment details (OS name and version, etc.)

macOS

**Comment by humanzz** [comment]
A first stab at such support at https://github.com/aws/aws-cdk/pull/23012
I'm seeking feedback, and also guidance on how to best integ test this - also where (in this package or in stepfunctions-tasks

**Comment by yashda** [comment]
Will this be released with v1 ?
