### ISSUE TITLE
`aws_batch_alpha`: job_queue_name returns ARN instead

### ISSUE THREAD

**Issue by SebastianNichtern** [aws/aws-cdk#23018]
### Describe the bug

When calling [job_queue_name](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_batch_alpha/JobQueue.html#aws_cdk.aws_batch_alpha.JobQueue.job_queue_arn) on a `aws_cdk.aws_batch_alpha.JobQueue` resource, it returns the ARN instead of the name. This would be expected only from the [job_queue_arn](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_batch_alpha/JobQueue.html#aws_cdk.aws_batch_alpha.JobQueue.job_queue_arn) function (that one works correctly)

### Expected Behavior

-

### Current Behavior

-

### Reproduction Steps

```
job_queue = batch.JobQueue(self, "JobQueue",compute_environments=[batch.JobQueueComputeEnvironment(compute_environment=spot_environment,order=1)],priority=1)
job_queue.apply_removal_policy(cdk.RemovalPolicy.DESTROY)
CfnOutput(self, "BatchJobQueue Name", value=job_queue.job_queue_arn)
```

### CDK CLI Version

2.51.1

### Node.js Version

v16.16.0

### OS

MacOS

### Language

Python

### Language Version

Python (3.9.15)

**Comment by peterwoodworth** [comment]
You're right @svsn2117,

According to [CloudFormation documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-batch-jobqueue.html#aws-resource-batch-jobqueue-return-values), JobQueue has two return values - the default `ref` and the `JobQueueArn` attribute. The `ref` value resolves to the arn, making the `JobQueueArn` attribute redundant.

The CDK code sets the `ref` value to `jobQueueName`. https://github.com/aws/aws-cdk/blob/3d30cdb55620a5f2a34944d21edca770e90ff7c5/packages/%40aws-cdk/aws-batch/lib/job-queue.ts#L133

There isn't a direct way to fetch the name with the current CloudFormation API, however there should be a way to find the name by using [CloudFormation intrinsic functions](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_core.Fn.html#static-selectindex-array) to select and split the right value from the arn by splitting by `/` and selecting the `1` value in the array. We might want to take this direction in the CDK code too if they aren't going to directly expose the name from this resource

**Comment by svsn2117** [comment]
Thanks for your insights! For now, it might be a good idea to remove the name attribute since it's not (really) available to avoid confusion
