### ISSUE TITLE
(custom_resources): (AwsCustomResource does not trigger lambda on_update of the stack)

### ISSUE THREAD

**Issue by michalkonik** [aws/aws-cdk#23015]
### Describe the bug

custom_resources.AwsCustomResource on_update=custom_resources.AwsSdkCall (service="Lambda", action="invoke") is not triggering the defined lambda, when the stack which contains the triggers gets redeployed (updated). 

There are two triggers implemented in the same stack: on_create and on_update. Both should trigger the same lambda function. 
Whenever the stack gets created (deployed for the first time), trigger on_create works as expected and triggers the lambda, however updating the stack with new changes, doesn't trigger it. 

### Expected Behavior

The defined lambda gets triggered every time, when the stack is updated. 

### Current Behavior

There are two triggers implemented in the same stack: on_create and on_update. Both should trigger the same lambda function. 
Whenever the stack gets created (deployed for the first time), trigger on_create works as expected and triggers the lambda, however updating the stack with new changes, doesn't trigger it. 

### Reproduction Steps

from aws_cdk import (
    Duration,
    Stack,
    aws_apigateway,
    aws_lambda,
    NestedStack,
    custom_resources,
    aws_iam
)
from constructs import Construct

class ApiGatewayStack(NestedStack):
    def __init__(self, scope: Construct, construct_id: str, lambdas_stack: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        self.api_gateway = aws_apigateway.RestApi(
            self,
            f"api-gateway",
            endpoint_configuration=aws_apigateway.EndpointConfiguration(types=[aws_apigateway.EndpointType.REGIONAL]),
            binary_media_types=["application/gzip"],
        )
        
        self.api_docs_endpoint_name = "docs"

        api_docs = self.api_gateway.root.add_resource(self.api_docs_endpoint_name)
        swagger = api_docs.add_resource("{item}")

        swagger.add_method(
            http_method="GET",
            request_parameters={"method.request.path.item": True, "method.request.header.Content-Type": True},
            method_responses=[
                aws_apigateway.MethodResponse(
                    status_code="200",
                    response_parameters={
                        "method.response.header.Content-Type": True,
                    },
                )
            ],
        )

        custom_resources.AwsCustomResource(
            scope=self,
            id="invoke_lambda",
            policy=(
                custom_resources.AwsCustomResourcePolicy.from_statements(
                    statements=[
                        aws_iam.PolicyStatement(
                            actions=["lambda:InvokeFunction"],
                            effect=aws_iam.Effect.ALLOW,
                            resources=[lambdas_stack.update_api_docs_lambda.function_arn],
                        )
                    ]
                )
            ),
            timeout=Duration.minutes(3),
            on_create=custom_resources.AwsSdkCall(
                service="Lambda",
                action="invoke",
                parameters={
                    "FunctionName": lambdas_stack.update_api_docs_lambda.function_name,
                    "InvocationType": "Event",
                },
                physical_resource_id=custom_resources.PhysicalResourceId.of("update_api_docs_lambda_trigger"),
            ),
            on_update=custom_resources.AwsSdkCall(
                service="Lambda",
                action="invoke",
                parameters={
                    "FunctionName": lambdas_stack.update_api_docs_lambda.function_name,
                    "InvocationType": "Event",
                },
                physical_resource_id=custom_resources.PhysicalResourceId.of("update_api_docs_lambda_trigger"),
            ),
        )

class LambdasStack(NestedStack):
    def __init__(
        self,
        scope: Construct,
        construct_id: str,
        **kwargs,
    ) -> None:
        super().__init__(scope, construct_id, **kwargs)

        self.update_api_docs_lambda = aws_lambda.Function(
                self,
                "update-api-docs",
                runtime=aws_lambda.Runtime.PYTHON_3_8,
                code=aws_lambda.Code.from_asset("./lambdas"),
                handler="handler.lambda_handler",
                timeout=Duration.minutes(3),
            )
        

class PocApiGatewayOnUpdateStack(Stack):

    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        self.lambdas_stack = LambdasStack(self,"lambdas")
        
        self.api_gateway_stack = ApiGatewayStack(self, "api-gateway", lambdas_stack=self.lambdas_stack,)

        

        

### CDK CLI Version

2.43.1

### Framework Version

Version: 2.43.1

### Node.js Version

v18.12.0

### OS

Ubuntu 22.04.1 LTS

### Language

Python

### Language Version

3.8.15

**Comment by peterwoodworth** [comment]
I'm not able to reproduce this @michalkonik, our AwsCustomResource seems to be working fine.

Are you sure that you're making an update to the nested stack itself? If an update is made to the stack containing the nested stack but not the nested stack itself, then you wouldn't expect to see an update.

**Comment by michalkonik** [comment]
@peterwoodworth are you able to provide your working code, which triggers a lambda on_update event?

**Comment by peterwoodworth** [comment]
I copied all the infrastructure you posted here @michalkonik, maybe there's a bug in your handler?
