### ISSUE TITLE
Allow import of existing CFT(json/yaml) into AWS-CDK constructs

### ISSUE THREAD

**Issue by willkara** [aws/aws-cdk#2302]
It'd be great if there was a way to import existing CFTs that create the underlying app/stack/constructs objects.

So if I then generate/export a CFT, I could then do the following:

- Export to a file
- Import CFT
- Generate AWS-CDK constructs from imported CFT

That way, you can use the SDK to continuously tweak existing templates.

**Comment by rix0rrr** [comment]
If you are feeling adventurous and comfortable doing some development work yourself, [cdk-dasm](https://github.com/awslabs/aws-cdk/tree/master/packages/cdk-dasm) is a start at some work in that direction.

**Comment by willkara** [comment]
@rix0rrr , thanks for the idea... I'll take a look!
