### ISSUE TITLE
aws_logs: MetricFilter does not support setting the Unit

### ISSUE THREAD

**Issue by DanielBauman88** [aws/aws-cdk#23022]
### Describe the feature

This is supported by the APIs and the CFN resource - see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-logs-metricfilter-metrictransformation.html and the Unit property.

This should be supported by CDK too but it isn't currently available that I can see - https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_logs.MetricFilter.html

### Use Case

I need to be able to set the unit for my MetricFilter metrics so that it shows up and is correctly annotated in cloudwatch.

EG: I have a metric filter for cold start durations of my lambdas which are logged as ms values but I can't set this via the CDK.

### Proposed Solution

Support the Unit property.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

v2

### Environment details (OS name and version, etc.)

any

**Comment by peterwoodworth** [comment]
It seems like you're right that we don't directly support this yet. I think all we would need to do is create a new prop and pass it here https://github.com/aws/aws-cdk/blob/3d30cdb55620a5f2a34944d21edca770e90ff7c5/packages/%40aws-cdk/aws-logs/lib/metric-filter.ts#L43

At the moment, you can use [escape hatches](https://docs.aws.amazon.com/cdk/v2/guide/cfn_layer.html) to work around the fact we don't support this with our L2s yet.

I am marking this issue as p2, which means that we are unable to work on this immediately.

We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://cdk.dev) to solicit support for reprioritization.

Check out our [contributing guide](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) if you're interested in contributing yourself - there's a low chance the team will be able to address this soon but we might be able to review a PR 🙂

**Comment by kichik** [comment]
For now I use:

```
if (metricFilter.node.defaultChild instanceof logs.CfnMetricFilter) {
  metricFilter.node.defaultChild.addPropertyOverride('MetricTransformations.0.Unit', 'Count');
} else {
  Annotations.of(metricFilter).addWarning('Unable to set Unit to Count');
}
```
