### ISSUE TITLE
(aws_events): L2 Construct support for EventBusPolicy

### ISSUE THREAD

**Issue by hassaku63** [aws/aws-cdk#23021]
### Describe the feature

Provide the way to attach EventBusPolicy to EventBus on L2 construct.

### Use Case

Support for the use cases presented in the document below

https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-event-bus-perms.html

### Proposed Solution

According to other service that has resouce based policy such as SNS and SQS, service specific (resource based) Policy class is available and service class provides "addToResourcePolicy()" method.

e.x) addToResourcePolicy method in Topic class and TopicPolicy class

- https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_sns.Topic.html#addwbrtowbrresourcewbrpolicystatement
- https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_sns.TopicPolicy.html

> All AWS resources that support resource policies have a method called addToResourcePolicy(), which will automatically create a new resource policy if one doesn't exist yet, otherwise it will add to the existing policy.

Follow the above, like SNS and SQS, I think it would be a good idea to provide an addToResourcePolicy method for EventBus.

```typescript
const eventBus = new events.EventBus(this, 'MyEventBus', {
    eventBusName: 'my-event-bus',
});

eventBus.addToResourcePolicy(
    new iam.PolicyStatement({
        effect: iam.Effect.ALLOW,
        actions: ['events:PutEvents'],
        principals: [new iam.AccountPrincipal('123456789012')],
        resources: [eventBus.eventBusArn],
    })
);
```

### Other Information

A similar topic was discussed in #22080 

However, it looks like vague whether the goal of this issue is "to create or add a resource-based policy for EventBus", so I created a new feature request issue.

### Acknowledgements

- [X] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### CDK version used

v2.51.0

### Environment details (OS name and version, etc.)

Mac OS 12.4

**Comment by peterwoodworth** [comment]
This is definitely something we should support, thank you for the feature request 🙂

**Comment by hassaku63** [comment]
I will try writing RFC
