### ISSUE TITLE
Calling Python Lambda from typscript based cdk project

### ISSUE THREAD

**Issue by vjindalradialtheory** [aws/aws-cdk#2303]
Hi,

Can i integrated Python  based Lambda in typscript based cdk project

**Comment by rix0rrr** [comment]
Hi there,

We'd be happy to help you out, but GitHub issues is not a support forum. There are websites much better suited for that, such as StackOverflow. If you could please [ask that same question again on StackOverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk) and paste the link to it here, we will answer it for you over there.
