### ISSUE TITLE
RDS: gp3 support

### ISSUE THREAD

**Issue by sander-su** [aws/aws-cdk#23036]
### Describe the feature

GP3 is now available for RDS:
https://aws.amazon.com/about-aws/whats-new/2022/11/amazon-rds-general-purpose-gp3-storage-volumes/

### Use Case

GP3 is faster and cheaper

### Proposed Solution

Add GP3 to the storage enums

https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/aws-rds/lib/instance.ts#L260

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.51.1

### Environment details (OS name and version, etc.)

Win 10

**Comment by pahud** [comment]
Thank you for your PR. This is definitely a great feature!
