### ISSUE TITLE
(CDK Bootstrapping): Add kms encryption key arn as argument for cdk bootstrap

### ISSUE THREAD

**Issue by sanjaymenon7** [aws/aws-cdk#23032]
### Describe the feature

When bootstrapping an account I should be able to provide an AWS KMS key Arn with a flag like `--bootstrap-kms-key-arn`

Currently the flag `--bootstrap-kms-key-id` only takes the KeyId of a KMS-CMK key which needs to be present in the same account and in the same Region.

Currently, in the bootstrap template, the description for FileAssetsBucketKmsKeyId is given below 

![CDKIssueScreenshot1](https://user-images.githubusercontent.com/22540098/203285789-e85a44bc-f0f2-4de8-85a8-9b135485004e.png)

It is used in two places as given below 

![CDKIssueScreenshot2](https://user-images.githubusercontent.com/22540098/203285947-b42b964c-eba7-405b-ad1e-c7338766ce44.png)

![CDKIssueScreenshot3](https://user-images.githubusercontent.com/22540098/203285963-acd54860-0ccd-42b9-bb73-6388b54f9923.png)

If we give a Key Arn it will break the FilePublishingRoleDefaultPolicy.

So if we have a flag like `--bootstrap-kms-key-arn` in the AWS bootstrapping CLI we could provide a fully qualified AWS KMS-CMK Key Arn which should be properly added in two places:
1.  The Key Arn should be added as the default encryption key for the bucket.
2. The Key Arn should be added properly to the policies.

### Use Case

We as a team provides centralized encryption key to our customers.

These keys are present in a central account and replicated across regions. And used across accounts.

When we provide these for our customers to use they should be able to encrypt their CDK deployment buckets with these centralized keys.

Currently, our customers will not be able to use these keys as currently, we can only provide the KeyId when bootstrapping.

Also, this is very restrictive when it is expected to create a key in a particular region to be used when bootstrapping. 
The CDK users should be allowed to provide a Key Arn.

### Proposed Solution

Add a new flag in the cdk bootstrap cli `--bootstrap-kms-key-arn`
Where we can give an existing kms cmk key arn

### Other Information

Currently, the workaround is to provide a synthesizer when deploying each stack.

`synthesizer: new DefaultStackSynthesizer({ fileAssetsBucketName:'<centralized-key-encrypted-bucket-name>', }),`workaround

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.30.0

### Environment details (OS name and version, etc.)

MacOs Ventura 13.0.1

**Comment by peterwoodworth** [comment]
Thanks for reporting this feature request,

At the least, we will need to update the description of the parameter here, as it cannot take in the arn https://github.com/aws/aws-cdk/blob/6f4dcfd74a33dcf04d15e3c5a1c1b53bcfe0dbde/packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml#L25

As for the feature request, it seems valid! Would need to modify the template a little bit to make sure the template is built correctly depending on if either the ID or ARN is passed, but that doesn't seem like too much trouble.

I am marking this issue as p2, which means that we are unable to work on this immediately.

We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://cdk.dev) to solicit support for reprioritization.

Check out our [contributing guide](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) if you're interested in contributing yourself - there's a low chance the team will be able to address this soon but we'd welcome any PR submission

**Comment by indrora** [comment]
I'm going to add a dissenting opinion on this one. 

While a reasonable ask, the use case here is likely unsafe. KMS keys should be partitioned and used for as small a scope as is required. I'm going to tag this as requiring a security review as well.

**Comment by peterwoodworth** [comment]
I'm sorry to say but we won't be implementing this. If you need to bootstrap many accounts I recommend checking out [this guide](https://aws.amazon.com/blogs/mt/bootstrapping-multiple-aws-accounts-for-aws-cdk-using-cloudformation-stacksets/). Else, be sure to check our bootstrapping documentation to see how to modify the template yourself.
