### ISSUE TITLE
(trigger): Allow trigger to work with Lambda functions with long timeouts

### ISSUE THREAD

**Issue by DerkSchooltink** [aws/aws-cdk#23058]
### Describe the feature

Considering the following resources:

```
const lambda = new GoFunction(this, 'LambdaWithLongTimeout', {
    entry: '../../test',
    timeout: Duration.minutes(15),
});

new Trigger(this, 'LambdaTrigger', {
    handler: lambda,
});
```

Considering the timeout of 15 minutes of the Lambda to trigger on build, I would expect the trigger to be able to deal with this. However, the SDK in the trigger Lambda times out after 2 minutes:

```
(LambdaTriggerLambdaWithLongTimeoutA4E48B8F) Received response status [FAILED] from custom resource. Message returned: TimeoutError: Connection timed out after 120000ms
```

I see two potential solutions:

1. Add the option to specify an override for the Lambda SDK client config timeout in the trigger Lambda
2. Add the option to specify an override for the invocation type (to Event) of the Lambda to be triggered

Or a combination of both as optional parameters! I can see a use-case for specifying invocation type Event for a fire-and-forget trigger, separate from increasing timeouts on the trigger Lambda.

### Use Case

For Lambda functions that run longer than 2 minutes, I want to execute a trigger for them at build-time. There is no reason to assume all Lambda functions finish within this 2 minute window. 

### Proposed Solution

Considering the previous resources, I propose a solution that would allow the following:

```
const lambda = new GoFunction(this, 'LambdaWithLongTimeout', {
    entry: '../../test',
    timeout: Duration.minutes(15),
});

new Trigger(this, 'LambdaTrigger', {
    handler: lambda,
    timeout: Duration.minutes(15),
    invocationType: 'Event',
});
```

Where `timeout` and `invocationType` are both optional parameters in the properties of `Trigger`. 

If `timeout` is not set, it will default to the default timeout of the AWS SDK configuration timeout (2 minutes).

If `invocationType` is not set, it will default `RequestResponse`, which is a default for creating Lambdas, and guarantees backwards compatibility with existing usages of `Trigger`.

### Acknowledgements

- [x] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.51.1

### Environment details (OS name and version, etc.)

MacOs Ventura 13.0.1

**Comment by pahud** [comment]
Yeah I believe it should be possible to expose the timeout property to the surface in TriggerOptions or TriggerProps. Thanks for that and we'll be happy to review the PR.

**Comment by khushail** [comment]
Implemented in this PR - https://github.com/aws/aws-cdk/pull/24435
