### ISSUE TITLE
DynamoEventSource: Incorrect code example for filter property

### ISSUE THREAD

**Issue by lewisrichardson** [aws/aws-cdk#23057]
### Describe the issue

When applying a filter property from the given code example, an error is thrown by CloudFormation.

```ts
fn.addEventSource(new eventsources.DynamoEventSource(table, {
  filters: [{ eventName: aws_lambda.FilterRule.isEqual('INSERT') }],
}));
```

`Resource handler returned message: "Invalid request provided: Invalid filter pattern definition.`

When using it in this format, it works as expected.

```ts
fn.addEventSource(new eventsources.DynamoEventSource(table, {
  filters: [aws_lambda.FilterCriteria.filter({ eventName: aws_lambda.FilterRule.isEqual('INSERT') })],
}));
```

### Links

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda_event_sources.DynamoEventSource.html

**Comment by peterwoodworth** [comment]
Thanks for letting us know,

This is found in our Lambda readme https://github.com/aws/aws-cdk/blob/v2.51.1/packages/%40aws-cdk/aws-lambda/README.md

If you'd like to fix this for us feel free 🙂
