### ISSUE TITLE
@aws-cdk/aws-iam:standardizedServicePrincipals: produces invalid templates when using some L2 constructs

### ISSUE THREAD

**Issue by lowpast** [aws/aws-cdk#23066]
### Describe the bug

When enabling the feature flag @aws-cdk/aws-iam:standardizedServicePrincipals and using the L2 construct for AppSync "AppsyncFunction", the synthesized template is invalid. 

### Expected Behavior

The produced assume role policy is valid
    "AssumeRolePolicyDocument": {
     "Statement": [
      {
       "Action": "sts:AssumeRole",
       "Effect": "Allow",
       "Principal": {
        "Service": "appsync.amazonaws.com"
       }
      }

### Current Behavior

An invalid assume role policy is produced
     "Statement": [
      {
       "Action": "sts:AssumeRole",
       "Effect": "Allow",
       "Principal": {
        "Service": "appsync"
       }
      }

As "Service": "appsync" is not a valid principal.

### Reproduction Steps

Enable the feature flag @aws-cdk/aws-iam:standardizedServicePrincipals
Create a new AppsyncFunction
npx cdk synth
npx cdk deploy <stack_name>

### CDK CLI Version

2.51.1

### Node.js Version

16.18

### OS

OSx, AmazonLinux2

### Language

Typescript

**Comment by peterwoodworth** [comment]
We've addressed this issue, see here https://github.com/aws/aws-cdk/issues/23035
