### ISSUE TITLE
ec2: incorrect error: client CIDR cannot overlap with local CIDR of the VPC

### ISSUE THREAD

**Issue by mdnorman** [aws/aws-cdk#23077]
### Describe the bug

When using `ClientVpnEndpoint`, I am getting the following error:

> The client CIDR cannot overlap with the local CIDR of the VPC

However, the CIDR blocks don't overlap. The issue appears to be because I am using the following to get the VPC:

`const vpc = Vpc.fromLookup(this, 'vpc', { vpcId });`

This works fine when I create the VPN in the same stack I'm creating the VPC.

To confirm, my VPC cidr block is `10.4.0.0/16` and the VPC client cidr block is `10.132.0.0/22`.

However, when using `Vpc.fromLookup(...)`, I printed out the `vpc.vpcCidrBlock`, and it is `1.2.3.4/5`, which looks like a dummy default.

### Expected Behavior

The CIDR block cannot be checked at runtime because then the VPC must be created in the same stack.

### Current Behavior

I am getting the following error:

```
Error: The client CIDR cannot overlap with the local CIDR of the VPC
    at new ClientVpnEndpoint (/Users/mnorman/Projects/companies/norrio/infra-vpn/node_modules/aws-cdk-lib/aws-ec2/lib/client-vpn-endpoint.js:1:3159)
```

### Reproduction Steps

```
    const vpc = Vpc.fromLookup(this, 'vpc', { vpcId });
    new ClientVpnEndpoint(this, 'clientVpnEndpoint', { vpc, ... };
```

### CDK CLI Version

2.51.1 (build 3d30cdb)

### Node.js Version

18.7.0

### OS

MacOS

### Language

Typescript

**Comment by peterwoodworth** [comment]
You need to make sure your context is synthesized first - I would recommend running `cdk synth` once the `fromLookup` is defined and before any references are made to the Vpc. I was just attempting this, and was running into the same error with the same dummy value, but removing the reference in `ClientVpnEndpoint` allowed me to synth and create `cdk.context.json`. Readding the reference should work now that the context has been looked up and stored in your application.

I've reported this bug before [here](https://github.com/aws/aws-cdk/issues/22025), will continue to track this bug there. Thanks for reporting!

**Comment by mdnorman** [comment]
Thank you for the detail. I'm new to CDK so I didn't know about this workaround. I'll watch the other issue.
