### ISSUE TITLE
(aws-apigateway): Response parameter literals automatically quoted

### ISSUE THREAD

**Issue by jaco-smit** [aws/aws-cdk#23073]
### Describe the bug

As part of commit https://github.com/aws/aws-cdk/commit/fc9e1428cef0d292d918c47a06f9131cd5a04f92, any response parameter is automatically quoted. This breaks some API Gateway supported features like injecting fields from the request.

See https://docs.aws.amazon.com/apigateway/latest/developerguide/request-response-data-mappings.html#mapping-response-parameters

Specifically we can no longer specify something like the following since it will be quoted:

```
...
"requestParameters" : {
            
    "integration.request.path.integrationPathParam" : "method.request.header.methodRequestHeaderParam",        
    "integration.request.querystring.integrationQueryParam" : "method.request.multivaluequerystring.methodRequestQueryParam"
            
}
...
                       
```

### Expected Behavior

Response parameters should not be automatically quoted to allow for using variables.

### Current Behavior

Response parameters are automatically quoted which means native API Gateway parameters cannot be used.

### Reproduction Steps

```
api.addGatewayResponse(responseType, {
    responseHeaders: {
       "method.response.header.location":  "integration.response.body.redirect.url"
    }
})
```

Produces:
```
{
   "method.response.header.location":  "'integration.response.body.redirect.url'"
}
```

### Possible Solution

Revert commit https://github.com/aws/aws-cdk/commit/fc9e1428cef0d292d918c47a06f9131cd5a04f92

### CDK CLI Version

2.50

### Node.js Version

14

### OS

MacOS

### Language

Typescript

### Language Version

Typescript 4.8.4

**Comment by jaco-smit** [comment]
I see this is already reverted here: https://github.com/aws/aws-cdk/commit/dc8f87a

**Comment by peterwoodworth** [comment]
Yep, this was reverted. Thanks for reporting!
