### ISSUE TITLE
SNS: payload-based message filtering

### ISSUE THREAD

**Issue by brennanho** [aws/aws-cdk#23079]
### Describe the feature

AWS introduced payload-based message filtering: https://aws.amazon.com/blogs/compute/introducing-payload-based-message-filtering-for-amazon-sns/. Would be awesome to see support for this in CDK.

### Use Case

Filtering out messages by payload attributes. Often, SNS owners from away teams do not supply the sufficient message attributes to filter out messages. This change would allow SNS subscribers (SQS subscribing to SNS in my case) to filter messages regardless of whether the SNS owner has configured any message attributes.

### Proposed Solution

Have the option to choose `FilterPolicyScope` when subscribing to an SNS topic i.e. either `MessageBody` or `MessageAttributes`. See: https://docs.aws.amazon.com/sns/latest/dg/sns-message-filtering.html. I was thinking to add `filterPolicyScope` to the `SubscriptionFilter` class and then being able to switch `filterPolicyScope` to either `MessageBody` or `MessageAttributes`. 

**Before:**
```
  Topic.fromTopicArn(
      myStack,
      "myStackId",
      "arn:aws:sns:us-east-1:..."
  ).addSubscription(new SqsSubscription(myLambda.inputQueue, { filterPolicy: {...} }));
```

**After:**
```
  Topic.fromTopicArn(
      myStack,
      "myStackId",
      "arn:aws:sns:us-east-1:..."
  ).addSubscription(new SqsSubscription(myLambda.inputQueue, { filterPolicyScope: "MessageBody", filterPolicy: {...} }));
```

### Other Information

**Links**
- SNS Message Filtering: https://docs.aws.amazon.com/sns/latest/dg/sns-message-filtering.html
- Payload-based Message Filtering blog post: https://aws.amazon.com/blogs/compute/introducing-payload-based-message-filtering-for-amazon-sns/
- Example Filter Policies: https://docs.aws.amazon.com/sns/latest/dg/example-filter-policies.html
- CDK Docs: https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-sns.SubscriptionFilter.html

### Acknowledgements

- [X] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### CDK version used

2.38.1 (aws-cdk-lib)

### Environment details (OS name and version, etc.)

MacOS 12.3.1

**Comment by peterwoodworth** [comment]
Thanks for the request, it seems like CloudFormation support should be live already with this feature so we should be good to start working on it.

**Comment by brennanho** [comment]
> Thanks for the request, it seems like CloudFormation support should be live already with this feature so we should be good to start working on it.

I can create a PR for this if the effort is small. Do you know where the changes would need to be made?

**Comment by brennanho** [comment]
PR: https://github.com/aws/aws-cdk/pull/23108
