### ISSUE TITLE
aws-cdk: make "cdk notices" show only unacknowledged notices

### ISSUE THREAD

**Issue by enummela-diligent** [aws/aws-cdk#23078]
### Describe the feature

Make it possible for `cdk notices` to show only the unacknowledged notices. Currently it lists "the notices that are relevant to the current CDK repository, regardless of context flags or notices that have been acknowledged" [[link](https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk/README.md#cdk-notices)].

### Use Case

Checking if there are any unacknowledged notices in CI checks. Example `package.json`:

```json
{
  "scripts": {
    "test": "jest",
    "notices": "notices=$(cdk notices --unacknowledged-only); [ -z \"$notices\" ]",
    "ci": "npm test && npm run notices"
  }
}
```

### Proposed Solution

One possible way to implement could be adding an `--unacknowledged-only` flag. 

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.50.0 (build 4c11af6)

### Environment details (OS name and version, etc.)

macOS Monterey 12.6.1

**Comment by peterwoodworth** [comment]
Thanks for this request, it would be nice if we supported this 🙂 

I am marking this issue as p2, which means that we are unable to work on this immediately.

We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://cdk.dev) to solicit support for reprioritization.

Check out our [contributing guide](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) if you're interested in contributing yourself - there's a low chance the team will be able to address this soon but we'd be happy to review a PR 🙂
