### ISSUE TITLE
(eks): Documentation does not refer to the latest version of supported Kubernetes

### ISSUE THREAD

**Issue by markusl** [aws/aws-cdk#23072]
### Describe the issue

Documentation has:

```ts
const cluster = new eks.Cluster(this, 'hello-eks', {
  version: eks.KubernetesVersion.V1_21,
});
```

When it should likely be:

```ts
    const cluster = new eks.Cluster(this, 'hello-eks', {
      version: eks.KubernetesVersion.V1_23,
      kubectlLayer: new KubectlV23Layer(this, 'kubectl'),
    });
```

or explain why not to use the latest version.

### Links

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_eks-readme.html

**Comment by pahud** [comment]
Yeah I didn't see any reason we should not update it. Is this something you are interested pick up as a PR? Happy Thanksgiving day!

**Comment by markusl** [comment]
@pahud I think the documentation update should be done by the authors of KubectlV23Layer which seem to be @kaizencc and @rix0rrr 

What is weird is that the NPM library says "This library is currently under development. Do not use!" but the CDK constructs label says it's stable https://www.npmjs.com/package/@aws-cdk/lambda-layer-kubectl-v24

Anyone from the CDK team want to clarify this?

**Comment by kaizencc** [comment]
@markusl clarification: please use! will remove the scary comment, thanks for alerting me to it.
