### ISSUE TITLE
rds: use user-defined security group for db user rotation function

### ISSUE THREAD

**Issue by clueleaf** [aws/aws-cdk#23086]
### Describe the feature

When using `addRotationSingleUser` or `addRotationMultiUser` from rds module, the security group of the rotation Lambda function is always automatically created.

Therefore it is difficult for Secrets Manager endpoint to restrict access only to the security group of the rotation Lambda function. You have to allow all traffic to the Secrets Manager endpoint from within the VPC.

### Use Case

We will be able to limit access to the Secrets Manager endpoint from a single security group.

### Proposed Solution

The props of `secretsmanager.SecretRotation` class already has a `securityGroup` property. Just add `securityGroup` property to the options of `addRotationSingleUser` and `addRotationMultiUser` methods and pass it to `secretsmanager.SecretRotation`.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.50.0

### Environment details (OS name and version, etc.)

macOS Ventura 13.0

**Comment by peterwoodworth** [comment]
Thanks a bunch for creating a PR for this, we've left a review 🙂
