### ISSUE TITLE
aws-codebuild: The default image of aws/codebuild/standard:1.0 results in slow provisioning times

### ISSUE THREAD

**Issue by richardm** [aws/aws-cdk#23096]
### Describe the bug

Running a Hello World CodeBuild Project consistently takes 2+ minutes to provision yet only seconds to execute. This appears to be due to the AWS CDK using aws/codebuild/standard:1.0 by default. According to the references below, the [latest image for Ubuntu 18.04](https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-available.html) is aws/codebuild/standard:4.0, and it appears that only the latest images are cached.

![166-seconds-to-provision](https://user-images.githubusercontent.com/97908/204068213-0442260b-cff4-47be-934c-cc02fec267fa.png)

![default-standard-1](https://user-images.githubusercontent.com/97908/204068227-90fa118a-77c0-474f-9cdc-a4bebc9b3450.png)

### Expected Behavior

Per the [AWS CodeBuild docs](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_codebuild-readme.html#environment): "By default, projects use a small instance with an Ubuntu 18.04 image. You can use the environment property to customize the build environment."

I expected the default image to be cached since presumably most people new to the CDK (like me) would use the default. I further expected it to be the latest Ubuntu 18.04 image, which appears to be aws/codebuild/standard:4.0.

### Current Behavior

The default image used is aws/codebuild/standard:1.0, which takes 2+ minutes to provision.

![default-standard-1](https://user-images.githubusercontent.com/97908/204068416-36e0ac20-55f4-48b6-875a-4d45f7300b60.png)

### Reproduction Steps

```
return new Project(this, 'Project', {
  environment: {
    // Reproduce by not specifying any environment properties
  }
});

```

### Possible Solution

I provided a value for the build image, and it reduced provisioning times to under 30 seconds, which is a substantial improvement:
```
return new Project(this, 'Project', {
  environment: {
    buildImage: LinuxBuildImage.STANDARD_4_0
  }
});
```
![Screenshot 2022-11-25 at 7 08 26 PM](https://user-images.githubusercontent.com/97908/204068286-67fd8fee-6c04-4178-81c0-ee356b9dc8dc.png)

![Screenshot 2022-11-25 at 7 09 12 PM](https://user-images.githubusercontent.com/97908/204068298-e1ee75fe-d575-446c-baae-0c72064cc227.png)

### CDK CLI Version

2.51.1 (build 3d30cdb)

### Node.js Version

v14.18.2

### OS

Mac OS Ventura 13.0.1

### Language

Typescript

**Comment by richardm** [comment]
I should have verified this before opening the ticket, but I just ran `npm install -g aws-cdk@latest` to update to the latest version, and the same issue still exists.

**Comment by peterwoodworth** [comment]
This is defined here https://github.com/aws/aws-cdk/blob/3d30cdb55620a5f2a34944d21edca770e90ff7c5/packages/%40aws-cdk/aws-codebuild/lib/project.ts#L1042

Something like this we'd need to have a feature flag to adjust, in case anyone is using the default value intentionally and doesn't desire that to change

**Comment by richardm** [comment]
Is there a reference that documents the planned release schedule or planned end of maintenance for these `codebuild/standard` images? I found the [AWS-codebuild-docker-images readme](https://github.com/aws/aws-codebuild-docker-images#image-maintenance) which claims that the `codebuild/standard` images below 4.0 are no longer maintained or updated, but it's unclear how much longer 4.0 will receive support. If the default gets changed to 4.0, I wonder if we will soon find ourselves back in this same situation of the default image not being cached and another round of breaking changes required to update the default. Perhaps if the default gets changed, it should be to 5.0 or later, but even that simply delays the need to repeat this process.

From an end user standpoint, I don't mind adding a couple of lines to use a different image. The issue is there was nothing warning me that I should not use the default settings -- or that they referred to an unsupported image. At minimum, this could this be called out more clearly in [the docs](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_codebuild-readme.html#environment).

How about also marking `LinuxBuildImage.STANDARD_1_0` - `LinuxBuildImage.STANDARD_3_0` as deprecated? That seems appropriate given that the images are no longer supported or maintained, and I see this has already been done for `AMAZON_LINUX_2_ARM` (though possibly for different reasons). That doesn't solve the problem for projects using the defaults, but it does provide a gentle nudge for those who at one point hard-coded the image value and just haven't gotten around to upgrading.

When I run `cdk synth` with the default environment settings, it informs me that I'm using the 1.0 image. How about having `cdk synth` or `cdk deploy` warn anyone using lower than 4.0 that the image they are using is no longer maintained and recommending an upgrade to 4:0 or higher? This would encourage everyone to update to a newer (cached) image without the downside of breaking changes. This is also a more sustainable long-term solution to this issue, since a `LinuxBuildImage.MINIMUM_SUPPPORTED_VERSION` const could be easily updated once 4.0 is no longer supported.

I'm happy to work on a PR for some of these changes but wanted to confirm direction first.

**Comment by peterwoodworth** [comment]
Thanks again for the request and your input. If you're still interested in continuing this discussion, let's do so in #16707
