### ISSUE TITLE
[apigateway]: Configured responseHeaders in apigateway.GatewayResponse doesn't support mapping

### ISSUE THREAD

**Issue by grmorozov** [aws/aws-cdk#23105]
### Describe the bug

GatewayResponse parameter mapping is broken after adding forced quotation of all parameters in [this PR](https://github.com/aws/aws-cdk/pull/22637).

Previously, request parameters could be mapped to response parameters, for example headers.
That's it `method.request.header.<name>` should be a valid value for a response parameter. With forced quotation around parameter values, `method.request.header.<name>` becomes a string value and doesn't work.

### Expected Behavior

CDK should not add extra quotes for GatewayResponse parameters. It should be possible to use request parameter values in response headers.

### Current Behavior

CDK forces quotes around GatewayResponse parameter values. Mapping of request parameters in the response doesn't work.

### Reproduction Steps

```typescript
import * as apigateway from "aws-cdk-lib/aws-apigateway";
...
const api = new apigateway.RestApi(...);

api.addGatewayResponse(`gatewayResponse`, {
      type: apigateway.ResponseType.ACCESS_DENIED,
      responseHeaders: {
        'Access-Control-Allow-Origin': 'method.request.header.origin',
        'Access-Control-Allow-Credentials': "'true'",
        'Access-Control-Expose-Headers': "'x-amzn-errortype'",
      },
    })
```

### Possible Solution

Reverting changes from [this PR](https://github.com/aws/aws-cdk/pull/22637) should solve the issue.

### CDK CLI Version

2.48.0

### Node.js Version

v16.18.0

### OS

macOS Monteray

### Language

Typescript

### Other information

The [documentation](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-gatewayResponse-definition.html) about API Gateway responses doesn't clearly describe the use case of using request parameters in the response. More clear statement with an example can be found in [OpenAPI documentation](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-swagger-extensions-gateway-responses.gatewayResponse.html).

**Comment by yuyokk** [comment]
Changes were reverted https://github.com/aws/aws-cdk/pull/23037

**Comment by grmorozov** [comment]
[23037](https://github.com/aws/aws-cdk/pull/23037) was merged 6 days ago. However with the latest version (2.52.0) can still reproduce the issue.

**Comment by peterwoodworth** [comment]
The revert PR wasn't part of our `2.52.0` release, only one change made it through. The next version we release I would expect to have all the changes made since `2.51.0` launched. Feel free to ping me or reopen this if the bug is still present next release

**Comment by frikille** [comment]
@peterwoodworth Seems like with the latest release (v2.53.0) this is still not fixed: https://github.com/aws/aws-cdk/blob/v2.53.0/packages/@aws-cdk/aws-apigateway/lib/gateway-response.ts

**Comment by peterwoodworth** [comment]
Yes, this release was also a special case where we only merged one specific fix. Our next standard release I should say... I would expect next week
