### ISSUE TITLE
CloudWatch: Background option for TextWidget

### ISSUE THREAD

**Issue by IamVladislav** [aws/aws-cdk#23114]
### Describe the feature

TextWidget supports field background with two values - solid or transparent. It will be nice, if we can set this field from CDK too. 
https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/CloudWatch-Dashboard-Body-Structure.html#CloudWatch-Dashboard-Properties-Text-Widget-Object

### Use Case

This field makes TextWidget prettier to use as header for some pack of metrics below. 

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.47.0

### Environment details (OS name and version, etc.)

macOS 12.6 M1

**Comment by peterwoodworth** [comment]
Thanks for the feature request @IamVladislav,

We should be able to support this very similarly to how we support markdown here https://github.com/aws/aws-cdk/blob/3d30cdb55620a5f2a34944d21edca770e90ff7c5/packages/%40aws-cdk/aws-cloudwatch/lib/text.ts#L51

I am marking this issue as p2, which means that we are unable to work on this immediately.

We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://cdk.dev) to solicit support for reprioritization.

Check out our [contributing guide](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) if you're interested in contributing yourself - there's a low chance the team will be able to address this soon but we'll try to review a PR 🙂

**Comment by DeerajTheepshi** [comment]
@peterwoodworth , I have raised a PR for this issue. Could you please have a look at it whenever possible ?
