### ISSUE TITLE
aws-cdk-lib/aws-ecs: inconsistent documentation and typing for "TaskDefinitionProps"

### ISSUE THREAD

**Issue by ryanolee** [aws/aws-cdk#23117]
### Describe the bug

Documentation references the [FargateTaskDefinition](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ecs.FargateTaskDefinition.html) where the following fields have inconsistent documentation to type definitions
- `cpu`
- `memoryMiB`
Fields are referenced in documentation as integers but are typed as strings.
![image](https://user-images.githubusercontent.com/17767073/204307982-9017bd8d-6357-4a9e-b31c-e47864f4c050.png)
(Could not find this in repo but is under aws-cdk-lib/aws-ecs/lib/base/task-definition.d.ts:137)

### Expected Behavior

Either:
- [FargateTaskDefinitionProps](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ecs.FargateTaskDefinition.html)  having "number" typed fields for`cpu` and `memoryMiB`
- Documentation being updated to have the inputs referenced as strings.

### Current Behavior

```
Type 'number' is not assignable to type 'string'.ts(2322)
task-definition.d.ts(137, 14): The expected type comes from property 'cpu' which is declared here on type 'TaskDefinitionProps'
```

### Reproduction Steps

See 
```ts
import * as ecs from "aws-cdk-lib/aws-ecs";
import { Construct } from "constructs";

export class TestTask extends Construct {
  public readonly taskDefinition: ecs.IFargateTaskDefinition;
  constructor(scope: Construct, id: string) {
    super(scope, id);

    this.taskDefinition = new ecs.TaskDefinition(this, "TestTaskDefinition", {
      cpu: 256, // This does not work
      compatibility: ecs.Compatibility.FARGATE,
    });
  }
}
```

### Possible Solution

Either of the approaches listed in the "current behaviour"

### CDK CLI Version

2.51.1 (build 3d30cdb)

### Node.js Version

v16.16.0

### OS

Ubuntu 22.04.1

### Language

Typescript

### Language Version

typescript (3.9.7)

**Comment by peterwoodworth** [comment]
While it's inconvenient that we mismatch number and string types between these constructs, I don't see any bugs or inaccuracies in our documentation. [`FargateTaskDefinition`](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ecs.FargateTaskDefinition.html#memorylimitmib) takes in numbers, and the documentation snippets show this. Similarly, [`TaskDefinition`](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ecs.TaskDefinition.html#cpu) takes in strings, and the documentation snippets show this.

Is there anything I'm missing?

**Comment by ryanolee** [comment]
Nope sorry, This is just me conflating the [TaskDefinition](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ecs.TaskDefinition.html#cpu) and [FargateTaskDefinition](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ecs.FargateTaskDefinition.html#memorylimitmib) (And being completely blind to it somehow all the way until here :man_facepalming: ). There may be something so say surrounding consistency within the typing of these properties but that is well beyond the purview of this issue. Sorry for wasting you time on this one :bow: !
