### ISSUE TITLE
(@aws-cdk.aws-glue-alpha): Glue table separator + skip header

### ISSUE THREAD

**Issue by aram-eskandari** [aws/aws-cdk#23132]
### Describe the issue

I have created a glue-table using `DataFormat.CSV` with version `aws-cdk.aws-glue-alpha==2.51.1a0` and python `3.7.13`. The code looks similar to:
<img width="350" alt="Screenshot 2022-11-29 at 01 36 55" src="https://user-images.githubusercontent.com/116629216/204409727-4e9d5c42-6195-4803-9c12-47b7e8588232.png">

Now I'm trying to adjust the parameters `skip.header.line.count` and `separatorChar`. Specifically I want to skip the 1st row and use a semicolon separator.

Using L1's, the code would look similar to:
<img width="500" alt="Screenshot 2022-11-29 at 01 27 19" src="https://user-images.githubusercontent.com/116629216/204408680-d0b3574c-d9de-45bf-8767-1f9be2ae35e6.png">

Looked through the L2-documentation but couldn't find anything regarding this, any tips?

On a separate note, there is a repeating sentence in the documentation:
<img width="500" alt="Screenshot 2022-11-29 at 01 42 39" src="https://user-images.githubusercontent.com/116629216/204410458-4ec1c9e9-8fa4-4074-abdf-687e5c413a62.png">

### Links

https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_glue_alpha/README.html#table

**Comment by aram-eskandari** [comment]
i've never used escape hatches will have to read up on it, thanks for your response and the pointer @peterwoodworth!

**Comment by markusl** [comment]
CDK code for reference:

```ts
    const resource = table.node.defaultChild as cfnglue.CfnTable;
    resource.addPropertyOverride('TableInput.StorageDescriptor.SerdeInfo', {
      Parameters: {
        'skip.header.line.count': '1',
      },
    });
```

**Comment by WtfJoke** [comment]
@markusl The `skip.header.line.count` property is a table property.
Therefore the code should look like:

```typescript
const cfnTable= table.node.defaultChild as cfnglue.CfnTable;
cfnTable.addPropertyOverride("TableInput.Parameters", {
    "skip.header.line.count": "1",
});
```

**Comment by WtfJoke** [comment]
@markusl The `skip.header.line.count` is a table properties and therefore should be set like:

```typescript
const cfnTable = table.node.defaultChild as CfnTable;
cfnTable.addPropertyOverride("TableInput.Parameters", {
    "skip.header.line.count": "1",
});
```

**Comment by markusl** [comment]
@WtfJoke Did you try that out? In the opening message, you can see @aram-eskandari setting the parameters for `StorageDescriptor` object. I also tested setting `TableInput.StorageDescriptor.SerdeInfo` and it seemed to work just fine and was visible in the AWS console. I wonder if the property can be set in two different places?

**Comment by WtfJoke** [comment]
@markusl yeah we tested this successfully. 
With your snippet it was in the serde properties instead of the table properties.

We have also serde properties overwritten:
```typescript
  /*
      Set additional serializer properties (since its not possible with the current L2 construct):
      - Switch serializer from OpenCSV to LazySimpleSerDe (OpenCSV supports only string).
      - Specify ',' as field separator (default is tab)
   */
  cfnTable.addPropertyOverride("TableInput.StorageDescriptor.SerdeInfo", {
      SerializationLibrary: "org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe",
      Parameters: {
          "field.delim": ",",
      },
  });
 ```
