### ISSUE TITLE
CfnInclude: Does not work with InstanceType JSON Array parameter

### ISSUE THREAD

**Issue by michanto** [aws/aws-cdk#23142]
### Describe the bug

Found a bug in CfnInclude!
I have a parameter, InstanceTypes, that is a comma delimited list.  When I import it using CfnInclude, it does not work.
Works:
```
  "InstanceTypes": {
   "Type": "CommaDelimitedList",
   "Default": "optimal, p3",
   "Description": "The instance types that may be launched"
  },
...
  "ComputeEnvironment": {
   "Type": "AWS::Batch::ComputeEnvironment",
   "Properties": {
    "ComputeResources": {
       "InstanceTypes": {
        "Ref": "InstanceTypes"
       },
...
```
Fails:
```
  "ComputeEnvironment": {
   "Type": "AWS::Batch::ComputeEnvironment",
   "Properties": {
    "Type": "MANAGED",
    "ComputeResources": {
       "InstanceTypes": "optimal,p3",
```
The first is the original template, the second is the template as imported by CfnInclude.
Error is:
```
Properties validation failed for resource ComputeEnvironment with message: #/ComputeResources/InstanceTypes: expected type: JSONArray, found: String
```

### Expected Behavior

I expect the CfnInclude to do the right thing with CommaDelimitedList parameters.

### Current Behavior

CfnInclude substitutes the parameter incorrectly, resulting in a template that will not work.

### Reproduction Steps

Hmm.  Good question. I will add shortly.

### CDK CLI Version

2.53.0 (build 7690f43)

### Framework Version

2.17.0

### Node.js Version

^14.18.13

### OS

AL2

### Language

Typescript

### Language Version

4.7.4

**Comment by peterwoodworth** [comment]
Can you post reproduction steps please? At a glance, this doesn't seem to be an error and seems to be how it's [documented to work](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.cloudformation_include.CfnInclude.html#parameters). I'm unsure what the exact expected behavior is you think you should be getting

**Comment by michanto** [comment]
So what I am doing is calling describeStacks, getting the parameter names and values, and passing those to CfnInclude.  

That does not work, because describeStacks returns InstanceTypes as a string, not as an array. 

But I see what you are saying.  You are saying that I should just check the parameter type and convert it myself.  The use-case I describe is not really your use case.
