### ISSUE TITLE
(integ-runner): npm lists integ-runner@1.x.x package  as 'latest'

### ISSUE THREAD

**Issue by oleksii-donoha** [aws/aws-cdk#23144]
### Describe the bug

We're using automation to bump up the CDK versions, including `integ-runner`. Currently, we look for the latest version of the CDK packages via a combo of `npm outdated $PKG_NAME` and `npm v $PKG version`. The last run of this automation produced the situation, where the main lib was 2.53.0, and the `integ-runner` - 1.181.1. Which produced an error in the test run:

```
Error: Unsupported feature flag '@aws-cdk/core:enableStackNameDuplicates'. This flag existed on CDKv1 but has been removed in CDKv2. CDK will now behave as the same as when the flag is enabled.
```

### Expected Behavior

The latest `integ-runner` version should match the latest `aws-cdk-lib` version (`2.53.0`).

### Current Behavior

Right now if you run `npm v @aws-cdk/integ-runner version` you will get `1.181.1`

### Reproduction Steps

Run `npm v @aws-cdk/integ-runner version` 

### Possible Solution

Package version `2.53.0` exists, but is not labeled as the latest. Probably whichever npm package publishing process was last to be complete gets to label the package version. Since 1.181.1 is a patch release, which doesn't have a corresponding 2.x release, it was probably the only one to run, so marked its version as the latest.

The solution would be to never mark 1.x packages as the latest.

### Additional Information/Context

Exact same issue as here: https://github.com/aws/aws-cdk/issues/21268

### CDK CLI Version

2.53.0 (build 7690f43)

### Node.js Version

v16.18.1

### OS

Fedora 37

### Language

Typescript

### Language Version

4.8.3

**Comment by peterwoodworth** [comment]
Can confirm looking at the npm package that the latest version displays v1 - [integ-runner](https://www.npmjs.com/package/@aws-cdk/integ-runner), [integ-tests](https://www.npmjs.com/package/@aws-cdk/integ-tests)

This isn't a problem for our other packages because I don't think any other packages we publish are being published for both v1 and v2, though I might be wrong about that. Thanks for reporting!

**Comment by helbing** [comment]
Same issue, I use `integ-runner`, `integ-tests-alpha`, `aws-cdk-lib`. It reports an error: 

```
Error: Unsupported feature flag '@aws-cdk/core:enableStackNameDuplicates'. This flag existed on CDKv1 but has been removed in CDKv2. CDK will now behave as the same as when the flag is enabled.
```

How can I run `integ-tests-alpha` test cases?

```
> pnpm v @aws-cdk/integ-tests-alpha version
2.67.0-alpha.0

> pnpm v @aws-cdk/integ-runner version
1.195.0

> pnpm v aws-cdk-lib version
2.67.0
```

**Comment by helbing** [comment]
> The workaround is to make sure you depend on `@aws-cdk/integ-runner@^2` and not `latest`.

Thx
