### ISSUE TITLE
RDS: spin up / down an Aurora DB from RDS Snapshot

### ISSUE THREAD

**Issue by ccfife** [aws/aws-cdk#2316]
Customer request to spin up / down an Aurora DB from RDS Snapshot, which is explicitly called out as unsupported in the @aws-cdk/aws-rds README.md

**Comment by eladb** [comment]
I believe this is currently being worked on via #2187

**Comment by eladb** [comment]
@jogold FYI

**Comment by fimbulvetr** [comment]
Seems like you could also do a `addPropertyOverride` if you're so inclined.

Something like:
`
let l1Rds = l2Rds.node.findChild("Resource") as rds.CfnDBCluster;
l1Rds.addPropertyOverride('SnapshotIdentifier', 'snap-123456');
`
See changelog under 0.10.0 for the official example.

**Comment by SomayaB** [comment]
Closing since it seems to have been addressed by #2187. Feel free to reopen.
