### ISSUE TITLE
aws-lambda-nodejs: Not working with NestedStack

### ISSUE THREAD

**Issue by Depaa** [aws/aws-cdk#23181]
### Describe the bug

When creating lambdas with **aws-lambda-nodejs** in a **NestedStack** it takes the wrong entry point to the lambda function. I think it takes the root folder **only when deploying**.

 

### Expected Behavior

It deploys the lambdas following the right entry point specified

### Current Behavior

It deploys the lambdas using the root folder as entry point, it breaks every lambda within the nested stack

### Reproduction Steps

**api gateway stack**
```
import { App, Stack, StackProps } from 'aws-cdk-lib';
import { RestApi } from 'aws-cdk-lib/aws-apigateway';
import { PostsApiStack } from './posts';
import { DeployStack } from './deployment';

export class apiGatewayStack extends Stack {
  constructor(scope: App, props: StackProps) {
    super(scope, props);

    const api = new RestApi(this, 'RestApi', {
      deploy: true,
    });

    const postsApiStack = new PostsApiStack(
      this,
      'PostApi',
      {
        apiId: api.restApiId,
        apiRootResourceId: api.restApiRootResourceId,
      }
    );

    new DeployStack(
      this,
      'DeployRestApi',
      {
        apiId: api.restApiId,
        methods: postsApiStack.methods,
      }
    );
  };
}
```

**posts api nested stack**
```
import { NestedStack, NestedStackProps } from 'aws-cdk-lib';
import { Method, RestApi, LambdaIntegration } from 'aws-cdk-lib/aws-apigateway';
import { Runtime, Architecture } from 'aws-cdk-lib/aws-lambda';
import { NodejsFunction } from 'aws-cdk-lib/aws-lambda-nodejs';
import { Construct } from 'constructs';
import { join } from 'path';

interface PostStackProps extends NestedStackProps {
  readonly apiId: string;
  readonly apiRootResourceId: string;
}

export class PostsApiStack extends NestedStack {
  public readonly methods: Method[] = [];

  constructor(scope: Construct, props: PostStackProps) {
    super(scope, props);

    const api = RestApi.fromRestApiAttributes(this, 'RestApiPost', {
      restApiId: props.apiId,
      rootResourceId: props.apiRootResourceId,
    });

    const resourceApi = api.root.addResource('posts');

    const lambda =  new NodejsFunction(
      this,
      'lambdaTest',
      {
        architecture: Architecture.ARM_64,
        runtime: Runtime.NODEJS_18_X,
        bundling: {
          minify: false,
          target: 'node18',
          keepNames: true,
        },
        functionName: 'test',
        entry: join(__dirname, `../../../src/functions/test/index.ts`),
      }
    );

    return resourceApi.addMethod(
      'GET',
      new LambdaIntegration(lambda, { proxy: true }),
    );
  }
}
```

### CDK CLI Version

2.42.1 (build 48a95f1)

### Node.js Version

v16.17.0

### OS

Windows

### Language

Typescript

### Language Version

Typescript (4.9.3)

**Comment by peterwoodworth** [comment]
I wasn't able to reproduce this, I can deploy the exact same NodejsFunction both inside a nested stack and outside. What is the specific error message you're getting?

**Comment by Depaa** [comment]
Thank you @peterwoodworth for answering. 

I wrote the code in this repo https://github.com/Depaa/aws-sdk-nodejs-nested-function

after the deploy this is how the lambda package turn out:
![image](https://user-images.githubusercontent.com/34038747/205434269-490374a7-6172-4f7f-84f2-c04174af0be9.png)

**Comment by peterwoodworth** [comment]
Thanks for sharing you repo @Depaa,

I cloned it and am still unable to reproduce the behavior you describe. 

Just to make sure Im not missing anything, where exactly are you finding that the lambda package looks like that?

Also, is this happening in prod, non prod, or both?

**Comment by reecefenwick** [comment]
@peterwoodworth I believe that screenshot will be the function code artefact, so when you export the lambda function from the AWS console, inside the zip is what is in that screenshot, his entire project.. rather than the single js bundle from esbuild

I'm having the same issue, but worse in that I can't even get it to deploy because my project as a whole is too large. It simply fails to deploy because the ZIP file is 1GB

I use NodejsFunction heavily across other stacks, as soon as it moves into a nested stack it starts packaging the entire project and from what I can tell, it doesn't even run `esbuild` to bundle

**Comment by reecefenwick** [comment]
Just done some more digging and have identified a difference internally within CDK [here](https://github.com/aws/aws-cdk/blob/6fbcce66c50a6bea3b2f38541c54af6d5fbffaa7/packages/aws-cdk-lib/core/lib/asset-staging.ts#L304)
* When NodejsFunction is in a nested stack - `skip === true`
* When NodejsFunction is **not** in a nested stack - `skip === false`

I shall keep digging 🙃

**Comment by reecefenwick** [comment]
Looks like this issue is related (or the same) to this one https://github.com/aws/aws-cdk/issues/12898

**Comment by heikkis** [comment]
Same problem still with latest CDK version (typescript).

**Comment by pahud** [comment]
@heikkis  can you create a new issue for us if it's still relevant?
