### ISSUE TITLE
aws-autoscaling: support `defaultInstanceWarmup`

### ISSUE THREAD

**Issue by pb8o** [aws/aws-cdk#23180]
### Describe the feature

Support `defaultInstanceWarmup` in the AutoScalingGroup L2 construct.

Currently it is not supporter and the [docs](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_autoscaling.CfnAutoScalingGroup.html#defaultinstancewarmup) state:

> Not currently supported by CloudFormation.

[Which is not the case anymore](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-group.html#aws-properties-as-group-properties)

### Use Case

Right now we have to use the escape hatch.

```typescript
const cfnASG = asg.node.defaultChild as autoscaling.CfnAutoScalingGroup;
cfnASG.defaultInstanceWarmup = 60;
```

### Proposed Solution

Expose the feature through the L2 Construct.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.45.0

### Environment details (OS name and version, etc.)

Ubuntu 20.04

**Comment by pahud** [comment]
Awesome! Thanks for your PR!!

**Comment by HBobertz** [comment]
I don't see a PR for this? I'll pick this up if there isn't

**Comment by pb8o** [comment]
Yeah there isn't one. Thanks for picking it!

**Comment by HBobertz** [comment]
Unsure if there is a better way to link this pr. But here it is: https://github.com/aws/aws-cdk/pull/23285

**Comment by atchla** [comment]
Should this be closed? The linked PR has been merged but it looks like it didn't get auto-associated with this issue somehow

**Comment by pb8o** [comment]
Yep. Thanks!
