### ISSUE TITLE
(aws-lambda-python-alpha): Docker bundling does not occur as expected

### ISSUE THREAD

**Issue by hrvg** [aws/aws-cdk#23195]
### Describe the bug

Docker bundling does not occur as expected from reading the [docs](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_lambda_python_alpha/README.html):

> If requirements.txt, Pipfile or poetry.lock exists at the entry path, the construct will handle installing all required modules in a [Lambda compatible Docker container](https://gallery.ecr.aws/sam/build-python3.7) according to the runtime and with the Docker platform based on the target architecture of the Lambda function.

However, I cannot reproduce this behavior with `CDK Version: 2.53.0 (build 7690f43)`.

I have been looking into this issue for quite some time, but cannot figure what is going on from the limited information I could find. It might be a bug or simple error from my end.

### Expected Behavior

During `cdk synth`, the Lambda function is bundled as a `DockerImage`, and entry is created at `{stack-name}.assets.json.dockerImages`. During `cdk deploy`, the image is deployed to ECR and the Lambda function is created from the image.

### Current Behavior

During `cdk synth`, the Lambda function is bundled as a `.zip`, and an entry is created at `{stack-name}.assets.json.files`. During `cdk deploy`, the `.zip` is deployed to S3 and the Lambda function is created from the `.zip`.

### Reproduction Steps

1. Create a new cdk project
```
mkdir lambda-alpha
cd lambda-alpha
cdk init -l python
```

2. Add `src` directory and required files:

```
mkdir src
touch src/index.py
touch src/requirements.txt
```

```
├── src
│   ├── index.py
│   └── requirements.txt
```

3. Add Lambda function code at `./src/index.py`

```python
import json


def handler(event: dict, context: dict) -> dict:
    return {
        "statusCode": 200,
        "body": json.dumps({
            "message": "hello world"
        }),
    }

```

4. Add arbitrary dependencies in `./src/requirements.txt`, for example:

```
pandas

```

5. Add a `PythonFunction` to the default stack in `lambda_alpha/lambda_alpha_stack.py`:
```python
from aws_cdk import (
    # Duration,
    Stack,
    # aws_sqs as sqs,
)
from constructs import Construct
from aws_cdk.aws_lambda_python_alpha import PythonFunction
from aws_cdk.aws_lambda import Runtime

class LambdaAlphaStack(Stack):

    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        PythonFunction(self, "HelloWorld", entry='./src/', runtime=Runtime.PYTHON_3_9, index='index.py', handler='handler')
```

6. `cdk synth`

### Additional Information/Context

- Testing with a `Pipfile` instead of `requirements.txt` leads to the same behavior
- Replacing `aws_cdk.lambda_python_alpha.PythonFunction` with `aws_cdk.lambda.DockerImageFunction` (and adding a `Dockerfile` in `src` leads to the expected behavior: creation of a `DockerAsset` , entry in `{stack-name}.assets.json.dockerImages`, and deployment to ECR.
- Deploying directly with `cdk deploy` or through `aws_cdk.pipelines` leads to the same issue.

### CDK CLI Version

2.53.0 (build 7690f43)

### Node.js Version

v18.12.1

### OS

Tested on PopOS and Ubuntu

### Language

Python

### Language Version

3.9.9

### Other information

Not directly related, but the code used here is really similar to the code from https://github.com/aws/aws-cdk/issues/18696 which seems to be working (albeit with `ARM` and not `x86_64`, and deploying with `aws_cdk.pipelines`).

**Comment by peterwoodworth** [comment]
The image `PythonFunction` uses is used for _bundling_ your lambda function into a usable asset; it's not intended to be an image that's uploaded as a handler. When you `cdk deploy` the docker image is ran and bundles your handler + dependencies together into a functional asset, right?

If you want to use an image as the handler, it's correct to use `DockerImageFunction` 🙂

**Comment by hrvg** [comment]
> The image `PythonFunction` uses is used for _bundling_ your lambda function into a usable asset; it's not intended to be an image that's uploaded as a handler. When you `cdk deploy` the docker image is ran and bundles your handler + dependencies together into a functional asset, right?
> 

Thank you for this answer. It seems I misunderstood the docs and everything is working as intended. I would suggest adding the first sentence of your response to the docs for added disambiguation.
