### ISSUE TITLE
aws_iam: Role without Assumed by

### ISSUE THREAD

**Issue by aradyaron** [aws/aws-cdk#23190]
### Describe the feature

Allow to crate a role without an assumed_by, and grant assume by later on.

Currently When creation a role, the assumed_by is a required field.
However, I will know who should be able to assume the role only after the creation of it, due to how I manage my code:
1. I create a resource
2. I create a role to access that resource
3. I later grant who needs to access the resource the assume role to the mediating role.

### Use Case

I cannot work i the way I want to:
I want to work in the following way:
1. I create a resource
2. I create a role to access that resource
3. I later grant who needs to access the resource the assume ole to the mediating role.

However I am forced to work in the following
1. I create a resource
2. I create a role to access that resource - with a never used principal to assume role
3. I later grant who needs to access the resource the assume role to the mediating role.

### Proposed Solution

Allow to have a role without any assumed_by, and verify it only when creating synth the stack

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.50.0 (build 4c11af6)

### Environment details (OS name and version, etc.)

General

**Comment by peterwoodworth** [comment]
We want to have this property required to make it clear what information is required for a successful CloudFormation deployment. However, you can work around this by supplying an arbitrary principal to assume, then removing the created statement with an [escape hatch](https://docs.aws.amazon.com/cdk/v2/guide/cfn_layer.html) immediately after the role is created. You could create your own Role construct which does this automatically if you need to repeat this process anywhere

The escape hatch would look something like this

```ts
const role = Role(...);
(role.node.defaultChild as CfnRole).addPropertyDeletionOverride('AssumeRolePolicyDocument.Statements.0');
```

**Comment by aradyaron** [comment]
> We want to have this property required to make it clear what information is required for a successful CloudFormation deployment. However, you can work around this by supplying an arbitrary principal to assume, then removing the created statement with an [escape hatch](https://docs.aws.amazon.com/cdk/v2/guide/cfn_layer.html) immediately after the role is created. You could create your own Role construct which does this automatically if you need to repeat this process anywhere
> 
> The escape hatch would look something like this
> 
> ```ts
> const role = Role(...);
> (role.node.defaultChild as CfnRole).addPropertyDeletionOverride('AssumeRolePolicyDocument.Statements.0');
> ```

Thanks a lot for this information, and more than helpful example! What about having a boolean as a toggle to explicitly disable it? I think this can be helpful to other people as well.

**Comment by peterwoodworth** [comment]
We won't be considering implementing this feature request as it will likely lead to more confusion than anything. If people still want this, please create a new feature request with a clear use case of why this would be useful and is otherwise a blocker if not implemented.
