### ISSUE TITLE
(custom-resources): AwsCustomResource - export provider lambda uuid

### ISSUE THREAD

**Issue by cogwirrel** [aws/aws-cdk#23204]
### Describe the feature

Please could we export the uuid for the singleton lambda as a constant I can consume from `aws-cdk-lib/custom-resources`?

See here: https://github.com/aws/aws-cdk/blob/v2.53.0/packages/@aws-cdk/custom-resources/lib/aws-custom-resource/aws-custom-resource.ts#L399-L400

### Use Case

I'll often use [cdk-nag](https://github.com/cdklabs/cdk-nag/) with my CDK projects, and get an error that this singleton lambda is not using the latest lambda runtime. This is fine, and I'm happy to suppress the error, but it's difficult to suppress for that specific resource since the singleton lambda is attached to the stack - so I can't just add a suppression to the `AwsCustomResource` itself.

For example I can't do this, because the lambda isn't a child of the custom resource:

```ts
const customResource = new AwsCustomResource(...);

NagSuppressions.addResourceSuppressions(customResource, [
  {
    id: 'AwsSolutions-L1',
    reason: 'AwsCustomResource is controlled internally by CDK',
  },
], true);
```

But I can do this:

```ts
NagSuppressions.addResourceSuppressionsByPath(stack, `${PDKNag.getStackPrefix(stack)}AWS679f53fac002430cb0da5b7982bd2287`, [
  {
    id: 'AwsSolutions-L1',
    reason: 'AwsCustomResource is controlled internally by CDK',
  },
], true);
```

But I have to hardcode the uuid to reference it which is a bit of a shame!

### Proposed Solution

Export the uuid as a constant I can consume :). An alternative is to upgrade the lambda to use Node 18, so it doesn't trigger the error, but that's likely more work and less future proof to new lambda runtime versions.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.53.0

### Environment details (OS name and version, etc.)

macOS Monterey 12.6.1

**Comment by cogwirrel** [comment]
Thanks! Totally agree with the priority :) I'll see if I can squeeze in a PR sometime soon :)

**Comment by rix0rrr** [comment]
The UUID is guaranteed not to change. You can copy/paste it.
