### ISSUE TITLE
aws-lambda: Support DOTNET_7 for Function resources

### ISSUE THREAD

**Issue by petro2050** [aws/aws-cdk#23203]
### Describe the feature

I'm trying to create a Lambda with `Runtime` set to .NET 7. Is this supported? There doesn't seem to be an enum for `DOTNET_7`. https://github.com/aws/aws-cdk/blob/738922bac279aaafeca26f8aa401cff9a6a86629/packages/%40aws-cdk/aws-apprunner/lib/service.ts#L109

Also, I'm trying to deploy an ASP.NET WebAPI project. I've got some Lambda logs:

> It was not possible to find any compatible framework version
> The framework 'Microsoft.NETCore.App', version '7.0.0' (x64) was not found.
> - The following frameworks were found:
> - 6.0.4 at [/var/lang/bin/shared/Microsoft.NETCore.App]
> - You can resolve the problem by installing the specified framework and/or SDK.
> - The specified framework can be found at:
> - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=7.0.0&arch=x64&rid=amzn.2-x64

I found [this article](https://aws.amazon.com/blogs/compute/building-serverless-net-applications-on-aws-lambda-using-net-7/) that shows support for .NET 7, but it's only for native AOT. There is no native AOT support for ASP.NET yet. Can you tell me how I can go about deploying my app?

### Use Case

I've upgraded everything to .NET 7 locally. Got stuck with deployment.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.53.0

### Environment details (OS name and version, etc.)

AL2

**Comment by pahud** [comment]
According to https://docs.aws.amazon.com/lambda/latest/dg/lambda-csharp.html .NET 7 is not supported yet. Did you see any Lambda announcement for .NET 7 support?

**Comment by gscpw** [comment]
@pahud .NET 7 is supported now in lambda. It is still missing in AWS CDK though:

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda.Runtime.html
