### ISSUE TITLE
cdk-kms: facing issue when trying to attach policyDocument to KMS key.

### ISSUE THREAD

**Issue by siddheshpdy** [aws/aws-cdk#23207]
### Describe the bug

Hello,

I am facing follwing issue when I try to attach PolicyDocument to KMS Key policy.
```
**Type 'import("cloudformation/cdk-infra/node_modules/@aws-cdk/aws-iam/lib/policy-document").PolicyDocument' is not assignable to type 'import("cloudformation/cdk-infra/node_modules/@aws-cdk/aws-kms/node_modules/@aws-cdk/aws-iam/lib/policy-document").PolicyDocument'.
  Types have separate declarations of a private property 'statements'.**
```
I am using following link for reference:
https://docs.aws.amazon.com/cdk/api/v1/docs/aws-kms-readme.html#appending-to-or-replacing-the-default-key-policy

I have also tried This example to create role and using kms to grant access to IT:
```
const myKeyLookup = kms.Key.fromLookup(this, 'MyKeyLookup', {
  aliasName: 'alias/KeyAlias',
});

const role = new iam.Role(this, 'MyRole', {
  assumedBy: new iam.ServicePrincipal('lambda.amazonaws.com'),
});
myKeyLookup.grantEncryptDecrypt(role);
```
```
Argument of type 'Role' is not assignable to parameter of type 'IGrantable'.
  The types of 'grantPrincipal.addToPolicy' are incompatible between these types.
    Type '(statement: import("cloudformation/cdk-infra/node_modules/@aws-cdk/aws-iam/lib/policy-statement").PolicyStatement) => boolean' is not assignable to type '(statement: import("cloudformation/cdk-infra/node_modules/@aws-cdk/aws-kms/node_modules/@aws-cdk/aws-iam/lib/policy-statement").PolicyStatement) => boolean'.
      Types of parameters 'statement' and 'statement' are incompatible.
        Type 'import("cloudformation/cdk-infra/node_modules/@aws-cdk/aws-kms/node_modules/@aws-cdk/aws-iam/lib/policy-statement").PolicyStatement' is not assignable to type 'import("cloudformation/cdk-infra/node_modules/@aws-cdk/aws-iam/lib/policy-statement").PolicyStatement'.
          Types have separate declarations of a private property '_action'.
```
### Expected Behavior

CDK should have accepted policy as object is of type policyDocument.

### Current Behavior

while assigning policy its giving following error. and it seems like aws cdk for kms is expecting Iam from path of s3 modules dependancy.

Type 'import("cloudformation/cdk-infra/node_modules/@aws-cdk/aws-iam/lib/policy-document").PolicyDocument' is not assignable to type 'import("cloudformation/cdk-infra/node_modules/@aws-cdk/aws-kms/node_modules/@aws-cdk/aws-iam/lib/policy-document").PolicyDocument'.
  Types have separate declarations of a private property 'statements'.

### Reproduction Steps

NA

### CDK CLI Version

1.181.0

### Node.js Version

16

### OS

Windows

### Language

Typescript

### Language Version

ts: 3.9.7

**Comment by peterwoodworth** [comment]
This looks like a common error that occurred for v1 users where the installed packages are mismatched. I can run this code successfully in v2, and it should work in v1 if everything is installed correctly.

Try removing `node_modules` and `package-lock.json` and then reinstalling your packages after checking `package.json` to ensure all CDK packages are the same version. Thanks! 

If you need more assistance, you can search through existing CDK issues for [similar errors](https://github.com/aws/aws-cdk/issues/17930), or feel free to open up a discussion.

**Comment by siddheshpdy** [comment]
@peterwoodworth Thanks for reply, 

I upgraded CDK version to v2 and it solved that issue, I took decision to update as there were very few resources already present in project so It was like hitting 2 birds in one stone as I already wanted to update aws-cdk version in project.

**Comment by peterwoodworth** [comment]
Great to hear @siddheshpdy! Glad this got resolved for you
