### ISSUE TITLE
pipelines: minor readme update

### ISSUE THREAD

**Issue by ryanwilliams83** [aws/aws-cdk#23202]
### Describe the issue

Consider replacing
"and very specifically it is not built to use CodeDeploy to applications to instances"
with
"and very specifically it is not built to use CodeDeploy to **deploy** applications to instances"

### Links

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.pipelines-readme.html

**Comment by pahud** [comment]
Would you like to submit this PR? I think we just need update the README here
https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/pipelines/README.md
