### ISSUE TITLE
(aws-lambda-nodejs): esbuild `mainFields` option is not set by default

### ISSUE THREAD

**Issue by moltar** [aws/aws-cdk#23211]
### Describe the bug

The `mainFields` is not set by default.

But it is documented as such.

https://github.com/aws/aws-cdk/blob/main/packages/@aws-cdk/aws-lambda-nodejs/lib/types.ts#L295-L301

https://github.com/aws/aws-cdk/blob/b1d8d08ae4a8408cb9113d04b7ff644fcbc543ac/packages/@aws-cdk/aws-lambda-nodejs/README.md?plain=1#L200

https://github.com/aws/aws-cdk/blob/b1d8d08ae4a8408cb9113d04b7ff644fcbc543ac/packages/@aws-cdk/aws-lambda-nodejs/lib/bundling.ts#L200

### Expected Behavior

The default either to be set or documented as not set.

### Current Behavior

No default.

### Reproduction Steps

N/A

### Possible Solution

N/A

### Additional Information/Context

N/A

### CDK CLI Version

2.53.0

### Framework Version

2.53.0

### Node.js Version

v14.20.1

### OS

macOS

### Language

Typescript

### Language Version

4

**Comment by moltar** [comment]
It's a good option to have for SDK v3.

https://github.com/aws/aws-sdk-js-v3/issues/3023#issuecomment-1119756337

**Comment by peterwoodworth** [comment]
Thanks for reporting this @moltar, and linking to the code as well. 

We should adjust the documentation on this, it can be edited here https://github.com/aws/aws-cdk/blob/482dcca501b42d4a1f537274e47193f4db6768ef/packages/%40aws-cdk/aws-lambda-nodejs/lib/types.ts#L299

**Comment by badmintoncryer** [comment]
@peterwoodworth Can I take this up?

**Comment by peterwoodworth** [comment]
Yes, feel free @badmintoncryer! Thanks for the offer
