### ISSUE TITLE
aws_iam: AttributeError: 'tuple' object has no attribute 'IConstruct' when using Grant.apply_before()

### ISSUE THREAD

**Issue by michaela-vid** [aws/aws-cdk#23247]
### Describe the bug

From version 2.51.0 and later, when running a `cdk synth` or `cdk deploy` command on code that uses aws_cdk.aws_iam.Grant.apply_before(*constructs) the command fails with the following output:

```
Traceback (most recent call last):
  File "<file-path>/app.py", line 106, in <module>
    api = ApiStack(app,
  File "<file-path>/.venv/lib/python3.10/site-packages/jsii/_runtime.py", line 111, in __call__
    inst = super().__call__(*args, **kwargs)
  File "<file-path>/cdk/api.py", line 445, in __init__
    grant.apply_before(rotation_schedule)
  File "<file-path>/.venv/lib/python3.10/site-packages/aws_cdk/aws_iam/__init__.py", line 6916, in apply_before
    def stub(*constructs: constructs.IConstruct) -> None:
AttributeError: 'tuple' object has no attribute 'IConstruct'
```

rotation_schedule is a aws_cdk.aws_secretsmanager.RotationSchedule

### Expected Behavior

The command should successfully synthesize.

### Current Behavior

The command fails to synthesize.

### Reproduction Steps

1) Upgrade to version 2.51.0 or later
2) Use apply_grant somewhere in your CDK code
3) Try to synthesize by running `cdk synth`

### CDK CLI Version

2.51.0

### Node.js Version

16.14.2

### OS

Ubuntu 22.04.1 LTS

### Language

Python

### Language Version

Python (3.10.6)

**Comment by peterwoodworth** [comment]
I can only reproduce this in versions `2.49.1` and `2.50.0`. All other versions seem to fail with this code. Additionally, I've confirmed this same code works in TypeScript.

What this makes me think is that this is a bug with JSII that was fixed - But, then we had to revert the version of JSII the CDK uses because the new JSII released a breaking change. I suspect once we upgrade JSII version again that this will be fixed. 

CC @RomainMuller @MrArnoldPalmer

**Comment by michaela-vid** [comment]
Tagging two issues that are likely caused by the same issue seen here. This leads to the same conclusion that Peter commented, once JSII upgrades, it should be resolved, since that is what fixed this other issue the first time.
https://github.com/aws/aws-cdk/issues/22711
https://github.com/aws/aws-cdk/issues/23281

**Comment by michaela-vid** [comment]
I upgrade to version 2.55.0 and am now experiencing a different error. But, if I comment out the stack with the new error, this stack does synthesize. I believe this issued is fixed and can be closed.

I will open a new issue for the new error, as it's completely different.
