### ISSUE TITLE
RDS: Allow enabling Performance Insights on RDS Serverless v2

### ISSUE THREAD

**Issue by caevv** [aws/aws-cdk#23242]
### Describe the feature

Allow to enable Monitoring Aurora Serverless v2 performance with Performance Insights.

### Use Case

See performance issues.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.53.0

### Environment details (OS name and version, etc.)

Linux

**Comment by peterwoodworth** [comment]
Thanks for the request @caevv, this will definitely be a feature of our [L2 Aurora Serverless v2 support](https://github.com/aws/aws-cdk/issues/20197), since this is already a feature for other RDS instances/clusters we will build on top of that.
