### ISSUE TITLE
(aws_stepfunctions): Depreciated Parameters field in Map

### ISSUE THREAD

**Issue by grzegorzewald** [aws/aws-cdk#23265]
### Describe the feature

As per https://docs.aws.amazon.com/step-functions/latest/dg/concepts-asl-use-map-state-inline.html#map-state-inline-deprecated-fields, `Parameters` filed is now depreciated. `ItemSelector` field should be used instead (https://docs.aws.amazon.com/step-functions/latest/dg/concepts-asl-use-map-state-inline.html#itemselector)

### Use Case

Depreciated fields may break compatibility

### Proposed Solution

As new `ItemSelector`  filed takes input in exactly the same form as depreciated 'Parameters', the easiest solution would be to rename field and create "alias" with depreciation warning durning synth.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.53.0

### Environment details (OS name and version, etc.)

MacOS 13.0.1

**Comment by grzegorzewald** [comment]
Hi @peterwoodworth,
Yes, exactly this one.

**Comment by shantgup** [comment]
My customer is trying to use `ItemSelector` with CDK, only to find the `[Map](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_stepfunctions.Map.html)` does not support `ItemSelector`.

I have suggested them to use the deprecated Parameters field for now.

**Comment by Vluf** [comment]
Been a bit disappointed with the supported of `Map` in the CDK in general. First tried to find a way to use distributed mode: node supported, using `ItemSelector` as the alternative -> also not supported :/

**Comment by 7jpsan** [comment]
Hi, @grzegorzewald probably no canonical but I had a similar issue and while we wait the native cdk class Map support for it, we can use a CustomState based off the MapState and tweak a couple props: 

```typescript
const mapState = new sfn.CustomState(this, 'MapWithSelector', {
            stateJson: {
                ...new sfn.Map(this, 'Irrelevant', {
                    itemsPath: sfn.JsonPath.stringAt('$.parallelInputData'),
                })
                    .iterator(yourIteratorGoesHere)
                    .toStateJson(),
                End: undefined,
                ItemSelector: {
                    'ContextIndex.$': '$$.Map.Item.Index',
                    'ContextValue.$': '$$.Map.Item.Value',
                },
            },
        });
```

This will create the Map state with the ItemSelector on it.

**Comment by T-Guerrero** [comment]
IMO, this request shouldn't be labeled as "feature request". It's actually an inconsistency with the official doc, thus "bug" looks a better classification for me (even for prioritization purposes)

**Comment by joa44741** [comment]
would also love to use the ItemSelector instead of Parameters :)

**Comment by guyernest** [comment]
From the Step Functions Documentation for Map (https://docs.aws.amazon.com/step-functions/latest/dg/concepts-asl-use-map-state-inline.html) under the `Deprecated fields`:
>Note
Although you can continue to include Map states that use the following fields, we highly recommend that you replace Iterator with [ItemProcessor](https://docs.aws.amazon.com/step-functions/latest/dg/concepts-asl-use-map-state-inline.html#itemprocessor) and Parameters with [ItemSelector](https://docs.aws.amazon.com/step-functions/latest/dg/concepts-asl-use-map-state-inline.html#itemselector).

The current `map.iterator` implementation ignores this note, and there is no support for the recommended definition.

The only way around it is to use the `custom tast` option.
