### ISSUE TITLE
(aws_lambda): File permissions not respected in zip deployment

### ISSUE THREAD

**Issue by gsoyka** [aws/aws-cdk#23284]
### Describe the bug

When deploying a Lambda function using `aws_lambda.Code.from_asset`, the created ZIP file has files with modified permissions, which causes a permissions error when executing the Lambda.

### Expected Behavior

For files on the local filesystem that have 644 set, the files in the created ZIP file should also be 644.

Local files:
```
-rw-r--r--   1 gsoyka  staff   1188 Jun 29 10:45 README.md
-rw-r--r--   1 gsoyka  staff   6161 Nov 18 08:37 app.py
```

### Current Behavior

Files are modified to 640.  
```
-rw-r-----@   1 gsoyka  staff   1188 Jan  1  1980 README.md
-rw-r-----@   1 gsoyka  staff   6161 Jan  1  1980 app.py
```

### Reproduction Steps

When deploying a lambda function from source:
```
aws_lambda.Function(
            self, "function",
            runtime=aws_lambda.Runtime.PYTHON_3_7,
            code=aws_lambda.Code.from_asset("function_code"),
            handler="app.lambda_handler"
)
```
The resulting ZIP uploaded to S3 will have 640 file permissions.

### CDK CLI Version

2.22.0

### Node.js Version

16.15.1

### OS

Mac OS

### Language

Python

### Language Version

Python 3.7

**Comment by peterwoodworth** [comment]
@gsoyka can you provide a repo which I can clone and reproduce this issue with? I don't think we are modifying permissions anywhere and I've never seen this kind of issue be reported so I'm a little stumped 😅
