### ISSUE TITLE
aws-cdk-lib.pipelines: Adding referencing construct  causes "Error: Pipeline not created yet"

### ISSUE THREAD

**Issue by shawnwang-avl** [aws/aws-cdk#23292]
### Describe the bug

We've wrapped `pipelines.CodePipeline` in our own construct, instantiate it in a stack, and then attempted to reference it by another construct.

```
export class PipelineStack extends Stack {

	constructor(scope: Construct, id: string, props?: StackProps) {
		super(scope, id, props);

		const ahaPipeline = this.createPipeline();

		this.addGithubDeploymentStatusTracking(ahaPipeline.pipeline.pipeline)
	}

	private createPipeline(): AhaPipeline {
		const pipeline = new AhaPipeline(  // construct that calls pipelines.CodePipeline
			this,
			`${ SERVICE_NAME }-Pipeline`,
			pipelineProps,
		);
		
		...... add deployment stages ....

		return pipeline;
	}

	private addGithubDeploymentStatusTracking(pipeline: Pipeline){
		// Tracking pipeline status on github
		new CodePipelinePostToGitHub(this, 'CodePipelinePostToGitHub', {
			pipeline: pipeline,
			githubToken: GITHUB_STATUS_TRACKING_TOKEN_SECRET_ARN,
		});
	}
}


```

### Expected Behavior

Successfully compile and generate pipeline stack

### Current Behavior

Received error

```
Error: Pipeline not created yet
    at CodePipeline.get pipeline [as pipeline] (C:\Users\timmy\OneDrive\Documents\work_project\aha-nft-mgmt-service\cdk\node_modules\aws-cdk-lib\pipelines\lib\codepipeline\codepipeline.js:1:2140)
    at createPipeline (C:\Users\timmy\OneDrive\Documents\work_project\aha-nft-mgmt-service\cdk\src\envs\pipeline.ts:81:50)
```

### Reproduction Steps

1. create pipeline construct
3. create dependency construct that consumes cdk pipeline
3. create pipeline stack with the two 

will attach code example that accurately reflect our pipeline and dependency construct upon request, as it involves removing significant business logic.

### Additional Information/Context

CodePipelinePostToGitHub is a CDKv2 port of [this project](https://github.com/dance-electric/cdk-report-codepipeline-status-to-github/tree/cdk-v2/packages/github-notifier-construct/lib), which includes an Eventbridge with lambda listener, listening on pipeline events. Lambda handler invokes Github API.

Our pipeline construct defines a multi-stage, cross account CDK pipeline.

### CDK CLI Version

5.45.0 (build af1fb7c)

### Node.js Version

v16.17.0

### OS

MacOS Monterey 12.5.1

### Language

Typescript

### Language Version

TypeScript (4.9.3)

**Comment by peterwoodworth** [comment]
The error is occurring because another construct is trying to access `CodePipeline.pipeline` before the pipeline has been constructed

The pipeline isn't actually created until later in the synth stage. You can call [`buildPipeline()`](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.pipelines.CodePipeline.html#buildwbrpipeline) if you need the pipeline to have been internally built and constructed earlier in the app lifecycle. Does this work for you?

**Comment by shawnwang-avl** [comment]
Thank you Peter, that worked!

**Comment by pitayapj** [comment]
Hi @peterwoodworth

Asking in closed thread but,
With [buildPipeline()](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.pipelines.CodePipeline.html#buildwbrpipeline) document stated that `It is not possible to modify the pipeline after calling this method.`

Can you help me understand correctly but does it mean any pipeline modify after calling `buildPipeline()` will be ignore ?
As long as we keep changes before calling the function we are good ?

Or does it mean we can not modify the pipeline for good if we included said function into our code ? (I don't want this to happen 🦀 )

Thanks!
