### ISSUE TITLE
(ec2): missing SSM parameter for MachineImage throws ValidationError AccessDenied

### ISSUE THREAD

**Issue by rrhodes** [aws/aws-cdk#23297]
### Describe the bug

When I try to fetch a missing SSM parameter using `MachineImage.fromSsmParameter`, I receive an error message suggesting I do not have permission to call SSM Get Parameters, when in fact I did have these permissions but the parameter was not found.

### Expected Behavior

An error message indicating the parameter was not found.

### Current Behavior

The below error is thrown:

```txt
[ValidationError]: AccessDenied. User doesn't have permission to call ssm:GetParameters
```

### Reproduction Steps

Example CDK for TypeScript which raised this error, assuming SSM parameter `/missing/parameter` does not exist:

```ts
const instanceConfig = {
  instanceType: InstanceType.of(InstanceClass.T2, InstanceSize.NANO),
  machineImage: MachineImage.fromSsmParameter(
    "/missing/parameter",
    {
      userData: UserData.forLinux(),
    },
  ),
  vpc,
};

new Instance(this, "Instance", {
  ...instanceConfig,
  role: instanceRole,
});
```

### Possible Solution

Whether this may be solved within CDK, or requires changes to the AWS SDK for SSM, I'm not sure. If it is possible to capture parameter not found cases and produce a clearer error message, that would be great.

### CDK CLI Version

2.53.0 (build 7690f43)

### Node.js Version

v18.12.0

### OS

Mac OS Monterey

### Language

Typescript

**Comment by peterwoodworth** [comment]
You might actually be lacking permissions for some reason. I'm getting this error thrown after copying your code:


> ❌ Deployment failed: Error: Stack Deployments Failed: ValidationError: Unable to fetch parameters [/missing/parameter] from parameter store for this account.

Can you check CloudTrail to see which role attempted to make this call? And then can you check that role's perms? Thanks 🙂

**Comment by rrhodes** [comment]
Hey @peterwoodworth, thanks for looking into this. My user in this instance was running Administrator permissions and I couldn't identify anything explicitly denying that action for me. I'm able to retrieve parameters that exist without issue under the same setup.
