### ISSUE TITLE
cdk ini python issue

### ISSUE THREAD

**Issue by angusfz** [aws/aws-cdk#2330]
**Describe the bug**
Python virtual env should include pip to prevent use system pip

**To Reproduce**

```bash
$ cdk init app --language=python
$ source .env/bin/activate
$ pip install -r requirements.txt
Obtaining file:///Users/angus.lee/Project/github/cdk-test (from -r requirements.txt (line 1))
cdk-test requires Python '>=3.6' but the running Python is 2.7.15
```

**Expected behavior**
Just like `virtualenv .env ` 

**Version:**
 - OS: mac
 - Programming Language: python
 - CDK Version: 0.28

**Comment by garnaat** [comment]
Could you provide the complete output from the `cdk init` command you ran?  Were there errors?

**Comment by SomayaB** [comment]
Closing this issue since there hasn't been activity on it in a while. Feel free to reopen.
