### ISSUE TITLE
(documentation): Change format of documentation pages

### ISSUE THREAD

**Issue by biffgaut** [aws/aws-cdk#23302]
### Describe the feature

This may be an odd/trivial issue to suggest, but the formatting of the documentation wastes significant space while hiding the information we want to see. The content width is fixed, and with the width of the left and right columns there is not enough room in the middle column for the actual content. I realize that I can reduce the browser width to the point where the left and right columns disappear, but it is handy to have those. I'd rather the docs take advantage of the entire screen width so I can see the info I need and the left and right columns. 

I've attached a screen snip that demonstrates what I mean. Note that only about half the table describing the Props values is visible while about half of the entire browser is blank.

![image](https://user-images.githubusercontent.com/78155736/206748357-df32a8c4-b9d7-4505-a3ab-3ccbfde81ac2.png)

### Use Case

I'm always frustrated when...I spend more time scrolling left and right to see the content than I spend understanding the content.

### Other Information

The example is the aws-kinesisfirehose documentation for [CfnDeliveryStreamProps](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_kinesisfirehose.CfnDeliveryStreamProps.html). The extent of the issue varies on different pages.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.54.0

### Environment details (OS name and version, etc.)

Chrome browser, Safari browser

**Comment by ryparker** [comment]
Horizontal overscroll is definitely annoying. I'll see what we can do about this.

**Comment by ryparker** [comment]
We're still tweaking a few things on the doc site but you should notice an improvement now.

![CleanShot 2022-12-20 at 20 24 08@2x](https://user-images.githubusercontent.com/17558268/208820940-d66456ae-10a7-4473-86fd-a25df4249598.png)
