### ISSUE TITLE
Add possibility to call asAliasRecordTarget from an imported ApplicationLoadBalancer

### ISSUE THREAD

**Issue by stefanorg** [aws/aws-cdk#2331]
Version 0.28

It would be usefull to add the possibility to call asAliasRecordTarget (implemented in BaseLoadBalancer) to the interface IApplicationLoadBalancer.

In my use case i work mostly with the same load balancer and i need to add the alias to the ecs service i create.

Thanks

**Comment by rix0rrr** [comment]
Don't think this is relevant anymore. We use integration classes now.
