### ISSUE TITLE
Codebuild not able to find buildspec.yml file using fromSourceFilename method

### ISSUE THREAD

**Issue by jatinmehrotra** [aws/aws-cdk#23324]
### Describe the bug

I am trying to use YAML commands from buildspec.yml file using `codebuild.BuildSpec.fromSourceFilename` but codebuild is unable to find this file,, when I trying to run build job.

### Expected Behavior

It should run my commands present in the yml file.

### Current Behavior

It shows error In the build logs Phase context status code: `YAML_FILE_ERROR Message: stat /codebuild/output/srcxxxxxxx3/src/buildspec/plan-buildspec.yml: no such file or directory`

### Reproduction Steps

here is my cdk code 

```
const TFplan = new codebuild.PipelineProject(this, 'tf-plan', {
      projectName: 'tf-cicd-plan',
      description: 'Plan stage for terraform',
      environment: {
        computeType: ComputeType.SMALL,
        buildImage: LinuxBuildImage.AMAZON_LINUX_2_4
      },
      buildSpec: codebuild.BuildSpec.fromSourceFilename('buildspec/plan-buildspec.yml')
    })

    const TFplanbBuildAction = new codepipeline_actions.CodeBuildAction({
      actionName: 'Build',
      project: TFplan,
      input: sourceOutput,
    });
```

pipeline code 

```
const pipeline = new codepipeline.Pipeline(this, 'CodePipeline', {
      pipelineName: 'jatin-ci-cd',
      crossAccountKeys: false, // not required as it wont be cross account deployment
      stages: [

        {
          stageName: 'Source',
          actions: [sourceAction]
        },

        {
          stageName: 'Plan',
          actions: [TFplanbBuildAction]
        },
        // code
```

My directory structure 

```
./lib
├── pipeline-source-bucket.ts
└── pipeline-stack.ts
./buildspec
├── apply-buildspec.yml
└── plan-buildspec.yml

```

        
        

### CDK CLI Version

2.44.0 (build bf32cb1)

### Node.js Version

16.17.0

### OS

macOS

### Language

Typescript

### Language Version

 4.6.2

**Comment by jatinmehrotra** [comment]
@peterwoodworth any update on this?

**Comment by peterwoodworth** [comment]
From the [CloudFormation docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-source.html#cfn-codebuild-project-source-buildspec):

> If this value is provided, it can be either a single string containing the entire build specification, or the path to an alternate buildspec file relative to the value of the built-in environment variable CODEBUILD_SRC_DIR.

Are you sure that your codebuild project has this file defined where you're expecting it to be?

**Comment by jatinmehrotra** [comment]
Iy you check my directory structure mentioned in issue, looking by that I think so its is there where it should be.

After reading you comment and the link to docs I have few questions ?

- How to find the location of `CODEBUILD_SRC_DIR`. I think this is something determined by CDK at runtime, so I dont think so I have control over the location of this variable?
- After reading this issue https://github.com/aws/aws-cdk/issues/1138, Is it right to presume CDK does not have support for inline YAML file anymore?
- From the docs you mentioned, under the heading `Project without a source sample`, it says something like this `You can configure a CodeBuild project by choosing the NO_SOURCE source type when you configure your source. When your source type is NO_SOURCE, you cannot specify a buildspec file because your project does not have a source. Instead, you must specify a YAML-formatted buildspec string in the buildspec attribute of the JSON-formatted input to the create-project CLI command. It might look like this:`. CDK's codebuild.PipelineProject does not expose a way to use source. In the past I have use [terraform it was fine in that ](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/codebuild_project#type)

**Comment by peterwoodworth** [comment]
> How to find the location of CODEBUILD_SRC_DIR

This is the directory of whatever your source is. 

> You can check my directory structure mentioned in issue, looking by that I think so its is there where it should be.

I was asking you to make sure that this is the case in your codebuild source directory, not your local directory. It sounds like this was the case since you got the workaround to work using your local file

**Comment by jakegrabowski** [comment]
seem this is still an issue as I am facing similar problem
