### ISSUE TITLE
(aws-amplify-alpha): (Missing cloudformation property framework for Branch)

### ISSUE THREAD

**Issue by philschmid** [aws/aws-cdk#23325]
### Describe the bug

The [Branch](https://docs.aws.amazon.com/cdk/api/v2/docs/@aws-cdk_aws-amplify-alpha.Branch.html) construct is missing the important [Framework](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-amplify-branch.html#cfn-amplify-branch-framework) property from cloudformation, which is needed to run NextJs successfully. Since it is not automatically detected

### Expected Behavior

Allowing to add `framework` property

### Current Behavior

Not possible

### Reproduction Steps

Create Branch try to add `framework` property to BranchOptions

### CDK CLI Version

2.51.1 (build 3d30cdb)

### Framework Version

^2.51.1-alpha.0

### Node.js Version

v16.13.0

### OS

macos

### Language

Typescript

### Language Version

3.9.7

**Comment by peterwoodworth** [comment]
We offer this on our [L1 CfnBranch](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_amplify.CfnBranch.html), just not the L2 which is still considered in development

I'm going to remark this as a feature request for the L2 to support the `framework` property.

In the meantime you can still use the L2 and set the L1 property with an escape hatch

```
const branch = new Branch(...);
(branch.node.defaultChild as CfnBranch).addPropertyOverride('Framework', ...);
```

**Comment by philschmid** [comment]
Thank you for the response @peterwoodworth. I am using the suggested workaround already.

**Comment by kaizencc** [comment]
We'll pick this up. @sumupitchayan will take a stab at this one.

**Comment by sumupitchayan** [comment]
> You'll also need the `platform` property in the `amplify.App` construct to accomplish what this issue describes:
> 
> https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-amplify-app.html#:~:text=%3A%20No%20interruption-,Platform,-The%20platform%20for
> 
> This would be a quick example of configuring an Amplify app to support Next.js 12 and above:
> 
> ```js
> const app = new amplify.App(scope, 'App', { platform: 'WEB_COMPUTE' });
> const branch = app.addBranch('main', { framework: 'Next.js' }); 
> ```

After our conversation with David (SDM of Amplify), we learned that the `framework` property is meant to be an open string that we can take in any value (if an invalid framework is entered, Amplify just ignores it and does not break).

I will go ahead an update my PR to include the `platform` property in the `amplify.App` construct to solve this issue. Thank you @calavera  and @udaypant !

**Comment by malikalimoekhamedov** [comment]
> ```js
> addBranch
> ```

Is it 'Next.js' or 'Next.js - SSR'?
