### ISSUE TITLE
aws_glue: CfnConnection for Kafka resource not creating properly

### ISSUE THREAD

**Issue by bmaguiraz** [aws/aws-cdk#23348]
### Describe the bug

When creating a glue connector connection to MSK with CDK, Glue throws an error using the connection.  

CDK successfully creates the connection connector with cdk but it throws this error when used.

"An error occurred while calling o100.getSource. Invalid Kafka connection parameters."

If I go into the Glue console click to resave the connector with no changes from the cdk deployed connector, the connector then works properly.  

CDK:

cfn_connection = glue.CfnConnection(self, "MyCfnConnection",
        catalog_id=f"{self.account}",
        connection_input=glue.CfnConnection.ConnectionInputProperty(
            connection_type="KAFKA",
            connection_properties={
                "KAFKA_BOOTSTRAP_SERVERS": MSKClusterStack.cluster.bootstrap_brokers,
                "KAFKA_SSL_ENABLED": "False",
            },
            description="cfn connection for kafka",
            name=f"{self.connection_name}",
            physical_connection_requirements=glue.CfnConnection.PhysicalConnectionRequirementsProperty(
                availability_zone="us-east-1a",
                security_group_id_list=[MSKClusterStack.msk_security_group.security_group_id],
                subnet_id=self.connection_subnet
                )
            )
        )

### Expected Behavior

Expect the Kafka Glue connection to work with a Glue Job and not throw an error.

### Current Behavior

When creating the Glue connection resource with CDK the connection throws an "An error occurred while calling o100.getSource. Invalid Kafka connection parameters."

### Reproduction Steps

This is the CDK:

cfn_connection = glue.CfnConnection(self, "MyCfnConnection",
        catalog_id=f"{self.account}",
        connection_input=glue.CfnConnection.ConnectionInputProperty(
            connection_type="KAFKA",
            connection_properties={
                "KAFKA_BOOTSTRAP_SERVERS": MSKClusterStack.cluster.bootstrap_brokers,
                "KAFKA_SSL_ENABLED": "False",
            },
            description="cfn connection for kafka",
            name=f"{self.connection_name}",
            physical_connection_requirements=glue.CfnConnection.PhysicalConnectionRequirementsProperty(
                availability_zone="us-east-1a",
                security_group_id_list=[MSKClusterStack.msk_security_group.security_group_id],
                subnet_id=self.connection_subnet
                )
            )
        )

It creates this resource that does not work
aws glue  get-connection --name msk-lab

Creates this resource that does not work.

{
    "Connection": {
        "Name": "msk-lab",
        "Description": "cfn connection for kafka",
        "ConnectionType": "KAFKA",
        "ConnectionProperties": {
            "KAFKA_BOOTSTRAP_SERVERS": "b-3.xxxxxx01.jw5kl4.c1.kafka.us-east-1.amazonaws.com:9092,b-1.xxxxxx01.jw5kl4.c1.kafka.us-east-1.amazonaws.com:9092,b-2.xxxxxx01.jw5kl4.c1.kafka.us-east-1.amazonaws.com:9092",
            "KAFKA_SSL_ENABLED": "False"
        },
        "PhysicalConnectionRequirements": {
            "SubnetId": "subnet-03f1cee545fdd3d0b",
            "SecurityGroupIdList": [
                "sg-0a63a76376f4a6dc6"
            ],
            "AvailabilityZone": "us-east-1a"
        },
        "CreationTime": "2022-12-14T15:44:57.371000+00:00",
        "LastUpdatedTime": "2022-12-14T20:16:15.243000+00:00"
    }
}

Click save in console with no changes.  The connection works.

{
    "Connection": {
        "Name": "msk-lab",
        "Description": "cfn connection for kafka",
        "ConnectionType": "KAFKA",
        "ConnectionProperties": {
            "KAFKA_BOOTSTRAP_SERVERS": "b-3.xxxxxx01.jw5kl4.c1.kafka.us-east-1.amazonaws.com:9092,b-1.xxxxxx01.jw5kl4.c1.kafka.us-east-1.amazonaws.com:9092,b-2.xxxxxx01.jw5kl4.c1.kafka.us-east-1.amazonaws.com:9092",
            "KAFKA_SSL_ENABLED": "false"
        },
        "PhysicalConnectionRequirements": {
            "SubnetId": "subnet-03f1cee545fdd3d0b",
            "SecurityGroupIdList": [
                "sg-0a63a76376f4a6dc6"
            ],
            "AvailabilityZone": "us-east-1a"
        },
        "CreationTime": "2022-12-14T15:44:57.371000+00:00",
        "LastUpdatedTime": "2022-12-14T20:34:59.671000+00:00"
    }
}

### CDK CLI Version

2.54.0 (build 9f41881)

### Node.js Version

v18.11.0

### OS

Linux

### Language

Python

### Language Version

Python 3.10.8

**Comment by peterwoodworth** [comment]
Hey, I'm sorry you're running into this.

Since you're using L1 resources - you're essentially using CloudFormation directly here. If an L1 resource isn't being created successfully during deployment, you likely have some configurations wrong. Be sure to check out both CloudFormation documentation and Glue documentation on the topic, I'm not familiar with these resources personally. If you need further assistance or think this is a bug with Glue/CloudFormation, I'd recommend going through AWS support if you have it. If not, I recommend going to the [CloudFormation Coverage Roadmap](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues) 🙂
