### ISSUE TITLE
aws_apigateway.Stage.fromStageAttributes: Property does not exist on type 'typeof Stage'

### ISSUE THREAD

**Issue by ChristopheLej** [aws/aws-cdk#23355]
### Describe the bug

I use cdk v2.54 with typescript v4.2.4 and I try to get a stage from other api:
const stage = aws_apigateway.Stage.fromStageAttributes(this, stageName, { stageName: "webapp", restApi: externalApi });

In pipeline jenkins with command "npx aws-cdk@2 deploy ...", I receive this error message: 
Unable to compile TypeScript:
error TS2339: Property 'fromStageAttributes' does not exist on type 'typeof Stage'

but in my editor, I can see this static method in the class Stage.
Have you an idea?
many thanks

CLE

### Expected Behavior

Unable to compile TypeScript

### Current Behavior

Unable to compile TypeScript:
error TS2339: Property 'fromStageAttributes' does not exist on type 'typeof Stage'

### Reproduction Steps

const externalApi = aws_apigateway.RestApi.fromRestApiId(this, apiName, apiId);
const stage = aws_apigateway.Stage.fromStageAttributes(this, stageName, { stageName: "webapp", restApi: externalApi });

### CDK CLI Version

2.54

### Node.js Version

14.20.1

### OS

linux

### Language

Typescript

### Language Version

4.2.4

**Comment by peterwoodworth** [comment]
Try reinstalling your packages and making sure all CDK versions are the same. This is appearing fine for me!

If you find a way to consistently reproduce this, let us know. Thanks!

**Comment by ChristopheLej** [comment]
I have reinstalled all latest version of librairies for cdk. Now, It's run normally, my project compile and I can deploy.
many thanks
