### ISSUE TITLE
(aws-cdk): Failure to invoke `esbuild`

### ISSUE THREAD

**Issue by adesso-os** [aws/aws-cdk#23379]
### Describe the bug

When trying to synthesize, CDK will fail due to an invalid attempt to invoke `esbuild`.

### Expected Behavior

No errors. Lambda is bundled as intended.

### Current Behavior

It seems CDK is trying to execute:
```
bash -c yarn run esbuild --bundle ...
```
Which obviously results in: `Usage Error: Couldn't find a script named "esbuild".`, because `yarn run` is used to execute scripts, not binaries.

### Reproduction Steps

Create a CDK project using yarn and have a `NodejsFunction` in the stack. Then `cdk synth`.

### Possible Solution

1. Use `yarn exec` or simply `yarn` to invoke `esbuild`.
2. Instead of involving the shell or a package manager at all, use the [esbuild API](https://esbuild.github.io/api/).

### CDK CLI Version

2.54.0 (build 9f41881)

### Node.js Version

18

### OS

WSL

### Language

Typescript

### Language Version

4.9

**Comment by adesso-os** [comment]
- #18175 sounds related, but seems to focus on an unrelated aspect
- #13179 also talks about the same issue

**Comment by peterwoodworth** [comment]
Hey @adesso-os, how are you defining your `NodejsFununction`, and could you also share your `package.json`? This will be helpful information to be able to help out with this issue. Thanks!

**Comment by DoctorMalice** [comment]
I ran into this issue while creating a stack as a nested workspace using yarn workspaces and making the lambda package.json a further nested workspace under that (mainProject/infrastructureStack/lambda). 

For those that may stumble across this and get sad there are no potential fixes listed here, I offer a somewhat silly but straightforward workaround: add the following into the root workspace package.json scripts section: `"esbuild": "esbuild"`

Here's an abbreviated version of my root project `package.json` as an example:

```
{
  "name": "root-project-name",
  "private": true,
  "workspaces": [
    "frontend",
    "backend",
    "shared"
  ],
  "scripts": {
    "test": "jest",
    "esbuild": "esbuild"
  },
  "packageManager": "yarn@3.3.1",
  "devDependencies": {
    "@types/node": "^18.13.0"
  }
}
```

**Comment by adesso-os** [comment]
@DoctorMalice Smart move 😄 Will keep this in mind. I still think CDK shouldn't be so ignorant about different package manager behaviors. Especially since esbuild has an API.

**Comment by StefanTheWiz** [comment]
@peterwoodworth can we re-open the issue and get a fix please? Not great DX for Amplify if I have to spend time on silly stuff like this just to get a project started...

**Comment by DCzajkowski** [comment]
I've fixed this (with the help of @gtluszcz) by adding esbuild as a `devDependency` to the monorepo's root `package.json`. Then, `yarn run esbuild` correctly finds the executable.
