### ISSUE TITLE
[Java] CDK enforce providing non-required fields when creating Cloudwatch EventPattern

### ISSUE THREAD

**Issue by varunnvs92** [aws/aws-cdk#2337]
**Describe the bug**
1) `EventPattern` is required for creating `EventRule`. Creating an `EventPattern` object in Java fails if values like Id, Region, Account etc are not provided (they are optional for the service). 

2) Due to this, I provided list of asterisk for all fields which I want to match everything (see below for generated event pattern). But Cloudwatch events doesn't match all fields with this structure. 
For example: If I want my pattern to match all resources, then I should not provide the `resources` field as per Cloudwatch event behavior. So using ` "resources": ["*"]` this doesn't work.

```
{
  "detail-type": [
    "CodePipeline Pipeline Execution State Change"
  ],
  "resources": [
    "*"
  ],
  "source": [
    "aws.codepipeline"
  ],
  "time": [
    "*"
  ],
  "id": [
    "*"
  ],
  "account": [
    "*"
  ]
}
```

**To Reproduce**
Java code
```
new EventRule(this, "id", EventRuleProps.builder()
                                        .withEventPattern(EventPattern.builder()
                                                                      .withSource(Arrays.asList("aws.codepipeline"))
                                                                      .withDetailType(Arrays.asList("CodePipeline Pipeline Execution State Change"))
                                                                      .build())
                                        .build());
```
This will fail saying fields like Id, Region, Account etc are not provided.

**Expected behavior**
Optional fields like Id, Region, Account should not be required by CDK

**Version:**
 - OS: Mac
 - Programming Language: Java
 - CDK Version: 0.26

**Comment by RomainMuller** [comment]
Hey @varunnvs92,

Can you please verify whether this is still an issue with the latest CDK? I suspect this has been fixed at this point.

**Comment by NGL321** [comment]
_Closing stale_

Feel free to reopen if pertinent questions arise!
😸
