### ISSUE TITLE
aws_certificatemanager: DNS Verification Record of Certificate Doesn't Get Deleted

### ISSUE THREAD

**Issue by akefirad** [aws/aws-cdk#23388]
### Describe the bug

The ACM verification DNS record remains in the hosted zone after the certificate is deleted.

### Expected Behavior

The record should be deleted when the certificate is deleted.

### Current Behavior

The record stays orphaned in the hosted zone.

### Reproduction Steps

I've got this stack:
```ts
export class NamesStack extends cdk.NestedStack {
  constructor(scope: Construct, id: string, props: NameStackProps) {
    super(scope, id, props);

    // Assuming the parent zone is one level up: foo.example.com -> example.com
    const parentHostedZone = r53.PublicHostedZone.fromLookup(this, "ParentHostedZone", {
      domainName: props.domainName.substring(props.domainName.indexOf(".") + 1),
    });

    // You have to add NS servers to the main hosted zone! Manuallay!
    const hostedZone = new r53.PublicHostedZone(this, "HostedZone", {
      zoneName: props.domainName,
    });

    new r53.ZoneDelegationRecord(this, "ZoneDelegationRecord", {
      zone: parentHostedZone,
      nameServers: hostedZone.hostedZoneNameServers!,
      comment: `Added by ${scope.node.id}/${id}`,
      recordName: props.domainName,
      deleteExisting: false,
    });

    const mainCertificate = new acm.DnsValidatedCertificate(this, "MainCertificate", {
      domainName: props.domainName,
      subjectAlternativeNames: [`*.${props.domainName}`],
      hostedZone: hostedZone,
    });
  }
}
```
When I deploy the above (among other things, including an EKS stack which makes the whole template pretty complicated), on a failure, the rollback fails because the record stays in the hosted zone and since the hosted zone contains "non-required" records it cannot be deleted.

### CDK CLI Version

2.55.1

### Framework Version

2.55.1

### Node.js Version

v16.16.0

### OS

macOS 12.6

### Language

Typescript

### Language Version

4.9.0

**Comment by corymhall** [comment]
@akefirad have you tried providing `cleanupRoute53Records: true` in `DnsValidatedCertificate`?

**Comment by akefirad** [comment]
Ah good point. I didn't know about it, but seems to be the answer. Feel free to close the issue. Thanks for support.
