### ISSUE TITLE
aws_pipeline: Improve Assets Stage In Pipeline

### ISSUE THREAD

**Issue by akefirad** [aws/aws-cdk#23387]
### Describe the feature

For EKS (and probably some other complicated) stacks, the **Assets** stage becomes insanely big and time consuming:
![image](https://user-images.githubusercontent.com/2142363/208314861-0de66a8f-70cc-4eca-b970-c311d4e00ede.png)
It would be really helpful if we can somehow optimize it.

### Use Case

This becomes a huge issue since it takes hours for the pipeline to complete. Even though the job itself is pretty small and quick, the waiting time to provision an instance to run the job takes minutes and for such big pipelines, for some reasons the provisioning takes even longer, like hours. Canceling and retrying also doesn't work since it starts over and there's no guarantee that it gets completed any sooner. It's such an issue for us that practically we can't use the pipeline (we deploy the stack manually from local machines, if the change is important).

### Proposed Solution

I'm not sure what would be the best solution, and not sure even if there's anything that can be done (🤞). But maybe merge all of them into one, or at least decrease the number of `FileAsset` jobs. Or maybe use a different technology?

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.55.0

### Environment details (OS name and version, etc.)

macOS 12.6

**Comment by tim-finnigan** [comment]
Hi @akefirad thanks for reaching out. Could you provide some more context on your use case? Have you tried any alternatives as far as your approach with the assets? I'm not sure but there may be some ways to optimize this. Please let us know if you have any updates on your end as far as what you've tried.

**Comment by hoegertn** [comment]
Hi, did you try the `parallelAssetPublishing: false` option of the pipeline?

**Comment by akefirad** [comment]
> Hi, did you try the parallelAssetPublishing: false option of the pipeline?

@hoegertn can you please help me on how to use the flag? I can't find anything about this flag on the web whatsoever 😄.

**Comment by akefirad** [comment]
Ah is it `publishInParallel`?

**Comment by hoegertn** [comment]
Yes sorry. Remembered the name incorrectly.

**Comment by akefirad** [comment]
@hoegertn thanks for the confirmation. That seems to be a CLI option. Do you know how actually set it, since I don't have access to "Asset" stage to set it. Maybe should I set it in `cdk.json` file of the project?

**Comment by hoegertn** [comment]
It is an option on the CodePipeline class called `publishAssetsInParallel`

**Comment by akefirad** [comment]
Right, just found it. Thanks. Checking it right now.

**Comment by akefirad** [comment]
Wonderful, works like a charm, the whole stage took less than a minute. The flag is too helpful to be missed in the documentation. Thanks for the support. Feel free to close this.

**Comment by tim-finnigan** [comment]
Thanks @hoegertn for that suggestion and @akefirad for confirming that worked! It looks like `publishInParallel` was added in https://github.com/aws/aws-cdk/pull/19367. I'll go ahead and close this.

**Comment by hoegertn** [comment]
The CDK pipeline feature was basically added in #13803 
But I see that my docs are not good enough for this.
