### ISSUE TITLE
AppSync: Code first schema generation removed, but alternative seems not available yet

### ISSUE THREAD

**Issue by bndkt** [aws/aws-cdk#23389]
### Describe the bug

2.55 remove the code first schema generation (https://github.com/aws/aws-cdk/pull/23250) and hints at [awscdk-appsync-utils](https://github.com/cdklabs/awscdk-appsync-utils) as the way forward. The new module doesn't seem to be available, though.

### Expected Behavior

Upgrade path to 2.55 for people who use code first schema generation.

### Current Behavior

No upgrade path, as code first schema generation was removed and the alternative is not yet available.

### Reproduction Steps

Upgrade to 2.55 and try to use any code first schema generation capabilities.

### CDK CLI Version

2.55.1

### Node.js Version

18

### OS

macOS

### Language

Typescript

**Comment by MrArnoldPalmer** [comment]
Hey there, https://www.npmjs.com/package/awscdk-appsync-utils should be available now. Thanks for flagging this just had to turn on our deploy actions again once 1.55.0 came out. Let me know if you have issues with usage or want to add any additional capabilities to awscdk-appsync-utils.
