### ISSUE TITLE
aws-cloudtrail: Enabling KMS encryption makes CDK fail with not enough permissions

### ISSUE THREAD

**Issue by stoennies** [aws/aws-cdk#23391]
### Describe the bug

Whenever I try to create a new CloudTrail and I enable KMS encryption the CDK script always fails with creating the ressources because of permission errors: Not enough permission to acces S3 or KMS:

Invalid request provided: Insufficient permissions to access S3 bucket ... or KMS key arn:aws:kms:eu-west-1:...... (Service: CloudTrail, Status Code: 400, Request ID: ....)" (RequestToken: ...., HandlerErrorCode: InvalidRequest)

### Expected Behavior

If I enable KMS encrption I expect that CDK creates the key and the S3 bucket in such way, that the access works.

### Current Behavior

The reousrce can not be created because of permission errors.

### Reproduction Steps

1) Use CDK 2.55.1
2) Create a KMS Key
3) Cretae a CloudTrail and enable KMS using the key from 2

### CDK CLI Version

2.55.1

### Node.js Version

16.17.0

### OS

Windows 10

### Language

Typescript

**Comment by tim-finnigan** [comment]
Hi @stoennies thanks for reaching out. This appears to overlap with an existing issue: https://github.com/aws/aws-cdk/issues/20344. I think what was said in [this comment](https://github.com/aws/aws-cdk/issues/20344#issuecomment-1134677863) still applies. If there are any distinctions you want to make between these issues please let us know, but for the sake of consolidation and tracking I think we should close this as a duplicate.
