### ISSUE TITLE
(events): L2 for EventBridge Scheduler

### ISSUE THREAD

**Issue by tmokmss** [aws/aws-cdk#23394]
### Describe the feature

EventBridge Scheduler was released on 2022/11. It is basically a powerful version of the existing EventBridge scheduled rules, with more scalability, timezone support, time window schedules, etc. [Introducing Amazon EventBridge Scheduler](https://aws.amazon.com/blogs/compute/introducing-amazon-eventbridge-scheduler/)

It would be great if we have a user friendly interface for this resource just like the existing L2 constructs in `aws-events` module. CloudFormation reference is [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-scheduler-schedule.html).

**NOTE**: L1 constructs are already available: [doc](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_scheduler-readme.html)

### Use Case

It will improve most of the use cases that currently use EventBridge scheduled rules.

### Other Information

The RFC process is completed: https://github.com/aws/aws-cdk-rfcs/pull/486

See the referenced PRs to check the progress of implementation.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.52.0

### Environment details (OS name and version, etc.)

n/a

**Comment by mascur** [comment]
Hi @tmokmss,

Thank you for this feature request! I think this would be a great addition! If you would like to contribute then you'll need to submit an [RFC](https://github.com/aws/aws-cdk-rfcs) first [because this is a new L2 construct](https://github.com/aws/aws-cdk/blob/v1-main/CONTRIBUTING.md#step-2-design).

I've marked this issue as a `p2`. We most likely won't be able to get to this issue. However, if you or another community member would like to submit a PR we might be able to review that. You can refer to the [Contribution Guide here](https://github.com/aws/aws-cdk/blob/v1-main/CONTRIBUTING.md) to get started.

We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. You can reach out to the [cdk.dev](http://cdk.dev/) community on [Slack](https://cdk.dev/) to solicit support for reprioritization.

**Comment by aldex32** [comment]
following

**Comment by yaojiach** [comment]
+1

**Comment by yaojiach** [comment]
+1

**Comment by filletofish** [comment]
Hey all, have started a RFC for this construct: https://github.com/aws/aws-cdk-rfcs/issues/474.

**Comment by wilhen01** [comment]
+1!

**Comment by anamariad** [comment]
+1

**Comment by vitaliknet** [comment]
+1

**Comment by ElliotWhiley** [comment]
+1

**Comment by andriimykhailovsumup** [comment]
+1

**Comment by filletofish** [comment]
Hi all,

RFC for L2 EB Scheduler Constructs was approved by bar-raiser. We are currently waiting for community feedback until April 19th. Please do take a look if interested. 

https://github.com/aws/aws-cdk-rfcs/pull/486

**Comment by meowsick** [comment]
+1

**Comment by roshni06** [comment]
Hi what is the status of this feature? When will this be merged?

**Comment by bharatjoshi11** [comment]
Hey everyone. 
I want to create eventbridge scheduler using golang is there any sdk available for that?

**Comment by weijiany** [comment]
+1

**Comment by filletofish** [comment]
Hi all, 

We have added recently a first L2 target class LambdaInvoke to `scheduler-targets-alpha` package. See example at https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/aws-scheduler-targets-alpha/lib/lambda-invoke.ts. 

We need to implement other 11 templated targets as L2 CDK constructs. These targets could be implemented in parallel and could be a good beginner / first issue to work on.

I have created a bunch of issues to track the work on targets: 

1. https://github.com/aws/aws-cdk/issues/27448
2. https://github.com/aws/aws-cdk/issues/27449
3. https://github.com/aws/aws-cdk/issues/27450
4. https://github.com/aws/aws-cdk/issues/27451
5. https://github.com/aws/aws-cdk/issues/27453
6. https://github.com/aws/aws-cdk/issues/27454
7. https://github.com/aws/aws-cdk/issues/27456
8. https://github.com/aws/aws-cdk/issues/27457
9. https://github.com/aws/aws-cdk/issues/27458
10. https://github.com/aws/aws-cdk/issues/27459

**Comment by WtfJoke** [comment]
For completeness:
11. https://github.com/aws/aws-cdk/issues/27377 (including PR https://github.com/aws/aws-cdk/pull/27424)

**Comment by filletofish** [comment]
One more - https://github.com/aws/aws-cdk/issues/27543

**Comment by filletofish** [comment]
Also tracking feature to override target properties in https://github.com/aws/aws-cdk/issues/27545

**Comment by kaizencc** [comment]
I am going to close this as completed. We have a full-blown alpha module and targets now for eventbridge scheduler. all additional work can be tracked individually, we have followed through on the ask for an L2 for EventBridge. Lets create new issues for any feature requests and bug fixes and go from there! Excited to see this one in.
