### ISSUE TITLE
Golang support

### ISSUE THREAD

**Issue by buffovich** [aws/aws-cdk#234]
WebAssembly is the standard compiler backend now. So, why not?
https://medium.zenika.com/go-1-11-webassembly-for-the-gophers-ae4bb8b1ee03

**Comment by joebowbeer** [comment]
I think cdk needs support for golang as first-class language. golang is already supported as a first-class language in Lambda, CodeSuite, etc., and its absence is conspicuous here.

I suggest reopening this issue rather than tying the solution to a specific technology such as jssi or webassembly.

**Comment by jordanst3wart** [comment]
#547 is more fresh
