### ISSUE TITLE
(triggers): deployments of trigger functions fail with `TypeError [ERR_INVALID_ARG_TYPE]: The "msecs" argument must be of type number. Received type string`

### ISSUE THREAD

**Issue by cecheta** [aws/aws-cdk#23407]
Please add your +1 👍 to let us know you have encountered this
*---*

*### Status: IN-PROGRESS*

*### Overview:*

*Root cause:* breaking change in #23062 caused the wrong type to be passed to CloudFormation (`string` where a `number` was expected). The integration test that was supposed to catch this somehow did not run, that is still being investigated.

When trying to invoke a function using the `triggers` module, an error occurs when the stack is deployed. `InvocationType.EVENT` invocation also does not work as the status code returned is not 200. 

*#### Complete Error Message:*

```
submit response to cloudformation {
  Status: 'FAILED',
  Reason: `TypeError [ERR_INVALID_ARG_TYPE]: The "msecs" argument must be of type number. Received type string ('120000')\n` +
    '    at new NodeError (internal/errors.js:322:7)\n' +
    '    at validateNumber (internal/validators.js:129:11)\n' +
    '    at getTimerDuration (internal/timers.js:384:3)\n' +
    '    at ClientRequest.setTimeout (_http_client.js:865:11)\n' +
    '    at features.constructor.handleRequest (/var/runtime/node_modules/aws-sdk/lib/http/node.js:82:12)\n' +
    '    at executeSend (/var/runtime/node_modules/aws-sdk/lib/event_listeners.js:370:29)\n' +
    '    at Request.SEND (/var/runtime/node_modules/aws-sdk/lib/event_listeners.js:384:9)\n' +
    '    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:102:18)\n' +
    '    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)\n' +
    '    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:686:14)',
  StackId: 'arn:aws:cloudformation:us-east-1:***:stack/TestStack/83f77790-806c-11ed-8956-0a55d38b49ed',
  RequestId: '86a74312-347d-40c4-873a-09eed5b8eddd',
  PhysicalResourceId: 'AWSCDK::CustomResourceProviderFramework::CREATE_FAILED',
  LogicalResourceId: 'Trigger',
  NoEcho: undefined,
  Data: undefined
}
```

or

```
Error: Trigger handler failed with status code 202 at handler (/var/task/index.js:53:15) at processTicksAndRejections (internal/process/task_queues.js:95:5) at async Runtime.handler (/var/task/__entrypoint__.js:32:24) (RequestId: ab252a7a-e06b-4fcf-b2b4-f59b2dd88734)
```

*### Solution:* Revert #23062 until a more permanent fix is found.

### Reproduction Steps

Deploy stack:

```ts
const func = new lambda.Function(stack, 'Function', {
  runtime: lambda.Runtime.NODEJS_18_X,
  handler: 'index.handler',
  code: lambda.Code.fromInline('exports.handler = function() { console.log("hello"); };'),
});

const trigger = new triggers.Trigger(stack, 'Trigger', {
  handler: func,
  invocationType: triggers.InvocationType.EVENT,
});

```

**Comment by peterwoodworth** [comment]
Hey @cecheta, where are you finding the `invocationType` prop and the `InvocationType` enum? I can't find these in our API anywhere

**Comment by cecheta** [comment]
> Hey @cecheta, where are you finding the `invocationType` prop and the `InvocationType` enum? I can't find these in our API anywhere

They were added in #23062 

It's not in the latest release of the CDK yet, I ran into this issue when trying to create an integration test for an unrelated module

**Comment by peterwoodworth** [comment]
Ah I see, thanks for being on top of this!

**Comment by tenjaa** [comment]
After merging cdk 2.56.0 today my deployment failed with that error message.

**Comment by kollmats** [comment]
I'm seeing this error too. I'm not explicitly passing any invocation type. My lambda does have a timout though. Downgrading to the version before 2.56.0 works.

**Comment by DerkSchooltink** [comment]
Since I introduced the bug I will attempt to fix it :)  I'm working on a PR

**Comment by DerkSchooltink** [comment]
Not honouring the types specified to the custom resource seems to be related to https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1037 

I'm not sure exactly what the way forward with that specific issue is. I will implement it as string and revert it back in the function handler, but perhaps in the future we can revert that change.

**Comment by tenjaa** [comment]
Is there any update on this as this stops us completely from updating cdk at the moment?

**Comment by DerkSchooltink** [comment]
Holidays are over, I will have time for it soon :)
