### ISSUE TITLE
How to set authentication for elasticsearch

### ISSUE THREAD

**Issue by vjindalradialtheory** [aws/aws-cdk#2342]
How we can set authentication for elasticsearch ?

**Comment by cmckni3** [comment]
Appears that it's not supported by `@aws-cdk/aws-elasticsearch` yet. I believe an approach may be to create a custom resource that handles it `onCreate`.

In CloudFormation the fields are:

```
Enabled: boolean;
UserPoolId: string;
IdentityPoolId: string;
RoleArn: string;
```

**Comment by SomayaB** [comment]
Hi @vjindalradialtheory, like @cmckni3 mentioned, cognito for elasticsearch is not yet supported by cloudformation which means it isn't supported by the CDK. So in the meantime the best way is to follow the above steps. Thanks @cmckni3! 👍

Closing for now, but feel free to reopen.

**Comment by steffeng** [comment]
> elasticsearch is not yet supported by cloudformation

Now it is https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticsearch-domain-cognitooptions.html

**Comment by cmckni3** [comment]
Awesome!

I got the API and CFN docs mixed up. Exampled I posted came from AWS CLI.

Can use the AWS CDK [escape hatch](https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html#raw_overrides) until official CDK support.

Thanks @steffeng!

**Comment by iliapolo** [comment]
We are actively working on an [Elasticsearch L2](https://github.com/aws/aws-cdk/pull/8369) which will also include cognito authentication. In any case, The L1 also supports cognito options now: 

https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-elasticsearch.CfnDomain.CognitoOptionsProperty.html
