### ISSUE TITLE
cdk-route53: from_hosted_zone_attributes on imported stack has empty hosted_zone_name_servers

### ISSUE THREAD

**Issue by Marakai** [aws/aws-cdk#23436]
### Describe the bug

Using `from_hosted_zone_attributes` on an import Route53 stack (via YAML template) and trying to set `CfnOutput` to print the nameservers after completion.

The list of `hosted_zone_name_servers` is `None`, though they are clearly set in the Route53 zone. `hosted_zone_id` is correctly set, but of course that's passed in as parameter anyway.

### Expected Behavior

I expect to see the populated list of the name servers and be able to set them to the CFN `Outputs`.

### Current Behavior

the list of name servers is empty. Single-stepping in an IDE and drilling down, also shoes the attribute to be empty.

### Reproduction Steps

 ```
def __init__(self, scope: Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        my_zone = cfn_inc.CfnInclude(self, "MyImportedZone", template_file="myzone-route53.yaml"))

        _my_zone = route53.HostedZone.from_hosted_zone_attributes(self, 'MyZone', hosted_zone_id='ZOMETHING', zone_name='my.domain')


        CfnOutput(self, 'MyZoneId', value=_my_zone.hosted_zone_id)
        CfnOutput(self, 'MyServers',
                  value=Fn.join(',', _my_zone.hosted_zone_name_servers),
                  export_name='MY-NAMESERVERS')
```

### CDK CLI Version

2.49.1

### Node.js Version

14.20.1

### OS

Centos 8

### Language

Python

### Language Version

Python 3.9.11

**Comment by peterwoodworth** [comment]
Imported resources only contain the information that you have explicitly defined - no actual lookups are being performed. See [here](https://docs.aws.amazon.com/cdk/v2/guide/resources.html) for more info

**Comment by Marakai** [comment]
This begs the question what purpose an import would serve then.

In addition: I don't explicitly define the nameservers for a hosted zone! They are assigned by Route53.

How do I get to the list of assigned nameservers in this situation then? That is not at all clear from the documentation: it works fine when creating a new hosted zone in CDK, but when I import one I can't retrieve them?!

**Comment by peterwoodworth** [comment]
When importing constructs via methods like `fromXxxName`, `fromXxxArn`, `fromXxxAttributes`, etc, will not perform lookups. The purpose of those methods is to create a proxy class which you can pass to other constructs that require a class of a certain type. 

> Many AWS CDK classes require properties that are AWS CDK resource objects (resources). For example, an Amazon ECS resource requires a reference to the cluster on which it runs. An Amazon CloudFront distribution requires a reference to the bucket containing the source code.

We do support some methods with context lookups. You can use the [`fromLookup()`](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_route53.HostedZone.html#static-fromwbrlookupscope-id-query) method, which will lookup some necessary information for your Hosted Zone, but not the information you desire. 

To dynamically retrieve the information you desire with CDK, you would need to configure that lookup with a custom resource that makes use of an API call which can fetch this information, like [ListResourceRecordSets](https://docs.aws.amazon.com/Route53/latest/APIReference/API_ListResourceRecordSets.html). This would be the case for nearly any information you want to look up at deploy time
