### ISSUE TITLE
(aws-appsync): (Not able to attach a Lambda Authorizer to two GraphqlApi)

### ISSUE THREAD

**Issue by ranjith-jagadeesh** [aws/aws-cdk#23434]
### Describe the bug

When I attach a Lambda Authorizer to two graphql api, I'm getting an error, "There is already a construct with name appsync for lambda".

Attaching the screenshot for reference.
<img width="1210" alt="image" src="https://user-images.githubusercontent.com/86655894/209063686-b4d8642b-839d-46b8-9eb4-946775872277.png">

### Expected Behavior

Should attach lambda authorizer to two or more graphql api, with different costruct name.

### Current Behavior

Currently it is attaching lambda permission with same construct name "appsync" which is resulting in this error. Should create a addPermission with different construct name.

### Reproduction Steps

Create a LambdaAuthorizer and attach it to two or more GraphqlApi.

### CDK CLI Version

2.46

### Node.js Version

16

### OS

Mac

### Language

Typescript

**Comment by ranjith-jagadeesh** [comment]
Issue on this line 
<img width="876" alt="image" src="https://user-images.githubusercontent.com/86655894/209063788-e403d8cc-c52e-4687-b06b-a4ce31ca0ebf.png">

Instead of just passing 'appsync' as construct name, pass `${id}-appsync`, so it will have different construct name when attaching two or more graphql api.

I'm giving a fix in few mins

**Comment by peterwoodworth** [comment]
I can confirm this, thanks for reporting.

This code can reproduce the issue:

```
    const api = new appsync.GraphqlApi(this, 'api', {
      name: 'api',
      schema: appsync.SchemaFile.fromAsset('assets/graphql/schema.graphql'),
      authorizationConfig: {
        defaultAuthorization: {
          authorizationType: appsync.AuthorizationType.LAMBDA,
          lambdaAuthorizerConfig: {
            handler: authFn,
          },
        },
        additionalAuthorizationModes: [{
          authorizationType: appsync.AuthorizationType.LAMBDA,
          lambdaAuthorizerConfig: {
            handler: authFn2,
          },
        }]
      }
    });
```

Link to code here, your suggested solution sounds great :) https://github.com/aws/aws-cdk/blob/1485f48c515f81fa585a325e02f1602f56443605/packages/%40aws-cdk/aws-appsync/lib/graphqlapi.ts#L533-L541

I am marking this issue as p2, which means that we are unable to work on this immediately.

We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://cdk.dev) to solicit support for reprioritization.

Check out our [contributing guide](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) if you're interested in contributing yourself - there's a low chance the team will be able to address this soon but we can try to review a PR 🙂

**Comment by ranjith-jagadeesh** [comment]
@peterwoodworth I gave the fix, Please take a look at the PR https://github.com/aws/aws-cdk/pull/23435

**Comment by peterwoodworth** [comment]
Thanks for the PR @ranjith-jagadeesh,

Before we're able to give a review, you'll need to add integration testing. Additionally, this will be a breaking change (to an unstable module), so be sure to edit your PR description to make it clear that this is a breaking change because the logical ID is changing.

**Comment by owenmorgan** [comment]
hi there - any update on this issue? also seeing this and its blocking. Thanks

**Comment by ranjith-jagadeesh** [comment]
Till it gets merged, you can use it like this to avoid this error.
```NodejsFunction.fromFunctionArn(
        this,
        'authorizer',
        this.authorizer.functionArn
      )```

**Comment by ranjith-jagadeesh** [comment]
@peterwoodworth I have added integration tests, which is pending for a long time. Can you please review and merge.
