### ISSUE TITLE
(aws-rds): SnapshotCredentials generate a dummy credentials 

### ISSUE THREAD

**Issue by chitraprasanna** [aws/aws-cdk#23441]
### Describe the bug

I had issues in updating the DB master credentials, so I opted for this workaround:

https://github.com/aws/aws-cdk/issues/19409

```
  const existingSecret = aws_secretsmanager.Secret.fromSecretPartialArn(stack, 'db-secret', existingDBSecretArn.stringValue);;
      // Issue: https://github.com/aws/aws-cdk/issues/19409
      const dbCredentials = aws_rds.SnapshotCredentials.fromSecret(existingSecret as aws_secretsmanager.Secret);
      const clusterFromSnapshot = new aws_rds.DatabaseClusterFromSnapshot(stack, clusterName, {
        snapshotIdentifier: snapshotIdIn,
        clusterIdentifier: clusterName,
        snapshotCredentials: dbCredentials,
        ...
       });

```

Now I can login the DB is using the existing credentials.

### Expected Behavior

When existing Secrets is specified, a single SecretTargetAttachment with the reference to the existing secrets is expected.

### Current Behavior

However when I look at the CF resources of this stack, none of secret attachments of this db-cluster stack are referring to the existing dbSecretArn.
But, I notice several secret attachments with random ids, and none of those secret values are the above master dbSecretArn.

### Reproduction Steps

Deploy the above using npx cdk deploy stack-name

### CDK CLI Version

npx cdk --version 2.29.1 (build c42e961)

### Node.js Version

8.7.0

### OS

mac

### Language

Typescript

**Comment by peterwoodworth** [comment]
I'm unable to reproduce this, please upgrade to latest version and also ensure that the arn you're providing is the arn you're expecting.  If you continue to run into this issue, please provide full stack code which I can copy + run without any modifications. Thank you!
