### ISSUE TITLE
(init-templates): cdk init app ignores python version when generating requirements

### ISSUE THREAD

**Issue by teleological** [aws/aws-cdk#23458]
### Describe the bug

`cdk init --language python` generates `requirements.txt` using the active version of `aws-cdk`, even if that version is not compatible with the active version of python. When this happens, `pip install -r requirements.txt` fails with a message showing that the requested version of `aws-cdk-lib` is not available: `Could not find a version that satisfies the requirement aws-cdk-lib==2.56.0`

### Expected Behavior

Expected init to either inject a version of `aws-cdk-lib` compatible with the virtualenv that it generates, or failing that, to emit a warning that the the version of python needs to be upgraded.

### Current Behavior

1. Installed `aws-cdk` on Mac OS X 13.0 via homebrew: aws-cdk 2.56.0 (build 1485f48).
2. Created new project with `cdk init app --language python`. Init script created virtual environment with active python 3.6.13, as indicated in `.venv/pyvenv.cfg`.
3. With virtual environment active, tried to install generated requirements: `pip install -r requirements.txt`. Failed with error message that `aws-cdk-lib==2.56.0` is not available.
```
% pip install -r requirements.txt
ERROR: Could not find a version that satisfies the requirement aws-cdk-lib==2.56.0 (from versions: 2.0.0a1, 2.0.0a2, 2.0.0a3, 2.0.0a4, 2.0.0a5, 2.0.0a6, 2.0.0a10, 2.0.0a11, 2.0.0a12, 2.0.0a13, 2.0.0a14, 2.0.0rc1, 2.0.0rc3, 2.0.0rc4, 2.0.0rc5, 2.0.0rc6, 2.0.0rc7, 2.0.0rc8, 2.0.0rc9, 2.0.0rc10, 2.0.0rc11, 2.0.0rc12, 2.0.0rc13, 2.0.0rc14, 2.0.0rc15, 2.0.0rc16, 2.0.0rc17, 2.0.0rc18, 2.0.0rc19, 2.0.0rc20, 2.0.0rc21, 2.0.0rc22, 2.0.0rc23, 2.0.0rc24, 2.0.0rc25, 2.0.0rc26, 2.0.0rc27, 2.0.0rc28, 2.0.0rc29, 2.0.0rc30, 2.0.0rc31, 2.0.0rc32, 2.0.0rc33, 2.0.0, 2.1.0, 2.2.0, 2.3.0, 2.4.0, 2.5.0, 2.6.0, 2.7.0, 2.8.0, 2.9.0, 2.10.0, 2.11.0, 2.12.0, 2.13.0, 2.14.0, 2.15.0, 2.16.0, 2.17.0, 2.18.0, 2.19.0, 2.20.0, 2.21.0, 2.21.1, 2.22.0, 2.23.0)
ERROR: No matching distribution found for aws-cdk-lib==2.56.0
```
4. Diagnosed the problem by running `pip install -v -r requirements.txt`. Output is verbose, but includes: `The package … aws_cdk_lib-2.56.0-py3-none-any.whl … (requires-python:~=3.7) is incompatible with the pythonversion in use. Acceptable python versions are:~=3.7`

### Reproduction Steps

With `aws-cdk` >= 2.56.0 and `python` < 3.7:
```
cdk init app --language python
source .venv/bin/activate
pip install -r requirements.txt
```

### Possible Solution

The root issue seems to be that `aws-cdk/packages/aws-cdk/lib/init-templates/app/python/requirements.txt` injects the version of `cdk` without checking for compatibility against the version of python used to generate the virtualenv

If it's not practical to check the version of python, perhaps the script could output a warning that explains that if `requirements.txt` fails to install with error "Could not find a version that satisfies the requirement aws-cdk-lib", that it may be necessary to upgrade Python.

### CDK CLI Version

2.56.0 (build 1485f48)

### Node.js Version

v18.1.0

### OS

Mac OS X 13.0

### Language

Python

### Language Version

3.6.13

**Comment by teleological** [comment]
I note that Python 3.6 is EOL'd, which probably explains why 3.7 is required. https://endoflife.date/python

**Comment by rix0rrr** [comment]
* If your request is to make CDK stop requiring Python 3.7... well we have to draw the line somewhere and we're not really looking to support EOL versions of anything.
* If you want to keep using Python 3.7 and want to use an older version of CDK to do it... well then you know what the issue is and you probably also know how to get around it. You might also be able to trick `pip` into disregarding Python requirements and installing the package anyway.
