### ISSUE TITLE
Cloudfront Distribution: Custom Domain Url from S3 website url does not configure correctly

### ISSUE THREAD

**Issue by Punith13** [aws/aws-cdk#23463]
### Describe the bug

Hi cdk team ,

There is a bug when we configure custom domain url from S3 websiteurl , the routing stops. I currently manually re-configure the url including the http:// , to enable the traffic routing from cloudfront to S3 websiteurl after the deployment is complete.

Below is my code sample. 

```
      defaultBehavior: {
        origin: new cloudfront_origins.HttpOrigin(
          cdk.Fn.select(2, cdk.Fn.split("/", bucket.bucketWebsiteUrl))),
          .... 
      }
```

### Expected Behavior

The routing from cloudfront to S3 websiteurl should not break after deployment

### Current Behavior

The routing from cloudfront to S3 websiteurl breaks after deployment.

### Reproduction Steps

In a sample cdk project. 

- Configure a S3 hosted website
- Configure Cloudfront distribution with custom Httporigin and point to S3 bucketWebsiteUrl

### CDK CLI Version

2.41.0

### Node.js Version

v16.15.0

### OS

macos

### Language

Typescript

**Comment by peterwoodworth** [comment]
Based on this issue description I'm not sure if your code snippet is an example of a code snippet to reproduce the issue, or if it's an example of how you worked around the issue. Could you please provide a full stack definition which reproduces the error you've described?

**Comment by Punith13** [comment]
Hi Peter, 

The code configured below stops routing traffic when deployed. I have used Httporigin instead of S3 origin as I had to make the site public and access via cloudfront. Now after deployment I log into console , copy the website url from S3 website hosting and manually reconfigure it as custom origin in cloudfront distribution origin to get the site working again. 


Cloudfront Stack 
```
import * as route53 from "aws-cdk-lib/aws-route53";
import * as s3 from "aws-cdk-lib/aws-s3";
import * as acm from "aws-cdk-lib/aws-certificatemanager";
import * as cloudfront from "aws-cdk-lib/aws-cloudfront";
import * as targets from "aws-cdk-lib/aws-route53-targets";
import * as cloudfront_origins from "aws-cdk-lib/aws-cloudfront-origins";
import * as s3deploy from "aws-cdk-lib/aws-s3-deployment";

import * as cdk from "aws-cdk-lib";
import { Construct } from "constructs";

const path = require("node:path");

export interface CDKS3WebsiteStackProps extends cdk.StackProps {
  domainName: string;
  websiteBucket: s3.Bucket;
}

export class CDKS3WebsiteStack extends cdk.Stack {
  constructor(scope: Construct, name: string, props: CDKS3WebsiteStackProps) {
    super(scope, name, props);

    const zone = route53.HostedZone.fromLookup(this, "Zone", {
      domainName: props.domainName,
    });
    const siteDomain = `${props.domainName}`;

    const siteBucket = s3.Bucket.fromBucketName(
      this,
      "SiteBucket",
      props.websiteBucket.bucketName
    );

    // TLS certificate
    const certificate = new acm.DnsValidatedCertificate(
      this,
      "SiteCertificate",
      {
        domainName: siteDomain,
        hostedZone: zone,
        region: "us-east-1", // Cloudfront only checks this region for certificates.
      }
    );

    // CloudFront distribution  // DO NOT EDIT OR WEBSITE WILL BREAK - Punith Nayak
    const distribution = new cloudfront.Distribution(this, "SiteDistribution", {
      certificate: certificate,
      domainNames: [siteDomain],
      minimumProtocolVersion: cloudfront.SecurityPolicyProtocol.TLS_V1_2_2021,
      errorResponses: [
        {
          httpStatus: 400,
          responseHttpStatus: 200,
          responsePagePath: "/",
          ttl: cdk.Duration.minutes(5),
        },
        {
          httpStatus: 403,
          responseHttpStatus: 200,
          responsePagePath: "/",
          ttl: cdk.Duration.minutes(5),
        },
      ],
      defaultBehavior: {
        origin: new cloudfront_origins.HttpOrigin(
          cdk.Fn.select(2, cdk.Fn.split("/", siteBucket.bucketWebsiteUrl))
        ),
        compress: true,
        allowedMethods: cloudfront.AllowedMethods.ALLOW_GET_HEAD_OPTIONS,
        viewerProtocolPolicy: cloudfront.ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
      },
    });

    // Route53 alias record for the Cloudfront distribution
    new route53.ARecord(this, "SiteAliasRecord", {
      recordName: siteDomain,
      target: route53.RecordTarget.fromAlias(
        new targets.CloudFrontTarget(distribution)
      ),
      zone,
    });

    // Deploy site contents to S3 bucket
    new s3deploy.BucketDeployment(this, "DeployWithInvalidation", {
      sources: [s3deploy.Source.asset(path.relative(__dirname, "build"))],
      destinationBucket: siteBucket,
      distribution,
      distributionPaths: ["/*"],
    });

    siteBucket.grantPublicAccess();
  }
}
```

S3 website hosting 
```

import { Stack, StackProps, RemovalPolicy } from "aws-cdk-lib";
import { Construct } from "constructs";
import * as s3 from "aws-cdk-lib/aws-s3";
import * as iam from "aws-cdk-lib/aws-iam";

export class CdkS3BucketStack extends Stack {
  public readonly websiteBucket: s3.Bucket;

  constructor(scope: Construct, id: string, props: StackProps) {
    super(scope, id, props);

    this.websiteBucket = new s3.Bucket(this, "WebsiteBucket", {
      bucketName: `test-bucketname`,
      cors: [
        {
          allowedMethods: [s3.HttpMethods.GET],
          allowedOrigins: ["*"],
          allowedHeaders: ["Authorization", "Content-Length"],
          maxAge: 3000,
        },
      ],
      encryption: s3.BucketEncryption.S3_MANAGED,
      blockPublicAccess: {
        blockPublicAcls: false,
        blockPublicPolicy: false,
        ignorePublicAcls: false,
        restrictPublicBuckets: false,
      },
      publicReadAccess: true,
      removalPolicy: RemovalPolicy.RETAIN,
      websiteIndexDocument: "index.html",
    });

  }
}


```

**Comment by peterwoodworth** [comment]
Thanks for sharing reproduction code, it's helpful. 

My follow up question for you is this: what is exactly the point of failure? Is the CloudFormation deployment successful, and you run into a 503 error when attempting to reach the distribution endpoint? If so, could you check the console for your distribution and check what the origin domain is for this bucket - and if it's the expected value?

**Comment by Punith13** [comment]
Yes, I get the 504 timeout error after the deployment is successful. When I look into the console of the origin domain , it reads - **_website-example.s3-website-us-east-1.amazonaws.com_**, which is the expected value. 

What I have also observed is, when we copy the website url manually from S3 website which includes the http:// , paste it in the origin domain text box and select the value that appears in the drop down, we stop getting the 504 error. The value at origin domain again reads **_website-example.s3-website-us-east-1.amazonaws.com_** without http:// and this is bit puzzling.

**Comment by peterwoodworth** [comment]
I'm encountering the same thing @Punith13, the deployment will result in a 504 error. However if I go into the console, cut & paste the origin domain name, then select it and save changes, I will stop getting the 504 error. 

I believe this is a bug with CloudFront/CloudFormation. I have reported this internally (P78321288). Will provide updates here when they become available. Thanks for reporting this bug 🙂

**Comment by Punith13** [comment]
Cool, no worries. Glad the issue is triaged :)

**Comment by peterwoodworth** [comment]
Service team got back - try setting [protocolPolicy](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_cloudfront_origins.HttpOriginProps.html#protocolpolicy) to `HTTP_ONLY` in the `HttpOrigin` props, this should fix the issue since S3 websites must use HTTP_ONLY. This field is automatically updated when using the console, but of course cannot be improperly specified in a CloudFormation Template.

Let me know if this does not work for you, thanks!

**Comment by Punith13** [comment]
Thanks @peterwoodworth . I will give it a try and update here.
