### ISSUE TITLE
(core): '#' markdown in Stack inline doc is messing up jsii-docgen generator 

### ISSUE THREAD

**Issue by flochaz** [aws/aws-cdk#23465]
### Describe the issue

The extra `#` in Stack inline doc  (https://github.com/aws/aws-cdk/blob/4673c8b24c988e9ef931720f23e635a8827f370d/packages/@aws-cdk/core/lib/stack.ts#L1171) is messing up jsii-docgen generator when creating an extend of Stack.

Here is a screenshot of the generated markdown rendered:  ![Screenshot 2022-12-26 at 11 14 25](https://user-images.githubusercontent.com/1225809/209537058-34443ae2-954c-4694-b204-a19fe4b708a5.png)

### Links

https://github.com/aws/aws-cdk/blob/4673c8b24c988e9ef931720f23e635a8827f370d/packages/@aws-cdk/core/lib/stack.ts#L1171

**Comment by peterwoodworth** [comment]
Thanks for the PR to fix this 🙂
