### ISSUE TITLE
aws-stepfunctions-tasks: Allow using a specific revision in EcsRunTask

### ISSUE THREAD

**Issue by AdamJHall** [aws/aws-cdk#23491]
### Describe the feature

Currently when defining a `EcsRunTask` you pass through a `TaskDefinition` however the resulting stepfunction only references the task definitions family and the step function will use the latest "Active" definition.

However I would like to specify a revision number so that I can reference older task definition versions. This does seem to be possible with the underlying cloudformation but not via CDK.

### Use Case

I have one stack which defines the task definition and another stack that accepts that stack as a prop and deploys a step function using that task definition. 

There will be multiple instances of the stepfunction stack and I want that stepfunctions created by those stacks to refer to that task definition that it was referencing at that point in time.  

### Proposed Solution

Something like the below would be ideal, where `revisionNumber` is optional to not break current behaviour. 

```typescript
const runTask = new EcsRunTask(this, "RunTask", {
    cluster,
    taskDefinition,
    revisionNumber: taskDefinition.revisionNumber,
    launchTarget: new EcsFargateLaunchTarget(),
});
```

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.43.1

### Environment details (OS name and version, etc.)

Ubuntu 20.04

**Comment by peterwoodworth** [comment]
According to the [API ref,](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_RunTask.html#ECS-RunTask-request-taskDefinition) we should specify the task definition with `family:revision`. Currently, we only specify `family`. It should be easy to append the revision here if specified, thanks for the request!

I am marking this issue as p2, which means that we are unable to work on this immediately.

We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://cdk.dev) to solicit support for reprioritization.

Check out our [contributing guide](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) if you're interested in contributing yourself - there's a low chance the team will be able to address this soon but we can try to review a PR 🙂

**Comment by zorrofox** [comment]
I have a question about this requirement, because if we use different Revision Number for `TaskDefinition` there will be different `TaskDefinition` instance and how we can modified the `EcsRunTask` property `taskDefinition`?

**Comment by westhouseK** [comment]
@peterwoodworth
May I work on it? I want to try it!
I'm going to fix `TaskDefinition`, is it ok?

**Comment by peterwoodworth** [comment]
Yes, go ahead @westhouseK! Be sure to add unit and integration testing, and to follow the contributing guide I linked above!
