### ISSUE TITLE
(pipes): Add L2 support for Amazon EventBridge Pipes

### ISSUE THREAD

**Issue by moltar** [aws/aws-cdk#23495]
### Describe the feature

Add L2 constructs for Amazon EventBridge Pipes

### Use Case

N/A

### Proposed Solution

N/A

### Other Information

- Announcement: https://aws.amazon.com/blogs/aws/new-create-point-to-point-integrations-between-event-producers-and-consumers-with-amazon-eventbridge-pipes/?sc_channel=el
- Landing: https://aws.amazon.com/eventbridge/pipes/
- CF: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-pipes-pipe.html

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

N/A

### Environment details (OS name and version, etc.)

N/A

**Comment by peterwoodworth** [comment]
Thanks for the request, it would be great to have L2s for this service.

We'll need an approved [RFC](https://github.com/aws/aws-cdk-rfcs) before we can approve a PR for new L2s. If anyone is interested, please go ahead and submit an RFC in the [RFCs repo. ](https://github.com/aws/aws-cdk-rfcs) Thanks!

**Comment by MaazDev** [comment]
was the RFC created ?

**Comment by RaphaelManke** [comment]
I created a tracking issue and put some thoughts into a possible api 😃 
https://github.com/aws/aws-cdk-rfcs/issues/473
