### ISSUE TITLE
(aws-s3): Logging Bucket blocks KMS_MANAGED encryption

### ISSUE THREAD

**Issue by biffgaut** [aws/aws-cdk#23513]
### Describe the bug

PR [23385](https://github.com/aws/aws-cdk/pull/23385) introduced a check to block launching S3 access log buckets with KMS encryption. S3 does not support access log buckets with KMS encryption, so previously these stacks would launch but fail to generate any logs. This PR would throw an Error when this occurred.

The PR included KMS_MANAGED in the list of blocked encryptions, but tests show that S3 buckets with KMS_MANAGED encryption can accepts logs. So the application threw an error for configurations that were valid.

KMS_MANAGED needs to be removed from the list of encryptions flagged by the code.

### Expected Behavior

This code should not throw an error:

```
    const stack = new cdk.Stack();
    new s3.Bucket(stack, 'MyBucket', { encryption: s3.BucketEncryption.KMS_MANAGED, serverAccessLogsPrefix: 'test' });
```

### Current Behavior

That code throws 'SSE-S3 is the only supported default bucket encryption for Server Access Logging target buckets'

### Reproduction Steps

```
    // This code should not throw an error upon deployment
    new s3.Bucket(this, 'selfKmsManagedEnc', {
      bucketName: 'bgc-source-selflogging-kmsmanaged-encryption',
      removalPolicy: cdk.RemovalPolicy.DESTROY,
      autoDeleteObjects: true,
      serverAccessLogsPrefix: 'logs',
      encryption: BucketEncryption.KMS_MANAGED
    });
```

### CDK CLI Version

2.57.0

### Node.js Version

v14.21.1

### OS

macOS Monterey 12.7.1

### Language

Typescript

**Comment by ibliskavka** [comment]
@biffgaut, this came as a surprise to me too. We have been using access logging buckets with KMS encryption, but online docs state that it is not.

[Source](https://repost.aws/knowledge-center/s3-server-access-log-not-delivered):

- If default encryption is turned on for the target bucket, AES256 (SSE-S3) must be selected

- If you use [default encryption](https://docs.aws.amazon.com/AmazonS3/latest/dev/bucket-encryption.html) on the target bucket, then confirm that AES-256 (SSE-S3) is selected as the encryption key. Encryption using AWS-KMS (SSE-KMS) is not supported. For instructions on how to configure default encryption using the Amazon S3 console, see [Turning on Amazon S3 default bucket encryption](https://docs.aws.amazon.com/AmazonS3/latest/user-guide/default-bucket-encryption.html).

**Comment by jeffgardnerdev** [comment]
@biffgaut I am getting this error after upgrading an existing app but can confirm that the configuration is working properly--access logs are being sent to the KMS encrypted log target bucket and I am able to download and view them.

My log target bucket has the `encryptionKey` and `bucketKeyEnabled: true`  props passed in.

I'll note that logs were not getting delivered initially but it started working when I gave `logging.s3.amazonaws.com` the proper permissions in the KMS key's key policy.

I know that the documentation indicates that only SSE-S3 is supported, but it doesn't seem to be the case.

**Comment by zdf1230** [comment]
I agreed with @jeffgardnerdev. I am using KMS encryption with  `logging.s3.amazonaws.com` permission attached to the key of course. It works fine on my side - log is generating. So, I don't think we should have these checks which are breaking changes.

**Comment by maherrj** [comment]
I agree with the above. We are also using KMS encryption with our S3 logging destination bucket, provisioned by CDK and it works. 

This CDK check is then breaking our code so we need to revert to SSE. 
The [AWS documentation](https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucket-encryption.html) is then wrong as logging does work when using KMS encryption with S3 logging destination bucket. 

Would be good to get clarify here from AWS.

I'll raise this with our TAM also.

Cheers,
Rich
