### ISSUE TITLE
(aws-lambda): lambda does not set environment variable AWS_CODEGURU_PROFILER_GROUP_NAME when creating Amazon CodeGuru Profiler profiling group

### ISSUE THREAD

**Issue by tfcerda** [aws/aws-cdk#23511]
### Describe the bug

When setting `{ profiling: true }`, the CDK creates a Profiling Group with an autogenerated name. This name is never set to `AWS_CODEGURU_PROFILER_GROUP_NAME` environment variable as [stated in the official docs](https://docs.aws.amazon.com/codeguru/latest/profiler-ug/lambda-simple.html). This causes the Lambda to create _another_ profiling group with a default name `aws-lambda-<LAMBDA_FUNCTION_NAME>`. Therefore, the Lambda runs into permissions issues when submitting profiles, as the CDK does not create permissions to submit to `aws-lambda-<LAMBDA_FUNCTION_NAME>`.

### Expected Behavior

When setting `{ profiling: true }`, Lambda submits profiles to Profiling Group created by CDK.

### Current Behavior

When setting `{ profiling: true }`, Lambda fails with permissions issues. Example errors:
```
INFO: Could not find a profiling group name from environment variable AWS_CODEGURU_PROFILER_GROUP_NAME. Using default profiling group name aws-lambda-<LAMBDA_FUNCTION_NAME>

codegurushadow.software.amazon.awssdk.services.codeguruprofiler.model.CodeGuruProfilerException: User: <USER_ARN> is not authorized to perform: codeguru-profiler:ConfigureAgent on resource: arn:aws:codeguru-profiler:<REGION>:<AWS_ACCOUNT_ID>:profilingGroup/aws-lambda-<LAMBA_FUNCTION_NAME> (Service: CodeGuruProfiler, Status Code: 403, Request ID: <REQUEST_ID>)
```

### Reproduction Steps

Create Lambda function with Java runtime and `{ profiling: true }`

### Possible Solution

Set `AWS_CODEGURU_PROFILER_GROUP_NAME: props.profilingGroup.profilingGroupName` in https://github.com/aws/aws-cdk/blob/fc70535fe699e72332d5ddb4543308e76a89594a/packages/%40aws-cdk/aws-lambda/lib/function.ts#L725

and `AWS_CODEGURU_PROFILER_GROUP_NAME: profilingGroup.profilingGroupName` in https://github.com/aws/aws-cdk/blob/fc70535fe699e72332d5ddb4543308e76a89594a/packages/%40aws-cdk/aws-lambda/lib/function.ts#L739

### CDK CLI Version

1.186.0 and 2.58.0

### Node.js Version

18.11.0

### OS

MacOS

### Language

Typescript

**Comment by peterwoodworth** [comment]
It looks like this can apply to [Python](https://docs.aws.amazon.com/codeguru/latest/profiler-ug/python-lambda-command-line.html) too

Until this gets fixed you should be able to work around this by adding an environment variable for this to your function with an [escape hatch](https://docs.aws.amazon.com/cdk/v2/guide/cfn_layer.html)

I am marking this issue as p2, which means that we are unable to work on this immediately.

We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://cdk.dev) to solicit support for reprioritization.

Check out our [contributing guide](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) if you're interested in contributing yourself - there's a low chance the team will be able to address this soon but we can try to review a PR 🙂

**Comment by dastbe** [comment]
Decompling the codeguru profiler agent, this seems like a bug in the codeguru agent itself.

If you instrument using the request handler method, it uses the internal `LambdaProfilerUtils` class which looks at `AWS_CODEGURU_PROFILER_GROUP_ARN`, whereas with the corretto setup it uses `LambdaJvmArgumentParser` which doesn't look at that variable. Really the implementation should be consistent within java and the python profiler.

Beneficially, the implementations as currently written let you set both, so that would be a straightforward fix.

**Comment by tfcerda** [comment]
Thank you for all your comments so fast!

I have created PR #23542 fixing this issue
