### ISSUE TITLE
(aws-events): RuleTargetInput.fromObject function in string template issue

### ISSUE THREAD

**Issue by ellisium** [aws/aws-cdk#23522]
### Describe the bug

function is not executed inside string template

`Create Record API faulty activty, at least one check message reached the DLQ: <https://eu-west-1.console.aws.amazon.com/sqs/v2/home?region=eu-west-1#/queues/${encodeURIComponent(DLQ.queueURL)}|${DLQ.queueName}>`

return value  KO: `https://eu-west-1.console.aws.amazon.com/sqs/v2/home?region=eu-west-1#/queues/%24%7BToken%5BTOKEN.3905%5D%7D`

expected value : `https://eu-west-1.console.aws.amazon.com/sqs/v2/home?region=eu-west-1#/queues/https%3A%2F%2Fsqs.eu-west-1.amazonaws.com%2F175699276530%2Fseyna-platform-fix-aml-sqs-alarm--AMLDLQingestfixamlsqsalarmstackch-zDAwCfOQulj8`

`Create Record API faulty activty, at least one check message reached the DLQ: <https://eu-west-1.console.aws.amazon.com/sqs/v2/home?region=eu-west-1#/queues/${DLQ.queueURL|${params.queueUrl}}>`

return value  OK : `https://eu-west-1.console.aws.amazon.com/sqs/v2/home?region=eu-west-1#/queues/https://sqs.eu-west-1.amazonaws.com/175699276530/seyna-platform-fix-aml-sqs-alarm--AMLDLQingestfixamlsqsalarmstackch-zDAwCfOQulj8)` however the link is KO due to missing encodeURIComponent

### Expected Behavior

Function return the right value executing the params once the serializer has been executed itself.

### Current Behavior

Function in string template is not executed or exectued before replace serializer?

### Reproduction Steps

`RuleTargetInput.fromObject({encodedURL: `Create Record API faulty activty, at least one check message reached the DLQ: <https://eu-west-1.console.aws.amazon.com/sqs/v2/home?region=eu-west-1#/queues/${params.queueUrl}|${encodeURIComponent(DLQ.queueURL)}>`});`

### CDK CLI Version

2.58.1

### Node.js Version

16

### OS

lambda

### Language

Typescript

**Comment by pahud** [comment]
Hi @ellisium 

Can you provide a full minimal CDK app that I can reproduce in my environment?

**Comment by ellisium** [comment]
Hi @pahud, I will manage to provide it  begining of next week

thx much for support

**Comment by ellisium** [comment]
Reproduction case to provide ASAP
