### ISSUE TITLE
AmazonLinuxImage: MachineImage.latestAmazonLinux() should not default to using AMAZON_LINUX for the generation

### ISSUE THREAD

**Issue by rpivo** [aws/aws-cdk#23523]
### Describe the bug

I am attempting to create a LaunchTemplate like this:

```ts
    new LaunchTemplate(this, 'TestLaunchTemplate', {
      instanceType: InstanceType.of(InstanceClass.T4G, InstanceSize.NANO),
      launchTemplateName: 'TestLaunchTemplate',
      machineImage: MachineImage.latestAmazonLinux({
        cpuType: AmazonLinuxCpuType.ARM_64
      })
    });
```

When I do this, I receive an error from CDK:

```
Unable to fetch parameters [/aws/service/ami-amazon-linux-latest/amzn-ami-hvm-arm64-gp2] from parameter store for this account.
```

It looks like this is because the parameter doesn't exist, and it should have instead looked for `amzn2-ami-hvm-arm64-gp2`, which *does* exist.

### Expected Behavior

It looks like the ssm parameter defaults to using `AMAZON_LINUX` as the generation: https://github.com/aws/aws-cdk/blob/74aba8fef6bd22e3a3ffc74ebbf41615cfdd3ba1/packages/%40aws-cdk/aws-ec2/lib/machine-image.ts#L398

This doesn't make much sense when using `MachineImage.latestAmazonLinux()`.

At the very least, maybe the logic here needs to be expanded for more cases.

### Current Behavior

When I do this, I receive an error from CDK:

```
Unable to fetch parameters [/aws/service/ami-amazon-linux-latest/amzn-ami-hvm-arm64-gp2] from parameter store for this account.
```

It looks like this is because the parameter doesn't exist, and it should have instead looked for `amzn2-ami-hvm-arm64-gp2`, which *does* exist.

### Reproduction Steps

Attempt to create a new `LaunchTemplate` with these parameters:

```ts
      instanceType: InstanceType.of(InstanceClass.T4G, InstanceSize.NANO),
      launchTemplateName: 'TestMlLaunchTemplate',
      machineImage: MachineImage.latestAmazonLinux({
        cpuType: AmazonLinuxCpuType.ARM_64
      })
```

### Possible Solution

Use newer generation when calling `latestAmazonLinux`, or expand generation logic.

### CDK CLI Version

aws-cdk@2.58.0

### Node.js Version

v19.1.0

### OS

Mac

### Language

Typescript

### Language Version

^4.9.4

**Comment by rpivo** [comment]
Another smaller solution here could be to enforce the `generation` option for `AmazonLinuxImageProps` -- but I'd expect not to have to set that when using `latestAmazonLinux()`.

As a workaround, I can also use `MachineImage.fromSsmParameter()` and specify the parameter for the AMI that way.

**Comment by pahud** [comment]
I believe the `MachineImage.latestAmazonLinux()` might be first implemented when Amazon Linux 2 was not announced yet and that's the reason we need to indicate the `generation` prop if we opt in Amazon linux 2(or maybe ver 3 in the future).

**Comment by tmokmss** [comment]
Related discussion here: https://github.com/aws/aws-cdk/issues/21011#issuecomment-1372170948

**Comment by taylorb-syd** [comment]
Thank you. I think I will close this out in favour of #21011. I attempted to search for the issue before reporting but #21011 did not appear in my results.
