### ISSUE TITLE
awsstepfunctions|awsstepfunctionstasks: Allow custom state names

### ISSUE THREAD

**Issue by jerrydevin96** [aws/aws-cdk#23532]
### Describe the feature

We use the go bindings for AWS CDK (https://github.com/aws/aws-cdk-go) to deploy state machines. The functions provided to create a state machine in the library do not have the option to add a custom state name, which is possible while creating a state machine from the console. instead while using the CDK, the state name is auto-generated from other inputs provided while defining the state machine. This auto-generated state name is too long and confusing.

### Use Case

Too long state names are confusing. Having the possibility to add a custom user-defined state name would be really good.

### Proposed Solution

Add additional struct field to define custom state names.

### Other Information

I am raising this issue here, as the Go Bindings (https://github.com/aws/aws-cdk-go) do not have issues enabled.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.49.1

### Environment details (OS name and version, etc.)

macOS v12.5.1

**Comment by jerrydevin96** [comment]
Will this have to be implemented in the current repository (https://github.com/aws/aws-cdk) or should it be implemented in the go bindings repository?

**Comment by Jacco** [comment]
I do not understand the issue raised here. Looking at the code it seems to me that everywhere the `logical id` of the `State` construct is used as the name of the `State` in the rendered JSON.

**Comment by bun913** [comment]
Hello!
May I challenge this issue?

**Comment by bun913** [comment]
I was going to start working on this Issue, but as per the following comment, I reconsidered whether it is a problem on the naming convention side.

https://github.com/aws/aws-cdk/issues/23532#issuecomment-1374506128

I was going to start working on this issue, but then I reconsidered and wondered if it would be possible to write the logic on the naming side so that it would not be too long.
