### ISSUE TITLE
cdk: Can't install 2.59.0 with NPM

### ISSUE THREAD

**Issue by oceanofmaya** [aws/aws-cdk#23546]
### Describe the bug

When `npm i cdk` or `npm i cdk@latest` is called I encounter an error (seeing this since 2.59.0 was published on 01/03/2023 12:01 PM EST)

I checked NPM to see if anyone else had downloaded it; stats reported here https://www.npmjs.com/package/cdk?activeTab=versions indicates that as of this moment 01/03/2023 1:49 PM EST there are zero downloads for this version.

### Expected Behavior

Successful install

### Current Behavior

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for aws-cdk@2.59.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'cdk'
npm ERR! notarget
```

### Reproduction Steps

`npm i cdk@latest` 

### CDK CLI Version

2.59.0

### Node.js Version

14

### OS

Windows

### Language

Typescript

**Comment by peterwoodworth** [comment]
You shouldn't still be encountering this, works for me. May have been due to this just being published?

**Comment by oceanofmaya** [comment]
I just tried it and it works for me as well. I guess it might be because it was too close to it being published. @peterwoodworth thanks.
