### ISSUE TITLE
aws-lambda-event-sources: make event sources dependable

### ISSUE THREAD

**Issue by toxygene** [aws/aws-cdk#23550]
### Describe the feature

I would like to see the `aws_lambda_event_sources` be dependable.

### Use Case

I am trying to create a `aws-iam.ManagedPolicy` for an `aws-lambda-event-sources.SqsEventSource` using a `aws-lambda.Function` that was created with a role that is an `aws-iam.ImmutableRole`.

```python
self.role = aws_iam.Role(
    scope=self,
    id="role",
    assumed_by=aws_iam.ServicePrincipal("lambda.amazonaws.com")
)

self.fn = aws_lambda.Function(
    scope=self,
    id="function",
    code=aws_lambda.Code.from_inline(" "),
    handler="test",
    role=self.role.without_policy_updates(),  # Prevents various inline and AWS managed policies from being attached to the role
    runtime=aws_lambda.Runtime.PYTHON_3_9,
)

# Lambda function needed policies would be added to the role here

self.queue = aws_sqs.Queue(
    scope=self,
    id="queue",
    removal_policy=aws_cdk.RemovalPolicy.DESTROY
)

self.managed_policy = aws_iam.ManagedPolicy(
    scope=self,
    id="managed-policy",
    statements=[
        aws_iam.PolicyStatement(
            actions=[
                "sqs:ReceiveMessage",
                "sqs:ChangeMessageVisibility",
                "sqs:GetQueueUrl",
                "sqs:DeleteMessage",
                "sqs:GetQueueAttributes"
            ],
            resources=[self.queue.queue_arn]
        )
    ],
    roles=[self.role]
)

event_source = aws_lambda_event_sources.SqsEventSource(self.queue)

self.fn.add_event_source(event_source)
```

Unfortunately, this fails with the following error: `Resource handler returned message: "Invalid request provided: The provided execution role does not have permissions to call ReceiveMessage on SQS`

It appears that the `SqsEventSource` is being created before the `ManagedPolicy` is created, so CloudFormation is rejecting the template.

There does not appear to be a way to manually add a dependency on any of the `aws-lambda-event-sources` to fix an issue like this.

### Proposed Solution

I've looked through the source code and it does not appear that it'd be possible to add this functionality to the `aws-lambda-event-sources` due to the way they are designed.

It may be possible, however, to modify the `aws-lambda-event-sources.IEventSource.bind` to return an `aws-lambda.EventSourceMapping`, modify each `aws-lambda-event-sources` class to return the `aws-lambda.EventSourceMapping` they create, and modify `aws-lambda.Function.addEventSource` to return the value of `source.bind(this);`. Doing this would allow me modify the last two lines of my code to this:

```python
event_source_mapping = self.fn.add_event_source(aws_lambda_event_sources.SqsEventSource(self.queue))
self.event_source_mapping.node.add_depencency(self.managed_policy)
```

Alternatively, something could be added to the documentation about how `aws-lambda-event-sources` cannot be used with `aws-lambda.Function`s that have an `aws-iam.ImmutableRole`.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.57.0

### Environment details (OS name and version, etc.)

Python 3.9.13

**Comment by pahud** [comment]
Hi @toxygene 

As the lambda execution role is immutable role now, it is expected to have such error. What is your expected result from the given sample above?

**Comment by toxygene** [comment]
Hello @pahud

I would expect the managed policy that grants the consume messages permissions to be created before the event source mapping, *or* I be able to add a dependency manually to ensure the creation order is correct. Or the documentation state that you cannot use any of the `aws_lambda_event_sources` when you use an immutable role. 😄

**Comment by pahud** [comment]
@toxygene 

Looking at this:

https://github.com/aws/aws-cdk/blob/a15622188fdaf3cf17ee55ca193c12c90550d2f8/packages/%40aws-cdk/aws-iam/lib/role.ts#L600-L612

When you `without_policy_updates()`, CDK will not mutate the role and as the document described "If you do, you are responsible for adding the correct statements to the Role's policies yourself. "

In your case I think you will need to create the `Role` with all required policies yourself before you append the `without_policy_update()` to the `Role`. And I agree this is annoying and we probably should improve better experience here.

**Comment by toxygene** [comment]
I'm not sure why this didn't dawn on my several months ago, but simply adding a dependency between the function and the managed policy (`self.fn.node.add_dependency(this.managed_policy)`) is what I should have been doing.
