### ISSUE TITLE
(ecs-patterns): Divergent Options Between Pattern Classes

### ISSUE THREAD

**Issue by shellscape** [aws/aws-cdk#23561]
### Describe the bug

There is a distinct and baffling divergence between constructor options in pattern classes in the `ecs-patterns` module.

To demonstrate this, please look at the options for `ApplicationLoadBalancedFargateService` and  `QueueProcessingFargateService`. 

In `ApplicationLoadBalancedFargateService` we have:
- `desiredCount`
- `healthCheckGracePeriod`
- `taskImageOptions`

And a health check must be configured separately using the `taskGroup` property of the resulting class object.

In `QueueProcessingFargateService` we have:
- `healthCheck`
- `image` - which by the way, is curiously out of alphbetical order in the documentation https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ecs_patterns.QueueProcessingFargateService.html
- `desiredTaskCount` is now missing from the props as a property, and typedefs, which diverged from `desiredCount` above, even though it's mentioned in two places in the docs https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ecs_patterns.QueueProcessingFargateService.html

In this class, health check is fully configurable via options, without having to jump through hoops. While `image` exists here and several properties from `ApplicationLoadBalancedTaskImageOptions` are present, the service isn't fully configurable with all of the options provided in `ApplicationLoadBalancedTaskImageOptions`.

### Expected Behavior

I would have expected there to be some continuity and consistency to these options, naming, location, and function.

### Current Behavior

It's a mess between the two classes - indicative of different people working on the classes and lack of peer review by those also working in the module.

### Reproduction Steps

Read the documentation. (Seriously, that's where the issue is visible)

### Possible Solution

Consolidate and adhere to a contract for `ecs-patterns` options.

### CDK CLI Version

2.54.0

### Framework Version

2.59.0

### Node.js Version

18

### OS

MacOS

### Language

Typescript

### Language Version

^4.8.4

**Comment by pahud** [comment]
Yes I agree we should improve the continuity and consistency to these options, naming, location, and function. But as the module is stable now, it's not possible to introduce breaking changes for that. Thank you for your feedback. I am closing this issue as I don't think we are able to introduce breaking changes for that but it doesn't mean we don't agree with you. Thank you again.

**Comment by shellscape** [comment]
@pahud That's a premature close my friend. we have patterns available to us that can synchronize these discrepancies without introducing breaking changes. namely the use of deprecated properties. deprecated properties are quite common in CDK.
