### ISSUE TITLE
(acm): DomainName length check fails with too long prop due to string encoded tokens.

### ISSUE THREAD

**Issue by rv2673** [aws/aws-cdk#23565]
### Describe the bug

When creating Certificate where the domainName property contains domain with tokens, the length check fails because the string encoded token causes the length to exceed the maximum even if token resolved to something shorter. 

### Expected Behavior

Check is only done when string contains no unresolved tokens.

Offending line:
https://github.com/aws/aws-cdk/blob/3d8df57df9aced8c7ff2df35f379570feea73f6a/packages/%40aws-cdk/aws-certificatemanager/lib/certificate.ts#L245

### Current Behavior

Synthesis failed because length is exceeded due to string encoded token.

### Reproduction Steps

Create cdk stack 
Add Certificate where the base domain is 54 characters. 
Add domainName string where subdomain comes from Token (For example CfnParameter)
Try to synthesize stack.

### Possible Solution

Perform check only when tokens are unresolved. Like cdk documentation suggests.

https://github.com/aws/aws-cdk/blob/3d8df57df9aced8c7ff2df35f379570feea73f6a/packages/%40aws-cdk/aws-certificatemanager/lib/certificate.ts#L245

Example from docs:
```typescript
if (!Token.isUnresolved(name) && name.length > 10) {
  throw new Error(`Maximum length for name is 10 characters`);
}
```
In this context:
```typescript
if (!Token.isUnresolved(props.domainName) && props.domainName.length > 64) {
  throw new Error('Domain name must be 64 characters or less');
}
```

### CDK CLI Version

2.58.1

### Node.js Version

16.19.0

### OS

Ubuntu

### Language

Typescript

**Comment by peterwoodworth** [comment]
Thanks for the quick PR! much appreciated 🙂
