### ISSUE TITLE
(timestream): RententionProperties key should be PascalCase

### ISSUE THREAD

**Issue by Wurstnase** [aws/aws-cdk#23570]
### Describe the bug

In the cloudformation documentation all property keys are PascalCase. With 2.56.0 the RetentionProperties for timestream changed to camelCase:

```diff
         "RetentionProperties": {
-          "MagneticStoreRetentionPeriodInDays": "1",
-          "MemoryStoreRetentionPeriodInHours": "1"
+          "magneticStoreRetentionPeriodInDays": "1",
+          "memoryStoreRetentionPeriodInHours": "1"
         },
```

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-timestream-table.html

### Expected Behavior

PascalCase for properties

### Current Behavior

camelCase for properties

### Reproduction Steps

```python
class TimestreamStack(Stack):
    def __init__(
        self,
        scope: Construct,
        id_: str,
        *,
    ):
        super().__init__(scope, id_)

        cfn_database = timestream.CfnDatabase(
            self,
            "Database",
            database_name="database",
        )

        timestream.CfnTable(
            self,
            "Table",
            database_name=cfn_database.ref,
            table_name="input",
            retention_properties=timestream.CfnTable.RetentionPropertiesProperty(
                magnetic_store_retention_period_in_days="1",
                memory_store_retention_period_in_hours="1",
            ),
        )
```

### CDK CLI Version

-

### Framework Version

`>= 2.56.0`

### Node.js Version

-

### OS

-

### Language

Python

**Comment by peterwoodworth** [comment]
Thanks for reporting this, we actually reverted this intentionally because the behavior you see in `2.55.0` was actually a version of the previous behavior. See this issue for more info https://github.com/aws/aws-cdk/issues/23404. And this issue is tracking a way to prevent this from occurring again https://github.com/aws/aws-cdk/issues/21767

From here forward, please fill in these properties as if they are `any` type (because they are!)

**Comment by Wurstnase** [comment]
Why does the behavior of the dataclass change as well?

This is the example from the official documentation:

```python
# The code below shows an example of how to instantiate this type.
# The values are placeholders you should change.
import aws_cdk.aws_timestream as timestream

cfn_table = timestream.CfnTable(self, "MyCfnTable",
    database_name="databaseName",

    # the properties below are optional
    magnetic_store_write_properties=timestream.CfnTable.MagneticStoreWritePropertiesProperty(
        enable_magnetic_store_writes=False,

        # the properties below are optional
        magnetic_store_rejected_data_location=timestream.CfnTable.MagneticStoreRejectedDataLocationProperty(
            s3_configuration=timestream.CfnTable.S3ConfigurationProperty(
                bucket_name="bucketName",
                encryption_option="encryptionOption",

                # the properties below are optional
                kms_key_id="kmsKeyId",
                object_key_prefix="objectKeyPrefix"
            )
        )
    ),
    retention_properties=timestream.CfnTable.RetentionPropertiesProperty(
        magnetic_store_retention_period_in_days="magneticStoreRetentionPeriodInDays",
        memory_store_retention_period_in_hours="memoryStoreRetentionPeriodInHours"
    ),
    table_name="tableName",
    tags=[CfnTag(
        key="key",
        value="value"
    )]
)
```

**Comment by peterwoodworth** [comment]
You won't want to use the dataclass - the example up top shows that the properties in the CfnTable construct should be specified as any - not as a dataclass

**Comment by Wurstnase** [comment]
`Any` in this context is `dict[str, str]`?

```python
p1: Any = {}  # ok
p2: Any = timestream.CfnTable.RetentionPropertiesProperty()  # ok

p3: dict = {}  # ok
p3: dict = timestream.CfnTable.RetentionPropertiesProperty  # error
```

so somewhere seems to be an error?

**Comment by peterwoodworth** [comment]
Defining it like this works for me on latest version:

```
        timestream.CfnTable(
            self,
            "Table",
            database_name="name",
            table_name="input",
            magnetic_store_write_properties=dict(
                EnableMagneticStoreWrites=True
            ),
            retention_properties=dict(
                MagneticStoreRetentionPeriodInDays="1",
                MemoryStoreRetentionPeriodInHours="1",
            ),
        )
```

**Comment by Wurstnase** [comment]
Yes, this would work for me also.

However, it is not an error to define it with the given dataclass. I like cdk because it helps me to define everything with the right typings and it is harder to missuse. But not in this case.

 e.g. with cdk v1 (maybe not compatible in this case) has a complete example with the dataclass in the properties. Why is there this dataclass, and it will produce something which will produce a so similar cloudformation template in the end?

**Comment by Wurstnase** [comment]
I understand now the issue. With the new cloudformation spec came the newly generated dataclasses. With the patch they became `camelCase`.
