### ISSUE TITLE
(s3): CDK sets ACL on all buckets

### ISSUE THREAD

**Issue by khellan** [aws/aws-cdk#23588]
### Describe the bug

We don't use ACLs on buckets and we have disabled them on most if not all buckets. With v2.59.0, CDK attempts to set ACLs on all the buckets, causing the deployment to fail. Our deployments system does not have permissions for s3:PutBucketAcl and they shouldn't need that either since we are not using ACLs.

This is the cdk diff output:
```
[~] AWS::S3::Bucket <bucket_name <bucket_id>
 └─ [+] AccessControl
     └─ LogDeliveryWrite 
```

### Expected Behavior

No changes to ACLs as prior versions of CDK

### Current Behavior

Deployment fails with
"The bucket does not allow ACLs" or
"s3:PutBucketAcl Access Denied"
 

### Reproduction Steps

Create an S3 bucket with a CDK version prior to 2.59.0
```
s3.Bucket(
    self,
    'test_bucket',
    bucket_name=f'fail-{self.region}-{self.account}',
    object_ownership=s3.ObjectOwnership.BUCKET_OWNER_ENFORCED,
    block_public_access=s3.BlockPublicAccess.BLOCK_ALL,
    enforce_ssl=True,
    versioned=False,
    encryption=s3.BucketEncryption.S3_MANAGED,
    server_access_logs_bucket=s3_access_logs_bucket,
    server_access_logs_prefix='fail/'
)
```

The upgrade to CDK 2.59.0
and diff or deploy the stack

### Possible Solution

Revert this change since it does the opposite of what [23386](https://github.com/aws/aws-cdk/pull/23386) claims it will do. 

### CDK CLI Version

2.59.0

### Node.js Version

18.12.1

### OS

macOS

### Language

Python

### Language Version

Python 3.9

**Comment by kylelaker** [comment]
I believe this relates to https://github.com/aws/aws-cdk/issues/23547 and may be fixed by https://github.com/aws/aws-cdk/pull/23552.

@peterwoodworth sorry for the ping but since you triaged the earlier issue, this may be interesting to you.

**Comment by khellan** [comment]
The bucket is not created in the same stack. 

In this stack, it is imported like this:
`s3_access_logs_bucket = s3.Bucket.from_bucket_name(...)`

Looks like the test in 23552 should verify that this problem is solved.
