### ISSUE TITLE
LoadBalancedFargateService: Add ability to specify Load Balancer and Listener name

### ISSUE THREAD

**Issue by EduardTheThird** [aws/aws-cdk#2358]
We are using LoadBalancedFargateService to generate some Fargate services.

Currently, the load balancer and listener name is read-only and cannot be changed.
We need to set the load balancer name to conform with company policies.

Having the ability to specify or change the names of both would be greatly appreciated! 🐱 
Is there a workaround available for this?

Thanks!

**Comment by markusl** [comment]
Please check this if it helps: https://github.com/markusl/cdk-fargate-docker-starter/blob/master/lib/cdk-fargate-starter-docker-stack.ts

**Comment by pkandasamy91** [comment]
@EduardTheThird, sorry for the delayed response, The Application/Network LoadBalancedFargateService now support the ability to pass in your own loadbalancers. This should help to resolve your issue.

**Comment by pkandasamy91** [comment]
Resolved as part of: https://github.com/aws/aws-cdk/pull/4213
