### ISSUE TITLE
pipelines: not possible to enable key rotation

### ISSUE THREAD

**Issue by tkglaser** [aws/aws-cdk#23595]
### Describe the bug

When creating a _modern_ pipeline (`pipelines.CodePipeline`), it should be possible to enable key rotation of the internal `cp.Pipeline`).

### Expected Behavior

There should be a property `enableKeyRotation` on a `pipelines.CodePipeline` construct.

### Current Behavior

It is not currently possible to enable key rotation on a `pipelines.CodePipeline` construct.

### Reproduction Steps

Create a new `pipelines.CodePipeline` and observe that the created KMS key does not have key rotation enabled.

### Possible Solution

Wire the `enableKeyRotation` property from `cp.Pipeline` through to `pipelines.CodePipeline`.

### CDK CLI Version

2.59.0

### Framework Version

2.59.0

### Node.js Version

16.18.1

### OS

Linux

### Language

Typescript

### Language Version

4.9.3

**Comment by peterwoodworth** [comment]
You're right, the option to generate the underlying `CodePipeline.Pipeline` with key rotation enabled isn't present.

We have an option to [supply your own `CodePipeline.Pipeline`](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.pipelines.CodePipeline.html#codepipeline) on creation of the `pipelines.CodePipeline` construct. This should allow you to set any props you need until we officially support this

**Comment by tkglaser** [comment]
Thanks we've considered that workaround and opted for manually activating the key rotation in the console for the interim which is of course not great.

I'm happy to contribute the PR by the way.
