### ISSUE TITLE
LoadBalancedFargateService: Add ability to specify Health Check path

### ISSUE THREAD

**Issue by EduardTheThird** [aws/aws-cdk#2359]
We are using LoadBalancedFargateService to generate some Fargate services.

Currently, the health check path defaults to root. "/"
We need to set the health check path for each Fargate service.

Having the ability to specify or change the health check path would be greatly be appreciated! 
Is there a workaround available for this?

Thanks! 🐈

**Comment by markusl** [comment]
You can have a look at my template for creating a basic Fargate cluster: https://github.com/markusl/cdk-fargate-docker-starter/blob/master/lib/cdk-fargate-starter-docker-stack.ts

You can easily specify custom health check:
`      .addTargets(..., {
        // ...
        healthCheck: {
          path: '/health-check',
        },
      });`

**Comment by hoegertn** [comment]
But you are creating the resources manually. The request is to add health checks to the LoadBalancedFargateService L2 construct. This would really be great.

**Comment by NGL321** [comment]
Closing due to old data (see comments in #2704).

If closing was incorrect, feel free to reopen.

😸

**Comment by danilofuchs** [comment]
I could not find any solution other than creating all resources manually, defeating the purpose of `LoadBalancedFargateService`. #2704 was closed, but the solution isn't clear

**Comment by jwmonroe-outschool** [comment]
I found I was able to access the health check settings via:

```
const server = new ApplicationLoadBalancedFargateService(...)
server.targetGroup.configureHealthCheck({
      path: "/health",
      interval: Duration.seconds(120),
      unhealthyThresholdCount: 5,
      ... etc
    }); 
```
