### ISSUE TITLE
(aws-cdk-lib.aws_apprunner): App Runner Service external configuration support

### ISSUE THREAD

**Issue by clouddev-code** [aws/aws-cdk#23603]
### Describe the feature

AWS App Runner now supports retrieving secrets and configuration from AWS Secrets Manager and AWS Systems Manager

https://aws.amazon.com/about-aws/whats-new/2023/01/aws-app-runner-secrets-configuration-aws-secrets-systems-manager/

Support for properties such as RuntimeEnvironmentSecrets will be needed
https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-apprunner.Service.html

To reference the secret manager or ssm paramter store  it's needed:

Secret
https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-secretsmanager.Secret.html
StringParameter
https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-ssm.StringParameter.html

### Use Case

App Runner Service including external environment such as secret manager cannot be implemented with cdk at present.

### Other Information

boto3 already supports the RuntimeEnvironmentVariables property

https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/apprunner.html#AppRunner.Client.create_service

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.54.0

### Environment details (OS name and version, etc.)

Linux

**Comment by peterwoodworth** [comment]
Our L2 apprunner constructs are currently in alpha, or experimental state. If you're using the Service construct, you can use [escape hatches](https://docs.aws.amazon.com/cdk/v2/guide/cfn_layer.html) to set the properties you want to set until our higher level abstractions figure out a nice way to specify this information in the future 🙂 

Alternatively, you can drop to the l1 altogether to be able to specify this without making any overrides. [We already have this available on the L1](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_apprunner.CfnService.ImageConfigurationProperty.html)

**Comment by NicholasFields** [comment]
In case anyone else is eager to play with this in CDK, I was able to escape hatch it via
`'Properties.SourceConfiguration.ImageRepository.ImageConfiguration.RuntimeEnvironmentSecrets'`

![image](https://user-images.githubusercontent.com/68744844/211953134-333d7885-5e05-4ef6-b505-24fa9ac8c376.png)

AWS Console => your `App Runner` service => `Configuration` => `Service settings` => `Environment variables`

![image](https://user-images.githubusercontent.com/68744844/211952598-245bc4ab-f417-4462-8958-376218a5a707.png)

**Comment by peterwoodworth** [comment]
This is supported in both L1s and L2s https://docs.aws.amazon.com/cdk/api/v2/docs/aws-apprunner-alpha-readme.html#secrets-manager
