### ISSUE TITLE
aws_rum: AppMonitorConfigurationProperty property telemetries does not specify how to enable custom events

### ISSUE THREAD

**Issue by bunggum** [aws/aws-cdk#23609]
### Describe the issue

The RUM app monitor has the option to enable custom events. I cannot find in the documentation how to do this. I expected this to be in the `telemetries` property but it is not specified.

Thanks.

### Links

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_rum.CfnAppMonitor.AppMonitorConfigurationProperty.html#telemetries

**Comment by bunggum** [comment]
There doesn't seem to be this option in CloudFormation so I'm assuming it will affect the CDK and this option simply doesn't exist?

https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1450

**Comment by peterwoodworth** [comment]
Yes, we'll need CloudFormation support, then CDK will start supporting this soon after. Please refer to the linked issue in the roadmap, thanks!

**Comment by theo-rogers** [comment]
Now that the CFN updates are shipped, is there an eta on when CDK will get this support?

**Comment by bunggum** [comment]
Is there any update?

**Comment by haydster7** [comment]
Looks like this has been added
[CfnAppMonitorProps](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_rum.CfnAppMonitorProps.html)
[CustomEventsProperty](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_rum.CfnAppMonitor.CustomEventsProperty.html)

Have not tested it yet, but can probably be closed

**Comment by peterwoodworth** [comment]
Thanks @haydster7
