### ISSUE TITLE
(Cloudfront): Cannot remove headers

### ISSUE THREAD

**Issue by re-thc** [aws/aws-cdk#23606]
### Describe the bug

No option to remove headers when specifying a ResponseHeadersPolicy

### Expected Behavior

Able to both add or remove headers

### Current Behavior

Not supported

### Reproduction Steps

n/a

### Additional Information/Context

https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/modifying-response-headers.html can be done manually via the console.

### CDK CLI Version

2.59.0

### Node.js Version

19

### OS

Mac

### Language

Typescript

**Comment by pahud** [comment]
I think we are allowed to define `customHeadersBehavior` and `removeHeaders`.

https://github.com/aws/aws-cdk/blob/ce18037b2ba2b872dd1ed21fda71fd2ee4701353/packages/%40aws-cdk/aws-cloudfront/lib/response-headers-policy.ts#L122-L124

Is this something your expect?

**Comment by re-thc** [comment]
@pahud it's been a while but my memory is that this issue was created before `removeHeaders` was implemented so we should be good now.

**Comment by pahud** [comment]
@re-thc  OK I am closing it for now. Feel free to re-open when necessary.
