### ISSUE TITLE
(core): (creation policy missing for AWS::AppStream::Fleet)

### ISSUE THREAD

**Issue by hans-d** [aws/aws-cdk#23604]
### Describe the bug

```
{
    "CreationPolicy": {
        "StartFleet": {
            "Type": "Boolean"
        }
    }
}
```
is cannot be set

### Expected Behavior

CreationPolicy be able to set for an Appstream Resource

### Current Behavior

Not supported

### Reproduction Steps

n/a

### Additional Information/Context

see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-creationpolicy.html

### CDK CLI Version

2.59.0

### Node.js Version

v19

### OS

mac (all)

### Language

Typescript, Python

**Comment by Jacco** [comment]
@rix0rrr I made a PR for this bug.
