### ISSUE TITLE
S3 Bucket Deployment does not support big files (files bigger than 100MB)

### ISSUE THREAD

**Issue by ttais2017** [aws/aws-cdk#23611]
### Describe the bug

This is the CloudWatch Log of the Lambda function responsible for uploading files in s3 (BucketDeployment): 

Command '['/opt/awscli/aws', 's3', 'cp', 's3://cdk-hnb659fds-assets-597414363306-eu-central-1/e8973cd5348c415aa0e3643fe7444531cb87fccf4a158b31d8aa332d1d07425b.zip', '/tmp/tmpw20q0mfe/bd574b2f-9589-478a-808c-02efc15e803c']' died with <Signals.SIGKILL: 9>.
Traceback (most recent call last):
  File "/var/task/index.py", line 117, in handler
    s3_deploy(s3_source_zips, s3_dest, user_metadata, system_metadata, prune, exclude, include, source_markers, extract)
  File "/var/task/index.py", line 162, in s3_deploy
    aws_command("s3", "cp", s3_source_zip, archive)
  File "/var/task/index.py", line 232, in aws_command
    subprocess.check_call([aws] + list(args))
  File "/var/lang/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/opt/awscli/aws', 's3', 'cp', 's3://cdk-hnb659fds-assets-597414363306-eu-central-1/e8973cd5348c415aa0e3643fe7444531cb87fccf4a158b31d8aa332d1d07425b.zip', '/tmp/tmpw20q0mfe/bd574b2f-9589-478a-808c-02efc15e803c']' died with <Signals.SIGKILL: 9>.

The ZIP file has 106 MB.  Trying with other files (64MB, and 80MB) the upload works.   After 100MB the lambda function reports the error.  

[INFO]	2023-01-09T07:39:09.929Z	8848b680-07f9-4ff8-851f-3026587f3382	| response body:
{
    "Status": "FAILED",
    "Reason": "Command '['/opt/awscli/aws', 's3', 'cp', 's3://cdk-hnb659fds-assets-597414363306-eu-central-1/e8973cd5348c415aa0e3643fe7444531cb87fccf4a158b31d8aa332d1d07425b.zip', '/tmp/tmpw20q0mfe/bd574b2f-9589-478a-808c-02efc15e803c']' died with <Signals.SIGKILL: 9>.",
    "PhysicalResourceId": "2023/01/09/[$LATEST]16baf2348f7a4796854d562ba9a08815",
    "StackId": "arn:aws:cloudformation:eu-central-1:597414363306:stack/V1XBBS-V1XBASNestedStackV1XBASNestedStackResource90599E9D-1M6MZJDSQGWFM/fa497ff0-8fef-11ed-a79f-0ab2b079cc42",
    "RequestId": "28c2bf9c-bac9-495e-a193-4b548ec2d599",
    "LogicalResourceId": "V1Xs3dplCustomResource72A7CF62",
    "NoEcho": false,
    "Data": {}
}

### Expected Behavior

ZIP Files are uploaded in s3 (using the BucketDeployment class)

### Current Behavior

The stack deployment is broken

### Reproduction Steps

- Deploy a Stack using CDK and with the BucketDeployment try to upload a directory with big files (bigger than 100MB)

### CDK CLI Version

$ cdk version 2.59.0 (build b24095d)

### Node.js Version

Node.js v14.16.0

### OS

Windows

### Language

Java

**Comment by peterwoodworth** [comment]
Hey, thanks for reporting this issue. We have a feature request open for this currently, please be sure to give it a thumbs up to help us know to prioritize this issue more. Thanks!

**Comment by ttais2017** [comment]
> Hey, thanks for reporting this issue. We have a [feature request open](https://github.com/aws/aws-cdk/issues/7950) for this currently, please be sure to give it a thumbs up to help us know to prioritize this issue more. Thanks!

Hi Peter, 
thanks for your quick feedback.  

Currently I'm working with KinesisAnalyticsApplication and IaC with Java.  In such cases, the JAR Files/applications must be FatJARs (with all dependencies).  Most cases those JARs are at least 90MB. In my usecase I include three simple applications and the related JAR files are in sum around 320 MB.  Additionally I want to deploy some other resources must be available in S3. 

The Stack I'm using to deploy my full use case is broken, as soon the first JAR application (106MB) try to be deployed on S3

Kind Regards,

**Comment by bradodarb** [comment]
> > Hey, thanks for reporting this issue. We have a [feature request open](https://github.com/aws/aws-cdk/issues/7950) for this currently, please be sure to give it a thumbs up to help us know to prioritize this issue more. Thanks!
> 
> Hi Peter, thanks for your quick feedback.
> 
> Currently I'm working with KinesisAnalyticsApplication and IaC with Java. In such cases, the JAR Files/applications must be FatJARs (with all dependencies). Most cases those JARs are at least 90MB. In my usecase I include three simple applications and the related JAR files are in sum around 320 MB. Additionally I want to deploy some other resources must be available in S3.
> 
> The Stack I'm using to deploy my full use case is broken, as soon the first JAR application (106MB) try to be deployed on S3
> 
> Kind Regards,

Same issue, had to drop out of CDK  and use the AWS CLI for artifact deployments
