### ISSUE TITLE
(opensearch): Add support for OpenSearch Serverless

### ISSUE THREAD

**Issue by dblock** [aws/aws-cdk#23622]
### Describe the feature

Amazon OpenSearch Serverless is out in preview: https://aws.amazon.com/opensearch-service/features/serverless/

### Use Case

Launch serverless infrastructure.

### Proposed Solution

Either add a "flavor/version" of OpenSearch, or a brand new service support. 

I think it's the latter since serverless is identified as "aoss" vs. "es", but then it shouldn't have "versions" 🤔 

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

*

### Environment details (OS name and version, etc.)

*

**Comment by peterwoodworth** [comment]
[We have support for opensearch serverless already](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_opensearchserverless-readme.html) - unless this request is for higher level constructs?

**Comment by dblock** [comment]
My bad, it was hidden in https://github.com/aws/aws-cdk/pull/23294. Thanks!

**Comment by joekendal** [comment]
A higher-level construct might be nice.

**Comment by dobrynin** [comment]
+1 for a higher lever construct (also wouldn't mind one for ElasticCache Redis 😉)
