### ISSUE TITLE
 aws-ecs-patterns (QueueProcessingFargateService): Make Target CPU Utilization configurable

### ISSUE THREAD

**Issue by VarshaVid** [aws/aws-cdk#23624]
### Describe the feature

The current scaling policy defined in `QueueProcessingServiceBase` sets the `targetUtilizationPercent` at 50%, and is not configurable.
https://github.com/aws/aws-cdk/blob/fd5808f47111c0f72050f60e414df7f3f4ded6aa/packages/%40aws-cdk/aws-ecs-patterns/lib/base/queue-processing-service-base.ts#L344

This value should be configurable by users.

### Use Case

We have an application that works on a high throughput queue, but the processing is not latency-sensitive and we can afford to run hotter on the CPU, allowing us to run fewer ECS tasks and save on cost.

### Proposed Solution

This value should be configurable through an optional parameter added to `QueueProcessingServiceBaseProps` (and , by extension, `QueueProcessingFargateServiceProps`). If not specified by the user, this will default to 50% utilization, for backward compatibility.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

1.141

### Environment details (OS name and version, etc.)

NodeJS-14

**Comment by peterwoodworth** [comment]
Our L3 constructs will make some opinionated choices like this, this is something we _could_ add but typically if you need fine-grained control then building patterns with your own L2 constructs is a better choice if the modifications you need to make aren't easily achievable with [escape hatches](https://docs.aws.amazon.com/cdk/v2/guide/cfn_layer.html)

**Comment by AnuragMohapatra** [comment]
This issue should be closed after the merge of PR #28315 which introduces a prop to change the target CPU utilization on the main construct instead of base props.
