### ISSUE TITLE
aws-lambda: Add NODEJS_18_X to CDKv1

### ISSUE THREAD

**Issue by ArielPrevu3D** [aws/aws-cdk#23639]
### Describe the feature

NODEJS_18_X is missing from [aws-lambda/lib/Runtime.ts](https://github.com/aws/aws-cdk/blob/v1.187.0/packages/%40aws-cdk/aws-lambda/lib/runtime.ts).

### Use Case

NodeJS 14 LTS is EOL in 3 months, people will be upgrading to NodeJS 18 LTS. It would be nice to have it in the `Runtime` class for Lambda functions deployed via CDK v1.

### Proposed Solution

Add `NODEJS_18_X` under `NODEJS_16_X` in [aws-lambda/lib/Runtime.ts](https://github.com/aws/aws-cdk/blob/v1.187.0/packages/%40aws-cdk/aws-lambda/lib/runtime.ts).

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

1.187.0

### Environment details (OS name and version, etc.)

Windows 11 22H2

**Comment by peterwoodworth** [comment]
You'll need to resort to the override when using v1 - we aren't including any new features for v1, and haven't been since last June. Please upgrade to v2 to use the latest features, thanks!
