### ISSUE TITLE
aws-cdk/aws-ecs Documentation usage wrong for systemControls usage in readme

### ISSUE THREAD

**Issue by saimakhan89** [aws/aws-cdk#23635]
### Describe the issue

[Incorrect code link](https://github.com/aws/aws-cdk/blob/74318c7d22bfc00de9e005f68a0a6aaa58c7db39/packages/@aws-cdk/aws-ecs/README.md?plain=1#L454)

Works
```
 namespace: 'net.ipv6.conf.all.default.disable_ipv6',
value: '1',
```
Does not work - (example quoted in cdk doc)
```
namespace: 'net',
value: 'ipv6.conf.all.disable_ipv6',
```

Error you will get when doing above

```
The 'systemControls' namespace net must start with xxx prefix
```

### Links

https://github.com/aws/aws-cdk/blob/74318c7d22bfc00de9e005f68a0a6aaa58c7db39/packages/@aws-cdk/aws-ecs/README.md?plain=1#L454

**Comment by peterwoodworth** [comment]
Thanks for reporting this. We take [contributions](https://github.com/aws/aws-cdk/blob/v1-main/CONTRIBUTING.md), this would be a very simple change with no tests required 🙂
