### ISSUE TITLE
aws-opensearchservice: Domain creates new ResourcePolicy if logging enabled

### ISSUE THREAD

**Issue by andresblancomorales** [aws/aws-cdk#23637]
### Describe the bug

Creating a new OpenSearch domain creates a new ResourcePolicy every time if any of: slowSearchLogEnabled, slowIndexLogEnabled, appLogEnabled, auditLogEnabled is true.

According to the [CloudWatch limits](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/cloudwatch_limits_cwl.html):
```
Up to 10 CloudWatch Logs resource policies per Region per account. This quota can't be changed.
```

We're hitting this quota easily since every domain we create creates a new ResourcePolicy

### Expected Behavior

Not sure what what would be a good expected behavior.

May be: Reuse a previously created ResourcePolicy and add the new log policy statement.

### Current Behavior

A new resource policy is created with every new domain that is created with logging enabled.

### Reproduction Steps

Instantiate a new Domain and set any of the log types as true:

```typescript
                 const domain = new Domain(stack, 'TheDomain', {
                      version: EngineVersion.OPENSEARCH_1_2,
                      logging: {
                          appLogEnabled: true
                      }
                  })
```

### Possible Solution

Reuse a previously created ResourcePolicy and add the new log policy statement.

### CDK CLI Version

1.187.0

### Framework Version

1.187.0

### Node.js Version

16.19.0

### OS

Linux

### Language

Typescript

### Language Version

4.4.3

**Comment by pahud** [comment]
related to https://github.com/aws/aws-cdk/issues/22307

Yes we are aware  of the resource policy number limit and we definitely should have a workaround for that.

**Comment by XiaowenMaoA** [comment]
what's the workaround here?

**Comment by sakurai-ryo** [comment]
@XiaowenMaoA 
Could you try this code as a workaround until it is merged?

```ts
    const domain = new opensearch.Domain(this, 'Domain', domainProps);
    const domainResource = domain.node.defaultChild as opensearch.CfnDomain;
    domainResource.addOverride('DependsOn', undefined);

    domain.node.children
      .filter(child => child instanceof AwsCustomResource)
      .forEach(value => domain.node.tryRemoveChild(value.node.id));
```

**Comment by mxthxngx** [comment]
i faced a similar issue, and had to create a lambda that makes sdk calls to update the policy. 
i wrote an article on the same:  https://dev.to/math16/solved-resource-limit-exceeded-2np6 -- incase they are trying to update an existing resource policy, as referencing an existing policy was not possible directly through cdk
