### ISSUE TITLE
(cli): watch and `--hotswap` will not populate parameter fields

### ISSUE THREAD

**Issue by comcalvi** [aws/aws-cdk#23640]
### Describe the bug

`cdk watch` will not read parameters from `--parameters`

### Expected Behavior

`cdk watch` should read and use any parameters passed to it.

### Current Behavior

``` 
❌  Stack failed: Error: The following CloudFormation Parameters are missing a value: param1, param2
```

### Reproduction Steps

`yarn cdk watch --parameters param1=param-value --parameters param2=second-param-value `

where the stack contains

```
export class InlineLambdaStack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);

    const param = new CfnParameter(this, 'param1');
    const param2 = new CfnParameter(this, 'param2');

    // ...
```

### CDK CLI Version

2.56.0

### Node.js Version

14

### OS

mac

### Language

Typescript

**Comment by filipeandre** [comment]
bump

**Comment by pahud** [comment]
I assume this should be closed by https://github.com/aws/aws-cdk/pull/23653. Feel free to reopen if I was wrong.

**Comment by icj217** [comment]
@pahud We are still experiencing this issue on the latest CDK version (2.79.1). Details below.

requirements.txt:
```
aws-cdk-lib==2.79.1
constructs>=10.0.0,<11.0.0
```

stack:
```py
from aws_cdk import (
    Stack,
    CfnParameter
)
from constructs import Construct

class FooStack(Stack):

    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        param1 = CfnParameter(self, 'Foo')
        param2 = CfnParameter(self, 'Bar')
```

We did an initial deployment:
```
❯ npx -y aws-cdk@2.79.1 deploy --parameters "Foo=hello" --parameters "Bar=world"

 ✅  FooStack

✨  Deployment time: 18.22s
```
but attempting to do a watch fails:
```
❯ npx -y aws-cdk@2.79.1 watch --parameters "Foo=hello" --parameters "Bar=newworld"
...
 ❌  FooStack failed: Error: The following CloudFormation Parameters are missing a value: Foo, Bar
```
