### ISSUE TITLE
EKS: serviceAccountName should not be used as a label value. It can exceed 63 characters

### ISSUE THREAD

**Issue by portswigger-tim** [aws/aws-cdk#23643]
### Describe the bug

When using `Cluster.addServiceAccount` or creating a `ServiceAccount` directly, it is possible for the name to exceed the 63-character limit on label values and cause an error to be returned from the Kubernetes API server.

### Expected Behavior

Creating a `ServiceAccount` does not cause an error. 

### Current Behavior

Creating a `ServiceAccount` can cause an error to be returned by the Kubernetes API server:
```
Received response status [FAILED] from custom resource. Message returned: Error: b'The ServiceAccount "cdkmanagementeksclusterstackeksclusterkarpenterserviceaccount75eb78d2" is invalid: metadata.labels: Invalid value: "cdkmanagementeksclusterstackeksclusterkarpenterserviceaccount75eb78d2": must be no more than 63 characters\n' Logs: /aws/lambda/CDK-management-EksClusterStack-aws-Handler886CB40B-mM6UW0XNzxC3 at invokeUserFunction (/var/task/framework.js:2:6) at processTicksAndRejections (internal/process/task_queues.js:95:5) at async onEvent (/var/task/framework.js:1:365) at async Runtime.handler (/var/task/cfn-response.js:1:1543) (RequestId: 22e09e60-bee4-444a-89a8-3230b7d64f4f)
```

### Reproduction Steps

Create a ServiceAccount at a point where the name would exceed 63 characters.

### Possible Solution

Don't add the label at:

https://github.com/aws/aws-cdk/blob/e5b023089e168c50eda83a11db0e697b96caf7e9/packages/%40aws-cdk/aws-eks/lib/service-account.ts#L125

IMO it's not necessary as the name is, well the name (metadata.name, which can be 253 characters). 

### CDK CLI Version

2.59.0

### Node.js Version

LTS

### OS

AL2

### Language

Python

### Language Version

3.11

**Comment by pahud** [comment]
Hi

Have you tried to specify your custom account name to avoid this?
https://github.com/aws/aws-cdk/blob/a6fa5b88e1bd6a45b9c176a92eac20c702c894f4/packages/%40aws-cdk/aws-eks/lib/service-account.ts#L18
