### ISSUE TITLE
C#: Consider using keyword arguments instead of prop classes

### ISSUE THREAD

**Issue by fulghum** [aws/aws-cdk#2365]

**Comment by eladb** [comment]
Maybe add a bit more context

**Comment by assyadh** [comment]
We chose not to do it and keep using prop objects. 

This can be closed.

**Comment by eladb** [comment]
Can you share the rational behind the decision for posterity?

**Comment by assyadh** [comment]
Exploding the parameters in the constructors:

* *PRO*: This provides required parameters validation out of the box
* *CON*: Calling the constructors becomes a hassle as you may need to provide many inline parameters.
* *CON*: The customers would have to only use named arguments. We can write a Roslyn Analyzer to enforce this (https://github.com/mykolav/require-named-args-fs)
* *CON*: New parameters can only be added at the end of the parameters list.
* *CON*: This affect jsii usages other than just the CDK.
