### ISSUE TITLE
using s3Deployment.BucketDeployment and passing cloudfront distribution for cache invalidation is causing us downtime of around 10-15 seconds.

### ISSUE THREAD

**Issue by RahulChowdaryN** [aws/aws-cdk#23678]
### Describe the bug

We have static app hosted on s3 with cloudfront. our users are seeing downtime whenever a deployment is happening for around 10-15secs. We are using CDK and I believe S3 bucket deployment which also invalidates the cache causing the downtime. Is this know issue? any workarounds?

We are passing cloudfront distribution to the function for invalidation. It's trying to upload the assets and before that it's also trying to invalidate the cache. 

This happens irrespective of whether or not we add a dependency bcos it's happening within a function

```
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>1.0.12580.0/index.html</Key>
<RequestId>WBVXGT18JX5CD15H</RequestId>
<HostId>/zq3kRpwy21WpHGtRSGdVP4NNhN75Ap87WoyvTSlMpJIA5cDY0TWtr9Tp5E/3oEZkJ74mQpi9VM=</HostId>
</Error>
```

### Expected Behavior

no downtime

### Current Behavior

downtime with error

### Reproduction Steps

pass cloudfront distribution to  s3Deployment.BucketDeployment 

### CDK CLI Version

2.17.0

### Node.js Version

14

### OS

macos

### Language

Typescript

**Comment by jaredtbates** [comment]
This is happening to us as well. Are you by chance using hotswap? We use hotswap in our dev environment and wondering if it's related.

**Comment by RahulChowdaryN** [comment]
Not really. We aren’t using hotswap.

**Comment by rix0rrr** [comment]
`1.0.12580.0/index.html` is this the old key or the new key?

**Comment by pahud** [comment]
Looking at this issue now.

@RahulChowdaryN  are you able to provide minimal code snippets and steps so I can reproduce this issue?
