### ISSUE TITLE
CodeBuildStep: There is no way to provide a LoggingOptions to PipelineProject through CodeBuildStep.

### ISSUE THREAD

**Issue by mrm12m** [aws/aws-cdk#23676]
### Describe the bug

A few months back, a change was made to allow passing a LoggingOptions to PipelineProjectProps/CommonProjectProps:

 https://github.com/aws/aws-cdk/issues/3856
 https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-codebuild.PipelineProject.html#logging
 
The CodeBuildStep construct generates a PipelineProject by itself, and there is no way to pass the log group object to it.

https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/pipelines/lib/codepipeline/private/codebuild-factory.ts#L294

### Expected Behavior

We should be able to set the LoggingOptions whenever we use BuildStep. The config can be passed through CodeBuildStepProps and gets passed along to PipelineProject.

### STEP 1
`export interface CodeBuildStepProps extends ShellStepProps {
 //...
      /**
     * Information about logs for the build project. A project can create logs in Amazon CloudWatch Logs, an S3 bucket, or both.
     *
     * @default - no log configuration is set
     */
    readonly logging?: LoggingOptions;

//...
}
`

### STEP2
`
export class CodeBuildFactory implements ICodePipelineActionFactory {

//...
    const project = new codebuild.PipelineProject(projectScope, this.constructId, {
      projectName: this.props.projectName,
      description: `Pipeline step ${safePipelineName}/${stage.stageName}/${actionName}`.substring(0, 255),
      environment,
      vpc: projectOptions.vpc,
      subnetSelection: projectOptions.subnetSelection,
      securityGroups: projectOptions.securityGroups,
      cache: projectOptions.cache,
      buildSpec: projectBuildSpec,
      role: this.props.role,
      timeout: projectOptions.timeout,
      logging: projectOptions.logging, // <----- THIS LINE IS NEW
    });

//...
}
`

### Current Behavior

There is no way to pass LoggingOptions down to PipelineProject when using CodeBuildStep.

### Reproduction Steps

Just by creating a CodeBuildStep

`
const step = new CodeBuildStep(this, 'CodeBuildStep', {
// No logging options available
});
`

### Possible Solution

Mentioned in expected behaviour.

### CDK CLI Version

2.60.0

### Node.js Version

16.14.0

### OS

Ubuntu 20.04.5 LTS

### Language

Typescript

### Language Version

TypeScript (4.7.4)

**Comment by mrm12m** [comment]
@yo-ga 
First of all, thanks for the change in PR #24016. It already makes things better. But having just one place to define the default logging options for all builds can be a bit restrictive as all of the codeBuilds will fall into the same LogGroup.

So I would really appreciated it if you could also do this feature as well.

Many thanks in advance!

**Comment by yo-ga** [comment]
@mrm12m Thanks for the reply.
It would be easy to add the options supporting in different steps.
I would do that when I'm free.

**Comment by yo-ga** [comment]
Because the reviewer is reviewing the PR, I would create a new PR to support the feature.

**Comment by mrm12m** [comment]
>>> Because the reviewer is reviewing the PR, I would create a new PR to support the feature.

This makes total sense.

Thank you for willing to help @yo-ga !

**Comment by pahud** [comment]
Thank you for the PR contribution!!

**Comment by khushail** [comment]
this is implemented by https://github.com/aws/aws-cdk/pull/25266. closing the issue now.
