### ISSUE TITLE
aws_cdk.aws_guardduty >> CfnDetector: Doesn't recognize CFNMalwareProtectionConfigurationProperty

### ISSUE THREAD

**Issue by iamgabeortiz** [aws/aws-cdk#23686]
### Describe the bug

Using the example from:

https://docs.aws.amazon.com/cdk/api/v1/python/aws_cdk.aws_guardduty/CfnDetector.html

I get this error:

`Traceback (most recent call last):
  File "app.py", line 101, in <module>
    my_security_stack = MySecurityStack(
  File "/home/gabeortiz/cdk-projects/my-aws/.venv/lib/python3.8/site-packages/jsii/_runtime.py", line 86, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/home/gabeortiz/cdk-projects/my-aws/my_aws/my_security_stack.py", line 101, in __init__
    malware_protection=guardduty.CfnDetector.CFNMalwareProtectionConfigurationProperty(
AttributeError: type object 'CfnDetector' has no attribute 'CFNMalwareProtectionConfigurationProperty'`

### Expected Behavior

Expect the CDK Diff to show me the Diff. :P

### Current Behavior

`(.venv) gabeortiz@Gabe-Desktop:~/cdk-projects/my-aws$ cdk diff
Traceback (most recent call last):
  File "app.py", line 101, in <module>
    my_security_stack = MySecurityStack(
  File "/home/gabeortiz/cdk-projects/my-aws/.venv/lib/python3.8/site-packages/jsii/_runtime.py", line 86, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/home/gabeortiz/cdk-projects/my-aws/my_aws/my_security_stack.py", line 101, in __init__
    malware_protection=guardduty.CfnDetector.CFNMalwareProtectionConfigurationProperty(
AttributeError: type object 'CfnDetector' has no attribute 'CFNMalwareProtectionConfigurationProperty'`

### Reproduction Steps

Use the example from this page.

https://docs.aws.amazon.com/cdk/api/v1/python/aws_cdk.aws_guardduty/CfnDetector.html

The other GuardDuty features work as expected.

### CDK CLI Version

2.60.0 (build 2d40d77)

### Node.js Version

v14.17.0

### OS

Windows 10 WSL 2

### Language

Python

### Language Version

Python 3.8.10

**Comment by peterwoodworth** [comment]
I'm not able to reproduce this, the generated code snippet works fine for me. Could you please post the exact snippet that you are using?
