### ISSUE TITLE
aws_eks: AlbControllerOptions not accepting policy

### ISSUE THREAD

**Issue by ItielOlenick** [aws/aws-cdk#23690]
### Describe the bug

One cannot create a aws_eks.AlbControllerOptions with a plicy.

The first issue is that the policy parameter's type hint is `Any`. 
So after trying any possible policy related object from aws_iam, arrays, jsons, you name it, i get the following error in all cases:

```python
  File "/opt/usr/app/.env/lib/python3.9/site-packages/jsii/_runtime.py", line 86, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/opt/usr/app/.env/lib/python3.9/site-packages/aws_cdk/aws_eks/__init__.py", line 12970, in __init__
    jsii.create(self.__class__, self, [scope, id, props])
  File "/opt/usr/app/.env/lib/python3.9/site-packages/jsii/_kernel/__init__.py", line 321, in create
    response = self.provider.create(
  File "/opt/usr/app/.env/lib/python3.9/site-packages/jsii/_kernel/providers/process.py", line 347, in create
    return self._process.send(request, CreateResponse)
  File "/opt/usr/app/.env/lib/python3.9/site-packages/jsii/_kernel/providers/process.py", line 329, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: policy.Statement is not iterable
```

Looking into the typescript code alongside the python one makes sense why.
Seems like there is no such `Policy` object that has an iterable field called Statement.

### Expected Behavior

An aws_eks.AlbControllerOptions should be created

### Current Behavior

An error is thrown

### Reproduction Steps

Try to create an aws_eks.AlbControllerOptions with a policy

### Possible Solution

Figure out if and what actually needs to be passed to the policy argument, and add that as a type hint.

### CDK CLI Version

2.37.1

### Node.js Version

15

### OS

Linux

### Language

Python

**Comment by pahud** [comment]
Hi

Can you provide a full CDK sample code that reproduces this problem?

**Comment by ItielOlenick** [comment]
@pahud Sure.

```python
policy_a = aws_iam.Policy(
    id="policyA"
)

alb_controller_settings = aws_eks.AlbControllerOptions(
    version=aws_eks.AlbControllerVersion.V2_4_1,
    policy=policy_a
)
```

**Comment by pahud** [comment]
@ItielOlenick 

According to this https://github.com/aws/aws-cdk/blob/be4f97129f4237b39d0b99977eb597e2af49ed2a/packages/%40aws-cdk/aws-eks/lib/alb-controller.ts#L216

I believe the value should be a json object and the default json is at 
https://github.com/aws/aws-cdk/tree/main/packages/%40aws-cdk/aws-eks/lib/addons

I hope this helps.

**Comment by ItielOlenick** [comment]
What does this translate into in python? Tried a dict, didn't work.

**Comment by peterwoodworth** [comment]
```
policy_a = aws_iam.Policy(
    id="policyA"
)

alb_controller_settings = aws_eks.AlbControllerOptions(
    version=aws_eks.AlbControllerVersion.V2_4_1,
    policy=policy_a
)
```

This snippet won't work in _any_ language. `AlbControllerOptions` doesn't want to accept a `Policy` construct, it wants to accept a literal JSON object of [this format](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_statement.html). If you're using a `PolicyStatement`, you can use the [`toJSON()` method](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_iam.PolicyStatement.html#towbrjson)
