### ISSUE TITLE
Python MemoryDB: attr_cluster_endpoint_port token is returned as number instead of a Token.

### ISSUE THREAD

**Issue by NoahLiot** [aws/aws-cdk#23694]
### Describe the bug

When running the code snippet below in a CDK stack, the attribute `attr_cluster_endpoint_port` in a memoryDB cluster is returned as number instead of a Token. As a consequence it does not get replaced at deployment time and break downstream dependencies.

```
cfnACL = mdb.CfnACL(self, 
        id="aclredis",
        acl_name="aclredis",
        )
redis_clust = mdb.CfnCluster(self, 
        id="redisclust",
        acl_name="aclredis",
        cluster_name="redisclust",
        node_type="db.t4g.small",
        )
redis_endpoint = redis_clust.attr_cluster_endpoint_address
redis_port = redis_clust.attr_cluster_endpoint_port
```

This code snippet output is:

```
${Token[TOKEN.213]}
-1.8881545897087961e+289
```

As you can see the first token (the endpoint) is correct. The second one, the port, is corrupted.

### Expected Behavior

The attribute `attr_cluster_endpoint_port` should return an object of type Token which gets replaced a by a String at deployment time.

### Current Behavior

The attribute `attr_cluster_endpoint_port` is a number and cannot be used later in the stack to populate, for example, a lambda env variable:

```
jsii.errors.JavaScriptError:
  @jsii/kernel.SerializationError: Passed to parameter props of new aws-cdk-lib.aws_lambda.Function: Unable to deserialize value as aws-cdk-lib.aws_lambda.FunctionProps
  ├── 🛑 Failing value is an object
  │      { '$jsii.struct': [Object] }
  ╰── 🔍 Failure reason(s):
      ╰─ Key 'environment': Unable to deserialize value as map<string> | undefined
          ├── 🛑 Failing value is an object
          │      { '$jsii.map': [Object] }
          ╰── 🔍 Failure reason(s):
              ╰─ Key 'redis_port': Unable to deserialize value as string
                  ├── 🛑 Failing value is a number
                  │      -1.888154589708796e+289
                  ╰── 🔍 Failure reason(s):
                      ╰─ Value is not a string
```

### Reproduction Steps

Run the above code snippet in a CDK stack.

### Possible Solution

Find where is the Token being cast into a number and prevent this.

### Additional Information/Context

N/A

### CDK CLI Version

2.60.0 (build 2d40d77)

### Framework Version

N/A

### Node.js Version

N/A

### OS

macOS Monterey 12.6.1

### Language

Python

### Language Version

Python (3.10.0)

**Comment by NoahLiot** [comment]
Any update on the triage of the issue? I can workaround it by hardcoding the variable, but this is far from ideal. Thank you!

**Comment by pahud** [comment]
cloud related to https://github.com/aws/aws-cdk/issues/18282 but that value seems to be a number token. I need reproduce the deployment in my account first.

**Comment by pahud** [comment]
@NoahLiot  before I reproduce it, are you able to output this value with the following statement but in Python syntax?

```
new cdk.CfnOutput(this, 'Port', { value: cluster.attrClusterEndpointPort.toString() })
```

According to https://github.com/aws/aws-cdk/issues/18282 this should be a number token and should correctly display with toString() now.

**Comment by pahud** [comment]
I am making it as p1 bug now. 

I can deploy the memoryDB cluster as below but I can't CfnOutput the value either with `cluster.attrClusterEndpointPort.toString()` or `cdk.Token.asString(cluster.attrClusterEndpointPort)`

```ts

    const vpc = ec2.Vpc.fromLookup(this, 'Vpc', { isDefault: true });
    const subnets = vpc.selectSubnets({
      subnetType: ec2.SubnetType.PRIVATE_WITH_EGRESS,
      availabilityZones: ['us-east-1a', 'us-east-1b', 'us-east-1d' ],
    });
    const memoryDBSubnetGroup = new mdb.CfnSubnetGroup(this, 'MemoryDB Subnet Group', {
      subnetGroupName: `subnetGroup${id}`.toLocaleLowerCase(),
      subnetIds: subnets.subnetIds,
    });
    const dbSecurityGroup = new ec2.SecurityGroup(this, 'DB Security Group', {
      vpc
    });
    const cluster = new mdb.CfnCluster(this, 'Cluster', {
      aclName: 'open-access',
      clusterName: `cluster${id}`.toLocaleLowerCase(),
      nodeType: 'db.t4g.small',
      subnetGroupName: memoryDBSubnetGroup.subnetGroupName,
      securityGroupIds: [ dbSecurityGroup.securityGroupId ],
    });

    new cdk.CfnOutput(this, 'Port', { value:  cluster.attrClusterEndpointPort.toString() })
    new cdk.CfnOutput(this, 'Port', { value: cdk.Token.asString(cluster.attrClusterEndpointPort) })
```

**Comment by robosung** [comment]
I'm having a similar issue trying to pass into an lambda.
```
cluster = memorydb.CfnCluster(
    self,
    "MemoryDBCluster",
    ...
)

...
# Lambda code
my_lambda = lambda_.DockerImageFunction(
    self,
    "my_lambda",
    ...
    environment={
        "ENVIRONMENT": stage,
        "MDB_ENDPOINT": cluster.cluster_endpoint,
    },
    tracing=lambda_.Tracing.ACTIVE,
)
```
On synth, throws:
```
RuntimeError: Passed to parameter props of new aws-cdk-lib.aws_lambda.DockerImageFunction: Unable to deserialize value as aws-cdk-lib.aws_lambda.DockerImageFunctionProps
├── 🛑 Failing value is an object
│      { '$jsii.struct': [Object] }
╰── 🔍 Failure reason(s):
    ╰─ Key 'environment': Unable to deserialize value as map<string> | undefined
        ├── 🛑 Failing value is an object
        │      { '$jsii.map': [Object] }
        ╰── 🔍 Failure reason(s):
            ╰─ Key 'MDB_ENDPOINT': Unable to deserialize value as string
                ├── 🛑 Failing value is null
                ╰── 🔍 Failure reason(s):
                    ╰─ A value is required (type is non-optional)

Subprocess exited with error 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by GavinZZ** [comment]
Thanks for raising this issue, I can confirm that I am able to reproduce this issue. There seems to be a bug in the implementation of `cdk.Token.asNumber`. Will confirm with the team and draft a PR for the fix.

**Comment by GavinZZ** [comment]
After doing some investigation, I believe this is not a bug but we do miss some documentations on how to use Tokenized numbers. 

When you create a the construct like the following
```
const cluster = new mdb.CfnCluster(this, 'Cluster', {...});
console.log(cluster.attrClusterEndpointPort);
```

The output of the endpoint port is a weird-looking double value, i.e. `-1.8881545897087961e+289`. This looks a lot different from the other Tokenized strings we have `${Token[X.123]}`. This double value is actually a representation of the token counter (i.e. `X.123`) in number. 

As the value is expected to be a number, the token has to be encoded into a value that can go into
```
var x: number;

// This will not work.
var x: number = '${Token[X.123]}';
```

To workaround the problem, you will need to use the `Tokenization.stringifyNumber` to stringify a number directly or lazily if it's a Token. If it is an object (i.e., { Ref: 'SomeLogicalId' }), return it as-is.

As complete example would be 
```
const cluster = new mdb.CfnCluster(this, 'Cluster', {
      aclName: 'open-access',
      clusterName: `cluster${id}`.toLocaleLowerCase(),
      nodeType: 'db.t4g.small',
      subnetGroupName: memoryDBSubnetGroup.subnetGroupName,
      securityGroupIds: [ dbSecurityGroup.securityGroupId ],
});

new cdk.CfnOutput(this, 'Port', { value:  Tokenization.stringifyNumber(cluster.attrClusterEndpointPort) })

// To use it in environment variable or substrings, you could also use the above method.
```

**Comment by GavinZZ** [comment]
As mentioned above, this is not a bug as this is how the token value is designed and implemented for numbers. I think CDK is missing some documentation on this usage and thus causing the confusion. I will kick off a PR to add some documentations on using number formatted Token values.

**Comment by GavinZZ** [comment]
As described above, this is technically not a bug. Workaround is provided above. Will downgrade this issue to `p2` for now. Once the official documentation is updated with more details on using number-encoded tokens, I'll come up and resolve this issue. 

Meanwhile if you have any additional questions, feel free to ping me and I'll try to get back to you ASAP.

**Comment by GavinZZ** [comment]
Please checkout this new documentation page https://docs.aws.amazon.com/cdk/v2/guide/tokens.html#tokens_number. Marking this issue as completed. Feel free to open another issue if you have additional questions.
