### ISSUE TITLE
aws-wafv2: LoggingFilterProperty generating incorrect CloudFormation Template

### ISSUE THREAD

**Issue by automartin5000** [aws/aws-cdk#23709]
### Describe the bug

At some point since version 2.50 (I think), there seems to have been a breaking change to the CloudFormation resource being created by the aws-wafv2 `LoggingFilterProperty` resulting in the following error message: 
```
#/LoggingFilter: required key [DefaultBehavior] not found
#/LoggingFilter: required key [Filters] not found
#/LoggingFilter: extraneous key [defaultBehavior] is not permitted
#/LoggingFilter: extraneous key [filters] is not permitted
```

This seems to be related to the wrong casing (see details below).

### Expected Behavior

CloudFormation code that uses pascal casing as described in [the API](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-wafv2-loggingconfiguration-loggingfilter.html)

### Current Behavior

The following CloudFormation code is created with camel cased properties:
```
"LoggingFilter": {
     "defaultBehavior": "DROP",
     "filters": [
      {
       "requirement": "MEETS_ANY",
       "conditions": [
        {
         "actionCondition": {
          "action": "BLOCK"
         }
        },
        {
         "actionCondition": {
          "action": "COUNT"
         }
        }
       ],
       "behavior": "KEEP"
      }
     ]
    },
```
This results in the following error message when attempting to deploy:
```
#/LoggingFilter: required key [DefaultBehavior] not found
#/LoggingFilter: required key [Filters] not found
#/LoggingFilter: extraneous key [defaultBehavior] is not permitted
#/LoggingFilter: extraneous key [filters] is not permitted
```

### Reproduction Steps

We're using the following code to build our logging configuration:
``` typescript
export abstract class LoggingFilterConfiguration {
  /**
   * Keep logs that don't match any of the specified filter conditions.
   * @param filters
   * @returns LoggingFilterConfiguration
   */
  public static defaultKeep(
    filters: any[],
  ): wafv2.CfnLoggingConfiguration.LoggingFilterProperty {
    return {
      defaultBehavior: LoggingFilterBehavior.KEEP,
      filters: filters,
    };
  }

  /**
   * Drop logs that don't match any of the specified filter conditions.
   * @param filters
   * @returns LoggingFilterConfiguration
   */
  public static defaultDrop(
    filters: any[],
  ): wafv2.CfnLoggingConfiguration.LoggingFilterProperty {
    return {
      defaultBehavior: LoggingFilterBehavior.DROP,
      filters: filters,
    };
  }
}
```

### CDK CLI Version

2.61.1

### Node.js Version

18

### OS

Mac OS 13.1

### Language

Typescript

### Language Version

4.7.4

**Comment by eloymg** [comment]
I think that exist the same bug with:
 - wafv2.CfnWebACL.SingleHeaderProperty
 - wafv2.CfnLoggingConfiguration.SingleHeaderProperty
Generate the property with "name" no "Name" that is correct.

**Comment by pahud** [comment]
According to [this cfnspec](https://github.com/aws/aws-cdk/blob/0c7c7e4a7c34957ff7877eda5171f82c5feaba1d/packages/%40aws-cdk/cfnspec/spec-source/specification/000_cfn/000_official/000_AWS_WAFv2.json#L2379), I think the `loggingFilter` property should be a [LoggingFilter](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-wafv2-loggingconfiguration-loggingfilter.html) type rather than `any`([described](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_wafv2.CfnLoggingConfigurationProps.html#properties) in the API reference). I need to discuss this internally with the team.

**Comment by pahud** [comment]
This issue is related to https://github.com/aws/aws-cdk/issues/23679#issuecomment-1382594104 as described by @peterwoodworth. At this moment, as `loggingFilter` property in L1 is not strongly typed, you will need to capitalize the property to synthesize correct CFN template.

**Comment by peterwoodworth** [comment]
The way described above is the proper way to define this from now on. Sorry for any inconvenience, we're looking into making sure this doesn't happen again

**Comment by JohannesTimmreck-MHP** [comment]
Hi @peterwoodworth,

I believe that this problem was not resolved in the [fix(WAFv2): add patch to revert struct names #24651](https://github.com/aws/aws-cdk/pull/24651) as it did not modify the LoggingFilterProperty.

**Comment by peterwoodworth** [comment]
That's already been done before that PR here @JohannesTimmreck-MHP  https://github.com/aws/aws-cdk/blob/5d5264622d376d3ec41cfbeb1736e6de375f6f12/packages/%40aws-cdk/cfnspec/spec-source/specification/000_cfn/500_Revert_To_Json_Types_patch.json#L510

**Comment by JohannesTimmreck-MHP** [comment]
Hi @peterwoodworth,  
 as it seems the link you send corrected the  LoggingFilterConfiguration, but it also does not mention the CfnLoggingConfiguration.LoggingFilterProperty, for which the error in regards to the mismatch of "DefaultBehavior"-"defaultBehavior" and "Filters"-"filters" properties.

**Comment by peterwoodworth** [comment]
[The type](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_wafv2.CfnLoggingConfiguration.LoggingFilterProperty.html) that this construct originally expected still gets generated - you just shouldn't use the type because the construct doesn't want to accept this type anymore. The patch here is changing the type that `CfnLoggingConfiguration` expects for its `loggingConfiguration` property.

**Comment by JohannesTimmreck-MHP** [comment]
Ahh alright, thank you for the help!
