### ISSUE TITLE
Support multiple context files via commandline parameter

### ISSUE THREAD

**Issue by kertzi** [aws/aws-cdk#2371]
In our use case we need to specify some parameters based on  deployment environment. 
Like tag "environment" which valua may be prod, staging, devel, testing etc. depends on where cdk app is going to be deployed. 

Adding those to cdk.json under "context" key is useful but what is missing is ability to specify cdk.json file used when deploy/synth.
 
So it would be nice to have parameter like "--context-file":
cdk deploy --context-file cdk.prod.json
or 
cdk deploy --context-file cdk.devel.json

**Comment by tomilaurell** [comment]
I have just implemented similar feature for my purposes in the npm-package:
https://www.npmjs.com/package/cdk-infra-properties
https://github.com/tomilaurell/cdk-infra-properties

Example:
https://github.com/tomilaurell/cdk-infra-properties-simple-example

This is based in infra.properties files. Branch specific files (infra-BRANCHNAME.properties) will overwrite properties set in default file. Properties in the subfolders overwrite those set at higher levels. More specific files overwrite more generic. We have used this approach succesfully for years with this project: https://github.com/NitorCreations/nitor-deploy-tools
I copied the idea from that to try how it works natively with AWS-CDK and it works well. I will write documentation for that next in a week.

**Comment by SomayaB** [comment]
Hi @kertzi ! I apologize for the late reply. Did @tomilaurell 's solution work for you? (Thanks @tomilaurell 👍) 
I will close this issue shortly if no response.

**Comment by kertzi** [comment]
> Hi @kertzi ! I apologize for the late reply. Did @tomilaurell 's solution work for you? (Thanks @tomilaurell 👍)
> I will close this issue shortly if no response.

Looks good! Thanks

**Comment by juanjoDiaz** [comment]
I think that this is a pretty valid use case and I'd like to see it reopened. 🙂

I don't think that @tomilaurell is a valid solution since it seems undocumented, unupdated and unused.

I think that being able to select the context as runtime is a basic functionality to be able to reuse code between multiple environments.

**Comment by mskrip** [comment]
This feature would by greatly appreciated to enable us to be able to have a separate context file for devel that we don't have to commit to VCS. IMO should be reopened.

**Comment by mutovkin** [comment]
@SomayaB I believe this is a very useful feature that should be part of CDK itself.

**Comment by virajkanwade** [comment]
@SomayaB Added an attempt for supporting this feature https://github.com/aws/aws-cdk/pull/23784
But I have never worked on nodejs/ typescript so not sure how or where to add the tests.

FYI, @kertzi @juanjoDiaz @mskrip @mutovkin @ajota-admios
