### ISSUE TITLE
(aws-kms): Add support for HMAC keys

### ISSUE THREAD

**Issue by matthias-pichler-warrify** [aws/aws-cdk#23727]
### Describe the feature

KMS not only supports symmetric and asymmetric keys but also HMAC keys: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kms-key.html#cfn-kms-key-keyspec

It would be great to have 1st class support for them in the cdk.

### Use Case

I want to implement the OAuth2 authorization_code flow with a nonce that is hmac verified and use KMS to do the signing.

### Proposed Solution

Add the missing values to the `KeySpec` and `KeyUsage` enums:

```ts
 const hmacKey = new kms.Key(this, "HMACSecret", {
      enabled: true,
      enableKeyRotation: true,
      keySpec: kms.KeySpec.HMAC_256,
      keyUsage: kms.KeyUsage.GENERATE_VERIFY_MAC,
    });
```

### Other Information

Trying to override the enum values with strings directly (like this):

```typescript
const hmacKey = new kms.Key(this, "HMACSecret", {
      enabled: true,
      enableKeyRotation: true,
      keySpec: "HMAC_256" as any,
      keyUsage: "GENERATE_VERIFY_MAC" as any,
    });
```

 currently fails due to the validation [here](https://github.com/aws/aws-cdk/blob/c2997325e3a1c48ba9d884f1db64b4c14eae1a0b/packages/%40aws-cdk/aws-kms/lib/key.ts#L605)

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.60.0

### Environment details (OS name and version, etc.)

MacOS, Node 18

**Comment by peterwoodworth** [comment]
Thanks for the request, it looks like we can also add `SM2` as well as `HMAC` keys 🙂 

I am marking this issue as p2, which means that we are unable to work on this immediately.

We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://cdk.dev) to solicit support for reprioritization.

Check out our [contributing guide](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) if you're interested in contributing yourself!

For now, you can override the key after it's been generated:
```ts
const hmacKey = new Key(...);
(hmacKey.node.defaultChild as CfnKey).addPropertyOverride('KeySpec', 'HMAC_XXX');
```

**Comment by daschaa** [comment]
@peterwoodworth I would like to work on this issue :-) 
However, I have one more question before I start: I have read that for HMAC keys key can not be enabled. How would I prevent it in the CDK? Should I throw an error when a combination of `enableKeyRotation` and `keySpec: "HMAC"` is given? What is a best practice here?
