### ISSUE TITLE
How to create Bastion Server for vpc

### ISSUE THREAD

**Issue by vjindalradialtheory** [aws/aws-cdk#2373]
Hi,

How can i create Bastion Server for vpc  ?

**Comment by SomayaB** [comment]
Hi, I apologize for the late reply. Do you still guidance regarding this issue?

**Comment by skinny85** [comment]
We also now have support for [native Bastions](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-ec2-readme.html#bastion-hosts) :)

**Comment by SomayaB** [comment]
Closing this issue since there hasn't been activity on it for a while. Feel free to reopen if you would still like guidance on this.
