### ISSUE TITLE
aws-cdk-lib.aws_lambda_event_sources module: Support for Amazon MQ trigger

### ISSUE THREAD

**Issue by sahilrc** [aws/aws-cdk#23764]
### Describe the feature

Currently missing support for MQ as an event source. 

"Eventually, this module will support all the event sources described under [Supported Event Sources](https://docs.aws.amazon.com/lambda/latest/dg/invoking-lambda-function.html) in the AWS Lambda Developer Guide."

https://docs.aws.amazon.com/lambda/latest/dg/lambda-services.html

Is there an ETA for this?

### Use Case

Use Amazon MQ as trigger for Lambda via CDK.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.61.0

### Environment details (OS name and version, etc.)

MacOS

**Comment by pahud** [comment]
I am afraid this is a feature request to AWS lambda.  We need to ensure lambda native supports that before we are able to deliver it in CDK. Closing this issue as it's not relevant to aws-cdk.
