### ISSUE TITLE
(synthetics): add DeleteLambdaResourcesOnCanaryDeletion to the canary L2

### ISSUE THREAD

**Issue by kaizencc** [aws/aws-cdk#23772]
### Describe the feature

Lambda has a new? property that will delete lambda resources when the canary is deleted. 

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-synthetics-canary.html#cfn-synthetics-canary-deletelambdaresourcesoncanarydeletion

This is a step in the right direction, but still not perfect, because canaries will still isolate s3 buckets, log groups, etc. Still, we should support this property in the L2 and allow our users to specify this prop.

### Use Case

Currently, after deleting the canary you have to go and manually delete lambda/s3/cloudwatch logs. Now, you can set this property and only delete s3 + cloudwatch.

### Proposed Solution

Add the prop to `Canary`. This will need some testing to make sure that the property is doing what we expect.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

latest

### Environment details (OS name and version, etc.)

MacOs

**Comment by jedwards1211** [comment]
Did this property go away?  OP's link to the CloudFormation docs no longer shows anything about DeleteLambdaResourcesOnCanaryDeletion.

**Comment by SankyRed** [comment]
As part of stabilizing the `synthetics` module I see @kaizencc has cleaned up `DeleteLambdaResourcesOnCanaryDeletion` property in this [PR](https://github.com/aws/aws-cdk/pull/27305). Also, instead of `enableAutoDeleteLambdas` you could use `cleanup: Cleanup.LAMBDA` the same affect via custom resource.

**Comment by jedwards1211** [comment]
Do you know if CloudFormation itself supports deleting the lambda?  I'm not actually using the CDK, just landed here because OP had a link to the CloudFormation docs that looks like it mentioned the kind of option I need.
