### ISSUE TITLE
(bootstrap): cannot remove permissions boundary for cfn execution role

### ISSUE THREAD

**Issue by clueleaf** [aws/aws-cdk#23780]
### Describe the bug

After bootstrapping with `--custom-permissions-boundary` option, it is not possible to remove the boundary attached to the CloudFormation execution role by bootstrapping again without `--custom-permissions-boundary` option.
Though adding a boundary from nothing or switching to another boundary is working fine.

### Expected Behavior

CloudFormation execution role is updated without a permissions boundary.

### Current Behavior

CloudFormation execution role is not updated.

### Reproduction Steps

1. Bootstrap with permissions boundary.

> cdk bootstrap --custom-permissions-boundary "my-boundary"

2. Bootstrap again without permissions boundary.

> cdk bootstrap -v

Console log says it is switching boundaries but the deployment is skipped after all.

<img width="1176" alt="Screenshot 2023-01-22 at 18 32 15" src="https://user-images.githubusercontent.com/10379303/213909466-1b0c39c0-1e4d-41df-8558-a34ba8541a36.png">

3. Even with `--force` option, role is not updated.

> cdk bootstrap -v --force

<img width="1387" alt="Screenshot 2023-01-22 at 18 33 39" src="https://user-images.githubusercontent.com/10379303/213909534-80500b04-7c00-4430-8cfd-7c2965e5e2bd.png">

### CDK CLI Version

2.61.1

### Node.js Version

18

### OS

macOS Ventura

### Language

Typescript

**Comment by pahud** [comment]
Thanks for your report. I am making it p1 for more visibility.
