### ISSUE TITLE
[aws-eks] Unable to managed the self managed node group's securityGroup when using cluster.add_nodegroup_capacity.

### ISSUE THREAD

**Issue by gzus85** [aws/aws-cdk#23792]
### Describe the bug

Unable to managed the self managed node group's securityGroup when using cluster.add_nodegroup_capacity.
There is seemingly no way to specify the SecurityGroupID to be used by the self managed node group.

My use case is that I'm running my EKS cluster with a SelfManaged NodeGroup and another set of nodes managed by Karpenter.
I can't find a CDK native way to allow traffic from the karpenterSG (created in CDK) to the SelfManaged NodeGroupSG .

The main issue I have is that the NodeGroup construct does not take a SecurityGroupID as an input parameter but instead a SecurityGroup is created automatically behind the scene . Therefore I'm unable to allow traffic inbound from this SecurityGroup that is created for my Managed NodeGroup into my KarpenterSG using CDK. 

### Expected Behavior

Able to get the SecurityGroup ID assigned to the SelfManaged Node group  or the NodeGroup to take securityGroupID as an input. 

### Current Behavior

SecurityGroup is created automatically behind the scene and there is seemingly no way to get the SecurityGroup of the managed nodegroup. 

### Reproduction Steps

An alternative way to re-create this issue would be to create a EKS cluster with two SelfManaged NodeGroup. And try to allow full communication access between the two nodeGroups. 

### CDK CLI Version

2.61.1

### Node.js Version

v17.1.0.

### OS

Ubuntu 20.04.2

### Language

Python

### Language Version

Python 3.8.5

**Comment by pahud** [comment]
Hi

@gzus85 

The addNodegroupCapacity() method essentially creates a managed nodegroup rather than a "self-managed" nodegroup.
https://github.com/aws/aws-cdk/blob/a6fa5b88e1bd6a45b9c176a92eac20c702c894f4/packages/%40aws-cdk/aws-eks/lib/cluster.ts#L1712

If you need a "self-managed" nodegroup, you will need the `addAutoScalingGroupCapacity()` instead.
https://github.com/aws/aws-cdk/tree/main/packages/%40aws-cdk/aws-eks#self-managed-nodes

Please clarify if you need an aws-managed nodegroup or self-managed nodegroup. Thanks.

**Comment by gzus85** [comment]
> Hi
> 
> @gzus85
> 
> The addNodegroupCapacity() method essentially creates a managed nodegroup rather than a "self-managed" nodegroup.
> 
> https://github.com/aws/aws-cdk/blob/a6fa5b88e1bd6a45b9c176a92eac20c702c894f4/packages/%40aws-cdk/aws-eks/lib/cluster.ts#L1712
> 
> If you need a "self-managed" nodegroup, you will need the `addAutoScalingGroupCapacity()` instead. https://github.com/aws/aws-cdk/tree/main/packages/%40aws-cdk/aws-eks#self-managed-nodes
> 
> Please clarify if you need an aws-managed nodegroup or self-managed nodegroup. Thanks.

Thanks for the reply @pahud.

You are right, ideally I want Managed NodeGroup  and not "Self-Managed" as stated in the case description. 

Do you believe that I will not encounter the issue using "Self-Managed"  nodeGroups `addAutoScalingGroupCapacity()` ?

Anyway I will give it a go and see if I can achieve the intended network configuration using `addAutoScalingGroupCapacity()`.

**Comment by pahud** [comment]
@gzus85 

No I think you should create managed NG with `addNodegroupCapacity()` and specify the `launchTemplateSpec` for it.

With LaunchTemplate you should be able to specify your custom [SecurityGroupIds](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-launchtemplatedata.html#cfn-ec2-launchtemplate-launchtemplatedata-securitygroupids).
