### ISSUE TITLE
Allow Python unit testing for NestedStacks with Template.from_stack(state_machine_stack)

### ISSUE THREAD

**Issue by johancar** [aws/aws-cdk#23817]
### Describe the feature

I was looking for a python example of [unit testing](https://docs.aws.amazon.com/cdk/v2/guide/testing.html#testing_fine_grained) ( template = Template.from_stack(state_machine_stack) ) in cdk Python on nested stacks but could not find any. 

I'm using the example [here](https://github.com/aws-samples/aws-cdk-examples/tree/master/python/iot-msk-lambda-pipeline) for testing this, however I either receive error:
 
    `Nested stacks must be defined within scope of another non-nested stack`

or the unit test simply fails saying it cannot find the resource.

       ( RuntimeError: Error: Expected 2 resources of type AWS::EC2::SecurityGroup but found 0 )

Below test is working just fine when VPC is in the main stack ( MskDemoStack )
```
import aws_cdk as core
import aws_cdk.assertions as assertions
from msk_demo.msk_demo_stack import MskDemoStack

def test_vpc_count():
    app = core.App()
    stack = MskDemoStack(app, "MskDemoStack")
    template = assertions.Template.from_stack(stack)
    template.resource_count_is("AWS::EC2::VPC",1)
```

But how could I reference the nested stack from here? Or rather, how do I define stack to point to the nested stack MSKClient and then test for template.resource_count_is("AWS::EC2::SecurityGroup",2) ?

### Use Case

Use case is to easily perform a unit test on NestedStack resources, and being able to import the NestedStack in the same way main stacks are imported, e.g. 

```
import aws_cdk as core
import aws_cdk.assertions as assertions
from msk_demo.msk_demo_stack import MskDemoStack
```

### Proposed Solution

As a workaround, opening the synthesized template works, however my hope is that an easier method exists 

```
def test_stack_resource_count():
    with open(".\\cdk.out\\mskdemoMSKBrokerMskClient8D053BAA.nested.template.json") as f:
      stack = json.load(f) 
    template = assertions.Template.from_json(stack)
    template.resource_count_is("AWS::EC2::SecurityGroup", 2)
```

### Other Information

Found https://github.com/aws/aws-cdk/issues/19389 helpful,  and somewhat related.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.61.1 (build d319d9c)

### Environment details (OS name and version, etc.)

Windows 10 - 21H2

**Comment by peterwoodworth** [comment]
You would want to expose the nestedstack as a property of the stack that creates it, and refer to that when checking the template. Else, you could use escape hatches if you don't want to make the nestedstack a public property

If you need further help on this, please open a discussion and reference this issue 🙂

**Comment by gagipro** [comment]
> You would want to expose the nestedstack as a property of the stack that creates it, and refer to that when checking the template. Else, you could use escape hatches if you don't want to make the nestedstack a public property
> 
> If you need further help on this, please open a discussion and reference this issue slightly_smiling_face

Hello, if you can give us a sample or update example available? Thanks in advance.

how is it possible when we have 10 or 20 nested stacks?
