### ISSUE TITLE
[rds] Add more entries for AuroraPostgresEngineVersionmodule(module name): (short issue description)

### ISSUE THREAD

**Issue by danak95** [aws/aws-cdk#23810]
### Describe the feature

adding VER_11_7 to AuroraPostgresEngineVersion

### Use Case

I have aurora postgres cluster version 11.17, I need to deploy it using aws cdk, though its missing this version

### Proposed Solution

adding VER_11_7 to AuroraPostgresEngineVersion

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.27

### Environment details (OS name and version, etc.)

ubuntu 20.04

**Comment by pahud** [comment]
Thanks! You can just add an entry under here and submit a PR just like https://github.com/aws/aws-cdk/pull/20830.

https://github.com/aws/aws-cdk/blob/afce30a6e84a2f7e4eba499d3e71365a7939bef5/packages/%40aws-cdk/aws-rds/lib/cluster-engine.ts#L647

Is this something you want to pick up with?
