### ISSUE TITLE
aws-cognito: Cannot customise "Verify email" string in emailBody of UserPool userVerification

### ISSUE THREAD

**Issue by fdansey-ostmodern** [aws/aws-cdk#23828]
### Describe the bug

When I change the text in the "{##Verify Email##}" placeholder, e.g. to "{##verify your email##}", `cdk synth` and `cdk deploy` commands yield the error,

> Error: Verification email body must contain the template string '{##Verify Email##}'

This is incorrect as that documentation states that this string may be customised.
https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pool-settings-email-verification-message-customization.html

Help text in the AWS Cognito console reads:
> You can customize this message with HTML. "Verify email" is the text that will be displayed over the clickable link in the message. You can customize the "Verify email" string, but the variable - some text enclosed by "{##" and "##}" - must be kept in the message.

### Expected Behavior

I am able to change the `emailBody` property of a UserPool to include the placeholder of format, "{##Verify Your Email##}" **with any custom string** allowed by AWS Cognito.

### Current Behavior

`cdk synth` and `cdk deploy` commands yield the error,

> Error: Verification email body must contain the template string '{##Verify Email##}'
  at UserPool.verificationMessageConfiguration (<PATH>/node_modules/aws-cdk-lib/aws-cognito/lib/user-pool.js:1:10661)
  at new UserPool (<PATH>/node_modules/aws-cdk-lib/aws-cognito/lib/user-pool.js:1:4946)
  at new BlarnStack (<PATH>/blarn-stack/blarn-stack.ts:75:22)
  at Object.<anonymous> (<PATH>/stack-blarn.ts:12:1)
  at Module._compile (node:internal/modules/cjs/loader:1218:14)
  at Module.m._compile (<PATH>/node_modules/ts-node/src/index.ts:1455:23)
  at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
  at Object.require.extensions.<computed> [as .ts] (<PATH>/node_modules/ts-node/src/index.ts:1458:12)
  at Module.load (node:internal/modules/cjs/loader:1081:32)
  at Function.Module._load (node:internal/modules/cjs/loader:922:12)

### Reproduction Steps

Create a stack containing a cognito.UserPool resource with property,
```
userVerification: {
  emailSubject: "Please verify your email",
  emailBody: `<p>Hello Hottie Pingi!</p>
<p>Please {##verify your email address##}</p>`,
  emailStyle: cognito.VerificationEmailStyle.LINK,
}
```
Run `cdk synth` on the stack.

### CDK CLI Version

2.61.0 (build 34f4926)

### Node.js Version

v18.13.0

### OS

Ubuntu 22.04.1 LTS

### Language

Typescript

**Comment by pahud** [comment]
Thank you for your report.

Can you provide a minimal CDK app so I can deploy in my account and reproduce this issue?

**Comment by fdansey-ostmodern** [comment]
@pahud You can use a stack like this to reproduce the issue:
```
import {
  Stack,
  StackProps,
} from "aws-cdk-lib";
import { Construct } from "constructs";
import * as cognito from "aws-cdk-lib/aws-cognito";

export class BlarnStack extends Stack {
  constructor(
    scope: Construct,
    id: string,
    stackProps: StackProps
  ) {
    super(scope, id, stackProps);

    new cognito.UserPool(this, "Hottie" + "Pingi", {
      email: cognito.UserPoolEmail.withSES({
        fromEmail: `hello@blarn.com`,
        fromName: "Charlie",
        replyTo: `hello@blarn.com`,
        sesRegion: this.region,
        sesVerifiedDomain: "blarn.com",
      }),

      userVerification: {
        emailSubject: "Please verify your e-mail",
        emailBody: `<p>Welcome to blarn...</p>

<p>{##Custom Text##} and blarn your blarn blarn</p>`,
        emailStyle: cognito.VerificationEmailStyle.LINK,
      },
      accountRecovery: cognito.AccountRecovery.EMAIL_ONLY,
    });
  }
}
```

**Comment by pahud** [comment]
Yes you are right.

I think we have made it static here 

https://github.com/aws/aws-cdk/blob/64eb2bdb7126799e21bad03d668d91c7a501feb4/packages/%40aws-cdk/aws-cognito/lib/user-pool.ts#L1037

And we should change the logic here:

https://github.com/aws/aws-cdk/blob/64eb2bdb7126799e21bad03d668d91c7a501feb4/packages/%40aws-cdk/aws-cognito/lib/user-pool.ts#L1060-L1062

I am making it a p2. Any PR contribution would be welcome and appreciated!

**Comment by jadiaheno** [comment]
Hey @pahud, any update on this effort?

**Comment by antmarot** [comment]
I'm interested in this as well, any plan to fix this?

**Comment by jadiaheno** [comment]
Are you accepting PRs for this issue?

**Comment by GavinZZ** [comment]
Drafted a PR to fix this issue, included the bug fix and updating README with some more examples on `LINK` type verification method.
