### ISSUE TITLE
v2.60.0+: High memory usage when running cdk deploy

### ISSUE THREAD

**Issue by tobias-g** [aws/aws-cdk#23832]
### Describe the bug

Running `cdk deploy` using `aws-cdk` & `aws-cdk-lib` at v2.60.0 or above uses significant higher memory.

Using builds before this version for me took ~200mb while after takes in the region of 1.2gb (your numbers may vary but hopefully you should see a similar significant jump).

Noticed this when out CICD deploy runners were throwing `FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory`.

### Expected Behavior

Memory usage between versions does not change drastically.

### Current Behavior

After v2.60.0 an extra GB of memory seems to be eaten up.

### Reproduction Steps

Create cdk app (doesnt need to include a lot). In my instance I was creating an event bus.

```
const { Stack } = require('aws-cdk-lib');
const events = require('aws-cdk-lib/aws-events');

class CdkStack extends Stack {
  /**
   *
   * @param {Construct} scope
   * @param {string} id
   * @param {StackProps=} props
   */
  constructor(scope, id, props) {
    super(scope, id, props);

    // The code that defines your stack goes here
    const eventBus = events.EventBus.fromEventBusName(this, "ImportedEventBus", "some-events")
    new events.Rule(this, 'rule', {
      eventBus,
      eventPattern: {
        "detail-type": ["something"]
      },
    });
  }
}

module.exports = { CdkStack }
```

Setup package.json to use `aws-cdk` & `aws-cdk-lib` at v2.60.0.

```
{
  "name": "cdk",
  "version": "0.1.0",
  "bin": {
    "cdk": "bin/cdk.js"
  },
  "scripts": {
    "build": "echo \"The build step is not required when using JavaScript!\" && exit 0",
    "cdk": "cdk",
    "deploy": "cdk deploy --require-approval never --all",
    "test": "jest"
  },
  "devDependencies": {
    "aws-cdk": "2.60.0",
    "jest": "29.4.0"
  },
  "dependencies": {
    "aws-cdk-lib": "2.60.0",
    "constructs": "10.1.230"
  }
}
```
Run `top` or something to monitor your memory usage.

Run `npm i` and `npm run deploy` (cdk deploy).

Repeat with `v2.59.0` by updating package.json.

Run `top` or something to monitor your memory usage.

Run `npm i` and `npm run deploy` (cdk deploy).

Compare mem usage to first deploy.

### Possible Solution

Unsure but heres the diff if that helps 😅 https://github.com/aws/aws-cdk/compare/v2.59.0...v2.60.0

### CDK CLI Version

2.60.0

### Node.js Version

18

### OS

Mac

### Language

Typescript

**Comment by shifaizAcc** [comment]
We experienced the same behavior. CDK 2.60.0 is using significantly more memory.

**Comment by pahud** [comment]
This should be fixed in https://github.com/aws/aws-cdk/pull/23752 and available since 2.62.0.

Would you please verify if you still have this issue in 2.62.0 ?

**Comment by tmokmss** [comment]
I confirmed it's fixed now. (actually, even faster and less memory than 2.59.0 😄 )

**Comment by tobias-g** [comment]
Can also confirm memory issue is solved and seemingly even better than before. Closing this issue 🎉

**Comment by shifaizAcc** [comment]
I also confirm that it's fixed. Thanks!
