### ISSUE TITLE
custom-resource: Passthrough physicalResourceId when its not specified in onUpdate at AwsCustomResource

### ISSUE THREAD

**Issue by konokenj** [aws/aws-cdk#23843]
### Describe the feature

Currently, when using AwsCustomResource construct, users have to specify `physicalResourceId` in `onUpdate`. 
This limitation is brought by AwsCustomResource copies `onUpdate` (`physicalResourceId` is NOT mandatory) to `onCreate` (`physicalResourceId` is mandatory) when `onCreate` is not specified.

AwsCustomResource should be able to omit `physicalResourceId` in `onUpdate` with passthrough it from request. This is useful when users want to call an update API without resoure replacing. 

Some AWS APIs send empty response in update. This causes problem in below situation:

- Create API generates unpredictable IDs, and return it in response
  -  Users set `physicalResourceId: PhysicalResourceId.fromResponse()`
- Update API requires resource ID (not Name), and return **empty response**
  - Users provide resouce ID by `new PhysicalResourceIdReference()` in parameters
  - With empty response, users can't use `physicalResourceId: PhysicalResourceId.fromResponse()` or any ID generation

### Use Case

To create / update / delete resources that is not covered by CloudFormation. If API specification matches above conditions, this feature is critical. Like below:

- https://docs.aws.amazon.com/athena/latest/APIReference/API_UpdateNotebook.html
- https://docs.aws.amazon.com/singlesignon/latest/IdentityStoreAPIReference/API_UpdateUser.html

### Proposed Solution

Passthrough `physicalResourceId` from request to response in `onUpdate` when `physicalResourceId` is not specified.
To do that, update input check logic for `physicalResourceId`.

This change is not breaking, because it's not a problem if users can specify `physicalResourceId` in `onUpdate`.

| onCreate | onCreate.physicalResourceId | onUpdate | onUpdate.physicalResourceId | validation error now? | validation error after change? |
| --- | --- | ---| --- | :---: | :---: |
| AwsSdkCall | specified | AwsSdkCall | specified | no | no |
| AwsSdkCall | specified | AwsSdkCall | undefined | yes | **no <-** |
| AwsSdkCall | undefined | AwsSdkCall | undefined | yes | yes |
| AwsSdkCall | undefined | AwsSdkCall | specified | yes | yes |
| undefined (copied from onUpdate) | undefined | AwsSdkCall | specified | no | no |
| undefined (copied from onUpdate) | undefined | AwsSdkCall | undefined | yes | yes |
| AwsSdkCall | specified | undefined | undefined | no | no |
| AwsSdkCall | undefined | undefined | undefined | yes | yes |

### Other Information

Instead of omit `physicalResourceId` to passthrough, we can provide a property like `passthroughPhysicalResourceId: true`. But I think its more intuitive that omit `physicalResourceId`.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.61.1

### Environment details (OS name and version, etc.)

Node.js 16.13.0, MacOS 12.6.2

**Comment by khushail** [comment]
Hi @konokenj , thanks for reaching out. It would be great if you could  provide some more information on what you are trying to solve and the solution steps as well. Thanks.

**Comment by konokenj** [comment]
Hi @khushail, thank you for your ownership. 
The handler function is implemented to return from event object if PhysicalResourceId is unspecified, so I simply change Construct's error checking.
https://github.com/aws/aws-cdk/blob/9b2a45a6757c91011f47a6b3893cdfa0f4891002/packages/%40aws-cdk/custom-resources/lib/aws-custom-resource/runtime/index.ts#L153

I created a PR. 
https://github.com/aws/aws-cdk/actions/runs/4190162666/jobs/7263286767
