### ISSUE TITLE
aws_elasticloadbalancingv2: content type does not exist

### ISSUE THREAD

**Issue by watany-dev** [aws/aws-cdk#23842]
### Describe the bug

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_elasticloadbalancingv2-readme.html#convenience-methods-and-more-complex-actions

Apparently, ContentType used to exist.
https://github.com/aws/aws-cdk/blob/475dbef2e58ed5cf63cacf7d0c24cea4980b0ce2/packages/%40aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-listener-rule.ts#L115-L119

I checked the latest spec, and it seems that the previous spec is appropriate for L2 Construct.
https://github.com/aws/aws-cdk/blob/475dbef2e58ed5cf63cacf7d0c24cea4980b0ce2/packages/%40aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-listener-action.ts#L228-L240

### Expected Behavior

Let me enter this setting successfully.

```ts
listener.addAction('Fixed', {
  priority: 10,
  conditions: [
    elbv2.ListenerCondition.pathPatterns(['/ok']),
  ],
  action: elbv2.ListenerAction.fixedResponse(200, {
    contentType: elbv2.ContentType.TEXT_PLAIN,
    messageBody: 'OK',
  })
});
```

### Current Behavior

Cannot enter `elb.ContentType` because it does not exist

### Reproduction Steps

Same as ”Expected Behavior”

### Possible Solution

Add `elb.ContentType` as follows
https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_elasticloadbalancingv2.FixedResponseOptions.html#contenttype

### CDK CLI Version

any

### Node.js Version

any

### OS

any

### Language

Typescript

**Comment by peterwoodworth** [comment]
The bug here is just with the documentation, correct? We deprecated `ContentType` a while ago, so it is a mistake to still feature this enum in our README
