### ISSUE TITLE
aws_cdk.aws_ec2.InstanceClass: Support MAC2

### ISSUE THREAD

**Issue by samuel40791765** [aws/aws-cdk#23854]
### Describe the feature

I would like support for spinning up Mac ec2 Instances with ARM processors (M1).

### Use Case

Add it to the instance class definitions.

### Proposed Solution

Add `MAC2`(?) to the instance class definitions.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

1.97.0 (looking to upgrade soon)

### Environment details (OS name and version, etc.)

Ubuntu 20.04

**Comment by pahud** [comment]
Thank you.

We need to first explore if the instance type has been supported in cloudformation. Are you interested to submit a PR for this?

Adding the announcement URL here for reference:
https://aws.amazon.com/about-aws/whats-new/2022/07/general-availability-amazon-ec2-m1-mac-instances-macos/

**Comment by samuel40791765** [comment]
Just a minor update, I got my cdk script working by using [`CfnInstance`](https://docs.aws.amazon.com/cdk/api/v1/python/aws_cdk.aws_ec2/CfnInstance.html) instead. That should help indicate that cloudformation supports the new instance type? 
I'm quite unfamiliar with this codebase, so it would take me a while to figure things out. But new support for this shouldn't be too hard-pressing :).

**Comment by markshep-wbg** [comment]
The documentation for [AWS::EC2::LaunchTemplate LaunchTemplateData](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-launchtemplatedata.html) now lists `mac2-m2pro.metal` and `mac2.metal` among the allowed values for `InstanceType`.

I don't know how long `mac2.metal` has been supported, but I guess this announcement from yesterday relates to the `mac2-m2pro.metal` instance type:

https://aws.amazon.com/about-aws/whats-new/2023/10/general-availability-amazon-ec2-m2-mac-instances-mac-os/

So does that mean it's possible to implement this feature request now?

**Comment by thyming** [comment]
I think this needs to be reopened; I tried using the new instance types but they don't seem to match this regex:
https://github.com/aws/aws-cdk/blob/70dc4e8e8ca94694a732989d9c8233ab14c83b00/packages/aws-cdk-lib/aws-ec2/lib/instance-types.ts#L1652
