### ISSUE TITLE
aws_ec2: ARN for shared VPC has wrong account id

### ISSUE THREAD

**Issue by hugowschneider** [aws/aws-cdk#23865]
### Describe the bug

When looking up for a shared VPC with:
```python
vpc =  ec2.Vpc.from_lookup(self, "VPC", vpc_id=shared_vpc_id)
```
and then reading the vpc_arn

```python
print(vpc.vpc_arn)
```

Instead of having the correct ARN like `arn:aws:ec2:eu-west-1:YYYYYYYY:vpc/vpc-1234567890` where YYYYYY should be the account owning the VPC, I get `arn:aws:ec2:eu-west-1:XXXXXXXX:vpc/vpc-1234567890`, where XXXXX is the account where I am trying to deploy my stack.

### Expected Behavior

I would expect that the attrivute `vpc_arn` would return the correct VPC ARN referring to the owning account.

### Current Behavior

The stack refers to a wrong ARN.

### Reproduction Steps

- Share a VPC from account Y to account X
- In account X try to deploy a CDK stack where
- - This VPC is retrieve with `ec2.Vpc.from_lookup(self, "VPC", vpc_id=shared_vpc_id)`
- - Add a iam role policy where the resource is `vpc.vpc_arn`

### CDK CLI Version

2.61.1 (build d319d9c)

### Node.js Version

v16.17.0

### OS

MacOS

### Language

Python

### Language Version

Python 3.9.13

**Comment by pahud** [comment]
Yes you are right. 

I think we assume the vpc always belongs to the deploying account. We should consider the use case for a shared vpc.
https://github.com/aws/aws-cdk/blob/642b4ac8188561df9f31fde984e844ce4c98efd4/packages/%40aws-cdk/aws-ec2/lib/vpc.ts#L2166-L2170
