### ISSUE TITLE
How to build fulll stack rest api and microservices in ECS using CDK

### ISSUE THREAD

**Issue by j--wong** [aws/aws-cdk#2386]
Hi, 

I am currently evaluating CDK, and would like to know if the following scenario is possible.  I am unable to find a complete end-to-end example on how to achieve this so here's the question.

We are building a bunch of microservices on ECS that expose REST endpoints behind Amazon API Gateway and ALB.  

When a dev deploys any one of those microservices, I'd like the following to happen:

1. Create an API gateway (APIGW) with custom domain (if it doesn't already exist) (https://api.example.com) -- if gateway exists, no change
1. Create ACM certs with auto approval required for custom https domain (assume domain is registered with AWS and hosted zone exist in Route53)
1. Create an ALB (if it doesn't already exist).  If one exists, routes request to backend ECS service based on paths
1. Proxy requests from APIGW to ALB (if not already done)
1. Create ECS cluster (if it doesn't exist); if it does, deploy to the existing cluster
1. Create ECS service (non-fargate), task definition and all required target groups 
1. Create or update routing rules in ALB -> target group
1. Create or update ECS service discovery record (during deployment)
1. Create or update all necessary IAM roles for ECS service to access SSM param store, DDB tables, ES indices, and other AWS services they may need to access.

The key developer experience I'd like to achieve is when they deploy their microservice, they get a publicly accessible API endpoint (api-dev.example.com) without having to worry about provisioning VPC, Subnets, APIGW, ALB, ECS cluster, ACM Certs, IAM roles, ECS service, task definitions, etc.  which has been an overwhelming experience for a lot of devs who are new to AWS.

I'd like to provide seamless dev experience via shared stacks/constructs, and evaluating whether or not CDK is intended for this kind of scenario.

I hope everything makes sense.  If complete examples are not yet available,  any pointers on where to start would be greatly appreciated.

Thanks,
Josh

**Comment by janaka** [comment]
I cannot give an authoritative answer. But eyeballing your requirements I've got app with a couple of microservies up and running with a public ALB and DNS based service discovery (Cloud Map). I haven't codified all the IAM roles but the one that get auto created work. I've not tried APIGW yet. And I manually created the Fargate cluster (for no particular reason, just how I started). App Mesh support is definitely not there yet. 

My experience so far is that CDK API (constructs) are buggy. I guess it's reflective of the 0.29 versioning. I suspect at least some of that is because I'm using C# libs and there are some quirks still in the generator they use. So if you are using Type Script would probably have a better experience.

Once I have working code deploying infrastructure has been reliable.

**Comment by j--wong** [comment]
Thanks for the comment @janaka   I am using TypeScript.  Going through CDK source and https://github.com/aws-samples/aws-cdk-examples repo helps a bit.  Examples are small and bits and pieces.  I am just trying to put those pieces together to create a full stack example.

I'd like official guidance from CDK team on this, but I am slowly feeling my way through CDK and try to build something end to end entirely in CDK.  I might be able to share for others once I got something going.

**Comment by ChrisLahaye** [comment]
Hey,

I have recently build a similar infrastructure and wanted to share the following pointers:

2) Possible (`certificatemanager.DnsValidatedCertificate`), although importing certificates isn't currently supported
3) Possible (`elbv2.ApplicationLoadBalancer`, `elbv2.ApplicationTargetGroup`, `elbv2.ApplicationListenerRule`, `elbv2.ApplicationListenerCertificate`), create a load balancer with HTTP and HTTPS listener, default target group, and HTTPS certificate. For the HTTPS certificate we create a new ACM-signed certificate as importing (self-signed) certificates is not supported. Lastly, create a HTTP(S) listener rule with domain attribute for each service.
5) Possible (`ecs.Cluster`), deploying is done automatically after creating the task definitions
6) Possible (`ecs.Ec2Service`, `ecs.Ec2TaskDefinition`)
7) Possible (`elbv2.ApplicationTargetGroup`, `elbv2.ApplicationListenerRule`)
9) Possible

You might run into some missing constructs, but with some persistence you will be able to work around the limitations. Version 0.29 was a great release as it add some of the constructs that were missing for me.

**Comment by j--wong** [comment]
Thanks @ChrisLahaye  this is very helpful.  Reading CDK source and accompanying tests help too. 

One more question I have is what's the recommended approach for discovering / referencing existing resources in AWS?  Is there an extension point for custom context provider? https://github.com/awslabs/aws-cdk/tree/master/packages/aws-cdk/lib/context-providers

Thanks

**Comment by SomayaB** [comment]
Hi @j--wong, I'm so sorry it's taken so long to reply. Do you still need guidance around this?

**Comment by SomayaB** [comment]
Closing for now since there hasn't been a response in a while. Feel free to reopen.
