### ISSUE TITLE
@aws-cdk/aws-servicecatalogappregistry-alpha: ApplicationAssociator's hardcoded stack id is not meaningful and causes conflicts if user deploys multiple apps in the same account-region

### ISSUE THREAD

**Issue by jungle-amazon** [aws/aws-cdk#23861]
### Describe the bug

Note from user:

> By default, application_name value will be used as the stack ID and stack name. cdk.Stack uses construct path as the stack ID. When cdk.Stack has cdk.App as the parent, like in the TargetApplication use case, effectively the cdk.Stack construct ID is used as stack ID. We can mimic that behavior by using application_name value as the resulting cdk.Stack construct ID. For an example, if I use UserManagementBackend as the application name, I will get that value as both stack ID and stack name.

In addition, if a stage is not associated then currently an error is thrown. A warning should be displayed instead to continue with the rest of the child nodes, instead of stopping on the error.

### Expected Behavior

* If a stack's stage is not associated then a warning is displayed
* Stack name for CreateTargetApplication should not be statically defined. If the name is not provided by the user, we should use a dynamic identifier that prevents conflicts and has more meaning to the user.
* Stack name for ExistingTargetApplication should not be statically defined. If the name is not provided by the user, we should use a dynamic identifier that prevents conflicts and has more meaning to the user.

### Current Behavior

* If a stage is not associated then an error is thrown
* By default, the stack name for CreateTargetApplication and ExistingTargetApplication stacks are hardcoded to `ApplicationAssociatorStack` because the stack ID is hardcoded to that value (if stack name is not specified by the user then the stack id is used as the name). `ApplicationAssociatorStack` also doesn't provide meaningful details.

### Reproduction Steps

Sample code using the `ApplicationAssociator` to create a new application named `NewApplication`:
```
const autoApp = new appreg.ApplicationAssociator(app, 'TestApplicationAssociatorOne', {
    applications: [
        appreg.TargetApplication.createApplicationStack({
            applicationName: 'NewApplication',
            applicationDescription: 'Associated Application description us-west-2',
            env: { account: '11111111', region: 'us-west-2' },
        }),
    ],
});
```

Run CDK synthesis on this, and note that the stack name is `ApplicationAssociatorStack`

### Possible Solution

* Replace [stage association error](https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/aws-servicecatalogappregistry/lib/aspects/stack-associator.ts#L26) with warning.
* Replace the hard coding in stack name [here](https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/aws-servicecatalogappregistry/lib/target-application.ts#L93) with a reference to the application name.
* Replace the hard coding in stack name [here](https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/aws-servicecatalogappregistry/lib/target-application.ts#L120) with a reference to application ID.

### CDK CLI Version

2.50.0

### Node.js Version

16.5.0

### OS

macOS 12.6.2 Monterey

### Language

Typescript

**Comment by peterwoodworth** [comment]
Thanks for working with us on the PR for this 🙂

**Comment by alexpulver** [comment]
@jungle-amazon @peterwoodworth deprecating stack ID breaks the behavior of user being able to control stack ID in AWS CDK Toolkit output. This is important for project naming convention and avoid surprising output.

Using Stack ID I can set the AppRegistry application stack ID based on my project convention (UserManagementBackendApplication):
```
Supply a stack id (UserManagementBackendApplication, UserManagementBackendSandbox, UserManagementBackendToolchain) to display its template.
```

Removing Stack ID and using stack name generates a surprising name (from user perspective):
```
Supply a stack id (ApplicationAssociatorStack, UserManagementBackendSandbox, UserManagementBackendToolchain) to display its template.
```

Now that TargetApplication uses cdk.App as scope, using stack name as stack ID should address this issue. Do you want me to open a separate issue for this?

**Comment by jungle-amazon** [comment]
Yes, please create a separate github issue to so that we can track your issue. 

If I understand correctly, the new stack name references the application name which was part of the last fix, but in your use case you need stack id to have this default value as well, not just the stack name. We can look into this change.

**Comment by alexpulver** [comment]
@jungle-amazon thanks for circling back! I opened the issue to clarify the ask: https://github.com/aws/aws-cdk/issues/24160
