### ISSUE TITLE
@aws-lambda-nodejs: missing aws-sdk-v3 libs at runtime

### ISSUE THREAD

**Issue by dambaron** [aws/aws-cdk#23873]
### Describe the bug

After bumping aws-cdk & aws-cdk-lib from `2.51.1` to `2.62.1` multiple lambdas are failing while performing DynamoDB calls.

The log messages look like:

```typescript
{type: "INTERNAL_SERVER_ERROR", message: "Cannot read properties of undefined (reading 'ALL_NEW')"}

message:  "Cannot read properties of undefined (reading 'ALL_NEW')"

type: "INTERNAL_SERVER_ERROR"
```

All lambda perform similar DynamoDB commands like this :

```typescript
const updateCommand = new UpdateCommand({
      ...
      ReturnValues: ReturnValue.ALL_NEW,
 })
```

It seems like that the ReturnValue enum is missing from the package asset.
It is confirmed by the fact that the package asset went from 900ko to 300ko and the announcement that the aws-sdk-v3 is now included within the NodeJs runtime.

Knowing that, how should the lambdas be packages to avoid this behavior ?

### Expected Behavior

The aws-sdk-v3 libs should be bundled in the lambda asset and / or be available at runtime.

### Current Behavior

The aws-sdk-v3 libs are not available at runtime

### Reproduction Steps

Build a Node.js lambda with the 18.x runtime and perform a simple DynamoDB update

### CDK CLI Version

2.62.1

### Node.js Version

v18.12.1

### OS

N/A

### Language

Typescript

### Language Version

4.9.4

**Comment by mattiamatrix** [comment]
I think there is an issue with `aws-sdk-v3` and Enums. I am having the same problem with `StandardUnit.Count `from `@aws-sdk/client-cloudwatch`.

**Comment by mattiamatrix** [comment]
Yep, looks like it works again with

```ts
const bundling: BundlingOptions = {
    minify: true,
    sourceMap: true,
    externalModules: [],
};
```

Feeling like a breaking change. Not impressed with this change.

**Comment by mrgrain** [comment]
> Feeling like a breaking change. Not impressed with this change.

I can understand where you are coming from. From our perspective `NodejsFunction` by default does not bundle the SDK already available in Lambda. That was documented but explicitly only for sdk v2. The SDK change in the Node18 lambda caught us off guard and was missed when originally adding Node 18 support. 

I'll take your feedback on for future changes.

**Comment by mattiamatrix** [comment]
Thank you @mrgrain. But I am still very confused by the behaviour here. 
Looking at https://github.com/aws/aws-cdk/blob/main/packages/@aws-cdk/aws-lambda-nodejs/lib/bundling.ts#L127-L130 doesn't help either.

Looking at @peterwoodworth changes to the tags,  it seems like something needs to be done. Correct?

**Comment by mrgrain** [comment]
Hey @mattiamatrix Sorry this behavior isn't clear yet. Does the docstring help at all?

```
A list of modules that should be considered as externals (already available
in the runtime).

@default - ['aws-sdk'] if the runtime is < Node.js 18.x, ['@aws-sdk/*'] otherwise.
```

Another way of saying this could be: "By default `NodejsFunction` excludes the major SDK version that is provided with the Runtime version. For a list of Runtime and SDK versions, see: https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html"

We are very open to improving the docs in this regard.

---
Regarding the tags Peter added - this is on me. I meant to close the issue after a bit and forgot to do this. I have done this now.
