### ISSUE TITLE
.NET CDK libraries missing inline docs in VS Code.

### ISSUE THREAD

**Issue by janaka** [aws/aws-cdk#2388]
**Describe the bug**
Inline documentation for classes, methods, properties etc. not showing in VS Code. When I hover over a construct method, for example, I expect to see inline reference documentation along with the method signature. This documentation is now appearing. The TS code seems to have the doc comments. JSII appears to have the ability to convert them to C# doc comment XML. Maybe there's an issue with the Nuget publish.

![image](https://user-images.githubusercontent.com/51779/56863258-ee621f00-69d1-11e9-9e5b-20a5a8a1bf59.png)

**To Reproduce**
In VS Code hover over a CDK construct method. 

**Expected behaviour**
I expect the inline docs to be displayed like this.

![image](https://user-images.githubusercontent.com/51779/56863276-1a7da000-69d2-11e9-93ff-52eab456bbb5.png)

**Version:**
 - macOS
 - C#
 - CDK Version 0.29.0
 - VS Code 1.33.1

**Comment by SomayaB** [comment]
Hi, I apologize for the late reply. Are you still having this issue?

**Comment by SomayaB** [comment]
Closing this issue since there hasn't been activity on it in a while. Feel free to reopen if you are still experiencing this issue.
