### ISSUE TITLE
cli: slow for even basic matters but also  synth/deploy

### ISSUE THREAD

**Issue by erikerikson** [aws/aws-cdk#23883]
### Describe the bug

The CDK CLI is unreasonably slow.

Running `cd /; time cdk --help` resulted in:

```
cdk --help  5.84s user 1.35s system 106% cpu 6.776 total
```

### Expected Behavior

more or less immediate (ms) printing of help docs

### Current Behavior

printing the help docs takes multiple seconds

### Reproduction Steps

`time cdk --help`

### CDK CLI Version

2.61.1 (build d319d9c)

### Node.js Version

v18.9.1

### OS

Ubuntu 22.04.1 LTS

### Language

Typescript

### Language Version

zsh

**Comment by tmokmss** [comment]
It is fixed in the latest CDK :) https://github.com/aws/aws-cdk/issues/23832#issuecomment-1406696918

**Comment by erikerikson** [comment]
Confirmed.  Thank you very much!
