### ISSUE TITLE
Validation bug in servicediscovery.service constructor 

### ISSUE THREAD

**Issue by janaka** [aws/aws-cdk#2389]
**Describe the bug**
When creating a cloud map service the following error is thrown. 

```Cannot specify `routingPolicy` or `dnsRecord` when using an HTTP namespace.```

https://github.com/awslabs/aws-cdk/blob/e5e4a3d177d8b027663ee42e6d704bbbc3c43b7a/packages/%40aws-cdk/aws-servicediscovery/lib/service.ts#L168

This seems incorrect especially given one cannot create a namespace that is not HTTP. 

**To Reproduce**
```csharp
var janakaExperimentsClusterRef = Cluster.Import(this, "janaka-experiments-cluster", new ClusterImportProps
{
    ClusterName = "janaka-experiments",
    Vpc = defaultVpcEuw1,
    SecurityGroups = new SecurityGroupImportProps[] { },
    DefaultNamespace = new NamespaceImportProps // need this set if cloud map enabling fargate services.
    {
        NamespaceName = "local",
        Type = Amazon.CDK.AWS.ServiceDiscovery.NamespaceType.DnsPrivate
    }
});

var fargateService = new FargateService(this, "the-fargate-service", new FargateServiceProps
{
    Cluster = janakaExperimentsClusterRef,
    TaskDefinition = fargateTaskDef,
    ServiceName = props.MicroserviceName,
    SecurityGroup = secGroup,
    DesiredCount = 1,
    AssignPublicIp = true, // need this for container pull to work.
    ServiceDiscoveryOptions = new ServiceDiscoveryOptions
    {
        DnsRecordType = DnsRecordType.A,
        DnsTtlSec = 60,
        Name = props.MicroserviceName, // the name given to the cloud map service created and attached to this fargate service.
    }
});
```

**Expected behavior**
Given an HTTP and DNS namespace, I expect to be able to create a cloud map service and associate it with the Fargate service such that the Fargate tasks auto-register with cloud map.

I expect this error to be thrown if trying to add a `routingPolicy` or `dnsRecord` to an API only namespace.

It seems like the namespace type isn't being imported correctly. If defined manual in the import it seems to work. I expect the type to be auto-set correctly during an import by name/id/arn

**Version:**
 - macOS
 - C#
 - CDK Version 0.29.0

**Comment by SomayaB** [comment]
Hi, I apologize for the late reply. Are you still experiencing this issue?

**Comment by SomayaB** [comment]
Closing this issue since there hasn't been activity on it in a while. Feel free to reopen.
