### ISSUE TITLE
lambda: enable RuntimeManagementConfig

### ISSUE THREAD

**Issue by watany-dev** [aws/aws-cdk#23890]
### Describe the feature

Introducing AWS Lambda runtime management controls
https://aws.amazon.com/jp/blogs/compute/introducing-aws-lambda-runtime-management-controls/

https://docs.aws.amazon.com/lambda/latest/dg/runtimes-update.html

### Use Case

```ts
const fn = new lambda.Function(this, 'MyFunction', {
  runtime: lambda.Runtime.NODEJS_18_X,
  runtimeManagement: {
    arn: "arn:aws:lambda:ap-northeast-1::runtime:07a48df201798d627f2b950f03bb227aab4a655a1d019c3296406f95937e2525",
    mode: lambda.updateRuntimeOn.AUTO
  }
  handler: 'index.handler',
  code: lambda.Code.fromAsset(path.join(__dirname, 'lambda-handler')),
});
```

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

v2.62.0

### Environment details (OS name and version, etc.)

any

**Comment by pahud** [comment]
Awesome! Thank you for this PR contribution! @watany-dev
