### ISSUE TITLE
contributing: Unable to buildup on Windows

### ISSUE THREAD

**Issue by padaszewski** [aws/aws-cdk#23910]
### Describe the bug

Hi,
Newly I wanted to do a contribution to CDK, but I was unable to get to that point I can start hacking.
I followed the [tutorial done by Pahud](https://www.youtube.com/watch?v=JjAMvBzSrEQ), but I failed to execute the `buildup` script. I am working on Windows with IntelliJ. For the `buildup` I've uset the Git Bash.

I tried the following:
```bash
$ cd packages/@aws-cdk/aws-ec2
$ ../../../scripts/buildup
```
I got following problems:

1. `tools/@aws-cdk/node-bundle`: 
```bash
$ npx projen build
👾 unable to evaluate environment variable PATH=$(npx -c "node -e \"console.log(process.env.PATH)\""): unknown error
```
After some googling I found the following issue: https://github.com/projen/projen/issues/448
In the corresponding PR I've realized I have to change in `tasks.json` tne `env` to this (which is highly unwanted!):
```json
"env": {
    "PATH": "$(npx -c \"node -e console.log(process.env.PATH)\")"
  }
```
Then I got this step working. Next problem:

2. `tools/@aws-cdk/pkg-lint`: 
```bash
yarn run v1.22.19
$ tsc -b && eslint . --ext=.ts && chmod +x bin/pkglint

Oops! Something went wrong! :(

ESLint: 7.32.0

Error: Error while loading rule '@aws-cdk/invalid-cfn-imports': ENOENT: no such file or directory, open 'C:\...\aws-cdk\tools\@aws-cdk\pkglint\bin\pkglint.ts\package.json'
```
Okay, what helped? Commenting out the rule `'@aws-cdk/invalid-cfn-imports': [ 'error' ],` in `eslintrc.js`
Again: unwanted!

Next:

3. `packages\@aws-cdk\cloud-assembly-schema`:
```bash
yarn run v1.22.19
$ cdk-build
Command "C:\...\aws-cdk\node_modules\jsii\bin\jsii" not found.
Error: C:\...\aws-cdk\node_modules\jsii\bin\jsii --silence-warnings=reserved-word --add-deprecation-warnings exited with error code 1
Build failed.!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

After that I had no more energy to get this running and I feel something has to be done in order to get this easiliy running on a windows machine.

Ah, one more thing: event `git clone repo` does not work properly on Windows because of some too long filenames. Changing the git config helped.

I'm trying now with the contenerized approach for VSCode, but it needs to download much stuff, so I took the time to write this issue, hopefully it can be addressed and I can contribute writing the code in IntelliJ.

Edit: VSCode Container failing as well:
`error An unexpected error occurred: "EPERM: operation not permitted, chmod '/workspaces/aws-cdk/packages/@aws-cdk-testing/cli-integ/node_modules/.bin/cdk-build'".`

### Expected Behavior

Install process on Windows is simple and causes no pain.

### Current Behavior

Install process on Windows is complicated and causes emotional damage.

### Reproduction Steps

Just try to prepare the environment on Windows in order to contribute to CDK. After `yarn install` proceed e.g. with that:
```bash
$ cd packages/@aws-cdk/aws-ec2
$ ../../../scripts/buildup
```
Git Bash is of course allowed for the invoking the `*.sh` scripts :)

### CDK CLI Version

2.61.0 (build 34f4926)

### Node.js Version

v18.13.0

### OS

Windows

### Language

Typescript

**Comment by pahud** [comment]
Hi @padaszewski 

Thanks for watching my video. I have very limited experience to build aws-cdk in Windows environment. However, if you insist on working in a Windows environment, I would suggest you use Gitpod online IDE to open the aws-cdk repo and follow the steps below:


1. in aws-cdk repo root, run `yarn install` to install all development dependencies and libraries.
2. cd packages/@aws-cdk/aws-ec2
3.  ../../../scripts/buildup

It should work as expected.

Feel free to reach out to me directly on cdk.dev if you encounter any further errors. I hope to help you successfully build your development environment.

**Comment by padaszewski** [comment]
Hi @pahud 
Thanks for the great video and responding here.
I'll start with Gitpod (like in the video), but I would love to work on my local machine and my favourite IDE.

Is there someone who has experiance with working on windows?

**Comment by pahud** [comment]
I agree we should improve documents on cdk contributing guide on windows. I am making this p2 now. Also consider to call out in the cdk.dev `#constributing` channel. We probably have some community contributors with relevant experience on windows but AFAIK mostly contributors on Mac or Linux.

**Comment by thefat32** [comment]
Anyone interested in developing on Windows can use VSCode Dev Container command `Clone Repository in Container Volume`

![image](https://github.com/aws/aws-cdk/assets/10998637/307aca27-40bd-437c-bde5-24ed0a0f3a71)

Follow instructions, this will clone your repo inside a Docker volume and attach it to the container.

Drawback: you cannot access files from Windows

NOTE: if getting

```
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
```

just adjust memmory size using `export NODE_OPTIONS="--max-old-space-size=8192"`
