### ISSUE TITLE
emr-create-cluster: uses EMR V1 policies instead of V2

### ISSUE THREAD

**Issue by davidjgolding** [aws/aws-cdk#23915]
### Describe the bug

AWS documentation states that V1 policies are on the deprecation path, however, they are still used within CDK. For example, by default, the [service role created](https://github.com/aws/aws-cdk/blob/d319d9ccba17d0ef8b566e0c68af1f622518f254/packages/%40aws-cdk/aws-stepfunctions-tasks/lib/emr/emr-create-cluster.ts#L345) uses `AmazonElasticMapReduceRole` instead of `AmazonEMRServicePolicy_v2`. Consequently, I have received warnings that these policies are going to be deprecated and that I should update them.

### Expected Behavior

V2 policies should be used as documented [here](https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-managed-iam-policies.html).

### Current Behavior

V1 policies are used.

### Reproduction Steps

N/A

### CDK CLI Version

2.51.0

### Node.js Version

v16.19.0

### OS

macOS

### Language

Typescript

**Comment by pahud** [comment]
Thank you and agree. Are you interested to submit a PR for this?

**Comment by davidjgolding** [comment]
Hey @pahud - I don't currently have the capacity to do this so it would be great if you could help!
