### ISSUE TITLE
aws-ecr-assets: toomanyrequests

### ISSUE THREAD

**Issue by pwrmiller** [aws/aws-cdk#23923]
### Describe the bug

When using CDK to build docker images, docker pulls from ECR seem to be failing

```
Step 1/19 : FROM public.ecr.aws/docker/library/gradle:jdk11 as gradle
toomanyrequests: Rate exceeded
[100%] fail: docker build --tag <some_tag> --platform linux/amd64 . exited with error code 1: toomanyrequests: Rate exceeded

 ❌ Building assets failed: Error: Building Assets Failed: Error: Failed to build one or more assets. See the error messages above for more information.
    at buildAllStackAssets (/usr/local/lib/node_modules/aws-cdk/lib/index.js:330:116673)
```

This only seems to happen when called from CI. I have confirmed that I am authenticated to ECR in my account (and this does not seem to make a difference). 

### Expected Behavior

I expected pulls from ECR public repositories to succeed without a rate limiting issue. 

### Current Behavior

I received a `toomanyrequests` rate limiting error. 

### Reproduction Steps

- Create a container image using `from_docker_image_asset`

```python
ecs.ContainerImage.from_docker_image_asset(
                asset=DockerImageAsset(
                    self,
                    "SomeImage",
                    directory=str(Path(__file__).parent / "task" / "container"),
                    platform=Platform.LINUX_AMD64,
                )
            )
```

- run `cdk synth` then `cdk deploy`
- observe the toomanyrequests error as shown above.  
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

### Possible Solution

It's not clear why this might be working locally but not from CI (Azure Devops in our case). At the time of the `cdk deploy` we were only attempting to build the container for a single environment, so this is unexpected. 

We might consider moving away from `DockerImageAsset` if it continues not to work properly. 

### Additional Information/Context

- python version might not be relevant, since the Docker asset is built during the `cdk deploy`
- if anything has changed in ECR lately to prevent or rate limit docker pulls, it might be relevant to this issue 

### CDK CLI Version

2.60.0 (build 2d40d77)

### Node.js Version

16.x

### OS

Ubuntu 22.04

### Language

Python

### Language Version

3.9.6

**Comment by pahud** [comment]
Thanks for the report. I have no experience with Azure DevOps but this seems to be an common error when unauthenticated. How do you authenticate and login in ECR public in Azure DevOps?

**Comment by pwrmiller** [comment]
Your comment caused me to look at the pipeline - it turns out that I was mistakenly authenticating to a private ECR repository rather than ECR Public. 

After changing the pipeline to authenticate to ECR public, everything works as expected. Thank you for your prompt and useful help @pahud
