### ISSUE TITLE
cdk init: Upgrade from netcoreapp3.1 to net6.0

### ISSUE THREAD

**Issue by berviantoleo** [aws/aws-cdk#23921]
### Describe the feature

Any plan to upgrade the template from netcoreapp3.1 to net6.0? .NET Core 3.1 has reached the end of life for the support. Is it cdk support net6.0? If yes, I think it will be good to use net6.0.

### Use Case

I want to reduce the warning.

![warnings](https://user-images.githubusercontent.com/15927349/215637021-8b08f0e9-151e-42ed-8138-fbb91e23f634.png)

### Proposed Solution

Upgrade to net6.0 for the template

### Other Information

I expect to update this [line](https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk/lib/init-templates/sample-app/csharp/src/%25name.PascalCased%25/%25name.PascalCased%25.template.csproj#L5)

### Acknowledgements

- [X] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### CDK version used

2.62.2

### Environment details (OS name and version, etc.)

Linux Manjaro 22.0.1 and .NET 6

**Comment by peterwoodworth** [comment]
Thanks for the PR - copying over from the PR for visibility here too, we will want to update jsii first

**Comment by berviantoleo** [comment]
> Thanks for the PR - copying over from the PR for visibility here too, we will want to update jsii first

Sure, I think we don't need to rush about it. I would like to help update too.
