### ISSUE TITLE
route53: CrossAccountZoneDelegationRecord does not work in aws-iso(-b) partitions

### ISSUE THREAD

**Issue by liuxh0** [aws/aws-cdk#23948]
### Describe the bug

This construct fails in aws-iso and aws-iso-b partitions because it uses an older version of AWS SDK provided by lambda runtime. A wrong route53 endpoint is configured.

AWS SDK fixed the issue in https://github.com/aws/aws-sdk-js/pull/4056/commits/09c3b4b16eecd4398834591f14202329da5cfca6.

### Expected Behavior

Deploying the construct to aws-iso and aws-iso-b partitions does not result an error.

### Current Behavior

It fails with error message: `Failed to create resource  UnknownEndpoint: Inaccessible host 'route53.us-iso-west-1.c2s.ic.gov' at port 'undefined' This service may not be available in the 'us-iso-west-1' region at request ENOTFOUND_ERROR `

### Reproduction Steps

N/A

### Possible Solution

- Use latest AWS SDK version
- Override route53 endpoint for selected regions

### CDK CLI Version

2.44.0

### Node.js Version

14

### OS

MacOS

### Language

Typescript

**Comment by tim-finnigan** [comment]
@liuxh0 was this not fixed in https://github.com/aws/aws-cdk/pull/23082? Here is the issue associated with that PR: https://github.com/aws/aws-cdk/issues/23081
