### ISSUE TITLE
Error: Failed to publish one or more assets

### ISSUE THREAD

**Issue by ttais2017** [aws/aws-cdk#23945]
### Describe the bug

![image](https://user-images.githubusercontent.com/26426283/215964280-64b4ba1d-7e38-47ea-8152-e73b6ec77e28.png)

### Expected Behavior

The deployment should be succesfull 

### Current Behavior

After update to the latest cdk version on my machine, i'm getting this error before the deployment start.  Everything was working with the version 2.59.0

### Reproduction Steps

After install cdk 2.63.0, the deployment of assets is not working  :(

### CDK CLI Version

2.63.0 (build 7f4e35e)

### Node.js Version

{   npm: '6.14.11',   ares: '1.16.1',   brotli: '1.0.9',   cldr: '37.0',   icu: '67.1',   llhttp: '2.1.3',   modules: '83',   napi: '7',   nghttp2: '1.41.0',   node: '14.16.0',   openssl: '1.1.1j',   tz: '2020a',   unicode: '13.0',   uv: '1.40.0',   v8: '8.4.371.19-node.18',   zlib: '1.2.11' }

### OS

Windows

### Language

Java

### Language Version

Java 17.0.5

**Comment by ttais2017** [comment]
Here a screen-shot with the same project using cdk 2.59.0

![image](https://user-images.githubusercontent.com/26426283/215966020-b73b1f4f-91dc-4a54-88f2-2ef28523341b.png)

**Comment by pahud** [comment]
closing by https://github.com/aws/aws-cdk/pull/23994
