### ISSUE TITLE
(aws_events_targets): Confusing installLatestAwsSdk warning

### ISSUE THREAD

**Issue by mvs5465** [aws/aws-cdk#23956]
### Describe the issue

We are using the aws_events_targets module and this appears to be creating a custom resource. Specifically working with cloudtrail events for the `onEvent` static method: https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_cloudtrail.Trail.html#static-onwbreventscope-id-options

When compiling, there is a warning:

```
installLatestAwsSdk was not specified, and defaults to true. You probably do not want this. Set the global context flag '@aws-cdk/customresources:installLatestAwsSdkDefault' to false to switch this behavior off project-wide, or set the property explicitly to true if you know you need to call APIs that are not in Lambda's built-in SDK version.
```

What is the intended way to set this flag? Is this something the user should set? I see this PR from 3 weeks ago saying the default value is now false: https://github.com/aws/aws-cdk/pull/23591

### Links

https://github.com/aws/aws-cdk/pull/23591

**Comment by peterwoodworth** [comment]
Hey @mvs5465, could you please provide sample code which will generate this issue?

**Comment by mvs5465** [comment]
@peterwoodworth Sure, this will generate the warning as of cdk 2.63.0:

```
import * as cdk from 'aws-cdk-lib';
import { aws_cloudtrail as ct, aws_events_targets as targets, aws_logs as logs } from 'aws-cdk-lib';

export class LoginEventStack extends cdk.Stack {

  constructor(scope: cdk.App, id: string, props: cdk.StackProps) {
    super(scope, id, props);

    const loginEvent = ct.Trail.onEvent(this, 'login-event', {
      eventPattern: {
        source: ['aws.signin'],
        detailType: ['AWS Console Sign In via CloudTrail'],
        detail: {
          eventName: [
            'ConsoleLogin',
          ],
        },
      },
    });

    loginEvent.addTarget(new targets.CloudWatchLogGroup(new logs.LogGroup(this, 'login-event-logs')));
  }
}
```

**Comment by peterwoodworth** [comment]
Thanks for the code @mvs5465, that was really easy to copy and paste and reproduce the warning 🙂 

Were you able to successfully disable the warning by setting the flag in `cdk.json`?

**Comment by mvs5465** [comment]
Yes @peterwoodworth thanks for the fantastic link! We added the rest of the recommended feature flags too. The warning is gone and we got a few other improvements out of that. Appreciate it.
