### ISSUE TITLE
s3 lifecycle policy: the storageclass type generated by cdk does not match cfn storageclass type.

### ISSUE THREAD

**Issue by hulu-xu** [aws/aws-cdk#23950]
### Describe the bug

An error occured when creating bucket with lifecycle policy: `The XML you provided was not well-formed or did not validate against our published schema`

<img width="1275" alt="image" src="https://user-images.githubusercontent.com/26135307/216016584-a59c96cf-9c93-4f0e-a77d-b0367ee2bb03.png">

It look like the storageclass type generated by cdk does not match cfn storageclass type.
cdk  storageclass type: https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_s3/StorageClass.html#aws_cdk.aws_s3.StorageClass
cfn  storageclass type: https://docs.aws.amazon.com/zh_cn/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-lifecycleconfig-rule-transition.html

### Expected Behavior

cdk storageclass type should consistent with cfn storageclass type.

### Current Behavior

cdk storageclass type is not consistent with cfn storageclass type.

### Reproduction Steps

method we called : https://docs.aws.amazon.com/cdk/api/v1/python/aws_cdk.aws_s3/Bucket.html#aws_cdk.aws_s3.Bucket.add_lifecycle_rule

### CDK CLI Version

2.59.0

### Node.js Version

16

### OS

linux

### Language

Python

**Comment by peterwoodworth** [comment]
Hey @hulu-xu, the enum names differ slightly, however the [actual values](https://github.com/aws/aws-cdk/blob/7f4e35e278a646f504bbcf401e680f0a2ac18e36/packages/%40aws-cdk/aws-s3/lib/rule.ts#L198) match what the CloudFormation documentation shows. The error message doesn't seem to suggest that this is the issue either, could you please provide example code which will run into this error? Thanks

**Comment by hulu-xu** [comment]
@peterwoodworth  It's fixed when using actual values, Thank you!
