### ISSUE TITLE
aws-cdk: VPC Flowlog bucket `destinationOptions` property keys are in camelCase in snapshot tests and synthesised templates after v2.56.1

### ISSUE THREAD

**Issue by therealvio** [aws/aws-cdk#23964]
### Describe the bug

In `aws-cdk-lib` v2.56.1 and `aws-cdk` 2.56.1 there is an issue where the VPC Flowlog `DestinationOptions` properties are in camelCase instead of PascalCase in synthesised Cloudformation Templates and snapshot tests.

This issue makes the template invalid as the properties for `DestinationOptions` are invalid.

Below is a screenshot of failing tests exhibiting this issue:
![image](https://user-images.githubusercontent.com/41095688/216220043-c196fbd6-2f8a-4095-a590-0529324571f4.png)

### Expected Behavior

Flowlog `DestinationOptions` properties should be in PascalCase, as below:

```
  "FlowLog": {
   "Type": "AWS::EC2::FlowLog",
   "Properties": {
    "ResourceId": {
     "Ref": "TransitGateway"
    },
    "ResourceType": "TransitGateway",
    "DestinationOptions": {
     "FileFormat": "plain-text",
     "HiveCompatiblePartitions": true,
     "PerHourPartition": true
    },
```

### Current Behavior

Flowlog `DestinationOptions` properties are in camel case, as below:

```
  "FlowLog": {
   "Type": "AWS::EC2::FlowLog",
   "Properties": {
    "ResourceId": {
     "Ref": "TransitGateway"
    },
    "ResourceType": "TransitGateway",
    "DestinationOptions": {
     "fileFormat": "plain-text",
     "hiveCompatiblePartitions": true,
     "perHourPartition": true
    },
```

### Reproduction Steps

```
import {
  CfnFlowLog,
  FlowLogDestinationType,
  FlowLogFileFormat,
} from "aws-cdk-lib/aws-ec2"

    const transitGateway = new CfnTransitGateway(this, "TransitGateway", {
      autoAcceptSharedAttachments: "enable",
      tags: [{ key: "Name", value: "my-tgw" }],
    })

    const flowLogBucket = Bucket.fromBucketName(
      this,
      "FlowLogBucket",
     "<NAME-OF-YOUR-BUCKET>"
    )

    const flowLog = new CfnFlowLog(this, "FlowLog", {
      resourceId: transitGateway.ref,
      resourceType: "TransitGateway",
      destinationOptions: {
        fileFormat: FlowLogFileFormat.PLAIN_TEXT,
        hiveCompatiblePartitions: true,
        perHourPartition: true,
      },
      logDestination: `<ARN-OF-YOUR-BUCKET>`,
      logDestinationType: FlowLogDestinationType.S3,
    })
```

### Possible Solution

The issue seems to have been introduced since version [2.56.1](https://github.com/aws/aws-cdk/compare/v2.56.0...v2.56.1).

### CDK CLI Version

2.56.1 (build 9329a73)

### Node.js Version

v18.12.1

### OS

MacOS v 12.6.2

### Language

Typescript

### Language Version

Typescript (4.9.4)

**Comment by peterwoodworth** [comment]
Thanks for reporting this @therealvio,

Prior to this change, the way to specify this was like the following:

```
    const transitGateway = new CfnTransitGateway(this, "TransitGateway", {
      autoAcceptSharedAttachments: "enable",
      tags: [{ key: "Name", value: "my-tgw" }],
    })

    const flowLogBucket = Bucket.fromBucketName(
      this,
      "FlowLogBucket",
     "<NAME-OF-YOUR-BUCKET>"
    )

    const flowLog = new CfnFlowLog(this, "FlowLog", {
      resourceId: transitGateway.ref,
      resourceType: "TransitGateway",
      destinationOptions: {
        FileFormat: FlowLogFileFormat.PLAIN_TEXT,
        HiveCompatiblePartitions: true,
        PerHourPartition: true,
      },
      logDestination: `<ARN-OF-YOUR-BUCKET>`,
      logDestinationType: FlowLogDestinationType.S3,
    })
```

This is because previously, there was no DestinationsOptionProperty - that prop used to take in an object of type `any`, but was changed in `2.55` (i believe it was `2.55`) to include a new property due to CloudFormation pushing an update, which users would now have to account for. We decided to revert that change (and other similar ones) back to previous behavior, and we don't plan on this changing in the future. 

Thanks for your feedback on this, I hope this comment will help you move forward in your development 🙂
