### ISSUE TITLE
aws-cdk-lib: Running commands like `cdk diff FooStack`and `cdk deploy FooStack` results in all stacks being synthesized in cdk.out directory, not just `FooStack`

### ISSUE THREAD

**Issue by pv93** [aws/aws-cdk#23973]
### Describe the feature

When we run commands like `cdk diff FooStack`, we are looking for a way to only synthesize the stack `FooStack` instead of all stacks found in `bin/cdk.ts`.

### Use Case

We have multiple versions of our stack in our `bin/cdk.ts` file for different environments/regions, as such:

```typescript
#!/usr/bin/env node
import 'source-map-support/register';
import * as cdk from 'aws-cdk-lib';
import { FooStack } from '../lib/stack';

const app = new cdk.App();

new FooStack(app, 'FooStackProductionUsEast1', {
// ...parameters go here
});


new FooStack(app, 'FooStackProductionUsWest1', {
// ...parameters go here
});


new FooStack(app, 'FooStackStagingUsEast1', {
// ...parameters go here
});


new FooStack(app, 'FooStackStagingUsWest1', {
// ...parameters go here
});
```

In our CI/CD system, we run `cdk diff` and `cdk deploy` against one stack at a time, for example:

```
cdk diff FooStackProductionUsEast1
```

As part of the `cdk diff` flow, cdk synthesizes all stacks in `bin/cdk.ts` instead of just the one that we specified in our command. Based on our testing, this results in about a 5x increase in synthesis time vs. just synthesizing the stack specified in the command. I'd imagine this slowdown increases with the amount of stacks specified in `bin/cdk.ts`

Is there any way to prevent this from happening?

Thank you

### Proposed Solution

Have `cdk synth` only synthesize the specified stack.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.63.0

### Environment details (OS name and version, etc.)

Darwin, Debian

**Comment by hoegertn** [comment]
This behaves exactly as expected, but I wrote a blog post about how you use this without the build time adding up.

https://taimos.de/blog/deploying-your-cdk-app-to-different-stages-and-environments

**Comment by pv93** [comment]
> This behaves exactly as expected, but I wrote a blog post about how you use this without the build time adding up.
> 
> https://taimos.de/blog/deploying-your-cdk-app-to-different-stages-and-environments

Thank you for the link. However, I don't see a workaround for reducing build times there.

In our CI/CD system, we run `cdk deploy` in a freshly checked out repository. This means that the `cdk.out` directory is not there. We only every run cdk deploy against a single stack, so there's no reason for all stacks to be synthesized. Is there currently no way to do this with a flag or something similar?

**Comment by hoegertn** [comment]
As you can see in the post you would run synth once and then for every environment run `cdk --app cdk.out deploy` and it will not synth again. You need to transfer the cdk.out artifact from one stage to the next.

CDK always needs to synth everything as during synth it doe snot yet know which stacks will be there. It can't partially instantiate the object tree.
