### ISSUE TITLE
(custom_resources.AwsCustomResource): Upgrade Node 14 to Node 16

### ISSUE THREAD

**Issue by mbp** [aws/aws-cdk#23989]
### Describe the bug

When using AwsCustomResource, it uses NODEJS_14_X, but that is End-of-life in a few months: 2023-04-30

### Expected Behavior

I would expect the CDK to use a supported version of Node. 

### Current Behavior

In my case, I am using CDK to generate the Cognito user client secret, which internally uses AwsCustomResource:

https://github.com/aws/aws-cdk/blob/v2-release/packages/@aws-cdk/aws-cognito/lib/user-pool-client.ts#L449

### Reproduction Steps

Use AwsCustomResource directly or any code that relies on it.

### Possible Solution

I suggest that it is upgraded to NODEJS_16_X.

### CDK CLI Version

v2.63.0

### Node.js Version

16

### OS

Linux

### Language

Typescript

**Comment by peterwoodworth** [comment]
Thanks for letting us know that you'd like to see the version upgraded 🙂 

There's [already an issue for this](https://github.com/aws/aws-cdk/issues/23682), if you want I suggest giving a thumbs up on the issue and commenting your support. Thanks!
