### ISSUE TITLE
aws_ecs_patterns: Cloudformation creating a new service resource when adding a circuit breaker

### ISSUE THREAD

**Issue by robert-lilleker** [aws/aws-cdk#23988]
### Describe the bug

When I try to add a circuit-breaker to `ApplicationLoadBalancedFargateService` construct cloudformtion tries to re-create the ECS service resource in the cloudformation stack rather than just updating the current resource. This will cause an outage 

### Expected Behavior

I should expect the ECS service to be updated rather than replaced, as described in the [ECS cloudformation document](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-service-deploymentconfiguration.html#cfn-ecs-service-deploymentconfiguration-deploymentcircuitbreaker) 

### Current Behavior

When trying to update an already deployed ECS service you get the following:
`rl-stand-alone-engine-stack | 0/6 | 10:46:53 | UPDATE_FAILED        | AWS::ECS::Service                           | 
StandAloneEngineStack/dev-service/Service/Service (devserviceService339EC638) Resource handler returned message:
 "Resource of type 'AWS::ECS::Service' with identifier 'dev-engine-svc-eu-west-2' already exists." (RequestToken: f804d1a3-72ab-4169-9773-fa9a6f301214, HandlerErrorCode: AlreadyExists)`

As cloudformation is trying to re-create the resource

### Reproduction Steps
`            ApplicationLoadBalancedFargateService engineECSCluster = new ApplicationLoadBalancedFargateService(scope, $"{NamingPrefix}-service", new ApplicationLoadBalancedFargateServiceProps

            {

                ServiceName ="name",

                Cluster = new Cluster(scope, $"{NamingPrefix}-engine-cluster", new ClusterProps

                {

                    ClusterName = $"{StackConfig.Identifier}-{NamingPrefix}-engine-cluster",

                    Vpc = vpc,

                    ContainerInsights = true

                }),
                RedirectHTTP = true,
                Certificate = Certificate.FromCertificateArn(scope, "engine-cluster-cert", StackConfig.DnsSecret.SecretValueFromJson("CertificateArn").ToString()),

                ListenerPort = 443,

                CircuitBreaker = new DeploymentCircuitBreaker

                {

                    Rollback = true

                },

                SslPolicy = SslPolicy.TLS12_EXT,

                TaskDefinition = engineTask,

                MinHealthyPercent = 100,

                DesiredCount = numberEngineTasks

            });`

Is the code I've already deployed with out the `CircuitBreaker` part, when added in the stack fails to update   

### Possible Solution

I am able to get it working with the following
`            ApplicationLoadBalancedFargateService engineECSCluster = new ApplicationLoadBalancedFargateService(scope, $"{NamingPrefix}-service", new ApplicationLoadBalancedFargateServiceProps

            {

                ServiceName = $"{NamingPrefix}-engine-svc-{StackConfig.Region}",

                Cluster = new Cluster(scope, $"{NamingPrefix}-engine-cluster", new ClusterProps

                {

                    ClusterName = $"{StackConfig.Identifier}-{NamingPrefix}-engine-cluster",

                    Vpc = vpc,

                    ContainerInsights = true

                }),

                RedirectHTTP = true,

                Certificate = Certificate.FromCertificateArn(scope, "engine-cluster-cert", StackConfig.DnsSecret.SecretValueFromJson("CertificateArn").ToString()),

                ListenerPort = 443,

                CircuitBreaker = new DeploymentCircuitBreaker

                {

                    Rollback = true

                },

                SslPolicy = SslPolicy.TLS12_EXT,

                TaskDefinition = engineTask,

                MinHealthyPercent = 100,

                DesiredCount = numberEngineTasks

            });

            CfnService ecsCfn = (CfnService) engineECSCluster.Service.Node.DefaultChild;

            ecsCfn.AddOverride("Properties.DeploymentConfiguration", new Dictionary<string, Dictionary<string, bool>>

                {

                    {"DeploymentCircuitBreaker", new Dictionary<string, bool>

                        {

                            {"Enable", true},

                            {"Rollback", true}

                        }

                    }

                });`

Where I'm "manually" overriding the construct to have the 'DeploymentConfiguration.DeploymentCircuitBreaker' to the cloudformation resource.

The issue is when `ApplicationLoadBalancedFargateService` is brought up without a `CircuitBreaker` property the cloudformation template **doesn't** include a `DeploymentController` property. Cloudformation defaults this to [ECS ](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-service.html#cfn-ecs-service-deploymentcontroller). However when specifying the `CircuitBreaker` property, CDK is generating cloudformation template with the propery `deploymentcontroller` defined. Thus seeing it as a change and trying to re-create it. When overriding the construct there isn't a `DeploymentController` property added and defaulting to ECS and updating the resource correctly.

Should having `CircuitBreaker` also define `DeploymentController` ? Or `ApplicationLoadBalancedFargateService` should always define `DeploymentController`  in order not to get into the situation I'm currently in

### CDK CLI Version

2.63.0

### Node.js Version

16.8.1

### OS

Windows

### Language

.NET

**Comment by khushail** [comment]
Yes @robert-lilleker , you are right. We have this PR- https://github.com/aws/aws-cdk/pull/22467 addressing the same issue. Have you tried enabling the feature flag mentioned in the PR?

**Comment by robert-lilleker** [comment]
That works, thanks! @khushail
