### ISSUE TITLE
Testing Lambda locally

### ISSUE THREAD

**Issue by vjindalradialtheory** [aws/aws-cdk#2399]
Hi, How we we test the lambda locally ?

**Comment by nija-at** [comment]
Hello @vjindalradialtheory -

You should be testing most of your lambda function logic using standard unit tests in the language you use. Further, to locally test a Lambda function in an environment similar to what AWS Lambda provides, you could use SAM CLI - https://github.com/awslabs/aws-sam-cli.

Hope that's helpful. I would recommend that you reach out to us and the community via our Gitter channel for such questions. The community will be able to provide a lot more options here, as well as, options that might work specifically for you.
