### ISSUE TITLE
(aws_stepfunctions_tasks): LambdaInvoke payload TaskInput cannot be set fromJsonPath when payloadResponseOnly enabed

### ISSUE THREAD

**Issue by rpmcginty** [aws/aws-cdk#23996]
## Describe the issue

When using the [`LambdaInvoke`](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_stepfunctions_tasks.LambdaInvoke.html) step functions task construct, I have found a limitations with payload specification when the `payloadResponseOnly` is enabled. This limitation is not clearly documented. 

### Missing Documentation
Namely, when `payloadResponseOnly=true`, you _cannot_ set the `payload=sfn.JsonPath.fromJsonPathAt("...")`. 

And while other limitations of the flag's usage _are_ documented, this limitation is not. 

In the [documentation](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_stepfunctions_tasks.LambdaInvoke.html#example), the following code example is provided. 

#### Docs Example Code (Correctly resolves json path input)
```ts
// use the output of fn as input
new tasks.LambdaInvoke(this, 'Invoke with payload field in the state input', {
  lambdaFunction: fn,
  payload: sfn.TaskInput.fromJsonPathAt('$.Payload'),
});
``` 

####  Modified Example Code (Does not resolve json path input)

```ts
new tasks.LambdaInvoke(this, 'Invoke with payload field in the state input', {
  lambdaFunction: fn,
  payload: sfn.TaskInput.fromJsonPathAt('$.Payload'),
  payloadResponseOnly: true,
});
```
## Proposed Documentation

I believe it is not possible to configure the payload as a json path reference when using `payloadResponseOnly` (step function ASL limitation).

Best place to specify this is in the same docstring that other limitations are mentiond for the [`payloadResponseOnly`](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_stepfunctions_tasks.LambdaInvoke.html#payloadresponseonly) field.

### Links

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_stepfunctions_tasks.LambdaInvoke.html

**Comment by tim-finnigan** [comment]
Hi thanks for reaching out. This issue looks like it overlaps with https://github.com/aws/aws-cdk/issues/22390. I think we should close this as a duplicate and continue tracking the issue there. I'll mention this issue over in that one, and if there are any distinctions you'd like to clarify please let us know.
