### ISSUE TITLE
pipelines: 2.63 introduces breaking change with shared ManualApprovalStep 

### ISSUE THREAD

**Issue by joelsmith3-nhs** [aws/aws-cdk#23990]
### Describe the bug

In 2.62 we were able to put a shared manual changeset approval step in the stage, so that rather than having an approval gate for each stack, we could have a single approval gate. Following upgrade to 2.63, a `cdk ls` produced the error 
`RuntimeError: Error: Dependency cycle in graph: docker-statemachine-assets => docker-assets => docker-statemachine-assets`
Reverting to 2.62 and `cdk ls` and `cdk deploy` completed as expected.

### Expected Behavior

Pipeline to continue to build with a single shared manual gate for the stage to validate the change sets for the stacks had been checked.

### Current Behavior

`cdk ls` produced the error
`RuntimeError: Error: Dependency cycle in graph: docker-statemachine-assets => docker-assets => docker-statemachine-assets`

### Reproduction Steps

```
        bucket_stage = AssetsBucketStage(self, "AssetsBucketStage")
        approval_step = pipelines.ManualApprovalStep("ChangeSet Approval", comment="Please confirm the change set details")
        pipeline.add_stage(
            bucket_stage,
            stack_steps=[
                pipelines.StackSteps(stack=bucket_stage.bucket1, change_set=[approval_step]),
                pipelines.StackSteps(stack=bucket_stage.bucket2, change_set=[approval_step]),
            ],
        )

```

### Possible Solution

Seems to be related to https://github.com/aws/aws-cdk/pull/23908

### Additional Information/Context

Code above is the minimal piece from a stage in a basic pipeline to build two buckets.  

### CDK CLI Version

2.62.0 (build b317696)

### Node.js Version

v16.14.2

### OS

Darwin 22.2.0

### Language

Python

### Language Version

Python 3.9.16

**Comment by peterwoodworth** [comment]
Thanks for reporting this @joelsmith3-nhs, I've been able to reproduce your findings. Switching back to `2.62.0` will produce a successful synthesis when using a shared `ManualApprovalStep`, while it fails on `2.63.1`. We'll try to fix this soon
