### ISSUE TITLE
(API Gateway): (With nested stacks, a child resource cannot start with the same string that its parent ends with)

### ISSUE THREAD

**Issue by nvelado** [aws/aws-cdk#23998]
### Describe the bug

When using nested stacks, creating the following two resources generates a non-descript deployment error:

/device_firmware/firmware_distribution

It appears that a parent resource that ends in the same substring as it's child resource begins generates a non-descript deployment error

### Expected Behavior

Should be no issue creating an API such as /device_firmware/firmware_distribution

### Current Behavior

Non descript deployment error occurs

### Reproduction Steps

The following code reproduces the issue:

```
IRestApi api = RestApi.FromRestApiAttributes(this, "RestAPI", new RestApiAttributes
            {
                RestApiId = props.RestApiId,
                RootResourceId = props.RootResourceId
            });


            Amazon.CDK.AWS.APIGateway.Resource devMgmtResource = api.Root.AddResource("device_firmware");
            Amazon.CDK.AWS.APIGateway.Resource fwDistResource = devMgmtResource.AddResource("firmware_distribition");
            Method methodFW = fwDistResource.AddResource("cancel_upgrade").AddMethod("POST", vpcIntegration);
            Methods.Add(methodFW);
            return;
```

### CDK CLI Version

2.63.0

### Node.js Version

v16.16.0

### OS

Windows

### Language

.NET

**Comment by peterwoodworth** [comment]
Hey @nvelado, could you please provide the definitions for `Methods` and `vpcIntegration` in your example? Thanks!

**Comment by nvelado** [comment]
Hi Peter, sure thing....

       public CDKAPIGateway(Construct parent, string id, IStackProps props, Dictionary<string, List<APIGatewayAPIDescriptionObj>> APIGatewayNestedStackMap) : base(parent, id, props)
        {
            try
            {
                Vpc vpc = new Vpc(this, "VPC");
                NetworkLoadBalancer nlb = new NetworkLoadBalancer(this, "EKS_NLB", new NetworkLoadBalancerProps
                {
                    Vpc = vpc
                });
                VpcLink link = new VpcLink(this, "link", new VpcLinkProps
                {
                    Targets = new[] { nlb }
                });

                Integration vpcIntegration = new Integration(new IntegrationProps
                {
                    Type = IntegrationType.HTTP_PROXY,
                    Options = new IntegrationOptions
                    {
                        ConnectionType = ConnectionType.VPC_LINK,
                        VpcLink = link,
                    },
                    IntegrationHttpMethod = "POST",
                });

                RestApi restApi = new RestApi(this, "RestApi", new RestApiProps // apiGWObj.restAPIObj.name
                {
                    CloudWatchRole = true,
                    Deploy = false,
                });
                // CDK seems to require the constructor to make one AddMethod request directly, otherwise throws an error during synth
                restApi.Root.AddMethod("ANY");

                // Keep track of all resources added to the api gateway object, ie: /v1, /v2, /v3, etc...
                Dictionary<string, Amazon.CDK.AWS.APIGateway.Resource> rootResourceIDMap = new Dictionary<string, Amazon.CDK.AWS.APIGateway.Resource>();
                // Keep track of all resources added in total, including from the nested stacks.  This is needed because opeanapi may describe duplicate 
                // resources out-of-order. ie; /v1/asset_management/create_policy/methods but then later on, /v1/asset_management/methods
                // Thus, it's necessary to maintain a reference for all resources added to retrieve these when adding new ones based on previously created
                // parent nodes
                Dictionary<string, Amazon.CDK.AWS.APIGateway.Resource> allResourceIDMap = new Dictionary<string, Amazon.CDK.AWS.APIGateway.Resource>();
                Amazon.CDK.AWS.APIGateway.Resource parentResource = null;
                // Used to describe all methods when creating the final deployment stack obj
                List<Method> apiMethodList = new List<Method>();

                int count = 0;
                foreach (KeyValuePair<string, List<APIGatewayAPIDescriptionObj>> stackEntry in APIGatewayNestedStackMap)
                {
                    // As of CDK 2.63.0, seems to be a bug where when using an interface for referencing the api gateway object,
                    // adding a root resource with a numerical value in it causes the CDK to fail, ie: /v1
                    //
                    // As a work-around, we'll add all pathToken[0] values, ie: /v1, /v2, /v3 as resources to the api gateway object
                    // then pass that resources as the parent to the nested stack object (RootResourceId assignment in CDKAPIGatewayNestedStack constructor below)
                    List<string> pathTokens = APIGatewayClass.tokenizePath(stackEntry.Key);
                    string rootResourceId = pathTokens[0];

                    if (rootResourceIDMap.ContainsKey(rootResourceId) == false)
                    {
                        parentResource = restApi.Root.AddResource(rootResourceId);
                        rootResourceIDMap.Add(rootResourceId, parentResource);
                        allResourceIDMap.Add(rootResourceId, parentResource);
                    }
                    else
                        parentResource = rootResourceIDMap[rootResourceId];

                    string nestedStackName = Format.removeNonAlphaNumbericChars(stackEntry.Key);
                    CDKAPIGatewayNestedStack nestedStack = new CDKAPIGatewayNestedStack(this, new ResourceNestedStackProps
                    {
                        RestApiId = restApi.RestApiId,
                        RootResourceId = parentResource.ResourceId, //restApi.RestApiRootResourceId
                    },
                    restApi, vpcIntegration, ref allResourceIDMap, parentResource, nestedStackName, pathTokens.GetRange(1, pathTokens.Count - 1), stackEntry.Value);

                    apiMethodList.AddRange(nestedStack.Methods);
                }

                DeployStack deployStack = new DeployStack(this, new DeployStackProps
                {
                    RestApiId = restApi.RestApiId,
                    Methods = apiMethodList
                });
             }
            catch (Exception e)
            {
                m_debug.DebugOut(String.Format("Exception: {0}", e.ToString()), DebugLevel.ERROR);
            }
        }

        // Builds nested stack resources off of the RestAPI object's root resource passed in
    // ie: if root is passed in (via parentResource.Path), pathList[] will contain /v1 and nested stack will be built off of root
    //      if root/v1 is passed in, pathList[] will not contain v1 and thus, will build the nested resource based on root/v1
    // It's up to the calling function to decide what resources are built against the main RestAPI object and where in the tree 
    // the nested stacks should begin
    class CDKAPIGatewayNestedStack : NestedStack
    {
        public List<Method> Methods = new List<Method>();
        Debug m_debug = new Debug();

        public CDKAPIGatewayNestedStack(Construct scope, ResourceNestedStackProps props, RestApi rootAPI, Integration vpcIntegration, 
            ref Dictionary<string, Amazon.CDK.AWS.APIGateway.Resource> allResourceIDMap,    // Map of all resources built in this function, maintained at caller stack level
            Amazon.CDK.AWS.APIGateway.Resource parentResource,                              // The node off the RestAPI object that is the parent for the IRestApi interface object
            string nestedStackResourceName,                                                 // Name of this nested stack that gets passed to the inherited base object
            List<string> pathList,                                                          // List of paths that need to be created as resources before any methods are created, ie: /v1, /v1/asset_management, etc...
            List<APIGatewayAPIDescriptionObj> resourceObjList) :                            // List of all API objects to be created as Methods at the end of the pathList
            base(scope, nestedStackResourceName, props)
        {
            // TODO- pass in API Name for multi-instance
            // Interface must be used in order for nested stacks to work.  This is not well documented, but absolutely required
            IRestApi api = RestApi.FromRestApiAttributes(this, "RestAPI", new RestApiAttributes
            {
                RestApiId = props.RestApiId,
                RootResourceId = props.RootResourceId
            });

            Amazon.CDK.AWS.APIGateway.Resource childResource = parentResource;

            m_debug.DebugOut(String.Format("CDKAPIGatewayNestedStack: building {0}", nestedStackResourceName), DebugLevel.API_GATEWAY_VERBOSE);

            // Initialize to parentResource.Path so that /v1/asset_management can be distinguished from /v2/asset_management when asset_management is the 
            // root of the nested stack.  The allResourceIDMap needs this global uniqueness.
            string pathStr = parentResource.Path;
            bool isRoot = true;
            foreach (string pathToken in pathList)
            {
                pathStr += "/" + pathToken;

                if (allResourceIDMap.ContainsKey(pathStr) == false)
                {
                    if (isRoot == true)
                    {
                        // Change from api to rootAPI to not use nested stacks- but will hit deployment issue at 500 resources
                        // Also would require changing root schema back to have nested stacks start at /v1, /v2, etc...
                        childResource = api.Root.AddResource(pathToken);
                        m_debug.DebugOut(String.Format("\t:{0}-R(new)", pathToken), DebugLevel.API_GATEWAY_VERBOSE);
                    }
                    else
                    {
                        childResource = childResource.AddResource(pathToken);
                        m_debug.DebugOut(String.Format("\t:{0}-C", pathToken), DebugLevel.API_GATEWAY_VERBOSE);
                    }
                    
                    allResourceIDMap.Add(pathStr, childResource);
                }
                else
                    childResource = allResourceIDMap[pathStr];

                isRoot = false;
            }

            foreach (APIGatewayAPIDescriptionObj apiDescObj in resourceObjList)
            {
                // TODO- Address proxy case where a resource may or may not already exist
                // TODO- CORS
                // TODO- response transformations
                if (apiDescObj.IsProxyRequired == false)
                {
                    m_debug.DebugOut(String.Format("\t:APIName: {0}, Method: {1}", apiDescObj.APIName, apiDescObj.Method), DebugLevel.API_GATEWAY_VERBOSE);

                    Method method = childResource.AddResource(apiDescObj.APIName).AddMethod(apiDescObj.Method, vpcIntegration);
                    Methods.Add(method);
                }
            }
        }
    }

**Comment by nvelado** [comment]
Hello, is this is still an open issue that github actions closed on a watchdog?

**Comment by peterwoodworth** [comment]
I haven't been able to reproduce this with the information given. Could you please share a github repository which I can _easily clone and deploy_ to reproduce this issue?
