### ISSUE TITLE
(assertions): NestedStacks inside NestedCloudAssemblys fail `Template.fromStack()`

### ISSUE THREAD

**Issue by Styerp** [aws/aws-cdk#24004]
### Describe the bug

Templates aren't created for NestedStacks that reside in a Stage below the App root. 

My application defines a (custom) pipeline. Each wave of my pipeline is a Stage. These stages have Stacks as deployment units, any of which can contain NestedStack constructs. When testing against the NestedStacks, all templates fail to generate, as they don't include the stage assembly inside the path.

### Expected Behavior

Templates are created and can be tested against.

### Current Behavior

Tests fail with "ENOENT: no such file or directory" errors, as the path is incomplete. 

### Reproduction Steps

I wrote this so I could run it in my Node REPL, so it uses requires. 
```
const cdk = require("aws-cdk-lib")
const fs = require("fs");
const path = require("path");

const app = new cdk.App("Root");
const stage = new cdk.Stage(app, "Trunk");
const stack = new cdk.Stack(stage, "Branch");
const nested1 = new cdk.NestedStack(stack, "Leaf1");
const nestedConstruct = new cdk.aws_s3.Bucket(nested1, "NestedBucket", {})


const nested2 = new cdk.NestedStack(stack, "Leaf2");
const templateNest1 = cdk.assertions.Template.fromStack(nested1) //fails - ENOENT: no such file or directory, open '/private/var/folders/lj/2pctvcb518dcg10t7m9kk660f4_slb/T/cdk.out03txcp/intermediateTopLevelNest12B0AFB29.nested.template.json'

const fullAssembly = app.synth();
// Walk down the construct tree to find the last stage in this construct's path. I'm sure there's a nicer way to do this.
const closestStageToStack = nested1.node.scopes.reduce(function(prev, current){
  if(cdk.Stage.isStage(current)) return current
  else return prev;
})
const workingTemplateFile = fs.readFileSync(path.join(fullAssembly.directory, "assembly-" + closestStageToStack.stageName, nested1.templateFile)).toString("utf-8")
const goodTemplate = cdk.assertions.Template.fromString(workingTemplateFile)
console.log(goodTemplate.template)
```

### Possible Solution

Inclusion of intermediate assemblies in the path specifying nested stacks resolves the problem, at least for single layers of nesting.

### CDK CLI Version

2.40.0

### Node.js Version

16

### OS

OSX

### Language

Typescript

### Language Version

Typescript (4.9)

**Comment by Styerp** [comment]
Presumably the culprit is [here](https://github.com/aws/aws-cdk/blob/6bd9fe23ddc880e05a00bd0657cb04f59263b100/packages/%40aws-cdk/assertions/lib/template.ts#L241), where no levels of nesting underneath the root are considered.

**Comment by peterwoodworth** [comment]
Thanks for reporting this, I've been able to reproduce and confirm the issue. 

Thank you as well for the suggested change and PR, we'll try to take a look and provide feedback when possible 🙂
