### ISSUE TITLE
@aws-cdk/aws-apigatewayv2-alpha: example URL property for HttpUrlIntegration constructor leads to "Invalid HTTP endpoint specified for URI"

### ISSUE THREAD

**Issue by matwerber1** [aws/aws-cdk#24017]
### Describe the issue

Modules with affected documentation:

 * `@aws-cdk/aws-apigatewayv2-alpha`
 * `@aws-cdk/aws-apigatewayv2-integrations-alpha`
 * `@aws-cdk/aws-apigatewayv2-authorizers-alpha`

In the docs for the modules above, there are several places where the reader is shown an example of using the `HttpUrlIntegration` constructor from `@aws-cdk/aws-apigatewayv2-integrations` with a URL of `https://get-books-proxy.myproxy.internal`. 

Below is a full example: 

```js
const booksIntegration = new HttpUrlIntegration('BooksIntegration', 'https://get-books-proxy.myproxy.internal');
```

While following along with the examples in the docs, my colleague, @joshdirkx, and I were receiving a runtime error of `Invalid HTTP endpoint specified for URI` from the line above. We eventually realized that ([per the docs](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-http.html)) the URL must be a **publicly** routable URL. 

We knew API Gateway is capable of routing to private resources within a VPC and we knew the `.internal` is by default the private DNS TLD assigned to EC2 instances, so at first glance we didn't see anything wrong. It took a bit of trial and error before that "oooohhhh" moment. 

Our suggestion is to change the example URL to something with a public domain like `https://get-books-proxy.example.com`. 

We'll post a PR for this change in case you agree and want to merge. 

### Links

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-apigatewayv2-alpha-readme.html
https://docs.aws.amazon.com/cdk/api/v2/docs/aws-apigatewayv2-integrations-alpha-readme.html
https://docs.aws.amazon.com/cdk/api/v2/docs/aws-apigatewayv2-authorizers-alpha-readme.html

**Comment by peterwoodworth** [comment]
Thanks for the PR and for the reasoning behind this suggested change! We'll think about this and provide feedback on your PR when able to 🙂
