### ISSUE TITLE
Amazon Kinesis Firehose:  Convert record format (Parquet/ORC) cannot be set in s3DestinationConfiguration

### ISSUE THREAD

**Issue by ttais2017** [aws/aws-cdk#24047]
### Describe the bug

 Convert record format (Parquet/ORC) cannot be set in s3DestinationConfiguration.

As shown in the image from AWS Console, the delivery stream can be configured with Parquet/ORC convert record.

![image](https://user-images.githubusercontent.com/26426283/217210720-351cd216-89cc-4f92-9358-1a0df50c896a.png)

This configuration cannot be set from s3DestinationConfiguration in Java Code: 

![image](https://user-images.githubusercontent.com/26426283/217211235-630ef76d-2dc6-4abb-b6d2-1d35a7103b51.png)

### Expected Behavior

Parquet or ORC format conversion should be allowed **also** in s3DestinationConfiguration

### Current Behavior

Parquet cannot be used in the delivery stream using s3DestinationConfiguration.  

_Currently this option is only allowed in extendedS3DestinationConfiguration_

### Reproduction Steps

see images

### CDK CLI Version

2.63.2

### Node.js Version

19.6

### OS

Windows

### Language

Java

**Comment by pahud** [comment]
Correct me if I was wrong but I didn't see the cloudformation support at this moment. This could be a dependency of CFN support.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-kinesisfirehose-deliverystream-s3destinationconfiguration.html#cfn-kinesisfirehose-deliverystream-s3destinationconfiguration-compressionformat

**Comment by zupmeL** [comment]
I think what you are searching is not in the s3DestinationConfiguration but in the extendedS3DestinationConfiguration:

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_kinesisfirehose.CfnDeliveryStream.ExtendedS3DestinationConfigurationProperty.html

**Comment by ttais2017** [comment]
Thanks for the link.  I already found that info and fixed my code.!.

**Comment by khushail** [comment]
@ttais2017 , looks like the issue is resolved . Could you please confirm ?

**Comment by ttais2017** [comment]
Thanks for asking. it was fixed !!
