### ISSUE TITLE
Amazon Kinesis Firehose / Dynamic partitioning key name / JQ expressions cannot be defined

### ISSUE THREAD

**Issue by ttais2017** [aws/aws-cdk#24044]
### Describe the bug

Dynamic partitioning key name and Dynamic partitioning JQ expression cannot be used currently

![image](https://user-images.githubusercontent.com/26426283/217197813-62d0726d-191f-41e2-8427-70ac96331996.png)

### Expected Behavior

is this feature already implemented ?.  I looked over all in the latest version but I could not find. 

### Current Behavior

my kinesis firehose delivery stream (+extendedS3DestinationConfiguration) will not be deployed due to prefix and error prefix for dynamic partition are not well defined.

### Reproduction Steps

define a kinesis firehose stream (+extendedS3DestinationConfiguration) with dynamic partitioning.  set prefix and prefix for errors like:  

            .prefix("simulation/!{timestamp:yyyy}/!{timestamp:MM}/!{timestamp:dd}/!{timestamp:HH}/!{timestamp:mm}")
            .errorOutputPrefix("simulation/!{firehose:error-output-type}")

![image](https://user-images.githubusercontent.com/26426283/217201027-98ffd168-167a-4c6a-b3a1-14adec8fb922.png)

-->>>

![image](https://user-images.githubusercontent.com/26426283/217202438-2d8dfd91-534c-4ad7-a869-e9638bb408d5.png)

### CDK CLI Version

2.63.2

### Node.js Version

19.6

### OS

Windows

### Language

Java

### Language Version

11

**Comment by pahud** [comment]
AFAIK this should be already supported.

Please check the sample in the README here:
https://github.com/aws/aws-cdk/tree/main/packages/%40aws-cdk/aws-kinesisfirehose#s3

**Comment by ttais2017** [comment]
Hi there, 
it should be already possible; nevertheless I included the screenshot with error during deployment  :(  
The expressions I used are very similar with the documentation.

Best Regards

**Comment by pahud** [comment]
Hi

I actually can successfully deploy this with CDK in TS as below:

```ts
import * as cdk from "aws-cdk-lib";
import { 
aws_s3 as s3,
aws_kinesis as kinesis,
} from "aws-cdk-lib";
import { Construct } from "constructs";
import * as fh from '@aws-cdk/aws-kinesisfirehose-alpha'
import * as destinations from '@aws-cdk/aws-kinesisfirehose-destinations-alpha';

export class CdkSandboxStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const bucket = new s3.Bucket(this, 'Bucket');

    const s3Destination = new destinations.S3Bucket(bucket, {
      dataOutputPrefix: 'myFirehose/DeliveredYear=!{timestamp:yyyy}/anyMonth/rand=!{firehose:random-string}',
      errorOutputPrefix: 'myFirehoseFailures/!{firehose:error-output-type}/!{timestamp:yyyy}/anyMonth/!{timestamp:dd}',
    });

    const sourceStream = new kinesis.Stream(this, 'Source Stream');
    new fh.DeliveryStream(this, 'Delivery Stream', {
      sourceStream: sourceStream,
      destinations: [s3Destination],
    });
  }
}
```

Can you provide your full CDK code that fails with error?
