### ISSUE TITLE
EFS: Support File System Policy

### ISSUE THREAD

**Issue by cameron-dunn-sublime** [aws/aws-cdk#24042]
### Describe the feature

The [FileSystem construct](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_efs.FileSystem.html) does not support a [File System Policy](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_efs.CfnFileSystem.html#filesystempolicy).

### Use Case

This would make working with the FileSystem construct more useful, and would avoid needing to use escape hatches to associate a policy.

### Proposed Solution

I believe this could simply be added as an additional property. Or an additional construct could allow associating a policy, similar to `s3.BucketPolicy`.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

0.2.63

### Environment details (OS name and version, etc.)

OS X, not related

**Comment by pahud** [comment]
Yes, this seems to be a new L1 property and we could add it in the L2 props. Are you interested to submit a PR for that?
