### ISSUE TITLE
SSM: Invalid link on SSM Document "Target Type" Property

### ISSUE THREAD

**Issue by ryanolee** [aws/aws-cdk#24054]
### Describe the issue

Minor link issue on the ssm documentation page for "CfnDocument".
The "targetType" has a link with the text "AWS resource and property types reference" which directs to "https://awscloudformation/latest/UserGuide/aws-template-resource-type-ref.html".

This looks to be down to the documentation line having a double slash between `docs.aws.amazon.com` and `AWSCloudFormation`.
```
"TargetType": "Specify a target type to define the kinds of resources the document can run on. For example, to run a document on EC2 instances, specify the following value: `/AWS::EC2::Instance` . If you specify a value of '/' the document can run on all types of resources. If you don't specify a value, the document can't run on any resources. For a list of valid resource types, see [AWS resource and property types reference](https://docs.aws.amazon.com//AWSCloudFormation/latest/UserGuide/aws-template-resource-type-ref.html) in the *AWS CloudFormation User Guide* .",
```
(See packages/@aws-cdk/cfnspec/spec-source/cfn-docs/cfn-docs.json#L44463) ([Locked line number by making fork](https://raw.githubusercontent.com/ryanolee/aws-cdk/main/packages/%40aws-cdk/cfnspec/spec-source/cfn-docs/cfn-docs.json))

### Links

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ssm.CfnDocument.html
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ssm-document.html

**Comment by tim-finnigan** [comment]
Hi @ryanolee thanks for reporting this, I could confirm the issue. This will need to be fixed upstream by CloudFormation or service API documentation, so I'll create an internal ticket for the appropriate team to address this.

**Comment by tim-finnigan** [comment]
I was informed that this issue has been fixed, and looking at the docs page I can confirm that the link is working now. Thanks again for reporting this!
