### ISSUE TITLE
(@aws-cdk/aws-cloudwatch): Cross-account metrics on SQS queue expected in incorrect account

### ISSUE THREAD

**Issue by EHadoux** [aws/aws-cdk#24061]
### Describe the bug

I have a FargateService with an autoscale that scales on the `ApproximateNumberOfMessagesVisible` of a queue located in another account. The sharing is working as I can see the metrics from the monitoring account.
In my cdk app (Typescript), I import the queue using the ARN and end up with an `IQueue`.
I then get the metric to use in the autoscale using:
```typescript
const metric = queue.metricApproximateNumberOfMessagesVisible({
    account: 'ACCOUNT ID WHERE THE QUEUE IS COMING FROM',
});
```
I then use that metric in `service.autoScaleTaskCount(...).scaleOnMetric('ID', { metric, ... })`

### Expected Behavior

The alarm for the autoscaling listens to the metric located on the account that has the queue generating that metric.

### Current Behavior

It's listening to the metric on the account that deploys the cdk app. However the metrics doesn't exist there.

### Reproduction Steps

```typescript
const queue = Queue.fromQueueArn(this, 'Queue', props.QueueArn);
const fargateCluster = new Cluster(this, 'Cluster', {});
const definition = new FargateTaskDefinition(this, 'FargateDef', {
  cpu: 256,
  memoryLimitMiB: 512,
});
const service = new FargateService(this, 'FargateService', {
  cluster: fargateCluster,
  taskDefinition: definition,
});
const metric = queue.metricApproximateNumberOfMessagesVisible({
  account: 'ACCOUNT WHERE THE QUEUE EXISTS',
});
service.autoScaleTaskCount({ minCapacity: 0, maxCapacity: 1 }).scaleOnMetric('ScaleOnQueueSize', {
  metric,
  scalingSteps: [
    { upper: 0, change: 0 },
    { lower: 1, change: 1 },
  ],
  adjustmentType: AdjustmentType.EXACT_CAPACITY,
});
```

### Possible Solution

Defining the metric externally (i.e. not going through the imported queue) works.

In other words replacing from above
```typescript
const metric = queue.metricApproximateNumberOfMessagesVisible({
  account: 'ACCOUNT WHERE THE QUEUE EXISTS',
});
```
with
```typescript
const metric = new Metric({
  metricName: 'ApproximateNumberOfMessagesVisible',
  namespace: 'AWS/SQS',
  account: 'ACCOUNT WHERE THE QUEUE EXISTS',
  dimensionsMap: { QueueName: queue.queueName }, // note that it's using the imported IQueue here
});
```

### Additional Information/Context

When outputting during synthesis the account attribute it shows:
* the imported queue -> the cdk app account, i.e. the monitoring account
* the metric when going through the queue (i.e. `queue.metricApproximateNumberOfMessagesVisible`) -> monitoring account
* the metric created with `new Metric` -> correct account where the queue is located

Note that despite using `new Metric` it doesn't actually create a new metric, it correctly links to the right one, already present in the other account.

### CDK CLI Version

2.60

### Framework Version

2.62.2

### Node.js Version

19.6.0

### OS

Mac

### Language

Typescript

### Language Version

4.9.4

**Comment by tim-finnigan** [comment]
Hi @EHadoux thanks for reporting this. After doing some investigation it looks like this overlaps with an existing issue: https://github.com/aws/aws-cdk/issues/18951. I think this may be a known limitation that requires a further deep dive. I'm going to go check in on that previous issue and see if there are any distinctions between these two.

**Comment by tim-finnigan** [comment]
Following up here - I think we should de-duplicate this issue to consolidate tracking in https://github.com/aws/aws-cdk/issues/18951.
