### ISSUE TITLE
[AWS EKS]: Helm Chart not uninstalled after changing namespace

### ISSUE THREAD

**Issue by jordangullen** [aws/aws-cdk#24063]
### Helm Chart construct fails to uninstall release on namespace update
The HelmChart construct is not removing helm releases when updating the namespace even though it deploys the new release to the new namespace, resulting in 2 releases.

Before
```ts
    new cdk.aws_eks.HelmChart(this, 'app-helm-chart', {
      cluster,
      createNamespace: true,
      namespace: 'before',
      chartAsset: localHelmChartAsset,
      release: props.serviceName,
      values: {}
    })
```

After
```ts
    new cdk.aws_eks.HelmChart(this, 'app-helm-chart', {
      cluster,
      createNamespace: true,
      namespace: 'after',
      chartAsset: localHelmChartAsset,
      release: props.serviceName,
      values: {}
    })
```

### Expected Behavior

Before:
Helm chart deployed into before namespace

After:
Helm chart uninstalled from before namespace
Helm chart deployed to after namespace

### Current Behavior

Before:
Helm chart deployed into before namespace

After:
~Helm chart uninstalled from before namespace~ // missing step
Helm chart deployed to after namespace

### Reproduction Steps

1. Release a helm chart to a namespace
2. Update the namespace

### Possible Solution

Option 1 - preferred behaviour:
Have the construct handle the namespace update as expected

Option 2 - add safety guard and use a workaround:
Fail the release on a namespace change and require a new HelmChart resource e.g. just changing the resource id of the construct to trigger a whole delete/create

### CDK CLI Version

2.40.0

### Node.js Version

16.16.0

### OS

Ubuntu

### Language

Typescript

**Comment by pahud** [comment]
Interesting. I'll try reproduce this in my account.

**Comment by pahud** [comment]
According to this, the custom resource will always run `helm upgrade` on resource change

https://github.com/aws/aws-cdk/blob/eda8c72015553c017bdbc8b4c5a5bc2b4a849315/packages/%40aws-cdk/aws-eks/lib/kubectl-handler/helm/__init__.py#L88

and should append new namespace parameter:

https://github.com/aws/aws-cdk/blob/eda8c72015553c017bdbc8b4c5a5bc2b4a849315/packages/%40aws-cdk/aws-eks/lib/kubectl-handler/helm/__init__.py#L167-L168

Before I dive deep into this issue, do you have any existing helm chart that can help me reproduce it? @jordangullen
