### ISSUE TITLE
(aws-cdk/aws-amplify): (Add Platform property to amplify.App)

### ISSUE THREAD

**Issue by kevinold** [aws/aws-cdk#24076]
### Describe the feature

Amplify accepts a `Platform` [property via CloudFormation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-amplify-app.html#aws-resource-amplify-app-properties), but this is not accessible via the CDK.

### Use Case

I am looking to deploy single-page applications (SPAs) and server-rendered applications (SSR) to Amplify via CDK.

The `Platform` defaults to "WEB" if not set, and deploying an SSR application via the CDK, I need a way to set the `Platform` to "WEB_COMPUTE".

### Proposed Solution

Add a `platform` property to the `AppProps` for `amplify.App`.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.63.2

### Environment details (OS name and version, etc.)

MacOS Monterey 12.6.2

**Comment by kevinold** [comment]
PR for this feature https://github.com/aws/aws-cdk/pull/23818

**Comment by peterwoodworth** [comment]
Thanks again for the issue and PR kevinold, the new PR for this issue is here https://github.com/aws/aws-cdk/pull/23818
