### ISSUE TITLE
(aws_lambda_nodejs): text after `@` (ampersand) is trimmed in documentation

### ISSUE THREAD

**Issue by trivikr** [aws/aws-cdk#24089]
### Describe the issue

 If the code documentation contains '@' ampersand, the rest of the text is trimmed in HTML documentation

For example, the JS docs for BundlingOptions.externalModules in `aws-lambda-nodejs/lib/types.ts` is:
```js
['aws-sdk'] if the runtime is < Node.js 18.x, ['@aws-sdk/*'] otherwise.
```

https://github.com/aws/aws-cdk/blob/eda8c72015553c017bdbc8b4c5a5bc2b4a849315/packages/%40aws-cdk/aws-lambda-nodejs/lib/types.ts#L178-L181

In the documentation, the content is trimmed after `@`
```console
Type: string[] (optional, default: ['aws-sdk'] if the runtime is < Node.js 18.x, [')
```

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda_nodejs.BundlingOptions.html#externalmodules

<details>
<summary>Screenshot</summary>

![aws_cdk_ampersand](https://user-images.githubusercontent.com/16024985/217870526-f9c69737-21ab-44b9-8770-c89015df1f76.png)

</details>

### Links

* Code: https://github.com/aws/aws-cdk/blob/eda8c72015553c017bdbc8b4c5a5bc2b4a849315/packages/%40aws-cdk/aws-lambda-nodejs/lib/types.ts#L178-L181
* Documentation: https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda_nodejs.BundlingOptions.html#externalmodules

**Comment by trivikr** [comment]
Although the issue is noticed in `@aws-cdk/aws-lambda-nodejs`, it should be applicable to all documentation.

**Comment by peterwoodworth** [comment]
Thanks for reporting this @trivikr, I can confirm what you're seeing. I wonder if this is only applicable on lines that already have something such as `@default`, something to investigate and fix

**Comment by trivikr** [comment]
> I wonder if this is only applicable on lines that already have something such as `@default`

Because `@default` is not part of the JS documentation, but `@aws-sdk` is.

**Comment by aasthavar** [comment]
It could also be seen for dockerImage(refere below screenshot) as well - 
<img width="763" alt="Screenshot 2023-02-19 at 23 10 06" src="https://user-images.githubusercontent.com/81507417/219965193-705c78cd-6aa9-4a9b-a784-431fc1b64dee.png">

**Comment by aasthavar** [comment]
I'm not entirely sure - but this seems to be some configuration issue which isn't supported as of yet. I maybe wrong. Check this [link](https://esbuild.github.io/content-types/#typescript). Check the row with content relevant to Experimental decorators. It mentions the use of a flag [emitDecoratorMetadata](https://www.typescriptlang.org/tsconfig#emitDecoratorMetadata).

**Comment by exoego** [comment]
Hi. This issue appears to be fixed already?

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda_nodejs.BundlingOptions.html#externalmodules
Text after `@` is present in the generated document.
<img width="724" alt="image" src="https://user-images.githubusercontent.com/127635/236109116-51784df2-e753-458c-a58d-9a2faf994cb3.png">

**Comment by peterwoodworth** [comment]
You're right, this is fixed for me too
