### ISSUE TITLE
(ec2.vpc): (PRIVATE_WITH_NAT is deprecated but it was not reported in the documentation)

### ISSUE THREAD

**Issue by talalong** [aws/aws-cdk#24088]
### Describe the bug

The code stated that the PRIVATE_WITH_NAT has been deprecated, but I couldn't find any related information in the documentation. So, I assume that it's a bug.

![Screenshot 2023-02-09 at 14 29 40](https://user-images.githubusercontent.com/24271207/217825950-092ed440-b631-4905-b355-d0a286602365.png)

### Expected Behavior

The type is not marked as "deprecated"

### Current Behavior

The type is marked as "deprecated"

### Reproduction Steps

Define VPC as below:

```
const vpc = new Vpc(this, "Vpc", {
      subnetConfiguration: [
        { name: "Public", subnetType: SubnetType.PUBLIC },
        { name: "Private", subnetType: SubnetType.PRIVATE_WITH_NAT },
        { name: "Isolated", subnetType: SubnetType.PRIVATE_ISOLATED }
      ]
    });
```

### CDK CLI Version

2.60

### Node.js Version

14.17

### OS

MacOS 12.5

### Language

Typescript

### Language Version

TypeScript (4.9.4)

**Comment by talalong** [comment]
@TheRealAmazonKendra what is the name of the new type? because this is what I can see in the vpc source file.
![image](https://user-images.githubusercontent.com/24271207/218112887-85bcd593-8875-47ac-81a0-ace23e42f193.png)

**Comment by madeline-k** [comment]
@talalong The new enum value to use is `PRIVATE_WITH_EGRESS`. See [this line](https://github.com/aws/aws-cdk/blob/eda8c72015553c017bdbc8b4c5a5bc2b4a849315/packages/%40aws-cdk/aws-ec2/lib/vpc.ts#L225). 

It's strange that it doesn't show in the documentation, I'm not sure why that's happening. We should definitely fix that.

**Comment by bun913** [comment]
I want to fix this ploblem.
May I challenge this ?

**Comment by bun913** [comment]
Is there any way for us to build [this document](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ec2.SubnetType.html) in our local environment?
I would like to reproduce the problem.

**Comment by talalong** [comment]
@bun913
I created the new CDK project using `cdk init app --language typescript` and defined the vpc like above.

**Comment by bun913** [comment]
@talalong 

Oh. I'm sorry.
I am aware that this is an issue where it shows as Deprecated in the [source code](https://github.com/aws/aws-cdk/blob/eda8c72015553c017bdbc8b4c5a5bc2b4a849315/packages/%40aws-cdk/aws-ec2/lib/vpc.ts#L225), but not in the [online document](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ec2.SubnetType.html).

example: my editor display the problem like below.

<img width="709" alt="vscode" src="https://user-images.githubusercontent.com/73948280/219983900-e3c9167b-f41e-4c63-a9b2-d1dec5319efb.png">



What I wanted to know is if it is possible to build the HTML of this online documentation locally.

From looking at the [source code](https://github.com/aws/aws-cdk/blob/eda8c72015553c017bdbc8b4c5a5bc2b4a849315/packages/%40aws-cdk/aws-ec2/lib/vpc.ts#L225), it looks like it should show up as Deprecated on the document as in the following example([MatchResult](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.assertions.MatchResult.html#pushmatcher-path-messagespan-classapi-icon-api-icon-deprecated-titlethis-api-element-is-deprecated-its-use-is-not-recommended%EF%B8%8Fspan): [source code](https://github.com/aws/aws-cdk/blob/eda8c72015553c017bdbc8b4c5a5bc2b4a849315/packages/%40aws-cdk/assertions/lib/matcher.ts#L96))...

I would like to verify step by step why it does not show Deprecated in the documentation...

@TheRealAmazonKendra 

If you know of any, could you please let me know?

**Comment by talalong** [comment]
I am closing this. Just use `PRIVATE_WITH_EGRESS` instead.
