### ISSUE TITLE
(aws_apigateway): binaryMediaTypes are not removed 

### ISSUE THREAD

**Issue by HannesOberreiter** [aws/aws-cdk#24099]
### Describe the bug

If you remove the `binaryMediaTypes` param from RestApi config it is not removed on live API Gateway.

### Expected Behavior

Removing `binaryMediaTypes` from the config should remove the media types on deployment.

### Current Behavior

It does not remove it on deployment. **Although it is removed in the stack template**. (Bug related to cloudFormation?)

### Reproduction Steps

1. Add binaryMediaType

```TypeScript
const api = new apigateway.RestApi(this, `cwc-cdk-api`, {
      binaryMediaTypes: ['*/*'],
}
```
2. Deploy, property is correctly added to template.json

```json
"Type": "AWS::ApiGateway::RestApi",
"Properties": {
    "BinaryMediaTypes": [
     "*/*"
    ],
}
```

3. Remove `binaryMediaType`

```TypeScript
const api = new apigateway.RestApi(this, `cwc-cdk-api`, {}
```
5. Deploy again, property is correctly removed from template.json

```json
"Type": "AWS::ApiGateway::RestApi",
"Properties": {}
```

6. Visit Amazon API Gateway and go into settings, binaryMediaType is still there.

![Binary Media Types](https://user-images.githubusercontent.com/16878981/218029075-e9daafc1-402f-4d3f-8d3a-56c57eeaa04a.png)

### CDK CLI Version

2.64.0

### Node.js Version

v19.4.0

### OS

macOS

### Language

Typescript

### Language Version

4.9.4

**Comment by peterwoodworth** [comment]
#23438 and #14660 seem to be related issues, I'll mention this in the ticket I have open and mentioned in #23438

**Comment by xrzhuang** [comment]
i manually removed it too and it's still broken. we found adding this caused our OPTIONS requests to break... https://stackoverflow.com/questions/59568148/enabling-binary-media-types-breaks-option-post-call-cors-in-aws-lambda

**Comment by peterwoodworth** [comment]
Thanks again for reporting this @xrzhuang,

I'm closing this issue to track the overall issue at #23438
