### ISSUE TITLE
no possible way to override service properties in @aws-cdk/aws-apprunner-alpha

### ISSUE THREAD

**Issue by ivanix1** [aws/aws-cdk#24119]
### Describe the bug

Trying to set low level property  Properties.IngressConfiguration.IsPubliclyAccessible,
but all the documented methods using L1, L2, Escape hatch do not work!
Documented methods require to pull out service as a CfnService, but not possible. 

### Expected Behavior

overrides and escape hatches should work, especially since this is alpha and does not implement much of the lower level features needed for apprunner.

### Current Behavior

just general errors that either CfnService not found, or addOverride or PropertyOverride not found
Its easy to update cloudformation template, but  impossible with cdk2!!! 

### Reproduction Steps

Add the code like so
import * as apprunner from '@aws-cdk/aws-apprunner-alpha';
...
const service = new apprunner.Service(this, 'ApiServerService', {
...
}
// Try to override 
const cfnService = service.node.defaultChild as apprunner.CfnService;
cfn.addOverride('Properties.IngressConfiguration.IsPubliclyAccessible', 'False');

### CDK CLI Version

2.60.0

### Framework Version

cdk 2.60.0-alpha.0

### Node.js Version

v16

### OS

linux

### Language

Typescript

**Comment by peterwoodworth** [comment]
Our L1 constructs aren't found in the alpha package, because L1 constructs are stable. You should be able to do this if you import `CfnService` from `aws-cdk-lib/aws-apprunner`. Let me know if you run into further issues after doing this
