### ISSUE TITLE
(region-info): `ROUTE_53_BUCKET_WEBSITE_ZONE_ID` of ap-southeast-3 seems to be wrong

### ISSUE THREAD

**Issue by fynnfluegge** [aws/aws-cdk#24120]
### Describe the bug

The `ROUTE_53_BUCKET_WEBSITE_ZONE_ID` of `ap-southeast-3` in https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/region-info/build-tools/fact-tables.ts seems to be wrong compared to the specification in https://docs.aws.amazon.com/general/latest/gr/s3.html#s3_region.

### Expected Behavior

```
ap-southeast-3': 'Z01846753K324LI26A3VV'
```

### Current Behavior

```
ap-southeast-3': 'Z01613992JD795ZI93075',
```

### Reproduction Steps

*No response*

### CDK CLI Version

2.60.0

### Node.js Version

v18.13.0

### OS

Mac OS

### Language

Typescript

**Comment by peterwoodworth** [comment]
You seem to be right here - Did you run into any errors using the currently implemented ID?

**Comment by fynnfluegge** [comment]
> You seem to be right here - Did you run into any errors using the currently implemented ID?

Didn't run into errors, just discovered it somehow when solving #23619
