### ISSUE TITLE
(secrets-manager): fromSecretCompleteArn().secretValueFromJson() locks up deployment if the secret is deleted

### ISSUE THREAD

**Issue by LukaHedt** [aws/aws-cdk#24130]
### Describe the bug

This may be a Cloudformation bug, but I have no idea how to report that to them, so sorry in advance.

Background - I have a 2 stack solution, currently, to separate my data resources from my API Gateway resources.

Stack 1:
- Aurora v1 Database Cluster
- Secrets Manager Secret, containing a user created specifically for a single Database in the Aurora Cluster (ie - not the root user)
- Some Custom Resources related to setting up that secret and DB Cluster.

Stack 2:
- Imports the secret from Stack 1 using fromSecretCompleteArn().
- Contains some lambda functions that serve an API that talks to the DB in Stack 1
- Some other unrelated resources like an S3 bucket.

The lambda functions connect to the DB Cluster in Stack 1 by using a Database URL environment variable, and it's formed by using this in the standard Stack constructor definition.

```ts
const rdsCredsSecret = Secret.fromSecretCompleteArn(this, 'rds-lambda-creds-secret', props.dbCredsSecretArn);
const rdsUsername = rdsCredsSecret.secretValueFromJson('username').toString();
const rdsPassword =  rdsCredsSecret.secretValueFromJson('password').toString();
const rdsDbName =  rdsCredsSecret.secretValueFromJson('dbname').toString();

// Endpoint is the Aurora endpoint + Port, and this is injected into the Environment Variables of the lambdas
const databaseUrl = `mysql://${rdsUsername}:${rdsPassword}@${props.rdsEndpoint}/${rdsDbName}`;
```

Now, because we aren't using hard cross-stack references (I found a separate deadlock issue that this solution overcame), the Secret in Stack 1 can be deleted at any time.
If the secret is removed in the CDK/Cloudformation template, and DeletionPolicy.RETAIN is not applied, the secret will be deleted immediately, with no restoration period available.

At this point, stack 2 can no longer be deployed again to change the ARN for the Credentials Secret - the old ARN remains in the template, and cloudformation _will not deploy the stack again_ if it cannot find the reference to that Secret.

Excerpt from the Cloudformation Template:
```json
{
  "Environment": {
     "Variables": {
      "DATABASE_URL": "mysql://{{resolve:secretsmanager:arn:aws:secretsmanager:ap-southeast-2:{accountId}:secret:rds-db-credentials-3i9qcP:SecretString:username::}}:{{resolve:secretsmanager:arn:aws:secretsmanager:ap-southeast-2:{accountId}:secret:rds-db-credentials-3i9qcP:SecretString:password::}}@rdsserverlesscluster-cluster.cluster-{clusterId}.ap-southeast-2.rds.amazonaws.com:3306/{{resolve:secretsmanager:arn:aws:secretsmanager:ap-southeast-2:{accountId}:secret:rds-db-credentials-3i9qcP:SecretString:dbname::}}",
     }
  },
}
```

The error when attempting to deploy:

```
Secrets Manager can't find the specified secret. (Service: AWSSecretsManager; Status Code: 400; Error Code: ResourceNotFoundException; Request ID: ba2250f6-40f1-4ddd-a2b8-a446301369d4; Proxy: null)
```

Obviously there are some possible anti-patterns in use here, but I suspect it's not uncommon to do this kind of import-then-reference activity.

### Expected Behavior

The stack should not become un-deployable if the Secret is deleted.

### Current Behavior

The Secret is decoded and used as if the secret were created and referenced in this stack.

### Reproduction Steps

```ts
class TestStack1 extends Stack {
  constructor(scope: Construct, id: string, props: StackProps) {
    super(scope, id, props);

    const secret = new Secret(this, 'my-secret', {
      secretName: 'my-secret-1',
      secretObjectValue: {
        username: SecretValue.unsafePlainText('foo'),
        password: SecretValue.unsafePlainText('foo'),
      },
    });

    new CfnOutput(this, 'my-secret-arn', {
      value: secret.secretArn,
    });
  }
}

class TestStack2 extends Stack {
  constructor(scope: Construct, id: string, props: StackProps & { secretArn: string }) {
    super(scope, id, props);

    const importedSecret = Secret.fromSecretCompleteArn(this, 'my-secret-import', props.secretArn);

    const fn = new Function(this, 'MyFunction', {
      runtime: Runtime.NODEJS_18_X,
      handler: 'index.handler',
      code: Code.fromInline(
        'exports.handler = function(event, ctx, cb) { return cb(null, "hi"); }'
      ),
      environment: {
        myVar:
          importedSecret.secretValueFromJson('username').toString() +
          ':' +
          importedSecret.secretValueFromJson('password').toString(),
      },
    });
  }
}

const app = new App();
new TestStack1(app, 'teststack1', {});
// Deploy teststack1 and copy out the secret ARN
new TestStack2(app, 'teststack2', {
  secretArn: 'arn:aws:secretsmanager:ap-southeast-2:{accountId}:secret:my-secret-1-W95d4g',
});
```

Now we go and change the SecretName inside TestStack1, and redeploy testStack1.

This should automatically force-delete the Secret without a retention period, and create a new secret.

Once teststack1 has redeployed, copy the new secret ARN into the stack props of stack 2, and attempt to redeploy it.

I get this error:

```
Stack Deployments Failed: Error: The stack named teststack2 failed to deploy: UPDATE_ROLLBACK_COMPLETE: Secrets Manager can't find the specified secret. (Service: AWSSecretsManager; Status Code: 400; Error Code: ResourceNotFoundException; Request ID: 0dfd6b17-551e-4dae-8e13-51b21683999a; Proxy: null)
```

### Possible Solution

`fromSecretCompleteArn()` should throw an error when trying to call `secretValueFromJson()` with it, since the stack can become brittle later on if the Secret ARN no longer exists.

This isn't an issue when using `fromSecretNameV2()` or `fromSecretPartialArn()`, since you can always recreate a secret with the same name and kinda juice it if you really need.

### Additional Information/Context

You also can't delete the stack from the console once the secret has been deleted :)

### CDK CLI Version

2.17.0 (build f9cd009)

### Node.js Version

v16.16.0

### OS

macOS 12.16.3

### Language

Typescript

**Comment by peterwoodworth** [comment]
Thanks for the clear reproduction steps, I was able to confirm that this is occurring.

As reported, if the secret in the original stack is renamed (deleted and recreated with a different name), updating the secret arn in stack 2 will result in the error message you've pasted in the issue. Interestingly enough, if you change the name in the original stack back to its original name, and copy the newly created arn (which will have a different 6 string suffix than the original secret) arn the deployment will successfully update.

I think this is a CloudFormation issue, I'll pass this on to them internally and provide updates here as they become available

**Comment by LukaHedt** [comment]
Huh that's really interesting, I wonder if it will un-deadlock my little situation with the Databases.
Thanks for testing that!

I agree, it's definitely a Cloudformation Issue, to be honest, I didn't know how to report a bug to them.
If it's not something they intend to fix, I think it would be prudent of CDK to disallow this pattern in future also, since it is a bit of a massive headache situation, but I'll understand if the team disagrees.

**Comment by LukaHedt** [comment]
Update: Yeah I manually recreated the secret with exactly the same name, copied in the new FullArn, and it deployed just fine.

That is super trippy, I wish it didn't take me a whole day to figure out.

Thanks sooooo much though! Saved me a bunch of hassle!!

**Comment by peterwoodworth** [comment]
Great to hear this unblocked you! There's no telling when I'm going to be able to provide further information behind the root cause, so at least this can help unblock anyone else who runs into this

**Comment by peterwoodworth** [comment]
> When an update is triggered on the resource containing the dynamic reference, CloudFormation has to determine the difference between the old and new resource during the update, for which it needs the value of the old secret as well. There can also arise a need to fetch the value of the old secret later, for eg: if the stack update fails on any other resource and CloudFormation has to rollback the stack, it will need to know the old secret value then to update the resource containing the dynamic reference, to its previous configuration. Thus, CloudFormation will always try to retrieve the value of old secret, even if the dynamic reference is being updated with an existing secret/replaced with a hard-coded value.

> Now to fetch the value of this old secret, CFN  makes a GetSecretValue API call for it. The issuing of “GetSecretValue” API call for the old secret cannot be avoided from service side because doing that would mean storing the resolved value of the old secret somewhere and that is against the security design of secretsmanager dynamic references

> The following workarounds can be used to unstuck the stack in this scenario:

> 1. If the secret is only scheduled for deletion and not fully deleted yet, restore the secret by referring the steps mentioned [here](https://docs.aws.amazon.com/secretsmanager/latest/userguide/manage_restore-secret.html) and then feel free to perform any further updates on the resource containing the dynamic reference.

> 2. If the old secret is not available for restore anymore or was deleted with -force-delete-without-recovery setting, then create another secret with the same name and values as the old deleted secret. Further, replace the ARN of the deleted secret present in the dynamic reference with either the ARN of this recreated secret or with any other existing secret ARN present in your Secrets Manager. After making these changes, the CloudFormation stack will be able to update successfully to use the new secret ARN mentioned in the dynamic reference. If the new secret ARN is different from the recreated secret ARN, you can also choose to delete the recreated secret after the stack update goes through.

> Important: Unlike Secrets Manager Console, If a secret created and managed via CloudFormation is deleted via CFN, the deletion is permanent i.e. there is no way to restore the deleted secret. Thus, if a CFN managed secret being referred inside a dynamic reference is deleted via CFN followed by an update to the resource containing the dynamic reference, then only workaround [2] can be used to unstuck the stack in this case.
