### ISSUE TITLE
(aws-opensearchserverless): CfnVpcEndpoint exceeds CloudFormation 32-character limit

### ISSUE THREAD

**Issue by mvs5465** [aws/aws-cdk#24138]
### Describe the bug

Instantiating a CfnVpcEndpoint with a long name will exceed the CloudFormation character limit

```
    new aws_opensearchserverless.CfnVpcEndpoint(this, 'vpc-endpoint', {
      name: `very-long-name-that-exceeds-32-characters-vpc-endpoint`
    });
```

### Expected Behavior

CDK should automatically truncate the name if it is too long

### Current Behavior

Stack creation fails

### Reproduction Steps

See above

### CDK CLI Version

2.64.0

### Node.js Version

n/a

### OS

n/a

### Language

Typescript

**Comment by peterwoodworth** [comment]
Hey @mvs5465,

Using our L1/Cfn resources is akin to using CloudFormation directly - just as if you built a CloudFormation template and specified this resource with this name.  They cannot be aware of any restrictions like this that are on the service side. On the other hand, L2 resources can have logic that throws/truncates if the name is too long, or if any other configurations are invalid.

Let me know if you have any other questions, thanks!

**Comment by mvs5465** [comment]
> Hey @mvs5465,
> 
> Using our L1/Cfn resources is akin to using CloudFormation directly - just as if you built a CloudFormation template and specified this resource with this name. They cannot be aware of any restrictions like this that are on the service side. On the other hand, L2 resources can have logic that throws/truncates if the name is too long, or if any other configurations are invalid.
> 
> Let me know if you have any other questions, thanks!

Thanks @peterwoodworth, that makes sense and is good to know!
