### ISSUE TITLE
aws-rds: ParameterGroup construct does not have `defaultChild` set

### ISSUE THREAD

**Issue by clementallen** [aws/aws-cdk#24140]
### Describe the bug

`parameterGroup.node.defaultChild` is `undefined` instead of an instance of `CfnDBParameterGroup`

### Expected Behavior

I expect `parameterGroup.node.defaultChild` to return instance of `CfnDBParameterGroup`, but it is currently `undefined`

### Current Behavior

`parameterGroup.node.defaultChild` returns `undefined`

### Reproduction Steps

```typescript
const app = new App();
const stack = new Stack(app);
const parameterGroup = new ParameterGroup(this, 'parameter-group', {
    engine: DatabaseInstanceEngine.postgres({ version: PostgresEngineVersion.VER_14_5 }), // Can be any
});
const cfnParameterGroup = parameterGroup.node.defaultChild as CfnDBParameterGroup; // This is undefined
```

### CDK CLI Version

2.64.0

### Node.js Version

18.14.0

### OS

macOS Ventura 13.2

### Language

Typescript

### Language Version

4.9.5

**Comment by peterwoodworth** [comment]
This construct won't create the `CfnDbParameterGroup` or `CfnDbClusterParameterGroup` resources until the `bindToCluster()` or `bindToInstance()` methods are called. These will be called automatically if this `ParameterGroup` construct is passed in to an Instance or Cluster construct. The first one of these to bind will be set as the default child.

See details here https://github.com/aws/aws-cdk/blob/fb67c77855967e7d493f85f4f2d31532efdd560c/packages/%40aws-cdk/aws-rds/lib/parameter-group.ts#L136-L162

Let me know if this doesn't clear things up for you 👍🏻

**Comment by clementallen** [comment]
Thanks @peterwoodworth, applying the code to access the underlying L1 construct after attaching the parameter group to a database worked fine.
