### ISSUE TITLE
SubnetSelection: setting onePerAz to true, still returns all subnets from an AZ

### ISSUE THREAD

**Issue by danblacklist** [aws/aws-cdk#24155]
### Describe the bug

When using subnetSelection as below, it still returns all subnets from all AZs whereas it should be returning just one per AZ.

```
const subnetSelection = {
      subnetType: ec2.SubnetType.PUBLIC,
      onePerAz: true
    }
```

Even the below returns all subnets from all AZs

```
const subOne = ec2.Subnet.fromSubnetId(this, "subOne", "subnet-3e92bb31")
    const subnetSelection = {
      subnets: [
        subOne
      ]
    }
```

I'm unable to find a way to get it to contain just one subnet.

### Expected Behavior

It should return one subnet per AZ

### Current Behavior

Its returning all subnets from all AZs

### Reproduction Steps

1. Create a SubnetSelection with above properties.
2. Use it inside `cdk.aws_ecs_patterns.ApplicationLoadBalancedFargateServiceProps` for `taskSubnets`
3. BOOM 

### Additional Information/Context

This was also highlighted in a previous issue : https://github.com/aws/aws-cdk/issues/6217

### CDK CLI Version

2.59.0 (build b24095d)

### Node.js Version

18.12.1.

### OS

Mac OS Ventura 13.2

### Language

Typescript

**Comment by peterwoodworth** [comment]
Thanks for raising this issue with us,

We have an open issue tracking this issue here #3126, please refer to that issue and use it for any other concerns. Thanks!
