### ISSUE TITLE
(dynamodb cdk): (spread operator on undefined variable)

### ISSUE THREAD

**Issue by jian7wang** [aws/aws-cdk#24150]
### Describe the bug

https://github.com/aws/aws-cdk/blob/554d049a6e5b88afdb8297e2075f30e0e1bef600/packages/%40aws-cdk/aws-dynamodb/lib/table.ts#L804

"props" can be undefined. Applying spread operator on undefined will throw run-time error.

### Expected Behavior

As above

### Current Behavior

As above.

### Reproduction Steps

As above

### CDK CLI Version

ANY

### Node.js Version

ANY

### OS

ANY

### Language

Typescript

**Comment by peterwoodworth** [comment]
Can you please provide more information? This doesn't throw for me

```

    const t = new Table(this, 'Table', {
      partitionKey: {
        name: 'key',
        type: AttributeType.STRING
      }
    })

    t.metric('metric');
```

**Comment by jian7wang** [comment]
Sample code that will throw error.

```
function sampleFunc(par1?: number[]) {
    console.log(...par1);
}

sampleFunc([1, 2, 3]);
sampleFunc();
```

'...par1' is not the best way to write code. Since par1 is optional, function may be called without supplying this parameter. So this parameter is undefined. Applying ... on undefined will throw exception.

The best way should be as 

https://github.com/aws/aws-cdk/blob/554d049a6e5b88afdb8297e2075f30e0e1bef600/packages/%40aws-cdk/aws-dynamodb/lib/table.ts#L841

**Comment by peterwoodworth** [comment]
Thanks, but I mean with CDK constructs and methods
