### ISSUE TITLE
(aws-codebuild): Static LinuxBuildImage don't return IBuildImage type

### ISSUE THREAD

**Issue by larskinder** [aws/aws-cdk#24164]
### Describe the bug

When updating the `CodeBuildOptions` in a CodePipeline pipeline to use a different `build_image`, I got an unexpected type exception `Expected type 'IBuildImage | None', got '() -> IBuildImage' instead`.

To me it seems that I get a callback function returned and not the IBuildImage. 

### Expected Behavior

When setting the `CodeBuildOptions` as follows, I would expect an `IBuildImage` type return when referencing an AMI enum `codebuild.LinuxBuildImage.STANDARD_6_0`. 

```
code_build_defaults=pipelines.CodeBuildOptions(
      build_environment=codebuild.BuildEnvironment(
            build_image=codebuild.LinuxBuildImage.STANDARD_6_0,
 ),
 ```

### Current Behavior

Exception is thrown, as wrong type is returned. 
`Expected type 'IBuildImage | None', got '() -> IBuildImage' instead`

### Reproduction Steps

Use Python CDK >=v2.50.0, create a `pipelines.CodePipeline` and override the default `CodeBuildOptions` like this.

```
# Create CodePipeline pipeline for deploying infrastructure
 pipeline = pipelines.CodePipeline(
      self,
      "BaseInfraPipeline",
      code_pipeline=pipeline_base,
      code_build_defaults=pipelines.CodeBuildOptions(
             build_environment=codebuild.BuildEnvironment(
                 build_image=codebuild.LinuxBuildImage.STANDARD_6_0,
        ),
```

### Possible Solution

Update return type. 

### CDK CLI Version

2.64.0

### Node.js Version

v16.15.1

### OS

MacOS

### Language

Python

### Language Version

3.10.8

**Comment by RomainMuller** [comment]
I'm unable to reproduce this issue with the following code (running Python 3.10.10 / `aws-ckd-lib` 2.64.0):

```py
from aws_cdk import (
   App,
   Stack,
)
from aws_cdk.pipelines import (
   CodePipeline,
   CodeBuildOptions,
   ShellStep,
)
from aws_cdk.aws_codebuild import (
   BuildEnvironment,
   LinuxBuildImage,
)

app = App()
stack = Stack(app, "PythonStack")

pipeline = CodePipeline(stack, "Pipeline",
                        synth=ShellStep("Synth", commands=[]),
                        code_build_defaults=CodeBuildOptions(
                           build_environment=BuildEnvironment(
                              build_image=LinuxBuildImage.STANDARD_6_0,
                           )
                        ),
)

```

Using a virtual env under `.venv` and the following pyright config:

```json
{
  "include": [
    "app.py"
  ],
  "venv": ".venv",
}
```

I get the following result:

```console
$ pyright --venv-path .
Loading configuration file at /Users/rmuller/Development/Repro/Python/pyrightconfig.json
Assuming Python version 3.10
Assuming Python platform Darwin
Auto-excluding **/node_modules
Auto-excluding **/__pycache__
Auto-excluding **/.*
stubPath /Users/rmuller/Development/Repro/Python/typings is not a valid directory.
Searching for source files
Found 1 source file
pyright 1.1.293
0 errors, 0 warnings, 0 informations 
Completed in 2.303sec
```

At this stage I'm a bit puzzled as to why you are hitting the error... we are likely going to need additional information... If you were able to build a `Docker` image that consistently hits the issue you are facing, this would very likely help (this is for lack of a better idea of what would lead us in the right direction).
