### ISSUE TITLE
(ecs): small refactor for PortMapping ease of change

### ISSUE THREAD

**Issue by bun913** [aws/aws-cdk#24170]
### Describe the feature

Sorry if I have the wrong category for the Issue or the wrong place for the discussion!

While looking at Issue #23509, I was surprised by the following `addPortMappings` conditional branch.

https://github.com/aws/aws-cdk/blob/de097ee9b40c983d733d31c420389933ea32f6d6/packages/%40aws-cdk/aws-ecs/lib/container-definition.ts#L567-L607

The ContainerDefinition class is responsible for many of the responsibilities, and many if statements are added to verify PortMapping's sanity.

I feel that by writing down if statements like this, we lose the ease of modification.

Therefore, I would like to refactor it so that many contributors can easily modify it here in a way that does not affect the existing system!

### Use Case

ECS is a very widely used service, and I believe it is a service that will continue to see many bug fixes and feature additions.

I think that every time we add more properties in the future, we will make it harder to make changes by making miscellaneous changes!

I want to make it easy for many developers to contribute to this project!

### Proposed Solution

I think `ContainerDefinition` has too many responsibility.

An if statement is written in `addPortMappings` that assumes all contexts.

https://github.com/aws/aws-cdk/blob/de097ee9b40c983d733d31c420389933ea32f6d6/packages/%40aws-cdk/aws-ecs/lib/container-definition.ts#L567-L607

For example, this nested if statement is also commented as Sevice Connect logick, but now I don't know what the decision logic is for.

https://github.com/aws/aws-cdk/blob/de097ee9b40c983d733d31c420389933ea32f6d6/packages/%40aws-cdk/aws-ecs/lib/container-definition.ts#L578-L606

So, I suggest creating a PortMap or similarly named class (I think it would be a Value Object) like below.

```ts
export class PortMap {
  readonly portmap: PortMapping;
  readonly namedPorts: Map<string, PortMapping>;
  readonly networkMode: NetworkMode;

  constructor(pm: PortMapping, np: Map<string, PortMapping>, nwm: NetworkMode) {
    this.portmap = pm;
    this.namedPorts = np;
    this.networkMode = nwm;
    this.hasRequiredProp();
    this.canServiceConnect();
  }

  private hasRequiredProp() {
    if ( this.portmap.name == '') {
      throw new Error('Port mapping name cannot be an empty string.');
    }
  }
  private canServiceConnect() {
    // validation
  }
  private addNamedPort() {
    // return new NamedPort(Don'n change curret taskdef propertiy)
  }
}
```

I thought it would make for a more prospective code by taking the responsibility for checking the sanity of PortMapping related properties out of the picture!

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.64.0

### Environment details (OS name and version, etc.)

macOS Monterey

**Comment by peterwoodworth** [comment]
Thanks for providing this feedback and your suggestions on how to improve this code after your previous experience of attempting to change it. @madeline-k you have some good context around this library, what do you think about this refactoring suggestion?
