### ISSUE TITLE
pipelines: defining dockerCredentials does not enable "docker pull"

### ISSUE THREAD

**Issue by nisan-p** [aws/aws-cdk#24179]
### Describe the bug

Defining `dockerCredentials` for CodePipeline does not enable `docker pull ...` in commands.

### Expected Behavior

The `docker pull ...` to succeed.

### Current Behavior

The `docker pull ...` results in `... no basic auth credentials` error.

### Reproduction Steps

```
const myRepository = Repository.fromRepositoryArn(
  this,
  'MyRepository',
  `arn:aws:ecr:${development.region}:${development.account}:repository/my-repo`
);
myRepository.addToResourcePolicy(
  new PolicyStatement({
    sid: 'AllowCodeBuildToPull',
    effect: Effect.ALLOW,
    actions: [
      'ecr:BatchGetImage',
      'ecr:GetDownloadUrlForLayer',
    ],
    principals: [
      new ServicePrincipal('codebuild.amazonaws.com'),
      new AccountPrincipal(Aws.ACCOUNT_ID),
    ]
  })
);

const pipeline = new CodePipeline(this, 'Name', {
  pipelineName: 'Name',
  crossAccountKeys: true,
  dockerEnabledForSynth: true,
  dockerCredentials: [
    DockerCredential.ecr([
      myRepository,
    ], {
      usages: [
        DockerCredentialUsage.SYNTH,
      ]
    })
  ],
  synth: new ShellStep('Synth', {
    input: CodePipelineSource.connection('my/repo', branch, {
      connectionArn: connectionArn,
      codeBuildCloneOutput: true,
    }),
    installCommands: [
      `docker pull ${development.account}.dkr.ecr.${development.region}.amazonaws.com/my-repo:latest`,
    ],
    commands: [
      'mvn verify',
      'cd infra',
      'npm install',
      'npm run test',
      `npm run cdk synth -- -c branch="${branch}"`,
    ],
    primaryOutputDirectory: 'infra/cdk.out',
  }),
});
```

### Possible Solution

Now I have to run `aws ecr get-login-password --region ${development.region} | docker login --username AWS --password-stdin ${development.account}.dkr.ecr.${development.region}.amazonaws.com` before the pull.

### CDK CLI Version

2.63.0 (build 7f4e35e)

### Node.js Version

v14.17.4

### OS

aws/codebuild/standard:5.0

### Language

Typescript

**Comment by peterwoodworth** [comment]
Thanks for reporting this @nisan-p, we've been able to reproduce this with the code you've provided.

I'm not 100% sure if this is configured correctly since I have never tested this use case before, so I'm going to research a bit to see if there's anything else that needs to be done in this scenario and get back to you. Thanks!

**Comment by pahud** [comment]
Hi,

To enable the IAM role of the pipeline to pull images from ECR:

1.  You need to grant the pipeline role the read access of the ECR repo.
2. You need to explicit run [aws ecr get-login-password](https://awscli.amazonaws.com/v2/documentation/api/2.0.34/reference/ecr/get-login-password.html) with AWS CLI v2 and pass to docker login before you execute the `docker pull`.


So basically I would explore something like this:

```ts
// import an existing repo
const repo = Repository.fromRepositoryArn(..)
// define my pipline
const pipeline = new CodePipeline(...)
// grant the read access to the pipeline role
repo.grantRead(pipeline.role);
```

I hope this helps.

**Comment by nisan-p** [comment]
Yes, as stated in the original, I can make it work like this but why do I need to add explicit login if there's a property like `dockerCredentials` for which I pass the repository? Feels counter intuitive. While testing I didn't find that `repo.grantRead(pipeline.role);` would be enough.

**Comment by pahud** [comment]
@nisan-p 

I just read the doc [Authenticating to Docker registries](https://github.com/aws/aws-cdk/tree/main/packages/@aws-cdk/pipelines#authenticating-to-docker-registries) and looked into the implementation behind `pipelines.DockerCredential.ecr`, the [EcrDockerCredential](https://github.com/aws/aws-cdk/blob/74318c7d22bfc00de9e005f68a0a6aaa58c7db39/packages/%40aws-cdk/pipelines/lib/docker-credentials.ts#L149) class essentially takes care of the grantPull() for you so I believe you don't need to explicitly do that yourself. But it seems `aws ecr get-login-password` is still required before you are able to docker pull the images from ecr. Yeah I think we definitely need to improve the doc on ECR with cdk-pipeline.

**Comment by pahud** [comment]
Hi @nisan-p 

Please check out my sample below. This sample essentially:

1. run `docker build` to build a new container image
2. `docker push` to a private ECR repo

As you can see, you'll need to run `aws ecr get-login-password` in the `installCommands`.

I hope this working sample helps.

```ts
import * as cdk from 'aws-cdk-lib';
import { pipelines,
aws_ecr as ecr, 
aws_iam as iam,
CfnOutput} from 'aws-cdk-lib'
import { CfnOutcome } from 'aws-cdk-lib/aws-frauddetector';
import { Construct } from 'constructs';
// import * as sqs from 'aws-cdk-lib/aws-sqs';

export class PipelinesTsStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    // create a new ECR repo
    const repo = new ecr.Repository(this, 'EcrRepo', {
      removalPolicy: cdk.RemovalPolicy.DESTROY,
    });
    // create a pipeline that docker build the image and push to ECR
    const pipeline = new pipelines.CodePipeline(this, 'Pipeline', {
      dockerEnabledForSynth: true,
      dockerCredentials: [
        pipelines.DockerCredential.ecr([repo], {
          usages: [ pipelines.DockerCredentialUsage.SYNTH ],
        }),
      ],
      synth: new pipelines.ShellStep('DockerBuildAndPush', {
        input: pipelines.CodePipelineSource.connection('pahud/nyancat-docker-image', 'main', {
          connectionArn, // Created using the AWS console * });',
        }),
        installCommands: [
          `aws ecr get-login-password | docker login --username AWS --password-stdin ${cdk.Aws.ACCOUNT_ID}.dkr.ecr.${cdk.Aws.REGION}.amazonaws.com`
        ],
        commands: [
          'git clone https://github.com/cristurm/nyan-cat.git nyancat',
          `docker build -t ${repo.repositoryUri}:mytag .`,
          `docker push ${repo.repositoryUri}:mytag`,
        ],
      }),
      codeBuildDefaults: {
        rolePolicy: [
          // additional policy required for image push. 
          // See https://docs.aws.amazon.com/AmazonECR/latest/userguide/repository-policy-examples.html
          new iam.PolicyStatement({
            actions: [
              'ecr:CompleteLayerUpload',
              'ecr:InitiateLayerUpload',
              'ecr:PutImage',
              'ecr:UploadLayerPart',
            ],
            resources: [`${repo.repositoryArn}`],
          })
        ]
      }
    });
  }
}
```
