### ISSUE TITLE
(@aws-cdk/aws-batch-alpha): Add convenience grant methods

### ISSUE THREAD

**Issue by daniel-j-h** [aws/aws-cdk#24178]
### Describe the feature

Ideally the batch constructs would provide convenience .grant* methods to e.g. grant job submission for the most common use cases.

### Use Case

A common use case is to have e.g. a Lambda start (or terminate) an AWS Batch job.

At the moment we need to manually add policy statements for `batch:SubmitJob` for example even internally here

https://github.com/aws/aws-cdk/blob/fb67c77855967e7d493f85f4f2d31532efdd560c/packages/@aws-cdk/aws-stepfunctions-tasks/lib/batch/submit-job.ts#L273-L283

### Proposed Solution

It would be great to have functionality like

```typescript
const fn = new lambda.Function(...);

const jobQueue = new batch.JobQueue(..);
const jobDef = new batch.JobDefinition(..);

jobQueue.grantSubmitJob(fn); // <-
jobDef.grantSubmitJob(fn); // <-
```

or similar, instead of having to write the policies manually for the AWS Batch constructs.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.64.0

### Environment details (OS name and version, etc.)

Ubuntu 22.04

**Comment by pahud** [comment]
Yes I believe we can implement it in the L2 construct class:

https://github.com/aws/aws-cdk/blob/ce18037b2ba2b872dd1ed21fda71fd2ee4701353/packages/%40aws-cdk/aws-batch/lib/job-queue.ts#L86-L135

I am making it as p2 but any community PR would be appreciated.

**Comment by comcalvi** [comment]
Closing this one in favor of #16020, since all the context is on that one
