### ISSUE TITLE
(sqs + lambda): SQS + Lambda concurrency set to 1 does not work

### ISSUE THREAD

**Issue by leantorres73** [aws/aws-cdk#24180]
### Describe the bug

The issue happens when setting lambda concurrency to 1 with sqs event consumer (I can't use the new attribute `maxConcurrency` from the sqs event source because the minimum is 2 and I need it to be 1). 
So setting `reservedConcurrentExecutions` it's generating a weird behavior. 

All messages are in flight and the lambda is only processing the first one (in this case I set also batchSize = 1 but should not be relevant), the rest of the messages are in flight until they go to the DLQ (the lambda is free to process more of them but that never happens).

I have the same stack in serverless and it's working, and the fun part (that's why I'm reporting this here), is that if I go into the AWS console and manually change `reservedConcurrentExecutions` to 2, and then set it to 1 again, it starts working well. 

### Expected Behavior

Lambda concurrency to 1 as an SQS event consumer should process all messages

### Current Behavior

Lambda only process the first message, the others are in flight until timeout and they go to the dead letter queue

### Reproduction Steps

1- Create a Lambda with `reservedConcurrentExecutions` = 1
2- Create a queue and a dead letter queue
3- set the lambda an event source of the queue
4- send multiple messages into the queue
5- You will see all of them in flight except for the first one that is processed (in this case I set also batchSize = 1 but should not be relevant)

### CDK CLI Version

2.64.0

### Node.js Version

14

### OS

MacOS

### Language

Typescript

**Comment by nholmes3** [comment]
@leantorres73 did you ever figure out how to correctly configure a queue and lambda function to only process 1 message at a time?

**Comment by vadymhimself** [comment]
@leantorres73 @nholmes3 did you find a way to sequentially process from an SQS queue ?
