### ISSUE TITLE
(ec2): (Amazon Linux 2022 uses different kernel to Amazon Linux 2)

### ISSUE THREAD

**Issue by taylorb-syd** [aws/aws-cdk#24193]
### Describe the bug

When you deploy an Amazon Linux 2022 image it will use a Systems Manager Public Parameter based method to define which image to pull. At the moment, this is constructed based classes like `AmazonLinuxKernel` which has one parameter, a static `KERNEL5_X` which is a static value set to '5.10'. Amazon Linux 2022 also enforces use of the `KERNEL5_X` parameter.

Amazon Linux 2022 is running on Kernel 5.15, whereas Amazon Linux 2 is running on Kernel 5.10.

### Expected Behavior

When synthesizing, selecting a `MachineImage.latestAmazonLinux` with `AmazonLinuxGeneration.AMAZON_LINUX_2022` it should produce a parameter name to a kernel 5.15, for example:

```
/aws/service/ami-amazon-linux-latest/al2022-ami-kernel-5.15-arm64
```

### Current Behavior

When synthesizing, selecting a `MachineImage.latestAmazonLinux` with `AmazonLinuxGeneration.AMAZON_LINUX_2022`  it produces a paramater name to a kernel 5.10. As in the Expected Behaviour we get:

```
/aws/service/ami-amazon-linux-latest/al2022-ami-kernel-5.15-arm64
```

### Reproduction Steps

Using Python I used the following code to generate my machine image:

```python3
machine_image = MachineImage.latest_amazon_linux(
    cpu_type=AmazonLinuxCpuType.ARM_64,
    generation=AmazonLinuxGeneration.AMAZON_LINUX_2022
    )
```

### Possible Solution

Currently `KERNEL5_X` is a static string, however it could be replaced with a function that will take in `AmazonLinuxGeneration` and produce a different kernel version depending on the provided generation. This will however break most peoples stacks as now KERNEL5_X is a callable, not an emun.

Therefore the best way to solve this will be to the modify the [following](https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/aws-ec2/lib/machine-image.ts#L405):

```
    if (generation === AmazonLinuxGeneration.AMAZON_LINUX_2022) {
      kernel = '5.15' // Explicit override as Amazon Linux 2 and Amazon Linux 2022 do not track the same kernel minor versions
```

 

### Additional Information/Context

I think it is important to note that AMAZON_LINUX is depercated, and thus we should seriously consider changing the default to `AMAZON_LINUX_2` [here](https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/aws-ec2/lib/machine-image.ts#L398).

### CDK CLI Version

2.65.0 (build 5862f7a)

### Node.js Version

v19.6.0

### OS

macOS 12.6.3

### Language

Python

### Language Version

3.10.10

**Comment by pahud** [comment]
closing as duplicate https://github.com/aws/aws-cdk/issues/21011
