### ISSUE TITLE
(aws-logs): update log retention lambdas to nodejs18.x

### ISSUE THREAD

**Issue by wilhen01** [aws/aws-cdk#24202]
### Describe the feature

Similar to #23682, Lambdas created via Log Retention settings are [currently using the Node 14 runtime](https://github.com/aws/aws-cdk/blob/ce18037b2ba2b872dd1ed21fda71fd2ee4701353/packages/%40aws-cdk/aws-logs/lib/log-retention.ts#L173). Node 14 is EOL at the end of April, just over two months away. These lambdas should be updated to Node 18 prior to that EOL. 

### Use Case

All lambdas created by aws-cdk internally should be updated prior to EOL.

### Proposed Solution

Update to NODEJS_18_X when creating lambda in aws-logs.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.63.0

### Environment details (OS name and version, etc.)

Mac OS

**Comment by pahud** [comment]
Yes we should get it fixed. Are you interested to submit a PR for that?

**Comment by wilhen01** [comment]
@pahud I've raised https://github.com/aws/aws-cdk/pull/24203 to cover this. Hopefully all correct 😄

**Comment by peterwoodworth** [comment]
We only need to track this on one issue https://github.com/aws/aws-cdk/issues/23682
