### ISSUE TITLE
(Aspects): Aspects do not work during unit tests

### ISSUE THREAD

**Issue by mvs5465** [aws/aws-cdk#24220]
### Describe the bug

Aspects work as expected when attempting to synth or deploy from an entrypoint file like `src/main.ts`. However, it appears that something is interrupting this when the same code is used in a unit test.

### Expected Behavior

Aspect annotations should appear on stacks and templates when used in a unit test.

### Current Behavior

Aspects have no effect when used in a unit test.

### Reproduction Steps

Add this code to your `src/main.ts` file and run `cdk synth`. It will log a number of issues to the console.

However if you add it during a unit test, eg `src/test/Bucket.test.ts`, it appears that Aspects no longer function.

```
import * as cdk from 'aws-cdk-lib';
import * as cdk_nag from 'cdk-nag';

const app = new cdk.App();
const stack = new cdk.Stack(app, 'test-stack');

cdk.Aspects.of(stack).add(new cdk_nag.AwsSolutionsChecks({ verbose: true }));

new cdk.aws_s3.Bucket(stack, 'bucket');

app.synth().stacks.forEach(curStack => {
  console.log(JSON.stringify(curStack.template, null, 2));
});
```

This will output a JSON representation of the stack and no annotations have been added. Creating a basic S3 bucket like this should light up the AwsSolutionsChecks with many errors (missing replication, encryption, logging, etc). However, nothing occurs.

### Additional Information/Context

Related issues:
- https://github.com/aws/aws-cdk/issues/17805
- https://github.com/aws/aws-cdk/issues/18921
- https://github.com/cdklabs/cdk-nag/issues/728
- https://github.com/cdklabs/cdk-nag/issues/1135

### CDK CLI Version

2.65.0

### Node.js Version

v16.14.0

### OS

na

### Language

Typescript

### Language Version

TypeScript (4.8.4)

**Comment by mvs5465** [comment]
I'm not sure why, but wrapping the calls inside of the jest test wrappers appears to fix it?

```
      beforeAll(() => {
        cdk.Aspects.of(this.stack).add(new cdk_nag.AwsSolutionsChecks({ verbose: true }));
      });

      test('No unsuppressed Warnings', () => {
        const warnings = Annotations.fromStack(this.stack).findWarning(
          '*',
          Match.stringLikeRegexp('AwsSolutions-.*'),
        );
        if (warnings.length > 0) {
          error(warnings);
        }
        expect(warnings).toHaveLength(0);
      });
```

**Comment by mvs5465** [comment]
Sorry, this is incorrect.

**Comment by jugarpeupv** [comment]
Hello, in case someone from the future steps into this problem i have a video explaining how to solve it

https://www.youtube.com/watch?v=JwwNsSiHECE
