### ISSUE TITLE
aws_rds: DatabaseCluster deletion_protection does not default to false

### ISSUE THREAD

**Issue by rittneje** [aws/aws-cdk#24236]
### Describe the bug

The CDK docs say the following:

> deletion_protection (Optional[bool]) – Indicates whether the DB cluster should have deletion protection enabled. Default: - true if removalPolicy is RETAIN, false otherwise

### Expected Behavior

If I first deploy a stack with that flag set to `True`, and then I deploy a stack update with the flag not set at all, it should disable deletion protection, as the docs claim.

### Current Behavior

CloudFormation instead stops tracking the deletion protection property.

### Reproduction Steps

Deploy a stack with a `DatabaseCluster` like so:

```python
aws_rds.DatabaseCluster(stack, "Database", ..., deletion_protection=True, ...)
```

Then remove the `deletion_protection` argument from the constructor. Look at the output of `cdk diff`. Then deploy the stack and confirm in the RDS console that deletion protection is still enabled.

### Possible Solution

CDK is not passing the `DeletionProtection` property in the CloudFormation template at all if the `deletion_protection` parameter is not passed. So the docs are really describing CloudFormation's default behavior, which is only applicable to creating a new resource.

Instead, either CDK MUST always set the `DeletionProtection` flag in the stack template to abide by its current documentation, or the documentation needs to be amended to distinguish resource creation from update.

### CDK CLI Version

2.60.0

### Node.js Version

v18.13.0

### OS

Alpine 3.17

### Language

Python

### Language Version

3.11.1

**Comment by pahud** [comment]
Yes. Database replacement is something we definitely should avoid. I'll bring this to the team for more visibility. Any additional comments or ideas are appreciated here.

**Comment by pahud** [comment]
According to this, I think by default `deletionProtection` is actually `undefined`, which is equivalent to `false` only when the resource is initially created:

https://github.com/aws/aws-cdk/blob/8492dfefd209dfcceb528bc30dea4be55eaa66c7/packages/aws-cdk-lib/aws-rds/lib/private/util.ts#L77-L83

However, if you update the resource from explicit `deletionProtection: true` to `deletionProtection: undefined` and `removalPolicy != RETAIN`, cloudformation seems to just leave it as is and not set it to `false`, which explains we are seeing this value remains `true` in the console.

I think we should update the document to clarify this.
