### ISSUE TITLE
aws-redshift: allow changing of table column names

### ISSUE THREAD

**Issue by Rizxcviii** [aws/aws-cdk#24234]
### Describe the feature

Currently, the construct is based around the name of a table column being fixed, however redshift enables the user to change the name of the table columns, if needed.

### Use Case

If we have an existing column name that is not distinctive enough, further columns added in the future might "clash" with the "meaning" behind the original table column.

### Proposed Solution

Possibly by implementing an extra `id` attribute to the existing `Column` construct. However this would require a possible refactor to the checking conditions that already exist, due to the `name` attribute being used currently. This is definitely **NOT** a critical change, and infra developers could currently alleviate this problem by using the AWS console, and reworking their tables from there.
However, if this is implementable by just a simple addition of an `id` attribute, then this would be a good step in the right direction I believe for the Redshift Construct.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.56.0

### Environment details (OS name and version, etc.)

Amazon Linux 2

**Comment by pahud** [comment]
Thank you. Is this related to https://github.com/aws/aws-cdk/issues/20495 ?

I am making it as p2 and any PR submission would be appreciated.

**Comment by Rizxcviii** [comment]
> Thank you. Is this related to #20495 ?
> 
> I am making it as p2 and any PR submission would be appreciated.

Potentially, if we are able to create a solution that allows `id`s to be used, then perhaps we can use that to work on the ordering of the columns. My feature request did not have that in mind, but I do see it as a way of solving #20495 easier.
