### ISSUE TITLE
aws-eks: unable to install oci chart from public ecr

### ISSUE THREAD

**Issue by chn217** [aws/aws-cdk#24244]
### Describe the bug

When installing an OCI chart from public ECR using CDK on any region other than us-east-1 as follows:
        const chart = cluster.addHelmChart('xxx-chart', {
            chart: '<chart name>',
            repository: 'oci://public.ecr.aws/<registry_alias>',
            values: {
                replicaCount: 3,
            },
        });
CDK deployment reported an error as follows:
 ❌ Deployment failed: Error: Stack Deployments Failed: Error: The stack named DruidEksStack failed to deploy: UPDATE_ROLLBACK_COMPLETE: Received response status [FAILED] from custom resource. Message returned: Error: b'\nAn error occurred (UnsupportedCommandException) when calling the GetAuthorizationToken operation: GetAuthorizationToken command is only supported in us-east-1.\nLogin Succeeded\nError: GET "https://public.ecr.aws/v2/l3p6w5z4/external-secrets/tags/list": unexpected status code 400: denied: Your Authorization Token is invalid.\n'

### Expected Behavior

The OCI chart on public ECR should be installed successfully.

### Current Behavior

The OCI chart installation was unsuccessful due to the following error:
 ❌ Deployment failed: Error: Stack Deployments Failed: Error: The stack named DruidEksStack failed to deploy: UPDATE_ROLLBACK_COMPLETE: Received response status [FAILED] from custom resource. Message returned: Error: b'\nAn error occurred (UnsupportedCommandException) when calling the GetAuthorizationToken operation: GetAuthorizationToken command is only supported in us-east-1.\nLogin Succeeded\nError: GET "https://public.ecr.aws/v2/l3p6w5z4/external-secrets/tags/list": unexpected status code 400: denied: Your Authorization Token is invalid.\n'

### Reproduction Steps

- Install the public ecr chart from any region other than us-east-1 
- cdk deployment

### Possible Solution

aws-cdk/packages/@aws-cdk/aws-eks/lib/kubectl-handler/helm/__init__.py:

Line 114:
            f"aws ecr-public get-login-password --region {region} | " \

This region should be hard coded to us-east-1 as aws ecr-public commands only support us-east-1 region.

### CDK CLI Version

2.60.0

### Node.js Version

v14.17.6

### OS

Mac Os 

### Language

Typescript

**Comment by pahud** [comment]
duplicate https://github.com/aws/aws-cdk/issues/23977
