### ISSUE TITLE
codepipeline-actions: Outdated link in Readme on ECS deployment role

### ISSUE THREAD

**Issue by alFReD-NSH** [aws/aws-cdk#24248]
### Describe the issue

This link about permissions of cross account ECS deployment role is outdated and redirects to the main page of Codepipeline docs: https://github.com/aws/aws-cdk/blob/52edf29/packages/@aws-cdk/aws-codepipeline-actions/README.md?plain=1#L848

Basically I want to know how exactly should that role be created for cross account access.

### Links

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_codepipeline_actions-readme.html#ecs
https://github.com/aws/aws-cdk/blob/52edf29/packages/@aws-cdk/aws-codepipeline-actions/README.md?plain=1#L848

**Comment by khushail** [comment]
Hi @alFReD-NSH ,thanks for reporting this. I can confirm the same as seen by you.

Reg. the role creation for cross-account access, this [link](https://aws.amazon.com/premiumsupport/knowledge-center/ecs-iam-role-another-account/) might be helpful to go through. 
I also found somewhat [similar issue ](https://github.com/aws/aws-cdk/issues/17558)in the past, with the suggested solution(https://github.com/aws/aws-cdk/pull/17917#issuecomment-993853634).

Let me know if this does not resolve what you are looking for. Would be happy to assist further. Thanks

**Comment by alFReD-NSH** [comment]
> this [link](https://aws.amazon.com/premiumsupport/knowledge-center/ecs-iam-role-another-account/) might be helpful to go through. 

That's about ECS task assuming role into another account. I want to know how to create the IAM role for cross account deployment via EcsDeployAction.

> I also found somewhat [similar issue](https://github.com/aws/aws-cdk/issues/17558) in the past, with the suggested solution([#17917 (comment)](https://github.com/aws/aws-cdk/pull/17917#issuecomment-993853634)).

Yes, I read it as it was the first result on Google. It doesn't show how the IAM role should be created.
