### ISSUE TITLE
iam: SamlConsolePrincipal does not work in aws.amazon.com-regions

### ISSUE THREAD

**Issue by Wurstnase** [aws/aws-cdk#24243]
### Describe the bug

With https://github.com/aws/aws-cdk/pull/24034 the default `SAML:aud` changed from `aws.amazon.com` to `"Ref": "AWS::URLSuffix"` which is resolves to `amazonaws.com`.

### Expected Behavior

When not in china, it should resolves to `aws.amazon.com`.

### Current Behavior

it is `"Ref": "AWS::URLSuffix"`, which resolves to `amazonaws.com`.

### Reproduction Steps

install `2.65.0`
create an `iam.SamlConsolePrincipal`

### Possible Solution

https://github.com/zorrofox/aws-cdk/blob/f8fe1d292feb3fc39a99687bf454a829302c4ff5/packages/%40aws-cdk/aws-iam/lib/principals.ts#L740

```diff
      StringEquals: {
-        'SAML:aud': cdk.Aws.PARTITION==='aws-cn'? 'https://signin.amazonaws.cn/saml': `https://signin.${cdk.Aws.URL_SUFFIX}/saml`,
+        'SAML:aud': cdk.Aws.PARTITION==='aws-cn'? 'https://signin.amazonaws.cn/saml': `https://signin.aws.amazon.com/saml`, 
      },
```

### CDK CLI Version

2.65.0

### Node.js Version

-

### OS

-

### Language

Python

**Comment by Wurstnase** [comment]
Here is the list of all possible endpoints: https://docs.aws.amazon.com/general/latest/gr/signin-service.html

I'm wondering, that i did not find amazonaws.cn in this list as in https://github.com/aws/aws-cdk/pull/24034 introduced.

**Comment by pahud** [comment]
Yes I think you are right.

According to the [doc](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/pseudo-parameter-reference.html#cfn-pseudo-param-urlsuffix), urlsuffix is typically `amazonaws.com` in non-china AWS commercial regions while `aws.amazon.com` should be use instead here.
