### ISSUE TITLE
cdk.json : toolkitBucketName not working

### ISSUE THREAD

**Issue by pbougie** [aws/aws-cdk#24259]
### Describe the bug

Setting configuration option `toolkitBucketName` in `cdk.json` does not work. Using the CLI instead with `cdk bootstrap --toolkit-bucket-name=custom-bucket-name` does work as expected.

### Expected Behavior

Bucket name should be custom name.

### Current Behavior

Uses default toolkit bucket name.

### Reproduction Steps

`cdk.json`:
```json
{
  "toolkitBucketName": "custom-bucket-name"
}
```

### CDK CLI Version

2.65.0 (build 5862f7a)

### Node.js Version

19.6.1

### OS

macOS 13.2.1

### Language

Typescript

**Comment by khushail** [comment]
Hi @pbougie , thanks for reporting this bug. I could also confirm that the bucket name provided in cdk.json was not used. 

I am not sure why this is not working though I will co-ordinate with my team to get this issue looked at and update the documentation(with working scenario) if needed.

**Comment by lpizzinidev** [comment]
@pbougie 
This is probably just a documentation error.

Looking at the code:
https://github.com/aws/aws-cdk/blob/3d7505b5a9c3daf5edfecdb4576b555bfe8d7553/packages/aws-cdk/lib/cli.ts#L503

So  you should be able to specify the attribute in `cdk.json` with: 
```
{
    "toolkitBucket": {
        "bucketName": "custom-bucket-name"
    }
}
```

**Comment by pbougie** [comment]
I can confirm this works. The documentation needs updating. Both the `toolkitBucketName`  and `bootstrapKmsKeyId` configuration keys are wrong in the [`cdk.json` documentation](https://docs.aws.amazon.com/cdk/v2/guide/cli.html#cli-config). They should be:

```json
{
    "toolkitBucket": {
        "bucketName": "custom-bucket-name",
        "kmsKeyId": "kms-key-id"
    }
}
```
