### ISSUE TITLE
aws-cdk / cli: option to have the `synth`'s `--quiet` option exposed in `cdk.json`

### ISSUE THREAD

**Issue by gburke-ppb** [aws/aws-cdk#24251]
### Describe the feature

The vast majority of the time when running `cdk synth` we don't want the template to be written -- I can't think of a time when I _do_ want it to be written...

Whilst the `--quiet` option can be added to the command line, it would be nice to be able to specify this in any of the `cdk.json` files

### Use Case

When running `cdk synth`, the output is written to the `cdk.out/` folder, and this is generally what I look at when I want to view the CF Templates, etc.  On the console I really only want to be seeing the warnings and errors, never the template.

Adding `--quiet` each and every time I want to synth is cumbersome, often forgotten (which could mean scrolling back several hundred lines to see any other outputs), and is additional characters to have to type each and every time.

### Proposed Solution

Either a
```
"quiet": true
```
or
```
"synthesize": {
    "quiet": true
}
```
in the cdk.json, picked up in any of the files (personally I'd add it to `~/.cdk.json`).

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.65.0

### Environment details (OS name and version, etc.)

MacOS, although the feature would be for all OSes.

**Comment by khushail** [comment]
Hi @gburke-ppb , thanks for reaching out. I am marking this issue as p2, which means that we are unable to work on this immediately. 

We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. You can reach out to the [cdk.dev](http://cdk.dev/) community on [Slack](https://cdk.dev/) to solicit support for reprioritization.

Although it would be great if you would like to contribute.Here is the [contributing guide](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md).
