### ISSUE TITLE
pipelines: Multiple pipelines from different branches are getting triggered with same commit

### ISSUE THREAD

**Issue by flexelem** [aws/aws-cdk#24278]
### Describe the bug

Hey guys, please let me know if this is not the correct place for this topic. Our Pipeline -> UpdatePipeline -> SelfMutate action is failing with error `Error: Stack Deployments Failed: InvalidChangeSetStatus: Cannot delete ChangeSet in status CREATE_IN_PROGRESS`. We have two pipelines where each of them are running in different accounts based on different branches; `development` and `main`. And these two CodePipelines are defined in same cdk stack with parameterized resources based on the environment name. From the `CloudFormation -> Changes` section I can verify that the Logical IDs of *Assets are getting changed which causes to pipelines get triggered.

```
file -> cdk.ts

new AtxPipelineStack(app, 'atx-app-pipeline', {
  env: {
    account: Constants.PIPELINE_ACCOUNT_ID,
    region: Constants.PIPELINE_ACCOUNT_REGION,
  },
});
```

```
file -> atx-app-pipeline-stack.ts

export class AtxAppPipelineStack extends Stack {
  constructor(scope: Construct, id: string, props: StackProps) {
    super(scope, id, props);

    const devInfraPipeline = new CodePipeline(this, 'atx-app-infrastructure-pipeline', {
      // pipeline configuration
    });

    const mainInfraPipeline = new CodePipeline(this, 'main-atx-app-infrastructure-pipeline', {
      // pipeline configuration
    });

    const stages: AtxAppEnv[] = this.node.tryGetContext('stages');
    stages.forEach((stage) => {
      if (stage.type === 'prod') {
        mainInfraPipeline.addStage(
          new AtxAppPipelineStage(this, `${stage.type}-atx-app-stage`, {
            env: {
              account: stage.context['accountId'],
              region: stage.context['region'],
            },
            type: stage.type,
            context: stage.context,
          }),
          { pre: [new ManualApprovalStep(`promote-to-${stage.type}`)] },
        );
      } else if (stage.type === 'stage') {
        mainInfraPipeline.addStage(
          new AtxAppPipelineStage(this, `${stage.type}-atx-app-stage`, {
            env: {
              account: stage.context['accountId'],
              region: stage.context['region'],
            },
            type: stage.type,
            context: stage.context,
          }),
        );
      } else {
        devInfraPipeline.addStage(
          new AtxAppPipelineStage(this, `${stage.type}-atx-app-stage`, {
            env: {
              account: stage.context['accountId'],
              region: stage.context['region'],
            },
            type: stage.type,
            context: stage.context,
          }),
        );
      }
    });

    devInfraPipeline.buildPipeline();
    mainInfraPipeline.buildPipeline();

    // Add SNS Topic for pipeline
    const pipelineTopic = new Topic(this, 'atx-app-pipeline-sns-topic');

    // Configure Slack channel configuration
    const slack = SlackChannelConfiguration.fromSlackChannelConfigurationArn(
      this,
      'slack-config',
      Fn.importValue(`${AtxExports.SLACK_CONFIGURATION_ARN_EXPORT}`),
    );

    //Add notification rule for infra pipeline events - dev
    const devInfraPipelineNotifRule = new NotificationRule(this, 'atx-app-infra-notif-rule', {
      detailType: DetailType.BASIC,
      source: devInfraPipeline.pipeline,
      events: [
        'codepipeline-pipeline-manual-approval-succeeded',
        'codepipeline-pipeline-manual-approval-failed',
        'codepipeline-pipeline-action-execution-failed',
      ],
      targets: [pipelineTopic],
    });

    devInfraPipelineNotifRule.addTarget(slack);

    //Add notification rule for infra pipeline events - main
    const mainInfraPipelineNotifRule = new NotificationRule(this, 'main-atx-app-infra-notif-rule', {
      detailType: DetailType.BASIC,
      source: mainInfraPipeline.pipeline,
      events: [
        'codepipeline-pipeline-manual-approval-succeeded',
        'codepipeline-pipeline-manual-approval-failed',
        'codepipeline-pipeline-action-execution-failed',
      ],
      targets: [pipelineTopic],
    });

    mainInfraPipelineNotifRule.addTarget(slack);
  }
}
```

```
file -> atx-app-pipeline-stage.ts

export class AtxAppPipelineStage extends Stage {
  constructor(scope: Stack, name: string, props: AtxAppEnv) {
    super(scope, name, props);

    new AtxAppStack(this, 'atx-app-pipeline-stack', {
      type: props.type,
      context: props.context,
    });

    //Tags
    Tags.of(this).add('stage', `${props.type}`);
    Tags.of(this).add('stackName', `${this.stageName}`);
  }
}
```

As you can see there are two pipelines created inside the same stack with different configuration and both of them have their own Stage definitions. There is no any shared resource (except the source code itself). When we push a new commit into `development` branch the related pipeline is getting triggered and pipeline with `main` branch remains still. Later on, for unknown reason the main pipeline is also getting triggered and running on the latest commit it has built before. Any help is appreciated. And please let me know if you need more information from me. Thanks!

### Expected Behavior

We are expecting only the development pipeline to be triggered when there is a new commit pushed into development branch.

### Current Behavior

Both of the pipelines are getting triggered sequentially even though we are not merging any code from development into main branch.

### Reproduction Steps

Create multiple pipelines with different source branches in same stack will make both of them to be triggered.

### Additional Information/Context

Here is the error logs from CodeBuild;

```
[16:39:56] atx-app-pipeline: checking if we can skip deploy
[16:39:57] atx-app-pipeline: template has changed
[16:39:57] atx-app-pipeline: deploying...
[16:39:57] Removing existing change set with name cdk-deploy-change-set if it exists
[16:39:57] Call failed: deleteChangeSet({     "StackName": "atx-app-pipeline",     "ChangeSetName": "cdk-deploy-change-set" }) => Cannot delete ChangeSet in status CREATE_IN_PROGRESS (code=InvalidChangeSetStatus)
 
❌  atx-app-pipeline failed: InvalidChangeSetStatus: Cannot delete ChangeSet in status CREATE_IN_PROGRESS
at Request.extractError (/usr/local/lib/node_modules/aws-cdk/lib/index.js:31:33843)
at Request.callListeners (/usr/local/lib/node_modules/aws-cdk/lib/index.js:31:76646)
at Request.emit (/usr/local/lib/node_modules/aws-cdk/lib/index.js:31:76094)
at Request.emit (/usr/local/lib/node_modules/aws-cdk/lib/index.js:31:182419)
at Request.transition (/usr/local/lib/node_modules/aws-cdk/lib/index.js:31:175971)
at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/aws-cdk/lib/index.js:31:140843)
at /usr/local/lib/node_modules/aws-cdk/lib/index.js:31:141173
at Request.<anonymous> (/usr/local/lib/node_modules/aws-cdk/lib/index.js:31:176263)
at Request.<anonymous> (/usr/local/lib/node_modules/aws-cdk/lib/index.js:31:182494)
at Request.callListeners (/usr/local/lib/node_modules/aws-cdk/lib/index.js:31:76814) {
code: 'InvalidChangeSetStatus',
time: 2023-02-22T16:39:57.288Z,
requestId: '5f8cae0c-ea38-40c8-9296-04bf09d36e3f',
statusCode: 400,
retryable: false,
retryDelay: 171.71356661217717
}
 
❌ Deployment failed: Error: Stack Deployments Failed: InvalidChangeSetStatus: Cannot delete ChangeSet in status CREATE_IN_PROGRESS
at deployStacks (/usr/local/lib/node_modules/aws-cdk/lib/index.js:347:130558)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async CdkToolkit.deploy (/usr/local/lib/node_modules/aws-cdk/lib/index.js:347:146846)
at async exec4 (/usr/local/lib/node_modules/aws-cdk/lib/index.js:402:51795)
[16:39:57] Notices refreshed
 
Stack Deployments Failed: InvalidChangeSetStatus: Cannot delete ChangeSet in status CREATE_IN_PROGRESS
[16:39:57] Error: Stack Deployments Failed: InvalidChangeSetStatus: Cannot delete ChangeSet in status CREATE_IN_PROGRESS
at deployStacks (/usr/local/lib/node_modules/aws-cdk/lib/index.js:347:130558)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async CdkToolkit.deploy (/usr/local/lib/node_modules/aws-cdk/lib/index.js:347:146846)
at async exec4 (/usr/local/lib/node_modules/aws-cdk/lib/index.js:402:51795)
 
[Container] 2023/02/22 16:39:57 Command did not exit successfully cdk -a . deploy atx-app-pipeline --require-approval=never --verbose exit status 1
[Container] 2023/02/22 16:39:57 Phase complete: BUILD State: FAILED
[Container] 2023/02/22 16:39:57 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: cdk -a . deploy atx-app-pipeline --require-approval=never --verbose. Reason: exit status 1
[Container] 2023/02/22 16:39:57 Entering phase POST_BUILD
[Container] 2023/02/22 16:39:57 Phase complete: POST_BUILD State: SUCCEEDED
[Container] 2023/02/22 16:39:57 Phase context status code:  Message:

```

### CDK CLI Version

2.50.0 (build 4c11af6)

### Node.js Version

18

### OS

Linux

### Language

Typescript

### Other information

Here is also the TreeView for `atx-app-pipeline` stack

![Screen Shot 2023-02-22 at 20 52 58](https://user-images.githubusercontent.com/6500753/220716059-ed99c300-9e48-4850-90de-a6e2396fdab1.png)

Additionally, here is another screenshot from CloudFormation creating a changeset on both pipelines.

![Screen Shot 2023-02-22 at 20 01 18](https://user-images.githubusercontent.com/6500753/220717122-6164bd15-2753-4f1e-8002-256f74e9a3a7.png)

**Comment by khushail** [comment]
Hi @flexelem , thanks for reaching out.

Before providing any suggestion, I would really like to know and understand why you are using same stack for multiple branches and pipelines. Appreciate your response.

**Comment by flexelem** [comment]
Hi @khushail thanks for replying back. Initially we were using trunk based development with only one pipeline having multiple stages in different accounts. Later on, we decided to separate out stages on different branches with different pipelines to make our development process to fit our needs. So, we thought creating another CodePipeline inside the same stack would do the trick since we are not changing logical IDs. And this approach was working. I am guessing the problem occurs when we add new changes into the `atx-app-pipeline-stack.ts` which caused to generate different hashes for Assets making pipelines to get triggered for SelfMutate. Please let me know if this approach is not recommended and should we have separate stacks? Thanks!

**Comment by khushail** [comment]
Hi @flexelem , Any asset/stack change results in the mutation of pipeline. Please see [this](https://github.com/aws/aws-cdk/issues/9080#issuecomment-661137716) As you have mentioned about the different hashes, t[here](https://github.com/aws/aws-cdk/issues/9080#issuecomment-661687798) is also a solution provided here. You could use this approach for decoupling hashes for assets which might stop the triggering.
I also see a [fix](https://github.com/aws/aws-cdk/pull/9183) was applied but there has been some roadblocks. So I would also suggest you to separate the stacks and then try the deployment.

**Comment by flexelem** [comment]
Hi @khushail thanks for sharing the related threads! We separated pipelines into different stacks which seems to be fixed the problem we were having.
