### ISSUE TITLE
route53: private hosted zone is not tagged with 'aws:cloudformation:stack-name' tag upon creation

### ISSUE THREAD

**Issue by j4zzcat** [aws/aws-cdk#24287]
### Describe the bug

When creating a PrivateHostedZone, the resource is created but it is not tagged with the `aws:cloudformation:stack-name` tag.

### Expected Behavior

As any resource created with the CDK, a PrivateHostZone should be tagged with the `aws:cloudformation:stack-name` tag.

### Current Behavior

Resource not tagged.

### Reproduction Steps

```
...
val phz = PrivateHostedZone.Builder.create(app, "dummy-phz")
  .zoneName("foo.bar")
  .vpc(vpc)
  .build()
...
```

### CDK CLI Version

2.65.0 (build 5862f7a)

### Node.js Version

v19.6.1

### OS

macOS 13.1

### Language

Java

**Comment by khushail** [comment]
Thanks @j4zzcat for reaching out. it would be great if you could clarify why you expect adding tags by AWS for the resources.

**Comment by j4zzcat** [comment]
All the other constructs I used so far added this tag - vpc, subnet, security group, route table, nat, ec2 instance, inbound resolver etc. With this tag, life's easy identifying resources of a particular stack.

**Comment by khushail** [comment]
Thanks for the response @j4zzcat . AFAIK, there are no default tags applied on resources. Tags are created by user via constructs in the app and once the code is synthesized, these are applied to all the AWS resources it deploys. Here is reference for the [tags](https://docs.aws.amazon.com/cdk/v2/guide/tagging.html#tagging_example) and how these can be implemented.
Let me know if that helps clarify your question.

**Comment by j4zzcat** [comment]
I can only say that when I'm using CDK to create resources, the tag `aws:cloudformation:stack-name` *is* created on many of the resources, including, but not limited to, vpc, subnet, security group, route table, nat, ec2 instance and inbound resolver. Further, one cannot create tags prefixed with `aws` - and so doesn't it mean that it's being done by AWS code somewhere? maybe on a lower level like CloudFormation?

**Comment by khushail** [comment]
@j4zzcat , I re-checked the documentations for [resource tags](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-resource-tags.html),  but I am not sure why tags are not created with PrivateHostedZone resource. I will reach out to internal team to get it sorted. Thank you for reporting this.

**Comment by khushail** [comment]
Hey @j4zzcat , [here is a doc](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-hostedzone-hostedzonetag.html) that details out how cloudformation support adding tags to hostedZone, tags can be added l,tags are implemented through interface HostedZoneTagProperty , something like this , as mentioned in this article -https://docs.aws.amazon.com/cdk/api/v2/java/software/amazon/awscdk/services/route53/CfnHostedZone.html

```java
 Example:

     // The code below shows an example of how to instantiate this type.
     // The values are placeholders you should change.
     import software.amazon.awscdk.services.route53.*;
     CfnHostedZone cfnHostedZone = CfnHostedZone.Builder.create(this, "MyCfnHostedZone")
             .hostedZoneConfig(HostedZoneConfigProperty.builder()
                     .comment("comment")
                     .build())
             .hostedZoneTags(List.of(HostedZoneTagProperty.builder()
                     .key("key")
                     .value("value")
                     .build()))
             .name("name")
             .queryLoggingConfig(QueryLoggingConfigProperty.builder()
                     .cloudWatchLogsLogGroupArn("cloudWatchLogsLogGroupArn")
                     .build())
             .vpcs(List.of(VPCProperty.builder()
                     .vpcId("vpcId")
                     .vpcRegion("vpcRegion")
                     .build()))
             .build();
```
 Please let me know if this works for you!
