### ISSUE TITLE
aws-cdk: Asset publishing fails every second time

### ISSUE THREAD

**Issue by abrose** [aws/aws-cdk#24298]
### Describe the bug

Hello,

We are using CDK with [SST](https://sst.dev) as a higher level wrapper. One of our SST Apps consists of seven stacks - the whole thing builds up a pretty huge and parallelized step function which calls many lambda functions which itself do different machine learning stuff. Now when deploying one or several of the stacks suddenly starts failing. And this is the strange part - when the deployment is executed again, then it works. Next time - fails. Then works again.

### Expected Behavior

Previously everything worked perfectly. We already suspected that the issue might be the number of resources of the stack, so we split some of the stacks to several smaller stacks but this also didn't help.

### Current Behavior

Here is the screenshot of the error (private parts blacked out):
![cdk_build_error](https://user-images.githubusercontent.com/11835836/220854487-2bad9fd3-cc5e-4033-b73b-8b0adba98d4f.jpg)

Unfortunately the error message is not helpful at all, atm I have no clue what the reason for the failures is and how to fix it. I tried to delete the .build folder after each build, but it doesn't help. I'm using SST 1.18.4, CDK 2.50.0 on Node 16.13.1. I tried switching to node 18 but it also didn't help.

### Reproduction Steps

Simply running ```npx sst deploy``` triggers the CDK build and the build fails every second time.

### CDK CLI Version

2.50.0

### Node.js Version

16.13.1

### OS

Ubuntu 20.04 (WSL2@Win11)

### Language

Typescript, Python

### Language Version

Python 3.9,

### Other information

Any hint or suggestion would be very appreciated since we need to meet a deadline and this issue is a hard blocker for us right now. 

Regards,
Alfred

**Comment by joni3k** [comment]
We've noticed the same issue with one of our CDK apps, which deploys a big amount of lambdas.

**Comment by mrgrain** [comment]
Can you run your `cdk` commands with `--debug` and `-vvv` for additional output.
(But I don't know if/how you can achieve this with SST)

**Comment by abrose** [comment]
I can run ```sst deploy --verbose``` which also enables the CDK verbose mode, but I'm not sure if the debug mode is also enabled. Anyway, this is the output using --verbose, there is slightly more output, but nothing really new.
![cdk_build_error2](https://user-images.githubusercontent.com/11835836/220919056-a6b27c9b-3a56-4f7a-887f-cc2fc9c72fb2.jpg)

Looking at the output I had a quite stupid thought - could it possibly be the case that due to some async  stuff the publishing process starts before the asset zip is finished? Apparently there is a matching zip file but it still has the suffix "_tmp". Maybe the large amount of resources in the stack slows down the zip creation to a point where this happens?

**Comment by abrose** [comment]
Here's another bit of information which might help - I tried to deploy changes only in one substack (with sst one can target substacks individually) and this worked perfectly.

**Comment by mrgrain** [comment]
It's an interesting though. Something like that might well be the case. 

Looking at the code the promise appears to be awaited correctly though
https://github.com/aws/aws-cdk/blob/fb67c77855967e7d493f85f4f2d31532efdd560c/packages/cdk-assets/lib/private/archive.ts#L15-L16


Would you be able to post the verbose output for one of the successful second runs?

**Comment by abrose** [comment]
Unfortunately I can't figure out how to "force" SST to use a newer CDK build. I created a post in SST's [discord](https://discord.com/channels/983865673656705025/1078335587972567060)  for this issue and hope that there is a simple way to test this out. 
Regarding the verbose output of a successful (mostly cached) run - on the first glance I could not identify any interesting parts. The entire log is almost 500kb large and there is too much to black out - can I send it directly to you somehow? It's a client's project and the stack names could give away some sensible bits of information about the product we're building.

**Comment by mrgrain** [comment]
> Unfortunately I can't figure out how to "force" SST to use a newer CDK build. I created a post in SST's [discord](https://discord.com/channels/983865673656705025/1078335587972567060) for this issue and hope that there is a simple way to test this out.
Yeah that's something you will have to take up with SST unfortunately. :( 

> Regarding the verbose output of a successful (mostly cached) run - on the first glance I could not identify any interesting parts.

I basically want to confirm if the previously failing asset in question (identifiable by the hash) is loaded from cache when run the second time, or if building works the second time around. If loaded from cache there would be a message in gray prefixed with `cached`, otherwise you would see the `build: Zip....` from above.

> The entire log is almost 500kb large and there is too much to black out - can I send it directly to you somehow? It's a client's project and the stack names could give away some sensible bits of information about the product we're building.
Not sure what your requirements are. My DMs are open on cdk.dev though. I'm `@mrgrain` there as well.

**Comment by mrgrain** [comment]
Based on the other issue, it might also help to disable concurrency. That would make everything slower though.

**Comment by abrose** [comment]
The failing hash from the earlier run appears multiple times in the following successful run but there is no "cached" string or anything else indicating that it was loaded from cache. Here is an example of one of the occurrences
![cdk_build_error3](https://user-images.githubusercontent.com/11835836/220981835-d7bbe6d6-8a4b-4906-8028-26ae833ad72f.jpg)

There is also nothing being rebuilt as far as I can see. 

Regarding disabling concurrency - I've already tried to disable SST's concurrency by setting `SST_BUILD_CONCURRENCY=1` but this didn't solve the issue.

**Comment by abrose** [comment]
So, we found a way to force SST to use the newer CDK (by using package.json overrides) and yes the problem is gone. So now we need to find out if and how fast SST will update it's dependency and if we continue to use it or decide to use CDK directly. 
Thank you for your support!

**Comment by mrgrain** [comment]
That's excellent news. Will be good to know what SST comes back with, but overrides might be a workable solution either way.

Closing this issue here.
