### ISSUE TITLE
(aws-rds): DatabaseCluster with MySQL 8.0 uses aurora_load_from_s3_role parameter when s3ImportBuckets is set

### ISSUE THREAD

**Issue by asif-ali-244** [aws/aws-cdk#24297]
### Describe the bug

When database cluster is created using arbitrary MySql engine version, `engine: DatabaseClusterEngine.auroraMysql({version: AuroraMysqlEngineVersion.of("8.0.mysql_aurora.3.02.2", "8.0")})` and the `s3ImportBuckets` option is set, it automatically creates `aurora_load_from_s3_role` parameter instead of `aws_default_s3_role`. Parameter `aurora_load_from_s3_role` is not supported in MySql engine version `8.0`

### Expected Behavior

When the major version of MySql is set to `8.0`, it should create the `aws_default_s3_role` parameter instead of `aurora_load_from_s3_role`.

### Current Behavior

`DatabaseCluster` engine created using 
`DatabaseClusterEngine.auroraMysql({version: AuroraMysqlEngineVersion.of("8.0.mysql_aurora.3.02.2", "8.0")})` creates the parameter `aurora_load_from_s3_role` that is not supported by MySql major version 8.0.

### Reproduction Steps

```typescript
this._rds = new DatabaseCluster(this, 'DbCluster', {
            engine: DatabaseClusterEngine.auroraMysql({version: AuroraMysqlEngineVersion.of("8.0.mysql_aurora.3.02.2", "8.0")}),
            instanceProps: {
                vpc: props.Vpc,
                vpcSubnets: props.dbSubnets,
                instanceType: InstanceType.of(InstanceClass.T3, InstanceSize.MEDIUM),
                publiclyAccessible: false,
                securityGroups: [props.dbSecurityGroup],
                deleteAutomatedBackups: true
            },
            cloudwatchLogsRetention: RetentionDays.ONE_WEEK,
            storageEncrypted: true,
            deletionProtection: false,
            credentials: Credentials.fromGeneratedSecret('admin', {
            }),
            removalPolicy: RemovalPolicy.DESTROY,
            defaultDatabaseName: "database",
            s3ImportBuckets: props.bucket
        });
```

### Possible Solution

`AuroraMysqlEngineVersion` doesn't have an option to set `_combineImportAndExportRoles` to `true` when the engine is configured using arbitrary version. Having an additional argument `combineImportAndExportRoles` in arbitrary version selection of engine would resolve this issue.

https://github.com/aws/aws-cdk/blob/c96c17da55feb5735d65130adc8af758a8468450/packages/%40aws-cdk/aws-rds/lib/cluster-engine.ts#L432-L434

Adding an additional argument `combineImportAndExportRoles`
```typescript
public static of(auroraMysqlFullVersion: string, auroraMysqlMajorVersion?: string, combineImportAndExportRoles?: boolean): AuroraMysqlEngineVersion { 
   return new AuroraMysqlEngineVersion(auroraMysqlFullVersion, auroraMysqlMajorVersion, combineImportAndExportRoles); 
 } 
```
Now we can force the cluster to use `aws_default_s3_role` parameter by passing `true`
```typescript
engine: DatabaseClusterEngine.auroraMysql({version: AuroraMysqlEngineVersion.of("8.0.mysql_aurora.3.02.2", "8.0", true)}),

``` 

### CDK CLI Version

2.65.0

### Node.js Version

16.17.1

### OS

Mac OS

### Language

Typescript

**Comment by pahud** [comment]
Yeah I think it makes sense but maybe we should bump 3.02.2 enum as it seems to be a low-hanging fruit?

https://github.com/aws/aws-cdk/blob/236ecde4378a3ac307d662a3f3e28b14b44468fe/packages/%40aws-cdk/aws-rds/lib/cluster-engine.ts#L422

**Comment by pahud** [comment]
Just submitted https://github.com/aws/aws-cdk/pull/24304 for a quick version bump.

**Comment by pahud** [comment]
closed by https://github.com/aws/aws-cdk/pull/24304
