### ISSUE TITLE
cdk-java: Regression on Lex Bot DataPrivacy

### ISSUE THREAD

**Issue by faermanj** [aws/aws-cdk#24301]
### Describe the bug

Since 2.56.0, bot deploy fails with the following error:
```
 Properties validation failed for resource simplebot with message:
#/DataPrivacy: required key [ChildDirected] not found
#/DataPrivacy: extraneous key [childDirected] is not permitted
8:45:14 AM | ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack
```

The different capitalization suggests a typo.

### Expected Behavior

2.56.0 works fine, synth and deploy

### Current Behavior

Deploy fails

### Reproduction Steps

This prevents any bot to be deployed, as the property is required.
So just create a bot using CDK

my class:
`package com.myorg;

import software.amazon.awscdk.services.iam.ManagedPolicy;
import software.amazon.awscdk.services.iam.Role;
import software.amazon.awscdk.services.iam.ServicePrincipal;
import software.constructs.Construct;
import software.amazon.awscdk.Stack;
import software.amazon.awscdk.StackProps;
import software.amazon.awscdk.services.lex.CfnBot;
// import software.amazon.awscdk.Duration;
// import software.amazon.awscdk.services.sqs.Queue;

import java.util.List;

public class SimpleBotStack extends Stack {
    public SimpleBotStack(final Construct scope, final String id) {
        this(scope, id, null);
    }

    public SimpleBotStack(final Construct scope, final String id, final StackProps props) {
        super(scope, id, props);

        var privacy = CfnBot.DataPrivacyProperty.builder()
                .childDirected(false)
                .build();
        var idleTimeout = 60 * 30L;
        var botName = "simple-bot";

        var botPrincipal = ServicePrincipal.Builder.create("lexv2.amazonaws.com").build();
        var botPolicyArn = "arn:aws:iam::aws:policy/AmazonLexRunBotsOnly";
        var botPolicy = ManagedPolicy.fromManagedPolicyArn(this, "simple-bot-policy", botPolicyArn);
        var botPolicies = List.of(botPolicy);

        var role = Role.Builder.create(this, "simple-bot-role")
                .assumedBy(botPrincipal)
                .managedPolicies(botPolicies)
                .build();
        var roleArn = role.getRoleArn();

        var br = createLocaleBR();
        var locales = List.of(br);
        var bot = CfnBot.Builder.create(this, "simple-bot")
                .dataPrivacy(privacy)
                .idleSessionTtlInSeconds(idleTimeout)
                .name(botName)
                .roleArn(roleArn)
                .botLocales(locales)
                .autoBuildBotLocales(true)
                .build();

    }

    private CfnBot.BotLocaleProperty createLocaleBR() {
        var fallback = CfnBot.IntentProperty.builder()
                .name("FallbackIntent")
                .description("Fallback if not understood")
                .parentIntentSignature("AMAZON.FallbackIntent")
                .build();
        var oi = CfnBot.SampleUtteranceProperty.builder()
                .utterance("Oi")
                .build();
        var salve = CfnBot.SampleUtteranceProperty.builder()
                .utterance("salve")
                .build();
        var utts = List.of(oi, salve);
        var hello = CfnBot.IntentProperty.builder()
                .name("HelloIntent")
                .description("Say hello to the bot")
                .sampleUtterances(utts)
                .build();
        var intents = List.of(hello, fallback);
        var locale = CfnBot.BotLocaleProperty.builder()
                .localeId("pt_BR")
                .nluConfidenceThreshold(0.5)
                .intents(intents)
                .build();
        return locale;
    }

}
`

### Possible Solution

fix the property name?

### CDK CLI Version

2.57.0+

### Node.js Version

16.19.0

### OS

macos

### Language

Java

**Comment by pahud** [comment]
Hi, 

Does this still exist in the latest v2.66.0?

**Comment by peterwoodworth** [comment]
Hey @faermanj,

the dataPrivacy prop accepts an object of type `any`, so you will want to refrain from using `CfnBot.DataPrivacyProperty.builder()` as this will generate improperly cased properties. You can see how to implement a generic structure in Java [here](https://docs.aws.amazon.com/cdk/v2/guide/work-with-cdk-java.html#java-cdk-idioms)

This was caused by a breaking change to the spec, and we are working on making sure we aren't put in this pickle again. Let me know if you have any more concerns, thanks!

**Comment by mirodrr** [comment]
How do I resolve this when using Python? I am encountering the same issue

**Comment by mirodrr** [comment]
@peterwoodworth

**Comment by vaughngit** [comment]
> How do I resolve this when using Python? I am encountering the same issue

        # Define DataPrivacy as a dictionary with the correct casing
        data_privacy_property = {
            "ChildDirected": False
        }

        chatbot = lex.CfnBot(self, 
                        "chatbot",
                        name="CDKChatbot",
                        data_privacy=data_privacy_property, 
                        idle_session_ttl_in_seconds=90, 
                        role_arn=props.chatbot_role_run
                        )

**Comment by irenegl3** [comment]
How do I resolve this when using TypeScript? I am encountering the same issue

**Comment by ghdezc** [comment]
> How do I resolve this when using TypeScript? I am encountering the same issue

For reference similar than the @vaughngit solution:

`**const dataPrivacyProperty = {
            "ChildDirected": false
        };**

        // Crear el bot de Amazon Lex utilizando el archivo subido a S3
        const yesNoBot = new lex.CfnBot(this, 'chatbot', {
            name: 'CDKChatbot',
            **dataPrivacy: dataPrivacyProperty,**
            idleSessionTtlInSeconds: 300,
           roleArn: lexV2ServiceRole.roleArn,
        })`
