### ISSUE TITLE
static fromVersionArn method: Doesn't return IVersion

### ISSUE THREAD

**Issue by rtejwani1309** [aws/aws-cdk#24307]
### Describe the bug

I found the bug when one of my CX was using static fromVersionArn, to get the version in his CDK code to get the IVersion.

Code Snippet Used:
```
export function getLambdaFunctionAliasCfnReference(scope: Construct, lambdaFunctionAlias: lambda.Alias): lambda.Alias|lambda.IAlias {
    try {
        // Get the lambdaFunctionAliasArn from the SSM Parameter Store.
        // const lambdaFunctionAliasVersionArn = ssm.StringParameter.fromStringParameterName(
        //     scope,
        //     `${[lambdaFunctionAlias.node.id ](http://lambdafunctionalias.node.id/)}VersionArn`,
        //     `${[lambdaFunctionAlias.node.id ](http://lambdafunctionalias.node.id/)}VersionArn`
        // ).stringValue;

        const lambdaFunction = lambda.Function.fromFunctionArn(scope, `${[lambdaFunctionAlias.node.id ](http://lambdafunctionalias.node.id/)}Version`, 'arn:aws:lambda:us-west-2:336595061080:function:us-prod-web-requester');

        // Lookup LambdaFunctionAlias by AliasAttributes.
        // const lambdaFunctionAliasVersion = lambda.Version.fromVersionArn(scope, `${[lambdaFunctionAlias.node.id ](http://lambdafunctionalias.node.id/)}Version`, 'arn:aws:lambda:us-west-2:336595061080:function:us-prod-web-requester:1');
        const lambdaFunctionVersion = lambda.Version.fromVersionAttributes(scope, `${[lambdaFunctionAlias.node.id ](http://lambdafunctionalias.node.id/)}Version`, {
            lambda: lambdaFunction,
            version: '1'
        });

        return lambda.Alias.fromAliasAttributes(scope, `${[lambdaFunctionAlias.node.id ](http://lambdafunctionalias.node.id/)}`, {
            aliasName: 'prod',
            aliasVersion: lambdaFunctionVersion,
        });

        // 'arn:aws:lambda:us-west-2:336595061080:function:us-prod-web-requester:1:prod'
        // 'arn:aws:lambda:us-west-2:336595061080:function:us-prod-web-requester:prod:prod'

    } catch(e) {
        return lambdaFunctionAlias;
    }
}
```

When using the above, the stack was failing with the below error:

`Parameter arn:aws:lambda:us-west-2:336595061080:function:us-prod-web-requester:1:prod is not valid. Reason: Provided Arn is not in correct format. (Service: AmazonCloudWatchEvents; Status Code: 400; Error Code: ValidationException; Request ID: f9ba50d1-4231-48fb-a37e-0e390c9b8be1; Proxy: null)`

Further, when we tried using the same code just by using static fromVersionAttributes method, it got successfully created without any issues.

### Expected Behavior

The expected behaviour is to return IVersion

### Current Behavior

It is returning the Lambda ARN that was passed in the method static fromVersionArn

### Reproduction Steps

One can try using the method static fromVersionArn
https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-lambda.Version.html#static-fromwbrversionwbrarnscope-id-versionarn

And will face this issue

### Possible Solution

As a workaround usage of static fromVersionAttributes method resolves the issue for now.

### CDK CLI Version

2.x

### Node.js Version

node 16.x

### OS

MacOs

### Language

Typescript

### Language Version

NA

**Comment by peterwoodworth** [comment]
I can't just copy + paste this snippet, I had to modify it a bit and I'm finding that it's working properly. Can you please paste a clean reproduction which I don't have to modify at all? I suspect you have some bug in your code
