### ISSUE TITLE
AWS-RDS: Deleting Proxy Deletes Security Group Rule

### ISSUE THREAD

**Issue by StevieBoyWonder** [aws/aws-cdk#24305]
### Describe the bug

I have defined a child construct called `Database` that provisions a Security Group that is attached to a DB (databaseSecurityGroup), 1 Security group that has ingress to the DBSecurity Group (databaseAccessSecurityGroup) and a Cluster

In a stack, I've used my construct to spin an RDS Cluster Up, and I attached a proxy to it,
I am trying to remove the proxy by deleting the construct, while keeping the db.

But it results in cdk trying to remove the ingress rule from the db `databaseSecurityGroup`.

### Expected Behavior

I expect the proxy to delete and the security group I have defined in the child construct to be correctly configured, not missing a rule.

### Current Behavior

The proxy is deleted, but the 'databaseSecurityGroup' in the child construct has lost an ingress rule from the `databaseAccessSecurityGroup`

The deletion of the ingress rule on the `databaseSecurityGroup` results in all connectivity to the db being shut down since many resources may be connecting to the db through the `databaseAccessSecurityGroup` even if they are not using the proxy.

### Reproduction Steps

Define child construct called `Database` that provisions a Security Group and a Cluster

Note: Some things are omitted here as I don't think they apply to the issue and to be more succinct (vpc, subnets, etc) 

```
export class AuroraDatabase extends Construct {
  public readonly databaseAccessSecurityGroup: ec2.ISecurityGroup;
  public readonly databaseCluster: rds.IDatabaseCluster;

  constructor(scope: Construct, id: string, props: AuroraDatabaseProps) {
    super(scope, id);

    const databaseSecurityGroup = new ec2.SecurityGroup(
      this,
      "DatabaseSecurityGroup",
      {
        description: "security group attached to rds database",
      }
    );

    this.databaseAccessSecurityGroup = new ec2.SecurityGroup(
      this,
      "DatabaseAccessSecurityGroup",
      {
        description: "security group attached to things needing to connect to database",
      }
    );

    databaseSecurityGroup.addIngressRule(
      ec2.Peer.securityGroupId(
        this.databaseAccessSecurityGroup.securityGroupId
      ),
      ec2.Port.tcp(3306),
      "Allow MySQL TCP traffic from database access security group"
    );

    this.databaseCluster = new rds.DatabaseCluster(this, "DbCluster", {
      instanceProps: {
        securityGroups: [databaseSecurityGroup],
      },
      ....
    });
  }
}
```

In a stack, use the construct to spin an RDS Cluster Up, and attach a proxy to it.
```
// dedicated db
const db = new AuroraDatabase(this, `database`, {
  databaseName: props.service,
  stage: props.stage,
});

const dbProxy = db.databaseCluster.addProxy(`DatabaseProxy`, {
  secrets: [db.databaseCluster.secret!],
  securityGroups: [databaseAccessSecurityGroup],
});
```

Remove the `dbProxy` by deleting the construct, while keeping the db.
```
// dedicated db
const db = new AuroraDatabase(this, `database`, {
  databaseName: props.service,
  stage: props.stage,
});

//db proxy code deleted
```

It results in cdk trying to remove the ingress rule from the db `databaseSecurityGroup`.

Heres a snippet of the cdk diff
```
- │ ${database/DatabaseSecurityGroup.GroupId}                      │ In  │ TCP ${database/DbCluster.Endpoint.Port}                        │ ${database/DatabaseAccessSecurityGroup.GroupId}       
```

### CDK CLI Version

2.66

### Node.js Version

18.14.2

### OS

Mac Os Ventura 13.1

### Language

Typescript

### Language Version

Typescript 4.7.4

**Comment by peterwoodworth** [comment]
This ingress that is being removed is the one that is automatically created when you pass in a security group to the `addProxy()` method. It allows connections from the cluster to the proxy. This isn't removing the ingress rule you've created within your construct, so I believe this is expected behavior.

**Comment by StevieBoyWonder** [comment]
@peterwoodworth 

But you can see from my child construct that I explicitly have an ingress rule that should still continue to exist? 

I think the db proxy is removing a rule it thinks it added but did not, because it was already defined elsewhere.

**Comment by peterwoodworth** [comment]
If you're referring to 

```
    databaseSecurityGroup.addIngressRule(
      ec2.Peer.securityGroupId(
        this.databaseAccessSecurityGroup.securityGroupId
      ),
      ec2.Port.tcp(3306),
      "Allow MySQL TCP traffic from database access security group"
    );
```

You can see based on the description that this remains in the template, and that the ingress that was removed did not have this description

**Comment by StevieBoyWonder** [comment]
@peterwoodworth I'm not sure I'm following. 

When I add the proxy as a stack.

```
// dedicated db
const db = new AuroraDatabase(this, `database`, {
  databaseName: props.service,
  stage: props.stage,
});

const dbProxy = db.databaseCluster.addProxy(`DatabaseProxy`, {
  secrets: [db.databaseCluster.secret!],
  securityGroups: [databaseAccessSecurityGroup],
});
```

I observe that the DatabaseSecurityGroup has one ingress rule, and it has the description `Allow MySQL TCP traffic from database access security group`

This implies that this ingress rule was created as a part of the `AuroraDatabase` construct, not a part of the proxy. I don't actually see any ingress rule added as a part of adding a proxy? Perhaps cloud formation is able to detect that the rule already exists (Albeit with a different description), and doesn't create a duplicate rule.

Now when I remove the dbProxy

```
const db = new AuroraDatabase(this, `database`, {
  databaseName: props.service,
  stage: props.stage,
});
```

I observe through the CDK diff, and through the actually deploying, that the Proxy removes the rule.
There is no longer any rules on the DatabaseSecurityGroup. The one with the description `Allow MySQL TCP traffic from database access security group` is gone.

 To me this is a bug, because my existing and still valid stack has
```
databaseSecurityGroup.addIngressRule(
  ec2.Peer.securityGroupId(
    this.databaseAccessSecurityGroup.securityGroupId
  ),
  ec2.Port.tcp(3306),
  "Allow MySQL TCP traffic from database access security group"
);
```

in code, yet the security group does not reflect that.


If I had to hypothesize, the DB Proxy is intelligently adding ingress (unless a valid rule already exists), and it will _always_ try to remove the rule on delete. This behavior to me is a bug because the proxy addition/removal now has a side effect.

**Comment by peterwoodworth** [comment]
I'm still unable to reproduce this a second time around @StevieBoyWonder, using the exact reproduction code you've provided, I first deployed the stack without a proxy, then updated it to add the proxy, and removed the proxy again. The whole time the ingress rule we explicitly created was attached to the sg. Similarly, if I create it with the proxy first then remove the proxy, the rule was there the whole time.

You should be able to still find your ingress rule in your template as a prop of the security group.
