### ISSUE TITLE
(cdk_ecs): interactive property missing in container definition

### ISSUE THREAD

**Issue by mdeshmu** [aws/aws-cdk#24326]
### Describe the bug

We are trying to use this property https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ecs.CfnTaskDefinition.ContainerDefinitionProperty.html#interactive in a fargate task but when we add it using 

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ecs.FargateTaskDefinition.html#addwbrcontainerid-props

We get error "interactive" does not exist in type 'ContainerDefinitionOptions'. How can we solve this ?

One observation: 'interactive' property doesn't exist in non-cfn construct for container definition https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ecs.ContainerDefinitionOptions.html

### Expected Behavior

We should be able to specify 'interactive' property

### Current Behavior

throws error

### Reproduction Steps

try to create a fargate task using cdk and add 'interactive': true to container defintion

### CDK CLI Version

2.59.0

### Node.js Version

14.x

### OS

Amazon Linux 2

### Language

Typescript

### Language Version

3.9.10

**Comment by mdeshmu** [comment]
From https://github.com/aws/aws-cdk/issues/16025#issuecomment-900691683, containerDefinitions is a [Lazy Value](https://docs.aws.amazon.com/cdk/latest/guide/tokens.html#tokens_lazy), which means we can't use escape hatches to modify the properties that aren't exposed to our L2 constructs.

Is there any other workaround? If not, can we please add it as a feature please.

**Comment by pahud** [comment]
We probably need to add this in the [ContainerDefinitionOptions](https://github.com/aws/aws-cdk/blob/dee02a64197d6acfb0b15471d7bff9532dc037da/packages/%40aws-cdk/aws-ecs/lib/container-definition.ts#L102) so it could be rendered as expected. I am making it a p2 feature request and any PR submission is welcome and appreciated.

**Comment by mdeshmu** [comment]
@pahud I can raise for this one if time permits. Any sample PR would be useful to follow.
