### ISSUE TITLE
@aws-cdk/aws-s3-deployment: Stack update fails due to cloudformation didn't receive a response from custom resource

### ISSUE THREAD

**Issue by romanakash** [aws/aws-cdk#24327]
### Describe the bug

We have a BucketDeployment construct that was already deployed as part of a stack. When this stack is updated the stack update fails with this error 

`
CloudFormation did not receive a response from your Custom Resource. Please check your logs for requestId [999e88c0-e371-4ecb-bd1d-69ce8922feda]. If you are using the Python cfn-response module, you may need to update your Lambda function code so that CloudFormation can attach the updated version.`

I checked the logs the lambda which is part of the DeploymentBucket construct. It uploads the file using "aws s3" cli successfully, but it fails when it tries to send the response back to cloudformation.

`[ERROR]	2023-02-24T16:28:01.437Z | unable to send response to CloudFormation

[ERROR]	2023-02-24T16:28:01.437Z	HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/var/task/index.py", line 261, in cfn_send
    with contextlib.closing(urlopen(request)) as response:
  File "/var/lang/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/var/lang/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/var/lang/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/var/lang/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/var/lang/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/var/lang/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
`

### Expected Behavior

The stack update to happen successfully and the BucketDeployment lambda to send correct response to cloudformation. 

### Current Behavior

The stack update fails, and the BucketDeployment lambda had HTTP 404 error when sending response back to cloudformation.

### Reproduction Steps

`
new BucketDeployment(this, "bucket-id", {
            sources: [Source.asset(`file-location`)],
            destinationBucket: 's3-bucket',
            destinationKeyPrefix: 's3-key',
            role: role,
});
`

const role = new iam.Role(this, "s3DeploymentRole", {
            assumedBy: new iam.ServicePrincipal("lambda.amazonaws.com"),
            roleName,
        });
        role.addManagedPolicy(iam.ManagedPolicy.fromAwsManagedPolicyName("AmazonS3ReadOnlyAccess"));
        role.addManagedPolicy(iam.ManagedPolicy.fromAwsManagedPolicyName(
            "service-role/AWSLambdaBasicExecutionRole"
));

### CDK CLI Version

2.60.0

### Node.js Version

14.21.2

### OS

Amazon Linux

### Language

Typescript

**Comment by pahud** [comment]
Can you provide full sample code that we can run in out environment to reproduce this error?

You can quote your code with "```" for better reading experience as described [here](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code). Thanks.
