### ISSUE TITLE
(apigateway): (small refactor for LambdaAuthorizer.setupPermissions)

### ISSUE THREAD

**Issue by bun913** [aws/aws-cdk#24339]
### Describe the feature

When I was looking at the api-gateway module, I thought it would be easier to understand if I refactored the following code.

Now:

https://github.com/aws/aws-cdk/blob/d986e143df3cf9b42031eba0f5a2d9a71d6d9208/packages/%40aws-cdk/aws-apigateway/lib/authorizers/lambda.ts#L124-L138

My suggestion:

```ts
  /**
   * Sets up the permissions necessary for the API Gateway service to invoke the Lambda function.
   */
  protected setupPermissions() {
    if (this.role instanceof iam.Role) {
      this.addLambdaInvokePermission(this.role);
      return;
    }
    this.addDefaultPermisionRole();
  }

  /**
   * Add Default Permission Role for handler
   */
  private addDefaultPermisionRole() :void {
    this.handler.addPermission(`${Names.uniqueId(this)}:Permissions`, {
      principal: new iam.ServicePrincipal('apigateway.amazonaws.com'),
      sourceArn: this.authorizerArn,
    });
  }

  /**
   * Add Lambda Invoke Permission for LambdaAurhorizer's role
   */
  private addLambdaInvokePermission(role: iam.Role) :void {
    role.attachInlinePolicy(new iam.Policy(this, 'authorizerInvokePolicy', {
      statements: [
        new iam.PolicyStatement({
          resources: this.handler.resourceArnsForGrantInvoke,
          actions: ['lambda:InvokeFunction'],
        }),
      ],
    }));
  }
```

### Use Case

I will continue to do small refactorings so that more people will want to be involved in this project!

I feel that I would like to start by encapsulating functions and extracting code into meaningful chunks.

Not only this Issue, but I think this product could be refactored to make it even nicer!

### Proposed Solution

Plese refer to 'Describe the feature' section.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.66.1

### Environment details (OS name and version, etc.)

macOS Monterey

**Comment by pahud** [comment]
Thank you for your feedback and refactoring thoughts. As `aws-apigateway` has been stable, we tend to avoid code changes or refactoring unless necessary. But any community upvotes or feedbacks would definitely appreciated. Can you elaborate more about it if the existing code has any blockers and you need to introduce the code refactoring to remove them?

**Comment by bun913** [comment]
@pahud 

Thank you for your comment.

First of all I believe refactoring is necessary when there are few changes.

This project is particularly large, so I think we will accumulate more and more technical debt by adding code because we don't want to refactor a few things!

For example, please take a look at the following code from the aws-ecs package.

https://github.com/aws/aws-cdk/blob/7dd8b7e1ce88a13e597e52ff95353d74ab4807f1/packages/%40aws-cdk/aws-ecs/lib/container-definition.ts#L567-L607

By adding "if" statements and logic to existing functions, it becomes more and more difficult to understand what the intention of the code is and what the code is trying to do!

As for this code, it may not be an issue at this time.
However, I think it would be better to be able to make it clear in the code what the code is intended to do and that we want the function to be small and separate in this class.

Fortunately, this project has a lot of testing, so I believe the conditions are right for me to refactor.

However, I didn't know that some packages specifically avoid changes.

> As aws-apigateway has been stable, we tend to avoid code changes or refactoring unless necessary.

Thanks for letting me know.
