### ISSUE TITLE
aws-cdk-lib/aws_dynamodb: DynamoDB global tables should not use custom resource

### ISSUE THREAD

**Issue by nakedible-p** [aws/aws-cdk#24332]
### Describe the feature

Not exactly a new feature, but an improvement to the current one.

- In 2017, support was added for DynamoDB global tables via a separate module that "glues" tables together. This has since been deprecated and fully removed.
- In 2019 this support was converted to use the new DynamoDB global tables by just specifying `replicationRegions`, and a custom resource is provisioned to set up the replication. There is no longer a separate class for replicated dynamodb table.
- In 2021 support was added in CloudFormation to directly create DynamoDB global tables via the `AWS::DynamoDB::GlobalTable`. This was never added to CDK L2 constructs.
- It is now 2023...

Please add L2 support for CfnGlobalTable separately, or modify the current L2 support to instead use CfnGlobalTable directly rather than adding custom resources to mimic the same functionality.

### Use Case

I don't like additional custom resources than can break where "native" support is available. This seems to be just a remnant of the past.

### Proposed Solution

Either add GlobalTable as a separate resource, or modify the current implementation of Table. It maybe hard to keep compatibility with a stable module if modifying the current implementation.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### CDK version used

2.66.0 (build c96c17d)

### Environment details (OS name and version, etc.)

Linux codespaces-af5ba0 5.4.0-1103-azure #109~18.04.1-Ubuntu SMP Wed Jan 25 20:53:00 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by pahud** [comment]
Yes we definitely should consider having a L2 for `AWS::DynamoDB::GlobalTable`. I am making this a p1 feature request and please help us prioritize with :+1:.
