### ISSUE TITLE
(apprunner-alpha): only using .addEnvrionmentVariable() and .addSecret() fails to work

### ISSUE THREAD

**Issue by rogerchi** [aws/aws-cdk#24345]
### Describe the bug

Using the apprunner-alpha module, methods `.addEnvironmentVariable()` and `.addSecret()` only work if there are existing entries that have been created in the initial `imageConfiguration` props.  This is because in the private `renderEnvironmentVariables()` and `renderEnvironmentSecrets()` methods, there is an if condition which returns undefined if there are no entries in the initial `imageConfiguration` prop. See code here https://github.com/aws/aws-cdk/blob/d986e143df3cf9b42031eba0f5a2d9a71d6d9208/packages/%40aws-cdk/aws-apprunner/lib/service.ts#L1139-L1167

### Expected Behavior

Ability to use the methods without having defined initial env variables in the props.

### Current Behavior

No environment or secret variables are rendered if only using the `.addEnvironmentVariable()` and `.addSecret()` methods.

### Reproduction Steps

```
    const service = new Service(this, 'service', {
      source: Source.fromAsset({
        imageConfiguration: {
          port: 3000,
        },
        asset: imageAsset,
      }),
      instanceRole,
    })
    
    service.addEnvironmentVariable('TEST', 'test')
    service.addSecret('SECRET', Secret.fromSecretsManager(secret)
```

This will not render any secrets or environment variables in the resulting template, but adding some initial values will cause add environment variables to be correctly rendered, e.g.

```
    const service = new Service(this, 'service', {
      source: Source.fromAsset({
        imageConfiguration: {
          port: 3000,
          environmentSecrets: { SEED1: Secret.fromSecretsManager(seedSecret) },
          environmentVariables: { SEED2: 'seed' },
        },
        asset: imageAsset,
      }),
      instanceRole,
    })
    
    service.addEnvironmentVariable('TEST', 'test')
    service.addSecret('SECRET', Secret.fromSecretsManager(secret)
```

### Possible Solution

Correct the faulty if logic in `renderEnvironmentVariables()` and `renderEnvironmentSecrets()`

### CDK CLI Version

2.66.0

### Node.js Version

16.17.0

### OS

M1 MacOS

### Language

Typescript

**Comment by pahud** [comment]
Thanks for addressing this issue and the PR contribution.
