### ISSUE TITLE
`CodeBuild`: Can't run docker image on ARM build instance

### ISSUE THREAD

**Issue by BastiQ** [aws/aws-cdk#24342]
### Describe the bug

Hey there!

It seems like, so far, the `LinuxArmBuildImage` class doesn't support the `from_docker_registry` function [1]. But the `LinuxBuildImage` class does. This seems weird to me since CodeBuild is generally supporting the use of ARM images [2].

Not sure if this is a bug or a future request, feel free to change.

[1] https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_codebuild/README.html#images and https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_codebuild/LinuxArmBuildImage.html
[2] https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-compute-types.html###

### Reproduction Steps

```python
my_codebuild_project = codebuild.Project(
    self,
    "MyCodeBuildProject",
    project_name="MyCodeBuildProject",
    build_spec=codebuild.BuildSpec.from_object(
        {
            "version": "0.2",
            "phases": {
                "build": {
                    "commands": [
                        "echo hi",
                    ]
                }
            },
        }
    ),
    environment=codebuild.BuildEnvironment(
        build_image=codebuild.LinuxBuildImage.from_docker_registry( # can't use LinuxArmBuildImage
            f"public.ecr.aws/sam/build-python3.9:latest-arm64" # runs into error with the -arm64 ending
        ),
        compute_type=codebuild.ComputeType.LARGE,
        privileged=True,
    ),
)
```

### Possible Solution

`LinuxArmBuildImage` should also support `from_docker_registry` function

### CDK CLI Version

2.66.1

### Node.js Version

v16.16.0

### OS

MacOS

### Language

Python

### Language Version

3.9.15

**Comment by pahud** [comment]
Yes. This is related to https://github.com/aws/aws-cdk/issues/24367 and we definitely need to add this feature on it. Any PR submission is welcome and appreciated!
