### ISSUE TITLE
EbsDeviceProps missing support for setting throughput on GP3 volumes, yet VolumeProps has support for it

### ISSUE THREAD

**Issue by adrabkin** [aws/aws-cdk#24341]
### Describe the feature

When creating and EC2 instance, and configuring a blockDevices property, this uses the [BlockDeviceVolume](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ec2.BlockDeviceVolume.html) type, which accepts an ebsDevice parameter of type EbsDeviceProps. EbsDeviceProps does not have the option to set a throughput property.

However, if you look at [VolumeProps](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ec2.VolumeProps.html), when creating a volume separately, it does support the throughput property. 

### Use Case

I've seen examples where people are creating volumes outside of the blockDevices property of an Instance, then have to deal with attaching the volume. 

Having the option to create a gp3 volume along with all of its configuration properties (including throughput) directly via the instance as part of the blockDevices property simplifies the deployment of an instance. iops is already an accepted property as part of EbsDeviceProps, why not throughput?

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.66.1

### Environment details (OS name and version, etc.)

OSX 12.6.3

**Comment by pahud** [comment]
Yes we probably should add this property in [EbsDeviceOptionsBase](https://github.com/aws/aws-cdk/blob/32781f825352f9cb43d8fed5c122b454275b3076/packages/%40aws-cdk/aws-ec2/lib/volume.ts#L42) or other interfaces. I'm making this a p2 feature request and any PR submission will be more than welcome and appreciated.

**Comment by isker** [comment]
I tried to fix this in #30317 but could not get a review before automation closed it. Trying again in #30716.
