### ISSUE TITLE
(custom-resources): StateNotFoundError: State functionActiveV2 not found in ap-south-2

### ISSUE THREAD

**Issue by pahud** [aws/aws-cdk#24358]
### Describe the bug

When deploying 10+ custom resources in `ap-south-2`, it fails with `StateNotFoundError: State functionActiveV2 not found` error as below:

1. It's fine to deploy 10+ custom resources in other AWS regions such as `us-east-1` or `ap-northeast-1`. Only `ap-south-2` fails in this case.
2. When deploying with <10 custom resources, `ap-south-2` will be fine with no error.

### Expected Behavior

The provided code above should deploy in `ap-south-2`.

### Current Behavior

<img width="1172" alt="image" src="https://user-images.githubusercontent.com/278432/221716895-f414c22f-2da8-47a9-95e8-e77cddf7f42b.png">

### Reproduction Steps

```ts
import * as cdk from "aws-cdk-lib";
import { Construct } from "constructs";
import * as lambda from "aws-cdk-lib/aws-lambda";
import { CustomResource } from "aws-cdk-lib";
import * as cr from "aws-cdk-lib/custom-resources";

export class DummyLambdaStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const onEventHandler = new lambda.Function(this, 'OnEventHandler', {
      runtime: lambda.Runtime.NODEJS_18_X,
      code: lambda.Code.fromInline(`exports.onEvent = () => { return }`),
      handler: 'index.onEvent',
    })

    const provider = new cr.Provider(this, "Provider", {
      onEventHandler,
    });

    const numResources = 10
    for (let i = 0; i < numResources; i++) {
      new CustomResource(this, `CR${i}`, {
        serviceToken: provider.serviceToken,
      });
    }
  }
}
```

### Possible Solution

There might be some restrictions in `ap-south-2`.

### CDK CLI Version

2.66.1 (build 539d036)

### Node.js Version

v16.17.0

### OS

Linux

### Language

Typescript

**Comment by pahud** [comment]
Same error if I change the runtime to Python 3.9

```ts
const onEventHandler = new lambda.Function(this, 'OnEventHandler', {
  runtime: lambda.Runtime.PYTHON_3_9,
  code: lambda.Code.fromInline(`def on_event(event, context): return {}`),
  handler: 'index.on_event',
})
```

**Comment by zelu-zuehlke** [comment]
Same error in eu-central-2 region, except that we are using EKS (deployed with CDK), but we have more than 10 custom resources.
Any update on this?

**Comment by pahud** [comment]
I am reaching out to the relevant team internally.

**Comment by robert-carbmee** [comment]
It seems like this CDK commit is using the functionActiveV2 state from the JS SDK:
https://github.com/aws/aws-cdk/commit/def2971d91eedbd327d3acec201d902376129f25

Then the change in CDK v2.60.0 switched off installLatestAwsSdk by default for custom resources, and from the PR it seems the default SDK version packaged by Lambda is 2.1055.0:
https://github.com/aws/aws-cdk/pull/23591

But the functionActiveV2 state seems to have been introduced in the SDK in version v2.1080.0 from this commit in the JS SDK repo:
https://github.com/aws/aws-sdk-js/commit/488f6ad83b02efcc1b4867caeba3ccd44b65be58

So it seems the installLatestAwsSdk change is the culprit for the issue we are experiencing

**Comment by robert-carbmee** [comment]
I got around this for now by reverting to a CDK version older than 2.60.0

**Comment by KSSLR** [comment]
Is there a way forward? I cannot go back to an older CDK version and I have to use isolated subnets.

**Comment by washimimizuku** [comment]
Any updates on this?

**Comment by pahud** [comment]
Thank you @robert-carbmee for the details. I have brought it up to the CDK core team. Will keep the update posted here whenever possible.

**Comment by MrArnoldPalmer** [comment]
This seems like the right root cause as far as I can tell. I guess the reason this shows in ap-south-2 and not other regions is for some reason deploying certain number of custom resources causes some backup in lambda function creation that causes the functions to be pending, where in other regions we actually just never call `waitFor('functionActiveV2'` because the invoke doesn't fail...

I guess the easiest fix would be changing to use `functionActive` instead of `functionActiveV2`.

**Comment by anthonygerrard** [comment]
We're seeing this issue today in us-east-1. We're using cdk 2.63.1 with 3 custom resources built using the provided:al2 docker image

**Comment by SamuraiPrinciple** [comment]
Seems to be related to concurrency - as a workaround, if you introduce (artificial) dependencies (using addDependency for example) it will reconcile successfully.

**Comment by SamuraiPrinciple** [comment]
> We are also facing this issue in `eu-central-1`. We can reproduce the issue with just 2 Custom Resources at the same time with the identical CR Provider.

For science (not as a proper solution), does the issue go away if you add to your construct:

```typescript
cr1.node.addDependency(cr2)
```

**Comment by pahud** [comment]
related to https://github.com/aws/aws-cdk/pull/24916
