### ISSUE TITLE
codebuild: use custom arm linux image from external Docker registry

### ISSUE THREAD

**Issue by viktorhaid** [aws/aws-cdk#24367]
### Describe the feature

Today you can use a custom x86 image from an external registry as a CodeBuild build image using the method `codebuild.LinuxBuildImage.fromDockerRegistry`.

But class `LinuxArmBuildImage` lacks this method. 
It would be great if this class could also implement the method `fromDockerRegistry`, so we can use our own custom arm images, e.g.

```    
const project = new codebuild.Project(this, 'MyProject', {
  environment: {
    buildImage: LinuxArmBuildImage.fromDockerRegistry('ghcr.io/...:latest'),
    computeType: codebuild.ComputeType.SMALL
  }
});
```

### Use Case

I want to be able to use a custom arm linux image from external docker registry as a CodeBuild build image.

Both, the AWS Management Console and CloudFormation support it, but it is not possible when using CDK.

Currently we are stuck having to use Cloudformation for our arm compatible pipelines.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.66.0

### Environment details (OS name and version, etc.)

Ubuntu 20.04.5 LTS

**Comment by pahud** [comment]
Yeah I guess we can add this method to [LinuxArmBuildImage](https://github.com/aws/aws-cdk/blob/dee02a64197d6acfb0b15471d7bff9532dc037da/packages/%40aws-cdk/aws-codebuild/lib/linux-arm-build-image.ts#L30). Any PR submission on this is more than welcome.
