### ISSUE TITLE
aws-ecs: spot instance draning resources are not provisioned

### ISSUE THREAD

**Issue by ScOut3R** [aws/aws-cdk#24360]
### Describe the bug

I've specified `spotInstanceDraining: true` on the `AsgCapacityProvider` instance, yet the required resources (Lambda, SNS, LifecycleHook, etc) are not being provisioned.

### Expected Behavior

ECS spot instance draining resources being provisioned to provide the functionality.

### Current Behavior

The ASG Capacity Provider gets created and associated with the ECS Cluster, however the spot instance draining resources are missing.

### Reproduction Steps

Please see the code snippet below.

```
    const vpc = Vpc.fromLookup(this, "VPC", {
      vpcId: props.vpcId,
    });
    this.vpc = vpc;

    const cluster = new Cluster(this, "Cluster", {
      enableFargateCapacityProviders: true,
      vpc,
    });
    this.cluster = cluster;

    const instanceRole = new Role(this, "InstanceRole", {
      assumedBy: new ServicePrincipal("ec2.amazonaws.com"),
      managedPolicies: [
        ManagedPolicy.fromAwsManagedPolicyName("AmazonSSMManagedInstanceCore"),
        ManagedPolicy.fromAwsManagedPolicyName(
          "service-role/AmazonEC2ContainerServiceforEC2Role"
        ),
      ],
    });

    const launchTemplate = new LaunchTemplate(this, "LaunchTemplate", {
      blockDevices: [
        {
          deviceName: "/dev/xvda",
          volume: {
            ebsDevice: {
              volumeType: EbsDeviceVolumeType.GP3,
              volumeSize: props.ebsVolumeSize ?? 30,
            },
          },
        },
      ],
      machineImage: EcsOptimizedImage.amazonLinux2(),
      requireImdsv2: true,
      role: instanceRole,
      userData: UserData.forLinux(),
    });

    const asg = new AutoScalingGroup(this, "ASG", {
      capacityRebalance: true,
      maxCapacity: 10,
      minCapacity: 0,
      mixedInstancesPolicy: {
        launchTemplate,
        launchTemplateOverrides: props.launchTemplateOverrides ?? [
          {
            instanceType: InstanceType.of(
              InstanceClass.T3,
              InstanceSize.MEDIUM
            ),
          },
          {
            instanceType: InstanceType.of(
              InstanceClass.T3A,
              InstanceSize.MEDIUM
            ),
          },
        ],
        instancesDistribution: {
          onDemandPercentageAboveBaseCapacity: 0,
          spotAllocationStrategy:
            SpotAllocationStrategy.PRICE_CAPACITY_OPTIMIZED,
        },
      },
      newInstancesProtectedFromScaleIn: true,
      vpc,
      vpcSubnets: {
        subnetType: SubnetType.PUBLIC,
      },
    });

    const asgCapacityProvider = new AsgCapacityProvider(
      this,
      "AsgCapacityProvider",
      {
        autoScalingGroup: asg,
        canContainersAccessInstanceRole: false,
        enableManagedScaling: true,
        enableManagedTerminationProtection: true,
        spotInstanceDraining: true,
      }
    );

    cluster.addAsgCapacityProvider(asgCapacityProvider);
```

### Possible Solution

I'm trying to understand the behaviour by looking at CDK's code, but I can't seem to find what I'm missing.

### CDK CLI Version

2.66.1 (build 539d036)

### Framework Version

2.66.1

### Node.js Version

18.14.0

### OS

Linux

### Language

Typescript

### Language Version

4.9.5

**Comment by pahud** [comment]
[ECS Spot Instance Draining](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/container-instance-spot.html) essentially adds `ECS_ENABLE_SPOT_INSTANCE_DRAINING=true` in `/etc/ecs/ecs.config` and you can see how it was implemented in CDK here:

https://github.com/aws/aws-cdk/blob/cea1039e3664fdfa89c6f00cdaeb1a0185a12678/packages/%40aws-cdk/aws-ecs/lib/cluster.ts#L422-L424

I don't think this will create additional Lambda, SNS and LifecycleHook in this case. Is this something you are looking at?

**Comment by ncaq** [comment]
I am using the same setup method as the person who created the issue.
When I set up this way, AWS these days is set to automatically pay the price of the spot instance up to the on-demand instance.
In that case, I don't set spotPrice naturally, so this is not enabled and I get a warning in the AWS console.
As a workaround for now, adjust the user data manually.
However, it seems to be the intended behavior to be done automatically if spot instances are originally enabled, so it would be preferable for CDK to set this automatically even if you are using the automatic price adjustment feature.

**Comment by ncaq** [comment]
I found that it is too deep where it is set to be easily added.
I don't see any harm in having the ECS_ENABLE_SPOT_INSTANCE_DRAINING environment variable set.
Therefore, I think it is sufficient to just check spotInstanceDraining without making spotPrice a condition.
