### ISSUE TITLE
(service-catalog): (CfnPortfolioPrincipalAssociation should support IAM_PATTERN)

### ISSUE THREAD

**Issue by gbvanrenswoude** [aws/aws-cdk#24370]
### Describe the bug

Using

```
    new sc.CfnPortfolioPrincipalAssociation(
      this,
      'CfnPortfolioPrincipalAssociation',
      {
        portfolioId: portfolio.portfolioId,
        principalArn: `arn:aws:iam:::role/somerole`,
        principalType: 'IAM_PATTERN',
      },
    );
```
throws `Property validation failure: [Value for property {/PrincipalType} does not match pattern {IAM}]`

### Expected Behavior

IAM is not the only supported pattern. Per `https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/ServiceCatalog.html#associatePrincipalWithPortfolio-property` (used in the AWS Custom Resources Framework of the CDK) usage of `IAM_PATTERN` is supported. Writing a Custom Resource using it yields the expected results:
```
    new cr.AwsCustomResource(this, "sharePortfolioWithPrincipalName", {
      installLatestAwsSdk: true,
      onCreate: {
        service: "ServiceCatalog",
        action: "associatePrincipalWithPortfolio",
        physicalResourceId: cr.PhysicalResourceId.of(
          "sharePortfolioWithPrincipalName"
        ),
        parameters: {
          PortfolioId: portfolio.portfolioId,
          PrincipalARN: `arn:aws:iam:::role/somerole`,
          PrincipalType: "IAM_PATTERN",
        },
      },
      onDelete: {
        service: "ServiceCatalog",
        action: "disassociatePrincipalFromPortfolio",
        physicalResourceId: cr.PhysicalResourceId.of(
          "sharePortfolioWithPrincipalName"
        ),
        parameters: {
          PortfolioId: portfolio.portfolioId,
          PrincipalARN: `arn:aws:iam:::role/somerole`,
          PrincipalType: "IAM_PATTERN",
        },
      },
      policy: cr.AwsCustomResourcePolicy.fromSdkCalls({
        resources: [portfolio.portfolioArn],
      }),
    });
```

```
mystack: creating CloudFormation changeset...

 ✅  mystack

✨  Deployment time: 1073.13s
```

### Current Behavior

Throws Error: `Property validation failure: [Value for property {/PrincipalType} does not match pattern {IAM}]`

### Reproduction Steps

See code attachments above

### CDK CLI Version

2.66.1

### Node.js Version

17

### OS

MacOs

### Language

Typescript

### Language Version

TS 4

**Comment by pahud** [comment]
From what I can see in the [CFN doc](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-servicecatalog-portfolioprincipalassociation.html#cfn-servicecatalog-portfolioprincipalassociation-principaltype), `IAM_PATTERN` should be accepted. I will try reproduce it in my account.

**Comment by pahud** [comment]
I can reproduce this issue with the code below:

```ts
export class ServicecatalogTsStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const portfolio = new sc.Portfolio(this, 'PF', {
      displayName: 'my-portfolio',
      providerName: 'my-provider',
    });

    new sc.CfnPortfolioPrincipalAssociation(
      this,
      'CfnPortfolioPrincipalAssociation',
      {
        portfolioId: portfolio.portfolioId,
        principalArn: `arn:aws:iam:::role/somerole`,
        principalType: 'IAM_PATTERN',
      },
    );
  }
}
```

And the error:

<img width="929" alt="image" src="https://user-images.githubusercontent.com/278432/222570188-85a4a04b-2da2-49dc-bda3-2c7277393f78.png">

This seems to be a bug from CloudFormation. I'll escalate this internally.

**Comment by pahud** [comment]
Looking at the [doc](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-servicecatalog-portfolioprincipalassociation.html#aws-resource-servicecatalog-portfolioprincipalassociation-properties) again. Seems the only accepted value is `IAM`.

```
PrincipalType
The principal type. The supported value is IAM.

Allowed Values: IAM

Required: Yes

Type: String

Update requires: [Replacement](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-replacement)
```
