### ISSUE TITLE
Bootstrap template: missing new IAM permission cloudformation:ListStacks

### ISSUE THREAD

**Issue by OperationalFallacy** [aws/aws-cdk#24371]
### Describe the bug

We've received a warning from AWS about IAM roles changes

> On January 25, 2023, we updated our DescribeStacks API as part of our continuous improvements to ensure customers have granular control over the APIs they use.

> We require your action to update IAM Policies in your account by March 27, 2023 to avoid disruption to your DescribeStacks API calls.

> AWS CloudFormation now requires that customers have the cloudformation:ListStacks permission when calling DescribeStacks [1] without a target stack. This is in addition to the cloudformation:DescribeStacks permission that is already a requirement. You will need to add the cloudformation:ListStacks permission by March 27, 2023, on any calling principals using the DescribeStacks API without a target. CloudFormation has identified principals associated with your account that do not have ListStacks permissions making DescribeStacks calls without a target. These users or roles need their policies updated to include cloudformation:ListStacks along with the existing cloudformation:DescribeStacks permissions:

The role listed in the warning was `assumeed-role/cdk-hnb659fds-deploy-role-acct-region`

I've checked template for bootstrapping
https://github.com/aws/aws-cdk/blob/v1-main/packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml

It is missing `cloudformation:ListStacks` permission

### Expected Behavior

bootstrap-template.yaml needs cloudformation:ListStacks

### Current Behavior

bootstrap template missing permissions to list stacks granularly 

### Reproduction Steps

It is not breaking yet.

### CDK CLI Version

2.66.1

### Node.js Version

18x

### OS

osx

### Language

Typescript

### Other information

None

**Comment by pahud** [comment]
Thank you for the report. I will discuss with the team internally about this.

**Comment by rix0rrr** [comment]
I've checked our code base, and it does not look like we are using `describeStacks` without a stack name anywhere. I wonder if it is the CodePipeline Action doing this call. Are you using CDK Pipelines?

**Comment by rix0rrr** [comment]
Ah, have you perhaps been running CDK integ tests?

**Comment by rix0rrr** [comment]
So far, we've not been able to determine the cause of these untargeted calls, and while we use CDK ourselves every day, none of our accounts are affected by this new policy.

I would therefore like to ask you to dig into your CloudTrail logs to help us figure out when and how your `cdk-hnb659fds-deploy-role-$ACCT-$REGION` role was involved in making untargeted `DescribeStacks` calls.

Merging the proposed fix would weaken the security posture of all CDK users. Since it seems like CDK doesn't actually need these permissions by default, that's something we'd rather not do if it's not strictly necessary.

**Comment by rix0rrr** [comment]
What version of CDK are you on?

**Comment by OperationalFallacy** [comment]
Thank you for investigating.

I found these calls. I was doing some troubleshooting with iam role that assumed `arn:aws:iam::xxx:role/cdk-hnb659fds-deploy`.

Thanks again for keeping this project secure.
