### ISSUE TITLE
@cdklabs/cdk-ssm-documents: Error passing payload to InvokeLambdaFunctionStep step in an SSM Document

### ISSUE THREAD

**Issue by aramkoukia** [aws/aws-cdk#24388]
### Describe the bug

I am writing an SSM document with CDK and have a InvokeLambdaFunctionStep  step
For the payload the type is a bit odd. it expects IStringMapVariable
I do this and it makes TS happy:
```
    const invokeLambdaFunctionStep = new InvokeLambdaFunctionStep(this, "StepName",{
      functionName: StringVariable.of("LambdaName"),
      payload: new HardCodedStringMap({ cfnStackId: StringVariable.of("CloudFormationStackID") })
    });
```

But when I try to deploy I get this error:

```
Resource handler returned message: "Invalid request provided: Input {cfnStackId={{ CloudFormationStackID }}} is of type LinkedHashMap, but expected type is String. (Service: Ssm, Status Code: 400, Request ID: XXXXXXXXXXXXXXXXXX)" (HandlerErrorCode: InvalidRequest)
```

Any ideas about this?

### Expected Behavior

I expect for this to work when I pass the payload like above, 

### Current Behavior

seems like the API expects the Payload to be string but CDK is passing it as a dictionary

### Reproduction Steps

Dependencies

  "devDependencies": {
    "@types/node": "18.11.18",
    "aws-cdk": "2.64.0",
    "ts-node": "^10.9.1",
    "typescript": "~4.9.5"
  },
  "dependencies": {
    "@cdklabs/cdk-ssm-documents": "0.0.33",
    "aws-cdk-lib": "2.64.0",
    "cdk-ssm-document": "^3.1.1",
    "constructs": "^10.0.0"
  }

### CDK CLI Version

2.64.0

### Framework Version

"aws-cdk": "2.64.0", "@cdklabs/cdk-ssm-documents": "0.0.33", "cdk-ssm-document": "^3.1.1",

### Node.js Version

v14.16.0

### OS

Windows

### Language

Typescript

**Comment by pahud** [comment]
Is this issue related to https://github.com/cdklabs/cdk-ssm-documents ? If yes, I think the best place is to post this issue in https://github.com/cdklabs/cdk-ssm-documents/issues

**Comment by aramkoukia** [comment]
ok did that. https://github.com/cdklabs/cdk-ssm-documents/issues/57
closing this one
