### ISSUE TITLE
(aws_sam): permissions_boundaries --> permissions_boundary

### ISSUE THREAD

**Issue by SamPlatek** [aws/aws-cdk#24384]
### Describe the bug

Hello,

It seems that the key-name `permissions_boundaries` is used and generates a `PermissionsBoundaries` field in the resulting template which is an invalid key when trying to deploy.

### Expected Behavior

The key should be `permissions_boundary` as passed in to the Python class and should generate the key `PermissionsBoundary` instead of `PermissionsBoundaries`

### Current Behavior

`PermissionsBoundaries` key is generated

### Reproduction Steps

Attempt to give `permissions_boundaries` any sort of value. `permissions_boundary` is not accepted as a valid key and will error out if attempted.

### Possible Solution

Rekey

### CDK CLI Version

2.66.0

### Node.js Version

v18.12.1

### OS

Mac

### Language

Python

**Comment by pahud** [comment]
Can you share your full code sample so we can deploy in our account?
