### ISSUE TITLE
synthetics: alarm for the metric not linked in the console

### ISSUE THREAD

**Issue by npvisual** [aws/aws-cdk#24387]
### Describe the bug

I have created a canary synthetic : simple heartbeat monitoring. I have then linked this canary to a new alarm that is sending notifications to a SNS topic.

Everything works as expected : canary is all setup and alarm will send a notification to the topic when the endpoint is failing.

However I am not seeing the alarm in the console under the canary configuration

![Screenshot 2023-02-28 at 5 41 12 PM](https://user-images.githubusercontent.com/3268395/222008364-7ded0f37-0528-4c02-89de-8fa28a8364af.png)

However if I create this via the console, I see the alarm in that configuration screen (note it's different base : using nodejs) : 

![Screenshot 2023-02-28 at 5 43 30 PM](https://user-images.githubusercontent.com/3268395/222009001-80b669cb-2bcb-4f89-99f4-912a9d3bab91.png)

This is pretty convenient because it links the canary to its alarm. Is there something I am missing that would allow the alarm to be displayed in the configuration screen of the canary ?

### Expected Behavior

I would expect to see the canary in the console (so maybe I am missing a step ?).

![Screenshot 2023-02-28 at 5 43 30 PM](https://user-images.githubusercontent.com/3268395/222009001-80b669cb-2bcb-4f89-99f4-912a9d3bab91.png)

### Current Behavior

See illustration below and description above : 

![Screenshot 2023-02-28 at 5 41 12 PM](https://user-images.githubusercontent.com/3268395/222008364-7ded0f37-0528-4c02-89de-8fa28a8364af.png)

### Reproduction Steps

Here's the code snippet I am using (python) : 

```python
                canary = synthetics.Canary(
                    self,
                    f"{tenant_name}-hb",
                    canary_name=f"{tenant_name}-hb",
                    schedule=synthetics.Schedule.rate(
                        Duration.minutes(tenant_canaryhb_schedule)
                    ),
                    runtime=synthetics.Runtime.SYNTHETICS_PYTHON_SELENIUM_1_3,
                    environment_variables={"url": tenant_url},
                    enable_auto_delete_lambdas=True,
                    test=synthetics.Test.custom(
                        code=synthetics.Code.from_asset(
                            path.join(path.dirname(__file__), "./canary")
                        ),
                        handler="index.handler",
                    ),
                )
                topic = Fn.import_value("PodTopicDevopsArn")
                if topic:
                    sns_topic = sns.Topic.from_topic_arn(
                        self,
                        f"{tenant_name}-snstopic",
                        topic_arn=topic,
                    )
                    alarm = cloudwatch.Alarm(
                        self,
                        f"{tenant_name}-hb-alarm",
                        metric=canary.metric_success_percent(),
                        threshold=tenant_canaryhb_treshold,
                        comparison_operator=cloudwatch.ComparisonOperator.LESS_THAN_THRESHOLD,
                        evaluation_periods=tenant_canaryhb_period,
                        alarm_name=f"{tenant_name}-hb-alarm",
                        alarm_description=f"Hearbeat monitoring for {tenant_name}",
                    )
                    alarm.add_alarm_action(actions.SnsAction(sns_topic))

```

### CDK CLI Version

2.66.1 (build 539d036)

### Framework Version

"aws-cdk-lib" = "2.66..1"

### Node.js Version

whatever is installed as part of synthetics.Runtime.SYNTHETICS_PYTHON_SELENIUM_1_3

### OS

whatever is used for synthetics.Runtime.SYNTHETICS_PYTHON_SELENIUM_1_3

### Language

Python

### Language Version

3.9 I guess (installed base for synthetics.Runtime.SYNTHETICS_PYTHON_SELENIUM_1_3)

**Comment by pahud** [comment]
Hi

I noticed the alarm created from the console will be in the `CloudWatchSynthetics` namespace. Maybe you can specify this namespace for your alarm created with CDK?

<img width="895" alt="image" src="https://user-images.githubusercontent.com/278432/222294871-d365648c-8d8c-46ca-af33-985b6839bdf1.png">

**Comment by npvisual** [comment]
@pahud : thanks for the suggestion. 

I looked at the alarm that was created as part of the CDK stack and it seems to already have the proper Namespace : 

![Screenshot 2023-03-09 at 1 20 44 PM](https://user-images.githubusercontent.com/3268395/224165006-23606545-6d99-4de0-b731-f2dc921a088b.png)

But it's still not showing up linked under the Canary configuration page.

**Comment by sujee81** [comment]
Hi @npvisual 
I had the same issue and upon further investigation found out from [here](https://github.com/hashicorp/terraform-provider-aws/issues/19993#issuecomment-1069078802) that the alarm name should be named "Synthetics-Alarm-canary_name" to make it appears in the Canary console. Hope it helps.

**Comment by good92** [comment]
@sujee81 Thanks, it solved my issue in Terraform configuration.

```
resource "aws_cloudwatch_metric_alarm" "canary_alarm" {
  # alarm_name                          = "${local.name_prefix}-synthetics-canary-endpoint" # Synthetics-Alarm-canary_name
  alarm_name                            = "Synthetics-Alarm-${aws_synthetics_canary.canary_api_calls.name}" # https://github.com/aws/aws-cdk/issues/24387
```
