### ISSUE TITLE
elastic beanstalk environment: creates launch template without resource tags

### ISSUE THREAD

**Issue by AntonAIT** [aws/aws-cdk#24399]
### Describe the bug

When EB environment are in creating process it creates for itself a launch template and not pass a resource tags to it.

### Expected Behavior

Pass tags to resource tags in launch template.

### Current Behavior

It doesn't pass tags to resource tags in launch template.

### Reproduction Steps

Create an environment with an option setting to disable IMDSv1.
`eb.CfnEnvironment.OptionSettingProperty(
                namespace="aws:autoscaling:launchconfiguration",
                option_name="DisableIMDSv1",
                value="true",
            )`

### CDK CLI Version

1.194.0

### Node.js Version

v19.7.0

### OS

MacOs

### Language

Python

**Comment by pahud** [comment]
Can you elaborate more on what resource tags are you expecting and provide a full working CDK code that we can run in out account to see more details?

**Comment by AntonAIT** [comment]
Hi, @pahud! Thanks for your response.
Here is a code to reproduct an error.

`from aws_cdk import (
    aws_ec2 as ec2,
    aws_elasticbeanstalk as eb,
    aws_iam as iam,
    aws_logs as logs,
    core,
)
from constructs import Construct

class EbBugStack(core.Stack):

    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)
        node = self.node
        self.vpc = ec2.Vpc(
            self,
            "VPC",
            max_azs=2,
            cidr="10.120.0.0/16",
            vpc_name="test-eb-bug-vpc",
            subnet_configuration=[
                ec2.SubnetConfiguration(
                    subnet_type=ec2.SubnetType.PUBLIC,
                    name="public-subnet",
                    cidr_mask=24,
                ),
                ec2.SubnetConfiguration(
                    subnet_type=ec2.SubnetType.PRIVATE_WITH_NAT,
                    name="private-subnet",
                    cidr_mask=24,
                ),
            ],
        )
        self.eb_instance_role = iam.Role(
            self,
            f"eb-bug-elasticbeanstalk-ec2-role",
            assumed_by=iam.ServicePrincipal("ec2.amazonaws.com"),
            managed_policies=[
                iam.ManagedPolicy.from_aws_managed_policy_name(
                    "AWSElasticBeanstalkWebTier"
                )
            ],
            role_name="eb-bug-elasticbeanstalk-ec2-role",
        )
        eb_log_group = logs.LogGroup(
            self,
            f"eb-log-group",
            log_group_name="eb-log-group",
            retention=logs.RetentionDays.ONE_YEAR,
            removal_policy=core.RemovalPolicy.DESTROY,
        )
        self.eb_instance_role.add_to_policy(
            iam.PolicyStatement(
                actions=[
                    "logs:CreateLogGroup",
                    "logs:CreateLogStream",
                    "logs:GetLogEvents",
                    "logs:PutLogEvents",
                    "logs:DescribeLogGroups",
                    "logs:DescribeLogStreams",
                    "logs:PutRetentionPolicy",
                ],
                resources=[eb_log_group.log_group_arn],
            )
        )
        self.eb_instance_role.add_to_policy(
            iam.PolicyStatement(
                actions=["sts:AssumeRole"],
                resources=[
                    f"arn:aws:iam::{core.Stack.of(self).account}:role/aws-service-role/elasticbeanstalk.amazonaws.com/AWSServiceRoleForElasticBeanstalk"
                ],
            )
        )
        self.eb_instance_role.add_to_policy(
            iam.PolicyStatement(
                effect=iam.Effect.ALLOW,
                actions=[
                    "ssm:DescribeParameters",
                ],
                resources=["*"],
            )
        )
        profile_name = "env-profile-name"
        iam.CfnInstanceProfile(
            self,
            profile_name,
            roles=[self.eb_instance_role.role_name],
            instance_profile_name=profile_name,
        )
        option_settings_props = [
            eb.CfnEnvironment.OptionSettingProperty(
                namespace="aws:autoscaling:launchconfiguration",
                option_name="DisableIMDSv1",
                value="true",
            ),
            eb.CfnEnvironment.OptionSettingProperty(
                namespace="aws:autoscaling:launchconfiguration",
                option_name="InstanceType",
                value="t3.small",
            ),
            eb.CfnEnvironment.OptionSettingProperty(
                namespace="aws:ec2:vpc",
                option_name="VPCId",
                value=self.vpc.vpc_id,
            ),
            eb.CfnEnvironment.OptionSettingProperty(
                namespace="aws:ec2:vpc",
                option_name="Subnets",
                value=",".join(self.vpc.select_subnets(subnet_type=ec2.SubnetType.PRIVATE).subnet_ids)
            ),
            eb.CfnEnvironment.OptionSettingProperty(
                namespace="aws:ec2:vpc",
                option_name="ElbSubnets",
                value=",".join(
                    self.vpc.select_subnets(subnet_type=ec2.SubnetType.PUBLIC).subnet_ids
                ),
            ),
            eb.CfnEnvironment.OptionSettingProperty(
                namespace="aws:autoscaling:launchconfiguration",
                option_name="IamInstanceProfile",
                value=profile_name,
            ),
        ]

        self.eb_app = eb.CfnApplication(
            self,
            "Application",
            application_name=f"EB-Bug-App"
        )
        self.eb_env = eb.CfnEnvironment(
            self,
            "Environment",
            environment_name="EB-Bug-Env",
            application_name="EB-Bug-App",
            platform_arn=node.try_get_context("platform"),
            solution_stack_name="64bit Amazon Linux 2 v2.5.0 running .NET Core",
            option_settings=option_settings_props,
            tags=[
                core.CfnTag(
                    key="foo1",
                    value="bar1",
                ),
                core.CfnTag(
                    key="foo2",
                    value="bar2"
                ),
            ],
        )


`

**Comment by pahud** [comment]
Thanks for you sample code. I see you specify `tags` in `CfnEnvironment`. Do you expect the tags propagated to the LaunchTemplate generated by EB?

**Comment by pahud** [comment]
OK I can confirm the Environment tags will not propagate to LaunchTemplate tags. As this should be a gap for CFN or EB, rather than CDK and we probably can't do anything with CDK for that given the LT is not managed by CDK, I am closing this issue for now and report to the relevant team internally.

This is the code I used for reproduction(just a little bit modification from the code above):

```py
from aws_cdk import (
    Stack,
    aws_ec2 as ec2,
    aws_iam as iam,
    aws_logs as logs,
    aws_elasticbeanstalk as eb,
)
import aws_cdk as core
from constructs import Construct

class ElasticbeanstalkPyStack(Stack):

    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        node = self.node
        self.vpc = ec2.Vpc.from_lookup(self, 'Vpc', is_default=True)
        # self.vpc = ec2.Vpc(
        #     self,
        #     "VPC",
        #     max_azs=2,
        #     cidr="10.120.0.0/16",
        #     vpc_name="test-eb-bug-vpc",
        #     subnet_configuration=[
        #         ec2.SubnetConfiguration(
        #             subnet_type=ec2.SubnetType.PUBLIC,
        #             name="public-subnet",
        #             cidr_mask=24,
        #         ),
        #         ec2.SubnetConfiguration(
        #             subnet_type=ec2.SubnetType.PRIVATE_WITH_NAT,
        #             name="private-subnet",
        #             cidr_mask=24,
        #         ),
        #     ],
        # )
        self.eb_instance_role = iam.Role(
            self,
            f"eb-bug-elasticbeanstalk-ec2-role",
            assumed_by=iam.ServicePrincipal("ec2.amazonaws.com"),
            managed_policies=[
                iam.ManagedPolicy.from_aws_managed_policy_name(
                    "AWSElasticBeanstalkWebTier"
                )
            ],
            role_name="eb-bug-elasticbeanstalk-ec2-role",
        )
        eb_log_group = logs.LogGroup(
            self,
            f"eb-log-group",
            log_group_name="eb-log-group",
            retention=logs.RetentionDays.ONE_YEAR,
            removal_policy=core.RemovalPolicy.DESTROY,
        )
        self.eb_instance_role.add_to_policy(
            iam.PolicyStatement(
                actions=[
                    "logs:CreateLogGroup",
                    "logs:CreateLogStream",
                    "logs:GetLogEvents",
                    "logs:PutLogEvents",
                    "logs:DescribeLogGroups",
                    "logs:DescribeLogStreams",
                    "logs:PutRetentionPolicy",
                ],
                resources=[eb_log_group.log_group_arn],
            )
        )
        self.eb_instance_role.add_to_policy(
            iam.PolicyStatement(
                actions=["sts:AssumeRole"],
                resources=[
                    f"arn:aws:iam::{core.Stack.of(self).account}:role/aws-service-role/elasticbeanstalk.amazonaws.com/AWSServiceRoleForElasticBeanstalk"
                ],
            )
        )
        self.eb_instance_role.add_to_policy(
            iam.PolicyStatement(
                effect=iam.Effect.ALLOW,
                actions=[
                    "ssm:DescribeParameters",
                ],
                resources=["*"],
            )
        )
        profile_name = "env-profile-name"
        iam.CfnInstanceProfile(
            self,
            profile_name,
            roles=[self.eb_instance_role.role_name],
            instance_profile_name=profile_name,
        )
        option_settings_props = [
            eb.CfnEnvironment.OptionSettingProperty(
                namespace="aws:autoscaling:launchconfiguration",
                option_name="DisableIMDSv1",
                value="true",
            ),
            eb.CfnEnvironment.OptionSettingProperty(
                namespace="aws:autoscaling:launchconfiguration",
                option_name="InstanceType",
                value="t3.small",
            ),
            eb.CfnEnvironment.OptionSettingProperty(
                namespace="aws:ec2:vpc",
                option_name="VPCId",
                value=self.vpc.vpc_id,
            ),
            eb.CfnEnvironment.OptionSettingProperty(
                namespace="aws:ec2:vpc",
                option_name="Subnets",
                value=",".join(self.vpc.select_subnets(subnet_type=ec2.SubnetType.PRIVATE_WITH_NAT).subnet_ids)
            ),
            eb.CfnEnvironment.OptionSettingProperty(
                namespace="aws:ec2:vpc",
                option_name="ElbSubnets",
                value=",".join(
                    self.vpc.select_subnets(subnet_type=ec2.SubnetType.PUBLIC).subnet_ids
                ),
            ),
            eb.CfnEnvironment.OptionSettingProperty(
                namespace="aws:autoscaling:launchconfiguration",
                option_name="IamInstanceProfile",
                value=profile_name,
            ),
        ]

        self.eb_app = eb.CfnApplication(
            self,
            "Application",
            application_name=f"EB-Bug-App"
        )
        self.eb_env = eb.CfnEnvironment(
            self,
            "Environment",
            environment_name="EB-Bug-Env",
            application_name="EB-Bug-App",
            platform_arn=node.try_get_context("platform"),
            solution_stack_name="64bit Amazon Linux 2 v2.5.0 running .NET Core",
            option_settings=option_settings_props,
            tags=[
                core.CfnTag(
                    key="foo1",
                    value="bar1",
                ),
                core.CfnTag(
                    key="foo2",
                    value="bar2"
                ),
            ],
        )

```

**Comment by AntonAIT** [comment]
@pahud Thanks for your cooperation!
