### ISSUE TITLE
CLI: support sending an email when deployment is done (suggestion)

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#244]
Just an idea - need to think of use cases

**Comment by rhboyd** [comment]
What about publishing deployment events to Amazon Event Bridge (publish to default event-bus for that account/region?)

bar-raising: Create a construct that listens to the default bus and has a few notification options.

**Comment by rix0rrr** [comment]
From the issue description this sounds like a solution waiting for a problem. Closing.
