### ISSUE TITLE
CodeBuild:  You are not authorized to perform this operation in CDK Pipeline

### ISSUE THREAD

**Issue by jinspark-lab** [aws/aws-cdk#24407]
### Describe the bug

Building cdk synth inside of CDK Pipeline, CodeBuild shows

"You are not authorized to perform this operation" Error.

What I try to do is to refer other Nested Stack's variable which works without CDK Pipeline. I don't see any statements it would be impossible. From what I know, referring other Nested Stack's variable is possible. Is that right?

```
    const pipeline = new CodePipeline(this, 'CdkPipeline', {
      pipelineName: 'appCdkPipeline',
      selfMutation: true,
      synth: new cdk.pipelines.CodeBuildStep('Synth', {
        input: CodePipelineSource.codeCommit(repo, 'main'),
        commands: [
          'yarn install',
          'yarn vite build',
          'yarn cdk synth'
        ],
        rolePolicyStatements: [
          new iam.PolicyStatement({
            actions: ['sts:AssumeRole'],
            resources: ['*']
          })
        ],
        role: new iam.Role(this, 'SynthRole', {
          assumedBy: new iam.ServicePrincipal('codebuild.amazonaws.com'),
          managedPolicies: [
            // Permissions
          ]
        }),
        actionRole: new iam.Role(this, 'ActionRole', {
          assumedBy: new iam.ServicePrincipal('codebuild.amazonaws.com'),
          managedPolicies: [
            // Permissions
          ]
        })
      }),
      role: new iam.Role(this, 'CdkPipelineRole', {
        assumedBy: new iam.ServicePrincipal('codepipeline.amazonaws.com'),
        managedPolicies: [
            // Permissions
        ]
      })
    });
    pipeline.addStage(new MainStage(this, "MainStage"));
  }
}
```

### Expected Behavior

CDK Synth should be succeeded as local environment.

### Current Behavior

CDK Synth failed.

### Reproduction Steps

Whenever build CDK Pipeline, it shows an error.

### Possible Solution

N/A

### CDK CLI Version

2.63.0

### Node.js Version

v19.5.0

### OS

CodeBuild

### Language

Typescript

### Other information

Local works, CodeBuild fails

**Comment by pahud** [comment]
Where did you see the error message? Was it the code you provided that returned the error?

**Comment by jinspark-lab** [comment]
Actually, that is what I confused. I could not see any message without it. For sure deployment failed in Build Step.
Now I am trying workaround, but I wonder why it happens. I think it would be possible to refer another stack's variable inside of CDK Pipeline. Without referring it deployment succeeded. If it is not expected result, I am going to try workaround first and revisit this issue with simpler sample.

**Comment by jinspark-lab** [comment]
I cannot see same error on the clean sample. I am going to open new issue, if I meet the situation.
