### ISSUE TITLE
cdk-ec2-key-pair: adding "functionName" property to KeyPairProps

### ISSUE THREAD

**Issue by mostafaDashtiGrohe** [aws/aws-cdk#24413]
### Describe the feature

I propose to add the **functionName** property to **KeyPairProps** to support overwriting the lambda function's name that **KeyPair()** generates.

### Use Case

Using the **KeyPair()** will generate a lambda function with a long name (in my case, because the stack name is too long) and it exceeds 64 characters which is the maximum length for a lambda function name because it adds **CFN-Resource-Custom-EC2-Key-Pair** to the end of stack name and uses it as the lambda function name.

There is this possibility to rewrite the function name by setting the **functionName** property but there is no such property in **KeyPairProps** which is the input type of **KeyPair()**.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2

### Environment details (OS name and version, etc.)

Windows 10

**Comment by pahud** [comment]
Which module are you using for the `KeyPair` class? I can't find `KeyPairProps` in the aws-cdk source code.
