### ISSUE TITLE
aws-cognito: Missing UserPoolIdentityProviderSaml class in typescript

### ISSUE THREAD

**Issue by an-sciseed** [aws/aws-cdk#24416]
### Describe the bug

As document mention, there are `UserPoolIdentityProviderSaml` and `UserPoolIdentityProviderSamlMetadata` could use in typescript, but I have tried to same example but these classes not found.

The document I have reference is bellow.
https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_cognito.UserPoolIdentityProviderSaml.html

I am using `aws-cdk` version `2.66.1`
Library using: `aws-cdk-lib/aws-cognito`
Language: typescript

### Expected Behavior

Add `UserPoolIdentityProviderSaml` and `UserPoolIdentityProviderSamlMetadata` to `aws-cdk-lib`

### Current Behavior

Trying to use cdk in other language (python)

### Reproduction Steps

Have tried to find `UserPoolIdentityProviderSaml` and `UserPoolIdentityProviderSamlMetadata` in library but not found

### CDK CLI Version

2.66.1

### Node.js Version

18.14.2

### OS

macOS Vertuna 13.2.1

### Language

Typescript

### Language Version

3.9.7

**Comment by pahud** [comment]
Yes it's actually in the library.

<img width="867" alt="image" src="https://user-images.githubusercontent.com/278432/222487509-643d742c-e6ff-4f09-858c-ecf0f92015d3.png">

**Comment by an-sciseed** [comment]
@pahud Thank you for responding.
Yes, I have tried to create new cdk project and found it.
Maybe `dependencies` in `package.json` of my project is too old.

Thank for your support!
