### ISSUE TITLE
Add code commit to lambda trigger to CDK 

### ISSUE THREAD

**Issue by aurelien-leloup** [aws/aws-cdk#24414]
### Describe the feature

On the AWS console, it is possible to create a trigger from a CodeCommit repository to a Lambda Function. I would like to be able to do it, with the same level of configuration through the CDK. 

### Use Case

Unless I am mistaken, this is not possible to do from the CDK. I have seen something using EventBridge. But it is not the same. 

### Proposed Solution

I am thinking that the easiest way to do this would be to add CodeCommit as a possible [EventSource ](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda.IEventSource.html)for lambda fuctions. 

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.66.1

### Environment details (OS name and version, etc.)

not relevant

**Comment by pahud** [comment]
Hi,

You actually can use `repo.onXxxx()` to listen on specific events and push to arbitrary event targets as described in the [README](https://github.com/aws/aws-cdk/tree/main/packages/%40aws-cdk/aws-codecommit#events). Can you elaborate why it doesn't work for you?

**Comment by aurelien-leloup** [comment]
Hello, 
Yes, I have noticed those methods and tried to use them, but it does not work for me. 
They use EventBridge to trigger the lambda. The triggering part works fine, but then my lambda expects a CodeCommitEvent and cannot interpret this. 

So, I am left with two bad options : 

- Add the CodeCommit trigger manually because it seems it is not possible to do with the CDK. 
- Edit my lambda code to accept an EventBridge notification

**Comment by pahud** [comment]
Yes when you specify `repo.onXxxx()`, your lambda function will receive events from the event bridge and you will need to parse the CodeCommitEvent in your lambda function.

Is there something missing from the CodeCommitEvent and your lambda func just can't work with it?

**Comment by aurelien-leloup** [comment]
EventBridge works fine for that use case, there is no problem with it. It is a fine workaround for most people looking for triggering lambda from the CDK. 

However, it is still a workaround. In the AWS Console you can trigger a lambda directly from CodeCommit (see image). This alone justifies the feature request. 

I understand my use case is very specific. As I am not authorized to use EventBridge in my organization, I have to configure the lambda manually. 

![image](https://user-images.githubusercontent.com/59309352/236403388-d46ce9cf-0dfa-4338-8a74-391eaa7bdd3c.png)

**Comment by adamjkeller** [comment]
We should close this issue as CodeCommit is no longer taking new customers and eventually will be deprecated. See here: https://aws.amazon.com/blogs/devops/how-to-migrate-your-aws-codecommit-repository-to-another-git-provider/

@pahud
