### ISSUE TITLE
aws-ec2: SubnetFilter byIds does not work as expected when using vpc.selectSubnets()

### ISSUE THREAD

**Issue by marcandjulien** [aws/aws-cdk#24427]
### Describe the bug

When creating a subnet selection with only the SubnetFilter.byIds, the selection if empty if the subnets are not of type PRIVATE_WITH_EGRESS.

### Expected Behavior

Being able to select subnet by ids in a subnet selection when using SubnetFilter.byIds.

### Current Behavior

When creating a subnet selection with only the SubnetFilter.byIds, the selection if empty if the subnets are not of type PRIVATE_WITH_EGRESS.

### Reproduction Steps

Try a subnet selection with a SubnetFilter.byIds on a vpc without subnet of type PRIVATE_WITH_EGRESS.

### Possible Solution

Current code
```typescript
  /**
   * From https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/aws-ec2/lib/vpc.ts
   */

  /**
   * Returns IDs of selected subnets
   */
  public selectSubnets(selection: SubnetSelection = {}): SelectedSubnets {
    const subnets = this.selectSubnetObjects(selection);
    const pubs = new Set(this.publicSubnets);

    return {
      subnetIds: subnets.map(s => s.subnetId),
      get availabilityZones(): string[] { return subnets.map(s => s.availabilityZone); },
      internetConnectivityEstablished: tap(new CompositeDependable(), d => subnets.forEach(s => d.add(s.internetConnectivityEstablished))),
      subnets,
      hasPublic: subnets.some(s => pubs.has(s)),
      isPendingLookup: this.incompleteSubnetDefinition,
    };
  }

  protected selectSubnetObjects(selection: SubnetSelection = {}): ISubnet[] {
    selection = this.reifySelectionDefaults(selection);

    if (selection.subnets !== undefined) {
      return selection.subnets;
    }

    let subnets;

    if (selection.subnetGroupName !== undefined) { // Select by name
      subnets = this.selectSubnetObjectsByName(selection.subnetGroupName);

    } else { // Or specify by type
      const type = selection.subnetType || SubnetType.PRIVATE_WITH_EGRESS;
      subnets = this.selectSubnetObjectsByType(type);
    }

    // Apply all the filters
    subnets = this.applySubnetFilters(subnets, selection.subnetFilters ?? []);

    return subnets;
  }
```

I propose creating a new function selectAllSubnetObjects applying a patch on the selectSubnetObjects function:
```typescript
  private selectAllSubnetObjects() {
    const allSubnets = [...this.publicSubnets, ...this.privateSubnets, ...this.isolatedSubnets];
    return allSubnets;
  }

  protected selectSubnetObjects(selection: SubnetSelection = {}): ISubnet[] {
    selection = this.reifySelectionDefaults(selection);

    if (selection.subnets !== undefined) {
      return selection.subnets;
    }

    let subnets;

    if (selection.subnetGroupName !== undefined) { // Select by name
      subnets = this.selectSubnetObjectsByName(selection.subnetGroupName);
    } else if (selection.subnetType) { // Or specify by type
      const type = selection.subnetType;
      subnets = this.selectSubnetObjectsByType(type);
    } else {
      subnets = this.selectAllSubnetObjects();
    }

    // Apply all the filters
    subnets = this.applySubnetFilters(subnets, selection.subnetFilters ?? []);

    return subnets;
  }

```

### CDK CLI Version

2.60.0 (build 2d40d77)

### Node.js Version

v16.17.0

### OS

Windows 11

### Language

Typescript

**Comment by pahud** [comment]
Yes I can reproduce this bug.

```ts
    const vpc = ec2.Vpc.fromLookup(this, 'Vpc', { isDefault: true });
    const subnets = vpc.selectSubnets({
      // select a public subnet by IDs
      // subnetFilters: [ ec2.SubnetFilter.byIds(['subnet-050929f8c6efb7657'])]
      // select a private subnet by IDs
      subnetFilters: [ ec2.SubnetFilter.byIds(['subnet-0d0069776469b2e0d'])]
    })
    
    new cdk.CfnOutput(this, 'SubnetIds', { value: subnets.subnetIds.join(',') })
```

And I think we probably should fix here:

https://github.com/aws/aws-cdk/blob/0b822b36bc2bb8d786d9c2fb7c8f493d80564384/packages/%40aws-cdk/aws-ec2/lib/vpc.ts#L576

**Comment by ahmetsoykan** [comment]
Hello,

i think subnet type selection is also happening in another function; and when tried with filtering byID it resulted with empty array with other vpc setups too.
https://github.com/aws/aws-cdk/blob/b935f2bbaf44b7a0186eafa465a8939d36d60915/packages/%40aws-cdk/aws-ec2/lib/vpc.ts#L653


by reproducing the case, i can not create outputs because subnets.subnetIds is empty array. 

    const vpc = new Vpc(this, "VPC", {
      subnetConfiguration: [
        { subnetType: SubnetType.PUBLIC, name: "BlaBla" },
        { subnetType: SubnetType.PRIVATE_ISOLATED, name: "DontTalkAtAll" },
      ],
    });
    const subnets = vpc.selectSubnets({});

    console.log(subnets.subnetIds);

    subnets.subnetIds.forEach((item, index) => {
      new cdk.CfnOutput(this, `SubnetID${index}`, {
        value: item,
      });
    });

from my understanding, is it doing filtering right, but when the subnetIDs are tokenised, it resulted with empty because there was no matches. example subnetIds: [ '${Token[TOKEN.622]}', '${Token[TOKEN.638]}' ]. 
https://github.com/aws/aws-cdk/blob/0b822b36bc2bb8d786d9c2fb7c8f493d80564384/packages/%40aws-cdk/aws-ec2/lib/subnet.ts#L147


Then tried this code block, it can be resolved as string.

     const vpc = new Vpc(this, "VPC", {
      subnetConfiguration: [
        { subnetType: SubnetType.PUBLIC, name: "BlaBla" },
        { subnetType: SubnetType.PRIVATE_ISOLATED, name: "DontTalkAtAll" },
      ],
    });
    const subnets = vpc.selectSubnets({});

    console.log(cdk.Token.asString(subnets.subnets[0].subnetId));

    new cdk.CfnOutput(this, `SubnetID1`, {
      value:  cdk.Token.asString(subnets.subnets[0].subnetId),
    });


As this is my first conversation, can you please review my findings, @pahud . thank you.
