### ISSUE TITLE
(ecs): (replace instnaceOf with strict type check method)

### ISSUE THREAD

**Issue by bun913** [aws/aws-cdk#24454]
### Describe the feature

I create `Role.isRole()` method at #24340 (https://github.com/aws/aws-cdk/pull/24340#discussion_r1120780639)

That's is for strict type check for `iam.Role` class.

I'll create `ecs.Cluster` type check like above.

Fix the code that uses instanceOf as follows

https://github.com/aws/aws-cdk/blob/29bdd6c3a0d387b394fe9d8f8b97e14d5db802f6/packages/%40aws-cdk/aws-ecs/lib/cluster.ts#L1262

### Use Case

Since instanceOf is not a product to be used for strict type determination, it is better to replace it.

fyi: https://github.com/aws/aws-cdk/pull/20564/files#diff-fe41afc44afd9acb16980754990f93acb596ed37662296575ea2fbe1c5531b50R203-R206

### Proposed Solution

I'll create isCluster() method like below.

```ts
export class Cluster extends Resource implements ICluster {

  /**
    * Return whether the given object is a Cluster
   */
  public static isCluster(x: any) : x is Cluster {
    return x !== null && typeof(x) === 'object' && CLUSTER_SYMBOL in x;
  }
}

Object.defineProperty(Cluster.prototype, CLUSTER_SYMBOL, {
  value: true,
  enumerable: false,
  writable: false,
});
```

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.67.0

### Environment details (OS name and version, etc.)

macOs Big Sur

**Comment by pahud** [comment]
Awesome! Thanks for the PR submission!
