### ISSUE TITLE
(aws-lambda): Issues deploying Lambda w/ nodeJs 18 runtime in gov cloud

### ISSUE THREAD

**Issue by developerfitz** [aws/aws-cdk#24460]
### CDK Deployment Issue
Unable able to deploy a lambda with the `nodeJs18.x` runtime using CDK v2 
in a Gov Cloud account. The documentation appears to support `nodejs18.x`.
Does the Lambda API not support the runtime `NODEJS_18_X` in gov cloud?

If `NODEJS_18_X` is available in gov cloud any suggestions or advice to point me in the right direction to try and fix this issue?

### Expected Behavior

A deployed Lambda with the `NODEJS_18_X` runtime in gov cloud.

### Current Behavior

I am getting the below error when trying to deploy a stack containing lambdas that are updated from the `NODEJS_16_X` to `NODEJS_18_X` runtime. 

```bash
Stack Deployments Failed: Error: The stack named <stack-name> failed to deploy: UPDATE_ROLLBACK_COMPLETE: Resource handler returned message: "Value nodejs18.x at 'runtime' failed to satisfy constraint: Member must satisfy enum value set: [nodejs12.x, provided, nodejs16.x, nodejs14.x, ruby2.7, java11, dotnet6, go1.x, provided.al2, java8, java8.al2, dotnetcore3.1, python3.7, python3.8, python3.9] or be a valid ARN
```

Is this the expected behavior in a gov cloud account? Checking the CloudTrail history it appears the API call is reaching the lambda endpoint, but the values provided are invalid despite the various documentation specifying `NODEJS_18_X` is available for use. It mentions all commercial regions, but does not explicitly exclude Gov Cloud.
- [AWS Lambda Docs](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html)
- [AWS CDK PR - nodeJs 18](https://github.com/aws/aws-cdk/pull/22964/files)
- [CDK API Ref](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda.Runtime.html#static-nodejs_18_x)

```text
// Info from one of the CloudTrail events for a failing API call

Error Code: InvalidParameterValueException
Event Name: UpdateFunctionConfiguration
Event Type: AwsApiCall
Event Source: lambda.amazonaws.com
User Agent: cloudformation.amazonaws.com,
Error Code: InvalidParameterValueException
Error Message: "Value nodejs18.x at 'runtime' failed to satisfy constraint: Member must satisfy enum value set: [nodejs12.x, provided, nodejs16.x, nodejs14.x, ruby2.7, java11, dotnet6, go1.x, provided.al2, java8, java8.al2, dotnetcore3.1, python3.7, python3.8, python3.9] or be a valid ARN"
```

### Reproduction Steps

```typescript
import * as cdk from "aws-cdk-lib";
import * as lambda from "aws-cdk-lib/aws-lambda";
import * as nodejs from "aws-cdk-lib/aws-lambda-nodejs";

// In a Stack
 const sampleFn = new nodejs.NodejsFunction(this, "SampleFunction", {
      entry: "src/sample-function.ts",
      runtime: lambda.Runtime.NODEJS_18_X,
      memorySize: 512,
      timeout: cdk.Duration.seconds(60),
    });
```

```bash
cdk deploy
```

### Possible Solution

Possibly, allow the `NODEJS_18_X` runtime in gov cloud if not yet available.

### Additional Information/Context

Trying to deploy a stack using CDK in a Gov Cloud account, and the documentation mentions `nodejs18.x` is available in all commercial regions, but does not mention gov cloud regions. 

### CDK CLI Version

2.64.0

### Node.js Version

18.14.2

### OS

macOS monterey

### Language

Typescript

### Language Version

Typescript (4.7.2)

**Comment by pahud** [comment]
According to the [doc](https://docs.aws.amazon.com/govcloud-us/latest/UserGuide/govcloud-lambda.html), lambda node18 runtime is not available in AWS GovCloud(US).

I will leave this feature request open till it is supported.

**Comment by KhaledEsmail99** [comment]
@pahud I'm not using GovCloud and couldn't able to find node18
 "aws-cdk": "2.70.0"
 "@types/aws-lambda": "^8.10.96"

**Comment by peterwoodworth** [comment]
I don't think we need to keep this open - this isn't able to be handled by us. It may have already gone through at this point too, since i see no mention of invalid runtime node 18 on the page Pahud linked

@KhaledEsmail99 if you need support please open a discussion with further details about your stack and the exact behavior you encounter
