### ISSUE TITLE
(core): Build script does not recognize dotnet >= 6

### ISSUE THREAD

**Issue by markusl** [aws/aws-cdk#24466]
### Describe the bug

Running `yarn build` does not succeed if dotnet 7 is installed.

### Expected Behavior

dotnet 7, which is Microsoft recommendation, should be recognized properly.

### Current Behavior

Checking dotnet version... Found dotnet version 7.0.102 [/usr/local/share/dotnet/x64/sdk]. Install dotnet >= 6.0.100

### Reproduction Steps

Install recommended .NET 7.0 version from https://dotnet.microsoft.com/en-us/download

### CDK CLI Version

2.66.1 (build 539d036)

### Node.js Version

v18.12.1

### OS

macOS

### Language

Typescript

**Comment by pahud** [comment]
Thank you for the call out and the PR! I think it makes sense here.
