### ISSUE TITLE
CDK CodePipeline: Default Build Image Out of Support March 2023

### ISSUE THREAD

**Issue by Althum2000** [aws/aws-cdk#24474]
### Describe the feature

The current default build image for CDK pipeline generated CodeBuild projects is 'aws/codebuild/standard:5.0'.  AWS has issued notices to say that this image will be unsupported after 30th March 2023 which means slower provisioning times as the image will no longer be cached.

Please can we have the default image updated to version 6.0. without delay so that product teams can redeploy their pipelines without having to make code changes to specify the build image?

### Use Case

Slower provisioning times for CodeBuild jobs in CDK generated pipelines will result from NOT making this update before 30th March 2023.

### Proposed Solution

Update the default image to 6.0.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.67.0

### Environment details (OS name and version, etc.)

Ubuntu 20

**Comment by pahud** [comment]
And according to [this](https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-available.html), yes we probably should set the default image to 6.0.

**Comment by Althum2000** [comment]
Confirmed with TAM this afternoon that the dashboard notifications reflect the reality of the situation and the date is confirmed as 30th March 2023.  Given the short term notice for the change, I wonder if the proliferation of CodeBuild projects via CDK was taken into account.

**Comment by pahud** [comment]
As https://github.com/aws/aws-cdk/pull/24544 was merged. I am closing this issue now. Feel free to re-open if it's still relevant.
