### ISSUE TITLE
redshift: Requested attribute ParameterGroupName must be a readonly property in schema for AWS::Redshift::ClusterParameterGroup

### ISSUE THREAD

**Issue by ivanblagdan** [aws/aws-cdk#24480]
### Describe the bug

When trying to access prop `attrParameterGroupName` of Redshifts `CfnClusterParameterGroup`, the stack fails to update with the error: 

```Requested attribute ParameterGroupName must be a readonly property in schema for AWS::Redshift::ClusterParameterGroup```

I'm using this as prop as input for `CfnCluster.clusterParameterGroupName`. The stack was provisioned successfully with this pattern and only started failing to update recently.

If I manually pass the string name of the parameter group, the stack update goes through as expected.

### Expected Behavior

The stack should be able to retrieve the name of the ParamaterGroup via `CfnClusterParameterGroup.attrParameterGroupName`.

### Current Behavior

Stack fails update with error: ```Requested attribute ParameterGroupName must be a readonly property in schema for AWS::Redshift::ClusterParameterGroup```

### Reproduction Steps

1. Create an instance of CfnClusterParameterGroup
2. Create an instance of CfnCluster, and use the CfnClusterParameterGroup.attrParameterGroupName for its clusterParameterGroupName property.

### CDK CLI Version

2.60.0 (build 2d40d77)

### Framework Version

2.45.0

### Node.js Version

v14.20.0

### OS

Mac OS 13.2.1 (22D68)

### Language

Typescript

### Language Version

4.9.4

**Comment by pahud** [comment]
Hi

Can you provide the full code snippet you used so we can reproduce in our account? Thank you.

**Comment by pahud** [comment]
Hi

Is this issue still relevant?

According to the API reference [here](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_redshift.CfnClusterParameterGroup.html#parametergroupname-1) I guess you should use `parameterGroupName` to reference the L1 attribute instead. Can you let me know if this works for you?
