### ISSUE TITLE
(aws-glue-alpha):  glue.Code.fromAsset does not package the script

### ISSUE THREAD

**Issue by deshruch** [aws/aws-cdk#24481]
### Describe the bug

I am trying to create a Glue job as shown here:

import * as glue from '@aws-cdk/aws-glue-alpha';

    const job = new glue.Job(this, 'testJob', {
            executable: glue.JobExecutable.pythonEtl({
                glueVersion: glue.GlueVersion.V3_0,
                pythonVersion: glue.PythonVersion.THREE,
                script: glue.Code.fromAsset('../scripts/glue/testScript.py')
            }),
            continuousLogging: { enabled: true },
            description: 'test',
            jobName: 'testJob'
        });

The job is deployed, but fails to load the script with 'No such key' error.
The synthesized template shows that the script name has changed to a hash:

```

"BackendApplicationAthenaConstructtestJobCB459564": {
   "Type": "AWS::Glue::Job",
   "Properties": {
    "Command": {
     "Name": "glueetl",
     "PythonVersion": "3",
     "ScriptLocation": {
      "Fn::Join": [
       "",
       [
        "s3://",
        {
         "Fn::Sub": "health-recruit-assets-${AWS::Region}"
        },
        "/health-recruit/v1.0.0/373c6499ca7d843846dd48e2728b5f5c9e17b4f77d5d2a7bc0abaaf0e83233ed.py"
       ]
      ]
     }
    },
    "Role": {
     "Fn::GetAtt": [
      "BackendApplicationAthenaConstructtestJobServiceRole39B84C30",
      "Arn"
     ]
    },
    "DefaultArguments": {
     "--job-language": "python",
     "--enable-continuous-cloudwatch-log": "true",
     "--enable-continuous-log-filter": "true"
    },
    "Description": "test",
    "GlueVersion": "3.0",
    "Name": "testJob"
   }
  },

```

This hash name script is not present an an asset, resulting no such file being uploaded to S3 which in turn results in the 'no such key' error.

### Expected Behavior

The Glue script must be package when  glue.Code.fromAsset is used

### Current Behavior

The job is deployed, but fails to load the script with 'No such key' error.
The synthesized template shows that the script name has changed to a hash:

### Reproduction Steps

Create a Stack using above steps to create a Glue job with script location- fromAsset

### CDK CLI Version

2.50.0

### Node.js Version

16.15.1

### OS

Mac OS Monterey 12.6.3

### Language

Typescript

### Language Version

4.6.3

**Comment by pahud** [comment]
Can you share the full error message of that?

**Comment by deshruch** [comment]
Closing this issue. It was an issue elsewhere.
