### ISSUE TITLE
custom_resources: log retention rate limit error during deploy

### ISSUE THREAD

**Issue by jsauter** [aws/aws-cdk#24485]
### Describe the bug

When deploying a stack containing a custom resource, we received several rate limit exceptions when the cdk code deployed the logRetention infrastructure.  This seems to happen intermittently and we have not received feedback recently of the issue.  However, we figured you would like to know.

### Expected Behavior

Not to receive a rate limit exception and the application to deploy.

### Current Behavior

Deploying cdk application that contained a customer resource and lambda, the logRetention infrastructure generated a rate exceeded exception.

### Reproduction Steps

It has not happened recently, but create a cdk application with a custom resource that has configuration that will generate a logRetention policy etc.  

### Additional Information/Context

We are curious if there is a way to manage these rate limit exceptions if they are outside of our code.

### CDK CLI Version

2.29.1

### Node.js Version

14.18.3

### OS

macos

### Language

Typescript

**Comment by jsauter** [comment]
![Screen Shot 2023-03-06 at 3 33 18 PM](https://user-images.githubusercontent.com/4924552/223268687-30a754b3-58e0-4f53-ab0f-81b610ca9a2e.png)

**Comment by jsauter** [comment]
Console output during deploy.

![Screen Shot 2023-03-06 at 3 33 18 PM](https://user-images.githubusercontent.com/4924552/223268994-65b52af6-3559-42f2-a11e-462e3ed3d603.png)

**Comment by cgarvis** [comment]
thanks @jsauter for the report.

**Comment by khushail** [comment]
Hey @jsauter , thanks for reporting this, as we can't tell what's the rate limit is about, this screenshot is still very helpful.

**Comment by pahud** [comment]
Hi @jsauter 

Can you tell how many custom resources you are creating in this CDK app? I am just interested where the limit rate comes from.

**Comment by jsauter** [comment]
> 

It this case of this stack, we are created a custom resource and configuring it for log retention.  So one in our code, and I guess two from CDK, the 'AWS CDK resource provider framework - onEvent'  and the logRetetion cr.

**Comment by idwagner** [comment]
I'm also running into the issue that the logrotation lambda is timing out at three seconds, causing the stack to timeout/fail. Some additional tuning options would be helpful to resolve issues with this without having to use escape hatches.

```
INIT_START Runtime Version: nodejs:14.v29	Runtime Version ARN: arn:aws:lambda:us-east-1::runtime:XXXXXX
START RequestId: 8fe6a7e5-a521-48dd-8f73-07b97e0feff2 Version: $LATEST
2023-03-09T15:29:10.583Z	8fe6a7e5-a521-48dd-8f73-07b97e0feff2	INFO	
{
    "RequestType": "Create",
    "ServiceToken": "arn:aws:lambda:us-east-1:XXXX:function:XXXXX-LogRetentionaae0aa3c5b4d4f87b0-m6gZos1arCB1",
    "ResponseURL": "...",
    "StackId": "arn:aws:cloudformation:us-east-1:XXXXX:stack/XXXXX/f4e26fa0-be8d-11ed-8fb1-0ecbd2482a13",
    "RequestId": "1b1b5d99-72d0-43ba-936d-49ab668ffe0b",
    "LogicalResourceId": "XXXXXXLogRetentionED515AF7",
    "ResourceType": "Custom::LogRetention",
    "ResourceProperties": {
        "ServiceToken": "arn:aws:lambda:us-east-1:XXXXX:function:XXXXX-LogRetentionaae0aa3c5b4d4f87b0-m6gZos1arCB1",
        "RetentionInDays": "7",
        "LogGroupName": "/aws/lambda/XXXXX-c1quvH5k3SfR"
    }
}

2023-03-09T15:29:13.587Z 8fe6a7e5-a521-48dd-8f73-07b97e0feff2 Task timed out after 3.01 seconds

END RequestId: 8fe6a7e5-a521-48dd-8f73-07b97e0feff2
REPORT RequestId: 8fe6a7e5-a521-48dd-8f73-07b97e0feff2	Duration: 3006.29 ms	Billed Duration: 3000 ms	Memory Size: 128 MB	Max Memory Used: 26 MB	
```

**Comment by dylan-westbury** [comment]
Also receiving rate exceeded for log retention for cdk stack. 

<img width="1097" alt="Screenshot 2023-08-07 at 6 31 28 pm" src="https://github.com/aws/aws-cdk/assets/16129043/86ea037c-d785-4e5e-8673-775060a3394f">



```
6:11:56 pm | CREATE_FAILED        | Custom::LogRetention                   | updateUserFuncLogRetention149A7992
Received response status [FAILED] from custom resource. Message returned: Rate exceeded (RequestId: c4ef077d-2d0b-456d-b6ee-06cb37f18d7b)

6:11:56 pm | CREATE_FAILED        | Custom::LogRetention                   | CreateTeamUserFunc...gRetention023842B5
Received response status [FAILED] from custom resource. Message returned: Rate exceeded (RequestId: bc0e7573-2a33-4ea5-916b-ab4397ec3cd2)
```

**Comment by jusdino** [comment]
I'm also hitting this issue. Here's a stack trace for reference. I think the lambda code just needs to have a reasonable retry policy set:
```2023-08-15T22:50:17.218Z	af3b73cb-af4e-491a-a5bd-e16897a7af65	INFO	ThrottlingException: Rate exceeded
    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'ThrottlingException',
  time: 2023-08-15T22:50:17.215Z,
  requestId: '59263e11-a284-42cb-8b4d-097c4cfe7c40',
  statusCode: 400,
  retryable: true
}
```

We've got devs running into this - all you have to do is try to deploy an app with a bunch of lambdas, all with `logRetention` set.

**Comment by jusdino** [comment]
Doing a little digging, in case it helps somebody, it looks like the LogRetention function code just [pulls retry options from its resource properties](https://github.com/aws/aws-cdk/blob/b23252b99559ad1a1f0e05b6936c60f9c52522ff/packages/aws-cdk-lib/aws-logs/lib/log-retention-provider/index.ts#L94), which is also available to specify by the user in `aws-lambda.Function` via the [`logRetentionRetryOptions`](https://github.com/aws/aws-cdk/blob/b23252b99559ad1a1f0e05b6936c60f9c52522ff/packages/aws-cdk-lib/aws-lambda/lib/function.ts#L322) property, though you're only given a `maxRetries` option, which apparently defaults to `5`.

I'm not familiar with the JavaScript aws-sdk, so it's unclear to me if these rate exceeded errors are retried and what the sdk v3 retry strategy looks like, if it does. I don't see any logs in CloudWatch indicating that any retries were done.

**Comment by jusdino** [comment]
I think it was because they migrated from SDK v2 to SDK v3 in the lambda and retry strategies work differently in v3.

**Comment by jaapvanblaaderen** [comment]
This issue got worse since `CDK 2.90`: https://github.com/aws/aws-cdk/issues/26837
