### ISSUE TITLE
(@aws-cdk/aws-s3-deployment): Allow setting AWS CLI S3 Configuration Values

### ISSUE THREAD

**Issue by zakyg** [aws/aws-cdk#24511]
### Describe the feature

Allow Allow setting AWS CLI S3 configuration values to fine tune the s3 transfer details.

### Use Case

We’re using BucketDeployment to upload a Realtime script for our GameLift fleet. The process currently breaks when uploading a file larger then 8mb - according to the GameLift team. this is due to the multipart upload. The proposed solution by the GameLift team is to move away from CDK and do the deployment as a separate process, but this is going to be detrimental to the way we manage our infrastructure. If we could somehow set the multipart_threshold to be larger then 8mb this problem would go away.

### Proposed Solution

BucketDeploymentProps could have a map parameter to specify configuration values. For example:

`new BucketDeployment(this, "BucketDeployment", new BucketDeploymentProps
                {
                    DestinationBucket = destinationBucket,
                    Sources = new[] { Source.Asset("assets-folder/") },
                    S3Configuration = new Dictionary<string, object> { "multipart_threshold", "100mb" }
                });`

### Other Information

The proposed solution would also address issue https://github.com/aws/aws-cdk/issues/15609

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.53.0 (build 7690f43)

### Environment details (OS name and version, etc.)

MacOS Ventura 13.2 (22D49)

**Comment by pahud** [comment]
I am not sure if this is related to any GameLift limitation but yes we probably can expose the s3 sync arguments to the surface.

https://github.com/aws/aws-cdk/blob/21aa42144548099cac9b9dcd03ea842c01cddb09/packages/%40aws-cdk/aws-s3-deployment/lib/lambda/index.py#L172-L187

Have you every tried `aws s3 sync` from your local environment to GameLift with the default arguments? Does it work without increasing the multipart_threshold?

And you probably will want to raise the [memoryLimit](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-s3-deployment.BucketDeployment.html#memorylimit) for large file transfer performance as the default 128MB might be a blocker in your case.

**Comment by pahud** [comment]
>According to GameLift, they don't support pulling game scripts which are uploaded to S3 with a multipart upload, I'm not sure about the internals beyond that.

Do you have any public document about this limit?

**Comment by zakyg** [comment]
Unfortunately no. We have started running into an issue when deploying game script zips which are > 8mb and contacted support. In case you have access to support cases, the aws support case id is 11924392891. Here is an excerpt from the AWS rep response:

> We have strong reason to believe that CDK switches to multi-upload after the file is 8MB or larger. So, manually uploading the script should solve this issue for the customer.
------------------

Hence we have tried uploading the file manually and from CLI and could see that we are not facing any issue. Currently team have mentioned that the workaround is to use CLI or AWS SDK to upload the file to S3
[+] [https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3api/put-object.html ](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3api/put-object.html)
[+] [https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObject.html ](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObject.html)

Further regarding Game Lift to support files uploaded as multi-part, its currently not supported and team have marked this as feature request.

**Comment by pahud** [comment]
@zakyg 

Thank you for providing the support case ID. I'll see what I can do with that.

**Comment by zakyg** [comment]
@pahud thank you for looking into this for us.

The last communication we've had with the support team indicated that they don't treat this as a bug but as a feature enhancement (as you can see in the last response which I've quoted above), which we assumed went into a backlog. This is why we explored ways to get around the issue right now, like the one suggested in this feature request. 

I'm understanding that you're seeing something that we aren't, which indicates that the team is working on fixing the multipart issue that they've mentioned? I'm asking this because proceeding with the recommendation from Support (using the sdk / cli scripts) would break our CDK centered deployment process and we're really trying to find any way to avoid going there.

**Comment by pahud** [comment]
@zakyg Thank you for your prompt reply.

I believe you should be able to deploy with CDK without modifying your CDK code very soon as in cdk-s3-deployment essentially executes the AWS CLI to run `aws s3 sync` for you under the covers.  As you have already created a premium support ticket, the support engineer would have been coordinating your ticket with relevant teams. Please make sure to reach out to your support engineer through your ticket for the update. I hope you can deploy your GameLift workload with CDK smoothly as expected very soon.
