### ISSUE TITLE
aws-s3: The `eventBridgeEnabled` property of the `Bucket` Object Errors on Deployment

### ISSUE THREAD

**Issue by X-Guardian** [aws/aws-cdk#24520]
### Describe the bug

When deploying a stack that has `eventBridgeEnabled: true` on a [Bucket](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_s3.Bucket.html) object, the deployment fails.

### Expected Behavior

On deployment, the stack should deploy and enable the EventBridge notification on the S3 bucket.

### Current Behavior

The following error is thrown on deployment:

```
Stack Deployments Failed: Error: The stack named dev-s3 failed to deploy: UPDATE_ROLLBACK_COMPLETE: Received response
status [FAILED] from custom resource. Message returned: Error: An error occurred (AccessDenied) when calling the
PutBucketNotificationConfiguration operation: Access Denied. See the details in CloudWatch Log Stream:
2023/03/08/[$LATEST]927d904acae34ae38736e2947ce07c72 (RequestId: c3f37496-7410-4db5-98c1-9c67e7d46da9), Received
response status [FAILED] from custom resource. Message returned: Error: An error occurred (AccessDenied) when calling the
PutBucketNotificationConfiguration operation: Access Denied. See the details in CloudWatch Log Stream: 
2023/03/08/[$LATEST]927d904acae34ae38736e2947ce07c72 (RequestId: 004c11a2-437e-4f58-90be-ca70d1cd7959)
```

### Reproduction Steps

Deploy a stack that includes the following construct:

```typescript
const bucket = new Bucket(this, `bucket`, {
                bucketName : 'this-bucket,
                eventBridgeEnabled : true
}
```

### Possible Solution

Looking at the synthed CloudFormation for this stack, a CloudFormation custom resource is used to configure this setting. The permissions policy for the custom resource role is:

```
Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: s3:PutBucketNotification
            Effect: Allow
            Resource: "*"
        Version: "2012-10-17"
```

The `action` value is not correct, as the API being used is `PutBucketNotificationConfiguration`.

### CDK CLI Version

2.67.0 (build b6f7f39)

### Node.js Version

v18.12.1

### OS

Windows 11

### Language

Typescript

### Language Version

typescript 4.6.3

### Other information

Here is the original PR that adds this feature: https://github.com/aws/aws-cdk/pull/18614.

Here is the code that is building the custom resource policy: https://github.com/aws/aws-cdk/blob/b2d293d3f8d36547d8cfd7ff3957428718c3827f/packages/%40aws-cdk/aws-s3/lib/notifications-resource/notifications-resource-handler.ts#L69-L72

The [PutBucketNotification](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutBucketNotification.html) API has been deprecated at some point and replaced with [PutBucketNotificationConfiguration](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutBucketNotificationConfiguration.html).

**Comment by corymhall** [comment]
Not sure what was going on, but you may be right and it may have been a transient issue. Looking at the code we are using the correct permissions and the correct API method so there shouldn't be any issue.

I'm going to close this, but if anyone sees this issue again let us know.
