### ISSUE TITLE
aws_cdk.aws_apigateway.RestApi:  returns _RestApiBaseProxy not RestApi as indicated

### ISSUE THREAD

**Issue by czabriskie** [aws/aws-cdk#24528]
### Describe the issue

When referencing an existing `aws_cdk.aws_apigateway.RestApi` with the `from_rest_api_id` method, the documentation states that a IRestApi will be returned , but instaed we get a Proxy.

Specifically, I need to reference an existing restAPI and reference it in a eventbridge rule, `aws_cdk.aws_events.Rule`, which is expecting a restAPI not a proxy.

### Links

Documentation: https://docs.aws.amazon.com/cdk/api/v1/python/aws_cdk.aws_apigateway/RestApi.html
Related Bug: https://github.com/aws/aws-cdk/issues/22523

**Comment by czabriskie** [comment]
This is the error when passing the `_RestApiBaseProxy` to the `aws_cdk.aws_events.Rule().add_target` method

```
TypeError: type of argument rest_api must be aws_cdk.aws_apigateway.RestApi; got aws_cdk.aws_apigateway._RestApiBaseProxy instead
```

**Comment by czabriskie** [comment]
Sure, the arn would be different for every user though

```
from aws_cdk.aws_apigateway import RestApi
from aws_cdk.aws_events import Rule, Schedule

api = RestApi.from_rest_api_id(self,
                                                    "RestAPI",
                                                    rest_api_id="some_id")

 rule = Rule(self, "ScheduleRule",
             schedule=Schedule.cron(minute="1")
             )

rule.add_target(
            targets.ApiGateway(api,
                               path="/path,
                               method="GET",
                               stage="prod"
                               ))
```

**Comment by peterwoodworth** [comment]
This is [how importing resources works](https://docs.aws.amazon.com/cdk/v2/guide/resources.html#resources_external). [We require a `RestApi`, not an `IRestApi`](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_events_targets.ApiGateway.html#restapi) when creating an ApiGateway target, because we don't get the full information necessary with the imported resource
