### ISSUE TITLE
redshift: no default id being assigned

### ISSUE THREAD

**Issue by Rizxcviii** [aws/aws-cdk#24545]
### Describe the bug

Upon the recent release, column ids were introduced, however the default value of the `id` is not set.
The `id` should be set to the `name` property, however this is not the case. The `cdk diff` does not show this.

### Expected Behavior

Upon not setting an id in the `Table` construct.
```
[ ]   {
[ ]     "name": "col3",
[ ]     "dataType": "float",
[ ]     "comment": "A test column",
[-]     "encoding": "RAW"
[+]     "encoding": "RAW",
[+]     "id": "col3"
[ ]   }
```

### Current Behavior

```
[ ]   {
[ ]     "name": "col3",
[ ]     "dataType": "float",
[ ]     "comment": "A test column",
[-]     "encoding": "RAW"
[+]     "encoding": "RAW",
[ ]   }
```

### Reproduction Steps

Create a new table, without setting the `id` property of that table.
```typescript
new redshift.Table(stack, 'Table', {
  ...databaseOptions,
  tableColumns: [
    { name: 'col1', dataType: 'varchar(4)' },
    { name: 'col2', dataType: 'float' },
    { name: 'col3', dataType: 'float' },
  ],
});
```

### Possible Solution

Update the `addColumnIds` function to include the necessary functionality, which is a side effect to append on a column id if not present.

### Additional Information/Context

This should have been implemented in the recent update, however this was overlooked.

### CDK CLI Version

2.68.0

### Node.js Version

v16.16.0

### OS

Amazon Linux 2

### Language

Typescript, Python

### Language Version

TypeScript (3.7.5) | 3.7.16

### Other information

The PR that should have contained the fix is included here:
https://github.com/aws/aws-cdk/pull/24272

**Comment by pahud** [comment]
Does this happen when creating a new table or updating an existing one without `id` column?

And, thank you for your PR!!

**Comment by Rizxcviii** [comment]
> Does this happen when creating a new table or updating an existing one without `id` column?
> 
> And, thank you for your PR!!

@pahud This happens for both. Ids are not being appended on either applications.

**Comment by pahud** [comment]
Thank you for the clarification @Rizxcviii . We'll be happy to review your PR when it's ready. Thanks.
