### ISSUE TITLE
(s3-deployment): add yamlData

### ISSUE THREAD

**Issue by RichiCoder1** [aws/aws-cdk#24554]
### Describe the feature

The PR https://github.com/aws/aws-cdk/pull/18659 added the excellent `data` and `jsonData` helpers. I'd like to add a `yamlData` equivalent, which should just be the same as `jsonData`, but strigifyied to YAML.

### Use Case

It's not uncommon for config files to be yaml instead of JSON (see Cloudformation :D), so I'd just like to be able to take advantage of the same optimization as `jsonData`

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

v2.68.0

### Environment details (OS name and version, etc.)

Windows 11

**Comment by khushail** [comment]
Hi @RichiCoder1 ,thanks for reaching out with this request. 

I am marking this as P2 and we would be happy to review your PR when available. Sharing the [contributing](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md#step-1-find-something-to-work-on) guide to get started.
