### ISSUE TITLE
aws-cdk-lib/aws-cloudfront: AllViewerExceptHostHeader is missing from OriginRequestPolicy

### ISSUE THREAD

**Issue by nidhin-raj** [aws/aws-cdk#24552]
### Describe the feature

In documentation there is reference to a managed policy called `AllViewerExceptHostHeader`, https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/using-managed-origin-request-policies.html

This is beneficial in cloudfront-apigateway integration. However, this policy alone is missing from aws-cdk-lib. 

### Use Case

Once available we can use this policy as 
`originRequestPolicy: cloudfront.OriginRequestPolicy.ALL_VIEWER_EXCEPT_HOST_HEADER `

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

"aws-cdk-lib": "^2.68.0"

### Environment details (OS name and version, etc.)

windows 10

**Comment by khushail** [comment]
Thanks for reaching out @nidhin-raj with this feature request. I am marking this as P2 which means we are unable to work on this immediately. However if you would like to contribute, here is a [contributing guide ](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md#step-1-find-something-to-work-on)to get started. 

We use +1s to help prioritize our work, and are happy to re-evaluate this request based on community feedback. You can reach out to the [cdk.dev](http://cdk.dev/) community on [Slack](https://cdk.dev/) to solicit support for re-prioritization.

**Comment by stefanfreitag** [comment]
I tried to come up with a PR for this. It is linked against this issue. Still need to check on possible changes for the README and the integrations tests.

**Comment by stefanfreitag** [comment]
@khushail Would be awesome if you find time to review the PR. Code + integration test are in place. Please let me know if changes are required.

**Comment by khushail** [comment]
Thanks @stefanfreitag , appreciate your contribution. It would be great if you could re-base your code. I would mark that PR with appropriate tags for visibility and review by our team.
