### ISSUE TITLE
(metadata): Add source information to the generated stack

### ISSUE THREAD

**Issue by evgenyka** [aws/aws-cdk#24555]
### Describe the feature

Provide framework for enhancing generated templates with custom metadata.

### Use Case

I build an application with the CDK; it (eventually) works; yay. It's deployed, I forget about it for years. 
One day need to make a change (for whatever reason).
I can find the Cloudformation stack the CDK generated easily enough, but then I'm left having to hunt down where the CDK repository that generated it lives, on which computer, etc. etc. etc.

### Proposed Solution

Add additional info metadata info to the generated stack. For example: git repo URL and (optionally) commit hash.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.67.0

### Environment details (OS name and version, etc.)

MacOS 12.6.3

**Comment by markusl** [comment]
I think commit hash (and branch) could even be a part of stack tags by default, making it easy to check from which version the stack was deployed from. Many users might not be able to extract the information from the template metadata.

**Comment by evgenyka** [comment]
I was able to achieve that by using tags: 

```
import {S3ObjectLambdaStack} from '../lib/s3-object-lambda-stack';
import { Tag, Tags } from '@aws-cdk/core';
import * as gitRev from 'git-rev-sync';

const app = new cdk.App();
const S3ObjectLambda = new S3ObjectLambdaStack(app, 'S3ObjectLambdaStack');

// Get the Git repository and commit information
const gitRepoUrl = gitRev.remoteUrl();
const gitCommitId = gitRev.short();

Tags.of(S3ObjectLambda).add("gitRepoUrl", gitRepoUrl);
Tags.of(S3ObjectLambda).add("gitCommitId", gitCommitId);


```

**Comment by corymhall** [comment]
I think this can be accomplished with a combination of stack metadata and resource tags. If I want to add metadata to the stack I can do 

```ts
const stack = new Stack();
stack.addMetadata('git_repo', 'https://github.com/aws/aws-cdk');
```

If I want to add the information to resources I can use tags like @evgenyka's comment above.

@evgenyka is there anything else you were thinking we need to implement in regards to this?
