### ISSUE TITLE
DynamoDB: Deletion protection

### ISSUE THREAD

**Issue by arjanschaaf** [aws/aws-cdk#24560]
### Describe the feature

Deletion protection is now available for Amazon DynamoDB tables in all AWS Regions. DynamoDB now makes it possible for you to protect your tables from accidental deletion when performing regular table management operations. 
https://aws.amazon.com/about-aws/whats-new/2023/03/amazon-dynamodb-table-deletion-protection/

### Use Case

Feature parity with CFN for newly created feature in the CDK DynamoDB Table construct.

### Other Information

CDK needs to be updated to latest CFN Specification first.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

v2.68.0

### Environment details (OS name and version, etc.)

n/a

**Comment by pahud** [comment]
Thank you. As we already have https://github.com/aws/aws-cdk/issues/24540, I am closing this one to avoid duplication.

**Comment by arjanschaaf** [comment]
I just noticed, great speed by the community! 😅
