### ISSUE TITLE
aws-sagemaker: Studio Space can not be created with aws-cdk

### ISSUE THREAD

**Issue by chihebdaoues** [aws/aws-cdk#24585]
### Describe the feature

One can not create a Sagemaker Studio Space using aws-cdk, although the Cloudformation property exists [AWS::SageMaker::Space](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sagemaker-space.html)

### Use Case

I am trying to create a SageMaker Domain space using cdk but can't find the L1 construct associated to [AWS::SageMaker::Space](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sagemaker-space.html)

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.68.0

### Environment details (OS name and version, etc.)

MacOS

**Comment by pahud** [comment]
related to https://github.com/aws/aws-cdk/issues/24540

**Comment by matt9ucci** [comment]
@chihebdaoues @pahud This issue could be closed. AWS CDK v2.83.1 provides [CfnSpace class](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_sagemaker.CfnSpace.html) now.
