### ISSUE TITLE
codebuild: Usage of unsupported default docker image aws/codebuild/standard:5.0.

### ISSUE THREAD

**Issue by niraj-khandelwal** [aws/aws-cdk#24609]
### Describe the bug

Received a AWS Notification -

We are reaching out to you because you ran a build using the Ubuntu standard 5.0 [1] Docker Image, Amazon Linux 2 ARM standard 1.0 [2], or Amazon Linux 2 standard 3.0 [3] in the last 30 days. Starting March 30, 2023, AWS CodeBuild will be moving these images to an unsupported status and they will not be cached on the build hosts anymore.

You may continue using these images for your builds, but you will notice an increase in provisioning latency after March 30, 2023.
These images will also not be getting any new updates. We recommend updating your Build Projects to use the latest build images in order to get the latest language runtimes and tools. For more information on how to do this you can follow 'Docker images provided by CodeBuild' [4].

Upon checking, we have identified that CDK Codecuild project is using Docker Image: aws/codebuild/standard:5.0 

### Expected Behavior

CDK Codebuild project should use supported docker image 

### Current Behavior

CDK Codecuild project is using Docker Image: aws/codebuild/standard:5.0 
This will be deprecated soon

### Reproduction Steps

selfupdate and PipelineBuildSynthCdkBuild codebuild is using unsupported docker image

### CDK CLI Version

2.50.0

### Node.js Version

NA

### OS

Linux

### Language

Python

**Comment by pahud** [comment]
Hi

If you provision codebuild project with aws-codebuild, the default build image should be `LinuxBuildImage.STANDARD_1_0` if unspecified and you can opt in `STANDARD_6_0` in `props.environment.buildImage`.

https://github.com/aws/aws-cdk/blob/1105514fc88ae4637a5d187a48ff1a37a4932579/packages/%40aws-cdk/aws-codebuild/lib/project.ts#L1042

And if you are using cdk pipelines, according to https://github.com/aws/aws-cdk/pull/24544 the default image should be `STANDARD_6` which will be available in next CDK release(v2.69.0)

Let me know if it helps you clarify the issue.

**Comment by niraj-khandelwal** [comment]
Sorry for delay in response

I updated cdk version to 2.69.0. It fixed codebuild project docker image to aws/codebuild/standard:6.0. 

Closing this issue

**Comment by niraj-khandelwal** [comment]
I updated cdk version to 2.69.0. It fixed codebuild project docker image to aws/codebuild/standard:6.0.

**Comment by mfittko** [comment]
@niraj-khandelwal Does that mean, that building on ARM based images will no longer be supported and we can move our production workloads away from graviton2 as well?

**Comment by niraj-khandelwal** [comment]
@mfittko - not sure, if I understood your requirement clearly. 
I have created CDK pipeline with OOB features and so earlier version of CDK were using unsupported Docker image. Updating CDK version fix this and it also updated to supported version of Docker Image
