### ISSUE TITLE
(aws-ecs): The sum of all container cpu values should be lower than the value of the task cpu

### ISSUE THREAD

**Issue by sakurai-ryo** [aws/aws-cdk#24629]
### Describe the feature

Hi team.

I would like to add a validation for cpu in ContainerDefinition.
In ECS, the total cpu of each ContainerDefinition cannot exceed the CPU defined in the TaskDefinition.
Currently, if write such code, it will not be validated and will be deployed to CloudFormation with an error.

### Use Case

Allow errors to be detected at the Synth stage before the CDK is deployed.

### Proposed Solution

Validation is performed when a container is added using the addContainer method.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

v2.69.0

### Environment details (OS name and version, etc.)

MacOS

**Comment by pahud** [comment]
Yes this makes sense. What is the full error message from cloudformation?

**Comment by sakurai-ryo** [comment]
@pahud 
Cfn gives the following error.

`Invalid request provided: Create TaskDefinition: The sum of all container 'cpu' values cannot be greater than the value of the task 'cpu'. (Service: AmazonECS; Status Code: 400; Error Code: ClientException; Request ID: ea9cf1a8-31b2-46
d7-b654-f5ef522d02ef; Proxy: null)`

**Comment by pahud** [comment]
Awesome! I think it makes perfect sense to have CDK validate this before deployment.
