### ISSUE TITLE
CDK pipelines: File [... .template.json] does not exist in artifact [Synth_Output]

### ISSUE THREAD

**Issue by alejandroSpark** [aws/aws-cdk#24632]
### Describe the bug

A stack template is not found by CodePipeline in the `prepare` step of the first stage added when deploying a CDK pipeline.

### Expected Behavior

CDK pipeline finds the stack template generated in the `primaryOutputDirectory` or allows the generation of a personalized stack template filename.

### Current Behavior

The `prepare` phase of the CodePipeline stage (in which it is tried to deploy a stack) fails with the following error:

`File [assembly-CICDStack-FirstStage/CICDStackFirstStageStackToDeploy55271C95.template.json] does not exist in artifact [Synth_Output]`

### Reproduction Steps

When deploying a CDK Pipeline, the Prepare step of the first stage of the pipeline fails with the following error:

`File [assembly-CICDStack-FirstStage/CICDStackFirstStageStackToDeploy55271C95.template.json] does not exist in artifact [Synth_Output]`

The stack definition looks like:

```
export default class CiCdDevelopStack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);
   
    const shellStep = new ShellStep('Synth', {
      input: CodePipelineSource.connection(`${REPO_OWNER}/${REPO_NAME}`, `${REPO_DEVELOP_BRANCH}`, { connectionArn: CONNECTION_ARN }),
      commands: [
        'cd infrastructure',
        'yarn install --frozen-lockfile',
        'CDK_TARGET_ENV=dev npx cdk synth -o ./cdk.dev.out/'
      ],
      primaryOutputDirectory: "infrastructure/cdk.dev.out/"

    })

    const cdPipeline = new CodePipeline(this, 'Pipeline', {
      pipelineName: 'CDPipeline',
      selfMutation: false,
      synth: shellStep,
    });

    cdPipeline.addStage(new FirstStage(this, FIRST_STAGE, { env: getTargetEnvironment() }));
  }
}

```

The third command of the `ShellStep` (`CDK_TARGET_ENV=dev npx cdk synth -o ./cdk.dev.out/`) produces a file like `./cdk.dev.out/StackToDeploy.template.json`. However, the stage added tries to find a file with the name `assembly-CICDStack-FirstStage/CICDStackFirstStageStackToDeploy55271C95.template.json` instead.

### Possible Solution

It is possible to modify the file name of the template through the AWS console, but I hadn't found the way to do it through CDK.

![image](https://user-images.githubusercontent.com/126483936/225352896-d1c148c4-cd04-45ba-a5a2-59301cc010bb.png)

### CDK CLI Version

2.61.1 (build d319d9c)

### Node.js Version

v18.12.1

### OS

macOS Ventura 13.1

### Language

Typescript

### Language Version

Typescript

**Comment by khushail** [comment]
Hi @alejandroSpark , thanks for reporting this bug. However I am unable to repro the issue. It would be great if you could share the snippet of your directory structure and also the code for `getTargetEnvironment()` function.
