### ISSUE TITLE
(aws-dynamodb): Add a property to TableOptions to set "DeletionProtectionEnabled" property

### ISSUE THREAD

**Issue by r0b0ji** [aws/aws-cdk#24655]
### Describe the feature

This is a new feature by Dynamodb team to add a deletion protection on dynamodb table. It needs to be made available by CDK as well.

The cloudformation documentation: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html

Blog post: https://aws.amazon.com/blogs/database/how-to-use-deletion-protection-to-enhance-your-amazon-dynamodb-table-protection-strategy/

### Use Case

Production table needs to be protected against accidental delete. Dynamodb has delivered this new feature where it can be enabled at per table. This feature is available through console/cli/sdk.

This ask is to make it available through cdk.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.60

### Environment details (OS name and version, etc.)

macos, amazon linux2

**Comment by khushail** [comment]
Hi @r0b0ji , thanks for suggesting this feature request. There is already an [existing request ](https://github.com/aws/aws-cdk/issues/24540)for the same feature upgrade, which is work-in-progress.
