### ISSUE TITLE
(opensearch): (can not support cold storage enable when create a new opensearch cluster)

### ISSUE THREAD

**Issue by JiaTingYefei** [aws/aws-cdk#24658]
### Describe the bug

Not support cold storage enable when create a new opensearch cluster.
There is no ColdStorageOption  in Opensearch  Domain and CfnDomain : can not support cold storage enable when create a new opensearch cluster:
https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_opensearchservice.Domain.html
https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_opensearchservice.CfnDomain.html

while elasticsearch CfnDomain supported the cold storage enable : https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_elasticsearch.CfnDomain.html 

### Expected Behavior

Enable cold storage when Opensearch cluster created by CDK.

### Current Behavior

Not support cold storage enable when create a new opensearch cluster.

### Reproduction Steps

--

### CDK CLI Version

2.68.0

### Node.js Version

v18.4.0

### OS

Mac OS

### Language

Typescript

**Comment by pahud** [comment]
Hi

It looks like `ColdStorageOptions` is not supported for OpenSearch resources.

>If your template includes ColdStorageOptions, remove it, as it's not currently supported for OpenSearch resources.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticsearch-domain.html

I am closing this issue for now as this is not relevant to CDK.
