### ISSUE TITLE
@aws-cdk-lib/aws-rds: DatabaseCluster's .node.defaultChild is undefined when using 'fromDatabaseClusterAttributes'

### ISSUE THREAD

**Issue by malikalimoekhamedov** [aws/aws-cdk#24659]
### Describe the bug

Result returned from DatabaseCluster.fromDatabaseClusterAttributes has its attribute `.node.defaultChild` set to `undefined` and `.node.children` is `[]`.

### Expected Behavior

Just like with other constructs, it should allow for an escape hatch through `.node.defaultChild` so that it can be manually cast to `DatabaseCluster` which can later be used to infer things like this database cluster's VPC, securityGroups, secrets, etc.

Example:

```typescript
const cluster = DatabaseCluster.fromDatabaseClusterAttributes(
    this,
    'Cluster',
    { clusterIdentifier: 'cluster-identifier' }
).node.defaultChild as DatabaseCluster;
```

### Current Behavior

`.node.defaultChild` is `undefined`. `.node.children` is `[]`.

### Reproduction Steps

```typescript
const cluster = DatabaseCluster.fromDatabaseClusterAttributes(
    this,
    'Cluster',
    { clusterIdentifier: 'your-cluster-id' }
).node.defaultChild;

console.log(cluster);
```

### CDK CLI Version

2.69.0

### Node.js Version

19.8.1

### OS

MacOS Ventura 13.2.1

### Language

Typescript

### Language Version

5.0.2

**Comment by antikvarBE** [comment]
> [fromDatabaseClusterAttributes](https://github.com/aws/aws-cdk/blob/1ba85fee418fc79ccf5d5a36c12f2a83422f92e5/packages/%40aws-cdk/aws-rds/lib/cluster.ts#L651-L653) essentially returns [ImportedDatabaseCluster](https://github.com/aws/aws-cdk/blob/1ba85fee418fc79ccf5d5a36c12f2a83422f92e5/packages/%40aws-cdk/aws-rds/lib/cluster.ts#L562) that literally does not create any new database cluster resources as its child node resource. And from CFN's perspective it's a reference to an existing resource created outsides this CFN stack so it's not possible to modify the VPC, securityGroups or secrets of this imported cluster.
> 
> Let me know if it helps.

Thank you, @pahud.

I'm aware of the fact that this method returns an existing resource without creating anything. The reason I'm using it is that I need to programmatically determine what VPC, subnets and security groups my RDS cluster operates in so I can use these values while deploying a new AWS Lambda function that's supposed to communicate with it. I'm not trying to change the RDS cluster. Although, normally, I could do so once I've gotten back the result of `DatabaseCluster.fromDatabaseClusterAttributes`.

**Comment by malikalimoekhamedov** [comment]
> @malikalimoekhamedov
> 
> Please allow me to confirm your use case. Sounds like you need to import existing cluster in order to look up its VPC, subnets and security groups so you can provision a lambda function in VPC to interact with it?
> 
> However, if you look at [DatabaseClusterAttributes](https://github.com/aws/aws-cdk/blob/f2294ba5d17b31895267a672dcc7ec457cc779c7/packages/aws-cdk-lib/aws-rds/lib/cluster-ref.ts#L61) used for [fromDatabaseClusterAttributes()](https://github.com/aws/aws-cdk/blob/f2294ba5d17b31895267a672dcc7ec457cc779c7/packages/aws-cdk-lib/aws-rds/lib/cluster.ts#L652), I don't think you would be able to get the VPC info of the imported cluster. Can you explain more about it?

@pahud, you're right on the money here. That's what I'm trying to achieve. I'm writing a CDK infrastructure around certain resources that existed before I joined the project. I need to enrich it with lambda functions and other bits but I'm not allowed to recreate a database anew from my CDK project. Of course, I can find all of the values through the console and hard code them, but, I'd like my CDK code to use environment variables or lookups should I deploy into a different AWS account later on.

**Comment by pahud** [comment]
@malikalimoekhamedov 

Got it. Unfortunately the fromXxx() methods can't return everything for you to reference and you need to provide those info before you can reference it. In your use case, you probably have some options to reuse existing resources across Apps/Stacks/Accounts such as Vpc, IAM Roles, Security Groups you previously created outsides CDK:

1. define a static file such as [dotenv](https://www.npmjs.com/package/dotenv), [cdk.context.json or cdk.json](https://docs.aws.amazon.com/cdk/v2/guide/context.html) to declare those info so your new app can just look up from env vars or context vars and import them with `fromXxx()` methods. 
2. store those information in SSM parameter store and share between CDK apps or stacks.

I hope you find it useful.

**Comment by dennisvang** [comment]
A similar issue arises trying to get the default security group from the default vpc:

```typescript
const defaultVpc = ec2.Vpc.fromLookup(this, 'DefaultVPC', {isDefault: true});
const cfnVpc = defaultVpc.node.defaultChild as ec2.CfnVPC;
const defaultVpcSecurityGroup = cfnVpc.attrDefaultSecurityGroup;
```
results in 

>TypeError: Cannot read properties of undefined (reading 'attrDefaultSecurityGroup')


Perhaps something like [this][1] could help?

[1]: https://github.com/aws/aws-cdk/issues/10282#issuecomment-778177319
