### ISSUE TITLE
aws-cdk-lib/aws-secretsmanager: Secret already exists in another stack

### ISSUE THREAD

**Issue by lhincapie0** [aws/aws-cdk#24657]
### Describe the bug

We are trying to deploy new stacks with aws-cdk referencing a secret to attach credentials to an RDS instance and we are getting the following error (only happens with new stacks):

`❌  Error: The stack named new_stack_name failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: arn:aws:secretsmanager:us-east-2:<*****accountd_id*****>:secret:<*****secret_arn*****> already exists in stack arn:aws:cloudformation:us-east-2:<*****accountd_id*****>:stack/<*****existing_stack_name*****>/<*****existing_stack_id*****>
`

This error started happening one month ago without any changes from our side, before this we were able to deploy the same infrastructure for existing and new stacks.

The following code is getting the secret from secrets manager and attaching this secret to the RDS instance:

```
const dbCredentials = secretsmanager.Secret.fromSecretNameV2(stack, 'DBSecret', 'secret-name');

 const database = new rds.DatabaseInstance(stack, 'database-name', {
        credentials: rds.Credentials.fromSecret(dbCredentials),
        removalPolicy: RemovalPolicy.RETAIN,
        engine: rds.DatabaseInstanceEngine.postgres({ version: postgresVersion })
        ... 
    }
});
```

### Expected Behavior

The database and secret attachment is created successfully

### Current Behavior

The deployment of a new stack fails when it tries to create the Secret Attachment for the RDS instance
```
stack-name | 41/44 | 10:56:06 PM | CREATE_FAILED        | AWS::SecretsManager::SecretTargetAttachment | project-name/DBSecret/Attachment (DBSecretAttachmentC565A14F) arn:aws:secretsmanager:us-east-2:<*****accountd_id*****>:secret:<*****secret_arn*****> already exists in stack arn:aws:cloudformation:us-east-2:<*****accountd_id*****>:stack/<*****existing_stack_name*****>/<*****existing_stack_id*****>
```

### Reproduction Steps

Described above.

### Possible Solution

I tried to follow the steps described in https://github.com/aws/aws-cdk/issues/24383 but its still happening

### CDK CLI Version

2.67.0

### Node.js Version

16.0

### OS

Ubuntu

### Language

Typescript

**Comment by pahud** [comment]
Hi

Where is the `credentials` defined in `rds.Credentials.fromSecret(credentials),` ?

Can you share more details?

```ts
const dbCredentials = secretsmanager.Secret.fromSecretNameV2(stack, 'DBSecret', 'secret-name');

 const database = new rds.DatabaseInstance(stack, 'database-name', {
        credentials: rds.Credentials.fromSecret(credentials),
        removalPolicy: RemovalPolicy.RETAIN,
        engine: rds.DatabaseInstanceEngine.postgres({ version: postgresVersion })
        ... 
    }
});
```

**Comment by lhincapie0** [comment]
@pahud sorry, I just modified the description, its the one being retrieved from secrets manager:

```
const dbCredentials = secretsmanager.Secret.fromSecretNameV2(stack, 'DBSecret', 'secret-name');

 const database = new rds.DatabaseInstance(stack, 'database-name', {
        credentials: rds.Credentials.fromSecret(dbCredentials),
        removalPolicy: RemovalPolicy.RETAIN,
        engine: rds.DatabaseInstanceEngine.postgres({ version: postgresVersion })
        ... 
    }
});
```

**Comment by lhincapie0** [comment]
Any updates?
