### ISSUE TITLE
(ecs): (replace instnaceOf with isBottleRocketImage)

### ISSUE THREAD

**Issue by bun913** [aws/aws-cdk#24692]
### Describe the feature

I create `Role.isRole()` method at #24340 (https://github.com/aws/aws-cdk/pull/24340#discussion_r1120780639)

That's is for strict type check for `iam.Role` class.

I'll create `ecs.BottleRocketImage` type check like above.

```ts
export class BottleRocketImage implements ec2.IMachineImage {
  /**
   * Return whether the given object is a BottleRocketImage
   */
  public static isBottleRocketImage(x: any): x is BottleRocketImage {
    return x !== null && typeof x === 'object' && BR_IMAGE_SYMBOL in x;
  }

```

Fix the code that uses instanceOf as follows

https://github.com/aws/aws-cdk/blob/e8158af34eb6402c79edbc171746fb5501775c68/packages/%40aws-cdk/aws-ecs/lib/cluster.ts#L1292

### Use Case

Since instanceOf is not a product to be used for strict type determination, it is better to replace it.

fyi: https://github.com/aws/aws-cdk/pull/20564/files#diff-fe41afc44afd9acb16980754990f93acb596ed37662296575ea2fbe1c5531b50R203-R206

### Proposed Solution

I'll create isBottleRocketImage() method like below.

```ts
export class BottleRocketImage implements ec2.IMachineImage {
  /**
   * Return whether the given object is a BottleRocketImage
   */
  public static isBottleRocketImage(x: any): x is BottleRocketImage {
    return x !== null && typeof x === 'object' && BR_IMAGE_SYMBOL in x;
  }
}

Object.defineProperty(BottleRocketImage.prototype, BR_IMAGE_SYMBOL, {
  value: true,
  enumerable: false,
  writable: false,
});
```

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.69.0

### Environment details (OS name and version, etc.)

macOS Monterey

**Comment by pahud** [comment]
Thank you for the PR contribution!!
