### ISSUE TITLE
‼️ NOTICE: @aws-cdk/assert no longer published after 2.68.0

### ISSUE THREAD

**Issue by rix0rrr** [aws/aws-cdk#24701]
## Context

The [@aws-cdk/assert](https://www.npmjs.com/package/@aws-cdk/assert) library was deprecated in April 2021, and has not received any updates for the last 2 years.

Its replacement is [@aws-cdk/assertions](https://docs.aws.amazon.com/cdk/api/v1/docs/assertions-readme.html) (v1) and [aws-cdk-lib.assertions](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.assertions-readme.html) (v2). 

## The change

The replacement `assertions` library has been in CDK v2 from the day it was released. We did not intend to keep on publishing `@aws-cdk/assert` under the `2.x.x` version line, but we did so anyway up until version `2.68.0`. Despite the weekly release, there have been no functional changes in `@aws-cdk/assert` for the last 2 years, and there never will be.

We have now stopped releasing versions of `@aws-cdk/assert`. Version 2.68.0 will be the last release of that package.

## What does this mean for me?

You can keep on using version 2.68.0 of `@aws-cdk/assert` if you want. CDKv2 does not have the requirement anymore that all packages are on the exact same version. Therefore, it would be perfectly fine to combine (hypothetically)  `aws-cdk-lib@2.123.0` with `@aws-cdk/assert@2.68.0`.

If you do so, be aware that this package will not see further development. Its official replacement is `aws-cdk-lib.assertions`.

**Comment by MrArnoldPalmer** [comment]
Closing this out since its been up almost a month.
