### ISSUE TITLE
aws_iam: add_to_policy missing on a Role obtained via Role.from_role_arn() 

### ISSUE THREAD

**Issue by memleak00** [aws/aws-cdk#24738]
### Describe the bug

Trying to migrate CDK v1 code to CDK v2.

There is a failure in invoking "add_to_policy" on a Role obtained via Role.from_role_arn()  

 ```
   inst_role.add_to_policy(
  File "..../python3.9/site-packages/jsii/_reference_map.py", line 153, in __getattr__
    raise AttributeError(f"'%s' object has no attribute '%s'" % (type_info, name))
AttributeError: '<class 'aws_cdk.Resource'>+<class 'aws_cdk.aws_iam._IRoleProxy'>' object has no attribute 'add_to_policy'
```

### Expected Behavior

The function add_to_policy should not fail.

### Current Behavior

Fails with AttributeError.

### Reproduction Steps

1) role = Role.from_role_arn()
2) role.add_to_policy( .... )

### CDK CLI Version

2.69.0

### Node.js Version

v18.15.0

### OS

Linux

### Language

Python

### Language Version

Python (3.9.13)

**Comment by pahud** [comment]
[addToPolicy](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-iam.IRole.html#addwbrtowbrpolicystatementspan-classapi-icon-api-icon-deprecated-titlethis-api-element-is-deprecated-its-use-is-not-recommended%EF%B8%8Fspan) was depreciated and you should use [addToPrincipalPolicy](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-iam.IRole.html#addwbrtowbrprincipalwbrpolicystatement) instead.

**Comment by memleak00** [comment]
Thank you. I am now able to move past the issue.

I was going off this documentation: https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_iam/Role.html#role. In our migration exercise from v1 to v2 we hit a few other cases of missing (removed) APIs, but in those cases, the documentation had no reference to the removed APIs. Is there a list of all the deprecated/removed APIs that could be referenced?
