### ISSUE TITLE
Amazon.CDK.Assertions: Build warning

### ISSUE THREAD

**Issue by patricm-enbw** [aws/aws-cdk#24742]
### Describe the bug

I´ve created a new .NET CDK project plus a test project using Amazon.CDK.Assertions using the most recent versions for everything.

### Expected Behavior

It builds without warnings.

### Current Behavior

Build warning:

Warning NU1608 Detected package version outside of dependency constraint: Amazon.CDK.Assertions 1.197.0 requires Constructs (>= 3.3.69 && < 4.0.0) but version Constructs 10.1.279 was resolved. xxx.Tests C:\xxx\xxx\xxx\xxx.csproj 1

### Reproduction Steps

n/a

### Additional Information/Context

I´m unsure if this really means I should use Constructs (>= 3.3.69 && < 4.0.0) 

### CDK CLI Version

2.69.0 (build 60a5b2a)

### Framework Version

6

### Node.js Version

v16.191.1

### OS

Windows

### Language

.NET

### Language Version

c# 11

**Comment by pahud** [comment]
Amazon.CDK.Assertions 1.197.0 is the CDK v1 version which requires Constructs (>= 3.3.69 && < 4.0.0). As I can't see more details I doubt you probably have installed some v1 packages. You probably need to check if your project is created with CDK v2 CLI.

And may find more info at [Working with the AWS CDK in C#](https://docs.aws.amazon.com/cdk/v2/guide/work-with-cdk-csharp.html).

**Comment by patricm-enbw** [comment]
Thanks... it looks like a 2.xx version of Amazon.CDK.Assertions was never released. Or it least it´s not availabile via nuget (see https://www.nuget.org/packages/Amazon.CDK.Assertions) ... 

But it´s mentioned in the v2 guide (link you also sent me -> testing) under c# snippets (https://docs.aws.amazon.com/cdk/v2/guide/testing.html)

That´s what confused me.

**Comment by pahud** [comment]
@patricm-enbw 

I believe CDK v2 for Nuget is at https://www.nuget.org/packages/Amazon.CDK.Lib
