### ISSUE TITLE
CDK v2 migration: CDK v2 migration issue with feature flag disabling

### ISSUE THREAD

**Issue by priyashri2** [aws/aws-cdk#24748]
### Describe the bug

We recently tried updating CDK V1 to V2 and it changed one load balancer export value which is being used in other stacks.  This resulted in failure during deployment with error -
```Export ExportsOutputRefServiceFargateServiceLBPublicListenerEA8C5A0AB6690587 cannot be deleted as it is in use by monitoring stack```

CDK diff shows export name change -

```
Outputs
[-] Output ExportsOutputRefServiceFargateServiceLBPublicListenerEA8C5A0AB6690587: {"Value":{"Ref":"ServiceFargateServiceLBPublicListenerEA8C5A0A"},"Export":{"Name":"ExportsOutputRefServiceFargateServiceLBPublicListenerEA8C5A0AB6690587"}}

[+] Output Exports/Output{"Fn::GetAtt":["ServiceFargateServiceLB720D70F0","LoadBalancerFullName"]} ExportsOutputFnGetAttServiceFargateServiceLB720D70F0LoadBalancerFullName764D3C3D: {"Value":{"Fn::GetAtt":["ServiceFargateServiceLB720D70F0","LoadBalancerFullName"]},"Export":{"Name":":ExportsOutputFnGetAttServiceFargateServiceLB720D70F0LoadBalancerFullName764D3C3D"}}


```

As per CDK migration guideline and some sage posts , We made changes to add ```"@aws-cdk/core:stackRelativeExports": false``` in the ```cdk.context.json```  , but the diff is still shown in export value.
This is blocking the CDK update as it's not easy for us to remove the stack dependency.

We haven't made any change which can cause the export name change.

Can you help us with why this feature `@aws-cdk/core:stackRelativeExports` is not working in v2 upgrade ?

Is there any way to check if this feature is getting executed or not ?

### Expected Behavior

No diff should be shown in cdk diff for export name change after adding this flag -

```"@aws-cdk/core:stackRelativeExports": false```

### Current Behavior

Load balancer reference is getting changed. CDK diff shows the export output change.

### Reproduction Steps

TBD

### CDK CLI Version

v2

### Node.js Version

14

### OS

13.2.1 (22D68)

### Language

Typescript

**Comment by khushail** [comment]
Hi @priyashri2 , thanks for reaching out. This issue being tracked through internal ticket, so closing this issue.

**Comment by khushail** [comment]
Closing it as customer is guided through ticket.
