### ISSUE TITLE
glue: glue connections to be assigned to glue tables

### ISSUE THREAD

**Issue by Rizxcviii** [aws/aws-cdk#24741]
### Describe the feature

When creating a table, you are able to add an additional parameter to the Table properties called `connectionName` which will allow developers to assign a Glue Data Connection to the `Connection` property.
There should be a field to allow you to directly manipulate the `connectionName` property. In addition, there could potentially be a need to allow direct access of the `location` property, as crawlers tend to change the location property, if crawling a third party database.

### Use Case

Databases that contain structured data, that may never change (or change very rarely) would not need the use of a crawler to update the schema. This could be good in reducing cost of the end user.
In addition, when running glue jobs, developers can directly use the table, as this will also contain the connection needed.

### Proposed Solution

- Add a `connection` property that could potentially take an existing glue connection, or it's associating connection name.
- Allow dynamic changing of the `location` name, if the glue data source does not reside in S3. This could either be a separate feature request, or could be included here.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.68.0

### Environment details (OS name and version, etc.)

Amazon Linux 2

**Comment by pahud** [comment]
Thanks for the use case and this seems to be a useful feature. Feel free to submit your PR when it's ready. Thanks!
