### ISSUE TITLE
cdk ls err's out trying to find dll

### ISSUE THREAD

**Issue by unicomp21** [aws/aws-cdk#2474]
**Describe the bug**
jdavis@DESKTOP-GCP4E2T:/mnt/c/Users/unico/Documents/repo/dev/cdk-tests$ cdk ls
Error:
  An assembly specified in the application dependencies manifest (HelloCdk.deps.json) was not found:
    package: 'Amazon.CDK.AWS.ApplicationAutoScaling', version: '0.30.0'
    path: 'lib/netstandard2.0/Amazon.CDK.AWS.ApplicationAutoScaling.dll'
Subprocess exited with error 140

**To Reproduce**
code for repro is located here:
https://github.com/unicomp21/cdk-tests/commit/cf266686744fab17d7ba6689803b08bd30343c3e

**Expected behavior**
I shouldn't be getting an error, right?

**Version:**
 - Linux on Windows Subsystem, ubuntu, win10
 - C#
 - 30

**Comment by eladb** [comment]
Is this module defined as a dependency of your project? Did you remember to `dotnet build src`?

**Comment by unicomp21** [comment]
yes, and yes

**Comment by SomayaB** [comment]
Hi @unicomp21, sorry for the late reply. Are you still experiencing this issue?

**Comment by SomayaB** [comment]
Closing this issue since there hasn't been activity on it in a while. Feel free to reopen.
