### ISSUE TITLE
TransitGatewayAttachment: AWS::EC2::TransitGatewayAttachment ApplianceModeSupport options are named "applianceModeSupport"

### ISSUE THREAD

**Issue by JPLemelin** [aws/aws-cdk#24754]
### Describe the bug

After upgrading from **2.56.0** to **2.56.1**, the CloudFormation attribute "ApplianceModeSupport" was rename with a lower case

Sample of construct usage:
```ts
const transitGatewayAttachmentVpc = new ec2.CfnTransitGatewayAttachment(this, 'tgw-att-vpc', {
  transitGatewayId: transitGateway.ref,
  vpcId: vpc.vpcId,
  subnetIds: vpc.selectSubnets({subnetGroupName: 'tgw-subnet'}).subnetIds,
  options: {
    applianceModeSupport: 'enable',
  },
}
```

Diff after upgrading
```
[~] AWS::EC2::TransitGatewayAttachment tgw-att-vpc tgwattvpc 
 └─ [~] Options
     ├─ [-] Removed: .ApplianceModeSupport
     └─ [+] Added: .applianceModeSupport
```

### Expected Behavior

Cloudformation generated should be named accourding to the doc: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-transitgatewayvpcattachment-options.html#cfn-ec2-transitgatewayvpcattachment-options-appliancemodesupport

### Current Behavior

The stack failed to deploy

```
The stack named hub-network failed to deploy: UPDATE_ROLLBACK_COMPLETE: Properties validation failed for resource tgwattvpc with message:
#/Options: extraneous key [applianceModeSupport] is not permitted
```

### Reproduction Steps

Just execute `cdk deploy` cmd

### CDK CLI Version

2.56.1

### Node.js Version

16

### OS

MacOs 

### Language

Typescript

**Comment by peterwoodworth** [comment]
This is the same cause as the other issues I've named in [this comment](https://github.com/aws/aws-cdk/issues/21767#issuecomment-1433881046). tl;dr we got stuck between a rock and a hard place regarding typing of resources cfnspec changed. Going forward we're looking how to prevent this from happening again. In the meantime, you'll need to define the properties with capital letters
