### ISSUE TITLE
(cloudfront-origins): originAccessIdentity not applied for existing bucket

### ISSUE THREAD

**Issue by iRoachie** [aws/aws-cdk#24763]
### Describe the bug

I have a stack where it's using an S3 bucket from another stack via `Bucket.fromBucketName`.

I created my own origin access identity and added the bucket policy via:
```ts
new BucketPolicy(this, 'bucket-policy', {
  bucket: myBucket,
}).document.addStatements(
  new PolicyStatement({
    actions: ['s3:GetObject'],
    resources: [myBucket.arnForObjects('*')],
    principals: [oai.grantPrincipal],
  })
);
 ```
 
When creating the distribution, the stack deploys, but the oai is not associated with my origin.

```ts
new Distribution(this, 'my-cdn', {
  defaultBehavior: {
    origin: new S3Origin(myBucket, {
      originAccessIdentity: oai,
    }),
  },
});

```

### Expected Behavior

The oai should be associated with the origin.

### Current Behavior

A new oai instead is being created by `S3Origin` even though I've provided one https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/aws-cloudfront-origins/lib/s3-origin.ts#L60

### Reproduction Steps

- Create a bucket through console or another cdk stack
- Create oai and distribution in the above steps

### CDK CLI Version

2.70.0

### Framework Version

2.70.0

### Node.js Version

v18.12.1

### OS

Mac

### Language

Typescript

### Language Version

4.9.5

### Other information

I've already checked issues like https://github.com/aws/aws-cdk/issues/22451 but my bucket is not configured as a website

**Comment by outcast292** [comment]
I've same issue with   `IBucket.grantRead` , the OAI  does not get added to the bucket policies .

# How to reproduce

* I get a bucket from `Bucket.fromBucketArn` , it returns an `IBucket` interface
* IBucket.grantRead(OAI) 

# Expected Behavior 
  
Bucket Should be accessible via the OAI  in the cloudfront distribution 

# Current Behavior

Bucket policies do not get updated at all .

## CDK version

2.68.0 - 2.70.0

**Comment by iRoachie** [comment]
Closing this, issue came from external source (trustedKeyGroups)
