### ISSUE TITLE
(aws-s3): (cdk calls DeleteBucketPolicy and PutBucketNotification at the same time causes an  conflicting operation error.)

### ISSUE THREAD

**Issue by hulu-xu** [aws/aws-cdk#24762]
### Describe the bug

We often get these occasional errors in our smoke tests deployed by aws cdk.
![image](https://user-images.githubusercontent.com/26135307/227139929-53185803-e985-4717-8a7f-3975eb42dda9.png)
![image](https://user-images.githubusercontent.com/26135307/227140059-9540559c-c9a1-42aa-9af0-9abb470b0835.png)
![image](https://user-images.githubusercontent.com/26135307/227144997-c96a1d30-1a5f-4437-b41d-a7de8aefef11.png)

By digging through the event logs in cloudtrail, we found that if cdk calls DeleteBucketPolicy and PutBucketNotification at the same time. One of these operations will raise an error for a conflicting operation.
![image](https://user-images.githubusercontent.com/26135307/227141378-cdc1db6e-6dea-41c3-bfa3-ca40f776e2e4.png)
![image](https://user-images.githubusercontent.com/26135307/227141660-8b172ca5-2db1-403e-b4b4-b95bb3e1bf0d.png)

### Expected Behavior

The operations on the bucket can be performed in sequence.
![image](https://user-images.githubusercontent.com/26135307/227142004-7b355af3-4ed4-4196-8697-9e5aa779a992.png)

### Current Behavior

cdk calls DeleteBucketPolicy and PutBucketNotification at the same time causes an  conflicting operation error.

### Reproduction Steps

This error is uncontrollable. It is sometimes absent and sometimes too frequent.  It always occurs when deleting a bucket stack with a bucket policy and bucket notifications.

### CDK CLI Version

2.59.0

### Node.js Version

16

### OS

linux

### Language

Python

### Language Version

3.10

**Comment by hulu-xu** [comment]
Hi @peterwoodworth , we use both of these methods to add configurations to the bucket and then deploy it via `cdk deploy`. When running `cdk destroy`, a conflicts operation error sometimes occur. 
https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_s3/IBucket.html#aws_cdk.aws_s3.IBucket.add_event_notification
https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_s3/IBucket.html#aws_cdk.aws_s3.IBucket.add_to_resource_policy

**Comment by hulu-xu** [comment]
same issue [16811](https://github.com/aws/aws-cdk/issues/16811)

**Comment by peterwoodworth** [comment]
It looks like we can close this as a duplicate then 🙂  Thanks for reporting
