### ISSUE TITLE
RestApi - CDK thinks the API has no method and throws error

### ISSUE THREAD

**Issue by lucioFlores** [aws/aws-cdk#24772]
### Describe the bug

``I'm creating stack with a RestAPI, adding a single method, and deploying a 'dev' stage. I get the following error:

> Cannot determine deployment stage for API from "deploymentStage". Use "deploy" or explicitly set "deploymentStage"
/home/lucio/dev/cdk/Queue/node_modules/aws-cdk-lib/core/lib/private/synthesis.js:2
  `);throw new Error(`Validation failed with the following errors:
           ^
Error: Validation failed with the following errors:
  [QueueStack/api/Queue] The REST API doesn't contain any methods
    at validateTree (/home/lucio/dev/cdk/Queue/node_modules/aws-cdk-lib/core/lib/private/synthesis.js:2:12)

Here is the code:
```
  this.api = new apigw.RestApi(this, "Queue", {
      deploy: false,
      endpointTypes: [apigw.EndpointType.PRIVATE],
    });
    this.url = this.api.url;

    const createItem = this.api.root.addResource('createItem');
    createItem.addMethod('GET', this.createIntegration('createItem', devTable, prodTable));

    // Deployment
    const deployment = new apigw.Deployment(this, 'dev-deployment', {
      api: this.api,
    })

    const dev_stage = new apigw.Stage(this, "dev-stage", {
      deployment,
      stageName: 'dev',
    }

    this.api.deploymentStage = dev_stage;

  createIntegration = (id: string, devTable: dynamodb.ITable, prodTable: dynamodb.ITable): apigw.LambdaIntegration => {
    const func = new lambda.Function(this, id + "Handler", {
      runtime: lambda.Runtime.NODEJS_14_X,
      code: lambda.Code.fromAsset("lambda"),
      handler: 'src/' + id + '.handler',
      environment: {
        DEV_TABLE_NAME: devTable.tableName,
        PROD_TABLE_NAME: prodTable.tableName,
      }
    });
    devTable.grantReadWriteData(func);
    prodTable.grantReadWriteData(func);
    return new apigw.LambdaIntegration(func);
  }

```

### Expected Behavior

'cdk synth' should just work

### Current Behavior

cdk synth throws an error:

> Cannot determine deployment stage for API from "deploymentStage". Use "deploy" or explicitly set "deploymentStage"
/home/lucio/dev/cdk/Queue/node_modules/aws-cdk-lib/core/lib/private/synthesis.js:2
  `);throw new Error(`Validation failed with the following errors:
           ^
Error: Validation failed with the following errors:
  [QueueStack/api/Queue] The REST API doesn't contain any methods
    at validateTree (/home/lucio/dev/cdk/Queue/node_modules/aws-cdk-lib/core/lib/private/synthesis.js:2:12)
    at Object.synthesize (/home/lucio/dev/cdk/Queue/node_modules/aws-cdk-lib/core/lib/private/synthesis.js:1:647)
    at App.synth (/home/lucio/dev/cdk/Queue/node_modules/aws-cdk-lib/core/lib/stage.js:1:1922)
    at process.<anonymous> (/home/lucio/dev/cdk/Queue/node_modules/aws-cdk-lib/core/lib/app.js:1:1355)
    at Object.onceWrapper (events.js:520:26)
    at process.emit (events.js:400:28)
    at process.emit (domain.js:475:12)
    at process.emit.sharedData.processEmitHook.installedValue [as emit] (/home/lucio/dev/cdk/Queue/node_modules/@cspotcode/source-map-support/source-map-support.js:745:40)

### Reproduction Steps

import {Construct} from "constructs";
import * as dynamodb from 'aws-cdk-lib/aws-dynamodb';
import * as apigw from "aws-cdk-lib/aws-apigateway";
import * as lambda from 'aws-cdk-lib/aws-lambda';
import {ITable} from "aws-cdk-lib/aws-dynamodb/lib/table";

export interface ApiProps {
  devTable: string,
  prodTable: string,
}

export class QueueApi extends Construct {

  public readonly url: string;
  private props: ApiProps;
  private api: apigw.RestApi;

  constructor(scope: Construct, id: string, props: ApiProps) {
    super(scope, id);

    this.props = props;

    const devTable = dynamodb.Table.fromTableName(this, 'dev-table', props.devTable);
    const prodTable = dynamodb.Table.fromTableName(this, 'prod-table', props.prodTable);

    this.api = new apigw.RestApi(this, "Queue", {
      deploy: false,
      endpointTypes: [apigw.EndpointType.PRIVATE],
    });
    this.url = this.api.url;

    const createItem = this.api.root.addResource('createItem');
    createItem.addMethod('GET', this.createIntegration('createItem', devTable, prodTable));

    // Deployment
    const deployment = new apigw.Deployment(this, 'dev-deployment', {
      api: this.api,
    })

    const dev_stage = new apigw.Stage(this, "dev-stage", {
      deployment,
      stageName: 'dev',
    });

    this.api.deploymentStage = dev_stage;
  }

  createIntegration = (id: string, devTable: dynamodb.ITable, prodTable: dynamodb.ITable): apigw.LambdaIntegration => {
    const func = new lambda.Function(this, id + "Handler", {
      runtime: lambda.Runtime.NODEJS_14_X,
      code: lambda.Code.fromAsset("lambda"),
      handler: 'src/' + id + '.handler',
      environment: {
        DEV_TABLE_NAME: devTable.tableName,
        PROD_TABLE_NAME: prodTable.tableName,
      }
    });
    devTable.grantReadWriteData(func);
    prodTable.grantReadWriteData(func);
    return new apigw.LambdaIntegration(func);
  }

}

### CDK CLI Version

2.69.0 (build 60a5b2a)

### Node.js Version

v14.21.2

### OS

Linux owner 5.15.0-60-generic #66~20.04.1-Ubuntu SMP Wed Jan 25 09:41:30 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Language

Typescript

**Comment by peterwoodworth** [comment]
You cannot reference `RestApi.url` until a deploymentStage has been attached to the RestApi. Since you're attempting to associate the deploymentsStage with the RestApi _after_ trying to reference the url, this is throwing an error. It doesn't look like moving this url reference to after the deploymentStage will change anything in your app based on what you've provided, so that's likely all you will need to do here.

**Comment by lucioFlores** [comment]
That worked, much thanks!!! Should definitely amend the construct docs to have people refer to the url property AFTER the deployment.
