### ISSUE TITLE
aws-cdk-lib/aws-s3: Unable to add necessary logging permissions to imported target bucket

### ISSUE THREAD

**Issue by timfulmer** [aws/aws-cdk#24771]
### Describe the bug

Running `cdk deploy` on a stack which creates an s3 bucket, configured with s3 access logging to another bucket created outside the stack, gives a spurious warning, even though s3 access logging is setup correctly.

### Expected Behavior

The `cdk deploy` command completes without warning, since s3 access logging permissions are setup correctly and s3 access logging is confirmed to be working.

### Current Behavior

A warning is given that s3 access logging permissions are not setup correctly, even though s3 access logging is observed to be working successfully.

### Reproduction Steps

PRECONDITIONS:
1. An s3 bucket for access logs is created outside the CDK stack, i.e. through AWS Console
2. The access logs s3 bucket is configured with "ACLs enabled", "Object writer"
3. Defaults are used for the rest of the s3 bucket configuration
4. After creating the access logs bucket, edit the ACLs, for "S3 log delivery group", select Objects Write and Bucket ACL Read
5. Create an innocuous test file on your local machine like this: `echo "Testing one, two .." > ~/Desktop/test.txt`

REPRO:
1. Initialize a new Typescript CDK project
2. Add the following to the stack:

```
    const serverAccessLogsBucket = Bucket.fromBucketName(
      scope,
      `s3-access-logging`,
      'tfulmer-mock-access-logs',
    );

    new Bucket(scope, 's3-logged-bucket', {
      bucketName: 's3-logged-bucket',
      accessControl: BucketAccessControl.PRIVATE,
      blockPublicAccess: BlockPublicAccess.BLOCK_ALL,
      serverAccessLogsBucket,
    });
```

3. Check `cdk.json`, make sure it contains `"@aws-cdk/aws-s3:serverAccessLogsUseBucketPolicy": true`
6. Run `cdk synth`
7. Note the warning given: `Warning at /S3LoggingWarningStack/s3-logged-bucket] Unable to add necessary logging permissions to imported target bucket: S3LoggingWarningStack/s3-access-logging`
8. Run `cdk deploy`
9. Wait for up to an hour for the access logging config to be applied
10. Upload your innocuous test file to the `s3-access-logging` bucket created in s3
11. Download the innocuous test file to local through the AWS Console a few times to trigger access logs
12. Wait for up to an hour for access logs to populate in the access logging bucket
13. Confirm access logs accurately reflect the actions taken on the logged bucket

### CDK CLI Version

2.70.0

### Node.js Version

16.17.0

### OS

OSX

### Language

Typescript

### Language Version

4.9.5

**Comment by peterwoodworth** [comment]
You can view [this PR](https://github.com/aws/aws-cdk/pull/23552) and the associated issues to see why we implemented this warning

We have a feature request [here](https://github.com/aws/aws-cdk/issues/23403) for suppressing warning messages you'd prefer to not see 🙂
