### ISSUE TITLE
AWS CodePipeline: Ability to get or set the bucket name to an CodePipeline Artifact

### ISSUE THREAD

**Issue by darko-mesaros** [aws/aws-cdk#24784]
### Describe the feature

Ability to use existing bucket or set a name for the bucket created by an AWS CodePipeline Artifact. Or, at the very least have the possibility of getting the bucket name of the created Artifact.

### Use Case

I need to be able to get the name or object of the Artifact bucket created by CDK for AWS CodePipeline. The reason I need this, is I need to grant permission to an EC2 Instance, that is using CodeDeploy access to ONLY ONE bucket, instead of all buckets. And to be able to do so, I need to be able to programmatically deduce the S3 bucket name. 

Here is the example code I tried to use:
```typescript
...
const webServerRole = new Role(this, "ec2Role", {
      assumedBy: new ServicePrincipal("ec2.amazonaws.com"),
});

// Source action
const sourceOutput = new Artifact();

// fix some CodeDeploy permissions
const sourceBucket = Bucket.fromBucketName(this, 'sourceBucket',
      sourceOutput.bucketName
)
// Give permission to this specific bucket
    sourceBucket.grantRead(webServerRole)
...

```

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.69.0

### Environment details (OS name and version, etc.)

Linux x86

**Comment by pahud** [comment]
Hi @darko-mesaros 

I believe you can access [bucketname](https://github.com/aws/aws-cdk/blob/9d4b66a437a1ce2518d46764fe53c7d699576d6a/packages/%40aws-cdk/aws-codepipeline/lib/artifact.ts#L44) from the Artifacts. Can you share more cdk code snippets about what your pipeline looks like and why you believe it's not possible to access the bucket name?
