### ISSUE TITLE
AWS AppSync: add EventBridge as L2 datasource

### ISSUE THREAD

**Issue by mtliendo** [aws/aws-cdk#24809]
### Describe the feature

This feature adds eventBridge as an L2 construct following the release of the [L1 construct](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_appsync.CfnDataSource.EventBridgeConfigProperty.html)

### Use Case

Customers should have an easy way to add EventBridge as a datasource alongside the current L2 datasource options.

### Proposed Solution

```ts
// datasource.ts
/**
 * Properties for an AppSync EventBridge datasource
 */
export interface EventBridgeDataSourceProps extends BackedDataSourceProps {
	/**
	 * The EventBridge function to call to interact with this data source
	 */
	readonly eventBridgeBus: IEventBus
}

/**
 * An AppSync datasource backed by a EventBridge function
 */
export class EventBridgeDataSource extends BackedDataSource {
	constructor(scope: Construct, id: string, props: EventBridgeDataSourceProps) {
		super(scope, id, props, {
			type: 'AWS_EVENTBRIDGE',
			eventBridgeConfig: {
				eventBridgeBusArn: props.eventBridgeBus.eventBusArn,
			},
		})
		props.eventBridgeBus.grantInvoke(this)
	}
}
```

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

0.00.0

### Environment details (OS name and version, etc.)

mac m1 mbp

**Comment by pahud** [comment]
Thank you @mtliendo. I believe the core team will review your PR soon.
