### ISSUE TITLE
aws-eks: KubectlProvider fails to create/update in govcloud

### ISSUE THREAD

**Issue by wongma7** [aws/aws-cdk#24808]
### Describe the bug

In govcloud (aws-us-gov partition), "[Amazon ECR public registries](https://docs.aws.amazon.com/AmazonECR/latest/public/public-registries.html) aren't supported." https://docs.aws.amazon.com/govcloud-us/latest/UserGuide/govcloud-ecr.html

The managed policy "AmazonElasticContainerRegistryPublicReadOnly" does not exist there.

https://github.com/aws/aws-cdk/pull/24104 added this managed policy "AmazonElasticContainerRegistryPublicReadOnly" and now KubectlProvider HandlerServiceRole fails to create/update.

### Expected Behavior

KubectlProvider HandlerServiceRole successfully creates/updates in govcloud same as in other AWS partitions

### Current Behavior

KubectlProvider HandlerServiceRole fails to create/update in govcloud

### Reproduction Steps

Create a 1.25 EKS cluster in govcloud*
```
const cluster = new eks.Cluster(this, 'hello-eks', {
  version: eks.KubernetesVersion.V1_25,
});
```

### Possible Solution

Wrap this:
```
    // For OCI helm chart public ECR authorization.
    this.handlerRole.addManagedPolicy(
      iam.ManagedPolicy.fromAwsManagedPolicyName('AmazonElasticContainerRegistryPublicReadOnly'),
    );
```
in a partition check

### CDK CLI Version

~~2.27.0 (build 8e89048)~~

    "aws-cdk": "^2.69.0",

### Framework Version

    "aws-cdk": "^2.69.0",

### Node.js Version

v18.14.0

### OS

linux

### Language

Typescript

**Comment by pahud** [comment]
closed by https://github.com/aws/aws-cdk/pull/25215
