### ISSUE TITLE
cli: synthesizes all stacks

### ISSUE THREAD

**Issue by YuriGal** [aws/aws-cdk#24826]
### Describe the bug

I have several stacks in my application. If I try to synthesize only specific ones e.g.
```
cdk synth "my-stack"
```
or by pattern 
```
cdk synth "my*"
```
or even
```
cdk synth "stack-that-doesnt-exist"
```
And then check `cdk.out` folder - I see templates synthesized for all stacks in the application.

### Expected Behavior

Only stacks specified in `cdk synth` command parameters should produce CloudFormation template in `cdk.out` directory.

### Current Behavior

Templates for all stacks in the application are being synthesized.

### Reproduction Steps

Have a CDK application that instantiate  several stacks, e.g. Stack1, Stack2, Stack3. Run `cdk synth Stack1`. Look into `cdk.out` folder - you will see templates synthesized for all 3 stacks.

### CDK CLI Version

2.69.0 (build 60a5b2a)

### Node.js Version

v16.19.1

### OS

MacOS 13.2.1 (22D68)

### Language

Typescript

**Comment by peterwoodworth** [comment]
This is how it's supposed to work 🙂. The [app lifecycle documentation](https://docs.aws.amazon.com/cdk/v2/guide/apps.html#lifecycle) describes in more detail what happens when you synth.

Our docs on invoking the `cdk synth` command do seem to be inaccurate when considering this behavior, we should adjust them both in our CLI help command and in our devguide. Thanks for reporting!

**Comment by YuriGal** [comment]
Yep, I definitely expected the `synth` command only synthesize stacks I specified as parameters, but it makes sense it would synthesize everything and parameters only serve as filters.

I found a workaround though, I can have several different entry points and target them with the `synth` command to produce different stacks.

**Comment by YuriGal** [comment]
I found a possible workaround https://codecorner.galanter.net/2023/03/30/synthesize-only-stacks-you-need-in-cdk/
