### ISSUE TITLE
monocdk/aws-ecs: Container Insights enabled in cdk but show up as default in ECS console with no CI metrics 

### ISSUE THREAD

**Issue by ruiqizzzz** [aws/aws-cdk#24835]
### Describe the bug

We use eploy some ECS clusters to run our services, the setup is the same everywhere, but we're seeing different setup of ContainerInsights on the clusters in KIX (ap-northeast-3)

```ts
const cluster = new Cluster(this, createUniqueResourceName('Cluster'), {
    clusterName,
    vpc: this.network.vpc,
    containerInsights: true,
});
```
CDK generates templates with ContributorInsights enabled like below
```json
  "ClusterEB0386A7": {
   "Type": "AWS::ECS::Cluster",
   "Properties": {
    "ClusterSettings": [
     {
      "Name": "containerInsights",
      "Value": "enabled"
     }
    ]
   },
   "Metadata": {
    "aws:cdk:path": "Cell-Prod-KIX-01-PartitionRegistry-r0/Cluster/Resource"
   }
  },
```

And ecs container insights are enabled in the console for both ec2 and fargate clusters in all other regions except `ap-northeast-3`,  we're wondering if there's a gap somewhere that we're not aware of when using this feature in KIX.

### Expected Behavior

We expect container insights to be enabled with detailed metrics available in ap-northeast-3 same as other region

### Current Behavior

Cloudformation templates showing ecs container insights are enabled, but in the console for both ec2 and fargate clusters in `ap-northeast-3` show `default` and metrics unavailable

### Reproduction Steps

same as description above

### Possible Solution

Upgrade to newer cdk version? I couldn't find in previous issues/release notes mentioning issues specific to this region though.

### CDK CLI Version

CDKBuild-3.x

### Framework Version

"monocdk": "^1.107.0", "monocdk": "^1.72.0", "monocdk": "1.164.0",
(we have different packages for building multiple clusters, all of them in kix don't have the same issue described above)
### Node.js Version

default

### OS

Linux/macOS

### Language

Typescript

**Comment by pahud** [comment]
Unfortunately I can't reproduce this in my account.

```ts
class EcsCI extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props)

    const vpc = ec2.Vpc.fromLookup(this, 'Vpc', { isDefault: true });
    const cluster = new ecs.Cluster(this, 'Cluster', {
      vpc,
      containerInsights: true,
    });
  }
}
```

<img width="1431" alt="image" src="https://user-images.githubusercontent.com/278432/228567850-7380587c-e518-408d-8b61-c9c1c49f8a75.png">

Please note [monocdk](https://www.npmjs.com/package/monocdk) is experimental and not recommended to use in production. We highly recommend use cdk v2 instead.

Can you try the latest aws cdk version 2.70.0 and let me know if this issue still exists?

**Comment by brahadas** [comment]
@dandrei
You should have received two raw domain files today. Please disregard and delete the file named [`raw_domains_20241017_104656.csv.gz`] that was sent earlier, as it was for testing purpose.

Kindly refer to the updated file sent today, titled [`raw_domains_20241017_132606.csv.g`z], which is the correct one for this week.

Please confirm receipt of the file. Thank you!
