### ISSUE TITLE
Unable to use secret value for CfnIPSet ipSetDescriptors value

### ISSUE THREAD

**Issue by AlexCheema** [aws/aws-cdk#2483]
```typescript
// secret is an ip in plaintext
const ipSet = new waf.CfnIPSet(this, "IPSet", {
    name: "IPSet",
    ipSetDescriptors: [{ type: "IPV4", value: `${secret.secretValue.toString()}/32` }]
});
```

Gives error
`Update failed, invalid CIDR block: cannot parse {{resolve:secretsmanager:arn:aws:secretsmanager:xxxxxx:secret:XXXXXX:SecretString:::}} as a CIDR`

**Version:**
 - OS
Windows 10
 - Programming Language
Typescript
 - CDK Version
0.30.0

**Comment by SomayaB** [comment]
Hi, I apologize for the late reply. Are you still experiencing this issue?

**Comment by SomayaB** [comment]
Closing this issue since there hasn't been activity on it in a while. Feel free to reopen if you are still experiencing this issue.
