### ISSUE TITLE
(aws-apigateway): (SpecRestApi doesn't support composed schema)

### ISSUE THREAD

**Issue by Ys-Zhou** [aws/aws-cdk#24844]
### Describe the bug

I believe this bug is related to CloudFormation. But I cannot fine a way to report it.
I created a OpenAPI Specification with a schema containing allOf like:
```yaml
openapi: 3.0.3
info:
  title: test API
  version: 0.0.1
paths:
  /test:
    get:
      responses:
        200:
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    properties:
                      a:
                        type: string
                  - type: object
                    properties:
                      b:
                        type: string
      x-amazon-apigateway-integration:
        type: mock
        requestTemplates:
          application/json: '{"statusCode": 200}'
        passthroughBehavior: never
        responses:
          default:
            statusCode: 200
            responseTemplates:
              application/json: '{"message": "OK"}'
```
And a SpecRestApi like:
```ts
new SpecRestApi(this, 'test-api', {
  apiDefinition: ApiDefinition.fromAsset(path_to_file),
  failOnWarnings: true,
};
```
But when I ran cdk deploy, it reported:
```
Unsupported model type 'ComposedSchema' in 200 response to method 'GET /test'. Ignoring.
```

And API Gateway actually support composed schema, I can add a model with the schema from API Gateway console:
```json
{
    "allOf":[
        {
            "type": "object",
            "properties": {
                "a": {"type": "string"}
            }
        },
        {
            "type": "object",
            "properties": {
                "b": {"type": "string"}
            }
        }
    ]
}
```

### Expected Behavior

API Created with a correct model

### Current Behavior

It reports `Unsupported model type 'ComposedSchema' in 200 response to method 'GET /test'. Ignoring.`
But API Gateway supports `ComposedSchema` actually.
BTW, if I put the schema in a requestBody, it reported: `Unsupported model type 'Content' in request schema for 'PUT /test'. Ignoring.`

### Reproduction Steps

see description

### CDK CLI Version

2.70.0

### Node.js Version

v18.15.0

### OS

macos

### Language

Typescript

### Language Version

TypeScript 4.9.5

**Comment by pahud** [comment]
Hi

This doesn't seem to be relevant to CDK but a limitation on cloudformation or API Gateway. I would suggest you report this potential bug to [clouodformation-coverage-roadmap](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/new/choose) for more visibility. If this is urgent, please report this through the [AWS support](https://docs.aws.amazon.com/awssupport/latest/user/aws-support-plans.html).
