### ISSUE TITLE
elasticache: add support for import from existing instance

### ISSUE THREAD

**Issue by spdrman** [aws/aws-cdk#24857]
### Describe the feature

elasticache should support the ability to import an instance via a similar function as in RDS:
rds.DatabaseInstanceBase.fromDatabaseInstanceAttributes()

### Use Case

When creating a lambda in a separate stack, we could import the instance to obtain its parameters, and to grant the lambda function access, etc...

### Proposed Solution

Ideally we could have a fromElasticacheInstanceName()

### Other Information

This ability to import an instance definition from one stack into another is supported by most other services...

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.71.0

### Environment details (OS name and version, etc.)

Darwin XXXXX.local 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:39:35 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T8103 arm64

**Comment by tim-finnigan** [comment]
Hi @spdrman thanks for reaching out. Here is a tracking issue for adding an L2 ElastiCache construct: https://github.com/aws/aws-cdk/issues/6908. When an L2 construct is added, then feature requests such as this can be revisited. For now we will close this and continue tracking ElastiCache-related feature requests in https://github.com/aws/aws-cdk/issues/6908.
