### ISSUE TITLE
Custom::LogRetention - ThrottlingException when creating multiple resources

### ISSUE THREAD

**Issue by shantgup** [aws/aws-cdk#24879]
### Describe the bug

CDK,

Creating this on behalf of an enterprise customer that experienced significant pains & delays due to this issue.

The `Custom::LogRetention` resource backed by a Lambda function managed by CDK with the source code [here](https://github.com/aws/aws-cdk/blob/cea1039e3664fdfa89c6f00cdaeb1a0185a12678/packages/%40aws-cdk/aws-logs/lib/log-retention-provider/index.ts), gets throttled by CloudWatch Logs when multiple resources are being created.

Recommend implementing backoff and retry mechanism on this custom resource to prevent failure due to throttling.

### Expected Behavior

The `Custom::LogRetention` resource should backoff and retry when it encounters a `ThrottlingException`.

### Current Behavior

Currently, the `Custom::LogRetention` resource fails when it encounters a `ThrottlingException`, and this causes the entire CloudFormation stack to fail and rollback.

### Reproduction Steps

Deploy any CloudFormation stack with multiple [`log-retention-provider`](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_logs.LogRetention.html) that in turn create `Custom::LogRetention` resources.

### Possible Solution

Implement backoff and retry until successful.

### CDK CLI Version

2.67.0

### Node.js Version

14.x

### OS

Lambda

### Language

Typescript

**Comment by khushail** [comment]
Hi @shantgup , thanks for reaching out. [This](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_logs.LogRetention.html#logretentionretryoptions) might be helpful to go through for what you are looking for. `LogRetentionRetryOptions` might be the option for your usecase.

Let me know if this does not help.
