### ISSUE TITLE
aws-ecs: Race condition in Ec2Service & FargateService between updating the TaskRole default policy and the CfnService

### ISSUE THREAD

**Issue by iancaffey** [aws/aws-cdk#24880]
### Describe the bug

Within [Ec2Service](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ecs.Ec2Service.html) and [FargateService](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ecs.FargateService.html), there is no dependency added between the TaskRole default policy and the CfnService.

If updates are made to the TaskRole default policy (e.g. adding new inline policies), CloudFormation will update both the CfnService and the TaskRole default policy at the same time, and this can result in ECS tasks spinning up without the proper permissions being updated in IAM for the task role yet.

### Expected Behavior

The TaskRole and its children (e.g. the default policy) should _always_ deploy first within a CloudFormation stack before the ECS service.

### Current Behavior

The TaskRole default policy and the ECS service deploy at the same time.

### Reproduction Steps

Every usage of [Ec2Service](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ecs.Ec2Service.html) and [FargateService](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ecs.FargateService.html) is vulnerable to this deployment race condition risk, if they ever make edits to the task role default policy.

### Possible Solution

```
this.node.addDependency(this.taskDefinition.taskRole);
```
within the [BaseService](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ecs.BaseService.html) constructor.

Lambda L2 Function construct does this already (see [here](https://github.com/aws/aws-cdk/blob/v2.72.0/packages/@aws-cdk/aws-lambda/lib/function.ts#L831)).

### CDK CLI Version

2.72.0

### Node.js Version

v16.9.1

### OS

Mac OSX

### Language

Typescript

### Language Version

TypeScript 4.9.5

**Comment by peterwoodworth** [comment]
Thanks for reporting, this makes sense!

We could probably add this in the base service class to cover both of these constructs, just right after the CfnService is created

https://github.com/aws/aws-cdk/blob/397e46c998308d05ee7508223ddba60af122b671/packages/%40aws-cdk/aws-ecs/lib/base/base-service.ts#L538
