### ISSUE TITLE
(aws-cdk-go): Documantation Overview is something wrong.

### ISSUE THREAD

**Issue by bun913** [aws/aws-cdk#24883]
### Describe the issue

Plese see the aws-cdk-go doc page.

https://pkg.go.dev/github.com/aws/aws-cdk-go/awscdk/v2@v2.72.0

It looks like something storage.

The Documantation section is particularly strange, with a lot of text that says "Version 2 of the AWS Cloud Development Kit library".

<img width="1362" alt="image" src="https://user-images.githubusercontent.com/73948280/229029964-8ff6c3c4-cddb-4467-894b-c8e9a04309fc.png">

### Links

https://pkg.go.dev/github.com/aws/aws-cdk-go/awscdk/v2@v2.72.0

**Comment by peterwoodworth** [comment]
Thanks for reporting this, we're looking into it and it's important we get this resolved

**Comment by peterwoodworth** [comment]
This has been fixed, thanks to @vinayak-kukreja
