### ISSUE TITLE
aws-eks: Release "istio-discovery" does not exist

### ISSUE THREAD

**Issue by quintonn** [aws/aws-cdk#24888]
### Describe the bug

Using CDK (TypeScript) to create an eks cluster and add helm charts, specifically istio.

Prior to upgrading aws-cdk to 2.72.0 from 2.68.0 it worked.

After the upgrade, running cdk deploy would give the following error:  

    Received response status [FAILED] from custom resource. Message returned: Error: b'Release "istio-discovery" does not exist. 
    Installing it now.\nError: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind 
    "EnvoyFilter" in version "networking.istio.io/v1alpha3"\n'

    Logs: /aws/lambda/My-Test-Stack-awscdkawseksKubec-Handler886CB40B-Splwig1XmfjP

    at invokeUserFunction (/var/task/framework.js:2:6)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async onEvent (/var/task/framework.js:1:365)
    at async Runtime.handler (/var/task/cfn-response.js:1:1543) (RequestId: 5c3be607-3328-4f9e-8499-55a76ba93764)`

I double checked by running `cdk deploy` on the same code, but using aws-cdk version 2.68.0 and that works.

### Expected Behavior

cdk deploy to run without errors

### Current Behavior

cdk deploy gives the error:  

    Received response status [FAILED] from custom resource. Message returned: Error: b'Release "istio-discovery" does not exist. 
    Installing it now.\nError: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind 
    "EnvoyFilter" in version "networking.istio.io/v1alpha3"\n'

    Logs: /aws/lambda/My-Test-Stack-awscdkawseksKubec-Handler886CB40B-Splwig1XmfjP

    at invokeUserFunction (/var/task/framework.js:2:6)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async onEvent (/var/task/framework.js:1:365)
    at async Runtime.handler (/var/task/cfn-response.js:1:1543) (RequestId: 5c3be607-3328-4f9e-8499-55a76ba93764)`

### Reproduction Steps

Using CDK, create an eks cluster and then add istio helm charts:

``` typescript
eksCluster.addHelmChart(`istio-base-helm-chart-${props.environmentName}`, {
      repository: "https://istio-release.storage.googleapis.com/charts",
      chart: "base",
      release: "istio-base",
      namespace: "istio-system",
      version: '1.17.1',
    });
    eksCluster.addHelmChart(`istio-discovery-helm-chart-${props.environmentName}`, {
      repository: "https://istio-release.storage.googleapis.com/charts",
      chart: "istiod",
      release: "istio-discovery",
      namespace: "istio-system",
      version: '1.17.1',
    });
    eksCluster.addHelmChart(`istio-gateway-helm-chart-${props.environmentName}`, {
      repository: "https://istio-release.storage.googleapis.com/charts",
      chart: "gateway",
      release: "istio-ingressgateway",
      namespace: "istio-ingress",
      version: '1.17.1',
    });
```

Then run cdk deploy

### CDK CLI Version

2.72.0

### Node.js Version

v18.12.1

### OS

Windows 10

### Language

Typescript

**Comment by pahud** [comment]
Unfortunately I can't reproduce it.



```
 % /usr/local/bin/helm -n istio-system ls
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
istio-base      istio-system    1               2023-03-31 15:38:50.812445217 +0000 UTC deployed        base-1.17.1     1.17.1     
istio-discovery istio-system    1               2023-03-31 15:38:48.726021587 +0000 UTC deployed        istiod-1.17.1   1.17.1   
```

Basically, the kubectl handler just run the following command in lambda and it works great in my environment.

```
helm upgrade istio-discovery istiod --install --create-namespace --repo https://istio-release.storage.googleapis.com/charts --version 1.17.1 --namespace istio-system --kubeconfig /tmp/kubeconfig
```

I am using cdk `2.71.1` with the cdk code below:

```ts
export class EksStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props)

    const eksCluster = getEksCluster(this);
    const environmentName = 'demo';

    eksCluster.addHelmChart(`istio-base-helm-chart-${environmentName}`, {
      repository: "https://istio-release.storage.googleapis.com/charts",
      chart: "base",
      release: "istio-base",
      namespace: "istio-system",
      version: '1.17.1',
    });
    eksCluster.addHelmChart(`istio-discovery-helm-chart-${environmentName}`, {
      repository: "https://istio-release.storage.googleapis.com/charts",
      chart: "istiod",
      release: "istio-discovery",
      namespace: "istio-system",
      version: '1.17.1',
    });
    eksCluster.addHelmChart(`istio-gateway-helm-chart-${environmentName}`, {
      repository: "https://istio-release.storage.googleapis.com/charts",
      chart: "gateway",
      release: "istio-ingressgateway",
      namespace: "istio-ingress",
      version: '1.17.1',
    });
  }
}
```

**Comment by quintonn** [comment]
I think it's something in CDK 2.72.0.
I'm also using Kubernetes Cluster version 1.25

**Comment by pahud** [comment]
@quintonn  Is it working now?

**Comment by quintonn** [comment]
no, I had to roll back my aws-cdk version to 2.68.0 for it to work.
I'll try create a full project to reproduce this.

**Comment by pahud** [comment]
@quintonn OK let me know if it works.

**Comment by quintonn** [comment]
I have managed to replicate the issue with the following repository:  
https://github.com/quintonn/aws-eks-test

run `cdk deploy`  

I get the error: `Message returned: Error: b'Release "istio-discovery" does not exist. Installing it now.\nError: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "EnvoyFilter" in version "networking.istio.io/v1alpha3"`

**Comment by quintonn** [comment]
Hi @pahud , is it possible to re-open this ticket?

**Comment by pahud** [comment]
@quintonn  if this issue is still relevant, please create a new one and mention this one. We'll validate again from there.
