### ISSUE TITLE
Automatically transform cloudformation to AWS CDK code

### ISSUE THREAD

**Issue by SyCode7** [aws/aws-cdk#2489]
It will be nice to be able to automatically translate a cloudformation template to AWS CDK code e.g.  Java. This feature could be similar to how [OpenApi codegen](https://github.com/swagger-api/swagger-codegen) translates OpenAPI documents (json and yaml) to several programming languages.

**Comment by eladb** [comment]
WIP: https://www.npmjs.com/package/cdk-dasm

**Comment by SyCode7** [comment]
> WIP: https://www.npmjs.com/package/cdk-dasm

**Comment by eladb** [comment]
Just to set expectations: this is something I am working on in the background, so don't expect steady progression. More than happy to collaborate on this and accept pull requests.

**Comment by ColWillis** [comment]
+1 to @SyCode7  Disassembler for Java!!! (pretty please)

**Comment by tom10271** [comment]
> Just to set expectations: this is something I am working on in the background, so don't expect steady progression. More than happy to collaborate on this and accept pull requests.

How to use it? It is not responding and no help message.

cdk-dasm ./My-Cloudformation.yml anything.ts

**Comment by LazzariPaolo** [comment]
@eladb any updates on this?

**Comment by LazzariPaolo** [comment]
@skinny85 how is that the same to what is being proposed here?

**Comment by skinny85** [comment]
It allows you to migrate from CloudFormation to CDK, which I'm pretty sure is the underlying ask here.

**Comment by filipeandre** [comment]
@skinny85 I don't think so. He wants to generate CDK code from cloudformation language.

**Comment by sasuolander** [comment]
From working maintenance project which till use cloudformation, I would say this is must feature if we are goin to migrate into CDK. Otherwise we would need to support cloudformation and cdk which is in my unmaintainable solution.

**Comment by skinny85** [comment]
@sasuolander the [`cloudformation-include` module](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.cloudformation_include-readme.html) is specifically designed for migrating from CloudFormation to CDK.

**Comment by danviizr** [comment]
Would love to have this for making State Machines in Step Functions using CDK code more easily (make it in the designer tool then export to IaC)
