### ISSUE TITLE
(pipelines): Support specifying artifact bucket for CodePipeline

### ISSUE THREAD

**Issue by bjornhandersson** [aws/aws-cdk#24902]
### Describe the feature

Make it possible to pass an existing artifact s3 bucket to `aws-pipelines/CodePipeline`

### Use Case

When having many CodePipeline in one account it would be desirable to be able to specify a common s3 bucket to not "pollute" the account with many buckets.

I know that you can pass an existing `aws-codepipeline/Pipeline` where you can define the `artifactBucket` prop, but it would be more lean and straight forward to have it natively on the `aws-pipelines/CodePipeLine` construct.

### Proposed Solution

Extend [CodePipelineProps](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.pipelines.CodePipelineProps.html) with an optional `artifactBucket` property that is passed to the underlying `aws-codepipeline/Pipeline` construct. 

```ts
const buildArtifacts = new Bucket(scope, 'SomeBuildArtifacts', {
  ...
});
const sourceArtifact = new codepipeline.Artifact('MySourceArtifact');

const pipeline = new pipelines.CodePipeline(this, 'Pipeline', {
  artifactBucket: buildArtifacts,
  synth: new pipelines.ShellStep('Synth', {
    input: pipelines.CodePipelineFileSet.fromArtifact(sourceArtifact),
    commands: ['npm ci','npm run build','npx cdk synth'],
    ....
}),
```

### Acknowledgements

- [X] I may be able to implement this feature request

### CDK version used

2.72.0

### Environment details (OS name and version, etc.)

All

**Comment by pahud** [comment]
It makes sense to me. Thank you for your PR!

**Comment by gagipro** [comment]
Same here, have to create bucket and pipeline and pass to each codepipeline to respect enterprise security constraints, it´s a pain and makes code heavier.
Subscribed to this one.

**Comment by bjornhandersson** [comment]
Guess #24945 closes this.
