### ISSUE TITLE
aws-ecs: Adding capcity provider to a fargate service replaces service instead of updating

### ISSUE THREAD

**Issue by fabiozig** [aws/aws-cdk#24907]
### Describe the bug

On cdk, after adding FargateCapacityProviders to the service that already exists, the service is replaced instead of being updated.

### Expected Behavior

According to the CF documentation there should be no replacement of the service when updating the capacity provider strategy.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-service.html#cfn-ecs-service-capacityproviderstrategy

### Current Behavior

Changes during deployment.
```
UPDATE_IN_PROGRESS   | AWS::ECS::Service                             | serverless-app/serverless-ecs/cdk-patterns-test-dev-ecs-service/Service (serverlessecscdkpatternstestdevecsserviceService8F1F40AF) Requested update requires the creation of a new physical resource; hence creating one.
```

### Reproduction Steps

1. Create service without a capacity provider strategy and deploy
2. Add capacity provider strategy to service and deploy

Cdk code:
```typescript
const cluster = new ecs.Cluster(this, `${clusterName}`, {
	clusterName,
	vpc,
	enableFargateCapacityProviders: true,
})

const service = new ecs.FargateService(this, serviceName, {
	serviceName, 
	cluster, 
	taskDefinition: task,
	securityGroups: [serviceSecurityGroup],
	vpcSubnets: {
		subnetType: this.options.ecsOption?.serviceSubnetType
			? this.options.ecsOption?.serviceSubnetType
			: ec2.SubnetType.PRIVATE_WITH_EGRESS
	},
	desiredCount: 5,
	assignPublicIp: true,
	healthCheckGracePeriod: this.options.ecsOption?.healthCheckGracePeriodSeconds ? cdk.Duration.seconds(this.options.ecsOption.healthCheckGracePeriodSeconds) : undefined,
	minHealthyPercent: 100,
        // ADDING CAPACITY PROVIDER STRATEGY TO THE SERVICE TRIGGERS RECREATION OF THE SERVICE
	capacityProviderStrategies: [
		{
			capacityProvider: "FARGATE_SPOT",
			weight: 1,
		},
		{
			capacityProvider: "FARGATE",
			weight: 1,
			base: 3,
		},
	]
})
```

### Additional Information/Context

Currently my service is named, so my deployment is failing because the service already exists...

```
UPDATE_FAILED        | AWS::ECS::Service                             | serverless-app/serverless-ecs/cdk-patterns-test-dev-ecs-service/Service (serverlessecscdkpatternstestdevecsserviceService8F1F40AF) Resource handler returned message: "Resource of type 'AWS::ECS::Service' with identifier 'cdk-patterns-test-dev-ecs-service' already exists." (RequestToken: 8251c81d-158a-bc49-153c-27c85b225ab0, HandlerErrorCode: AlreadyExists)

```

### CDK CLI Version

2.72.1

### Node.js Version

14

### OS

ubuntu 18

### Language

Typescript

### Language Version

4.3.2

**Comment by pahud** [comment]
I am afraid this is a limitation on ECS but I can't find any document about it. I'll reach out internally and get back to here if I have any updates.

**Comment by fabiozig** [comment]
Just checked the output in the cdk diff and it seems the reason this is happening is because cdk unsets lunch type when capacity provider is defined.

```
[~] AWS::ECS::Service serverless-ecs/cdk-patterns-test-dev-ecs-service/Service serverlessecscdkpatternstestdevecsserviceService8F1F40AF replace
 ├─ [+] CapacityProviderStrategy
 │   └─ []
 └─ [-] LaunchType (requires replacement)
     └─ FARGATE
```

You can find the related code in the link bellow:
https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-ecs/lib/base/base-service.ts#L531

I also tested changing the capacity provider directly on the AWS console, and I was able to add the capacity provider without having to recreate the service... after the update it started a new deployment in the service. 

It doesn't seem to be a limitation on ECS.

**Comment by pahud** [comment]
Thank you for the insight.

Yes, according to this:
https://github.com/aws/aws-cdk/blob/e98a5186dc4b22f5b3a2c6a972cf9bd38a9e1484/packages/aws-cdk-lib/aws-ecs/lib/base/base-service.ts#L308

and this:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-service.html#cfn-ecs-service-capacityproviderstrategy

The `LaunchType` will be unset and omitted when you add the CapacityProvider, which triggers the replacement in CFN. I will discuss this with relevant teams internally and see if there's anything we can work it around.

**Comment by pahud** [comment]
Hi @fabiozig 

Following up this issue. Can you tell us more details of the impact?

Sounds like adding CP from CDK/CFN will trigger service replacement while adding CP from the ECS console will trigger new service deployment. Service replacement could lead to service downtime while service deployment ensures the desired count of tasks. Is it correct?

**Comment by fabiozig** [comment]
Our solution was renaming the service on our cloud formation stack... It's not ideal but it is how we solved it. By doing that we can ensure a new service with the spot instance will be created before the old service is deleted, with no downtime.
