### ISSUE TITLE
aws-rds: Clarify documentation around Performance Insights retention granularity

### ISSUE THREAD

**Issue by adrianwright** [aws/aws-cdk#24913]
### Describe the feature

RDS Performance Insights enumeration only supports retention periods of 7 days or 2 years:
https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_rds.PerformanceInsightRetention.html

This can lead a dev to believe only those two values are supported by CDK. Values not present in the enumeration can still be set by using an integer instead of the enumeration.

This request is to clarify the documentation to make it clear that other values can be provided.

### Use Case

RDS users often need to retain performance insights data for retention periods other than 7 days or 2 years. The documentation may lead readers to believe those two values are the only ones supported.

### Proposed Solution

Update the documentation to indicate that an integer value can be supplied instead of the retention period.

### Acknowledgements

- [x] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.72.1

### Environment details (OS name and version, etc.)

All

**Comment by pahud** [comment]
I think the doc string here indicates its format but I agree we can improve the document whenever possible.

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_rds.InstanceProps.html#performanceinsightretention

**Comment by adrianwright** [comment]
To me, the enumeration is misleading. It seems to communicate that there are only two settings supported by CDK (7 days or 2 years). It would be clearer if it there was no enumeration and the type was either integer or Duration.

**Comment by jtoberon** [comment]
Can this issue be closed? Looks like the enum now supports all months between 1 and 24 which is the max: https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-rds/lib/props.ts#L548. This enum change was made in this commit: https://github.com/aws/aws-cdk/commit/1dbae20bdc633ce580cab8f758a43bfba763c4f6.
