### ISSUE TITLE
Set ulimit in container definition prop

### ISSUE THREAD

**Issue by peterwoodworth** [aws/aws-cdk#24918]
### Discussed in https://github.com/aws/aws-cdk/discussions/23063

Ability to set ulimit as prop, instead of just through a method

<div type='discussions-op-text'>

<sup>Originally posted by **ambethell** November 23, 2022</sup>
I need to set the ulimits on a fargate ECS task - (I'm using the Java CDK).  

From what I can tell I should be able to set this on the fargate task definition - but I cannot see how to do this using the CDK.  Do I need to add an extension to the fargateTaskDefinition? 

I see 'ContainerDefinition' has a public method for setting uLimit - however the ContainerDefinitionOptions.builder() does not appear to provide methods to set this.  

Both v1 / v2 documentation dont provide this - https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ecs.ContainerDefinitionOptions.html

Any pointers? 

Thanks!</div>

**Comment by pahud** [comment]
I think we probably can just add [ulimits](https://github.com/aws/aws-cdk/blob/cea1039e3664fdfa89c6f00cdaeb1a0185a12678/packages/%40aws-cdk/aws-ecs/lib/container-definition.ts#L394) in [ContainerDefinitionOptions](https://github.com/aws/aws-cdk/blob/cea1039e3664fdfa89c6f00cdaeb1a0185a12678/packages/%40aws-cdk/aws-ecs/lib/container-definition.ts#L102) so we can specify ulimits when we [addContainer()](https://github.com/aws/aws-cdk/blob/cea1039e3664fdfa89c6f00cdaeb1a0185a12678/packages/%40aws-cdk/aws-ecs/lib/base/task-definition.ts#L590).


```ts
const task = ecs.TaskDefinition(...);
task.addContainer('id', options_with_ulimits);
```
