### ISSUE TITLE
Step Functions definition is unreadable when generating Cloud Formation Template

### ISSUE THREAD

**Issue by elvinx** [aws/aws-cdk#2493]
Hello,

Is there a way to get the generated Step Functions definition nicely formatted inside the Cloud Formation Template?

Below is the current behavior. Is it a known issue ?

<img width="964" alt="Screen Shot 2019-05-07 at 2 18 09 PM" src="https://user-images.githubusercontent.com/8008982/57298669-0a04ae00-70d3-11e9-8b88-1eed572ab81c.png">

**Comment by eladb** [comment]
We don't have any current plans to optimize the format of the CloudFormation output. We see the synthesized CloudFormation templates as "compiled artifacts" which are meant to be read by machines and not humans. Can you please provide some more details about your use case and describe why the format of the CloudFormation output is of importance?

**Comment by elvinx** [comment]
Our use case restricts us from directly using `cdk.deploy()` and therefore we would like to generate CF templates using CDK and deploy the stacks manually. And because of that having a "human" readable output would make the code review process for us much easier.

**Comment by eladb** [comment]
Thanks for the details about your use case. I doubt that this is something we will prioritize within the coming months, but we are open to contributions!

**Comment by elvinx** [comment]
Thanks for the quick reply :)
