### ISSUE TITLE
(contributing): Duplicate directories in `packages/@aws-cdk` and `packages/aws-cdk-lib`

### ISSUE THREAD

**Issue by kylelaker** [aws/aws-cdk#24939]
### Describe the issue

After the remodel PR was merged, there are duplicate directories in `packages/@aws-cdk` and `packages/aws-cdk-lib`. It seems like there are open PRs to handle several of these. #24930 handles duplicates of `aws-` prefixed packages (to clarify which are alpha packages) and #24929 handles `cloud-assembly-schema`. There are still two packages, `cx-api` and `region-info` that are duplicated between the two directories.

`cx-api` is specifically [mentioned in CONTRIBUTING.md](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md#feature-flags). It's unclear which of the two directories contributions for feature flags would be made two; #24929 implies it'd be the one in `aws-cdk-lib` but the docs link to the other one in `@aws-cdk`.

<details>
<summary>Full list of duplicate directories</summary>

```text
$ cd packages
$ ls @aws-cdk > @aws-cdk.txt
$ ls aws-cdk-lib > aws-cdk-lib.txt
comm -12 <(sort @aws-cdk.txt) <(sort aws-cdk-lib.txt)
aws-amplify
aws-apigatewayv2
aws-apprunner
aws-batch
aws-cloud9
aws-codestar
aws-gamelift
aws-glue
aws-iot
aws-iotevents
aws-ivs
aws-kinesisfirehose
aws-location
aws-msk
aws-neptune
aws-redshift
aws-route53resolver
aws-s3objectlambda
aws-sagemaker
aws-servicecatalogappregistry
aws-synthetics
cloud-assembly-schema
cx-api
region-info
```
</details>

### Links

- https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md#feature-flags

**Comment by MrArnoldPalmer** [comment]
hey @kylelaker , yeah the same thing that fixes cloud-assembly-schema will be applied to all the non-alpha modules, IE cx-api. Working on that now.

**Comment by rix0rrr** [comment]
Does this issue still apply? As far as I can tell we've renamed all service packages to `*-alpha`, and changed all support packages to have a copy build step. 

Do you think there is still room for confusion?
