### ISSUE TITLE
(@aws-cdk-testing): The file should be excluded but existent after remodel

### ISSUE THREAD

**Issue by yo-ga** [aws/aws-cdk#24947]
### Describe the bug

Some JavaScript files generated from the integration testing files are added to the repository during remodeling.

### Expected Behavior

Without the following files in `packages/@aws-cdk-testing/framework-integ/test`
- `integ.*.d.ts`
- `integ.*.js`

### Current Behavior

With the following files in `packages/@aws-cdk-testing/framework-integ/test`
- `integ.*.d.ts`
- `integ.*.js`

### Reproduction Steps

N/A

### Possible Solution

- Remove the existing files
- Add the rule to `.gitignore`

### CDK CLI Version

N/A

### Framework Version

master

### Node.js Version

N/A

### OS

N/A

### Language

Typescript

**Comment by yo-ga** [comment]
I may be able to fix this bug report

**Comment by pahud** [comment]
Thank you for the PR!!
