### ISSUE TITLE
(aws-logs): update log retention lambdas to nodejs16.x

### ISSUE THREAD

**Issue by abelmokadem** [aws/aws-cdk#24941]
### Describe the feature

Lambda 14 is out of security support on the 30th of April 2023.

### Use Case

Upgrade to nodejs16.x to extend the security support for the AWS CDK lambdas.

### Other Information

Linked to #24202 

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.72.1

### Environment details (OS name and version, etc.)

N/A

**Comment by joostvdwsd** [comment]
I've noticed multiple PR's for upgrading to 16 or 18 i.e.:
https://github.com/aws/aws-cdk/pull/24203
https://github.com/aws/aws-cdk/pull/24725

These PR's are closed with the remark:
- that the SDK version needs to be upgraded to 3 when moving to 18
- not all regions support 16 or 18

Both are logical but I would expect a plan of action and a timeline.
Does anyone have a good overview about runtime availability in all regions? This is something I can't find

**Comment by pahud** [comment]
related to https://github.com/aws/aws-cdk/pull/24747#issuecomment-1485625617
