### ISSUE TITLE
Python support in CDK Workshop

### ISSUE THREAD

**Issue by fulghum** [aws/aws-cdk#2495]
Now that the CDK Python Developer Preview is officially released, we'd like to extend the cdkworkshop site to include a guided walkthrough for Python developers, in addition to the TypeScript material.

**Comment by pierorex** [comment]
It would be really useful for the CDK guys at my company.
Working with Python code is definitely easier for everyone over here.

**Comment by fulghum** [comment]
Good news!  We added Python to the CDK Workshop last week!  
https://cdkworkshop.com/
