### ISSUE TITLE
aws-cdk-lib: Cannot find fromJobQueueArn in cdk v2 JobQueue

### ISSUE THREAD

**Issue by abdoolly** [aws/aws-cdk#24950]
### Describe the bug

I am trying to create a batch job and upgrade from cdk v1 to v2 in typescript.

```
import { BatchJob } from 'aws-cdk-lib/aws-events-targets';
import * as batchV1 from '@aws-cdk/aws-batch';


// this is cdk v1 
const jobQueue = batchV1.JobQueue.fromJobQueueArn(
  this,
  `${prefix}JobQueue`,
  props.jobQueueArn
);

// no alternative in cdk v2 only CfnJobQueue allowed  and will force to create a new job queue
// how create a job queue object from an existing one.

const batchJobTarget = new BatchJob(
  jobQueue.jobQueueArn,
  jobQueue,
  jobDefinitionArn,
  jobDefinition,
);

```

I cannot find an alternative in cdkv2 to be able to create a job queue from an already existing job queue 
also this is the same case for job definitions as well?

### Expected Behavior

since the cdk v1 support is going to end on next june
I hoped I can find alternatives to what happens in cdk v2

I expected the `CfnJobQueue` to also have a `fromJobQueueArn` 
as well as the same case in `CfnJobDefinition`

### Current Behavior

cdk v2 currently does not support `fromJobQueueArn` or `batchV1.JobDefinition.fromJobDefinitionArn`
what is the alternatives ? 
while BatchJob requires the JobQueue object and JobDefinition object.

### CDK CLI Version

2.72.1

### Node.js Version

v16.14.0

### OS

mac os ventura

### Language

Typescript

### Language Version

4.6.4

**Comment by pahud** [comment]
Hi

I believe `JobQueue` in v2 is at `aws-batch-alpha` and you will need to install the alpha package manually.

See https://docs.aws.amazon.com/cdk/api/v2/docs/@aws-cdk_aws-batch-alpha.JobQueue.html

And [Experimental construct libraries are now available in AWS CDK v2](https://aws.amazon.com/blogs/developer/experimental-construct-libraries-are-now-available-in-aws-cdk-v2/) for more details.

**Comment by abdoolly** [comment]
I was wondering if I could get some clarification on the stability of the CDK alpha version, given that v1 is reaching end-of-life. Is the alpha version stable enough for us to consider switching to? Also, could you please confirm the end-of-life date for v1? My understanding is that it's approaching.

**Comment by comcalvi** [comment]
v1 is now EOL. The constructs for Batch have just been entirely rewritten and will be available soon on v2, and will *not* be available on v1. They are still in alpha, but the overall API design is now something we intend to graduate once the construct has been in the hands of customers for some time.
