### ISSUE TITLE
(Asset Staging): using docker image inside codebuild hits docker ratelimit

### ISSUE THREAD

**Issue by jaypea** [aws/aws-cdk#24969]
### Describe the bug

when running cdk deploy inside a codebuild build to deploy a lambda `PythonFunction` with bundling set to 
```
bundling: {
        bundlingFileAccess: BundlingFileAccess.VOLUME_COPY,
      },
 ```
 
 a helper docker is ran using a basic `alpine` image (see https://github.com/aws/aws-cdk/blob/4c2e7d63b46490bbaf512b3c2b96efc189deb78d/packages/aws-cdk-lib/core/lib/private/asset-staging.ts#L122)
 
 this tries to load the `alpine:latest` image from docker.com which usually hits the `docker: toomanyrequests: You have reached your pull rate limit. ` error in a shared environment like codebuild.
 

 

### Expected Behavior

just build the asset

### Current Behavior

hitting a rate limit error

### Reproduction Steps

see above

### Possible Solution

 if this would take the image from public.ecr, this would help avoiding this rate limit (public.ecr.aws/docker/library/alpine:latest)
 

### CDK CLI Version

2.63

### Node.js Version

16

### OS

linux

### Language

Typescript

**Comment by pahud** [comment]
Thank you for the report. I believe we should use images from ECR public instead. Making this p1 and any PR is highly welcome.
