### ISSUE TITLE
@aws-cdk/aws-cloudwatch/lib/alarm.ts: Cloudwatch Alarm with p100 statistics is missing ExtendedStatistic property in CFN template after recent cdk change.

### ISSUE THREAD

**Issue by pearlswan** [aws/aws-cdk#24976]
### Describe the bug

Starting recently, I noticed when using p100 statistics for cloudwatch Alarms, the generated CFN template is missing ExtendedStatistic property. However the same code was working previously. Also p100 is a valid value if create alarm from AWS console.

Looks like this change changes behavior for validating percentiles. 
https://github.com/aws/aws-cdk/commit/853e3d631ef0490b0e2d14fdcf50df9f745de3eb

### Expected Behavior

The generated CFN template should have ExtendedStatistic property.

### Current Behavior

The generated CFN template is missing the ExtendedStatistic property.

### Reproduction Steps

```
        const alarm = new Alarm(this, `----`, {
            alarmName: `----`,
            metric: new Metric({
                dimensionsMap: {
                    Program: program,
                },
                metricName: '----',
                namespace: namespace ,
                period: Duration.minutes(1),
                statistic: Stats.p(100),
            }),
            comparisonOperator: ComparisonOperator.GREATER_THAN_OR_EQUAL_TO_THRESHOLD,
            evaluationPeriods: 1,
            threshold: ----,
            treatMissingData: TreatMissingData.NOT_BREACHING,
        });
```

### CDK CLI Version

na

### Node.js Version

14

### OS

macOs

### Language

Typescript

**Comment by peterwoodworth** [comment]
Thanks for reporting this, I was able to confirm that the `"ExtendedStatistic": "p100",` prop in the template disappears before and after this change. We will try to address this promptly
