### ISSUE TITLE
ApplicationLoadBalancedFargateService: There is already a Construct with name 'PublicListener' in ApplicationLoadBalancer [LoadBalancer]

### ISSUE THREAD

**Issue by tiwarrab** [aws/aws-cdk#24975]
### Describe the bug

We're trying to migrate from `FargateService` to `ApplicationLoadBalancedFargateService` for incorporating autoscaling
But the issue here is we have a separate setup for our OneBox setup which requires us to create a common `ApplicationLoadBalancer`
I did create one separately and tried to attach it to the loadBalancer = props.loadBalancer  property in ApplicationLoadBalancedFargateService , however it does not work with the error,  `There is already a Construct with name 'PublicListener' in ApplicationLoadBalancer [LoadBalancer]`

This is what I am doing to reference the existing ALB
```
this.loadBalancer = new ApplicationLoadBalancer(this, 'LoadBalancer', {
      vpc: this.cluster.vpc,
      deletionProtection: true,
      internetFacing: true,
    });

this.service = new ApplicationLoadBalancedFargateService(this, 'LTSService', {
      platformVersion: FargatePlatformVersion.VERSION1_4,
      cluster: props.ecsCluster,
      taskDefinition: this.taskDefinition,
      desiredCount: 1,
      enableExecuteCommand: true,
      loadBalancer = props.loadBalancer
    });
    
    targetGroupProps.targetGroup.addTarget(this.service.service.loadBalancerTarget({ containerName: 'Application', containerPort: targetGroupProps.port, protocol: Protocol.TCP }));
      this.service.service.connections.allowFrom(props.loadBalancer.connections, Port.tcp(targetGroupProps.port), `ALB to ${targetGroupProps.type} Access`);
```
    
    

### Expected Behavior

Attach the external ALB to ALBFS

### Current Behavior

`There is already a Construct with name 'PublicListener' in ApplicationLoadBalancer [LoadBalancer]`

### Reproduction Steps

This is what I am doing to reference the existing ALB

```
this.loadBalancer = new ApplicationLoadBalancer(this, 'LoadBalancer', {
      vpc: this.cluster.vpc,
      deletionProtection: true,
      internetFacing: true,
    });

this.service = new ApplicationLoadBalancedFargateService(this, 'LTSService', {
      platformVersion: FargatePlatformVersion.VERSION1_4,
      cluster: props.ecsCluster,
      taskDefinition: this.taskDefinition,
      desiredCount: 1,
      enableExecuteCommand: true,
      loadBalancer = props.loadBalancer
    });
    
    targetGroupProps.targetGroup.addTarget(this.service.service.loadBalancerTarget({ containerName: 'Application', containerPort: targetGroupProps.port, protocol: Protocol.TCP }));
      this.service.service.connections.allowFrom(props.loadBalancer.connections, Port.tcp(targetGroupProps.port), `ALB to ${targetGroupProps.type} Access`);
```
    
    

### CDK CLI Version

2.46.0

### Node.js Version

14

### OS

MacOS

### Language

Typescript

**Comment by peterwoodworth** [comment]
I can't reproduce this with the snippet provided. Passing in this alb to the pattern construct will create a single construct called `PublicListener`. You likely have code outside this snippet that is adding that other public listener to your ALB

**Comment by tiwarrab** [comment]
This is the entire code I have for the ALB creation
`this.loadBalancer = new ApplicationLoadBalancer(this, 'LoadBalancer', {
      vpc: this.cluster.vpc,
      deletionProtection: true,
      internetFacing: true,
    });

    this.loadBalancer.setAttribute('routing.http.drop_invalid_header_fields.enabled', 'true');
    this.loadBalancer.setAttribute('routing.http.desync_mitigation_mode', 'strictest');
    const accessLogsBucket = createAccessLogsBuckets(this, `${ServiceName.LTS}-ServerAccessLogsBucket`, `${ServiceName.LTS}-LoadBalancerAccessLogsBucket`);
    this.loadBalancer.logAccessLogs(accessLogsBucket);

    const wsTargetGroupPort: number = 8080;
    const wsApplicationTargetGroup: ApplicationTargetGroup = new ApplicationTargetGroup(this, 'TargetGroup', {
      healthCheck: {
        path: '/',
        port: 'traffic-port',
        protocol: Protocol.HTTP,
        healthyHttpCodes: '200-499',
      },
      port: wsTargetGroupPort,
      protocol: ApplicationProtocol.HTTP,
      vpc: this.cluster.vpc,
      deregistrationDelay: Duration.seconds(60),
    });

    this.loadBalancer.addListener('HttpsListener', {
      port: 443,
      certificates: [{ certificateArn: hostedZoneCertificate.certificateArn }],
      defaultTargetGroups: [wsApplicationTargetGroup],
      sslPolicy: SslPolicy.TLS12_EXT,
    });

    const grpcTargetGroupPort: number = 8081;
    const grpcApplicationTargetGroup: ApplicationTargetGroup = new ApplicationTargetGroup(this, 'GrpcTargetGroup', {
      healthCheck: {
        path: '/livetail.proto.AWSLogsLiveTailingService/healthCheck',
        port: `${grpcTargetGroupPort}`,
        protocol: Protocol.HTTP,
        healthyGrpcCodes: '0',
      },
      port: grpcTargetGroupPort,
      protocol: ApplicationProtocol.HTTP,
      protocolVersion: ApplicationProtocolVersion.GRPC,
      vpc: this.cluster.vpc,
      deregistrationDelay: Duration.seconds(60),
    });

    this.loadBalancer.addListener('GrpcListener', {
      port: 8443,
      certificates: [{ certificateArn: hostedZoneCertificate.certificateArn }],
      defaultTargetGroups: [grpcApplicationTargetGroup],
      sslPolicy: SslPolicy.TLS12_EXT,
    });`

**Comment by peterwoodworth** [comment]
I still can't reproduce this with the snippet given. If you'd like us to continue assistance, please create a GitHub repository which I can clone and synth to reproduce the error on latest version. Thanks!

**Comment by bytesnz** [comment]
I'm getting the same error. It is caused by trying to add multiple fargate services to the same load balancer. See demo repo https://gitlab.com/bytesnz/fargate-services-fail and error cause (hardcoded id) https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-ecs-patterns/lib/base/application-load-balanced-service-base.ts#L510. I was wondering if the id could be something like `id + 'Listener'` instead of `'PublicListener'`. Can do a PR for, but there are a few other ids that might need the same treatment.
