### ISSUE TITLE
aws-eks: Cloudformation changeset fails on EKS version upgrade

### ISSUE THREAD

**Issue by ongkong** [aws/aws-cdk#24996]
### Describe the bug

Upgrading EKS from 1.20 to 1.21 using CDK results in a changeset execution failure with the status of "Update Failed" on the EKSCluster resource. 

### Expected Behavior

I expected for the EKS update to be successful.

### Current Behavior

The EKSCluster resource has the following Update Message:
```
Received response status [FAILED] from custom resource. Message returned: ResourceNotReadyException: Resources for the function are being restored. at Object.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27) at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/rest_json.js:49:8) at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20) at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10) at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:686:14) at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10) at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12) at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10 at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9) at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:688:12) (RequestId: cd921112-3006-41d3-9197-3bcc5ca1728a)
```
The stack is stack in Update Rollback failed as well with the message: "The following resource(s) failed to update: [EKSCluster80635D6E]."

### Reproduction Steps

1. create a cluster with EKS 1.20
```
new Cluster(this, "Resource", {
      clusterName: "Cluster",
      version: KubernetesVersion.of("1.20"),
...
})
```
2. Bump the version to 1.21
```
new Cluster(this, "Resource", {
      clusterName: "Cluster",
      version: KubernetesVersion.of("1.21"),
...
})
```

Reproduction might be difficult because cloudformation / eks does not support deploying new EKS clusters running 1.20.

### Additional Information/Context

I have custom resources in the stack and use a managed node group.

Because reproducing is difficult since I can't create new clusters with EKS 1.20, I created a new cluster running 1.21 and tried to upgrade it to 1.22. I ran into a different error:
```
{
    "errorType": "Error",
    "errorMessage": "cluster update id \"d509fe19-851e-40ff-a344-8cdc7fa41246\" failed with errors: []",
    "stack": [
        "Error: cluster update id \"d509fe19-851e-40ff-a344-8cdc7fa41246\" failed with errors: []",
        "    at ClusterResourceHandler.isEksUpdateComplete (/var/task/cluster.js:1:5005)",
        "    at processTicksAndRejections (internal/process/task_queues.js:95:5)",
        "    at async ClusterResourceHandler.isUpdateComplete (/var/task/cluster.js:1:3251)"
    ]
}
```
But the rollback succeeded.

I tried to upgrade the CDK version from 2.0.0-rc.6 to 2.36.0 and then attempt another upgrade, and ran into the same error along with a successful rollback.

### CDK CLI Version

2.0.0-rc.6 (build 849f0c0)

### Node.js Version

v14.19.1

### OS

mac osx

### Language

Typescript

**Comment by pahud** [comment]
Can you share your full construct property of eks.Cluster() ?

Did you specify [kubectlLayer](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_eks.FargateCluster.html#kubectllayer)?

**Comment by ongkong** [comment]
@pahud 
When i ran the experiment detailed in ## Additional Information/Context, I used the following eks.Cluster()
```
const kubeLayer = new KubectlLayer(this, 'KubectlLayer');

  // Reference: https://docs.aws.amazon.com/cdk/api/latest/docs/aws-eks-readme.html
  const cluster = (this.cluster = new Cluster(this, "Resource", {
    clusterName: "Cluster",
    kubectlLayer: kubeLayer,
    version: KubernetesVersion.of("1.22"),
    vpc: props.vpc,

    // Place Lambda function for interacting with EKS API for cluster lifecycle in our VPC.
    placeClusterHandlerInVpc: true,

    // Don't expose Kubernetes API endpoint to the public internet. kubectl can then only be run
    // from the VPC or connected networks, like the bastion host created above.
    // See https://docs.aws.amazon.com/eks/latest/userguide/cluster-endpoint.html
    endpointAccess: EndpointAccess.PRIVATE,

    // Disable automatic node group creation. We create our own below.
    defaultCapacity: 0,

    // Use envelope encryption for Kubernetes secrets
    secretsEncryptionKey: secretsKey,
  }));
```
with `"@aws-cdk/lambda-layer-kubectl-v22": "^2.0.7"`. I got the empty error message detailed above.

**Comment by ongkong** [comment]
I tried this with `aws-cdk/lambda-layer-kubectl-v22` and the changeset succeeded. What happened was
1. Changeset was executed to upgrade to EKS 1.22.
2. Cloudformation gets an errors and fails the changeset.
3. I check the UX and EKS is at 1.22 though.
4. The next changeset I execute tries to upgrade EKS to 1.22, sees its already in 1.22 and does a noop.
