### ISSUE TITLE
Add s3 location to bucket class as public field

### ISSUE THREAD

**Issue by ali-habibzadeh** [aws/aws-cdk#2500]
Hi,

One of the most important/basic pieces of information to know about a bucket is its location. This by default is `s3://<bucketArn>`.

It would be great if you guys could add this public field so users don't have to create a whole new class and extend the bucket for 1 basic field.

Currently users have to write lots of boilerplate like this

```
BaseBucket extends Bucket {
  public s3Location = `s3://${this.bucketName}`;
  constructor(parent: Construct, id: string, props: BucketProps) {
    super(parent, id, props);
  }
}
```

**Comment by SomayaB** [comment]
Hi @ali-habibzadeh, I'm sorry this has gone so long without response. We will look into this and someone will update this issue when there is movement.

**Comment by ali-habibzadeh** [comment]
Hi @SomayaB Thanks for getting back to me. Looking forward to see what happens with this.

**Comment by iliapolo** [comment]
This is now available as `bucket.s3UrlForObject()`
