### ISSUE TITLE
Missing modules from new reference docs site

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#2501]
**Describe the bug**
The new reference docs site (https://docs.aws.amazon.com/cdk/api/latest) only includes modules that represent AWS services and not modules like @aws-cdk/core, @aws-cdk/assets, etc.

**To Reproduce**
Go to: https://docs.aws.amazon.com/cdk/api/latest/

**Expected behavior**
We should include all modules (their README files are especially important) in the reference docs website. Probably distinguish them from the service modules some how.

**Version:**
 - CDK Version: 0.31.0

**Comment by rix0rrr** [comment]
I'd like to remind you that you yourself requested we only show the AWS services :)

**Comment by eladb** [comment]
What the hell was I thinking then? I think we said, "lets start with those, and then add the rest".

**Comment by rix0rrr** [comment]
I think the motivation was, "because people only/mostly care about AWS services they can use."

I don't disagree. OTOH, the core modules are in the language-specific references.

**Comment by eladb** [comment]
> I don't disagree. OTOH, the core modules are in the language-specific references.

But the README files are not there, right?

**Comment by zmgehlke** [comment]
I'd like to add that a ton of supporting files from the docs are missing.

https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-greengrass.CfnFunctionDefinitionVersion.html

This page contains many broken links, FunctionProperty and DefaultConfigProperty are both broken.

In general, this problem spans all modules I've used: all of the support types are missing from the docs, which makes it difficult to figure out the inputs to various constructors.
