### ISSUE TITLE
Eks Cluster: EKS Cluster lookup should return a Cluster object and not an ICluster object

### ISSUE THREAD

**Issue by RonakShah92** [aws/aws-cdk#25016]
### Describe the feature

Hello,

When we create an EKS cluster and want to reference the same within the cdk code, we use the below sample code for the same:
```
ICluster importedCluster = Cluster.fromClusterAttributes(this, "ImportedCluster", ClusterAttributes.builder()
         .clusterName(cluster.getClusterName())
         .clusterSecurityGroupId(cluster.getClusterSecurityGroupId())
         .build());
```
The above method always returns an `ICluster` object instead of a `Cluter` object.
Now let's say if want to add other functionalities such as granting other nodes as master level permissions on this cluster, adding manifest to cluster. Now all these use cases require a Cluster object and not ICluster object, thus making the returned type from `fromClusterAttributes(...)` method not much useful.
Also, `ICluster` object cannot be directly type casted to `Cluster` object.
https://docs.aws.amazon.com/cdk/api/v1/java/index.html?software/amazon/awscdk/services/eks/package-summary.html

### Use Case

If we can lookup any EKS cluster and get the appropriate return type (`Cluster` object in this use case), then we can use CDK to create the entire end-to-end infrastructure. Because of the current limitation I have to use deployment scripts using `eksctl` in order to interact and make changes to an EKS cluster.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.35.0

### Environment details (OS name and version, etc.)

CDK on Java

**Comment by peterwoodworth** [comment]
Imported resources cannot become part of your CDK app, and you cannot make changes to them. Please see our [documentation on this topic](https://docs.aws.amazon.com/cdk/v2/guide/resources.html#resources_external), and open a discussion if you have more questions.

**Comment by RonakShah92** [comment]
Hello Peter,

Thank you for your response.
Even if I use CDK L1 Construct to create the cluster (https://docs.aws.amazon.com/cdk/api/v2/java/index.html?software/amazon/awscdk/services/eks/CfnCluster.html), I cannot use this again as it will provide me CfnCluster within the stack and thus I have to do a lookup to work with the cluster. If there is way to get Cluster from CfnCluster directly then it would help resolved the problem as well.
Currently I cannot use the L3 construct Cluster as it creates some additional IAM resources on its own and we have an explicit deny for creation of any IAM resources by the services.

**Comment by pahud** [comment]
Hi @RonakShah92 

>then we can use CDK to create the entire end-to-end infrastructure

Nice ask. Can you tell me more details about what you intend to do? Technically, when you Cluster.fromClusterAttributes(), it returns an importedCluster as ICluster but not Cluster and this means all helper method binding to Cluster such as [addNodeGroupCapacity](https://github.com/aws/aws-cdk/blob/6d906f8f99d3adc38f3dd15390bd3118701f2f81/packages/aws-cdk-lib/aws-eks/lib/cluster.ts#L1722)() will not be available for this importedCluster unless those helper methods.

CDK allows you to import existing resources created outsides of CDK app by fromXxxx() methods but those imported resources will not be able to use the construct methods.

However, CDK allows you to create custom resources and technically you can create a custom resource that executes `eksctl` for you against any imported cluster. This might be something you could do in your end-to-end architecture.
