### ISSUE TITLE
aws-cdk-lib/aws-cloudwatch: ability to import dashboards via exported value

### ISSUE THREAD

**Issue by justinwiley** [aws/aws-cdk#25015]
### Describe the feature

Currently there doesn't seem to be a way to import dashboards created in other stacks using `cdk.Fn.importValue`.

### Use Case

Our Cloudwatch dashboards are created in one stack, and exported via `CfnOutput`.  We would like to have services add widgets to imported dashboards.  It's possible to expose the dashboard and pass it has a reference to the other stacks, but this leads to explicit, deploy-time coupling (i.e. stacks that consume the dashboard are deployed whenever the dashboard stack is updated, which often isnt the desired behavior).

### Proposed Solution

Implement `fromDashboardArn` similar to `s3.fromBucketArn`.

Export:

```
    this.dashboard = new Dashboard(this, 'some-dashboard', {
      dashboardName: 'SomeDashboard'
    })

    new CfnOutput(this, 'DashboardArn', {
      value: this.dashboard.dashboardArn
    })
```

Import and use:

```
    Dashboard.fromDashboardArn(this, 'imported-dashboard', cdk.Fn.importValue('SomeStack.Dashboard'));
```

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

^2.64.0

### Environment details (OS name and version, etc.)

mac os ventura

**Comment by peterwoodworth** [comment]
For importing a Dashboard to do anything, other constructs would need to assume an `IDashboard`. [Importing resources like this](https://docs.aws.amazon.com/cdk/v2/guide/resources.html#resources_external) is just creating a proxy for passing around data like the resource arn or name, which you can already do with import/export value. 

How were you thinking of using this imported dashboard?

**Comment by kisharma24** [comment]
keep it open, we are looking for a solution
