### ISSUE TITLE
(custom-resources): (use lambda.Runtime.NODEJS_18_X  by default in Provider)

### ISSUE THREAD

**Issue by rajaravi1** [aws/aws-cdk#25021]
### Describe the feature

Similar to https://github.com/aws/aws-cdk/issues/19117 we should update to latest supported Node.js runtime for the custom-resources lambda prior to Node 14 going eol. 

### Use Case

All lambdas created by aws-cdk internally should be updated prior to EOL.

### Proposed Solution

Update to NODEJS_18_X when creating lambda in custom-resources.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.29.1

### Environment details (OS name and version, etc.)

Mac 13.3.1 (22E261)

**Comment by pahud** [comment]
I am afraid we can't all in nodejs 18 for now. See https://github.com/aws/aws-cdk/pull/24725#issuecomment-1478310909

**Comment by peterwoodworth** [comment]
You've seemed to have exactly duplicated this issue https://github.com/aws/aws-cdk/issues/23682
