### ISSUE TITLE
python API reference: "latest" redirects to v1, rather than v2

### ISSUE THREAD

**Issue by cmooreamazon** [aws/aws-cdk#25038]
### Describe the issue

When viewing the CDK API Reference for Python, the "latest" path redirects to "v1" rather than "v2"

I would expect this link: https://docs.aws.amazon.com/cdk/api/latest/python/index.html

to redirect here: https://docs.aws.amazon.com/cdk/api/v2/python/index.html

but instead, it redirects here: https://docs.aws.amazon.com/cdk/api/v1/python/index.html

The same is true for all pages within, e.g.:

- https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_cloudwatch/Metric.html
- https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_sns/Subscription.html

### Links

https://docs.aws.amazon.com/cdk/api/latest/python/index.html

**Comment by peterwoodworth** [comment]
Thanks for letting us know

**Comment by rix0rrr** [comment]
Thanks for letting us know. Unfortunately, this is on purpose. The word `latest` was poorly chosen and is really not compatible with permanent hyperlinks. We are hesitant to move those links wholesale to point to `v2`, as that will break existing deeplinks. Just as an example:

```
https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_core.Stack.html   <-- exists
https://docs.aws.amazon.com/cdk/api/v2/docs/@aws-cdk_core.Stack.html   <-- does not exist
```

So we have a choice for the URL:

```
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.Stack.html
```

If we redirect `latest` -> `v2`, all existing hyperlinks to `Stack` break.
