### ISSUE TITLE
redshiftserverless.CfnWorkgroup: add support for VPC and subnets

### ISSUE THREAD

**Issue by melazarus** [aws/aws-cdk#25043]
### Describe the feature

Add VPC and subnet configuration to Redshift serverless.

Does not seem to be possible in the 2.72.1 version.

### Use Case

Setting up Redshift serverless by using only CDK.

### Proposed Solution

Add vpc and subnet properties.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.72.1

### Environment details (OS name and version, etc.)

ubuntu 22.04 (WSL2)

**Comment by pahud** [comment]
Hi

I didn't see VPC property but subnetId is supported  in [AWS::RedshiftServerless::Workgroup](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-redshiftserverless-workgroup.html) and in [CfnWorkshopProps](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_redshiftserverless.CfnWorkgroupProps.html#subnetids).


If you need an additional vpc prop, I would recommend create a feature request in [cloudformation coverage roadmap](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues) instead for more visibility. But I believe subnetId might be sufficient as subnets are associated to VPC.

**Comment by melazarus** [comment]
@pahud Thanks, that indeed sets the VPC to.

Thanks again. I'll close the request as it's not needed anymore.
