### ISSUE TITLE
(aws-auth): AWS_DEFAULT_REGION does not work with web identity credentials

### ISSUE THREAD

**Issue by GoGoris** [aws/aws-cdk#25082]
### Describe the bug

Follow up to discussion #19701 since this bug is still present in the latest version and poorly documented.

_Note: the bug is worsened by the fact that the bitbucket cloudformation pipe only supports AWS_DEFAULT_REGION_

### Expected Behavior

The deploy works when authentication using the AWS_ROLE_ARN, AWS_WEB_IDENTITY_TOKEN_FILE and AWS_DEFAULT_REGION environment variables.

### Current Behavior

When authenticating using AWS_ROLE_ARN, AWS_WEB_IDENTITY_TOKEN_FILE and AWS_DEFAULT_REGION, I receive the following error: ` ❌  Environment ***********/eu-west-1 failed bootstrapping: Error: Need to perform AWS calls for account ***********, but no credentials have been configured`
When I add `export AWS_REGION=$AWS_DEFAULT_REGION`, it works fine.

### Reproduction Steps

Deploy a cdk stack using AWS_ROLE_ARN, AWS_WEB_IDENTITY_TOKEN_FILE and AWS_DEFAULT_REGION.

### CDK CLI Version

2.73.0

### Node.js Version

18

### OS

linux

### Language

Typescript

**Comment by peterwoodworth** [comment]
Thanks for making an issue for this @GoGoris, I remember investigating this and being unable to reproduce or explain why our codebase would treat `AWS_DEFAULT_REGION` so differently from `AWS_REGION`.

Couple questions: 

1. are you using cloudformation bitbucket pipeline? If so, then this seems to be only affecting users in this use case
2. Could you please fill out your reproduction steps in much more detail? I've had trouble reproducing this and I need to be able to do so. Currently it says you're getting this error when deploying a CDK stack, but the error message you posted can only be thrown when bootstrapping

**Comment by GoGoris** [comment]
I started from a clean account so yes the error occurred during bootstrapping.
If you say it is only on bitbucket I will do some extra testing tomorrow or the day after to be sure it does not work when I deploy without bootstrapping or export AWS_DEFAULT_REGION directly because AWS_DEFAULT_REGION is a variable in my bitbucket pipeline repository variables.

**Comment by GoGoris** [comment]
I can confirm that both the bootstrap and the deploy command fail with AWS_DEFAULT_REGION instead of AWS_REGION.
Explicitly executing `export AWS_DEFAULT_REGION=eu-west-1` instead of relying on Repository Variables does not help.
This is the error: 
` ❌ Building assets failed: Error: Building Assets Failed: Error: Unable to resolve AWS account to use. It must be either configured when you define your CDK Stack, or through the environment`
But now that I don't bootstrap I get a different error so I will look tomorrow why it does not work without running cdk bootstrap first.

**Comment by hypostulate** [comment]
I'm running into the same issue and was also able to solve it by adding AWS_REGION on top of AWS_DEFAULT_REGION. AWS CLI commands worked fine, but CDK failed when using OIDC roles.

**Comment by astef** [comment]
If you experience non-determenistic "Unable to resolve AWS account to use" error, most likely it's this or related to this: https://github.com/aws/aws-cdk/issues/24744

**Comment by pahud** [comment]
Hi

I am here assisting this issue.

>Reproduction Steps
>Deploy a cdk stack using AWS_ROLE_ARN, AWS_WEB_IDENTITY_TOKEN_FILE and AWS_DEFAULT_REGION.

Are you able to provide more details about the steps with minimal required code snippets that I can reproduce this in my account?
