### ISSUE TITLE
VpcContextProvider does not allow importing VPC that have not been created via CDK

### ISSUE THREAD

**Issue by xelibrion** [aws/aws-cdk#2508]
**Describe the bug**

In my CDK app I'm attempting to import a VPC that has been created by another CloudFormation stack (that is not using CDK).

```
const vpc = ec2.VpcNetwork.importFromContext(this, 'ecs-vpc', {
        vpcName: props.vpcName,
      })
```

It did fail with a message 
```
Not all subnets in VPC have the same AZs: us-west-2b,us-west-2c vs us-west-2b,us-west-2b,us-west-2b,us-west-2b,us-west-2b,us-west-2b,us-west-2c,us-west-2c,us-west-2c,us-west-2c,us-west-2c,us-west-2c
```
The reason for that is the key for grouping subnets is `[subnet.type, subnet.name]`, where name is assumed as:
```
const name = getTag('aws-cdk:subnet-name', subnet.Tags) || type;
```
https://github.com/awslabs/aws-cdk/blob/master/packages/aws-cdk/lib/context-providers/vpcs.ts#L64

This is a pretty strong assumption, as in our case VPC that we want to reference has not been created via CDK.  

**To Reproduce**
Deploy stack with uneven number of subnets per type, i.e. 2 Public and 4 Private subnets. Make sure subnets don't have `aws-cdk:subnet-name` tag. Try importing the VPC. 

**Expected behavior**
VPC is imported and VpcNetwork object is created. 

**Version:**
 - OS: Mac OS
 - Programming Language: Typescript
 - CDK Version: 0.30.0

**Comment by RomainMuller** [comment]
Hey @xelibrion,

It looks like you're looking to import a VPC that does not have the features of the standard CDK VPC construct. At this stage, the CDK will not be able to map such a VPC to the API that the `IVpc` interface describes, which makes it an awkward proposition.

It appears this is in fact not a `bug`, but more of a `feature request`, in any case it would greatly help us if you could provide some of the specifics of the VPC you are looking to import here:
- What's your VPC's layout?
  + Subnets in each AZ, ... even obfuscated, so we can reproduce the setup)
- What's the desired behavior here?
  + How does your subnet map to the `IVpc` API?

Regards,
Romain.
