### ISSUE TITLE
(aws-ec2): Cannot create to InitFiles with same target file name

### ISSUE THREAD

**Issue by bpauwels** [aws/aws-cdk#25105]
### Describe the bug

Opening a new bug report for an already reported bug: https://github.com/aws/aws-cdk/issues/16891

Naming collision of InitFile constructs for multiple ec2 instances defined in the same stack definition when using the fromAsset or fromSource methods. Affected file: https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-ec2/lib/cfn-init-elements.ts. Cause is most likely due to the underlying InitFile fromAsset and fromSource methods creating an s3 asset with interpolated id of ${targetFileName}Asset.

This bug just occurred to me again. I think it should not be closed until fixed.

### Expected Behavior

One can create as many InitFiles as wanted with the same target file names

### Current Behavior

You cannot create more than one InitFile with the same target file name

### Reproduction Steps

Create more than one InitFile with the same target file name

### CDK CLI Version

2.67.0

### Node.js Version

16.19.1

### OS

amazon linux 2

### Language

Typescript, Python, .NET, Java, Go

**Comment by pahud** [comment]
Thank you for your report. Can you share a little CDK sample that we can quickly reproduce and verify it in our account?

**Comment by bpauwels** [comment]
Sure,

```
import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import {Vpc, Instance, InstanceType, InstanceClass, InstanceSize, AmazonLinuxImage,
  AmazonLinuxGeneration, CloudFormationInit, InitConfig, InitFile} from 'aws-cdk-lib/aws-ec2';

export class CdkIssue25105Stack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const vpc = new Vpc(this, "vpc");

    new Instance(this, "FirstInstance", {
      vpc,
      instanceType:
        InstanceType.of(InstanceClass.T3A, InstanceSize.MICRO),
      machineImage: new AmazonLinuxImage({
        generation: AmazonLinuxGeneration.AMAZON_LINUX_2,
      }),
      init: CloudFormationInit.fromConfigSets({
        configSets: {
          default: ["default"],
        },
        configs: {
          default: new InitConfig([
            InitFile.fromAsset(
              "/target/path/config.json",
              "configFileForFirstInstance.json"
            )
          ])
        },
      })
    });

    new Instance(this, "SecondInstance", {
      vpc,
      instanceType:
        InstanceType.of(InstanceClass.T3A, InstanceSize.MICRO),
      machineImage: new AmazonLinuxImage({
        generation: AmazonLinuxGeneration.AMAZON_LINUX_2,
      }),
      init: CloudFormationInit.fromConfigSets({
        configSets: {
          default: ["default"],
        },
        configs: {
          default: new InitConfig([
            InitFile.fromAsset(
              "/target/path/config.json",
              "configFileForSecondInstance.json"
            )
          ])
        },
      })
    });

  }
}
```


If I run `cdk synth` with this, I see the following error:
```
/path/to/cdk/project/node_modules/constructs/src/construct.ts:403
      throw new Error(`There is already a Construct with name '${childName}' in ${typeName}${name.length > 0 ? ' [' + name + ']' : ''}`);
            ^
Error: There is already a Construct with name '--target--path--config.jsonAsset' in CdkIssue25105Stack [CdkIssue25105Stack]
...
```

**Comment by peterwoodworth** [comment]
Thanks @bpauwels, I'm going to close this and reopen the original issue, as well as provide the context you've been able to provide to us 🙂
