### ISSUE TITLE
DBClusterParameterGroup not found: default.aurora5.6

### ISSUE THREAD

**Issue by mhuebner** [aws/aws-cdk#2512]
**Describe the bug**
My DatabaseCluster ist configured with `engine: rds.DatabaseClusterEngine.AuroraMysql` and no custom `ClusterParameterGroup` is configured.

The following Exception is thrown:

```DBClusterParameterGroup not found: default.aurora5.6 (Service: AmazonRDS; Status Code: 404; Error Code: DBClusterParameterGroupNotFound;```

**To Reproduce**
```
        new rds.DatabaseCluster(this, 'prodRdsCuster', {
            clusterIdentifier: 'rds-prod',
            engine: rds.DatabaseClusterEngine.AuroraMysql,
            instances: 1,
            port: 3306,
            defaultDatabaseName: 'app',
            masterUser: {
                username: 'admin'
            },
            instanceProps: {
                instanceType: new ec2.InstanceTypePair(ec2.InstanceClass.Burstable2, ec2.InstanceSize.Medium),
                securityGroup: rdsSecurityGroup,
                vpc: props.vpc,
                vpcSubnets: {
                    subnetType: ec2.SubnetType.Isolated,
                }
            },
            backup: {
                preferredWindow: '02:00-03:00',
                retentionDays: 21
            },
            preferredMaintenanceWindow: 'Sun:03:00-Sun:04:00'
        });
```

`cdk deploy`

**Expected behavior**
Successful deployment

**Version:**
 - OS: MacOS Moave
 - Programming Language: TypeScript
 - CDK Version: 0.31.0

**Workaround**
Create a ClusterParameterGroup with explicit family setting:

```
const rdsClusterPrameterGroup = new ClusterParameterGroup(this, 'rdsClusterPrameterGroup', {
            description: 'MySQL 5.7',
            family: 'aurora-mysql5.7'
}
```
and use it in your cluster with
```
parameterGroup: rdsClusterPrameterGroup

```

**Comment by jogold** [comment]
Also already experienced this.

I think this is a bug in RDS. The problem is that the `default.xxx` parameter groups (created by AWS) are created only after creating a instance/cluster in the console or using the API directly. So if you never created a instance/cluster this way in a region and you try to deploy with CloudFormation it will not find the `default.xxx` parameter group.

**Comment by joehillen** [comment]
@jogold Incorrect. I just launched a cluster with a default parameter group

```ts
    this.db = new DatabaseCluster(this, "Database", {
      engine: rds.DatabaseClusterEngine.AuroraPostgresql,
      engineVersion: "10.7",
      masterUser: {
        username: "admin",
      },
      defaultDatabaseName: "main",
      instanceProps: {
        instanceType: new ec2.InstanceType("r5.large"),
        vpcSubnets: {
          subnetType: ec2.SubnetType.Private,
        },
        vpc,
      },
      storageEncrypted: true,
      parameterGroup: {
        parameterGroupName: "default.aurora-postgresql10",
      } as any,
    });
```

**Comment by hoang-innomizetech** [comment]
@joehillen So how can we create a new parameter group and override some parameters rather using the default one? See below sample code

```
const parameterGroup = new ParameterGroup(this, 'ParameterGroup', {
      family: 'aurora-mysql5.7',
      parameters: {
        max_connections: '100'
      }
    });

```

I am getting the error as above

**Comment by pwrmiller** [comment]
If you need to do this in Python, to use the default parameter group for Aurora MySQL 5.7, use this: 

`pg = rds.ClusterParameterGroup.from_parameter_group_name(self, 'ParameterGroup', "default.aurora-mysql5.7")`

**Comment by machielg** [comment]
The bug is still present

**Comment by skinny85** [comment]
> The bug is still present

Yep. I can tell you I'm working on it right now. Stay tuned.

**Comment by saviour123** [comment]
The bug is still present in 2022. I just wanted to created a new resource via cloudformation in ap and this is the same error i got.

**Comment by itjuan** [comment]
> The bug is still present in 2022. I just wanted to created a new resource via cloudformation in ap and this is the same error i got.

In case you still have the issue. This is caused by parameter group versions been deprecated. You can still use the default parameter groups, you just need to find the available versions with `aws rds describe-db-engine-versions --query "DBEngineVersions[].DBParameterGroupFamily"`

Source: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbclusterparametergroup.html#cfn-rds-dbclusterparametergroup-family

**Comment by sushilatlabs** [comment]
I created test database using AWS console UI first, it created default `default.aurora-postgresql14` parameter group.
After this my CDK command started working with:
`
parameterGroup: ParameterGroup.fromParameterGroupName(
        this,
        "ParameterGroup",
        "default.aurora-postgresql13"
)
`

**Comment by tyler-rpi** [comment]
I faced this. I think the answer is somewhat concealed in the description of the [`parameters` props](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_rds.DatabaseCluster.html#parameters):

> You can only specify parameterGroup or parameters but not both. You need to use a versioned engine to auto-generate a DBClusterParameterGroup.

Using a version engine, rather than `DatabaseClusterEngine.AURORA_MYSQL`, solved the issue.
