### ISSUE TITLE
ApplicationLoadBalancedFargateService: Python Memory Variable incorrect

### ISSUE THREAD

**Issue by arjun921** [aws/aws-cdk#25128]
### Describe the issue

The example codeblock listed in documentation has the wrong variable in the code snippet for Memory

`memory_limit_mi_b` - Incorrect, does not work.
Throws error
```python
TypeError: __init__() got an unexpected keyword argument 'memory_limit_mi_b'
```
`memory_limit_mib` - Correct, works as expected.

I'm happy to fix it if someone can point me to the right file for this change. 

Thank you!

### Links

https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_ecs_patterns/ApplicationLoadBalancedFargateService.html

**Comment by btanand** [comment]
@khushail @arjun921 does this issue persist or has this been deprecated? I am trying to find the file that contains this issue, but I am not able to find it.

**Comment by peterwoodworth** [comment]
[We're tracking this in `jsii`](https://github.com/aws/jsii/issues/3516) - it's a codegen issue, we don't handwrite the python code nor docs
