### ISSUE TITLE
aws-events : Unable to Create Event Bus Archive with CDK

### ISSUE THREAD

**Issue by ravthiru** [aws/aws-cdk#25139]
### Describe the bug

Trying to create Event Archive for the Event Bus using CDK 

Tried following Options 

**Option 1** 

```
 let archiveProps: ArchiveProps = {
    eventPattern: {
      "source": ["com.example.idm", "com.example.ebs"]
    },
     description : "Archive IDM and EBS Events for 15 days",
     archiveName : "MyArchiveEvents",
     retention : Duration.days(15)
    }
 myEventBus.archive("Archive IDM and EBS Events for 15 days", archiveProps);
```

**Option 2**

```
const archive = new Archive(this, "ArchiveEventAdapterEvents",{
     sourceEventBus: myEventBus,
     eventPattern: {
       "source": ["com.example.idm", "com.example.ebs"]
     },
     description : "Archive IDM and EBS Events for 15 days",
     archiveName : "MyArchiveEvents",
     retention : Duration.days(15)
    });

```
Which is the right way to create archive for EventBus as none of them is working for me

### Expected Behavior

Archive should be reacted for the eventbus

### Current Behavior

Getting following Error while trying to create Event Archive

Resource handler returned message: "Error occurred during operation 'AWS::Events::Archive'

### Reproduction Steps

use CDK to Deploy the stack

### CDK CLI Version

2.31.1

### Node.js Version

1.18

### OS

linux

### Language

Typescript

**Comment by pahud** [comment]
I can deploy this with no error. Does it work for you?

```ts
const myEventBus = new events.EventBus(this, 'MyBus');

myEventBus.archive("MyArchive", {
  eventPattern: {
    "source": ["com.example.idm", "com.example.ebs"]
  },
  retention: Duration.days(15)
})
```

**Comment by ravthiru** [comment]
Thanks pahud,  I am still seeing same error with code you provided .

.../eventBus/eventBus/MyArchive/Archive (eventBusMyArchiveD7713FCD) Resource handler returned message: "Error occurred during operation 'AWS::Events::Archive'." (RequestToken: 8f8d71b7-4ed9-5e35-ff0c-df4b63eb57cb, HandlerErrorCode: GeneralServiceException)

**Comment by ravthiru** [comment]
I have also tried creating with , 

 new CfnArchive(this,'ArchiveEventAdapterEvents',{
  
       sourceArn: myEventBus.eventBusArn,
       archiveName: "ArchiveEventAdapterEvents",
       description: "Archive Events for 15 days",
       eventPattern: {
        "source": ["com.example.idm", "com.example.ebs"]
      },
      retentionDays: 15
    });

Getting same error and message is not useful

 **Resource handler returned message: "Error occurred during operation 'AWS::Events::Archive'**

**Comment by peterwoodworth** [comment]
The error message returned by the service isn't helpful here, they need to handle this better. I suspect either there's an issue with how you've configured the resource, or the resource already exists and you're running into errors because you've specified the physical name. Try not specifying the name and see if you get a successful deployment?

If this doesn't help, I recommend checking CloudTrail to see if the API logs show any helpful error messages. If not, I suggest opening a case with AWS support if you have it

Please ping me if you have any followups or concerns. Thanks!
