### ISSUE TITLE
How can I configure MySQL Community Edition?

### ISSUE THREAD

**Issue by mhuebner** [aws/aws-cdk#2513]
I am able to configure one of the following engines:
```
export declare enum DatabaseClusterEngine {
    Aurora = "aurora",
    AuroraMysql = "aurora-mysql",
    AuroraPostgresql = "aurora-postgresql",
    Neptune = "neptune"
}
```

Is there a way to configure MySQL?

**Comment by SomayaB** [comment]
Hi, I apologize for the late reply. Is this still a concern?

**Comment by SomayaB** [comment]
Closing this issue since there hasn't been activity on it for a while. Feel free to reopen if you would still like guidance on this.
