### ISSUE TITLE
ECS: Cloudmap service per container instead of service

### ISSUE THREAD

**Issue by Pucmaster** [aws/aws-cdk#25147]
### Describe the feature

Lets say that in order to save costs we want to have 2 containers inside of single fargate service. We want to have these two containers to be reachable with different paths via HttpApi utilizing ServiceDiscovery of CloudMap. Like In Picture
![image](https://user-images.githubusercontent.com/9165840/232430814-2728bbfe-00ba-418c-add1-9db0a1e4efa5.png)

It is possible to enable ServiceConnect and use created services insided of HttpApi integrations for proper routing. However its not possible to do that in CDK. You have no reference to CloudMap services created by ServiceConnect. Ive tried to create CloudMap association per container but it allows to create it for single container and you cannot create multiple associations to same ECS service.

### Use Case

Usage of differents path of Http Api to different containers inside of ECS Service

### Proposed Solution

In order to connect to containers inside of ecs service we should be able to create more association to ECS service via CloudMap. This wil helps with creating referencies of CloudMap services inside of Http Api integrations

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.74.0

### Environment details (OS name and version, etc.)

C# , HttpApi alpha

**Comment by pahud** [comment]
AFAIK, CloudMap with ECS is per-service and is primarily used for service discovery. Can you tell me how did you make it associated per container from a ECS service?
