### ISSUE TITLE
CDK Pipeline: No matching version found for cdk-assets@2.74.0.

### ISSUE THREAD

**Issue by vaneek** [aws/aws-cdk#25143]
### Describe the bug

There is no cdk-assets@2.74.0 package in the NPM repo, only 2.74.0-alpha.0.

Codebuild fails with the following message,

[Container] 2023/04/14 16:05:53 Entering phase INSTALL
--
19 | [Container] 2023/04/14 16:05:53 Running command npm install -g cdk-assets@2.74.0
20 | npm ERR! code ETARGET
21 | npm ERR! notarget No matching version found for cdk-assets@2.74.0.
22 | npm ERR! notarget In most cases you or one of your dependencies are requesting
23 | npm ERR! notarget a package version that doesn't exist.
24 |  
25 | npm ERR! A complete log of this run can be found in:
26 | npm ERR!     /root/.npm/_logs/2023-04-14T16_06_04_638Z-debug-0.log
27 |  
28 | [Container] 2023/04/14 16:06:06 Command did not exit successfully npm install -g cdk-assets@2.74.0 exit status 1
29 | [Container] 2023/04/14 16:06:06 Phase complete: INSTALL State: FAILED
30 | [Container] 2023/04/14 16:06:06 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: npm install -g cdk-assets@2.74.0. Reason: exit status 1

### Expected Behavior

success.

### Current Behavior

fails on missing package in NPM repo.

### Reproduction Steps

CDK Pipeline using CDK 2.74.0

### Possible Solution

add package to NPM

### CDK CLI Version

2.74.0

### Node.js Version

latest AL2 codebuild image

### OS

AL2

### Language

Python

### Language Version

any

**Comment by pahud** [comment]
Hi

>Running command npm install -g cdk-assets@2.74.0

What made it install `cdk-assets@2.74.0` from the CodeBuild?

**Comment by vaneek** [comment]
> Hi
> 
> > Running command npm install -g cdk-assets@2.74.0
> 
> What made it install `cdk-assets@2.74.0` from the CodeBuild?

Hi The basis is the CDK project structure for Python (https://github.com/aws-samples/aws-cdk-project-structure-python).
Updating the package.json to 2.74.0 cause the CDK Pipeline to run the install.
The versioning of the cdk-assets seems to have changed with versions 2.73.0 and 2.74.0 having the alpha extensions added. Looking at the NPM repo, prior versions did not do that.
