### ISSUE TITLE
NodejsFunction: Doesn't compile to esnext or es2022

### ISSUE THREAD

**Issue by ShivamJoker** [aws/aws-cdk#25145]
### Describe the bug

I am trying to compile the Typescript to ESM with ES2022 but I keep seeing var in my Lambda console.

![image](https://user-images.githubusercontent.com/23727670/232348533-b2a6cfff-c966-4cb7-820f-c1ec1e6fc23d.png)

### Expected Behavior

I should be able to compile the TypeScript files into ES2020+ and get rid of vars and older methods.

### Current Behavior

Unable to compile to the latest esm version

### Reproduction Steps

1. Create a CDK project
2. Use the following config to create lambda:

```js
new NodejsFunction(scope, name, {
    functionName: name,
    runtime: Runtime.NODEJS_18_X,
    memorySize: 512,
    bundling: {
      format: OutputFormat.ESM,
      target: "esnext",
      banner: `import { createRequire } from 'module';const require = createRequire(import.meta.url);`,
      tsconfig: "./lambda/tsconfig.json",
      ...bundling,
    },
    entry: `./lambda/${path}.ts`,
    // environment: env as Function["environment"],
    timeout: Duration.seconds(10),
    ...rest,
  });
```

### Possible Solution

Manually compile using esbuild and then normally use the compiled paths?

### CDK CLI Version

2.74.0 (build 70e2a33)

### Framework Version

2.74.0

### Node.js Version

16

### OS

Arch Linux

### Language

Typescript

### Language Version

~5.0.4

**Comment by pahud** [comment]
Thank you for your report. Can you share a little bit more about why you think it is not correctly compiled?

**Comment by ShivamJoker** [comment]
> Thank you for your report. Can you share a little bit more about why you think it is not correctly compiled?

I want it to use the current syntax of JavaScript instead of using var, it works but it's not what I want in my output.

It should give me let and const depending on my typescript source code.

**Comment by Tietew** [comment]
esbuild uses `var` intentionally.
- https://github.com/evanw/esbuild/issues/478
- https://github.com/evanw/esbuild/issues/1301
- https://github.com/evanw/esbuild/issues/2889

**Comment by ShivamJoker** [comment]
Oh, I see so it's the esbuild problem which will be fixed in the near future.

**Comment by peterwoodworth** [comment]
Thanks for providing context @Tietew, given this is related to esbuild I'm going to close this issue, unless there's something that needs to be done on our end when this is supported, but I don't believe that to be the case
