### ISSUE TITLE
(module name): (short issue description)

### ISSUE THREAD

**Issue by jazzblue** [aws/aws-cdk#25199]
### Describe the bug

`aws-cdk-aws-scheduler` is constrained to old version of the dependency `constructs` which causes dependency conflicts while installing:
```
ERROR: Cannot install -r jobs/malicious_domain_sandvine_feature_engineering/automation/requirements.txt (line 5) and automation_lib because these package versions have conflicting dependencies.

The conflict is caused by:
aws-cdk-lib 2.50.0 depends on constructs<11.0.0 and >=10.0.0
aws-cdk-aws-scheduler 1.198.1 depends on constructs<4.0.0 and >=3.3.69
```

### Expected Behavior

`aws-cdk-aws-scheduler` `consdtructs` dependency version should be updated to eliminate dependency conflicts.

### Current Behavior

`aws-cdk-aws-scheduler` is constrained to old version of the dependency `constructs` which causes dependency conflicts while installing

### Reproduction Steps

Use python and try to install:
```
aws-cdk-lib==2.50.0
aws-cdk-aws-scheduler
```

### CDK CLI Version

Does not matter

### Node.js Version

Does not matter

### OS

Does not matter

### Language

Python

### Language Version

3.7 or higher

**Comment by peterwoodworth** [comment]
```
The conflict is caused by:
aws-cdk-lib 2.50.0 depends on constructs<11.0.0 and >=10.0.0
aws-cdk-aws-scheduler 1.198.1 depends on constructs<4.0.0 and >=3.3.69
```
Please specify the proper version of aws-scheduler in your `requirements.txt` https://docs.aws.amazon.com/cdk/v2/guide/manage-dependencies.html#manage-dependencies-python

**Comment by jazzblue** [comment]
> ```
> The conflict is caused by:
> aws-cdk-lib 2.50.0 depends on constructs<11.0.0 and >=10.0.0
> aws-cdk-aws-scheduler 1.198.1 depends on constructs<4.0.0 and >=3.3.69
> ```
> 
> Please specify the proper version of aws-scheduler in your `requirements.txt` https://docs.aws.amazon.com/cdk/v2/guide/manage-dependencies.html#manage-dependencies-python

@peterwoodworth thank you for the prompt response. I actually tried both pinned version and unpinned and it gives the same error. I tried:
```
aws-cdk-lib==2.50.0
aws-cdk.aws-scheduler==1.198.1
```
1.198.1 is the latest aws-scheduler version.
It gives the same error.

**Comment by peterwoodworth** [comment]
You're mixing and matching versions, alpha modules need to be the same version as your core library (especially the same major version)

And since you're on v2 - you don't need to install scheduler at all. it's part of the core library
