### ISSUE TITLE
ECS: ContainerImage.fromAsset not working for the new versions of CDK

### ISSUE THREAD

**Issue by aritraplaygroundtech** [aws/aws-cdk#25195]
### Describe the bug

In the previous versions of the AWS CDK ECS service, We were directly able to upload the docker image inside any repository while creating an ELB-ECS construct.
Example code is shown below : 

```
springBootServiceTaskDefination.addContainer("testing",
    ContainerDefinitionOptions
    .builder()
    .containerName(serviceName)
    .image(ContainerImage.fromAsset("../app"))
    .essential(true)
    .memoryLimitMiB(512)
    .healthCheck(software.amazon.awscdk.services.ecs.HealthCheck.builder()
        .command(
            List.of("CMD-SHELL",
                "curl -f http://localhost:8080" +
                healthCheckPath +
                "|| exit 1"))
        .interval(Duration.seconds(30))
        .retries(5)
        .timeout(Duration.seconds(10))
        .startPeriod(Duration.seconds(200))
        .build())
    .portMappings(List
        .of(PortMapping.builder().containerPort(8080).build()))
    .logging(LogDriver.awsLogs(AwsLogDriverProps.builder()
        .logGroup(springBootEcsLogGroup)
        .streamPrefix("ecs")
        .build()))
    .build());
```

Currently, this snippet is failing for the **ContainerImage.fromAsset** because of the docker daemon not found.
with the command "cdk deploy -v", We are seeing the following logs:

Call failed: describeImages({"repositoryName":"cdk-hnb659fds-container-assets-<account-id>-eu-west-1","imageIds":[{"imageTag":"<sha54>"}]}) => The image with imageId {imageDigest:'null', imageTag:'ed82f2f56ed33625cfc0327fec183e8cf39240acf2077763b757b4521dcc9780'} does not exist within the repository with name 'cdk-hnb659fds-container-assets-<account-id>-eu-west-1' in the registry with id '<account-id>' (code=ImageNotFoundException)

And its failing with the error showing as : 

19:20:46] [66%] debug: docker tag cdkasset-<sha54> <account-id>.dkr.ecr.eu-west-1.amazonaws.com/cdk-hnb659fds-container-assets-<account-id>-eu-west-1:<sha54>
Error response from daemon: No such image: cdkasset-<sha54>:latest
[100%] fail: docker tag cdkasset-<sha54> <account-id>.dkr.ecr.eu-west-1.amazonaws.com/cdk-hnb659fds-container-assets-<account-id>-eu-west-1:<sha54> exited with error code 1: Error response from daemon: No such image: cdkasset-<sha54>:latest

CDK Version :  2.75.1 (build aa30a30)
Java Version : 
java 17.0.6 2023-01-17 LTS
Java(TM) SE Runtime Environment (build 17.0.6+9-LTS-190)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.6+9-LTS-190, mixed mode, sharing)

### Expected Behavior

Docker Image should be created and uploaded to the ECR repository. Currently, We need to manually upload the using the command : 

docker build -t <account-id>.dkr.ecr.eu-west-1.amazonaws.com/cdk-hnb659fds-container-assets-<account-id>-eu-west-1:<sha256> --push .

### Current Behavior

failing with the error showing as : 

19:20:46] [66%] debug: docker tag cdkasset-<sha54> <account-id>.dkr.ecr.eu-west-1.amazonaws.com/cdk-hnb659fds-container-assets-<account-id>-eu-west-1:<sha54>
Error response from daemon: No such image: cdkasset-<sha54>:latest
[100%] fail: docker tag cdkasset-<sha54> <account-id>.dkr.ecr.eu-west-1.amazonaws.com/cdk-hnb659fds-container-assets-<account-id>-eu-west-1:<sha54> exited with error code 1: Error response from daemon: No such image: cdkasset-<sha54>:latest

### Reproduction Steps

attach this code contruct to any java cdk application and run "cdk deploy"

```
springBootServiceTaskDefination.addContainer("testing",
    ContainerDefinitionOptions
    .builder()
    .containerName(serviceName)
    .image(ContainerImage.fromAsset("../app"))
    .essential(true)
    .memoryLimitMiB(512)
    .healthCheck(software.amazon.awscdk.services.ecs.HealthCheck.builder()
        .command(
            List.of("CMD-SHELL",
                "curl -f http://localhost:8080" +
                healthCheckPath +
                "|| exit 1"))
        .interval(Duration.seconds(30))
        .retries(5)
        .timeout(Duration.seconds(10))
        .startPeriod(Duration.seconds(200))
        .build())
    .portMappings(List
        .of(PortMapping.builder().containerPort(8080).build()))
    .logging(LogDriver.awsLogs(AwsLogDriverProps.builder()
        .logGroup(springBootEcsLogGroup)
        .streamPrefix("ecs")
        .build()))
    .build());
```

### CDK CLI Version

2.75.1 (build aa30a30)

### Node.js Version

v19.8.1

### OS

Mac OS Ventura

### Language

Java

**Comment by peterwoodworth** [comment]
Which version did you start noticing this on, did it stop working on `2.72.0` by any chance? The only change we made here recently is specifying `e: any` instead of just `e` on line 195. Maybe this is causing some weirdness in Java? Will try to investigate

**Comment by peterwoodworth** [comment]
I'm not able to reproduce this on latest version. Could you please supply more info? I'd like to know the version you updgraded from, and if going back to that version makes the error go away. Additionally, does creating a new project on latest version still make the error persist with a minor reproduction? I'd very much appreciate if you could find out how to minimally reproduce this in a fresh project and provide that code for me

**Comment by aritraplaygroundtech** [comment]
Yes, i could see stopped working the current version. 
Here is the **java** version : 
java 17.0.6 2023-01-17 LTS
Java(TM) SE Runtime Environment (build 17.0.6+9-LTS-190)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.6+9-LTS-190, mixed mode, sharing)
Here is the **cdk** version:
2.75.1 (build aa30a30)
Here is the **node** version:
v19.8.1

Full Code Version for the solution construct:




 `       final TaskDefinition springBootServiceTaskDefination = TaskDefinition.Builder
                .create(scope, "springBoot-service-demo-task-defination-fargate-service")
                .memoryMiB("512")
                .cpu("256")     .runtimePlatform(RuntimePlatform.builder().cpuArchitecture(CpuArchitecture.ARM64).operatingSystemFamily(OperatingSystemFamily.LINUX).build())
                .compatibility(Compatibility.FARGATE)
                .networkMode(NetworkMode.AWS_VPC)
                .executionRole(springBootTaskExecutionRole)
                .taskRole(springBootTaskRole)
                .build();

        springBootServiceTaskDefination.addContainer("springBootFargateContainerDefination", ContainerDefinitionOptions
                .builder()
                .containerName(serviceName)
                .image(ContainerImage.fromAsset("../app/"))
                .essential(true)
                .memoryLimitMiB(512)
                .healthCheck(software.amazon.awscdk.services.ecs.HealthCheck.builder()
                        .command(
                                List.of("CMD-SHELL", "curl -f http://localhost:8080" + healthCheckPath + "|| exit 1"))
                        .interval(Duration.seconds(30))
                        .retries(5)
                        .timeout(Duration.seconds(10))
                        .startPeriod(Duration.seconds(200))
                        .build())
                .portMappings(List.of(PortMapping.builder().containerPort(8080).build()))
                .logging(LogDriver.awsLogs(AwsLogDriverProps.builder()
                        .logGroup(springBootEcsLogGroup)
                        .streamPrefix("ecs")
                        .build()))
                .build());

        // Add the Cloudwatch Agent 

        springBootServiceTaskDefination.addContainer("SpringbootFargateContainerDefinationCloudwatchAgent", ContainerDefinitionOptions
                .builder()
                .containerName(cdkOtelAppName)
                .image(ContainerImage.fromRegistry("public.ecr.aws/cloudwatch-agent/cloudwatch-agent:latest"))
                .essential(true)
                .memoryLimitMiB(512)
                .secrets(Collections.singletonMap("CW_CONFIG_CONTENT", Secret.fromSsmParameter(logsConfigParameter)))
                .logging(LogDriver.awsLogs(AwsLogDriverProps.builder()
                        .logGroup(LogGroup.Builder.create(scope, id+"-ecs-service-cw-log-group")
                        .logGroupName("/ecs/ecs-cwagent-ec2-"+id)
                        .retention(RetentionDays.TWO_WEEKS)
                        .removalPolicy(RemovalPolicy.DESTROY)
                        .build())
                        .streamPrefix("ecs")
                        .build()))
                .build());
`

**Comment by aritraplaygroundtech** [comment]
The current implementation is manually run docker run command to upload the image tag and run **cdk deploy** again.

**Comment by peterwoodworth** [comment]
I'm still unable to reproduce this. Could you please be as specific as possible with regards to your upgrade, and if any other changes were made? 

Which version did you upgrade from?
Does reverting to that version make the error go away?
Do you still run into the error if you try reproducing this on a fresh project on latest version?

**Comment by aritraplaygroundtech** [comment]
I will try out it from a fresh project
