### ISSUE TITLE
Add warning on `addContainer` if container resource limits exceed task-size limits

### ISSUE THREAD

**Issue by SoManyHs** [aws/aws-cdk#2520]
Currently, a deployment will fail if the cpu/memory limits set on a container exceed those specified at the Task Definition level (both Fargate and ECS). Rather than auto-adjusting the task size, we will add a client-side warning if a container is added to a task definition whose resource limits exceeds that of the task definition.

Related: #1553

**Comment by pkandasamy91** [comment]
Closing this Issue. CPU and Memory can both be tokens, at which point, we cannot perform any validation. In that case, it does not add any benefit to have inconsistent behaviour if it only fails when cpu and memory are concrete strings/numbers, but succeeds when they're tokens.

**Comment by pkandasamy91** [comment]
Reopening issue.
