### ISSUE TITLE
eks: use lambda.Runtime.PYTHON_3_9 by default in kubectl-provider

### ISSUE THREAD

**Issue by jarthur-scottlogic** [aws/aws-cdk#25213]
### Describe the feature

When creating a KubernetesManifest, a KubectlProvider is created that uses PYTHON_3_7 in its lambda. This should be upgraded to PYTHON_3_9.

https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-eks/lib/kubectl-provider.ts#L138

### Use Case

All lambdas created by aws-cdk internally should be updated prior to EOL.

### Proposed Solution

Update to PYTHON_3_9 when creating lambda in kubectl-provider

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.69.0

### Environment details (OS name and version, etc.)

Windows 10 Enterprise, 21H2, 19044.2728

**Comment by pahud** [comment]
Yes we should bump the version upgrade before the EOL. I am making this p1 and the core team will evaluate it based on region availability. We will need to ensure all regions have python3.9 runtime before we bump this. Thank you for the report.

**Comment by watany-dev** [comment]
I'll update to python 3.10.

**Comment by pahud** [comment]
related to https://github.com/aws/aws-cdk/pull/27031

**Comment by pahud** [comment]
It should be 3.10 now. Let me know if it isn't.

https://github.com/aws/aws-cdk/blob/b196b13b0b8a54dcacadf87fdbe744772a6e6c4d/packages/%40aws-cdk/custom-resource-handlers/lib/custom-resources-framework/config.ts#L179
