### ISSUE TITLE
s3: adding additional statements after initial BucketPolicy is not appended, when using `add_to_resource_policy`

### ISSUE THREAD

**Issue by Rizxcviii** [aws/aws-cdk#25218]
### Describe the bug

When creating an initial bucket policy for an S3 bucket, additional statements added thereafter will not appear in Cloudformation. This is especially apparent when using `add_to_resource_policy` or using the underlying function `example_bucket.policy.document.add_statements`. 

### Expected Behavior

Given the following:
```py
bucket = s3.Bucket(
    self,
    id="ExampleBucket",
    bucket_name="ExampleBucket",
    enforce_ssl=True # will be attached as a bucket policy
    ...
)
```
When a developer adds on additional bucket policy statements, they should be appended to the bucket.
```py
bucket.add_to_resource_policy(
    iam.PolicyStatement(
        sid="TLSVersion",
        principals=[iam.AnyPrincipal()],
        actions=["s3:*"],
        effect=iam.Effect.DENY,
        resources=[bucket.bucket_arn, bucket.arn_for_objects("*")],
        conditions={"NumericLessThan": {"s3:TlsVersion": tls_version}},
    )
)
```
Multiple statements to be appended to the Bucket Policy, after initially creating one.
```json
 {
    "ExampleBucketPolicy61C50A52": {
   "Type": "AWS::S3::BucketPolicy",
   "Properties": {
    "Bucket": {
     "Ref": "ExampleBucket0C3EE094"
    },
    "PolicyDocument": {
     "Statement": [ // with all policies added on
        "enforce_ssl statement goes here",
        "TLSVersion statement goes here"
     ],
     "Version": "2012-10-17"
    }
   }
  }
}
```

### Current Behavior

Only the initial policy statement will be added to the Cloudformation template
```json
 {
    "ExampleBucketPolicy61C50A52": {
   "Type": "AWS::S3::BucketPolicy",
   "Properties": {
    "Bucket": {
     "Ref": "ExampleBucket0C3EE094"
    },
    "PolicyDocument": {
     "Statement": [ // only the initialised policy is added.
        "enforce_ssl statement goes here",
     ],
     "Version": "2012-10-17"
    }
   }
  }
}
```

### Reproduction Steps

```py
bucket = s3.Bucket(
    self,
    id="ExampleBucket",
    bucket_name="ExampleBucket",
    enforce_ssl=True # will be attached as a bucket policy
    ...
)
bucket.add_to_resource_policy(
    iam.PolicyStatement(
        sid="TLSVersion",
        principals=[iam.AnyPrincipal()],
        actions=["s3:*"],
        effect=iam.Effect.DENY,
        resources=[bucket.bucket_arn, bucket.arn_for_objects("*")],
        conditions={"NumericLessThan": {"s3:TlsVersion": tls_version}},
    )
)
```

### Possible Solution

Potentially by lazily evaluating the `PolicyDocument` key within BucketPolicy construct. This could evaluate the bucket policy after synthesis. 

### CDK CLI Version

2.76.0

### Node.js Version

v16.16.0

### OS

Amazon Linux 2

### Language

Python

### Language Version

Python (3.7.16)

**Comment by khushail** [comment]
Hi @Rizxcviii , thanks for reaching out. I am able to see the updated template and hence policy statements after invoking `addToResourcePolicy` in the code (used typescript). Here is my code -

```
    const examplebucket = new s3.Bucket(this, "testbucket",{
      bucketName : "examplebucket",
      enforceSSL: true,
      versioned: true,
      transferAcceleration: true,
      removalPolicy: RemovalPolicy.RETAIN,
    });

    examplebucket.addToResourcePolicy(
      new PolicyStatement({
        resources: ['*'],
        principals: [new AnyPrincipal()],
        actions:["s3:Get*", "s3:Put*"],
        effect: Effect.ALLOW
      })
    );
```

However there are some restrictions on permissions being added to existing bucket which I could share with you. Please refer to [this](https://github.com/aws/aws-cdk/tree/main/packages/aws-cdk-lib/aws-s3#permissions). Let me know if this is helpful. Also could you please try running the code from scratch and see if that solves the issue. Please feel free to reach out.

**Comment by Rizxcviii** [comment]
Yes, my apologies. This was an issue on my end.
