### ISSUE TITLE
custom-resource: Expose removalPolicy for AwsCustomResource

### ISSUE THREAD

**Issue by iRoachie** [aws/aws-cdk#25220]
### Describe the feature

There's currently no way to set `removalPolicy` on `AwsCustomResource` even though the underlying construct `CustomResource` supports it.

### Use Case

Was raised in a discussion in the #aws-cdk channel in the cdk.dev slack. https://cdk-dev.slack.com/archives/C018XT6REKT/p1681939784829589

### Proposed Solution

Add `removalPolicy` as a parameter on `AwsCustomResource` 

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.76.0

### Environment details (OS name and version, etc.)

Mac 13.3.1

**Comment by pahud** [comment]
Makes sense to me. Can you provide the link to the slack discussion thread in `Use Case`? And thank you for your PR btw.

**Comment by iRoachie** [comment]
Sure thing, comment updated
