### ISSUE TITLE
CDK Deploy: s3:PutBucketPolicy Access Denied when deploying static site

### ISSUE THREAD

**Issue by h5aaimtron** [aws/aws-cdk#25231]
### Describe the bug

I had a deployment that was working and then it became corrupted due to a redeployment mistake. Now when attempting to deploy the cdk post-clean up, I get an error API: s3:PutBucketPolicy Access Denied which triggers the rest of the stack to fail.

### Expected Behavior

The app to deploy like it did the first time.

### Current Behavior

API: s3:PutBucketPolicy Access Denied

### Reproduction Steps

Not entirely sure. Deploy an app/stack that creates a static site. Change a few names on the Ids and deploy again causing the stack to mess up. Destroy/delete the stack and try to redeploy?

### Possible Solution

I wish I knew. The role the deploy command utilizes as AdminAccess attached so it should just work.

### CDK CLI Version

2.69

### Node.js Version

16

### OS

Windows 10

### Language

Typescript

**Comment by h5aaimtron** [comment]
Forgot they were applying the Block all by default on S3 buckets in April.

**Comment by 0xdevalias** [comment]
For anyone else who ends up here, you may want to look at the following for solutions/workarounds:

- https://github.com/aws/aws-cdk/issues/25358
- https://github.com/aws/aws-cdk/issues/25983
- https://www.reddit.com/r/aws/comments/12tqqpw/aws_cdk_api_s3_putbucketpolicy_access_denied_and/
