### ISSUE TITLE
aws-s3: grantReadWrite() does not grant kms key access for bucket objects created with s3.bucket.fromBucketArn()

### ISSUE THREAD

**Issue by NadimNadimNadimNadimNadim** [aws/aws-cdk#25238]
### Describe the bug

When obtaining the reference to an S3 bucket that uses an KMS key using `Bucket.fromBucketArn()`, and then trying to grant read/write access to an `IGrantable` using `IBucket.grantReadWrite()`, the `IGrantable` does not obtain any permissions to the KMS key.

### Expected Behavior

I expect the `IGrantable` to receive the necessary KMS permissions to read from and write to the S3 bucket that is using a KMS key.

### Current Behavior

No KMS permissions are granted.

### Reproduction Steps

```
import * as s3 from 'aws-cdk-lib/aws-s3';

const myBucket = s3.Bucket.fromBucketArn(this, 'my-bucket', 'arn:aws:s3:::myBucketArn');
const myGlueRole = new iam.Role(this, 'glue-role', {assumedBy: new iam.ServicePrincipal('glue.amazonaws.com')});
myBucket.grantReadWrite(myGlueRole);
```

### CDK CLI Version

2.17.0

### Node.js Version

v18.15.0

### OS

Amazon Linux 2

### Language

Typescript

### Language Version

4.0.5

**Comment by peterwoodworth** [comment]
Since you're importing the bucket you need to specify the Key when importing from attributes so that CDK knows there's a key associated with the Bucket. Here's what you'll want to do to grant permissions related to the key:

```ts
    const b = s3.Bucket.fromBucketAttributes(this, 'Bucket', {
      bucketArn: 'arn:aws:s3:::website-bucket',
      encryptionKey: kms.Key.fromKeyArn(this, 'Key', 'arn:aws:kms:us-east-1:123456789012:key/1b2b3b4b-5b6b-7b8b-9b0b-1b2b3b4b5b6b'),
    });

    const role = new iam.Role(this, 'Role', {
      assumedBy: new iam.ServicePrincipal('cloudfront.amazonaws.com'),
    })

    b.grantReadWrite(role);
```
