### ISSUE TITLE
(module name): (short issue description)

### ISSUE THREAD

**Issue by Arpisrinivas** [aws/aws-cdk#25236]
### Describe the feature

 I would like to update the verification message of an existing user pool through CDK. Currently, I am able to create a verification message for a new user pool, but I need to update an existing user pool's verification message.

### Use Case

The reason I need this feature is that updating an existing user pool's verification message manually through the AWS Management Console can be time-consuming and prone to human error. With the ability to update the verification message through CDK, it would allow for a more streamlined and automated process, making it easier for developers to manage and maintain their user pools. This would save time and reduce the potential for errors, leading to a more efficient and effective development process.

### Proposed Solution

const verificationMessageTemplateProperty: cognito.CfnUserPool.VerificationMessageTemplateProperty = {
      emailSubject: 'Welcome to Office!!!',
      emailMessage: `
    <html>
      <body>
        <h3 style="color: #2e6c80;">Welcome to Office!!!</h3>
        <p>Your Company verification code.</p>
        <p>verification code : {####}</p>
        <br />
        <br />
        <p>If you are not the intended recipient, you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited.</p>
        <br />
        <p>{##customMessage##}</p>
      </body>
    </html>
  `,
      smsMessage: 'Welcome to Office! Your verification code is {####}',
    };

    const userPool = cognito.UserPool.fromUserPoolId(this, 'UserPoolProtected', 'ap-south-1_KRPoD9MAk');

    const cfnUserPool = userPool.node.defaultChild as cognito.CfnUserPool;
    cfnUserPool.addPropertyOverride('VerificationMessageTemplate', verificationMessageTemplateProperty);

    new cognito.CfnUserPool(this, 'UserPoolProtected', {
      userPoolName: 'producerUserRoutes',
      verificationMessageTemplate: verificationMessageTemplateProperty
    });
  }
}

### Other Information

By the above code I am not able to update the existing user pool, insted  It is creating new user pool

I want to update the existing user pool

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.75.0 (build 37c53d6)

### Environment details (OS name and version, etc.)

Windows

**Comment by peterwoodworth** [comment]
You cannot directly modify resources not controlled through CDK/CloudFormation. To modify an existing user pool with CDK you will need to implement a custom resource, or utilize [AwsCustomResource](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.custom_resources.AwsCustomResource.html) if all you need to make is an API call

If you need more help, please feel free to open a discussion and ping me.

**Comment by Arpisrinivas** [comment]
Thank you for your message. As you mentioned, I am using a custom resource to modify the existing user pool in CDK.  Can you provide guidance on how to update an existing user pool in AWS? specially on email template

I appreciate your willingness to keep this case open until the issue is resolved to my satisfaction.

**Comment by Arpisrinivas** [comment]
Hey, 
I am waiting for your response

**Comment by peterwoodworth** [comment]
> As you mentioned, I am using a custom resource to modify the existing user pool in CDK. Can you provide guidance on how to update an existing user pool in AWS?

I'm not really sure what you mean by this. Could you elaborate on what you need guidance on specifically? If you're implementing the custom resource with CDK then you're good to go.

**Comment by BBopanna** [comment]
@peterwoodworth - to be specific - We have an Amplify project, to which we added auth category/service using "amplify add auth" and now after X days we want to update the auth (userpool config) which was added earlier by loading the auth service via the cdk (again added as custom category) and updating the properties of auth/userpool - IS IT POSSIBLE ?
