### ISSUE TITLE
Find Subnet by Tag or Name within publicSubnets, privateSubnets or isolatedSubnets of given VPC

### ISSUE THREAD

**Issue by mhuebner** [aws/aws-cdk#2523]
It would be very helpful to be able to select / find Subnets by name within a given VPC.
Currently there seems not to be a solution for this.

So perhaps `IVpcSubnet` might have a property `name`?

**Comment by rix0rrr** [comment]
Not for individual subnets, but it is possible for subnet groups.

**Comment by cweidinger** [comment]
+1 We just ran into this issue. We are having to hardcode subnetIds to the SubnetSelection for albs and ec2. It's not very much fun per level and account.

**Comment by dlynam01** [comment]
+1 , We've run into this so many times, generally have to inject the ids into the pipeline to avoid it

**Comment by awsluke** [comment]
+1 painful when dealing with subnets created outside CDK.

**Comment by vinayak-kukreja** [comment]
Hey, @mhuebner , @cweidinger, @dlynam01, and @awsluke, could you please explain the use case that this feature would help you out with? 
Providing us with example code snippets of where you could potentially use this feature would really help us.

**Comment by maggoun** [comment]
We want it because our subnet names will never change but the id's can if they are recreated, we would like to have the ability to search by the name.

**Comment by ash-rwt** [comment]
Has anyone worked on it?
I can give a classic example on the use case: I have 10 different subnets in a VPC, and I want to use specific subnets have tag in its name. Basically I want to have capability of filtering by name instead of statically passing subnetIds

**Comment by mMeijden** [comment]
+1
