### ISSUE TITLE
aws_batch_alpha: JobQueue uses wrong id for underlying CfnJobQueue

### ISSUE THREAD

**Issue by diego-santacruz** [aws/aws-cdk#25248]
### Describe the bug

With the new API in `aws_batch_alpha` the `node.defaultChild` property no longer returns the underlying `CfnJobQueue`.

I tracked this to the fact that instead of using `'Resource'` as the `id` for the `CfnJobQueue` created in https://github.com/aws/aws-cdk/blob/046d0fce6904521eb4d22bf0fb69afe5cef139be/packages/%40aws-cdk/aws-batch-alpha/lib/job-queue.ts#L181 the `id` of the parent `JobQueue` is used. Before rewriting `JobQueue` for the new API it was `'Resource'`.

This also has the effect that the logical ID of a JobQueue changed with the new API, although there was no reason for it.

### Expected Behavior

`JobQueue`'s `node.defaultChild` property returns the underlying `CfnJobQueue`.

### Current Behavior

`JobQueue`'s `node.defaultChild` property returns `undefined`.

### Reproduction Steps

Trivial

### Possible Solution

Use the usual `'Resource'` string as the `id` for the `CfnJobQueue`.

### CDK CLI Version

2.76

### Framework Version

2.76

### Node.js Version

v16.18.1

### OS

Linux

### Language

Typescript

### Language Version

4.9.5

**Comment by peterwoodworth** [comment]
Makes sense, thanks for reporting. @comcalvi do we want to change the id to `Resource`, or should we manually set the `CfnJobQueue` as the default child of this construct?

**Comment by daschaa** [comment]
Should this be feature-flagged?

**Comment by diego-santacruz** [comment]
My opinion is that given that this a change recently introduced (2.74) in an experimental package, and that apparently there are not many users of this new package version given the number of bugs that I've found for ECS on EC2 and that had not been reported yet I think not many people will care or notice the change if released soon. So I would not put it behind a feature flag.

**Comment by peterwoodworth** [comment]
I don't think it needs to be behind a feature flag simply because this is not a stable package yet
