### ISSUE TITLE
core: allow writing and interacting with Project CDK Context in app code

### ISSUE THREAD

**Issue by rnag** [aws/aws-cdk#25244]
### Describe the feature

I am already using a custom context variable -- let's call it `my-context`. User passes it in to cdk with `-c my-context=value`.

In cases where this context variable is not passed in, I want to auto-determine it based on the AWS account number.

This part is easy enough - to get the AWS account id, I can do something like this (in Typescript):
```ts
import { DEFAULT_ACCOUNT_ENV } from 'aws-cdk-lib/cx-api';

export const CDK_ACCOUNT = process.env[DEFAULT_ACCOUNT_ENV]!;
```

of course, the actual process to determine the context value based on the AWS account, is a bit more involved and time-consuming, let's say. That is, it's not as instantaneous as reading a single file, or reading from `process.env` for example.

Therefore, I want to store this context so that I can easily access it for next time. I am not sure of best place to store it, but I know that the context info isn't secret or confidential in any manner, so it can be committed to version control, no problemo. 

Thus, I believe best use case for this workload is the project-level `cdk.context.json` file. 

### Request

My ask here is, is it currently possible within user or CDK app code to save or "persist" a context variable to a local disk drive, i.e. so that CDK can pick it up on a next run?

I want to save it to project-level `cdk.context.json` file. I tried to investigate and look into the code of how `aws-cdk-lib` is implemented and how it reads and writes to this file, but I don't have any luck in understanding the codebase. I am sorry about that -- not really sure where to start, or where to discover the core logic which interacts with the project-specific CDK context, as mentioned above.

However, I have working code -- this is my attempt below at putting together a helper function to update the `cdk.context.json` file, in TypeScript. Let me know the thoughts or how it can be improve. Ideally, I will like to see CDK support this out of the box -- I truly feel it's an exciting use case!

```typescript
import { readJSON, writeJSON } from 'fs-extra';
import { join } from 'path';

let cdkContextConfig: {};

/**
 * Updates the `cdk.context.json` with new config.
 *
 * @param config Updated config for the CDK Context file.
 */
export const writeCdkContext = async (config: any) => {
    const cdkContextPath = join(__dirname, '..', 'cdk.context.json');
    if (!cdkContextConfig) {
        try {
            cdkContextConfig = await readJSON(cdkContextPath);
        } catch (e: any) {
            if (e.code === 'ENOENT') cdkContextConfig = {};
            else throw e;
        }
    }

    if (Object.keys(cdkContextConfig).length)
        cdkContextConfig = { ...cdkContextConfig, ...config };
    else cdkContextConfig = config;

    await writeJSON(cdkContextPath, cdkContextConfig, {
        spaces: 4,
    });
};
```

Usage in my `bin/app.ts` file, is something similar to this -- including a lot of pseudo code:

```typescript
    if { the context value was passed in to cdk }:
           // we all good!
    else:
        const defaultVal = `default-context:account=${CDK_ACCOUNT}`;
        value = app.node.tryGetContext(defaultVal);

        if (!!value) 
            // the context value exists in `cdk.context.json`. we all good! caching FTW!
        else {
            value = doExpensiveStuffToDetermineContextValueToCache()
            await writeCdkContext({
                [defaultVal]: value,
            });
        }
```

Hopefully this helps! I am excited to learn more about how I can use CDK to read/write from project context values located at `cdk.context.json` directly, and what are best practices of how I can incorporate this in my code. I believe the helper function `writeCdkContext` I came up with above is a good head start to this, and I will like to know if this is natively supported in CDK currently.

And if not, I will certainly like to request or propose such a feature request! I think it will be cool to expose this functionality so that basically and long story short, **caching == good**. 

Thanks, and let me know if there's any other info I can provide, and would be glad to do so!

### Use Case

Already addressed above. In app code, I want to basically do expensive operaiton and cache context value into project `cdk.context.json` file.

### Proposed Solution

See above

### Other Information

N/a

### Acknowledgements

- [ ] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### CDK version used

2.76.0 (build 78c411b)

### Environment details (OS name and version, etc.)

Mac OS X (M1 chip, Ventura)

**Comment by peterwoodworth** [comment]
I'm not sure I understand your exact requirements, I'd like to understand them first

> In cases where this context variable is not passed in, I want to auto-determine it based on the AWS account number.

What exactly do you want to auto-determine? Do you want to have each context variable to have a different value depending on the environment you're in? If so, you can already do this like so:

```
my-context:account=123456789012:region=eu-central-1
```

> of course, the actual process to determine the context value based on the AWS account, is a bit more involved and time-consuming, let's say

I'm not exactly sure what you mean by this 😅 

If you haven't already, I suggest reading our [guide on context values](https://docs.aws.amazon.com/cdk/v2/guide/context.html), you may learn something new 🙂
