### ISSUE TITLE
aws-cdk-lib: incremental build takes a few minutes every time

### ISSUE THREAD

**Issue by tmokmss** [aws/aws-cdk#25255]
### Describe the bug

As a CDK contributor, when using `yarn watch` in the `aws-cdk-lib` directory, it takes about 3 minutes to build ts files incrementally, resulting in bad developer experience.

Please let us know if there are better ways other than `yarn watch` for faster development iteration (write->build->test) 😃 

### Expected Behavior

Incremental build should finish in a few seconds, which was achieved in the previous package structure.

### Current Behavior

Incremental build takes a few minutes.

### Reproduction Steps

```
cd packages/aws-cdk-lib
yarn watch
# change some file and trigger an incremental build
```

### Possible Solution

I'm not sure why it is so slow yet. Just creating this issue for visibility.

Maybe the package is just very large and we need to split it into multiple ones (like the previous structure). c.f. [tsc doc](https://github.com/microsoft/TypeScript/wiki/Performance#existing-code).

Or maybe we can use faster compiler (without type check) like esbuild as an alternative for local development.

### Additional Information/Context

yarn watch on `framework-integ` also takes 10 to 20 seconds on every incremental build. It is acceptable for now but will possibly raise a similar problem in the future.

### CDK CLI Version

2.76.0

### Node.js Version

v18.13.0

### OS

macOS

### Language

Typescript

**Comment by pahud** [comment]
related to #25196

**Comment by MrArnoldPalmer** [comment]
Hey, working on some optimizations now. For now I would recommend using `npx tsc --watch` for MOST workflows as it's significantly faster (on my machine less than 10 seconds between compiles). There are some tests that rely on transforms that JSII provides but they are pretty niche so most people won't need them.

**Comment by ashishdhingra** [comment]
@tmokmss Closing this issue since the related issue https://github.com/aws/aws-cdk/issues/25196 is now closed. Feel free to reopen in case this issue still needs traction.
