### ISSUE TITLE
aws_batch_alpha: instance role for ManagedEc2EcsComputeEnvironment missing managed policy

### ISSUE THREAD

**Issue by diego-santacruz** [aws/aws-cdk#25256]
### Describe the bug

With the new aws_batch_alpha API in 2.74 the `ManagedEc2EcsComputeEnvironment` creates an instance role automatically but it does not attach the necessary `AmazonEC2ContainerServiceforEC2Role` managed policy.

The consequence is that, unless that is manually added, the jobs cannot connect to ECS and the compute environment is invalidated.

### Expected Behavior

The instance role that is automatically created by `ManagedEc2EcsComputeEnvironment` should have the `AmazonEC2ContainerServiceforEC2Role` managed policy attached.

### Current Behavior

The instance role that is automatically created by `ManagedEc2EcsComputeEnvironment` does not have any policies attached.

### Reproduction Steps

The following snippet creates a compute environment with the default instance profile.

```ts
    new batch.ManagedEc2EcsComputeEnvironment(this, 'TestComputeEnv', {
      allocationStrategy: batch.AllocationStrategy.BEST_FIT,
      vpc: myVPC
    });
```

An trimmed down version of the synthetized output is the following, note that the instance role `VideocvtTestComputeEnvInstanceProfileRoleB1632120` does not have a policy attached.

```json
  "VideocvtTestComputeEnvInstanceProfileRoleB1632120": {
   "Type": "AWS::IAM::Role",
   "Properties": {
    "AssumeRolePolicyDocument": {
     "Statement": [
      {
       "Action": "sts:AssumeRole",
       "Effect": "Allow",
       "Principal": {
        "Service": "ec2.amazonaws.com"
       }
      }
     ],
     "Version": "2012-10-17"
    }
   },
   "Metadata": {
    "aws:cdk:path": ".../Videocvt/TestComputeEnv/InstanceProfileRole/Resource"
   }
  },
  "VideocvtTestComputeEnvInstanceProfile1A03EEED": {
   "Type": "AWS::IAM::InstanceProfile",
   "Properties": {
    "Roles": [
     {
      "Ref": "VideocvtTestComputeEnvInstanceProfileRoleB1632120"
     }
    ]
   },
   ...
  },
  "VideocvtTestComputeEnv3406EB79": {
   "Type": "AWS::Batch::ComputeEnvironment",
   "Properties": {
    "ComputeResources": {
     "InstanceRole": {
      "Fn::GetAtt": [
       "VideocvtTestComputeEnvInstanceProfile1A03EEED",
       "Arn"
      ]
     },
     ...
    },
    ...
  }
```

### Possible Solution

When the instance role is created in https://github.com/aws/aws-cdk/blob/5573025f89359d46fd2878be49ce09b52854b6fd/packages/%40aws-cdk/aws-batch-alpha/lib/managed-compute-environment.ts#L1121

Add the following line
```ts
  managedPolicies: [iam.ManagedPolicy.fromAwsManagedPolicyName('service-role/AmazonEC2ContainerServiceforEC2Role')]
```

### CDK CLI Version

2.76

### Framework Version

2.76

### Node.js Version

v16.18.1

### OS

Linux

### Language

Typescript

### Language Version

4.9.5

**Comment by pahud** [comment]
Thank you for your detailed report. Yes we should attach the policy to that instance role. I am making it p2 bug now. Any PR is welcome and appreciated.
