### ISSUE TITLE
How to resolve "Cross-account pass role is not allowed" error in AWS CloudFormation using CDK in Python?

### ISSUE THREAD

**Issue by rlamba89** [aws/aws-cdk#25258]
### Describe the bug

 I am attempting to create an AWS CodePipeline using CDK in Python that deploys a CloudFormation stack to Account 2 from Account 1. However, I am encountering the error "Cross-account pass role is not allowed" when attempting to deploy in the cross-account deployment stage.

I have successfully deployed code to Account 1 and can also deploy code to Account 2 from my local machine using "cdk deploy --all". Additionally, I have established a trust relationship between Account 1 and Account 2 during cdk bootstrap.

How can I resolve this error and successfully deploy the CloudFormation stack to Account 2 using CDK?

### Expected Behavior

It should be able to deploy cross account.

### Current Behavior

Getting error : Cross-account pass role is not allowed

### Reproduction Steps

 I am attempting to create an AWS CodePipeline using CDK in Python that deploys a CloudFormation stack to Account 2 from Account 1. However, I am encountering the error "Cross-account pass role is not allowed" when attempting to deploy in the cross-account deployment stage.

I have successfully deployed code to Account 1 and can also deploy code to Account 2 from my local machine using "cdk deploy --all". Additionally, I have established a trust relationship between Account 1 and Account 2 during cdk bootstrap.

How can I resolve this error and successfully deploy the CloudFormation stack to Account 2 using CDK?

### CDK CLI Version

2.66.1 (build 539d036)

### Node.js Version

v19.6.1

### OS

Mac

### Language

Python

### Language Version

Python 3.9.13

**Comment by pahud** [comment]
Sounds like you are deploying a CDK pipeline in Account 1 and the pipeline deploys the CDK app in Account 2, is it correct?

Can you simplify your CDK code and paste your code in this issue so we can reproduce in our environment?
