### ISSUE TITLE
aws-batch-alpha: ManagedEc2EcsComputeEnvironmentProps instanceRole incorrect type

### ISSUE THREAD

**Issue by k-boyle** [aws/aws-cdk#25262]
### Describe the bug

I'm trying to create a `ManagedEc2EcsComputeEnvironment` and I need to use a `CfnInstanceProfile` and [instanceRole](https://github.com/aws/aws-cdk/blob/f628a1b73e6cc4f93d8f193c9f8cd77fc3ebe178/packages/%40aws-cdk/aws-batch-alpha/lib/managed-compute-environment.ts#L304) is typed as `iam.IRole` so it's not assignable.

In the 'old' batch code it's typed as `string` [see this mr comment](https://github.com/aws/aws-cdk/pull/6549/files#r388373120)

### Expected Behavior

To be able to assign a `CfnInstanceProfile` or its name to the `instanceRole` property

### Current Behavior

Can't assign since it expects an `IRole`

### Reproduction Steps

```ts
const instanceProfile = new iam.CfnInstanceProfile(this, 'name', { roles: ['role'] });
const environment = new batch.ManagedEc2EcsComputeEnvironment(this, 'environment', {
    instanceRole: instanceProfile
});
```

### Possible Solution

Change `instanceRole` to be typed as `string`/`CfnInstanceProfile`

### CDK CLI Version

2.76.0 (build 78c411b)

### Node.js Version

19.9.0

### OS

Windows

### Language

Typescript

**Comment by k-boyle** [comment]
update: so after digging through the source code I see that it'll create an instance profile for you with the specified role, and for that usecase that's good enough

**Comment by pahud** [comment]
Hi @k-boyle 

Yes, from current API design:

https://github.com/aws/aws-cdk/blob/0cd06e958a7092103f4848c802afb2446b2e39d6/packages/%40aws-cdk/aws-batch-alpha/lib/managed-compute-environment.ts#L910

An optional `instanceRole` can be specified and instanceProfile will be auto generated for you:

https://github.com/aws/aws-cdk/blob/0cd06e958a7092103f4848c802afb2446b2e39d6/packages/%40aws-cdk/aws-batch-alpha/lib/managed-compute-environment.ts#L641
