### ISSUE TITLE
aws-cdk-lib: Uncaught Exception [High Severity] in yaml@1.10.2

### ISSUE THREAD

**Issue by joelgarrett** [aws/aws-cdk#25271]
### Describe the bug

High Severity security issue identified by Snyk.

```
Issues with no direct upgrade or patch:
  ✗ Uncaught Exception [High Severity][https://security.snyk.io/vuln/SNYK-JS-YAML-5458867] in yaml@1.10.2
    introduced by aws-cdk-lib@2.69.0 > yaml@1.10.2
  This issue was fixed in versions: 2.2.2
```

### Expected Behavior

No high-severity security issues exist.

### Current Behavior

Projects with Snyk security scans can not pass pull request branch protections.

### Reproduction Steps

Scan an empty CDK project with Snyk.

```
snyk test --all-projects
```

### Possible Solution

Upgrade yaml dependency version to 2.2.2.

### CDK CLI Version

2.69.0

### Node.js Version

16.16.0

### OS

macOS 13.3.1

### Language

Typescript

**Comment by joelgarrett** [comment]
I'm testing using PNPM's override feature to force `yaml@2.2.2`.

**Comment by joelgarrett** [comment]
Overrides do not work for this dependency as it is bundled with `aws-cdk-lib` at the fixed version of 1.10.2.

**Comment by pahud** [comment]
Thank you for your report! I will bring up to the team immediately.

**Comment by mrgrain** [comment]
Hi all, unfortunately the version range on the reported CVE is wrong. The issue isn't present in the version CDK uses.

See report to GitHub Advisory database:
https://github.com/github/advisory-database/pull/2193

And a comment by the maintainer on huntr:
https://huntr.dev/bounties/4b494e99-5a3e-40d9-8678-277f3060e96c/ (at the very end)

**Comment by mrgrain** [comment]
Synk has also updated the version range:
https://security.snyk.io/package/npm/yaml/2.1.3

**Comment by mrgrain** [comment]
Closing this now. The advisory has been updated to correctly reflect affected versions (which this one isn't) and the upgrade to v2 of yaml isn't trivial.
