### ISSUE TITLE
(synthetics): (Add new runtime SYNTHETICS_NODEJS_PUPPETEER_3_9)

### ISSUE THREAD

**Issue by verma-rajatk** [aws/aws-cdk#25276]
### Describe the feature

![image](https://user-images.githubusercontent.com/19155094/234168582-8d3a4d34-fe35-49ac-bf52-e1f628f46eae.png)

### Use Case

Ability to upgrade canaries to latest runtime

### Proposed Solution

Add new constant [here](https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/aws-synthetics-alpha/lib/runtime.ts) called SYNTHETICS_NODEJS_PUPPETEER_3_9 with value new Runtime('syn-nodejs-puppeteer-3.9', RuntimeFamily.NODEJS);

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2

### Environment details (OS name and version, etc.)

n/a

**Comment by pahud** [comment]
Thanks for reporting. Are you interested to submit a PR for this?

**Comment by colifran** [comment]
@verma-rajatk thanks for reporting! After reviewing, it looks like this runtime was added 2 months ago. We should be okay to close this one.
