### ISSUE TITLE
(sns): (There is no enabled property in SnsEventSource)

### ISSUE THREAD

**Issue by ranjith-jagadeesh** [aws/aws-cdk#25289]
### Describe the bug

When attaching event source to lambda, enabled property is not available, but it is available in other event sources such as Dynamo Event source and SQS Event Source.

### Expected Behavior

Should be able to disable SNS Event Source

### Current Behavior

Enabled property is not available in SnsEventSource class 

### Reproduction Steps

```this.eventRouterFn.addEventSource(
      new SnsEventSource(orderEventTopic, {
        enabled: false,
        filterPolicy: { version: { conditions: ['2'] } },
      })
    )
```
    
Enabled property is not available

### CDK CLI Version

2.46

### Node.js Version

18

### OS

Mac

### Language

Typescript

**Comment by pahud** [comment]
`Enabled` seems to be a general property for all supported event source mapping. It makes sense to me. I am making this p2 feature request and any community PRs are welcome and appreciated.

**Comment by daschaa** [comment]
@pahud I had a look at this and saw that the SNS event source can not be compared to e.g. DynamoDB, because no event source mapping is used under the hood.
SNS is using a `CfnSubscription` for this, which does not have an `enabled` property.

Should the enabled property still considered to be added here? Can/Should this implementation be changed to use a EventSourceMapping too?

**Comment by anshikam** [comment]
I will be giving this one a try

**Comment by xazhao** [comment]
I agree with @daschaa. `enabled` property was added to event sources which use `AWS::Lambda::EventSourceMapping` resource (SQS, DynamoDB etc.). However SNS event source uses a different resource which doesn't have `enabled` property, `enabled` shouldn't be added to the `SnsEventSource`.

**Comment by ashishdhingra** [comment]
This should be closed per https://github.com/aws/aws-cdk/issues/25289#issuecomment-1910431970.
