### ISSUE TITLE
(core): slow synthesis after update to 2.71.0

### ISSUE THREAD

**Issue by deftomat** [aws/aws-cdk#25286]
### Describe the bug

Looks like large `cdk.out` directory (>10GB) is causing slow synthesis due to file/directory hash calculation introduced in 
https://github.com/aws/aws-cdk/pull/23951.

I was able to revert synthesis times back to normal by just returning static string from [`computeChecksumOfFolder`](https://github.com/aws/aws-cdk/commit/91d6509ce43285a20aca85d45e4017b7dcfbe49f#diff-d0099b082f7fd45e04a9543093a83d7fd136977424fe4cd3a50aab1c49d54684R158-R170).

Looks like calculating hash of 10GB of `cdk.out` content can easily introduce a 10~15 seconds delays.
This is especially an issue as there is no automated cleaning process for this directory. 

I'm not sure if reading GBs of data each time we are synthesising app is a good idea, especially when a lot of people probably not using https://github.com/aws/aws-cdk/pull/23951 feature anyway.

### Expected Behavior

Synthesis times should not by affected by stale data stored in `cdk.out` directory.

### Current Behavior

The larger the `cdk.out` directory, the slower the synthesis is.

### Reproduction Steps

- Install aws-cdk 2.71.0
- Add a huge amount of data into `cdk.out`
- Lost a 15 seconds of your life by waiting for synthesis 🙂 

### Possible Solution

- **Consider to calculate hash from file's `lastModified` time instead from the file's content. Looks like that should be enough for the given functionality.**
- Consider to use [`faster hashing alg`](https://github.com/Cyan4973/xxHash)
- Do not calculate hash when there is no validation plugin

### CDK CLI Version

2.74.0

### Node.js Version

18.16.0

### OS

macOS 13.3.1

### Language

Typescript

### Language Version

5.0.4

**Comment by pahud** [comment]
Thank you for your report.
