### ISSUE TITLE
(custom-resources): AwsCustomResource returns no data

### ISSUE THREAD

**Issue by bobveringa** [aws/aws-cdk#25283]
### Describe the bug

To get create certain resources, we use AWS Custom Resources to fetch details from the SDK. Upgrading to the latest version 2.76 broke all our custom resources that fetch data using the SDK. This only applies to resources using the `AwsCustomResource` construct.

When attempting to fetch the resources, the following error is returned from CDK.
```
CustomResource attribute error: Vendor response doesn't contain endpointAddress key in object
```

Failures occur on all platforms (Mac, Windows, Linux) including CDK Code Pipeline. The previous version 2.63 was working without issue.

### Expected Behavior

Normal operation without breaking changes.

### Current Behavior

Investigating lambda return values in CloudWatch there is a difference in the returned response.

Return on 2.76
```json
{
    "Status": "SUCCESS",
    "Reason": "OK",
    "PhysicalResourceId": "[HIDDEN]-ats.iot.eu-central-1.amazonaws.com",
    "StackId": "arn:aws:cloudformation:eu-central-1:[HIDDEN]:stack/iot/462a6010-82e4-11ed-ad4c-06513e2530cc",
    "RequestId": "4a7eed3c-296d-4472-aa2a-e367c08ac434",
    "LogicalResourceId": "IoTEndpoint9F0B923E",
    "NoEcho": false,
    "Data": {}
}
```

Return < 2.76 
```json
{
    "Status": "SUCCESS",
    "Reason": "OK",
    "PhysicalResourceId": "[HIDDEN]-ats.iot.eu-central-1.amazonaws.com",
    "StackId": "arn:aws:cloudformation:eu-central-1:[HIDDEN]:stack/iot/462a6010-82e4-11ed-ad4c-06513e2530cc",
    "RequestId": "f99dfa9a-e771-49fd-aa7f-faefc122e921",
    "LogicalResourceId": "IoTEndpoint9F0B923E",
    "NoEcho": false,
    "Data": {
        "apiVersion": null,
        "region": "eu-central-1",
        "endpointAddress": "[HIDDEN]-ats.iot.eu-central-1.amazonaws.com"
    }
}
```

### Reproduction Steps

```python
from aws_cdk import (
    custom_resources as cr,
)

        iot_endpoint = cr.AwsCustomResource(
            self,
            'IoTEndpoint',
            policy=cr.AwsCustomResourcePolicy.from_sdk_calls(
                resources=cr.AwsCustomResourcePolicy.ANY_RESOURCE
            ),
            on_create=cr.AwsSdkCall(
                service='Iot',
                action='describeEndpoint',
                physical_resource_id=cr.PhysicalResourceId.from_response(
                    'endpointAddress'),
                parameters={
                    'endpointType': 'iot:Data-ATS'
                }
            )
        )

        endpoint = iot_endpoint.get_response_field('endpointAddress')
```

### CDK CLI Version

2.76.0 (build 78c411b)

### Node.js Version

v16.14.2

### OS

Windows

### Language

Python

### Language Version

Python 3.9.6

**Comment by bobveringa** [comment]
After several hours of debugging, it turns out that the `on_update` method is now required for these custom resource calls. In version 2.69 a change was introduced in https://github.com/aws/aws-cdk/pull/24194 which made some modifications to the way Physical IDs are handled. It includes the line

> AwsCustomResource.getResponseField() and .getResponseFieldReference() will not work if the Create and Update APIs don't consistently return the same fields.

However, this caused a breaking change which seems to have gone unnoticed.

**Comment by bobveringa** [comment]
In version 2.63 only defining the `on_create` was sufficient. After updating to 2.76 the `on_update` also needed to be defined in order for data to be returned. I assume that this change was caused by another change to custom-resources. However, I have not had the time to investigate if this change is caused by 2.69.


These are the 2 implementations I pulled out of our git history. This initial version has had this implementation since at least CDK v2.20.

```python
iot_endpoint = cr.AwsCustomResource(
    self,
    'IoTEndpoint',
    policy=cr.AwsCustomResourcePolicy.from_sdk_calls(
        resources=cr.AwsCustomResourcePolicy.ANY_RESOURCE
    ),
    on_create=cr.AwsSdkCall(
        service='Iot',
        action='describeEndpoint',
        physical_resource_id=cr.PhysicalResourceId.from_response(
            'endpointAddress'),
        parameters={
            'endpointType': 'iot:Data-ATS'
        }
    )
)

endpoint = iot_endpoint.get_response_field('endpointAddress')
```

This broke updating to 2.76. Implementing the `on_update` method to the following resolved the issue.

```python
iot_endpoint = cr.AwsCustomResource(
    self,
    'IoTEndpoint',
    policy=cr.AwsCustomResourcePolicy.from_sdk_calls(
        resources=cr.AwsCustomResourcePolicy.ANY_RESOURCE
    ),
    on_create=cr.AwsSdkCall(
        service='Iot',
        action='describeEndpoint',
        physical_resource_id=cr.PhysicalResourceId.from_response(
            'endpointAddress'),
        parameters={
            'endpointType': 'iot:Data-ATS'
        }
    ),
    on_update=cr.AwsSdkCall(
        service='Iot',
        action='describeEndpoint',
        parameters={
            'endpointType': 'iot:Data-ATS'
        }
    )
)

endpoint = iot_endpoint.get_response_field('endpointAddress')
```

**Comment by tmegow** [comment]
I am attempting to create an MSK Custom Plugin using an AwsCustomResource using the [createCustomPlugin KafkaConnect AwsSdkCall](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/KafkaConnect.html#createCustomPlugin-property). 

Now that on_update method is required in addition to on_create, I am using the same createCustomPlugin call in the on_update method. 

My issue is that, after initial creation of the Cloudformation Stack and resource, each `cdk deploy` results in the AwsCustomResource going into `UPDATE_IN_PROGRESS` and that call fails with `Invalid parameter name: A resource with this name already exists`

So I am unable to run `cdk deploy` in an idempotent way, instead being forced to deploy once and then ensure to never deploy again, else be confronted with `Invalid parameter name: A resource with this name already exists` errors.

**Comment by davidjmemmett** [comment]
I'm also experiencing the same issue, I'm issuing a KMS `replicateKey` call using `on_create`, and it's failing to get the replica ARN:

Error:
```
Vendor response doesn't contain ReplicaKeyMetadata.Arn attribute in object...
```

Redacted code:
```
replica_resource = AwsCustomResource(
    scope=self,
    id=f'kms_replica_{region}',
    on_create=AwsSdkCall(
        service='KMS',
        action='replicateKey',
        parameters={
            'KeyId': self.kms_key.attr_key_id,
            'ReplicaRegion': region,
            'Policy': dumps(self.key_policy),
        },
        physical_resource_id=PhysicalResourceId.of(f'kms-replica-{region}-{self.stack_unique_name_suffix}'),
    ),
    policy=AwsCustomResourcePolicy.from_statements(
        statements=[
            PolicyStatement(
                actions=['kms:*'],
                resources=['*'],
            )
        ],
    )
)
key_replica_arn = replica_resource.get_response_field('ReplicaKeyMetadata.Arn')

AwsCustomResource(
    scope=self,
    id=f'kms_replica_alias_{region}',
    on_create=AwsSdkCall(
        service='KMS',
        action='createAlias',
        parameters={
            'AliasName': 'alias/KMSAlias',
            'TargetKeyId': key_replica_arn,
        },
        physical_resource_id=PhysicalResourceId.of(f'kms-replica-alias-{region}-{self.stack_unique_name_suffix}'),
        region=region,
    ),
    policy=AwsCustomResourcePolicy.from_statements(
        statements=[
            PolicyStatement(
                actions=['kms:CreateAlias'],
                resources=['*'],
            )
        ],
    )
)

```

**Comment by stijnbrouwers** [comment]
@bobveringa thanks for info!
Adding the on_update also solved the issue for me.
I was calling the AWS CustomResource with only an on_create. It used to work, but after an update it broke. Adding on_update fixed it for me (I was calling describeUserPoolClient but I think it doesn't really matter which exact endpoint you are calling).

**Comment by davidjmemmett** [comment]
> @davidjmemmett, can you try adding on on_update to your code?

There isn't a KMS API call which returns the same response with an update verb, therefore only on_create works, any further updates fail.

**Comment by pahud** [comment]
I assume this should have been fixed in https://github.com/aws/aws-cdk/issues/29949

Feel free to open a new ticket if it's still relevant.
