### ISSUE TITLE
s3: breaking change, cannot create bucket anymore, InvalidBucketAclWithObjectOwn

### ISSUE THREAD

**Issue by melinaschweizer** [aws/aws-cdk#25288]
### Describe the bug

Deployed S3 bucket last week into account A without issues and this week it fails on account B with a "Bucket cannot have ACLs set with "ObjectOwnership's BucketOwnerEnforced setting (Service: Amazon S3; Status Code: 400; Error Code: InvalidBucketAclWithObjectOwnership; Request ID: K97VC1M7Z0YY14A5; S3 Extended Request ID: DZGiUrXpLClhwp+7nOjoGocVx15FGQCQd6V0NGXk/YSJ3n/OTZWOIg5sNZGagfs7T0wWX2hPw6M=; Proxy: null)".
Perhaps the announcement https://www.helpnetsecurity.com/2023/02/07/amazon-s3-bucket-security/ is the reason. 

### Expected Behavior

I expected the buckets to be created without issue, since this worked last week.

### Current Behavior

TERMINAL Output: The bucket creation fails with "1:43:11 PM | CREATE_FAILED        | AWS::S3::Bucket               | Servicesxxxcsvaccesslogstsm07305C09
Bucket cannot have ACLs set with ObjectOwnership's BucketOwnerEnforced setting (Service: Amazon S3; Status Code: 400; Error Code: InvalidBucketAclWithObjectOwn
ership; Request ID: K97VC1M7Z0YY14A5; S3 Extended Request ID: DZGiUrXpLClhwp+7nOjoGocVx15FGQCQd6V0NGXk/YSJ3n/OTZWOIg5sNZGagfs7T0wWX2hPw6M=; Proxy: null)"

CFN Output:
2023-04-25 13:43:11 UTC+0200 | Servicesxxxcsvaccesslogstsm07305C09 | CREATE_FAILED | Bucket cannot have ACLs set with ObjectOwnership's BucketOwnerEnforced setting (Service: Amazon S3; Status Code: 400; Error Code: InvalidBucketAclWithObjectOwnership; Request ID: K97VC1M7Z0YY14A5; S3 Extended Request ID: DZGiUrXpLClhwp+7nOjoGocVx15FGQCQd6V0NGXk/YSJ3n/OTZWOIg5sNZGagfs7T0wWX2hPw6M=; Proxy: null)
-- | -- | -- | --

### Reproduction Steps

        access_logs_bucket = s3.Bucket(
            self, "xxx-csv-access-logs-tsm", 
            encryption=s3.BucketEncryption.S3_MANAGED,
            versioned=True,
            block_public_access=s3.BlockPublicAccess.BLOCK_ALL,
        )
        csv_bucket = s3.Bucket(
            self, "xxx-csv", 
            encryption=s3.BucketEncryption.KMS, 
            encryption_key=csv_bucket_key,
            versioned=True,
            block_public_access=s3.BlockPublicAccess.BLOCK_ALL,
            enforce_ssl=True,
            server_access_logs_bucket=access_logs_bucket
        )

### CDK CLI Version

2.76.0 (build 78c411b)

### Node.js Version

v19.8.1

### OS

macos

### Language

Python

### Language Version

Python 3.9.6

**Comment by vincenthongzy** [comment]
we are facing this issue as well

**Comment by pahud** [comment]
According to the [blog post announcement](https://aws.amazon.com/blogs/aws/heads-up-amazon-s3-security-changes-are-coming-in-april-of-2023/):

>Once the changes are in effect for a target Region, all newly created buckets in the Region will by default have [S3 Block Public Access](https://aws.amazon.com/blogs/aws/amazon-s3-block-public-access-another-layer-of-protection-for-your-accounts-and-buckets/) enabled and [access control lists](https://aws.amazon.com/blogs/aws/new-simplify-access-management-for-data-stored-in-amazon-s3/) (ACLs) disabled. Both of these options are already console defaults and have long been recommended as best practices. The options will become the default for buckets that are created using the [S3 API](https://docs.aws.amazon.com/AmazonS3/latest/API/Welcome.html), [S3 CLI](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3/index.html), the [AWS SDKs](https://aws.amazon.com/tools/), or [AWS CloudFormation](https://aws.amazon.com/cloudformation/) templates.

I believe we should improve the property validation in L2 Bucket construct to improve better user experience.

**Comment by rittneje** [comment]
@pahud I think you should pin this issue.

**Comment by WealthBlockAI** [comment]
> we are facing this issue as well:
> 
> ```
>     this.bucket = new s3.Bucket(this, 'Bucket', {
>       autoDeleteObjects: true,
>       removalPolicy: RemovalPolicy.DESTROY,
>       bucketName: `bucket-name`,
>       publicReadAccess: true,
>       accessControl: s3.BucketAccessControl.PUBLIC_READ,
>     });
> ```
> 
> edit: following this https://aws.amazon.com/blogs/aws/heads-up-amazon-s3-security-changes-are-coming-in-april-of-2023/ , I managed to generate a new error `Bucket cannot have public ACLs set with BlockPublicAccess enabled`:
> 
> ```
>     this.bucket = new s3.Bucket(this, 'Bucket', {
>       autoDeleteObjects: true,
>       removalPolicy: RemovalPolicy.DESTROY,
>       bucketName: `bucket-name`,
>       publicReadAccess: true,
>       objectOwnership: ObjectOwnership.OBJECT_WRITER,
>       accessControl: s3.BucketAccessControl.PUBLIC_READ,
>     });
> ```
> 
> ...but there seems to be no way to remove the `BlockPublicAccess` config



> publicReadAccess: true,

I got the same message, but after sifting around the documentation for a while, found that this can be achieved with two calls (examples using NodeJS SDK)

1. Create bucket with the Object Ownership set to Object Writer, but do NOT include any public read access or public ACLs. 
e.g. s3.createBucket({ Bucket: "my_bucket", ObjectOwnership: "ObjectWriter" })

2. Make a second call to delete the PublicAccessBlock
e.g. s3.deletePublicAccessBlock({ Bucket: "my_bucket" })

**Comment by jstampleman** [comment]
I'm an AWS noob, but the bottom line for me is that I'm getting these errors while followind an AWS tutorial...

https://catalog.workshops.aws/complete-aws-sam/en-US/module-4-cicd/module-4-cicd-gh/50-sampipeinit

... is this something likely to be fixed?  Or does someone need to update that tutorial?

**Comment by 0xdevalias** [comment]
> [catalog.workshops.aws/complete-aws-sam/en-US/module-4-cicd/module-4-cicd-gh/50-sampipeinit](https://catalog.workshops.aws/complete-aws-sam/en-US/module-4-cicd/module-4-cicd-gh/50-sampipeinit)
> 
> ... is this something likely to be fixed? Or does someone need to update that tutorial?

@jstampleman I didn't look too deeply into it, but my guess is that the tutorial (or the `sam pipeline init --bootstrap` code will likely need to be updated (if it hasn't already been) to account for the changes needed in the CloudFormation template.

If it's still an issue, I would suggest searching the existing issues on the SAM CLI GitHub repo, and if a relevant one doesn't exist, then submitting a new issue for it there (potentially referring back to this issue if relevant):

-  https://github.com/aws/aws-sam-cli/issues

**Comment by pkit** [comment]
This shitshow is amazing. Yes, all official AWS documents for CloudFormation still use the old syntax that fails to create anything.
ALL OF THEM!
