### ISSUE TITLE
aws_s3: Starting April 2023, it's not possible to setup an s3 bucket to use as logging bucket for a cloudfront distribution

### ISSUE THREAD

**Issue by ben-elsen** [aws/aws-cdk#25291]
### Describe the feature

At the moment, it is not possible to create a bucket with aws_cdk that can be used in a cloudfront distribution as logging bucket. 

There was the announcement of AWS: Starting April 2023  you will need to enable S3 access control lists (ACLs) for new S3 buckets being used for CloudFront standard logs. (https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/AccessLogs.html)

I don't think there is a way to do this with CDK at the moment, every configuration I use, I get the following error:
ROLLBACK_COMPLETE: Bucket cannot have ACLs set with ObjectOwnership's BucketOwnerEnforced setting (Service: Amazon S3; Status Code: 400; Error Code: InvalidBucketAclWithObjectOwnership;

### Use Case

I want to be able to define a s3 bucket and use it as logging bucket for a cloudfront distribution. 

### Proposed Solution

I think a new type for BucketAccessControl could help? 

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.76.0 (build 78c411b)

### Environment details (OS name and version, etc.)

Macbook Ventura 13.3.1 (22E261)

**Comment by pahud** [comment]
related to https://github.com/aws/aws-cdk/issues/25288#issuecomment-1522011311

And this works for me FYR

```ts
const logBucket = new s3.Bucket(this, 'logBucket', {
  accessControl: s3.BucketAccessControl.PRIVATE,
  objectOwnership: s3.ObjectOwnership.OBJECT_WRITER,
  autoDeleteObjects: true,
  removalPolicy: RemovalPolicy.DESTROY,
});
```

We probably need to improve our API document for this.

**Comment by rittneje** [comment]
We are facing the same issue trying to use a bucket for the server access logs of another bucket. According to the docs the recommendation is to use an IAM policy instead of an ACL. CDK ought to be fixed to follow this security best practice. https://docs.aws.amazon.com/AmazonS3/latest/userguide/enable-server-access-logging.html#grant-log-delivery-permissions-bucket-policy

**Comment by ben-elsen** [comment]
Thanks @pahud this seems to work for us!

**Comment by corymhall** [comment]
I'm going to close this in favor of https://github.com/aws/aws-cdk/issues/25358
