### ISSUE TITLE
aws-ec2: Elasticache Interface VPC endpoint service name in China regions is incorrect

### ISSUE THREAD

**Issue by murrmaz** [aws/aws-cdk#25329]
### Describe the bug

The static [InterfaceVpcEndpointAwsService ELASTICACHE](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ec2.InterfaceVpcEndpointAwsService.html#static-elasticache) does not produce the correct service name in China regions (cn-north-1 and cn-northwest-1). Instead, it produces the service name for the Non-China regions.

### Expected Behavior

For a Cloudformation Stack in region cn-north-1:
`{
    name: 'cn.com.amazonaws.cn-north-1.elasticache',
    shortName: 'elasticache',
    port: 443
}`

For a Cloudformation Stack in region cn-northwest-1:
`{
    name: 'cn.com.amazonaws.cn-northwest-1.elasticache',
    shortName: 'elasticache',
    port: 443
}`

### Current Behavior

For a Cloudformation Stack in region cn-north-1:
`{
    name: 'com.amazonaws.cn-north-1.elasticache',
    shortName: 'elasticache',
    port: 443
}`

For a Cloudformation Stack in region cn-northwest-1:
`{
    name: 'com.amazonaws.cn-northwest-1.elasticache',
    shortName: 'elasticache',
    port: 443
}`

### Reproduction Steps

```
import {Vpc, InterfaceVpcEndpointAwsService} from 'aws-cdk-lib/aws-ec2'

myVpc = new Vpc(...)

// Interface VPC endpoint for Elasticache
elasticacheEndpoint = myVpc.addInterfaceEndpoint('elasticacheEndpoint', {
    service: InterfaceVpcEndpointAwsService.ELASTICACHE
})
```

### Possible Solution

Add elasticache to the list of [VPC_ENDPOINT_SERVICE_EXCEPTIONS](https://github.com/aws/aws-cdk/blob/f44946ba5fe0f59fe510df6d224d0adb40578d59/packages/aws-cdk-lib/aws-ec2/lib/vpc-endpoint.ts#L516) for cn-north-1 and cn-northwest-1.

This will generate the correct interface VPC endpoint service name prefix (cn.com.amazonaws)

### CDK CLI Version

2.74.0 (build 70e2a33)

### Node.js Version

v16.20.0

### OS

Amazon Linux 2

### Language

Typescript

### Language Version

TypeScript (4.9.5)

**Comment by pahud** [comment]
Yes I can confirm that with the following commands.

```sh
% AWS_PROFILE=bjs AWS_REGION=cn-north-1 aws ec2 describe-vpc-endpoint-services | jq -r '.ServiceDetails[]|select(.ServiceName | startswith("cn.com.amazonaws")) | .ServiceName'
```
cn.com.amazonaws.cn-north-1.application-autoscaling
cn.com.amazonaws.cn-north-1.appmesh-envoy-management
cn.com.amazonaws.cn-north-1.athena
cn.com.amazonaws.cn-north-1.autoscaling
cn.com.amazonaws.cn-north-1.awsconnector
cn.com.amazonaws.cn-north-1.backup
cn.com.amazonaws.cn-north-1.batch
cn.com.amazonaws.cn-north-1.cassandra
cn.com.amazonaws.cn-north-1.cloudcontrolapi
cn.com.amazonaws.cn-north-1.cloudformation
cn.com.amazonaws.cn-north-1.codedeploy-commands-secure
cn.com.amazonaws.cn-north-1.databrew
cn.com.amazonaws.cn-north-1.dms
cn.com.amazonaws.cn-north-1.ebs
cn.com.amazonaws.cn-north-1.ec2
cn.com.amazonaws.cn-north-1.ecr.api
cn.com.amazonaws.cn-north-1.ecr.dkr
cn.com.amazonaws.cn-north-1.eks
cn.com.amazonaws.cn-north-1.elasticache
cn.com.amazonaws.cn-north-1.elasticbeanstalk
cn.com.amazonaws.cn-north-1.elasticfilesystem
cn.com.amazonaws.cn-north-1.elasticfilesystem-fips
cn.com.amazonaws.cn-north-1.emr-containers
cn.com.amazonaws.cn-north-1.execute-api
cn.com.amazonaws.cn-north-1.fsx
cn.com.amazonaws.cn-north-1.imagebuilder
cn.com.amazonaws.cn-north-1.iot.data
cn.com.amazonaws.cn-north-1.iotsitewise.api
cn.com.amazonaws.cn-north-1.iotsitewise.data
cn.com.amazonaws.cn-north-1.kinesis-streams
cn.com.amazonaws.cn-north-1.lambda
cn.com.amazonaws.cn-north-1.license-manager
cn.com.amazonaws.cn-north-1.monitoring
cn.com.amazonaws.cn-north-1.rds
cn.com.amazonaws.cn-north-1.redshift
cn.com.amazonaws.cn-north-1.redshift-data
cn.com.amazonaws.cn-north-1.s3
cn.com.amazonaws.cn-north-1.sagemaker.api
cn.com.amazonaws.cn-north-1.sagemaker.featurestore-runtime
cn.com.amazonaws.cn-north-1.sagemaker.runtime
cn.com.amazonaws.cn-north-1.securityhub
cn.com.amazonaws.cn-north-1.servicecatalog
cn.com.amazonaws.cn-north-1.sms
cn.com.amazonaws.cn-north-1.sqs
cn.com.amazonaws.cn-north-1.states
cn.com.amazonaws.cn-north-1.sts
cn.com.amazonaws.cn-north-1.sync-states
cn.com.amazonaws.cn-north-1.synthetics
cn.com.amazonaws.cn-north-1.transcribe.cn
cn.com.amazonaws.cn-north-1.transcribestreaming
cn.com.amazonaws.cn-north-1.transfer
cn.com.amazonaws.cn-north-1.xray

```sh
 % AWS_PROFILE=bjs AWS_REGION=cn-northwest-1 aws ec2 describe-vpc-endpoint-services | jq -r '.ServiceDetails[]|select(.ServiceName | startswith("cn.com.amazonaws")) | .ServiceName'
```
cn.com.amazonaws.cn-northwest-1.account
cn.com.amazonaws.cn-northwest-1.application-autoscaling
cn.com.amazonaws.cn-northwest-1.appmesh-envoy-management
cn.com.amazonaws.cn-northwest-1.athena
cn.com.amazonaws.cn-northwest-1.autoscaling
cn.com.amazonaws.cn-northwest-1.awsconnector
cn.com.amazonaws.cn-northwest-1.backup
cn.com.amazonaws.cn-northwest-1.batch
cn.com.amazonaws.cn-northwest-1.cassandra
cn.com.amazonaws.cn-northwest-1.cloudcontrolapi
cn.com.amazonaws.cn-northwest-1.cloudformation
cn.com.amazonaws.cn-northwest-1.codedeploy-commands-secure
cn.com.amazonaws.cn-northwest-1.databrew
cn.com.amazonaws.cn-northwest-1.dms
cn.com.amazonaws.cn-northwest-1.ebs
cn.com.amazonaws.cn-northwest-1.ec2
cn.com.amazonaws.cn-northwest-1.ecr.api
cn.com.amazonaws.cn-northwest-1.ecr.dkr
cn.com.amazonaws.cn-northwest-1.eks
cn.com.amazonaws.cn-northwest-1.elasticache
cn.com.amazonaws.cn-northwest-1.elasticbeanstalk
cn.com.amazonaws.cn-northwest-1.elasticfilesystem
cn.com.amazonaws.cn-northwest-1.elasticfilesystem-fips
cn.com.amazonaws.cn-northwest-1.emr-containers
cn.com.amazonaws.cn-northwest-1.execute-api
cn.com.amazonaws.cn-northwest-1.fsx
cn.com.amazonaws.cn-northwest-1.imagebuilder
cn.com.amazonaws.cn-northwest-1.iot.data
cn.com.amazonaws.cn-northwest-1.kinesis-streams
cn.com.amazonaws.cn-northwest-1.lambda
cn.com.amazonaws.cn-northwest-1.license-manager
cn.com.amazonaws.cn-northwest-1.monitoring
cn.com.amazonaws.cn-northwest-1.polly
cn.com.amazonaws.cn-northwest-1.rds
cn.com.amazonaws.cn-northwest-1.redshift
cn.com.amazonaws.cn-northwest-1.redshift-data
cn.com.amazonaws.cn-northwest-1.s3
cn.com.amazonaws.cn-northwest-1.sagemaker.api
cn.com.amazonaws.cn-northwest-1.sagemaker.featurestore-runtime
cn.com.amazonaws.cn-northwest-1.sagemaker.runtime
cn.com.amazonaws.cn-northwest-1.securityhub
cn.com.amazonaws.cn-northwest-1.servicecatalog
cn.com.amazonaws.cn-northwest-1.sms
cn.com.amazonaws.cn-northwest-1.sqs
cn.com.amazonaws.cn-northwest-1.states
cn.com.amazonaws.cn-northwest-1.sts
cn.com.amazonaws.cn-northwest-1.sync-states
cn.com.amazonaws.cn-northwest-1.synthetics
cn.com.amazonaws.cn-northwest-1.transcribe.cn
cn.com.amazonaws.cn-northwest-1.transcribestreaming
cn.com.amazonaws.cn-northwest-1.transfer
cn.com.amazonaws.cn-northwest-1.workspaces
cn.com.amazonaws.cn-northwest-1.xray

```sh
% AWS_PROFILE=bjs AWS_REGION=cn-north-1 aws ec2 describe-vpc-endpoint-services | jq -r '.ServiceDetails[]|select(.ServiceName | startswith("cn.com.amazonaws")) | .ServiceName' | cut -d. -f5- | tr '\n' ','
```
application-autoscaling,appmesh-envoy-management,athena,autoscaling,awsconnector,backup,batch,cassandra,cloudcontrolapi,cloudformation,codedeploy-commands-secure,databrew,dms,ebs,ec2,ecr.api,ecr.dkr,eks,elasticache,elasticbeanstalk,elasticfilesystem,elasticfilesystem-fips,emr-containers,execute-api,fsx,imagebuilder,iot.data,iotsitewise.api,iotsitewise.data,kinesis-streams,lambda,license-manager,monitoring,rds,redshift,redshift-data,s3,sagemaker.api,sagemaker.featurestore-runtime,sagemaker.runtime,securityhub,servicecatalog,sms,sqs,states,sts,sync-states,synthetics,transcribe.cn,transcribestreaming,transfer,xray,%
