### ISSUE TITLE
triggers: Documentation for Event and RequestResponse invocation types are swapped

### ISSUE THREAD

**Issue by mattiamatrix** [aws/aws-cdk#25325]
### Describe the bug

```
def lambda_handler(event: None, context: LambdaContext):

    raise Exception("HELL0")
```

This is my lambda function; when I deploy it and trigger via [Trigger](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.triggers.Trigger.html), the CloudFormation deployment should fail. However, it does not. Also, `FunctionError` is ignored.

### Expected Behavior

CloudFormation deployment should fail.

If I run `aws lambda invoke --function-name ***` I get. `FunctionError` should be handled [here](https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/triggers/lib/lambda/index.ts#L74)
```
{
    "StatusCode": 200,
    "FunctionError": "Unhandled",
    "ExecutedVersion": "$LATEST"
}
```

### Current Behavior

CloudFormation deployment does not fail and always logs.

```
{ invokeResponse: { StatusCode: 202, Payload: '' } }
```

### Reproduction Steps

https://github.com/aws/aws-cdk/tree/main/packages/aws-cdk-lib/triggers#usage

### CDK CLI Version

2.76.0

### Node.js Version

v18.15.0

### OS

mac OS 13.3.1

### Language

Typescript

**Comment by peterwoodworth** [comment]
This is working properly for me, I copied your exact lambda handler, and here's my stack.

```ts
    const fn = new lambda.Function(this, 'Function', { 
      code: lambda.Code.fromAsset('assets/pylambda'),
      handler: 'index.handler',
      runtime: lambda.Runtime.PYTHON_3_9
    });
    const t = new triggers.Trigger(this, 'Trigger', {
      handler: fn
    });
```

I've tried to mess around a bit with it and I can't get it to not throw an error. Could you please supply your full reproduction code?

**Comment by mattiamatrix** [comment]
errata corrige: the error is in the [documentation](https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/triggers/lib/trigger.ts#L68-L78).

The documentation for `EVENT` and `REQUEST_RESPONSE` is switched. 

My bad @peterwoodworth , I should know better

**Comment by pahud** [comment]
@mattiamatrix 

Yap, you can't set the `invocationType: InvocationType.EVENT` otherwise you always get 202 from async lambda invoke.

**Comment by peterwoodworth** [comment]
> The docstring for EVENT and REQUEST_RESPONSE is switched.

That would explain it! Thanks for calling this out

**Comment by mattiamatrix** [comment]
@peterwoodworth, https://github.com/aws/aws-cdk/pull/25327 should fix
