### ISSUE TITLE
certificatemanager: upgrade lambda runtime from node14

### ISSUE THREAD

**Issue by mbp** [aws/aws-cdk#25335]
### Describe the bug

DnsValidatedCertificate uses Lambda function with runtime NODEJS_14_X which is EOL in a few days.

https://github.com/aws/aws-cdk/blob/v2-release/packages/aws-cdk-lib/aws-certificatemanager/lib/dns-validated-certificate.ts#L112

### Expected Behavior

That the DnsValidatedCertificate uses NODEJS_16_x or higher version.

### Current Behavior

Uses NODEJS_14_x

### Reproduction Steps

```
const authCertificate = new acm.DnsValidatedCertificate(
      this,
      // ...
);
      ```

### CDK CLI Version

2.77.0

### Node.js Version

16

### OS

Linux

### Language

Typescript

**Comment by pahud** [comment]
Yes we should bump the version.

related to https://github.com/aws/aws-cdk/pull/24916
