### ISSUE TITLE
CfnTaskDefinition_.AddPropertyOverride() doesn't handle JSON correctly in C#

### ISSUE THREAD

**Issue by janaka** [aws/aws-cdk#2533]
**Describe the bug**
Unlike in JS there's no native JSON support in C# (.NET Core 2.x). Passing JSON as a string into the value parameter results in incorrectly formatted CloudFormation JSON. 

```csharp 
void CfnResource.AddPropertyOverride(string propertyPath, object value)
```

See code and output below for example and reproduction.

Note how the value is wrapped in double quotes and all the quote escaping is still present. I can replace the double quote with single quote to avoid the escaping there but the outer most double quotes cannot be eliminated (or at least I don't know how)

**To Reproduce**
Code:
```csharp

        public static void AddAppMeshProxyConfiguration(TaskDefinition TaskDefinition)
        {
            var cfnTaskDef = (CfnTaskDefinition_)TaskDefinition.Node.FindChild("Resource");

            var jsonString = @"{""type"": ""APPMESH"",""containerName"": ""envoy"",""properties"": [{""name"": ""IgnoredUID"",""value"": ""1337""},{""name"": ""ProxyIngressPort"",""value"": ""15000""},{""name"": ""ProxyEgressPort"",""value"": ""15001""},{""name"": ""AppPorts"", ""value"": ""80""},{""name"": ""EgressIgnoredIPs"", ""value"": ""169.254.170.2,169.254.169.254""}]}";

            cfnTaskDef.AddPropertyOverride("proxyConfiguration", jsonString);

        }
```

Output:
```json
"proxyConfiguration": "{\"type\": \"APPMESH\",\"containerName\": \"envoy\",\"properties\": [{\"name\": \"IgnoredUID\",\"value\": \"1337\"},{\"name\": \"ProxyIngressPort\",\"value\": \"15000\"},{\"name\": \"ProxyEgressPort\",\"value\": \"15001\"},{\"name\": \"AppPorts\", \"value\": \"80\"},{\"name\": \"EgressIgnoredIPs\", \"value\": \"169.254.170.2,169.254.169.254\"}]}"
```
**Expected behavior**
Correctly formatted json in the CF template output.

**Version:**
 - OS: macOS
 - C# .NET Core 2.x
 - CDK Version: 0.31.0

**Comment by SomayaB** [comment]
I'm sorry this has gone so long without response. Are you still experiencing this issue?

**Comment by SomayaB** [comment]
Closing this issue since there hasn't been activity on it in a while. Feel free to reopen if you are still experiencing this issue.
