### ISSUE TITLE
aws_sam.CfnFunction.SQSEventProperty: Adding  ScalingConfig in  AWS::Lambda::EventSourceMapping

### ISSUE THREAD

**Issue by next-cesarenriquegonzales** [aws/aws-cdk#25344]
### Describe the feature

It's a very important parameter for functions created sam module. Nowly it's possible using cloudformation template.  

### Use Case

Scaling configuration of SQS pollers to control the invoke rate and set maximum concurrent invokes.

### Proposed Solution

ADD parameter  ScalingConfig to SQSEventProperty

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.77.0

### Environment details (OS name and version, etc.)

mac

**Comment by peterwoodworth** [comment]
There's an automatic process for this to occur - if it exists in cloudformation, we will support it very soon. You can already use this if you manually set the property with escape hatches

**Comment by next-cesarenriquegonzales** [comment]
Many thanks for your support, but I don't understand very well when you say "You can already use this if you manually set the property with escape hatches" Could you type an example of that? Or send me an link .....
Many thanks again.
Regards

**Comment by peterwoodworth** [comment]
The docs here should help out 🙂  https://docs.aws.amazon.com/cdk/v2/guide/cfn_layer.html#cfn_layer_raw

**Comment by next-cesarenriquegonzales** [comment]
Thanks, but I think there is a litle mistake, when I said, " Nowly it's possible using cloudformation template." I refer to cloudformation template out of Cdk constructor L1, so, your recommendation is about the parameter is in L1 constructor,  in this case, it doesn't applied because I use CfnFunction of sam module, in this constructor the parameter  ScalingConfig doesn't exist. I created this issue because I'd like to know if someone can add it to module.
Many thanks!!
Regards

**Comment by peterwoodworth** [comment]
You can use escape hatches to manually synthesize any arbitrary property in the CloudFormation template, please view the documentation I linked, all you have to do is use the `addPropertyOverride()` method.

example:
```
const fn = new CfnFunction(this, 'fn', {...});
fn.addPropertyOverride('ScalingConfig', ...);
```

As I mentioned above, there's an automatic process that ingests new cloudformation properties when they're available. This should be out within the next version or two

**Comment by next-cesarenriquegonzales** [comment]
Many thanks, it works!!!! :D
