### ISSUE TITLE
(aws-events): Validate events rule name

### ISSUE THREAD

**Issue by pyto86pri** [aws/aws-cdk#25352]
### Describe the feature

The events rule name should be validated. Currently, event rule names are limited in the number of characters and characters that can be used.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-rule.html#cfn-events-rule-name

### Use Case

Notice bugs without deploying. It's useful for validation in CI or other.

### Proposed Solution

Add rule name validation in Rule class.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.77.0

### Environment details (OS name and version, etc.)

MacOS

**Comment by pahud** [comment]
Thank you for your report and PR!
