### ISSUE TITLE
‼️ NOTICE: CDK Pipelines creates role with overly permissive trust policy

### ISSUE THREAD

**Issue by rix0rrr** [aws/aws-cdk#25356]
## What is the issue?

Starting with versions 1.158.0 and 2.26.0 (released 2022-05-30), the CDK Pipelines construct library creates a role that allows every identity in the same account with the appropriate `sts:AssumeRole` permissions to assume it. For example, this can happen if another Role in your account has `sts:AssumeRole` permissions on `Resource: "*"`.

## What is the impact?

This role can be used to trigger CodeBuild Projects in the pipeline out of band without a source change, on different Pipeline artifacts than the Project is expecting (older versions of the software, or artifacts intended for different CodeBuild Projects).

What a potential attacker could do with this ability depends on what the CodeBuild Projects in your pipeline are configured to do, and what kind of permissions those Projects have.

## How do I know if I'm affected?

You are affected if you are using the `pipelines.CodePipeline` construct, and your version of:

* `@aws-cdk/pipelines` is between `1.158.0` and `1.200.0`; OR
* `aws-cdk-lib` is between `2.26.0` and `2.77.0`.

## How do I resolve this?

The issue has been fixed in versions v1.200.0, v2.77.0 (released 2022-04-27). Please upgrade to a fixed version as soon as possible. See [Managing Dependencies](https://docs.aws.amazon.com/cdk/v2/guide/manage-dependencies.html) in the CDK Developer Guide for instructions on how to do this.

**Comment by hatchetation** [comment]
Just in case anyone else is confused - the dates in this notice should read 2023, not 2022.

**Comment by rix0rrr** [comment]
> Just in case anyone else is confused - at least one of the dates in this notice should read 2023, not 2022.

Doh! Thanks
