### ISSUE TITLE
aws-iam: Role.fromRoleName no longer supports AWS created roles

### ISSUE THREAD

**Issue by ChrisLane** [aws/aws-cdk#25360]
### Describe the bug

I import an AWS created role and its ARN via the following code:
```js
iam.Role.fromRoleName(
            this,
            "transfer-logging-role",
            "service-role/AWSTransferLoggingAccess").roleArn
```

### Expected Behavior

`Rolefrom.fromRoleName` is able to generate the correct ARN for the automatically created "AWSTransferLoggingAccess" role.

### Current Behavior

Previously, I relied on what I now realise may have been a bug in CDK.

The role created by AWS is called "AWSTransferLoggingAccess" but has the ARN "arn:aws:iam::{accountId}:role/service-role/AWSTransferLoggingAccess".
By importing the role with the name"service-role/AWSTransferLoggingAccess", CDK produced the correct ARN.

Now that I have updated CDK, I get the following error:
```
Error: The role name service-role/AWSTransferLoggingAccess does not match the IAM conventions.
```

If I change the code to import the role with the name "AWSTransferLoggingAccess" I do not get this error but then the ARN is incorrect as it takes the form of "arn:aws:iam::{accountId}:role/AWSTransferLoggingAccess".

### Reproduction Steps

1. Create an AWS Transfer Family server to generate the logging access role.
2. Attempt to import the role by name and get its ARN via CDK

### Possible Solution

I think CDK should either fix the logic that gets the ARN for a role or relax the rules around what role names can be imported.

### Additional Information/Context

I did not have this issue on CDK v2.63.2

### CDK CLI Version

2.77.0

### Node.js Version

19.9.0

### OS

Arch Linux

### Language

Typescript

### Language Version

JavaScript

**Comment by peterwoodworth** [comment]
This change was introduced in `2.73.0` from [this PR](https://github.com/aws/aws-cdk/pull/24549)

Roles can come from more than just user created roles, which is where the regex used came from. CC @TheRealAmazonKendra 

Thanks for reporting, we'll get this fixed for next release

**Comment by tfentonz** [comment]
I have the same issue with `2.77.0` using fromRoleName.

```ts
    const serviceRoleForImageBuilder = iam.Role.fromRoleName(
      this,
      'ServiceRoleForImageBuilder',
      'aws-service-role/imagebuilder.amazonaws.com/AWSServiceRoleForImageBuilder',
    );
```

Previously was working on `2.69.0`.

**Comment by peterwoodworth** [comment]
Yes, this was fixed and will be included in our next release @tfentonz
