### ISSUE TITLE
OpenSearch: Add support for OpenSearch 2.5

### ISSUE THREAD

**Issue by vaughngit** [aws/aws-cdk#25364]
### Describe the feature

AWS Launched the support for Amazon OpenSearch Service 2.5 as per the announcement here: https://aws.amazon.com/about-aws/whats-new/2023/03/amazon-opensearch-service-opensearch-version-2-5/ 

AWS CDk does not support the latest version yet, and having issue launching the OpenSearch cluster with CDK using 2.5

### Use Case

I would like to launch latest OpenSearch version using CDK

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.74

### Environment details (OS name and version, etc.)

Windows 10

**Comment by khushail** [comment]
Hi @vaughngit , thanks for reaching out with this request. CDK Team always works on providing support for latest services, this would be supported/updated soon.

**Comment by pahud** [comment]
@vaughngit 

Before we have a PR for that, you can define your custom version with [openSearch](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_opensearchservice.EngineVersion.html#static-openwbrsearchversion) static method like:

```ts
version: opensearch.EngineVersion.openSearch('OpenSearch_2.5'),
```

**Comment by vaughngit** [comment]
> @vaughngit
> 
> Before we have a PR for that, you can define your custom version with [openSearch](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_opensearchservice.EngineVersion.html#static-openwbrsearchversion) static method like:
> 
> ```ts
> version: opensearch.EngineVersion.openSearch('OpenSearch_2.5'),
> ```

I attempted this approach in the interim but received this error as output: 
 
OpenSearchDomain (OpenSearchDomain) Resource handler returned message: "Invalid request provided: 2 validation errors detected: Value 'OpenSearch_OpenSearch_2.5' at 'engineVersion' failed to satisfy constraint: Member must satisfy regular expression pattern: ^Elasticsearch_[0-9]{1}\.[0-9]{1,2}$|^OpenSearch_[0-9]{1,2}\.[0-9]{1,2}$; Value 'OpenSearch_OpenSearch_2.5' at 'engineVersion' failed to satisfy constraint: Member must have length less than or equal to 18 (Service: OpenSearch, Status Code: 400, Request ID: )" (RequestToken: , HandlerErrorCode: InvalidRequest)
