### ISSUE TITLE
Hotswap doesn't update SSM parameter environment variables properly

### ISSUE THREAD

**Issue by fongchinghinunsw** [aws/aws-cdk#25387]
### Describe the bug

My lambda function is like the following.
`new NodejsFunction(this, "some-id", { environment: { VAR1: StringParameter.valueForStringParameter(this, "/au/parameter/cool-parameter") } })`

If I deploy the function before and apply hotswap, the deployment works fine. However, if I add a new environment variable to the function and use hotswap to deploy it. The value of the variable VAR1 is resolved to the path (i.e. `/au/parameter/cool-parameter`) instead of the true value in the parameter store.

### Expected Behavior

CDK should be able to resolve the right SSM parameter value.

### Current Behavior

The value of the variable VAR1 is resolved to the path (i.e. `/au/parameter/cool-parameter`) instead of the true value in the parameter store.

### Reproduction Steps

```ts
new NodejsFunction(this, "some-id", { environment: { VAR1: StringParameter.valueForStringParameter(this, "/au/parameter/cool-parameter") } })
```

### CDK CLI Version

2.69.0

### Node.js Version

16

### OS

macOS Ventura 13.2.1

### Language

Typescript

**Comment by pahud** [comment]
According to [this](https://github.com/aws/aws-cdk/tree/main/packages/aws-cdk#hotswap-deployments-for-faster-development), I believe hotswap has not supported SSM parameter environment variables yet. I am making this p2 feature request and please help us prioritize by upvotes.

**Comment by peterwoodworth** [comment]
@pahud In this use case, they aren't hotswapping an SSM parameter, but are instead using a [dynamic references](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/dynamic-references.html) to specify an environment variable on a lambda function. When we're hotswapping, we're not using CloudFormation deploy, we're using the Lambda API https://github.com/aws/aws-cdk/blob/d8272ef30d64777f54a7a283caf49b1dc67be927/packages/aws-cdk/lib/api/hotswap/lambda-functions.ts#L98

I'm not sure there's a good solution here that works both for CloudFormation deployments and for hotswapping
