### ISSUE TITLE
(cdk-assets): `cdk depoly --concurrency N` still sometimes causes ENOENT error to occur

### ISSUE THREAD

**Issue by tockn** [aws/aws-cdk#25380]
### Describe the bug

There are still similar issues of #23290  occurring despite the fixes for #23677 and #24026.

### Expected Behavior

The deployment succeeds without any errors.

### Current Behavior

`ENOENT: no such file or directory, unlink ...` error occurs occasionally.

![Group 103](https://user-images.githubusercontent.com/29294540/234319839-10b3e1e2-c071-43e8-b18d-64df5069508b.png)

### Reproduction Steps

same as https://github.com/aws/aws-cdk/issues/23290 !

### Possible Solution

I have created a pull request to fix this issue. I would appreciate it if you could review it and merge it.
https://github.com/aws/aws-cdk/pull/25293

### CDK CLI Version

2.75.0 (build 37c53d6)

### Node.js Version

v16.17.0

### OS

Linux

### Language

Typescript

**Comment by pahud** [comment]
Thank you for your report. I noticed your PR has passed the CI. I believe the core team will review your PR soon.

**Comment by ruvimrd** [comment]
I get this issue running node v16, upgrading to node 18 resolves the issue for me. Curious if anyone else gets the same result?
