### ISSUE TITLE
aws-batch-alpha: Missing ephemeralStorage configuration

### ISSUE THREAD

**Issue by gael-ft** [aws/aws-cdk#25393]
### Describe the bug

AWS Batch using ECS Fargate should support setting the `ephemeralStorage` (< 200GiB).

I can't find any ways to do it currently

### Expected Behavior

Having a `ephemeralStorage` property in `EcsFargateContainerDefinition`.

### Current Behavior

No way to configure `ephemeralStorage`

### Reproduction Steps

Create a `new EcsJobDefinition(...)` with `new EcsFargateContainerDefinition(...)` as `container` property

### CDK CLI Version

2.77.0 (build 06a0b19)

### Node.js Version

v16.13.0

### OS

MacOS

### Language

Typescript

**Comment by pahud** [comment]
We probably can add it in [EcsContainerDefinitionProps](https://github.com/aws/aws-cdk/blob/d8272ef30d64777f54a7a283caf49b1dc67be927/packages/%40aws-cdk/aws-batch-alpha/lib/ecs-container-definition.ts#L376). Are you interested to submit a PR for that?

**Comment by kaizencc** [comment]
@sumupitchayan @daschaa i mean it looks like you both created a PR for this issue at the exact same time. But maybe Sumu was first by minutes

**Comment by daschaa** [comment]
@kaizencc Thanks for notifying. I'll close mine. 👍🏼
