### ISSUE TITLE
(aws-dynamodb): replica-provider has a hardcoded `aws` partition in the IAM policy

### ISSUE THREAD

**Issue by jacklin213** [aws/aws-cdk#25407]
### Describe the bug

In f35b70b, a new policy statement was introduced to add permissions `'dynamodb:DeleteTable', 'dynamodb:DeleteTableReplica'` to allow for custom resource to delete the replication Table. However the resource arn was hardcoded to the `aws` partition meaning that this code will not work in other partitions such as `aws-cn`. (See Line 100 below)

https://github.com/aws/aws-cdk/blob/04323c44da6b8821a361a36bb2feadde77d54c35/packages/aws-cdk-lib/aws-dynamodb/lib/replica-provider.ts#L97-L108

The error we see when the CDK stack is deployed to CN:
```
Partition "aws" is not valid for resource "arn:aws:dynamodb:cn-northwest-1:1234567890:table/MyTable". (Service: AmazonIdentityManagement; Status Code: 400; Error Code: MalformedPolicyDocument; Request ID: -snip-; Proxy: null)
```

### Expected Behavior

The policy should be create inferring the partition when specifying the tableArn for the resource of the new policy statement.

### Current Behavior

The policy creation fails in CN partition as the partition is hardcoded to standard partition.

### Reproduction Steps

1. Create a CDK repo that only has 1 `Table` resource.
2. As part of the Table resource provide `replicationRegions` and have either `cn-north-1` or `cn-northwest-1`.
3. Synth the repo and attempt to deploy the stack to China

### CDK CLI Version

2.73.0

### Node.js Version

18.0.0

### OS

Linux

### Language

Typescript

**Comment by peterwoodworth** [comment]
Thanks for the report, you're right that this is hardcoded. Should use `Aws.PARTITION` instead

**Comment by jacklin213** [comment]
Will get a PR out for this shortly

**Comment by jacklin213** [comment]
The current workaround for anyone experiencing this issue is to version lock to `aws-cdk-lib: 2.71.0` . This will remove the new IAM policy that was introduced with the hardcoded partition
