### ISSUE TITLE
stepfunctions: easy access to fields in execution context object

### ISSUE THREAD

**Issue by suhussai** [aws/aws-cdk#25415]
### Describe the feature

Add functions for accessing fields like `name` or `id` from the execution context object. We already have a function for accessing the Task Token: https://github.com/aws/aws-cdk/blob/96bb8ce6b3a45daf47d4d4dbf91fd6b69988bb7b/packages/aws-cdk-lib/aws-stepfunctions/lib/fields.ts#L75

### Use Case

For accessing the task token, we can do something like this:

```
sfn.JsonPath.taskToken
```

However, when it comes to accessing something like the name of the Execution, we have to do something like this:

```
sfn.JsonPath.stringAt("$$.Execution.Name")
```

### Proposed Solution

Add functions for getting all of the remaining fields from the context object.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.72.0

### Environment details (OS name and version, etc.)

macOS 12.6.5

**Comment by peterwoodworth** [comment]
Thanks for the request, we'll probably need contributor support for this feature to be realized

**Comment by tejasmr** [comment]
I can help with this if no one is already working on this

Just for clarification: Considering the example JSON for context object

```json
{
    "Execution": {
        "Id": "arn:aws:states:us-east-1:123456789012:execution:stateMachineName:executionName",
        "Input": {
           "key": "value"
        },
        "Name": "executionName",
        "RoleArn": "arn:aws:iam::123456789012:role...",
        "StartTime": "2019-03-26T20:14:13.192Z"
    },
    "State": {
        "EnteredTime": "2019-03-26T20:14:13.192Z",
        "Name": "Test",
        "RetryCount": 3
    },
    "StateMachine": {
        "Id": "arn:aws:states:us-east-1:123456789012:stateMachine:stateMachineName",
        "Name": "name"
    },
    "Task": {
        "Token": "h7XRiCdLtd/83p1E0dMccoxlzFhglsdkzpK9mBVKZsp7d9yrT1W"
    }
}
```

Assuming that we have to implement functions for the below fields. Let me know if there needs to be any additions/deletions to the below list. 

1. $$.Execution.Id - type string 
2. $$.Execution.Input - `should the type be any?`
3. $$.Execution.Name - type string 
4. $$.Execution.RoleArn - type string 
5. $$.Execution.StartTime - `should the type be string or convert it to Date?`
6. $$.State.EnteredTime - `should the type be Date or convert it to Date?`
7. $$.State.Name - type string
8. $$.State.RetryCount - type number
9. $$.StateMachine.Id - type string
10. $$.StateMachine.Name - type string
11. ~~$$.Task.Token - type string~~ - ALREADY IMPLEMENTED

Need clarification for the questions highlighted above regarding the types the functions should return.

Cheers,
Tejas
