### ISSUE TITLE
aws_fms: unable to use CfnResourceSet

### ISSUE THREAD

**Issue by bsaab** [aws/aws-cdk#25420]
### Describe the bug

I am unable to use class CfnResourceSet from aws-cdk-lib.aws_fms to create resource sets in AWS FMS via CDK. 

I have the latest cdk version 2.77.0

### Expected Behavior

Expected behavior is to be able to use class CfnResourceSet as outlined in https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_fms.CfnResourceSet.html

### Current Behavior

Property 'CfnResourceSet' does not exist on type 'typeof import("<local-path>/node_modules/aws-cdk-lib/aws-fms/index")'.ts(2339)

### Reproduction Steps

import * as fms from 'aws-cdk-lib/aws-fms';
export class ResourceSetStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);
  
      const resource_Set = new fms.CfnResourceSet(this, fms_resourceset, {
        name: 'Name',
        resourceTypeList: somelist,
        description: somedescription,
        resources: AWS::NetworkFirewall::Firewall
      });

  }
}

### CDK CLI Version

2.77.0 (build 06a0b19)

### Node.js Version

v18.16.0

### OS

macOs

### Language

Typescript

**Comment by peterwoodworth** [comment]
This synthesizes for me on latest version,

```
import * as fms from 'aws-cdk-lib/aws-fms';

export class TestingStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    new fms.CfnResourceSet(this, 'ResourceSet', {
      name: 'name',
      resourceTypeList: ['AWS::EC2::Instance'],
    })
  }
}

```

try reinstalling your packages?

**Comment by peterwoodworth** [comment]
reinstalling packages worked for customer after following up directly
