### ISSUE TITLE
Eventbridge rule allows pattern matching for `resources` argument

### ISSUE THREAD

**Issue by eugeneh101** [aws/aws-cdk#25424]
### Describe the feature

When creating a Eventbridge rule (in Python's version of `aws_cdk`), the `resources` argument does not allow pattern matching, which I propose that it should. For example, in the AWS console, you can manually create a pattern that allows pattern matching on the `resources` attribute. Currently `aws_cdk` only allows pattern matching on `detail` argument.

Here is the sample code that I wish would work:
```python
from aws_cdk import (
    App,
    Stack,
    aws_events as events,
)


class TempStack(Stack):
    def __init__(
        self, scope, construct_id, **kwargs
    ) -> None:
        super().__init__(scope, construct_id, **kwargs)

        self.eventbridge_rule = events.Rule(self, "EventBridgeRule")
        self.eventbridge_rule.add_event_pattern(
            resources=[{"suffix": "SOME_REDSHIFT_CLUSTER_NAME"}],  # wish this line would work
        )


app = App()
TempStack(app, "TempStack")
app.synth()
```
Both `event_pattern` argument in the `Rule` constructor (using the `EventPattern` class) and `.add_event_pattern()` method does not support pattern matching for `resources` argument.

As an extra note, it appears that `aws_cdk` currently only supports pattern matching on the `detail` argument since the type annotation is `Optional[Mapping[str, Any]]`. `resources` argument has the type annotation `Optional[Sequence[str]]`, which is the same for `account`, `detail_type`, `id`, `region`, `source`, `time`, and `version` arguments. If an upgrade is made to allow patching matching on the `resources` argument, hopefully that can also be made for the other aforementioned arguments. I presume the other arguments allow pattern matching when created manually in the AWS console.

### Use Case

I am creating an Eventbridge rule to get the events that are from `redshift-data` API. Specifically on the event's `resources` attribute, I am getting events that are from a specific Redshift cluster. For example, the event will have `resources` set to             "arn:aws:redshift:us-east-1:...:cluster:redshiftcluster-u94ov1ux9grq". However since the Redshift cluster does not seem to have an ARN attribute (but _does_ have the cluster name attribute), I want to be able to create a `Rule` in cdk where `resources` attribute is pattern matching to `{"suffix": REDSHIFT_CLUSTER_NAME_HERE}`. In the AWS console, I was able to do this by hard coding the cluster name when manually creating the Eventbridge rule. However, it would be nice in cdk to programatically create the rule since the cdk stack has access to the Redshift cluster name, so no hard coding would be needed.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.77.0 (build 06a0b19)

### Environment details (OS name and version, etc.)

macOs Ventura 13.0

**Comment by peterwoodworth** [comment]
Have you tried the [`Match`](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_events.Match.html#static-exists) class?

[From the docs:](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_events-readme.html#rule)

> To define a pattern, use the matcher API, which provides a number of factory methods to declare different logical predicates. For example, to match all S3 events for objects larger than 1024 bytes, stored using one of the storage classes Glacier, Glacier IR or Deep Archive and coming from any region other than the AWS GovCloud ones:

```ts
const rule = new events.Rule(this, 'rule', {
  eventPattern: {
    detail: {
      object: {
        // Matchers may appear at any level
        size: events.Match.greaterThan(1024),
      },

      // 'OR' condition
      'source-storage-class': events.Match.anyOf(
        events.Match.prefix("GLACIER"),
        events.Match.exactString('DEEP_ARCHIVE'),
      ),
    },
    detailType: events.Match.equalsIgnoreCase('object created'),

    // If you prefer, you can use a low level array of strings, as directly consumed by EventBridge
    source: ['aws.s3'],

    region: events.Match.anythingButPrefix('us-gov'),
  },
});
```

**Comment by eugeneh101** [comment]
@peterwoodworth Thanks for the getting back to much so quickly.

Yep, I tried with `Match` and worked. Here's the code:
```python
        self.eventbridge_rule.add_event_pattern(
            resources=events.Match.suffix(value="SOME_REDSHIFT_CLUSTER_NAME")
        )
```

I'm surprised this works since I thought it would just resolve to `[{"suffix": "SOME_REDSHIFT_CLUSTER_NAME"}]` anyways. But it turns out that it actually resolves to `['#{Token[TOKEN.661]}']`, which satisfies the type hint `Optional[Sequence[str]]`.
I actually used `Match` in `detail`, but then I switched to explicitly using `[{"prefix": "SOME_STRING_HERE"}]` because I thought it would be more obvious to other readers. Hence I thought I would use `[{"suffix "SOME_REDSHIFT_CLUSTER_NAME"}]` in `resources`, but you can just use `Match.suffix()` instead.

Feel free to close this Issue. Thank you.

**Comment by peterwoodworth** [comment]
We have another ticket open that aims to clarify this behavior, you're not the only one to not know this functionality existed 🙂

**Comment by eugeneh101** [comment]
@peterwoodworth 
Haha, got it. My suggestion is if you can update the documentation on https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_events/Rule.html and/or https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_events/EventPattern.html#aws_cdk.aws_events.EventPattern to mention `Match`, then that would clarify the behavior.

The type hint for `resource` (and other parameters) says `Optional[Sequence[str]]`. I did not know `Match` would generate such a value; I thought it would stay a `Match` type.
