### ISSUE TITLE
(quicksight): aws_quicksight/__init__.py is 69 megabytes

### ISSUE THREAD

**Issue by dsturnbull** [aws/aws-cdk#25425]
### Describe the bug

The size of the file ballooned from 830K to 69M

aws-cdk-lib-2.71.0/src/aws_cdk/aws_quicksight 830K
aws-cdk-lib-2.72.0/src/aws_cdk/aws_quicksight 69M

packages/@aws-cdk/cfnspec/spec-source/specification/000_cfn/000_official/000_AWS_QuickSight.json is 37k loc, compared to the next biggest: EC2 is 9k.

a 69 megabyte file is unusable from e.g. the pylance tool.

### Expected Behavior

Type hinting to work without trying and failing to process gigantic files.

### Current Behavior

IDE unable to provide support for quicksight.

### Reproduction Steps

Download published aws-cdk dist from e.g. https://pypi.org/project/aws-cdk-lib/2.77.0/#files, where the version is >= 2.72.0.

Extract, look at the size of src/aws_cdk/aws_quicksight

### CDK CLI Version

2.77.0 (build 06a0b19)

### Node.js Version

v18.16.0

### OS

macOS

### Language

Python

### Language Version

Python (3.10.9)

**Comment by peterwoodworth** [comment]
Thanks for reporting, closing in favor of https://github.com/aws/jsii/issues/4066. Please take further discussion and comments there
