### ISSUE TITLE
(aws_s3): serverAccessLogsBucket still uses ACL and causes error in deployment

### ISSUE THREAD

**Issue by YonaMoreda** [aws/aws-cdk#25455]
### Describe the issue

Hello CDK Devs,

As the use of bucket policy over bucket ACL has come to full effect since April, we are having issues setting up serverAccessLogsBucket() as it still uses ACL to permit log delivery. Particularly this method: [allowLogDelivery](https://github.com/aws/aws-cdk/blob/6f2572f4deef23df96009758c91f9ba1846175b9/packages/%40aws-cdk/aws-s3/lib/bucket.ts#L2077) which still uses accessControl. 

This issue was mentioned in #19603 while back however the solution was workaround which does not seem to be wise to have require the use of this workaround each time a user wants access logging enabled. Your input would be greatly appreciated, thank you!

### Links

https://github.com/aws/aws-cdk/blob/6f2572f4deef23df96009758c91f9ba1846175b9/packages/%40aws-cdk/aws-s3/lib/bucket.ts#L2077

**Comment by peterwoodworth** [comment]
Use a feature flag https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_s3-readme.html#allowing-access-log-delivery-using-a-bucket-policy-recommended
