### ISSUE TITLE
@aws-cdk/aws-apigatewayv2-alpha: enableTracing (for XRay)

### ISSUE THREAD

**Issue by akil-rails** [aws/aws-cdk#25467]
### Describe the feature

The @aws-cdk/aws-apigatewayv2-alpha is great for creating HttpApi, but it is missing the option to enable x-ray tracing, which is available in the StageProps v1 version (enableTracing=true)

### Use Case

X-ray tracing is useful, and having it in the construct will make it simpler to enable it.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

@aws-cdk/aws-apigatewayv2-alpha@2.77.0-alpha.0

### Environment details (OS name and version, etc.)

nodejs

**Comment by pahud** [comment]
From [doc](https://docs.aws.amazon.com/xray/latest/devguide/xray-services-apigateway.html):
>X-Ray only supports tracing for REST APIs through API Gateway.

I am afraid HTTP API is not supported?
