### ISSUE TITLE
aws_cdk: No module named 'aws_cdk.asset_awscli_v1'

### ISSUE THREAD

**Issue by jomach** [aws/aws-cdk#25461]
### Describe the bug

bash-5.1$ pip freeze | grep aws
aws-cdk-lib==2.78.0
aws-cdk.asset-awscli-v1==2.2.162
aws-cdk.asset-kubectl-v20==2.1.1
aws-cdk.asset-node-proxy-agent-v5==2.0.136
bash-5.1$ python
Python 3.10.11 (main, Apr  6 2023, 01:17:26) [GCC 11.2.1 20220219] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from aws_cdk import App
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/node/.local/lib/python3.10/site-packages/aws_cdk/__init__.py", line 1422, in <module>
    from ._jsii import *
  File "/home/node/.local/lib/python3.10/site-packages/aws_cdk/_jsii/__init__.py", line 13, in <module>
    import aws_cdk.asset_awscli_v1._jsii
ModuleNotFoundError: No module named 'aws_cdk.asset_awscli_v1'

### Expected Behavior

from aws_cdk import App should work

### Current Behavior

s

### Reproduction Steps

bash-5.1$ python
Python 3.10.11 (main, Apr  6 2023, 01:17:26) [GCC 11.2.1 20220219] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from aws_cdk import App
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/node/.local/lib/python3.10/site-packages/aws_cdk/__init__.py", line 1324, in <module>
    from ._jsii import *
  File "/home/node/.local/lib/python3.10/site-packages/aws_cdk/_jsii/__init__.py", line 13, in <module>
    import aws_cdk.asset_awscli_v1._jsii
ModuleNotFoundError: No module named 'aws_cdk.asset_awscli_v1'

### Possible Solution

s

### Additional Information/Context

s

### CDK CLI Version

bash-5.1$ cdk version
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!                                                                                                                  !!
!!  Node 19 is approaching end-of-life and will no longer be supported in new releases after 2023-06-01.            !!
!!  Please upgrade to a supported node version as soon as possible.                                                 !!
!!                                                                                                                  !!
!!  This software is currently running on node v19.9.0.                                                             !!
!!  As of the current release of this software, supported node releases are:                                        !!
!!  - ^18.0.0 (Planned end-of-life: 2025-04-30)                                                                     !!
!!  - ^16.3.0 (Planned end-of-life: 2023-09-11)                                                                     !!
!!  - ^19.0.0 (Planned end-of-life: 2023-06-01) [DEPRECATED]                                                        !!
!!                                                                                                                  !!
!!  This warning can be silenced by setting the JSII_SILENCE_WARNING_DEPRECATED_NODE_VERSION environment variable.  !!
!!                                                                                                                  !!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2.69.0 (build 60a5b2a)

### Node.js Version

bash-5.1$ npm --version
9.6.3

### OS

apk (docker)

### Language

Python

### Language Version

bash-5.1$ python
Python 3.10.11 (main, Apr  6 2023, 01:17:26) [GCC 11.2.1 20220219] on linux
Type "help", "copyright", "credits" or "license" for more information.

### Other information

s

**Comment by pahud** [comment]
Hi

I can't reproduce this in my environment with 2.78.0.


(.venv) pahud@MBA issue-triage-py % python
Python 3.9.6 (default, Mar 10 2023, 20:16:38) 
[Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from aws_cdk import App
>>> 

Can you share the full steps to reproduce this error?

**Comment by jomach** [comment]
> Hi
> 
> I can't reproduce this in my environment with 2.78.0.
> 
> ```
> (.venv) pahud@MBA issue-triage-py % python
> Python 3.9.6 (default, Mar 10 2023, 20:16:38) 
> [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
> Type "help", "copyright", "credits" or "license" for more information.
> >>> from aws_cdk import App
> >>> 
> ```
> 
> Can you share the full steps to reproduce this error?

I mean you have other versions.  

Python 3.10 vs 3.9
cdk 2.69 vs cdk 2.78

can you reproduce it ?

**Comment by pahud** [comment]
@jomach 

I still can't reproduce it with python 3.10 and cdk 2.69.0

<img width="747" alt="image" src="https://user-images.githubusercontent.com/278432/236853484-1b83c83b-ce91-410c-a1cc-8f51cf2fb951.png">

**Comment by jomach** [comment]
Sorry, seems to be something in our infrastructure from docker builds. Thanks can be close.

**Comment by symphonymarie** [comment]
> Sorry, seems to be something in our infrastructure from docker builds. Thanks can be close.

If you happen to see this, what was the issue for you? I'm having the same problem.
