### ISSUE TITLE
@aws-cdk/aws-cognito-identitypool-alpha: allowUnauthenticatedIdentities still creates IAM role

### ISSUE THREAD

**Issue by markmansur** [aws/aws-cdk#25470]
### Describe the bug

Hello!

When creating an `IdentityPool` that I only want authenticated users to access I set `allowUnauthenticatedIdentities` to `false`. However, this still ends up creating an IAM role for unauthenticated users, eventhough I specified I don't need it and it's not required. 

### Expected Behavior

When setting `allowUnauthenticatedIdentities` to `false`, an IAM role for unauthenticated users should not be synthesized.

### Current Behavior

When setting `allowUnauthenticatedIdentities` to `false`, an IAM role for unauthenticated users is being synthesized.

### Reproduction Steps

```
const stack = new Stack();
const identityPool = new IdentityPool(stack, 'TestIdentityPool');
```

### Possible Solution

Check if `allowUnauthenticatedIdentities` is `false`. If so, do not synthesize the unauthenticated IAM role.

### CDK CLI Version

2.78.0

### Node.js Version

16.16.0

### OS

MacOS

### Language

Typescript

**Comment by pahud** [comment]
Yes I believe we should fix this:

https://github.com/aws/aws-cdk/blob/b76c18287ce452f5b5d27af68028e9f6b47d67b5/packages/%40aws-cdk/aws-cognito-identitypool-alpha/lib/identitypool.ts#L433

Are you interested to submit a PR for that?

**Comment by markmansur** [comment]
Yeah I'll submit a PR

**Comment by TheRealAmazonKendra** [comment]
A redesign of this is in progress.

**Comment by markmansur** [comment]
Okay, I'll wait for that. Is there a tracking issue?

**Comment by markmansur** [comment]
#25204?

**Comment by Leo10Gama** [comment]
This is the the expected behaviour of IdentityPools. When `allowUnauthenticatedIdentities` is set to false, it will still create the unauthenticated role, but more importantly, it sets "Guest Status" to inactive in the console, which is what the parameter is meant to do. Even as shown in the console, it's possible to both have a guest role and have guest access disabled, so there is no reason to change this behaviour.
