### ISSUE TITLE
aws-cdk-lib/aws-cloudwatch: Tags don't attach to CloudWatch alarms

### ISSUE THREAD

**Issue by dacampos1** [aws/aws-cdk#25489]
### Describe the bug

I am trying to add tags to my Cloudwatch Alarm. I am using the Alarm construct from `aws-cdk-lib/aws-cloudwatch`. The parent stack has a set of default tags that all other resources inherit, except for Cloudwatch Alarms. I have also tried adding tags to this resource manually, but it does not work.

### Expected Behavior

Tags can be added to the resource and verified on the AWS console.

### Current Behavior

The tags don't attach to the resource.

### Reproduction Steps

```
import * as cdk from 'aws-cdk-lib';
import * as sns from 'aws-cdk-lib/aws-sns';
import * as cloudwatch from 'aws-cdk-lib/aws-cloudwatch';
import { Construct } from 'constructs';

export class MyStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);
    const topic = new sns.Topic(this, 'Topic', {
      displayName: 'My SNS topic',
    });
    const _alarm = new cloudwatch.Alarm(this, 'Alarm', {
      metric: topic.metricNumberOfMessagesPublished(),
      threshold: 10,
      evaluationPeriods: 1,
      alarmName: 'My SNS alarm',
      alarmDescription: 'Triggered when message count exceeds 10',
      comparisonOperator:
        cloudwatch.ComparisonOperator.GREATER_THAN_OR_EQUAL_TO_THRESHOLD,
    });
  }
}
```
and then

```
import * as cdk from 'aws-cdk-lib';

const env = {
  account: process.env.AWS_ACCOUNT_ID,
  region: process.env.AWS_REGION,
};
const app = new cdk.App();
new MyStack(app, 'stack', {
  env,
  tags: {
    testTag: 'testValue',
  },
});
cdk.Tags.of(app).add('testTag', 'testValue');

```

### CDK CLI Version

2.76.0

### Node.js Version

v16.18.1

### OS

13.2.1

### Language

Typescript

### Language Version

4.8.4

**Comment by khushail** [comment]
Hi @dacampos1 , as of now Cloudformation [does not support](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudwatch-alarm.html) adding tags to cloudwatch alarms. You could track this issue [here](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/64#).

**Comment by rgoltz** [comment]
@dacampos1 - If you have stack-level Tags, you should see Tags are getting propagate to `AWS::CloudWatch::Alarm` - Please check my test-case and comment here: https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/64#issuecomment-2033575776

**Comment by tommyhegarty** [comment]
After the rollout of the tags for CloudWatch Alarms in CloudFormation, this is still bugged in CDK. Stack-level tags are not currently propagating down to Alarms when the template is generated with `cdk synth`.
