### ISSUE TITLE
cloudwatch: GaugeWidget with annotations produces invalid JSON

### ISSUE THREAD

**Issue by jSherz** [aws/aws-cdk#25496]
### Describe the bug

Hey folks,

Consider the following GaugeWidget:

```typescript
new GaugeWidget({
  title: "My gauge widget",
  metrics: new Metric({
    namespace: "AWS/VPN",
    metricName: "TunnelState",
    dimensionsMap: {
      TunnelIpAddress: "123.123.123.123",
    },
    statistic: "Minimum",
  }),
  leftYAxis: {
    min: 0,
    max: 1,
  },
  annotations: [
    {
      color: "#b2df8d",
      label: "Up",
      value: 1,
      fill: Shading.ABOVE,
    },
  ],
  statistic: "Minimum",
  period: Duration.minutes(1),
  width: 6,
  height: 6,
});
```

This will be converted to the following JSON:

```json
{
  "type": "metric",
  "width": 6,
  "height": 6,
  "x": 0,
  "y": 0,
  "properties": {
    "view": "gauge",
    "title": "My gauge widget",
    "region": "eu-west-1",
    "metrics": [["AWS/VPN", "TunnelState", "TunnelIpAddress", "123.123.123.123"]],
    "annotations": {
      "horizontal": [
        {
          "color": "#b2df8d",
          "label": "Up",
          "value": 1,
          "fill": "above",
          "yAxis": "annotations"
        }
      ]
    },
    "yAxis": { "left": { "min": 0, "max": 1 } },
    "period": 60,
    "stat": "Minimum"
  }
}
```

The "yAxis" value is "annotations" as a result of: https://github.com/aws/aws-cdk/blob/4038274b812a68993bf6b6cb5b0a3fe971a059ad/packages/aws-cdk-lib/aws-cloudwatch/lib/graph.ts#L237 - this is invalid and yields the following error (in this case, the error was three separate gauge charts):

```
The dashboard body is invalid, there are 3 validation errors: [ { "dataPath": "/widgets/0/properties", "message": "Should match exactly one schema in oneOf" }, { "dataPath": "/widgets/1/properties", "message": "Should match exactly one schema in oneOf" }, { "dataPath": "/widgets/2/properties", "message": "Should match exactly one schema in oneOf" } ]
```

### Expected Behavior

The JSON should've been generated with a value that's accepted by CloudWatch.

### Current Behavior

See above - the annotations contain an invalid yAxis.

### Reproduction Steps

See snippet above.

### Possible Solution

Add test cases for GauageWidget with annotations. Emit a valid yAxis.

### CDK CLI Version

2.75.0 (build 37c53d6)

### Node.js Version

v18.16.0

### OS

MacOS 13.3.1

### Language

Typescript

### Other information

https://github.com/aws/aws-cdk/pull/22213

**Comment by pahud** [comment]
Yes I can reproduce this with the following code:


```ts
export class Demo2Stack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);

    const dashboard = new cloudwatch.Dashboard(this, 'Dashboard');

    const widget = new cloudwatch.GaugeWidget({
      title: "My gauge widget",
      metrics: [ new cloudwatch.Metric({
        namespace: "AWS/VPN",
        metricName: "TunnelState",
        dimensionsMap: {
          TunnelIpAddress: "123.123.123.123",
        },
        statistic: "Minimum",
      })],
      leftYAxis: {
        min: 0,
        max: 1,
      },
      annotations: [
        {
          color: "#b2df8d",
          label: "Up",
          value: 1,
          fill: cloudwatch.Shading.ABOVE,
        },
      ],
      statistic: "Minimum",
      period: Duration.minutes(1),
      width: 6,
      height: 6,
    });
    dashboard.addWidgets(widget);
  }
}
```

And I got the error on cdk deploy:

```
The dashboard body is invalid, there are 1 validation errors:
[
  {
    "dataPath": "/widgets/0/properties",
    "message": "Should match exactly one schema in oneOf"
  }
] (Service: AmazonCloudWatch; Status Code: 400; Error Code: InvalidParameterInput; Request ID: b0be3ca4-3ffe-4d71-904d-5add3a8f9173; Proxy: null)
```

**Comment by hotmori** [comment]
Yep, the same me when I add horizontal annotations for gauge widget: AWS support team confirmed the bug.

**Comment by fokkobucys** [comment]
Same for me. If you drop the annotations everything works fine. But this gives us not the possibility to add areas for a DevOps dashboard.

**Comment by brentcetinich** [comment]
Same for me, its broken.

**Comment by scanlonp** [comment]
Creating a gauge widget on the console and looking at the source shows that the annotations do not have a yAxis property. This looks like it should not have been added in the first place. Will open a PR to fix this.

**Comment by kellertk** [comment]
Hi there! Thanks to all the people that commented, but if your comment is just that you are having a similar problem, please instead use the 👍 reaction on the top comment. Sorting by reactions is one data point we use to prioritize our issue backlog.

We're working on this one now :)
