### ISSUE TITLE
(aws-synthetics-alpha): support latest canary runtime for NodeJS v4.0

### ISSUE THREAD

**Issue by wilhen01** [aws/aws-cdk#25493]
### Describe the feature

AWS have just released [runtime version 4.0](https://aws.amazon.com/about-aws/whats-new/2023/05/amazon-cloudwatch-synthetics-synthetics-nodejs-runtime-version-4-0/) for Synthetics Canaries using NodeJS, which uses Node 16 rather than Node 14. All previous runtime versions will presumably be marked as deprecated soon since Node 14 is EOL. 

CDK should expose the appropriate enum value for the new 4.0 runtime. 

### Use Case

Make latest runtime available and allow canaries to run on a supported Node version.

### Proposed Solution

Add entry for the new runtime version to the [Runtime class](https://github.com/aws/aws-cdk/blob/4038274b812a68993bf6b6cb5b0a3fe971a059ad/packages/%40aws-cdk/aws-synthetics-alpha/lib/runtime.ts#L33)

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

v2.78.0

### Environment details (OS name and version, etc.)

Mac OS

**Comment by WinterYukky** [comment]
@wilhen01 
Oh... I'm sorry, I tried to support runtime version 4.0 few days ago and created #25553 today.
If you trying this issue, I'm sorry again.

**Comment by wilhen01** [comment]
@WinterYukky no problem! I was going to look at this today but you've beaten me to it 😁
