### ISSUE TITLE
aws-s3-deployment: `Source.jsonData` fails for certain types of deploy-time values

### ISSUE THREAD

**Issue by ktmayes-amzn** [aws/aws-cdk#25504]
### Describe the bug

Some types of deploy-time values cause `Source.jsonData` (and presumably the other deploy-time static methods for `Source`) to fail since these deploy-time values contain CloudFormation functions other than `Ref` or `Fn::Get`.

For example, the `secretName` field on a `Secret` becomes an `Fn::Join` function call which gets rejected by `Source.jsonData` (see `Reproduction Steps` for example code).

### Expected Behavior

For the rendered JSON file containing the secret ID to be deployed to the S3 bucket.

### Current Behavior

For the code for reproducing the issue, I get this error:

```
Error: Invalid CloudFormation reference. "Ref" or "Fn::GetAtt". Got {"Fn::Join":["-",[{"Fn::Select":[0,{"Fn::Split":["-",{"Fn::Select":[6,{"Fn::Split":[":",{"Ref":"testsecretF8BBC644"}]}]}]}]},{"Fn::Select":[1,{"Fn::Split":["-",{"Fn::Select":[6,{"Fn::Split":[":",{"Ref":"testsecretF8BBC644"}]}]}]}]}]]}
```

### Reproduction Steps

```typescript
const bucket = new Bucket(this, 'test-bucket');
const secret = new Secret(this, 'test-secret');
new BucketDeployment(this, 'test-bucket-deployment', {
  destinationBucket: bucket,
  sources: [Source.jsonData('key.json', { secretId: secret.secretName })],
});
```

### Additional Information/Context

Seems to be rejected by this code: https://github.com/aws/aws-cdk/blob/dde8a4a423adbf5c543e93f8729af10909335100/packages/aws-cdk-lib/aws-s3-deployment/lib/render-data.ts#L61-L73

### CDK CLI Version

2.75.0 (build 37c53d6)

### Node.js Version

18

### OS

macOS

### Language

Typescript

### Language Version

TypeScript (4.9.5)

**Comment by pahud** [comment]
Thanks for your report. Can you share your content of `key.json` so I can rapidly reproduce it in my account?

**Comment by pahud** [comment]
And you are right. The addMarker() seems only support `Fn::GetAtt` and `Fn::GetAtt` while you were passing `Fn::Join` and `Fn::Select` which are not supported yet.

**Comment by Justinon** [comment]
Also seeing this issue:
```
Error: Invalid CloudFormation reference. "Ref" or "Fn::GetAtt". Got {"Fn::Select":[1,{"Fn::Split":["/",{"Ref":"SsmParameterValue<REDACTED>Parameter"}]}]}
```

**Comment by Justinon** [comment]
> Also seeing this issue:
> 
> ```
> Error: Invalid CloudFormation reference. "Ref" or "Fn::GetAtt". Got {"Fn::Select":[1,{"Fn::Split":["/",{"Ref":"SsmParameterValue<REDACTED>Parameter"}]}]}
> ```

This comes from the following:
```js
let tg: ApplicationTargetGroup // Assume this is defined
const str = tg.firstLoadBalancerFullName + '/' + tg.targetGroupFullName
```

Followed by then utilizing that `str` as a value in a JSON blob being utilzed as object for `Source.jsonData`.

**Comment by Justinon** [comment]
Played around w/ my local copy of `node_modules/aws-cdk-lib/aws-s3-deployment/lib/render-data.js` and removed the conditional in `addMarker` from this:

```
if (keys.length !== 1 || (keys[0] != 'Ref' && keys[0] != 'Fn::GetAtt')) {
```

to this:

```
if (keys.length !== 1) {
```

and...it worked beautifully. The rendered value in the S3 object itself is 100% correct. Why have this condition at all? Perhaps either removing it, or adding `&& keys[0] != 'Fn::Select'`, `&& keys[0] != 'Fn::Join'`, etc. will solve this.
