### ISSUE TITLE
aws-cdk-lib.custom_resources: S3File and S3Assert examples broken links

### ISSUE THREAD

**Issue by dbaileyut** [aws/aws-cdk#25503]
### Describe the issue

The links in [custom_resources](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.custom_resources-readme.html)'s S3File and S3Assert are broken:

> ## S3File
> Provisions an object in an S3 bucket with textual contents. See the source code for the [construct(broken)](https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/custom-resources/test/provider-framework/integration-test-fixtures/s3-file.ts) and [handler(broken)](https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/custom-resources/test/provider-framework/integration-test-fixtures/s3-file-handler/index.ts).

> ## S3Assert
> Checks that the textual contents of an S3 object matches a certain value. The check will be retried for 5 minutes as long as the object is not found or the value is different. See the source code for the [construct(broken)](https://docs.aws.amazon.com/cdk/api/v2/docs/test/provider-framework/integration-test-fixtures/s3-assert.ts) and [handler(broken)](https://docs.aws.amazon.com/cdk/api/v2/docs/test/provider-framework/integration-test-fixtures/s3-assert-handler/index.py).

### Links

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.custom_resources-readme.html

**Comment by peterwoodworth** [comment]
Thanks for fixing this @khushail
