### ISSUE TITLE
(msk): Support for Apache Kafka version 3.4.0

### ISSUE THREAD

**Issue by stefanfreitag** [aws/aws-cdk#25522]
### Describe the feature

AWS MSK now supports Kafka version 3.4.0. The press release is available [here](https://aws.amazon.com/de/about-aws/whats-new/2023/05/amazon-msk-apache-kafka-version-3-4-0/).
CDK supports up to version 3.3.2 - we should add support for the new version.

### Use Case

Enabling CDK users to make use of the latest supported Kafka version in MSK.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.78.0

### Environment details (OS name and version, etc.)

Ubuntu

**Comment by peterwoodworth** [comment]
You can use `.of()` to set any version you need currently

Setting this as a good first issue to add the enum value for the newer version(s)
