### ISSUE TITLE
"Cannot convert undefined or null to object" when synthesizing sam.Api

### ISSUE THREAD

**Issue by jwbogusz** [aws/aws-cdk#2552]
**Describe the bug**
I get the following exception when synthesizing a stack with a sam.Api resource. This stack trace is from 0.29.0 with Scala, but I've reproduced on 0.31.0 with Java too.

`[exec] Exception in thread "main" software.amazon.jsii.JsiiException: Cannot convert undefined or null to object
     [exec] TypeError: Cannot convert undefined or null to object
     [exec]     at Function.entries (<anonymous>)
     [exec]     at filterUndefined (/private/var/folders/js/k8w8ct0j4lsfj3fgpjkrytnr7693j1/T/jsii-kernel-dQfEbe/node_modules/@aws-cdk/cdk/lib/util.js:54:43)
     [exec]     at filterUndefined (/private/var/folders/js/k8w8ct0j4lsfj3fgpjkrytnr7693j1/T/jsii-kernel-dQfEbe/node_modules/@aws-cdk/cdk/lib/util.js:58:24)
     [exec]     at filterUndefined (/private/var/folders/js/k8w8ct0j4lsfj3fgpjkrytnr7693j1/T/jsii-kernel-dQfEbe/node_modules/@aws-cdk/cdk/lib/util.js:58:24)
     [exec]     at filterUndefined (/private/var/folders/js/k8w8ct0j4lsfj3fgpjkrytnr7693j1/T/jsii-kernel-dQfEbe/node_modules/@aws-cdk/cdk/lib/util.js:58:24)
     [exec]     at filterUndefined (/private/var/folders/js/k8w8ct0j4lsfj3fgpjkrytnr7693j1/T/jsii-kernel-dQfEbe/node_modules/@aws-cdk/cdk/lib/util.js:58:24)
     [exec]     at filterUndefined (/private/var/folders/js/k8w8ct0j4lsfj3fgpjkrytnr7693j1/T/jsii-kernel-dQfEbe/node_modules/@aws-cdk/cdk/lib/util.js:58:24)
     [exec]     at Object.filterUndefined (/private/var/folders/js/k8w8ct0j4lsfj3fgpjkrytnr7693j1/T/jsii-kernel-dQfEbe/node_modules/@aws-cdk/cdk/lib/util.js:58:24)
     [exec]     at renderLegacyStacks (/private/var/folders/js/k8w8ct0j4lsfj3fgpjkrytnr7693j1/T/jsii-kernel-dQfEbe/node_modules/@aws-cdk/cdk/lib/synthesis.js:236:32)
     [exec]     at Kernel._wrapSandboxCode (/private/var/folders/js/k8w8ct0j4lsfj3fgpjkrytnr7693j1/T/jsii-java-runtime6652119430230563640/jsii-runtime.js:6967:19)
     [exec]     at ret._ensureSync (/private/var/folders/js/k8w8ct0j4lsfj3fgpjkrytnr7693j1/T/jsii-java-runtime6652119430230563640/jsii-runtime.js:6331:25)
     [exec]     at Kernel._ensureSync (/private/var/folders/js/k8w8ct0j4lsfj3fgpjkrytnr7693j1/T/jsii-java-runtime6652119430230563640/jsii-runtime.js:6935:20)
     [exec]     at Kernel.invoke (/private/var/folders/js/k8w8ct0j4lsfj3fgpjkrytnr7693j1/T/jsii-java-runtime6652119430230563640/jsii-runtime.js:6330:26)
     [exec]     at KernelHost.processRequest (/private/var/folders/js/k8w8ct0j4lsfj3fgpjkrytnr7693j1/T/jsii-java-runtime6652119430230563640/jsii-runtime.js:6024:28)
     [exec]     at KernelHost.run (/private/var/folders/js/k8w8ct0j4lsfj3fgpjkrytnr7693j1/T/jsii-java-runtime6652119430230563640/jsii-runtime.js:5970:14)
     [exec]     at processRequest (/private/var/folders/js/k8w8ct0j4lsfj3fgpjkrytnr7693j1/T/jsii-java-runtime6652119430230563640/jsii-runtime.js:5970:45)
     [exec]     at KernelHost.processRequest (/private/var/folders/js/k8w8ct0j4lsfj3fgpjkrytnr7693j1/T/jsii-java-runtime6652119430230563640/jsii-runtime.js:6066:16)
     [exec]     at KernelHost.run (/private/var/folders/js/k8w8ct0j4lsfj3fgpjkrytnr7693j1/T/jsii-java-runtime6652119430230563640/jsii-runtime.js:5970:14)
     [exec]     at processRequest (/private/var/folders/js/k8w8ct0j4lsfj3fgpjkrytnr7693j1/T/jsii-java-runtime6652119430230563640/jsii-runtime.js:5970:45)
     [exec]     at KernelHost.processRequest (/private/var/folders/js/k8w8ct0j4lsfj3fgpjkrytnr7693j1/T/jsii-java-runtime6652119430230563640/jsii-runtime.js:6066:16)
     [exec]     at software.amazon.jsii.JsiiRuntime.processErrorResponse(JsiiRuntime.java:112)
     [exec]     at software.amazon.jsii.JsiiRuntime.requestResponse(JsiiRuntime.java:84)
     [exec]     at software.amazon.jsii.JsiiClient.callMethod(JsiiClient.java:185)
     [exec]     at software.amazon.jsii.JsiiObject.jsiiCall(JsiiObject.java:57)
     [exec]     at software.amazon.awscdk.App.run(App.java:33)
     [exec]     at MyApp$.main(MyApp.scala:28)
     [exec]     at MyApp.main(MyApp.scala)
     [exec] Subprocess exited with error 1
`

It looks like https://github.com/awslabs/aws-cdk/blob/82c1f1029d49fa73550e554627017bd90212b99c/packages/%40aws-cdk/cdk/lib/util.ts#L61 should include a null check, `if (typeof(obj) === 'object' && obj !== null) {`, as per https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof#null typeof null is 'object'

**To Reproduce**
`new CfnApi(this, "API", CfnApiProps.builder().withStageName("Live").build());`

**Expected behavior**
Should synth successfully.

**Version:**
 - OS: macOS Mojave 10.14.4
 - Programming Language: Java/Scala
 - CDK Version: .29/.31

**Comment by SomayaB** [comment]
Hi @jwbogusz. I'm sorry this has gone so long without response. Are you still experiencing this issue?

**Comment by SomayaB** [comment]
Closing this issue since there hasn't been activity on it in a while. Feel free to reopen if you are still experiencing this issue.
