### ISSUE TITLE
cdk import: Allow to import stacks from pipeline assembly

### ISSUE THREAD

**Issue by dbartholomae** [aws/aws-cdk#25532]
### Describe the feature

When I run `cdk import 'NameOfTheStackInThePipeline'`, it isn't found, as it is part of the assembly, not of the main list of Stacks. It would be great if `cdk import` could also act on assembly stacks.

### Use Case

I'm currently trying to use import to move a stack that was manually deployed before to be deployed by a pipeline instead.

### Proposed Solution

It would be great if `cdk import` could also act on assembly stacks.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.79.0

### Environment details (OS name and version, etc.)

Mac

**Comment by pahud** [comment]
Thank you for your feedback. 

[cdk import](https://github.com/aws/aws-cdk/tree/main/packages/aws-cdk#cdk-import) is currently in preview and only supports [a list of resources](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-import-supported-resources.html) that can be imported as it leverages [the import capabilities from cloudformation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-import.html).

I am making this a p2 feature request and we welcome the upvotes from the community to help us prioritize.

**Comment by dbartholomae** [comment]
Thanks! Please note that this is not for adding additional resources, but for cdk import. The specific feature already works in pure CloudFormation.
