### ISSUE TITLE
aws_rds: examples from the doc fails to deploy.

### ISSUE THREAD

**Issue by sebsto** [aws/aws-cdk#25534]
### Describe the bug

copy pasting code from the doc does not work.

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_rds.DatabaseInstance.html

```
// Simple secret
const secret = new secretsmanager.Secret(this, 'Secret');
// Using the secret
const instance1 = new rds.DatabaseInstance(this, "PostgresInstance1", {
  engine: rds.DatabaseInstanceEngine.POSTGRES,
  credentials: rds.Credentials.fromSecret(secret),
  vpc
});
```

There are two errors with this documentation snippet.

1. compile time.  VPC should be (missing property name)
`vpc: vpc,`

2. second is at deployment, CFN returns the error :

`Could not parse SecretString JSON`

### Expected Behavior

Examples from documentation should work.

### Current Behavior

Fails to compile and fails to deploy

### Reproduction Steps

Build a stack with the above example copy / pasted from doc 2.79.0

### CDK CLI Version

2.79.0

### Framework Version

2.79.0

### Node.js Version

18

### OS

macOS

### Language

Typescript

### Language Version

5.0.4

**Comment by pahud** [comment]
Hi @sebsto 

Yes this is a little bit confusing.

The `vpc` could be either new ec2.Vpc or existing VPC.

For example:

```ts
// new Vpc
const vpc = new ec2.Vpc(this, 'New', { natGateways: 1, maxAzs: 3});
// or import existing vpc
const vpc = ec2.Vpc.fromLookup(this, 'Vpc', { isDefault: true });
```

And rather than `vpc: vpc` you can simply pass `vpc` to the construct property.

In terms of the `credentials` prop, I think we should use this to generate the secret instead.

```ts
const secret = new secretsmanager.Secret(this, 'Secret', {
  generateSecretString: {
    secretStringTemplate: JSON.stringify({ username: 'postgres' }),
    generateStringKey: 'password',
  }
});
```

I'll submit a PR to improve the doc.
