### ISSUE TITLE
software.amazon.awscdk.services.apigatewayv2.HttpApi: invalid ConstructNode type

### ISSUE THREAD

**Issue by jonbo372** [aws/aws-cdk#25551]
### Describe the bug

Trying to create a new HttpApi, leads to a `invalid Construct Node`. 

```
        final var api = new HttpApi(this, "MyApi", HttpApiProps.builder()
                .apiName("MyApi")
                .description("API for processing webhooks")
                .build());
```

where `this` is my `Stack`

### Expected Behavior

Should be possible to create a new `HttpApi`

### Current Behavior

It blows up on a `software.amazon.jsii.JsiiError: invalid ConstructNode type`

### Reproduction Steps

See code above.

### CDK CLI Version

2.79.1 (build 2e7f8b7)

### Framework Version

CDK Version - 2.79.0, Constructs - 10.2.19, software.amazon.awscdk.[apigatewayv2, apigatewayv2-integrations] - 1.201.0

### Node.js Version

v16.15.1

### OS

Ubuntu 20.04

### Language

Java

### Language Version

Java 17

**Comment by peterwoodworth** [comment]
> CDK Version - 2.79.0, Constructs - 10.2.19, software.amazon.awscdk.[apigatewayv2, apigatewayv2-integrations] - 1.201.0

Your CDK package versions need to be the same. Make sure your alpha modules use the same version as the CDK version. Especially the same major version. Thanks

**Comment by jonbo372** [comment]
These are all the latest and greatest package versions. I would assume they would go together.

**Comment by peterwoodworth** [comment]
v1 and v2 are separate major versions, you should only use the latest of whichever major version your project is using.

We just released 2.79.1 today, it should be available for Java soon if it hasn't already become available since you last tried

**Comment by jonbo372** [comment]
@peterwoodworth I guess I'm confused as I assumed all of these are v2. Looking at Maven Central, these are the latest versions that exists.

**Comment by peterwoodworth** [comment]
In v2 you need to explicitly use [the alpha module](https://mvnrepository.com/artifact/software.amazon.awscdk/apigatewayv2-alpha), check our API reference to know which modules are [still in alpha and need to be installed individually in v2](https://docs.aws.amazon.com/cdk/v2/guide/migrating-v2.html). See our docs [here](https://docs.aws.amazon.com/cdk/v2/guide/work-with-cdk-java.html#java-managemodules) to see how to manage your dependencies in Java

**Comment by jonbo372** [comment]
Thanks @peterwoodworth , that took care of it!

**Comment by peterwoodworth** [comment]
Great to hear @jonbo372, if there are any ideas you have to make this more clear in the documentation, please let me know

**Comment by jonbo372** [comment]
Yes, it is a bit confusing as e.g. HttpApi exists in both v1 and v2 under the `...apigatewayv2` package (and I got caught up on the v2 name in `apigatewayv2`, thinking it therefore was v2 of the overall CDK). 

So:

1. make it easier to know what is part of CDK v1 v.s. CDK v2.
2. In the error, instead of just stating `Invalid Construct Node`, the JSii could check if the reason is using a v1 construct v.s. v2. That would have pointed me in the right direction immediately. 
3. A maven bom for CDK v1 and a separate bom for v2 would be nice. It would save me a lot of time trying to figure out which artifacts are v1 v.s. v2.

Again, thanks for your patience @peterwoodworth !
