### ISSUE TITLE
aws-batch-alpha: Unable to specify ECS container env vars containing secrets

### ISSUE THREAD

**Issue by Malanius** [aws/aws-cdk#25559]
### Describe the bug

Since the changes in the batch-alpha module in 2.74.0, it is impossible to define environment variables holding values from secrets. This is due to the changed interface between the old [`JobDefinitionContainer`](https://github.com/aws/aws-cdk/commit/92e6c6706aae72d406cb5bf6a3f5c4d4885a5cb2#diff-2553ece2628a2568b587dc2262eb0ec5432e1b3ca46121dab78ac22595d16e53L120) and new [`IEcsContainerDefinition`](https://github.com/aws/aws-cdk/commit/92e6c6706aae72d406cb5bf6a3f5c4d4885a5cb2#diff-d7bb253aac49f7fb0cc1d918247ea6c4cee3f2abe1f7236a5a78801a060dbe61R449).
The old interface correctly uses `key: value from ECS secret` with control of which env variable the secret is assigned to and also which secret field is used. The new one just expects an array of Secrets Manager secrets that don't provide any way to specify these things.

### Expected Behavior

To be able to define and use ECS secrets in the same way as with previous constructs.

### Current Behavior

The new one just expects an array of Secrets Manager secrets that don't provide any way to assign the secret value and field to the container env variable.
I didn't even try to synthesise and deploy this to see what would happen as this clearly doesn't do what's needed.

### Reproduction Steps

This is working pre 2.74.0:

```typescript
import * as batch from '@aws-cdk/aws-batch-alpha';
import * as ecr from 'aws-cdk-lib/aws-ecr';
import * as esc from 'aws-cdk-lib/aws-ecs';
import * as sm from 'aws-cdk-lib/aws-secretsmanager';
import { Construct } from 'constructs';

declare const ecrRepo: ecr.IRepository;
declare const secret: sm.ISecret;

export class JobDefBug extends Construct {
  constructor(scope: Construct, id: string, _props: {}) {
    super(scope, id);

    new batch.JobDefinition(this, 'JobDefinition', {
      container: {
        image: esc.ContainerImage.fromEcrRepository(ecrRepo),
        secrets: {
          SOME_SECRET: esc.Secret.fromSecretsManager(secret, 'secret-field'),
        },
      },
    });
  }
}
```

Trying to update to the new, post 2.74.0 constructs, the secrets property is incompatible:

```typescript
import * as batch from '@aws-cdk/aws-batch-alpha';
import * as ecr from 'aws-cdk-lib/aws-ecr';
import * as esc from 'aws-cdk-lib/aws-ecs';
import * as sm from 'aws-cdk-lib/aws-secretsmanager';
import { Construct } from 'constructs';

declare const ecrRepo: ecr.IRepository;
declare const secret: sm.ISecret;

export class JobDefBug extends Construct {
  constructor(scope: Construct, id: string, _props: {}) {
    super(scope, id);

    new batch.EcsJobDefinition(this, 'JobDefinition', {
      container: {
        image: esc.ContainerImage.fromEcrRepository(ecrRepo),
        secrets: {
          SOME_SECRET: esc.Secret.fromSecretsManager(secret, 'secret-field'),
        },
      },
    });
  }
}
```

The new interface also requires some properties that were optional and had default values in the old one like CPU and memory resources.

### Possible Solution

Using the correct interface for secrets property in order to be able to use ECS secrets as before and be able to upgrade existing job definitions is probably the way.

### CDK CLI Version

2.79.1

### Framework Version

>2.74.0

### Node.js Version

16.20.0

### OS

Linux

### Language

Typescript

### Language Version

Typescript (4.9.5)

**Comment by pahud** [comment]
Yeah I noticed the type is `secretsmanager.ISecret[];` now. Thank you for your feedback.
