### ISSUE TITLE
ecs: concurrent creation of http namespace fails if namespace is created by ECS cluster as default namespace

### ISSUE THREAD

**Issue by seeebiii** [aws/aws-cdk#25554]
### Describe the bug

If I create an ECS cluster and create a default CloudMap namespace using `.addDefaultCloudMapNamespace(...)`, CloudFormation tries to create the namespace twice and fails with the following error:

```
Another operation of type CreateHttpNamespace and id <some-id> is in progress
```

See reproduction steps below. The problem is that calling the CDK method adds a `Namespace` property to the `AWS::ECS::Cluster` resource if I set `useForServiceConnect: true`. The value of the `Namespace` property is the namespace name. And according to the docs, setting `Namespace` will try to create the namespace if it does not exist:

> If you enter a new name, a AWS Cloud Map namespace will be created. Amazon ECS creates a AWS Cloud Map namespace with the "API calls" method of instance discovery only.

[AWS::ECS::Cluster Documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-cluster-serviceconnectdefaults.html#cfn-ecs-cluster-serviceconnectdefaults-namespace)

### Expected Behavior

I expect that CloudFormation only tries to create one Http Namespace and the deployment does not fail.

### Current Behavior

CloudFormation fails because there are two concurrent operations trying to create an Http namespace: one operation due to the `Namespace` property of `AWS::ECS::Cluster` and one operation due to the `AWS::ServiceDiscovery::HttpNamespace` resource.

### Reproduction Steps

The following CDK stack can be used to reproduce the problem:

```typescript
import * as cdk from 'aws-cdk-lib';
import { Cluster } from 'aws-cdk-lib/aws-ecs';
import { NamespaceType } from 'aws-cdk-lib/aws-servicediscovery';
import { Construct } from 'constructs';

export class CdkNamespaceConcurrentOperationErrorStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const cluster = new Cluster(this, 'SomeCluster');
    cluster.addDefaultCloudMapNamespace({
      name: 'TestNamespace',
      type: NamespaceType.HTTP,
      useForServiceConnect: true,
    });
  }
}
```

### Possible Solution

For CDK users, a workaround is to add an explicit dependency between the cluster and namespace, e.g.:

```typescript
const cluster = new Cluster(this, 'SomeCluster');
const namespace = cluster.addDefaultCloudMapNamespace({
  name: 'TestNamespace',
  type: NamespaceType.HTTP,
  useForServiceConnect: true,
});
cluster.node.addDependency(namespace);
```

However, I believe there are three better options:
1. the CDK could automatically add this dependency,
2. the CDK could set the namespace ARN instead of the namespace name -> using the ARN will not lead to creating a new namespace,
3. or CloudFormation should properly handle the case of using a name for `Namespace` and having an `AWS::ServiceDiscovery::HttpNamespace` resource in the same template.

### Additional Information/Context

One hint: While testing, somehow my namespaces were not deleted when deleting the CloudFormation stack. Hence, you might experience the error mentioned above even when setting the dependency from my suggested workaround if a namespace with the same name already exists. At least that happened to me and made the investigation a bit more complicated until I realized it 😀

### CDK CLI Version

2.72.0

### Node.js Version

16.15.0

### OS

MacOS

### Language

Typescript

### Language Version

4.9.5

**Comment by pahud** [comment]
Hi 

Unfortunately I can't reproduce this error.

I use the code below to deploy in my default VPC.

```ts
  const vpc = getDefaultVpc(this);
  const cluster = new ecs.Cluster(this, 'SomeCluster', { vpc });
  cluster.addDefaultCloudMapNamespace({
    name: 'TestNamespace',
    type: servicediscovery.NamespaceType.HTTP,
    useForServiceConnect: true,
  });
```

When I run `cdk diff` I only see 1 cluster and 1 HttpNamespace.

```
Resources
[+] AWS::ECS::Cluster SomeCluster SomeCluster706C05D5 
[+] AWS::ServiceDiscovery::HttpNamespace SomeCluster/DefaultServiceDiscoveryNamespace SomeClusterDefaultServiceDiscoveryNamespaceAE271633 
```

In your provided sample, I didn't see the `namespace` property in your Cluster construct.

Did you specify `defaultCloudMapNamespace` in your Cluster props?

**Comment by lucasgadams** [comment]
Looks to me like this has been fixed? In my cdk output it looks like ServiceConnectDefaults.Namespace uses the ARN of the sd namespace not the namespace name

**Comment by seeebiii** [comment]
@lucasgadams Yeah it has been fixed with https://github.com/aws/aws-cdk/commit/4f6029372be147fad951cc88f6ce4d7fc2367a48 which references another issue https://github.com/aws/aws-cdk/issues/25616 describing the same problem.
