### ISSUE TITLE
backup: Properties validation failed for resource when using CfnReportPlan.ReportSettingProperty and CfnReportPlan.ReportDeliveryChannelProperty

### ISSUE THREAD

**Issue by TSE-WDG** [aws/aws-cdk#25558]
### Describe the bug

I want to use CfnReportPlan construct (in java) but if i use CfnReportPlan.ReportSettingProperty and  CfnReportPlan.ReportDeliveryChannelProperty i have an error in Cloudformation at deploy step. 

### Expected Behavior

working cloudformation stack

### Current Behavior

(in cloudformation stack events)
CREATE_FAILED
 
 Properties validation failed for resource XXXXXXX with message: 
 #/ReportSetting: required key [ReportTemplate] not found 
 #/ReportSetting: extraneous key [reportTemplate] is not permitted 
 #/ReportSetting: extraneous key [regions] is not permitted 
 #/ReportSetting: extraneous key [accounts] is not permitted 
 #/ReportDeliveryChannel: required key [S3BucketName] not found 
 #/ReportDeliveryChannel: extraneous key [s3BucketName] is not permitted

### Reproduction Steps

```
ReportSettingProperty reportSettingProperty = ReportSettingProperty.builder()
	         .reportTemplate("BACKUP_JOB_REPORT")
	         .accounts(List.of(accountId))
	         .regions(List.of("eu-central-1"))
	         .build();
	
	ReportDeliveryChannelProperty deliveryChannel = ReportDeliveryChannelProperty.builder()
		.s3BucketName(REPORT_BUCKET) // The bucket already exist
		.build();
	
	CfnReportPlanProps props = CfnReportPlanProps.builder()
		.reportPlanName("backup_jobs")
		.reportSetting(reportSettingProperty)
		.reportDeliveryChannel(deliveryChannel)
		.build();

	return new CfnReportPlan(this, "backup-report", props);
```

### Possible Solution

As workaround you can use Map instead of ReportSettingProperty & ReportDeliveryChannelProperty. 

```
    CfnReportPlanProps props = CfnReportPlanProps.builder()
        .reportPlanName("backup_jobs")
        .reportSetting(Map.of(
            "ReportTemplate", "BACKUP_JOB_REPORT",
            "Accounts", List.of(accountId),
            "Regions", List.of("eu-central-1")
        ))
        .reportDeliveryChannel(Map.of(
            "S3BucketName", REPORT_BUCKET
        ))
        .build();

    return new CfnReportPlan(this, "backup-report", props);
```

### CDK CLI Version

2.61.1

### Node.js Version

18

### OS

Linux

### Language

Java

### Language Version

17

**Comment by pahud** [comment]
Thank you for your feedback.

I will discuss with the team internally as this is a previous bug from cfn-spec. At this moment, as it's not strong typed, we need to define the properties in this way. We'll see if there's something we can do to improve the experience.

**Comment by peterwoodworth** [comment]
This is a consequence of this https://github.com/aws/aws-cdk/issues/21767, we're tracking this and will come up with a way to make sure this doesn't happen again. For now though, going forward you'll need to explicitly define the JSON exactly as it will appear in the template
