### ISSUE TITLE
(msk): kafka version 1.1.1. not longer supported

### ISSUE THREAD

**Issue by daschaa** [aws/aws-cdk#25565]
### Describe the bug

When trying to deploy a Kafka cluster with version `KafkaVersion.V1_1_1` I get the error

```
Resource handler returned message: "[ClientRequestToken: fab03ef7-2048-88e5-b49b-a58d0c91af5a] Unsupported KafkaVersion [1.1.1]. Valid values: [2.8.2.tiered, 2.6.2, 2.7.1, 2.8.0, 2.6.3, 2.7.2, 2.8.1, 2.5.1, 2.6.0, 2.6.1, 2.7.0, 2.3.1, 2.2.1, 2.4.1.1, 3.3.2, 3.1.1, 3.2.0, 3.3.1, 3.4.0]
```

### Expected Behavior

The enum `KafkaVersion` contains only supported versions.

### Current Behavior

`KafkaVersion.V1_1_1` is still implemented.

### Reproduction Steps

```
class KafkaVersionTest extends Stack {
  constructor(scope: Construct, id: string, { version }: {version: KafkaVersion}) {
    super(scope, id, { env });
    const vpc = Vpc.fromLookup(this, 'Vpc', { isDefault: true });

    new msk.Cluster(this, 'Cluster', {
      clusterName: `integ-test-v111`,
      kafkaVersion: KafkaVersion.V1_1_1,
      vpc,
      removalPolicy: RemovalPolicy.DESTROY,
    });
  }
}
```

### Possible Solution

Remove the unsupported versions from the class. This should not break backwards compatibility because they can't be deployed anyways.

### CDK CLI Version

2.79.1

### Node.js Version

18

### OS

Mac

### Language

Typescript

**Comment by khushail** [comment]
Hi @daschaa ,Thanks for reporting this bug and coming up with the PR. Our team should be able to review it.
