### ISSUE TITLE
rds: Multiuser rotation incompatible with RDS Proxy

### ISSUE THREAD

**Issue by ahammond** [aws/aws-cdk#25568]
### Describe the bug

The multiuser rotation scheme works by having two actual user roles for each "user". The second user role is just the original with _clone appended to the name. For this discussion we'll call them `user` and `user_clone`.

At any given time, the SecretsManager secret has the name and password for one of these two users. When the rotation lambda is triggered, it pulls the secret to find out which user is currently active. Next it generates a new password for the inactive user and updates it in the database. Finally, it updates the secret to swap users and provides the newly activated user's password. See https://aws.amazon.com/blogs/database/multi-user-secrets-rotation-for-amazon-rds/ for details.

Here's an example of a rotation: Let's assume that user_clone is currently active.

generate a new password and assign it to user in the database.
update Secret to have user as the active user and provide the new password.
The application always, even if it fetched the secret several days ago, can connect to the database. The whole point of this approach is to provide a window of opportunity for the application to update its connection string.

MEANWHILE

RDS Proxy receives a list of SecretsManager secrets for access management: https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_rds.DatabaseProxy.html#secrets

When the rotation happens, the secret is updated. RDS Proxy says "ok, so, `user_clone` is no longer allowed to connect. Instead `user` is allowed to connect." Which makes perfect sense, except... the application still wants to connect as user_clone. The "window of opportunity" has been slammed closed and we have effectively the "single user rotation" pattern, but worse because it also terminates existing connections.

### Expected Behavior

Multiuser rotation should work as expected both when connecting directly to the cluster vs via the proxy.

### Current Behavior

Password rotation causes database access outage.

### Reproduction Steps

https://github.com/time-loop/cdk-aurora instantiate a database, connect a client to that database, trigger rotation, watch your connection get severed.

### Possible Solution

Update the secret schema to include a "previous user" and "previous password". Make the proxy multiuser-rotation aware. 

Considered simply adding a second secret but... you either have to convince your app to swap back and forth between secrets OR if the users names are swapping in the secrets this will cause rds proxy to sever the existing connections.

### CDK CLI Version

2.78.0

### Node.js Version

16.20

### OS

Mac

### Language

Typescript

### Language Version

4.9.5

**Comment by ahammond** [comment]
See also https://github.com/time-loop/cdk-aurora#proxy--multiuser-rotation-incompatibility

**Comment by pahud** [comment]
Thank you for your detailed feedback. I am no RDS proxy expert but this sounds more like a feature request to improve the user experience. Is there something in your mind that aws-rds construct can improve from CDK's perspective with minimal impact on the client app?

**Comment by mrgrain** [comment]
> I submitted [aws-samples/aws-secrets-manager-rotation-lambdas#109](https://github.com/aws-samples/aws-secrets-manager-rotation-lambdas/pull/109) in the hopes that if we make it easy for the RDS Proxy team, they'll just support it.

Can you confirm my understanding here is correct. The change you've proposed alone would not be enough to make this work with RDS Proxy, correct? Nor would it allow you directly to build a custom workflow?

> The SecretsManager team says that the SAM based lambdas you're using in cdk are just samples.

I've followed up internally. This is probably just a misunderstanding.

**Comment by evgenyka** [comment]
CDK does not own this implementation, and currently there is no plan for that. Please continue to work with Secrets Manager team on that. All info is in https://github.com/aws-samples/aws-secrets-manager-rotation-lambdas/issues/108.

**Comment by ahammond** [comment]
@evgenyka  https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-secretsmanager/lib/secret-rotation.ts#L135 is where cdk references these lambdas.  https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-secretsmanager/lib/secret-rotation.ts#L327 is where it deploys them.

If this is an experimental or otherwise non-production feature, then it should be noted as such. Currently https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_rds-readme.html#rotating-credentials makes no such warning and is not in the alpha modules section.
