### ISSUE TITLE
api-gateway: Allow to use an existent stage for deployments

### ISSUE THREAD

**Issue by lucashfreitas** [aws/aws-cdk#25582]
### Describe the feature

Ability to specify existent environments name when creating a new deployment for an API Gateway.

Currently is possible to do that bypassing cdk lib type definition using the suggestion specified here https://stackoverflow.com/questions/63950199/how-to-use-an-existing-stage-in-api-gateway-deployments-in-aws-cdk

``` typescript

const deployment = new apigateway.Deployment(this, "Deployment", {
      api: restApi,
    });
    //deploys an existent stage (dev, stage, prod) - 
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    (deployment as any).resource.stageName = "myStage";
    
```

See more information here: https://stackoverflow.com/questions/63950199/how-to-use-an-existing-stage-in-api-gateway-deployments-in-aws-cdkenvironment

### Use Case

When you have a central API Gateway and multiple other APIs/resources defined in other stacks/repo, we want to be able to deploy it to an "existent" stage without having to create/replace a new one. 

1. I have a central API Gateway which has multiple resources:
     - `/resource-A` -> points to an external resources defined by an external `Stack-A`
     - `/resource-B` -> points to an external resources defined by an external `Stack-B`.
     
    
I want to be able to re deploy `Stack-A` and `Stack-B` and also create a new deployment for an existent environment - the current options on CDK Constructs doesn't allow to easily do that and suggest creating a new stage by using `new Stage`
as define here https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_apigateway.Deployment.html.

<img width="777" alt="image" src="https://github.com/aws/aws-cdk/assets/11416392/f5dc1e4b-3649-4165-a99b-398e0d8a05d4">

### Proposed Solution

A property in the deployment construct to use an existent schema (either by stageName or an `IStage` interface)

```typescript

 const deployment = new apigateway.Deployment(this, "Deployment", {
      api: restApi,
     stageName: stageName // this extra property to utilize an existent stage 
    });
    
 ```
 
 This is the current way of doing that and I can confirm it works:
 
 ```typescript
 
    (deployment as any).resource.stageName = "myStage";
    
```
    
 I also considered trying to assign a stage to the rest api construct, but the deployment Stage expects a `Stage` object and doesn't not accept `IStage`.
 
 ```typescript
 
   restApi.deploymentStage = apigateway.Stage.fromStageAttributes(
      this,
      "sggg",
      {
        restApi,
        stageName: "myStage",
      }
    );

```

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

"aws-cdk-lib": "^2.42.1",

### Environment details (OS name and version, etc.)

MacOS

**Comment by pahud** [comment]
Yes, being allowed to deploy using the existing stage would be great! Thank you for your detailed feature request and we appreciate your PR.

**Comment by lucashfreitas** [comment]
@pahud Thanks for the quick response - I am happy to help/submit a PR with a proposal to implement this  :)

**Comment by Doradas0** [comment]
Any update on this? I'm also keen for this to be implemented. Is the currently agreed workaround to still bypass the typescript type of the deployment construct?

**Comment by AlexLarentis01** [comment]
Any Updates?

**Comment by DenyWatanabe** [comment]
Also eagerly waiting for this feature, currently my only option is redeploying the existing stage using the aws client which is far from ideal.

**Comment by ChrisK1982** [comment]
I would like to see this feature as well. Has there been any movement on this topic?

**Comment by msmolich** [comment]
I've also encountered a need for this feature.

**Comment by pahud** [comment]
Hello all,

Please help us prioritize this feature request by upvotes 👍  on the issue description. According to our [contributing guide](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md), any P2 issue with 20 or more +1s will be automatically upgraded from P2 to P1 and we welcome community PRs as well.
