### ISSUE TITLE
cdk synth/deploy: synth and deploy fail with following error unexpected: --output is required

### ISSUE THREAD

**Issue by AmyOctoCat** [aws/aws-cdk#25594]
### Describe the bug

I am on a Mac laptop. On Friday both cdk synth and cdk deploy were working fine for me. Now when I try I get the following error:

unexpected: --output is required
[13:40:31] Error: unexpected: --output is required

When I try and add --output=cdk.out or --output=./cdk.out I get the following:

Could not create output directory ,cdk.out (The "path" argument must be of type string. Received an instance of Array)

I have tried upgrading my cdk cli to the latest version and I've tried setting my node version to 18.6.0.

### Expected Behavior

I expect cdk to automatically use the cdk.out folder if --output is not specified. When I use --output, I expect it to create a folder at the location specified and output cloudformation there.

### Current Behavior

 When I try to use cdk synth or cdk deploy I get the following error:

unexpected: --output is required
[13:40:31] Error: unexpected: --output is required

When I try and add --output=cdk.out or --output=./cdk.out I get the following:

Could not create output directory ,cdk.out (The "path" argument must be of type string. Received an instance of Array)

I have tried upgrading my cdk cli to the latest version and I've tried setting my node version to 18.6.0.

### Reproduction Steps

I think this is an issue with the setup on my machine, the same thing happens for every cdk project I have. 

### CDK CLI Version

2.77.0, 2.61.0, 2.78.1

### Node.js Version

18.16.0

### OS

Mac

### Language

Java

**Comment by khushail** [comment]
Hi @AmyOctoCat , I am using Mac , with node 18.12.1 and CDK 2.79.1, things are working fine and I am able to synth/deploy CDK apps. Could you share more insights as what might have changed in your system settings?

**Comment by mderagonpoka** [comment]
@AmyOctoCat Getting the same issue on my end when using aws cdk synth inside a github action, did you manage to solve the issue on your local machine?
