### ISSUE TITLE
aws_ecr_assets: Allow for a tag value for DockerImageAsset

### ISSUE THREAD

**Issue by rupe120** [aws/aws-cdk#25595]
### Describe the feature

Add a property to DockerImageAsset to set a tag on the image, similar to setting Latest on a repo, but obviously needing to be more specific in the tag value. 

### Use Case

I am using a small CDK app to create a base image used in other apps. I currently export the asset URI from the stack and pull that value via SDK calls in the other CDK apps.

### Proposed Solution

Add a constructor props property to supply a tag value for the image.

### Other Information

I am willing to attempt to add this though I have not submitted changes before. I have pulled the repository and poked around a little.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.79.0 (build e4a2c01)

### Environment details (OS name and version, etc.)

Windows 11, Typescript app

**Comment by pahud** [comment]
Hi

This is by design.  At this moment you will need [cdklabs/cdk-ecr-deployment](https://github.com/cdklabs/cdk-ecr-deployment) to publish this intermediate image to your ECR repo with custom tags.
https://github.com/aws/aws-cdk/tree/main/packages/aws-cdk-lib/aws-ecr-assets#publishing-images-to-ecr-repositories

**Comment by rupe120** [comment]
@pahud please add official support for the ECR deployment construct. There are 2 constructs in Construct Hub (https://constructs.dev/packages/cdk-ecr-deployment/v/2.5.6?lang=typescript and https://constructs.dev/packages/cdk-ecr-deployment-patched/v/2.0.1?lang=typescript) neither of which actually works as documented. I get CloudFormation deployment errors from both.
