### ISSUE TITLE
ecs: ContainerDefinition.addEnvironment

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#2559]
It's very useful to be able to mutate the environment configuration of the container definition, similar to Lambda.

**Comment by bf-sodle** [comment]
+1

**Comment by blimmer** [comment]
I was able to hack around this like so, but your mileage may vary:

```typescript
(service.taskDefinition.defaultContainer as any).props.environment["ENV_VAR_FOO"] = "bar";
```

**Comment by blimmer** [comment]
Somewhere between CDK v1.122.0 and v1.144.0 my workaround above stopped working. This is what I now have to use instead:

```typescript
(service.taskDefinition.defaultContainer as any).node.host.environment["ENV_VAR_FOO"] = "bar";
```

**Comment by girotomas** [comment]
Isn't this Done ? https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ecs.ContainerDefinition.html#addwbrenvironmentname-value

**Comment by MrArnoldPalmer** [comment]
This was in fact resolved via https://github.com/aws/aws-cdk/pull/17889
