### ISSUE TITLE
CfnAuthorizer creation fails if optional property `identitySource` is missing

### ISSUE THREAD

**Issue by zakwalters** [aws/aws-cdk#2561]
**Describe the bug**
Trying to create a `CfnAuthorizer` without `identitySource` specified in the props fails.

The `identitySource` field is specified as "Required: no" in [the CloudFormation docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-authorizer.html#cfn-apigateway-authorizer-identitysource).

Furthermore, once you have deployed an authorizer with `identitySource` specified, removing this from the props and redeploying will not remove the Identity Sources from the authorizer.

**To Reproduce**
Use this minimal stack: 

```ts
import * as cdk from "@aws-cdk/cdk";
import * as apig from "@aws-cdk/aws-apigateway";
import * as lambda from "@aws-cdk/aws-lambda";

export class IdentitySourceStack extends cdk.Stack {
    constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
        super(scope, id, props);

        new IdentitySourceService(this, "testService");
    }
}

export class IdentitySourceService extends cdk.Construct {

    constructor(scope: cdk.Construct, id: string) {
        super(scope, id);

        const handlerFunction = new lambda.Function(this, "sayHelloHandler", {
            runtime: lambda.Runtime.NodeJS810,
            code: lambda.Code.directory("resources"),
            handler: "index.handler",
        });

        const authoriserFunction = new lambda.Function(this, "authoriser", {
            runtime: lambda.Runtime.NodeJS810,
            code: lambda.Code.directory("resources"),
            handler: "index.authoriser",
        });

        const api = new apig.RestApi(this, "IdentitySourceApi", {
            restApiName: "Identity source service",
            description: "This API shows that the IdentitySource option is required",
            deploy: true,
        });

        const authoriser = new apig.CfnAuthorizer(this, "apiAuthoriser", {
            restApiId: api.restApiId,
            type: "REQUEST",
            // Uncomment the line below for deployment to succeed
            // identitySource: "method.request.header.Authorization",
            name: "MyAuthorizer",
            authorizerUri: `arn:aws:apigateway:eu-west-3:lambda:path/2015-03-31/functions/${authoriserFunction.functionArn}/invocations`,
        });

        const handlerIntegration = new apig.LambdaIntegration(handlerFunction);

        api.root.addMethod("GET", handlerIntegration, {
            authorizationType: apig.AuthorizationType.Custom,
            authorizerId: authoriser.authorizerId,
        });
    }
}
```

First, deploy using `tsc && cdk deploy` with `identitySource` commented out. It fails with the error: 
```
CREATE_FAILED        | AWS::ApiGateway::Authorizer | testService/apiAuthoriser (testServiceapiAuthoriser950C7F8F) Invalid request input (Service: AmazonApiGateway; Status Code: 400; Error Code: BadRequestException; Request ID: 925fdf20-77c5-11e9-a2f7-c3ab60e1a613)
```

Second, un-comment `identitySource` and deploy again. The authorizer is created with the identity sources specified.

Third, comment out the `identitySource` again, and redeploy. The deployment succeeds, but the identity sources are still specified on the resource.

Finally, delete the identity sources from the authorizer through the console. This succeeds, indicating that they really aren't required.

**Expected behavior**
The stack should deploy successfully without `identitySource` specified. 

The identity sources should be removed when redeploying after removing them from the props.

**Version:**
 - OS: Mac OS 10.13.6
 - Programming Language: TypeScript
 - CDK Version: 0.31.0

**Comment by rix0rrr** [comment]
The error message tells me the source of the error is CloudFormation. Probably the property was incorrectly marked as optional by them.

I'm very sorry, but there's nothing we can do about that.

**Comment by SomayaB** [comment]
I will close this issue for now as the error is coming from CloudFormation. Feel free to reopen.

**Comment by jmferrete** [comment]
Hi!

If you look in the [API reference documentation](https://docs.aws.amazon.com/apigatewayv2/latest/api-reference/apis-apiid-authorizers-authorizerid.html#apis-apiid-authorizers-authorizerid-prop-updateauthorizerinput-authorizerresultttlinseconds) about the `identitySource` property:

> For the REQUEST authorizer, this is required when authorization caching is enabled.

I've tested it directly with a CloudFormation stack and it works perfectly if you set the `AuthorizerResultTtlInSeconds` to `0` seconds for disabling cache.

**Comment by nija-at** [comment]
@jmferrete -

Unfortunately, I'm unable to follow your last comment and how it relates to the original issue you opened. 

As far as resources that have the `Cfn` prefix (in this case, the `CfnAuthorizer`), the CDK does not apply any special logic. It simply translates what's specified directly into a CloudFormation template and `cdk deploy` deploys this template. 

So, if the `inlineSource` property is specified, it adds this to the Cloudformation template; if not specified, it's left out. No additional logic or validation is applied beyond this. You can see the effect of this change by running `cdk synth` and checking the template in the `cdk.out/` folder. 

Any behaviour beyond this - such as resources being marked as mandatory but are actually not - are part of the logic that CloudFormation and the service team (in this case, API Gateway) control.

Hope that helps.

**Comment by nija-at** [comment]
Closing this issue. 
Feel free to re-open when you have an update and feel this is still an issue.

Thanks.

**Comment by nija-at** [comment]
Reopening this issue after a bit more investigation. It seems like this is a bug with CloudFormation. It doesn't seem to honour that the `identitySource` is removed.

Internal reference: i/CFN-30548
