### ISSUE TITLE
eks: Nodegroup options instance type does not accept tokens

### ISSUE THREAD

**Issue by jpmcb** [aws/aws-cdk#25615]
### Describe the bug

Similar to #20914

When deploying a nodegroup with an instance type provided through the Cfn parameters in Go, the program panics in with:
```
Runtime process exited abnormally: wait: no child processes panic: Error: Malformed instance type identifier
```

When printing the value for that parameter, I get:
```
${Token[TOKEN.650]}
```

### Expected Behavior

I'd expect that doing `ValueAsString()` should _just work_ and get me the string value for that parameter but seems that something with the instance types are doing a synth-time check (not at deploy time when that value will be available).

### Current Behavior

Panics - would expect the instance types to take a node value.

### Reproduction Steps

Create a nodegroup using the cfn parameter for an instance type

```go
        myInstanceType := awscdk.NewCfnParameter(stack, jsii.String("TestsysInstanceType"), &awscdk.CfnParameterProps{
                Type:        jsii.String("String"),
                Description: jsii.String("The instance type for nodes"),
                Default:     jsii.String("m5.xlarge"),
        })

        myCluster.AddNodegroupCapacity(jsii.String("nodegroup"), &eks.NodegroupOptions{
                InstanceTypes: &[]ec2.InstanceType{
                        ec2.NewInstanceType(jsii.String(*testsysInstanceType.ValueAsString())),
                },
        })
```

### CDK CLI Version

2.78.0 (build 8e95c37)

### Node.js Version

v18.16.0

### OS

Linux x86_64 ubuntu

### Language

Go

**Comment by pahud** [comment]
Yes, looks like it's not supported. I just tried it in TypeScript


This is not supported: 

```ts
  const paramInstanceType = new CfnParameter(this, 'ParamInstanceType', {
       type: 'String',
       default: 'm5.xlarge',
  });

  const InstanceTypeString = paramInstanceType.valueAsString
  cluster.addNodegroupCapacity('NG', {
    instanceTypes: [
      new ec2.InstanceType(InstanceTypeString),
    ]
  })；
```
But passing context variable like this is supported:

```ts
  const InstanceTypeString = Stack.of(this).node.tryGetContext('instance_type') || 'm5.xlarge';

  cluster.addNodegroupCapacity('NG', {
    instanceTypes: [
      new ec2.InstanceType(InstanceTypeString),
    ]
  })；
```
