### ISSUE TITLE
class Queue: Missing KMS permissions

### ISSUE THREAD

**Issue by nivashegde** [aws/aws-cdk#25620]
### Describe the issue

Reading the doc for [class Queue: Construct](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_sqs.Queue.html), 

Under `grantSendMessage` and `grantConsumeMessage`, it says below SQS read/write permissions are provided. But i see that even KMS encrypt/decrypt permissions are provided as well which is missing .

Please add the following sentence - `If encryption is used, permission to use the key to decrypt the contents of the queue will also be granted to the same principal.`

### Links

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_sqs.Queue.html

**Comment by peterwoodworth** [comment]
Thanks for letting us know how we can improve our docs. Would you be able to submit a PR which specifies that KMS permissions will be provided as well when using `grantSendMessage` and `grantConsumeMessage` if a key is associated with the Queue?

**Comment by nivashegde** [comment]
Thanks the response, I don't think the official docs are part of `aws-cdk` code base - https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_sqs.Queue.html

I tried to search, if you can link me the code base I can send a PR

**Comment by peterwoodworth** [comment]
Our docs are generated from our codebase in the docstring. If you click `source` on the page you linked, it will link to the source code for the `Queue` construct. `Queue` extends `QueueBase`, which is where these methods are defined, with the comments appearing above the function definition that render as our docs

**Comment by nivashegde** [comment]
Thanks, here's the PR - https://github.com/aws/aws-cdk/pull/25622
