### ISSUE TITLE
eks: tags doesn't inherit from stack

### ISSUE THREAD

**Issue by singlewind** [aws/aws-cdk#25647]
### Describe the bug

`Custom::AWSCDK-EKS-Cluster` has to be passed from properties to get populate. Can not inherit from stack.

### Expected Behavior

Should inherit from stack just like `Custom::AWSCDK-EKS-KubernetesResource` in the same library.

### Current Behavior

Tags not attached from parent stack.

### Reproduction Steps

```
import * as eks from 'aws-cdk-lib/aws-eks'
import { KubectlV26Layer } from '@aws-cdk/lambda-layer-kubectl-v26'

------
Tags.of(this).add('ENV', 'production') // doesn't work

const cluster = new eks.Cluster(this, 'Eks', {
      clusterName: props.clusterName,
      version: eks.KubernetesVersion.V1_26,
      kubectlLayer: new KubectlV26Layer(this, 'kubectl'),
      tags: {
          'ENV': 'productions' // I thought this works, failed on update stack. No tags appears add after cluster creations.
      }
    });

Tags.of(cluster).add('ENV', 'production') // doesn't work
```

### CDK CLI Version

2.79.1 (build 2e7f8b7)

### Node.js Version

16.19.1

### OS

all system

### Language

Typescript

### Language Version

5.0.4

**Comment by pahud** [comment]
This is because the `Tags` class essentially iterate all L1 CfnReources and apply the tag if it's "taggable" but eks.Cluster behind the scene is not provisioned as the L1 resource, which explains why it's not working here. I am afraid we still have to specify the `tags` in the cluster property in this use case.

**Comment by singlewind** [comment]
I was wrong, even the tags has specified in the tags property. The resources still haven't been tagged properly in updating stacks. I can try delete and redeploy to see whether this bug appears during creation.

**Comment by andreprawira** [comment]
@singlewind could you please explain to me how did you pass the tags to make it work?
