### ISSUE TITLE
aws-lambda-nodejs: comments in tsconfig - precompile in bundling 

### ISSUE THREAD

**Issue by niko-achilles** [aws/aws-cdk#25664]
### Describe the bug

When using the NodejsFunction of aws-cdk-lib/aws-lambda-nodejs
and using the Bundling Options of NodejsFunction Options 
and configuring that the bundler should precompile 
and introducing a tsconfig for precompilation with comments 
- (by default tsconfig is a json with comments support artifact ) 
Then the synth process of cdk fails , the bundler esbuild does not produce precompile results
and cdk produces a synth lock   

### Expected Behavior

Precompilation of a NodejsFunction by using a tsconfig with comments should produce a precompiled artifact

### Current Behavior

aws cdk synth prints the error:
 
```
Unexpected token / in JSON at position .. 
at extractTsConfig /node_modules/aws-cdk-lib/aws-lambda-nodejs/lib/util.js:5:206
at getTsconfigCompilerOptions /node_modules/aws-cdk-lib/aws-lambda-nodejs/lib/util.js:4:1336
at Bundling.createBundlingCommand /node_modules/aws-cdk-lib/aws-lambda-nodejs/lib/bundling.js:1:3743
at new Bundling aws-cdk-lib/aws-lambda-nodejs/lib/bundling.js:1:2637

```

### Reproduction Steps

Steps

1. introduce a tsconfig with comments as in the example tsconfig below
2. define precompile as in the example function-construct below
3. execute cdk synth

Example function construct 

```ts
const exampleFunction = new NodejsFunction(this, 'example', {
      bundling: {
        preCompilation: true,
        ...
    });
```

Example tsconfig

```jsonc
"compilerOptions": {
    /* Visit https://aka.ms/tsconfig to read more about this file */

    /* Language and Environment */
    "target": "ES2020",
    "lib": ["ES2020"],
    "experimentalDecorators": true

    // ...
}
```
 

### Possible Solution

Utilities able to parse tsconfig with comments when used for precompilation purposes .  

### CDK CLI Version

2.79.1 (build 2e7f8b7)

### Node.js Version

lts/hydrogen

### OS

unix

### Language

Typescript

### Language Version

5.0.4

**Comment by peterwoodworth** [comment]
Hey, thanks for reporting this. We're aware of this and tracking it [here](https://github.com/aws/aws-cdk/issues/18974)
