### ISSUE TITLE
aws_cdk.aws_appsync: Move from aws_cdk.aws_appsync_alpha to aws_cdk.aws_appsync is not possible due to old constructs lib requirement

### ISSUE THREAD

**Issue by ben-elsen** [aws/aws-cdk#25678]
### Describe the bug

Hi, 

Probably I am missing something but I cannot upgrade from aws_appsync_alpha to aws_appsync. When I try to upgrade my dependencies, I get the following error: 
```
There are incompatible versions in the resolved dependencies:
  constructs<4.0.0,>=3.3.69 (from aws_cdk.aws_appsync==1.202.0->-r requirements.in (line 6))
  constructs<11.0.0,>=10.0.0 (from aws-cdk.aws-apigatewayv2-integrations-alpha==2.80.0a0->-r requirements.in (line 7))
  constructs<11.0.0,>=10.0.0 (from aws-cdk-lib==2.80.0->-r requirements.in (line 4))
  constructs<11.0.0,>=10.0.0 (from aws-cdk.aws-lambda-python-alpha==2.80.0a0->-r requirements.in (line 5))
```

### Expected Behavior

I would expect that the version of the constructs library that is needed for aws_cdk.aws_appsync is compatible with the other aws packages and definitely aws-cdk-lib but the versions are miles away: constructs<11.0.0,>=10.0.0 vs constructs<4.0.0,>=3.3.69. 

### Current Behavior

The compilation to use the new requirements fails.

### Reproduction Steps

Use the following requirements.in file:
```
aws-cdk-lib
aws-cdk.aws-lambda-python-alpha
aws_cdk.aws_appsync
aws-cdk.aws-apigatewayv2-integrations-alpha
cognitojwt
python-dotenv
pytz
```

Use the following command to compile my requirements:
```
pip-compile --upgrade requirements.in
```

### CDK CLI Version

2.80

### Node.js Version

18.11.0

### OS

Ventura 13.3

### Language

Python

### Language Version

Python

**Comment by peterwoodworth** [comment]
`aws_appsync` is just in `aws-cdk-lib` now like all the other stable packages. You shouldn't install it separately anymore

**Comment by ben-elsen** [comment]
Thanks @peterwoodworth oh boy, it was time to wrap up for me ;-)
