### ISSUE TITLE
aws-backup: BackupPlanRule support for recovery point tags

### ISSUE THREAD

**Issue by delenamalan** [aws/aws-cdk#25671]
### Describe the feature

It would be nice to be able to add recovery point tags to `BackupPlanRule`. See the `RecoveryPointTags` property of [BackupRuleResourceType](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-backup-backupplan-backupruleresourcetype.html).

### Use Case

I want all backups that have been created with AWS Backup to have the same tags.

### Proposed Solution

Add a parameter to the `BackupPlanRule` class for recovery point tags.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.79.1

### Environment details (OS name and version, etc.)

Mac OS 13.3.1 Python 3.7.13

**Comment by peterwoodworth** [comment]
Thanks for the request, we would be happy to accept a PR for this.

Until this is implemented, you can use [escape hatches](https://docs.aws.amazon.com/cdk/v2/guide/cfn_layer.html) to manually add the property to the template
