### ISSUE TITLE
(cdk-cli): cdk bootstrap fails with: encountered unsupported property ImageTagMutability

### ISSUE THREAD

**Issue by cponfick-bhs** [aws/aws-cdk#25676]
### Describe the bug

The `cdk bootstrap aws://123456789/region` command fails. 

### Expected Behavior

The command should run without errors.

### Current Behavior

Calling `cdk bootstrap` fails with the following error:

```bash
cdk bootstrap aws://123456789/eu-central-1

 ⏳  Bootstrapping environment aws://123456789/eu-central-1...
Trusted accounts for deployment: (none)
Trusted accounts for lookup: (none)
Using default execution policy of 'arn:aws:iam::aws:policy/AdministratorAccess'. Pass '--cloudformation-execution-policies' to customize.
CDKToolkit: creating CloudFormation changeset...
8:24:52 PM | CREATE_FAILED        | AWS::ECR::Repository    | ContainerAssetsRepository
Encountered unsupported property ImageTagMutability

 ❌  Environment aws://123456789/eu-central-1  failed bootstrapping: Error: The stack named CDKToolkit failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Encountered unsupported property ImageTagMutability
    at FullCloudFormationDeployment.monitorDeployment (/Users/cponfick/.nvm/versions/node/v18.16.0/lib/node_modules/aws-cdk/lib/index.js:397:10236)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/cponfick/.nvm/versions/node/v18.16.0/lib/node_modules/aws-cdk/lib/index.js:402:2104
    at async Promise.all (index 0)
    at async CdkToolkit.bootstrap (/Users/cponfick/.nvm/versions/node/v18.16.0/lib/node_modules/aws-cdk/lib/index.js:402:1949)
    at async exec4 (/Users/cponfick/.nvm/versions/node/v18.16.0/lib/node_modules/aws-cdk/lib/index.js:455:51970)

The stack named CDKToolkit failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Encountered unsupported property ImageTagMutability
```

### Reproduction Steps

`cdk bootstrap aws://account/region`

### CDK CLI Version

2.80.0

### Node.js Version

18.16.0

### OS

macOs 13.3.1 (a) 

### Language

Typescript

### Language Version

5.0.4

**Comment by peterwoodworth** [comment]
The `eu-central-1` region has this property supported in the [resource specification](https://d1mta8qj7i28i2.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json). Additionally, I have this region bootstrapped with this property enabled, so I'm unsure why you're running into this for `eu-central-1`.

**Comment by peterwoodworth** [comment]
If there's any other information you can provide, let me know. Else, I recommend creating a case through AWS support

**Comment by danielbayerlein** [comment]
@mirko-pira Same here. Region `eu-central-1` with `Encountered unsupported property Architectures` error during the lambda deployment.

**Comment by cponfick-bhs** [comment]
@peterwoodworth 
This seems to be an eu-central-1 specific issue. I think this is not a cdk issue. Other regions work without problems for me.

**Comment by mirko-pira** [comment]
> @peterwoodworth This seems to be an eu-central-1 specific issue. I think this is not a cdk issue. Other regions work without problems for me.

Yes, eu-south-1 works fine.

**Comment by peterwoodworth** [comment]
Could be an intermittent issue with the service, I'll reach out to see what's going on

**Comment by cponfick-bhs** [comment]
@peterwoodworth Seems like it is working again.

**Comment by peterwoodworth** [comment]
The intermittent issues related to CloudFormation resources have been reported to be resolved. Closing out, please ping me if people continue to run into issues
