### ISSUE TITLE
CodePipeline: allow alias to be assigned to autogenerated KMS key

### ISSUE THREAD

**Issue by otterley** [aws/aws-cdk#2569]
CodePipeline pipelines created by the `codepipeline.Pipeline` class will automatically generate an S3 bucket to store artifacts in and a KMS key (CMK) to encrypt the objects in that bucket, if the bucket isn't specified via the `artifactBucket` property.

It would be helpful if one could specify an alias to assign to the autogenerated CMK so that other account users have an indication that the CMK is used for the pipeline.  This could also help dissuade administrators from accidentally marking the CMK for expiration, which would render the pipeline unusable.

**Comment by skinny85** [comment]
This is solved in #3694 by always creating an `Alias` for the autogenerated CodePipeline`Key`.
