### ISSUE TITLE
Separate higher-level constructs into their own module

### ISSUE THREAD

**Issue by SoManyHs** [aws/aws-cdk#2570]
Based on https://github.com/awslabs/aws-cdk/pull/2402#issuecomment-492192883, we may want to move higher-level constructs ("L3s", or constructs that incorporate components from multiple AWS services, into its own module.

**Comment by SoManyHs** [comment]
Per offline discussion with @eladb, working on writing a doc to elaborate on this idea

**Comment by eladb** [comment]
Thanks! Looking forward

**Comment by MrArnoldPalmer** [comment]
This was resolved by creation of the `aws-ecs-patterns` module. See the [design pr](https://github.com/aws/aws-cdk/pull/2402) for info.
