### ISSUE TITLE
core: Asset bundling in concurrent runs may fail due to moving build assets with a shared build name (`ENOENT ... bundling-temp-<hash>`)

### ISSUE THREAD

**Issue by garyd203** [aws/aws-cdk#25711]
### Describe the bug

When we run `cdk synth` in parallel against multiple stacks (eg. when running tests), then we sometimes get an error like:

```
ENOENT: no such file or directory, scandir 'test/out/bundling-temp-0123...cdef'
```

(the hash suffix has been anonymised).

Why does this happen? Looking at `stageByBundling`...

https://github.com/aws/aws-cdk/blob/cdafcc52ad4aea3ef7f1446da7521fb504cb33b9/packages/aws-cdk-lib/core/lib/asset-staging.ts#L330-L342

... we can see that since we don't know the asset hash in my case, then `determineBundleDir` will use the (deterministic) cache key to create the bundle build directory `bundleDir`, meaning that concurrent and subsequent runs will use the same bundle directory.

Then `determineBundledAsset` will return the (shared) `bundleDir` as `bundledAsset.path`, and the innocuously named `stageAsset` will *rename* `bundleDir` on the filesystem due to the `style: 'move'` argument.

This will then cause concurrent runs to fail because `bundleDir` is shared by them, but no longer exists. It's possible that concurrent runs will produce corrupted assets anyway, depending on how the specific bundling works.

### Expected Behavior

Concurrent runs should not interfere with each other. If they share state via disk, it should be done in a concurrency-safe way.

### Current Behavior

As described above, occasional `ENOENT: no such file or directory, scandir 'test/out/bundling-temp-0123...cdef'`

### Reproduction Steps

Concurrently synthesise multiple stacks with an identical asset-based resource such as a Lambda

### Possible Solution

Possible Fix: This section of `stageByBundling` treats `bundleDir` as a temporary directory, so it should use a genuine temporary directory. However, this may just be a bandaid fix, and may have follow-on effects that are not clear to me.

Possible root cause: This asset bundling code mixes temporary directories/files with permanent directories/files, and intermingles caching and performance concerns. This makes resource lifecycle management complex and easy to get wrong, and documentation (such as "Moving implies the source directory is temporary and can be trashed." on `stageAsset`) is only a partial mitigation. It seems sensible to refactor the code to separate these concerns, avoid deterministic names for temporary files, and explicitly manage the lifecycle for temporary files.

### Additional Information/Context

Related to #25380 and others

### CDK CLI Version

2.76.0 (build 78c411b)

### Node.js Version

v18.15.0

### OS

OS X Ventura

### Language

Typescript

**Comment by pahud** [comment]
Thank you for your detailed report. Unfortunately I can't reproduce this in my environment but I will bring this up to the team.

**Comment by otaviomacedo** [comment]
@garyd203 Can you please test this with the latest version of the framework. This problem might have already been solved.

**Comment by garyd203** [comment]
Thanks @otaviomacedo I'll check it out later this week

**Comment by garyd203** [comment]
Thanks @otaviomacedo - one of the changes between 2.76.0 and v2.84.0 does appear to have solved the issue we were experiencing
