### ISSUE TITLE
iam: SamlConsolePrincipal does not work for GovCloud or ADC regions

### ISSUE THREAD

**Issue by nagmesh** [aws/aws-cdk#25723]
### Describe the bug

While creating the SAML federation principal as below, the SAML attribute is hardcoded with `https://signin.aws.amazon.com/saml` or `https://signin.amazonaws.cn/saml `, which breaks in GovCloud, Iso and Iso-b partitions.

### Expected Behavior

The construct SamlConsolePrincipal should check partition and supply the right URL.

### Current Behavior

Only works in aws or aws-cn partition rest of the partition has to be changed.

### Reproduction Steps

Use partition as `aws-us-gov` and the signon URL is `https://signin.aws.amazon.com/saml` 

### Possible Solution

Make a map from partition and push it in 

```
llet samlSignOnUrl: string;
const partition = cdk.Aws.PARTITION;
if (partition === 'aws-cn') {
  samlSignOnUrl = 'https://signin.amazonaws.cn/saml';
} else if (partition === 'aws-us-gov') {
  samlSignOnUrl = 'https://signin.amazonaws-us-gov.com/saml';
} else if (partition === 'aws-iso-b') {
  samlSignOnUrl = 'https://signin.sc2shome.sgov.gov/saml';
} else if (partition === 'aws-iso') {
  samlSignOnUrl = 'https://signin.c2shome.ic.gov/saml';
} else {
  samlSignOnUrl = 'https://signin.aws.amazon.com/saml';
}

export class SamlConsolePrincipal extends SamlPrincipal {
  constructor(samlProvider: ISamlProvider, conditions: Conditions = {}) {
    super(samlProvider, {
      ...conditions,
      StringEquals: {
        'SAML:aud': samlSignOnUrl,
      },
    });
  }
...
```

or add saml signonUrl in [fact-table](https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/region-info/build-tools/fact-tables.ts) and source it in `SamlConsolePrincipal`

### CDK CLI Version

2.79.1

### Node.js Version

16

### OS

macOS 12.6.5

### Language

Typescript

### Other information

Related issue: https://github.com/aws/aws-cdk/issues/22091

**Comment by peterwoodworth** [comment]
I think this should be a similar fix to the PR on the related issue. We're happy to accept a contribution for this 🙂

**Comment by virajmavani** [comment]
I would like to work on this.

**Comment by peterwoodworth** [comment]
Please feel free @virajmavani!
