### ISSUE TITLE
lambda:lambda.Handler.FROM_IMAGE not resolving during build

### ISSUE THREAD

**Issue by ETisREAL** [aws/aws-cdk#25758]
### Describe the bug

When I launch the stack I get this error: 
> Error: handler must be `Handler.FROM_IMAGE` when using image asset for Lambda function
   

### Expected Behavior

This is my code:

```
const openapiEdgeLambda = new cloudfront.experimental.EdgeFunction(this, 'openapiSignURLHandler', {
            functionName: 'openapiSignURLHandler',
            handler: lambda.Handler.FROM_IMAGE,
            runtime: lambda.Runtime.FROM_IMAGE,
            code: lambda.Code.fromDockerBuild('resources/lambdas/openapi-python/'),
            logRetention: RetentionDays.ONE_DAY,
            environment: {
                'OPENAPI_URL': `https://${config.openapiDomainName[0]}`,
                'OPENAPI_ACCESS_KEY_ID': this.openapiKeyId.publicKeyId,
                'OPENAPI_PRIVATE_KEY': process.env.OPENAPI_PRIVATE_KEY as string
            },
            description: 'Lambda function responsibile for signing URL to access openapi documentation from tournaments.qlash.gg'
        })
```

as you can see I am specifying the handler as FROM_IMAGE

### Current Behavior

I get this error:

> Error: handler must be `Handler.FROM_IMAGE` when using image asset for Lambda function

### Reproduction Steps

Simply launch the stack with the following code and this Dockerfile

```
FROM public.ecr.aws/lambda/python:3.8

RUN  pip3 install cryptography boto3 --target "/asset"

WORKDIR /asset

COPY openapi-sign-url.py .

COPY STGopenapiKey.pem .
ENV OPENAPI_ACCESS_KEY_ID=K17L208H5RTTN9
ENV OPENAPI_URL=https://stg.docs.qlash.gg/

CMD [ "openapi-sign-url.lambda_handler" ] 
```

### CDK CLI Version

2.80

### Node.js Version

v18.04

### OS

Linux - Ubuntu

### Language

Typescript

**Comment by pahud** [comment]
lambda.Code.fromDockerBuild essentially create a container image assets but from what I can see in the [doc - Supported Runtimes](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/edge-functions-restrictions.html), the edge functions only support nodejs and python runtimes. Did you see any example using docker image assets for edge functions in CDK?

**Comment by ETisREAL** [comment]
I don't know, I'm not sure if I ever saw it as an example actually. I just opted for using Inline code. Thank you anyway
