### ISSUE TITLE
(Aws-Stepfunctions): (Issue with catch block in Custom State)

### ISSUE THREAD

**Issue by nivedita104** [aws/aws-cdk#25798]
### Describe the bug

I have a use case where I am using a custom step in one of our state machines and in the catch block, i want to add a new step that is not previously referenced in the state machine. When I tried deploying this, the statemachine throws an error that 
"Invalid State Machine Definition: 'MISSING_TRANSITION_TARGET: Missing 'Next' target: testLambda at /States/CreateTrainingJobWithou
tItemsDataset/Catch[0]/Next, MISSING_TRANSITION_TARGET: Missing 'Next' target: testLambda at /States/CreateTrainingJobWithItemsDataset/Catch[0]/Next' (Service: AWSSte
pFunctions; Status Code: 400; Error Code: InvalidDefinition; Request ID: 77eb25f8-02b7-49b3-8cdd-b1ff1921ec5f; Proxy: null)" (RequestToken: 92e222c1-409c-cfb0-558a-15
f75529c9c7, HandlerErrorCode: InvalidRequest)"

Here, testLambda was the step I introduced in the catch block of the custom step. 

I checked the generated template it was not generating the "testLambda" step. Hence i tried to use the .addCatch() function call that we use with the other steps and i got an error that the .addCatch handler is not supported for custom steps. 

What is the solution for this? Can we not add new steps for catch block in the custom steps or am i missing something here?

### Expected Behavior

The step mentioned in the Next step of the catch block of the custom step props should also get generated in the cfn template.

### Current Behavior

"Invalid State Machine Definition: 'MISSING_TRANSITION_TARGET: Missing 'Next' target: testLambda at /States/CreateTrainingJobWithou
tItemsDataset/Catch[0]/Next, MISSING_TRANSITION_TARGET: Missing 'Next' target: testLambda at /States/CreateTrainingJobWithItemsDataset/Catch[0]/Next' (Service: AWSSte
pFunctions; Status Code: 400; Error Code: InvalidDefinition; Request ID: 77eb25f8-02b7-49b3-8cdd-b1ff1921ec5f; Proxy: null)" (RequestToken: 92e222c1-409c-cfb0-558a-15
f75529c9c7, HandlerErrorCode: InvalidRequest)"

### Reproduction Steps

Default Custom state example in docs:
```
import * as dynamodb from '@aws-cdk/aws-dynamodb';

// create a table
const table = new dynamodb.Table(this, 'montable', {
  partitionKey: {
    name: 'id',
    type: dynamodb.AttributeType.STRING,
  },
});

const finalStatus = new sfn.Pass(this, 'final step');

// States language JSON to put an item into DynamoDB
// snippet generated from https://docs.aws.amazon.com/step-functions/latest/dg/tutorial-code-snippet.html#tutorial-code-snippet-1
const stateJson = {
  Type: 'Task',
  Resource: 'arn:aws:states:::dynamodb:putItem',
  Parameters: {
    TableName: table.tableName,
    Item: {
      id: {
        S: 'MyEntry',
      },
    },
  },
  ResultPath: null,
};

// custom state which represents a task to insert data into DynamoDB
const custom = new sfn.CustomState(this, 'my custom task', {
  stateJson,
});

const chain = sfn.Chain.start(custom)
  .next(finalStatus);

const sm = new sfn.StateMachine(this, 'StateMachine', {
  definition: chain,
  timeout: Duration.seconds(30),
});

// don't forget permissions. You need to assign them
table.grantWriteData(sm);


```
**Now, we add a new pass state and catch block to the custom step :**

```
const errorHandlerLambda = new Pass(
        this,
        "errorHandlerLambda"
    );

const stateJson = {
  Type: 'Task',
  Resource: 'arn:aws:states:::dynamodb:putItem',
  Parameters: {
    TableName: table.tableName,
    Item: {
      id: {
        S: 'MyEntry',
      },
    },
  },
Catch: [
          {
            ErrorEquals: [Errors.ALL],
            ResultPath: "$.JobDetails.errorInfo",
            Next: 'errorHandlerLambda'
          }
        ],
  ResultPath: null,
};

```

This will throw the error I mentioned above. 
I cannot add the errorHandlerLambda to the step function definition as it will only be used as the next step in case the custom step fails.

### CDK CLI Version

"aws-cdk-lib": "^2.60.0", CDKBuild = 4.x;

### Node.js Version

12.x

### OS

Linux

### Language

Typescript

**Comment by peterwoodworth** [comment]
Could you post the full example where you add the errorHandlerLambda to the definition?

Also, why not use [DynamoPutItem](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_stepfunctions_tasks.DynamoPutItem.html)?

**Comment by vishak28** [comment]
@nivedita104 were you able to find a walk-around for this?

**Comment by studna** [comment]
I had the same issue and I switched from using CustomState to `tasks.CallAwsService`. More complex flows I have to write as raw ASL and register it as:

```ts
new CfnStateMachine(this, 'MagicWorkflow', {
  roleArn,
  definition,
})
```

I would love to know if there's a better way.

**Comment by AaronWoodrow** [comment]
We're having exactly the same issue. We have a state machine the we'd like to define using chained CustomStates similar to the original example above but Catch is directing to another CustomState that it cannot find.

**Comment by object-Object** [comment]
I also ran into this issue, and found this workaround (Python):
```py
custom_state._add_choice(sfn.Condition.is_null("$"), handler_state)
```

This is hacky, but it works because [State.addChoice()](https://github.com/aws/aws-cdk/blob/4fd510ec75f03e3e674911cd347fa96ea3edd93a/packages/aws-cdk-lib/aws-stepfunctions/lib/states/state.ts#L321) basically has the same functionality as [State._addCatch()](https://github.com/aws/aws-cdk/blob/4fd510ec75f03e3e674911cd347fa96ea3edd93a/packages/aws-cdk-lib/aws-stepfunctions/lib/states/state.ts#L287), which is what subclasses call to add a catch handler to the state graph. `CustomState` doesn't use the private `choices` list (or `catches`) in its `toStateJson()` implementation, so this doesn't affect the output.

I think the TypeScript equivalent would be this:
```ts
customState.addChoice(sfn.Condition.is_null("$"), handlerState)
```

You might also be able to call `_addCatch()` directly, or create a subclass which implements `addCatch()` in the same way as the existing constructs. We just can't do that from Python because `_addCatch()` is marked as `@internal`.

**Comment by mschwieb** [comment]
For TypeScript I got around this with this hack:
```
const customStateExample = new CustomState(...);
const stateThatDependsOnCustomStateExample = ...;

// HACK: because CDK doesn't support addCatch for CustomState yet: https://github.com/aws/aws-cdk/issues/25798
// @ts-ignore
customStateExample.stateJson = {
  // @ts-ignore
  ...customStateExample.stateJson,
  Catch: [
    {
      ErrorEquals: ['States.ALL'],
      ResultPath: '$.retryConfig',
      Next: stateThatDependsOnCustomStateExample.id,
    },
  ],
};
 


```

**Comment by object-Object** [comment]
@mschwieb Does that actually add `stateThatDependsOnCustomStateExample` to the state machine definition if it's only used as the error handler for `customStateExample` (ie. no non-custom state has `stateThatDependsOnCustomStateExample` as a `.next()` state)? That's what this issue is about.

**Comment by mschwieb** [comment]
yes, `stateThatDependsOnCustomStateExample` is added to the SFN definition as it is a state reached when there is an error thrown. It is similar to the example described by OP.

**Comment by object-Object** [comment]
Here's a reasonably minimal set of test cases to show the issue. Both tests with `addNext=false` are failing as of CDK `2.93.0`.

`test/cdk-ts.test.ts`
```ts
import * as cdk from 'aws-cdk-lib';
import { Template, Match, Capture } from 'aws-cdk-lib/assertions';
import { AppendStack, InlineStack } from '../lib/cdk-ts-stack';

describe.each([InlineStack, AppendStack])("%p", (clazz) => {
    it.each([true, false])("adds ErrorHandler to the definition when addNext=%p", (addNext) => {
        // synth the app
        const app = new cdk.App();
        const stack = new clazz(app, "Stack", addNext);
        const template = Template.fromStack(stack);
    
        // capture the states definition
        const statesCapture = new Capture();
        
        template.hasResourceProperties("AWS::StepFunctions::StateMachine", {
            DefinitionString: Match.serializedJson({
                StartAt: "CustomState",
                States: statesCapture,
            })
        })
    
        // assert ErrorHandler was added to the definition
        expect(statesCapture.asObject()).toHaveProperty("ErrorHandler");
    })
})
```

`lib/cdk-ts-stack.ts`
```ts
import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as sfn from 'aws-cdk-lib/aws-stepfunctions';

// add the catcher in the state definition
export class InlineStack extends cdk.Stack {
  constructor(scope: Construct, id: string, addNext: boolean) {
    super(scope, id);

    let errorHandler = new sfn.Pass(this, "ErrorHandler");

    // this could be any Task, Map, or Parallel which can't be represented with existing constructs
    let customState = new sfn.CustomState(this, "CustomState", {
      stateJson: {
        Type: "Parallel",
        Branches: [],
        Catch: {
          ErrorEquals: ["States.ALL"],
          Next: errorHandler.id,
        },
      }
    })
    
    new sfn.StateMachine(this, "StateMachine", {
      definitionBody: sfn.DefinitionBody.fromChainable(
        // for the test, conditionally add ErrorHandler as the next state after CustomState
        addNext ? customState.next(errorHandler) : customState
      )
    })
  }
}

// add the catcher after defining the state by modifying private properties
export class AppendStack extends cdk.Stack {
  constructor(scope: Construct, id: string, addNext: boolean) {
    super(scope, id);

    let errorHandler = new sfn.Pass(this, "ErrorHandler");

    // this could be any Task, Map, or Parallel which can't be represented with existing constructs
    let customState = new sfn.CustomState(this, "CustomState", {
      stateJson: {
        Type: "Parallel",
        Branches: [],
      }
    })

    // @ts-ignore
    customState.stateJson = {
      // @ts-ignore
      ...customState.stateJson,
      Catch: {
        ErrorEquals: ["States.ALL"],
        Next: errorHandler.id,
      }
    }
    
    new sfn.StateMachine(this, "StateMachine", {
      definitionBody: sfn.DefinitionBody.fromChainable(
        // for the test, conditionally add ErrorHandler as the next state after CustomState
        addNext ? customState.next(errorHandler) : customState
      )
    })
  }
}
```

```
[Function InlineStack]
    √ adds ErrorHandler to the definition when addNext=true (68 ms)
    × adds ErrorHandler to the definition when addNext=false (45 ms)
  [Function AppendStack]
    √ adds ErrorHandler to the definition when addNext=true (20 ms)
    × adds ErrorHandler to the definition when addNext=false (19 ms)

  ● [Function InlineStack] › adds ErrorHandler to the definition when addNext=false

    expect(received).toHaveProperty(path)

    Expected path: "ErrorHandler"
    Received path: []

    Received value: {"CustomState": {"Branches": [], "Catch": {"ErrorEquals": ["States.ALL"], "Next": "ErrorHandler"}, "End": true, "Type": "Parallel"}}

  ● [Function AppendStack] › adds ErrorHandler to the definition when addNext=false

    expect(received).toHaveProperty(path)

    Expected path: "ErrorHandler"
    Received path: []

    Received value: {"CustomState": {"Branches": [], "Catch": {"ErrorEquals": ["States.ALL"], "Next": "ErrorHandler"}, "End": true, "Type": "Parallel"}}
```

**Comment by joonb14** [comment]
I tried above solutions, but still did not solve my problem.
So I just used [StepFunctionsStartExecution](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_stepfunctions_tasks.StepFunctionsStartExecution.html) to start execute my CustomState and applied addCatch to the task. This is messy work-around but it worked for me.
In detail I created 2 files for each child state machine and parent state machine to prevent circular dependency.

```typescript
// My CustomState
const customState = new sfn.CustomState( ... )

// Define a state machine
const child = new sfn.StateMachine(this, "Proto-CvopsConversionStateMachine", {
    definitionBody: sfn.DefinitionBody.fromChainable(customState),
    role: stateMachineRole,
    timeout: Duration.hours(1),
});

//---------------- another file from here -------------------------//

// Include the state machine in a Task state with callback pattern
const task = new tasks.StepFunctionsStartExecution(this, 'ChildTask', {
    stateMachine: child,
    integrationPattern: sfn.IntegrationPattern.RUN_JOB,
    taskTimeout: sfn.Timeout.duration(Duration.hours(1)),
});

// add Catch
task.addCatch(errorHandlerTask.task, {
    errors: ['States.TaskFailed', ... ],
    resultPath: '$.errorInfo',
});

// Define a second state machine with the Task state above
const parent = new sfn.StateMachine(this, 'ParentStateMachine', {
  definition: task,
});


```

**Comment by mfekadu** [comment]
This worked for me 

```
// Sometimes the failure path is not added to the state machine definition, unless _addCatch is called
// https://github.com/aws/aws-cdk/issues/25798
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore

customState._addCatch(failurePath.startState) // intentionally omit the CatchProps because my CustomState already sets it up
```

**Comment by mfekadu** [comment]
For the sake of context 

```

const failurePath: IChainable = ...;

const customState = new CustomState(
    scope,
    "MyCustomState",
    {
        stateJson: {
            "Type": "Task",
            "Resource": myCustomResourceArn,
            "Parameters": {
                "myCustomParameters": myCustomParameters,
                "myCustomInput.$": "$$.Execution.Input",
            },
            "Catch": [
                {
                    "ErrorEquals": [
                        "States.ALL"
                    ],
                    "ResultPath": "$.error",
                    "Next": failurePath.startState.stateId
                }
            ],
            "Retry": [
                {
                    "ErrorEquals": [
                        "MyCustom.ServiceException",
                        "MyCustom.MyCustomException",
                        "MyCustom.SdkClientException"
                    ],
                    "IntervalSeconds": 2,
                    "MaxAttempts": 6,
                    "BackoffRate": 2,
                    "JitterStrategy": "FULL",
                }
            ],
        }
    }
);
```
