### ISSUE TITLE
aws-cdk/aws-s3: cdk can generate an invalid lifecycle configuration for s3:Bucket

### ISSUE THREAD

**Issue by cloventt** [aws/aws-cdk#25824]
### Describe the bug

Synthed buckets can end up with an invalid lifecycle configuration which fails to be applied by CFN when adding the `expiredObjectDeleteMarker` configuration.

For example, according to the CFN docs for [ExpiredObjectDeleteMarker](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-lifecycleconfig-rule.html#cfn-s3-bucket-rule-expiredobjectdeletemarker):

> This cannot be specified with `ExpirationInDays`, `ExpirationDate`, or `TagFilters`.

However, if the developer sets `expire` and `expiredObjectDeleteMarker`, CDK synths the code with no errors.

### Expected Behavior

An invalid lifecycle configuration should fail to synth.

### Current Behavior

When an invalid lifecycle configuration is specified, CDK synths the artifacts without raising any warning or errors. The error only occurs when applying the template in CFN. You get this fantastically cryptic error in the CFN logs, and the stack rolls back:

```
The XML you provided was not well-formed or did not validate against our published schema (Service: Amazon S3; Status Code: 400; Error Code: MalformedXML;)
```

### Reproduction Steps

This code would generate a template that would fail to be applied in CFN:

```typescript
new s3.Bucket(this, 'bucket', {
      lifecycleRules: [
        {
          enabled: true,
          expiration: Duration.days(14),
          noncurrentVersionExpiration: Duration.days(7),
          abortIncompleteMultipartUploadAfter: Duration.days(1),
          expiredObjectDeleteMarker: true,
        },
      ],
    });
```

### Possible Solution

If the user adds an invalid combination of lifecycle configurations, we could do any of these:

* prominently warn the user that the configuration will fail in CFN
* just fail the build completely

### CDK CLI Version

2.79.1

### Node.js Version

19.1.0

### OS

Linux

### Language

Typescript

### Language Version

4.9.5

**Comment by peterwoodworth** [comment]
This should fail at synth, should be easy to fix up. Thanks for reporting!

**Comment by Zishanwang1992** [comment]
I would like to take this task if no one takes it yet.
