### ISSUE TITLE
awslint:physical-name-attribute

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#2582]
We need an awslint rule that will enforce the following guidelines:

All resources should have a single prop that defines it's physical name (of type `PhysicalName`). There should always be an attribute WITH THE SAME NAE that corresponds to this prop

For example:

```ts
export BucketProps {
  bucketName: PhysicalName;
}
```

And:

```ts
export IBucket {
  /** @attribute *.
  readonly bucketName: string;
}
```

- [ ] Add to guidelines

**Comment by skinny85** [comment]
Not all resources allow setting physical names (KMS Keys, for example). Should those be explicitly marked as exceptions in `package.json`?

**Comment by eladb** [comment]
If it's a very rare case, then yes. If it's prevalent (which I don't think so), then maybe we'd want to support doing this on the interface itself.

**Comment by skinny85** [comment]
This has been done 🎉
