### ISSUE TITLE
cdk: Unable to get user input in a `cdk` program

### ISSUE THREAD

**Issue by Qlub53** [aws/aws-cdk#25843]
### Describe the bug

Trying to get user input from stdin through `readline` always ends up with
```
Subprocess exited with error 13
```

Does cdk not allow user input from stdin by design?

### Expected Behavior

`cdk` program accepts user input from stdin.

### Current Behavior

```
Subprocess exited with error 13
```

### Reproduction Steps

```ts
import readline from 'readline';
import { stdin as input, stdout as output } from 'process';

readline.createInterface({ input, output })
	.question(`Please put in your answer: `, answer => console.log(answer));
```
Put the above snippet anywhere in your cdk program. In my case, I put it before `const app = new cdk.App();`.
Then run `cdk synth` or `cdk deploy`.

### CDK CLI Version

2.69.0

### Node.js Version

16.8.0

### OS

macOS 12.5

### Language

Typescript

### Language Version

4.6.3

**Comment by peterwoodworth** [comment]
And also why not use [parameters](https://docs.aws.amazon.com/cdk/v2/guide/parameters.html)?

**Comment by Qlub53** [comment]
> And also why not use [parameters](https://docs.aws.amazon.com/cdk/v2/guide/parameters.html)?

Because some decisions in my logic can only be made at runtime and should require human intervention.
