### ISSUE TITLE
aws-cdk-lib.aws_rds.DatabaseClusterProps: Deprecation Warnings

### ISSUE THREAD

**Issue by argarinpauljohn** [aws/aws-cdk#25898]
### Describe the feature

```
use writer and readers instead
This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_rds.DatabaseClusterProps#instances is deprecated.

use writer and readers instead
This API will be removed in the next major release.
```

So we fixed this by using writer and readers instead. But CDK will destroy the old database instances then recreate them. This isn't good for us as restoring the data in the new databases will require us more time and work. Would it be possible for the CDK team to handle the migration?

### Use Case

It will be cumbersome backing up the data and restoring them especially in our production databases.

### Proposed Solution

Handle the migration of data in the background?

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.82.0

### Environment details (OS name and version, etc.)

macOS Ventura 13.3.1

**Comment by peterwoodworth** [comment]
We do offer a migration path, have you tried this out? https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_rds-readme.html#migrating-from-instanceprops

**Comment by peterwoodworth** [comment]
1. It looks to me like there is not currently a way to set `deleteAutomatedBackups`. With the modern reader/writer API, we would need to add this, or else you would have to use escape hatches
2. On a quick glance it looks like `instanceIdentifiers` should be returning something. The `instanceIdentifiers` returned from this function is set as the construct property, but it looks like this is only done for readers, not for writers, so it would be expected in your case. I'm not familiar enough with this service however to know if that is _right_ https://github.com/aws/aws-cdk/blob/006b542844726afb9e52ee728e6cd14ab9f975b7/packages/aws-cdk-lib/aws-rds/lib/cluster.ts#L666

**Comment by argarinpauljohn** [comment]
Thank you @peterwoodworth! I will file separate issues to request for these features!

**Comment by peterwoodworth** [comment]
Great @argarinpauljohn, I've triaged and responded to both of them, should be pretty easy for any contributors to implement 🙂. I think we can close this issue out now that we have two separate ones, ping me if you have any more concerns.

**Comment by argarinpauljohn** [comment]
Thanks @peterwoodworth! I will try to contribute! :)

**Comment by andreprawira** [comment]
@peterwoodworth could you please tell me how do we suppress these warnings?
