### ISSUE TITLE
aws_ecs: TaskDefinition constraint.type 'distinctInstance' is not supported

### ISSUE THREAD

**Issue by IllarionovDimitri** [aws/aws-cdk#25905]
### Describe the bug

According to the documentation ecs.Ec2Taskdefinition supports placement_constraints attribute (which looks kinda redundant, because ecs.Ec2Service supports both placement_constraints and placement_strategies)

```python
ecs.Ec2TaskDefinition(
  self,
  id",
  family="ecs-family",
  task_role=task_role,
  placement_constraints=[ecs.PlacementConstraint.distinct_instances()],
)
```

Stack deployment raises following exception

```
Resource handler returned message: "Invalid request provided: Create TaskDefinition: constraint.type 'distinctInstance' is not supported. (Service: AmazonECS; Status Code: 400; Error Code: ClientException; Request ID: 71214110-96ed-4631-a83e-74a3
8206a8db; Proxy: null)" (RequestToken: 59dedc0b-cb70-0b09-c0f5-9b580c5fe3da, HandlerErrorCode: InvalidRequest)
```

### Expected Behavior

Either the ecs.Ec2Taskdefinition can be properly deployed with set placement_constraints attribute or it can be only defined in ecs.Ec2Service (regarding redundancy I am no quite sure, probably there are cases where definition of placement_constraints in ecs.Ec2Taskdefinition also makes sense)

### Current Behavior

Error during stack deployment if placement_constraints is defined in ecs.Ec2Taskdefinition 

### Reproduction Steps

Define placement_constraints as follows in ecs.Ec2Taskdefinition and deploy the esc stack ()there is no error with `cdk synth` or `cdk ls`)

```python
ecs.Ec2TaskDefinition(
  self,
  id",
  family="ecs-family",
  task_role=task_role,
  placement_constraints=[ecs.PlacementConstraint.distinct_instances()],
)
```

### CDK CLI Version

2.83.0

### Node.js Version

18

### OS

Ubuntu 20.04.5 LTS

### Language

Python

### Language Version

3.10.6

**Comment by peterwoodworth** [comment]
It looks like we should clarify this in the docs. You can specify `distinctInstances` when creating a Service, or running a task. You can specify `memberOf` when doing the previous two actions, or when creating a task or new revision. See the docs [here](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-placement-constraints.html)

In CloudFormation this is reflected in being only able to specify [`memberOf` for TaskDefinition](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-taskdefinitionplacementconstraint.html), and being able to specify [both for `Service`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-service-placementconstraint.html). This is also reflected in the API model as having different types for `TaskDefinitionPlacementConstraint` and `PlacementConstraint`.

**Comment by IllarionovDimitri** [comment]
understood.

at least in docs for Python CDK both Ec2Service and Ec2TaskDefinition implement the placement_constraints as `(Optional[Sequence[[PlacementConstraint]])`, so there is no `TaskDefinitionPlacementConstraint`, only the `PlacementConstrain`, which implements both `distinct_instances()`  and `member_of` class methods

**Comment by peterwoodworth** [comment]
Sorry I wasn't clear, we don't separate these in our API, I was describing how they are separated in both CloudFormation and the actual ECS API. I don't think we need to separate these on our end, but we should put in the docstring and make a check at synth time that there are some invalid configurations.
