### ISSUE TITLE
ECS: TaskDefinition.addContainer incorrectly fails validation

### ISSUE THREAD

**Issue by digitalsanctum** [aws/aws-cdk#2592]
**Describe the bug**
Attempting to call addContainer method on a TaskDefinition will fail validation if the ContainerDefinition does not include a TaskDefinition.

**To Reproduce**
This fails validation:

```
this.taskDefinition = TaskDefinition(
            this, "task-definition", TaskDefinitionProps.builder()
                .withFamily(props.family)
                .withCompatibility(Compatibility.Fargate)
                .withNetworkMode(NetworkMode.AwsVpc)
                .withCpu(props.cpu)
                .withMemoryMiB(props.memory)
                .build()
        )

        val containerImage = ContainerImage.fromEcrRepository(props.repository, props.tag)

        this.taskDefinition.addContainer(props.containerName, ContainerDefinitionProps.builder()
            .withImage(containerImage)
            .withEssential(true)
            .withCpu(props.containerCpu)
            .withMemoryLimitMiB(props.containerMemory)
            .build())
```
and this passes validation (with task definition added to `ContainerDefinitionProps`):
```
this.taskDefinition = TaskDefinition(
            this, "task-definition", TaskDefinitionProps.builder()
                .withFamily(props.family)
                .withCompatibility(Compatibility.Fargate)
                .withNetworkMode(NetworkMode.AwsVpc)
                .withCpu(props.cpu)
                .withMemoryMiB(props.memory)
                .build()
        )

        val containerImage = ContainerImage.fromEcrRepository(props.repository, props.tag)

        this.taskDefinition.addContainer(props.containerName, ContainerDefinitionProps.builder()
            .withImage(containerImage)
            .withEssential(true)
            .withCpu(props.containerCpu)
            .withMemoryLimitMiB(props.containerMemory)
            .withTaskDefinition(this.taskDefinition)
            .build())
```

**Expected behavior**
Should not require task definition to be included in ContainerDefinitionProps since the `addContainer` code appears to add task definition anyway. See: https://github.com/awslabs/aws-cdk/blob/v0.31.0/packages/@aws-cdk/aws-ecs/lib/base/task-definition.ts#L229

**Version:**
 - Ubuntu 18.04
 - Java/Kotlin
 - 0.31.0

**Comment by SoManyHs** [comment]
Hi @digitalsanctum,

taskDefinition#[addContainer](https://github.com/awslabs/aws-cdk/blob/v0.31.0/packages/@aws-cdk/aws-ecs/lib/base/task-definition.ts#L229) takes `ContainerDefinitionOptions` rather than `ContainerDefinitionProps`, which does not require a taskDefinition field. See: https://github.com/awslabs/aws-cdk/blob/master/packages/%40aws-cdk/aws-ecs/lib/container-definition.ts#L9

Let me know if that works for you!

**Comment by digitalsanctum** [comment]
It does, thanks. Although, I'm left wondering when one should use `ContainerDefinition` which takes `ContainerDefinitionProps` versus the `taskDefinition.addContainer(..., ContainerDefinitionOptions)`. I had started down the road creating a `ContainerDefinition` and adding things like port mappings to it before I realized you couldn't then associate it with a `TaskDefinition` without using the `addContainer` method.

**Comment by rix0rrr** [comment]
Two observations:

- We can prevent this from happening in the future by hiding some of the types that users aren't supposed to use?
- I'm wondering how the incorrect Java code even compiled, and why the failing case was failing. To my mind, both of those things shouldn't be possible. More investigation needed.

**Comment by digitalsanctum** [comment]
To address your second point: the code wasn't incorrect. Since `ContainerDefinitionProps` extends `ContainerDefinitionOptions`. It wasn't until runtime that the null check on `TaskDefinition` made it fail.

Something to consider in terms of the builder pattern is to make required properties part of the builder constructor. Although the docs do a good job of outlining which properties are required, it's a guessing game while coding things up. Even this only gets you so far in the cases where certain properties are required only in cases where particular value(s) for other properties are set.

**Comment by SomayaB** [comment]
Closing this issue since a solution was provided. Feel free to open a feature request to address how things are implemented.
