### ISSUE TITLE
RDS: DatabaseCluster Instance Identifiers Attribute

### ISSUE THREAD

**Issue by argarinpauljohn** [aws/aws-cdk#25947]
### Describe the feature
In the new writer/reader API, only readers' IDs are returned: [aws-cdk/packages/aws-cdk-lib/aws-rds/lib/cluster.ts](https://github.com/aws/aws-cdk/blob/006b542844726afb9e52ee728e6cd14ab9f975b7/packages/aws-cdk-lib/aws-rds/lib/cluster.ts#L666)

Related issue: https://github.com/aws/aws-cdk/issues/25898

### Use Case

We need the writer's instance ID to subscribe to its events.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.82.0

### Environment details (OS name and version, etc.)

macOS Ventura 13.3.1

**Comment by peterwoodworth** [comment]
Makes sense to return the writer ID here as well as the reader ID. I think this should only take a one liner which pushes the `writer.instanceIdentifier` to `instanceIdentifiers`. https://github.com/aws/aws-cdk/blob/006b542844726afb9e52ee728e6cd14ab9f975b7/packages/aws-cdk-lib/aws-rds/lib/cluster.ts#L666

**Comment by vincent-dm** [comment]
Is anyone working on this?
