### ISSUE TITLE
(provider-framework): (lambda runtime still using NODEJS_14)

### ISSUE THREAD

**Issue by alexherriott** [aws/aws-cdk#25940]
### Describe the bug

as part of release 2.77.0 lambdas were updated from nodejs14 to nodejs 16. 
https://github.com/aws/aws-cdk/releases/tag/v2.77.0

however it seems that some were missed - https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/custom-resources/lib/provider-framework/provider.ts
nodejs_14 is still being used

### Expected Behavior

nodejs_16 to be used for all CDK generated lambdas since release 2.77.0

### Current Behavior

NODEJS_14 is still used in some cases

### Reproduction Steps

deploy CDK which uses custom provider.

### Possible Solution

update all lambdas so they do not use NODEJS_14

### CDK CLI Version

2.77.0

### Node.js Version

16.20.0

### OS

Ubuntu standard:6.0

### Language

Typescript

### Language Version

Typescript 4.9.4

**Comment by peterwoodworth** [comment]
Thanks for the report 👍🏻
