### ISSUE TITLE
Lambda code asset reuse

### ISSUE THREAD

**Issue by mitchlloyd** [aws/aws-cdk#2595]
There are 2 new CDK features that seem to nearly address a use case I have. 

First we have the ability to `--build-exclude` an asset, letting us reuse the previously uploaded asset for a Lambda. Secondly [a feature exposing an asset fingerprint and asset sha256 hash](https://github.com/awslabs/aws-cdk/pull/2334) is in progress.

With CDK I'd like to express: "when there is no local code asset, don't deploy a new code asset and don't create a new Lambda version".

```ts
// This is some hypothetical API that signals asset reuse.
let codeAsset = lambda.Code.previousAsset();
if (fs.existsSync(codePath)) {
  codeAsset = lambda.Code.asset(codePath);
}

// Everything else from here on out is typical Lambda use today
const lambdaFunction = new lambda.Function(this, 'Resource', {
  code: codeAsset,
  // ...
});

const alias = new lambda.Alias(this, 'LiveAlias', {
  aliasName: 'Live',
  description: 'Live alias used to shift traffic during deployments.',
  version: lambdaFunction.addVersion(codeAsset.sourceHash, codeAsset.bundleHash),
});
```

`PreviousAsset` would both mark the asset to be reused (i.e. keep previous deployment parameters) _and_ expose the previous hashes for versioning.

Does this seems possible? Am I missing the boat and there is a better way to accomplish this workflow?

**Comment by eladb** [comment]
This now happens by default. Assets are identified by the hash of their source and won't get uploaded if already exists.
