### ISSUE TITLE
appsync: support Merged APIs

### ISSUE THREAD

**Issue by jumic** [aws/aws-cdk#25960]
### Describe the feature

Since end of May, AppSync supports Merged APIs. Multiple APIs can be combined into a single API.
At the moment, this feature is missing in AWS CDK.

### Use Case

Multiple teams develop components for an application. Each team develops their AppSync APIs independently. A Merged API is necessary to provide a central AppSync API with APIs from each component.

### Proposed Solution

Tasks that I already identified:
- `ApiType` has to be set to `MERGED`.
- An IAM role has to be created and passed to attribute `MergedApiExecutionRoleArn`.

Workaround: use escape hatches (not yet tested)

### Other Information

AWS Blog Post:
https://aws.amazon.com/blogs/mobile/introducing-merged-apis-on-aws-appsync/

AWS Documentation:
https://docs.aws.amazon.com/appsync/latest/devguide/merged-api.html

CoudFormation already supports this feature:
https://docs.aws.amazon.com/de_de/AWSCloudFormation/latest/UserGuide/aws-resource-appsync-graphqlapi.html#cfn-appsync-graphqlapi-apitype

I am not currently working on this feature request. Someone else is welcome to take it over. If I start working on the design/implementation myself, I'll leave a comment here again.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

v2.83.1

### Environment details (OS name and version, etc.)

macOS 13.4

**Comment by pahud** [comment]
Merge API is really awesome! Thank you for your feature request and we welcome and appreciate your PR.

**Comment by jumic** [comment]
There are two additional tasks we need to consider:
- Resource type [SourceApiAssociation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appsync-sourceapiassociation.html) must be created for each associated source GraphQL API.
- A MergedAPI doesn't contain a schema. Changing attribute `schema` to optional is not possible. This would be a breaking change. So I would suggest creating a new L2 construct, e.g. MergedGraphqlApi. Extending the existing GraphQL class is not possible because it would require a schema that is not used in Merged APIs.

As mentioned in the [contributing guide](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md), I will create a new RFC in the RFC repo for this new L2 construct.

@pahud: Please let me know if I should proceed in a different way. Thanks.

**Comment by pahud** [comment]
I will bring this to the core team for discussion and get back to you here.
