### ISSUE TITLE
SageMaker Notebook Interface VPC Endpoint does not deploy (service name is incorrect)

### ISSUE THREAD

**Issue by chriswessells** [aws/aws-cdk#2597]
**Describe the bug**
The SageMaker Notebook Interface VPC Endpoint does not deploy. The service name is incorrect.

When deploying I receive the following error
The Vpc Endpoint Service 'aws.sagemaker.us-west-2.sagemaker' does not exist (Service: AmazonEC2; Status Code: 400; Error Code: InvalidServiceName; Request ID: bb11fb4a-b775-49b3-958c-f75cc8dcd63c)

**To Reproduce**
Create directory SagemakerWorkflow
cd SagemakerWorkflow
cdk init --language typescript
below is the sagemaker_workflow-stack.ts file
import cdk = require('@aws-cdk/cdk');
import ec2 = require('@aws-cdk/aws-ec2');
export class SagemakerWorkflowStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);
    const vpc = new ec2.VpcNetwork(this, 'sagemakerVpc', { 
      maxAZs: 2,
      natGateways: 1,
      gatewayEndpoints: {
        S3: {
          service: ec2.GatewayVpcEndpointAwsService.S3
        }
      }
    });
const sageMakerNotebookEndpoint = vpc.addInterfaceEndpoint('sageMakerNotebookEndpoint', {
      service: ec2.InterfaceVpcEndpointAwsService.SageMakerNotebook
    });
    sageMakerNotebookEndpoint.connections.allowDefaultPortFromAnyIpv4();
  }
}

**Expected behavior**
When creating a SageMaker Notebook Interface VPC Endpoint, it should deploy

**Version:**
 - OS Mac
 - Programming Language Typescript
 - CDK Version 0.31

**Comment by chriswessells** [comment]
in file  aws-cdk/packages/@aws-cdk/aws-ec2/lib/vpc-endpoint.ts 

line 208 should be 
public static readonly SageMakerNotebook = new InterfaceVpcEndpointAwsService('sagemaker', 'notebook');

I'm building the cdk now to test

**Comment by chriswessells** [comment]
Tested the changes and the recommended change to line 208 of file aws-cdk/packages/@aws-cdk/aws-ec2/lib/vpc-endpoint.ts deployed the endpoint successfully.

**Comment by nija-at** [comment]
Closing this issue. Already fixed in PR https://github.com/aws/aws-cdk/pull/2598
