### ISSUE TITLE
aws_ecr: CDK only creates "ECRAutoDeleteImagesCustomResourceProvider" for 1 ECR repository instead of 2

### ISSUE THREAD

**Issue by adrenaline681** [aws/aws-cdk#26025]
### Describe the bug

I create 2 repositories with removal_policy set to Destroy and with auto_delete_images set to True.

When CDK presents me with the IAM Statements, there is only "ECRAutoDeleteImagesCustomResourceProvider" for the first repository. Due to this when I destroy the stack only the first repository gets deleted and I get an error on the 2nd repository saying that t I dont have permissions to delete the images:

```
AccessDeniedException: User: 
arn:aws:sts::536382905314:assumed-role/Pipeline-CustomECRAutoDeleteImagesCustomResourcePr-17A3R3WYBMEU0/Pipeline-CustomECRAutoDeleteImagesCustomResourcePr-gb4AMTavlZO9 is not authorized to perform: ecr:DescribeRepositories on resource: arn:aws:ecr:
us-west-2:536382905314:repository/project-web because no identity-based policy allows the ecr:DescribeRepositories action
```

### Expected Behavior

When I destroy the stack both repositories get deleted and not just the first one.

### Current Behavior

When I destroy the stack only first repository gets deleted and I get an error:

```
The repository with name 'project-web' in registry with id '536382905314' cannot be deleted because it still contains images
```

### Reproduction Steps

```
class PipelineStack(core.Stack):
    def __init__(self, scope, construct_id, context, **kwargs):
        super().__init__(scope, construct_id, **kwargs)
        ecr_backend = ecr.Repository(
            self, 'ECRBackend',
            repository_name='project-api',
            removal_policy=core.RemovalPolicy.DESTROY,
            auto_delete_images=True,
        )
        ecr_frontend = ecr.Repository(
            self, 'ECRFrontend',
            repository_name='project-web',
            removal_policy=core.RemovalPolicy.DESTROY,
            auto_delete_images=True,
         )
```

### CDK CLI Version

2.83.1 (build 006b542)

### Node.js Version

v16.14.2

### OS

Windows 10

### Language

Python

### Language Version

Python 3.10.4

**Comment by pahud** [comment]
close in favor of https://github.com/aws/aws-cdk/issues/25308
