### ISSUE TITLE
Amazon OpenSearch Service: High Level Constructs For OpenSearch MultiAZWithStandBy Feature

### ISSUE THREAD

**Issue by AmanRajAWS** [aws/aws-cdk#26026]
### Describe the feature

The OpenSearch Team has recently launched MultiAZWithStandby Feature for OpenSearch Domain. [Feature Documentation Link](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/managedomains-multiaz.html#:~:text=around%20these%20configurations.-,Multi%2DAZ%20with%20Standby,-Multi%2DAZ%20with).  According to the CDK docs currently there is no high level CDK construct for this feature.[CDK Docs link for the MultiAZWIthStandbyFeature](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_opensearchservice.CfnDomain.ClusterConfigProperty.html#:~:text=OpenSearch%20Service%20.-,multiAzWithStandbyEnabled%3F,-Type%3A%20boolean)

### Use Case

The general recommendation is to use high level constructs and due to lack of High level construct for this feature, the CDK template needs to be migrated to use CFN constructs if there is a need to Create an OpenSearchDomain with MultiAZWithStandBy. This serves as a hinderance to the adoption of the MultiAZWithStandBy feature for AWS OpenSearch Domains.

### Proposed Solution

Add the MultiAZWithStandByAttribute to the capacityConfig object [CDK Doc for CapacityConfig Attribute](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_opensearchservice.CapacityConfig.html) . 
 A MultiAZWithStandBy based OpenSearchDomain created using CDK high level constructs should look like
const domain = new Domain(this, 'Domain', {
  version: EngineVersion.OPENSEARCH_1_0,
  capacity: {
    masterNodes: 3,
    **multiAZWithStandbyEnabled: true (possible values: [true,false])**
  },
});

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.84.0

### Environment details (OS name and version, etc.)

macOS Ventura 13.4

**Comment by pahud** [comment]
Is this feature supported by cloudformation? If not, it sounds like we need to create a L3(or at least L2.5) construct for that?

**Comment by AmanRajAWS** [comment]
yes this feature is supported by cloudformation
[docs link](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-opensearchservice-domain-clusterconfig.html#:~:text=%3A%20No%20interruption-,MultiAZWithStandbyEnabled,Update%20requires%3A%20No%20interruption,-WarmCount)

**Comment by peterwoodworth** [comment]
You should be able to easily add this now to your template with an escape hatch.

Labeled as good first issue, all we need to do is add a boolean prop it appears

**Comment by tmokmss** [comment]
@AmanRajAWS 
Hi, I always get the following error with `multiAZWithStandbyEnabled: true`. But I think `Auto-Tune` feature cannot be controlled from CloudFormation for now. Should `multiAZWithStandbyEnabled` be true by default then? I'm not sure how this option can be used. 

```
Resource handler returned message: "Invalid request provided: You must turn on Auto-Tune for domains with standby. 
(Service: OpenSearch, Status Code: 400, Request ID: eac0100d-5014-43b3-8af0-84e2d0e10197)" (RequestToken: 51cb5e17-12ae-508e-0eb8-de5a14a75639, HandlerErrorCode: InvalidRequest)
```

**Comment by tmokmss** [comment]
@Aman199825 Thanks. I also found the doc explaining that:

> OpenSearch Service enables Auto-Tune by default on new domains.
> https://docs.aws.amazon.com/opensearch-service/latest/developerguide/auto-tune.html#auto-tune-enable

So I checked my configuration and turned out that I'm using `t3.medium.search` as instance type, which does not support Multi-AZ with standby feature:

> Multi-AZ with Standby only works with the m5, c5, r5, r6g, c6g, m6g, r6gd and i3 instance types.
> https://docs.aws.amazon.com/opensearch-service/latest/developerguide/managedomains-multiaz.html

I think this is the reason why I'm seeing the error. I also think CDK should validate this limitation, so I'll submit a PR or issue for this.

code to reproduce:

```ts
import * as cdk from 'aws-cdk-lib';
import { Domain, EngineVersion } from 'aws-cdk-lib/aws-opensearchservice';
import { EbsDeviceVolumeType, Vpc } from 'aws-cdk-lib/aws-ec2';

const stack = new cdk.Stack(app, 'OpenSearchAutoTuneReproduce', {
  env: {
    region: 'ap-northeast-1',
  },
});

const vpc = new Vpc(stack, 'Vpc', {natGateways: 1});
const targetSubnets = vpc.privateSubnets;

new Domain(stack, 'Domain', {
  version: EngineVersion.OPENSEARCH_2_11,
  capacity: {
    dataNodeInstanceType: 't3.medium.search',
    dataNodes: targetSubnets.length,
    multiAzWithStandbyEnabled: true, // not usable with t3
  },
  zoneAwareness: {
    enabled: true,
    availabilityZoneCount: targetSubnets.length,
  },
  ebs: {
    volumeSize: 30,
    volumeType: EbsDeviceVolumeType.GP3,
    throughput: 125,
    iops: 3000,
  },
  enforceHttps: true,
  fineGrainedAccessControl: {
    masterUserName: 'admin',
  },
  nodeToNodeEncryption: true,
  encryptionAtRest: {
    enabled: true,
  },
  vpc,
  vpcSubnets: [{ subnets: targetSubnets }],
  logging: {
    auditLogEnabled: true,
    slowSearchLogEnabled: true,
    appLogEnabled: true,
    slowIndexLogEnabled: true,
  },
  removalPolicy: cdk.RemovalPolicy.DESTROY,
});
```

**Comment by tmokmss** [comment]
@Aman199825 Do you know if OR1 and Im4gn instance type supports multi-AZ with standby feature?

https://docs.aws.amazon.com/opensearch-service/latest/developerguide/supported-instance-types.html

It's not listed in [this doc](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/managedomains-multiaz.html#:~:text=the%20troubleshooting%20guide.-,Limitations,-When%20you%20set) but I suspect the doc is wrong because these instance types looks new and there's no reason not to support the feature.

**Comment by Aman199825** [comment]
@tmokmss yes they are supported as instance types but not as master type

**Comment by tmokmss** [comment]
Thanks. I just sent a feedback to the doc.
