### ISSUE TITLE
lambda: add PYTHON_3_10 runtime

### ISSUE THREAD

**Issue by rittneje** [aws/aws-cdk#26038]
### Describe the feature

Lambda added support for Python 3.10 back in April. https://aws.amazon.com/about-aws/whats-new/2023/04/aws-lambda-python-3-10/

CloudFormation already supports it. https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-runtime

Add PYTHON_3_10 to the runtime enum. https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_lambda/Runtime.html

Also, this should not have needed a feature request. This process should be automated such that as soon as a new runtime is supported by CloudFormation, it also gets added to CDK.

### Use Case

n/a

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.74.0

### Environment details (OS name and version, etc.)

Alpine 3.17

**Comment by rittneje** [comment]
@pahud I guess since the docs are sorting the enum wrong (alphabetical), we did not see it. Is there any way to fix that so it appears after PYTHON_3_9?

**Comment by peterwoodworth** [comment]
It's sorting alphabetically which works fine enough, so probably not.
