### ISSUE TITLE
aws-stepfunctions: Nested arrays are not serialized correctly

### ISSUE THREAD

**Issue by markmansur** [aws/aws-cdk#26045]
### Describe the bug

If a StepFunction definition contains a nested array, the nested array is serialized as an object where the keys are the array indices.

This looks like an issue with the `FieldUtils.renderObject` method.

Duplicate of #14599 

### Expected Behavior

I would expect the following to be logged to the console

```
{"myNestedArray":[[[123,123],[456,456]]]}
```

### Current Behavior

Current behavior treats the nested array as an object and adds indices
```{"myNestedArray":[{"0":[123,123],"1":[456,456]}]}```

### Reproduction Steps

 ```
console.log(
      JSON.stringify(
        FieldUtils.renderObject({
          myNestedArray: [
            [
              [123, 123],
              [456, 456],
            ],
          ],
        }),
      ),
    );
```

### CDK CLI Version

2.84.0

### Node.js Version

18

### OS

MacOS

### Language

Typescript

**Comment by peterwoodworth** [comment]
Thanks for creating another report for this - we don't have issues configured to close automatically anymore after just inactivity
