### ISSUE TITLE
(hotswap): do not support attributes for distribution

### ISSUE THREAD

**Issue by alishanP** [aws/aws-cdk#26061]
### Describe the bug

Could not perform a hotswap deployment, because the CloudFormation template could not be resolved: We don't support attributes of the 'AWS::CloudFront::Distribution' resource. This is a CDK limitation. Please report it at https://github.com/aws/aws-cdk/issues/new/choose

### Expected Behavior

hotswap successful

### Current Behavior

Could not perform a hotswap deployment, because the CloudFormation template could not be resolved: We don't support attributes of the 'AWS::CloudFront::Distribution' resource. This is a CDK limitation. Please report it at https://github.com/aws/aws-cdk/issues/new/choose

### Reproduction Steps

try hotswapping with a attributes of the 'AWS::CloudFront::Distribution' resource

### CDK CLI Version

4.0

### Node.js Version

18

### OS

mac

### Language

Typescript

**Comment by peterwoodworth** [comment]
What's the `cdk diff`? What resource(s) were you trying to hotswap?

**Comment by alishanP** [comment]
✨ hotswapping resources:
   ✨ Contents of S3 Bucket 'staticwebsitestack-personal-sitebucket04cddfa5-1mqdhww4ch7j0'
   ✨ Contents of S3 Bucket 'staticwebsitestack-perso-siteconfigbucketc620d08b-9sciqytbs8ua'
   ✨ Lambda Function 'StaticWebsiteStack-person-StaticWebsiteLambdaF07F5-OXNtUZdNUn9M'
   ✨ Lambda Version for Function 'StaticWebsiteStack-person-StaticWebsiteLambdaF07F5-OXNtUZdNUn9M'
   ✨ Lambda Alias 'release' for Function 'StaticWebsiteStack-person-StaticWebsiteLambdaF07F5-OXNtUZdNUn9M'
   ✨ Lambda Function 'StaticWebsiteStack-person-dashboardUrlLambda2D4D06-vUxs9VgL0UCU'
   ✨ Lambda Version for Function 'StaticWebsiteStack-person-dashboardUrlLambda2D4D06-vUxs9VgL0UCU'
   ✨ Lambda Alias 'release' for Function 'StaticWebsiteStack-person-dashboardUrlLambda2D4D06-vUxs9VgL0UCU'

The S3 buckets work but the rest dont. Thats the only error i get - Could not perform a hotswap deployment, because the CloudFormation template could not be resolved: We don't support attributes of the 'AWS::CloudFront::Distribution' resource. This is a CDK limitation. Please report it at https://github.com/aws/aws-cdk/issues/new/choose

**Comment by peterwoodworth** [comment]
Please share your `cdk diff`

**Comment by alishanP** [comment]
Resources
[-] AWS::Lambda::Version StaticWebsiteLambda/CurrentVersion StaticWebsiteLambdaCurrentVersion9C2ACB00a43ba08ff912d4bdffd8dbd38dcb3d50 destroy
[-] AWS::Lambda::Version dashboardUrlLambda/CurrentVersion dashboardUrlLambdaCurrentVersion061325DC859c3c7a81c64b40218603d36dd65f46 destroy
[-] AWS::ApiGateway::Deployment apiGatewayDeployment716b900b80ef36b0da16a6bee52b86fa1e44ef1c apiGatewayDeployment716b900b80ef36b0da16a6bee52b86fa1e44ef1c destroy
[+] AWS::Lambda::Version StaticWebsiteLambda/CurrentVersion StaticWebsiteLambdaCurrentVersion9C2ACB003dfb452d4b42b29dbbb9f451437a6dad 
[+] AWS::Lambda::Version dashboardUrlLambda/CurrentVersion dashboardUrlLambdaCurrentVersion061325DCd3c72beae9e1594737221e9c0569d13f 
[+] AWS::ApiGateway::Deployment apiGatewayDeploymented7bdda9c3cd290bad13d98545f4080d79a5593e apiGatewayDeploymented7bdda9c3cd290bad13d98545f4080d79a5593e 
[~] AWS::S3::Bucket siteBucket siteBucket04CDDFA5 
 └─ [~] Tags
     └─ @@ -1,6 +1,6 @@
        [ ] [
        [ ]   {
        [-]     "Key": "aws-cdk:cr-owned:37b599d2-aaa1-4c81-bb0d-eb1a66743031:1343b980",
        [+]     "Key": "aws-cdk:cr-owned:7761a8ad-0fd0-48b1-af68-e925c69a5d6c:1343b980",
        [ ]     "Value": "true"
        [ ]   }
        [ ] ]
[~] AWS::S3::Bucket siteConfigBucket siteConfigBucketC620D08B 
 └─ [~] Tags
     └─ @@ -1,6 +1,6 @@
        [ ] [
        [ ]   {
        [-]     "Key": "aws-cdk:cr-owned:37b599d2-aaa1-4c81-bb0d-eb1a66743031/site-config/:f3d77e05",
        [+]     "Key": "aws-cdk:cr-owned:7761a8ad-0fd0-48b1-af68-e925c69a5d6c/site-config/:f3d77e05",
        [ ]     "Value": "true"
        [ ]   }
        [ ] ]
[~] Custom::CDKBucketDeployment siteBucketDeployment/CustomResource siteBucketDeploymentCustomResource42B26A85 
 └─ [~] DestinationBucketKeyPrefix
     ├─ [-] 37b599d2-aaa1-4c81-bb0d-eb1a66743031
     └─ [+] 7761a8ad-0fd0-48b1-af68-e925c69a5d6c
[~] Custom::CDKBucketDeployment siteConfigBucketDeployment/CustomResource siteConfigBucketDeploymentCustomResource56EC6EAA 
 └─ [~] DestinationBucketKeyPrefix
     ├─ [-] 37b599d2-aaa1-4c81-bb0d-eb1a66743031/site-config/
     └─ [+] 7761a8ad-0fd0-48b1-af68-e925c69a5d6c/site-config/
[~] AWS::Lambda::Function StaticWebsiteLambda StaticWebsiteLambdaF07F584D 
 ├─ [~] Description
 │   ├─ [-] Generated on 2023-06-20T18:54:31.576Z for deployment version: 37b599d2-aaa1-4c81-bb0d-eb1a66743031
 │   └─ [+] Generated on 2023-06-20T19:38:31.176Z for deployment version: 7761a8ad-0fd0-48b1-af68-e925c69a5d6c
 └─ [~] Environment
     └─ [~] .Variables:
         └─ [~] .deploymentVersion:
             ├─ [-] 37b599d2-aaa1-4c81-bb0d-eb1a66743031
             └─ [+] 7761a8ad-0fd0-48b1-af68-e925c69a5d6c
[~] AWS::Lambda::Function dashboardUrlLambda dashboardUrlLambda2D4D06B8 
 ├─ [~] Description
 │   ├─ [-] Zapdos Data Visualization Url lambda. Generated on 2023-06-20T18:54:31.566Z
 │   └─ [+] Zapdos Data Visualization Url lambda. Generated on 2023-06-20T19:38:31.167Z
 └─ [~] Environment
     └─ [~] .Variables:
         └─ [~] .deploymentVersion:
             ├─ [-] 37b599d2-aaa1-4c81-bb0d-eb1a66743031
             └─ [+] 7761a8ad-0fd0-48b1-af68-e925c69a5d6c
[~] AWS::Lambda::Alias dashboardUrlLambdaAlias dashboardUrlLambdaAlias0EC80E5E 
 └─ [~] FunctionVersion
     └─ [~] .Fn::GetAtt:
         └─ @@ -1,4 +1,4 @@
            [ ] [
            [-]   "dashboardUrlLambdaCurrentVersion061325DC859c3c7a81c64b40218603d36dd65f46",
            [+]   "dashboardUrlLambdaCurrentVersion061325DCd3c72beae9e1594737221e9c0569d13f",
            [ ]   "Version"
            [ ] ]
[~] AWS::Lambda::Alias StaticWebsiteLambdaAlias StaticWebsiteLambdaAlias2F02FAAC 
 └─ [~] FunctionVersion
     └─ [~] .Fn::GetAtt:
         └─ @@ -1,4 +1,4 @@
            [ ] [
            [-]   "StaticWebsiteLambdaCurrentVersion9C2ACB00a43ba08ff912d4bdffd8dbd38dcb3d50",
            [+]   "StaticWebsiteLambdaCurrentVersion9C2ACB003dfb452d4b42b29dbbb9f451437a6dad",
            [ ]   "Version"
            [ ] ]
[~] AWS::ApiGateway::Stage apiGatewayStage apiGatewayStage 
 └─ [~] DeploymentId
     └─ [~] .Ref:
         ├─ [-] apiGatewayDeployment716b900b80ef36b0da16a6bee52b86fa1e44ef1c
         └─ [+] apiGatewayDeploymented7bdda9c3cd290bad13d98545f4080d79a5593e

**Comment by alishanP** [comment]
main thing i want to fix and be able to hotswap is my lambda function

**Comment by peterwoodworth** [comment]
Thanks. What did you change to make these changes in the diff appear? Was it just the contents of your bucket, or were there additional changes?

**Comment by alishanP** [comment]
Just the lambda function code

**Comment by peterwoodworth** [comment]
Could you share your stack please?
