### ISSUE TITLE
DatabaseCluster: writers and readers not taking publiclyAccessible flag

### ISSUE THREAD

**Issue by mdesousa** [aws/aws-cdk#26077]
### Describe the bug

We are defining an Aurora Postgres Serverless V2 cluster as follows:
```
    const cluster = new DatabaseCluster(this, `${id}-serverless-db`, {
      engine: DatabaseClusterEngine.auroraPostgres({
        version: AuroraPostgresEngineVersion.VER_15_2,
      }),
      credentials: Credentials.fromGeneratedSecret("serverless"),
      vpc,
      securityGroups: [dbSecurityGroup],
      vpcSubnets: vpc.selectSubnets({ subnetType: SubnetType.PUBLIC }),
      writer: ClusterInstance.serverlessV2(`${id}-serverless-writer`, {
        publiclyAccessible: true,
      }),
      readers: [
        ClusterInstance.serverlessV2(`${id}-serverless-reader`, {
          publiclyAccessible: true,
          scaleWithWriter: true,
        }),
      ],
    });
```

however, the new writer and reader instances show in the console with "Publicly Accessible: No", and they are not reachable

### Expected Behavior

Configuring publiclyAccessible: true should set the expected accessibility value, and the database should be reachable

### Current Behavior

the new writer and reader instances show in the console with "Publicly Accessible: No", and they are not reachable

### Reproduction Steps

Use the cdk to deploy as shown in the snippet

### CDK CLI Version

2.83.1

### Node.js Version

18.15.0

### OS

macOS

### Language

Typescript

### Language Version

TypeScript 5.1.3

**Comment by pahud** [comment]
According to this logic:

https://github.com/aws/aws-cdk/blob/a79794e3f2609e6efa5cf659eec039964a8ad61c/packages/aws-cdk-lib/aws-rds/lib/aurora-cluster-instance.ts#L447

I guess you should use `subnetSelection` for vpcSubnets instead.

```ts
vpcSubnets: { subnetType: ec2.SubnetType.PUBLIC },
```

It works for me:

% npx cdk synth | grep PubliclyAccessible
      PubliclyAccessible: true
      PubliclyAccessible: true
