### ISSUE TITLE
pipelines: Stage can't deploy an existing stack bound to another scope

### ISSUE THREAD

**Issue by justinwiley** [aws/aws-cdk#26074]
### Describe the bug

I have an existing application, with a stack called 'ExampleStack' that I have been deploying via `cdk deploy ExampleStack`.  It's bound to the scope of the app:

```
const app = new App();
const exampleStack = new ExampleStack(app, 'ExampleStack', props); 
```

I want to set up a new code pipeline, using CDK Pipeline to deploy ExampleStack, [per AWS recommended best practices](https://docs.aws.amazon.com/cdk/v2/guide/best-practices.html).  

However, when I move the example stack into a stage:

```
class ExampleStage extends Stage {
  constructor(scope: Construct, id: string, props: StageProps) {
    super(scope, id, props);

    new ExampleStack(this, 'ExampleStack', props);  // example stack duplicate created
  }
}
```

...the logical id of the stack changes, since it's now in the scope of the Stage, not the app, meaning an entirely new stack with duplicated resources is created which is not the desired behavior.  

If I use the app in the stage:

```
class ExampleStage extends Stage {
  constructor(scope: Construct, id: string, props: StageProps) {
    super(scope, id, props);

    new ExampleStack(app, 'ExampleStack', props); // synth fails
  }
}
```

...it fails during synthesis time with:
> The given Stage construct ('Example') should contain at least one Stack.

### Expected Behavior

A convenient and documented way of deploying existing stacks in stages without having to recreate the or import their resources into a new stack.

### Current Behavior

Stacks are recreated when moved into stages, or blueprint errors are thrown.

### Reproduction Steps

See above.

### Possible Solution

Update the stage synth method to [allow a scope](https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/core/lib/stage.ts#L213) to be passed in, and reference it during synthesis:

```
  interface StageSynthesisOptions = {
    ...
    synthesisScope: App|Stage
  }

  public synth(options: StageSynthesisOptions = { }): cxapi.CloudAssembly {
    if (!this.assembly || options.force) {
      this.assembly = synthesize(options.synthesisScope || this, {
        skipValidation: options.skipValidation,
        validateOnSynthesis: options.validateOnSynthesis,
      });
    }

    return this.assembly;
  }
```

...and updating what invokes snyth to pass on the new argument as well.

### CDK CLI Version

2.83.0 (build 0fd7f2b)

### Node.js Version

18

### OS

mac

### Language

Typescript

**Comment by peterwoodworth** [comment]
Did you try [supplying the stackName directly](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.Stack.html#stackname)?
