### ISSUE TITLE
apprunner: Allow `instanceRole` to be obtained from `Service` instances.

### ISSUE THREAD

**Issue by kt-hr** [aws/aws-cdk#26089]
### Describe the feature

Currently, `instanceRole` can only be set from the constructor.
If it is possible to retrieve it even after initialization like [`obtainExecutionRole`](https://github.com/aws/aws-cdk/blob/v2.85.0/packages/aws-cdk-lib/aws-ecs/lib/base/task-definition.ts#L704) in `TaskDefinition` of ECS, it would be useful to be able to grant privileges with the `grant` method.

### Use Case

Use as follows:

```typescript
declare const bucket: IBucket;

const service = new apprunner.Service(this, 'Service', {
    source: apprunner.Source.fromEcrPublic({
        imageConfiguration: { port: 8000 },
        imageIdentifier: 'public.ecr.aws/aws-containers/hello-app-runner:latest',
    }),
});

bucket.grantRead(service.obtainInstanceRole());
```

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.85.0

### Environment details (OS name and version, etc.)

N/A

**Comment by pahud** [comment]
Yeah maybe we can just expose the [instanceRole](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apprunner-service-instanceconfiguration.html#cfn-apprunner-service-instanceconfiguration-instancerolearn) to the surface and simply

```ts
bucket.grantRead(service.instanceRole);
```
