### ISSUE TITLE
 aws_rds: add support for RotateImmediatelyOnUpdate to secret rotation

### ISSUE THREAD

**Issue by rittneje** [aws/aws-cdk#26099]
### Describe the feature

Reopening #25365 because the feature request was not actually completed.

In CloudFormation, AWS::SecretsManager::RotationSchedule contains an optional property RotateImmediatelyOnUpdate, which controls whether the secret gets rotated as part of the stack update.

As of #25652, this property can also be set during _creation_ of `aws_secretsmanager.RotationSchedule`, but this alone is not sufficient, because there is no way to set this property via `aws_rds.DatabaseCluster.add_rotation_single_user`.

Add an optional parameter to `add_rotation_single_user` to control this property. Probably should be added to `add_rotation_multi_user` as well.

cc @colifran @pahud 

### Use Case

We don't want the secret to rotate immediately.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.85.0

### Environment details (OS name and version, etc.)

Alpine 3.18

**Comment by pahud** [comment]
Yes I guess we probably should expose this option in `RotationSingleUserOptions` for [addRotationSingleUser](https://github.com/aws/aws-cdk/blob/341de48e3637953514a009715dfdeeb061aad929/packages/aws-cdk-lib/aws-rds/lib/instance.ts#L1031) and pass all the way to [SecretRotation](https://github.com/aws/aws-cdk/blob/341de48e3637953514a009715dfdeeb061aad929/packages/aws-cdk-lib/aws-rds/lib/instance.ts#L1042) for addRotationSchedule [here](https://github.com/aws/aws-cdk/blob/341de48e3637953514a009715dfdeeb061aad929/packages/aws-cdk-lib/aws-secretsmanager/lib/secret-rotation.ts#L342C18-L342C37).
