### ISSUE TITLE
route53: " not escaped correctly

### ISSUE THREAD

**Issue by dbartholomae** [aws/aws-cdk#26104]
### Describe the bug

Hi there!

```
    new TxtRecord(this, "TxtRecord", {
      recordName: "xxx.example.com",
      values: [
        'a""b',
      ],
      zone,
    });
```

### Expected Behavior

This should generate a text record with `a""b`

### Current Behavior

It creates `a\"\"b` instead.

### Reproduction Steps

See example

### CDK CLI Version

2.72.1

### Node.js Version

16.14.2

### OS

Mac

### Language

Typescript

**Comment by stefanfreitag** [comment]
Hi @dbartholomae ,

I have seen this behavior also when creating a TXT record in the AWS Management Console itself.
The double quotes are escaped in the way you described: a""b -> a\\"\\"b,

The latter seems to be in line with the Route53 documentation available [here](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/ResourceRecordTypes.html#TXTformat-special-characters). There is an information about using double quotes:

> To include a quotation mark (") in a string, put a backslash (\\) character before the quotation mark: \\".

An example is also provided

> "This string includes \"quotation marks\"

Hope this helps a bit.

**Comment by peterwoodworth** [comment]
We seem to do this intentionally

https://github.com/aws/aws-cdk/blob/9752ed225c82982d8b443f7c6a47f47979458217/packages/%40aws-cdk/aws-route53/lib/record-set.ts#L336-L364

Thanks for the additional context @stefanfreitag. @dbartholomae is there a specific value you're trying to provide that doesn't want to have the backslash?

**Comment by dbartholomae** [comment]
Thanks! I'm currently transferring an existing Hosted Zone to CDK and compare the records with help of `aws route53 list-resource-record-sets`. The specific record that I can't seem to match exactly is a verification record from an external provider and I will reach out to them to understand whether the quote is intentional, but given that the current version works, I'm hesitant to just change it to a version with backslash.
Do you know if there is a workaround to manually set the value to include the quotation mark?

**Comment by dbartholomae** [comment]
Thanks! The difference came because the record was larger than maximum length and CDK split it at a different point than the previous setup. Since this doesn't have an effect on the actual record, the current behavior should be fine except for very weird special cases.
