### ISSUE TITLE
lambda: Updating The Lambda Architecture Properties with toString() methods

### ISSUE THREAD

**Issue by lukey-aleios** [aws/aws-cdk#26117]
### Describe the feature

Updating The Lambda Properties with toString() methods

### Use Case

We want to use effective error throwing using config properties, but they require a lot of code that could be decluttered if the properties have a toString method consistently (like there is on Runtime)

### Proposed Solution

Add toString() methods to the Lambda Props

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.69.0

### Environment details (OS name and version, etc.)

macOS Ventura -  Version 13.3.1 (22E261)

**Comment by pahud** [comment]
It's unclear to me about the advantages.

Can you share some code snippets to elaborate a little more on that?

**Comment by lukey-aleios** [comment]
Hey Pahud!

We're building a wrapper around constructs (in this instance Lambda) and want to throw an error to tell what particular property is incorrect. Say I have this _allowedConfig_ (the acceptable values for certain fields)
`
export const allowedConfig = {
  runtime: [Runtime.NODEJS_18_X],
  architecture: [Architecture.ARM_64],
  tracing: [Tracing.ACTIVE] as const,
  retryAttempts: [0, 1, 2] as const,
};`

But I create this Lamdba:

`new MyLambda(this, 'HelloWorldLambda', {
      functionName: 'hello-world',
      architecture: Architecture.X86_64,
      tracing: Tracing.ACTIVE,
      entry: join(__dirname, 'handler.ts'),
      runtime: Runtime.NODEJS_18_X,
      retryAttempts: 2,
    });
`
And I'm throwing an error that would reference the _allowedConfig_ like this:

`Invalid architecture for Lambda function. Allowed architectures: ${allowedConfig.architecture.join(
    ', ',
  )}`,
  
I only see an [object bject] response in the error string instead of the actual value of allowed architectures. Here's the exact error

`LambdaConfigurationError: Invalid architecture for Lambda function. Allowed architectures: [object Object].`

The addition of a toString() method on the architecture parameter would alleviate this issue, and I was looking at potentially adding this to other fields that may be useful.

**Comment by lukey-aleios** [comment]
I've updated the title to just add a toString for the architecture, so this would require less work and solve my immediate issue
