### ISSUE TITLE
EC2 : Lifecycle Management for Snapshots

### ISSUE THREAD

**Issue by ETisREAL** [aws/aws-cdk#26122]
### Describe the feature

Hi, I believe it  would be very useful to introduce the functionalities of Lifecycle Management in the CDK

### Use Case

Configuring automatic snapshots for Volumes and/or Instances from the CDK

### Proposed Solution

Implementing it directly in the Instance class or in the Volume class

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.85.0

### Environment details (OS name and version, etc.)

Linux - Ubuntu 22.04

**Comment by peterwoodworth** [comment]
The only functionality that I can find related to this through CloudFormation is being able to [configure the deletion policy of a Volume as snapshot](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-volume.html). This can be configured through CDK already. Could you elaborate on what kind of lifecycle management you'd like to see?

**Comment by pahud** [comment]
@ETisREAL 

I guess the best solution off the top of my head is using [BackupPlan](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_backup.BackupPlan.html) from AWS Backup to define your plan, target resource and schedule. Is there anything else in your mind?

**Comment by ETisREAL** [comment]
> The only functionality that I can find related to this through CloudFormation is being able to [configure the deletion policy of a Volume as snapshot](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-volume.html). This can be configured through CDK already. Could you elaborate on what kind of lifecycle management you'd like to see?

Thanks for the quick reply and sorry I wasn't clear. What I think would be a very helpful addition would be integrating the Lyfecycle management functionality that are available from the console regarding `Automated snapshots`

**Comment by ETisREAL** [comment]
> @ETisREAL
> 
> I guess the best solution off the top of my head is using [BackupPlan](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_backup.BackupPlan.html) from AWS Backup to define your plan, target resource and schedule. Is there anything else in your mind?

I guess if BackupPlan is an option that would do the job. Thank you @pahud
