### ISSUE TITLE
VPC with VPN throws NullReferenceException

### ISSUE THREAD

**Issue by McDoit** [aws/aws-cdk#2613]
**Describe the bug**
Creating a VPC with a VPN connection throws NullReferenceException

**To Reproduce**
````
new VpcNetwork(this, "office-vpc", new VpcNetworkProps
{
    Cidr = "10.0.0.0/16",
    SubnetConfiguration = new ISubnetConfiguration[]
    {
        new SubnetConfiguration { Name = "Public", CidrMask = 24, SubnetType = SubnetType.Public }
    },
    VpnGateway = true,
    VpnGatewayAsn = 65534 - 1,
    VpnConnections = {
        {
            "office",
            new VpnConnectionOptions
            {
                Asn = 65534 - 2,
                Ip = "127.0.0.1"
            }
        },
    },
    VpnRoutePropagation = new ISubnetSelection[] { new SubnetSelection { SubnetType = SubnetType.Public }  }
});
````
**Expected behavior**
Create a VPC with a VPN

Works when I create a VPC, without the `VpnConnections` property, and create the VPN separately afterwards

**Version:**
 - OS - Win 10
 - Programming Language - C#/dotnet core
 - CDK Version - 0.31

**Comment by jogold** [comment]
Not familiar with C#/dotnet syntax but `VpnConnections` expects an object with keys that are construct id's and values `VpnConnectionOptions`. I think it should be `"office" = new VpnConnectionsOptions...`

**Comment by McDoit** [comment]
> Not familiar with C#/dotnet syntax but `VpnConnections` expects an object with keys that are construct id's and values `VpnConnectionOptions`. I think it should be `"office" = new VpnConnectionsOptions...`

I guess that is what the transformation makes it into
The `VpnConnections` is a `IDictionary<string, IVpnConnectionOptions>` in C#

That is the beauty with a strongly typed language, it tells you how to do things ;)

**Comment by RomainMuller** [comment]
Seems to be the same as #3580

**Comment by McDoit** [comment]
Indeed, that fixed the issue, thanks!
