### ISSUE TITLE
opensearch: add throughput to EbsOptions

### ISSUE THREAD

**Issue by richardwu** [aws/aws-cdk#26137]
### Describe the feature

The `interface EbsOptions` for the `opensearchservices` CDK construct is missing a provisioned `throughput` option for eg gp3 instance types.

`iops` is there, but not `throughput` (which can be configured in the web console.

### Use Case

To configure provisioned `throughput` in CDK.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.83.1

### Environment details (OS name and version, etc.)

macOS

**Comment by pahud** [comment]
Yes we can add this in the EbsOptions interface:

https://github.com/aws/aws-cdk/blob/0e251e68bad90b2dd7cb3ef48dfe025695e4ab64/packages/aws-cdk-lib/aws-opensearchservice/lib/domain.ts#L113-L149

Making this a p2 feature request and we welcome community pull requests for this.
