### ISSUE TITLE
aws-cdk-lib/aws-ecs-patterns: setting maxHealthyPercent incorrectly causes stack to fail to deploy

### ISSUE THREAD

**Issue by cloventt** [aws/aws-cdk#26158]
### Describe the bug

Setting the `maxHealthyPercent` on an `ApplicationLoadBalancedFargateService` to an invalid value does not raise a synth-time error, but it generates invalid CFN templates.

### Expected Behavior

Setting the `maxHealthyPercent` on an `ApplicationLoadBalancedFargateService` to a value such as 0.5 should trigger a compile-time error.

### Current Behavior

The invalid config is synthed without raising any warnings and results in the stack failing to apply.

### Reproduction Steps

Setting the `maxHealthyPercent` on an `ApplicationLoadBalancedFargateService` to a value such as 0.5.

### Possible Solution

Throw an exception at synth-time if `maxHealthyPercent` is not a whole integer between 0 and 100 inclusive.

### CDK CLI Version

2.79.1

### Node.js Version

19.1.0

### OS

Linux

### Language

Typescript

**Comment by peterwoodworth** [comment]
> Throw an exception at synth-time if maxHealthyPercent is not a whole integer between 0 and 100 inclusive.

I can't find anywhere in the documentation what the acceptable range of values is - but it can certainly be above 100 [according to the docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-service-deploymentconfiguration.html#cfn-ecs-service-deploymentconfiguration-maximumpercent). It does appear to only accept whole numbers though, so we could check for that, and clarify in our docs that a whole number is required
