### ISSUE TITLE
cloudformation.CfnStackSet.ManagedExecutionProperty: extraneous key [active] is not permitted

### ISSUE THREAD

**Issue by savagete2860** [aws/aws-cdk#26152]
### Describe the bug

I am writing CDK in Python 3.10 which deploys a stackset. It seems there is currently a bug in `ManagedExecutionProperty` where you can not specify this property without getting an extraneous key error.

Example construct:
```
class CrenelStackSet(Construct):
    def __init__(self, scope: Construct, id_: str):
        super().__init__(scope, id_)
        self.stack_set = cloudformation.CfnStackSet(
            self, 'stackset',
            permission_model='SERVICE_MANAGED',
            call_as='DELEGATED_ADMIN',
            stack_set_name='test-stack-set,
            managed_execution=cloudformation.CfnStackSet.ManagedExecutionProperty(active=False),
            operation_preferences=cloudformation.CfnStackSet.OperationPreferencesProperty(
                failure_tolerance_percentage=100,
                max_concurrent_percentage=100
            ),
            stack_instances_group=[cloudformation.CfnStackSet.StackInstancesProperty(
                deployment_targets=cloudformation.CfnStackSet.DeploymentTargetsProperty(
                    organizational_unit_ids='ou-xxx',
                ),
                regions=['region']
            )],
            template_body=template
        )
```

This will synth fine but when deploying the following error causes a rollback:
`#/ManagedExecution: extraneous key [active] is not permitted`

The synth'd template looks like:
```
    "ManagedExecution": {
     "active": true
    },
```

I think the `a` in active is supposed to be capitalized like:
```
    "ManagedExecution": {
     "Active": true
    },
``` 

### Expected Behavior

No errors when using ManagedExecutionProperty

### Current Behavior

Using ManagedExecutionProperty will always result in the error: ManagedExecution: extraneous key [active] is not permitted

### Reproduction Steps

Create a stackset using cdk and specify the managed_execution argument.

### Possible Solution

Make the the word `active` synth to `Active` in the template.

### CDK CLI Version

2.85.0

### Node.js Version

18.x.x

### OS

macos

### Language

Python

### Language Version

Python 3.10

**Comment by pahud** [comment]
managed_execution is type `Any`([doc](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk/CfnStackSet.html)) so I believe you will need to pass the JSON like

managed_execution={
    "Active": true
}

**Comment by savagete2860** [comment]
> managed_execution is type `Any`([doc](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk/CfnStackSet.html)) so I believe you will need to pass the JSON like
> 
> ```python
> managed_execution={
>     "Active": true
> }
> ```

Thank you that worked. I was using the example found [here](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk/CfnStackSet.html#aws_cdk.CfnStackSet.ManagedExecutionProperty).

**Comment by peterwoodworth** [comment]
We hope to make those docs accurate in the future by allowing that way of specifying this when an `any` type is expected. Sorry for the confusion
