### ISSUE TITLE
aws-cdk-lib.aws_lambda: AdotLambdaLayerPythonSdkVersion incorrect latest version

### ISSUE THREAD

**Issue by michael-c-hoffman** [aws/aws-cdk#26168]
### Describe the bug

When using the [AdotLambdaLayerPythonSdkVersion.html](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_lambda/AdotLambdaLayerPythonSdkVersion.html) It returns back version 1.13 for latest.  This is an extremely old version and the latest should return back (as of this report) 1.18.  

### Expected Behavior

when calling [AdotLambdaLayerPythonSdkVersion.html](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_lambda/AdotLambdaLayerPythonSdkVersion.html) should be able to specify any valid version or use the LATEST to get the current latest version.
LATEST -> arn:aws:lambda:<region>:901920570463:layer:aws-otel-python-<architecture>-ver-1-18-0:1
V1_18_0 -> arn:aws:lambda:<region>:901920570463:layer:aws-otel-python-<architecture>-ver-1-18-0:1
V1_17_0 -> arn:aws:lambda:<region>:901920570463:layer:aws-otel-python-<architecture>-ver-1-17-0:1
etc

### Current Behavior

Currently the LATEST attribute returns version 1-13-0. There is also also no other versions other than V1_13_0 to specify directly.

### Reproduction Steps

```
>>> import aws_cdk
>>> app = aws_cdk.App()
>>> stack = aws_cdk.Stack(app, "test")
>>> lambda_adot = aws_cdk.aws_lambda.AdotLambdaLayerPythonSdkVersion.LATEST
>>> lambda_adot.layer_arn(stack, aws_cdk.aws_lambda.Architecture.X86_64)
'arn:aws:lambda:${Token[AWS.Region.6]}:901920570463:layer:aws-otel-python-amd64-ver-1-13-0:1'
```

### CDK CLI Version

2.85.0 (build 4e0d726)

### Node.js Version

v18.6.0

### OS

fedora 17

### Language

Python

### Language Version

python 3.10

**Comment by randyridgley** [comment]
I can take this issue

**Comment by pahud** [comment]
Looks like we need fix this

https://github.com/aws/aws-cdk/blob/1ccfc7801d406f6ba9746b7717b468f49b9c00d3/packages/aws-cdk-lib/aws-lambda/lib/adot-layers.ts#L251

Thank you @randyridgley !
