### ISSUE TITLE
iam: role arn parsed incorrectly 

### ISSUE THREAD

**Issue by phch** [aws/aws-cdk#26175]
### Describe the bug

I am using the following code to grant index read/write from an imported role to an imported domain.
The role that I am using follows the structure: `arn:aws:iam::<account>:role/<project-name>/<role-name>`
When I use the following piece of CDK code, it fails saying it cannot find the role called `<project-name>`. 

It seems like it's incorrectly parsing out the role for this policy. 

Example of the Typescript CDK code:
```typescript
const domain = Domain.fromDomainAttributes(node, 'imported-opensearch-domain', this.domainAttributes);
const lambdaFunctionRole = Role.fromRoleArn(node, 'imported-role', node.attrArn);
domain.grantIndexReadWrite('my-index', lambdaFunctionRole);
```

Example of the synthesized CloudFormation:
```json
  "MySamplePolicy": {
   "Type": "AWS::IAM::Policy",
   "Properties": {
    "PolicyDocument": {
     "Statement": [
      {
       "Action": [
        "es:ESHttpDelete",
        "es:ESHttpGet",
        "es:ESHttpHead",
        "es:ESHttpPatch",
        "es:ESHttpPost",
        "es:ESHttpPut"
       ],
       "Effect": "Allow",
       "Resource": [
        "arn:aws:es:us-east-1:<account>:domain/<domain>/<index>",
        "arn:aws:es:us-east-1:<account>:domain/<domain>/<index>/*"
       ]
      }
     ],
     "Version": "2012-10-17"
    },
    "PolicyName": "MySamplePolicy",
    "Roles": [
     {
      "Fn::Select": [
       1,
       {
        "Fn::Split": [
         "/",
         {
          "Fn::Select": [
           5,
           {
            "Fn::Split": [
             ":",
             {
              "Fn::GetAtt": [
               "CustomResourcesRole",
               "Arn"
              ]
             }
            ]
           }
          ]
         }
        ]
       }
      ]
     }
    ]
   }
  },

```

### Expected Behavior

It should grant access correctly for the role to access this domain and be granting access to the full role ARN. 

### Current Behavior

However, due to some behind-the-scenes logic it splits the ARN incorrectly. 

```
Original - arn:aws:iam::<account>:role/<project-name>/<role-name>
Split on ':', Select 5th element - role/<project-name>/<role-name>
Split on '/', Select 1st element - <project-name>
```

### Reproduction Steps

```typescript
const domain = Domain.fromDomainAttributes(node, 'imported-opensearch-domain', this.domainAttributes);
const lambdaFunctionRole = Role.fromRoleArn(node, 'imported-role', node.attrArn);
domain.grantIndexReadWrite('my-index', lambdaFunctionRole);
```

### CDK CLI Version

2.83.1 (build 006b542)

### Node.js Version

v18.0.0

### OS

MacOS 13.4 Ventura

### Language

Typescript

**Comment by peterwoodworth** [comment]
This is what the code is doing, which doesn't look like it accounts for roles with the type of name that you have https://github.com/aws/aws-cdk/blob/dcf53524947ef5bece6b79cb936cacee1ac94483/packages/aws-cdk-lib/aws-iam/lib/role.ts#L255-L263

Thanks for reporting

**Comment by peterwoodworth** [comment]
This is actually documented, and we don't think there's a way to fix it so we'll be closing this out. https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_iam.Role.html#static-fromwbrrolewbrarnscope-id-rolearn-options
