### ISSUE TITLE
cloudwatch: support dashboard variables

### ISSUE THREAD

**Issue by humanzz** [aws/aws-cdk#26200]
### Describe the feature

CloudWatch recently released the new dashboard variables feature which allows parameterizing dashboards with variables to reduce repetition/duplication of dashboards
- https://aws.amazon.com/about-aws/whats-new/2023/06/amazon-cloudwatch-dashboard-variables/
- https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch_dashboard_variables.html
- https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/CloudWatch-Dashboard-Body-Structure.html#CloudWatch-Dashboard-Properties-Variables-Structure

### Use Case

This feature would enable retiring near identical/duplicate dashboards which only differ in some parameters and enable consolidating them into one single parameterized dashboard

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.84.0

### Environment details (OS name and version, etc.)

macOS

**Comment by pahud** [comment]
It is unclear to me how it would be created or referenced in cloudformation. Any insight would be welcome and appreciated.

**Comment by Stacy-D** [comment]
@pahud, The dashboard variables when created are part of the json which corresponds to the dashboard body. To get the dashboard variables deployed via cloudformation or via CDK, the dashboard body should follow the following format:

```
{
widgets: [....]
variables: [....] <- new addition to the dashboard json which allow to define the variables. Each variable here is the variable json
}
```

The proposal for this new feature will be as follows: add new `addVariable(variable: IVariable)` method to the cloudwatch.Dashboard which would accept the variables of different types following the common IVariable interface. For the types of the IVariable the following will be available: property and pattern based variables. 

I intent to make a PR to address this feature request and it will be more clear from it on how these variable work.
