### ISSUE TITLE
(cli-lib): cannot load the default bootstrap template

### ISSUE THREAD

**Issue by AntonioAngelino** [aws/aws-cdk#26224]
### Describe the bug

I discovered a bug in the bootstrap command I implemented yesterday. It doesn't work out of the box because it cannot find the default YAML template.

The cli-lib tries to load the bootstrap-template.yaml in `@aws-cdk/cli-lib-alpha/lib/api/bootstrap/bootstrap-template.yaml` instead of `aws-cdk/lib/api/bootstrap/bootstrap-template.yaml`

### Expected Behavior

CDK deploys the default bootstrap stack.

### Current Behavior
The CLI returns the following error:
```
Environment aws://XXXXXXX/us-east-1 failed bootstrapping: [Error: ENOENT: no such file or directory, open 'XXXX/node_modules/@aws-cdk/cli-lib-alpha/lib/api/bootstrap/bootstrap-template.yaml'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'XXXX/node_modules/@aws-cdk/cli-lib-alpha/lib/api/bootstrap/bootstrap-template.yaml'
}
```

### Reproduction Steps

Follow the CLI lib documentation to create an instance of the AwsCdkCli and then invoke the `cli.bootstrap();` method.

### Possible Solution

The following line should be edited: https://github.com/aws/aws-cdk/blob/928b64ecbfb68ceaf4e15a5fb434c4b39dc7a4a1/packages/aws-cdk/lib/api/bootstrap/bootstrap-environment.ts#L309

I can open a new PR, but I'm not sure what's the best way of fixing it. Should I change `rootDir()` with something else?

### CDK CLI Version

main branch

### Node.js Version

18

### OS

node:18-alpine

### Language

Typescript

**Comment by mrgrain** [comment]
Reproducing this right now.

**Comment by mrgrain** [comment]
Confirmed. This is a bundling issue and we need to copy over `bootstrap-template.yaml` during bundling.
