### ISSUE TITLE
EC2 Instance Connect Endpoint: new connection method

### ISSUE THREAD

**Issue by khaitranhq** [aws/aws-cdk#26226]
### Describe the feature

Please implement the new feature that AWS has just introduced: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Connect-using-EC2-Instance-Connect-Endpoint.html.

### Use Case

I see that this feature is very useful so so I hope that there should be a way to create EIC Endpoints programmatically.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.50.0

### Environment details (OS name and version, etc.)

Debian 10

**Comment by peterwoodworth** [comment]
Is this [supported by CloudFormation yet?](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcendpoint.html) We will depend on CloudFormation support first

**Comment by awsdataarchitect** [comment]
Additionally, instance connect endpoint is not working on an instance running on a dedicated host. it works on other ec2 which is not on dedicated host and using same eic endpoint in same subnet. please advice

just hangs here on websocket
Websocket Closure Reason: Unable to connect to target
ssh_exchange_identification: Connection closed by remote host

debug---

OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2
debug1: Reading configuration data /.ssh/config
debug1: Executing proxy command: exec aws ec2-instance-connect open-tunnel --instance-id "" --private-ip-address 10.0.0.xx --remote-port 22 --instance-connect-endpoint-id eice --instance-connect-endpoint-dns-name eice-.ec2-instance-connect-endpoint.us-east-1.amazonaws.com
debug1: identity file C:\\\private-key type -1
debug1: identity file C:\\\private-key-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_for_Windows_8.1

**Comment by neilferreira** [comment]
It looks like support for this exists on CloudFormation now https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-instanceconnectendpoint.html

**Comment by badmintoncryer** [comment]
> It looks like support for this exists on CloudFormation now https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-instanceconnectendpoint.html

Thanks!
For reference, here is the L1 Construct document on CDK.
https://github.com/aws/aws-cdk/issues/26226#issuecomment-1702271414

**Comment by lart2150** [comment]
Looks like it was added in 2.97.0!

**Comment by badmintoncryer** [comment]
You can use [the EIC Endpoint L2 construct](https://github.com/open-constructs/aws-cdk-library/tree/main/src/aws-ec2#ec2-instance-connect-endpoint-cdk-construct) at [open-constructs/aws-cdk](https://github.com/open-constructs/aws-cdk-library) which is a community driven CDK construct library.

It is more usuful than L1.
