### ISSUE TITLE
(aws-apprunner-alpha): serviceName property being ignored 

### ISSUE THREAD

**Issue by roketworks** [aws/aws-cdk#26237]
### Describe the bug

When creating an AppRunner service using the `Service` construct the `serviceName` property is ignored and a generated service name is used. 

### Expected Behavior

The `serviceName` property gets populated into the Cfn resource in the template

### Current Behavior

The CloudFormation templated generated by `cdk synth` is missing the `serviceName` property. 

### Reproduction Steps

```typescript
const repo = ecr.Repository.fromRepositoryName(this, 'repo', 'app')

new apprunner.Service(this, 'Service', {
    serviceName: 'app',
    cpu: apprunner.Cpu.QUARTER_VCPU,
    memory: apprunner.Memory.HALF_GB,
    source: apprunner.Source.fromEcr({
      repository: repo,
      imageConfiguration: { port: 80 },
    })
  })
```

### Possible Solution

https://github.com/aws/aws-cdk/blob/41cb2883e637a429c9eeb30c48544b69dbc7b065/packages/%40aws-cdk/aws-apprunner-alpha/lib/service.ts#L1075

The property is not used as an input into the L1 construct

### CDK CLI Version

2.86.0

### Framework Version

2.86.

### Node.js Version

19

### OS

MacOS

### Language

Typescript

### Other information

https://github.com/aws/aws-cdk/issues/23351#issuecomment-1443852119 - referenced in this issue

**Comment by roketworks** [comment]
https://github.com/aws/aws-cdk/issues/23351#issuecomment-1443852119 - issue referenced here

**Comment by peterwoodworth** [comment]
Would be an easy fix, feel free to submit a PR

**Comment by roketworks** [comment]
PR opened here #26238
