### ISSUE TITLE
aws_rds (Return all instance identifiers)

### ISSUE THREAD

**Issue by amscheaws** [aws/aws-cdk#26249]
### Describe the feature

Be able to return all DB Instance Identifiers when the following property is called.
```
const cluster = new rds.DatabaseCluster(this, 'Database', { ... });
const identifiers = cluster.instanceIdentifiers;
```
It only returns the reader replicas' identifiers currently.

### Use Case

The SSL/TSL `rds-ca-2019` CA is expiring on Aug 22, 2024. I need to update the Instances' CA identifiers to `rds-ca-rsa2048-g1`.

I had a success using `CfnDbInstance` class along with the Instance Identifier to achieve this through following code.

```csharp
var instanceId = 1;
foreach (string identifier in instanceIdentifiers)
{
    var id = $"db-instance-{instanceId}";
    var cfnDbInstance = new CfnDbInstance(this, id, new CfnDbInstanceProps
    {
        DbInstanceIdentifier = identifier,
        CaCertificationIdentifier = "rds-ca-rsa2048-g1",
    };
    instanceId++;
}
```

### Proposed Solution

Create new property `writerInstanceIdentifiers` and `readerInstanceIdentifiers` and deprecating the existing one.

### Other Information

Alternatively I tried using property `instanceIdentifierBase` to pre-define the instance identifier. But I didn't see the identifier value in CloudFormation after synth.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.86.0

### Environment details (OS name and version, etc.)

Windows Subsystem Linux (Ubuntu) 4.4.0-19041-Microsoft

**Comment by peterwoodworth** [comment]
[This issue](https://github.com/aws/aws-cdk/issues/25947) is already tracking this and there's a PR up for it (which may end up getting closed if we don't hear from the submitter soon). Feel free to give your opinion about creating separate properties in the linked issue or associated PR
