### ISSUE TITLE
cloudwatch: allow configuring period on SingleValueWidget

### ISSUE THREAD

**Issue by humanzz** [aws/aws-cdk#26259]
### Describe the feature

SingleValue widget supports setting a `period` parameter as can be tested/verified via CloudWatch console.

The `SingleValueWidget` class and its props, do not expose a `period` prop.

### Use Case

Being able to customize the period on SingleValueWidget

### Proposed Solution

- `SingleValueWidgetProps` to expose a `period` prop
- `SingleValueWidget.toJson` to render the period correctly

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.85.0

### Environment details (OS name and version, etc.)

macOS

**Comment by khushail** [comment]
Thanks for submitting the feature request and PR @humanzz. It would be reviewed by our team.
