### ISSUE TITLE
(aws_cdk.aws_lakeformation.CfnTagAssociation.ResourceProperty): cannot define catalog

### ISSUE THREAD

**Issue by plazmakeks** [aws/aws-cdk#26261]
### Describe the bug

I'd like to assign LF Tags to some resources and therefor create a 

`aws_lakeformation.CfnTagAssociation` which takes as property `resource` an object of type `aws_lakeformation.CfnTagAssociation.ResourceProperty`. That class has a property named `catalog`, which by documentation is of type `Any` and is by default the aws account id. If i pass in my aws account id as a string i get the error message

`
RuntimeError: Error: Resolution error: Supplied properties not correct for "CfnTagAssociationProps"
  resource: supplied properties not correct for "ResourceProperty"
    catalog: "my_aws_account_id" should be an 'object'.
`

### Expected Behavior

I never did that before, so no idea what is the expected behavior. I guess that object should just be created,.

### Current Behavior

`
RuntimeError: Error: Resolution error: Supplied properties not correct for "CfnTagAssociationProps"
  resource: supplied properties not correct for "ResourceProperty"
    catalog: "my_aws_account_id" should be an 'object'.
`

### Reproduction Steps

Setup that resource property

`
aws_lakeformation.CfnTagAssociation.ResourceProperty(
                catalog=env.account,
                database=aws_lakeformation.CfnTagAssociation.DatabaseResourceProperty(
                    catalog_id=env.account,
                    name="test_database",
                ))
`

### CDK CLI Version

2.86.0 (build 1130fab)

### Node.js Version

v18.16.1

### OS

macos

### Language

Python

### Language Version

Python 3.10.12

**Comment by peterwoodworth** [comment]
It's not accepting a string because as the error message says, it wants an object. However, I have no idea what kind of object structure CloudFormation wants here, because the [API itself doesn't specify how catalog should be used](https://docs.aws.amazon.com/lake-formation/latest/APIReference/API_AddLFTagsToResource.html), it seems unfinished unless I'm missing something.

**Comment by peterwoodworth** [comment]
Try reaching out to the [CloudFormation coverage roadmap](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues), or AWS premium support if you have it to see if they have any insights. CDK is pulling this as properly as it can right now
