### ISSUE TITLE
(aws-ec2): VPC construct - make Internet Gateway creation fully controllable

### ISSUE THREAD

**Issue by Obirah** [aws/aws-cdk#26270]
### Describe the feature

Currently the `Vpc` construct contains logic that determines whether to create an internet gateway [here](https://github.com/aws/aws-cdk/blob/7f31d9fc130002e8010a47d432b1277d76b9d835/packages/aws-cdk-lib/aws-ec2/lib/vpc.ts#L1485).

There should be a feature that allows to control the creation of the internet gateway explicitly.

### Use Case

I'm deploying VPCs in an enterprise environment that requires to create the VPC only with private subnets of the CDK type `PRIVATE_WITH_EGRESS` because our subnets are connected to a transit gateway and hence are not to be considered `PRIVATE_ISOLATED` - this is important for dynamic lookups, e.g. for [EKS](https://github.com/aws/aws-cdk/issues/12171).

My Vpc looks like this:

```
new Vpc(this, "vpc", {
    availabilityZones: this.props.availabilityZones,
    enableDnsHostnames: true,
    enableDnsSupport: true,
    flowLogs: { traffic: this.flowLogOptions },
    ipAddresses: this.ipAddresses,
    natGateways: 0,
    subnetConfiguration: this.subnetConfiguration,
    vpcName: `${this.props.name}`,
    vpnGateway: false,
});
```

The subnet configuration like that:

```
{
    name: this.props.name,
    subnetType: SubnetType.PRIVATE_WITH_EGRESS,
    cidrMask: this.vpcCidrMask + azSubnetNetmask,
    reserved: false,
}
```

This setup results in an unwanted internet gateway being created. Of course, there's a simple workaround that I use:

```
vpc.node.tryRemoveChild('IGW');
vpc.node.tryRemoveChild('VPCGW');
```

### Proposed Solution

There should be a `createInternetGateway` flag in the `VpcProps` that explicitly allows me to disable the creation of an internet gateway that precedes over the above mentioned computation in order to provide a clean convention-over-configuration approach.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.85.0

### Environment details (OS name and version, etc.)

any

**Comment by peterwoodworth** [comment]
Thanks for the FR, makes sense 👍🏻

**Comment by pahud** [comment]
related to https://github.com/aws/aws-cdk-rfcs/issues/507 and https://github.com/aws/aws-cdk/issues/5927

**Comment by peterwoodworth** [comment]
Thanks, I was looking for that pahud
