### ISSUE TITLE
aws_s3: python CfnBucket.EventBridgeConfigurationProperty ignored

### ISSUE THREAD

**Issue by mmaeng** [aws/aws-cdk#26282]
### Describe the bug

Trying to enable event bridge events on an s3 bucket using the L1 CfnBucket.

```
        testbucket = aws_s3.CfnBucket(self, "testingBucketCfnBucket")
        testbucket.EventBridgeConfigurationProperty(
            event_bridge_enabled=True,
        )
```
event_bridge_enabled property looks to be ignored.

cdk synth, generates this snippet
```
  "testingBucketCfnBucket": {
   "Type": "AWS::S3::Bucket",
   "Metadata": {
    "aws:cdk:path": "s3-python/testingBucketCfnBucket"
   }
```

### Expected Behavior

Expecting cdk synth to generate

```
  "testingBucketCfnBucket": {
   "Type": "AWS::S3::Bucket",
   "Metadata": {
    "aws:cdk:path": "s3-python/testingBucketCfnBucket"
   },
   "Properties": {
    "NotificationConfiguration": {
     "EventBridgeConfiguration": {
      "EventBridgeEnabled": true
     }
    }
   }
```

### Current Behavior

```
testbucket = aws_s3.CfnBucket(self, "testingBucketCfnBucket")
testbucket.EventBridgeConfigurationProperty(
    event_bridge_enabled=True,
)
```

event_bridge_enabled setting is ignored.
```
  "testingBucketCfnBucket": {
   "Type": "AWS::S3::Bucket",
   "Metadata": {
    "aws:cdk:path": "s3-python/testingBucketCfnBucket"
   }
```
### Reproduction Steps

```
from aws_cdk import aws_s3

testbucket = aws_s3.CfnBucket(self, "testingBucketCfnBucket")
testbucket.EventBridgeConfigurationProperty(
    event_bridge_enabled=True,
)
```

### Possible Solution

Broke out into an override to add the parameter

```
testbucket.add_property_override("NotificationConfiguration.EventBridgeConfiguration.EventBridgeEnabled", True)
```

### CDK CLI Version

2.87.0

### Node.js Version

18.16.0

### OS

MacOS Ventura 13.4

### Language

Python

### Language Version

Python 3.9.6

**Comment by pahud** [comment]
According to [this](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-notificationconfig.html), EventBridgeConfiguration is under NotificationConfiguration. If you really need to configure that with L1 construct(i.e. CfnBucket) you will need to configure that under NotificationConfiguration. [Check this out](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_s3/CfnBucket.html#notificationconfigurationproperty) for more details about the `NotificationConfigurationProperty`.

Is there any reason you have to use CfnBucket L1 construct like that?

**Comment by mmaeng** [comment]
Using the L2 construct does not fullfill the cloudformation guard rules that Control Tower uses to ensure notifications are set.

**Comment by peterwoodworth** [comment]
```py
from aws_cdk import aws_s3

testbucket = aws_s3.CfnBucket(self, "testingBucketCfnBucket")
testbucket.EventBridgeConfigurationProperty(
    event_bridge_enabled=True,
)
```

This isn't [the right syntax](https://docs.aws.amazon.com/cdk/v2/guide/cfn_layer.html#cfn_layer_resource) if you're trying to modify the property in this manner.

Prefer to use `add_property_override` or setting the property in the constructor, but the following should work using the method you submitted:

```py
from aws_cdk import aws_s3

testbucket = aws_s3.CfnBucket(self, "testingBucketCfnBucket")
testbucket.notification_configuration.event_bridge_configuration.event_bridge_enabled = True
```
