### ISSUE TITLE
Support OIDC Web Identity Token File as a means of picking up credentials

### ISSUE THREAD

**Issue by exussum12** [aws/aws-cdk#26292]
### Describe the bug

When using OIDC  as the following
```
aws configure set web_identity_token_file ${AWS_WEB_IDENTITY_TOKEN_FILE}
```

aws CLI commands work for example `aws sts get-caller-identity`

but CDK does not correctly pick this up from the profile and needs to be manually set as env vars to be picked up

I would have expected the CLI behaviour to match CDK 

### Expected Behavior

when using oidc, aws-cli works, cdk should work in the same way

### Current Behavior

cdk misses the credentials and carries on down the chain

### Reproduction Steps

This can be reproduced on bitbucket (or any provider with OIDC installed)

bitbucket pipeline example
oidc: true
script:
          - export AWS_WEB_IDENTITY_TOKEN_FILE=$(pwd)/web-identity-token
          - echo $BITBUCKET_STEP_OIDC_TOKEN > $AWS_WEB_IDENTITY_TOKEN_FILE
          - chmod 400 ${AWS_WEB_IDENTITY_TOKEN_FILE}
          - aws configure set web_identity_token_file ${AWS_WEB_IDENTITY_TOKEN_FILE}
          - aws sts get-caller-identity
          - npx run cdk deploy

### SDK version used

2.85.0

### Environment details (OS name and version, etc.)

Bitbucket

**Comment by peterwoodworth** [comment]
What error message are you receiving?

**Comment by exussum12** [comment]
@peterwoodworth As its running on bitbucket, they appear to use EC2. The error message is around not being able to get permissions for the account. Changing the env variables  to match
https://github.com/aws/aws-cdk/blob/2462b0b0155a5cf5382b1780e8a8cd40d1206a95/packages/aws-cdk/lib/api/aws-auth/awscli-compatible.ts#L170

Works. but this should be picked up before that point (specifically here https://github.com/aws/aws-cdk/blob/2462b0b0155a5cf5382b1780e8a8cd40d1206a95/packages/aws-cdk/lib/api/aws-auth/awscli-compatible.ts#L52)

**Comment by peterwoodworth** [comment]
The specific error message would be helpful in knowing how / if I'm reproducing the same behavior

**Comment by exussum12** [comment]
```
 ❌ Deployment failed: Error: Need to perform AWS calls for account xxxxxx, but no credentials have been configured
    at SdkProvider.forEnvironment (/opt/atlassian/pipelines/agent/build/node_modules/aws-cdk/lib/index.js:325:46159)
    at async Deployments.cachedSdkForEnvironment (/opt/atlassian/pipelines/agent/build/node_modules/aws-cdk/lib/index.js:415:12792)
    at async Deployments.prepareSdkFor (/opt/atlassian/pipelines/agent/build/node_modules/aws-cdk/lib/index.js:415:7866)
    at async Deployments.isSingleAssetPublished (/opt/atlassian/pipelines/agent/build/node_modules/aws-cdk/lib/index.js:415:11963)
    at async /opt/atlassian/pipelines/agent/build/node_modules/aws-cdk/lib/index.js:415:139187
Need to perform AWS calls for account xxxxxx, but no credentials have been configured
```

With verbose 

```
[00:28:07] Determining if we're on an EC2 instance.
[00:28:07] Looks like an EC2 instance.
[00:28:07] Toolkit stack: CDKToolkit
[00:28:07] Setting "CDK_DEFAULT_REGION" environment variable to ap-southeast-2
[00:28:07] Resolving default credentials
[00:28:07] Notices refreshed
[00:28:07] Failed to store notices in the cache: Error: ENOENT: no such file or directory, open '/root/.cdk/cache/notices.json'
[00:28:15] Unable to determine the default AWS account (TimeoutError): EC2 Metadata roleName request returned error
```


Both of those example above `aws sts get-caller-identity` returns as expected

**Comment by peterwoodworth** [comment]
We don't currently support this - We rely on the SDKs, and they take some different calls to be able to use this feature that I don't think we've set up. This is possible in both JS [v2](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/TokenFileWebIdentityCredentials.html) and [v3](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-aws-sdk-credential-providers/#fromwebtoken) SDKs.

**Comment by exussum12** [comment]
The v3 looks like it supports it

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-aws-sdk-credential-providers/#profile-with-webidentitytokenfile

**Comment by peterwoodworth** [comment]
That's the same page I linked 🙂

**Comment by mpashkovskiy** [comment]
I spent several days fighting with the same issue 🤦‍♂️ .

First of the all AWS_ROLE_ARN should be defined. But that's not all! `AWS_REGION`, it is the lack of `AWS_REGION` that was the main issue for me.

That's a working snippet:

```yaml
image: node:16.3.0
pipelines:
  branches:
    main:
      - step:
          name: Deployment
          oidc: true
          script:
              - export AWS_REGION=...
              - export AWS_ROLE_ARN=....
              - export AWS_WEB_IDENTITY_TOKEN_FILE=$(pwd)/web-identity-token
              - echo $BITBUCKET_STEP_OIDC_TOKEN > $AWS_WEB_IDENTITY_TOKEN_FILE
              - aws sts get-caller-identity
              - npx run cdk deploy
```

You don't even need `chmod` and `aws configure` lines.

**Comment by rumesh-athu** [comment]
> I spent several days fighting with the same issue 🤦‍♂️ .
> 
> First of the all AWS_ROLE_ARN should be defined. But that's not all! `AWS_REGION`, it is the lack of `AWS_REGION` that was the main issue for me.
> 
> That's a working snippet:
> 
> ```yaml
> image: node:16.3.0
> pipelines:
>   branches:
>     main:
>       - step:
>           name: Deployment
>           oidc: true
>           script:
>               - export AWS_REGION=...
>               - export AWS_ROLE_ARN=....
>               - export AWS_WEB_IDENTITY_TOKEN_FILE=$(pwd)/web-identity-token
>               - echo $BITBUCKET_STEP_OIDC_TOKEN > $AWS_WEB_IDENTITY_TOKEN_FILE
>               - aws sts get-caller-identity
>               - npx run cdk deploy
> ```
> 
> You don't even need `chmod` and `aws configure` lines.

Thank you @mpashkovskiy 
Export the `AWS_REGION` was resolved my issue as well

**Comment by TheRealAmazonKendra** [comment]
This support will be added as soon as https://github.com/aws/aws-cdk/pull/31702 is merged.
