### ISSUE TITLE
(aws-apigatewayv2): Validation of apiMappingKey in ApiMappingProps is too strict

### ISSUE THREAD

**Issue by Dzhuneyt** [aws/aws-cdk#26298]
### Describe the bug

Previously resolved at https://github.com/aws/aws-cdk/issues/15948, but I think not fully.

The `new ApiMapping()` [construct](https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/aws-apigatewayv2-alpha/lib/common/api-mapping.ts) is pretty much a wrapper around the [CfnApiMapping](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_apigatewayv2.CfnApiMapping.html#apimappingkey-1) CloudFormation resource, but I think it is opinionated regarding the `apiMappingKey` prop in a way that doesn't make sense.

Both the CloudFormation resource and the AWS Web Based console allow the mapping key to be empty, but the CDK construct `new ApiMapping()` enforces the prop to be an non-empty string, when defined, which stems from [this](https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/aws-apigatewayv2-alpha/lib/common/api-mapping.ts#L101C15-L101C28) check.

This is fine for the most common use case, where there is just API mapping inside a Custom Domain and people never pass the "apiMappingKey" prop, or pass it as undefined, but for more advanced use cases like adding two mappings inside the same Custom Domain, this is actually a blocking limitation. One that just forced me to not use this L1 construct but rather opt for the L1 CloudFormation resources.

### Expected Behavior

People should be able to use the `new ApiMapping()` construct passing an empty apiMappingKey, which matches the CloudFormation L1 resource and the AWS web console experience.

### Current Behavior

People should be able to use multiple `new ApiMapping()` constructs with an empty `apiMappingKey`.

### Reproduction Steps

Using two instances of:
```
new ApiMapping(this, 'ApiMappingOne'...)
new ApiMapping(this, 'ApiMappingTwo'...)
```
while passing an empty string inside the prop "apiMappingKey" for both, leads to a CDK validation error `empty string for api mapping key not allowed`, but the same operation is allowed "manually" through the AWS Web Console or CloudFormation templates.

### Possible Solution

Remove [this](https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/aws-apigatewayv2-alpha/lib/common/api-mapping.ts#L101C15-L101C28) validation.

### CDK CLI Version

2.85.0 (build 4e0d726)

### Node.js Version

v18.16.0

### OS

MacOS

### Language

Typescript

**Comment by pahud** [comment]
CFN allows this prop to be undefined but I am not sure if it allows it to be empty string(''), which is defined but empty string.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigatewayv2-apimapping.html#cfn-apigatewayv2-apimapping-apimappingkey

Are you able to pass empty string '' in the L1 cosntruct with no error? If yes, we probably should remove this restriction.

Can you share your `cdk synth` output for this resource using L1 construct that successfully deploy in CFN?

**Comment by pahud** [comment]
And, can you elaborate more about your use case for "adding two mappings inside the same Custom Domain" that requires the apiMappingKey to be ""(empty string)?

**Comment by Dzhuneyt** [comment]
The use case is, have two domains that map to the same API Gateway's stage, e.g.
customer.prod.something.com
customer.something.com

**Comment by pahud** [comment]
@Dzhuneyt

Thank you for your use case sharing. If cloudformation accepts empty string for `ApiMappingKey`, I don't see any reason we should restrict that in CDK.

Making this a p1 bug.

**Comment by pahud** [comment]
Hi @Dzhuneyt 

I just write a sample cdk app for your use case. I think `apiMappingKey` could be just ignored as below:


```ts
import * as cdk from 'aws-cdk-lib';
import * as apigw from '../../lib';

class DummyRouteIntegration extends apigw.HttpRouteIntegration {
  constructor() {
    super('DummyRouteIntegration');
  }

  public bind(_: apigw.HttpRouteIntegrationBindOptions): apigw.HttpRouteIntegrationConfig {
    return {
      payloadFormatVersion: apigw.PayloadFormatVersion.VERSION_1_0,
      type: apigw.HttpIntegrationType.HTTP_PROXY,
      method: apigw.HttpMethod.ANY,
      uri: 'https://aws.amazon.com/{proxy}',
    };
  }
}

const app = new cdk.App();

const env = { region: process.env.CDK_DEFAULT_REGION, account: process.env.CDK_DEFAULT_ACCOUNT };

const stack = new cdk.Stack(app, 'aws-cdk-aws-apigatewayv2-http-apimapping', { env });

const MOCK_CERT_ARN = 'arn:aws:acm:us-east-1:*****:certificate/********';
const certificate = cdk.aws_certificatemanager.Certificate.fromCertificateArn(stack, 'ImportedCert', MOCK_CERT_ARN);

const domain1 = new apigw.DomainName(stack, 'Domain1', {
  domainName: 'demo1.example.com',
  certificate,
});

const domain2 = new apigw.DomainName(stack, 'Domain2', {
  domainName: 'demo2.example.com',
  certificate,
});

const httpApi = new apigw.HttpApi(stack, 'HttpApi');

httpApi.addRoutes({
  path: '/{proxy+}',
  integration: new DummyRouteIntegration(),
});

new apigw.ApiMapping(stack, 'Mapping1', {
  api: httpApi,
  domainName: domain1,
  // apiMappingKey: 'domain1Mapping',
});

new apigw.ApiMapping(stack, 'Mapping2', {
  api: httpApi,
  domainName: domain2,
  // apiMappingKey: 'domain2Mapping',
});

app.synth();
```

This works for me with multiple custom domain name sharing a single http api with 2 apiMappings.

Does this work for you?
