### ISSUE TITLE
ECS Fargate Service: service not created because of alarm based rollback

### ISSUE THREAD

**Issue by srshkmr** [aws/aws-cdk#26307]
### Describe the bug

During the deployment process with the same code which was working previously is returning the following error.

```
4:43:04 pm | CREATE_FAILED        | AWS::ECS::Service                               | xxxx
Resource handler returned message: "Invalid request provided: CreateService error: Alarm based rollback feature is only supported with ECS deployment controller. Update t
o ECS deployment controller and try again. (Service: AmazonECS; Status Code: 400; Error Code: InvalidParameterException; Request ID: xxx;
Proxy: null)" (RequestToken: xxx, HandlerErrorCode: InvalidRequest)
```

The following is my ECS deployment group
```
const ecsDeploymentGroup = new codeDeploy.EcsDeploymentGroup(this, 'ecsDeploymentGroup', {
      application: ecsApplication,
      deploymentGroupName: props.ECSTaskFamilyName,
      deploymentConfig,
      alarms: ecsServiceAlarms.alarms,
      service: ecsBlueGreenService.ecsService,
      blueGreenDeploymentConfig: {
        blueTargetGroup: ecsBlueGreenService.blueTargetGroup,
        greenTargetGroup: ecsBlueGreenService.greenTargetGroup,
        listener: ecsBlueGreenService.albProdListener,
        testListener: ecsBlueGreenService.albHttpsListener,
        terminationWaitTime: Duration.minutes(10),
      },
      autoRollback: {
        stoppedDeployment: true,
      }
    });
```

The application is deployed using Code deploy, So the deployment controller is set as CODE_DEPLOY

```
this.ecsService = new ecs.FargateService(this, 'FargateService', {
      cluster: props.cluster!,
      desiredCount: 1,
      taskDefinition,
      minHealthyPercent: 100,
      maxHealthyPercent: 200,
      enableExecuteCommand: true,
      deploymentController: {
        type: DeploymentControllerType.CODE_DEPLOY
      },
      healthCheckGracePeriod: Duration.seconds(60)
    });

```

### Expected Behavior

ECS Cluster gets deployed successfully

### Current Behavior

ECS creation failed

### Reproduction Steps

Use the code in the bug description 

### CDK CLI Version

2.87.0

### Node.js Version

v18.15.0

### OS

MacOS 14.0

### Language

Typescript

### Language Version

5.1.6

**Comment by peterwoodworth** [comment]
> During the deployment process with the same code which was working previously is returning the following error.

Could you share the difference in output between when this was working and when this was not? (i.e. cdk diff) - Additionally, when did this stop working, which version did you upgrade from to start encountering this error?

**Comment by jiem-ying** [comment]
Hi +1 to this issue. 

Confirmed from ECS side that if using Code_Deploy type, the CreateService API would fail with Validation when "CODE_DEPLOY" and "DeploymentConfiguration.Alarm" combination detected:
{
  ...
  "DeploymentController": {
    "Type": "CODE_DEPLOY"
  },
  ...
  "DeploymentConfiguration": {
    "Alarms": {
      "AlarmNames": [],
      "Enable": "false",
      "Rollback": "false"
    },
    ...
  },
 ...
}
And as ECS is designed that the DeploymentConfiguration.Alarm can only used by default controller AKA "ECS deployment controller". https://docs.aws.amazon.com/AmazonECS/latest/developerguide/deployment-alarm-failure.html

I understand this new change is from this release https://github.com/aws/aws-cdk/pull/25840

Given it is ECS service API limitation, the L2 construct should have a judgement that if "DeploymentController.Type" is "CODE_DEPLOY", do not explicitly specify the DeploymentConfiguration.Alarms.

Currently the workaround is using Escape Hatches then override deletion:
CfnService.addPropertyDeletionOverride('DeploymentConfiguration.Alarms');

Let me know if you need more clarifications.

**Comment by srshkmr** [comment]
> Could you share the difference in output between when this was working and when this was not? (i.e. cdk diff) - Additionally, when did this stop working, which version did you upgrade from to start encountering this error?

I upgraded from 2.81.0 to 2.87.0, That's when this issue started occuring, Weird thing is even after downgrading the CDK version to 2.81 I am getting the same error. It was working fine on Thursday last week

**Comment by tam0ri** [comment]
When deploymentAlarms property is defined explicitly, CDK checks deploymentController is ECS or not.
https://github.com/aws/aws-cdk/blob/9fca7909797e71788b65bd1bf7bd2c0c85a75159/packages/aws-cdk-lib/aws-ecs/lib/base/base-service.ts#L632-L636

On the other hand, currently CDK never validates deploymentController property for the default alarms settings.
https://github.com/aws/aws-cdk/blob/9fca7909797e71788b65bd1bf7bd2c0c85a75159/packages/aws-cdk-lib/aws-ecs/lib/base/base-service.ts#L685-L691

I just submitted PR to fix this.

**Comment by peterwoodworth** [comment]
Thanks a bunch @tam0ri!

**Comment by YikaiHu** [comment]
Hi @tam0ri,

We still face the same issue in cn-north-1 region.

Our CDK version is v2.89.0

```
    const service = new ecs.FargateService(this, `Service`, {
      cluster: ecsCluster,
      desiredCount: 2, // This number must larger than the number of NLB AZs
      taskDefinition: taskDefinition,
      vpcSubnets: {
        subnets: taskSubnets,
      },
      securityGroups: [ecsServiceSG],
      assignPublicIp: false,
      minHealthyPercent: 100,
      maxHealthyPercent: 200,
      propagateTags: ecs.PropagatedTagSource.SERVICE,
      enableECSManagedTags: true,
      enableExecuteCommand: true,
    });
```
