### ISSUE TITLE
aws-ec2: Missing CfnKeyPair

### ISSUE THREAD

**Issue by SeanStockwell** [aws/aws-cdk#26306]
### Describe the bug

I am trying to make use of aws-cdk-lib/aws-ec2 CfnKeyPair, [documented here](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ec2.CfnKeyPair.html)… but I consistently get a “no exported member named ‘CfnKeyPair’” error, and looking at the [source code from the latest release](https://github.com/aws/aws-cdk/releases/tag/v2.85.0), it doesn’t seem to exist there. Am I missing something?

### Expected Behavior

I expected to be able to make use of the CfnKeyPair construct to create EC2 Key Pairs

### Current Behavior

I get an error stating "no exported member named CfnKeyPair"

### Reproduction Steps

import {CfnKeyPair} from 'aws-cdk-lib/aws-ec2'

### CDK CLI Version

2.

### Node.js Version

18.x

### OS

Linux

### Language

Typescript

### Language Version

~4.7.4

**Comment by peterwoodworth** [comment]
The CloudFormation resources are autogenerated, so they won't appear in the source code.

And I'm not seeing any error, this works for me. Try reinstalling your packages
```ts
    new ec2.CfnKeyPair(this, 'adsfasd', {
      keyName: 'adsfasd',
    })
```
