### ISSUE TITLE
aws-cdk: bootstrapping fails due to permissions boundary name not matching the IAM conventions

### ISSUE THREAD

**Issue by przemolb** [aws/aws-cdk#26320]
### Describe the bug

`cdk bootstrap` command doesn't accept IAM policy names with forward slash (/) in it.

### Expected Behavior

cdk should accept IAM name with forward slashes in its name

### Current Behavior

When I try to run `cdk bootstrap` command with permissions boundry with forward slash in its name, cdk fails:
```
cdk bootstrap --custom-permissions-boundary aaa/bbb
Boostrapping environment ...
Trusted accounts deployment ...
Trusted accounts for lookup ...
Using default execution policy of ...

Environment .... failed bootstrapping: Error: The permissions boundary name aaa/bbb does not match the IAM conventions.
   ...
   ...
   at sync exec4 (...node_modules/aws-cdk/lib/index.js:490:52657)
```

### Reproduction Steps

The error and code I refer to runs on companys laptop and I cannot copy/paste full message here.

### CDK CLI Version

2.87.0

### Node.js Version

v18.12.1

### OS

MacOS

### Language

Go

### Language Version

1.20.1

**Comment by peterwoodworth** [comment]
How do you have an IAM policy name with a slash in it?
<img width="411" alt="Screenshot 2023-07-11 at 11 49 20 AM" src="https://github.com/aws/aws-cdk/assets/44349620/ff2b3b40-4afa-4e6c-994e-435baa9b4e25">

The regex we use is the same as described in the [linked documentation](https://docs.aws.amazon.com/IAM/latest/APIReference/API_CreatePolicy.html) https://github.com/aws/aws-cdk/blob/66c0aa1745b65c6019b84bb5543f0e3cf5a85571/packages/aws-cdk/lib/api/bootstrap/bootstrap-environment.ts#L280-L287

**Comment by peterwoodworth** [comment]
If you have slashes, that's probably part of the optional path. You want to supply the friendly name, which is what would appear after the path.

**Comment by peterwoodworth** [comment]
Hmm the place this value ends up is here https://github.com/aws/aws-cdk/blob/66c0aa1745b65c6019b84bb5543f0e3cf5a85571/packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml#L556

If a policy has a path, is that path required when specifying the arn? [The documentation is unclear to me](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_identifiers.html), though specifying the path obviously doesn't hurt. Fixing this should probably only consist of updating the regex and adding/updating tests - feel free to check out our [contributing guide](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) if you'd like to help out 🙂

**Comment by przemolb** [comment]
According to the [linked documentation](https://docs.aws.amazon.com/IAM/latest/APIReference/API_CreatePolicy.html) this parameter
```
... allows ... a string of characters consisting of either a forward slash (/) by itself or a string
that must begin and end with forward slashes ...
```
and the pattern for the path is:
```
((/[A-Za-z0-9\.,\+@=_-]+)*)/
```

**Comment by przemolb** [comment]
```
feel free to check out our [contributing guide](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)
if you'd like to help out slightly_smiling_face
```
I'd love to my unfortunately my contract doesn't allow me to contribute. :disappointed: 
Sad but true.

**Comment by przemolb** [comment]
In this particular code:

        ```
  - Fn::Sub: 'arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/${InputPermissionsBoundary}'
```
what we need to put into `${InputPermissionsBoundary}` is, i.e.,
```
sth/sthelse/anotherthing/anotherthing2/blahblah
```
(of course, the number of forward slashes can vary)

**Comment by przemolb** [comment]
@peterwoodworth 
Once this has passed all the tests, what is the approximate timeline to get this released and available to everyone?

**Comment by peterwoodworth** [comment]
We usually release once a week or so, so once this is merged it will probably take a week at most
