### ISSUE TITLE
aws-stepfunctions-tasks: Tag Batch Jobs

### ISSUE THREAD

**Issue by gael-ft** [aws/aws-cdk#26336]
### Describe the feature

Currently there's no way to tag a Batch job with `BatchSubmitJob` construct properties.
But looks like it's supported using AWS Console.

### Use Case

Categorize / manage resources used, here Batch jobs.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.74.0 (build 70e2a33)

### Environment details (OS name and version, etc.)

MacOS

**Comment by peterwoodworth** [comment]
Thanks for the feature request,

We'll need to add this as a prop, and then pass it in here https://github.com/aws/aws-cdk/blob/9fca7909797e71788b65bd1bf7bd2c0c85a75159/packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/batch/submit-job.ts#L231

I'm marking this as a p2, which means the team won't be able to get to this soon. Check out the [contributing guide](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) if you'd like to help by submitting a pull request for this feature.
