### ISSUE TITLE
aws-cdk-lib/triggers: Confusing/missing explanation on trigger failures

### ISSUE THREAD

**Issue by archevel** [aws/aws-cdk#26341]
### Describe the issue

From the docs about trigger failures:

> If the trigger handler fails (e.g. an exception is raised), the CloudFormation deployment will fail, as if a resource failed to provision.

However, when the `invocationType` in the trigger's props is `triggers.InvocationType.EVENT` a deployment will succeed regardless of if an error is thrown in the handler body. The quoted statement is true if `triggers.InvocationType.REQUEST_RESPONSE` is used however. Since the example code snippet of a trigger uses `triggers.InvocationType.EVENT` it gives the impression that the deployment will fail if an exception is raised in the handler for the event. Perhaps this is an actual bug in this case, but if it works as intended then it would be good to be explicit about the effect of the different `invocationType`s in the documentation.

### Links

[aws-cdk-lib](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.triggers-readme.html#trigger-failures)

**Comment by pahud** [comment]
Yes you are right. We definitely should update the doc. Any interest to submit a PR for this small doc fix?
