### ISSUE TITLE
aws-lambda-event-sources: add filters to kafka event sources

### ISSUE THREAD

**Issue by jdiebold** [aws/aws-cdk#26348]
### Describe the feature

The AWS documentation (https://docs.aws.amazon.com/lambda/latest/dg/invocation-eventfiltering.html#filtering-msk-smak) suggests that event filtering is also possible for MSK or self-managed Kafka.
Yet, the cdk doesn't offer this config for the (Self)ManagedKafkaEventSource construct.

### Use Case

Filter the Kafka events before the lambda is called to reduce the number of lambda calls.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.87.0

### Environment details (OS name and version, etc.)

n/A

**Comment by pahud** [comment]
https://github.com/aws/aws-cdk/blob/a93bc54e8ede3f59bcd3e20efa4808bcbb0fbb9e/packages/aws-cdk-lib/aws-lambda-event-sources/lib/kafka.ts#L117

**Comment by pahud** [comment]
reopening for close by mistake.

Looks like we can add a [filter](https://github.com/aws/aws-cdk/blob/a93bc54e8ede3f59bcd3e20efa4808bcbb0fbb9e/packages/aws-cdk-lib/aws-lambda/lib/event-source-mapping.ts#L252) here:

https://github.com/aws/aws-cdk/blob/a93bc54e8ede3f59bcd3e20efa4808bcbb0fbb9e/packages/aws-cdk-lib/aws-lambda-event-sources/lib/kafka.ts#L129-L137
