### ISSUE TITLE
(aws-iot-actions-alpha): (IotRepublishMqttAction does not allow 'role' in props)

### ISSUE THREAD

**Issue by dmeehan1968** [aws/aws-cdk#26351]
### Describe the bug

The implementation allows for the instance to carry a role, but the role attribute is not on the IotRepublishMqttActionProps.

### Expected Behavior

Role should be permitted on the props

### Current Behavior

Role cannot be specified, unless a type cast is used

### Reproduction Steps

```
const myRole = new Role(this, 'role', { assumedBy: new ServicePrincipal('iot.amazonaws.com' })
new IotRepublishMqttAction('errors', { role: myRole })
```

### Possible Solution

Update types

### CDK CLI Version

2.87.0

### Framework Version

2.87.0-alpha

### Node.js Version

18.8.0

### OS

macOS 13.4.1

### Language

Typescript

### Language Version

4.9.5

**Comment by jumic** [comment]
I can use the following lines without any error messages.
```ts
const myRole = new Role(this, 'role', { assumedBy: new ServicePrincipal('iot.amazonaws.com') })
new IotRepublishMqttAction('errors', { role: myRole })
```

Can you please show / compare your imports and `package.json` file?

I am using these imports:
```ts
import { Role, ServicePrincipal } from 'aws-cdk-lib/aws-iam';
import { IotRepublishMqttAction } from '@aws-cdk/aws-iot-actions-alpha';
```

My `package.json`:
```json
"dependencies": {
  "@aws-cdk/aws-iot-actions-alpha": "^2.87.0-alpha.0",
  "aws-cdk-lib": "2.87.0",
  "constructs": "^10.2.69",
  "source-map-support": "^0.5.21"
}
```

Maybe you are using import `@aws-cdk/aws-iot-actions` from CDK v1. You need to use `@aws-cdk/aws-iot-actions-alpha` for CDK v2.
