### ISSUE TITLE
aws-cdk-lib/aws-rds: please add AuroraPostgresEngineVersion 15.3 / 15_3

### ISSUE THREAD

**Issue by mla-v-office** [aws/aws-cdk#26363]
### Describe the feature

Aurora Postgres 15.3 was just released. Please add the Version to the aws-cdk-lib/aws-rds
https://github.com/aws/aws-cdk/blob/54e589d9bae07248dc42b381f472e4c13876c3d4/packages/aws-cdk-lib/aws-rds/lib/cluster-engine.ts#L714
https://aws.amazon.com/de/about-aws/whats-new/2023/07/amazon-aurora-postgresql-pgvector-vector-storage-similarity-search/

### Use Case

New Version was released and I want to use it.

### Proposed Solution

just add: 
`public static readonly VER_15_3 = AuroraPostgresEngineVersion.of('15.3', '15', { s3Import: true, s3Export: true });`

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.87.0

### Environment details (OS name and version, etc.)

2.87.0

**Comment by pahud** [comment]
Thank you. Are you interested to pick up a PR for this just as https://github.com/aws/aws-cdk/pull/25000 ?

**Comment by mla-v-office** [comment]
> Thank you. Are you interested to pick up a PR for this just as #25000 ?

Sure.

**Comment by nodomain** [comment]
Can you also please add 13.11?

I am using Discourse and therefore are stuck to v13. 
https://aws.amazon.com/de/about-aws/whats-new/2023/07/amazon-aurora-postgresql-pgvector-vector-storage-similarity-search/
