### ISSUE TITLE
ec2: flowLogName property in FlowLog construct does not work

### ISSUE THREAD

**Issue by tam0ri** [aws/aws-cdk#26370]
### Describe the bug

FlowLog L2 construct has flowLogName property.
https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ec2.FlowLog.html

This is only assigned to physicalName here.
https://github.com/aws/aws-cdk/blob/9fca7909797e71788b65bd1bf7bd2c0c85a75159/packages/aws-cdk-lib/aws-ec2/lib/vpc-flow-logs.ts#L722-L724

However, we can't define physical name for `AWS::EC2::FlowLog` resource. The pysical name for VPC Flow Logs is always automatically generated id.

So, currently flowLogName property is meaningless property.

### Expected Behavior

In VPC console, a tag value for Name key is shown in Name column as below. 

![flowlog-console](https://github.com/aws/aws-cdk/assets/7079411/9031a460-9d67-4aea-af9f-68abad7f0c4d)

So, FlowLog L2 construct should add Name tag like VPC or Instance L2 construct.
https://github.com/aws/aws-cdk/blob/9fca7909797e71788b65bd1bf7bd2c0c85a75159/packages/aws-cdk-lib/aws-ec2/lib/vpc.ts#L1450
https://github.com/aws/aws-cdk/blob/9fca7909797e71788b65bd1bf7bd2c0c85a75159/packages/aws-cdk-lib/aws-ec2/lib/instance.ts#L362

### Current Behavior

The value of flowLogName property is never referred in generated CloudFormation template.

### Reproduction Steps

We can reproduce it with the following snippet.

```typescript
    const vpc = ec2.Vpc.fromLookup(this, 'Vpc', {
      isDefault: true,
    });

    new ec2.FlowLog(this, 'FlowLog', {
      flowLogName: 'CustomFlowLogName',
      resourceType: ec2.FlowLogResourceType.fromVpc(vpc),
    });
```

### Possible Solution

Adding Name tag with the value of flowLogName property.

### CDK CLI Version

v2.87.0

### Node.js Version

v18.16.0

### OS

Amazon Linux 2

### Language

Typescript

**Comment by pahud** [comment]
Thank you for your PR.
