### ISSUE TITLE
opensearch: High Level Constructs For OpenSearchOffPeakWindowOptions and Software Update Options Feature

### ISSUE THREAD

**Issue by AmanRajAWS** [aws/aws-cdk#26388]
### Describe the feature

The OpenSearch Team has recently launched OffPeak and Software Update OptionsFeature for OpenSearch Domain. [OffPeakWindowOptionsLink](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/off-peak.html). 
[SoftwareUpdateOptionsLink](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/service-software.html)
According to the CDK docs currently there is no high level CDK construct for these features.
[CDK docs link for OffPeakWindowOptionsProperty](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_opensearchservice.CfnDomain.OffPeakWindowOptionsProperty.html)
[CDK Docs link for  OffPeakWindow](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_opensearchservice.CfnDomain.OffPeakWindowProperty.html)
[CDK Docs link for SoftwareUpdateOptions](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_opensearchservice.CfnDomain.SoftwareUpdateOptionsProperty.html)
[CFN docs link for OffPeakWindow](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-opensearchservice-domain-offpeakwindow.html)
[CFN docs link for OffPeakWindowOptions](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-opensearchservice-domain-offpeakwindowoptions.html)
[CFN docs link for  SoftwareUpdateOptions](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-opensearchservice-domain-softwareupdateoptions.html)

### Use Case

The general recommendation is to use high level constructs and due to lack of High level construct for this feature, the CDK template needs to be migrated to use CFN constructs if there is a need to Create OffPeak window for OpenSearch Domain . This serves as a hinderance to the adoption of the  OffPeak Window and Software Update Options feature for AWS OpenSearch Domains.

### Proposed Solution

Add the OffPeakWindowOptions to the OpenSearch Domain Props(https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_opensearchservice.Domain.html) .
Configuring OffPeakWindowOptions on OpenSearchDomain created using CDK high level constructs should look like
const domain = new Domain(this, 'Domain', {
version: EngineVersion.OPENSEARCH_1_0,

offPeakWindowOptions: {
   enabled: true (possible values: [true,false])
   offPeakWindow: {
    windowStartTime: {
   hours: 4 [possible values from 0 to 60]
  minutes: 4 [possible values from 0 to 60]
 }
 }
},
softwareUpdateOptions : {
 autoSoftwareUpdateEnabled: true (possible values: [true,false])
}
});

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.84.0

### Environment details (OS name and version, etc.)

macOS Ventura 13.4

**Comment by pahud** [comment]
Yes [OffPeakWindowOptions](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-opensearchservice-domain.html#cfn-opensearchservice-domain-offpeakwindowoptions) is an optional prop for domain and we welcome and appreciate any PRs for that.
