### ISSUE TITLE
(Pipeline): The 'account' property must be a concrete value (action: 'StagingDeploy')

### ISSUE THREAD

**Issue by pclowes** [aws/aws-cdk#26409]
### Describe the bug

I have a CDK pipeline that creates creates infrastructure as code via stages. This Infrastructure Pipeline creates a FargateService as well as an ApplicationPipeline for deploying application code to the Fargate service via ECS.

To reference the FargateService in the ApplicationPipepline I import the cluster and the serviceArn of the Fargate service.
This import fails with the error: The 'account' property must be a concrete value'

### Expected Behavior

The CDK docs say you can use either the cluster AND (serviceArn OR serviceName) to lookup a fargate service via `ecs.FargateService.fromFargateServiceAttributes` I would expect both options to work.

### Current Behavior

If a Fargate Service is looked up via `ecs.FargateService.fromFargateServiceAttributes` with cluster AND serviceArn. The Account cannot be inferred and the error is raised.

### Reproduction Steps

Try to import a Fargate Service from another Stack via `ecs.FargateService.fromFargateServiceAttributes` by exporting/importing cluster AND serviceArn.

### Possible Solution

This very similar to: https://github.com/aws/aws-cdk/pull/14224 and https://github.com/aws/aws-cdk/issues/14741
For now I can just use serviceName.

### CDK CLI Version

2.87.0 (build 9fca790)

### Node.js Version

Node.js v18.16.0

### OS

MacOS

### Language

Typescript

**Comment by peterwoodworth** [comment]
I think I understand but could you give reproduction code please? i'm not sure exactly how the pipeline fits into this

**Comment by pclowes** [comment]
Sure, I have a Service in a CDK infrastructure Pipeline stack defined as:
`const fargateService = new ApplicationLoadBalancedFargateService(this, "WebAppFargateService", {
...
})`

And I am exporting its clusterArn and serviceARN as follows:
` new CfnOutput(this, 'FargateClusterArn', {
            value: cluster.clusterArn,
            exportName: `FargateClusterArn`
        });

        new CfnOutput(this, 'FargateServiceArn', {
            value: fargateService.service.serviceArn,
            exportName: `FargateServiceArn`
        });`
        
  And importing it into my CI/CD Pipeline stack for to target for ECS deployment like:
  `const fargateClusterArn = Fn.importValue('FargateClusterArn')
const fargateCluster = ecs.Cluster.fromClusterArn(this, 'StagingFargateCluster', fargateClusterArn)
const fargateServiceArn = Fn.importValue('FargateServiceArn')
const fargateService = ecs.FargateService.fromFargateServiceAttributes(this, 'StagingFargateService', {
    cluster: fargateCluster,
    serviceArn: fargateServiceArn
});
`
When I do that I get the error: "The 'account' property must be a concrete value", when I switch from serviceArn to serviceName it works as expected. The Pipeline is incidental, was just describing the use case.

**Comment by peterwoodworth** [comment]
Just having this snippet won't trigger the error - could you please provide a minimal reproduction which will throw the error?

This is likely occurring because the arn value you're supplying in this case is a [token](https://docs.aws.amazon.com/cdk/v2/guide/tokens.html), which is why it can't parse the account at synth time.
