### ISSUE TITLE
ECS : Allow LoadBalancedFargateService to receive ExecutionRole and TaskRole as property overrides

### ISSUE THREAD

**Issue by DavidChristiansen** [aws/aws-cdk#2640]
I propose we add optional `executionRole?: Role`  and `taskRole?: Role` parameters to https://github.com/awslabs/aws-cdk/blob/master/packages/@aws-cdk/aws-ecs-patterns/lib/fargate/load-balanced-fargate-service.ts#L10

**Comment by pkandasamy91** [comment]
Change has already been made. Closing this issue. Please reopen if you have any questions.
