### ISSUE TITLE
(build error): (npx lerna run build --scope=aws-cdk-lib is failed with heap out of memory)

### ISSUE THREAD

**Issue by bun913** [aws/aws-cdk#26415]
### Describe the issue

First, I executed the following command, referring to the following page, to set up the environment:

`﻿npx lerna run build --scope=aws-cdk-lib`

https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md#building-aws-cdk-lib

However, I encountered the following error:

`﻿FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory`

I resolved this issue by increasing the available memory space by executing the following command:

`﻿export NODE_OPTIONS="--max-old-space-size=8192"`

After that, I ran the command again:

`﻿npx lerna run build --scope=aws-cdk-lib`

## Proposal

I understand that this error is not caused by this repository but rather by the user's environment.

However, I believe that if the build fails, it could hinder the intentions of future contributors.

Would it be possible to add the following statement to CONTRIBUTING.md?

"If you encounter `﻿FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory`, please try running the command with increased memory by using ﻿export NODE_OPTIONS="--max-old-space-size=8192"."

I am also considering how far I should address this issue, so please let me know your opinion whether it is necessary or not if you think it is unnecessary.

### Links

https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md#building-aws-cdk-lib

**Comment by khushail** [comment]
Hi @bun913 , thanks for reaching out. I agree with seeing this issue sometimes, so it would be helpful for the first time contributors to have this added to Contributing guide.

**Comment by bun913** [comment]
@khushail 
Thank you for your response. I will create a pull request for this issue today or tomorrow.
