### ISSUE TITLE
build: switch to Bazel build system and CircleCI

### ISSUE THREAD

**Issue by CaerusKaru** [aws/aws-cdk#2641]
This is an extension of the proposal in #1445. Take a look at how [Angular](https://github.com/angular/angular) has set up their repository. For PRs alone, they distribute many of the tasks thanks to the parallelization afforded by CircleCI and Bazel.

They are able to take advantage of other benefits too, like incremental builds, packaging-level versioning, and workspace support out of the box.

**Comment by eladb** [comment]
Superseded by https://github.com/aws/aws-cdk-rfcs/issues/60
