### ISSUE TITLE
aws-neptune: no CDK for Neptune Serverless

### ISSUE THREAD

**Issue by MieladN** [aws/aws-cdk#26428]
### Describe the feature

On the 26th of October 2022, AWS released [serverless Neptune](https://aws.amazon.com/about-aws/whats-new/2022/10/amazon-neptune-serverless-generally-available/) (a graph database). About 2 months ago, AWS released [Cloudformation support](https://aws.amazon.com/about-aws/whats-new/2023/05/amazon-neptune-cloudformation-serverless/) for serverless Neptune, which means now serverless Neptune can be made with Cloudformation files.

It would be pretty useful to create constructs for serverless Neptune. Currently these do not exist.

### Use Case

At present, you can only choose instances when building Neptune with CDK. There is no ability to go serverless. Neptune is pretty costly, so even at its smallest size, it costs a pretty penny. Having the ability to write the configuration for serverless Neptune in CDK would be a lifesaver (& prevent us from constantly using the GUI). The benefits of IaC are obviously innumerable.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.87.0

### Environment details (OS name and version, etc.)

Windows/Mac/Linux

**Comment by khushail** [comment]
Hi @MieladN , thanks for reaching out.
CDK provides construct for [Neptune](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-neptune-alpha-readme.html).  Let me know if you are asking for something else and this is not helpful.

**Comment by khushail** [comment]
Hi @MieladN , thanks for coming up with [this](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-neptune-alpha-readme.html#starting-a-neptune-database) feature in CDK.
