### ISSUE TITLE
(aws-iot): Support for Attaching iot policy to Thing Groups

### ISSUE THREAD

**Issue by raziza** [aws/aws-cdk#26425]
### Describe the feature

Support for Attaching iot policy to Thing Groups

### Use Case

In order to avoid using custom resources/lamda/policies and relevant problems - and working pure with CDK objects

### Proposed Solution

Implement APIs to create the aforementioned resources

For ex.

`CfnAttachPolicy.builder.create(this, "id").policyName("policyName").thingGroupName("groupName").build();`

or even adding support to the existing `CfnPolicyPrincipalAttachment` object which allows to send group arn as well

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.87.0

### Environment details (OS name and version, etc.)

Windows 10, Java SDK

**Comment by khushail** [comment]
Hi @raziza , thanks for reaching out. I see you have opened similar issue in the past, linked above. So I am makring this as P2 and redirecting to cfn team for further traction
