### ISSUE TITLE
(custom-resources): Provider function is throwing "Error: return values from user-handlers must be JSON objects. got: ""

### ISSUE THREAD

**Issue by mrlikl** [aws/aws-cdk#26429]
### Describe the bug

Hello team, 

I am seeing the error `Error: return values from user-handlers must be JSON objects. got: ""` recently while using the `Provider` construct of `aws-cdk-lib/custom-resources`. Checking the cloudwatch logs of the request, I see that this is the return value sent back from the oneventhandler lambda fn. 

```
{
    $metadata: {
      httpStatusCode: 200,
      requestId: 'xxxx',
      attempts: 1,
      totalRetryDelay: 0
    },
    ExecutedVersion: '$LATEST',
    Payload: {},
    StatusCode: 200
  }
```

I see that there was a change recently in [parseJsonPayload](https://github.com/aws/aws-cdk/blob/399b6bbdbfbf6440145e6d78e18898aae6261702/packages/aws-cdk-lib/custom-resources/lib/provider-framework/runtime/framework.ts#L149C10-L149C26) function from `const text = payload.toString();` to `let text = new TextDecoder().decode(Buffer.from(payload));`.

### Expected Behavior

Provider fn to return empty values/success

### Current Behavior

Provider function is throwing "Error: return values from user-handlers must be JSON objects. got: ""

### Reproduction Steps

Not sure of the reproduction steps here. Although I do not see any return from the event lambda. 
This works fine if the return logged is "" like 
```
{
    $metadata: {
      httpStatusCode: 200,
      requestId: 'xxxx',
      attempts: 1,
      totalRetryDelay: 0
    },
    ExecutedVersion: '$LATEST',
    Payload: "",
    StatusCode: 200
  }
```

### CDK CLI Version

2.87.0

### Node.js Version

18.16

### OS

mac

### Language

Typescript

**Comment by peterwoodworth** [comment]
Logging the return as `""` probably works because that is a falsy value, as opposed to `{}`. Looks like this was an edge case that went unaccounted for. Does this break you and prevent you from being able to properly upgrade without making changes @mrlikl?

**Comment by mrlikl** [comment]
I do not have direct access to the onevent lambda code. The payload data is from the provider lambda's logs.

**Comment by jalvinake** [comment]
I am also having this exact error. I am unable to upgrade our production system due to it.

**Comment by MrArnoldPalmer** [comment]
@jalvinake @mrlikl can you provide an example of what your handler is returning (I know you said you don't have access to the handler code is it a CR in aws-cdk-lib?)? I'm pretty sure we can just change the logic to something similar to the change we made in `AwsCustomResource`, but I want to make sure I have a good test here.

**Comment by rtfinspace** [comment]
we recently migrated to cdkv2, provider lambda errored with this return response object .
{
    $metadata: {
      httpStatusCode: 200,
      requestId: 'xxxx',
      attempts: 1,
      totalRetryDelay: 0
    },
    ExecutedVersion: '$LATEST',
    Payload: {},
    StatusCode: 200
  }

Provider lambda used nodejs18 as runtime. Having issues with specifically with this. 
There are other packages which exact same implemenation, where provider lambda doesnt have any issues, uses nodejs14 as runtime. Not sure if error is because of nodejs18 ?
