### ISSUE TITLE
(step-functions): (The state machine IAM Role is not authorized to access the Log Destination)

### ISSUE THREAD

**Issue by pete-mcneill** [aws/aws-cdk#26432]
### Describe the bug

Using a custom log group for a while to prefix "vendedlogs" to the log group name for our State Machines.

This has worked previously but this week it has started throwing an error.

### Expected Behavior

`new sfn.StateMachine(this, "TechnicalData", {
      stateMachineName:
        Stack.of(scope).stackName.toLowerCase() + "_TechnicalData",
      definition: technicalData,
      tracingEnabled: true,
      logs: {
        destination: new LogGroup(this, "TechnicalDataLogGroup",
        {
          logGroupName: '/aws/vendedlogs/states/${Stack.of(
            this
          ).stackName.toLowerCase()}_TechnicalData',
        }),
        level: LogLevel.ALL,
      },
    });
`

Using this code will generate a State Machine with Log Group.

### Current Behavior

Deployment failed with an error:

Resource handler returned message: "The state machine IAM Role is not authorized to access the Log Destination (Service: AWSStepFunctions; Status Code: 400; Error Code: AccessDeniedException; Request ID: 3dde30f8-e3fe-49a5-a424-14c41192ebb0; Proxy: null)" (RequestToken: 43782337-d13f-cbb3-e093-cfe71ed4bcd9, HandlerErrorCode: AccessDenied)

### Reproduction Steps

Deploy with a log group that has a logGroupName assigned.

### Possible Solution

Tried manually adding the suggested Policy from:
https://docs.aws.amazon.com/step-functions/latest/dg/cw-logs.html#cloudwatch-iam-policy

Had success with this but CDK should already be adding this policy on deploy.

### CDK CLI Version

2.47.0 (build 3528e3d)

### Node.js Version

16

### OS

Linux

### Language

Typescript

**Comment by indrora** [comment]
Does this happen when you create the log group first independently, reference it in the state machine properties, and then explicitly grant permission with [GrantWrite](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_logs.LogGroup.html#grantwbrwritegrantee)?

**Comment by pete-mcneill** [comment]
Adding grant write has fixed it. Looking at what that adds to the IAM role seems to be 2 permissions for creating and putting to a log stream. The link for the correct IAM permissions on AWS docs indicate those should be included along with the others that CDK by default create.

I'll look to create a PR to update the permissions to match the AWS docs

**Comment by indrora** [comment]
Given that `grantWrite` is the standard path that should be taken (the CDK doesn't usually hand out permissions, instead going for the `grantX` pattern), I'm closing this.
