### ISSUE TITLE
aws-ecs: Incorrect Partition Names For Disabling ECS Alarms

### ISSUE THREAD

**Issue by bmoor-amzn** [aws/aws-cdk#26456]
### Describe the bug

A recent change was released to add support for ECS alarms.  The partitions listed [here](https://github.com/aws/aws-cdk/blob/v2.88.0/packages/aws-cdk-lib/aws-ecs/lib/base/base-service.ts#L1370) are NOT the correct partition names.

They should be `aws-iso` and `aws-iso-b`

### Expected Behavior

No Alarm property should be added on a service in `aws-iso` and `aws-iso-b` regions.

### Current Behavior

The Alarm property is added to a service in `aws-iso` and `aws-iso-b` regions.  These cause cloud formation deployments to fail.

### Reproduction Steps

1. Create an ECS service for a stack in `us-isob-east-1`
2. Observe Alarm property exists

### CDK CLI Version

2.87.0 (build 9fca790)

### Node.js Version

18

### OS

linux

### Language

Java

**Comment by peterwoodworth** [comment]
Thanks for reporting, and thanks @bvtujo for getting a PR up so quickly
