### ISSUE TITLE
aws-glue-alpha: Undefined behavior of Code.fromAsset API

### ISSUE THREAD

**Issue by protyay** [aws/aws-cdk#26469]
### Describe the bug

I'm trying to upload a Glue Job from local Disk. The glue job currently lies in assets folder in the CDK package. I've the following code for creating a glue job out of that script

```
private readonly ASSET_PATH = path.join(__dirname, `/../assets/jobName.scala`);
...
....
....
new glue.Job(this, 'SparkScalaETLJob', {
      executable: glue.JobExecutable.scalaEtl({
        glueVersion: glue.GlueVersion.V3_0,
        script: glue.Code.fromAsset(this.ASSET_PATH),
        className: 'GlueApp',
      }),
      workerType: glue.WorkerType.G_1X,
      workerCount: 10,
      description: 'Glue ETL Job',
      defaultArguments,
    });
```
When i run brazil-build, this is the issue I get

`Error: ENOTDIR: not a directory, lstat '/Volumes/.../src/CDKPackage/dist/lib/assets/ETLJob.scala'`
So, i thought i might have to point to the directory, in which case, I get the following error

`Code path /Volumes/workplace/DeveloperRiskWorkflow/src/DeveloperRiskWorkflowCDK/lib/assets is a directory. Only files are supported`

### Expected Behavior

`Code.fromAsset` must work properly when the Asset Path points to a fileName, because the [source code](https://github.com/aws/aws-cdk/blob/v2.88.0/packages/%40aws-cdk/aws-glue-alpha/lib/code.ts#L70) throws an error if the Asset path is a directory.

### Current Behavior

Already mentioned in Bug Section

### Reproduction Steps

Mentioned in the Bug Scenario

### CDK CLI Version

ENOTDIR: not a directory

### Node.js Version

18.16.1

### OS

MacOS 13.3.1

### Language

Typescript

**Comment by peterwoodworth** [comment]
This is working for me:

```ts
    new glue.Job(this, 'SparkScalaETLJob', {
      executable: glue.JobExecutable.scalaEtl({
        glueVersion: glue.GlueVersion.V3_0,
        script: glue.Code.fromAsset('assets/glue/index.js'),
        className: 'GlueApp',
      }),
      workerType: glue.WorkerType.G_1X,
      workerCount: 10,
      description: 'Glue ETL Job',
    });
```

Alternatively:

```ts
    const ASSET_PATH = path.join(__dirname, `../assets/glue/index.js`);

    new glue.Job(this, 'SparkScalaETLJob', {
      executable: glue.JobExecutable.scalaEtl({
        glueVersion: glue.GlueVersion.V3_0,
        script: glue.Code.fromAsset(ASSET_PATH),
        className: 'GlueApp',
      }),
      workerType: glue.WorkerType.G_1X,
      workerCount: 10,
      description: 'Glue ETL Job',
    });
```

It's possible you're running into a problem with the internal tooling, which we can't help with here. Ensure you're specifying the right path, else I assume this is an issue with the internal tooling.

**Comment by protyay** [comment]
Thanks. Found the issue. It was with a local folder.
