### ISSUE TITLE
NodejsFunction: External dependecy bundling not working?

### ISSUE THREAD

**Issue by rupe120** [aws/aws-cdk#26464]
### Describe the bug

I install a module and reference it in `bundling.externalModules[]` and the execution fails with a Module Not Found error

### Expected Behavior

Successfully import external module

### Current Behavior

With `uuid` both installed and referenced in `bundling.externalModules[]`, the following error is produced.

```json
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'uuid'\nRequire stack:\n- /var/task/index.js\n- /var/runtime/index.mjs",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module 'uuid'",
        "Require stack:",
        "- /var/task/index.js",
        "- /var/runtime/index.mjs",
        "    at _loadUserApp (file:///var/runtime/index.mjs:997:17)",
        "    at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1029:21)",
        "    at async start (file:///var/runtime/index.mjs:1192:23)",
        "    at async file:///var/runtime/index.mjs:1198:1"
    ]
}
```

### Reproduction Steps

Deploy the following app and run the Lambda.

https://github.com/rupe120/cdk-typescript-bundling-dependency-test

### Possible Solution

Unknown

### CDK CLI Version

2.88.0

### Node.js Version

v18.16.1

### OS

Windows 11 Enterprise build 22621.1702

### Language

Typescript

### Language Version

Typescript 5.1.6

**Comment by tmokmss** [comment]
You should be able to use [nodeModules](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda_nodejs.BundlingOptions.html#nodemodules) instead of externalModules to make the package available on runtime environment.

**Comment by jsec** [comment]
`externalModules` actually does the opposite of what you're expecting. It's a list of modules that esbuild will _not_ bundle with your function, because they're considered external modules that are already available in the runtime (ie. `@aws-sdk/*`). So in this case, you wouldn't want to add `uuid` to `externalModules`, so that it's available to your lambda's runtime.

**Comment by peterwoodworth** [comment]
Thanks for the help offered, does this help unblock @rupe120?

**Comment by rupe120** [comment]
> Thanks for the help offered, does this help unblock @rupe120?

I haven't tried it yet but I think this will resolve my issue.

I do feel like the description should be updated to reference the difference between the 2 properties.

**Comment by rupe120** [comment]
Yes, not listing the desired module in `externalModules` solved my issue.
