### ISSUE TITLE
(lambda): (CDK lambdas still using node16)

### ISSUE THREAD

**Issue by alexherriott** [aws/aws-cdk#26461]
### Describe the bug

Since https://github.com/aws/aws-cdk/releases/tag/v2.87.0 CDK lambda runtime should be using node 18 runtime.

We are seeing some runtimes still using node 16 e.g. LogRetention lambda. (there may be more)

https://github.com/aws/aws-cdk/blob/v2.87.0/packages/aws-cdk-lib/aws-logs/lib/log-retention.ts

![image](https://github.com/aws/aws-cdk/assets/190514/fedb079f-ee77-44b9-989a-2ad07f9532ee)

it seems to be defaulting to node_16 if a regional Fact is not set – where is this set? I couldn’t see anything in release notes relating to this. is this something AWS configures  so that node 18 is used? Or do we have to do something?

### Expected Behavior

node 18 runtime should be used in *all* CDK generated lambdas 

### Current Behavior

Node 16 is being used in some CDK generated lambdas

### Reproduction Steps

this is autogenerated by CDK

### CDK CLI Version

2.87.0

### Framework Version

2.87.0

### Node.js Version

16

### OS

Ubuntu standard:6.0

### Language

Typescript

**Comment by alexherriott** [comment]
Hi

Any ETA on this?

Thanks

**Comment by lkoniecz** [comment]
@alexherriott 

on 2.94
cdk diff does not show any differences
cdk deploy --all does not roll out handlers, they are still on node 14

**Comment by mrgrain** [comment]
> on 2.94
> cdk diff does not show any differences
> cdk deploy --all does not roll out handlers, they are still on node 14

Hi @lkoniecz  Thanks for reporting this. The team is currently aware of 2 custom resources that are still on node 16 (not 18).
Could you share some of the code and/or generated CFN template that is still using node 14 runtimes?

**Comment by lkoniecz** [comment]
I wasnt clear enough

I am shifting from 2.60.x
the problem is that I cannot update any lambda function whatsoever since cdk deploy does not override existing runtimes

do I need to fire cdk boostrap or anything similiar to apply new runtime to CDKs lambda 
handlers?

**Comment by lkoniecz** [comment]
@mrgrain 
please disregard my previous comment - internal issue

**Comment by mrgrain** [comment]
No worries and thanks for confirming!
