### ISSUE TITLE
aws-rds: Add `grantConnect` on `DatabaseCluster`

### ISSUE THREAD

**Issue by bestickley** [aws/aws-cdk#26489]
### Describe the feature

Add `grantConnect` (like `DatabaseInstance` has) method on `DatabaseCluster`

### Use Case

I want to instantiate a `DatabaseCluster` and then call `grantConnect` on my lambda function so it can access the cluster - both readers and writers.

### Proposed Solution

See: https://github.com/aws/aws-cdk/discussions/25924#discussioncomment-6533325

### Other Information

cc: @peterwoodworth 

### Acknowledgements

- [ ] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### CDK version used

N/A

### Environment details (OS name and version, etc.)

N/A

**Comment by jaeyeun97** [comment]
+1

**Comment by bestickley** [comment]
closed in https://github.com/aws/aws-cdk/pull/28118
