### ISSUE TITLE
(aws-batch-alpha): Construct Props RuntimePlatform

### ISSUE THREAD

**Issue by gmarchand** [aws/aws-cdk#26484]
### Describe the feature

The property [RuntimePlatform](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-batch-jobdefinition-containerproperties.html#cfn-batch-jobdefinition-containerproperties-runtimeplatform) is not present in the [interface IEcsContainerDefinition](https://docs.aws.amazon.com/cdk/api/v2/docs/@aws-cdk_aws-batch-alpha.IEcsContainerDefinition.html)

### Use Case

I would want to use AWS Batch with Fargate on ARM64 as describe in this news : https://aws.amazon.com/about-aws/whats-new/2023/07/aws-batch-fargate-linux-arm64-windows-x86-containers-cli-sdk/

>To do that customers will need to create ARM64 or Windows job definition using RegisterJobDefinition API of AWS Batch. ARM64-based and Windows-based containers are supported in all Fargate on-demand compute environments.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.88.0

### Environment details (OS name and version, etc.)

All OS

**Comment by pahud** [comment]
Makes sense to me. We could add [RuntimePlatform](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-batch-jobdefinition-containerproperties.html#cfn-batch-jobdefinition-containerproperties-runtimeplatform) in https://github.com/aws/aws-cdk/blob/f22bd4e2b1914b42450ffa061d27009039469b2b/packages/%40aws-cdk/aws-batch-alpha/lib/ecs-container-definition.ts#L361

**Comment by khushail** [comment]
working on it.

**Comment by gmarchand** [comment]
Hello @khushail @pahud the bot @aws-cdk-automation closed your PR last week https://github.com/aws/aws-cdk/pull/26506#issuecomment-1722070067
And the release https://github.com/aws/aws-cdk/releases/tag/v2.96.0 has stabilized the aws-batch module

Do you think your code is still up to date ?

**Comment by khushail** [comment]
Hi @gmarchand , I need to fix some comments, will do it this week hopefully and update the PR. Thanks for checking.

**Comment by gmarchand** [comment]
Hello, Any update on this one ?

**Comment by khushail** [comment]
@gmarchand , Apologies, I could not spend much time on finishing this as got into some other priority work. Please feel free to work on the PR. Contributions are welcome from the community as well.

**Comment by mtheindiecoder** [comment]
I can take over this one.
@gmarchand
