### ISSUE TITLE
Mismatched CDK CLI and Python libs should be reported

### ISSUE THREAD

**Issue by jamesoff** [aws/aws-cdk#2650]
**Describe the bug**
If your Python libs (from `pip install aws_cdk...`) are older than the CLI (from `npm install -g aws-cdk`) then weird errors may occur. It would be good to warn if the cdk installation and the Python libraries are mismatched.

**To Reproduce**
* Install aws-cdk 0.32.0
* Install Python aws-cdk.aws-s3-deployment 0.31.0
* Build a Stack using the BucketDeployment class
* On `deploy`, receive errors about Parameters being `null`, because the two versions disagree on how `Asset`s are represented
* Uninstall aws-cdk 0.32.0 and install 0.31.0
* `cdk deploy` works again

**Expected behavior**
Output which warns that the two components are not matched and thus errors may occur, or cdk should abort.

**Version:**
 - OS: Amazon Linux on Cloud9 (4.14.114-83.126.amzn1.x86_64, launched from ami-03185f4a905fc68c9)
 - Programming Language: Python 3.6.8; aws-cdk 0.31.0
 - CDK Version: 0.32.0 (installed today from `npm i -g aws-cdk`)

**Comment by ranguard** [comment]
I'm having something similar in node, on 0.32.0 but can't quite reproduce, 0.31.0 is fine though
```
failed: ValidationError: 1 validation error detected: Value null at 'parameterList.3.member.parameterKey' failed to satisfy constraint: Member must not be null
```

Using Lambda's / api gateway and dynamodb - will try pin down another time

**Comment by jamesoff** [comment]
Just seen someone report this error on Gitter too, asked them to try 0.31.0 if they're on 0.32.0, so maybe this is an actual bug in 0.32.0 and not just a library mismatch issue.

**Comment by eladb** [comment]
This is resolved. We now have a handshake protocol between the CLI and the app
