### ISSUE TITLE
aws-lambda: VpcConfig is not configured for Lambda Function without specifying Vpc prop

### ISSUE THREAD

**Issue by longtv2222** [aws/aws-cdk#26508]
### Describe the bug

Specifying `securityGroups` without specifying `vpc` prop in Lambda Function leads to `VpcConfig` not added to the generated CloudFormation Template.

### Expected Behavior

VpcConfig is added to Lambda Function:
```json
  "functionF19B1A04": {
   "Type": "AWS::Lambda::Function",
   "Properties": {
    "Code": {
     "ZipFile": "..."
    },
    "Handler": "index.handler",
    "Role": {
     "Fn::GetAtt": [
      "functionServiceRoleEF216095",
      "Arn"
     ]
    },
    "Runtime": "nodejs18.x",
    "VpcConfig": { // VpcConfig is added here
        ...
    }
   },
   "DependsOn": [
    ...
   ]
```

### Current Behavior

VpcConfig is not in Lambda Function

```json
  "functionF19B1A04": {
   "Type": "AWS::Lambda::Function",
   "Properties": {
    "Code": {
     "ZipFile": "..."
    },
    "Handler": "index.handler",
    "Role": {
     "Fn::GetAtt": [
      "functionServiceRoleEF216095",
      "Arn"
     ]
    },
    "Runtime": "nodejs18.x"
   },
   "DependsOn": [
    "functionServiceRoleEF216095"
   ],
   "Metadata": {
    "aws:cdk:path": "TestStack/function/Resource"
   }
  },
```

### Reproduction Steps

The following code does not add `VpcConfig` to CloudFormation template for Lambda function:

```typescript
import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as ec2 from 'aws-cdk-lib/aws-ec2'
import * as lambda from 'aws-cdk-lib/aws-lambda';

export class TestStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const vpc = new ec2.Vpc(this, "vpc");
    const sg = new ec2.SecurityGroup(this, "sg", {
      vpc
    });

    const fn = new lambda.Function(this, 'function', {
      runtime: lambda.Runtime.NODEJS_18_X,
      handler: 'index.handler',
      code: lambda.Code.fromInline("..."),
      securityGroups:[sg],
    });
  }
}
```

However, by adding `vpc` to `props`, now `VpcConfig` is added to the CloudFormation template

```typescript
    const fn = new lambda.Function(this, 'function', {
      runtime: lambda.Runtime.NODEJS_18_X,
      handler: 'index.handler',
      code: lambda.Code.fromInline("..."),
      securityGroups:[sg],
      vpc, // Add vpc to prop
    });
```

### Possible Solution

`securityGroup` (no s) is deprecated and CDK is not throwing error if `securityGroups` is specified and `vpc` is not specified

https://github.com/aws/aws-cdk/blob/39a1d6bf5b5d87d73ec10de1a7a74b4cc4d1ac66/packages/aws-cdk-lib/aws-lambda/lib/function.ts#L1225-L1227

### CDK CLI Version

2.87.0

### Node.js Version

18

### OS

Window

### Language

Typescript

**Comment by pahud** [comment]
Agree. `configureVpc()` will only be executed if props.vpc is provided. We need a check when props.securityGroup is provided and vpc undefined.

**Comment by mbhaalalhhaexchange** [comment]
When **we are using the Security group without VPC for @aws-cdk/aws-lambda package** it **was working well** but when **we have migrate it to the aws-cdk-lib/aws-lambda package** we are **getting following error message**,
**Cannot configure 'securityGroups' without configuring a VPC**

Kindly suggest the possible solution for it.
