### ISSUE TITLE
(module name): (short issue description)

### ISSUE THREAD

**Issue by itaymelamed** [aws/aws-cdk#26521]
### Describe the bug

When trying to create a rule in AWS network firewall using ip set reference, once running cdk deploy , the value in the template for "reference_sets" is empty and i'm getting an internal error

### Expected Behavior

value for reference_sets should be created

### Current Behavior

Value is empty 

### Reproduction Steps

Create a aws network firewall rule with  

```
                    reference_sets=networkfirewall.CfnRuleGroup.ReferenceSetsProperty(
                        ip_set_references={
                            "ip_set_references_key": {
                                "reference_arn": "referenceArn"
                            }
                        }
                    )
``` 

### CDK CLI Version

2.88

### Node.js Version

18.16.0

### OS

Mac

### Language

Python

**Comment by peterwoodworth** [comment]
[`ipSetReferences`](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_networkfirewall.CfnRuleGroup.ReferenceSetsProperty.html) wants an `IPSetReferenceProperty` type for the value. The following works for me:
```py
        networkfirewall.CfnRuleGroup(self, "ruleGroup", 
            capacity=123,
            rule_group_name="ruleGroupName",
            type="type",
            description="description",
            rule_group=networkfirewall.CfnRuleGroup.RuleGroupProperty(
              rules_source=networkfirewall.CfnRuleGroup.RulesSourceProperty(
                rules_string="rulesString",
              ),
              reference_sets=networkfirewall.CfnRuleGroup.ReferenceSetsProperty(
                ip_set_references= {
                    "key" : networkfirewall.CfnRuleGroup.IPSetReferenceProperty(
                        reference_arn='arn'
                    )
                }
              )
            )
        )
