### ISSUE TITLE
(aws-rfdk): CloudWatch Agent role to cdkv2

### ISSUE THREAD

**Issue by rantoniuk-toptal** [aws/aws-cdk#26550]
### Describe the feature

I see it is possible to install CloudWatch agent via [aws-rfdk.CloudWatchAgent](https://docs.aws.amazon.com/rfdk/api/latest/docs/aws-rfdk.CloudWatchAgent.html) and I am wondering why is this in a separate repository from aws-cdk? Shouldn't that be the major usecase for AWS CDK EC2 management? 
Could that be merged into this repository?

### Use Case

Deploying CloudWatch Agent is a standard usecase for CDK EC2 management.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

current

### Environment details (OS name and version, etc.)

-

**Comment by peterwoodworth** [comment]
I've never seen this package before. It doesn't appear to me that we own it, and it doesn't appear to have its own L1s. So I don't think we will be able to put this in the main library. If it ever makes sense for that to happen, it will, but I doubt it will.
