### ISSUE TITLE
appsync: Log group for API is not created at deployment leading to "The specified log group does not exist" error when applying metric filter

### ISSUE THREAD

**Issue by jzybert** [aws/aws-cdk#26564]
### Describe the bug

I am deploying a GraphqlApi construct with a `logConfig` prop set with retention days as well. I am also calling `api.logGroup.addMetricFilter` in the same stack. However, I get this error `Resource handler returned message: "The specified log group does not exist`. It appears that the log group is not created even when the `logConfig` prop is provided upon deployment. This is causing newly deployed stacks to fail.

### Expected Behavior

I would have expected the log group to be created when the API is created so that metric filters could be applied.

### Current Behavior

I get a CloudFormation error of `Resource handler returned message: "The specified log group does not exist` and my stack fails to depoy.

### Reproduction Steps

```
const api = new GraphqlApi(this, 'API', {
  name: 'api',
  schema: SchemaFile.fromAsset('schema.graphql'),
  logConfig: {
    fieldLogLevel: FieldLogLevel.ALL,
    retention: RetentionDays.ONE_WEEK,
    excludeVerboseContent: true
  },
});

api.logGroup.addMetricFilter('MetricFilter', {
  filterPattern: {
    logPatternString: '{ $.fieldName = "myQuery" && $.fieldInError IS TRUE }'
  },
  metricName: 'ErrorCount',
  metricNamespace: 'MyNamespace,
  metricValue: '1',
});
```

### Possible Solution

It appears that the code is simply looking for a log group name but not actually generating its own log group when the API is created. See [here](https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-appsync/lib/graphqlapi.ts#L568). A fix for this would be to ensure the log group is actually created rather than trying to load it by name.

### Additional Information/Context

Some additional context is that I'm using VTL templates for some of my API resolvers. Because they don't natively have their own log groups or metrics, I'm leveraging adding a metric filter to the main API log group which is where the template resolvers log their logs/errors to.

### CDK CLI Version

2.88.0

### Node.js Version

18

### OS

macOS Ventura 13.4

### Language

Typescript

### Language Version

5.0.4

**Comment by pahud** [comment]
Looks like it assums the log group already exists.

https://github.com/aws/aws-cdk/blob/960d14a675d9eb3c454a9d6960d3c0c124711d5d/packages/aws-cdk-lib/aws-appsync/lib/graphqlapi.ts#L566-L568

Reading the doc I guess you will need to enable the logging first?
https://docs.aws.amazon.com/appsync/latest/devguide/monitoring.html

If this works for you, we probably should add this notice in the CDK doc.

**Comment by jzybert** [comment]
@pahud The logConfig is added if that's what you mean by enable logging first

**Comment by jzybert** [comment]
@pahud ah, I see. Unfortunately that doesn't entirely work for us, because our CloudFormation stack deployment would fail after deploying the API but before enabling the logs then. Hoping for a CDK update here to support turning it on immediately after the API is created rather than needing to be a manual process

**Comment by yashmardikar** [comment]
For me even after logging was turned on, the log group was not getting created. I ran some queries and then log group was created. Is log group created lazily? This is not ideal. 

For first time deployment in new region/env, deployment fails and then rollback takes at least 20 mins before i can try another deployment. Please Fix this.

**Comment by vineetdevop** [comment]
> For me even after logging was turned on, the log group was not getting created. I ran some queries and then log group was created. Is log group created lazily? This is not ideal.
> 
> For first time deployment in new account/region, deployment fails and then rollback takes at least 20 mins before i can try another deployment. Please Fix this.

facing same issue. May I know what query you had executed to create the log group ?

**Comment by cremich** [comment]
+1. I also ran in this issue using Amplify Gen2.
