### ISSUE TITLE
aws-s3-deployment: Add ability to invalidate multiple CloudFront Distributions

### ISSUE THREAD

**Issue by stephen-christie-ss** [aws/aws-cdk#26565]
### Describe the feature

Currently, there is support to invalidate the cache on a single CloudFront Distribution. It is possible to use the same bucket for multiple distributions, but currently no way to invalidate the files across all of those distributions.

### Use Case

Example: Deploying to multiple domains, each with their own Certificates (can require multiple distributions serving the same content).

### Proposed Solution

Accept a List of Distributions as input to the Construct.

### Other Information

A workaround may be to create additional s3_deployments, each with no sources.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

1.204.0

### Environment details (OS name and version, etc.)

Debian 12

**Comment by khushail** [comment]
Seems like a duplicate of existing request [#22309](https://github.com/aws/aws-cdk/issues/22309)

**Comment by khushail** [comment]
Looks like its similar to this one - [#22309 ](https://github.com/aws/aws-cdk/issues/22309)

**Comment by stephen-christie-ss** [comment]
Agreed. Thank you!
