### ISSUE TITLE
aws-cdk-lib: add RetainExceptOnCreate to RemovalPolicy enum

### ISSUE THREAD

**Issue by rittneje** [aws/aws-cdk#26570]
### Describe the feature

CloudFormation recently added a new DeletionPolicy `RetainExceptOnCreate`. Please add an equivalent enum value to `RemovalPolicy`.

Note: There is no corresponding UpdateRemovalPolicy for this. Presumably the new enum value should translate to an UpdateRemovalPolicy of `Retain`.

### Use Case

We don't want to retain newly created resources since they are essentially empty. Generally this comes up where the deployment fails for some reason and CloudFormation rolls back. But then we cannot try again without manual intervention since it will try to create the same resoruce again and fail.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.89.0

### Environment details (OS name and version, etc.)

Alpine 3.18

**Comment by evgenyka** [comment]
Also, sounds like a reasonable default for stateful resources.
