### ISSUE TITLE
ECS Fargate Service: Alarm based rollback is not supported (cn-north-1)

### ISSUE THREAD

**Issue by YikaiHu** [aws/aws-cdk#26574]
### Describe the bug

In version v2.89.0, 

```
    const service = new ecs.FargateService(this, `Service`, {
      cluster: ecsCluster,
      desiredCount: 2, // This number must larger than the number of NLB AZs
      taskDefinition: taskDefinition,
      vpcSubnets: {
        subnets: taskSubnets,
      },
      securityGroups: [ecsServiceSG],
      assignPublicIp: false,
      minHealthyPercent: 100,
      maxHealthyPercent: 200,
      propagateTags: ecs.PropagatedTagSource.SERVICE,
      enableECSManagedTags: true,
      enableExecuteCommand: true,
    });
```

will trigger the CDK deployment failure:

![image](https://github.com/aws/aws-cdk/assets/34271744/860668ca-4186-4cbb-bceb-28eb4e8206c5)

> Resource handler returned message: "Alarm based rollback is not supported. (Service: AmazonECS; Status Code: 400; Error Code: UnsupportedFeatureException; Request ID: a76f0b28-829f-40dc-ad32-11ff095a3d22; Proxy: null)" (RequestToken: 1fc816d1-763b-edf2-813f-52938aac2e50, HandlerErrorCode: GeneralServiceException)

This may caused by: from https://github.com/aws/aws-cdk/pull/25840, ECS L2 construct sets the default configuration for the CfnService.deploymentConfiguration.alarms property to:

```
alarmNames: [],
rollback: false,
enable: false,
```

But it seems like that not all AWS region support this feature.

### Expected Behavior

Deployment successfully

### Current Behavior

CDK deployment failed

Resource handler returned message: "Alarm based rollback is not supported. (Service: AmazonECS; Status Code: 400; Error Code: UnsupportedFeatureException; Request ID: a76f0b28-829f-40dc-ad32-11ff095a3d22; Proxy: null)" (RequestToken: 1fc816d1-763b-edf2-813f-52938aac2e50, HandlerErrorCode: GeneralServiceException)

### Reproduction Steps

```
    const service = new ecs.FargateService(this, `Service`, {
      cluster: ecsCluster,
      desiredCount: 2, // This number must larger than the number of NLB AZs
      taskDefinition: taskDefinition,
      vpcSubnets: {
        subnets: taskSubnets,
      },
      securityGroups: [ecsServiceSG],
      assignPublicIp: false,
      minHealthyPercent: 100,
      maxHealthyPercent: 200,
      propagateTags: ecs.PropagatedTagSource.SERVICE,
      enableECSManagedTags: true,
      enableExecuteCommand: true,
    });
```

### CDK CLI Version

v2.89.0

### Node.js Version

nodejs16

### OS

MacOS

### Language

Typescript

**Comment by pahud** [comment]
Thank you for your feedback.

Have you tried to remove the `"Rollback": false` property with `addPropertyDeletionOverride`?

```ts
(service.node.tryFindChild('Service') as ecs.CfnService).addPropertyDeletionOverride('DeploymentConfiguration.Alarms.Rollback')
```

If this works in CN regions, we probably should add a condition for that.

**Comment by YikaiHu** [comment]
Thanks Pahub, nice to meet you again hahaha.

Yes, I use `addPropertyDeletionOverride ` to solve this issue finally.

Here is my code:

```typescript
.....

Aspects.of(this).add(new InjectRemoveECSAlarm());

....

class InjectRemoveECSAlarm implements IAspect {
  public visit(node: IConstruct): void {
    if (
      node instanceof CfnResource &&
      node.cfnResourceType === "AWS::ECS::Service"
    ) {
      node.addDeletionOverride(
        "Properties.DeploymentConfiguration.Alarms"
      );
    }
  }
}

```

**Comment by peterwoodworth** [comment]
This was fixed, https://github.com/aws/aws-cdk/pull/26458 correct?

**Comment by pahud** [comment]
Hi @YikaiHu 

According to https://github.com/bvtujo/aws-cdk/blob/a25fdc8545f2a6731afddd3ab6f27becbf4dd6e1/packages/aws-cdk-lib/aws-ecs/lib/base/base-service.ts#L1370 I think you should not need the injection anymore?

**Comment by YikaiHu** [comment]
Yes, it worked, no more injection is needed, thanks!
