### ISSUE TITLE
aws_redshiftserverless.CfnWorkgroup: creation of Redshift-managed VPC endpoints not working

### ISSUE THREAD

**Issue by davyto** [aws/aws-cdk#26585]
### Describe the bug

Hi, we are trying to create a Redshift-managed VPC endpoints in our Redshift Serverless workgroup, but this does not seem to be supported with CDK. There is no option in CfnWorkgroup to create one, while the [VpcEndpointProperty](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_redshiftserverless/CfnWorkgroup.html#vpcendpointproperty) and [WorkgroupProperty](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_redshiftserverless/CfnWorkgroup.html#workgroupproperty) are ignored at deploy.

### Expected Behavior

The vpc endpoint creation should be triggered by VpcEndpointProperty, or something that calls this API https://docs.aws.amazon.com/redshift-serverless/latest/APIReference/API_CreateEndpointAccess.html

### Current Behavior

The creation of the endpoint gets ignored by cdk deploy.

### Reproduction Steps

        # create workgroup
        workgroup = redshiftserverless.CfnWorkgroup(self, "workgroup",
            workgroup_name = "workgroup",
            # the properties below are optional
            base_capacity = 24,
            enhanced_vpc_routing = True,
            namespace_name = namespace.namespace_name,
            security_group_ids = [ security_group_id ],
            subnet_ids = subnets_ids
            )
              
        workgroup_property = redshiftserverless.CfnWorkgroup.WorkgroupProperty(
            endpoint=redshiftserverless.CfnWorkgroup.EndpointProperty(
                port=5439,
                vpc_endpoints=[redshiftserverless.CfnWorkgroup.VpcEndpointProperty(
                    network_interfaces=redshiftserverless.CfnWorkgroup.NetworkInterfaceProperty(
                        subnet_id=subnet_id ),
                    vpc_endpoint_id="endpoint",
                    vpc_id=vpc.vpc_id
                )]
            ),
            workgroup_arn=workgroup.attr_workgroup_workgroup_arn
        )

### Possible Solution

The construct should use this api https://docs.aws.amazon.com/redshift-serverless/latest/APIReference/API_CreateEndpointAccess.html

### CDK CLI Version

2.87.0

### Node.js Version

16.20

### OS

mac and linux

### Language

Python

**Comment by peterwoodworth** [comment]
We are simply generating the CloudFormation template here directly as you've defined it. Be sure to check if the template that's deploying is synthesizing correctly. Please share the template synthesized if you're not sure

If it is synthing correctly, and you're finding issues after deployment with a Cfn resource, you'll want to report that to the Cloudformation coverage roadmap repository https://github.com/aws-cloudformation/cloudformation-coverage-roadmap

**Comment by pietrocarbo** [comment]
I'm working alongside @davyto and I'm experiencing the same issue. 

The synthetized Cloudformation code for the above snippet is the following: 

```
  "redshiftworkgroup": {
   "Type": "AWS::RedshiftServerless::Workgroup",
   "Properties": {
    "WorkgroupName": "redshift-workgroup",
    "BaseCapacity": 24,
    "EnhancedVpcRouting": true,
    "NamespaceName": "redshift-namespace",
    "SecurityGroupIds": [
     {
      "Fn::GetAtt": [
       "RedshiftSsSg1A2DB58F",
       "GroupId"
      ]
     }
    ],
    "SubnetIds": [
     {
      "Fn::ImportValue": "SharedInfraStack:ExportsOutputRefSharedInfraVpcRedshiftServerlessSubnet1Subnet8A5BC66334236308"
     },
     {
      "Fn::ImportValue": "SharedInfraStack:ExportsOutputRefSharedInfraVpcRedshiftServerlessSubnet2SubnetEC3C9E5B7744B006"
     },
     {
      "Fn::ImportValue": "SharedInfraStack:ExportsOutputRefSharedInfraVpcRedshiftServerlessSubnet3Subnet936BBE9D2CBE133E"
     }
    ]
   },
   "DependsOn": [
    "redshiftnamespace"
   ],
   "Metadata": {
    "aws:cdk:path": "RedshiftServerlessStack/redshift-workgroup"
   }
  }
```

The problem is that in the generated Cloudformation resource there is no Endpoint property being created

**Comment by peterwoodworth** [comment]
> The problem is that in the generated Cloudformation resource there is no Endpoint property being created

Yeah, you aren't specifying this property with the snippet you gave

> If this snippet is exactly what you used then you'll need to actually specify the properties in the construct constructor, or use escape hatches on the construct after the fact

```
    # create workgroup
    workgroup = redshiftserverless.CfnWorkgroup(self, "workgroup",
        workgroup_name = "workgroup",
        # the properties below are optional
        base_capacity = 24,
        enhanced_vpc_routing = True,
        namespace_name = namespace.namespace_name,
        security_group_ids = [ security_group_id ],
        subnet_ids = subnets_ids,
        endpoint=redshiftserverless.CfnWorkgroup.EndpointProperty(
            port=5439,
            vpc_endpoints=[redshiftserverless.CfnWorkgroup.VpcEndpointProperty(
                network_interfaces=redshiftserverless.CfnWorkgroup.NetworkInterfaceProperty(
                    subnet_id=subnet_id ),
                vpc_endpoint_id="endpoint",
                vpc_id=vpc.vpc_id
            )]
        ),
        workgroup_arn=workgroup.attr_workgroup_workgroup_arn
        )
   
```

**Comment by davyto** [comment]
@peterwoodworth the `endpoint` property does not seem to exist in `CfnWorkgroup`. I tried your snippet and I got 
`TypeError: __init__() got an unexpected keyword argument 'endpoint'` .

The cdk documentation also does not show it https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_redshiftserverless/CfnWorkgroup.html
