### ISSUE TITLE
(stepfunctions): invalid parameter value in `CfnStateMachineAlias` example

### ISSUE THREAD

**Issue by lpizzinidev** [aws/aws-cdk#26601]
### Describe the issue

The `CfnStateMachineAlias` documentation example contains an invalid `routingConfiguration.weight` value of `123`.
The `weight` attributes specified in `routingConfiguration` should add up to `100`.

Also, it is not specified in the docs, but maybe also `deploymentPreference.percentage` should be `<= 100`?

<img width="870" alt="Screenshot 2023-08-02 at 08 57 48" src="https://github.com/aws/aws-cdk/assets/15077781/423ce689-95ae-46a2-8e0a-855ae357eb33">

### Links

- https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_stepfunctions.CfnStateMachineAlias.html
- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-stepfunctions-statemachinealias-routingconfigurationversion.html#:~:text=%3A%20No%20interruption-,Weight,-The%20percentage%20of

**Comment by peterwoodworth** [comment]
Given the docs note above the snippet, I think this is fine.

> The values are placeholders you should change

We cannot possibly know the restrictions of every single property of every single CloudFormation resource. We just know the properties and types CloudFormation expects. This will have to stay, even if it would be nice if we could make the values more realistic
