### ISSUE TITLE
aws_opensearchservice: High Level Constructs For OpenSearch SamlOptions Feature

### ISSUE THREAD

**Issue by devardee** [aws/aws-cdk#26600]
### Describe the feature

SAMLOptions is an existing Feature for OpenSearch Domain. [Feature Documentation Link](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/saml.html). According to the CDK docs currently there is no high level CDK construct for this feature.[CDK Docs link for the SamlOptions](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_opensearchservice.CfnDomain.SAMLOptionsProperty.html)

### Use Case

The general recommendation is to use high level constructs and due to lack of High level construct for this feature, the CDK template needs to be migrated to use CFN constructs if there is a need to Create an OpenSearchDomain with SAMLOptionsProperty. This serves as a hinderance to the adoption of the SAMLOptionsProperty feature for AWS OpenSearch Domains.

### Proposed Solution

Add the SAMLOptionsProperty to the AdvancedSecurityOptions interface object [CDK Doc for AdvancedSecurityOptions Attribute](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_opensearchservice.AdvancedSecurityOptions.html) .
A SamlOptions enabeld OpenSearchDomain created using CDK high level constructs should look like
```
const domain = new Domain(this, 'Domain', {
  version: EngineVersion.OPENSEARCH_1_0,
  enforceHttps: true,
  nodeToNodeEncryption: true,
  encryptionAtRest: {
    enabled: true,
  },
  fineGrainedAccessControl: {
    masterUserName: 'master-user',
    samlOptions: {
      enabled: true,
      idp: {
             entityId: 'entityId',
             metadataContent: 'metadataContent',
      },
     masterBackendRole: 'masterBackendRole',
     masterUserName: 'masterUserName',
     rolesKey: 'rolesKey',
     sessionTimeoutMinutes: 123,
     subjectKey: 'subjectKey',
   }
  },
  logging: {
    auditLogEnabled: true,
    slowSearchLogEnabled: true,
    appLogEnabled: true,
    slowIndexLogEnabled: true,
  },
});
```

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.84.0

### Environment details (OS name and version, etc.)

macOS Ventura 13.4

**Comment by khushail** [comment]
thanks @devardee  for submitting this feature request. You could get started with this [contributing guide](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md#step-1-find-something-to-work-on) for the PR.
