### ISSUE TITLE
Amazon.CDK.AWS.EKS.Cluster does not apply stack tags while sub-resources do

### ISSUE THREAD

**Issue by icelava** [aws/aws-cdk#26617]
### Describe the bug

We have an L3 construct that deploys an EKS cluster with add-ons and node groups.
```
this.Cluster = new Cluster(this, this._clusterName, new ClusterProps
{
	ClusterName = this._clusterName,
	Version = KubernetesVersion.V1_26,
	Vpc = this._props.Vpc,
	VpcSubnets = this._props.DeploymentSubnets.ToArray(),
	Role = this._clusterRole,
	EndpointAccess = EndpointAccess.PRIVATE,
	KubectlLayer = new KubectlV26Layer(this, $"{this._props.ProductName}-kubectllayer-{this._props.Environment}"),
	DefaultCapacity = 0,
	AlbController = new AlbControllerOptions
	{
		Version = AlbControllerVersion.V2_4_1
	},
	MastersRole = this._props.MastersRole

});
```
Tags are applied at the Stack level, thus propagating to all resources.
```
public static void ApplyTags(Stack stack, Dictionary<string, string> stackTags)
{
	if (stackTags == null ||
		stackTags.Count < 1) return;

	foreach (var tag in stackTags)
	{
		Amazon.CDK.Tags.Of(stack).Add(tag.Key, tag.Value);
	}
}
```

Other stack resources get the tags except the EKS cluster. The sub-resources of the cluster like the node groups do get tagged, although the actual node instances don't get them either.

### Expected Behavior

EKS cluster and nodes should be tagged accordingly to stack tags.

### Current Behavior

EKS cluster and nodes don't get tagged.

### Reproduction Steps

Apply tags at Stack level instead of individual construct as per above code example.

### CDK CLI Version

2.88.0

### Framework Version

.NET 6.0

### Node.js Version

18.9.0

### OS

Windows 10

### Language

.NET

### Language Version

C# 10

**Comment by peterwoodworth** [comment]
Since our EKS L2s use Custom resources under the hood, aspects like this won't work because the resources aren't defined in the template. You can use the [tags](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_eks.Cluster.html#tags) prop instead

**Comment by icelava** [comment]
What about nodes in the node groups?

**Comment by andreprawira** [comment]
> You can use the [tags](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_eks.Cluster.html#tags) prop instead
@peterwoodworth but this prop does not update the tags in the cluster, it only applies the tags during creation, if you try to update the tags, its not reflected, any idea how to fix it?
