### ISSUE TITLE
awseks: Unable to update EKS cluster tags

### ISSUE THREAD

**Issue by ytizhang** [aws/aws-cdk#26614]
### Describe the bug

We are using awscdk Go version v2.63.2 to create cluster with tags. When we create a cluster, the tags are correctly added. However, when we update a cluster, the tags on EKS cluster is not updated.
CDK diff shows 
[~] Custom::AWSCDK-EKS-Cluster EKSCluster/Resource/Resource EKSClusterE11008B6 
 └─ [~] Config
     └─ [~] .tags:
         ├─ [+] Added: .LastRevalidatedAt
         └─ [+] Added: .LastRevalidatedBy

Tried using the latest version v2.89.0, and saw the same issue

### Expected Behavior

The tags on EKS cluster should be updated

### Current Behavior

The tags on EKS cluster doesn't get updated

### Reproduction Steps

Part of the Go code that's used to create a cluster:
```
tags := getClusterTags(props) // get tags from our internal cluster type
clusterProps := &awseks.ClusterProps{
                 ...
		Tags:                 &tags,
                 ...
	}
cluster := awseks.NewCluster(stack, jsii.String("EKSCluster"), clusterProps)
```
We have an internal cluster type definition which we can specify the tags to use.

Reproduction steps:
1. Run `cdk deploy...` to create a cluster with tags.
2. Update the cluster type to add some additional tags
3. Run `cdk deploy...` to update the cluster
4. Observed the cluster tags are not updated.

### CDK CLI Version

2.89.0

### Node.js Version

v18.12.1

### OS

MacOS

### Language

Go

### Language Version

1.18

**Comment by pahud** [comment]
Thanks for report. Closing in favor of https://github.com/aws/aws-cdk/issues/26614

**Comment by ytizhang** [comment]
@pahud I guess you put the wrong link in your closing comment. Please check.
