### ISSUE TITLE
Python snake case conversion is odd in some cases

### ISSUE THREAD

**Issue by jamesoff** [aws/aws-cdk#2661]
**Describe the bug**
I am assuming that the jsii conversion/shim attempts to make Pythonic names in snake case by splitting the source camel case words at capital letters, but as a result it can generate slightly odd names where two capitals appear together. For example, the `MaxAZs` property of the aws_ec2.Vpc class becomes `max_a_zs`.

While not breaking, this does mean some names are not that which one might expect (i.e. `max_azs` in this case).

**To Reproduce**
Inspect the `Vpc` class in the aws_ec2 package. It can also be seen as the `Fn.get_a_zs` classmethod in the main cdk package. This is not an exhaustive list.

**Expected behavior**
I would expect this parameter to be `max_azs`.

**Version:**
 - OS: Any
 - Programming Language: Python
 - CDK Version: 0.32.0

**Comment by garnaat** [comment]
I agree that the current snake-casing approach leads to some very awkward names like the one shown above.  I would like to address this and, obviously, this should be done sooner rather than later as it would be a breaking change.

**Comment by eladb** [comment]
Ideally we should find a way to solve this at the Jsii compiler level so all languages benefit. Perhaps we can just enforce that names will never have 2 consecutive capital letters...

**Comment by fulghum** [comment]
Need to confirm fix.  @garnaat or @rix0rrr can you confirm?

**Comment by garnaat** [comment]
This is fixed.
