### ISSUE TITLE
Lambda Insights has incorrect ARN for 1.0.229 in us-west-1 on ARM64

### ISSUE THREAD

**Issue by chuanconggao** [aws/aws-cdk#26615]
### Describe the bug

In [public doc](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Lambda-Insights-extension-versionsARM.html) and CDK, it mentions Lambda layer ARN of version 5 for 1.0.229 in us-west-1 on ARM64
`arn:aws:lambda:us-west-1:580247275435:layer:LambdaInsightsExtension-Arm64:5`

However, I am getting CFN error like below only in us-west-1
```
... is not authorized to perform: lambda:GetLayerVersion on resource: arn:aws:lambda:us-west-1:580247275435:layer:LambdaInsightsExtension-Arm64:5 because no resource-based policy allows the lambda:GetLayerVersion action ...
```

It seems version 5 actually does not exist, and only version 3 exists in us-west-1 on ARM64, based on verification in Lambda console. 

### Expected Behavior

Able to use Lambda Insights 1.0.229 in us-west-1 on ARM64

### Current Behavior

Not able to deploy

### Reproduction Steps

As mentioned above

### Possible Solution

Either fix Lambda layer ARN to version 3 or actually upgrade to version 5

### CDK CLI Version

2.88

### Node.js Version

18

### OS

macOS

### Language

Typescript

**Comment by chuanconggao** [comment]
I have confirmed with Lambda Insights folks and confirmed the version is wrong. They are updating on their side, and CDK side should update as well.

**Comment by pahud** [comment]
yes we should fix here

https://github.com/aws/aws-cdk/blob/03c6f6fb667a1d7034537b514103215bb949a8da/packages/aws-cdk-lib/region-info/build-tools/fact-tables.ts#L230C41-L230C41

Would you like to submit a PR for that?

**Comment by orekav** [comment]
I have checked against Google cached website and yes, it was wrong before.
I put the previous PR up https://github.com/aws/aws-cdk/issues/26150

Wouldn't be better to have an actual test that deploys a lambda in each region with every layer in the fact_table?
Or is it an overkill?

https://webcache.googleusercontent.com/search?q=cache:pLFJLErl5FcJ:https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Lambda-Insights-extension-versionsARM.html&cd=8&hl=en&ct=clnk&gl=uk

**Comment by chuanconggao** [comment]
Integ tests against all regions and different combinations should be there, especially for this case where there are so many hardcoded values different across regions.
