### ISSUE TITLE
(glue-alpha): Improve Glue version synth time checks

### ISSUE THREAD

**Issue by dokeita** [aws/aws-cdk#26620]
### Describe the feature

we can create PythonShell job with GlueVersion 3.0 using AWS Glue Studio.
I would like to be able to create it in glue-alpha.Job as well.

### Use Case

When we create a PythonShell job in AWS Glue Studio, the GlueVersion is set to 3.0.
Therefore, it is better to be able to create PythonShell jobs with GlueVersion 3.0 using CDK.

### Proposed Solution

We just need to fix this if statement.

https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/aws-glue-alpha/lib/job-executable.ts#L357
``` python
      if ([GlueVersion.V0_9, GlueVersion.V3_0, GlueVersion.V4_0].includes(config.glueVersion)) {
        throw new Error(`Specified GlueVersion ${config.glueVersion.name} does not support Python Shell`);
      }
```

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.89.0

### Environment details (OS name and version, etc.)

Ubuntu 20.04 on Windows10 ( WSL2 )

**Comment by pahud** [comment]
related to https://github.com/aws/aws-cdk/issues/26599

Making it a p1 and any PR would be welcome and appreciated.

**Comment by peterwoodworth** [comment]
and related to #26616

**Comment by peterwoodworth** [comment]
Consolidating all these issues into this one
