### ISSUE TITLE
(aws-batch): Unable to Specify Mount point and Volume in CDK for Batch Job

### ISSUE THREAD

**Issue by navneethc** [aws/aws-cdk#26622]
### Describe the bug

I have a working StepFunction that calls a couple of Batch jobs. These were configured using the console. I'm trying to automate the deployment of the workflow using CDK (TypeScript). I am unable to find the options to specify the mount points and volume configuration that's found in the console. 

Specifically, if you are looking at the console and setting up an EC2-based job definition:
`Linux and logging settings > Filesystem configuration > Additional configuration > Volumes configuration`, and similarly, next to it `Mount points configuration`.

I am trying to do this with both `aws-cdk-lib/aws-batch` and `@aws-cdk/aws-batch-alpha` (v2.89.0), but I can't find the right properties to specify.

The Batch job is EC2-based and will run a container using a previously defined computer environments. The EBS storage cannot be restricted to 30 GB.

### Expected Behavior

I can't find the appropriate classes to use in the documentation. I'm not sure if it's unimplemented or undocumented.

### Current Behavior

Batch job cannot be created without these options.

### Reproduction Steps

NA

### CDK CLI Version

2.79.0

### Node.js Version

16.20.1

### OS

Ubuntu

### Language

Typescript

### Language Version

4.9.5

**Comment by peterwoodworth** [comment]
You should be able to provide volumes to our ECS Container constructs, such as [here](https://docs.aws.amazon.com/cdk/api/v2/docs/@aws-cdk_aws-batch-alpha.EcsEc2ContainerDefinition.html#volumesspan-classapi-icon-api-icon-experimental-titlethis-api-element-is-experimental-it-may-change-without-noticespan).

 If you want to drop to the L1s, you will want to configure the [JobDefinition.containerProperties](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_batch.CfnJobDefinitionProps.html#containerproperties)

Do either of these help your use case?

**Comment by navneethc** [comment]
> You should be able to provide volumes to our ECS Container constructs, such as [here](https://docs.aws.amazon.com/cdk/api/v2/docs/@aws-cdk_aws-batch-alpha.EcsEc2ContainerDefinition.html#volumesspan-classapi-icon-api-icon-experimental-titlethis-api-element-is-experimental-it-may-change-without-noticespan).
> 
> If you want to drop to the L1s, you will want to configure the [JobDefinition.containerProperties](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_batch.CfnJobDefinitionProps.html#containerproperties)
> 
> Do either of these help your use case?

Thanks for the reply. This is the relevant bit of the stack I have already created:

```
import * as batch from '@aws-cdk/aws-batch-alpha';

const jobdef = new batch.EcsJobDefinition(this, 'job-def-name',{
  jobDefinitionName: 'fooname',
  timeout: cdk.Duration.hours(#),
  container = new batch.EcsEc2ContainerDefinition(this, 'container-name', {
    image: fooImage,
    jobRole: batchRole,
    command: [foo, bar, baz],
    memory: cdk.Size.mebibytes(####)
    cpu: #,
    logging: ecs.LogDriver.awslogs,
  })
})
```
I'm not quite sure which properties I should use to specify the mount points and volume. I see the `volume` property, but when I follow the links, the [example provided](https://docs.aws.amazon.com/cdk/api/v2/docs/@aws-cdk_aws-batch-alpha.EcsVolume.html#example) is for EFS.

**Comment by peterwoodworth** [comment]
[Volume prop](https://docs.aws.amazon.com/cdk/api/v2/docs/@aws-cdk_aws-batch-alpha.EcsEc2ContainerDefinition.html#volumesspan-classapi-icon-api-icon-experimental-titlethis-api-element-is-experimental-it-may-change-without-noticespan) takes in an array of [`EcsVolume`s](https://docs.aws.amazon.com/cdk/api/v2/docs/@aws-cdk_aws-batch-alpha.EcsVolume.html). You should be able to use [EcsVolume.host()](https://docs.aws.amazon.com/cdk/api/v2/docs/@aws-cdk_aws-batch-alpha.EcsVolume.html#static-hostoptionsspan-classapi-icon-api-icon-experimental-titlethis-api-element-is-experimental-it-may-change-without-noticespan)

**Comment by navneethc** [comment]
> [Volume prop](https://docs.aws.amazon.com/cdk/api/v2/docs/@aws-cdk_aws-batch-alpha.EcsEc2ContainerDefinition.html#volumesspan-classapi-icon-api-icon-experimental-titlethis-api-element-is-experimental-it-may-change-without-noticespan) takes in an array of [`EcsVolume`s](https://docs.aws.amazon.com/cdk/api/v2/docs/@aws-cdk_aws-batch-alpha.EcsVolume.html). You should be able to use [EcsVolume.host()](https://docs.aws.amazon.com/cdk/api/v2/docs/@aws-cdk_aws-batch-alpha.EcsVolume.html#static-hostoptionsspan-classapi-icon-api-icon-experimental-titlethis-api-element-is-experimental-it-may-change-without-noticespan)

This is exactly what I was looking for. Thank you.
