### ISSUE TITLE
Apprunner: After pushing a Docker image to ECR, isn't triggered.

### ISSUE THREAD

**Issue by watany-dev** [aws/aws-cdk#26640]
### Describe the bug

Deployed AppRunner using AWS CDK.
The expected behavior is for AppRunner to automatically deploy upon each change to the container image in ECR.

### Expected Behavior

After pushing a Docker image to ECR, the AppRunner deployment is triggered.

### Current Behavior

However, even after pushing a Docker image to ECR, the AppRunner deployment isn't triggered.

### Reproduction Steps

import * as apprunner from '@aws-cdk/aws-apprunner-alpha'
import { Cpu, Memory } from '@aws-cdk/aws-apprunner-alpha'
import * as cdk from 'aws-cdk-lib'
import * as iam from 'aws-cdk-lib/aws-iam'
import { Construct } from 'constructs'
import { EcrStack } from './ecr'

export class AppRunnerStack extends cdk.Stack {
  constructor(
    scope: Construct,
    id: string,
    ecrStack: EcrStack,
    props?: cdk.StackProps,
  ) {
    super(scope, id, props)

    new apprunner.Service(this, 'SampleAppRunnerService', {
      serviceName: 'sample-app',
      cpu: Cpu.ONE_VCPU,
      memory: Memory.TWO_GB,
      autoDeploymentsEnabled: true,
      source: apprunner.Source.fromEcr({
        imageConfiguration: {
          port: 3000,
          startCommand: 'npm run start --workspace=app',
        },
        repository: ecrStack.repository,
        tagOrDigest: 'latest',
      }),
    })
  }
}

## Cause:

The access role for AppRunner’s service is automatically generated. However, it lacks permission for the ecr:DescribeImages action, preventing it from detecting image changes.

## Necessary Permissions:
Actions required for ECR access:
- ecr:BatchCheckLayerAvailability
- ecr:GetDownloadUrlForLayer
- ecr:BatchGetImage
- ecr:GetAuthorizationToken

## Actions that AppRunner needs for ECR access:
- ecr:GetDownloadUrlForLayer
- ecr:BatchCheckLayerAvailability
- ecr:BatchGetImage
- ecr:DescribeImages
- ecr:GetAuthorizationToken

## Proposed Solution:
1. Add the ecr:DescribeImages action to the access role of AppRunner's service.
2. Attach the IAM policy that includes the above actions to AppRunner.
3. Make the AccessRole public to allow users to access it.

### Additional Information/Context

https://zenn.dev/okaharuna/articles/bed7f41498a1b6

### CDK CLI Version

2.89.0

### Node.js Version

any

### OS

any

### Language

Typescript

**Comment by pinelibg** [comment]
It seems that `ecr:DescribeImages` action for the ECR repository is missing in the access role.

Reference of the required actions: https://docs.aws.amazon.com/apprunner/latest/dg/security_iam_service-with-iam.html#security_iam_service-with-iam-roles

As a workaround, the following fix worked for me.

```typescript
(service.node.findChild('AccessRole') as Role).addToPrincipalPolicy(
  new PolicyStatement({
    actions: ['ecr:DescribeImages'],
    resources: [repository.repositoryArn],
  }),
);
```

**Comment by wired00** [comment]
Seeing the same behaviour, looking forwrad to the above PR being (merged).

**Comment by Rajeevroushandev** [comment]
after adding permission `ecr:DescribeImages`, then also it does not work. app runner does not triggered on ecr image tag update. please suggest.
