### ISSUE TITLE
app-staging-synthesizer: ecr repo not immutable

### ISSUE THREAD

**Issue by tenjaa** [aws/aws-cdk#26655]
### Describe the bug

AWS recommends ECR repos to have tag immutability configured.
The ECR repos created by this module to not do that.

### Expected Behavior

The ECR repos created by this module should have tag immutability configured.

### Current Behavior

The ECR repos created by this module do not have tag immutability configured.

### Reproduction Steps

Deploy a stack with a docker image and have a look at the created repo.

### CDK CLI Version

2.90.0

### Node.js Version

18

### OS

OSX

### Language

Typescript

**Comment by peterwoodworth** [comment]
Is this a recommendation or a requirement? Also, could you share the docs where AWS recommends this?

**Comment by tenjaa** [comment]
Totally forgot the link: https://docs.aws.amazon.com/securityhub/latest/userguide/ecr-controls.html
It is `[ECR.2]`

**Comment by peterwoodworth** [comment]
Thanks, we don't necessarily conform to security hub recommendations I have relabeled this as a feature request.

I don't know of any downsides, and you're right this is enabled in our bootstrap template. But also, it's not enabled by default in our [construct](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ecr.Repository.html#imagetagmutability)

Regardless, thanks for the PR. We can consider it and get back to you

**Comment by tenjaa** [comment]
I put it as a bug because I saw that in the past, the CDK team merged [a PR](https://github.com/aws/aws-cdk/pull/24175) explicitly to fix a Security Hub finding.

Would you be more open to a PR to make in configurable?
