### ISSUE TITLE
(lambda): (CDK lambdas still using node16)

### ISSUE THREAD

**Issue by Mahdi-Malekan** [aws/aws-cdk#26654]
### Describe the bug

Since https://github.com/aws/aws-cdk/releases/tag/v2.87.0 CDK lambda runtime should be using node 18 runtime.

We are seeing some runtimes still using node 16 e.g. EC2 VPC restrictDefaultSecurityGroup lambda. (there might be more)
https://github.com/aws/aws-cdk/blob/v2-release/packages/aws-cdk-lib/aws-ec2/lib/vpc.ts#L1703
![image](https://github.com/aws/aws-cdk/assets/141637084/b19faaab-1362-41a3-a38a-426dd90029d0)

### Expected Behavior

Node 18 runtime should be used in all CDK generated lambdas

### Current Behavior

Node 16 is being used in some CDK generated lambdas

### Reproduction Steps

This is autogenerated by CDK

### CDK CLI Version

2.89

### Node.js Version

16

### OS

Windows

### Language

Typescript

**Comment by peterwoodworth** [comment]
Our latest release closed [this issue](https://github.com/aws/aws-cdk/issues/26461), please see `2.90.0`

**Comment by Mahdi-Malekan** [comment]
@peterwoodworth Thanks for the reply.
If you please follow the link I've provided, you can see that it's for the latest release (2.90.0) and it hasn't fixed yet.
Thanks
