### ISSUE TITLE
(stepfunctions-tasks): InputMode for SageMaker does not support FastFile

### ISSUE THREAD

**Issue by straygar** [aws/aws-cdk#26653]
### Describe the feature

* [InputMode enum](https://github.com/aws/aws-cdk/blob/v2.90.0/packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/sagemaker/base-types.ts#L458)
* [SageMaker API param](https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_Channel.html#sagemaker-Type-Channel-InputMode)

### Use Case

The feature can lead to performance gains when your training job works on a subset of the data that lives under the prefix, with little implementation effort.

### Proposed Solution

Add 'FastFile' to the enum

### Other Information

I haven't checked whether the SFN integration with the SageMaker API call supports this or throws an error, but other API fields are fully supported now so I don't see why not.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.90.0

### Environment details (OS name and version, etc.)

Mac OS

**Comment by peterwoodworth** [comment]
Yes, makes sense 👍🏻 Check out our [contributing guide](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) if you're interested in helping out with this

**Comment by straygar** [comment]
@tmyoda Thanks for picking this up, Tomoya! 🎉
