### ISSUE TITLE
aws-cdk-lib: TypeError: (displayHint || "TOKEN").replace is not a function

### ISSUE THREAD

**Issue by amwy-manishs** [aws/aws-cdk#26667]
### Describe the bug

We are trying to use aws-cdk-lib to create a layer-1 stack. 

At deployment time our cdk deploy gives the following error stack:

2023-08-07 14:06:36.665  ERROR [main   printFatalErrorUponExit] /codebuild/output/src1705055176/src/github.com/AmwayShared/amcontroller-apse1/infra-as-code/cdk/ams-infra/prod02/layer-1/node_modules/aws-cdk-lib/core/lib/private/token-map.js:1
--
111 | "use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.TokenMap=void 0;const token_1=require("../token"),encoding_1=require("./encoding"),glob=global,STRING_SYMBOL=Symbol.for("@aws-cdk/core.TokenMap.STRING"),LIST_SYMBOL=Symbol.for("@aws-cdk/core.TokenMap.LIST"),NUMBER_SYMBOL=Symbol.for("@aws-cdk/core.TokenMap.NUMBER");class TokenMap{constructor(){this.stringTokenMap=new Map,this.numberTokenMap=new Map,this.tokenCounter=Math.floor(Math.random()*10)}static instance(){return glob.__cdkTokenMap\|\|(glob.__cdkTokenMap=new TokenMap),glob.__cdkTokenMap}registerString(token,displayHint){return cachedValue(token,STRING_SYMBOL,()=>{const key=this.registerStringKey(token,displayHint);return`${encoding_1.BEGIN_STRING_TOKEN_MARKER}${key}${encoding_1.END_TOKEN_MARKER}`})}registerList(token,displayHint){return cachedValue(token,LIST_SYMBOL,()=>{const key=this.registerStringKey(token,displayHint);return[`${encoding_1.BEGIN_LIST_TOKEN_MARKER}${key}${encoding_1.END_TOKEN_MARKER}`]})}registerNumber(token){return cachedValue(token,NUMBER_SYMBOL,()=>this.registerNumberKey(token))}tokenFromEncoding(x){if(token_1.isResolvableObject(x))return x;if(typeof x=="string")return this.lookupString(x);if(Array.isArray(x))return this.lookupList(x);if(token_1.Token.isUnresolved(x))return x}lookupString(s){const fragments=this.splitString(s);if(fragments.tokens.length>0&&fragments.length===1)return fragments.firstToken}lookupList(xs){if(xs.length!==1)return;const fragments=encoding_1.TokenString.forListToken(xs[0]).split(this.lookupToken.bind(this));if(fragments.length===1)return fragments.firstToken}splitString(s){return encoding_1.TokenString.forString(s).split(this.lookupToken.bind(this))}lookupNumberToken(x){const tokenIndex=encoding_1.extractTokenDouble(x);if(tokenIndex===void 0)return;const t=this.numberTokenMap.get(tokenIndex);if(t===void 0)throw new Error("Encoded representation of unknown number Token found");return t}lookupToken(key){const token=this.stringTokenMap.get(key);if(!token)throw new Error(`Unrecognized token key: ${key}`);return token}registerStringKey(token,displayHint){const counter=this.tokenCounter++,key=`${(displayHint\|\|"TOKEN").replace(new RegExp(`[^${encoding_1.VALID_KEY_CHARS}]`,"g"),".")}.${counter}`;return this.stringTokenMap.set(key,token),key}registerNumberKey(token){const counter=this.tokenCounter++,dbl=encoding_1.createTokenDouble(counter);return this.numberTokenMap.set(counter,token),this.stringTokenMap.set(`${dbl}`,token),dbl}}exports.TokenMap=TokenMap;function cachedValue(x,sym,prod){let cached=x[sym];return cached===void 0&&(cached=prod(),Object.defineProperty(x,sym,{value:cached})),cached}
112 | ^
113 | 2023-08-07 14:06:36.666  ERROR [main   printFatalErrorUponExit] TypeError: (displayHint \|\| "TOKEN").replace is not a function
114 | at TokenMap.registerStringKey (/codebuild/output/src1705055176/src/github.com/AmwayShared/amcontroller-apse1/infra-as-code/cdk/ams-infra/prod02/layer-1/node_modules/aws-cdk-lib/core/lib/private/token-map.js:1:2178)
115 | at /codebuild/output/src1705055176/src/github.com/AmwayShared/amcontroller-apse1/infra-as-code/cdk/ams-infra/prod02/layer-1/node_modules/aws-cdk-lib/core/lib/private/token-map.js:1:665
116 | at cachedValue (/codebuild/output/src1705055176/src/github.com/AmwayShared/amcontroller-apse1/infra-as-code/cdk/ams-infra/prod02/layer-1/node_modules/aws-cdk-lib/core/lib/private/token-map.js:1:2602)
117 | at TokenMap.registerString (/codebuild/output/src1705055176/src/github.com/AmwayShared/amcontroller-apse1/infra-as-code/cdk/ams-infra/prod02/layer-1/node_modules/aws-cdk-lib/core/lib/private/token-map.js:1:613)
118 | at Function.asString (/codebuild/output/src1705055176/src/github.com/AmwayShared/amcontroller-apse1/infra-as-code/cdk/ams-infra/prod02/layer-1/node_modules/aws-cdk-lib/core/lib/token.js:1:1244)
119 | at ServicePrincipalToken.toString (/codebuild/output/src1705055176/src/github.com/AmwayShared/amcontroller-apse1/infra-as-code/cdk/ams-infra/prod02/layer-1/node_modules/aws-cdk-lib/aws-iam/lib/principals.js:1:16993)
120 | at ServicePrincipal.get policyFragment [as policyFragment] (/codebuild/output/src1705055176/src/github.com/AmwayShared/amcontroller-apse1/infra-as-code/cdk/ams-infra/prod02/layer-1/node_modules/aws-cdk-lib/aws-iam/lib/principals.js:1:8633)
121 | at PolicyStatement.addPrincipals (/codebuild/output/src1705055176/src/github.com/AmwayShared/amcontroller-apse1/infra-as-code/cdk/ams-infra/prod02/layer-1/node_modules/aws-cdk-lib/aws-iam/lib/policy-statement.js:2:1427)
122 | at new PolicyStatement (/codebuild/output/src1705055176/src/github.com/AmwayShared/amcontroller-apse1/infra-as-code/cdk/ams-infra/prod02/layer-1/node_modules/aws-cdk-lib/aws-iam/lib/policy-statement.js:1:1570)
123 | at ServicePrincipal.addToAssumeRolePolicy (/codebuild/output/src1705055176/src/github.com/AmwayShared/amcontroller-apse1/infra-as-code/cdk/ams-infra/prod02/layer-1/node_modules/aws-cdk-lib/aws-iam/lib/principals.js:1:2740)
124 |  
125 | Subprocess exited with error 1

### Expected Behavior

DeploySynth should happen

### Current Behavior

It throws exception while cdk synth & deploy 

### Reproduction Steps

n/a

### Possible Solution

n/a

### CDK CLI Version

2.50.0

### Framework Version

2.50.0

### Node.js Version

v16.14.0

### OS

Linux

### Language

Typescript

### Language Version

4.9.4

**Comment by pahud** [comment]
Can you provide the smallest code that reproduces this issue?
