### ISSUE TITLE
(aws-autoscaling/cfn-resource-policy): (maxBatchSize is 100 which is too small, we want maxBatchSize dynamically update by ASG size)

### ISSUE THREAD

**Issue by chensy-aws** [aws/aws-cdk#26663]
### Describe the feature

Since most ASG scale with percentage of instance in use. So it is make more sense to use maxBatchSizeInPercentage instead of just maxBatchSize.

Also, the maxBatchSize upper limit is 100 which is still small in our usage, we have a ASG with more than 4000+ instance and 10%  can be replace at a time. So request to increase the upper limit

### Use Case

When RollingUpdate a large ASG, the update time is too long which decrease the deployment quite a lot

### Proposed Solution

Introduce maxBatchSizeInPercentage as on RollingUpdate policy and increase the upper limit for maxBatchSize.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.73

### Environment details (OS name and version, etc.)

AL2

**Comment by chensy-aws** [comment]
This greatly impact our prod pipeline deployment speed when we need a RollingUpdate.

**Comment by peterwoodworth** [comment]
CfnResourcePolicy in Autoscaling? Could you please link to the API reference page of the construct you are referring to?

**Comment by peterwoodworth** [comment]
OK I see https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.CfnAutoScalingRollingUpdate.html

This is handled by CloudFormation, we just create the template. Please report this issue at the [CloudFormation Coverage Roadmap](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues), CDK will automatically support this when CloudFormation does.
