### ISSUE TITLE
CDK Pipelines: broken link

### ISSUE THREAD

**Issue by matthiasgubler** [aws/aws-cdk#26662]
### Describe the issue

Broken link to original API found:
https://github.com/aws/aws-cdk/blob/main/packages/@aws-cdk/pipelines/ORIGINAL_API.md

Should probably be: 
https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/pipelines/ORIGINAL_API.md

Where it states:
```
The README for the original API, as well as a migration guide, can be found in [our GitHub repository](https://github.com/aws/aws-cdk/blob/main/packages/@aws-cdk/pipelines/ORIGINAL_API.md).
```

### Links

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.pipelines-readme.html
https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/pipelines/README.md

**Comment by peterwoodworth** [comment]
Thanks, consolidating this issue here https://github.com/aws/aws-cdk/issues/24958
