### ISSUE TITLE
EFS: Lookup for filesystems by name

### ISSUE THREAD

**Issue by Balaji-JBC** [aws/aws-cdk#26661]
### Describe the feature

Whenever we want to use an existing EFS, we have to refer it by arn or ID. Why not have a look up that returns list of filesystems and we can continue with it

### Use Case

First time i deploy, i expect the EFS to be created fresh. Second time when i deploy a stack, i want to code like if this filesystem with the given name already exists, use it, like that. But not able to do as as arn/filesystemid is mandatory

### Proposed Solution

Have a lookup function which returns array of file systems available with the given name

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.63.2

### Environment details (OS name and version, etc.)

MacOS Ventura 13.4.1

**Comment by peterwoodworth** [comment]
> First time i deploy, i expect the EFS to be created fresh. Second time when i deploy a stack, i want to code like if this filesystem with the given name already exists, use it, like that.

I'm not sure I understand, if you want to create a new FileSystem and have your stack control that FileSystem, then you want to use `new FileSystem(...)`.  Also, how would a list of FileSystems be used exactly especially in this use case?

**Comment by Balaji-JBC** [comment]
Hi,
I would like to have a cdk code as follows

1. Define a file system configuration with a file_system_name
2. If the file_system_name doesn't already exist, create a new one.
3. else if the file_system_name already exists, get that file system, modify it's properties if needed and deploy

since, file_system_name is not unique, I was expecting a function that returns array of file_system having the given file_system_name and I can work accordingly on them

**Comment by peterwoodworth** [comment]
You need to either have your stack manage a resource (`new XXX`), or create a proxy class for an existing resource to pass that information into resources your stack will manage (`construct.fromXxx`). You cannot have both at once while still using CDK the way it was meant to be used
