### ISSUE TITLE
(aws-cdk-lib/aws-ecs-patterns): (use exist VPC for ApplicationLoadBalancedFargateService error)

### ISSUE THREAD

**Issue by JiaTingYefei** [aws/aws-cdk#26660]
### Describe the bug

When I tried use an exist VPC to create ECS cluster and ApplicationLoadBalancedFargateService, I got an error:
Error: There are no 'Public' subnet groups in this VPC. Available types: Deprecated_Private_NAT,Private,Deprecated_Private

The VPC has 2 public subnet and 2 private subnet.

Code below:
```typescript
this.vpc = ec2.Vpc.fromVpcAttributes(this, `Vpc-carbon-mgt`, {
      vpcId: 'vpc-0a2d4755',
      availabilityZones: Fn.getAzs(),
      privateSubnetIds: 'subnet-042872beda,subnet-0f86502'.split(',')
})

this.cluster = new Cluster(this, 'ECSCluster', {
        vpc: this.vpc,
        containerInsights: true,
      });


 const metabaseService = new ApplicationLoadBalancedFargateService(this, 'MetaBase-Service', {
            platformVersion: FargatePlatformVersion.VERSION1_4,
            cluster: props.cluster,
            // taskSubnets: {subnets: [ec2.Subnet.fromSubnetId(this, '01af7912cecd', 'subnet-01af794ecd'),ec2.Subnet.fromSubnetId(this, '0e1284c734f069', 'subnet-0e1282f4f069')]},
            cpu: 1024,
            memoryLimitMiB: 4096,
            taskImageOptions: {
                containerPort: 3000,
                // image: ContainerImage.fromEcrRepository(repository, IdpConfig.ECR_METABASE_IMAGE_TAG),
                image: ContainerImage.fromRegistry('metabase/metabase:latest'),
                environment: {
                    'MB_DB_TYPE': 'mysql',
                },
            },
            desiredCount: 1,
            circuitBreaker: { rollback: true },
            healthCheckGracePeriod: Duration.minutes(3),
            listenerPort: IdpConfig.ALB_PORT
        });
``` 

### Expected Behavior

Create ApplicationLoadBalancedFargateService in an exist VPC.

### Current Behavior

Can not create ApplicationLoadBalancedFargateService in an exist VPC.

### Reproduction Steps

NA

### CDK CLI Version

2.90.0 

### Node.js Version

v18.12.1

### OS

Amazon Linux2

### Language

Typescript

**Comment by peterwoodworth** [comment]
You aren't defining the public subnets in `fromVpcAttributes`, so it thinks there are no public subnets. Either include them in this import, or use `fromLookup()` instead to actually fetch the information from your account
