### ISSUE TITLE
(cloudwatch): add validation for metric id field on CfnAlarm

### ISSUE THREAD

**Issue by wilhen01** [aws/aws-cdk#26674]
### Describe the feature

When creating alarms via the L1 construct, it's possible to create an alarm which is totally valid according to CDK but fails to deploy with a cryptic error as follows:

`Invalid metrics list (Service: AmazonCloudWatch; Status Code: 400; Error Code: ValidationError; Request ID: 980ecb87-eb02-4eb8-80f3-dfe53d25f442; Proxy: null)`

This is caused by metric Ids failing validation (see CloudFormation docs [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudwatch-alarm-metricdataquery.html#cfn-cloudwatch-alarm-metricdataquery-id))

> Id
> A short name used to tie this object to the results in the response. This name must be unique within a single call to GetMetricData. If you are performing math expressions on this set of data, this name represents that data and can serve as a variable in the mathematical expression. **The valid characters are letters, numbers, and underscore. The first character must be a lowercase letter.**

It would be great if CDK validated this field and caught bad IDs up front. 

Example CDK code which causes this kind of deployment error:

```
   new CfnAlarm(this, '4xxErrorAlarm', {
      alarmDescription: 'High percentage of 4xx errors vs. total calls',
      metrics: [
        {
          id: 'percentage-of-4xx-errors', // id includes hyphens - invalid
          label: '% of total calls that receive 4xx response',
          expression: '(4xxErrors / totalCalls) * 100',
          returnData: true
        },
        {
          id: '4xxErrors', // id doesn't start with a lowercase letter - invalid
          metricStat: {
            metric: {
              namespace: 'AWS/ApiGateway',
              metricName: '4XXError',
              dimensions: [{ name: 'ApiName', value: this.restApi.restApiName }]
            },
            stat: 'Average',
            period: 300
          },
          returnData: false
        },
        {
          id: 'totalCalls',
          metricStat: {
            metric: {
              namespace: 'AWS/ApiGateway',
              metricName: 'Count',
              dimensions: [{ name: 'ApiName', value: this.restApi.restApiName }]
            },
            stat: 'Average',
            period: 300
          },
          returnData: false
        }
      ],
      comparisonOperator: ComparisonOperator.GREATER_THAN_OR_EQUAL_TO_THRESHOLD,
      evaluationPeriods: 1,
      datapointsToAlarm: 1,
      threshold: 10,
      treatMissingData: TreatMissingData.IGNORE
    });
```

### Use Case

Better developer experience when creating alarms

### Proposed Solution

Add validation in CDK

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.87.0

### Environment details (OS name and version, etc.)

Mac OS

**Comment by peterwoodworth** [comment]
L1 resources are defining L1 resources exactly as you'd like them in the CloudFormation template. If it follows the API model that CloudFormation allows, then we will allow it. We can't do any validation on these since we don't own these resources and cannot programmatically know details like this
