### ISSUE TITLE
aws-eks: Add properties from IHelmChartOptions to HelmChart construct

### ISSUE THREAD

**Issue by pergardebrink** [aws/aws-cdk#26678]
### Describe the feature

I would like the helm chart properties (at least: chart, repository, version) to be available in the HelmChart construct after instantiation.

### Use Case

I was looking at writing an aspect that I wanted to use to inspect all helm charts added in our CDK stacks

### Proposed Solution

Add and populate the properties in the HelmChart 
```
export class HelmChart extends Construct {
  public abstract readonly chart: string;
  public abstract readonly repository: string;
  public abstract readonly version: string;
  public abstract readonly chartAsset: Asset;
  ....
```

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.90.0

### Environment details (OS name and version, etc.)

Windows

**Comment by peterwoodworth** [comment]
If having the properties exposed will help for some use cases then it makes sense

**Comment by davidcosc** [comment]
Hi @peterwoodworth,
this is my first contribution attempt.
I interpreted the desired change as a refactor since there seem to be no changes to the generated CloudFormation or any behavioral changes that might impact synthesis. At least as far as I know of. I hope i didn't miss anything.
