### ISSUE TITLE
aws-cdk-lib: unmaintained transitive dependency with critical vulnerabilities

### ISSUE THREAD

**Issue by caseytoomey** [aws/aws-cdk#26677]
### Describe the bug

Similar to this issue with aws-cdk: https://github.com/aws/aws-cdk/issues/26417

aws-cdk-lib has a dependency on @aws-cdk/asset-node-proxy-agent-v5, which includes a layer containing vm2. vm2 has critical vulnerabilities and is no longer maintained. This doesn't seem to get picked up by yarn or npm audit.

Not sure if this is the best spot for this issue but I wasn't able to directly create an issue for @aws-cdk/asset-node-proxy-agent-v5 on GitHub.

### Expected Behavior

No usage of proxy-agent v5 / vm2.

### Current Behavior

proxy-agent v5 is used which has reliance on the vulnerable vm2 package.

### Reproduction Steps

n/a

### Possible Solution

Update the asset to use proxy agent 6.3.0

### CDK CLI Version

2.90.0

### Node.js Version

18

### OS

Linux

### Language

Typescript

**Comment by haydster7** [comment]
Would be fixed by updating dependency to newly release (3 days ago) [node-proxy-agent-v6v2.0.1](https://github.com/cdklabs/awscdk-asset-node-proxy-agent/releases/tag/node-proxy-agent-v6v2.0.1)

**Comment by rix0rrr** [comment]
Fixed by https://github.com/aws/aws-cdk/pull/26722
