### ISSUE TITLE
AWS-Lambda: Sharing Lambda bucket between accounts

### ISSUE THREAD

**Issue by Ajris** [aws/aws-cdk#26684]
### Describe the feature

Hi,
Currently in CDK it is impossible to share values between the accounts/region (limitation of cloudformation). It is quite usual setup that there are couple of separate environments (1 shared with S3 bucket for Lambda code & ECR repositories, 1 dev account for application that uses those repositories and 1 prod account that is almost the same as the main one).

I suggest changing the implementation of S3Code or even adding the new implementation like S3CrossAccountCode, where we could provide the additional parameters like aws account so that it will be utilised by the Stack.

### Use Case

In the current implementation of passing the code in the "new aws_lambda.Function", if we want to use the code from S3 bucket, we have to provide directly the object IBucket (from which only bucket name is taken). It limits the possibility of using bucket and ECR in another account (we cannot pass the object from one stack in one account to another account in CDK).

### Proposed Solution

I found code for the S3Code here:
https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-lambda/lib/code.ts#L215

Adding additional implementation based on this (and probably extending the configuration a bit of interface CodeConfig to add the account number) should be sufficient to solve it. 

TBH, I would be happy to try out implementing it. (if the suggested solution is not enough, please clarify what is missing, so I can adjust it for the CDK)

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.88.0

### Environment details (OS name and version, etc.)

Ubuntu 22.04, Typescript

**Comment by peterwoodworth** [comment]
When you pass in the bucket to `Code.fromBucket`, you can [specify the account when importing the bucket](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_s3.BucketAttributes.html). Does this help?

**Comment by Ajris** [comment]
Yes, it works. Sorry for trouble :) I was hoping that I dont have to explicitly provide the string values, but I could someohw just reference it in the CDK by passing the bucket. Thanks!
