### ISSUE TITLE
aws_ecs: docker volume autoprovision parameter document do not match cdk behavior

### ISSUE THREAD

**Issue by HangJiaKolmostar** [aws/aws-cdk#26697]
### Describe the issue

in https://docs.aws.amazon.com/AmazonECS/latest/developerguide/docker-volumes.html 
the doc of autoprovision param says："If this value is true, the Docker volume is created if it does not already exist. This field is only used if the scope is shared. If the scope is task then this parameter must either be omitted or set to false."

but when i use scope="task" , autoprovison=False in code, when deploy,  the error message says

 ❌  XXX-my-app-name-XXX failed: Error: The stack named XXX failed to deploy: UPDATE_ROLLBACK_COMPLETE: Resource handler returned message: "Invalid request provided: Create TaskDefinition: When 'scope' parameter is 'task', 'autoprovision' must either not be specified or set to 'True'. (Service: AmazonECS; Status Code: 400; Error Code: ClientException; Request ID: XXXXXXX; Proxy: null)" (RequestToken:XXXXXX, HandlerErrorCode: InvalidRequest)
    at FullCloudFormationDeployment.monitorDeployment (/usr/local/lib/node_modules/aws-cdk/lib/index.js:426:10236)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.deployStack2 [as deployStack] (/usr/local/lib/node_modules/aws-cdk/lib/index.js:429:153208)
    at async /usr/local/lib/node_modules/aws-cdk/lib/index.js:429:136985

the doc says it should be set to false, the error message says it should set to true

### Links

https://docs.aws.amazon.com/AmazonECS/latest/developerguide/docker-volumes.html

**Comment by peterwoodworth** [comment]
Are you using CDK? If you're not, you should provide feedback on this docpage you linked

**Comment by HangJiaKolmostar** [comment]
> 

yes, of course Im using cdk.
the code is 
`

    volume_name = volume_config['name']
    destroy = volume_config.get('destroy', False)
    task.add_volume(
        name=volume_name,
        docker_volume_configuration=ecs.DockerVolumeConfiguration(
            scope=ecs.Scope.TASK if destroy else ecs.Scope.SHARED,
            autoprovision=not destroy,
            driver='local'
        )
    )
`
the doc in https://docs.aws.amazon.com/AmazonECS/latest/developerguide/docker-volumes.html#specify-volume-config
describe that i should use autoprovison=False, but cdk error told me that i should use autovison=True

<img width="1040" alt="image" src="https://github.com/aws/aws-cdk/assets/137740577/6b354f77-7c39-4ca0-ae7f-e59dda5171e3">

**Comment by peterwoodworth** [comment]
None of the errors you're running into are rooted in CDK. _Our_ documentation doesn't state anything incorrect, and the error message isn't coming from us - but rather CloudFormation. So, I'm not sure there's anything we can do to help clear this up in the docs/error message. Like I mentioned before, if you have docs feedback, report that on the docs page itself. And if you want to reach out to CloudFormation, create an issue [here](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues)
