### ISSUE TITLE
(aws-msk-alpha): (add vpc connectivity interface to msk-alpha construct)

### ISSUE THREAD

**Issue by fridgerator** [aws/aws-cdk#26690]
### Describe the feature

[VPC Connectivity](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_msk.CfnCluster.VpcConnectivityProperty.html) exists as a part of the L1 [CfnCluster](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_msk.CfnCluster.html) construct, however these props are not exposed to [aws-msk-alpha Cluster](https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/aws-msk-alpha/lib/cluster.ts).  This feature would add an interface for the Vpc Connectivity props, to be passed down to the underlying CfnCluster.

### Use Case

The current solution is to create a new MSK Cluster then use a custom resource to make api calls that enable VPC Connectivity , which can take a long time.  It would be beneficial if a cluster could be created with this already enabled via the aws-msk-alpha construct.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.90.0

### Environment details (OS name and version, etc.)

Mac OS Ventura, Typescript

**Comment by peterwoodworth** [comment]
Thanks for the report, makes sense 👍🏻 

Note that you can use [escape hatches](https://docs.aws.amazon.com/cdk/v2/guide/cfn_layer.html) to make use of these L1 properties without our explicit support

**Comment by fridgerator** [comment]
Actually this may not be supported.

I tried:

```javascript
const cluster = new msk.Cluster...
const cfnCluster = cluster.node.defaultChild as CfnCluster;
cfnCluster.addOverride("Properties.BrokerNodeGroupInfo.ConnectivityInfo.VpcConnectivity.ClientAuthentication.Sasl.Iam.Enabled", true)
cfnCluster.addOverride("Properties.BrokerNodeGroupInfo.ConnectivityInfo.VpcConnectivity.ClientAuthentication.Tls.Enabled", true)
```

And when I deployed I got a 400 error:

`When creating a cluster, all vpcConnectivity auth schemes must be disabled ('enabled' : false). You can enable auth schemes after the cluster is created. (Service: Kafka, Status Code: 400, Request ID: xxxx) 'vpcConnectivity.clientAuthentication'" (RequestToken: xxxx, HandlerErrorCode: InvalidRequest)`

**Comment by peterwoodworth** [comment]
Hmm you may want to reach out to the [CloudFormation coverage roadmap](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues) in that case

**Comment by dobeerman** [comment]
I want to connect Amazon Data Firehose to the existing MSK Cluster and it requires this option as turned on. I could not find any configuration aside manual intervention. But, I'm afraid, with manual intervention next deployment would override this settings back.
