### ISSUE TITLE
`codebuild`: Arrays are not preserved between commands

### ISSUE THREAD

**Issue by BastiQ** [aws/aws-cdk#26694]
### Describe the bug

When using `LinuxArmBuildImage` with the docker image, `public.ecr.aws/sam/build-python3.9:latest-arm64` and buildspec version 0.2, I run into the issue that arrays are not being preserved between commands.

According to the [docs](https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-cmd.html#:~:text=In%20buildspec%20version%200.1%2C%20CodeBuild%20runs%20each%20Shell%20command%20in%20a%20separate%20instance%20in%20the%20build%20environment.%20This%20means%20that%20each%20command%20runs%20in%20isolation%20from%20all%20other%20commands.) this should only happen with buildspec version 0.1 and be [resolved](https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-cmd.html#:~:text=To%20get%20around%20this%20limitation%2C%20we%20recommend%20that%20you%20use%20version%200.2%2C%20which%20solves%20this%20issue.) in version 0.2.

The weird thing is, that other variables are preserved, and array variables can be looped over if the command is in the same line (see examples below).

This, btw. doesn't happen if I use `LinuxBuildImage` with `public.ecr.aws/sam/build-python3.9:latest` (no arm image).

I assume this is a bug, as arm support has just recently ([v2.88.0](https://github.com/aws/aws-cdk/releases/tag/v2.88.0), https://github.com/aws/aws-cdk/pull/26121, https://github.com/aws/aws-cdk/commit/f522796426a0d9526fae99330784fff9bdb67740) been added.

### Expected Behavior

-

### Current Behavior

-

### Reproduction Steps

```python
from aws_cdk import aws_codebuild as codebuild
# ...
example_codebuild_project = codebuild.Project(
    self,
    "EFSPackageInstallerProject",
    project_name="EFSPackageInstallerProject",
    description="Installs Python packages on EFS for use in model serving Lambda",
    build_spec=codebuild.BuildSpec.from_object(
        {
            "version": "0.2",
            "phases": {
                "build": {
                    "commands": [
                        'my_array=("first" "second" "third" "fourth")',
                        'for item in "${my_array[@]}"; do echo "$item" ; done',
                        # → empty outputs
                        'my_array=("first" "second" "third" "fourth"); for item in "${my_array[@]}"; do echo "$item" ; done',
                        # Outputs:
                        # first
                        # second
                        # third
                        # fourth

                        'myvar=hello; echo $myvar',
                        # outputs: hello
                        'myvar=hello',
                        'echo $myvar',
                        # outputs: hello
                    ]
                }
            },
        }
    ),
    environment=codebuild.BuildEnvironment(
        build_image=codebuild.LinuxArmBuildImage.from_docker_registry(
            f"public.ecr.aws/sam/build-python3.9:latest-arm64"
        ),
        compute_type=codebuild.ComputeType.SMALL,
        privileged=True,
    ),
)
```

### CDK CLI Version

2.90.0 (build 8c535e4)

### Node.js Version

v16.16.0

### OS

MacOS

### Language

Python

### Language Version

3.9

**Comment by peterwoodworth** [comment]
What makes you think this is an issue with CDK, can you identify a misconfigured option in the synthesized template?

**Comment by BastiQ** [comment]
Hey Peter, not sure if this is an issue with CDK. I thought it would make sense since ARM support was just recently added. Let me know where else I can report the issue. It takes some time to figure out that such a basic thing is not working, so I'm just trying to create awareness and potentially help others not to run into it. Feel free to close if the issue is not with CDK.

**Comment by peterwoodworth** [comment]
Yeah I don't see any explicit issues with the template. If you're able to test this same setup in the console to verify that it's not an issue with the service not fixing this particular case of the issue, that would be very helpful.

**Comment by BastiQ** [comment]
Sorry, but I don't have the time for further investigation now. I also don't feel particularly excited about fixing AWS services for them. For anyone running into the same issue, just use multi-line commands. E.g.:
```python
from aws_cdk import aws_codebuild as codebuild
# ...
example_codebuild_project = codebuild.Project(
    self,
    "EFSPackageInstallerProject",
    project_name="EFSPackageInstallerProject",
    description="Installs Python packages on EFS for use in model serving Lambda",
    build_spec=codebuild.BuildSpec.from_object(
        {
            "version": "0.2",
            "phases": {
                "build": {
                    "commands": [
                        """echo "Using an example array";
                        my_array=("first" "second" "third" "fourth");
                        for item in "${my_array[@]}"; do 
                            echo "$item";
                        done""",
                    ]
                }
            },
        }
    ),
    environment=codebuild.BuildEnvironment(
        build_image=codebuild.LinuxArmBuildImage.from_docker_registry(
            f"public.ecr.aws/sam/build-python3.9:latest-arm64"
        ),
        compute_type=codebuild.ComputeType.SMALL,
        privileged=True,
    ),
)
```

**Comment by peterwoodworth** [comment]
Yeah to put it simply - if it is using the correct image after you deploy, then this is almost certainly a service issue, which unfortunately I can't help much with. I submitted a ticket internally for this (P96948151), will provide an update when one becomes available

**Comment by peterwoodworth** [comment]
@BastiQ the service team let me know that arrays are not supported in buildspec command yet - From the team: 

> In order to workaround, try putting that in a script file and invoke that in buildspec, which should work.

**Comment by BastiQ** [comment]
Good to know, thanks for the update! Maybe something worth adding to the docs somewhere.

**Comment by peterwoodworth** [comment]
I'll forward this feedback onto them 🙂
