### ISSUE TITLE
(ec2/iam): custom resources using Node16/SdkV2

### ISSUE THREAD

**Issue by MrArnoldPalmer** [aws/aws-cdk#26708]
### Describe the bug

The IAM OIDC and EC2 VPC restrict default security group custom resources still use Node16 and SdkV2. These weren't changed because they didn't use the `builtInCustomResourceNodeRuntime` mechanisms.

### Expected Behavior

Use Node18 as the custom resources runtime which necessitates also using sdkv3 in the handler.

### Current Behavior

Node16 is used.

### Reproduction Steps

Provision these custom resources.

### CDK CLI Version

2.90.0

### Node.js Version

18

### OS

MacOS

### Language

Typescript

**Comment by Mahdi-Malekan** [comment]
There are other places which still using Node16
https://github.com/aws/aws-cdk/issues/26654
Please fix them all ✌️
