### ISSUE TITLE
aws-cdk-lib.stepfunctions: Add Non-trivial Examples to Map Documentation

### ISSUE THREAD

**Issue by navneethc** [aws/aws-cdk#26707]
### Describe the issue

The documentation for the Map constructor currently points to using a single Pass state, however this is far from a real-world scenario. (Without intending to be rude, I'd say this is useless.) Recently I was bitten by a few bugs and lost a few hours thanks to the way I arranged the tasks within Map state.

Consider adding an example or two which show how to add more than one state to a Map, and how to proceed from a Map to the outside. And also how to use the `next` methods in such cases.

### Links

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_stepfunctions-readme.html#map

**Comment by anshikam** [comment]
@peterwoodworth @navneethc I would like to take this one up as my first task.

**Comment by peterwoodworth** [comment]
Feel free @anshikam
