### ISSUE TITLE
(cdk diff): Unicode characters not properly recognised by the cdk diff

### ISSUE THREAD

**Issue by johnfox** [aws/aws-cdk#26703]
### Describe the bug

When using unicode characters in the environment variable value the `cdk diff` displays changes even when the content of the env. variable does not change (i.e. when the environment variable defined in the code have the same value as the one already deployed on AWS).   
This was observed on ECS and Lambda services.

### Expected Behavior

The `cdk diff` should not display changes on environment variables content when there is no change.

### Current Behavior

The `cdk diff` displays change on environment variable content even when there is no change to the environmental variable value.

### Reproduction Steps

```typescript
    const taskDefinition = new ecs.FargateTaskDefinition(this, 'TaskDefinition', {
    });

    taskDefinition.addContainer('test-service', {
      image: ecs.ContainerImage.fromRegistry('amazon/amazon-ecs-sample'),
      environment: {
        'TEST_STRING': 'test',
        'TEST_SPECIAL_CHARS': 'test!@#$%^&*()_+',
        'TEST_UNICODE_CHARS': 'test😀',
        'TEST_CURRENCY_CHARS': 'test ¥ $ € £',
      }
    });

    const service = new ecs.FargateService(this, 'Service', {
      cluster,
      taskDefinition,
      serviceName: 'test-service',
      vpcSubnets: { subnets: vpc.privateSubnets },
    });
```
`cdk diff` call result after the stack is deployed and no change made to the code:
```
Stack UnexpectedCharactersInEnvDiffStack
Resources
[~] AWS::ECS::TaskDefinition TaskDefinition TaskDefinitionB36D86D9 replace
 └─ [~] ContainerDefinitions (requires replacement)
     └─ @@ -11,11 +11,11 @@
        [ ]   },
        [ ]   {
        [ ]     "Name": "TEST_UNICODE_CHARS",
        [-]     "Value": "test?"
        [+]     "Value": "test😀"
        [ ]   },
        [ ]   {
        [ ]     "Name": "TEST_CURRENCY_CHARS",
        [-]     "Value": "test ? $ ? ?"
        [+]     "Value": "test ¥ $ € £"
        [ ]   }
        [ ] ],
        [ ] "Essential": true,
```

### Additional Information/Context

The value is correctly set and available in correct form to the ECS container. So I guess the problem is either in the way the DIFF is obtained (saved `version` of the CF template on the AWS side my not support Unicode?).

### CDK CLI Version

2.84.0 (build f7c792f)

### Framework Version

2.84.0

### Node.js Version

18.16.0

### OS

Mac OS X

### Language

Typescript

**Comment by peterwoodworth** [comment]
This was fixed in https://github.com/aws/aws-cdk/pull/25912, you should only need to upgrade to `2.85.0` to see this fixed
