### ISSUE TITLE
(ecr): make validateRepositoryName errors human readable

### ISSUE THREAD

**Issue by scanlonp** [aws/aws-cdk#26715]
### Describe the feature

The current errors say repository names must match a long regex. Make the errors explain why the name was not valid in an understandable way.

### Use Case

Understanding why a repository name is not valid without deciphering regex.

### Proposed Solution

Translate the regex into words in the error messages.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.91.0

### Environment details (OS name and version, etc.)

Mac

**Comment by scanlonp** [comment]
For reference 
https://github.com/aws/aws-cdk/blob/e593229e095b5800a053a0c51903a4f27ccf6228/packages/aws-cdk-lib/aws-ecr/lib/repository.ts#L659-L681

**Comment by pahud** [comment]
Yeah it makes sense to improve the error messages here.
