### ISSUE TITLE
dms: AWS CDK doesn't provide resources to create DMS serverless replications

### ISSUE THREAD

**Issue by maxd** [aws/aws-cdk#26717]
### Describe the bug

The AWS Console has the `AWS DMS` / `Serverless replications` section where I can manually create serverless replications but AWS CDK doesn't provide resources (L1 constructs) for creating them too for AWS CDK).

<img width="1848" alt="Screenshot 2023-08-11 at 11 40 30" src="https://github.com/aws/aws-cdk/assets/27208/429bb26c-e51c-4feb-8cfa-6c3e186205df">

### Expected Behavior

The AWS CDK should provide an L1 construct for creating DMS serverless replication.

### Current Behavior

The AWS CDK doesn't provide an L1 construct for creating DMS serverless replication.

### Reproduction Steps

Look at [official AWS CDK documentation for DMS](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_dms-readme.html) It doesn't have a resource for create a serverless replication.

### Possible Solution

As I understand an L1 construct for [ReplicationConfig](https://docs.aws.amazon.com/dms/latest/APIReference/API_ReplicationConfig.html) Cloud Formation object should be created in AWS CDK library.

### CDK CLI Version

2.91.0

### Node.js Version

16.15.1

### OS

macOS 12.4

### Language

Typescript

**Comment by pahud** [comment]
If L1 construct is not available, it typically means the cloudformation support is still missing.

Looks like what we currently have from cloudformation is [AWS::DMS::ReplicationInstance](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-replicationinstance.html) but it's unclear to me if the serverless instance can be created with that.

**Comment by peterwoodworth** [comment]
It must be new @maxd, in the [most recent cfnspec we merged](https://github.com/aws/aws-cdk/pull/26362/files) this resource wasn't present. However, it is present in the [spec now](https://d1uauaxba7bl26.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json), so it will be part of the next CDK version that has an updated spec.

In the meantime, you can simply use [CfnResource](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.CfnResource.html) to get around this for now
