### ISSUE TITLE
aws-certificatemanager: Bring back/keep DnsValidatedCertificate

### ISSUE THREAD

**Issue by guentherwieser** [aws/aws-cdk#26714]
### Describe the feature

DnsValidatedCertificate has been marked deprecated. The recommended solution is to use Certificate, and provide/use a CertificateValidation implementation. Unfortunately, when using certificates in another region, there is no smooth transition for DnsValidatedCertificates when e.g. the domain name is built using a value from a parameter store of another region.

Also, we cannot use the output of the core stack to feed the domain name value into the certificate stack (this is a recommended solution for many use cases), as we would create a circular reference - we simply need the certificate in the core stack (CloudFront, API Gateway, etc.).

Example: core deployment happens to eu-central-1, for CloudFront the certificate has to go to us-east-1. The domain name to use is built partly from a parameter store value in eu-central-1. When creating a dedicated stack for the certificate, during synth it will fail with 

`Error: Stack "XXXStack" cannot reference {YYYStack/SsmParameterValue:<some-ref>.Parameter[Ref]} in stack "YYYStack". Cross stack references are only supported for stacks deployed to the same account or between nested stacks and their parent stack`

Maybe I'm missing something important here, but I don't see how one will be able to create a Certificate with a domain name where parts of the domain name come from Parameter Store values from another region. Thus, a migration path away from DnsValidatedCertificate does not exist.

### Use Case

Create Certificate in one region with dependencies to values from another region.

### Proposed Solution

Either keep DnsValidatedCertificate, provide a "region" property on Certificate that is independent from the Stack it is bound to, or provide other means to cross-reference parameter store values from another region.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.87.0

### Environment details (OS name and version, etc.)

MacOS, Linux, Windows

**Comment by peterwoodworth** [comment]
See https://github.com/aws/aws-cdk/issues/25343
