### ISSUE TITLE
aws_workspaces: register directory with workspaces

### ISSUE THREAD

**Issue by ruckc** [aws/aws-cdk#26721]
### Describe the feature

In trying to provide a fully automated AWS workspaces, directory deployment is impossible.  I need the ability to register a directory service with workspaces in the CDK.

### Use Case

Currently with AWS-CDK, it is impossible to deploy a Directory Service and new WorkSpaces in the same stack.  The Directory Service has to be registered with the Workspace, and there are no L1 Constructs to do so.

### Proposed Solution

Create a CfnWorkspaceDirectory construct that ties directory service ID.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.90

### Environment details (OS name and version, etc.)

Ubuntu 22.04

**Comment by pahud** [comment]
Can you elaborate more on the details?

Looks like workspace allows you to specify the directory ID

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-workspaces-workspace.html#cfn-workspaces-workspace-directoryid

Can you create the directory first and pass the ID to the workspace?

**Comment by niallwalsh** [comment]
@pahud The problem is not the passing of the ID, the problem is that the directory needs to be registered first in order to be found. There is no process in constructs to do so; it has to be done via CLI commands.

**Comment by ruckc** [comment]
@pahud - my project ended up using terraform where they provide a mechanism to register a directory in Workspaces

**Comment by jhony-ourlegup** [comment]
This still not be implemented
