### ISSUE TITLE
(module name): (short issue description) L2 construct for Step Functions

### ISSUE THREAD

**Issue by lowelljehu** [aws/aws-cdk#26723]
### Describe the feature

Request is to add a nice L2 construct for step functions - @pouemes

### Use Case

Customer is building heavily with CDK and State Machines. They’re running into situations where they can’t see a way to constuct, using cdk, what can be easily defined in a json definition, like a top-level comment on the state machine.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

v2

### Environment details (OS name and version, etc.)

n/a

**Comment by peterwoodworth** [comment]
Check out our [stepfunctions module](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_stepfunctions-readme.html)
