### ISSUE TITLE
(aws-elasticloadbalancingv2): (network-load-balancer-supports-security-groups)

### ISSUE THREAD

**Issue by neilkuan** [aws/aws-cdk#26735]
### Describe the feature

https://aws.amazon.com/tw/about-aws/whats-new/2023/08/network-load-balancer-supports-security-groups/
network load balancer supports security groups.

### Use Case

Supports create NLB with SG via aws cdk L2.

### Proposed Solution

Support securityGroup into NetworkLoadBalancerProps.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.91.0

### Environment details (OS name and version, etc.)

macOS Ventura 13.4.1

**Comment by neilkuan** [comment]
I can use addPropertyOverride() setting SecurityGroups for now.
```ts
const lb = new elasticloadbalancingv2.NetworkLoadBalancer(this, 'nyancatNlb', {
      vpc,
      internetFacing: true,
      crossZoneEnabled: true,
    });
    const ntg80 = lb.addListener('Listener80', { port: 80 });
    ntg80.addTargets('svc80', {
      port: 80,
      targets: [svc],
    });
    const nlbSg = new ec2.SecurityGroup(this, 'NLBSecurityGroup', { vpc, allowAllOutbound: true });
    svc.connections.allowFrom(nlbSg, ec2.Port.tcp(80));
    const cfnlb = (lb.node.defaultChild as elasticloadbalancingv2.CfnLoadBalancer );
    cfnlb.addPropertyOverride('SecurityGroups', [
      nlbSg.securityGroupId,
    ]);
```

**Comment by pahud** [comment]
Awesome @neilkuan ! This is a huge update from NLB! Can't wait to see it in CDK.

**Comment by vumdao** [comment]
Hope to see this release soon!

**Comment by amouly** [comment]
Looking for this feature too! Thanks for documenting it!

**Comment by ZhouLihua** [comment]
For some one who uses CDK python launguage. 
`nlb.node.default_child.add_property_override("SecurityGroups", [
            nlb_sg.security_group_id
        ])`
