### ISSUE TITLE
(custom_resources): How to break a cross-stack dependency

### ISSUE THREAD

**Issue by pb8o** [aws/aws-cdk#26758]
### Describe the bug

Hi, I have 2 stacks where one depends on the custom resource function of another.

**Stack A** has this

```ts
const myProvider = new cr.Provider(this, 'MyProvider', {onEventHandler: myFn});
```

It has an output like (edited):

```ts
MyStack:ExportsOutputFnGetAttMyProviderframeworkonEvent60E6A034ArnCBF1E63C
```

**Stack B** gets passed myProvider as a parameter and has this

```ts
myCR = new core.CustomResource(this, 'Sync', {
            serviceToken: myProvider.serviceToken,
            properties: {...}
}
```

I am now trying to break the relationship between the two, but it I am blocked since there is no direct access to the CDK-generated Lambda.

### Expected Behavior

```
this.exportValue(myProvider);
```

### Current Behavior

```
Error: exportValue: either supply 'name' or make sure to export a resource attribute (like 'bucket.bucketName')
```

### Reproduction Steps

```ts
const myProvider = new cr.Provider(this, 'MyProvider', {onEventHandler: myFn});
```

### Possible Solution

Would it be as easy as exposing this as a property of `Provider`?

https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/custom-resources/lib/provider-framework/provider.ts#L181

### CDK CLI Version

2.89.0

### Node.js Version

18

### OS

Linux

### Language

Typescript

**Comment by pahud** [comment]
It's not clear to me where the error comes from.

```
Error: exportValue: either supply 'name' or make sure to export a resource attribute (like 'bucket.bucketName')
```

Do you mean the `myProvider` is in stack A but `myFn` is in stack B?


```
const myProvider = new cr.Provider(this, 'MyProvider', {onEventHandler: myFn});
```

Can you share the smallest code that represents both stacks and the their content?

**Comment by pb8o** [comment]
Ok while updating the details of the issue I found I do this:

```ts
myProvider.node.addDependency(asg);
```

So maybe I will have to do this in 2 steps?

1. Remove this addDependency call, but no changes to Stack A 
2. Remove the myProvider in Stack B

I will try this out and report back. Maybe I opened this bug too soon.

**Comment by pb8o** [comment]
Ok I made some tiny progress. This is what I am trying to write for breaking the dependency:

```
        // to break the dependency, for the transition
        const ltSyncerFn = new lambda.Function(this, 'Sync Launch Template', {
            memorySize: 128, // MB
            timeout: core.Duration.seconds(60),
            runtime: lambda.Runtime.NODEJS_18_X,
            code: new lambda.InlineCode('foo'),
            handler: 'index.handler',
        });
        const ltSyncProvider = new cr.Provider(this, 'LaunchTemplateSyncProvider', {
            onEventHandler: ltSyncerFn,
        });
        this.exportValue(ltSyncProvider.entrypoint);
```

and this is what I get:

```
lib/imageBuilder.ts:196:41 - error TS2341: Property 'entrypoint' is private and only accessible within class 'Provider'.

196         this.exportValue(ltSyncProvider.entrypoint);
                                            ~~~~~~~~~~
```

Would it make sense to make that property public, so we can keep exporting it?

**Comment by pahud** [comment]
```
const ltSyncProvider = new cr.Provider(this, 'LaunchTemplateSyncProvider', {
            onEventHandler: ltSyncerFn,
        });
        this.exportValue(ltSyncProvider.entrypoint);
```

Why would you export the entrypoint?

It is actually private so you can't export it like that.

https://github.com/aws/aws-cdk/blob/2855da66c7b8fd2def86ff0aa15b524894fd11e1/packages/aws-cdk-lib/custom-resources/lib/provider-framework/provider.ts#L154
