### ISSUE TITLE
certificatemanager: DnsValidatedCertificate resource fails if domain contains uppercase characters

### ISSUE THREAD

**Issue by milesnash-sky** [aws/aws-cdk#26750]
### Describe the bug

Attempting to deploy a stack with a certificatemanager DnsValidatedCertificate resource fails if the domain name contains uppercase characters.

For example:
```typescript
const certificate = new certmngr.DnsValidatedCertificate(
  this,
  "MyCert",
  {
    domainName: "FOO.bar.baz.example.com",
    hostedZone: this.hostedZone,
    region: "us-east-1",
  }
);
```

The above results in the backing custom resource creating a policy for its Lambda function that looks like this:
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "acm:AddTagsToCertificate",
                "acm:DeleteCertificate",
                "acm:DescribeCertificate",
                "acm:RequestCertificate",
                "route53:GetChange"
            ],
            "Resource": "*",
            "Effect": "Allow"
        },
        {
            "Condition": {
                "ForAllValues:StringLike": {
                    "route53:ChangeResourceRecordSetsNormalizedRecordNames": [
                        "*.FOO.bar.baz.example.com"
                    ]
                },
                "ForAllValues:StringEquals": {
                    "route53:ChangeResourceRecordSetsActions": [
                        "UPSERT",
                        "DELETE"
                    ],
                    "route53:ChangeResourceRecordSetsRecordTypes": [
                        "CNAME"
                    ]
                }
            },
            "Action": "route53:changeResourceRecordSets",
            "Resource": "arn:aws:route53:::hostedzone/HOSTED_ZONE_ID",
            "Effect": "Allow"
        }
    ]
}
```

Note that according to [the documentation](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition_operators.html#Conditions_String), `ForAllValues:StringLike` is for "Case-sensitive matching."

However, the Lambda function later calls the route53.changeResourceRecordSets SDK method using the response of an earlier call to acm.describeCertificate SDK method, specifically the value at path response.CertificateDetail.DomainValidationOptions[N].ResourceRecord.Value, and somewhere on its journey to becoming the value of the property, the domain name has been lowercased, i.e. it is `foo.bar.baz.example.com`.

### Expected Behavior

Domain names are (usually) case-insensitive so the policy role should be updated to reflect that.

### Current Behavior

The stack build fails because the lambda doesn't have the permission to call `route53.changeResourceRecordSets` on that resource.  For example:
```
Received response status [FAILED] from custom resource. Message returned: User: arn:aws:sts::[REDACTED]:assumed-role/[REDACTED]/[REDACTED] is not authorized to perform: route53:ChangeResourceRecordSets on resource: arn:aws:route53:::hostedzone/[REDACTED] because no identity-based policy allows the route53:ChangeResourceRecordSets action (RequestId: [REDACTED])
```

### Reproduction Steps

See bug description.

### Possible Solution

Maybe `StringEqualsIgnoreCase`?  Otherwise some other change to the role-building logic.

### CDK CLI Version

2.86.0 (build 1130fab)

### Node.js Version

18.17.0

### OS

macOS Ventura 13.4.1

### Language

Typescript

**Comment by pahud** [comment]
```ts
const certificate = new certmngr.DnsValidatedCertificate(
  this,
  "MyCert",
  {
    domainName: "FOO.bar.baz.example.com",
    hostedZone: this.hostedZone,
    region: "us-east-1",
  }
);
```

I guess we probably should always lowercase the `domainName` in this case. What do you think?

**Comment by milesnash-sky** [comment]
> ```ts
> const certificate = new certmngr.DnsValidatedCertificate(
>   this,
>   "MyCert",
>   {
>     domainName: "FOO.bar.baz.example.com",
>     hostedZone: this.hostedZone,
>     region: "us-east-1",
>   }
> );
> ```
> 
> I guess we probably should always lowercase the `domainName` in this case. What do you think?

Yeah I guess that would be easiest, but only at the point at which it is used to construct the policy role.

**Comment by milesnash-sky** [comment]
I say that because that would hopefully minimise the blast radius of that change.

**Comment by mrgrain** [comment]
Thank you for your reporting this issue!
`DnsValidatedCertificate` is a deprecated construct and, as a result, we are not accepting changes to it anymore. Given that there is also a very easy workaround (pass in the domain name as lower case), I'm going to go ahead and close this issue.
