### ISSUE TITLE
(ec2): add metadata for M7gd, R7gd, C7gd instance types

### ISSUE THREAD

**Issue by funguy-tech** [aws/aws-cdk#26774]
### Describe the feature

As of v2.92.0, we don't yet have C7gd, M7gd, and R7gd instance types available via instance type selection. 

### Use Case

These instance types were announced in July 2023 and are now live for select regions, as seen in [this release](https://aws.amazon.com/blogs/aws/new-amazon-ec2-instances-c7gd-m7gd-and-r7gd-powered-by-aws-graviton3-processor-with-local-nvme-based-ssd-storage/).

### Proposed Solution

Add new instance types to `InstanceType` enum and internal `instanceClassMap`, following the paradigm set by the \*6gd subfamily of instance types.

### Other Information

Proposed solution is #26776 

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.92.0

### Environment details (OS name and version, etc.)

Platform Independent

**Comment by pahud** [comment]
Awesome! Thank you for the PR!
