### ISSUE TITLE
aws-cdk-lib/aws-eks: Cluster fail to deploy with lambda layer v27 and v26

### ISSUE THREAD

**Issue by lmouhib** [aws/aws-cdk#26787]
### Describe the bug

Cluster fail to deploy with error from the customer resource responsible for managing the lifecycle of the cluster. The error is as follow:
```
09:44:24 | CREATE_FAILED        | Custom::AWSCDK-EKS-Cluster                  | Cluster9EE0221C
Received response status [FAILED] from custom resource. Message returned: ProxyAgent is not a constructor
```

If I remove the kubectl layer and rely on the the one part of CDK which is kubectl 1.20, the cluster successfully deploy.

### Expected Behavior

Cluster deploy without issues.

### Current Behavior

Cluster fail to deploy with the following error:

```
09:44:24 | CREATE_FAILED        | Custom::AWSCDK-EKS-Cluster                  | Cluster9EE0221C
Received response status [FAILED] from custom resource. Message returned: ProxyAgent is not a constructor
```

### Reproduction Steps

code is in this [repo](https://github.com/emrspecialistsamer/amazon-emr-on-eks-labs)

Package.json
```
   "aws-cdk-lib": "^2.84.0",
    "@aws-cdk/lambda-layer-kubectl-v27": "^2.0.0",
```

```
import { AwsAuth, CapacityType, CfnAddon, Cluster, KubernetesVersion } from 'aws-cdk-lib/aws-eks';
import { KubectlV27Layer } from '@aws-cdk/lambda-layer-kubectl-v27';

    const kubectl = new KubectlV27Layer(this, 'KubectlLayer');
    
    const eksCluster = new Cluster(this, "Cluster", {
      vpc: vpc,
      clusterName: 'cluster',
      version: KubernetesVersion.V1_27,
      kubectlLayer: kubectl,
    });

```

This will fail with the above errors

### Possible Solution

It might be related to the notice, for the upgrade to node 18.

I tried to deploy with the following dependencies and it works without issues. The only difference is using k8s 1.26 instead of 1.27 because the version is not available in cdk 2.81

```
    "@aws-cdk/lambda-layer-kubectl-v26": "^2.0.0",
    "aws-cdk-lib": "2.81.0",
```

### CDK CLI Version

2.92.0

### Framework Version

2.84.0

### Node.js Version

Node.js v18.12.1.

### OS

macOS

### Language

Typescript

### Language Version

TypeScript 4.9.4

**Comment by peterwoodworth** [comment]
Hey thanks for reporting, [this issue](https://github.com/aws/aws-cdk/issues/26771) was fixed [yesterday](https://github.com/aws/aws-cdk/pull/26782) and should be in our next release
