### ISSUE TITLE
aws_elasticloadbalancingv2: documentation update needed for `CfnLoadBalancer` regarding Security Groups

### ISSUE THREAD

**Issue by unirt** [aws/aws-cdk#26799]
### Describe the issue

In the AWS CDK documentation for `class CfnLoadBalancer (construct)`, the security group description reads:
`[Application Load Balancers] The IDs of the security groups for the load balancer.`  
However, in [the AWS CloudFormation documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-loadbalancer.html), it is stated as:
`[Application Load Balancers and Network Load Balancers] The IDs of the security groups for the load balancer.`  
It seems that the CDK documentation might not be updated to reflect that [the security groups also apply to NLB](https://aws.amazon.com/about-aws/whats-new/2023/08/network-load-balancer-supports-security-groups/) in addition to ALB.  
Can we get this documentation updated to ensure clarity and consistency with CloudFormation's documentation? Thanks.

### Links

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_elasticloadbalancingv2.CfnLoadBalancer.html

**Comment by peterwoodworth** [comment]
This all happens in an automatic process. Either this is a recent change, or the process is blocked for this package for some reason. Regardless, I don't think I can give a timeline here, but thanks for letting us know.

**Comment by tim-finnigan** [comment]
It looks like https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_elasticloadbalancingv2.CfnLoadBalancer.html has since been updated to reflect the requested change, so I'll go ahead and close this issue.
