### ISSUE TITLE
rds: Can't add PostgreSQL read replica with gp3 storage type

### ISSUE THREAD

**Issue by arlampin** [aws/aws-cdk#26803]
### Describe the bug

Trying to add `DatabaseInstanceReadReplica` with gp3 storage type causes the following error when just `maxAllocatedStorage` is defined. And there's no option to add `allocatedStorage`.

```
You must specify both the storage size and iops when modifying the storage size or iops on a DB instance that has iops
```

### Expected Behavior

It should be possible to add `DatabaseInstanceReadReplica` with gp3 storage without errors.

### Current Behavior

Trying to add `DatabaseInstanceReadReplica` causes the following error at the end of process
```
You must specify both the storage size and iops when modifying the storage size or iops on a DB instance that has iops. 
```

### Reproduction Steps

```
new rds.DatabaseInstanceReadReplica(this, 'DatabaseReadReplica', {
  sourceDatabaseInstance: database,
  vpc: vpc,
  instanceType: ec2.InstanceType.of(
    ec2.InstanceClass.M6G,
    ec2.InstanceSize.LARGE,
  ),
  maxAllocatedStorage: 100,
  storageType: StorageType.GP3
});
```

### Possible Solution

Maybe this is caused by gp3 storage inherently having iops even without any explicit configuration?

### CDK CLI Version

2.91.0 (build eea12ea)

### Node.js Version

v18.17.0

### OS

macOS

### Language

Typescript

**Comment by arlampin** [comment]
Seems that https://github.com/aws/aws-cdk/issues/16934#issuecomment-948062070 can be used to work around the problem

**Comment by peterwoodworth** [comment]
Thanks for the report, I created [this feature request](https://github.com/aws/aws-cdk/issues/17083) which is the same as this issue I believe 🙂

If you're willing to contribute, check out our [contributing guide](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md). This would be a pretty easy one 🙂
