### ISSUE TITLE
"Number of stacks with differences" is wrong

### ISSUE THREAD

**Issue by trondhindenes** [aws/aws-cdk#26818]
### Describe the bug

WHen running cdk diff (and also "cdk deploy" I think), cdk produces this:
"Number of stacks with differences: xx". This is not correct. It should read "Number of resources with differences: xx"

### Expected Behavior

the message should read "Number of resources with differences"

### Current Behavior

The message reads: "Number of stacks with differences"

### Reproduction Steps

just run cdk diff/deploy and look at the output

### CDK CLI Version

2.89.0

### Node.js Version

18.17

### OS

Ubuntu 22

### Language

Python

**Comment by peterwoodworth** [comment]
Yeah, I get 

```
Resources
[-] AWS::IAM::Role fn/ServiceRole fnServiceRole5D180AFD destroy
[-] AWS::Lambda::Function fn fn5FF616E3 destroy
[+] AWS::IAM::Role fndfsdf/ServiceRole fndfsdfServiceRoleC234D9DC 
[+] AWS::Lambda::Function fndfsdf fndfsdf4F4834C5 


✨  Number of stacks with differences: 4
```
