### ISSUE TITLE
aws-eks: Create cluster fails on 2.92.0 with ProxyAgent is not a constructor

### ISSUE THREAD

**Issue by shapirov103** [aws/aws-cdk#26828]
### Describe the bug

Creatiing cluster with 2.92.0 fails in the custom resource with ProxyAgent is not a constructor.

```
blueprint-construct-dev \|  90/245 \| 3:35:17 PM \| CREATE_FAILED        \| Custom::AWSCDK-EKS-Cluster            \| blueprint-construct-dev/Resource/Resource/Default (blueprintconstructdevE0DAE201) Received response status [FAILED] from custom resource. Message returned: ProxyAgent is not a constructor
--
1019 |  
1020 | Logs: /aws/lambda/blueprint-construct-dev-aws-OnEventHandler42BEBAE0-faAQVwewHMDZ
1021 |  
1022 | at Object.<anonymous> (/var/task/index.js:1:417)
1023 | at Module._compile (node:internal/modules/cjs/loader:1256:14)
1024 | at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
1025 | at Module.load (node:internal/modules/cjs/loader:1119:32)
1026 | at Module._load (node:internal/modules/cjs/loader:960:12)
1027 | at Module.require (node:internal/modules/cjs/loader:1143:19)
1028 | at require (node:internal/modules/cjs/helpers:110:18)
1029 | at _tryRequireFile (file:///var/runtime/index.mjs:912:37)
1030 | at _tryRequire (file:///var/runtime/index.mjs:962:25)
1031 | at _loadUserApp (file:///var/runtime/index.mjs:991:22) (RequestId: 22f81db7-d9e5-45ba-a7dc-ea354d98ccea)
```

Same code works fine with 2.88.0.  Reproduced with EKS Blueprints [here](https://github.com/aws-quickstart/cdk-eks-blueprints/pull/826#issuecomment-1686546255).

### Expected Behavior

Expected cluster creation to succeed. 

### Current Behavior

Fails with the above message. 

### Reproduction Steps

Reproduced with EKS Blueprints. Checkout this [branch](https://github.com/aws-quickstart/cdk-eks-blueprints/tree/task/1.11.0-release-prep). 

Update package.json `aws-cdk` and `aws-cdk-lib` to use cdk 2.92. 

Deploy with `cdk deploy blueprint-construct-dev`.

### Additional Information/Context

Potentially due to node upgrade on custom resources.

### CDK CLI Version

2.92

### Node.js Version

18

### OS

macos ventura 13

### Language

Typescript

**Comment by peterwoodworth** [comment]
It will be out in the next release 
https://github.com/aws/aws-cdk/issues/26771
https://github.com/aws/aws-cdk/issues/26787
