### ISSUE TITLE
ApiGateway: parameter for changing retention policy of CloudWatchRole and Account

### ISSUE THREAD

**Issue by nguyen102** [aws/aws-cdk#26827]
### Describe the feature

When creating ApiGateway via `RestApi`, the retention policy for the CloudWatchRole and Account sub-resources is `RETAIN`. There is no option to set the policy to `DELETE`. It looks like the policy used to be `DELETE` based on [this Issue](https://github.com/aws/aws-cdk/issues/22020).

I would like an option to set the retention policy of those two resources to be `DELETE`. 

### Use Case

When I'm trying to destroy my CDK stack, `CloudWatchRole` and `Account` are the only two resources I have to manually delete. I would like those resources to be deleted automatically when I destroy the CDK stack.

### Proposed Solution

A parameter option that I can past into [RestApi Construct](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_apigateway.RestApi.html) to delete those two resources. 

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

3.315.0

### Environment details (OS name and version, etc.)

MacOS

**Comment by peterwoodworth** [comment]
Makes sense @nguyen102,

You can currently work around this with [escape hatches](https://docs.aws.amazon.com/cdk/v2/guide/cfn_layer.html) - Check `tree.json` for a visual of the construct tree if you aren't sure how to override the constructs we're creating under the hood

**Comment by nguyen102** [comment]
Ah, this worked. I was able to change the retention policy of the `CloudWatchRole`. However, I wasn't able to change the retention policy of `Account`. I also wasn't able to find that resource in the console. Do you know how I can manually delete that resource after I delete my Cloudformation stack?

**Comment by peterwoodworth** [comment]
`Account` resource seems to be just an IAM role based on the cloudformation documentation
