### ISSUE TITLE
CDK deploy: Lambda LogRetention resources fail with rate exceeded errors

### ISSUE THREAD

**Issue by jaapvanblaaderen** [aws/aws-cdk#26837]
### Describe the bug

Deploying multiple stacks with a lot of Lambda functions, results in a lot of CloudWatch Log groups being created by CDK. CDK provides retry options through the [logRetentionRetryOptions](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda.LogRetentionRetryOptions.html) property of a Lambda Function construct to prevent rate exceeded errors from happening. 

Until `CDK 2.89.0` this worked fine. In `CDK 2.90.0`, the retry implementation changed in [this PR](https://github.com/aws/aws-cdk/pull/26609/files#diff-d55347d6fbeca6f583a04b79dab153dc73d1756203544571136caa03f4e014fdR187) and the rate exceeded errors occur again.

### Expected Behavior

The retry mechanism should just function properly, same way it did in older, `CDK 2.89` and lower, versions. Stacks should deploy without issues.

### Current Behavior

Stacks cannot be deployed with `CDK 2.90.0` and up as they error with a `Rate exceeded` error:
```
LogRetentionRateLimitStack3 |  57/183 | 11:34:35 AM | CREATE_FAILED        | Custom::LogRetention        | hello_11/LogRetention (hello11LogRetention0EC20DD0) Received response status [FAILED] from custom resource. Message returned: Rate exceeded (RequestId: b84c54c4-3053-487a-82b9-48671904d05a)
```

### Reproduction Steps

I created a small test project to reproduce the issue: https://github.com/jaapvanblaaderen/log-retention-rate-limit. With this simple setup, the issue can be easily reproduced when deploying the stacks in parallel as described in the readme of the repo. I even increased the [amount of retries](https://github.com/jaapvanblaaderen/log-retention-rate-limit/blob/master/lib/log-retention-rate-limit-stack.ts#L24) to `50` but then it still fails.

Testing it against `2.89.0` (which works fine) is possible by checking out the [cdk-289 tag](https://github.com/jaapvanblaaderen/log-retention-rate-limit/releases/tag/cdk-289).

### Possible Solution

Revert the retry mechanism as implemented in `CDK 2.89.0` or troubleshoot why the new retry mechanism doesn't work properly.

### Additional Information/Context

I'm actually a bit surprised and disappointed that this issue popped up again. I [fixed this issue myself in CDK](https://github.com/aws/aws-cdk/issues/8257) 3 years ago and now we have this regression on it which causes it to fail.

### CDK CLI Version

2.90.0

### Node.js Version

18

### OS

OSX

### Language

Typescript

### Other information

Related issues:
- https://github.com/aws/aws-cdk/issues/8257
- https://github.com/aws/aws-cdk/issues/24485

**Comment by mrgrain** [comment]
Thanks @jaapvanblaaderen for reporting and apologies for this regression. The retry mechanism changed from SDK v2 to SDK v3, and was supposed to be smarter. But clearly something did not work. Looking into it.

**Comment by jaapvanblaaderen** [comment]
Thanks @mrgrain, please let me know if I can assist in any way.

**Comment by mrgrain** [comment]
With the patched version from my PR, your reproduction example now succeeds! 🥳

**Comment by jaapvanblaaderen** [comment]
That sounds great!

**Comment by nikolay-radkov** [comment]
The issue was resolved with updating to 2.93.0 on our side but it starts to occur again without changing the version. Is it reproducible again on your side @jaapvanblaaderen? We have the same setup as described in the issue.

**Comment by mrgrain** [comment]
Thanks @nikolay-radkov for the report! Have you tried setting a higher number for `maxRetries`? The default might well be too conservative.

**Comment by mrgrain** [comment]
@jaapvanblaaderen Did you ever get around to confirming if this has been resolved for you?

**Comment by wwjhu** [comment]
I can confirm that after upgrading to 2.94, the test project can be deployed without rate limit errors. We will upgrade our services to 2.94 coming weeks, but so far so good. Nice job!

**Comment by mrgrain** [comment]
> I can confirm that after upgrading to 2.94, the test project can be deployed without rate limit errors. We will upgrade our services to 2.94 coming weeks, but so far so good. Nice job!

Thanks, but should have worked in first place!
Once you have upgraded your services, could you please let me know if it works with a real world project and if you have to customize `maxRetries`? We are very open to adjusting the default number of retries to one that's working for most.

**Comment by wwjhu** [comment]
> Once you have upgraded your services, could you please let me know if it works with a real world project and if you have to customize `maxRetries`? We are very open to adjusting the default number of retries to one that's working for most.

Sure, will keep you posted.
