### ISSUE TITLE
Lakeformation: CDK is re-creating resources when they are not changed

### ISSUE THREAD

**Issue by denys-tyshetskyy** [aws/aws-cdk#26834]
### Describe the bug

CDK is trying to create a new ResourceProperty in the lakeformation, every time the stack is being deployed even when no changes were made. For some resources like DataLocationResourceProperty, it breaks the deployment since provided resource already exists.

### Expected Behavior

When nothing changes, the resource shouldn't be attempted to be deployed.

### Current Behavior

I am provisioning the lake formation stack as a part of the project and every time deployment happens, even with no changes to lake formation stack whatsoever (other stacks are updated) the resources are being re-created in the lake formation stack.
This breaks the deployment because when DataLocationResourceProperty is attempted to be re-created the stack fails with the error **Resource is already registered (Service: AWSLakeFormation; Status Code: 400; Error Code: AlreadyExistsException;**

### Reproduction Steps

```py
         for bucket in buckets:
            bucket_resource: s3.Bucket = buckets.get(bucket)
            resource_property = lakeformation.CfnPermissions.ResourceProperty(
                data_location_resource=lakeformation.CfnPermissions.DataLocationResourceProperty(
                    s3_resource=bucket_resource.bucket_arn)
            )
            # Register S3 buckets as LF resources
            data_lake_resource = lakeformation.CfnResource(self, f"{bucket_resource}-LFResource",
                                                           resource_arn=bucket_resource.bucket_arn,
                                                           use_service_linked_role=False,
                                                           role_arn=role.role_arn
                                                           )
            lakeformation.CfnPermissions(self, f"{bucket_resource}-GlueDataLocationPermission",
                                         data_lake_principal=glue_principal,
                                         resource=resource_property,
                                         permissions=['DATA_LOCATION_ACCESS']
                                         ).add_dependency(data_lake_resource)
```

### CDK CLI Version

2.92.0

### Node.js Version

v16.20.1

### OS

AWS Linux

### Language

Python

### Language Version

Python 3.10

**Comment by pahud** [comment]
What did you see when you run `cdk diff` or `npx cdk diff` ?

**Comment by peterwoodworth** [comment]
Yes, if there is a diff appearing then that means there is something in your code that is triggering CDK to add more to your template, which could be a bug on your end that we don't have the details on.

If there is no diff appearing, then CloudFormation should not be taking any action. If this does turn out to be the case, we will need to reach out to the service team

**Comment by denys-tyshetskyy** [comment]
Hi, apologies - it was a naming issue of the resource on my side.
This bug can be closed.

Cheers
Denys



CONFIDENTIAL
