### ISSUE TITLE
aws-appsync: support passing dynamic values from CDK to APPSYNC_JS

### ISSUE THREAD

**Issue by samturner3** [aws/aws-cdk#26848]
### Describe the feature

javascript resolver support was added: https://github.com/aws/aws-cdk/issues/22921
However for some configurations context in the cdk file is required to be passed to the APPSYNC_JS file.

### Use Case

For example when using other DynamoDB operations such as, [TransactionWriteItem](https://docs.aws.amazon.com/appsync/latest/devguide/js-resolver-reference-dynamodb.html#js-aws-appsync-resolver-reference-dynamodb-transact-write-items), the table name is required. If the table name is different for each application environment there is currently no way to provide a dynamic value to the resolver. The work arounds are to write the resolver code inline in the CDK stack or provide the table name as part of the GraphQL request context.

Another example is [in this aws-sample step functions example](https://github.com/aws-samples/aws-amplify-stepfunctions-example/blob/86a3cfb51fbf7ea0292c9b2cc7d3e7196faae27d/template/cdk-stack.ts#L25) where we need to pass in `stateMachineArn` to the request template.

### Proposed Solution

something like:

1. Add `codeArgs`

_cdk-stack.ts_
```
    httpdatasource.createResolver('execute-state-machine', {
      typeName: 'Mutation',
      fieldName: 'executeSearch',
      runtime: appsync.FunctionRuntime.JS_1_0_0,
      code: appsync.Code.fromAsset(path.join(__dirname, 'appSyncResolver.js')),
      codeArgs: { stateMachineArn: stateMachine.stateMachineArn}
    })
```
2. (prefered) in `AssetCode` options add a new option such as `codeArgs` (may need a better name):
```
code: appsync.Code.fromAsset(path.join(__dirname, 'appSyncResolver.js'), { codeArgs: { stateMachineArn: stateMachine.stateMachineArn} })
```

Then in the code file:

1. (prefered) Have it come through from Context ,`ctx.codeArgs`

_appSyncResolver.js_
```
import { util } from '@aws-appsync/utils'

export const request = (ctx) => {
  return {
    ...
      body: JSON.stringify({
        stateMachineArn: ctx.codeArgs.stateMachineArn,
        input: {
         ...
```

2. Have it come through from a new arg ,`codeArgs`

_appSyncResolver.js_
```
import { util } from '@aws-appsync/utils'

export const request = (ctx, codeArgs) => {
  return {
    ...
      body: JSON.stringify({
        stateMachineArn: codeArgs.stateMachineArn,
        input: {
         ...
```

### Other Information

This is a much wanted feature as mentioned:

- [Developing and Testing AWS AppSync JavaScript Resolvers](https://medium.com/ama-tech-blog/developing-and-testing-aws-appsync-javascript-resolvers-d485090f3fe) - medium.com
- [AppSync JS Resolvers with CDK: How to easy get a DynamoDB Table Name for all your Transact Operations](https://kieron-mckenna.medium.com/appsync-resolvers-with-typescript-cdk-getting-a-dynamodb-table-name-for-transactions-d8060f438b6b) - medium.com

I am using amplify that transpiles TS files, I then reference the built file into `appsync.Code.fromAsset`.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

v2 (unknown exactly as using amplify)

### Environment details (OS name and version, etc.)

Mac OS 11.6

**Comment by samturner3** [comment]
I don't know enough to create a PR, however it may be something like;
in `packages/aws-cdk-lib/aws-appsync/lib/code.ts`:
```
// New:
export interface CodeOptions extends s3_assets.AssetOptions {
  codeArgs?: { key: string; value: string }[];
}

// Modified: 
public static fromAsset(path: string, options?: CodeOptions): AssetCode {
  return new AssetCode(path, options);
}
```

Not sure if extending `s3_assets.AssetOptions` is the right approach... 

Then I have no idea how to get this into the file, ie `ctx.codeArgs.`

**Comment by danrivett** [comment]
I totally agree with solving this use case in a first class way.

FWIW we solved it for now via creating a factory function for creating a dynamic Pipeline Resolver that added the value to the context's `stash`. Later Pipeline Resolvers can then read that value to create requests using the dynamic Table name.

Here's our factory function verbatim, including all our comments and reference to what inspired our solution as they may be helpful.

This is used in a CDK construct, as the comments below explain, via `Code.fromInline(createTableNameInjector(table.tableName))` where `table` is a CDK `ITable` resource managed via CDK.

```ts
// For Batch DynamoDB operations the AppSync Resolvers need access to the table name to read from
// This isn't available at runtime so we need to inject it at build time using the following Pipeline Resolver factory function
//
// Note: This returns generated string with the resolvered table name embedded and so needs to be used with Code.fromInline() rather than Code.fromAsset().
// Inspired by: https://kieron-mckenna.medium.com/appsync-resolvers-with-typescript-cdk-getting-a-dynamodb-table-name-for-transactions-d8060f438b6b

export const createTableNameInjector = (tableName: string) => `
  export function request(ctx) {
    ctx.stash.tableName = "${tableName}"
    return {}
  }
  export function response(ctx) {
    return ctx.prev.result
  }
`;
```

Hope that's at least helpful as a possible solution in the short term.

**Comment by sudokar** [comment]
Right now, I am using this construct https://constructs.dev/packages/cdk-appsync-typescript-resolver which transpiles TS to JS and replace strings (for example ENV or TABLE_NAME)

PS: I created the construct

**Comment by pahud** [comment]
Thank you for the feature request and we welcome pull requests from the community.

**Comment by onlybakam** [comment]
We released support for env vars in appsync: https://docs.aws.amazon.com/appsync/latest/devguide/environmental-variables.html
This PR exposes the feature in L2 construct: https://github.com/aws/aws-cdk/pull/29064

**Comment by ashishdhingra** [comment]
@samturner3 Good morning. Could you please check if support for env vars in appsync: https://docs.aws.amazon.com/appsync/latest/devguide/environmental-variables.html helps resolve your use case?

Thanks,
Ashish

**Comment by samturner3** [comment]
I am not able to test the solution as the specific engagement has ended, however from just reading the docs it looks like it is solved in principle.
