### ISSUE TITLE
ec2: Create an ec2.Port and add it to SG, it won't work 

### ISSUE THREAD

**Issue by NB3025** [aws/aws-cdk#26867]
### Describe the bug

(I'm using Python.)

I am trying to add 2 rules to a security group.
1. SCTP, to_port=38412, from_port=38412
2. SCTP, to_port=3868, from_port=3868

I created the above ports using ec2.Port.
And add it to the ingress rule of Security Group.

However, what is actually applied is SCTP, to_port=all, from_port=all.

### Expected Behavior

There should be 2 rules in the security group's ingress rule.
1. SCTP, to_port=38412, from_port=38412
2. SCTP, to_port=3868, from_port=3868

### Current Behavior

The ingress rule of the scurity group contains 1 rule.
1. SCTP, to_port=all, from_port=all

### Reproduction Steps
(Python 3.9.16)

```py
multus_security_group_new = ec2.SecurityGroup(self, "MySecurityGroup", vpc=my_vpc)

sctp_port_36412 = ec2.Port(protocol=ec2.Protocol.SCTP, string_representation="sctp", from_port=36412, to_port=36412)
sctp_port_3868 = ec2.Port(protocol=ec2.Protocol.SCTP, string_representation="sctp", from_port=3868, to_port=3868)
multus_security_group_new.add_ingress_rule(ec2.Peer.any_ipv4(), sctp_port_36412, 'allow sctp from port 36412')
multus_security_group_new.add_ingress_rule(ec2.Peer.any_ipv4(), sctp_port_3868, 'allow sctp from port 3868')
```

### Additional Information/Context

<img width="1433" alt="sctp_bug" src="https://github.com/aws/aws-cdk/assets/22049499/7d205070-e4ef-40c3-94f3-3af834d71d96">

### CDK CLI Version

2.82.0 (build 3a8648a)

### Node.js Version

v18.16.0

### OS

Linux

### Language

Python

### Language Version

파이썬(3.9.16)

**Comment by pahud** [comment]
<img width="1504" alt="image" src="https://github.com/aws/aws-cdk/assets/278432/a123e811-205c-43a8-a993-f0e548c92c93">

Looks like SCTP would not allow you to specify port range.

Are you able to configure that in the AWS console?
Can you show me what the AWS console looks like with correct configuration?

**Comment by NB3025** [comment]
I think I made a mistake.
Thank you.
