### ISSUE TITLE
cfn-parse.ts: parseDeletionPolicy is missing CreateExceptOnDelete

### ISSUE THREAD

**Issue by njsouthwood** [aws/aws-cdk#26863]
### Describe the bug

CFN recently added support for a new [deletion policy called RetainExceptOnCreate](https://aws.amazon.com/about-aws/whats-new/2023/07/aws-cloudformation-deletion-policies-dev-test-cycle/). This policy was added to the removal-policy enum in [e0d5ca](https://github.com/aws/aws-cdk/pull/26602/commits/e0d5cad96d982c531bb19788939cede36c133e5c), however it is missing from the [switch/case block in `parseDeletionPolicy`](https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/core/lib/helpers-internal/cfn-parse.ts#L468), which causes errors when this removal policy is used.

EDIT: It looks like this code may only be executed when using `CfnInclude` to create a stack from an existing CloudFormation template. Updating the rest of this issue to be more clear about that.

### Expected Behavior

You should be able to use `CfnInclude` to import an existing cloudformation template with valid usage of `DeletionPolicy: RetainExceptOnCreate` without any errors

### Current Behavior

If you define a stack resource with `DeletionPolicy: RetainExceptOnCreate`, then use `CfnInclude` to import that stack you'll get this error:

```
Error: Unrecognized DeletionPolicy 'RetainExceptOnCreate'
```

### Reproduction Steps

* Create Cloudformation template with a stack resource with `DeletionPolicy: RetainExceptOnCreate`
* Import that template as a cdk stack using [`CfnInclude`](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.cloudformation_include.CfnInclude.html)

### Possible Solution

* Add a case for `RetainExceptOnCreate`
* It looks like[ cfn-parse uses this same parsing function for both](https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/core/lib/helpers-internal/cfn-parse.ts#L356) `deletionPolicy` and `updateReplacePolicy`. It looks like the new `RetainExceptOnCreate` policy is not a valid `updateReplacePolicy`. There will need to be two separate parsing functions.

### CDK CLI Version

2.91.0 

### Node.js Version

v14.21.3

### OS

AL2

### Language

Typescript

**Comment by peterwoodworth** [comment]
This would only come into play if you're using the `CfnInclude` module, right?

**Comment by njsouthwood** [comment]
Not sure if that's the only case where it would happen, but it looks like that is what we are doing in this case.
