### ISSUE TITLE
aws-route53: (BREAKING!) Imported Route53 zone attribute and/or type mismatch

### ISSUE THREAD

**Issue by einstein-aws** [aws/aws-cdk#26872]
### Describe the bug

Seems like after the latest CDK update to v2.93.0 I am having trouble with importing Route53 hosted zones. I tried:
```
const route53Zone = r53.HostedZone.fromLookup(this, 'my-route53-zone', { domainName: 'mydomain.com' });

and...

const route53Zone = r53.PublicHostedZone.fromLookup(this, 'my-route53-zone', { domainName: 'mydomain.com' });

and...

const route53Zone = r53.HostedZone.fromHostedZoneAttributes(this, 'my-route53-zone', { zoneName: 'mydomain.com', hostedZoneId: 'my-zone-id' });

and...

const route53Zone = r53.PublicHostedZone.fromHostedZoneAttributes(this, 'my-route53-zone', { zoneName: 'mydomain.com', hostedZoneId: 'my-zone-id' });
```
and when I tried:
```
const sesIdentity = ses.Identity.publicHostedZone(route53Zone);
```
I am getting:

```
Argument of type 'IHostedZone' is not assignable to parameter of type 'IPublicHostedZone'.
  Property 'grantDelegation' is missing in type 'IHostedZone' but required in type 'IPublicHostedZone'.ts(2345)
hosted-zone.d.ts(146, 5): 'grantDelegation' is declared here.
```

### Expected Behavior

Either of the above imports should work.

### Current Behavior

Getting error:

```
Argument of type 'IHostedZone' is not assignable to parameter of type 'IPublicHostedZone'.
  Property 'grantDelegation' is missing in type 'IHostedZone' but required in type 'IPublicHostedZone'.ts(2345)
hosted-zone.d.ts(146, 5): 'grantDelegation' is declared here.
```

### Reproduction Steps

Try to use either of the above Route53 zone imports in:

```
const sesIdentity = ses.Identity.publicHostedZone(route53Zone);
```

### CDK CLI Version

v2.93.0

### Node.js Version

v18.12.0

### OS

MacOS Ventura 13.4.1

### Language

Typescript

**Comment by khushail** [comment]
Hi @einstein-aws , could you please share the complete code snippet for reproducing this issue? TIA.

**Comment by einstein-aws** [comment]
Hi @khushail. This is literally the code I am using. Here is the excerpt from my stack:

```
    // Lookup default Route53 public hosted zone
    // const appR53ZoneIdDefault = ssm.StringParameter.valueForStringParameter(this, appLabelR53ZoneIdDefault);
    // const appR53ZoneDefault = r53.PublicHostedZone.fromHostedZoneAttributes(this, appLabelR53Zone, { zoneName: appDomain, hostedZoneId: appR53ZoneIdDefault });
    const appR53Zone        = r53.HostedZone.fromLookup(this, appLabelR53Zone, { domainName: appDomain });
    const appR53SesIdentity = ses.Identity.publicHostedZone(appR53Zone); // <-- error is here

    // Define default SES identity
    const appSesIdentity = new ses.EmailIdentity(this, appLabelSesIdentity, {
      mailFromDomain              : `${appSubDomainMail}.${appDomain}`,
      configurationSet            : appSesConfigurationSet,
      identity                    : appR53SesIdentity,
      mailFromBehaviorOnMxFailure : ses.MailFromBehaviorOnMxFailure.REJECT_MESSAGE,
      dkimSigning                 : true,
      feedbackForwarding          : true
    });
``` 

<img width="1472" alt="Screenshot 2023-08-24 at 11 30 21 AM" src="https://github.com/aws/aws-cdk/assets/104647230/d9012dcb-6309-437d-8cbe-ce6811c8e363">

**Comment by khushail** [comment]
Hi @einstein-aws , I used one of the import methods and tried to reproduce the issue but my code is succeeding. Please see here-
<img width="1346" alt="Screenshot 2023-08-24 at 11 51 00 AM" src="https://github.com/aws/aws-cdk/assets/117320115/8e346477-f914-4806-8d7c-a02df3217782">

**Comment by einstein-aws** [comment]
I am getting the same error no matter what export method I use... Here is my version of your example:

<img width="1204" alt="Screenshot 2023-08-24 at 12 39 39 PM" src="https://github.com/aws/aws-cdk/assets/104647230/3c6e67d3-9f99-47cd-a8b2-6aafaa254ea3">

Same problem. What else could it be? I have all my libraries updated (i.e. npm-check-updates).

**Comment by khushail** [comment]
@einstein-aws , the `r53.HostedZone.fromLookup(this, appLabelR53Zone, ...)` this `appLabelR53Zone` should be id , while it seems you have given some PublicHostedZone variable here. Could you please check againa nd try giving it some string based id?

**Comment by einstein-aws** [comment]
@khushail It is a string, just a label. But, here is a hardcoded string:

<img width="910" alt="Screenshot 2023-08-24 at 2 07 45 PM" src="https://github.com/aws/aws-cdk/assets/104647230/4b8ea2f2-9d3b-43b6-88c5-ac88bb32e69a">

...and here is import using ```fromHostedZoneId()```:

<img width="1156" alt="Screenshot 2023-08-24 at 2 09 04 PM" src="https://github.com/aws/aws-cdk/assets/104647230/ab3a16ba-ca36-427f-9710-e5bc65060e54">

**Comment by khushail** [comment]
@einstein-aws , Yes, you are correct (my bad, forgot to check the version changes). This is a bug in the latest version which was released yesterday. Looking at this [PR](https://github.com/aws/aws-cdk/pull/26333/files), it looks like the changes in `aws-route53` module caused this error. 

Marking this issue as P2. Community PRs are welcome.

**Comment by einstein-aws** [comment]
@khushail Thank you! I hope this will be fixed soon :)
