### ISSUE TITLE
Use a lower level API of the SDK in AwsCustomResource

### ISSUE THREAD

**Issue by jogold** [aws/aws-cdk#2689]
This would allow to issue API calls even if the version available on Lambda is not the most recent one.

See discussion in #1850.

**Comment by spg** [comment]
Just hit this roadblock today. I was trying to create a `Glue::Crawler`, but the `CatalogTargets` property is neither supported by CloudFormation natively nor the JS SDK v2.437.0 (bundled with runtime `nodejs10.x`. Supported started in [v2.453.0](https://github.com/aws/aws-sdk-js/blob/master/CHANGELOG.md#24530)).
