### ISSUE TITLE
aws-cdk-lib: to use nodejs18

### ISSUE THREAD

**Issue by beaumsc** [aws/aws-cdk#26902]
### Describe the feature

As a python developer wishing to use cdk for python, I want common services built by the cdk using NodeJS to be based on a non-deprecated version of NodeJS and certainly not version 14 which is soon to be unsupported by AWS.

Given latest version version of cdk installed
When `cdk init app --language python` is issued on a new folder
And `pip install -r requirements.txt` is issued
Then all references to `runtime="` for installed files within `.../.venv/lib/python3.x/site-packages/aws_cdk/` specify NODEJS_18_X

### Use Case

I want to use cdk for my AWS deployments and this will soon not be possible [1].

[1] https://endoflife.date/nodejs

### Proposed Solution

NodeJS v18

### Other Information

Specifically, I came across this problem with the SingletonLambda that is created by CDK. However, I can see from searching the code base, this problem exists for other common services too.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.93.0

### Environment details (OS name and version, etc.)

Ubuntu 22.04, Python 3.10

**Comment by peterwoodworth** [comment]
Closing as duplicate

**Comment by beaumsc** [comment]
@peterwoodworth I'm sorry for raising a duplicate; I did check for open issues and did not find anything mentioning nodejs14. Can you provide the existing issue so that I can see progress/delivery date?
