### ISSUE TITLE
aws-cdk-lib: to use nodejs18

### ISSUE THREAD

**Issue by beaumsc** [aws/aws-cdk#26901]
### Describe the feature

As a python developer wishing to use cdk for python, I want common services built by the cdk using NodeJS to be based on a non-deprecated version of NodeJS and certainly not version 14 which is soon to be unsupported by AWS.

Given latest version version of cdk installed
When `cdk init app --language python` is issued on a new folder
And `pip install -r requirements.txt` is issued
Then all references to `runtime="` for installed files within `.../.venv/lib/python3.x/site-packages/aws_cdk/` specify NODEJS_18_X

### Use Case

I want to use cdk for my AWS deployments and this will soon not be possible [1].

[1] https://endoflife.date/nodejs

### Proposed Solution

NodeJS v18

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.93.0

### Environment details (OS name and version, etc.)

Linux (WSL2)

**Comment by peterwoodworth** [comment]
If you could let us know what is not using node18 yet that would be helpful - we have migrated most if not everything to node18

**Comment by peterwoodworth** [comment]
I think all that's still left is just one custom resource handler found in Route 53 - All our other functions should be on Node 18, unless I'm misunderstanding the issue @beaumsc

**Comment by msheiny** [comment]
> I think all that's still left is just one custom resource handler found in Route 53 - All our other functions should be on Node 18, unless I'm misunderstanding the issue @beaumsc

Hey which CR handler is still on nodejs14? Just want to check if I'm using it and keep tabs on it so I can upgrade when it bumps. Thanks for the work ya'll do ❤️

**Comment by khushail** [comment]
Hi @beaumsc , it would be helpful if you could share which custom resource handler is on nodejs14, as our team is working on this update

**Comment by beaumsc** [comment]
@msheiny @khushail 
The building of the `singletonLambda` is being deployed as a NodeJS14 runtime as result of of `cdk boostrap` is my specific issue. However, when I search the installed python library into my virtual environment for runtime version ("runtime=" search string, see description for suggested BDD test for this issue), I can see this issue extends beyond just the singletonLambda common resource code, NODEJS14 is mentioned in 10+ other places.

**Comment by iliapolo** [comment]
@beaumsc what exactly do you mean by `singletonLambda`? Can you please share more specific identifiers? 


Also it would be helpful if you can share the results of your search? I'm not able to find the occurrences you are mentioning...

**Comment by beaumsc** [comment]
@iliapolo,

in answer to your question, when deploying my CDK defined app, more specifically, after running `cdk bootstrap`, one of the resultant resources in cloudformation is a Lambda with logical ID of SingletonLambda<uuid>.

The following docker file isolates the issues, it outputs 95 references to NODEJS14

```dockerfile
FROM python:3.10-slim

RUN pip install aws-cdk-lib==2.93.0

WORKDIR /usr/local/lib/python3.10/site-packages
CMD grep -r -H -n --include \*.py Runtime.NODEJS_14 aws_cdk
```

**Comment by pahud** [comment]
@beaumsc 

Try using 2.94.0 instead. You will not grep anything. See below:

<img width="956" alt="image" src="https://github.com/aws/aws-cdk/assets/278432/39035bde-3547-4b46-b8f2-1936b3ba6eb9">

**Comment by beaumsc** [comment]
@pahud,

I concur, when upgrading to aws-cdk-lib 2.94.0

1. `cdk boostrap` replaced the SingletonLambda with Nodejs-18 runtime
2. There are no references to version 14

FYI, there are 32 references to nodejs version 16.

Thanks for resolving, great job. 👏
