### ISSUE TITLE
(cdk-Bootstrap): bootstrap an account with a custom qualifier

### ISSUE THREAD

**Issue by Lyndabenboudaoud** [aws/aws-cdk#26939]
### Describe the bug

We have bootstrapped our account with a custom qualifier, However, although setting the stack synthesizer to use the correct qualifier when deploying the stack, it is failing with the following error message: 

"Error [ValidationError]: Unable to fetch parameters [/cdk-bootstrap/nnnnnnnnnn/version] from parameter store for this account."

We face this problem in eu-east-1 but it works fine in eu-west-1

here is the portion of the code in question:

![unnamed](https://github.com/aws/aws-cdk/assets/97296818/8b8b642e-1787-4da4-9930-f57c8ace5bb2)

### Expected Behavior

Have the same behaviour in us-east1 as in  eu-west1

### Current Behavior

We have bootstrapped our account with a custom qualifier, However, although setting the stack synthesizer to use the correct qualifier when deploying the stack, it is failing with the following error message: 

"Error [ValidationError]: Unable to fetch parameters [/cdk-bootstrap/nnnnnnnnnn/version] from parameter store for this account."

<img width="743" alt="error" src="https://github.com/aws/aws-cdk/assets/97296818/87fd1df6-108b-4bd5-9787-d07e3f3d85d9">

### Reproduction Steps

Deploying a CDK app and later changing the qualifier for the bootstrap

### Additional Information/Context

We use this command to deploy: 
npx aws-cdk@2.67.0 deploy '*' --toolkit-stack-name stack-xxxx-cdk-v2-bootstrap --require-approval never --debug

### CDK CLI Version

2.67

### Node.js Version

14.19.3

### OS

Linux

### Language

Typescript

**Comment by peterwoodworth** [comment]
Try setting the [qualifier](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.DefaultStackSynthesizerProps.html) prop?

**Comment by saharzitoun56** [comment]
> Try setting the [qualifier](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.DefaultStackSynthesizerProps.html) prop? Also, make sure to check the console to ensure that it has actually been bootstrapped with the appropriate qualifier.

The environment has been bootstrapped with the correct qualifier. But when it comes to the creation of the lambda edge stack , he is unable to see the personalized bucket and ssm parameter. He took into account that qualifier it since it was added to cdk.json. But not the personalized template of bootstrap. However this personalized template works for the other stacks in eu-west ( it dosen't work only with the stack of lambda edge in us-east)

**Comment by pahud** [comment]
Hi, I am looking into this issue. Is it still happening in CDK 2.111.0 or above? If yes, can you provide code snippet for me to reproduce this issue without using screenshot so I can easily copy/paste with minimal tweaks?
