### ISSUE TITLE
(aws-eks): nodegroup already exists when re-sizing a node

### ISSUE THREAD

**Issue by juweeks** [aws/aws-cdk#26931]
### Describe the bug

trying to resize nodes in a nodegroup and get a cloudformation failure saying that the nodegroup already exists. seems it's trying to replace the nodegroup itself.

![Untitled](https://github.com/aws/aws-cdk/assets/17327142/574609b5-cf45-46c6-8552-1bf0a39f79cf)

### Expected Behavior

resized nodes in a nodegroup

### Current Behavior

deployment failure 
```
11:24:19 PM | UPDATE_FAILED        | AWS::EKS::Nodegroup                      | eksclusterworkers
Resource handler returned message: "NodeGroup already exists with name workers and cluster name mycluster (Service: Eks, Status Code: 409, Request ID: 11b219b7-c960-4ad1-a645-e6b4
cfe049ec)" (RequestToken: e712139f-280f-0b53-57cb-6798386d48b6, HandlerErrorCode: AlreadyExists)
```

### Reproduction Steps

1. deploy an eks nodegroup (say c5.large)
2. re-deploy nodegroup with different size instance (say, t3a.medium)

### CDK CLI Version

2.91.0 (build eea12ea)

### Framework Version

2.91.0

### Node.js Version

20.5.1

### OS

Mac 13.4.1 (Ventura)

### Language

Python

### Language Version

Python (3.9.4)

**Comment by pahud** [comment]
If you update the instance type of the nodegroup, this will trigger cloudformation resource update [replacement](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-replacement), which means new NG with exactly the same name will be created before the old one being destroyed hence the error ""NodeGroup already exists with name workers and cluster name mycluster ".

I think you will need to update the nodegroup name as well to avoid this or just leave the name undefined.

**Comment by juweeks** [comment]
k. thanks.
