### ISSUE TITLE
aws-elasticloadbalancingv2: health and unhealthy threshold counts can vary

### ISSUE THREAD

**Issue by toxygene** [aws/aws-cdk#26941]
The `validateTargetGroup` method in the `NetworkTargetGroup` class has a check to ensure the healthy and unhealthy threshold counts are the same (https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/nlb/network-target-group.ts#L262-L268), but this does not appear to be a requirement of AWS.

```
➜  aws elbv2 describe-target-groups --target-group-arns [omitted] --query 'TargetGroups[0].[HealthyThresholdCount,UnhealthyThresholdCount]'
[
    5,
    5
]
```

### Expected Behavior

The `NetworkTargetGroup` is created

### Current Behavior

An error message of `Healthy and Unhealthy Threshold Counts must be the same`.

### Reproduction Steps

Create a `NetworkTargetGroup` with differing healthy and unhealthy threshold counts.

### Possible Solution

Remove https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/nlb/network-target-group.ts#L262-L268

### CDK CLI Version

2.91.0

### Node.js Version

18.17.1

### OS

macOS 13.5.1

### Language

Python

### Language Version

3.9.16

**Comment by peterwoodworth** [comment]
I can't find any docs on the topic, and neither the [PR](https://github.com/aws/aws-cdk/pull/10205) or the issue it fixed linked to any docs either. I'm not sure that your CLI output shows that the values can differ. Can you use escape hatches to set the values manually and see if it deploys?

**Comment by toxygene** [comment]
My apologies -- I copy/pasted the output from the wrong target group. Here is the output for a target group with differing thresholds:
```
➜  aws elbv2 describe-target-groups --target-group-arns [omitted] --query 'TargetGroups[0].[HealthyThresholdCount,UnhealthyThresholdCount]' 
[
    5,
    2
]
```
Additionally, here is a screenshot of the web console:
<img width="1530" alt="Screenshot 2023-08-30 at 10 32 38 AM" src="https://github.com/aws/aws-cdk/assets/350210/ef3d3eb8-9843-4a71-b5b6-5442db250a7b">

**Comment by peterwoodworth** [comment]
Great, thanks!
