### ISSUE TITLE
(aws-cloudwatch): Ability to set time frames for individual graphs in a dashboard

### ISSUE THREAD

**Issue by hhxiagithub** [aws/aws-cdk#26945]
### Describe the feature

Currently, we can set a time frame for an entire dashboard, or set individual time frames for graphs in the CloudWatch dashboard console manually, but the functionality to do so inside CDK doesn't exist. 

Setting these time frames manually in the CloudWatch console is not an option for me, as any changes I make there are overwritten with the next code deployment. 

### Use Case

I'd like to display graphs with different time frames in the same dashboard. For example, I'd like to display the same metric over a period of 7 days, and also display it over 8 hours so I get a more complete look at the metric and its history. 

### Proposed Solution

Just as we have the option to specify start and end times for a [dashboard](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_cloudwatch.Dashboard.html), I'd like that option added for a graph. The start/end times that a graph specifies should override the start/end of the dashboard that the graph sits in. This way, we can specify a default time range for graphs in a dashboard, but individual graphs can still override that when needed.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.79.1

### Environment details (OS name and version, etc.)

macOS 13.3.1

**Comment by khushail** [comment]
hi @hhxiagithub ,thanks for reaching out with this feature request.
