### ISSUE TITLE
(integ-tests-alpha): Incorrect IAM policy statement generated when actions has a hyphen in the name

### ISSUE THREAD

**Issue by dontirun** [aws/aws-cdk#26952]
### Describe the bug

The generated IAM policy does not take into account if the service has a `-` in it's name for the IAM  Policy Action

### Expected Behavior

The generated IAM policy has the correct permissions

### Current Behavior

The generated IAM policy does not has the correct permissions

### Reproduction Steps

Given the following integ test

```ts
import * as integ from '@aws-cdk/integ-tests-alpha';
import * as cdk from 'aws-cdk-lib';

const app = new cdk.App();
const stack = new cdk.Stack();
const test = new integ.IntegTest(app, 'integ', {
  testCases: [stack],
});

const describeUsageLimit = test.assertions.awsApiCall('RedshiftServerless', 'getUsageLimit', {
  UsageLimitId: 'foo',
});

describeUsageLimit.expect(
  integ.ExpectedResult.objectLike({
    amount: 100,
    breachAction: 'deactivate',
    period: 'monthly',
  }),
);

app.synth();
```

An IAM Role with the following policy is generated with an incorrect action 

```json
    "Policies": [
     {
      "PolicyName": "Inline",
      "PolicyDocument": {
       "Version": "2012-10-17",
       "Statement": [
        {
         "Action": [
          "redshiftserverless:GetUsageLimit"
         ],
         "Effect": "Allow",
         "Resource": [
          "*"
         ]
        }
       ]

```

The action needs to be `redshift-serverless:GetUsageLimit` instead of `redshiftserverless:GetUsageLimit`

### CDK CLI Version

2.89.0-alpha.0

### Node.js Version

v20.5.0

### OS

Osx Ventura

### Language

Typescript

**Comment by msambol** [comment]
@peterwoodworth I can take this, after you triage and deem it needing to be fixed.

**Comment by khushail** [comment]
Hi @dontirun , thanks for reaching out. I am able to reproduce the issue.

**Comment by msambol** [comment]
@khushail I'll take this, please assign me.

**Comment by khushail** [comment]
> @khushail I'll take this, please assign me.

Thanks for volunteering to work on this PR. Please feel fee to proceed.
