### ISSUE TITLE
formatArn helper can't generate valid SQS queue ARNs

### ISSUE THREAD

**Issue by adambiggs** [aws/aws-cdk#26958]
### Describe the bug

When using `Stack.of(this).formatArn()` it doesn't appear possible to generate valid SQS queue ARNs. Queue ARNs don't contain a resource type at all, and there's no `arnFormat` for this particular use case.

### Expected Behavior

`formatArn()` should be able to generate valid SQS queue ARNs.

### Current Behavior

The closest I can get is something like this:
```ts
Stack.of(this).formatArn({
  service: 'sqs',
  resource: '',
  resourceName: 'my-queue.fifo',
  arnFormat: ArnFormat.COLON_RESOURCE_NAME
})
```
Which outputs e.g. `:sqs:us-east-1:000000000000::my-queue.fifo` (note the double `::` before the queue name).

The actual ARN is `arn:aws:sqs:us-east-1:000000000000:my-queue.fifo`.

### Reproduction Steps

Same as above:
```ts
Stack.of(this).formatArn({
  service: 'sqs',
  resource: '',
  resourceName: 'my-queue.fifo',
  arnFormat: ArnFormat.COLON_RESOURCE_NAME
})
```

### Possible Solution

Really I think the best solution would be to deprecate (or at least make optional) the `arnFormat` parameter, and have `formatArn()` automatically deal with this based on the value of `service`.

But at the very least there should be an `arnFormat` for this use case.

### CDK CLI Version

2.92.0 (build bf62e55)

### Node.js Version

16

### OS

MacOS

### Language

Typescript

### Language Version

4.9.5

**Comment by peterwoodworth** [comment]
This works

```
    const arn = this.formatArn({
      service: 'sqs',
      resource: 'myqueuename',
    })

    new cdk.CfnOutput(this, 'QueueArn', { value: arn })
```

> OutputStack.QueueArn = arn:aws:sqs:us-east-1:123456789012:myqueuename

**Comment by peterwoodworth** [comment]
The docstring for `resource` states:

> Resource type (e.g. "table", "autoScalingGroup", "certificate"). For some resource types, e.g. S3 buckets, this field defines the bucket name.

Could this be made more clear somehow?

**Comment by adambiggs** [comment]
This could definitely be made more clear by documenting how ARNs are structured for all services in a central place.

Or better yet, update `formatArn` or create a new helper that takes that cognitive load away from the user and just does the work. I would love to not have to think about this.

**Comment by peterwoodworth** [comment]
> This could definitely be made more clear by documenting how ARNs are structured for all services in a central place.

I'm not super sure what you mean by this exactly

> Or better yet, update formatArn or create a new helper that takes the cognitive load away from the user and just does the work. I would love to not have to think about this.

If you have an idea of how the user contract for this could improve, feel free to create a feature request with a proposed solution 🙂
