### ISSUE TITLE
aws_events_targets: AwsApi still on node 14

### ISSUE THREAD

**Issue by juweeks** [aws/aws-cdk#26963]
### Describe the bug

AwsApi stll on node v14. needs upgrade before that runtime is deprecated.

### Expected Behavior

node >14

### Current Behavior

node == 14

### Reproduction Steps

evt.AwsApi(
                service="Amplify",
                action="startDeployment",
                policy_statement=iam.PolicyStatement(
                    actions=[
                        "amplify:StartDeployment",
                        "s3:DeleteObject",
                        "s3:GetObject",
                        "s3:GetObjectAcl",
                        "s3:ListBucket",
                        "s3:PutObject",
                        "s3:PutObjectAcl",
                        "s3:PutObjectVersionAcl",
                    ],
                    resources=[fdfdasfds],
                ),
                parameters=dict(appId=webapp.app_id, branchName=branch, sourceUrl=fdfdsds)
                ),
            )

### CDK CLI Version

2.91

### Framework Version

2.91

### Node.js Version

v20.5.1

### OS

mac 13.4.1

### Language

Python

### Language Version

3.9.6

**Comment by cm-dyoshikawa** [comment]
It seems to have been resolved recently.

https://github.com/aws/aws-cdk/pull/26921

**Comment by juweeks** [comment]
good catch. thanks!

**Comment by jacklin213** [comment]
For anyone that stumbles upon this issue, the fix which was called out above has been released in version [2.94.0](https://github.com/aws/aws-cdk/releases/tag/v2.94.0)
