### ISSUE TITLE
(aws-ecs): add support for Amazon Linux 2023 in EcsOptimizedImage

### ISSUE THREAD

**Issue by layertwo** [aws/aws-cdk#26988]
### Describe the feature

Currently, the EcsOptimizedImage only provides hooks for Windows, Amazon Linux, and Amazon Linux 2. ECS is publishing a recommended ECS AMI for Amazon Linux 2023, however this is not implemented in the aws-ecs module.

### Use Case

I want to launch ECS instances with the latest Amazon Linux 2023 AMI.

### Proposed Solution

Expand EcsOptimizedImage to include a hook for Amazon Linux 2023. The same method for Amazon Linux and Amazon Linux 2 can be reapplied with a different `ec2.AmazonLinuxGeneration`.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.94.0

### Environment details (OS name and version, etc.)

Ubuntu 22.04 LTS

**Comment by pahud** [comment]
Agree we should create a static method for [EcsOptimizedImage](https://github.com/aws/aws-cdk/blob/d69c51a2e10864e69d4610b6df30d40a9bfec3ac/packages/aws-cdk-lib/aws-ecs/lib/amis.ts#L194)? e.g. 

```
EcsOptimizedImage.amazonLinux2023()
```
