### ISSUE TITLE
SageMaker-Domains: "Suggested code repositories for the domain" cannot be set

### ISSUE THREAD

**Issue by ttais2017** [aws/aws-cdk#26993]
### Describe the bug

The Builder of "CfnDomain" does not have a property for setting the "suggested code repositories" of the domain is being created.

![image](https://github.com/aws/aws-cdk/assets/26426283/96806ee6-ea8f-4f45-9ceb-a79641cee500)

### Expected Behavior

The Domain Builder includes a property for setting the "suggested code repositories"

### Current Behavior

The Builder of "CfnDomain" does not have a property for setting the "suggested code repositories" of the domain is being created.

![image](https://github.com/aws/aws-cdk/assets/26426283/96806ee6-ea8f-4f45-9ceb-a79641cee500)

Here the current API:

![image](https://github.com/aws/aws-cdk/assets/26426283/e5091794-7e25-4507-88e2-914fe9ee4b93)

As can be set, the "Environment"-tab does not have a related property within the Domain Builder.

### Reproduction Steps

The Builder of "CfnDomain" does not have a property for setting the "suggested code repositories" of the domain is being created.

![image](https://github.com/aws/aws-cdk/assets/26426283/96806ee6-ea8f-4f45-9ceb-a79641cee500)

### Possible Solution

extend the current Domain Builder with the property for setting the suggested code repositories

### CDK CLI Version

aws-cli/2.13.12 Python/3.11.4 Windows/10 exe/AMD64 prompt/off

### Node.js Version

9.5.1

### OS

Windows

### Language

Java

### Language Version

Java 17

**Comment by peterwoodworth** [comment]
This is an L1 CloudFormation resource, so if you need more functionality, then you'll need to reach out to CloudFormation at the [CloudFormation Coverage Roadmap](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues). If this is available in CloudFormation and is not yet available in CDK, then there's an automatic process for that and it will be in shortly from whenever it's introduced to CloudFormation.
