### ISSUE TITLE
aws-eks: do not use Python 3.7 Lambda runtime for the kubectl provider

### ISSUE THREAD

**Issue by plumdog** [aws/aws-cdk#26994]
### Describe the bug

AWS emailed me about the deprecation of the Python 3.7 Lambda runtime. Inspecting resources, found that - even where I'm on latest CDK - still have one using 3.7 due to the kubectl provider: https://github.com/aws/aws-cdk/blob/v2.94.0/packages/aws-cdk-lib/aws-eks/lib/kubectl-provider.ts#L138

(A quick review of https://github.com/search?q=repo%3Aaws%2Faws-cdk+PYTHON_3_7+language%3ATypeScript+path%3A%2F%5Epackages%5C%2Faws-cdk-lib%5C%2F%2F&type=code suggests this is the only remaining such Lambda, hence creating an issue for this Lambda specifically, rather than a general one.)

### Expected Behavior

For the CDK not to use Python 3.7 as it has an impending EOL.

### Current Behavior

Uses Python 3.7.

### Reproduction Steps

Deploy an EKS cluster with latest CDK (2.94.0), see it creates a Lambda for the kubectl provider handler that uses Python 3.7.

### CDK CLI Version

2.94.0

### Node.js Version

n/a

### OS

n/a

### Language

Typescript

**Comment by pahud** [comment]
Yes, according to this https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html we probably should bump to 3.8 or 3.9 before its deprecation (Phase 1).

**Comment by cwoebker** [comment]
We have now also been getting warning from AWS on the usage of this runtime. Would be best to have an update available before 27.11.2023. 

> As described in the Lambda runtime support policy [2], end of support for language runtimes in Lambda happens in two stages. Starting November 27, 2023, Lambda will no longer apply security patches and other updates to the Python 3.7 runtime used by Lambda functions, and functions using Python 3.7 will no longer be eligible for technical support. In addition, you will no longer be able to create new Lambda functions using the Python 3.7 runtime. Starting January 25, 2024, you will no longer be able to update existing functions using the Python 3.7 runtime.

>We recommend that you upgrade your existing Python 3.7 functions to Python 3.11 before November 27, 2023.
