### ISSUE TITLE
aws-stepfunctions: comment field appears not supported

### ISSUE THREAD

**Issue by berenddeboer** [aws/aws-cdk#27005]
### Describe the feature

When editing a state machine via the AWS Console, I could provide a comment for a choice rule. It suggest my state language will look like this:

```json
    "Verification needed?": {
      "Type": "Choice",
      "Choices": [
        {
          "Variable": "$.verification_needed",
          "IsBoolean": true,
          "Next": "Set status to pending verification",
          "Comment": "yes"
        }
      ],
      "Default": "Wait for approval"
    },
```

This "yes" comment gets nicely displayed in the graph. However, I could not see a way to generate this comment field withi CDK. Is that correct?

Are there any plans to introduce that? Really great for more complex flows.

Unfortunately this comment is only visible in the editor, not in the "Definition" tab.

### Use Case

Improve output of state machine graph.

### Proposed Solution

Add a property or optional input to `sfn.Condition.isBoolean()`.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.91.0

### Environment details (OS name and version, etc.)

Mac x86_64, Darwin kernel 22.6.0

**Comment by msambol** [comment]
@mrgrain I'll take this. It's there but not implemented.

https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-stepfunctions/lib/states/choice.ts#L17

**Comment by msambol** [comment]
> @mrgrain I'll take this. It's there but not implemented.
> 
> https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-stepfunctions/lib/states/choice.ts#L17

I linked the wrong type of comment jfyi. That is working as expected. But my PR adds the requested comment.

**Comment by khushail** [comment]
Thanks @berenddeboer for reaching out with this request. Thanks @msambol for submitting a PR. Appreciate your contribution.
