### ISSUE TITLE
(IAM): (Adding multiple AccountPrincipal to a role)

### ISSUE THREAD

**Issue by RonLek** [aws/aws-cdk#27017]
### Describe the bug

Through the console, I can add multiple principals by specifying the account ids as a list.

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": ["account_id1", "account_id2"]
            },
            "Action": "sts:AssumeRole"
        }
    ]
}
```

How do I achieve this via the CDK? I tried using `CompositePrincipal` but later realized it only accepts `ServicePrincipal` as parameters.

### Expected Behavior

Expected `cdk synth` to produce output like when modifying through console above. If `CompositePrincipal` does not take in `AccountPrincipal` it should error out during synth.

### Current Behavior

When specifying account Id within `CompositePrincipal` I get the following on `cdk synth` without any errors.

```json
"Role1": {
      "Type": "AWS::IAM::Role",
      "Properties": {
        "AssumeRolePolicyDocument": {
          "Statement": [
            {
              "Action": "sts:AssumeRole",
              "Effect": "Allow",
              "Principal": {
                "AWS": {
                  "Fn::Join": [
                    "",
                    [
                      "arn:",
                      {
                        "Ref": "AWS::Partition"
                      },
                      ":iam::account_id_1:root"
                    ]
                  ]
                }
              }
            },
            {
              "Action": "sts:AssumeRole",
              "Effect": "Allow",
              "Principal": {
                "AWS": {
                  "Fn::Join": [
                    "",
                    [
                      "arn:",
                      {
                        "Ref": "AWS::Partition"
                      },
                      ":iam::account_id_2:root"
                    ]
                  ]
                }
              }
            }
          ],
          "Version": "2012-10-17"
        },
        "Description": "IAM role for outside AWS accounts to call send_ses_email lambda",
        "Policies": [
         {inline_policies}
        ],
        "RoleName": "Role1"
      },
    },
```

### Reproduction Steps

Use `AccountPrincipal` as argument to `CompositePrincipal`.

### CDK CLI Version

2.87.0

### Node.js Version

v16.3.0

### OS

Amazon Linux

### Language

Typescript

**Comment by peterwoodworth** [comment]
Aren't these statements identical in functionality?

**Comment by RonLek** [comment]
My bad, you're correct. On a closer look the join statement does produce the same principal. The `CompositePrincipal` doc only lists `ServicePrincipal` which made me think you could not use `AccountPrincipal` with it. Thanks.

**Comment by abhi7cr** [comment]
Although these are identical behaviors at runtime, we could run into character limits (2048) more easily with cdk v2. We ran across this issue when migrating from v1 to v2 since we had a large list of account ids that were previously under 1 statement, but now separated into their own. Is there any way we can override this behavior ?

**Comment by abhi7cr** [comment]
I was able to get around with a custom principal:
```
import { ArnPrincipal, Conditions, PrincipalBase, PrincipalPolicyFragment } from 'aws-cdk-lib/aws-iam';

export default class CustomCompositePrincipal extends PrincipalBase {
  /**
   *
   */
  constructor(principals: ArnPrincipal[], conditions: Conditions = {}) {
    super();
    this.policyFragment = {
      principalJson: {
        AWS: principals.map((p) => p.arn),
      },
      conditions,
    };
  }

  policyFragment: PrincipalPolicyFragment;

  // eslint-disable-next-line
  dedupeString(): string | undefined {
    return undefined;
  }
}
```
