### ISSUE TITLE
(aws-cdk-lib/aws-ec2): (Request to update Windows Version enum list)

### ISSUE THREAD

**Issue by aashishgk7760** [aws/aws-cdk#27019]
### Describe the feature

As per latest version of the CDK 2.94.0 (build 987c329) , whenever we are creating a Windows instance , there are few AMI version which are not available in the list of enums https://github.com/aws/aws-cdk/tree/main/packages/aws-cdk-lib/aws-ec2/lib/windows-versions.ts. 

Example : we don't have the Microsoft Windows Server 2019 Full Locale English with SQL Standard 2019 AMI provided by Amazon enum value. 

### Use Case

Instead of using LookupMachineImage , if we can have the updated list ,its easier to manage by directly referring to enum value. 

### Proposed Solution

Add a Enum value WINDOWS_SERVER_2019_ENGLISH_FULL_SQL_2019_Standard

example: 

export enum WindowsVersion {

WINDOWS_SERVER_2019_ENGLISH_FULL_SQL_2019_Standard : ''Windows_Server-2019-English-Full-SQL_2019_Standard'
}

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

CDK 2.94.0 (build 987c329

### Environment details (OS name and version, etc.)

Mac OS

**Comment by khushail** [comment]
Thanks @aashishgk7760  for submitting this feature request.

**Comment by msambol** [comment]
@khushail please assign me

**Comment by msambol** [comment]
@khushail / @mrgrain – There are quite a few missing from the [file](https://github.com/aws/aws-cdk/tree/main/packages/aws-cdk-lib/aws-ec2/lib/windows-versions.ts) compared to what's returned by the CLI:
```bash
aws ssm get-parameters-by-path --path "/aws/service/ami-windows-latest" --region us-east-1 | jq '.Parameters | .[] | .Name' | grep Windows_Server
```

**97** by my count. Do you want me to add them all?
