### ISSUE TITLE
lambda: Lambdas can connect and execute queries against RDS without any related IAM policies

### ISSUE THREAD

**Issue by suharsha** [aws/aws-cdk#27022]
### Describe the bug

Recently I moved few of my Lambdas in to the same VPC as the RDS as suggested by [cdk-nag](https://github.com/cdklabs/cdk-nag/tree/main). Then to adjust RDS permissions on those Lambdas, I removed all RDS IAM policies which they had initially and did some tests. They were still able to connect to the RDS and run queries too even without any RDS related IAM permissions.

### Expected Behavior

Lambdas without proper RDS IAM permissions should not be able to connect to RDS or run queries in RDS. They should log an error and specify which permissions are missing.

### Current Behavior

Lambdas can connect and execute queries on RDS without any RDS related policies

### Reproduction Steps

Deploy a Lambda with code to connect to RDS and run a query without any RDS policies

### CDK CLI Version

2.93.0

### Node.js Version

18

### OS

MacOS

### Language

Typescript

### Language Version

4.9.5

**Comment by msambol** [comment]
What type of [auth](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/database-authentication.html) is the Lambda doing? Is it fetching secrets from Secrets Manager? As far as _connecting_ to RDS, that depends on the security group attached to the RDS instance.

**Comment by peterwoodworth** [comment]
Thanks for the response @msambol, @suharsha if this doesn't help, could you provide the code necessary to reproduce the issue you're experiencing?
