### ISSUE TITLE
aws-cdk-lib: Missing tags when cfn is synthesized from the app

### ISSUE THREAD

**Issue by xavi-bean** [aws/aws-cdk#27024]
### Describe the bug

When adding stack [tags](https://docs.aws.amazon.com/cdk/v2/guide/tagging.html) using `Tags.of(stackname).add("key", "value")` it works great until CDK version 2.87. However, when synthesizing the stacks using cdk versions >=2.88 (latest version 2.94 also tested and failing) the tags disappear from the stacks.

### Expected Behavior

Tags should apply to all child constructs once the stack is synthesized, the same way it has been doing until aws-cdk-lib version <=2.87.

### Current Behavior

Tags are not generated when the stacks are built.

### Reproduction Steps

I apply tags at stack entry point level through app.py, the same way showed in the [documentation](https://docs.aws.amazon.com/cdk/v2/guide/tagging.html) `Tags.of(stackname).add("key", "value")` (this has been working until v.2.87).

### Additional Information/Context

This is similar (or the same) bug that was reported in past: https://github.com/aws/aws-cdk/issues/26169. Apparently this was fixed in cdk v. 2.87 (it appears in its changelog) but seems broke again in versions >=2.88.
Have opened a case to aws support and they have said me to open this issue in order to be able to publicly track its fixing status.

### CDK CLI Version

2.94

### Node.js Version

20.3.0

### OS

Linux / macOS

### Language

Python

**Comment by peterwoodworth** [comment]
There was a similar issue reported [here](https://github.com/aws/aws-cdk/issues/26495) - It seems to me that the issue starts appearing on `2.81.0` using the code in that issue. Could you please provide a reproduction snippet if it's `2.88.0` where you start seeing the issue?
