### ISSUE TITLE
(autoscaling): applyCloudFormationInit on each launchTemplateOverrides of mixedInstancesPolicy

### ISSUE THREAD

**Issue by BDeus** [aws/aws-cdk#27030]
### Describe the feature

In the Construct autoscaling when setting a CloudFormationInit, the UserData is apply on the LaunchTemplate attach to the ASG.

https://github.com/aws/aws-cdk/blob/e260d30dab3815e2bd650df5b61ad7aa8fb72ea8/packages/aws-cdk-lib/aws-autoscaling/lib/auto-scaling-group.ts#L1528-L1536

In case of usage of a MixedInstancesPolicy with LaunchTemplateOverrides, the overrides do not inherit from the UserData of the CloudFormationInit

### Use Case

In case on multiple LaunchTemplate (ARM and x86 as example) the second one does apply the CloudFormationInit?
I do not know how to add the UserData on [LaunchTemplateOverrides](https://github.com/aws/aws-cdk/blob/e260d30dab3815e2bd650df5b61ad7aa8fb72ea8/packages/aws-cdk-lib/aws-autoscaling/lib/auto-scaling-group.ts#L559).

### Proposed Solution

add the ability to copy the UserData of the main LaunchTemplate to every LaunchTemplates overrides on a MixedInstancesPolicy

### Other Information

If anyone as a workaround solution, i'll be grateful

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.93.0

### Environment details (OS name and version, etc.)

linux

**Comment by indrora** [comment]
While I believe this is the case, what would this look like in CloudFormation? Could you build this in CloudFormation?
