### ISSUE TITLE
aws_s3.Bucket: add_event_notification example doesn't work

### ISSUE THREAD

**Issue by bencaldwell** [aws/aws-cdk#27038]
### Describe the issue

This is the example from the docs:

```
# my_lambda: lambda.Function
bucket = s3.Bucket(self, "MyBucket")
bucket.add_event_notification(s3.EventType.OBJECT_CREATED, s3n.LambdaDestination(my_lambda), prefix="home/myusername/*")
```
cdk synth throws an error from this: `TypeError: BucketBase.add_event_notification() got an unexpected keyword argument 'prefix'`

The below is what I ended up having to use. Perhaps the example should be changed to something like this:
```
# my_lambda: lambda.Function
bucket = s3.Bucket(self, "MyBucket")
bucket.add_event_notification(s3.EventType.OBJECT_CREATED, s3n.LambdaDestination(my_lambda), s3.NotificationKeyFilter(prefix="home/myusername/*"))
```

### Links

https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_s3/Bucket.html

**Comment by msambol** [comment]
Weird, the comment is correct [here](https://github.com/aws/aws-cdk/blob/6f3e8386f483fe715a4ce7dc8e54e87843400030/packages/aws-cdk-lib/aws-s3/lib/bucket.ts#L881). Maybe whatever is rending the Python docs has a bug?

**Comment by bencaldwell** [comment]
That link just has `{prefix: 'home/myusername/*'}` - perhaps that doesn't tell what is rendering the python docs that it needs to be a list of s3.NotificationKeyFilter() objects.

**Comment by msambol** [comment]
@bencaldwell Take a look here: https://github.com/aws/aws-cdk/issues/8100. They mention limitations in Python doc generation.

**Comment by khushail** [comment]
Hi @bencaldwell , python and other language docs are generated by jsii-codegen and our original documentation is written in typescript. Here is an actual example of adding event notification in typescript- https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_s3.Bucket.html#addwbreventwbrnotificationevent-dest-filters -

`public addEventNotification(event: EventType, dest: IBucketNotificationDestination, ...filters: NotificationKeyFilter[]): void`
