### ISSUE TITLE
(BackupPlanRule): the completion_window default value does not match the documentation

### ISSUE THREAD

**Issue by dilpreetSingh12** [aws/aws-cdk#27050]
### Describe the bug

https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_backup/BackupPlanRule.html states that completion_window default value is 8 hours but it is set to 7 days.

### Expected Behavior

completion_window default value shall be set to 8 hours 

### Current Behavior

completion_window default value is set to 7 days. 

### Reproduction Steps

Create a backplan rule via aws cdk python.

### CDK CLI Version

2.85.0

### Node.js Version

v18.13.0

### OS

mac

### Language

Python

**Comment by peterwoodworth** [comment]
Yep, can confirm this. Thanks for reporting, it's likely that this got mixed up with the default for `startWindow`. Would need to change the docstring here https://github.com/aws/aws-cdk/blob/987c329e26a31f29842a597fae9112c35c7eba88/packages/aws-cdk-lib/aws-backup/lib/rule.ts#L13

**Comment by lpizzinidev** [comment]
@peterwoodworth 
I don't see the default values for `completionWindow` and `startWindow` being set [when a new rule is added to the backup plan](https://github.com/aws/aws-cdk/blob/ffd4b7d7897c34b43bb5f80edb9c42024df98776/packages/aws-cdk-lib/aws-backup/lib/plan.ts#L172).
Shouldn't we fall back to the declared defaults if the two attributes are not defined?

**Comment by kaizencc** [comment]
@lpizzinidev sometimes we default to the cloudformation defaults but declare those in documentation for cdk. That looks like what is happening here.
