### ISSUE TITLE
Modify clusterRole in ICluster or apply k8s manifest in imported Cluster(ICluster)

### ISSUE THREAD

**Issue by oliverdavidnoguerasanmartin** [aws/aws-cdk#27086]
### Describe the feature

I want to modify clusterRole of existing imported Cluster, so ICluster.
ICluster doesn't have any way to make this and apply "

### Use Case

```
 KubernetesManifest(
            scope,
            id,
            KubernetesManifestProps
                    .builder()
                    .cluster(eksCluster)
                    .manifest(listOf(manifestMap))
                    .build()
```

### Other Information

I think i have this error "Exception in thread "main" software.amazon.jsii.JsiiError: "kubectlRole" is not defined, cannot issue kubectl commands against this cluster"  by this reason.

### Acknowledgements

- [X] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### CDK version used

2.90.0

### Environment details (OS name and version, etc.)

github actions

**Comment by indrora** [comment]
Imported resources cannot be modified in CDK, only referenced, except where there is a means to do so in CloudFormation.
