### ISSUE TITLE
@aws-cdk/aws-lambda-python-alpha: allow "--without-urls" option to poetry export

### ISSUE THREAD

**Issue by lokucrazy** [aws/aws-cdk#27103]
### Describe the feature

I would like the poetry export command to be able to export without the url.

### Use Case

the projects I would like to use cdk and poetry with use an authenticated codeartifact url for dependencies which are sourced in the pyproject.toml.

When Poetry exports a requirements.txt it has an un-auth'd URL in the file which causes any install to fail waiting for username and password input.  Being able to export without a url would fix this problem.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.85.0

### Environment details (OS name and version, etc.)

Mac OS 13.5.1 (22G90)

**Comment by khushail** [comment]
Hi @lokucrazy , thanks for reaching out. Looking at the [existing packaging props](https://github.com/aws/aws-cdk/blob/a12470696d7450971f1af58cdeb2413a87777b64/packages/%40aws-cdk/aws-lambda-python-alpha/lib/packaging.ts#L61), this request would be a good addition to have.

**Comment by msambol** [comment]
@khushail I'll take this.

**Comment by khushail** [comment]
sounds good. Thanks @msambol

**Comment by lokucrazy** [comment]
@msambol thank you!
