### ISSUE TITLE
aws-codepipeline-actions integ test not working

### ISSUE THREAD

**Issue by mrgrain** [aws/aws-cdk#27117]
`aws-codepipeline-actions/test/integ.pipeline-elastic-beanstalk-deploy.ts` is currently not working.

During the execution of the CodePipeline, the file `aws-codepipeline-actions/test/assets/nodejs.zip` is accessed. This is supposed to be a ZIP archive of configuration for ElasticBeanstalk. However the file is corrupted now and not a working ZIP archive anymore.

I suspect we just need to track down a working version of this file and we are good. Potentially exists on an earlier commit or the v1 branch.

This is not a bug in the construct, it is simply a broken integ test.

**Comment by msambol** [comment]
@peterwoodworth I'll take this.
