### ISSUE TITLE
(aws-cdk): (To be able to create in the same stack: an EFS, EFS access point, and EFS file system policy to govern that access point)

### ISSUE THREAD

**Issue by JayeMcC** [aws/aws-cdk#27123]
### Describe the feature

I want to create an EFS, EFS access points, and EFS file system policies that govern those access points in the same stack.

### Use Case

This causes a circular dependency error (as we refer to the access point ID in the policy).

The current (ridiculous) workaround if you don't want to do things manually is to create the EFS and access points in one stack, then in a new stack, use a lambda to query the now-created EFS by name, then retrieve the access points to pull the ids off of. All up it's ~250 lines of code that shouldn't need to be there.

### Proposed Solution

Split efs policy out to a separate resource.

### Other Information

I encountered this while using CDK, expecting it to work a certain way. The underlying issue may be a CloudFormation issue more than the CDK, but the proposal in CloudFormation has been dead since 2021: https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/900

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.95.1 (build ae455d8)

### Environment details (OS name and version, etc.)

macOS Ventura 13.5.1 (22G90)

**Comment by peterwoodworth** [comment]
Yeah, we would need that cloudformation support first. the workaround will have to do for now

**Comment by kukkunuruanil** [comment]
I was able to test this using the attached template, which worked. 
Replace the (KMS Keys, UUID/GUID) from the template. Please modify accordingly as per your requirements.


AWSTemplateFormatVersion: 2010-09-09
Description: This template deploys EFS File Systems
Parameters:
  EFSSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
    Description: VPC Security group for the EFS file system.
  EFSSubNetId1:
    Type: AWS::EC2::Subnet::Id
    Description: VPC Subnet ID 1 for the EFS file system; this subnet should be apart of the VPC associated with the security group.
  EFSSubNetId2:
    Type: AWS::EC2::Subnet::Id
    Description: VPC Subnet ID 2 for the EFS file system; this subnet should be apart of the VPC associated with the security group.

Resources:
  EFSFileSystem:
    Type: AWS::EFS::FileSystem
    UpdateReplacePolicy: Retain
    Properties:
      BackupPolicy: 
        Status: DISABLED
      PerformanceMode: generalPurpose
      ThroughputMode: bursting 
      Encrypted: true
      KmsKeyId: arn:aws:kms:us-west-2:1234567890:key/abcder-b546-44e4-9055-ec32458610
      FileSystemTags:
        - Key: data_residency
          Value: canada
        - Key: environment
          Value: dev
      FileSystemPolicy: 
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "elasticfilesystem:*"
            Principal:
              AWS: "*"
            Condition:
              Bool:
                'elasticfilesystem:AccessedViaMountTarget': "true"
          - Effect: "Deny"
            Action:
              - "*"
            Principal:
              AWS: "*"
            Condition:
              Bool:
                'aws:SecureTransport': "false"          
          - Effect: "Allow"
            Principal:
              AWS: "*"
            Action:
              - elasticfilesystem:ClientMount
              - elasticfilesystem:ClientWrite
            Resource: "*"

  MountTargetResource1:
    Type: AWS::EFS::MountTarget
    UpdateReplacePolicy: Retain
    Properties:
      FileSystemId: !Ref EFSFileSystem
      SubnetId: !Ref EFSSubNetId1
      SecurityGroups: 
        - !Ref EFSSecurityGroup

  MountTargetResource2:
    Type: AWS::EFS::MountTarget
    UpdateReplacePolicy: Retain
    Properties:
      FileSystemId: !Ref EFSFileSystem
      SubnetId: !Ref EFSSubNetId2
      SecurityGroups: 
        - !Ref EFSSecurityGroup

  EFSAccessPoint:
    Type: AWS::EFS::AccessPoint
    Properties:
      FileSystemId: !Ref EFSFileSystem
      PosixUser:
        Uid: "100"
        Gid: "100"
      RootDirectory:
        CreationInfo:
          OwnerGid: "708798"
          OwnerUid: "7987987"
          Permissions: "0755"
        Path: "/testcfn/abc"
