### ISSUE TITLE
ecs: Breaking change in v2.96.0 - from_ecr_repository() got an unexpected keyword argument 'tag'

### ISSUE THREAD

**Issue by adam-kiss-sg** [aws/aws-cdk#27139]
### Describe the bug

Our CI/CD pipeline using cdk with python started reporting an error: `TypeError: from_ecr_repository() got an unexpected keyword argument 'tag'`

### Expected Behavior

No error.

### Current Behavior

TypeError: from_ecr_repository() got an unexpected keyword argument 'tag'

### Reproduction Steps

use 
```
ecs.ContainerImage.from_ecr_repository(
                        repository=repo,
                        tag=image_tag,
                    )
```

### Possible Solution

Please revert this change: https://github.com/aws/aws-cdk/commit/9f079110d55b77be57d564d9659c9b923ed8b60c , because this is a breaking change.

### CDK CLI Version

2.96.0

### Node.js Version

irrelevant

### OS

irrelevant

### Language

Python

### Language Version

irrelevant

**Comment by Annegies** [comment]
I also encountered this issue, would have expected it to be backwards compatible
