### ISSUE TITLE
(dynamodb): Dynamo TableV2 does not support tagging replicas

### ISSUE THREAD

**Issue by mikevec23** [aws/aws-cdk#27146]
### Describe the feature

I would like to be able to supply tags to the primary and secondary replicas within the TableV2 GlobalTable construct.

### Use Case

I need to be able to tag specific replicas in order to allow those replicas to be detected by other applications.

### Proposed Solution

Tags already exist on the CfnGlobalTable.ReplicaSpecificationProperty type so we simply need to allow the property to be passed to either the TablePropsV2 (for the primary replica) or ReplicaTableProps (for the secondary replicas). Both of these interfaces extend the TableOptionsV2 interface so I would propose the update be added there. Additionally there are some small changes needed to use the tags when configuring the promary replica and  when performing the configureReplicaTable method. All these changes are outlined in the attached screenshot of the proposed diff.

![Proposed Changes](https://github.com/aws/aws-cdk/assets/19393815/97716436-629d-4ba4-a8d2-416fac78eb9b)

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.96.0

### Environment details (OS name and version, etc.)

Node 20.6.1, Mac

**Comment by khushail** [comment]
Hi @mikevec23 , looks like your request is similar to this one - https://github.com/aws/aws-cdk/issues/14943

**Comment by mikevec23** [comment]
@khushail Similar but not the same. Both #14943 and #26891 are in reference to the CfnGlobalTable L1 construct and the taggability of the top level entity. 

CfnGlobalTable does however allow tagging of each replica independently (I know because I'm already doing this today) but this newly created TableV2 L2 construct is not mapping tags to the CfnGlobalTable replicas underneath which is possible with the minor changes I've proposed above.

**Comment by khushail** [comment]
Thanks @mikevec23 for the clarification there.

**Comment by mikevec23** [comment]
Any updates on this? It was "self-assigned" a month ago so I figured it would have been worked on shortly after, but if that's not the case I could easily make these changes myself.

**Comment by colifran** [comment]
@mikevec23 this isn't currently being prioritized by our team, but we're always happy to take PRs! I've removed my assignment on this. Please feel free to work on this.
