### ISSUE TITLE
(aws-cloudwatch): Error while creating a cloudwatch alarm with 10 metrics

### ISSUE THREAD

**Issue by andreprawira** [aws/aws-cdk#27144]
### Describe the bug

I'm trying to create a cloudwatch alarm using math expressions that contains more than 10 metrics but i'm seeing an error instead

### Expected Behavior

expecting to create more than 10 individual metrics

### Current Behavior

`RuntimeError: Alarms on math expressions cannot contain more than 10 individual metrics` error message

### Reproduction Steps

```
math_expression = cw.MathExpression(
            label="test label",
            expression="IF(e9 OR e10, 1, 0)",
            using_metrics={
                "e9": rds_e9_metric,
                "e7": rds_e7_metric,
                "e2": rds_e2_metric,
                "m2": rds_m2_metric,
                "e3": rds_e3_metric,
                "m1": rds_m1_metric,             
                "e8": rds_e8_metric,
                "e5": rds_e5_metric,      
                "m5": rds_m5_metric,           
                "e10": rds_e10_metric,
                "e1": rds_e1_metric,
                "m3": rds_m3_metric,                
                "e6": rds_e6_metric,
                "m6": rds_m6_metric
            },
            period=cdk.Duration.minutes(5),
        )
```
this will cause the 10 individual metric error, any idea how to bypass it? seems like an unnecessary limitation

### CDK CLI Version

2.51.0 (build a87259f)

### Node.js Version

16.18.0

### OS

Windows

### Language

Python

**Comment by khushail** [comment]
Hi @andreprawira , thanks for reaching out. Yes, its a limitation from our side as clearly indicated in the docs [here](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch_limits.html).There are no direct solution to bypass this but you could try using multiple [math expressions](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/AlarmThatSendsEmail.html#alarms-on-metric-math-expressions) with distributed number of metrics.e.g 2 alarms with 5 metrics each. You could then use an [EventBridge](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/AlarmThatSendsEmail.html#alarms-and-EventBridge) rule to trigger an action when either alarm goes into the ALARM state.
