### ISSUE TITLE
(apigatewayv2-integrations): Specify `AWS` type integration on WebSocketLambdaIntegration

### ISSUE THREAD

**Issue by peterwoodworth** [aws/aws-cdk#27150]
### Describe the feature

Currently this is not possible without escape hatches, since it will always set it to `AWS_PROXY` https://github.com/aws/aws-cdk/blob/dc87d28110403f6223ed2ee506c35bc79fc7835e/packages/%40aws-cdk/aws-apigatewayv2-integrations-alpha/lib/websocket/lambda.ts#L48

### Use Case

It appears to be valid configuration looking at [Cfn docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigatewayv2-integration.html#cfn-apigatewayv2-integration-integrationtype), someone asked how to accomplish this in [this discussion](https://github.com/aws/aws-cdk/discussions/27073)

### Proposed Solution

Add new prop to `WebSocketLambdaIntegration`

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

latest

### Environment details (OS name and version, etc.)

mac

**Comment by JobaDiniz** [comment]
It's not a lambda integration. I do not need to define any lambda. It's a direct integration from WebSocket to an AWS service, like step function.
WebSocket to call Step Function directly, without requiring lambda.

**Comment by peterwoodworth** [comment]
OK, feel free to create a feature request for a high level pattern that you would like to see supported 🙂

**Comment by JobaDiniz** [comment]
Created a detailed enhancement request here: https://github.com/aws/aws-cdk/issues/27164
