### ISSUE TITLE
(aws-ecs): support RuntimePlatform Property at TaskDefinition class for govcloud

### ISSUE THREAD

**Issue by arun-annamalai** [aws/aws-cdk#27169]
### Describe the bug

When I deploy a ECS task definition via CDK in the commercial region I am able to go into the console and verify that the created task definition has a RuntimePlatform. When I do the same in a govcloud region, the task definition does not get created with a RuntimePlatform and the cloudformation stack indicates a drift. 

### Expected Behavior

When I deploy a task definition that contains a RuntimePlatform through CDK into govcloud region, the task definition should have a runtime platform when inspected in the console. 

### Current Behavior

The task definition gets created, but the RuntimePlatform field is not created. 

### Reproduction Steps

You can reproduce this by deploying the same task definition with a RuntimePlatform to us-east-1 and us-gov-east-1 (or us-gov-west-1). You will notice the govcloud task definition does not have a RuntimePlatform. 

### CDK CLI Version

2.59.0 (build b24095d)

### Node.js Version

Node.js v20.3.0

### OS

Mac

### Language

Typescript

**Comment by peterwoodworth** [comment]
I don't think this is a CDK issue, the template is still generating with these properties when setting the region, and the CloudFormation spec says that these properties can be used [for this region](https://s3.us-gov-east-1.amazonaws.com/cfn-resource-specifications-us-gov-east-1-prod/latest/CloudFormationResourceSpecification.json). I recommend you reach out to CloudFormation about this
