### ISSUE TITLE
aws-msk-alpha: edit cluster config will cause cluster recreation

### ISSUE THREAD

**Issue by leo-li-wcq** [aws/aws-cdk#27173]
### Describe the bug

After editing the server properties for the cluster Config, the clusterConfig does not update in place, it will create a new cluster and delete the existing cluster. 

`    this.clusterConfig = new CfnConfiguration(this, 'kafka-cluster-config', {
      name: `${clusterName}-kafka-config`,
      serverProperties: kafkaClusterConfigOptionsToEnable ? generateClusterConfig( kafkaClusterConfigOptionsToEnable ) : ''
    });
`

### Expected Behavior

After editing the server properties for the cluster Config, the clusterConfig should update in place and not cause cluster recreation.

### Current Behavior

Editing cluster config will cause cluster recreation.

### Reproduction Steps

1. Create a new cluster.
2. Modify values in serverProperties.
3. Run CDK against the existing stack, it will trigger cluster recreation.

### CDK CLI Version

2.93.0 (build 724bd01)

### Node.js Version

v18.17.1.

### OS

MacOS

### Language

Typescript

**Comment by peterwoodworth** [comment]
If your diff is only showing changes to `ServerProperties`, then this seems [misdocumented or bugged on CloudFormation's end](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-msk-configuration.html#cfn-msk-configuration-serverproperties). Cloudformation is seeing the changes in the template and they are the ones doing resource replacement, we're just creating the template.

**Comment by leo-li-wcq** [comment]
Thanks @peterwoodworth We got it fixed, not related to the cluster Config, it's actually a code change in the cluster name, closing this issue.
