### ISSUE TITLE
(aws-lambda-nodejs): (Lack of client-scheduler in @aws-sdk/* included in Node18 runtime )

### ISSUE THREAD

**Issue by valex91** [aws/aws-cdk#27180]
### Describe the bug

Deploying a NodeJS function with a Node18 runtime fails at runtime as the nodeJSFunction construct default

```
bundling: {
        externalModules: ['@aws-sdk/*'],
      },
```
which mean that expect every @aws/sdk module already present in the lambda runtime, but since the current NodeJS18 runtime uses SDK version `3.188.0` and the @aws/client-scheduler has been introduce since 
3.208 (https://github.com/aws/aws-sdk-js-v3/releases/tag/v3.208.0) 

### Expected Behavior

Runtime to include an up to date @aws/sdk / option to include the missing @aws/sdk which does not require to declare all the used one explicitly in externalModules.

### Current Behavior

`Error: Cannot find module '@aws-sdk/client-scheduler'` once the Lambda gets invoked.

### Reproduction Steps

- create a new cdk stack with `cdk init`
- declare a NodeJS function in the stack 

```
 new NodejsFunction(this, "test", {
      runtime: Runtime.NODEJS_18_X,
      entry: join(__dirname, "./handler.ts"),
    });
  }
```
```
// handler.ts
import { SchedulerClient } from "@aws-sdk/client-scheduler"

const schedulerClient = new SchedulerClient()

export const handler = () => {
    // do stuff
}
```

invoke the lambda with any method will result in `"Error: Cannot find module '@aws-sdk/client-scheduler'
`

### Additional Information/Context

A possibile workaround for the issue is to declare explicitly in the lambda configuration, so that the default '@aws-sdk/*' is overwritten.

e.g:
```
      externalModules: [
          '@aws-sdk/client-dynamodb',
          '@aws-sdk/client-secrets-manager',
          '@aws-sdk/client-ssm',
        ],
```

### CDK CLI Version

2.83.1 (build 006b542)

### Node.js Version

v16.20.0

### OS

Mac OSX

### Language

Typescript

**Comment by peterwoodworth** [comment]
Hey @valex91,

I believe [this issue](https://github.com/aws/aws-cdk/issues/26681) is the same as the core issue you're experiencing here :)

**Comment by cshields236** [comment]
This is an issue I have recently come across this problem too and I don't believe that the linked issue is a duplicate or fixes the problem.

**Comment by PaulRose112358** [comment]
Odd that I would create a lambda function within the AWS editing environment, specify the "latest" and get this error. Any idea when it will be corrected?
