### ISSUE TITLE
aws-batch: MultiNodeJobDefinition Incorrectly Requires InstanceType

### ISSUE THREAD

**Issue by SeanStockwell** [aws/aws-cdk#27185]
### Describe the bug

It seems that the Batch [MultiNodeJobDefinition CDK Construct](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_batch.MultiNodeJobDefinition.html) requires instance type to be defined. However, instanceType is not required by the Batch AWS SDK.

This seems to be more than a documentation issue, as I'm unable to create a MultiNodeJobDefinition in my CDK package without specifying instance type.

This constraint takes away from one of the primary advantages to having Batch manage our EC2 resources in that they optimally assign batch jobs to instance types based on availability/resource requirements.

### Expected Behavior

We shouldn't need to specify instance type. Batch should determine it based on job resource requirements.

### Current Behavior

CDK requires instance type to be required at job definition level.

### Reproduction Steps

Create a MultiNodeJobDefinition.

### CDK CLI Version

2.96.2

### Node.js Version

18.x

### OS

linux

### Language

Typescript

**Comment by indrora** [comment]
This is because multinode jobs (through a quirk of CloudFormation) requires it. 

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-batch-jobdefinition-containerproperties.html#cfn-batch-jobdefinition-containerproperties-instancetype

**Comment by SeanStockwell** [comment]
The link you provided says that InstanceType is not required

**Comment by peterwoodworth** [comment]
Maybe @comcalvi can comment on why this is required, but as far as I can tell it isn't required in CloudFormation. I implemented this aspect on my stack and successfully deployed.

```ts
class BatchContainerDefinitionModifier implements cdk.IAspect {
  public visit(node: IConstruct): void {
    // will need to be stricter in search if you are creating other job definitions
    if (node instanceof batch.CfnJobDefinition) {
      node.addPropertyDeletionOverride('NodeProperties.NodeRangeProperties.0.Container.InstanceType')
      node.addPropertyDeletionOverride('NodeProperties.NodeRangeProperties.1.Container.InstanceType')
      // repeat for as many containers as necessary
    }
  }
}

cdk.Aspects.of(stack).add(new BatchContainerDefinitionModifier());
```

repro stack
```ts
    const def = new batch.MultiNodeJobDefinition(this, 'JobDefinition', {
      instanceType: new ec2.InstanceType('m5.large'),
    });

    def.addContainer({
      startNode: 0,
      endNode: 5,
      container: new batch.EcsEc2ContainerDefinition(this, 'multiContainer', {
        image: ecs.ContainerImage.fromRegistry('amazon/amazon-ecs-sample'),
        cpu: 256,
        memory: cdk.Size.mebibytes(2048),
      })
    });

    def.addContainer({
      startNode: 6,
      endNode: 10,
      container: new batch.EcsEc2ContainerDefinition(this, 'multiContainer2', {
        image: ecs.ContainerImage.fromRegistry('amazon/amazon-ecs-sample'),
        cpu: 256,
        memory: cdk.Size.mebibytes(2048),
      })
    });
```
