### ISSUE TITLE
Move to modular versioning

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#272]
At the moment, the entire repository has a single version. We should move to per-module versioning when we start publishing to package managers.

Some issues to consider:

- How do we version the global CDK project? This is relevant for github releases and for the documentation website
- We need to include specific version numbers for each module in the docs website
- Lerna doesn't respect semantic pre-1.0 bumps. This means that any minor change will cause the "Y" component of the version ("X.Y.Z") to be bumped, which in pre 1.0 is considered a breaking change, and not what we want (see https://github.com/strongloop/loopback-next/issues/1068, https://github.com/npm/node-semver/issues/177)

**Comment by fulghum** [comment]
Pulled this off the GA planning board since we found a way to avoid this work for GA
