### ISSUE TITLE
Alpha Modules: Pre-release semantic version causes resolution issues with peer dependencies

### ISSUE THREAD

**Issue by haljarrett** [aws/aws-cdk#27205]
### Describe the bug

Not 100% sure if this should be filed under "Bug Report" or "Feature Request"

The Alpha packages (e.g. @aws-cdk/aws-synthetics-alpha) are tagged with a prerelease identifier, such as 2.96.2-alpha.0; this constrains dependency range expressions such as `^2.95.0-alpha.0` to exact patch versions, accepting `^2.95.0-alpha.1` but not `^2.96.2-alpha.0`

This makes it harder to use packages which take peer dependencies on these packages without forcing resolutions.

To give a more concrete example, [cdk-monitoring-constructs](https://github.com/cdklabs/cdk-monitoring-constructs) takes a peer dependency on `aws-cdk-lib@^2.65.0` and `@aws-cdk/aws-synthetics-alpha@^2.65.0-alpha.0`. This allows a project with a dependency on `cdk-monitoring-constructs` to accept `aws-cdk-lib@2.96.0`, but not `@aws-cdk-aws-synthetics-alpha@2.96.0`

### Expected Behavior

I would expect that the alpha modules would be tagged with the same release identifiers as the rest of the given CDK release, which would allow more graceful version resolution.

### Current Behavior

NPM Semantic Versioning requires that version ranges with pre-release identifiers can only span a given patch version, so satisfying a peer dependency on an older version of an alpha package requires that exact older version, not the version shipped with the current CDK release.

### Reproduction Steps

```
{
  "name": "cdk-dependency-issue",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@aws-cdk/aws-synthetics-alpha": "^2.96.2-alpha.0",
    "aws-cdk-lib": "^2.96.2",
    "cdk-monitoring-constructs": "5.10.3"
  }
}
```

Producing output:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: cdk-dependency-issue@1.0.0
npm ERR! Found: @aws-cdk/aws-synthetics-alpha@2.96.2-alpha.0
npm ERR! node_modules/@aws-cdk/aws-synthetics-alpha
npm ERR!   @aws-cdk/aws-synthetics-alpha@"^2.96.2-alpha.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @aws-cdk/aws-synthetics-alpha@"^2.65.0-alpha.0" from cdk-monitoring-constructs@5.10.3
npm ERR! node_modules/cdk-monitoring-constructs
npm ERR!   cdk-monitoring-constructs@"5.10.3" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /Users/haljar/.npm/_logs/2023-09-19T20_00_35_622Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /Users/haljar/.npm/_logs/2023-09-19T20_00_35_622Z-debug-0.log
```

### Possible Solution

Remove the prerelease tags on the alpha packages, given they are already designated as alpha in the package name

### CDK CLI Version

2.96.2 (build 3edd240)

### Node.js Version

v18.16.0

### OS

MacOS

### Language

Typescript

**Comment by indrora** [comment]
This is an edge case in SemVer that we've decided to solve like this such that we don't ship breaking changes to customers that aren't ready for them.

If you need to ship this to customers, vendor/bundle it independently.

**Comment by haljarrett** [comment]
Fair enough, thanks Morgan - for my usecase accepting older versions of the alpha packages w/r/t to the core cdk version is probably fine. Given that the `cdk-monitoring-constructs@^5.10.3` version range could eventually lead to picking up newer versions, probably best that I don't pin them at all and let the peer dependency pick the version.
