### ISSUE TITLE
custom-resources: provider-framework ignores Status response from user lambdas

### ISSUE THREAD

**Issue by ckenna** [aws/aws-cdk#27208]
### Describe the bug

There is (IMO) a bug in the custom resource provider framework CDK code [here](https://github.com/aws/aws-cdk/blob/af998c8581d2600fa4aa8d5fc5137da84d0f3418/packages/aws-cdk-lib/custom-resources/lib/provider-framework/runtime/framework.ts#L37-L43).

This custom resource provider function calls my user defined Lambda and gets a result back. My user Lambda can fail, and when it does it returns a JSON object that contains `{ "Status": "FAILED" }` (this is even in the object on line 37). But, then this CDK provider framework code ignore this status on line 43 and sends `SUCCESS` back which does not fail the deployment. The same happens on line 86, too, but that's not my codepath.

### Expected Behavior

I expect the status to be equal to the one in my Lambda response, which may be 'FAILED'. This should fail the deployment.

### Current Behavior

The response is hard coded as 'SUCCESS' and the deployment will always succeed. 

### Reproduction Steps

Create a Lambda that always replies with the `{ "Status": "FAILED" }` and use it in a custom resource like this, then deploy the stack. It will succeed.

```
        this.provider = new Provider(this, `MyProvider`, {
            onEventHandler: this.myLambda,
            logRetention: RetentionDays.ONE_YEAR,
        });
        this.customResource = new CustomResource(this, `MyCustomResource`, {
            serviceToken: this.provider.serviceToken,
            properties: {
                // This executes the lambda every deployment
                deployDate: new Date().toISOString(),
            },
        });

```

### Possible Solution

Honor the response from the Lambda.

### CDK CLI Version

2.95.1 (build ae455d8)

### Node.js Version

18.16.0

### OS

Linux

### Language

Typescript

**Comment by pahud** [comment]
>Specifically, to report success or failure, have your Lambda Function exit in the right way: return data for success, or throw an exception for failure. Do not post the success or failure of your custom resource to an HTTPS URL as the CloudFormation documentation tells you to do.
https://github.com/aws/aws-cdk/tree/main/packages/aws-cdk-lib/custom-resources#provider-framework

I believe you will need to throw an error in your lambda function based on the description in the doc.

**Comment by ckenna** [comment]
Interesting! Thank you I'll do that instead. You can close this bug. I was using an internal library at the company I work at, and I think maybe the library itself is outdated.
