### ISSUE TITLE
aws_cleanrooms: missing construct for CfnAnalysisTemplate

### ISSUE THREAD

**Issue by rmalecky** [aws/aws-cdk#27207]
### Describe the bug

On [2023-08-31](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html) AWS Clean Rooms added a resource,  [AnalysisTemplate](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cleanrooms-analysistemplate.html) but there isn't a corresponding L1 construct.  Is there an expected release cadence?

### Expected Behavior

I would expect an L1 construct to be available within 20 days of release.

### Current Behavior

No L1 construct for aws_cleanrooms.CfnAnalysisTemplate

### Reproduction Steps

na

### CDK CLI Version

2.96.2

### Node.js Version

na

### OS

na

### Language

Typescript

**Comment by peterwoodworth** [comment]
We recently made changes to our L1 generation and data source, I'm not certain on the details and will need to check. Thanks for the report

**Comment by peterwoodworth** [comment]
This is present in the spec in the latest version of `@aws-cdk/aws-service-spec`, which will be included in the next CDK release.
