### ISSUE TITLE
aws-ec2: flow logs for TransitGateway & TransitGatewayAttachment

### ISSUE THREAD

**Issue by juweeks** [aws/aws-cdk#27222]
### Describe the feature

TransitGateway and TransitGatewayAttachment resource types are missing from FlowLogResourceType

### Use Case

add flow logs to Transit Gateway resources

### Proposed Solution

for FlowLogResourceType, add `from_transit_gateway_id` and `from_transit_gateway_attachement_id` methods

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.91

### Environment details (OS name and version, etc.)

mac ventura 13.5.2

**Comment by khushail** [comment]
Hi @juweeks , thanks for reaching out. Yes, it would be helpful to have these methods in [FlowlogsResourceType](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ec2.FlowLogResourceType.html#resourcetype)

**Comment by dyoshikawa** [comment]
I'll work on it.

**Comment by dyoshikawa** [comment]
I've implemented it. Could you review?
