### ISSUE TITLE
incorrect links to Java docs

### ISSUE THREAD

**Issue by rittneje** [aws/aws-cdk#27228]
### Describe the issue

The main docs are generating incorrect links to the Java docs.

For example, [Bucket](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_s3.Bucket.html) incorrectly links to https://docs.aws.amazon.com/cdk/api/v2/java/index.html?software/amazon/awscdk/services/s3/Bucket.html instead of https://docs.aws.amazon.com/cdk/api/v2/java/software/amazon/awscdk/services/s3/Bucket.html.

This problem is pervasive, so it seems more like some auto-generation problem than a one-off issue.

### Links

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_s3.Bucket.html
https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.Stack.html
https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_dynamodb.Table.html

to name a few

**Comment by peterwoodworth** [comment]
Thanks, can confirm

**Comment by vinayak-kukreja** [comment]
Hey @rittneje , I believe the links are fixed now. Can you please confirm if the issue still persists for you?

**Comment by rittneje** [comment]
Yep, seems to be fixed.
