### ISSUE TITLE
aws-s3/notifications-resource: Scope down S3 bucket notifications lambda permission to only buckets it interacts with

### ISSUE THREAD

**Issue by alFReD-NSH** [aws/aws-cdk#27234]
### Describe the feature

This lambda function([permission defined here](https://github.com/aws/aws-cdk/blob/7d02e5ef89ed4952bce754dda9d69e8eeb1f53a2/packages/aws-cdk-lib/aws-s3/lib/notifications-resource/notifications-resource-handler.ts#L71)) allows s3:PutBucketNotification with any bucket and we would need it to be only the buckets it actually sets the notification up with.

### Use Case

Following security best practices of scoping down permissions.

### Proposed Solution

I'm thinking we can move out the s3:PutBucketNotification permission definition from the notifications-resource-handler and move it to where we try [to create it given a bucket](https://github.com/aws/aws-cdk/blob/7d02e5ef89ed4952bce754dda9d69e8eeb1f53a2/packages/aws-cdk-lib/aws-s3/lib/notifications-resource/notifications-resource.ts#L119).

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

v2.96.2

### Environment details (OS name and version, etc.)

any

**Comment by peterwoodworth** [comment]
Will prefer to reopen original thread, thanks for bringing this up
