### ISSUE TITLE
(aws-eks): (on Event Handler uses python3.7)

### ISSUE THREAD

**Issue by lkoniecz** [aws/aws-cdk#27248]
### Describe the bug

awscdkawseksKubectlProviderNestedStackawscdkawseksKubectlProvider stack uses python3.7 as the runtime for lambdas

its getting end of life

### Expected Behavior

bump runtime to 3.9

### Current Behavior

child stack with handler in python 3.7 is created

### Reproduction Steps

create a stack with a resource that requires kubectl handler

### CDK CLI Version

2.96.2 (build 3edd240)

### Node.js Version

1.18

### OS

macos

### Language

Python

### Language Version

Python 3.11.1

### Other information

refers to [26866](https://github.com/aws/aws-cdk/pull/26884)

**Comment by indrora** [comment]
Thank you for the report. Can you confirm this on version 2.97 release?

**Comment by lkoniecz** [comment]
@indrora thanks, runtime got updated to 3.10 in 2.97

closing
