### ISSUE TITLE
aws_route53: HostedZone.fromLookup fails in nested stacks

### ISSUE THREAD

**Issue by bencaldwell** [aws/aws-cdk#27249]
### Describe the bug

I think this one has been raised and fixed a few times before e.g. #4651, #25171  

I have a pipeline stack with stages, pretty similar to what is described in https://docs.aws.amazon.com/cdk/v2/guide/cdk_pipeline.html

This app requires that I lookup some records in an already existing hosted zone. 
I can perform HostedZone.fromLookup in the top level stack. The below works:

```
...
export class MyPipelineStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props: MyPipelineStackProps) {
    super(scope, id, props);

    const zoneStage = HostedZone.fromLookup(this, 'my-zone', { domainName: 'mydomain.com.au' }) as HostedZone;
   
    // create a pipeline that watches the codecommit repo develop branch
    const pipelineDevelop = new CodePipeline(this, 'pipeline-develop', {
      pipelineName: 'my-pipeline-develop',
      synth: new ShellStep('Synth', {
        input: CodePipelineSource.codeCommit(repo, 'develop'),
        commands: ['npm ci', 'npm run build', 'npx cdk synth']
      }),
    });

    pipelineDevelop.addStage(new MyPipelineAppStage(this, "my-stage", {
      env: envStage,
      domainName: 'mydomain.com.au'
    }));

```

However, I have a cross account deploy so I need to change environments to lookup a hosted zone in a prod account. So I moved the HostedZone.fromLookup inside my MyPipelineAppStage class, which is called above as a nested stack in the pipelineDevelop.addStage. The below does __not__ work :

```
export class MyPipelineAppStage extends cdk.Stage {

  lambdaStack: MyLambdaStack;
  zone: HostedZone;

  constructor(scope: Construct, id: string, props: MyPipelineAppStageProps) {
    super(scope, id, props);

    this.zone = HostedZone.fromLookup(this, 'zone', { domainName: props.domainName }) as HostedZone;
    this.lambdaStack= new MyLambdaStack(this, 'blue');

  }

}
```

The error I get is:
 
Error: MyPipelineAppStage at 'my-pipeline/my-stage' should be created in the scope of a Stack, but no Stack found

It appears that calling this from the nested Stage stack is breaking the lookup.

### Expected Behavior

I expected that HostedZone.fromLookup would work in all stacks, top level and nested.

### Current Behavior

HostedZone.fromLookup only works in the top level stack. When I call it in a nested stack, created by pipeline.addStage, it throws an error:

Error: MyPipelineAppStage at 'my-pipeline/my-stage' should be created in the scope of a Stack, but no Stack found

### Reproduction Steps

Snippets included in the main description should be enough. The stack looks like:

app
 - pipeline stack
   - stage stack - where the HostedZone.fromLookup is called

### CDK CLI Version

2.96.2 (build 3edd240)

### Node.js Version

v18.17.1

### OS

WSL... but the error happens in the pipeline in AWS account

### Language

Typescript

### Language Version

5.2.2

**Comment by indrora** [comment]
Hmm... Three times sounds like we need to do a longer investigation into this. Cross-Account stuff is always hard to manage. 

Can you produce a Very Minimal (non)working example?

**Comment by peterwoodworth** [comment]
@indrora the information given is plenty sufficient to reproduce. If you have any specific questions, feel free to ask

**Comment by bencaldwell** [comment]
Agh! My apologies, I've just realised that this problem is user error.
I was creating the hostedZone in a class that extends Stage, which itself only extends Construct, *not* Stack. So the error message was valid.
