### ISSUE TITLE
aws-autoscaling: Schedule.cron fails with "Cannot supply both 'day' and 'weekDay', use at most one"

### ISSUE THREAD

**Issue by lmiguelmh** [aws/aws-cdk#27256]
### Describe the bug

Using the Schedule.cron fails on aws-cdk-lib==2.97.0 at synth time. 

> Cannot supply both 'day' and 'weekDay', use at most one

This is how I was calling it before:

```
autoscaling.Schedule.cron(
      week_day="MON-SUN",
      hour="1",  # 01:00 UTC+0 ~ 20:00 int PET (-05:00)
      minute="0",
  )
```

The problem may be here:

https://github.com/aws/aws-cdk/blob/42494f1c49cae8030921b8f74ce67af7b6c6d0e0/packages/aws-cdk-lib/aws-autoscaling/lib/schedule.ts#L22-L29

### Expected Behavior

This was working before:

```
autoscaling.Schedule.cron(
      week_day="MON-SUN",
      hour="1",  # 01:00 UTC+0 ~ 20:00 int PET (-05:00)
      minute="0",
  )
```

### Current Behavior

Error at synth time:

> RuntimeError: Error: Cannot supply both 'day' and 'weekDay', use at most one

### Reproduction Steps

Install latest `aws-cdk-lib`

### Possible Solution

Workaround:
```
aws-cdk-lib==2.96.0
```

### CDK CLI Version

2.97.0 (build d7cf3be)

### Node.js Version

v20.5.1

### OS

Linux

### Language

Python

### Language Version

Python 3.11.5

**Comment by khushail** [comment]
Hi @lmiguelmh , yes I am able to repro the issue. Looks like there is some default value being [passed into `day`](https://github.com/aws/aws-cdk/blob/ab52bb55aae8cf8510bb6788f3bd88a71b648567/packages/aws-cdk-lib/core/lib/schedule.ts#L70) which is causing this error.

**Comment by blankynap** [comment]
Had this issue today with ASG as well as in ECS scheduled scaling. Jumped back to 2.96.0 where everything worked.
