### ISSUE TITLE
region-info: Fact.regions behavior does not match description.

### ISSUE THREAD

**Issue by chamsco-aws** [aws/aws-cdk#27260]
### Describe the bug

In fact.ts

https://github.com/aws/aws-cdk/blob/ab52bb55aae8cf8510bb6788f3bd88a71b648567/packages/aws-cdk-lib/region-info/lib/fact.ts#L7-L14

the description of `regions` it states it returns any region that has at least one fact registered. This is untrue, it is only listing from the fixed list defined in `AWS_REGIONS` from aws-entities.ts.

Either the description needs to be updated, or the logic needs to pull the list of regions from `this.database` instead of the `AWS_REGIONS` export.

### Expected Behavior

1. Call `Fact.regions` and save the array as `call1`
3. Register a new fact with a region that has yet to be added to the list in `AWS_REGIONS`
4. Call `Fact.regions` as `call2`
5. The `call2` array would include the name of my newly added region and the `call1` array would not.

### Current Behavior

1. Call `Fact.regions` and save the array as `call1`
3. Register a new fact with a region that has yet to be added to the list in `AWS_REGIONS`
4. Call `Fact.regions` as `call2`
5. The `call2` array is identical to the `call1` array.

### Reproduction Steps

```
  it('can find new region in `Fact.region`', () => {
    Fact.register({
      region: 'us-unreleased-1',
      name: FactName.PARTITION,
      value: 'aws',
    });
    expect(Fact.regions.includes('us-unreleased-1')).toBeTruthy();
  })
  ```

### Possible Solution

Switch the code from `Array.from(AWS_REGIONS)` to `Array.from(Object.keys(this.database))` or update the documentation to say it is a fixed list based on `AWS_REGIONS` in aws-entities.ts

### CDK CLI Version

2.95.0 (build cfa7e88)

### Node.js Version

v18.17.1

### OS

OSX 13.5.2 (22G91)

### Language

Typescript

### Language Version

TypeScript (4.3.0)

### Other information

You can reach out to me on the Amazon internal slack as `@chamsco`

**Comment by peterwoodworth** [comment]
Thanks for the report, makes sense!

I'm not personally familiar with why you would want to use this feature (returning regions from `Fact`), so I'm not sure if we should just update the documentation or adjust the functionality to match the documentation. I would think it would make sense to adjust the functionality, but there could be something I'm missing. Either way, it should be simple to address
