### ISSUE TITLE
[aws-cdk-lib/aws-dynamodb]: Synthesized IAM Template

### ISSUE THREAD

**Issue by ShamithaReddy** [aws/aws-cdk#27263]
### Describe the bug

Hi team,

Accoriding to the wiki https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_dynamodb.Table.html 
 the method `table.grantStreamRead(grantee);` Permits an IAM principal all stream data read operations 
**for this table's stream**: DescribeStream, GetRecords, GetShardIterator, ListStreams.

But this method on dynamodb table is allowing ListStreams with "*" and i could see that these changes are made as part of https://github.com/aws/aws-cdk/pull/10631

please look into it as soon as possible
Thankyou.

### Expected Behavior

```
{
              "Action": "dynamodb:ListStreams",
              "Effect": "Allow",
              "Resource": {
                "Fn::Join": [
                  "",
                  [
                    "arn:",
                    {
                      "Ref": "AWS::Partition"
                    },
                    ":dynamodb:eu-west-1:dummyaccNumber:table/SDIFileHeaders/stream/*"
                  ]
                ]
              }
            }
```

### Current Behavior

```
{
  "Action": "dynamodb:ListStreams",
  "Effect": "Allow",
  "Resource":
    "*"
}
```

### Reproduction Steps

```
import * as cdk from 'aws-cdk-lib';
import * as dynamodb from 'aws-cdk-lib/aws-dynamodb';
import * as iam from 'aws-cdk-lib/aws-iam';

export class CdkStreamIssueStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const table = new dynamodb.Table(this, 'MyTable', {
      partitionKey: {
        name: 'id',
        type: dynamodb.AttributeType.STRING,
      },
      stream: dynamodb.StreamViewType.NEW_IMAGE,
    });

    const user = new iam.User(this, 'MyUser');

    table.grantStreamRead(user); // Grant stream read permission to the user
  }
}
```

### Possible Solution

revert https://github.com/aws/aws-cdk/pull/10631

### CDK CLI Version

CDK Version: 2.96.2

### Framework Version

aws-cdk-lib: ^2.14.0

### Node.js Version

NodeJS = 18.x

### OS

Linux

### Language

Typescript

**Comment by peterwoodworth** [comment]
The PR that introduced this states why ListStreams is permitted for `*` , and links to documentation that shows this is required. Additionally, I'm not sure what the problem with this would be or why this is a bug that requires a revert in the first place
