### ISSUE TITLE
(aws-ec2/FlowLog): L2 construct FlowLog can't configure kinesis data firehose as LogDestination

### ISSUE THREAD

**Issue by imaig** [aws/aws-cdk#27275]
### Describe the feature

Currently there are only 2 supported properties for [FlowLogDestination](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ec2.FlowLogDestination.html):
- CloudWatch Logs: toCloudWatchLogs()
- S3: toS3()

However the CloudFormation template and L1 Construct([CfnFlowLog](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ec2.CfnFlowLog.html#logdestination)) allow 1 more option:
- Kinesis Data Firehose

So we'd like to enable to configure Kinesis Data Firehose as LogDestination in L2 construct FlowLog as same as CloudWatch Logs and S3.

### Use Case

Same as CloudFormation

### Proposed Solution

Implement the method `toKinesisDataFirehose()` as same as the CloudWatch Logs and S3 in the [FlowLogDestination class](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ec2.FlowLogDestination.html).

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.97.0

### Environment details (OS name and version, etc.)

macOS 13.6

**Comment by peterwoodworth** [comment]
Thanks for the request, makes sense!

**Comment by ymhiroki** [comment]
I want to implement this feature!

**Comment by msambol** [comment]
@ymhiroki Are you already working on this? If not, I'll take it :)

**Comment by ymhiroki** [comment]
I want to implement this feature! 

> @ymhiroki Are you already working on this? If not, I'll take it :)

I'm sorry for the delay, but I've just started the implementation.
I publish it as soon as possible.
