### ISSUE TITLE
s3: add support for TlsVersion condition key in Bucket

### ISSUE THREAD

**Issue by rittneje** [aws/aws-cdk#27279]
### Describe the feature

Currently the `aws_s3.Bucket` constructor has a flag for `enforce_ssl`. However, this only mandates that TLS is used, not which version of TLS.

Recently, S3 added support for restriction which version of TLS is allowed via the `s3:TlsVersion` condition key. https://repost.aws/knowledge-center/s3-enforce-modern-tls

Please add another constructor parameter `enforce_minimum_tls_version` to specify the minimum version.

Open question: If `enforce_minimum_tls_version` is specified but `enforce_ssl` is not, what happens? I believe it should default to mandating TLS. If you don't want that, you must explicitly pass `enforce_ssl=False`.

### Use Case

We want to follow modern security best practices.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.85.0

### Environment details (OS name and version, etc.)

Alpine 3.18

**Comment by peterwoodworth** [comment]
Thanks for the request 👍🏻
