### ISSUE TITLE
@aws-cdk/aws-scheduler-alpha: typo on ref to module @aws-cdk/aws-scheduler-targets-alpha

### ISSUE THREAD

**Issue by pedropedruzzi** [aws/aws-cdk#27281]
### Describe the issue

The doc of module `@aws-cdk/aws-scheduler-alpha` has a reference to the companion module `@aws-cdk/aws-scheduler-targets-alpha`. However there is a typo (`schedule` instead of `scheduler`).

### Links

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-scheduler-alpha-readme.html

**Comment by peterwoodworth** [comment]
Thanks for catching this and for the PR 🙂
