### ISSUE TITLE
custom resources: Generated step function generates finding due to missing logging

### ISSUE THREAD

**Issue by rv2673** [aws/aws-cdk#27283]
### Describe the bug

When custom resources with provider framework has a completedHandler function it generates a aws step function for polling for completion with a configured interval and total timeout. 

This generated step function however has no logging configuration. Which causes the [StepFunctions.1](https://docs.aws.amazon.com/securityhub/latest/userguide/stepfunctions-controls.html#stepfunctions-1) rule from the [AWS Foundational Security Best Practices (FSBP) standard](https://docs.aws.amazon.com/securityhub/latest/userguide/fsbp-standard.html) set to be triggered. 

This is due to the missing logging configuration. The provider construct however also does not provide any option to configure this logging.

### Expected Behavior

The provider construct adds logging by default following the foundational best practice and/or allows this to be configured.

### Current Behavior

The provider construct does not add logging configuration on step function nor does it allow for it to be configured through construct props. 

### Reproduction Steps

Enable StepFunctions.1 rule.
Create stack with custom resource with both evenHandler and isCompleteHandler to trigger generation of state machine.
Deploy generated template
This template should triggger the rule due to missing logging configuration

### Possible Solution

- Add logging configuration by default (with logRetention from props if provided)
- And/or allow for loggroup (configuration) to be provided to provider construct for use in state machine.

### CDK CLI Version

2.96.0

### Node.js Version

18

### OS

Ubuntu 20.04

### Language

Typescript

**Comment by pahud** [comment]
Yes we should add logging here by default unless disabled.

https://github.com/aws/aws-cdk/blob/1fd22a7498223ae5d2faf1799056e81be4f71f5c/packages/aws-cdk-lib/custom-resources/lib/provider-framework/waiter-state-machine.ts#L80-L83
