### ISSUE TITLE
aws-ecr-assets: Readme points to out of date information

### ISSUE THREAD

**Issue by chamsco-aws** [aws/aws-cdk#27298]
### Describe the issue

This section of the README.md directs customers to use `cdklabs/cdk-ecr-deployment`

https://github.com/aws/aws-cdk/blob/9312c9763813af4ac6d2be96e78f6aeaefeeb32c/packages/aws-cdk-lib/aws-ecr-assets/README.md?plain=1#L147-L180

However in this closed issue [(ecr-deployment): new aws-ecr-deployment module](https://github.com/aws/aws-cdk/issues/12076)

> Check out [cdk-docker-image-deployment](https://github.com/cdklabs/cdk-docker-image-deployment), a new library that gives you control of the tags and organization of your Docker image assets.
>
> Right now, it lives in cdklabs and will be maintained by the cdk team, but depending on its popularity we may add it to the core aws-cdk-lib library as well. We are excited to get your feedback and hear what features you would like to see added!

_Originally posted by @scanlonp in https://github.com/aws/aws-cdk/issues/12597#issuecomment-1243879965_
            

You direct people to use cdklabs/cdk-docker-image-deployment, I think the documentation needs to be updated to the new preferred package.

### Links

https://github.com/aws/aws-cdk/blob/9312c9763813af4ac6d2be96e78f6aeaefeeb32c/packages/aws-cdk-lib/aws-ecr-assets/README.md?plain=1#L147-L180

**Comment by peterwoodworth** [comment]
If it's still true that the new package isn't working on non-ts languages, we may want to address that first before updating the docs here
