### ISSUE TITLE
Support GPU resource requirements in container definition

### ISSUE THREAD

**Issue by SoManyHs** [aws/aws-cdk#2729]
With #2453, we can now specify GPU instances. We still need to be able to specify the GPU resource requirements in a container definition for customers to actually use GPUs.

See: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-gpu.html

**Comment by SoManyHs** [comment]
Pending CFN support

**Comment by mattmcclean** [comment]
Is now supported in CFN so when CDK supports the latest CFN definition (see entry for **13th June 2019** [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html)) it can be implemented
