### ISSUE TITLE
(aws-batch): Implement LogConfigurationProperty  with awslogs per default in EcsJobDefinition

### ISSUE THREAD

**Issue by gmarchand** [aws/aws-cdk#27308]
### Describe the feature

Today every AWS Batch Job Definition created with CDK has no logging configuration.

<img width="3291" alt="image" src="https://github.com/aws/aws-cdk/assets/308444/930e72e7-ba07-4153-8caf-b004529bcedb">

### Use Case

A container of a AWS Batch job failed with this message : 
```
"Reason
CannotStartContainerError: Error response from daemon: failed to create shim task: OCI runtime create failed: unable to retrieve OCI runtime error (open /run/containerd/io.containerd.runtime.v2.task/moby/0534f9b15a9e102dac0012fc03becb4279027afd7f6419df578"
```
I can't debug without the logging configuration enabled. 

FYI : Logging data is displayed in "Job logs" when the job status is RUNNING. So there's no point for this use case

### Proposed Solution

enable per default awslogs`awslogs` as described in this interface aws_cdk.aws_batch.CfnJobDefinition.LogConfigurationProperty
https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_batch.CfnJobDefinition.LogConfigurationProperty.html 

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.96.2

### Environment details (OS name and version, etc.)

All OS

**Comment by peterwoodworth** [comment]
Is the request just to make this the default? You can configure [logging on your containers](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_batch.EcsEc2ContainerDefinition.html#logging) with our L2 constructs.

**Comment by gmarchand** [comment]
Sorry for the confusion, I don't understand something ...
