### ISSUE TITLE
aws-cdk-lib: the package seems no longer lazy-loaded

### ISSUE THREAD

**Issue by tmokmss** [aws/aws-cdk#27307]
### Describe the bug

Hi, I just saw [the release note](https://github.com/aws/aws-cdk/releases/tag/v2.98.0) and tested the time to require aws-cdk-lib module, expecting it's got faster from 2.98.0. However, as far as I tested it actually got slower.

```
2.97.0: 214ms
2.98.0: 1044ms
```

Looking at strace, it seems that the modules in aws-cdk-lib are not lazy-loaded any more in 2.98.0.

### Expected Behavior

I don't know it's expected or not, just creating this issue for visibility.

### Current Behavior

Requiring aws-cdk-lib package takes longer time than previous versions. I think it's still fast enough for running a single cdk app though.

### Reproduction Steps

Install aws-cdk-lib:

```sh
npm init -y
npm i aws-cdk-lib@2.98.0
```

Then run the following code:

```js
// index.js
console.time('require');
require('aws-cdk-lib');
console.timeEnd('require');
```

```sh
node index.js
```

Change package version and rerun:

```sh
npm i aws-cdk-lib@2.97.0
node index.js
```

### CDK CLI Version

2.98.0

### Framework Version

2.98.0

### Node.js Version

v18.13.0

### OS

macOS, AL2023

### Language

Typescript

**Comment by khushail** [comment]
Hi @tmokmss , Thanks for reporting this.
looks like team is working on this issue in the PR -https://github.com/aws/aws-cdk/pull/27314
