### ISSUE TITLE
aws-stepfunctions: JsonPath.format incorrectly escapes newlines

### ISSUE THREAD

**Issue by clareliguori** [aws/aws-cdk#27304]
### Describe the bug

When I call JsonPath.format with a string that contains newlines, the resulting string in the CloudFormation template is escaped too many times and fails to deploy.

The example in the repro steps produces this template snippet.  Note the two extra backslashes for the newline in `States.Format('Hello\\\\n{}'`.
```json
"DefinitionString": "{\"StartAt\":\"MessageState\",\"States\":{\"MessageState\":{\"Type\":\"Pass\",\"Parameters\":{\"message.$\":\"States.Format('Hello\\\\n{}', $.name)\"},\"End\":true}}}",
```

### Expected Behavior

Template can be successfully deployed.

If I manually edit the synthesized template to remove the two extra backslashes for the newline (`States.Format('Hello\\n{}'`), then the template can be successfully deployed and the state machine has the correct newline in its output:
```json
"DefinitionString": "{\"StartAt\":\"MessageState\",\"States\":{\"MessageState\":{\"Type\":\"Pass\",\"Parameters\":{\"message.$\":\"States.Format('Hello\\n{}', $.name)\"},\"End\":true}}}",
```

### Current Behavior

The template fails to deploy with:
```
Resource handler returned message: "Invalid State Machine Definition: 'SCHEMA_VALIDATION_FAILED: The value for the field 'message.$' must be a valid JSONPath or a valid intrinsic
function call at /States/MessageState/Parameters' (Service: AWSStepFunctions; Status Code: 400; Error Code: InvalidDefinition; Request ID: cc2099fa-e693-4e51-ab5e-4672cb9abfb6; P
roxy: null)" (RequestToken: 66bd7a2e-b18c-58a9-fe08-807ee96cc521, HandlerErrorCode: InvalidRequest)
```

### Reproduction Steps

```typescript
    const messageState = new sfn.Pass(this, 'MessageState', {
      parameters: {
        "message": sfn.JsonPath.format('Hello\n{}', sfn.JsonPath.stringAt('$.name')),
      },
    });

    new sfn.StateMachine(this, 'StateMachine', {
      definitionBody: sfn.DefinitionBody.fromChainable(messageState),
    });
```

### Possible Solution

The escaping logic for newlines here for JsonPath.format seems to be right, so I'm wondering if there's another round of escaping that's happening when the template is synthesized:
https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-stepfunctions/lib/private/json-path.ts#L340-L356

### CDK CLI Version

2.98.0

### Framework Version

2.98.0

### Node.js Version

v18.17.1

### OS

Linux

### Language

Typescript

### Language Version

Typescript (5.2.2)

**Comment by clareliguori** [comment]
If I use the return value of JsonPath.format as a stack output, then that string is not incorrectly escaped in the synthesized template:
```typescript
const messageFormat = sfn.JsonPath.format('Hello\n{}', sfn.JsonPath.stringAt('$.name'));
new cdk.CfnOutput(this, 'MessageFormat', {
      value: messageFormat,
    });
```

Result:
```json
  "Outputs": {
    "MessageFormat": {
      "Value": "States.Format('Hello\\n{}', $.name)"
    }
  },
```

So the double-escaping could be happening when the DefinitionString is created in the StateMachine construct

**Comment by clareliguori** [comment]
It looks like this is where the double-escaping could be happening - when toJsonString is called on the state machine graph JSON:
https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-stepfunctions/lib/state-machine.ts#L723

Example of doing toJsonString on my Pass state in a new stack output vs what comes directly out of JsonPath.format:
```typescript
  const messageFormat = sfn.JsonPath.format('Hello\n{}', sfn.JsonPath.stringAt('$.name'));
  const messageState = new sfn.Pass(this, 'MessageState', {
      parameters: {
        "message": messageFormat,
      },
    });

  new cdk.CfnOutput(this, 'MessageFormat', {
      value: messageFormat,
    });

  new cdk.CfnOutput(this, 'MessageStateDef', {
      value: cdk.Stack.of(this).toJsonString(messageState.toStateJson()),
    });
```
Output:
```json
  "Outputs": {
    "MessageFormat": {
      "Value": "States.Format('Hello\\n{}', $.name)"
    },
    "MessageStateDef": {
      "Value": "{\"Type\":\"Pass\",\"Parameters\":{\"message.$\":\"States.Format('Hello\\\\n{}', $.name)\"},\"End\":true}"
    }
  },

```

**Comment by peterwoodworth** [comment]
Thanks for the investigation and PR 🙂 Much appreciated!
