### ISSUE TITLE
aws_lambda_event_sources: Missing support for maxRecordAge=-1 value in  KinesisEventSourceProps

### ISSUE THREAD

**Issue by grollat** [aws/aws-cdk#27321]
### Describe the bug

The service supports -1 as a value but CDK imposes a Duration object which does not support negative value. This can become an issue in case the Kinesis Stream Retention window is set to > 7 days (which is the max allowed for maxRecordAge). when this happens customer may lose records.

### Expected Behavior

the KinesisEventSourceProps should support  a way to set the maxRecordAge value to -1. (Duration(-1)?)

### Current Behavior

Duration(-1) is not allowed and no other way to set this value

![image](https://github.com/aws/aws-cdk/assets/8355505/3daf3387-f871-4d66-af98-c90f7a352d9a)

### Reproduction Steps

self explanatory

### Possible Solution

allow Duration.seconds(-1)  as a way to pass through the value? 

### CDK CLI Version

latest

### Node.js Version

all

### OS

all

### Language

Typescript

### Language Version

all

**Comment by peterwoodworth** [comment]
Thanks for reporting, we may want to allow an override on Duration to allow this to work.

For now, you can work around this by overriding the template with [escape hatches](https://docs.aws.amazon.com/cdk/v2/guide/cfn_layer.html)

**Comment by roger-zhangg** [comment]
Just FYI for who doesn't know, The default value for `maxRecordAge` is -1, [document](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-eventsourcemapping.html#cfn-lambda-eventsourcemapping-maximumrecordageinseconds). So if you don't set this value at all, it will be automatically set to -1 in lambda.

E.g.:
const eventSource = new KinesisEventSource(stream, {
      startingPosition: lambda.StartingPosition.TRIM_HORIZON,
      tumblingWindow: cdk.Duration.seconds(60),
});



![Image](https://github.com/aws/aws-cdk/assets/9064139/c2607f12-f9f1-4440-9057-5622c756dd16)

**Comment by roger-zhangg** [comment]
Thanks for the suggestion, I'll take a look at how retention period might affect the maxRecordAge.

**Comment by DanyloGitylo** [comment]
@roger-zhangg @TheRealAmazonKendra @peterwoodworth 

If I leave `maxRecordAge` unset, the default value is 86400, which is 1 day, regardless of the stream retention period (we have both 7 days and 14 days set for different environments).

What results in record age set to -1 is an explicit set to `undefined` in CDK, e.g. `maxRecordAge: undefined`. Then, `MaximumRecordAgeInSeconds` property gets removed from CloudFormation template, which ultimately results in desired behavior.

cdk version 2.200.1
