### ISSUE TITLE
CfnInsightRule: Name restrictions are not documented 

### ISSUE THREAD

**Issue by madsid** [aws/aws-cdk#27327]
### Describe the issue

Rule name has a restriction `INVALID_RULE_NAME: RuleName “<Redacted>” does not match the pattern: [A-Za-z0-9][A-Za-z0-9\-\_\.]{0,126}[A-Za-z0-9] (Service: AmazonCloudWatch; Status Code: 400; Error Code: InvalidParameterValue`. This should have been documented in the CfnInsightRuleProps  props type or description 

### Links

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_cloudwatch.CfnInsightRule.html
https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_cloudwatch.CfnInsightRuleProps.html

**Comment by khushail** [comment]
Hi @madsid , thanks for reporting [this](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/ContributorInsights-CreateRule.html).

`For Rule name, enter a name. Valid characters are A-Z, a-z, 0-9, (hyphen), (underscore), and (period).`

**Comment by peterwoodworth** [comment]
Our docs are sourced from CloudFormation, who likely source from the service. The best way to create tickets to improve that documentation is to use the feedback buttons at the bottom of docs pages

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudwatch-insightrule.html
https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_PutInsightRule.html
