### ISSUE TITLE
aws-ec2: PublicSubnet does not create route table with internet gateway

### ISSUE THREAD

**Issue by priggad** [aws/aws-cdk#27333]
### Describe the bug

I'm trying to create a public subnet in an existing vpc. My understanding is that, unlike a private subnet, a public subnet should be created with a route table that has a route to an internet gateway but the internet gateway route does not get created.

### Expected Behavior

Expecting a subnet to be created with a routing table with a route to an internet gateway. 

### Current Behavior

A subnet is created but it does not have a route to an internet gateway

### Reproduction Steps

    const vpc = ec2.Vpc.fromLookup(this, 'ExistingVPC', {
      vpcId: 'idnumber'
    })
    
    const testSubnet = new ec2.PublicSubnet(this, "TestSubnet", {
      vpcId: vpc.vpcId,
      availabilityZone: 'eu-west-2b',
      cidrBlock: '172.31.0.0/20',
      mapPublicIpOnLaunch: true,
    })

### CDK CLI Version

2.96.2

### Node.js Version

18.17.1

### OS

Fedora 38

### Language

Typescript

**Comment by khushail** [comment]
Hi @priggad , thanks for reaching out. I tried with existing VPC and added another subnet with the code.Subnets can currently only be created in the following availability zones: us-east-1a, us-east-1b, us-east-1c, us-east-1d, us-east-1e, us-east-1f. This is the code I ran -

```
    const vpc = ec2.Vpc
      .fromLookup(this, 'VPC', {
        vpcId:"vpc-01fffa360388518a5"
      });

      const testSubnet = new ec2.PublicSubnet(this, 'testSubnet', {
        vpcId: vpc.vpcId,
        availabilityZone: 'us-east-1b',
        cidrBlock: '10.0.0.0/24',
        mapPublicIpOnLaunch: true,     
        });
```

However, It succeeded with creating the local table for the newly created subnet but the route table to internet gateway was missing.

<img width="1296" alt="Screenshot 2023-09-29 at 4 59 10 PM" src="https://github.com/aws/aws-cdk/assets/117320115/3252d37e-5aca-4586-b6ff-b1462592bef3">

Marking the issue as P2.

**Comment by kevinhdz97** [comment]
Hello, I am seeing the same issue with the below code:

```
const vpc = new ec2.Vpc(this, 'MyVPC', {
            availabilityZones: [AvailabilityZone.US_EAST_1A, AvailabilityZone.US_EAST_1B],
            enableDnsHostnames: false,
            enableDnsSupport: false,
            ipAddresses: ec2.IpAddresses.cidr('10.0.0.0/16'),
            subnetConfiguration: [
                {
                    cidrMask: 20,
                    name: 'VPCPrivate',
                    subnetType: ec2.SubnetType.PRIVATE_ISOLATED
                }
            ],
            vpcName: 'MyVPC'
        });

        // Creates a public subnet additional to the private ones
        const publicSubnet = new ec2.PublicSubnet(this, "PublicSubnet", {
            vpcId: vpc.vpcId,
            availabilityZone: AvailabilityZone.US_EAST_1C,
            cidrBlock: '10.0.32.0/20'
        });
```

**Comment by khushail** [comment]
Hi @priggad ,Apologies for the oversight earlier, I went through issue reproduction again and In CDK Code, while creating PublicSubnet,  a method `addNatgateway()`, you can explicitly call this method to add Gateway to the subnet 

https://github.com/aws/aws-cdk/blob/7a8ae02dbc1d55885cdafead26fd1f780c522e8c/packages/aws-cdk-lib/aws-ec2/lib/vpc.ts#L2383

CDK Doc mentioning the same - https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ec2.PublicSubnet.html#addwbrnatwbrgatewayeipallocationid

Let me know if this is helpful!

**Comment by priggad-uob** [comment]
Hi @khushail, adding a nat gateway to the subnet does not make it public, for a subnet to be public it needs a route table with a route to an internet gateway. I've been able to do this with `subnet.addRoute()` but of course it doesn't make much sense instantiating a class named "PublicSubnet" when in fact it isn't public by default?
