### ISSUE TITLE
(cdk code pipeline): limit 10 assets concurrency 

### ISSUE THREAD

**Issue by alinasir85** [aws/aws-cdk#27335]
Receiving following error on Assets stage of cdk code pipeline

**Error calling startBuild: Cannot have more than 10 builds in queue for the account (Service: AWSCodeBuild; Status Code: 400; Error Code: AccountLimitExceededException; Proxy: null)**

There should be an automated retry feature implemented after the initial 10 builds. Currently, the process fails at this point, necessitating manual intervention to hit the retry button, thereby negating the advantages of an automated pipeline.

![image](https://github.com/aws/aws-cdk/assets/47711616/c56ae3e1-069a-4814-8013-3d4b337bc399)

_Originally posted by @alinasir85 in https://github.com/aws/aws-cdk/discussions/27334_

**Comment by s-maheshbabu** [comment]
Any updates here? If concurrency is the issue, I would expect the pipeline to execute the failed actions once the capacity is freed up. Or at least have a way to configure that behavior.

**Comment by tim-finnigan** [comment]
It looks like this issue is is already being tracked here: https://github.com/aws/aws-cdk/issues/17744

I'll close this as a duplicate but share the workaround mentioned in [this comment](https://github.com/aws/aws-cdk/issues/17744#issuecomment-1783881410):

> The `CodePipeline` construct has a property ([`publishAssetsInParallel`](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.pipelines.CodePipeline.html#publishassetsinparallel)) that should help avoiding this problem.
> 
> Setting it to `false` should result in a single CodeBuild project for publishing all assets. This avoids the concurrency problem if the speed of publishing assets is not a concern.
