### ISSUE TITLE
events_targets: AttributeError: module 'aws_cdk.aws_events_targets' has no attribute 'Tag'

### ISSUE THREAD

**Issue by pascalgulikers** [aws/aws-cdk#27338]
### Describe the bug

When trying to use Tag (https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_events_targets/Tag.html#aws_cdk.aws_events_targets.Tag), it is not recognized and an error is thrown: AttributeError: module 'aws_cdk.aws_events_targets' has no attribute 'Tag'

### Expected Behavior

No error, but the processing of tags

### Current Behavior

Exception with error

### Reproduction Steps

```
from aws_cdk import (
    aws_events as events,
    aws_events_targets as events_targets
)

rule = events.Rule(self, "Rule",
    schedule=events.Schedule.expression(job_schedule)
)

rule.add_target(events_targets.EcsTask(
    cluster=cluster,
    enable_execute_command=True,
    task_definition=task_definition,
    task_count=1,
    container_overrides=[events_targets.ContainerOverride(
        container_name="appContainer",
        command=command
    )],
    tags=events_targets.Tag(
        key="type",
        value="job"
    )
))
```

Result:
```
tags=events_targets.Tag(
         ^^^^^^^^^^^^^^^^^^
AttributeError: module 'aws_cdk.aws_events_targets' has no attribute 'Tag'
```

### CDK CLI Version

2.99.0

### Node.js Version

18

### OS

Ubuntu Linux

### Language

Python

### Language Version

3.11.5

**Comment by khushail** [comment]
@pascalgulikers , could you try adding tags like this instead of the above mentioned -

```
        tags = [event_targets.Tag(
            key="my-tag",
            value="my-tag-value"
        )]
```

**Comment by peterwoodworth** [comment]
@pascalgulikers you'll need to supply it as an array like described above, but that's not what would result in the error you've seen. It seems to me like your packages might not be installed correctly on the version you described, try making sure your installed packages are up to date and the property should exist, it works for me on recent versions, including the latest
