### ISSUE TITLE
(aws-synthetics-alpha): Node 16 End Of Life 

### ISSUE THREAD

**Issue by Abdu03** [aws/aws-cdk#27337]
### Describe the feature

Opeing new issue (duplicate of previously [closed issue](https://github.com/aws/aws-cdk/issues/27028)) now that `syn-nodejs-puppeteer-6.0` has been released.

Node 16 is [EOL](https://nodejs.org/en/blog/announcements/nodejs16-eol). Cloudwatch Synthetics should be able to utilise the next supported runtime (node 18), ideally before the EOL.

### Use Case

Cloudwatch Synthetic Lambda's should have the ability to use the Node 18 runtime... so that AWS clients can keep up to date with the later NodeJS software releases and stay on a supported version.

### Proposed Solution

Create a new SYNTHETICS_NODEJS runtime running on the newly configured syn-nodejs-puppeteer v6.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.83.0

### Environment details (OS name and version, etc.)

n/a

**Comment by khushail** [comment]
Thanks @Abdu03 for keeping a track and submitting the PR.

**Comment by Abdu03** [comment]
> Thanks @Abdu03 for keeping a track and submitting the PR.

No problem 😄  the build is failing on the PR (not entirely sure why tbh), and the linter is asking for integration tests.

it is nearing EOD where i am so i am probably going to leave it for today and have another look tomorrow (unless someone else figures out whats wrong before me 👀 )
