### ISSUE TITLE
SSMParameterProvider returns default value

### ISSUE THREAD

**Issue by ScOut3R** [aws/aws-cdk#2734]
**Describe the bug**
cdk.SSMParameterProvider returns default value although the parameter exists.

According to CloudTrail the API request succeeded but I am still getting the default value in return.

The Parameter is a String.

**To Reproduce**
```typescript
const vpcId: string = new SSMParameterProvider(this, {
      parameterName: `${props.env}/terraform/outputs/vpc/id`
    }).parameterValue();
```

**Expected behavior**
I expect the content of the parameter to be returned.

**Version:**
- OS: Linux
 - Programming Language: Typescript 3.4.5
 - CDK Version: 0.33.0

**Comment by rix0rrr** [comment]
Are you running your application through `cdk synth` and `cdk deploy`?

Are you aware that usin `SSMParameterProvider` will cache the value and never update it? If you want to re-evaluate on every deployment, you might want to use [ParameterStoreString](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ssm.ParameterStoreString.html)

**Comment by ScOut3R** [comment]
I was actually just running ```cdk diff```. :)

Yes, I am aware of the limitations, though in my case I don't think that ```SSMParameterProvider``` gets to a point to persist the data, because the ```cdk.context.json``` does not include its value.

Also my main concern is that it returns the default value not what is stored the SSM PS key.

As I mentioned in the original post the API call is made to SSM (according to CloudTrail) and it succeeds, but ```cdk``` still returns the default value at runtime, hence the _bug_ label.

**Comment by rix0rrr** [comment]
Can you run again with `cdk -v` and paste the output?
