### ISSUE TITLE
EdgeFunction: Does not respect custom qualifier

### ISSUE THREAD

**Issue by sachitsac** [aws/aws-cdk#27361]
### Describe the bug

I am trying to use the [experimental EdgeFunction](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_cloudfront.experimental.EdgeFunction.html) construct. But it fails due to usage of a custom qualifier. Here's some information:

- I have my application stack that reside in the ap-southeast-2 region
- I have a custom construct that deploys a react website to s3 with cloud front distribution in front of it
- I have bootstrapped two regions in my aws account: us-east-1 and ap-southeast-2
- Both of the accounts have been bootstrapped with a custom qualifier: xxx-cdk

So in my custom construct ( L3 pattern ) that deploys the react app to S3, i am trying to add an edge function like this:

## Default Synthesiser with qualifier

<img width="643" alt="Screenshot 2023-09-30 at 12 51 09 pm" src="https://github.com/aws/aws-cdk/assets/79681/045bfdcf-4aaa-4eba-93b9-32a6a9ad0520">
 
## Edge auth function

<img width="848" alt="MicrosoftTeams-image (3)" src="https://github.com/aws/aws-cdk/assets/79681/7b74c00e-533d-4279-8c29-2e7e0b158c7e">

## Distribution config

<img width="699" alt="MicrosoftTeams-image (2)" src="https://github.com/aws/aws-cdk/assets/79681/5ab7f1aa-d572-432c-bd14-a6349e10517d">

### Expected Behavior

Upon synthesis, the edge function stack should respect the custom qualifier name provided to the stack. Given that i am initialising the edge function from within my cloudfront stack, ( kinda like nested stack ), i should be able to use to inherit the custom qualifier.

### Current Behavior

Its not respecting the custom qualifier provided upon stack initialisation.

### Reproduction Steps

- Bootstrap cdk in us-east-1 and ap-southeast-2 regions with a custom qualifier 
- Create a Main stack with a custom qualifier
- Use a custom construct to create a S3ToCloudfront pattern 
- Add an edge auth lambda using the EdgeFunction construct.
- Synthesise the stack

There will be an error trying to create the edge lambda function in the us-east-1 as its not using the custom qualifier passed to the parent Main stack.

### Possible Solution

Two things i can think of:

- The EdgeFunction either needs to respect the custom qualifier given its creating a new stack 
- Or The EdgeFunction stack need to be able to take in the custom qualifier as a synthesis property
- Or The EdgeFunction stack needs to take in the instance of synthesiser 

I believe for the sake of simplicity, the first option should be the default as in most circumstances but the third offers most flexibility as we could possibly bootstrap different regions with different qualifiers.
 

### CDK CLI Version

2.95.1

### Framework Version

2.95.1

### Node.js Version

18

### OS

macos 14.0 

### Language

Typescript

### Language Version

5

**Comment by rv2673** [comment]
@sachitsac 
If you want to only customize qualifier, and only use single qualifier per Stage(or App if you don't have stages). 

You could set context variable, @aws-cdk/core:bootstrapQualifier, on Stage/App containing the stack with EdgeLambda or in cdk.json(if it is for entire app). 

Which is where synthesizer looks for value(if not provided), before falling back to default value.

(I am not from cdk team)

**Comment by sachitsac** [comment]
Thanks @rv2673 

I think you are right I'm passing it at the stack level. I'll try passing it at the app level. Might even resolve an issue I was having with the certificate construct where it wasn't respecting permission boundary. 

Thanks

**Comment by sachitsac** [comment]
Closed as this is resolved by @rv2673 comment. No action needed.

**Comment by rv2673** [comment]
@sachitsac I do think your suggestion for lambda stack to inherit the synthesizer from the containing stack still has merit, though maybe less prio. The context setting only works for qualifier customization, not for other customizations for the synthesizer.
