### ISSUE TITLE
dynamodb: TableV2 to support fixed write capacity

### ISSUE THREAD

**Issue by skal111** [aws/aws-cdk#27378]
### Describe the feature

Creating a TableV2 with provisionned billing fails if I specify fixed capacity for WCU.

Error: You cannot configure 'writeCapacity' with FIXED capacity mode

new TableV2(this, `my-table`, {
  billing: Billing.provisioned({
    readCapacity: Capacity.fixed(3),
    writeCapacity: Capacity.fixed(1),
  }),
}

### Use Case

My table's capacity is well known so I don't need the autoscaling.

The thing is it autoscaling capacity creates a lot of cloudwatch alarms which I don't need, as they will never trigger. This produces unwanted additional costs.

### Proposed Solution

Support fixed capacity for WCU.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.99.1

### Environment details (OS name and version, etc.)

Win11

**Comment by khushail** [comment]
Hi @skal111 ,thanks for reaching out. As mentioned [here in the docs](https://github.com/aws/aws-cdk/tree/main/packages/aws-cdk-lib/aws-dynamodb#billing)-

`When using provisioned billing, you must also specify readCapacity and writeCapacity. You can choose to configure readCapacity with fixed capacity or autoscaled capacity, but writeCapacity can only be configured with autoscaled capacity. `

I am marking your request as P2.
