### ISSUE TITLE
aws_cdk.aws_cloudwatch: CfnAlarm drops MetricDataQueryProperty contents if arguments come from a dict

### ISSUE THREAD

**Issue by SC-CTS** [aws/aws-cdk#27372]
### Describe the bug

When instantiatig a CfnAlarm from a Dict as follows:

```python
CfnAlarm(scope=self, id="cfn-alarm", **{
    'alarm_name': 'Descriptive Name', 
    'alarm_description': 'Very descriptive description.', 
    'actions_enabled': True, 
    'ok_actions': ['arn:aws:sns:eu-central-1:666:XXX_CloudWatch_Integration'], 
    'alarm_actions': ['arn:aws:sns:eu-central-1:666:XXX_CloudWatch_Integration'], 
    'insufficient_data_actions': [], 
    'evaluation_periods': 15, 
    'datapoints_to_alarm': 15, 
    'threshold': 1.5, 
    'comparison_operator': 'LessThanThreshold', 
    'treat_missing_data': 'missing', 
    'metrics': [
      {
        'id': 'e1', 
        'label': 'Currently running Alerts', 
        'return_data': True, 
        'expression': 'MAX(METRICS()/3)'
      }, 
      {
        'id': 'm1', 
        'return_data': False, 
        'metric_stat': {
          'metric': {
            'namespace': 'project', 
            'metric_name': 'gauge.project.value', 
            'dimensions': []
          }, 
          'period': 60, 
          'stat': 'Average'
        }
      }
    ]
  })
```

It will fail with the following error from the Stack: `Resource handler returned message: "Period must not be null (Service: CloudWatch, Status Code: 400, Request ID: 123)"`

### Expected Behavior

The Alarm should be created successfully and the stack should not fail.

### Current Behavior

When checking the synth output in `cdk.out` I see the following was generated:

```json
{
  "abcde": {
    "Type": "AWS::CloudWatch::Alarm",
    "Properties": {
      "ActionsEnabled": true,
      "AlarmActions": [
        "arn:aws:sns:eu-central-1:666:XXX_CloudWatch_Integration"
      ],
      "AlarmDescription": "Very descriptive description.",
      "AlarmName": "Descriptive Name",
      "ComparisonOperator": "LessThanThreshold",
      "DatapointsToAlarm": 15,
      "EvaluationPeriods": 15,
      "InsufficientDataActions": [],
      "Metrics": [
        {
          "Expression": "MAX(METRICS()/3)",
          "Id": "e1",
          "Label": "Currently running Alerts"
        },
        {
          "Id": "m1"
        }
      ],
      "OKActions": [
        "arn:aws:sns:eu-central-1:666:XXX_CloudWatch_Integration"
      ],
      "Threshold": 1.5,
      "TreatMissingData": "missing"
    },
    "DependsOn": [
      "qwer",
      "zxc"
    ],
    "Metadata": {
      "aws:cdk:path": "hjk"
    }
  }
}
```

The second object in `abcde.Properties.Metrics` with `"id": "m1"` is missing all properties.

### Reproduction Steps

See provided code.

### Possible Solution

Instantiating the `MetricDataQueryProperty` manually like so:

```python
CfnAlarm(scope=self, id="cfn-alarm", **{
    'alarm_name': 'Descriptive Name', 
    'alarm_description': 'Very descriptive description.', 
    'actions_enabled': True, 
    'ok_actions': ['arn:aws:sns:eu-central-1:666:XXX_CloudWatch_Integration'], 
    'alarm_actions': ['arn:aws:sns:eu-central-1:666:XXX_CloudWatch_Integration'], 
    'insufficient_data_actions': [], 
    'evaluation_periods': 15, 
    'datapoints_to_alarm': 15, 
    'threshold': 1.5, 
    'comparison_operator': 'LessThanThreshold', 
    'treat_missing_data': 'missing', 
    'metrics': [
      CfnAlarm.MetricDataQueryProperty(**{
        'id': 'e1', 
        'label': 'Currently running Alerts', 
        'return_data': True, 
        'expression': 'MAX(METRICS()/3)'
      }), 
      CfnAlarm.MetricDataQueryProperty(**{
        'id': 'm1', 
        'return_data': False, 
        'metric_stat': {
          'metric': {
            'namespace': 'project', 
            'metric_name': 'gauge.project.value', 
            'dimensions': []
          }, 
          'period': 60, 
          'stat': 'Average'
        }
      })
    ]
  })
```

Will generate the expected, correct CF code in `cdk.out`. This is not great because we load the CF from a file and would like to not parse it any further if possible.

### Additional Information/Context

When checking the `CfnAlarmProps` spec: https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_cloudwatch/CfnAlarmProps.html
I would interpret the type for `metrics` (`Union[IResolvable, Sequence[Union[IResolvable, MetricDataQueryProperty, Dict[str, Any]]], None]`) to allow for Dicts. Maybe I just misinterpeted that?

### CDK CLI Version

2.99.1 (build b2a895e)

### Node.js Version

18.16.0

### OS

Ubuntu 20.04.6 LTS (in WSL on Win 11)

### Language

Python

### Language Version

Python 3.11

**Comment by khushail** [comment]
Hi @SC-CTS ,thanks for reaching out.

Going through the available documentation about [Metrics](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_cloudwatch.CfnAlarm.html#metrics), it expects the array objects to be of type `CfnAlarm.MetricDataQueryProperty` as given in [this example.](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_cloudwatch/CfnAlarmProps.html). So when you explicitly added this and corrected the code, it produced the correct CF template.

And you also mentioned about using CF from file, so using [Cloudformation Include module](https://aws.amazon.com/blogs/mt/introducing-aws-cloudformation-modules/) might help solve your usecase. Let me know if it does not help.
