### ISSUE TITLE
s3: bucket.grantRead does not allow s3:HeadObject

### ISSUE THREAD

**Issue by tmokmss** [aws/aws-cdk#27389]
### Describe the bug

Currently `bucket.grantRead` does not allow s3:HeadObject action. Because of this, the code like below does not work if you set the IAM policy by `grantRead` method, which is a surprising behavior.

```py
s3 = boto3.client("s3")
# this operation requires s3:HeadObject permission
s3.download_file(bucket, key, filepath)

# you get the following error:
# [ERROR] ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden
```

### Expected Behavior

`bucket.grantRead` allows s3:HeadObject action.

### Current Behavior

`bucket.grantRead` only allows `s3:GetBucket* , s3:GetObject*, s3:List*` actions.

### Reproduction Steps

```ts
    const bucket = new Bucket(this, 'Bucket', {
    });
    const role = new Role(this, 'Role', {
      assumedBy: new ServicePrincipal('sns.amazonaws.com'),
    });
    bucket.grantRead(role);
    // See the synthesized IAM policy.
```

### CDK CLI Version

2.99.1

### Framework Version

2.99.1

### Node.js Version

v18.13.0

### OS

macOS

### Language

Typescript

**Comment by khushail** [comment]
Hi @tmokmss , thanks for the report on the [permitted actions](https://github.com/aws/aws-cdk/blob/v2.99.1/packages/aws-cdk-lib/aws-s3/lib/perms.ts) for grantRead().

**Comment by davekerber** [comment]
Also verified this is still happening with v2.101.0 of the CDK CLI.

**Comment by andresionek91** [comment]
Your authorization issue was related to something else. `s3:HeadObject` is not a valid action in IAM.
