### ISSUE TITLE
(assertions): misformatted doc string causes generated docs to cut off information

### ISSUE THREAD

**Issue by jishi** [aws/aws-cdk#27392]
### Describe the issue

I was about to file a PR to clarify syntax for the Template.findParameters() call, but when I looked at the source, the documentation for parameters has been correct for 2 years. See this:

https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/assertions/lib/template.ts#L183

However, the latest documentation for this method is missing the `*` info. Isn't the online documentation generated from the comments? Why is the crucial information about this omitted here? 

### Links

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.assertions.Template.html#findwbrparameterslogicalid-props

**Comment by scanlonp** [comment]
I suspect that the docstring below the `@param` tags is messing up the doc generation. Looks like an easy fix, but this problem is somewhat widespread in that file.

**Comment by daschaa** [comment]
@scanlonp Is there a way to generate the docs locally to test it?

**Comment by Exter-dg** [comment]
I would like to work on this. As someone mentioned, is there a way to generate docs locally and test the changes? How are docs generated, I wasn't able to figure that out from the code
