### ISSUE TITLE
[lambda] support for dead letter targets

### ISSUE THREAD

**Issue by Obirah** [aws/aws-cdk#2739]
As it was suggested to my colleague @pierreozoux in https://github.com/awslabs/aws-cdk/issues/660, we are now opening this issue, because we'd love to have support for SNS dead letters in the `Function` L2 construct.

Right now we are successfully working around this, by overriding the property on the internal L1 resource after the L2 resource has been instantiated:

```
protected addSnsDeadLetterConfig(topic: Topic): void {
    this.role.addToPolicy(DbcsLambda.createPolicyStatement(topic.topicArn, 'SNS:Publish'));

    (this.function.node.findChild('Resource') as CfnResource).addPropertyOverride('deadLetterConfig', {
        targetArn: topic.topicArn
    });
}
```

Nonetheless, it would be cool to have to have real support for this on `Function`. From reading all the comments in https://github.com/awslabs/aws-cdk/issues/660, I understand that you are going through some hassle with the dependencies between the Lambda and SNS packages.

Would it maybe be feasible to have a very simple approach for starters so that the `FunctionProps` have a field `deadLetterTargetArn` that is used if the `deadLetterQueueEnabled` flag is false?

This way, the Lambda package does not necessarily need to care about the SNS package in the beginning and later one can develop a similar high-level approach for SNS as it already exists for SQS.

I'd also be totally open to contribute code to this, if we find an approach for this problem.

**Comment by SomayaB** [comment]
Hi @Obirah, thanks for submitting! We will update this issue when there is any progress.

**Comment by MaartenThoelen** [comment]
Hi,

Is there any update on this feature?

Thanks!

**Comment by SomayaB** [comment]
Hi @MaartenThoelen, there is a PR in progress, thanks @nmussy! You can follow the PR process here #4763

**Comment by nija-at** [comment]
@Obirah & other requesters - Lambda now supports [`DestinationConfig`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-eventinvokeconfig-destinationconfig.html#cfn-lambda-eventinvokeconfig-destinationconfig-onfailure). 

Does this satisfy your use case for a dead letter queue? If not, could you detail how you would benefit from the `DeadLetterConfig`?

**Comment by SomayaB** [comment]
Closing this issue since there hasn't been a response in a while. Feel free to reopen.
