### ISSUE TITLE
wafv2.CfnLoggingConfiguration.LoggingFilterProperty  and wafv2.CfnLoggingConfiguration.FilterProperty create CF code with wrong keys

### ISSUE THREAD

**Issue by D592** [aws/aws-cdk#27404]
### Describe the bug

logging_filter=wafv2.CfnLoggingConfiguration.LoggingFilterProperty(
            default_behavior="DROP",
            filters=[wafv2.CfnLoggingConfiguration.FilterProperty(
                behavior="KEEP",
                conditions=[wafv2.CfnLoggingConfiguration.ConditionProperty(
                    action_condition=wafv2.CfnLoggingConfiguration.ActionConditionProperty(action="BLOCK")
                    )],
                requirement="MEETS_ALL"
                )]
            )
creates CF stack with incorrect keys (started with a lowercase letter - should be from capital) 
      LoggingFilter:
        defaultBehavior: DROP
        filters:
          - behavior: KEEP
            conditions:
              - actionCondition:
                  action: BLOCK
            requirement: MEETS_ALL

### Expected Behavior

      LoggingFilter:
        DefaultBehavior: DROP
        Filters:
          - Behavior: KEEP
            Conditions:
              - ActionCondition:
                  Action: BLOCK
            Requirement: MEETS_ALL

### Current Behavior

      LoggingFilter:
        defaultBehavior: DROP
        filters:
          - behavior: KEEP
            conditions:
              - actionCondition:
                  action: BLOCK
            requirement: MEETS_ALL
the keys are incorrect and deploy is broken

### Reproduction Steps

code in the "Describe the bug" section
synth - OK
deploy - error - AWS CF return "wrong Key"

### Possible Solution

update the wafv2.CfnLoggingConfiguration.LoggingFilterProperty  and wafv2.CfnLoggingConfiguration.FilterProperty

### CDK CLI Version

2.99.0

### Node.js Version

18.18.0

### OS

Linux Ubuntu 22.04

### Language

Python

### Language Version

3.10

**Comment by peterwoodworth** [comment]
Hey, thanks for reporting. Please see [this issue](https://github.com/aws/aws-cdk/issues/23709), in short you don't want to use the specific property types where the API is not expecting those types.
