### ISSUE TITLE
aws-lambda-nodejs: NodejsFunction should enable configuring log group

### ISSUE THREAD

**Issue by AlJohri** [aws/aws-cdk#27414]
### Describe the feature

The [NodejsFunction](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda_nodejs.NodejsFunction.html) construct should enable setting the log group similar to how the underlying Lambda construct already does.

### Use Case

We would like to centralize all of our application logs into a single log group.

### Proposed Solution

Add a new `logGroup` property to the constructor props.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.95.0 (build cfa7e88)

### Environment details (OS name and version, etc.)

Amazon Linux 2

**Comment by indrora** [comment]
This feels like a duplicate of #27413 but with a different target. 

I suspect that adding a more generic "It'd be nice to have log groups configurable where they might make one" ticket and binding these to it would be appropriate. I'll bring this up with the Construct Squad.

**Comment by peterwoodworth** [comment]
NodejsFunction extends Function, and includes the same logging related props, so it has all the same functionality. Lambda functions create logs by default on creation, I'm pretty sure we offer the most control you can really have already. Maybe I don't understand the request?

**Comment by AlJohri** [comment]
>Lambda functions create logs by default on creation, I'm pretty sure we offer the most control you can really have already.

Thanks for the prompt response and clarification. I see that indeed even on the `Function` construct, there is no construct property for log group. Coming from the ECS world, I did not realize that you can't change the log group of a lambda.

**Comment by AlJohri** [comment]
Customizing lambda log group is supported now and should get exposed on the Function construct: https://aws.amazon.com/blogs/compute/introducing-advanced-logging-controls-for-aws-lambda-functions/

When that is done, NodeJsFunction construct will also get this property.

**Comment by AlJohri** [comment]
And it’s already done! https://github.com/aws/aws-cdk/pull/28039
