### ISSUE TITLE
(aws-ses): expose scalingMode property on DedicatedIPPool

### ISSUE THREAD

**Issue by tobiasviehweger** [aws/aws-cdk#27418]
### Describe the feature

Currently, you can only create dedicated IP pools with scaling mode "standard" as the scalingMode property from CfnDedicatedIpPool is not exposed in DedicatedIpPool.

### Use Case

I want to create a managed IP pool :)

### Proposed Solution

Expose property "scalingMode" with typed enum.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.99.1

### Environment details (OS name and version, etc.)

Windows 11

**Comment by khushail** [comment]
Thanks @tobiasviehweger for submitting this feature request. Your contributions are welcome.
