### ISSUE TITLE
aws-ec2: Filter subnets by CIDR Range

### ISSUE THREAD

**Issue by AlemanCS** [aws/aws-cdk#27421]
### Describe the feature

I would like the ability to filter a SubnetSelection based on a CIDR range in a VPC. While SubnetFilter does allow to filter by CIDR mask and IP address, a VPC can have multiple CIDR Ranges associated with it and the CIDR masks can be the same while the range can be different.

### Use Case

I would like this feature because some of the VPCs I have worked with have 2 or more CIDR Ranges associated and the current subnet filter options don't really work unless I filter by Id.

Simple Example: 

VPC A can have CIDR ranges: `10.2.0.0/16` and `100.64.0.0/16`

Its subnets can be as follows: 

Subnet A: `10.2.0.0/18`
Subnet B: `10.2.64.0/18`
Subnet C: `100.64.0.0/18`
Subnet D: `100.64.64.0/18`

I want to only use the subnets under the `10.2.0.0/16` CIDR range.

### Proposed Solution

I think the feature would look something like this

```
const subnetsByCidrRanges: SubnetSelection = {
      subnetFilters: [SubnetFilter.byCidrRanges([10.2.0.0/16])]
    }
````

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.93.0

### Environment details (OS name and version, etc.)

Mac OS

**Comment by peterwoodworth** [comment]
Thanks for the request, this makes sense and I can see how it would be useful 🙂 

Be sure to check out our [contributing guide](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md), we will likely rely on contributor support for this feature
