### ISSUE TITLE
apigateway: Deployment of model without any required field fails 

### ISSUE THREAD

**Issue by tmplcl** [aws/aws-cdk#27433]
### Describe the bug

When deploying an API Gateway Model validator without any required fields the deployment fails for this resource.

When I add any field to the required block the deployment works. 

### Expected Behavior

The deployment of the API Gateway Model succeeds.

### Current Behavior

The deployment of the API Gateway Model fails and throws the following error.

```
Resource handler returned message: "Invalid model specified: Validation Result: warnings : [], errors : [Invalid modelschema specified] (Service: ApiGateway, Status Code: 400, Request ID: (RequestToken: , HandlerErrorCode: InvalidRequest)
```

### Reproduction Steps

Deploy API Gateway Model:

```typescript
new apigateway.Model(this, 'model-validator', {
      restApi: this.apigateway,
      contentType: 'application/json',
      description: 'desc'
      modelName: 'model',
      schema: {
        type: JsonSchemaType.OBJECT,
        required: [],
        properties: {
          description: { type: apigateway.JsonSchemaType.STRING }
        }
    }
}
```

### CDK CLI Version

2.99.1

### Node.js Version

v18.17.1

### OS

Mac OS

### Language

Typescript

**Comment by peterwoodworth** [comment]
I don't understand the bug report - If you need to fill in this property for your model, then supply it. 

Do you think this shouldn't be throwing an error? Do you think `required` should be required?
