### ISSUE TITLE
(aws-scheduler-targets-alpha): Add CodeBuildStartBuild Target

### ISSUE THREAD

**Issue by filletofish** [aws/aws-cdk#27448]
### Describe the feature

Work to support L2 constructs for AWS Scheduler is in progress (https://github.com/aws/aws-cdk/issues/23394). See the approved [RFC](https://github.com/aws/aws-cdk-rfcs/pull/486/files). RFC planned to add 12 templates targets, but only Lambda Invoke is currently implemented (https://github.com/aws/aws-cdk/pull/26575). 

This issue tracks implementation of  `CodeBuildStartBuild` target to start an AWS CodeBuild build. 

### Use Case

Customers would like to use templated target `CodeBuildStartBuild` to be able to start AWS CodeBuild build on schedule. L2 target construct  should grant required permissions to the `scheduler` to start the CodeBuild.  

### Proposed Solution

The proposed solution needs to be adopted to the recent examples of `LambdaInvoke` (https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/aws-scheduler-targets-alpha/lib/lambda-invoke.ts). 

Solution should also include unit and integration tests. 

```ts
export class CodeBuildStartBuild extends ScheduleTargetBase implements IScheduleTarget {
    constructor(
      private readonly project: codebuild.IProject,
      private readonly props: ScheduleTargetBaseProps,
    ) {
      super(props, project.projectArn)
    }

    protected addTargetActionToRole(schedule: ISchedule, role: IRole): void {
      // TODO: Check if target and schedule are in the same account and region
      // TODO: Check if target and role are in the same account

     // TODO: Check if L2 grant methods can be used
      role.addToPrincipalPolicy(new iam.PolicyStatement({
        actions: ['codebuild:StartBuild'],
        resources: [this.project.projectArn],
      }));
    }
  }
```

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.99.1

### Environment details (OS name and version, etc.)

MacOs

**Comment by pahud** [comment]
Thank you for all those feature requests and PRs!
