### ISSUE TITLE
(aws-scheduler-targets-alpha): Add InspectorStartAssessmentRun Target

### ISSUE THREAD

**Issue by filletofish** [aws/aws-cdk#27453]
### Describe the feature

Work to support L2 constructs for AWS Scheduler is in progress (https://github.com/aws/aws-cdk/issues/23394). See the approved [RFC](https://github.com/aws/aws-cdk-rfcs/pull/486/files). RFC planned to add 12 templates targets, but only Lambda Invoke is currently implemented (https://github.com/aws/aws-cdk/pull/26575). 

This issue tracks implementation of  `InspectorStartAssessmentRun` target to start an AWS Inspector assessment run.

### Use Case

Customers would like to use templated target `InspectorStartAssessmentRun` to be able to start a record to an AWS Inspector assessment run on schedule. L2 target construct should grant required permissions to the `AWS Scheduler` to start an AWS Inspector Assessment run.

### Proposed Solution

The proposed solution needs to be adopted to the recent examples of `LambdaInvoke` (https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/aws-scheduler-targets-alpha/lib/lambda-invoke.ts). 

Solution should also include unit and integration tests. 

```ts
  export class InspectorStartAssessmentRun extends ScheduleTargetBase implements IScheduleTarget {
    constructor(
      private readonly target: inspector.CfnAssessmentTarget,
      private readonly props: ScheduleTargetBaseProps,
    ) {
      super(props, target.attrArn);
    }

    protected addTargetActionToRole(schedule: ISchedule, role: IRole): void {
     // TODO: Check if target and schedule are in the same account and region
     // TODO: Check if target and role are in the same account

     // TODO: Check if L2 grant methods can be used
      role.addToPrincipalPolicy(new iam.PolicyStatement({
        actions: ['inpsector:StartAssessmentRun'],
        resources: ["*"],
      }));      
    }
  }
```

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.99.1

### Environment details (OS name and version, etc.)

MacOS

**Comment by pahud** [comment]
Thank you for all those feature requests and PRs!
