### ISSUE TITLE
(aws-scheduler-targets-alpha): Add EventBridgePutEvents Target

### ISSUE THREAD

**Issue by filletofish** [aws/aws-cdk#27454]
### Describe the feature

Work to support L2 constructs for AWS Scheduler is in progress (https://github.com/aws/aws-cdk/issues/23394). See the approved [RFC](https://github.com/aws/aws-cdk-rfcs/pull/486/files). RFC planned to add 12 templates targets, but only Lambda Invoke is currently implemented (https://github.com/aws/aws-cdk/pull/26575). 

This issue tracks implementation of  `EventBridgePutEvents` target to put an event to AWS Event Bridge Event Bus.

### Use Case

Customers would like to use templated target `EventBridgePutEvents` to be able to put events to Event Bus on schedule. L2 target construct should grant required permissions to the `AWS Scheduler` to put events to a Event Bus.

### Proposed Solution

The proposed solution needs to be adopted to the recent examples of `LambdaInvoke` (https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/aws-scheduler-targets-alpha/lib/lambda-invoke.ts). 

Solution should also include unit and integration tests. 

Class `EventBridgePutEvents ` should: 
1. Grant Scheduler Execution Role permissions to Put Events via `addTargetActionToRole`
2. Override `bindBaseTargetConfig` to return `eventBridgeParameters`  as part of `ScheduleTargetConfig`.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.99.1

### Environment details (OS name and version, etc.)

MacOS

**Comment by pahud** [comment]
Thank you for all those feature requests and PRs!

**Comment by WtfJoke** [comment]
Is it fine for you if I pick that?

**Comment by WtfJoke** [comment]
I hope you dont mind, that I've opened #27629. I couldnt resist 🙈 
Would appreciate feedback once you have time :)

**Comment by filletofish** [comment]
@WtfJoke of course. Thank you!

Please, I will make it clear that people should feel free to pick up the issues and create pull requests! 

I will try to review the PR soon

**Comment by WtfJoke** [comment]
> @WtfJoke of course. Thank you!
> 
> Please, I will make it clear that people should feel free to pick up the issues and create pull requests! 
> 
> I will try to review the PR soon

Awesome, thank you
