### ISSUE TITLE
@aws-cdk/aws-synthetics-alpha: version 2.100.0-alpha.0 does not contain SYNTHETICS_NODEJS_PUPPETEER_6_0

### ISSUE THREAD

**Issue by drrobharper** [aws/aws-cdk#27465]
### Describe the bug

The [release notes](https://github.com/aws/aws-cdk/releases) say that version `2.100.0-alpha.0` of `@aws-cdk/aws-synthetics-alpha` should contain "Synthetics NodeJS Puppeteer 6.0 Runtime with NodeJS 18"

This does not seem to be the case, however.

### Expected Behavior

`npm i @aws-cdk/aws-synthetics-alpha@2.100.0-alpha.0`

```
import { Runtime } from '@aws-cdk/aws-synthetics-alpha';
const synthetics6 = Runtime.SYNTHETICS_NODEJS_PUPPETEER_6_0
```

### Current Behavior

`SYNTHETICS_NODEJS_PUPPETEER_6_0` is not available on `Runtime`

### Reproduction Steps

`npm i @aws-cdk/aws-synthetics-alpha@2.100.0-alpha.0`

```
import { Runtime } from '@aws-cdk/aws-synthetics-alpha';
const synthetics6 = Runtime.SYNTHETICS_NODEJS_PUPPETEER_6_0
```

### CDK CLI Version

2.100.0 (build e1b5c77)

### Node.js Version

18

### OS

macOS

### Language

TypeScript

**Comment by JohnNewman1** [comment]
+1

**Comment by kaizencc** [comment]
Hi! Synthetics was stabilized. That means that all new additions to the synthetics module lives in `aws-cdk-lib/aws-synthetics`. The migration path should be exceedingly simple to get to the stable module, the most you would have to do is update a few deprecated properties.

The alpha version exists so as not to break existing users, but it will receive no new updates. Let me know (in a new issue) if there are problems with the new stable module!
