### ISSUE TITLE
(aws-elasticloadbalancingv2): AlbTarget does not accept an instance of IApplicationLoadBalancer

### ISSUE THREAD

**Issue by shadab16** [aws/aws-cdk#27466]
### Describe the bug

`AlbTarget` does not accept an instance of `IApplicationLoadBalancer`. This prevents it from being used alongside `ApplicationLoadBalancer.fromLookup` and `ApplicationLoadBalancer.fromApplicationLoadBalancerAttributes` because of their return type.

Workaround is to use `AlbArnTarget` directly.

### Expected Behavior

No compilation error.

### Current Behavior

Compilation error
`error TS2345: Argument of type 'IApplicationLoadBalancer' is not assignable to parameter of type 'ApplicationLoadBalancer'.`

### Reproduction Steps

```typescript
import * as elbv2 from 'aws-cdk-lib/aws-elasticloadbalancingv2';
import { AlbTarget } from 'aws-cdk-lib/aws-elasticloadbalancingv2-targets';

const testingAlb = elbv2.ApplicationLoadBalancer.fromLookup(this, 'TestingAlb', {
  loadBalancerTags: { Products: '...' }
});

const albTarget = new AlbTarget(testingAlb, 80);
                                ~~~~~~~~~~
```

### Possible Solution

Constructor for `AlbTarget` can be changed to accept interface `IApplicationLoadBalancer`. The implementation only references `loadBalancerArn` from the given object, which is available in the interface too.

### CDK CLI Version

2.100.0 (build e1b5c77)

### Node.js Version

v18.18.0

### OS

Windows 10 22H2, WSL (5.15.90.1-microsoft-standard-WSL2)

### Language

TypeScript

### Language Version

5.2.2

**Comment by peterwoodworth** [comment]
Thanks for reporting this issue, this makes sense
