### ISSUE TITLE
Enable Cluster "Default" Name Space To Either Create or Use Existing Namespace

### ISSUE THREAD

**Issue by canada4663** [aws/aws-cdk#2747]
the Referenced line/function only allows adding a default namespace that doesn't currently exist.  If it does exist, the stack creation fails - even when updating existing stack.

https://github.com/awslabs/aws-cdk/blob/0e101d534ec2b39abcf19f93fde1e67d651e4089/packages/%40aws-cdk/aws-ecs/lib/cluster.ts#L83

It would be fantastic if you could define a default namespace and have the stack check for existing namespace and use that if available, and only attempt to create new space if one by same namespace identifier doesn't' exist.

**Comment by rix0rrr** [comment]
Paging @SoManyHs :)

**Comment by MrArnoldPalmer** [comment]
I may be misinterpreting whats required here but unless we can check for the existence of a corresponding namespace resource and conditionally create a new one using cfn intrinsics, this feels like it requires a custom resource. Correct me if I'm wrong, just trying to get an accurate effort estimate.
