### ISSUE TITLE
lambda: log retention policy is created when log retention role is provided

### ISSUE THREAD

**Issue by gkaskonas** [aws/aws-cdk#27494]
### Describe the bug

When creating a lambda function, passing an existing roleARn should be enough to make it work. However, it keeps creating a policy and attaching it to the role. Why is that the case?

### Expected Behavior

Do not create any policies

### Current Behavior

Creates another policy and attaches it to the role provided

### Reproduction Steps

Create a lambda function with logRetentionRole prop

### CDK CLI Version

2.100.0

### Node.js Version

v18

### OS

macOS

### Language

TypeScript

### Language Version

v5.2.2

**Comment by gkaskonas** [comment]
https://github.com/aws/aws-cdk/blob/61be7a659f22e7ff3df255fc9542214135d07d5e/packages/aws-cdk-lib/aws-logs/lib/log-retention.ts#L159C5-L159C13
This should only be called if the role is not provided

**Comment by peterwoodworth** [comment]
It should be called regardless. If you don't want permissions to be added when passing in a role to a construct, call https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_iam.Role.html#withoutwbrpolicywbrupdatesoptions
