### ISSUE TITLE
(KubernetesVersion): (Add support for Kubernetes version 1.28)

### ISSUE THREAD

**Issue by brecolic** [aws/aws-cdk#27500]
### Describe the feature

The latest Kubernetes version release is 1.28, released on 8/15/2023. AWS announced support on EKS for v1.28 on 9/26/2023 ([blog post here](https://aws.amazon.com/blogs/containers/amazon-eks-now-supports-kubernetes-version-1-28/).)

However, the latest version of the CDK [`2.99.1`] doesn't look to support this version (see the available properties for KubernetesVersion ending on `1.27` [here](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_eks.KubernetesVersion.html)).

Opening this issue to gain visibility into when this new version will be made available in the CDK and add to roadmap if not already.

### Use Case

I have a customer who is building their applications on AWS and wants to use the latest K8s version.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.99.1

### Environment details (OS name and version, etc.)

Kubernetes 1.28

**Comment by khushail** [comment]
Thanks @brecolic for submitting the feature request.
