### ISSUE TITLE
aws-lambda: Invalid principal type for Lambda permission statement: CompositePrincipal.

### ISSUE THREAD

**Issue by AlJohri** [aws/aws-cdk#27503]
### Describe the bug

I am getting an error when trying to use a CompositePrincipal to `grantInvoke` permissions on a lambda.

### Expected Behavior

I expect it to work and allow all of the account principals to invoke the lambda.

### Current Behavior

Currently it errors out and says it is unsupported with the following error:

```
Error: Invalid principal type for Lambda permission statement: CompositePrincipal. Supported: AccountPrincipal, ArnPrincipal, ServicePrincipal, OrganizationPrincipal
```

### Reproduction Steps

This code results in the error:

```typescript
const accounts = new iam.CompositePrincipal(
  new iam.AccountPrincipal('1234'),
  new iam.AccountPrincipal('5678'),
);
myLambda.grantInvoke(accounts);
```

### Additional Information/Context

Possibly related:
- https://github.com/aws/aws-cdk/issues/3264
- https://github.com/aws/aws-cdk/pull/3501

### CDK CLI Version

2.95.0 (build cfa7e88)

### Node.js Version

v18.17.1

### OS

macOS Sonoma

### Language

TypeScript

### Language Version

TypeScript 5.2

**Comment by msambol** [comment]
@peterwoodworth I'll take this.

**Comment by msambol** [comment]
@AlJohri This currently isn't supported but you can do this:

```
    const account1 = new iam.AccountPrincipal('111111111111')
    const account2 = new iam.AccountPrincipal('222222222222')
    myLambda.grantInvoke(account1);
    myLambda.grantInvoke(account2);
```

@peterwoodworth Is this functionality we want to add?

**Comment by peterwoodworth** [comment]
I don't see why not @msambol, feel free to take

**Comment by msambol** [comment]
@peterwoodworth I don't think it makes sense to change `grantInvoke` to accommodate this. I could add a new method if we want to support it, maybe `grantInvokeCompositePrincipal` (basically a wrapper around `grantInvoke`). Thoughts?

**Comment by vinayak-kukreja** [comment]
Hey @msambol, could you tell me why did you not go for accommodating this in `grantInvoke` function? :)

**Comment by msambol** [comment]
@vinayak-kukreja I think it would require updating the function declaration? At the very least the return type. So I thought best to create a new method. I'm open to suggestions though if you think we can do it better.

**Comment by vinayak-kukreja** [comment]
Hey @msambol , I agree, thank you for the clarification.
