### ISSUE TITLE
pipelines: unable to reference GitLab repositories nested under a group with CodePipelieneSource.connection

### ISSUE THREAD

**Issue by akrantz01** [aws/aws-cdk#27504]
### Describe the bug

GitLab repositories that are nested under at least one group cannot be directly with `CodePipelineSource.connection` as it limits repositories to the form `<owner>/<repo>`. GitLab includes the group names in the repository string, falling outside this format (i.e. `owner/group1/group2/groupN/repo`).

### Expected Behavior

I expect the pipeline to synthesize successfully when sourcing from a `CodePipelineSource.connection` that references a GitLab repository nested under multiple groups.

### Current Behavior

The following error is thrown:
```
Error: CodeStar repository name should be a resolved string like '<owner>/<repo>', got 'owner/group1/group2/repo'
```

This error is from [`aws-cdk-lib/pipelines/lib/codepipeline/codepipeline-source.ts` line 429](https://github.com/aws/aws-cdk/blob/b2a895ef285e5451e64c21e179172e998c479582/packages/aws-cdk-lib/pipelines/lib/codepipeline/codepipeline-source.ts#L429).

### Reproduction Steps

```typescript
import * as cdk from 'aws-cdk-lib';
import { CodePipeline, CodePipelineSource, ShellStep } from 'aws-cdk-lib/pipelines';
import { Construct } from 'constructs';

class DummyStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);
  }
}

class DummyApplication extends cdk.Stage {
  constructor(scope: Construct, id: string, props?: cdk.StageProps) {
    super(scope, id, props);

    new DummyStack(this, 'Dummy');
  }
}

export class PipelineStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const pipeline = new CodePipeline(this, 'Pipeline', {
      synth: new ShellStep("Synthesize", {
        input: CodePipelineSource.connection('owner/group/repo', 'main', {
          connectionArn: 'arn:aws:codestar-connections:us-east-1:222222222222:connection/7d2469ff-514a-4e4f-9003-5ca4a43cdc41',
        }),
        commands: [
          'npm ci',
          'npm run build',
          'npx cdk synth',
        ],
      }),
    });

    pipeline.addStage(new DummyApplication(this, 'DummyApp'));
  }
}
```

### Possible Solution

```diff
--- a/packages/aws-cdk-lib/pipelines/lib/codepipeline/codepipeline-source.ts
+++ b/packages/aws-cdk-lib/pipelines/lib/codepipeline/codepipeline-source.ts
@@ -425,11 +425,11 @@ class CodeStarConnectionSource extends CodePipelineSource 
{
     super(repoString);
 
     const parts = repoString.split('/');
-    if (Token.isUnresolved(repoString) || parts.length !== 2) {
+    if (Token.isUnresolved(repoString) || parts.length < 2) {
       throw new Error(`CodeStar repository name should be a resolved string like '<owner>/<repo>', got '${repoString}'`);
     }
     this.owner = parts[0];
-    this.repo = parts[1];
+    this.repo = parts.slice(1).join('/');
     this.configurePrimaryOutput(new FileSet('Source', this));
   }
```

### CDK CLI Version

2.100.0 (build e1b5c77)

### Node.js Version

v18.17.1

### OS

Ubuntu 20.04.6 LTS

### Language

Python

### Language Version

Python 3.8.10

### Other information

As a workaround until this is fixed, you can manually re-implement [`CodeStarConnectionSource`](https://github.com/aws/aws-cdk/blob/b2a895ef285e5451e64c21e179172e998c479582/packages/aws-cdk-lib/pipelines/lib/codepipeline/codepipeline-source.ts#L420-L450) to include the above changes and instantiate directly.

**Comment by peterwoodworth** [comment]
Thanks for the request, this bug makes sense and it should be an easy fix

**Comment by Abhinav-CHD** [comment]
I'd like to work on this issue

**Comment by jgilewski-siili** [comment]
I was happy reading this https://aws.amazon.com/about-aws/whats-new/2023/08/aws-codepipeline-supports-gitlab/ and was struggling with CDK finally finding this issue. Hope it will be fixed soon :)

**Comment by airmonitor** [comment]
Hey.

CDK Team how it's going with fixing that issue?

**Comment by sebastian-kucharzyk-tcl** [comment]
This sounds like an amazing feature for GitLab users (including myself). I'd love to see that happen, especially that there already was a MR for that.

**Comment by afrankevych** [comment]
Is there any update on this?
