### ISSUE TITLE
AmplifyGraphqlApi: latest release for creating a resolver not working (detailed below)

### ISSUE THREAD

**Issue by weisisheng** [aws/aws-cdk#27514]
### Describe the bug

Example found here missing something--https://aws.amazon.com/blogs/mobile/announcing-aws-amplifys-graphql-api-cdk-construct-deploy-real-time-graphql-api-and-data-stack-on-aws/

version: 2.100.0

In the backend stack, amplifyApi.addResolver is not identifying the following:

"Code.fromAsset"

and 

"FunctionRuntime"

Reviewing the docs, this seems to be a new feature.  

### Expected Behavior

Resolver is deployed correctly.

### Current Behavior

IDE shows errors, "can not find foo" for the two items

### Reproduction Steps

Work thru the example given on the blog.

### Possible Solution

Need another module imported?

### Additional Information/Context

Appreciate any tips, tricks...

### CDK CLI Version

2.100.0

### Framework Version

0.00.00

### Node.js Version

v18.17.1

### OS

Ubuntu 23.04

### Language

TypeScript

### Language Version

Node.js

### Other information

N/A

**Comment by renebrandel** [comment]
![image](https://github.com/aws/aws-cdk/assets/4989523/17377289-cf2a-4873-a143-0bdbec590a6e)

**Comment by weisisheng** [comment]
Well done.  Thank you!
