### ISSUE TITLE
aws_ecs_patterns: add customname parameter to ScheduledFargateTaskImageOptions

### ISSUE THREAD

**Issue by mrtngrbmn** [aws/aws-cdk#27515]
### Describe the feature

At the moment for a ScheduledFargateTaskImageOptions a new task definition is created with an automatically generated name. 
This names are quite difficult to read in the AWS web console.

Please add a parameter to assign a custom name to the newly created task definition.

Same thing is possible in aws_ecs.FargateTaskDefinition with parameter family.

### Use Case

I have to create a long list of tasks with similar task definitions. The name created by ScheduledFargateTaskImageOptions are not readable and makes it difficult to distinguish them from each other

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.84.0

### Environment details (OS name and version, etc.)

Amazon Linux 2

**Comment by peterwoodworth** [comment]
Hey, there are a number of similar reported FRs for our patterns constructs. Our patterns are opinionated, if you need fine control over the resources we suggest dropping down to the L2 constructs.

That said, we can still accept this as a feature request, thanks for the ask
