### ISSUE TITLE
kinesisfirehose: example and properties missing for CfnDeliveryStream

### ISSUE THREAD

**Issue by juweeks** [aws/aws-cdk#27522]
### Describe the issue

python documentation version missing for aws_cdk.aws_kinesisfirehose.CfnDeliveryStream. python docs also still on 2.99.1 (should be 2.100?)

### Links

https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_kinesisfirehose/CfnDeliveryStream.html

**Comment by khushail** [comment]
Hi @juweeks , thanks for submitting this request. This is the available [CDK Documentation on CfnDeliveryStream.](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_kinesisfirehose.CfnDeliveryStream.html)

AFAIK, the doc generation process is carried out by [jsii-docgen](https://github.com/cdklabs/jsii-docgen). we write the original implementation in Typescript and it gets translated to supported languages later. So I am hopeful that the subsequent change would soon reflect in Python docs as well.

**Comment by tim-finnigan** [comment]
It looks like the documentation referenced here is available now and reflecting 2.132.1.
