### ISSUE TITLE
apigateway: StepFunctionsIntegrations add default methodResponses

### ISSUE THREAD

**Issue by redvex** [aws/aws-cdk#27520]
### Describe the feature

When StepFunctionsIntegrations is used, it creates methodResponses for 200, 400 and 500 and it's not possible to override this behaviour.

### Use Case

When custom responses are provided they may clash with default ones.
For example one may want setup a different responseTemplate from the one provided.
For example I have a state machine that returns an URL and my responseTemplate set the http status to 302.

### Proposed Solution

Adding a `useDefaultMethodResponses?: boolean` prop (default true) to the `StepFunctionsExecutionIntegrationOptions` interface to avoid adding default responses:

https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-apigateway/lib/integrations/stepfunctions.ts#L160

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.100

### Environment details (OS name and version, etc.)

MacOs Sonoma

**Comment by pahud** [comment]
This makes sense to allow custom response.
