### ISSUE TITLE
ElasticLoadBalancingV2: add dualstack NetworkLoadBalancer creation

### ISSUE THREAD

**Issue by mausman4** [aws/aws-cdk#27538]
### Describe the feature

Currently it is not possible to create a dualstack Network Load Balancer with the higher level construct, it is only possible with the lower level CfnLoadBalancer resource. Dualstack Network Load Balancers were introduced ~3 years ago. 

### Use Case

It is not possible to create a dualstack Network Load Balancer with the higher level construct. It is only possible with the lower level CfnLoadBalancer resource. There are limitations to the CfnLoadBalancer resource; it doesn't have an ARN property, it is not a valid RecordTarget. 

### Proposed Solution

add ipAddressType property to NetworkLoadBalancer. This is implemented for Application Load Balancers so can reference its implementation. 

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.99.1

### Environment details (OS name and version, etc.)

Amazon Linux 2 aarch64 5.10 Kernel

**Comment by pahud** [comment]
I just noticed this

https://github.com/aws/aws-cdk/blob/48d7726421352eb3c032b1293a361a70339b0566/packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/alb/application-load-balancer.ts#L28

And this

https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-ip-address-type.html

Looks like NLB supports dualstack as well.

We can add this property for NLB:

https://github.com/aws/aws-cdk/blob/48d7726421352eb3c032b1293a361a70339b0566/packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/nlb/network-load-balancer.ts#L15-L22
