### ISSUE TITLE
[aws-lambda]: Add support for Dockerfiles not named Dockerfile in DockerImageCode.fromImageAsset

### ISSUE THREAD

**Issue by mainframenzo** [aws/aws-cdk#27549]
### Describe the feature

Lambda.DockerImageCode.fromImageAsset expects Docker image instructions files to be named "Dockerfile", and they might not be. Please consider adding support for Docker image instruction files not named "Dockerfile".

### Use Case

I have a number of Dockerfiles in a single folder that do not work with Lambda.DockerImageCode.fromImageAsset because it expects Docker image instructions files to be named "Dockerfile". For example, given the list of Docker files below, if I specify `Lambda.DockerImageCode.fromImageAsset(path.resolve(process.cwd(), '../build-utils/docker/dockerfile.lambda.backend'))`, the CDK errors with `Cannot find file at <root-path>/build-utils/docker/dockerfile.lambda.backend/Dockerfile`.

Docker files e.g.:
```tree build-utils/docker 
build-utils/docker
├── dockerfile.base
├── dockerfile.lambda.backend
├── dockerfile.lambda.backend.dockerignore
├── dockerfile.lambda.backend.handler.sh
├── dockerfile.lambda.dataset-to-sqlite-db
├── dockerfile.lambda.dataset-to-sqlite-db.dockerignore
├── dockerfile.lambda.dataset-to-sqlite-db.handler.sh
├── dockerfile.run
├── dockerfile.run.dockerignore
├── dockerfile.run.entrypoint.sh
└── lambda-docker-bootstrap.sh
```

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.89.0 (build 2ad6683)

### Environment details (OS name and version, etc.)

Mac Ventura 13.5.2

**Comment by mainframenzo** [comment]
Looks like this exists :)

**Comment by pahud** [comment]
I believe it should exist, no?

https://github.com/aws/aws-cdk/blob/c445b8cc6e20d17e4a536f17262646b291a0fe36/packages/aws-cdk-lib/aws-ecr-assets/lib/image-asset.ts#L256
