### ISSUE TITLE
pipelines: UpdatePipeline stage fails on invalid S3 policy

### ISSUE THREAD

**Issue by ekeyser** [aws/aws-cdk#27542]
### Describe the bug

Upgraded from v2.100.0 to v2.101.0

Upon deployment received the following message (in CodeBuild) for the UpdatePipeline stage. Currently using `pipelines` to facilitate creation of CodePipeline.

```Resource handler returned message: "Policy has invalid action (Service: S3, Status Code: 400, Request ID: XSE075TJK1K319VC, Extended Request ID: ORsos9yz7sdctnOg4AT8QiCjo9irN0v0nBFD/vW/ZxEMW1Y2PclX9Ve0o6lCstdGxQpaHdJjZi8=)" (RequestToken: 3d521b5c-2f09-4c59-09a6-cb30ccdf294e, HandlerErrorCode: GeneralServiceException)```

### Expected Behavior

No difference to our CodePipeline behavior after upgrading.

### Current Behavior

Deploys all the way through without issue on v2.100.0. Fails with above error on v2.101.0.

### Reproduction Steps

Implement CodePipelines using cdk `pipelines` cdk sub-module. Deploy using v2.100.0. Upgrade to v2.101.0. Probably need some lambda assets if this is related to staging S3 assets.

### CDK CLI Version

2.101.0

### Node.js Version

v18.18.1

### OS

LInux

### Language

TypeScript

### Language Version

5.2.2

**Comment by days-later** [comment]
i'm seeing the same error and i'm not using pipelines.

i guess this could be the reason:  https://github.com/aws/aws-cdk/pull/27416#issuecomment-1759505651

**Comment by silo-su** [comment]
I had same issue after upgrading to v2.101.0. Need to downgrade to v2.100.0 to get it worked.

**Comment by Khoulaiz** [comment]
My self modifying Pipeline failed after upgrading to this version. Please revert/fix the patch ASAP or warn your users about this version.

**Comment by NanHeSam** [comment]
+1, running into the same issue initializing a new pipeline

**Comment by denys-tyshetskyy** [comment]
Any ETA on when this is going to be fixed?

**Comment by manu-remsense** [comment]
+1 having the exact same issue

**Comment by roamingthings** [comment]
+1 having the exact same issue

**Comment by Khoulaiz** [comment]
more generic bug is #27547

**Comment by avsteel** [comment]
can confirm was facing same issue in SelfMutate step but latest aws-cdk [2.101.1](https://www.npmjs.com/package/aws-cdk/v/2.101.1) appears to have fixed the issue for me, now able to release successfully.

**Comment by manu-remsense** [comment]
Agree with @avsteel, the latest 2.101.1 resolved the issue for me.

**Comment by HMthyl** [comment]
I'm the same as avsteel and manu-remsense - 2.101.1 fixed this for us!

**Comment by pahud** [comment]
could related to https://github.com/aws/aws-cdk/pull/27416#issuecomment-1759505651
I am closing this issue for now and feel free to reopen it if any concerns.
