### ISSUE TITLE
Policy has invalid action (Service: S3, Status Code: 400,

### ISSUE THREAD

**Issue by davekerber** [aws/aws-cdk#27547]
Please add your +1 👍 to let us know you have encountered this
---

### Overview:
An incorrect action was previously added to the policy attached when calling `bucket.grantRead` based on an incorrect interpretation of an error message. [This PR](https://github.com/aws/aws-cdk/pull/27416) has been reverted and is awaiting release.

#### Complete Error Message:
```
Resource handler returned message: "Policy has invalid action (Service: S3, Status Code: 400, ....
```

### Workaround:
Downgrade to 2.100.0 of `aws-cdk-lib` if encountering this error.

### Solution:
Root cause PR has been reverted and a patch release is out v2.101.1

### Related Issues:
https://github.com/aws/aws-cdk/issues/27389
#27564

### Describe the bug

With this CDK code: 

```typescript
import { Bucket } from "aws-cdk-lib/aws-s3";
import { OriginAccessIdentity } from "aws-cdk-lib/aws-cloudfront";

...

const uiBucket = new Bucket(this, "uiBucket", {...})
const cloudFrontOAI = new OriginAccessIdentity(this, "OAI");
uiBucket.grantRead(cloudFrontOAI.grantPrincipal);
```

When updating from 2.100.0 to 2.101.0 and deploying the same stack I get this output: 
```bash
IAM Statement Changes
┌───┬────────────────────┬────────┬────────────────────┬────────────────────┬───────────┐
│   │ Resource           │ Effect │ Action             │ Principal          │ Condition │
├───┼────────────────────┼────────┼────────────────────┼────────────────────┼───────────┤
│ - │ ${uiBucket.Arn}    │ Allow  │ s3:GetBucket*      │ CanonicalUser:${OA │           │
│   │ ${uiBucket.Arn}/*  │        │ s3:GetObject*      │ I.S3CanonicalUserI │           │
│   │                    │        │ s3:List*           │ d}                 │           │
├───┼────────────────────┼────────┼────────────────────┼────────────────────┼───────────┤
│ + │ ${uiBucket.Arn}    │ Allow  │ s3:GetBucket*      │ CanonicalUser:${OA │           │
│   │ ${uiBucket.Arn}/*  │        │ s3:GetObject*      │ I.S3CanonicalUserI │           │
│   │                    │        │ s3:HeadObject      │ d}                 │           │
│   │                    │        │ s3:List*           │                    │           │
└───┴────────────────────┴────────┴────────────────────┴────────────────────┴───────────┘
```

Then the deployment fails with the error: 

`"Policy has invalid action (Service: S3, Status Code: 400,`

It looks related to #27389. 

I can't find `s3:HeadObject` in the docs (https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazons3.html) and the console will not let me create a policy with that permission.  

Should this have been `s3:GetObjectAttributes` instead?

### Expected Behavior

`bucket.grantRead` should not add invalid actions to a policy. 

### Current Behavior

`bucket.grantRead` adds the invalid action `s3:HeadObject` to the policy. 

### Reproduction Steps

```typescript
import { Bucket } from "aws-cdk-lib/aws-s3";
import { OriginAccessIdentity } from "aws-cdk-lib/aws-cloudfront";

...

const uiBucket = new Bucket(this, "uiBucket", {...})
const cloudFrontOAI = new OriginAccessIdentity(this, "OAI");
uiBucket.grantRead(cloudFrontOAI.grantPrincipal);
```

### Possible Solution

Perhaps change `s3:HeadObject` to `s3:GetObjectAttributes` ?

### CDK CLI Version

2.97.0

### Framework Version

2.101.0

### Node.js Version

18.18.0

### OS

Ubuntu

### Language

TypeScript

### Language Version

5.2.2

**Comment by davekerber** [comment]
Also verified this is still happens with v2.101.0 of the CDK CLI.

**Comment by givsly-stephen** [comment]
Same here with v2.101.0 of the CDK CLI

**Comment by Khoulaiz** [comment]
related to #27542

**Comment by leejh10003** [comment]
+1 Having the exact same issue

**Comment by andresionek91** [comment]
Same issue here:
```
Resource handler returned message: "Policy has invalid action (Service: S3, Status Code: 400, ....
```

**Comment by mbeacom** [comment]
Reverted in https://github.com/aws/aws-cdk/pull/27556 -- once the next release is published, the error shouldn't persist.

**Comment by davekerber** [comment]
@mbeacom  thanks!

**Comment by MrArnoldPalmer** [comment]
@plumdog yikes... sorry about that. [Patch should be out shortly](https://github.com/aws/aws-cdk/pull/27562). The `cliVersion` passed in the pipeline should be used by the [install step in self-mutate](https://github.com/aws/aws-cdk/blob/v2.99.1/packages/aws-cdk-lib/pipelines/lib/codepipeline/codepipeline.ts#L759-L769).

**Comment by plumdog** [comment]
@MrArnoldPalmer indeed! I was able to mitigate by:
- setting `cliVersion: '2.100.0'` and pushing
- pipeline fails in selfmutate
- manually doing the self-mutate on the self-mutate step, eg changing `npm install -g aws-cdk@2` to `npm install -g aws-cdk@2.100.0`
- re-running the pipeline
