### ISSUE TITLE
ecs-patterns: make "cluster" optional in "LoadBalancedFargateService"

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#2754]
We should consider making "cluster" optional when defining a LoadBalancedFargateService (and perhaps even `FargateService`). It is very common for users to just need a single service + cluster, so let's make it minimal effort for them

**Comment by hoegertn** [comment]
This sounds like a great idea, but then you need a way to provide the vpc. I think there is no downside in creating one Cluster per service even if you have more services, but you want them in one VPC.

**Comment by eladb** [comment]
Funny you mention this: https://github.com/awslabs/aws-cdk/issues/2753

**Comment by hoegertn** [comment]
I read that. I think my request is another case.

So in total, we will have:
* no cluster and VPC provided and both will be auto-created
* only cluster provided and VPC will be auto-created
* only VPC provided and Cluster will be auto-created
* both provided

**Comment by eladb** [comment]
* no cluster and VPC provided and both will be auto-created:

```ts
// cluster will be auto-created and implicitly vpc will be auto-created
const service = new ecsp.LoadBalancedFargateService(this, 'service', { image: ... });
const cluster = service.cluster;
const vpc = service.cluster.vpc;
```

* only cluster provided and VPC will be auto-created:

```ts
const cluster = new ecs.Cluster(this, 'cluster'); // vpc is auto-created
const service = new ecsp.LoadBalancedFargateService(this, 'service', { cluster });
const vpc = cluster.vpc;
```

* only VPC provided and Cluster will be auto-created

We *can* support this, but I am wondering how critical is this use case? We could allow `vpc` to be passed to `LoadBalancedFargateService` and only allow that if `cluster` is undefined.

* both provided (the current behavior):

```ts
const vpc = new ec2.Vpc(this, 'vpc');
const cluster = new ecs.Cluster(this, 'cluster', { vpc });
const service = new ecsp.LoadBalancedFargateService(this, 'service', { cluster, ... });
```

**Comment by hoegertn** [comment]
To be honest, the third case is exactly what I would love to do and planned to create a PR for within next days ;-) I have a given VPC (VPN, peering, ...) and I want to run Fargate container in it. So providing the VPC is mandatory but I do not care about the clusters.

If you like I can create the PR for this case.

**Comment by eladb** [comment]
Fair enough, thanks for chiming in. I think it's a legitimate use case. Let's support all of them.

**Comment by hoegertn** [comment]
So should I create a PR or do you want to implement it?

**Comment by eladb** [comment]
Go ahead!

**Comment by pkandasamy91** [comment]
@aws/aws-ecs-devx

**Comment by pkandasamy91** [comment]
Merged as part of https://github.com/aws/aws-cdk/pull/2773
