### ISSUE TITLE
aws_stepfunctions_tasks : Generates wrong action in role policy

### ISSUE THREAD

**Issue by Smotrov** [aws/aws-cdk#27573]
### Describe the bug

Following code is properly creates a step in the Step Function
```
  // Create log stream step  using arn:aws:states:::aws-sdk:cloudwatchlogs:createLogStream
  const createLogStream = new tasks.CallAwsService(scope, 'Create log stream', {
    service: 'cloudwatchlogs',
    action: 'createLogStream',
    parameters: {
      LogGroupName: myLogGroup.logGroupName,
      LogStreamName: sfn.JsonPath.stringAt('$$.Execution.Name'),
    },
    resultPath: sfn.JsonPath.DISCARD,
    iamResources: [myLogGroup.logGroupArn],
  });
```

However, it creates wrong statement in the role action 

```
{
 "Action": "cloudwatchlogs:createLogStream",
 "Resource": "arn:aws:logs:eu-west-1:408064982279:log-group:some_name:*",
 "Effect": "Allow"
},
```

### Expected Behavior

action should be `logs:CreateLogStream`

### Current Behavior

Action is cloudwatchlogs:createLogStream

### Reproduction Steps

Create a step function with provided code.

### CDK CLI Version

v2.101.1

### Node.js Version

v18.16.0

### OS

MacOS

### Language

TypeScript

**Comment by pahud** [comment]
We probably should improve here

https://github.com/aws/aws-cdk/blob/c445b8cc6e20d17e4a536f17262646b291a0fe36/packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/aws-sdk/call-aws-service.ts#L86C24-L86C37

But for now, I believe you should specify this instead.

```
service: 'logs',
```

**Comment by Smotrov** [comment]
> ```
> service: 'logs',
> ```

Unfortunately this doesn't works. There is an error on deployment stage

```
Resource handler returned message: "Invalid State Machine Definition: 'SCHEMA_VALIDATION_FAILED: The resource provided arn:aws:states:::aws-sdk:logs:createLogStream is not recognized. The value is not a valid resource ARN, or the resource is not available in this region.
```
