### ISSUE TITLE
cdk synth returns exit code 0 despite policy validation failures

### ISSUE THREAD

**Issue by rittneje** [aws/aws-cdk#27575]
### Describe the bug

Reopening #26844.

If a custom policy validation reports a failure, `cdk synth` still exits successfully (exit code 0).

Until this is fixed, the plugin is worthless. That the framework was poorly designed does not make this not a bug.

### Expected Behavior

A policy validation failure should result in a non-zero exit code.

### Current Behavior

It reports the failure on stdout/stderr but still exits successfully.

### Reproduction Steps

```python
@jsii.implements(aws_cdk.IPolicyValidationPluginBeta1)
class MyPlugin:
    def validate(self, context):
        return aws_cdk.PolicyValidationPluginReportBeta1(success=False)

def main():
    app = aws_cdk.App(policy_validation_beta1=[MyPlugin()])
    env = aws_cdk.Environment(region="us-east-1", account="...")
    stack = aws_cdk.Stack(app, "test-stack", env=env)
    app.synth()

if __name__ == "__main__":
    main()
```

```bash
cdk synth
echo $?
```

### CDK CLI Version

2.85.0 (build 4e0d726)

### Node.js Version

v18.16.1

### OS

Alpine 3.18

### Language

Python

### Language Version

Python 3.11.4

**Comment by peterwoodworth** [comment]
Thanks for your feedback, I understand you'd like the functionality to be different, but the team has made a decision to not go forward with this. We don't keep issues open we plan to not do anything with, so this issue will be closed out

**Comment by rittneje** [comment]
@peterwoodworth Again, the current functionality is completely useless. I hope one day AWS will actually care about its customers instead of delivering worthless features and ignoring feedback.
