### ISSUE TITLE
aws-cdk-lib/aws-ec2: "Malformed instance type identifier" when creating ec2 instance of type 'm7i-flex.large'

### ISSUE THREAD

**Issue by matt-mclaughlin-quantum-si** [aws/aws-cdk#27587]
### Describe the bug

I'm trying to add an `m7i-flex.large` instance to a managed node group per
`createManagedComputeNodes(
        name,
        subnet,
        [
          new ec2.InstanceType('m7i-flex.large'),
        ],
        eks.CapacityType.SPOT,
      );`

But receive a `Malformed instance type identifier` when doing so.

### Expected Behavior

I'm able to add the `m7i-flex.large` instance type as an instance choice for the managed node group

### Current Behavior

```
Error: Malformed instance type identifier
    at InstanceType.sameInstanceClassAs (/node_modules/aws-cdk-lib/aws-ec2/lib/instance-types.js:1:17751)
    at /node_modules/aws-cdk-lib/aws-eks/lib/managed-nodegroup.js:1:7443
    at Array.some (<anonymous>)
    at isGpuInstanceType (/node_modules/aws-cdk-lib/aws-eks/lib/managed-nodegroup.js:1:7422)
    at typeToArch (/node_modules/aws-cdk-lib/aws-eks/lib/managed-nodegroup.js:1:8182)
    at Array.map (<anonymous>)
    at getPossibleAmiTypes (/node_modules/aws-cdk-lib/aws-eks/lib/managed-nodegroup.js:1:8442)
    at new Nodegroup (/node_modules/aws-cdk-lib/aws-eks/lib/managed-nodegroup.js:1:3543)
    at Cluster.addNodegroupCapacity (/node_modules/aws-cdk-lib/aws-eks/lib/cluster.js:1:19557)

Node.js v20.5.0
```

### Reproduction Steps

Add a `m7i-flex.large` instance type to a managed node group per "Describe the bug".  Then run `cdk synthesize`.

### CDK CLI Version

2.101.1 (build 16ddad1)

### Node.js Version

20.5.0

### OS

MAC OS Monterey 12.6.1

### Language

TypeScript

**Comment by peterwoodworth** [comment]
The regex doesn't allow for hyphens, ths would need to change https://github.com/aws/aws-cdk/blob/b2a895ef285e5451e64c21e179172e998c479582/packages/aws-cdk-lib/aws-ec2/lib/instance-types.ts#L1393

**Comment by bibhu107** [comment]
I would like to contribute here!
Thanks

**Comment by scanlonp** [comment]
@matt-mclaughlin-quantum-si would defining it by `ec2.InstanceType.of(ec2.InstanceClass.M7I_FLEX, ec2.InstanceSize.LARGE)` work? That looks like the preferred instantiation.

**Comment by matt-mclaughlin-quantum-si** [comment]
> @matt-mclaughlin-quantum-si would defining it by `ec2.InstanceType.of(ec2.InstanceClass.M7I_FLEX, ec2.InstanceSize.LARGE)` work? That looks like the preferred instantiation.

@scanlonp Went ahead and tested with that method, but it produces the same result

**Comment by jsamuel1** [comment]
This also affects calling the architecture property of instance type, when constructed with the string 'm7i-flex'.

```ts
// repo aws-cdk-lib 2.115.0, typescript:
var instanceType = new ec2.InstanceType('m7i-flex.xlarge');
var cpuArch : string = instanceType.architecture;
console.log(`cpuArch: ${cpuArch}`);
```

Compiler Output:
```
Error: Malformed instance type identifier
    at InstanceType.get architecture [as architecture] (XXXX/node_modules/aws-cdk-lib/aws-ec2/lib/instance-types.js:1:18931)
```
