### ISSUE TITLE
all the Python docs show TS/JS code samples

### ISSUE THREAD

**Issue by kidbrax** [aws/aws-cdk#2758]
This may have to do with jsii, but for example, if you look at https://pypi.org/project/aws-cdk.aws-codebuild/ the code samples are not Python.  This is not helpful at all, and in fact, probably greatly slows down adoption of the tool.

**Comment by fulghum** [comment]
Hey Braxton, thanks for opening this issue.  You're correct that this shows up as an artifact of generating the Python binding using jsii.  You are also correct that showing TypeScript sample code in Python documentation is not very helpful – we are not satisfied with it either and we want our Python customers to have a rich, Pythonic experience.  

We've got a few high priority items we're focused on, but we've discussed this on the team and want to flesh out a design that enables us to provide multi-language sample code across each CDK API reference. 

We'll leave this issue open to track +1s and progress.  In the meantime, I hope the Python samples in the aws-cdk-examples repo have at least helped provide _some_ useful sample code for you: https://github.com/aws-samples/aws-cdk-examples/tree/master/python

**Comment by eladb** [comment]
I am wondering if in the meantime at least we can add a little note next to each snippet in our docs that will point to https://docs.aws.amazon.com/cdk/latest/guide/multiple_languages.html so people at least not trip over.

**Comment by kidbrax** [comment]
That would be helpful. As soon as I find some time, I plan to to contribute here. But that would be a good start.

**Comment by ccfife** [comment]
Most of the TypeScript code snippets have been translated to Python in the API reference. The (need help translating TypeScript to Python?) note should be updated to an issue template to let the team know if a particular code snippet is incorrect.

**Comment by rix0rrr** [comment]
It is.
