### ISSUE TITLE
aws-cdk-lib/aws-wafv2: ja3fingerprint missing in CDK lib

### ISSUE THREAD

**Issue by xavi-bean** [aws/aws-cdk#27590]
### Describe the feature

The use of ja3 fingerprint is a great new [feature](https://docs.aws.amazon.com/waf/latest/APIReference/API_JA3Fingerprint.html) offered by AWS WAF. However, this is not available to be set up through cdk-lib yet.

### Use Case

To be able to block malicious traffic based on ja3 fingerprint.

### Proposed Solution

Update class FieldToMatchProperty from aws_cdk/aws_wafv2 and include ja3fingerprint as a parameter to be used.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.101.0

### Environment details (OS name and version, etc.)

N/A

**Comment by khushail** [comment]
Hi @xavi-bean , thanks for reaching out.

upon checking [cdk](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_wafv2.CfnWebACL.FieldToMatchProperty.html) and [existing spec file](https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/cfnspec/spec-source/specification/000_cfn/000_official/000_AWS_WAFv2.json), the property is currently not supported. Hence can't be added by CDK.

**Comment by xavi-bean** [comment]
Thanks for your answer @khushail . Just raised this case for Cloudformation team https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1833.

Once this is onboarded in Cloudformation is automatically done in CDK at some point? in case not, what has to be done? Open the same case for CDK?

Thanks
