### ISSUE TITLE
CfnScalingPolicy - support datapointsToAlarm

### ISSUE THREAD

**Issue by dominiquearpin** [aws/aws-cdk#27595]
### Describe the feature

Be able to change the default value of datapointsToAlarm needed to start the process to scale.   Presently, this value is hardcode (3 on 3).

### Use Case

The scaling process is to slow for us, we will like to be able to change the number of occurrence for scaling.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.94

### Environment details (OS name and version, etc.)

CDK

**Comment by peterwoodworth** [comment]
CDK is just a tool to generate CloudFormation templates - if something isn't supported on the L1 then it needs CloudFormation support. You can create issues for them at the [CloudFormation Coverage Roadmap](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues)
