### ISSUE TITLE
lambda: apply data protection policy to generated log group

### ISSUE THREAD

**Issue by tactactactactac** [aws/aws-cdk#27598]
### Describe the feature

Currently there is no idiomatic way to apply a data protection policy to a log group that is automatically generated for a lambda.

It can be done but the solution is hacky -> by creating a log group with the assumed name that the lambda will use before the lambda creates the group. The lambda will then "Adopt" the log group you've made manually.

I believe it would be best if data protection policies can be applied to lambda generated log groups out-of-the-box.

### Use Case

I am attempting to create a data protection policy for my CDK applicatio, but it is not easy to apply a data protection policy to log groups generated by lambda.

If this feature was implemented it would be very easy and natural to apply a data protection policy to a log group generated by a lambda.

### Proposed Solution

I don't exactly know why this feature does not already exist but my assumption is the lambda life-cycles do not allow it normally.

My proposed solution is that when you're configuring a new lambda with a log group you can just apply a data protection policy to the configuration.

### Acknowledgements

- [X] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### CDK version used

2.87.0

### Environment details (OS name and version, etc.)

Mac, 13.5.2 (22G91)

**Comment by pahud** [comment]
I think it's possible. Can you share more about your data protection policy to log groups?


https://github.com/aws/aws-cdk/tree/main/packages/aws-cdk-lib/aws-lambda#log-group

https://github.com/aws/aws-cdk/blob/93904e8a7cb8597f0ce0df34777a93f46c7c0ebf/packages/aws-cdk-lib/aws-lambda/lib/function.ts#L1091-L1110
