### ISSUE TITLE
custom-resource: installLatestAwsSdk could timeout in China regions

### ISSUE THREAD

**Issue by pahud** [aws/aws-cdk#27597]
### Describe the bug

https://github.com/aws/aws-cdk/blob/3f6401c56536e83e1dde87ae730c56d735cf5663/packages/aws-cdk-lib/custom-resources/lib/aws-custom-resource/aws-custom-resource.ts#L351

This function triggers a straight `npm install` which generally would timeout in China regions.

https://github.com/aws/aws-cdk/blob/671b7606ec7d276724ad8ea80695d78a2abac472/packages/%40aws-cdk/custom-resource-handlers/lib/custom-resources/aws-custom-resource-handler/aws-sdk-v3-handler.ts#L24

This is not a bug we just need some workaround for it.

### Expected Behavior

installLatestSdk would not timeout

### Current Behavior

would timeout

### Reproduction Steps

set installLatestAwsSdk to true in custom resource

### Workaround

Set `installLatestAwsSdk: false` or the feature flag `@aws-cdk/customresources:installLatestAwsSdkDefault` to `false`.

See: https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.custom_resources.AwsCustomResource.html#installlatestawssdk

### Possible Solution

I guess China users might need to use npm proxy or alternative mirrors to work it around.

### CDK CLI Version

2.100.0

### Node.js Version

v18.16.0

### OS

linux

### Language

TypeScript

**Comment by pahud** [comment]
loop @zxkane

**Comment by zxkane** [comment]
If you are not using AwsCustomResource to directly call APIs without your custom code, you can use NodejsFunction to bundle the specific SDK within your lambda.

**Comment by pahud** [comment]
I've confirmed this issue doesn't exist in cn-north-1 and cn-northwest-1 anymore with the following code.

```ts
import {
  App, Stack,
  aws_eks as eks,
  aws_ec2 as ec2,
  aws_iam as iam,
} from 'aws-cdk-lib';

import { KubectlV29Layer } from '@aws-cdk/lambda-layer-kubectl-v29';

const app = new App();

const stack = new Stack(app, 'my-test-stack4');

const mastersRole = new iam.Role(stack, 'AdminRole', {
  assumedBy: new iam.AccountRootPrincipal(),
});

const vpc = new ec2.Vpc(stack, 'Vpc', { natGateways: 1 });

new eks.Cluster(stack, 'Cluster', {
  vpc,
  mastersRole,
  version: eks.KubernetesVersion.V1_29,
  kubectlLayer: new KubectlV29Layer(stack, 'KubectlLayer'),
  defaultCapacity: 2,
});
```

[@aws-cdk/customresources:installLatestAwsSdkDefault ](https://github.com/aws/aws-cdk/blob/7103fed9bc03062e464d907818afcf32c27ba6b2/packages/%40aws-cdk/cx-api/FEATURE_FLAGS.md#aws-cdkcustomresourcesinstalllatestawssdkdefault)is now default to false since 2.60.0.
