### ISSUE TITLE
Warn/fail synthesis when reached the 200 resource limit

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#276]
Stack synthesis should fail if number of resources exceeds 200 (potentially warn if we are at 80% of that).

**Comment by eladb** [comment]
still relevant

**Comment by davidrupp** [comment]
I'm painfully aware that this PR doesn't include unit tests; couldn't figure out a way to add one usefully, hoping a seasoned core dev can give me some pointers. I did verify manually by building and linking the change locally against a sample app with varying numbers of resources (< 160, 160 - 200, > 200).

**Comment by rzamana** [comment]
@davidrupp Created my PR based on your work!! Thanks! How can I give you the proper mentioning?

**Comment by davidrupp** [comment]
No need. I'm glad it ended up being useful. :-)
