### ISSUE TITLE
be able to compute all diffs compared to a given cached cdk.out folder

### ISSUE THREAD

**Issue by girotomas** [aws/aws-cdk#27606]
### Describe the feature

It would be great to be able to compute all diffs from a given cdk.out folder.

for example:

```
bb cdk diff --cached ../cdk.out.old
```

This would compute all diffs of all stacks compared to the previous version

### Use Case

I'm super frustrated when I run `cdk diff` and then I need to access 200 aws accounts one for each region and provide contingent authorizations for each one.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

v2

### Environment details (OS name and version, etc.)

typescript amazon-linux

**Comment by pahud** [comment]
do you mean your stacks are from 200 AWS accounts and when you run `cdk diff` you need to make sure they are all authenticated?

**Comment by niebloomj** [comment]
I think this already works if you pass in a wildcard for the stack name
