### ISSUE TITLE
Developer Guide: Working Around Gaps section

### ISSUE THREAD

**Issue by fulghum** [aws/aws-cdk#2763]
We should have an easy to find section that lists how to work around any gaps in CloudFormation features and CDK Construct Library features.  

It should cover: 
* explaining that the CloudFormation low-level resources are always available and stay up to date with CloudFormation (i.e. when high-level constructs aren't available for a use case)
* reference the escape hatch method (i.e. when a high-level construct exists, but doesn't support a feature)
* point to info on building CloudFormation custom resources (i.e. when a feature doesn't exist in CloudFormation yet)

It should also reiterate to customers that we really want to hear feedback when they have to work around a gap so we can address it (or that we also love pull requests). :-)

**Comment by Doug-AWS** [comment]
We have "Work Around Missing AWS CDK Features", https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html. Is that what you want?

**Comment by fulghum** [comment]
This is an excellent start!  Looks like we've got a lot of great details on using the escape hatch.  I think we could add some more intro content at the start of the section to send a strong message that: 1) the CloudFormation low-level resources are always there if there is not a high-level construct present; 2) overrides (which we cover very well already); 3) custom resources are easy and can work around anything you can't do in CloudFormation. 

@eladb – do we have any existing docs on using custom resources?  It would be great to help users know about that as an option.

**Comment by Doug-AWS** [comment]
When we talk about custom resources, do we mean changing the properties of a low-level resource, such as what we describe in https://docs.aws.amazon.com/cdk/latest/guide/resources.html#resources_object?

**Comment by fulghum** [comment]
Nope, custom resources essentially allow you to extend CloudFormation with virtual resources.  We do have an example in TypeScript that we could reference, too:
https://github.com/aws-samples/aws-cdk-examples/tree/master/typescript/custom-resource/
