### ISSUE TITLE
aws-kinesisfirehose-alpha: 2.95.0 removed support for eu-central-2, eu-south-2, ap-south-2

### ISSUE THREAD

**Issue by jstoneham** [aws/aws-cdk#27656]
### Describe the bug

Commit `1604cf4b88af1239253a1ecb1c411ca66f8f57b2` (https://github.com/aws/aws-cdk/commit/1604cf) removed the Firehose CIDR blocks in `packages/aws-cdk-lib/region-info/build-tools/fact-tables.ts` for `eu-central-2`, `eu-south-2`, and `ap-south-2`, so these constructs cannot be synthesized in those regions in 2.95+.

### Expected Behavior

Constructs synth in these regions

### Current Behavior

They don't!

### Reproduction Steps

Synth your normal constructs in one of these regions.

### Possible Solution

CIDR blocks removed

### Additional Information/Context

```
Error: Mapping doesn't contain top-level key 'eu-south-2'
    at CfnMapping.findInMap (/workspace/jgstone/UpgradeCDK/src/MyCDK/node_modules/aws-cdk-lib/core/lib/cfn-mapping.js:1:1419)
    at setConnections (/workspace/jgstone/UpgradeCDK/src/MyCDK/node_modules/@aws-cdk/aws-kinesisfirehose-alpha/lib/delivery-stream.ts:407:32)
    at new DeliveryStreamBase (/workspace/jgstone/UpgradeCDK/src/MyCDK/node_modules/@aws-cdk/aws-kinesisfirehose-alpha/lib/delivery-stream.ts:108:24)
    at new DeliveryStream (/workspace/jgstone/UpgradeCDK/src/MyCDK/node_modules/@aws-cdk/aws-kinesisfirehose-alpha/lib/delivery-stream.ts:317:5)
...
```

### CDK CLI Version

2.99.1 (build b2a895e)

### Node.js Version

18

### OS

MacOS

### Language

TypeScript

**Comment by khushail** [comment]
Hi @jstoneham , thanks for reporting this. I will consult with team on why this change was implemented and get back with updates.

**Comment by khushail** [comment]
@jstoneham , Team is working on this issue and a fix would be provided soon

**Comment by jstoneham** [comment]
Thank you for your prompt attention!

**Comment by SankyRed** [comment]
@jstoneham Working on getting the changes added in for `eu-central-2` and `ap-south-2`. Also wanted to call out that at the moment we do not support `eu-south-2`(Europe (Spain)). Did check the [documentation](https://docs.aws.amazon.com/firehose/latest/dev/controlling-access.html#using-iam-rs-vpc) for the Kinesis Data Firehose CIDR block and seems like we do not support it. Thank you for calling the issue out.
