### ISSUE TITLE
(aws-s3-deployment): (Errors on resource deletion when `retainOnDelete` is set to false)

### ISSUE THREAD

**Issue by massi-ang** [aws/aws-cdk#27651]
### Describe the bug

I deployed a stack using BucketDeployment construct with `reatinOnDelete=false`
I then changed the construct name in the stack and redeployed.
The stack would correctly try to remove the old files, but an error is thrown:

```
3:21:06 PM | DELETE_FAILED        | AWS::CloudFormation::CustomResource             | ...omResourceE9F2C2EB
Received response status [FAILED] from custom resource. Message returned: Command '['/opt/awscli/aws', 's3', 'rm', 's3://bucket-xyz-zf6fdg25ehh1/build-script', '--recursive']' returned non-zero exit status 1. (RequestId: e52c1279-8e5f-466a-9b49-f01d1098e6e5)
```

### Expected Behavior

Files are correctly removed if present

### Current Behavior

An error is thrown (see above)

### Reproduction Steps

Deploy something first using:
``` 
 new s3deploy.BucketDeployment(this, "Script", {
      sources: [s3deploy.Source.asset(path.join(__dirname, "./build-script"))],
      retainOnDelete: false,
      destinationBucket: buildBucket,
      destinationKeyPrefix: "build-script",
    });
```

then change the construct resource name and redeploy
```
 new s3deploy.BucketDeployment(this, "Script-new", {
      sources: [s3deploy.Source.asset(path.join(__dirname, "./build-script"))],
      retainOnDelete: false,
      destinationBucket: buildBucket,
      destinationKeyPrefix: "build-script",
    });
```

### Possible Solution

Automatically add the necessary permission to the custom resource Lambda function

### CDK CLI Version

2.99.1 (build b2a895e)

### Framework Version

2.99.1

### Node.js Version

v20.2.0

### OS

MacOS

### Language

TypeScript

### Language Version

5.1.3

**Comment by khushail** [comment]
Hi @massi-ang , thanks for reaching out.

As stated here for the `retainOnDelete` flag, I tried to repro the issue with the code provided, but it succeeded as stated. `cdk diff` produces this result -
<img width="927" alt="Screenshot 2023-10-23 at 4 40 53 PM" src="https://github.com/aws/aws-cdk/assets/117320115/38710e71-9437-4062-9e51-4e6c93cc4a3e">

could you please share the result of `cdk diff` which might help in understanding the issue on your side.

**Comment by massi-ang** [comment]
Hi Shailja 

thank for the prompt answer. I am not sure I can draw any conclusions from the `cdk diff` you have provided since the issue is about the Lambda function role not having the right permissions to delete objects from the S3 bucket.
