### ISSUE TITLE
(@aws-cdk/aws-gamelift-alpha): Missing properties to support GameLift Server SDK 5+

### ISSUE THREAD

**Issue by wintersieck** [aws/aws-cdk#27655]
### Describe the bug

Two similar issues:

You can't set the `ServerSdkVersion` property when creating a build, which is mandatory to use SDK 5+ (since the default is 4 something). Here's [documentation on the property](https://docs.aws.amazon.com/gamelift/latest/apireference/API_CreateBuild.html#gamelift-CreateBuild-request-ServerSdkVersion) and [the property missing in the CDK documentation](https://docs.aws.amazon.com/cdk/api/v2/docs/@aws-cdk_aws-gamelift-alpha.Build.html).

Similarly, the [enum for operating system](https://docs.aws.amazon.com/cdk/api/v2/docs/@aws-cdk_aws-gamelift-alpha.OperatingSystem.html) doesn't allow setting `AMAZON_LINUX_2023` as [documented here](https://docs.aws.amazon.com/gamelift/latest/apireference/API_FleetAttributes.html#gamelift-Type-FleetAttributes-OperatingSystem).

Thank you!

### Expected Behavior

To be able to set `ServerSdkVersion` and `OperatingSystem`.

### Current Behavior

You can't set `ServerSdkVersion` and `OperatingSystem`.

### Reproduction Steps

N/A

### Possible Solution

- Add a `serverSdkVersion` prop to `Build` and pass it along when calling `CfnBuild`.
- Add `AMAZON_LINUX_2023` to the `OperatingSystem` enum. No logic changes seem to be necessary.

### CDK CLI Version

2.101.1

### Node.js Version

v20.8.1

### OS

Ubuntu (WSL2 on Windows 11)

### Language

TypeScript

### Language Version

5.2.2

**Comment by khushail** [comment]
Thanks @wintersieck for reporting this. Contributions are welcome from the community. 
However, if you would like to contribute, feel free to go through [Contibuting guide.](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md#step-1-find-something-to-work-on)
