### ISSUE TITLE
aws-location: Ability to add API keys through CDK

### ISSUE THREAD

**Issue by adicle** [aws/aws-cdk#27663]
### Describe the feature

Ability to create API keys through Level 1 or Level 2 construct for AWS Location Maps & Places.

### Use Case

Currently this is not supported, therefore requires going outside the scope of CDK into the AWS console to create and manage API keys.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.102.0

### Environment details (OS name and version, etc.)

Windows 11

**Comment by peterwoodworth** [comment]
If something isn't supported at the L1 level then that means CloudFormation does not support it - which means we can't really do anything about this. The best place to go would be the [CloudFormation coverage roadmap](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues), if/when cloudformation support becomes available, it will then be automatically available in CDK.
