### ISSUE TITLE
CDK: ARN function retrieval consistency

### ISSUE THREAD

**Issue by sdpoueme** [aws/aws-cdk#27665]
### Describe the feature

Customers use ARN to wire CDK applications and build custom constructs. The ideal way to retrieve ARNs is to leverage a function attached to the CDK object and extract the value. In most cases, there is no consistent way to retrieve ARNs with CDK. Each construct implements its own method and it impacts developer experience. 

This consistency will make code easier to read and maintain across organizations. In addition, it will help developers adopting new resources faster. Developers can implicitly guess the function required to retrieve ARNs. 

### Use Case

Developers experience is broken when trying to find the way to retrieve ARNs for specific AWS resources. 

### Proposed Solution

Developers may benefit from a consistent method to retrieve ARNs regardless of the service.  e.g: myresource.getARN() 

That function will be available to all CDK resources and will use the specific attribute for each to return the ARN value. 

### Other Information

Related discussions: 
https://bobbyhadz.com/blog/get-arn-aws-cdk

### Acknowledgements

- [X] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### CDK version used

v2.102.0

### Environment details (OS name and version, etc.)

MacOS ventura 13.5.2 (22G91)

**Comment by indrora** [comment]
This should be brought up as an RFC with the team, rather than as a feature request here. 

Please submit one here: https://github.com/aws/aws-cdk-rfcs
