### ISSUE TITLE
aws-cdk-lib: Function.addEventSource with SelfManagedKafkaEventSource results in an Unexpected Error

### ISSUE THREAD

**Issue by sergichisvert-eb** [aws/aws-cdk#27689]
### Describe the bug

Calling `addEventSource`  method using a `SelfManagedKafkaEventSource` as argument in a `lambda.Function` instance results in the following error:

```Function is not a construct. Unexpected error.```

### Expected Behavior

No errors raised. Event source is created as expected.

### Current Behavior

Deploy fails when calling the `addEventSource` method with the following message:

```
Function is not a construct. Unexpected error.
```

### Reproduction Steps

```
const lambdaFunction = new lambda.Function(app, 'the-function', {...});

lambdaFunction.addEventSource(new SelfManagedKafkaEventSource({
  bootstrapServers: ['kafka-broker:9092'],
  topic: 'some-cool-topic',
  secret: new Secret(app, "secret"),
  startingPosition: lambda.StartingPosition.TRIM_HORIZON,
}));
```

### Possible Solution

I haven't found a possible solution. However I've detected that this was working in `aws-cdk-lib@2.99.1` and started failing in `aws-cdk-lib@2.100.0`. I've also tried with `aws-cdk-lib@2.102.0`, same behaviour.

### CDK CLI Version

2.84.0 (build f7c792f)

### Node.js Version

v20.3.0

### OS

macOS 13.6

### Language

TypeScript

### Language Version

typescript@5.2.2

**Comment by sergichisvert-eb** [comment]
To bring more context to this issue: after taking a look at [this comment](https://github.com/aws/aws-cdk/issues/27312#issuecomment-1737919272) in another issue, I've realised that this issue only occurs while running tests with `jest`, but I'm able e.g. to synth the manifest.

We were also using `jest.resetModules()` before each test. After removing that line, all the tests passed as usual.

**Comment by khushail** [comment]
Hi @sergichisvert-eb , could you pls check if this works in the latest CDK version.
