### ISSUE TITLE
aws_ec2: Support for P5 InstanceClass

### ISSUE THREAD

**Issue by niroam** [aws/aws-cdk#27704]
### Describe the feature

The P5 Instance type is now GA, but not currently supported as part of the InstanceClass Enum

### Use Case

P5 instances used in Batch pipelines for ML / Inference workloads, Creating the Batch piplines in CDK requires additional effort without the InstanceClass enum available

### Proposed Solution

Add the missing types to the list.

### Other Information

https://aws.amazon.com/ec2/instance-types/p5/

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.103.0 (build d0d7547)

### Environment details (OS name and version, etc.)

MacOS

**Comment by khushail** [comment]
thanks @niroam for this FR and submittng PR as well.
