### ISSUE TITLE
codepipelineActions.CodeCommitSourceAction: Default branch is 'Master'

### ISSUE THREAD

**Issue by alexclifton4** [aws/aws-cdk#27710]
### Describe the bug

When creating the resource `codepipelineActions.CodeCommitSourceAction`, if `branch` is not specified, it will default to 'master'.

However, when creating a CodeCommit repository through the console, the default branch is 'main', meaning that if everything is kept as default, the pipeline will fail.

### Expected Behavior

The default branch on `codepipelineActions.CodeCommitSourceAction` should be the same as the default branch in CodeCommit

### Current Behavior

`codepipelineActions.CodeCommitSourceAction` defaults to 'master'. If defaults are used, the following error occurs in the pipeline: `The action failed because no branch named master was found in the selected AWS CodeCommit repository`

### Reproduction Steps

1. Create a codecommit repo from the console called 'testRepo'.
2. Upload at least one file through the console - this will create the default branch `main`
3. 
```
pipeline = codepipeline.Pipeline(self, "testPipeline")
sourceOutput = codepipeline.Artifact()
repo = codecommit.Repository.from_repository_name(self, "testRepo", "testRepo")
pipeline.add_stage(stage_name="Source", actions=[
    codepipelineActions.CodeCommitSourceAction(action_name="CodeCommit", repository=repo, output=sourceOutput)
])
```
4. Once CDK has deployed, observe the pipeline in the console - it will have failed.

### Possible Solution

Change the default branch in CDK from "master" to "main"

### CDK CLI Version

2.100.0 (build e1b5c77)

### Node.js Version

v18.12.1

### OS

macOS 13.5.2 (22G91)

### Language

Python

### Language Version

Python 3.9.6 (default, Aug 11 2023, 19:44:49)

**Comment by khushail** [comment]
Hi @alexclifton4 ,thanks for reporting this. I am able to repro this.
