### ISSUE TITLE
aws-lambda: Allow undefined values to be passed to the environment prop of a Function

### ISSUE THREAD

**Issue by piotrekwitkowski** [aws/aws-cdk#27715]
### Describe the bug

TypeScript doesn't allow me to pass objects with undefined props to the environment prop of a Lambda function. 
This code could work but currently doesn't:

```ts
new Function(this, 'function', {
  environment: {
    myOptionalBucketName: thisBucketMayNotExist?.bucketName // <-- could work but doesn't 
  }
}
```

I would like to pass such object and let CDK deal with it.

### Expected Behavior

TypeScript will not mark this as an error, my stack can be synthesized and deployed.

### Current Behavior

I see a type error:
```
Type 'string | undefined' is not assignable to type 'string'.
  Type 'undefined' is not assignable to type 'string'.ts(2322)
function.d.ts(72, 14): The expected type comes from property 'environment' which is declared here on type 'FunctionProps'
```

### Reproduction Steps

Can be reproduced with this code:
```ts
new Function(this, 'function', {
  code: Code.fromInline(''),
  handler: 'index.handler',
  runtime: Runtime.NODEJS_18_X,
  environment: {
    myOptionalBucketName: undefined
  }
}
```

### Possible Solution

The type `[key: string] : string` specified in [function.ts:L82](https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-lambda/lib/function.ts#L82) could be replaced with a `Partial<[key: string] : string>` (or a `Partial<Record<string, string>>`).

If needed, the passed values that are undefined should be filtered out before synth/deployment.

The workaround I need to have today is either conditionally append the prop in another statement or use a somewhat ugly conditional assignment with 
```ts
{
  envVariable1: "aaa",
  ...(myLengthyBucketIdentifier?.bucketName && { myBucketName: myLengthyBucketIdentifier.bucketName })
}
```

### Additional Information/Context

I'm opening this ticket to see if the maintainers see the current behavior as a bug or as a feature. I am able to implement the change/fix if approved.

### CDK CLI Version

2.103.1

### Node.js Version

18.12.1

### OS

MacOS

### Language

TypeScript

**Comment by khushail** [comment]
Hi @piotrekwitkowski , thanks for reaching out. Partial types are [a JSII implementation](https://github.com/aws/jsii/issues/2901) and hence can't be supported.

**Comment by ashishdhingra** [comment]
Closing due to lack of traction.
