### ISSUE TITLE
(EFS): Undocumented breaking change upgrading from 2.92 to 2.93+

### ISSUE THREAD

**Issue by lamebear** [aws/aws-cdk#27728]
### Describe the bug

This PR brought in an undocumented breaking change for existing deployments of EFS mount targets.

https://github.com/aws/aws-cdk/pull/26155

### Expected Behavior

We expect for the name to stay the same in the generated CloudFormation

### Current Behavior

The name of the resource changes, causing a replace action and the CloudFormation ChangeSet to fail.

### Reproduction Steps

Upgrade `aws-cdk-lib` from <=2.92.0 to >=2.93.0 while have EFS mount targets

### CDK CLI Version

2.103

### Node.js Version

v18.18.2

### OS

Linux,OSX,Windows

### Language

TypeScript

### Other information

File in above PR showing change to generated YAML:

https://github.com/aws/aws-cdk/commit/d54b67d9e03fe293784011e285be11f258d0a37c?diff=unified#diff-026b4716bf92acfe8e0d2d83d2c9e4cdd6f75c292c647ea14773ca5c542bfc9e

**Comment by matthiasgubler** [comment]
The breaking change was mentioned here, https://github.com/aws/aws-cdk/issues/25099#issuecomment-1591724414 but mentioned feature-flag seems to be missing.

**Comment by matthiasgubler** [comment]
NVM. I found the feature-flag here: https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/cx-api/FEATURE_FLAGS.md#aws-cdkaws-efsmounttargetorderinsensitivelogicalid
