### ISSUE TITLE
aws_stepfunctions: JsonPath.arrayContains errors when checking for booleans

### ISSUE THREAD

**Issue by Pharrox** [aws/aws-cdk#27722]
### Describe the bug

Using [`JsonPath.arrayConains`](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_stepfunctions.JsonPath.html#static-arraywbrcontainsarray-value) throws an error when trying to check if an array contains a boolean value because the inner function for rendering expressions doesn't account for boolean values:

```
JsonPath.arrayContains(JsonPath.entirePayload, true);
```

### Expected Behavior

Renders the intrinsic function as;

```
States.ArrayContains($, true)
```

### Current Behavior

Throws the error:

```
Error: Unxexpected value.
    at renderInExpression (./aws-cdk-lib/aws-stepfunctions/lib/private/json-path.js:1:5194)
    at Array.map (<anonymous>)
    at Function.arrayContains (./node_modules/aws-cdk-lib/aws-stepfunctions/lib/fields.js:1:2527)
...
```

### Reproduction Steps

Run anywhere in a Typescript CDK app:

```
JsonPath.arrayContains(JsonPath.entirePayload, true);
```

### Possible Solution

Update [`renderInExpression`](https://github.com/aws/aws-cdk/blob/3bb19acf08bdc3f5e99f1dfe0b6eb689f1f269e1/packages/aws-cdk-lib/aws-stepfunctions/lib/private/json-path.ts#L332) to be able to identify and output boolean values.

Probably along the lines of adding:
```
if (typeof x === 'boolean') return x.toString();
```

### Additional Information/Context

Could probably occur in other intrinsic functions. Any intrinsics that uses [`renderInExpression`](https://github.com/aws/aws-cdk/blob/3bb19acf08bdc3f5e99f1dfe0b6eb689f1f269e1/packages/aws-cdk-lib/aws-stepfunctions/lib/private/json-path.ts#L332) seems like it would suffer from this problem.

### CDK CLI Version

2.102.1 (build 8e4485b)

### Framework Version

2.102.1

### Node.js Version

v18.16.0

### OS

Fedora 34 (Workstation Edition)

### Language

TypeScript

### Language Version

4.9.5

**Comment by pahud** [comment]
Thank you for your report. Are you able to provide a minimal reproducible CDK app that we can run in our account?
