### ISSUE TITLE
(iam): CDK always detecting a change when there is none

### ISSUE THREAD

**Issue by gaetansnl** [aws/aws-cdk#27721]
### Describe the bug

I have two account with trust. 

I have one stack called stackA with a property `role` of type `iam.Role`
Then in a second stack in another account i reference `stackA.role.roleArn`

Everything works fine, but everytime I do cdk diff I have this diff
```
           [-]     "Resource": "arn:aws:iam::1234:role/test"
            [+]     "Resource": {
            [+]       "Fn::Join": [
            [+]         "",
            [+]         [
            [+]           "arn:",
            [+]           {
            [+]             "Ref": "AWS::Partition"
            [+]           },
            [+]           ":iam::1234:role/test"
            [+]         ]
            [+]       ]
            [+]     }

```

So it seems that it needs a function to get the string `aws`

### Expected Behavior

No diff

### Current Behavior

A diff

### Reproduction Steps

```typescript
export class StackA extends cdk.Stack {
  public role: iam.Role;
  constructor(
    scope: Construct,
    id: string,
    props: SackAProps,
  ) {
    super(scope, id, props);
    this.role= new iam.Role(this, "user-role", {
      roleName: props.exportedResourcesPrefix + props.userRoleName,
      assumedBy: new iam.ArnPrincipal(props.userArn),
    });
  }
}
const isntanceA = new StackA() ....
  new StackA(app, `xxxxx`, {
    allowedRolesArn: [
     isntanceA.role.roleArn
    ],
    env: {
      account: "otherAccount",
      region: "eu-west-1",
    },
  });
```

### CDK CLI Version

2.103.1

### Node.js Version

v18.1.0

### OS

ubuntu

### Language

TypeScript

**Comment by pahud** [comment]
Can you share a complete minimal sample code that we can reproduce in our environment?

e.g.  `SackAProps` is not defined in your provided code.

**Comment by gaetansnl** [comment]
I will post better reproduction soon

**Comment by gaetansnl** [comment]
seems to work in latest version
