### ISSUE TITLE
@aws-cdk/aws-glue-alpha: Add description to Glue table object

### ISSUE THREAD

**Issue by ksco92** [aws/aws-cdk#27740]
### Describe the feature

Glue tables can already be created with CDK:

https://docs.aws.amazon.com/cdk/api/v2/docs/@aws-cdk_aws-glue-alpha.Database.html

For the purpose of documentation and data governance, the database description field from CFN should be added to this:

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-database-databaseinput.html#cfn-glue-database-databaseinput-description

### Use Case

This will help people that created their data lakes fully on AWS with CDK to embed documentation on IaC. Having to use a different API or manually changing database descriptions is not a feasible option for large scale users with hundreds of databases.

### Proposed Solution

Add the description field to the props of the database object.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

latest

### Environment details (OS name and version, etc.)

MacOS

**Comment by msambol** [comment]
I'll take this.

**Comment by khushail** [comment]
@ksco92 ,thanks for submitting this feature request.

@msambol , appreciate your contribution of PR.

**Comment by ksco92** [comment]
Thanks for the quick turnaround, what is the timeline for this to be released now?
