### ISSUE TITLE
aws-opensearchservice: No support for IM4GN instances

### ISSUE THREAD

**Issue by ksco92** [aws/aws-cdk#27757]
### Describe the bug

No support for IM4GN instances:

https://github.com/aws/aws-cdk/blob/72bf499071dd36ef54c24fce0ac265140291fb4f/packages/aws-cdk-lib/aws-opensearchservice/lib/domain.ts#L1544-L1548

IM4GN instances don't support EBS. Upgrading to IM4GN makes cdk deployments fail.

### Expected Behavior

IM4GN deployments are supported.

### Current Behavior

Error message on build:

`Error: EBS volumes are required when using instance types other than r3, i3 or r6gd.`

### Reproduction Steps

Change the instances type to any IM4GN instance in OS.

### CDK CLI Version

Latest

### Node.js Version

Latest

### OS

MacOS

### Language

TypeScript

**Comment by msambol** [comment]
I'll take this.

**Comment by khushail** [comment]
Thanks @ksco92  for reporting this.

Thanks @msambol for submitting the PR.

**Comment by ksco92** [comment]
Thanks for the quick turnaround, what is the timeline for this to be released now?
