### ISSUE TITLE
(applicationautoscaling): Support timezone on ScalableTarget.scaleOnSchedule

### ISSUE THREAD

**Issue by tl24** [aws/aws-cdk#27754]
### Describe the feature

Cloudformation ScalableTarget [ScheduledAction](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-applicationautoscaling-scalabletarget-scheduledaction.html) supports a timezone property.  The timezone argument is not available when calling ScalableTarget.scaleOnSchedule:
https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_applicationautoscaling.ScalableTarget.html#scalewbronwbrscheduleid-action
https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_applicationautoscaling.ScalingSchedule.html

### Use Case

Cron time expressions have to be entered in UTC.  For timezones observing Daylight Savings Time you have to adjust the schedule when DST starts and again when it ends to get proper scheduling.

### Proposed Solution

Add the timezone property to the ScalingSchedule type that is passed to scaleOnSchedule

### Other Information

I am using the python library, so I would have no way to add this to the json object for ScalingSchedule like you could in JS/TS since the autogenerated code turns these into individual arguments to the scaleOnSchedule call.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.103.1

### Environment details (OS name and version, etc.)

Ubuntu 20.04

**Comment by msambol** [comment]
I'll take this.

**Comment by msambol** [comment]
On second thought, I'm going to wait for the CDK team to comment. There are definitely some assumptions made regarding UTC:
https://github.com/aws/aws-cdk/blob/9babd7aa44752659cc827886acc77c5cb0b103e3/packages/aws-cdk-lib/aws-applicationautoscaling/lib/schedule.ts#L151-L167.

**Comment by sothawo** [comment]
This is an old topic, there was some attempt mentioned in #22645 but up to date still no support for this. Sometimes it seems cdk is the ugly sibling of cfn that noone wants do deal with
