### ISSUE TITLE
(@aws-cdk/s3): InventoryConfiguration[].Id exceeds maximum size allowed by the PutBucketInventoryConfiguration API, when NodeId is overly long

### ISSUE THREAD

**Issue by bweigel** [aws/aws-cdk#27793]
### Describe the bug

In cases where the node-id of the bucket is quite long, the generated `InventoryConfiguration[].Id` will be longer than the [S3 PutBucketInventoryConfiguration](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutBucketInventoryConfiguration.html) API allows. This will cause the cloudformation deployment to fail:

```
Service: Amazon S3; Status Code: 400; Error Code: MalformedXML; Request ID: ...; S3 Extended Request ID: ...; Proxy: null), The XML you provided was not well-formed or did not validate against our published schema.
```

### Expected Behavior

The automatically generated id will satisfy the S3 API and the deployment will be successful.

### Current Behavior

The deployment fails and Cloudformation errors:

```
2:09:29 PM | CREATE_FAILED        | AWS::S3::Bucket       | VeryVeryVeryVeryVe...NodeIdName0592D76A
The XML you provided was not well-formed or did not validate against our published schema (Service: Amazon S3; Status Code: 400; Error Code: MalformedXML; Request ID: RKRENTWF25HGT99P; S3 Extended Request ID: CB8ezYmFdgU+KE9ZABh1sVEp4v
U1kd7r3Kdkse/pxrNTQImcbrFoO7ODJlwVsVRDTcwbLZIRLE8=; Proxy: null)
```

### Reproduction Steps

Example to reproduce:

```ts
const stack = new cdk.Stack();
  
  const inventoryBucket = new s3.Bucket(stack, 'InventoryBucket');
  new s3.Bucket(stack, 'VeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryLongNodeIdName', {
    inventories: [
      {
        destination: {
          bucket: inventoryBucket,
        },
      },
    ],
  });
```

### Possible Solution

Truncating the inventory-id to 64 characters.

---

A workaraound is to set the id manually:

```ts
const stack = new cdk.Stack();

const inventoryBucket = new s3.Bucket(stack, 'InventoryBucket');
new s3.Bucket(stack, 'VeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVery&LongNodeIdName', {
  inventories: [
    {
      destination: {
        bucket: inventoryBucket,
      },
      inventoryId: 'a-short-id'
    },
  ],
});
```

### Additional Information/Context

Relevant correspondence with the AWS support

> Hello ***, 
> 
> I hope you are doing well. This is *** again from AWS premium support.
> 
> [...]
> Our service team has identified that the inventory configuration ID should be limited to 64 characters and can only contain letters, numbers, periods, dashes, and underscores.
> 
> Upon investigation, we found that the ID generated in the shared CDK code exceeds the 64-character limit. We are actively working on updating our documentation to ensure that this information is readily available to other customers in the future. We deeply regret that it took some time to identify that the root cause of this issue was simply an extra character in the ID.
> 
> [...]
> 
> Best regards,
> \***
> Amazon Web Services

### CDK CLI Version

2.103.1 (build 3bb19ac)

### Framework Version

2.103.1

### Node.js Version

v18.17.0

### OS

Linux 5.15.133-1-MANJARO #1 SMP PREEMPT Sat Sep 23 10:10:02 UTC 2023 x86_64 GNU/Linux

### Language

TypeScript

### Language Version

Typescript 5.2.2

**Comment by khushail** [comment]
Hi @bweigel , thanks for reporting this and working on PR.
