### ISSUE TITLE
(apigateway.RequestAuthorizer): (Removing Cache TTL does not reset to default value of 300s)

### ISSUE THREAD

**Issue by bpauwels** [aws/aws-cdk#27826]
### Describe the bug

If you create a custom authorizer and set resultsCacheTtl to any value other then 300s, then later remove the property, I would expect it to reset to the default of 300s. Instead, it remains at the latest set value.

### Expected Behavior

TTL is reset to the default value of 300s

### Current Behavior

TTL remains at the previously set value

### Reproduction Steps

Reproduction Steps:
```
const authorizer = new RequestAuthorizer(this, "LambdaAuthorizer", {
      handler: authorizerHandler,
      resultsCacheTtl: cdk.Duration.seconds(301),
      identitySources: [
        IdentitySource.header("someheader"),
      ],
    });
```

Deploy this, then change it to

```
const authorizer = new RequestAuthorizer(this, "LambdaAuthorizer", {
      handler: authorizerHandler,
      identitySources: [
        IdentitySource.header("someheader"),
      ],
    });
```

### CDK CLI Version

2.96.2

### Node.js Version

16.19.1

### OS

MacOS

### Language

TypeScript

**Comment by pahud** [comment]
Thank you for the report. I have seen an open PR for this issue. We'll review the PR when it's ready.
