### ISSUE TITLE
cli: fix provided generated Go test

### ISSUE THREAD

**Issue by josephbartley** [aws/aws-cdk#27869]
### Describe the bug

After creating an application in Go and uncommenting the provided test, the provided test won't run because it is missing an argument. 

### Expected Behavior

I would expect a test to be able to run as soon as it is uncommented. 

### Current Behavior

The test failed because `not enough arguments in call`

### Reproduction Steps

1. `cdk init app --language go`
2. Navigate to the `_test.go` file
3. Uncomment the file
4. Attempt to run the tests 

### Possible Solution

I have forked this for the minor fix. 

### CDK CLI Version

2.104.0

### Node.js Version

20.8.1

### OS

Linux - Fedora

### Language

Go

### Language Version

1.21.3

**Comment by khushail** [comment]
Thanks @josephbartley for reporting this and submitting a PR. Appreciate it.
