### ISSUE TITLE
(deploy): (deploying bootstrap stack errors out with `The bucket does not allow ACLs` CFN error)

### ISSUE THREAD

**Issue by n-tucker** [aws/aws-cdk#27866]
### Describe the bug

We're trying to update the CDK bootstrap stack in one of our AWS accounts and recently we've started seeing the above error when trying to deploy one of the S3 buckets

![image](https://github.com/aws/aws-cdk/assets/8991772/f4dbbf8e-17e3-44d6-987e-5bea05519523)

When I check the template provided [here](https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml#L185), I can see that this is using the legacy `AccessControl` property.

I'm not sure if I'm missing something, but I'm confused why this property is still being set if this is causing issues? I'm happy to contribute a fix if this is a problem, but I first wanted to confirm if I'm on the right track! 😄 

### Expected Behavior

I should be able to update the bootstrap stack without issues

### Current Behavior

I receive an error when I try and update the bootstrap stack 

### Reproduction Steps

Run `cdk bootstrap --template cloudformation.yaml`

### Possible Solution

Removing the `AccessControl` property, [this guide](https://repost.aws/knowledge-center/cloudformation-objectownership-acl-error) seems to suggest using `ObjectOwnership`

### Additional Information/Context

We do run a custom bootstrap template, however this doesn't touch any of the S3 bucket resources

### CDK CLI Version

2.86.0

### Node.js Version

18.16.1

### OS

Mac Ventura 13.6

### Language

TypeScript

**Comment by khushail** [comment]
Hi @n-tucker ,thanks for reaching out. As mentioned in the CDK Docs [here](https://docs.aws.amazon.com/AmazonS3/latest/userguide/about-object-ownership.html), Bucket policy was updated quite a while ago.

`By default, Object Ownership is set to the Bucket owner enforced setting and all ACLs are disabled. When ACLs are disabled, the bucket owner owns all the objects in the bucket and manages access to data exclusively using access management policies.`

This is the [recommended policy ](https://github.com/aws/aws-cdk/tree/main/packages/aws-cdk-lib/aws-s3#allowing-access-log-delivery-using-a-bucket-policy-recommended)now and the [solution shared by you](https://repost.aws/knowledge-center/cloudformation-objectownership-acl-error) also stands right. Hope that would be helpful!

**Comment by n-tucker** [comment]
Thanks for getting back to me! I'm still unsure as to whether the current bootstrap template needs to be updated?

Based on the info provided in your previous comment, it sounds like disabling ACLs in favour of using `OwnershipControls`? However this isn't currently done in the CDK bootstrap template.

Could you confirm if something needs to changed with the bootstrap template, or if I'm doing something wrong in the bootstrap process?

**Comment by pahud** [comment]
>2.86.0

Is there any reason using 2.86.0 as this has been a while.

I just bootstrap us-west-2 with the latest CDK CLI and it works with no error.

**Comment by scanlonp** [comment]
Related https://github.com/aws/aws-cdk/pull/27764.

**Comment by kyleparisi** [comment]
> Related #27764.

I ran into this today, we have not changed anything related to our cdk deployment in 3 months.  Add in the following s3 bucket prop fixed our bootstrap command:

```javascript
accessControl: BucketAccessControl.PRIVATE,
```

**Comment by kyleparisi** [comment]
Based on this thread, I think something did break for the things that were bootstapped with acls.  My resolution was to skip the `bootstrap` command, continue using `deploy`, in our automation (at the expense of probably my future self) and add the following bucket prop:

```javascript
objectOwnership: s3.ObjectOwnership.BUCKET_OWNER_ENFORCED,
```

The alternative, I'm guessing, would be to do a destroy/up with the appropriate non-acl settings.

**Comment by prazian** [comment]
Upgrading from `2.106.0` to `2.124.0` fixed the issue for me.

`2.106.0` was the version in the scaffolding code created by the `cdk init app --language typescript` command (just now) for this new project.
