### ISSUE TITLE
aws-scheduler-alpha: Schedule Group is ignored

### ISSUE THREAD

**Issue by tvdijk** [aws/aws-cdk#27885]
### Describe the bug

When I set a Schedule Group on a Schedule, the setting is ignored, and my Schedule ends up in the `default` group.

### Expected Behavior

I expect my Schedule to be associated with the Schedule Group I created and specified.

### Current Behavior

The setting is ignored, and my Schedule ends up in the `default` group. The template does not have a `GroupName` attribute set on the `AWS::Scheduler::Schedule` resource.

### Reproduction Steps

```java
        final IGroup scheduleGroup = new Group(this, "ScheduleGroup", GroupProps.builder()
                .build());
        final ISchedule schedule = new Schedule(this, "Schedule", ScheduleProps.builder()
                .group(scheduleGroup)
                .key(appKey)
                .schedule(ScheduleExpression.rate(Duration.minutes(10)))
                .target(LambdaInvoke.Builder.create(function)
                                .retryAttempts(0)
                                .input(ScheduleTargetInput.fromText("{}"))
                                .build())
                .build());
```

### CDK CLI Version

2.104.0 (build 3b99abe)

### Node.js Version

npm@9.5.1

### OS

Windows 10

### Language

Java

### Language Version

Java 11

**Comment by msambol** [comment]
I'll take this.

**Comment by msambol** [comment]
@tvdijk I was able to reproduce this. As a workaround for now, when you're creating the group, you can specify `groupName` (instead of defaulting to the autogenerated name) and the schedule will be added to the group. I'll discuss with the team on how to fix this issue.
