### ISSUE TITLE
lambda-layer-kubectl-v27: update Helm version

### ISSUE THREAD

**Issue by juweeks** [aws/aws-cdk#27896]
### Describe the bug

from what I see, the lambda layers are using a fairly old version of Helm (3.11)

would be nice to also update lambda-layer-kubectl-v26 & lambda-layer-kubectl-v25

### Expected Behavior

Helm version >3.13

### Current Behavior

Helm version ==3.11

### Reproduction Steps

stack diff (for 1.25->1.26) 
![image](https://github.com/aws/aws-cdk/assets/17327142/f08bf1bc-2586-46ff-8d36-2ae232198729)

### CDK CLI Version

2.104.0

### Node.js Version

20.5.1

### OS

Mac 14.1 (Sonoma)

### Language

Python

**Comment by pahud** [comment]
We just ships 1.28 kubectl asset package with Helm 3.13.1.  You can optionally import the `@aws-cdk/lambda-layer-kubectl-v28` package.
https://github.com/cdklabs/awscdk-asset-kubectl/pull/450
