### ISSUE TITLE
(appsync): wrong suggestion for deprecated schema property

### ISSUE THREAD

**Issue by daschaa** [aws/aws-cdk#27895]
### Describe the issue

For the property `schema` in `appsync.GraphqlApi` I see the following documentation:
```
GraphQL schema definition. Specify how you want to define your schema.
SchemaFile.fromAsset(filePath: string) allows schema definition through schema.graphql file Deprecated: use apiSource.schema instead
```
However, there is no property apiSource. I think it's misleading and should be corrected.

### Links

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_appsync.GraphqlApiProps.html#schemaspan-classapi-icon-api-icon-deprecated-titlethis-api-element-is-deprecated-its-use-is-not-recommended%EF%B8%8Fspan

**Comment by pahud** [comment]
https://github.com/aws/aws-cdk/blob/412fb9fd53bddcf6024950f9645bfcc7a51c2aa2/packages/aws-cdk-lib/aws-appsync/lib/graphqlapi.ts#L412

The latest source says "use Definition.schema" instead, which was [updated 5 days ago](https://github.com/aws/aws-cdk/commit/7c497ee998976b69ad1e2cd3e68f30cb593f8ded). We'll check why the doc was not updated. Thanks for the report.

**Comment by daschaa** [comment]
@pahud awesome thanks!
