### ISSUE TITLE
aws_eks: update AlbControllerVersion

### ISSUE THREAD

**Issue by juweeks** [aws/aws-cdk#27890]
### Describe the bug

as of 2.105.0, the latest AlbControllerVersion has been on v2.5.1 for a while now (version has been out since 4/2023). 

please update to current version, which, at this time, is [v2.6.2](https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases) 

### Expected Behavior

alb controller version ~2.6.2

### Current Behavior

alb controller version 2.5.1

### Reproduction Steps

n/a

### CDK CLI Version

2.104.0

### Node.js Version

20.5.1

### OS

Mac 14.1 (Sonoma)

### Language

Python

**Comment by khushail** [comment]
thanks @juweeks for reporting this.
