### ISSUE TITLE
Interactive synthesis (idea)

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#279]
The idea came up at a customer meeting with Anagog. Rotem Dotan described a potential use case for the CDK. They want to vend a "private cloud" for specific customers. Technically, they want to deploy a full Anagog cloud into a customer's account.

They were looking for ways to provide an interactive setup experience where customers would provide answers to questions which will feed into the CDK stack.

This might also be relevant for internal users of BONES, which currently use the BONES-CLI to determine which templates they need in their project.

Rotem mentioned that some answers may require fetching information from other services, so we are not talking only about "primitive values".

**Comment by shivlaks** [comment]
closing stale issue.
