### ISSUE TITLE
aws-lambda: Amazon Linux 2023 Runtime Support

### ISSUE THREAD

**Issue by GrahamCampbell** [aws/aws-cdk#27947]
### Describe the feature

Amazon Linux 2023 Lambda Runtime Support

### Use Case

For using AL 2023 on Lambda.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

N/A

### Environment details (OS name and version, etc.)

N/A

**Comment by daschaa** [comment]
It should be already supported, see here:
https://github.com/aws/aws-cdk/blob/e5959a0a660c9636a1052895d36b360523851508/packages/aws-cdk-lib/aws-lambda/lib/runtime.ts#L265
