### ISSUE TITLE
api-gateway: support kinesis firehose as access log destination in aws-cdk-lib.aws_apigateway.StageOptions

### ISSUE THREAD

**Issue by p3tek** [aws/aws-cdk#27954]
### Describe the feature

Kinesis firehose is an option for access logging through AWS console:
https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-logging-to-kinesis.html

Currently only  `cdk.aws_apigateway.IAccessLogDestination` is accepted for accessLogDestination in `aws-cdk-lib.aws_apigateway.StageOptions` with no way option of providing a firehose data stream meaning only Cloudwatch logs is possible for access logs

### Use Case

I want to be able to use cdk to deploy an rest api with kinesis firehose as an access logging destination 

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.87.0

### Environment details (OS name and version, etc.)

linux

**Comment by khushail** [comment]
Thanks @p3tek for submitting this feature request.
Thanks @lpizzinidev for submitting a PR. Appreciate your contribution.

**Comment by p3tek** [comment]
Thanks for raising the PR @lpizzinidev
