### ISSUE TITLE
Please stop cloudflare and aws from restricting my device. (module name): (short issue description)

### ISSUE THREAD

**Issue by ghost** [aws/aws-cdk#27953]
### Describe the bug

Please detach and allow my independence. I'm not receiving calls or text messages to my device. They are blocking my DNS , which is Google. I live in Atlanta, GA. Why does aws keep my in Canada 
![Screenshot_20231112-214222](https://github.com/aws/aws-cdk/assets/150327785/86ecdda6-aaae-4e46-8cec-e37c7b38e1ca)

### Expected Behavior

Restore my device to default. Secondly, move on, and allow my independence. Inform me if anything additional is needed 

Test started at: 2023-11-12T21:35:05.521-05:00

true: 1. Connect to Google: null
true: 2. Check app status: Server status: OK
true: 3. Connect to app: Your IP address: 172.56.69.62, 18.68.4.133
Your DNS servers: /2607:fb90:e317:4cce::9d; /192.168.139.27; /fd00:976a::9; /fd00:976a::10; /fd00:976a::9; /fd00:976a::10
Hardware ID: droid-3a73fb3666a23a23

Your DNS servers: /2607:fb90:e317:4cce::9d; /192.168.139.27; /fd00:976a::9; /fd00:976a::10; /fd00:976a::9; /fd00:976a::10
Your hardware ID: droid-3a73fb3666a23a23

### Current Behavior

Moving my server to Denmark 

### Reproduction Steps

Please stop

### CDK CLI Version

Not sure 

### Node.js Version

Not sure 

### OS

Android 

### Language

TypeScript

**Comment by kellertk** [comment]
Hi! Can you tell us what this has to do with AWS CDK? We're a little confused with what you're saying because you reported this against the repository that hosts the AWS CDK.
