### ISSUE TITLE
aws_elasticloadbalancingv2.NetworkLoadBalancer: add security groups parameter

### ISSUE THREAD

**Issue by juweeks** [aws/aws-cdk#27963]
### Describe the feature

add aws_elasticloadbalancingv2.NetworkLoadBalancer security group parameter

### Use Case

would like to add a security group parameter to aws_elasticloadbalancingv2.NetworkLoadBalancer like aws_elasticloadbalancingv2.ApplicationLoadBalancer

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.105

### Environment details (OS name and version, etc.)

mac 14.1

**Comment by msambol** [comment]
I'll take this.

**Comment by khushail** [comment]
This seems to be duplicate of already existing request - https://github.com/aws/aws-cdk/issues/26735.

Closing this as duplicate and keep the past one active.

Thanks @juweeks for submitting this request. You can also upvote on the earlier request.

Thanks @msambol for volunteering to take this.
