### ISSUE TITLE
bad cron validation in autoscaling scheduled actions

### ISSUE THREAD

**Issue by wryfi** [aws/aws-cdk#2797]
**Describe the bug**

In [aws-autoscaling/lib/scheduled-action.ts](https://github.com/awslabs/aws-cdk/blob/master/packages/%40aws-cdk/aws-autoscaling/lib/scheduled-action.ts#L78), the constant that validates cron expressions does not allow commas or dashes:

```
const CRON_PART = '(\\*|\\?|[0-9]+)';

const CRON_EXPRESSION = new RegExp('^' + [CRON_PART, CRON_PART, CRON_PART, CRON_PART, CRON_PART].join('\\s+') + '$');
```

This effectively makes it impossible to create certain types of ASG schedules, for example those that do something every weekday.

**To Reproduce**

Add a schedule to an AutoScalingGroup e.g. `asg.scaleOnSchedule('end-workday', {schedule: '45 12 * * 2-6', desiredCapacity: 0});`  

This will throw an error: `Input to ScheduledAction should be a cron expression, got: 45 12 * * 2-6`. 

**Expected behavior**

Cron expressions with commas and dashes do not throw errors, but are passed into cloudformation as valid data.

**Version:**

 - MacOS
 - Typescript
 - 0.33.0

**Comment by made2591** [comment]
A temporary solution in #1181

**Comment by NGL321** [comment]
Hi @wryfi,

Please let me know if the new builds of the CDK have resolved this problem as indicated [here](https://github.com/awslabs/aws-cdk/pull/2817#issuecomment-504350696).
If they have, I will close out the issue, otherwise let me know, and we will look into it further.

Thanks!

**Comment by wryfi** [comment]
Yeah this has been resolved.
