### ISSUE TITLE
Installing libraries in Docker via git

### ISSUE THREAD

**Issue by nicor88** [aws/aws-cdk#28004]
### Describe the bug

When using Lambdas with Docker, or when building ECS containers, I want to be able to install python libraries from via git.

e.g. I want to install git+https://github.com/dbt-athena/dbt-athena@main

When trying to do that I get this error:
> ERROR: Error [Errno 2] No such file or directory: 'git' while executing command git version

### Expected Behavior

I should be able to install a python library hosted in git.

### Current Behavior

Considering that git is not available in the lambda packaging Docker image, I'm not able to install install librabries from git

### Reproduction Steps

```
const MyLambda = new lambda.DockerImageFunction(
      this,
      "MyLambda",
      {
        code: lambda.DockerImageCode.fromImageAsset(
          path.join(__dirname, "./lambdas/my_lambda")
        ),
        timeout: cdk.Duration.seconds(900),
        memorySize: 4096,
        logRetention: logs.RetentionDays.ONE_WEEK,
      }
    );
```

inside `my_lambda` I have thi structure:
* Dockerfile
* requirementst.txt
* app/
   * main.py

## Dockerfile content
```
FROM public.ecr.aws/lambda/python:3.12
# Install the function's dependencies using file requirements.txt
# from your project folder.
COPY requirements.txt  .
RUN  pip3 install -r requirements.txt --target "${LAMBDA_TASK_ROOT}"
# Copy function code
COPY app/main.py ${LAMBDA_TASK_ROOT}
# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
ADD app/components components
CMD [ "main.handler" ]

```

## requirements.txt
```
awswrangler==3.4.2
requests==2.31.0
git+https://github.com/dbt-athena/dbt-athena@main
```

### Possible Solution

Having git installed in the Docker packaing 

### CDK CLI Version

2.91.0

### Node.js Version

v18.0.0

### OS

MacOs

### Language

TypeScript

**Comment by nicor88** [comment]
Simply resolved adding `RUN yum -y install git` to my Dockerfile :)

**Comment by dennybiasiolli** [comment]
Thanks for the hint @nicor88 , I'm using `public.ecr.aws/lambda/python:3.12` and I resolved the same issue adding
`RUN dnf -y install git` to my Dockerfile
