### ISSUE TITLE
CodePipeline AddAction CodeCommitSourceAcction throwing Cannot read property 'node' of undefined

### ISSUE THREAD

**Issue by paulfryer** [aws/aws-cdk#2800]
**Describe the bug**
Generic error ": Cannot read property 'node' of undefined" when trying to use a code commit source.

> Amazon.JSII.Runtime.JsiiException: 'Amazon.JSII.Runtime.JsiiException: Cannot read property 'node' of undefined
>    at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
>    at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
>    at Amazon.JSII.Runtime.Deputy.DeputyBase.<InvokeMethodCore>g__GetResult|18_0[T](<>c__DisplayClass18_0`1& )
>    at Amazon.JSII.Runtime.Deputy.DeputyBase.InvokeMethodCore[T](JsiiMethodAttribute methodAttribute, Object[] arguments, Func`3 beginFunc, Func`3 invokeFunc)
>    at Amazon.JSII.Runtime.Deputy.DeputyBase.InvokeInstanceMethod[T](Object[] arguments, String methodName)
>    at Amazon.CDK.AWS.Codepipeline.Actions.CodeCommitSourceAction.Bind(IActionBind info)'
> 

**To Reproduce**

```

            var repo = new Repository(this, "Reop", new RepositoryProps
            {
                RepositoryName = name,
                Description = "A description here."
            });


            var codePipeline = new Pipeline(this, "Pipeline", new PipelineProps
            {
               
            });
            

            var stage = codePipeline.AddStage(new StageAddToPipelineProps
            {
                Name = "SourceStage"
            });

            var output = new Artifact_("ArtifactName"){};
            stage.AddAction(new CodeCommitSourceAction(new CodeCommitSourceActionProps
            {
                Repository = repo,
                ActionName = "SourceAction",
                Branch = "master",
                Output = output,
                PollForSourceChanges = false,
                RunOrder = 1
            }));
```

**Expected behavior**
It's not clear what "node" is null?

**Version:**
 - OS: Windows 10
 - Programming Language: .Net Core
 - CDK Version: Latest Nuget as of June 8th 2019

**Comment by rileylyman** [comment]
Have you tried adding another stage to your pipeline that uses that output artifact as an input? If so, what is the result of doing that?

**Comment by paulfryer** [comment]
@rileylyman I tried adding the code commit output as the input to the code build action, but still getting the same error. I attached a screenshot here.
![same-error](https://user-images.githubusercontent.com/472725/59233227-71af8c80-8b9c-11e9-8dd5-74d38a2bf500.png)

**Comment by skinny85** [comment]
@paulfryer can you try updating to the latest CDK version (`1.15.0`), and see if the error persists?

Thanks,
Adam

**Comment by SomayaB** [comment]
Closing this issue since there hasn't been a response in a while. Feel free to reopen.
