### ISSUE TITLE
(aws-lambda-python-alpha):  Pipenv lock -r is no longer supported

### ISSUE THREAD

**Issue by josephjnatale** [aws/aws-cdk#28015]
### Describe the bug

When using a custom docker image for a PythonFunction that uses a Pipfile I am getting "Error: No such option: -r" for the ' pipenv lock -r > requirements.txt' command.  In my custom docker image I installed the latest version of pipenv which has since replaced 'pipenv lock -r' with 'pipenv requirements'. https://github.com/pypa/pipenv/issues/5253

### Expected Behavior

Using a custom docker image to bundle a PythonFunction with the latest version of pipenv successfully bundles the lambda function.

### Current Behavior

The CDK synth errors out with "Error: No such option: -r"

### Reproduction Steps

Use a custom docker image with the latest version of pipenv installed to bundle the PythonLambda function and try to synth. 

### Possible Solution

In packaging.ts update withPipenv(): Packaging with pipenv requirements.

### Additional Information/Context

The need for a custom docker image came from pytest not being installed on the default bundler image. However, the example on the documentation page (https://docs.aws.amazon.com/cdk/api/v2/docs/@aws-cdk_aws-lambda-python-alpha.ICommandHooks.html) shows the pytest command in beforeBundling. 

### CDK CLI Version

2.100.0

### Node.js Version

v18.16.0

### OS

Mac OS 

### Language

TypeScript, Python

**Comment by khushail** [comment]
@josephjnatale , thanks for reaching out. Have you tried running this using the latest release?

**Comment by josephjnatale** [comment]
@khushail Updated to CDK CLI Version: 2.109.0 and "@aws-cdk/aws-lambda-python-alpha": "^2.109.0-alpha.0" and I'm getting the same "Error: No such option: -r"

**Comment by khushail** [comment]
Hi @josephjnatale , looks like [this section of code](https://github.com/aws/aws-cdk/blob/78b34accfa1cba88cc412b04df42ea5819c2cf4c/packages/%40aws-cdk/aws-lambda-python-alpha/lib/packaging.ts#L56) might be causing the issue.
