### ISSUE TITLE
@aws-cdk/cloudformation-diff: `this.ipProtocol.toUpperCase is not a function`

### ISSUE THREAD

**Issue by gastonsilva** [aws/aws-cdk#28021]
### Describe the bug

When running cdk diff over a processed cloudformation template (existing stack), some rule `ipProtocol` might be -1 (as number) which produces the exception `this.ipProtocol.toUpperCase is not a function`

### Expected Behavior

Display diff normally

### Current Behavior

`cdk diff` throws `this.ipProtocol.toUpperCase is not a function`

### Reproduction Steps

- Deploy a cloudformation template with a security group and a rule that has a -1 in the ipProtocol
- Import the same cloudformation template in a stack (with the same name) using `cloudformation-include.CfnInclude`
- Run cdk diff

### Possible Solution

This:

https://github.com/aws/aws-cdk/blob/f0939f23c59b8f676880627b3fdf606edcc07db4/packages/%40aws-cdk/cloudformation-diff/lib/network/security-group-rule.ts#L31

Should be replaced by this:
```typescript
this.ipProtocol = ruleObject.IpProtocol?.toString() || '*unknown*';
```

### CDK CLI Version

2.98.0

### Node.js Version

18

### OS

Ubuntu 22.04.3 LTS

### Language

TypeScript

**Comment by pahud** [comment]
Thank you for your report. We'll review your PR when it's ready.
