### ISSUE TITLE
aws-cdk-lib: CfnOriginAccessControl does not give error message for name that is too long

### ISSUE THREAD

**Issue by euanw-cgi** [aws/aws-cdk#28030]
### Describe the bug

When you have a CfnOriginAccessControl configuration with  an `originAccessControlConfig` with a `name` parameter that is too long it does not highlight this in the given error message:

`Resource handler returned message: "Invalid request provided: AWS::CloudFront::OriginAccessControl" (RequestToken: 1aafb6fa-72fe-4ce0-08be-523c109c03c1, HandlerErrorCode: InvalidRequest)`

You just get a `Invalid request` response. 

### Expected Behavior

Error message should highlight that the name parameter is too long.

### Current Behavior

Error message does not reflect why the request is invalid.

### Reproduction Steps

Create a CfnOriginAccessControl resource with a very long name.

### CDK CLI Version

2.109.0

### Node.js Version

v20.3.0

### OS

WSL

### Language

TypeScript

**Comment by msambol** [comment]
I'll take this.

**Comment by pahud** [comment]
@msambol Thank you! Yes we should capture that in CDK.

**Comment by msambol** [comment]
@pahud I took a look.. it's a generated file so I don't think it's possible?

**Comment by euanw-cgi** [comment]
cdk synth works, but cdk deploy does not

**Comment by pahud** [comment]
@euanw-cgi

Are you still having this issue? Can you provide some minimal code snippet so we can address and get it fixed?
