### ISSUE TITLE
globalaccelerator: ip addresses attribute from the Accelerator construct

### ISSUE THREAD

**Issue by werebear73** [aws/aws-cdk#28051]
### Describe the feature

It would be helpful to have the public IP addresses associated with the Accelerator (Global Accelerator) available as properties during stack definition.

### Use Case

As some of applications 3rd party and internally built may require firewall or open port setting requiring the public IP address in configuration, this property (IPAddresses) would be useful.  I haven't found another way (Fn:GetAttr) to be able to get this information easily.

### Proposed Solution

The addition of a read only property of the Accelerator object named something similar to IPAddresses that lists the 2 IP Addresses for the Accelerator object

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.106.0

### Environment details (OS name and version, etc.)

Windows 11, Visual Studio 2022 Community Edition, .Net 6

**Comment by pahud** [comment]
Yes, we should expose that to the L2 attributes with a pull request.

You can work it around with this 

```ts
  const myga = new ga.Accelerator(this, 'GA');
  const cfnAccelerator = myga.node.tryFindChild('Resource') as ga.CfnAccelerator
  cfnAccelerator.attrIpv4Addresses // the IPv4 addresses
```

**Comment by msambol** [comment]
I'll take this.
