### ISSUE TITLE
(rds): Support kerberos authentication on RDS clusters

### ISSUE THREAD

**Issue by tl24** [aws/aws-cdk#28050]
### Describe the feature

Support kerberos (domain and domainIamRoleName arguments) on RDS clusters for authentication.  This is supported on RDS single instances but not clusters.  These arguments are exposed by CloudFormation.

### Use Case

So that I can configure my RDS cluster to support kerberos authentication and not have to maintain separate passwords in RDS.

### Proposed Solution

Add domain and domainIamRoleName props to RDS DatabaseClusterProps and pass those to CfnDatabaseCluster

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.110.0

### Environment details (OS name and version, etc.)

Ubuntu 20.04

**Comment by pahud** [comment]
Thank you for the feature request and we are looking forward to your pull request.
