### ISSUE TITLE
s3 LifecycleRule.ExpirationDate: due to changes in CFN validation last week - template format is broken

### ISSUE THREAD

**Issue by raziza** [aws/aws-cdk#28065]
### Describe the bug

Since last week our template failed to deploy. After talking to AWS customer services seems that last week a strict validation was forced now on this field. which leads the CDK output template to fail.

today the output results this text 

`"ExpirationDate": "2024-11-19T00:00:00"`

as understood from the customer services - `Z` must be added in the end.

our code is doing so:
`lifecycleMaxSizeRuleBuilder.expirationDate(LocalDate.now().plus(1, ChronoUnit.YEARS).atStartOfDay().toInstant(ZoneOffset.UTC));`

### Expected Behavior

With Z in the end
`"ExpirationDate": "2024-11-19T00:00:00Z"`

### Current Behavior

`"ExpirationDate": "2024-11-19T00:00:00"`

### Reproduction Steps

simply synth

### CDK CLI Version

2.109.0

### Node.js Version

16.13.1

### OS

Win 10

### Language

Java

**Comment by msambol** [comment]
I'll take this. Can confirm [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-rule.html#cfn-s3-bucket-rule-expirationdate) there is a `Z` on the end of the pattern.

**Comment by pahud** [comment]
Sounds like a cloudformation validation error? Yes, we should add a trailing Z if it's necessary.
