### ISSUE TITLE
ec2:ResolveSsmParameterAtLaunchImage):   error on deploy.

### ISSUE THREAD

**Issue by mrpackethead** [aws/aws-cdk#28090]
### Describe the bug

I'm passing the name of a ssm parameter to REsolveSSMParamterAtLaunchImage, as the machineimage for an ASG.  Its failing with this error and deploy time. 

7:20:02 AM | CREATE_FAILED        | AWS::AutoScaling::LaunchConfiguration | portalASGLaunchConf
ig16E327B6
Resource handler returned message: "AMI resolve:ssm:portalAMI is invalid: Invalid id: "resolve:
ssm:portalAMI" (expecting "ami-...") (Service: AutoScaling, Status Code: 400, Request ID: 0c8bf
885-13df-4156-b85b-2d9eb1c2c5c6)" (RequestToken: a94bb337-b183-2a4d-4b08-745839d5b9da, HandlerE
rrorCode: InvalidRequest)

```
// create an application scaling group for portal service
    this.portal = new autoscaling.AutoScalingGroup(scope, 'portalASG', {
      vpc: props.vpc,
      allowAllOutbound: false,
      associatePublicIpAddress: false,
      autoScalingGroupName: 'portal',
      cooldown: core.Duration.minutes(5),
      defaultInstanceWarmup: core.Duration.seconds(60),
      minCapacity: 2,
      maxCapacity: 5,
      maxInstanceLifetime: core.Duration.days(7),
      groupMetrics: [autoscaling.GroupMetrics.all()],
      instanceType: ec2.InstanceType.of(ec2.InstanceClass.MEMORY5, ec2.InstanceSize.XLARGE2),
      machineImage: new ec2.ResolveSsmParameterAtLaunchImage(
        props.portalAMIssm,
        {
          cachedInContext: false,
          os: ec2.OperatingSystemType.LINUX,
          // userData:
        },
      ),
      requireImdsv2: true,
      ssmSessionPermissions: true,
      vpcSubnets: { subnetGroupName: 'portal' },
    });
```

### Expected Behavior

for it to resolve the ami value

### Current Behavior

its not resolving.

### Reproduction Steps

see code above

### Possible Solution

not sure.

### CDK CLI Version

2.105.0

### Node.js Version

20

### OS

linux

### Language

TypeScript

**Comment by pahud** [comment]
Looks like your ASG is using launch configuration but this feature only supports launch template.

https://docs.aws.amazon.com/autoscaling/ec2/userguide/using-systems-manager-parameters.html
