### ISSUE TITLE
Toolkit: support removal policy

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#281]
If removalPolicy is set to "Forbid" then "aws:cdk:protect" metadata is set to true for that resource. This is a hint for the toolkit to setup stack update permissions that will forbid deletion of this resource.

Consider if the CDK app and the toolkit can automatically generate a safe stack policy to protect against accidental deletion of "persistent" resources

**Comment by mipearson** [comment]
Found this when searching for `aws:cdk:protected` to see whether the metadata did anything, as was looking through the toolkit to see if it handles stack policies.

Another idea for you: constructs with `frozen: true` options, which apply a stack policy that prevents updates of that construct - eg, prevent updates to RDS instances that could cause unexpected downtime. Then supporting toolkit options that confirm with you whether you want to "unfreeze" the construct for this `cdk deploy` and refreeze it once complete.
