### ISSUE TITLE
aws-cdk-lib/aws-kms: No available option to get the a Alias ARN

### ISSUE THREAD

**Issue by rafaelrcamargo** [aws/aws-cdk#28105]
### Describe the bug

Currently, there is no available option to retrieve an Alias ARN within the AWS KMS module of the AWS CDK.

### Expected Behavior

I expected to find a method or property within the AWS KMS construct that allows retrieving the Alias ARN associated with a specific key.

### Current Behavior

There isn't a direct method or property available to retrieve the Alias ARN associated with a KMS key in the AWS CDK AWS KMS module.

### Reproduction Steps

```
const key = new Key(this, "app_key")
const alias = new Alias(this, "app_key_alias", {
    aliasName: "app/key",
    targetKey: key
})
```

> Now there should be a way to get the ARN like: `alias.aliasArn`

### Possible Solution

One potential fix for this issue could be to introduce a method or property within the KMS module that exposes the Alias ARN associated with a key. Like there is for the `kms.Key`

### Additional Information/Context

Understanding the Alias ARN is crucial for various operational and management tasks involving KMS keys. Having a direct way to retrieve this information within the CDK AWS KMS module would streamline many use cases.

### CDK CLI Version

2.110.0 (build c6471f2)

### Node.js Version

v20.9.0

### OS

Ubuntu 22.04.3 LTS

### Language

TypeScript

### Language Version

Typescript (3.9.10)

### Other information

![image](https://github.com/aws/aws-cdk/assets/66796237/37b5ab00-7d35-42ad-ae7b-50bf4dd0c2f2)
> The ARN is accessible on the AWS Dashboard.

**Comment by pahud** [comment]
Looks like the only return attribute is the alias name:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kms-alias.html

Yes it would be great to return the ARN from L2 construct.

**Comment by daschaa** [comment]
Isn't the `keyArn` method already returning the correct ARN? It looks like it's creating an ARN with the alias name, which should be the desired format. (I've checked the documentation here: https://docs.aws.amazon.com/kms/latest/developerguide/find-cmk-alias.html#find-alias-console)

https://github.com/aws/aws-cdk/blob/b865320674f97bd7dd7cfcc69235d3521e6aa0d4/packages/aws-cdk-lib/aws-kms/lib/alias.ts#L62-L68

**Comment by rafaelrcamargo** [comment]
Thanks for the quick feedback. I noticed that using `keyArn` gives the **Key ARN** for a key, but for an alias, it returns the **Alias ARN**. It's a bit puzzling since the same name refers to different things. This solves the issue, but it might confuse users.

I noticed too that this `alias.aliasTargetKey.keyArn` also retrieves the **Key ARN**. Which makes this a confusing situation:

```ts
const key = new Key(this, "app_key") // My KMS Key
const alias = new Alias(this, "app_key_alias", { targetKey: key })

key.keyArn // My Key ARN
alias.keyArn // My Alias ARN
alias.aliasTargetKey.keyArn // My Key ARN
```
> As we are in the same `kms` context this can be confusing.

Is there a reason behind this naming variation?

**Comment by daschaa** [comment]
I agree, this is indeed very confusing for users. And I don't think there is a purpose behind the naming.

How could we improve this here? Renaming the attribute is not possible, because we have to be backwards compatible. Do you think it would be sufficient to change the documentation?

**Comment by rafaelrcamargo** [comment]
May creating a new `aliasArn` that just mirrors the value from `keyArn` solve this. Of course, this can be bad to maintain due to the duplication of code, but would for sure make things simpler.

Other than that updating the docs would for sure help too, was looking into it and I think this one may be straight up wrong about this: [class Alias (construct)](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_kms.Alias.html#:~:text=resource%20belongs%20to.-,keyArn,The%20ARN%20of%20the%20key.,-keyId).

Let me know what you think about those points and if I can help further.
