### ISSUE TITLE
Guide to bootstrapping using CloudFormation Stacksets missing IAM permission boundary examples

### ISSUE THREAD

**Issue by reidca** [aws/aws-cdk#28119]
### Describe the issue

The guide to bootstrapping an account using CloudFormation stack sets published on the AWS blog makes specific mention of adding an IAM permission boundary but this is not included in the post.

```
In this post, you’ll perform the following steps to deploy the AWS CDK bootstrap template:

Extract the AWS CDK bootstrap CloudFormation template from the AWS CDK CLI
Customize the bootstrap template by adding an IAM permission boundary
```

The post has no further reference to this.

### Links

https://aws.amazon.com/blogs/mt/bootstrapping-multiple-aws-accounts-for-aws-cdk-using-cloudformation-stacksets/

**Comment by khushail** [comment]
Hi @reidca , thanks for reporting this.
For up-to-date documentation and reference, we recommend checking the [official CDK Documentation](https://docs.aws.amazon.com/cdk/v2/guide/bootstrapping.html) . However there is also a blogpost for [defining IAM boundaries](https://aws.amazon.com/blogs/mt/bootstrapping-multiple-aws-accounts-for-aws-cdk-using-cloudformation-stacksets/) as well. For now, I am marking this as P2.

**Comment by khushail** [comment]
@reidca , the examples are maintained in different repo. I have created similar issue with cdk examples team. please [refer to this](https://github.com/aws-samples/aws-cdk-examples/issues/966) for updates.
