### ISSUE TITLE
core: 'cdk synth' always synthesizes every stack

### ISSUE THREAD

**Issue by castleadmin** [aws/aws-cdk#28136]
### Describe the bug

If the command `cdk synth 'Dev/*'` is executed. All stacks are synthesized.

The same output is created in the `cdk.out` directory if a concrete stack is synthesized `cdk synth 'Dev/ExampleStack'`.

### Expected Behavior

Only the `Dev` environment stacks should be synthesized. Only the `Dev` environment lambda assets should be created.

### Current Behavior

All stacks are synthesized. All lambda assets are created.

### Reproduction Steps

Create a project with the following files and execute `cdk synth 'Dev/*'` .

`cdk/app.ts`
```
import { App, Tags } from 'aws-cdk-lib';
import { SourceMapMode } from 'aws-cdk-lib/aws-lambda-nodejs';
import { Construct } from 'constructs';
import { resolve } from 'node:path';
import 'source-map-support/register';
import { Environment } from '../shared/environment';
import { ExampleStack, ExampleStackProps } from './example-stack';

export const createApp = (): App => {
  const app = new App();
  const serviceName = 'testApp';

  new EnvironmentStacks(app, 'Dev', {
    environment: Environment.Dev,
    serviceName,
    env: {
      account:
        process.env['CDK_DEV_ACCOUNT'] ??
        process.env['CDK_DEFAULT_ACCOUNT'] ??
        'not-available',
      region:
        process.env['CDK_DEV_REGION'] ??
        process.env['CDK_DEFAULT_REGION'] ??
        'not-available',
    },
    build: {
      minify: false,
      sourceMapMode: SourceMapMode.INLINE,
      tsconfig: resolve(__dirname, '../tsconfig.app.json'),
    },
  });

  new EnvironmentStacks(app, 'Stage', {
    environment: Environment.Stage,
    serviceName,
    env: {
      account:
        process.env['CDK_STAGE_ACCOUNT'] ??
        process.env['CDK_DEFAULT_ACCOUNT'] ??
        'not-available',
      region:
        process.env['CDK_STAGE_REGION'] ??
        process.env['CDK_DEFAULT_REGION'] ??
        'not-available',
    },
    build: {
      minify: true,
      sourceMapMode: SourceMapMode.EXTERNAL,
      tsconfig: resolve(__dirname, '../tsconfig.app.json'),
    },
  });

  new EnvironmentStacks(app, 'Prod', {
    environment: Environment.Prod,
    serviceName,
    env: {
      account:
        process.env['CDK_PROD_ACCOUNT'] ??
        process.env['CDK_DEFAULT_ACCOUNT'] ??
        'not-available',
      region:
        process.env['CDK_PROD_REGION'] ??
        process.env['CDK_DEFAULT_REGION'] ??
        'not-available',
    },
    build: {
      minify: true,
      sourceMapMode: SourceMapMode.EXTERNAL,
      tsconfig: resolve(__dirname, '../tsconfig.app.json'),
    },
  });

  return app;
};

export type EnvironmentStacksProps = ExampleStackProps;

export class EnvironmentStacks extends Construct {
  constructor(scope: Construct, id: string, props: EnvironmentStacksProps) {
    const { environment, serviceName } = props;

    super(scope, id);

    const exampleStack = new ExampleStack(this, 'ExampleStack', props);

    Tags.of(exampleStack).add('Environment', environment);
    Tags.of(exampleStack).add('App', serviceName);
  }
}

createApp();
````

`cdk/example-stack.ts`
```
import { Duration, Stack, StackProps } from 'aws-cdk-lib';
import { LogFormat, Runtime, Tracing } from 'aws-cdk-lib/aws-lambda';
import {
  Charset,
  NodejsFunction,
  OutputFormat,
  SourceMapMode,
} from 'aws-cdk-lib/aws-lambda-nodejs';
import { RetentionDays } from 'aws-cdk-lib/aws-logs';
import { Construct } from 'constructs';
import { resolve } from 'node:path';
import { Environment } from '../shared/environment';

export interface ExampleStackProps extends StackProps {
  // Define stack properties here

  environment: Environment;
  serviceName: string;
  build: {
    minify: boolean;
    sourceMapMode: SourceMapMode;
    tsconfig: string;
  };
}

export class ExampleStack extends Stack {
  constructor(scope: Construct, id: string, props: ExampleStackProps) {
    const { environment, serviceName, build, ...stackProps } = props;
    const { minify, sourceMapMode, tsconfig } = build;

    super(scope, id, stackProps);

    new NodejsFunction(this, 'ExampleFunction', {
      bundling: {
        charset: Charset.UTF8,
        format: OutputFormat.ESM,
        minify,
        sourceMap: true,
        sourceMapMode,
        tsconfig,
        nodeModules: ['@aws-lambda-powertools/logger'],
      },
      description: 'An example Lambda function.',
      entry: resolve(__dirname, '../src/example-handler.ts'),
      environment: {
        ENVIRONMENT: environment,
        POWERTOOLS_SERVICE_NAME: serviceName,
      },
      handler: 'exampleHandler',
      logFormat: LogFormat.JSON,
      logRetention: RetentionDays.THREE_MONTHS,
      memorySize: 128,
      runtime: Runtime.NODEJS_20_X,
      timeout: Duration.seconds(29),
      tracing: Tracing.ACTIVE,
    });
  }
}
```

`shared/environment.ts`
````
export enum Environment {
  Dev = 'Dev',
  Stage = 'Stage',
  Prod = 'Prod',
}
````

`src/example-handler.ts`
```
import { Context } from 'aws-lambda';

export interface ExampleEvent {
  a: number;
  b: number;
}

export interface ExampleResult {
  sum: number;
}

export const exampleHandler = async (
  event: ExampleEvent,
  context: Context,
): Promise<ExampleResult> => {
  console.log('Example log message', JSON.stringify({ event, context }, null, 2));

  return {
    sum: event.a + event.b,
  };
};
```

### CDK CLI Version

2.110.1

### Framework Version

2.110.1

### Node.js Version

20.9.0

### OS

WSL2 - Ubuntu 22.04.2 LTS

### Language

TypeScript

### Language Version

5.2.2

**Comment by pahud** [comment]
Yes, this seems to be a bug.

**Comment by tmokmss** [comment]
You can try `--exclusively` flag; this should save some time by skipping bundling of stacks you didn't specified.

e.g. `cdk synth --exclusively 'Dev/*'`

**Comment by castleadmin** [comment]
> You can try `--exclusively` flag; this should save some time by skipping bundling (not entire synthesis though) of stacks you didn't specified.
> 
> e.g. `cdk synth --exclusively 'Dev/*'`

Indeed, through the usage of the `--exclusively` flag only the Lambda function assets for the `Dev` environment are synthesized. This is a nice workaround, which speeds up local testing of Lambda functions with AWS SAM. The execution of the synthesize step is needed to generate the CloudFormation template and assets.

**Comment by AllanOricil** [comment]
the `-e` flag does not work all the time.

I have a stack which references a resource from another account, and I asked cdk to synth it with the `-e` flag, but it decided to synthesize everything on a stack that usses this stack. Why?

Im using cdk 2.139.1 (build b88f959)

<img width="594" alt="image" src="https://github.com/aws/aws-cdk/assets/55927613/7a3df45e-e045-44cf-b4c3-21cdbd47be45">

<img width="750" alt="image" src="https://github.com/aws/aws-cdk/assets/55927613/0b6fdeb7-af46-46f0-aa6b-8cdfd9285bf9">

**Comment by AllanOricil** [comment]
edit: it is actually building all my stacks

**Comment by AllanOricil** [comment]
after I commented all stacks but the one I was interested in synth, cdk did what I needed

![image](https://github.com/aws/aws-cdk/assets/55927613/e9759450-0c9f-4afe-8a98-1924543d947f)

**Comment by tmokmss** [comment]
@AllanOricil 
iirc with `--exclusively` flag, only **bundling** steps (e.g. bundling assets like lambda code) are skipped, while **building** steps (e.g. generating CFn template) always run. In my experience, bundling steps are usually the biggest contributor to the duration of synthesis, so skipping bundling greatly reduced synthesis time.

That said, I sometimes add an environment variable to entirelly include/exclude certain stacks, that do not have dependencies with each other, from `bin/cdk.ts`, e.g.

```ts
// bin/cdk.ts
if (process.env.ENV=='prod') {
  new SomeStack(app, "ProdStack");
} else {
  new SomeStack(app, "DevStack");
}
```

this allows you to synth only the required stacks by modifying the cdk deploy command:

```sh
 # build and deploy only DevStack
npx cdk deploy --all

 # build and deploy only ProdStack
ENV=prod npx cdk deploy --all
```

**Comment by AllanOricil** [comment]
So there is some kind of bug because the bundling steps are also running 😅
I thought it was an issue with 2.139, but 2.138 also has this issue.

**Comment by AllanOricil** [comment]
this is how the "instance-provisioning" stack bundles its lambda functions, which the bundling is triggered whenever I try to deploy that simple "route-53-stack". Coul it be related to `cdk.DockerImage.fromBuild`?

```js
bundling: {
          sourceMap: true,
          nodeModules: ["winston", "@sentry/serverless"],
          externalModules: ["aws-sdk", "@aws-sdk"],
          user: "root",
          forceDockerBundling: true,
          dockerImage: cdk.DockerImage.fromBuild(
            DEFAULT_DOCKER_BUILD_IMAGES_PATH,
            {
              file: "ci.Dockerfile",
            },
          ),
          commandHooks: {
            beforeBundling(i: string, o: string): string[] {
              return ['echo "BEFORE BUNDLING"'];
            },
            beforeInstall(i: string, o: string): string[] {
              return ['echo "BEFORE INSTALL"'];
            },
            afterBundling(i: string, o: string): string[] {
              return [
                'echo "AFTER BUNDLING"',
                `cp ${i}/.sentryclirc .`,
                `sentry-cli sourcemaps inject --org journeylab --project create-route-53-records .`,
                `sentry-cli sourcemaps upload --org journeylab --project create-route-53-records .`,
                `rm .sentryclirc`,
              ];
            },
          },
        },
      },
```

**Comment by AllanOricil** [comment]
@tmokmss evidence to show that `-e` flag has a problem

<img width="747" alt="image" src="https://github.com/aws/aws-cdk/assets/55927613/99d626be-3d99-4222-8bba-a53c443bf6c6">

<img width="612" alt="image" src="https://github.com/aws/aws-cdk/assets/55927613/d6fa1630-f20e-444b-8ab1-cebbddb5cb9a">

As you can see, cdk triggered the bundling phase of a stack that I did not even asked it to deploy when running `cdk deploy` with `-e`. This vpc stack has dependencies, but they shouldnt be built if Im not deploying them and Im using `-e`

<img width="1300" alt="image" src="https://github.com/aws/aws-cdk/assets/55927613/36258d3c-20e0-42d8-9110-0ee8df3ae3f5">

**Comment by tmokmss** [comment]
`cdk.DockerImage.fromBuild` builds a container image as soon as it is called. `--exclusively` flag does not affect that behavior, I guess.

**Comment by comcalvi** [comment]
This looks like the same issue as https://github.com/aws/aws-cdk/issues/28136

**Comment by comcalvi** [comment]
That issue has more upvotes, so I'm closing this one in favor of the other one - please continue the discussion there.
