### ISSUE TITLE
(lambda-python-alpha): cdk synth gets stuck forever

### ISSUE THREAD

**Issue by gabriels1234** [aws/aws-cdk#28135]
### Describe the bug

version: 2.110.1a0

cdk synth gets stuck forever.
tried also creating a new project.
Tried with other assets, synth is ok. when adding a PythonLambda and then run cdk synth it gets stuck.
It was working before, So I'm trying to backtrack the issue to the cdk version, to the code (reduced the lambda to just do "hello world").
probably it's a non-issue, but since I've been trying for hours already, perhaps someone else finds it useful.

### Expected Behavior

cdk synth should either:
- exit with error
- finish successfully
- provide feedback on where is it, to understand where it got stuck

### Current Behavior

cdk synth says nothing, for hours.

### Reproduction Steps

"Tried with other assets, synth is ok. when adding a PythonLambda and then run cdk synth it gets stuck."

### CDK CLI Version

2.110.1a0

### Node.js Version

18.17.1

### OS

Mac OS 13.4

### Language

Python

### Language Version

3.11

**Comment by gabriels1234** [comment]
```
        lambda_function = _alambda.PythonFunction(
            self, "CdkAppLambda",
            entry="./lambda",
            index="main.py",
            handler="handler",
            runtime=_lambda.Runtime.PYTHON_3_7,
            timeout=Duration.seconds(300),
        )
```
this gets stuck, but only after the entry and index are correct, otherwise it will exit with error immediately.

**Comment by gabriels1234** [comment]
FYI, cdk synth failed after quitting Docker Desktop.
Restarting docker desktop fixed the issue. (It was not self-evident, though)

**Comment by pahud** [comment]
It could because your local docker command just hanged without any response because the PythonFunction would bundle with docker.

**Comment by douglascayers** [comment]
> FYI, cdk synth failed after quitting Docker Desktop. Restarting docker desktop fixed the issue. (It was not self-evident, though)

Bless you, restarting Docker resolved the stuck `cdk synth` command for me. Thanks!
