### ISSUE TITLE
(aws-s3): server access logging support automatic date-based partitioning

### ISSUE THREAD

**Issue by mrgrain** [aws/aws-cdk#28141]
### Describe the feature

S3 Bucket Logging Configuration should support automatic date-based partitioning for delivered logs.

### Use Case

See: https://aws.amazon.com/about-aws/whats-new/2023/11/amazon-s3-server-access-logging-date-partitioning/

### Proposed Solution

Probably need to introduce a new property and/or enum class to allow setting the [TargetObjectKeyFormat](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-targetobjectkeyformat.html)

### Other Information

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-partitionedprefix.html
https://docs.aws.amazon.com/AmazonS3/latest/userguide/ServerLogs.html

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

any

### Environment details (OS name and version, etc.)

any

**Comment by msambol** [comment]
I'll take this.

**Comment by msambol** [comment]
@mrgrain This depends on an update to `s3.generated.ts`. I _think_ I should be using `spec2cdk` to update that? It won't pick up the new property.

```
❯ ./bin/spec2cdk ../../../packages/aws-cdk-lib/aws-s3/lib/ -s AWS::S3
Generating 1 modules...
Summary:
  Service files:  1
  Resources:      7
🐢  Completed in: 54.442ms
```

**Comment by mrgrain** [comment]
I'm guessing you need to wait for the next [AWS Service Spec Update](https://github.com/aws/aws-cdk/actions/runs/7002700145) PR to come through. That happens every Monday.
