### ISSUE TITLE
aws-cdk-lib/aws-rds: please add AuroraPostgresEngineVersion 15.4 

### ISSUE THREAD

**Issue by AirSantix** [aws/aws-cdk#28158]
### Describe the feature

Aurora Postgres 15.4 was released. Please add the Version to the aws-cdk-lib/aws-rds

### Use Case

New Version was released and I want to use it.

### Proposed Solution

    /** Version "15.4". */
    static readonly VER_15_4: AuroraPostgresEngineVersion;

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.110.1

### Environment details (OS name and version, etc.)

Mac OS - CDK Typescript

**Comment by pahud** [comment]
Yes we welcome any pull request from the community like https://github.com/aws/aws-cdk/pull/26377

**Comment by go-to-k** [comment]
This version seems to have just been merged.

https://github.com/aws/aws-cdk/pull/27731

**Comment by ConnorRobertson** [comment]
Closing as https://github.com/aws/aws-cdk/pull/27731 merged this.
