### ISSUE TITLE
(aws-events-targets): (imported dead letter queue could not anymore be associated to a Rule)

### ISSUE THREAD

**Issue by JeromeGuyon** [aws/aws-cdk#28165]
### Describe the bug

Previously (2.95.1), I was able to associate a DLQ to a Rule. 

In last version (2.111.0), it is nor more possible : 

```
const failedEventQueue = sqs.Queue.fromQueueArn(
      this,
      "FailedEventsQueue",
      ssm.StringParameter.valueForStringParameter(
        this,
        `xyz/failed-events-queue-arn`
      )
    );
    
eventRule.addTarget(
      new targets.SqsQueue(aQueue, {
        messageGroupId: messageGroupId,
        deadLetterQueue: failedEventQueue,
        maxEventAge: cdk.Duration.seconds(60),
        retryAttempts: 0,
      })
    ); 
```

Generate

```
Error: Cannot assign Dead Letter Queue in region ${Token[TOKEN.35]} to the rule XYZEventRule89558AAC in region eu-west-1. Both the queue and the rule must be in the same region.
```

### Expected Behavior

It should be possible to support imported SQS Queue as DLQ.

### Current Behavior

```
Error: Cannot assign Dead Letter Queue in region ${Token[TOKEN.35]} to the rule XYZEventRule89558AAC in region eu-west-1. Both the queue and the rule must be in the same region.
```

### Reproduction Steps

```
const failedEventQueue = sqs.Queue.fromQueueArn(
      this,
      "FailedEventsQueue",
      ssm.StringParameter.valueForStringParameter(
        this,
        `xyz/failed-events-queue-arn`
      )
    );
    
eventRule.addTarget(
      new targets.SqsQueue(aQueue, {
        messageGroupId: messageGroupId,
        deadLetterQueue: failedEventQueue,
        maxEventAge: cdk.Duration.seconds(60),
        retryAttempts: 0,
      })
    ); 
```

and in stack
`env: { account: process.env.CDK_DEFAULT_ACCOUNT, region: process.env.CDK_DEFAULT_REGION },`

### Possible Solution

N/A

### CDK CLI Version

2.108.0

### Node.js Version

v18.13.0

### OS

macos

### Language

TypeScript

### Language Version

TypeScript (5.2.2)

**Comment by pahud** [comment]
Is the error message from cloudformation?

Looks like the region of the failedEventQueue can't be resolved.

```ts
const failedEventQueue = sqs.Queue.fromQueueArn(
      this,
      "FailedEventsQueue",
      ssm.StringParameter.valueForStringParameter(
        this,
        `xyz/failed-events-queue-arn`
      )
    );
```

Can you assign a static ARN to `failedEventQueue` without retrieving from ssm and see if the error still exists?

And, can you confirm if the value is successfully retrieved from the given parameter?

**Comment by sjbthfc2** [comment]
I am having the same issue, I have checked that the Rule and Dead Letter Queue are in the same region but I can't resolve this.

**Comment by sjbthfc2** [comment]
I can confirm that after reverting back to CDK version 2.93.0, it works. Looks like this is a bug with latest version.

**Comment by JeromeGuyon** [comment]
> Is the error message from cloudformation?
> 
> Looks like the region of the failedEventQueue can't be resolved.
> 
> ```ts
> const failedEventQueue = sqs.Queue.fromQueueArn(
>       this,
>       "FailedEventsQueue",
>       ssm.StringParameter.valueForStringParameter(
>         this,
>         `xyz/failed-events-queue-arn`
>       )
>     );
> ```
> 
> Can you assign a static ARN to `failedEventQueue` without retrieving from ssm and see if the error still exists?
> 
> And, can you confirm if the value is successfully retrieved from the given parameter?

Sorry for the delay, : 

I tried with `const deadLetterQueue = new sqs.Queue( ` => Working
With const `deadLetterQueue = sqs.Queue.fromQueueArn(this,'MyDeadLetterQueue',"arn:aws:sqs:eu-west-1:444455556666:queue1")` => Synth fails

issue still exists in 2.114.1

**Comment by JeromeGuyon** [comment]
last working release : 2.108.1, bug introduced in 2.109.0

This Commit introduce the regression : 
https://github.com/aws/aws-cdk/commit/e789adca33b0ef2f1a3a94373867e0ae123edc02
last working release : 2.108.1, bug introduced in 2.109.0

Maybe it has been introduced with this PR  
https://github.com/aws/aws-cdk/commit/633dbe281e200a63a2588803c8dd30c8daf3f672
https://github.com/aws/aws-cdk/pull/27906

**Comment by JeromeGuyon** [comment]
With https://github.com/aws/aws-cdk/pull/27906 PR, the region/account is now considered as **resolved** and are not anymore tokens. 

As a workaround, I suggest changing 

`return [TokenComparison.SAME, TokenComparison.BOTH_UNRESOLVED].includes(Token.compareStrings(dim1, dim2));`

to 

`return [TokenComparison.SAME, TokenComparison.BOTH_UNRESOLVED,, TokenComparison.ONE_UNRESOLVED].includes(Token.compareStrings(dim1, dim2));`

**Comment by kaizencc** [comment]
Looks like a [small] regression we've introduced, so labeling this p0. It isn't going to matter much in terms of priority, as @JeromeGuyon has already created a fix that has been accepted (thanks :)).
