### ISSUE TITLE
[GitHub] No Branch [branch] found for FullRepositoryName [branch]Tracking: [service]

### ISSUE THREAD

**Issue by sabin2018** [aws/aws-cdk#28164]
### Overview

after configure my pipeline manifest i run `copilot pipeline deploy` it give me `Successfully deployed pipeline` message but my pipeline fails with message [GitHub] No Branch [branch] found for FullRepositoryName [branch] at AWS pipeline console. I run my pipeline command under same environment. 

### Link to the service’s CDK Construct Library API reference page.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-cluster.html

### Maturity: CloudFormation Resources Only

CloudFormation Resources Only

### Implementation

i had run in the same environment 

### Issue list

- [GitHub] No Branch [branch] found for FullRepositoryName [branch]Tracking: [service]
- [ ]

**Comment by piradeepk** [comment]
Closing as this issue does not look to be related to the AWS-CDK.
