### ISSUE TITLE
aws-cdk-lib/aws-cloudfront: Unable to select all headers in CachePolicy CacheHeaderBehavior

### ISSUE THREAD

**Issue by ppenelon-kiliba** [aws/aws-cdk#28168]
### Describe the bug

I'm using CDK to create a CloudFront distribution following the requirements of SendGrid "[How to configure SSL for click tracking using CloudFront](https://support.sendgrid.com/hc/en-us/articles/4412701748891-How-to-configure-SSL-for-click-tracking-using-CloudFront)".

It's required here to select "All headers" in the "legacy" cache policy settings. It is totally possible to do it via the CloudFront console but not via CDK (only "none" and "whitelist" allowed).
<img width="827" alt="image" src="https://github.com/aws/aws-cdk/assets/114905265/290c4665-c8b3-4345-8646-6f387b1f213f">

The "all" option is available for `cookieBehavior` and for `queryStringBehavior`.
<img width="670" alt="image" src="https://github.com/aws/aws-cdk/assets/114905265/eb3874fb-f850-465d-8bf2-430808335fed">

### Expected Behavior

To be able to set the "all headers" value to the `headerBehavior` property.
```typescript
const cachePolicy = new CloudFront.CachePolicy(this, "CachePolicy", {
	headerBehavior: CloudFront.CacheHeaderBehavior.all()
});
```

### Current Behavior

```typescript
const cachePolicy = new CloudFront.CachePolicy(this, "CachePolicy", {
	headerBehavior: CloudFront.CacheHeaderBehavior.all()
});
```

Throws a Typescript error

```typescript
const cachePolicy = new CloudFront.CachePolicy(this, "CachePolicy", {
	headerBehavior: CloudFront.OriginRequestHeaderBehavior.all()
});
```

Throws a CloudFormation error while creating the stack with the following error :
> Model validation failed (#/CachePolicyConfig/ParametersInCacheKeyAndForwardedToOrigin/HeadersConfig/HeaderBehavior: failed validation constraint for keyword [pattern])

### Reproduction Steps

Create the following Cache Policy.

```typescript
const cachePolicy = new CloudFront.CachePolicy(this, "CachePolicy", {
	headerBehavior: CloudFront.CacheHeaderBehavior.all()
});
```

### CDK CLI Version

2.70.0

### Framework Version

2.50.0

### Node.js Version

18.17.1

### OS

MacOS

### Language

TypeScript

### Language Version

TypeScript (4.9.5)

### Other information

I saw a related issue (#16962) but was about the origin request settings and was close without solution for the CacheHeaderBehavior all problem.

**Comment by ppenelon-kiliba** [comment]
Legacy configuration translates to origin request `ALL_VIEWER`, cache `CACHING_DISABLED `

```typescript
const distribution = new CloudFront.Distribution(this, "Distribution", {
  defaultBehavior: {
    cachePolicy: CloudFront.CachePolicy.CACHING_DISABLED,
    originRequestPolicy: CloudFront.OriginRequestPolicy.ALL_VIEWER
  }
});
```

Source: https://repost.aws/questions/QUotfRrCe4Tl6QVfKAhzTMeQ/what-new-cache-and-origin-request-policy-matches-our-legacy-cache-settings

**Comment by victorresola** [comment]
> Legacy configuration translates to origin request `ALL_VIEWER`, cache `CACHING_DISABLED `
> 
> ```ts
> const distribution = new CloudFront.Distribution(this, "Distribution", {
>   defaultBehavior: {
>     cachePolicy: CloudFront.CachePolicy.CACHING_DISABLED,
>     originRequestPolicy: CloudFront.OriginRequestPolicy.ALL_VIEWER
>   }
> });
> ```
> 
> Source: https://repost.aws/questions/QUotfRrCe4Tl6QVfKAhzTMeQ/what-new-cache-and-origin-request-policy-matches-our-legacy-cache-settings

This one works.
