### ISSUE TITLE
(aws-cdk): (Unable to create nested stack with > 500 resources)

### ISSUE THREAD

**Issue by benliger1987** [aws/aws-cdk#28186]
### Describe the bug

I am using a nested stack inside of a regular stack to get past the resource limit of 500 in a stack. After moving 413 resources to a nested stack I receive the following error on deployment:

```[Info at /dev/Frontend/LambdasApi-dev] Number of resources: 413 is approaching allowed maximum of 500```

Please note that `/dev/Frontend/LambdasApi-dev` refers to my nested stack. 

As per the resource limits stated in this table here:

[https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cloudformation-limits.html](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cloudformation-limits.html)

Nested stacks should have a max resource limit of 2500, not 500 hence the bug.

The part of the repository that gives this warning is here, the nested stack class simply extends the stack with some modifications, resource limit is not one of those modifications:

https://github.com/aws/aws-cdk/blob/8e42fe6f765b3556f0e4038f8ae252d48a46ed98/packages/aws-cdk-lib/core/lib/stack.ts#L1086

### Expected Behavior

I would expect to be able to create 2500 resources in a nested stack as per the documentation here:

[https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cloudformation-limits.html](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cloudformation-limits.html)

### Current Behavior

I receive a warning message if I am close to going over 500 resources in a nested stack and presumably an error if I do go over 500

### Reproduction Steps

1. Create a stack 
2. Create a nested stack within the first stack
3. Populate the nested stack with >400 resources to receive the warning and >500 to presumably get an error

### Possible Solution

Implement custom resource limits for Nested Stacks

### CDK CLI Version

2.111.0

### Node.js Version

18.16.0

### OS

Ubuntu

### Language

TypeScript

**Comment by pahud** [comment]
We probably should fix the logic here

https://github.com/aws/aws-cdk/blame/1a586f2935764bce56c4658165291ffacde7e0b1/packages/aws-cdk-lib/core/lib/stack.ts#L39

https://github.com/aws/aws-cdk/blame/1a586f2935764bce56c4658165291ffacde7e0b1/packages/aws-cdk-lib/core/lib/stack.ts#L1445-L1448

Before that, I guess you can unblock it by setting the context variable described here:

https://github.com/aws/aws-cdk/blob/1a586f2935764bce56c4658165291ffacde7e0b1/packages/aws-cdk-lib/README.md?plain=1#L1240C13-L1240C13

**Comment by azhong-git** [comment]
Following the unblock advice from https://github.com/aws/aws-cdk/issues/28186#issuecomment-1832467229 to set ` "@aws-cdk/core:stackResourceLimit": 0` in cdk.json.

However I am seeing the following error. What is the actual maximum number of resources?

```
 [ValidationError]: Template format error: Number of resources, 502, is greater than maximum allowed, 500
```

**Comment by gnakohet** [comment]
Same here with @azhong-git 

I couldn't fix up that error even though I set "@aws-cdk/core:stackResourceLimit" in both cdk.json and value of -c option of cdk cli.

My solution was only separate one to two or stack having problem move into a stack as nested stack.

**Comment by TheRealAmazonKendra** [comment]
@scanlonp's assessment is correct here. Each stack, nested or otherwise, can only have up to 500 resources each. If you are performing some operation on the entire set of nested stacks within your stack hierarchy, you can perform that operation on up to 2500 resources at a time. 

So, you could have five stacks with 500 resources each in your stack hierarchy, or any other combination that is within that limit. See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-nested-stacks.html for more details.

**Comment by JoshMcCullough** [comment]
> I guess you can unblock it by setting the context variable described here:
> 
> https://github.com/aws/aws-cdk/blob/1a586f2935764bce56c4658165291ffacde7e0b1/packages/aws-cdk-lib/README.md?plain=1#L1240C13-L1240C13

This will get past the synth error, but once the CF changeset is being evaluated, CF will throw the same/similar message.
