### ISSUE TITLE
aws-batch: support runtimePlatform for EcsFargateContainerDefinition

### ISSUE THREAD

**Issue by chriskeyser** [aws/aws-cdk#28188]
### Describe the feature

Add runtimePlatform to EcsFargateContainerDefinition so an ARM platform can be specified. In order to use ARM I need to drop down to the low level construct, CfnJobDefinition.

### Use Case

We use golang and compile for ARM. ARM resources give us consistent compute (no hyperthreading) and is more economical.

### Proposed Solution

Add the `runtimePlatform` information to the higher level `EcsFargateContainerDefinition` construct.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

^2.97.0

### Environment details (OS name and version, etc.)

dev - mac/ventura, runtime: amazon linux 2 / arm

**Comment by khushail** [comment]
Hi @chriskeyser ,thanks for submitting this. There is [already a FR](https://github.com/aws/aws-cdk/issues/26484) for the same, so I am marking this as duplicate.

However, thanks for volunteering to contribute on this. Please feel free to work on this and team would be happy to review your PR.

**Comment by gracelu0** [comment]
Closing this issue as it is a duplicate and has been addressed by https://github.com/aws/aws-cdk/pull/28841.
