### ISSUE TITLE
aws-cdk-lib/aws-ecr: No option available in CDK to set EmptyOnDelete property for ECR repo

### ISSUE THREAD

**Issue by carlosahs** [aws/aws-cdk#28196]
### Describe the issue

AWS CloudFormation documentation states that [`AWS::ECR::Repository` resources have `EmptyOnDelete` property](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecr-repository.html#aws-resource-ecr-repository-properties), but it's not possible to set such property in CDK using [`Repository` construct](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ecr.Repository.html).

Is expected `EmptyOnDelete` property not to be set in CDK?

### Links

+ https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ecr.Repository.html
+ https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecr-repository.html#aws-resource-ecr-repository-properties

**Comment by markmansur** [comment]
You're right it is supported by CloudFormation. The `CfnRepository` L1 construct supports `emptyOnDelete` as optional, with the default being `false`. See here: https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ecr.CfnRepository.html#emptyondelete

Should be a fairly straight forward change here: https://github.com/aws/aws-cdk/blob/116b93324f5c2d961ed222c659b1b35ec71c57c7/packages/aws-cdk-lib/aws-ecr/lib/repository.ts#L701C16-L701C16

Do you want to submit a PR? If not I can work on it

**Comment by khushail** [comment]
@carlosahs ,thanks for submitting this request.
@markmansur , as its supported by [Cloudformation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecr-repository.html#aws-resource-ecr-repository-properties) and [L1 construct](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ecr.CfnRepository.html#emptyondelete), it should be implementable. Contributions from community are welcome.

**Comment by markmansur** [comment]
Thanks @khushail 

What do you recommend we do with the autoDeleteImages custom resource? It doesn't make sense for both to co-exist IMO.
