### ISSUE TITLE
(aws-ecs): AsgCapacityProvider and AsgCapacityProviderProps should expose InstanceWarmupPeriod

### ISSUE THREAD

**Issue by jeffb4** [aws/aws-cdk#28190]
### Describe the feature

`aws-ecs.AsgCapacityProviderProps` should expose the [InstanceWarmupPeriod](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-capacityprovider-managedscaling.html#cfn-ecs-capacityprovider-managedscaling-instancewarmupperiod) property from the L1 provider

### Use Case

Allowing this configuration of the underlying `CfnCapacityProvider` L1 object would allow CDK users defining ECS clusters to effectively lower or raise the expected time for instances to become available, without delving into the L1 object themselves.

### Other Information

In the alternate, a user can specify their own L1 `CfnCapacityProvider` instead of using `AsgCapacityProvider`

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

v2.99.1

### Environment details (OS name and version, etc.)

MacOS 14.1.1

**Comment by khushail** [comment]
thanks @jeffb4 for submitting this. Contributions are welcome from the community.

**Comment by msambol** [comment]
I'll take this.
