### ISSUE TITLE
aws_elasticloadbalancingv2: Support MutualAuthentication on ApplicationListener

### ISSUE THREAD

**Issue by TirTech** [aws/aws-cdk#28206]
### Describe the feature

Support [was recently added](https://aws.amazon.com/about-aws/whats-new/2023/11/application-load-balancer-authenticate-x509-certificate-based-identities/) on AWS::ElasticLoadBalancingV2::Listener to support mTLS X.509 certificate validation through the MutualAuthentication property. I'd like to see it added to the L1 (and if possible L2) ApplicationListener constructs and helper methods (like add_listener).

### Use Case

We would like to shift some applications to using mTLS when communicating with services behind an ALB.

### Other Information

The new mTLS support came with the addition of AWS::ElasticLoadBalancingV2::TrustStoreRevocation and AWS::ElasticLoadBalancingV2::TrustStore in cloudformation, which would also need to be added as their L1 constructs appear to be missing.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.91.0

### Environment details (OS name and version, etc.)

Ubuntu 22.04.3 LTS on Windows 10 x86_64, python 3.10

**Comment by msambol** [comment]
I can take this but I don't see it in the [CFN spec](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html) just yet? I see hints of it in the documentation but the links are null pointers.

**Comment by TirTech** [comment]
For now we have worked around it by applying overrides and creating the trust store using CfnResource (based on [these doc pages](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticloadbalancingv2-listener-mutualauthentication.html)):
```python
trust_store = CfnResource(
    self,
    "ALBTrustStore",
    type="AWS::ElasticLoadBalancingV2::TrustStore",
    properties={
        "CaCertificatesBundleS3Bucket": "alb-trust-store-bucket",
        "CaCertificatesBundleS3Key": "ca.pem",
        "Name": "ALBTrustStore",
    },
)

balancer = aws_elasticloadbalancingv2.ApplicationLoadBalancer(...) # snipped for brevity
listener = balancer.add_listener(...) # snipped for brevity

cfn: CfnResource = listener.node.default_child
cfn.add_property_override("MutualAuthentication.IgnoreClientCertificateExpiry", False)
cfn.add_property_override("MutualAuthentication.Mode", "verify")
cfn.add_property_override("MutualAuthentication.TrustStoreArn", trust_store.get_att("TrustStoreArn"))
```
This seems to deploy and work fine in us-east-1 at least, so it can be used till the CFN spec has the resources added.

**Comment by khushail** [comment]
@TirTech , this needs to be supported by Cloudformation. You could add this request on [Cloudformation coverage roadmap](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues) and follow up for updates.

**Comment by zensolution** [comment]
Is AWS CDK L2 support for this feature planned?

**Comment by nomike** [comment]
I would like to see L2 support for this as well.

It is currently the only method of achieving MTLS support and having static IPs (by putting a global accelerator in front of it). Something which can't be done with API Gateway (the other AWS component which supports MTLS).

At the moment we terminate TLS endpoints with that requirement on EC2 instances running a third-party software by putting an NLB in front of them, which is unsatisfactory on multiple levels.

**Comment by pepastach** [comment]
@msambol There are now L1 constructs for [TrustStore](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_elasticloadbalancingv2.CfnTrustStore.html) and [CfnTrustStoreRevocation](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_elasticloadbalancingv2.CfnTrustStoreRevocation.html).

**Comment by mazyu36** [comment]
Hi.
Is anyone working on this issue?
If not, I’ll take it.​​​​​​​​​​​​​​​​

**Comment by mazyu36** [comment]
I'm working on it.
