### ISSUE TITLE
aws_ec2: Parameter cpu_type ignored when calling ec2.MachineImage.latest_amazon_linux2023()

### ISSUE THREAD

**Issue by jedreky** [aws/aws-cdk#28201]
### Describe the bug

I am using AWS CDK in Python. I want to get the latest Amazon Linux AMI for either x86 or arm architecture, to do this I call:
```
ec2.MachineImage.latest_amazon_linux2023(cpu_type=ec2.AmazonLinuxCpuType.X86_64).ssm_parameter_name()
ec2.MachineImage.latest_amazon_linux2023(cpu_type=ec2.AmazonLinuxCpuType.ARM_64).ssm_parameter_name()
```

### Expected Behavior

I would expect to get two different outputs.

### Current Behavior

In both cases I get:
```
'/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64'
```

### Reproduction Steps

```
import aws_cdk.aws_ec2 as ec2
print(ec2.MachineImage.latest_amazon_linux2023(cpu_type=ec2.AmazonLinuxCpuType.X86_64).ssm_parameter_name())
print(ec2.MachineImage.latest_amazon_linux2023(cpu_type=ec2.AmazonLinuxCpuType.ARM_64).ssm_parameter_name())
```

### CDK CLI Version

2.109.0 (build 941dc16)

### Node.js Version

v20.5.1

### OS

Linux

### Language

Python

### Language Version

3.11.1

**Comment by khushail** [comment]
Hi @jedreky, thanks for reporting this

**Comment by jedreky** [comment]
hey Luca, the first method works, thanks a lot :)
