### ISSUE TITLE
aws-cdk: CdkJsonStringify and AWSCDKCfnUtilsProviderCustomResourceProvider are not available in node children

### ISSUE THREAD

**Issue by marcin-cto** [aws/aws-cdk#28215]
### Describe the bug

I've educated myself that CDK supports passing only simple types, when I execute the code below a new custom resource is created just for handling an array returned by `vpc_endpoint.vpc_endpoint_network_interface_ids`.

This is the code that I use.
```python 
        vpc_endpoint = vpc.add_interface_endpoint(
            'api-gateway-vpce', service=ec2.InterfaceVpcEndpointAwsService.APIGATEWAY
        )

        custom_resources.AwsCustomResource(
            self, 'endpoint-ips',
            on_update=custom_resources.AwsSdkCall(
                action='describeNetworkInterfaces',
                service='EC2',
                parameters={
                    'NetworkInterfaceIds':vpc_endpoint.vpc_endpoint_network_interface_ids
                },
                physical_resource_id=custom_resources.PhysicalResourceId.of(get_resource_prefix('endpoint-nics')),
            ),
            policy=custom_resources.AwsCustomResourcePolicy.from_sdk_calls(
                resources=custom_resources.AwsCustomResourcePolicy.ANY_RESOURCE
            )
        )
 ```

This is an additional custom resource that is produced by cdk and doesn't exist in the children structure:

```json
    "AWSCDKCfnUtilsProviderCustomResourceProviderHandlerCF82AA57": {
      "Type": "AWS::Lambda::Function",
      "Properties": {
        "Code": {
          "S3Bucket": "***",
          "S3Key": "***"
        },
        "Timeout": 900,
        "MemorySize": 128,
        "Handler": "__entrypoint__.handler",
        "Role": {
          "Fn::GetAtt": [
            "AWSCDKCfnUtilsProviderCustomResourceProviderRoleFE0EE867",
            "Arn"
          ]
        },
        "Runtime": "nodejs18.x"
      },
      "DependsOn": [
        "AWSCDKCfnUtilsProviderCustomResourceProviderRoleFE0EE867"
      ],
      "Metadata": {
        "aws:cdk:path": "***",
        "aws:asset:path": "***",
        "aws:asset:property": "Code"
      }
    },
    "CdkJsonStringify2": {
      "Type": "Custom::AWSCDKCfnJsonStringify",
      "Properties": {
        "ServiceToken": {
          "Fn::GetAtt": [
            "AWSCDKCfnUtilsProviderCustomResourceProviderHandlerCF82AA57",
            "Arn"
          ]
        },
        "Value": {
          "Fn::GetAtt": [
            "essvpcessapigatewayvpce16FC46B0",
            "NetworkInterfaceIds"
          ]
        }
      },
      "UpdateReplacePolicy": "Delete",
      "DeletionPolicy": "Delete",
      "Metadata": {
        "aws:cdk:path": "***"
      }
    }
  }
```

### Expected Behavior

I expected `Custom::AWSCDKCfnJsonStringify` to be found in the node structure.

### Current Behavior

The problem I have is `Custom::AWSCDKCfnJsonStringify` cannot be found in node children. It looks like it is added when python execution ends. What I want to do is to add a condition to `Custom::AWSCDKCfnJsonStringify` as I create `essvpcessapigatewayvpce16FC46B0` conditionally based on input parameters. As follows:

```python
vpc_endpoint.node.default_child.cfn_options.condition = my_condition
```

How can I access `Custom::AWSCDKCfnJsonStringify` in python to add my modifications?

### Reproduction Steps

''

### CDK CLI Version

2.111.0

### Node.js Version

v18.18.2

### OS

Mac OS

### Language

Python

**Comment by marcin-cto** [comment]
I create a vpc endpoint only when the `installation_type` input parameter is `private`. Otherwise, when `public` installation type is chosen is fails as it cannot find `essvpcessapigatewayvpce16FC46B0`. I need to add there a cloudformation condition that creates that custom resource only when then the input parameter is `private`.

**Comment by FarrOut** [comment]
one use-case is being able to define a custom name for the handler's role i.e. ```AWSCDKCfnUtilsProviderCustomResourceProviderRoleFE0EE867```

**Comment by pahud** [comment]
Closing this issue now. Feel free to reopen if it's still relevant.

**Comment by imduchy** [comment]
@pahud in an enterprise environment where developers are required to create IAM roles with paths and permissions boundaries, this becomes a blocker. Because the `AWSCDKCfnJsonStringify` and the underlying IAM role are not present during the preparation phase, and can't be modified using e.g., Aspects, the only working solution we've found is `iam.Role.customize_roles` (as mentioned above).

However, using `iam.Role.customize_roles` is not recommended, and not practical because it forces you to pre-create all IAM roles.

I believe there's a good reason to generate the resources after the preparation phase—after CDK Aspects finished the execution—but I also believe there should be a way to make it easier for enterprise customers to configure the roles to be created with paths and/or permissions boundaries.

**Comment by danilodesolesonar** [comment]
hi @pahud can this be re-open? I believe many developer need to customise the role created by the `AWSCDKCfnJsonStringify` custom resource. The custom resource creates a role that cannot be modified by Aspects.
