### ISSUE TITLE
Vpc: Error when running with FIPS endpoint enabled

### ISSUE THREAD

**Issue by omriman12** [aws/aws-cdk#28238]
### Describe the bug

Deploying a stack with a Vpc construct while `AWS_USE_FIPS_ENDPOINT=true` fails with an error:

"Inaccessible host: `ec2-fips.us-gov-west-1.amazonaws.com' at port `undefined'. This service may not be available in the `us-gov-west-1' region.: getaddrinfo ENOTFOUND ec2-fips.us-gov-west-1.amazonaws.com"

Running with `AWS_ENDPOINT_URL_EC2=https://ec2.{region_name}.amazonaws.com`  doesn't help!

### Expected Behavior

Stack should be deployed using FIPS endpoints

### Current Behavior

Error in synth process

### Reproduction Steps

**AWS_USE_FIPS_ENDPOINT=true cdk deploy**

**Stack code in python:**
```

import aws_cdk as cdk
import boto3
from boto3 import session
from constructs import Construct
from aws_cdk.aws_ec2 import Vpc


class TestStack(cdk.Stack):

    def __init__(self, scope: Construct, _id: str, **kwargs) -> None:
        region = session.Session().region_name
        account_id = boto3.client('sts').get_caller_identity().get('Account')
        super().__init__(scope=scope, id=_id, env=cdk.Environment(account=account_id, region=region))

        Vpc(
            self,
            'Vpc',
        )


app = cdk.App()
stack = TestStack(app, "TestStack")
app.synth()
```

### CDK CLI Version

2.113.0 (build ccd534a)

### Node.js Version

v18.1.0

### OS

MacOS

### Language

Python

### Language Version

Python 3.8.15

**Comment by khushail** [comment]
Hi @omriman12 , thanks for reporting this. This issue has been reported earlier and we have internal investigation going on through internal ticket -P106273204.  Will keep posting updates here.
