### ISSUE TITLE
aws-lambda: `currentVersion` Version already exists

### ISSUE THREAD

**Issue by yellowmamba** [aws/aws-cdk#28252]
### Describe the bug

Upgraded `aws-cdk-lib` to `2.113.0`. Now `AWS::Lambda::Version` will throw this error when the current version already exists.

### Expected Behavior

Deployment should succeed like before.

### Current Behavior

Throw this error when trying to update the lambda version
```
Resource handler returned message: "Version already exists: [my-lambda-version-arn]. Please modify the function to create a new version. (Service: Lambda, Status Code: 409)"
```

### Reproduction Steps

Make sure `aws-cdk-lib` is at `2.113.0`.

```
const lambda = new NodejsFunction(this, "lambda", {...})

const lambdaAlias = new Alias(this, "LambdaAlias", {
  aliasName: "prod",
  version: lambda.currentVersion, // this seems to be the problem
})

myApi.addRoutes({
  integration: new HttpLambdaIntegration("id", lambdaAlias),
  path: "/url",
})
```

### Additional Information/Context

- We try to upgrade`aws-cdk-lib` from `2.84.0` to `2.113.0`
- We replaced `@aws-cdk/aws-apigatewayv2-integrations-alpha` with `aws-cdk-lib/aws-apigatewayv2-integrations` for `HttpLambdaIntegration` because it'd been GA and alpha has now been deprecated.

### CDK CLI Version

2.113.0

### Node.js Version

v18.17.1

### OS

macOS 14.1.1

### Language

TypeScript

### Language Version

5.1.6

**Comment by pahud** [comment]
could relate to https://github.com/aws/aws-cdk/issues/27884

```ts
const lambdaAlias = new Alias(this, "LambdaAlias", {
  aliasName: "prod",
  version: lambda.currentVersion, // this seems to be the problem
})
```

Have you tried `function.addAlias()` to create the alias instead which was introduced in https://github.com/aws/aws-cdk/pull/20034

**Comment by yellowmamba** [comment]
@pahud it worked today with the code unchanged. I think there's some weirdness with the underlying Lambda api. A colleague was also able to reproduce this intermittent error.

**Comment by yellowmamba** [comment]
Hi @pahud , has there been an update on this issue?

**Comment by pahud** [comment]
No. Did you mean the code below deployed in 2.84.0 will fail when you upgrade to 2.113.0 ?


```ts
const lambda = new NodejsFunction(this, "lambda", {...})

const lambdaAlias = new Alias(this, "LambdaAlias", {
  aliasName: "prod",
  version: lambda.currentVersion, // this seems to be the problem
})

myApi.addRoutes({
  integration: new HttpLambdaIntegration("id", lambdaAlias),
  path: "/url",
})
```

I just tested the simplified sample below. Deployed in `2.84.0`

```ts
export class DemoStack extends MyStack {
  constructor(scope: Construct, id: string, props: StackProps) {
    super(scope, id, props);

    const fn = getLambdaFunction(this); // return a dummy lambda func

    new lambda.Alias(this, "LambdaAlias", {
      aliasName: "prod",
      version: fn.currentVersion, // this seems to be the problem
    })
  }
}
```

Then, upgrade to `2.113.0`. Run `cdk diff`, I didn't see any difference.

Now, I updated the lambda code and run `cdk diff` again. I saw below:

```
Resources
[-] AWS::Lambda::Version Func/CurrentVersion FuncCurrentVersion348374EF7ba836ac0b5250e9b7fd41805d4a042a destroy
[+] AWS::Lambda::Version Func/CurrentVersion FuncCurrentVersion348374EFf8af8e354054f8991a63e3b66f5c1d16 
[~] AWS::Lambda::Function Func Func217E03A4 
 └─ [~] Code
     └─ [~] .ZipFile:
         ├─ [-] def handler(_, _): return {"foo": "bar"}
         └─ [+] def handler(_, _): return {"foo": "bar"} 
[~] AWS::Lambda::Alias LambdaAlias LambdaAlias9C15A666 
 └─ [~] FunctionVersion
     └─ [~] .Fn::GetAtt:
         └─ @@ -1,4 +1,4 @@
            [ ] [
            [-]   "FuncCurrentVersion348374EF7ba836ac0b5250e9b7fd41805d4a042a",
            [+]   "FuncCurrentVersion348374EFf8af8e354054f8991a63e3b66f5c1d16",
            [ ]   "Version"
            [ ] ]
```

And then I run `cdk deploy` to get it deployed. It works great with no error messages.
