### ISSUE TITLE
aws-secretsmanager: Cannot set rotation schedule to be less than a day

### ISSUE THREAD

**Issue by wmattei** [aws/aws-cdk#28261]
### Describe the bug

AWS [secrets manager documentation](https://docs.aws.amazon.com/secretsmanager/latest/userguide/rotate-secrets_managed.html), says that "You can rotate a secret as often as every four hours". However if I want to do something like:

```typescript
    new Secret(this, 'my-secret').addRotationSchedule('my-secret-rotation-schedule', {
        rotationLambda: myLambdaFunction,
        automaticallyAfter: Duration.hours(4),
    })
```

I will get the following error:

```
Error: '4 hours' cannot be converted into a whole number of days.
    at convert (/Users/wmattei/www/peek/peek-iac/node_modules/aws-cdk-lib/core/lib/duration.js:1:6197)
    at Duration.toDays (/Users/wmattei/www/peek/peek-iac/node_modules/aws-cdk-lib/core/lib/duration.js:1:3641)
    at new RotationSchedule (/Users/wmattei/www/peek/peek-iac/node_modules/aws-cdk-lib/aws-secretsmanager/lib/rotation-schedule.js:1:2264)
    at Secret.addRotationSchedule (/Users/wmattei/www/peek/peek-iac/node_modules/aws-cdk-lib/aws-secretsmanager/lib/secret.js:1:4727)
```

### Expected Behavior

I would expect CDK to allow me to create schedules for 4 hours, as described in the documention.

### Current Behavior

I can only rotation schedules for the minimum of 1 day.

### Reproduction Steps

Try to synth this stack:

```typescript
import { App, Stack, Duration } from "aws-cdk-lib";
import { Secret } from "aws-cdk-lib/aws-secretsmanager";
import { NodejsFunction } from "aws-cdk-lib/aws-lambda-nodejs";
export class MyStack extends Stack {
  constructor() {
    const app = new App();

    super(app, "MyStack");

    const myLambdaFunction = new NodejsFunction(this, "my-lambda-function", {
      entry: "path/to/my/lambda",
    });

    new Secret(this, "my-secret").addRotationSchedule(
      "my-secret-rotation-schedule",
      {
        rotationLambda: myLambdaFunction,
        automaticallyAfter: Duration.hours(4),
      }
    );
  }
}

```

### Possible Solution

I suppose this is related to the fact that [when checking if the provided duration is greater than 1000 days](https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-secretsmanager/lib/rotation-schedule.ts#L130) we are directly calling `.toDays` which validates [wether the given value can be converted in a whole number of days](https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/core/lib/duration.ts#L329).

### CDK CLI Version

2.113.0 (build ccd534a)

### Node.js Version

v21.3.0

### OS

MacOs

### Language

TypeScript

### Language Version

Version 5.1.6

**Comment by pahud** [comment]
I guess this is because current implementation is to satisfy [AutomaticallyAfterDays](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-secretsmanager-rotationschedule-rotationrules.html#cfn-secretsmanager-rotationschedule-rotationrules-automaticallyafterdays) which the unit is day but it's still possible to implement it with `ScheduleExpression`.

https://github.com/aws/aws-cdk/blob/89f98030d103241ab19fa430936df04d848b7ef8/packages/aws-cdk-lib/aws-secretsmanager/lib/rotation-schedule.ts#L139-L141
