### ISSUE TITLE
aws-stepfunctions-tasks: Support for integration with Bedrock InvokeModel

### ISSUE THREAD

**Issue by clareliguori** [aws/aws-cdk#28268]
### Describe the feature

Step Functions recently released an optimized integration for Bedrock InvokeModel API:
https://aws.amazon.com/about-aws/whats-new/2023/11/aws-step-functions-optimized-integration-bedrock/
https://docs.aws.amazon.com/step-functions/latest/dg/connect-bedrock.html

### Use Case

The aws-stepfunctions-tasks now needs to support creating Bedrock InvokeModel tasks

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

N/A

### Environment details (OS name and version, etc.)

N/A

**Comment by khushail** [comment]
@clareliguori , thanks for submitting this request. would be good to have.
