### ISSUE TITLE
aws-ecs: Cluster.addAsgCapacityProvider blocks EC2 metadata in instances created by the ASG

### ISSUE THREAD

**Issue by Brads3290** [aws/aws-cdk#28270]
### Describe the bug

Calling `Cluster.addAsgCapacityProvider` modifies the AutoScalingGroup to add a userdata script to the launch template which blocks access to 169.254.169.254:
```
"MyEcsClusterAsgLaunchTemplate854B9AAD": {
   "Type": "AWS::EC2::LaunchTemplate",
   "Properties": {
    "LaunchTemplateData": {

     ...

     "UserData": {
      "Fn::Base64": {
       "Fn::Join": [
        "",
        [
         "#!/bin/bash\necho ECS_CLUSTER=",
         {
          "Ref": "MyEcsClusterACF79753"
         },
         " >> /etc/ecs/ecs.config\nsudo iptables --insert FORWARD 1 --in-interface docker+ --destination 169.254.169.254/32 --jump DROP\nsudo service iptables save\necho ECS_AWSVPC_BLOCK_IMDS=true >> /etc/ecs/ecs.config"
        ]
       ]
      }
     }
    },
    
    ...
}
```

In particular: `sudo iptables --insert FORWARD 1 --in-interface docker+ --destination 169.254.169.254/32 --jump DROP`

Without the call to `Cluster.addAsgCapacityProvider` (and possibly other methods do this too), this isn't added.

This behaviour isn't documented anywhere that I can find, and causes the error `No RegionEndpoint or ServiceURL configured` from the SDK when using the default settings and expecting everything to be picked up from the environment (which is how it seems to work when creating the cluster from the console).

### Expected Behavior

Don't block access to EC2 metadata, or at least clearly document it and offer alternatives if someone wants to make use of the TaskRole inside the container

### Current Behavior

The EC2 metadata endpoint is blocked using `sudo iptables --insert FORWARD 1 --in-interface docker+ --destination 169.254.169.254/32 --jump DROP`

### Reproduction Steps

```csharp
var app = new App();
var stack = new Stack(app, "ReproStack", new StackProps() {
    Env = new Amazon.CDK.Environment {
        Account = System.Environment.GetEnvironmentVariable("CDK_DEFAULT_ACCOUNT"),
        Region = System.Environment.GetEnvironmentVariable("CDK_DEFAULT_REGION"),
    },
});

var defaultVpc = Vpc.FromLookup(stack, "defaultVpc", new VpcLookupOptions() {
    IsDefault = true,
});

var asg = new AutoScalingGroup(stack, "AutoScalingGroup", new AutoScalingGroupProps() {
    Vpc = defaultVpc,
    InstanceType = InstanceType.Of(InstanceClass.T3A, InstanceSize.SMALL),
    MachineImage = EcsOptimizedImage.AmazonLinux2(),
});

var cluster = new Cluster(stack, "Cluster", new ClusterProps() {
    Vpc = defaultVpc,
});

var provider = new AsgCapacityProvider(stack, "AsgCapacityProvider", new AsgCapacityProviderProps() {
    AutoScalingGroup = asg,
});

// With this line, the UserData is included in the ASG's launch template; without it, it is not
cluster.AddAsgCapacityProvider(provider);

app.Synth();
```

### Possible Solution

Don't block access to EC2 metadata, or at least clearly document it and offer alternatives if someone wants to make use of the TaskRole inside the container

### CDK CLI Version

2.114.0 (build 12879fa)

### Node.js Version

v18.16.1

### OS

MacOS 13.6.2

### Language

.NET

### Language Version

.NET 8

**Comment by Brads3290** [comment]
I tested this a bit further, looks like the task role still works with the SDK, it's just the region that is unable to be automatically determined.

I've updated my task definitions to set `AWS_REGION`, and everything works now.

It only became a big headache for me because I had my containers set up in a cluster that I created using the console, then I decided to move it into my CDK stack, and all of a sudden my containers were failing with `No RegionEndpoint or ServiceURL configured`.

**Comment by pahud** [comment]
https://github.com/aws/aws-cdk/blame/2d9de189e583186f2b77386ae4fcfff42c864568/packages/aws-cdk-lib/aws-ecs/lib/cluster.ts#L502-L504

I think your taskRole should work as expected if you provision your ecs cluster/service/task with CDK.  I can't find any relevant document about the blocking for the metadata access but we need to be very careful if we remove it as it's been a stable module for a long time and this might cause additional issues or breaking changes.

Your `Reproduction Steps` look great to me and the task role should work as expected. Can you share more about your task definition and service running on this ASG and the error message you've seen with that?

**Comment by juinquok** [comment]
I had a similar issue recently whereby access to the instance metadata endpoint was failing resulting in aws-otel and aws-sdk throwing errors on container startup. I was similarly also able to resolve the issue by simply adding `AWS_REGION` to the container's environment as the only thing that the underlying deps could not source was the region information. 

The reason behind the iptables block is documented at: https://docs.aws.amazon.com/AmazonECS/latest/bestpracticesguide/security-iam-roles.html

May I suggest that we add in the `AWS_REGION` env variable as part of the `Cluster. addAsgCapacityProvider` method? @pahud I can raise a PR for this

**Comment by Brads3290** [comment]
@pahud @juinquok 

I also came across that page when I was debugging my issue and thought "well I haven't done that, so that can't be the problem". I think it needs to be documented on the CDK side, that the `addAsgCapacityProvider` does this (along with any other methods / properties that cause this behaviour).
