### ISSUE TITLE
(ECS.LogsDrivers): Resolution error when using ecs.LogDrivers.firelens secretOptions

### ISSUE THREAD

**Issue by lockenj** [aws/aws-cdk#28279]
### Describe the bug

I get a Resolution Error when trying to synthesize ` 

### Expected Behavior

If I retrieve my Datadog API Key secret and attempt to use secretOptions like the simplified snippet below I get `Resolution error: Trying to resolve a non-data object. Only token are supported for lazy evaluation`. 

```
const dataDogApiKeySecret = secretsmanager.Secret.fromSecretNameV2(this, 'DataDogApiKeySecret', this.#_dataDogApiKeySecretName);
...
this.#_taskDefinition.addContainer('Server', {
      ...
      logging: ecs.LogDrivers.firelens({
        options: {
          ...
          secretOptions: {
            apikey: ecs.Secret.fromSecretsManager(dataDogApiKeySecret)
          }
        }
      })
      ...deltaServerContainer
});
```

### Current Behavior

Error: Resolution error: Resolution error: Resolution error: Trying to resolve a non-data object. Only token are supported for lazy evaluation. Path: /Resources/${Token[DeltaServerStack.DeltaServer.TaskDefinition.Resource.LogicalID.498]}/Properties/containerDefinitions/2/logConfiguration/options/secretOptions/apikey/grantRead. Object: grantee=>secret.grantRead(grantee).

### Reproduction Steps

See snippet above... Just running cdk synth or cdk deploy gives the error

### CDK CLI Version

2.114.1

### Node.js Version

v20.7.0

### OS

MAC 13.4.1

### Language

TypeScript

**Comment by pahud** [comment]
I just tried the code below and I can successfully synth and deploy with no errors.

```ts
export class Demo extends DemoStack {
	constructor(scope: Construct, id: string, props: StackProps) {
		super(scope, id, props);

		const task = new ecs.Ec2TaskDefinition(this, 'Task');
		const dataDogApiKeySecret = secretsmanager.Secret.fromSecretNameV2(this, 'DataDogApiKeySecret', 'dummyName');
		task.addContainer('Server', {
			image: ecs.ContainerImage.fromRegistry('nginx'),
			memoryLimitMiB: 512,
			cpu: 1,
			logging: ecs.LogDrivers.firelens({
				options: {
					Name: 'firehose',
					region: 'us-east-1',
					delivery_stream: 'my-stream',
				},
				secretOptions: {
					apikey: ecs.Secret.fromSecretsManager(dataDogApiKeySecret)
				}
			})
		});
	}	
}
```

As I can't see your full code, I am not sure if it's a bug but it works to me with the code above. Can you simplify your code and see if it works with the latest cdk release?

**Comment by lockenj** [comment]
I was playing with simplifying things yesterday. Once I narrow it down to exactly what's causing the issue I will share a snippet. Thanks for your help on this!
