### ISSUE TITLE
(CDK Tags): Tags are not being suppressed when using Tags.of(SCOPE).remove() or Tags.of(SCOPE).add() 

### ISSUE THREAD

**Issue by aashishgk7760** [aws/aws-cdk#28290]
### Describe the bug

I am trying to tag only Clouformation stack and exclude the few resources from the Tag as shown Below 

```
export class Stack5 extends cdk.Stack {
    public readonly cluster : eks.Cluster;
    constructor(scope: Construct, id: string, props:cdk.StackProps) {
      super(scope, id, props);

      const toci = new sns.Topic(this, 'toci', {
        displayName: "toci",
        topicName: "wefwew"
      });

      const buc = new s3.Bucket(this, 'fwefwefwefw', {})
      cdk.Tags.of(buc).add('Name','asfafasfaeqef',{
       
      })
```

```
const stack5 = new Stack5(app, 'stack555', {
  env: envUSA1,
});
cdk.Tags.of(stack5).add('profile','IaC',{
  excludeResourceTypes: ['AWS::S3::Bucket']
})

```

When I am trying to exclude the resource type `AWS::S3::Bucket` as above , tag is being propagated to both Cloudformation stack and Resource. Also there there are 4 auto tags with name` aws:cloudformation:stack-name`  `aws:cloudformation:stack-id`  `aws:cloudformation:logical-id` and `Name` being added to resource under the stack but I was not able to remove them using the remove method. We need a clarification , what's the behaviour of this auto- tags on whether can this removed if required. 

### Expected Behavior

Expected behavior should be that from the above example the tag named `profile` should be added to only stack but the S3 resource

### Current Behavior

Tags are being propagated even after explicitly removing the resource type as shown above 

### Reproduction Steps

```
export class Stack5 extends cdk.Stack {
    constructor(scope: Construct, id: string, props:cdk.StackProps) {
      super(scope, id, props);

      const toci = new sns.Topic(this, 'toci', {
        displayName: "toci",
        topicName: "wefwew"
      });

      const buc = new s3.Bucket(this, 'fwefwefwefw', {})
      cdk.Tags.of(buc).add('Name','asfafasfaeqef',{
       
      })
```

```
const stack5 = new Stack5(app, 'stack555', {
  env: envUSA1,
});
cdk.Tags.of(stack5).add('profile','IaC',{
  excludeResourceTypes: ['AWS::S3::Bucket']
})

```

Step1: Create a CFN Stack with the code snippet above
Step2: observe that tag name profile is being propagated to both S3 Bucket and Cloudformation stack

### Possible Solution

https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/core/lib/tag-aspect.ts

### CDK CLI Version

2.114.1 (build 02bbb1d)

### Node.js Version

v20.5.1

### OS

13.6.1 (22G313)

### Language

TypeScript

### Language Version

Version 4.9.5

**Comment by pahud** [comment]
```ts
export class Stack5 extends Stack {
  constructor(scope: Construct, id: string, props: StackProps) {
    super(scope, id, props);

    new sns.Topic(this, 'toci', {
      displayName: "toci",
      topicName: "wefwew"
    });

    const buc = new s3.Bucket(this, 'fwefwefwefw', {})
    Tags.of(buc).add('Name','asfafasfaeqef',{});
  }
}

const stack5 = new Stack5(app, 'Stack5', { env });
cdk.Tags.of(stack5).add('profile','IaC',{
  excludeResourceTypes: ['AWS::S3::Bucket']
})

```

The provided code indicates 

1. that the bucket would have the tag key `Name` with value `asfafasfaeqef`
2. all taggable resources within this stack should have key `profile` with value `IaC` except for the bucket resource

Given this, the topic resource should have `profile` but no `Name`.

Checking the synthesized template:


```
   "Type": "AWS::SNS::Topic",
   "Properties": {
    "DisplayName": "toci",
    "Tags": [
     {
      "Key": "profile",
      "Value": "IaC"
     }
    ],
```

```
   "Type": "AWS::S3::Bucket",
   "Properties": {
    "Tags": [
     {
      "Key": "Name",
      "Value": "asfafasfaeqef"
     }
```

It is expected.

Did you see anything unexpected from the synthesized JSON template in `cdk.out`?

The tags with `aws:` prefix are auto generated by cloudformation([doc](https://docs.aws.amazon.com/tag-editor/latest/userguide/tagging.html)) and you can't edit or delete them.
