### ISSUE TITLE
(cfnspec): Has cfnspec been deprecated/replaced by aws-service-spec?

### ISSUE THREAD

**Issue by frankpengau** [aws/aws-cdk#28301]
### Describe the issue

Recently, I've been trying to debug some issues with jest assertions of aws-cdk constructs, when moving from aws-cdk/aws-cdk-lib v2.99.1 to v2.100.0+ , where it no longer detects the base class of the construct that I am trying to extend from (e.g. `aws-cdk-lib/aws-route53/RecordTarget`, `aws-cdk-lib/CustomResource`), in order to create my new custom construct (e.g. `AutoConfigReccordTarget`, `AutoConfigCustomResource`)

I have noticed that `cfnspec` in aws-cdk seems to show a README that it has been replaced by `aws-service-spec`, see here: https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/cfnspec/README.md

Which notes the following:
> This package has been replaced by a more modern version.
Please use `@aws-cdk/aws-service-spec` ([source](https://github.com/cdklabs/awscdk-service-spec)) instead.

Is this documentation accurate? If so, it would be preferable that it has a warn for a deprecation notice, during npm package install?

If not, then can you please inform me of what it would be? As I do see that alpha version packages are still being released as recent as last month: https://www.npmjs.com/package/@aws-cdk/cfnspec?activeTab=versions

### Links

https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/cfnspec/README.md

**Comment by frankpengau** [comment]
The PR in question that seems to have put the README notice up for it: https://github.com/aws/aws-cdk/pull/27858

**Comment by pahud** [comment]
Following up this issue - aws-service-spec is now used as the CFN schema source rather than cfnspec. I think relevant document has been updated. Let me know if there's any further concern.

**Comment by frankpengau** [comment]
It was a bit unclear at the time, but looks to be that way now.

Thank you for confirming!

I still think deprecation notice would be nice, especially for npm package installs but just a minor suggestion.

Happy to close off the issue.
