### ISSUE TITLE
Tracking: [service] No module named 'psycopg2._psycopg'

### ISSUE THREAD

**Issue by bkrishnaiah** [aws/aws-cdk#28347]
### Overview

Hi,

I am trying to create a lambda function where I can have Postgres DB connection with AWS RDS. I am using the tech stack as python and aws cdk.

I have installed psycopg2-binary library to enable the DB connection. I have deployed this lambda function to AWS environment. But while testing the lambda in AWS console, I am getting below error. 

Could someone help me on this. Thanks in advance..!!!

### Link to the service’s CDK Construct Library API reference page.

NA

### Maturity: CloudFormation Resources Only

CloudFormation Resources Only

### Implementation

> pip install -t "my_dir" "psycopg2-binary"

my “test_db.py” looks like below and the db connection values used as per my requirement.

import psycopg2

connection = psycopg2.connect(
host=db_host,
user=user_name,
password=user_password,
database=dbname
)

### Issue list

Issues:  1

{
"errorMessage": "Unable to import module 'testdb': No module named 'psycopg2._psycopg'",
"errorType": "Runtime.ImportModuleError",
"requestId": "593f9067-he23-4a54-b7773-39acdb2cd723",
"stackTrace": []
}

**Comment by ashishdhingra** [comment]
@bkrishnaiah Good morning. I'm not sure why `management/tracking` label was added, could you please confirm if this is still an issue?

Thanks,
Ashish

**Comment by santoshshinde2012** [comment]
Any specific solution to fix this issue?
