### ISSUE TITLE
aws_cdk.aws_ec2.InstanceType : Database instance type being synthesised into cloudformation incorrectly

### ISSUE THREAD

**Issue by dnrico1** [aws/aws-cdk#28355]
### Describe the bug

Defining ` instance_type=ec2.InstanceType("db.t4g.micro"),` for a aws_rds.DatabaseInstance synths to `"DBInstanceClass": "db.db.t4g.micro",` causing the following error when deploying:
`
Resource handler returned message: "Invalid DB Instance class: db.db.t4g.micro (Service: Rds, Status Code: 400, Request ID: xxx)" (RequestToken: xxx HandlerErrorCode: InvalidRequest)
`

### Expected Behavior

For the synth to be `"DBInstanceClass": "db.t4g.micro",` and the database to be created correctly

### Current Behavior

Synth was `"DBInstanceClass": "db.db.t4g.micro",` 

### Reproduction Steps

1. Init an cdk app
2. Put the following into app.py:
`
from aws_cdk import (
    aws_rds as rds,
    aws_ec2 as ec2,
)
import aws_cdk as cdk
from constructs import Construct

class StatefulStack(cdk.Stack):
    def __init__(self, scope: Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        # Define a VPC (minimal configuration for example purposes)
        vpc = ec2.Vpc(self, "MyVPC", max_azs=2)

        db_secret = rds.DatabaseSecret(self, "DBSecret",
            username="admin",
            secret_name="DBCredentials"
        )

        funnelsystems_database_name = "database"
        self.database = rds.DatabaseInstance(self, "database",
            engine=rds.DatabaseInstanceEngine.mysql(version=rds.MysqlEngineVersion.VER_8_0_28),
            instance_type=ec2.InstanceType("db.t4g.micro"),
            vpc=vpc,
            multi_az=False,
            allocated_storage=20, 
            database_name="name",
            publicly_accessible=False,
            credentials=rds.Credentials.from_secret(db_secret),
        
app = cdk.App()
StatefulStack(app, "StatefulStack")

app.synth()
`
3. Run `cdk synth`
4. Check the synthesised cloudformation and notice `DBInstanceClass: db.db.t4g.micro`

### Possible Solution

Unfortunately do not have enough experience with CDK / CFN to suggest a solution.

### CDK CLI Version

2.114.1 (build 02bbb1d)

### Node.js Version

Node.js v20.5.1

### OS

macOS Ventura 13.0

### Language

Python

**Comment by pahud** [comment]
@dnrico1 

You should remove the prefix `db.`, the DatabaseInstance() construct will handle the prefixing for you.

https://github.com/aws/aws-cdk/blob/b8b6bafc07b0804f6e802ba563ff3b7deaea6eee/packages/aws-cdk-lib/aws-docdb/lib/instance.ts#L213
