### ISSUE TITLE
aws-ec2: Security groups for interface VPC endpoints

### ISSUE THREAD

**Issue by azatoth** [aws/aws-cdk#28350]
### Describe the issue

In the README for EC2, under the section "Security groups for interface VPC endpoints", it states:

> By default, interface VPC endpoints create a new security group and traffic is not automatically allowed from the VPC CIDR.
> 
> Use the connections object to allow traffic to flow to the endpoint:
> ```ts
> declare const myEndpoint: ec2.InterfaceVpcEndpoint;
> 
> myEndpoint.connections.allowDefaultPortFromAnyIpv4();
> ```

In contrast, the `InterfaceVpcEndpoint` class does have a `open` property that is default true which states:

> Whether to automatically allow VPC traffic to the endpoint.
> 
> If enabled, all traffic to the endpoint from within the VPC will be automatically allowed. This is done based on the VPC's CIDR range.

### Links

- https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ec2-readme.html#security-groups-for-interface-vpc-endpoints
- https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ec2.InterfaceVpcEndpoint.html#open

**Comment by pahud** [comment]
https://github.com/aws/aws-cdk/blob/db22b85c9b2a853aa2f830c182a340f0bcf95d1a/packages/aws-cdk-lib/aws-ec2/lib/vpc-endpoint.ts#L718-L720

Yes you are right. And we should fix the document.

Are you interested to submit a PR for that?
