### ISSUE TITLE
aws-cloudfront: support KeyValueStore

### ISSUE THREAD

**Issue by epiphone** [aws/aws-cdk#28377]
### Describe the feature

Hi! Are there any plans of supporting the new Cloudfront [KeyValueStore](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/kvs-with-functions.html) feature in cdk?

### Use Case

I'd like to
1. create a key value store, and
2. associate the store with a function.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.115.0

### Environment details (OS name and version, etc.)

Ubuntu 22

**Comment by pahud** [comment]
This is awesome!

https://aws.amazon.com/blogs/aws/introducing-amazon-cloudfront-keyvaluestore-a-low-latency-datastore-for-cloudfront-functions/

CloudFormation support is coming soon. We definitely should support that when it arrives to cloudformation.

**Comment by robc79** [comment]
Hello. Do we know when support for this will be added to CloudFormation and CDK? Curious as I have a project at work that wants to use this feature. Thank you.

**Comment by kylelaker** [comment]
I see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudfront-keyvaluestore.html is now documented; I can go ahead and take an initial stab at this if community contributions are something the team is interested in for this construct.

**Comment by kylelaker** [comment]
Okay so I went ahead and got started in https://github.com/aws/aws-cdk/pull/28473; however, I am concerned about the usability of the construct. Reviewing the CloudFormation documentation and resource specification, it seems that at the moment CloudFormation doesn't actually support associating the Key Value Store with a function (in either direction). This means users would either need to do this manually or the user/library would need a custom resource.

@pahud is there any way to get an indication of whether there will be CloudFormation support for the associations? It seems silly for the library to go through the effort to create a custom resource to do so if it'll be supported natively in a couple revisions of the spec.

**Comment by pahud** [comment]
Yes looks like this resource is missing a functionArn property or maybe a new association resource. I will cut an internal ticket to relevant team to clarify but I can't guarantee the response. I would recommend to create an issue to https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues as well and link it back to this issue for more community visibility.

**Comment by pahud** [comment]
ticket ID V1175345449
