### ISSUE TITLE
(aws-ecs-patterns): Integration testing of aws-ecs-patterns contains an invalid integration test

### ISSUE THREAD

**Issue by AnuragMohapatra** [aws/aws-cdk#28383]
### Describe the bug

The integration testing of the aws-ecs-patterns has an invalid docker being used,

1. When executed the container state always fails with the following message - 
![image](https://github.com/aws/aws-cdk/assets/8456793/72d48d39-034f-4200-960a-33afcb9fc91f)

2. Looking at the docker and python file it never creates a webserver so the test on this location(https://github.com/aws/aws-cdk/blob/7c62d6809cbdeee251c8ff31e22db7d0ff85aba2/packages/%40aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.queue-processing-fargate-service-public.ts#L18) ideally should always fail as it asks the container to either respond with a localhost response which is not possible as there is no web server building in the docker image or give exit 1 which is exit with failure.

3. It is possible there are other issues with the integration testing but I have found these while working on the bug - #20706

### Expected Behavior

All integration tests should be perfectly aligned and work as expected.

### Current Behavior

Integration tests go into infinite loop until cloud formation tasks fail.

### Reproduction Steps

Create a new integration step using the QueueProcessingFargateService, using the same Docker and the index.py with no webserver and the docker should be using the CMD command.

### Possible Solution

1. Separate Docker file for separate fargate integration tests.
2. Queue processing is different from application load balancer.

### CDK CLI Version

NA

### Framework Version

2.115

### Node.js Version

NA

### OS

NA

### Language

TypeScript

**Comment by pahud** [comment]
Yes I see your point.

https://github.com/aws/aws-cdk/blob/7c62d6809cbdeee251c8ff31e22db7d0ff85aba2/packages/%40aws-cdk-testing/framework-integ/test/aws-ecs-patterns/test/fargate/integ.queue-processing-fargate-service-public.ts#L18

The `sqs-reader` is not actually listening on http port so the health check would always fail.

Are you interested to submit a PR for that?
