### ISSUE TITLE
AutoScalingGroup: LaunchTemplateOverrides is missing the InstanceRequirements Attribute in AWS CDK L2 construct

### ISSUE THREAD

**Issue by ayush-shah-1501** [aws/aws-cdk#28393]
### Describe the feature

The LaunchTemplateOverridesProperty is a crucial feature for our use case as it allows us to specify CPU, and memory configurations on a per-instance basis within the Auto Scaling Group and define spot and on-deamnd instances capcaity percentage. While this functionality is available in the L1 construct, it seems to be missing in the L2 construct.

### Use Case

We expect the L2 construct (AutoScalingGroup) to provide support for the LaunchTemplateOverridesProperty, enabling us to define specific configurations (such as min and max CPU and memory) and spot and on-demand capacity percentage within the Auto Scaling Group.

### Proposed Solution

We propose extending the L2 AutoScalingGroup construct to include support for the LaunchTemplateOverridesProperty or providing an alternative mechanism to achieve per-instance configuration within the Auto Scaling Group.

### Acknowledgements

- [x] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.100.0

### Environment details (OS name and version, etc.)

ubuntu

**Comment by lpizzinidev** [comment]
This feature is currently supported, you can use the [launchTemplateOverrides](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_autoscaling.MixedInstancesPolicy.html#launchtemplateoverrides) property.
Please take a look at the [docs](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_autoscaling.MixedInstancesPolicy.html#example) for an example implementation.

**Comment by ayush-shah-1501** [comment]
I don't want to specify multiple instances; I want to provide minimum and maximum values for CPU and memory, and based on that, all possible instances should be selected.

**Comment by lpizzinidev** [comment]
@ayush-shah-1501 
Thanks for the follow-up.
Basically [LaunchTemplateOverrides](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_autoscaling.LaunchTemplateOverrides.html) for L2 construct is missing the [InstanceRequirements](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-autoscaling-autoscalinggroup-launchtemplateoverrides.html#cfn-autoscaling-autoscalinggroup-launchtemplateoverrides-instancerequirements) attribute.

**Comment by khushail** [comment]
Thanks @ayush-shah-1501 for submitting this request. Community contributions are welcome in this regard.
