### ISSUE TITLE
aws-autoscaling: OnDemandAllocationStrategy enum does not support lowest-price

### ISSUE THREAD

**Issue by bwagner5** [aws/aws-cdk#28395]
### Describe the bug

AWS AutoScaling OnDemandAllocationStrategy enum for Mixed Instance Policy does not support `lowest-price`, only `prioritized`.   

ASG supports both: https://docs.aws.amazon.com/autoscaling/ec2/userguide/allocation-strategies.html#on-demand-allocation-strategy

### Expected Behavior

OnDemandAllocationStrategy should support both `prioritized` and `lowest-price`

### Current Behavior

OnDemandAllocationStrategy only supports `prioritized` and NOT `lowest-price`

### Reproduction Steps

https://github.com/aws/aws-cdk/blob/1a9c30e55e58203bd0a61de82711cf10f1e04851/packages/aws-cdk-lib/aws-autoscaling/lib/auto-scaling-group.ts#L423-L432

### Possible Solution

Add `lowest-price` enum

### CDK CLI Version

2.106.0

### Node.js Version

21.1.0

### OS

Mac M1 14.2

### Language

TypeScript

**Comment by pahud** [comment]
Awesome! Thank you for your PR!
