### ISSUE TITLE
(appconfig-alpha): (make content optional for hosted configuration)

### ISSUE THREAD

**Issue by morrijm4** [aws/aws-cdk#28390]
### Describe the feature

I would like to create a configuration profile without creating a hosted configuration version with it.

### Use Case

I would like to manage my configuration outside of my source control.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.115.0-alpha.0

### Environment details (OS name and version, etc.)

macOS Ventura 13.6.3

**Comment by pahud** [comment]
Thanks for your feature request. Can you share more info about current challenges and what CDK experience you'd like to have. Any code snippets would be highly welcome and appreciated.

**Comment by morrijm4** [comment]
> Thanks for your feature request. Can you share more info about current challenges and what CDK experience you'd like to have. Any code snippets would be highly welcome and appreciated.

Of course, thanks for the quick response!

I am trying to use the `@aws-cdk/app-config-alpha` module to create an application and a hosted configuration for each of my microservices along with multiple environments for them. I want this configuration to be separated from my codebase so it can be modified without needing to go through development cycles. From what I have read in the [documentation](https://docs.aws.amazon.com/cdk/api/v2/docs/@aws-cdk_aws-appconfig-alpha.HostedConfiguration.html#contentspan-classapi-icon-api-icon-experimental-titlethis-api-element-is-experimental-it-may-change-without-noticespan-1) the content property is required for the `HostedConfiguration` construct. From the [code](https://github.com/aws/aws-cdk/blob/21a0fa68c997cd1af4e30dac9aeb8e25eb1c68f6/packages/%40aws-cdk/aws-appconfig-alpha/lib/configuration.ts#L464C5-L472C8) I have read it seems you always want to create a new hosted configuration version.

Would it be possible to make the `content` property optional so, I can create a hosted configuration profile without needing to provide the configuration.

This would be super helpful thanks!

**Comment by pahud** [comment]
Unfortunately, the [content](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appconfig-hostedconfigurationversion.html#cfn-appconfig-hostedconfigurationversion-content) prop is required in cloudformation. CDK behind the scene has to pass that when it synthesize. Can you share some CDK example of your desired experience?
