### ISSUE TITLE
Doc: Create a shared stack and expose it via a CDK construct

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#284]
> For example, some users a central Cloud IT team define their network topology, which app developers need to plug into

I think we practically have all the building blocks to support this, and more and more I am realizing a lot of our work is going to be writing blog posts or HOW TOs that describe best practices and idioms.

In this particular case, the way this can be achieved is by using CloudFormation’s Import/Export mechanism. The Cloud IT team will define the shared network stack (using CDK or not) and export various parameters from it (say “PrivateSubnets”), then they can vend an internal CDK construct which will represent the shared stack, and encapsulate the Import statements, so developers that use this construct will have an experience such as:

```
const network = new AcmeSharedNetworkStack(this);
fleet.subnets = network.privateSubnets;
```

This will translate into an `{Fn::ImportValue}` under the hood.

**Comment by Jerry-AWS** [comment]
I've made a task for this in the CDK Guide topic. This can be closed.
