### ISSUE TITLE
aws-codebuild: CodeBuild lambda images/compute types missing from CDK

### ISSUE THREAD

**Issue by colyoonamaz** [aws/aws-cdk#28418]
### Describe the feature

Recently, CodeBuild released a new set of lambda images which can be found [here](https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-available.html) under `Lambda compute images`. Along with these new images, CodeBuild released new lambda compute types listed [here](https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-compute-types.html) as the BUILD_LAMBDA_1GB-10GB compute types. The CodeBuild CDK code should be updated to reflect these new images/compute types.

### Use Case

When trying to run lambda CodeBuild builds using CDK, the lambda project cannot be created as the relevant CDK values are missing.

### Proposed Solution

Create new ARM/Linux image files with the new lambda images and compute types

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

Any

### Environment details (OS name and version, etc.)

Any

**Comment by pahud** [comment]
Thank you for the feature request.
