### ISSUE TITLE
init templates: add cdk.out/ and .env/ (python only) to .gitignore

### ISSUE THREAD

**Issue by dhx-mike-palandra** [aws/aws-cdk#2842]
$ cdk --version
0.34.0 (build 523807c)

**Comment by bgdnlp** [comment]
For Python, I'd set:
```
cdk.out/

__pycache__/
*.py[cod]
*$py.class

.env
.venv
env/
venv/
ENV/
env.bak/
venv.bak/
```

Maybe vi backup and swap files, too.

There is a more complete [.gitignore from Github](https://github.com/github/gitignore/blob/master/Python.gitignore), but it looks too much.

**Comment by shivlaks** [comment]
@bgdnlp that seems like a reasonable starting point and I agree the example you linked does feel like overkill.
