### ISSUE TITLE
Amazon OpenSearch Service: High Level Constructs For OpenSearch IPAddressType Feature

### ISSUE THREAD

**Issue by vidit624** [aws/aws-cdk#28436]
### Describe the feature

The OpenSearch Team has recently launched IPAddressType Feature for OpenSearch Domain. [API Documentation Link](https://docs.aws.amazon.com/opensearch-service/latest/APIReference/API_CreateDomain.html#opensearchservice-CreateDomain-request-IPAddressType). According to the CDK docs currently there is no high level CDK construct for this feature 

### Use Case

The general recommendation is to use high level constructs and due to lack of High level construct for this feature, the CDK template needs to be migrated to use CFN constructs if there is a need to Create an OpenSearchDomain with IPAddressType. This serves as a hinderance to the adoption of the IPAddressType feature for AWS OpenSearch Domains.

### Proposed Solution

Add the IPAddressType to the Domain high level object [CDK Doc for Domain Options](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_opensearchservice.Domain.html) .
A IPAddressType based OpenSearchDomain created using CDK high level constructs should look like

```ts
const domain = new Domain(this, 'Domain', {
  version: EngineVersion.OPENSEARCH_1_0,
  ipAddressType: ipv4 (possible values: [ipv4, dualstack])
  capacity: {
  masterNodes: 3
  },
});
```

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.84.0

### Environment details (OS name and version, etc.)

macOS Ventura 13.4

**Comment by pahud** [comment]
Yes, the prop is already in L1. Should be easy to expose that to the L2 props.
Are you interested to submit a PR for that?

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-opensearchservice-domain.html#cfn-opensearchservice-domain-ipaddresstype
