### ISSUE TITLE
add a safety check to prevent clobbering non-CDK stacks

### ISSUE THREAD

**Issue by dhx-mike-palandra** [aws/aws-cdk#2844]
$ cdk --version
0.34.0 (build 523807c)

By default, the cdk CLI should refuse any command that would mutate a non-cdk stack.  For example, {`diff`, `synth`} should be accepted but {`deploy`, `destroy`} should be refused.  A command line switch and/or declaration in `cdk.json` could be implemented to override this check globally and perhaps also per-stack.

A stack could be identified as "CDK managed" by the presence of a resource of type `AWS::CDK::Metadata`.

**Comment by SomayaB** [comment]
HI @dhx-mike-palandra, thanks for submitting a feature request! We will look into this and someone will update this issue when there is movement.

**Comment by shantanu-nagarro** [comment]
This can be done through restricting the policies applied to the role for which the access keys are generated during the cdk run

**Comment by shaansharma1980** [comment]
This can be controlled by having fine grained IAM policies on the role for which the access credentials are being used in CDK. The destroy option even if run would disallow deletion of resources as per the policies attached to the user role.

**Comment by dhx-mike-palandra** [comment]
I like the idea of enforcing protections via IAM but I don't think it's flexible enough to differentiate between CDK and non-CDK stacks.

I reviewed [AWS CloudFormation conditions](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-iam-template.html#using-iam-template-conditions), and initially I thought there was some potential with condition key `cloudformation:ResourceTypes`.  After more careful review, I don't think it's useful here but it may be for other purposes, so it might be a good idea to check if CDK passes the requisite `ResourceTypes` parameter to CloudFormation.

The simplest idea I can come up with is a naming or tagging convention that partitions stacks into CDK and non-CDK, and a policy for the CDK user/role that restricts operations only to CDK stacks based on that convention.  Such a policy would be site-specific, so there may be some value to adding protections in CDK code.

**Comment by shaansharma1980** [comment]
cdk deploy provides

-r, --role-arn             ARN of Role to use when invoking CloudFormation                                                                        [string]

I believe this could be invoked to secure the deployment through the role ?

**Comment by dhx-mike-palandra** [comment]
That's a good observation, and generally your suggestions about IAM reflect best practice BUT they require a bit of advance planning.

My intent here is to suggest a safe guard for avoiding a potentially disruptive outcome:  modifying a stack that was never managed by CDK before.  Such an operation might be intentional but I believe it's more likely to happen accidentally.  As explained earlier, I believe such a change would be relatively simple to implement.
