### ISSUE TITLE
pipeline: should allow crossRegionReplicationBuckets passthrough to underlying CodePipeline construct

### ISSUE THREAD

**Issue by ahammond** [aws/aws-cdk#28446]
### Describe the feature

When deploying large numbers of CdkPipelines, we consume a lot of S3 buckets. There is already a way to reuse the artifact buckets across multiple CdkPipelines. We would like to also reuse the cross region replication buckets. To do this, we need to pass through the crossRegionReplicationBuckets property from the Pipeline object to the internal CodePipeline object.

### Use Case

There's a hard limit of 1000 S3 buckets per account. Our CdkPipelines deployer account supports pipelines from roughly 130 repos at this time and recently crossed the 900 bucket line. We need to be able to keep scaling out.

### Proposed Solution

Pass the `crossRegionReplicationBuckets` through, same has how `reuseCrossRegionSupportStacks` is passed through:
https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/pipelines/lib/codepipeline/codepipeline.ts#L458

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.115.0

### Environment details (OS name and version, etc.)

irrelevant

**Comment by khushail** [comment]
@ahammond ,thanks for submitting the FR and your contribution on PR.
