### ISSUE TITLE
aws-s3-deployment: `DeployTimeSubstitutedFile` doesn't keep original file name

### ISSUE THREAD

**Issue by garysassano** [aws/aws-cdk#28450]
### Describe the bug

When using DeployTimeSubstitutedFile, it might seem logical to assume that the uploaded file name, where substitutions are made, remains unchanged. However, this is not the case. Surprisingly, the system utilizes the file's [fingerprint](https://github.com/aws/aws-cdk/blob/58027ee477c2196e280dddb35626eefde2dce743/packages/aws-cdk-lib/aws-s3-deployment/lib/bucket-deployment.ts#L631) as the object key, rather than retaining the original file name. This approach can be quite unintuitive and unhelpful.

![image](https://github.com/aws/aws-cdk/assets/10464497/2beb83ac-23ec-49d6-9ce4-8b69f36eab45)

### Expected Behavior

see above

### Current Behavior

see above

### Reproduction Steps

see above

### Possible Solution

Use the original file name as the object key.

### CDK CLI Version

2.115.0

### Node.js Version

18.18.2

### OS

Windows 11 23H2

### Language

TypeScript

**Comment by gshpychka** [comment]
Seems like a deliberate design choice as opposed to a bug. This would probably make more sense as a feature request.

**Comment by khushail** [comment]
@garysassano , thanks for reporting this. Agree with @gshpychka , this might be a feature request.

**Comment by jmgtan** [comment]
Any update on this issue? This is complicating our deployment because we have to do another step to rename the file S3 API.

**Comment by gshpychka** [comment]
> Any update on this issue? This is complicating our deployment because we have to do another step to rename the file via S3 API.

There will not be any updates unless someone from the community implements this (since this is a feature request and it's marked as P2).

If there are updates, you will see them here
