### ISSUE TITLE
aws-elasticloadbalancingv2: SslPolicy enum doesn't include FIPS policies

### ISSUE THREAD

**Issue by nwesoccer** [aws/aws-cdk#28455]
### Describe the bug

The SslPolicy enum does not include the FIPS Policies that were announce in November (https://docs.aws.amazon.com/elasticloadbalancing/latest/application/create-https-listener.html#fips-security-policies).

### Expected Behavior

All Policies would be present in the SslPolicy enum, or there would be an option to use our own as a string.

### Current Behavior

No FIPS policies can be selected/used.

### Reproduction Steps

Create an ALB Listener.  During the create, use attempt to set the sslPolicy property to SslPolicy.(value that represents ELBSecurityPolicy-TLS13-1-2-Ext0-FIPS-2023-04 policy).

### CDK CLI Version

2.114.1

### Node.js Version

18

### OS

Mac

### Language

TypeScript

**Comment by pahud** [comment]
Looks like we can simply add it into the enum
https://github.com/aws/aws-cdk/blob/cd54c4239ec29182e30fd91634505df560d6e5f8/packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/shared/enums.ts#L99

Are you interested to submit a PR for that?
