### ISSUE TITLE
aws-ses: The naming convention for the dedicated IP pool cannot be confirmed.

### ISSUE THREAD

**Issue by badmintoncryer** [aws/aws-cdk#28451]
### Describe the feature

The dedicated pool has [specific characters that can be used in its name.](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ses-dedicatedippool.html#cfn-ses-dedicatedippool-poolname)

I propose a feature for CDK to verify that it adheres to this naming convention.

### Use Case

If a name containing forbidden characters is set for the dedicated IP pool, no error occurs at the stage of ‘cdk synth’, but it fails during deployment. Therefore, I believe it would be preferable to trigger an error at the synth stage.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.115.0

### Environment details (OS name and version, etc.)

irrelevant

**Comment by khushail** [comment]
Hi @badmintoncryer , that request makes sense. Thanks for submitting it and agreeing to work on it. Team would be happy to review your PR.
