### ISSUE TITLE
❗ NOTICE (core): Stack `crossRegionReferences` and `CfnJson` fail with `Error: Cannot find module '../dist/core/<file>.generated'`

### ISSUE THREAD

**Issue by mrgrain** [aws/aws-cdk#28465]
### Status

IN-PROGRESS

### What is the issue?

Enabling the experimental crossRegionReferences on a Stack or using the core.CfnJson construct causes app synthesis to fail with `Error: Cannot find module '../dist/core/<file>.generated'` because the files are missing from the faulty release. If you are not using either of the two features, you will not be affected by this.

### Error message

```console
Error: Cannot find module '../dist/core/cfn-utils-provider.generated'
```

### What is the impact?

Synth & deployment fails completely 

### Workaround

None.

### Who is affected?

Everyone using `CfnJson` or has enabled the experimental `crossRegionReferences` on a Stack with [v2.116.0](https://github.com/aws/aws-cdk/releases/tag/v2.116.0)

### How do I resolve this?

Update to `v2.116.1` (pending release)

### Related issues

https://github.com/aws/aws-cdk/pull/28251#issuecomment-1867476777

**Comment by Geaper** [comment]
Also facing similar issues...
`Error: Cannot find module '../../dist/core/cross-region-ssm-reader-provider.generated'
Require stack:
- /root/projects/senocloud-fleet-commander/cdk/node_modules/aws-cdk-lib/core/lib/custom-resource-provider/cross-region-export-providers/export-reader-provider.js
- /root/projects/senocloud-fleet-commander/cdk/node_modules/aws-cdk-lib/core/lib/custom-resource-provider/cross-region-export-providers/export-writer-provider.js
- /root/projects/project/cdk/node_modules/aws-cdk-lib/core/lib/private/refs.js
- /root/projects/project/cdk/node_modules/aws-cdk-lib/core/lib/private/prepare-app.js
- /root/projects/project/cdk/node_modules/aws-cdk-lib/core/lib/private/synthesis.js
- /root/projects/project/cdk/node_modules/aws-cdk-lib/core/lib/stage.js
- /root/projects/project/cdk/node_modules/aws-cdk-lib/core/lib/index.js
- /root/projects/project/cdk/node_modules/aws-cdk-lib/core/index.js
- /root/projects/project/cdk/node_modules/aws-cdk-lib/index.js`

**Comment by mrgrain** [comment]
@Geaper Thanks for reporting!

**Comment by mrgrain** [comment]
Hotfix release is underway: https://github.com/aws/aws-cdk/pull/28468
ETA: 2023-22-12 18:00 UTC

**Comment by mrgrain** [comment]
Fix has been released: https://github.com/aws/aws-cdk/releases/tag/v2.116.1
