### ISSUE TITLE
(aws-events): EventPattern support for wildcard filters

### ISSUE THREAD

**Issue by tyyzqmf** [aws/aws-cdk#28462]
### Describe the feature

As this whats-new: [Amazon EventBridge announces support for wildcard filters in rules](https://aws.amazon.com/about-aws/whats-new/2023/10/amazon-eventbridge-wildcard-filters-rules/?nc1=h_ls) 

### Use Case

We can set event pattern in web console:
```
{
  "detail-type": ["Step Functions Execution Status Change"],
  "resources": [{
    "wildcard": "arn:aws:states:us-east-1:111122223333:execution:xxx:yyy*"
  }],
  "source": ["aws.states"]
}
```
But can not create this rule by CDK:
```
const ruleState = new Rule(this, 'ListenStateStatusChange', {
      description: 'Rule for listen SFN state machine status change',
      eventPattern: {
        source: ['aws.states'],
        detailType: ['Step Functions Execution Status Change'],
        resources: [`{ "wildcard": "arn:${Aws.PARTITION}:states:${Aws.REGION}:${Aws.ACCOUNT_ID}:execution:xxx:yyy*" }`],
      },
    });
```

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.81.0

### Environment details (OS name and version, etc.)

linux

**Comment by pahud** [comment]
>But can not create this rule by CDK:

What error message was that?

Can you share the synthesized output specifically for the `Rule` resource?

**Comment by tim-finnigan** [comment]
Have you tried using the Match class? https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_events.Match.html

This came up in a similar issue earlier this year: https://github.com/aws/aws-cdk/issues/25424

**Comment by tyyzqmf** [comment]
> resources: [`{ "wildcard": "arn:${Aws.PARTITION}:states:${Aws.REGION}:${Aws.ACCOUNT_ID}:execution:xxx:yyy*" }`],



> > But can not create this rule by CDK:
> 
> What error message was that?
> 
> Can you share the synthesized output specifically for the `Rule` resource?

```json
{
  "EventPattern": {
    "source": [
      "aws.states"
    ],
    "detail-type": [
      "Step Functions Execution Status Change"
    ],
    "resources": [
      {
        "Fn::Join": [
          "",
          [
            "{ \"wildcard\": \"arn:",
            {
              "Ref": "AWS::Partition"
            },
            ":states:",
            {
              "Ref": "AWS::Region"
            },
            ":",
            {
              "Ref": "AWS::AccountId"
            },
            ":execution:xxx:yyy*\" }"
          ]
        ]
      }
    ]
  }
}
```

**Comment by tyyzqmf** [comment]
> Have you tried using the Match class? https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_events.Match.html
> 
> This came up in a similar issue earlier this year: #25424

@tim-finnigan Yes, I had try it. But there is no event pattern matcher can support for wildcard filter.

**Comment by pahud** [comment]
Yes it can deploy and I see this from the console

```json
{
  "detail-type": ["Step Functions Execution Status Change"],
  "resources": ["{ \"wildcard\": \"arn:aws:states:us-west-2:903779448426:execution:xxx:yyy*\" }"],
  "source": ["aws.states"]
}
```

while this is expected:

```json
{
  "detail-type": ["Step Functions Execution Status Change"],
  "resources": [{
    "wildcard": "arn:aws:states:us-east-1:111122223333:execution:xxx:yyy*"
  }],
  "source": ["aws.states"]
}
```

I guess the Match would need to support `wildcard` but before that you can use this workaround:

```ts
    const ruleState = new events.Rule(this, 'ListenStateStatusChange', {
      description: 'Rule for listen SFN state machine status change',
      eventPattern: {
        source: ['aws.states'],
        detailType: ['Step Functions Execution Status Change'],
        resources: [`{ "wildcard": "arn:${Aws.PARTITION}:states:${Aws.REGION}:${Aws.ACCOUNT_ID}:execution:xxx:yyy*" }`],
      },
    });

    (ruleState.node.defaultChild as events.CfnRule).addPropertyOverride('EventPattern.resources.0', 
     { wildcard: `arn:${Aws.PARTITION}:states:${Aws.REGION}:${Aws.ACCOUNT_ID}:execution:xxx:yyy*` },
    );
```

**Comment by tyyzqmf** [comment]
@pahud Thank you for your prompt. I have successfully created the rule following code:
```
    const cfnRule = rule.node.defaultChild as events.CfnRule;
    cfnRule.addOverride('Properties.EventPattern.resources', [
     {wildcard: `arn:${Aws.PARTITION}:states:${Aws.REGION}:${Aws.ACCOUNT_ID}:execution:xxx:yyy*`},
    ]);
```

**Comment by pahud** [comment]
@tyyzqmf Awesome! I am leaving this issue open until we have better implementation in CDK.

**Comment by jk2l** [comment]
encountered this issue too
