### ISSUE TITLE
aws_ec2: passing keyPair to Instance does nothing

### ISSUE THREAD

**Issue by SamuraiPrinciple** [aws/aws-cdk#28478]
### Describe the bug

With keyName property being deprecated (https://github.com/aws/aws-cdk/pull/28138), creating aws_ec2.KeyPair and passing it to aws_ec2.Instance does nothing.

### Expected Behavior

Make sure the keypair is associated with the instance when passed through keyPair property.

### Current Behavior

keypair does not get associated with the instance.

### Reproduction Steps

```ts
const keyPair = new ec2.KeyPair(this, 'KeyPair', {});
 this.instance = new ec2.Instance(this, 'EC2Instance', {
      vpc: props.vpc,
      vpcSubnets: { subnetType: ec2.SubnetType.PUBLIC },
      securityGroup,
      instanceType: ec2.InstanceType.of(ec2.InstanceClass.T3, ec2.InstanceSize.MICRO),
      machineImage: ec2.MachineImage.latestAmazonLinux2023(),
      keyPair,
      userDataCausesReplacement: true,
      ssmSessionPermissions: true,
    });

```

### CDK CLI Version

2.116.1 (build 222de71)

### Node.js Version

20.10.0

### OS

Linux

### Language

TypeScript

**Comment by tam0ri** [comment]
`props.keyPair` is never referred as property of CfnInstance.
https://github.com/aws/aws-cdk/blob/8071015400fbd71fd6eb85ae1118844422b6391c/packages/aws-cdk-lib/aws-ec2/lib/instance.ts#L438-L453

Specifying `props.keyPair?.keyPairName` for keyName property as same as LaunchTemplate will solve the issue.
https://github.com/aws/aws-cdk/blob/8071015400fbd71fd6eb85ae1118844422b6391c/packages/aws-cdk-lib/aws-ec2/lib/launch-template.ts#L758

It seems to be easy to fix and suitable for good first issue. I can take this, but if anyone is interested in submitting PR please feel free to try it :)

**Comment by pahud** [comment]
Awesome! Thank you for the PR!

**Comment by fire015** [comment]
+1 having the same problem

**Comment by yuki549** [comment]
+1 having the same problem

**Comment by GuillaumeEscande** [comment]
+1 having the same problem

**Comment by mrgrain** [comment]
Please use the 👍🏻 reaction on the original post if you have the same issue. Plus there already is a PR with potential fix open: https://github.com/aws/aws-cdk/pull/28482
