### ISSUE TITLE
"cdk docs" platform-specific browser command

### ISSUE THREAD

**Issue by dhx-mike-palandra** [aws/aws-cdk#2847]
$ cdk --version
0.34.0 (build 523807c)

The `docs` command should set `--browser` to a sensible value based on host platform.

On my platform of choice (cpe:/o:fedoraproject:fedora:30), the current default does not open a web browser.  A more reasonable default for me and probably for other Linux users would be `xdg-open %u`.

**Comment by shivlaks** [comment]
closed by #5800
