### ISSUE TITLE
aws_stepfunctions: item_processor function missing

### ISSUE THREAD

**Issue by hunt3ri** [aws/aws-cdk#28470]
### Describe the bug

As per the docs here I should be able to use the item_processor along with ProcessorMode, ProcessorType to define a distributed map.  None of these functions are available in the 2.115.0 build I'm using, eg they don't appear to be in the source code at all, or at least are not exposed to the python version

[ProcessorMode](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_stepfunctions/ProcessorMode.html)

### Expected Behavior

ProcessorMode functions should be available

### Current Behavior

ProcessorMode not available

### Reproduction Steps

Put this code in Python, see that item_processor not available

```
    distributed_map = sfn.Map(
            self,
            "ExtractDataMap",
            items_path=sfn.JsonPath.string_at("$.tables"),
            state_name="Process CSV",
        ).add_catch(failure, errors=["States.ALL"])

        distributed_map.item_processor(
            sfn.Pass(self, "Pass State"),
            mode=sfn.ProcessorMode.DISTRIBUTED,
            execution_type=sfn.ProcessorType.STANDARD,
        )
```

### Possible Solution

Expose these methods to Python?

### CDK CLI Version

2.115.0 (build 58027ee)

### Node.js Version

20

### OS

mac

### Language

Python

### Language Version

3.11

**Comment by khushail** [comment]
Hi @hunt3ri , I noticed [this PR ](https://github.com/aws/aws-cdk/pull/27913/files) was merged recently and addresses the issue. So this works in [latest version 2.116](https://github.com/aws/aws-cdk/releases/tag/v2.116.0). 
Please feel free to reach out if the issue persists.
