### ISSUE TITLE
Migration paths to CDK

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#285]
Discussion of tools in the CDK to support existing customers using CloudFormation/Terraform/etc to the CDK.

Ideas:

1. A construct that is backed by a JSON CFN template. Practically this means that all entities of this templates are represented by a single construct (the only difference from the original template [optionally] is that the logical IDs are prefixed by the parent's ID.
2. Create a construct that uses a nested stack and references a full existing template (example: QuickStarts).
3. Disassemblers - generate CDK code from a template
4. Load a template into memory and allow manipulation

**Comment by mabead** [comment]
Any update on this topic? I really love the CDK. In my opinion, it is perfect for brand new projects. But migrating existing projects that are based on terraform (for example) is a must to facilitate adoption from a larger audience.

**Comment by rix0rrr** [comment]
At the moment, we're focusing on feature completeness of the CDK system itself over migration scenarios. There is *some* interop with existing CloudFormation-based solutions, but Terraform will be a harder proposition because its deployment mechanism is completely different.

So the answer is, not anytime soon, sorry.

**Comment by mabead** [comment]
As long as you have a migration tool from cloudformation to cdk, it will be feasible for us to use CloudFormer to migrate an existing infrastructure deployed with terraform to cloudformation and then convert it to cdk.

Thanks for the answer. 

I'm looking forward for your GA!

**Comment by abelmokadem** [comment]
@eladb I'm really interested in the disassemblers. Is there a discussion on this topic?

**Comment by eladb** [comment]
There’s this: https://github.com/awslabs/aws-cdk/tree/master/packages/cdk-dasm

**Comment by Jerry-AWS** [comment]
Created an issue in the Dev Guide repo for this. https://github.com/awsdocs/aws-cdk-guide/issues/106

Closing it here.
