### ISSUE TITLE
(glue): openTableFormatInput does not exist in CfnTable

### ISSUE THREAD

**Issue by ShawnOY** [aws/aws-cdk#28506]
### Describe the issue

I tried to create an iceberg table, but I got the error message told me openTableFormatInput does not exist, and I upgraded the CDK version to v2.117.0, it has no help.

### Links

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_glue.CfnTable.html#opentableformatinput

**Comment by pahud** [comment]
Can you share the minimal reproducible code snippet, what is your expected result, what is current result and the full error messages?

**Comment by ShawnOY** [comment]
@pahud I found the root cause, I take a mistake, so it's not a bug/issue.
