### ISSUE TITLE
(iam): The naming conventions for IAM role names have not been verified

### ISSUE THREAD

**Issue by badmintoncryer** [aws/aws-cdk#28502]
### Describe the feature

[There are characters that cannot be used in IAM role names.](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html#aws-resource-iam-role-properties) (e.g., "/")

I propose a feature for CDK to verify that it adheres to this naming convention.

### Use Case

If a name containing forbidden characters is set for the role name, no error occurs at the stage of ‘cdk synth’, but it fails during deployment. Therefore, I believe it would be preferable to trigger an error at the synth stage.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.116.1

### Environment details (OS name and version, etc.)

irrelevant

**Comment by pahud** [comment]
Sounds good! Thank you for the PR.
