### ISSUE TITLE
AWS EKS: ALB Controller another operation error

### ISSUE THREAD

**Issue by andreprawira** [aws/aws-cdk#28514]
### Describe the bug

According to the official [doc ](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_eks/README.html#alb-controller-integration) we can add a controller by using `alb_controller=eks.AlbControllerOptions(version=eks.AlbControllerVersion.V2_6_2)` to an EKS cluster. However, that causes `another operation (install/upgrade/rollback) is in progress` error. And no, there was no other operation happening at the time. 

### Expected Behavior

ALB Controller created succesfully 

### Current Behavior

**Status reason:** Received response status [FAILED] from custom resource. Message returned: Error: b'Error: UPGRADE FAILED: another operation (install/upgrade/rollback) is in progress\n' Logs: /aws/lambda/infrastructure-stage-development-e-Handler886CB40B-Uefu5nGbCM3Q at invokeUserFunction (/var/task/framework.js:2:6) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async onEvent (/var/task/framework.js:1:369) at async Runtime.handler (/var/task/cfn-response.js:1:1573) (RequestId: 3d6422e7-a41c-48c1-96bd-d0b7897abdfb) 

**Logical ID:** developmentCDKPipelineinfrastructurestagedevelopmenteksstackekscluster3CDD0688AlbController122E6845

### Reproduction Steps

```
        vpc = ec2.Vpc.from_lookup(self, "VPCLookup", vpc_id="vpc-abcd1234")

        cluster = eks.Cluster(
            self,
            "eks-cluster",
            version=eks.KubernetesVersion.V1_28,
            kubectl_layer=lambda_layer_kubectl_v28.KubectlV28Layer(self, "kubectl-layer"),
            default_capacity_instance=ec2.InstanceType("t3.medium"),
            **alb_controller=eks.AlbControllerOptions(version=eks.AlbControllerVersion.V2_6_2)**,
            vpc=vpc,
            vpc_subnets=[ec2.SubnetSelection(subnet_type=ec2.SubnetType.PRIVATE_ISOLATED)]
        )
```
FYI, the code works if you remove or comment out the `alb_controller ` line

### CDK CLI Version

2.115.0 (build 58027ee)

### Node.js Version

v18.18.0

### OS

Windows

### Language

Python

### Language Version

Python 3.11.5

**Comment by pahud** [comment]
Let's discuss in https://github.com/aws/aws-cdk/issues/22005.
Close duplicate.
