### ISSUE TITLE
AWS CDK CDk-application-pipeline (module name): (short issue description)

### ISSUE THREAD

**Issue by araravicha** [aws/aws-cdk#28511]
### Describe the bug

executing the bootstrapping command in the provided examples npx ts-node infrastructure/src/bootstrap.tx results in unable to get local issuer certificate. 
I am trying this command form a windows powersheli. I am in the corporate network that uses Zscaler. IS there a way to determine what site is the command reaching out to? The eero happens after it gets the progule for the toolchain account. The error message is very cryptic and does not provide any indication of the destination it is trying to reach. Here is the error message:
 npx ts-node infrastructure/src/bootstrap.ts
√ Select AWS profile for 'toolchain' account » toolchain
Error: unable to get local issuer certificate
    at TLSSocket.onConnectSecure (node:_tls_wrap:1550:34)
    at TLSSocket.emit (node:events:514:28)
    at TLSSocket.emit (node:domain:489:12)
    at TLSSocket._finishInit (node:_tls_wrap:967:8)
    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:743:12) {
  code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY',
  '$metadata': { attempts: 1, totalRetryDelay: 0 }

### Expected Behavior

It should have bootstrapped the toolchain account

### Current Behavior

 npx ts-node infrastructure/src/bootstrap.ts
√ Select AWS profile for 'toolchain' account » toolchain
Error: unable to get local issuer certificate
    at TLSSocket.onConnectSecure (node:_tls_wrap:1550:34)
    at TLSSocket.emit (node:events:514:28)
    at TLSSocket.emit (node:domain:489:12)
    at TLSSocket._finishInit (node:_tls_wrap:967:8)
    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:743:12) {
  code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY',
  '$metadata': { attempts: 1, totalRetryDelay: 0 }

### Reproduction Steps

You need to be on a WIndows 10 environemnt on a corproate network using Zscaler (self signed certificates)

### Possible Solution

Need to determine the destination being accessed so that the certificate for that location along with Zscaler root certificate can be provisioned and the location of the certificate provided to the software (aws-CDK?) can be specified

### Additional Information/Context

Nothing else

### CDK CLI Version

2.113

### Node.js Version

18.17.1

### OS

Windows 10

### Language

TypeScript

### Language Version

10.9.2

**Comment by araravicha** [comment]
It is coconfirmed as an issue with Node.js not forwrding the env variable aws_ca-bundle to a sub process. If for that step we set https-proxy variable that step works but we get erros in the immediatley following steps because the proxy terminates the request before the handshake. SO remove the proxy and then the rest of the stuff works. The work around is clunky but will do fo rnow but the issue needs to be fixed within node.

**Comment by pahud** [comment]
I am not sure if this issue still exists. If it does, please provide a minimal code snippets that reproduces this issue. Thanks.

**Comment by araravicha** [comment]
This issue needs to be resolved. Node is not conveying environmental
parameters, when is spawns a sub process. The example code is in the cdk-
application- directory. In the file bootstrap.ts, when it spawns a sub
process to execute bootstrap command npx command
It works from the command line but not through the code
Thanks
Ravi

**Comment by pahud** [comment]
As mentioned, please provide a minimal code snippets that reproduces this issue so we can look into this problem. Thanks.
