### ISSUE TITLE
(aws-events): Upgrade to 2.117.0 rolls back due duplicate resources

### ISSUE THREAD

**Issue by pgarbe** [aws/aws-cdk#28520]
### Describe the bug

Upgrading to v2.117.0 breaks existing EventBus resources with an attached EventBusPolicy. The stack can't be deployed.

### Expected Behavior

Upgrade of CDK versions without breaking changes

### Current Behavior

The stack rolls back with a message like this:

```
MyEventsPolicySid already exists in stack arn:aws:cloudformation:eu-west-1:123456789012:stack/MyStack/...
```

### Reproduction Steps

Create an EventBus and a EventBus policy with CDK < 2.117.0. After updating to 2.117.0 the deployment fails.

Reason:
The PR https://github.com/aws/aws-cdk/pull/27340 changes the logicalId of the policy (from "Policy" to Sid) but keeps the `StatementId`. The changed logicalId triggers a replacement. But CloudFormation can't create multiple policies with the same StatementId and rolls back.

### Possible Solution

Workaround: Rename the `Sid` of your Policy and CloudFormation can roll out the update.

Possible fix: Ensure that the `StatementId` changes for existing resources (maybe prefix it or add a hash)

### CDK CLI Version

2.117.0

### Node.js Version

18

### OS

all

### Language

TypeScript, Python, .NET, Java, Go

**Comment by kaizencc** [comment]
Thanks for the report @pgarbe -- looks like something needs to be done about this, I'll be looking into it
