### ISSUE TITLE
aws-redshift-alpha: getting 'A previous rotation isn't complete. That rotation will be reattempted'

### ISSUE THREAD

**Issue by omer727** [aws/aws-cdk#28539]
### Describe the bug

When upgrade from 2.93.0-alpha.0 to 2.117.0-alpha.0 I'm getting:
'A previous rotation isn't complete. That rotation will be reattempted'
while doing deployment.

### Expected Behavior

deployed successfully

### Current Behavior

deployment is failing with a message 'A previous rotation isn't complete. That rotation will be reattempted'

### Reproduction Steps

create a stack with the following info
```
this.redshiftCluster = new Cluster(this, 'redshift', {
            clusterType: props.stage === 'main' ? ClusterType.MULTI_NODE : ClusterType.SINGLE_NODE,
            defaultDatabaseName: databaseName,
            encrypted: true,
            // loggingBucket: bucket, //todo
            // loggingKeyPrefix: `${props.serviceName}-${props.stage}`,
            masterUser: {
                masterUsername: this.redshiftUserName,
            },
            nodeType: NodeType.DC2_LARGE,
            numberOfNodes: props.stage === 'main' ? 2 : 1,
            port,
            removalPolicy: props.stage === 'main' ? RemovalPolicy.RETAIN : RemovalPolicy.DESTROY,
            roles: roles,
            securityGroups: [sg],
            vpc,
            vpcSubnets: { subnets: [vpc.publicSubnets[0]] },
            preferredMaintenanceWindow: 'Sun:01:00-Sun:10:00',
            clusterName: this.clusterIdentifier,
        });

        this.redshiftCluster.addRotationSingleUser();
```

on 2.117.0-alpha.0 you'll get the error message

### CDK CLI Version

2.117

### Node.js Version

node 20

### OS

mac

### Language

TypeScript

### Language Version

5.2.2

**Comment by pahud** [comment]
Probably related to https://github.com/aws/aws-cdk/issues/17265

Did you see any timeout logs in the rotation lambda log?
