### ISSUE TITLE
SecretsManager: Access denied trying to read secret value across accounts

### ISSUE THREAD

**Issue by jmihalich** [aws/aws-cdk#28537]
### Describe the bug

I'm trying to pull a secret value from the CDK (.Net V2.116.1), and i'm getting the following error:

10:33:46 PM | CREATE_FAILED        | AWS::IAM::SAMLProvider | VpnClientSelfServiceSAMLApp
User: arn:aws:sts::account-id-1:assumed-role/cdk-con-things-cfn-exec-role-account-id-1-us-west-2/AWSCloudFormation is not authorized to perform: secretsmanager:GetSecretValue on resource: arn:aws:secretsmanager:us-east-1:account-id-2:secret:ct/vpn/samlMetadata because no resource-based polic
y allows the secretsmanager:GetSecretValue action (Service: AWSSecretsManager; Status Code: 400; Error Code: AccessDeniedException; Request ID: 181b8870-46a3-4457-949e-2850e3ebe48b; Proxy: null)

Note above that the actual account ids were removed above.  Also, account-id-1 is in us-west-2 and account-id-2 is in us-east1.

This is confusing me, because if I assume the same role (cdk-con-things-cfn-exec-role-account-id-1-us-west-2) using the aws cli v2, and then set my environment vars to have the access key, secret key, session token, and region to be what assume role returned, and then i make the following cli call:

aws secretsmanager get-secret-value --secret-id arn:aws:secretsmanager:us-east-1:account-id-2:secret:ct/vpn/samlMetadata

That works fine and i get the secret back.

I have setup account-id-2 to allow secret access from that cdk-con-things-cfn-exec-role-account-id-1-us-west-2 role in the secret's resource policy.

### Expected Behavior

The CDK should be able to pull the secret from account-id-2

### Current Behavior

Getting an access denied error

10:33:46 PM | CREATE_FAILED        | AWS::IAM::SAMLProvider | VpnClientSelfServiceSAMLApp
User: arn:aws:sts::account-id-1:assumed-role/cdk-con-things-cfn-exec-role-account-id-1-us-west-2/AWSCloudFormation is not authorized to perform: secretsmanager:GetSecretValue on resource: arn:aws:secretsmanager:us-east-1:<account-id-2>:secret:ct/vpn/samlMetadata because no resource-based polic
y allows the secretsmanager:GetSecretValue action (Service: AWSSecretsManager; Status Code: 400; Error Code: AccessDeniedException; Request ID: 181b8870-46a3-4457-949e-2850e3ebe48b; Proxy: null)

### Reproduction Steps

This is my CDK Code:

`        var vpnCertJson = Secret.FromSecretCompleteArn(scope, "smTest1", "arn:aws:secretsmanager:us-east-1:account-id-2:secret:ct/vpn/samlMetadata-B24qcr");

        var vpnSecretValue = vpnCertJson.SecretValueFromJson("clientMetadataFile");
        clientMetadataFile = vpnSecretValue.UnsafeUnwrap();

        new CfnSAMLProvider(scope, "VpnClientSAMLApp", new CfnSAMLProviderProps()
        {
            SamlMetadataDocument = clientMetadataFile,
            Name = "aws-client-vpn",
        });
`
Note that the same problem occurs wether i use FromSecretCompleteArn or FromSecretPartialArn (without the -B24qcr at the end)

Also, the secret key resource policy is set as:

{
  "Version" : "2012-10-17",
  "Statement" : [ {
    "Effect" : "Allow",
    "Principal" : {
      "AWS" : "arn:aws:iam::account-id-1:role/cdk-con-things-cfn-exec-role-<account-id-1>-us-west-2"
    },
    "Action" : "secretsmanager:GetSecretValue",
    "Resource" : "*"
  } ]
}

Also, that secret was signed with a customer managed KMS key.  The KMS key has the same resource policy setup to give decrypt and describe access to account-id-1.

### CDK CLI Version

2.116.1 (build 222de71)

### Framework Version

.Net 8

### Node.js Version

v20.10.0

### OS

WSL Ubuntu 22.04 running on Windows 11

### Language

.NET

### Language Version

.Net 8

**Comment by jmihalich** [comment]
I've debugged this a little more.  It appears the issue lies in CloudFormation itself.  It doesn't seem like CF can handle different regions in the same template file.  

ie:  Deploy a stack in account 1 is us-west-2.  Within the account 1 stack, reference a secret in account 2 in us-east-1.

If i create the secret in account 2 in us-west-2 (same region as account 1), the secret lookup works fine.

For the life of me i can't understand why this wouldn't work.  it's clear the secret is being referenced in us-east-1, why can't CF hit the us-east-1 endpoint to do the lookup.

FYI, the same problem occurs with the CDK level 2 construct SamlProvider.  Obviously the problem is not within the SamlProvider construct itself...it's within the code doing the resolving of secret.

**Comment by jmihalich** [comment]
Now, that I know what/where the problem is, i was able to refine my google search, and found a number of articles that say that CF is a regional service and can't do cross region operations.

And yet, nowhere that i have found, does the CF documentation actually state that.

**Comment by pahud** [comment]
Yes cloudformation would not reference secrets cross regions. Thanks for your sharing.
