### ISSUE TITLE
all: check construct id and name length

### ISSUE THREAD

**Issue by mhintz-clickup** [aws/aws-cdk#28551]
### Describe the feature

Run into issues all the time where there is a cap on ID's from roles, kms keys, etc.
CDK should be aware of this and be able to detect when these will happen. 
Not sure if this happens with construct ID length but pretty sure I've seen it happen in the past. I mostly see it with KMS key names, Role names, and a few other resources.

### Use Case

Create a new role with some variables in it (like region or account name). 
When using projen (or just cdk) and doing a "build" (or synth, lint, etc.) then cdk will check on name lengths. 

### Proposed Solution

When using projen (or just cdk) and doing a "build" (or synth, lint, etc.) then cdk will check on name lengths. 

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

latest

### Environment details (OS name and version, etc.)

Linux

**Comment by tim-finnigan** [comment]
Thanks for the feature request. Could you provide specific steps/code to reproduce the issue? I'm wondering if this is something similar to https://github.com/aws/aws-cdk/issues/3402. I'd expect the limits to be consistent with whatever the services have defined, for example with KMS: https://docs.aws.amazon.com/kms/latest/APIReference/API_KeyMetadata.html
