### ISSUE TITLE
(custom-resources): Default logging configuration hits Cloudwatch Logs Resource Policy size limit

### ISSUE THREAD

**Issue by munch9** [aws/aws-cdk#28577]
Please add your +1 👍 to let us know you have encountered this
---

### Overview:

A previous PR enabled the ability to configure logging for a state-machine that was managed via a custom resource. This introduced a bug where the logging resource policy became too large because of the name of the log group. This could break the deploys of existing applications that contained this custom resource.

#### Complete Error Message:

```
@aws-cdk--aws-dynamodb.ReplicaProvider/Provider/waiter-state-machine (Providerwaiterstatemachine5D4A9DF0) Resource handler returned message: "Invalid Logging Configuration: The CloudWatch Logs Resource Policy size was exceeded. We suggest prefixing your CloudWatch log group name with /aws/vendedlogs/states/. (Service: AWSStepFunctions; Status Code: 400; Error Code: InvalidLoggingConfiguration; Request ID: 4ba96f98-4be5-450c-a069-3d4cbf93271a; Proxy: null)"
```

### Workaround:

Lock your cdk version to v1.115.0 or below.

### Solution:

Revert in progress: https://github.com/aws/aws-cdk/pull/28699

## Original Issue:

Title: **(custom-resources): Default logging configuration hits Cloudwatch Logs Resource Policy size limit**
-----------------------
### Describe the bug

Upgrading aws-cdk > 2.115 adds a default logging configuration to custom resources. 

When using `aws_dynamodb.Table` with `replication_regions` specified this automatically generates a `@aws-cdk--aws-dynamodb.ReplicaProvider.NestedStackResource` which contains `Providerwaiterstatemachine` and post upgrade also a new log group

When deploying the following error is returned
`@aws-cdk--aws-dynamodb.ReplicaProvider/Provider/waiter-state-machine (Providerwaiterstatemachine5D4A9DF0) Resource handler returned message: "Invalid Logging Configuration: The CloudWatch Logs Resource Policy size was exceeded. We suggest prefixing your CloudWatch log group name with /aws/vendedlogs/states/. (Service: AWSStepFunctions; Status Code: 400; Error Code: InvalidLoggingConfiguration; Request ID: 4ba96f98-4be5-450c-a069-3d4cbf93271a; Proxy: null)"`

### Expected Behavior

Default logging configuration should be configured in a way to prevent the above error

### Current Behavior

Upgrading to aws-cdk >=2.116 generates a logging configuration with what I believe is no name/prefix specified to the log group

```
"ProviderwaiterstatemachineLogGroupDD693A98": {
   "Type": "AWS::Logs::LogGroup",
   "Properties": {
    "RetentionInDays": 731,
   },
   "UpdateReplacePolicy": "Retain",
   "DeletionPolicy": "Retain",
   "Metadata": {
    "aws:cdk:path": "my-stack/@aws-cdk--aws-dynamodb.ReplicaProvider/Provider/waiter-state-machine/LogGroup/Resource"
   }
  }
```

Given the nested stack is auto generated I see no way to override the properties here.

### Reproduction Steps

Using the below construct with aws-cdk <=2.115 deploys successfully

```
table = aws_dynamodb.Table(
            self,
            "my-table",
            table_name="my-table",
            partition_key={"name": "pk", "type": aws_dynamodb.AttributeType.STRING},
            removal_policy=RemovalPolicy.RETAIN,
            replication_regions=["eu-central-1"],
            billing_mode=aws_dynamodb.BillingMode.PAY_PER_REQUEST,
            encryption=aws_dynamodb.TableEncryption.AWS_MANAGED,
            point_in_time_recovery=True,
        )
```

Upgrading aws-cdk > 2.115 causes the above error due to the newly added log group

### Possible Solution

Applying the prefix recommended in the above error message `/aws/vendedlogs/states/` similar to the recommendation [here] (https://docs.aws.amazon.com/step-functions/latest/dg/cw-logs.html) to the log group name?

### CDK CLI Version

2.116.0

### Node.js Version

18

### OS

Linux

### Language

Python

**Comment by pahud** [comment]
I think it's related to https://github.com/aws/aws-cdk/pull/27310

@go-to-k do you have any ideas about that?

**Comment by go-to-k** [comment]
Thanks for this report.

That is certainly true. I will work on this issue. It's to create a default log to start with `/aws/vendedlogs/states/`.

**Comment by MrArnoldPalmer** [comment]
Because this issue is a regression, I am reverting the PR that caused this initially. We can roll the new fix into the original change and make sure the tests cover the failure correctly to avoid this in the future.

**Comment by go-to-k** [comment]
@MrArnoldPalmer 

Okey, I'm going to add the correct changes in the PR for the one I'm working on now.

**Comment by MrArnoldPalmer** [comment]
thank you @go-to-k appreciate you taking this up again.

**Comment by MrArnoldPalmer** [comment]
v1.121.1 is out and should have this solved.

**Comment by digitalkaoz** [comment]
@go-to-k @MrArnoldPalmer we have the same issue with rolling out AWS WAFs the default log resource policy grows bigger with every waf (without configuring anything special beside the logging to CW) until the policy is to big and then every deployment fails. its fixable with the AWS CLI, but so far not with CDK (when tearing down a WAF Stack again we like to remove the entry inside the log resource policy:

```
aws logs describe-resource-policies | jq
{
  "resourcePolicies": [
    {
      "policyName": "AWSLogDeliveryWrite20150319",
      "policyDocument": "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Sid\":\"AWSLogDeliveryWrite\",\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"delivery.logs.amazonaws.com\"},\"Action\":[\"logs:CreateLogStream\",\"logs:PutLogEvents\"],\"Resource\":[\"arn:aws:logs:us-east-1:xx:log-group:aws-waf-logs-stage:log-stream:*\",\"arn:aws:logs:us-east-1:xx:log-group:/aws/vendedlogs/*\",\"arn:aws:logs:us-east-1:xx:log-group:aws-waf-logs-dev-pr-659:log-stream:*\",\"arn:aws:logs:us-east-1:xx:log-group:aws-waf-logs-dev-pr-652:log-stream:*\",\"arn:aws:logs:us-east-1:xx:log-group:aws-waf-logs-dev-pr-658:log-stream:*\",\"arn:aws:logs:us-east-1:xx:log-group:aws-waf-logs-dev-pr-656:log-stream:*\",\"arn:aws:logs:us-east-1:xx:log-group:aws-waf-logs-dev-pr-654:log-stream:*\",\"arn:aws:logs:us-east-1:xx:log-group:aws-waf-logs-dev-pr-655:log-stream:*\"],\"Condition\":{\"StringEquals\":{\"aws:SourceAccount\":\"xx\"},\"ArnLike\":{\"aws:SourceArn\":\"arn:aws:logs:us-east-1:xx:*\"}}}]}",
      "lastUpdatedTime": 1736329308830
    }
  ]
}
``` 

(see all the `aws-waf-logs-dev-pr-xyz:log-stream:*`entries)

**Comment by go-to-k** [comment]
@digitalkaoz I see, but the WAF L2 construct doesn't exist yet, so I think we have to handle it in our own CDK code.

(This issue is about using custom resources in SFn state machines.)

**Comment by ibrahim56201** [comment]
I got this issue again.

CDK CLI Version
2.116.0

Node.js Version
20.18.1

OS
Windows 11

Language
Typescript

Code:

```
    const logGroup = new LogGroup(this, `logGroup-${stateMachineName}`, {
        retention: RetentionDays.THREE_MONTHS,
        logGroupName: `/aws/vendedlogs/states/${stateMachineName}`,
        removalPolicy: RemovalPolicy.DESTROY,
    });

    this.sessionStartStateMachineV2 = new StateMachine(this, 'sessionStartStateMachineV2', {
        stateMachineName: sessionStartStateMachineNameV2,
        definitionBody: DefinitionBody.fromChainable(parallelStepsStart),
        logs: {
            destination: logGroupStart,
            includeExecutionData: true,
            level: LogLevel.ALL,
        },
        timeout: Duration.minutes(15),
        tracingEnabled: true,
    });
```

**Comment by go-to-k** [comment]
@ibrahim56201 

Have you tried `aws logs describe-resource-policies`?
Is it already full of policies for resources other than `/aws/vendedlogs/states/`? (In other words, doesn't the statement with the `/aws/vendedlogs/states/` in the resource policy?)

If not, it might be a good idea to start a new issue.

**Comment by go-to-k** [comment]
@ibrahim56201 

> CDK CLI Version
> 2.116.0

Could you please try it with the latest CDK version?

**Comment by WtfJoke** [comment]
@go-to-k I experienced the issue with the latest CDK version (cdk: 2.183.0  / cli: 2.1003.0)

**Comment by jaidisido** [comment]
> [@go-to-k](https://github.com/go-to-k) I experienced the issue with the latest CDK version (cdk: 2.183.0 / cli: 2.1003.0)
> 
> With following code-snippet:
> 
> const stateMachineLogs = new LogGroup(stack, "MyStateMachineLogs", {
>     removalPolicy: RemovalPolicy.DESTROY,
> });
> const stateMachine = new StateMachine(stack, "MyStateMachine", {
>     stateMachineType: StateMachineType.EXPRESS,
>     definitionBody: DefinitionBody.fromChainable(new Pass(stack, "Hello")),
>     tracingEnabled: true,
>     logs: {
>         destination: stateMachineLogs,
>         includeExecutionData: true,
>         level: LogLevel.ALL,
>     },
> });
> As a workaround: I defined a loggroupName for the StateMachine

I am facing a similar issue when defining the logs of my state machine without passing a specific name
