### ISSUE TITLE
(aws-s3-deployment): Fails to deploy when a large number of object keys are present

### ISSUE THREAD

**Issue by watersry** [aws/aws-cdk#28579]
### Describe the bug

When using the BucketDeployment for a large number of individual source files, the custom resource correctly persists them to S3, but ultimately fails the deployment due the large response send back to CloudFormation, exceeding the 4k limit for response objects. 

### Expected Behavior

The Cfn deployment should succeed if the BucketDeployment's underlying custom resource succeeds. 

### Current Behavior

Cfn fails to deploy the stack with `Response object is too long` despite the BucketDeployment lambda succeeding and successfully deploying all resources as expected. 

### Reproduction Steps

Any bucket deployment where the number of sources is sufficient to exceed the 4k response count. In our case, 50 config files succeeded to persist to s3  but failed due to the response to Cfn. 

```
    new BucketDeployment(this, `Deployment`, {
      sources: configs.map((conf) => Source.jsonData("someKey", conf)), 
      destinationBucket: bucket,
      memoryLimit: 1024,
      prune: false,
    });
```

### Possible Solution

The underlying custom resource provides the ability to choose an output path in the response, this could be used to truncate the response to Cfn and avoid this issue when the number of keys is sufficiently large or if a user intentionally configures it to do so. 

### CDK CLI Version

2.103.1

### Node.js Version

18

### OS

any

### Language

TypeScript

**Comment by pahud** [comment]
Looks like we need to fix it through the custom resource output path.

**Comment by mrlikl** [comment]
@pahud I am checking this part of a customer issue. Can I submit a PR to re-use `SourceObjectKeys` in the [objectKeys()](https://github.com/aws/aws-cdk/blob/597228c1552a21f8dc7250a0be62160f838bb776/packages/aws-cdk-lib/aws-s3-deployment/lib/bucket-deployment.ts#L521) method ? 

The [CR lambda](https://github.com/aws/aws-cdk/blob/597228c1552a21f8dc7250a0be62160f838bb776/packages/%40aws-cdk/custom-resource-handlers/lib/aws-s3-deployment/bucket-deployment-handler/index.py#L138C14-L138C30) is essentially sending back the same data in the response which is hitting the limit for close to 50 object uploads. 

Particularly this is being a limitation when using `servicecatalog.ProductStack`, if there are local assets beyond a particular number, the Custom::CDKBucketDeployment would fail with the error `Response object is too long` which is a hard limit of 4096 bytes. 

Please LMK your thoughts on this.

**Comment by pahud** [comment]
@mrlikl  I am not pretty sure how you would implement your PR. My initial idea is to allow user optionally specify the output path in the `BucketDeployment` construct props to work it around but there might be better solution.

Feel free to submit your PR so we have better visibility and hopefully move it forward.
