### ISSUE TITLE
(appconfig-alpha): grant read Configuration

### ISSUE THREAD

**Issue by yamatatsu** [aws/aws-cdk#28585]
### Describe the feature

Now `appconfig-alpha` has no grant method. If `grantReadConfig()` is implemented, it will be useful.

### Use Case

Using AppConfig from application codes.

### Proposed Solution

```ts
environment.grantReadConfig(lambdaFunction);
```

### Other Information

Needed policy is following:
```ts
new iam.PolicyStatement({
  actions: [
    "appconfig:GetLatestConfiguration",
    "appconfig:StartConfigurationSession",
  ],
  resources: [`${appConfigEnvironment.environmentArn}/*`],
})
```

see, https://docs.aws.amazon.com/appconfig/latest/userguide/about-data-plane.html

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.114.1

### Environment details (OS name and version, etc.)

Mac OS, Apple silicon, Sonoma 14.2.1

**Comment by pahud** [comment]
Absolutely! Thank you @yamatatsu !

**Comment by garciparedes** [comment]
This `grantReadConfig` is at `Enviornment` level so all the configurations within the environment can be read. So, we cannot define the permissions at `HostedConfiguration` using it. Could it make sense to add `grantRead` method for the `HostedConfiguration` construct in order to fill that gap? 🤔

**Comment by garciparedes** [comment]
Update: I've realized that, to do so on the `HostedConfiguration`, we need to know the `Environment` as well, so it would not be as "easy to use" as the current one for `Environment`.

**Comment by garciparedes** [comment]
Maybe adding `HostedConfiguration` as optional parameter when for the existing `Environment::grantReadConfig` to scope down the permissions would be the best solution. I'm thinking on something like: 
```
public grantReadConfig(identity: IGrantable, hostedConfiguration?: HostedConfiguration): Grant
```` 

@yamatatsu @pahud  @daschaa What do you think?
