### ISSUE TITLE
aws-signer: Signer Profile construct should support Notation-OCI-SHA384-ECDSA platform

### ISSUE THREAD

**Issue by Sohail-Haaris-bah** [aws/aws-cdk#28580]
### Describe the feature

The L2 construct for creating a Signer Profile in AWS Signer doesn't support creating a singer profile with the `Notation-OCI-SHA384-ECDSA` signing platform. This is odd, given that the L1 construct for it does. As such, I'd like to open a PR for the construct to add this capability, assuming that it just involves adding an instantiation to the `Platform` class.

### Use Case

[AWS documentation](https://docs.aws.amazon.com/signer/latest/developerguide/image-signing-steps.html) recommends using this particular signing profile for creating an AWS Signer configuration for signing Docker images that get pushed to an ECR repository. 

### Proposed Solution

Adding a new enum value for the Platform class. https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-signer/lib/signing-profile.ts#L9

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.x

### Environment details (OS name and version, etc.)

MacOS

**Comment by pahud** [comment]
Awesome! Thanks for the PR!
