### ISSUE TITLE
Print asset name and id when lambdas are built

### ISSUE THREAD

**Issue by MichaelHindley** [aws/aws-cdk#2858]
In stacks with multiple lambdas you may want to exclude some of them by using "build-exclude".

![image](https://user-images.githubusercontent.com/1016639/59435188-5ab3a900-8ded-11e9-89f9-bef063ce284b.png)

The problem is illustrated in the image above, how do you tell which lambda is which asset? I tried supplying the "ID" of the lamba as defined in the stack, but that does not work.

Suggestion: Print the "ID" of the lambda next to the asset hash, so you know which asset is which.

0.33.0

**Comment by MichaelHindley** [comment]
On third glance, what even is the asset ID?

It's not any of these things, at least I can't get it to be skipped by supplying these things:
* The ID supplied in the parameter to the Resource, i..e "MyFunLambda"
* The string part after `asset.`, or both combined

**Comment by SomayaB** [comment]
Hi @MichaelHindley, sorry for the late reply. We will look into this and someone will update this issue when there is movement.

**Comment by sambs** [comment]
This took me a while to figure out but I found the required ids in the manifest.json file. Search for a type "aws:cdk:asset" and the id is in the adjacent data object.
