### ISSUE TITLE
aws-cdk-cli: CDK fails if node executable has a space in the path

### ISSUE THREAD

**Issue by zastrowm** [aws/aws-cdk#28582]
### Describe the bug

The CDK fails to execute any command that uses a sub-process when the node executable has a space in its path.  The error is non-obvious as to the cause.

### Expected Behavior

The CDK commands should work the same whether or not the node executable has a space in its path.

### Current Behavior

A seemingly random error occurs running cdk commands:

```
❯ npm run release-synthesize
> cdk synthesize --output dist/cdk.out --app dist/src/resources/index.js

/bin/sh: /Users/{username}/Library/Application: No such file or directory
Error: Subprocess exited with error 127
    at ChildProcess.<anonymous> (/{path}/node_modules/aws-cdk/lib/api/cxapp/exec.ts:132:9)
    at ChildProcess.emit (node:events:517:28)
    at ChildProcess.emit (node:domain:489:12)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:292:12)
```

### Reproduction Steps

- Put node somewhere with a space in the path
- Then using that version of node in your path, execute the cdk command.

On MacOS I use [FNM](https://github.com/Schniz/fnm) as my node module and this was my node path:

```
/Users/{UserName}/Library/Application Support/fnm/node-versions/v18.18.2/installation/bin/node dist/src/resources/index.js
```

### Possible Solution

This seems to be caused by the line where the [`commandLine params are joined`](https://github.com/aws/aws-cdk/blob/10ed1948beb0f83c1b978da9c0a656aa01a382cb/packages/aws-cdk/lib/api/cxapp/exec.ts#L85C1-L86C1):

```ts
await exec(commandLine.join(' '));
```

I monkey-patched my local CDK install to quote values which have a space in them:

> [!TIP]
> it's worth noting that the `exec.js` may not be the file to fix this in - I needed to modify `index.js` instead

```ts
await exec(commandLine.map(it => it.includes(" ") ? `"${it}"` : it).join(' '));
```

which allowed all my CDK commands to execute successfully and without errors.

### Additional Information/Context

This took me a while to debug because I had no context as to what sub-process was failing. Immediately above the line there is some logging of the environment in debug mode - I'd suggest also emitting the path to the command line as well before calling `exec`; that would have at least alerted me to the fact that it was a node problem.

### CDK CLI Version

2.32.1 (build 79cbe95)

### Node.js Version

v18.18.2

### OS

MacOS

### Language

TypeScript

**Comment by pahud** [comment]
Thank you for the report. Yes I think we should fix it.

**Comment by albertothedev** [comment]
I have a similar error.

**Comment by vinayak-kukreja** [comment]
Hey, thank you for reporting this issue.

This issue as mentioned is being caused by a space being present in the path for node executable. Looking at node github repository issues, it looks like this is a known issue with how node handles spaces in paths. And for CDK, this occurs [here](https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk/lib/api/cxapp/exec.ts#L105-L113).

We currently do not have any plans to fix this on our end. Our recommendation for a workaround here would be to install node at a path which does not have spaces in it.
