### ISSUE TITLE
eks: Changing securityGroup deletes entire cluster

### ISSUE THREAD

**Issue by gricey432** [aws/aws-cdk#28584]
### Describe the bug

Adding a custom `securityGroup` to `eks.Cluster` causes a full replacement of the stateful k8s cluster and data loss.

### Expected Behavior

`securityGroup` would be updated in place as it is through the console, SDK, and as indicated in `cdk diff`.

### Current Behavior

The custom resource quietly created a new, empty EKS cluster and then deleted the existing cluster.

### Reproduction Steps

Should be reproducible by

1. Create a barebones `eks.Cluster` with no `securityGroup`
2. Deploy
3. Add a custom `securityGroup` to the cluster
4. Deploy

### Possible Solution

Looking at the `onEventHandler` logs for the custom resource, it looks like the issue is that changing the SG caused this update set

```
{
    "updates": {
        "replaceName": false,
        "replaceVpc": true,
        "updateAccess": false,
        "replaceRole": false,
        "updateVersion": false,
        "updateEncryption": false,
        "updateLogging": false
    }
}
```

Looks like the check for `replaceVpc` is very rough and way too trigger happy

https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/custom-resource-handlers/lib/aws-eks/cluster-resource-handler/cluster.ts#L330

In fact it looks like the API can replace subnets and security groups in place https://docs.aws.amazon.com/eks/latest/APIReference/API_UpdateClusterConfig.html

The `eks.Cluster` resource takes a `vpc` prop, I think the changing of that prop should be the only reason that `replaceVpc` needs to be true...

### CDK CLI Version

2.113.0 (build ccd534a)

### Node.js Version

v18.17.1

### OS

Windows 11

### Language

TypeScript

### Language Version

4.9.3

### Other information

https://github.com/aws/aws-cdk/issues/25544 may have aided disaster recovery here

I would like to have a Stack Policy on this stack but since it's implemented as a custom resource, cloudformation can only tell me that the CR itself isn't going to be replaced, but can't stop / inform me that the CR is going to be destructive.

**Comment by pahud** [comment]
Yes I think it's possible to just update the cluster security groups without replacing the cluster. At this moment the cluster construct from aws-eks is using customer resource to create the cluster but if we look at [SecurityGroupsIds](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-eks-cluster-resourcesvpcconfig.html#cfn-eks-cluster-resourcesvpcconfig-subnetids), it's [update with no Interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt).

Agree we should fix [replaceVpc](https://github.com/aws/aws-cdk/blob/10ed1948beb0f83c1b978da9c0a656aa01a382cb/packages/%40aws-cdk/custom-resource-handlers/lib/aws-eks/cluster-resource-handler/cluster.ts#L330).

**Comment by gricey432** [comment]
I've created #28609 to capture the broader idea of removing this custom resource all together.

This smaller improvement could still be implemented though, given the scale of that other ticket.
