### ISSUE TITLE
aws-cdk-lib: CrossAccountZoneDelegationRecord does not validate hostedZoneNameServers

### ISSUE THREAD

**Issue by u873838** [aws/aws-cdk#28581]
### Describe the bug

Our deployment failed when trying to use `CrossAccountZoneDelegationRecord` with an `IHostedZone` that did not have `hostedZoneNameServers` set. In our particular case, `IHostedZone` came from `PublicHostedZone.fromHostedZoneAttributes`.

### Expected Behavior

Either an error should be thrown during the CDK build process, or the construct should support an `IHostedZone` without unset.

### Current Behavior

We received the error during our CF deployment:
```
[FAILED] from custom resource. Message returned: TypeError: Cannot read properties of undefined (reading 'map') at cfnEventHandler
```

### Reproduction Steps

Our internal CDK code looked something like:
```typescript
const hostedZone = route53.PublicHostedZone.fromHostedZoneAttributes(this, 'WebsiteHostedZone', {
  hostedZoneId,
  zoneName: 'same.example.com'',
});

new CrossAccountZoneDelegationRecord(this, 'CrossAccountZoneDelegation', {
  // ...
  parentHostedZoneName: 'same.example.com',
  childHostedZoneName: hostedZone,
});
```

### Possible Solution

This line forcefully asserts that `hostedZoneNameServers` is defined: https://github.com/aws/aws-cdk/blob/a40f2ec1508e9b1718854b4b7c4037d59f197903/packages/aws-cdk-lib/aws-route53/lib/record-set.ts#L793

Then the handler reads from that possibly undefined array: https://github.com/aws/aws-cdk/blob/d69c51a2e10864e69d4610b6df30d40a9bfec3ac/packages/aws-cdk-lib/aws-route53/lib/cross-account-zone-delegation-handler/index.ts#L58

### CDK CLI Version

2.77.0

### Node.js Version

v18.12.1

### OS

Ubuntu 22.04.3

### Language

TypeScript

### Other information

We are an internal AWS team using SuperNova.

**Comment by pahud** [comment]
Thank you for the report. Yes it should throw out an error and the assertion might need more consideration.
