### ISSUE TITLE
eks: Remove the Cluster custom resource in favour of L1

### ISSUE THREAD

**Issue by gricey432** [aws/aws-cdk#28609]
### Describe the feature

Currently, `eks.Cluster` is implemented as a Custom Resource, though I believe this is no longer required and is causing unneeded complexity.

The docstring for the CR says

```
 Implements EKS create/update/delete through a CloudFormation custom resource
 in order to allow us to control the IAM role which creates the cluster. This
 is required in order to be able to allow CloudFormation to interact with the
 cluster via `kubectl` to enable Kubernetes management capabilities like apply
 manifest and IAM role/user RBAC mapping.
```

This was added 4 years ago in #3510 and I don't think it's true anymore. The [Cfn resource](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-eks-cluster.html) takes a `RoleArn` property which should solve the problem identified in the docstring.

I had a quick run through of the custom handler source and it looks like it hasn't really gained any other features since then, so should be a straighforward replacement.

### Use Case

#28584 highlights the serious risks introduced by CDK diverging from Cloudformation and implementing custom resources. The current implementation makes the behaviour harder to inspect.

### Proposed Solution

The L2 `eks.Cluster` should replace its internal `ClusterResource` with just the L1 `CfnCluster`.

I'm unsure on how this migration would actually have to work.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### CDK version used

2.113.0 (build ccd534a)

### Environment details (OS name and version, etc.)

N/A

**Comment by gshpychka** [comment]
>The [Cfn resource](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-eks-cluster.html) takes a RoleArn property which should solve the problem identified in the docstring.

I don't think this is correct - that is for the role that calls AWS APIs, not kubectl.

**Comment by gricey432** [comment]
> I don't think this is correct - that is for the role that calls AWS APIs, not kubectl.

I think you're right. @benfriebe do you think we might have this backwards?

https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-eks/lib/cluster-resource.ts#L79 and Line 92 show where the two different roles are used for their different purposes.

Is this "creator is admin" problem supposed to be solved by [Access Entries](https://docs.aws.amazon.com/eks/latest/userguide/access-entries.html#setting-up-access-entries)?

**Comment by pahud** [comment]
We absolutely need the new module. Let's track this feature request in https://github.com/aws/aws-cdk/issues/24059 and please help us prioritize with 👍  on that issue.

I am closing this one in favor of https://github.com/aws/aws-cdk/issues/24059
