### ISSUE TITLE
Setting Execution Role ARN in Lambda Integration Request - API Gateway

### ISSUE THREAD

**Issue by smoghal** [aws/aws-cdk#2860]
**Describe the bug**
I am using Java CDK to stand-up API’s in API Gateway service backed by Lambda function written in Java8.  In my customer’s account, I am not allowed to create Roles.  Roles are created by customer security team and given to the dev’s.
 
In API Gateway’s Lambda Integration request, I want to assign Execution Role in the Lambda integration request.  However, I’m running into a CDK Java SDK problem.  I can create `IRole` from a string using the Java `IRole` interface.  However, the `LambdaIntegrationOptions.Builder` only accepts a `Role` object in `.withCredentialRole()`.  I don’t see any way to convert `IRole` to a `Role` object, nor I found any other methods in `LambdaIntegrationOptions.Builder` that will allow me to pass the Role ARN instead of Role object.
 
To test things, I created CloudFormation template manually and used a Role ARN (given to me by the dev’s) in `AWS::ApiGateway::Method`.  It worked.

**To Reproduce**
NA - Related to CDK SDK specifically with `LambdaIntegrationOptions.Builder.withCredentialRole()` method

**Expected behavior**
Provide a mechanism in `LambdaIntegrationOptions.Builder` to accept a Role ARN and not a Role object.  Enterprise customers typically restrict developers to create Roles in AWS accounts; Role creation in AWS account is managed by separate security teams.  

So keeping the above use-case in mind, please make a CDK wide change where if you are creating a CloudFormation Resource that accepts `Role` object, make it accept Role ARN (using `IRole` interface).

**Version:**
 - OS - all
 - Programming Language - Java
 - CDK Version - 0.33.0

**Comment by tcco** [comment]
I am in a similar situation with my ability to create IAM roles via CDK. I am forced to use existing roles when creating stacks. However, for the python CDK SDK I am unable to specify a role for aws_gateway.LambdaRestAPI in order to send logs to CloudWatch. This is something @smoghal you'll want to check for the Java SDK since gateway is in your construct.

FYI the API reference for aws_lambda.Function has a `role` parameter documented [here](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_lambda/Function.html#aws_cdk.aws_lambda.Function.__init__). Maybe the recent updates cleared things up for you

Version:
CDK: 0.35.0
Programming Language: Python

**Comment by smoghal** [comment]
I have tested latest CDK 0.35.0.  `LambdaIntegrationOptions.Builder.withCredentialRole()` still doesn't accept a Role ARN.

Also, `aws_gateway.LambdaRestAPI` Python SDK is slightly different from what I read per your documentation reference.  I have no issue creating a Lambda function that accept Role ARN to send logs to CW.

The issue occurs in later stage when you want to assign the Lambda in APIG integration request.  The integration request also requires a role that APIG assumes to execute the Lambda.  This is where I'm stuck as the CDK SDK only allows you to specify a Role object (that CDK wants to create) instead of a Role ARN (created outside of CDK).

**Comment by RomainMuller** [comment]
Yes, the `credentialsRole` property should be typed `IRole` and not `Role`.

**Comment by smoghal** [comment]
Hi, is there any eta on this fix?  I have tried to use [addPropertyOverride](https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html) to override generated method resources.  It allows me to replace the generated `Integration.Credentials` at the method level.  However, the CDK execution still fails because now I have a dummy role in CFN that I can't delete.

I have to create a dummy role initially to properly construct `LambdaIntegration` object with `.withCredentialsRole()` which I can then later override with my Role ARN (above).  I haven't found a way to completely delete a resource from generated CDK template.  Apparently, `addDeletionOverride` only allows you to delete a property and not the entire resource.
