### ISSUE TITLE
aws cdk commands fail with error "Subprocess exited with error null"

### ISSUE THREAD

**Issue by ddev1122** [aws/aws-cdk#28637]
### Describe the bug

When I run any cdk command, it fails with the following error and exit code 1:
`Subprocess exited with error null`
No extra helpful information is printed out. 
However, when I use --verbose it raises the following info
Example running cdk ls --verbose
:

```
[14:56:39] Reading cached notices from /Users/{user}/.cdk/cache/notices.json

Subprocess exited with error null
[14:56:39] Error: Subprocess exited with error null
    at ChildProcess.<anonymous> (/Users/{user}/.nvm/versions/node/v18.19.0/lib/node_modules/aws-cdk/lib/index.js:423:50595)
    at ChildProcess.emit (node:events:517:28)
    at ChildProcess.emit (node:domain:489:12)
    at ChildProcess._handle.onexit (node:internal/child_process:292:12)
```

### Expected Behavior

List stacks or show a more helpful error message.

### Current Behavior

Fails with subprocess exited with error null

### Reproduction Steps

I have been able to run cdk ls, synth and deploy in other repository's, but not this one

### Additional Information/Context

I have tried different combinations of version of node (20, 14) , npm, and aws-cdk but still running into the same issue.
I am able to run cdk and deploy this same code/repo on a windows machine
I am using pyenv and nvm for version management, and running these cdk commands within a python poetry environment

### CDK CLI Version

2.118

### Node.js Version

18.19.0

### OS

Mac Sonoma 14.2.1

### Language

Python

### Language Version

3.8.10

**Comment by pahud** [comment]
I am not sure if this is related to the notice cache(`/Users/{user}/.cdk/cache/notices.json`) but it should be safe to delete it and run `cdk ls -vvv` again.



Can you try that and see if it is fixed?

**Comment by ddev1122** [comment]
Hi, just tried it and still getting the same error.  The notices.json just gets recreated each time

**Comment by mrgrain** [comment]
Please run with `--debug`

The line about notices might be misleading. That's likely just the last thing that worked.

**Comment by ddev1122** [comment]
Still immediately exiting with error when running cdk commands
ex.
`cdk ls --debug `or `cdk synth --debug`
`Subprocess exited with error null`

**Comment by mrgrain** [comment]
> Still immediately exiting with error when running cdk commands ex. `cdk ls --debug `or `cdk synth --debug` `Subprocess exited with error null`

Sorry I didn't specify this @ddev1122 . This will still fail, but can you please post the stack trace when running `cdk ls --debug`. The `--debug` stack trace will point us to the actual code point to identify what is going wrong.

**Comment by ddev1122** [comment]
Hi Mrgrain, I am not seeing any stack trace.
Immediately after entering those commands
the next line output is
`Subprocess exited with error null`

**Comment by mrgrain** [comment]
Hmm, @ddev1122 so in your first post you got this stack trace:
```
[14:56:39] Error: Subprocess exited with error null
    at ChildProcess.<anonymous> (/Users/{user}/.nvm/versions/node/v18.19.0/lib/node_modules/aws-cdk/lib/index.js:423:50595)
    at ChildProcess.emit (node:events:517:28)
    at ChildProcess.emit (node:domain:489:12)
    at ChildProcess._handle.onexit (node:internal/child_process:292:12)
```

Are you still getting this? But with `--debug` you get no stack trace?

**Comment by ddev1122** [comment]
Correct - if i use `--verbose,` I get that stack trace, but with `--debug,` no output is given

**Comment by mrgrain** [comment]
Alright, so apparently you need to run `cdk ls -vvv --debug` - Apologies, I wrongly assumed that `--debug` implies verbosity. Could you try that again and post the output?

**Comment by ddev1122** [comment]
Sure, here is the output running 
cdk ls -vvv -debug
```
[13:05:54] outdir: cdk.out
[13:05:54] env: {
  CDK_DEFAULT_REGION: 'us-west-2',
  CDK_DEFAULT_ACCOUNT: 'ACCTNUMBER',
  CDK_DEBUG: 'true',
  CDK_OUTDIR: 'cdk.out',
  CDK_CLI_ASM_VERSION: '36.0.0',
  CDK_CLI_VERSION: '2.118.0'
}

[13:05:54] Notices refreshed
[13:05:58] Reading cached notices from /Users/{}/.cdk/cache/notices.json

Subprocess exited with error null
[13:05:59] Error: Subprocess exited with error null
    at ChildProcess.<anonymous> (/Users/{user}/.nvm/versions/node/v18.19.0/lib/node_modules/aws-cdk/lib/api/cxapp/exec.ts:121:23)
    at ChildProcess.emit (node:events:517:28)
    at ChildProcess.emit (node:domain:489:12)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:292:12)
```

I believe this is the code from the cdk lib thats raising that error (cxapp/exec.js)
```
    async function exec(commandAndArgs) {
        return new Promise((ok, fail) => {
            // We use a slightly lower-level interface to:
            //
            // - Pass arguments in an array instead of a string, to get around a
            //   number of quoting issues introduced by the intermediate shell layer
            //   (which would be different between Linux and Windows).
            //
            // - Inherit stderr from controlling terminal. We don't use the captured value
            //   anyway, and if the subprocess is printing to it for debugging purposes the
            //   user gets to see it sooner. Plus, capturing doesn't interact nicely with some
            //   processes like Maven.
            const proc = childProcess.spawn(commandAndArgs, {
                stdio: ['ignore', 'inherit', 'inherit'],
                detached: false,
                shell: true,
                env: {
                    ...process.env,
                    ...env,
                },
            });
            proc.on('error', fail);
            proc.on('exit', code => {
                if (code === 0) {
                    return ok();
                }
                else {
                    return fail(new Error(`Subprocess exited with error ${code}`));
                }
            });
        });
    }
```

**Comment by mrgrain** [comment]
Okay, I think your cdk app doesn't synthesize correctly. Obviously the error should be more helpful.

In the meantime:
- What is the command for your CDK app? That's the `app` value in `cdk.json`.
- If you run this command directly, does it work? If you get an error, is it more helpful?
- Are you using a non default synthesizer? If so, can you provide the code snippets how you use it.

**Comment by ddev1122** [comment]
- The command being used is `python app.py`
- If I run this directly, I am getting a `Segmentation fault: 11 `(not sure if this is any more helpful)
- We are using the default synthesizer

**Comment by mrgrain** [comment]
> - If I run this directly, I am getting a Segmentation fault: 11 (not sure if this is any more helpful)

It tells us the following:
- The issue is not with the AWS CDK CLI
- The issue is within Python

I'm not a Python expert, but found this when googling, maybe it's https://blog.richard.do/2018/03/18/how-to-debug-segmentation-fault-in-python/

You can probably use standard debugging techniques to find the offending code.

> I have been able to run cdk ls, synth and deploy in other repository's, but not this one

Do you know if this ever worked?

**Comment by ddev1122** [comment]
Finally got the commands to run..
I upgraded python from 3.8.10 to 3.12 and updated some of the package dependencies...that seemed to do it
Thanks for your help.
