### ISSUE TITLE
CodePipeline: S3 bucket policy race condition

### ISSUE THREAD

**Issue by estepamo-amazon** [aws/aws-cdk#28650]
### Describe the bug

A race condition happens randomly when provisioning the S3 bucket and its bucket policy as part of the CodePipeline construct. CloudTrail logs show a PutBucketTagging API call to S3 happening before the API call to create the S3 bucket.

### Expected Behavior

The CodePipeline construct is provisioned without issues

### Current Behavior

Provisioning fails.

### Reproduction Steps

1) Write a CDK stack that provisions a CodePipeline resource using the CodePipeline construct. 
2) cdk synth
3) cdk deploy

### CDK CLI Version

2.87.0

### Node.js Version

18.17.1

### OS

Windows (WSL)

### Language

Python

### Language Version

3.10.12

### Other information

https://github.com/aws-solutions/mlops-workload-orchestrator/blob/main/source/infrastructure/lib/mlops_orchestrator_stack.py#L484

**Comment by pahud** [comment]
Are you able to provide the minimal code snippets that reproduces this issue?
