### ISSUE TITLE
Fix broken CDK Workshop links

### ISSUE THREAD

**Issue by fulghum** [aws/aws-cdk#2865]
A few of the links in the CDK workshop are broken; example: links to the old Developer Guide location. 

https://cdkworkshop.com/70-conclusion.html

**Comment by made2591** [comment]
It seems now they are fixed but the site is not using the latest content from master branch ([source](https://github.com/aws-samples/aws-cdk-intro-workshop/commit/ee57007b6cc92dd0ba0fe937da5b4c590c063fdf)) 🤔... Am I wrong?
