### ISSUE TITLE
aws-cdk-cli: cdk synth runs ec2.Vpc.fromLoookup twice and fails the second time

### ISSUE THREAD

**Issue by dirkgomez** [aws/aws-cdk#28686]
### Describe the bug

This is the bug ticket from this discussion: https://github.com/aws/aws-cdk/discussions/28262: cdk synth runs twice and ultimately fails with:

Could not assume arn:aws:iam::<accountid>:role/cdk-hnb659fds-lookup-role-<accountid>-eu-central-1, proceeding anyway.
(To get rid of this warning, please upgrade to bootstrap version >= 8)
Need to perform AWS calls for account <accountid>, but no credentials have been configured

For me the offending line in my CDK stack seems to be:

    const vpc = ec2.Vpc.fromLookup(this, 'vpcForAccount', { vpcName: 'VPC1-VPC', isDefault: false, });

Synthing works fine when I use an AWS profile that uses AWS SSO, it fails (alas not 100% deterministically) when run in a container on our Gitlab runners that use the EC2 instance profile as their credential source. Our containers are AL2023-based and use Node 18. I last tested this with CDK 2.118.0

### Expected Behavior

cdk synth works deterministically

### Current Behavior

The failing run ends with

Could not assume arn:aws:iam::<accountid>:role/cdk-hnb659fds-lookup-role-<accountid>-eu-central-1, proceeding anyway.
(To get rid of this warning, please upgrade to bootstrap version >= 8)
Need to perform AWS calls for account <accountid>, but no credentials have been configured

### Reproduction Steps

- Create a CDK stack with a Vpc.fromLookup call
- Deploy with permissions assumed via EC2 instance profile

### CDK CLI Version

2.118

### Node.js Version

18.19.0

### OS

Amazon Linux 2023

### Language

TypeScript

**Comment by pahud** [comment]
```
Could not assume arn:aws:iam:::role/cdk-hnb659fds-lookup-role--eu-central-1
```

This means your instance profile that runs the `cdk deploy` can't assume the lookup-role.

Can you share the full  IAM policies of the instance role?
