### ISSUE TITLE
kinesisfirehose-destinations-alpha: support firehose zero buffering

### ISSUE THREAD

**Issue by humanzz** [aws/aws-cdk#28714]
### Describe the feature

Firehose released Firehose zero buffering in [this announcement](https://aws.amazon.com/about-aws/whats-new/2023/12/amazon-kinesis-data-firehose-zero-buffering/) ([documentation](https://docs.aws.amazon.com/firehose/latest/dev/buffering-hints.html)) which allows for setting buffering interval seconds as low as `0` as opposed to the [existing minimum of `60`](https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/aws-kinesisfirehose-destinations-alpha/lib/private/helpers.ts#L90) in cdk.

This is a request to allow setting `bufferingInterval` prop as low as `0`.

### Use Case

See released feature

### Proposed Solution

Update the validation to allow for values as low as `0`

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.117.0

### Environment details (OS name and version, etc.)

macOS

**Comment by pahud** [comment]
Thank you for the PR.
