### ISSUE TITLE
awscdklambdagoalpha: LogRetention doesn't work

### ISSUE THREAD

**Issue by eloymg** [aws/aws-cdk#28711]
### Describe the bug

LogRetention doesn't work

### Expected Behavior

Modify Lambda Logs retention to 3 months

### Current Behavior

The Lambda Logs retention remains in never

### Reproduction Steps

I cretae the lambda using this code: 
![image](https://github.com/aws/aws-cdk/assets/10076482/973bf5f2-17e6-487a-9813-7739ab166a4b)
And in Cloudwatch logs see:
![image](https://github.com/aws/aws-cdk/assets/10076482/1bf75464-a3a6-409c-ad6c-048153ed63da)
Don't see any errors in LogRetetion Lambda.

### CDK CLI Version

2.117.0 (build 59d9b23)

### Node.js Version

v18.19.0

### OS

macOS Sonoma 14.2.1 (23C71)

### Language

Go

### Language Version

go1.21.3 darwin/arm64

**Comment by sakurai-ryo** [comment]
Hi @eloymg 
Thanks for reaching out!
Could you try to use `awslogs.RetentionDays_THREE_MONTHS` instead of `awslogs.RetentionDays("90")`?
https://pkg.go.dev/github.com/aws/aws-cdk-go/awscdk/awslogs#RetentionDays

**Comment by eloymg** [comment]
Hi @sakurai-ryo , works. Sorry i doesn't see properly that the type needed are a Enum. My confusion comes from the code itself works but no in the proper way. The name of the type I think is a bit confusing.

**Comment by sakurai-ryo** [comment]
@eloymg 
Sorry for the confusion and thanks for the feedback.
Many examples are listed in godoc and elsewhere, so if you have any problems, I would be grateful if you could look.
