### ISSUE TITLE
CDK Autoscaling ASG: instance type m7a.medium is not valid (us-east-1)

### ISSUE THREAD

**Issue by matsonkepson** [aws/aws-cdk#28721]
### Describe the bug

When trying to update the EC2 type to m7a.medium from m5a.large (us-east-1) I get 
```
"The specified instance type m7a.medium is not valid(Service: AutoScaling, Status Code: 400)"
```

### Expected Behavior

Instance type is being deployed since I can find it in docs as well as the web interface

### Current Behavior

The `cdk diff` shows planned changed but deploy gives >
```
"The specified instance type m7a.medium is not valid(Service: AutoScaling, Status Code: 400)"
```

### Reproduction Steps

1. CDK version 2.121.1, us-east-1
2. create an ASG with EC2 m5a.large
3. try to change it to m7a.medium

### CDK CLI Version

2.121.1

### Node.js Version

18

### OS

linux

### Language

TypeScript

### Other information

Works with c6a.large to which I have changed instead

**Comment by pahud** [comment]
Can you just deploy a new ASG with `m7a.medium` instance type in us-east-1?

If not, can you share the minimal cdk code snippets?

**Comment by MADDY312** [comment]
I am trying to switch from t2.small to c7a.medium/m7a.medium, It throws the same error, but when trying to switch from t2.small to c5a.large, it works fine. And my region is us-east-1. Has anybody found any solution to this?

**Comment by MADDY312** [comment]
just activate IMDSv1 by deselceting the checkbox, in the instance configuration

**Comment by petervanwylen** [comment]
Having the same problem. I'm trying to launch an m7a.medium from brand new environment config and getting that exact error.
