### ISSUE TITLE
route53: support latency based routing

### ISSUE THREAD

**Issue by badmintoncryer** [aws/aws-cdk#28722]
### Describe the feature

In Route 53, there is a latency-based routing feature. I want to implement this using CDK.

https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/routing-policy-latency.html

### Use Case

In Cfn, this can be implemented by setting the region argument, but it cannot be implemented from L2.

### Proposed Solution

Add region props to RecordSet and generate setIdentifier.
```ts
new RecordSet(scope, id, {
  ...  
  region: 'ap-northeast-1', // add
})
```

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.116.1

### Environment details (OS name and version, etc.)

irrelevant

**Comment by pahud** [comment]
Thank you for the PR.
