### ISSUE TITLE
efs: support `TransitionToArchive` property for `AWS::EFS::FileSystem`

### ISSUE THREAD

**Issue by longtv2222** [aws/aws-cdk#28720]
### Describe the feature

Support `TransitionToArchive` property for `AWS::EFS::FileSystem`

More about this property [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-efs-filesystem-lifecyclepolicy.html#cfn-efs-filesystem-lifecyclepolicy-transitiontoarchive)

### Use Case

Currently the property is not supported by `FileSystem` L2 construct

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

v2.121.1

### Environment details (OS name and version, etc.)

Ubuntu 22.04

**Comment by pahud** [comment]
Thank you for the PR!
