### ISSUE TITLE
opensearch-service: custom endpoint configuration is not removed on rollback or delete

### ISSUE THREAD

**Issue by dermicus-miclip** [aws/aws-cdk#28724]
### Describe the bug

When updating an OpenSearch service domain and adding a custom endpoint, on rollback (due to failure) the custom endpoint is not removed.

The same issue occurs when attempting to remove a custom endpoint that already exists.

When using CDK along with an ACM certificate and a R53 hosted zone, the result is that the cloudformation stack is now in an endless loop, as it cannot delete the ACM certificate as it is still in use in the OpenSearch domain's custom endpoint. It can be resolved by manually deleting the Opensearch custom endpoint.

### Expected Behavior

Cloudformation eventually marks the OpenSearch domain as `UPDATED` in the console.

### Current Behavior

The Cloudformation update should actually trigger the deletion of the custom endpoint of the OpenSearch domain.

### Reproduction Steps

* Create an opensearch domain in CDK and let the Cloudformation stack be created
* Update the custom endpoint configuration and add one using a certificate and r53 hosted zone explicitly configured
* Now try to delete the custom endpoint again

### CDK CLI Version

2.114.1

### Node.js Version

18.x

### OS

macOS

### Language

TypeScript

### Language Version

4.7

**Comment by pahud** [comment]
Thank you for the report. Are you able to share the minimal code snippets that we can reproduce in our environment?
