### ISSUE TITLE
queue-base: JSDoc of QueueAttributes QueueURL point to falsy Documentation Location 

### ISSUE THREAD

**Issue by niko-achilles** [aws/aws-cdk#28734]
### Describe the bug

Queue Base exports the interface `QueueAttributes` . 
The interface `QueueAttributes` defines the `queueUrl` property among other interface properties. 
The `QueueAttributes` are documented in JSDoc annotation.  
In the documentation about `queueUrl` property as JSDoc annotation, the bug is found.
The `@see` tag of JSDoc points to a falsy http documentation location.  

### Expected Behavior

The property `queueUrl` of the `QueueAttributes` interface is expected to be documented as JSDoc annotation correctly. 

### Current Behavior

Below the `@see` tag of JSDoc annotation for `queueUrl` as defined in the current code base.    
The line of code in the repository is located [here](https://github.com/aws/aws-cdk/blob/109b2abe4c713624e731afa1b82c3c1a3ba064c9/packages/aws-cdk-lib/aws-sqs/lib/queue-base.ts#L284-L290)

```ts
export interface QueueAttributes {
 
...

  /**
   * The URL of the queue.
   * @see https://docs.aws.amazon.com/sdk-for-net/v2/developer-guide/QueueURL.html
   *
   * @default - 'https://sqs.<region-endpoint>/<account-ID>/<queue-name>'
   */
  readonly queueUrl?: string;

...
} 
```

### Reproduction Steps

Visit 
the lines of code in the current repository [here](https://github.com/aws/aws-cdk/blob/109b2abe4c713624e731afa1b82c3c1a3ba064c9/packages/aws-cdk-lib/aws-sqs/lib/queue-base.ts#L284-L290)

And use the http resource defined in the JSDoc `@see` tag, which navigates to the following http [location](https://docs.aws.amazon.com/sdk-for-net/v2/developer-guide/QueueURL.html)

### Possible Solution

2 possible solutions:

1.  The `@see` JSDoc tag should be removed

```ts
export interface QueueAttributes {
...

  /**
   * The URL of the queue.
   * 
   * @default - 'https://sqs.<region-endpoint>/<account-ID>/<queue-name>'
   */
  readonly queueUrl?: string;

...
}
```

2. correct the `@see` tag of JSDoc to point to the following http [location](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_GetQueueUrl.html#SQS-GetQueueUrl-response-QueueUrl)

```ts
export interface QueueAttributes {
...

  /**
   * The URL of the queue.
   * @see https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_GetQueueUrl.html#SQS-GetQueueUrl-response-QueueUrl
   * 
   * @default - 'https://sqs.<region-endpoint>/<account-ID>/<queue-name>'
   */
  readonly queueUrl?: string;

...
}

### Additional Information/Context

_No response_

### CDK CLI Version

2.121.1 (build d86bb1a)

### Framework Version

_No response_

### Node.js Version

v20.11.0

### OS

ubuntu

### Language

TypeScript

### Language Version

_No response_

### Other information

_No response_

**Comment by tim-finnigan** [comment]
Hi @niko-achilles thanks for catching this issues, it definitely looks like that URL should be removed or replaced. Looking at other examples of `@see` in the code, it seems like those often point to User/Developer Guides. I think this page/section might be the best place to pout here for an SQS Queue URL: https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-queue-message-identifiers.html#sqs-general-identifiers. But I'd be interested to hear the feedback of others as well. Please feel free to submit a PR for this if you are inclined.
