### ISSUE TITLE
(apigateway): Add EndpointConfiguration property support for SpecRestAPI

### ISSUE THREAD

**Issue by mrlikl** [aws/aws-cdk#28739]
### Describe the feature

Please add the `EndpointConfiguration` prop to SpecRestAPI construct just like to [RestApi](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_apigateway.RestApi.html#endpointconfiguration) and [LambdaRestApi](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_apigateway.LambdaRestApi.html#endpointconfiguration) constructs.

Atm, the WorkArounds are to use the Open API file or Escape hatch as per [comment](https://github.com/aws/aws-cdk/issues/9684#issuecomment-810524732)

### Use Case

Continuation to issue #9684

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.103.1

### Environment details (OS name and version, etc.)

macos

**Comment by tim-finnigan** [comment]
Thanks for bringing attention back to this, I'm going to reopen https://github.com/aws/aws-cdk/issues/9684 for tracking so that others following that issue can continue to do so there.
