### ISSUE TITLE
stepfunctions-tasks: mediapackagevod service generates wrong action in role policy

### ISSUE THREAD

**Issue by orekav** [aws/aws-cdk#28774]
### Describe the bug

Following code is properly creates a step in Step Functions

```typescript
new sfn_tasks.CallAwsService(stack, 'DeleteMediaPackageVoDAsset', {
  service: 'mediapackagevod',
  action: 'deleteAsset',
  resultPath: sfn.JsonPath.DISCARD,
  iamResources: ['*'],
});
```
However, it creates wrong statement in the role policy.
```json
        {
            "Action": "mediapackagevod:deleteAsset",
            "Resource": "*",
            "Effect": "Allow"
        }
```

Correct service prefix for `MediaPackageVoD` is `mediapackage-vod`.
https://docs.aws.amazon.com/service-authorization/latest/reference/list_awselementalmediapackagevod.html

This issue is similar with https://github.com/aws/aws-cdk/issues/27573 and https://github.com/aws/aws-cdk/issues/28081.

### Expected Behavior

Action should be mediapackage-vod:deleteAsset

### Current Behavior

Action is mediapackagevod:deleteAsset

### Reproduction Steps

Sample code for reproduction is below:

```typescript
import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import {
  aws_stepfunctions as sfn,
  aws_stepfunctions_tasks as sfn_tasks,
} from 'aws-cdk-lib';

export class SfnMediaPackageVoDStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const deleteAsset = new sfn_tasks.CallAwsService(stack, 'DeleteMediaPackageVoDAsset', {
      service: 'mediapackagevod',
      action: 'deleteAsset',
      resultPath: sfn.JsonPath.DISCARD,
      iamResources: ['*'],
    });
  
    new sfn.StateMachine(this, 'SimpleStateMachine', {
      definitionBody: sfn.DefinitionBody.fromChainable(deleteAsset)
    });
  }
}
```

### Possible Solution

[aws-cdk/packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/aws-sdk/call-aws-service.ts](https://github.com/aws/aws-cdk/blob/25ee8ef61d6b33628923a0fee4c042a0f0f2441e/packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/aws-sdk/call-aws-service.ts#L92-L96)

### CDK CLI Version

2.122.0

### Node.js Version

v18.19.0

### OS

MacOS

### Language

TypeScript

**Comment by pahud** [comment]
Thank you for the report and pull request.
