### ISSUE TITLE
(eks): Helm custom handler uninstall does not respect --wait

### ISSUE THREAD

**Issue by ellistarn** [aws/aws-cdk#28831]
### Describe the bug

When I use `--wait` in the HelmChart construct, helm does not correctly wait during object deletion.

### Expected Behavior

Helm should pass `--wait` on uninstall.

### Current Behavior

Dependency ordering is not respected.

### Reproduction Steps

* Create helm chart that contains objects with finalizers
* Delete helm chart 
* Helm chart should block deletion until the objects are successfully deleted

### CDK CLI Version

2.117.0

### Node.js Version

14

### OS

osx

### Language

TypeScript

**Comment by pahud** [comment]
Just read your PR. Figured out we missed to pass `wait` for uninstallation. Good catch. Thank you.
