### ISSUE TITLE
integ-tests-alpha: Can't use full SDKv3 package name in an awsApiCall

### ISSUE THREAD

**Issue by dontirun** [aws/aws-cdk#28844]
### Describe the bug

Using the full SDKv3 package name (as described here https://github.com/aws/aws-cdk/pull/27313) causes the CDK to throw an error when attempting to run a test

### Expected Behavior

Using the full SDKv3 package name does not throw an error

### Current Behavior

The `/` in the full SDKv3 package name causes  the naming constraints for the custom resource type name to errir

```bash
Error: Custom resource type name can only include alphanumeric characters and _@- (DeployAssert@SdkCall@aws-sdk/client-redshift-serverl)
```

### Reproduction Steps

``` ts
import * as integ from '@aws-cdk/integ-tests-alpha';
import * as cdk from 'aws-cdk-lib';

const app = new cdk.App();
const stack = new cdk.Stack();
const test = new integ.IntegTest(app, 'integ', {
  testCases: [stack],
});

const describeUsageLimit = test.assertions.awsApiCall('@aws-sdk/client-redshift-serverless', 'GetUsageLimitCommand' {
  UsageLimitId: 'foo',
});

describeUsageLimit.expect(
  integ.ExpectedResult.objectLike({
    amount: 100,
    breachAction: 'deactivate',
    period: 'monthly',
  }),
);

app.synth();
```

### Possible Solution

Remove the `@aws-sdk/client-` from the full SDKv3 package name when naming the custom resource type

### CDK CLI Version

2.121.0 (build 9f2b78c)

### Node.js Version

v18.15.0

### OS

Osx

### Language

TypeScript

**Comment by dontirun** [comment]
Additionally it looks like having any non alphanumeric characters  `-` in the service name (like with the SDKv3 service name: `redshift-serverless`) 

causes template validation errors with CloudFormation Outputs

```bash
assertions: deploying... [3/3]
assertions: creating CloudFormation changeset...

 ❌  assertions failed: Error [ValidationError]: Template format error: Outputs name 'AssertionResultsAwsApiCallredshift-serverlessGetUsageLimitCommand6e1bf0d7444675e4ba3cb27c0240fd75' is non alphanumeric.
 ```

**Comment by sakurai-ryo** [comment]
Hi @dontirun
Thanks for reaching out!
The problem seems to be that the `resourceType` of `CustomResource` contains a slash.
I will create a PR to fix this.
https://github.com/aws/aws-cdk/blob/efccfcb9fb77207653781457d4dbbd9715443aa0/packages/%40aws-cdk/integ-tests-alpha/lib/assertions/sdk.ts#L100
https://github.com/aws/aws-cdk/blob/efccfcb9fb77207653781457d4dbbd9715443aa0/packages/aws-cdk-lib/core/lib/custom-resource.ts#L211

**Comment by dontirun** [comment]
@sakurai-ryo Thank you! The PR should also fix the second part of the issue that I put in the comments with CloudFormation outputs not supporting `-`

**Comment by sakurai-ryo** [comment]
@dontirun 
Yes, as you wrote in this issue, both need to be fixed.

I just noticed that the documentation says to use SDK v2 to call AWS APIs, but it is probably the same code internally, so it can be fixed.
https://docs.aws.amazon.com/cdk/api/v2/docs/@aws-cdk_integ-tests-alpha.IDeployAssert.html#awswbrapiwbrcallservice-api-parameters-outputpathsspan-classapi-icon-api-icon-experimental-titlethis-api-element-is-experimental-it-may-change-without-noticespan

**Comment by tim-finnigan** [comment]
Thanks for reaching out - based on the discussion here I've marked this as a documentation issue.
