### ISSUE TITLE
(aws-docdb): unsupported snapshot policy although documentation says it should be

### ISSUE THREAD

**Issue by kornicameister** [aws/aws-cdk#28861]
### Describe the bug

#28773 addressed the fact that it is impossible to spin up L2 DocumentDbCluster with retention policy said to Snaphost.
Although that is correct for security group inside (there's an escape hatch in DocumentDbCluster that sets cluster's retention policy onto the group) it turned out that `cdk synth` against `DocumentDbCluster` with a policy == Snaphost and seperately created security group also fails with an error that this time snaphost policy is not possible for `DocumentDbCluster` even though [documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-deletionpolicy.html) says so

### Expected Behavior

It is possible to configure DocumentDBCluster with Snapshot removal policy.

### Current Behavior

It is not possible to configure said cluster with Snapshot removal policy.

### Reproduction Steps

```typescript
#!/usr/bin/env node

import 'source-map-support/register';

import * as cdk from 'aws-cdk-lib';
import * as docdb from 'aws-cdk-lib/aws-docdb';
import * as ec2 from 'aws-cdk-lib/aws-ec2';

const app = new cdk.App();
const stack = new cdk.Stack(app, 'Stack');

const vpc = new ec2.Vpc(stack, 'VPC');
const securityGroup = new ec2.SecurityGroup(stack, 'SG', {
  vpc,
});
new docdb.DatabaseCluster(stack, 'Cluster', {
  vpc,
  removalPolicy: cdk.RemovalPolicy.SNAPSHOT,
  securityGroup,
  instanceType: ec2.InstanceType.of(
    ec2.InstanceClass.A1,
    ec2.InstanceSize.SMALL,
  ),
  masterUser: {
    username: 'admin',
    password: cdk.SecretValue.unsafePlainText('password'),
  },
});

app.synth();
```

### Possible Solution

@lpizzinidev mentioned that there might some sort of a list that needs to be updated to allow *sscce* to synthetize but I have no idea what that is and where that is.

### CDK CLI Version

2.121.1

### Node.js Version

20.8

### OS

MacOS sierra

### Language

TypeScript

### Language Version

5.3

**Comment by GavinZZ** [comment]
I believe the issue is that the [list](https://github.com/aws/aws-cdk/blob/b4630972865a7d7595a0528bed6def38af2e4b1e/packages/%40aws-cdk/core/lib/cfn-resource.ts#L136) here is missing `AWS::DocDB::DBCluster`. Going to draft a PR to add it.

**Comment by kornicameister** [comment]
Wonderful @GavinZZ , thx a lot.
I kinda though this list is something that happens in CloudFormation native code.
Good that was not the case.

**Comment by lpizzinidev** [comment]
@GavinZZ 
I already opened a [PR](https://github.com/aws/aws-cdk/pull/28798) for the fix.

**Comment by GavinZZ** [comment]
@lpizzinidev Noted, I will close my PR. Please in the future assign your self to the issue or linked the issue in your PR to avoid wasted effort. Thank you!

**Comment by lpizzinidev** [comment]
@GavinZZ 
I did as you can see in my PR description.
This issue is a duplicate that was opened after my PR.
Thanks for pointing out 👍

**Comment by kornicameister** [comment]
It is a bit of my fault. I did not notice @lpizzinidev has included the change.

**Comment by lpizzinidev** [comment]
@kornicameister 
No worries. It's better to have two open issues for a bug than none 😉
