### ISSUE TITLE
(integ-runner): (integ runner doesn't work anymore when specifying test files)

### ISSUE THREAD

**Issue by GavinZZ** [aws/aws-cdk#28890]
### Describe the bug

After this PR change, https://github.com/aws/aws-cdk/pull/28770, `integ-runner` doesn't work anymore when specifying test files, i.e. `yarn integ test/aws-apigatewayv2-integrations/test/websocket/integ.aws.t --update-on-failed`.

### Expected Behavior

Should work and run the integration test.

### Current Behavior

```
Invalid values:
  Argument: language, Given: "test/aws-apigatewayv2-integrations/test/websocket/integ.aws.js", Choices: "javascript", "typescript", "python", "go"
```

### Reproduction Steps

Pull latest `main`

### CDK CLI Version

N/A

### Node.js Version

N/A

### OS

N/A

### Language

TypeScript

**Comment by pahud** [comment]
Thank you for the report and PR.
