### ISSUE TITLE
cloudfront: get default distribution metrics

### ISSUE THREAD

**Issue by badmintoncryer** [aws/aws-cdk#28893]
### Describe the feature

CloudFront distributions have [default metrics](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/viewing-cloudfront-metrics.html) available, but there's a need for metricXyz() that can retrieve these as cloudwatch.Metric objects.

### Use Case

Distributions have both additional metrics and default metrics. 
While all [metric retrieval functions are implemented for additional metrics](https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-cloudfront/lib/distribution.ts#L405), it would be very convenient to have similar functions available for default metrics as well.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.123.0

### Environment details (OS name and version, etc.)

irrelevant

**Comment by pahud** [comment]
Thank you for the feature request and we look forward to your PRs.
