### ISSUE TITLE
Another integration: `secretsmanager.ISecretAttachmentTarget`

### ISSUE THREAD

**Issue by rix0rrr** [aws/aws-cdk#2890]

**Comment by skinny85** [comment]
@rix0rrr can you be a little more specific: what needs to be done here?

**Comment by peterwoodworth** [comment]
@rix0rrr @njlynch is this fine sitting in the backlog? going through old feature requests

**Comment by njlynch** [comment]
This looks like it can be closed out. I think closed by #2052
