### ISSUE TITLE
@aws-cdk/aws-s3: Unable to delete the existing S3 event notifications 

### ISSUE THREAD

**Issue by sarangarav** [aws/aws-cdk#28915]
### Describe the bug

I'm facing an issue while trying to delete the existing S3 event notifications.

The problem arises with S3 bucket event notification handler Lambda(AWS CloudFormation handler for "Custom::S3BucketNotifications" resources (@aws-cdk/aws-s3)), where it fails and reports an error: when calling the PutBucketNotificationConfiguration operation: Configuration is ambiguously defined. Cannot have overlapping suffixes in two rules if the prefixes are overlapping for the same event type.

Custom event notification handler reference :  https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/custom-resource-handlers/lib/aws-s3/notifications-resource-handler/index.py

The issue is likely related to the change: https://github.com/aws/aws-cdk/commit/37be7b9b5d2abe04aa5f632a7b78aed3e9c233d8

The offending line is Line 39 - we are updating the ID of a JSON object, but the ID is inside of that object when it comes from outside. (https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/custom-resource-handlers/lib/aws-s3/notifications-resource-handler/index.py#L39)

### Expected Behavior

Should delete the existing event notifications

### Current Behavior

Unable to delete the existing filters: 
Error: when calling the PutBucketNotificationConfiguration operation: Configuration is ambiguously defined. Cannot have overlapping suffixes in two rules if the prefixes are overlapping for the same event type.

### Reproduction Steps

1. Add few event notifications
2. Remove some of the the added notifications.
Please find the example stack attached to reproduce the issue.
[s3-event-notifications.txt](https://github.com/user-attachments/files/15928937/s3-event-notifications.txt)

### CDK CLI Version

2.124.0

### Node.js Version

v20.11.0

### OS

Linux

### Language

TypeScript

**Comment by pahud** [comment]
>Custom event notification handler reference
I am getting a 404 from this link.

Are you able to provide a minimal reproducible code snippets that we can simply copy/paste to reproduce this issue in our environment? That would be very helpful if we share the same code snippets. Thank you.

**Comment by gkaskonas** [comment]
Hi, we are getting this error everytime we update the lambda target.

```
  import { Function as Handler } from "aws-cdk-lib/aws-lambda";
  ...
  const handler = Handler.fromFunctionArn(stack, "Handler", stackLocalArn);
  const bucket = Bucket.fromBucketName(stack, "Bucket", bucketName);
  bucket.addEventNotification(EventType.OBJECT_CREATED_PUT, new LambdaDestination(handler));
  return stack;
```

Every time `stackLocalArn` is updated the stack update fails with this error

```
Received response status [FAILED] from custom resource. Message returned: Error: An error occurred (InvalidArgument) when calling the PutBucketNotificationConfiguration operation: Configurations overlap. Configurations on the same bucket cannot share a common event type.. See the details in CloudWatch Log Stream: 2024/01/29/[$LATEST]099d50dec4ab44dcb5be29f1d1b6e13c (RequestId: 9582e198-4537-479b-b112-b17761fb58a2)
```

Why does it try to create a new notification config instead of updating the existing one? We tried deleting the existing notification config and allowing cf to create a new one but as soon as we update the lambda it fails again.

I think this is related to this change https://github.com/aws/aws-cdk/commit/37be7b9b5d2abe04aa5f632a7b78aed3e9c233d8

**Comment by sarangarav** [comment]
Here is the correct code path :

https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/custom-resource-handlers/lib/aws-s3/notifications-resource-handler/index.py

The issue is likely related to the change: https://github.com/aws/aws-cdk/commit/37be7b9b5d2abe04aa5f632a7b78aed3e9c233d8


We can reproduce this issue when we try to add a new S3 event notifications on top of existing ones.




> > Custom event notification handler reference
> > I am getting a 404 from this link.
> 
> Are you able to provide a minimal reproducible code snippets that we can simply copy/paste to reproduce this issue in our environment? That would be very helpful if we share the same code snippets. Thank you.

**Comment by pahud** [comment]
I was not able to deploy this 

```ts
export class ExampleStack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);

    const handler = this.getDummyHandler();
    const importedHandler = lambda.Function.fromFunctionArn(this, "Handler", handler.functionArn);
    const bucket = s3.Bucket.fromBucketName(this, "Bucket", my_existing_bucket_name);
    bucket.addEventNotification(s3.EventType.OBJECT_CREATED_PUT, new s3n.LambdaDestination(importedHandler));
    new CfnOutput(this, 'importedHandlerArn', { value: importedHandler.functionArn });


  }
  private getDummyHandler(): lambda.Function {
    return new lambda.Function(this, 'Func', {
      code: lambda.Code.fromInline(`def handler(_, _): return {"foo": "bar"} `),
      functionName: 'Func',
      handler: 'index.handler',
      runtime: lambda.Runtime.PYTHON_3_10,
  })
  }
}
```

And the log reads:

```
[ERROR]	2024-02-07T16:42:59.726Z	23d8f18a-c4da-430e-91c3-1f511c22a30d	Failed to put bucket notification configuration
Traceback (most recent call last):
  File "/var/task/index.py", line 24, in handler
    s3.put_bucket_notification_configuration(Bucket=props["BucketName"], NotificationConfiguration=config)
  File "/var/runtime/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/runtime/botocore/client.py", line 960, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidArgument) when calling the PutBucketNotificationConfiguration operation: Unable to validate the following destination configurations
```

Upgrading this issue to p1.

**Comment by Exter-dg** [comment]
I am facing the same issue when adding a new SNS event notification to my already-created S3 bucket. The bucket is created using CDK only.

Error - `An error occurred (InvalidArgument) when calling the PutBucketNotificationConfiguration operation`

```
let bucket = new s3.Bucket(this, "Bucket", {
  bucketName: bucketName
}

// new code
// Fetch SNS topic from ARN
const snsTopic = sns.Topic.fromTopicArn(
  this,
  `snsTopic`,
  "arn"
);

bucket.addEventNotification(
  s3.EventType[eventNotification.eventType as keyof typeof s3.EventType],
  new s3n.SnsDestination(snsTopic)
);
```

**Comment by manmartgarc** [comment]
@Exter-dg check that there's not an existing rule that's referencing a construct that does not exist anymore. If this is the case, recreate the construct (with the same arn) and then delete the notification setting before removing the construct.

**Comment by Exter-dg** [comment]
> @Exter-dg check that there's not an existing rule that's referencing a construct that does not exist anymore. If this is the case, recreate the construct (with the same arn) and then delete the notification setting before removing the construct.

There isn't. This is the first notification that is being added to the bucket

**Comment by manmartgarc** [comment]
> 
> 
> 
> > @Exter-dg check that there's not an existing rule that's referencing a construct that does not exist anymore. If this is the case, recreate the construct (with the same arn) and then delete the notification setting before removing the construct.
> 
> @manmartgarc  There isn't. This is the first notification that is being added to the bucket

When you check the bucket notification configuration, can you verify that there's nothing there?

**Comment by Exter-dg** [comment]
> > > @Exter-dg check that there's not an existing rule that's referencing a construct that does not exist anymore. If this is the case, recreate the construct (with the same arn) and then delete the notification setting before removing the construct.
> > 
> > 
> > @manmartgarc  There isn't. This is the first notification that is being added to the bucket
> 
> When you check the bucket notification configuration, can you verify that there's nothing there?

@manmartgarc yes, it is empty. There are no notifications configured

**Comment by kshefchek** [comment]
I'm also facing this issue when adding additional event notifications to a bucket that already has event notifications with different prefix filters.  I'm wondering if anyone has discovered a workaround that does not require a fix in the cdk module itself?

**Comment by pahud** [comment]
@kshefchek  We have a PR #29022 WIP and will hopefully resolve this issue.

**Comment by kshefchek** [comment]
@pahud thank you!

**Comment by jurkov** [comment]
What can we do, if PR #29022 is closed?

**Comment by GavinZZ** [comment]
> Hi, we are getting this error everytime we update the lambda target.
> 
> ```
>   import { Function as Handler } from "aws-cdk-lib/aws-lambda";
>   ...
>   const handler = Handler.fromFunctionArn(stack, "Handler", stackLocalArn);
>   const bucket = Bucket.fromBucketName(stack, "Bucket", bucketName);
>   bucket.addEventNotification(EventType.OBJECT_CREATED_PUT, new LambdaDestination(handler));
>   return stack;
> ```
> 
> Every time `stackLocalArn` is updated the stack update fails with this error
> 
> ```
> Received response status [FAILED] from custom resource. Message returned: Error: An error occurred (InvalidArgument) when calling the PutBucketNotificationConfiguration operation: Configurations overlap. Configurations on the same bucket cannot share a common event type.. See the details in CloudWatch Log Stream: 2024/01/29/[$LATEST]099d50dec4ab44dcb5be29f1d1b6e13c (RequestId: 9582e198-4537-479b-b112-b17761fb58a2)
> ```
> 
> Why does it try to create a new notification config instead of updating the existing one? We tried deleting the existing notification config and allowing cf to create a new one but as soon as we update the lambda it fails again.
> 
> I think this is related to this change [37be7b9](https://github.com/aws/aws-cdk/commit/37be7b9b5d2abe04aa5f632a7b78aed3e9c233d8)

Hi @gkaskonas, What you're seeing is actually not related to the change you mentioned. After a bit investigation, I notice that you're using imported lambda function. For imported function, we will set the property `canCreatePermission` to false, see [code](https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-lambda/lib/function-base.ts#L269). 

Since this property is set to `false`, then when binding the `LambdaDestination` to s3 event notifications, it will attempt to create lambda permisison (see [code](https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-s3-notifications/lib/lambda.ts#L23)) but failed to create since `canCreatePermissions` is false.

Without necessary permission, creating a s3 event notification will then fail due to `Configurations on the same bucket cannot share a common event type`

**Comment by GavinZZ** [comment]
@Exter-dg I can confirm that I can reproduce the issue. However, one thing I noticed is that the default access policy for SNS topic has the following condition:
```
"Condition": {
        "StringEquals": {
          "AWS:SourceOwner": "649563674902"
        }
      }
```

This seems to be the issue here and causes configuration error. According to the [official documentation](https://docs.aws.amazon.com/AmazonS3/latest/userguide/ways-to-add-notification-config-to-bucket.html#step1-create-sns-topic-for-notification), one of the step is to replace the default access policy with the one they provided which uses 
```
"Condition": {
                "ArnLike": {
                    "aws:SourceArn": "arn:aws:s3:*:*:bucket-name"
                },
                "StringEquals": {
                    "aws:SourceAccount": "bucket-owner-account-id"
                }
            }
```
I tried it out and this time it deploys successfully.

**Comment by GavinZZ** [comment]
To summarize this issue, there are three issues I noticed in the description and comments.
1. When using imported function to configure a lambda destination event for s3 notifications. For imported function, we will set the property canCreatePermission to false, see [code](https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-lambda/lib/function-base.ts#L269). This will result in not creating lambda permission which is necessary to configure the event notification through lambda destination. Without necessary permission, creating a s3 event notification will then fail due to `Unable to validate the following destination configurations`.
2. Issue when using s3 notifications on SNS topic. The default access policy of SNS topic uses `"AWS:SourceOwner"` in the condition. According to the [official documentation](https://docs.aws.amazon.com/AmazonS3/latest/userguide/ways-to-add-notification-config-to-bucket.html#step1-create-sns-topic-for-notification), it requires a different access policy condition, specifically 
```
  "Condition": {
      "ArnLike": {
          "aws:SourceArn": "arn:aws:s3:*:*:bucket-name"
      },
      "StringEquals": {
          "aws:SourceAccount": "bucket-owner-account-id"
      }
  }
```
3. Failure when using the same type of event with overlapping prefix. `Configuration is ambiguously defined. Cannot have overlapping suffixes in two rules if the prefixes are overlapping for the same event type`. This is expected when the prefix is the same for the same event type. My understanding is that this issue itself complains about not able to **_delete_** the stack that is in `CREATE_FAILED` state due to this issue. I cannot seem to reproduce the deletion failure issue. @sarangarav would you be able to provide an example stack that can reproduce this?

**Comment by gkaskonas** [comment]
> > Hi, we are getting this error everytime we update the lambda target.
> > ```
> >   import { Function as Handler } from "aws-cdk-lib/aws-lambda";
> >   ...
> >   const handler = Handler.fromFunctionArn(stack, "Handler", stackLocalArn);
> >   const bucket = Bucket.fromBucketName(stack, "Bucket", bucketName);
> >   bucket.addEventNotification(EventType.OBJECT_CREATED_PUT, new LambdaDestination(handler));
> >   return stack;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Every time `stackLocalArn` is updated the stack update fails with this error
> > ```
> > Received response status [FAILED] from custom resource. Message returned: Error: An error occurred (InvalidArgument) when calling the PutBucketNotificationConfiguration operation: Configurations overlap. Configurations on the same bucket cannot share a common event type.. See the details in CloudWatch Log Stream: 2024/01/29/[$LATEST]099d50dec4ab44dcb5be29f1d1b6e13c (RequestId: 9582e198-4537-479b-b112-b17761fb58a2)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Why does it try to create a new notification config instead of updating the existing one? We tried deleting the existing notification config and allowing cf to create a new one but as soon as we update the lambda it fails again.
> > I think this is related to this change [37be7b9](https://github.com/aws/aws-cdk/commit/37be7b9b5d2abe04aa5f632a7b78aed3e9c233d8)
> 
> Hi @gkaskonas, What you're seeing is actually not related to the change you mentioned. After a bit investigation, I notice that you're using imported lambda function. For imported function, we will set the property `canCreatePermission` to false, see [code](https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-lambda/lib/function-base.ts#L269).
> 
> Since this property is set to `false`, then when binding the `LambdaDestination` to s3 event notifications, it will attempt to create lambda permisison (see [code](https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-s3-notifications/lib/lambda.ts#L23)) but failed to create since `canCreatePermissions` is false.
> 
> Without necessary permission, creating a s3 event notification will then fail due to `Unable to validate the following destination configurations`

It works fine when creating the notification config the first time (permissions are fine) so not sure what changes when updating it.
We are migrating to EventBridge because this is taking too long

**Comment by sarangarav** [comment]
> To summarize this issue, there are three issues I noticed in the description and comments.
> 
> 1. When using imported function to configure a lambda destination event for s3 notifications. For imported function, we will set the property canCreatePermission to false, see [code](https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-lambda/lib/function-base.ts#L269). This will result in not creating lambda permission which is necessary to configure the event notification through lambda destination. Without necessary permission, creating a s3 event notification will then fail due to `Unable to validate the following destination configurations`.
> 2. Issue when using s3 notifications on SNS topic. The default access policy of SNS topic uses `"AWS:SourceOwner"` in the condition. According to the [official documentation](https://docs.aws.amazon.com/AmazonS3/latest/userguide/ways-to-add-notification-config-to-bucket.html#step1-create-sns-topic-for-notification), it requires a different access policy condition, specifically
> 
> ```
>   "Condition": {
>       "ArnLike": {
>           "aws:SourceArn": "arn:aws:s3:*:*:bucket-name"
>       },
>       "StringEquals": {
>           "aws:SourceAccount": "bucket-owner-account-id"
>       }
>   }
> ```
> 
> 3. Failure when using the same type of event with overlapping prefix. `Configuration is ambiguously defined. Cannot have overlapping suffixes in two rules if the prefixes are overlapping for the same event type`. This is expected when the prefix is the same for the same event type. My understanding is that this issue itself complains about not able to **_delete_** the stack that is in `CREATE_FAILED` state due to this issue. I cannot seem to reproduce the deletion failure issue. @sarangarav would you be able to provide an example stack that can reproduce this?

Sure.. Please find the example stack attached.
[s3-event-notifications.txt](https://github.com/user-attachments/files/15928927/s3-event-notifications.txt)

**Comment by GavinZZ** [comment]
Re-opening as the original fix has a bug in the Feature flag implementation.
