### ISSUE TITLE
Bootstrapping: Security Hub Findings incorrectly refer to Sid: PipelineCrossAccountArtifactsBucket

### ISSUE THREAD

**Issue by FarrOut** [aws/aws-cdk#28924]
### Describe the issue

# Overview
The *Concepts > Bootstrapping* page of the Dev guide has a section on [Security Hub Findings](https://docs.aws.amazon.com/cdk/v2/guide/bootstrapping.html#bootstrapping-securityhub). This sections makes an incorrect reference to a policy statement in the deployment role (*cdk-hnb659fds-deploy-role-ACCOUNT-REGION*).

# Example
Under the paragraph starting with **What if I want to fix this finding?**

> If you are not using AWS CDK Pipelines for cross-account deployments: remove the statement with Sid: PipelineCrossAccountArtifactsBucket from the deploy role; or
>
> If you are using AWS CDK Pipelines for cross-account deployments: after deploying your AWS CDK Pipeline, look up the AWS KMS Key ARN of the Artifact Bucket and replace the Resource: * of the Sid: PipelineCrossAccountArtifactsBucket statement with the actual Key ARN.

# Problem
Sid: PipelineCrossAccountArtifacts**Bucket**

Confirmed by inspecting deployment role....generated by ```CDK version 2.124.0 (build 4b6724c)```

```
        {
            "Condition": {
                "StringEquals": {
                    "kms:ViaService": "s3.us-west-1.amazonaws.com"
                }
            },
            "Action": [
                "kms:Decrypt",
                "kms:DescribeKey",
                "kms:Encrypt",
                "kms:ReEncrypt*",
                "kms:GenerateDataKey*"
            ],
            "Resource": "*",
            "Effect": "Allow",
            "Sid": "PipelineCrossAccountArtifactsKey"
        },
```

# Proposed Correction

[Security Hub Findings](https://docs.aws.amazon.com/cdk/v2/guide/bootstrapping.html#bootstrapping-securityhub) should refer to ...Sid: PipelineCrossAccountArtifacts**Key**

### Links

[Security Hub Findings](https://docs.aws.amazon.com/cdk/v2/guide/bootstrapping.html#bootstrapping-securityhub)

**Comment by vinayak-kukreja** [comment]
Thank you for the report. 

I believe if CDK Pipelines are not being used for cross account deployments, then we should delete both `PipelineCrossAccountArtifactsKey` and `PipelineCrossAccountArtifactsBucket` from the [template](https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml#L457-L489).

We can update documentation related to this.

**Comment by vinayak-kukreja** [comment]
Hey thank you for letting us know about this issue. 

The documentation has now been updated: https://docs.aws.amazon.com/cdk/v2/guide/bootstrapping.html#bootstrapping-securityhub
