### ISSUE TITLE
route53: support for multivalue answer routing

### ISSUE THREAD

**Issue by badmintoncryer** [aws/aws-cdk#28939]
### Describe the feature

Route53 can configure [multivalue answer routing](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/routing-policy-multivalue.html).
I want to specify `multiValueAnswer` parameter from RecordSet class.

### Use Case

When configuring multi-value answer routing, it is always necessary to set it via the L1.

### Proposed Solution

Add `multiValueAnswer` property to RecordSetProps.

```ts
    new route53.RecordSet(this, 'MultiValueAnswerRouting', {
      zone: hostedZone,
      recordName: 'www',
      target: route53.RecordTarget.fromIpAddresses('1.2.3.4'),
      multiValueAnswer: true, // add
    });
```

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.123.0

### Environment details (OS name and version, etc.)

irrelevant

**Comment by pahud** [comment]
Yes I guess we could just expose this property to the surface
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-route53-recordset.html#cfn-route53-recordset-multivalueanswer
