### ISSUE TITLE
ALB: DELETE_FAILED 'AWS::ElasticLoadBalancingV2::ListenerRuleRate exceeded

### ISSUE THREAD

**Issue by Aeolun** [aws/aws-cdk#28965]
### Describe the bug

When deploying my CDK stack, I'll randomly get the following errors:

```
0/97 | 6:39:42 AM | DELETE_FAILED        | AWS::ElasticLoadBalancingV2::ListenerRule | listenerRule3A5ACB178 Resource handler returned message: "Error occurred during operation 'AWS::ElasticLoadBalancingV2::ListenerRuleRate exceeded (Service: ElasticLoadBalancingV2, Status Code: 400, Request ID: 06e67a1b-0782-467f-ba16-5a3a00b14eac)'." (RequestToken: bdfbcf77-2cba-866f-1cf1-e3cd3289479f, HandlerErrorCode: GeneralServiceException)
```

It's not like I'm doing anything really exciting here. I have a parent stack with a bunch of sub stacks (40), that each try to create (or delete) their listener rule on a common ALB at more or less the same time.

I do not think 40 request per second on a whole AWS account should be very uncommon (assuming that the request all even happen in the same second).

### Expected Behavior

I expect this to succeed without running into rate limits.

### Current Behavior

Rate limit issues will randomly appear when either deleting or adding rules.

### Reproduction Steps

Create a CDK stack with 40 substacks, that each add a rule to an ALB listener in the parent stack (I test deletion issues by tearing down the stack).

### Possible Solution

- Have a burst limit on that API call in addition to the general limit.
- Have no limits on calls from CloudFormation (really, why is that a thing?)
- Retry the deletion if it fails the first time around

### CDK CLI Version

2.124.0 (build 4b6724c)

### Node.js Version

v20.10.0

### OS

MacOSX Ventura

### Language

TypeScript

### Language Version

5.3.3

**Comment by pahud** [comment]
Unfortunately this is not a CDK bug and a limit on CDK or CFN but we appreciate your use case sharing. I am not sure if this is a hard limit from service API's perspective.

Does it only happen when you have 40 substacks(nested stacks I assume) with each creating a listener rule at the same time? What if you create some dependency between those stacks as a workaround?
