### ISSUE TITLE
cloudwatch: support the new data table widget

### ISSUE THREAD

**Issue by humanzz** [aws/aws-cdk#28975]
### Describe the feature

Add support for the newly released data table widget https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/add_remove_table_dashboard.html

### Use Case

Leverage data table widget in CloudWatch Dashboards

### Other Information

The full schema is not yet posted in documentation at https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/CloudWatch-Dashboard-Body-Structure.html

I’ve asked CW team to update this page so work in CDK can be based off of that

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.125.0

### Environment details (OS name and version, etc.)

macOS

**Comment by pahud** [comment]
Thank you and we look forward to your pull request.
