### ISSUE TITLE
feat(aws-eks): add support for EKS version 1.29

### ISSUE THREAD

**Issue by awsdataarchitect** [aws/aws-cdk#28983]
### Describe the feature

Amazon EKS announced support for Kubernetes version 1.29

https://aws.amazon.com/blogs/containers/amazon-eks-now-supports-kubernetes-version-1-29/

CDK support for aws_eks.KubernetesVersion would be needed to mark this feature as complete

Kubectl lambda layer is waiting approval to  [support v1.29 ](https://github.com/cdklabs/awscdk-asset-kubectl/pull/546)

### Use Case

EKS Blueprints deployed from cdk need to be manually upgraded to v1.29 

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.115.0

### Environment details (OS name and version, etc.)

macOS Sonoma 14.1

**Comment by pahud** [comment]
Awesome! Thank you!

**Comment by ebizboy** [comment]
Thank you
