### ISSUE TITLE
CustomResource update problem

### ISSUE THREAD

**Issue by andreadisimone** [aws/aws-cdk#28999]
### Describe the bug

I have a CustomResource, implementing a Sagemaker StudioLifecycleConfig.
I use a aws_lambda.Function as a handler for the Provider.

The lambda code contains the bash scripts that define the Lifecycle, converts them to base64 and handles the creation/deletion/update of the Lifecycle using boto3 calls. Since Lifecycle are immutable, on update I delete and recreate the existing Lifecycle.

After initial deployment, I change the bash scripts defining the Lifecycle and redeploy.

### Expected Behavior

When I change the bash scripts within the lambda, the desired outcome would be that the CustomResource realizes it needs to be updated and triggers the Provider with an Update event.

### Current Behavior

No changes are detected.
Is this intended? What is the recommended way to update a CustomResource each time the code underlying its Provider changes?

### Reproduction Steps

Can't really past code here. I hope the explanation is clear enough to at least confirm if this behavior is intended, and possibly provide guidance on how to achieve the desired outcome instead.

### CDK CLI Version

2.115.0

### Node.js Version

18.17.1

### OS

linux

### Language

Python

**Comment by andreadisimone** [comment]
An update here, just to help others with the same problem in the future.

After some trial and error, I found out that the CustomResource decides if it needs updating or not only based on its props. Any change in props will trigger an update. Any change in the code backing up the Provider will not. So my solution is to pass the base64 encoding of the bash script in the props, rather than preparing it in the lambda.

I guess now that I know this, the design makes sense. My only suggestion to the developers is maybe to improve the class documentation to add this information.

Unless of course the devs think this is a bug and I am completely misunderstanding the current behavior.

**Comment by pahud** [comment]
Did you use the [custom resource framework](https://github.com/aws/aws-cdk/tree/main/packages/aws-cdk-lib/custom-resources) to create your own Provider and pass to CustomResource class or you just write your own native lambda function with bash and handle the onCreate/onUpdate/onDelete yourself? Can you share a little bit about your code snippets?

**Comment by andreadisimone** [comment]
@pahud thanks for your reply. on a high level, here is what I do:

```
on_event=lambda_.Function(self, "a_name", code=lambda_.Code.from_asset("a_path"), **other_args)
on_event.add_to_role_policy(a_policy_statement)

provider = Provider(self, "provider_name", on_event_handler=on_event)

CustomResource(self, "resource_name", service_token=provider.service_token, properties=**props)
```

**Comment by pahud** [comment]
```
on_event=lambda_.Function(self, "a_name", code=lambda_.Code.from_asset("a_path"), **other_args)
```

As I didn't see your code I can't see what's going on there but generally, if you change any code lambda uses, CDK would detect that and update the lambda function for you.

**Comment by bestickley** [comment]
@pahud, unfortunately this is not true in that the lambda function will not run again when the code changes:

> but generally, if you change any code lambda uses, CDK would detect that and update the lambda function for you.

CloudFormation will update the Lambda function but the custom resource won't update unless the props change. Workaround:

```ts
new CustomResource(
      this,
      "InitOpenSearchCustomResource",
      {
        serviceToken: provider.serviceToken,
        properties: {
          hash: (fn.node.findChild("Code") as Asset).assetHash,
        },
      },
    );
```
