### ISSUE TITLE
Environments

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#290]
Model environments as arbitrary names given to some method of getting credentials to an AWS account:
* AWS profile name
* Some source of AWS credentials
  * Profiles
  * AWS Organizations
  * Some other way (pluggable)

They can be modeled in `cdk.json` files (although maybe AWS profiles don't need to me "copied" in there - they're discoverable already).

Environments may also include additional context values, too.

* Allow using AWS SDK Profiles and AWS Organizations to map to different environments

__The CDK team have discussed this design__

**Comment by fulghum** [comment]
From Romain – minimum bar would be letting users specify different AWS credentials profiles for different stacks in an app.

**Comment by eladb** [comment]
This is going to be addressed as part of the CI/CD project (copy: @rix0rrr)
