### ISSUE TITLE
region-info: GovCloud missing Deep Learning Container Repository Account

### ISSUE THREAD

**Issue by scottschreckengaust** [aws/aws-cdk#29024]
### Describe the bug

The Deep Learning Container (DLC) Elastic Container Repository (ECR) are missing for the two GovCloud regions:

1. `us-gov-west-1`
2. `us-gov-east-1`

However, from [How Amazon Elastic Container Registry Differs for AWS GovCloud (US)](https://docs.aws.amazon.com/govcloud-us/latest/UserGuide/govcloud-ecr.html#govcloud-ecr-diffs):
> [Amazon ECR public registries](https://docs.aws.amazon.com/AmazonECR/latest/public/public-registries.html) aren't supported.

### Expected Behavior

An AWS Account for the DLC ECR path:

https://docs.aws.amazon.com/sagemaker/latest/dg-ecr-paths/ecr-us-gov-east-1.html
https://docs.aws.amazon.com/sagemaker/latest/dg-ecr-paths/ecr-us-gov-west-1.html

### Current Behavior

> Error: region-info: don't know dlcRepositoryAccount for region us-gov-west-1. Use 'Fact.register' to provide this value.

and

> Error: region-info: don't know dlcRepositoryAccount for region us-gov-east-1. Use 'Fact.register' to provide this value.

### Reproduction Steps

`bin/testing_fact_name.ts`:
```typescript
#!/usr/bin/env node
import 'source-map-support/register';
import { App } from 'aws-cdk-lib';
import { TestingFactNameStack } from '../lib/testing_fact_name-stack';

const app = new App();
new TestingFactNameStack(app, 'TestingFactNameStack', {
   env: { account: process.env.CDK_DEFAULT_ACCOUNT, region: process.env.CDK_DEFAULT_REGION },
});
```

`lib/testing_fact_name-stack.ts`:
```typescript
import { Stack, StackProps } from 'aws-cdk-lib';
import { Construct } from 'constructs';
import { FactName, IFact, Fact } from 'aws-cdk-lib/region-info';

export class TestingFactNameStack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);
    console.log(`${this.region}`);
    const stack = Stack.of(this);
    const dlcRepositoryAccount = (() => {
      try {
        return stack.regionalFact(FactName.DLC_REPOSITORY_ACCOUNT);
      }
      catch (e) {
        console.error(e);
        return null;
      }
    })();
    console.log(`${FactName.DLC_REPOSITORY_ACCOUNT}=${dlcRepositoryAccount}`);
  }
}
```

### Possible Solution

Create a stack to create a GovCloud ECR repository that copies all DLC images mimicking a public repository.

### CDK CLI Version

2.126.0 (build fb74c41)

### Node.js Version

v20.11.0

### OS

macOS 14.3 (23D56)

### Language

TypeScript

### Language Version

TypeScript (5.3.3)

**Comment by pahud** [comment]
I don't have the access to GovCloud regions but according the provided [doc](https://docs.aws.amazon.com/sagemaker/latest/dg-ecr-paths/ecr-us-gov-east-1.html), the images seem to be shared in the private ECR repos.

What are you trying to do with that using CDK? Can you share some code snippet and the error messages?

**Comment by mgwidmann** [comment]
For those coming to this issue later, I was able to get past this error with the following code added before trying to use any sagemaker constructs.

```typescript
   Fact.register({
      name: 'dlcRepositoryAccount',
      region: Stack.of(this).region,
      value: '442386744353',
    });
```
