### ISSUE TITLE
ApplicationLoadBalancedFargateService : Add Support for IPv6 on LB's

### ISSUE THREAD

**Issue by jlouk** [aws/aws-cdk#29039]
### Describe the feature

I would like to enable IPv6 support on the load balancers created by ApplicationLoadBalancedFargateService and ApplicationLoadBalancedEc2Service.

Ideally this could be used as a new property for these two classes.``

### Use Case

With the introduction of AWS charging for public IPv4 addresses ([source](https://aws.amazon.com/blogs/aws/new-aws-public-ipv4-address-charge-public-ip-insights)), I am looking to enable IPv6 addresses on my ECS ALBs.

### Proposed Solution

In the `elbv2.ApplicationLoadBalancer` class, there is a property for ipv6: 
```
new elbv2.ApplicationLoadBalancer(stack, 'ALB', {
  vpc,
  internetFacing: true,
  ipAddressType: elbv2.IpAddressType.DUAL_STACK,
});
```

My proposal would be to add the property `ipAddressType` to ApplicationLoadBalancedFargateService and ApplicationLoadBalancedEc2Service with the corresponding actions to enable when necessary. The default would be `elbv2.IpAddressType.IPV4` which would make this an opt-in service.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.126.0

### Environment details (OS name and version, etc.)

MacOS Monterey 12.7

**Comment by pahud** [comment]
We welcome the PRs and before that I guess we could always doing [escape hatches](https://docs.aws.amazon.com/cdk/v2/guide/cfn_layer.html) using addPropertyOverride() to achieve that.

**Comment by jmnarloch** [comment]
@pahud Do you think you could review the Application Load Balancer PR(https://github.com/aws/aws-cdk/pull/30089#issuecomment-2201231428)? I would like to enable IPv6 Load Balancer in my production stack. I can also give the PR a first review.

**Comment by pahud** [comment]
@jmnarloch  I've escalated this PR review to the team. The maintainer should take a look shortly. Thank you for letting me know.
