### ISSUE TITLE
(Bootstrap stack): (Abort failed multipart upload after 7 days)

### ISSUE THREAD

**Issue by nikhil-zadoo** [aws/aws-cdk#29045]
### Describe the feature

Enable lifecycle rule to abort multipart uploads after 7 days for assets bucket rolled out with CDK bootstrap.

### Use Case

I realized the configuration after trusted advisor rolled out a new check. Reference : https://docs.aws.amazon.com/awssupport/latest/user/cost-optimization-checks.html#s3-incomplete-multipart-upload-abort-config

Makes sense that any failed multipart uploads are deleted after 7 days. This is to ensure that the failed parts don't unnecessarily take up s3 space and cause costs.

### Proposed Solution

Enable lifecycle rule to delete failed multipart uploads in case of s3 assets bucket rolled out with cdk bootstrap.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.114.1

### Environment details (OS name and version, etc.)

MACOS, LINUX

**Comment by pahud** [comment]
This is an awesome feature! Thank you and we look forward to your upcoming PR.

**Comment by nikhil-zadoo** [comment]
https://github.com/aws/aws-cdk/pull/29046 is created for the issue
