### ISSUE TITLE
aws_cdk: Add support for description to aws_cdk.ExportValueOptions

### ISSUE THREAD

**Issue by toxygene** [aws/aws-cdk#29092]
### Describe the feature

`aws_cdk.ExportValueOptions` currently does not expose a property for setting the description of the `CfnOutput` it creates.

https://github.com/aws/aws-cdk/blob/c3c771c6f6f6790f2298a85a549bded640d2e35b/packages/aws-cdk-lib/core/lib/stack.ts#L1762

### Use Case

I would like to be able to set the description of the `CfnOutput` created when using `aws_cdk.Stack.exportValue` and `aws_cdk.Stack.exportStringListValue`.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.114.1 (build 02bbb1d)

### Environment details (OS name and version, etc.)

MacOS 14.3.1

**Comment by pahud** [comment]
According to the [doc](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html), `Export` only supports `Name`.  Can you share some code sample or snippets that you expect ?

**Comment by toxygene** [comment]
My request is that the `CfnOutput` created by `aws_cdk.Stack.exportValue` and `aws_cdk.Stack.exportStringListValue` add support for setting the `Description` of the CloudFormation output.

For example:
```
aws_cdk.Stack.exportValue("test", {
  "description": "the description for the value",
  "name": "testing"
})
```
would produce:
```
Outputs:
  [...]:
    Description: the description for the value
    Value: test
    Export:
      Name: testing
```
