### ISSUE TITLE
(ec2): BastionHost deviceName example is wrong

### ISSUE THREAD

**Issue by rantoniuk** [aws/aws-cdk#29103]
### Describe the bug

The [example listed in the documentation](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ec2.BastionHostLinux.html) renders:
```
1:27:28 PM | CREATE_FAILED        | AWS::EC2::Instance                    | BastionHost30F9ED05
Invalid device name EBSBastionHost (Service: AmazonEC2; Status Code: 400; Error Code: InvalidBlockDeviceMapping; Request ID: 3bd4a132-0230-4769-8ef5-5ceaa559ad36; P
roxy: null)
```

The proposed `deviceName` does not align [with the supported ones](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/device_naming.html).

Additionally:
```
volume: ec2.BlockDeviceVolume.ebs(10, { encrypted: true }),
```
has an implicit volumeType default of GP2, while it should now be GP3 by default if not specified.

### Expected Behavior

The example from documentation should work when copy-pasted.

### Current Behavior

As above.

### Reproduction Steps

As above.

### CDK CLI Version

2.127.0 (build 6c90efc)

### Node.js Version

v18.18.2

### OS

MacOS

### Language

TypeScript

**Comment by rantoniuk** [comment]
@msambol any thoughts about GP2 vs GP3 default?

**Comment by hoegertn** [comment]
> @msambol any thoughts about GP2 vs GP3 default?

Changing this might lead to recreation of disks and is a breaking change. So only possible with feature flags.

**Comment by rantoniuk** [comment]
@hoegertn so I understand that you're going to add a new feature flag for this so that newly created instances are actually following the current AWS platform defaults without explicitly setting this, right? 
If there a related issue I can watch regarding this, I'd be interested to subscribe to it!

**Comment by hoegertn** [comment]
The implementation of BastionHost and Instance that it uses internally currently does not specify the volume type but uses the CloudFormation default. So, if this should be changed, that needs to be implemented and then guarded by a feature flag to not break existing users. I'm not sure if this is planned currently.

**Comment by rantoniuk** [comment]
Ah! I assumed it was internally hardcoded as a default in aws-cdk and wasn't aware it's coming from CloudFormation - so it would need actually an update on the platform side for the [Cloudformation default to be updated](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-volume.html) to be updated.
Thanks for the info!
