### ISSUE TITLE
aws-sqs: Cannot add permission to existing SQS queue

### ISSUE THREAD

**Issue by Exter-dg** [aws/aws-cdk#29102]
### Describe the bug

I am unable to add permissions to a **imported** SQS queue

```typescript
mySqs = Queue.fromQueueArn(this, 'MyQ');
myTopic = new Topic(this, 'MyTopic');

// Add permissions
mySqs.addToResourcePolicy(new iam.PolicyStatement({
    resources: [mySqs.queueArn],
    actions: ["sqs:SendMessage"],
    principals: [new iam.ServicePrincipal("sns.amazonaws.com")],
    conditions: {
        "ArnEquals": {
            "aws:SourceArn": myTopic.topicArn
        }
    }
}))

myTopic.addSubscription(new SqsSubscription(mySqs));
```

### Expected Behavior

Policy should be added to SQS

### Current Behavior

When I add the policy statement, CDK DIFF shows no change

### Reproduction Steps

code

### CDK CLI Version

2.123.0

### Node.js Version

v16.20.2

### OS

Linux/UNIX

### Language

TypeScript

**Comment by pahud** [comment]
It does not support imported queue as described here.

https://github.com/aws/aws-cdk/blob/a21731c9b1f34525433fbee668ebb2321debf5b8/packages/aws-cdk-lib/aws-sqs/lib/queue-base.ts#L154-L160

**Comment by jeichhorn** [comment]
It would be great if this would be implemented. It was already requested in #10040 https://github.com/aws/aws-cdk/issues/10040
