### ISSUE TITLE
awscdk-kubectl-go: KubectlLayer modules out of date, broken by Python 3.7 runtime removal

### ISSUE THREAD

**Issue by jaredhancock31** [aws/aws-cdk#29123]
### Describe the bug

Python 3.7 runtime support was recently dropped. 

For those who use aws-cdk-go, we have to import separate KubectlLayers after K8s 1.21. But these layers are extremely outdated, and now broken. 

1.25 example: https://github.com/cdklabs/awscdk-kubectl-go/blob/kubectl.25/kubectlv25/go.mod#L7

they all use aws-cdk 2.28 and are still on Go 1.18.

We use aws-cdk-go and these layer libraries in production, so this prevents any stack updates until we hack a workaround or new tags are pushed in the cdklabs repo.

### Expected Behavior

EKS cluster stack should successfully be created

### Current Behavior

stack fails with errors like

`Embedded stack XXXX-awscdkawseksKubectlProviderNestedStackawscdkawseksKubectlPro-XXXXXX was not successfully created: The following resource(s) failed to create: [Handler886CB40B]`

`"The runtime parameter of python3.7 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (python3.12) while creating or updating functions. "`

when checking the rendered cloudformation it looks like this:

```json
   "Role":"arn:aws:iam::REDACTED-HandlerServiceRoleFCDC14A-REDACTED",
   "MemorySize":"1024",
   "Runtime":"python3.7",
   "Description":"onEvent handler for EKS kubectl resource provider",
   "Timeout":"900",
   "Handler":"index.handler",
   "Code":{
      "S3Bucket":"REDACTED",
      "S3Key":"REDACTED.zip"
   },
   "Layers":[
      "arn:aws:lambda:REDACTED:layer:AwsCliLayerF44AAF94:58",
      "arn:aws:lambda:REDACTED:layer:KubectlV25Layer182E5352:29"
   ]
```

### Reproduction Steps

create an awseks.Cluster construct with kubectl layer like so:

```go
props := &awseks.ClusterProps{
    KubectlLayer = getKubectlLayer(stack, version)
}

cluster := awseks.NewCluster(stack, jsii.String("EKSCluster"), props)
```

```go
import (
	layer22 "github.com/cdklabs/awscdk-kubectl-go/kubectlv22/v2"
	layer23 "github.com/cdklabs/awscdk-kubectl-go/kubectlv23/v2"
	layer24 "github.com/cdklabs/awscdk-kubectl-go/kubectlv24/v2"
	layer25 "github.com/cdklabs/awscdk-kubectl-go/kubectlv25/v2"
)

func getKubectlLayer(stack awscdk.Stack, k8sVersion string) awslambda.LayerVersion {
	switch k8sVersion {
	case "1.22":
		return layer22.NewKubectlV22Layer(stack, jsii.String("KubectlV22Layer"))
	case "1.23":
		return layer23.NewKubectlV23Layer(stack, jsii.String("KubectlV23Layer"))
	case "1.24":
		return layer24.NewKubectlV24Layer(stack, jsii.String("KubectlV24Layer"))
	case "1.25":
		return layer25.NewKubectlV25Layer(stack, jsii.String("KubectlV25Layer"))
	}
	return nil
}
```

### Possible Solution

update libs at https://github.com/cdklabs/awscdk-kubectl-go

### CDK CLI Version

2.80.0

### Node.js Version

18

### OS

Mac/Linux

### Language

Go

### Language Version

1.20

**Comment by pahud** [comment]
Thank you for the report. We'll investigate this and take actions to get it fixed.

**Comment by moelasmar** [comment]
If you want to use the latest supported Python version (python 3.12), you can upgrade the `aws-cdk-go` library, and use the latest version (`v2.128.0`) and keep using old `awscdk-kubectl-go` library, and then you will be able to use Python 3.12 for your Lambda function.

See the following snippets:
```
\\ go.mod

module app_kubectl_go

go 1.18

require (
	github.com/aws/aws-cdk-go/awscdk/v2 v2.128.0
	github.com/aws/constructs-go/constructs/v10 v10.1.33
	github.com/aws/jsii-runtime-go v1.76.0
	github.com/cdklabs/awscdk-kubectl-go/kubectlv25/v2 v2.0.4
)
``` 
```
// app_kubectl_go.go
....
func NewAppKubectlGoStack(scope constructs.Construct, id string, props *AppKubectlGoStackProps) awscdk.Stack {
	var sprops awscdk.StackProps
	if props != nil {
		sprops = props.StackProps
	}
	stack := awscdk.NewStack(scope, &id, &sprops)
	baseDir, err := os.Getwd()

	if err != nil {
		fmt.Println("Failed to get current working directory", err)
		return nil
	}

	fn := lambda.NewFunction(stack, jsii.String("MyFunction"), &lambda.FunctionProps{
		Runtime: lambda.Runtime_PYTHON_3_12(),
		Handler: jsii.String("index.handler"),
		Code:    lambda.Code_FromAsset(jsii.String(filepath.Join(baseDir, "code")), nil),
	})

	fn.AddLayers(layer.NewKubectlV25Layer(stack, jsii.String("KubectlV25Layer")))

	return stack
}
```

synthesized template:
```
{
 "Resources": {
  "MyFunction3BAA72D1": {
   "Type": "AWS::Lambda::Function",
   "Properties": {
    "Code": {
     "S3Bucket": {
      "Fn::Sub": "cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}"
     },
     "S3Key": "6496abe9c6f32f60e58f0e56455ba87c91b27f052e4e9fdfa642ff85339a2521.zip"
    },
    "Handler": "index.handler",
    "Layers": [
     {
      "Ref": "KubectlV25Layer182E5352"
     }
    ],
    "Role": {
     "Fn::GetAtt": [
      "MyFunctionServiceRole3C357FF2",
      "Arn"
     ]
    },
    "Runtime": "python3.12"
   },
   "DependsOn": [
    "MyFunctionServiceRole3C357FF2"
   ],
   "Metadata": {
    "aws:cdk:path": "AppKubectlGoStack/MyFunction/Resource",
    "aws:asset:path": "asset.6496abe9c6f32f60e58f0e56455ba87c91b27f052e4e9fdfa642ff85339a2521",
    "aws:asset:is-bundled": false,
    "aws:asset:property": "Code"
   }
  },
  "KubectlV25Layer182E5352": {
   "Type": "AWS::Lambda::LayerVersion",
   "Properties": {
    "Content": {
     "S3Bucket": {
      "Fn::Sub": "cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}"
     },
     "S3Key": "ebc48a9a74e277f463f78c5a0b3bcf489a891efe25ece75b5b439b9e89bee4ac.zip"
    },
    "Description": "/opt/kubectl/kubectl 1.25; /opt/helm/helm 3.11",
    "LicenseInfo": "Apache-2.0"
   },
   "Metadata": {
    "aws:cdk:path": "AppKubectlGoStack/KubectlV25Layer/Resource",
    "aws:asset:path": "asset.ebc48a9a74e277f463f78c5a0b3bcf489a891efe25ece75b5b439b9e89bee4ac.zip",
    "aws:asset:is-bundled": false,
    "aws:asset:property": "Content"
   }
  }
 }
}
```

**Comment by moelasmar** [comment]
@jaredhancock31, I hope my answers help address your concerns.

**Comment by jaredhancock31** [comment]
re: your first reply - we don't make our own lambda layer , we just import the AWS-published ones and plug it into the cluster construct. Up til now there was never a need to implement our own kubectl layer in order for EKS stacks to function.

The guidance we got was to upgrade to the latest CDK, but unfortunately that's a large jump for us and it will take some time to fully test all the changes in latest. In general it was just a surprise to us that the code we import from AWS repos suddenly stopped working.

**Comment by jaredhancock31** [comment]
@moelasmar we're going to proceed in trying to get caught up to latest CDK. Not sure how we can avoid situations like this in the future, but I suppose since there's a path forward we can close this.

**Comment by moelasmar** [comment]
you can still use the latest python runtime without upgrading your CDK version
```
runtime := lambda.NewRuntime(jsii.String("python3.12"), lambda.RuntimeFamily_PYTHON, &lambda.LambdaRuntimeProps{
		SupportsInlineCode:        jsii.Bool(true),
		SupportsCodeGuruProfiling: jsii.Bool(true),
	})

	fn := lambda.NewFunction(stack, jsii.String("MyFunction"), &lambda.FunctionProps{
		Runtime: runtime,
		Handler: jsii.String("index.handler"),
		Code:    lambda.Code_FromAsset(jsii.String(filepath.Join(baseDir, "code")), nil),
	})
```

**Comment by moelasmar** [comment]
Thanks @jaredhancock31 for raising this issue. I will mark this issue as closed. If you have any more concerns or questions, please open a new issue.
