### ISSUE TITLE
aws-stepfunctions: DistrbituedMap itemReader get bucket and key at runtime from state input

### ISSUE THREAD

**Issue by tonerm43** [aws/aws-cdk#29136]
### Describe the feature

When creating a DistributedMap in the console, I can get the bucket and key from state input at runtime.

Currently in the CDK implementation, I can only use a static bucket and key.

### Use Case

My step function sends bucket and key as input to a distributed map

### Other Information

You can use CustomState as a workaround:
```
ItemReader: {
  Parameters: {
    'Bucket.$': '$.bucket',
    'Key.$': '$.key'
  }
}
```

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

1.128.0

### Environment details (OS name and version, etc.)

4.14, Amazon Linux 2, x86_64

**Comment by pahud** [comment]
Thank you and we will be happy to review the PR to move this forward.

**Comment by nguyentoanit** [comment]
Any updates on this issue?

**Comment by ot-brad-steiner** [comment]
I also need this functionality

**Comment by tonerm43** [comment]
This appears to be solved by https://github.com/aws/aws-cdk/pull/31619
