### ISSUE TITLE
aws_cdk.aws_kinesisfirehose.CfnDeliveryStream: buffering hints size_in_m_bs example incorrect.

### ISSUE THREAD

**Issue by Outrun207** [aws/aws-cdk#29138]
### Describe the issue

The example for the [aws_cdk.aws_kinesisfirehose](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_kinesisfirehose.html) CfnDeliveryStream buffering hints construct/object incorrectly:

```
buffering_hints_property = kinesisfirehose.CfnDeliveryStream.BufferingHintsProperty(
    interval_in_seconds=123,
    size_in_mBs=123
)
```

"size_in_mBs" is incorrect. 

It needs to be fixed to read: 
```
buffering_hints_property = kinesisfirehose.CfnDeliveryStream.BufferingHintsProperty(
    interval_in_seconds=123,
    size_in_m_bs=123
)
```

### Links

https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_kinesisfirehose/CfnDeliveryStream.html#aws_cdk.aws_kinesisfirehose.CfnDeliveryStream.BufferingHintsProperty

**Comment by msambol** [comment]
Looks like a doc generation issue..

**Comment by pahud** [comment]
I can't find any example in [aws_cdk.aws_kinesisfirehose](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_kinesisfirehose.html). Is it correct link?

**Comment by msambol** [comment]
@pahud This doc: https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_kinesisfirehose/CfnDeliveryStream.html#aws_cdk.aws_kinesisfirehose.CfnDeliveryStream.BufferingHintsProperty
