### ISSUE TITLE
aws-codepipeline: add `executionMode` property to Pipeline

### ISSUE THREAD

**Issue by go-to-k** [aws/aws-cdk#29147]
### Describe the feature

CloudFormation already supports `executionMode`, which can also be supported by CDK.

https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-resource-codepipeline-pipeline.html#cfn-codepipeline-pipeline-executionmode

### Use Case

We would be good to add a new parameter for execution mode.

### Proposed Solution

Add an `executionMode` parameter to the `PipelineProps` interface.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.128.0

### Environment details (OS name and version, etc.)

MacOS 13.0

**Comment by pahud** [comment]
Thank you @go-to-k !
