### ISSUE TITLE
null values are not allowed in templates when ResultPath=JsonPath.DISCARD

### ISSUE THREAD

**Issue by ck-on-github** [aws/aws-cdk#29164]
### Describe the bug

I am using the Python CDK to generate a CloudFormation template in json format.

`cdk deploy` of  the json CloudFormation template generated using the code snippet:

```
StepFunctionsStartExecution(
    ...
    result_path=JsonPath.DISCARD
    ...
)
```

fails with 

```
[/Resources/CfTemplate747CB3D5/Type/DefinitionString/Fn::Join/1/33] 'null' values are not allowed in templates
```

on  aws-cdk-lib=2.70.0

### Expected Behavior

Before aws-cdk-lib=2.70.0, the ResultPath in the json template looks like:

`\"ResultPath\": null,`

and CDK deploy succeeds.

### Current Behavior

After aws-cdk-lib=2.70.0, the ResultPath in the json template looks like:

```
\"ResultPath\": \"",
       null, 
 "\",
```

and CDK deploy fails with `'null' values are not allowed in templates`.

### Reproduction Steps

CDK version 2.70.0 or higher.

### CDK CLI Version

2.70.0

### Node.js Version

18.18.2

### OS

Linux

### Language

Python

### Language Version

3.8.17

**Comment by pahud** [comment]
Can you share a minimal full sample of your code that we can run in our environment? It's probably related to https://github.com/aws/aws-cdk/pull/28661 but we need more details about it.

**Comment by ck-on-github** [comment]
this was due to converting the StateGraph instance to json with json.dumps instead of using Stack.to_json_string.

**Comment by sdasgupta-spectra** [comment]
Having the same issue with cdk `2.1023.0 (build 45ceb89)` attempting to deploy a Step Functions state machine with `"ResultPath": null. Also tried passing in JsonPath.DISCARD, but evaluated to null and threw the same error: 

```
ValidationError: [...] 'null' values are not allowed in templates
```
