### ISSUE TITLE
Error message "Possible EventEmitter memory leak detected."

### ISSUE THREAD

**Issue by nomike** [aws/aws-cdk#29176]
### Describe the bug

When I'm, running CDK my terminal get's spamed with these errors:

```plaintext
(node:110573) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
```

### Expected Behavior

These error should not be displayed.

### Current Behavior

see above

### Reproduction Steps

Happens every time I run `cdk deploy`.

### CDK CLI Version

2.128.0 (build d995261)

### Framework Version

2.126.0

### Node.js Version

v20.5.1

### OS

Ubuntu 22.04.3 LTS - WSL

### Language

Python

### Language Version

Python 3.10.12

### Other information

My CDK code is quite huge.

If you can not easily reproduce this let me know please. I might work on constructing a simpler example then which I am actually able to share.

**Comment by pahud** [comment]
Thank you for the report. Any chance you could share a tiny repo that we can check out and reproduce it in our local environment?
