### ISSUE TITLE
(cdk migrate): wrong migration of "special character" JSON Keys ("application/json" -> applicationJson)

### ISSUE THREAD

**Issue by jwoehrle** [aws/aws-cdk#29216]
### Describe the bug

I'm using CDK migrate to create a CDK app for my already deployed CloudFormation Stack.

The CFN template contains an `AWS::ApiGateway::Method` with the following property:

```
"RequestModels": {
          "application/json": {
            "Ref": "ApiGatewayMethodHelloPostApplicationJsonModel"
          }
        }
```

note the `/` in the JSON key of `application/json`

This gets migrated into the following L1 construct code:

```
requestModels: {
        applicationJson: apiGatewayMethodHelloPostApplicationJsonModel.ref,
      },
```

which after synth gives us:

```
      RequestModels:
        applicationJson:
          Ref: ApiGatewayMethodHelloPostApplicationJsonModel
```

which fails the `cdk deploy` with the following message

failed: Error: The stack named serverless-project-dev failed to deploy: UPDATE_ROLLBACK_FAILED (The following resource(s) failed to update: [ApiGatewayMethodHelloPost]. ): Resource handler returned message: "Validation Result: warnings : [], errors : [Invalid content type specified: applicationJson] (Service: ApiGateway, Status Code: 400, Request ID: 26885dad-a6cb-45a2-8640-53bddad60568)" (RequestToken: d7151781-c4b7-8fae-7545-49b6c1c2eaa2, HandlerErrorCode: InvalidRequest), Resource handler returned message: "Invalid Method identifier specified (Service: ApiGateway, Status Code: 404, Request ID: f25f0c89-6591-41fc-bf0b-33382df1b91f)" (RequestToken: 1ec85c11-87f6-7ced-b3a5-a1018561425f, HandlerErrorCode: NotFound)
...

when I change `applicationJson` to `"application/json"` (enclosed in `"`) the deployment succeeds

### Expected Behavior

deployment succeeds and JSON properties are not changed between original CFN stack and resulting/migrated CDK/CFN stack

### Current Behavior

quoted String `"application/json"` gets changed to `applicationJson` (not quoted)

### Reproduction Steps

see above CFN snippet

### CDK CLI Version

2.128.0 (build d995261)

### Node.js Version

v20.9.0

### OS

macOS

### Language

TypeScript

### Language Version

~5.3.3

**Comment by TheRealAmazonKendra** [comment]
The fix for this was released in v2.132.
