### ISSUE TITLE
aws-lambda: LoggingConfig is not supported in us-gov-east-1.

### ISSUE THREAD

**Issue by ssshahri** [aws/aws-cdk#29227]
### Describe the bug

Even after building in [release v2.125.0](https://github.com/aws/aws-cdk/releases/tag/v2.125.0), I still see this issue when trying to create Lambda.
```
Resource handler returned message: "LoggingConfig is not supported in us-gov-east-1. Remove LoggingConfig value from your request and try again (Service: Lambda, Status Code: 400, Request ID: 3ac89cff-8a9c-4d23-845b-790cb1069268)" (RequestToken: ba4e6739-c3ea-10b0-4dc3-8d1fd0b2583d, HandlerErrorCode: InvalidRequest)
```

### Expected Behavior

We've built in new release, and don't specify `LoggingConfig` on creation of Lambda so not sure why we're still seeing this error.

### Current Behavior

Error in stack creation
```
Resource handler returned message: "LoggingConfig is not supported in us-gov-east-1. Remove LoggingConfig value from your request and try again (Service: Lambda, Status Code: 400, Request ID: 3ac89cff-8a9c-4d23-845b-790cb1069268)" (RequestToken: ba4e6739-c3ea-10b0-4dc3-8d1fd0b2583d, HandlerErrorCode: InvalidRequest)
```

### Reproduction Steps

N/A

### Additional Information/Context

AWS Internal Slack Message with more details: https://amzn-wwc.slack.com/archives/C01853SDU7N/p1708647464531339

Similar issue: https://github.com/aws/aws-cdk/issues/28919
Original fix: https://github.com/aws/aws-cdk/pull/28934

### CDK CLI Version

^2.125.0

### Node.js Version

18.x

### OS

N/A

### Language

TypeScript

### Language Version

Typescript ~4.5.5

**Comment by ssshahri** [comment]
I think we might be specify some kind of log configuration via a customer resource. Not able to get help here considering I can't link internal amazon code. Closing out.

**Comment by ssshahri** [comment]
re-opening and providing some sample code, to show we don't use Log configs in our Lambda CustomProvider
```
        const onEventHandler = new lambda.Function(this,
            `{lambdaName}-${stackSuffix}`,
            {
                runtime: lambda.Runtime.NODEJS_12_X,
                code: lambdaHandlerCode,
                handler: props.onEventHandler,
                vpc: Vpc,
                timeout: cdk.Duration.seconds(30)
            });

        const isCompleteHandler = new lambda.Function(this,
            `{LambdaName}-${stackSuffix}`,
            {
                runtime: lambda.Runtime.NODEJS_12_X,
                code: lambdaHanlderCode,
                handler: props.isCompleteHandler,
                vpc: Vpc,
                timeout: cdk.Duration.minutes(1)
            });

        const provider = new cr.Provider(this,
            `Provider-${stackSuffix}`,
            {
                onEventHandler: onEventHandler,
                isCompleteHandler: isCompleteHandler,
                queryInterval: cdk.Duration.minutes(2),
                totalTimeout: cdk.Duration.minutes(60)
            });

const customResource = new cdk.CustomResource(
            this,
            `customResource-${(new Date()).toLocaleString()}`,
            {
                serviceToken: provider.serviceToken,
                properties: {
                    ...bunch of properties
                }
            })
```

**Comment by ssshahri** [comment]
Just looked at a template in non-us-gov region and found that there was LoggingConfig there. If I don't specify in my CDK code, that means it's auto-generated in template right? How do I avoid getting this error?

**Comment by pahud** [comment]
I think it should have been reverted https://github.com/aws/aws-cdk/pull/28934

I am using 2.130.0 now and my code like

```ts
export class DummyStack extends Stack {
  constructor(scope: Construct, id: string, props: StackProps) {
    super(scope, id, props);

    const stackSuffix = 'foo';
    const dummyFunction = getLambdaFunction(this);

    const provider = new cr.Provider(this,
      `Provider-${stackSuffix}`,
      {
          onEventHandler: dummyFunction,
          isCompleteHandler: dummyFunction,
          queryInterval: Duration.minutes(2),
          totalTimeout: Duration.minutes(60)
      });

    const customResource = new CustomResource(
      this,
      `customResource-${(new Date()).toLocaleString()}`,
      {
          serviceToken: provider.serviceToken,
      })
  }
}
```

I didn't see `LoggingConfig` when I `cdk synth`.

Feel free to ping me internally if you need any check.

**Comment by ssshahri** [comment]
Ok apologies, I was looking at old commit, we recently pushed commit that used LogGroup on customProvider. Writing in conditional to fix.
