### ISSUE TITLE
(apigatewayv2): expose a way to enable logging

### ISSUE THREAD

**Issue by rantoniuk** [aws/aws-cdk#29220]
### Describe the feature

[ApiGateway exposes](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_apigateway.RestApi.html#deployoptions) `deployOptions` that permits to enable logging easily:
```ts
const api = new apigateway.RestApi(this, 'API', {
       restApiName: 'BackendApi',
       deployOptions: {
         accessLogDestination: new apigateway.LogGroupLogDestination(logGroup),
         accessLogFormat: apigateway.AccessLogFormat.clf(),
         loggingLevel: apigateway.MethodLoggingLevel.INFO,
       },
});
```

However, ApiGatewayv2 does not. Looking at [default Stage](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_apigatewayv2.HttpApi.html#defaultstage) also doesn't seem to make it possible.

### Use Case

Easily enable cloudwatch logs via HttpApi props.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.129.0

### Environment details (OS name and version, etc.)

MacOS

**Comment by rantoniuk** [comment]
After long search, I found out [how to use use CfnApiGatewayManagedOverrides](
https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_apigatewayv2.CfnApiGatewayManagedOverrides.html), but doing this:

```ts
 const api = new cdk.aws_apigatewayv2.HttpApi(this, 'HttpProxyPrivateApi', {
      apiName: 'BackendApi',
      defaultIntegration: new HttpAlbIntegration('DefaultIntegration', listener, { vpcLink }),
    });

    // Create a CloudWatch Log Group for storing access logs
    const logGroup = new LogGroup(this, 'ApiGatewayAccessLogs', {
      logGroupName: '/watchdog/apigw/backend/access_log',
      retention: RetentionDays.THREE_MONTHS,
    });

    // Grant write access to the API Gateway service to write to the log group
    logGroup.grantWrite(new ServicePrincipal('apigateway.amazonaws.com'));

    new cdk.aws_apigatewayv2.CfnApiGatewayManagedOverrides(this, 'ApiGatewayOverrides', {
      apiId: api.apiId,
      stage: {
        accessLogSettings: {
          destinationArn: logGroup.logGroupArn,
        },
      },
    });

```

renders:

```
 ❌  ApiGw-Stack failed: Error: The stack named ApiGw-Stack failed to deploy: UPDATE_ROLLBACK_COMPLETE: ApiGatewayManagedOverrides can only be associated to APIs created via quick create (Service: null; Status Code: 0; Error Code: null; Request ID: null; Proxy: null) (Service: null; Status Code: 404; Error Code: BadRequestException; Request ID: null; Proxy: null)
```

**Comment by tim-finnigan** [comment]
Thanks for the feature request, it looks like this may be a duplicate of https://github.com/aws/aws-cdk/issues/11100 - can you confirm?

**Comment by rantoniuk** [comment]
Closing as duplicate.
