### ISSUE TITLE
aws_cdk.aws_cloudtrail.Trail: KMS encryption kms_key example incorrect

### ISSUE THREAD

**Issue by ayankowsky** [aws/aws-cdk#29222]
### Describe the issue

The example for [aws_cdk.aws_cloudtrail.Trail](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_cloudtrail/Trail.html) provides an incorrect example of setting an encryption key:

```
trail = cloudtrail.Trail(self, "myCloudTrail",
    send_to_cloud_watch_logs=True,
    kms_key=my_key_alias
)
```

`kms_key` is incorrect and should be changed to `encryption_key`:

```
trail = cloudtrail.Trail(self, "myCloudTrail",
    send_to_cloud_watch_logs=True,
    encryption_key=my_key_alias
)
```

### Links

https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_cloudtrail/Trail.html

**Comment by tim-finnigan** [comment]
Thanks for reporting, looks like it should be `encryption_key` in that example.
