### ISSUE TITLE
aws-lambda: DockerImageCode.fromImageAsset not caching as-expected

### ISSUE THREAD

**Issue by mccauleyp** [aws/aws-cdk#29240]
### Describe the bug

I have a simple Dockerfile: 

```
FROM public.ecr.aws/lambda/python:3.11

# Copy requirements.txt separately and run `pip install` first to facilitate build caching
COPY requirements.txt .
RUN pip install --upgrade pip && \
    pip install -r ./requirements.txt

COPY handlers ${LAMBDA_TASK_ROOT}/handlers
```
If I build this outside of CDK, the caching works as-expected in that the `RUN pip install` command only runs if `requirements.txt` changes, otherwise the cache is used. 

When I build it inside CDK, e.g.:
```
        self.my_function = aws_lambda.DockerImageFunction(
            scope,
            "MyLambda",
            code=aws_lambda.DockerImageCode.from_image_asset(
                platform=aws_ecr_assets.Platform.LINUX_AMD64,
                directory="/path/to/dockerfile/dir/,
                cmd=["handlers.entrypoint.handler"],
            ),
        )
``` 
The `pip install` re-runs any time the code changes, event if `requirements.txt` is unchanged. I'm guessing that's related to the `Dockerfile`, `requirements`, and app code all being part of the same new asset, e.g.:
```
- cdk.out/
- - asset.___/
- - - handlers/
- - - Dockerfile
- - - requirements.txt
```

Is it possible to refactor the CDK code to allow caching? Is there a way for me to merge two assets in a single build, so the Dockerfile and requirements.txt don't get duplicated in a new hash?

### Expected Behavior

CDK docker build caches in the same way as outside of CDK. 

### Current Behavior

CDK build requires rerunning lengthy steps.

### Reproduction Steps

See above.

### CDK CLI Version

2.128.0

### Node.js Version

v20.11.0

### OS

OSX

### Language

Python

**Comment by pahud** [comment]
>The pip install re-runs any time the code changes

What is the code you mentioned? Is it the python code in your docker directory or the CDK code?


I just tested this

```ts
    new lambda.DockerImageFunction(this, 'MyLamsbda', {
      code: lambda.DockerImageCode.fromImageAsset(
        path.join(__dirname, '../docker.d/python.d'),
      ),
      memorySize: 256,
    })
```

And my Dockerfile like

```
FROM public.ecr.aws/lambda/python:3.11

# Copy requirements.txt separately and run `pip install` first to facilitate build caching
COPY requirements.txt .
RUN pip install --upgrade pip && \
    pip install -r ./requirements.txt

# COPY handlers ${LAMBDA_TASK_ROOT}/handlers
COPY index.py ${LAMBDA_TASK_ROOT}/index.py
```

I modified the index.py and I saw the `pip install` is actually cached.

```
#7 [3/4] RUN pip install --upgrade pip &&     pip install -r ./requirements.txt
#7 CACHED
```

**Comment by mccauleyp** [comment]
@pahud Thanks for looking into this! I was talking about the Python code, and you tested it in the way I intended. I'm still seeing my CDK builds not use the cache while a regular build does, but your test suggests that it's probably something specific to my environment, so I'll close this and try to sort that out. Thanks!
