### ISSUE TITLE
aws-ecs: `Cluster.fromClusterAttributes` does not properly set `autoScalingGroup`

### ISSUE THREAD

**Issue by cheruvian** [aws/aws-cdk#29241]
### Describe the bug

`Cluster.fromClusterAttributes` does not properly set `autoScalingGroup`

### Expected Behavior

`autoScalingGroup` to be set

### Current Behavior

Is `undefined` which leads to NPEs.

### Reproduction Steps

```
    const vpc   = new Vpc(this, 'Vpc', {});
    const cluster = Cluster.fromClusterAttributes(this, 'Cluster', {
      clusterName: 'my-cluster',
      vpc,
      securityGroups: [],
      autoscalingGroup: new AutoScalingGroup(this, 'Asg', {
        vpc,
        instanceType: InstanceType.of(InstanceClass.A1, InstanceSize.MICRO),
        machineImage: MachineImage.latestAmazonLinux2(),
      }),
    });
    cluster.autoscalingGroup!.addUserData('yum install -y aws-cli');
```

### Possible Solution

All `ClusterAttribute`s should get set on the `ImportCluster`.

### CDK CLI Version

2.126.0

### Node.js Version

v20.10.0

### OS

OSX

### Language

TypeScript

**Comment by cheruvian** [comment]
Workaround for anyone interested:

```
    (this.cluster as any).autoscalingGroup = this.autoScalingGroup;
```

**Comment by tim-finnigan** [comment]
Thanks for reporting this issue and noting the workaround! Looks like the PR linked above (https://github.com/aws/aws-cdk/pull/29244) was created to address this issue.
