### ISSUE TITLE
@aws-cdk/integ-tests-alpha: SingletonFunctions used for test assertions should set a CloudWatch log group retention policy

### ISSUE THREAD

**Issue by jvalore-medallia** [aws/aws-cdk#29260]
### Describe the feature

Currently if you perform a test like

```
import { ExpectedResult, IntegTest } from '@aws-cdk/integ-tests-alpha';

const integ = new IntegTest(app, 'Example', {
  testCases: [testStack],
  assertionStack: new cdk.Stack(app, 'assertions', { synthesizer }),
});

const invoke = integ.assertions.invokeFunction({
  functionName: 'some:lambda:arn',
  payload: '{}'
});
```

The stack deletes itself after a test, but CloudWatch log groups named like
```
/aws/lambda/assertions-SingletonFunction{random id}
```
and are set to never expire, so end up cluttering up your aws account and need manual cleanup.

### Use Case

Test results are not needed forever and should have some default retention policy, or at least a way to set them.

### Proposed Solution

Include a default retention policy for `SingletonFunction` CloudWatch log groups.

### Other Information

nodejs dependencies:
```
    "@aws-cdk/integ-runner": "^2.129.0-alpha.0",
    "@aws-cdk/integ-tests-alpha": "2.129.0-alpha.0",
    "aws-cdk": "2.129.0",
```

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.129.0

### Environment details (OS name and version, etc.)

Mac. Node 20. cdk 2.129.0

**Comment by pahud** [comment]
I guess this is because by default lambda.Function will create a built-in log group that never expires unless a custom loggroup is specified [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-function-loggingconfig.html#cfn-lambda-function-loggingconfig-loggroup).

Yes it would be great to have the log retention policy support for that.
