### ISSUE TITLE
aws-cdk-lib/aws-rds/DatabaseCluster: DatabaseCluster.instanceEndpoints does not return writer endpoints

### ISSUE THREAD

**Issue by steffenjambit** [aws/aws-cdk#29279]
### Describe the bug

The DatabaseCluster.instanceEndpoints only returns the reader endpoints but not the writer endpoints, while DatabaseCluster.instanceIdentifiers returns identifiers for both. 

### Expected Behavior

According to the documentation I would expect both endpoints return the information for all instances: 
<img width="400" alt="Screenshot 2024-02-27 at 14 45 39" src="https://github.com/aws/aws-cdk/assets/93670184/16eed5eb-c5de-4f0f-8885-8acfca06e104">

i.e. DatabaseCluster.instanceEndpoints should return writer and reader endpoints. 

### Current Behavior

DatabaseCluster.instanceEndpoints only returns the reader endpoints but not the writer endpoints

### Reproduction Steps

```
const clusterProps:DatabaseClusterProps = {
     …,
     writer: ClusterInstance.serverlessV2('writer'),
     readers: [ClusterInstance.serverlessV2('reader')],
     …
};
```

```
databaseCluster = new DatabaseCluster(
    this,
   `${id}`,
     {
       ...clusterProps,
        credentials: Credentials.fromSecret(secret),
     },
);
```

```
databaseCluster.instanceEndpoints
```

### Possible Solution

the writer endpoint should be added to instanceEndpoints here: https://github.com/aws/aws-cdk/blob/f3d74bb78189ec6b76cfa85c97d993c1b26c1cac/packages/aws-cdk-lib/aws-rds/lib/cluster.ts#L716
<img width="700" alt="Screenshot 2024-02-27 at 14 53 30" src="https://github.com/aws/aws-cdk/assets/93670184/492f13e6-66d4-4829-a6e9-000b2d100a93">

### CDK CLI Version

2.130.0

### Node.js Version

v18.17.1

### OS

Mac

### Language

TypeScript

**Comment by pahud** [comment]
According to this

https://github.com/aws/aws-cdk/blob/f3d74bb78189ec6b76cfa85c97d993c1b26c1cac/packages/aws-cdk-lib/aws-rds/lib/cluster.ts#L718-L733

Only reader endpoints are returned and writer's is missing.
