### ISSUE TITLE
cdk: not simple to get older versions of the documentation

### ISSUE THREAD

**Issue by cmatKhan** [aws/aws-cdk#29271]
### Describe the issue

this section:

https://docs.aws.amazon.com/cdk/v2/guide/getting_started.html#getting_started_learn_more

provides a link to the API. However, I cannot figure out how to get older versions of the API docs.

### Links

https://docs.aws.amazon.com/cdk/api/v2/python/

**Comment by tim-finnigan** [comment]
Thanks for reaching out - this feature request has come up a few times before, and is currently being tracked in https://github.com/aws/aws-cdk/issues/11172. In the meantime, you can see what functionality was added for each release on this page: https://github.com/aws/aws-cdk/releases, or view [commits](https://github.com/aws/aws-cdk/commits/v2.130.0) to see the changes.
