### ISSUE TITLE
aws-stepfunctions: state.Retry is not iterable

### ISSUE THREAD

**Issue by abdelnn** [aws/aws-cdk#29274]
### Describe the bug

When creating a CustomState within a state machine, and specifying the retry behaviour within the inline definition, we get back an error saying `state.Retry is not iterable`. However, adding the retry behaviour separately with `.addRetry` seems to fix this issue. I strongly suspects this is linked to the following PR #28793 

### Expected Behavior

The state machine should create successfully

### Current Behavior

Throws
```
TypeError: state.Retry is not iterable
    at CustomState.toStateJson
```

### Reproduction Steps

Creating a state machine with the following state

```        
const myLambdaState: sfn.CustomState = new sfn.CustomState(this, 'Call Lambda', {
            stateJson: {
                Type: "Task",
                Resource: "arn:aws:states:::lambda:invoke",
                OutputPath: "$.Payload",
                Parameters: {
                    'Payload.$': "$",
                    "FunctionName": "arn:aws:lambda:us-east-1:<<ACCOUNT>>:function:print1:$LATEST"
                },
                Retry: [
                    {
                        "ErrorEquals": [
                            "Lambda.ServiceException",
                            "Lambda.AWSLambdaException",
                            "Lambda.SdkClientException",
                            "Lambda.TooManyRequestsException"
                        ],
                        "IntervalSeconds": 1,
                        "MaxAttempts": 3,
                        "BackoffRate": 2
                    }
                ],
                Catch: [
                    {
                        ErrorEquals: [
                            "States.ALL"
                        ],
                        Next: "fail.id"
                    }
                ]
                ,
            }
        });
```

However, doing the following works:
```
      const success: sfn.Succeed = new sfn.Succeed(this, 'Success Name');
        const fail: sfn.Fail = new sfn.Fail(this, 'Fail Name');

        const myLambdaState: sfn.CustomState = new sfn.CustomState(this, 'Call Lambda', {
            stateJson: {
                Type: "Task",
                Resource: "arn:aws:states:::lambda:invoke",
                OutputPath: "$.Payload",
                Parameters: {
                    'Payload.$': "$",
                    "FunctionName": "arn:aws:lambda:us-east-1:<<ACCOUNT-ID>>:function:print1:$LATEST"
                }
            }
        });
        myLambdaState.addRetry({
            maxAttempts: 1,
            maxDelay: cdk.Duration.seconds(5),
            jitterStrategy: sfn.JitterType.FULL,
        });

        myLambdaState.addCatch(fail, {
            errors: ['States.ALL']
        }
        )
        myLambdaState.next(success);
```

### CDK CLI Version

2.128.0

### Node.js Version

v21.6.2

### OS

Mac 14.3.1

### Language

TypeScript

**Comment by jsayres** [comment]
The problem seems to be here: https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-stepfunctions/lib/states/custom-state.ts#L74

`renderRetryCatch` can yield a value of `undefined` for `Retry` if the list of retries is empty. You can see this in the `renderList` function: https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-stepfunctions/lib/states/state.ts#L641

This will cause the `state` value to have a `Retry` of `undefined` from the merge. Then the attempt to iterate fails here: https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-stepfunctions/lib/states/custom-state.ts#L79

The solution would be to make the merge a bit smarter and also to validate `state.Retry`.

**Comment by abdelnn** [comment]
I agree - which is probably why we're not getting an error when specifying the error strategy through `.addRetry`

**Comment by abhi-shek01** [comment]
In which file do we need to make this change? I am getting a same error with "aws-cdk-lib" : "^2.118.0" version

**Comment by wong-a** [comment]
@abhi-shek01 The fix was released in the most recent version of aws-cdk https://github.com/aws/aws-cdk/releases/tag/v2.133.0
