### ISSUE TITLE
(bootstrap): Incomplete information 

### ISSUE THREAD

**Issue by evgenyka** [aws/aws-cdk#29307]
### Describe the issue

On the page: 
`If the environment is bootstrapped, do not delete and recreate the environment's bootstrap stack. Deleting the bootstrap stack will delete the AWS resources that were originally provisioned in the environment to support CDK deployments. This will cause the pipeline to stop working. Instead, try to update the bootstrap stack to a new version by running the CDK CLI cdk bootstrap command again.`

There is no explanation why the pipeline will stop working nor recovery procedure for it.

### Links

https://docs.aws.amazon.com/cdk/v2/guide/bootstrapping.html

**Comment by vinayak-kukreja** [comment]
We have added more documentation for this scenario: 
* https://docs.aws.amazon.com/cdk/v2/guide/bootstrapping.html#bootstrapping-env-pipelines-protect
* https://docs.aws.amazon.com/cdk/v2/guide/cdk_pipeline.html#cdk-pipeline-protect
* https://docs.aws.amazon.com/cdk/v2/guide/ref-cli-cmd-bootstrap.html#ref-cli-cmd-bootstrap-options-termination-protection
