### ISSUE TITLE
RestApi: support modifying api key source to ApiKeySourceType.AUTHORIZER

### ISSUE THREAD

**Issue by mbenita-Cyberark** [aws/aws-cdk#29309]
### Describe the feature

Currently `RestApi` construct does not support adjusting the `ApiKeySourceType` property.
This is supported via the `RestApiProps` in other RestApi constructs such as `LambdaRestApi` via the props settings.
In the console this feature is available inside API Settings -> API key source.

Please add this functionality in some way.
Thanks

![image](https://github.com/aws/aws-cdk/assets/76062747/cc0ce302-2576-4fdc-b63a-3110f6e1ffd7)
 

### Use Case

We work with api gateway usage-plan. the api-key is extracted by the lambda authorizer.
Currently we had to build a custom resource to implement this.

Thanks very much

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.129.0

### Environment details (OS name and version, etc.)

Python cdk

**Comment by pahud** [comment]
Thank you for the feat request and we welcome the pull requests from the community.

**Comment by nmussy** [comment]
I'm not sure I understand the issue, `RestApiProps` does have the `apiKeySourceType` property, and it is deployed properly:

```ts
import { ApiKeySourceType, RestApi } from "aws-cdk-lib/aws-apigateway";

const restApi = new RestApi(this, 'RestApi', {
  apiKeySourceType: ApiKeySourceType.AUTHORIZER,
});
restApi.root.addMethod("ANY");
```

![image](https://github.com/aws/aws-cdk/assets/2505696/8cad45e3-39bc-4597-8b43-069f2dec7022)
![image](https://github.com/aws/aws-cdk/assets/2505696/3300d2ee-497b-41d7-b3c8-b898fecaf4e5)

**Comment by mbenita-Cyberark** [comment]
Sorry
