### ISSUE TITLE
(stepfunction-tasks): eventbridge scheduler create, update schedule 

### ISSUE THREAD

**Issue by cshields236** [aws/aws-cdk#29351]
### Describe the feature

Would love an implementation of the Eventbridge Scheduler as a task so we could move away from using custom task integrations. It's available on the AWS console as an option.  
 
Thanks!

https://aws.amazon.com/blogs/compute/introducing-amazon-eventbridge-scheduler/

### Use Case

I'm always frustrated when I see an integration on the console drag and drop and then go to add it to my existing CDK projects to see its not supported and needs to be a custom task. 

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

v2.131.0

### Environment details (OS name and version, etc.)

OSX14.3.1

**Comment by pahud** [comment]
Yeah I guess it should be possible. We welcome any PRs for this.

**Comment by badmintoncryer** [comment]
@cshields236 I’ll try to implement it later!
