### ISSUE TITLE
(aws-glue-alpha): S3 path specified in `--spark-event-logs-path` needs to end with slash

### ISSUE THREAD

**Issue by moomindani** [aws/aws-cdk#29356]
### Describe the bug

When only bucket is provided for spark event log path in job, the s3 path does not end with slash.
It is accepted in job API, but it does not work on actual Spark UI.

### Expected Behavior

S3 path specified in `--spark-event-logs-path` ends with slash

### Current Behavior

S3 path specified in `--spark-event-logs-path` does not end with slash in case only bucket is provided but prefix is not provided

### Reproduction Steps

```
      sparkUI: {
        enabled: true,
      },
```

### Possible Solution

Add trailing slash when it does not end with slash

### CDK CLI Version

2.131.0

### Node.js Version

20.11.1

### OS

macOS Ventura 13.6.4

### Language

TypeScript

**Comment by tim-finnigan** [comment]
Thanks for reaching out and creating the PR - it looks like there is already some [feedback](https://github.com/aws/aws-cdk/pull/29357#pullrequestreview-1915787000) that is awaiting a response.
