### ISSUE TITLE
aws cdk synth results in NEW folder under /tmp every time a command is run, which results to 100% disk space usage over time

### ISSUE THREAD

**Issue by piotrwalczak1** [aws/aws-cdk#29368]
### Describe the bug

I am using WSL 2 with Ubuntu distro. Every time I run cdk synth, the cdk.out file is saved in /tmp folder. Over time, the user is surprised that he has no space left on the disk. Investigation of this took hours, and finally it occurred that cdk synth saving files to /tmp is the issue.

### Expected Behavior

I guess this should have some limit at least if it really do need to save it there.

### Current Behavior

Out of disk space over time

### Reproduction Steps

Have a project. Run cdk synth 1000 times.

### CDK CLI Version

2.128.0

### Node.js Version

20.x

### OS

Ubuntu WSL 2

### Language

TypeScript

### Language Version

5.1.6

**Comment by nmussy** [comment]
Would you be able to give us a minimal reproduction application? I am able to get something similar to what you're describing, but only if my stack contains a `CustomResource`s, e.g. `BucketDeployment`:

```sh
$ cdk synth
$ ls -t $TMPDIR | head
cdk-custom-resourceav715a
cdk-custom-resourcenjXTtG
```

https://github.com/aws/aws-cdk/blob/2378635ae278eb4c2f05ef1302c8737009022dc8/packages/aws-cdk-lib/core/lib/custom-resource-provider/custom-resource-provider-base.ts#L232-L233

**Comment by pahud** [comment]
yes please share some code snippet. The `cdk.out` should be created in your cdk project root unless you specify `-o` to /tmp.
