### ISSUE TITLE
(aws_rds): (Add Support for RDS Oracle 19.0.0.0.ru-2024-01.rur-2024-01.r1 and 21.0.0.0.ru-2024-01.rur-2024-01.r1 in OracleEngineVersion)

### ISSUE THREAD

**Issue by ayushrawat007** [aws/aws-cdk#29360]
### Describe the feature

As per the RDS Doc: both RDS Oracle 19.0.0.0.ru-2024-01.rur-2024-01.r1 and 21.0.0.0.ru-2024-01.rur-2024-01.r1 are supported.

https://docs.aws.amazon.com/AmazonRDS/latest/OracleReleaseNotes/oracle-version-21-0.html#oracle-version-RU-RUR.21.0.0.0.ru-2024-01.rur-2024-01.r1
https://docs.aws.amazon.com/AmazonRDS/latest/OracleReleaseNotes/oracle-version-19-0.html#oracle-version-RU-RUR.19.0.0.0.ru-2024-01.rur-2024-01.r1

However the same is not reflected in the [OracleEngineVersion](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_rds.OracleEngineVersion.html#class-oracleengineversion) class.

Hence requesting to add the support for the same.

### Use Case

To be able to define RDS Oracle 19.0.0.0.ru-2024-01.rur-2024-01.r1 and 21.0.0.0.ru-2024-01.rur-2024-01.r1 via Static property value like the rest of the RDS Oracle versions.

Workaround: [static of(oracleFullVersion, oracleMajorVersion)](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_rds.OracleEngineVersion.html#static-oforaclefullversion-oraclemajorversion) is know to us.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.131.0

### Environment details (OS name and version, etc.)

Mac

**Comment by pahud** [comment]
Yes we should add that into the [enum-like class](https://github.com/aws/aws-cdk/blob/9c82bcaf90a1dc2df324a72ea622c7eec729d0f5/packages/aws-cdk-lib/aws-rds/lib/instance-engine.ts#L1453).

**Comment by nmussy** [comment]
I'm currently working on a tool to help detect these kinds of drifts (RDS engine versions, EC2 Windows images, etc.), by comparing the CDK code to SDK requests. For RDS, it's also checking whether a deprecated engine has been marked as such in TSDoc:

<img width="329" alt="image" src="https://github.com/aws/aws-cdk/assets/2505696/06b4eb95-ed82-4f32-960c-d9ec288fa78a">

It's just a CLI at the moment, but I'll probably end up turning it into a scheduled task, maybe even automate the opening of issues here if it's something you're interested in?
