### ISSUE TITLE
boto3 python: async sns publish

### ISSUE THREAD

**Issue by archws225** [aws/aws-cdk#29363]
### Describe the feature

i want a python equivalent of the amazonSNSAsync.publishAsync() call in boto3. this needs to be done for an aws customer

### Use Case

the boto3 sns client publish() method takes too long. i need to send and forget the published message

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.85

### Environment details (OS name and version, etc.)

linux

**Comment by pahud** [comment]
Which cdk construct are you asking? Can you share some code snippets?

**Comment by archws225** [comment]
import boto3

sns_client = boto3.client("sns")

    sns_client.publish(
        TopicArn=destination_sns_arn,
        Message=my_message,
    )

**Comment by pahud** [comment]
I guess you want to report this to [boto3](https://github.com/boto/boto3/issues) github?

I am closing it as it's not relevant to CDK. Feel free to reopen if it's still relevant.
