### ISSUE TITLE
(pipes-targets): Add API destination target for EventBridge pipes

### ISSUE THREAD

**Issue by RaphaelManke** [aws/aws-cdk#29386]
### Describe the feature

Add a implementation for the API destination target for EventBridge pipes in the `pipes-targets` module.

### Use Case

For feature completeness of the L2 pipes module this source is required.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

-

### Environment details (OS name and version, etc.)

-

**Comment by garysassano** [comment]
This is probably the most needed target since it's used to implement webhooks.

**Comment by garysassano** [comment]
This is probably one of most needed targets since it's used to implement webhooks.

**Comment by garysassano** [comment]
This is probably one of the most essential targets, as it's used for implementing webhooks. I would personally need it to set up something similar to [this](https://aws.amazon.com/blogs/compute/sending-and-receiving-webhooks-on-aws-innovate-with-event-notifications/).

**Comment by Leo10Gama** [comment]
Hello, it seems like [this PR](https://github.com/aws/aws-cdk/pull/30756) has resolved this issue! The API Destination pipe target should be available in CDK version [2.161.0](https://github.com/aws/aws-cdk/releases/tag/v2.161.0) and beyond.
