### ISSUE TITLE
rds: support for IO2 instance storage

### ISSUE THREAD

**Issue by badmintoncryer** [aws/aws-cdk#29396]
### Describe the feature

Support for IO2 instance storage type.

https://aws.amazon.com/jp/blogs/aws/amazon-rds-now-supports-io2-block-express-volumes-for-mission-critical-database-workloads/

### Use Case

AWS CDK cannot configure IO2 storage type for RDS instance .

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.131.0

### Environment details (OS name and version, etc.)

irrelevant

**Comment by pahud** [comment]
Yes I guess we should add the support in the enum. Thank you for your PR!
