### ISSUE TITLE
aws_iam.Policy: Confusing parameter description in the Policy construct

### ISSUE THREAD

**Issue by abdulkadirdere** [aws/aws-cdk#29398]
### Describe the issue

The `force` parameter from the `Policy` construct still requires the policy to be attached to a role, user, or group. However, documentation can be interpreted as a `force` parameter that will force CDK to create the policy without attaching the policy.
I believe docs should also indicate that the `Policy` construct is in-line policy and should refer to to ManagedPolicy for customer-managed policies.

### Links

[Policy](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_iam/Policy.html)

**Comment by pahud** [comment]
Hi

We would love to move this forward if you could submit a PR for us.

I guess this is the document we can improve.

https://github.com/aws/aws-cdk/blob/f0383d65c7cc8017c55ec9c9262d4a863bb63730/packages/aws-cdk-lib/aws-iam/lib/policy.ts#L72-L86
