### ISSUE TITLE
eks: managed node group allocatable pods number error

### ISSUE THREAD

**Issue by tony-vsx** [aws/aws-cdk#29418]
### Describe the bug

When I use managed node group multiple instance types, I got wrong allocatable pods number, t3a.xlarge allocatable pods 
 should be 58 not 17

<img width="635" alt="image" src="https://github.com/aws/aws-cdk/assets/152257237/2a1860e8-5e2f-4067-8af1-b55f44ed0560">
<img width="746" alt="截圖 2024-03-09 16 58 47" src="https://github.com/aws/aws-cdk/assets/152257237/b2c9509b-0d36-4b73-bbae-e0417e6d4118">
<img width="770" alt="截圖 2024-03-09 16 58 26" src="https://github.com/aws/aws-cdk/assets/152257237/c45d294f-e40b-40fd-b73d-8348ed9d35e9">

### Expected Behavior

t3a.xlarge allocatable pods should be 58 not 17

### Current Behavior

t3a.xlarge allocatable pods got 17

### Reproduction Steps

const cluster = new eks.Cluster(scope, 'eks', {
    version: eks.KubernetesVersion.V1_29,
    kubectlLayer: new KubectlV29Layer(scope, 'kubectl'),
    clusterName,
    vpc,
    vpcSubnets: [{ subnetType: ec2.SubnetType.PRIVATE_WITH_EGRESS }],
    endpointAccess: eks.EndpointAccess.PRIVATE,
    role: iam.eksRole(scope),
    outputMastersRoleArn: true,
    albController: { version: eks.AlbControllerVersion.V2_6_2 },
    clusterLogging: [eks.ClusterLoggingTypes.AUTHENTICATOR],
    defaultCapacity: 0,
    securityGroup: Vpc.eksControlPlaneSecurityGroup(scope, vpc),
  })

new eks.Nodegroup(scope, `${clusterName}-default-group`, {
    cluster,
    diskSize: 20,
    desiredSize: 2,
    minSize: 0,
    maxSize: 10,
    nodeRole,
    subnets: { subnetType: ec2.SubnetType.PRIVATE_WITH_EGRESS },
    instanceTypes: [
      new ec2.InstanceType('t3a.xlarge'),
      new ec2.InstanceType('t3a.medium'),
    ],
    tags: {
      [`k8s.io/cluster-autoscaler/${clusterName}`]: 'owned',
      ['k8s.io/cluster-autoscaler/enabled']: 'true',
      Name: `${clusterName}-default-group`,
    },
  })

### CDK CLI Version

2.128.0

### Node.js Version

20

### OS

MacOS

### Language

TypeScript

**Comment by msambol** [comment]
The first two screenshots show 58. The second shows 17, which is the limit for `t3a.medium` as defined here. Can you try this again but for instance types only include `t3a.xlarge` ?

**Comment by tony-vsx** [comment]
It will be 58

**Comment by msambol** [comment]
So it's behaving as expected ? 😀

**Comment by tony-vsx** [comment]
If I only choose one, yes. But if I choose two, no.

**Comment by msambol** [comment]
Right, because you are also specifying `t3a.medium` as an instance type: 

```
instanceTypes: [
   new ec2.InstanceType('t3a.xlarge'),
   new ec2.InstanceType('t3a.medium'),
],
```

If you want 58 allocable pods, only use `t3a.xlarge`. Hope that helps.

**Comment by pahud** [comment]
@tony-vsx did you mean you are having 17 allocable pods on `t3a.medium` which should be 58?

I think it's managed by the agent in the AMI as described in this [file](https://github.com/awslabs/amazon-eks-ami/blob/master/files/eni-max-pods.txt)(thank you @msambol ) and t3a.medium is actually having 17 allocable pods.

**Comment by tony-vsx** [comment]
@pahud yes, that's what I want to express

**Comment by pahud** [comment]
I think it should be 17 according to that file. I am closing this issue as it doesn't seem to be a CDK bug. Feel free to reopen if there's any concern.

**Comment by tony-vsx** [comment]
Sorry for the confusion. What I meant to say is that if set within the same array, `t3a.xlarge` should be set to 58, `t3a.medium` to 17, but when set together,`t3a.xlarge` would end up being only 17.
