### ISSUE TITLE
Personalize: Wrong attribute created in cloudformation (Python)

### ISSUE THREAD

**Issue by ricciocri** [aws/aws-cdk#29411]
### Describe the bug

While creating a dataset job import for a personalize dataset with Python and cdk 2.130 the resulted cloudformation has a wrong attribute and so the deploy fails.

The correct attribute in cloudformation should be **DataLocation** : https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-personalize-dataset-datasource.html

### Expected Behavior

This is the expected cloudformation

```yaml
"Type": "AWS::Personalize::Dataset",
   "Properties": {
    "DatasetGroupArn": "arn:aws:personalize:eu-west-1:xxxxxxxxx:dataset-group/personalize-dsg",
    "DatasetImportJob": {
     "DataSource": {
      "**DataLocation**": "s3://my_bucket/my_path/users.csv"
     },
     "JobName": "personalize-users-import-job",
     "RoleArn": {
      "Fn::GetAtt": [
       "PersonalizeRole6C121A81",
       "Arn"
      ]
     }
    },
    "DatasetType": "Users",
    "Name": "personalize-users",
    "SchemaArn": {
     "Fn::GetAtt": [
      "usersschema",
      "SchemaArn"
     ]
    }
   },
   "Metadata": {
    "aws:cdk:path": "prod-personalize-stack/personalize-users"
   }
  },
```

### Current Behavior

This is the output of the cloudformation in cdk.out

```yaml
"Type": "AWS::Personalize::Dataset",
   "Properties": {
    "DatasetGroupArn": "arn:aws:personalize:eu-west-1:xxxxxxxxx:dataset-group/personalize-dsg",
    "DatasetImportJob": {
     "DataSource": {
      "**dataLocation**": "s3://my_bucket/my_path/users.csv"
     },
     "JobName": "personalize-users-import-job",
     "RoleArn": {
      "Fn::GetAtt": [
       "PersonalizeRole6C121A81",
       "Arn"
      ]
     }
    },
    "DatasetType": "Users",
    "Name": "personalize-users",
    "SchemaArn": {
     "Fn::GetAtt": [
      "usersschema",
      "SchemaArn"
     ]
    }
   },
   "Metadata": {
    "aws:cdk:path": "prod-personalize-stack/personalize-users"
   }
  },`
```

### Reproduction Steps

create a dataset and its importjob:

personalize.CfnDataset(
            self,
            dataset_name,
            name=my_dataset,
            dataset_type=ITEMS,
            dataset_group_arn=dataset_group_arn,
            schema_arn=schema_arn,
            dataset_import_job=personalize.CfnDataset.DatasetImportJobProperty(
                job_name=my-import-job",
                role_arn=self._personalize_role.role_arn,
                data_source=personalize.CfnDataset.DataSourceProperty(
                    data_location="s3://mybucket/mypath/items.csv",
                ),
            )
        )

Just do a synth anche check the datalocation

### CDK CLI Version

2.130

### Node.js Version

v18.19.1

### OS

Debian 12

### Language

Python

**Comment by pahud** [comment]
The dataSource is type `any`(see [doc](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_personalize.CfnDataset.DatasetImportJobProperty.html#datasource)) so you need to construct a JSON like

```
data_source={'dataLocation': 's3://my_bucket/my_path/users.csv'}
```

Let me know if it works for you.

**Comment by ricciocri** [comment]
Hello @pahud,

Thanks for the info, I confirm that using a Json it works.
So probably it's the personalize.CfnDataset.DataSourceProperty to be checked, but for my use case I'm set.

Thanks.

**Comment by pahud** [comment]
Yeah if you are using CDK in Python. Make sure to check the CDK API reference,  if the prop type is `any`, just use the JSON and it will be good. Hope everything is doing great with you.
