### ISSUE TITLE
core: Stack Construct: when set stack-level tags with pseudo parameters such as Class Aws.STACK_NAME should emit error

### ISSUE THREAD

**Issue by jiem-ying** [aws/aws-cdk#29424]
### Describe the bug

In previous closed issue "core: improve experience around stack-level tagging"
https://github.com/aws/aws-cdk/issues/4134

Should have feature "We should emit an error if you try to apply a tag that uses tokens to the Stack itself."

However, when use Stack Class to work on tags, example Python code
```
        bucket = s3.Bucket(self, "testCDKBucketwithImportedValuejiemying",
                           removal_policy= RemovalPolicy.DESTROY,
                           auto_delete_objects= True
                           )
        
        Stack.of(self).tags.set_tag("StackNameViaAws",Aws.STACK_NAME)
``` 
CDK ``` ls and synth ```do not emit the error, only when ```cdk deploy``` the expected invalid token value error will be incurred during stack operation when trying to tag resources in the scope:
```
Deployment failed: Error: The stack named CdkCaseworkingPythonStack failed to deploy: UPDATE_ROLLBACK_COMPLETE: Resource handler returned message: "1 validation error detected: Value '${Token[AWS.StackName.13]}' at 'tags.2.member.value' failed to satisfy constraint: Member must satisfy regular expression pattern: [\p{L}\p{Z}\p{N}_.:/=+\-@]* (Service: Iam, Status Code: 400, Request ID: df4a5550-9d06-4cc0-bd1d-46331da9858e)" (RequestToken: ce3f7dc0-4937-80e1-4b98-c639edead1b0, HandlerErrorCode: GeneralServiceException)
```

### Expected Behavior

When user pass pseudo parameters such as Aws.STACK_NAME, and Aws.REGION to Stack Construct tags. An error should be given due to https://github.com/aws/aws-cdk/issues/4106#issuecomment-532761271

### Current Behavior

CDK ls and synth does not give error. 

The Stack construct will pass {Token[AWS.StackName.13]} as stack-level tag value when CDK create-changeset, subsequently causing error when the stack level tags propagate to resources inside of the stack. 

### Reproduction Steps

1. Create a tag-able resource in a CDK stack and set tags value with pseudo parameter Class Aws

```
        bucket = s3.Bucket(self, "testCDKBucketwithImportedValuejiemying",
                           removal_policy= RemovalPolicy.DESTROY,
                           auto_delete_objects= True
                           )
        
        Stack.of(self).tags.set_tag("StackNameViaAws",Aws.STACK_NAME)
``` 

2. cdk deploy

### Possible Solution

We should emit an error if you try to apply a tag that uses tokens to the Stack itself

### CDK CLI Version

2.132.0

### Node.js Version

v20.11.1

### OS

MacOS

### Language

Python

**Comment by pahud** [comment]
This error is from CloudFormation not CDK. Yes I think we should check that in [setTag](https://github.com/aws/aws-cdk/blob/5b910f0d61d4adae38788f7f16ccdae6cb214057/packages/aws-cdk-lib/core/lib/tag-manager.ts#L361).

**Comment by comcalvi** [comment]
This will break existing functionality; we should not do this. See: https://github.com/aws/aws-cdk/pull/30022#issuecomment-2276754163
