### ISSUE TITLE
iam: SAML principal AssumeRoleAction is hardcoded

### ISSUE THREAD

**Issue by justin8** [aws/aws-cdk#29456]
### Describe the bug

Currently when defining an assume role policy on a role the action is hardcoded to `sts:AssumeRoleWithSAML' [here](https://github.com/aws/aws-cdk/blob/v2.132.0/packages/aws-cdk-lib/aws-iam/lib/principals.ts#L746). However for some use cases, such as Quicksight's own SAML integration, you also need `sts:TagSession` in order to use the email sync feature.

### Expected Behavior

You should be able to modify the assume role action and just have a default, not a hardcoded action.

### Current Behavior

It's hardcoded and requires the use of escape hatches such as:

```javascript
    const cfnFederationRole = federationRole.node.defaultChild as iam.CfnRole;
    cfnFederationRole.addOverride('Properties.AssumeRolePolicyDocument.Statement.0.Action', [
      'stsAssumeRoleWithSAML',
      'sts:TagSession',
    ]);
```

### Reproduction Steps

```javascript
    const federationRolePrincipal = new iam.SamlPrincipal(samlProvider, {
      StringEquals: { 'SAML:aud': 'https://signin.aws.amazon.com/saml' },
    });

    const federationRole = new iam.Role(this, 'QuicksightFederationRole', {
      roleName: 'QuicksightFederationRole',
      assumedBy: federationRolePrincipal,
    });

    const cfnFederationRole = federationRole.node.defaultChild as iam.CfnRole;
    cfnFederationRole.addOverride('Properties.AssumeRolePolicyDocument.Statement.0.Action', [
      'stsAssumeRoleWithSAML',
      'sts:TagSession',
    ]);
```

### CDK CLI Version

2.126.0

### Node.js Version

18

### OS

Linux

### Language

TypeScript

**Comment by pahud** [comment]
>However for some use cases, such as Quicksight's own SAML integration, you also need sts:TagSession` in order to use the email sync feature.

Do you have any public document link about this?

We probably need to update here

https://github.com/aws/aws-cdk/blob/0c7314362ecd5d6a560a8e6282ca1416fdb22c64/packages/aws-cdk-lib/aws-iam/lib/principals.ts#L741-L752

**Comment by justin8** [comment]
There is an example in the docs here for implementing ABAC using tags and SAML IdP integration: https://docs.aws.amazon.com/IAM/latest/UserGuide/tutorial_abac-saml.html

For Quicksight, it has it in their docs to add `sts:TagSession` permissions to the SAML integration role as well: https://docs.aws.amazon.com/quicksight/latest/user/jit-email-syncing.html

**Comment by msambol** [comment]
I'll take this.

**Comment by msambol** [comment]
@justin8 I think you should be able to use `federationRolePrincipal.addToAssumeRolePolicy....`.

**Comment by justin8** [comment]
I did the same thing :) I tried that thinking it sounded correct, then ended up reading through the code to see that it wouldn't work

**Comment by msambol** [comment]
Try adding `withSessionTags()`: 

```
    const federationRolePrincipal = new iam.SamlPrincipal(samlProvider, {
      StringEquals: { 'SAML:aud': 'https://signin.aws.amazon.com/saml' },
    }).withSessionTags();
```
