### ISSUE TITLE
(aws-ec2): VpcEndpointService allowedPrincipals has type of `ArnPrincipal[]`, but should also support the `ServicePrincipal` type

### ISSUE THREAD

**Issue by 7e11** [aws/aws-cdk#29478]
### Describe the bug

`VpcEndpointService` has the member `allowedPrincipals` which is of type `ArnPrincipal[]`. However, if you use the AWS console, allowlisting a service principal is supported as well. Users are not able to use the type `ServicePrincipal` in `allowedPrincipals` in CDK. This is a feature gap.

[packages/aws-cdk-lib/aws-ec2/lib/vpc-endpoint-service.ts](https://github.com/aws/aws-cdk/blob/135b5208dce849f49b6f540f7199ece057a7ef22/packages/aws-cdk-lib/aws-ec2/lib/vpc-endpoint-service.ts)

### Expected Behavior

`VpcEndpointService` `allowedPrincipals` should support `ArnPrincipal` as well as `ServicePrincipal`.

### Current Behavior

`VpcEndpointService` `allowedPrincipals` only supports `ArnPrincipal`.

### Reproduction Steps

```
const privateLinkVPCEService = new VpcEndpointService(this, 'PrivateLinkVPCEService', {
  vpcEndpointServiceLoadBalancers: [privateLinkNlb],
  acceptanceRequired: false,
  allowedPrincipals: [new ServicePrincipal('someservice.aws.internal'),  // <-- type error. Only ArnPrincipal[] allowed.
});
```

### Possible Solution

Modify the `VpcEndpointService` construct to support `ServicePrincipal` as well as `ArnPrincipal` for the member `allowedPrincipals`

### Additional Information/Context

For context, this is an AWS internal service which is onboarding to privatelink, and only wants to allowlist specific service principals. This is possible in the console, but not in CDK.

----

There is a workaround I've been using, but it's a little janky. It's possible to pass in a service principal to the `allowedPrincipals` by wrapping it in the `ArnPrincipal` type. For example:

`new ArnPrincipal('someservice.aws.internal');`

You could also use L1 constructs, but that gets painful if you're using `VpcEndpointServiceDomainName`, because there is no corresponding L1 construct and it's nontrivial.

### CDK CLI Version

2.130.0 (build bd6e5ee)

### Framework Version

2.130.0

### Node.js Version

v16.7.0

### OS

macOS Ventura 13.6.4

### Language

TypeScript

**Comment by 7e11** [comment]
This is what the VPCE principal allowlisting page looks like in the console. It also claims to only accept ARNs, but service principals also work.
![VPCE Allow Principals](https://github.com/aws/aws-cdk/assets/5494304/f9c05979-075a-4d56-a424-0820cb311458)

**Comment by 7e11** [comment]
Here's a redacted service principle in the "Allow Principles" list after adding it in the above UI. The type is listed as `Service`, instead of `Arn`.
![VPCE Allow principals list](https://github.com/aws/aws-cdk/assets/5494304/90138140-e46a-4e7a-b662-04ae8ff85e76)

**Comment by pahud** [comment]
The principals passed in will generate [AllowedPrincipals](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcendpointservicepermissions.html#cfn-ec2-vpcendpointservicepermissions-allowedprincipals) in [VPCEndpointServicePermissions](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcendpointservicepermissions.html), which literally accept any format of any format of principals.

https://github.com/aws/aws-cdk/blob/87139ab2eeae96df9d775118b870cfb326438197/packages/aws-cdk-lib/aws-ec2/lib/vpc-endpoint-service.ts#L127-L130

We can't make it either ArnPrincipal type or ServicePrincipal type in CDK. I guess we need to document what we should do when we are assigning a service principal for it. And it could be the workaround you provided.

I'll request the team for more input on this. And let me know if you have any further thoughts.

**Comment by GavinZZ** [comment]
Hi @7e11, after investigation, I think you're right that although the documentation specifically mentions arn principal, the console doesn't stop you from using service principals. I agree with Pahud's suggestion on adding the workaround to [README](https://github.com/aws/aws-cdk/blob/0cb1ba98d0fdff1a0aee0ac84fc31e136e4ed042/packages/aws-cdk-lib/aws-ec2/README.md#L1039) documentation.

Since this is an issue with potential workaround, I think marking this issue as `p2` is reasonable here, and unfortunately we won't be able to prioritize working on a p2 issue. Meanwhile we welcome community contribution and it will be appreciated if you'll be able to make the documentation update.

**Comment by 7e11** [comment]
Gotcha -- so because using SPs is a bit of an undocumented feature, we can't alter the construct to accept other principal types. I'll update the readme soon.
