### ISSUE TITLE
aws_lambda_nodejs: Unexisting `AWS_NODEJS_CONNECTION_REUSE_ENABLED` env variable set to `1` as default

### ISSUE THREAD

**Issue by garysassano** [aws/aws-cdk#29497]
### Describe the bug

The AWS SDK for JavaScript v3 is included by default in AWS Lambda Node.js 18 and Node.js 20 runtimes.

`NodejsFunction` construct comes with an `awsSdkConnectionReuse` optional prop, which is set to `true` by default. This default automatically sets the `AWS_NODEJS_CONNECTION_REUSE_ENABLED` environment variable to `1` in the Lambda function's configuration.

However, it has been identified that the `AWS_NODEJS_CONNECTION_REUSE_ENABLED` environment variable [does not exist in AWS SDK for JavaScript v3](https://github.com/aws/aws-sdk-js-v3/issues/5883), rendering the variable obsolete for those utilizing the more recent Lambda runtimes. This situation not only leads to unnecessary configuration, but it also has a performance impact. The inclusion of this redundant environment variable is associated with a [20ms increase in cold start times](https://speedrun.nobackspacecrew.com/blog/2024/03/13/lambda-environment-variables-impact-on-coldstarts.html), highlighting an opportunity for performance improvement by removing this default setting for those who do not require it.

### Expected Behavior

see above

### Current Behavior

see above

### Reproduction Steps

see above

### CDK CLI Version

2.132.1

### Node.js Version

20.11.1

### OS

Ubuntu 22.04.3 LTS

### Language

TypeScript

**Comment by garysassano** [comment]
The new default for `awsSdkConnectionReuse` should either be always `false`, or:
- true for `nodejs20.x` and `nodejs18.x`
- false for `nodejs16.x`

**Comment by garysassano** [comment]
The new default for `awsSdkConnectionReuse` should either be always `false`, or:
- `true` for `nodejs20.x` and `nodejs18.x`
- `false` for `nodejs16.x`

**Comment by garysassano** [comment]
The new default for `awsSdkConnectionReuse` should either be always `false`, or:
- `false` for `nodejs20.x` and `nodejs18.x`
- `true` for `nodejs16.x`

**Comment by pahud** [comment]
Yes I agree with your proposed solution. Making this a p1 but we welcome PRs as well.

**Comment by TheRealAmazonKendra** [comment]
This will actually become a moot point in just a few weeks or so. We are removing use of v2 from the CDK.
