### ISSUE TITLE
Ability to add an existing security group to a RDS database

### ISSUE THREAD

**Issue by repolevedavaj** [aws/aws-cdk#2949]
I noticed that some configuration options which are available when creating a RDS database (e.g. MySQL) in the console, are not available if creating one with CDK. 

Options which are currently not available (in version 0.35):

- Adding an existing security group
- Configure public accessibility
- Configure enhanced monitoring

(I am sure this list is not complete)

**Comment by jogold** [comment]
Configure public accessibility: this is automatically determined based on the type of subnets specified in `vpcPlacement`, your instance will be publicly accessible if those are of the type `SubnetType.Public`

Configure enhanced monitoring: setting `monitoringInterval` to a value > 0 will enable it.

You are right about the existing security group but note that you can use the `connections` object of the created instance to add ingress/egress rules.

**Comment by repolevedavaj** [comment]
Thanks for your quick advice. I will change my setup accordingly. Should I close the issue or should I rename it to something like "Ability to add an existing security group to a RDS database"?

**Comment by jogold** [comment]
Rename it

**Comment by NGL321** [comment]
@repolevedavaj thank you so much for bringing this to our attention!
We are working hard to stabilize the CDK APIs and tuning them to meet our consistency guidelines. While we work on getting the APIs aligned with our guidelines, we are pausing work on most community PRs and feature-requests starting today. Please continue to report issues and submit feature requests, of course. We expect to get back to work on community PRs within a few weeks.

A team member will update this issue when we are able to address it.

**Comment by jogold** [comment]
@skinny85 it has been merged by mergify... it doesn't contain the `BREAKING CHANGE`.
