### ISSUE TITLE
Lambda:  runtime must be `Runtime.FROM_IMAGE` when using image asset for Lambda function

### ISSUE THREAD

**Issue by LajosPolya** [aws/aws-cdk#29502]
### Describe the bug

Neither `aws_lambda.Handler.FROM_IMAGE` nor `cdk.aws_lambda.Runtime.FROM_IMAGE` resolve when deploying a lambda using the `aws_lambda.Code.fromDockerBuild`.

They produce the following errors:

1. "Error: handler must be `Handler.FROM_IMAGE` when using image asset for Lambda function"
and
2. "Error: runtime must be `Runtime.FROM_IMAGE` when using image asset for Lambda function"

### Expected Behavior

Neither `aws_lambda.Handler.FROM_IMAGE` nor `cdk.aws_lambda.Runtime.FROM_IMAGE` should produce an error when deploying a lambda using the `aws_lambda.Code.fromDockerBuild`.

### Current Behavior

Neither `aws_lambda.Handler.FROM_IMAGE` nor `cdk.aws_lambda.Runtime.FROM_IMAGE` resolve when deploying a lambda using the `aws_lambda.Code.fromDockerBuild`.

Note that I was able to resolve the first error but replacing `cdk.aws_lambda.Handler.FROM_IMAGE` with the string `"Handler.FROM_IMAGE"`.

I wasn't able to resolve the runtime error this way since `FunctionProps.runtime` is of type `Runtime` not `string`.

### Reproduction Steps

I have a repo to repsoduce the steps (use this exact commit since it's not the most recent commit):
https://github.com/LajosPolya/aws-cdk-templates/commit/b92f222678a77310451787a729d3e522071a9eb9

### Possible Solution

The interesting this about this is that both `cdk.aws_lambda.Runtime.FROM_IMAGE` and `cdk.aws_lambda.Handler.FROM_IMAGE` resolve correctly when using `aws_lambda.Code.fromEcrImage` instead of `aws_lambda.Code.fromDockerBuild`.

I have an example in this repo:
https://github.com/LajosPolya/aws-cdk-templates/tree/main/deploy-lambda-from-ecr

Another interesting fact about this is I'm able to deploy the Lambda successfully if I set the runtime to `cdk.aws_lambda.Runtime.NODEJS_20_X` and the handler to `"index.handler"`. This seems to go against what the docs say: "Use `Handler.FROM_IMAGE` when defining a function from a Docker image."

This can be reproduced here:
https://github.com/LajosPolya/aws-cdk-templates/commit/fc768144efbebcf55e95a0b29681689a368dff14

### Additional Information/Context

This bug was already opened once but was never fixed:
https://github.com/aws/aws-cdk/issues/25758

### CDK CLI Version

2.133.0 (build dcc1e75)

### Node.js Version

v20.11.1

### OS

Windows 10

### Language

TypeScript

### Language Version

"typescript": "~5.3.3"

**Comment by pahud** [comment]
Let's simplify the code. I guess you should use

```ts
    const dockerImageCode = lambda.Code.fromDockerBuild(
      path.join(__dirname, '../docker-function.d')
    );

    const fn = new lambda.Function(this, 'Fn', {
      runtime: lambda.Runtime.FROM_IMAGE,
      code: dockerImageCode,
      handler: lambda.Handler.FROM_IMAGE,
    });
```

But if you look at the source code here, [DockerImageFunction](https://github.com/aws/aws-cdk/tree/main/packages/aws-cdk-lib/aws-lambda#docker-images) is generally recommended in your use case.

https://github.com/aws/aws-cdk/blob/87139ab2eeae96df9d775118b870cfb326438197/packages/aws-cdk-lib/aws-lambda/lib/image-function.ts#L63-L75

Why not just use DockerImageFunction in your use case?

**Comment by LajosPolya** [comment]
I wasn't aware of this option. I was able to test this and it works! Thanks for the suggestion @pahud
