### ISSUE TITLE
elasticloadbalancingv2: support NLB attributes

### ISSUE THREAD

**Issue by badmintoncryer** [aws/aws-cdk#29520]
### Describe the feature

We can configure NLB attributes from AWS CDK.
- ipv6.deny_all_igw_traffic 
- dns_record.client_routing_policy

### Use Case

NLB supports these attributes but they are not be configurable by AWS CDK. 

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.132.0

### Environment details (OS name and version, etc.)

irrelevant

**Comment by tim-finnigan** [comment]
Thanks for the feature request and creating that PR!
