### ISSUE TITLE
aws_ec2: InterfaceVpcEndpointAwsService not supported for bedrock-runtime and bedrock

### ISSUE THREAD

**Issue by clouddev-code** [aws/aws-cdk#29523]
### Describe the feature

by InterfaceVpcEndpointAwsServiceçe  not supported for bedrock-runtime and bedrock
https://docs.aws.amazon.com/bedrock/latest/userguide/usingVPC.html

### Use Case

I want to crate interface endpoint by AWS CDK

### Proposed Solution

Could easily be accomplished by adding variables by the foolowing code
https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-ec2/lib/vpc-endpoint.ts

### Other Information

static readonly defintion add
https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-ec2/lib/vpc-endpoint.ts

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.133.0

### Environment details (OS name and version, etc.)

M1 mac

**Comment by tim-finnigan** [comment]
Thanks for the feature request. It looks like a PR (https://github.com/aws/aws-cdk/pull/29524) was created to address this.
