### ISSUE TITLE
sns: Support for SignatureVersion

### ISSUE THREAD

**Issue by jun1-t** [aws/aws-cdk#29539]
### Describe the feature

Enable setting of SignatureVersion in the L2 construct for SNS topics.

https://docs.aws.amazon.com/sns/latest/dg/sns-verify-signature-of-message.html

### Use Case

To set the SignatureVersion, it is necessary to configure it via L1.

https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-resource-sns-topic.html#cfn-sns-topic-signatureversion

### Proposed Solution

Allows passing the "SigantureVersion" parameter as an argument.

```ts
const topic = new sns.Topic(this, 'MyTopic', {
  signatureVersion: '1',
});
```

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.133.0

### Environment details (OS name and version, etc.)

irrelevant

**Comment by tim-finnigan** [comment]
Hi @jun1-t thanks for the feature request. Have you tried using `signatureVersion` with `CfnTopic`? Documentation here: https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_sns.CfnTopic.html#signatureversion
