### ISSUE TITLE
eks: Amazon Linux 2023 is not fully supported in nodegroup

### ISSUE THREAD

**Issue by arlampin** [aws/aws-cdk#29546]
### Describe the bug

https://github.com/aws/aws-cdk/pull/29335 added support for Amazon Linux 2023 `NodegroupAmiType`, but it only added the enum values. They are not listed as valid types in `managed-nodegroup.ts` `arm64AmiTypes` or `x8664AmiTypes`, thus they can't be used alongside `instanceTypes` nodegroup parameter.

### Expected Behavior

Defining both `amiType: AL2023_X86_64_STANDARD / AL2023_ARM_64_STANDARD` and `instanceTypes` should work.

### Current Behavior

Using both `instanceTypes` and AL2023 `amiType` results in following error:

    Error: The specified AMI does not match the instance types architecture, either specify one of AL2_ARM_64, BOTTLEROCKET_ARM_64 or don't specify any

### Reproduction Steps

```ts
cluster.addNodegroupCapacity('Arm64', {
  instanceTypes: [
    ec2.InstanceType.of(ec2.InstanceClass.T4G, ec2.InstanceSize.XLARGE), 
  ],
  amiType: NodegroupAmiType.AL2023_ARM_64_STANDARD
});
```

### CDK CLI Version

2.133.0 (build dcc1e75)

### Node.js Version

v18.18.2

### OS

macos

### Language

TypeScript

**Comment by pahud** [comment]
Yes we should add a PR for that.

**Comment by pahud** [comment]
I will submit a PR for this.
