### ISSUE TITLE
Improve error messages for cdk migrate in cdk-from-cfn

### ISSUE THREAD

**Issue by TheRealAmazonKendra** [aws/aws-cdk#29558]
### Context

In cdk-from-cfn, the current code defines a single error named `TransmuteError` and all other errors are defined using one of the `panic!`, `unimplemented!`, or `unreachable!` macros. `TransmuteError` is all encompassing for any transmutation related errors such as resource translation errors, parsing errors, import instruction errors, etc. Any use of the `panic!`, `unimplemented!`, or `unreachable!` macro will cause the source code to panic in place. In wasm builds, this causes a non-descriptive runtime error with a message of "unreachable".

In general, our current mechanism for defining error types and messages causes several problems:

1. Our code is harder to debug since error types are all encompassing and too widely scoped
2. Error messages are too generic when they originate from the panic!, unimplemented!, or unreachable! macros
3. New custom error types must be implemented manually which slows down development speed and is error prone
4. Users don't have clear error messages that help them to effectively debug resulting in a frustrating UX and increasing issues in our queue

### Task Description

Use the [thiserror](https://crates.io/crates/thiserror) crate to build a new mechanism for defining errors with more specific error types and messages.

### Acceptance Criteria

1. We have a single enum with all errors defined.
2. All instances of `panic!`, `unreachable!`, and `unimplemented!` are replaced with a well-defined error type and a descriptive message.
3. Unit tests have been created for each defined error.
4. The updated code is built to wasm and error message formatting is checked on the CLI side.
5. If needed, the CLI error formatting code must be updated in a follow-up PR.
6. Version of cdk-from-cfn is released to aws-cdk and all unit/integ tests still pass or are fixed.

---

Comments:
https://github.com/cdklabs/cdk-from-cfn/pull/600

**Comment by colifran** [comment]
Closed with - https://github.com/cdklabs/cdk-from-cfn/pull/600
