### ISSUE TITLE
aws-cdk: Duration.parse() does not handle units larger then days 

### ISSUE THREAD

**Issue by mattaschmann** [aws/aws-cdk#29572]
### Describe the bug

While trying to use `cdk.Duration.parse()` with the strings `P1Y` and `P1M` it threw errors.  Looking at the source (https://github.com/aws/aws-cdk/blob/43e681e26cab82c5dbc4ab6212314a641e676097/packages/aws-cdk-lib/core/lib/duration.ts#L69-L89) it's obvious that any unit larger then days are not handled.

### Expected Behavior

As the documentation for this message states:
```
    /**
     * Parse a period formatted according to the ISO 8601 standard
     *
     * @see https://www.iso.org/standard/70907.html
     * @param duration an ISO-formatted duration to be parsed.
     * @returns the parsed `Duration`.
     */
```
It should correctly handle all valid ISO 8601 strings.  Either that, or the documentation needs to indicate it doesn't handled anything larger then days.

### Current Behavior

Throws an error on any unit larger then a day.

### Reproduction Steps

import * as cdk from 'aws-cdk-lib'

cdk.Duration.parse('P1Y')
cdk.Duration.parse('P1M')

### Possible Solution

Add larger units to the regular expression and handle them, or change the documentation to indicate that they are not handled.

### CDK CLI Version

2.115.0 (build 58027ee)

### Node.js Version

v18.15.0

### OS

macOS: 14.3.1 (23D60)

### Language

TypeScript

**Comment by pahud** [comment]
Thank you for the report.

And @msambol thanks for your PR as always!
