### ISSUE TITLE
elasticloadbalancingv2: support ALB attributes

### ISSUE THREAD

**Issue by badmintoncryer** [aws/aws-cdk#29585]
### Describe the feature

CDK supports configuring some ALB attributes.
- `routing.http.preserve_host_header.enabled`
- `routing.http.x_amzn_tls_version_and_cipher_suite.enabled`
- `routing.http.xff_client_port.enabled`
- `routing.http.xff_header_processing.mode`
- `waf.fail_open.enabled`

### Use Case

We want to configure these attributes from CDK.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.132.0

### Environment details (OS name and version, etc.)

irrelevant

**Comment by tim-finnigan** [comment]
Thank you for the feature request and creating the PR!
