### ISSUE TITLE
docs(sns): remove an unused variable declaration in Archive Policy

### ISSUE THREAD

**Issue by jun1-t** [aws/aws-cdk#29590]
### Describe the issue

Archive Policy parameter in the aws_cdk_sns document has an unused variable declaration.

Currently the documentation says:
***
Example with an archive policy for SQS:
```ts
declare const role: iam.Role;
const topic = new sns.Topic(this, 'MyTopic', {
   fifo: true,
   messageRetentionPeriodInDays: 7,
});
```
***

I think the following is better.
***
Example with an archive policy:
```ts
const topic = new sns.Topic(this, 'MyTopic', {
   fifo: true,
   messageRetentionPeriodInDays: 7,
});
```
***
Removed "for SQS" and "declare const role: iam.Role;".

### Links

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_sns-readme.html#archive-policy

**Comment by tim-finnigan** [comment]
Thanks for reporting this issue and creating the PR!
