### ISSUE TITLE
(cognito): Add idpInitiated flag to UserPoolIdentityProviderSaml

### ISSUE THREAD

**Issue by Booligoosh** [aws/aws-cdk#29598]
### Describe the feature

Cognito now supports IdP-initiated SAML auth flows, however it requires an option being set on the User Pool Identity Provider: https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-SAML-session-initiation.html

The option is available in the AWS console under the "IDP-initiated SAML sign-in" section when editing a SAML identity provider, just under the "Sign-out flow" section.

### Use Case

I can't currently enable IdP-initiated auth without using a CFN override:
```typescript
const cfnSamlProvider = samlProvider.node.defaultChild as cognito.CfnUserPoolIdentityProvider;
cfnSamlProvider.providerDetails.IDPInit = "true";
```

### Proposed Solution

Add a new prop `idpInitiated: boolean` to `UserPoolIdentityProviderSaml` that controls whether ProviderDetails.IDPInit is set to "true" or "false".

### Other Information

Related to PR #29588 and issue #29494

### Acknowledgements

- [x] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.115.0

### Environment details (OS name and version, etc.)

Windows 10 Enterprise

**Comment by msambol** [comment]
@badmintoncryer Do you want to take this and add it to https://github.com/aws/aws-cdk/pull/29588 ?

**Comment by badmintoncryer** [comment]
@msambol Of course! I'll take it.

**Comment by Booligoosh** [comment]
Hi @badmintoncryer, if you're happy to take it, that'd be awesome, cheers!! If you don't want to though, I can do it.

**Comment by badmintoncryer** [comment]
@Booligoosh Sure! I'll take it😃

**Comment by tim-finnigan** [comment]
Thank you for the feature request and the PR!
