### ISSUE TITLE
Create a "How-To" topic in the guide docs

### ISSUE THREAD

**Issue by Doug-AWS** [aws/aws-cdk#296]
Some how-tos might also exist in other doc topics. I think the best strategy is to use a common file and incorporate it into both locations. It's pretty simple to do in RST.

These answer the question "How do I ..." and each how-to is in its own issue.

**Comment by Doug-AWS** [comment]
I've split out all proposed how-to entries into separate issues. All are in my dougsch/addhowto branch, which is currently a WIP. Once I've finished, I'll open a PR and add that info to this issue and close it.

**Comment by Doug-AWS** [comment]
Done

**Comment by Doug-AWS** [comment]
It's alive!

**Comment by Doug-AWS** [comment]
Some ideas from #1607 

* How to use secrets
* How to create a Custom Resource
* How to grant permissions
* How to create multi-stacks apps
* How to start EC2 instances in an AutoScaling Group
* How to set up AutoScaling
* How to deploy my application using a Pipeline
* How to work around missing CDK features
* How to set up monitoring
* How to do complicated auth using the CLI
* How to respond to CloudWatch events
* How to control generated CloudFormation template

**Comment by fulghum** [comment]
@Jerry-AWS can you confirm if there is work here and close otherwise?  Sounds like we are tracking in the other issues Doug created.

**Comment by fulghum** [comment]
@Jerry-AWS – let's break these down into individual issues, then the community can vote on them or even contribute.

**Comment by Doug-AWS** [comment]
I moved all of the doc issues to the doc repo (https://github.com/awsdocs/aws-cdk-guide/issues) about a month ago.

**Comment by Jerry-AWS** [comment]
Maybe the team can have a look at the list of ideas in @Doug-AWS's Feb 12 post and decide which (if any) might still be needed. I'll make new issues for the survivors in the CDK Guide repo.
