### ISSUE TITLE
CodeBuild: Fleet L2

### ISSUE THREAD

**Issue by nmussy** [aws/aws-cdk#29617]
### Describe the feature

There is currently no documented examples or tests of reserved capacity CodeBuild projects.

### Use Case

I discovered this issue while attempting to add the `aws/codebuild/windows-base:2019-3` image to `WindowsBuildImage`, see https://github.com/aws/aws-cdk/pull/29616#issuecomment-2019991742 for additional context

### Proposed Solution

Adding a `fleet` prop to the `Project` construct shouldn't be too much work, and will allow us to easily check that the `fleet` property is present when a `WindowsImageType.SERVER_2022` image is given

### Other Information

[Working with reserved capacity in AWS CodeBuild](https://docs.aws.amazon.com/codebuild/latest/userguide/fleets.html)
#29616

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

v2.133.0

### Environment details (OS name and version, etc.)

macOS 14.3.1

**Comment by tim-finnigan** [comment]
Thanks for the feature request!

**Comment by nmussy** [comment]
I've started working on implementing the L2 construct. It shouldn't be too much more work, but the integration tests are slow running given how long fleets take to be deleted.

Unfortunately, I've noticed two missing attributes in the L1 construct, [`overflowBehavior`](https://docs.aws.amazon.com/codebuild/latest/APIReference/API_Fleet.html#CodeBuild-Type-Fleet-overflowBehavior) and [`scalingConfiguration`](https://docs.aws.amazon.com/codebuild/latest/APIReference/API_Fleet.html#CodeBuild-Type-Fleet-scalingConfiguration).


I've opened an issue in the CloudFormation Public Coverage Roadmap project (https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1998). Unfortunately I'm going to have to ignore these attributes in the meantime, I'll open another PR to add them to the construct if and when they're implemented.

**Comment by nmussy** [comment]
I'll update the PR, thanks for the ping 👍

**Comment by michaelbwebb** [comment]
@nmussy  If I'm understanding this correctly, CDK L1 constructs are not supporting this feature yet due to CloudFormation limitations. I am catching myself up to speed with my CDK skills and wanted to verify I am following this thread correctly

**Comment by nmussy** [comment]
#30354 just added support for the recently added CloudFormation properties listed [here](https://github.com/aws/aws-cdk/issues/29617#issuecomment-2130225676). [scalingConfiguration](https://docs.aws.amazon.com/codebuild/latest/APIReference/API_Fleet.html#CodeBuild-Type-Fleet-scalingConfiguration) is still missing from the CloudFormation construct
