### ISSUE TITLE
Feature Request: Configurable minimumHealthyPercent and maximumHealthyPercent for ECS Service Hotswap

### ISSUE THREAD

**Issue by rexrafa** [aws/aws-cdk#29618]
### Describe the feature

Currently, when using the --hotswap flag for deploying ECS services, the **minimumHealthyPercent** is hardcoded to 0, which can be disruptive for services with interdependencies. This can result in downtime as the current tasks are stopped before the new ones are fully up and running. To improve the flexibility of hotswap deployments, allowing users to set the minimumHealthyPercent and maximumHealthyPercent parameters would be beneficial.

### Use Case

We aim to speed up deployment times in our development environment by using the hotswap feature. However, our services have dependencies on each other, and the current hotswap behavior is too disruptive. We want to keep the current tasks running until the new ones are fully operational. Configuring minimumHealthyPercent and maximumHealthyPercent would give us the control needed to ensure smoother transitions during deployments.

### Proposed Solution

Modify the ECS service hotswap implementation to accept minimumHealthyPercent and maximumHealthyPercent as configurable parameters, with default values of 0 and 200, respectively. These parameters should be exposed in the CDK, allowing users to override them as needed.

For example, the current implementation at:

https://github.com/aws/aws-cdk/blob/0fee99b473c17210a156d74263227cdf3274d253/packages/aws-cdk/lib/api/hotswap/ecs-services.ts#L108

It could be modified to accept these parameters from the user's CDK stack configuration.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.117.0

### Environment details (OS name and version, etc.)

Darwin Kernel Version 23.3.0

**Comment by tim-finnigan** [comment]
Thanks for the feature request. I saw some related discussion on this topic and @pahud's comment here: https://github.com/aws/aws-cdk/discussions/22241#discussioncomment-3754599

>I am not sure if this is a good default value but I believe if you run an ecs service with just single task with maximumHealthyPercent=100 and you need force the task update, you probably have to set the minimumHealthyPercent to 0 otherwise the only task might not be replaced unless maximumHealthyPercent is set to 200. However, with maximumHealthyPercent=200 the new deployment will have to bring up an additional healthy task before it can terminate the original one. If the additional one is not in healthy state min>0 max>100 might not be able to replace the only task. With min=0, the only task will be immediately tore down and replaced.
>
>As cdk hot swap is designed for development only I believe setting min=0 makes sense here.

I think this request needs some further review and discussion, would be interested to get your thoughts on that comment.

**Comment by dysosmus** [comment]
@tim-finnigan , answering for my co-worker @rexrafa as he is OoO.

We mostly agree with @pahud's comment that `min=0` is a good default and shouldn't be changed as the default value.
Our opinion is that allowing the user to customize that value will enable them to determine the exact trade-off between speed, safety, and cost they desire in their development process. It also helps to better account for development environments where ECS Services run more than a single task.
