### ISSUE TITLE
aws-events-targets: Hardcoded AWS Partition in ECS task resource ARN

### ISSUE THREAD

**Issue by 1somorphism** [aws/aws-cdk#29610]
### Describe the bug

Partition in https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-events-targets/lib/ecs-task.ts#L291 is hardcoded to `aws` so it doesn't work for other special partitions.

### Expected Behavior

Partition should be coming from `this.cluster.env.partition`?

### Current Behavior

Fixed to `aws`

### Reproduction Steps

Cannot provide. I'm an AWS employee and the snippet / reproduction steps could possibly contain confidential information.

### Possible Solution

Partition should be coming from `this.cluster.env.partition`?

### CDK CLI Version

2.132.1

### Node.js Version

18.18.2

### OS

MacOS 14.3.1

### Language

TypeScript

### Language Version

5.4.2

**Comment by tim-finnigan** [comment]
Thanks for reporting this issue. It looks like that was recently added in https://github.com/aws/aws-cdk/pull/28898, and the partition should be dynamically populated.

**Comment by tim-finnigan** [comment]
https://github.com/aws/aws-cdk/pull/29633 has been merged to fix this and should be available soon in an upcoming release.

**Comment by paulhcsun** [comment]
Fix has been released in  `v2.135.0`.
