### ISSUE TITLE
(aws_ecs.FargateTaskDefinition): (support for pidMode)

### ISSUE THREAD

**Issue by ssplatt** [aws/aws-cdk#29619]
### Describe the bug

ecs.TaskDefinition supports `pidMode`. ecs.FargateTaskDefinition should as well.

### Expected Behavior

supports `pidMode`

### Current Behavior

does not support pidMode

### Reproduction Steps

try to use `pidMode` as an arg

### Possible Solution

add support for `pidMode`

### CDK CLI Version

2.133.0

### Node.js Version

18

### OS

mac os

### Language

TypeScript

**Comment by ssplatt** [comment]
https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ecs.FargateTaskDefinition.html (no `pidMode`)
https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ecs.TaskDefinition.html#construct-props (has `pidMode`)

**Comment by tim-finnigan** [comment]
Thanks for reporting this issue, it looks like `pidMode` should be supported.

**Comment by shuluster** [comment]
Resource handler returned message: "Invalid request provided: Create TaskDefinition: Tasks using the Fargate launch type do not support pidMode 'host'. The supported value for pidMode is 'task'. (Service: AmazonECS; Status Code: 400; Error Code: ClientException; Request ID: a75d06a4-dc4c-4209-b464-d33e0ba66f0a; Proxy: null)" (RequestToken: 20902d22-1d4f-1a6e-2db1-ddf7b63bb7b1, HandlerErrorCode: InvalidRequest)
