### ISSUE TITLE
Mismatch between EKS AMI and Kubernetes version

### ISSUE THREAD

**Issue by abelmokadem** [aws/aws-cdk#2963]
**Describe the bug**
The version for EKS is being selected based on what the hardcoded latest version is, in the codebase. Which is `1.11` [source](https://github.com/awslabs/aws-cdk/blob/v0.35.0/packages/@aws-cdk/aws-eks/lib/ami.ts#L35). However, specifying no version for EKS at all creates `1.12` based on what CloudFormation decides for you.

**To Reproduce**
Create an EKS cluster and worker nodes without specifying any version.

**Expected behavior**
I would like to see the same AMI being used as the Kubernetes version that CloudFormation is selecting for EKS.

**Version:**
 - OS X
 - Typescript
 - CDK 0.33.0 (still the same in 0.35.0)

**Comment by abelmokadem** [comment]
I want to add to this that I don't think that it's a good idea to support creating a cluster without specifying which Kubernetes version you would like to use. I created a small "decision" graph to elaborate.

<img width="972" alt="Screen Shot 2019-06-20 at 16 12 16" src="https://user-images.githubusercontent.com/9717944/59855939-3d935300-9376-11e9-8ff8-b703fbddf859.png">

Maybe there is a simpler solution. Implementing something like this would seem a bit brittle.

**Comment by NGL321** [comment]
After a brief bit of research, it looks like Cloudformation [automatically assigns the latest version](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-eks-cluster.html) of Kubernetes supported by EKS ([currently 1.3](https://github.com/aws/containers-roadmap/issues/30)).
I will have to look into this further because you are seeing 1.12, and really it should be 1.13, and we have it set to 1.1.

**Comment by Aspekt112** [comment]
Any progress on this?

**Comment by eladb** [comment]
I think the best we can do here is to hard-code the default version within the CDK so we can pick the right AMI. Currently AMI IDs are stored within the CDK and if a new version comes out, we will have to add those IDs to the construct library anyway. Thoughts?

**Comment by moofish32** [comment]
Any chance we can use the lambda later with aws cli to look up the correct AMI in a custom resource? I have to imagine we will forget this manual step at least once or Eks will update when it’s a bad time to release etc.

**Comment by eladb** [comment]
If we hard-code the default, there will not be unsolicited updates to it.

**Comment by abelmokadem** [comment]
By default, do you mean that this version will change over time with new releases of eks? In that case, is it expected behaviour that if you upgrade the CDK version, that you might also be updating your EKS + AMI versions? I'm a fan of removing this option entirely and just forcing people to choose a version, this is less user-friendly, but it avoids any confusion on which version will be deployed.

While writing this, I'm still confused about the functionality. If I don't specify a version for my EKS cluster, according to this you will not specify a version and use the default version of Amazon:

https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-eks/lib/cluster.ts#L137-L142

Then if I look at this code:

https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-eks/lib/ami.ts#L25-L33

You are fetching the latest version of the CDK stack. According to what I see here, there are bound to be some mismatches in the future.

*Scenario 1*
If amazon releases 1.14 and makes it the default version and I'm using this version of CDK and I deploy an EKS cluster without a version, then I will get an EKS cluster with 1.14 and AMI of 1.13. 

*Scenario 2*
The same problem can occur the other way around. If I have an existing stack with no version specified and my EKS cluster is running on version 1.12 and I'm upgrading my CDK to this version, then the AMI will change to 1.13.

Are these two scenarios correct? If so, why can't we just make the version number mandatory?

**Comment by eladb** [comment]
I am leaning towards making the version explicit. Seems like any automatic selection of a version will result in non-deterministic behavior.

**Comment by eladb** [comment]
@pahud I am curious what you think about this?

**Comment by pahud** [comment]
If we check `eksctl`, when no version specified, it [goes to](https://github.com/weaveworks/eksctl/blob/950f9bc695234107725234b9e1a9c9d2ee54e51f/pkg/ctl/create/cluster.go#L106-L108) `api.DefaultVersion`, which is hard-coded [here](https://github.com/weaveworks/eksctl/blob/fc59b684b69ba46a17bc4e0e9fbe457aa096157d/pkg/apis/eksctl.io/v1alpha5/types.go#L89-L90). At this moment, the default version is `1.13`, which aligns to the Amazon EKS console default value.

<img width="479" alt="圖片" src="https://user-images.githubusercontent.com/278432/64491745-64d72d80-d29e-11e9-88e6-8adb3f2c4706.png">

It would be better we stick to `eksctl` and when `1.14` becomes a new default version ,I believe `eksctl` will have a version bump with `1.14` as the new `api.DefaultVersion` and CDK should also upgrade the default version in the next release.

In `aws-samples/amazon-eks-refarch-cloudformation`,  I also hardcoded `1.13` as current default:

https://github.com/aws-samples/amazon-eks-refarch-cloudformation/blob/525741289298bba8cfa4e8229d09b92ac8c00609/cloudformation/cluster.yaml#L43-L47

Now the question is, what will happen if user `cdk deploy` the existing app/stack with new default version? Technically it will trigger the cluster update from `1.13` to `1.14` with new AMI update as well, unless you explicitly specify your cluster version in CDK to avoid accidental upgrade. However, that is just how cloudformation works.

On the other hand, I agree CDK can display some friendly warning messages after user just run `cdk deploy`.

For example:

_Version mismatch detected. The deployment is about to upgrade your cluster or nodegroud. During this time the control plane may be inactive until the upgrade complete. Check [Amazon EKS doc](https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html) for more details. Continue? (y/n)_

Would be nice to have. This also shows CDK can do far more than cloudformation. :-)

**Comment by zanhsieh** [comment]
Agree with Pahud. I would say we adapt the similar behavior just like other IaCs do, e.g. KOPS, Terraform, etc. In KOPS, it will show the warning message that tips the user to upgrade till the user particularly says so, which this behavior has been wide-adapted since 2016. This might not a desire behavior for some people (why it spends my precious time to query which version is the latest one?), but CDK does not suppose to handle all EKS / K8S and its subsidiaries (e.g. CNI / CSI) upgrade issues; doing so would force CDK closely coupled with EKS.

CDK is CDK; it has its own mission to fulfil.

**Comment by eladb** [comment]
Duplicate #7762
