### ISSUE TITLE
RDS: support passing PreferredMaintenanceWindow to Cluster's writer and reader instances

### ISSUE THREAD

**Issue by Konosh93** [aws/aws-cdk#29687]
### Describe the bug

Related:
- https://github.com/aws/aws-cdk/issues/16954

When creating a DatabaseCluster it should be possible to specify PreferredMaintenanceWindow property for the database instances as per https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbinstance.html#cfn-rds-dbinstance-preferredmaintenancewindow

### Expected Behavior

Should be able specify the writer and readers PreferredMaintenanceWindow prop without using the deprecated instanceProps property.

Expected style:
```ts
new DatabaseCluster(stack, 'DatabaseCluster', {
  engine: DatabaseClusterEngine.AURORA,
  vpc: vpc,
  writer: ClusterInstance.provisioned('Instance1', {
    preferredMaintenanceWindow: 'Sat:22:15-Sat:22:45',
  }),
  preferredMaintenanceWindow: 'Sat:22:15-Sat:22:45',
});
```

### Current Behavior

Can specify the PreferredMaintenanceWindow prop only through `instanceProps`:

```ts
declare const vpc: ec2.Vpc;
new rds.DatabaseCluster(this, 'DatabaseCluster', {
  engine: rds.DatabaseClusterEngine.AURORA,
  instanceProps: {
    vpc: vpc,
    preferredMaintenanceWindow: 'Sun:23:15-Sun:23:45',
  },
  preferredMaintenanceWindow: 'Sat:22:15-Sat:22:45',
});
```

### Reproduction Steps

Trying adding `preferredMaintenanceWindow` to writer or readers props:

```ts
new DatabaseCluster(stack, 'DatabaseCluster', {
  engine: DatabaseClusterEngine.AURORA,
  vpc: vpc,
  writer: ClusterInstance.provisioned('Instance1', {
    preferredMaintenanceWindow: 'Sat:22:15-Sat:22:45', // Typescript error and wont be reflected in the synthesized templates
  }),
  preferredMaintenanceWindow: 'Sat:22:15-Sat:22:45',
});
```

### Possible Solution

feat(rds): allow specifying PreferredMaintenanceWindow in RDS cluster instances using the new api

- https://github.com/aws/aws-cdk/pull/29686

### CDK CLI Version

1.158.0

### Node.js Version

v18.17.1

### OS

Linux

### Language

TypeScript

### Language Version

5.1.6

**Comment by khushail** [comment]
Thanks @Konosh93  for reaching out and submitting a PR !

**Comment by Konosh93** [comment]
Fixed in:
- https://github.com/aws/aws-cdk/pull/29686
