### ISSUE TITLE
(crossRegionReference): error logging for throwIfAnyInUse fails to log exports in use

### ISSUE THREAD

**Issue by elliotsegler** [aws/aws-cdk#29699]
### Describe the bug

Discovered whilst debugging an issue with cross-stack exports, it looks like the error message logic that would identify which exports are in use by which stack is broken.

https://github.com/aws/aws-cdk/blob/36fd79d8714bd29527bb1184ec10cd504b83510d/packages/%40aws-cdk/custom-resource-handlers/lib/core/cross-region-ssm-writer-handler/index.ts#L104-L109

In my case, there _are_ `tagResults` but the results aren't mapped into the error message, so you just get a clear line in the error message.

### Expected Behavior

The error message to identify which exports are in use by which stacks.

For example:
```
Received response status [FAILED] from custom resource. Message returned: Error: Exports cannot be updated:
/cdk/exports/MyTestExportStack/MyResourceExport is in use by stack(s) MyTestConsumerStack

at i (/var/task/index.js:4:10)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async P (/var/task/index.js:3:184)
at async Runtime.handler (/var/task/__entrypoint__.js:1:932)
```

### Current Behavior

Error message doesn't include the content

Example
```
Received response status [FAILED] from custom resource. Message returned: Error: Exports cannot be updated:

at i (/var/task/index.js:4:10)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async P (/var/task/index.js:3:184)
at async Runtime.handler (/var/task/__entrypoint__.js:1:932)
```

this appears to be the case in a number of issues:
https://github.com/aws/aws-cdk/issues/27251
https://github.com/aws/aws-cdk/issues/28200
https://github.com/aws/aws-cdk/issues/24464
https://github.com/aws/aws-cdk/issues/27902

### Reproduction Steps

Create a cross region stack that uses an export, and then try to destroy the exporting stack first

### CDK CLI Version

2.118.0 (build a40f2ec)

### Node.js Version

v18.9.0

### OS

arn:aws:lambda:us-east-1::runtime:464db84005d4f68e67934a6df703e04e6e8782a50ec2882673a8e1c996ab814a

### Language

TypeScript

**Comment by andreialecu** [comment]
PR at #29961 with fix.
