### ISSUE TITLE
aws-apigateway: Documentation lacks information about stack separation for RestApi and Resources

### ISSUE THREAD

**Issue by engineer-taro** [aws/aws-cdk#29690]
### Overview

In this documentation, I would like to note that when separating the stacks for `RestApi` and `Resource`, `Deployment` is not automatically created, and to avoid this issue, it is necessary to use `Deployment.addToLogicalId()`.

### Details

When a `Resource` is added to an `IRestApi` imported via `RestApi.fromRestApiAttribute` or `RestApi.fromRestApiId`, `Deployment` is not created, so the latest resource state is not associated with the API Gateway stage, which is a known issue.
This has been discussed in several issues, including the following:

- https://github.com/aws/aws-cdk/issues/13526
- https://github.com/aws/aws-cdk/issues/29079

We understand that it is not easy to automatically create Deployment, and there may be differing opinions on whether it should be fixed.
However, since there is no mention of this issue in the documentation, we feel that many developers who are separating stacks related to API Gateway may unintentionally create an environment where `Deployment` is not created.
Due to this issue, developers need to manually deploy to API Gateway after running `cdk deploy`.

While it is possible to share a workaround implementation, it is difficult to implement an automatic `Deployment` creation that detects changes in `Resource` without increasing complexity in the current configuration.

Therefore, we would like to propose adding a note to the documentation first.

### Links

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_apigateway-readme.html#breaking-up-methods-and-resources-across-stacks

**Comment by tim-finnigan** [comment]
Thanks for creating the issue/PR. There is a note in https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_apigateway.Deployment.html that says:

> Normally, you don't need to define deployments manually. The RestApi construct manages a Deployment resource that represents the latest model. It can be accessed through `restApi.latestDeployment` (unless `deploy: false` is set when defining the `RestApi`).
> 
> If you manually define this resource, you will need to know that since deployments are immutable, as long as the resource's logical ID doesn't change, the deployment will represent the snapshot in time in which the resource was created. This means that if you modify the RestApi model (i.e. add methods or resources), these changes will not be reflected unless a new deployment resource is created.
> 
> To achieve this behavior, the method `addToLogicalId(data)` can be used to augment the logical ID generated for the deployment resource such that it will include arbitrary data. This is done automatically for the `restApi.latestDeployment` deployment.

[Also here](https://github.com/aws/aws-cdk/issues/29079#issuecomment-2026174741) is a link to another workaround in that latter issue you referenced. 

Maybe further clarification is needed in the docs but I'm not sure about just linking https://github.com/aws/aws-cdk/issues/13526 in your PR.
