### ISSUE TITLE
pythonfunction: BundlingOptions/Bundling Props interface mismatch

### ISSUE THREAD

**Issue by automartin5000** [aws/aws-cdk#29697]
### Describe the bug

In the PythonFunction construct, `bundling` [expects](https://github.com/aws/aws-cdk/blob/70dc4e8e8ca94694a732989d9c8233ab14c83b00/packages/%40aws-cdk/aws-lambda-python-alpha/lib/function.ts#L44) `BundlingOptions`. However, the actual `bundle` method [expects](https://github.com/aws/aws-cdk/blob/70dc4e8e8ca94694a732989d9c8233ab14c83b00/packages/%40aws-cdk/aws-lambda-python-alpha/lib/bundling.ts#L20) `BundleProps`.

### Expected Behavior

I think the expected behavior [of this code](https://github.com/aws/aws-cdk/blob/70dc4e8e8ca94694a732989d9c8233ab14c83b00/packages/%40aws-cdk/aws-lambda-python-alpha/lib/function.ts#L79), is that the spread operator will allow you specify whatever additional options you want. 

### Current Behavior

Given the type mismatch, I believe it then resolves any missing props from BundlingProps to `never`. For example, this means that if you give any value for `bundling`, that it's impossible to specify `Architecture`, as that doesn't exist on `BundlingOptions`.

### Reproduction Steps

Set a new image for a PythonFunction in `bundling`, set `Architecture` to `Architecture.ARM64`. Set the `platform` value to `linux/arm64`. Docker still attempts to build with x86.

### Possible Solution

The expected type for `bundling` should be `BundlingProps`, not `BundlingOptions`.

### CDK CLI Version

2.135.0

### Node.js Version

20

### OS

macOS Sonoma

### Language

Python

### Language Version

3.12

**Comment by Leo10Gama** [comment]
I'm not too sure what the source of the issue is here. The parameters you've mentioned such as `architecture` are passed in when `bundle()` is called via the `PythonFunctionProps` constructor itself, and it's not possible to pass in that value via `bundling` for it to get overwritten, since `BundlingOptions` doesn't expect that value.

If you could provide a full snippet showing where you're running into problems, I can help resolve things better.

**Comment by automartin5000** [comment]
I'll work on trying to replicate this issue this week.

**Comment by automartin5000** [comment]
Ok, this looks like it might be a bug on our side, so I'm gonna close for now.
