### ISSUE TITLE
sns: Support for TracingConfig

### ISSUE THREAD

**Issue by jun1-t** [aws/aws-cdk#29714]
### Describe the feature

Enable setting of TracingConfig in the L2 construct for SNS topics.
https://docs.aws.amazon.com/sns/latest/dg/sns-active-tracing.html### 

### Use Case

Currently, to set the TracingConfig, it is necessary to configure it via L1.
https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_sns.CfnTopic.html#tracingconfig

### Proposed Solution

Allows passing the "TracingConfig" parameter as an argument.
```ts
const topic = new sns.Topic(this, 'MyTopic', {
  tracingConfig: 'Active',
});
```

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.135.0

### Environment details (OS name and version, etc.)

irrelevant

**Comment by khushail** [comment]
Thanks @jun1-t for reaching out and submitting a PR for the same.
