### ISSUE TITLE
(ecs): ContainerDefinition.addDockerLabel

### ISSUE THREAD

**Issue by blimmer** [aws/aws-cdk#29728]
### Describe the feature

It would be nice to be able to add docker labels _after_ the container has been constructed.

For example, I can call `addEnvironment` to add an environment variable after the fact: https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ecs.ContainerDefinition.html#addwbrenvironmentname-value

However, I can't do the same with docker labels.

### Use Case

I have a construct that automatically applies Datadog monitoring information to a TaskDefinition with an application container. [Datadog requires](https://docs.datadoghq.com/integrations/faq/integration-setup-ecs-fargate/?tab=rediswebui) that I set some information as Docker Labels for observability:

![Screenshot 2024-04-04 at 12 23 53](https://github.com/aws/aws-cdk/assets/630449/ec04ac2b-5674-4b7e-859d-e5450a743722)

However, I want to add these labels _after_ the user already created their default container.

### Proposed Solution

Add a `.addDockerLabel` method similar to `.addEnvironment` to the `ContainerDefiniton` construct. It'd be similar to https://github.com/aws/aws-cdk/issues/2559 / https://github.com/aws/aws-cdk/pull/17889

### Other Information

You can hack this like so:

```ts
const defaultContainerAsAny = defaultContainer as any;
defaultContainerAsAny.props.dockerLabels = Object.assign(defaultContainerAsAny.props.dockerLabels || {}, {
  "com.datadoghq.tags.env": this.env,
  "com.datadoghq.tags.service": serviceName,

  // TODO: The ECS CircleCI orb doesn't expose the ability to set `dockerLabels` when deploying
  // a task definition update. See https://github.com/CircleCI-Public/aws-ecs-orb/issues/119
  // "com.datadoghq.tags.version": "",

  "com.datadoghq.ad.instances": JSON.stringify([
    { host: "%%host%%", port: defaultContainer.portMappings.length ? defaultContainer.ingressPort : null },
  ]),
  "com.datadoghq.ad.check_names": JSON.stringify([serviceName]),
  "com.datadoghq.ad.init_configs": JSON.stringify([{}]),
});
```

But it's not ideal

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.135.0

### Environment details (OS name and version, etc.)

MacOS Sonoma

**Comment by khushail** [comment]
@blimmer ,thanks for reaching out with this request and volunteering for PR contribution.

**Comment by blimmer** [comment]
@khushail - I'm not sure when I'll be able to get to this. Would you mind also throwing a "good first issue" tag on it?

**Comment by khushail** [comment]
> @khushail - I'm not sure when I'll be able to get to this. Would you mind also throwing a "good first issue" tag on it?

done!

**Comment by alpha951** [comment]
Hey @khushail , I'm looking for my first contribution here. Could you please assign this issue to me?

**Comment by khushail** [comment]
Thanks @alpha951 for volunteering to contribute. This is the [contribution guide](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md#step-1-find-something-to-work-on) to get started.

**Comment by alpha951** [comment]
Let me know if there are any other beginner friendly issues are still open.

**Comment by khushail** [comment]
> Let me know if there are any other beginner friendly issues are still open.

You can filter out the issues with label "good first issue" and would get a list like [this](https://github.com/aws/aws-cdk/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) and can pick to work on any issue, you want
