### ISSUE TITLE
aws-synthetics: NodeJS puppeteer Runtime Versions 7.0 & Python Selenium 3.0

### ISSUE THREAD

**Issue by npvisual** [aws/aws-cdk#29724]
### Describe the feature

Please see earlier issue reported in https://github.com/aws/aws-cdk/issues/29135#issue-2138456748.

This is a similar request but for Synthetics NodeJS runtime version 7.0 and Synthetics Python runtime version 3.0, which are now available.

See also the [announcement](https://aws.amazon.com/about-aws/whats-new/2024/03/synthetics-node-js-runtime-version-7-0-python-runtime-3-0-amazon-cloudwatch-synthetics/), the recommendation in the canaries config page and the planned lifecycle event :

![Screenshot 2024-04-04 at 9 22 44 AM](https://github.com/aws/aws-cdk/assets/3268395/7d3cd904-4e9c-4f4c-9ace-60c32b442ee4)

![Screenshot 2024-04-04 at 9 10 46 AM](https://github.com/aws/aws-cdk/assets/3268395/274f4259-cf24-469e-8616-1c1cc0086e0d)

Note that, as opposed to the previous announcement, those versions do exist in the latest CDK version.

### Use Case

Availability of newer version of synthetics platforms.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.135.0

### Environment details (OS name and version, etc.)

MacOS 14.4.1

**Comment by msambol** [comment]
@npvisual I see these were added in https://github.com/aws/aws-cdk/pull/29446 by @nmussy.

**Comment by npvisual** [comment]
> @npvisual I see these were added in #29446 by @nmussy.

Ok, great. I'll close this issue then. Thanks !
