### ISSUE TITLE
aws_mediaconvert: CfnJobTemplate cannot disable tags

### ISSUE THREAD

**Issue by ShawnOY** [aws/aws-cdk#29755]
### Describe the bug

CfnJobTemplate will add 3 tags:

1. aws:cloudformation:stack-name
2. aws:cloudformation:stack-id
3. aws:cloudformation:logical-id

If I create a job via template, I will get the error message:
One or more tag keys start with the reserved prefix 'aws:' (case insensitive).

### Expected Behavior

The tags add by CDK, it should be pass.

### Current Behavior

One or more tag keys start with the reserved prefix 'aws:' (case insensitive).

### Reproduction Steps

```ts
new mediaconvert.CfnJobTemplate(this, 'MediaHubJobTemplate', {
  name: 'MediaHub',
  // This is not work
  tags: {},
  settingsJson: {
  }
}
```

### CDK CLI Version

2.134.0

### Node.js Version

v18.14.2

### OS

maxOS Ventura 13.2.1

### Language

TypeScript

**Comment by pahud** [comment]
Did you mean even you specify empty `tags`, the job template will still have the 3 build-in tags?

```
aws:cloudformation:stack-name
aws:cloudformation:stack-id
aws:cloudformation:logical-id
```

```ts
new mediaconvert.CfnJobTemplate(this, 'MediaHubJobTemplate', {
  name: 'MediaHub',
  // This is not work
  tags: {},
  settingsJson: {
  }
}
```

**Comment by ShawnOY** [comment]
> Did you mean even you specify empty `tags`, the job template will still have the 3 build-in tags?
> 
> ```
> aws:cloudformation:stack-name
> aws:cloudformation:stack-id
> aws:cloudformation:logical-id
> ```
> 
> ```ts
> new mediaconvert.CfnJobTemplate(this, 'MediaHubJobTemplate', {
>   name: 'MediaHub',
>   // This is not work
>   tags: {},
>   settingsJson: {
>   }
> }
> ```

Yes

**Comment by ShawnOY** [comment]
@pahud 
I reported the issue to AWS support, and they have resolved it.
