### ISSUE TITLE
IAM/Groups/S3: Default policy replaced when group imported with from_group_arn, then bucket.grant_read(group)

### ISSUE THREAD

**Issue by sklibanov312** [aws/aws-cdk#29762]
### Describe the bug

Consider 3 CDK stacks, communicating with SSM string parameters.

GroupStack - creates an IAM Group, and writes its ARN to an SSM String parameter
FirstBucketStack - Gets the group ARN from SSM parameter, creates the first bucket, grants the group read permission to that bucket.
SecondBucketStack - Gets the group ARN from SSM parameter, creates the second bucket, grants the group read permission to that bucket.

Deploy them in that order.

### Expected Behavior

Expected behavior is that the group's policy now allows reading from both the first and second buckets, after all 3 stacks are deployed.

### Current Behavior

Current behavior is that the group's policy contains read permission for only one bucket. The other bucket is totally absent.

### Reproduction Steps

Unzip the attached file [stacks.zip](https://github.com/aws/aws-cdk/files/14906853/stacks.zip)

.

1. `cd group`
2. `cdk deploy GroupStack`
3. In the AWS Management Console in the IAM page, find the group. Note that it has no policies and no users. Fine.
4. `cd ../firstbucket`
5. `cdk deploy FirstBucketStack`
6. Observe that there's now a `readergroupDefaultPolicyNNNNN` which grants GetBucket, GetObject, st:List* to the Resources `arn:aws:s3:::firstbucketstack-firstbucketNNNNN` . So far so good
7. `cd ../secondbucket`
8. `cdk deploy SecondBucketStack`
9. Observe that the `readergroupDefaultPolicyNNNNN` has changed to only mention the `arn:aws:s3:::secondbucketstack-secondbucketNNNNN` and any mention of the first bucket is now gone.

If you go on to delete the SecondBucketStack, you'll see that the policy is gone completely. You have to destroy and re-create the FirstBucketStack, then, to get permissions added.

### Possible Solution

Should the CDK create a new policy document in these cases, instead of editing the default? 

### Additional Information/Context

If you change the situation to add some kind of default policy to the group in the group stack (e.g. s3:ListAllMyBuckets) then it will also get replaced.

Decoupling stacks from each other completely and communicating resources from one stack to another with the SSM Parameter Store is important to our wider use case. 

### CDK CLI Version

2.135.0 (build d46c474)

### Node.js Version

v18.19.1

### OS

Debian 12

### Language

Python

### Language Version

Python (3.11.2)

**Comment by sklibanov312** [comment]
Just for convenience, here's the most important parts of all 3 stacks:

group stack:
```
        group = iam.Group(self, 'reader-group')

        ssm.StringParameter(self, "reader-group-arn-parameter",
                            parameter_name='/group-arn',
                            string_value=group.group_arn)
```

first bucket stack:
```
        group_arn = ssm.StringParameter.value_from_lookup(self, '/group-arn')
...
        group = iam.Group.from_group_arn(self, 'reader-group', group_arn)
        first_bucket = s3.Bucket(...)
        first_bucket.grant_read(group)
```

Second bucket stack looks pretty much the same as the first.

**Comment by ashishdhingra** [comment]
**Findings:**
- Deploying FirstBucketStack creates default policy with Logical ID, let's say `readergroupDefaultPolicy1F226D05` (with physical ID `First-reade-xMHcCmPunTUu`):
```JSON
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "s3:GetBucket*",
                "s3:GetObject*",
                "s3:List*"
            ],
            "Resource": [
                "arn:aws:s3:::firstbucketstack-firstbucket918e3579-woyilreurmh2",
                "arn:aws:s3:::firstbucketstack-firstbucket918e3579-woyilreurmh2/*"
            ],
            "Effect": "Allow"
        }
    ]
}
```
- Thereafter, deploying SecondBucketStack creates default policy with same Logical ID `readergroupDefaultPolicy1F226D05` (with physical ID `Secon-reade-EG03HblxbJMY`):
```JSON
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "s3:GetBucket*",
                "s3:GetObject*",
                "s3:List*"
            ],
            "Resource": [
                "arn:aws:s3:::secondbucketstack-secondbucketb073b450-hcg2ukqliqzo",
                "arn:aws:s3:::secondbucketstack-secondbucketb073b450-hcg2ukqliqzo/*"
            ],
            "Effect": "Allow"
        }
    ]
}
```
  It appears that the existing policy `readergroupDefaultPolicy1F226D05` is modified (instead of amended, or new policy created all together).
- Deleting SecondBucketStack (using `cdk destroy SecondBucketStack`), deleted the bucket, but doesn't appear to remove policy (may be because first bucket has it's reference somehow).
- Deleting FirstBucketStack (using `cdk destroy FirstBucketStack`), deleted the bucket and also now deletes the policy.

Needs review with the team.

**Comment by pahud** [comment]
Off the top of my head, this is because when you [grantRead() ](https://github.com/aws/aws-cdk/blob/92a160bb0a2c6ca528fc3f4e3ca036d0c70e6ca5/packages/aws-cdk-lib/aws-s3/lib/bucket.ts#L768)you are actually [addToPrincipalOrResource()](https://github.com/aws/aws-cdk/blob/92a160bb0a2c6ca528fc3f4e3ca036d0c70e6ca5/packages/aws-cdk-lib/aws-s3/lib/bucket.ts#L972-L977). And according to the description [here](https://github.com/aws/aws-cdk/blob/92a160bb0a2c6ca528fc3f4e3ca036d0c70e6ca5/packages/aws-cdk-lib/aws-iam/lib/grant.ts#L108-L121), you can't do it twice on the same grantee.

I will provide some suggested sample for you later.

**Comment by ashishdhingra** [comment]
> Off the top of my head, this is because when you [grantRead() ](https://github.com/aws/aws-cdk/blob/92a160bb0a2c6ca528fc3f4e3ca036d0c70e6ca5/packages/aws-cdk-lib/aws-s3/lib/bucket.ts#L768)you are actually [addToPrincipalOrResource()](https://github.com/aws/aws-cdk/blob/92a160bb0a2c6ca528fc3f4e3ca036d0c70e6ca5/packages/aws-cdk-lib/aws-s3/lib/bucket.ts#L972-L977). And according to the description [here](https://github.com/aws/aws-cdk/blob/92a160bb0a2c6ca528fc3f4e3ca036d0c70e6ca5/packages/aws-cdk-lib/aws-iam/lib/grant.ts#L108-L121), you can't do it twice on the same grantee.
> 
> I will provide some suggested sample for you later.

@pahud Edited my comment https://github.com/aws/aws-cdk/issues/29762#issuecomment-2043754096 with more findings.

**Comment by sklibanov312** [comment]
So, I have a different local workaround which creates a separate policy document for each of the buckets, like this:

```
        imported_group.attach_inline_policy(iam.Policy(context, policyName,
                                                          statements=[iam.PolicyStatement(
                                                              actions=[
                                                                  "s3:GetBucket*",
                                                                  "s3:GetObject*",
                                                                  "s3:List*"
                                                              ],
                                                              resources=[bucket.bucket_arn, bucket.bucket_arn + '/*'],
                                                              effect=iam.Effect.ALLOW)]))
```

instead of using `greant_read`. It seems to be behaving the way I want. So I have a workaround - well, two now - one using a role per your suggestion and the other using a separate policy document like I just pasted. Great.

But that doesn't actually resolve the spirit of this issue.

I think to resolve the spirit of the issue, the CDK implementation itself must be changed to prevent my original bug report from being silently buggy. It must either loudly fail, or (ideally) work according to expectations.
