### ISSUE TITLE
FIS: Experiment Template Log Configuration Class Camel Cases LogGroupArn

### ISSUE THREAD

**Issue by hakenmt** [aws/aws-cdk#29761]
### Describe the bug

Using the `CfnExperimentTemplate` construct in .net. Using the below log group configuration.

```csharp
LogConfiguration = new ExperimentTemplateLogConfigurationProperty() {
                    CloudWatchLogsConfiguration = new CloudWatchLogsConfigurationProperty() {
                        LogGroupArn = this.LogGroup.LogGroupArn
                    }
                }
```

This produces output like the following:

```json
"LogConfiguration": {
     "CloudWatchLogsConfiguration": {
      "logGroupArn": {
       "Fn::GetAtt": [
        "logGroup68A52FBE",
        "Arn"
       ]
      }
     },
     "LogSchemaVersion": 0
    },
```

The property `logGroupArn` isn't accepted by CloudFormation, it must be `LogGroupArn`.

### Expected Behavior

Produces this output:

```json
"LogConfiguration": {
     "CloudWatchLogsConfiguration": {
      "LogGroupArn": {
       "Fn::GetAtt": [
        "logGroup68A52FBE",
        "Arn"
       ]
      }
     },
     "LogSchemaVersion": 0
    },
```

### Current Behavior

Produces camel case name.

### Reproduction Steps

```csharp
LogConfiguration = new ExperimentTemplateLogConfigurationProperty() {
                    CloudWatchLogsConfiguration = new CloudWatchLogsConfigurationProperty() {
                        LogGroupArn = this.LogGroup.LogGroupArn
                    }
                }
```

### CDK CLI Version

2.133.0 (build dcc1e75)

### Node.js Version

v20.9.0

### OS

darwin

### Language

.NET

**Comment by nmussy** [comment]
Confirmed in TypeScript and with `v2.136.0`, this is an issue with the generated L1 interface. See also the [`AWS::FIS::ExperimentTemplate CloudWatchLogsConfiguration` CloudFormation docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-fis-experimenttemplate-cloudwatchlogsconfiguration.html#cfn-fis-experimenttemplate-cloudwatchlogsconfiguration-loggrouparn)

```ts
import { CfnExperimentTemplate } from 'aws-cdk-lib/aws-fis';

// ...
const config: CfnExperimentTemplate.ExperimentTemplateLogConfigurationProperty = {
  cloudWatchLogsConfiguration: { logGroupArn: 'arn' },
  logSchemaVersion: 0,
};

new cdk.CfnOutput (this, 'ExperimentTemplateLogConfiguration', {
  value: JSON.stringify(config),
});
```

```sh
$ npm run cdk synth

Outputs:
  ExperimentTemplateLogConfiguration:
    Value: '{"cloudWatchLogsConfiguration":{"logGroupArn":"arn"},"logSchemaVersion":0}'
```

`aws-cdk-lib/aws-fis/lib/fis.generated.d.ts`:
```ts
/**
 * Specifies the configuration for experiment logging to CloudWatch Logs .
 *
 * @struct
 * @stability external
 * @see http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-fis-experimenttemplate-cloudwatchlogsconfiguration.html
 */
interface CloudWatchLogsConfigurationProperty {
    /**
     * The Amazon Resource Name (ARN) of the destination Amazon CloudWatch Logs log group.
     *
     * @see http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-fis-experimenttemplate-cloudwatchlogsconfiguration.html#cfn-fis-experimenttemplate-cloudwatchlogsconfiguration-loggrouparn
     */
    readonly logGroupArn: string;
}
```

**Comment by nmussy** [comment]
Not sure how the L1 generated constructs handle this, but I'm going to assume that this is happening because the `cloudWatchLogsConfiguration` property is not properly typed, [see docs](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_fis.CfnExperimentTemplate.ExperimentTemplateLogConfigurationProperty.html#properties). Because it's just `any` object, I think that the CDK will not translate the property key because it does not expect it to be a CloudFormation object.

I'm not great in C# @hakenmt, but what you can do in the meantime is just not type the `cloudWatchLogsConfiguration` value, something like this:

```csharp
LogConfiguration = new ExperimentTemplateLogConfigurationProperty() {
    CloudWatchLogsConfiguration = new {
        LogGroupArn = this.LogGroup.LogGroupArn
    }
}
```

**Comment by hakenmt** [comment]
Thanks for the workaround, I actually ended up doing this:

```csharp
this.PacketLossExperiment.AddOverride("Properties.LogConfiguration.CloudWatchLogsConfiguration.LogGroupArn", this.LogGroup.LogGroupArn);
this.PacketLossExperiment.AddOverride("Properties.LogConfiguration.CloudWatchLogsConfiguration.logGroupArn", null);
```

I think both work, but obviously ideally would like to use the concrete generated type for the property if possible. The entire ExperimentTemplate construct is fairly hard to navigate, the Action and Target properties are both just `object?` objects (like `any`), instead of being something like `Dictionary<string, ExperimentTemplateTargetProperty>`.

**Comment by nmussy** [comment]
Yeah, your solution at least keeps some type safety 👍

As far as the issues with the generated L1, I don't have a ton of insight into that process. There was an issue raised about creating an L2 construct for `ExperimentTemplate` (#13744), but it never got a PR

**Comment by khushail** [comment]
Hi @hakenmt , thanks for reaching out with this bug info. 
Thanks @nmussy for sharing the repro code in Typescript. I also see the casing issue in generated synth output template.
Marking this issue as appropriate. Also Please feel free to submit a PR for L2 construct if you are willing.

**Comment by nmussy** [comment]
@pahud From what I gather, https://github.com/cdklabs/awscdk-service-spec needs to get a patch PR to override the currently generated L1?

**Comment by pahud** [comment]
@nmussy No, from my take, it's because it’s originally set to Json in cfnspec but at some point was added to an actual type by service team. To avoid breaking changes in CDK, we added a patch from awscdk-service-spec to make it always JSON type even it’s now typed in CFN. We have some other similar cases mentioned in https://github.com/aws/aws-cdk/issues/21767
