### ISSUE TITLE
Add string validation for CloudFormation DashboardName

### ISSUE THREAD

**Issue by cybergoof** [aws/aws-cdk#2976]
* **I'm submitting a ...**
- [ x ] :rocket: feature request

* **What is the current behavior?**
The "dashboardName" paramater for cloudwatch.Dashboard accepts a String, but on server side, CloudFormation will throw an error if the cloudwatch name has spaces

```
The value Doc Website Monitor for field DashboardName contains invalid characters. It can only contain alphanumerics, dash (-) and underscore (_). (Service: AmazonCloudWatch; Status Code: 400; Error Code: InvalidParameterValue; 
```
To reproduce:
```
  new cloudwatch.Dashboard(this, "FailedDashboard", { dashboardName: "Failed Dasboard"});
```

* **What is the expected behavior (or behaviour of feature suggested)?**
Add parameter validation in CDK

* **What is the motivation / use case for changing the behaviour or adding this feature?**
Identifies string errors at build time, rather than at CDK deploy

* **Please tell us about your environment:**
  
  - CDK CLI Version: 0.34.0
  - Module Version: 0.34.0
  - OS:  Ubuntu 
  - Language: TypeScript

**Comment by made2591** [comment]
I can fix this

**Comment by NGL321** [comment]
@cybergoof Thank you for bringing this to our attention!

Unfortunately, we are working hard to stabilize the CDK APIs and tuning them to meet our consistency guidelines. While we work on getting the APIs aligned with our guidelines, we are pausing work on most community PRs and feature-requests starting today. 
We expect to get back to work on community PRs within a few weeks.

That being said, @made2591 you are a rockstar! That would absolutely expedite the process. Feel free to self-assign this issue. We will get to any PRs submitted as soon as we can.

**Comment by made2591** [comment]
thank @NGL321 ! then hope you will have fun in the next weeks 😃 you cannot imagine how much I would like to be there and partecipate to discussions with you guys 🤩
