### ISSUE TITLE
aws_iam: Cannot use a service or account principal with grantAssumeRole, use assumeRolePolicy instead.

### ISSUE THREAD

**Issue by vmx-kbabenko** [aws/aws-cdk#29782]
### Describe the bug

Since version 2.136 trying to grant assume role to a principal results in an error.

**Code example:**
```python
        role.grant_assume_role(
            aws_iam.ServicePrincipal('batchoperations.s3.amazonaws.com')
        )
```
**Error:**
@jsii/kernel.RuntimeError: Error: Cannot use a service or account principal with grantAssumeRole, use assumeRolePolicy instead.

### Expected Behavior

No error expected

### Current Behavior

@jsii/kernel.RuntimeError is observed

### Reproduction Steps

Grant assume role to an AWS principal.

### Possible Solution

Breaking change happened in 2.136 release:

iam: grantAssumeRole silently fails with service and account principals (https://github.com/aws/aws-cdk/issues/29452) ([36fd79d](https://github.com/aws/aws-cdk/commit/36fd79d8714bd29527bb1184ec10cd504b83510d)), closes https://github.com/aws/aws-cdk/issues/24507

### CDK CLI Version

2.136.1

### Node.js Version

18

### OS

AL2

### Language

Python

### Language Version

3.9

**Comment by msambol** [comment]
Related: https://github.com/aws/aws-cdk/pull/29452. Can you try the following:

```ts
role.assumeRolePolicy?.addStatements(new iam.PolicyStatement({
  actions: ['sts:AssumeRole'],
  principals: [
    new iam.ServicePrincipal('batchoperations.s3.amazonaws.com'),
    ],
}));

**Comment by badfun** [comment]
I had the identical error. The solution provided by @msambol works. Now to go and refactor all the code. 
Funny how the "solution" in #29452 is a documentation change. Helps for the future I suppose. Not sure why my stuff has been working all along until this update.
