### ISSUE TITLE
aws-cdk-lib/core: RangeError: Map maximum size exceeded

### ISSUE THREAD

**Issue by gockle** [aws/aws-cdk#29785]
### Describe the bug

When I am trying to do `npx cdk synth` in the project [Serverless-Image-Handler](https://github.com/aws-solutions/serverless-image-handler/tree/main), I am getting an error.

### Expected Behavior

The command npx cdk synth should output a CloudFormation Template.

### Current Behavior

Getting an error 

```
RangeError: Map maximum size exceeded
    at Map.set (<anonymous>)
    at TokenMap.registerStringKey ([PATH_TO_REPO]/Serverless-image-handler/source/constructs/node_modules/aws-cdk-lib/core/lib/private/token-map.js:1:2399)
    at [PATH_TO_REPO]/Serverless-image-handler/source/constructs/node_modules/aws-cdk-lib/core/lib/private/token-map.js:1:754
    at cachedValue ([PATH_TO_REPO]/Serverless-image-handler/source/constructs/node_modules/aws-cdk-lib/core/lib/private/token-map.js:1:2725)
    at TokenMap.registerString ([PATH_TO_REPO]/Serverless-image-handler/source/constructs/node_modules/aws-cdk-lib/core/lib/private/token-map.js:1:702)
    at Function.asString ([PATH_TO_REPO]/Serverless-image-handler/source/constructs/node_modules/aws-cdk-lib/core/lib/token.js:1:1541)
    at PolicyStatement.toString ([PATH_TO_REPO]/Serverless-image-handler/source/constructs/node_modules/aws-cdk-lib/aws-iam/lib/policy-statement.js:2:6884)
    at realTypeOf ([PATH_TO_REPO]/Serverless-image-handler/source/constructs/node_modules/@aws-solutions-constructs/core/node_modules/deep-diff/index.js:117:81)
    at deepDiff ([PATH_TO_REPO]/Serverless-image-handler/source/constructs/node_modules/@aws-solutions-constructs/core/node_modules/deep-diff/index.js:213:36)
    at deepDiff ([PATH_TO_REPO]/Serverless-image-handler/source/constructs/node_modules/@aws-solutions-constructs/core/node_modules/deep-diff/index.js:246:13)
```

### Reproduction Steps

```
git clone git@github.com:aws-solutions/serverless-image-handler.git
cd serverless-image-handler/source && npm i
cd image-handler && npm i
cd ../custom-resource/ && npm i
cd ../constructs/ && npm i
NODE_OPTIONS=--max-old-space-size=8192
npx cdk synth
```

### Possible Solution

The issue does not show up if the environment variable overrideWarningsEnabled is set to false

Command: `overrideWarningsEnabled=false npx cdk synth `

### CDK CLI Version

2.102.0

### Node.js Version

v18.18.1

### OS

MacOS 14.4.1 (23E224)

### Language

TypeScript

### Language Version

5.2.2

### Other information

Similar bug here https://github.com/aws/aws-cdk/issues/21062

**Comment by khushail** [comment]
Hi @gockle , the project (aws-solutions/serverles-image-handler))you linked is not CDK related or not handled by CDK Team. The issue linked https://github.com/aws/aws-cdk/issues/21062 is also not owned by CDK Team as you can read in the comments.

It would be helpful if you could  share more insights into why this relates to CDK.

**Comment by gockle** [comment]
Hi Khushail

 the stack trace indicates the source code of issue is in the function `registerStringKey` in the file  `TokenMap` for`PolicyStatement.toString` (in aws-solutions-constructs) [here](https://github.com/aws/aws-cdk/blob/a7b4e2953c09ef59d25ec409b879d12a894318ab/packages/aws-cdk-lib/core/lib/private/token-map.ts#L174)

**Comment by scanlonp** [comment]
Hey @gockle, looking at the comments on the bug you linked, it appears the underlying problem was with the `aws-solution-constructs`. Any reason you believe this issue is different; that it is related to the CDK library code rather than the construct?

**Comment by gockle** [comment]
Hi @scanlonp aws-solutions-construct uses the node-module deep-diff [here](https://github.com/awslabs/aws-solutions-constructs/blob/dca402cf991c4a70bd7d09e9ec9f4fe3ef081078/source/patterns/%40aws-solutions-constructs/core/lib/override-warning-service.ts#L68) to provide override information, the issue is when the module deep-diff is calling to string on iam policy resource. The exact function call from deep-diff is [here](https://github.com/bluelovers/deep-diff/blob/9b0b82f846c3ea9ed2a9d24c0475e7940a9e0260/src/index.ts#L141). When deep-diff calls toString, the aws-cdk code fails in [token-maps.ts](https://github.com/aws/aws-cdk/blob/a7b4e2953c09ef59d25ec409b879d12a894318ab/packages/aws-cdk-lib/core/lib/private/token-map.ts#L174),

I am not sure why the bug #21062 stopped and assumed its an issue with the aws-solutions-construct. on first review the comment below, is same as what we are facing.

```
I can deploy the same stack to a different account fine. The stack we have could not potentially be creating 2^24 entities/things in PolicyStatement, otherwise it would have failed to deploy to the other account.
Something is happening in PolicyStatement.toString which probably making it go into an infinite loop.
```

**Comment by gockle** [comment]
The token-map documentation clearly states that TokenStringMap storage is shared so this doesn't look like a cdk issue. 

```
/**
 * Central place where we keep a mapping from Tokens to their String representation
 *
 * The string representation is used to embed token into strings,
 * and stored to be able to reverse that mapping.
 *
 * All instances of TokenStringMap share the same storage, so that this process
 * works even when different copies of the library are loaded.
 */
```

Closing this issue.

**Comment by scanlonp** [comment]
@gockle, got it, thank you! If you do find what is causing this, feel free commenting here (even through the visibility warning); I would be interested in case we see this in the future!
