### ISSUE TITLE
dms: CfnReplicationTask does not apply task_data

### ISSUE THREAD

**Issue by hunt3ri** [aws/aws-cdk#29799]
### Describe the bug

I set the task_data to a valid JSON string.  The TaskData value can be seen in the CloudFormation template but it is not applied to the DMS replication task and only default values are seen. 

### Expected Behavior

JSON string that is supplied in task_data is applied to the DMS replication task

### Current Behavior

Default values for taskdata is generated despite attempt to override

### Reproduction Steps

Create a new CfnReplicationTask update the task_data value observe that overidden JSON is ignored.

### Possible Solution

 It's possible this is actually a bug in the AWS API as the JSON is observed in the CloudFormation template?

### CDK CLI Version

2.137.0

### Framework Version

2

### Node.js Version

20.10

### OS

MacOS

### Language

Python

### Language Version

3.12

**Comment by pahud** [comment]
In terms of `Reproduction Steps`, can you provide minimal code snippets that we can run in our account and reproduce this issue?
