### ISSUE TITLE
Secrets Manager: Security issue when adding rotationLambda with CT Hooks

### ISSUE THREAD

**Issue by JMJHOX** [aws/aws-cdk#29791]
### Describe the bug

This bug has been previously raised by #28406 and closed for inactivity.

But in my case, it is reflected when you enable an CT Guardrail that checks the rule [CT.LAMBDA.PR.2] is complying proactively.
That is, deploying a CFN Hook into your account that checks if your lambdas deployed have the property called "SourceAccount" in the service principal, for this case It fails when I try to deploy a lambda rotation with CDK.

### Expected Behavior

I should be allowed to add or override the service principal created, like was discussed in the old thread.

### Current Behavior

It creates the resource without the required fields, causing it to fail when the hook checks on the creation process.

### Reproduction Steps

add a rotation lambda to secrets manager, enable ct guardrail for rule [CT.LAMBDA.PR.2] and you are good to go

### Possible Solution

Continue the previous PR.
I´d like to check the old PR and go on with it, I´m interested in this issue is fixed.

### Additional Information/Context

Not much

### CDK CLI Version

v2.136.0

### Node.js Version

v16.20.0

### OS

windows

### Language

TypeScript

**Comment by pahud** [comment]
Hi

Can you provide minimal code snippets in the `Reproduction Steps
` that reproduces this issue?
