### ISSUE TITLE
aws_lambda: Version.fromVersionArn creates invalid Version object

### ISSUE THREAD

**Issue by rehos** [aws/aws-cdk#29813]
### Describe the bug

The version object created by Version.fromVersionArn is created with a lambda property that still contains the version qualifier in its function url. Which can cause CloudFormation deployment errors. For example when you create a lambda alias from it and then try to use that alias fro a lambda function url.

### Expected Behavior

I expect Version.fromVersionArn to create the equivalent object as Version.fromVersionAttributes when referencing the same version.

The following test when using Version.fromVersionAttributes succeeds:

```
import {
    Stack,
    aws_lambda as lambda,
} from 'aws-cdk-lib';

test('lambda.Version.fromVersionAttributes generates Version with correct lambda property', () => {
    const stack = new Stack();
    const version = lambda.Version.fromVersionAttributes(stack, 'ExampleVersion', {
        lambda: lambda.Function.fromFunctionArn(stack, 'Examplelambda', 'arn:aws:lambda:eu-central-1:123456789012:function:ExampleLambda'),
        version: '13',
    });

    expect(version.version).toStrictEqual('13') // Ok
    expect(version.lambda.functionArn).toStrictEqual('arn:aws:lambda:eu-central-1:123456789012:function:ExampleLambda') // Ok
})

```

### Current Behavior

However the following test when using Version.fromVersionArn fails because the version qualifier is not stripped from the arn:

```
import {
    Stack,
    aws_lambda as lambda,
} from 'aws-cdk-lib';

test('lambda.Version.fromVersionArn generates Version with correct lambda property', () => {
    const stack = new Stack();
    const version = lambda.Version.fromVersionArn(stack, 'ExampleVersion', 'arn:aws:lambda:eu-central-1:123456789012:function:ExampleLambda:13');

    expect(version.version).toStrictEqual('13') // Ok
    expect(version.lambda.functionArn).toStrictEqual('arn:aws:lambda:eu-central-1:123456789012:function:ExampleLambda') // Not Ok
})
```

### Reproduction Steps

Run the above tests

### CDK CLI Version

2.137.0

### Node.js Version

v20.11.0

### OS

macOS Sonoma 14.4.1

### Language

TypeScript

### Language Version

Typescript (5.4.5)

**Comment by pahud** [comment]
Yes, it should be a tiny fix here

https://github.com/aws/aws-cdk/blob/f14b60fc990cb98d1d2b0e48f9a89492bddf868c/packages/aws-cdk-lib/aws-lambda/lib/lambda-version.ts#L125

**Comment by aaythapa** [comment]
Re opening this issue since the PR that fixed this was reverted
