### ISSUE TITLE
aws_appintegrations: Can not create 

### ISSUE THREAD

**Issue by cjhelloletsgo** [aws/aws-cdk#29817]
### Describe the bug

App integrations does not allow creating an event integration with source aws.cases

``` python
cfn_event_integration = appintegrations.CfnEventIntegration(
      self,
      "Connect Case Streams Event Integration",
      event_bridge_bus="default",
      event_filter=appintegrations.CfnEventIntegration.EventFilterProperty(
          source="aws.cases"
      ),
      name="amazon-connect-cases",
      description="Amazon Connect app integration for enabling case event streams",
  )
```
### Expected Behavior

Create an event integration

### Current Behavior

Event integration fails to create

### Reproduction Steps

deploy with code snippet and you will get this error:

12:38:20 PM | CREATE_FAILED        | AWS::AppIntegrations::EventIntegration | ConnectCaseStreamsEventIntegration
Properties validation failed for resource ConnectCaseStreamsEventIntegration with message:
[#/EventFilter/Source: string [aws.cases] does not match pattern ^aws\.partner\/.*$]

 ❌  CustomerProfilePortalStack failed: Error: The stack named CustomerProfilePortalStack failed to deploy: UPDATE_ROLLBACK_COMPLETE: Properties validation failed for resource ConnectCaseStreamsEventIntegration with message:
[#/EventFilter/Source: string [aws.cases] does not match pattern ^aws\.partner\/.*$]
    at FullCloudFormationDeployment.monitorDeployment (/home/colton/.nvm/versions/node/v20.12.2/lib/node_modules/aws-cdk/lib/index.js:433:10615)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.deployStack2 [as deployStack] (/home/colton/.nvm/versions/node/v20.12.2/lib/node_modules/aws-cdk/lib/index.js:436:200503)
    at async /home/colton/.nvm/versions/node/v20.12.2/lib/node_modules/aws-cdk/lib/index.js:436:181341

 ❌ Deployment failed: Error: The stack named CustomerProfilePortalStack failed to deploy: UPDATE_ROLLBACK_COMPLETE: Properties validation failed for resource ConnectCaseStreamsEventIntegration with message:
[#/EventFilter/Source: string [aws.cases] does not match pattern ^aws\.partner\/.*$]
    at FullCloudFormationDeployment.monitorDeployment (/home/colton/.nvm/versions/node/v20.12.2/lib/node_modules/aws-cdk/lib/index.js:433:10615)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.deployStack2 [as deployStack] (/home/colton/.nvm/versions/node/v20.12.2/lib/node_modules/aws-cdk/lib/index.js:436:200503)
    at async /home/colton/.nvm/versions/node/v20.12.2/lib/node_modules/aws-cdk/lib/index.js:436:181341

The stack named CustomerProfilePortalStack failed to deploy: UPDATE_ROLLBACK_COMPLETE: Properties validation failed for resource ConnectCaseStreamsEventIntegration with message:
[#/EventFilter/Source: string [aws.cases] does not match pattern ^aws\.partner\/.*$]

### Possible Solution

From the error message it looks like the regex needs to be adjusted to match available options, I know this is a valid configuration as I have successfully deployed this through a custom resource.

### CDK CLI Version

2.137.0 (build bb90b4c)

### Node.js Version

v18.13.0

### OS

Ubuntu 23.10

### Language

Python

### Language Version

Python 3.11

**Comment by pahud** [comment]
Based on the error messages and the [document](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-appintegrations-eventintegration-eventfilter.html#cfn-appintegrations-eventintegration-eventfilter-source), I believe the source "aws.cases" is not allowed. It should be like "aws.partner/xxxx" or anything in this pattern. Please not this is not relevant to CDK bug and the error is from cloudformation. I am resolving this issue as it's not related to a CDK bug.
