### ISSUE TITLE
SDKv3-08: Update `@aws-cdk/integ-tests-alpha`

### ISSUE THREAD

**Issue by TheRealAmazonKendra** [aws/aws-cdk#29839]
### Context
The AWS SDK V2 is being deprecated. We need to remove all uses of it from the CDK.

### Task Description
Ensure that the integ test (and integ runner) construct is only making calls to sdkv3.

### Acceptance Criteria
1. There are no uses of sdkv2 in this package.
2. All tests (unit and integ) pass after the change has been made (ensure that the resources behave as expected and not that they just deploy, some manual verification may be required).

**Comment by SankyRed** [comment]
Upon investigating the update from SDK v2 to v3 for the `@aws-cdk/integ-tests-alpha` module, I noticed there are no references to `sdk-v2` in the code. Additionally, all references to the `aws-sdk-v2-to-v3-adapter` have been updated in this [PR](https://github.com/aws/aws-cdk/pull/29847), and also all the references are pointing to v3 handler imports such as `@aws-sdk/client-s3`. I've tested the changes and everything appears to be functioning correctly.
