### ISSUE TITLE
bedrock: add L1 constructs

### ISSUE THREAD

**Issue by jlosito** [aws/aws-cdk#29858]
### Describe the feature

I'd like to be able to programmatically provision and configure resources within Bedrock such as agents, knowledge bases, etc. Right now the only way to do something like this is by using the [generative-ai-cdk-constructs](https://github.com/awslabs/generative-ai-cdk-constructs), but all of the constructs within that library are essentially custom resources. Maybe that library was made before CloudFormation support, but it seems to me like CloudFormation supports these resources now.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-bedrock-knowledgebase.html

### Use Case

I would like to provision and configure various Bedrock resources such as KnowledgeBase and Agents programmatically.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.137.0

### Environment details (OS name and version, etc.)

macOS 14.4.1

**Comment by khushail** [comment]
Thanks @jlosito for reaching out with this request. This needs to be supported by Cloudformation team first, after that it would be available for CDK Usage and implementation. You could create an issue in [Cloudformation coverage roadmap](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues) and help in prioritizing this by likes.

**Comment by pahud** [comment]
Hi @jlosito 

Thank you for bringing this up. [generative-ai-cdk-constructs](https://github.com/awslabs/generative-ai-cdk-constructs) is not maintained by CDK team. I will discuss the official L2 support with the team and update here.

Please note, I've seen some bedrock L1 resources supported in [CFN spec v169.0.0](https://d1uauaxba7bl26.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json) and it should be imported by [awscdk-service-spec](https://github.com/cdklabs/awscdk-service-spec) very soon and available in recent CDK releases. I will update here when it's available as L1.

**Comment by pahud** [comment]
The latest servicespec release(v0.0.63) was released 5 days ago, the JSON imported is at
https://github.com/cdklabs/awscdk-service-spec/tree/%40aws-cdk/service-spec-types%40v0.0.63/sources/CloudFormationSchema/us-east-1
CDK imports servicespec using [spec2cdk](https://github.com/aws/aws-cdk/tree/main/tools/%40aws-cdk/spec2cdk) and based on the [package.json](https://github.com/aws/aws-cdk/blob/bb90b4ccdbddbbce08a7d6f1b7d7e625263a70cf/tools/%40aws-cdk/spec2cdk/package.json#L35), current latest CDK release is [still using 0.0.61](https://github.com/aws/aws-cdk/blob/bb90b4ccdbddbbce08a7d6f1b7d7e625263a70cf/tools/%40aws-cdk/spec2cdk/package.json#L35) and the main branch[ is using 0.0.63](https://github.com/aws/aws-cdk/blob/72b6d8e4697c33796b8b2539b349f0874f07fca8/tools/%40aws-cdk/spec2cdk/package.json#L35) now. So I am confident the next release of CDK v2.138.0 should include the bedrock L1s. I hope this clarifies.

**Comment by ymhiroki** [comment]
@pahud 
CDK v2.138.0 is released, however, L1 Constructs for Amazon Bedrock is not available yet.
I think this is because generated CloudFormation Resources are not exported in aws-bedrock.

I made a pull request #29900 and fixed the issue. Would you like to check it?
In addition, AWS CodeBuild CI Report reports that the test is succeeded, but the workflow check is not completed. Do you have any ideas?

**Comment by pahud** [comment]
We have fixed that in https://github.com/aws/aws-cdk/pull/29911 and it should be available in the next release.

**Comment by TheRealAmazonKendra** [comment]
These have now been released
