### ISSUE TITLE
(aws-service-catalog): SIGKILL: 9 CustomCDKBucketDeployment Lambda runs out of memory

### ISSUE THREAD

**Issue by schnipseljagd** [aws/aws-cdk#29862]
### Describe the bug

> Received response status [FAILED] from custom resource. Message returned: Command '['/opt/awscli/aws', 's3', 'cp', 's3://cdk-accel-assets-XXXX-eu-central-1/d91fe0e02571a1639b83572917ebc528352265bd305ff570f75cae8419dae522.zip', '/tmp/tmpd41vn6fr/contents']' died with <Signals.SIGKILL: 9>. (RequestId: 90349d17-82a5-4ed1-b285-aad7469cb046)

### Expected Behavior

I should be able to configure the memory limit for the bucket deployment Lambda used by the `ProductStackSynthesizer`.

### Current Behavior

It is not configurable since it is hard-coded deep in the synthesizer: https://github.com/aws/aws-cdk/blob/8e2cbae3b479efe76d601c343be0ae536e3e1805/packages/aws-cdk-lib/aws-servicecatalog/lib/private/product-stack-synthesizer.ts#L85

### Reproduction Steps

You need to try to deploy a big enough CDK Stack using service catalog product stacks.

### CDK CLI Version

2.134.0 (build 265d769)

### Node.js Version

v18.20.0

### OS

Linux

### Language

TypeScript

**Comment by schnipseljagd** [comment]
Btw. Increasing the memory limit of the Lambda manually fixes the problem for the time being.

**Comment by nmussy** [comment]
I don't think increasing the memory allocated to the Lambda is the correct solution here. It's a waste of resources and would not scale with larger file sizes. The file downloaded from S3 should not be fully stored in memory until its download is completed, it should be progressively saved to disk and assembled.

I don't think this is possible with the AWS CLI, but it might be doable with boto3, see [Multipart transfers](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/s3.html#multipart-transfers). If not, it could be done with the SDK, see [Upload or download large files to and from Amazon S3 using an AWS SDK](https://docs.aws.amazon.com/AmazonS3/latest/userguide/example_s3_Scenario_UsingLargeFiles_section.html)

**Comment by pahud** [comment]
@nmussy Thank you and I agree with you.

But it makes sense to expose the memoryLimit as well. Feel free and welcome to submit a PR to expose the [memoryLimit](https://github.com/aws/aws-cdk/blob/5a918d12ec0455626b5630b35aa47e6d9da6df7c/packages/aws-cdk-lib/aws-s3-deployment/lib/bucket-deployment.ts#L140) for [this](https://github.com/aws/aws-cdk/blob/8e2cbae3b479efe76d601c343be0ae536e3e1805/packages/aws-cdk-lib/aws-servicecatalog/lib/private/product-stack-synthesizer.ts#L84-L93). 

Please help us prioritize with 👍 .

**Comment by nmussy** [comment]
I've opened another issue for my solution, so we can keep track of it after this one is fixed by the `memoryLimit` prop: #29898
