### ISSUE TITLE
aws-elb: Disabling cross zone load balancing is not respected in Java CDK

### ISSUE THREAD

**Issue by codypenta** [aws/aws-cdk#29866]
### Describe the bug

```typescript
        ApplicationLoadBalancer loadBalancer = ApplicationLoadBalancer.Builder.create(this, "ApplicationLoadBalancer")
                .vpc(vpc)
                .crossZoneEnabled(false) // BUG: This is not respected and cross zone is enabled
                .desyncMitigationMode(DesyncMitigationMode.DEFENSIVE)
                .internetFacing(true)
                .build();
```

### Expected Behavior

I expect cross zone to be disabled or a warning why it was enabled

### Current Behavior

Cross zone load balancer is not respected

### Reproduction Steps

See source

### CDK CLI Version

2.134.0

### Framework Version

2

### Node.js Version

v21.7.1

### OS

MacOS

### Language

Java

### Language Version

Java (17)

**Comment by codypenta** [comment]
Turn's out this is a feature request. While ALB does support cross zone load balancing, it's different than ELBs. You must enable it at the target group level with TargetAttributes. TargetAttributes are not available in the L2 construct for TargetGroups

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-targetgroup.html

**Comment by ashishdhingra** [comment]
We would submit a PR to improve the documentation [here](https://github.com/aws/aws-cdk/blob/5a918d12ec0455626b5630b35aa47e6d9da6df7c/packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/shared/base-load-balancer.ts#L51-L55).

**Comment by codypenta** [comment]
That makes sense to me, a quick documentation PR or logging a warning for this (You tried disabling `cross-zone` on an ALB see xyz) would resolve this issue in my mind with a longer term fix being allowed to directly set these values on the `ApplicationTargetGroup` type vs having to do an escape hatch

**Comment by codypenta** [comment]
Ahh yes that works, I was looking for a strongly typed option like they have in the ALB `tg.crossZoneEnabled = false` or something like that but the key/value map makes sense.
