### ISSUE TITLE
Python - SecurityGroup does bot have tags property

### ISSUE THREAD

**Issue by lkoniecz** [aws/aws-cdk#2987]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [ ] :beetle: bug report
  - [ ] :rocket: feature request
  - [x] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/awslabs/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*

https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_ec2/SecurityGroup.html
SecurityGroup construct does now have tags property

* **What is the expected behavior (or behavior of feature suggested)?**
It should be possible to create SecurityGroup via Construct and provide tags

* **What is the motivation / use case for changing the behavior or adding this feature?**
It's easier to browse thru security groups on GUI when they are named ('Name' tagged).

* **Please tell us about your environment:**
  
  - CDK CLI Version: 0.35.0
  - Module Version: 0.35.0
  - OS: [all]
  - Language: [Python ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group.html - it is possible to define tags

**Comment by NGL321** [comment]
@lkoniecz thank you for bringing this to our attention.

We are working hard to stabilize the CDK APIs and tuning them to meet our consistency guidelines. While we work on getting the APIs aligned with our guidelines, we are pausing work on most community PRs and feature-requests starting today. Please continue to report issues and submit feature requests, of course. We expect to get back to work on community PRs within a few weeks.

One of the team members will be sure to update this issue as soon as we are able to address it!

**Comment by rix0rrr** [comment]
Assuming this answers your question: https://docs.aws.amazon.com/cdk/latest/guide/tagging.html

Please reopen if not.

**Comment by HeskethGD** [comment]
Has this situation been resolved? I have tagged my cdk app in the main app.py so that tags are applied to all resources and everything apart from security groups gets tagged. The clients policy is that only appropriately tagged resources can be deleted so this causes problems for maintaining the stack particularly if a deployment fails and rollback cannot delete resources. I'm then required to tag the security groups in the console in order to delete them manually.
