### ISSUE TITLE
Toolkit: warn user if stack uses deprecated module versions

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#299]
Stack metadata includes module version information which is used to insert the AWS::CDK::Metadata resource (#221), we can also add a toolkit feature that will warn users if they are using deprecated versions (via [npm-deprecate])

[npm-deprecate]: https://docs.npmjs.com/cli/deprecate

**Comment by eladb** [comment]
@nija-at isn't this part of v2 work?

**Comment by nija-at** [comment]
Indeed.

**Comment by njlynch** [comment]
> isn't this part of v2 work?
> Indeed

I disagree, unless I misunderstand the original premise. The title (deprecated **module** versions) and usage of `npm-deprecate` makes this issue very much targeted at deprecated npm modules. The outstanding work for v2 with respect to deprecation warnings is really more so on warning if the user is using deprecated **APIs**, not entire modules.

Re-labelling as a p2, and disassociating from the v2 GA board. I'm going to open a separate issue to track the work to implement https://github.com/aws/aws-cdk-rfcs/blob/master/text/287-cli-deprecation-warnings.md.
