### ISSUE TITLE
cdk deploy: (unable to verify the first certificate)

### ISSUE THREAD

**Issue by holoyolo247** [aws/aws-cdk#29901]
### Describe the bug

I have been using cdk for a while, and today I just use it as usual, but when I run `cdk deploy` or  `cdk destroy` 
and even if I run `cdk boostrap`, it always return error related to **unable to verify the first certificate**

### Expected Behavior

Expected: cdk can automatically completes deploy and can destroy stack when running cdk destroy

### Current Behavior

when running  `cdk deploy` or  `cdk destroy` , it returns the following error
![eer](https://github.com/aws/aws-cdk/assets/157797678/e1486b64-e319-43d6-84d6-55ad5150c8e3)

when running  `cdk boostrap`, it returns the following error
![err5](https://github.com/aws/aws-cdk/assets/157797678/8d102ea2-f074-4fc9-9e25-32427463d85a)

### Reproduction Steps

Running   `cdk deploy` or  `cdk destroy`  will produce the error

### CDK CLI Version

2.136.1 (build 6f21c1d)

### Node.js Version

v20.6.1

### OS

window

### Language

Python

**Comment by ashishdhingra** [comment]
@holoyolo247 Could you please share the complete stack trace? There is a similar issue reported at https://repost.aws/questions/QUUsfG_RKYQ5iqIAtHLmNw4g/cdk-deploy-and-cdk-destory-suddenly-cause-deployment-failed-error-teststack-unable-to-verify-the-first-certificate, which indicates some problem with your Nodejs setup!
