### ISSUE TITLE
kms: support for key rotation period

### ISSUE THREAD

**Issue by badmintoncryer** [aws/aws-cdk#29927]
### Describe the feature

Configuring automatic key rotation period.

```ts
new kms.Key(this, 'MyKey', {
  enableKeyRotation: true,
  rotationPeriod: Duration.days(180), // Add
});
```

### Use Case

Cloudformation [supports for configuring period of automatic key rotation](https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-resource-kms-key.html#cfn-kms-key-rotationperiodindays) but CDK does not.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.127.0

### Environment details (OS name and version, etc.)

irrelevant

**Comment by khushail** [comment]
@badmintoncryer , there is already such feature request in the past for enabling key rotation. See this -https://github.com/aws/aws-cdk/issues/22125. As mentioned in [AWS Docs](https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-resource-kms-key.html#aws-resource-kms-key-properties) and suggested [here](https://github.com/aws/aws-cdk/issues/22125#issuecomment-1373597881) in comments as well

`AWS KMS charges a monthly fee for first and second rotation of key material maintained for your KMS key`

**Comment by badmintoncryer** [comment]
Thank you, @khushail, for the information. Issue #21455 discusses enabling key rotation feature that has already been implemented. 

However, this issue pertains to configuring the rotation period, so I believe there is a distinction between the two.

**Comment by khushail** [comment]
Yes that's true , you are talking about rotation period. I might be unsure but what I think the reason behind not keeping the rotation period was the same as well. By default this is `false` which means if user wants, and is aware of the billing, they can set it to `true` using the template or directly. 

@hunhsieh, wdyt?

**Comment by badmintoncryer** [comment]
@khushail 
I also agree that key rotation should be disabled by default, and I understand that enabling it could incur charges.

This feature request is intended for users who do not mind the additional costs and want to perform key rotations. Currently, the only setting available is the default 365 days. 

Therefore, even if key rotation is disabled by default, I believe there is still merit in implementing this feature. What do you think?

**Comment by khushail** [comment]
> @khushail I also agree that key rotation should be disabled by default, and I understand that enabling it could incur charges.
> 
> This feature request is intended for users who do not mind the additional costs and want to perform key rotations. Currently, the only setting available is the default 365 days.
> 
> Therefore, even if key rotation is disabled by default, I believe there is still merit in implementing this feature.
> 
> Additionally, my understanding is that the discussion in issue #22125 revolves around the keys that are automatically generated at bootstrap. Indeed, it would be hard to accept if this setting incurs additional charges.
> 
> This time, we are considering an option for keys freely created by users. Wouldn't this be a different situation from the previous issue?
> 
> What are your thoughts about this?

Hmmm, I understand your point of view in enabling this feature.  Marking this as appropriate.
