### ISSUE TITLE
aws-s3: eventBridgeEnabled creates redundant resources

### ISSUE THREAD

**Issue by blaxx** [aws/aws-cdk#29932]
### Describe the bug

When creating a new Bucket with `eventBridgeEnabled = true`, redundant resources are created as well.

### Expected Behavior

The snippet
`const bucket = new s3.Bucket(this, 'MyEventBridgeBucket', { eventBridgeEnabled: true, }); `
creates a new `AWS::S3::Bucket` resource with `eventBridgeEnabled = true` only.

### Current Behavior

The snippet
`const bucket = new s3.Bucket(this, 'MyEventBridgeBucket', { eventBridgeEnabled: true, }); `
creates not only a `AWS::S3::Bucket`, but also the following resources:
- `Custom::S3BucketNotifications`
- `AWS::IAM::Role`
- `AWS::IAM::Policy`
- `AWS::Lambda::Function` 

### Reproduction Steps

`const bucket = new s3.Bucket(this, 'MyEventBridgeBucket', { eventBridgeEnabled: true, }); `

### Additional Information/Context

Was also reported in https://github.com/aws/aws-cdk/issues/26772 but closed without fix.

### CDK CLI Version

2.137.0 (build bb90b4c)

### Node.js Version

v20.12.1

### OS

Mac OS 12.7.4 (21H1123)

### Language

TypeScript

### Language Version

TypeScript (5.4.5)

**Comment by pahud** [comment]
Just reopened https://github.com/aws/aws-cdk/issues/26772
Closing in favor of https://github.com/aws/aws-cdk/issues/26772
