### ISSUE TITLE
ec2: change default  Volume.volumeType and/or change generic EbsDeviceVolumeType

### ISSUE THREAD

**Issue by azatoth** [aws/aws-cdk#29931]
### Describe the feature

Change `Volume.volumeType` default to be `EbsDeviceVolumeType.GENERAL_PURPOSE_SSD_GP3`, and rename `EbsDeviceVolumeType.GENERAL_PURPOSE_SSD` to `EbsDeviceVolumeType.GENERAL_PURPOSE_SSD_GP2`

### Use Case

People incur extra cost because they might not know that they should change the volume type from the default GP2 which is discouraged to use.

### Other Information

Currently `Volume.volumeType` defaults to `EbsDeviceVolumeType.GENERAL_PURPOSE_SSD` which refers to GP2; I think it might be time to switch the default to GP3; The naming of `EbsDeviceVolumeType.GENERAL_PURPOSE_SSD` for GP2 is unfortunate and should probably be deprecated for a `EbsDeviceVolumeType.GENERAL_PURPOSE_SSD_GP2` instead.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### CDK version used

v2.138

### Environment details (OS name and version, etc.)

Ubuntu 22.04.4

**Comment by pahud** [comment]
Love this idea but I guess we can't switch the [EbsDeviceVolumeType](https://github.com/aws/aws-cdk/blob/31492c621c835e3fa08de2bbac24a0adc6fc2d69/packages/aws-cdk-lib/aws-ec2/lib/volume.ts#L174) enum using feature flag if we plan to make `EbsDeviceVolumeType.GENERAL_PURPOSE_SSD` point to `EbsDeviceVolumeType.GENERAL_PURPOSE_SSD_GP3`.  But we can change the default volume type for EBS [here](https://github.com/aws/aws-cdk/blob/31492c621c835e3fa08de2bbac24a0adc6fc2d69/packages/aws-cdk-lib/aws-ec2/lib/volume.ts#L624) if volumeType is undefined.

i.e.

```ts
volumeType: props.volumeType ?? EbsDeviceVolumeType.GENERAL_PURPOSE_SSD_GP3,
```

Looking at the EBS console, the default volume type for a new ebs is now gp3 so I think it makes sense here.

<img width="918" alt="image" src="https://github.com/aws/aws-cdk/assets/278432/137a113a-5d57-436f-aca0-017acfda7776">
