### ISSUE TITLE
(aws-events): ApiDestination missing fromArn methods for existing API destinations

### ISSUE THREAD

**Issue by keenangraham** [aws/aws-cdk#29942]
### Describe the bug

`ApiDestination` doesn't have any way to reference an existing EventBridge API destination:

https://github.com/aws/aws-cdk/blob/f00f918af45abf26072df396bba1d591fcb6210d/packages/aws-cdk-lib/aws-events/lib/api-destination.ts#L70-L107

This is problematic because the `aws-events-targets.ApiDestination` expects an `aws-events.ApiDestination`:
https://github.com/aws/aws-cdk/blob/f00f918af45abf26072df396bba1d591fcb6210d/packages/aws-cdk-lib/aws-events-targets/lib/api-destination.ts#L63

I would like to have multiple `Rules` targeting the same (existing) `ApiDestination`. In my case the API destination is a Slack webhook with a secret in the URL endpoint.

### Expected Behavior

To be able to reference an existing API destination by an ARN, like in `Connection`:

https://github.com/aws/aws-cdk/blob/f00f918af45abf26072df396bba1d591fcb6210d/packages/aws-cdk-lib/aws-events/lib/connection.ts#L303

Or `Eventbus`:
https://github.com/aws/aws-cdk/blob/f00f918af45abf26072df396bba1d591fcb6210d/packages/aws-cdk-lib/aws-events/lib/event-bus.ts#L171

### Current Behavior

No method to reference existing EventBridge API destination by ARN.

### Reproduction Steps

Try to import existing API destination.

### Possible Solution

Add `ImportedApiConnection` and method.

### CDK CLI Version

2.138.0

### Node.js Version

20

### OS

Sonoma

### Language

Python

**Comment by khushail** [comment]
thanks @keenangraham for reporting this.
