### ISSUE TITLE
AutoAssignIP is always set to true, even for ECS EC2 task

### ISSUE THREAD

**Issue by Kent1** [aws/aws-cdk#2996]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/awslabs/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
I want to create a _Compatibility.Ec2AndFargate_ _TaskDefinition_. using the network mode AWSVPC. However, AutoAssignIP property is set automatically if we use public Subnet.
See run-ecs-task-base.ts. While it is not a problem with Fargate, ECS EC2 does not allow to have AutoAssignIP to true.

* **What is the expected behavior (or behavior of feature suggested)?**
AutoAssignIP should be disabled in run-ecs-ec2-task.ts

* **What is the motivation / use case for changing the behavior or adding this feature?**
Make Fargate task definition work with ECS EC2

* **Please tell us about your environment:**
  
  - CDK CLI Version: 0.35.0 (build c5e43e2)
  - Module Version: 0.35.0
  - OS: OSX Mojave
  - Language: Java

* **Code:**
```
Cluster ecsCluster = new Cluster(this, "PtaEcsCluster", ClusterProps.builder()
        .withClusterName("Pta")
        .withVpc(vpc)
        .build());

ecsCluster.addCapacity("PtaEcsInstance", AddCapacityOptions.builder()
        .withInstanceType(new InstanceType("t3.small"))
        .withVpcSubnets(SubnetSelection.builder().withSubnetType(SubnetType.Public).build())
        .build());

TaskDefinition taskDefinition = new TaskDefinition(this, "PtaEcsTaskDefinition", 
TaskDefinitionProps.builder()
        .withCompatibility(Compatibility.Ec2AndFargate)
        .withNetworkMode(NetworkMode.AwsVpc)
        .withMemoryMiB("1024")
        .build());

taskDefinition.addContainer("PtaContainer", ContainerDefinitionOptions.builder()
        .withImage(ecrImage)
        .withCpu(512)
        .withMemoryReservationMiB(512)
        .withEssential(true)
        .build());

Rule rule = new Rule(this, "PtaEventRule", RuleProps.builder()
        .withEnabled(false)
        .withSchedule(Schedule.rate(15, TimeUnit.Minute))
        .build());

rule.addTarget(new EcsTask(EcsTaskProps.builder()
        .withSubnetSelection(SubnetSelection.builder().withSubnetType(SubnetType.Public).build())
        .withCluster(ecsCluster)
        .withTaskDefinition(taskDefinition)
        .withTaskCount(1)
        .build()));
```

**Comment by rix0rrr** [comment]
Could you supply me with a reference, or an error message you're receiving, on the fact you're stating here:

> ECS EC2 does not allow to have AutoAssignIP to true

I can't seem to find this limitation in the ECS documentation, and it also runs counter to what I know about AWS networking. Not saying there isn't a bug, but I'm going to need more information on the exact issue before we can fix it. 

It might also be that your problem has been fixed already since the ECS tasks have been completely reworked recently.

**Comment by rix0rrr** [comment]
Closing this because of lack of response. Feel free to reopen if you can add more context here.
