### ISSUE TITLE
aws-stepfunction-tasks: verifiiedPermissions createPolicy error on parsing Property Static in Definition.

### ISSUE THREAD

**Issue by Xenoha** [aws/aws-cdk#29968]
### Describe the bug

When creating a task to use the service verifiedPermissions of action createPolicy, I am getting a field not supported error for the property 'static'.  I have tried using pascal and lower camelcase with the same error. 

Type:AWS::StepFunctions::StateMachine, StatusReason:Resource handler returned message: \"Invalid State Machine Definition: 'SCHEMA_VALIDATION_FAILED: The field \"static\" is not supported by Step Functions at /States/resource/Parameters' (Service: AWSStepFunctions; Status Code: 400)\""

### Expected Behavior

I would expect the CallAwsService tasks to be duplicate of the aws sdk v3 for inputs. I would expect this task to create a static policy.

### Current Behavior

Type:AWS::StepFunctions::StateMachine, StatusReason:Resource handler returned message: \"Invalid State Machine Definition: 'SCHEMA_VALIDATION_FAILED: The field \"static\" is not supported by Step Functions at /States/create-tenant-admin-policy/Parameters' (Service: AWSStepFunctions; Status Code: 400)\""

The above error occurs at the time of deployment, not during synth.

### Reproduction Steps

Create a state Machine and use the CallAwsService Construct to create a Policy in verified Permissions. You will get the error at the time of deployment, not during synthesis.

### Possible Solution

Update the construct to follow the sdk v3 syntax for all properties.

### CDK CLI Version

2.139

### Framework Version

2.139

### Node.js Version

20.12.0

### OS

Linux 

### Language

TypeScript

### Language Version

Typescript 5.4.4

**Comment by pahud** [comment]
Can you share your code snippets so we can reproduce and verify this issue?

**Comment by Xenoha** [comment]
Hello @pahud 

Sorry for the delay.

I moved on from this, but here is a sample using the resouce.

`		const test = new CallAwsService(this, 'test-policy-create', {
			service: 'verifiedpermissions',
			action: 'createPolicy',
			iamResources: ['*'],
			parameters: {
				PolicyStoreId: 'foo',
				Definition: {
					Static: {
						Description: 'A test policy',
						Statement: `
						// policy def
						`,
					},
				},
			},
		})`

**Comment by Xenoha** [comment]
Hello, What is the status of this bug?

**Comment by pahud** [comment]
[CallAwsService](https://github.com/aws/aws-cdk/tree/f9fd00cd3401e5264518b3409b1130eea976e2db/packages/aws-cdk-lib/aws-stepfunctions-tasks#aws-sdk) essentially uses the SDK integration to call AWS services through state machine. Generally, I would suggest:

1. make sure you can call that API via AWS CLI like `aws verifiedpermissions create-policy`
2. or just try to use AWS JS SDK to attempt to call that API and see if it works.

If the SDK call works, it should be good to configure `CallAwsService` to allow step function to call that for you.



1. Can you make sure if you can successfully call that using SDK? If yes, can you share your full SDK code with all parameters?
2. After that, can you share your full CDK code for `CallAwsService` with all the `parameters` you specified?
3. And please share the full CDK or CloudFormation error messages.

Thank you.


 


```ts
const test = new CallAwsService(this, 'test-policy-create', { 
   service: 'verifiedpermissions', 
   action: 'createPolicy', 
   iamResources: ['*'], 
   parameters: { 
      PolicyStoreId: 'foo', 
      Definition: { 
         Static: { 
         Description: 'A test policy', 
         Statement: 
         // policy def
    , }, 
}, }, })
```

**Comment by Xenoha** [comment]
So, it seems like this has already been labeled a bug. I assumed this team has already been able to review and replicate the problem. The SDK call works just fine. I am forced to use a lambda as this integration has an issue with the "Static" property.

**Comment by pahud** [comment]
This issue is in the bug category but we need more info before we could reproduce and address this issue and reprioritize it correctly. Are you able to provide the information as requested in my previous comment?
