### ISSUE TITLE
aws_ecs.FargateTaskDefinition: pidmode Task unsupported

### ISSUE THREAD

**Issue by vduits** [aws/aws-cdk#29995]
### Describe the bug

Reading the pidmode announcement [here](https://aws.amazon.com/about-aws/whats-new/2023/08/aws-fargate-pid-namespace-sharing-kernel-configuration/), the cloudformation description for [pidMode here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-taskdefinition.html#cfn-ecs-taskdefinition-pidmode). It explains `task` is the only option. But currently the [FargateTaskDefinition](https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-ecs/lib/fargate/fargate-task-definition.ts#L174) only allows `host`.

Changing this to host will result in a failed deployment, because host isn't allowed on Fargate (linux) tasks.

### Expected Behavior

Consistency between documentation and usable options reflected by synth/deployments in CDK.
Task is the one that is the only one actually supported.

### Current Behavior

> Error: 'pidMode' can only be set to 'host' for Fargate containers, got: 'task'.
    at new FargateTaskDefinition (C:\projects\push-gateway-cdk\node_modules\aws-cdk-lib\aws-ecs\lib\fargate\fargate-task-definition.js:1:2562)

But using the host variant will results in:
> Deployment failed: Error: The stack named XXXX failed to deploy: UPDATE_ROLLBACK_COMPLETE: Resource handler returned message: "Invalid request provided: Create TaskDefinition: Tasks using the Fargate launch type do not support pidMode 'host'. The supported value for pidMode is 'task'.

### Reproduction Steps

```typescript
const ftdTask = new ecs.FargateTaskDefinition(stack, `task-that-will-fail-to-synth`, {
    cpu: 1024,
    memoryLimitMiB: 2048,
    pidMode: PidMode.TASK,
});
```
  
```typescript
const ftdHost = new ecs.FargateTaskDefinition(stack, `task-that-will-fail-to-deploy`, {
    cpu: 1024,
    memoryLimitMiB: 2048,
    pidMode: PidMode.HOST,
});
```

### Possible Solution

Switch [the checks](https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-ecs/lib/fargate/fargate-task-definition.ts#L174) from pidMode.HOST to pidMode.TASK.

### CDK CLI Version

2.139.0

### Node.js Version

v20.12.0

### OS

windows

### Language

TypeScript

### Other information

(OS is windows for where I ran CDK, the containers are linux as those are the only one allowing pidMode anyway)

**Comment by pahud** [comment]
yap, looks like we should remove that check.

Are you able to get it deployed using this workaround?

```
    const task = new ecs.FargateTaskDefinition(this, `task-that-will-fail-to-deploy`, {
      cpu: 1024,
      memoryLimitMiB: 2048,
      pidMode: ecs.PidMode.HOST,
    });
    (task.node.defaultChild as ecs.CfnTaskDefinition).addPropertyOverride('PidMode', 'task');
```

We just need to make sure removing that check would not cause other issues.

If it works great with you, feel free to submit a tiny PR for this. Thank you.
