### ISSUE TITLE
❗ NOTICE (lambda): importing `Functions` with `fromFunctionArn` removes trailing version or alias from ARN

### ISSUE THREAD

**Issue by colifran** [aws/aws-cdk#30008]
Please add your +1 👍 to let us know you have encountered this

---

### Status

In-Progress

### What is the issue?

This [PR](https://github.com/aws/aws-cdk/pull/29820) introduced a change to the static `fromFunctionArn` method that removes any trailing version or alias from the specified function ARN. As a result, the `functionArn` property for `Functions` imported with `fromFunctionArn` will no longer include their version or alias.

### What is the impact?

`Functions` imported using the static `fromFunctionArn` method will have their version or alias removed. As a result, the `functionArn` property for `Functions` imported with `fromFunctionArn` will be the raw ARN without the `Function` version or alias.

### Who is affected?

Users importing `Functions` with a version or alias specific `Function` ARN via the `fromFunctionArn` static method.

### How do I resolve this?

We are working on a patch release for this. This [PR](https://github.com/aws/aws-cdk/pull/30003) reverts the initial code change.

**Comment by moelasmar** [comment]
We released a patch release https://github.com/aws/aws-cdk/releases/tag/v2.139.1 that contains the fix of this issue.
