### ISSUE TITLE
EFS: support setting the AZ when setting up a oneZone FileSystem

### ISSUE THREAD

**Issue by kabo** [aws/aws-cdk#30005]
### Describe the feature

We'd like to be able to specify which AZ the one-zone FS should be in

### Use Case

 So it's in the same AZ as the rest of our setup. This is for a test environment so one AZ is fine and cheaper.

### Proposed Solution

There's a `vpcSubnets` constructor prop, it'd be handy if it could work like this

```typescript
    const efs = new FileSystem(this, 'Efs', {
      vpc,
      encrypted: true,
      oneZone: true,
      vpcSubnets: { availabilityZones: [ 'eu-west-1b' ] },
    })
```

But maybe some other solution is easier.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.136.0

### Environment details (OS name and version, etc.)

Artix Linux

**Comment by pahud** [comment]
Sounds good to me.

At this moment it's determined automatically by selecting the first VPC AZ this way, which is not configurable.
https://github.com/aws/aws-cdk/blob/af7dcffa96224a2b0ffef5cd4715a74b6db632c5/packages/aws-cdk-lib/aws-efs/lib/efs-file-system.ts#L770

Having the support to allow users to configure would be great.
