### ISSUE TITLE
(pipes): Add EventBridge Pipes event delivery VPC Endpoint Service

### ISSUE THREAD

**Issue by Liversticks** [aws/aws-cdk#30015]
### Describe the feature

https://aws.amazon.com/about-aws/whats-new/2024/04/amazon-eventbridge-pipes-event-delivery-aws-privatelink/

EventBridge Pipes recently launched support to deliver events through AWS PrivateLink.

### Use Case

This is an official AWS service so we think it would be nice to include it with the other AWS services.

### Proposed Solution

Modify https://github.com/aws/aws-cdk/blob/4f1c94b27ef7f4ceccea0ff39625c0e8add31c9f/packages/aws-cdk-lib/aws-ec2/lib/vpc-endpoint.ts#L274, add `pipes-data` AWS VPC Endpoint Service

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

-

### Environment details (OS name and version, etc.)

all

**Comment by khushail** [comment]
thanks @Liversticks for requesting this feature. Please feel free to refer to this [Contributing guide](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md#step-1-find-something-to-work-on) to get started.
