### ISSUE TITLE
aws-stepfunctions-tasks: Add cpu and memory parameters to EcsRunTask

### ISSUE THREAD

**Issue by kackyt** [aws/aws-cdk#30027]
### Describe the feature

Add cpu and memory parameters to EcsRunTask in StepFunctions to allow flexible allocation of Ecs resources according to the situation.

### Use Case

This is useful when you want to allocate resources flexibly according to the data set used in EcsTask, or when you want to increase memory when retrying from errors such as OOM.

### Proposed Solution

Add cpu and memory parameters to EcsRunTask

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.139.1

### Environment details (OS name and version, etc.)

client:  macOS,Windows,Linux

**Comment by khushail** [comment]
thanks @kackyt for submitting the request and volunteering for PR contribution.

**Comment by daschaa** [comment]
Hi @kackyt - I was looking at this issue and saw that there is the `containerOverrides` property for the EcsRunTask. With a ContainerOverride it seems that you can override the ephemeralStorage and the cpu for an ecs task. Would this already help you/solve the issue?
For documentation reference see here: [https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_stepfunctions_tasks.EcsRunTask.html#containeroverrides](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_stepfunctions_tasks.EcsRunTask.html#containeroverrides)

And here for the API reference: [https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_RunTask.html#API_RunTask_RequestSyntax](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_RunTask.html#API_RunTask_RequestSyntax)

**Comment by kackyt** [comment]
@daschaa 
The method to allocate resources by overriding cpu and memory settings in ContainerOverrides is limited to using ec2 instances in ECS, while allocating resources for Fargate is not possible with ContainerOverrides, so I would like to resolve this feature.

**Comment by daschaa** [comment]
@kackyt Thanks for the clarification! I didn‘t knew that. 👍🏼 Do you have a link to some documentation where I can find that information?

**Comment by kackyt** [comment]
@daschaa 

The task definition reference contains a following link to a description of the Fargate task.

https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#task_size

> For tasks that run on Fargate (both Linux and Windows containers), this field is required and you must use one of the following values, which determines your range of supported values for the memory parameter. The table below shows the valid combinations of task-level CPU and memory.

The same applies to EcsRunTask.

**Comment by VaidSaraswat** [comment]
Hey there I believe was already addressed by this?: https://github.com/aws/aws-cdk/commit/5f597877c75f9e92d3bf08eedb5007ecc3cb001e.

**Comment by kackyt** [comment]
@VaidSaraswat 
This is a feature request for EcsRunTask cpu and memory field of root parameter, not a containerOverrides issue.
