### ISSUE TITLE
(aws-logs): Add metric methods for log group IncomingLogEvents and IncomingBytes

### ISSUE THREAD

**Issue by yattoni** [aws/aws-cdk#30034]
### Describe the feature

Add metric methods for log group IncomingLogEvents and IncomingBytes, similar to existing metric methods like metricInvocations on Lambda functions.

https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/CloudWatch-Logs-Monitoring-CloudWatch-Metrics.html

### Use Case

Create alarms on log ingestion to ensure it is working.

### Proposed Solution

Create `metricIncomingLogEvents` and `metricIncomingBytes` and maybe a generic `metric` methods on the LogGroup class similar to other resources with metric* methods.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.139.1

### Environment details (OS name and version, etc.)

Amazon Linux 2

**Comment by ashishdhingra** [comment]
Perhaps needs to be implemented using guideline at https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md#metrics.

@yattoni Thanks for submitting feature request. Feel free to contribute a PR which could be reviewed by the team.

Thanks,
Ashish
