### ISSUE TITLE
CfnInsightRule and TagManager: Duplicate tag key/value pair leads to INVALID_TAG issue

### ISSUE THREAD

**Issue by neilzhao-aws** [aws/aws-cdk#30056]
### Describe the bug

Following the thread of https://github.com/aws/aws-cdk/issues/20103 but with more evidence.
Digging into CloudTrail, the INVALID_TAG from CfnInsightRules are caused by duplicate key/value pairs.
One of the Tags KeyValue pair is duplicated in the `PutInsightRule` CloudTrail event. 
The CDK changeset shows the key/value pair isn't duplicated

### Expected Behavior

`CfnInsightRule` generated `PutInsightRule` should not duplicate tags.

### Current Behavior

`CfnInsightRule` generated `PutInsightRule` should one duplicate tags.

### Reproduction Steps

create multiple tags on the stack level.

### CDK CLI Version

2.132.0

### Node.js Version

18.19.1

### OS

Linux

### Language

TypeScript

### Language Version

4.9.5

### Other information

I don't think the bug is related to CDk. the cloudformation output is correct.
However, the `PutInsightRule` action taken by the cdk has an extra duplicated tag, leading to the issue.

**Comment by pahud** [comment]
>Reproduction Steps
create multiple tags on the stack level.

Can you share the minimal code snippets that reproduces this bug?
