### ISSUE TITLE
(codebuild): Add support new newly introduced event filter

### ISSUE THREAD

**Issue by aseppala** [aws/aws-cdk#30062]
### Describe the feature

A new feature has been recently introduced in AWS CodeBuild: https://aws.amazon.com/about-aws/whats-new/2024/04/aws-codebuild-managed-github-action-runners/. This feature enables to use AWS CodeBuild as GitHub Actions runner. However, using this feature requires to configure a new event filter which is currently not yet available in CDK.

### Use Case

To be able to use 'aws-cdk-lib/aws-codebuild.Project' L2 Construct to define a runner for Github Action I need to be able to pass in `FilterGroup.inEventOf(EventAction.WORKFLOW_JOB_QUEUED)` but its not available so for now I'm force to use L1 Construct which requires setting up IAM roles etc which would be automatically created by the Project construct.

### Proposed Solution

Introduce new value to `aws-cdk-lib/aws-codebuild.EventAction` enum: "WORKFLOW_JOB_QUEUED"

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.140.0

### Environment details (OS name and version, etc.)

MacOS 14.3.1 (23D60)

**Comment by khushail** [comment]
Hi @aseppala , thanks for requesting this feature.

Thanks @msambol for submitting the PR.

**Comment by aseppala** [comment]
Until this issue is resolved, a working workaround is to use CDK escape hatch:

```ts
import { CfnProject, Project, Source, FilterGroup, EventAction } from 'aws-cdk-lib/aws-codebuild';

const project = new Project(this, 'Project', {
  projectName: props.projectName,
  source: Source.gitHub({
    ...
    webhookFilters: [
      FilterGroup.inEventOf(EventAction.PULL_REQUEST_CREATED),
    ],
  }),
})

const cfnProject = project.node.defaultChild as CfnProject
const triggers = cfnProject.triggers as CfnProject.ProjectTriggersProperty
const filterGroups = triggers.filterGroups as CfnProject.WebhookFilterProperty[][]
// remove wrong (PULL_REQUEST_CREATED) filter
filterGroups[0].pop()
// add correct (WORKFLOW_JOB_QUEUED) filter
filterGroups[0].push({
  type: 'EVENT',
  pattern: 'WORKFLOW_JOB_QUEUED',
})
```
