### ISSUE TITLE
SSM Parameter lookup gives "Not making progress trying to resolve environmental context. Giving up." error

### ISSUE THREAD

**Issue by AvivSamet-Silk** [aws/aws-cdk#30078]
### Describe the bug

When running `npx cdk synth` I get the following error:
![image](https://github.com/aws/aws-cdk/assets/108717750/2133a712-66b5-4297-a17f-2a0fcd61ff5c)

(This stacktrace is produced in verbose mode, in regular mode you get a less descriptive error).

Following the stacktrace, it looks like this happens when I try to look up an SSM string parameter.

### Expected Behavior

This CDK produces a valid cloudformation template that is being deployed by my github actions. For some reason this just isn't working on my local machine.

### Current Behavior

![image](https://github.com/aws/aws-cdk/assets/108717750/2133a712-66b5-4297-a17f-2a0fcd61ff5c)

### Reproduction Steps

This is the code that produces the issue, however I wasn't able to reproduce it outside of my local machine (it works fine on GHA and my coworker's machine):
``` 
 vpc: ec2.IVpc;

  constructor(scope: Construct) {
    const vpcIdParameter = ssm.StringParameter.valueFromLookup(
      scope,
      "vpc/parameter/path"
    );

    const vpc = ec2.Vpc.fromLookup(
      scope,
      "SilkVpc",
      { vpcId: vpcIdParameter }
    );

    this.vpc = vpc;
  }
```

### CDK CLI Version

2.9.0

### Node.js Version

20.3.1

### OS

macOS 14.4.1

### Language

TypeScript

**Comment by khushail** [comment]
Hi @AvivSamet-Silk , thanks for reaching out.

From the error it looks like, the user profile calling the api is not configured on your local machine. You can run this - `aws sts get-caller-identity` in console to see which user profile is configured. 

You could create a user in AWS Console and then generate access and security key and configure the credentials in ~/.aws/config file with this new user . Run `cdk bootstrap` and run `cdk deploy --profile <user-profile>`. it should work fine. Here is a [doc for reference](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-configure.html) on how to configure aws cli.

Please feel free to reach out if that does not solve the issue.

**Comment by AvivSamet-Silk** [comment]
I am using `aws sso login` to get my local credentials. Running `aws sts get-caller-identity` returns a role with SystemAdministrator privileges. Running `cdk bootstrap --verbose` Also results in the following error:
![image](https://github.com/aws/aws-cdk/assets/108717750/329cde43-8345-4e70-8fce-44f570f53d15)

**Comment by AvivSamet-Silk** [comment]
I also tried exporting AWS creds locally, and that didn't resolve the issue as well. I'm not sure what else to try at this point.

**Comment by khushail** [comment]
@AvivSamet-Silk , are you still facing the issue ?
