### ISSUE TITLE
(ivs-alpha): support advanced channel type

### ISSUE THREAD

**Issue by mazyu36** [aws/aws-cdk#30075]
### Describe the feature

Amazon IVS has been supporting advanced channel types since June 2023. 
However, the current Channel Construct only supports BASIC and STANDARD channel types.

See: 
https://aws.amazon.com/about-aws/whats-new/2023/06/amazon-ivs-advanced-channel-types-input-encoding/?nc1=h_ls

### Use Case

To use advanced channel types using CDK.

### Proposed Solution

* Add `ADVANCED_HD` and `ADVANCED_SD` to the `ChannelType`.
* Add `preset` property to the `Channel` Construct. Additionally, implement validation according to the following:

> An optional transcode preset for the channel. This is selectable only for ADVANCED_HD and ADVANCED_SD channel types. For those channel types, the default preset is HIGHER_BANDWIDTH_DELIVERY. For other channel types (BASIC and STANDARD), preset is the empty string ("").

See: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ivs-channel.html#cfn-ivs-channel-preset

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.140.0

### Environment details (OS name and version, etc.)

MacOS

**Comment by ashishdhingra** [comment]
- https://github.com/aws/aws-cdk/tree/main/packages/aws-cdk-lib/aws-ivs, there are no official hand-written ([L2](https://docs.aws.amazon.com/cdk/latest/guide/constructs.html#constructs_lib)) constructs for this service yet.
  ```
  An experimental construct library for this service is available in preview. Since it is not stable yet, it is distributed as a separate package so that you can pin its version independently of the rest of the CDK. See the package:

  @aws-cdk/aws-ivs-alpha
  ```
- The CF documentation [link](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ivs-channel.html#cfn-ivs-channel-preset) does specify support for `ADVANCED_SD` and `ADVANCED_HD` channel types. However, CDK [ChannelType](https://github.com/aws/aws-cdk/blob/8e98078a54896b7a9531ba4b11bb0c6221383e34/packages/%40aws-cdk/aws-ivs-alpha/lib/channel.ts#L57) enum is missing these channel types.

@mazyu36 Feel free to contribute a PR for this feature request which could be reviewed by the team.

Thanks,
Ashish
