### ISSUE TITLE
CLI ignores profile in cdk.json

### ISSUE THREAD

**Issue by prencher** [aws/aws-cdk#3007]
* **I'm submitting a ...**
  - [X] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/awslabs/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*

When you specify `profile` in `cdk.json`, it's ignored.

* **What is the expected behavior (or behavior of feature suggested)?**

`profile` key is respected.

* **What is the motivation / use case for changing the behavior or adding this feature?**

Having reasonable defaults for a project. The ultimate ideal would be per-env credentials but we're using multiple `cdk.json` files (one per account) as a stopgap.

* **Please tell us about your environment:**
  
  - CDK CLI Version: 0.35.0
  - Module Version: 0.35.0
  - OS: macOS Mojave 
  - Language: TypeScript

**Comment by boricic** [comment]
I've experienced the same issue. Following [this](https://github.com/awsdocs/aws-cdk-guide/blob/master/doc_source/tools.md) I was under the impression that adding `profile` to `cdk.json` should work, but it doesn't.

If that worked, for me that would be a major improvement since I have multiple profiles I currently have to specify `--profile` option with every cli command.

**Comment by shivlaks** [comment]
@prencher @boricic - I don't believe we support all the switches in `cdk.json` and we should. tagging this as a bug

**Comment by roll** [comment]
Hi, thanks for solving it!

Is it a part of `1.36.1`? The `ckd.json->profile` still doesn't seem to affect my `npx cdk` calls

**Comment by shivlaks** [comment]
> Hi, thanks for solving it!
> 
> 
> 
> Is it a part of `1.36.1`? The `ckd.json->profile` still doesn't seem to affect my `npx cdk` calls

it will be included in the next release (likely 1.37.0)
