### ISSUE TITLE
aws-dynamodb: OnDemandThroughput configuration

### ISSUE THREAD

**Issue by LeeroyHannigan** [aws/aws-cdk#30091]
### Describe the feature

Sets the maximum number of read and write units for the specified on-demand table. If you use this property, you must specify MaxReadRequestUnits, MaxWriteRequestUnits, or both.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html#cfn-dynamodb-table-ondemandthroughput

### Use Case

New DynamoDB feature not yet implemented in CDK

### Proposed Solution

Include the new parameters as soon as CFN is updated to the current version

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.122.0

### Environment details (OS name and version, etc.)

MacOS

**Comment by go-to-k** [comment]
Thanks for this issue.
It would be great if you could address both of these: `AWS::DynamoDB::GlobalTable`, `AWS::DynamoDB::Table`.


These have already been added to the L1 Constructs: https://github.com/aws/aws-cdk/pull/30074 .

```
├[~] service aws-dynamodb
│ └ resources
│    ├[~] resource AWS::DynamoDB::GlobalTable
│    │ ├ properties
│    │ │  └[+] WriteOnDemandThroughputSettings: WriteOnDemandThroughputSettings
│    │ └ types
│    │    ├[~] type GlobalSecondaryIndex
│    │    │ └ properties
│    │    │    └[+] WriteOnDemandThroughputSettings: WriteOnDemandThroughputSettings
│    │    ├[+] type ReadOnDemandThroughputSettings
│    │    │ ├  name: ReadOnDemandThroughputSettings
│    │    │ └ properties
│    │    │    └MaxReadRequestUnits: integer
│    │    ├[~] type ReplicaGlobalSecondaryIndexSpecification
│    │    │ └ properties
│    │    │    └[+] ReadOnDemandThroughputSettings: ReadOnDemandThroughputSettings
│    │    ├[~] type ReplicaSpecification
│    │    │ └ properties
│    │    │    └[+] ReadOnDemandThroughputSettings: ReadOnDemandThroughputSettings
│    │    └[+] type WriteOnDemandThroughputSettings
│    │      ├  name: WriteOnDemandThroughputSettings
│    │      └ properties
│    │         └MaxWriteRequestUnits: integer
│    └[~] resource AWS::DynamoDB::Table
│      ├ properties
│      │  └[+] OnDemandThroughput: OnDemandThroughput
│      └ types
│         ├[~] type GlobalSecondaryIndex
│         │ └ properties
│         │    └[+] OnDemandThroughput: OnDemandThroughput
│         └[+] type OnDemandThroughput
│           ├  name: OnDemandThroughput
│           └ properties
│              ├MaxReadRequestUnits: integer
│              └MaxWriteRequestUnits: integer
```
