### ISSUE TITLE
(docdb): copyTagsToSnapshot is missing in the DatabaseCluster Construct

### ISSUE THREAD

**Issue by mazyu36** [aws/aws-cdk#30090]
### Describe the feature

In the [DatabaseCluster](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_docdb.DatabaseCluster.html) Construct, [copyTagsToSnapshot](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_docdb.CfnDBCluster.html#copytagstosnapshot) is missing.

### Use Case

Use this when you want to copy tags to snapshots.

### Proposed Solution

Add copyTagsToSnapshot  to the DatabaseCluster Construct.

```ts
const cluster = new docdb.DatabaseCluster(this, 'Database', {
  masterUser: {
    username: 'myuser', // NOTE: 'admin' is reserved by DocumentDB
    excludeCharacters: '\"@/:', // optional, defaults to the set "\"@/" and is also used for eventually created rotations
    secretName: '/myapp/mydocdb/masteruser', // optional, if you prefer to specify the secret name
  },
  instanceType: ec2.InstanceType.of(ec2.InstanceClass.MEMORY5, ec2.InstanceSize.LARGE),
  vpc,
  copyTagsToSnapshot: true, // Add
});
```

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.140.0

### Environment details (OS name and version, etc.)

MacOS

**Comment by ashishdhingra** [comment]
Refer [AWS::DocDB::DBCluster](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-docdb-dbcluster.html), [CopyTagsToSnapshot](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-docdb-dbcluster.html#cfn-docdb-dbcluster-copytagstosnapshot) is a supported property.

@mazyu36 Looks like you linked this issue to a PR for experimental `aws-neptune-alpha` construct. Please check if you intended to create a separate PR for `aws-cdk-lib.aws_docdb` `DatabaseCluster` construct.

Thanks,
Ashish

**Comment by mazyu36** [comment]
@ashishdhingra 
Thanks for your confirmation.
I mistakenly linked a neptune PR, so I've now removed. 

For the different module, I plan to create a separate pull request for the docsdb changes, distinct from the one for neptune. Apologies for the confusion.
