### ISSUE TITLE
aws-rds:  CDK to support default engine version for Aurora MySQL Version 3  "3.04.2" 

### ISSUE THREAD

**Issue by aashishgk7760** [aws/aws-cdk#30109]
### Describe the feature

Hello Team , 

Currently CDK does not show option to select the Engine version `3.04.2` [1] 

[1] https://github.com/aws/aws-cdk/blob/v2.140.0/packages/aws-cdk-lib/aws-rds/lib/cluster-engine.ts

### Use Case

 default engine version for Aurora MySQL Version 3  "3.04.2" 

### Proposed Solution

Update the below class name to include "3.04.2" 

export class AuroraMysqlEngineVersion {
 public static readonly VER_3_04_2 = AuroraMysqlEngineVersion.builtIn_8_0('3.04.2');
}

### Other Information

N/A

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.140.0

### Environment details (OS name and version, etc.)

Mac OS

**Comment by ashishdhingra** [comment]
The feature request appears to be valid. Per [Database engine updates for Amazon Aurora MySQL version 3](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraMySQLReleaseNotes/AuroraMySQL.Updates.30Updates.html), version `3.04.2` appears to be default version when instance is created using AWS console.

@aashishgk7760 Feel free to contribute PR for this change.

Thanks,
Ashish
