### ISSUE TITLE
aws-synthetics: Python Selenium Runtime to support Python 3.9 and above

### ISSUE THREAD

**Issue by nirmana** [aws/aws-cdk#30137]
### Describe the feature

AWS Synthetics runtime support for Python 3.9 and above

### Use Case

AWS has recently announced the end of life (EOL) for Python 3.8 in AWS Lambda runtimes. Unfortunately, the synthetic canary runtimes have not been updated to support newer Python versions. As a result, the Lambdas generated by synthetic canaries are running on an outdated Python runtime that will soon be obsolete.

AWS Notification on Python 3,8 Runtime the EOL

> Starting on October 14, 2024, Lambda will no longer apply security patches and other updates to the Python 3.8 runtime used by Lambda functions, and functions using Python 3.8 will no longer be eligible for technical support. Also, Python 3.8 will no longer be available in the AWS Console, although you can still create and update functions that use Python 3.8 via AWS CloudFormation, the AWS CLI, AWS SAM, or other tools. Starting February 28, 2025, you will no longer be able to create new Lambda functions using the Python 3.8 runtime. Starting March 31, 2025, you will no longer be able to update existing functions using the Python 3.8 runtime.

### Acknowledgements

- [X] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### CDK version used

2.141.0

### Environment details (OS name and version, etc.)

Windows

**Comment by pahud** [comment]
That would be awesome! Feel free to submit your PR and let me know if you need any help. Thank!

**Comment by nirmana** [comment]
Hi @pahud , I've just realized that the AWS platform does not yet support Python 3.8+ versions. This has to wait till it gets the runtime support and happy to fix it whenever it gets available. Is there a way to raise this issue or request support for newer Python versions?

reference - https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Synthetics_Library_python_selenium.html#CloudWatch_Synthetics_runtimeversion-syn-python-selenium-3.0

**Comment by fabianf92** [comment]
Any updates on this? We want to update all our lambda functions to python 3.9+ before EOL in October.

**Comment by pahud** [comment]
@fabianf92 CDK is pending on the CFN support.

Please help the CFN team prioritize with 👍  on https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/2039

After CFN support that, CDK would be able to include that support shortly.
