### ISSUE TITLE
The runtime parameter of python3.7 is no longer supported for creating or updating AWS Lambda functions.

### ISSUE THREAD

**Issue by abdullahodibat** [aws/aws-cdk#30145]
### Describe the bug

Hello,
**please note this is a similar issue to: https://github.com/aws/aws-cdk/issues/21470**
i am unable to create cloudformation stacks anymore. because of these errors:

`Resource handler returned message: "The runtime parameter of python3.7 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (python3.12) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: b575bb11-b5c9-45dc-8d9d-198a6fa62166)`

`The runtime parameter of nodejs14.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs20.x) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: 37f11f2e-679b-4234-abd7-ed4a01afe84b)" (RequestToken: 109b8402-1a62-b4a4-633d-736a5a14647d, HandlerErrorCode: InvalidRequest)`

for some reason some reason the resources below are being created with python 3.7.
![image](https://github.com/aws/aws-cdk/assets/15142264/5e7d6b59-1e17-47ae-b9c5-3d2f67980703)

Although the cdk  libraries versions are the latest.

### Expected Behavior

I should be able to create stacks without errors.

### Current Behavior

The cloudformation stack failes with these errors:
`Resource handler returned message: "The runtime parameter of python3.7 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (python3.12) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: b575bb11-b5c9-45dc-8d9d-198a6fa62166)`

`The runtime parameter of nodejs14.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs20.x) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: 37f11f2e-679b-4234-abd7-ed4a01afe84b)" (RequestToken: 109b8402-1a62-b4a4-633d-736a5a14647d, HandlerErrorCode: InvalidRequest)`

### Reproduction Steps

These are the aws-cdk versions that i have:
`aws-cdk.aws-sqs==1.204.0
aws-cdk.aws-ec2==1.204.0
aws-cdk.aws-rds==1.204.0
aws-cdk.aws-sagemaker==1.204.0
aws-cdk.aws-apigateway==1.204.0
aws-cdk.aws-ecr-assets==1.204.0
aws-cdk.aws-s3-deployment==1.204.0
aws-cdk.aws-s3-notifications==1.204.0
aws-cdk.aws-ecs==1.204.0
aws-cdk.aws-ecs-patterns==1.204.0
aws-cdk.aws-cloudwatch-actions==1.204.0
aws-cdk.core==1.204.0`

the cdk cli version is:
`2.140.0`

### CDK CLI Version

2.140.0

### Node.js Version

v20.13.0

### OS

MacOS Montery

### Language

Python

### Language Version

3.9.17

**Comment by ashishdhingra** [comment]
@abdullahodibat Good morning. Could you please share the minimal reproducible code solution to reproduce the issue (along with `package.json`)?

I do see that you are using AWS CDK v1 packages. AWS CDK v1 has reached End-of-Support on 2023-06-01. The v1 packages are no longer being updated, and users should migrate to AWS CDK v2. For more information on how to migrate, see https://docs.aws.amazon.com/cdk/v2/guide/migrating-v2.html.

Thanks
Ashish

**Comment by abdullahodibat** [comment]
@ashishdhingra Thanks alot for your hint. i totally missed the V2 thing, cdk v2 is another respository. i will upgrade :)

Regards,
Abdullah

**Comment by abdullahodibat** [comment]
It worked perfectly locally after i upgraded to cdk 2, but its it fails on circle ci, although i updated cdk there too.
i used `aws-cdk-lib==2.141.0` and `jsii==1.98.0`,,,
 but getting this error on circleci:

`Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/circleci/Credit-Risk-Service/deployment/credit_risk_service.py", line 7, in <module>
    MainStack(app)
  File "/home/circleci/Credit-Risk-Service/.venv/lib/python3.9/site-packages/jsii/_runtime.py", line 118, in __call__
    inst = super(JSIIMeta, cast(JSIIMeta, cls)).__call__(*args, **kwargs)
  File "/home/circleci/Credit-Risk-Service/deployment/main_stack.py", line 31, in __init__
    api_gateway_stack = ApiGatewayStack(self, sagemaker_endpoint=sagemaker_stack.sagemaker_endpoint_v2)
  File "/home/circleci/Credit-Risk-Service/.venv/lib/python3.9/site-packages/jsii/_runtime.py", line 118, in __call__
    inst = super(JSIIMeta, cast(JSIIMeta, cls)).__call__(*args, **kwargs)
  File "/home/circleci/Credit-Risk-Service/deployment/api_gateway_stack.py", line 194, in __init__
    metric = cloudwatch.Metric(
  File "/home/circleci/Credit-Risk-Service/.venv/lib/python3.9/site-packages/jsii/_runtime.py", line 118, in __call__
    inst = super(JSIIMeta, cast(JSIIMeta, cls)).__call__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'dimensions'`

Thanks in advance :)

**Comment by abdullahodibat** [comment]
> It worked perfectly locally after i upgraded to cdk 2, but its it fails on circle ci, although i updated cdk there too. i used `aws-cdk-lib==2.141.0` and `jsii==1.98.0`,,, but getting this error on circleci:
> 
> `Traceback (most recent call last): File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main return _run_code(code, main_globals, None, File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code exec(code, run_globals) File "/home/circleci/Credit-Risk-Service/deployment/credit_risk_service.py", line 7, in <module> MainStack(app) File "/home/circleci/Credit-Risk-Service/.venv/lib/python3.9/site-packages/jsii/_runtime.py", line 118, in __call__ inst = super(JSIIMeta, cast(JSIIMeta, cls)).__call__(*args, **kwargs) File "/home/circleci/Credit-Risk-Service/deployment/main_stack.py", line 31, in __init__ api_gateway_stack = ApiGatewayStack(self, sagemaker_endpoint=sagemaker_stack.sagemaker_endpoint_v2) File "/home/circleci/Credit-Risk-Service/.venv/lib/python3.9/site-packages/jsii/_runtime.py", line 118, in __call__ inst = super(JSIIMeta, cast(JSIIMeta, cls)).__call__(*args, **kwargs) File "/home/circleci/Credit-Risk-Service/deployment/api_gateway_stack.py", line 194, in __init__ metric = cloudwatch.Metric( File "/home/circleci/Credit-Risk-Service/.venv/lib/python3.9/site-packages/jsii/_runtime.py", line 118, in __call__ inst = super(JSIIMeta, cast(JSIIMeta, cls)).__call__(*args, **kwargs) TypeError: __init__() got an unexpected keyword argument 'dimensions'`
> 
> Thanks in advance :)

Ok working now. The cdk cloudwatch Metric Function parameter was changed to `dimensions_map` instead of `dimensions` ,,, no idea how it was working locally!

**Comment by ashishdhingra** [comment]
@abdullahodibat Thanks for the confirmation. Glad that it's working for you now.
