### ISSUE TITLE
(aws-apprunner-alpha): missing apprunner runtime Python_311

### ISSUE THREAD

**Issue by hiselitelordship** [aws/aws-cdk#30146]
### Describe the bug

Apprunner supports two Python Runtimes: 3 and 311 as documented here: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apprunner-service-codeconfigurationvalues.html

PYTHON_311 is missing from https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/aws-apprunner-alpha/lib/service.ts#L210

### Expected Behavior

It is expected that the CDK should make all supported runtimes available.

### Current Behavior

It only supports Python_3  (this translates to the extremely old Python 3.8)

### Reproduction Steps

apprunner_alpha.Service(
    self,
    "My Web Site",
    instance_role=web_instance_role,
    source=apprunner_alpha.Source.from_git_hub(
        repository_url="",
        branch="main",
        configuration_source=apprunner_alpha.ConfigurationSourceType.API,
        code_configuration_values=apprunner_alpha.CodeConfigurationValues(
            **runtime=apprunner_alpha.Runtime.PYTHON_3,**
            port="5000",
            start_command="",
            build_command="",
            environment_variables={},
        ),
        connection=apprunner_alpha.GitHubConnection.from_connection_arn(
            web_github_arn
        ),
    ),
)

### Possible Solution

  /**
   * Python 3.11
   */
  public static readonly PYTHON_311 = Runtime.of('PYTHON_311')

### CDK CLI Version

2.140.0

### Node.js Version

v20.9.0

### OS

Ubuntu

### Language

Python

### Language Version

Python 3.11

**Comment by ashishdhingra** [comment]
Appears to be a valid request for experimental `aws-apprunner-alpha` package. @hiselitelordship Feel free to contribute PR which could be reviewed by the team.
