### ISSUE TITLE
(api-gateway): StepFunctionsIntegration doesnt pass Cognito claims with authorizer:true

### ISSUE THREAD

**Issue by gmborisov** [aws/aws-cdk#30144]
Current StepfunctionIntegreation vtl script for integration request mapping doesnt support Cognito claims in authorization context.
`
#if ($includeAuthorizer)
        #set($inputString = "$inputString, @@authorizer@@:{")
        #foreach($paramName in $context.authorizer.keySet())
            #set($inputString = "$inputString @@$paramName@@: @@$util.escapeJavaScript($context.authorizer.get($paramName))@@")
            #if($foreach.hasNext)
                #set($inputString = "$inputString,")
            #end
        #end
        #set($inputString = "$inputString }")
    #end
`

If I specify just the 'claims' in the forloop, then I will get all details:
`    
#if ($includeAuthorizer)
        #set($inputString = "$inputString, @@authorizer@@:{")
        #foreach($paramName in $context.authorizer.claims.keySet())
            #set($inputString = "$inputString @@$paramName@@: @@$util.escapeJavaScript($context.authorizer.claims.get($paramName))@@")
            #if($foreach.hasNext)
                #set($inputString = "$inputString,")
            #end
        #end
        #set($inputString = "$inputString }")
    #end
`

### Expected Behavior

Stepfunction input contains all Cognito claims inside 'authorizer' object
![image](https://github.com/aws/aws-cdk/assets/15331163/a7d66d28-367b-4a24-9b47-123b27b281d6)

### Current Behavior

The authorizer.claims object is empty:
![image](https://github.com/aws/aws-cdk/assets/15331163/eb708565-bc19-4946-a8c1-584090a480dc)

### Reproduction Steps

1. Create Cognito user pool
2. Create RestApi with StepFunctionsIntegration for a resource method
3. Specify authorizerType = Cognito and provide a link to the created pool
4.  specify authorizer: true

### Possible Solution

iterate over claims separately.

### CDK CLI Version

2.102.0 (build 2abc59a)

### Node.js Version

20.5.1

### OS

Windows 11 Pro

### Language

TypeScript

**Comment by ashishdhingra** [comment]
@gmborisov Good morning. Thanks for opening the issue. Could you please elaborate the issue by providing the minimal reproducible CDK code, which confirms that this is the issue with CDK?

Thanks,
Ashish
