### ISSUE TITLE
ecsPatterns.ApplicationLoadBalancedFargateService: targetGroup cannot be declared.

### ISSUE THREAD

**Issue by ZenergyBryson** [aws/aws-cdk#30151]
### Describe the issue

This is my first submission, so try not to rake me over the coals too harshly if this is a bug and not a documentation issue.

In the documentation, `targetGroup` shows up in the Properties table, along with `loadBalancer`, `certificate`, and other properties that CAN be assigned.  I have verified I'm using CDK v2.141.0 on my local, and am reading the docs for 2.141.0, but when I try to run `diff`, `synth`, or `deploy` I get this:
error TS2345: Argument of type '{ loadBalancer: cdk.aws_elasticloadbalancingv2.IApplicationLoadBalancer; targetGroup: cdk.aws_elasticloadbalancingv2.IApplicationTargetGroup; publicLoadBalancer: false; ... 14 more ...; openListener: false; }' is not assignable to parameter of type 'ApplicationLoadBalancedFargateServiceProps'.
  Object literal may only specify known properties, and 'targetGroup' does not exist in type 'ApplicationLoadBalancedFargateServiceProps'.
179           targetGroup: jenkinsTargetGroup,

### Links

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ecs_patterns.ApplicationLoadBalancedFargateService.html

**Comment by khushail** [comment]
Hi @ZenergyBryson , thanks for reaching out.  I tested the above scenario with this code and it worked fine for me. Sharing the code and snippet of synthesized template with mentioned properties as well -

```
   const cluster= new ecs.Cluster(this, 'Cluster', {
      vpc: new ec2.Vpc(this, 'Vpc', {
        maxAzs: 2,
        subnetConfiguration: [
          {
            name: 'public',
            subnetType: ec2.SubnetType.PUBLIC,
          },
          {
            name: 'private',
            subnetType: ec2.SubnetType.PRIVATE_WITH_EGRESS
          },
        ],
      }),
    }); 

    const loadBalancedFargateService = new ecsPatterns.ApplicationLoadBalancedFargateService(this, 'Service', {
      cluster,
      memoryLimitMiB: 1024,
      desiredCount: 1,
      cpu: 512,
      taskImageOptions: {
        image: ecs.ContainerImage.fromRegistry("amazon/amazon-ecs-sample"),
      },
      taskSubnets: {
        subnets: [ec2.Subnet.fromSubnetId(this, 'subnet', 'VpcISOLATEDSubnet1Subnet80F07FA0')],
      },
      loadBalancerName: 'application-lb-name',
    });

    const listner = loadBalancedFargateService.loadBalancer.addListener('listener', {
      port: 80,
    });

    const targetGroup = listner.addTargets('Fleet', { port: 80 });
```

```
"ServiceLBPublicListener46709EAA": {
   "Type": "AWS::ElasticLoadBalancingV2::Listener",
   "Properties": {
    "DefaultActions": [
     {
      "TargetGroupArn": {
       "Ref": "ServiceLBPublicListenerECSGroup0CC8688C"
      },
      "Type": "forward"
     }
    ],
    "LoadBalancerArn": {
     "Ref": "ServiceLBE9A1ADBC"
    },
    "Port": 80,
    "Protocol": "HTTP"
   },
   "Metadata": {
    "aws:cdk:path": "PatternIssueStack/Service/LB/PublicListener/Resource"
   }
  },
  "ServiceLBPublicListenerECSGroup0CC8688C": {
   "Type": "AWS::ElasticLoadBalancingV2::TargetGroup",
   "Properties": {
    "Port": 80,
    "Protocol": "HTTP",
    "TargetGroupAttributes": [
     {
      "Key": "stickiness.enabled",
      "Value": "false"
     }
    ],
    "TargetType": "ip",
    "VpcId": {
     "Ref": "Vpc8378EB38"
    }
```


I am not sue why you are facing this error. Could you please share the minimum reproducible code.
