### ISSUE TITLE
ec2: support `instanceInitiatedShutdownBehavior` for EC2 instance

### ISSUE THREAD

**Issue by badmintoncryer** [aws/aws-cdk#30164]
### Describe the feature

Add `instanceInitiatedShutdownBehavior` prop for EC2 Instance L2 construct.

### Use Case

Cloudforamtion supports to specify `instanceInitiatedShutdownBehavior` for EC2 instance but CDK cannot.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-instance.html#cfn-ec2-instance-instanceinitiatedshutdownbehavior

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.141.0

### Environment details (OS name and version, etc.)

irrelevant

**Comment by pahud** [comment]
@badmintoncryer  We're looking forward to your PR as always. Thank you!
