### ISSUE TITLE
config: support for proactive evaluation mode

### ISSUE THREAD

**Issue by badmintoncryer** [aws/aws-cdk#30172]
### Describe the feature

CDK supports for proactive evaluation of AWS Config.

### Use Case

AWS Config supports proactive evaluation in addition to detective mode.
https://docs.aws.amazon.com/config/latest/developerguide/evaluate-config-rules.html

However, CDK can only configure detective mode now.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.141.0

### Environment details (OS name and version, etc.)

irrelevant

**Comment by pahud** [comment]
@badmintoncryer  We're looking forward to your PR as always. Thank you!
