### ISSUE TITLE
dms: CfnDataProviderProps is missing the 'Settings' field of AWS::DMS::DataProvider.

### ISSUE THREAD

**Issue by stowns** [aws/aws-cdk#30224]
### Describe the bug

[CfnDataProviderProps](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_dms.CfnDataProviderProps.html) is missing the 'Settings' field of [AWS::DMS::DataProvider](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-dataprovider.html).

### Expected Behavior

I would expect `CfnDataProviderProps` to include a `settings` property for configuring database properties ie)
```
"Settings": {
    "DocDbSettings": {
        "ServerName": "my-server-name",
        "Port": 27017,
        "DatabaseName": "docdb",
        "SslMode": "require"
    }
}
```

### Current Behavior

There is no `settings` property of the `CfnDataProviderProps` construct

### Reproduction Steps

```
new CfnDataProvider(this, 'my-data-provider', {
  // try to add 'settings'
})
```

### CDK CLI Version

2.141.0

### Node.js Version

18.18.0

### OS

MacOS 14.4.1

### Language

TypeScript

**Comment by ashishdhingra** [comment]
Reproducible.

The CFN Schema at https://github.com/cdklabs/awscdk-service-spec/commits/main/sources/CloudFormationSchema/us-east-1/aws-dms-dataprovider.json appears to be have `Settings` as one of the properties for `AWS::DMS::DataProvider`. This is in sync with https://d1uauaxba7bl26.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json.

Needs review with the team.

**Comment by moelasmar** [comment]
fixed by this PR https://github.com/aws/aws-cdk/pull/31800 .. it will be available in next release
