### ISSUE TITLE
cdk-lib: Typescript template uses obsolete 'source-map-support/register'

### ISSUE THREAD

**Issue by samloibl** [aws/aws-cdk#30231]
### Describe the bug

When creating a Typescript project via `cdk init app --language typescript`, the generated code imports`source-map-support/register`. This library is obsolete, and is not required for node versions `12.12.0` or higher (see [docs](https://github.com/evanw/node-source-map-support?tab=readme-ov-file#node-support)).

The library interferes with `tsx`, and results in invalid stack traces (see [this bug report](https://github.com/privatenumber/tsx/issues/447#issuecomment-2113214647)).
`ts-node` does not appear to be affected, but stack traces equally work without the library.

### Expected Behavior

`source-map-support` should not be included in `package.json`, and not be imported in the .ts file in /bin.

When running the synth using `tsx` instead of `ts-node`, stack traces for uncaught errors should be correct.

### Current Behavior

The generated `package.json` file includes `source-map-support` as a dependency, and the generated .ts file in /bin includes `import 'source-map-support/register';`

When running the synth using `tsx` via `npx tsx bin/<project>.ts`, the stack trace will be incorrect, and point to an incorrect line number:

```
Error: Duh!
    at new TsxIssue447Stack (/Users/me/tsx-issue447/lib/tsx-issue447-stack.ts:2:1366)
    at /Users/me/tsx-issue447/bin/tsx-issue447.ts:3:950
    at Object.<anonymous> (/Users/me/tsx-issue447/bin/tsx-issue447.ts:4:3)
 ```

### Reproduction Steps

```
nvm use 20
mkdir tsx-issue447 && cd tsx-issue447
npx cdk init app --language typescript
sed -i.bak 's/\/\/ The code.*$/throw new Error("Duh!");/' lib/tsx-issue447-stack.ts
npx tsx bin/tsx-issue447.ts
```

### Possible Solution

Remove the library from dependencies, and remove the import

Changes required:
* Remove from .ts template:  https://github.com/aws/aws-cdk/blob/7624c62ffd293187749f742de70695af9b5f4f87/packages/aws-cdk/lib/init-templates/app/typescript/bin/%25name%25.template.ts#L2
* Remove from package.json template: https://github.com/aws/aws-cdk/blob/7624c62ffd293187749f742de70695af9b5f4f87/packages/aws-cdk/lib/init-templates/app/typescript/package.json#L25

### CDK CLI Version

2.141.0 (build 3d1c06e)

### Node.js Version

v20.11.1, v18.17.0, v16.20.2

### OS

OSX

### Language

TypeScript

### Language Version

5.4.5

**Comment by pahud** [comment]
Thank you for bringing this to our attention. We'll discuss this with the team.
