### ISSUE TITLE
elbv2: IPv6 only support

### ISSUE THREAD

**Issue by pahud** [aws/aws-cdk#30256]
### Describe the feature

Application Load Balancer launches IPv6 only support for internet clients
https://aws.amazon.com/about-aws/whats-new/2024/05/application-load-balancer-ipv6-internet-clients/

Let's include this support in CDK.

### Use Case

For customers using ALB for IPv6 only.

### Proposed Solution

Add a new enum with some checks as only ALB support that.

https://github.com/aws/aws-cdk/blob/8bac15da95f8b26498ca9c4fce88f9f3cb3a9478/packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/shared/enums.ts#L4-L14

### Other Information

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-loadbalancer.html#cfn-elasticloadbalancingv2-loadbalancer-ipaddresstype

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

all

### Environment details (OS name and version, etc.)

all

**Comment by go-to-k** [comment]
Thanks @pahud 
I found the PR for this feature already submitted.

see: https://github.com/aws/aws-cdk/pull/30248

**Comment by pahud** [comment]
thank you for letting me know @go-to-k
