### ISSUE TITLE
IConstruct.node.addError no-op when called from an aspect

### ISSUE THREAD

**Issue by strax** [aws/aws-cdk#3026]
* **I'm submitting a ...**
  - [x] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/awslabs/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
We have an aspect that we use to validate certain properties of constructs. Ideally we'd use `construct.node.addError(...)` from within the aspect to not bail at the first error. However, calling `addError` from within the aspect seems to do nothing. As a workaround, we fall back to throwing an error if the validation fails.

* **What is the expected behavior (or behavior of feature suggested)?**
`IConstructNode.addError` reports an error when it is called from within `IConstruct.apply`.

* **Please tell us about your environment:**
  
  - CDK CLI Version: 0.35.0
  - Module Version: 0.35.0
  - Language: TypeScript

**Comment by rix0rrr** [comment]
Cannot reproduce this, wrote a unit test in linked PR in which this works as intended.

**Comment by strax** [comment]
@rix0rrr I set up a minimal repro at https://github.com/strax/cdk-3122-repro. Note that it is against 0.36, I haven't checked if `master` has this issue too. I can revisit when the next version is released.

**Comment by eladb** [comment]
Closing for now. Please reopen if this is still relevant in 1.x
