### ISSUE TITLE
rds: Bug in writer/reader definition of clusters

### ISSUE THREAD

**Issue by lucabrunox** [aws/aws-cdk#30260]
### Describe the bug

When creating a fresh cluster with readers and writer, one of the reader instances is effectively created before the writer and becomes the actual writer. So the opposite of what's written in the CDK code happens. This is a bug and it's reproducible.

### Expected Behavior

The expected behavior is that the writer specified in CDK is indeed the writer when the cluster is created.

### Current Behavior

The current behavior is that the writer becomes the reader, and viceversa, on a fresh cluster creation, which is the opposite of what's specified in CDK.

The CDK puts the writer instance first in CloudFormation, but that's not enough to guarantee that the first instance being created in the cluster because CloudFormation creates resources in parallel.

### Reproduction Steps

Code:

```
import { App, RemovalPolicy, Stack, StackProps } from 'aws-cdk-lib';
import { InstanceClass, InstanceSize, InstanceType, SubnetType, Vpc } from 'aws-cdk-lib/aws-ec2';
import {
  AuroraMysqlEngineVersion,
  ClusterInstance,
  Credentials,
  DatabaseCluster,
  DatabaseClusterEngine,
} from 'aws-cdk-lib/aws-rds';

export class RDSReproduceStack extends Stack {
  constructor(parent: App, id: string, props: StackProps, vpc: Vpc) {
    super(parent, id, props);

    const cluster = new DatabaseCluster(this, 'testcluster', {
      clusterIdentifier: 'testcluster',
      engine: DatabaseClusterEngine.auroraMysql({ version: AuroraMysqlEngineVersion.VER_3_04_1 }),
      credentials: Credentials.fromGeneratedSecret('myuser', {}),
      writer: ClusterInstance.provisioned('writer', {
        instanceIdentifier: 'writer',
        instanceType: InstanceType.of(InstanceClass.BURSTABLE4_GRAVITON, InstanceSize.MEDIUM),
        publiclyAccessible: false,
      }),
      serverlessV2MinCapacity: 0.5,
      serverlessV2MaxCapacity: 1.0,
      readers: [
        ClusterInstance.serverlessV2('reader', {
          scaleWithWriter: true,
          publiclyAccessible: false,
        }),
      ],
      vpc: vpc,
      vpcSubnets: {
        subnetType: SubnetType.PRIVATE_WITH_EGRESS,
      },
      removalPolicy: RemovalPolicy.DESTROY,
    });
  }
}
```

Result, see in the image that the writer is the reader and viceversa, on a freshly created cluster:

![snap 240508161922 wxXVOsXL](https://github.com/aws/aws-cdk/assets/480920/9a4c2d5a-6211-4522-b6c9-2a9cdd1e3441)

### Possible Solution

The possible solution is to add a dependency on the writer instance to all the reader instances here: https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-rds/lib/cluster.ts , to guarantee that the writer instance is the first instance being created in the cluster and thus become the writer.

### CDK CLI Version

2.130.0

### Node.js Version

18

### OS

Ubuntu

### Language

TypeScript

**Comment by pahud** [comment]
internal tracking: D132052101

**Comment by pahud** [comment]
Hi

According to this:

https://github.com/aws/aws-cdk/blob/465c8ad278dada88abf5839b5314f5e87b988a05/packages/aws-cdk-lib/aws-rds/lib/cluster.ts#L756-L764

And this



https://github.com/aws/aws-cdk/blob/465c8ad278dada88abf5839b5314f5e87b988a05/packages/aws-cdk-lib/aws-rds/lib/cluster.ts#L780

The `writer` should be at the first position of the `instanceIdentifiers` and executes the [bind() that provision the instance](https://github.com/aws/aws-cdk/blob/465c8ad278dada88abf5839b5314f5e87b988a05/packages/aws-cdk-lib/aws-rds/lib/aurora-cluster-instance.ts#L387-L391). But actually there's no dependencies to ensure the first reader would create after the writer.

I think we still need to ensure the dependencies for them.
