### ISSUE TITLE
(pipes-targets): Add Lambda Function target for EventBridge pipes

### ISSUE THREAD

**Issue by WtfJoke** [aws/aws-cdk#30270]
### Describe the feature

Add a implementation for the Lambda Function target for EventBridge pipes in the pipes-targets module.

### Use Case

For feature completeness of the L2 pipes module this source is required.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.136.0

### Environment details (OS name and version, etc.)

windows 11

**Comment by ashishdhingra** [comment]
Per [Amazon EventBridge Pipes targets](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-pipes-event-target.html), [Lambda function (SYNC or ASYNC)](https://docs.aws.amazon.com/eventbridge/latest/userguide/pipes-targets-specifics.html#pipes-targets-specifics-lambda-stepfunctions) is one of the supported target.
