### ISSUE TITLE
rds: cannot adjust security groups of existing RDS

### ISSUE THREAD

**Issue by adam-nielsen** [aws/aws-cdk#30285]
### Describe the bug

If you create an RDS in your stack, you can adjust the security groups (e.g. allowing an EC2 to connect) which is fine.

However if you import an existing RDS into your stack, you can't adjust the security groups, so there appears to be no way to grant anything in a stack access to an existing RDS.

### Expected Behavior

I expected the call to `rds.connections.allowFrom()` to work the same whether the RDS instance was created in the current stack or imported from another stack with `rds.DatabaseCluster.fromDatabaseClusterAttributes()`.

### Current Behavior

If the database already exists outside of the current stack, the `allowFrom()`/`allowTo()` calls produce no errors, but the Cfn output does not contain any mention of the security group changes.

### Reproduction Steps

```
import { Stack, StackProps } from 'aws-cdk-lib';
import { Construct } from 'constructs';

import * as ec2 from 'aws-cdk-lib/aws-ec2';
import * as rds from 'aws-cdk-lib/aws-rds';

export class ExampleStack extends Stack {
  public constructor(scope: Construct, id: string, props: StackProps) {
    super(scope, id, props);

    const vpc = ec2.Vpc.fromLookup(this, 'vpc', {
      vpcId: 'vpc-12345',
    });

    const client = new ec2.Instance(this, 'test', {
      vpc: vpc,
      instanceType: ec2.InstanceType.of(ec2.InstanceClass.BURSTABLE2, ec2.InstanceSize.MICRO),
      machineImage: new ec2.AmazonLinuxImage({ generation: ec2.AmazonLinuxGeneration.AMAZON_LINUX_2 }),
    });

    // If we create a new RDS, then the security groups work fine:
    /*
    const db = new rds.DatabaseCluster(this, 'Database', {
      engine: rds.DatabaseClusterEngine.auroraMysql({ version: rds.AuroraMysqlEngineVersion.VER_3_01_0 }),
      writer: rds.ClusterInstance.provisioned('writer', {
        instanceType: ec2.InstanceType.of(ec2.InstanceClass.R6G, ec2.InstanceSize.XLARGE4),
      }),
      vpc,
    });
    */

    // Produces:
    //    DatabaseSecurityGroupfromteststacktestInstanceSecurityGroup26634811330682648EE3:
    //      Type: AWS::EC2::SecurityGroupIngress
    //      Properties:
    //        Description: EC2 access to RDS
    //        FromPort: 3306
    //        ...

    // But if we get an existing RDS instead, then the security groups do not
    // get mentioned at all in the `cdk synth` output:
    const db = rds.DatabaseCluster.fromDatabaseClusterAttributes(this, 'existing-rds', {
      clusterIdentifier: 'existing-rds', // RDS cluster name
    });

    // Neither of these options work if the RDS already exists outside this stack.
    client.connections.allowTo(db, ec2.Port.MYSQL_AURORA, 'EC2 access to RDS');
    db.connections.allowFrom(client, ec2.Port.MYSQL_AURORA, 'RDS access from EC2');
  }
}
```

If you comment out the lower `const db` and uncomment the upper one, you can switch between importing an RDS and creating a new RDS, to see the difference.

Running this with `cdk synth` is enough to check the Cfn output to see if the security groups are mentioned or not.

### Additional Information/Context

We have a shared RDS used by multiple independent applications, so when we deploy an application we want the resources (EC2/ECS/Lambda/etc.) to be able to access the RDS, without having to use a blanket rule that permits access to the whole VPC.

### CDK CLI Version

2.142.1 (build ed4e152)

### Node.js Version

v18.18.2

### OS

Arch Linux

### Language

TypeScript

### Language Version

TypeScript (5.3.3)

**Comment by pahud** [comment]
It is expected. When you "import" an RDS instance or cluster using `rds.DatabaseCluster.fromDatabaseClusterAttributes`, you literally create a reference object that refers to an existing RDS resource not managed by CDK and it could be something created by CLI or console. CloudFormation would not be able to modify the security groups on any instances not managed by cloudformation and that's why you can't do that with CDK.

With that being said, if you have multiple stacks with one for your AP instances and another for your DB like:

1.   ApplicationStack
2. DatabaseStack

You need to consider:

1. `AP` instances should have a SG with a `Ingress` that allow egress to `DB`.
2. `DB` should have a SG with a `Egress` that allow ingress from `AP`.

Generally, you should avoid using multiple stacks until it's necessary but if you really need to do that. Off the top of my head you probably need to have another stack to create the SGs for AP and DB and your AP stack and DB stack would use the existing SGs for them and just add Ingress//Egress rules from their own stacks. I guess this would be possible if you really need to break them into different stacks.

**Comment by pahud** [comment]
Looking at DatabaseClusterAttributes, it does have an optional  [securityGroups](https://github.com/aws/aws-cdk/blob/168cdacf7f7505471051cef79cffe0d548c1e119/packages/aws-cdk-lib/aws-rds/lib/cluster-ref.ts#L110). I guess it's possible to simplify it. Let me try write a sample for you.

**Comment by adam-nielsen** [comment]
Hi @pahud,

Many thanks for your reply and apologies for the late response!

You example does work, but it requires the two stacks are in the same CDK project.  In our case we have one CDK project for our shared infrastructure, and then six other stacks for each application we deploy to the shared infrastructure.  So we're unable to pass the `IDatabaseCluster` instance between stacks as you have suggested, because the stacks are entirely independent.

If you take your example and put `DatabaseStack` in one CDK project (then deploy with `npx cdk deploy`), and `cd` into the other CDK stack for `InstanceStack` and do another `npx cdk deploy` then you will see the problem.

Any ideas how to get your example to work in this situation?
