### ISSUE TITLE
ecs: Support linuxParameters in FargateTaskDefinition 

### ISSUE THREAD

**Issue by ThePlenkov** [aws/aws-cdk#30294]
### Describe the feature

Hi!

My container requires extended shared memory and I can only set them via container linuxParameters.

It would be nice if FargateTaskDefinition  and ApplicationLoadBalancedFargateService would also support this.

Thanks!

### Use Case

Create a new service with extended shared memory

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.137.0 (build bb90b4c)

### Environment details (OS name and version, etc.)

Ubuntu 23.10

**Comment by pahud** [comment]
[linuxParameters](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-containerdefinition.html#cfn-ecs-taskdefinition-containerdefinition-linuxparameters) is per container definition. While it is only having limited supported with Fargate, I don't see any reason you can't use that in CDK based on the doc:

https://github.com/aws/aws-cdk/tree/168cdacf7f7505471051cef79cffe0d548c1e119/packages/aws-cdk-lib/aws-ecs#linux-parameters

Can you share your code snippets and any error messages?

**Comment by ThePlenkov** [comment]
@pahud you're right, I was using ApplicationLoadBalancedFargateService with taskImageOptions and my whole CDK code was trully minimalistic, but when I changed to taskDefinition + addContainer comibination - there I can use now Linux parameters. This is not an issue indeed

**Comment by ThePlenkov** [comment]
meanwhile here is what I got now:
```
Resource handler returned message: "Invalid request provided: Create TaskDefinition: Fargate compatible task definitions do not support sharedMemorySize (Service: AmazonECS; Status Code: 400; Error Code: ClientException; Request ID: 20a99bbb-f958-4499-8bbb-02d7db3a0939; Proxy: null)" (RequestToken: e029135d-fc74-59de-2d5b-c4cfb6de890e, HandlerErrorCode: InvalidRequest)
```

So actually the problem is not with using linuxParameters - seems like shared memory is not allowed for fargate. 

I'd like to serve the image requiring at least 1000MB in shared memory. How can I do this then? Thank you!

**Comment by pahud** [comment]
In Fargate, you need to specify the required memory in the TaskDefinition. For 1GB of shared memory, you would need to select at least 1024 for the Memory value.

Closing as this is not relevant to CDK. Feel free to create a new issue if it is still relevant.
