### ISSUE TITLE
aws-lambda: AdotLambdaExecWrapper is missing an element for /opt/otel-sqs-handler

### ISSUE THREAD

**Issue by vchik795** [aws/aws-cdk#30310]
### Describe the feature

According to the OpenTelemetry [documentation](https://aws-otel.github.io/docs/getting-started/lambda/lambda-java), the environment variable `AWS_LAMBDA_EXEC_WRAPPER` is supposed to be set to `/opt/otel-sqs-handler` for SQS-triggered Lambda  handlers. However, there is no corresponding element for it in the [AdotLambdaExecWrapper](https://github.com/aws/aws-cdk/blob/dfea72118790ea591d9de720f337c1e14eb11411/packages/aws-cdk-lib/aws-lambda/lib/adot-layers.ts#L170) enum.

### Use Case

When enabling ADOT instrumentation for an SQS-triggered Lambda function, there is no way to set the environment variable `AWS_LAMBDA_EXEC_WRAPPER` to `/opt/otel-sqs-handler`. And using the available `/opt/otel-handler` (`REGULAR_HANDLER`) leads to issues like [this](https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/7517) one.

### Proposed Solution

Add a new element to the `AdotLambdaExecWrapper` enum that would support `/opt/otel-sqs-handler`.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.139

### Environment details (OS name and version, etc.)

N/A

**Comment by khushail** [comment]
Yes, @vchik795 , this enum - https://github.com/aws/aws-cdk/blob/dfea72118790ea591d9de720f337c1e14eb11411/packages/aws-cdk-lib/aws-lambda/lib/adot-layers.ts#L170 needs to have the mentioned element.

PR from the community is welcome !

**Comment by vchik795** [comment]
Thank you for creating the pull request, @mazyu36. Do you think it is going to be merged any time soon?

**Comment by mazyu36** [comment]
@vchik795 
Thank you for your comment. 
The PR is currently awaiting review from the community. While the review process will eventually progress and it will be merged, I'm not sure exactly when the review will take place. 
I kindly ask that you wait for a little while.​​​​​​​​​​​​​​​​
