### ISSUE TITLE
EC2: Security Groups lookup by Owner

### ISSUE THREAD

**Issue by eschirle** [aws/aws-cdk#30331]
### Describe the feature

[SecurityGroup.fromLookupByName()](https://github.com/aws/aws-cdk/blob/823cab30553b1045dab049a0257d21408dbce3f5/packages/aws-cdk-lib/aws-ec2/lib/security-group.ts#L386) provides an option for looking up a security group by name - but this fails if multiple SGs are found with the provided name.  

This feature is for the ability to filter security groups by Owner as well.

### Use Case

I have a use case where I'd like to use a Baseline SecurityGroup for Lambda Functions that are a part of a custom construct to avoid creating a new SG and using up more Hyperplane ENIs.  I can lookup by name "BaselineSecurityGroup", but my VPC is shared across multiple micro accounts, and so multiple SecurityGroups are returned. 

This feature would include the option to filter SecurityGroups by SecurityGroupName and Owner, so that I can grab the SG when there are multiple with the same name in a single VPC.

### Proposed Solution

Either adding an optional owner input to `fromLookupByName` or add a new method `fromLookupByNameAndOwner` in [security-group.ts](https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-ec2/lib/security-group.ts)

`public static fromLookupByName(scope: Construct, id: string, securityGroupName: string, vpc: IVpc, owner?: string)
{
    return this.fromLookupAttributes(scope, id, { securityGroupName, vpc, owner });
}`

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.142.0

### Environment details (OS name and version, etc.)

N/A

**Comment by eschirle** [comment]
I created a PR for this #30334

**Comment by khushail** [comment]
@eschirle , this makes sense to me. Thanks for reporting and volunteering for PR contribution !

**Comment by eschirle** [comment]
> @eschirle , this makes sense to me. Thanks for reporting and volunteering for PR contribution !

Hi @khushail - I made some updates to the PR today and marked it as ready for review.  I was able to run unit tests and integration tests in my development environment but I think it needs some additional changes to pass validation.  
Could you please take a look?

**Comment by khushail** [comment]
@eschirle , thanks for the PR. Usually community PRs ar first reviewed by approved community reviewers and then by Core CDK Team. [Here](https://github.com/aws/aws-cdk/wiki/CDK-Community-PR-Reviews) are the approved guidelines.
