### ISSUE TITLE
SqsQueue & SqsQueueProps not exposed

### ISSUE THREAD

**Issue by jasonstanek** [aws/aws-cdk#3034]
- [x] :beetle: bug report

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*

SqsQueue and SqsQueueProps not exposed in java cdk for use, but are in the documentation.  Produced importing maven cdk (at least in 0.34.0 or 0.35.0) packages.

* **What is the expected behavior (or behavior of feature suggested)?**

Expecting that SqsQueue and SqsQueueProps are exposed for use as an IRuleTarget.  

* **What is the motivation / use case for changing the behavior or adding this feature?**

Example consequence: Unavailability prevents linking cloudtrail events of imported artifacts (e.g. IBucket) to an SQS queue with cdk.

* **Please tell us about your environment:**
  
  - CDK CLI Version: 0.35.0
  - Language: [ Java ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

**Comment by rix0rrr** [comment]
Could you please supply some example code, because I'm afraid I don't understand the report.

**Comment by jasonstanek** [comment]
When creating a new S3 Bucket, one can relay events that occur on the new Bucket to SQS with the following function:

    private Pair<IBucket,Queue> buildS3ToSQSPipe(Bucket data_bucket, String data_prefix, String data_suffix, String queue_name) {
		Queue event_queue = addSQS(queue_name);
		ServicePrincipal s3_principal = new ServicePrincipal("s3.amazonaws.com");
		ServicePrincipal cloudwatch_principal = new ServicePrincipal("events.amazonaws.com");
		event_queue.grantSendMessages((IPrincipal)s3_principal);
		event_queue.grantSendMessages((IPrincipal)cloudwatch_principal);

        NotificationKeyFilter filter = NotificationKeyFilter.builder().withPrefix(data_prefix).withSuffix(data_suffix).build();
		data_bucket.addObjectCreatedNotification(new SqsDestination(event_queue),filter);

        return new Pair<IBucket,Queue>(data_bucket,event_queue);
    }

However, while it appears that there is similar (unfortunately not the same) functionality in the documentation for imported buckets, the functionality is not exposed for the programmer.  An imported S3 bucket (IBucket) appears to require an IRuleTarget to relay an event from the bucket to SQS.

Specifically, Bucket.fromBucketName(...) returns type IBucket, which does not have the addObjectCreatedNotification function available to it (like Bucket does).  Instead it appears there is a IBucket.onCloudTrailPutObject(...) function.  The OnCloudTrailBucketEventOptions structure that is required by IBucket.onCloudTrailPutObject requires specification of the target (to where the event is to be sent) of type IRuleTarget.  The documentation at [https://docs.aws.amazon.com/cdk/api/latest/java/software/amazon/awscdk/services/events/targets/SqsQueue.html] appears to indicate the existence of SqsQueue which derives from IRuleTarget.  However the SqsQueue class does not import.  The statement "import software.amazon.awscdk.services.events.targets.SqsQueue" fails to find "targets" despite the associated maven dependency:

        <dependency>
            <groupId>software.amazon.awscdk</groupId>
            <artifactId>events</artifactId>
            <version>${cdk.version}</version>
        </dependency>

SqsQueueProps being in the same "targets" branch also appears unavailable.  As a consequence, any function that requires an IRuleTarget cannot supply an SqsQueue instance as a target for relaying an event.  So, while it is possible to relay an event from a new construct (e.g. Bucket) to SQS, it appears currently impossible via the Java CDK (at least 0.34.0-0.36.1) to relay an event from an existing construct (e.g. IBucket) to SQS.  

	private Pair<IBucket,Queue> buildS3ToSQSPipe(IBucket data_bucket, String data_prefix, String data_suffix, String queue_name) {
		Queue event_queue = addSQS(queue_name);
		ServicePrincipal s3_principal = new ServicePrincipal("s3.amazonaws.com");
		ServicePrincipal cloudwatch_principal = new ServicePrincipal("events.amazonaws.com");
		event_queue.grantSendMessages((IPrincipal)s3_principal);
		event_queue.grantSendMessages((IPrincipal)cloudwatch_principal);


        List<String> accounts = new ArrayList<>();
        accounts.add("0123456789");

        List<String> regions = new ArrayList<>();
        regions.add("us-east-1");

        List<String> source = new ArrayList<>();
        source.add("aws.s3");

        List<String> detail_type = new ArrayList<>();
        detail_type.add("AWS API Call via CloudTrail");

        JsonNodeFactory json_node_factory = new JsonNodeFactory(false);
        Map<String,Object> detail = new HashMap<>();
        Map<String,Object> request_parameters = new HashMap<>();
        List<String> event_source = new ArrayList<>();
		List<String> event_name = new ArrayList<>();
		List<String> bucket_name = new ArrayList<>();
        request_parameters.put("bucketName",bucket_name);
        detail.put("requestParameters",request_parameters);
        detail.put("eventSource",event_source);
        detail.put("eventName",event_name);
        event_source.add("s3.amazonaws.com");
        event_name.add("PutObject");
        bucket_name.add(data_bucket.getBucketName());

        EventPattern event_pattern = EventPattern.builder()
                .withAccount(accounts)
                .withRegion(regions)
                .withSource(source)
                .withDetailType(detail_type)
                .withDetail(detail)
                .build();

        List<String> paths = new ArrayList<>();
        paths.add(data_prefix + "*" + data_suffix);

		SqsQueueProps queue_properties = new SqsQueueProps.builder().withMessageGroupId("mymessagegroupid").build(); //class SqsQueueProps not found
		SqsQueue target = new SqsQueue(event_queue,queue_properties); //class SqsQueue not found

        String rule_name = data_bucket.getBucketName() + "2" + queue_name;
        OnCloudTrailBucketEventOptions bucket_options = OnCloudTrailBucketEventOptions.builder()
                .withRuleName(rule_name)
                .withDescription(rule_name)
                .withPaths(paths)
                .withEventPattern(event_pattern)
                .withTarget(target)
                .build();
        data_bucket.onCloudTrailPutObject(rule_name, bucket_options);

		return new Pair<IBucket,Queue>(data_bucket,event_queue);
	}

**Comment by jasonstanek** [comment]
Any takers?

**Comment by RomainMuller** [comment]
The event targets would be in [`software.amazon.awscdk:events-targets`](https://search.maven.org/artifact/software.amazon.awscdk/events-targets/1.15.0.DEVPREVIEW/jar), not directly in `software.amazon.awscdk:events`.

**Comment by jasonstanek** [comment]
The package you suggest using does not appear to be available to us.  See image below.

[cid:image001.png@01D593C2.E489C3F0]
