### ISSUE TITLE
(aws-apprunner): support a customer managed key

### ISSUE THREAD

**Issue by mazyu36** [aws/aws-cdk#30365]
### Describe the feature

Support a customer managed key to encrypt all stored copies of your application source image or source bundle.
At the moment,  L2 Construct (alpha module) cannot use a customer managed key.

### Use Case

In App Runner, the source code and images that are copied are typically encrypted using AWS-managed keys. 
However, there may be cases where you want to use a customer-managed key for encryption to enhance security or meet auditing requirements.

For this purpose, App Runner supports encryption using customer-managed keys.

### Proposed Solution

Add a property to use a KMS key

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.143.0

### Environment details (OS name and version, etc.)

all

**Comment by khushail** [comment]
Thanks  @mazyu36 for submitting the PR !
