### ISSUE TITLE
Update AWSCustomResource runtime version from node.js14 to node.js16

### ISSUE THREAD

**Issue by jacido** [aws/aws-cdk#30373]
### Describe the feature

Update Runtime version of AWSCustomResource from node.js14 to node.js16 or recommended runtime. 
Currently using certain constructs and properties are resulting in deploying with a deprecated runtime. 

### Use Case

When deploying a solution using AWSCustomResource, it results in using an old deprecated runtime version. 

cdk.out/ tree.json code snippet:
-----------------------------------

"Resource": {
                "id": "Resource",
                "path": "Cognito-lane36/AWSXXXXXXXXXXXXXXXXXXX7982bd2287/Resource",
                "attributes": {
                  "aws:cdk:cloudformation:type": "AWS::Lambda::Function",
                  "aws:cdk:cloudformation:props": {
                    "code": {
                      "s3Bucket": "cdk-hnb659fds-assets-XXXXXXXX7970-us-west-2",
                      "s3Key": "XXXXXXXXXXXXXXXXXXXXXXXXX226d161a5cfe96f4648b21f9e4912c698bf30.zip"
                    },
                    "role": {
                      "Fn::GetAtt": [
                        "AWSXXXXXXXXXXXXXXXXXXX7982bd2287ServiceRoleC1XXXFF2",
                        "Arn"
                      ]
                    },
                    "functionName": "MyCustomLmbdFn",
                    "handler": "index.handler",
                    "runtime": "nodejs14.x",
                    "tags": [
                      {
                        "key": "AppManagerCFNStackKey",
                        "value": "Cognito-lane36"
                      }
                    ],
                    "timeout": 120
                  }
                },
                "constructInfo": {
                  "fqn": "aws-cdk-lib.aws_lambda.CfnFunction",
                  "version": "2.72.1"
                }
              }

-----------------------------------

### Proposed Solution

Update to latest runtime. 

### Other Information

Current workaround regarding the issue is using property override escape hatch. 

-------------------------------------
test = self.node.find_child("AWSXXXXXXXXXXXXXXXXXXX7982bd2287").node.default_child
        test.add_property_override("Runtime", "nodejs20.x")
-------------------------------------

[Link] - add_property_override
https://constructs.dev/packages/aws-cdk-lib/v/2.135.0/api/CfnHoursOfOperation?lang=python&submodule=aws_connect#addPropertyOverride

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.142.1

### Environment details (OS name and version, etc.)

Python

**Comment by khushail** [comment]
Hey @jacido , could you please share the repro code for which particular construct, this runtime is being generated.

**Comment by jacido** [comment]
def setup_environment_variables(self, lane_name:str, function_name:str, function_arn: str, user_pool_id: str, client_id: str ):
   
    custom_resource = _awsCustomResource(
        scope=self,
        id='AWSCustomResource_'+function_name,  
        install_latest_aws_sdk=True,  
        function_name="MyCustomLmbdFn",       
        on_create=_awsSdkCall(
            service='Lambda',                
            action='updateFunctionConfiguration',
            parameters={
                "FunctionName" : function_arn,
                "Environment": {
                    "Variables" : {
                        'DB_USERNAME' : _ssm.StringParameter.value_from_lookup(self, "/cognito/{0}/db_user_name".format(lane_name)),
                        'DB_PASSWORD' : _ssm.StringParameter.value_from_lookup(self, "/cognito/{0}/db_password".format(lane_name)),
                        'DB_CONNECTION_STRING' : _ssm.StringParameter.value_from_lookup(self, "/cognito/{0}/db_connection_string".format(lane_name)),
                        'HOSTALIASES' : self.node.try_get_context('environments')[lane_name]['host_aliases'],
                        'REGION' : self.node.try_get_context('environments')[lane_name]['aws_region'],
                        "CLIENTID" : client_id,
                        "USERPOOLID" : user_pool_id
                    }
                }
            },
            physical_resource_id=_physicalResourceId.of('LambdaEnvUpdate_'+function_name)
        ),
        policy=_awsCustomResourcePolicy.from_sdk_calls( resources=_awsCustomResourcePolicy.ANY_RESOURCE)
    )

**Comment by scanlonp** [comment]
Hey @jacido, I believe we have updated our `AwsCustomResource` construct to use NodeJS 18. In your initial code snippet, I see that in construct info, the version is 2.72.1. 

Make sure that both your `aws-cdk-lib` and `aws-cdk` versions are updated.

**Comment by ashishdhingra** [comment]
@jacido Please review last comment https://github.com/aws/aws-cdk/issues/30373#issuecomment-2138335726 and share your findings.
