### ISSUE TITLE
rds:  Upgrade(2.142.0 -> 2.143.0) added an explicit dependency between some of our DB constructs.

### ISSUE THREAD

**Issue by mamta925** [aws/aws-cdk#30383]
### Describe the bug

In CDK upgrade
| Package | Type | Update | Change |
|---|---|---|---|
| [aws-cdk](https://github.com/aws/aws-cdk) ([source](https://github.com/aws/aws-cdk/tree/HEAD/packages/aws-cdk)) | devDependencies | minor | [`2.142.0` -> `2.143.0`](https://renovatebot.com/diffs/npm/aws-cdk/2.142.0/2.143.0) |
| [aws-cdk-lib](https://github.com/aws/aws-cdk) ([source](https://github.com/aws/aws-cdk/tree/HEAD/packages/aws-cdk-lib)) | dependencies | minor | [`2.142.0` -> `2.143.0`](https://renovatebot.com/diffs/npm/aws-cdk-lib/2.142.0/2.143.0) |

---

This upgrade added an explicit dependency between some of our DB constructs.

`"DbDbClusterreaderB277327D": {
      "DeletionPolicy": "Delete",
      "DependsOn": [
        "DbDbClusterwriterCE53952E",
      ],
      "Properties": {
        "DBClusterIdentifier": {
          "Ref": "DbDbCluster8FBC7FAD",`
          
Now, cloudformation wants to delete and recreate the database in order to apply that change, which is obviously not convenient.

So… any ideas how we can deploy this change without deleting the DB and having to re-load the data?

### Expected Behavior

It should not delete DB

### Current Behavior

Stack update is failing because of DB recreation

### Reproduction Steps

    const dbCluster = new rds.DatabaseCluster(this, "DbCluster", {
      serverlessV2MinCapacity: 1,
      serverlessV2MaxCapacity: 10,
      writer: rds.ClusterInstance.serverlessV2("writer"),
      readers: [rds.ClusterInstance.serverlessV2("reader")],
      storageEncryptionKey: dbStorageEncryptionKmsKey,
      removalPolicy: RemovalPolicy.DESTROY,
      copyTagsToSnapshot: true,
      clusterIdentifier: dbName,
      securityGroups: [dbSecurityGroup],
      credentials: dbClusterCredentials,
      vpc,
      vpcSubnets: privateSubnets,
      defaultDatabaseName: dbDatabaseName,
      engine: rds.DatabaseClusterEngine.auroraMysql({
        version: rds.AuroraMysqlEngineVersion.VER_3_05_2,
      }),
    });
    
  Our old DB constuct , now updating
  
  cdk versions 
    
    

### Possible Solution

not sure if this is causing issue : https://github.com/aws/aws-cdk/issues/30260

### CDK CLI Version

aws-cdk (source) devDependencies minor 2.142.0 -> 2.143.0

### Node.js Version

20

### OS

Linux

### Language

TypeScript

**Comment by colifran** [comment]
I think this [PR](https://github.com/aws/aws-cdk/pull/30277) is where the explicit dependency was added. @pahud any thoughts on this?

**Comment by pahud** [comment]
Yes that PR ensures the writer would always be created before the reader.

Hi @mamta925 

Did you mean you created this in `2.142.0` and now you just tried to upgrade to `2.143.0` and CDK is trying to replace your nodes?

```ts
const dbCluster = new rds.DatabaseCluster(this, "DbCluster", {
  serverlessV2MinCapacity: 1,
  serverlessV2MaxCapacity: 10,
  writer: rds.ClusterInstance.serverlessV2("writer"),
  readers: [rds.ClusterInstance.serverlessV2("reader")],
  storageEncryptionKey: dbStorageEncryptionKmsKey,
  removalPolicy: RemovalPolicy.DESTROY,
  copyTagsToSnapshot: true,
  clusterIdentifier: dbName,
  securityGroups: [dbSecurityGroup],
  credentials: dbClusterCredentials,
  vpc,
  vpcSubnets: privateSubnets,
  defaultDatabaseName: dbDatabaseName,
  engine: rds.DatabaseClusterEngine.auroraMysql({
    version: rds.AuroraMysqlEngineVersion.VER_3_05_2,
  }),
});
```

**Comment by pahud** [comment]
trying to reproduce this in my account

**Comment by pahud** [comment]
Hi @mamta925 

I created the cluster with 2.142.0 as below:

```ts
export class DummyStack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);

    const vpc = ec2.Vpc.fromLookup(this, 'Vpc', { isDefault: true });

    const dbCluster = new rds.DatabaseCluster(this, "DbCluster", {
      serverlessV2MinCapacity: 1,
      serverlessV2MaxCapacity: 10,
      writer: rds.ClusterInstance.serverlessV2("writer"),
      readers: [rds.ClusterInstance.serverlessV2("reader")],
      // storageEncryptionKey: dbStorageEncryptionKmsKey,
      removalPolicy: RemovalPolicy.DESTROY,
      copyTagsToSnapshot: true,
      // clusterIdentifier: dbName,
      // securityGroups: [dbSecurityGroup],
      // credentials: dbClusterCredentials,
      vpc,
      // vpcSubnets: privateSubnets,
      // defaultDatabaseName: dbDatabaseName,
      engine: rds.DatabaseClusterEngine.auroraMysql({
        version: rds.AuroraMysqlEngineVersion.VER_3_05_2,
      }),
    });

  }
}
```

Then I upgraded to 2.143.0. The `cdk diff` indicates the reader node is going to have a `DependOn` on the writer with in-place update and it took 10 seconds on the deployment. No node is being replaced. 

<img width="709" alt="image" src="https://github.com/aws/aws-cdk/assets/278432/7878b85b-0694-4dfe-a185-7add426a84d2">

>Now, cloudformation wants to delete and recreate the database in order to apply that change, which is obviously not convenient.


What made you think CFN was trying to delete and recreate the instance?

**Comment by mamta925** [comment]
Hey.., yes this part only, 
As soon as  I added below code(removed dependecy ) then every thing worked
```
   const  cfnDbReader = dbCluster.node.findChild("reader").node.defaultChild as CfnResource;
    cfnDbReader.addOverride("DependsOn", undefined);
```
![Screenshot 2024-06-05 at 8 10 29 AM](https://github.com/aws/aws-cdk/assets/20533514/204b293d-1563-4e32-9ee4-69ea2e7c238e)

**Comment by pahud** [comment]
Hi @mamta925 

Can you elaborate on what made you think CFN was trying to delete and recreate the instance? Adding dependency should not cause the node replacement.
