### ISSUE TITLE
codedeploy: zonal configuration for the EC2/on-premises deploy configuration

### ISSUE THREAD

**Issue by badmintoncryer** [aws/aws-cdk#30430]
### Describe the feature

Configure [zonal configuration](https://docs.aws.amazon.com/codedeploy/latest/userguide/deployment-configurations-create.html#zonal-config) for the EC2/on-premises deploy configuration.

### Use Case

`ServerDeploymentConfig` class does not support for configuring zonal configuration.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.141.0

### Environment details (OS name and version, etc.)

irrelevant

**Comment by khushail** [comment]
thanks @badmintoncryer for submitting the PR.
