### ISSUE TITLE
aws_rds: VER_13_13 not available but documentation says otherwise

### ISSUE THREAD

**Issue by bayoishola** [aws/aws-cdk#30445]
### Describe the bug

Hi,

In the documentation, it says that [Postgres Engine version 13.13 should be available](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_rds/PostgresEngineVersion.html#aws_cdk.aws_rds.PostgresEngineVersion.VER_13_13) but this isn't the case in the cdk library.

### Expected Behavior

`DatabaseInstanceEngine.postgres(version=PostgresEngineVersion.VER_13_13)`

### Current Behavior

`DatabaseInstanceEngine.postgres(version=PostgresEngineVersion.VER_13_12)`
13.12 is the max minor version for Postgres Engine 13 in the library.

### Reproduction Steps

```python
from aws_cdk.aws_rds import DatabaseInstanceEngine, PostgresEngineVersion

DatabaseInstanceEngine.postgres(version=PostgresEngineVersion.VER_13_13)
```

### Possible Solution

```python
@jsii.python.classproperty
    @jsii.member(jsii_name="VER_13_13")
    def VER_13_13(cls) -> "PostgresEngineVersion":
        '''Version "13.13".'''
        return typing.cast("PostgresEngineVersion", jsii.sget(cls, "VER_13_13"))
```
...

### Additional Information/Context

AWS recommends upgrading your Amazon RDS for PostgreSQL databases running minor versions to 13.13.

### CDK CLI Version

2.143.0 (build 9f2bdf7)

### Node.js Version

v20.11.1

### OS

Windows

### Language

Python

### Language Version

3.9.16

**Comment by pahud** [comment]
% aws rds describe-db-engine-versions --engine postgres --query "DBEngineVersions[].EngineVersion"

[
    "11.22",
    "11.22-rds.20240418",
    "12.15",
    "12.16",
    "12.17",
    "12.18",
    "12.19",
    "13.11",
    "13.12",
    "13.13",
    "13.14",
    "13.15",
    "14.9",
    "14.10",
    "14.11",
    "14.12",
    "15.4",
    "15.5",
    "15.6",
    "15.7",
    "16.1",
    "16.2",
    "16.3"
]

**Comment by pahud** [comment]
It should be available

https://github.com/aws/aws-cdk/blob/f9371001f4cb3a921d66992072972d9687e3698e/packages/aws-cdk-lib/aws-rds/lib/instance-engine.ts#L1481

Can you make sure you use the latest AWS CDK and try again?

**Comment by richardgroves** [comment]
VER_15_6 is also listed in the documentation referenced and not actually available in 2.145 (also using Python) - but I do see VER_13_13 listed (and VER_13_14).

**Comment by bayoishola** [comment]
@richardgroves , do you mean that `VER_13_13` is available in `2.145`?

**Comment by richardgroves** [comment]
@bayoishola Yes - I see all of 13.3 through 13.14 enumerated in the Python library for 2.145. For 15 it is just 15.2-15.5, but the code for 15.6 was committed 3 days ago, so maybe released in the next version - shame that 15.7 is already available on console...

```
from aws_cdk import (
    aws_rds as rds
)
print("DB versions:\n" + "\n".join(rds.AuroraPostgresEngineVersion.__dict__.keys()))
```
 for a hacky dump of the versions available.

**Comment by bayoishola** [comment]
Thanks for confirming and for the tips as well. @richardgroves

**Comment by richardgroves** [comment]
Another tip - from CLI you can do this:

`aws rds describe-db-engine-versions --engine aurora-postgresql | grep DBEngineVersionDescription` to get a list of the versions available.

From my current CLI version of "aws-cli/2.16.4 Python/3.11.9 Darwin/23.5.0 source/x86_64" I get:

         "DBEngineVersionDescription": "Aurora PostgreSQL (Compatible with PostgreSQL 11.9)",
            "DBEngineVersionDescription": "Aurora PostgreSQL (Compatible with PostgreSQL 11.21)",
            "DBEngineVersionDescription": "Aurora PostgreSQL (Compatible with PostgreSQL 12.9)",
            "DBEngineVersionDescription": "Aurora PostgreSQL (Compatible with PostgreSQL 12.11)",
            "DBEngineVersionDescription": "Aurora PostgreSQL (Compatible with PostgreSQL 12.12)",
            "DBEngineVersionDescription": "Aurora PostgreSQL (Compatible with PostgreSQL 12.13)",
            "DBEngineVersionDescription": "Aurora PostgreSQL (Compatible with PostgreSQL 12.14)",
            "DBEngineVersionDescription": "Aurora PostgreSQL (Compatible with PostgreSQL 12.15)",
            "DBEngineVersionDescription": "Aurora PostgreSQL (Compatible with PostgreSQL 12.16)",
            "DBEngineVersionDescription": "Aurora PostgreSQL (Compatible with PostgreSQL 12.17)",
            "DBEngineVersionDescription": "Aurora PostgreSQL (Compatible with PostgreSQL 12.18)",
            "DBEngineVersionDescription": "Aurora PostgreSQL (Compatible with PostgreSQL 13.7)",
            "DBEngineVersionDescription": "Aurora PostgreSQL (Compatible with PostgreSQL 13.8)",
            "DBEngineVersionDescription": "Aurora PostgreSQL (Compatible with PostgreSQL 13.9)",
            "DBEngineVersionDescription": "Aurora PostgreSQL (Compatible with PostgreSQL 13.10)",
            "DBEngineVersionDescription": "Aurora PostgreSQL (Compatible with PostgreSQL 13.11)",
            "DBEngineVersionDescription": "Aurora PostgreSQL (Compatible with PostgreSQL 13.12)",
            "DBEngineVersionDescription": "Aurora PostgreSQL (compatible with PostgreSQL 13.12)",
            "DBEngineVersionDescription": "Aurora PostgreSQL (Compatible with PostgreSQL 13.13)",
            "DBEngineVersionDescription": "Aurora PostgreSQL (Compatible with PostgreSQL 13.14)",
            "DBEngineVersionDescription": "Aurora PostgreSQL (Compatible with PostgreSQL 14.3)",
            "DBEngineVersionDescription": "Aurora PostgreSQL (Compatible with PostgreSQL 14.4)",
            "DBEngineVersionDescription": "Aurora PostgreSQL (Compatible with PostgreSQL 14.5)",
            "DBEngineVersionDescription": "Aurora PostgreSQL (Compatible with PostgreSQL 14.6)",
            "DBEngineVersionDescription": "Aurora PostgreSQL (Compatible with PostgreSQL 14.7)",
            "DBEngineVersionDescription": "Aurora PostgreSQL (Compatible with PostgreSQL 14.8)",
            "DBEngineVersionDescription": "Aurora PostgreSQL (Compatible with PostgreSQL 14.9)",
            "DBEngineVersionDescription": "Aurora PostgreSQL (Compatible with PostgreSQL 14.10)",
            "DBEngineVersionDescription": "Aurora PostgreSQL (Compatible with PostgreSQL 14.11)",
            "DBEngineVersionDescription": "Aurora PostgreSQL (Compatible with PostgreSQL 15.2)",
            "DBEngineVersionDescription": "Aurora PostgreSQL (Compatible with PostgreSQL 15.3)",
            "DBEngineVersionDescription": "Aurora PostgreSQL (Compatible with PostgreSQL 15.4)",
            "DBEngineVersionDescription": "Aurora PostgreSQL (Compatible with PostgreSQL 15.5)",
            "DBEngineVersionDescription": "Aurora PostgreSQL (Compatible with PostgreSQL 15.6)",
            "DBEngineVersionDescription": "Aurora PostgreSQL (Compatible with PostgreSQL 16.1)",
            "DBEngineVersionDescription": "Aurora PostgreSQL (Compatible with PostgreSQL 16.2)",


So that isn't showing 15.7 and 16.3 which were announced as available on 9th May 2024 - https://aws.amazon.com/about-aws/whats-new/2024/05/amazon-rds-postgresql-supports-new-versions/

There appears to be a lot of lag in the support of new versions across the toolchains.

**Comment by bayoishola** [comment]
@richardgroves , just getting back to this and I noticed you were looking at aurora postgres as opposed to rds postgres. Up until aws-cdk-lib version 2.149.0 (current latest release), I still don't see engine version `13_13`.

```bash
aws rds describe-db-engine-versions --engine postgres | grep DBEngineVersionDescription
```

@pahud , any update, please?

**Comment by bayoishola** [comment]
@pahud , thanks for responding. What version of the python AWS CDK do you have installed for the above? Thanks!

**Comment by pahud** [comment]
@bayoishola 

```
% cdk --version
2.149.0 (build c8e5924)
% grep aws-cdk-lib requirements.txt
aws-cdk-lib==2.149.0
```

Make sure you have activated the `venv` and `pip install` the requirements.txt

```
$ source .venv/bin/activate
$ pip install -r requirements.txt
```
