### ISSUE TITLE
feat(aws-eks): add support for EKS version 1.30

### ISSUE THREAD

**Issue by cristianmagana** [aws/aws-cdk#30443]
### Describe the feature

Amazon EKS announced support for Kubernetes version 1.30

https://aws.amazon.com/about-aws/whats-new/2024/05/amazon-eks-distro-kubernetes-version-1-30/

CDK support for aws_eks.KubernetesVersion would be needed to mark this feature as complete

Kubectl lambda layer is waiting approval to support v1.30

### Use Case

EKS Blueprints deployed from cdk need to be manually upgraded to v1.30

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.144.0

### Environment details (OS name and version, etc.)

EKS

**Comment by pahud** [comment]
depends on https://github.com/cdklabs/awscdk-asset-kubectl/issues/838
