### ISSUE TITLE
aws-eks: aws-auth creation failure takes 1 hour

### ISSUE THREAD

**Issue by taku-hatano** [aws/aws-cdk#30452]
### Describe the bug

In creation cluster stack, aws-auth creation step was failed and it took 1 hour for fail parent stack.
Error message is below,
```
CloudFormation did not receive a response from your Custom Resource. Please check your logs for requestId [ca31f6eb-af1b-412e-8a06-f312c8affcc7]. If you are using the Python cfn-response module, you may need to update your Lambda function code so that CloudFormation can attach the updated version.
```

(There is no error in Lambda handler log, so I think the aws-auth creation was successful.)

### Expected Behavior

If aws-auth creation fails, the parent Stack will also fail immediately.

### Current Behavior

If aws-auth creation fails, the parent Stack fail after 1 hour.

### Reproduction Steps

I use https://aws-quickstart.github.io/cdk-eks-blueprints/

```typescript
const cluster = new blueprints.GenericClusterProvider({
  fargateProfiles: {
	  "fp-default": {
		  selectors: [{ namespace: "default", labels: { worker: "fargate" } }],
	  },
  },
});
blueprints.EksBlueprint.builder()
  .clusterProvider(cluster)
  .resourceProvider(
    blueprints.GlobalResources.Vpc,
    new blueprints.DirectVpcProvider(args.vpc),
  )
  .build(app, stackName, props)
```

### Possible Solution

I read deployed Lambda handler code, but I cannot find cfn response.
ref. [here](https://github.com/aws/aws-cdk/blob/f9371001f4cb3a921d66992072972d9687e3698e/packages/%40aws-cdk/custom-resource-handlers/lib/aws-eks/kubectl-handler/index.py)

Where is cfn response for Python custom resource handlers?

### CDK CLI Version

2.137.0 (build bb90b4c)

### Node.js Version

v20.14.0

### OS

AmazonLinux 2023.3.20240312

### Language

TypeScript

### Language Version

5.4.3

**Comment by pahud** [comment]
cdk-blue-prints is not maintained by AWS CDK team. Please report your issue to https://github.com/aws-quickstart/cdk-eks-blueprints/issues
