### ISSUE TITLE
CodeBuild: new Fleet properties

### ISSUE THREAD

**Issue by nmussy** [aws/aws-cdk#30458]
### Describe the feature

After I initially implemented the Fleet L2 construct in #29754, CloudFormation added support for the following three properties, which should be added to the L2:

* [`OverflowBehavior`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codebuild-fleet.html#cfn-codebuild-fleet-overflowbehavior)
* [`ScalingConfiguration`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codebuild-fleet.html#cfn-codebuild-fleet-scalingconfiguration)
* [`FleetVpcConfig`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codebuild-fleet.html#cfn-codebuild-fleet-fleetvpcconfig)

### Use Case

Match L2 coverage with newly added Cfn properties

### Other Information

_Originally reported by @rgoltz in https://github.com/aws/aws-cdk/issues/29617#issuecomment-2130225676_

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.144.0

### Environment details (OS name and version, etc.)

N/A

**Comment by pahud** [comment]
Thank you!

**Comment by nmussy** [comment]
Updated the issue to also include the recently(ish) added ScalingConfiguration from about a month ago, see https://github.com/aws/aws-cdk/pull/32175#issue-2668621769.

I'll open a PR for all three props some time this week
