### ISSUE TITLE
EKS: Kubectl Lambda Function Doesn't Support Regional STS Endpoints

### ISSUE THREAD

**Issue by hakenmt** [aws/aws-cdk#30496]
### Describe the bug

When deploying a private EKS cluster using an STS VPC endpoint, the Kubetctl function access to STS fails because it attempts to use the global endpoint. This is either from using a V1 SDK, the endpoint is explicitly set, or the environment variable is set

### Expected Behavior

All SDKs and functions not under user control should default to using regional STS endpoints.

### Current Behavior

The function uses the global endpoint.

### Reproduction Steps

Deploy a private EKS cluster with an STS VPC endpoint.

### Possible Solution

Set the environment variable in the Lambda function definition. This is my current workaround:

```csharp
        FixUpLambdaFunctions("@aws-cdk--aws-eks.KubectlProvider");

        private void FixUpLambdaFunctions(string name)
        {
            IConstruct resourceProviderNestedStack = this.Node.TryFindChild(name);

            if (resourceProviderNestedStack != null)
            {
                NestedStack nestedStack = resourceProviderNestedStack as NestedStack;

                if (nestedStack != null)
                {
                    Function lambda = nestedStack.Node.TryFindChild("Handler") as Function;

                    if (lambda != null)
                    {
                        lambda.AddEnvironment("AWS_STS_REGIONAL_ENDPOINTS", "regional");
                    }

                    IConstruct provider = nestedStack.Node.TryFindChild("Provider");
                    Function onEvent = provider.Node.TryFindChild("framework-onEvent") as Function;

                    if (onEvent != null)
                    {
                        onEvent.AddEnvironment("AWS_STS_REGIONAL_ENDPOINTS", "regional");
                    }
                }
            }
        }

```

### CDK CLI Version

2.138.0

### Node.js Version

v20.9.0

### OS

darwin

### Language

.NET

**Comment by hakenmt** [comment]
1/Deploying in us-east-1. 
2/Yes, the function provided in the construct is using python3.10 as the runtime. 

My understanding is that all new MAJOR versions should be defaulting to using regional endpoints per the documentation, but I'm not sure how that's interpreted for boto3 since it's still v1.x.x.

**Comment by pahud** [comment]
Have discussed with @tim-finnigan about https://github.com/boto/botocore/issues/2577#issuecomment-992924764

Setting it to `regional` would still be required and recommended. I guess we should figure out how to do that from custom resource framework.

**Comment by pahud** [comment]
OK we do have this in cluster resource provider

https://github.com/aws/aws-cdk/blob/b196b13b0b8a54dcacadf87fdbe744772a6e6c4d/packages/aws-cdk-lib/aws-eks/lib/cluster-resource-provider.ts#L69-L71

But not added here
https://github.com/aws/aws-cdk/blob/b196b13b0b8a54dcacadf87fdbe744772a6e6c4d/packages/aws-cdk-lib/aws-eks/lib/kubectl-provider.ts#L139C28-L139C46

I'll submit a PR for that.
