### ISSUE TITLE
(aws-lambda): Switching scaling option doesn't update the Provisioned Concurrency

### ISSUE THREAD

**Issue by garysassano** [aws/aws-cdk#30503]
### Describe the bug

Starting point:

```ts
const scalableFunction = new NodejsFunction(this, "ScalableFunction", {
  functionName: "scalable-function",
  entry: join(__dirname, "..", "functions", "scalable", "index.ts"),
  runtime: Runtime.NODEJS_20_X,
  architecture: Architecture.ARM_64,
  memorySize: 1024,
  timeout: Duration.minutes(5),
  loggingFormat: LoggingFormat.JSON,
});

const scalableFunctionAlias = new Alias(this, "ScalableFunctionAlias", {
  aliasName: "live",
  version: scalableFunction.currentVersion,
});

scalableFunctionAlias
  .addAutoScaling({
    minCapacity: 1,
    maxCapacity: 10,
  })
  .scaleOnSchedule("ScaleUpInMorning", {
    schedule: Schedule.cron({ hour: "3", minute: "30" }),
    minCapacity: 5,
  });
```

I deploy the code, wait for the scheduled time and check that the Provisioned Concurrency correctly changed from 1 to 5 in Lambda AWS Console.

Then I update the code as follows:

```ts
scalableFunctionAlias
  .addAutoScaling({
    minCapacity: 1,
    maxCapacity: 10,
  })
  .scaleOnUtilization({
    utilizationTarget: 0.7,
  });
```

I deploy it and go check again in Lambda AWS Console:

![image](https://github.com/aws/aws-cdk/assets/10464497/8d2a8b19-f2e0-4e69-abde-e0290a80475b)

The Provisioned Concurrency is still 5, it didn't get updated to the default `minCapacity`.

### Expected Behavior

see above

### Current Behavior

see above

### Reproduction Steps

see above

### CDK CLI Version

2.145.0

### Node.js Version

20.13.1

### OS

Ubuntu 22.04.3 LTS

### Language

TypeScript

**Comment by pahud** [comment]
I think it makes sense here.

[minCapacity](https://github.com/aws/aws-cdk/blob/f1dc1429c8d2253fb8b0f7570443d0881921d6d4/packages/aws-cdk-lib/aws-applicationautoscaling/lib/base-scalable-attribute.ts#L93) is the minimal capacity to scale to. It doesn't mean it has to scale to that value on stack update.

Per CFN doc[[1](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-applicationautoscaling-scalabletarget.html#cfn-applicationautoscaling-scalabletarget-mincapacity)]:

>The minimum value that you plan to scale in to. When a scaling policy is in effect, Application Auto Scaling can scale in (contract) as needed to the minimum capacity limit in response to changing demand.
