### ISSUE TITLE
aws_rds: DatabaseInstance `credentials` doesn't accept `dict` in Python

### ISSUE THREAD

**Issue by andrewvaughan** [aws/aws-cdk#30514]
### Describe the bug

Per the Python documentation:

https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_rds/DatabaseInstance.html

> credentials (Optional[[Credentials](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_rds/Credentials.html#aws_cdk.aws_rds.Credentials)]) – Credentials for the administrative user. Default: - A username of ‘admin’ (or ‘postgres’ for PostgreSQL) and SecretsManager-generated password

However, the example immediately preceding shows a dictionary being used to involve template secrets:

```py
# Templated secret with username and password fields
templated_secret = secretsmanager.Secret(self, "TemplatedSecret",
    generate_secret_string=secretsmanager.SecretStringGenerator(
        secret_string_template=JSON.stringify({"username": "postgres"}),
        generate_string_key="password",
        exclude_characters="/@""
    )
)
# Using the templated secret as credentials
instance2 = rds.DatabaseInstance(self, "PostgresInstance2",
    engine=rds.DatabaseInstanceEngine.POSTGRES,
    credentials={
        "username": templated_secret.secret_value_from_json("username").to_string(),
        "password": templated_secret.secret_value_from_json("password")
    },
    vpc=vpc
)
```

And the code will fail if a `dict` is used, as shown. Either the documentation should be updated to remove the invalid example, or (recommended) the `credentials` variable should be updated to accept a `dict`.

### Expected Behavior

A `dict` should be accepted for the `credentials` parameter of `DatabaseInstance`.

### Current Behavior

```
TypeError: type of argument credentials must be one of (aws_cdk.aws_rds.Credentials, NoneType); got dict instead
```

### Reproduction Steps

Copy and paste the example from the documentation.

### CDK CLI Version

2.145.0 (build fdf53ba)

### Node.js Version

Node.js v22.2.0

### OS

macOS

### Language

Python

### Language Version

Python 3.12.0

**Comment by andrewvaughan** [comment]
Alternatively, improve the documentation by removing the `dict` based approach and use:

```py
  # ...
  credentials=rds.Credentials.from_secret(templated_secret)
  # ...
```

**Comment by khushail** [comment]
Hi @andrewvaughan , thanks for reaching out.

Could you please try doing this way and see if it works as I noticed that the fromSecert() uses Secret object and username which works like this -
https://github.com/aws/aws-cdk/blob/b368c78026ae4547d6f04e3290a375340c1f6de7/packages/aws-cdk-lib/aws-rds/lib/props.ts#L251

code change - 
```python
credentials= rds.Credentials.from_secret(secret01, "username"),
```
Sharing the synthesized template snippet -

```json
{
 "Resources": {
  "AuroraSecret41E6E877": {
   "Type": "AWS::SecretsManager::Secret",
   "Properties": {
    "Description": {
     "Fn::Join": [
      "",
      [
       "Generated by the CDK for stack: ",
       {
        "Ref": "AWS::StackName"
       }
      ]
     ]
    },
    "GenerateSecretString": {
     "ExcludeCharacters": " %+~`#$&*()|[]{}:;<>?!'/@\"\\",
     "GenerateStringKey": "password",
     "PasswordLength": 30,
     "SecretStringTemplate": "{\"username\":\"clusteradmin\"}"
    }
   },
   "UpdateReplacePolicy": "Delete",
   "DeletionPolicy": "Delete",
   "Metadata": {
    "aws:cdk:path": "RdscredsissueStack/AuroraSecret/Resource"
   }
  },
  ```
  
  Also I tried to repro in typescript to see if dict is accepted and its successful there as well -
  
  ```ts
  const cluster = new rds.DatabaseCluster(this, 'AuroraClusterV2', {
        engine: rds.DatabaseClusterEngine.auroraPostgres({ version: rds.AuroraPostgresEngineVersion.VER_15_5 }),
        credentials: { username: 'clusteradmin'},
        clusterIdentifier: 'db-endpoint-test',
        writer: rds.ClusterInstance.serverlessV2('writer'),
        serverlessV2MinCapacity: 2,
        serverlessV2MaxCapacity: 10,
        vpc,
        defaultDatabaseName: 'demos',
        enableDataApi: true,  // has to be set to true to enable Data API as not enable by default
      });
```

Please feel free to correct if something is misinterpreted.
