### ISSUE TITLE
aws_ec2: ipAddresses is an invalid key for Python, but CIDR gives deprecation warning to use it

### ISSUE THREAD

**Issue by andrewvaughan** [aws/aws-cdk#30510]
### Describe the bug

The `VPC.cidr` prop is deprecated to be removed in the next major release. The deprecation notice and documentation state to use `ipAddresses`, instead.

If you use `ipAddresses` in Python, you get an Exception:

```
TypeError: Vpc.__init__() got an unexpected keyword argument 'ipAddresses'
```

### Expected Behavior

Replacing the `cidr` prop for a VPC with an `ipAddresses` prop, as directed by the deprecation warning, should succeed.

### Current Behavior

```
Traceback (most recent call last):
  File "/Users/andrew/Repositories/REDACTED/devops/infra/entrypoint.py", line 10, in <module>
    NetworkingVPC(app, "vpc-common")
  File "/Users/andrew/.pyenv/versions/3.12.0/lib/python3.12/site-packages/jsii/_runtime.py", line 118, in __call__
    inst = super(JSIIMeta, cast(JSIIMeta, cls)).__call__(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Repositories/REDACTED/devops/infra/Networking/VPC.py", line 20, in __init__
    vpc = aws_ec2.Vpc(
          ^^^^^^^^^^^^
  File "/Users/andrew/.pyenv/versions/3.12.0/lib/python3.12/site-packages/jsii/_runtime.py", line 118, in __call__
    inst = super(JSIIMeta, cast(JSIIMeta, cls)).__call__(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Vpc.__init__() got an unexpected keyword argument 'ipAddresses'

Subprocess exited with error 1
````

### Reproduction Steps

```py
vpc = aws_ec2.Vpc(
    self,
    "vpc-common",
    max_azs=1,
    # cidr="10.0.0.0/16", # This shows a "Deprecated" warning
    ipAddresses=aws_ec2.IpAddresses.cidr(
        "10.0.0.0/16"
    ) # This raises a `TypeError` Exception
)
```

### Possible Solution

Add the `ipAddresses` as a valid keyword for Python.

### CDK CLI Version

2.145.0 (build fdf53ba)

### Node.js Version

v22.2.0

### OS

macOS

### Language

Python

### Language Version

Python 3.12.0

**Comment by andrewvaughan** [comment]
This may be a confusion with the way deprecation warnings are currently performed in Python.

`ip_addresses` is the valid property, but the warning still explicitly states the TypeScript variable. This isn't immediately clear unless you just happen to know to "Pythonize" things with CDK:

```
[WARNING] aws-cdk-lib.aws_ec2.VpcProps#cidr is deprecated.
  Use ipAddresses instead
  This API will be removed in the next major release.
```

**Comment by ashishdhingra** [comment]
@andrewvaughan Good morning. Thanks for reporting the issue. You are right, `ip_addresses` is a valid property. So the following code works:
```Python
from aws_cdk import (
    # Duration,
    Stack,
    aws_ec2 as ec2,
)
from constructs import Construct

class PythonStack(Stack):

    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        vpc = ec2.Vpc(self, 
                      "vpc-common",
                      ip_addresses=ec2.IpAddresses.cidr("10.0.0.0/16")
                      )
```

Refer Python [Vpc](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_ec2/Vpc.html) documentation.

Regarding the warning message, the Python code is converted to TypeScript code via JSII layer and then the CFN template is synthesized from converted TypeScript code. The warning message is thrown in the converted TypeScript code.

Please let us know if you are unblocked and is this issue could be closed.

Thanks,
Ashish

**Comment by andrewvaughan** [comment]
Thank you for the detailed response! You nailed it exactly. Even if the documentation can't be updated, this issue will likely help people Googling for the issue like I was. Cheers!
