### ISSUE TITLE
Enhancements to `core.Include`

### ISSUE THREAD

**Issue by ccfife** [aws/aws-cdk#3052]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [ ] :beetle: bug report
  - [X] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/awslabs/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*

You can import an existing CloudFormation template into a CDK app, but can't manipulate the resources it defines.

* **What is the expected behavior (or behavior of feature suggested)?**

1. Reference an existing CloudFormation stack (by ARN or stack name) in a CDK app
2. On the empty CDK app, run CDK diff, which shows that none of the resources are defined in CDK code yet. 
3. add CDK constructs that match the resources in the running stack. 
4. As the code is written, keep running CDK diff to see the resources that are missing
5. repeat this process until CDK diff returns an empty set, or no differences. 

* **What is the motivation / use case for changing the behavior or adding this feature?**

Provide a way to migrate existing stacks/resources into CDK applications.

**Comment by eladb** [comment]
Covered by the new CfnInclude module
