### ISSUE TITLE
stepfunctions-tasks: support FLEX execution class for GlusStartJobRun

### ISSUE THREAD

**Issue by mazyu36** [aws/aws-cdk#30533]
### Describe the feature

Glue Job supports [FLEX execution class](https://aws.amazon.com/about-aws/whats-new/2022/08/aws-glue-supports-flex-execution-option/?nc1=h_ls).

This feature can be used by setting `ExecutionClass` in `StartJobRun`.

But current [GlusStartJobRun](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_stepfunctions_tasks.GlueStartJobRun.html) class does not support it.

### Use Case

To reduce job running cost by using FLEX class.

### Proposed Solution

Add `executionClass` property.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.143.0

### Environment details (OS name and version, etc.)

all

**Comment by khushail** [comment]
Thanks @mazyu36 for submitting the request and PR contribution on adding this [FLEX executionClass](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-job.html#cfn-glue-job-executionclass).
