### ISSUE TITLE
Gateway API: integration timeout cannot be over 29 seconds

### ISSUE THREAD

**Issue by kraashen** [aws/aws-cdk#30539]
### Describe the bug

AWS API Gateway timeout limit for integrations was previously 29 seconds. There has been an update to allow increasing the Gateway integration timeouts past the previous limit. https://aws.amazon.com/about-aws/whats-new/2024/06/amazon-api-gateway-integration-timeout-limit-29-seconds/

However, when implementing a Gateway API to Lambda, it seems that when synth'ing the stack, this seems to hit a validation error.

### Expected Behavior

When configuring the Gateway API type (regional/private), timeout could be set over 29 seconds.

### Current Behavior

When configuring the Gateway API, timeout cannot be over 29 seconds.

Error log when deploying/synth'ing

```
WARN AWS_SOLUTIONS_CONSTRUCTS_WARNING:  Possible override of timeout value.
Failed to synthesize: Error: Integration timeout must be between 50 milliseconds and 29 seconds.
```

### Reproduction Steps

```typescript
const ApiGateway = new ApiGatewayToLambda(
      this,
      'MyAPIGW',
      {
        lambdaFunctionProps: {
          runtime: Runtime.PROVIDED_AL2,
          handler: 'bootstrap',
          code: Code.fromAsset(join(__dirname, '..', '..', 'target', 'bin', 'linux', 'amd64', 'lambda', 'runtime')),
          timeout: Duration.minutes(5),
          environment: {
            ...
          },
        },
        apiGatewayProps: {
          defaultCorsPreflightOptions: {
            allowOrigins: ['*'],
            allowMethods: [HttpMethod.POST],
          },
          integrationOptions: {
            timeout: Duration.seconds(60),
          },
          endpointConfiguration: {
            types: [aws_apigateway.EndpointType.REGIONAL],
          },
        },
      },
    );
```

### CDK CLI Version

2.145.0

### Framework Version

2.145.0

### Node.js Version

20.14.0

### OS

MacOS

### Language

TypeScript

### Other information

This issue came up when using `aws-solutions-constructs`. After quick look, it seemed to point to the Gateway API core package. Original issue reference here: https://github.com/awslabs/aws-solutions-constructs/issues/1137,

**Comment by nmussy** [comment]
I'll take care of it, thanks for the detailed issue 👍

**Comment by ashishdhingra** [comment]
@nmussy Thanks for the PR.

**Comment by ashishdhingra** [comment]
Another issue https://github.com/aws/aws-cdk/issues/30550 related to timeout.
