### ISSUE TITLE
events: support dead letter queue for the event bus

### ISSUE THREAD

**Issue by mazyu36** [aws/aws-cdk#30531]
### Describe the feature

Event bus support the [Dead Letter Queue](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_events.CfnEventBus.html#deadletterconfig).

But current [EventBus](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_events.EventBus.html) Class does not support it.

### Use Case

To avoid losing events after they fail to be delivered to a target.

### Proposed Solution

Add `queue` property to set the Dead Letter Queue.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.143.0

### Environment details (OS name and version, etc.)

all

**Comment by khushail** [comment]
Thanks @mazyu36 for submitting this Feature request and volunteering for contribution!
