### ISSUE TITLE
(apigateway): support integration timeout >29 seconds

### ISSUE THREAD

**Issue by awsdataarchitect** [aws/aws-cdk#30550]
### Describe the bug

API Gateway now supports integration timeout greater than 29 seconds as released [here](https://aws.amazon.com/about-aws/whats-new/2024/06/amazon-api-gateway-integration-timeout-limit-29-seconds/).

This PR [#14154](https://github.com/aws/aws-cdk/pull/14154) added a hard limit of 29000 milliseconds, so we need to remove that.

### Expected Behavior

To be able to specify a value greater than 29 seconds from CDK

### Current Behavior

Error: Integration timeout must be between 50 milliseconds and 29 seconds.
    at new Integration (../node_modules/aws-cdk-lib/aws-apigateway/lib/integration.js:1:1439)
    at new AwsIntegration (../node_modules/aws-cdk-lib/aws-apigateway/lib/integrations/aws.js:1:1140)
    at new LambdaIntegration (../node_modules/aws-cdk-lib/aws-apigateway/lib/integrations/lambda.js:1:979)
    at new CdkApiTimeoutDemoStack (../lib/cdk-api-timeout-demo-stack.ts:28:43)
    at Object.<anonymous> (../bin/cdk-api-timeout-demo.ts:7:1)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module.m._compile (../node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Object.require.extensions.<computed> [as .ts] (../node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1207:32)

Subprocess exited with error 1

### Reproduction Steps

 // Integrate the Lambda function with the API Gateway
    const getImageProcessingIntegration = new apigateway.LambdaIntegration(imageProcessor, {
      requestTemplates: { 'application/json': '{ "statusCode": "200" }' },
      timeout: cdk.Duration.seconds(35), // This throws Error: Integration timeout must be between 50 milliseconds and 29 seconds.
      integrationResponses: [
        {
          statusCode: '200',
          responseTemplates: {
            'application/json': ''
          }
        }
      ]
    });

### CDK CLI Version

2.145.0 (build fdf53ba)

### Node.js Version

v20.11.0

### OS

macOS 14.4 Beta (23E5196e)

### Language

TypeScript

**Comment by ashishdhingra** [comment]
@awsdataarchitect Thanks for reporting the issue. Looks like it is similar to existing issue https://github.com/aws/aws-cdk/issues/30539. Please verify if that is the case, then we could close this issue since are other one has associated PR already drafted.

Thanks,
Ashish

**Comment by awsdataarchitect** [comment]
> @awsdataarchitect Thanks for reporting the issue. Looks like it is similar to existing issue https://github.com/aws/aws-cdk/issues/30539. Please verify if that is the case, then we could close this issue since are other one has associated PR already drafted.
> 
> 
> 
> Thanks,
> 
> Ashish

Yes looks similar. Reviewing the pull request as need to remove apigatewayv2 since the http and websocket limits are still hard 29 seconds

**Comment by ashishdhingra** [comment]
@awsdataarchitect Thank you for sharing the update. Great to hear that. Yes we need a PR to unblock the limit, before that, you can use escape hatches to override [TimeoutInMillis](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apigateway-method-integration.html#cfn-apigateway-method-integration-timeoutinmillis) to work it around. I am not pretty sure if it would work because per CFN doc of this property: `Custom timeout between 50 and 29,000 milliseconds. The default value is 29,000 milliseconds or 29 seconds.` Looks like this property still has the limit of 29 seconds. Please let me know if it works for you.

Thanks,
Ashish

**Comment by pahud** [comment]
closed by https://github.com/aws/aws-cdk/pull/30547
