### ISSUE TITLE
AWS Backup - CDK Support

### ISSUE THREAD

**Issue by dietkinnie** [aws/aws-cdk#3056]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [ ] :beetle: bug report
  - [x] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/awslabs/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*

* **What is the expected behavior (or behavior of feature suggested)?**
Since AWS Backup now supports CloudFormation, it would be great if this can also be made available within CDK 

https://aws.amazon.com/about-aws/whats-new/2019/05/aws-backup-now-supports-aws-cloudformation/

* **What is the motivation / use case for changing the behavior or adding this feature?**
The Main Motivation would be to fully automate our AWS infrastructure by adopting an IaC approach and this is one of the missing pieces. 

* **Please tell us about your environment:**
  
  - CDK CLI Version: 0.35.0
  - Module Version: 0.35.0
  - OS: Serverless
  - Language: TypeScript

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

https://aws.amazon.com/about-aws/whats-new/2019/05/aws-backup-now-supports-aws-cloudformation/

**Comment by NGL321** [comment]
Hi @dietkinnie! This seems like a totally reasonable feature-request.

I just want to give you a heads up that, while we **_will_** address this, right now we are working hard to stabilize the CDK APIs and tune them to meet our consistency guidelines. While we work on getting the APIs aligned with our guidelines, we are pausineg work on most community feature-requests. We hope to get back to work on community issues within a few weeks.

I will keep this issue updated when we have time to address it!

**Comment by RomainMuller** [comment]
AWS Backups is now available in `@aws-cdk/aws-backup`.
