### ISSUE TITLE
Network Firewall: L1 construct don't have any way to add Customer managed key

### ISSUE THREAD

**Issue by huyhoang160593** [aws/aws-cdk#30585]
### Describe the bug

like the title said

### Expected Behavior

provide some property like kmsKeyId or somethings to add kms key to construct

### Current Behavior

There is no option to define which Key to use in the struct

### Reproduction Steps

The documentation don't have that option whatsoever

### CDK CLI Version

2.143.0

### Node.js Version

20.10.0

### OS

Linux

### Language

TypeScript

**Comment by pahud** [comment]
Are you looking for a property for customer managed key in [AWS::NetworkFirewall::Firewall](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-networkfirewall-firewall.html) ? If yes, this would be a cloudformation gap and please help the CFN team prioritize by submitting an issue to https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues
