### ISSUE TITLE
aws-amplify-alpha: Add support for custom ACM cert

### ISSUE THREAD

**Issue by thedevopsguyblog** [aws/aws-cdk#30594]
### Describe the feature

Hello,

In the UI their is an option to specify a custom SSL cert that is provisioned via ACM.

<img width="611" alt="Screenshot 2024-06-20 at 9 59 48 am" src="https://github.com/aws/aws-cdk/assets/39054710/f78c49af-4c72-487d-a1ca-6ad8350bab47">

Using the aws-amplify-alpha construct it would be handy if i could specify a SSL cert I would like to use.

### Use Case

I know Specifically in the case when i want to provision my own cert for a custom domain name in cognito and use the same cert for my frontend.

### Proposed Solution

1. Provision the ACM managed cert in a separate stack 
```ts
      new cdk.aws_certificatemanager.Certificate(this, 'Certificate', {
        domainName: props!.envVars.FQDN,
        validation: cdk.aws_certificatemanager.CertificateValidation.fromDns(importedHostedZone),
        subjectAlternativeNames:[
            `*.${props!.envVars.FQDN}`,
            `*.api.${props!.envVars.FQDN}`,
            `*.auth.${props!.envVars.FQDN}`,
        ]
      });
    }
```
2. In the stack where we define the FE app
```ts
new amplifyAlpha.App(this, 'mySubAmpHosting', {
...
acmCert:{
 fromCertificateArn:`xxx`
}
})
```

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.143.0 (build 9f2bdf7)

### Environment details (OS name and version, etc.)

macOS Ventura - 13.6.3

**Comment by khushail** [comment]
Hi @thedevopsguyblog , thanks for reaching out.

I see that [CertificateSettings](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-amplify-domain.html#cfn-amplify-domain-certificatesettings) prop is supported by the cloudformation, and is missing from the alpha module. This prop support providing [AWS managed or Custom certificates](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-amplify-domain-certificatesettings.html), hence is suitable for your usecase.
However I am marking this issue as P3, requesting contributions from the community in this regard.
