### ISSUE TITLE
Local resources for development and debugging

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#306]
Consider if perhaps specific constructs can support "local mode", which will allow us to bring up local instances of mock services such as DynamoDB, redis, memcached, postgres. This might be very beneficial for dev stacks for quick iteration and cost savings

For compute code (i.e. Lambda, EC2), it should be possible to do something like [sam-cli](https://github.com/awslabs/aws-sam-cli) where we deploy a proxy lambda and route events to the local machine, allowing developers to use the IDE for debugging.

One thing to notice is how the code behaves in respect to VPNs. There are some AWS resources (e.g. ElasticCache) that can only be accessed from within a VPC. Does that mean that the local machine needs to be connected to the VPC or the VPC needs to allow access from that machine.

**Comment by eladb** [comment]
still relevant

**Comment by michaelbrewer** [comment]
@eladb would it be possible to work with the AWS SAM team to allow for CDK and SAM to do this in a much more connected way. AWS SAM CLI is stable, but it just does not easily see the stacks created by CDK

**Comment by madeline-k** [comment]
After closer examination of the issue by CDK product and development team, there are no plans to implement this in the near feature. If you are still interested in discussing this with the CDK team and community, please open a new issue, or a [discussion](https://github.com/aws/aws-cdk/discussions).
