### ISSUE TITLE
(dynamodb): Dynamo TableV2 does not work with Tags.of

### ISSUE THREAD

**Issue by ckuehne** [aws/aws-cdk#30631]
### Describe the bug

The `aws_dynamodb.TableV2` construct does not support adding tags via `Tags.of`.

I.e., the following code does not create the `myKey` tag.

``` 
import * as cdk from 'aws-cdk-lib';
import {aws_dynamodb, Tags} from "aws-cdk-lib";

const app = new cdk.App();
const stack = new cdk.Stack(app, 'Stack');

const globalTable = new aws_dynamodb.TableV2(stack, 'GlobalTable', {
    partitionKey: {name: 'pk', type: aws_dynamodb.AttributeType.STRING},
});

Tags.of(globalTable).add('myKey', 'myValue');
```

### Expected Behavior

Creates tag.

### Current Behavior

Does not create tag.

### Reproduction Steps

``` 
import * as cdk from 'aws-cdk-lib';
import {aws_dynamodb, Tags} from "aws-cdk-lib";

const app = new cdk.App();
const stack = new cdk.Stack(app, 'Stack');

const globalTable = new aws_dynamodb.TableV2(stack, 'GlobalTable', {
    partitionKey: {name: 'pk', type: aws_dynamodb.AttributeType.STRING},
});

Tags.of(globalTable).add('myKey', 'myValue');
```

cdk synth

### CDK CLI Version

2.147.0 (build 3338fc0)

### Node.js Version

v20.3.1

### OS

Macos

### Language

TypeScript

### Language Version

TypeScript 5.4.5

**Comment by TirushV** [comment]
Suggestion: Try using aspects to add tags to the current stack where Aspect is called.

**Comment by ckuehne** [comment]
> Suggestion: Try using aspects to add tags to the current stack where Aspect is called.

Yes, this would work. But still the buggy behaviour is unexpected and should be fixed.

**Comment by TirushV** [comment]
Thats true. I agree

**Comment by khushail** [comment]
Hey @ckuehne , thanks for reporting this. I reproduced this issue and agree that this is a buggy behavior. Hence marking it as P3.

However if you try assigning the tags like this, this adds the tags to the table

```ts
    const globalTable = new aws_dynamodb.TableV2(this, 'GlobalTable', {
      partitionKey: {name: 'pk', type: aws_dynamodb.AttributeType.STRING},
      tags: [{key: "myKeyTag", value: "myValueTag"}]
    });
    ```
