### ISSUE TITLE
(aws-location-alpha): support L2 Map Construct 

### ISSUE THREAD

**Issue by mazyu36** [aws/aws-cdk#30647]
### Describe the feature
In [aws-location-alpha](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-location-alpha-readme.html), `map` has not been supported yet.

Adding the Map class to the alpha module enables easier usage.

### Use Case

To create map resource.

### Proposed Solution

Add `Map` class.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.147.0

### Environment details (OS name and version, etc.)

all

**Comment by khushail** [comment]
Thanks for requesting this feature and submitting a PR @mazyu36 ! Appreciate your efforts!
