### ISSUE TITLE
cloudformation-include: overrideLogicalId validation causing CfnInclude to error on Condition logical Id

### ISSUE THREAD

**Issue by mjgoble** [aws/aws-cdk#30669]
### Describe the bug

The following PR #29708 introduced validation for `overrideLogicalId`

This has caused an issue with `cloudformation-include` when trying to cfnInclude a cloudformation template that has defined Conditions using non-alphanumeric characters, e.g. snake case `my_condition`

Cloudformation include by default preserves the logical Id that is defined in the cloudformation template. This is done in part by using the `overrideLogicalId` function to ensure the logical id of the resource is not changed during the cdk synth

https://github.com/aws/aws-cdk/blob/cce10b1c1f0f764e39e734ad7d6c288b7ffb9da3/packages/aws-cdk-lib/cloudformation-include/lib/cfn-include.ts#L771-L775

Now due to the new validation on `overrideLogicalId` - Conditions cannot be defined as non-alphanumeric despite them never actually being deployed as resources in Cloudformation

### Expected Behavior

Stack synth completes successfully, logical Ids defined in the included cloudformation template is preserved, including the snake case Condition logical Ids

Cloudformation deploy succeeds even despite having non-alphanumeric logical Ids defined for `Conditions`

### Current Behavior

Stack synth fails with a Runtime Error
`RuntimeError: Invalid logical ID override: 'my_condition'. It must only contain alphanumeric characters.`

### Reproduction Steps

cfn_include a cloudformation template that defines conditions using snake case logical id, e.g. `my_condition`

### CDK CLI Version

2.147.1

### Node.js Version

20.5.0

### OS

Linux

### Language

Python

### Language Version

Python (3.12.3)

**Comment by GavinZZ** [comment]
Thanks @mjgoble for creating this issue. You're right that the logical id validation code is applied not only on the `Resources` properties only but also `Conditions`. This caused unexpected behaviours. Since this is a regression, we will treat it as `p0`. As a temporary workaround, please downgrade to a previous version.

**Comment by TheRealAmazonKendra** [comment]
Revert: https://github.com/aws/aws-cdk/pull/30695
