### ISSUE TITLE
SES: EventDestination does not have eventBridge as a destination option

### ISSUE THREAD

**Issue by anishsundarjee** [aws/aws-cdk#30677]
### Describe the bug

I'm trying to add the default event bus as the event destination for my mailing events.

My use case is that I want to save delivery information about the emails being sent from SES for compliance reasons.
Am able to achieve this if I setup the configuationSet and event destination via the AWS CLI, however I can't see the option to add eventBridge as a destination in cdk.

### Expected Behavior

Be able to set EventBridge as a event destination

### Current Behavior

not able to set EventBridge as a event destination

### Reproduction Steps

```
  appState.sesConfigurationSet = new ses.CfnConfigurationSet(appState.stack, `${PREFIX}ConfigurationSet`, {
    name: `${PREFIX}ConfigurationSet`,
    reputationOptions: {
      reputationMetricsEnabled: true,
    },
  });

  appState.sesEventDestination = new ses.CfnConfigurationSetEventDestination(appState.stack, `${PREFIX}EventDestination`, {
    configurationSetName: appState.sesConfigurationSet.name || "",
    eventDestination: {
      matchingEventTypes: ['delivery'],
      name: `${PREFIX}EventDestination`,
      enabled: true,
      eventBridgeDestination: {
        arn: appState.defaultEventBus.eventBusArn || "",
      },
      // set event bridge as destination with name AWS_SES_SEND_EMAIL and rules for bounce, complaint and delivery
    },
  });
```

### CDK CLI Version

1.199.0

### Node.js Version

18

### OS

Mac OS

### Language

TypeScript

### Language Version

3.8

**Comment by ashishdhingra** [comment]
Findings:
- Based on [CfnConfigurationSetEventDestination](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ses.CfnConfigurationSetEventDestination.html) CDK documentation, there is no property for EventBridge as destination option.
- However, [AWS::SES::ConfigurationSetEventDestination EventDestination](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ses-configurationseteventdestination-eventdestination.html) specifies [EventBridgeDestination](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ses-configurationseteventdestination-eventdestination.html#cfn-ses-configurationseteventdestination-eventdestination-eventbridgedestination) as one of the options.
- CloudFormation spec [here](https://d1uauaxba7bl26.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json) also has `EventBridgeDestination` for `AWS::SES::ConfigurationSetEventDestination.EventDestination`.

**Comment by ashishdhingra** [comment]
[eventBridgeDestination](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ses.CfnConfigurationSetEventDestination.EventDestinationProperty.html#eventbridgedestination) is now available in latest CDK Lib version.
