### ISSUE TITLE
aws-location-alpha: support L2 Route Calculator Construct

### ISSUE THREAD

**Issue by mazyu36** [aws/aws-cdk#30681]
### Describe the feature

In [aws-location-alpha](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-location-alpha-readme.html), [route calculator](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_location.CfnRouteCalculator.html) has not been supported yet.

Adding the RouteCalculator class to the alpha module enables easier usage.

### Use Case

To use route calculator.

### Proposed Solution

Add `RouteCalculator` class.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.147.0

### Environment details (OS name and version, etc.)

all

**Comment by khushail** [comment]
thanks for requesting this feature @mazyu36
