### ISSUE TITLE
[lambda] Ability to select subnets from a VPC

### ISSUE THREAD

**Issue by mariovalentim** [aws/aws-cdk#3070]
* **I'm submitting a ...**
  - [X] :beetle: bug report

* **What is the current behavior?**
On version 0.35 there's no way to import a current VPC with a subset of Subnets. It looks like this was doable on previous versions with ec2.VPCNetwork but this object doesn't exist anymore.
Basically, I need to create a lambda in a VPC for just 3 subnets out of 15. When I import like:
``` 
const importedVpc = ec2.Vpc.fromLookup(this, `vpc-myvpcname-01-vpc`, {
  vpcName: `vpc-myvpcname-01-vpc`
});
```
If I use this const in my lambda config. like bellow, it will configure the function with all the subnets:
```
const func = new lambda.Function(this, 'MyLambda', {
            code: lambda.Code.asset('../folder'),
            handler: 'class.lambda_handler',
            runtime: lambda.Runtime.Python37,
            vpc: importedVpc,
            memorySize: 400,
            timeout: 300
        });
```
* **What is the expected behavior (or behavior of feature suggested)?**
Either filter the looked up VPC for specific subnets or being able to filter the subnets in my lambda function.

* **What is the motivation / use case for changing the behavior or adding this feature?**
Being able to specify which subnets my lambda should be configured for, and not all the subnets in the vpc that was looked up

* **Please tell us about your environment:**
  - CDK CLI Version: 0.35.0
  - OS: all
  - Language: TypeScript

**Comment by nija-at** [comment]
We now have the ability to do this via the `vpcSubnets` property - https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-lambda.FunctionProps.html#vpcsubnets.

This should satisfy your ask.

Reopen this issue if you think there's something still amiss.
