### ISSUE TITLE
aws-location-alpha: support L2 Geofence Collection Construct

### ISSUE THREAD

**Issue by mazyu36** [aws/aws-cdk#30710]
### Describe the feature

In [aws-location-alpha](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-location-alpha-readme.html), [geofence collection](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_location.CfnGeofenceCollection.html) has not been supported yet.

Adding the GeofenceCollection class to the alpha module enables easier usage.

### Use Case

To use geofence collection.

### Proposed Solution

Add `GeofenceCollection` class.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.147.0

### Environment details (OS name and version, etc.)

all

**Comment by pahud** [comment]
Thank you @mazyu36
