### ISSUE TITLE
aws-ecs: Enable Ephemeral storage encryption in ECS Cluster L2 construct

### ISSUE THREAD

**Issue by jaecktec** [aws/aws-cdk#30721]
### Describe the feature

Add properties to L2 ecs CLuster construct to support ephemeral storage configuration

### Use Case

Right now to enable this feature I need to edit the L1 construct like this: 

```typescript
const cfnCluster = cluster.node.defaultChild as CfnCluster;
cfnCluster.configuration = {
  ...cfnCluster.configuration,
  managedStorageConfiguration: {
    ...cfnCluster.configuration,
    fargateEphemeralStorageKmsKeyId: key.keyId,
  },
};
```

and adjusting the key policy according to the developer guide. 

### Proposed Solution

L2 Construct should support setting the new feature of ephermal storage encryption which adds the keys + updates the key policy

### Other Information

Developer Guide: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/fargate-create-storage-key.html
Ephemeral Storage Encryption: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/fargate-storage-encryption.html

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.147.0

### Environment details (OS name and version, etc.)

-

**Comment by ashishdhingra** [comment]
@jaecktec Thanks for submitting feature request and nominating to submit a PR.
