### ISSUE TITLE
(ec2.Vpc): (max_azs=3 does not take effect)

### ISSUE THREAD

**Issue by syangdh** [aws/aws-cdk#30732]
### Describe the bug

I am trying to create a VPC with 3 AZs, but it turns out it only used 2 AZ, i.e.,  only have 6 subnets instead of 9 subnets

```
class VPCStack(core.Stack):

    def __init__(self, scope: Construct, id: str, environment: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        self.vpc = ec2.Vpc(self, "SharedVPC",
            ip_addresses=ec2.IpAddresses.cidr("10.0.0.0/16"),
            max_azs=3,
            nat_gateways = 1,
            subnet_configuration=[
                ec2.SubnetConfiguration(
                    subnet_type=ec2.SubnetType.PUBLIC,
                    name="Ingress",
                    cidr_mask=24
                ),
                ec2.SubnetConfiguration(
                    subnet_type=ec2.SubnetType.PRIVATE_WITH_EGRESS,
                    name="Application",
                    cidr_mask=24
                ),
                ec2.SubnetConfiguration(
                    subnet_type=ec2.SubnetType.PRIVATE_ISOLATED,
                    name="Database",
                    cidr_mask=28
                )
            ]
        )

```

### Expected Behavior

It should have created 9 subnets, but instead it created 6 subnets (My region is us-west-2)

### Current Behavior

only 2 Az were used for the subnet creation

### Reproduction Steps

Code is posted above

### CDK CLI Version

2.147.1 (build d3695d4)

### Node.js Version

v22.2.0

### OS

mac OS

### Language

Python

### Language Version

Python

**Comment by khushail** [comment]
works well for python as well - 9 subnets created -

<img width="979" alt="Screenshot 2024-07-02 at 1 50 46 PM" src="https://github.com/aws/aws-cdk/assets/117320115/713ec8e8-912c-45db-a12d-b54900147fe1">
