### ISSUE TITLE
aws-ssm: Allow creating parameters from a full ARN

### ISSUE THREAD

**Issue by doublecompile** [aws/aws-cdk#30790]
### Describe the feature

As it stands today, [the `StringParameter` class](https://github.com/aws/aws-cdk/blob/e5740c01a5f524b099258820b3206045873b6732/packages/aws-cdk-lib/aws-ssm/lib/parameter.ts#L503) assumes parameter names given to `fromStringParameterAttributes` are in the same account as the containing stack.

Please introduce support for providing a pre-existing SSM Parameter Store parameter ARN to create an instance of `StringParameter`.

Another acceptable implementation might be to add an `account` property to the [`StringParameterAttributes`](https://github.com/aws/aws-cdk/blob/e5740c01a5f524b099258820b3206045873b6732/packages/aws-cdk-lib/aws-ssm/lib/parameter.ts#L365) interface and alter the logic inside `fromStringParameterAttributes` to use the full ARN for the `CfnParameter` default value.

### Use Case

SSM Parameter Store [introduced cross-account sharing](https://aws.amazon.com/about-aws/whats-new/2024/02/aws-systems-manager-parameter-store-cross-account-sharing/) in February 2024. The linked post has the following excerpt:

> You can use central AWS accounts to share parameters for many cross-account scenarios, such as referencing centrally managed “golden” AMI IDs in EC2 Launch Templates for autoscaling

This is my _exact_ use case. I have a String Parameter whose data type is `aws:ec2:image` in account A. The parameter is shared with account B. I have a CloudFormation stack with a Launch Template in account B where I'd like to reference the parameter in account A.

### Proposed Solution

Add a new static method named `fromStringParameterArn` (or something similar) on the `StringParameter` class. This new method should allow me to provide a full ARN for an SSM Parameter Store parameter that can be used in a CloudFormation stack in a different account.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.148.0

### Environment details (OS name and version, etc.)

N/A

**Comment by doublecompile** [comment]
The proposed solution should generate CloudFormation template parameters like this working example:

```yaml
Parameters:
  ImageIdParam:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: arn:aws:ssm:us-east-1:123456789012:parameter/name/of/my/param
```

**Comment by pahud** [comment]
related to https://github.com/aws/aws-cdk/pull/30646

Is this something you want?

**Comment by doublecompile** [comment]
@pahud Yes, the pull request you linked will cover my use case. Thanks!

**Comment by doublecompile** [comment]
Closing; this has been resolved thanks to https://github.com/aws/aws-cdk/pull/30646 being merged in.
