### ISSUE TITLE
api-gateway-deployment: stage_name parameter for the L2 deployment construct is unavailable

### ISSUE THREAD

**Issue by junnkim** [aws/aws-cdk#30805]
### Describe the bug

aws-cdk-lib release v2.140 includes the addition of the stage_name parameter to the L2 deployment construct: https://github.com/aws/aws-cdk/releases/tag/v2.140.0

This parameter is also listed as available in the docs: https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_apigateway/Deployment.html

However, the param is unavailable upon import:
![apig deployment params](https://github.com/aws/aws-cdk/assets/104690669/8df6d8c6-a7ed-4eb1-b54b-b0c550e2f3d4)

I am on: 
aws-cdk-lib==2.141.0
constructs>=10.0.0,<11.0.0

### Expected Behavior

Use the stage_name parameter when utilizing the Deployment construct

### Current Behavior

The stage_name param shows as unavailable

### Reproduction Steps

The definition of the Deployment class is: 

    def __init__(
        self,
        scope: _constructs_77d1e7e8.Construct,
        id: builtins.str,
        *,
        api: "IRestApi",
        description: typing.Optional[builtins.str] = None,
        retain_deployments: typing.Optional[builtins.bool] = None,
    ) -> None:
        '''
        :param scope: -
        :param id: -
        :param api: The Rest API to deploy.
        :param description: A description of the purpose of the API Gateway deployment. Default: - No description.
        :param retain_deployments: When an API Gateway model is updated, a new deployment will automatically be created. If this is true, the old API Gateway Deployment resource will not be deleted. This will allow manually reverting back to a previous deployment in case for example Default: false
        '''

As you can see, there is no stage_name parameter. 

### CDK CLI Version

2.127

### Node.js Version

18.17.0

### OS

Windows

### Language

Python

### Language Version

3.11.4

**Comment by khushail** [comment]
Hi @junnkim , thanks for reaching out.

I am able to see the mentioned property in code with CDK 2.141.0, please see the attached snapshot for the same -

<img width="782" alt="Screenshot 2024-07-10 at 12 11 50 PM" src="https://github.com/aws/aws-cdk/assets/117320115/e44dfd9d-123c-43af-9dab-94c773e477d7">

**Comment by junnkim** [comment]
Thank you for assisting. This was indeed due to a messed virtual env on my part. I can see the parameter now.

**Comment by khushail** [comment]
Happy to help! I am closing this one now!
