### ISSUE TITLE
Code refactoring of enum like members (0.36.0) to ALL_CAPS not reflected in docs

### ISSUE THREAD

**Issue by mhuebner** [aws/aws-cdk#3081]
* **I'm submitting a ...**
  - [x] :beetle: bug report

* **What is the current behavior?**
Docs are out of sync regarding refactored enum like members (`0.36.0`):
#3024 #3023, #3018 #980 #2989 #2918 #2287

* **What is the expected behavior (or behavior of feature suggested)?**
Docs should be rewritten to reflect changes of #3024 #3023, #3018 #980 #2989 #2918 #2287

**Comment by Doug-AWS** [comment]
Let's track the readme issues here.

**Comment by Jerry-AWS** [comment]
This should all be correct now, surely? If not, we can reopen.
