### ISSUE TITLE
aws_rds: RDS construct cannot create Aurora serverless in Isolated VPC

### ISSUE THREAD

**Issue by zmgehlke** [aws/aws-cdk#30827]
### Describe the bug

I create a VPC using the CDK with isolated networks.

```
this.vpc = new cdk.aws_ec2.Vpc(this, 'vpc', {
            ipAddresses: cdk.aws_ec2.IpAddresses.cidr('10.0.0.0/16'),
            createInternetGateway: false,
            subnetConfiguration: [
                {
                    name: 'isolated',
                    subnetType: cdk.aws_ec2.SubnetType.PRIVATE_ISOLATED,
                    cidrMask: 24,
                }
            ]
        })
```

I then create a subnet group:
```
        const subnetGroup = new cdk.aws_rds.SubnetGroup(this, 'subnets', {
            description: 'ledger-isolated',
            subnetGroupName: 'ledger-isolated',
            removalPolicy: cdk.RemovalPolicy.DESTROY,

            vpc: props.vpc,
            vpcSubnets: {
                subnets: props.vpc.isolatedSubnets
            },
        })
```

I then create an RDS cluster:
```
        this.table = new cdk.aws_rds.DatabaseCluster(this, 'ledger', {
            engine: cdk.aws_rds.DatabaseClusterEngine.auroraPostgres({version: cdk.aws_rds.AuroraPostgresEngineVersion.VER_16_2}),
            deletionProtection: false, // TODO: Enable for production.
            
            serverlessV2MaxCapacity: 2,
            serverlessV2MinCapacity: 0.5,
            vpcSubnets: subnetGroup,

            writer: cdk.aws_rds.ClusterInstance.serverlessV2('writer'),
            readers: [
                cdk.aws_rds.ClusterInstance.serverlessV2('reader')
            ]
        });
```

I get the following error:
```
Error: Provide either vpc or instanceProps.vpc, but not both
    at new DatabaseClusterNew [...]
    at new DatabaseCluster [...]
```

I have tried numerous options on the subnet group and other definitions; no combination of features appears to work.

### Expected Behavior

Create RDS serverless cluster in isolated VPC.

### Current Behavior

Inscrutable error about defining VPC settings.

### Reproduction Steps

See above.

### Additional Information/Context

I'm deeply frustrated that the CDK decided to become "smart" by automating so many important features -- because you took a good product and made it impossible to use, due to the continually malfunctioning automation. RDS wasn't previously impossible to set up, due to the CDK breaking when small customizations were made.

### CDK CLI Version

2.148.0

### Node.js Version

20.15.1

### OS

Ubuntu 22.04

### Language

TypeScript

**Comment by khushail** [comment]
Hey @zmgehlke , thanks for reaching out. Could you please mention in which CDK version you found it to be correctly working ?

**Comment by zmgehlke** [comment]
Hi @khushail -- I appreciate your effort investigating this issue, but unfortunately it's been a few years since I've used the RDS construct (since circa 2022) and I no longer know which specific version I was using.

I'm not actually convinced that I'm reporting the correct error, eg if I switch the definition:
```
    serverlessV2MaxCapacity: 2,
    serverlessV2MinCapacity: 0.5,
    vpc: props.vpc,
    vpcSubnets: subnetGroup,
```

...then I get a new error where it apparently cannot find the correct subnet entities. My larger complaint is that no variety of options appears to work in even this relatively basic case to accomplish a relatively simple goal -- deploying severless RDS into a VPC.

**Comment by khushail** [comment]
Hi @zmgehlke , Looks like your issue is quite similar to this one - https://github.com/aws/aws-cdk/issues/29256

The sample code shared here might be what you are looking for- https://github.com/aws/aws-cdk/issues/29256#issuecomment-1965551293

Let me know if it does not work for you.
