### ISSUE TITLE
(ec2): BastionHostLinux should use AmazonSSMManagedInstanceCore policy

### ISSUE THREAD

**Issue by clueleaf** [aws/aws-cdk#30834]
### Describe the feature

`BastionHostLinux` currently has the following instance role.
https://github.com/aws/aws-cdk/blob/5ef3be5b5da8653614c75613337429c2a85b86fb/packages/aws-cdk-lib/aws-ec2/lib/bastion-host.ts#L192-L199

This has insufficient permissions to be managed by SSM. [AmazonSSMManagedInstanceCore](https://docs.aws.amazon.com/aws-managed-policy/latest/reference/AmazonSSMManagedInstanceCore.html) should be used instead. (Especially `ssm` permissions)

### Use Case

Manage instance by SSM.

### Proposed Solution

Use AmazonSSMManagedInstanceCore policy instead of inline policy.

### Other Information

According to my research, The code above first appeared in https://github.com/aws/aws-cdk/pull/3697
It seems like the instance role was not discussed then.

### Acknowledgements

- [X] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### CDK version used

2.144.0

### Environment details (OS name and version, etc.)

macOS

**Comment by hoegertn** [comment]
Hi, can you elaborate on the missing permissions? I explicitly did not use it because of the broad permissions regarding parameter store etc.

But we can change that if it is deemed safe.

**Comment by clueleaf** [comment]
@hoegertn 
Thank you for your response.
One thing I noticed is when I tried to scan the bastion host using [Inspector](https://docs.aws.amazon.com/inspector/latest/user/scanning-ec2.html), the State Manager association created automatically failed because of the lack of permission, which resulted in scan failure.
<img width="1375" alt="Screenshot 2024-07-12 at 21 26 01" src="https://github.com/user-attachments/assets/98fe81e7-15fa-4fb7-9a91-e72c3e6f1f72">
<img width="1424" alt="Screenshot 2024-07-12 at 21 23 48" src="https://github.com/user-attachments/assets/db5fe0e2-0c14-4e48-ad3c-d2ef1b305be1">

The execution history shows `ssm:GetManifest` was missing, which is included in `AmazonSSMManagedInstanceCore`. I'm not sure about other permissions, but I have a feeling that it would be safe to use `AmazonSSMManagedInstanceCore` so that bastion instances can be fully managed by SSM.

**Comment by pahud** [comment]
@clueleaf 

Makes sense to me. Feel free to submit a PR for that if you like. Before that, I am afraid we'll need to manually attach that managed policy to the instance role like

```ts
    const bast = new ec2.BastionHostLinux(this, 'Bast', {
      vpc,
    });

    bast.role.addManagedPolicy(iam.ManagedPolicy.fromAwsManagedPolicyName('AmazonSSMManagedInstanceCore'));
```

**Comment by hoegertn** [comment]
Please consider adding the missing statements instead of adding the ManagedPolicy. The ManagedPolicy might be a breaking change for users as some companies do not allow the use of managed policies as they ofter are to wide.

**Comment by clueleaf** [comment]
> The ManagedPolicy might be a breaking change for users as some companies do not allow the use of managed policies as they ofter are to wide.

Good point. Since we can work around by adding policies like @pahud shows, it is safe to keep the current state. Closing this issue.
