### ISSUE TITLE
AWS::Cognito::UserPool: not supported for hotswap deployments

### ISSUE THREAD

**Issue by wcheek** [aws/aws-cdk#30838]
### Describe the bug

Every time I run `cdk deploy` with `--hotswap` or `--hotswap-fallback` I am notified that I have non-Asset changes and it must fall back to a full deployment

### Expected Behavior

`hotswap` succeeds without needing to fall back to a full deployment.

It seems like these /should/ be hotswappable changes, since they are just settings of my `UserPool`. By not being hotswappable, this issue slows down my deployments.

### Current Behavior

```cmd
⚠️ The following non-hotswappable changes were found:
    logicalID: XXXXXXXXX, type: AWS::Cognito::UserPool, 
rejected changes: AdminCreateUserConfig,EmailVerificationMessage,EmailVerificationSubject,VerificationMessageTemplate, 
reason: This resource type is not supported for hotswap deployments

Could not perform a hotswap deployment, as the stack XXXX contains non-Asset changes
Falling back to doing a full deployment
```

### Reproduction Steps

1. Define a `UserPool` with these settings:
```ts
    let userPool = new cognito.UserPool(this, "userPool", {
...
      userVerification: {
        emailSubject: "....",
        emailBody: `.... `,
      },
      userInvitation: {
        emailSubject: "....",
        emailBody: `....`,
      },
    });
```

2. Run `cdk deploy --hotswap` or `cdk deploy --hotswap-fallback`

### CDK CLI Version

2.148.0 (build e5740c0)

### Node.js Version

v20.11.1

### OS

Ubuntu 22.04.4 LTS

### Language

TypeScript

### Language Version

5.4.3

**Comment by ashishdhingra** [comment]
@wcheek Good morning. Your issue appears to be similar to existing issue https://github.com/aws/aws-cdk/issues/28058. Please review if this is the case and close this one.

Thanks,
Ashish
