### ISSUE TITLE
Do not include aws-cdk (CLI) in reference docs

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#3084]

**Comment by SomayaB** [comment]
@shivlaks  What's the status on this?

**Comment by shivlaks** [comment]
@SomayaB The issue is still relevant as the TypeScript reference still has `aws-cdk` in it. Doesn't look like the other languages or the universal docs include it though.

**Comment by ccfife** [comment]
There is useful information in the "core" (formally "cdk") library section of the API reference, such as duration, secrets, ARN manipulation, and CloudFormation features. I strongly advocate we keep this section.
