### ISSUE TITLE
(aws_s3_deployment): Specify destinationKey for S3 asset in BucketDeployment

### ISSUE THREAD

**Issue by erwaxler** [aws/aws-cdk#30846]
### Describe the feature

I am proposing that an optional prop `destinationKey` is added to the [BucketDeployment](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_s3_deployment.BucketDeployment.html) construct, mirroring the `destinationKey` prop that exists on the [DeployTimeSubstitutedFile](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_s3_deployment.DeployTimeSubstitutedFile.html#destinationkey) construct. This will allow users to upload file assets to S3 to a predefined S3 path.

### Use Case

I am trying to use the CDK to create and invoke an AWS CodePipeline that uses S3 as a source. CodePipeline requires that files exist as a `.zip` file in the source S3 bucket. While I know I could reference the auto-generated object key of the file in the CodePipeline definition, this would then require users to reuse a lengthy and meaningless file name when working with files locally, rather than a friendly expected name. 

I attempted to use [DeployTimeSubstitutedFile](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_s3_deployment.DeployTimeSubstitutedFile.html#destinationkey) to achieve this behavior with a locally zipped file (with no substitutions), but this resulted in a corrupted zip file in S3. 

### Proposed Solution

Add an optional `destinationKey` similar to what was done for the `DeployTimeSubstitutedFile` class here: https://github.com/aws/aws-cdk/pull/29029

### Other Information

I understand this feature represents a general anti-pattern in CDK of using static names, in this use case the idea is to generate an easy-to-use CodePipeline for users who likely do not have significant development experience. I'm open to other ideas of how to work around this that result in local files zipped and uploaded to S3 with a specific object key that don't require implementing a custom resource.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.147.3

### Environment details (OS name and version, etc.)

macOS Sonoma 14.5

**Comment by ashishdhingra** [comment]
[BucketDeployment](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_s3_deployment.BucketDeployment.html) construct also supports optional [destinationKeyPrefix](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_s3_deployment.BucketDeployment.html#destinationkeyprefix) property. So it needs to be decided whether to use it as prefix or ignore it, if we happen to support `destinationKey` property.

**Comment by erwaxler** [comment]
@ashishdhingra That's a great point, I would personally lean toward validating that only one of `destinationKeyPrefix` or `destinationKey` is specified. 

After some more thought,`destinationKey` would also not be relevant when using `BucketDeployment` to upload multiple files. Allowing for a `destinationKey` property may require validating that when specified, `sources` contains a single file (difficult) or that the `extract` property is set to false (easier).

**Comment by erwaxler** [comment]
I've discovered I can achieve this by specifying the asset path to be the directory containing the `.zip` file rather than the full file path. I'll be closing this issue as this discovery negates the need for a `destinationKey` property from my perspective. 

For anyone attempting to upload a zip file using `BucketDeployment`:

Works:
```
    new cdk.aws_s3_deployment.BucketDeployment(this, 'UploadZipFileToS3', {
      sources: [cdk.aws_s3_deployment.Source.asset(`zipFileDirectory`)],
```

Does not work:
```
    new cdk.aws_s3_deployment.BucketDeployment(this, 'UploadZipFileToS3', {
      sources: [cdk.aws_s3_deployment.Source.asset(`zipFileDirectory/zipFile.zip`)],
```
