### ISSUE TITLE
aws-synthetics: support syn-nodejs-puppeteer-8.0 runtime

### ISSUE THREAD

**Issue by jwilson-anonyome** [aws/aws-cdk#30850]
### Describe the feature

https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Synthetics_Library_nodejs_puppeteer.html confirms that Synthetics runtime "syn-nodejs-puppeteer-8.0" is available. 

https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-synthetics/lib/runtime.ts only has up to 7.0

Can we support this in CDK please? Thanks.

### Use Case

Need to be able to use latest runtimes

### Proposed Solution

Update aws-cdk-lib/aws-synthetics/lib/runtime.ts

### Other Information

Previous PR for runtime updating: https://github.com/aws/aws-cdk/pull/29446

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.148.0

### Environment details (OS name and version, etc.)

n/a

**Comment by ashishdhingra** [comment]
Indeed, [syn-nodejs-puppeteer-8.0](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Synthetics_Library_nodejs_puppeteer.html#CloudWatch_Synthetics_runtimeversion-nodejs-puppeteer-8.0) is the newest version supported. Below screenshot from AWS CloudWatch console also confirms the same:
![Screenshot 2024-07-15 at 10 09 42 AM](https://github.com/user-attachments/assets/b3bcd12a-a49f-4660-a761-a0f369e0211c)
