### ISSUE TITLE
codebuild: ARM images supports all compute types, incorrect validation

### ISSUE THREAD

**Issue by Samrose-Ahmed** [aws/aws-cdk#30869]
### Describe the bug

Theres is an incorrect validation here: https://github.com/aws/aws-cdk/blob/9bd92da62d8c4594a11f4ab078f07b8c20762329/packages/aws-cdk-lib/aws-codebuild/lib/linux-arm-build-image.ts#L115 that results in error like `ARM images only support ComputeTypes 'BUILD_GENERAL1_SMALL' and 'BUILD_GENERAL1_LARGE' - 'BUILD_GENERAL1_XLARGE' was given
    at PipelineProject.renderEnvironment`. 

ARM images support all compute types, this is probably outdated.

### Expected Behavior

Should support all compute types.

### Current Behavior

Only supports small and large.

### Reproduction Steps

create codebuild arm project with compute type XLARGE

### Possible Solution

Just remove this code:

https://github.com/aws/aws-cdk/blob/9bd92da62d8c4594a11f4ab078f07b8c20762329/packages/aws-cdk-lib/aws-codebuild/lib/linux-arm-build-image.ts#L112-L116

### CDK CLI Version

2.149.0 (build c8e5924)

### Node.js Version

18

### OS

macos

### Language

TypeScript

**Comment by scanlonp** [comment]
Looks like as of [last week](https://docs.aws.amazon.com/codebuild/latest/userguide/history.html) ARM expanded to medium Xlarge and 2Xlarge compute types! See the [table here](https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-compute-types.html). 

We should remove the validation, thanks for the call out @Samrose-Ahmed!

Side note: it looks like [reserved capacity fleets](https://docs.aws.amazon.com/codebuild/latest/userguide/fleets.html) still have ARM compute types limited to small and large. Best to remove this validation to enable use, but something to keep in mind.

**Comment by PeterEckIII** [comment]
I'd like to work on this issue. 

I've removed the code from the "Possible Solution" step. I've also removed the comment above it, suggesting the computeType must be `ComputeType.SMALL` or `ComputeType.LARGE`. 

How should I be handling the TS warning now that the `buildEnvironment` variable is no longer being utilized in the `validate` method?

**Comment by scanlonp** [comment]
@PeterEckIII, looks like that validate function is specific to ARM build images. Since there are now no restrictions on ARM compute types, the validation may not be necessary at all.

**Comment by PeterEckIII** [comment]
Thanks @scanlonp, just created https://github.com/aws/aws-cdk/pull/30879 for this. Please let me know of any feedback.

**Comment by PeterEckIII** [comment]
@scanlonp, I amended my commit with some changes to test files, but it's still denying my PR due to no integration files being changed. I'm looking for any potentially affected files but am slow moving at the moment. If you know any integration files off the top of your head that I can adjust I will make that change. Otherwise, I'll keep digging. Thanks
