### ISSUE TITLE
❗️NOTICE (lambda): SnapStart for Java functions using ARM64

### ISSUE THREAD

**Issue by Leo10Gama** [aws/aws-cdk#30899]
### Describe the feature

The new feature is currently being worked on in [this PR](https://github.com/aws/aws-cdk/pull/30898). In the meantime, you can access the SnapStart feature using the following workaround:

```typescript
    const fn = new lambda.Function(this, 'Func', {
      runtime: lambda.Runtime.JAVA_21,
      handler: 'example.Handler',
      architecture: lambda.Architecture.ARM_64,
      code: lambda.Code.fromAsset(path.join(__dirname, '../../lambda/example.jar')),
      memorySize: 256,
    });

    // Workaround: Add SnapStart configuration like this:
    (fn.node.defaultChild as lambda.CfnFunction).addPropertyOverride('SnapStart', {
      ApplyOn: 'PublishedVersions',
    });
```

### CDK version used

2.149.0

### Environment details (OS name and version, etc.)

All

**Comment by ashishdhingra** [comment]
PR https://github.com/aws/aws-cdk/pull/30898 pending review.
