### ISSUE TITLE
'Bootstrap required' error message has wrong sample command

### ISSUE THREAD

**Issue by clareliguori** [aws/aws-cdk#3091]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/awslabs/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*

Running cdk deploy against a stack with a custom resource:
```
<stack name> failed: Error: This stack uses assets, so the toolkit stack must be deployed to the environment (Run "cdk bootstrap aws://123456789012/us-east-1")
This stack uses assets, so the toolkit stack must be deployed to the environment (Run "cdk bootstrap aws://123456789012/us-east-1")
```

Following the instructions and running `cdk bootstrap aws://123456789012/us-east-1` results in:
```
Expected environment name in format '<account>/<region>', got: aws://123456789012/us-east-1
```

* **What is the expected behavior (or behavior of feature suggested)?**

Error gives sample cdk bootstrap command in expected format.

* **What is the motivation / use case for changing the behavior or adding this feature?**

Useful error message

* **Please tell us about your environment:**
  
  - CDK CLI Version: 0.36.0
  - Module Version: 0.36.0
  - OS: Ubuntu
  - Language: Typescript

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

**Comment by ozbillwang** [comment]
Thanks, @clareliguori 

I got similar error when run `cdk deploy`, but with `unknown-account/unknown-region`

>Error: This stack uses assets, so the toolkit stack must be deployed to the environment (Run "cdk bootstrap aws://unknown-account/unknown-region")

After read your notes, I realised on how to run `cdk bootstrap`. 

```
 $ cdk bootstrap aws://1234/ap-southeast-2
 ⏳  Bootstrapping environment aws://1234/ap-southeast-2...
CDKToolkit: creating CloudFormation changeset...
 0/2 | 11:47:23 PM | CREATE_IN_PROGRESS   | AWS::S3::Bucket | StagingBucket
 0/2 | 11:47:24 PM | CREATE_IN_PROGRESS   | AWS::S3::Bucket | StagingBucket Resource creation Initiated
 1/2 | 11:47:46 PM | CREATE_COMPLETE      | AWS::S3::Bucket | StagingBucket
 2/2 | 11:47:48 PM | CREATE_COMPLETE      | AWS::CloudFormation::Stack | CDKToolkit
 ✅  Environment aws://1234/ap-southeast-2 bootstrapped.
```

After that, I can run `cdk deploy` successfully

**Comment by vegetabill** [comment]
I encountered the same issue. I think the error message is fine but it makes it seem like the AWS account and region are not configured even when they are.

I would just update the error message, if anything.

It informs the user how to fix, namely `cdk bootstrap`

(using named profiles if that is why it appears as unknown in the msg)

**Comment by shivlaks** [comment]
@vegetabill what would a more helpful message look like. Fix the command to just `Run cdk bootstrap` and link to it's documentation?

@Jerry-AWS - This is probably also an opportunity for us to improve the documentation around bootstrap, what it does, why it's necessary and how the CDK uses it. The documentation likely hasn't been touched in a long time.

**Comment by Jerry-AWS** [comment]
@shivlaks I have a bit on bootstrap in the new troubleshooting topic I'm working on, but I should add it to the Getting Started topic as well. (Even though the example used in Getting Started doesn't need the bootstrap.)

**Comment by shivlaks** [comment]
realized this was already addressed through #3599

**Comment by mattiLeBlanc** [comment]
You can also do `cdk bootstrap --profile [aws profile name]` if you have stored your credentials under the `~/.aws` folder.

**Comment by lachlanvass-srg** [comment]
For the benefit of whoever else finds this, I came across this issue from the "imageScanOnPush" parameter of ecr.Repository

**Comment by simsek97** [comment]
Running `cdk bootstrap` before `cdk deploy` should be enough.
But I agree, the error message is a bit confusing.
