### ISSUE TITLE
AwsCustomResource: AwsSdkCall implementations don't support empty parameters for some APIs

### ISSUE THREAD

**Issue by ricmattj** [aws/aws-cdk#30943]
### Describe the bug

The SES API has an endpoint to set an active receipt rule set.  To deactivate all rulesets you need to call the set-active-receipt-rule-set API and not provide a rule-set-name

CLI example:
```sh
# Set active receipt rule
aws ses set-active-receipt-rule-set --rule-set-name my-rule

# Deactivate all receipt rules
aws ses set-active-receipt-rule-set
```

When creating a receipt rule set in CDK it is recommended to use an AwsCustomResource, as setting a ruleset active in Cloud Formation is not supported.  

Example:
```sh
const setActiveReceiptRuleSetSdkCall: AwsSdkCall = {
      service: "SES",
      action: "setActiveReceiptRuleSet",
      physicalResourceId: PhysicalResourceId.of("SesCustomResource"),
      parameters: {
        RuleSetName: sesRuleSet.receiptRuleSetName,
      },
    };

    new AwsCustomResource(this, "SetActiveReceiptRuleSetCustomResource", {
      onCreate: setActiveReceiptRuleSetSdkCall,
     });
```

## The Problem
Attempting to implement the onDelete handler for this consistently gives an error:

Sample Code:
```sh
const setInactiveReceiptRuleSetSdkCall: AwsSdkCall = {
      service: "SES",
      action: "setActiveReceiptRuleSet",
    };

    new AwsCustomResource(this, "SetActiveReceiptRuleSetCustomResource", {
      ...
      onDelete: setInactiveReceiptRuleSetSdkCall,
     });
```

> Received response status [FAILED] from custom resource. Message returned: ruleSetName must not be empty 

This error is consistent with the following permutations:
* Undefined parameters
* Empty parameters
* Null parameters
* Null RuleSetName

It seems that the AwsSdkCall expects a RuleSetName regardless and it's impossible to unset it via an AwsSdkCall

### Expected Behavior

AwsCustomResource objects with AwsSdkCall implementations will only pass in parameters that are explicitly defined in the parameters object

### Current Behavior

Certain parameters seem to be hard-coded 

### Reproduction Steps

1. Create a ReceiptRuleSet and an AwsCustomResource to activate and deactivate the ruleset
```typescript
 // Create the Receipt Rule Set
    const sesRuleSet = new ReceiptRuleSet(this, "SESRuleSet", {
      rules: [
        {
          recipients: ["foobar@anycompany.com"],
          actions: [
            new S3({
              bucket,
              objectKeyPrefix: "foo/",
            }),
          ],
        },
      ],
    });

    /*
     * Enable the Receipt Rule Set - NOTE: this is not supported with bare CloudFormation calls, so this is a custom resource to activate the rule set after creation
     */
    const setActiveReceiptRuleSetSdkCall: AwsSdkCall = {
      service: "SES",
      action: "setActiveReceiptRuleSet",
      physicalResourceId: PhysicalResourceId.of("SesCustomResource"),
      parameters: {
        RuleSetName: sesRuleSet.receiptRuleSetName,
      },
    };

    const setInactiveReceiptRuleSetSdkCall: AwsSdkCall = {
      service: "SES",
      action: "setActiveReceiptRuleSet",
    };

    new AwsCustomResource(this, "SetActiveReceiptRuleSetCustomResource", {
      onCreate: setActiveReceiptRuleSetSdkCall,
      onUpdate: setActiveReceiptRuleSetSdkCall,
      onDelete: setInactiveReceiptRuleSetSdkCall,
      logRetention: RetentionDays.ONE_WEEK,
      installLatestAwsSdk: true,
      policy: AwsCustomResourcePolicy.fromStatements([
        new PolicyStatement({
          sid: "CanActivateSESRuleSet",
          effect: Effect.ALLOW,
          actions: ["ses:SetActiveReceiptRuleSet"],
          resources: ["*"],
        }),
      ]),
    });
```

2. CDK Deploy
3. CDK Destroy

### CDK CLI Version

2.150.0

### Node.js Version

v20.15.1

### OS

MacOS Ventura 13.6.7

### Language

TypeScript

**Comment by ashishdhingra** [comment]
@ricmattj Good morning. Thanks for reporting the issue. Upon quickly checking [SES:: SetActiveReceiptRuleSet](https://docs.aws.amazon.com/ses/latest/APIReference/API_SetActiveReceiptRuleSet.html), for `RuleSetName` property, setting value to `null` disables all email receiving. Could you please check if you are able to explicitly set `RuleSetName` to `null` in your API call? CDK uses AWS JavaScript SDK behind the scenes, if this doesn't work, then most likely it is an issue with AWS JAvaScript SDK.

Thanks,
Ashish
