### ISSUE TITLE
AWS Step Functions Tasks - HttpInvoke: Bug in code example

### ISSUE THREAD

**Issue by DennisTraub** [aws/aws-cdk#30940]
### Describe the issue

The value passed into the `api_endpoint` parameter in the code example does not work and leads to an error. It doesn't accept the full url, it must be the path, relative to the value in `apiRoot`.

```python
// Is:

tasks.HttpInvoke(self, "Invoke HTTP API",
    api_root="https://api.example.com",
    api_endpoint=sfn.TaskInput.from_text("https://api.example.com/path/to/resource"),
    ...
)

// Should be:

tasks.HttpInvoke(self, "Invoke HTTP API",
    api_root="https://api.example.com",
    api_endpoint=sfn.TaskInput.from_text("path/to/resource"),
    ...
)
```

### Links

[API Reference / aws_cdk.aws_stepfunctions_tasks / HttpInvoke](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_stepfunctions_tasks/HttpInvoke.html)

**Comment by ashishdhingra** [comment]
Example appears to be incorrect. The documentation states that api_endpoint ([TaskInput](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_stepfunctions/TaskInput.html#aws_cdk.aws_stepfunctions.TaskInput)) is `The API endpoint to call, relative to apiRoot`.
