### ISSUE TITLE
aws-alb-lambda: Does not allow ApplicationLoadBalancerProps

### ISSUE THREAD

**Issue by darrenflannerypoppulo** [aws/aws-cdk#30951]
### Describe the bug

On the [aws-alb-lambda](https://docs.aws.amazon.com/solutions/latest/constructs/aws-alb-lambda.html) it says you can specify ApplicationLoadBalancerProps, but says the following **`This cannot specify a VPC, it will use the VPC in existingVpc or the VPC created by the construct.`** . 

I tried to all ApplicationLoadBalancerProps without a vpc so I can specify what subnets I want the ALB to be created in, but I get an error, saying 'vpc' is a required field. 

When I add a vpc, the same as the existing_vpc property. I also get an error: `Specify any existing VPC at the construct level, not within loadBalancerProps.`

My Code:

```
alb_to_lambda = AlbToLambda(
            self,
            f"{STACK_PREFIX}{self.stack_config.function_name}AlbToLambda",
            lambda_function_props=FunctionProps(
                runtime=Runtime.PYTHON_3_9,
                handler=self.stack_config.function_handler,
                code=get_lambda_code(self.stack_config.lambda_code_path),
                function_name=f"{STACK_PREFIX}{self.stack_config.function_name}",
                description=f"{STACK_PREFIX}{self.stack_config.function_description}",
                log_retention=RetentionDays.FIVE_DAYS,
                timeout=Duration.seconds(30),
                environment=self.stack_config.environment,
                dead_letter_queue=dlq,
                memory_size=self.stack_config.memory_size,
            ),
            target_props=elbv2.ApplicationTargetGroupProps(
                target_group_name=f"{STACK_PREFIX}{self.stack_config.function_name}TG",
                health_check=elbv2.HealthCheck(
                    path="/healthcheck", interval=Duration.minutes(5), enabled=True
                ),
            ),
            existing_vpc=vpc,
            listener_props=elbv2.BaseApplicationListenerProps(
                certificates=[certificate],
            ),
            load_balancer_props=elbv2.ApplicationLoadBalancerProps(
                vpc_subnets=subnets,
            ),
            public_api=False,
        )
```

### Expected Behavior

I can add ApplicationLoadBalancerProps to AlbToLambda construct

### Current Behavior

I cannot add ApplicationLoadBalancerProps to AlbToLambda construct without getting an error

### Reproduction Steps

Try to deploy an AlbToLambda construct using ApplicationLoadBalancerProps as a property

### CDK CLI Version

2.143

### Node.js Version

n/a

### OS

Linux

### Language

Python

**Comment by ashishdhingra** [comment]
`aws-alb-lambda` is part of https://github.com/awslabs/aws-solutions-constructs repository. This issue should be transferred to that repository.
