### ISSUE TITLE
(aws-ses): ConfigurationSet.reputationMetrics incorrect default value

### ISSUE THREAD

**Issue by greg5123334** [aws/aws-cdk#30968]
### Describe the issue

```ses.ConfigurationSet.reputationMetrics``` states the default value for this property is ```false``` whereas in reality it defaults to ```true```.

### Links

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ses.ConfigurationSet.html#reputationmetrics

**Comment by ashishdhingra** [comment]
Reproducible using simple code `new ses.ConfigurationSet(this, 'testconfigset');` which generates the following CloudFormation template:
```TypeScript
Resources:
  testconfigsetC2A896EF:
    Type: AWS::SES::ConfigurationSet
    Metadata:
      aws:cdk:path: CdktestStack/testconfigset/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/12KQQ6DIBAA3+IdtmJ66dkf6AMaCqtZtEvCgh6Mf29IPXmaZGY6MM8XtI3dRTu/6JU+cIzZukXZXd6CAkcfeaK5JJsp8ohZ9RPf3VnlgBJLcngNnmo8FUePEOSxdS0YA6YJQqRT4UxfhOHPH4K+9g6JAAAA
    Metadata:
      aws:cdk:path: CdktestStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
...
```
Deploying it using `cdk deploy` command creates configuration set with `Reputation metrics` as enabled:
![Screenshot 2024-07-29 at 4 10 15 PM](https://github.com/user-attachments/assets/0fa975bd-000d-4cb2-8f53-cac33d4a8d63)
