### ISSUE TITLE
vpc: add AWS Resource Access Manager VPC endpoints

### ISSUE THREAD

**Issue by dontirun** [aws/aws-cdk#30975]
### Describe the feature

Add the [RAM VPC endpoints](https://docs.aws.amazon.com/general/latest/gr/ram.html) to `InterfaceVpcEndpointAwsService`

### Use Case

I'd like to access RAM from a VPC endpoint

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.144.0 (build 5fb15bc)

### Environment details (OS name and version, etc.)

mac os

**Comment by khushail** [comment]
Thanks for submitting the PR @dontirun

**Comment by dontirun** [comment]
My mistake the ram vpc endpoint does not exist
