### ISSUE TITLE
kms: Add support for KEY_AGREEMENT to KeyUsage in KMS key

### ISSUE THREAD

**Issue by lohn** [aws/aws-cdk#30989]
### Describe the feature

Add support for KEY_AGREEMENT to KeyUsage when creating KMS keys.

### Use Case

To create KMS keys for shared secret derivation using CDK, enabling the use of the new DeriveSharedSecret API.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.150.0

### Environment details (OS name and version, etc.)

macOS Sonoma 14.5

**Comment by khushail** [comment]
Hi @lohn , thanks for requesting this. I see this is supported by Cloudformation - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kms-key.html#cfn-kms-key-keyusage, so CDK is good to provide support for the requested feature-

https://github.com/aws/aws-cdk/blob/3f930279513b0f168333c6f6038b8ad81b99b7e1/packages/aws-cdk-lib/aws-kms/lib/key.ts#L392


Marking this as P2 for the contribution from the community.
