### ISSUE TITLE
aws-cdk-lib/aws-lambda: Add allowAllIpv6Outbound option to lambda function props

### ISSUE THREAD

**Issue by mawallace** [aws/aws-cdk#30994]
### Describe the feature

There is already an `allowAllOutbound` option. It confused my that this did not actually allow all outbound (only all IPv4 outbound), given that there was no corresponding IPv6 option. I think adding the option would make this more clear. It would also mirror the options on security group props.

### Use Case

It's nice to be able to define a lambda function without explicitly setting up security groups. This option would allow me to do this when I need to allow outbound IPv6 traffic.

### Proposed Solution

It looks like we'd just need to pipe this option through to the security group that gets created (it's already an option on security groups).

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

3.616

### Environment details (OS name and version, etc.)

Ubuntu 22.04.4

**Comment by ashishdhingra** [comment]
[SecurityGroupProps](https://github.com/aws/aws-cdk/blob/9295a85a8fb893d7f5eae06108b68df864096c4c/packages/aws-cdk-lib/aws-ec2/lib/security-group.ts#L272) supports `allowAllIpv6Outbound` property. The existing Lambda [FunctionOptions](https://github.com/aws/aws-cdk/blob/9295a85a8fb893d7f5eae06108b68df864096c4c/packages/aws-cdk-lib/aws-lambda/lib/function.ts#L146C18-L146C33) only supports [allowAllOutbound](https://github.com/aws/aws-cdk/blob/9295a85a8fb893d7f5eae06108b68df864096c4c/packages/aws-cdk-lib/aws-lambda/lib/function.ts#L296C12-L296C28), which is used in [configureVpc()](https://github.com/aws/aws-cdk/blob/9295a85a8fb893d7f5eae06108b68df864096c4c/packages/aws-cdk-lib/aws-lambda/lib/function.ts#L1464C11-L1464C23) while creating a new `SecurityGroup` [here](https://github.com/aws/aws-cdk/blob/9295a85a8fb893d7f5eae06108b68df864096c4c/packages/aws-cdk-lib/aws-lambda/lib/function.ts#L1503).
