### ISSUE TITLE
SecretsManager: is there feature to set a day of week rather that specifying number

### ISSUE THREAD

**Issue by PreranaAmirapu** [aws/aws-cdk#31002]
### Describe the bug

        self.harness_secret.add_rotation_schedule(
            "RotationSchedule", rotation_lambda=rotate_delegates_function, automatically_after=Duration.days(7)
        )

this is the code I have written where it rotates after 7 days , but i want my secret to rotate on sunday only. I have tried below code but it is not working 

        cfn_rotation_schedule = secretsmanager.CfnRotationSchedule(
            self, "RotationSchedule",
            secret_id=self.example_secret.secret_arn,
            rotation_lambda_arn=rotate_delegates_function.function_arn,
            rotation_rules=secretsmanager.CfnRotationSchedule.RotationRulesProperty(
                schedule_expression="cron(0 12 ? * SUN *)",
            )
        )

### Expected Behavior

rotate on every sunday

### Current Behavior

      cfn_rotation_schedule = secretsmanager.CfnRotationSchedule(
            self, "RotationSchedule",
            secret_id=self.example_secret.secret_arn,
            rotation_lambda_arn=rotate_delegates_function.function_arn,
            rotation_rules=secretsmanager.CfnRotationSchedule.RotationRulesProperty(
                schedule_expression="cron(0 12 ? * SUN *)",
            )
        )

it is not throwing error but the lambda is not attaching to the secret

### Reproduction Steps

-

### CDK CLI Version

2.147.0

### Node.js Version

v22.4.1

### OS

mac

### Language

Python

**Comment by khushail** [comment]
Hey @PreranaAmirapu , thanks for reaching out. Have you tried giving cron expression like this  (this is typescript code)-

```ts
rotationRules:{
        scheduleExpression: "cron(0 8 * * 0)",
      }
 ```
 this cron expression means the scheduler will run Every sunday at 8:00am
 
 Let us know if this works!

**Comment by PreranaAmirapu** [comment]
my code:  
  
        rotate_delegates_function.add_permission("SecretRotationPermission",
                                                 principal=iam.ServicePrincipal("secretsmanager.amazonaws.com"),
                                                 action="lambda:InvokeFunction",
                                                 source_arn=self.harness_secret.secret_arn,
                                                 )

        secretsmanager.CfnRotationSchedule(
            self, "RotationSchedule",
            secret_id=self.harness_secret.secret_arn,
            rotation_lambda_arn=rotate_delegates_function.function_arn,
            rotation_rules=secretsmanager.CfnRotationSchedule.RotationRulesProperty(
                schedule_expression="cron(0 12 ? * SUN *)",
            )
        )
        
        
    error:
    Secrets Manager cannot invoke the specified Lambda function. Ensure that the function policy grants access to the principal secretsmanager.amaz
onaws.com. (Service: AWSSecretsManager; Status Code: 400; Error Code: AccessDeniedException; Request ID: 63a6dea7-0f5c-4294-8db9-8ff9652d85d9;
Proxy: null)

**Comment by PreranaAmirapu** [comment]
<img width="1298" alt="Screenshot 2024-08-02 at 9 44 32 PM" src="https://github.com/user-attachments/assets/1e32d7b1-12dc-4d92-8149-a8fa1acb30af">

the permission is added I guess

**Comment by khushail** [comment]
@PreranaAmirapu , so looks like the code is working ? right ?

**Comment by PreranaAmirapu** [comment]
I'm getting this error
Secrets Manager cannot invoke the specified Lambda function. Ensure that the function policy grants access to the principal secretsmanager.amaz
onaws.com. (Service: AWSSecretsManager; Status Code: 400; Error Code: AccessDeniedException; Request ID: 63a6dea7-0f5c-4294-8db9-8ff9652d85d9;
Proxy: null)

**Comment by khushail** [comment]
@PreranaAmirapu , this error only indicates that function policy needs to be added which is added in the given code. 
These are the alternatives you could try -
1. Could you please specify the complete arn in the Source_Arn, instead of using a reference. 
2. run this command in terminal - 
```cmd
aws lambda add-permission 
          --function-name secrets_manager 
          --principal secretsmanager.amazonaws.com 
          --action lambda:InvokeFunction 
          --statement-id SecretsManagerAccess
```

Replace function name with your lambda function name.

Let me know if this works
