### ISSUE TITLE
(aws-events-targets): Add scheduling a Redshift query to "Event Targets for Amazon EventBridge"

### ISSUE THREAD

**Issue by Rizxcviii** [aws/aws-cdk#31017]
### Describe the feature

The event targets module has implemented a couple of event targets but is missing some, one of which is scheduling a Redshift query.

### Use Case

Schedule RedShift queries.

### Proposed Solution

Cloudformation already allows for this, here's my current implementation which isn't yet very CDKish:

```ts
    const redshiftClusterArn = ...

    const redshiftRole = new iam.Role(this, 'RedshiftEventRole', {
      assumedBy: new iam.CompositePrincipal(new iam.ServicePrincipal('events.amazonaws.com'), new iam.AccountRootPrincipal()),
      managedPolicies: [iam.ManagedPolicy.fromAwsManagedPolicyName('AmazonRedshiftDataFullAccess')],
    });

    redshiftRole.addToPolicy(
      new iam.PolicyStatement({
        resources: [redshiftClusterArn],
        actions: [
          'sts:AssumeRole',
        ],
      }),
    );

    const redshiftSecret = ...
    redshiftSecret.grantRead(redshiftRole);

    const loader = new events.Rule(this, 'eventRule', {
      schedule: events.Schedule.expression('cron(2 */1 * * ? *)'),
    });

    const cfnLoader = loader.node.defaultChild as events.CfnRule;
    cfnLoader.targets = [{
      arn: `${redshiftClusterArn}`,
      roleArn: redshiftRole.roleArn,
      id: 'loader',
      redshiftDataParameters: {
        database: 'databasename',
        sql: 'call myprocedure()',
        secretManagerArn: redshiftSecret.secretArn,
      },
    }];
```

### Other Information

Originally posted by @dirkgomez in https://github.com/aws/aws-cdk/issues/15712

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.151.0

### Environment details (OS name and version, etc.)

Windows 11

**Comment by Rizxcviii** [comment]
@rix0rrr, I implemented your change that was recommended on the previous ticket

**Comment by ashishdhingra** [comment]
[AWS::Events::Rule Target](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-events-rule-target.html) does mention support for [RedshiftDataParameters](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-events-rule-redshiftdataparameters.html).

@Rizxcviii Thanks for opening this feature request and PR contribution.

**Comment by Rizxcviii** [comment]
Hi @ashishdhingra, the original issue was marked as p1, this is the same issue as before
