### ISSUE TITLE
lambda: default architecture X86_64 isn't used for cross-platform docker builds

### ISSUE THREAD

**Issue by tabrezm** [aws/aws-cdk#31048]
### Describe the bug

The current documented behavior for the `architecture` prop on `lambda_.DockerImageFunction` is:
```
architecture: The system architectures compatible with this lambda function. Default: Architecture.X86_64
```

However, I found running `cdk deploy` on my Mac would not target amd64. This results in the following error message when invoking the deployed Lambda function:
```
Error: fork/exec /lambda-entrypoint.sh: exec format error Runtime.InvalidEntrypoint
```

I was able to resolve this by explicitly setting:
```
lambda_.DockerImageFunction(self, ..., architecture=lambda_.Architecture.X86_64)
```

Another quirk I found was that specifying `--platform` in `build_args` is silently ignored. You can only specify this setting via the `platform` property.

```
code=lambda_.DockerImageCode.from_image_asset(
    directory=...,
    build_args={"--platform": "linux/amd64"},  # doesn't work
    platform=ecr_assets.Platform.LINUX_X86_64,  # works
),
```

### Expected Behavior

1. The `lambda_.DockerImageFunction()` default architecture of `lambda_.Architecture.X86_64` is passed to docker build
2. Allow passing `--platform` in `build_args` or raise an error

### Current Behavior

The default value either seems to not be set correctly, or it's not passed correctly to docker build.

### Reproduction Steps

Follow the hello world example [here](https://docs.aws.amazon.com/lambda/latest/dg/python-image.html).

```
lambda_.DockerImageFunction(
            self,
            "HelloWorldLambda",
            code=lambda_.DockerImageCode.from_image_asset(
                directory=...,
                # build_args={"--platform": "linux/amd64"},
                # platform=ecr_assets.DockerPlatform.LINUX_X86_64,
            ),
            # architecture=lambda_.Architecture.X86_64,
        )
```

### CDK CLI Version

2.151.0 (build b8289e2)

### Node.js Version

v20.16.0

### OS

macOS

### Language

Python

**Comment by pahud** [comment]
Looks like you are trying to build a lambda docker-compatible function of X86_64 architecture from a ARM64 Mac laptop.

The `architecture` of DockerImageFunction is used for:

1. pass correct architecture for the L1 CfnFunction props, which defaults to X86_64.
2. pass additional `--platform` argument for docker build if specified, especially for cross-platform building(per [this PR](https://github.com/aws/aws-cdk/commit/48178ac6c4d4d3bb6d85561860d552502a4ead01)).

Can you just specify `architecture` for `DockerImageFunction` and let me know if it works for you?

**Comment by tabrezm** [comment]
Thanks for your reply.

> Can you just specify `architecture` for `DockerImageFunction` and let me know if it works for you? I guess we probably need to improve the doc with another PR.

Yes, I confirmed this works here (I didn't have any props on `from_image_asset` specified at the time):
> I was able to resolve this by explicitly setting:
> ```
> lambda_.DockerImageFunction(self, ..., architecture=lambda_.Architecture.X86_64)
> ```

Is that what you were asking about?

**Comment by pahud** [comment]
Yes in your case as I presumed `architecture` would be the only required option. You don't need to specify `--platform` because behind the scene according to this [PR](https://github.com/aws/aws-cdk/commit/48178ac6c4d4d3bb6d85561860d552502a4ead01), it has pass the platform argument all the way to docker build.

I'm glad this works for you. I will cut a tiny PR to improve the doc.

Did I miss anything else?

**Comment by tabrezm** [comment]
> Yes in your case as I presumed `architecture` would be the only required option. You don't need to specify `--platform` because behind the scene according to this [PR](https://github.com/aws/aws-cdk/commit/48178ac6c4d4d3bb6d85561860d552502a4ead01), it would pass the platform argument all the way to docker build.
> 
> I'm glad this works for you. I will cut a tiny PR to improve the doc.
> 
> Did I miss anything else?

It's more of a nit, but having better fail-fast validation here would've be helpful since there are a few AWS samples still out there that have `build_args={"--platform": "linux/amd64"}` which seem to be superseded with the newer(?) explicit `platform` prop:
> 2. Allow passing --platform in build_args or raise an error

**Comment by pahud** [comment]
Yes we need to address them with clearer doc. For this issue, I will submit a PR shortly. If you see other similar issues that deserve more clarifying or even a code fix, please raise a new issue for us. Thank you.
