### ISSUE TITLE
❗ NOTICE sagemaker: domains fail to deploy in govcloud regions

### ISSUE THREAD

**Issue by RossMeyers** [aws/aws-cdk#31054]
### Status

Investigating (Default)

### What is the issue?

When trying to deploy a new sagemaker domain into aws-gov-west-1 or aws-gov-east-1, I get an `Internal Error` message. I confirmed that deploying the domain as is in us-east-1 works without issue. 

### Error message

```console
Internal Failure
```

### What is the impact?

I cannot deploy sagemaker domains into either of the Govcloud Regions.

### Workaround

Console deployments work. 

### Who is affected?

Typescript cdk users. 

### How do I resolve this?

Deploy via the console.

**Comment by QuantumNeuralCoder** [comment]
Lowering severity as this doesnt fit our criteria. We will triage this issue and come back. Please confirm if this was a regression.
