### ISSUE TITLE
feature request: option to invalidate CloudFront distribution for s3-deployment

### ISSUE THREAD

**Issue by clareliguori** [aws/aws-cdk#3106]
* **I'm submitting a ...**
  - [ ] :beetle: bug report
  - [x] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/awslabs/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*

s3-deployment can't be easily used for many static websites, because a CloudFront distribution needs to be invalidated after new files are uploaded to S3 (assuming you want the new files to show up immediately to users after a deployment, and not wait for the edge caches to expire).

* **What is the expected behavior (or behavior of feature suggested)?**

Provide an option for passing in a cloudfront.IDistribution and a list of invalidation paths.  The s3-deployment Lambda function should create an invalidation, and then wait for that invalidation to complete.

* **What is the motivation / use case for changing the behavior or adding this feature?**

Static websites

**Comment by clareliguori** [comment]
Example addition to BucketDeploymentProps:
```
  /**
   * The CloudFront distribution using the destination bucket as an origin.
   * Files in the distribution's edge caches will be invalidated after
   * files are uploaded to the destination bucket.
   *
   * @default No invalidation occurs
   */
  readonly distribution?: cloudfront.IDistribution;

  /**
   * The file paths to invalidate in the CloudFront distribution.
   *
   * @default All files under the destination bucket key prefix will be invalidated.
   */
  readonly distributionPaths?: string[];

```

**Comment by NGL321** [comment]
Hi Clare!

Thank you for posting. This definitely sounds like something worth looking into.

While we work on getting the APIs aligned with our guidelines, we are pausing work on most community feature-requests. Please continue to report issues and submit feature requests, of course. 

We expect to get back to work on community features within a few weeks.

**Comment by eladb** [comment]
+1 totally agree

Assets now expose both source hash (synth-time) and artifact hash (deploy-time) which can be used to automatically invalidate based on source changes.

**Comment by hoegertn** [comment]
If you like, I can have a look at this. I need it for my current project. @eladb @clareliguori

**Comment by clareliguori** [comment]
I started on this, but got pulled off to something else while trying to figure out unit tests and Python SDK mocking for the deployment Lambda function.  I also have not looked into comparing the source hash and artifact hash before doing invalidation.  Happy for someone to take over:
https://github.com/clareliguori/aws-cdk/commit/047d654943756c8b07494f9b792a88b5d1e8e5eb

**Comment by hoegertn** [comment]
This looks like a very good start. I am happy to take over.

**Comment by hoegertn** [comment]
I think this can be closed

**Comment by clareliguori** [comment]
Fixed by https://github.com/aws/aws-cdk/pull/3213
