### ISSUE TITLE
neptune: specify port for the cluster

### ISSUE THREAD

**Issue by badmintoncryer** [aws/aws-cdk#31074]
### Describe the feature

Specify port number of the Neptune cluster.

### Use Case

We can configure the port number of Neptune cluster but CDK L2 construct cannot configure this.

### Proposed Solution

Add `port` property to `DatabaseClusterProps` and set DBPort to the `port` value.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-neptune-dbcluster.html#cfn-neptune-dbcluster-dbport

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.150.0

### Environment details (OS name and version, etc.)

irrelevant

**Comment by ashishdhingra** [comment]
Looking at [DatabaseClusterProps](https://github.com/aws/aws-cdk/blob/501a4f1a81983992ec04a1acbed84d09e9470f8c/packages/%40aws-cdk/aws-neptune-alpha/lib/cluster.ts#L130), there appears to be no property that maps to `DBPort`. However, per [AWS::Neptune::DBCluster](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-neptune-dbcluster.html#cfn-neptune-dbcluster-dbport) appears to be supported property (there is also `Port` property, however, there is a note that `This property will soon be deprecated. Please update existing templates to use the new DBPort property that has the same functionality.`).

@badmintoncryer Thanks for submitting the feature request. Kindly note that [aws-neptune-alpha](https://github.com/aws/aws-cdk/tree/main/packages/%40aws-cdk/aws-neptune-alpha) is an experimental L2 construct as of now, so we encourage community to submit updates to this construct package. Feel free to submit PR that could be reviewed by the team.

Thanks,
Ashish
