### ISSUE TITLE
ec2: support for specify IPv6 address count for an instance

### ISSUE THREAD

**Issue by badmintoncryer** [aws/aws-cdk#31075]
### Describe the feature

Specify [Ipv6AddressCount property](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-instance.html#cfn-ec2-instance-ipv6addresscount) for EC2 instance.

### Use Case

We can not configure `ipv6AddressCount` property through EC2 instance L2 construct.

### Proposed Solution

Add `ipv6AddressCount` to `InstanceProps` and pass it to `CfnInstance.ipv6AddressCount` property.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.150.0

### Environment details (OS name and version, etc.)

irrelevant

**Comment by pahud** [comment]
Thank you for the PR @badmintoncryer !
