### ISSUE TITLE
rds: Support Postgres 16.4 minor version

### ISSUE THREAD

**Issue by arlampin** [aws/aws-cdk#31081]
### Describe the feature

Postgres 16.4 was released to RDS a few days ago and should be supported by CDK.

### Use Case

I would like to use 16.4 without constructing version manually.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.151.0

### Environment details (OS name and version, etc.)

N/A

**Comment by ashishdhingra** [comment]
Per [PostgreSQL version 16.4 on Amazon RDS](https://docs.aws.amazon.com/AmazonRDS/latest/PostgreSQLReleaseNotes/postgresql-versions.html#postgresql-versions-version164), PostgreSQL version 16.4 is now available on Amazon RDS. The change is to add this version to [PostgresEngineVersion](https://github.com/aws/aws-cdk/blob/501a4f1a81983992ec04a1acbed84d09e9470f8c/packages/aws-cdk-lib/aws-rds/lib/instance-engine.ts#L1014C14-L1014C35) class.

@arlampin Thanks for submitting feature request. Feel free to contribute PR that could be reviewed by the team.

Thanks,
Ashish
