### ISSUE TITLE
eks: Support latest AWS Load Balancer Controller versions

### ISSUE THREAD

**Issue by arlampin** [aws/aws-cdk#31082]
### Describe the feature

The latest controller version is 2.8.2, but CDK only supports versions up to 2.6.2. Also, both 2.7.x and 2.8.x have some changes to reference IAM policies, so using them is not just a matter of increasing version number.

### Use Case

I would like to use the latest controller version

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.151.0

### Environment details (OS name and version, etc.)

N/A

**Comment by ashishdhingra** [comment]
Per https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases and https://github.com/aws/eks-charts/blob/v0.0.178/stable/aws-load-balancer-controller/Chart.yaml, the latest ALB controller version as of now is `2.8.2`.

@arlampin Thanks for opening the feature request. Feel free to contribute PR that could be reviewed by the team.

Thanks,
Ashish

**Comment by pahud** [comment]
PR WIP https://github.com/aws/aws-cdk/pull/29959
