### ISSUE TITLE
aws_applicationautoscaling: Enable SageMaker high resolution predefined metric

### ISSUE THREAD

**Issue by shahks** [aws/aws-cdk#31113]
### Describe the feature

Add missing Predefined metrics for Application Autoscaling as per https://docs.aws.amazon.com/autoscaling/application/APIReference/API_PredefinedMetricSpecification.html

### Use Case

I would like to use autoscaling along with high resolution metrics for SageMaker endpoints.

### Proposed Solution

aws_cdk.aws_applicationautoscaling.PredefinedMetric.SAGEMAKER_INFERENCE_COMPONENT_CONCURRENT_REQUESTS_PER_COPY_HIGH_RESOLUTION enum value could be added.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.151.0

### Environment details (OS name and version, etc.)

N/A

**Comment by ashishdhingra** [comment]
@shahks Thanks for the PR contribution.
