### ISSUE TITLE
FSx: Enable file_system_type_version property for LustreFileSystem construct

### ISSUE THREAD

**Issue by LArkema** [aws/aws-cdk#31130]
### Describe the feature

When creating a FSx Lustre File System with the fsx.LustreFileSystem() construct, users should be able to specify the File System Version just like they are able to do with the CloudFormation construct (using the `file_system_type_version` property). Currently, CDK creates a 2.10 File System, which lacks many core FSx features.

At the very least, CDK should create the File System with the latest / recommended version. Per the [CloudFormation docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-fsx-filesystem.html#aws-resource-fsx-filesystem-return-values) "2.15 is supported by all Lustre deployment types and is recommended for all new file systems." Per the [Getting Started docs](https://docs.aws.amazon.com/fsx/latest/LustreGuide/getting-started.html#getting-started-step1), "All FSx for Lustre file systems are built on Lustre version 2.15 when created using the Amazon FSx console."

### Use Case

When creating a FSx filesystem with CDK, I want to be able to use the latest version of the File System, not be stuck with version 2.10. While I can get around the problem by using the [CfnFileSystem Resource](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_fsx.CfnFileSystem.html), CDK is much preferred. 

### Proposed Solution

Add a property to the CDK construct that maps to the equivalent property for the CloudFormation 'file_system_type_version' property, and/or update the default Lustre version to 2.15

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.152.0

### Environment details (OS name and version, etc.)

Various

**Comment by ashishdhingra** [comment]
[CfnFileSystem](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_fsx.CfnFileSystem.html) and [AWS::FSx::FileSystem](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-fsx-filesystem.html) appear to support `FileSystemTypeVersion`, which is not modeled in L2 [LustreFileSystem](https://github.com/aws/aws-cdk/blob/9acd5288b2b9a4d72dac199d472a42b5590a916e/packages/aws-cdk-lib/aws-fsx/lib/lustre-file-system.ts#L197C14-L197C30) construct.

@LArkema Thanks for opening the issue. Feel free to contribute PR, if possible, that could be reviewed by the team.

**Comment by rvencu** [comment]
this is bad, for instance RHEL 9.x is not compatible with version 2.10
