### ISSUE TITLE
codebuild: Add support for MacOS

### ISSUE THREAD

**Issue by alanxluc** [aws/aws-cdk#31170]
### Describe the feature

CodeBuild recently added support for Mac builds. https://aws.amazon.com/about-aws/whats-new/2024/08/aws-codebuild-mac-builds/

The CDK can to be extended to support Mac CodeBuild fleets, as well as using those fleets in CodeBuild projects.

### Use Case

I have a couple of existing CodeBuild jobs created using CDK for building a project on AL2023 and Windows. I would like to extend this to Mac as well to ensure that builds work smoothly on as many platforms as possible.

### Proposed Solution

1) This [enum](https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-codebuild/lib/environment-type.ts) needs to have an additional `MAC_ARM` value added to it.
2) A `MacBuildImage` class needs to be added to [this](https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-codebuild/lib/project.ts) file.

Validation will also need to be added, since the MacOS support has some limitations. See the release article linked above for more information.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.152.0

### Environment details (OS name and version, etc.)

Amazon Linux 2023

**Comment by pahud** [comment]
Absolutely! Is this something you'd like to pick up with a PR? We welcome pull requests for this.

**Comment by alanxluc** [comment]
Sure, I'll give it a shot
