### ISSUE TITLE
aws-cdk-lib » aws_rds » DatabaseCluster : Missing securityGroups property.

### ISSUE THREAD

**Issue by zmgehlke** [aws/aws-cdk#31196]
### Describe the bug

The DatabaseCluster type doesn't have the securityGroups property.

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_rds.DatabaseCluster.html#securitygroups-1

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

The property listed in the document is visible in IDEs.

### Current Behavior

That property and others appear not to exist on DatabaseCluster.

### Reproduction Steps

Install aws-cdk-lib and aws-cdk 2.154.0; attempt to access the property in VSCode.

### CDK CLI Version

2.154.0

### Node.js Version

20.15.1

### OS

Ubuntu 22.04

### Language

TypeScript

**Comment by ashishdhingra** [comment]
@zmgehlke Good morning. Thanks for opening the issue. I'm using `2.154.0 (build 0fc07f3)` and could see `securityGroups` property while creating a new `DatabaseCluster` instance:
<img width="578" alt="Screenshot 2024-08-23 at 9 43 19 AM" src="https://github.com/user-attachments/assets/f1e2a8c0-01ac-4701-af08-3ef5151ba792">

Could you please check in some other machine? Did you run `npm install` to install updated packages?

Thanks,
Ashish
