### ISSUE TITLE
Toolkit: don't save of the environmental context for default environments in cdk.json

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#312]
When users don't explicitly associate a stack with an environment, it doesn't really make sense to store environmental context project's `cdk.json`. Perhaps we should store it in `~/.cdk.json`.

Should work in tandem with #290

**Comment by justinmchase** [comment]
It definitely shouldn't go in there. The cdk.json gets committed into source control but different users have different accounts, it doesn't make sense to go into this file.
