### ISSUE TITLE
(events): Add ScheduleGroup

### ISSUE THREAD

**Issue by WtfJoke** [aws/aws-cdk#31249]
### Describe the feature

Currently there seems to be no way to create an EventBridge [ScheduleGroup](https://docs.aws.amazon.com/scheduler/latest/UserGuide/managing-schedule-group.html) using cdk or associate a Schedule with a ScheduleGroup.

### Use Case

I would like to group my Scheduled Rules into Groups (in order to tag them).

### Proposed Solution

Cloudformation allows creating [Scheduled Rules](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-scheduler-schedulegroup.html) and associating Scheduled Rules with the property "[GroupName](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-scheduler-schedule.html#cfn-scheduler-schedule-groupname)".

Once a ScheduleGroup is created, it can be implemented in the [Schedule](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_events.Schedule.html) construct.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.150.0

### Environment details (OS name and version, etc.)

windows 11, 23H2

**Comment by pahud** [comment]
We actually have [Group](https://github.com/aws/aws-cdk/blob/c7b236cfa74f3e4d7b412b368d41c506d7ba9f98/packages/%40aws-cdk/aws-scheduler-alpha/lib/group.ts#L293) and [GroupProps](https://github.com/aws/aws-cdk/blob/c7b236cfa74f3e4d7b412b368d41c506d7ba9f98/packages/%40aws-cdk/aws-scheduler-alpha/lib/group.ts#L7). Is this what you are looking for?

**Comment by WtfJoke** [comment]
I just figured out that these are two different products (https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-create-rule-schedule.html vs https://docs.aws.amazon.com/eventbridge/latest/userguide/using-eventbridge-scheduler.html#using-eventbridge-scheduler-create) closing this
