### ISSUE TITLE
(neptune-alpha): Add latest engine versions and supported instance types

### ISSUE THREAD

**Issue by triggan** [aws/aws-cdk#31244]
### Describe the feature

Add Engine Versions 1.3.2.0, 1.3.2.1, 1.3.3.0, 1.2.1.1, and 1.2.1.2 (https://docs.aws.amazon.com/neptune/latest/userguide/engine-releases.html).

Add latest set of supported instances:
- `db.r6i.x` (large to 32xlarge)
- `db.r5d.x` (large to 24xlarge)
- `db.x2g.x` (large to 16xlarge)
- `db.x2iedn.x` (xlarge to 32xlarge)
(https://aws.amazon.com/neptune/pricing/)

### Use Case

Provide users the ability to configure latest engine versions for a cluster along with the full list of supported instance types when using the neptune L2 construct (alpha).

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.154.1

### Environment details (OS name and version, etc.)

N/A

**Comment by ashishdhingra** [comment]
- List of supported instance classes could be retrieved using AWS CLI command `aws neptune describe-orderable-db-instance-options --engine neptune --query "OrderableDBInstanceOptions[*].[DBInstanceClass]" --output text`.
- Refer [Engine releases for Amazon Neptune](https://docs.aws.amazon.com/neptune/latest/userguide/engine-releases.html) for list of supported engine versions.

@triggan Thanks for opening feature request. Feel free to contribute PR.

Thanks,
Ashish
