### ISSUE TITLE
aws-cognito: UserPool.identityProviders is empty

### ISSUE THREAD

**Issue by jburn7** [aws/aws-cdk#31252]
### Describe the bug

When a modification is made to the UserPoolClient, its associated identity providers are reset to just the Cognito identity provider. According to [(https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_cognito.UserPoolClientIdentityProvider.html)](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_cognito.UserPoolClientIdentityProvider.html), that is is supposed to be mitigated by providing `supportedIdentityProviders` to the `UserPoolClient`.

I'm having trouble fetching the existing identity providers in the user pool to pass into `supportedIdentityProviders`

```
const userPool = new UserPool(scope, poolName, {
  userPoolName: poolName,
  ...
}

const identityProviders = userPool.identityProviders.map((identityProvider) =>
  UserPoolClientIdentityProvider.custom(identityProvider.providerName)
);

const userPoolClient = new UserPoolClient(scope, clientName, {
  userPool,
  ...,
  supportedIdentityProviders: [
    UserPoolClientIdentityProvider.COGNITO,
    ...identityProviders
  ]
});
```

Deploying that results in the user pool client's identity providers being reset to just Cognito, which as far as I can tell would imply that UserPool.identityProviders is always empty, because if I were to specify the name of an identity provider instead of fetching it from the user pool like so:

```
const userPoolClient = new UserPoolClient(scope, clientName, {
  userPool,
  ...,
  supportedIdentityProviders: [
    UserPoolClientIdentityProvider.COGNITO,
    UserPoolClientIdentityProvider.custom('KnownProviderName')
  ]
});
```

Then that custom provider is kept on the user pool client after a deployment. So the issue is with fetching the existing ones from the user pool

Therefore, I'd ask two things:
1) Is it a known bug that UserPool.identityProviders doesn't return the list of identity providers on that user pool
2) Is there a way to prevent user pool client identity provider associations from being wiped after a deployment in the first place? Omitting `supportedIdentityProviders` from the construct produces the same result, where the identity providers are reset to Cognito

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

`UserPool.identityProviders` returns the full list of identity providers as seen in the "Federated identity provider sign-in" box of the "Sign-in Experience" tab of a user pool in the AWS console

### Current Behavior

`UserPool.identityProviders` returns an empty list

### Reproduction Steps

```
const userPool = new UserPool(scope, poolName, {
  userPoolName: poolName,
  autoVerify: { email: true },
  signInAliases: { email: true },
  selfSignUpEnabled: false,
  signInCaseSensitive: false,
  mfa: Mfa.OFF, 
  accountRecovery: AccountRecovery.EMAIL_ONLY,
});

const readAttributes = new ClientAttributes().withStandardAttributes({
  givenName: true,
  familyName: true,
  email: true,
  emailVerified: true,
  address: true,
  birthdate: true,
  gender: true,
  locale: true,
  middleName: true,
  fullname: true,
  nickname: true,
  phoneNumber: true,
  profilePicture: true,
  preferredUsername: true,
  profilePage: true,
  timezone: true,
  lastUpdateTime: true,
  website: true,
  phoneNumberVerified: true
});

const writeAttributes = new ClientAttributes().withStandardAttributes({
  givenName: true,
  familyName: true,
  email: true,
  emailVerified: false,
  address: true,
  birthdate: true,
  gender: true,
  locale: true,
  middleName: true,
  fullname: true,
  nickname: true,
  phoneNumber: true,
  profilePicture: true,
  preferredUsername: true,
  profilePage: true,
  timezone: true,
  lastUpdateTime: true,
  website: true,
  phoneNumberVerified: false
});

const identityProviders = userPool.identityProviders.map((identityProvider) =>
  UserPoolClientIdentityProvider.custom(identityProvider.providerName)
);

const callbackUrls = [`${appUrl}/sign-in/sso`];
const logoutUrls = [`${appUrl}`];
const userPoolClient = new UserPoolClient(scope, idTag('frontend-client'), {
  userPool,
  authFlows: {
    userPassword: true,
    adminUserPassword: true,
    custom: true,
    userSrp: true
  },
  oAuth: { callbackUrls, logoutUrls },
  writeAttributes: writeAttributes,
  readAttributes: readAttributes,
  generateSecret: false,
  supportedIdentityProviders: [
    UserPoolClientIdentityProvider.COGNITO,
    ...identityProviders
  ]
});
```

### CDK CLI Version

2.138.0

### Node.js Version

20

### OS

Alpine Linux

### Language

TypeScript

**Comment by ashishdhingra** [comment]
@jburn7 Good afternoon. For your scenario, were these identity providers added outside the CDK code? If yes, then CDK doesn't know about it. CDK represents a CloudFormation resource with set of attributes. When you run `cdk synth`, it would synthesize the CDK code to a template. In most cases where context lookup is not used, it would not refresh the properties of existing CFN resource if these were added outside of the CDK. In other words, it would not make an AWS SDK API call to retrieve the resource.

As a workaround, you may try using customer resource provider that makes AWS Cognito Service API call to retrieve list of identity providers. In the successful custom resource call, you could use that list in your code. In case of failure, we could just ignore and proceed with the default.

Thanks,
Ashish

**Comment by jburn7** [comment]
@ashishdhingra @pahud I was able to solve this using a combination of both of your answers, thank you

**Comment by ashishdhingra** [comment]
> @ashishdhingra @pahud I was able to solve this using a combination of both of your answers, thank you

@jburn7 Glad the guidance worked for you.
