### ISSUE TITLE
aws-synthetics: support syn-nodejs-puppeteer-9.0 runtime 

### ISSUE THREAD

**Issue by sigJoe** [aws/aws-cdk#31271]
### Describe the feature

https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Synthetics_Library_nodejs_puppeteer.html confirms that Synthetics runtime "syn-nodejs-puppeteer-9.0" is available.

https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-synthetics/lib/runtime.ts only has up to 8.0

Can we support this in CDK please? Thanks.

### Use Case

Need to be able to use latest runtimes

### Proposed Solution

Update aws-cdk-lib/aws-synthetics/lib/runtime.ts

### Other Information

Previous PR for runtime updating: #30851 

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.155.0

### Environment details (OS name and version, etc.)

n/a

**Comment by ashishdhingra** [comment]
Created PR https://github.com/aws/aws-cdk/pull/31272
