### ISSUE TITLE
aws-location-alpha: dataSource property should be required in PlaceIndex class

### ISSUE THREAD

**Issue by mazyu36** [aws/aws-cdk#31288]
### Describe the bug

Currently, [dataSource](https://docs.aws.amazon.com/cdk/api/v2/docs/@aws-cdk_aws-location-alpha.PlaceIndex.html#datasourcespan-classapi-icon-api-icon-experimental-titlethis-api-element-is-experimental-it-may-change-without-noticespan) property in PlaceIndex class is optional.

But in [CFn document](https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-resource-location-placeindex.html#cfn-location-placeindex-datasource), `DataSource` property is required.

I think it would be preferable to make this a required field in accordance with CloudFormation.

In #30682, the `dataSource` property was also implemented, and based on the review comment, it was changed from optional to required.

https://github.com/aws/aws-cdk/pull/30682/files#r1734958764

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

The `dataSource` property is required.

### Current Behavior

The `dataSource` property is optional.

### Reproduction Steps

When use `PlaceIndex` class without `dataSource` property.

### Possible Solution

Change `dataSource` property to required.

### CDK CLI Version

2.151.0

### Node.js Version

All

### OS

MacOS

### Language

TypeScript

### Other information
 I have created an issue to discuss whether the modification should be implemented.

Considering the consistency with the RouteCalculator class and the CFn documentation, I think it would be better to make the `dataSource` required.
I recognize that this would be a breaking change, but `aws-location` is  an alpha module.

However, I think this change is not mandatory. 

Please let me know your thoughts.

**Comment by ashishdhingra** [comment]
CloudFormation schema [aws-location-placeindex.json](https://github.com/cdklabs/awscdk-service-spec/blob/main/sources/CloudFormationSchema/us-east-1/aws-location-placeindex.json) specifies `DataSource` as required field:
```JSON
...
  "required" : [ "DataSource", "IndexName" ],
...
```

**Comment by kaizencc** [comment]
Copying my comment on the PR here:

> A property being required on CFN does not necessarily mean we have to require it in CDK, if we can find a reasonable default for it. That's what we've done here -- we are not sending undefined into CFN and getting an error back, we are providing what we think is a sane default.

> It sounds like you don't think that DataSource.ESRI is a reasonable default -- before making that change, I think that's a better discussion to have in an issue.
