### ISSUE TITLE
(autoscaling): applyCloudFormationInit on each launchTemplateOverrides of mixedInstancesPolicy

### ISSUE THREAD

**Issue by BDeus** [aws/aws-cdk#31315]
### Describe the bug

Reopening of https://github.com/aws/aws-cdk/issues/27030

In the Construct AutoscalingGroup when setting a CloudFormationInit, the UserData is apply on the LaunchTemplate attach to the ASG. ([attach here](https://github.com/aws/aws-cdk/blob/a3863a6b5607dd462b3774f01f21d9dea4fd15d5/packages/aws-cdk-lib/aws-autoscaling/lib/auto-scaling-group.ts#L1655))
In case of using a MixedInstancesPolicy with LaunchTemplateOverrides, the templates overrides do not inherit from the UserData of the CloudFormationInit.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

Set the CfnSignals in all LaunchTemplates of the AutoscalingGroup when a CloudFormationInit is attach.
https://github.com/aws/aws-cdk/blob/a3863a6b5607dd462b3774f01f21d9dea4fd15d5/packages/aws-cdk-lib/aws-ec2/lib/cfn-init.ts#L157

### Current Behavior

The UserData build by the AutoscalingGroup and the Cloudformation does not set the signals on the overrides template, only on the default one.

### Reproduction Steps

Create an **AutoscalingGroup** with a **MixedInstancesPolicy** with two **LaunchTemplates**
Attach a **CloudFormationInit** to the **AutoscalingGroup**.
On synthetize, all LaunchTemplates need to have the signals generate by the **CloudFormationInit**

### CDK CLI Version

2.123.0

### Node.js Version

20.11.1

### OS

macos

### Language

TypeScript, Java

**Comment by khushail** [comment]
Hi @BDeus , Thanks for reaching out. 
Could you please share the minimal reproducible sample code for the issue mentioned. It would also be very helpful if you could share the synthesized template as well.
