### ISSUE TITLE
aws-s3: The `autoDeleteObjects` prop of `Bucket` is too brittle

### ISSUE THREAD

**Issue by garysassano** [aws/aws-cdk#31358]
### Describe the bug

We are going to deploy this CDK stack and observe the behavior.

```ts
const uniqueId = this.node.addr.substring(0, 8);

const myBucket = new Bucket(this, "MyBucket", {
  bucketName: `my-bucket-${uniqueId}`,
  enforceSSL: true,
  removalPolicy: RemovalPolicy.DESTROY,
  autoDeleteObjects: true,
});

const myBucketPolicy = new BucketPolicy(this, "MyBucketPolicy", {
  bucket: myBucket,
});

const myUser = new User(this, "MyUser", {
  userName: "my-user",
});

myBucketPolicy.document.addStatements(
  new PolicyStatement({
    effect: Effect.ALLOW,
    principals: [myUser],
    actions: ["s3:GetObject", "s3:ListBucket"],
    resources: [myBucket.bucketArn, `${myBucket.bucketArn}/*`],
  }),
);
```

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

I expected the `cdk deploy` to fail immediately due to a conflict between the `autoDeleteObjects` custom resource and the `BucketPolicy` we defined. Since only one bucket policy can exist at a time, the system should have detected this conflict and prevented the deployment.

### Current Behavior

However, the stack deploys successfully without any error.

![image](https://github.com/user-attachments/assets/aa74f95a-b7c2-4530-b1f5-32dc342329f4)

Inspecting the S3 bucket policy shows that the `BucketPolicy` we explicitly created overrides the one generated by `autoDeleteObjects`:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::533267016779:user/my-user"
            },
            "Action": [
                "s3:GetObject",
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::my-bucket-c812be60",
                "arn:aws:s3:::my-bucket-c812be60/*"
            ]
        }
    ]
}
```

When attempting to destroy the stack with `cdk destroy`, it fails because the Lambda function linked to `autoDeleteObjects` custom resource lacks the necessary permissions to delete the S3 bucket. This occurs because the `BucketPolicy` we defined overrides the policy that grants the required permissions.

### Reproduction Steps

see above

### Possible Solution

The CDK should enforce a check to prevent defining a `BucketPolicy` that overrides the permissions needed by the `autoDeleteObjects` custom resource. Although the deployment works, it leads to conflicts during stack destruction due to missing permissions.

### CDK CLI Version

2.156.0

### Node.js Version

20.17.0

### OS

Ubuntu 22.04.3 LTS

### Language

TypeScript

**Comment by khushail** [comment]
Hi @garysassano , thanks for reaching out. I am able to reproduce the scenario with given bucket policy. Its observed that adding a new bucket policy with existing Bucket Policy with autoDeleteObject:true actually leads to error when deleting the stack. 

```json
Received response status [FAILED] from custom resource. Message returned: AccessDenied: User: arn:aws:sts::1234567890:assumed-role/BucketAutoDeleteObjectP
ol-CustomS3AutoDeleteObjects-mHw0z310uANA/BucketAutoDeleteObjectPol-CustomS3AutoDeleteObject-mSxwX4IBLB2P is not authorized to perform: s3:GetBucketTagging
on resource: "arn:aws:s3:::my-bucket-c8939193" because no identity-based policy allows the s3:GetBucketTagging action
```
Sharing my observation -

When a bucket is created with `autoDeleteObject:true` -

https://github.com/aws/aws-cdk/blob/7315a59795a783a94a576ce24c07f11498e5291d/packages/aws-cdk-lib/aws-s3/lib/bucket.ts#L2562

these are the permissions granted -

https://github.com/aws/aws-cdk/blob/7315a59795a783a94a576ce24c07f11498e5291d/packages/aws-cdk-lib/aws-s3/lib/bucket.ts#L2570

```ts
    this.addToResourcePolicy(new iam.PolicyStatement({
      actions: [
        // prevent further PutObject calls
        ...perms.BUCKET_PUT_POLICY_ACTIONS,
        // list objects
        ...perms.BUCKET_READ_METADATA_ACTIONS,
        ...perms.BUCKET_DELETE_ACTIONS, // and then delete them
      ],
```

which results in this snippet of synthesized template when deployed
```json
      {
       "Action": [
        "s3:DeleteObject*",
        "s3:GetBucket*",
        "s3:List*",
        "s3:PutBucketPolicy"
       ],
```

but after defining the new policy, one sees the updation in Bucket policy-

```json
            "Action": [
                "s3:GetObject",
                "s3:ListBucket"
            ],
```

Hence leading to error during deletion. 

Suggested solution makes sense. I am marking this issue as P1 , for further discussion and action by the team.

**Comment by khushail** [comment]
@garysassano , it says in the [BucketPolicy](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_s3.BucketPolicy.html) doc that it should not be preferred way of adding policy

**Comment by pahud** [comment]
The BucketPolicy is not aware if there is another BucketPolicy being created for the same bucket hence it's not preferred.

The general recommended practice is always use `bucket.addToResourcePolicy()` instead.

**Comment by khushail** [comment]
@garysassano , I just rewrote the code with using `addToResourcePolicy()` and what it does it appends the Bucket policy and hence when the stack is destroyed, it succeeds without any error. Please see the shared snippet and template -

```ts

    const myBucket015 = new s3.Bucket(this, "MyBucket015", {
      bucketName: `my-bucket-015`,
      enforceSSL: true,
      removalPolicy: RemovalPolicy.DESTROY,
      autoDeleteObjects: true,
    });

    myBucket015.addToResourcePolicy( new iam.PolicyStatement({
      effect: iam.Effect.ALLOW,
      principals: [new iam.ArnPrincipal("3********6")],
      actions: ["s3:GetObject", "s3:ListBucket"],
      resources: [myBucket015.bucketArn, `${myBucket015.bucketArn}/*`],
    }));

```


```json

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Deny",
            "Principal": {
                "AWS": "*"
            },
            "Action": "s3:*",
            "Resource": [
                "arn:aws:s3:::my-bucket-015",
                "arn:aws:s3:::my-bucket-015/*"
            ],
            "Condition": {
                "Bool": {
                    "aws:SecureTransport": "false"
                }
            }
        },
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::3*******6:role/BucketV2IssueStack-CustomS3AutoDeleteObjectsCustomR-op0fiXi89QWA"
            },
            "Action": [
                "s3:DeleteObject*",
                "s3:GetBucket*",
                "s3:List*",
                "s3:PutBucketPolicy"
            ],
            "Resource": [
                "arn:aws:s3:::my-bucket-015",
                "arn:aws:s3:::my-bucket-015/*"
            ]
        },
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::3*******6:root"
            },
            "Action": [
                "s3:GetObject",
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::my-bucket-015",
                "arn:aws:s3:::my-bucket-015/*"
            ]
        }
    ]
}
```
<img width="1001" alt="Screenshot 2024-09-10 at 2 29 24 PM" src="https://github.com/user-attachments/assets/375b6f57-c57d-4cf3-a151-337ad1e1f570">

Hope that would be helpful.
