### ISSUE TITLE
iot: configure AWS IoT logging

### ISSUE THREAD

**Issue by badmintoncryer** [aws/aws-cdk#31357]
### Describe the feature

To enable [AWS IoT logging](https://docs.aws.amazon.com/iot/latest/developerguide/configure-logging.html) feature by AWS CDK.

```ts
new iot.Logging(this, 'Logging', {
  logLevel: iot.LogLevel.WARN,
})
```

### Use Case

Cloudformation supports for configuring [AWS IoT logging](https://docs.aws.amazon.com/iot/latest/developerguide/configure-logging.html) for all activities but AWS CDK doesn't support this.

To enable this feature, we have to setup [logging role](https://docs.aws.amazon.com/iot/latest/developerguide/configure-logging.html#configure-logging-role-and-policy) simultaneously. I believe it would be better to create the logging role implicitly using AWS CDK."

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.155.0

### Environment details (OS name and version, etc.)

irrelevant

**Comment by pahud** [comment]
Thank you for the PR!
