### ISSUE TITLE
aws-cloudfront-origins: optional `s3:PutObject` permission missing in `S3BucketOrigin.withOriginAccessControl`

### ISSUE THREAD

**Issue by garysassano** [aws/aws-cdk#31362]
### Describe the bug

According to the [AWS docs](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-restricting-access-to-s3.html#oac-permission-to-access-s3), it's possible to grant both read and write access when using CloudFront OAC with an S3 bucket origin. However, the `S3BucketOrigin.withOriginAccessControl` L2 construct currently defaults to read-only access, and there is no built-in option to add write permissions.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

See above.

### Current Behavior

See above.

### Reproduction Steps

See above.

### CDK CLI Version

2.156.0

### Node.js Version

20.17.0

### OS

Ubuntu 22.04.3 LTS

### Language

TypeScript

**Comment by vpylypenko2** [comment]
Try to set `originAccessLevels` to `[cloudfront.AccessLevel.READ, cloudfront.AccessLevel.WRITE]`
```
import * as cloudfront from 'aws-cdk-lib/aws-cloudfront';
import * as origins from 'aws-cdk-lib/aws-cloudfront-origins';

const accessControl = new cloudfront.S3OriginAccessControl(this, 'AccessControl', {
  originAccessControlName: <name>,
  description: <description>
});

origins.S3BucketOrigin.withOriginAccessControl(
  <bucket>, {
    originAccessControl: accessControl,
    originAccessLevels: [cloudfront.AccessLevel.READ, cloudfront.AccessLevel.WRITE]}
)
```

**Comment by garysassano** [comment]
Thanks, that seems to work in adding the `s3:PutObject` permission to the S3 bucket policy:

![image](https://github.com/user-attachments/assets/db375cb9-ed4a-47dc-b3e1-8873745a54a5)

**Comment by garysassano** [comment]
Thanks, that seems to work in adding the `s3:PutObject` permission to the S3 bucket policy:

![image](https://github.com/user-attachments/assets/db375cb9-ed4a-47dc-b3e1-8873745a54a5)
