### ISSUE TITLE
(rds): add `performanceInisghts` configuration at cluster level

### ISSUE THREAD

**Issue by aprat84** [aws/aws-cdk#31375]
### Describe the feature

Add the performance insights configuration options at cluster level:
```ts
/**
 * Whether to enable Performance Insights for the DB instance.
 *
 * @default - false, unless `performanceInsightRetention` or `performanceInsightEncryptionKey` is set.
 */
readonly enablePerformanceInsights?: boolean;

/**
 * The amount of time, in days, to retain Performance Insights data.
 *
 * @default 7
 */
readonly performanceInsightRetention?: PerformanceInsightRetention;

/**
 * The AWS KMS key for encryption of Performance Insights data.
 *
 * @default - default master key
 */
readonly performanceInsightEncryptionKey?: kms.IKey;
```

### Use Case

So we don't need to configure it to all instances. Also, because CloufFormation allows it.

### Proposed Solution

Add the same 3 configuration options present in `DatabaseInstance` class, to the `DatabaseCluster` class: `enablePerformanceInsights`, `performanceInsightRetention` and `performanceInsightEncryptionKey`.

### Other Information

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbcluster.html#cfn-rds-dbcluster-performanceinsightsenabled

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.256

### Environment details (OS name and version, etc.)

macOS 14.6.1

**Comment by pahud** [comment]
Makes sense to me. Please help us prioritize with 👍  and we welcome any PRs for this.
