### ISSUE TITLE
Osaka regions has only one AZ

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#3139]
Environment-agnostic behavior of `stack.availabilityZones` assumes all regions have at least 2 AZs but apparently Osaka has only a single AZ.

I am not sure if there is something we can do about it, but even just document this would be nice.

@mhuebner 

this is what came to my mind but I was fooled by Osaka region that only has one AZ
https://aws.amazon.com/about-aws/global-infrastructure/regions_az/?p=ngi&loc=2

but I read it over again and seems its a special case, so 2 AZ per region setup will basically work everywhere

thanks for the explanation,
case closed.

_Originally posted by @lkoniecz in https://github.com/awslabs/aws-cdk/issues/3124#issuecomment-507138815_

**Comment by NGL321** [comment]
@eladb Do we still need this in documentation?

**Comment by Jerry-AWS** [comment]
@NGL321 @eladb The new Troubleshooting topic contains a bit about the AZ thing and calls out Osaka specifically, and I just added similar information to the Environments topic as well. So I think we've got it covered.

**Comment by NGL321** [comment]
Okay! 
Closing out due to resolve.
