### ISSUE TITLE
We don't have an AMI for kubernetes version 1.13

### ISSUE THREAD

**Issue by lkoniecz** [aws/aws-cdk#3140]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/awslabs/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*

``` python
class DevelopmentStack(core.Stack):
    def __init__(self, app: core.App, id: str, **kwargs) -> None:
        super().__init__(app, id, **kwargs)
        vpc = aws_ec2.Vpc(scope=self, id='Vpc', cidr='192.168.0.0./16')
        eks_cluster = aws_eks.Cluster(scope=self, id='EksCluster', vpc=vpc, version='1.13')
        eks_cluster.add_capacity(id='EksClusterOnDemandCapacity', 't2.large', desired_capacity=2)


app = core.App()
DevelopmentStack(
    app=app,
    id='Dev',
    env={
        'region': os.environ['CDK_DEFAULT_REGION'],
        'account': os.environ['CDK_DEFAULT_ACCOUNT']
    })

app.synth()
```

fails with: `jsii.errors.JSIIError: We don't have an AMI for kubernetes version 1.13`

* **What is the expected behavior (or behavior of feature suggested)?**
Template compiles.

* **What is the motivation / use case for changing the behavior or adding this feature?**
Cannot create EKS cluster with version 1.13

* **Please tell us about your environment:**
  
  - CDK CLI Version: 0.36.0 (build 6d38487)
  - Module Version: 0.36.0
  - OS:  [Ubuntu 19.4]
  - Language: [Python]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

https://github.com/awslabs/aws-cdk/issues/3120
The template compiles only using autoscaling groups, that is via
`eks_cluster.add_auto_scaling_group(...)`

**Comment by nmussy** [comment]
This should have been fixed with #3331
