### ISSUE TITLE
aws_rds/DatabaseInstance: DB instance being replaced when updating deletionProtection

### ISSUE THREAD

**Issue by awsiv** [aws/aws-cdk#31426]
### Describe the bug

When Updating `deletionProtection` and `removalPolicy` in rds.DBInstance, both of which DO NOT trigger `replacement` - DB ends being replaced anyways.

Change:
<img width="623" alt="image" src="https://github.com/user-attachments/assets/feaa26fd-1ce2-4e65-8ed5-d0f0dac96494">

cdk diff shows no indication of replacement:
<img width="485" alt="image" src="https://github.com/user-attachments/assets/3aedad1b-d529-4d76-9192-52165d836c20">

However, during `cdk deploy` the DB gets replaced with the following message:

```bash
<stack> |   1/242 | 8:37:09 AM | UPDATE_COMPLETE      | AWS::RDS::DBSubnetGroup                         | rds-mysql-svc/rds-mysql-svc/SubnetGroup/Default (rdsmysqlsvcSubnetGroup4EE92041) 
...
<stack>|   1/242 | 8:37:12 AM | UPDATE_IN_PROGRESS   | AWS::RDS::DBInstance                            | rds-mysql-svc/rds-mysql-svc(rds) 
Requested update requires the creation of a new physical resource; hence creating one.

```

I think this is because of the update in AWS::RDS::DBSubnetGroup which is in use by the RDS instance.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

1. Diff should show that DB replacement would/might happen
2. DB Subnet group might not need to be updated in the Construct

### Current Behavior

1. DB subnet group is updated and
2. Diff doesn't show that replacement would occur but `deploy` replaces the DB instance anyways

### Reproduction Steps

Update `deletionProtection` and or `removalPolicy` for rds/DatabaseInstance

### CDK CLI Version

2.157.0 (build 7315a59)

### Node.js Version

v20.0.0

### OS

ubuntu

### Language

TypeScript

**Comment by khushail** [comment]
Hi @awsiv , thanks for reaching out.

i tried to repro the above scenario with this code -

Initially I setup the values to be false for `deletionProtection` 
```ts
    const instance1 = new rds.DatabaseInstance(this, "mysqlinstance1", {
      engine: rds.DatabaseInstanceEngine.MYSQL,
      credentials: rds.Credentials.fromGeneratedSecret('mysqladmin'),
      vpc,
      deletionProtection: false,
      removalPolicy: cdk.RemovalPolicy.DESTROY
    });
```
and it deployed successfully, When I changed the both boolean values, as shown below , this is what is displayed in `cdk diff` -

<img width="1214" alt="Screenshot 2024-09-12 at 2 48 09 PM" src="https://github.com/user-attachments/assets/bed8d72e-b000-450c-bcf9-e4b61c675cd0">

and running `npx cdk deploy --verbose` successfully dpeloys the changes without any replacement of DB on my end-

<img width="1219" alt="Screenshot 2024-09-12 at 2 55 06 PM" src="https://github.com/user-attachments/assets/84c14538-79e0-44fd-a476-f1ee39c0dbd1">

As I am not able to repro this, requesting you to please share the minimum reproducible code snippet for before and after scenario.
Thanks.

**Comment by awsiv** [comment]
Hi @khushail,

Thanks for your response. Unfortunately, I am unable to replicate this as well. Someone in the team deployed with "encryption=true" (which was the main cause of the replacement).

It is however strange that this did not show up on the diff as shown in my screenshot above(needs to be investigated further). I will close this issue for now.
