### ISSUE TITLE
aws_ecs: L2 support for restartpolicy

### ISSUE THREAD

**Issue by raoz** [aws/aws-cdk#31425]
### Describe the feature

The RestartPolicy L1 construct is now available https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ecs.CfnTaskDefinition.RestartPolicyProperty.html, but it cannot be conveniently set up using L2 ContainerDefinition.

### Use Case

I use L2 constructs for setting up ECS services and need to set the restart policy for a container.

### Proposed Solution

Add `restartPolicy` field to ContainerDefinition.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.158.0

### Environment details (OS name and version, etc.)

Typescript

**Comment by ashishdhingra** [comment]
`RestartPolicy` was added in L1 construct as a result of CFN schema change, refer https://github.com/aws/aws-cdk/issues/31127 and [CfnTaskDefinition.ContainerDefinitionProperty](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ecs.CfnTaskDefinition.ContainerDefinitionProperty.html#restartpolicy). This should now be supported in L2 construct.

**Comment by go-to-k** [comment]
The PR has been submitted. It is now awaiting review.

https://github.com/aws/aws-cdk/pull/31228

**Comment by toplac** [comment]
Hey @go-to-k do you have any idea when this PR is ready to be merged?
We are eagerly awaiting this feature

**Comment by go-to-k** [comment]
Right now I'm waiting for a review and I don't know when it will be reviewed as it depends on the status of the team. I can't wait either.

If we get more reactions to this issue, it will be prioritized.

**Comment by go-to-k** [comment]
The PR has been merged!

**Comment by gracelu0** [comment]
Thank you for your PR! Closing this issue as the PR has been merged.
