### ISSUE TITLE
[aws-events-targets] Add DLQ support for Kinesis Target

### ISSUE THREAD

**Issue by ryanschulz46** [aws/aws-cdk#31428]
### Describe the feature

This is an available feature through the AWS Console already and is supported in many other target but not Kinesis.

[aws-events] Add support for Rule Dead Letter Queue: https://github.com/aws/aws-cdk/issues/11612
feat(events-targets): Add DLQ support for SQS target: https://github.com/aws/aws-cdk/issues/16417

### Use Case

Use `aws-cdk-lib/aws-events-targets` to create Kinesis Targets, but also support a DLQ for such target

### Proposed Solution

Extend `aws-cdk-lib/aws-events-targets/kinesis-stream/KinesisStreamProps` to extend TargetBaseProps (similar to SQS)

```
import * as events from 'aws-cdk-lib/aws-events';
import * as event_targets from 'aws-cdk-lib/aws-events-targets';
import * as sqs from 'aws-cdk-lib/aws-sqs';
import * as kinesis from 'aws-cdk-lib/aws-kinesis';

// Create Stream and DLQ
const myKinesisStream = new kinesis.Stream(this, 'MyKinesisStream', {
    streamName: 'my-kinesis-stream',
    streamMode: kinesis.StreamMode.ON_DEMAND,
});
const myDeadLetterQueue = new sqs.Queue(this, 'MyDeadLetterQueue');

// Kinesis Target created with DLQ configured
const myKinesisTarget = new event_targets.KinesisStream(myKinesisStream, {deadLetterQueue: myDeadLetterQueue});


// Example Target Use-case: Connecting EventBus to Kinesis Stream now has DLQ
const myEventBus = new events.EventBus(this, 'MyEventBus', { eventBusName: 'my-event-bus'});

const myEventRule = new events.Rule(this, 'MyEventRule', {
    eventBus: myEventBus,
    eventPattern: ['pattern'],
    targets: [myKinesisTarget],
});
```

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.149.0

### Environment details (OS name and version, etc.)

AL2

**Comment by khushail** [comment]
Hi @ryanschulz46 , thanks for reaching out with this request. This would be good to have (https://github.com/aws/aws-cdk/pull/13660)
Contribution from the community are welcome.
