### ISSUE TITLE
(aws_iam): Service Principals for Cloudwatch Logs and Step Functions changing to exclude region

### ISSUE THREAD

**Issue by frankpengau** [aws/aws-cdk#31438]
### Describe the bug

Hi AWS Team,

Hope you've been well!

We are currently looking into changes in our snapshot tests which indicate that region is being removed from Service Principals around Cloudwatch Log Groups and Step Functions State Machines. 

Just wanted to make sure this is normal? 

![Screenshot 2024-09-13 at 4 42 06 PM](https://github.com/user-attachments/assets/86ef0fe1-9b3f-40dc-b736-45f248f61a77)

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Last Known Working CDK Version

2.149.0

### Expected Behavior

No change in Service Principal

### Current Behavior

Changes detected in Service Principal

### Reproduction Steps

Jest Snapshot Testing

### CDK CLI Version

2.156.0

### Node.js Version

18.20.1

### OS

macOS Sonoma 14.6.1

### Language

TypeScript

### Language Version

5.5.3

**Comment by frankpengau** [comment]
Found that it might be related to a deprecation of service principal mappings that include regions? 

Ref: https://github.com/aws/aws-cdk/pull/30832

**Comment by pahud** [comment]
Looking into it.

**Comment by pahud** [comment]
https://github.com/aws/aws-cdk/pull/30832 this should be a bug fix, not breaking change or regression. Checking with the maintainers.

**Comment by ashishdhingra** [comment]
Confirmed with the team. This change is intentional and all service principles have moved away from being regionalized.
