### ISSUE TITLE
Deployment crashing while zipping assets

### ISSUE THREAD

**Issue by PygmalionPolymorph** [aws/aws-cdk#3145]
* **I'm submitting a ...**
  - [x] :beetle: bug report

* **What is the current behavior?**
After upgrading to CDK 0.36.0, deployment fails without an error message while creating an asset zip file for my lambda. Running deploy in verbose mode, i can see the last debug message printed:
`Preparing zip asset from directory: cdk.out/asset.357a0d25d1...`

* **Please tell us about your environment:**
  
  - CDK CLI Version: 0.36.0
  - Module Version: 0.36.0
  - OS: Antergos (Arch Linux)
  - Language: Typescript

* **Other information**
After looking through the corresponding source code [(here)](https://github.com/awslabs/aws-cdk/blob/master/packages/aws-cdk/lib/assets.ts) it seems like the process is crashing completely, as the `finally` statement (removing the staging directory in `/tmp`) is'nt run, the directory still exists.
I've made sure there is enough disk space in `/tmp` and it is writable.

**Comment by jogold** [comment]
Can you give more information about the content of the folder you are zipping?

**Comment by PygmalionPolymorph** [comment]
It is a gatsby application with some dependent subprojects, so there are:

- package.json
- node_modules
- src
- main.js
- gatsby-(config|browser|node).js
- components (subproject containing package.json and src folder)
- feature-toggles (subproject containing package.json and src folder)
- lambda (folder with the lambda handler and some additional source files)

**Comment by jogold** [comment]
What about the size and number of files? Is it failing with for a specific Lambda function or all functions?

**Comment by PygmalionPolymorph** [comment]
25823 files
341 links
5077 directories

Total size of the directory is 239M, with 236M being node_modules

**Comment by eladb** [comment]
This is a major issue.

I remember @rix0rrr had a comment about this in #2931, and I can't see if it was addressed or not. If it wasn't, I rather we revert this change and rethink this.

**Comment by jogold** [comment]
@eladb agree

@PygmalionPolymorph it would be nice if you could share your code (at least what's generating the folder content) so that we can reproduce. Can you also confirm that the issue is specific to this Lambda function's asset?

**Comment by PygmalionPolymorph** [comment]
I have another lambda inside the same stack which is being deployed fine, so yes, it is specific to this asset. I don't know whether this occurs on other lamdas as well as i only have this stack..
And unfortunately i can't share the code as it is a closed source client project

**Comment by jogold** [comment]
Can you at least share the `dependencies` of your `package.json` so that I can generate an equivalent `node_modules` folder?

**Comment by PygmalionPolymorph** [comment]
Sure, here they are:
```
  "dependencies": {
    "@clientname/components": "*",
    "@contentful/rich-text-react-renderer": "^13.2.0",
    "@contentful/rich-text-types": "^13.1.0",
    "babel-plugin-styled-components": "^1.10.2",
    "dotenv": "^8.0.0",
    "gatsby": "2.9.4",
    "gatsby-cli": "^2.6.0",
    "gatsby-image": "^2.1.0",
    "gatsby-plugin-google-gtag": "^1.0.17",
    "gatsby-plugin-manifest": "^2.1.1",
    "gatsby-plugin-offline": "^2.1.1",
    "gatsby-plugin-react-helmet": "^3.0.12",
    "gatsby-plugin-sharp": "^2.0.37",
    "gatsby-plugin-styled-components": "^3.1.0",
    "gatsby-source-contentful": "^2.0.62",
    "gatsby-source-filesystem": "^2.0.37",
    "gatsby-transformer-sharp": "^2.1.19",
    "prop-types": "^15.7.2",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-helmet": "^5.2.1",
    "styled-components": "^4.3.2"
  }
```

`@clientname/components` has these:
```
"dependencies": {
    "@clientname/feature-toggles": "*",
    "react": "^16.8.6",
    "styled-components": "^4.3.2"
}
```

And  `@clientname/feature-toggles` doesn't have any

**Comment by jogold** [comment]
I'm able to zip the `node_modules` after installing all the dependencies:

```ts
import { zipDirectory } from '../archive';

(async () => {
  await zipDirectory('./node_modules', 'test.zip');
})();
```

![image](https://user-images.githubusercontent.com/12623249/60445138-e8312e80-9c1e-11e9-8122-c9ed899a865c.png)

**Comment by eladb** [comment]
I am not 100% comfortable that we need to load the entire directory into memory...

**Comment by jogold** [comment]
> I am not 100% comfortable that we need to load the entire directory into memory...

Not sure it's case, `zipDirectory` uses streams.

**Comment by PygmalionPolymorph** [comment]
I've had a colleague try the same deployment, and it worked on his machine. I'm not quite sure how to continue debugging this.

**Comment by jogold** [comment]
@PygmalionPolymorph can you add a `console.log(file)` statement in the `forEach`?

https://github.com/awslabs/aws-cdk/blob/aa28db7179f367558cfe82658c25d1d3a916bea2/packages/aws-cdk/lib/archive.ts#L27-L32

Is it then crashing after all files have been appended?

**Comment by PygmalionPolymorph** [comment]
I'll investigate, where it crashes exactly...

**Comment by PygmalionPolymorph** [comment]
Tried this:
```
        console.log('Appending files...');
        files.forEach(file => {
            console.log(file);
            archive.append(fs.createReadStream(path.join(directory, file)), {
                name: file,
                date: new Date('1980-01-01T00:00:00.000Z'),
            });
        });
        console.log('Done appending');
        console.log('Finalizing...');
        archive.finalize();
        console.log('Done Finalizing');
        // archive has been finalized and the output file descriptor has closed, resolve promise
        output.once('close', () => {
          console.log('Output closing...');
          ok();
        });
```

And i can see `Done finalizing`, but not `Output closing...`. Seems like it has nothing to do with the zipping itself

**Comment by jogold** [comment]
The zipping is async and happens after the sync call to `archive.finalize()`.

Can you console log in the `archive.on('warning', ...)` and `archive.on('error', ...)`

**Comment by PygmalionPolymorph** [comment]
Strangely, if i change the `ok()` to `fail()`, i can see both the log `Output closing...` and the error resulting from the failing promise

**Comment by PygmalionPolymorph** [comment]
> The zipping is async and happens after the sync call to `archive.finalize()`.
Oh, right..

> Can you console log in the `archive.on('warning', ...)` and `archive.on('error', ...)`
I did, but none of those two were called.
```
        archive.on('warning', (err) => {
          console.log('WARNING');
          console.log(err);
          fail(err);
        });
        archive.on('error', (err) => {
          console.log('ERROR');
          console.log(err);
          fail(err);
        });
```

**Comment by jogold** [comment]
Do you see this debug message?
https://github.com/awslabs/aws-cdk/blob/aa28db7179f367558cfe82658c25d1d3a916bea2/packages/aws-cdk/lib/assets.ts#L86

**Comment by PygmalionPolymorph** [comment]
> Do you see this debug message?
> 
> https://github.com/awslabs/aws-cdk/blob/aa28db7179f367558cfe82658c25d1d3a916bea2/packages/aws-cdk/lib/assets.ts#L86

No, the process ends before that

**Comment by jogold** [comment]
Can you add this in `zipDirectory`?

```ts
output.on('error', (err) => console.log(err));
output.on('warning', (err) => console.log(err));
```

**Comment by PygmalionPolymorph** [comment]
> Can you add this in `zipDirectory`?
> 
> ```ts
> output.on('error', (err) => console.log(err));
> output.on('warning', (err) => console.log(err));
> ```

Both don't get called

**Comment by jogold** [comment]
Node version?

**Comment by PygmalionPolymorph** [comment]
v10.16.0

**Comment by jogold** [comment]
What are the differences with your colleague's environnement/machine?

**Comment by PygmalionPolymorph** [comment]
> v10.16.0

I just tried with Node 12, but i get the same error

> What are the differences with your colleague's environnement/machine?

He is also running Arch Linux, and i suppose the same node version. I'll ask him for his machine specs tomorrow. It also runs fine on our Gitlab CI server running alpine, as well as on the MacOS machines of two other colleagues.
Seems like it's something personal :smile:

**Comment by jogold** [comment]
Made some more tests and I was able to successfully zip a directory containing 3 times the mentioned dependencies (98,193 files and 14,952 folders):

![image](https://user-images.githubusercontent.com/12623249/60451484-706a0080-9c2c-11e9-824f-33d710288fc0.png)

**Comment by rix0rrr** [comment]
I notice mention of the presence of symlinks. A normal node install wouldn't create those, so is it the presence of symlinks that is causing the issue?

**Comment by PygmalionPolymorph** [comment]
I put an intermediate step into our deployment which removes all symlinks prior to zipping the lambda, but that didnt' seem to solve the problem unfortunately.

I just confirmed however, that the zipping is the problem by feeding a path to a previously built zip file into the lambda construct. That went through and the deployment worked fine.

As no one else seems to have this problem, i think i will just zip the lambda myself beforehand.

**Comment by RomainMuller** [comment]
I wonder if there is an issue where `node` runs out of memory while trying to drain the queue, and the process dies... Could you try to run again while setting `NODE_OPTIONS=--max-old-space-size=8192`?

**Comment by jogold** [comment]
@artyom-melnikov can you provide code to reproduce the issue?

**Comment by artyom-melnikov** [comment]
@jogold I can provide you with the content of the folder on which I always can reproduce this issue (this is node_modules for my project, I also verified that issue remains after I unzip content). 

https://drive.google.com/open?id=1LPF5cJX9jZAEPscgp4vJlytJTq0dmZVo

As for the code - I used this one: (based on `aws-cdk/lib/archive.js:36`)
```js
zipDirectory('/path/to/layer',  '/tmp/1.zip')
  .then(() => console.log('Done'));
```
The 'Done' is never printed for that folder, works fine with other

Some more observations:
 - I tried to remove some folder and it seems that when there are about 7200 files the process works fine (originally there are 10500 files)

**Comment by jogold** [comment]
@artyom-melnikov cannot reproduce with your zip on WSL using Ubutunu...

**Comment by artyom-melnikov** [comment]
@jogold seems like a platform-related issue then... I can try to debug it on my machine if you want, but for that, I need some pointers, I'm not a nodejs expert

**Comment by jogold** [comment]
@artyom-melnikov can you try playing with `nodir` and `follow` here?
https://github.com/aws/aws-cdk/blob/cd0e9bd53e37f4b5824d64a0234e28c3a86b1ed9/packages/aws-cdk/lib/archive.ts#L12-L17

**Comment by artyom-melnikov** [comment]
@jogold I tried to change those but it didn't result in anything good. I also tried to pin `archiver` to the versions used to work for me and it doesn't work either, so the problem with the new code in the `zipDirectory` function. 

I have a bold guess:
```ts
    files.forEach(file => { // Append files serially to ensure file order
      archive.append(fs.createReadStream(path.join(directory, file)), {
        name: file,
        date: new Date('1980-01-01T00:00:00.000Z'), // reset dates to get the same hash for the same content
      });
    });
```
Shouldn't such code result in all files being open simultaneously? I feel like it can be related to the `EMFILE, too many open files` and the OS file limit. Will try to check this version

**Comment by artyom-melnikov** [comment]
@jogold I created a very crude solution that sends files in batch as soon as the previous batch is processed

```js
function zipDirectory(directory, outputFile) {
    return new Promise((ok, fail) => {
        // The below options are needed to support following symlinks when building zip files:
        // - nodir: This will prevent symlinks themselves from being copied into the zip.
        // - follow: This will follow symlinks and copy the files within.
        const globOptions = {
            dot: true,
            nodir: true,
            follow: true,
            cwd: directory,
        };
        const files = glob.sync('**', globOptions); // The output here is already sorted
        const output = fs.createWriteStream(outputFile);
        const archive = archiver('zip');
        archive.on('warning', fail);
        archive.on('error', fail);

        let i = 0;
        archive.on('progress', (progress) => {
            if (progress.entries.total === progress.entries.processed) {
                // Previous batch has been processed, add next batch
                if (i < files.length) {
                    let j = i;
                    for (j; j < Math.min(files.length, i + 1000); j++) {
                        appendFile(archive, directory, files[j]);
                    }
                    i = j;
                } else {
                    // Everything done, finalize
                    archive.finalize();
                }
            }
        });
        archive.pipe(output);

        if (files.length > 0) {
            // Send first file to start processing
            appendFile(archive, directory, files[i++]);
        } else {
             archive.finalize();
        }

        output.once('close', () => ok());
    });
}

function appendFile(archive, directory, file) {
    archive.append(fs.createReadStream(path.join(directory, file)), {
        name: file,
        date: new Date('1980-01-01T00:00:00.000Z')
    });
}
```

This solution works for me, processing everything and returning proper callback. Please consider using similar approach

**Comment by jogold** [comment]
Can you try with:
```ts
    files.forEach(file => { // Append files serially to ensure file order
      archive.file(path.join(directory, file), {
        name: file,
        date: new Date('1980-01-01T00:00:00.000Z'), // reset dates to get the same hash for the same content
      });
    });
```

`archive.file` uses [`lazystream`](https://github.com/jpommerening/node-lazystream) to solve this issue, but then I'm not that file order is preserved across zips...

**Comment by artyom-melnikov** [comment]
@jogold yes, this solution also works

**Comment by jogold** [comment]
@artyom-melnikov can you try this https://github.com/jogold/aws-cdk/commit/d0464b2869cf572c3057e532a15781ce57eb0a84?

**Comment by jogold** [comment]
@aereal @artyom-melnikov can you try this https://github.com/jogold/aws-cdk/commit/d0464b2869cf572c3057e532a15781ce57eb0a84

**Comment by jogold** [comment]
https://github.com/aws/aws-cdk/compare/master...jogold:fix-zip

**Comment by artyom-melnikov** [comment]
@jogold that one didn't work for me

**Comment by jogold** [comment]
> @jogold that one didn't work for me

The last one?

**Comment by artyom-melnikov** [comment]
@jogold https://github.com/aws/aws-cdk/compare/master...jogold:fix-zip works for me!

**Comment by jogold** [comment]
@PygmalionPolymorph can you give it a try?

**Comment by jogold** [comment]
@artyom-melnikov and this one https://github.com/aws/aws-cdk/compare/master...jogold:fix-zip-stream?

**Comment by artyom-melnikov** [comment]
@jogold no, https://github.com/aws/aws-cdk/compare/master...jogold:fix-zip-stream is not working

**Comment by jogold** [comment]
@artyom-melnikov the one from this commit https://github.com/jogold/aws-cdk/commit/151303919036a7d8c913e008cc94328d32f9946d?

**Comment by artyom-melnikov** [comment]
@jogold yes, the one which use graceful-fs

**Comment by jogold** [comment]
@artyom-melnikov ok reverting to something much simpler, can you try this last one https://github.com/jogold/aws-cdk/commit/d34e6060302dc1ee29cca3011ae716b834a20a31? Will then open a PR

**Comment by artyom-melnikov** [comment]
@jogold the last solution https://github.com/jogold/aws-cdk/commit/d34e6060302dc1ee29cca3011ae716b834a20a31 works for me!
