### ISSUE TITLE
aws_kms: kms.Key(alias=...) didn't work

### ISSUE THREAD

**Issue by anentropic** [aws/aws-cdk#31481]
### Describe the bug

I added a `kms.Key` to my CDK stack and specified an alias via the `alias` kwarg

But after deploying the stack the new key had no alias

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

created key should have the specified alias

### Current Behavior

<img width="389" alt="kms-key-alias" src="https://github.com/user-attachments/assets/69cba4aa-448b-4546-9534-5ef7e5cbe306">

key seems to have been deployed with no alias

### Reproduction Steps

my code was like:

```python
    encryption_key = kms.Key(
        self,
        "RDS Encrypted Storage Key",
        alias=f"{resource_prefix}-rds-encryption",
        description="...",
        enable_key_rotation=True,
        policy=iam.PolicyDocument(...),
    )
```

### Additional Information/Context

I subsequently edited my code to:
```python
    encryption_key = kms.Key(
        self,
        "RDS Encrypted Storage Key",
        description="...",
        enable_key_rotation=True,
        policy=iam.PolicyDocument(...),
    )
    encryption_key.add_alias(f"{resource_prefix}-rds-encryption")
```

after redeploying it seems that this method works - the key has an alias - but it has created a new key rather than setting the alias on the one created in previous cdk deploy

### CDK CLI Version

2.158.0 (build 4b8714d)

### Framework Version

2.155.0

### Node.js Version

v20.15.1

### OS

macOS 14.6.1

### Language

Python

### Language Version

3.11.5

**Comment by khushail** [comment]
Hi @anentropic , thanks for reaching out.

I tried to repro the scenario with this code (Language  - Typescript, CDK Version - 2.158)

```ts
    const encryption = new kms.Key(this, 'MyKey', {
      enableKeyRotation: true,
      enabled: true,
      keySpec: kms.KeySpec.SYMMETRIC_DEFAULT,
      keyUsage: kms.KeyUsage.ENCRYPT_DECRYPT,
      pendingWindow: cdk.Duration.days(7),
      removalPolicy: cdk.RemovalPolicy.DESTROY,
      alias: 'alias/MyKey',
    });

    new cdk.CfnOutput(this, 'KeyId', {
      value: encryption.keyId,
      description: 'The KMS Key Id',
      exportName: 'KeyId',
    });
 ```
 
 and it works as epected, please see this output -
 
<img width="1062" alt="Screenshot 2024-09-18 at 2 08 32 PM" src="https://github.com/user-attachments/assets/6e428cbc-2bb2-4cc7-a278-3ba762347523">

Now when you want to add another alias, you can do this by calling addAlias(..) in the existent code -

```ts
    const encryption = new kms.Key(this, 'MyKey', {
      enableKeyRotation: true,
      enabled: true,
      keySpec: kms.KeySpec.SYMMETRIC_DEFAULT,
      keyUsage: kms.KeyUsage.ENCRYPT_DECRYPT,
      pendingWindow: cdk.Duration.days(7),
      removalPolicy: cdk.RemovalPolicy.DESTROY,
      alias: 'alias/MyKey',
    });

    encryption.addAlias('alias/UpdatedkeyAlias');

    new cdk.CfnOutput(this, 'KeyId', {
      value: encryption.keyId,
      description: 'The KMS Key Id',
      exportName: 'KeyId',
    });
```

`cdk diff` shows this -

<img width="978" alt="Screenshot 2024-09-18 at 2 20 34 PM" src="https://github.com/user-attachments/assets/59103a1f-3284-4fa4-93fe-d34a893df597">

and the output on the console -
<img width="1027" alt="Screenshot 2024-09-18 at 2 24 10 PM" src="https://github.com/user-attachments/assets/da9a1b46-b28b-4bbb-88c5-475a9d9a5656">


So this adds another alias on the key.

Let me know if this does not work for you.

**Comment by anentropic** [comment]
Maybe better to try to repro from the Python SDK.

What happened for me is I ended up with this key:

![Screenshot 2024-09-19 at 09 51 06](https://github.com/user-attachments/assets/48ddb0fa-387f-4e86-8020-19f5ee55926c)

no aliases

then changing the code to do `encryption_key.add_alias(...)` instead of `kms.Key(alias=...)` and re-deploying resulted in a new key created with the expected alias:
![Screenshot 2024-09-19 at 09 54 27](https://github.com/user-attachments/assets/08925d0e-636d-48ce-9418-3490ce569e82)

**Comment by khushail** [comment]
@anentropic , sure, let me try with python and get back to you

**Comment by khushail** [comment]
@anentropic , sharing the repro in Python -

initial python code deployed, which created the Alias - `testKey`
```py
        testKey = kms.Key(self,"testKey",
            enabled= True,
            enable_key_rotation= True,
            alias="alias/testKey"
        )

        aws_cdk.CfnOutput(self, "keyArn", 
                          value=testKey.key_arn
                          )
```

Alias added in console -

<img width="1082" alt="Screenshot 2024-09-19 at 12 50 40 PM" src="https://github.com/user-attachments/assets/bff15499-c4c6-4725-b8db-13db5fb0ac52">

This is the updated code with another alias -

```py
        testKey = kms.Key(self,"testKey",
            enabled= True,
            enable_key_rotation= True,
            alias="alias/testKey"
        )

        testKey.add_alias("alias/testKey02").  // this should be added in the console , along with previous one
        
        aws_cdk.CfnOutput(self, "keyArn", 
                          value=testKey.key_arn
                          )
```

Console output -
<img width="1077" alt="Screenshot 2024-09-19 at 12 57 55 PM" src="https://github.com/user-attachments/assets/acbd39db-dc6c-4c36-b68f-1db34621b79d">

So this also works in Python.

Hope that helps! Please feel free to reach out if something is misinterpreted in results.

**Comment by anentropic** [comment]
hmm, I wonder if mine was a left-over artefact from a failed deployment or something

I will try and reproduce again my side

**Comment by khushail** [comment]
@anentropic , for now I am closing this issue.

Please feel free to reopen if you encounter any issue again. Thanks!
