### ISSUE TITLE
rds: support for local write forwarding for an Aurora mysql cluster

### ISSUE THREAD

**Issue by badmintoncryer** [aws/aws-cdk#31523]
### Describe the feature

To configure [local write forwarding](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-mysql-write-forwarding.html) feature for an Aurora mysql cluster.

### Use Case

Cloudformation supports enabling local write forwarding feature but AWS CDK does not support it.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.159.0

### Environment details (OS name and version, etc.)

irrelevant

**Comment by khushail** [comment]
@badmintoncryer , thanks for your contribution!
