### ISSUE TITLE
java: Serverless Function events do not work properly and their `Properties` is set to empty object

### ISSUE THREAD

**Issue by lambrospetrou** [aws/aws-cdk#3153]
* **I'm submitting a ...**
  - [x ] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/awslabs/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*

I have the following code using `Java CDK 0.34.0` through Kotlin code.

```
val eventCustom : CfnFunction.ApiEventProperty = object : CfnFunction.ApiEventProperty {
    override fun getMethod() = "ANY"
    override fun getPath() = "/"
    override fun getRestApiId() = "TODO-RESTAPIID"
}

val eventFromCdk = CfnFunction.ApiEventProperty.builder()
    .withMethod("ANY")
    .withPath("/")
    .withRestApiId("TODO-RESTAPIID")
    .build()

val eventSource: CfnFunction.EventSourceProperty = CfnFunction.EventSourceProperty.builder()
    .withProperties(eventFromCdk)
    .withType("Api")
    .build()

CfnFunction(stack, "lambda-function-test-events", CfnFunctionProps.builder()
    .withEvents(mapOf(
        // FIXME???: this ends up having properties: {}
        "APIG" to event
    ))
    .withCodeUri(CfnFunction.S3LocationProperty.builder()
        .withBucket("MyS3Bucket")
        .withKey("MyS3BucketKey")
        .build()
    )
    .withHandler("com.example.handleRequest")
    .withMemorySize(512)
    .withRole("TODO-role")
    .withRuntime("java8")
    .withTimeout(30)
    .build()
)
```

Basically setting up an API Gateway event source for my lambda function. The main point to note is the two objects `eventCustom` and `eventFromCdk` defined at the top.

The `eventFromCdk` is using the [ApiEventProperty.Builder](https://docs.aws.amazon.com/cdk/api/latest/java/software/amazon/awscdk/services/sam/CfnFunction.ApiEventProperty.Builder.html#build--) to create the event properties, whereas the `eventCustom` is using an anonymous class to implement the right interface `ApiEventProperty`.

The issue is that when using `withProperties(eventFromCdk)` call for the definition of `eventSource`, the output CloudFormation template contains the following (empty event):

```
"lambdafunctiontestevents": {
  "Type": "AWS::Serverless::Function",
  "Properties": {
    "CodeUri": {
      "Bucket": "MyS3Bucket",
      "Key": "MyS3BucketKey"
    },
    "Handler": "com.example.handleRequest",
    "Runtime": "java8",
    "Events": {
      "APIG": {
        "Properties": {},
        "Type": "Api"
      }
    },
    "MemorySize": 512,
    "Role": "TODO-role",
    "Timeout": 30
  }
}
```

and when I use `withProperties(eventCustom)`, I get the proper output:

```
"lambdafunctiontestevents": {
  "Type": "AWS::Serverless::Function",
  "Properties": {
    "CodeUri": {
      "Bucket": "MyS3Bucket",
      "Key": "MyS3BucketKey"
    },
    "Handler": "com.example.handleRequest",
    "Runtime": "java8",
    "Events": {
      "APIG": {
        "Properties": {
          "Method": "ANY",
          "Path": "/",
          "RestApiId": "TODO-RESTAPIID"
        },
        "Type": "Api"
      }
    },
    "MemorySize": 512,
    "Role": "TODO-role",
    "Timeout": 30
  }
}
```

* **What is the expected behavior (or behavior of feature suggested)?**

I am expecting the `eventFromCdk` above to have the same behavior as the `eventCustom` but instead it does not generate the right `Properties` for the Lambda function event source.

I also tried the same thing with the [S3EventProperty](https://docs.aws.amazon.com/cdk/api/latest/java/software/amazon/awscdk/services/sam/CfnFunction.S3EventProperty.html) and the results were identical, I get empty `{}` properties.

So, is there any problem with how I use the above CDK feature, or is it a problem with the template generation of the event source objects? 

If I make the implementation of `eventCustom` to be the following, which uses the code from the Java CDK, it also does not work, which makes me think that the issue is with the `$jsii$toJson` method:

```
val valid: CfnFunction.ApiEventProperty = object : CfnFunction.ApiEventProperty {
    override fun getMethod() = "ANY"
    override fun getPath() = "/"
    override fun getRestApiId() = "TODO-RESTAPIID"
    
    // taken straight from the Java code for CfnFunction.ApiEventProperty.Builder as shown by Intellij
    override fun `$jsii$toJson`(): TreeNode {
        val om = JsiiObjectMapper.INSTANCE;
        val obj = JsonNodeFactory.instance.objectNode();
        obj.set("method", om.valueToTree(this.method));
        obj.set("path", om.valueToTree(this.path));
        obj.set("restApiId", om.valueToTree(this.restApiId))
        return obj;
    }
}
```

* **Please tell us about your environment:**
  
  - Module Version: 0.34
  - OS: OSX Mojave | Linux
  - Language: Java

**Comment by lambrospetrou** [comment]
Hello, were you able to reproduce the bug on your side? 

Is it an actual bug or something circumstantial that happens only when used like above? If that's the case, how should we use the `ApiEventProperty`?

Thanks

**Comment by eladb** [comment]
@RomainMuller can you please take a look? seems like this is related to our jsii java bindings?

**Comment by RomainMuller** [comment]
Pretty sure there is another issue about the same (although I was unable to find it on a cursory search from my phone). This is due to a deserialization bug in jsii caused by the fact this property involved a large type union (12 or so candidates) where the first candidate has only optional parameters (and thus always succeeds in deserializing an empty object).

That's the next kernel bug I'll be looking into (as soon as possible now - I meant to tackle it last week but things came up...)

**Comment by RomainMuller** [comment]
It ought to be fixed with the next CDK release!

**Comment by RomainMuller** [comment]
This should have been fixed in the latest release!
