### ISSUE TITLE
cdk bootstrap: Error running cdk bootstrap with yaml template

### ISSUE THREAD

**Issue by CFarinellaCM** [aws/aws-cdk#31547]
### Describe the bug

**Running command:** 
cdk bootstrap --template bootstrap-template.yaml --profile <profile-name>

**Returns error message:**
Error: Trying to perform an operation that requires a bootstrap stack; you should not see this error, this is a bug in the CDK CLI.

Full trace below:
 ⏳  Bootstrapping environment aws://account-id/ap-southeast-2...
 ❌  Environment aws://account-id/ap-southeast-2 failed bootstrapping: Error: Trying to perform an operation that requires a bootstrap stack; you should not see this error, this is a bug in the CDK CLI.        ❌  Environment aws://account-id/ap-southeast-2 failed bootstrapping: Error: Trying to perform an operation that requires a bootstrap stack; you should not see this error, this is a bug in the CDK CLI.
    at NoBootstrapStackEnvironmentResources.lookupToolkit (C:\Users\profile.name\AppData\Roaming\npm\node_modules\aws-cdk\lib\index.js:463:19087)
    at makeBodyParameter (C:\Users\profile.name\AppData\Roaming\npm\node_modules\aws-cdk\lib\index.js:453:93731)
    at deployStack (C:\Users\profile.name\AppData\Roaming\npm\node_modules\aws-cdk\lib\index.js:463:259)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async C:\Users\profile.name\AppData\Roaming\npm\node_modules\aws-cdk\lib\index.js:468:2348
    at async Promise.all (index 0)
    at async CdkToolkit.bootstrap (C:\Users\profile.name\AppData\Roaming\npm\node_modules\aws-cdk\lib\index.js:468:2193)
    at async exec4 (C:\Users\profile.name\AppData\Roaming\npm\node_modules\aws-cdk\lib\index.js:521:54490)

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

cdk bootstrap to run to completion

### Current Behavior

Command is failing to execute

### Reproduction Steps

**Generate template**
cdk bootstrap --show-template > bootstrap-template.yaml

**Run command** 
cdk bootstrap --template bootstrap-template.yaml --profile <profile-name>

### CDK CLI Version

2.159.1 (build c66f4e3)

### Node.js Version

v20.11.0

### OS

Windows 10 Enterprise

### Language

TypeScript

**Comment by ashishdhingra** [comment]
@CFarinellaCM Good afternoon. Unfortunately, I'm unable to reproduce the issue. Executing `cdk bootstrap --template ~/bootstrap-template.yaml --profile default aws://ACCOUNTID-REDACTED/ap-southeast-2` works fine:
```
Using bootstrapping template from /Users/REDACTED/bootstrap-template.yaml
 ⏳  Bootstrapping environment aws://ACCOUNTID-REDACTED/ap-southeast-2...
Trusted accounts for deployment: (none)
Trusted accounts for lookup: (none)
Using default execution policy of 'arn:aws:iam::aws:policy/AdministratorAccess'. Pass '--cloudformation-execution-policies' to customize.
CDKToolkit: creating CloudFormation changeset...
 ✅  Environment aws://ACCOUNTID-REDACTED/ap-southeast-2 bootstrapped.
```

Could you please execute the `cdk bootstrap` command with `--debug true` option to get detailed logs?

Per [cdk bootstrap](https://docs.aws.amazon.com/cdk/v2/guide/ref-cli-cmd-bootstrap.html), the bootstrap stack is a CloudFormation stack that provisions an Amazon S3 bucket and Amazon ECR repository in the AWS environment. Do you have sufficient permissions to create CDK bootstrap stack in the destination account and/or region?

Thanks,
Ashish

**Comment by rahuldev06** [comment]
I also came across this issue, issue was with file encoding of the bootstrap-template.yaml file. Try to run cloudformation validate command on the same file. (Not on contents but the actual file directly). 
Error I was getting:
Error parsing parameter '--template-body': Unable to load paramfile (bootstrap-template.yaml), text contents could not be decoded.  If this is a binary file, please use the fileb:// prefix instead of the file:// prefix.

Created a new file with same contents , and then ran the command , it worked afterwards
