### ISSUE TITLE
aws-cdk-lib: v2.160.0 jar missing from maven central

### ISSUE THREAD

**Issue by scarytom** [aws/aws-cdk#31552]
### Describe the bug

Version 2.160.0 was [released Sep 24, 2024, 16:10 UTC](https://github.com/aws/aws-cdk/releases/tag/v2.160.0) but the Jar artifact has yet to show up in [Maven Central](https://central.sonatype.com/artifact/software.amazon.awscdk/aws-cdk-lib/versions).

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Last Known Working CDK Version

2.159.1

### Expected Behavior

Jar should be in maven central

### Current Behavior

Jar is missing from maven central

### Reproduction Steps

N/A

### Possible Solution

publish the missing jar

### CDK CLI Version

N/A

### Framework Version

N/A

### Node.js Version

N/A

### OS

ubuntu

### Language

Java

### Language Version

openjdk 21.0.4

### Other information

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.7.0:get (default-cli) on project standalone-pom: Couldn't download artifact: org.eclipse.aether.resolution.DependencyResolutionException: The following artifacts could not be resolved: software.amazon.awscdk:aws-cdk-lib:jar:2.160.0 (absent): Could not find artifact software.amazon.awscdk:aws-cdk-lib:jar:2.160.0 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
```

**Comment by pahud** [comment]
Looks like it's available now. Let me know if there's any other concerns.

**Comment by scarytom** [comment]
yep, it is there now.  Any idea why there was such a delay between the release and the artifact appearing?

**Comment by pahud** [comment]
It could be a time gap before it's available on maven. We'll bring this up to the team for awareness.

**Comment by scarytom** [comment]
Thanks,  I'll let you know if it happens again (I recall it happening one other time in the past)

**Comment by gracelu0** [comment]
Thank you, closing this issue for now as it has been resolved.
