### ISSUE TITLE
(api-gateway): provide a grant method

### ISSUE THREAD

**Issue by GaalDornick** [aws/aws-cdk#31577]
### Describe the feature

If you have a component that calls an API, the component has to be given permissions to invoke the API. It would be nice to have a grant method on RestAPI

### Use Case

I have an API that is called from a Lambda. Right now, I have to add this to lambda's Policy

```
this.myFn.addToRolePolicy(
      new iam.PolicyStatement({
        effect: iam.Effect.ALLOW,
        actions: ['execute-api:Invoke'],
        resources: [`arn:aws:execute-api:${props.region}:${props.account}:*`],
      }),
    );
```

### Proposed Solution

It would be great to be able to do this
`this.restAPi.grantInvoke(this.myFn)`

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.160.0

### Environment details (OS name and version, etc.)

Linux

**Comment by khushail** [comment]
Hi @GaalDornick , thanks for reaching out. Is this something you are talking about-[grantExecute](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_apigateway.Method.html#grantwbrexecutegrantee)()?
