### ISSUE TITLE
(module name): (short issue description)

### ISSUE THREAD

**Issue by holomekc** [aws/aws-cdk#31591]
### Describe the feature

I am not 100% sure where to address this. It is not a cdk issue and also not a cloudformation issue.
On the following page: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Lambda-Insights-extension-versionsARM.html
the available versions for Lambda Insights on arm64 are listed. I was wondering why cn-north-1 is missing? It is available for x86 though.

### Use Case

Using Lambda Insights for Lambda running on arm64

### Proposed Solution

Also push the layer to cn-north-1

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.158.0

### Environment details (OS name and version, etc.)

OS-X

**Comment by pahud** [comment]
We can't answer as this is unrelated to CDK.

I'd suggest you submit this feedback at the top right corner of this page
https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Lambda-Insights-extension-versions.html

Hope it helps!
