### ISSUE TITLE
(aws-cognito): add ability to use V2_0 as PreTokenGenerationConfig

### ISSUE THREAD

**Issue by kornicameister** [aws/aws-cdk#31595]
### Describe the feature

I want to use Cognito's advanced security for augmenting access tokens per https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-pre-token-generation.html#user-pool-lambda-pre-token-generation-accesstoken

<img width="988" alt="image" src="https://github.com/user-attachments/assets/c6723423-e779-4fe6-820c-78d0d3b90ebc">

From what I can tell this should be as simple as setting `LambdaVersion` to `V2_0` of https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-pretokengenerationconfig.html#cfn-cognito-userpool-pretokengenerationconfig-lambdaversion

### Use Case

Changing access tokens

### Proposed Solution

add `PRE_TOKEN_GENERATION_CONFIG_V2` to UserPoolOperation enum

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.160.0

### Environment details (OS name and version, etc.)

MacOS Sierra

**Comment by pahud** [comment]
Thank you for the feedback. We welcome the PRs!

**Comment by pahud** [comment]
Thank you @mhboon !

Hi @kornicameister can you validate if this works for you?

**Comment by kornicameister** [comment]
@mhboon @pahud my bad, I misunderstood the `LambdaVersion` as something from lambda alias.
