### ISSUE TITLE
aws-cdk-lib.aws_codebuild.PipelineProject: Upgrade default build environment

### ISSUE THREAD

**Issue by awerchniak** [aws/aws-cdk#31614]
### Describe the feature

The BuildImage for a CodeBuild Pipeline Project currently defaults to `BuildEnvironment.LinuxBuildImage.STANDARD_1_0`, which is deprecated. This can cause issues for AWS CodeBuild users who don't do a deep dive, as they will be working on a super old / deprecated version of Linux. I personally have run into issues as the version of Docker installed is quite old and is missing modern functionality; I'm sure there are plenty of other issues wrong with using a deprecated Linux Image, not the least of which being security implications.

References:
1. https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_codebuild.PipelineProject.html#environment
2. https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_codebuild.LinuxBuildImage.html#static-standard_1_0span-classapi-icon-api-icon-deprecated-titlethis-api-element-is-deprecated-its-use-is-not-recommended%EF%B8%8Fspan

### Use Case

Users creating a CodeBuild PipelineProject with very simple build logic should receive a linux base image that is not deprecated. The default behavior for AWS customers is to provide an old image without security patches, which is bad.

### Proposed Solution

Maybe upgrade the default value to one that's not deprecated, such as https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_codebuild.LinuxBuildImage.html#static-standard_7_0 ?

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.160.0

### Environment details (OS name and version, etc.)

all environments

**Comment by khushail** [comment]
Hi @awerchniak , thanks for reaching out.

The code defaults to usage of `BuildEnvironment.LinuxBuildImage.STANDARD_1_0`
https://github.com/aws/aws-cdk/blob/7e80cc9665c0a1f7e82b124991d946a4234313c2/packages/aws-cdk-lib/aws-codebuild/lib/project.ts#L1063

https://github.com/aws/aws-cdk/blob/7e80cc9665c0a1f7e82b124991d946a4234313c2/packages/aws-cdk-lib/aws-codebuild/lib/project.ts#L566

while this has been mentioned here as deprecated -
https://github.com/aws/aws-cdk/blob/7a8ae02dbc1d55885cdafead26fd1f780c522e8c/packages/aws-cdk-lib/aws-codebuild/lib/project.ts#L1797

Thanks for pointing this out and volunteering for contribution. Marking this as P2.
