### ISSUE TITLE
aws-ec2: restrictDefaultSecurityGroup custom resource lambda uses basic lambda execution role, no ability to add perm boundary

### ISSUE THREAD

**Issue by justinwiley** [aws/aws-cdk#31628]
### Describe the bug

If the `restrictDefaultSecurityGroup` option is enabled for ec2.Vpc, a new lambda and lambda execution role is created with the AWSLambdaBasicExecutionRole attached, which grants inappropriately broad wildcard log access.

There doesn't seem to be a way to override this, or to add a permissions boundary to the lambda execution role.

There are two issues with this:

- by default, cdknag complains about wildcard access
- if you are providing a custom permissions boundary for the cdk bootstrap role, you likely want to have the role require lambdas be deployed with a permissions boundary attached

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

ec2.Vpc should:
- expose the lambda execution role or allow it to be overwritten
- or, stop using the basic execution role and provide a perm boundary option

### Current Behavior

See above

### Reproduction Steps

```
    const vpc = new ec2.Vpc(this, 'VPC', {
      ipAddresses: ec2.IpAddresses.cidr(`10.0.0.0/16`),
      restrictDefaultSecurityGroup: true,
    })
```

### Possible Solution

see expected behavior

### CDK CLI Version

2.160

### Node.js Version

20

### OS

any

### Language

TypeScript

**Comment by khushail** [comment]
Hi @justinwiley , thanks for reaching out.

i tried to repro this with given scenario and here is my observation -

The lambdaBasicExecutionRole is having access to Logs after setting 'restrictDefaultSecurityGroup` to true -

<img width="1028" alt="Screenshot 2024-10-07 at 3 34 40 PM" src="https://github.com/user-attachments/assets/32905789-0f59-488b-8a6f-029558582018">

<img width="1038" alt="Screenshot 2024-10-07 at 6 19 05 PM" src="https://github.com/user-attachments/assets/903efb10-0d4a-4dba-b5d3-e4d0e2515fd9">

However when I try to restrict the role permission by custom boundary, 
```
    //creating custom boundary
    const boundary = new iam.ManagedPolicy(this, 'Boundary2', {
      statements: [
        new iam.PolicyStatement({
          effect: iam.Effect.DENY,
          actions: ['logs:PutLogEvents'],
          resources: ['*'],
        }),
      ],
    });

    iam.PermissionsBoundary.of(this).apply(boundary);
 ```
 I see Boundary role getting attached to customRole as shown in this template-
 
 ```json
   "CustomVpcRestrictDefaultSGCustomResourceProviderRole26592FE0": {
   "Type": "AWS::IAM::Role",
   "Properties": {
    "AssumeRolePolicyDocument": {
     "Version": "2012-10-17",
     "Statement": [
      {
       "Action": "sts:AssumeRole",
       "Effect": "Allow",
       "Principal": {
        "Service": "lambda.amazonaws.com"
       }
      }
     ]
    },
    "ManagedPolicyArns": [
     {
      "Fn::Sub": "arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
     }
    ],
    "Policies": [
     {
      "PolicyName": "Inline",
      "PolicyDocument": {
       "Version": "2012-10-17",
       "Statement": [
        {
         "Effect": "Allow",
         "Action": [
          "ec2:AuthorizeSecurityGroupIngress",
          "ec2:AuthorizeSecurityGroupEgress",
          "ec2:RevokeSecurityGroupIngress",
          "ec2:RevokeSecurityGroupEgress"
         ],
         "Resource": [
          {
           "Fn::Join": [
            "",
            [
             "arn:aws:ec2:us-west-1:123456789012:security-group/",
             {
              "Fn::GetAtt": [
               "VPCB9E5F0B4",
               "DefaultSecurityGroup"
              ]
             }
            ]
           ]
          }
         ]
        }
       ]
      }
     }
    ],
    "PermissionsBoundary": {
     "Ref": "Boundary261F0699E"
    }
 ```
 
is this what you are expecting to do ??
I agree that by changing the boolean value to true, wide permissions are granted but AFAIU, this boundary role is limiting the access permissions. 
Please feel free to clarify if something is misinterpreted.
