### ISSUE TITLE
Fargate Task state management issue compatibility with codedeploy

### ISSUE THREAD

**Issue by erwanrioualbelli** [aws/aws-cdk#31620]
### Describe the bug

on last version of cdk deploy the tasks created by cdk such as for instance

```js
this.taskDefinition = new ecs.TaskDefinition(this, `${id}-main-task-definition`, {
    family: `${id}-main-task-definition`,
    compatibility: ecs.Compatibility.FARGATE,
    cpu: '4096',
    memoryMiB: '10240',
    networkMode: ecs.NetworkMode.AWS_VPC,
    taskRole: this.clusterRole,
    executionRole: this.clusterRole,
    volumes: [
        {
            name: 'translations',
            efsVolumeConfiguration: {
                fileSystemId: this.fileSystem.fileSystemId,
                transitEncryption: 'ENABLED',
                authorizationConfig: {
                    iam: 'ENABLED',
                    accessPointId: this.accessPoint.accessPointId,
                },
            },
        },
    ],
});
```
    
in sync with codedeploy
for instance 
    
```js
this.fargateService = new ecs.FargateService(this, `${id}-service`, {
      serviceName: `${id}-service`,
      cluster: this.cluster,
      taskDefinition: this.taskDefinition,
      deploymentController: { type: ecs.DeploymentControllerType.CODE_DEPLOY },
      // NETWORK CONFIGURATION
      securityGroups: [this.securityGroup],
      // ACCESS
      propagateTags: 'TASK_DEFINITION',
      enableExecuteCommand: true,
      healthCheckGracePeriod: Duration.seconds(300),
});
```
        
now whenever modify it (name or anything) throw an error that is -->
        
```txt
Error: The stack named XXXXXXXXX. failed to deploy: UPDATE_ROLLBACK_COMPLETE: Resource handler returned message: "Invalid request provided: UpdateService error: Unable to update task definition on services with a CODE_DEPLOY deployment controller. Use AWS CodeDeploy to trigger a new deployment.
```

Would be nice if fixed :) Not sure if it is directly related to `cdk` or more a `cloudformation` thing.

    

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

The expected behavior would be the pipeline accept the state change of the task without codedeploy been a blocker

### Current Behavior

codedeploy block the `cdk deploy`

### Reproduction Steps

create a ECS cluster with tasks and farget and setup a codedeploy to handle deployment. The all of it with CDK. Enjoy the crash whenever you modify one task config after a sucessful deployment

### CDK CLI Version

2.160.0

### Node.js Version

20

### OS

(container ubuntu)

### Language

TypeScript

**Comment by khushail** [comment]
Hi @erwanrioualbelli , thanks for reaching out.

Apologies for not clearly understanding your issue, could you please share complete minimal repro code of the above scenario which could help in issue reproduction on my end.
