### ISSUE TITLE
aws-iam: Arn in a composite principal sometimes get replaced with a (seemingly) random string of capitalized letters

### ISSUE THREAD

**Issue by bmitchum-3rdeyecam** [aws/aws-cdk#31638]
### Describe the bug

I am creating a role with the iam.Role construct that has a list of principals in the trust policy (code below). The first time I deployed this, the role was deployed correctly. At some point down the road, after a non-related update to the stack, one of the role arns in the trust policy got replaced with a random (I think) string of capitalized letters. I deleted the role, redeployed, added the role back, & redeployed again, and the role arn was back! I tested by redeploying the same code to another environment that had also been changed to an ALPHA string (same role) and the arn did not come back. So, I repeated the process above and the role came back in that environment too. Is this a known bug? 
```
const myRole = new Role(this, "MyRole", {
        assumedBy: new CompositePrincipal(
          new ArnPrincipal(`arn:aws:iam::111111111111:role/role-1`),
          new ArnPrincipal(`arn:aws:iam::111111111111:role/role-2`),
          new ArnPrincipal(`arn:aws:iam::111111111111:role/role-3`),
        ),
        roleName: "MyRole",
      });
```

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

my trust policy to retain the correct principals unless that code is updated

### Current Behavior

one of the principal arns got replaced by a capitalized alpha string

### Reproduction Steps

```
const myRole = new Role(this, "MyRole", {
        assumedBy: new CompositePrincipal(
          new ArnPrincipal(`arn:aws:iam::111111111111:role/role-1`),
          new ArnPrincipal(`arn:aws:iam::111111111111:role/role-2`),
          new ArnPrincipal(`arn:aws:iam::111111111111:role/role-3`),
        ),
        roleName: "MyRole",
      });

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### CDK CLI Version

2.160.0

### Framework Version

_No response_

### Node.js Version

v20.13.1

### OS

Amazon Linux 2

### Language

TypeScript

### Language Version

_No response_

### Other information

_No response_

**Comment by khushail** [comment]
Hi @bmitchum-3rdeyecam , thanks for reaching out.
its a bit unclear to me what did you change in the stack , after which the role arn got changed to capitalised strings.

Could you please share the complete code, the synthesized template, the change to the stack and the change in role arn, to better understand and repro the situation. Appreciate your help here!
