### ISSUE TITLE
(aws-ecr): Expose repository domain or hostname

### ISSUE THREAD

**Issue by moltar** [aws/aws-cdk#31631]
### Describe the feature

Expose the repository domain/hostname as a prop.

### Use Case

The Docker credentials helper (e.g. [`docker-credential-ecr-login`](https://github.com/awslabs/amazon-ecr-credential-helper)) expects a hostname in the configuration.

```json
{
	"credHelpers": {
		"public.ecr.aws": "ecr-login",
		"<aws_account_id>.dkr.ecr.<region>.amazonaws.com": "ecr-login"
	}
}
```

Docs: https://github.com/awslabs/amazon-ecr-credential-helper?tab=readme-ov-file#docker

### Proposed Solution

Extract the hostname part from this method:

https://github.com/aws/aws-cdk/blob/0c753c39304a248843de9d995dc9bf0359ae3496/packages/aws-cdk-lib/aws-ecr/lib/repository.ts#L234-L242

And make it public:

```ts
  /**
   * Returns the domain of the repository. Can be used in Docker credentials helper.
   *
   *    ACCOUNT.dkr.ecr.REGION.amazonaws.com
   *
   * @param tagOrDigest Optional image tag or digest (digests must start with `sha256:`)
   */
  public get repositoryDomain(): string {
    return "";
  }
```

### Other Information

This helper already ships with some CodeBuild images:

https://github.com/aws/aws-codebuild-docker-images/issues/743

### Acknowledgements

- [ ] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### CDK version used

2.x

### Environment details (OS name and version, etc.)

N/A

**Comment by ashishdhingra** [comment]
If we examine Push commands for an ECR repository, the 1st step is to `Retrieve an authentication token and authenticate your Docker client to your registry. Use the AWS CLI:`
```
aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin <<ACCOUNT>>.dkr.ecr.<<REGION>>.amazonaws.com`
```

So it is useful to expose a property, let's say `registryUri`, in [IRepository](https://github.com/aws/aws-cdk/blob/79d9c4ddd4b96a4d4bd0c38a83687229253449fc/packages/aws-cdk-lib/aws-ecr/lib/repository.ts#L30C18-L30C29) interface (similar to `repositoryUri`):
```TypeScript
  /**
   * The URI of this repository's registry:
   *
   *    ACCOUNT.dkr.ecr.REGION.amazonaws.com
   *
   * @attribute
   */
  readonly registryUri: string;
```
Then introduce property below in [RepositoryBase](https://github.com/aws/aws-cdk/blob/79d9c4ddd4b96a4d4bd0c38a83687229253449fc/packages/aws-cdk-lib/aws-ecr/lib/repository.ts#L152C23-L152C37) class:
```TypeScript
  /**
   * The URI of this repository (represents the latest image):
   *
   *    ACCOUNT.dkr.ecr.REGION.amazonaws.com/REPOSITORY
   *
   */
  public get registryUri() {
    const parts = this.stack.splitArn(this.repositoryArn, ArnFormat.SLASH_RESOURCE_NAME);
    return `${parts.account}.dkr.ecr.${parts.region}.${this.stack.urlSuffix}`;
  }
```

**Comment by moltar** [comment]
@ashishdhingra Good point. Luckily, that command seems to work with the full `repositoryUri` value, too!

**Comment by moltar** [comment]
Altho I'd be careful with the `registryUri` nomenclature, as URI implies that there must be a scheme. What we have is truly just a domain or a hostname. But if we forget the implementation detail, it might just be a name. 🤷🏼 

https://en.wikipedia.org/wiki/Uniform_Resource_Identifier
