### ISSUE TITLE
CompositePrincial constructor params is wrong in .NET

### ISSUE THREAD

**Issue by su-rabbit** [aws/aws-cdk#3163]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/awslabs/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*

Follow typescript definition, `CompositePrincipal` allow multiple principal objects in object constructor.
But, In .NET definition, `CompositePrincial` allow only one of principal object in constructor.

https://github.com/awslabs/aws-cdk/blob/f954128529a51ce0a0ac5658a225660d2392cd59/packages/%40aws-cdk/aws-iam/lib/principals.ts#L262-L273

![image](https://user-images.githubusercontent.com/52145358/60500260-fc475f80-9cf4-11e9-96ed-472c0a44e667.png)

* **What is the expected behavior (or behavior of feature suggested)?**

In my think,  `CompositePrintical` must be received multiple principal objects as array type.

* **What is the motivation / use case for changing the behavior or adding this feature?**

Mismatch user guide documentation

* **Please tell us about your environment:**
  
  - CDK CLI Version: 0.36.0
  - Module Version: 0.36.0
  - OS: Windows 10
  - Language: .NET

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

**Comment by RomainMuller** [comment]
This might be fixed with the next release.

**Comment by RomainMuller** [comment]
This should be fixed in 1.16.x!
