### ISSUE TITLE
AWS-Redshift-Alpha: Support for RA3.large Node Type

### ISSUE THREAD

**Issue by AsadBinImtiaz** [aws/aws-cdk#31634]
### Describe the feature

Amazon Redshift recently introduced the new "RA3.large" instance type, which provides a cost-efficient option for clusters. However, the aws-redshift-alpha construct in the AWS CDK currently does not support this new node type. It would be beneficial to extend the NodeType enum in ClusterProps.nodeType to include RA3.large to enable users to take advantage of this new instance type (see: https://docs.aws.amazon.com/cdk/api/v2/docs/@aws-cdk_aws-redshift-alpha.NodeType.html)

### Use Case

Our team relies on Amazon Redshift for managing large-scale data analytics workloads using aws CDK. With the recent introduction of the RA3.large node type, we see an opportunity to significantly reduce our cluster costs without sacrificing performance.

### Proposed Solution

Extend the NodeType enum within the ClusterProps.nodeType in the aws-redshift-alpha module to include the newly released RA3.large node type:

```
RA3_LARGE: 'ra3.large'
```

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.149

### Environment details (OS name and version, etc.)

MacOS

**Comment by ashishdhingra** [comment]
The value `ra3.large` for [NodeType](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-redshift-cluster.html#cfn-redshift-cluster-nodetype) is not yet available for [AWS::Redshift::Cluster](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-redshift-cluster.html) resource in CloudFormation per [aws-redshift-cluster.json](https://github.com/cdklabs/awscdk-service-spec/blob/main/sources/CloudFormationSchema/us-east-1/aws-redshift-cluster.json). This schema JSON file was last updated 2 months ago as of now. Please wait until the schema is updated and CloudFormation resource accepts `ra3.large` as valid `NodeType`.
