### ISSUE TITLE
(aws_ec2): Unable to create dual-stack VPC if no subnets are defined

### ISSUE THREAD

**Issue by tpflueger** [aws/aws-cdk#31641]
### Describe the bug

Our initial CDK setup uses the VPC construct but delays the creation of subnets until later. Note, this worked but it may not be the way CDK is intended to be used. Switching to dual stack IPV4/IPV6, the construct now requires subnets to be defined.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

An ipv6 cidr block to be created that I could use for later subnet creation.

### Current Behavior

CDK throws an exception.
`Unhandled exception. System.Exception: Fn::Cidr's count attribute must be between 1 and 256, 0 was provided.`

### Reproduction Steps

```C#
new Vpc(parent.Construct, Name, new VpcProps
        {
            IpProtocol = IpProtocol.DUAL_STACK,
            VpcName = _name,
            IpAddresses = IpAddresses.Cidr(_cidrBlock.ToString()),
            DefaultInstanceTenancy = DefaultInstanceTenancy.DEFAULT,
            Ipv6Addresses = Ipv6Addresses.AmazonProvided(),
            EnableDnsHostnames = true,
            EnableDnsSupport = true,
            SubnetConfiguration = Array.Empty<SubnetConfiguration>()
        })
````

### Possible Solution

Is subnet now a requirement? If not, it might be useful to allow specifying the Ipv6 CIDR block size.

### CDK CLI Version

2.160.0

### Node.js Version

v22.1.0

### OS

Windows 11

### Language

.NET

### Language Version

.NET 8.0.402

**Comment by ashishdhingra** [comment]
The error is thrown at [Ipv6Addresses.amazonProvided()](https://github.com/aws/aws-cdk/blob/d0c99d85e0bd85beea78ce65f843d319abd493ce/packages/aws-cdk-lib/aws-ec2/lib/ip-addresses.ts#L435C17-L435C31) > [AmazonProvided.createIpv6CidrBlocks()](https://github.com/aws/aws-cdk/blob/d0c99d85e0bd85beea78ce65f843d319abd493ce/packages/aws-cdk-lib/aws-ec2/lib/ip-addresses.ts#L516) (invoked from [here](https://github.com/aws/aws-cdk/blob/d0c99d85e0bd85beea78ce65f843d319abd493ce/packages/aws-cdk-lib/aws-ec2/lib/vpc.ts#L1775C36-L1775C49) > [Fn.cidr()](https://github.com/aws/aws-cdk/blob/19ee46d7653894f0669aff3872c6c5314be0666c/packages/aws-cdk-lib/core/lib/cfn-fn.ts#L176) > [FnCidr()](https://github.com/aws/aws-cdk/blob/19ee46d7653894f0669aff3872c6c5314be0666c/packages/aws-cdk-lib/core/lib/cfn-fn.ts#L672).

Since `AmazonProvided` Ipv6Addresses is used, it expects subnet configuration to be created.

**Comment by pahud** [comment]
yes subnet configuration is like the definition of your subnets for this vpc which tells the subnet cidr, subnet count as well as the mask, which is required for `createIpv6CidrBlocks`.

https://github.com/aws/aws-cdk/blob/d0c99d85e0bd85beea78ce65f843d319abd493ce/packages/aws-cdk-lib/aws-ec2/lib/ip-addresses.ts#L513-L517

**Comment by ashishdhingra** [comment]
@pahud Thanks for elaborating the design.

**Comment by tpflueger** [comment]
Is there a way to delay specifying subnets for IPv6? The creation of the VPC without subnets works until you try to use dual stack. For example, what we are doing is creating the VPC and then separately creating each subnet which works with IPv4. Dual stack puts a requirement of specifying subnets up front.

```C#
var vpc = new Vpc(parent.Construct, Name, new VpcProps
        {
            IpProtocol = IpProtocol.DUAL_STACK,
            VpcName = _name,
            IpAddresses = IpAddresses.Cidr(_cidrBlock.ToString()),
            DefaultInstanceTenancy = DefaultInstanceTenancy.DEFAULT,
            Ipv6Addresses = Ipv6Addresses.AmazonProvided(),
            EnableDnsHostnames = true,
            EnableDnsSupport = true,
            SubnetConfiguration = Array.Empty<SubnetConfiguration>()
        })
new CfnSubnet(parent.Construct, $"Subnet-{cidrBlockName}", new CfnSubnetProps
        {
            CidrBlock = _cidrBlock.ToString(),
            AvailabilityZone = _availabilityZone.ToString(),
            VpcId = vpc .RefId,
            MapPublicIpOnLaunch = _isPublic
        })
````

**Comment by tpflueger** [comment]
The current implementation I am working on made constructs of everything and limited the VPC construct to only create the VPC. Subnets were being handled by a separate construct. I can make the changes to allow the VPC construct to create the subnets instead. I was unsure if this was intended behavior due to IPv4 VPC working without specifying subnets initially.

**Comment by ashishdhingra** [comment]
> The current implementation I am working on made constructs of everything and limited the VPC construct to only create the VPC. Subnets were being handled by a separate construct. I can make the changes to allow the VPC construct to create the subnets instead. I was unsure if this was intended behavior due to IPv4 VPC working without specifying subnets initially.

@tpflueger Thanks for the details. Please confirm if we could close this issue since you might have mitigated your use case.
