### ISSUE TITLE
AwsCdkCli: Unable to provide Environment to Bootstrap command

### ISSUE THREAD

**Issue by joe-eagle-emc** [aws/aws-cdk#31656]
### Describe the bug

I am attempting to run the bootstrap command from a lambda.
```
const cli = AwsCdkCli.fromCdkAppDirectory();
await cli.bootstrap();
```
This gives the error `Error: Specify an environment name like 'aws://123456789012/us-east-1'`.
When running `cdk bootstrap` from the terminal, I would provide this value.  But I don't see anywhere in BootstrapOptions to provide this.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

I would expect to have somewhere here I would provide the environment information.

### Current Behavior

Currently I get this error message `Error: Specify an environment name like 'aws://123456789012/us-east-1'`.

### Reproduction Steps

Run code similar to the following in a lambda.
```
const cli = AwsCdkCli.fromCdkAppDirectory();
await cli.bootstrap();
```

### Possible Solution

Add a field in BootstrapOptions to accept the environment information like "aws://123456789012/us-east-1".

### CDK CLI Version

N/A

### Node.js Version

aws_lambda.Runtime.NODEJS_20_X

### OS

AWS Lambda

### Language

TypeScript

**Comment by pahud** [comment]
Yes, it's unclear to me how to specify that using `AwsCdkCli`.

We'll bring it up to the team for inputs.

**Comment by mrgrain** [comment]
> Yes, it's unclear to me how to specify that using `AwsCdkCli`.
> 
> We'll bring it up to the team for inputs.

Correct, this is not currently possible. Thanks for the report.
