### ISSUE TITLE
iot-alpha: support for creating account audit configuration

### ISSUE THREAD

**Issue by badmintoncryer** [aws/aws-cdk#31663]
### Describe the feature

To create AccountAuditConfiguration L2 construct for AWS IoT alpha module.

### Use Case

AWS Cloudformation supports for creating [account audit configuration](https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-resource-iot-accountauditconfiguration.html) for an [AWS IoT Device Defender](https://docs.aws.amazon.com/iot-device-defender/latest/devguide/device-defender-audit.html) but AWS CDK doesn't.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.160.0

### Environment details (OS name and version, etc.)

irrelevant

**Comment by pahud** [comment]
Thank you for the PR!
