### ISSUE TITLE
(cli): `Stack undefined` in `cdk deploy` output

### ISSUE THREAD

**Issue by meve** [aws/aws-cdk#31685]
### Describe the bug

Running `cdk deploy` using the cli seems to return 'Stack undefined' in some cases.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Last Known Working CDK Version

v2.160.0

### Expected Behavior

To either show:
```
Stack <stackName>
```

Or nothing.

### Current Behavior

I receive output like this:
```shell
sc-pipeline/test/queues (queues)
Stack undefined
sc-pipeline/test/queues (queues): deploying... [2/12]
```

### Reproduction Steps

Run
```shell
cdk deploy
```
. 

### Possible Solution

I included a PR. The cause I suppose is related to https://github.com/aws/aws-cdk/commit/bcf9209fb1b9e9aa295f50c5681201db094b8c00#diff-c7b9751a4ca56b6ee26510c9f650f6d5328f5be39071c93165aadbc138496eddR130. To resolve this, I just copied the condition found on line 42 of the same file, as it checks if `stackName` is defined or not. The comment on the line above seems to be identical as well.

### CDK CLI Version

2.161.1 (build 0a606c9)

### Node.js Version

v18.20.4

### OS

macOS 14.6.1 (23G93)

### Language

TypeScript

**Comment by akhilesh-akza** [comment]
Experiencing same. When I use `NestedStacks` it also seems to randomly fail with a validation error on `stackName` and that `stackName=''` is being passed and shows regex. But last time I checked NestedStacks don't need a stackName?

**Comment by ashishdhingra** [comment]
@meve / @akhilesh-akza Could you please test with `2.161.1 (build 0a606c9)`. There was a regression issue reported in https://github.com/aws/aws-cdk/issues/31654 and CDK team had rollbacked PR that caused that issue.

Thanks,
Ashish

**Comment by meve** [comment]
@ashishdhingra I'm pretty sure the issue is still present in v2.161.1. I think it can be solved by just fixing that condition; it is only hit in the deploy path if I see it correctly:

```
sc-pipeline-stack/test/dynamodb (dynamodb)
Stack undefined
sc-pipeline-stack/test/dynamodb (dynamodb): deploying... [1/12]
dynamodb: creating CloudFormation changeset...
```

Thank you,

Joost

**Comment by akhilesh-akza** [comment]
> @meve / @akhilesh-akza Could you please test with `2.161.1 (build 0a606c9)`. There was a regression issue reported in #31654 and CDK team had rollbacked PR that caused that issue.
> 
> Thanks, Ashish

The specific issue I mentioned is fixed in latest version. It seems default initialised project has frozen version in `package.json` to `2.161.0` and for some reason it's both dependency and devDependencies.

```bash


✨  Synthesis time: 8.36s

Stack undefined
```

But this still exists. Nothing major but better to clean it up so as to not cause confusion that somewhere name is not being read.
