### ISSUE TITLE
(eks): Add support for EKS 1.31 clusters

### ISSUE THREAD

**Issue by JoeNorth** [aws/aws-cdk#31695]
### Describe the feature

Add support for creating EKS 1.31 clusters. The Amazon EKS Construct Library and the `lambda-layer-kubectl` currently only support up to version 1.30.

Existing issue open for the `lambda-layer-kubectl` repo: https://github.com/cdklabs/awscdk-asset-kubectl/issues/1172

### Use Case

Customers are unable to create 1.31 clusters as the latest defined version in the construct library is 1.30.

See https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-eks/lib/cluster.ts#L992

### Proposed Solution

Update the construct library to add a V1_31 KubernetesVersion.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.161.1

### Environment details (OS name and version, etc.)

Any

**Comment by pahud** [comment]
depend on https://github.com/cdklabs/awscdk-asset-kubectl/pull/1173

**Comment by pahud** [comment]
pending review https://github.com/cdklabs/awscdk-asset-kubectl/pull/1190

**Comment by pahud** [comment]
Hi

Given https://github.com/cdklabs/awscdk-asset-kubectl/pull/1190 is merged, we welcome community PRs for aws-eks to add the 1.31 clusters support.
