### ISSUE TITLE
(aws-elasticloadbalancingv2): ALB custom healthcheck port to be opened to target automatically

### ISSUE THREAD

**Issue by heikkis** [aws/aws-cdk#31694]
### Describe the feature

Currently listener.addTargets opens the port for ALB to connect eg. Fargate automatically. But for custom health check port, CDK does not add egress rule for apps SG. So if my app traffic goes to 8080 and health check should go to 8081, only 8080 egress rule is added to app (source ALB sg).

### Use Case

Integration Fargate with custom health check port for ALB.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.154.0

### Environment details (OS name and version, etc.)

MacOS

**Comment by khushail** [comment]
Hi @heikkis , thanks for reaching out.
This health check enabling is something new to me but  I found this repost article that is trying to do the same as you mentioned -https://repost.aws/questions/QUaopUdvIIQymbG8qQjY-m-g/alb-health-checks-port

I would request you to read through it and  respond back if you are trying to do something like this.
Thanks .
