### ISSUE TITLE
aws-cdk-lib/aws-codebuild: Incorrect documentation on LinuxArmBuildImage

### ISSUE THREAD

**Issue by lucacucchetti** [aws/aws-cdk#31717]
### Describe the issue

Hello, I was temporarily thrown off by `LinuxArmBuildImage.fromDockerRegistry` saying the following (being in a class for `aarch64`):

> Returns: a x86-64 Linux build image from a Docker Hub image.

[Source Code](https://github.com/aws/aws-cdk/blob/c1b240ee6fdba9a0ca1126c97c5e0173bae007ce/packages/aws-cdk-lib/aws-codebuild/lib/linux-arm-build-image.ts#L45C6-L45C23).

### Links

https://github.com/aws/aws-cdk/blob/c1b240ee6fdba9a0ca1126c97c5e0173bae007ce/packages/aws-cdk-lib/aws-codebuild/lib/linux-arm-build-image.ts#L45C6-L45C23

**Comment by khushail** [comment]
Hi @lucacucchetti ,thanks for reaching out. 

Yes, I can confirm by looking at the cdk doc for this module as well -

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_codebuild.LinuxArmBuildImage.html


<img width="741" alt="Screenshot 2024-10-10 at 11 46 36 AM" src="https://github.com/user-attachments/assets/e91fcd85-9314-4d00-bea1-c39e1e5dbe3c">

Yes, this surely needs to be corrected. 
Thanks.
