### ISSUE TITLE
aws_stepfunctions: StateMachine construct doesn't generate a valid policy for default StateMachineRole

### ISSUE THREAD

**Issue by JamieClayton7** [aws/aws-cdk#31714]
### Describe the bug

When using `aws_stepfunctions.StateMachine`, the default IAM policy for the state machine role does not generate the correct statement for the action `ecs:RunTask`.

The difference being that we now must specify the revision number (or all revisions by omitting the number and simply adding `:`) tagged onto the task definition ARN.

From 15th October 2024, the statement generated will result in an AccessDeniedException when the state machine attempts to RunTask on the non-tagged task definition ARN.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Last Known Working CDK Version

N/A

### Expected Behavior

The valid statement that should be generated:
```json
{
    "Action": "ecs:RunTask",
    "Resource": "arn:aws:ecs:eu-west-1:12345:task-definition/TaskDefinitionABC1234:1",
    "Effect": "Allow"
}
```

### Current Behavior

The statement generated: 
```json
{
    "Action": "ecs:RunTask",
    "Resource": "arn:aws:ecs:eu-west-1:12345:task-definition/TaskDefinitionABC1234",
    "Effect": "Allow"
}
```

### Reproduction Steps

```typescipt

// exectionRole

const taskDefinition = new ecs.FargateTaskDefinition(this, 'TaskDefinition', {
  cpu: 256,
  executionRole,
  memoryLimitMiB: 512,
});

// container definitions...

const stateMachineDefinition = new tasks.EcsRunTask(this, 'Run Traffic DB maintenance jobs', {
  cluster,
  launchTarget: new tasks.EcsFargateLaunchTarget(),
  taskDefinition,
  integrationPattern: sfn.IntegrationPattern.RUN_JOB,
});

const stateMachine = new sfn.StateMachine(this, 'StateMachine', {
    definition: stateMachineDefinition,
    stateMachineName: 'StateMachine',
    stateMachineType: sfn.StateMachineType.STANDARD,
    timeout: Duration.hours(2),
    tracingEnabled: true,
});
```

### Possible Solution

CDK synth should generate the correct IAM statement for state machines ecs:RunTask by using the task definition role ARN with the revision tag attached to the task definition.

Work around for the time being:

```typescipt

// exectionRole

const taskDefinition = new ecs.FargateTaskDefinition(this, 'TaskDefinition', {
  cpu: 256,
  executionRole,
  memoryLimitMiB: 512,
});

// container definitions...

const stateMachineDefinition = new tasks.EcsRunTask(this, 'Run Traffic DB maintenance jobs', {
  cluster,
  launchTarget: new tasks.EcsFargateLaunchTarget(),
  taskDefinition,
  integrationPattern: sfn.IntegrationPattern.RUN_JOB,
});

const stateMachine = new sfn.StateMachine(this, 'StateMachine', {
    definition: stateMachineDefinition,
    stateMachineName: 'StateMachine',
    stateMachineType: sfn.StateMachineType.STANDARD,
    timeout: Duration.hours(2),
    tracingEnabled: true,
});

// WORK AROUND 
// Create a new policy
const policy = new iam.Policy(this, 'RunTaskPolicy', {
  statements: [
    new iam.PolicyStatement({
      actions: ['ecs:RunTask'],
      resources: [`${taskDefinition.taskDefinitionArn}`]
    })
  ]
});

// Attach the new policy to the state machine
policy.attachToRole(stateMachine.role)
```

### CDK CLI Version

2.161.1 (build 0a606c9)

### Node.js Version

v22.9.0

### OS

MacOS

### Language

TypeScript

**Comment by khushail** [comment]
Hi @JamieClayton7 , thanks for reaching out.

I tried to deploy the source code and see this `ecs:runtask` policy added to the role as -

```json
{
	"Version": "2012-10-17",
	"Statement": [
		{
			"Action": "ecs:RunTask",
			"Resource": "arn:aws:ecs:us-west-1:123456789012:task-definition/StepfunctionIssueStackTaskDefinition64A4E983:*",
			"Effect": "Allow"
		},
```

which seems exactly as its supposed to be. I am not sure why you expect the resource to have value as stated above.

This [PR](https://github.com/aws/aws-cdk/pull/30788/files) introduced the change to correct the arn returned -([Original issue](https://github.com/aws/aws-cdk/issues/30751)).

**Comment by khushail** [comment]
could you please share the article link where is says it should be generated with tag?

**Comment by khushail** [comment]
I found an article on this task definition with revision number -

https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonelasticcontainerservice.html#amazonelasticcontainerservice-task-definition
 
 and this PR seems to be merged 3 days ago -https://github.com/aws/aws-cdk/pull/31615 which addresses the same issue
