### ISSUE TITLE
`aws-cdk-lib.aws_apigatewayv2`: confusing wording for `HttpApi.disableExecuteApiEndpoint`

### ISSUE THREAD

**Issue by anentropic** [aws/aws-cdk#31729]
### Describe the issue

> ### disableExecuteApiEndpoint?
> Type: `boolean` _(optional, default: false execute-api endpoint enabled.)_
>
> Specifies whether clients can invoke your API using the default endpoint.
>
> By default, clients can invoke your API with the default `https://{api_id}.execute-api.{region}.amazonaws.com` endpoint. Enable this if you would like clients to use your custom domain name.

I think this means if you want to use a custom domain you should set `disableExecuteApiEndpoint=true` ?
I'm pretty sure that's how I would want it to behave.

It is confusing because the wording says "enable this" but the param is called "disable...", so it's unclear if it means to enable the disabling flag, or to enable the thing that the disabling flag disables.

### Links

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_apigatewayv2.HttpApi.html#disableexecuteapiendpoint

**Comment by ashishdhingra** [comment]
Created PR https://github.com/aws/aws-cdk/pull/31734 to make documentation more clearer.
