### ISSUE TITLE
aws_codebuild: REPOSITORY_NAME/WORKFLOW_NAME webhook filters and webhook scope configuration

### ISSUE THREAD

**Issue by colyoonamaz** [aws/aws-cdk#31736]
### Describe the feature

CodeBuild webhooks in CDK should support the REPOSITORY_NAME/WORKFLOW name filters e.g.
```
const source = codebuild.Source.gitHub({
      owner: 'owner',
      repo: 'repo',
      webhook: true,
      webhookFilters: [FilterGroup.inEventOf(EventAction.WORKFLOW_JOB_QUEUED).andRepositoryNameIs("repo_name")],
    })
```
as these filter types are currently missing (https://docs.aws.amazon.com/codebuild/latest/APIReference/API_WebhookFilter.html). Additionally, there is no option to provide a scope configuration for the webhook in the source (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-scopeconfiguration.html).

### Use Case

The REPOSITORY_NAME/WORKFLOW_NAME filters are used to filter out organization/global webhook events, so that the webhook doesn't trigger builds for specific repositories/workflows. Additionally, scope configuration is needed to create an organization or global webhook (https://docs.aws.amazon.com/codebuild/latest/userguide/github-global-organization-webhook.html)

### Proposed Solution

Add repository name and workflow name to the list of webhook filters and allow a scope configuration to be provided in the source for the webhook

### Acknowledgements

- [X] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### CDK version used

2.162.1

### Environment details (OS name and version, etc.)

Any

**Comment by khushail** [comment]
Hi @colyoonamaz , thanks for reaching out.

Is this FR in accordance with this bug reported - https://github.com/aws/aws-cdk/issues/31726

Could you please check and share your insights ?

**Comment by dviryamin** [comment]
I've submitted a PR that adds support for creating GitHub organization-level webhooks directly in the GitHubSource construct for CodeBuild.

However, I'm currently running into issues with building the aws-cdk-lib package locally and could use some help testing this feature. If anyone can assist by setting up a CodeBuild project with the new organization webhook property and verifying that it works as expected, I would greatly appreciate it!

Thanks in advance for any help and feedback!

**Comment by khushail** [comment]
Thanks @dviryamin for submtting a PR. For guidance/help, you could-
1. Reach out to [CDK.DEV community](https://cdk.dev/) and ask for help.
2. [Youtube tutorials](https://www.youtube.com/@CDK-Live).
3. [Community posts](https://community.aws/content/2jhmIXdVWZJy3uJnUfEzEmp652j/contributing-to-aws-cdk).

Hope this would be helpful!

**Comment by colyoonamaz** [comment]
@khushail, https://github.com/aws/aws-cdk/issues/31726 looks like a separate issue, as this is in relation to missing attributes rather than webhook creation failures

**Comment by dviryamin** [comment]
Hi @colyoonamaz,
Thank you so much for your guidance and help! I was able to successfully build the aws-cdk-lib package locally and test my pull request with the new organization webhook feature. Everything worked as expected on my end.

It would be great if you could test it out as well and let me know if it resolves the issue you were facing. I’d really appreciate your feedback!

**Comment by shivatalwar** [comment]
> I've submitted a PR that adds support for creating GitHub organization-level webhooks directly in the GitHubSource construct for CodeBuild.
> 
> However, I'm currently running into issues with building the aws-cdk-lib package locally and could use some help testing this feature. If anyone can assist by setting up a CodeBuild project with the new organization webhook property and verifying that it works as expected, I would greatly appreciate it!
> 
> Thanks in advance for any help and feedback!

@dviryamin could you post a snippet on how to currently get this done configuring the underlying codebuild CfnProject, until your PR is reviewed and merged?

**Comment by dviryamin** [comment]
@shivatalwar I just posted a [Gist Post](https://gist.github.com/dviryamin/a062b769575740c8469e7c1012526737) with detailed tutorial

**Comment by colyoonamaz** [comment]
Thanks, marked the issue as completed
