### ISSUE TITLE
aws-batch: Malformed Instance Type thrown for new InstanceType("optimal") regardless of architecture

### ISSUE THREAD

**Issue by DaveMadsen** [aws/aws-cdk#31762]
### Describe the bug

We use `new InstanceType("optimal")` in our platform for batch resources. In the past, this has "just worked." Now we are getting an error, `Resolution error: Malformed instance type identifier`. I expect this to "just work".

it looks like [this commit](https://github.com/aws/aws-cdk/commit/7e80cc9665c0a1f7e82b124991d946a4234313c2#diff-7ae09067a7ce8a58d494da3c01be13161be021e9cdb96008221d6e16cd0366b3R1145) broke us in 2.161.1. If I understand what is happening, a check was added to block `optimal` use (or at least warn against its use) on `ARM64` instances, but it looks like the architecture check is breaking because `optimal` is not yet resolved into a valid architecture.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Last Known Working CDK Version

2.160.0

### Expected Behavior

I am able to use `new InstanceType("optimal")` on `x86-64` architecture.

### Current Behavior

`new InstanceType("optimal") throws `Resolution error: Malformed instance type identifier` on all architectures.

### Reproduction Steps

let instanceType = new InstanceType("optimal");

### Possible Solution

"optimal" needs to resolve into the target instance types before doing the architecture check. Longer term, "optimal" should be deprecated/removed or expanded to ARM64 archs.

### CDK CLI Version

2.161.1 (build 0a606c9)

### Node.js Version

v18.20.4

### OS

Linux 5.10 x86_64

### Language

TypeScript

### Language Version

TypeScript ~4.7.4

**Comment by khushail** [comment]
Hi @DaveMadsen , thanks for reaching out.

this is what I found about 'Optimal' types in cdk docs-

https://github.com/aws/aws-cdk/tree/main/packages/aws-cdk-lib/aws-batch

I also deployed the cdk stack with CDK Version 2.160 and 2.162, both deployed successfully for me.
Sharing the code and snippets -

CDK Version 2.160 - Typescript code -
```ts
    const vpc01 = ec2.Vpc.fromLookup(this, 'myVpc', {
      isDefault: true,
      });
      
    const computeEnvironment = new batch.ManagedEc2EcsComputeEnvironment(this, 'myEc2ComputeEnv', {
      instanceTypes: [ec2.InstanceType.of(ec2.InstanceClass.M5AD, ec2.InstanceSize.LARGE)],
      useOptimalInstanceClasses: true, // default
      vpc: vpc01,
    });
```

synthesized template snippet -

```json
  "myEc2ComputeEnvF0625F52": {
   "Type": "AWS::Batch::ComputeEnvironment",
   "Properties": {
    "ComputeResources": {
     "AllocationStrategy": "BEST_FIT_PROGRESSIVE",
     "InstanceRole": {
      "Fn::GetAtt": [
       "myEc2ComputeEnvInstanceProfileEACE4CE2",
       "Arn"
      ]
     },
     "InstanceTypes": [
      "m5ad.large",
      "optimal"
     ],
     "MaxvCpus": 256,
     "MinvCpus": 0,
     "SecurityGroupIds": [
      {
       "Fn::GetAtt": [
        "myEc2ComputeEnvSecurityGroupD0EB1CF5",
        "GroupId"
       ]
      }
     ],
```

Same code deployed with CDK Version 2.162.0 and it deployed successfully -

<img width="1151" alt="Screenshot 2024-10-17 at 2 29 55 PM" src="https://github.com/user-attachments/assets/2d0dff49-f476-479c-b6f1-043bbaa457f2">

Would request you to please share a minimal repro code for the above mentioned issue as I am not able to repro it on my side.
