### ISSUE TITLE
s3: support `TransitionDefaultMinimumObjectSize` for life cycle

### ISSUE THREAD

**Issue by go-to-k** [aws/aws-cdk#31777]
### Describe the feature

TransitionDefaultMinimumObjectSize for lifecycles has been supported: https://aws.amazon.com/about-aws/whats-new/2024/09/amazon-s3-default-minimum-object-size-lifecycle-transition-rules

Cfn doc: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-lifecycleconfiguration.html#cfn-s3-bucket-lifecycleconfiguration-transitiondefaultminimumobjectsize

### Use Case

It can be possible to indicate which default minimum object size behavior is applied to the lifecycle configuration.

### Proposed Solution

Add `TransitionDefaultMinimumObjectSize` to BucketProps.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.162.0

### Environment details (OS name and version, etc.)

Mac

**Comment by ashishdhingra** [comment]
- Per [AWS::S3::Bucket LifecycleConfiguration](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-lifecycleconfiguration.html#cfn-s3-bucket-lifecycleconfiguration-transitiondefaultminimumobjectsize), S3 Bucket `LifecycleConfiguration` property has [TransitionDefaultMinimumObjectSize](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-lifecycleconfiguration.html#cfn-s3-bucket-lifecycleconfiguration-transitiondefaultminimumobjectsize) as one of the child-property.
- However, in [Bucket](https://github.com/aws/aws-cdk/blob/7815144ece5fd95e80177cd3aa6f9dcaca602651/packages/aws-cdk-lib/aws-s3/lib/bucket.ts#L1720) L2 construct doesn't allow setting `transitionDefaultMinimumObjectSize` property which is available in L1 [CfnBucket. LifecycleConfigurationProperty](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_s3.CfnBucket.LifecycleConfigurationProperty.html) interface.
- `AWS::S3::Bucket LifecycleConfiguration` is set [here](https://github.com/aws/aws-cdk/blob/7815144ece5fd95e80177cd3aa6f9dcaca602651/packages/aws-cdk-lib/aws-s3/lib/bucket.ts#L1941) while returning `CfnBucket` object.

Although escape hatch could be workaround, this feature request fills the gap in L2 `Bucket` construct.
