### ISSUE TITLE
iot: support for scheduled audit configuration

### ISSUE THREAD

**Issue by badmintoncryer** [aws/aws-cdk#31779]
### Describe the feature

Add AWS IoT Scheduled Audit construct for AWS CDK.

### Use Case

Cloudformation supports for creating scheduled audit configuration but CDK does not support this.

<https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-resource-iot-scheduledaudit.html>

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.161.0

### Environment details (OS name and version, etc.)

irrelevant

**Comment by khushail** [comment]
Thanks @badmintoncryer for the request and submitting a PR!
