### ISSUE TITLE
aws-lambda-nodejs: incomprehensible documentation for `bundleAwsSDK`

### ISSUE THREAD

**Issue by wimlewis-amazon** [aws/aws-cdk#31789]
### Describe the issue

The sentence starting "This will be essentially exclude sdk..." is difficult to extract any meaning from. I can guess kinda what it means by context and from being pretty familiar with this module, but it would be nice if it were grammatical and said something.

### Links

https://github.com/aws/aws-cdk/blob/799b541135d0fb9cea31ddf29a8dacc1a94cb0fc/packages/aws-cdk-lib/aws-lambda-nodejs/README.md?plain=1#L178

**Comment by khushail** [comment]
@wimlewis-amazon , thanks for highlighting the grammatical mistake in docs. it should be corrected.
