### ISSUE TITLE
aws_codestarnotifications: Creating unreachable notification rules

### ISSUE THREAD

**Issue by cjhelloletsgo** [aws/aws-cdk#31784]
### Describe the bug

The aws_cdk.aws_codestarnotifications NotificationRule and CfnNotificationRule constucts both create notification rules which are unable to reach a sns target.
![image](https://github.com/user-attachments/assets/68d5889e-46dd-4a54-ae2a-a86fb2c6e8c6)

The correct policy is added to the sns topic according to the docs but the topic is always unreachable.
![image](https://github.com/user-attachments/assets/8ad4d319-f3f9-42d4-a25a-a5f0ebf870d9)
https://docs.aws.amazon.com/dtconsole/latest/userguide/notification-target-create.html?icmpid=docs_acn_console_acp

Creating a sns topic target through the console works fine and if i describe a notification rule with a target created by the cdk it looks identical to the ui created target.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

The sns topic should have an Active Notification target status.

### Current Behavior

The target SNS topic is in an Unreachable Notification target status.

### Reproduction Steps

Code example:

``` python

import aws_cdk.aws_codestarnotifications as notifications
from aws_cdk import (
    aws_codepipeline as codepipeline,
)
from aws_cdk import (
    aws_codepipeline_actions as codepipeline_actions,
)
from aws_cdk import aws_sns as sns

 pipeline_topic = sns.Topic(
     self,
    "Pipeline Topic",
    display_name="Pipeline Topic",
    enforce_ssl=True,
)

pipeline = codepipeline.Pipeline(
    self,
    "Pipeline",
    pipeline_type=codepipeline.PipelineType.V2,
    triggers=[],
    stages=[
        codepipeline.StageProps(
            stage_name="Source",
            actions=[
                codepipeline_actions.CodeStarConnectionsSourceAction(
                    action_name="Github_Source",
                    owner=github_account_owner,
                    repo=github_repo,
                    branch=git_repo_branch,
                    output=source_output,
                    connection_arn=code_connection,
                    trigger_on_push=True,
                    run_order=1,
                ),
            ],
        ),
    ],
    restart_execution_on_update=True,
)

notification_rule = notifications.NotificationRule(
    self,
    "Notification Rule",
    source=pipeline,
    events=[
        "codepipeline-pipeline-pipeline-execution-failed",
        "codepipeline-pipeline-action-execution-failed",
        "codepipeline-pipeline-stage-execution-failed",
        "codepipeline-pipeline-manual-approval-failed",
    ],
    targets=[
        pipeline_topic,
    ],
    enabled=True,
    detail_type=notifications.DetailType.FULL,
)
```

### CDK CLI Version

2.162.1 (build 10aa526)

### Node.js Version

v20.18.0

### OS

Ubuntu 24.04

### Language

Python

### Language Version

Python 3.12.3

**Comment by cjhelloletsgo** [comment]
This doesn't happen if you deploy in one go. I think it is caused by adding the target after the notification rule is already created.

**Comment by khushail** [comment]
Hey @cjhelloletsgo , thanks for reaching out.
Could you please check the Topics access policy statement because as per [AWS Docs](https://docs.aws.amazon.com/dtconsole/latest/userguide/set-up-sns.html) , it should look like the following -

```json
{
  "Version": "2008-10-17",
  "Id": "__default_policy_ID",
  "Statement": [
    {
      "Sid": "__default_statement_ID",
      "Effect": "Allow",
      "Principal": {
        "AWS": "*"
      },
      "Action": [
        "SNS:GetTopicAttributes",
        "SNS:SetTopicAttributes",
        "SNS:AddPermission",
        "SNS:RemovePermission",
        "SNS:DeleteTopic",
        "SNS:Subscribe",
        "SNS:ListSubscriptionsByTopic",
        "SNS:Publish"
      ],
      "Resource": "arn:aws:sns:us-east-2:123456789012:codestar-notifications-MyTopicForNotificationRules",
      "Condition": {
        "StringEquals": {
          "AWS:SourceOwner": "123456789012"
        }
      }
    },
	{
      "Sid": "AWSCodeStarNotifications_publish",
      "Effect": "Allow",
      "Principal": {
        "Service": [
          "codestar-notifications.amazonaws.com"
        ]
      },
      "Action": "SNS:Publish",
      "Resource": "arn:aws:sns:us-east-2:123456789012:codestar-notifications-MyTopicForNotificationRules"
    }
  ]
}
```
