### ISSUE TITLE
ivs: support RecordingConfiguration for channel

### ISSUE THREAD

**Issue by mazyu36** [aws/aws-cdk#31780]
### Describe the feature

[RecordingConfiguration](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ivs.CfnChannel.html#recordingconfigurationarn) is not supported in current alpha [Channel](https://docs.aws.amazon.com/cdk/api/v2/docs/@aws-cdk_aws-ivs-alpha.Channel.html) Construct.

### Use Case

To use recording configuration.

### Proposed Solution

* Add `RecordingConfiguration` Construct.
* Add `recordingConfiguration` property to the `Channel`.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.162.0

### Environment details (OS name and version, etc.)

all

**Comment by ashishdhingra** [comment]
- [AWS::IVS::Channel](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ivs-channel.html#cfn-ivs-channel-recordingconfigurationarn) supports `RecordingConfigurationArn` as one of the properties.
- `RecordingConfigurationArn` maps to ARN of [AWS::IVS::RecordingConfiguration](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ivs-recordingconfiguration.html) resource.
- IVS L1 constructs:
  - [CfnChannel](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ivs.CfnChannel.html#recordingconfigurationarn) supports `recordingConfigurationArn` property.
  - [CfnRecordingConfiguration](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ivs.CfnRecordingConfiguration.html) represents `AWS::IVS::RecordingConfiguration` resource.
- In [aws-ivs-alpha](https://github.com/aws/aws-cdk/tree/main/packages/%40aws-cdk/aws-ivs-alpha) package,
  - [Channel](https://github.com/aws/aws-cdk/blob/893769ed22818a6c31ec1bdd58d458f50ba28c48/packages/%40aws-cdk/aws-ivs-alpha/lib/channel.ts#L161C14-L161C21) doesn't support `recordingConfigurationArn`.
  - There is no L2 `RecordingConfiguration` construct.
- ther
