### ISSUE TITLE
stepfunctions: support dynamic bucket in Map ItemReader

### ISSUE THREAD

**Issue by gael-ft** [aws/aws-cdk#31807]
### Describe the feature

Goal is to allow using `JsonPath` for [IItemReader](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_stepfunctions.IItemReader.html#properties) properties when defining a `Map`.

For now, interface [IItemReader](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_stepfunctions.IItemReader.html#properties) defines `bucket` field as type `IBucket`.

But from a CFN perspective we only need a bucket name.
Using `IBucket` blocks users from using `JsonPath` as dynamic bucket name.

Example:

```typescript
const distributedMap = new sfn.DistributedMap(this, 'Distributed Map State', {
  itemReader: new sfn.S3JsonItemReader({
    bucket: JsonPath.stringAt('$.myBucket'),
    key: JsonPath.stringAt('$.myKey'),
  }),
  // ...
});
```

```json
"ItemReader": {
    "Resource": "arn:aws:states:::s3:getObject",
    "ReaderConfig": {
        "InputType": "JSON"
    },
    "Parameters": {
        "Bucket.$": "$.myBucket",
        "Key.$": "$.myKey"
    }
}
```

[Current CDK implementation](https://github.com/aws/aws-cdk/blob/v2.162.1/packages/aws-cdk-lib/aws-stepfunctions/lib/states/distributed-map/item-reader.ts#L206-L210)

### Use Case

Using the provided construct instead of a `CustomState` for `DistributedMap`.

### Proposed Solution

Simply using `string` instead of `IBucket` (possibly accepting both if necessary ?)

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.162.1

### Environment details (OS name and version, etc.)

macOS 13.5

**Comment by khushail** [comment]
Hi @gael-ft , thanks for reaching out.

I found a previous similar issue reg the support of Dynamic bucket in Map ItemReader - https://github.com/aws/aws-cdk/issues/29409 and PR seems to be merged 4 days ago -https://github.com/aws/aws-cdk/pull/31619

Please let me know if that works as per your usecase.

**Comment by gael-ft** [comment]
Hello @khushail,

Ok thanks for linking, didn't find it ...
Looks to be release with in v2.163.
