### ISSUE TITLE
cognito: support email for multi-factor authentication (MFA) 

### ISSUE THREAD

**Issue by mazyu36** [aws/aws-cdk#31815]
### Describe the feature

Cognito now supports email for MFA.

Ref: https://aws.amazon.com/about-aws/whats-new/2024/09/amazon-cognito-user-pools-email-authentication-option/?nc1=h_ls

In CloudFormation, `EMAIL_OTP` was added to [EnabledMfas](https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpool.html#cfn-cognito-userpool-enabledmfas) property at [October 15, 2024](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html).

This options is not supported yet in L2 Construct.

### Use Case

To use email MFA

### Proposed Solution

Add email option to [MfaSecondFactor](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_cognito.MfaSecondFactor.html).

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.162.0

### Environment details (OS name and version, etc.)

All

**Comment by ashishdhingra** [comment]
[MfaSecondFactor](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_cognito.MfaSecondFactor.html) is processed [here](https://github.com/aws/aws-cdk/blob/318eae6c9eca456e0c34ed21855dad9d2bfa2a0f/packages/aws-cdk-lib/aws-cognito/lib/user-pool.ts#L1226), which is used to set `enabledMfas` when creating [CfnUserPool](https://github.com/aws/aws-cdk/blob/318eae6c9eca456e0c34ed21855dad9d2bfa2a0f/packages/aws-cdk-lib/aws-cognito/lib/user-pool.ts#L1011) object. `EMAIL_OTP` support needs to be set in `enabledMfas`.

@mazyu36 Thanks for the PR contribution.
