### ISSUE TITLE
(aws-glue-alpha): (add jobRunQueuingEnabled to Job)

### ISSUE THREAD

**Issue by jdebuseamazon** [aws/aws-cdk#31826]
### Describe the feature

Add the [jobRunQueuingEnabled](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_glue.CfnJob.html#jobrunqueuingenabled) property of [CfnJob](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_glue.CfnJob.html) within [aws-cdk-lib/aws-glue](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_glue-readme.html) to [Job](https://docs.aws.amazon.com/cdk/api/v2/docs/@aws-cdk_aws-glue-alpha.Job.html) within [@aws-cdk/aws-glue-alpha](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-glue-alpha-readme.html).

### Use Case

Setting this property currently requires a [raw override](https://docs.aws.amazon.com/cdk/v2/guide/cfn_layer.html#develop-customize-override); for example

```ts
(job.node.defaultChild as CfnJob).addOverride('Properties.JobRunQueuingEnabled', true)
```

### Acknowledgements

- [X] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### CDK version used

v2.162.1

### Environment details (OS name and version, etc.)

macOS Sequoia 15.0.1

**Comment by ashishdhingra** [comment]
[AWS::Glue::Job](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-job.html) supports [JobRunQueuingEnabled](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-job.html#cfn-glue-job-jobrunqueuingenabled) property. This is available in [CfnJob](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_glue.CfnJob.html) L1 construct as `jobRunQueuingEnabled`, but not available in [Job](https://github.com/aws/aws-cdk/blob/318eae6c9eca456e0c34ed21855dad9d2bfa2a0f/packages/%40aws-cdk/aws-glue-alpha/lib/job.ts#L643C14-L643C17) L2 (experimental) construct.

@jdebuseamazon Thanks for the PR contribution.
