### ISSUE TITLE
community review workflow stuck with `Action Required` state

### ISSUE THREAD

**Issue by tmokmss** [aws/aws-cdk#31870]
### Describe the bug

Hi, apparently the community review workflow is not working now. It seems an approval from a maintainer is required to run the PR linter workflow. PR: https://github.com/aws/aws-cdk/pull/31212

These runs are left pending since yesterday: [#1](https://github.com/aws/aws-cdk/actions/runs/11465124810), [#2](https://github.com/aws/aws-cdk/actions/runs/11465124815)

Can someone from the core team approve the workflow execution? Also, do we need the approval for each PR?

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

PR linter workflow runs and if there is an approval review, a tag (`pr/needs-maintainer-review`) is added. As [described here](https://github.com/aws/aws-cdk/wiki/CDK-Community-PR-Reviews#priorities).

### Current Behavior

PR linter workflow stuck with pending approval.

### Reproduction Steps

leave a community review to a PR.

### CDK CLI Version

2.163.1

### Node.js Version

20

### OS

macos

### Language

TypeScript

**Comment by khushail** [comment]
Hi @tmokmss ,thanks for reporting this. 
```
Can someone from the core team approve the workflow execution? Also, do we need the approval for each PR?
```
Reaching out to core team, requesting their inputs and action.

**Comment by khushail** [comment]
@tmokmss , core team is aware of this issue and is already working towards this.

I would be moving this issue to team's project board for visibility and further action.

Appreciate you having patience here !

**Comment by kaizencc** [comment]
Thanks for bringing this up @tmokmss. I don't think our existing github action triggers will work with our new settings anymore. The best I can think of is creating a new github action that runs hourly over all open PRs and either runs the linter or just the community review workflow. It won't be as nice as a trigger on reviews, but it will be better than what we have now :/

I'll try to get this up and running this week.

**Comment by kaizencc** [comment]
Hi @tmokmss, the underlying setting was changed back to what it used to be -- require approval for first time contributors. I'm keeping this ticket open until we can confirm that the community review workflow works again. I would really appreciate it if you can let me know if one of your reviews works without manual intervention!

**Comment by tmokmss** [comment]
Hi @kaizencc sorry for the delayed response. I approved another PR https://github.com/aws/aws-cdk/pull/31996 but I'm afraid it is not working as expected. It is not getting a new label although the OP is not a first time contributor..
