### ISSUE TITLE
aws-cdk-lib/aws-iam.ServicePrincipal: No Longer Translating Endpoints for GovCloud

### ISSUE THREAD

**Issue by quantumew** [aws/aws-cdk#31905]
### Describe the bug

I have a service sitting on CDK 2.140.0, works fine, when using service principal to allow our StateMachine to assume a role we created, ServicePrincipal properly uses the URI that is correct for Gov Cloud: "states.us-gov-west-1.amazonaws.com". After upgrading CDK, it stops translating "states.amazonaws.com" to the correct URI. Is this intentional? Do we need to update our code? This was a handy feature, getting the correct URI from service principal for our region, wanted to make sure it wasn't remove unintentionally.

### Regression Issue

- [X] Select this option if this issue appears to be a regression.

### Last Known Working CDK Version

2.140.0

### Expected Behavior

ServicePrincipal translates input to the correct URI for states in gov cloud.

### Current Behavior

ServicePrincipal uses the commercial cloud URI for states.

### Reproduction Steps

Create a role

```
new Role(this, 'StepFunctionRole', {
  roleName: `some-test`,
  description: `Execution role for step function`,
  assumedBy: new ServicePrincipal('states.amazonaws.com')
})
```

This previously resulted in:

```
{
       Action: 'sts:AssumeRole',
       Effect: 'Allow',
       Principal: { Service: 'states.us-gov-west-1.amazonaws.com' }
}
```

Now it results in:

```
{
      Action: 'sts:AssumeRole',
      Effect: 'Allow',
      Principal: { Service: 'states.amazonaws.com' }
}
```

### Possible Solution

I admittedly haven't cracked the code, so not sure on this one.

### CDK CLI Version

2.140.0

### Node.js Version

18.20.4

### OS

Same regardless of OS

### Language

TypeScript

### Language Version

4.8.3

**Comment by ashishdhingra** [comment]
@quantumew Good morning. Thanks for reporting the issue. The change was perhaps introduced in [commit](https://github.com/aws/aws-cdk/commit/4af3685888383e5451884bc6a9ddde7f0cdefa0c#diff-50248f671e9b13a9cb35a62441d72832dca89b6c7ad4a88aa4fb2ec8e676b7cdR946) where it removed the legacy behavior and always now uses new standardized behavior. Similar issue was reported in https://github.com/aws/aws-cdk/issues/31767. The workaround provided is to use `iam.ServicePrincipal.fromStaticServicePrincipleName()` (e.g. `iam.ServicePrincipal.fromStaticServicePrincipleName('states.us-gov-west-1.amazonaws.com')`) to mitigate the issue.

Please confirm:
- If new standardized behavior `Principal: { Service: 'states.amazonaws.com' }` works for you?
- If new standardized behavior doesn't work, could you please try using workaround `iam.ServicePrincipal.fromStaticServicePrincipleName('states.us-gov-west-1.amazonaws.com')` for your use case?

Thanks,
Ashish
