### ISSUE TITLE
Init templates recommend "npm run cdk", should be "npx cdk"

### ISSUE THREAD

**Issue by rix0rrr** [aws/aws-cdk#3191]
For example, "npm run cdk diff" makes an exit code of 1 spew out an ugly error message, npx wouldn't have that.

* **I'm submitting a ...**
  - [x] :beetle: bug report
  - [ ] :rocket: feature request
  - [] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/awslabs/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

**Comment by shivlaks** [comment]
Init-templates do not contain `npm run cdk ...` commands anymore.
