### ISSUE TITLE
ec2: pricing api interface vpc endpoint duplicated

### ISSUE THREAD

**Issue by mazyu36** [aws/aws-cdk#31911]
### Describe the bug

`InterfaceVpcEndpointAwsService('pricing.api')` enum duplicated.

https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-ec2/lib/vpc-endpoint.ts#L518

https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-ec2/lib/vpc-endpoint.ts#L520

These are added in #31882 and #31907.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

Only one `InterfaceVpcEndpointAwsService('pricing.api')` enum exists.

### Current Behavior

`InterfaceVpcEndpointAwsService('pricing.api')` enum duplicated.

### Reproduction Steps

N/A

### CDK CLI Version

maybe not released yet

### Node.js Version

irrelevant

### OS

irrelevant

### Language

TypeScript

**Comment by ashishdhingra** [comment]
Issue closed by related PR.
