### ISSUE TITLE
cdk context command only mentions cdk.json

### ISSUE THREAD

**Issue by Doug-AWS** [aws/aws-cdk#3193]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/awslabs/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
If you run ```cdk context``` and have context info in *cdk.context.json*, the command erroneously introduces the output with: "Context found in cdk.json:". It also mixes context info found in *cdk.json* as well as context info found in *cdk.context.json*.

* **What is the expected behavior (or behavior of feature suggested)?**
I would expect the command to separate the output based on where it found the context info.

* **What is the motivation / use case for changing the behavior or adding this feature?**

* **Please tell us about your environment:**
  
  - CDK CLI Version: 0.36.0
  - Module Version: xx.xx.xx
  - OS: Windows 10
  - Language: [all]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

**Comment by shivlaks** [comment]
since there's a precedence order that's respected, displaying all discovered output would be confusing because it pushes the cognitive load of deciding what the cdk will use to the user.

I do agree that it might be useful to know the source of a resolved value though...
