### ISSUE TITLE
region-info Fact.find() should throw exception if fact not found

### ISSUE THREAD

**Issue by chelma-amzn** [aws/aws-cdk#3194]
* **I'm submitting a ...**
  - [ ] :beetle: bug report
  - [x] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/awslabs/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*

The current behavior is that when a user uses the @aws-cdk/region-info's Fact.find() method, it may return an undefined result.  This forces users to perform further checking if they want to pass the result to their own code.  

`
const fact = Fact.find(...); // type string?

if (!fact) throw new Error('fact must be provided');

// here fact has type string
`

* **What is the expected behavior (or behavior of feature suggested)?**

The Fact class should define a method that throws an exception if the fact is not found.

* **What is the motivation / use case for changing the behavior or adding this feature?**

This enables users to avoid boilerplate code.

* **Please tell us about your environment:**
  
N/A

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

**Comment by SomayaB** [comment]
Hi @chelma-amzn, thank you for submitting this request! This seems totally reasonable, and not too difficult to implement. If you would like to submit a PR one of us will review it, otherwise someone will update this issue when there is further information!

**Comment by stephendwu** [comment]
@chelma-amzn Posted a question in the glitter group, but are we trying to define a second method that will throw, or have this original method throw?
