### ISSUE TITLE
lambda: Node 22

### ISSUE THREAD

**Issue by w3nl** [aws/aws-cdk#31964]
### Describe the feature

Node 22 is now the active LTS version.
Node 20 is already is already in maintenance mode.
Node 18 is still in maintenance mode, but will end-of-life in 6 months.
https://github.com/nodejs/Release

So I hope I can upgrade soon my AWS lambda functions also to Node 22.

### Use Case

```javascript
import { Runtime } from 'aws-cdk-lib/aws-lambda'
import { NodejsFunction } from 'aws-cdk-lib/aws-lambda-nodejs'

new NodejsFunction(this, 'Example', {
    runtime: Runtime.NODEJS_22_X
})
```

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.162.1

### Environment details (OS name and version, etc.)

Ubuntu 24.04

**Comment by ashishdhingra** [comment]
Node.js 22 runtime support is yet to be supported by Lambda:

<img width="782" alt="Screenshot 2024-10-31 at 2 26 11 PM" src="https://github.com/user-attachments/assets/61d41e09-8608-4434-952c-02904e1eee44">

Also refer [AWS Lambda > Supported runtimes](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html#runtimes-supported).

This feature request for CDK could be implemented once Lambda supports Node.js 22.x runtime.

**Comment by JamesKyburz** [comment]
Lambda always release the Node.js runtime after the Node.js project releases a new LTS version, hopefully it be released soon.

The EOL is also extended in AWS compared with that of Node.js, it starts 3 months after the Node.js EOL and is documented [here](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html)

**Comment by joergbaier** [comment]
Seems to be in the works, they started publishing `nodejs:22` images `2 days ago`
https://gallery.ecr.aws/lambda/nodejs

**Comment by Tietew** [comment]
v2.168.0 has released including NodeJS 22.x support #32104
