### ISSUE TITLE
ElasticLoadBalancingV2: Add Property To Enable Zonal Shift Support in L2 Construct

### ISSUE THREAD

**Issue by hakenmt** [aws/aws-cdk#31983]
### Describe the feature

NLB attributes can only directly be set in the L1 construct. Exposing some of the standard ones, like enabling zonal shift, which requires opt-in, requires additionally calling `SetAttribute` or casting to the L1 construct and adding the key/value to the array of attributes.

### Use Case

Exposing this as a top level property for an NLB helps make users aware they need to opt-in (which is a recent change of behavior) and makes doing so easy.

### Proposed Solution

Add `EnableZonalShift` as a boolean value, defaulting to `false` in the `NetworkLoadBalancer` L2 construct.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.164.0

### Environment details (OS name and version, etc.)

darwin

**Comment by ashishdhingra** [comment]
Appears to be a valid feature request. Per [AWS::ElasticLoadBalancingV2::LoadBalancer LoadBalancerAttribute](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticloadbalancingv2-loadbalancer-loadbalancerattribute.html), the attributes `dns_record.client_routing_policy` and `zonal_shift.config.enabled` are only available for Network Load Balancers. In [NetworkLoadBalancer](https://github.com/aws/aws-cdk/blob/5137e380a22129fd98ffe35caf333162e55149a7/packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/nlb/network-load-balancer.ts#L182C14-L182C33) L2 construct, it exposes [clientRoutingPolicy](https://github.com/aws/aws-cdk/blob/5137e380a22129fd98ffe35caf333162e55149a7/packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/nlb/network-load-balancer.ts#L61) in `NetworkLoadBalancerProps`, which is used to set `dns_record.client_routing_policy` [here](https://github.com/aws/aws-cdk/blob/5137e380a22129fd98ffe35caf333162e55149a7/packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/nlb/network-load-balancer.ts#L262). However, it doesn't expose any property (e.g. `enableZonalShift`) for setting `zonal_shift.config.enabled` attribute.
