### ISSUE TITLE
aws-s3: key rotation is not enabled while creating KMS encrypted S3 buckets

### ISSUE THREAD

**Issue by animesh-bhadouria** [aws/aws-cdk#31982]
### Describe the bug

If an encryption key is not provided while creating the S3 bucket, then S3 construct creates a key by default but it does not enable key rotation. This could cause a security risk on downstream consumers.

S3 bucket creation where key is created without keyrotation enabled
https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-s3/lib/bucket.ts#L2160

Similar example with DynamoDb where keyrotation enabled by default
https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-dynamodb/lib/table.ts#L1696

Change should be straightforward since enableKeyRotation doesn’t require a [replacement on update](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kms-key.html#cfn-kms-key-enablekeyrotation).

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

S3 created KMS keys to have key rotation enabled

### Current Behavior

S3 created KMS keys do not enable key rotation

### Reproduction Steps

https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-s3/lib/bucket.ts#L2160

### Possible Solution

https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-dynamodb/lib/table.ts#L1696

### CDK CLI Version

Latest

### Node.js Version

18

### OS

AL2

### Language

Java

**Comment by ashishdhingra** [comment]
Per code [here](https://github.com/aws/aws-cdk/blob/5137e380a22129fd98ffe35caf333162e55149a7/packages/aws-cdk-lib/aws-s3/lib/bucket.ts#L2203), if the `props.encryption` is set but `props.encryptionKey` is not specified, then it attempts to create a new KMS `Key` without `enableKeyRotation` set to `true`. Agreed `enableKeyRotation` should be enabled.
