### ISSUE TITLE
aws-cdk-lib/aws-ecs: Removing cluster-wide storage encryption key from code does not remove it from cluster

### ISSUE THREAD

**Issue by thetillhoff** [aws/aws-cdk#32036]
### Describe the bug

I recently learned about the relatively new possibility to encrypt ephemeral storage of ECS tasks on Fargate; https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ecs.ManagedStorageConfiguration.html

Trying it out with Typescript CDK (https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ecs.ManagedStorageConfiguration.html), it worked perfectly.

However, when removing it from the code to reach the previous state, the kms key stayed listed in the ECS Cluster, so the encryption was still on, even though I disabled it in the code.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

The key and all encryption related settings should've been removed again after removing it from CDK code.

### Current Behavior

The key and the encryption settings stay even after removing them from CDK code.

### Reproduction Steps

Create an ECS cluster with a KMS key for encryption with CDK.
Remove the reference in the code.
After applying the change, the encryption is still enabled, and needs to be manually removed.

### CDK CLI Version

2.163.0

### Node.js Version

20.18.0

### OS

Windows Server 2022

### Language

TypeScript

**Comment by pahud** [comment]
Off the top off my head, this might be intentional by design but we need further check.

1. Can you share minimal reproducible so I can paste to my IDE and reproduce that?

2. Can you share what did you see when you run `cdk diff` before the 2nd deployment? This should display which resources will be removed.
