### ISSUE TITLE
(aws-cdk): centralize all cli logging into a single logging function

### ISSUE THREAD

**Issue by HBobertz** [aws/aws-cdk#32039]
### Describe the feature

[This file](https://github.com/aws/aws-cdk/blob/4af1564cc3c67f1f58464f2db9c81c2e505d0c34/packages/aws-cdk/lib/logging.ts) defines our logging tools for the CDK CLI. Refactor the logging implementation into a single logging function which takes both a message and the logging type (info, debug, trace, error, etc...), and then additionally ensure any logging in the package uses this logging function.

### Use Case

needed to support future CDK Programmatic Access, but also Centralizes and consolidates logging for the CLI.

### Proposed Solution

Probably something like

```
export type LogLevel = 'error' | 'warn' | 'info' | 'debug' | 'trace';

export interface LogEntry = {
  level: LogLevel
  message: string
}

export function log(...args: LogEntry[]) {
  // do the stuff
}
```

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.165

### Environment details (OS name and version, etc.)

macOS 15 Sequoia

**Comment by ashishdhingra** [comment]
Worked upon by CDK team.
