### ISSUE TITLE
consider renaming the "id" parameter for constructs (reserved word in Python)

### ISSUE THREAD

**Issue by bverhoeve** [aws/aws-cdk#3203]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [ ] :beetle: bug report
  - [X] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/awslabs/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
To create a new `Construct` (or any other `Resource`) using CDK, the constructor in Python has the following syntax:
```
 class aws_cdk.core.Construct(scope, id)
```
The `id` parameter serves as a unique id for CloudFormation. Naming a parameter `id` in Python is not really good practice, since `id()` is a built-in function in the Python standard library, which represents the address of the object in memory in CPython. (see https://docs.python.org/3/library/functions.html#id)

I think this could lead to potentials errors down the line for users that use the Python variant of CDK, since the `id` parameter could clash with the `id()` function. 

* **What is the expected behavior (or behavior of feature suggested)?**
If possible, renaming the `id` parameter to something like `identifier` or `cdk_id` would avoid having this parameter clash with the built-in `id()` function.

* **What is the motivation / use case for changing the behavior or adding this feature?**
Clashes with Python standard library built-in functions.

* **Please tell us about your environment:**
  
  - CDK CLI Version: 0.36.2
  - Module Version: 0.36.2.0
  - OS: [all]
  - Language: [Python ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

**Comment by SomayaB** [comment]
Hi @bverhoeve, thanks for submitting this request! We will look into this and someone will update this issue when there is movement.

**Comment by SamStephens** [comment]
@eladb Look through the linked issues, I cannot see any discussion of this request, it appears to have been closed with no discussion. It'd be great to understand the motivations behind not doing this.

**Comment by bazd** [comment]
> @eladb Look through the linked issues, I cannot see any discussion of this request, it appears to have been closed with no discussion. It'd be great to understand the motivations behind not doing this.

I just tested this with CDK 2.0.0 and the sample-app, and looks like they have renamed it to 'construct_id'.

`class HelloCdkStack(Stack):

    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)`

**Comment by SamStephens** [comment]
@bazd that may be the case in the sample application, but the actual CDK constructs themselves still use the keyword `id`. See for example the constructor of [Stack](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk/Stack.html) that's being called above via `super.init`. If you rewrote that code sample to use named parameters, it'd be:

```
class HelloCdkStack(Stack):
    def init(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().init(
            scope=scope,
            id=construct_id,
            **kwargs,
        )
```

**Comment by bazd** [comment]
> @bazd that may be the case in the sample application, but the actual CDK constructs themselves still use the keyword `id`. See for example the constructor of [Stack](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk/Stack.html) that's being called above via `super.init`. If you rewrote that code sample to use named parameters, it'd be:
> 
> ```
> class HelloCdkStack(Stack):
>     def init(self, scope: Construct, construct_id: str, **kwargs) -> None:
>         super().init(
>             scope=scope,
>             id=construct_id,
>             **kwargs,
>         )
> ```

Yes, cheers for clarifying.  They haven't addressed it at all which is disappointing considering v2 has just been released.
