### ISSUE TITLE
aws-cdk-lib: v2.166.0 jar missing from maven central

### ISSUE THREAD

**Issue by scarytom** [aws/aws-cdk#32048]
### Describe the bug

Version 2.166.0 was [released at 2024-11-07T01:44:58Z](https://github.com/aws/aws-cdk/releases/tag/v2.166.0) but the Jar artifact has yet to show up in [Maven Central](https://central.sonatype.com/artifact/software.amazon.awscdk/aws-cdk-lib/versions).

I'm essentially re-opening issue #31552

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Last Known Working CDK Version

2.165.0

### Expected Behavior

Jar should be in maven central

### Current Behavior

Jar is missing from maven central

### Reproduction Steps

N/A

### Possible Solution

publish the missing jar

### Additional Information/Context

@pahud said he would raise this with the team.

https://github.com/aws/aws-cdk/issues/31552#issuecomment-2414589289

### CDK CLI Version

N/A

### Framework Version

N/A

### Node.js Version

N/A

### OS

ubuntu

### Language

Java

### Language Version

openjdk 21.0.4

### Other information

```
Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.7.0:get (default-cli) on project standalone-pom: Couldn't download artifact: org.eclipse.aether.resolution.DependencyResolutionException: The following artifacts could not be resolved: software.amazon.awscdk:aws-cdk-lib:jar:2.166.0 (absent): Could not find artifact software.amazon.awscdk:aws-cdk-lib:jar:2.166.0 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
```

**Comment by ashishdhingra** [comment]
@scarytom Good morning. Thanks for reporting the issue. I do see that .NET [Amazon.CDK.Lib 2.166.0](https://www.nuget.org/packages/Amazon.CDK.Lib/2.166.0) already published. I have notified the team to advise on the delay.

**Comment by kaizencc** [comment]
Maven release was delayed but is now out. Thanks for your patience. When this sort of thing happens, we are aware and already on it :)
