### ISSUE TITLE
CDKTF : Unable to get output for this data_aws_ssm_parameters_by_path

### ISSUE THREAD

**Issue by PreranaAmirapu** [aws/aws-cdk#32044]
### Describe the bug

    def get_latest_stable_release(self):
        """
        Fetches the latest release version from the specified GitHub repository.
        Returns:
            str: The latest release version.
        """
        test = data_aws_ssm_parameters_by_path.DataAwsSsmParametersByPath(
            self.terraform_stack,
            "get_ami_version",
            path="/aws/service/bottlerocket/aws-k8s-1.30/x86_64/latest/image_version",
            with_decryption=True
        )
        latest_ami_version = Fn.element(test.values, 0)

        test = TerraformOutput(self.terraform_stack, "latest_ami_version", value=Fn.element(test.values, 0))
        print("----------------------")
        latest_ami_version = test.value
        return latest_ami_version

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

for the above code I need the latest version which comes in the output, tried various ways to extract the output but failed, is this the correct way to write the code in cdktf

### Current Behavior

error for the above code says list is empty

### Reproduction Steps

from cdktf_cdktf_provider_aws import data_aws_ssm_parameters_by_path

    def get_latest_stable_release(self):
        """
        Fetches the latest release version from the specified GitHub repository.
        Returns:
            str: The latest release version.
        """
        test = data_aws_ssm_parameters_by_path.DataAwsSsmParametersByPath(
            self.terraform_stack,
            "get_ami_version",
            path="/aws/service/bottlerocket/aws-k8s-1.30/x86_64/latest/image_version",
            with_decryption=True
        )
        latest_ami_version = Fn.element(test.values, 0)

        test = TerraformOutput(self.terraform_stack, "latest_ami_version", value=Fn.element(test.values, 0))
        print("----------------------")
        latest_ami_version = test.value
        return latest_ami_version

### CDK CLI Version

2.147.0

### Node.js Version

v22.4.1

### OS

mac

### Language

Python

**Comment by khushail** [comment]
Hi @PreranaAmirapu , thanks for reaching out. Looks like this belongs to CDK for terraform(https://github.com/hashicorp/terraform-cdk) and this `aws-cdk` repo handled only issus related specific to 'aws-cdk`. 

Please open issue with Terraform-cdk. I am closing this one now
