### ISSUE TITLE
(aws-ecs-patterns): desiredTaskCount not a property of aws-ecs-patterns

### ISSUE THREAD

**Issue by spensireli** [aws/aws-cdk#32056]
### Describe the issue

If I'm reading this correctly the desiredTaskCount isn't actually a property of queueProcessingEc2Service, so it cannot be specified as it is in the example. 

### Links

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ecs_patterns.QueueProcessingEc2Service.html

https://github.com/aws/aws-cdk/blame/7bb9203eb95fe894c0d40942ff49c782a9fec251/packages/aws-cdk-lib/aws-ecs-patterns/lib/ecs/queue-processing-ecs-service.ts#L132

**Comment by khushail** [comment]
Hi @spensireli , thanks for reporting this. I can confirm that its non existent in [QueueProcessingEc2Service](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ecs_patterns.QueueProcessingEc2Service.html) construct([QueueProcessingServiceBase](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ecs_patterns.QueueProcessingServiceBase.html)). I found this mention in the doc where this parameter is read from FLAG value to be passed to EC2 Service props. 

https://github.com/aws/aws-cdk/blob/7bb9203eb95fe894c0d40942ff49c782a9fec251/packages/aws-cdk-lib/aws-ecs-patterns/lib/ecs/queue-processing-ecs-service.ts#L132

If i try to access it, the synth process would give error as its not in the props-

<img width="1027" alt="Screenshot 2024-11-08 at 11 00 04 AM" src="https://github.com/user-attachments/assets/de02d373-7cbc-47d9-870e-b06f2cb088d5">

So this seems legit, Marking it as P3 as its a documentation bug, contributions from the community are welcome

**Comment by spensireli** [comment]
Okay thought so, I'll try and find time to craft a PR.
