### ISSUE TITLE
Wrong explanation/identifier

### ISSUE THREAD

**Issue by mmescherin** [aws/aws-cdk#32067]
### Describe the issue

Wrong text/identifier/field. At the end of the page:

_If you received a 5xx error from API Gateway, it is likely one of two issues:_

_The response your function returned is not what API Gateway expects. Go back and make sure your handler returns a response that includes a statusCode, body and **header** fields_ 

it has to be **headers**, not **header**. The name of the response object field is **headers**. I had 502 and error spent some time for  that issue :)

### Links

https://catalog.us-east-1.prod.workshops.aws/event/dashboard/en-US/workshop/2000-typescript-workshop/300-create-hello-cdk-app/340-apigw

**Comment by ashishdhingra** [comment]
Per example at https://catalog.us-east-1.prod.workshops.aws/workshops/10141411-0192-4021-afa8-2436f3c66bd8/en-US/2000-typescript-workshop/300-create-hello-cdk-app/320-lambda, the fields are `statusCode`, `headers` and `body`.

**Comment by ashishdhingra** [comment]
@mmescherin I have communicated the issue to the right team. They should take a look and fix the typo. Closing this issue here.
