### ISSUE TITLE
AWS Amplify Console - Add L2 Construct

### ISSUE THREAD

**Issue by simalexan** [aws/aws-cdk#3207]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [ ] :beetle: bug report
  - [x] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/awslabs/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*

* **What is the expected behavior (or behavior of feature suggested)?**
Since AWS Amplify Console is now within CDK as an L1 Construct it would be great if this can also be made available within CDK as an L2 Construct and I'd like to contribute to it, as its a relatively small case. 

* **What is the motivation / use case for changing the behavior or adding this feature?**
Enable AWS customers to use a nicer and more convenient AWS CDK L2 Construct API

* **Please tell us about your environment:**
  
  - CDK CLI Version: 0.37.0
  - Module Version: 0.37.0
  - OS: all
  - Language: all

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

I've started today, please let me know if someone would like to add their contribution as well. I shall ping also @sthulb for assistance in this.

**Comment by sthulb** [comment]
@simalexan I’ve already started this. I’ve got the app resource mostly done. :)

**Comment by sthulb** [comment]
Hey @swaminator we’re tracking the work here.

**Comment by simalexan** [comment]
@sthulb great can you share the repo pls? :) I've got the starting points of all three, and willing to add.

Sorry, I didn't see the AWS CDK issue for this per the Contribution guideline, so unfortunate :/

**Comment by sthulb** [comment]
I’ll push it tomorrow. I’ll ping you on slack tomorrow to run through it

**Comment by simalexan** [comment]
Alrighty then! Glad I pinged you here!

**Comment by MrArnoldPalmer** [comment]
Closed via https://github.com/aws/aws-cdk/pull/5177
