### ISSUE TITLE
cli: shrinkwrap dependencies

### ISSUE THREAD

**Issue by rix0rrr** [aws/aws-cdk#3210]
* **I'm submitting a ...**
  - [ ] :beetle: bug report
  - [x] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/awslabs/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**

CLI dependencies are not locked, which makes them vulnerable to patch-version malware injection of dependencies.

We should [npm-shrinkwrap](https://docs.npmjs.com/files/shrinkwrap.json) our dependencies to mitigate some of that risk, and then do controlled upgrades of deps.

**Comment by rix0rrr** [comment]
This is also necessary to patch transitive dependencies, as with the `https-proxy-agent` problem.

**Comment by rix0rrr** [comment]
After switching to yarn, we need to be able to generate `npm-shrinkwrap` from the yarn packages.

**Comment by rix0rrr** [comment]
I believe this has long been added

**Comment by TomLingham** [comment]
Is there a suggested solution for those behind proxies and having to stick with corporate proxies and registry mirrors (Verdaccio, Artifactory, Sonartype, etc.) when resolving packages listed in the `npm-shrinkwrap.json` file? These dependencies are [hard coded](https://unpkg.com/aws-cdk@1.95.1/npm-shrinkwrap.json) to be fetched from `https://registry.yarnpkg.com/` which causes problems when this is blocked by corporate proxies. There is no way to rewrite these URLs nicely without potentially forking or downloading the dependency and installing from the filesystem.

**Comment by cqcmdwym** [comment]
@TomLingham tricky solution:
1. delete lock file.
2. set package-lock=false
3. npm install
4. set package-lock=true
5. npm install
