### ISSUE TITLE
CodeBuild: Missing EncyptionDisabled Artifact property

### ISSUE THREAD

**Issue by nmussy** [aws/aws-cdk#3211]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [ ] :beetle: bug report
  - [ ] :rocket: feature request
  - [x] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/awslabs/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*
There is currently no way to disable artifact encryption.

* **What is the expected behavior (or behavior of feature suggested)?**
Include a boolean `encryptionDisabled` parameter to `ArtifactsProps`, matching [CloudFormation's `EncryptionDisabled`](https://docs.amazonaws.cn/en_us/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-artifacts.html#cfn-codebuild-project-artifacts-encryptiondisabled)

* **What is the motivation / use case for changing the behavior or adding this feature?**
The motivation for this property is best explained in the CodeBuild Console:
> Disable encryption if using the artifact to publish a static website or sharing content with others

* **Please tell us about your environment:**
  
  - CDK CLI Version: 0.37.0
  - Module Version: 0.37.0
  - OS: all
  - Language: all

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

**Comment by skinny85** [comment]
Hey @nmussy ,

thanks for opening the issue! Adding this should be fairly straightforward -- it's adding an `encryptionDisabled` property in the [`S3ArtifactProps`](https://github.com/awslabs/aws-cdk/blob/master/packages/%40aws-cdk/aws-codebuild/lib/artifacts.ts#L80) interface, and a corresponding small change in the [`S3Artifacts`](https://github.com/awslabs/aws-cdk/blob/master/packages/%40aws-cdk/aws-codebuild/lib/artifacts.ts#L71) class -- plus a unit test, of course!.

Would you be interested in opening us a Pull Request with this change?

Thanks,
Adam

**Comment by nmussy** [comment]
Hey @skinny85,

Sure, I'll look into it. I should have a PR ready by the end of the day.
