### ISSUE TITLE
(dynamodb): l2 construct for warm-throughput feature

### ISSUE THREAD

**Issue by LeeroyHannigan** [aws/aws-cdk#32127]
### Describe the feature

https://aws.amazon.com/blogs/database/pre-warming-amazon-dynamodb-tables-with-warm-throughput/

### Use Case

Allow users pre-warm their DynamoDB tables using CDK

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

LATEST

### Environment details (OS name and version, etc.)

MacOS

**Comment by khushail** [comment]
@LeeroyHannigan , thanks for submitting this request. 
As mentioned in [this article](https://aws.amazon.com/blogs/database/pre-warming-amazon-dynamodb-tables-with-warm-throughput/), Cloudformation supports the pre-warming to DynamoDB Table, you can pre-warm your table by passing in values for warm throughput during the table creation process. This is what I see in your [PR](https://github.com/aws/aws-cdk/pull/32128).
Thanks for PR submission. Appreciate your efforts!
