### ISSUE TITLE
CDK CLI: region must be in `config` file (ignored in `credentials` file) since 2.167.0

### ISSUE THREAD

**Issue by rix0rrr** [aws/aws-cdk#32130]
### Describe the bug

From this thread: https://github.com/aws/aws-cdk/issues/32120

By @otbe:

----------

For us the issue is in the region, e.g.

deploy -vvv
```
10:38:42] Looking up AWS region in the EC2 Instance Metadata Service (IMDS).
[10:38:43] Unable to retrieve AWS region from IMDS: Error: Error fetching metadata token: TimeoutError: Connection timed out after 1000 ms
[10:38:43] Unable to determine AWS region from environment or AWS configuration (profile: "default"), defaulting to 'us-east-1'
```

Not quite sure how it worked in older aws-cdk versions but the region is specified in `.aws/credentials` similar to this

```
[default]
aws_access_key_id=
aws_secret_access_key=
aws_session_token=
aws_security_token=
region=eu-central-1
```

That means our stacks are deployed in the wrong region with 2.167.0 🫠
Reverting back to 2.166.0 solves the issue.

### Regression Issue

- [X] Select this option if this issue appears to be a regression.

### Expected Behavior

Uses my configured region in the INI file

### Current Behavior

Uses `us-east-1`

### Reproduction Steps

See description

### CDK CLI Version

2.167.0

### Node.js Version

-

### OS

-

### Language

TypeScript

**Comment by rix0rrr** [comment]
| Location of `[default] region=` statement | Works in 2.167.0 | Works in AWS CLI |
|-------------------------------|-----------|--------------|
| `~/.aws/credentials` | ❌ | ✅ |
| `~/.aws/config` | ✅ | ✅ |

**Comment by otbe** [comment]
Interesting findings. What is also somehow strange we have a lot of node scripts with aws sdkv3 running in the same setup (region in /credentials) and they still work fine.

**Comment by rix0rrr** [comment]
> What is also somehow strange we have a lot of node scripts with aws sdkv3 running in the same setup (region in /credentials) and they still work fine.

That is quite weird indeed

**Comment by rix0rrr** [comment]
Ah yeah, it's us:

https://github.com/aws/aws-cdk/blob/fb97684de54da5e2815851edda50bebe980f8eb5/packages/aws-cdk/lib/api/aws-auth/awscli-compatible.ts#L152

**Comment by otbe** [comment]
Just for confirmation: after putting the region into `.aws/config` everything works again :)

**Comment by ashishdhingra** [comment]
Labeling the issue as `p1` for now since it is being actively worked upon.
