### ISSUE TITLE
@aws-cdk/aws-glue-alpha: pythonShell should not require glueVersion

### ISSUE THREAD

**Issue by urkle** [aws/aws-cdk#32148]
### Describe the bug

When creating a pythongshell job type the GlueVersion should not be required (as it is not used for this mode).

All examples of creating python shell jobs do not specify the GlueVersion at all, just the python version

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

I should be able to omit the glueVersion parameter to JobExecution.pythonShell.

### Current Behavior

It throws an error stating that the glue_version parameter is required. 

### Reproduction Steps

 glue.Job(
            self, 'ShellJob',
            job_name='myShellJob',
            role=glue_role,
            default_arguments={
                "--additional-python-modules": "awswrangler,fastparquet,google-api-python-client,google-auth-oauthlib,google-auth-httplib2",
            },
            timeout=Duration.minutes(30),
            max_concurrent_runs=1,
            executable=glue.JobExecutable.python_shell(
                python_version=glue.PythonVersion.THREE_NINE,
                script=glue.Code.from_asset(glue_script_path('my-shell-job.py')),
            )
        )

### Possible Solution

make it optional for PythonShellExecutableProps

### CDK CLI Version

2.166.0

### Node.js Version

18.16.1

### OS

macOS 12.7.6

### Language

Python

### Language Version

3.9

### Other information

@aws-cdk/aws-glue-alpha = 2.166.0a0

**Comment by khushail** [comment]
Hi @urkle , thanks for reaching out. I see that in CDK documentation for [Python shell jobs](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-glue-alpha-readme.html#python-shell-jobs), it clearly mentions that Glue version is required.

<img width="721" alt="Screenshot 2024-11-18 at 4 07 56 PM" src="https://github.com/user-attachments/assets/2676bc1d-2949-4fdb-8165-c55407ce2508">

Could you please share your insights on why this is not required and if this shared context of CDK Docs makes any sense.

Thanks

**Comment by urkle** [comment]
@khushail whenever I create pyhon shell jobs via CF I have to NOT set the glue_version to create the resource, otherwise it refuses to create saying that isn't supported.

And when I look at my jobs in the glue job list, the shell jobs have NO glue version specified at all.

![image](https://github.com/user-attachments/assets/af9c449c-8bfd-4d1b-b7d3-2e50562f53ee)

The only value I was able to get to behave when using CDK was to set the glue version to 3.0 (some default somewhere I assume). But as you can see in the screenshot there is no glue version associated with my python shell job.
