### ISSUE TITLE
DynamoDB: Allow accessing the table's key schema

### ISSUE THREAD

**Issue by RomainMuller** [aws/aws-cdk#3215]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] :rocket: feature request

* **What is the expected behavior (or behavior of feature suggested)?**

It would be nice if it was possible to read a DynamoDB table's key schema (hash attribute name and type, as well as range attribute name and type if there is one).

* **What is the motivation / use case for changing the behavior or adding this feature?**

When building abstractions on top of DynamoDB (think: API Gateway proxies, Lambda functions that perform scheduled maintenance, ...), it can be useful to know the key schema in order to be able to generate correct integration requests.

**Comment by eladb** [comment]
I agree, and more! Lately I realized we need to expose all (resolved) configuration props as read only properties of the concrete construct, to support reflection use cases and aspects. Wanna pick this up?

**Comment by RomainMuller** [comment]
I agree with the general ideal, however the current DynamoDB Table construct does not lend itself very well to this... because it is a somewhat mutable construct (you can add local & global indices after the construct is initialized, and those are effectively configuration props).

**Comment by eladb** [comment]
It’s a good point but still for the use case of aspects and validation this is still useful because at that point I expect all configuration to be final. Having said that, we should call that out in the docs of relevant properties that those can change
