### ISSUE TITLE
A version for this Lambda function exists ( 2 ). Modify the function to create a new version.

### ISSUE THREAD

**Issue by iammulani** [aws/aws-cdk#32169]
### Describe the bug

After adding Lambda auto-scaling configuration to one of the functions in our stack, CDK is showing unexpected version changes for all Lambda functions during deployment:

Stack Context:
- Multiple Lambda functions in the same stack
- Each Lambda has an 'active' alias
- Recently added auto-scaling to some Lambda functions
- Issue affects ALL Lambdas in the stack, not just the ones with auto-scaling
- Stack was deploying successfully until auto-scaling was added
- No code changes were made to any Lambda functions

- Stack was working correctly until yesterday
- Issues started occurring after adding auto-scaling configuration
- No other changes were made to the stack or Lambda configurations

- Unable to deploy stack updates
- False positive changes appearing in CDK diff
- Affects CI/CD pipeline as it detects changes when there are none

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Last Known Working CDK Version

2.166.0

### Expected Behavior

Expected Behaviour:
- CDK should only create new versions when there are actual changes to Lambda code or configuration
- Non-modified Lambdas should not show version changes in cdk diff
- Stack should deploy successfully when no actual changes are made

### Current Behavior

Symptoms:
- Every `cdk diff` shows Lambda version changes for all functions in the stack even when no code has changed
- Sample diff for each Lambda in the stack:
  [-] AWS::Lambda::Version nf-desktop-0cd96323a84b-check-hoop/CurrentVersion nfdesktop0cd96323a84bcheckhoopCurrentVersionF5770E83cf059a8134aeb229930e72a918d8d4ac destroy
  [+] AWS::Lambda::Version nf-desktop-0cd96323a84b-check-hoop/CurrentVersion nfdesktop0cd96323a84bcheckhoopCurrentVersionF5770E83216aa1efab3dd8ff9f82a9837663744a
  [~] AWS::Lambda::Alias nf-desktop-0cd96323a84b-check-hoop/Aliasactive nfdesktop0cd96323a84bcheckhoopAliasactive9BEE7D94

Deployment Error:
- When trying to deploy, receiving error: "A version for this Lambda function exists"
- This error occurs despite no actual changes to any Lambda function code

### Reproduction Steps

I added one of the sample Lambda functions inside the stack’s Additional Information/Context. I have other Lambda functions as well, and if there are changes to any of them, but not to this specific Lambda, it throws an error. so it expects every lambda to be changed every time to deploy stack successfully. 

### Additional Information/Context

const checkHoliday = new Function(this, `${branding}-check-holiday`, {
            functionName: `${branding}-checkHoliday`,
            runtime: Runtime.NODEJS_20_X,
            handler: 'index.handler',
            code: Code.fromAsset('./src/lambdas/checkHoliday'),
            layers: [
                cdk.aws_lambda.LayerVersion.fromLayerVersionArn(
                    this,
                    `${branding}-check-holiday-common-layer`,
                    commonLayer,
                ),
            ],
            environment: {
                TABLE_NAME: tableName,
                PARTITION_KEY: partitionKey,
                SORT_KEY: sortKey,
                PHONE_PK_VALUE: phoneNumberPkValue,
                QUEUE_PK_VALUE: queuePkValue,
                CALENDAR_EVENT_PK_VALUE: calendarEventPkValue,
                CALENDAR_PK_VALUE: calendarPkValue,
                DATE_FORMAT_PATTERN: dateFormatPattern,
                LOG_LEVEL: logLevel,
            },
            timeout: Duration.seconds(8),
            memorySize: 512,
            environmentEncryption: lambdaEnvironmentEncryptionKey,
        });

        // alias to lambda checkCalendar
        const checkHolidayAlias = checkHoliday.addAlias('active', {});

        // Create AutoScaling target
        const checkHolidayAliasScaling = checkHolidayAlias.addAutoScaling({
            minCapacity: minLambdaConcurrentCapacity,
            maxCapacity: maxLambdaConcurrentCapacity,
        });

        // Configure Target Tracking
        checkHolidayAliasScaling.scaleOnUtilization({
            utilizationTarget: concurrentLambdaUtilizationTarget,
        });

### CDK CLI Version

2.166.0 (build 7bb9203)

### Node.js Version

20

### OS

macOS Sonoma 14.5

### Language

TypeScript

### Language Version

5.6.2

**Comment by greg5123334** [comment]
There is a bug that was introduced previously affecting how CDK generates logicalIds for Lambda functions. This has been fixed since version 2.27 and all new projects created via ```cdk init``` will not be affected. For existing projects, a workarond exists by means of feature flags.

# Workaround
  1) Add feature flags to the context of cdk.json:

``` json
    "@aws-cdk/aws-lambda:recognizeVersionProps": false,
    "@aws-cdk/aws-lambda:recognizeLayerVersion": false,
```

  2) Make trivial change to affected Lambda functions. i.e Description, Tags...
  3) Deploy

This should correct the Lambda functions. To test, deploy again leaving the feature flags in-place, without any changes to the Lambda function(s).

References:
[currentVersion: Updated hashing logic](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda-readme.html#currentversion-updated-hashing-logic)
[currentVersion: Updated hashing logic for layer versions](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda-readme.html#currentversion-updated-hashing-logic-for-layer-versions)

**Comment by iammulani** [comment]
@greg5123334 thank you. it worked.

**Comment by khushail** [comment]
@greg5123334 , thanks for sharing the detailed information and solution.

@iammulani , since this is resolved from your side, should I close this issue?
