### ISSUE TITLE
(awselasticloadbalancingv2): No load balancers found with NetworkLoadBalancer lookup method after 2.167.0

### ISSUE THREAD

**Issue by rishi-kulkarni** [aws/aws-cdk#32161]
### Describe the bug

I had three CI pipelines fail with the following error starting today using both Go and Python cdk:

```go
Runtime process exited abnormally: waitid: no child processes[Error at /***-***-scorer-ecs-stack] 
No load balancers found matching {"dummyValue":{"ipAddressType":"dualstack","loadBalancerArn":"arn:aws:elasticloadbalancing:us-west-2:123456789012:loadbalancer/network/my-load-balancer/50dc6c495c0c9188","loadBalancerCanonicalHostedZoneId":"Z3DZXE0EXAMPLE","loadBalancerDnsName":"my-load-balancer-1234567890.us-west-2.elb.amazonaws.com","securityGroupIds":["sg-1234"],"vpcId":"vpc-12345"},"account":"***","region":"us-east-1","loadBalancerTags":[{"key":"Name","value":"***-ds-apigtwy"}],"loadBalancerType":"network","lookupRoleArn":"arn:aws:iam::***:role/cdk-hnb659fds-lookup-role-***-us-east-1"}
```

```python
[Error at /***-REX/***-REX-API-Gateway-V2] No load balancers found matching 
{"account":"***","region":"us-east-1","loadBalancerTags":[{"key":"Name","value":"***-ds-apigtwy"}],"loadBalancerType":"network","lookupRoleArn":"arn:aws:iam::***:role/cdk-hnb659fds-lookup-role-***-us-east-1"}
```

Pinning the `aws-cdk` CLI to `npm install -g aws-cdk@2.166.0` resolved the issue in all pipelines. Perhaps could be related to the new Zonal Shift feature? 

### Regression Issue

Confirmed Regression 

### Last Known Working CDK Version

2.166.0

### Expected Behavior

Looking up a still-existing Network Load Balancer by tag should work. 

### Current Behavior

The Network Load Balancer lookup fails to resolve. 

### Reproduction Steps

* Create a network load balancer in an account with a tag
* Attempt to look it up by tag

### CDK CLI Version

2.167.1

### Node.js Version

22

### OS

Linux

### Language

Python, Go

### Language Version

Python 3.11 | Go 1.23.2

**Comment by otaviomacedo** [comment]
Working hypothesis: the load balancer context provider is now requiring that the load balancer have the same set of tags as the query:

https://github.com/aws/aws-cdk/blob/5bc0662bacf7eca814f09b7560d77a68e3f5ddea/packages/aws-cdk/lib/context-providers/load-balancers.ts#L164

whereas before it only required that the query was a subset of the load balancer's tags.

@rishi-kulkarni can you please confirm that this is your case?

**Comment by rishi-kulkarni** [comment]
Aha, very interesting. Yes, I can confirm that looking up _all_ tags resolves the NLB, but looking up any subset does not. Thanks for the quick investigation and PR!
