### ISSUE TITLE
aws-cdk-lib(step_functions): Creating an S3ObjectsItemReader with a dynamic path but fixed bucket name does not show up correctly in the StepFunction console.

### ISSUE THREAD

**Issue by urkle** [aws/aws-cdk#32167]
### Describe the bug

I am creating a DistributedMap step like so

```python
map_for_s3 = sfn.DistributedMap(
    self, 'List Files',
    max_concurrency=1,
    item_reader=sfn.S3ObjectsItemReader(
        bucket=self.incoming_mail_bucket,
        prefix=sfn.JsonPath.string_at('$.pending_path'),
    ),
    item_batcher=sfn.ItemBatcher(
        max_items_per_batch=500,
    )
)
```

This generates a working step where the item payload looks like this.
```json
{
    "ItemReader": {
        "Resource": "arn:aws:states:::s3:listObjectsV2",
        "Parameters": {
            "Bucket": "my-bucket-name",
            "Prefix.$": "$.pending_path"
        }
   },
}
```

However, the Step Function console page shows the step as incomplete, as the Step function console only recognizes either both json path values or fixed values

![image](https://github.com/user-attachments/assets/5c2953ae-d224-48a1-b555-65c59dae4056)

I tried to change it to use bucket_name_path instead, however that failed to add the required permissions into the Step function role for the S3 Bucket.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

The step function console UI to allow a mixed of fixed & dynamic definition

### Current Behavior

the UI does not show the configuration correctly, and doing any reworking to allow it to show correctly (e.g. adding a Pass above the DistributedMap that sets a bucket var to the fixed value and the path to the input param) does not auto-add the needed permissions to the generated step function execution role

### Reproduction Steps

Documented above.

### CDK CLI Version

2.166.0

### Node.js Version

18.16.1

### OS

macOS 12.7.6

### Language

Python

### Language Version

Python 3.11

**Comment by markmansur** [comment]
If you open the `S3 item source` drop down you'll notice two options
1. `Get bucket and prefix at runtime from state input`
2. `Enter bucket and prefix`

It's not possible to mix the two. Either both come from the state input or both are static values.

Regarding the permissions not being added. I believe this is because CDK does not know the bucket/prefix to which it should add permissions at synth time, since you're getting these values at runtime from the state input. In this case you'll need to explicitly add the S3 read permissions to the state machine execution role yourself.

Hope this helps!

**Comment by urkle** [comment]
@markmansur that is what I noticed as well.  IMHO Kind of limiting. And would require an extra step just to assign state input to the fixed bucket value just to have it show on the UI correctly.   Right now it "works" with the mixed configuration.  It is just limiting on the UI to restrict things that way when the backend will work correctly regardless.

**Comment by markmansur** [comment]
@urkle Yes, it is a bit annoying to have to add a pass state when you want a static bucket name and a dynamic prefix (or vica-versa).

**Comment by khushail** [comment]
@urkle , thanks for reaching out.

@markmansur , thanks for sharing your insights on this issue. I agree with you on stating the facts about `S3 ItemSource`. In the CDK code, it either accepts the S3 Bucket name or the json path. Combining both does not seem to be an option. Please see this -

https://github.com/aws/aws-cdk/blob/060af6c4383e599e41511ca8e2f63f0f71c68bba/packages/aws-cdk-lib/aws-stepfunctions/lib/states/distributed-map/item-reader.ts#L181

Also mentioned in CDK [Readme](https://github.com/aws/aws-cdk/tree/v2.170.0/packages/aws-cdk-lib/aws-stepfunctions) -

```
Both bucket and bucketNamePath are mutually exclusive.
```

I noticed that [this PR](https://github.com/aws/aws-cdk/pull/31619) introduced the change for adding this dynamic path which might be helpful in udnerstanding the context behind current implementation.

So from CDK point, this seems the way it is as provided by the StepFunctions service.
