### ISSUE TITLE
aws_cdk.aws_batch/JobDefinitionProps: Links pointing to another page

### ISSUE THREAD

**Issue by jpio97** [aws/aws-cdk#32193]
### Describe the issue

In the documentation, under the parameters attribute, there is a link that points to a reference about defining job parameters, however, when clicking the link it sends you to the main AWS Batch page.

Link points to
https://docs.aws.amazon.com/batch/latest/userguide/job_definition_parameters.html#parameters

But redirects to
https://docs.aws.amazon.com/batch/latest/userguide/what-is-batch.html›

Should point to this page
https://docs.aws.amazon.com/batch/latest/userguide/job_definition_parameters-copy.html#parameters

### Links

https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_batch/JobDefinitionProps.html

**Comment by mrgum** [comment]
Hello
why was
https://docs.aws.amazon.com/batch/latest/userguide/job_definition_parameters.html
renamed to
https://docs.aws.amazon.com/batch/latest/userguide/job_definition_parameters-copy.html
 ?

**Comment by ashishdhingra** [comment]
@mrgum Good morning. Please use feedback link at the top of the page to report the issue. The documentation links you provided are for AWS Batch service as a general. This repository is for reporting issues related to CDK.

Thanks,
Ashish
