### ISSUE TITLE
feature: cdk deploy --all

### ISSUE THREAD

**Issue by fulghum** [aws/aws-cdk#3222]
* **I'm submitting a ...**
  - [ ] :beetle: bug report
  - [X] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/awslabs/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
The "cdk deploy" command recently stopped deploying all stacks by default, which was often a handy behavior.  You can still pass glob patterns, like '*', to deploy all stacks, but it might be nice to also have an explicit "--all" flag you could pass.  Low priority, since the glob behavior works for this use case, but I suspect many users would expect an explicit "--all" option to be supported in addition to the glob support.

**Comment by stephendwu** [comment]
I'd like to take a stab at this. In the event that a user uses the `--all` flag, but they also provide stacks, should the CLI default to deploying all stacks or only deploy the provided stacks?

**Comment by shivlaks** [comment]
@stephendwu - I think it's also reasonable to just error and provide guidance to the user to provide one or the other (rather than guess the user's intent)

**Comment by IsmaelMartinez** [comment]
PR ready for review in #10745
