### ISSUE TITLE
aws-lambda-event-sources: KafkaEventSourceProps does not support startingPosition AT_TIMESTAMP correctly?

### ISSUE THREAD

**Issue by justin-masse** [aws/aws-cdk#32235]
### Describe the bug

Getting a synth error: `Error: startingPositionTimestamp must be provided when startingPosition is AT_TIMESTAMP` when instantiating `SelfManagedKafkaEventSource()` with `startingPosition: StartingPosition.AT_TIMESTAMP`

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

KafkaEventSourceProps chain of inheritance should allow for passing in `startingPositionTimestamp`  

### Current Behavior

You cannot provide startingPositionTimestamp anywhere on that constructor prop... if you do it will error and even if you do something like ts-ignore-error it will give you an error when running synth:

Error: startingPositionTimestamp must be provided when startingPosition is AT_TIMESTAMP

### Reproduction Steps

Instantiate `SelfManagedKafkaEventSource()` and in the props provide `startingPosition: StartingPosition.AT_TIMESTAMP,` which appears to be a valid option based on the types. This will cause an error when running synth... and you cannot provide required `startingPositionTimestamp` as it is not on the interfaces.

### CDK CLI Version

2.142.1

### Node.js Version

20

### OS

macos

### Language

TypeScript

### Language Version

5.4

### Other information

using latest aws-cdk-lib version

**Comment by ashishdhingra** [comment]
@justin-masse Good afternoon. Thanks for opening the issue. If you refer the documentation for [StartingPosition.AT_TIMESTAMP](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda.StartingPosition.html#at_timestamp), it is **only supported** for Amazon Kinesis streams. Based on this limitation, if you refer documentation for [KinesisEventSource  > KinesisEventSourceProps](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda_event_sources.KinesisEventSourceProps.html), it does support [startingPositionTimestamp](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda_event_sources.KinesisEventSourceProps.html#startingpositiontimestamp) property.

Thanks,
Ashish
