### ISSUE TITLE
(aws-cdk): Allow CLI to reuse cdk.out on subsequent commands

### ISSUE THREAD

**Issue by hanseltime** [aws/aws-cdk#32244]
### Describe the feature

When I call `cdk <action>`, I should have the option (non-default) to tell the cdk to use the existing CloudAssembly in the output directory.

Example:

```shell
cdk synth
# This command would skip all of the CloudAssembly synthesis time because it would just load what is there
cdk diff --reuse-out -e my-stackA
```

### Use Case

Currently, if I run `cdk synth` and then `cdk diff stack-a` or `cdk deploy`, etc.  The entire CDK app is rendered out completely before the actual diff or deploy function is done.  As a default state, I have no issue with this, since that guarantees that I didn't change any CDK code and have stale output.

However, with growing CDK apps (especially those that might write a lot of data, like EKS clusters with manifests or dashboard templates), running multiple cdk commands becomes an expensive chore (we're talking up to 5-10 minutes of additional lost time given larger grouping).  For both controlled CD environments (where I may want to run synth, maybe output a diff, and then deploy) and local development/troubleshooting (where you might want to run many separate stack diffs as you verify something), it would be very helpful to have a top-level flag like: `--reuse-out`, that would allow subsequent calls to operate on the same output from a previous synth step.

### Proposed Solution

I have implemented something like this already, albeit in a very hacked way.

Ideally, we would just update the cli.js file `aws-cdk` to:

1. consume the 'reuse-out` flag
2. in the default synthesizer of the CloudExecutable, perform a lookup of the `out` directory and just use cxapi.CloudAssembly to load the assembly and return without re-running the execProgram() function

As a matter of safety, we would write out a warning to console to notify that we are doing this, and we could even print a summary of stacks, etc. for a double check.  I think by making this feature opt-in, the developer is taking an active role in double-checking when they call it.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.169.0

### Environment details (OS name and version, etc.)

mac and pop_os

**Comment by floverfelt** [comment]
@hanseltime if you specify the --app flag, you can skip the synthesis: https://docs.aws.amazon.com/cdk/v2/guide/cli.html#cli-app-command

"When deploying, you may also specify a directory containing synthesized cloud assemblies, such as cdk.out, as the value of --app. The specified stacks are deployed from this directory; the app is not synthesized."

We do:
```
cdk --app cdk.out deploy
```
which sped up our deployments quite a bit when the templates were already synthed. I'm not sure if that would work with diff.

**Comment by ashishdhingra** [comment]
> https://docs.aws.amazon.com/cdk/v2/guide/cli.html#cli-app-command

@floverfelt Nice call out.

@hanseltime Please verify if it works for you.

Thanks,
Ashish

**Comment by hanseltime** [comment]
@floverfelt - I have no idea how I've missed that.  That does indeed load the CloudAssembly without rebuilding it in the commands (including diff)!

Thank you and my apologies for creating a feature request that already exists.
