### ISSUE TITLE
CLI: short-lived credentials are not refreshed

### ISSUE THREAD

**Issue by rix0rrr** [aws/aws-cdk#32287]
### Describe the bug

If Role credentials are only valid for 15 minutes, and a deploy operation takes longer than that, the operation should complete successfully.

Make sure that credentials are correctly refreshed by the SDK.

**Comment by ashishdhingra** [comment]
Opened by CDK team. Marking it as `p2`.

**Comment by rix0rrr** [comment]
Internal reference D181861042
