### ISSUE TITLE
(repo tooling): cannot install with dotnet 9

### ISSUE THREAD

**Issue by kirkwaiblinger** [aws/aws-cdk#32282]
### Describe the bug

when running `yarn build` as a new contributor, and installing dotnet in order to address the build requirements check, I get 
```text
Checking dotnet version... Found dotnet version 9.0.100 [/usr/local/share/dotnet/sdk]. Install dotnet >= 6.0.100
```
9.9.100 is plainly >= 6.0.100, so I propose the erorr message be updated to match the actual requirements in order to make setup accessible for new contributors.

Related: #17605

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

No error, or error message like 
```text
Checking dotnet version... Found dotnet version 9.0.100 [/usr/local/share/dotnet/sdk]. Install dotnet >= 6.0.100 and < 9
```

### Current Behavior

```text
Checking dotnet version... Found dotnet version 9.0.100 [/usr/local/share/dotnet/sdk]. Install dotnet >= 6.0.100
```

### Reproduction Steps

`yarn build` on a machine with dotnet == 9.0.100

### CDK CLI Version

n/a. This is on main, commit 0153da42c7c1ace591711e8b0b7afad8f21e44c1

### Node.js Version

v22.11.0

### OS

macos

### Language

TypeScript

### Language Version

n/a

### Other information

It would also be helpful if the error message when dotnet is missing gave mentioned referring to the CONTRIBUTING.md for `.NET SDK` installation instructions. I searched for `dotnet` in `CONTRIBUTING.md` and found nothing.

**Comment by kirkwaiblinger** [comment]
Oh, it would also be helpful if the gitpod instructions were mentioned _before_ the Quick Start instructions. That's a great feature for contributors, but I didn't know it to use it because I was trying to follow the directions in order 🤦‍♂️

**Comment by ashishdhingra** [comment]
Reproducible (also when executing `scripts/check-build-prerequisites.sh`)
```
Checking if node is installed... Ok
Checking node version... Ok
Checking if yarn is installed... Ok
Checking yarn version... Ok
Checking if docker is installed... Ok
Checking if Docker is running... Ok
Checking if dotnet is installed... Ok
Checking dotnet version... Found dotnet version 9.0.100 [/local/home/ashdhin/.dotnet/sdk]. Install dotnet >= 6.0.100
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
Need to modify RegEx at https://github.com/aws/aws-cdk/blob/2eebc5913966f0266efbad65c3f137c07c75270b/scripts/check-build-prerequisites.sh#L130.
