### ISSUE TITLE
AwsCdkCli: cdk deploy tries automatic rollback even when `--no-rollback` specified

### ISSUE THREAD

**Issue by dsturnbull** [aws/aws-cdk#32295]
### Describe the bug

I run `cdk deploy X --no-rollback`, and some failure happened. CDK reports:
```
X: deploying... [1/1]
X: creating CloudFormation changeset...
Stack is in a paused fail state and command line arguments do not include "--no-rollback". Roll back first and then proceed with deployment (y/n)?
```

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

I believe that if `--no-rollback` is supplied, automatic rollback should clearly be disabled, and also we should not be presented with an incorrect message

### Current Behavior

CDK attempts reports incorrect message

### Reproduction Steps

Contrive a non-fatal transient cloudformation error such that you would normally attempt a redeploy after some time.

### Possible Solution

Disable automatic rollback if `--no-rollback` supplied.

### CDK CLI Version

2.170.0

### Node.js Version

18.20.4

### OS

macOS

### Language

TypeScript

**Comment by rix0rrr** [comment]
This should only be able to happen if the `--no-rollback` flag is ignored altogether. But it doesn't seem to be, right? Normally you are able to perform `--no-rollback` deployments?

Can you run `npx cdk deploy --no-rollback -vvv` when this happens again and paste the log?

**Comment by rix0rrr** [comment]
I was able to repro.
