### ISSUE TITLE
aws_eks: Cluster Name generation can cause inability to create BottleRocket clusters 

### ISSUE THREAD

**Issue by Gum-Christopher-bah** [aws/aws-cdk#32299]
### Describe the bug

When supplying a cluster name that is not Kubernetes label compliant, bottlerocket nodes are unable to join the cluster and the cdk deployment fails. 

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

Cluster can properly handle bottlerocket nodes

### Current Behavior

Error from Ec2 system logs:
```
Unable to deserialize into KubernetesClusterName: Given invalid cluster name 'eksclusterEksClusterEastBr5useast1clusterE0E4572F-c36ad2b5b0494751969f4e15a4c91a6d': cluster names must be valid Kubernetes label
```

### Reproduction Steps

Create a cluster with either no name or a name like the one provided above (which was cdk generated)
```
const clusterName = eksclusterEksClusterEastBr5useast1clusterE0E4572F-c36ad2b5b0494751969f4e15a4c91a6d;
const cluster = new eks.Cluster(this, 'hello-eks', {
  version: eks.KubernetesVersion.V1_31,
  kubectlLayer: new KubectlV31Layer(this, 'kubectl'),
  defaultCapacity: 0,
  clusterName: clusterName,
});
```
Create user data for bottlerocket and add it to a launch template, add nodegroup capacity
```
const userData = ec2.UserData.forLinux();
userData.addCommands(`[settings.kubernetes]
api-server = "${this.cluster.clusterEndpoint}"
cluster-certificate = "${this.cluster.clusterCertificateAuthorityData}"
cluster-name = "${clusterName}"
[settings.host-containers.admin]
enabled = ${bottleRocketAdminContainerEnabled}`,
      );
      
    launchTemplate = new ec2.LaunchTemplate(this, `${Stack.of(this).stackName}-${Stack.of(this).region}-launch-template-br`, {
        blockDevices: [{
          deviceName: '/dev/xvda',
          volume: autoscaling.BlockDeviceVolume.ebs(
            50,
            {
              volumeType: autoscaling.EbsDeviceVolumeType.GP3,
            },
          ),
        }],
        machineImage: ec2.MachineImage.fromSsmParameter('/aws/service/bottlerocket/aws-k8s-1.31/x86_64/latest/image_id'),
        instanceType: 't3.medium',
        userData: userData,
      });
      Tags.of(launchTemplate).add('eks:cluster-name', clusterName);
      Tags.of(launchTemplate).add('eks:nodegroup-name', nodeGroupName);
      cluster.addNodegroupCapacity(`${Stack.of(this).stackName}-${Stack.of(this).region}-ng`, nodeGroupOptions);
```

In theory, you could skip all the launch template stuff and just try to pass the bottlerocket ami type to the nodegroup via options directly, this is just how I did it so I could set userData settings.

### Possible Solution

generate cluster names in all lowercase, potentially truncate for very large cluster names

### CDK CLI Version

2.170.0

### Node.js Version

18.20.4

### OS

Mac

### Language

TypeScript

**Comment by Gum-Christopher-bah** [comment]
The workaround is to supply a k8s label compliant cluster name, but this is not apparent at all without troubleshooting failed deployments

**Comment by khushail** [comment]
Hi @Gum-Christopher-bah , thanks for reporting this. On checking AWS Docs, rules regrading the Clustername are -
```
The name can contain only alphanumeric characters (case-sensitive) and hyphens. It must start with an alphanumeric character and can’t be longer than 100 characters. The name must be unique within the AWS Region and AWS account that you’re creating the cluster in.
```

Referenced docs -
- https://docs.aws.amazon.com/eks/latest/userguide/create-cluster.html
- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-eks-cluster.html#aws-resource-eks-cluster-properties

Also troubleshooting guide also lists out reasons of failure which are helpful -
https://docs.aws.amazon.com/eks/latest/userguide/troubleshooting.html#worker-node-fail 

However I will try to repro this error as well.

**Comment by khushail** [comment]
@Gum-Christopher-bah , i tried reproducing the scenario with this code which failed during deployment with the error code-
```ts
const clusterName = "eksclusterEksClusterEastBr5useast1cluster1011234E0E4572F-c36ad2b5b0494751969f4e15a4c91a6d";
    const cluster = new eks.Cluster(this, 'hello-eks-101', {
      version: eks.KubernetesVersion.V1_31,
      kubectlLayer: new KubectlV31Layer(this, 'kubectl101'),
      defaultCapacity: 0,
      clusterName: clusterName,
    });

    cluster.addNodegroupCapacity('custom-node-group-101', {
      amiType: eks.NodegroupAmiType.BOTTLEROCKET_X86_64
    });
```

Error received -
```
Resource handler returned message: "[Issue(Code=NodeCreationFailure, Message=Instances failed to join the kubernetes cluster
```

however when i changed the cluster name, it also fails with deployment error citing `cluster crreation access denied` -
```
const clusterName = "$eksclusterv2";
```

wonder what's going wrong as I am not super knowledgeable about creating bottlerocket clusters. 
Does the example code shared look good to you for reproducing the error ? @Gum-Christopher-bah
