### ISSUE TITLE
aws-codebuild : Cannot create a CodeBuildProject Source using a codestar connection 

### ISSUE THREAD

**Issue by lehigh123** [aws/aws-cdk#32300]
### Describe the issue

In the AWS console I am able to create a Code Build buildproject with:
1. Github as the source:
2. Custom source credential 
3. Specify which codestar connection should be used 
4. And then select the repository I am interested in 

However, when I try to make the corresponding build project defined in CDK it is not possible:

e.g. my connection works when I use it to create a codestar source action:

```
 return new CodeStarConnectionsSourceAction(
            {
                actionName: `${this.repo}`,
                connectionArn: this.connectionArn,
                repo: this.repo,
                output: artifact,
                owner: this.owner,
                branch: this.branch
            }
        )
```

but there is no corresponding way to use that ```connectionArn``` 

```
import {BuildSpec, LinuxBuildImage, Project, Source} from "aws-cdk-lib/aws-codebuild";
...

        const buildDockerImage = new Project(this, '123Project',
            {
                projectName: "123BProject",
                source: ?
                
            });
```

### Links

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_codebuild.Project.html
https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_codebuild.GitHubSourceProps.html

**Comment by khushail** [comment]
Hi @lehigh123 , checking the AWS Cloudformation docs and CDK as well, looks like CodeBuild source does not provide the support for using CodeStar connection arn -

- CDK - https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_codebuild.Source.html
- Cloudformation - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-source.html#cfn-codebuild-project-source-sourceidentifier
 
 Hope that is helpful. Let me know if you any questions.

**Comment by 65156** [comment]
why is it possible to do this via the webGUI then?

i am also having this issue

**Comment by BobbyTumur** [comment]
> why is it possible to do this via the webGUI then?
> 
> i am also having this issue

Probably because AWS Console uses API calls rather than CDK -> CF.
For IaC, terraform is able to do such initialization, for CDK prob gotta wait for CF support then CDK side implementation.
