### ISSUE TITLE
(aws-elasticloadbalancingv2): SslPolicy missing ELBSecurityPolicy-TLS13-1-2-2021-06

### ISSUE THREAD

**Issue by lumattr** [aws/aws-cdk#32307]
### Describe the bug

https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/shared/enums.ts#L132-L145

You have `TLS13_10`, `TLS13_11`, and `TLS13_13`, but no `TLS13_12`.

Its apparently in `RECOMMENDED_TLS` which seems like a silly idea as that may change causing unexpected changes for consumers if that ever changes.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

If its a list of available policies it should be a consistent list with the policies available.

### Current Behavior

Missing the most commonly used policy in the expected place.

### Reproduction Steps

N/A

### CDK CLI Version

15.29.6

### Node.js Version

v22.11.0

### OS

Ubuntu

### Language

TypeScript

**Comment by ashishdhingra** [comment]
We cannot rename existing [SslPolicy.RECOMMENDED_TLS](https://github.com/aws/aws-cdk/blob/be000a251b781b0b0870930992793df5a2fc4b01/packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/shared/enums.ts#L109C3-L109C18) enum value name. Probably, introducing another enum name `TLS13_12` with value `ELBSecurityPolicy-TLS13-1-2-2021-06` should mitigate this issue.

@lumattr Feel free to contribute PR mentioning reason for change, that could be reviewed by the team. They should reply back in case of any concerns.

Thanks,
Ashish
