### ISSUE TITLE
cdk bootstrap: Error running cdk bootstrap with custom template 

### ISSUE THREAD

**Issue by saiumesh-appfire** [aws/aws-cdk#32330]
### Describe the bug

We’re encountering an inconsistent issue with CDK bootstrap when using a custom template. Here’s the scenario: 

1. We initially bootstrap using the command:
```
cdk bootstrap aws://<accountId>/us-east-1 --template bootstrap-template.yaml
```
This works as expected, and the resources are created successfully.

2. However, when we update the template to include new permissions and attempt to reapply it with:

```cdk bootstrap aws://<accountId>/us-east-1 --template bootstrap-template.yaml --force``` or ```cdk bootstrap aws://<accountId>/us-east-1 --template bootstrap-template.yaml```

(with or without the --force flag),the command fails intermittently with below error 

```
Environment aws://<accountId>/us-east-1 failed bootstrapping: Error: Trying to perform an operation that requires a bootstrap stack; you should not see this error, this is a bug in the CDK CLI.
    at NoBootstrapStackEnvironmentResources.lookupToolkit (/Users/apple/.volta/tools/image/packages/cdk/lib/node_modules/cdk/node_modules/aws-cdk/lib/index.js:614:6763)
    at makeBodyParameter (/Users/apple/.volta/tools/image/packages/cdk/lib/node_modules/cdk/node_modules/aws-cdk/lib/index.js:603:14404)
    at deployStack (/Users/apple/.volta/tools/image/packages/cdk/lib/node_modules/cdk/node_modules/aws-cdk/lib/index.js:613:283)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _BootstrapStack.update (/Users/apple/.volta/tools/image/packages/cdk/lib/node_modules/cdk/node_modules/aws-cdk/lib/index.js:614:10772)
    at async /Users/apple/.volta/tools/image/packages/cdk/lib/node_modules/cdk/node_modules/aws-cdk/lib/index.js:821:1671
Trying to perform an operation that requires a bootstrap stack; you should not see this error, this is a bug in the CDK CLI.
```

3. Interestingly, if I manually update the same template through the AWS CloudFormation console, it works without any issues.

Is there something we might be missing, or could this be a bug in the CDK bootstrap process? We’d appreciate your guidance on troubleshooting this.

Thank you!

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Last Known Working CDK Version

2.171.1 (build a95560c)

### Expected Behavior

- The updated template with new permissions should apply successfully when using the `cdk bootstrap` command.
- The `--force` flag should reliably overwrite the existing resources with the updated template, without requiring manual intervention through the AWS console.
- There should be consistent behavior between applying changes via `cdk bootstrap` and updating the CloudFormation stack manually in the AWS console.

### Current Behavior

- The initial `cdk bootstrap` command with the custom template works as expected, creating the necessary resources.
- When updating the template with new permissions and reapplying it using `cdk bootstrap` (with or without the `--force` flag), the process fails intermittently
- The same template works perfectly fine when updated manually via the AWS CloudFormation console.

### Reproduction Steps

1. Create a custom CloudFormation template (e.g., `bootstrap-template.yaml`) with specific permissions and resources for CDK bootstrap.
2. Run the initial bootstrap command: ``` cdk bootstrap aws://<accountId>/us-east-1 --template bootstrap-template.yaml```
3. Modify the template to include new permissions or resources.
4. ```cdk bootstrap aws://<accountId>/us-east-1 --template bootstrap-template.yaml --force``` or ```cdk bootstrap aws://<accountId>/us-east-1 --template bootstrap-template.yaml```
5. Observe that the update fails intermittently 
6. Manually update the same template through the AWS CloudFormation console.
   

### CDK CLI Version

2.171.1 (build a95560c)

### Node.js Version

18.16.0

### OS

MacOS

### Language

TypeScript

**Comment by saiumesh-appfire** [comment]
Hi @ashishdhingra ,Thank you for your response!

This issue seems to occur intermittently, not every time, which makes it a bit tricky to debug. Unfortunately, I’m unable to share the internal template we’re using. Given that the error message states, `you should not see this error, this is a bug in the CDK CLI,` do you have any suggestions on how to proceed if this happens again?

Thanks for your help!

**Comment by ashishdhingra** [comment]
> Hi @ashishdhingra ,Thank you for your response!
> 
> 
> 
> This issue seems to occur intermittently, not every time, which makes it a bit tricky to debug. Unfortunately, I’m unable to share the internal template we’re using. Given that the error message states, `you should not see this error, this is a bug in the CDK CLI,` do you have any suggestions on how to proceed if this happens again?
> 
> 
> 
> Thanks for your help!

@saiumesh-appfire You may try using `--verbose --trace` flags when this issue occurs to capture the trace, thereafter opening new issue with the findings.

We would close this issue for now.

Thanks,
Ashish

**Comment by saiumesh-appfire** [comment]
Thanks, @ashishdhingra I'll close the issue now and will open it with traces once we have this error. Thanks for your help!!
