### ISSUE TITLE
aws_elasticloadbalancingv2: Incorrect statement that NLB health check healthy/unhealthy counts need to be the same

### ISSUE THREAD

**Issue by vcschapp** [aws/aws-cdk#32365]
### Describe the issue

The documentation for the [`unhealthyThresholdCount`](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_elasticloadbalancingv2.HealthCheck.html#unhealthythresholdcount) member of the ELBv2 [`HealthCheck`](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_elasticloadbalancingv2.HealthCheck.html) interface says that for NLBs the unhealthy threshold count must be the same as the healthy threshold count:

> ### unhealthyThresholdCount?
> 
> Type: `number` (*optional, default: 2*)
> 
> The number of consecutive health check failures required before considering a target unhealthy.
> 
> For Application Load Balancers, the default is 2. **For Network Load Balancers, this value must be the same as the healthy threshold count**.

This does not appear to be accurate.

- When I create an NLB target group manually in the AWS EC2 console and configure the health check manually, I can set the healthy/unhealthy counts to different values.
- There is no reference to this limitation in the CloudFormation documentation for [`AWS::ElasticLoadBalancingV2::TargetGroup`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-targetgroup.html) or any of its member attributes.
- There is no attempt to validate this constraint in the CDK TypeScript code.

![image](https://github.com/user-attachments/assets/694f7a16-92ca-4686-b04e-ef13cb017b4d)

### Links

1. **Impacted CDK documentation page**: https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_elasticloadbalancingv2.HealthCheck.html#unhealthythresholdcount
2. **Documentation source in GitHub**. https://github.com/aws/aws-cdk/blob/v2.170.0/packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/shared/base-target-group.ts#L135-L136
3. **Relevant CloudFormation documentation**: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-targetgroup.html#cfn-elasticloadbalancingv2-targetgroup-unhealthythresholdcount

### CDK Version

Last checked in documentation for `v2.170.0`.

**Comment by khushail** [comment]
Hi @vcschapp , thanks for reporting this.

I see that on the AWS Docs page, both the range is mentioned as 2-10 while the defaults differ in case of both `UnhealthyThresholdCount` and `HealthyThresholdCount` (https://docs.aws.amazon.com/elasticloadbalancing/latest/network/target-group-health-checks.html) -

<img width="761" alt="Screenshot 2024-12-04 at 5 20 08 PM" src="https://github.com/user-attachments/assets/b355e8d0-d194-4974-8f7a-aea983b06f71">

and the same is mentioned in Cloudformation docs as well -https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-targetgroup.html#cfn-elasticloadbalancingv2-targetgroup-healthythresholdcount

So it might be misleading to write such statement in CDK doc and should be corrected -https://github.com/aws/aws-cdk/blob/a95560cdf116c90a42283492a047967d88630df8/packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/shared/base-target-group.ts#L136
