### ISSUE TITLE
EKS: AL2023 Nvidia instance type missing

### ISSUE THREAD

**Issue by markusl** [aws/aws-cdk#32378]
### Describe the bug

It seems that the GPU instances are missing AL2023 Nvidia and Neuron entries
https://github.com/aws/aws-cdk/blob/bf77e51c90e3da972c464430d579695163160a13/packages/aws-cdk-lib/aws-eks/lib/managed-nodegroup.ts#L595-L600
are

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

All supported GPU instances are in the enumeration

https://aws.amazon.com/blogs/containers/amazon-eks-optimized-amazon-linux-2023-accelerated-amis-now-available/

![image](https://github.com/user-attachments/assets/fc363f8e-52e9-44cc-9071-e6a99ad91f17)

### Current Behavior

GPU instances are missing AL2023 Nvidia and Neuron entries

### Reproduction Steps

See the enum

### CDK CLI Version

2.171.1 (build a95560c)

### Node.js Version

22

### OS

Mac

### Language

TypeScript

**Comment by nmussy** [comment]
I'm not seeing an API endpoint to list all possible values, but the values you listed seem to match the [CloudFormation documentation for `Nodegroup#amiType`](https://docs.aws.amazon.com/eks/latest/APIReference/API_Nodegroup.html#AmazonEKS-Type-Nodegroup-amiType):

* `'AL2023_x86_64_NEURON'`
* `'AL2023_x86_64_NVIDIA'`

---

There is also a `'CUSTOM'` value missing from the `NodegroupAmiType` enum, but it doesn't seem to be needed to use `launchTemplateSpec`

https://github.com/aws/aws-cdk/blob/fa55194698960b9161590e05cf1138a813315615/packages/aws-cdk-lib/aws-eks/lib/managed-nodegroup.ts#L195-L201
https://github.com/aws/aws-cdk/blob/fa55194698960b9161590e05cf1138a813315615/packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-cluster.ts#L251-L259

**Comment by ashishdhingra** [comment]
@nmussy Thanks for your review. We need to update [NodegroupAmiType](https://github.com/aws/aws-cdk/blob/bf77e51c90e3da972c464430d579695163160a13/packages/aws-cdk-lib/aws-eks/lib/managed-nodegroup.ts#L29) enum as well. Community contributed PR is welcome. :)
