### ISSUE TITLE
aws-synthetics: canary name limit is inconsistent with the API

### ISSUE THREAD

**Issue by regmicmahesh** [aws/aws-cdk#32376]
### Describe the bug

When I set the `canaryName` via cdk code then it says the maximum allowed character is 21. But when I do the same thing on AWS Management Console, I can have upto 255 characters.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

I expected the CDK to have the same limit to the AWS Management Console API.

### Current Behavior

I'm getting this error.

Error: Canary name is too large, must be between 1 and 21 characters, but is 29 (got "Generiskinvalid_id_case_12345")

### Reproduction Steps

Create a synthetic resource with canaryName string having length of more than 21 characters.

```
        new aws_synthetics.Canary(this, cdkLogicalId, {
          schedule: aws_synthetics.Schedule.rate(cdk.Duration.minutes(5)),
          canaryName: cdkLogicalId,
          vpc: vpc,
          vpcSubnets: { subnetGroupName: "Private" },
          runtime: aws_synthetics.Runtime.SYNTHETICS_PYTHON_SELENIUM_4_0,
          test: aws_synthetics.Test.custom({
            code: codeAsset,
            handler: `${canaryNameWithoutExt}.handler`,
          }),
          timeout: cdk.Duration.minutes(1),
          startAfterCreation: false,
        });
      });

```

### Possible Solution

https://github.com/aws/aws-cdk/blob/bf77e51c90e3da972c464430d579695163160a13/packages/aws-cdk-lib/aws-synthetics/lib/canary.ts#L747-L753

In this file,  we should update the comparison to be `length > 255`.

### CDK CLI Version

2.162.1 (build 10aa526)

### Node.js Version

v18.18.2

### OS

Terminal

### Language

TypeScript

### Language Version

"aws-cdk-lib": "^2.171.0"

**Comment by khushail** [comment]
Hi @regmicmahesh , thanks for reporting this. Yes, I can see the difference in the limit as its mentioned 255 chars in AWS docs -https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-synthetics-canary.html

<img width="699" alt="Screenshot 2024-12-04 at 11 04 05 AM" src="https://github.com/user-attachments/assets/185e1f98-3326-4380-9232-48efc7227181">

Cloudformation docs also specify the 255 char limit for canary name -

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-synthetics-canary.html#cfn-synthetics-canary-name
