### ISSUE TITLE
core: CustomResourceConfig has no effect

### ISSUE THREAD

**Issue by Dreamescaper** [aws/aws-cdk#32380]
### Describe the bug

I've added the following lines to my CDK app:

```chsarp
var app = new App();

// Add stacks

CustomResourceConfig.Of(app).AddRemovalPolicy(RemovalPolicy.DESTROY);
CustomResourceConfig.Of(app).AddLogRetentionLifetime(RetentionDays.THREE_MONTHS);
```

However, it has no effect. `BucketNotificationsHandl` and `CustomS3AutoDeleteObject` Log Groups are never expired, and are not removed when CF stack is removed.

![image](https://github.com/user-attachments/assets/96382d61-7b06-46cd-9604-964fdfa7f832)

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

LogGroups have 3 months expiry period and are removed when CF stack is deleted.

### Current Behavior

LogGroups have 'Never Expire' period and are not removed when CF stack is deleted.

### CDK CLI Version

2.167.2

### Node.js Version

20

### OS

AmazonLinux

### Language

.NET

### Language Version

.NET 8

### Other information

It is mentioned in comments in this issue: https://github.com/aws/aws-cdk/issues/23909
I decided to add a separate ticket though.

**Comment by khushail** [comment]
Hi @Dreamescaper , thanks for reaching out. Could you please share minimal self-contained code that could help reproduce the issue?

**Comment by wtobi** [comment]
Can we reopen this? I still have the same problem with CDK 2.177.0
