### ISSUE TITLE
aws-ec2 update documentation to match environment-agnostic cloud assemblies feature #2922

### ISSUE THREAD

**Issue by fortunecookiezen** [aws/aws-cdk#3238]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [ ] :beetle: bug report
  - [X] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/awslabs/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**

construct Vpc ignores maxAZs when used without specifying aws region or account. It will always produce a vpc with subnets spread across 2 az if maxAZs >2 or unless maxAZs is <2 without producing an error or warning. API documentation for maxAZs indicates 3 is default.

*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*

export class Vpc3Stack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    // The code that defines your stack goes here
    const vpc = new ec2.Vpc(this, 'vpc', {
      cidr: '10.1.0.0/21',
      maxAZs: 3
    });

npm run build && cdk synth 

* **What is the expected behavior (or behavior of feature suggested)?**

Subnets/AZs should match maxAZs setting in SubnetConfiguration array or should issue a warning when unable to determine if maxAZs will be available in a given region. Documentation should be updated to indicate new behavior introduced in feature #2922

* **What is the motivation / use case for changing the behavior or adding this feature?**

Provide more transparent indication of why output is not as defined in stack or matching default value for maxAZs

* **Please tell us about your environment:**
  
  - CDK CLI Version: > 0.34.0
  - Module Version: xx.xx.xx
  - OS: all
  - Language: Typescript

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

Another option would be to change maxAZs default to 2, and update documentation to indicate how to specifiy >2 availability zones by defining environment variables. A compelling argument could be made that Construct defaults should be region independent, and thus should not include default values that are not implementable in all AWS regions.

**Comment by rix0rrr** [comment]
Will be addressed by https://github.com/aws/aws-cdk/pull/3810

**Comment by SomayaB** [comment]
Closing since it should be addressed by the now merged #3810. Feel free to reopen if that's not the case.
