### ISSUE TITLE
aws-cdk-lib/aws-apigatewayv2: ApiMapping module is not removing mapping path for custom domains

### ISSUE THREAD

**Issue by Madhan-droid** [aws/aws-cdk#32401]
### Describe the bug

Hello Everyone, 
         I was working on mapping my aws apigateway with custom domain name. I was able to create the api mapping using aws cdk. But I'm not able to remove the api mapping path even after removing ApimappingKey from the deployment code.
         
        

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

Initially I created the custom domain with no path.

Here's the code snippet I used for creating the api maping. 
![image](https://github.com/user-attachments/assets/9c82095c-b496-45fa-82ca-71935b79b674)

It created the api mapping with no path. 

In next deployment I updated the code like this:
![image](https://github.com/user-attachments/assets/f31f3552-d9f6-4a7a-8293-4839e54c468d)

I can see the mapping with path:
![image](https://github.com/user-attachments/assets/15e60f50-9424-4e8c-859e-2048de05a820)

But I removed the apiMappingKey from the deployment code then deployed it. 

I'm assuming it should remove the path from the mapping. 

### Current Behavior

I can see the logs of the apimapping being updated:
![image](https://github.com/user-attachments/assets/7ee9bcd7-914a-4ce1-b339-9e9ae14c61a8)

But the mapping path is not removed.
![image](https://github.com/user-attachments/assets/1cd27aac-3f2b-4262-b558-a680d104a8c1)

Is it the default behaviour of aws cdk?

### Reproduction Steps

I have mentioned everything above.

### Possible Solution

The mapping should be removed.

### CDK CLI Version

2.170.0

### Node.js Version

v22.11.0

### OS

Windows 10

### Language

TypeScript

**Comment by khushail** [comment]
Hi @Madhan-droid , thanks for reaching out. Could you share the result of `cdk diff` when you removed the path from the code and re-deployed it ?
