### ISSUE TITLE
CodeBuild: directly connect with codeStarConnection

### ISSUE THREAD

**Issue by vwits-sujit** [aws/aws-cdk#32443]
### Describe the feature

Codebuild project have property called source it allowed to connect to github/bitbucket/codeCommit by passing token key, can't find anyway to connect external source using existing codeStar connection.

### Use Case

When I try to add stage in codePipeline, which have different codebuild I am not able to connect with external source. codePipeline.connection does have option to connect with external source by using codestar connection arn, which is not compartible with ISource in codeBuild.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.172.0

### Environment details (OS name and version, etc.)

ALL

**Comment by vwits-sujit** [comment]
> ```ts
> connectionArn
> ```

Hi @nmussy 

Above example work when i creating pipeline as you explain.

I am creating pipeline in different way. similar like below code. may be you can have a look.

`export class PipelineStack extends Stack{
    constructor(scope: Construct, id: string, props?: cdk.StackProps) {
        super(scope, id, props);
        
        const pipelineSource  = CodePipelineSource.connection("owner/repo", "master", {
            connectionArn: "codeStarConnectionARN",
        })
        const pipeline = new CodePipeline(this, "TestPipeline", {
            pipelineName: "test-pipeline",
            selfMutation: true,
            codeBuildDefaults: {

                subnetSelection: {subnetType: SubnetType.PRIVATE_ISOLATED},
                rolePolicy: [
                    new PolicyStatement({
                        resources: ['*'],
                        effect: Effect.ALLOW,
                        actions: ['kms:Decrypt', 'kms:Encrypt', 'kms:ReEncrypt*', 'kms:GenerateDataKey'],
                    }),
                ],
                partialBuildSpec: BuildSpec.fromObject({
                    phases: {
                        install: {
                            commands: [
                               "Some commands"
                            ],
                        },
                    },
                }),
            },
            synth: new CodeBuildStep("Synth", {
                    input: pipelineSource,
                    // primaryOutputDirectory: 'infra/cdk.out',
                    installCommands: [
                        "Some commands "

                    ],
                    commands: [
                        "Some Commands"
                    ]
                }
            ),
        });

        pipeline.addStage(
            new Application(this, 'NewStuffBuildStage')
        )
    }
}`

applicaton.ts
`
export class Application extends Stage{
    constructor(scope:Construct, id:string, props?: StageProps){
        super(scope, id);
        new StuffBuildStack(this, 'stuffBuildStack')
    }
}
` 

'stuffBuildStack.ts`
`
export class StuffBuildStack extends Stack{
    public readonly blackDuckProject: Project;
    constructor(scope: Construct, id: string, props?: StackProps) {
        super(scope, id, props);

        new Project(this, 'stuff-build',{
            projectName: 'blackduck-scanner',
            role: new Role(this, 'date-calculation-code-quality-check-role', {
                assumedBy: new ServicePrincipal('codebuild.amazonaws.com'),
            }),
//*****************************************
// source required instance of ISource, but can't find the way to provide Isource from CodePipelineSource
            source: pipelineSource //as a props
            buildSpec: BuildSpec.fromSourceFilename(path.resolve(__dirname, 'buildspec.yml')),
        });
    }

`

**Comment by khushail** [comment]
@vwits-sujit , thanks for reaching out. I assume you are talking about such usage as mentioned here in these docs -

- CodeBuild project - https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_codebuild.Project.html
- Source props -https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_codebuild.GitHubSourceProps.html
- CDK - https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_codebuild.Source.html
- Cloudformation - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-source.html#cfn-codebuild-project-source-sourceidentifier
