### ISSUE TITLE
rds: `AuroraPostgresEngineVersion` contains invalid versions

### ISSUE THREAD

**Issue by tmokmss** [aws/aws-cdk#32457]
### Describe the bug

As per doc https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraPostgreSQL.Updates.20180305.html, we can get the available Aurora postgres versions with the following command: `aws rds describe-db-engine-versions --engine aurora-postgresql --query '*[].[EngineVersion]' --output text --region aws-region`

Given the output, at least [`AuroraPostgresEngineVersion.VER_16_6`](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_rds.AuroraPostgresEngineVersion.html#static-ver_16_6) is not supported yet.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

AuroraPostgresEngineVersion contains already available versions.

### Current Behavior

AuroraPostgresEngineVersion contains not-yet-available versions.

### Reproduction Steps

Deployment of Aurora cluster with `AuroraPostgresEngineVersion.VER_16_6` fails.

### CDK CLI Version

2.170.0

### Node.js Version

22

### OS

macos

### Language

TypeScript

**Comment by nmussy** [comment]
Version availability varies by region, in this case it's available in `us-east-2` but not `us-east-1`:

```sh
$ aws rds describe-db-engine-versions --engine aurora-postgresql --region us-east-1 | jq -r '.DBEngineVersions[] | select(.EngineVersion=="16.6") | .EngineVersion'
$ aws rds describe-db-engine-versions --engine aurora-postgresql --region us-east-2 | jq -r '.DBEngineVersions[] | select(.EngineVersion=="16.6") | .EngineVersion'
16.6
```

**Comment by tmokmss** [comment]
@nmussy wow thanks. I thought us-east-1 is one of the most up-to-date region but it seems not. Aurora Postgres 17 also looks only supported in Ohio ([ref](https://aws.amazon.com/about-aws/whats-new/2024/11/amazon-aurora-postgresql-17-rds-database-preview/)). Closing the issue 🙏
