### ISSUE TITLE
(ecs): Support AL2023

### ISSUE THREAD

**Issue by phuhung273** [aws/aws-cdk#32496]
### Describe the feature

ECS support AL2023

### Use Case

ECS support AL2023

### Proposed Solution

ECS [MachineImageType](https://github.com/aws/aws-cdk/blob/9d5ad934caf2c5b30967535631da2caba3b62f0a/packages/aws-cdk-lib/aws-ecs/lib/cluster.ts#L93) add `AMAZON_LINUX_2023`

### Other Information

As instruction https://github.com/aws/aws-cdk/issues/32469#issuecomment-2536820262

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

latest

### Environment details (OS name and version, etc.)

Amazon Linux 2023

**Comment by ashishdhingra** [comment]
@phuhung273 Good morning. I'm unsure if we need to track this separately from https://github.com/aws/aws-cdk/issues/32469#issuecomment-2536820262. Perhaps, you could contribute PR as part of https://github.com/aws/aws-cdk/issues/32469 and close this issue. Please validate.

**Comment by phuhung273** [comment]
Thanks @ashishdhingra. Can we leave this issue open ? For new AL2023 PR i will mention both issues.

Also another point, it must be:
- 1 PR for adding AL2023
- 1 PR for switching default to AL2023. As I have found some failing tests like this https://github.com/aws/aws-cdk/issues/32469#issuecomment-2538778720
