### ISSUE TITLE
(events rule): Event pattern is not valid. Reason: suffix match pattern must be a string 

### ISSUE THREAD

**Issue by phmello20** [aws/aws-cdk#32492]
### Describe the bug

Match.suffix method seems to be generating an invalid event patter

Here's the example:
```
const searchIndexRule = new events.Rule(this, id, {
    eventPattern: {
      detail: {
        matchPrefix: events.Match.prefix('created'),
        matchSuffix: events.Match.suffix('created'),
      },
    },
    eventBus,
    enabled,
  });
```

Once the code is deployed the result is the following:

```
{
    "Rules": [
        {
            "Name": "----",
            "Arn": "----",
            "EventPattern": "{\"detail\": {\"matchPrefix\": [{\"prefix\": \"created:\"}], \"matchSuffix\": [{\"suffix\": [\":created\"]}]}}",
            "State": "ENABLED",
        }
    ]
}
```

prefix works fine and the result is {"prefix": "created"} however, suffix is invalid as the result is {"suffix":["created"]}

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

the event patter should be {"suffix":"created"}

### Current Behavior

the event pattern is {"suffix":["created"]}

### Reproduction Steps

cdk deploy

### CDK CLI Version

2.172.0

### Node.js Version

v20.12.2

### OS

Mac OS 14.6.1

### Language

TypeScript

### Language Version

5.6.3

**Comment by nmussy** [comment]
I'm not able to reproduce the issue in your example, would you be able to provide a complete reproducible code sample?

```ts
const app = new cdk.App();
const stack = new cdk.Stack(app, 'Stack');
const eventBus = new EventBus(stack, 'EventBus');
new Rule(stack, 'Rule', {
  eventPattern: {
    detail: {
      matchPrefix: m.prefix('created'),
      matchSuffix: m.suffix('created'),
    },
  },
  eventBus,
});

Template.fromStack(stack).hasResourceProperties('AWS::Events::Rule', {
  'EventPattern': {
    'detail': {
      matchPrefix: [{ 'prefix': 'created' }],
      matchSuffix: [{ 'suffix': 'created' }],
    },
  },
  'State': 'ENABLED',
});
```

Additionally, I think you are mistaken here:
> prefix works fine and the result is {"prefix": "created"} however, suffix is invalid as the result is {"suffix":["created"]}

According to the docs, both [prefix](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-create-pattern-operators.html#eb-filtering-prefix-matching) and [suffix](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-create-pattern-operators.html#eb-filtering-suffix-matching) matching should be array objects, which is what I'm also seeing in the web console:

Invalid prefix:
<img width="973" alt="image" src="https://github.com/user-attachments/assets/a2599170-f9a1-48d0-a44b-103a9c7dfb27" />

Valid suffix:
<img width="969" alt="image" src="https://github.com/user-attachments/assets/f44747b3-8bb0-4cfb-804c-9afdd0c507a9" />


Invalid suffix:
<img width="972" alt="image" src="https://github.com/user-attachments/assets/d984f09b-43ef-460e-9e2c-de6992bdb902" />
Valid suffix:
<img width="974" alt="image" src="https://github.com/user-attachments/assets/c7aea7c0-62f7-4b84-bca2-a6d3290d7d58" />

**Comment by khushail** [comment]
Hi @phmello20 , thanks for reaching out. 

Here is the sample code for reproducing the issue -

```ts
    const eventBus = new events.EventBus(this, 'EventBus');

    const searchIndexRule = new events.Rule(this, id, {
      eventPattern: {
        detail: {
          matchPrefix: events.Match.prefix('created'),
          matchSuffix: events.Match.suffix('created'),
        },
      },
      eventBus,
      enabled: true,
    });
```

and the synthesized template -

```json
"EventIssueStackE5385CAB": {
   "Type": "AWS::Events::Rule",
   "Properties": {
    "EventBusName": {
     "Ref": "EventBus7B8748AA"
    },
    "EventPattern": {
     "detail": {
      "matchPrefix": [
       {
        "prefix": "created"
       }
      ],
      "matchSuffix": [
       {
        "suffix": "created"
       }
      ]
     }
    },
    "State": "ENABLED"
   },
```

which seems as expected. 

is there anything being missed in the code ? Would request you to share insights on how this issue could be reproduced.

Thanks

**Comment by phmello20** [comment]
hey @khushail, thanks for your response, I'll try again and I'll let you know shortly
