### ISSUE TITLE
EKS: Update KubectlLayer to cdk v2

### ISSUE THREAD

**Issue by clayrosenthal** [aws/aws-cdk#32493]
### Describe the feature

Currently to use any version of kubectl above 1.20, you need to use `'@aws-cdk/lambda-layer-kubectl-v30'`, which is part of CDK v1. CDK v1 has been [deprecated](https://aws.amazon.com/blogs/developer/version-1-of-the-aws-cloud-development-kit-aws-cdk-is-now-in-maintenance-mode/) for over a year.

### Use Case

I want to a KubectlLayer later than version 20 while only using CDK v2.

### Proposed Solution

Update the package to be in cdk v2

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.172.0

### Environment details (OS name and version, etc.)

macOS 14.7

**Comment by pahud** [comment]
Hi 

@aws-cdk/lambda-layer-kubectl-v30 is actually a separate package not included in aws-cdk-lib.

What makes you think it's CDK v1 and wondering if you have seen any conflicts or issues that have to be addressed?
