### ISSUE TITLE
CfnInstance: No default VPC for this user

### ISSUE THREAD

**Issue by tmpm697** [aws/aws-cdk#3251]
I'm trying to create new ec2 instance with `CfnInstance` and I don't have default vpc in my current region.

When run `cdk deploy`, it issued error with `No default VPC for this user`. `cdk diff` gave no error.

But I don't see that `CfnInstance` has `vpc` option in documentation.

**Comment by tmpm697** [comment]
After add `subnet_id`, the above complain's gone but another one: `The parameter groupName cannot be used with the parameter subnet`

**Comment by rix0rrr** [comment]
How do I do X? (assuming we have a stable solution) / Why do I get an error when I do X?

Hi there,

We'd be happy to help you out, but GitHub issues is not a support forum. There are websites much better suited for that, such as StackOverflow. If you could please [ask that same question again on StackOverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk) and paste the link to it here, we will answer it for you over there.

I will now close this issue, feel free to reopen when pasting the StackOverflow link.
