### ISSUE TITLE
EC2: Add Graviton4 processors C8g and M8g to EC2 instance class

### ISSUE THREAD

**Issue by rockaport** [aws/aws-cdk#32522]
### Describe the feature

I'm not sure what's required in terms of availability for adding a new instance class, but they were released in [September](https://aws.amazon.com/about-aws/whats-new/2024/09/amazon-ec2-c8g-m8g-instances/).

If it's as straightforward as just updating the enum I'm willing to submit a PR:
packages/aws-cdk-lib/aws-ec2/lib/instance-types.ts

### Use Case

I'd like to use this instance class in my deployment

### Proposed Solution

Update the instance class enum with these types

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.173.0

### Environment details (OS name and version, etc.)

Ubuntu 24

**Comment by nmussy** [comment]
From what I see running `DescribeInstanceTypes` across `us-east-1` and `us-east-2`, these are the currently missing instance types:

* `c7i-flex`
* `c8g`
* `f2`
* `gr6`
* `i7ie`
* `i8g`
* `m8g`
* `p5e`
* `p5en`
* `trn2`
* `u7i-12tb`
* `u7i-6tb`
* `u7i-8tb`
* `u7in-16tb`
* `u7in-24tb`
* `u7in-32tb`
* `x8g`

Some of these might be inaccessible without developer preview. If you want to add all of these, you should be able to find a human friendly name and a description [here](https://aws.amazon.com/ec2/instance-types/). Let me know if you need help!

**Comment by ashishdhingra** [comment]
> From what I see running `DescribeInstanceTypes` across `us-east-1` and `us-east-2`, these are the currently missing instance types:
> 
> * `c7i-flex`
> * `c8g`
> * `f2`
> * `gr6`
> * `i7ie`
> * `i8g`
> * `m8g`
> * `p5e`
> * `p5en`
> * `trn2`
> * `u7i-12tb`
> * `u7i-6tb`
> * `u7i-8tb`
> * `u7in-16tb`
> * `u7in-24tb`
> * `u7in-32tb`
> * `x8g`
> 
> Some of these might be inaccessible without developer preview. If you want to add all of these, you should be able to find a human friendly name and a description [here](https://aws.amazon.com/ec2/instance-types/). Let me know if you need help!

@nmussy Thanks for sharing the the links to get the missing instance types. CloudFormation documentation appears to be out of sync as well.
