### ISSUE TITLE
cloudfront: expose ARN for `Distribution`

### ISSUE THREAD

**Issue by tmokmss** [aws/aws-cdk#32530]
### Describe the feature

It would be great if we could get ARN of a [CloudFront distribution L2](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_cloudfront.Distribution.html) construct.

### Use Case

easily get ARN of a distribution.

### Proposed Solution

add `IDistribution.distributionArn` property. We already have a function to calculate it.
https://github.com/aws/aws-cdk/blob/bf026bdd8557305d427510af49f1bc538d439cb6/packages/aws-cdk-lib/aws-cloudfront/lib/private/utils.ts#L7-L14

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.170.0

### Environment details (OS name and version, etc.)

macOS

**Comment by ashishdhingra** [comment]
Makes sense to expose the property for processing. The linked PR https://github.com/aws/aws-cdk/pull/32531 attempts to add support.
