### ISSUE TITLE
package: upgrade ESLint to v9

### ISSUE THREAD

**Issue by ren-yamanashi** [aws/aws-cdk#32565]
### Describe the feature

NOTE: Please note that this proposal is not a feature request , but a change request 🙏   
(I could not determine which issue template to propose, so I am proposing a fetrure request...)

Currently v7 of ESLint is used in this repository, but v7 and v8 are now past EOL and should be updated to v9.

see: https://eslint.org/blog/2024/09/eslint-v8-eol-version-support/

Also, v9 changes the way configuration files are written, so I think it is better to write them in `flatConfig`.    
(By specifying environment variables, it is possible to write the configuration file in v9 as it has been written so far (`config`), but in v10, only `flatConfig` is fully functional, so it is considered better to change it to `flatConfig`.

see: https://eslint.org/blog/2023/10/flat-config-rollout-plans/

### Use Case

Because ESLint v7 is past EOL.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.166.0

### Environment details (OS name and version, etc.)

macOS Sonoma v14.0

**Comment by ren-yamanashi** [comment]
Oops, this issue may not be necessary since the following MR was submitte!

https://github.com/aws/aws-cdk/pull/32573

**Comment by khushail** [comment]
Thanks for linking the [action item](https://github.com/aws/aws-cdk/pull/32573) which is being worked on @ren-yamanashi.

Marking it as duplicate.
