### ISSUE TITLE
apigateway: unique name for `restApiName`

### ISSUE THREAD

**Issue by kmkhr** [aws/aws-cdk#32564]
### Describe the feature

Currently the resource ID is set in `restApiName`, but change it to a CloudFormation-compatible unique identifier such as `Names.uniqueResourceName`.

### Use Case

Easily identification of APIs on the management console.

### Proposed Solution

https://github.com/aws/aws-cdk/blob/v2.173.2/packages/aws-cdk-lib/aws-apigateway/lib/restapi.ts#L374

```diff
diff --git a/packages/aws-cdk-lib/aws-apigateway/lib/restapi.ts b/packages/aws-cdk-lib/aws-apigateway/lib/restapi.ts
index 32dca38262..91019e8340 100644
--- a/packages/aws-cdk-lib/aws-apigateway/lib/restapi.ts
+++ b/packages/aws-cdk-lib/aws-apigateway/lib/restapi.ts
@@ -372,11 +372,14 @@ export abstract class RestApiBase extends Resource implements IRestApi {
   protected cloudWatchAccount?: CfnAccount;
 
   constructor(scope: Construct, id: string, props: RestApiBaseProps = { }) {
-    const restApiName = props.restApiName ?? id;
     super(scope, id, {
-      physicalName: restApiName,
+      physicalName:
+        props.restApiName ??
+        Lazy.string({
+          produce: () => Names.uniqueResourceName(this, {}),
+        }),
     });
-    this.restApiName = restApiName;
+    this.restApiName = this.physicalName;
 
     Object.defineProperty(this, RESTAPI_SYMBOL, { value: true });
   }
```

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.173.2

### Environment details (OS name and version, etc.)

macOS

**Comment by khushail** [comment]
Hi @kmkhr , thanks for reaching out.

The `id` that is passed with Construct initialization is the physical id which is supposed to be unique in the scope of current scope. See this for further details -https://docs.aws.amazon.com/cdk/v2/guide/identifiers.html#identifiers_construct_ids

```
The id of a stack is also the identifier that you use to refer to it in the [AWS CDK CLI reference](https://docs.aws.amazon.com/cdk/v2/guide/cli.html).
```
Given ID is also used for generating [Logical id](https://docs.aws.amazon.com/cdk/v2/guide/identifiers.html#identifiers_logical_ids)

So considering all the scenario, I think the `restApiName`  id  assignment/generation should not be changed.

cc: @ashishdhingra
