### ISSUE TITLE
(EcsDeployAction): Optionally allow `service_name` and `cluster_name` as String

### ISSUE THREAD

**Issue by Stretch96** [aws/aws-cdk#32584]
### Describe the feature

Optionally allow `service_name` and `cluster_name` as `str` type for `EcsDeployAction`

And change `service` (`IBaseService`) to optional

### Use Case

Creating an `ecs.FargateService`, which pulls an image from an `ecs.Repository` within the same Stack will fail, or hang (because there will not be an image in the new ECR)

Example Stack:

- ECR Repository
- Fargate Service (Image pulling from the ECR repository)
- CodePipeline connected to GitHub (Build and Push to ECR and `EcsDeployAction` to ECS)

The ECR Repository will create fine, but will be empty

The Fargate Service will launch fine (albeit failing to launch a container), and then the cdk/CloudFormation deploy hangs because the ECR is empty

The CodePipeline doesn't get created because the `EcsDeployAction` Depends on the `IBaseService` type - even though it only needs the Service Name and Cluster Name, which can be provided as known Strings:
https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-codepipeline-actions/lib/ecs/deploy-action.ts#L114-L115

### Proposed Solution

Optionally allow:

```
service_name(Optional[str]) – The ECS Service Name to deploy
cluster_name(Optional[str]) - The ECS Service Cluster's name
```

https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_codepipeline_actions/EcsDeployAction.html

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2

### Environment details (OS name and version, etc.)

N/A

**Comment by khushail** [comment]
@Stretch96 , thanks for reaching out. I see a similar past issue was opened with the same requirements - https://github.com/aws/aws-cdk/issues/17911 and our team provided their insights and workaround here -https://github.com/aws/aws-cdk/pull/17917#pullrequestreview-829371977

Would request you to go through the shared issue and workaround, and see if that matches with what you are asking for.

Thanks
