### ISSUE TITLE
jsii.errors.JSIIError: Expected object reference when attach policy to a role

### ISSUE THREAD

**Issue by tmpm697** [aws/aws-cdk#3260]
I've got this error when trying to attach a policy to a role, `my_role.add_managed_policy('arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy')`:
```
jsii.errors.JSIIError: Expected object reference, got "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"
```

aws-cdk: 0.39.0 (build c3a3c88)

**Comment by aviralvishnoi** [comment]
I hope this will help you:
from aws_cdk import (core,
                     aws_ec2 as ec2,
                     aws_iam as iam)

attach_managed_policy = iam.ManagedPolicy()
base_vpc_ec2_role = iam.Role(self, "BaceVPCEC2Role", 
                                    assumed_by=iam.ServicePrincipal('ec2.amazonaws.com'),
                                    role_name='abc',
                                    managed_policies=[attach_managed_policy.from_aws_managed_policy_name('AmazonEC2ReadOnlyAccess')])

**Comment by RomainMuller** [comment]
Does this still happen with CDK >= 1.0.0 ?

**Comment by arraafat** [comment]
Also when i run  [attach_managed_policy = iam.ManagedPolicy()] i got error [TypeError: __init__() missing 2 required positional arguments: 'scope' and 'id']
