### ISSUE TITLE
Codepipeline cdk v2: Self mutate before synth step

### ISSUE THREAD

**Issue by purnasrivatsa96** [aws/aws-cdk#32628]
### Describe the bug

i believe self mutate runs (if we set self Mutation to true in new CodePipeline(...) initialization) after synth step. What if i change commands in synth . Then i need self mutate to run first so that synth takes the latest codeBuildproject( with updated synth commands).
Proposed Solution -
selfMutateFirst? : boolean

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

A field to configure running self mutate before synth. 

### Current Behavior

No option to configure running self mutate before synth. 

### Reproduction Steps

    const pipeline = new CodePipeline(this, "Pipeline", {
      pipelineName: "TestPipeline",
      selfMutation: true,
      synth: new ShellStep("Synth", {
.
.
.
.
}

### Possible Solution

A field in new CodePipeline() init - 
selfMutateFirst? : boolean

### CDK CLI Version

2.165.0 (build 00f70f1)

### Node.js Version

v18.20.4

### OS

Darwin MacOS

### Language

TypeScript

**Comment by pahud** [comment]
close in favor of https://github.com/aws/aws-cdk/issues/32627
