### ISSUE TITLE
awsroute53: New record A uses lambda Node 14

### ISSUE THREAD

**Issue by joaovitorteixeira** [aws/aws-cdk#32629]
### Describe the bug

I'm trying to create a custom domain for my cognito user pool. This is my code:

``` go
userPoolDomain := userPool.AddDomain(jsii.String("MoonenvCognitoDomain"), &awscognito.UserPoolDomainOptions{
	CustomDomain: &awscognito.CustomDomainOptions{
		DomainName:  props.AuthSubdomain,
		Certificate: props.CdkRoute53StackResource.UsEast1Certificate,
	},
})


awsroute53.NewARecord(stack, jsii.String("MoonenvUserPoolARecord"), &awsroute53.ARecordProps{
	Zone:       props.CdkRoute53StackResource.IHostedZone,
	RecordName: props.AuthSubdomain,
	Target:     awsroute53.AddressRecordTarget_FromAlias(awsroute53targets.NewUserPoolDomainTarget(userPoolDomain)),
})
```

When I deploy it, I get this error: `The runtime parameter of nodejs14.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use a supported runtime while creating or updating functions.`

This is the created template:

```json
  "AWS679f53fac002430cb0da5b7982bd22872D164C4C": {
   "Type": "AWS::Lambda::Function",
   "Properties": {
    "Code": {
     "S3Bucket": {
      "Ref": "AssetParameters105b4f39ae68785e705640aa91919e412fcba2dd454aca53412747be8d955286S3BucketC526447A"
     },
     "S3Key": {
      "Fn::Join": [
       "",
       [
        {
         "Fn::Select": [
          0,
          {
           "Fn::Split": [
            "||",
            {
             "Ref": "AssetParameters105b4f39ae68785e705640aa91919e412fcba2dd454aca53412747be8d955286S3VersionKey237620B5"
            }
           ]
          }
         ]
        },
        {
         "Fn::Select": [
          1,
          {
           "Fn::Split": [
            "||",
            {
             "Ref": "AssetParameters105b4f39ae68785e705640aa91919e412fcba2dd454aca53412747be8d955286S3VersionKey237620B5"
            }
           ]
          }
         ]
        }
       ]
      ]
     }
    },
    "Role": {
     "Fn::GetAtt": [
      "AWS679f53fac002430cb0da5b7982bd2287ServiceRoleC1EA0FF2",
      "Arn"
     ]
    },
    "Handler": "index.handler",
    "Runtime": "nodejs14.x",
    "Timeout": 120
   },
   "DependsOn": [
    "AWS679f53fac002430cb0da5b7982bd2287ServiceRoleC1EA0FF2"
   ],
   "Metadata": {
    "aws:cdk:path": "MoonenvCognitoStack/AWS679f53fac002430cb0da5b7982bd2287/Resource",
    "aws:asset:path": "asset.105b4f39ae68785e705640aa91919e412fcba2dd454aca53412747be8d955286",
    "aws:asset:is-bundled": false,
    "aws:asset:property": "Code"
   }
  },
```

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

I imagine it should try to execute on the LTS version, which is 20

### Current Behavior

It's trying to use version 14

### Reproduction Steps

Create a stack that creates a cognito with a user pool, then try to attach a custom domain (using the example i gave), and finally creates a record o route 53 using `NewUserPoolDomainTarget` as alias. 

### Additional Information/Context

I'm working on it in my public repository on `refator/infra-as-code` branch in case you want to have more context.
https://github.com/PBH-Tech/moonenv

### CDK CLI Version

2.173.2

### Node.js Version

v20.10.0

### OS

Sequoia Version 15.0.1

### Language

Go

### Language Version

go1.22.2

**Comment by pahud** [comment]
Looks like you are still using v1.204?


https://github.com/PBH-Tech/moonenv/blob/619501d58bc514bf9d026ced2c6859fd67d30ae7/server/go.mod#L41C2-L41C27

You need to make sure your awscdk is using v2 and we recommend the latest CDK release.

check https://docs.aws.amazon.com/cdk/v2/guide/work-with-cdk-go.html#go-prerequisites for more details.

**Comment by joaovitorteixeira** [comment]
Thanks @pahud, my bad mate! I've updated it, and it is working... closing this issue
