### ISSUE TITLE
Add resource count to cdk diff

### ISSUE THREAD

**Issue by goranopacic** [aws/aws-cdk#3263]
I'm submitting a :rocket: feature request.
cdk-diff command displays results in several sections. Section Resources has a list of resources that will be added or removed.
I suggest adding a new section called Summary that will show total number of resources in stack currently deployed, total + diff, total - diff, total number of resources the stack will have after deploy and warning if it is above the limit assigned to that account for the maximum number of resources in a stack.

My motivation is to warn about resource limits before deploy.

My current environment:
  - CDK CLI Version: 0.39.0
  - OS: OSX Mojave
  - Language: TypeScript

**Comment by Jerry-AWS** [comment]
Would be nice to have a resource count in `cdk synth` as well.

**Comment by ZachDischner** [comment]
Since CFN stacks have a [hard limit fo 200 resources](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cloudformation-limits.html) having this value available at `synth` time would be excellent.

**Comment by Jerry-AWS** [comment]
Or maybe `cdk ls` should show the resource count next to the stack name...

**Comment by Jerry-AWS** [comment]
https://github.com/aws/aws-cdk/pull/9049 :-)
