### ISSUE TITLE
Reduce CfnParameters for lambda.Function

### ISSUE THREAD

**Issue by artyom-melnikov** [aws/aws-cdk#3266]
* **I'm submitting a ...**
  - [x] :rocket: feature request

* **What is the current behavior?**

Currently for each lambda 2 CfnParameters are created (`LambdaSourceBucketNameParameter` and `LambdaSourceObjectKeyParameter`)

As you can see here: https://github.com/awslabs/aws-cdk/blob/4a0272db5eb9aae5f440bb0813fdbad6514b60c3/packages/%40aws-cdk/aws-lambda/lib/code.ts#L209

CloudFormation has a limitation of 60 parameters, meaning we can only have 30 lambda functions in a single stack

* **What is the expected behavior (or behavior of feature suggested)?**

Add an ability to suppress creation of these parameters, or at least check for the duplicated values (for example `LambdaSourceBucketNameParameter` is duplicated in my case, since all lambda code assets are uploaded to the same CDKToolkit S3 bucket)

* **What is the motivation / use case for changing the behavior or adding this feature?**

Do not add the additional limitations

* **Please tell us about your environment:**
  
  - CDK CLI Version: 0.31.0 (build 7a70c08)
  - Module Version: xx.xx.xx
  - OS: all
  - Language: TypeScript

**Comment by skinny85** [comment]
Hey @artyom-melnikov ,

thanks for opening the issue. You can reduce the number of created parameters by either:

a) re-using the same `CfnParametersCode` for multiple Lambda functions (they can have a different entrypoints, set with the `handler` property)
b) using explicit parameters provided when creating the `CfnParametersCode`, like this:

```ts
lambda.Code.cfnParameters({
  bucketNameParam: yourParam1,
  objectKeyParam: yourParam2,
});
```

(both `bucketNameParam` and `objectKeyParam` are optional construction properties of `CfnParametersCode`)

Hope this helps,
Adam

**Comment by artyom-melnikov** [comment]
This indeed helped, thanks
