### ISSUE TITLE
CodeBuild: build status changes (failed, succeeded, etc) event rules not getting identified as they supposed to. 

### ISSUE THREAD

**Issue by dandu1008** [aws/aws-cdk#3267]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [X] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/awslabs/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*
CodeBuild: build status changes (failed, succeeded, etc) event rules not getting identified as they supposed to. 

  *Resources:*
  - Created a Topic with Email subscription and successfully confirmed the subscription..
  - Created rule targets with custom event input transformer like customised inputTemplate & inputPathMaps and target is above Topic.
  - Created BuildProject rules with Succeed and Failed events (ex: project.onBuildSucceeded(), project.onBuildFailed()) and bind to rule targets.

Resources are created as defined, below is the event pattern, inputPathMaps and inputTemplate. 

*succeeded event pattern:*
``` yaml
{
  "detail-type": [
    "CodeBuild Build State Change"
  ],
  "source": [
    "aws.codebuild"
  ],
  "detail": {
    "build-status": [
      "SUCCEEDED"
    ],
    "project-name": [
      "example-project"
    ]
  }
}
```
*failed event pattern:*
``` yaml
{
  "detail-type": [
    "CodeBuild Build State Change"
  ],
  "source": [
    "aws.codebuild"
  ],
  "detail": {
    "build-status": [
      "FAILED"
    ],
    "project-name": [
      "example-project"
    ]
  }
}
```
*inputTemplate:*
``` yaml
{"buildId":"$.detail.build-id","projectName":"$.detail.project-name","buildStatus":"$.detail.build-status"}
```

*inputPathsMap:*
``` yaml
{"build-id": <buildId>, "project-name": <projectName>,  "build-status": <buildStatus>}
```

Code build project is tested with failed event and succeed event, but not getting any notifications as expected. But the rule metrics, it clearly shows the triggered events, i.e. it is identifying the defined events but not pushing notifications.

The very same configurations created manually i.e. out of CDK, it works. 

Note: Once the CDK deployment, on test failure, the same event pattern is updated with dummy updates like adding another build-status in detail, saved and tested, It works. Rollback this test updates and keep event pattern back to original form, and tested, it works. Point is whatever ruleTarget is created via CDK, it may not bind up tightly with eventRule or not able to fix it from user prospective. 

* **What is the expected behavior (or behavior of feature suggested)?**
Expected behaviour is getting notification on event of build project status changes.

* **What is the motivation / use case for changing the behavior or adding this feature?**
It is is not working as it supposed to be.

* **Please tell us about your environment:**
  
  - CDK CLI Version: 0.36.0
  - Module Version: 0.36.0
  - OS: [all | Windows 10 | OSX Mojave | Ubuntu | etc... ] all
  - Language: [all | TypeScript | Java | Python ] TypeScript

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

**Comment by NGL321** [comment]
Hi @dandu1008, 
Could you share the CDK code you are using to create and bind the event patterns?

While the patterns are helpful for understanding the context, to investigate problems with a construct we would need reproducible CDK code.

**Comment by dandu1008** [comment]
Hi @NGL321 
Please find the below gist link to have cdk code files, but it won't be run as is. These files are copied from my actual project which have other dependent classes and other resources. But this code will give you an idea how the rules are binding with code build, which may helps for your question.

https://gist.github.com/dandu1008/ad236772368a635c3b0a89463efa5802

**Comment by skinny85** [comment]
Hey @dandu1008 ,

thanks for opening the issue, but I was unable to reproduce your results.

Try this simple test:

```ts
import codebuild = require('@aws-cdk/aws-codebuild');
import event_targets = require('@aws-cdk/aws-events-targets');
import sns = require('@aws-cdk/aws-sns');
import sns_sub = require('@aws-cdk/aws-sns-subscriptions');

        const project = new codebuild.Project(this, 'Project', {
            projectName: 'EventsEmittingProject',
            source: codebuild.Source.gitHub({
                owner: 'skinny85',
                repo: 'test-code-build-deploy-spring-boot-project',
            }),
            environment: {
                buildImage: codebuild.LinuxBuildImage.UBUNTU_14_04_OPEN_JDK_8,
            },
        });

        const topic = new sns.Topic(this, 'Topic', {
           topicName: 'codebuild-events-consuming-topic',
        });
        topic.addSubscription(new sns_sub.EmailSubscription("<my-email-address>"));

        project.onBuildStarted('BuildStarted', {
            target: new event_targets.SnsTopic(topic),
        });
```

I started a build of the CodeBuild Project, and I got the following email:

```
{"version":"0","id":"fa52699d-63ca-3d75-b9f8-2eb55c051341","detail-type":"CodeBuild Build State Change","source":"aws.codebuild","account":"123456789012","time":"2020-01-09T00:55:48Z","region":"us-west-2","resources":["arn:aws:codebuild:us-west-2:123456789012:build/EventsEmittingProject:863ae65a-6499-45f5-be7d-3ab874866bbf"],"detail":{"build-status":"IN_PROGRESS","project-name":"EventsEmittingProject","build-id":"arn:aws:codebuild:us-west-2:123456789012:build/EventsEmittingProject:863ae65a-6499-45f5-be7d-3ab874866bbf","additional-information":{"cache":{"type":"NO_CACHE"},"timeout-in-minutes":60.0,"build-complete":false,"initiator":"Admin/adamruka-Isengard","build-start-time":"Jan 9, 2020 12:55:48 AM","source":{"location":"https://github.com/skinny85/test-code-build-deploy-spring-boot-project.git","type":"GITHUB"},"artifact":{"location":""},"environment":{"image":"aws/codebuild/java:openjdk-8","privileged-mode":false,"image-pull-credentials-type":"CODEBUILD","compute-type":"BU
 ILD_GENERAL1_SMALL","type":"LINUX_CONTAINER","environment-variables":[]},"logs":{"deep-link":"https://console.aws.amazon.com/cloudwatch/home?region=us-west-2#logEvent:group=null;stream=null"},"queued-timeout-in-minutes":480.0},"current-phase":"SUBMITTED","current-phase-context":"[]","version":"1"}}

--
If you wish to stop receiving notifications from this topic, please click or visit the link below to unsubscribe:
https://sns.us-west-2.amazonaws.com/unsubscribe.html?SubscriptionArn=arn:aws:sns:us-west-2:123456789012:codebuild-events-consuming-topic:fe39c0de-43be-4d04-9a52-7d52c4901009&Endpoint=adamruka@amazon.com

Please do not reply directly to this email. If you have any questions or comments regarding this email, please contact us at https://aws.amazon.com/support
```

Let me know if this helps, or if you are not able to reproduce these results. In the meantime, I'm removing the 'bug' label from this issue.

Thanks,
Adam

**Comment by SomayaB** [comment]
Closing this issue since there hasn't been any response in a while. Feel free to reopen.
