### ISSUE TITLE
Feature Request: Fargate Worker Fleet Construct in ECS Patterns 

### ISSUE THREAD

**Issue by fulghum** [aws/aws-cdk#3271]
* **I'm submitting a ...**
  - [X] :rocket: feature request

* **What is the expected behavior (or behavior of feature suggested)?**
The [LoadBalancedFargateService Construct in the ECS Patterns module](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs-patterns.LoadBalancedFargateService.html) is so awesome and so easy to use!  It would be cool to provide a version that doesn't require a load balancer, for example, if you just want to spin up a bunch of containers to do some processing, traffic load generation, etc.  This isn't necessarily hard to do with the ECS Constructs, but you do have to explicitly specify the task definition.  It would be nice to consider providing the same super easy creation experience as LoadBalancedFargateService for a non-loadbalanced container cluster.

**Comment by hoegertn** [comment]
Sounds like a great idea. Can you elaborate on the desired interface or features? I could start implementing it if you like.

**Comment by SoManyHs** [comment]
I believe the [QueueProcessingFargateService](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-ecs-patterns/lib/fargate/queue-processing-fargate-service.ts) provides this functionality -- can we close this issue? @fulghum

**Comment by pkandasamy91** [comment]
Resolving this issue. @fulghum please reopen if the [QueueProcessingFargateService](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-ecs-patterns/lib/fargate/queue-processing-fargate-service.ts) does not meet what you were thinking.
