### ISSUE TITLE
Can't delete vpc that created via stack

### ISSUE THREAD

**Issue by tmpm697** [aws/aws-cdk#3277]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/awslabs/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
Can't delete stack dues to can't delete vpc that created via stack
```
The vpc 'vpc-0c57f723328b34c65' has dependencies and cannot be deleted. (Service: AmazonEC2; Status Code: 400; Error Code: DependencyViolation; Request ID: 59823552-e4cd-4a9f-88b2-06795e25531a)
```

I have to delete vpc manually and then delete stack again or delete cloudformation stack manually.

* **What is the expected behavior (or behavior of feature suggested)?**
When `destroy` stack, vpc should be cleaned.

* **What is the motivation / use case for changing the behavior or adding this feature?**

* **Please tell us about your environment:**
  
  - CDK CLI Version: 0.39.0 (build c3a3c88)
  - Module Version: xx.xx.xx
  - OS: Archlinux
  - Language: Python

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

**Comment by rix0rrr** [comment]
It is probably the case that you added resources (instances, load balancers, something else) that use the VPC outside your CDK app, or potentially in a different stack.

The VPC cannot be deleted as long as something still uses it, and CloudFormation will not scan your account to find and delete resources still using it.

Closing this issue now. If you find this issue was closed in error, please reopen it.

**Comment by AlJohri** [comment]
I'm running into the same error. I believe its the Elastic IPs which are created in the same stack.

```
Network vpc-0b490e4e47cbd313c has some mapped public address(es). Please unmap those public address(es) before detaching the gateway. (Service: AmazonEC2; Status Code: 400; Error Code: DependencyViolation; Request ID: 46396ef8-86d8-47f9-8551-6c0160543aa8; Proxy: null)
```

**Comment by AlJohri** [comment]
Nevermind, turns out this issue occurs if you try to reconfigure a VPC in place with the same name. By changing the name it properly deletes the old VPC and creates a new one.

**Comment by adminy** [comment]
Sounds pretty hacky to me. Why can't I just delete and recreate the cdk stack.

`Resource handler returned message: "Cannot delete vpc link in PENDING. Please try again later (Service: AmazonApiGatewayV2; `
