### ISSUE TITLE
Add security group parameters to ecs_patterns.LoadBalancedFargateService

### ISSUE THREAD

**Issue by tmpm697** [aws/aws-cdk#3278]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [ ] :beetle: bug report
  - [x] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/awslabs/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
Default `ecs_patterns.LoadBalancedFargateService` will create IAM roles and SGs but only IAM can be able to choose from its parameters, please add SGs parameters to `LoadBalancedFargateService`

* **What is the expected behavior (or behavior of feature suggested)?**

* **What is the motivation / use case for changing the behavior or adding this feature?**

* **Please tell us about your environment:**
  
  - CDK CLI Version: 0.39.0 (build c3a3c88)
  - Module Version: xx.xx.xx
  - OS: Archlinux
  - Language: Python

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

**Comment by SoManyHs** [comment]
Related: https://github.com/aws/aws-cdk/pull/3985, https://github.com/aws/aws-cdk/issues/2540

**Comment by vjain16** [comment]
seems like this still a problem and no fix yet .

**Comment by MrArnoldPalmer** [comment]
@vjain16 @tmpm697 I assume you mean specifying the security groups on the load balancer, or do you mean specifying SGs on the `FargateService`?

If its on the load-balancer, both [`NetworkLoadBalancedFargateService`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs-patterns.NetworkLoadBalancedFargateServiceProps.html#loadbalancer) and [`ApplicationLoadBalancedFargateService`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs-patterns.ApplicationLoadBalancedFargateServiceProps.html#loadbalancer) allow passing your own load balancer construct as a prop.

On the service itself, you can access the connections object to add new security groups.

```typescript
const fargateService = new ApplicationLoadBalancedFargateService(...);

fargateService.service.connections.addSecurityGroup(someSecurityGroup);
```
[`Connections` Docs](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ec2.Connections.html#add-wbr-security-wbr-groupsecuritygroups)

**Comment by SomayaB** [comment]
Closing for now since there hasn't been a response in a while. Feel free to reopen.
