### ISSUE TITLE
No override for 'ViewerProtocolPolicy' per Behavior

### ISSUE THREAD

**Issue by McDoit** [aws/aws-cdk#3282]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [ ] :beetle: bug report
  - [ ] :rocket: feature request
  - [X] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/awslabs/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*

There is no way on a `CloudFrontWebDistribution` to override the `ViewerProtocolPolicy` on a specific `Behavior`

* **What is the expected behavior (or behavior of feature suggested)?**

To be able to set `ViewerProtocolPolicy` to different values on different `Behavior`s

* **What is the motivation / use case for changing the behavior or adding this feature?**

First of all it is a lack from the CloudFormation type

Secondly I ran into this now when im porting existing CloudFormation templates to the CDK

* **Please tell us about your environment:**
  
  - CDK CLI Version: 0.39
  - Module Version: 0.39
  - OS: [Windows 10]
  - Language: [C#]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

**Comment by iliapolo** [comment]
closing in favor of a more recent duplicate: https://github.com/aws/aws-cdk/issues/7086
