### ISSUE TITLE
Acessing the 'DistributionConfig' of the 'CfnDistribution_' throws an error

### ISSUE THREAD

**Issue by McDoit** [aws/aws-cdk#3284]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [X] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/awslabs/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*

Create a new `CloudFrontWebDistribution`, `var cf = new CloudFrontWebDistribution`
Access the underlying `CfnDistribution_` with `var cfd = cf.Node.FindChild("CFDistribution") as CfnDistribution_;`
Acessing the `DistributionConfig` of the `CfnDistribution_` throws an error:

````
Got 'undefined' for non-optional instance of {"abstract":true,"docs":{"remarks":"If this returns an empty array the stack will not be attached.","stability":"stable","summary":"The creation stack of this resolvable which will be appended to errors thrown during resolution."},"immutable":true,"locationInModule":{"filename":"lib/resolvable.ts","line":38},"name":"creationStack","type":{"collection":{"elementtype":{"primitive":"string"},"kind":"array"}}}
````

* **What is the expected behavior (or behavior of feature suggested)?**

To be able to see the `DistributionConfig` of the  `CfnDistribution_`

* **What is the motivation / use case for changing the behavior or adding this feature?**

I was trying to work around other bugs in the `CloudFrontWebDistribution` by accessing the `DistributionConfig` to modify and add it back as overrides

* **Please tell us about your environment:**
  
  - CDK CLI Version: 0.39
  - Module Version: 0.39
  - OS: [Windows 10]
  - Language: [C#]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)
Stacktrace:
````
Got 'undefined' for non-optional instance of {"abstract":true,"docs":{"remarks":"If this returns an empty array the stack will not be attached.","stability":"stable","summary":"The creation stack of this resolvable which will be appended to errors thrown during resolution."},"immutable":true,"locationInModule":{"filename":"lib/resolvable.ts","line":38},"name":"creationStack","type":{"collection":{"elementtype":{"primitive":"string"},"kind":"array"}}}

   at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
   at Amazon.JSII.Runtime.Deputy.DeputyBase.GetPropertyCore[T](JsiiPropertyAttribute propertyAttribute, Func`2 getFunc)
````

**Comment by RomainMuller** [comment]
Does this problem still exist with `cdk >= 1.0.0`?

**Comment by McDoit** [comment]
Still get the same error message in 1.1.0-devpreview

**Comment by McDoit** [comment]
Still get the same error in 1.4-devpreview

**Comment by McDoit** [comment]
Here is a samll repro:

````
public class ReproCloudFrontStack : Stack
        {
            public ReproCloudFrontStack(Construct scope, string name, IStackProps props) : base(scope, name, props)
            {
                var cf = new CloudFrontWebDistribution(this, "MyDistribution", new CloudFrontWebDistributionProps
                {
                    HttpVersion = HttpVersion.HTTP2,
                    PriceClass = PriceClass.PRICE_CLASS_ALL,
                    OriginConfigs = new ISourceConfiguration[]
                        {
                            new SourceConfiguration
                            {
                                CustomOriginSource = new CustomOriginConfig
                                {
                                    DomainName = "example.com",
                                    HttpPort = 80,
                                    OriginProtocolPolicy = OriginProtocolPolicy.HTTP_ONLY,
                                },
                               Behaviors = new IBehavior[]
                               {
                                   new Behavior
                                   {
                                       AllowedMethods = CloudFrontAllowedMethods.ALL,
                                       Compress = true,
                                       IsDefaultBehavior = true
                                   }
                               }
                            }
                        }
                });

                var cfd = cf.Node.FindChild("CFDistribution") as CfnDistribution;

                var dcp = cfd.DistributionConfig as CfnDistribution.DistributionConfigProperty;

                var ir = cfd.DistributionConfig as IIResolvable;

                Console.WriteLine(ir.CreationStack);
            }
        }
````

`cdp` is null as `DistributionConfig` can't be resolved into `CfnDistribution.DistributionConfigProperty`

But casting `DistributionConfig` into a `IIResolvable` will make the `ir.CreationStack` throw the error

**Comment by McDoit** [comment]
Still an issue with CDK 1.8 and JSII 0.17 sadly

**Comment by McDoit** [comment]
Still an issue with CDK 1.10.1 and JSII 0.18 sadly

**Comment by RomainMuller** [comment]
Alright - thanks for providing the repro code. We'll be having a look into the cause of this (hopefully) shortly, and will update the issue with our findings!

**Comment by McDoit** [comment]
Perfect, thank you @RomainMuller!

These two are a bit related, at least the first, and might be beneficial to work on at the same time?

https://github.com/aws/aws-cdk/issues/3281
https://github.com/aws/aws-cdk/issues/3282

**Comment by RomainMuller** [comment]
Sorry it took me so long to come back. I'm looking into testing your reproduction against the current HEAD of aws/jsii, in hopes that the last kernel bug I fixed was the cause of this issue (I'm pretty optimistic!)

**Comment by McDoit** [comment]
No worries

Just tried the latest CDK with JSII 0.19 with no change
With JSII 0.20 and Visual studio 2019 i get a new error:
`Unhandled exception. System.MissingMethodException: .ctor`
I guess i should file that as a new issue

As a side note i get the following erro in my full code when using alias config and a ACM cert:
`Unhandled Exception: Amazon.JSII.Runtime.JsiiException: acmCertificate certficate must be in the us-east-1 region, got eu-west-1`
even if i specify "us-east-1" in the `DnsValidatedCertificate` i setup in the stack

**Comment by RomainMuller** [comment]
Yeah the problem is our dependencies are currently not modeled currently and this allowed an incompatible JSII runtime to be picked up by your install. We are going to release a fixed version very soon.

**Comment by McDoit** [comment]
Just tested this again, no error this time, but the object returned cant be cast into a `DistributionConfigProperty`, it returns a `Amazon.JSII.Runtime.Deputy.AnonymousObject` instead

It throws this:

```
System.InvalidCastException: 'Unable to cast object of type 'Amazon.JSII.Runtime.Deputy.AnonymousObject' to type 'DistributionConfigProperty'.'
```

**Comment by McDoit** [comment]
@RomainMuller is it possible to open this one up again, as it is still not fixed?

**Comment by njlynch** [comment]
I verified; just reproduced the above errors (`Amazon.JSII.Runtime.Deputy.AnonymousObject`/NPE) on CDK 1.68.0.

**Comment by McDoit** [comment]
@njlynch Maybe unassign @RomainMuller so someone else can take a look?

**Comment by RomainMuller** [comment]
The issue is that `cfd.DistributionConfig` is originally typed as a union, which prevents the .NET code from having enough type information to systematically back this cast. We'll probably need to offer a separate API to allow for this (one already exists, but it might still not allow what you are trying to do right now -- although it probably can be modified to allow that).

**Comment by njlynch** [comment]
@McDoit ,

Separate from the underlying issue, I wonder if we can help with anything with the construct library itself. What is it that CloudFront is missing such that you need to resort to these escape hatches and post-creation modifications?

**Comment by RomainMuller** [comment]
I've created aws/jsii#2192 to introduce an `UnsafeCast<T>()` method on `DeputyBase` (the parent class of `AnonymousObject`) to allow casting to an arbitrary interface type.

This would allow you to perform the following:
```c#
var dcp = (cfd.DistributionConfig as DeputyBase).UnsafeCast<CfnDistribution.DistributionConfigProperty >();
```

Effectively un-blocking your use-case (and other use-cases that involve property overrides with complex/composite properties).

**Comment by McDoit** [comment]
> @McDoit ,
> 
> Separate from the underlying issue, I wonder if we can help with anything with the construct library itself. What is it that CloudFront is missing such that you need to resort to these escape hatches and post-creation modifications?

Trying to remember it from over a year ago, but I think the reason was to modify some option and naming to convert our existing CF stacks to using the CDK instead. So deploying the same stack name (and resources) but wrap it in the CDK instead.

Main issue there was that replacing the CF distributions as custom domains on them need to be unique, and we didn't want to deal with it manually or have downtime solving it.

**Comment by McDoit** [comment]
> I've created [aws/jsii#2192](https://github.com/aws/jsii/pull/2192) to introduce an `UnsafeCast<T>()` method on `DeputyBase` (the parent class of `AnonymousObject`) to allow casting to an arbitrary interface type.
> 
> This would allow you to write something along the lines of:
> 
> ```cs
> var dcp = (cfd.DistributionConfig as DeputyBase).UnsafeCast<CfnDistribution.DistributionConfigProperty>();
> ```
> 
> Effectively un-blocking your use-case (and other use-cases that involve property overrides with complex/composite properties).
> 
> This might become more elegant in the future, as type unions are supported better (more info at [aws/aws-cdk-rfcs#193](https://github.com/aws/aws-cdk-rfcs/issues/193)).

I tried it with CDK 1.70 and JSII 1.14, but I got the following error running the repro stack above:
`System.InvalidCastException: 'Unable to cast Amazon.JSII.Runtime.Deputy.AnonymousObject into Amazon.CDK.AWS.CloudFront.CfnDistribution+DistributionConfigProperty'`

**Comment by RomainMuller** [comment]
Hmmm. Thanks for reporting. I'll have a look into it.
