### ISSUE TITLE
feat(aws-ec2): add ability to pass name to CfnVPCEndpoint

### ISSUE THREAD

**Issue by seawatts** [aws/aws-cdk#3286]
* **I'm submitting a ...**
  - [ ] :beetle: bug report
  - [x] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/awslabs/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*
Instantiating `ec2.CfnVPCEndpoint` does not allow passing in a name for the endpoint resource.

* **What is the expected behavior (or behavior of feature suggested)?**
Have ability to pass in name to `ec2.CfnVPCEndpoint`

* **What is the motivation / use case for changing the behavior or adding this feature?**
It makes it easier to determine which endpoint is for what instead of having to try to look at the endpoint service name ID

* **Please tell us about your environment:**
  
  - CDK CLI Version: 0.39.0
  - Module Version: 0.39.0
  - OS: all
  - Language: all

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

**Comment by rix0rrr** [comment]
Doesn't look like endpoints have a name? https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateVpcEndpoint.html

In any case, the CFN layer supports whatever CloudFormation supports, CDK cannot really help here.
