### ISSUE TITLE
cfn2ts: Include region availability information in generated resource constructs

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#329]
Synthesis should fail is a resource (or property?) are not available in the region this stack is targeting. 

We can do this by by cross-referencing all the specs they publish for each region and determining the regional differences this way.

Then, when a stack is synthesized and we know the target region (which is most of the time), we can ensure that only resources available in that region are used.

We should consider this not only at the resource level but also at the property (/feature) level.

Proposed modeling: the CDK will include the superset of all resources and properties, but the generated resource classes will include metadata information which will indicate in which regions a resource is supported (and/or certain properties of the resource). Then, during synthesis, the region context will be consulted to determine if there is a violation.

Also, incorporate regional information into the JSDocs of the generated resources/properties.

**Comment by rix0rrr** [comment]
@mindstorms6 at some point suggested a CloudFormation transform that could take decisions based on conditions of being in a particular region (maybe omit, or fail, or something similar).

The advantage of running something like that is that both CloudFormation customers as well as CDK customers will be able to take advantage of it.

The downside of it is that it complicates our surface area a lot if we would be the ones to do so.

**Comment by eladb** [comment]
I think this is not the full solution, but required in order to help users or upper layers (L2 for example) to make a decision what to do. 

This does bring up the requirement to be able to query this info in runtime...

**Comment by eladb** [comment]
still relevant
