### ISSUE TITLE
Enhance Subnet selection with Subnet object

### ISSUE THREAD

**Issue by Kent1** [aws/aws-cdk#3291]
* **I'm submitting a ...**
  - [x] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/awslabs/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**

I would like to create one or multiple subnets to a VPC and then create an autoscaling group and specify the subnet(s) i just created. Right now i cannot (or didn't find a way)

* **What is the motivation / use case for changing the behavior or adding this feature?**
I want to be able to specify which subnets to use

* **Please tell us about your environment:**
  
  - CDK CLI Version: 0.39.0
  - Module Version: 0.39.0
  - OS: OSX Mojave
  - Language: Java

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

```
IVpc vpc = Vpc.fromLookup(this, "vpc", VpcLookupOptions.builder()
        .withVpcName("vpc00")
        .build());

    Subnet subnet1 = new Subnet(this, "Subnet1", SubnetProps.builder()
        .withVpcId(vpc.getVpcId())
        .withAvailabilityZone("eu-west-1a")
        .withCidrBlock("10.20.43.0/25")
        .build());

    Subnet subnet2 = new Subnet(this, "Subnet2", SubnetProps.builder()
        .withVpcId(vpc.getVpcId())
        .withAvailabilityZone("eu-west-1b")
        .withCidrBlock("10.20.43.128/25")
        .build());

    final InstanceType instanceType = new InstanceType("t3.micro");
    
    // ECS
    ecsCluster = new Cluster(this, "EcsCluster", ClusterProps.builder()
        .withClusterName("EcsCluster")
        .withVpc(vpc)
        .build());

    ecsCluster.addCapacity("RdapAsgCapacity", AddCapacityOptions.builder()
        .withInstanceType(instanceType)
// I don't know how to specify the subnet. The simpler would be to pass a list of Subnets
        .withVpcSubnets(SubnetSelection.builder().withSubnetName("?").build())
        .withDesiredCapacity(1)
        .build());
```

**Comment by Kent1** [comment]
And also, might be another bug, but if i do 

```
    AutoScalingGroup asgCapacity = ecsCluster.addCapacity("AsgCapacity", AddCapacityOptions.builder()
        .withInstanceType(instanceType)
        .withDesiredCapacity(1)
        .build());

    CfnAutoScalingGroup cfnAsgCapacity = (CfnAutoScalingGroup) asgCapacity.getNode().getDefaultChild();
```

cfnAsgCapacity is null. Do i do something wrong ?

**Comment by ayazhussein** [comment]
@Kent1 I workaround I found is to ```findChild("ASG")``` and the modify the vpcZoneIdentifier with an array of subnet ids.

**Comment by Kent1** [comment]
Thx @ayazhussein. I found the same workaround. i now better understand child resources.

**Comment by febus982** [comment]
Thx @Kent1 and @ayazhussein That workaround works perfectly!

**Comment by rix0rrr** [comment]
This has been added in the mean time
