### ISSUE TITLE
OriginGroup feature is missing in aws-cloudfront

### ISSUE THREAD

**Issue by kawamoto** [aws/aws-cdk#3295]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [ ] :beetle: bug report
  - [x] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/awslabs/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*

* **What is the expected behavior (or behavior of feature suggested)?**

support origin group feature in `@aws-cdk/aws-cloudfront` package. it’s not included in generated code.

* **What is the motivation / use case for changing the behavior or adding this feature?**

that is a missing feature from cloudfront.

* **Please tell us about your environment:**
  
  - CDK CLI Version: 1.0.0
  - Module Version: 1.0.0
  - OS: all
  - Language: TypeScript

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

Looks like it is missing from the cloudformation resource specification.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html

in Api reference, property related originGroups is there.

ex. 
https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_DistributionConfig.html#cloudfront-Type-DistributionConfig-OriginGroups

**Comment by SomayaB** [comment]
Hi @kawamoto, thanks for submitting a feature request! You're right, it looks like OriginGroup is still not supported by CloudFormation and, unfortunately, until it is we won't be able to add it to the CDK. I suggest requesting it on the CloudFormation forum [here](https://forums.aws.amazon.com/forum.jspa?forumID=92).

**Comment by kennu** [comment]
I believe CloudFormation now supports OriginGroups https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/65#issuecomment-596959898

**Comment by kawamoto** [comment]
> I believe CloudFormation now supports OriginGroups [aws-cloudformation/aws-cloudformation-coverage-roadmap#65 (comment)](https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/65#issuecomment-596959898)

it will be coming in next release, yay

https://github.com/aws/aws-cdk/pull/6995
https://github.com/aws/aws-cdk/commit/9a552c275ee011fd794b27735503d139f538f70a#diff-4a4e15a081904ee16b4d84e2f5cf5aeeR61
