### ISSUE TITLE
RDS: Missing default Snapshot deletion policy

### ISSUE THREAD

**Issue by nmussy** [aws/aws-cdk#3298]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [ ] :beetle: bug report
  - [ ] :rocket: feature request
  - [x] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/awslabs/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*
Both RDS Instance and Cluster classes use the [`RemovalPolicy`](https://github.com/aws/aws-cdk/blob/4a0272db5eb9aae5f440bb0813fdbad6514b60c3/packages/@aws-cdk/core/lib/removal-policy.ts#L1) enum for their removalPolicy property, which does not implement the [default `Snpashot` option](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-deletionpolicy.html)

* **What is the expected behavior (or behavior of feature suggested)?**
The Snapshot option should be available. Changing the default to `Snapshot` would also be preferable in my opinion.

* **What is the motivation / use case for changing the behavior or adding this feature?**
Fix gap, possibly gain consistence with CloudFormation's default value.

* **Please tell us about your environment:**
  
  - CDK CLI Version: 1.0.0
  - Module Version: 1.0.0
  - OS: all
  - Language: all

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

The `CfnDeletionPolicy` enum does implement the Snapshot option:
https://github.com/aws/aws-cdk/blob/4a0272db5eb9aae5f440bb0813fdbad6514b60c3/packages/%40aws-cdk/core/lib/cfn-resource-policy.ts#L96

**Comment by NGL321** [comment]
Hi @nmussy,

Thank you for commenting and bringing this to our attention. I did a quick search and validated, this is indeed a gap. We will look into this problem as soon as we are able.

Thank you again, and please know that these contributions really help our project grow and improve. 😸

**Comment by paujim** [comment]
Thank you for CDK I'm loving it.
Is there any update on this? Still happening on version 1.34.1

**Comment by guilarteH** [comment]
I just stumbled across this issue too. Default CDK behaviour is to "Retain" clusters and instances when it should actually be "Snapshot" according to Cloudformation documentation.
An interesting related link:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-deletionpolicy.html
