### ISSUE TITLE
cdkworkshop documentation in https://cdkworkshop.com for python has reference to typescript files

### ISSUE THREAD

**Issue by jayk-sub** [aws/aws-cdk#3301]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [ ] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/awslabs/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*

* **What is the expected behavior (or behavior of feature suggested)?**

* **What is the motivation / use case for changing the behavior or adding this feature?**

* **Please tell us about your environment:**
  
  - CDK CLI Version: xx.xx.xx
  - Module Version: xx.xx.xx
  - OS: [all | Windows 10 | OSX Mojave | Ubuntu | etc... ]
  - Language: [all | TypeScript | Java | Python ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

**Comment by jayk-sub** [comment]
In this url https://cdkworkshop.com/30-python/30-hello-cdk/200-lambda.html, there is reference to lib/cdk-workshop-stack.ts. 
 In this url https://cdkworkshop.com/30-python/20-create-project/300-structure.html, there is reference to hello/hello_stack.ts

**Comment by NGL321** [comment]
Hi @jayk-sub,

Good catch! Thank you for reporting. We did catch these issues shortly after pushing to live, and they were fixed in a PR [here](https://github.com/aws-samples/aws-cdk-intro-workshop/pull/39). We have been waiting to see if anything else bubbled up before pushing a new version of the workshop. I will make sure something gets pushed soon to correct the error.
