### ISSUE TITLE
aws-events-targets EcsTask Only allows one security group to be added

### ISSUE THREAD

**Issue by phcyso** [aws/aws-cdk#3312]
* **I'm submitting a ...**
  - [ ] :beetle: bug report
  - [x] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/aws/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
When using AwsVpc mode for scheduled fargate tasks the optional `securityGroup` prop on EcsTask only allows for passing one security group through.

It gets cast to an array within the custom resource:
https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-events-targets/lib/ecs-task.ts#L141

* **What is the expected behavior (or behavior of feature suggested)?**
It should allow a array of security groups to be passed through.

* **What is the motivation / use case for changing the behavior or adding this feature?**
To allow multiple source security groups to be added to the running scheduled task

* **Please tell us about your environment:**

  - CDK CLI Version: 1.0.0
  - Module Version:1.0.0
  - OS: all
  - Language: typescript

* **Other information**
Unless there are further limitation within the `NetworkConfiguration` & `awsvpcConfiguration` custom resources this should just be able to be changed to an array of Security groups

**Comment by efekarakus** [comment]
Hi @phcyso 👋

PR https://github.com/aws/aws-cdk/pull/7857 adds a new property `securityGroups` and deprecates the existing `securityGroup` to support the request!
