### ISSUE TITLE
defaultChild doesn't work for Autoscaling group

### ISSUE THREAD

**Issue by SanderKnape** [aws/aws-cdk#3314]
* **I'm submitting a ...**
  - [x] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/aws/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*

To get the underlying CFN resource for an Autoscaling group, `node.tryFindChild('ASG')` must be used instead of `node.defaultChild()`. This is because "ASG" is used instead of "Resource" within the construct: https://github.com/aws/aws-cdk/blob/f0fec54d3ed2e1f83763d3cc4ebf9e239ab7dc97/packages/%40aws-cdk/aws-autoscaling/lib/auto-scaling-group.ts#L454 

* **What is the expected behavior (or behavior of feature suggested)?**

To be able to simply use `defaultChild`.

* **What is the motivation / use case for changing the behavior or adding this feature?**

Ideally you wouldn't need access to the underlying CFN resource, but for an autoscaling group there is a use case when using `cfn-init` as described here: https://github.com/aws/aws-cdk/issues/1413

* **Please tell us about your environment:**

  - CDK CLI Version: 1.0.0
  - Module Version: 1.0.0
  - OS: [all]
  - Language: [all ]

**Comment by rix0rrr** [comment]
Fixed by https://github.com/aws/aws-cdk/pull/3572
