### ISSUE TITLE
Python-I am submitting a support request for using aws-cdk for Iam Role creation with multiple inline policies

### ISSUE THREAD

**Issue by aviralvishnoi** [aws/aws-cdk#3316]
* **I'm submitting a ...**
  - [X] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/aws/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*

When I try to create a role with multiple inline policies I get the below given error:
jsii.errors.JSIIError: Expected object reference, got {"AllowLogAccess":{"$jsii.byref":"@aws-cdk/aws-iam.PolicyDocument@10009"}}

Below code do not work
`iam.Role(
            self,
            "BaseVPCIAMLogRole",
            assumed_by=iam.ServicePrincipal('vpc-flow-logs.amazonaws.com'),
            role_name=kwargs["log_role_name"],
            inline_policies=[
                {
                    "AllowLogAccess":
                    iam.PolicyDocument(
                        assign_sids=False,
                        statements=[
                            iam.PolicyStatement(
                                actions=[
                                    'logs:CreateLogGroup', 
                                    'logs:CreateLogStream',
                                    'logs:PutLogEvents', 
                                    'logs:DescribeLogGroups',
                                    'logs:DescribeLogsStreams'
                                ],
                                effect=iam.Effect('ALLOW'),
                                resources=['*']
                            )
                        ]
                    )
                },
                {
                    "AllowS3Access":
                    iam.PolicyDocument(
                        assign_sids=False,
                        statements=[
                            iam.PolicyStatement(
                                actions=[
                                    's3:*'
                                ],
                                effect=iam.Effect('ALLOW'),
                                resources=['*']
                            )
                        ]
                    )
                }
            ]                
        )`

Please let me know if it is a bug or I am doing something wrong,

* **What is the expected behavior (or behavior of feature suggested)?**
[Documentation ](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_iam/Role.html) says **inline_policies (Optional[Mapping[str, PolicyDocument]]) – A list of named policies to inline into this role. These policies will be created with the role, whereas those added by addToPolicy are added using a separate CloudFormation resource (allowing a way around circular dependencies that could otherwise be introduced). Default: - No policy is inlined in the Role resource.**

* **What is the motivation / use case for changing the behavior or adding this feature?**

* **Please tell us about your environment:**

  - CDK CLI Version: 1.0.0
  - Module Version: 1.0.0
  - OS: windows7
  - Language: python

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

When I try to create the role with a single inline policy it works but in that case I dont pass inline policy as list.
Below code works
`iam.Role(
            self,
            "BaseVPCIAMLogRole",
            assumed_by=iam.ServicePrincipal('vpc-flow-logs.amazonaws.com'),
            role_name=kwargs["log_role_name"],
            inline_policies={
                "AllowLogAccess":
                iam.PolicyDocument(
                    assign_sids=False,
                    statements=[
                        iam.PolicyStatement(
                            actions=[
                                'logs:CreateLogGroup', 
                                'logs:CreateLogStream',
                                'logs:PutLogEvents', 
                                'logs:DescribeLogGroups',
                                'logs:DescribeLogsStreams'
                            ],
                            effect=iam.Effect('ALLOW'),
                            resources=['*']
                        )
                    ]
                )
            }                
        )`

**Comment by sjschmidt44** [comment]
@aviralvishnoi `inline_policies` are a Mapping (Python Dict), not a List, so the second code snippet is correctly formatted. See below for an example:
```python
inline_policies={
    'AllowAssumeRole': iam.PolicyDocument(
        statements=[
            iam.PolicyStatement(
                effect=iam.Effect.ALLOW,
                actions=['sts:AssumeRole'],
                resources=[f'arn:aws:iam::*:role/{os.getenv("ASSUME_ROLE_NAME")}']
            )
        ]
    ),
    'AllowListOrgUnitParent': iam.PolicyDocument(
        statements=[
            iam.PolicyStatement(
                effect=iam.Effect.ALLOW,
                actions=['organizations:ListAccountsForParent'],
                resources=['*']
            )
        ]
    )
}
```

These two statements are output as a list of statements within the same policy document when your run `cdk synth`.

**Comment by aviralvishnoi** [comment]
Thank you very much for your response, I understood what I was doing wrong.
