### ISSUE TITLE
Do not include tsconfig in npm modules

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#3317]
* **I'm submitting a ...**
  - [x] :rocket: feature request

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*

tsconfig.json files are included in our npm modules, and they contain relative references to project modules, which appear as errors in IDEs.

* **What is the expected behavior (or behavior of feature suggested)?**

tsconfig.json is not needed in npm modules since typescript code is already compiled.

* **What is the motivation / use case for changing the behavior or adding this feature?**

Bad developer experience:

![Screen Shot 2019-07-16 at 3 24 00 PM](https://user-images.githubusercontent.com/598796/61294114-c8cd0080-a7dd-11e9-9559-d4aed5f0bb0f.png)

**Comment by RomainMuller** [comment]
Note - the typescript doc build currently requires the file being present in the published artifacts.

**Comment by eladb** [comment]
what? why?

**Comment by RomainMuller** [comment]
I don't know - it's a note from @rix0rrr in the `pkglint` rule that excludes the `*.tsbuildinfo` files. Would have to dig more / try stuff to validate or find out how to address.

**Comment by eladb** [comment]
This is ugly

**Comment by rix0rrr** [comment]
We did this.
