### ISSUE TITLE
CfnIdentityPool missing identityPoolId

### ISSUE THREAD

**Issue by artyom-melnikov** [aws/aws-cdk#3338]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] :beetle: bug report
  - [ ] :rocket: feature request
  - [x] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/aws/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*

`CfnIdentityPool` in `aws-cognito` has no `identityPoolId` any more. This id is required for `CfnIdentityPoolRoleAttachment` (`CfnIdentityPoolRoleAttachmentProps`)

* **What is the expected behavior (or behavior of feature suggested)?**

This attribute existed in 0.31.0 at least

* **What is the motivation / use case for changing the behavior or adding this feature?**

* **Please tell us about your environment:**

  - CDK CLI Version: 1.0.0
  - Module Version: 1.0.0
  - OS: [all | Windows 10 | OSX Mojave | Ubuntu | etc... ]
  - Language: TypeScript

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

**Comment by jogold** [comment]
As of v1.0.0 you need to use `ref`.

```ts
const pool = new CfnIdentifyPool(this, 'Pool', ...);
const id = pool.ref;
```

**Comment by artyom-melnikov** [comment]
Thanks

**Comment by andreimcristof** [comment]
had same issue, perhaps the docs on `ref` property could be improved a bit to make it obvious that this resolves in the identityPoolId format?  
Best regards,

**Comment by Zerquix18** [comment]
I second the comment above ^

**Comment by jacido** [comment]
Hi, for CDK V2 is there a a way to do this?
