### ISSUE TITLE
Silent end of deployment

### ISSUE THREAD

**Issue by artyom-melnikov** [aws/aws-cdk#3344]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/aws/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*

I'm migrating from `0.31.0` to `1.0.0`. I have a stack to create ApiGateway and Lambdas
This is part of the code:
```ts
const DEFAULT_RUNTIME = lambda.Runtime.NODEJS_8_10;
const API_LAMBDAS_BASE_PATH = path.join(__dirname, '../../rest/dist');

export class ApiStack extends cdk.Stack {
  private sharedLayer: lambda.LayerVersion;

  constructor(scope: cdk.Construct, id: string, props: ApiStackProps) {
    super(scope, id, props);

    this.createCodeAsset();
    this.createSharedLayer();
    ...
  }

  private createCodeAsset(): void {
    this.codeAsset = lambda.Code.asset(path.join(API_LAMBDAS_BASE_PATH, 'code'));
  }

  private createSharedLayer(): void {
    const layerName = StackUtils.getEnvName('api-layer', this.envName);
    this.sharedLayer = new lambda.LayerVersion(this, layerName, {
      code: lambda.Code.asset(path.join(API_LAMBDAS_BASE_PATH, 'layer')),
      compatibleRuntimes: [ DEFAULT_RUNTIME ],
      description: 'Shared dependencies layer for API Lambdas',
    });
  }
  ...
}
```

The deployment simply ends without any errors rights after the start. The verbose logs:
```
api-stackcdk1test
api-stackcdk1test: deploying...
Waiting for stack CDKToolkit to finish creating or updating...
Preparing asset apistackcdk1testapilayercdk1testCode5ED1E954: {"path":"asset.904bbef99d02b2b8c95d96e2a1621f358c424427f3d15b0c0256838afe31b98f","id":"apistackcdk1testapilayercdk1testCode5ED1E954","packaging":"zip","sourceHash":"904bbef99d02b2b8c95d96e2a1621f358c424427f3d15b0c0256838afe31b98f","s3BucketParameter":"apilayercdk1testCodeS3Bucket2C4C037A","s3KeyParameter":"apilayercdk1testCodeS3VersionKeyDFEF168D","artifactHashParameter":"apilayercdk1testCodeArtifactHash3A74B244"}
Preparing zip asset from directory: cdk.out/asset.904bbef99d02b2b8c95d96e2a1621f358c424427f3d15b0c0256838afe31b98f
```

* **What is the expected behavior (or behavior of feature suggested)?**

Code should create resources properly

* **What is the motivation / use case for changing the behavior or adding this feature?**

* **Please tell us about your environment:**

  - CDK CLI Version: 1.0.0
  - Module Version: 1.0.0
  - OS: [all | Windows 10 | OSX Mojave | Ubuntu | etc... ]
  - Language: TypeScript

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

Seems like either assets are stealthily fails or the `LayerVersion` code

**Comment by jogold** [comment]
What are you zipping? Related to https://github.com/aws/aws-cdk/issues/3145?

**Comment by artyom-melnikov** [comment]
Yes, seems like the same issue. Will update  #3145
