### ISSUE TITLE
TypeError: __new__() got an unexpected keyword argument 'jsii_type' after installing 1.0.0

### ISSUE THREAD

**Issue by alexabate** [aws/aws-cdk#3349]
* **I'm submitting a ...**
:question: support request

* **What is the current behavior?**
After installing aws cdk for the first time:
```
>>> from aws_cdk import core
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/alexabate/.virtualenvs/cdk-test/lib/python3.6/site-packages/aws_cdk/core/__init__.py", line 1554, in <module>
    class DependableTrait(metaclass=jsii.JSIIAbstractClass, jsii_type="@aws-cdk/core.DependableTrait"):
TypeError: __new__() got an unexpected keyword argument 'jsii_type'
```
This looks like it's pointing to a dependency issue but I can't figure out what it is. It seems like the version of `jsii` I'm using doesn't have kwargs in its `__new__()` constructor?

* **Please tell us about your environment:**

  - CDK CLI Version: 1.0.0 (build d89592e)
  - OS: OS: [OSX Mojave 10.14.5]
  - Language: [Python 3.6.0]
  - Node v10.16.0

* **Other information** 
This is might be related to issue [3293](https://github.com/aws/aws-cdk/issues/3293) and with `jsii==                              0.13.4` I get the  `unexpected keyword argument 'name_mapping'` error described there.

Output of `pip freeze`
```
atomicwrites==1.3.0
attrs==19.1.0
aws-cdk.assets==1.0.0
aws-cdk.aws-apigateway==1.0.0
aws-cdk.aws-applicationautoscaling==1.0.0
aws-cdk.aws-autoscaling==1.0.0
aws-cdk.aws-autoscaling-common==1.0.0
aws-cdk.aws-autoscaling-hooktargets==1.0.0
aws-cdk.aws-certificatemanager==1.0.0
aws-cdk.aws-cloudformation==1.0.0
aws-cdk.aws-cloudfront==1.0.0
aws-cdk.aws-cloudwatch==1.0.0
aws-cdk.aws-codebuild==1.0.0
aws-cdk.aws-codecommit==1.0.0
aws-cdk.aws-codepipeline==1.0.0
aws-cdk.aws-ec2==1.0.0
aws-cdk.aws-ecr==1.0.0
aws-cdk.aws-ecr-assets==1.0.0
aws-cdk.aws-ecs==1.0.0
aws-cdk.aws-ecs-patterns==1.0.0
aws-cdk.aws-elasticloadbalancing==1.0.0
aws-cdk.aws-elasticloadbalancingv2==1.0.0
aws-cdk.aws-events==1.0.0
aws-cdk.aws-events-targets==1.0.0
aws-cdk.aws-iam==1.0.0
aws-cdk.aws-kms==1.0.0
aws-cdk.aws-lambda==1.0.0
aws-cdk.aws-logs==1.0.0
aws-cdk.aws-route53==1.0.0
aws-cdk.aws-route53-targets==1.0.0
aws-cdk.aws-s3==1.0.0
aws-cdk.aws-s3-assets==1.0.0
aws-cdk.aws-secretsmanager==1.0.0
aws-cdk.aws-servicediscovery==1.0.0
aws-cdk.aws-sns==1.0.0
aws-cdk.aws-sns-subscriptions==1.0.0
aws-cdk.aws-sqs==1.0.0
aws-cdk.aws-ssm==1.0.0
aws-cdk.aws-stepfunctions==1.0.0
aws-cdk.core==1.0.0
aws-cdk.custom-resources==1.0.0
aws-cdk.cx-api==1.0.0
aws-cdk.region-info==1.0.0
cattrs==0.9.0
importlib-metadata==0.18
importlib-resources==1.0.2
jsii==0.14.0
more-itertools==7.1.0
mypy-extensions==0.4.1
packaging==19.0
pluggy==0.12.0
publication==0.0.3
py==1.8.0
pyparsing==2.4.0
pytest==5.0.1
python-dateutil==2.8.0
six==1.12.0
typing-extensions==3.7.4
wcwidth==0.1.7
zipp==0.5.2
```

**Comment by nscott9350** [comment]
I upgraded to python 3.7 and this fixed the error for me.

**Comment by NGL321** [comment]
Hi @alexabate,

Sorry for the slow response. It looks like this issue has been resolved for several different people. Are you still experiencing the problem? If so, I will make sure this is recorded as a bug and receives attention. Otherwise I'd love to close out the issue!

😸

**Comment by alexabate** [comment]
I ended up uninstalling and reinstalling everything (python, pip, aws cli, aws cdk, all dependencies) and it went away; no idea what was causing the issue

**Comment by NGL321** [comment]
Glad to hear that this went away! If you encounter it again, please do not hesitate to post another issue (and go ahead and @ me in it so I can make sure it gets attention faster this time).

Closing this issue for now.

😸
