### ISSUE TITLE
RDS - Isolated subnet

### ISSUE THREAD

**Issue by RoyMaunders** [aws/aws-cdk#3356]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/aws/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*

Error adding RDS instance to Isolated subnet from imported VPC.

```
Error: There are no 'Isolated' subnets in this VPC. Use a different VPC subnet selection.
```

```javascript
    const vpc = ec2.Vpc.fromLookup(this, "lookupVPC", {
      vpcName: "MyVPC"
    });

    const dbInstance = new rds.DatabaseInstance(this, "Instance", {
      engine: rds.DatabaseInstanceEngine.POSTGRES,
      instanceClass: new ec2.InstanceType("t3.micro"),
      masterUsername: dbInstanceUser,
      vpcPlacement: {
        subnetType: ec2.SubnetType.ISOLATED
      },
      vpc
    });
```
The VPC does contain an isolated subnet (it was created in another cdk stack).  I suspect the problem is here:

https://github.com/aws/aws-cdk/blob/v1.0.0/packages/@aws-cdk/aws-ec2/lib/vpc.ts#L1355

as it doesn't contain a dummy entry for isolated subnets.

* **What is the expected behavior (or behavior of feature suggested)?**

No error. Construct created.

* **What is the motivation / use case for changing the behavior or adding this feature?**

* **Please tell us about your environment:**

  - CDK CLI Version: 00.37.00
  - Module Version: 00.37.00
  - OS: [all | Windows 10 | OSX Mojave | Ubuntu | etc... ]
  - Language: [all | TypeScript | Java | Python ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

**Comment by skinny85** [comment]
Hey @RoyMaunders ,

thanks for opening us the issue. Can you paste the contents of your `cdk.context.json` file? (Feel free to redact your actual AWS account ID from it, and replace it with `123456789012`)

**Comment by RoyMaunders** [comment]
Hi,  the cdk.context.json was empty when getting this problem :)

**Comment by michaeldimoudis** [comment]
I have the exact same issue. I solved it by accident, but really it's not ideal.

Doing `cdk diff` with the rds vpcPlacement set to ISOLATED spat out that error, and there was nothing in `cdk.context.json`.

Changed the rds vpcPlacement set to PRIVATE, did a `cdk diff`, it worked and the `cdk.context.json` populated, with correct isolated subnets in there.

I then changed rds vpcPlacement back to ISOLATED, and this time it worked and got deployed out successfully...

**Comment by AmitBaranes** [comment]
This is a big stopper for us. We use codebuild to deploy the stack and we don't want to change the subnet type to PRIVATE and then back to ISOLATED in each deployment. I looked at the source code and it looks like the isolated subnet based on the private subnet. that's means when you call the Isolated subnet nothing really changes ( therefore, the cdk.context.json is empty) this issue needs to be fixed in the ec2 module.
The only solution I could think of changes the type to private and then check-in the cdk.context.json into the source code. But, this is means we need to maintain the cdk.context.json file, which we don't want to.
Please advise if there's a workaround beside the Private\Isolated solution.

**Comment by mmccauley-verimatrix** [comment]
I encountered this issue for both RDS Aurora & Lambdas and was able to work around it by changing from
```python
vpc_subnets=aws_ec2.SubnetType.ISOLATED
````
To
```python
vpc_subnets=aws_ec2.SubnetSelection(subnet_group_name="data")
```

**Comment by davvilla** [comment]
I was having a similar issue where an RDS instance was being placed in the Private subnets instead of the isolated one. This change solved it:

`vpc_placement=ec2.SubnetType.ISOLATED` -> `vpc_placement=ec2.SubnetSelection(subnet_type=ec2.SubnetType.ISOLATED)`

**Comment by dacoty** [comment]
@davvilla's solution worked for me as well, however i had to destroy/redeploy my database stack to work correctly because of existing VPC dependencies. Not a big deal, it's something i am just starting to work on so no real loss.

**Comment by skinny85** [comment]
@RoyMaunders is it possible that your VPC just didn't have isolated subnets, by how CDK understands that term? (Details here: https://docs.aws.amazon.com/cdk/api/latest/docs/aws-ec2-readme.html#choosing-subnets-for-resources ).

Thanks,
Adam
