### ISSUE TITLE
Kinesis Stream permissions missing ListShards

### ISSUE THREAD

**Issue by perihelion1** [aws/aws-cdk#3357]
* **I'm submitting a ...**
  - [x] :books: construct library gap

* **What is the current behavior?**
`Stream.grantRead` doesn't grant the ListShards permission, which is useful for Kinesis Client Library v2 among other things.

Stream also doesn't offer a custom `.grant(Grantable, List<String>)` to allow an easy workaround.

**Comment by reillykw** [comment]
#6141 should close this PR
