### ISSUE TITLE
Mixing of Languages

### ISSUE THREAD

**Issue by webratz** [aws/aws-cdk#336]
Hi,
so this is more of a question than an issue:
Where are the "barriers" between the different language implementations?
So would it be possible to have Constructs written in different languages within one App?

Related but not the same: will the `cdk` commands also be availlable for use within other tools (eg as a library) and if so, would also all languages be supported?
This would help to integrate cdk within language specific build tooling (eg pybuilder, sbt, ...)
cc @joh-m @pgarbe

**Comment by yuchuanzhang09** [comment]
could you please show a code example in which   one cdk app using python call one stack using typescript?

**Comment by yuchuanzhang09** [comment]
how to call TypeScript constructs  from cdk app using python ?
