### ISSUE TITLE
IResolvable value synthesizing with format cloud formation doesn't accept

### ISSUE THREAD

**Issue by Gamanderr** [aws/aws-cdk#3363]
* **I'm submitting a ...**
  - [x] :beetle: bug report

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*

I am using CfnTableProps and trying to set ProvisionedThroughput to an IResolvable value.
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-dynamodb.CfnTable.html#provisionedthroughput-1

I am using the CfnTableProps builder like:

```
CfnTableProps.builder()
   .withTableName("tablename")
   .withProvisionedThroughput(getProvisionedThroughput())
```

where getProvisionedThroughput() looks like:

```
private ICfnConditionExpression getProvisionedThroughput() {
    ProvisionedThroughputProperty betaProvisionedThroughputProperty = ProvisionedThroughputProperty
            .builder()
            .withReadCapacityUnits(READ_CAPACITY_BETA)
            .withWriteCapacityUnits(WRITE_CAPACITY_BETA)
            .build();

    ProvisionedThroughputProperty prodProvisionedThroughputProperty = ProvisionedThroughputProperty
            .builder()
            .withReadCapacityUnits(READ_CAPACITY_PROD)
            .withWriteCapacityUnits(WRITE_CAPACITY_PROD)
            .build();

    return Fn.conditionIf(isBeta.getLogicalId(),
            betaProvisionedThroughputProperty, prodProvisionedThroughputProperty);

}
```

* **What is the expected behavior (or behavior of feature suggested)?**

I expect during synthesis the ProvisionedThroughput to contain "Fn::If" block with correct parameters. However the ReadCapacityUnits and WriteCapacityUnits keys are returned in lower camelCase instead of Upper CamelCase. 

```
"ProvisionedThroughput": {
                            "Fn::If": [
                                "isBeta",
                                {
                                    "readCapacityUnits": 5,
                                    "writeCapacityUnits": 5
                                },
                                {
                                    "readCapacityUnits": 20,
                                    "writeCapacityUnits": 20
                                }
                            ]
                        }
```

CloudFormation gives unsupported property error for lower camelCase properties. If I manually change template to Upper CamelCase (ie: "ReadCapacityUnits") it works. 

If I use ProvisionedThroughputProperty directly instead of ICfnConditionExpression it synthesizes correctly with Upper CamelCase properties.

* **Please tell us about your environment:**

  - Module Version: 1.0.0
  - OS: [all ]
  - Language: [Java ]

**Comment by eladb** [comment]
This is indeed not supported. This will require special-casing things like `Fn::If` (and I guess other CFN functions) in the generated `toCloudFormation` method in `CfnXxx`.

As a workaround, you should be able to do something like this:

```java

JsonNodeFactory json = JsonNodeFactory.instance;

ObjectNode ifTrue = json.objectNode();
ifTrue.put("ReadCapacityUnits", 20);
ifTrue.put("WriteCapacityUnits", 20);

ObjectNode ifFalse = json.objectNode();
ifFalse.put("ReadCapacityUnits", 200);
ifFalse.put("WriteCapacityUnits", 200);

ICfnConditionExpression throughput = Fn.conditionIf("isBeta", ifTrue, ifFalse);

CfnTable.Builder.create(this, "MyTable")
        .keySchema(Collections.singletonList(CfnTable.KeySchemaProperty.builder().keyType("S").attributeName("ID").build()))
        .provisionedThroughput(throughput)
        .build();
```

**Comment by eladb** [comment]
Stale
