### ISSUE TITLE
Feature request: Make StepScalingPolicy alarm (periods) configurable

### ISSUE THREAD

**Issue by ChrisLahaye** [aws/aws-cdk#3367]
* **I'm submitting a ...**
  - [ ] :beetle: bug report
  - [x] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/aws/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
StepScalingPolicy alarms have a predefined period of 1 minute.

* **What is the expected behavior (or behavior of feature suggested)?**
Allowing StepScalingPolicy alarm props to be passed, or at least having the possibility to change the alarm periods.

* **What is the motivation / use case for changing the behavior or adding this feature?**
To avoid scaling for short fluctuations.

**Comment by rix0rrr** [comment]
Application scaling or instance scaling?

**Comment by ChrisLahaye** [comment]
@rix0rrr instance scaling

Here is a usage example:
```
const autoScalingGroup = new autoscaling.AutoScalingGroup(this, 'Fleet', {
   desiredCapacity,
   instanceType: new ec2.InstanceType(instanceTypeIdentifier),
   machineImage: new ecs.EcsOptimizedAmi(),
   maxCapacity,
   minCapacity,
   notificationsTopic: new sns.Topic(this, 'Topic', { displayName: id }),
   vpc,
 });

const stepScalingPolicy = autoScalingGroup.scaleOnMetric('ScaleOnMemoryReservation', {
  adjustmentType: autoscaling.AdjustmentType.CHANGE_IN_CAPACITY,
  metric: ecsCluster.metricMemoryReservation(),
  scalingSteps: [
    { upper: targetMemoryReservationInterval.min, change: -1 },
    { lower: targetMemoryReservationInterval.max, change: +1 },
  ],
});

[stepScalingPolicy.lowerAlarm, stepScalingPolicy.upperAlarm].forEach((alarm): void => {
  if (!alarm) return;

  const cfnAlarm = alarm.node.findChild('Resource') as cloudwatch.CfnAlarm;

  cfnAlarm.period = 300;
});

ecsCluster.addAutoScalingGroup(autoScalingGroup);
```

**Comment by NetaNir** [comment]
@rix0rrr  looks like this was resolved by https://github.com/aws/aws-cdk/commit/1408eadfcf65b8f79ad026aa684753e29504d07a?

**Comment by rix0rrr** [comment]
I think so.
