### ISSUE TITLE
Use CloudformationTemplate section out of date. Still uses old api.

### ISSUE THREAD

**Issue by aneeshgarg** [aws/aws-cdk#3368]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [X] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/aws/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

https://docs.aws.amazon.com/cdk/latest/guide/use_cfn_template.html

**Comment by Jerry-AWS** [comment]
@aneeshgarg Thanks for submitting this! I've added it as a bug against the AWS CDK Developer Guide. https://github.com/awsdocs/aws-cdk-guide/issues/96
