### ISSUE TITLE
Construct ScheduledFargateTask lacks access to IGrantable

### ISSUE THREAD

**Issue by Pwntus** [aws/aws-cdk#3371]
* **I'm submitting a ...**
  - [ ] :beetle: bug report
  - [ ] :rocket: feature request
  - [X] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/aws/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
``` ts
const table = new dynamodb.Table( ... );
const task = new ScheduledFargateTask( ... );

// IGrantable not present on any accessible properties
table.grantReadWriteData(task);
```

* **What is the expected behavior (or behavior of feature suggested)?**
You should be able to grant IAM principal (`ScheduledFargateTask`) to read/write/etc on a DynamoDB table. Suggested fix is to make `taskDefinition` a `public readonly` property on the construct: https://github.com/aws/aws-cdk/blob/v1.1.0/packages/@aws-cdk/aws-ecs-patterns/lib/fargate/scheduled-fargate-task.ts#L43

```ts
const table = new dynamodb.Table( ... );
const task = new ScheduledFargateTask( ... );

// Works, if suggested fix is implemented
table.grantReadWriteData(task.taskDefinition.taskRole);
```

* **What is the motivation / use case for changing the behavior or adding this feature?**
Run containers on ECS Fargate which can interact with the AWS API using IAM policies.

* **Please tell us about your environment:**

  - CDK CLI Version: 1.1.0 (build 1a11e96)
  - OS: Ubuntu
  - Language: TypeScript

**Comment by pkandasamy91** [comment]
Resolved as part of https://github.com/aws/aws-cdk/pull/3404

**Comment by prabhash-c** [comment]
Hopefully you will be able to help me with this

@Pwntus does this work for you?

@piradeepk this still gives me the same error, no IGrantable on ScheduledFargateTask 

Did the format change or something? 

Thanks for your help!
