### ISSUE TITLE
Question - Lookup one app/stack from another

### ISSUE THREAD

**Issue by lobsterdore** [aws/aws-cdk#3372]
I am using the Python version of the CDK, I have a question about looking up stacks/apps (and whether it's possible or not).

I am creating a few different apps for the various parts of my infra, I would like to create separate apps so I do not need to update foundational components when deploying services, eg. I don't want to deploy the VPC when I deploy a Fargate service.

So far I have three separate apps, one for the VPC, one for the ECS Cluster and one for a Fargate service. To make all this work I need to be able to lookup the VPC stack from both the ECS Cluster and Fargate apps, I will also need to lookup the Cluster app within the Fargate app. Is this currently possible? Or is there a different method for splitting things up?

**Comment by lobsterdore** [comment]
OK I managed to find the from_lookup static method of the vpc class, however when I try perform a lookup using tags like so:

```vpc = aws_ec2.Vpc.from_lookup(self, 'Vpc', tags={"environment": "dev", "project": "cdk-example"})```

I get the following error when I run cdk ls:

```The filter 'environment' is invalid```

Are tag based lookups currently working? I am using version 1.1.0 of the CDK.

**Comment by RomainMuller** [comment]
Hey @lobsterdore - you are correct, we are not correctly emitting filters for the tags when making the EC2 call. Whoops.

If you want this to work right now, you can prefix all tag names with `tag:` until we have fixed the bug in the CLI.

**Comment by lobsterdore** [comment]
@RomainMuller OK no worries at all, I will try the ```tag:```fix.

**Comment by lobsterdore** [comment]
@RomainMuller is there a way to lookup any Cloudfomation stack and examine it's outputs?

**Comment by RomainMuller** [comment]
@lobsterdore we don't have any support for this built-in right now, but it should be fairly straight-forward to make a lambda-backed CustomResource that does just this!
