### ISSUE TITLE
CustomResource applies presumptuous property uppercasing

### ISSUE THREAD

**Issue by briancoit** [aws/aws-cdk#3421]
* **I'm submitting a ...**
  - [ ] :beetle: bug report
  - [x] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/aws/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
https://github.com/aws/aws-cdk/blob/v1.1.0/packages/@aws-cdk/aws-cloudformation/lib/custom-resource.ts#L96

Uppercasing is applied to the first character of a provided parameter name. This seems very opinionated, and is not mirrored by the existing Cloudformation behavior.

* **What is the expected behavior (or behavior of feature suggested)?**
No transformation is applied.

* **What is the motivation / use case for changing the behavior or adding this feature?**
 In our case, we have an existing lambda which accepts some parameters, which are currently lowercase. Migrating to CDK requires an update to the deployed lambda code - which our team does not own. This behavior is not documented outside code (from what I can see), and what has been documented does not seem to serve as any real justification for the transformation.

* **Please tell us about your environment:**

  - CDK CLI Version: 1.1.0
  - Module Version: 1.1.0
  - OS: all
  - Language: TypeScript

**Comment by SomayaB** [comment]
Hi @briancoit, thanks for submitting a feature request! We will look into this and someone will update this issue when there is movement.

**Comment by eladb** [comment]
MUST BE FIXED

**Comment by eladb** [comment]
Since this is a breaking change it will require a feature flag.

**Comment by eladb** [comment]
Resolved in #7736
