### ISSUE TITLE
Escape hatches for modifying resource does not work in python

### ISSUE THREAD

**Issue by lkoniecz** [aws/aws-cdk#3431]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [ ] :beetle: bug report
  - [ ] :rocket: feature request
  - [x] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/aws/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*
According to https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html paragraph 'Modifying the AWS CloudFormation Resource behind AWS Constructs'
```
        loadbalancer = aws_elasticloadbalancing.LoadBalancer(
            # params ommited
        )

        cfn_loadbalancer = loadbalancer.node.default_child
        cfn_loadbalancer.load_balancer_name = 'test'
```
this should change load balancer name to the value provided, but it does not do anything.

* **What is the expected behavior (or behavior of feature suggested)?**

load balancer name changes to test

* **What is the motivation / use case for changing the behavior or adding this feature?**

Fill missing constructs functionality. 

* **Please tell us about your environment:**

  - CDK CLI Version: 1.0.0
  - Module Version: 1.0.0
  - OS: [all ]
  - Language: [Python ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

**Comment by lkoniecz** [comment]
#1595

**Comment by RomainMuller** [comment]
I have confirmed this works with the current version of CDK (`>= 1.18.0`)
