### ISSUE TITLE
Cannot specify existing SecurityGroup for autoscaling.AutoScalingGroup

### ISSUE THREAD

**Issue by alokito** [aws/aws-cdk#3433]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [ ] :beetle: bug report
  - [x ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/aws/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*

Currently the AutoScalingGroup always creates a new SecurityGroup per auto-scaling-group.js:

```
        this.securityGroup = new ec2.SecurityGroup(this, 'InstanceSecurityGroup', {
            vpc: props.vpc,
            allowAllOutbound: props.allowAllOutbound !== false
        });
```

* **What is the expected behavior (or behavior of feature suggested)?**

Ideally we could specify an existing ec2.SecurityGroup that could be used.

* **What is the motivation / use case for changing the behavior or adding this feature?**

Corporate policy forbids ordinary users like myself from creating security groups, so all attempts to use AWS CDK will result in 403 forbidden unless I can use an existing security group.

* **Please tell us about your environment:**

  - CDK CLI Version: 1.1.0 (build 1a11e96)
  - Module Version: aws-autoscaling@1.1.0
  - OS: OSX Mojave
  - Language: TypeScript

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

**Comment by gandroz** [comment]
It would be very convenient indeed. We can add a SG to the autoScalingGroup, but there is still one new "empty" unused SG created.

**Comment by knutster** [comment]
I would actually say this is a bug since the default security group cannot be modified in any way except for declaring that all outgoing connections are permitted.

**Comment by Zirkonium88** [comment]
Addiotnally, the default Security Groups holds outbound rules. This could lead to security issues. 

This SG shold be removed replaced by

```Python
auto_scaling_group.add_security_group(exampl_sg)
```

**Comment by gandroz** [comment]
As stated in the documentation 

> If you are defining new infrastructure in CDK, there is a good chance you won't have to interact with this class at all. Like IAM Roles, Security Groups need to exist to control access between AWS resources, but CDK will automatically generate and populate them with least-privilege permissions for you so you can concentrate on your business logic.
>
> All Constructs that require Security Groups will create one for you if you don't specify one at construction. After construction, you can selectively allow connections to and between constructs via--for example-- the instance.connections object. Think of it as "allowing connections to your instance", rather than "adding ingress rules a security group". See the Allowing Connections section in the library documentation for examples.
>
> Direct manipulation of the Security Group through addIngressRule and addEgressRule is possible, but mutation through the .connections object is recommended.

why recommending the default creation (and mutation) of a default SG at the creation of each construct, why not using an existing SG so that it is easier to update only one SG if rules change ?

**Comment by Zirkonium88** [comment]
If the SG would be really closed from inbound and outbound perspective, I totally aggree. But it's not. There are ICMP outbound rules. Unfortunenately, there seems to be no to overwrite them. That's why .add_security() is a preffered solution from point of view. 

A second point comes up, if you want to adress the Id of the SG. Within the ASG module there seems to be no opportunity to do this. 

Within the EC2 module this  way of overwriting the SG is already implemented, isn't it? And by using .add_security(), I can adress every property of my SG.

**Comment by gandroz** [comment]
This options should have been placed into the `CommonAutoScalingGroupProps` instead of the `AutoScalingGroupProps` because there is still the issue with ECS cluster when adding a capacity. The `AddCapacityOptions` does not support the new `securityGroup` option.

**Comment by tvb** [comment]
> As stated in the documentation
> 
> > If you are defining new infrastructure in CDK, there is a good chance you won't have to interact with this class at all. Like IAM Roles, Security Groups need to exist to control access between AWS resources, but CDK will automatically generate and populate them with least-privilege permissions for you so you can concentrate on your business logic.
> > All Constructs that require Security Groups will create one for you if you don't specify one at construction. After construction, you can selectively allow connections to and between constructs via--for example-- the instance.connections object. Think of it as "allowing connections to your instance", rather than "adding ingress rules a security group". See the Allowing Connections section in the library documentation for examples.
> > Direct manipulation of the Security Group through addIngressRule and addEgressRule is possible, but mutation through the .connections object is recommended.
> 
> why recommending the default creation (and mutation) of a default SG at the creation of each construct, why not using an existing SG so that it is easier to update only one SG if rules change ?

>but CDK will automatically generate and populate them with least-privilege permissions

How is defaulting to "egress allow all" providing least-privilege permissions?
