### ISSUE TITLE
ec2.Vpc.from_lookup does not work when app is deployed in multiple accounts

### ISSUE THREAD

**Issue by mbergkvist** [aws/aws-cdk#3438]
* **I'm submitting a ...**
  - [X] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/aws/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
When the application is configured for multiple account
```python
app = core.App()
MyStack(app, "hello-cdk-n1", env={'region': 'eu-north-1', 'account': '123456789012'})
MyStack(app, "hello-cdk-n2", env={'region': 'eu-north-1', 'account': '210987654321'})
app.synth()
```
and the stack utilizes *aws_ec2.Vpc.from_lookup*
```python
aws_ec2.Vpc.from_lookup(self, "MyVPC", vpc_name="MyVPC")
```
the following
```sh
$ cdk synth hello-cdk-n1 -v --profile profile-for-210987654321
```
will fail with
```
Need to perform AWS calls for account 123456789012, but no credentials found. Tried: default credentials.
```
* **What is the expected behavior (or behavior of feature suggested)?**
Lazy evaluation of *ec2.Vpc.from_lookup* to avoid AWS calls for accounts not matching the current profile.

* **What is the motivation / use case for changing the behavior or adding this feature?**
[The recommendation](https://docs.aws.amazon.com/cdk/latest/guide/getting_started.html#getting_started_credentials_prop) is to explicitly set the account and the region using the *env* property but I don't know how to get that to work while *ec2.Vpc.from_lookup* is eager.

* **Please tell us about your environment:**

  - CDK CLI Version: 1.1.0
  - Python 3.7.3
  - OS: Ubuntu
  - Language: Python

**Comment by mbergkvist** [comment]
This is not exclusively for *ec2.Vpc.from_lookup*, you will get the same behaviour with
```sh
cdk bootstrap --profile profile-for-210987654321
```

**Comment by Console32** [comment]
calling vpc.fromVpcAttributes causes the same error, even cdk list fails: 
The problem is aws is trying too lookup the azs. You can work around this issue by adding the azs to the cdk.context.json file manually

```
{
  "availability-zones:account=655307789548:region=eu-central-1": [
    "eu-central-1a",
    "eu-central-1b",
    "eu-central-1c"
  ],
  "availability-zones:account=132189485739:region=eu-west-1": [
    "eu-central-1a",
    "eu-central-1b",
    "eu-central-1c"
  ]
}
```

I do not have any permissions for the account 132189485739 on my machine, after adding the azs to the context file everything works again.

If this does not fix your problem you can try to add -v to the cdk call to get some detailed logs

**Comment by mbergkvist** [comment]
Thanks! This fixed my problem.

I wasn't aware of the `cdk.context.json` file. Now, if there were only a way to populate this file from the AWS CDK CLI...

**Comment by ralph-tice** [comment]
Having run into this same problem two years later, I think it is worth making an addition to the documentation for this quirk as it relates to multiple account setups.
