### ISSUE TITLE
How can I have stable CfnOutput parameter names for CDK's internally created outputs?

### ISSUE THREAD

**Issue by jderose9** [aws/aws-cdk#3439]
* **I'm submitting a ...**
  - [ ] :beetle: bug report
  - [X ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/aws/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
Generated values in stack Output keys

* **What is the expected behavior (or behavior of feature suggested)?**
Stable/Predictable keys in the stack output

* **What is the motivation / use case for changing the behavior or adding this feature?**
A number of the resources generate stack outputs automatically. For example, api gateway outputs the endpoint URL, and dynamo outputs the table name.

I tend to query the stack for output variables with the CLI when doing deployment tasks. For example, maybe my stack generates a db table and I want to run a script to populate that table as an automated next step. Or I want to feed the generated API endpoint into a later web app build.

The problem is that I end up with output key names such as `MyApiEndpoint288BD6BB` or `ExportsOutputRefMyTable75718D3D178CFBFC`. How can I override these values to something predictable? (The constructs in question have been assigned physical names in their props)

**Comment by eladb** [comment]
It should be possible to specify the `outputName` when a `CfnOutput` is defined to allow people to override the default behavior which generates a unique name based the construct path. Note that this can cause conflicts if multiple outputs within the same tree will provide an explicit name, similarly to any physical name I guess.

**Comment by jderose9** [comment]
@eladb I'm not sure why this was closed? My concern wasn't around specifying an outputName but rather that many of the CfnOutput objects are automatically generated and I don't have a way to assign that property.

**Comment by orzikhd** [comment]
@eladb @jderose9 was there any further resolution to this issue? Any good work-around? 

To me it seems like the only way to do this is to manually define `CfnOutput` and use `Fn.importValue`

**Comment by make-ing** [comment]
@eladb @jderose9 Is there any solution to this problem? We are struggling our-self with this at the moment.

@orzikhd Can you explain your solution a little more in-depth? I would like to get this to work.
