### ISSUE TITLE
CodeBuildAction requires an input even though it's optional in Cfn

### ISSUE THREAD

**Issue by mb-dev** [aws/aws-cdk#3441]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [X] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/aws/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*

CodeBuildAction requires an input artifact to be given: https://github.com/aws/aws-cdk/blob/921dcc9f9f569331467a924ca4d849e501a3a557/packages/%40aws-cdk/aws-codepipeline-actions/lib/codebuild/build-action.ts#L32

* **What is the expected behavior (or behavior of feature suggested)?**

Input should be optional similar to how it is in cloudformation:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codepipeline-pipeline-stages-actions.html#cfn-codepipeline-pipeline-stages-actions-inputartifacts

* **What is the motivation / use case for changing the behavior or adding this feature?**

I am creating a codepipeline where the source is checked out manually from github enterprise in a CodeBuild action. So CodeBuild has no inputs.

* **Please tell us about your environment:**

  - CDK CLI Version: 1.1.0
  - Module Version: 1.1.0
  - OS: all
  - Language: all

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

**Comment by skinny85** [comment]
Hey @mb-dev ,

thanks for opening the issue. In fact, input is *not* optional for CodeBuild Actions (if you left it our of  your CloudFormation-defined Pipeline, you would get a failure at deploy time). Here's an excerpt from the [CodePipeline structure reference](https://docs.aws.amazon.com/codepipeline/latest/userguide/reference-pipeline-structure.html):

Owner | Type of Action | Provider | Valid Number of Input Artifacts | Valid Number of Output Artifacts
-- | -- | -- | -- | --
AWS | Build | CodeBuild | 1 to 5 | 0 to 5
AWS | Test | CodeBuild | 1 to 5 | 0 to 5

**Comment by mb-dev** [comment]
Oops, thanks for clarifying. I under estimated the limitations of code pipeline.
