### ISSUE TITLE
ec2.Vpc.from_lookup fails to recognise any private subnets

### ISSUE THREAD

**Issue by reeseyc** [aws/aws-cdk#3442]
I'm submitting a :beetle: bug report

What is the current behavior?

When utilising an exisiting VPC to deploy, ec2.Vpc.from_lookup will fail to recognise any subnets other than the public subnets. 
Any further attempt to deploy components to a Private subnet (through choice or design) will therefore fail

For instance:

eks cluster will not create as no private subnet 
ecs cluster will not create as no private subnet
autoscaling group with subnet type set to private will not create

What is the expected behavior (or behavior of feature suggested)?
Private subnets should be detected by ec2.Vpc.from_lookup

 OS: Windows 10
# cdk --version
1.1.0 (build 1a11e96)

# python --version
Python 3.7.4

**Comment by rix0rrr** [comment]
Can you run [`describe-vpcs`](https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-vpcs.html), [`describe-subnets`](https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-subnets.html) and [`describe-route-tables`](https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-route-tables.html) on your VPC and post the results here?

Can you show the snippet you are using to import your VPC?

**Comment by reeseyc** [comment]
@rix0rrr 
apologies i should have closed this.  This is the same issue as #3706 
the issue is cause by the fact that the subnets need to be tagged for VPCfromlookup to work; if you created the vpc outside of CDK then you need to add subnet tagging
I feel this is a documentation issue and should be clarified in the API reference that VPCfromSubnet requires these values to work
