### ISSUE TITLE
Elastic Loadbalancer exposes security group name instead of id

### ISSUE THREAD

**Issue by lkoniecz** [aws/aws-cdk#3443]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [ ] :beetle: bug report
  - [ ] :rocket: feature request
  - [x] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/aws/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*
https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_elasticloadbalancing/LoadBalancer.html

Since classic Loadbalancer constructor is missing secuirty group paramerter I tried to grab its security group via load_balancer_source_security_group_group_name. Unfortunately it's useless as https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_ec2/SecurityGroup.html#aws_cdk.aws_ec2.SecurityGroup.from_security_group_idfrom* factory method expects id rather name name.
The load_balancer_source_security_group_group_name is a token rather than a resolved name I cannot use it with SDK.

* **What is the expected behavior (or behavior of feature suggested)?**
Add a possibility to access loadbalancer security group id.

* **What is the motivation / use case for changing the behavior or adding this feature?**
I have a few lambdas in other stack. In order to shorten execution time I am passing load balancer sg id (along with a few other resources) as an env variable instead of calling describe* API in the lambda code.
Elegant way would be to pass load balancer object from one stack to the other - without it I have to grab the id with SDK before synthesize. 
What makes things worse that I cannot rely on logical ids as they are some random strings.

* **Please tell us about your environment:**

  - CDK CLI Version: 1.0.0
  - Module Version: 1.0.0
  - OS: [all]
  - Language: [all]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

**Comment by rix0rrr** [comment]
You can go a couple of different ways about this.

You can use the [escape hatch](https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html) mechanism to access the [Security Group child](https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-elasticloadbalancing/lib/load-balancer.ts#L236).

Alternatively, you can go through the `connections` object and get the SG from [its `securityGroups` member](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ec2.Connections.html#securitygroups):

```
sg = load_balancer.connections.security_groups[0]
sg.security_group_id
```

**Comment by rix0rrr** [comment]
You shouldn't need to work with security group ids directly. Passing the load balancer around will work.
