### ISSUE TITLE
Proposal: Use a code formater

### ISSUE THREAD

**Issue by nmussy** [aws/aws-cdk#3444]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [ ] :beetle: bug report
  - [x] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/aws/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*
TSLint is currently being used as a code style enforcer, with the following rules:
    * ✨ [`align`](https://palantir.github.io/tslint/rules/align)
    * [`comment-format`](https://palantir.github.io/tslint/rules/comment-format)
    * [`curly`](https://palantir.github.io/tslint/rules/curly)
    * ✨ [`import-spacing`](https://palantir.github.io/tslint/rules/import-spacing)
    * [`indent`](https://palantir.github.io/tslint/rules/indent)
    * [`jsdoc-format`](https://palantir.github.io/tslint/rules/jsdoc-format)
    * [`no-consecutive-blank-lines`](https://palantir.github.io/tslint/rules/no-consecutive-blank-lines)
    * ✨ [`one-line`](https://palantir.github.io/tslint/rules/one-line)
    * ✨ [`only-arrow-functions`](https://palantir.github.io/tslint/rules/only-arrow-functions)
    * [`space-before-function-paren`](https://palantir.github.io/tslint/rules/space-before-function-paren)
    * [`typedef-whitespace`](https://palantir.github.io/tslint/rules/typedef-whitespace)
    * ✨ [`whitespace`](https://palantir.github.io/tslint/rules/whitespace)
    * [`no-trailing-whitespace`](https://palantir.github.io/tslint/rules/no-trailing-whitespace)
I am currently making a PR (#3430) to replace the soon to be deprecated TSLint with ESLint. Some of the rules listed above, marked with a ✨, are not made available by ESLint. 

* **What is the expected behavior (or behavior of feature suggested)?**
Integrate a code formater (Prettier) in the development flow

* **What is the motivation / use case for changing the behavior or adding this feature?**

**⚠️ Please feel free to help me extend this list ⚠️**

### Pros
  * 👍 Prettier is very popular, and [well covered (94%)](https://codecov.io/gh/prettier/prettier)
  * 👍 It is recommended by the [TSLint team as a code formater](/palantir/tslint/issues/4534#issue-413722441), instead of the rules listed above
### Cons
  * 👎  Contributor overhead (can be alleviated with tool like [lint-staged](/okonet/lint-staged))

* **Please tell us about your environment:**

  - CDK CLI Version: 1.1.0
  - Module Version: 1.1.0
  - OS: all
  - Language: all

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

**Comment by eladb** [comment]
I am going to close this for now.
