### ISSUE TITLE
Storage Gateway is missing from the list of VPC Endpoint services.

### ISSUE THREAD

**Issue by vaneek** [aws/aws-cdk#3446]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [ ] :beetle: bug report
  - [ ] :rocket: feature request
  - [X] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/aws/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*

Storage Gateway is missing from the list of VPC Endpoint services.

* **What is the expected behavior (or behavior of feature suggested)?**

* **What is the motivation / use case for changing the behavior or adding this feature?**

* **Please tell us about your environment:**

  - CDK CLI Version: xx.xx.xx
  - Module Version: xx.xx.xx
  - OS: [all | Windows 10 | OSX Mojave | Ubuntu | etc... ]
  - Language: [all | TypeScript | Java | Python ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

**Comment by jogold** [comment]
As a workaround until it's implemented you can do:
```ts
// Add an storage gateway interface endpoint
const storageGatewayEndpoint = vpc.addInterfaceEndpoint('StorageGatewayEndpoint', {
  service: new InterfaceVpcEndpointAwsService('storagegateway')
});
```
