### ISSUE TITLE
aws-cloudtrail.addS3EventSelector generates faulty cfn code

### ISSUE THREAD

**Issue by jonny-rimek** [aws/aws-cdk#3450]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/aws/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*

`cdk init app --language=typescript`

add these 3 lines 

	const uploadBucket = new s3.Bucket(this, 'UploadBucket')
	const trail = new ct.Trail(this, 'StepfunctionTrail')
	trail.addS3EventSelector([uploadBucket.bucketArn])                                                                                                 

run `cdk deploy`

**ERROR MESSAGE:**

```
Value arn:aws:s3:::<replaced> for DataResources.Values is invalid. 
(Service: AWSCloudTrail; Status Code: 400; Error Code: InvalidEventSelectorsException; 
Request ID: ...
```

* **What is the expected behavior (or behavior of feature suggested)?**

The cfn should run.

* **What is the motivation / use case for changing the behavior or adding this feature?**

* **Please tell us about your environment:**

  - CDK CLI Version: 1.2
  - OS: w10
  - Language: TypeScript

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

This is the cfn I get [SffStack.template.txt](https://github.com/aws/aws-cdk/files/3436593/SffStack.template.txt)

I wanted to created a stepfunction, to be triggered on s3 upload, so I wanted to add cloudtrail on the writes of that bucket and create a CloudWacht Event for PutObject calls, unfortunately I failed right at the start^^.

I got this far by clicking around in the console tho.

**Comment by jimbo5644535** [comment]
the issue still exists, same error message
