### ISSUE TITLE
hidden characters in doc causing problem for copy/paste

### ISSUE THREAD

**Issue by 0xdabbad00** [aws/aws-cdk#3452]
On https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ec2.Vpc.html the value `max­Azs` is being written as `max&shy;Azs` so it copy/pastes poorly, specifically on VS Code that retains characters like that apparently, so you end up with an invisible character and your code doesn't work.

Inspecting with Chrome shows the issue:
<img width="413" alt="Screen Shot 2019-07-26 at 3 35 32 PM" src="https://user-images.githubusercontent.com/1979334/61984080-1f95bf80-afc0-11e9-87ab-75e80e8e373c.png">

This is how it looks when you copy paste it, because it is being pasted as `max-Azs`:
<img width="230" alt="Screen Shot 2019-07-26 at 3 36 44 PM" src="https://user-images.githubusercontent.com/1979334/61984097-2de3db80-afc0-11e9-8ea3-153e6b9f4b57.png">

I don't know if this issue exists elsewhere in the docs.  

The change I would like to have happen is to make it possible to copy/paste that variable from the docs without an invisible character ending up in it.

**Comment by rix0rrr** [comment]
That is my bad. We are doing this to make long identifiers wrap naturally when the screen size gets narrow, or for very long columns.

I will investigate another way achieving this. Replacing soft hyphens with a `<wbr>` tag might be sufficient.

**Comment by aripalo** [comment]
Same happened to me in https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.SecretsManagerSecretOptions.html#properties

Took a while to understand what's actually going on here:
![Screenshot 2019-08-14 at 22 22 13](https://user-images.githubusercontent.com/679146/63049739-0b1f5580-bee2-11e9-8cf1-2cd59c5757c2.png)

Turns out there is a zero-width space character between `json` and `Field`.

This is what it looks like in Firefox:
![Screenshot 2019-08-14 at 22 24 13](https://user-images.githubusercontent.com/679146/63049825-4883e300-bee2-11e9-894f-d9df58a42012.png)

**Comment by 0xdabbad00** [comment]
@rix0rrr It doesn't look like this issue has been resolved if I look at https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ec2.Vpc.html . Have the docs not been updated to reflect the change?

**Comment by 0xdabbad00** [comment]
@rix0rrr Looks like the docs are updated now to using a `<wbr>` element, which seems to have resolved my previous issue, but now is causing those characters to show up in the text in some places.  For example on https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-iam.PolicyStatement.html you can see the in the "Initializer" section the text `new Policy<wbr>Statement` as shown in the screenshot below.

<img width="655" alt="Screen Shot 2019-08-23 at 7 27 45 PM" src="https://user-images.githubusercontent.com/1979334/63630827-47d30700-c5dc-11e9-9420-bbdca6207d47.png">

**Comment by 0xdabbad00** [comment]
My preference would be for the docs to not care about word breaks.  You can see here an example where the string `ConstructNode` breaks awkwardly currently, and that is totally fine.  I'd much rather have the docs appear like this than have these hidden character tricks that are happening currently. https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-s3.BucketPolicy.html

<img width="256" alt="Screen Shot 2019-08-24 at 8 13 23 AM" src="https://user-images.githubusercontent.com/1979334/63638553-12173800-c647-11e9-9f33-4614e5966899.png">
