### ISSUE TITLE
PassProp Should accept parameters just like StateProp.

### ISSUE THREAD

**Issue by nikamipara** [aws/aws-cdk#3453]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [ ] :beetle: bug report

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*

Pass State Props currently does not support adding parameters  : https://github.com/aws/aws-cdk/blob/97b1168db536f013fa0db50257608d2413d61293/packages/%40aws-cdk/aws-stepfunctions/lib/states/pass.ts#L53

* **What is the expected behavior (or behavior of feature suggested)?**

It should accept parameters just like State.

https://github.com/aws/aws-cdk/blob/97b1168db536f013fa0db50257608d2413d61293/packages/%40aws-cdk/aws-stepfunctions/lib/states/state.ts#L35

* **What is the motivation / use case for changing the behavior or adding this feature?**

parameters gives more freedom to mainipulate json input.

https://docs.aws.amazon.com/step-functions/latest/dg/input-output-inputpath-params.html

* **Please tell us about your environment:**

  - CDK CLI Version: xx.xx.xx
  - Module Version: xx.xx.xx
  - OS: [all | Windows 10 | OSX Mojave | Ubuntu | etc... ]
  - Language: [all | TypeScript | Java | Python ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

**Comment by rbs392** [comment]
Hi @rix0rrr 
Any updates on when this will be implemented??

**Comment by rix0rrr** [comment]
We are not focusing on StepFunctions right now. Would be happy to accept PRs though.

**Comment by alukach** [comment]
> PassProp Should accept parameters just like StateProp.

I believe this that TaskProps should also accept `parameters`.

**Comment by sinistral** [comment]
This appears to be related to https://github.com/aws/aws-cdk/issues/1480, which includes a [patch](https://github.com/aws/aws-cdk/issues/1480#issuecomment-451498961) that might be [adapted](https://gist.github.com/sinistral/51e5188bd885b43c4aabddc1973a368f) for use with Pass.
