### ISSUE TITLE
Support for GeoRestrictions in CloudFrontWebDistribution

### ISSUE THREAD

**Issue by schof** [aws/aws-cdk#3456]
* **I'm submitting a ...**
  - [ ] :beetle: bug report
  - [x] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/aws/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
Currently there is no way to add GeoRestriction even though this is supported in Cloud Formation.

* **What is the expected behavior (or behavior of feature suggested)?**
I was expecting a `Restrictions` property that allowed a single property of `GeoRestriction` which can then be used to blacklist/whitelist countries.

* **What is the motivation / use case for changing the behavior or adding this feature?**
Getting this construct closer to 100% of Cloud Formation supported functionality

**Comment by NGL321** [comment]
Hi @schof,

Thank you for reporting this! Since it is in the Cloudformation Resource Specification and therefore should have automatically been generated, I am marking this as an issue with the L1 construct.

Someone will make a note here when we are able to address the issue.
Let us know if you find anything else!

**Comment by rbright** [comment]
Are there any updates on the addition of this functionality?

**Comment by iliapolo** [comment]
Hi @rbright @schof 

As there are quite a bit of issues accumulating around this package, we are considering our course of action here. We will update our intent for this feature soon. 

Thanks for the patience

**Comment by rbright** [comment]
@iliapolo Thanks for the update!

**Comment by bminahan73** [comment]
+1

**Comment by mina-asham** [comment]
@iliapolo Are you open for PR contributions here? Seems easy enough to support and I can help!

**Comment by iliapolo** [comment]
Hi @mina-asham Yes this definitely seems straight-forward enough. Your contribution would be greatly appreciated :)

**Comment by mina-asham** [comment]
@iliapolo any updates here?

**Comment by iliapolo** [comment]
Hi @mina-asham 

Thanks for the PR! And sorry for the delay...

I plan to start reviewing it this week.

Stay tuned :)
