### ISSUE TITLE
python jsii resolve error CfnSecurityGroupIngress

### ISSUE THREAD

**Issue by daveschmidt86** [aws/aws-cdk#3457]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [X] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/aws/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*

This is the code I was using to create a security group with an ingress rule (Cfn)
``` py
web_server_security_group = ec2.CfnSecurityGroup(self, "web_server_sg",
            vpc_id = main_vpc.ref,
            group_name = "WebServerSecurityGroup",
            group_description = "Web server security group for basic http access from internet",
            security_group_ingress = [
                ec2.CfnSecurityGroupIngress(self, "allow_http",
                    ip_protocol = "tcp",
                    cidr_ip = "0.0.0.0/0",
                    from_port = 80,
                    to_port = 80
                )
            ],
            tags = [core.CfnTag(key="Name", value="web_server_security_group")]
        )
```

* **What is the expected behavior (or behavior of feature suggested)?**
This should create a security group and have an ingress policy allowing http traffic port 80 as specified.

* **What is the motivation / use case for changing the behavior or adding this feature?**

* **Please tell us about your environment:**

  - CDK CLI Version: 1.2.0
  - Module Version: xx.xx.xx
  - OS: OSX
  - Language: Python

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

Part of error received:
```
jsii.errors.JSIIError: Resolution error: Resolution error: Trying to resolve() a Construct at /Resources/${Token[test-cdk.web_server_sg.LogicalID.42]}/Properties/securityGroupIngress/0/node.
Object creation stack: [long list of jsii errors]...
Subprocess exited with error 1
```

**Comment by rix0rrr** [comment]
I will admit the Python docs are a bit messy here, but [the generic docs](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ec2.CfnSecurityGroup.html) show that the type of `security_group_ingress` is supposed to be [`CfnSecurityGroup.IngressProperty`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ec2.CfnSecurityGroup.IngressProperty.html) and not `CfnSecurityGroupIngress`.

The docs for [`CfnSecurityGroupIngress`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ec2.CfnSecurityGroupIngress.html) will tell you that it represents an `AWS::EC2::SecurityGroupIngress` resource.

**Comment by russmac** [comment]
Just putting my hand up the py doc on this is incredibly poor as it doesn't mention `CfnSecurityGroup.IngressProperty` once. The advice here seems to be to read the Typescript and the Python doc?

Perhaps it does mention it out of the aws_ec2 reference however the Python doc search is broken and has been for some time.
Grepping the AWS cdk samples repo to see how on earth someone else created an sg resource shows 0 examples, Its all using the patterns or default SG's

I'm not sure reading two languages doc while developing counts as something being "supported", I think while AWS is encouraging customers to adopt this tech with _"Python support"_ the doc really needs improving. Maybe this is the wrong channel to voice my concerns.

**Comment by juanledesma84** [comment]
Hi guys. I still can't solve it for Typescript. Could you help me with this, please? I don't know how to use IngressProperty here

`const albSecurityGroupCfn = new CfnSecurityGroup(this, "albSecurityGroupCfn", {
      vpcId: 'vpc-id',
      groupDescription: appEnv + "-alb-sg",
      securityGroupIngress: [
        new CfnSecurityGroupIngress(this, "SGIngress123", {
          ipProtocol: "tcp",
          fromPort: 443,
          toPort: 443,
          cidrIp: "0.0.0.0/0"//props.securityGroupIngressCidr
        })
      ]
    });`
