### ISSUE TITLE
S3 Deploy Codepipeline Action does not support CacheControl /  CannedACL

### ISSUE THREAD

**Issue by rvdwijngaard** [aws/aws-cdk#3462]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [ ] :beetle: bug report
  - [ ] :rocket: feature request
  - [x] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/aws/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
```
    const webDeployAction = new actions.S3DeployAction({      
      actionName: "webapp-deploy", bucket: app.bucket, extract: true, input: webBuildAction.outputArtifact, runOrder: 2
    });  
```

see https://docs.aws.amazon.com/codepipeline/latest/userguide/reference-pipeline-structure.html#actions-valid-providers

* **What is the expected behavior (or behavior of feature suggested)?**
```
    const webDeployAction = new actions.S3DeployAction({      
      actionName: "webapp-deploy", bucket: app.bucket, extract: true, input: webBuildAction.outputArtifact, runOrder: 2, cannedAcl: PUBLIC_READ, cacheControl: 'max-age=300'
    });  
```

* **What is the motivation / use case for changing the behavior or adding this feature?**
I want to use s3 deploy action to deploy artifacts to a public website. 

* **Please tell us about your environment:**

  - CDK CLI Version: 1.2.0
  - Module Version: xx.xx.xx
  - OS:all 
  - Language: TypeScript

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

**Comment by nmussy** [comment]
This seems pretty straightforward, I can make a PR tonight.

**Comment by skinny85** [comment]
If you could open a PR, that would be awesome @nmussy 😊
