### ISSUE TITLE
STS configurability for Route53 dependent actions

### ISSUE THREAD

**Issue by PhilKershaw** [aws/aws-cdk#3470]
* **I'm submitting a ...**
  - [ ] :beetle: bug report
  - [x] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/aws/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**

From a Control Tower managed estate, attempting to create a DNS Validated ACM Certificate using:
```javascript
new cert.DnsValidatedCertificate(this, 'certId', {
    domainName: 'example.com',
    hostedZone: hostedZone,
    region: this.region
})
```
Amongst other things, a role is assumed in order to Upsert DNS records to Route53. This fails with an access error:

```
Caught error AccessDenied: User: arn:aws:sts::[accountId]:assumed-role/[role name] is not authorized to access this resource. Uploading FAILED message to S3.
```

This is due to the Hosted Zone residing within the `master` account whilst attempting to deploy to a separate `production` account.

Note, custom policies/roles manually added to IAM and an `STS` policy added to the SSO Permission Set have been added to no avail.

* **What is the expected behavior (or behavior of feature suggested)?**

Allowing the attachment of custom policies to the built-in assumed role or allowing over-riding of said role.

* **What is the motivation / use case for changing the behaviour or adding this feature?**

Use case: As mentioned above, we manage the AWS estate with AWS Control Tower and have separate accounts for different business functions. DNS management happens to be in the `management` account but we'd need to enable access from other accounts in order to manage DNS records as public facing stacks need.

* **Please tell us about your environment:**

  - CDK CLI Version: 1.2.0
  - Module Version: 1.2.0
  - OS: OSX Mojave
  - Language: JavaScript

**Comment by sachin10101998** [comment]
+1 . The role should be allowed to be overridden.

**Comment by TheRealAmazonKendra** [comment]
We are deprecating `DnsValidatedCertificate`. If you experience this issue in another context, please open a new issue.

**Comment by TheRealAmazonKendra** [comment]
For reference: https://github.com/aws/aws-cdk/pull/21982
