### ISSUE TITLE
Cross stack references are not identified in stack.toJsonString()

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#3474]
* **I'm submitting a ...**
  - [x] :beetle: bug report

* **What is the current behavior?**

When using `stack.toJsonString` to stringify an object that includes references to resources in a different stack within the same region, these references (GetAtt/Ref) are not converted to exports/imports.

* **What is the expected behavior (or behavior of feature suggested)?**

Since these are cross stack references, we expect them to be identified as such and converted to exports/imports.

**Comment by jogold** [comment]
Related to #3412?
