### ISSUE TITLE
iam.PolicyDocument.toJSON() does not return valid JSON object

### ISSUE THREAD

**Issue by dz902** [aws/aws-cdk#3477]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/aws/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*

Create a new `iam.PolicyDocument`, add some values, then something like the following will be produced:

`{
  Action: [
    'es:DescribeElasticsearchDomain',
    'es:DescribeElasticsearchDomains',
    'es:DescribeElasticsearchDomainConfig',
    'es:ESHttpPost',
    'es:ESHttpPut',
    'es:ESHttpGet'
  ],
  Effect: 'Allow',
  Principal: { AWS: 'xxx' },
  Resource: 'xxx'
}`

* **What is the expected behavior (or behavior of feature suggested)?**

JSON keys and values should be contained in double quotes.

* **What is the motivation / use case for changing the behavior or adding this feature?**

I'd like to use higher level APIs to generate resource-based policies (when there is not an official policies construct in the resource), but there is currently no good way to do this. 

`toJSON()` is the last rescue, ugly, needs to use `JSON.parse()` to get a valid value, but unfortunately even this does not work, as `toJSON()` does not return valid JSON objects.

* **Please tell us about your environment:**

  - CDK CLI Version: 1.2.0
  - Module Version: 1.2.0
  - OS: all
  - Language: TypeScript

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

**Comment by rix0rrr** [comment]
Can you please provide a minimal reproducing example that shows the issue? I'm not sure I understand what's going on.

**Comment by rix0rrr** [comment]
I'm going to close this issue to keep our queue manageable. 

Feel free to reopen this issue when you have a reproducing code sample that shows the issue. Specifically, I'm not clear where you're getting the "something like this is produced" value.
