### ISSUE TITLE
AutoScalingGroup does not have default_child set

### ISSUE THREAD

**Issue by lkoniecz** [aws/aws-cdk#3478]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/aws/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*

```
asg = aws_autoscaling.AutoScalingGroup(
    scope=self,
    id='asg',
    instance_type=aws_ec2.InstanceType(instance_type),
    key_name='key'
    vpc=vpc,
    machine_image=aws_eks.EksOptimizedAmi(),
    desired_capacity=5
)

 asg.node.default_child.override_logical_id('MyNewId')
```

```
Traceback (most recent call last):
...
    asg.node.default_child.override_logical_id('MyNewId')
AttributeError: 'NoneType' object has no attribute 'override_logical_id'

```
* **What is the expected behavior (or behavior of feature suggested)?**
It is possible to override logical id of the autoscaling group

* **What is the motivation / use case for changing the behavior or adding this feature?**
Make https://github.com/aws/aws-cdk/issues/207 fully working for every construct.

* **Please tell us about your environment:**

  - CDK CLI Version: 1.0.0
  - Module Version: 1.0.0
  - OS: [all]
  - Language: [Python ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

**Comment by lkoniecz** [comment]
Subnet construct (https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_ec2/Subnet.html) has the same problem, where it's corresponding Cfn resource is not available thru default_child - its named 'Subnet' instead of 'Resource'

**Comment by drakir** [comment]
@rix0rrr I cannot see this working for an imported subnet (originated from Vpc.fromLookup). Checking the ImportedSubnet class it seems this class doesn't have the defaultChild property set.
