### ISSUE TITLE
Downloadable API docs

### ISSUE THREAD

**Issue by dz902** [aws/aws-cdk#3479]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [ ] :beetle: bug report
  - [x] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/aws/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

A lot of docs-reading is needed to make CDK work as lots of features are not ready. Now we only have online access to the docs which is really painfully slow, and not integrate-able into dev workflows like Dash. 

Please put the docs in the repo or in a dedicated repo so offline access is possible. Thanks!

**Comment by eladb** [comment]
Are you referring to the [developer guide](https://docs.aws.amazon.com/cdk/latest/guide/home.html)? It is available on [PDF](https://docs.aws.amazon.com/cdk/latest/guide/awscdk.pdf) and even for [Kindle](http://www.amazon.com/dp/B07S97HM34).

Links are available at the top bar:

![Screen Shot 2019-07-30 at 2 07 42 PM](https://user-images.githubusercontent.com/598796/62124654-6ee73300-b2d3-11e9-9efd-3cc570c4aad0.png)

**Comment by dz902** [comment]
> Are you referring to the [developer guide](https://docs.aws.amazon.com/cdk/latest/guide/home.html)? It is available on [PDF](https://docs.aws.amazon.com/cdk/latest/guide/awscdk.pdf) and even for [Kindle](http://www.amazon.com/dp/B07S97HM34).
> 
> Links are available at the top bar:
> 
> ![Screen Shot 2019-07-30 at 2 07 42 PM](https://user-images.githubusercontent.com/598796/62124654-6ee73300-b2d3-11e9-9efd-3cc570c4aad0.png)

No, I'm looking for API documents: https://docs.aws.amazon.com/cdk/api/latest/versions.html
