### ISSUE TITLE
CDK is not using the profile mentioned

### ISSUE THREAD

**Issue by ganku007** [aws/aws-cdk#3482]
**Error**: Unable to resolve AWS account to use. It must be either configured when you define your CDK or through the environment

**Commands**: 
1) cdk deploy --profile dev
2) cdk diff --profile dev

**Stack**: Stack provided in the sample.
``` ts
import sns = require('@aws-cdk/aws-sns');
import subs = require('@aws-cdk/aws-sns-subscriptions');
import sqs = require('@aws-cdk/aws-sqs');
import cdk = require('@aws-cdk/core');

export class CdkStack extends cdk.Stack {
  constructor(scope: cdk.App, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const queue = new sqs.Queue(this, 'CdkQueue', {
      visibilityTimeout: cdk.Duration.seconds(300)
    });

    const topic = new sns.Topic(this, 'CdkTopic');

    topic.addSubscription(new subs.SqsSubscription(queue));
  }
}
```

**Comment by minhlongdo** [comment]
I ran into this issue as well and solved it by adding a region to my profile.
Does your aws profile have a default region attached to it?

**Comment by NGL321** [comment]
Hi @ganku007!

Have you checked that your AWS Cli is properly configured?
[Here](https://cdkworkshop.com/15-prerequisites/200-account.html) is a walkthrough if you are unsure.

Otherwise @minhlongdo's suggestion is a good starting point.
If neither of those things work, try uninstalling the cdk and reinstalling again.

Your best bet for quick live help would be our [Gitter](https://gitter.im/aws-cdk) chat!

**Comment by ganku007** [comment]
> I ran into this issue as well and solved it by adding a region to my profile.
> Does your aws profile have a default region attached to it?

Yes.  I have configured region attached to my profile.  My account is configured through a role and MFA with it

**Comment by NGL321** [comment]
At this point, without more information on your configuration, your best bet it to uninstall the cdk and aws cli and then reinstall.
As indicated in our issue template, we try to keep the issue queue clear for bugs and feature requests, so I'm going to close this issue, and will follow up more through our guidance platforms.
