### ISSUE TITLE
Add command to CDK CLI to popoulate cdk.context.json

### ISSUE THREAD

**Issue by mbergkvist** [aws/aws-cdk#3488]
* **I'm submitting a ...**
  - [ ] :beetle: bug report
  - [X] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/aws/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
The `cdk.context.json` is only populated when synthesizing the templates. This is a problem if the stack is to be deployed in multiple accounts. See #3438.

* **What is the expected behavior (or behavior of feature suggested)?**
It is possible to populate `cdk.context.json` with the AWS CDK CLI.

* **What is the motivation / use case for changing the behavior or adding this feature?**
It would be a convenient way to populate the `cdk.context.json` when the CDK application is to be deployed in multiple accounts.

* **Please tell us about your environment:**

  - CDK CLI Version: 1.2.0

**Comment by indrora** [comment]
Closing (CDKv1). If this is a feature that you'd like to see in CDKv2, please open a new ticket.
