### ISSUE TITLE
apigateway: change default endpoint type to EDGE

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#3494]
It seems odd that the default endpoint type is REGIONAL. It seems that most users that are making a public API with custom domain name would benefit from choosing EDGE instead, which is the default selection when using the console.

_Originally posted by @jderose9 in https://github.com/aws/aws-cdk/issues/3103#issuecomment-516932459_

**Comment by TheRealAmazonKendra** [comment]
This would be a breaking change. We currently do not have any plans to implement this change so we're closing this issue.
