### ISSUE TITLE
logs: extract metric filters from unstructured logs

### ISSUE THREAD

**Issue by chelma-amzn** [aws/aws-cdk#3495]
A common customer use case is to trigger a CloudWatch Alarm based upon application logs entries (e.g. `FATAL`).  Currently, customers that want to set up such an Alarm need to define four Constructs.  The nature of the use is dictates that customers will typically want to define many of these groupings (e.g. `ERROR` and `FATAL`), leading to every customer with this use case making creating their own abstraction around it (or just copy/pasting the resources).

Consider the following code to define a single CloudWatch Alarm that fires based upon a log entry:

```js
import cloudwatch = require('@aws-cdk/aws-cloudwatch');
import logs = require("@aws-cdk/aws-logs");


const metricLogsWARN = new cloudwatch.Metric({
    metricName: "WarnCount",
    namespace: "Namespace",
    period: core.Duration.seconds(60),
    statistic: "sum"
});
new logs.MetricFilter(this, "FilterLogsWARN", {
    logGroup: logGroup,
    metricNamespace: "Namespace",
    metricName: metricLogsWARN.metricName,
    filterPattern: logs.FilterPattern.literal("[WARN]"),
    metricValue: "1"
});
new logs.MetricFilter(this, "FilterLogsWARNMatchAll", {
    logGroup: logGroup,
    metricNamespace: "Namespace",
    metricName: metricLogsWARN.metricName,
    filterPattern: logs.FilterPattern.literal(""),
    metricValue: "0"
});
new cloudwatch.Alarm(this, "AlarmLogsWARN", {
    metric: metricLogsWARN,
    threshold: 1,
    evaluationPeriods: 1,
});
```

**Comment by eladb** [comment]
Is [`logGroup.extractMetric`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-logs.LogGroup.html#extract-metricjsonfield-metricnamespace-metricname) what you are after?

**Comment by chelma-amzn** [comment]
A customer use case could look like this:

"As a service owner, I want to be notified when my application is logging FATAL exceptions"

What this looks like in practice as a service owner is that you want a CloudWatch Alarm to transition from "OK" to "ALARM", as it gives you powerful abilities to perform automated actions based upon that transition (e.g. fire Lambda X or notify the team).  CloudWatch Alarms are the thing that converts Metrics into actions, if that makes sense.

With that in mind, [logGroup.extractMetric](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-logs.LogGroup.html#extract-metricjsonfield-metricnamespace-metricname) would gives us the metrics we need, but would not provide the Alarm that watches them and takes useful action.  Additionally, that API  seems to be targeted [at JSON-formatted logs only](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/FilterAndPatternSyntax.html) instead of arbitrary application logs, which may be in any or no format.  

I'd love for us to support both folks that made the investment to dump all their logs to CloudWatch Logs in a JSON format and those that haven't (which I'm assuming are the majority).

**Comment by eladb** [comment]
`extractMetric` returns a [`Metric`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cloudwatch.Metric.html#class-metric) object which has a [`createAlarm`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cloudwatch.Metric.html#create-alarmscope-id-props) method.

**Comment by chelma-amzn** [comment]
Cool, so that would definitely work for the customers who submit their logs in the structured, JSON format that `extractMetric()` expects.  However, as I mentioned before, I don't think most of our customers submit logs in that format.  The question is, what would be the plan for those customers?  

It sounds like the work here is to either expand [the existing extractMetric behavior](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-logs/lib/log-group.ts#L141) to accept [the FilterPattern as a parameter](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-logs/lib/log-group.ts#L146) or make a new method that does.

Then we'd have something like:

```js
import cloudwatch = require('@aws-cdk/aws-cloudwatch');
import logs = require("@aws-cdk/aws-logs");

const logGroup = new logs.LogGroup(this, "LogGroup", {retention: logs.RetentionDays.THREE_MONTHS});

const metricFatal = logGroup.extractMetric(logs.FilterPattern.literal('[FATAL]'), "Namespace", "MetricFatal)

metricFatal.createAlarm(this, 'AlarmFatal', {
    threshold: 1,
    evaluationPeriods: 1
})
```

**Comment by rix0rrr** [comment]
`extractMetric` is a convenience method that creates a `MetricFilter` for you. You can also create the `MetricFilter` object yourself and configure it with whatever pattern you want to.

**Comment by SomayaB** [comment]
@chelma-amzn does the above solution solve your issue?

**Comment by cmckni3** [comment]
I had to configure my alarm based on a `MetricFilter` by using `CfnAlarm`.

I was seeing `MetricFilter is missing properties toAlarmConfig, toGraphConfig` in cdk 1.15.0.

**Comment by SomayaB** [comment]
Closing this issue since there hasn't been a response in a while but feel free to reopen.
