### ISSUE TITLE
+x executable bit not being set on uploaded AssetCode for golang lambdas

### ISSUE THREAD

**Issue by WIZARDISHUNGRY** [aws/aws-cdk#3498]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/aws/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
```python
from aws_cdk import (
    aws_ec2 as ec2,
    aws_ecs as ecs,
    aws_ecs_patterns as ecs_patterns,
    aws_apigateway as apigw,
    aws_lambda as lambda_,
    core,
)

class Sibyl(core.Stack):

    def __init__(self, scope: core.Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, *kwargs)

        web = lambda_.Function(
            self, "web",
            code=lambda_.AssetCode.asset("bin"),
            handler="httpd",
            runtime=lambda_.Runtime.GO_1_X
        )

        api = apigw.RestApi(self, "api",
            rest_api_name="Quotes",
            description="This does stuff"
        )

        integration = apigw.LambdaIntegration(web)
        api.root.add_proxy(
            default_integration=integration,
        )

        
app = core.App()
Sibyl(app, "sibyl")
app.synth()
```
Deploy and try to hit a url. CloudWatch logs:
```
fork/exec /var/task/httpd: permission denied: PathError
null
```
If I mess around with the handler path:
```
fork/exec /var/task/./bin/httpd: no such file or directory: PathError null 
```
Comparing `zipinfo` with serverless's output:
```
$ zipinfo .serverless/httpd.zip 
Archive:  .serverless/httpd.zip
Zip file size: 4309367 bytes, number of entries: 1
-rwxr-xr-x  4.5 unx 10067040 bl defN 80-Jan-01 00:00 bin/httpd
1 file, 10067040 bytes uncompressed, 4309235 bytes compressed:  57.2%
```
With the CDK asset zip I downloaded from S3:
```
$ zipinfo /Users/jonwilliams/Downloads/6d27f27d59cc0ed270439e7bca00df1033689146b3389c1e02b7ad3b93ce9518.zip
Archive:  /Users/jonwilliams/Downloads/6d27f27d59cc0ed270439e7bca00df1033689146b3389c1e02b7ad3b93ce9518.zip
Zip file size: 9286087 bytes, number of entries: 2
-rw-r--r--  4.5 unx 10071136 bl defN 80-Jan-01 00:00 httpd
-rw-r--r--  4.5 unx 12544352 bl defN 80-Jan-01 00:00 polld
```
No executable bit.

* **What is the expected behavior (or behavior of feature suggested)?**
The lambda executes.

* **What is the motivation / use case for changing the behavior or adding this feature?**
Suppporting golang lambdas.

* **Please tell us about your environment:**

  - CDK CLI Version: 1.2.0 (build 6b763b7)
  - Module Version: 1.2.0
  - OS: OSX Mojave
  - Language: Python

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

**Comment by jogold** [comment]
Should be fixed with https://github.com/aws/aws-cdk/pull/3428, can you test once this is released with the next version?

**Comment by jogold** [comment]
https://github.com/aws/aws-cdk/releases/tag/v1.3.0
