### ISSUE TITLE
LoadBalancedFargateService abstraction prevents using LB metrics

### ISSUE THREAD

**Issue by chelma-amzn** [aws/aws-cdk#3499]
(moved from original ticket: https://github.com/aws/aws-cdk/issues/3270)

Because [the LoadBalancedServiceBase stores its Load Balancer as an elbv2.BaseLoadBalancer](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-ecs-patterns/lib/base/load-balanced-service-base.ts#L158), users must typecast the Load Balancer member to access things like the native CloudWatch metrics they provide.  This is less than ideal, as it forces the user to pierce the veil of your abstraction.  It may also cause problems in the case where one person is vending another person a collection of constructs, and the consumer doesn't know whether the LB is an Application or Network LB.

```js
const loadBalancedService = new ecsPatternsLoadBalancedFargateService(...);

new cloudwatch.Alarm(this, "AlarmHealthyHostsCount", {
    metric: (<elbv2.NetworkLoadBalancer> loadBalancedService.loadBalancer).metricHealthyHostCount(),
    threshold: 1,
    evaluationPeriods: 1,
    period: core.Duration.seconds(60),
    comparisonOperator: cloudwatch.ComparisonOperator.LESS_THAN_THRESHOLD,
    statistic: "Average"
});
```

**Comment by pkandasamy91** [comment]
In this case, you can specify the LoadBalancerType when you're constructing the LoadBalancedFargateService, you can actually do something like this
```js

const loadBalancedService = new ecsPatterns.LoadBalancedFargateService(stack, 'ServiceName'
{ 
    cluster,
    loadBalancerType: ecsPatterns.LoadBalancerType.NETWORK,
    image
});

const metric = (loadBalancedService.loadBalancer as NetworkLoadBalancer).metricHealthyHostCount();

new cloudwatch.Alarm(this, "AlarmHealthyHostsCount", {
    metric,
    threshold: 1,
    evaluationPeriods: 1,
    period: core.Duration.seconds(60),
    comparisonOperator: cloudwatch.ComparisonOperator.LESS_THAN_THRESHOLD,
    statistic: "Average"
});
```

**Comment by chelma-amzn** [comment]
The proposed code will definitely work to enable users to make use of the LB metrics.  However, it doesn't solve the core issue raised - users must delve into the implementation of the the LoadBalancedFargateService to know which class to cast the LB as in order to access its specific methods and features.  The only way I know that setting the LB Type to NETWORK means I need to cast the LB as a NetworkLoadBalancer is by looking at the code for LoadBalancedServiceBase.  

That said, I think it's accurate to say that this is not a true blocker for users accessing the LB functionality as I originally stated in the issue subject.  It is, however, additional friction that I hope we can find a way to resolve eventually, though I imagine given the existing architecture that would be extremely difficult to do in a backwards-compatible way.

**Comment by eladb** [comment]
Potentially, we can offer strong-typed accessors `service.networkLoadBalancer` and `service.applicationLoadBalancer` which will be mutually exclusive and will allow users to get strong-type reflection without down-casting. I agree that "down-casting as an API" is not the right way:

```ts
const svc = new ecsPatterns.LoadBalancedFargateService(stack, 'ServiceName', { 
    cluster, image,
    loadBalancerType: ecsPatterns.LoadBalancerType.NETWORK,
});

assert.notNull(svc.networkLoadBalancer);
assert.null(svc.applicationLoadBalancer);
``

And vice versa of course.

Should be very easy to add.

**Comment by pkandasamy91** [comment]
@eladb I definitely agree that this will make it easier for customers to access the right LoadBalancer without casting, but this could potentially sky rocket if/when there are more load balancer types that are created/supported in the future. 

Is this the approach we want to take? If that's the case, what's stopping us from doing this to listeners/target groups as well? I don't think this is scalable and will start making it too convoluted. Thoughts?

**Comment by chelma-amzn** [comment]
To make the matter more interesting - the LoadBalancedBase also stores [its Listener](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-ecs-patterns/lib/base/load-balanced-service-base.ts#L160), [its TargetGroup](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-ecs-patterns/lib/base/load-balanced-service-base.ts#L162), [its Cluster](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-ecs-patterns/lib/base/load-balanced-service-base.ts#L164), and [its LogDriver](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-ecs-patterns/lib/base/load-balanced-service-base.ts#L166) as base classes.  The [top level issue this was moved from](https://github.com/aws/aws-cdk/issues/3270) identified that this architecture of storing as a Base class causes consistent customer issues with the way the individual constructs are implemented - the Base Classes (LoadBalancedBase, TargetGroupBase, LogDriver) don't offer the abstract versions of the methods customers will want to interact with, forcing them to typecast the Base into a usable descendant class.  This seems to be a bigger issue than something specific to the LoadBalancedBase.

**Comment by pkandasamy91** [comment]
Can we close this as well? @chelma-amzn

**Comment by chelma-amzn** [comment]
I think so - this is an architectural issue rather than bug.
