### ISSUE TITLE
LoadBalancedFargateService abstraction prevents easy access to LogGroup

### ISSUE THREAD

**Issue by chelma-amzn** [aws/aws-cdk#3500]
(moved from original ticket: https://github.com/aws/aws-cdk/issues/3270)

The current implementation of the LoadBalancedFargateService prevent users from easily accessing the LogGroup it [creates when they pass in the enableLogging constructor arg](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-ecs-patterns/lib/base/load-balanced-service-base.ts#L181).  The impact is that it is difficult (impossible?) for users to do things like create CloudWatch MetricFilters to watch their application logs and be notified of important log events.  It also prevents users from changing things like the retention policy of the LogGroup.

Specifically, [the code instantiates an AwsLogDriver without letting the use pass in a LogGroup](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-ecs-patterns/lib/base/load-balanced-service-base.ts#L260), as [the AwsLogDriver constructor allows](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-ecs/lib/log-drivers/aws-log-driver.ts#L27).  Since the LogGroup's retention policy can only be set during instantiation (no setter method), this means that customers are stuck with whatever retention policy is default.  Depending on whether the customer has external compliance obligations, this can be a complete non-starter for them.

While the AwsLogDriver class does [surface the LogGroup it creates to the use in its own interface](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-ecs/lib/log-drivers/aws-log-driver.ts#L71), it's [stored in the LoadBalancedServiceBase class as a LogDriver object](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-ecs-patterns/lib/base/load-balanced-service-base.ts#L166), and that type [does not surface the LogGroup in its own interface](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-ecs/lib/log-drivers/log-driver.ts#L8).  This means that in order to get access to the LogGroup, the user would need to perform a type cast on the `logDriver` member of their LoadBalancedFargateService, which is generally a bad idea.

**Comment by eladb** [comment]
+1 on allowing to specify the log driver.

Additionally, we can expose `service.logGroup` which will be defined if the AWS log driver is used and then `service.logGroup` can be used to access the log group in case an AWS log driver is used. Sounds like a common enough use case.

**Comment by pkandasamy91** [comment]
I'm in agreement with allowing the log driver to be specified as there could be various different log drivers that may be used in the future. 

I don't think we could expose loggroup properties because it will back us into a corner and prevent us from making changes in the future if customers want to use another logdriver such as Fluentd, etc.

**Comment by eladb** [comment]
Okay I am convinced.

**Comment by pkandasamy91** [comment]
Changes have been made and approved: https://github.com/aws/aws-cdk/pull/3550 - pending automerge.

**Comment by pkandasamy91** [comment]
Merge complete
