### ISSUE TITLE
cdk is not deploying updates to lambda function

### ISSUE THREAD

**Issue by harmohan-a** [aws/aws-cdk#3503]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/aws/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*

i created a cdk app using the cli and added a lambda function. did a deployment, it went fine. but when i updated the lambda function. did a deployment again, it created a new artifact for the lambda function in the cdk.out dir but didnt actually update the s3 bucket.

i ran cdk in verbose mode

```
DaxDdbApiCdkStack: deploying...
Waiting for stack CDKToolkit to finish creating or updating...
Preparing asset DaxDdbApiCdkStackdaxcoralmovieddbapicdkfunctionCode747A0694: {"path":"asset.b99b28c495b561bd928533f2d2216bb15509eb9afcf8e2b3e4ad29b398bf8f99","id":"DaxDdbApiCdkStackdaxcoralmovieddbapicdkfunctionCode747A0694","packaging":"zip","sourceHash":"b99b28c495b561bd928533f2d2216bb15509eb9afcf8e2b3e4ad29b398bf8f99","s3BucketParameter":"daxcoralmovieddbapicdkfunctionCodeS3BucketA7A89177","s3KeyParameter":"daxcoralmovieddbapicdkfunctionCodeS3VersionKey556CC4A6","artifactHashParameter":"daxcoralmovieddbapicdkfunctionCodeArtifactHash10E90108"}
Preparing zip asset from directory: cdk.out/asset.b99b28c495b561bd928533f2d2216bb15509eb9afcf8e2b3e4ad29b398bf8f99
````

but that's about it, it doesnt actully do any updates to the s3. when i checked s3, it still has the older artifact 

* **What is the expected behavior (or behavior of feature suggested)?**

the new artifact should be deployed to s3 and lambda function should update

* **What is the motivation / use case for changing the behavior or adding this feature?**

* **Please tell us about your environment:**

  - CDK CLI Version: 1.2.0
  - Module Version: 1.2.0
  - OS: [all | Windows 10 | OSX Mojave | Ubuntu | etc... ]
  - Language: TypeScript

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

https://stackoverflow.com/questions/57300735/cdk-deploy-neither-updating-my-coudformation-template-nor-is-it-deploying-the-up

**Comment by jogold** [comment]
Should be fixed with #3428, can you test once this is released with the next version?

**Comment by harmohan-a** [comment]
yea, absolutely. thanks for getting an update on this

**Comment by jogold** [comment]
https://github.com/aws/aws-cdk/releases/tag/v1.3.0

**Comment by harmohan-a** [comment]
its working now. but, i've found another issue relating to updating the iam statement changes. i'll create a new ticket for it. thanks for your help
