### ISSUE TITLE
Python dependency libraries are set to latest

### ISSUE THREAD

**Issue by lkoniecz** [aws/aws-cdk#3517]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/aws/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*
Following requirements set
```
aws-cdk.core==1.0.0
aws-cdk.aws_ec2==1.0.0
aws-cdk.aws_eks==1.0.0
aws-cdk.aws_autoscaling==1.0.0
aws-cdk.aws_elasticloadbalancing==1.0.0
aws-cdk.aws_dynamodb==1.0.0
aws-cdk.aws_lambda==1.0.0
aws-cdk.aws_iam==1.0.0
aws-cdk.aws_apigateway==1.0.0
```
installs
```
aws-cdk.assets                     1.2.0     
aws-cdk.aws-apigateway             1.0.0     
aws-cdk.aws-applicationautoscaling 1.2.0     
aws-cdk.aws-autoscaling            1.0.0     
aws-cdk.aws-autoscaling-common     1.2.0     
aws-cdk.aws-certificatemanager     1.2.0     
aws-cdk.aws-cloudformation         1.2.0     
aws-cdk.aws-cloudwatch             1.2.0     
aws-cdk.aws-dynamodb               1.0.0     
aws-cdk.aws-ec2                    1.0.0     
aws-cdk.aws-eks                    1.0.0     
aws-cdk.aws-elasticloadbalancing   1.0.0     
aws-cdk.aws-elasticloadbalancingv2 1.2.0     
aws-cdk.aws-events                 1.2.0     
aws-cdk.aws-iam                    1.0.0     
aws-cdk.aws-kms                    1.2.0     
aws-cdk.aws-lambda                 1.0.0     
aws-cdk.aws-logs                   1.2.0     
aws-cdk.aws-route53                1.2.0     
aws-cdk.aws-s3                     1.2.0     
aws-cdk.aws-s3-assets              1.2.0     
aws-cdk.aws-sns                    1.2.0     
aws-cdk.aws-sqs                    1.2.0     
aws-cdk.aws-ssm                    1.0.0     
aws-cdk.core                       1.0.0     
aws-cdk.cx-api                     1.2.0     
aws-cdk.region-info                1.2.0  
```

Transitive dependencies are always resolved to latest which leads to errors - this one, for instance:

```
(.env) [eba@INV-7947 eks]$ cdk ls
Traceback (most recent call last):
  File "app.py", line 3, in <module>
    from aws_cdk import (
  File "/home/eba/work/cfconfig/contrib/cloudformation/cdk/eks/.env/lib/python3.7/site-packages/aws_cdk/aws_ec2/__init__.py", line 14, in <module>
    import aws_cdk.aws_ssm
  File "/home/eba/work/cfconfig/contrib/cloudformation/cdk/eks/.env/lib/python3.7/site-packages/aws_cdk/aws_ssm/__init__.py", line 16, in <module>
    class CfnAssociation(aws_cdk.core.CfnResource, metaclass=jsii.JSIIMeta, jsii_type="@aws-cdk/aws-ssm.CfnAssociation"):
  File "/home/eba/work/cfconfig/contrib/cloudformation/cdk/eks/.env/lib/python3.7/site-packages/aws_cdk/aws_ssm/__init__.py", line 228, in CfnAssociation
    @jsii.data_type(jsii_type="@aws-cdk/aws-ssm.CfnAssociation.InstanceAssociationOutputLocationProperty", jsii_struct_bases=[])
TypeError: data_type() missing 1 required keyword-only argument: 'name_mapping'
```

* **What is the expected behavior (or behavior of feature suggested)?**
Libraries install their dependencies with the same version.

* **What is the motivation / use case for changing the behavior or adding this feature?**
Whole library set becomes unstable and does not work.

* **Please tell us about your environment:**

  - CDK CLI Version: 1.0.0
  - Module Version: 1.0.0
  - OS: [all]
  - Language: [Python]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

**Comment by vaneek** [comment]
I have also notice odd behavior, currently I am at CDK 1.2.0 but the modules all show 1.0.0.

```
CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.2.0,
                      @aws-cdk/assets=1.0.0,
                      @aws-cdk/aws-autoscaling=1.0.0,
                      @aws-cdk/aws-autoscaling-common=1.0.0,
                      @aws-cdk/aws-certificatemanager=1.0.0,
                      @aws-cdk/aws-cloudformation=1.0.0,
                      @aws-cdk/aws-cloudwatch=1.0.0,
                      @aws-cdk/aws-codecommit=1.0.0, 
                      @aws-cdk/aws-ec2=1.0.0,
                      @aws-cdk/aws-elasticloadbalancing=1.0.0,
                      @aws-cdk/aws-elasticloadbalancingv2=1.0.0,
                      @aws-cdk/aws-events=1.0.0,
                      @aws-cdk/aws-iam=1.0.0,
                      @aws-cdk/aws-kms=1.0.0,
                      @aws-cdk/aws-lambda=1.0.0,
                      @aws-cdk/aws-logs=1.0.0,
                      @aws-cdk/aws-route53=1.0.0,
                      @aws-cdk/aws-s3=1.0.0,
                      @aws-cdk/aws-s3-assets=1.0.0,
                      @aws-cdk/aws-sns=1.0.0,
                      @aws-cdk/aws-sns-subscriptions=1.0.0,
                      @aws-cdk/aws-sqs=1.0.0,
                      @aws-cdk/aws-ssm=1.0.0,
                      @aws-cdk/core=1.0.0,
                      @aws-cdk/cx-api=1.0.0,
                      @aws-cdk/region-info=1.0.0,
                      jsii-runtime=Python/3.6.8
```
I tried to force the modules to 1.2.0 but I only made a mess of things. There is also inconsistency with the latest JSII version as well.

**Comment by MrArnoldPalmer** [comment]
See https://github.com/aws/jsii/issues/676 for more information.

**Comment by lkoniecz** [comment]
@MrArnoldPalmer any updates on this?

**Comment by MrArnoldPalmer** [comment]
@lkoniecz I thought this was addressed with https://github.com/aws/jsii/pull/1141. Are you still experiencing issues?

**Comment by lkoniecz** [comment]
@MrArnoldPalmer 
I tried that on 1.18 which still installs 1.20 python dependecies.

**Comment by henrist** [comment]
The fix was released in jsii 0.21.0, which is used since cdk 1.20.0 (#5610). You will need to update to 1.20.0 or later for the dependencies to resolve correctly. This issue should be closed.

**Comment by lkoniecz** [comment]
@henrist 
Thanks, this explains the reason that I still see the problem.

**Comment by MrArnoldPalmer** [comment]
Closing this fixed/dupe.

See #676 and https://github.com/aws/jsii/pull/1141.
