### ISSUE TITLE
TypeError when validating ACM certificate

### ISSUE THREAD

**Issue by JoshYaxley** [aws/aws-cdk#3531]
* **I'm submitting a ...**
  - [x ] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/aws/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*

This behaviour occurs for me when creating a certificate using:
```
new certmgr.DnsValidatedCertificate(this, 'Certificate', {
  domainName: 'example.com',
  subjectAlternativeNames: ['*.example.com'],
  hostedZone
}));
```

* **What is the expected behavior (or behavior of feature suggested)?**

Certificate validates without error.

* **Please tell us about your environment:**

  - CDK CLI Version: 1.3.0
  - Module Version: 1.3.0
  - OS: Windows 10
  - Language: TypeScript

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

Logs from the Lambda function:

```

22:36:48
START RequestId: 02acf4cf-5c88-4a2d-b2e4-17587cac0b5a Version: $LATEST

22:36:48
2019-08-03T22:36:48.819Z	02acf4cf-5c88-4a2d-b2e4-17587cac0b5a	Requesting certificate for <REDACTED>

22:36:50
2019-08-03T22:36:50.198Z	02acf4cf-5c88-4a2d-b2e4-17587cac0b5a	Certificate ARN: arn:aws:acm:us-east-1:<REDACTED>:certificate/3f67aaef-16f7-47c1-9fd7-31cd902fccca

22:36:50
2019-08-03T22:36:50.198Z	02acf4cf-5c88-4a2d-b2e4-17587cac0b5a	Waiting for ACM to provide DNS records for validation...

22:36:51
2019-08-03T22:36:51.556Z	02acf4cf-5c88-4a2d-b2e4-17587cac0b5a	Caught error TypeError: Cannot read property '0' of undefined. Uploading FAILED message to S3.

22:36:51
END RequestId: 02acf4cf-5c88-4a2d-b2e4-17587cac0b5a
```

The error is: `TypeError: Cannot read property '0' of undefined`

Looking through the code that is used for the lambda, I believe that the error is thrown on this line: https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-certificatemanager/lambda-packages/dns_validated_certificate_handler/lib/index.js#L107

Which I believe is missing a `.length` as a typo.

**Comment by hoegertn** [comment]
I had the same error earlier this day. I am trying to reproduce it currently and will open a PR with a fix if I succeed.

**Comment by rix0rrr** [comment]
Does this still happen after https://github.com/aws/aws-cdk/pull/3528 ?

**Comment by rix0rrr** [comment]
I have a suspicion this might be fixed, so I'm closing this issue to keep our queue manageable. Please reopen this issue if you are still seeing the issue.
