### ISSUE TITLE
Add CDK Constructs support for Batch

### ISSUE THREAD

**Issue by stephnr** [aws/aws-cdk#3536]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [ ] :beetle: bug report
  - [ ] :rocket: feature request
  - [X] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/aws/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
Currently the Batch CDK supports only generated Cloudformation resource content.

* **What is the expected behavior (or behavior of feature suggested)?**
I am intending to add support for Batch Constructs in the `@aws-cdk/aws-batch` module.

* **What is the motivation / use case for changing the behavior or adding this feature?**
Adding full CDK support for the collection of Batch services. I estimate the following resources will be required to meet the requirement:

- ComputeEnvironment
- JobQueue
- JobDefinition

**Comment by defaltd** [comment]
I am currently working on this herein >> [Forked Project](https://github.com/defaltd/aws-cdk/tree/add-base-batch-cdk)

However, I am running into an issue with Service Linked Roles. Is there a practice somewhere in another CDK module that shows how to manage these in a CDK/Construct like fashion?

I ran into the same issue as well with the following properties of `ComputeEnvironment.computeResources`:

- launchTemplate
- placementGroup

**Comment by rhboyd** [comment]
Hey @defaltd, I'd love to help you make some progress on this. Are you in the Gitter chat or the cdk slack channel?

**Comment by defaltd** [comment]
Thank you! I would love any assistance on this ☺️. I'll see about getting into the CDK slack channel.

**Comment by defaltd** [comment]
@rhboyd what is your username in the slack channel?

**Comment by reisingerf** [comment]
Any progress on this? Would love to see this happen!

**Comment by stephnr** [comment]
Yes! Thanks for the friendly reminder here @reisingerf @rhboyd. I am finished with the logic now but working on tests. You can view the progress from my fork below:

https://github.com/stephnr/aws-cdk/commits/master

**Comment by stephnr** [comment]
Hello @skinny85, I noticed you were assigned here on this ticket. Do you mind reviewing my work thus far or shall we wait until I have finished everything up?

**Comment by skinny85** [comment]
Hello @stephnr , apologies for missing this! I'll review it today and leave my feedback. Thanks for the contribution!

**Comment by skinny85** [comment]
Actually, can you submit a PR based off your fork? You can submit it as a "Work in Progress" PR if you only want to get early feedback, but don't feel it's ready to be merged in yet.

**Comment by stephnr** [comment]
Please see PR #4732 for an early review. Great idea @skinny85.

**Comment by skinny85** [comment]
#4732 has been merged, closing this one :).
