### ISSUE TITLE
Support for modifying CFN templates imported using CfnInclude

### ISSUE THREAD

**Issue by strazeadin** [aws/aws-cdk#3537]
* **I'm submitting a ...**
  - [ x ] :rocket: feature request

* **What is the expected behavior (or behavior of feature suggested)?**
Ability to interact and modify Constructs that are imported using [CfnInclude](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.CfnInclude.html)

* **What is the motivation / use case for changing the behavior or adding this feature?**
I have an existing stack that I would like to continue supporting, that stack has already been deployed across several accounts and therefore I would like to preserve the logical ids. 
My current workaround is to maintain my old CFN and any updates to it the same way as before and using CDK for new constructs.

* **Please tell us about your environment:**
  - Language: TypeScript

* **Other information**
Potentially an ability to search / lookup by logical ID and get a matching CfnResource to allow modifying of the resource. 

Happy to hear any ideas/alternatives about how to potentially implement this or if there are workarounds I can use in the mean time.

**Comment by flyingImer** [comment]
any update on this? I have a very similar use case as well

**Comment by skinny85** [comment]
@flyingImer we hope to have this in the first quarter of 2020.

**Comment by ngamradt-turner** [comment]
We have a number of existing templates and stacks, having this ability to leverage the CDK to help manage those existing stacks/templates would be very useful.

**Comment by skinny85** [comment]
This is now possible with our new [cfn-include](https://docs.aws.amazon.com/cdk/api/latest/docs/cloudformation-include-readme.html) module.

Resolving, please let us know if there's anything more we can do here.
