### ISSUE TITLE
Importing StringListParameter results in array with single token string.

### ISSUE THREAD

**Issue by mescam** [aws/aws-cdk#3540]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/aws/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*

Hey,
importing ssm.StringListParameter allows me to get property `stringListValue` which I expect to be a list of strings from my parameter store. As it uses CfnDynamicReference the values are not present during synthesis, so it returns a single-item array: `[ '#{Token[TOKEN.11]}' ]`
```
const p = ssm.StringListParameter.fromStringListParameterName(
  this,
  "params",
  "/whatever"
);

console.log(p.stringListValue);
```

* **What is the expected behavior (or behavior of feature suggested)?**
Probably it should throw an exception that values are not present and we are not able to iterate over it as it will be resolved only during deployment.

* **What is the motivation / use case for changing the behavior or adding this feature?**
It might be misleading for developers that SSM parameters are being retrieved during synthesis via API calls and we will be able eg. store ARNs in SSM parameter and then create resources based on that entries.

* **Please tell us about your environment:**

  - CDK CLI Version: 1.3.0
  - Module Version: 1.3.0
  - OS: OSX Mojave
  - Language: all

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

**Comment by eladb** [comment]
This is the expected behavior. We should add some documentation on `fromStringListParameterName` that explains that the returned value is a token and should not be parsed.

**Comment by SomayaB** [comment]
Closing this issue since it is expected behavior. Created a new issue to address the documentation improvement needed. #5058
