### ISSUE TITLE
Cannot addDependency for Glue database

### ISSUE THREAD

**Issue by marc-air-agents** [aws/aws-cdk#3542]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [x ] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/aws/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
Create Glue.Database.
Create a CfnTable.
call table.addDependsOn passing the Glue.Database as parameter.
The code will not build - Glue.Database is not an acceptable parameter

*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*

class OurMainApp extends cdk.Construct {
    constructor(scope: any, id: any, props: any) {
        super(scope, id);
        let db_props: DatabaseProps = { databaseName: "db_props_name" };
        let database: Database = new Database(this, "db_name", db_props);

        let table_props: CfnTableProps = {
            //populate table props here
        }

        const table = new CfnTable(this, "table_name", table_props);
        //table builds successfully, but cannot add database as a dependency
        table.addDependsOn(database);
    }
}

* **What is the expected behavior (or behavior of feature suggested)?**
table.addDependsOn(database) should not give a build error - since Glue.Database extends
extends Resource

* **What is the motivation / use case for changing the behavior or adding this feature?**

* **Please tell us about your environment:**

  - CDK CLI Version: 1.3.0
  - Module Version: 1.3.0
  - OS: OSX Mojave
  - Language:  TypeScript

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

**Comment by skinny85** [comment]
Hey @marc-air-agents ,

I think there is some confusion between L1 and L2 resources here. See this topic for an explanation: https://docs.aws.amazon.com/cdk/latest/guide/constructs.html

In your code, `Database` is the L2, while `CfnTable` is the L1. If you want to make it work, you can do it like this:

```
table.node.addDependency(database);
```

Hope this helps!

Thanks,
Adam

**Comment by SomayaB** [comment]
Will close this issue since there hasn't been any response in a while but feel free to reopen!
