### ISSUE TITLE
Support DataProcessing in SagemakerTransformTask

### ISSUE THREAD

**Issue by rbs392** [aws/aws-cdk#3543]
* **I'm submitting a ...**
  - [X] :rocket: feature request

* **What is the expected behavior (or behavior of feature suggested)?**
SagemakerTransformTask supports DataProcessing property

* **What is the motivation / use case for changing the behavior or adding this feature?**
Missing feature from the actual api of sagemaker batch transform

* **Please tell us about your environment:**

  - CDK CLI Version: 1.30.0
  - Module Version: xx.xx.xx
  - OS: [all | Windows 10 | OSX Mojave | Ubuntu | etc... ]
  - Language: [all | TypeScript | Java | Python ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

https://docs.aws.amazon.com/sagemaker/latest/dg/API_CreateTransformJob.html#SageMaker-CreateTransformJob-request-DataProcessing

**Comment by rbs392** [comment]
@eladb can you please comment if this feature is planned or possible in any upcoming releases?

**Comment by SomayaB** [comment]
Hi @rbs392, thanks for submitting  a feature request. Unfortunately until this is added to CloudFormation we can't add it to the CDK. I've submitted a ticket for them to add it. You can also ask them [here](https://forums.aws.amazon.com/forum.jspa?forumID=92).

**Comment by dahnny012** [comment]
I was able to get it to work by overriding the bind method. Does this mean it works now?

```
export class SageMakerTransformTaskWithDataProcessingInput extends tasks.SagemakerTransformTask {
         public bind(task: sfn.Task): sfn.StepFunctionsTaskConfig {
             const config = super.bind(task)
 
             const newParameters = config.parameters || {};
 
             // Adding DataProcessing seperately into the input
             // as this is not part of the SagemakerTransformTask model
             // refer https://github.com/aws/aws-cdk/issues/3543
 
             newParameters["DataProcessing"] = {
                 "JoinSource": "Input"
             }
 
             return {
                 resourceArn: config.resourceArn,
                 policyStatements: config.policyStatements,
                 parameters: newParameters
             }
         }
     }
```

**Comment by nija-at** [comment]
Seems to be missing in their documentation for `CreateTransformJob` - https://docs.aws.amazon.com/step-functions/latest/dg/connect-sagemaker.html
