### ISSUE TITLE
cdk bootstrap should accept environments in aws:// format

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#3544]
* **I'm submitting a ...**
  - [x] :beetle: bug report

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*

When an environment needs to be bootstrapped the CLI prints this message:

```
This stack uses assets, so the toolkit stack must be deployed to the environment (Run "cdk bootstrap aws://585695111111/eu-west-2")
```

But when actually running this command we get an error:

```console
$ cdk bootstrap aws://585695111111/eu-west-2
Expected environment name in format '<account>/<region>'
```

* **What is the expected behavior (or behavior of feature suggested)?**

`cdk bootstrap` should _also_ accept environments in the format specified in the error message.

* **Please tell us about your environment:**

  - CDK CLI Version: 1.2.0

**Comment by jansony1** [comment]
Same request. It really confused me

**Comment by jmacnett** [comment]
so, this works, but the suggested syntax is kind of a lie:

`cdk bootstrap --profile myprofile aws://123456789123/us-east-1` does NOT work, but
`cdk bootstrap --profile myprofile 123456789123/us-east-1` does.

Because reasons.   This was on 1.3.0, which i just switched to today.
