### ISSUE TITLE
Support PULL_REQUEST_MERGED EventAction in aws-codebuild module

### ISSUE THREAD

**Issue by mbruning24** [aws/aws-cdk#3557]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [ ] :beetle: bug report
  - [x] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/aws/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*

aws-codebuild module does not support `EventAction.PULL_REQUEST_MERGED` for FilterGroup creation for webhooks in a build project

* **What is the expected behavior (or behavior of feature suggested)?**

aws-codebuild would support PULL_REQUEST_MERGED as an EventAction type for webhook FilterGroup creation `.inEventOf()` syntax.

Referenced [here](https://docs.aws.amazon.com/codebuild/latest/userguide/sample-bitbucket-pull-request.html#sample-bitbucket-pull-request-filter-webhook-events) as supported by AWS Documentation.

* **What is the motivation / use case for changing the behavior or adding this feature?**

We want to use aws-cdk for the building of our entire CI/CD pipeline, but this is one thing preventing us from doing so.

* **Please tell us about your environment:**

  - CDK CLI Version: 1.2.0 (build 6b763b7)
  - Module Version: 1.2.0
  - OS: Windows 10
  - Language: TypeScript

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

**Comment by skinny85** [comment]
Thanks for opening the issue @mbruning24 !

Would you consider opening us a Pull Request adding this functionality? From what I see, it's as simple as adding another value to the [Event Action enum](https://github.com/aws/aws-cdk/blob/8ffba4b04f5086b33b46aa87fe59a7fe7845ff01/packages/%40aws-cdk/aws-codebuild/lib/source.ts#L154).

**Comment by mbruning24** [comment]
@skinny85 Yeah I'm going to try and get that done in the next day or so.

**Comment by mbruning24** [comment]
@skinny85 Having some issues running ./install.sh and ./build.sh locally, so I can't run any tests. I'm getting the following:

```
$ ./install.sh
npm ci
=============================================================================================
installing repo-global dependencies...

> fsevents@1.2.9 install C:\dev\aws-cdk\node_modules\fsevents
> node install

added 1078 packages in 22.446s
=============================================================================================
cleanup and start bootstrapping...
module.js:550
    throw err;
    ^

Error: Cannot find module 'C:\Program Files\Git\dev\aws-cdk\node_modules\lerna\cli.js'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
```

I'm using gitbash MINGW64 on a windows 10 machine. Are there special instructions for that particular type of environment?

**Comment by skinny85** [comment]
Hmm. It seems that the dependencies were not installed (on the global level). Can you check what's the content of `C:\Program Files\Git\dev\aws-cdk\node_modules\lerna` on your machine? On mine, it has the `cli.js` file that the error is talking about.

In the worst case, just do the change without running the build - I know it's not great, but our CI will verify everything is building correctly.

**Comment by mbruning24** [comment]
@skinny85 yeah I tried on a fresh AWS Linux build with NVM and it ran no problem. I have made the change and run the tests on the codebuild module. I just have to commit and prep the PR should have it ready soon yet today. 

Btw if you have not tried remote ssh with vscode, I HIGHLY recommend it.

**Comment by skinny85** [comment]
Thanks for the recommendation, but you can pry Intellij IDEA from my cold, dead hands :D

**Comment by mbruning24** [comment]
@skinny85 only thing I couldn't figure out was how to modify the reviewers to the "awslabs/aws-cdk" team.

**Comment by skinny85** [comment]
No worries, I'm on it :)
