### ISSUE TITLE
aws_s3_assets Asset.s3_object_key does not work

### ISSUE THREAD

**Issue by SamProtas** [aws/aws-cdk#3566]
* **I'm submitting a ...**
  - [ x] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/aws/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
When a Stack includes an s3_asset.Asset and references its property `s3ObjectKey`, the string `"[object Object][object Object]"` is rendered instead of the actual object key.

```
import aws_cdk.aws_s3_assets as s3_asset

my_asset = s3_asset.Asset(self, 'SomeId', path='some-asset.txt')

my_asset.s3_object_key  # This will render as "[object Object][object Object]"
```

* **What is the expected behavior (or behavior of feature suggested)?**

I expect the actual s3 key to be rendered.

* **What is the motivation / use case for changing the behavior or adding this feature?**

I'm trying to use s3 assets for AWS glue scripts. This appears to need a script location like `s3://bucket/etc.` where as the built in s3.s3_url outputs `https://s3.....`.

Since the built in `s3_url` won't do the trick, I've attempted to build the `s3://` location myself using `bucket_name` and `s3_object_key`.

* **Please tell us about your environment:**

  - CDK CLI Version: 1.3.0 (build bba9914)
  - Module Version: 1.3.0
  - OS: OSX Mojave 
  - Language: Python

* **Other information** 

I'm fairly certain this is the offending line of code:
https://github.com/aws/aws-cdk/blob/a81e560de226e8c8aa9928833403c0e9da4ba455/packages/%40aws-cdk/aws-s3-assets/lib/asset.ts#L119

**Comment by SamProtas** [comment]
The issue was I was treating these tokens as `!Ref something` rather than the CDK token concept.

I was doing `core.Fn.join('', ['s3://', asset.s3_bucket_name, asset.s3_object_key])` instead of `'s3://' + asset.s3_bucket_name + asset.s3_object_key`.

I'm guessing this falls under "user error" but some sort of error message would definitely be helpful.

**Comment by eladb** [comment]
Thanks for following up. What message would you expect?

**Comment by SamProtas** [comment]
Well that's a good question.

Given two "strings" (code literal strings, Tokens, outputs for core.Fn.get_att) it's not particularly clear to me when they can be combined with one or both of `core.Fn.join` vs `+`.

If the answer is, "when dealing with `X`, you must use cloudformation functions, when dealing with `Y`, you must use your languages normal string concatenation" then I'd imagine just stating that would be a great first step. Ideally this would also explain what types you used so its clear which arguments are causing the issue.

If the answer is more nuanced, then whatever the specific situation that was hit could be explained.

Either way, I think this area could us a bit more documentation (or if exists, it could be more prominently displayed). Even dumping a link to the docs explaining how this works would be great in the error message.

Anyway, looking forward to the rough edges of CDK to be ironed out as I'm already sold on the idea. Things like this just expose areas that could use more polish I think. It took downloading the source and trying to fix what I perceived as a bug to realize how to correct the user error.

**Comment by SamProtas** [comment]
Sorry, didn't mean to re-open.

**Comment by skinny85** [comment]
> The issue was I was treating these tokens as `!Ref something` rather than the CDK token concept.
> 
> I was doing `core.Fn.join('', ['s3://', asset.s3_bucket_name, asset.s3_object_key])` instead of `'s3://' + asset.s3_bucket_name + asset.s3_object_key`.
> 
> I'm guessing this falls under "user error" but some sort of error message would definitely be helpful.

I'm wondering whether you possibly ran into this bug: #3554 ?

**Comment by SamProtas** [comment]
Hmmm, it definitely seems to be the same class of error (references not being rendered as intended) but I'm still not entirely sure if my situation is an actual bug or just functionality that could use better docs and error messages.

I was *not* seeing the token string representation in the rendered template, I was literally seeing `"[object Object][object Object]"` output, from my stack written in Python no less.

My usage of cloudformation functions was leading to what I believe are Tokens being rendered as strings using the default Object.prototype.toString() rather than their overridden toString().

**Comment by SamProtas** [comment]
@skinny85 I'm also now noticing that issue was closed with a PR fixing cross-stack references specifically.

My issue occurred within a single stack.

**Comment by skinny85** [comment]
Ah, got it. Yes, that means they're probably unrelated then.
