### ISSUE TITLE
Different ARN generated by formatArn than exists in the Stack

### ISSUE THREAD

**Issue by MichaelHindley** [aws/aws-cdk#3570]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/aws/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*
Given this code:
```typescript
    const deployServiceStateMachineName = 'DeployService'

    const deployServiceStateMachine = new sfn.StateMachine(
      this, 
      deployServiceStateMachineName
    )

    const deployServiceStateMachineArn = this.formatArn({
      account: this.account,
      region: this.region,
      service: 'states',
      resource: 'stateMachine',
      sep: ':',
      resourceName: deployServiceStateMachineName
    })
```

I would expect that `deployServiceStateMachineArn` is identical to `deployServiceStateMachine.stateMachineArn`.

The actual arn however has a randomly generated suffix on the end, resulting in an incorrect value in `deployServiceStateMachineArn`. Maybe there is a way to get the suffix and pass it to formatArn?

`deployServiceStateMachine.stateMachineArn` can not be used due to circular dependencies that the CDK creates behind the scenes when using this chain:
<StateMachineDefinition>
An event rule for PutImage with a Lambda as Target that needs the StateMachineArn to run StartExecution.

(I can't seem to figure out why there is a need circular dependency since the StateMachine does not depend on the Lambda but I'm not aware of cdk internals)

* **Please tell us about your environment:**
All latest, win 10

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

**Comment by eladb** [comment]
You shouldn't need to format the ARN yourself. `stateMachineArn` should work. Can you provide some more details about your circular dependency? Maybe you can provide a minimal code snippet that demonstrates it?

**Comment by MichaelHindley** [comment]
Sure I'll get a repro up :)

**Comment by rix0rrr** [comment]
```
    const deployServiceStateMachineName = 'DeployService'

    const deployServiceStateMachine = new sfn.StateMachine(
      this, 
      deployServiceStateMachineName
    )
```

This does not create a state machine with the given string as a *name*, it creates a state machine with the given name as a *construct id*. CloudFormation will give it a unique name, unless you specify the `state_machine_name` property.

Read the [Identifiers](https://docs.aws.amazon.com/cdk/latest/guide/identifiers.html) and the [Physical Names](https://docs.aws.amazon.com/cdk/latest/guide/resources.html) sections of the docs to learn about the difference.
