### ISSUE TITLE
CfnDeliveryChannel never completes and blocks deployment

### ISSUE THREAD

**Issue by mteichtahl** [aws/aws-cdk#3577]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [X] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/aws/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*

CfnDeliveryChannel causes a deployment to sit idle for >30min and never completes

```
/** create the config bucket */
        const configRulesDeliveryBucket = new Bucket(this, 'configRulesDeliveryBucket', {
            bucketName: `aws-configrules-${config.accountNumber}-do-not-delete`,
            removalPolicy: cdk.RemovalPolicy.DESTROY
        });

        /** add cloudtrail bucket policies */
        configRulesDeliveryBucket.addToResourcePolicy(new PolicyStatement({
            effect: Effect.ALLOW,
            principals: [ new ServicePrincipal('config.amazonaws.com') ],
            actions: ['s3:*'],
            resources: [`${configRulesDeliveryBucket.bucketArn}`]
        }))


        /** we need a delivery channel for config rules */
        const configDeliveryChannel = new CfnDeliveryChannel(this, 'configDeliveryChannel', {
            s3BucketName: configRulesDeliveryBucket.bucketName,
            name: 'configDeliveryChannel'
        })

 /** create a config recorder so we capture everything first */
        const configRecorder = new CfnConfigurationRecorder(this, 'configRecorder', {
            name: `${config.customerName}ConfigRecorder`,
            roleArn: prototypingConfigServiceRole.roleArn,
            recordingGroup: {
                allSupported: false,
                includeGlobalResourceTypes: false,
                resourceTypes: [
                    "AWS::EC2::EIP",
                    "AWS::EC2::Instance",
                    "AWS::EC2::NetworkAcl",
                    "AWS::EC2::SecurityGroup",
                    "AWS::CloudTrail::Trail",
                    "AWS::EC2::Volume",
                    "AWS::EC2::VPC",
                    "AWS::IAM::User",
                    "AWS::IAM::Policy"
                ]
            }
        })

        configRecorder.node.addDependency(configDeliveryChannel)
```

* **What is the expected behavior (or behavior of feature suggested)?**

Creation of a config rules delivery stream followed by a config rules recorder

* **Please tell us about your environment:**

  - CDK CLI Version: 1.0.0 (build d89592e)
  - Module Version: 1.3.0
  - OS: [ OSX Mojave]
  - Language: [ TypeScript]

**Comment by rix0rrr** [comment]
What kind of error, if any, does CloudFormation report during deployment?

Do you have a snippet of CloudFormation that does do what you want?

I'm asking, because the classes that start with `Cfn` names map directly onto CloudFormation, and there is 0 CDK code here. That means that we have no control over what happens here, it's completely between you and CloudFormation. It's one of 2 things: either CloudFormation has a bug or the code you wrote is not complete.

**Comment by SomayaB** [comment]
@mteichtahl

**Comment by SomayaB** [comment]
Closing this issue since there hasn't been activity on it in a while. Feel free to reopen.

**Comment by mark-schaal** [comment]
@mteichtahl I ran across something similar and after reading the docs in CloudFormation, I think your dependency might be reversed. You must have a Config Recorder created before you can create a Delivery Channel, and you may only have one Delivery Channel per region.

I do find it odd that there is no declarative statement in CloudFormation to show the relationship between the Recorder and Delivery Channel entities... but my guess is that they assume the uniqueness of delivery channels per region is enough?

**Comment by mark-schaal** [comment]
Curiosity got the better of me. Took the example at https://github.com/awslabs/aws-cloudformation-templates/blob/2249cbe7760f7c7bd4adbae5301d0c4ace8a037d/aws/services/Config/Config.yaml on a brand new account and implemented it into CDK with the same experience as @mteichtahl .

@rix0rrr It seems that there might be a circular dependency between the Recorder and the Delivery Channel. 

If you attempt to bring up the Recorder without the Delivery Channel, you get the following error:
```
ConfigDefaultRecorder Delivery channel is not available to start configuration recorder.
(Service: AmazonConfig; Status Code: 400; Error Code: NoAvailableDeliveryChannelException; Request ID: XXXX)
```

If you attempt to bring up the Delivery Channel without the Recorder, you get the expected error:
```
ConfigDefaultDeliveryChannel Configuration recorder is not available to put delivery channel.
(Service: AmazonConfig; Status Code: 400; Error Code: NoAvailableConfigurationRecorderException; Request ID: XXXX)
```

If you attempt to bring both up simultaneously, either using `.addDependency()` or just as independent resources, it will still fail.

For all of the above attempts, I see consistent failure after a 30 minute timeout.

Example CDK Typescript code executed on a new AWS Account:
```typescript
import * as cdk from '@aws-cdk/core';
import { Duration, RemovalPolicy, Stack } from '@aws-cdk/core';
import { CfnConfigurationRecorder, CfnDeliveryChannel } from "@aws-cdk/aws-config";
import { Role, ServicePrincipal, PolicyStatement, Effect, CfnInstanceProfile, ManagedPolicy } from '@aws-cdk/aws-iam';
import { Bucket, BlockPublicAccess, BucketAccessControl, BucketEncryption, StorageClass } from '@aws-cdk/aws-s3';
import { Topic } from '@aws-cdk/aws-sns';

/**
 * The core network stack responsible for initializing
 * all integrated configuration management and tracking
 * resources attached to the AWS landing zone.
 *
 * @export
 * @class ConfigurationManagementStack
 * @extends {cdk.Stack}
 */
export class ConfigurationManagementStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    // Defines the Config Delivery Channel SNS Topic resource.
    const configDeliveryTopic = new Topic(this, 'ConfigSNSTopicDelivery', {});
    configDeliveryTopic.addToResourcePolicy(new PolicyStatement({
      effect: Effect.ALLOW,
      actions: ['SNS:Publish'],
      principals: [new ServicePrincipal('config.amazonaws.com')],
      resources: ['*']
    }))

    // Defines the Config Delivery Channel Bucket resource.
    const configDeliveryBucket = new Bucket(this, 'S3Config', {
      blockPublicAccess: BlockPublicAccess.BLOCK_ALL,
      accessControl: BucketAccessControl.LOG_DELIVERY_WRITE,
      encryption: BucketEncryption.S3_MANAGED,
      bucketName: 'foo-domain-example--us-east-1--config',
      removalPolicy: RemovalPolicy.DESTROY,
      versioned: true,
      lifecycleRules: [
        {
          id: 'Transition90dRetain7y',
          enabled: true,
          expiration: Duration.days(2555),
          transitions: [{
            storageClass: StorageClass.GLACIER,
            transitionAfter: Duration.days(90),
          }]
        }
      ],
    });

    // Defines the Config Recorder Role.
    const configRole = new Role(this, 'IAMConfigRecorderRole', {
      path: '/',
      roleName: 'IAMConfigRecorderRole',
      assumedBy: new ServicePrincipal('config.amazonaws.com'),
    });

    // Adds the Managed Policy 'AWSConfigRole' to the Config Recorder role.
    configRole.addManagedPolicy(ManagedPolicy.fromAwsManagedPolicyName('service-role/AWSConfigRole'));

    // Adds custom policy to the Config Recorder role.
    configRole.addToPolicy(new PolicyStatement({
      effect: Effect.ALLOW,
      actions: ['s3:GetBucketAcl'],
      resources: [configDeliveryBucket.bucketArn]
    }));

    // Adds custom policy to the Config Recorder role.
    configRole.addToPolicy(new PolicyStatement({
      effect: Effect.ALLOW,
      actions: ['s3:PutObject'],
      resources: [
        configDeliveryBucket.arnForObjects(`/AWSLogs/${Stack.of(this).account}/*`)
      ],
      conditions: {
        StringEquals: {
          's3:x-amz-acl': 'bucket-owner-full-control',
        }
      }
    }));

    // Adds custom policy to the Config Recorder role.
    configRole.addToPolicy(new PolicyStatement({
      effect: Effect.ALLOW,
      actions: ['config:Put*'],
      resources: ['*'],
    }));

    // Defines the Config Recorder Instance Profile.
    const configProfile = new CfnInstanceProfile(this, 'IAMConfigRecorderProfile', {
      roles: [ configRole.roleName ],
      instanceProfileName: 'IAMConfigRecorderProfile',
    });

    // Defines the Config Recorder resource.
    const configRecorder = new CfnConfigurationRecorder(this, 'ConfigRecorder', {
      roleArn: configRole.roleArn,
      name: 'ConfigRecorder',
    });
    
    // Defines the Config Delivery Channel resource.
    const configDeliveryChannel = new CfnDeliveryChannel(this, 'ConfigDefaultDeliveryChannel', {
      configSnapshotDeliveryProperties: {
        deliveryFrequency: 'Six_Hours',
      },
      s3BucketName: configDeliveryBucket.bucketArn,
      snsTopicArn: configDeliveryTopic.topicArn,
    });

  }
}
```

**Comment by mark-schaal** [comment]
Actually...on a second glance, even though this works as a raw CloudFormation template there should probably be access policies on both the S3 Bucket and the IAM Role. Might also be the case for the SNS Topic. I'll take a look, and if so I'll publish an example of things working.

**Comment by mark-schaal** [comment]
After deeper investigation, this looks like a configuration/example docs area. I was able to force both examples to list `InsufficientDeliveryPolicyException` as the root cause, and cross-referencing https://aws.amazon.com/premiumsupport/knowledge-center/config-console-error/ leads me to believe it is an issue with permissions either on the bucket policy or the role policies.

I'll see what I can produce as even now with adding policies to both the bucket and the role in alignment with the docs doesn't seem to produce a different outcome.

**Comment by rix0rrr** [comment]
There seems to be a sharp edge here regarding setup of AWS Config, and L2 constructs would probably help this. I'm repurposing this issue to be a feature request for AWS Config L2s.

Feel free to continue discussing and upvoting.

**Comment by skinny85** [comment]
We actually [do have AWS Config L2s already](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-config-readme.html#rules).

It's true that it doesn't support `DeliveryChannel`s yet though.

**Comment by jogold** [comment]
Related to #5181

**Comment by robbierolin** [comment]
I also ran into this circular dependency. Was able to fix it providing the DeliveryChannel and the ConfigurationRecorder the same dependency. 

e.g.
```
// Defines the Config Recorder resource.
const configRecorder = new CfnConfigurationRecorder(this, 'ConfigRecorder', {
  roleArn: configRole.roleArn,
  name: 'ConfigRecorder',
}).node.addDependency(configDeliveryBucket);

// Defines the Config Delivery Channel resource.
const configDeliveryChannel = new CfnDeliveryChannel(this, 'ConfigDefaultDeliveryChannel', {
  configSnapshotDeliveryProperties: {
    deliveryFrequency: 'Six_Hours',
  },
  s3BucketName: configDeliveryBucket.bucketName,
  snsTopicArn: configDeliveryTopic.topicArn,
}).node.addDependency(configDeliveryBucket);
```

**Comment by ashikMostofaTonmoy** [comment]
got any update?
