### ISSUE TITLE
.NET - Trying to pass Environment variables causes null pointer.

### ISSUE THREAD

**Issue by costleya** [aws/aws-cdk#3580]
* **I'm submitting a ...**
  - [X] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/aws/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
Trying to pass ANYTHING to an "Environment" throws a NullPointerException.

```csharp
var inputProcessor = new QueueProcessingFargateService(this, "InputProcessor", new QueueProcessingFargateServiceProps
            {
                Cluster = cluster,
                Image = ContainerImage.FromAsset("./whatever", null),
                Environment =
                {
                    {"QueueUrl", ."Hello"},
                }
            });
```

```csharp
var lambdafun = new Function(this, "LambdaFun", new FunctionProps
            {
                Handler = "x::x::Run",
                Runtime = Runtime.DOTNET_CORE_2_1,
                Timeout = Duration.Seconds(15),
                Code = Code.Asset("./x.zip"),
                MemorySize = 512,
                Environment =
                {
                   {"OutputBucket", "Hello" }
                }
            });
```

Results in:

```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at x.DemoStack..ctor(Construct scope, String name, IStackProps props) in C:\Users\costleya\Work\x\x\DemoStack.c
s:line 25
   at Demo.Program.Main(String[] args) in C:\Users\costleya\Work\x\x\Program.cs:line 12
```

Not passing in Environment, or initializing it to an empty Dictionary succeeds.

* **What is the expected behavior (or behavior of feature suggested)?**

I should be able to set environment variables.

This is a game-stopping bug.

* **What is the motivation / use case for changing the behavior or adding this feature?**

It makes the .NET CDK practically useless. I can use it for simple demos, but for real life code that needs information about the cloud infrastructure, it's very broken.

* **Please tell us about your environment:**

  - CDK CLI Version: 1.3.0 (build bba9914)
  - Module Version: 1.3.0-devpreview
  - OS: Windows 10
  - Language: .NET

**Comment by RomainMuller** [comment]
Attempting to understand where the NPE comes from, discovered that the following way does __not__ crash:

```c#
var env = new Dictionary<string, object>
{
    {"Key", "Value"}
};
var functionProps = new FunctionProps
{
    Handler = "foo.bar",
    Runtime = Runtime.NODEJS_10_X,
    Code = code,
    Environment = env
};
```

The key difference seems to be that initializing the dictionary inline seems to cause the issue.

**Comment by costleya** [comment]
I need to find some time to test, but this could just me making a coding mistake in my haste for a demo application.

```csharp
Environment = new Dictionary<string, object>
                {
                   {"OutputBucket", "Hello" }
                }
```

I bet this works.

**Comment by costleya** [comment]
The above works. The issue was indeed between seat and keyboard. Closing issue.
