### ISSUE TITLE
cfnAccessKey: Getting AccessKeyId and SecretAccessKeyId to output

### ISSUE THREAD

**Issue by codypenta** [aws/aws-cdk#3589]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [ ] :beetle: bug report
  - [x] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/aws/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*
I have a constraint where a word press plugin for attaching static content to AWS Cloudfront requires accesskey and accesskeyID. cfnAccessKey allows me to pull the secret key but not access key id.

* **What is the expected behavior (or behavior of feature suggested)?**
``` typescript
    const cfuser = new iam.User(this, "CFPluginUser", {
      userName: "CFPluginUser",
      managedPolicies: [
        { managedPolicyArn: "arn:aws:iam::aws:policy/CloudFrontFullAccess" }
      ]
    });
    const cfpluginak = new iam.CfnAccessKey(this, "CFPluginAccessKey", {
      userName: cfuser.userName,
    });

    new cdk.CfnOutput(this, "AccessKeyId", {
      value: cfpluginak.attrAccessKeyId // <-- This should work
    })

    new cdk.CfnOutput(this, "SecretAccessKeyId", {
      value: cfpluginak.attrSecretAccessKey
    });
```

* **What is the motivation / use case for changing the behavior or adding this feature?**
The ability to fully automate making users with programmatic access and logging outputs to the local computer. Unless you guys know a better way?

* **Please tell us about your environment:**

  - CDK CLI Version: 1.3.0 (build bba9914)
  - Module Version: ???
  - OS: [OSX Mojave ]
  - Language: [TypeScript]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

[Example Seen elsewhere but solution no longer works](https://github.com/aws/aws-cdk/issues/1612)

[Maybe a workaround from CloudFormation Docs?](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-iam-accesskey.html)
Return Values
Ref
When you pass the logical ID of this resource to the intrinsic Ref function, Ref returns the AccessKeyId. For example: AKIAIOSFODNN7EXAMPLE.

For more information about using the Ref function, see Ref.

**Comment by nmussy** [comment]
For your specific use-case, if your WordPress is hosted on an EC2 instance in your stack, and your plugin is able to handle it, you can use attach [an IAM role to the instance](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-ec2.html)

**Comment by codypenta** [comment]
Unfortunately, W3 Total Cache requires access keys because it does not make assumptions on which compute platform and/or CDN you choose to host your WordPress site. Using a role would have been nice though.

**Comment by eladb** [comment]
As the CloudFormation docs indicate, the access key ID is the intrinsic reference of the resource, so you need to use `ref` instead of `attrAccessKeyId`:

```ts
new cdk.CfnOutput(this, "AccessKeyId", {
  value: cfpluginak.ref
});
```

**Comment by Mistobaan** [comment]
an aliased attribute `attrAccessKeyId` with the well known name would have saved hours to billions of programmers world wide.
