### ISSUE TITLE
Unable to create VPC with only a public subnet

### ISSUE THREAD

**Issue by 0xdabbad00** [aws/aws-cdk#3591]
* **I'm submitting a ...**
  - [X] :beetle: bug report

* **What is the current behavior?**
In order to avoid the charges associated with a NAT Gateway ($32/mo even if not used), I wanted to have a VPC with only a public subnet.  At first, I attempted to create a VPC without a NAT Gateway.  Example:
```
const vpc = new ec2.Vpc(this, 'CloudMapperVpc', {
      maxAzs: 1,
      natGateways: 0
    });
```

This will result in the error:
```
CloudMapperVpc/PrivateSubnet1/DefaultRoute (CloudMapperVpcPrivateSubnet1DefaultRoute07CAC05D) Exactly one of [NatGatewayId, EgressOnlyInternetGatewayId, InstanceId, GatewayId, VpcPeeringConnectionId, NetworkInterfaceId, TransitGatewayId] must be specified and not empty
```

So then I tried to create a VPC with only a Public subnet:
```
const vpc = new ec2.Vpc(this, 'CloudMapperVpc', {
      maxAzs: 1,
      subnetConfiguration: [{name: 'CloudMapper', subnetType: ec2.SubnetType.PUBLIC}]
    });
```

This results in the error:
```
Error: There are no 'Private' subnets in this VPC. Use a different VPC subnet selection.
```

* **What is the expected behavior (or behavior of feature suggested)?**
Be able to create a VPC with only a public subnet and no NAT Gateway.

* **What is the motivation / use case for changing the behavior or adding this feature?**
I don't want to spend $32/mo on something I'm not using.

* **Please tell us about your environment:**

  - CDK CLI Version: 1.2.0
  - OS: OSX
  - Language: TypeScript

**Comment by 0xdabbad00** [comment]
Closing this as a duplicate of https://github.com/aws/aws-cdk/issues/1305

**Comment by capaj** [comment]
@0xdabbad00 was this fixed? I am trying to do the same and I am getting 
```
Error: There are no 'Isolated' subnet groups in this VPC. Available types: Deprecated_Private_NAT,Private,Deprecated_Private,Public
```
