### ISSUE TITLE
app-delivery expects yaml output, but cdk synth only outputs json

### ISSUE THREAD

**Issue by brucejcooper** [aws/aws-cdk#3595]
I'd like to report a simple bug in the app-delivery module.  I'm trying to use the app-deploy module to build and self-deploy a CDK app, just like in the documentation.  The problem is that the app-deploy model expects the built CFN to be in yaml format (see https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/app-delivery/lib/pipeline-deploy-stack-action.ts#L123), but running `node_modules/.bin/cdk synth -o dist` will only produce json output, no matter what options you supply.  

The only way I've been able work around the problem is to do a dodgey content redirect in the `buildspec.yml` file

      # When redirecting, the directory must exist before the command is run.
      # TODO remove when cdk bug is resolved.
      - mkdir -p dist

      # There is a bug in CDK whereby the cdk command generates json when using the 
      # -o option, but the app-deploy target expects yaml.  To work around this, we
      # do silly buggers with redirection of the stdout, which is yaml.
      - node_modules/.bin/cdk synth -o dist > dist/CodepipelineMetaStack.template.yaml

Whilst this makes it work, it isn't very elegant and its prone to output changes in the cdk executable.  Its trivial to fix, so I thought I'd raise this issue.

This is related to https://github.com/aws/aws-cdk/issues/2965 in that fixing that one would allow me to create a yaml file as part of a call to `cdk synth`.  You could either fix that bug, or change the linked file to expect json instead...

**Comment by eladb** [comment]
Since [JSON *is* YAML](https://eli.thegreenplace.net/2008/11/22/json-yaml-but-yaml-json) I am wondering what kind of error you have observed.

**Comment by caseyhoward** [comment]
The problem isn't with the contents of the file, it's with the name of the file. The error I see is "File [blah.template.yaml] does not exist in artifact [Artifact_Blah_Something]". It's looking for a file with the yaml extension but synth outputs a json extension. I'm really curious how this ever worked since it's hardcoded to look for yaml in the source code. Did "cdk synth" used to emit yaml?

**Comment by brucejcooper** [comment]
> Since [JSON _is_ YAML](https://eli.thegreenplace.net/2008/11/22/json-yaml-but-yaml-json) I am wondering what kind of error you have observed.

As casey suggests, its a file naming problem.

if you look at https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/app-delivery/lib/pipeline-deploy-stack-action.ts#L123, you'll see that the replace changeset action is expecting a file that ends in .yaml.  When the pipeline is built using the suggested command of `node_modules/.bin/cdk synth -o dist` the file that is created is `dist/{nameofstack}.template.json`. This causes the action to fail.  Simply changing the expected filename to .json will fix this.

**Comment by eladb** [comment]
Got it. Confirming this is a bug in the app-delivery library.

**Comment by eklinkhammer** [comment]
As a short term fix, I added this to my buildspec:
`- find dist/ -name '*.template.json' -exec rename 's/\.json$/.yaml/' \{} \;`
