### ISSUE TITLE
CloudFrontWebDistribution external import method missing

### ISSUE THREAD

**Issue by nbaillie** [aws/aws-cdk#3606]
CloudFrontWebDistribution currently does not have an external import method like S3 and Repository.

my thought is that it should support something like:
`cloudfront.CloudFrontWebDistribution.from_distribution_arn(self,<ID>,<ARN>)`

**Comment by nmussy** [comment]
I'm going to make a PR for it 👍

**Comment by oleksandr-yefremov** [comment]
Is there any other way to import `CloudFrontWebDistribution` currently? I am missing this API

**Comment by iliapolo** [comment]
duplicate of https://github.com/aws/aws-cdk/issues/5607
