### ISSUE TITLE
Add S3 Bucket AliasRecordTarget for Route53

### ISSUE THREAD

**Issue by kadishmal** [aws/aws-cdk#3616]
* **I'm submitting a ...**
  - [ ] :beetle: bug report
  - [x] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/aws/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the expected behavior (or behavior of feature suggested)?**

Currently there is alias record target only for CloudFormation distribution to be used as follows:

```
const recordSetCommonProps: RecordSetProps = {
  recordName: wwwDomain,
  recordType: RecordType.A,
  target: RecordTarget.fromAlias(new CloudFrontTarget(cfDistribution)),
  zone: hostedZone
};
```

I need to point the alias record to an S3 bucket which is configured to serve a Web site.

* **What is the motivation / use case for changing the behavior or adding this feature?**

Need to point the root domain to an S3 bucket which serves a static Web site content.

* **Please tell us about your environment:**

  - CDK CLI Version: 1.3.0
  - Module Version: 1.3.0
  - OS: OSX Mojave
  - Language: TypeScript

**Comment by nmussy** [comment]
Thanks for opening on issue, I'm on it 👍

**Comment by eladb** [comment]
@nmussy we will probably need to hard code the zone Ids per region as part of the region-info library.

**Comment by nmussy** [comment]
I was going to inline it in `route53-targets`. I'll look into `region-info`, thanks
