### ISSUE TITLE
Modify the BlockDeviceMappings in AutoScalingGroup construct

### ISSUE THREAD

**Issue by tp6m4fu6250071** [aws/aws-cdk#3620]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [ ] :beetle: bug report
  - [x] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/aws/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*
The current AutoScalingGroup construct cannot be modified the BlockDeviceMappings of it. 
https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_autoscaling/AutoScalingGroup.html

* **What is the expected behavior (or behavior of feature suggested)?**
Sometimes, we need to add or modify the block devices. As in CfnLaunchConfiguration, there's a parameter "block_device_mappings" can modify it. I submit this feature request to have a parameter in the AutoScalingGroup construct.
https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_autoscaling/CfnLaunchConfiguration.html

* **What is the motivation / use case for changing the behavior or adding this feature?**
To add the other block device on instances which is created by ASG.

* **Please tell us about your environment:**

  - CDK CLI Version: xx.xx.xx
  - Module Version: 1.3.0
  - OS: [ OSX Mojave ]
  - Language: [ Python ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

**Comment by nmussy** [comment]
Both [BlockDevice](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-launchconfig-blockdev-mapping.html) and [BlockDeviceMapping](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-launchconfig-blockdev-mapping.html) seem to be missing. Should I open a separate issue for the former?
