### ISSUE TITLE
Documentation error (Python)

### ISSUE THREAD

**Issue by briannd81** [aws/aws-cdk#3623]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [ ] :beetle: bug report

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*

The code, handler and runtime of the Function class should have been documented as keyword arguments, not positional.
``` py
class aws_cdk.aws_lambda.Function(scope, id, *, code, handler, runtime, allow_all_outbound=None, dead_letter_queue=None, dead_letter_queue_enabled=None, description=None, environment=None, events=None, function_name=None, initial_policy=None, layers=None, log_retention=None, memory_size=None, reserved_concurrent_executions=None, role=None, security_group=None, timeout=None, tracing=None, vpc=None, vpc_subnets=None)
```

* **What is the expected behavior (or behavior of feature suggested)?**

The documentation said the code, handler and runtime of the `Function` class are positional arguments, but they should be keyword. Would get a runtime error when passing the params are positional.

* **What is the motivation / use case for changing the behavior or adding this feature?**

Improve documentation accuracy.

* **Please tell us about your environment:**

  - CDK CLI Version: 1.3.0 (build bba9914)
  - Module Version: xx.xx.xx
  - OS: Windows 10
  - Language: Python

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

**Comment by garnaat** [comment]
The documentation does show the `code`, handler`, and `runtime` arguments as keyword args.  The `*` after the `id` argument means all arguments following the `*` are keyword arguments.  Those arguments are still required, though, which is why they don't have a `=None` clause.

See [PEP3102](https://www.python.org/dev/peps/pep-3102/) for more details on the bare asterisk syntax.
