### ISSUE TITLE
Feature suggestion for ECS Patterns: Time based service scaling construct

### ISSUE THREAD

**Issue by nathanpeck** [aws/aws-cdk#3638]
The pattern for creating a service that scales according to a time schedule is quite complicated, requiring at least two CloudWatch Events and a Lambda function: https://aws.amazon.com/premiumsupport/knowledge-center/ecs-time-based-scaling/

This would make a nice pattern in ecs-patterns to more easily abstract the creation of a service that can scale down during the night but scale up during business hours

**Comment by jogold** [comment]
This could be partially addressed by first implementing an `AwsLambda` event target as suggested in #2538. I plan to work on this maybe next week.

**Comment by rix0rrr** [comment]
Why does the scheduled scaling that Application AutoScaling support not suffice?

https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-applicationautoscaling.ScalableTarget.html#scale-wbr-on-wbr-scheduleid-action

**Comment by jogold** [comment]
I think that only target tracking and step scaling are supported via Application Auto Scaling for the moment: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/service-auto-scaling.html

**Comment by nathanpeck** [comment]
Actually it looks from the AWS Auto Scaling docs like ECS services are also supported, so it should be possible with the default Application AutoScaling. There is an example in the official docs for the commandline:

```
aws application-autoscaling put-scheduled-action --service-namespace ecs \
  --scalable-dimension ecs:service:DesiredCount \
  --resource-id service/default/web-app \
  --scheduled-action-name my-one-time-action \
  --schedule "at(2019-01-31T17:00:00)" \
  --scalable-target-action MaxCapacity=10
```

**Comment by pkandasamy91** [comment]
This is actually pretty easy to do with an extra couple lines. Not sure a new construct would be valuable here, an example in the examples repo as well as the README might be enough. Thoughts?

**Comment by pkandasamy91** [comment]
Added to README: https://github.com/aws/aws-cdk/pull/5079
