### ISSUE TITLE
Can't import existing Ecs Cluster

### ISSUE THREAD

**Issue by ulf5** [aws/aws-cdk#3655]
* **I'm submitting a ...**
  - [ ] :beetle: bug report
  - [x] :rocket: feature request
  - [x] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/aws/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*
There is no classmethod on Cluster (ecs) for importing an existing cluster.

* **What is the expected behavior (or behavior of feature suggested)?**
Be able to import a Cluster from only a cluster_name or cluster_arn.

* **What is the motivation / use case for changing the behavior or adding this feature?**
I have a bunch of smaller ECS services that share a cluster (to save resources) these are defined in different repos. I don't see why I should need to create a cluster for each specific one. Maybe I am thinking about this wrong? I'm very open to hearing a solution. I mean I know I can just use the Cfn stuff, but it seems the benefit of only using them is not as big.

* **Please tell us about your environment:**

  - CDK CLI Version: 1.3.0
  - Module Version: 1.4.0
  - OS: Linux
  - Language: Python

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)
I'd like a Cluster.from_arn or something that just lets me import an existing cluster.

**Comment by nmussy** [comment]
Hi @ulf5,

There's already a [`Cluster.fromClusterAttributes`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs.Cluster.html#static-from-cluster-attributesscope-id-attrs) static method, or [`Cluster.from_cluster_attributes` in Python](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_ecs/Cluster.html#aws_cdk.aws_ecs.Cluster.from_cluster_attributes).

You can see a TypeScript example in the ECS test suite:

https://github.com/aws/aws-cdk/blob/24ebec8b0cb62da038711f5dd6a7030be441954d/packages/%40aws-cdk/aws-ecs/test/test.ecs-cluster.ts#L930-L939

Hope that's what you're looking for!

**Comment by ulf5** [comment]
Hi @nmussy, thanks for the response!
That requires me to know vpc and security groups, and also the documentation says it creates a new cluster if I'm not reading it wrong.

**Comment by nmussy** [comment]
You can use the [`Vpc.from_lookup`](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_ec2/Vpc.html#aws_cdk.aws_ec2.Vpc.from_lookup) and [`Vpc.from_vpc_attributes`](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_ec2/Vpc.html#aws_cdk.aws_ec2.Vpc.from_vpc_attributes) methods to retrieve your VPC, as well as [`SecurityGroup.from_security_group_id`](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_ec2/SecurityGroup.html#aws_cdk.aws_ec2.SecurityGroup.from_security_group_id) for your security groups.

I've used that method to share a cluster between small ECS stacks, and it works great 👍 

Can I ask what made you thought this would create a new cluster?

**Comment by ulf5** [comment]
This is what the classmethod for VPC says:

> Import an existing VPC from by querying the AWS environment this stack is deployed to.

This is what the classmethod for Cluster says:

> This method adds attributes from a specified cluster to this cluster.

To me this reads like it will create a new Cluster with attributes from an old one.

I guess this is a solution then, thank you, but I would've preferred to not have to look up the Vpc id and security group ids as this is not something that I need to do if I use CF for this use case.

**Comment by nmussy** [comment]
Oh, I see. I will make a PR to clarify that description, thanks!

**Comment by ivawzh** [comment]
@nmussy how do you export `cluster.connections.securityGroups` to Cfn Outputs via CDK?
