### ISSUE TITLE
option for LoadBalancedFargateService with NLB to specify different listener port

### ISSUE THREAD

**Issue by pahud** [aws/aws-cdk#3666]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [ ] :beetle: bug report
  - [x] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/aws/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*

The `LoadBalancedFargateService` class has no option to specify different ELB listerner port other than `80`

https://github.com/aws/aws-cdk/blob/77671ad4f76dadca7810ed0ee797a7b8210fb30f/packages/%40aws-cdk/aws-ecs-patterns/lib/fargate/load-balanced-fargate-service.ts#L50

And we need to addPropertyOverride() like this:

![圖片](https://user-images.githubusercontent.com/278432/63069065-1c9b4880-bf48-11e9-82cf-7792df393274.png)

* **What is the expected behavior (or behavior of feature suggested)?**

Provide a `loadBalancerListenerPort` property in [LoadBalancedFargateServiceProps](https://github.com/aws/aws-cdk/blob/77671ad4f76dadca7810ed0ee797a7b8210fb30f/packages/%40aws-cdk/aws-ecs-patterns/lib/fargate/load-balanced-fargate-service.ts#L60)

* **What is the motivation / use case for changing the behavior or adding this feature?**

Fargate service running as TCP service behind NLB could have listener other than 80 on the NLB. For example,  NLB:8888 to containerPort:8888 on Fargate.

* **Please tell us about your environment:**

  - CDK CLI Version: 1.4.0 (build 175471f)
  - Module Version: 1.4.0
  - OS: OSX Mojave
  - Language: TypeScript

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

**Comment by SoManyHs** [comment]
This should be addressed in https://github.com/aws/aws-cdk/pull/4213, please let us know if this works for you! @pahud
