### ISSUE TITLE
[Question] Account ID retrieval 

### ISSUE THREAD

**Issue by mdere-unbound** [aws/aws-cdk#3673]
This is more of a question, but not sure where this will go.

 noticed when I did this.account  in my stack component -  I get the following: `${Token[AWS::AccountId.0]}` - so we wont be able to actually get the string of the account?

The reason I'm asking this question is because my company I work for has multiple different accounts and wants me to build out an alarmStack that builds out the same alarms across all accounts, BUT - each ELB / Target Groups and etc has different names associated to it - so my approach was to see if I can take advantage of doing a comparison of a pre mapped config of my alarm configurations based on each account_id - but since I am only getting the above value - there is no way for me to do that comparison for when I switch accounts.

Thoughts?

**Comment by skinny85** [comment]
Hey @mdere-unbound ,

if you create your Stack passing a concrete account to the `env` property (so, `new Stack(app, 'MyStack', { account: '123456789012' }`), then `myStack.account` will return it (`'123456789012'` in this case).

Thanks,
Adam
