### ISSUE TITLE
Nice to be able to deploy multiple containers via LoadBalancedFargateService

### ISSUE THREAD

**Issue by realharry** [aws/aws-cdk#3674]
* **I'm submitting a ...**
  - [ ] :beetle: bug report
  - [x] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/aws/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*

You can deploy only one docker image when you are using `ecsPatterns.LoadBalancedFargateService`

* **What is the expected behavior (or behavior of feature suggested)?**

It'll be nice to be able to deploy multiple images (a la docker-compose) within a service. 

ESC-CLI, for example, currently provides a way to include multiple container images through a docker-compose file.

* **What is the motivation / use case for changing the behavior or adding this feature?**

Make the API, `LoadBalancedFargateService`, more useful.

* **Please tell us about your environment:**

  - CDK CLI Version: 1.4.0 (build 175471f)
  - Module Version: 1.4.0
  - OS: OSX Mojave
  - Language: TypeScript

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

* https://github.com/aws/amazon-ecs-cli

**Comment by NGL321** [comment]
Hey @realharry,

This seems like a great set of functionality to include. I dont think we need to wait for Cloudformation to catch up to work on this either!

Someone will update the issue here if we either need for info, or have an update.

In the meantime, if you feel this is something you can contribute to the codebase, please feel free to put in a Pull Request.
😸

**Comment by pkandasamy91** [comment]
@realharry you can actually add multiple containers after constructing the LoadBalancedFargateService by using the addContainer method within a taskDefinition. 

It would look something like:
```ts
const service = new LoadBalancedFargateService(...)
service.taskDefinition.addContainer(containerName, {
    image: new ecs.AssetImage(path.join(__dirname, '..', 'demo-image'))
})

```

**Comment by realharry** [comment]
Cool. Let me try that. Thanks!!

**Comment by pkandasamy91** [comment]
@realharry Updated my explanation above, hope that helps!

**Comment by pkandasamy91** [comment]
@realharry did this resolve your issue?

**Comment by pkandasamy91** [comment]
Resolving the issue, please feel free to reopen it if you still have questions.

**Comment by jgoux** [comment]
Hello @piradeepk and thanks for the `addContainer` tip.

Initially I wanted to use a docker-compose.yaml containing two services. I use depends_on and service_healthy to start one service only when the other is up. Seems like your solution doesn't cover such use case.

Also, only one of the two services needs to be exposed to the ALB.

Can the current API handle my use case?
