### ISSUE TITLE
Cannot use Ubuntu when creating Cloud9 EC2 environment.

### ISSUE THREAD

**Issue by realharry** [aws/aws-cdk#3678]
* **I'm submitting a ...**
  - [ ] :beetle: bug report
  - [ ] :rocket: feature request
  - [x] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/aws/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*

The API, https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cloud9.CfnEnvironmentEC2.html, does not provide a way to select Ubuntu as a platform when creating a Cloud9 EC2 environment.

```javascript
  private buildCloud9Environment = (envId: string): cloud9.CfnEnvironmentEC2 => {
    const c9 = new cloud9.CfnEnvironmentEC2(this, envId, {
      name: envId,
      description: 'For accessing staging stack',
      subnetId: this._vpcSubnet,
      instanceType: 't2.small',
      automaticStopTimeMinutes: 30,
    });
    return c9;
  }
```

* **What is the expected behavior (or behavior of feature suggested)?**

One should be able to choose Amazon Linux vs Ubuntu.

* **What is the motivation / use case for changing the behavior or adding this feature?**

I'm more familiar with Debian flavors of Linux.

* **Please tell us about your environment:**

  - Language: TypeScript

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

**Comment by nmussy** [comment]
Hey Harry,

I'm not very familiar with Cloud9, would you be able to find a way to set the AMI outside the Admin Console? A blog post from earlier this year and [developer guide](https://docs.aws.amazon.com/cloud9/latest/user-guide/ami-contents.html) mention Ubuntu, but I can't find how to set it, either in the [SDK](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Cloud9.html) or the [CloudFormation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloud9-environmentec2.html) specs.

**Comment by realharry** [comment]
Hi @nmussy You can choose Ubuntu vs Amazon Linux when you create a Cloud9 environment via Console (it's called "Platform" in the UI), but I don't see that option in the SDK or even in the CF docs, as you say. I marked the ticket as "GAP" because it's probably missing in CDK as well as in the underlying CF API.

**Comment by nmussy** [comment]
Unfortunately, the CDK can only generate CloudFormation templates.

You can request this feature in the [aws-cloudformation-coverage-roadmap](https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues), but seen as it's not even in the SDK, I would open a topic in the [AWS Forums](https://forums.aws.amazon.com/forum.jspa?forumID=268). I did a quick search, and it doesn't seem that either have had your issue raised.

**Comment by NGL321** [comment]
Hi @realharry!

Thank you for reaching out. Unfortunately, @nmussy is correct, and this is not a feature that is supported by Cloudformation. This makes it difficult for us to implement, and so we typically wait for Cloudformation coverage.

I have put in a ticket to the Cloudformation team regarding this and will update this issue when I can.
😸

**Comment by realharry** [comment]
Great! Thanks very much, @NGL321 @nmussy. Have a wonderful Friday!!

**Comment by shivlaks** [comment]
@realharry @nmussy @NGL321 

I also added the issue to the [cloudformation-coverage-roadmap](https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/129)

Feel free to +1, add any context!
