### ISSUE TITLE
Stack deploy with stack dependencies fails unnecessarily the second time

### ISSUE THREAD

**Issue by PeterBengtson** [aws/aws-cdk#3683]
* **I'm submitting a ...**
  - [x] :beetle: bug report

* **What is the current behavior?**

I have a CDK application which consists of two stacks: `BaseDev` and `Dev`. `BaseDev` defines basic things then used by `Dev`. Very standard.

The problem is that once deployed, `BaseDev` and `Dev` can't be deployed again: CDK first tries to update `BaseDev`, then suddenly reports that `BaseDev` can't be updated since there are other stacks depending on it even though there are no changes whatsoever to any of the stacks. 

Thus one's left in a situation where _no_ stack can be updated. The only way of updating `Dev` is by tearing `Dev` down and recreating it: the nonexistent changes to `BaseDev` won't allow anything dependent on it to be redeployed. The same thing goes for `BaseDev`, which can't be updated unless `Dev` first is removed entirely, even though there are no changes to any of the stacks.

This is the structure of the project: The stack `BaseDev` contains the following structure for the custom Lambda layer:

<img width="230" alt="Screenshot 2019-08-16 at 14 24 45" src="https://user-images.githubusercontent.com/3897/63168936-ce647300-c035-11e9-9f2d-dfbe934faa6b.png">

The `package.json` file looks like this:

<img width="768" alt="Screenshot 2019-08-16 at 14 25 16" src="https://user-images.githubusercontent.com/3897/63168958-df14e900-c035-11e9-91d7-0ea4d9664447.png">

`BaseDev` also contains the following definition to create the custom Lambda layer:

<img width="520" alt="Screenshot 2019-08-16 at 14 25 46" src="https://user-images.githubusercontent.com/3897/63169018-09ff3d00-c036-11e9-9357-b60d433efcb2.png">

So far, so good. When running `yarn`, things get installed as expected:

<img width="627" alt="Screenshot 2019-08-16 at 14 28 25" src="https://user-images.githubusercontent.com/3897/63169068-2602de80-c036-11e9-8573-b8328b30d8ac.png">

And a first install, of `Dev`, which also first installs `BaseDev`, succeeds as it should:

<img width="337" alt="Screenshot 2019-08-16 at 14 33 31" src="https://user-images.githubusercontent.com/3897/63169118-4763ca80-c036-11e9-9717-c64a975ae76f.png">

If we try to repeat the process, however:

<img width="337" alt="Screenshot 2019-08-16 at 14 33 31" src="https://user-images.githubusercontent.com/3897/63169354-e38dd180-c036-11e9-94c1-5b34a7e94487.png">

Then we get the following error:

<img width="1111" alt="Screenshot 2019-08-16 at 14 38 11" src="https://user-images.githubusercontent.com/3897/63169395-0324fa00-c037-11e9-9f21-be11aef8b773.png">

Note that CDK first tries to redeploy `BaseDev`, as `Dev` depends on it. This is as it should be, but the deploy shouldn't fail.

If I try to deploy only `BaseDev`, the result is the same:

<img width="1105" alt="Screenshot 2019-08-16 at 14 32 46" src="https://user-images.githubusercontent.com/3897/63169463-2780d680-c037-11e9-94fe-e8e3f564be77.png">

* **What is the expected behavior (or behavior of feature suggested)?**

This should just work, and it normally does when dealing with CloudFormation. It's to be expected that a changed `BaseDev` can't be updated, as this requires all stacks dependent on it also to be redeployed. 

Two things:

1. There are no changes to the `BaseDev` code. However, the lambda layer asset seems to be renewed all the time even though no changes to the layer have been done, which might be the cause.

2. CDK does, for a given stack, have full knowledge of what depends on it. Thus it would be entirely within the bounds of possibility that dependent stacks could be redeployed automatically. CF can't do this, but CDK could.

* **Please tell us about your environment:**

  - CDK CLI Version: 1.4.0
  - OS: all
  - Language: all

**Comment by nog642** [comment]
Why was this marked as completed? Was it actually implemented?
