### ISSUE TITLE
Can't let CDK create roles

### ISSUE THREAD

**Issue by pepastach** [aws/aws-cdk#3685]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [ ] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/aws/aws-cdk/security/policy)
  - [x] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
I'm deploying CDK apps in GitLab CI/CD pipeline under a deployer role. CDK creates roles (task roles, execution roles etc.) and attaches policies. So the deployer role should have permissions to create new roles. But that's insecure. If gitlab's credentials leak, an attacker can assume the role as gitlab does, create a new role, attach admin policy and become admin quite easily.

* **What is the expected behavior (or behavior of feature suggested)?**
I'd like to create all the roles prior to CDK deployment in gitlab CI/CD. Most constructs support passing a role, but I'm currently fighting with lambda log retention. If I create a lambda function and set log retention, CDK creates another nodejs lambda for that. But I can't figure out how to pass my own role to the log retention lambda.

I tried writing an Aspect (it's really a guess), but CDK is giving me the following error:
```
TypeError: Don't know how to convert object to JSON: <cdk_infra.my_stack.ReplaceLoggingLambdaRoleAspect object at 0x1136e9b90>
```

```python
class ReplaceLoggingLambdaRoleAspect(core.IAspect):
    def __init__(self, parent_construct: core.Construct) -> None:
        super().__init__()
        self.parent_construct = parent_construct

    def visit(self, node: core.IConstruct) -> None:
        if isinstance(node, aws_lambda.SingletonFunction):
            for idx, pn in enumerate(node.permissions_node.children):
                if isinstance(pn, aws_iam.Role):
                    node.permissions_node.children[idx] = aws_iam.Role.from_role_arn(
                        scope=self.parent_construct,
                        id='LogRetentionServiceRole',
                        role_arn=core.Fn.import_value('custom-log-retention-role-arn')
                    )
```

Any help would be greatly appreciated. Thanks!

* **What is the motivation / use case for changing the behavior or adding this feature?**
Improving security by not letting CDK create any roles.

* **Please tell us about your environment:**

  - CDK CLI Version: 1.4.0
  - Module Version: 1.4.0
  - OS: OSX Mojave
  - Language: Python

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

**Comment by slipdexic** [comment]
I agree with you on this, from an enterprise or customers in regulated space, healthcare, pci-dss, ISO27001/etc. You have to have separation on duties and the IAM policies will be presented by another team.

In respect of your issues, one thing you can use are IAM permission boundaries. These  allow you to scope the maximum permission a role can assume /what they can do

https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_boundaries.html

**Comment by pepastach** [comment]
Than you @slipdexic 
I considered IAM permission boundary, but couldn't find out how to specify a condition on `PolicyDocument` field in `iam:PutRolePolicy` action. Since the document can either be a JSON or a YAML, it might be impossible to exactly specify, that CDK can only put the following policies: `logs:PutRetentionPolicy` and `logs:DeleteRetentionPolicy`.

It's simple with `iam:AttachRolePolicy` where I can easily specify role names. But CDK uses `iam:PutRolePolicy`....

The more I'm thinking about it, the more it looks like I can't use log retention for lambdas. We may end up create our own log retention lambdas.

**Comment by jogold** [comment]
I've developed the `LogRetention` construct, will have a look to fix this.

**Comment by RomainMuller** [comment]
An alternate way to get log retention for your lambdas is to:
1. Not give Lambda permissions to create log groups
2. Create a log group with the desired retention in CDK, using the appropriate name

The downsides of this (and why we haven't done this in the CDK) is that if an execution triggers before the log group is created in this setup, this executions logging statements will be lost forever... If that's acceptable for you, you may not have to do much more magic than that :)
