### ISSUE TITLE
Cloud9 environment for contributors

### ISSUE THREAD

**Issue by rhboyd** [aws/aws-cdk#3686]
* **I'm submitting a ...**
  - [ ] :beetle: bug report
  - [X] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/aws/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
It would be super dope if there were a cloudformation template quick-launch that spun up a cloud9 environment with all of the cdk dev dependencies (for contributing to cdk) to give new contributors a turn-key experience to start on their first contribution.

* **What is the expected behavior (or behavior of feature suggested)?**
a link on the CONTRIBUTING.md document that would launch a cfn template to create a cloud9 dev environment with all the dependencies installed.

* **What is the motivation / use case for changing the behavior or adding this feature?**
It would be very nice for new users <3

**Comment by shivlaks** [comment]
Is there a lot of friction with getting started? It does sound pretty cool to have a turn-key getting started as a contributor experience.

I'm also wondering what the free tier eligible `t2.micro` experience is like from a development perspective. Any idea what that might look like? Finally, Cloud9 is only available in a handful of regions, although that's something I would expect to change over time (if that matters).

**Comment by rix0rrr** [comment]
Yep, this is a great idea. We would need to hack it though, afaik Cloud9 has no way to run "startup commands" so we can't provision a C9 workspace with enough preconfiguration.

**Comment by rhboyd** [comment]
My plan was to use the SSH Environment setup so CDK creates a VPC/EC2 instance then dumps the C9 client onto the host during user-data script

**Comment by eladb** [comment]
Contribution guide should have sufficient info on how to set up a Cloud 9 environment. @rhboyd do you think we need additional information?

**Comment by rhboyd** [comment]
I think the docker build has removed a lot of the friction. The only pain points remaining are un/reinstalling Typescript and linking against the local build, both are easily solved once you’ve done it a few times but aren’t intuitive to new users.

For linking, the contributor guide covers how to set it up but if I then want to create a sample app to test user experience and run “CDK synth” I get an error about the CDK version and I have to know to use the full path to the CDK CLI in my aws-cdk working directory.

Perhaps one of the CDK DAs can pick up a task to create something like cdkworkshop.com but focusing on contributors instead of consumers. Covering the linting process, specifying linter rules, overrides, etc... the types of tests we expect (integ and unit), the snippets we parse for documentation, and probably a few other topics I’m forgetting.
