### ISSUE TITLE
Failure when renaming an EC2 instance profile

### ISSUE THREAD

**Issue by mikemcmaster** [aws/aws-cdk#3687]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] :beetle: bug report

* **What is the current behavior?**
1. Define CDK code (I'm using Python) that creates an EC2 instance profile (defining the instance profile name) well as an EC2 instance that uses it. Deploy it.
2. Change the instance profile's name. Attempt to deploy it.

Here's a partial code sample:

```
wordpress_instance_profile = iam.CfnInstanceProfile(
    self, "InstanceProfile",
    roles=[wordpress_role.role_name], # Defined outside this code sample
    instance_profile_name="WordPressInstanceProfile"
)
wordpress_ec2_instance = ec2.CfnInstance(
    self, "WordPressInstance",
    iam_instance_profile=wordpress_instance_profile.instance_profile_name,
    image_id=wordpress_ami_id,
    instance_type="c5.large",
    key_name="my-key-name",
    monitoring=True,
    security_group_ids=[wordpress_sg.security_group_id],
    subnet_id=vpc.public_subnets[0].subnet_id,
    tags=[core.CfnTag(key="Name", value=f"WordPress-{env}")]
)
```

I deployed that, then modified `wordpress_instance_profile.instance_profile_name`:

```
wordpress_instance_profile = iam.CfnInstanceProfile(
    self, "InstanceProfile",
    roles=[wordpress_role.role_name],
    instance_profile_name="WordPressInstanceProfile-foo"
)
```

* **What is the expected behavior (or behavior of feature suggested)?**

As `cdk diff` explains, I'd expect the EC2 instance profile to be replaced, and the EC2 instance updated accordingly.

```
(.env) mike@mike-mbp-2 ~/P/my-project-cfn> cdk diff my-project-cfn --profile insider
Stack my-project-cfn
Resources
[~] AWS::IAM::InstanceProfile InstanceProfile InstanceProfile replace
 └─ [~] InstanceProfileName (requires replacement)
     ├─ [-] WordPressInstanceProfile
     └─ [+] WordPressInstanceProfile-foo
[~] AWS::EC2::Instance WordPressInstance WordPressInstance 
 └─ [~] IamInstanceProfile
     ├─ [-] WordPressInstanceProfile
     └─ [+] WordPressInstanceProfile-foo
```

When deploying, I get an error:

```
(.env) mike@mike-mbp-2 ~/P/my-project-cfn> cdk deploy my-project-cfn --profile insider
my-project-cfn: deploying...
my-project-cfn: creating CloudFormation changeset...
 0/3 | 9:20:39 AM | UPDATE_IN_PROGRESS   | AWS::EC2::Instance                          | WordPressInstance 
 1/3 | 9:20:39 AM | UPDATE_FAILED        | AWS::EC2::Instance                          | WordPressInstance Value (WordPressInstanceProfile-foo) for parameter iamInstanceProfile.name is invalid. Invalid IAM Instance Profile name (Service: AmazonEC2; Status Code: 400; Error Code: InvalidParameterValue; Request ID: 0e877c7d-fe71-4c44-880f-a1ed4173924e)
```

It's as if the CloudFormation to replace the instance profile was skipped, and it went directly to updating the EC2 instance (which, of course, fails).

* **What is the motivation / use case for changing the behavior or adding this feature?**

I wanted to rename the instance profile to something more meaningful so it doesn't conflict with another stack instance.

* **Please tell us about your environment:**

  - CDK CLI Version: 1.4.0
  - OS: OSX Mojave
  - Language: Python

**Comment by rix0rrr** [comment]
Looks like there's an ordering issue here. Can you paste the CloudFormation that is getting generated?

**Comment by SomayaB** [comment]
> Looks like there's an ordering issue here. Can you paste the CloudFormation that is getting generated?

@mikemcmaster

**Comment by rix0rrr** [comment]
Closing for lack of response.
