### ISSUE TITLE
Cached content in cdk.context.json prevents the stack from being properly deployed

### ISSUE THREAD

**Issue by realharry** [aws/aws-cdk#3688]
* **I'm submitting a ...**
  - [x] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/aws/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*

1. Create a stack using CDK.
1. Deploy it to one account/region, say, `account1` and `region1`.
1. Do something else (or modify the CDK app, or change some stacks via AWS console, etc.), and you forget you worked on one account/region.
1. Then, change account/region to a different account/region, say `account1` and `region2`.
1. Rebuild and `cdk synth`.
1. Try `cdk deploy`, and notice "sometimes" it mysteriously fails even though everything was properly configured for `account1` and `region2`.

As it turned out, the cached content for `account1` and `region1`, in cdk.context.json, threw error during `cdk deploy` even when we were only deploying to  `account1` and `region2`.

* **What is the expected behavior (or behavior of feature suggested)?**

I don't know what the purpose of cdk.context.json is. but either it should not keep old content when we are targeting a different target stack, or it should not try to validate the stale content which has little to do with the current deploy action.

* **What is the motivation / use case for changing the behavior or adding this feature?**

I ended up spending the whole day trying to figure out a mysterious bug yesterday. Any "hidden" content (I presume, cdk.context.json is auto-generated) should not affect/interfere with any actions that developers want to accomplish as expressed via the code/config.

* **Please tell us about your environment:**

  - CDK CLI Version: 1.4.0 (build 175471f)
  - Module Version: 1.3.0
  - OS: OSX Mojave
  - Language: TypeScript

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

**Comment by SomayaB** [comment]
Hi @realharry, thanks for bringing this to our attention. We will look into it and get back to you. In the meantime, [here](cdk.context.json) is a merged PR with more information about the cdk.context.json file.

**Comment by shivlaks** [comment]
@SomayaB - that link appears to be broken...

**Comment by shivlaks** [comment]
@realharry - I don't believe this is an issue. We did have a bug where we were erroneously merging some keys that were in`cdk.json` into `cdk.context.json`. I tried going through the repro steps with a couple of versions and have not run into any issues and I was not able to reproduce step no. 6

> Try cdk deploy, and notice "sometimes" it mysteriously fails even though everything was properly configured for account1 and region2.

I'm resolving this issue as we have not seen any additional activity in a while. Feel free to reopen if you're still experiencing it and we can pick it up again with some refreshed reproduction steps.

**Comment by realharry** [comment]
Hi @shiv yes, I agree. I don't see this issue any more. Thanks!
