### ISSUE TITLE
ecs-patterns: Enable load balancer subnet configuration in load balanced constructs

### ISSUE THREAD

**Issue by sonofachamp** [aws/aws-cdk#3691]
### General Information

* [ ] :wave: I may be able to implement this feature request

* [ ] :warning: This feature might incur a breaking change 

### Description
Enable consumers of load balanced constructs in `ecs-patterns` library to specify which VPC subnets to associate to their load balancer.

### Proposed Solution
Expose load balancer properties via the load balancer properties interface.

### Environment

  - **CDK CLI Version:** 1.3.0 (build bba9914)
  - **Module Version:** ecs-patterns 1.4.0
  - **OS:** all
  - **Language:** all

### Other information 

#3626

**Comment by bgdnlp** [comment]
As an easier solution, a parameter that takes a load balancer arn or object as input would allow both using an existing load balancer defined somewhere else (#3737) and simply creating a load balancer with the desired properties just before calling LoadBalancedFargateService() or LoadBalancedEc2Service().

**Comment by pkandasamy91** [comment]
Closing this feature request in favour of #3737
