### ISSUE TITLE
[ec2] build out RouterTables L2 Contructs

### ISSUE THREAD

**Issue by slipdexic** [aws/aws-cdk#3702]
### General Information

* [X] :wave: I may be able to implement this feature request

* [ ] :warning: This feature might incur a breaking change 

### Description
Build out the missing RouterTables, Route, and SubnetRouteTableAssociation

### Proposed Solution
Implement the basic L2 contructs (classes)
These are implemented the  same way as NetworkAcl's are which is inverse for SecurityGroups

### Environment

  - **CDK CLI Version:** 1.4.0
  - **Module Version:** 
  - **OS:** all
  - **Language:** all

**Comment by rix0rrr** [comment]
Related to https://github.com/aws/aws-cdk/issues/5927
