### ISSUE TITLE
VPC with only private subnet fails with error

### ISSUE THREAD

**Issue by harmohan-a** [aws/aws-cdk#3704]
### The Question

Because creating a VPC with default settings creates a public and private subnets that default to a NAT gateway for each public subnet, i am running out of EIP. 
My application doesnt even need a NAT gateways, its just an app that uses dax to connect to dynamodb.
Anyways, i tried creating a vpc with just private subnet and add dynamo as a gateway endpoint:

```
const daxVpc = new Vpc(this, 'daxVpc', {
      cidr: Vpc.DEFAULT_CIDR_RANGE,
      subnetConfiguration: [{
        subnetType: SubnetType.PRIVATE,
        name: defaultSubnetName(SubnetType.PRIVATE)
      }],
      gatewayEndpoints: {
        DYNAMODB: {
          service: GatewayVpcEndpointAwsService.DYNAMODB
        }
      }
    });
```

but it errors out during deployment:

```
8/31 | 16:24:34 | CREATE_IN_PROGRESS   | AWS::EC2::Subnet                      | daxVpc/IsolatedSubnet1/Subnet (daxVpcIsolatedSubnet1SubnetA090FC82) Resource creation Initiated
  8/31 | 16:24:34 | CREATE_IN_PROGRESS   | AWS::EC2::Subnet                      | daxVpc/IsolatedSubnet2/Subnet (daxVpcIsolatedSubnet2Subnet469D29C8) Resource creation Initiated
  9/31 | 16:24:34 | CREATE_COMPLETE      | AWS::EC2::RouteTable                  | daxVpc/IsolatedSubnet2/RouteTable (daxVpcIsolatedSubnet2RouteTableE102F846) 
 10/31 | 16:24:34 | CREATE_COMPLETE      | AWS::EC2::RouteTable                  | daxVpc/IsolatedSubnet1/RouteTable (daxVpcIsolatedSubnet1RouteTable5B90AC7F) 
 11/31 | 16:24:36 | CREATE_FAILED        | AWS::EC2::Route                       | daxVpc/IsolatedSubnet1/DefaultRoute (daxVpcIsolatedSubnet1DefaultRoute54F632D7) Exactly one of [EgressOnlyInternetGatewayId, InstanceId, NatGatewayId, TransitGatewayId, GatewayId, VpcPeeringConnectionId, NetworkInterfaceId] must be specified and not empty
```

What configuration am i missing ??

### Environment

  - **CDK CLI Version:** 1.3.0
  - **Module Version:** 1.3.0
  - **OS:** 
  - **Language:** TypeScript

**Comment by javydekoning** [comment]
It is possible to not create NAT GW's, however I run into the same issue with just private subnets: 

```typescript
    const vpcpriv = new ec2.Vpc(this, "privvpc", {
      cidr: "10.0.1.0/24",
      natGateways: 0,
      subnetConfiguration: [
        { cidrMask: 26, name: "ELB", subnetType: ec2.SubnetType.PRIVATE }
      ],
    });
```

**Error:**

```
14/36 | 10:28:18 AM | CREATE_FAILED        | AWS::EC2::Route                           | privvpc/ELBSubnet1/DefaultRoute (privvpcELBSubnet1DefaultRouteE8F5D68E) Exactly one of [EgressOnlyInternetGatewayId, NatGatewayId, GatewayId, TransitGatewayId, NetworkInterfaceId, VpcPeeringConnectionId, InstanceId] must be specified and not empty
```

**Comment by McDoit** [comment]
Doesn't private subnets need a NAT of some sort, and that's why it fails?
Of no route to internet is needed at all, shouldn't they be if type isolated?

**Comment by harmohan-a** [comment]
with an isolated subnet, i wont be able to connect to dynamo either. and i think lambda functions need to reside in a private subnet

**Comment by javydekoning** [comment]
@McDoit I think you are Co.

From the docs:

*PRIVATE

Subnet that routes to the internet, but not vice versa.

Instances in a private subnet can connect to the Internet, but will not allow connections to be initiated from the Internet.

Outbound traffic will be routed via a NAT Gateway. Preference being in the same AZ, but if not available will use another AZ (control by specifing maxGateways on VpcNetwork). This might be used for experimental cost conscious accounts or accounts where HA outbound traffic is not needed.*

For isolated it's mentioned it does NOT route any outbound traffic. In my mind routing over VPC peering was considered outbound. Perhaps we can clarify this in the documentation.

**Comment by harmohan-a** [comment]
what about the case of having a pivate subnet without a NAT and connect to internet (dynamodb) using a vpc endpoint like how i am trying to...

> A VPC endpoint enables you to privately connect your VPC to supported AWS services and VPC endpoint services powered by PrivateLink without requiring an internet gateway, NAT device, VPN connection, or AWS Direct Connect connection. Instances in your VPC do not require public IP addresses to communicate with resources in the service. Traffic between your VPC and the other service does not leave the Amazon network.

https://docs.aws.amazon.com/cdk/api/latest/docs/aws-ec2-readme.html#vpc-endpoints

**Comment by javydekoning** [comment]
VPC endpoints as well as privatelink can be considered local.

**Comment by nbaillie** [comment]
I also have a similar issue i don't want Nat GWs with my Private Subnet and wish to route all traffic over Direct Connect. 

Interestingly when I configure as bellow with nat_gateways=None i still get a Nat Gateway created. Not what i expected, but might be right. I had to add the PUBLIC subnet to get it to deploy.

       # VPC and Subnets
        subnet_config = [{
            'cidrMask': 24,
            'name': 'megaport-public-subnet',
            'subnetType': ec2.SubnetType.PUBLIC
        },
            {
            'cidrMask': 24,
            'name': 'megaport-private-subnet',
            'subnetType': ec2.SubnetType.PRIVATE
        }]

        vpc = ec2.Vpc(
            self, "VPC",
            nat_gateways=None,
            subnet_configuration=subnet_config,
            max_azs=1,
            vpn_gateway=True,
            vpn_gateway_asn=64512,
            #   vpn_route_propagation=subnet_config
        )

**Comment by javydekoning** [comment]
`nat_gateways` takes a number. By setting it to `None` I think you leave it undefined, hence using the default. Have you tried setting it to 0?

**Comment by nbaillie** [comment]
Makes sence, Just had a go with 0 and now hit the route issue below:

 1/4 | 12:24:56 | UPDATE_FAILED        | AWS::EC2::Route                       | VPC/megaport-private-subnetSubnet1/DefaultRoute (VPCmegaportprivatesubnetSubnet1DefaultRoute29ED121D) Exactly one of [NatGatewayId, NetworkInterfaceId, TransitGatewayId, EgressOnlyInternetGatewayId, VpcPeeringConnectionId, GatewayId, InstanceId] must be specified and not empty

**Comment by McDoit** [comment]
Yeah now you can override it yourself and add the gateway ID manually, creating your own type of private subnet

**Comment by harmohan-a** [comment]
What’s gateway is ?

Harmohan

On 20 Aug 2019, at 10:02 pm, Erik Karlsson <notifications@github.com<mailto:notifications@github.com>> wrote:


Yeah now you can override it yourself and add the gateway ID manually, creating your own type of private subnet

**Comment by McDoit** [comment]
@harmohan-a in your case you need to change the type of subnet to isolated from private 
My other answer was for @nbaillie

**Comment by harmohan-a** [comment]
yea, na, that wouldnt work. it needs to connect to dynamo which resides outside the vpc..

just having 

```
const daxVpc = new Vpc(this, 'daxVpc', {
      cidr: Vpc.DEFAULT_CIDR_RANGE,
      // maxAzs: 1
      subnetConfiguration: [{
        subnetType: SubnetType.ISOLATED,
        name: defaultSubnetName(SubnetType.ISOLATED)
      }],
      gatewayEndpoints: {
        DYNAMODB: {
          service: GatewayVpcEndpointAwsService.DYNAMODB
        }
      }
    });
```
errors out:

There are no 'Private' subnets in this VPC. Use a different VPC subnet selection.
Subprocess exited with error 1

**Comment by McDoit** [comment]
You would also need to set nat_gateways to zero i assume, even though that should probably be regarded as a bug when you only specify isolated subnets
The communication to dynamo would be handled by the endpoint, no NAT needed for that

**Comment by strazeadin** [comment]
@harmohan-a can you try the below and see if that works for you?

`const daxVpc = new Vpc(this, 'daxVpc', {
      cidr: Vpc.DEFAULT_CIDR_RANGE,
      natGateways: 0,
      subnetConfiguration: [{
        subnetType: SubnetType.ISOLATED,
        name: 'dax',
      }],
      gatewayEndpoints: {
        DYNAMODB: {
          service: GatewayVpcEndpointAwsService.DYNAMODB,
          subnets: [{ subnetType: SubnetType.ISOLATED }]
        }
      }
    });`

The key difference is adding the subnets property in the gatewayEndpoints section, as by default it tries to propagate routes to private subnets (which you don't have).

**Comment by mahmoudabid** [comment]
I have a similar issue, where whether using a NAT Gateway or not (i.e specifyng nat_gateways=0 or =1+) will result in a route with destination 0.0.0.0/0 but no target at all:

e.g.
`
vpc = ec2.Vpc(self, "VPC", 
           cidr=vpc_cidr,
           max_azs=2,
           subnet_configuration=[
                ec2.SubnetConfiguration(
                   name="subnet_group_%s" % i,
                   subnet_type=ec2.SubnetType.PRIVATE)
                for i in range(2)],
           nat_gateways=2,
        )
`
will create the following route for each Subnet, no target is specified:

`"VPCsubnetgroup1Subnet1DefaultRoute7E53BA71": {
      "Type": "AWS::EC2::Route",
      "Properties": {
        "RouteTableId": {
          "Ref": "VPCsubnetgroup1Subnet1RouteTableE6131C24"
        },
        "DestinationCidrBlock": "0.0.0.0/0"
      },
      "Metadata": {
       "..."
      }
    }
`
