### ISSUE TITLE
aws-ecs: TaskDefinition.addContainer() creates redundant policy resource

### ISSUE THREAD

**Issue by jcosentino11** [aws/aws-cdk#3714]
### What is the problem?
When the ECS execution role has proper read permissions (`secretsmanager:GetSecretValue`), `TaskDefinition#addContainer()` will still create a `AWS::IAM::Policy` resource.

In my case, this actually causes a `ValidationError` since the role contains a `/` (my org attaches a prefix to every role).

I would expect CDK to not create the policy resource unless it was strictly necessary.  Such behavior would also play nicely with organizations that impose limits on IAM role/policy creation.

### Reproduction Steps

* Manually create an IAM role allowing `secretsmanager:GetSecretValue`

* Define a stack with a TaskDefinition and add a container from a private registry, with authentication, to the task.
```
FargateTaskDefinition task = new FargateTaskDefintion(....);
task.addContainer("ecs-task-container", ContainerDefinitionOptions.builder()
    .withImage(ContainerImage.fromRegistry("a.private.repo/myImage", RepositoryImageProps.builder()
        .withCredentials(...)
        ....etc...
```

This triggers the following code path in `aws-ecs/.../repository.ts`, which in turn adds the policy:
```
if (this.props.credentials) {
    this.props.credentials.grantRead(containerDefinition.taskDefinition.obtainExecutionRole());
}
```

### Verbose Log
```
 2/6 | 17:20:32 | CREATE_FAILED        | AWS::IAM::Policy         | ecs-execution-role/Policy (ecsexecutionrolePolicyBC59850B) The specified value for roleName is invalid. It must contain only alphanumeric characters and/or the following: +=,.@_- (Service: AmazonIdentityManagement; Status Code: 400; Error Code: ValidationError; Request ID: a600991a-c2a5-11e9-a649-f3aea9112343)
	new Policy (/tmp/jsii-kernel-IHAebL/node_modules/@aws-cdk/aws-iam/lib/policy.js:29:26)
	\_ Import.addToPolicy (/tmp/jsii-kernel-IHAebL/node_modules/@aws-cdk/aws-iam/lib/role.js:84:42)
	\_ Function.addToPrincipal (/tmp/jsii-kernel-IHAebL/node_modules/@aws-cdk/aws-iam/lib/grant.js:52:65)
	\_ Import.grantRead (/tmp/jsii-kernel-IHAebL/node_modules/@aws-cdk/aws-secretsmanager/lib/secret.js:14:34)
	\_ RepositoryImage.bind (/tmp/jsii-kernel-IHAebL/node_modules/@aws-cdk/aws-ecs/lib/images/repository.js:19:36)
	\_ new ContainerDefinition (/tmp/jsii-kernel-IHAebL/node_modules/@aws-cdk/aws-ecs/lib/container-definition.js:71:40)
	\_ FargateTaskDefinition.addContainer (/tmp/jsii-kernel-IHAebL/node_modules/@aws-cdk/aws-ecs/lib/base/task-definition.js:118:16)
```

### Environment

  - **CDK CLI Version:** 1.4.0
  - **Module Version:** 1.4.0
  - **OS:** Alpine Linux
  - **Language:** Java

**Comment by rix0rrr** [comment]
I think this might be solved if we solve https://github.com/aws/aws-cdk/issues/3753
