### ISSUE TITLE
Region in ARN causing access denied error on iam:PassRole

### ISSUE THREAD

**Issue by awsuser19** [aws/aws-cdk#3733]
### What is the problem?
https://github.com/aws/aws-cdk/blob/013c18180ffe7eb3b404194f170ce8339bceff40/packages/%40aws-cdk/aws-ecs/test/fargate/integ.lb-awsvpc-nw.expected.json#L522
This line appears to add a region to the arn of the service linked role. This causes AccessDenied errors on iam:PassRole when it is deployed because IAM is a non-regional resource. 

https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html#arn-syntax-iam

### Reproduction Steps
1. install modules via npm install
2. compile code via npm run build
3. run synth via cdk synth

**Comment by nija-at** [comment]
Thanks for filing this bug report.

At first glance, it does look like the expected JSON might be expecting the wrong value here, however, I'm unable to reproduce this in a CDK app.

While I continue looking into this, it would be easier if you could provide the code or code snippet of your CDK app that's causing this issue.

**Comment by nija-at** [comment]
Found the issue.

It's coming from [BaseService#makeAutoScalingRole()](https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-ecs/lib/base/base-service.ts#L330) calling [formatArn()](https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/core/lib/arn.ts#L79-L81) that automatically puts the region in the generated ARN.
