### ISSUE TITLE
Add option to show diff before deploying

### ISSUE THREAD

**Issue by hoegertn** [aws/aws-cdk#3746]
### General Information

* [X] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change 

### Description
I think it would be great to have an option `--diff` for the `cdk deploy` command that shows the diff like `cdk diff` prior to deploying. The benefit over `cdk diff` would be that it does not exit with a status code greater 0 and does not need a second command.

The reason for this feature is to print out changes applied during CI/CD runs to the logs.

### Proposed Solution

Add `--diff` option to `cdk deploy` and print diff

### Environment

  - **CDK CLI Version:** 1.5.0
  - **Module Version:** 
  - **OS:** all
  - **Language:** all

**Comment by SomayaB** [comment]
Hi @hoegertn, thanks for submitting! We will update this issue when there is any progress. In the meantime if you want to give it a go and create a PR, please go ahead!

**Comment by guysqr** [comment]
I wrote a shell script (in zsh) to do this https://gist.github.com/guysqr/16efd78b8d63a021ea4471da98758449 in case it helps... you just run it instead of `cdk deploy` with the same arguments. It will first run diff, highlight any issues and then give you the option to run deploy.
