### ISSUE TITLE
inconsistent behaviour with validating function name in appsync CfnFunctionConfiguration

### ISSUE THREAD

**Issue by harmohan-a** [aws/aws-cdk#3747]
### What is the problem?

the name attribute for function configuration is string without any validations according to the docs
(https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appsync-functionconfiguration.html#cfn-appsync-functionconfiguration-name)

when i create a function configuration with a name like "function-1-harmohan" it works fine. But if i update any resolver for it and deploy again using cdk, the update fails with validation error that name attribute should match `[_A-Za-z][_0-9A-Za-z]*`

### Reproduction Steps
Create a graphql api using appsync from cdk
```
 const testApi = new CfnGraphQLApi(this, 'testApi', {
      name: "testApi",
      authenticationType: 'API_KEY'
    });

    new CfnApiKey(this, 'ItemsApiKey', {
      apiId: coralApi.attrApiId
    });

const graphQLDataSource = new CfnDataSource(this, 'graphQLDataSource', {
      apiId: testApi.attrApiId,
      name: "testGraphQLDataSource", 
      type: 'AMAZON_DYNAMODB',
      dynamoDbConfig: {
        awsRegion: this.region,
        tableName: table.tableName
      },
      serviceRoleArn: iamRoleAppSync.roleArn
    });

const testFunction = new CfnFunctionConfiguration(this, `testFunction-harmohan`, {
      apiId: testApi.attrApiId,
      dataSourceName: graphQLDataSource.name,
      name: test-function-harmohan,
      functionVersion: "2018-05-29",
      requestMappingTemplate: "{}",
      responseMappingTemplate: "{}",
    });
    testFunction.addDependsOn(graphQLDataSource);

const testResolver = new CfnResolver(this, 'createPostInGroupsResolver', {
      apiId: testApi.attrApiId,
      typeName: 'Mutation',
      fieldName: 'testFunction',
      kind: 'PIPELINE',
      pipelineConfig: {
        functions: [
          testFunction.attrFunctionId
        ]
      },
      requestMappingTemplate: "{}",
      responseMappingTemplate: "{}",
    });
```

do a deployment using cdk. it'll deploy and create the functions fine. then update one of the resolvers and try to deploy again, it will fail with error in the name field of the function configuration something like name attribute should match [_A-Za-z][_0-9A-Za-z]*

### Environment

  - **CDK CLI Version:** 1.4.0
  - **Module Version:** 1.4.0
  - **OS:** 
  - **Language:** TypeScript

**Comment by shivlaks** [comment]
hey @harmohan-a 

The sample code is using L1 constructs which should adhere to the CloudFormation specification.

I'm trying to reproduce this scenario but I have no problems with the `CfnFunctionConfiguration` resource. I do see that error message coming from the resolver though, but again that doesn't seem to be an issue with the CDK:
https://docs.aws.amazon.com/appsync/latest/APIReference/API_CreateResolver.html

Can you share the specific resources and error message you see?
I'd also love to see what the `cdk synth` output looks like.

**Comment by SomayaB** [comment]
Closing this issue since there hasn't been a response but feel free to reopen if you want to pick this back up.
