### ISSUE TITLE
Support people in locked-down environments by providing no-op IAM classes

### ISSUE THREAD

**Issue by rix0rrr** [aws/aws-cdk#3753]
#  :rocket: Feature Request

### General Information
* [ ] :wave: I may be able to implement this feature request
### Description

We should provide wrapper classes for common types (such as `Role` and `Bucket`) with stubbed out implements of methods like `addTo[Resource]Policy()`.

Many users will be operating in environments where they won't be able to make IAM changes, instead having to go to operators who will prepare IAM roles/permissions for them.

Right now, the CDK will do a whole bunch of IAM "heavy lifting" for users, but deployment of those stacks will fail because the deploying user won't have permissions to make the changes the CDK is proposing.

### Proposed Solution

Wrapper classes which no-op the modifications away (potentially registering/emitting them somewhere as metadata which can be queried).

Sample:

```ts
class BucketWrapper implements IBucket {
  constructor(private readonly inner: IBucket) { 
  }

  public get bucketArn()  {
    return this.inner.bucketArn;
  } 

  public urlForObject(key?: string) {
    return this.inner.urlForObject(key);
  }
  
  // ...

  public addToResourcePolicy(statement: iam.PolicyStatement) {
    // Intentionally do nothing
  }
}
```

The name obviously needs to be better. Suggestions welcome.

**Comment by rix0rrr** [comment]
I'll be happy for someone else to pick this up, BTW.

**Comment by slipdexic** [comment]
I'm happy to collaborate on this.

**Comment by slipdexic** [comment]
@rix0rrr where would you look for these to exist?

In its own section "wrappers"
OR
With each resource that we are supplying a wrapper,
e.g. 
BucketWrapper -> aws-s3
XYZWrapper -> aws-xyz

**Comment by rix0rrr** [comment]
Thank you @slipdexic! I think next to the resource in question makes the most sense (different file, but same package).

Name-wise, I think we need a better name for this concept than "Wrapper", but I'm a little stumped right now. I'm considering `ImmutableBucket`, `ImmutableRole`, etc. What do you think?

By the way, if you're going to implement this:

* Please mark the new classes `@experimental`.
* Please do a `this.bucket.addWarning(...something useful...)` in the call that is going to drop the permissions.

**Comment by eladb** [comment]
This seems to imply that now we have to implement a wrapper class for every AWS resource. Seems very heavy handed. Isn’t there a way to short circuit at the iam.Role level somehow? For example, we can offer a scope-level contextual switch that will disable the creation of actual iam.Roles and will no-op interaction with policies.

**Comment by rix0rrr** [comment]
It's not just roles though. We got into this discussion by talking about `ImportedBucket.addToResourcePolicy()`.

The alternative is to add a boolean to every imported resource that has a policy; in which case I'd rather have the wrapper class, since it's more flexible. It would also allow selectively disabling policy updates for certain operations and not others, and could also be applied to owned resources (both of which would not be true for a per-imported-resource flag).
