### ISSUE TITLE
Hi, Can you create a feature to use 'Existing Role' when create a lambda function ?

### ISSUE THREAD

**Issue by blacksun174** [aws/aws-cdk#3754]
### General Information

* [ ] :wave: I may be able to implement this feature request

* [ ] :warning: This feature might incur a breaking change 

### Environment

  - **CDK CLI Version:** 
  - **Module Version:** 
  - **OS:** 
  - **Language:**

**Comment by rhboyd** [comment]
Can you add some more information? Currently the CDK supports [using a Role that already exists](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-iam.Role.html#static-from-wbr-role-wbr-arnscope-id-rolearn) by specifying the Role's Arn.

**Comment by eladb** [comment]
Closing for now. Reopen if @rhboyd's pointer didn't help.
