### ISSUE TITLE
[ElasticSearch] Support ZoneAwarenessConfig

### ISSUE THREAD

**Issue by cmckni3** [aws/aws-cdk#3764]
### General Information

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change 

### Description

`ZoneAwarenessConfig` is not supported by `aws-elasticsearch` module. ElasticSearch module appears to default to 2 AZ when `ZoneAwarenessEnabled` is set to `true`.

### Environment

  - **CDK CLI Version:** 1.4.0 (build 175471f)
  - **Module Version:** 1.4.0
  - **OS:** OSX Mojave
  - **Language:** Using TypeScript but should apply to all

**Comment by cmckni3** [comment]
Seems like this may have been blocked by CloudFormation itself. It's available in CloudFormation.

See the latest blog post about new features at https://aws.amazon.com/about-aws/whats-new/2019/09/aws-cloudformation-updates-amazon-ec2-ecs-elasticache-elasticsearch/

**Comment by SomayaB** [comment]
Hi @cmckni3, is [this](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-elasticsearch.CfnDomain.ZoneAwarenessConfigProperty.html#interface-zoneawarenessconfigproperty) what you were looking for?

**Comment by cmckni3** [comment]
@SomayaB that's exactly what I was looking for. Appears to have been added shortly after I opened this issue.

Thanks!
