### ISSUE TITLE
Numbers that need stringification fail for Tokens

### ISSUE THREAD

**Issue by rix0rrr** [aws/aws-cdk#3769]
As seen in https://github.com/aws/aws-cdk/pull/3758:

Sometimes CFN models properties as strings which are clearly intended to be numbers, and are modeled in CDK as numbers. If we immediately stringify these numbers in the constructor and the user happened to pass a Token, the template will end up containing something like `"-1.8881545897087673e+289"`.

The solution is to stringify sometimes lazily, with a function like this:

```ts
function stringifyNumber(x: number) {
  if (Token.isUnresolved(x)) {
    return Lazy.stringValue({ produce: context => `${context.resolve(x)}` });
  } else {
    return `${x}`;
  }
}
```

This feature should probably live in the standard library, as many construct libraries are likely to need it.

An alternative approach would be spidering all strings for substrings that look like they might be stringified number Tokens, but this seems error-prone and expensive (computation-wise). For example, it would depend on the double stringification behavior of all JSII languages.

**Comment by jogold** [comment]
For reference, something similar was already discussed in https://github.com/aws/aws-cdk/pull/2846.

**Comment by rix0rrr** [comment]
Has been added to core library as `Tokenization.stringifyNumber()`.
