### ISSUE TITLE
Feature Proposal: CDK Project Generators

### ISSUE THREAD

**Issue by jewelsjacobs** [aws/aws-cdk#3770]
### General Information

* [ ] :wave: I may be able to implement this feature request

* [ ] :warning: This feature might incur a breaking change 

### Description

An expansion of the cdk --init [...] template system which would generate simple projects for very common use cases.

### Proposed Solution

I propose providing a generator / templating solution, similar to a yeoman generator, which will go beyond what cdk --init provides.

Currently using cdk --init to create an application project will create a sample cdk infrastructure. Although this is helpful, I feel there is a gap for folks needing a quick boilerplate showing how to use cdk with a real world application - including cdk unit / integration tests, application source (Ie. api, static web files), ideal file structures for pipeline projects, etc.

Having a templating / generator system simple enough for developers in the community to understand will remove the burden of support from the CDK core team and provide a  great repository of useful solutions for folks use. It will give them the opportunity to cut down the learning curve for teams internally as well, which is a pain point expressed by many, including myself.

AWS has some great venues for managing this sort of thing. I think templates and repositories are a specialty :)

I look forward to any feedback!

As always I am a big fan and am happy to offer support in any way I can :)

### Environment

  - **CDK CLI Version:** 
  - **Module Version:** 
  - **OS:** 
  - **Language:**

**Comment by hoegertn** [comment]
This sounds really great. You proposed something like yeoman, so why not use yeoman for this?

I think there could be templates for a Docker-based app, for serverless, etc.

**Comment by jewelsjacobs** [comment]
@hoegertn I don't know that sounds too easy.....

I was thinking create something from scratch. Maybe in Assembly? 😂 

That's a great idea and something I think I can actually do! I might be able to yeomanize a project I'm almost finished with and kill to birds with one stone (contribute to the community and help my team).

Thanks for the input!

**Comment by hoegertn** [comment]
Happy to help if you plan to create a cdk-yeoman generator for different use-cases.

**Comment by rhboyd** [comment]
+1. I would also like to see a `cdk init --langauge typescript package` template that will generate a CDK Library Construct and the accompanying pipeline to deploy it.

make creating a library as easy as creating a sample-app
