### ISSUE TITLE
Support for adding IAM conditions

### ISSUE THREAD

**Issue by acdha** [aws/aws-cdk#3773]
Using `cdk 1.5.0 (build c020efa)` the IAM conditions interfaces make it easy to specify values which pass type checking but will be rejected by IAM. Most of this comes back to the name being misleading:

"conditions" is plural and suggests a list as the expected type:

```typescript
conditions: [
    {
        StringEquals: {
            "ec2:ResourceTag/tagname": "value"
        }
    }
]
```

That will deploy but then fail due to a syntax error, because it actually needs to be an object:

```typescript
conditions: {
    StringEquals: {
        "ec2:ResourceTag/tagname": "value"
    }
}
```

This could be partially addressed with documentation showing the expected syntax for conditions but it seems like something which the type checker should be able to catch to avoid having to wait aeons for CloudFormation to fail the update.

**Comment by rix0rrr** [comment]
Can I ask where you are able to specify `conditions` as an array? What object are you creating, what language are you using?

**Comment by rix0rrr** [comment]
This seems to be a TypeScript oddity that we weren't aware of. The type is defined as:

```ts
  readonly conditions?: {[key: string]: any};
```

https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-iam/lib/policy-statement.ts#L291

But "because JavaScript" an array satisfies this type as well (and in fact any non-primitive type does).

I am honestly not sure how to fix this :(

**Comment by rix0rrr** [comment]
I feel you and thanks for the report, but I think this is not actionable for now. Sorry about the confusing API, we will have to rethink this for v2.

**Comment by peggalex** [comment]
@rix0rrr  i know this is old, but it seems that @acdha meant the type should be something like:

```
type Condition = {[key: string]: any};
type Conditions = Condition[];
```

personally, i think that the optimal fix is to rename it to `condition` without the plural, as it is in an [actual policy json definition](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition_operators.html), but this would obviously impact backwards compatibility.
