### ISSUE TITLE
Route 53 Alias for CloudFront (Python)

### ISSUE THREAD

**Issue by gadams999** [aws/aws-cdk#3776]
### The Question

I'm trying to create a Route 53 A record for a CloudFront distribution. The distribution is fine when I `cdk synth`, but I cannot get past the `CloudFrontTarget` from_alias section. Different errors for different approaches.

So, in Python, is there any code that will create the Route 53 A record using CloudFront domain name that works?

### Environment

  - **CDK CLI Version:** 1.5.0
  - **Module Version:** All are 1.5.0 (newly pipped)
  - **OS:** macOS Mojave
  - **Language:** Python

```python
from aws_cdk import core
from aws_cdk.aws_cloudfront import (
    CloudFrontWebDistribution,
    CfnCloudFrontOriginAccessIdentity,
    ViewerProtocolPolicy,
)
from aws_cdk.aws_route53 import ARecord, RecordTarget, AliasRecordTargetConfig
from aws_cdk.aws_route53_targets import CloudFrontTarget

host_name = "www.example.com"
cert_arn = "good arn that is working"
zone_id = "my route 53 public zone id for example.com"

# Bucket and CloudFront bits ** WORKING **
sourceBucket = Bucket(
    self,
    "SiteOriginBucket",
    website_index_document="index.html",
    website_error_document="/index.html",
    block_public_access=public_access,
    bucket_name=host_name + "-website",
    removal_policy=RemovalPolicy.DESTROY,
)
oai = CfnCloudFrontOriginAccessIdentity(
    self,
    "OriginIdentity",
    cloud_front_origin_access_identity_config={
        "comment": "Allow CloudFront to access web site"
    },
)
distribution = CloudFrontWebDistribution(
    self,
    "SiteDistribition",
    origin_configs=[
        {
            "s3OriginSource": {
                "s3BucketSource": sourceBucket,
                "originAccessIdentityId": oai.ref,
            },
            "behaviors": [{"isDefaultBehavior": True}],
        }
    ],
    alias_configuration={"acmCertRef": cert_arn, "names": [host_name]},
    viewer_protocol_policy=ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
)

# Trying to create Route 53 record
# x = {"dnsName":"${Token[TOKEN.22]}","hostedZoneId":"Z2FDTNDATAQYW2"}
x = CloudFrontTarget(distribution).bind(distribution)

# x = "AAABBBCCC..." (my Route 53 zone id - not the one to target for CloudFront)
x = CloudFrontTarget(distribution)

route53_record = ARecord(self, "SiteAlias",
    record_name=host_name,
    target=RecordTarget.from_alias(x),
    zone=zone_id
)
```

The error I get back for the methods (with or without bind()) are:
```jsii.errors.JSIIError: Expected object reference, got {"dnsName":"${Token[TOKEN.22]}","hostedZoneId":"Z2FDTNDATAQYW2"}```

and:

```jsii.errors.JSIIError: Expected object reference, got "Z1W5xxxxxANJ"```

So it looks like both are not returning an object that is expected for the `target=RecordTarget.from_alias(x)` reference. The one where I bind() the call appears to return closest to what is needed (reference to `dnsName` and the correct `hostedZoneId`, but I'm getting lost in the typescript to Python changes.

My expectation is that a call to `CloudFrontTarget(distribution)` would return the value expected for the `target` parameter for `ARecord`.

**Comment by rhboyd** [comment]
@gadams999 does this example help at all?

https://github.com/rhboyd/aws-cdk-examples/blob/master/python/static-site/static_site/static_site_construct.py#L56-L82

**Comment by gadams999** [comment]
@rhboyd it sure was helpful, thanks! Not only did it unblock me from creating the proper Route 53 record, but also showed me a way to start collecting construct artifacts for reuse!
