### ISSUE TITLE
CloudFormation CustomResource Does Not Support Lambda With Code From AssetCode

### ISSUE THREAD

**Issue by jd-carroll** [aws/aws-cdk#3778]
### What is the problem?
You cannot create a CustomResource definition which consumes a lambda function whose code is defined with `lambda.AssetCode`.

### Reproduction Steps
1. Start with the example project: https://github.com/aws-samples/aws-cdk-examples/tree/master/typescript/custom-resource
2. Move the `custom-resource-handler.py` into a folder called `my-function`
3. Change the lambda definition to as follows:
```javascript
      provider: cfn.CustomResourceProvider.lambda(new lambda.SingletonFunction(this, 'Singleton', {
        uuid: 'f7d4f730-4ee1-11e8-9c2d-custom-resource',
        code: new lambda.AssetCode('./my-function'),   // <-- Note the change here
        handler: 'custom-resource-handler.main',       // <-- Note the change here
        timeout: cdk.Duration.seconds(300),
        runtime: lambda.Runtime.PYTHON_2_7,
      })),
```
4. `$ cdk deploy` --> Fails

### Verbose Log
```
CustomResourceDemoStack: deploying...
Updated: asset.36ade47dcef99d1600d9360ce4b4d6fc7dea9ccd2760165781723db681b03c23 (zip)
CustomResourceDemoStack: creating CloudFormation changeset...
 0/5 | 3:35:11 PM | CREATE_IN_PROGRESS   | AWS::CDK::Metadata                  | CDKMetadata 
 0/5 | 3:35:12 PM | CREATE_IN_PROGRESS   | AWS::IAM::Role                      | SingletonLambdaf7d4f7304ee111e89c2dcustomresource/ServiceRole (SingletonLambdaf7d4f7304ee111e89c2dcustomresourceServiceRoleA0A9E703) 
 0/5 | 3:35:12 PM | CREATE_IN_PROGRESS   | AWS::IAM::Role                      | SingletonLambdaf7d4f7304ee111e89c2dcustomresource/ServiceRole (SingletonLambdaf7d4f7304ee111e89c2dcustomresourceServiceRoleA0A9E703) Resource creation Initiated
 0/5 | 3:35:13 PM | CREATE_IN_PROGRESS   | AWS::CDK::Metadata                  | CDKMetadata Resource creation Initiated
 1/5 | 3:35:14 PM | CREATE_COMPLETE      | AWS::CDK::Metadata                  | CDKMetadata 
 2/5 | 3:35:24 PM | CREATE_COMPLETE      | AWS::IAM::Role                      | SingletonLambdaf7d4f7304ee111e89c2dcustomresource/ServiceRole (SingletonLambdaf7d4f7304ee111e89c2dcustomresourceServiceRoleA0A9E703) 
 2/5 | 3:35:28 PM | CREATE_IN_PROGRESS   | AWS::Lambda::Function               | SingletonLambdaf7d4f7304ee111e89c2dcustomresource (SingletonLambdaf7d4f7304ee111e89c2dcustomresourceE59DEEEA) 
 2/5 | 3:35:28 PM | CREATE_IN_PROGRESS   | AWS::Lambda::Function               | SingletonLambdaf7d4f7304ee111e89c2dcustomresource (SingletonLambdaf7d4f7304ee111e89c2dcustomresourceE59DEEEA) Resource creation Initiated
 3/5 | 3:35:29 PM | CREATE_COMPLETE      | AWS::Lambda::Function               | SingletonLambdaf7d4f7304ee111e89c2dcustomresource (SingletonLambdaf7d4f7304ee111e89c2dcustomresourceE59DEEEA) 
 3/5 | 3:35:31 PM | CREATE_IN_PROGRESS   | AWS::CloudFormation::CustomResource | DemoResource/Resource/Default (DemoResource5B5C546C) 
3/5 Currently in progress: DemoResource5B5C546C
```

### Environment
Every environment
  - **CDK CLI Version:** 1.5.0
  - **Module Version:** 1.5.0
  - **OS:** MacOS
  - **Language:** Typescript

**Comment by jd-carroll** [comment]
@BerndWessels your issue #2126 is a duplicate of this.  Try moving your source to inline or an s3 bucket (i.e. `lambda.S3Code`) or use `lambda.InlineCode` and see if that works.

**Comment by eladb** [comment]
It seems like your custom resource is not sending a response to CloudFormation, which is why the stack deployment hangs. Can you share your custom resource code?

**Comment by eladb** [comment]
@jd-carroll sorry, you are right. Didn't see that you are using the sample. Can you look in your CloudWatch logs and see if you can find an error?

**Comment by jd-carroll** [comment]
No error, and in other iterations I could actually see the lambda being
invoked by the CustomResource (with the value defined in the custom
resource definition). So this is truly puzzling to me... could it be an
order of operations thing? Does the custom resource need to depend on the
lambda first being created? (the generated cf.json does not have a
DependsOn linking the CustomResource to the lambda)

**Comment by jd-carroll** [comment]
Solved: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-lambda-function-code-cfnresponsemodule.html

> **Note**
> The cfn-response module is available only when you use the ZipFile property to write your source code. It isn't available for source code that's stored in Amazon S3 buckets. For code in buckets, you must write your own functions to send responses.

For the record, that behavior sucks.  

Basically the issue is that AWS auto-injects the module `cfn-response` if it is `"inlined"`in the CloudFormation template.  This is similar behavior as the `aws-sdk-js` or `boto3` where you do not need to include them in your bundle for the lambda function, they are just automagically available.

However, I didn't realize that the behavior would vary based on how the source is included in the CloudFormation script.  **This really sucks, literally days!!!!!** 😡 😄

**Comment by albertodiazdorado** [comment]
@jd-carroll how do I provide the source code using `ZipFile` if I am using `CDK` instead of `ColudFormation`?
