### ISSUE TITLE
Add support for CloudMap on ECS LoadBalancedService

### ISSUE THREAD

**Issue by jonhkr** [aws/aws-cdk#3779]
### General Information

* [X] :wave: I may be able to implement this feature request

* [ ] :warning: This feature might incur a breaking change 

### Description

Add support for registering a LoadBalancedService to a CloudMap namespace. This will enable us to discover services from other services in the same cluster.

The ECS patterns package is very helpful in the sense that it makes it very simple to deploy a service in the cluster, but service discovery is a must have for distributed applications and the current version of LoadBalancedService does not support it.

### Proposed Solution

Allow passing the `cloudMapOptions` props to the internal service resource.

### Environment

  - **CDK CLI Version:** 1.5.0 (build c020efa)
  - **Module Version:** 1.5.0 
  - **OS:** all
  - **Language:** all

**Comment by pkandasamy91** [comment]
CloudMapOptions were added as part of: https://github.com/aws/aws-cdk/pull/4369
