### ISSUE TITLE
NPM Non-strict version declaration for peer dependencies

### ISSUE THREAD

**Issue by artyom-melnikov** [aws/aws-cdk#3783]
### What is the problem?

I use CDK v1.4 `"@aws-cdk/core": "1.4.0"` and a couple of packages like `"@aws-cdk/aws-lambda": "1.4.0",`
When installing via npm, the peer dependencies has non-strict version definition
`aws-lambda/package.json`: 
```
  "peerDependencies": {
    "@aws-cdk/aws-cloudwatch": "^1.4.0",
    "@aws-cdk/aws-ec2": "^1.4.0",
    "@aws-cdk/aws-events": "^1.4.0",
    "@aws-cdk/aws-iam": "^1.4.0",
    "@aws-cdk/aws-logs": "^1.4.0",
    "@aws-cdk/aws-s3": "^1.4.0",
    "@aws-cdk/aws-s3-assets": "^1.4.0",
    "@aws-cdk/aws-sqs": "^1.4.0",
    "@aws-cdk/core": "^1.4.0",
    "@aws-cdk/cx-api": "^1.4.0"
  },
```

Therefore npm installs higher version for peer dependencies if it is available (right now it's 1.5.0), resulting in the build conflicts:
```
lib/lambdas/lambdas-stack.ts:58:36 - error TS2345: Argument of type 'Stack' is not assignable to parameter of type 'Construct'.                                                                                            Types of property 'node' are incompatible.
    Type 'import("C:/_work/xxx/aws/cdk/node_modules/@aws-cdk/core/lib/construct").ConstructNode' is not assignable to type 'import("C:/_work/xxx/aws/cdk/node_modules/@aws-cdk/aws-kms/node_modules/@aws-cdk/core/lib/construct").ConstructNode'.
      Types have separate declarations of a private property 'host'.
```

### Reproduction Steps

Idk, just create some typescript project and try to install non-final version with some additional packages

### Environment

  - **CDK CLI Version:*1.4.0* 
  - **Module Version:*1.4.0* 
  - **OS:*Windows * 
  - **Language:*TypeScript * 

### Other information 

Pin versions to point only to specific project versions

**Comment by ulf5** [comment]
Related https://github.com/aws/aws-cdk/issues/3768 https://github.com/aws/aws-cdk/issues/3517

**Comment by eladb** [comment]
Duplicate #3711
