### ISSUE TITLE
CSharp - Related classes aren't discoverable via intellisense

### ISSUE THREAD

**Issue by rschiefer** [aws/aws-cdk#3812]
### General Information
* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a `breaking change

### Description
When related classes are nested inside other classes they aren't as discoverable via intellisense.  I almost created a bug because I couldn't find the JobCommandProperty to set the Command Property on CfnJob in the Glue module.  

I had to full text search the nuget package source manually to find the type I was looking for.  This was not a good experience.

### Proposed Solution
If you place the related classes as peers in the same namespace they should be more discoverable.

### Environment

  - **CDK CLI Version:** aws-cli/1.16.225 Python/3.6.0 Windows/10 botocore/1.12.215
  - **OS:** Windows 10
  - **Language:** CSharp

**Comment by RomainMuller** [comment]
This could result in naming collisions (nothing prevents another class with the same name to exist as a peer and as a nested class; or several peer classes to have identically-named nested children).

Another solution would be to do this for _all_ languages (the collision problem still exists but would be solved once in the TypeScript version only).
