### ISSUE TITLE
Modify the BlockDeviceMappings in eks.Cluster.addCapacity

### ISSUE THREAD

**Issue by abelmokadem** [aws/aws-cdk#3815]
### General Information
* [X] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

### Description
Similar to https://github.com/aws/aws-cdk/issues/3620 Provide an option to specify the BlockDeviceMappings when adding an autoscaling group to the cluster.

### Proposed Solution
Add BlockDeviceMapping to CapacityOptions.

### Environment

  - **CDK CLI Version:** 1.5.0
  - **Module Version:** 1.5.0
  - **OS:** OS X Sierra
  - **Language:** TypeScript

**Comment by SomayaB** [comment]
Hi @abelmokadem, thanks for submitting this request. We would really appreciate it if you submitted a PR on this. 👍

**Comment by abelmokadem** [comment]
@eladb I see that this can be approached in different ways. I think the simplest would be to move `blockDevices` from `AutoScalingGroupProps` to `CommonAutoScalingGroupProps`? Is there any argument against this?

**Comment by abelmokadem** [comment]
https://github.com/aws/aws-cdk/pull/7291 I think this closes the issue.
