### ISSUE TITLE
Adding Targets to an imported ApplicationTargetGroup

### ISSUE THREAD

**Issue by hertzknight** [aws/aws-cdk#3816]
I am trying to just add a new target to the ApplicationTargetGroup that has already been deployed. I imported it using elbv2.ApplicationTargetGroup.import_(). The code is written in python. Technically the TargetGroup exists in a separate scope,

Code:
```
TargetGroup=elbv2.ApplicationTargetGroup.import_(
    scope=stack,
    id="TargetGroup",
    default_port="80",
    target_group_arn=TargetGroupARN,
)
Service.attach_to_application_target_group(
    target_group=TargetGroup
)
```

But when I try to add my service to it, it gets this error message:
```
Object of type @aws-cdk/aws-elasticloadbalancingv2.IApplicationTargetGroup is not convertible to @aws-cdk/aws-elasticloadbalancingv2.ApplicationTargetGroup
```

Is there a way to convert an IApplicationTargetGroup to an ApplicationTargetGroup or Is there a way to add a new target to an existing LoadBalancer without redoing how it was deployed?

**Comment by SomayaB** [comment]
Hi @hertzknight, I'm so sorry for the long overdue response. Do you still need guidance on this issue?

**Comment by hertzknight** [comment]
Honestly this was so long ago, I am not sure if this was fixed in a frequent update or not. I will close this as I switched over to typescript and forgot about this/no longer need this.
