### ISSUE TITLE
Blog Post: Using asserts to test infra code

### ISSUE THREAD

**Issue by fulghum** [aws/aws-cdk#3817]
First draft of blog post to help demonstrate how to use asserts to test CDK infrastructure code.

**Comment by rix0rrr** [comment]
Small. Hah!

**Comment by rhboyd** [comment]
Is this using the `'@aws-cdk/assert'` module or assertions in general? It looks like the aws-cdk/assert module isn't jsii'd or published to npm so it can only be used for testing infra inside `@aws-cdk`.

**Comment by SomayaB** [comment]
Closing since the blog post has been published. See [here](https://aws.amazon.com/blogs/developer/testing-infrastructure-with-the-aws-cloud-development-kit-cdk/).
