### ISSUE TITLE
DocumentDb Instance is not attached to the same VPC as the DbCluster EC2 Security Group

### ISSUE THREAD

**Issue by theljani** [aws/aws-cdk#3827]
I'm using aws CDK with typescript to create a documentdb database under a specific VPC.
I'm getting an error while deploying the cdk project and the reason is that the cluster security group and the db instance are in different VPCs.

The cluster security group is under the specified VPC but in the instance is created under the default VPC in the targeted region.

How can I attach a dn instance to a specific VPC using the CDK?
Environment:
     CDK CLI Version: 1.5.0
     Module Version: 1.5.0
     Language: TypeScript

this is the error:
The DB instance and EC2 security group are in different VPCs. The DB instance is in vpc-58a8803e and the EC2 security group is in vpc-06e01183175cde5f9 (Service: AmazonRDS; Status Code: 400; Error Code: InvalidParameterCombination; Request ID: 8007d96f-b145-408f-ac5e-adaf3b9f4636)

**Comment by rddefauw** [comment]
What was the resolution to this?

**Comment by hoegertn** [comment]
I had the same problem and the issue was a wrong reference to the DBSubnetGroup. See https://github.com/taimos/awsloft-database-workshop/blob/implemented/lib/databases-stack.ts for a working example.

**Comment by theljani** [comment]
I had resolved the issue the same way.
