### ISSUE TITLE
[sns] support region property for SqsSubscription

### ISSUE THREAD

**Issue by jcosentino11** [aws/aws-cdk#3842]
### General Information

* [ ] :wave: I may be able to implement this feature request

* [ ] :warning: This feature might incur a breaking change

### Description

I would like to be able to specify region when creating an SqsSubscription:
``` ts
new SqsSubscription(queue,
                    SqsSubscriptionProps.builder()
                            .rawMessageDelivery(true)
                            .region("us-east-1")
                            .build());
```

Currently, I have to work around this via:
``` ts
new CfnSubscription(this, "my-subscription", CfnSubscriptionProps.builder()
                    .region("us-east-1")
                    .protocol("sqs")
                    .topicArn("arn:aws:sns:us-east-1:123456789:MyTopic")
                    .endpoint("arn:aws:sqs:us-west-2:123456789:QueueInADifferentRegion")
                    .rawMessageDelivery(true)
                    .build());
``` 

### Environment

  - **CDK CLI Version:** 1.6.0
  - **Module Version:** 1.6.0
  - **OS:** Linux Alpine
  - **Language:** Java

**Comment by nija-at** [comment]
CloudFormation does not allow resources to be defined across regions. This will only be available if you're importing either the SQS queue or the SNS topic.

@jcosentino11 - does this match up with your use case?

**Comment by jcosentino11** [comment]
@nija-at Yep, that matches the use case
