### ISSUE TITLE
CDK Bootstrap customisation 

### ISSUE THREAD

**Issue by erupare** [aws/aws-cdk#3853]
I would like CDK to use an existing bucket, instead of creating a staging bucket (this a constraint I have been given). I would CDK Bootstrap to have option to accept name of an existing bucket.

**Comment by shivlaks** [comment]
hey @erupare,

This seems like a duplicate of #3684
Can you +1 / comment on that issue instead if it is?

**Comment by shivlaks** [comment]
I'm going to close this as a duplicate. Please reopen if that's an incorrect classification.
