### ISSUE TITLE
CodeBuild: Add support for logging configuration in Project

### ISSUE THREAD

**Issue by idm-ryou** [aws/aws-cdk#3856]
### General Information

* [ ] :wave: I may be able to implement this feature request

* [ ] :warning: This feature might incur a breaking change

### Description

- There seems no way to specify a logging configuration for Project construct.

### Proposed Solution

- Accept [LogsConfigProperty](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-codebuild.CfnProject.LogsConfigProperty.html) in [ProjectProps](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-codebuild.ProjectProps.html)

### Environment

  - **CDK CLI Version:** 1.6.0 (build 3a0cde0)
  - **Module Version:** 1.6.0
  - **OS:** all
  - **Language:** all

**Comment by NGL321** [comment]
Hi @idm-ryou,

This seems like a reasonable request!
I have confirmed that `LogsConfig` property exists as a property of `Project` in Cloudformation, and that we do not accept it as a prop.

Someone will update this issue when any progress is made.

😸

**Comment by felipeloha** [comment]
is there any workaround for this?

**Comment by logemann** [comment]
> is there any workaround for this?

You might check out addOverride as seen in
https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html

I will take a look at it for the time being. And hopefully there will be a fix so that Project can get the relevant attribute.

**Comment by logemann** [comment]
This worked for me:

```
let pipelineProject = new PipelineProject(this, "MyProject", {
...
};

const logGroup = new logs.LogGroup(this, StackUtils.getResourceName('CodepipelineLogGroup', props.deployEnv!), {
            retention: logs.RetentionDays.ONE_WEEK
        });
const logStream = logGroup.addStream(StackUtils.getResourceName('CodepipelineStream', props.deployEnv!));
        
let cfnProject = pipelineProject.node.defaultChild as CfnProject;
cfnProject.addPropertyOverride('LogsConfig', {
    "CloudWatchLogs": {
         "GroupName": logGroup.logGroupName,
         "Status": "ENABLED",
         "StreamName": logStream.logStreamName
    }
 });

pipelineProject.role?.addManagedPolicy(ManagedPolicy.fromAwsManagedPolicyName('CloudWatchLogsFullAccess'));
```

**Comment by wulfmann** [comment]
I added an implementation for this on #11444 , feedback welcome!
