### ISSUE TITLE
No difference is generating diff 

### ISSUE THREAD

**Issue by abelmokadem** [aws/aws-cdk#3860]
### What is the problem?
I keep getting the following output with my SSM Document resource, without changing the stack:
```
Stack BiccQlikSenseOnWindowsStagingStack
The BiccQlikSenseOnWindowsStagingStack stack uses assets, which are currently not accounted for in the diff output! See https://github.com/aws/aws-cdk/issues/395
Resources
[~] AWS::SSM::Document CentralNodeCommands/CentralNodeBootstrapV0.0.29 CentralNodeCommandsCentralNodeBootstrapV0029A4430735 replace
 └─ [~] Content (requires replacement)
     └─ [~] .mainSteps:
         └─ @@ -23,7 +23,7 @@
            [ ] "action": "aws:runPowerShellScript",
            [ ] "inputs": {
            [ ]   "runCommand": [
            [-]     "Install-PackageProvider Nuget ?Force",
            [+]     "Install-PackageProvider Nuget –Force",
            [ ]     "Install-Module -Force -Name Qlik-Cli",
            [ ]     "Install-Module -Force -Name QlikResources",
            [ ]     "Install-Module -Force -Name cDownloadFile",
```

My observations:
- Stack inside `cdk.out` is generated with `-Force`
- SSM Document is created with `-Force`
- CloudFormation Template in AWS console is showing `?Force`

The code in question:
```
    const document = new ssm.CfnDocument(this, `CentralNodeBootstrap${props.version}`, {
      documentType: "Command",
      content: {
        schemaVersion: "2.2",
        ...
          {
            name: "InstallModules",
            action: "aws:runPowerShellScript",
            inputs: {
              runCommand: [
                "Install-PackageProvider Nuget –Force",
                "Install-Module -Force -Name Qlik-Cli",
                "Install-Module -Force -Name QlikResources",
```

Is this a CloudFormation bug or is this a CDK bug? I'm really confused now.

### Reproduction Steps
Create an SSM document using `new ssm.CfnDocument` with the code I provided above.

### Environment

  - **CDK CLI Version:** 1.4.0 / 1.5.0
  - **Module Version:** 1.4.0 / 1.5.0
  - **OS:** OS X Sierra
  - **Language:** TypeScript

**Comment by shivlaks** [comment]
Hey @abelmokadem ,

I'm attempting to repro your issue. Created a stack - [Gist](https://gist.github.com/shivlaks/a4eead64adb68b275e59ec2d05aeffd6)

running `cdk deploy` deployed to CloudFormation did not result in any weird issues or produce the '?' in the template that was uploaded to CloudFormation. Subsequent calls to `cdk diff` just result in no diff issues

```
Stack Github3860Stack
There were no differences
```

Your sample code has different unicode characters. The `–Force` in your first line is showing me [EN DASH](https://apps.timwhitlock.info/unicode/inspect?s=%E2%80%93) - which subsequently is producing the `?` in CloudFOrmation

and your other dashes show up as [HYPHEN-MINUS](https://apps.timwhitlock.info/unicode/inspect?s=-)

Try out the Gist / updating that character, but I don't think this is a bug with `diff`

**Comment by abelmokadem** [comment]
I can't believe I missed that... This one line was copied from somewhere else and I never checked the encoding. Thanks a lot! @shivlaks
