### ISSUE TITLE
LoadBalancedFargateService does not work when using network load balancer

### ISSUE THREAD

**Issue by davidsteed** [aws/aws-cdk#3864]
### What is the problem?

The security group created when setting loadBalancerType: LoadBalancerType.NETWORK does not allow any Pots to be open so the service does not work.  Have to manually create a rule to open a port range

### Reproduction Steps

take https://github.com/aws-samples/aws-cdk-examples/blob/master/typescript/ecs/fargate-load-balanced-service/index.ts and add the line 
set loadBalancerType: LoadBalancerType.NETWORK 
in the fargate service 

### Environment

  - **CDK CLI Version:1.6
  - **Module Version:
  - **OS:all
  - **Language:all

### Other information
The problem is because the security group created needs to have an inbound rule to allow connections

**Comment by davidsteed** [comment]
Is there a way of working round this?  I have to use a Network Load balancer not an application load balancer so that I can create a VPCLink between API Gateway and my Fargate Service.  The security group created does not allow inbound connections and othe than going to the console - I don't know how I can add listeners as I don't have access to the loadbalancer. Is there an Escape hatch that would make this possible.

**Comment by rix0rrr** [comment]
Duplicate of https://github.com/aws/aws-cdk/issues/3667
