### ISSUE TITLE
Harmonise the way iam ManagedPolicies and Policies are applied to groups / users / roles 

### ISSUE THREAD

**Issue by pontusvision** [aws/aws-cdk#3866]
### General Information

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

### Description
ManagedPolicies can be instantiated without the creation of groups, and added to groups using the managedPolicies property.  In contrast, custom policies are associated with groups during their creation; i.e. first a group/user/role must be created, and then passed in to the policy as an association.
 
This CDK behaviour does not seem to follow the normal pattern that the console uses, where a policy can be created without any group/user/role association.

### Proposed Solution
The best suggestion is to simply stop checking for the length of those entries, and add methods to the group/users to add a Policy (similar to the managed policies).   
The validate() function in the policy.ts file (Policy class) is checking for the length of the groups/users/roles to be > 0.  This causes trouble when the CDK scripts are attempting to create a custom Policy before creating any Users/ Roles/ Groups.

### Environment
  - **CDK CLI Version:** 1.6.0
  - **Module Version:** 1.6.0
  - **OS:** all
  - **Language:** TypeScript

### Other information
```
 user@users-MacBook-Pro  ~/workspace/aws-cdk   jira-45 ●  cdk synth iamStack
Error: Validation failed with the following errors:
  [iamStack/CreateUserRoleConstruct/AllowManageOwnUserMFA] Policy must be attached to at least one principal: user, group or role
  [iamStack/CreateUserRoleConstruct/DenyAllExceptListedIfNoMFA] Policy must be attached to at least one principal: user, group or role
    at Function.synth (/Users/user/workspace/aws-cdk/node_modules/@aws-cdk/core/lib/construct.ts:53:17)
    at App.synth (/Users/user/workspace/aws-cdk/node_modules/@aws-cdk/core/lib/app.ts:128:36)
    at /Users/user/workspace/aws-cdk/bin/aws-cdk.ts:74:7

/Users/user/workspace/aws-cdk/node_modules/@aws-cdk/core/lib/construct.ts:53
          throw new Error(`Validation failed with the following errors:\n  ${errorList}`);
                ^
Error: Validation failed with the following errors:
  [iamStack/CreateUserRoleConstruct/AllowManageOwnUserMFA] Policy must be attached to at least one principal: user, group or role
  [iamStack/CreateUserRoleConstruct/DenyAllExceptListedIfNoMFA] Policy must be attached to at least one principal: user, group or role
    at Function.synth (/Users/user/workspace/aws-cdk/node_modules/@aws-cdk/core/lib/construct.ts:53:17)
    at App.synth (/Users/user/workspace/aws-cdk/node_modules/@aws-cdk/core/lib/app.ts:128:36)
    at process.<anonymous> (/Users/user/workspace/aws-cdk/node_modules/@aws-cdk/core/lib/app.ts:111:45)
    at Object.onceWrapper (events.js:291:20)
    at process.emit (events.js:203:13)
    at process.EventEmitter.emit (domain.js:476:20)
    at process.emit (/Users/user/workspace/aws-cdk/node_modules/source-map-support/source-map-support.js:465:21)
    at process.topLevelDomainCallback (domain.js:131:23)
Subprocess exited with error 1
```

**Comment by rhboyd** [comment]
> The best suggestion is to simply stop checking for the length of those entries, and add methods to the group/users to add a Policy

I’m not sure this is advised. I believe there’s a limit to the policy document length for both inline policies and user managed policies

**Comment by rix0rrr** [comment]
Aha, managed policies shouldn't have inherited from policy, which it looks like it does. Thanks for reporting.

**Comment by rix0rrr** [comment]
Wait, `ManagedPolicy` doesn't inherit from `Policy` at all. `ManagedPolicy` can be created without attaching it to principals, `Policy` cannot.

I'm confused about what you're asking for in this ticket. Could you post example code that is not behaving the way you expect it  to?

In the mean time, downgrading this from bug to guidance.

**Comment by SomayaB** [comment]
> Wait, `ManagedPolicy` doesn't inherit from `Policy` at all. `ManagedPolicy` can be created without attaching it to principals, `Policy` cannot.
> 
> I'm confused about what you're asking for in this ticket. Could you post example code that is not behaving the way you expect it to?
> 
> In the mean time, downgrading this from bug to guidance.

@pontusvision

**Comment by SomayaB** [comment]
I will close this issue since it hasn't gotten a response. Feel free to reopen.
