### ISSUE TITLE
ALB: New types of listener rule conditions

### ISSUE THREAD

**Issue by KnisterPeter** [aws/aws-cdk#3888]
## :rocket: Feature Request

Add listener rules to ALB

### General Information

* [x] :wave: I may be able to implement this feature request

* [ ] :warning: This feature might incur a breaking change

### Description

This should contain the posibilities to add rules based on different conditions.
Right now there is support for path and header and at least one is required.
It should be possible to allow on query, source-ip, request method as well

(https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticloadbalancingv2-listenerrule-conditions.html)

### Proposed Solution

Not sure if this requires a breaking change or if it could be added with just new API.

### Environment

  - **CDK CLI Version:** 
  - **Module Version:** 
  - **OS:** 
  - **Language:**

**Comment by michaelbrewer** [comment]
This is related to issue : #5739

**Comment by rzamana** [comment]
@rix0rrr 
I decided to take a look at this issue to help fix it! But I don't agree with the labels "good first use" and "effort/small".

Today, the `ApplicationListenerRule` is ready to work including the values for _host-header_ and _path-pattern_ in the **Values** field. To create the other conditions we need to move to the new concept in the CloudFormation documentation, and start using the specific fields ('HostHeaderConfig', 'PathPatternConfig' and so on). So this requires more effort than first imagined!

**Comment by jverhoeks** [comment]
Currently hostHeader and pathPattern only support a single string. They conversion to array is done directly here: https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-listener-rule.ts#L196

Would be nice to have it support also multiple hostHeaders
