### ISSUE TITLE
Override / Remove y/n prompt

### ISSUE THREAD

**Issue by ColWillis** [aws/aws-cdk#3894]
As requested in the Forum:
https://forums.aws.amazon.com/thread.jspa?threadID=308982

Please provide a mechanism to override or remove the y/n prompt for a cdk deploy or destroy.

Big thx!

**Comment by rhboyd** [comment]
There’s a flag you can supply that’s something like “—require-approval never” and it will bypass that prompt.

**Comment by ColWillis** [comment]
Hey @rhboyd , thanks for the suggestion.

It appears that only works for the deploy but NOT the destroy:
(I have a Java CDK executed in Jenkins)...

> cdk -o ./target/cdk.out/ --app mvn exec:java destroy <app> --require-approval never
...BUILD SUCCESS...
Are you sure you want to delete: gymdiet-pipelinesmasterpipeline (y/n)?

> cdk -o ./target/cdk.out/ --app mvn exec:java deploy <app> --require-approval never
...BUILD SUCCESS...
<app>: deploying...

**Comment by rhboyd** [comment]
does `yes | cdk destory .....` work?

**Comment by bgdnlp** [comment]
Yes, `yes | cdk destory ...` does work.

Not sure if yes is available on Windows via the Linux layer. Still, there should be a command line option anyway.

**Comment by jogold** [comment]
`cdk destroy --force`

**Comment by ColWillis** [comment]
Superb @jogold 

For deploy use --require-approval never
For destroy use --force

This works for on both Windows and Linux

**Comment by eladb** [comment]
I think `—force` should apply to deploy as well

**Comment by ColWillis** [comment]
Sorry for closing the ticket @eladb 

I tried --force for a deploy but the prompt still appeared...I will test and confirm later

**Comment by rhboyd** [comment]
@ColWillis, I think @eladb meant that CDK is missing that feature and should have it so he reopened the issue so one of the engineers can add the behavior.

**Comment by vaneek** [comment]
@eladb I’m all for consistency not only in this project but across the board with all other AWS tools, frameworks, CLI’s, etc.

**Comment by ColWillis** [comment]
I can confirm --force does **not** work for a deploy.

**Comment by shivlaks** [comment]
> I can confirm --force does **not** work for a deploy.

That's right it needs to be implemented.
When adding the `--force` functionality to destroy, the deploy behavior should be updated to also take in the same flag for the same behavior.

**Comment by badi159** [comment]
`echo yes | cdk $1 --require-approval never`
works for both deploy and destroy.

**Comment by shivlaks** [comment]
@badi159  `deploy`, `destroy`, and `bootstrap` all support `--force` now

Resolving this issue. Feel free to re-open if I've missed something!

**Comment by ColWillis** [comment]
I can confirm **deploy --force** now works 👍

`cdk --app "python app.py" deploy * --force`

**Comment by radiosilence** [comment]
Piping yes doesn't seem to work as it stops it being an interactive prompt.

**Comment by benbieler** [comment]
You can use the `--require-approval=never ` flag. I can confirm that it works.

**Comment by alex4u2nv** [comment]
`echo "response"` normally works for commands that prompts for a response.
For example: `echo "y" | cdk destroy stackname`

**Comment by mrgum** [comment]
just fyi require-approval can be "never", "any-change" or "broadening"
broadening is quite useful once the app is stable

**Comment by skinny85** [comment]
> `echo "response"` normally works for commands that prompts for a response. For example: `echo "y" | cdk destroy stackname`

I would strongly suggest using `cdk destroy --force` instead 🙂.

BTW, if you're ever unsure what options each of the commands take, you can run them with the `--help` switch (for example, `cdk deploy --help`).
