### ISSUE TITLE
fromTableName and fromTableArn

### ISSUE THREAD

**Issue by rhboyd** [aws/aws-cdk#3895]
### General Information

* [X] :wave: I may be able to implement this feature request

* [ ] :warning: This feature might incur a breaking change

### Description

The DynamoDB Table Construct should support two static methods fromTableName and fromTableArn to create Table objects so that grant*() methods can be used to give Lambda Functions permissions to CRUD the Table.

### Proposed Solution

Ctrl + C / Ctrl + V from maybe S3 Buckets.

### Environment

  - **CDK CLI Version:** 
  - **Module Version:** 
  - **OS:** all 
  - **Language:** all

**Comment by jatsrt** [comment]
Another use case is subscribing a lambda function to an existing(defined elsewhere) table stream.

**Comment by NGL321** [comment]
@rhboyd,

Sorry for the long delay. This seems like a totally reasonable add!

😸

**Comment by gauravj116** [comment]
Is it possible to do this using any lower level APIs?

**Comment by Pinny3** [comment]
Any news for that? Need it desperately....

**Comment by zxkane** [comment]
Any progress on it? Might I contribute PR for it.

**Comment by skinny85** [comment]
Go ahead @zxkane .
