### ISSUE TITLE
CodeBuild -> PipelineProject -> BuildSpec from Object minor error with runtime-versions

### ISSUE THREAD

**Issue by codypenta** [aws/aws-cdk#3897]
### What is the problem?

I am building a code build pipeline, in order to create a build environment, I must specify a runtime. When using BuildSpec.fromObject({}) and specifying "runtime-version" you get an error because you cannot use "-" in defining objects. 

### Reproduction Steps

``` typescript
        const dockerBuild = new cbuild.PipelineProject(this, 'DockerBuildProject', {
            environment: {
                buildImage: cbuild.LinuxBuildImage.STANDARD_2_0,
                privileged: true
            },
            environmentVariables: {
                'APP_REPOSITORY_URI': {
                    value: this.appAsset.repository.repositoryUri
                },
                'SIDECAR_REPOSITORY_URI': {
                    value: this.sideCarAsset.repository.repositoryUri
                }
            },
            buildSpec: cbuild.BuildSpec.fromObject({
                version: '0.2',
                phases: {
                    install: {
                        runtime_versions: { // Can't use "runtime-versions"
                            docker: 18
                        }
                    },
                    pre_build: {
                        commands: '$(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)'
                    },
                    build: {
                        commands: [
                            'docker build -t $APP_REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION dash',
                            'docker build -t $SIDECAR_REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION nginx'
                        ]
                    },
                    post_build: {
                        commands: [
                            'docker push $APP_REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION',
                            'docker push $SIDECAR_REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION',
                            `printf '{ "imageTag": "'$CODEBUILD_RESOLVED_SOURCE_VERSION'" }' > imageTag.json`,
                        ],
                    },
                },
                artifacts: {
                    files: 'imageTag.json'
                },
            })
        })
```

### Verbose Log

[Container] 2019/09/01 01:55:29 Phase context status code: YAML_FILE_ERROR Message: This build image requires selecting at least one runtime version 

The fix is here [Bug fix](https://docs.aws.amazon.com/codebuild/latest/userguide/troubleshooting.html#troubleshooting-build-must-specify-runtime) which is just manually changing it from "runtime_versions" to runtime-versions" but there is no way to do this in the CDK.

### Environment

  - **CDK CLI Version:** 1.6.1
  - **Module Version:** 1.6.1
  - **OS:** MacOS
  - **Language:** Typescript

**Comment by jeshan** [comment]
Declaring runtime versions works fine for me.
I think it's just that you misunderstood the typescript/javascript syntax. When there's a dash, you should enclose it in a string, e.g try this: `'runtime-versions'`

By the way, there are escape hatches in case it really wasn't possible in the cdk. You can get a reference to the cloudformation resource with `dockerBuild.node.defaultChild`. See escape hatches:
https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html?shortFooter=true

**Comment by codypenta** [comment]
Yep, this is the perfect answer.
