### ISSUE TITLE
aws-ecs-patterns Service to use TaskDefinition

### ISSUE THREAD

**Issue by iamyaoxi** [aws/aws-cdk#3901]
### General Information
* [X] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

### Description
The main request is to be able deploying multiple containerised app in one single Service in LoadBalancedService. 

### Proposed Solution
At first, I thought we can just change ServicePropsBase `image` attribute to `images`, and accept array of ContainerImage. But after some thought, using TaskDefinition will be more useful.

Any opinion?

**Comment by codypenta** [comment]
Sounds pretty neat, I believe there's a feature request somewhere here already about having multiple images. I would caution avoiding FargateTaskDefinition, as Fargate task only supports awsvpc networking. Meaning if you wanted to something like this https://github.com/awslabs/ecs-nginx-reverse-proxy/tree/master/reverse-proxy, you wouldn't be able to yet.

**Comment by iamyaoxi** [comment]
You're right. There was another issue #3674 discussing the same thing... And since we can actually access TaskDefinition from LoadBalancedService, I guess this wouldn't be needed as much.
