### ISSUE TITLE
RFC? StepFunctions DSL

### ISSUE THREAD

**Issue by rhboyd** [aws/aws-cdk#3909]
Maybe I'm missing something but the StepFunctions seems to be a bit rough if the StateMachine has several paths it could take. Suppose I had a StateMachine that went `A->B->C->D->Task.Success()` but errors in A and C are caught with an `addCatch()` method and land in `E`. The failure path would be `E->F->G->Task.Fail()`. With the current `definition: Chain` in a StateMachine definition, there's no easy way to make sure the failure chain is included so I have to manually do 
```
E.next(F);
E.next(G);
G.next(H):
```
separate from my StateMachine chain.  

perhaps the definition could be a collection of chains? Either there's already some easier way to do this that I couldn't find or it might take some thinking to improve the DSL.

**Comment by davidbarsky** [comment]
My ignorance of how JSII works notwithstanding, I would prefer to use async/await to describe Step Functions. Async/await communicates the asynchronous nature of these operations, while supporting branching code that functional combinators have immense difficulty doing. The final portion of the [TypeScript Step Functions example](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-stepfunctions-readme.html#typescript-example) could be rewritten as something like:

```typescript
let definition = await submitJob;
let definition = await waitX(definition)
let definition = await(getStatus);
// assuming https://github.com/tc39/proposal-pattern-matching lands in TypeScript

const definition = case(sfn.Status) {
  when (Status.Failed) -> jobFailed,
  when (Status.Succeeded) -> finalStatus,
  when _ -> waitX,
};

new sfn.StateMachine(this, 'StateMachine', {
    definition,
    timeout: Duration.minutes(5)
});
```

Unfortunately, I can think of a few complications off the top of my head:
- Recent releases of JavaScript (but not TypeScript!) support `await`ing any class with a `then()` method. `.next()` can't, to the best of my knowledge, be changed to `.then()`.
- Node promises are eagerly—as opposed to lazily—evaluated, which seems to be at odds with how step functions _ought_ be defined in code.

**Comment by rix0rrr** [comment]
I have gone back and forth on deciding whether or not to recreate the `try/catch` block feature. But given that ASL doesn't natively have a "block" feature built in, and it could be recreated by a single-branch parallel, I decided not to.

Of course, a single-branch parallel has cost implications (it would cost you an extra transition for every workflow), but I didn't want to complicate this library more.

It should be possible to define a try-catch construct that adds a catch to every state inside it, though, should anyone be so inclined.

----

@davidbarsky you got it, the promises wouldn't translate very well over jsii, and in any case it wouldn't help a lot. It's not like SWF's Flow framework where it's actually *your* code that's running at workflow execution time, we just have to suspend it at opportune moments. We actually do need a *description* of the entire workflow built in a synchronous manner.

I have trouble seeing how it could be anything other than *some kind* of fluent API. But I'm very open to suggestions!
