### ISSUE TITLE
Environment variable parsing of CDK lambda is not working properly

### ISSUE THREAD

**Issue by tpai** [aws/aws-cdk#3918]
### What is the problem?

When using environment variables to define lambda function, the value will become totally different in AWS console panel.

### Reproduction Steps

1. Define a `TIMETABLE` variable with `17:00` string.

    ```ts
    const lambdaFn = new lambda.Function(this, 'Singleton', {
      environment: {VALUE: 123, 'TIMETABLE': '17:00'}
    });
    ```

1. Generate `template.yaml`.

    ```
    cdk synth --no-staging > template.yaml
    ```

    And the `TIMETABLE` seems weird from here.

    ```
    SingletonXXXXXXX:
      Type: AWS::Lambda::Function
      Environment:
        Variables:
          VALUE: "123"
          TIMETABLE: 17:00
    ```

1. Go to lambda function of AWS console panel, and the value of environment variable `TIMETABLE` is  `1020`.

### Environment

  - **CDK CLI Version:** 1.6.1
  - **Module Version:** 1.6.1
  - **OS:** OSX Mojave
  - **Language:** TypeScript

**Comment by rhboyd** [comment]
This is why the cloudformation team needs to update to a version of YAML that isn't 100 Million years old.

https://medium.com/@sidneyliebrand/the-greatnesses-and-gotchas-of-yaml-5e3377ef0c55

> We’ve already seen some weird behavior with some unquoted string values magically turning into booleans but there is more! YAML parses numbers in ii:jj format in base 60! 

I'm not sure there's anything CDK can do because CDK is outputting the correct JSON, but YAML (in its infinite wisdom) is stripping the quotes off the `"17:00"`

**Comment by tpai** [comment]
@rhboyd If CDK can provide an option to use `template.json` as stack building input, it will work around this.

**Comment by rhboyd** [comment]
yeah, that's what's confusing to me. CDK has been pretty insistent on sticking with JSON as the output format, but they deploy the YAML version to S3 and the JSON->YAML conversion is what's stripping the `"` off the `"17:00"`

**Comment by nija-at** [comment]
As @rhboyd pointed out, this is coming from the serializing function of the underlying [YAML library](https://www.npmjs.com/package/yaml).

You could use the `--json` option of `cdk synth` to generate the output in JSON, or use the one we generate for every synth command that you can find in the `cdk.out` folder. 
Would this sufficiently mitigate what you're trying to do here?

`cdk deploy` uses the JSON format, so this shouldn't occur when the stack is deployed via the `deploy` command.

**Comment by nija-at** [comment]
However, I'm unable to reproduce this -

Here's my CDK app -
```typescript
#!/usr/bin/env node
import cdk = require('@aws-cdk/core');
import lambda = require('@aws-cdk/aws-lambda');

class FirstStack extends cdk.Stack {

    constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
      super(scope, id, props);

    const firstLambda = new lambda.Function(this, 'firstLambda', {
        functionName: 'FirstLambda',
        code: lambda.Code.asset('resources'),
        handler: 'index.handler',
        runtime: lambda.Runtime.NODEJS_10_X,
        environment: {
          'TIME': '17:00'
        }
      });
    }
}
  
const app = new cdk.App();
new FirstStack(app, 'FirstStack');
app.synth();
```

Running `cdk synth --no-staging` generates YAML with this snippet in it -
```yaml
  firstLambda395F9ADE:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Role:
        Fn::GetAtt:
          - firstLambdaServiceRoleB6408C31
          - Arn
      Runtime: nodejs10.x
      Environment:
        Variables:
          TIME: "17:00"
      FunctionName: FirstLambda
```

And deploying the YAML file through Cloudformation yields a Lambda function -
```shell
⇒  aws lambda get-function-configuration --function-name FirstLambda
{
    ...
    "Environment": {
        "Variables": {
            "TIME": "17:00"
        }
    },
    ...
}
```

**Comment by rhboyd** [comment]
I was able to reproduce this several different ways. I’ll get some sample
code posted shortly.

**Comment by rhboyd** [comment]
This is strange. It's working now. I remember reproducing this several times trying to escape the string characters so it wouldn't strip them.

**Comment by nija-at** [comment]
Closing this for now. Re-open if you see it again.
