### ISSUE TITLE
Documentation doesn't specify how magic "private" vs "public" subnet type is determined

### ISSUE THREAD

**Issue by kjpgit** [aws/aws-cdk#3924]
Reading the docs at https://pypi.org/project/aws-cdk.aws-ec2/

Nothing says how subnet type is determined, for example when I call:

``` py
vpc =  aws_ec2.Vpc.from_lookup(self, "vpc", vpc_name="MyManuallyCreatedVPC")
 print(vpc.private_subnets)
 print(vpc.public_subnets)
```

It shows all of the subnets as private, even though there are some public subnets with IGWs.  cdk.context.json also shows them as all private.  

Is the CDK setting some magic tags on subnets it creates, and that doesn't work with external / manually created subnets & VPCs?

**Comment by NGL321** [comment]
Hey @kjpgit,

This looks like it might be a bug! With regard to how the subnets are supposed to be set, please refer to the documentation [here](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-ec2-readme.html#subnet-types).
If this is a bug, we can certainly look into it, but we will need more info from you before we can try to reproduce the behavior. Please see the [issue template for bugs](https://github.com/aws/aws-cdk/issues/new?labels=bug%2C+status%2Fneeds-triage&template=bug.md) for what information we will need.

😸

**Comment by kjpgit** [comment]
@NGL321 for the 2nd ticket in a row, you have responded with a link that I already put in my bug report.    You did the same thing in #3923.  And you didn't answer my question here about tags.
I'm just going to close this so we aren't wasting more time.
