### ISSUE TITLE
ec2  make the cidr_block of ISubnet visible

### ISSUE THREAD

**Issue by slipdexic** [aws/aws-cdk#3951]
### General Information

* [X] :wave: I may be able to implement this feature request

* [ ] :warning: This feature might incur a breaking change

### Description

Currently when you create a VPC , 
The VPC automatically assigns a CIDR range to each subnet , but this is not made visible to the stack.
So if you now wish to create a security group or NetworkAccessConton ,VPN static route etc
you have no Idea of what IP range was used until after the stack has deployed

Whilst this is Similar to #3931 they are different , this issue allow the end use to see with the current set up what IP range has been created and making the property visible, the other ticket is more about being able to control that property and may not be possible with the current VPC design.

### Proposed Solution

Add to the ISubnet a the CidrBlock property,
and populate it value in CreateSubnet()

### Environment

  - **CDK CLI Version:** 1.6
  - **Module Version:** 
  - **OS:** all
  - **Language:** all

**Comment by lielran** [comment]
I also didn't find a way to get the CIDR blocks per subnet once the vpc was created.

**Comment by corymhall** [comment]
Closing this since it is now possible subnets now have [ipv2cidrblock](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-ec2.Subnet.html#ipv4cidrblock)
