### ISSUE TITLE
Cannot supply both 'day' and 'weekDay', use at most one

### ISSUE THREAD

**Issue by suhaig** [aws/aws-cdk#3953]
### What is the problem?
According to CloudWatch [documentation](https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/ScheduledEvents.html#CronExpressions):
"You can't specify the Day-of-month and Day-of-week fields in the same cron expression. If you specify a value (or a *) in one of the fields, you must use a ? (question mark) in the other."

In [schedule.ts](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-events/lib/schedule.ts#L34):
```
if (options.weekDay !== undefined && options.day !== undefined) {
    throw new Error(`Cannot supply both 'day' and 'weekDay', use at most one`);
}
```

### Reproduction Steps
```
new Rule(this, "ID", {
            description: "description",
            ruleName:  "ruleName",
            schedule: Schedule.cron({
                minute: "0",
                hour: "18",
                day: "?",
                month: "*",
                weekDay: "MON-FRI",
                year: "*"
            })});
```
Example schedule is from CloudWatch documentation.

### Environment

  - **CDK CLI Version:** 1.6.1
  - **Module Version:** 
  - **OS:** Windows 10
  - **Language:** TypeScript

**Comment by rix0rrr** [comment]
Don't specify `day`, it will be set to `?` automatically.

**Comment by suhaig** [comment]
Thanks, if anyone is interested the documentation is [here](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-events.CronOptions.html).

> Absence of a field implies '*' or '?', whichever one is appropriate.
