### ISSUE TITLE
CodeSource Artefact in predefined bucket

### ISSUE THREAD

**Issue by jamiepmullan** [aws/aws-cdk#3969]
### General Information

* [ ] :wave: I may be able to implement this feature request

* [ ] :warning: This feature might incur a breaking change

### Description
I want to be able to have predefined buckets throughout my CDK Pipeline. At the moment CodeBuild supports the ability to specify a Project value that defines the S3 artifact store. I would like to be able to do something similar with Code Source. In my use case in particular I am using GitHubSourceAction but can only specify srcArtifact (i.e. a new Artifact object). I'm not sure if this is currently possible from what I've looked at in CDK doc's.

### Proposed Solution
I guess a solution could be being able to specify the Artifacts object...

### Environment
  - **OS:** all
  - **Language:** all

**Comment by SomayaB** [comment]
Hi @jamiepmullan, thanks for submitting a feature request! We will look into this and someone will update this issue when there is movement.

**Comment by skinny85** [comment]
@jamiepmullan can you explain what exactly do you want to achieve here? Maybe on an example? I'm having trouble following what is the ask here.

**Comment by jamiepmullan** [comment]
Hey @skinny85 ,

Hopefully this makes sense... but let me know if you want more information/extra clarification!

So when you use 'GitHubSourceAction' - you have no control over where your artefact goes. You can just create a 'new Artifact' and pass that into the 'output' of 'GitHubSourceActionProps'. This means when you deploy, a new S3 bucket is created and used for your GitHub Source.
Example:
`  public srcArtifact = new Artifact('jamie');
    private props: GitHubSourceActionProps = {
        actionName: SourceTrigger.Dev,
        output: this.srcArtifact,
    };
    private sourceAction = new GitHubSourceAction(this.props);
`

Where as in 'CodeBuildAction' you can pass in a 'project' which holds the definition of 'Artifacts.s3' (the bucket you want to as your artifact store). This allows me to have a centralised bucket for everything.
Example:
`private artifactStore = Bucket.fromBucketName(this, 'BucketByName', `artifact-store`);
  private prop: S3ArtifactsProps = {
        bucket: this.artifactStore,
        name: "jamie",
        path: "jamie",
   };
   public srcArtifactsLocation = Artifacts.s3(this.prop);
   protected projectProps: ProjectProps = {
        artifacts: this.srcArtifactsLocation
   };
   protected project: Project = new Project(this, 'build', this.projectProps);
`

It would be great if we could use 'Artifacts' in 'GitHubSourceAction' so that we can have 1 bucket created/deployed for holding code zips/artifacts instead of having another created.

**Comment by skinny85** [comment]
OK, now I got it. Couple of things:

1. The S3 bucket used in the Pipeline is set on the Pipeline construct, *not* with the `Artifact` class. So you can do it like this:

  ```ts
  const pipeline = new codepipeline.Pipeline(this, 'Pipeline', {
    artifactBucket: s3.Bucket.fromBucketName(this, 'Bucket', 'artifact-store'),
    // ...
  });
  ```

2. You cannot actually use a regular `Project` in a CodePipeline. You need `PipelineProject`, which does not allow setting the `artifacts` property. Either way, if you added `Project` that had `artifacts` set, it wouldn't matter, as that setting would be ignored, and the pipeline's bucket will be used anyway.

Hope this clears this up!

**Comment by jamiepmullan** [comment]
Thanks for the response - i'll give it a go... I didn't expect that behaviour from looking at the docs I must admit.

**Comment by skinny85** [comment]
Sounds good. I'll resolve this one then, feel free to comment if you still have issues,
