### ISSUE TITLE
More Adams Please

### ISSUE THREAD

**Issue by rhboyd** [aws/aws-cdk#3975]
### General Information
* [ ] :wave: I may be able to implement this feature request

* [X] :warning: This feature might incur a breaking change

### Description
@skinny85 is always super helpful in the Gitter and I don't think I've seen a customer issue in there that he hasn't been able to solve. CDK should have more Adams ( propose naming them skinny86, skinny87, skinny88, .... skinny136)

### Proposed Solution
[This seems promising](https://en.wikipedia.org/wiki/Human_cloning) though it may need to get approval from PR and Legal.

### Environment

  - **CDK CLI Version:** All
  - **Module Version:** All
  - **OS:** All
  - **Language:** primarily English, but other languages would be very helpful

**Comment by eladb** [comment]
+100!

Thanks for the reference about human cloning. Definitely looks promising! We will add to our roadmap.

**Comment by NGL321** [comment]
@rhboyd 
Thank you for the suggestion. I think we may have to look into that cloning thing.

Pending a new repo called `aws/clone-adam` I'm going to close this issue, but I will certainly update you once the cloning vats are up and running...
![clones](https://user-images.githubusercontent.com/4944099/66690302-225d9380-ec44-11e9-95ca-b8bef1ce5a7a.png)
