### ISSUE TITLE
ECS: Property 'ProxyConfiguration' is missing in type 'TaskDefinition'

### ISSUE THREAD

**Issue by pkandasamy91** [aws/aws-cdk#3977]
The ProxyConfiguration property supported by CloudFormation is not available in the TaskDefinition construct.

**Comment by tsykora-verimatrix** [comment]
This is the last missing piece that's preventing me to use App-Mesh with Fargate and CDK.
I'm very glad to see that this is now fixed. Any idea when it will be released? 
@pkandasamy91 @SoManyHs

**Comment by pkandasamy91** [comment]
@tsykora-verimatrix we'll try to get it into the next release

**Comment by tsykora-verimatrix** [comment]
> @tsykora-verimatrix we'll try to get it into the next release

that would be fantastic, can't wait to start using it :)

**Comment by iamhopaul123** [comment]
Fixed by #4007. This is now available in CDK v1.11.0. Close for now.
