### ISSUE TITLE
Global name prefix

### ISSUE THREAD

**Issue by PeterBengtson** [aws/aws-cdk#3982]
### General Information

* [ ] :wave: I may be able to implement this feature request

* [ ] :warning: This feature might incur a breaking change

### Description
I'm working as a consultant at a large international internet bank, which already has a number of security measures, standards and procedures in place to which I as a consultant have to adapt. One of these standards requires me to follow a specific naming standard for some types of resources such as lambda, security groups, ASGs, and many more – they all have to begin with a specific, team-related string, such as `theteam-`, otherwise access to the resources is blocked.

CDK currently doesn't offer any means of adding a prefix to all generated resource names, but always uses the name of the stack as the prefix. I'm sure I'm not alone in having to adapt to standards such as these, and it would be good if CDK had some means of specifying a global name prefix to be added to all resource names.

### Proposed Solution

I propose two ways of doing this: either via the CLI and a new switch to the `synth` command, such as 
```
$ cdk synth --prefix="myapp-"
```
Or, which is better, through a config setting.

### Environment

  - **CDK CLI Version:** 1.7
  - **OS:** all
  - **Language:** all

**Comment by rhboyd** [comment]
A workaround until this is resolved is that you can apply an Aspect to the resources you want named and CDK will go through an do the renaming for you when it builds the template.

**Comment by eladb** [comment]
This can be achieved by overriding the [`Stack.allocateLogicalId`][1] method and determining your own schema for logical ID allocations. Closing for now. Please reopen if you still think this is needed as an explicit feature.

[1]: https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.Stack.html#protected-allocate-wbr-logical-wbr-idcfnelement
