### ISSUE TITLE
App-Delivery PipelineDeploymentStackAction can't deploy multiple stacks per stage

### ISSUE THREAD

**Issue by eklinkhammer** [aws/aws-cdk#3984]
### What is the problem?
I am trying to use app-delivery to deploy two stacks from my deployment stage, following the [example provided](https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/app-delivery).

I get an error while trying to synthesize the cdk:
`
> cdk "synth" "-o" "dist"
Stage Deploy already contains an action with name 'Execute'`

I think the problem is because the name is hard-coded here:
https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/app-delivery/lib/pipeline-deploy-stack-action.ts#L129

### Reproduction Steps
The provided example will not deploy.

### Environment

  - **CDK CLI Version:** 1.7.0 (build 8870695)
  - **OS:** OSX
  - **Language:** TypeScript

**Comment by spac3-monk3y** [comment]
Any update on this? I'm facing the same issue.

**Comment by selvathiruarul** [comment]
This will be so useful to run the parallel pipeline actions
