### ISSUE TITLE
Json schema additionalProperties could be a boolean

### ISSUE THREAD

**Issue by daiwei920** [aws/aws-cdk#3993]
### What is the problem?
Try to use API gateway body validator, the json schema 'additionalProperties' could also be a boolean.

### Reproduction Steps
Unable to add "additionalProperties": false to disable addtional properties in my schema.

To fix, in the json-schema.ts, additionalProperties should be something like 
readonly additionalProperties?: 'JsonSchma | boolean';

### Verbose Log
I have verified in API gate way body validator, it works after my fix.

### Environment

  - **CDK CLI Version:** 1.7.0 (build 8870695)
  - **Module Version:** 1.6.1
  - **OS:** Ubuntu
  - **Language:** TypeScript

**Comment by SomayaB** [comment]
Hi @daiwei920, thank you for reaching out. What you have asked is contrary to the purpose of that member. The purpose of `additionalProperties?` exists to allow appending additional `jsonSchema` properties, and if you don't want additional properties it should just be left blank. 

Let me know if you have any additional questions or if I misunderstood your problem otherwise I will close out this issue shortly.

**Comment by daiwei920** [comment]
Hi Somaya,

Thanks for replying. I have tried to set additionalProperties = {}, in API gateway body validator, it doesn't seem to work.
It still allows me to add additional properties. However, if I change the schema to
   "additionalProperties"=false
in body validation model, it works! The CDK doesn't allow me to pass a Boolean value.

By the way the standard jsonschema<https://www.npmjs.com/package/jsonschema> in nodeJS only allowing to pass Boolean.

I hope it clarified my question.

Thanks
David


________________________________

**Comment by SomayaB** [comment]
Hi @daiwei920, so sorry for the late reply. Are you still having this issue?

**Comment by daiwei920** [comment]
not anymore I have fixed this issue and my fix has been merged in too. Thanks

david

From my phone

在 2020年3月10日，上午6:57，Somaya <notifications@github.com> 写道：

﻿

Hi @daiwei920<https://github.com/daiwei920>, so sorry for the late reply. Are you still having this issue?
