### ISSUE TITLE
Pipeline Event role not able to specify custom role

### ISSUE THREAD

**Issue by nikhilbhoj** [aws/aws-cdk#3999]
### General Information

* [ ] :wave: I may be able to implement this feature request

* [ ] :warning: This feature might incur a breaking change

### Description

When I have created a Pipeline and used codecommit as the source of code it start executing when code is pushed in the master branch.
To do that CDK created a PipelineEvent role and its policy. 

In my Organization, unless the role does not attach a boundary policy and the policy need to be a managed policy not a inline policy the CDK stack creation is failing.

### Proposed Solution

Please provide a role specification for this use-case , which I believe may be useful for other services.
Or is their any way in my which I can inspect the existing stack that is being creating and change the role properties from Inline to managed policy or substitute it with the role created by me.

I do not wanted the role which is not created explicitly to be created by CDK other wise my stack creation will fail. 
### Environment

  - **CDK CLI Version:**  cdk 1.7
  - **Module Version:**  aws-events and aws-pipeline
  - **OS:**  Ubuntu 16
  - **Language:**  Typescript

**Comment by nikhilbhoj** [comment]
I have tried below 

const rule = new events.Rule(stack, 'rule', {
      schedule: events.Schedule.expression('rate(1 minute)'),
      targets: [ new targets.CodePipeline(cdkpipeline)],
          
    });
    
  const ruleresource = rule.node.defaultChild as events.CfnRule;

 
ruleresource.roleArn=pipelineEventerole.roleArn; 

ruleresource.addPropertyOverride('AWS::IAM::Role',pipelineEventerole);


pipelineEventerole I have already created in my code.

But it is not working.

**Comment by skinny85** [comment]
Thanks for opening the issue @nikhilbhoj .

To unblock yourself, you can do something like this:

```ts
        // do this first
        const myRole = new iam.Role(cdkpipeline, 'EventsRole', {
            assumedBy: new iam.ServicePrincipal('events.amazonaws.com'),
        });

        // now this will use myRole above instead of creating a new one
        const rule = new events.Rule(this, 'rule', {
            schedule: events.Schedule.expression('rate(1 minute)'),
            targets: [ new targets.CodePipeline(cdkpipeline)],
        });
```

But long-term, I think you're right - you should be allowed to pass a custom role when creating the target. I'll work on aPR adding that to the `CodePipeline` target.

Thanks,
Adam

**Comment by nikhilbhoj** [comment]
Thanks @skinny85 for working on this and I can see you have also made the relevant code changes which hopefully will be roled out out in next release.  

I will also try your suggestion as mentioned above.

**Comment by newcomer** [comment]
Hi @skinny85, we have the same issue for `@aws-cdk/aws-events-targets.CodeBuildProject`. Could you please add role config for CodeBuildProject as well?

**Comment by skinny85** [comment]
Hey @newcomer ,

I'm pretty swamped right now :/. Any chance you would be able to submit us a PR with this change, based on #4006 that I made for `@aws-cdk/aws-events-targets.CodePipeline`? This one should be very similar. Check out our 'Contributing' guide here: https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md .

Thanks,
Adam

**Comment by newcomer** [comment]
@skinny85 , I've filed the issue https://github.com/aws/aws-cdk/issues/10866 and opened corresponding PR https://github.com/aws/aws-cdk/pull/10865

**Comment by skinny85** [comment]
Thanks @newcomer , approved - should be merged soon!
