### ISSUE TITLE
Api gateway: defaultMethodOptions.requestParameters are not applied

### ISSUE THREAD

**Issue by svenrienstra** [aws/aws-cdk#4034]
### What is the problem?
When creating a proxy resource for the API gateway the defaultMethodOptions.requestParameters are not applied to the default ANY method. 

### Reproduction Steps
```
const resource = rootAPI.root.addResource('google');
const proxy = resource.addProxy({
  defaultMethodOptions: {
    requestParameters: {"method.request.path.proxy": true}
   },
  defaultIntegration: new apigateway.HttpIntegration('https://google.com/{proxy}', {
    httpMethod: 'ANY',
    options: {
      requestParameters: {'integration.request.path.proxy': 'method.request.path.proxy'}
    }
  })
});
```
RequestParameters will be not be set for this proxy resource's default ANY method.

### Environment

  - **CDK CLI Version:** 1.7.0 (build 8870695)
  - **Module Version:** 1.7.0 ("@aws-cdk/aws-apigateway")
  - **OS:** OSX
  - **Language:** TypeScript

### Solution
Problem is in https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-apigateway/lib/method.ts

In the constructor some properties are copied from the defaultMethodOptions, for example:
`operationName: options.operationName || defaultMethodOptions.operationName,`
but this is not true for requestParameters:
`requestParameters: options.requestParameters,`

Workaround:
`const cfnProxy = proxy.anyMethod!!.node.defaultChild as CfnMethod;
      cfnProxy.requestParameters = {"method.request.path.proxy": true}`

**Comment by nija-at** [comment]
Thanks for the detailed report here @svenrienstra, as well as, diving into our code and identifying why this doesn't happen.

Your suggestion to use the `defaultMethodOptions.requestParmeters` seems right to me.

We're unable to get to fixing this right away, however, we're actively encouraging and reviewing PRs. Sending out a PR might be the fastest way to get this fixed, if you are able 😊

**Comment by svenrienstra** [comment]
See https://github.com/aws/aws-cdk/pull/4249 :)
