### ISSUE TITLE
Add stage and parameter file for stage

### ISSUE THREAD

**Issue by mirazmamun** [aws/aws-cdk#4056]
Might be addressed by #1499 
### General Information
* [x] :wave: I may be able to implement this feature request
* [x] :warning: This feature might incur a breaking change

### Description
I am proposing a feature to define the *stage* status of the infrastructure. This will help contextualize and isolate the set of infrastructure targeted for different environment. It will allow authors of IaC to contain the changes within the context of the stage and allow reproducing the target infrastructures or modifying the incrementally as long as they are in the same stage.

Additionally it will drive the practice of separating the parameter for the stages to be fed from text files and keep them outside of VCS for better security and make the workflow stateless.

### Proposed Solution
Here are my mind dumps:

- Have a CLI option like `cdk synth --stage [dev|staging|prod]` which will set the `app` level or stack level Environment property called `stage`. Or stage can be set from Stack instance property of Environment using `@aws-cdk/core.Environment` interface
- It can support reading a stage specific parameter input file following convention pattern like `stage` prod would read prod.yml file or any file defined by --stage-file CLI option. This will then inject it into stack properties

### Environment

  - **CDK CLI Version:** 1.8.0
  - **Module Version:** NA
  - **OS:** all
  - **Language:** all

### Other information
NA

**Comment by eladb** [comment]
Any reason `--context stage=prod` and `this.tryGetContext('stage')` can't be used to this purpose?

**Comment by SomayaB** [comment]
> Any reason `--context stage=prod` and `this.tryGetContext('stage')` can't be used to this purpose?

@mirazmamun

**Comment by SomayaB** [comment]
I will close this issue since there hasn't been activity on it in a while and it seems to have been resolved by the above comment. Feel free to reopen.
