### ISSUE TITLE
"BlockPublicAccess" should be named "PublicAccessBlockConfiguration"

### ISSUE THREAD

**Issue by joyofdata** [aws/aws-cdk#4059]
#3309  :question: General Issue

### The Question
Why would the class [BlockPublicAccess](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_s3/BlockPublicAccess.html) not be named [PublicAccessBlockConfiguration](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-publicaccessblockconfiguration.html) when that is what it corresponds to?

I hope you avoid naming inconsistencies going forward as this will help with adoption tremendously.

**Comment by eladb** [comment]
All CDK types are about "Configuration" and therefore we normally don't use the "Configuration" postfix. Semantically these are the same thing.
