### ISSUE TITLE
jest.config.js ignored by typescript .gitignore

### ISSUE THREAD

**Issue by engineal** [aws/aws-cdk#4073]
### The Question

The `cdk init app --language typescript` command creates a `jest.config.js` file in the new project, as well as a `.gitignore` file that excludes `*.js`. As a result, `jest.config.js` won't be committed.

### Environment

  - **CDK CLI Version:** 1.8.0 (build 5244f97)
  - **Module Version:** 1.8.0 (build 5244f97)
  - **OS:** all
  - **Language:** TypeScript

### Other information

Suggestions to fix:
- Only exclude `*.js` in `bin`, `lib`, and `test` directories
- add `!jest.config.js` to the `.gitignore`

**Comment by rhboyd** [comment]
Sorry, this was my bad. I just submitted a PR to fix it.
