### ISSUE TITLE
Lambda Layer CDK Metadata has wrong property for Content

### ISSUE THREAD

**Issue by abrooksv** [aws/aws-cdk#4076]
### What is the problem?
SAM Local issue: https://github.com/awslabs/aws-sam-cli/issues/1411

The CDK metadata lists the property as `Code`, but the CFN property is `Content`

```
      "Metadata": {
        "aws:cdk:path": "Stack-Dev/Layer/Resource",
        "aws:asset:path": "/tmp/aws-lambda-layer-kubectl/layer.zip",
        "aws:asset:property": "Code"
      }
```

### Reproduction Steps
```
       const gitLayer = new lambda.LayerVersion(this, "Layer", {
            code: lambda.Code.fromAsset("/tmp/aws-lambda-layer-kubectl/layer.zip")
        })
```

### Environment

  - **CDK CLI Version:** 
  - **Module Version:** 
  - **OS:**  OSX
  - **Language:** TS

**Comment by eladb** [comment]
Fix in: https://github.com/aws/aws-cdk/pull/4205

**Comment by abrooksv** [comment]
Thank you, Elad. Appreciate the quick turn around.
