### ISSUE TITLE
Cdk python document mixed with Node.js code example

### ISSUE THREAD

**Issue by zanhsieh** [aws/aws-cdk#4081]
### What is the problem?
Python document mixed with node.js code. For example, construct a new Vpc:

https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_ec2/Vpc.html

```
import { SubnetType, Vpc } from '@aws-cdk/aws-ec2'

const vpc = new Vpc(this, 'TheVPC', {
   cidr: "10.0.0.0/16"
})

// Iterate the private subnets
const selection = vpc.selectSubnets({
   subnetType: SubnetType.PRIVATE
});

for (const subnet of selection.subnets) {
   // ...
}
```
This is node.js / typescript code, not python code.

Advanced Subnet Configuration
Connection Peers
....

https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_ec2.README.html

Amazon ECR Construct Library

https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_ecr.README.html

### Reproduction Steps
Simple. For Vpc, in CLI do this:

```
$ python
>>> from aws_cdk.aws_ec2 import Vpc
>>> help(Vpc)
```

### Environment

  - **CDK CLI Version:1.8.0 (build 5244f97)** 
  - **OS:OSX Mojave** 
  - **Language:Python** 

Original link for issue:
https://github.com/aws-samples/aws-cdk-examples/issues/119

**Comment by gary-cowell** [comment]
I'm finding the python documentation extremely lacking in many areas. Too few examples, and littered with typescript syntax.

Example:

[https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_ecs.README.html#task-definitions](Task Definition)

Shows:

`const ec2TaskDefinition = new ecs.Ec2TaskDefinition(this, 'TaskDef', {
  networkMode: NetworkMode.BRIDGE
});

const container = ec2TaskDefinition.addContainer("WebContainer", {
  // Use an image from DockerHub
  image: ecs.ContainerImage.fromRegistry("amazon/amazon-ecs-sample"),
  memoryLimitMiB: 1024
  // ... other options here ...
});`

There are too many to list really.

I do notice some pages have a "need help translating typescript to python" link on them which is "great".

**Comment by rix0rrr** [comment]
We are aware that all examples are in TypeScript and not in your language of choice (be it Python, Java or C#).

This is unfortunately the way things are today. We'd rather leave the examples in than take them out altogether, as the shape of the code should still be the same and you should be able to use a short set of translation rules to  end up with code that would work in your language.

Rest assured that we are working on providing example code in multiple languages.

**Comment by zanhsieh** [comment]
@rix0rrr 
I understood what cdk documentation situation now. Just curious about how to contribute on the documentation part.

**Comment by rix0rrr** [comment]
We are actually not going to convert the examples manually, but are building a system to do it automatically. As such, there is no place to contribute for now. When we're done everything will be converted all at once. 

Thanks for the offer to contribute! There may be some examples that may need work in the future, at which point we'll gladly take you up on that :).

**Comment by adinemer** [comment]
@rix0rrr actually, in some cases the code shape differs. Is there a time frame for a proper python API reference (fully documented)

**Comment by rix0rrr** [comment]
@adinemer could you give an example of a case where it differs? I'd like to make sure we cover that case in the automatic translation.

Can't give you a time frame, sorry.
