### ISSUE TITLE
Increase control and safety of JSON serialization

### ISSUE THREAD

**Issue by whilp** [aws/aws-cdk#4082]
### General Information

* [x] :wave: I may be able to implement this feature request

* [x] :warning: This feature might incur a breaking change

### Description

The CDK serializes its constructs to CloudFormation JSON; it also uses the md5 hash of the serialized form of components within a template to generate logical IDs. In these cases, the serialization may vary depending on the way that the template is constructed. The rules for `JSON.stringify` are a little complicated and have evolved over time, but generally (IIUC) the properties on an `Object` are serialized in the order in which they are inserted.

If the order of insertion for `Object` properties does change, this increases the likelihood that the template's checksum changes or the logical IDs within the template change. And for build systems (like bazel.build) that rely on deterministic outputs, this may result in spurious rebuilds.

### Proposed Solution

1. Choose a stable default for serialization. There are various options, eg [safe-stable-stringify](https://github.com/BridgeAR/safe-stable-stringify/) or [json-stable-stringify](https://github.com/substack/json-stable-stringify).
2. Expose (perhaps on `AppProps`?) knobs so that the user can control serialization, including `spaces`, stableness/key sorting, newline at end of file, etc.

(2) is nice to have when producing "golden" outputs (like the `integ` tests) that may need to comply with project-wide formatting standards.

### Environment

  - **CDK CLI Version:** 
  - **Module Version:** 
  - **OS:** 
  - **Language:**

**Comment by NGL321** [comment]
Hey @whilp,

This is a really interesting proposal. I think it definitely warrants more discussion.
