### ISSUE TITLE
Create route53 target for ec2.Instance

### ISSUE THREAD

**Issue by abelmokadem** [aws/aws-cdk#4084]
### General Information

* [x] :wave: I may be able to implement this feature request

* [ ] :warning: This feature might incur a breaking change

### Description

It would be great to have a route53 target, now that we have an ec2.Instance construct. There should be a possibility to select between the public ip or private ip.

### Proposed Solution

Something like this would be nice:
```
import route53 = require("@aws-cdk/aws-route53");
import targets = require("@aws-cdk/aws-route53-targets");
...
    const dnsRecord = new route53.ARecord(this, "ARecord", {
      recordName: `windows-bastion.${props.hostedZone.zoneName}`,
      zone: props.hostedZone,
      target: new targets.Ec2InstancePublicIpTarget(instance),
      target: new targets.Ec2InstancePrivateIpTarget(instance) // or
      target: new targets.Ec2InstanceTarget(instance, targets.Ec2InstanceTargetType.PUBLIC_IP)
    }
```

### Environment

  - **CDK CLI Version:** 1.8.0
  - **Module Version:** 1.8.0
  - **OS:** macOS Sierra
  - **Language:** TypeScript

**Comment by nmussy** [comment]
I'm not familiar with private hosted zones, but can they contain public IP adresses? If not, we could exclusively bind public EC2 IPs for public hosted zones and private IPs for private zones.

**Comment by abelmokadem** [comment]
I went into the source code and realised that what I suggested would not work in the case of EC2 instances. However, would the following interface be something that could work? I noticed that this causes a cyclic dependency between ec2 and route53.

```
    const dnsRecord = new route53.ARecord(this, "ARecord", {
      recordName: `windows-bastion.${props.hostedZone.zoneName}`,
      zone: props.hostedZone,
      target: instance.publicIpRecordTarget!
    });
```

```
// EC2.Instance
  /**
   * Private IP based record target for the instance.
   */
  public readonly privateIpRecordTarget: RecordTarget;

  /**
   * Public IP based record target for the instance. Only usable when subnet selection contains a public subnet.
   */
  public readonly publicIpRecordTarget?: RecordTarget;
```

**Comment by NGL321** [comment]
Hey @abelmokadem,

Sorry for the slow response, this seems like a reasonable feature to add. If you would like to implement it that would be a great contribution.

As for the particulars of the implementation, unfortunately I am not that familiar with the Route53 construct library. I recommend asking in the [Gitter](https://gitter.im/awslabs/aws-cdk) room.  @shivlaks is the codeowner for the library.

**Comment by kiros-sc** [comment]
Hello, I think it would be a really good feature, and why?
I'm creating a cdk for the new vpn, and ofcourse I'm also creating a new recordSet for it, and I've already spent more than 2hours trying to get the record to match the EIP assign to the new instance.
I try with "route53.RecordTarget.fromValues" and "oute53.RecordTarget.fromalias" and nothing, in many cases the record was crested ok,. correct domainname, but the ip had no idea where it was coming from. 
At the end this is the solution I found...
```
      const vpnDnsRecord = new route53.ARecord(this, "vpnDnsRecord", {
          recordType: RecordType.A,
          recordName: "vpn-xxx",
          zone: hostedZone,
          target: route53.RecordTarget.fromIpAddresses(vpnElasticIP.ref),
          // target: route53.RecordTarget.fromValues(vpnInstance.instance.attrPublicIp),
          ttl: Duration.seconds(60),
      });
```
Just so you understand:
zone: hostedZone, >> I imported my hostedZone
target: route53.RecordTarget.fromIpAddresses(vpnElasticIP.ref), >> I have a const "vpnElasticIP".
Honestly I don't underdtand whi that work and not the other test, and one thing that I already told in this tickets...

PLEASE IMPROVE CDK DOCUMENTATION, it's really bad and not easy to understand to those who are not that familiar with cdk or coding.... (take a look to terraforms docs... great! full of examples, cases, test, etc.)

**Comment by ryanjdillon** [comment]
Pinging here to get this on radar as I also think a nice example in the docs would be great for this use-case
