### ISSUE TITLE
[lambda] allow undefined values for environment variables

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#4085]
### Description

When specifying environment variables for AWS Lambda, it should be possible to pass in a value of `undefined`, in which case the variable should not be set.

This will allow improvement of ergonomics when defining environment variables declaratively:

```ts
new lambda.Function(this, 'Foo', {
  // ...
  environment: {
    KEY: foo === 'bar' ? 'value' : undefined
  }
}
```

**Comment by nmussy** [comment]
I've given it a shot, but it seems like JSII doesn't like it. Either of the following throw an error:

```ts
readonly environment?: { [key: string]: string | undefined };
readonly environment?: { [key in string]?: string };

error TS9999: JSII: Encountered optional value in location where a plan type reference is expected
```

**Comment by RomainMuller** [comment]
I'll have to check on this. It looks like the first option should've worked (`{ [key: string]: string | undefined }`)
