### ISSUE TITLE
Security Group created by ecs_patterns.LoadBalancedFargateService for NetworkLoadBalancedFargateService construct does not have any Inbound rules.

### ISSUE THREAD

**Issue by PradeepKamathC** [aws/aws-cdk#4091]
When NetworkLoadBalancedFargateService construct is used to create a Fargate Service with a Network load balancer, the security group associated with the AWSVpcConfiguration property does not have any inbound rule associated with it. Due to this, the load balancer target is marked unhealthy, and the network load balancer is unable to accept any traffic. 

Repro : 
- Use this construct : https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs-patterns.NetworkLoadBalancedFargateService.html
- Check the CFN template generated, the security group would not have any inbound rule.

**Comment by rix0rrr** [comment]
Duplicate of https://github.com/aws/aws-cdk/issues/1490
