### ISSUE TITLE
CloudFormation is waiting for NetworkInterfaces associated with the Lambda Function to be cleaned up

### ISSUE THREAD

**Issue by mouyigang** [aws/aws-cdk#4119]
cdk destroy takes very long time when deployed lambda within VPC

### Reproduction Steps

This must be a known issue however I want to post it here see if cdk can help to solve this.

### Environment

  - **CLI Version      :1.8
  - **Framework Version:1.8
  - **OS               :Mac
  - **Language         :TS

### Other

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
I'm afraid not. This is squarely in CloudFormation territory.

**Comment by kethanva** [comment]
I  still am facing the same problem. Strangely even after AWS folks mentioned that they have fixed it (https://aws.amazon.com/blogs/compute/announcing-improved-vpc-networking-for-aws-lambda-functions/)

Workaround options to mitigate the problem :
* Get the list of Lambda functions(with VPC connectivity) that are in waiting state. Delete them manually or with automation.
* Add Lambda function IAM(policy) with "ec2:DeleteNetworkInterface" and "ec2:DetachNetworkInterface".
