### ISSUE TITLE
ALB Target Group UnHealthyHostCount metric has wrong name

### ISSUE THREAD

**Issue by alopix** [aws/aws-cdk#4128]
The ALB target group function `metricUnhealthyHostCount` will generate a wrong metric name `UnhealthyHostCount` instead of the `UnHealthyHostCount`.

### Reproduction Steps

```
const targetGroupMetric = applicationTargetGroup.metricUnhealthyHostCount({
      period: Duration.minutes(1),
      statistic: 'Maximum'
});
```

### Error Log

The alarm will be created but never get data, because of the incorrect metric name. Cannot even change it manually, as it's a read-only property.

### Environment

  - **CLI Version      :** 1.8.0
  - **Framework Version:** 1.8.0
  - **OS               :** macOS
  - **Language         :** Typescript

### Other

Line that requires fixing: https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-target-group.ts#L232

--- 

This is :bug: Bug Report

**Comment by nmussy** [comment]
Weird, it was correctly set for NLB: https://github.com/aws/aws-cdk/blob/4a0272db5eb9aae5f440bb0813fdbad6514b60c3/packages/%40aws-cdk/aws-elasticloadbalancingv2/lib/nlb/network-load-balancer.ts#L156

I'll make a PR

**Comment by alopix** [comment]
Noticed that as well. Thanks.
