### ISSUE TITLE
ec2.Instance does not implement IGrantable

### ISSUE THREAD

**Issue by abelmokadem** [aws/aws-cdk#4129]
### The Question

Why can't we use ec2.Instance in a more consistent way for IConnectable and IGrantable. For example:

```
# This works fine
queue.grantConsumeMessages(instance.role);

# This does not
queue.grantConsumeMessages(instance);

# However for connections both examples work fine
    databaseInstance.connections.allowFrom(
      instance,
      ec2.Port.tcp(cdk.Token.asNumber(databaseInstance.dbInstanceEndpointPort))
    );

    databaseInstance.connections.allowFrom(
      instance.connections,
      ec2.Port.tcp(cdk.Token.asNumber(databaseInstance.dbInstanceEndpointPort))
    );
```

### Environment

  - **CDK CLI Version:** 1.8.0
  - **Module Version:** 1.8.0
  - **OS:** macOS Sierra
  - **Language:** TypeScript

**Comment by rix0rrr** [comment]
Because we didn't implement `IGrantable` for `ec2.Instance`, I presume. An oversight on our part, should be rectifiable easily enough if you were so inclined.
