### ISSUE TITLE
Support for Dynamic StepFunction Dynamic Batching with Map and Iterator

### ISSUE THREAD

**Issue by yyolk** [aws/aws-cdk#4137]
In regards to this blog post: https://aws.amazon.com/blogs/aws/new-step-functions-support-for-dynamic-parallelism/ - AWS StepFunctions now support Dynamic Parallelism (released publicly today AFAICT). Here is the relevant section in the state-languages spec: https://states-language.net/spec.html#map-state

Like [`Task`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-stepfunctions.Task.html), and [`Parallel`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-stepfunctions.Parallel.html), I believe this would be a new [`Construct`](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-stepfunctions-readme.html), with an [`IChainable`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-stepfunctions.IChainable.html) interface for `Map` and `Iterator`

### Use Case

I would like to use this in an in-development project that's already taking advantage of aws-cdk to create a workflow with stepfunctions. I'm currently iterating on payloads that can be executed in parallel, dynamically. I've steered away from trying to manage the state around a StateMachineFragment, but could go down that path until aws-cdk includes the aformentioned constructs.

### Proposed Solution

Implement `Map` and `Iterator` constructs. (More is likely needed).

### Other

supporting links:
- https://aws.amazon.com/blogs/aws/new-step-functions-support-for-dynamic-parallelism/ - AWS blog post announcing support
- https://states-language.net/spec.html#map-state - State Language spec : map-state

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by SomayaB** [comment]
Duplicate created  #4154. 
@rhboyd Work in progress PR #4153

**Comment by yyolk** [comment]
now refs #4145

**Comment by yyolk** [comment]
i believe this can be closed with #4145 getting merged

**Comment by apalumbo** [comment]
#4145 Should not work as there is a problem in the validation, I have produced the issue with a unit test that performs a synth

I have a fix, PR will be created in an hour
