### ISSUE TITLE
CustomResource Hanging on cdk deploy!

### ISSUE THREAD

**Issue by ColWillis** [aws/aws-cdk#4147]
Hi, I have a Java CDK Project and I am attempting a CustomResource Lambda to purge S3 Bucket pre CloudFormation Stack Creation and pre CloudFormation Stack Deletion.

Unfortunately the cdk-deploy does not work, or maybe it is a CloudFormation issue...Or maybe my code!

The Issue I am seeing is it is Hanging on 'CREATE_IN_PROGRESS' for the CustomResource.

e.g It is 22:37 now, and the Action occured:
- 4/6 | 22:13:56 | CREATE_IN_PROGRESS   | Custom::MyCustomResourceLambdaDeleter | CustomResourceApp/customresource-id/Default (customresourceid)
- 4/6 Currently in progress: spike-customresource, customresourceid

I have attached Screenshots and also the reduced Source Code, and the issue can be reproduced.

To recover from this Issue, I had to run multiple cdk destroy (which caused Errors), manually delete the Stack in CloudFormation and manually delete the Lambda. (Repeat these steps if required)

### Reproduction Steps
1. Grab attached src
2. Set your AWS Account ID in the .properties File
3. mvn clean install
4. cdk -o ./target/cdk.out/ --app "mvn exec:java -Dexec.args=\"mystack.properties\"" deploy \"*\" --require-approval never

### Error Log
1. No Errors! It Hangs...Seemingly forever

### Environment

  - **CLI Version      :*1.8.0 (build 5244f97)*
  - **Framework Version:*1.8.0.DEVPREVIEW*
  - **OS               :*Win 10*
  - **Language         :*Java*

### Other

Apologies in advance for the poor code, this was just a Spike!

--- 

This is :bug: Bug Report
![1_Hanging](https://user-images.githubusercontent.com/15360237/65188110-8934c600-da65-11e9-926b-7d78d45a5989.jpg)
![2_Cfn1](https://user-images.githubusercontent.com/15360237/65188112-89cd5c80-da65-11e9-8081-48ab8c4ff1e3.jpg)
![3_Cfn2](https://user-images.githubusercontent.com/15360237/65188113-89cd5c80-da65-11e9-9327-9762fc07a051.jpg)
[CfnTemplate-FromConsole.txt](https://github.com/aws/aws-cdk/files/3628470/CfnTemplate-FromConsole.txt)
[spike-customresource-standalone.zip](https://github.com/aws/aws-cdk/files/3628471/spike-customresource-standalone.zip)

**Comment by RomainMuller** [comment]
Hey,

Could it be that the lambda function that backs your custom resource is failing? CloudFormation will happily wait for at least an hour per attempt (and if I remember correctly, it will make 3+ attempts) for the Lambda function to POST it's outcome to the result endpoint CloudFormation provided. The behavior you describe is consistent with a Lambda function that does _not_ provide a result back to CloudFormation (or maybe provides an invalid result document).

You probably should have a look at the lambda function's logs in CloudWatch logs to check on the function's execution status.

**Comment by ColWillis** [comment]
Hi @RomainMuller ,

I just copied the Lambda from the [cdk-java-lambda github ](https://github.com/aws-samples/aws-cdk-examples/blob/master/java/lambda-cron/src/main/java/software/amazon/awscdk/examples/LambdaCronStack.java) example.

I will re-write to make it work as you suggest and let you know, thanks

**Comment by ColWillis** [comment]
@RomainMuller , as you stated, I believe this is related to CloudFormation and the Lambda Implementation. I have tried to use the CDK Custom Resource with a 'standalone/jar' Lambda but I am still struggling.

`Custom::MyCustomResourceLambda / "errorMessage": 
..."Class does not implement an appropriate handler interface`

A little off-topic now, but I am unable to find examples of an Java Lambda CustomResource with the AWS SDK v2 - Do you have any resources that can help me here?


Big thanks by the way,

Col

**Comment by abelmokadem** [comment]
@ColWillis 2 tips I can offer you:
1. Create the lambda function first without creating the custom resource so that you can test your function in the console.
2. Use a library that prevents you from waiting for an hour. I use nodejs for my lambdas so I'm using https://www.npmjs.com/package/safe-cfn-custom-resource as a wrapper for my lambdas.

**Comment by ColWillis** [comment]
Yes I think this issue was related to my lambda, 100% not cdk either as I can re-create without cdk.

I will Close the issue as I do not have the time to properly address this, sorry
