### ISSUE TITLE
.NET CDK 1.8 ClusterEndpoint does not return port number

### ISSUE THREAD

**Issue by vgribok** [aws/aws-cdk#4149]
Like with #2711, .NET CDK 1.8 `DatabaseCluster.ClusterEndpoint.Port` is of type `double`, precluding getting endpoint port back. 
The workaround described in #2711 can be used to mitigate the issue.

### Reproduction Steps
Use .NET CDK 1.8 to create RDS Aurora cluster.

https://github.com/vgribok/modernization-unicorn-store/blob/073bc28f19108f86e53f7138e5544dee9f36492f/infra-as-code/src/Reusable/DatabaseConstructFactory.cs#L84

### Environment

  - **CLI Version      :1.8**
  - **Framework Version: .NET Core 2.1**
  - **OS               :WIndows 10**
  - **Language         :.NET C#**

### Other

#2711

--- 

This is :bug: Bug Report

**Comment by RomainMuller** [comment]
In principle, the CDK framework is able to encode deploy-time values in special doubles, so you could pass them around. There is however a possibility that the token somehow gets corrupted on it's way between .NET and Javascript.

Could you provide the log (in a gist, for example) produced by running your CDK application while have `JSII_DEBUG=1` set in your environment?

**Comment by vgribok** [comment]
I neglected to mention that when I tried to use double, I was getting non-integer negative value (-1.8881545897087719E+289), not resembling typical MySQL or Postgres port number.

Here's the evaluation of the rds cluster construct:
![image](https://user-images.githubusercontent.com/757185/65343307-8632f600-db89-11e9-829d-51d4f9f26870.png)

**Comment by tomred-net** [comment]
This issue also exists in the Java up to 1.14.0 so it may not be a corruption on it's way between .NET and Javascript unless that issue exists within the Java to Javascript issue also.

**Comment by skinny85** [comment]
Hello @vgribok ,

thanks for opening the issue, and sorry for the late response.

Can you confirm whether this issue still happens in the latest CDK version (`1.38.0`)?

Thanks,
Adam

**Comment by vgribok** [comment]
I will retest in about a week.

**Comment by vgribok** [comment]
Re-tested with TypeScript CDK 1.38. The problem is still there.

**Comment by RomainMuller** [comment]
What happens if you try to use the port number as the value of a `CfnOutput` (what does the corresponding entry look like in the `Output` section of `cdk synth` for this stack)?

**Comment by marioizquierdo** [comment]
This has happened to me with TypeScript CDK `1.45.0`. The port was passed into an ECS environment variable:
```typescript
environment: {
    DB_PORT: `${props.rdsICluster.clusterReadEndpoint.port}`,
},
```
And the value in the ECS Task Container looks like this:
```
DB_PORT: "-1.8881545897089361e+289"
```

**Comment by marioizquierdo** [comment]
In case anyone else ends up in this question, the mystery number comes form the numeric Token representation: https://docs.aws.amazon.com/cdk/latest/guide/tokens.html

To solve this in my case, I used the `cdk.Token` class to convert the numeric Token into a string Token:
```typescript
environment: {
    DB_PORT: cdk.Token.asString(props.rdsICluster.clusterReadEndpoint.port),
},
```
This synthesizes as `"Fn::ImportValue": "FoobarInfra:ExportsOutputFnGetAttDatabaseB269D8BBEndpointPort3ACB3F51"`, which ends with the correct value in the ECS Task Container.

**Comment by vgribok** [comment]
It's a nice workaround, @marioizquierdo, thank you, but it also shows the problem is still there and the issue needs trip be reopened @RomainMuller.
