### ISSUE TITLE
.NET CDK 1.8 Aurora Postgres cluster endpoint gets MySQL port 3306 instead of 5432

### ISSUE THREAD

**Issue by vgribok** [aws/aws-cdk#4150]
Using .NET CDK 1.8 to create Aurora Postgres cluster, observing the cluster endpoint getting port 3306, typically used by MySQL, instead of customary Postgres port 5432, while non-cluster, instance Postgres RDS gets the expected 5432 port.

### Reproduction Steps
Use .NET CDK 1.8 to create Aurora Postgres cluster. Observe cluster port being 3306.

### Environment

  - **CLI Version      :1.8**
  - **Framework Version:.NET Core 2.1**
  - **OS               :Windows 10**
  - **Language         :.NET C#**

### Other

--- 

This is :bug: Bug Report

**Comment by flygerian** [comment]
I also encountered this issue using CDK on typescript

**Comment by NGL321** [comment]
@vgribok, thank you for reporting!
It might be related to #929. Someone should look into this soon and will update this issue when there is any progress.

**Comment by vgribok** [comment]
IMO, that's unlikely. If feels more like a "copy & paste inheritance" kind of problem. I'd look for the code where default port is set, and whether the code setting Postgres Aurora cluster (regular, non-serverless) port was copied from MySQL w/o changing port constant value.

**Comment by Broctune** [comment]
I am encountering this issue as well and have lost of lot of time trying to resolve. Setting the port to 5432 in CDK code (using C#) throws an error on deploy. If I set the port to 3306 I am not able to connect to the database. Using pgadmin4 in the same VPC I receive the error, “received invalid response to ssl negotiation: j” when trying to connect. Setting the connection to other ports in pgadmin4 doesn’t help. I’m using CDK for dotnet v1.22. I am able to get things working when using setting up the Aurora Postgres Serverless DB using the web console.
