### ISSUE TITLE
[aws-eks] Enable Control Plane logs in EKS cluster

### ISSUE THREAD

**Issue by stefanolczak** [aws/aws-cdk#4159]
### Use Case

Enabling Control Plane logging in EKS cluster is only possible by calling EKS API after cluster is created. Doing it in CDK requires to create Custom Resource with code that calls the API. It would be nice to have it as an argument for creating EKS cluster from CDK.

### Proposed Solution

Since EKS is created from python lambda when kubectlEnabled flag is enabled there is a simple way to create the EKS cluster with logging enabled. Currently the lambda code uses boto3 method eks.create_cluster() where we can pass arguments to enable logging on created cluster. (https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/eks.html#EKS.Client.create_cluster).
The lambda uses config as an argument for this method :

https://github.com/aws/aws-cdk/blob/c3b3c935b2086288dd79f559a49c3b5304a8e40f/packages/%40aws-cdk/aws-eks/lib/cluster-resource/index.py#L69

The config is passed as a properties of custom resource and is created here: 

https://github.com/aws/aws-cdk/blob/c3b3c935b2086288dd79f559a49c3b5304a8e40f/packages/%40aws-cdk/aws-eks/lib/cluster.ts#L364-L379

So I suggest to expose a way to include logging properties in the config so it should be passed to eks.create_cluster() method without any more changes. That should result in enabling logging on newly created EKS cluster.

---

This is a :rocket: Feature Request

**Comment by SomayaB** [comment]
Hi @stefanolczak, thanks for submitting a feature request! We will update this issue when there is any progress.

**Comment by yjw113080** [comment]
Any updates on this? Waiting for this feature as well.

**Comment by eladb** [comment]
This is not highly prioritized at the moment, but more than happy to take contributions.

**Comment by iliapolo** [comment]
Note that there is an abandoned PR for this: https://github.com/aws/aws-cdk/pull/8497

Consider resurrecting it once we pick this up again.

**Comment by rameshmimit** [comment]
Any update on this feature?

**Comment by iliapolo** [comment]
@rameshmimit We are discussing this issue internally, we'll update here soon.

**Comment by micheal-hill** [comment]
In the meantime, what workarounds are available? It seems to me that click-ops or AWS cli are the alternatives, but neither is amicable to automation - is that correct? CLI will error if there's no change required.

**Comment by iliapolo** [comment]
Since cluster logging can be updated post cluster creation, you can create a custom resource that updates that config. 
The [AWS Custom Resource](https://docs.aws.amazon.com/cdk/api/latest/docs/custom-resources-readme.html#custom-resources-for-aws-apis) should be a good fit for this.

**Comment by daisuke-yoshimoto** [comment]
Any update on this?

**Comment by jtomaszewski** [comment]
Does anybody has some code to share of that custom resource that would enable the logs? Trying to build it now in cdk but don't know where to start.

**Comment by jtomaszewski** [comment]
If anybody wants the workaround, here's code we wrote in our CDK to enable the logging for the cluster once it's created :)

```ts
    new AwsCustomResource(this, "ClusterLogsEnabler", {
      policy: AwsCustomResourcePolicy.fromSdkCalls({
        resources: [
          `${this.cluster.clusterArn}/update-config`,
        ],
      }),
      onCreate: {
        physicalResourceId: { id: `${this.cluster.clusterArn}/LogsEnabler` },
        service: "EKS",
        action: "updateClusterConfig",
        region: this.region,
        parameters: {
          name: this.cluster.clusterName,
          logging: {
            clusterLogging: [
              {
                enabled: true,
                types: [
                  "api",
                  "audit",
                  "authenticator",
                  "controllerManager",
                  "scheduler",
                ],
              },
            ],
          },
        },
      },
    });
```

**Comment by jasonumiker** [comment]
So I did the above with a AwsCustomResource and it worked great until we wanted to create a FargateProfile. Even adding an explicit dependency from the FargateProfile on the logging custom resource didn't help - it fails with a "you can't update the logs while we are creating a Fargate Profile" error. Having fought with it all day I am now having to look at going lower level to a Lambda-backed custom resource to get access to a is_complete_handler or something.

**Comment by micheal-hill** [comment]
@jasonumiker in our case we're using Fargate, but the logging config is set _after_ Fargate has been setup. We're also using `eks.FargateCluster` in case that's relevant.

**Comment by jasonumiker** [comment]
Thanks - yeah I eventually tried flipping the dependency and that seems to work 🤞

**Comment by SpringMT** [comment]
CloudFormation (NOT CDK) supports EKS control plane logging settings.
https://aws.amazon.com/about-aws/whats-new/2021/11/amazon-eks-cluster-configuration-aws-cloudformation/
How About CDK?

**Comment by bweigel** [comment]
> CloudFormation (NOT CDK) supports EKS control plane logging settings.

I thought this would be easy...just use an escape hatch, like this:

```ts
    const cfnCluster = cluster.node.defaultChild as eks.CfnCluster;
    cfnCluster.logging = {
      clusterLogging: {
        enabledTypes: [{ type: 'api' }, { type: 'audit' }, { type: 'authenticator' }, { type: 'controllerManager' }, { type: 'scheduler' }]
      }
    }
```

But alas, it seems like the CDK does not use the low-level `CfnCluster` (aka `AWS::EKS::Cluster`)  to provision a cluster, but depends on a custom resource. 

https://github.com/aws/aws-cdk/blob/b8a4a9a9d28c65aff419beb5d7ac14fa4a0a473e/packages/%40aws-cdk/aws-eks/lib/cluster-resource.ts#L73-L102

Long story short the quick "escape hatch" hack does not work :sob:
