### ISSUE TITLE
Sharing load balancer listener between stacks

### ISSUE THREAD

**Issue by markusl** [aws/aws-cdk#4160]
## :question: General Issue

Since hitting CloudFormation 200 resource limit, I have been trying to refactor our services to multiple stacks sharing ALB between the stacks.

However, it seems importing ALB or ALB listener between stacks and adding more services to it is challenging.

### Stack1 - Create stack and ALB with listener

```typescript
  const stack = new cdk.Stack(app, `Stack`, props);
  const vpc = ec2.Vpc.fromVpcAttributes(stack, `Vpc`, networkConfiguration.vpcProps);

  const loadBalancerCertificate = cm.Certificate.fromCertificateArn(stack, `Certificate`, networkConfiguration.certificateArn);

  const loadBalancer = new elbv2.ApplicationLoadBalancer(stack, `LoadBalancer`, {
    vpc,
  });

  const listener = loadBalancer
    .addListener(`HttpsListener`, {
      port: 443,
      certificateArns: [loadBalancerCertificate.certificateArn],
    });

...

    fargateServices.map((fg, i) =>
      listener
        .addTargets(`${services[i].name}`, {
          protocol: elbv2.ApplicationProtocol.HTTP,
          targets: [fg],
        }
      ));


```

### Stack 2 - Trying to import existing listener to add new services

```typescript
  const stack2 = new cdk.Stack(app, `stack2`, props);
  const existingListener = elbv2.ApplicationListener.fromApplicationListenerAttributes(stackInternalServices,
    `Listener`, {
      listenerArn: listener.listenerArn,
      securityGroupId: loadBalancer.loadBalancerSecurityGroups[0]
  });


```

### Result

The result of trying to do that is following:  `Error: Can only call addTargets() when using a constructed ApplicationListener; construct a new TargetGroup and use addTargetGroup.`

Do you have any example or recommendations about how to do this? In general it does not feel right to work around CF limitations in this way..

### Environment

  - **CDK CLI Version:** 1.8.0 (build 5244f97)
  - **OS:** Macbook
  - **Language:** TypeScript

**Comment by rix0rrr** [comment]
What if you don't use `fromApplicationListenerAttributes` but just use the listener directly in stack 2?

**Comment by markusl** [comment]
@rix0rrr thanks for the tip. Didn't even think it could be that easy. Here's the problem with that one:

```
Error: 'ApplicationName-Stack2' depends on 'ApplicationName-Stack1'
(ApplicationName-Stack2/ApplicationName-Stack2-ContainerName/Service ->
    ApplicationName-Stack1/ApplicationName-Stack1LoadBalancer/ApplicationName-Stack1HttpsListener/ApplicationName-Stack2-ContainerNameGroup/Resource.Ref).
    
Adding this dependency (ApplicationName-Stack1/ApplicationName-Stack1LoadBalancer/SecurityGroup/to SecurityGroup997F5017:8080 -> ApplicationName-Stack2/ApplicationName-Stack2-ContainerName/SecurityGroup/Resource.GroupId) would create a cyclic reference.```

**Comment by rix0rrr** [comment]
I think you got hit by the issue that was fixed in https://github.com/aws/aws-cdk/pull/4111.

The fix for that will be rolling out later today in the new release. Sorry to keep you waiting.

**Comment by markusl** [comment]
I can now confirm that this is fixed. Thanks for the help :)

**Comment by PrettySolution** [comment]
> @rix0rrr thanks for the tip. Didn't even think it could be that easy. Here's the problem with that one:
> 
> ```
> Error: 'ApplicationName-Stack2' depends on 'ApplicationName-Stack1'
> (ApplicationName-Stack2/ApplicationName-Stack2-ContainerName/Service ->
>     ApplicationName-Stack1/ApplicationName-Stack1LoadBalancer/ApplicationName-Stack1HttpsListener/ApplicationName-Stack2-ContainerNameGroup/Resource.Ref).
>     
> Adding this dependency (ApplicationName-Stack1/ApplicationName-Stack1LoadBalancer/SecurityGroup/to SecurityGroup997F5017:8080 -> ApplicationName-Stack2/ApplicationName-Stack2-ContainerName/SecurityGroup/Resource.GroupId) would create a cyclic reference.```

Does it work in CDK v2? Can you please share and example? Can't get it working today

**Comment by rbrayner** [comment]
I'm facing the same issue in v2 as well. Couldn't find a solution yet.

**Comment by mixtah** [comment]
I believe I'm also facing the same issue in v2 using the same method originally suggested by @rix0rrr

**Comment by arijeetsengupta** [comment]
Cyclic dependency issue still exists in CDK v2

**Comment by jacido** [comment]
Greetings, is there a fix for this yet?
