### ISSUE TITLE
Feature Request: Fargate construct to setup Fargate cluster from docker image

### ISSUE THREAD

**Issue by aletheia** [aws/aws-cdk#4166]
Would like having construct support of Fargate, hiding cluster, VPC and docker image complexities. A construct like this should be able to instantiate a Fargate cluster with only docker image path and few other parameters and returning endpoint DNS back to the user.

### Use Case
It would be a great use case towards serverless computing because it could ease out the need to setup and configure VPCs or clusters

### Proposed Solution
Implement a custom construct receiving parameters such as ```cpu, memoryLimitMiB, desiredCount, maxAzs``or running on defaults.
Other params such as **type** should be required to decide wheter an EC2 or ECS cluster should be defined, but defaulting to LoadBalanced ECS.

**Image** param should be passed as existing docker image or DockerHub url string.
Otherwise, **imagePath** param should be used as pointer to local docker image folder. In this case, construct should build docker image, save it into Container Service and setup cluster.

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
`cluster` and `vpc` are already optional in `ApplicationLoadBalancedFargateService`.

https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs-patterns.ApplicationLoadBalancedEc2Service.html

If you want more or different configuration, I'm not sure the CDK standard library is the right place for such a construct. We'd rather be the building blocks for a cloud component ecosystem than the sole provider of cloud components.

You are free and welcome to start a GitHub project with the constructs you would prefer to exist, of course.
