### ISSUE TITLE
CodePipeline Source Actions for S3

### ISSUE THREAD

**Issue by rhboyd** [aws/aws-cdk#4167]
When I add 
```
new codepipeline_actions.S3SourceAction({
  actionName: 'S3_Source',
  bucket: props.stagingBucket,
  bucketKey: props.fileModelName,
  output: s3SourceOutput,
})
```

CDK should also add s3:read permissions to the pipeline's role

### Use Case
When users are using S3SourceActions in a pipeline, CDK knows enough information about the interaction to be able to grant IAM permissions to the Pipeline's Role so users don't have to. Users should still be able to add more permissions if they hate their free time and want to do it manually.

### Proposed Solution
could probably add some logic to the `addStage()` method to also create some IAM permissions.

### Other

* [X] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by skinny85** [comment]
It does...? https://github.com/aws/aws-cdk/blob/b8b4c4d82334480958975c55a105bc47d9fcc6d5/packages/@aws-cdk/aws-codepipeline-actions/lib/s3/source-action.ts#L96-L96

**Comment by rhboyd** [comment]
Strange. let me try to reproduce the issue I saw.  I'll close this if I can't reproduce it.

**Comment by rhboyd** [comment]
I am not smart. there was a typo in my cdk app.
