### ISSUE TITLE
Lambda being updated before policy cause permission error

### ISSUE THREAD

**Issue by amwill04** [aws/aws-cdk#4176]
Have a `Stack` that provissions a `lambda` function. I have since added `tracing: Tracing.Active` to the `Function` decleration and have tried to deploy.

`Cloudformation` is now failing with the following:

```
The provided execution role does not have permissions to call PutTraceSegments on XRAY.
```

The `cloudformation` template is fine and has the neccessary permisions associated with the `role/policy`.

This issue seems that the `lambda` function is being updated before the relevant `policy` has been updated.

I am unsure if this is a `aws-cdk` issue or a more general `Cloudformation` issue.

Thanks.

**Comment by nija-at** [comment]
Thanks for reporting an issue with us. However, I'm unable to reproduce this bug you describe.

I'm using the following CDK app with CDK version `1.9.0` - 

```ts
#!/usr/bin/env node
import cdk = require('@aws-cdk/core');
import lambda = require('@aws-cdk/aws-lambda');

class MyStack extends cdk.Stack {

    constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
      super(scope, id, props);

      new lambda.Function(this, 'firstLambda', {
        functionName: 'FirstLambda',
        code: lambda.Code.asset('/Users/nija/workplace/cdk/hello-cdk/resources'),
        handler: 'index.handler',
        runtime: lambda.Runtime.NODEJS_10_X,
        tracing: lambda.Tracing.ACTIVE
      });
    }
}
  
const app = new cdk.App();
new MyStack(app, 'MyStack');
app.synth();
```

I started off by running `cdk deploy` on this app without the line `tracing: lambda.Tracing.ACTIVE` and this succeeded.
Following this, I added the line around tracing and re-deployed and that went successfully as well.

Can you check again that you've modeled your app correctly, and that you're using a recent version of the CDK?

If you still have this issue, we would appreciate if you can provide a more reliable way to reproduce this.

**Comment by nija-at** [comment]
Closing now since this was not re-producible. Feel free to reopen with more details that can help us repro this issue if you think this problem persists.
