### ISSUE TITLE
certificate-manager: Unable to delete DnsValidatedCertificates that are still attached to resources

### ISSUE THREAD

**Issue by jonathanmorley** [aws/aws-cdk#4179]
If you have a DnsValidatedCertificate, and attach it to an ALB listener, you cannot successfully delete the stack.

This appears to be because the certificate resource deletion is triggered immediately after the listener deletion. Based on testing, it can take around 10s for ACM to acknowledge that the certificate is no longer in use. This causes the certificate deletion to fail, which propagates up to causing the stack deletion to fail

### Reproduction Steps

```typescript
import { HostedZone, RecordTarget, ARecord } from "@aws-cdk/aws-route53";
import { ApplicationProtocol, ApplicationLoadBalancer } from '@aws-cdk/aws-elasticloadbalancingv2';
import { DnsValidatedCertificate } from '@aws-cdk/aws-certificatemanager';
import { LoadBalancerTarget } from '@aws-cdk/aws-route53-targets';
import { Vpc } from '@aws-cdk/aws-ec2';
import { Stack, Construct, StackProps } from '@aws-cdk/core';

export class TestStack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);

    const domainName = 'example.com';

    const zone = HostedZone.fromLookup(this, 'Zone', {
      domainName
    });

    const alb = new ApplicationLoadBalancer(this, "Alb", {
      vpc: new Vpc(this, 'VPC'),
      internetFacing: true
    });

    const name = 'alb-test';

    new ARecord(this, "DNSRecord", {
      target: RecordTarget.fromAlias(new LoadBalancerTarget(alb)),
      recordName: name,
      zone
    });

    const lbCert = new DnsValidatedCertificate(this, "Certificate", {
      domainName: `${name}.${domainName}`,
      hostedZone: zone
    });

    alb
      .addListener("Listener", {
        protocol: ApplicationProtocol.HTTPS,
        port: 443,
        certificateArns: [lbCert.certificateArn]
      })
      .addFixedResponse("FixedResponseRule", {
        statusCode: '200',
        messageBody: 'None'
      });
  }
}
```

### Error Log

> Failed to delete resource. Certificate arn:aws:acm:us-east-1:123456789012:certificate/dfcc18cb-d587-488d-9e63-bad442e7b96e in account 123456789012 is in use.

### Environment

  - **CLI Version      :** v1.9.0
  - **Framework Version:** v1.9.0
  - **OS               :** MacOS
  - **Language         :** typescript

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
> This appears to be because the certificate resource deletion is triggered immediately after the listener deletion.

This seems odd to me. Since there's a dependency between the listener and the certificate, the certificate should be deleted before the listener is deleted. Can you confirm with a CloudFormation log snippet that the behavior you're seeing is as you've described?

---

What seems likely to me is that the deletion is started before the listener is deleted, but it doesn't wait for the deletion to finish and so the listener is deleted too soon.

**Comment by jonathanmorley** [comment]
There is a dependency between the listener and certificate, which does cause the certificate should be deleted AFTER the listener is deleted.

However, the certificate deletion happens **immediately** after the listener deletion, which is not enough time for ACM to recognise that the certificate is in use.

I can get a CloudFormation log snippet together to show that the deletions happen in the expected order, but I don't know how much that will help, because I _think_ we are on the same page about the order of deletions.

**Comment by rix0rrr** [comment]
Oh you are right, I was confused. I'm sorry.
