### ISSUE TITLE
Redesign `IConnections` and `IDefaultConnections` to play nicely with strict type models

### ISSUE THREAD

**Issue by mpiroc** [aws/aws-cdk#418]
Currently, `IDefaultConnectable` extends `IConnectable`, but changes the return type of `connections` from `IConnections` to the more dervied type `DefaultConnections`. This is not valid in `.NET`, which requires that overrides match the original return type exactly.

If we simply change the return type of `IDefaultConnectable.connections` back to `IConnections`, this breaks existing code in several places. For example, `database.connections` becomes `(database.connections as ec2.DefaultConnections)`.

We should come up with a better design that places nicely with `.NET` and does not require casting.

**Comment by rix0rrr** [comment]
Here's another potential solution for C#:

https://stackoverflow.com/a/5709191

But that requires inventing 2 function names, one for the polymorhpic function and a more strictly typed non-polymorphic one.
