### ISSUE TITLE
ec2.Instance should implement elbv2.IApplicationLoadBalancerTarget, elbv2.INetworkLoadBalancerTarget

### ISSUE THREAD

**Issue by swapnil-jak** [aws/aws-cdk#4180]
Similar to an AutoScaling Group, I should be able to add 1/more EC2 Instance/s as the target of an ALB/NLB target group. 

Only classes implementing IApplicationLoadBalancerTarget can be added as a target of ALB Target Groups.

### Use Case

This is a very common use-case for applications which support clustering but don't support scale-out/scale-in. Especially software products whose license is bound to the system MAC.

### Proposed Solution

ec2.Instance should implement elbv2.IApplicationLoadBalancerTarget, elbv2.INetworkLoadBalancerTarget

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
Recently implemented by @hoegertn in the way of an `InstanceTarget`. Unfortunately cyclic dependencies make it impossible for `Instance` to implement the required interfaces.
