### ISSUE TITLE
Escape Hatch Raw Overrides - AWS Glue Table - Does not work

### ISSUE THREAD

**Issue by dangarfield** [aws/aws-cdk#4188]
Attempting to add a property override through escape hatch to set the `SerDeInfo` parameters on a glue table through cdk. The table construct does not allow access to these parameters. I create the table through the standard `glue.Table(...)` construct and attempt to add property override through `tableVar.node.defaultChild.addPropertyOverride(...)` however, the defaultChild is undefined and throws an error. As such, I cannot use the override and instead have to create the whole table through `CfnTable`.

That being said, I apologise if I am just doing something incorrect. The exact scenario works 100% correctly for some other resources, eg `s3.Bucket`

### Reproduction Steps

```
const exampleTable = new glue.Table(this, 'insights-table-photo-match-sales', {
      columns: [
        {name: 'id', type: glue.Schema.STRING},
        {name: 'another', type: glue.Schema.STRING},
        {name: 'count', type: glue.Schema.SMALL_INT},
        {name: 'name', type: glue.Schema.STRING},
        {name: 'date', type: glue.Schema.TIMESTAMP}
      ],
      dataFormat: glue.DataFormat.Json,
      database: insightsDB,
      tableName: 'photo-match-sales'
    })
photoMatchSalesTable.node.defaultChild.addPropertyOverride('TableInput.StorageDescriptor.SerdeInfo.parameters', {'path': 'id,ship,count,name,date'})
```

### Error Log

```
   photoMatchSalesTable.node.defaultChild.addPropertyOverride('TableInput.StorageDescriptor.SerdeInfo.parameters', {'path': 'id,ship,count,name,date'})
                                           ^

TypeError: Cannot read property 'addPropertyOverride' of undefined
    at new DigitechInsightsStack (/Users/DanGarfield/code/digitech-insights/lib/digitech-insights-stack.js:47:44)
    at Object.<anonymous> (/Users/DanGarfield/code/digitech-insights/bin/digitech-insights.js:7:1)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:238:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3)
```

### Environment

  - **CLI Version      : 1.8.0**
  - **Framework Version: 1.8.0**
  - **OS               : OSX**
  - **Language         : JS & TS, both**

### Other

--- 

This is :bug: Bug Report

**Comment by nmussy** [comment]
I'm pretty sure this can be easily fixed by setting `CfnTable` as the default child of the Table construct:

https://github.com/aws/aws-cdk/blob/4a0272db5eb9aae5f440bb0813fdbad6514b60c3/packages/%40aws-cdk/aws-glue/lib/table.ts#L251

I'll make a PR

**Comment by nmussy** [comment]
@dangarfield Once this is merged, you should be able to do the following:

```ts
const cfnTable = table.node.defaultChild as glue.CfnTable;
const tableInput = cfnTable.tableInput as glue.CfnTable.TableInputProperty;
const storageDescriptor = tableInput.storageDescriptor as glue.CfnTable.StorageDescriptorProperty;
const serdeInfo = storageDescriptor.serdeInfo as glue.CfnTable.SerdeInfoProperty;

// @ts-ignore - readonly
serdeInfo.parameters = {
  path: 'id,ship,count,name,date'
};
```
