### ISSUE TITLE
aws-cdk-codepipeline: can we tighten InvokeLambdaAction permissions?

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#42]
The function invoked by the pipeline needs `codepipeline:PutJobXxxResult` permissions, and based on [the docs][1] we are using "*" as the resource instead of the pipeline's ARN.

Try to see if there is a way to specify an explicit pipeline instead.

See context in #29

[1]: https://docs.aws.amazon.com/codepipeline/latest/userguide/actions-invoke-lambda-function.html

**Comment by skinny85** [comment]
Confirmed with the CodePipeline team that indeed `"*"` is required there - the CodePipeline ARN is not enough. Resolving.
