### ISSUE TITLE
Publish a dev/nightly package

### ISSUE THREAD

**Issue by parisholley** [aws/aws-cdk#4236]
Considering how much movement is going on in the repo, it would be great to have nightly and/or dev tag version pushed to NPM on green builds. Right now, only a checkout on my local machine has fixes I need to push to production :)

**Comment by AntonioAngelino** [comment]
Since there're a lot of fixes/feat/improv merged every day, having a nightly build of aws-cdk would be great.
I imagine there are way more changes merged today than in 2019.
