### ISSUE TITLE
Add Security Group lookup by name

### ISSUE THREAD

**Issue by digitalsanctum** [aws/aws-cdk#4241]
Similar to `SecurityGroup.fromSecurityGroupId()`, please add a `SecurityGroup.fromSecurityGroupName`. 

### Use Case

There are cases where existing SecurityGroups need to be referenced and have well-known names but not the ids. It would be nice to be able to look up SGs by name. Otherwise, a custom resource and/or SDK is needed to do the lookup.

### Proposed Solution

Add a `SecurityGroup.fromSecurityGroupName` method.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
We will not be able to make a security group from a name. We might be able to look one up, given CLI support.

**Comment by digitalsanctum** [comment]
I just want to be able to look up an existing SG by name.

**Comment by tmo-trustpilot** [comment]
I have the same need. In my case I'm trying to create an AWS Batch Compute Environment using existing subnets and security groups, where I have known stable names but not ids.

I'm able to find the VPC by name, and from there get to the private security groups:
```
const vpc = ec2.Vpc.fromLookup(this, "vpc", {
  vpcName: `${vpcName}`
});

const subnetIds = vpc.privateSubnets.map(sn => sn.subnetId);

const computeResourcesProperties: batch.CfnComputeEnvironment.ComputeResourcesProperty = {
  type: "EC2",
  ...snip...
  subnets: subnetIds,
  securityGroupIds: ???
};
```
There is no way to do a similar lookup for the security group id though.

**Comment by tmo-trustpilot** [comment]
I have the same issue, I am trying to create an AWS Batch compute environment in an with existing subnets and security groups.

I am able to find the private subnets by looking up the VPC by name, but I have no way of finding the ids of the existing security groups.

```
const vpc = ec2.Vpc.fromLookup(this, "vpc", {
  vpcName: `${vpcName}`
});

const subnetIds = vpc.privateSubnets.map(sn => sn.subnetId);

const computeResourcesProperties: batch.CfnComputeEnvironment.ComputeResourcesProperty = {
    type: "EC2",
    ...snip...
    subnets: subnetIds,
    securityGroupIds: ???
};
```

Attempting to use a security group name seems to provision fine until the compute environment tries to add instances to the cluster: `CLIENT_ERROR - Invalid value '<SNIP>' for groupName. You may not reference Amazon VPC security groups by name. Please use the corresponding id for this operation.`

**Comment by kulesha** [comment]
is this feature available yet ? 
it would be super useful to us too .. 
in our case we have one cdk script that deploys 'infrastructure' ( vpc, subnets, security groups etc .. ) 
and another one is creating spot fleets to run applications in  this infrastructure ..
at the moment we have to hard code the security  group id in the application script ..

**Comment by michal-ziarnik** [comment]
It would be useful to us too. We're trying to create Redshift cluster and having an option to do a lookup for existing Security Groups by name would be a grate help.

**Comment by levarne** [comment]
nothing? Need to reference Security group per environment like I did with my existing VPC
```
cont vpc = Vpc.fromLookup(this, 'VPC', {
    vpcName: `dynamo-${environment}-app`,
})
```

Would be nice to do:
```
const groupWebAccess = SecurityGroup.fromLookup(this, 'Security-group-WebAccess', {
     groupName: `dynamo-${environment}-app-webAccess`
})
const groupProxyServer= SecurityGroup.fromLookup(this, 'Security-group-WebAccess', {
     groupName: `dynamo-${environment}-app-proxyServer`
})

new WebpackFunction(this, 'Metric', {
  vpc,
  securityGroups: [groupWebAccess, groupProxyServer]
})
```

But now I have to write each environments ID into a env file or configuration,
the above will allow me to change the security group without needing to redeploy code.

**Comment by calebpalmer** [comment]
I would also like this too.  I'm trying to deploy a Simple AD and some workspaces, I need to update the ingress rules on the worker sg created by the simple ad and the only way to know if (I think) is by the name it creates for it, directoryId_workspaceMembers.

**Comment by felipepulpo** [comment]
+1

**Comment by daminisinha** [comment]
+1, need this feature please

**Comment by suryakiran7** [comment]
+1

**Comment by suhas-hr** [comment]
+1

**Comment by laurabaste** [comment]
+1

**Comment by Prashanna313** [comment]
+1

**Comment by Amchien** [comment]
+1

**Comment by Nicoowr** [comment]
+1

**Comment by ebrahimahmadi** [comment]
+1

**Comment by argenstijn** [comment]
any process?

**Comment by yukihato** [comment]
+1

**Comment by ammonsabrinaPFG** [comment]
+1

**Comment by argenstijn** [comment]
@NetaNir  
What is the status of this request?

**Comment by mmislam101** [comment]
+11

**Comment by james-bw** [comment]
+1

**Comment by njlynch** [comment]
Given the attention this issue has received, I'm correctly labeling it as a p1, which means it should be on our near-term roadmap.

We welcome community contributions! If you are able, we encourage you to [contribute](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md). If you decide to contribute, please start an engineering discussion in this issue to ensure there is a commonly understood design before submitting code. This will minimize the number of review cycles and get your code merged faster. Security group lookup by id was added in #11089, and would be a good inspiration for this work.

**Comment by jumic** [comment]
I would suggest to extend the existing logic from PR #11089 and introduce the additional property `securityGroupName`.
From my point of view, the main topic which should be discussed is the interface in class [`SecurityGroup`](https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-ec2/lib/security-group.ts).

**ec2 SecurityGroup**
Method `fromLookup()` already exists.
https://github.com/aws/aws-cdk/blob/27a0113ac68a05360faa22fa8897609f2f90b764/packages/%40aws-cdk/aws-ec2/lib/security-group.ts#L320

Create a new method `fromLookupAttributes()` which can be used to lookup a SecurityGroup by name or id. (I'm not sure if this is a good name, actually I would prefere `fromLookup()` which is already in use.)
```ts
public static fromLookupAttributes(scope: Construct, id: string, options: SecurityGroupLookupOptions)
```

Move code from `fromLookup()` to this new method and use the new method in `fromLookup()`.

The interface will allow a security group name or id (if both or non of them are specified, it will throw an error).
```ts
export interface SecurityGroupLookupOptions {
  readonly securityGroupName?: string;
  readonly securityGroupId?: string;
}
```

Using this interface it is possible to extend the attributes later (e.g. lookup by tag).

(Alternative solution: implement method `fromLookupName()` with string-parameter `securityGroupName` similar to `fromLookup()` which has a string-parameter, too.)

**SecurityGroupContextQuery**
In [SecurityGroupContextQuery](https://github.com/aws/aws-cdk/blob/27a0113ac68a05360faa22fa8897609f2f90b764/packages/%40aws-cdk/cloud-assembly-schema/lib/cloud-assembly/context-queries.ts#L420) change variable `securityGroupId` to optional and add optional variable `securityGroupName`.

**SecurityGroupContextProviderPlugin**
In [SecurityGroupContextProviderPlugin](https://github.com/aws/aws-cdk/blob/27a0113ac68a05360faa22fa8897609f2f90b764/packages/aws-cdk/lib/context-providers/security-groups.ts#L18-L20) add additional parameter `GroupNames` to `describeSecurityGroups()`. It is possible to query the security group by name using this SDK method. Furthermore, check if both id and name or neither id nor name will be passed and throw an error in this case.

@njlynch I would be happy to have your feedback.

**Comment by Arthus15** [comment]
Any update on this topic?

**Comment by ranma2913** [comment]
> I would suggest to extend the existing logic from PR #11089 and introduce the additional property `securityGroupName`. From my point of view, the main topic which should be discussed is the interface in class [`SecurityGroup`](https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-ec2/lib/security-group.ts).
> 
> **ec2 SecurityGroup** Method `fromLookup()` already exists.
> 
> https://github.com/aws/aws-cdk/blob/27a0113ac68a05360faa22fa8897609f2f90b764/packages/%40aws-cdk/aws-ec2/lib/security-group.ts#L320
> 
> Create a new method `fromLookupAttributes()` which can be used to lookup a SecurityGroup by name or id. (I'm not sure if this is a good name, actually I would prefere `fromLookup()` which is already in use.)
> 
> ```ts
> public static fromLookupAttributes(scope: Construct, id: string, options: SecurityGroupLookupOptions)
> ```
> 
> Move code from `fromLookup()` to this new method and use the new method in `fromLookup()`.
> 
> The interface will allow a security group name or id (if both or non of them are specified, it will throw an error).
> 
> ```ts
> export interface SecurityGroupLookupOptions {
>   readonly securityGroupName?: string;
>   readonly securityGroupId?: string;
> }
> ```
> 
> Using this interface it is possible to extend the attributes later (e.g. lookup by tag).
> 
> (Alternative solution: implement method `fromLookupName()` with string-parameter `securityGroupName` similar to `fromLookup()` which has a string-parameter, too.)
> 
> **SecurityGroupContextQuery** In [SecurityGroupContextQuery](https://github.com/aws/aws-cdk/blob/27a0113ac68a05360faa22fa8897609f2f90b764/packages/%40aws-cdk/cloud-assembly-schema/lib/cloud-assembly/context-queries.ts#L420) change variable `securityGroupId` to optional and add optional variable `securityGroupName`.
> 
> **SecurityGroupContextProviderPlugin** In [SecurityGroupContextProviderPlugin](https://github.com/aws/aws-cdk/blob/27a0113ac68a05360faa22fa8897609f2f90b764/packages/aws-cdk/lib/context-providers/security-groups.ts#L18-L20) add additional parameter `GroupNames` to `describeSecurityGroups()`. It is possible to query the security group by name using this SDK method. Furthermore, check if both id and name or neither id nor name will be passed and throw an error in this case.
> 
> @njlynch I would be happy to have your feedback.

I'll use this right away! any idea when it might go in?
