### ISSUE TITLE
CI: Remove ANSI escape codes from CodeBuild CI Report

### ISSUE THREAD

**Issue by nmussy** [aws/aws-cdk#4243]
### Use Case

Remove ANSI escape codes, e.g. `[7m154[0m`

### Proposed Solution

Add `--no-color` flag. 

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by nmussy** [comment]
Actually, a better solution might be to implement something like [ansi-html](https://github.com/Tjatse/ansi-html), to interpret the escape codes into their proper format.

**Comment by skinny85** [comment]
This was done in #4165.
