### ISSUE TITLE
.NET CDK developer experience improvements

### ISSUE THREAD

**Issue by costleya** [aws/aws-cdk#4245]
We launched CDK GA support for TypeScript and Python on July 11th. Since GA, have been busy making API usability changes to improve the .NET developer experience for CDK. Recently, we rolled out quite a few changes for .NET developers. We would love to hear your reactions. _Add your comments on this pinned issue_. The CDK team will actively watch for your feedback and will follow-up on them as part of ongoing feature improvements and bug fixes priorities. See below a quick run-down for key changes —

* __Usability improvements:__
    * __Optional and variadic parameters support:__ The CDK for .NET now supports optional and variadic (params keyword) parameters in method signatures. Previously, a null value had to be passed to some of the CDK constructs methods parameters.
Example:
    ```csharp
            var bucket = new Bucket(stack, "MyBucket", null);
            // The third parameter is now optional
            var bucket = new Bucket(stack, "MyBucket");
    ```
    * __Naming improvements (syntax):__ In the dev preview version, underscores sometimes polluted the code. With the recent release, we solved this problem with nested classes and you no longer have to deal with class names ending with underscores. Here is an example of how you see the classes without the underscores. (https://docs.aws.amazon.com/cdk/api/latest/dotnet/api/Amazon.CDK.AWS.Glue.CfnJob.JobCommandProperty.html)
    * __Improved view-ability of warning messages in the IDE:__ We have introduced a new NuGet package (Amazon.JSII.Analyzers (https://www.nuget.org/packages/Amazon.JSII.Analyzers/) or the Roslyn Analyzer) to help .NET developers for showing errors in their IDE when developing for the CDK. For example, developers will now see a warning when a required property is not supplied to a CDK construct.
    * __.NET CDK documentation now displayed in the IDE:__ We have updated the .NET generator to get documentation in NDoc format. You can now see documentation displayed in the IDE.
    * __More syntax improvements (Double I prefix for interfaces):__ In some occurrences, interfaces names could start with two capital I letters in prop objects. The second capital I prefix is now removed.

* __Heads up on few other changes__
    * __The CDK .NET now targets  .NET Core 2.1 (netcoreapp2.1).__

* __Bug fixes__
    * __Nested type conversions:__ We are fixing the exceptions such as “Could not infer JSII type for..”. This is due to a bug in the .NET CDK runtime when converting nested arrays or nested maps of objects (https://github.com/aws/jsii/pull/772).

**Comment by McDoit** [comment]
Yeah after the most recent fixes and updates, the dotnet experience is really smooth
Most of my issues raised with the jsii is fixed and using the dotnet cdk for some minor projects already

The main issue blocking me now is https://github.com/aws/aws-cdk/issues/3284 regarding CloudFront

I have also noticed that I sometimes have problems with auto completion in VS2017, don't know if it is just my computer or if it's related to the CDK

**Comment by RomainMuller** [comment]
@McDoit - with respects to auto-completion... We've actually changed how our symbols & documentations packages are built & distributed. The symbols package is now served from NuGet's own symbols server (`https://symbols.nuget.org/download/symbols`). This might improve the situation for you.
