### ISSUE TITLE
elbv2: Investigate NetworkLoadBalancer

### ISSUE THREAD

**Issue by jd-carroll** [aws/aws-cdk#4268]
Quick Update:
---
This is partly user error 🙏 (60%)

One of the core things I missed to begin with is that a `NetworkLoadBalancer` does not support Security Groups.  Therefore they are fundamentally different from `ApplicationLoadBalancer` s.

However, there is still likely room to make the `NetworkLoadBalancer` a little more user friendly, specifically relating to the Security Group assigned to the instance.  

#### Recap: 
We are dealing with a `NetworkLoadBalancer`, therefore all of the security policies are defined at the instance level (not the load balancer level) (subnets aside). To change the ingress policy for the instance we either need access to the `SecurityGroup` of the `AutoScalingGroup` or the `AutoScalingGroup` itself (or add a new `AutoScalingGroup`).  With either of these we are able to make the necessary changes (either edit the existing or add a new `SecurityGroup`) to enable access to the instances.

#### Problem:
The problem is that when you get the `AutoScalingGroup` from the cluster (`cluster.autoscalingGroup`), it returns a type of `IAutoScalingGroup` and not the `AutoScalingGroup` type.  The `IAutoScalingGroup` does not have any reference to the underlying security groups and you are not able to add a new `SecurityGroup`.

All of these facts taken together make it very difficult to work with ECS & NetworkLoadBalancers from CDK.

Original Post:
---
It looks like there are a number of missing features from the `NetworkLoadBalancer`.  Specifically, there are no security groups created by default when using the `NetworkLoadBalancedEc2Service` from the `ecs-patterns` package.

### Reproduction Steps
First deploy the stack:
```javascript
const app = new cdk.App();
const stack = new cdk.Stack(app, 'aws-ecs-network-lb', { 
  tags: { id: 'network-lb' }
});

// Create a cluster
const vpc = new ec2.Vpc(stack, 'Vpc', { maxAzs: 2 });

const cluster = new ecs.Cluster(stack, 'EcsCluster', { vpc });
cluster.addCapacity('DefaultAutoScalingGroup', {
  instanceType: ec2.InstanceType.of(ec2.InstanceClass.T2, ec2.InstanceSize.MICRO)
});

// create a task definition with CloudWatch Logs
const logging = new ecs.AwsLogDriver({ streamPrefix: "task" })

// Create Task Definition
const taskDefinition = new ecs.Ec2TaskDefinition(stack, 'TaskDef');
const container = taskDefinition.addContainer('web', {
  image: ecs.ContainerImage.fromRegistry('nginx:latest'),
  memoryLimitMiB: 256,
  logging
});

container.addPortMappings({
  containerPort: 80,
  hostPort: 80,
  protocol: ecs.Protocol.TCP
});

// Create Service
const service = new ecs.Ec2Service(stack, "Service", {
  cluster,
  taskDefinition
});

// Create ALB
const lb = new elbv2.NetworkLoadBalancer(stack, 'LB', {
  vpc,
  internetFacing: true
});
const listener = lb.addListener('PublicListener', { port: 80 });

// Attach ALB to ECS Service
listener.addTargets('ECS', {
  port: 80,
  targets: [service],
  // include health check (default is none)
  healthCheck: {
    interval: cdk.Duration.seconds(30)
  }
});

new cdk.CfnOutput(stack, 'LoadBalancerDNS', { value: lb.loadBalancerDnsName, });

app.synth();
```

Then look at the security groups associated with the EC2 instances.  There are no ingress groups to allow traffic from the load balancer to the instance.

### Error Log
N.A.

### Environment

  - **CLI Version      :** 1.9.0
  - **Framework Version:** 1.9.0
  - **OS               :** macOS 10.14.6
  - **Language         :** all

### Other
Also given the issue described in #4267, I would expect to have this stack fail as well.

--- 

This is :bug: Bug Report

**Comment by jd-carroll** [comment]
_[Please note updated title and update at top]_

Below is a list of major features missing from the `NetworkLoadBalancer` making it unusable.  The fix for most of these features will be pulling the existing implementation out of the corresponding `ApplicationLoadBalancer` resource and into the shared `BaseLoadBalancer` resource.

**As stated above, the lack of these features and the lack of auto-generated Cfn* resource for these resources makes NetworkLoadBalancers unusable.** 

NetworkLoadBalancer
---
* No connection support
* No security group support
* Cannot configure access logs

NetworkListener
---
* No connection support
* Missing TLS support

NetworkTargetGroup
---
* Missing support for metrics

Again, I think the fix is going to pretty straight forward.  In most cases it will be taking the current feature from the `ApplicationLoadBalancer` and pulling it into the `BaseLoadBalancer`. But before I start down that road, I'd like to confirm that this would be the supported direction.

**Comment by jd-carroll** [comment]
Update #3

This is partly user error 🙏 (60%)

I've updated all of the existing comments with my latest knowledge, please take a gander at both and we can continue the conversation from there.

**Comment by rix0rrr** [comment]
Closing as a duplicate of https://github.com/aws/aws-cdk/issues/1490, please reopen if you think this has been closed in error.

**Comment by jd-carroll** [comment]
@rix0rrr - The issue listed above is probably a better location for the discussion around security groups.  However, I still feel there are issues with the current NetworkLoadBalancer.  I'll update the title again, because I don't think the NetworkLoadBalancer is unusable any more.  But there are certainly missing features and some discrepancies.

In the cases where there are missing attributes reported, it is still possible to add them through a generic `addAttribute` function on the shared object.  However, they are highlighted because the equivalent on the application-load-balancer side has specific support for the same attribute.

**If you still feel like the workarounds are acceptable, please re-close this issue.**

### NetworkLoadBalancer
Missing Attributes
* access_logs.s3.enabled - Indicates whether access logs are enabled. The value is true or false. The default is false.
* access_logs.s3.bucket - The name of the S3 bucket for the access logs. This attribute is required if access logs are enabled. The bucket must exist in the same region as the load balancer and have a bucket policy that grants Elastic Load Balancing permissions to write to the bucket.
* access_logs.s3.prefix - The prefix for the location in the S3 bucket for the access logs.
[From: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticloadbalancingv2-loadbalancer-loadbalancerattributes.html]

### NetworkListener
* Only 1 certificate is supported, and it does not use the same resource construct (CfnListenerCertificate) as the application listener
[From: https://docs.aws.amazon.com/elasticloadbalancing/latest/network/create-tls-listener.html]

### NetworkTargetGroup
* No support for adding metrics

Missing Attributes:
* deregistration_delay.timeout_seconds - The amount of time, in seconds, for Elastic Load Balancing to wait before changing the state of a deregistering target from draining to unused. The range is 0-3600 seconds. The default value is 300 seconds. If the target is a Lambda function, this attribute is not supported.
[From: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticloadbalancingv2-targetgroup-targetgroupattribute.html]


Additionally, the number and types of metrics offered on each side of the network / application load balancer seem to be duplicative and inconsistent.

**Comment by rix0rrr** [comment]
We have the new issue, so closing this one again.
