### ISSUE TITLE
ECS: TaskDefinition.network mode does not support empty (aka <default>) value

### ISSUE THREAD

**Issue by kolomied** [aws/aws-cdk#4272]
When working with ECS clusters and using Windows containers, ```networkMode``` has to be empty. See CloudFormation docs [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-taskdefinition.html#cfn-ecs-taskdefinition-networkmode):

> When you register a task definition with Windows containers, **you must not specify a network mode**.  If you use the console to register a task definition with Windows containers, you must choose the <default> network mode object. 

Current implementation does not support that case. Despite the fact that ```networkMode``` property is nullable, TaskDefinition construct maps it to the default value for Fargate/EC2 enironment:

https://github.com/aws/aws-cdk/blob/462055269c62a475201bbd51dc29768d32e31add/packages/%40aws-cdk/aws-ecs/lib/base/task-definition.ts#L248-L249

### Reproduction Steps

Here is the snippet (in C#, TypeScript would be a direct equivalent):
```c#
    var taskDefinition = new TaskDefinition(this, "apiTask", new TaskDefinitionProps()
    {
        // Important to specify this, see https://github.com/Microsoft/IIS.ServiceMonitor/issues/34
        Cpu = "1024",
        MemoryMiB = "1024",
        Compatibility = Compatibility.EC2,

        // Important for Windows containers! (but it does not work as you would hope)
        NetworkMode = null,
    });
```
Resulting CloudFormation snippet:

```yaml
      NetworkMode: bridge
      RequiresCompatibilities:
        - EC2
```
### Other

I understand that we can't change the current behavior to preserve backward compatibility. What if we add a new ```DEFAULT``` value to [NetworkMode](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs.NetworkMode.html) enum to support this Windows-specific case?

I can work on a PR for this.

**Comment by rix0rrr** [comment]
Yes, that seems appropriate. 

However, all current checks that involve `networkMode` will have to be re-evaluated as well.

We need someone with domain knowledge for this. @pkandasamy91, @iamhopaul123 ?

**Comment by kolomied** [comment]
Meanwhile, here is the workaround that seems to work for this case: 

```c#
    // Workaround for https://github.com/aws/aws-cdk/issues/4272
    if (taskDefinition.Node.DefaultChild is CfnTaskDefinition cfnTaskDefinition)
        cfnTaskDefinition.NetworkMode = null;
```

**Comment by iamhopaul123** [comment]
That's a good call. I think to minimize the code change and trying to avoid breaking, we can create another networkMode called "NAT" so that users can leave that field empty for Windows users.

**Comment by pkandasamy91** [comment]
@kolomied I believe there's a NetworkMode.NONE enum. Did you try using that instead?

**Comment by kolomied** [comment]
@pkandasamy91 I tried, but it is not the same as no network mode specified. ```NONE``` is a legitimate value to disable external networking for the container - covered in the [docs](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#network_mode).

I concur with @iamhopaul123  - ```NAT``` is a good choice as it clearly conveys the meaning.

**Comment by pkandasamy91** [comment]
Thanks for testing it out @kolomied! I like the idea of creating a new enum instead of leaving it as empty. 

As @rix0rrr mentions, you will need to change the validation logic in a couple places, but if you'd like to work on the PR for this that would be awesome!

> @pkandasamy91 I tried, but it is not the same as no network mode specified. `NONE` is a legitimate value to disable external networking for the container - covered in the [docs](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#network_mode).
> 
> I concur with @iamhopaul123 - `NAT` is a good choice as it clearly conveys the meaning.

Thanks for testing it out @kolomied! I like the idea of creating a new enum instead of leaving it as empty. 

As @rix0rrr mentions, you will need to change the validation logic in a couple places, but if you'd like to work on the PR for this that would be awesome!

**Comment by kolomied** [comment]
@pkandasamy91 @iamhopaul123 Just submitted the PR. Verified everything on my local box, but still the build fails on the build machine. Not sure what else I can try here. Any help is appreciated.
