### ISSUE TITLE
Support higher level constructs for AppSync

### ISSUE THREAD

**Issue by hoegertn** [aws/aws-cdk#4277]
I propose the implementation of higher-level constructs for AppSync. Is this something that other people would find helpful?

### Use Case

It would make implementing applications using AppSync easier than using the low-level objects.

### Proposed Solution

This is subject to discussion. I am developing an AppSync application right now and would create higher-level constructs on the way if this is of interest.

### Other

* [X] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by hoegertn** [comment]
@eladb @rix0rrr What do you think?

**Comment by hoegertn** [comment]
@shivlaks Any comment on this proposal? IF this is of interest I would push a first draft implementation this week. It is a preliminary result of my current AppSync application.

**Comment by ranguard** [comment]
@hoegertn I was just going to share https://github.com/nestorstay/cdk-constructs/tree/master/constructs/appsync which is a very basic (but working) set of wrappers around Cfn for AppSync, currently with only DynDB datasource
support.

Would be great to get a `@aws-cdk/cdk-appsync` package, so my advise could be... don't ask for permission to submit... just submit and see what happens :)

**Comment by hoegertn** [comment]
@ranguard Ok, I will submit my work today as a WIP PR and then we can discuss it.

**Comment by hoegertn** [comment]
This is merged into master
