### ISSUE TITLE
feat(s3deploy.BucketDeployment): Allow IAM Role override

### ISSUE THREAD

**Issue by DavidChristiansen** [aws/aws-cdk#4281]
I wish to be able to specify an existing Role to the `s3deploy.BucketDeployment` construct

### Use Case

Not every environment allows developers to create IAM Roles, but use a role provided to them by an admin instead.

### Proposed Solution

```
new s3deploy.BucketDeployment(this, "DeployWebsite", {
      sources: [s3deploy.Source.asset(webAppRoot)],
      destinationKeyPrefix: "web/",
      destinationBucket: bucket,
      distribution: cdn,
      role: myExistingRole,
      retainOnDelete: false,
    });
```

* [x ] :wave: I may be able to implement this feature request

---

This is a :rocket: Feature Request

**Comment by mcalello** [comment]
@DavidChristiansen - Thanks David - as I need this recently added feature.  Can you provide any insight to what the least privilege set of permissions that a provided Role here would require?
