### ISSUE TITLE
Vpc.fromLookup by name finds deleted vpcs

### ISSUE THREAD

**Issue by AlecErasmus** [aws/aws-cdk#4290]
I used Vpc.fromLookup to find a VPC by its name.  The first time is used it it found the correct vpc.  After a while I teared down the VPC stack and re-created it, but now when I run the code Vpc.fromLookup i find the previous stack(deleted) and then further down the stack I get the error VPC does not exists.

### Reproduction Steps

1.  Create vpc with a name using cdk.
2. Find vpc by name
```
const vpc = ec2.Vpc.fromLookup(this, "VPC", {
        vpcName: "SampleVPC"
});
```
3. Destroy vpc stack
4. Recreate the vpc with the same name(re-run stack)
5. Find the vpc by name.  The vpc id you get back is the vpc you created in step 1

### Environment

  - **CLI Version      :aws-cli/1.16.180 Python/3.7.3 Darwin/18.7.0 botocore/1.12.170**
  - **CDK Version      :1.9.0 (build 30f158a)**
  - **OS               :MacOS 10.14.6 **
  - **Language         :TypeScript**

### Other

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
The VPC ID has been cached in `cdk.context.json`. Edit the file or use `cdk context` to manage the settings in there.
