### ISSUE TITLE
Add "enableSpotInstanceDraining Field

### ISSUE THREAD

**Issue by pavneeta** [aws/aws-cdk#4301]
ECS just launched Automated Spot Instance Draining and It would be great if we could add the `enableSpotInstanceDraining`field in the CDK . See the what's new post here - https://aws.amazon.com/about-aws/whats-new/2019/09/amazon-ecs-supports-automated-draining-for-spot-instances-running-ecs-services/

### Use Case

This Tweet explains it well - https://twitter.com/pahudnet/status/1177770120577306624

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by nmussy** [comment]
It's either dependent or a duplicate of #1711
