### ISSUE TITLE
CodePipeline cross-account deploy

### ISSUE THREAD

**Issue by cbrothersnow** [aws/aws-cdk#4306]
description of the bug:  
codepipelineactions.CloudFormationCreateUpdateStackAction since 1.9.0 is using the wrong artifact bucket key because it's looking for the key in the cross account instead of the build account.  Before the cdk 1.9.0 changes my cross account deploy worked great.  Now, with 4 day till going live, I can no longer deploy across accounts.  I get the error:

```
Action execution failed
Key 'arn:aws:kms:us-west-2:123456789:key/5445e8ce-b6a6-4f48-a00c-a4c0c3542621' does not exist (Service: Amazon S3; Status Code: 400; Error Code: KMS.NotFoundException; Request ID: 1F8CB6D823E8CC03; S3 Extended Request ID: VAXq8Ijm50/jQ/62YBtPg1pQUS2QxfI+24VxCtRxxMRHNl3Tdsks5PvRcUyLWBCxIjkTcEAmDmg=) 
```

because the arn should be arn:aws:kms:us-west-2:*build account not deploy account*:key...  I think you mentioned using the kmskeyid instead of the kmskeyarn.  The pipelineartifact bucket key is, of course, in the build account not in the deploy account.

### Reproduction Steps
This action causes an error because of the pipeline artifact kms key.  I have a deployrole in the deploy account with permission to use the build account pipeline artifact key.  But it's trying to find the key in the deploy account.  

```ts
 const NetworkCreateUpdateStack = new codepipelineactions.CloudFormationCreateUpdateStackAction({ 
            account: props.deployAccount,
            region: props.deployRegion,
            outputFileName: "NetworkStackOutput.json",
            capabilities: [CloudFormationCapabilities.NAMED_IAM],
            templatePath:  new codepipeline.ArtifactPath(cdkOutput, props.beginDeployNameDashes + "-NetworkStack.template.json"),
            adminPermissions: false,
            stackName: props.beginDeployNameDashes + '-NetworkStack',
            actionName: "CreateReplaceChangeSet",
            deploymentRole: deployerRole,
            role: deployerRole,
        });  
        pipeline.addStage({
            stageName: 'NetworkCreateUpdateStack',
            actions: [NetworkCreateUpdateStack],
        });
```

### Error Log

The pipeline fails on the deploy cdk template stage with:

```
Action execution failed
Key 'arn:aws:kms:us-west-2:123456789:key/5445e8ce-b6a6-4f48-a00c-a4c0c3542621' does not exist (Service: Amazon S3; Status Code: 400; Error Code: KMS.NotFoundException; Request ID: 1F8CB6D823E8CC03; S3 Extended Request ID: VAXq8Ijm50/jQ/62YBtPg1pQUS2QxfI+24VxCtRxxMRHNl3Tdsks5PvRcUyLWBCxIjkTcEAmDmg=) 
````

because 123456789 is the deploy account, but the key/5445e8ce-b6a6-4f48-a00c-a4c0c3542621 in in the build account

### Environment

  - **CLI Version      :1.10.0
  - **Framework Version:8.12.0
  - **OS               :Linux
  - **Language         :nodejs

### Other

If you could give me an idea of how to work around this, that would be great.  I can't seem to figure out how to re-install cdk version 1.8.0 . I'm supposed to deploy to production on 10/4, but this is broken.

--- 

This is :bug: Bug Report

**Comment by cbrothersnow** [comment]
I found the problem.  In v1.8.0 the artifactstores looked like this:
"ArtifactStores": [
          {
            "ArtifactStore": {
              "EncryptionKey": {
                "Id": {
                  "Fn::GetAtt": [
                    "PipelinePipelineArtifactBucketKey46F58D83",
                    "Arn"
                  ]
                },
                "Type": "KMS"
              },
              "Location": {
                "Ref": "Pipelinesetajsuswest2qaartifactbucketE40E6D89"
              },
              "Type": "S3"
            },
            "Region": "us-west-2"
          }
        ],

and everything worked because it's using the kmskey arn.
With 1.9.0 it's doing this with the artifact stores:
"ArtifactStores": [
          {
            "ArtifactStore": {
              "EncryptionKey": {
                "Id": {
                  "Ref": "PipelinePipelineArtifactBucketKey46F58D83"
                },
                "Type": "KMS"
              },
              "Location": {
                "Ref": "Pipelinesetajsuswest2qaartifactbucketE40E6D89"
              },
              "Type": "S3"
            },
            "Region": "us-west-2"
          }
        ],
        "Name": "set-ajs-us-west-2-qa-pipeline"
      },
so it's using the kmskey id instead of the arn.

To work around, i synthized the pipeline template, and removed the artifactstore key statement and manually created the pipeline through the cloudformation create. Ugh

**Comment by cbrothersnow** [comment]
Is there a way to override the pipeline artifact store in cdk?

**Comment by skinny85** [comment]
Hey @cbrothersnow ,

apologies for the breakage. You are correct that it's a bug. We're fixing it in #4276 . In the meantime, I see 2 ways out:

* Pin your versions in `package.json` to `1.8.0`. Because of transitive dependencies and this issue: #3711, you might have to pin more modules (like `@aws-cdk/aws-s3`, `@aws-cdk/core`, etc.) then you have in your `package.json` now.
* Stay with `1.9.0`, but use [overrides](https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html#cfn_layer_raw) to change it:


```ts
        const cfnPipeline = pipeline.node.defaultChild as cdk.CfnResource;
        cfnPipeline.addPropertyOverride('ArtifactStores.0.ArtifactStore.EncryptionKey.Id',
            key.keyArn);
```

Let me know if this works! I don't want to mess up your production launch :(. Feel free to ping me directly though Gitter (https://gitter.im/awslabs/aws-cdk) if you have any more questions.

Thanks,
Adam

**Comment by cbrothersnow** [comment]
That you so much for getting back to me so quickly!  Yes, the override worked beautifully.  I just couldn’t figure out how to do the override syntax.

I’d upgraded to 1.9 and then 1.10 and everything was fine.  Until I redid the pipelines to add an approval stage ☹

What a panic.  All is well for now.


Carol Brothers
Senior DevOps Engineer
[signature_2128192346]

Email: carol.brothers@ucop.edu
Phone: (510) 587-6224
University of California, Office of the President
300 Lakeside Drive, 12th floor, 12216
Oakland, CA 94612
[Title: LinkedIn - Description: LinkedIn icon]<https://www.linkedin.com/in/carolbrothers>

**Comment by skinny85** [comment]
I'm glad the fix worked. Apologies for the bad experience again. Like I said, we're already in the process of changing it in #4276 , so hopefully `1.11.0` will no longer require the override (you can always confirm with `cdk diff`, or just look at the resulting template, to make 100% sure).

Thanks,
Adam

**Comment by cbrothersnow** [comment]
Actually, it looked like it should work because it put the kmskey arn, but it didn’t.  So something is also happening on cdk deploy 1.10.1

The only way it works is for me to cdk syth the template and then use Cloudformation design template to deploy.


Carol Brothers
Senior DevOps Engineer
[signature_1164894270]

Email: carol.brothers@ucop.edu
Phone: (510) 587-6224
University of California, Office of the President
300 Lakeside Drive, 12th floor, 12216
Oakland, CA 94612
[Title: LinkedIn - Description: LinkedIn icon]<https://www.linkedin.com/in/carolbrothers>

**Comment by skinny85** [comment]
Can you be more specific? What doesn't work with the override - what error do you get?

**Comment by cbrothersnow** [comment]
I get an S3 access denied when I do the first template deploy, which indicates an artifact key issue.

If I cdk synth the pipeline template, and use the CloudFormation Design template feature, upload and deploy the template, everything is fine.
If I use cdk deploy the pipeline template, I get the S3 access denied error.  I can only guess that cdk deploy is doing some stuff as it deploys the cloudformation template?

I have a build account with a codecommit repo and several pipelines.  One pipeline to deploy to the dev account that triggers on testing-branch changes, one pipeline to deploy to the qa account that triggers on a release-branch changes, one pipeline to deploy to the prod account that triggers on the master branch changes.

I need to log into each account and run a crossaccountroles.ts script to create a role that is assumable by the codepipeline roles in the build account.  I also need to have this script give the created assumable deployerrole access to the pipeline artifact bucket and kmskey.  There really isn’t any other way as you wouldn’t want to be able to deploy to an account that isn’t yours.

I manually create the pipeline in the build account, because the cloudformation deploy won’t let you deploy over the pipeline.
My pipeline:
Stage 1) get the codecommit repo source
Stage 2)  gradle build my java web application
Stage 3) put the application in a docker container and push the image to the ECR
Stage 4) cdk synth all the templates of my infrastructure.
Stage 5) Approval
I don’t want one giant stack, so I have several stack that seem manageable:
Stage6) cloudformation deploy a network stack template created in stage 4
Stage 7) cloudformation deploy an rds stack template created in stage 4
Stage 8) cloudformation deploy an application stack template created in stage 4
Stage 9) cloudformation deploy a monitor stack template created in stage 4

It may seem over-engineered, but It was all working in 1.8.0 and I was happy and bragging about going to production.

I am modeling on this AWS whitepaper https://aws.amazon.com/blogs/devops/aws-building-a-secure-cross-account-continuous-delivery-pipeline/

It really does set us up to have a production environment that nobody needs to log into except in break glass scenario.  And CDK is a wonderful tool.  I originally wrote it all in sceptre/python.  But I like CDK a lot better.





Carol Brothers
Senior DevOps Engineer
[signature_798382074]

Email: carol.brothers@ucop.edu
Phone: (510) 587-6224
University of California, Office of the President
300 Lakeside Drive, 12th floor, 12216
Oakland, CA 94612
[Title: LinkedIn - Description: LinkedIn icon]<https://www.linkedin.com/in/carolbrothers>

**Comment by skinny85** [comment]
OK. Can you run the  command `cdk diff` after you've deployed the working version of the template, and after you've applied the override in the code, and paste the output you get?

**Comment by cbrothersnow** [comment]
Maybe tomorrow.  I stayed up late last night freaking out about this, lol.  And woke up super early to get it fixed.  I just now got all the pipelines working again, though what is a very manual process. It was awesome you got 1.10.1 out so quickly so I could use 1.8.0

But I don’t mind tomorrow trying some more things in the dev deploy account.  Maybe if I update everything to 1.10.1, and now with the override, it’ll just work?  it would be interesting to see what cdk diff tells me.


Carol Brothers
Senior DevOps Engineer
[signature_782658940]

Email: carol.brothers@ucop.edu
Phone: (510) 587-6224
University of California, Office of the President
300 Lakeside Drive, 12th floor, 12216
Oakland, CA 94612
[Title: LinkedIn - Description: LinkedIn icon]<https://www.linkedin.com/in/carolbrothers>

**Comment by cbrothersnow** [comment]
Okay, duh, it was easy to run the cdk diff….and there is no difference.  So, is there a difference in the mechanism of using “cdk deploy” and the “Create stack” button on the design template?  Are they using the same API?

It could also be that I’m super tired and was just not being careful when doing one thing or another.  Again, maybe I’ll try it all once more tomorrow, this time carefully.


Carol Brothers
Senior DevOps Engineer
[signature_889622914]

Email: carol.brothers@ucop.edu
Phone: (510) 587-6224
University of California, Office of the President
300 Lakeside Drive, 12th floor, 12216
Oakland, CA 94612
[Title: LinkedIn - Description: LinkedIn icon]<https://www.linkedin.com/in/carolbrothers>

**Comment by skinny85** [comment]
There is no difference between the 2 deploy mechanisms. So, if `cdk diff` shows no difference, then something else must be at play here.

**Comment by cbrothersnow** [comment]
I did the whole thing over again carefully, and using the override and cdk deploy pipeline everything worked great.  So this fixed it:

        const cfnPipeline = pipeline.node.defaultChild as cdk.CfnResource;
        cfnPipeline.addPropertyOverride('ArtifactStores.0.ArtifactStore.EncryptionKey.Id',
            kmsKey.keyArn);



Carol Brothers
Senior DevOps Engineer
[signature_77527524]

Email: carol.brothers@ucop.edu
Phone: (510) 587-6224
University of California, Office of the President
300 Lakeside Drive, 12th floor, 12216
Oakland, CA 94612
[Title: LinkedIn - Description: LinkedIn icon]<https://www.linkedin.com/in/carolbrothers>

**Comment by skinny85** [comment]
👍

**Comment by cbrothersnow** [comment]
Back at you.  See you’ve fixed it already and released.  I’ll test.


Carol Brothers
Senior DevOps Engineer
[signature_1893684394]

Email: carol.brothers@ucop.edu
Phone: (510) 587-6224
University of California, Office of the President
300 Lakeside Drive, 12th floor, 12216
Oakland, CA 94612
[Title: LinkedIn - Description: LinkedIn icon]<https://www.linkedin.com/in/carolbrothers>

**Comment by skinny85** [comment]
Like I said, this is fixed in #4276 , which has not been merged yet.

**Comment by skinny85** [comment]
Hey @cbrothersnow ,

this has now been released in `1.13.0`. I'm going to resolve this one, feel free to comment if it still doesn't work with the newest release, and I'll investigate further.

Thanks,
Adam

**Comment by sergikpas** [comment]
Hey @skinny85 ,
I just tried it on 1.13.1, it still get the same issue as @cbrothersnow :(
Still works only with workaround provided by you.

Thanks
Sergey

**Comment by sergikpas** [comment]
> Hey @skinny85 ,
> I just tried it on 1.13.1, it still get the same issue as @cbrothersnow :(
> Still works only with workaround provided by you.
> 
> ![image](https://user-images.githubusercontent.com/19192955/66901415-f143e100-effe-11e9-998d-b51ce183e66d.png)
> 
> Thanks
> Sergey

Sorry, I missed update packages - looks that it fixed! Please ignore my last comment
