### ISSUE TITLE
aws_s3.CfnBucket publicAccessBlockConfiguration property skips blockPublicPolicy and ignorePublicAcls options

### ISSUE THREAD

**Issue by borisyukd** [aws/aws-cdk#4312]
CfnBucket class of aws_s3 module has `public_access_block_configuration` parameter.
According to [Documentation](https://docs.aws.amazon.com/en_pv/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-publicaccessblockconfiguration.html) and [Interface Property description](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-s3.CfnBucket.PublicAccessBlockConfigurationProperty.html) it receives 4 boolean parameters:
- blockPublicAcls
- blockPublicPolicy
- ignorePublicAcls
- restrictPublicBuckets

But `cdk synth` creates JSON template with 2 parameters only:
- BlockPublicAcls
- RestrictPublicBuckets

### Reproduction Steps

```bash
cdk init app --language=python
```
copy code to test/test_stack.py
```python
        # The code that defines your stack goes here
        s3.CfnBucket(
            self, 'S3Bucket',
            bucket_name='s3-bucket',
            public_access_block_configuration={
                'blockPublicAcls': True,
                'blockPublicPolicy:': True,
                'ignorePublicAcls:': True,
                'restrictPublicBuckets': True,
            },
        )
```
Run:
```bash
cdk synth
cat cdk.out/test.template.json 
{
  "Resources": {
    "S3Bucket": {
      "Type": "AWS::S3::Bucket",
      "Properties": {
        "BucketName": "s3-bucket",
        "PublicAccessBlockConfiguration": {
          "BlockPublicAcls": true,
          "RestrictPublicBuckets": true
        }
      },
      "Metadata": {
        "aws:cdk:path": "test/S3Bucket"
      }
    }
  }
}
```

### Error Log

Empty

### Environment

  - **CLI Version      : 1.10.0**
  - **Framework Version: 1.10.0**
  - **OS               : Ubuntu**
  - **Language         : Python**

### Other

--- 

This is :bug: Bug Report

**Comment by nmussy** [comment]
You have an additional colon in your property keys in your reproduction:

```python
                'blockPublicPolicy:': True,
                'ignorePublicAcls:': True,
```

should be:

```python
                'blockPublicPolicy': True,
                'ignorePublicAcls': True,
```
