### ISSUE TITLE
RestApi.addRequestValidator has incorrect doc comment

### ISSUE THREAD

**Issue by Ricool06** [aws/aws-cdk#4331]
https://github.com/aws/aws-cdk/blob/c35091f993b32f81792512088ff807d0621198bd/packages/%40aws-cdk/aws-apigateway/lib/restapi.ts#L318

RestApi.addRequestValidator's doc comment current says, "Adds a new model."
It should say "Adds a new request validator."

Simple change but worth doing so I've opened a PR :).

---

This is a 📕 documentation issue

**Comment by SomayaB** [comment]
Hi @Ricool06, thanks for working on this! 
I do think If we're going to change the docs here we should also reflect that change on the API reference [here](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-apigateway.RestApi.html#methods) and [here](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-apigateway.RestApi.html#add-wbr-request-wbr-validatorid-props). 

@rix0rrr could you provide guidance on how to do that?

**Comment by Ricool06** [comment]
Good point! I did a find all in vscode for "adds a new model" but that didn't appear.
Thanks for taking the time to look at this.
