### ISSUE TITLE
ApplicationLoadBalancedFargateServiceProps no longer has properties that were moved into TaskImageOptions

### ISSUE THREAD

**Issue by vgribok** [aws/aws-cdk#4335]
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs-patterns.ApplicationLoadBalancedFargateServiceProps.html

The doc for `ApplicationLoadBalancedFargateServiceProps` still contains properties like `Image`, `Environment` and a few others that seem to have been rolled up into the `TaskImageOptions` property of `IApplicationLoadBalancedTaskImageOptions` type - seeing this in .NET CDK 1.10.

---

This is a 📕 documentation issue

**Comment by NGL321** [comment]
Looks like this is correct. Changing the issue a bug. The props changes are [here](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-ecs-patterns/lib/base/application-load-balanced-service-base.ts) and should be represented in the API Reference.

😸

**Comment by pkandasamy91** [comment]
The documentation looks to be updated now.

**Comment by vgribok** [comment]
Verified, documentation is updated. Closing the issue.
