### ISSUE TITLE
Support for TCP_UDP as a supported protocol

### ISSUE THREAD

**Issue by dkovvuri** [aws/aws-cdk#4341]
It's currently possible to create a network load balancer listener that supports dual protocols of TCP and UDP by setting the protocol to TCP_UDP. 

"TCP_UDP" protocol is supported by CloudFormation for [AWS::ElasticLoadBalancingV2::Listener](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-listener.html#cfn-elasticloadbalancingv2-listener-protocol)

Currently, the `enum` for Protocols only allows HTTP, HTTPS, TCP, or TLS, but doesn't support the value 'UDP' or 'TCP_UDP' - [code path](https://github.com/aws/aws-cdk/blob/19ae072be9788a0c1ae7d3a347a99b3f3494f010/packages/%40aws-cdk/aws-elasticloadbalancingv2/lib/shared/enums.ts#L19)

Workaround: Using Escape Hatches - https://docs.aws.amazon.com/en_pv/cdk/latest/guide/cfn_layer.html#cfn_layer_raw

This is a :rocket: Feature Request

**Comment by NGL321** [comment]
Hi @dkovvuri,

This seems like a reasonable feature request. Thank you for providing all the tracking info!

We will look into implementing this, but if you would like to see it implemented quickly, your best bet is to put in a PR (if you do feel free to tag me and I will review).

😸

**Comment by nmussy** [comment]
This would also be the occasion to add support to UDP (#3107).

I'll make a PR for both.
