### ISSUE TITLE
Trying to find examples for CDK requires a PHD in the Google arts.

### ISSUE THREAD

**Issue by reduxdj** [aws/aws-cdk#4350]
Can you add this to your documentation please

https://github.com/aws/aws-cdk/pull/1719/commits/a6e912970273bedea494df4f01b71bc203d3403a

---

This is a 📕 documentation issue

**Comment by skinny85** [comment]
It is there, just in an updated form that's correct in version `1.0.0` and later (the original is no longer valid): https://docs.aws.amazon.com/cdk/api/latest/docs/aws-s3-readme.html#permissions

**Comment by NGL321** [comment]
Hey @reduxdj,

I hope this answered your question! If I am incorrect in that assumption, please feel free to reopen this issue.
