### ISSUE TITLE
DockerImageAsset: exclude option is ignored

### ISSUE THREAD

**Issue by kuwabarahiroshi** [aws/aws-cdk#4353]
[DockerImageAsset is documented](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecr-assets.DockerImageAsset.html#construct-props
) that it has `exclude?` property.

Then, I specified my image such as below:

```ts
const image = new DockerImageAsset(this, 'MyProjectImage', {
  directory: path.join(__dirname, '..', '..'),
  repositoryName: 'my-project',
  exclude: ['cdk', 'node_modules', 'tmp', 'log', 'storage', 'vendor']
});
```

It worked until v1.9.0, but the property is ignored since v1.10.0.

I found https://github.com/aws/aws-cdk/commit/8389eeb046ac6da4ef5eae7f90e2cd1079e8ff3a is just overriding the `exclude` property.

Workaround is to list those files into `.dockerignore`. But .dockerignore and `exclude` option behaves a little different.

### Reproduction Steps

```ts
const image = new DockerImageAsset(this, 'MyProjectImage', {
  directory: '.',
  repositoryName: 'my-project',
  exclude: ['cdk', 'node_modules', 'tmp', 'log', 'storage', 'vendor']
});
```

cdk.out shouldn't include those files listed in `exclude` option.

### Environment

  - **CLI Version      :** >= v1.10.0
  - **Framework Version:** 
  - **OS               :** Mac OSX 10.14.5
  - **Language         :** TypeScript

### Other

I just wanted to avoid this issue: https://github.com/aws/aws-cdk/issues/3899

--- 

This is :bug: Bug Report

**Comment by NGL321** [comment]
Hey @kuwabarahiroshi!

Thank you so much for contributing. This issue should be closed out once your PR is merged.
