### ISSUE TITLE
Cannot set context at app level after v1.9.0

### ISSUE THREAD

**Issue by jogold** [aws/aws-cdk#4359]
Cannot set context at app level anymore after v1.9.0. This is because a `Tree` child is automatically created under the app and context cannot be set after children have been added.

Comes from #4194 (3cca03d).

### Reproduction Steps

```ts
const app = new cdk.App();
app.node.setContext('stage', 'dev');
```

### Error Log

`Error: Cannot set context after children have been added: Tree`

### Environment

  - **CLI Version      :** > 1.9.0
  - **Framework Version:** > 1.9.0
  - **OS               :** all
  - **Language         :** all

### Other

--- 

This is :bug: Bug Report

**Comment by eladb** [comment]
You can specify the context when you initialise the app:

```ts
new App({ context: { key: 'value' });
```

Closing for now.

**Comment by jogold** [comment]
How would you set the context if not already set by the CLI?

I was doing:
```ts
const app = new cdk.App();

// Get and set stage context
const stage = app.node.tryGetContext('stage') || process.env.STAGE || 'dev';
app.node.setContext('stage', stage);

```

**Comment by eladb** [comment]
This should work since the CLI context is applied after the initializer’s:

```ts
new App({
  context: { stage: process.env.STAGE || 'dev' }
})
```

Reference: https://github.com/aws/aws-cdk/blob/934d36fed04bdaf24332fc5d38aaee663c6f7347/packages/%40aws-cdk/core/lib/app.ts#L149

Let me know if this works.

**Comment by jogold** [comment]
It works. Thanks 👍 

(could be documented)

**Comment by alex-a-ncino** [comment]
In the case of setting context when we initialize the app, how should the nested structures be handled? Context is expecting [key: string]: string which doesn't allow setting a key to a nested object.

**Comment by chefren** [comment]
If anyone lands here while trying to run pytest (python CDK), the comments above gave me the idea of [this workaround](https://stackoverflow.com/a/72166186/1736679), although I couldn't figure out why pytest `cdk.App()` invocation would fail to get the cdk.json from any place in the repo.

Effectively, creating context in the `App()` invocation works as explained here, so I suppose not using the CLI is the key difference and no mechanism may exist at the moment for pytest to put cdk.json through.

**Comment by et025** [comment]
How would you set the context in this case?

I’m trying to update this code past the 1.9.0 cdk version:

```typescript
const app = new cdk.App();

let stage: string = app.node.tryGetContext('stage');

// AppConfig is a custom defined interface  //stageConfig is a variable of custom defined interface, StageConfig
const appConfig: AppConfig = {
  domainName: app.node.tryGetContext('domainName'),
  isProduction: stage === 'prod',
  stageName: stage,
  // default to getting dev config if stage is other than prod or test
  stageConfig: app.node.tryGetContext(stage === 'prod' || stage === 'test' ? stage : 'dev')
};

// set appConfig as a context variable for downstream stacks to use
app.node.setContext('config', appConfig);
```

**Comment by shellscape** [comment]
@et025 create a new "dummy" instance of `App` and use that app's `stage` value in the initializer of the actual app you want to use. the "dummy" app should be garbage collected.
