### ISSUE TITLE
All Confirm Action names have to be different due to KMS alias name generation bug

### ISSUE THREAD

**Issue by PeterBengtson** [aws/aws-cdk#4365]
Having two CodePipeline Actions with identical names inside Stages with different names should work according to the documentation, but KMS key name generation issues makes it impossible in CDK. Presumably, the synth code doesn't take the Stage name into consideration when creating aliases.

### Reproduction Steps

in the following, if the actionNames are identical, CloudFormation bombs with an KMS error. They have to be different, i.e. not both "Confirm" but "Confirm1" and "Confirm2".

```
      const ApprovalAction1 = new codepipelineActions.ManualApprovalAction({
        actionName: 'Confirm1',
      })
      pipeline.addStage({
        stageName: 'FirstConfirm',
        actions: [ApprovalAction1],
      })

      ...

      const ApprovalAction2 = new codepipelineActions.ManualApprovalAction({
        actionName: 'Confirm2',
      })
      pipeline.addStage({
        stageName: 'SecondConfirm',
        actions: [ApprovalAction2],
      })
```

### Error Log

```
  8/24 | 16:12:52 | CREATE_FAILED        | AWS::KMS::Alias             | Pipeline/ArtifactsBucketEncryptionKeyAlias (PipelineArtifactsBucketEncryptionKeyAlias5C510EEE) alias/codepipeline-pipelinestaginguspipeline0934c352 already exists
```

### Environment

  - **Framework Version: 1.10.1
  - **OS               :All
  - **Language         :All

--- 

This is :bug: Bug Report

**Comment by PeterBengtson** [comment]
This needs wider research. Closing for now.

**Comment by skinny85** [comment]
@PeterBengtson is your problem perhaps the same as #4336 ?

**Comment by PeterBengtson** [comment]
That's precisely what I was going to investigate.
