### ISSUE TITLE
 process.env.CDK_DEFAULT_ACCOUNT and process.env.CDK_DEFAULT_REGION don't work

### ISSUE THREAD

**Issue by hacker65536** [aws/aws-cdk#4372]
These environments worked before. Didn't need to install  `@types/node`.

### Reproduction Steps

```ts
new VpcStack(app, "VpcStack", {
  env: {
    account: process.env.CDK_DEFAULT_ACCOUNT,
    region: process.env.CDK_DEFAULT_REGION,
  },
});
```

### Error Log

```
$ npm run build

> vpc@0.1.0 build /home/ec2-user/vpc
> tsc

bin/vpc.ts:9:14 - error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i @types/node`.

9     account: process.env.CDK_DEFAULT_ACCOUNT,
               ~~~~~~~

bin/vpc.ts:10:13 - error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i @types/node`.

10     region: process.env.CDK_DEFAULT_REGION,
               ~~~~~~~


Found 2 errors.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! vpc@0.1.0 build: `tsc`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the vpc@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ec2-user/.npm/_logs/2019-10-04T07_22_12_135Z-debug.log
```

### Environment

  - **CLI Version      :1.11.0 (build 4ed4d96)**
  - **Framework Version:**
  - **OS               :Amazon linux 2**
  - **Language         :typescript**

### Other

--- 

This is :bug: Bug Report

**Comment by eladb** [comment]
We used to include @types/node in "cdk init" but this was removed since it is not required in normal cases (https://github.com/aws/aws-cdk/pull/3840). You should simply `npm i -D @types/node` if you `process.env`. 

I will make sure we update the relevant documentation topic so this is less surprising.

Also, this behaviour is likely to be changed when we implement https://github.com/aws/aws-cdk/pull/4131

**Comment by eladb** [comment]
Doc fix: https://github.com/awsdocs/aws-cdk-guide/pull/132
