### ISSUE TITLE
FluentdLogDriver breaks deployment

### ISSUE THREAD

**Issue by hertzknight** [aws/aws-cdk#4376]
When I attach my Fluentdlogger to an ECS Task, the service doesn't deploy. I am using the default address of localhost:24224 that should point to my Fluentd Container.

### Reproduction Steps

``` ts
    const fluentdLogger = new ecs.FluentdLogDriver({
      asyncConnect: true,
      env: ["STACK_NAME","REGION","VERSION","MAINTAINER"],
      tag: "nginx"
    });

    const fluentdAWSLogging = new ecs.AwsLogDriver({
        streamPrefix: 'fluentd',
      });
    const fluentdTask = new ecs.TaskDefinition(this,"FluentdTaskDefinition",{
        compatibility: ecs.Compatibility.EC2,
        family: maintainer+'-fluentd',
        networkMode:ecs.NetworkMode.HOST,
      });
    const fluentdContainer = fluentdTask.addContainer('FluentdContainerDefintion',{
        essential: true,
        //Check image
        image:ecs.ContainerImage.fromEcrRepository(
          ecr.Repository.fromRepositoryName(
            this,
            'FluentdRepo',
            'ps-docker-images/fluentd'
          )
        ),
        memoryLimitMiB: 256,
        cpu: 100,
        environment:{
          'STACK_NAME': this.stackName,
          'REGION': this.region,
          'VERSION': version,
          'MAINTAINER': maintainer,
          'FLUENT_CONFIG_SUFFIX': maintainer,
          'AWS_ELASTICSEARCH_URL': logsEsEndpoint
        },
        logging: fluentdAWSLogging
      });
    fluentdContainer.addPortMappings({
        containerPort: 24224,
        hostPort: 24224,
        protocol: ecs.Protocol.TCP
      });
    new ecs.Ec2Service(this,'FluentdService',{
        cluster: packagistCluster,
        taskDefinition: fluentdTask,
        desiredCount: 1,
        minHealthyPercent: 0,
        maxHealthyPercent: 100,
      });
```

### Error Log

> service was unable to place a task because no container instance met all of its requirements. The closest matching container-instance is missing an attribute required by your task

### Environment

  - **CLI Version      :** 1.11.0
  - **Framework Version:** 1.11.0
  - **OS               :** ECS Optimized Amazon linux 2
  - **Language         :** Typescript

### Other
When I checked the instance, I found out that the `ECS_AVAILABLE_LOGGING_DRIVERS` was missing from /etc/ecs/ecs.config.

--- 

This is :bug: Bug Report

**Comment by NGL321** [comment]
Hi @hertzknight,

Thanks for submitting a report! Someone will comment here when there is progress.

Might have to do with PR #3762

**Comment by PettitWesley** [comment]
Hey @hertzknight, I have a guess as to the source of your problem. In the ECS optimized AMI, by default the Fluentd Docker Log Driver is not enabled. 

You can enable it by adding the following user data to your instances:

```
#!/bin/bash
echo "ECS_AVAILABLE_LOGGING_DRIVERS=[\"awslogs\",\"fluentd\"]" >> /etc/ecs/ecs.config
```

**Comment by hertzknight** [comment]
I added ECS_AVAILABLE_LOGGING_DRIVERS and then realised I needed to add \\\" instead of \" as it was sending it just as [awslogs, fluentd], which caused more issues, to the /etc/ecs/ecs.config.
