### ISSUE TITLE
s3.Bucket.grantDelete on bucket with KMS SSE generates invalid policy

### ISSUE THREAD

**Issue by Roman-L** [aws/aws-cdk#4380]
### Reproduction Steps
This simple stack
``` ts
Key sseKmsKey = new Key(this, "lapinr-see-kms-key");

BucketProps bucketProperties = BucketProps.builder()
                                          .bucketName("lapinr-test-bucket")
                                          .encryption(BucketEncryption.KMS)
                                          .encryptionKey(sseKmsKey)
                                          .build();
Bucket bucket = new Bucket(this,
                           "LapinrTestBucket",
                           bucketProperties);

RoleProps clientRoleProps = RoleProps.builder()
                                     .roleName("lapinr-access-role")
                                     .assumedBy(new ArnPrincipal("arn:aws:iam::1234567890:role/external-role"))
                                     .build();
Role clientRole = new Role(this,
                           "LapinrAccessRole",
                           clientRoleProps);

bucket.grantDelete(clientRole);
```

Generates the following policy
``` js
"LapinrAccessRoleDefaultPolicy0F01FF42": {
      "Type": "AWS::IAM::Policy",
      "Properties": {
        "PolicyDocument": {
          "Statement": [
            {
              "Action": "s3:DeleteObject*",
              "Effect": "Allow",
              "Resource": {
                "Fn::Join": [
                  "",
                  [
                    {
                      "Fn::GetAtt": [
                        "LapinrTestBucketDB437746",
                        "Arn"
                      ]
                    },
                    "/*"
                  ]
                ]
              }
            },
            {
              "Effect": "Allow",
              "Resource": {
                "Fn::GetAtt": [
                  "lapinrseekmskey4CB31ADE",
                  "Arn"
                ]
              }
            }
          ],
          "Version": "2012-10-17"
        },
        "PolicyName": "LapinrAccessRoleDefaultPolicy0F01FF42",
        "Roles": [
          {
            "Ref": "LapinrAccessRole015FF5A4"
          }
        ]
      }
```

The problematic part is below, note lack of 'Action' block
``` javascript
{
    "Effect": "Allow",
    "Resource": {
         "Fn::GetAtt": [
            "lapinrseekmskey4CB31ADE",
            "Arn"
         ]
    }
}
```
### Error Log

During CloudFormation stack update, the update fails with a Malformed Policy error due to missing Action block.

### Environment

  - **CLI Version      : 1.9.0**
  - **Framework Version: 1.9.0**
  - **OS               : Linux**
  - **Language         : Java**

--- 

This is :bug: Bug Report

**Comment by Roman-L** [comment]
Taking a look at the code

https://github.com/aws/aws-cdk/blob/960d71fed92e1c9d27dd9ed37c8097bf3846a923/packages/%40aws-cdk/aws-s3/lib/bucket.ts#L451-L454

Which leads to 
https://github.com/aws/aws-cdk/blob/960d71fed92e1c9d27dd9ed37c8097bf3846a923/packages/%40aws-cdk/aws-s3/lib/bucket.ts#L540-L542

Eventually eventually leads to this, without any checks on actions being empty
https://github.com/aws/aws-cdk/blob/69bff3d28687f7db1fb65ef4c967f8cce3b554ec/packages/%40aws-cdk/aws-iam/lib/grant.ts#L167-L171

**Comment by NGL321** [comment]
Might be related to #4381?

**Comment by Roman-L** [comment]
At first glance, doesn't seem like it.

Based on the code snippets I provided above, I believe this issue is due to an empty 'actions' parameter that translates to an empty 'Actions' block in the template. 
If I'm not mistaken, this makes s3.Bucket.grantDelete un-useable for buckets with SSE KMS.

#4381 has to do with a perceived difference between read/write and encrypt/decrypt. (I don't know enough to tell whether it's actually an issue)

**Comment by rix0rrr** [comment]
Yep, this should have had an "empty array" check in there.
