### ISSUE TITLE
ApplicationListener variable `Open` default value to False

### ISSUE THREAD

**Issue by selvathiruarul** [aws/aws-cdk#4385]
Currently, ApplicationListener has an attribute `Open`, which has a default value `True`. 
This opens up a load balancer to all in the case of public LB.  It will be safer to have a default value of `False` and open the Listener if needed.

https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_elasticloadbalancingv2/ApplicationListener.html

### Use Case

To have a secure listener by default

### Proposed Solution

make the default value of `open` to False

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
That is true, but we did this in order to optimize for the common case (is fronting a service with a load balancer available to anyone who can route to the ALB). If you know you want tighter security controls, you know how to get them.

This is unlikely to be changed.
