### ISSUE TITLE
DependsOn does not take Nested Stacks into account

### ISSUE THREAD

**Issue by kbessas** [aws/aws-cdk#4406]
When using Nested stacks, with the Vpc and the ApplicationLoadBalancer defined in different Nested Stacks, the ApplicationLoadBalancer construct appends a DependsOn entry to Routes that are created in the Nested Stack of the Vpc. **As the dependency is not present in the same template file, the stack creation fails in CloudFormation.**

When using multiple Stacks (top-level - not nested), the same DependsOn entry is not there.

### Reproduction Steps

``` py
from aws_cdk import (
    aws_cloudformation as cfn,
    aws_ec2 as ec2,
    aws_elasticloadbalancingv2 as elbv2,
    core,
)

class SkeletonStack(core.Stack):

    def __init__(self, scope: core.Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        self.vpc = ec2.Vpc(
            self, 'Vpc',
            cidr='10.0.0.0/16',
            max_azs=99, # use all available AZs,
            subnet_configuration=[ 
                { 'cidrMask': 27, 'name': 'public-lb', 'subnetType': ec2.SubnetType.PUBLIC }
            ]
        )

class LoadBalancerStack(cfn.NestedStack):

    def __init__(
        self,
        scope: core.Construct,
        id: str,
        vpc: ec2.IVpc,
        **kwargs
    ) -> None:
        super().__init__(scope, id, **kwargs)

        self.alb = elbv2.ApplicationLoadBalancer(
            self, 'ApplicationLoadBalancer',
            vpc=vpc,
            internet_facing=True,
            vpc_subnets={'subnetName': 'public-lb'}
        )

app = core.App()
skeleton = SkeletonStack(app, 'skeleton', env=_REPLACE_ME_)
load_balancer = LoadBalancerStack(skeleton, 'load-balancer', vpc=skeleton.vpc)
app.synth()

```

### Error Log

```
Template format error: Unresolved resource dependencies
```

### Environment

  - **CLI Version      : 1.12**
  - **Framework Version: 1.12**
  - **OS               :**
  - **Language         : python**

### Other

--- 

This is :bug: Bug Report

**Comment by tsykora-verimatrix** [comment]
I have the same issue, CF templates of nested stacks generated by CDK contains DependsOn setting on the parent stack and when trying to deploy I get an error message complaining about template being invalid. In my case it is related to Network LB and LB listeners in the parent stack.
Only workaround that I have atm is: 
1) cdk synth
2) manually delete the DependsOn setting from json files of the nested stacks
3) copy the json files and create the nested stacks manually

  message: 'Template format error: Unresolved resource dependencies...
  code: 'ValidationError',

this is CDK 1.15
