### ISSUE TITLE
aws-ecs - (start|stop)Timeout for `ContainerDefinitionOptions`

### ISSUE THREAD

**Issue by windymelt** [aws/aws-cdk#4410]
In CFn (and console), there is `(start|stop)Timeout` property, but in CDK.

### Use Case

Graceful shutdown for container, especially in batch service.

### Proposed Solution

Add `(start|stop)Timeout` field into `ContainerDefinitionOptions`.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by konstantinj** [comment]
We need that as well.
