### ISSUE TITLE
Usage of cdk.StackProps.stackName when having multiple stacks with the same name

### ISSUE THREAD

**Issue by konstantinj** [aws/aws-cdk#4412]
I'm having multiple stacks with the same name in different accounts/regions. Consider following example code:

```typescript
const app = new cdk.App()
new cdk.Stack(app, 'test1', { stackName: 'test', env: { account: 'XXXXXXXXXXXX', region: 'eu-west-1' } })
new cdk.Stack(app, 'test2', { stackName: 'test', env: { account: 'XXXXXXXXXXXX', region: 'us-east-1' } })
```

1) `cdk synth` is creating only one template for `test2`since it's the last one but the template is named `test`. `test1` gets overwritten.

2) `cdk list` also only lists the stack `test` and it's not possible to see the corresponding env

3) `cdk deploy` can only deploy `test2` as `cdk deploy test`

How is the stackName supposed to work? It looks like the stackName, when set, is treated as the main citizen here even though it's not unique.

Tested with cdk version `1.12.0`

#4339 maybe something like `visibleStackName` makes more sense.

**Comment by konstantinj** [comment]
I've investigated a bit more. I've found `deployName` in https://github.com/aws/aws-cdk/blob/master/packages/aws-cdk/lib/api/deploy-stack.ts#L52

What is this? If it would be possible to set a stackName on `cdk deploy` that would be awesome. Unfortunately I haven't found where this is coming from or how it's set.

But I was able to set just the visible stackName by abusing the stack tags like this:

In my Custom stack
```typescript
cdk.Tag.add(this, 'stackName', 'test');
```

In https://github.com/aws/aws-cdk/blob/master/packages/aws-cdk/lib/api/deploy-stack.ts
```javascript
for (var i in options.tags) {
    if (options.tags[i]["Key"] == "stackName") {
        options.deployName = options.tags[i]["Value"];
}
```

So if there would be a clean way of setting the deploy/stackName that would be great.

**Comment by konstantinj** [comment]
found it.

https://github.com/aws/aws-cdk/blob/7d6b4748176db300ecb323bc03a7eb7032f55a09/packages/aws-cdk/lib/cdk-toolkit.ts#L145
would need to be:
```typescript
deployName: options.deployName || stack.name,
```

and https://github.com/aws/aws-cdk/blob/7d6b4748176db300ecb323bc03a7eb7032f55a09/packages/aws-cdk/bin/cdk.ts#L197 needs an additional field:
```typescript
sdk: aws,
deployName: args.deployName,
```

and the manual has to be changed accordingly. I need this desperately. And since it looks like this was planned anyhow I'll create a PR for it.

**Comment by amoraes** [comment]
Any new about this issue? I am having the same problem with latest version 1.15.

**Comment by konstantinj** [comment]
@amoraes I'm doing this now with my own deploy-name implementation: https://github.com/aws/aws-cdk/pull/4514#issuecomment-543593988

**Comment by eladb** [comment]
This is a bug.

Basically the issue here is that the synthesized template file name is based on the stack name and not on the uniqueId of the stack construct. When `stackName` is not specified, it defaults to the ID of the Stack construct, so the template name == stack name.
