### ISSUE TITLE
core.RemovalPolicy indicates wrong default

### ISSUE THREAD

**Issue by azatoth** [aws/aws-cdk#4416]
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.RemovalPolicy.html

The documentation indicates that `DESTROY` is the "default removal policy", though the source code seems to indicate that `RETAIN` is the default. 
I assume the code is more correct and thus the documentation is wrong.

---

This is a 📕 documentation issue

**Comment by SomayaB** [comment]
Duplicated by #4444
