### ISSUE TITLE
Review & Harmonize CDK init templates

### ISSUE THREAD

**Issue by RomainMuller** [aws/aws-cdk#4418]
We should make sure all the init templates we have across the languages are consistent (same set of templates across all the languages, with similar/comparable content).

**Comment by NGL321** [comment]
- [ ] App initialization for C# no longer requires explicit `null` param
- [ ] C# and Java pass `Construct` param called `parent` instead of `scope`
- [ ] Java init template creates sample app instead of empty template

**Comment by shivlaks** [comment]
Fixed in #5067

**Comment by NGL321** [comment]
Closing after fix
