### ISSUE TITLE
aws-rds doesn't support AssociatedRoles attribute

### ISSUE THREAD

**Issue by rahouskiids** [aws/aws-cdk#4419]
### The Question
Using RDS AssociatedRoles is required in order to setup RDS S3 integration for Oracle and likely other database types. For example, to be able to restore an newly created database from a backup stored in an S3 bucket. 

The AssociatedRoles element is supported through CloudFormation (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html#cfn-rds-dbinstance-associatedroles). At the same there is no way to use this functionality with DatabaseInstance construct. 

Please consider adding this capability in  CDK API.

### Environment

  - **CDK CLI Version:** 1.12.0 (build 923055e)
  - **Module Version:** aws-cdk.aws-rds (1.10.0)
  - **OS:** Windows 10
  - **Language:** Python

**Comment by njlynch** [comment]
We have handled this in the `DatabaseCluster` construct via the `s3ImportRole`, `s3ImportBucket`, `s3ExportRole`, and `s3ExportRole` properties:
https://github.com/aws/aws-cdk/blob/3c116f3b5854726bef610e425fc35f2d2b50a179/packages/@aws-cdk/aws-rds/lib/cluster.ts#L175-L235

According to the [documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-dbcluster-dbclusterrole.html), we should populate both the role and the `FeatureName` associated with the role. This is the same for DB instance roles: [docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-dbinstance-dbinstancerole.html). However, we are currently only populating the `roleArn`, and not the `featureName`:

https://github.com/aws/aws-cdk/blob/3c116f3b5854726bef610e425fc35f2d2b50a179/packages/@aws-cdk/aws-rds/lib/cluster.ts#L409-L414

The features supported vary by engine-to-engine, and within the engines version-to-version. As of today, the only relevant features do appear to be the S3 import/export (which itself is only available on a limited set of engines), so most likely copying the cluster implementation should work (for now). Further investigation is required to understand if omitting the featureName from the role renders the functionality broken or not.

**Comment by shivlaks** [comment]
@njlynch Omitting the `featureName` from the role does result in a deploy-time failure with a message that looks like

> The feature-name parameter must be provided with the current operation
