### ISSUE TITLE
Update/Refresh API gateway bodyS3Location

### ISSUE THREAD

**Issue by cheelav** [aws/aws-cdk#4421]
I have created API gateway and importing swagger doc with bodyS3Location property. Not able to refresh gateway after uploading new swagger docs.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by NGL321** [comment]
Hi @cheelav,

I'm not really sure what you are asking. If you would like to request a feature, please describe the feature you want, why you want it, and how you think it could be implemented.

It really looks like you are trying to figure out how a system works. My recommendation is to look at our [Gitter](https://gitter.im/awslabs/aws-cdk) room or StackOverflow. However, if you would like to get an answer here, please provide more information on your issue.

**Comment by cheelav** [comment]
Noah,

I am creating apigateway and uploading swagger doc with bodyS3Location.
After initial creation, I want to refresh/update gateway with latest
swagger docs. I did not find any method to do that.
I have looked at CfnRestApi and RestApi.  Attaching typescript here.

Thanks
Vasantha

**Comment by NGL321** [comment]
Hey @cheelav were you going to post some ts? I can certainly look into this more, but I would need to see some code to really understand what you mean

**Comment by cheelav** [comment]
import cdk = require('@aws-cdk/core');
import apigw = require('@aws-cdk/aws-apigateway');
import { EndpointType } from '@aws-cdk/aws-apigateway';
import iam = require('@aws-cdk/aws-iam');
import { PolicyStatement, PolicyDocument } from '@aws-cdk/aws-iam';

export class ApiCdkStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);



    const api = new apigw.RestApi(this, 'AuthApi', {
      restApiName: 'AuthApi',
      endpointTypes: [EndpointType.REGIONAL],
      parameters: {
        endpointConfigurationTypes: EndpointType.REGIONAL
      }
    });

    api.root.addMethod('ANY');
    //const cfnApi = api.node.findChild('Default') as apigw.CfnRestApi;
    const cfnApi = api.node.defaultChild as apigw.CfnRestApi;

 
    cfnApi.parameters = {
      endpointConfigurationTypes: EndpointType.REGIONAL,
      ignore: 'documentation'
    }

    cfnApi.endpointConfiguration = {
      types: [EndpointType.REGIONAL]
    };

    cfnApi.bodyS3Location = {
      bucket: 'swagger-bucket',
      key: 'Test-AWS-APIGateway.postman_collection.json-Swagger'
    }

  }
}
