### ISSUE TITLE
Document how to use imported VPC and associated resources

### ISSUE THREAD

**Issue by shakerky** [aws/aws-cdk#4424]
It would be good to document (and some examples would be great too) in one place how to use imported VPCs. Like many others, we don't work in isolation and have already created VPCs in place which we need to import values from.

e.g.: 

From what I've gathered you should be able to use this in a lot of places (e.g. ApplicationLoadBalancer):

vpcId: cdk.Fn.importValue("VPCID")

But it fails in a lot of places and I have to hard code the vpc id. 

Also the requirement to tag resources like subnets with "aws-cdk:subnet-type". What resources require tagging and what tags and values are used and accepted.

There are lots of similar queries (this is just a sample):

https://github.com/aws/aws-cdk/issues/3649
https://github.com/aws/aws-cdk/issues/506
https://github.com/aws/aws-cdk/issues/2926
https://github.com/aws/aws-cdk/issues/3650
https://github.com/aws/aws-cdk/issues/3706

It would be good to document all these things in one place so it can be referenced.
---

This is a 📕 documentation issue

**Comment by shakerky** [comment]
Also add that all Subnets require tagging with aws-cdk:subnet-type for the look up to work. Which has cost me a few hours.

**Comment by rix0rrr** [comment]
> Also add that all Subnets require tagging with aws-cdk:subnet-type for the look up to work. Which has cost me a few hours.

This should not be true anymore. What version were you trying that on?

**Comment by rix0rrr** [comment]
If you are passing around IDs, you are working at too low a level. You should be working with `IVpc` objects.

This is the documentation about importing VPCs: https://docs.aws.amazon.com/cdk/api/latest/docs/aws-ec2-readme.html#importing-an-existing-vpc

What are you missing from this description?

**Comment by shakerky** [comment]
> > Also add that all Subnets require tagging with aws-cdk:subnet-type for the look up to work. Which has cost me a few hours.
> 
> This should not be true anymore. What version were you trying that on?

Definitely 1.12.0.

**Comment by shakerky** [comment]
> If you are passing around IDs, you are working at too low a level. You should be working with `IVpc` objects.
> 
> This is the documentation about importing VPCs: https://docs.aws.amazon.com/cdk/api/latest/docs/aws-ec2-readme.html#importing-an-existing-vpc
> 
> What are you missing from this description?

Actually that's not too bad. Could do with a bit more explanation and expasion, but that's life of the bleeding edge.

The issue is I'd like to cdk.Fn.importValue a value for the vpc, as they were created long ago, with inconsistent tagging etc. Same with the subnets and importing them. I guess this is a bigger, more general issue since I'd like to run 'cdk synth' without being logged into AWS for testing code while offline. This precludes us from doing so. I'll have a think about exactly what I'm asking for and maybe raise another ticket for it.

**Comment by rix0rrr** [comment]
>  I'd like to run 'cdk synth' without being logged into AWS 

This tells me you're not committing `cdk.context.json` to source control, or not specifying region and account on your stack. If you did, the second time you imported the VPC, you would not need AWS credentials to read the context.

**Comment by rix0rrr** [comment]
> Also add that all Subnets require tagging with aws-cdk:subnet-type for the look up to work. Which has cost me a few hours. 

> Definitely 1.12.0.

Okay. What subnet types were incorrectly recognized as what other type?

**Comment by shakerky** [comment]
This is the error I was getting:

outdir: cdk.out
env: {
  CDK_DEFAULT_REGION: 'ap-southeast-2',
  CDK_DEFAULT_ACCOUNT: '99999999',
  CDK_CONTEXT_JSON: '{"vpc-provider:account=99999999:filter.vpc-id=vpc-99999999:region=ap-southeast-2":{"$providerError":"Not all subnets in VPC have the same AZs: ap-southeast-2a,ap-southeast-2a,ap-southeast-2b,ap-southeast-2b,ap-southeast-2c,ap-southeast-2c vs ap-southeast-2a,ap-southeast-2b,ap-southeast-2c","$dontSaveContext":true},"aws:cdk:enable-path-metadata":true,"aws:cdk:enable-asset-metadata":true}',
  CDK_OUTDIR: 'cdk.out',
  CDK_CLI_ASM_VERSION: '1.10.0',
  CDK_CLI_VERSION: '1.12.0'
}
Not making progress trying to resolve environmental context. Giving up.
[Error at /CdkElbAsgStack] Not all subnets in VPC have the same AZs: ap-southeast-2a,ap-southeast-2a,ap-southeast-2b,ap-southeast-2b,ap-southeast-2c,ap-southeast-2c vs ap-southeast-2a,ap-southeast-2b,ap-southeast-2c

But I can't get it to appear again now after adding the tags and removing them again. 🤷‍♂️

**Comment by ivawzh** [comment]
Am I right that `Fn.importValue('VpcId')` and `Fn.importValue('VpcName')` will not work with `Vpc.fromLookup`? So that it will not show up properly in the stack dependency as imported value?

**Comment by maraisr** [comment]
That is correct, it errors with "no tokens" allowed. Any way to get a VPC using imported values?
