### ISSUE TITLE
Support Traffic Policy Document and related operations

### ISSUE THREAD

**Issue by geekybaiyi** [aws/aws-cdk#4426]
hi,

I'd like to implement blue/green deployment but can't use AWS CodeDeploy for internal company policy.  However I think this can be done by manipulating Route53 traffic policy. 

Will you guys consider to support model Traffic Policy as object and support related operations in CDK ? 

thx!

**Comment by SomayaB** [comment]
Hi @geekybaiyi, thanks for submitting a feature request! We will look into this and someone will update this issue when there is movement.

**Comment by dtserekhman-starz** [comment]
Hi, any movement/updates on that feature?

**Comment by alluriv** [comment]
Any update about the feature?
