### ISSUE TITLE
Beanstalk Environment redeployment fails if stack is tagged

### ISSUE THREAD

**Issue by whoiskevinrich** [aws/aws-cdk#4431]
I have a stack that deploys an application to Elastic Beanstalk. The stack will deploy initially, but will fail to redeploy giving the message: `Environment Elastic Beanstalk environment tags cannot be updated.`

### Reproduction Steps

1. Create a stack that is tagged
2. Create an elastic beanstalk application within the stack
3. Create an elastic beanstalk environment within the stack's application
4. Deploy
5. Redeploy

### Code Sample

``` ts
export class MyStack extends cdk.Stack {
  constructor(...) {

    cdk.Tag.add(this, "MyTagName", "MyTagValue");

    // set roles...

    const app = new elasticbeanstalk.CfnApplication(this, 'Application', {
      // set application properties ...
    };

    const environment = new elasticbeanstalk.CfnEnvironment(this, 'Environment', {
      // set environment properties ...
    };

    environment.addDependsOn(app);
  }
}
```

### Error Log

```
MyApp: deploying...
MyApp: creating CloudFormation changeset...
 0/3 | 3:01:52 PM | UPDATE_IN_PROGRESS   | AWS::IAM::Role                     | Role (Role********) 
 1/3 | 3:02:00 PM | UPDATE_COMPLETE      | AWS::IAM::Role                     | Role (Role********) 
 1/3 | 3:02:02 PM | UPDATE_IN_PROGRESS   | AWS::ElasticBeanstalk::Environment | Environment 
 2/3 | 3:02:03 PM | UPDATE_FAILED        | AWS::ElasticBeanstalk::Environment | Environment Elastic Beanstalk environment tags cannot be updated.
	new MyStack(/home/vsts/work/1/s/infrastructure/lib/infrastructure-stack.ts:40:25)
	\_ Object.<anonymous> (/home/vsts/work/1/s/infrastructure/bin/infrastructure.ts:7:1)
	\_ Module._compile (internal/modules/cjs/loader.js:778:30)
	\_ Module.m._compile (/home/vsts/work/1/s/infrastructure/node_modules/ts-node/src/index.ts:493:23)
	\_ Module._extensions..js (internal/modules/cjs/loader.js:789:10)
	\_ Object.require.extensions.(anonymous function) [as .ts] (/home/vsts/work/1/s/infrastructure/node_modules/ts-node/src/index.ts:496:12)
	\_ Module.load (internal/modules/cjs/loader.js:653:32)
	\_ tryModuleLoad (internal/modules/cjs/loader.js:593:12)
	\_ Function.Module._load (internal/modules/cjs/loader.js:585:3)
	\_ Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
	\_ Object.<anonymous> (/home/vsts/work/1/s/infrastructure/node_modules/ts-node/src/bin.ts:158:12)
	\_ Module._compile (internal/modules/cjs/loader.js:778:30)
	\_ Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
	\_ Module.load (internal/modules/cjs/loader.js:653:32)
	\_ tryModuleLoad (internal/modules/cjs/loader.js:593:12)
        \_ Function.Module._load (internal/modules/cjs/loader.js:585:3)
	\_ Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
	\_ findNodeScript.then.existing (/usr/local/lib/node_modules/npm/node_modules/libnpx/index.js:268:14)
 2/3 | 3:02:03 PM | UPDATE_ROLLBACK_IN_P | AWS::CloudFormation::Stack         | MyApp The following resource(s) failed to update: [Environment]. 
 3/3 | 3:02:16 PM | UPDATE_COMPLETE      | AWS::ElasticBeanstalk::Environment | Environment 
 3/3 | 3:02:16 PM | UPDATE_IN_PROGRESS   | AWS::IAM::Role                     | Role (Role********) 
 4/3 | 3:02:25 PM | UPDATE_COMPLETE      | AWS::IAM::Role                     | Role (Role********) 

 ❌  MyApp failed: Error: The stack named MyApp is in a failed state: UPDATE_ROLLBACK_COMPLETE
The stack named MyApp is in a failed state: UPDATE_ROLLBACK_COMPLETE

```

### Environment

  - **CLI Version      : AWS shell script (https://docs.aws.amazon.com/vsts/latest/userguide/awsshell.html)
  - **Framework Version: aws-cdk@1.12.0
  - **OS               : ubuntu
  - **Language         :typescript

### Other

I think this is related to [this issue](https://stackoverflow.com/a/54925308/2449105) which claims:

> "you cannot update tags without rebuilding the environment using cloudformation"

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hey @whoiskevinrich ,

thanks for opening the issue. 2 clarifying questions:

1. Did you deploy the stack at first without the tags, and then add them?
2. What is the effect you want here? Do you want the environment be tagged with `"MyTagName": "MyTagValue"`?

Thanks,
Adam

**Comment by whoiskevinrich** [comment]
1. I deployed the stack from cdk with tagging from the beginning (internal requirement; we want to always track our resources and the tags may change based on deployment-time variables)
2. Ideally, yes, the environment would be tagged as the rest of the stack. Most favorable would be the stack redeploys (with or without updated tags) without the need to tear down the application/instance.

**Comment by skinny85** [comment]
Thanks for the info. Looking at the issue you linked, I'm not sure there's much we can do here - it seems like a miss in CloudFormation :(. What you can do is remove the tags from the environment:

```ts
cdk.Tag.remove(this, "MyTagName", {
  includeResourceTypes: 'AWS::ElasticBeanstalk::Environment',
});
```

Sorry I don't have a better answer for you :(

**Comment by dhirajkhodade** [comment]
I am getting this same error while updating tags of my EB environment. 
I see the comment that issue is with CloudFormation. Where should I report it ?
