### ISSUE TITLE
ec2: add option on SecurityGroup to not add rules to them

### ISSUE THREAD

**Issue by valzam** [aws/aws-cdk#4437]
I am trying to deploy an ECS cluster + Application Load Balancer using existing VPC, Security Group and Subnet resources. 
SG1: Security group for apps
SG2: Security group for load balancers

SG1 has an existing inbound rule to allow TCP traffic on port 80 from SG2.
SG2 has existing inbound rules to allow TCP traffic on port 80 and 443 from the internet.

However, during deployment of my stack CDK wants to recreate those rules. This doesn't actually lead to any changes on the SGs. The problem arises when I destroy my stack and CDK **deletes the pre-existing rules from my SGs**, in effect rendering them useless.
![image](https://user-images.githubusercontent.com/9025786/66525508-6caa1c00-eb41-11e9-87bc-1b05a1008f0a.png)

### Reproduction Steps
Definition of existing resources
```
    let existingVPC = ec2.Vpc.fromVpcAttributes(this, "existing-vpc", {
      privateSubnetIds: config["private_subnet_ids"],
      publicSubnetIds: config["public_subnet_ids"],
      vpcId: config["vpc"],
      availabilityZones: ["us-east-1b" ,"us-east-1c"]
    })
    let existingLoadBalancerSG = ec2.SecurityGroup.fromSecurityGroupId(this, "lb-sg", config["loadbalancer_security_group"]);
    let existingAppSG = ec2.SecurityGroup.fromSecurityGroupId(this, "app-sg", config["app_security_group"]);
```

Cluster and load balancer
```
    let newCluster = new ecs.Cluster(this, "ecs-cluster", {
      clusterName: "newCluster-",
      vpc: existingVPC
    })

    let newService = new ecs.FargateService(this, "new-service", {
      cluster: newCluster,
      taskDefinition: ...,
      securityGroup: existingAppSG,
      vpcSubnets: {subnetGroupName: "Private"}
    })

    let kbLB = new lb.ApplicationLoadBalancer(this, _ID_PREFIX + "-lb", {
      vpc: existingVPC,
      loadBalancerName: "newLB",
      internetFacing: true,
      securityGroup: existingLoadBalancerSG,
    })
    let ListenerUnsecure = kbLB.addListener("lb-listener-unsecure", {
      protocol: lb.ApplicationProtocol.HTTP,
    })
    let ListenerSecure = kbLB.addListener(_"lb-listener-secure", {
      protocol: lb.ApplicationProtocol.HTTPS,
      certificateArns: [config["ssl_arn"]],
      sslPolicy: lb.SslPolicy.RECOMMENDED
    })
    kbListenerUnsecure.addTargets("ECS-UNSECURE", {
      port: 80
    }).addTarget(newService)
    kbListenerSecure.addTargets("ECS-SECURE", {
      port: 443
    }).addTarget(newService)
```

### Error Log
No error message

### Environment

  - **CLI Version: 1.12.0
  - **Framework Version: 1.12.0
  - **OS: Mac
  - **Language: Typescript
--- 

This is :bug: Bug Report

**Comment by valzam** [comment]
I have found this issue describing a similar problem
https://github.com/aws/aws-cdk/issues/3177

by setting `open: false` on the listeners I was able to get rid of the port 80/443 outbound rules on SG2.
The port 80 SG2--> SG1 rule is caused by adding a port mapping for the docker container in the ECS task (If I change it to port 1000 the rule changes to open port 1000): 

```
    kbDockerContainer.addPortMappings({
      containerPort: 80,
    })
```

**Comment by rix0rrr** [comment]
Thanks for the report. Yes, CDK will add rules to imported security groups.

Imported Roles have a flag to not modify them, Security Groups should have a similar feature.

It should be fairly simple to add if you're so inclined.

**Comment by valzam** [comment]
Hey,

thanks for your response. I found have another issue and overwriting the addIngressRule method worked for prevent CDK from creating new rules.
```
    sg.addIngressRule = () => {};
    sg.addEgressRule = () => {};
```

Presumably something like this can be done in the constructor when a mutable=false flag is passed (like you mentioned in the IAM roles). I will look into creating a PR for this.
