### ISSUE TITLE
Bucket RemovalPolicy documentation error. 

### ISSUE THREAD

**Issue by c4ruso** [aws/aws-cdk#4444]
## :question: General Issue
Documentation Error. 

### The Question
I have found a minor documentation error in 
`aws-cdk/packages/@aws-cdk/core/lib/removal-policy.ts`

The RemovalPolicy Enum states that the DESTROY value is the default but just below it in the RemovalPolicyOptions interface the default value is set to RETAIN.

I can make a quick PR to fix the documentation. But I am not sure if your intent was to have Destroy or Retain be the default value. Retain seems like the proper default to me. 

### Environment

  - **CDK CLI Version:** 1.12.0
  - **Module Version:** 
  - **OS:** all 
  - **Language:** TypeScript

**Comment by SomayaB** [comment]
Closing since this is a duplicate of #4416
