### ISSUE TITLE
run unit tests against npm tarball

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#4448]
To avoid "npmignore" mishaps like #4445 (and other previous incidents), ideally we should execute all unit tests against the npm tarball bundle and not against the source tree.

Sketch:

```bash
npm pack
mkdir temp && cd temp
tar -xzvf ../*.tgz
cd package
ln -s ../../node_modules
npm run test
```

**Comment by nija-at** [comment]
The source tree contains `.ts` files whereas the tarball doesn't and only contains the `.d.ts` and `.js`.

This sort of test would also catch errors where the declaration files or the output JS or declaration files raise errors in the absence of the `.ts` files.

**Comment by eladb** [comment]
Yes, it will run the test against the actual module we are going to publish, so it will plug this little hole we have in our coverage.

**Comment by eladb** [comment]
Since we have a single entry point for all our tests, shouldn't be too hard to add this to `cdk-test`
