### ISSUE TITLE
Nested stack deployments fail when using assets

### ISSUE THREAD

**Issue by Lightning303** [aws/aws-cdk#4451]
**[nija-at]:** Triage details here - https://github.com/aws/aws-cdk/issues/4451#issuecomment-543255809

Original issue below: 

-----
Hi,
when creating lambda functions in child stacks, the main stack will fail to deploy with a ValidationError. The order in which the stacks are deployed doesnt matter in this case. Having other ressources in the parent stack or having it empty also does not make a difference. Please see code below, which i have cut down to the bare minimum. We see this behaviour only with lambdas, other ressources in child stacks similar to this work just fine.

### Reproduction Steps

```
import cdk = require('@aws-cdk/core');
import { myStack } from './my-stack';

export class CdkLambdaStack extends cdk.Stack {
  constructor(scope: cdk.App, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const child = new myStack(this, "mystack");
    // Adding dependency to force child to be created first
    this.addDependency(child);
  }
}
```
```
import cdk = require('@aws-cdk/core');
import lambda = require('@aws-cdk/aws-lambda');
import { Runtime } from '@aws-cdk/aws-lambda';
import { Duration } from '@aws-cdk/core';

export class myStack extends cdk.Stack {
  constructor(scope: cdk.Stack, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    new lambda.Function(this, "test", {
      code: lambda.Code.asset("lambdas/test"),
      handler: "index.handler",
      runtime: Runtime.NODEJS_8_10,
      memorySize: 128,
      timeout: Duration.seconds(30)
    });
  }
}
```

### Error Log

cdk deploy *
CdkLambdaStackmystack73F24757
This deployment will make potentially sensitive changes according to your current security approval level (--require-approval broadening).
Please confirm you intend to make the following modifications:

...

Do you wish to deploy these changes (y/n)? y
CdkLambdaStackmystack73F24757: deploying...
CdkLambdaStackmystack73F24757: creating CloudFormation changeset...
...

 ✅  CdkLambdaStackmystack73F24757

Stack ARN:
arn:aws:cloudformation:eu-west-1:123456789:stack/CdkLambdaStackmystack73F24757/aabbdfd0-eb49-11e9-97dd-0234dfcdb558
CdkLambdaStack
CdkLambdaStack: deploying...
CdkLambdaStack: creating CloudFormation changeset...

 ❌  CdkLambdaStack failed: ValidationError: Parameter values specified for a template which does not require them.
Parameter values specified for a template which does not require them.

### Environment

  - **CLI Version: 1.12.0**
  - **Framework Version: 1.12.0**
  - **OS : Windows 10 Pro**
  - **Language: TypeScript**

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
I'm able to reproduce this issue (see code snippet below). Changing the `code` property to use `Code.fromInline()` doesn't generate this error, as well as, swapping out the lambda function for an SQS queue.

So, my guess is that this has something to do with stack nesting and assets.

Note: I've tested this on 1.13.0 which has the new nested stacks implementation.

Tagging this with CloudFormation and assets instead of lambda.

----

```typescript
import cdk = require('@aws-cdk/core');
import lambda = require('@aws-cdk/aws-lambda');

class CdkLambdaStack extends cdk.Stack {
  constructor(scope: cdk.App, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const child = new myStack(this, 'mystack');
    // Adding dependency to force child to be created first
    this.addDependency(child);
  }
}

class myStack extends cdk.Stack {
  constructor(scope: cdk.Stack, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    new lambda.Function(this, 'myfunction', {
      code: lambda.Code.fromInline('xx'),
      // code: lambda.Code.asset('resources'),
      handler: 'index.handler',
      runtime: lambda.Runtime.NODEJS_8_10,
      memorySize: 128,
      timeout: cdk.Duration.seconds(30)
    });
  }
}

const app = new cdk.App();
new CdkLambdaStack(app, 'mylambdastack')
app.synth();
```

```shell
$ cdk deploy \*
mylambdastackmystack9C53D615: deploying...
Updated: asset.8322f7aa7f51997ac751ff5889660ed764d3cd7a6fb19c02bca9413499e94090 (zip)
mylambdastackmystack9C53D615: creating CloudFormation changeset...

...
...
...

 ✅  mylambdastackmystack9C53D615

Stack ARN:
arn:aws:cloudformation:eu-west-1:664773442901:stack/mylambdastackmystack9C53D615/502e31a0-f0f1-11e9-ba7f-0a31ba4141ec
mylambdastack
mylambdastack: deploying...
mylambdastack: creating CloudFormation changeset...

 ❌  mylambdastack failed: ValidationError: Parameter values specified for a template which does not require them.
Parameter values specified for a template which does not require them.
```

**Comment by eladb** [comment]
This is fixed by https://github.com/aws/aws-cdk/pull/4540
