### ISSUE TITLE
AttributeError: 'FargateService' object has no attribute 'cloud_map_service'

### ISSUE THREAD

**Issue by mostafafarzane** [aws/aws-cdk#4452]
When calling "cloud_map_service" attribute on fargate service, this error occurs on "cdk ls".

**Comment by SomayaB** [comment]
Hi @mostafafarzane, we need more information to understand the issue better. Can you please fill out our [issue template](https://github.com/aws/aws-cdk/issues/new?labels=bug%2C+status%2Fneeds-triage&template=bug.md) here. Thank you!

**Comment by SomayaB** [comment]
Closing for now, but feel free to reopen.
