### ISSUE TITLE
Feature: EventBridge Resources

### ISSUE THREAD

**Issue by dehli** [aws/aws-cdk#4455]
With the release of event bus in CloudFormation ([Announcement](https://aws.amazon.com/about-aws/whats-new/2019/10/amazon-eventbridge-supports-aws-cloudformation/)) we can create an `EventBus` resource and also update the `Rule` resource to optionally have an `EventBus` passed in. 

### Use Case

Want to use the new EventBridge resources. 

### Proposed Solution

Currently working on a solution following other resources as an example.

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

#### Status

* [x] L2 `EventBus` construct (merged bbec8c5c3995b9400cfd6ad0d7a71e8f8646a3b9)
* [x] Add `eventBusName` to `Rule` construct (PR #4839)
---

This is a :rocket: Feature Request

**Comment by NGL321** [comment]
Hey @dehli,

Once the Cloudformation Team adds the functionality for EventBridge into their [Resource Specification](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html), the CDK should automatically update with a new L1 construct.

Unfortunately, we have no control over when this happens. If you would like more information, I would reach out to the Cloudformation team in their [forum](https://forums.aws.amazon.com/forum.jspa?forumID=92). Otherwise, I will update this issue when we have more information on timeline.

😸

**Comment by dehli** [comment]
Thanks @NGL321! I started to build the L2? construct and then realized the specification hadn't been updated to include an `AWS::Events::EventBus` so I didn't get too far. 😄 Cheers!

**Comment by ali-habibzadeh** [comment]
Really looking forward to getting this too 👍

**Comment by aripalo** [comment]
If I understood correctly, it seems that the EventBridge is now in the Resource Specification:
![Screenshot 2019-11-02 at 17 24 39](https://user-images.githubusercontent.com/679146/68073150-ad3e3380-fd95-11e9-87b1-d7cdd69692bb.png)

**Comment by dehli** [comment]
Yep! @aripalo This was merged in here: bbec8c5c3995b9400cfd6ad0d7a71e8f8646a3b9 

We're still waiting on the `AWS::Events::Rule` resource to allow you to specify an `EventBusName` for this feature to be complete.

**Comment by dehli** [comment]
With #4839 being merged in, this has been completed. I'll go ahead and close the issue!

**Comment by 0xdevalias** [comment]
Ended up here from Google, it's kind of confusing that all of the doco talks about CloudWatch Events, yet the service is called EventBridge. Did this get rebranded or something? Should the doco be updated to better match the current reality?

- https://docs.aws.amazon.com/cdk/api/latest/docs/aws-events-readme.html
  - > Amazon CloudWatch Events Construct Library
- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_Events.html
  - > Amazon EventBridge Resource Type Reference
