### ISSUE TITLE
 Encountered unsupported property PolicyName

### ISSUE THREAD

**Issue by nikhilbhoj** [aws/aws-cdk#4464]
So, I have created below Aspect to replace all the created Inline policy to Managed policy 

``` ts
export class modifyInlinePolicy implements cdk.IAspect {
  constructor() {}

  public visit(node: cdk.IConstruct): void {
    if (!(node instanceof iam.Policy)) {
      return;
    }
    const policyresource =  node.node.findChild('Resource') as iam.CfnPolicy;

    if (policyresource === undefined) {
      return;
    }
 
 
 policyresource.addOverride("Type","AWS::IAM::ManagedPolicy");


    }
}
```

And then applied this aspect to my stack
```root.node.applyAspect(new modifyInlinePolicy());```

### Environment

  - **CLI Version      :** 1.12
  - **Framework Version:**  1.12
  - **OS               :** Ubuntu
  - **Language         :** Typescript

### Other

--- 

This is :bug: Bug Report

**Comment by SomayaB** [comment]
Hi @nikhilbhoj, thanks for submitting a bug report. Could you describe the bug more in detail so that we can understand what the issue is better. Reproduction steps and an error log would be really helpful. Thanks!

**Comment by nikhilbhoj** [comment]
Hi @SomayaB 

I am developing CI/CD stack based on the below example from AWS CDK examples

https://docs.aws.amazon.com/cdk/latest/guide/codepipeline_example.html

However, in our Organization we cannot use Inline policies we have to use Managed policies which is CDK generates, so what I have done is use to use Escapse Hatches and Apply Asects to whole stack and convert  the "Type": "AWS::IAM::Policy" to "Type": "AWS::IAM::ManagedPolicy" using this wrapper code.

export class modifyInlinePolicy implements cdk.IAspect {
  constructor() {}

  public visit(node: cdk.IConstruct): void {
    if (!(node instanceof iam.Policy)) {
      return;
    }
    const policyresource =  node.node.findChild('Resource') as iam.CfnPolicy;

    if (policyresource === undefined) {
      return;
    }
 
 
 policyresource.addOverride("Type","AWS::IAM::ManagedPolicy");


    }
}

And then applied this aspect to my stack
root.node.applyAspect(new modifyInlinePolicy());


The AWS example works fine in a normal AWS account but the one which I have modified is not working, while to program complies fine and generates stack on cdk synth.
cdk synth
Successfully synthesized to /home/cicdlambdacdk/cdk.out
Supply a stack name (CicdlambdacdkStack, LambdaStack) to display its template.

Here is the error

**Comment by nikhilbhoj** [comment]
9/27 | 5:54:15 AM | CREATE_COMPLETE      | AWS::IAM::Role              | Pipeline/Build/Lambda_Build/CodePipelineActionRole (PipelineBuildLambdaBuildCodePipelineActionRole2DAE39E9)
 10/27 | 5:54:16 AM | CREATE_COMPLETE      | AWS::IAM::Role              | Pipeline/EventsRole (PipelineEventsRole46BEEA7C)
 11/27 | 5:54:17 AM | CREATE_FAILED        | AWS::IAM::ManagedPolicy     | Pipeline/Deploy/Lambda_CFN_Deploy/Role/DefaultPolicy (PipelineDeployLambdaCFNDeployRoleDefaultPolicyE83FD793) Encountered unsupported property PolicyName

**Comment by nikhilbhoj** [comment]
If you want I can paste the whole template files, both with or without Escape Hatchet and applied one.

**Comment by nikhilbhoj** [comment]
I was able to solve this issue by adding other missing properties filed.

Namely Path, description
