### ISSUE TITLE
No support for .net standard ?

### ISSUE THREAD

**Issue by LechuckThePirate** [aws/aws-cdk#4471]
## :question: General Issue

I'm creating some libraries for CDK, but I can't use "netstandard2.0" since all CDK libs need "netcoreapp2.1" ... is this by design? or will this packages be released for "netstandard2.0" when the final CDK for .NET is released?

**Comment by McDoit** [comment]
I think it will remain a netcoreapp, at least according to this JSII issue:
https://github.com/aws/jsii/issues/714

**Comment by NGL321** [comment]
Hey @LechuckThePirate,

@McDoit is correct. The CDK is written in Typescript. Other languages are supported with [JSII](https://github.com/aws/jsii) (creates bindings between a typescript API in other languages). Currently JSII only has bindings built for .NET Core.

.NET Standard encompasses both .NET Core and .NET Framework (which I imagine you are referring to). We do not have any plans to support .NET Framework for now.

I'm sorry to disappoint, but let me know if you have any other questions!
😸

**Comment by NGL321** [comment]
Closing for now. If you need further discussion, feel free to reopen.
