### ISSUE TITLE
Add VPCZoneIdentifiers to CommonAutoScaleGroupProps

### ISSUE THREAD

**Issue by hertzknight** [aws/aws-cdk#4472]
Add in the ability to choose which subnets the AutoScaleGroup is allowed to uses. 

### Use Case

This allows users to choose what subnets the instance is built on. When using DockerVolumes/EBS Volumes, you have to be in the same Availability Zone of said EBS Volume. We would prefer to choose what subnet ID to use instead.

### Proposed Solution

A workaround I created.
``` ts
const vpc = ec2.Vpc.fromLookup(this,'VPC',{
        vpcId: vpcId
      });
    const vpcASG = ec2.Vpc.fromVpcAttributes(this,'VPCASG',{
        vpcId: vpcId,
        availabilityZones: [vpc.availabilityZones[0]],
        privateSubnetIds: [vpc.privateSubnets[0].subnetId],
        privateSubnetRouteTableIds: [vpc.privateSubnets[0].routeTable.routeTableId]
    });
    const autoScaleGroup = new autoscaling.AutoScalingGroup(this,"AutoScalingGroup",{
      vpc: vpcASG,
      instanceType: instanceType,
      machineImage: new ecs.EcsOptimizedAmi(),
      updateType: autoscaling.UpdateType.ROLLING_UPDATE,
      desiredCapacity:1,
      allowAllOutbound: true,
      });
```

My recommendation would be to add VPCZoneIdentifier to CommonAutoScalingGroupProps as shown in [CloudFormation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-group.html).

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by konstantinj** [comment]
One way would be to define your own `selectSubnets` function. Unfortunately `ec2.Vpc.fromLookup` is returning a new vpc object from `ImportedVpc`. This one is not exported which makes it impossible to overwrite it with prototype. e.g.

```typescript
ec2.Vpc.prototype.selectSubnets = function (selection?: SubnetSelection): SelectedSubnets {
            let subnets: Array<ISubnet> = []
            for (const subnet of subnets) {
                subnets.push(subnet)
                break
            }
            return {
                subnetIds: subnets.map(s => s.subnetId),
                availabilityZones: subnets.map(s => s.availabilityZone),
                internetConnectivityEstablished: false,
                subnets: subnets,
                hasPublic: false
            };
        }
```

So please except a list of subnets here or make it possible to extend the `SubnetSelection` Interface so we can apply custom filters there which would be even better since `SubnetSelection` is used in a lot of places in cdk.

**Comment by rix0rrr** [comment]
It's possible to specify individual subnet objects on a `SubnetSelection` object now. Does that solve your issue? https://github.com/aws/aws-cdk/blob/44ed2e6303e1065faa93c86edb14b9ba1233de6a/packages/%40aws-cdk/aws-ec2/lib/vpc.ts#L233

**Comment by SomayaB** [comment]
Closing for now since there hasn't been a response in a while. Feel free to reopen.
