### ISSUE TITLE
Validation check: TaskDefinition.proxyConfiguration requires network mode AWSVPC

### ISSUE THREAD

**Issue by nathanpeck** [aws/aws-cdk#4476]
The task definition construct should perform an additional validation check. If the user passes a proxyConfiguration it should ensure that the user is also using the right network mode.

### Use Case

Without this validation the template with synthesize but will error out during CloudFormation template deploy with error:

```
name-task-definition (nametaskdefinition690762BB) APPMESH proxy configuration is only supported in networkMode=awsvpc (Service: AmazonECS; Status Code: 400; Error Code: ClientException; Request ID: 5f8fca57-61ef-4b40-8b9c-3ba62f8a651c)
```

### Proposed Solution

A simple validation at synthesis time to add some guard rails to save people time from their own misconfigurations.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by nmussy** [comment]
This looks fairly straightforward to implement, I'll make a PR for it.

I can't find any documentation mentioning this restriction though, should this be addressed internally?

**Comment by iamhopaul123** [comment]
@nmussy Thanks for contributing. It is the documentation that is outdated. Should be addressed there. Also in the console if you don't use the awsvpc network mode, proxyConfiguration won't show up.
