### ISSUE TITLE
Can't get the "command" for a CfnJob to work properly

### ISSUE THREAD

**Issue by joebowen** [aws/aws-cdk#4480]
Here's the code:

        aws_glue.CfnJob(
            scope=self,
            id=modname,
            command={
                'name': 'glueetl',
                'python_version': '3',
                'script_location': 's3://shaw-stc-edl-etl-config-playpen/test/glue/spark/__main__.py'
            },
            role=etl_role.role_arn,
            default_arguments={
                '--enable-glue-datacatalog': ''
            },
            allocated_capacity=10,
            description='Test Spark Glue ETL',
            glue_version='1.0',
            max_capacity=10,
            max_retries=0,
            number_of_workers=1,
            timeout=2880,
            worker_type='Standard'
        )

Here's what it generates:

      testgluesparkcdkBF0B19BD:
        Type: AWS::Glue::Job
        Properties:
          Command:
            Name: glueetl
          Role:
            Fn::GetAtt:
              - AWSGlueETLServiceRoleD61B5F38
              - Arn
          AllocatedCapacity: 10
          DefaultArguments:
            --enable-glue-datacatalog: ""
          Description: Test Spark Glue ETL
          GlueVersion: "1.0"
          MaxCapacity: 10
          MaxRetries: 0
          NumberOfWorkers: 1
          Timeout: 2880
          WorkerType: Standard
        Metadata:
          aws:cdk:path: ebd-glue-etl/test.glue.spark.cdk/test.glue.spark.cdk

Why is the 'PythonVersion' and 'ScriptLocation' missing?

Thank you,

Joe Bowen

**Comment by joebowen** [comment]
So I have no idea where this would be in the current codebase but from my local python cdk libraries, there's a file: python3.6/site-packages/aws_cdk/aws_glue/__init__.py line 2482

`    @jsii.data_type(jsii_type="@aws-cdk/aws-glue.CfnJob.JobCommandProperty", jsii_struct_bases=[], name_mapping={'name': 'name', 'python_version': 'pythonVersion', 'script_location': 'scriptLocation'})
`

I'm wondering if the problem is that it's not 'pythonVersion', it's 'PythonVersion'.  Same with 'scriptLocation', which should be 'ScriptLocation'.

Not sure where that would translate back into this codebase though.

**Comment by joebowen** [comment]
Turns out it needs to be like this, no clue why though... poorly documented:

        aws_glue.CfnJob(
            scope=self,
            id=modname,
            command=aws_glue.CfnJob.JobCommandProperty(
                name='glueetl',
                python_version='3',
                script_location='s3://shaw-stc-edl-etl-config-playpen/test/glue/spark/__main__.py'
            ),
            role=etl_role.role_arn,
            default_arguments={
                '--enable-glue-datacatalog': ''
            },
            allocated_capacity=10,
            description='Test Spark Glue ETL',
            glue_version='1.0',
            max_capacity=10,
            max_retries=0,
            number_of_workers=1,
            timeout=2880,
            worker_type='Standard'
        )

**Comment by husainzl** [comment]
Super-helpful @joebowen ! Thanks so much.
