### ISSUE TITLE
Support Lerna --scope Filter During Build

### ISSUE THREAD

**Issue by jd-carroll** [aws/aws-cdk#4484]
The build script should support the [lerna `--scope`](https://github.com/lerna/lerna/tree/master/core/filter-options#--scope-glob) parameter.

### Use Case
Will allow for quicker builds during development

### Proposed Solution
Expose the `--scope` parameter

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by nmussy** [comment]
You currently already have the [`../../../scripts/buildup` script](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md#partial-build-tools)

**Comment by jd-carroll** [comment]
Shucks, I definitely missed that, thank you

**Comment by nmussy** [comment]
No problem, it's definitely not the most visible command for how useful it is 😄

**Comment by jd-carroll** [comment]
@nmussy - Actually, I think I may re-open the PR and change the signature of the `build.sh` script to:
```
Usage: build.sh [--no-bail] [--force|-f] [--skip-test] [--scope <project-name> [--up] [--down]]
```

This way, there is one centralized script and you don't have to `cd` into a directory to run the build.  You can build any project from the root.

Thoughts?

This would replace the functionality of the following scripts:
* scripts/buildup
* scripts/builddown
* scripts/current-scope

**Comment by nmussy** [comment]
I don't really mind `cd`-ing into a specific package to build it, but feel free to re-open it to discuss this with the AWS team 👍

**Comment by jd-carroll** [comment]
Reopening as I think incorporating the `buildup` / `builddown` into the regular build script provides value

**Comment by SomayaB** [comment]
Hi @jd-carroll, thanks for submitting and opening a PR, much appreciated! 👍
