### ISSUE TITLE
Nested stacks cause `cdk deploy` to always have changes

### ISSUE THREAD

**Issue by nakedible** [aws/aws-cdk#4488]
Using nested stacks causes `cdk deploy` to always detect changes and to always run an update.  If there is even one nested stack, `cdk deploy` will never report "no changes" again.

This is most likely an underlying CloudFormation issue, as it happens with nested stacks in general, but you might have insider access to see if there is any way to go around it - for example if using `versionId` on template URLs might help. In any case, you should be aware of it, and perhaps note it in the documentation.

### Reproduction Steps

- Create stack utilizing `cfn.NestedStack`
- Run `npx cdk deploy`
- Run `npx cdk deploy` again and note that there are changes to apply

### Environment

  - **CLI Version      :** 1.12.0
  - **Framework Version:** 1.12.0
  - **OS               :** Linux
  - **Language         :** TypeScript

### Other

Considering CloudFormation currently supports "Dynamic References", even if the template is 100% exactly the same, the result might be some changes. This is probably why every nested stack needs to be updated even when there really is nothing to be updated.

--- 

This is :bug: Bug Report

**Comment by eladb** [comment]
This is no longer the case. The CLI will now update only if the nested stacks changed.

**Comment by erik-telesoftas** [comment]
Not sure how it was tested to be fixed, but in our case we still see nested stacks being updated each time we execute `cdk deploy` even when `cdk diff` reports no differences.
We are running on version `1.31.0` both CDK cli (Ubuntu Linux) and libraries (Java).

**Comment by AleksandarGT** [comment]
Almost always cdk reports that our nested stacks have been changed when we run cdk diff because the TemplateUrl hash changes for some reason.

> [~] AWS::CloudFormation::Stack StatefulNestedStack.NestedStack/StatefulNestedStack.NestedStackResource StatefulNestedStackNestedStackStatefulNestedStackNestedStackResource796B8306
 └─ [~] TemplateURL
     └─ [~] .Fn::Join:
         └─ @@ -5,6 +5,6 @@
            [ ]     {
            [ ]       "Ref": "AWS::URLSuffix"
            [ ]     },
            [-]     "/cdk-hnb659fds-assets-089113790002-eu-central-1/a431156dd28f358fadba60d941e2eb5b76e276d93ba5aad5a8e06f05bcb0b676.json"
            [+]     "/cdk-hnb659fds-assets-089113790002-eu-central-1/aa3000d204227a8fad8db9cf2ac08ca6b5764f7cfd09e24652ee415a0e9d08fe.json"
            [ ]   ]
            [ ] ]
