### ISSUE TITLE
Using LogGroup.fromLogGroupArn creates log group name with invalid characters

### ISSUE THREAD

**Issue by valzam** [aws/aws-cdk#4492]
When creating a log group from ARN the logGroupName property includes the wildcard character. This leads to an error when using the log group in a log driver:

```
Log driver awslogs option 'awslogs-group' contains invalid characters. (Service: AmazonECS; Status Code: 400; Error Code: ClientException;
```

Including the wildcard is necessary for the creation of valid IAM policies down the line (e.g. for an ECS Container that needs to log to that log group)

### Reproduction Steps
```
const lg = logs.LogGroup.fromLogGroupArn(this, "test-log-group", `arn:aws:logs:us-east-1:${current_deployment_env}:log-group:awslogs-test-lg:*`)

console.log(lg.logGroupName) --> awslogs-test-lg:*
```

### Environment

  - **CLI Version      : 1.12.0
  - **Framework Version: 1.12.0
  - **OS               :Mac
  - **Language         :Typescript

--- 

This is :bug: Bug Report

**Comment by jordanst3wart** [comment]
The error appears to be here:
https://github.com/aws/aws-cdk/blob/0528355789acea06be5ef46c5fab58a3116f20eb/packages/%40aws-cdk/aws-logs/lib/log-group.ts#L313

**Comment by rix0rrr** [comment]
As mentioned in PR, closing issue until user encounters it again.
