### ISSUE TITLE
Cognito: enabledMfas missing from generated CfnUserPool Cloudformation resource

### ISSUE THREAD

**Issue by plumdog** [aws/aws-cdk#4494]
A `UserPool` has an `enabledMfas` attribute in Cloudformation. See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpool.html#cfn-cognito-userpool-enabledmfas
But this is not exposed in the `UserPool` or `CfnUserPool` classes. Further, there seems to be no way of override this (because the underlying resource doesn't know about the attribute, the CDK never puts it into the Cloudformation).

a) why is `enabledMfas` missing from the generated resources, even though it does appear in https://d1uauaxba7bl26.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json? (This could be because it was only added to Cloudformation since the last build, I'm not sure whether the Cloudformation spec has dated versions anywhere)
b) is there a way of forcing the `Cfn*` resources to include an attribute that they don't know about?

### Reproduction Steps

```
$ npm install '@aws-cdk/aws-cognito'
$ grep -i 'enabledmfas' node_modules/@aws-cdk/aws-cognito/lib/*
```
(finds nothing)

### Environment

  - **CLI Version      : 1.12.0**
  - **Language         : Javascript**

**Comment by nmussy** [comment]
This was recently added to CloudFormation, and should ship with the next version: [cfnspec@6.3.0](https://github.com/aws/aws-cdk/blob/761b7d399d70e730552be1355d1c69fa1787fb87/packages/%40aws-cdk/cfnspec/CHANGELOG.md#cloudformation-resource-specification-v630)

**Comment by plumdog** [comment]
@nmussy understood and many thanks.

**Comment by nmussy** [comment]
My pleasure!
