### ISSUE TITLE
Add Glue Partition construct

### ISSUE THREAD

**Issue by joekiller** [aws/aws-cdk#4496]
Create a top level construct in aws-cdk_aws-glue for Partition. The only way to add or remove partitions from a table right now is via a Table constructor. See [partitions](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-glue-readme.html#partitions) in the documentation.

[Database](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-glue.Database.html) and [Table](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-glue.Table.html) both exist but Partition is missing.

### Use Case

A glue table could be shared across several systems where each one provides its own partition. For example partitioning off of a version number. With the top level construct I could use `fromDatabaseArn` and `fromTableArn` to construct partitions.

### Proposed Solution
Make a Glue.Partition top level construct.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by skinny85** [comment]
Hey @joekiller ,

thanks for opening the issue. Can you be a little more specific what is the ask here? Maybe with some code examples?

Thanks,
Adam

**Comment by joekiller** [comment]
I think what I really want is a "glue.Partition" Construct. I've updated the issue.

**Comment by joekiller** [comment]
I'm just using old fashioned [glue.CfnPartition](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-glue.CfnPartition.html) for now.
