### ISSUE TITLE
Add Developer Guide information on deletion/removal policies between CloudFormation and CDK

### ISSUE THREAD

**Issue by fulghum** [aws/aws-cdk#4497]

**Comment by 0xdevalias** [comment]
If i'm not mistaken, https://github.com/aws/aws-cdk/issues/1637#issuecomment-510662863 seems to show an example of how to do this:
```
import cdk = require('@aws-cdk/core');

const resource = bucket.node.findChild('Resource') as cdk.CfnResource;
resource.applyRemovalPolicy(cdk.RemovalPolicy.DESTROY);
```

**Comment by Jerry-AWS** [comment]
Added to Resources topic

**Comment by 0xdevalias** [comment]
> Added to Resources topic

Able to link to it by chance?

**Comment by Jerry-AWS** [comment]
https://docs.aws.amazon.com/cdk/latest/guide/resources.html#resources_removal
