### ISSUE TITLE
Support for service name for queue processing ECS services

### ISSUE THREAD

**Issue by pkspks** [aws/aws-cdk#4504]
`QueueProcessingEc2Service` and `QueueProcessingFargateService` don't support providing service name when constructing the services.

### Use Case

Service names provide visual sorting and filtering when dealing with a large number of services in a cluster.

### Proposed Solution
Add optional `serviceName: String` in `QueueProcessingServiceBaseProps.ts` and use it when creating services in `QueueProcessingEc2Service.ts` and `QueueProcessingFargateService.ts`

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by SomayaB** [comment]
Hi @pkspks, thanks for submitting a feature request and opening a PR, much appreciated! 👍
