### ISSUE TITLE
Naming conventions for importing existing AWS resources

### ISSUE THREAD

**Issue by KingOfPoptart** [aws/aws-cdk#4523]
## :question: General Issue

The naming conventions for importing existing resources is inconsistent across CDK.  These calls should be standardized so its easier for users to use this functionality.

### The Question

For example - to import an existing ALB, the call is 

```
const alb = elbv2.ApplicationLoadBalancer.fromApplicationLoadBalancerAttributes(this, "importedALB", props.albImportProps);
```

But to import an ApplicationTargetGroup, the call is:

```
const tg = elbv2.ApplicationTargetGroup.import(this, 'anotherTarget', props.tgImportProps);
```

Should this be standardized to just `import()` for all modules?  Should this be standardized to `from[nameOfResource]Attributes()`?

### Environment

  - **CDK CLI Version:** 1.12.0 (build 923055e)
  - **Module Version:** 1.12.0 (build 923055e)
  - **OS:** all
  - **Language:** TypeScript

**Comment by SomayaB** [comment]
Hi @KingOfPoptart, thanks for bringing this up, I think that's a fair ask. However, it seems like a pretty involved fix and one that will incur breaking changes so it might take a while to be implemented. Someone will update this issue when there is movement.

**Comment by mitchlloyd** [comment]
How about deprecating the old method name (`import`) and adding a new name like `elbv2.ApplicationTargetGroup.fromAttributes` to avoid a breaking change?

**Comment by eladb** [comment]
This has been standardized to "fromXxx"
