### ISSUE TITLE
Adding additional props to existing resource is not generating changes

### ISSUE THREAD

**Issue by albertogg** [aws/aws-cdk#4524]
Hello, I'm trying to add or remove additional properties to an already created resource and not getting any changes in the diff and or the synth. This resource was previously created using the CDK. I've tested the behavior in different resources and got the same result. I might have missed something.

### Reproduction Steps

I've created a function using this code:
```
    const lambdaFn = new lambda.Function(this, 'Function', {
      code: new lambda.AssetCode('src'),
      handler: 'index.handler',
      timeout: cdk.Duration.seconds(timeOut),
      runtime: lambda.Runtime.NODEJS_8_10,
      logRetention: logs.RetentionDays.ONE_WEEK,
    });
```

Everything worked out, but when I tried to add a description or remove the logRetention the synth didn't reflect the change. Same happened with a CloudWatch event resource.

### Environment

  - **CLI Version      :** 1.13.0
  - **Framework Version:** 1.13.0
  - **OS               :** macOS 10.14.6
  - **Language         :** TypeScript

--- 

This is :bug: Bug Report

**Comment by albertogg** [comment]
I keep forgetting to build 🤦‍♂ maybe the synth or diff should build by default?

**Comment by Jerry-AWS** [comment]
@albertogg Have you tried `npm run watch`?

**Comment by albertogg** [comment]
yes @Jerry-AWS, but I keep forgetting that I need to use two different CLIs (cdk and npm) to get the job done.

Thanks
