### ISSUE TITLE
cdk bootstrap tags option should be optional, Related to #4227

### ISSUE THREAD

**Issue by selvathiruarul** [aws/aws-cdk#4526]
CDK bootstrap tags options included as part of #4227 should be optional

Throws error `Cannot read property 'split' of undefined` for default of `undefined`

@shivlaks

**Comment by selvathiruarul** [comment]
@shivlaks  missed this in the integration test since I added tags to both, I'll change this and send a fix

**Comment by shivlaks** [comment]
@selvathiruarul - no worries, I addressed this through #4519
I don't think any further action is necessary

**Comment by selvathiruarul** [comment]
@shivlaks  Thanks
