### ISSUE TITLE
support setting environment variables on aws codebuild jobs from codepipline

### ISSUE THREAD

**Issue by rvdwijngaard** [aws/aws-cdk#4531]
Support environment variables for aws codebuild jobs from codepipeline. 
https://aws.amazon.com/about-aws/whats-new/2019/10/aws-codepipeline-enables-setting-environment-variables-on-aws-codebuild-build-jobs/

### Use Case

Reusing codebuild projects

### Proposed Solution

extend @aws-cdk/aws-codepipeline-actions

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by skinny85** [comment]
Already in PR in #4502 :)
