### ISSUE TITLE
Allow constructs for non-AWS cloud services

### ISSUE THREAD

**Issue by ronkorving** [aws/aws-cdk#4534]
Allow a mechanism to develop constructs to provision non-AWS cloud services.

### Use Case

There are plenty of very useful services out there, that we integrate with our AWS stack. Currently that tends to happen manually, or via API. I think Terraform can probably allow for this kind of integration via infrastructure-as-code.

It would be awesome if other companies (think Datadog, Splunk, SumoLogic, MongoDB Atlas, etc) could write constructs for their solutions, that make integration with AWS a breeze.

### Proposed Solution

I imagine if a construct exposes create/update/replace/destroy APIs and a mechanism for diff calculation and logging one could get pretty far. I'm sure the interface for that already exists for CloudFormation itself.

### Other

I do have to wonder whether it may be more ideal if custom resources would be used as a mechanism for this. If that is the case, I would love to see some great examples of that with a 3rd party service ([possibly related](https://github.com/awsdocs/aws-cdk-guide/issues/51)).

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by eladb** [comment]
This is already supported by [custom resources](https://docs.aws.amazon.com/cdk/api/latest/docs/custom-resources-readme.html)
