### ISSUE TITLE
EKS deployment does not set a correct userarn into the mapUsers by `awsAuth.addUserMapping`

### ISSUE THREAD

**Issue by lemonlatte** [aws/aws-cdk#4545]
I use cdk to manage aws-auth for my EKS deployment. When I try to add existing user by `addUserMapping`, it appends the stack region into the `userarn`. This makes me not able to access the cluster because of unauthorized error.

### Reproduction Steps

Here is my cdk scripts in typescript
```
    const cluster = new eks.Cluster(this, 'test-eks', {
      defaultCapacity: 0,
      defaultCapacityInstance: new ec2.InstanceType('t3.micro')
    });

    cluster.awsAuth.addUserMapping(iam.User.fromUserName(this, 'jim', 'jim'), {
      groups: ["system:masters"],
      username: "jim"
    });
```

The result of configmap `aws-auth`

```
data:
  mapUsers: '[{"userarn":"arn:aws:iam:ap-northeast-2:000000000000:user/jim","username":"jim","groups":["system:masters"]}]'
                                      ^^^^^^^^^^^^^^
```

Expected result

```
data:
  mapUsers: '[{"userarn":"arn:aws:iam::000000000000:user/jim","username":"jim","groups":["system:masters"]}]'
```

### Error Log

No compile error.

### Environment

  - **CLI Version      : ** 1.13.1 (build 96cfc63)
  - **Framework Version:** node v11.1.0
  - **OS               :** osx 10.15
  - **Language         :** typescript

### Other

After tracing the code, I find it is because the `region` is not set to empty string.
https://github.com/aws/aws-cdk/blob/7e226d62d1df98933e0fe64d401cd3c8b6b73352/packages/%40aws-cdk/aws-eks/lib/aws-auth.ts#L107

Therefore, the arn format function will bring in `stack.region` which causes the problem
https://github.com/aws/aws-cdk/blob/7e226d62d1df98933e0fe64d401cd3c8b6b73352/packages/%40aws-cdk/core/lib/arn.ts#L81

Could I try to fix the problem base on this direction? 
Please correct me if I am wrong at the view of the design. 

--- 

This is :bug: Bug Report

**Comment by eladb** [comment]
Thanks for the quality report. Fix is coming up.
