### ISSUE TITLE
.NET API Reference missing?

### ISSUE THREAD

**Issue by Graham-Beer** [aws/aws-cdk#4559]
https://docs.aws.amazon.com/cdk/api/latest/dotnet/api/index.html

Is there an issue with the .NET API Reference page? For all other languages it works fine, but for .NET there is no content. 

---

This is a 📕 documentation issue

**Comment by SomayaB** [comment]
Hi @Graham-Beer, thanks for letting us know. We will look into it right away.

**Comment by plumdog** [comment]
It appears that this is now for all languages, not just .NET.

Eg, go to https://github.com/aws/aws-cdk, click on "API Reference", which goes to https://docs.aws.amazon.com/cdk/api/latest/docs/aws-construct-library.html, and I get an AWS "Looking for Something?" page.

**Comment by plumdog** [comment]
My comment above does now appear to be resolved (that is, I believe #4582 is now resolved), but the .NET docs still just say
> Click on a module in the left sidebar to view its documentation.

And nothing else.

**Comment by plumdog** [comment]
The .NET docs now load for me, so I think this is now fixed?

**Comment by Graham-Beer** [comment]
Looks like it is now working.

**Comment by shivlaks** [comment]
@Graham-Beer - thanks for reporting, and for confirming the fix! 

It should all be working now. Let us know if you experience any issues.
