### ISSUE TITLE
Add support for CloudWatch Anomaly Detectio

### ISSUE THREAD

**Issue by noam-stein** [aws/aws-cdk#4569]
When creating a new alarm we could select 
Threshold Type: Static | Anomaly detection

### Use Case

I want to detect an abnormality in my lambda Duration run time

### Proposed Solution
we can create two new alarm types:
* AnomalydetectionAlarm
* StaticAlarm (this will replace the old Alarm)

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by SomayaB** [comment]
Hi @noam-stein, does [this](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cloudwatch.CfnAnomalyDetector.html#class-cfnanomalydetector-construct) not fulfill what you're looking for? If not, could you please provide more info so we can understand better what you're looking for. Thanks!

**Comment by noam-stein** [comment]
This  @SomayaB is precisely what I wanted, 
thanks for the quick response
