### ISSUE TITLE
Python installation not working on Mac OS Catalina

### ISSUE THREAD

**Issue by gamename** [aws/aws-cdk#4570]
## The Question

I've tried installing aws-cdk.core on 2 different macs and both exhibit the same problem.  After installing the package using `pip3 install aws-cdk.core`, the `cdk` command cannot be found.
In both cases, the cdk directories are present in the `site-packages` directory.

Both Macs are newly upgraded to Catalina (10.15).   

### Environment

  - **CDK CLI Version:** N/A
  - **Module Version:** N/A
  - **OS:**       System Version: macOS 10.15 (19A583)
      Kernel Version: Darwin 19.0.0
      Boot Volume: Disk
      Boot Mode: Normal
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 4 days 5:17
  - **Language:** Python 3

**Comment by Jerry-AWS** [comment]
The `aws-cdk.core` package is not the `cdk` command. The `cdk` command needs to be installed with `npm` (it's written in TypeScript and run on Node.js), even if you're otherwise using Python.

**Comment by gamename** [comment]
Thanks!
