### ISSUE TITLE
Allow modification of cdk cli

### ISSUE THREAD

**Issue by konstantinj** [aws/aws-cdk#4575]
## :question: General Issue

For issues like #4514 or #3780 it would be great if users of the cdk cli would be able to add their modifications/custom logic to the cli itself.

Currently my only approach is to create my own executable `cdk` file like this:
```javascript
#!/usr/bin/env node
var Module = require('module');
var originalRequire = Module.prototype.require;
Module.prototype.require = function () {
    if (arguments[0] == '../package.json') {
        arguments[0] = __dirname + '/node_modules/aws-cdk/bin/' + arguments[0];
    }
    return originalRequire.apply(this, arguments);
};

require('aws-cdk/bin/cdk');
Object.defineProperty(exports, "__esModule", { value: true });
const ctk = require("aws-cdk/lib/cdk-toolkit");
ctk.CdkToolkit.prototype.originalDeploy = ctk.CdkToolkit.prototype.deploy;
ctk.CdkToolkit.prototype.deploy = async function (options) {
    console.log('Overwriting!!!');
    this.originalDeploy(options);
};
```
This would be an example how to overwrite the deploy function from CdkToolkit. Unfortunately the `require.main.require` call to all `package.json` files does not resolv when the base path is not where the original `cdk` cli is placed so I need this workaround.

I understand that you presumably won't merge most of the changes to the cli. So I'm going this way now.

Maybe it is possible to achieve this through the plugin system. I haven't studied this one yet. Or you could allow some other kind of hooks that users could set in the codebase or as a separate file per command line argument.

**Comment by shivlaks** [comment]
@konstantinj have you given the template(s) a try? Does it work for your use cases or are there still limitations and sharp edges you're running into?

**Comment by konstantinj** [comment]
Hi @shivlaks what kind of templates do you mean?
