### ISSUE TITLE
Previously valid ELBv2 configuration is broken. NLB Healthchecks

### ISSUE THREAD

**Issue by trondiz** [aws/aws-cdk#4578]
This configuration used to work, but does not validate in 1.13.0

    const targets = listener.addTargets('targets', {
      port: 8200,
      targets: [asg],
      protocol: elb.Protocol.TLS,
      healthCheck: {
        protocol: elb.Protocol.HTTPS,
        healthyThresholdCount: 2,
        unhealthyThresholdCount: 2,
        path: '/',
        timeout: cdk.Duration.seconds(10),
        interval: cdk.Duration.seconds(10)
      }
    });

### Error Log

  [--redacted--] Health check paths are not supported for Network Load Balancer health checks
  [--redacted--] Custom health check timeouts are not supported for Network Load Balancer health checks

### Environment

  - **CLI Version      :*1.13.0*
  - **Framework Version:*1.13.0*
  - **OS               :*na*
  - **Language         :*javascript*

### Other

I believe this PR added the extra validation: https://github.com/aws/aws-cdk/pull/4280

Cloudformation/AWS fully supports configuring path for a TargetGroup healthcheck afaik.

--- 

This is :bug: Bug Report

**Comment by nmussy** [comment]
Hey @trondiz,

The [documentation](https://docs.aws.amazon.com/elasticloadbalancing/latest/network/target-group-health-checks.html) states that the path is for "HTTP/HTTPS health checks" only, which is probably where the confusion came from.

I'll make a PR to get this fixed.

Thanks for the report, and sorry for breaking your existing configuration.
