### ISSUE TITLE
Type mismatch warning in Python

### ISSUE THREAD

**Issue by DerkSchooltink** [aws/aws-cdk#4580]
The ability to add event sources to a Lambda is a cool feature, but inference of the common interface seems to fail for SQS event sources. The deployment seems to be successful anyway, which makes me believe the warning is incorrect.

The following snippet is a minimum working example:

```
class DeploymentsStack(core.Stack):

    def __init__(self, scope: core.Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        lambda = Function(
            self,
            id='id',
            handler='handler',
            runtime=Runtime.GO_1_X,
            code=Code.from_asset('...'),
        )

        queue = Queue(
            self,
            id='id',
            encryption=QueueEncryption.KMS_MANAGED
        )

        sqs_eventsource = SqsEventSource(
            batch_size=1,
            queue=queue
        )

        lambda.add_event_source(sqs_eventsource)

```

Even though the `sqs_eventsource` implements `aws_cdk.aws_lambda.IEventSource` according to the JSII annotation, and  the method `add_event_source()` accepts the exact same interface, a warning is still issued.

![image](https://user-images.githubusercontent.com/22047701/67081878-55e67380-f198-11e9-8061-aab0c9132032.png)

I'm not sure whether this is a IDE problem (I'm developing with Intellij IDEA), a JSII issue or a CDK issue. My apologies if this is the wrong place for creating this issue.

### Environment

  - **CDK Version : 1.11.0 (build 4ed4d96)**
  - **OS : Mac OSX Catalina**

--- 

This is :bug: Bug Report

**Comment by nmussy** [comment]
Hey @DerkSchooltink,

I tried to reproduce the same code with WebStorm and TypeScript, and it's working fine:

```ts
const lambda = new LambdaFn(this, 'function', {
  runtime: Runtime.NODEJS_8_10,
  handler: 'hello.handler',
  code: Code.fromInline('() => {}'),
});

const queue = new Queue(this, 'queue', {});
const eventSource = new SqsEventSource(queue, {batchSize: 1});

lambda.addEventSource(eventSource);
```

This seems to be Python specific.

**Comment by DerkSchooltink** [comment]
> Hey @DerkSchooltink,
> 
> I tried to reproduce the same code with WebStorm and TypeScript, and it's working fine:
> 
> ```ts
> const lambda = new LambdaFn(this, 'function', {
>   runtime: Runtime.NODEJS_8_10,
>   handler: 'hello.handler',
>   code: Code.fromInline('() => {}'),
> });
> 
> const queue = new Queue(this, 'queue', {});
> const eventSource = new SqsEventSource(queue, {batchSize: 1});
> 
> lambda.addEventSource(eventSource);
> ```
> 
> This seems to be Python specific.

Most likely a JSII issue then? I'm not that well-read on JSII but perhaps something is not transpiled correctly for the Python module?

**Comment by RomainMuller** [comment]
I suspect this might be related to how interfaces are handled in our Python bindings, that prevent the IDE from understanding the *implements* relationship there. Asked people deeper in Python than I am to have a quick look and hopefully confirm or infirm my assessment of the situation here...

**Comment by garnaat** [comment]
This seems to be IDE-specific.  I created the following sample:

```
#!/usr/bin/env python3

from aws_cdk import (
    aws_lambda as _lambda,
    aws_lambda_event_sources as events,
    aws_sqs as sqs,
    core,
)


class FooStack(core.Stack):

    def __init__(self, scope: core.Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        function = _lambda.Function(
            self, "lambda_function",
            handler='lambda_handler.main',
            runtime=_lambda.Runtime.PYTHON_3_7,
            code=_lambda.Code.asset("./lambda"),
        )

        queue = sqs.Queue(
            self, "myqueue",
            encryption=sqs.QueueEncryption.KMS_MANAGED
        )

        sqs_eventsource = events.SqsEventSource(
            batch_size=1,
            queue=queue
        )

        function.add_event_source(sqs_eventsource)


app = core.App()
FooStack(app, "foo")

app.synth()
```

With a small no-op Lambda function and then tried editing it in VS Code.  It doesn't complain about the event source as shown above and everything synthesizes correctly.
