### ISSUE TITLE
Official CDK API Reference documentation 404

### ISSUE THREAD

**Issue by jkinghed** [aws/aws-cdk#4582]
https://docs.aws.amazon.com/cdk/api/latest/index.html
https://docs.aws.amazon.com/en_pv/cdk/api/latest/index.html

Official API Reference documentation returns 404 page. Tried both the standard url and the "new look" url (not sure if applicable) with 404 as result.

This issue is referenced in #4559 but it's not applicable to .NET

---

This is a 📕 documentation issue

**Comment by plumdog** [comment]
@jkinghed the main docs have just started working for me.

Though #4559 appears to still be an issue.

**Comment by jkinghed** [comment]
@plumdog Hah, timing... but yes, can confirm that .NET is still missing. Closing this one.
