### ISSUE TITLE
Expandable VPC networking

### ISSUE THREAD

**Issue by fogfish** [aws/aws-cdk#4586]
[VPC with Public and Private Subnets](https://docs.aws.amazon.com/vpc/latest/userguide/VPC_Scenario2.html) is a classical pattern for networking. AWS CDK supports it just out of the box. However, existing implementation does not support well network expansion. 

#### Layered stacks

I’ve started with monolith Cloud Formation template that spin off entire infrastructure: networking gears, load balancers, compute resources, etc. The maintainability of it becomes a headache. It might even lead you to situation when you cannot apply updates without a downtime. Therefore, you have to split you solution for few independent layers - VPC networking shall be deployed in its own template.

The networking stack is deployed once per environment (e.g. dev, live). The deployment of The deployment of AWS resources in this design is grouped by unique routing requirement and deployed to appropriates subnets. 

**Existing** AWS CDK supports this use case

```typescript
// StackA
const vpc = new ec2.Vpc(this, 'Vpc', {/* config */})

// StackB
const vpc = new ec2.Vpc.fromLookup(this, 'Vpc',  { vpcName: 'StackA/Vpc' })
```

The problem arise when you have to fulfil unique routing requirement for resource in StackB and provision Private Subnets (e.g. isolate storage layer from back-end components) . It is possible to use `ec2.PrivateSubnet` but implementation becomes clumsy. StackB does not know anything about:
* CIDR and available allocations, the networking utils are not exported from `aws-ec2`.
* NAT Gateways, the concept of NAT gateways are not exported from `aws-ec2`. 

```typescript
   const subnetA = new ec2.PrivateSubnet(this, 'MyDatabase1', 
      {
        availabilityZone: vpc.availabilityZones[0],
        cidrBlock: '10.1.1.0/28',
        vpcId: vpc.vpcId
      }
    )
    subnetA.addDefaultNatRoute('nat-xxx')

    const subnetB = new ec2.PrivateSubnet(this, 'MyDatabase2
      {
        availabilityZone: vpc.availabilityZones[1],
        cidrBlock: '10.1.2.0/28',
        vpcId: vpc.vpcId
      }
    )
    subnetB.addDefaultNatRoute('nat-xxx')
```

#### Scalable CIDR allocation

Proper subnet layout is a key issue to provision scalable VPC networking. For example, I've use following policies with AWS Cloud Formation templates
* Existed implementation divides VPC network ranges evenly across two availability zones eu-west-1a and eu-west-1b in region. Half of VPC capacity is reserved for expansion to other availability zones.
* Each availability zone allocates its CIDR blocks between two subnets public for Internet facing services and private for back-end. Half of availability zone capacity is reserved for further subnet expansion.

The chosen schema gives you ability to expand VPC with subnets while we are going and deploy a new applications. 

**Existing** AWS CDK supports this use case. You can spawn VPC with reserved CIDR capacity. However, StackB does not know anything about CIDR allocations.  

```typescript
    new ec2.Vpc(this, 'Vpc',
      {
        ...
        maxAzs: 2,
        subnetConfiguration: [
          {
            name: 'Public',
            subnetType: ec2.SubnetType.PUBLIC,
            cidrMask: 24,
          },
          {
            name: 'Public',
            subnetType: ec2.SubnetType.PUBLIC,
            cidrMask: 19,
            reserved: true,
          },
          {
            name: 'Private',
            subnetType: ec2.SubnetType.PRIVATE,
            cidrMask: 24,
          },
          {
            name: 'Private',
            subnetType: ec2.SubnetType.PRIVATE,
            cidrMask: 19,
            reserved: true,
          },
        ],
      }
    )
```

### Proposed Solution

The requirement is only to have an ability to create Public/Private/Isolated subnets to existing VPCs. Key point here that `Vpc` class would manage association of CIDR, Nat GW, etc by itself.

```typescript
const vpc = new ec2.Vpc.fromLookup(this, 'Vpc',  { vpcName: 'StackA/Vpc' })

vpc.createSubnet(this, {
  name: 'MyDatabase',
  subnetType: ec2.SubnetType.PRIVATE,
  cidrMask: 28,
})
``` 

### Other

None.

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by fogfish** [comment]
What do you think about this feature? Is it even possible to implement it with current VPC interfaces?

**Comment by fogfish** [comment]
@rix0rrr @eladb do you have any thought about this issue? I am really struggling to understand if it is feasible to achieve with existing CDK?

**Comment by rix0rrr** [comment]
You seem to be asking for a feature where you declare a VPC without subnets in StackA, and progressively add subnets to it in StackB, StackC, etc., one per service. Do I have that right?

We can consider that as a feature request, but it seems niche. How many people have a workflow like that?

I think at some point we're going to say "this is the limits of what the built-in VPC will support, you can make your own implement of `IVpc` that does exactly what you need it to do."

Whether this particular request is going to fall inside our outside that boundary remains to be seen.

**Comment by fogfish** [comment]
Yes, you are right. This is about progressive ability to add subnets.

**Comment by fogfish** [comment]
Please let me comment more regarding the workflow.

Most simplest setup is the provision VPC with Front-End/Back-End subnetworks at once, then deploy all services there. The problem arise when you have to fulfil unique routing requirement for a new BE service. I think the dedicated `ec2.PrivateSubnet` would be a right option for this purposes. However, you are not able to create subnet w/o specification of CIDR block.
