### ISSUE TITLE
HostedZone.fromLookup throws exception

### ISSUE THREAD

**Issue by fogfish** [aws/aws-cdk#4592]
`HostedZone.fromLookup` crash the stack deployment.

You are using `this` within static method
https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-route53/lib/hosted-zone.ts#L97

### Reproduction Steps

I believe you example will fail
https://github.com/aws-samples/aws-cdk-examples/blob/master/typescript/static-site/static-site.ts

```
const zone = route53.HostedZone.fromLookup(this, 'Zone', { domainName: props.domainName });
```

### Error Log

```
   return this.fromHostedZoneAttributes(scope, id, {
                ^
TypeError: Cannot read property 'fromHostedZoneAttributes' of undefined
```

### Environment

  - **CLI Version      :*1.13.1*
  - **Framework Version:*1.13.1*
  - **OS               :*MacOS*
  - **Language         :*typescript*

### Other

None

--- 

This is :bug: Bug Report

**Comment by shivlaks** [comment]
@fogfish - can you provide the steps to reproduce the error you're running into. I haven't used this resource in a while but I think I was able to use `fromLookup`.

`this` reference from static method is valid TypeScript

**Comment by fogfish** [comment]
@shivlaks I am using your example. Please find the link in the error report. Now, I am suspecting that my `tsconfig.json` is root cause. Especially `noImplicitThis`

```
{
  "compilerOptions": {
    "target":"ES2018",
    "module": "commonjs",
    "lib": ["es2016", "es2017.object", "es2017.string"],
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "noImplicitThis": true,
    "alwaysStrict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": false,
    "inlineSourceMap": true,
    "inlineSources": true,
    "experimentalDecorators": true,
    "strictPropertyInitialization":false
  }
}
```

**Comment by fogfish** [comment]
I've nailed it down. Vanilla example code works file but issue appears if I make an equivalent code with https://github.com/fogfish/aws-cdk-pure

If you replace the [line 26](https://github.com/aws-samples/aws-cdk-examples/blob/master/typescript/static-site/static-site.ts#L26)

```typescript
const zone = route53.HostedZone.fromLookup(this, 'Zone', { domainName: props.domainName });
```

with

```typescript
const f = route53.HostedZone.fromLookup
const zone = f(this, 'Zone', { domainName: props.domainName });
```

then you'll see the exception 

```
return this.fromHostedZoneAttributes(scope, id, {
                ^
TypeError: Cannot read property 'fromHostedZoneAttributes' of undefined
```

**Comment by fogfish** [comment]
Would you be able to provide any feedback on the issue?

**Comment by AlexZeitler** [comment]
@fogfish I just tried to use `HostedZone.fromLookup` in a stack and I was wondering why I didn't get a reference to my zone. Anything else within the stack has been deployed and the part referring to the zone (Allow an IAM group to `ChangeResourceRecordSets` for this zone) silently fails.

Using your code

```ts
const f = route53.HostedZone.fromLookup
const zone = f(this, 'Zone', { domainName: props.domainName });
```

I got the error message you've described:

```txt
Cannot read property 'fromHostedZoneAttributes' of undefined
```
