### ISSUE TITLE
[lambda] Support inline lambda code for Node 10.x

### ISSUE THREAD

**Issue by PeterBengtson** [aws/aws-cdk#4642]
CDK doesn't support ZipFile inline lambda code for NODEJS10. It does support it for NodeJs 8, but when the code below uses NodeJs10, CDK returns an error message saying 10 is incompatible.

I have checked this with AWS Support. They're not familiar with the CDK, but doing the same thing in pure CloudFormation works with both 8 and 10

### Reproduction Steps

```
    // This lambda builds the AMI we later will need to start our EC2 instances
    // from. NB that we MUST use InlineCode as the ZipFile format is required
    // for the callback signal from cfnresponse.send to work. So no S3 here.
    const lambdaProvider = new lambda.SingletonFunction(this, 'AmiBuilderLambda', {
      uuid: 'xxxxxxxxxx-xxxxx-xxxx-xxxxxxx-xxxxx',
      runtime: lambda.Runtime.NODEJS_8_10, // MUST NOT be NODEJS 10
      code: new lambda.InlineCode(fs.readFileSync(`${sourcePath}/index.js`, { encoding: 'utf-8' })),
      handler: 'index.handler',
      timeout: cdk.Duration.minutes(15),
      environment: {
          ...
      },
    })
```

### Environment

  - **CLI Version      :1.16.208
  - **Framework Version:1.13.1
  - **OS               :MacOS
  - **Language         :TS

--- 

This is :bug: Bug Report

**Comment by nmussy** [comment]
Hey @PeterBengtson,

According to [aws-cloudformation-coverage-roadmap#80](https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/80), `ZipFile` support for Node 10 should be coming soon.

> pure CloudFormation works with both 8 and 10

I could check to make sure, but I doubt they would have rolled out this feature silently.

Hope this helps!

**Comment by PeterBengtson** [comment]
Thanks for the link. It's weird, though, that the Support person I talked to tried this out in CF with 10 and it worked. It does not work with the CDK. Timing?

**Comment by nmussy** [comment]
The CDK preemptively verifies that inline code isn't used with Node 10, with the `supportsInlineCode` property:

https://github.com/aws/aws-cdk/blob/c0c0513b68cc12e6696c57d2305bf84311ad9c59/packages/%40aws-cdk/aws-lambda/lib/runtime.ts#L37

I've opened a draft PR to test this out. I'll get back to you when the CI logs are available. 👍

**Comment by nmussy** [comment]
Well, what do you now... [It works fine](https://github.com/aws/aws-cdk/pull/4655#issuecomment-545684636).

Could someone from AWS confirm that this is available for good/across all regions?

I'll get the PR ready for prime-time in the meantime (I'll cover #4653 in #4655 too)

**Comment by nmussy** [comment]
Hey @PeterBengtson,

My bad, it's still not implemented. I thought the integration tests were ran during the CI process, but apparently not ([see @jogold's comment](https://github.com/aws/aws-cdk/pull/4655#discussion_r338965154)).

I'll keep the PR open to get this merged as soon as it's released

**Comment by PeterBengtson** [comment]
Any ETA?
