### ISSUE TITLE
Update deprecated Lambda run-times NODEJS_8_10 to NODEJS_10_X

### ISSUE THREAD

**Issue by 0xdabbad00** [aws/aws-cdk#4653]
The Lambda run-time NodeJS 8.10 has been deprecated and you will no longer be able to create new functions with it on January 6, 2020. https://docs.aws.amazon.com/lambda/latest/dg/runtime-support-policy.html

This run-time is in use by a number of Lambda functions that the CDK creates.  For example:
- https://github.com/aws/aws-cdk/blob/592bbc0b7b6baa00248f835899d137beede285a7/packages/%40aws-cdk/aws-dynamodb-global/lib/global-table-coordinator.ts#L19
- https://github.com/aws/aws-cdk/blob/592bbc0b7b6baa00248f835899d137beede285a7/packages/%40aws-cdk/aws-ecr-assets/lib/adopted-repository.ts#L36
- https://github.com/aws/aws-cdk/blob/a9fef66c058a96833b235b4a1690322f0285753c/packages/%40aws-cdk/aws-ses/lib/receipt-rule.ts#L174

It is also used by a lot of integration tests.  These should all be upgraded to use the latest run-time.  AWS has sent out emails to myself and others warning us to upgrade.

**Comment by nija-at** [comment]
Hi @0xdabbad00 - Thanks for reporting this issue and apologies for the delayed response here. 

We'll get these updated.
