### ISSUE TITLE
aws-certificatemanager DnsValidatedCertificateHandler does not properly handle certs with SubjectAlternativeNames

### ISSUE THREAD

**Issue by mmoulton** [aws/aws-cdk#4659]
A DnsValidatedCertificate will never successfully validate when SubjectAlternativeNames are present. This seems to be due to the custom resource only adding the first DomainValidationOptions record to Route53. See [line 110](https://github.com/aws/aws-cdk/blob/c0c0513b68cc12e6696c57d2305bf84311ad9c59/packages/%40aws-cdk/aws-certificatemanager/lambda-packages/dns_validated_certificate_handler/lib/index.js#L110) here. This should add a new ResourceRecordSet for every DomainValidationOptions result.

### Reproduction Steps

Create a `DnsValidatedCertificate` and add at least one record to `subjectAlternativeNames`.

### Environment

  - **CLI Version      :** 1.14.0
  - **Framework Version:** 1.14.0
  - **OS               :** MacOS 10.14
  - **Language         :** Typescript

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
Thanks for reporting.

**Comment by pasieronen** [comment]
Furthermore, it looks like `validationDomains` option (which could be used to work around this, assuming all subjectAlternativeNames are under the same name) is totally ignored by DnsValidatedCertificate...

**Comment by jamiepmullan** [comment]
Any updates on this @SomayaB ?

**Comment by jamiepmullan** [comment]
@rix0rrr  / @SomayaB Can we please get an update on this one?

**Comment by rix0rrr** [comment]
We don't have any concrete plans for addressing this on the short term. A PR for it would be welcomed though

**Comment by touzoku** [comment]
+1 to this bug report.

The bug is in the CustomResource function [here](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-certificatemanager/lambda-packages/dns_validated_certificate_handler/lib/index.js#L110):
```javascript
record = options[0].ResourceRecord;
```

The code should iterate over `options` array (these are all domain validation options, including subjectAlternativeNames) instead of taking the first element of the array and then passing it to:
```javascript
const changeBatch = await route53.changeResourceRecordSets({
    ChangeBatch: {
      Changes: [{
        Action: 'UPSERT',
        ResourceRecordSet: {
          Name: record.Name,
          Type: record.Type,
          TTL: 60,
          ResourceRecords: [{
            Value: record.Value
          }]
        }
      }]
    },
    HostedZoneId: hostedZoneId
  }).promise();
```

The fix is dead simple: just do a `for(const option of options) { ... }`

**Comment by touzoku** [comment]
Repro:
```javascript
const hostedZone = route53.HostedZone.fromLookup(this, 'WebsiteHostedZone', {domainName: 'example.com'})
new acm.DnsValidatedCertificate(
      this,
      'WebsiteCertificate',
      {
        domainName: 'example.com',
        subjectAlternativeNames: ['www.example.com'],
        hostedZone
      }
    )
```

It will only validate `example.com`, while `www.example.com` will be left hanging in ACM until the validator cloudformation custom resource times out.
