### ISSUE TITLE
EventPattern adds clauses not asked for

### ISSUE THREAD

**Issue by PeterBengtson** [aws/aws-cdk#4666]
EventPattern in CDK adds extra clauses not asked for. For instance, the following declaration:

```
        eventPattern: {
          detail: {
            eventName: ['ConsoleLogin'],
            responseElements: {
              ConsoleLogin: ['Success'],
            },
          },
```

Produces the following CloudFormation:

```
        "EventPattern": {
          "detail": {
            "eventName": [
              "ConsoleLogin"
            ],
            "responseElements": {
              "ConsoleLogin": [
                "Success"
              ]
            }
          },
          "detail-type": [
            "AWS API Call via CloudTrail"
          ]
        },
```
The `detail-type` clause value isn't only unwanted, it's also wrong. Also, if you explicitly specify another value, the result value is the union of your explicit specification and the erroneous `"AWS API Call via CloudTrail"` value, e.g. the following CF: 

```
"detail-type": [
            "AWS API Call via CloudTrail",
            "AWS Console Sign In via CloudTrail",
          ]
```
But there is no way of getting rid of the erroneously inserted API Call string in the generated CloudFormation.

### Reproduction Steps

Try the following CloudTrail code:
```
    trail
      .onCloudTrailEvent('FailedLogins', {
        description: 'Looks for failed logins',
        eventPattern: {
          detail: {
            eventName: ['ConsoleLogin'],
            responseElements: {
              ConsoleLogin: ['Failure'],
            },
          },
        },
      })
```

### Environment

  - **CLI Version      :** aws-cli/1.16.208 Python/2.7.10 Darwin/18.7.0 botocore/1.12.198
  - **Framework Version:** 1.13.1
  - **OS               :** MacOs Catalina
  - **Language         :** TS

--- 

This is :bug: Bug Report

**Comment by PeterBengtson** [comment]
Somaya, I see that you've added the language tag for Python. However, this is a TS problem, alternatively it applies to all languages. Are you sure the Python tag is correct here? Python is mentioned only in the CLI spec.

**Comment by rix0rrr** [comment]
I see, `onCloudTrailEvent` adds that selector, and should properly be called `onApiCall` instead.

Ultimately, there isn't much that separates a CloudTrail event from another type of event (except the detail-type) so you could just create an `events.Rule` with the pattern you're looking for instead.

**Comment by PeterBengtson** [comment]
Yeah, I'm examining alternatives as we speak. (The CloudTrail module also is not stable yet, so I don't expect consistency, of course.) It seems as if there are other problems with onCloudTrailEvent too. I'm considering foregoing rules altogether seems the entire thing seems flaky in CDK and instead use an SNS topic triggering a Lambda to parse the log files directly as they are deposited in the S3 bucket. Do you have any recommendations here?
