### ISSUE TITLE
addEventNotification not available for an existing S3 bucket

### ISSUE THREAD

**Issue by CharlesSieg** [aws/aws-cdk#4671]
Within the @aws-cdk/aws-s3 library, the static method Bucket.fromBucketName is used to return a reference to an existing S3 bucket. Unfortunately, this type of the object returned by this method is IBucket, not an actual Bucket. Since the IBucket interface does not have the addEventNotification method, it appears impossible to create an event on an existing S3 bucket using the CDK.

### Reproduction Steps

```
//
// Create a Lambda function.
//
const lambdaFn = new lambda.Function(this, 'lambda', {
});

//
// Set the Lambda function to be triggered when a file is added to the specified bucket.
//
const bucket = s3.Bucket.fromBucketName(this, 'bucket', `some-bucket-name`);
const eventSource = new eventSources.S3EventSource(bucket, {
	events: [s3.EventType.OBJECT_CREATED]
});
lambdaFn.addEventSource(eventSource);
```

### Error Log

```
.../lib/lambda.js:66
         bucket.addEventNotification(s3.EventType.OBJECT_CREATED, new s3n.LambdaDestination(lambdaFn));
                       ^
TypeError: bucket.addEventNotification is not a function
    at new Lambda (.../lib/lambda.js:66:10)
    at new JobService (.../jobService.js:57:3)
    at Object.<anonymous> (.../jobService.js:81:1)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11

```

### Environment

  - **CLI Version      : 1.14.0**
  - **Framework Version: all**
  - **OS               : all**
  - **Language         : JavaScript / Node.js**

### Other

Please return a fully realized Bucket object from this method rather than IBucket.

--- 

This is :bug: Bug Report

**Comment by insanitybit** [comment]
FWIW I found this on SO.
https://stackoverflow.com/questions/58087772/aws-cdk-how-to-add-an-event-notification-to-an-existing-s3-bucket

**Comment by eladb** [comment]
Duplicate with #2004
