### ISSUE TITLE
Cloudfront tagging for CloudFrontWebDistribution

### ISSUE THREAD

**Issue by abelmokadem** [aws/aws-cdk#4681]
Can we tag the CloudFront resources with the tags of the stack? Right now I have custom code lik this:

```typescript
    (metadataCdn.node.tryFindChild("CFDistribution") as cloudfront.CfnDistribution).addPropertyOverride(
      "Tags",
      this.tags.renderTags()
    );
```

### Use Case

To make my CloudFront life easier and to propagate tags to all resources in my stack. CloudFront for some reason seems to have its own `Tags` property and is not picking up the stack tags.

### Proposed Solution

Populate the `Tags` property by default with `this.tags.renderTags()`.

### Other

* [X] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by njlynch** [comment]
I realize this is rather old -- our apologies for the severe delay in answering -- but this appears to already work, both with the existing `CloudFrontWebDistribution` and the newer `Distribution` construct.

```ts
const dist = new Distribution(this, 'dist', {
  defaultBehavior : { origin: new HttpOrigin('www.example.com' },
});
// -- OR -- 
const dist = new CloudFrontWebDistribution(this, 'dist', {
  originConfigs: [{
    customOriginSource: {
      domainName: 'www.example.com',
    },
    behaviors: [{ isDefaultBehavior: true }],
  }],
});

Tags.of(dist).add('myKeyName', 'myKeyValue');
```

Closing this out, as somewhere in the last 10 months we seem to have fixed this.
