### ISSUE TITLE
CDK state and deployments

### ISSUE THREAD

**Issue by jamiepmullan** [aws/aws-cdk#4683]
**Background:**
At present we first deploy our CDK app/stacks from a local machine, which deploys all resources upfront. Thereafter, the Code pipeline takes git application code and deploys this new code only (e.g. and automatically create a new lambda version/aliases). If something changes in infrastructure, we have to redeploy the CDK pipeline from local.

**Desired behaviour:**
We want to take the step so that we can create/modify resources, deploy new code and have control over ALL resources we are deploying (i.e. nothing auto-created via CDK).

**Question:**
What way would you recommend doing this using CDK? Using ‘cdk deploy’ in the Pipeline to deploy every time within the app/stack? I didn’t know if this would be possible/the best approach as this would be a new entry in Cloudformation.
I want to be able mimic Terraform state files to keep track of infrastructure instead of having to reverse engineer CDK stacks to know what to modify/destroy from the previous version of code.

**Comment by eladb** [comment]
We expect to address this as part of #3437. Would you mind reviewing the RFC and letting us known over that PR if there are any use cases that won’t be addressed by the proposal? 

Reopen if needed.

**Comment by ali-habibzadeh** [comment]
@eladb #3437 is really great. Pretty much would solve our blocker. Do you have any estimates even if roughly as to when this might become available?
