### ISSUE TITLE
None of my imports work for local invoke. Error: Cannot find module

### ISSUE THREAD

**Issue by jbeckton** [aws/aws-cdk#4694]
When invoking a simple Lambda locally none of my imports work.

    
    import { APIGatewayEvent, APIGatewayEventRequestContext, Context } from "aws-lambda";
    const awsServerlessExpress = require( 'aws-serverless-express' );
    const app = require( './app/app' );

    const binaryMimeTypes = [
    'application/javascript',
    'application/json',
    'application/octet-stream',
    'application/xml',
    'font/eot',
    'font/opentype',
    'font/otf',
    'image/jpeg',
    'image/png',
    'image/svg+xml',
    'text/comma-separated-values',
    'text/css',
    'text/html',
    'text/javascript',
    'text/plain',
    'text/text',
    'text/xml'
    ]
    const server = awsServerlessExpress.createServer( app, undefined, binaryMimeTypes )
    exports.handler = ( event: APIGatewayEvent, context: Context ) => 
    awsServerlessExpress.proxy( server, event, context )
    
when I invoke the function locally I get the following error

    {
      "errorType": "Runtime.ImportModuleError",
      "errorMessage": "Error: Cannot find module 'aws-serverless-express'"
    }

if I change the order of the awsServerlessExpress and app imports then none of the imports in the app.js file work either.

here is the CDK code I used to define the lambda...

    const goodbye = new lambda.Function( this, 'GoodbyeHandler', {
          runtime: lambda.Runtime.NODEJS_10_X,
          code: lambda.Code.fromAsset( '../lambda/goodbye/dist' ),
          handler: 'lambda.handler'
        } );

**Comment by Rahmo** [comment]
I'm having this issue now. how did you resolve it ?
