### ISSUE TITLE
Automatically detect and split stacks when CloudFormation resource limits are reached

### ISSUE THREAD

**Issue by binarythinktank** [aws/aws-cdk#4698]
### :question: General Issue
It seems it is not possible to create and deploy an API with many resources and methods.

1. put all resources/methods into a single stack: 200 resource limit
2. move the resources/methods that don't fit into a separate stack: cyclic reference error
3. disable the deploy:true setting in the restapi: unable to add resources because no stage
4. create stage: it needs a deployment, add deployment in stack 1: see error 2, add deployment in stack 2: see error 3 for the resources in stack 1

it's a vicious circle.

i have seen a proposal to create 2 apis, then use a custom domain and mapping to make it look like a single one. i can see how that could work but seems terribly hacky. 

a suggestion to delete resources, ok, but that's not really solving anything is it. 

likely i will go with plan c for now: deploy what i can, then manually add the missing resources that i need via aws gui and hope that nobody accidentally deletes them. 

### Environment

  - **CDK CLI Version:** 1.14.0 (build 261a1bf)
  - **Module Version:** 1.14.0 
  - **OS:** Ubuntu 18
  - **Language:** Javascript

**Comment by nija-at** [comment]
Hello @binarythinktank  -

I'm sorry you've had a poor experience here in this situation. I'll confess that we don't have a very good story around what to do when users hit the stack resource limit.

> move the resources/methods that don't fit into a separate stack: cyclic reference error

Which specific ones did you hit on this? Are there bug reports already filed for these?

**Comment by binarythinktank** [comment]
@nija-at I don't think they are bugs, they are just cloudformation limitations. The cyclic reference errors also make sense if the resources are in 2 different stacks. I guess what I'm hoping for is a way for CDK to somehow solve these problems in the background. Perhaps there is a way to make it work with nested stacks for example and, if so, perhaps CDK could automatically create these nested stacks when it sees cloudformation limits being reached.

**Comment by nija-at** [comment]
Definitely something within the scope of the CDK. I'm converting this into a feature request.

**Comment by nija-at** [comment]
@binarythinktank - check out the new feature in API Gateway that allows you to break up resources and methods across CF stacks - https://docs.aws.amazon.com/cdk/api/latest/docs/aws-apigateway-readme.html#breaking-up-methods-and-resources-across-stacks

Does this satisfy your original ask?

**Comment by binarythinktank** [comment]
certainly looks promising, i'll give it a try. will this need additional work to support in CDK?

**Comment by nija-at** [comment]
Closing this for now. Reopen if this solution doesn't satisfy. 
Also open separate issues if this works mostly but there are gaps or bugs that you come across.
