### ISSUE TITLE
Add support for MessageAttributes in PublishToTopic step functions task

### ISSUE THREAD

**Issue by fabio-vitali** [aws/aws-cdk#4702]
The PublishToTopic step functions task should permit to publish filtrable messages.

### Use Case
We need an SQS queue to subscribe an SNS topic using a filterPolicy on message attributes 

### Proposed Solution
A new "messageAttributes" property in PublishToTopicProps will permit to set the publishing SNS message attributes with static or task input values.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by devendra-kumar1** [comment]
@shivlaks : any plan to include this feature in upcoming release ?

**Comment by joa44741** [comment]
I'd also appreciate this feature! :) 
Or is there any workaround?

**Comment by devendra-kumar1** [comment]
@joa44741 as a workaround  we introduced a lambda layer and from there we used AWS-SDK's SNS publish method. There is a facility

**Comment by shivlaks** [comment]
@victoriatanaka noted! i'll see if I can work a PR in for this missing capability this week

**Comment by victoriatanaka** [comment]
@shivlaks that would be really awesome, thank you so much! :)

**Comment by nmduarteus** [comment]
Hi @shivlaks - wondering if there is any update? or if someone knows a workaround (except creating an extra lambda)? Thanks a lot in advance!

**Comment by victoriatanaka** [comment]
Hi @shivlaks did you have a chance to look into it? Thanks! :)

**Comment by nmduarteus** [comment]
hi all,
just wondering if there is any update here?

thank you once again!
cheers

**Comment by moofish32** [comment]
Does anybody in this group need attributes besides String?

**Comment by nmduarteus** [comment]
I do not, no.

**Comment by taciosd** [comment]
I don't either, just String for now.

**Comment by jumic** [comment]
@peterwoodworth In PR #14817 this issue was resolved. Could you please close this issue? It wasn't referenced correctly in the PR. Thanks.

**Comment by peterwoodworth** [comment]
Thanks again jumic!
