### ISSUE TITLE
Tags are not added to IAM user

### ISSUE THREAD

**Issue by AlexZeitler** [aws/aws-cdk#4704]
### Reproduction Steps

I'm creating a new IAM user like this and try to add `Tag`s to it (using either option 1 or option 2):

```ts
const user = new iam.User(this, 'iam-user-ci-app', {
    userName: 'iam-user-ci-app'
})
user.node.applyAspect(new Tag('key', 'value')) // option 1 

Tag.add(user, 'key', 'value') // option 2
```

After `cdk deploy` the user is created but it has no tags applied.

### Environment

  - **CLI Version      : 1.14.0**
  - **Framework Version: 1.14.0**
  - **OS               : Darwin mbp.local 19.0.0 Darwin Kernel Version 19.0.0: Wed Sep 25 20:18:50 PDT 2019; root:xnu-6153.11.26~2/RELEASE_X86_64 x86_64**
  - **Language         : TypeScript**

### Other

Same happens for a `Group` construct.

--- 

This is :bug: Bug Report

**Comment by AlexZeitler** [comment]
`cdk synth` output also does not contain Tags.

**Comment by AlexZeitler** [comment]
I think I found [a hint](https://stackoverflow.com/a/56396964/90800), can somebody please confirm this?

**Comment by rix0rrr** [comment]
It seems to be true that IAM users do not allow tagging via CloudFormation: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-iam-user.html

**Comment by moofish32** [comment]
While it's definitely not an ideal solution, you could create a custom resource to add tags leveraging the API call while we wait for the CloudFormation update.

**Comment by AlexZeitler** [comment]
So this would be a Lambda function tagging the User using the AWS SDK?

**Comment by JoshMcCullough** [comment]
Any update on this? CDK is still not applying tags to IAM constructs (in my case, roles).

**Comment by systematicguy** [comment]
same issue here

**Comment by raziza** [comment]
Also not in iam policies or iot policies.. Not woring via `StackProps.Builder` and also specific when calling `Tags.of(...).add(..)`. ended up  2 years ago with developing an `IAspect` that creates a tagging - lambda+role, provider+role, custom resource. 4 Resources once and a custom resource for each policy that runs this function. I would reopen this bug.
