### ISSUE TITLE
Routing when multiple NAT gateways are specified is not as expected.

### ISSUE THREAD

**Issue by balkat** [aws/aws-cdk#4706]
* When specifying a value for `natGateways` greater than one the resulting private subnet route tables all point to one and the same NAT gateway.
* Expectation is that private subnets would be routed to different NAT gateways.

### Reproduction Steps

* An example VPC configuration is attached.
* Synthesize or deploy and observe that all private subnets are all routed to the same NAT gateway.  The other NAT gateways have no routes to them.

[vpc.ts.txt](https://github.com/aws/aws-cdk/files/3776966/vpc.ts.txt)

### Error Log

* No errors.
* Deployment succeeds.
* Routing tables are not configured as expected.

### Environment

  - **CLI Version      : aws-cli/1.16.107 Python/2.7.16 Darwin/18.7.0 botocore/1.12.97**
  - **Framework Version: 1.14.0 (build 261a1bf)**
  - **OS               : MacOS 10.14.6**
  - **Language         : typescript**

### Other

--- 

This is :bug: Bug Report

**Comment by balkat** [comment]
To be fair, I'm probably driving this way outside its intended design envelope, so if you want to treat it as a feature request instead, go right ahead :-)

**Comment by rix0rrr** [comment]
If that is true, that behavior is incorrect though. Every subnet should preferantially route through the NAT gateway in the same AZ.

**Comment by balkat** [comment]
And my original assumption was that if you have N private subnets, N public subnets and `natGateways` set to N then private_subnet[n] would route to nat_gateway[n] in public subnet[n].
This could lead to a lot of complexity and even more ambiguity, however.  Perhaps the NAT gateways are deployed evenly across public subnets and private subnets are routed evenly across the fleet of NAT gateways.....  If you wanted to enable full control then I would suggest each subnetConfiguration array element contains the option for natGateways which is honoured for PUBLIC subnets only.   PRIVATE subnets can specify the public subnet through which they route... e.g.
`[
  {
        cidrMask: 24,
        name: 'blah',
        subnetType: SubnetType.PUBLIC,
        natGateways: 2,
      },
      {
         cidrMask: 24,
         name: 'foo',
         subnetType: SubnetType.PRIVATE,
         useNatGatewayIn: 'blah',
      }
...
]`

Anyway, it's getting quite academic here, so again, don't stress on my account  :-)

**Comment by rix0rrr** [comment]
Oh I see now what you did. 1 AZ but 3 gateways required. It will create only 1 gateway though (for the one AZ) and not create redundant ones.

That's a different feature request. Closing this for now.
