### ISSUE TITLE
renderTags() with TagType

### ISSUE THREAD

**Issue by abelmokadem** [aws/aws-cdk#4709]
Allow developer to input the `TagType` to the `renderTags` method.

### Use Case

I need to create a custom resource with tags with the format of `{"TagName": "TagValue"}` instead of `[{Key: "foo", Value: "bar"}]`.

### Other

* [X] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by moofish32** [comment]
Hi @abelmokadem - any chance you can share some sample code? I'm trying to understand how you are using tags with custom resources?

The tag manager actually takes in `TagType` at instantiation time. If you are looking for a way to change this at render time, it's not currently supported. However, if there is a good use case perhaps we can solve it.

**Comment by eladb** [comment]
Supported
