### ISSUE TITLE
Implement IGrantable on aws-custom-resource/AwsCustomResource

### ISSUE THREAD

**Issue by abelmokadem** [aws/aws-cdk#4710]
Implement IGrantable on aws-custom-resource/AwsCustomResource.

### Use Case

I need to allow passRole for the creation of a custom resource.

### Other

* [X] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by jogold** [comment]
In the meantime you can use the `policyStatements` prop.

**Comment by SomayaB** [comment]
Hi @abelmokadem, thanks for submitting a feature request! We will look into this and someone will update this issue when there is movement.
