### ISSUE TITLE
Speed up custom resource development

### ISSUE THREAD

**Issue by abelmokadem** [aws/aws-cdk#4711]
## :question: General Issue
I think we can speed up custom resource development in `@aws-cdk/custom-resources` by not running this as part of cloudformation but from the machine that is running the `cdk deploy`. This feature, however, should only be used for local development purposes and not for production stacks. Introducing a flag would work:

`cdk deploy --local-custom-resources` 

This would definitely shorten my development cycle. Hope that this is possible.

### The Question
Can we create custom resources from the local machine?

### Environment

  - **CDK CLI Version:** 1.14.0
  - **Module Version:** 1.14.0
  - **OS:** all
  - **Language:** TypeScript

**Comment by mcalello** [comment]
@eladb Has this been fixed with your merge in #4572?
