### ISSUE TITLE
GraphWidget will not update CloudFormation for changed title

### ISSUE THREAD

**Issue by sbstjn** [aws/aws-cdk#4712]
If you change a `Widget` name in a CloudWatch `Dashboard`, the `aws-cdk` will not generate new CloudFormation resources when `title` is changed.

### Reproduction Steps

First, deploy the dashboard and widget, then change the widget's name and deploy again.

```ts
dashboard.addWidgets(
  new GraphWidget({
    title: 'A: B',
    // title: 'B: A',
    width: 12,
    left: [ … ]
  })
)
```

### Environment

  - **CLI Version      :** 1.14.0
  - **Framework Version:** 1.14.0
  - **OS               :** 
  - **Language         :** TypeScript

### Other

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
I find this one hard to judge. Can you help me investigate?

Could you post the templates before the change and after the change? Do they actually contain the title text?

If you deploy the 2 templates in succession directly through CloudFormation, does the change occur?  Does the CloudFormation log show an update of the Dashboard, but does it make no changes? Or does the CloudFormation log show it's not making any changes at all?

**Comment by SomayaB** [comment]
Hi @sbstjn, any updates on the questions above?

**Comment by SomayaB** [comment]
Closing this issue since there hasn't been a response but feel free to reopen if you want to pick this back up.

**Comment by gaulatti** [comment]
It seems this keeps happening. If you create a Widget and then you update it, it won't change. The workaround is to delete the dashboard and create it again.
