### ISSUE TITLE
cdk version is not displaying installed version

### ISSUE THREAD

**Issue by emanserav** [aws/aws-cdk#4718]
<cdk --version> displays an old version
in my current scenario  it shows 1.13.1 (build 96cfc63),  even if I've updated to 1.15

### Reproduction Steps

I am working on  a Mac ( got the same behaviour on python 2.7.16 and also on python 3.7.4 )

### Environment

  - **CLI Version      :*aws --version
aws-cli/1.16.215 Python/2.7.16 Darwin/19.0.0 botocore/1.12.205*
  - **Framework Version:*it should be 1.15, but it shows 1.13*
  - **OS               :*Mac OS Catalina*
  - **Language         :*EN*

### Other

--- 

This is :bug: Bug Report

**Comment by eladb** [comment]
The correct syntax is `cdk --version`, but it could be nice to also support `cdk version` as a shortcut.

**Comment by emanserav** [comment]
Hi @eladb , 

this is what I meant **`cdk --version`** 
thank you for the prompt response.

( Congrats on this wonderful project, I am watching it very closely to see if we can use it in production )

**Comment by nmussy** [comment]
I can probably take this one

**Comment by emanserav** [comment]
hi @mussy, 
just to be sure you got this right, 
the problem I am facing is is that I do not get the correct version displayed when 
`**cdk --version**`

**Comment by nmussy** [comment]
Oh, no sorry, that's not what I understood. I think @eladb misunderstood you as well.

Did you upgrade your global CDK version, or just your local dependencies?

```
> npm list -g --depth=0 | grep cdk
├── cdk@1.15.0

> cdk --version # your globally installed cdk package
1.15.0 (build bdbe3aa)

> npx cdk --version # your local cdk package
1.15.0 (build bdbe3aa)
```

**Comment by emanserav** [comment]
I cannot say why the version was not displaying correct.
I've initially ran only updating command
`pip install --upgrade aws-cdk.core`

I've tried now reinstalling through: 
`npm install -g aws-cdk`
and that seems it fixed now the problem and, the version is being displayed properly now.
Closing this issue - thank you.
