### ISSUE TITLE
regression in complete viewerCertificate support (#4579) for CertificatesArns imported from another Stack 

### ISSUE THREAD

**Issue by gergan** [aws/aws-cdk#4724]
I have a stack X, which creates all our app's certificates. The Certificate-Arns are exported from the stack X with cdk.CfnOutput and till now have been imported with cdk.Fn.importValue from our App-Stack and used in the following way 

```
new cloudfront.CloudFrontWebDistribution(this, 'Distribution,{
            ...
            aliasConfiguration: {
                acmCertRef: props.apexCertArnCloudFront, // <- cdk.Fn.importValue(...)
                names: [props.domainName],
            }, 
            ...
});

```
This leads to the following error:
```
acmCertificate certficate must be in the us-east-1 region, got eu-central-1
```
aliasConfiguration is now deprecated, but it does not change the problem, as I have re-written the code with the new viewerCertificate.

The Problem is in the certificatemanager getCertificateRegion, which tries to deduce the region, but falls back to the region of the current stack, if the certificate-Arn is not Resolvable.

```
export function getCertificateRegion(cert: ICertificate): string | undefined {
  const { certificateArn, stack } = cert;

  if (isDnsValidatedCertificate(cert)) {
    const requestResource = cert.node.findChild('CertificateRequestorResource').node.defaultChild;

    // @ts-ignore
    const { _cfnProperties: properties } = requestResource;
    const { Region: region } = properties;

    if (region && !Token.isUnresolved(region)) {
      return region;
    }
  }

  {
    const { region } = Arn.parse(certificateArn);

    if (region && !Token.isUnresolved(region)) {
      return region;
    }
  }

  return Stack.of(stack).region;   <-- that's the problem
}
```

Strangely enough the ViewerCertificate.fromAcmCertificate checks if the region is unresolved...

### Error Log

acmCertificate certficate must be in the us-east-1 region, got eu-central-1

### Environment

  - **CLI Version      : 1.15.0
  - **Framework Version: 1.15.0
  - **OS               : n/a
  - **Language         : typescript

### Other

Probably just returning Arn.parse(certificateArn); in getCertificateRegion should fix the problem...

--- 

This is :bug: Bug Report

**Comment by nmussy** [comment]
Hey @gergan,

Sorry for breaking your existing stacks. What I was attempting to catch with the `Stack.of(stack).region` fallback was the following common use-case:

https://github.com/aws/aws-cdk/blob/ea4a8aad96c4cf7d940e0e938aed7390cd32d4e7/packages/%40aws-cdk/aws-certificatemanager/test/test.util.ts#L55-L66

I'm looking into a fix, sorry again!

**Comment by hoegertn** [comment]
Any idea of the ETA and if this will be a patch release? It breaks all my web apps.

**Comment by nmussy** [comment]
@hoegertn Are you using the same method as @gergan?

It was supposed to be a UX improvement for the relative minor inconvenience of creating a certificate in the wrong region, and having that stack rollbacked.

I'll make a PR to revert this change right away, and look for a fix later.

**Comment by hoegertn** [comment]
I create the cert using the DnsValidatedCertificate... and it is a token and has no region info.

**Comment by hoegertn** [comment]
My code is:

```
		const certArn = new DnsValidatedCertificate(this, 'Certificate', {
            hostedZone: zone,
            domainName,
            region: 'us-east-1',
        }).certificateArn;

		...

        this.distribution = new CloudFrontWebDistribution(this, 'Distribution', {
            aliasConfiguration: {
                acmCertRef: certArn,
                names: [domainName],
            },
			...
        });
```

And this no longer works. If I should rewrite this differently this is fine.

**Comment by nmussy** [comment]
@hoegertn I've deprecated the `aliasConfiguration` property, but it's still using the new API if set:

https://github.com/aws/aws-cdk/blob/ea4a8aad96c4cf7d940e0e938aed7390cd32d4e7/packages/%40aws-cdk/aws-cloudfront/lib/web_distribution.ts#L765-L772

```ts
'deprecated alias': {
  'base usage'(test: Test) {
    const stack = new cdk.Stack();
    const sourceBucket = new s3.Bucket(stack, 'Bucket');

    const certificate = new certificatemanager.Certificate(stack, 'cert', {
      domainName: 'example.com',
    });

    new CloudFrontWebDistribution(stack, 'AnAmazingWebsiteProbably', {
      originConfigs: [{
        s3OriginSource: { s3BucketSource: sourceBucket },
        behaviors: [{ isDefaultBehavior: true }]
      }],
      aliasConfiguration: {
          acmCertRef: certificate.certificateArn,
          names: ['example.com'],
      },
    });

    expect(stack).to(haveResourceLike('AWS::CloudFront::Distribution', {
      "DistributionConfig": {
        "Aliases": ["example.com"],
        "ViewerCertificate": {
          "AcmCertificateArn": {
            "Ref": "cert56CA94EB"
          },
          "SslSupportMethod": "sni-only"
        }
      }
    }));

    test.done();
  },
},
```

**Comment by gergan** [comment]
> Hey @gergan,
> 
> Sorry for breaking your existing stacks. What I was attempting to catch with the `Stack.of(stack).region` fallback was the following common use-case:
> 
> https://github.com/aws/aws-cdk/blob/ea4a8aad96c4cf7d940e0e938aed7390cd32d4e7/packages/%40aws-cdk/aws-certificatemanager/test/test.util.ts#L55-L66
> 
> I'm looking into a fix, sorry again!

No problem, thanks for the fast reaction.

**Comment by hoegertn** [comment]
@nmussy I tracked it down and it seems to be the same problem for me. As I use lookups for the HostedZone I set the account and region using ENV. This leads to the stack region being used for the ACM Cert. I will switch to the new code but it seems to have the same issue.

**Comment by nmussy** [comment]
@hoegertn Yeah, either APIs in `v1.15.0` will check the region, sorry about that
