### ISSUE TITLE
CDK DIFF not displaying in AWS CF ChangeSet console

### ISSUE THREAD

**Issue by emanserav** [aws/aws-cdk#4739]
I've just noticed that `cdk diff `**is not** displaying the ChangeSet in the AWS CF Console.
Why ? Any reason for that ?
( seeing the ChangeSet in AWS CF Console history is too late with cdk deploy)

I like seeing the changes in console using `cdk diff `but they should be identical to what I should be visualising in AWS CF ChangeSet before applying them. Are they identical ?

### Use Case

daily scenario: updating existing Stacks in various environments
I don't want to check the ChangeSet history but I would like to check **prior** to applying the changes with `cdk deploy`

### Proposed Solution

`cdk diff` just this command or with a flag to display the ChangeSet details also in AWS CF ChangeSet Console 

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by robertma96** [comment]
I'm interested in this too. 

I would love to be able to deploy a Change Set to a stack, without executing the changes. Basically I would like to see what will change through AWS CloudFormation service, and then execute or discard the changes. 

`cdk deploy STACK` creates a Change Set **AND** applies the changes.

I would love to have an option that will create the Change Set (so I can visualise it in AWS CloudFormation) and not apply the changes.

Something like `cdk deploy STACK --execute-change-set no`.

**Comment by eladb** [comment]
I can see where this can be useful. How would that work with multi-stack apps? Will it create a changeset for all of them?

As for the name of the switch, I think `--execute` and `--no-execute` should be sufficient and `--no-execute` should print the link to the change set of course!

**Comment by emanserav** [comment]
hi @eladb,
yes, each Stack with its own ChangeSet, perfectly fine also with the options you mentioned.

That will be awesome and one more step closer to production ready as I see it.

Toda Raba.

**Comment by SomayaB** [comment]
Related to #3780

**Comment by emanserav** [comment]
Great job guys!
Many thanks @robertma96  @SomayaB @eladb 
Can’t wait to use this in the future release.
