### ISSUE TITLE
Instructions in `Contributing.md` for pulling the superchain docker image don't work

### ISSUE THREAD

**Issue by mpiroc** [aws/aws-cdk#474]
The relevant instructions:

    eval $(aws ecr get-login --no-include-email)
    IMAGE=260708760616.dkr.ecr.us-east-1.amazonaws.com/superchain:latest
    docker pull ${IMAGE}
    docker run --net=host -it -v $PWD:$PWD -w $PWD ${IMAGE}

The error:

    Error response from daemon: pull access denied for 260708760616.dkr.ecr.us-east-1.amazonaws.com/superchain, repository does not exist or may require 'docker login'

Ideally, the superchain image should be published to Docker Hub. In the meantime, we should fix these instructions to unblock potential contributors.

**Comment by mpiroc** [comment]
@costleya

**Comment by hassankhan** [comment]
Big +1, really wanted to get a PR in this weekend but can't figure out how to get set up.

**Comment by rix0rrr** [comment]
A simple solution would be to make the image pullable by anyone, which is easy enough to do.

However, I am told there might be legal implications and I'm not 100% up on the details enough to do it myself right now, I'm sorry. Calling @eladb to share his opinion on this next week.

**Comment by toddwildey** [comment]
export AWS_ACCOUNT_ID="your_account_id"
git clone git@github.com:awslabs/superchain.git
cd superchain
./build.sh
eval $(aws ecr get-login --no-include-email --region us-west-2)
docker tag superchain $AWS_ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com/superchain:latest
docker push $AWS_ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com/superchain:latest

**Comment by rix0rrr** [comment]
This will work only for members of the awslabs organization, unfortunately, as the superchain repository and image are private. Until we figure out whether it's okay to release this, the superchain contains these pieces of software, so either building your own image with these or installing them on your host system will also unblock you:

    node.js-8.11.0
    java-openjdk-8
    dotnet-core-2
    python-3.6.5
    ruby-2.5.1
    rsync

**Comment by hassankhan** [comment]
Aww that's a shame, I'd rather not have to install all this on my host system 😞

Is there an ETA on when you might reach a decision on the Docker image?

**Comment by rix0rrr** [comment]
I'm putting the gears into motion. Stay tuned.

**Comment by rix0rrr** [comment]
Thinking about it some more, you can quite effectively develop for the CDK using only TypeScript using only locally-installed npm packages.

The instructions don't really mention this, but you can probably get by with

```shell
$ ./install.sh
$ ./build.sh
```

from the root, outside a Docker image (this is what I do).

**Comment by hassankhan** [comment]
Thanks for the pointers, I'll give it a go 👍

**Comment by Doug-AWS** [comment]
Can we close this?

**Comment by hassankhan** [comment]
Yep I think so, this issue is now irrelevant since the `CONTRIBUTING.md` guide does not require the private Docker image any more.

**Comment by Doug-AWS** [comment]
Assigned to Michael to close as he opened it.

**Comment by NGL321** [comment]
@rix0rrr Status on this?

**Comment by SomayaB** [comment]
Closing this issue since there hasn't been activity on it in a while. Feel free to reopen.
