### ISSUE TITLE
route53: HostedZone should have a `hostedZoneArn` property

### ISSUE THREAD

**Issue by AlexZeitler** [aws/aws-cdk#4744]
### The Question
I'm trying to create a IAM group with a policy attached to change DNS records for a Route53 hosted zone.

This is my code:

```ts
const group = new iam.Group(this, 'group', {
      groupName: 'ci-ui-iam-group'
    })

const zone = route53.HostedZone.fromLookup(this, 'zone', {
      domainName: 'mydomain.com'
    })

group.addManagedPolicy(
      new iam.ManagedPolicy(this, 'AllowChangeRecordSets', {
        managedPolicyName: 'allow-change-record-sets',
        statements: [
          new iam.PolicyStatement({
            effect: iam.Effect.ALLOW,
            resources: [`arn:aws:route53:::${zone.hostedZoneId}`],
            actions: ['route53:ChangeResourceRecordSets']
          })
        ]
      })
    )
```

It creates the group as well as the policy, whose JSON looks like this:

```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": "route53:ChangeResourceRecordSets",
      "Resource": "arn:aws:route53:::/hostedzone/<SomeHostedZoneId>",
      "Effect": "Allow"
    }
  ]
}
```

When opening the new Policy in AWS Console, I get this warning:

![image](https://user-images.githubusercontent.com/287480/67809576-39501280-fa99-11e9-986e-14e2e2220fdf.png)

When changing the `Resource` entry like this (removing the `/` before `hostedzone`):

```
"Resource": "arn:aws:route53:::hostedzone/<SomeHostedZoneId>",
```

the policy is fixed.

So my question is: can I get `hostedzone/<SomeHostedZoneId>` using AWS CDK instead of `/hostedzone/<SomeHostedZoneId>` so I don't have to remove the leading `/` myself?

Or even better: is there a function in the CDK which allows me to get the full ARN for this zone?

### Environment

  - **CDK CLI Version: 1.15.0** 
  - **Module Version: 1.15.0** 
  - **OS: Darwin mbp.local 19.0.0 Darwin Kernel Version 19.0.0: Wed Sep 25 20:18:50 PDT 2019; root:xnu-6153.11.26~2/RELEASE_X86_64 x86_64** 
  - **Language: TypeScript**

**Comment by abelmokadem** [comment]
I think the entire `/hostedzone/` part should be removed. This attribute should just return the ID of the hosted zone.

**Comment by AlexZeitler** [comment]
That’s what I expected it to be when using it for the first time.

**Comment by rix0rrr** [comment]
You should not have to construct the ARN yourself, the class should do this for you.

**Comment by abelmokadem** [comment]
I see that the title was changed, but what about the issue of getting the `/hostedzone/` as part of the hosted zone id when importing a hosted zone? When creating a hosted zone in cdk, the id only returns the id part and does not prefixes it with `/hostedzone/`.

**Comment by AlexZeitler** [comment]
Having consistent behavior between creating the `HostedZone` and importing it using `route53.HostedZone.fromLookup` would be great.
