### ISSUE TITLE
EKS --use-max-pods=false not working

### ISSUE THREAD

**Issue by progamesigner** [aws/aws-cdk#4752]
In [bootstrap.sh](https://github.com/awslabs/amazon-eks-ami/blob/master/files/bootstrap.sh), option `--use-max-pods` can be `true` or `false` and default to `true`.

However, in CDK `--use-max-pods` option would be appended to `extraArgs` only if it's `true` and omitted when `false`. As a result, if I want to disable this behavior and pass `false` as `bootstrapOptions`, it would generate `LaunchConfiguration` with no `--use-max-pods` option and thus default to `true` in `bootstrap.sh` script. Which is not intended.

### Reproduction Steps

Set `useMaxPods` to `false` in `bootstrapOptions` when pass options in `AutoScalingGroup`.

### Error Log

No logs. Generated CF templates are not included desired option.

### Environment

  - **CLI Version**: 1.13.1
  - **Framework Version**: 1.13.1
  - **OS**: MacOS
  - **Language**: TypeScript

--- 

This is :bug: Bug Report

**Comment by eladb** [comment]
Thanks for the report
