### ISSUE TITLE
Add static dynamodb.Table.fromXxx methods

### ISSUE THREAD

**Issue by PeterBengtson** [aws/aws-cdk#4756]
<img width="349" alt="screenshot_2019-10-30_at_08 29 31" src="https://user-images.githubusercontent.com/3897/67837825-3af8f500-faf0-11e9-8ba2-a780f5219d1a.png">

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by jogold** [comment]
Duplicate of #3895
