### ISSUE TITLE
Possibility to setup SNS dead letter queue for Lambda Function? 

### ISSUE THREAD

**Issue by MaartenThoelen** [aws/aws-cdk#4758]
### The Question

Is it possible to setup an SNS dead letter queue for a Lambda Function using the AWS CDK?
It looks like only SQS dead letter queues are supported.

### Environment

  - **CDK CLI Version:** 1.15.0 (build bdbe3aa)
  - **Module Version:** ^1.15.0
  - **OS:** OSX Mojave
  - **Language:** TypeScript

**Comment by nmussy** [comment]
Hey @MaartenThoelen,

I'm not sure I understand what you mean by SNS dead letter queue. Unlike SQS, SNS delivers its messages synchronously to its subscribers.

There is a feature to log the [delivery status in SQS or to a Lambda](https://docs.aws.amazon.com/sns/latest/dg/sns-topic-attributes.html), but it's currently not implemented in CloudFormation. You can track its progress on the roadmap: [cloudformation-coverage-roadmap#66](https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/66)

**Comment by MaartenThoelen** [comment]
Hi @nmussy ,

I am trying to replicate the same behavior as I did before with an AWS SAM template.
See the attachment below for a snippet from the original template. 

![Screen Shot 2019-10-30 at 13 05 11](https://user-images.githubusercontent.com/4532864/67856967-013ae500-fb16-11e9-907f-1d618ce19df9.png)

**Comment by nmussy** [comment]
Ah, I see, sorry. The [CDK documentation](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-lambda.Function.html#deadletterqueue) only accepts an SQS queue, but the CloudFormation 
 [`AWS::Lambda::Function DeadLetterConfig` property docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-function-deadletterconfig.html) says:

> The Amazon Resource Name (ARN) of an Amazon SQS queue or Amazon SNS topic.

I'll make a PR to fix this issue. In the meantime, you should be able to circumvent the issue using an [escape hatch](https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html). Tell me if you need more info.

Just as an FIY, there's also a package for SAM if you want to keep using it, [see `aws-sam`'s `CfnFunction.deadLetterQueue`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-sam.CfnFunction.html#deadletterqueue)

**Comment by MaartenThoelen** [comment]
Great!

Thanks for the info.
