### ISSUE TITLE
Construct `AliasConfigurationCert` is created with a literal unique name by the CloudfrontWebDistribution Construct

### ISSUE THREAD

**Issue by winjer** [aws/aws-cdk#4759]
If you create more than one `CloudfrontWebDistribution` that has a certificate associated with it in a single stack then you get the error:

    Error: There is already a Construct with name 'AliasConfigurationCert' in Stack

This looks like it is because of this line:

        certificatemanager.Certificate.fromCertificateArn(scope, 'AliasConfigurationCert', acmCertRef),

in `web_distribution.ts`.

### Reproduction Steps

Create two CloudFrontWebDistributions in one stack.

### Error Log

    Error: There is already a Construct with name 'AliasConfigurationCert' in Stack

### Environment

  - **CLI Version      :1.14.0 (build 261a1bf)**
  - **Framework Version: 1.15.0**
  - **OS               : Linux**
  - **Language         : Typescript**

### Other

--- 

This is :bug: Bug Report

**Comment by winjer** [comment]
It looks like this can be avoided by using `viewerCertificate` instead of `aliasConfiguration` and that this is indeed preferable, so this is probably a documentation bug instead?

**Comment by nmussy** [comment]
Hey @winjer,

It's a mistake on my part when I added backwards compatibility from the deprecated `aliasConfiguration`. I'm making a PR to fix it for the next release.

Sorry to have to force you to switch to `viewerCertificate` in the meantime.

**Comment by winjer** [comment]
I'm happy to use viewerCertificate - it looks like that's a better choice anyway to be honest!

**Comment by nmussy** [comment]
Thanks for being understanding. The `aws-cloudfront` package is still marked as experimental, but it wasn't my intention to break `aliasConfiguration` 😄
