### ISSUE TITLE
InterfaceVpcEndpoint does not create valid security group

### ISSUE THREAD

**Issue by davidsteed** [aws/aws-cdk#4762]
### Reproduction Steps

new ec2.InterfaceVpcEndpoint(this, id , {
      service: ec2.InterfaceVpcEndpointAwsService.KMS,
      vpc: vpc,
      subnets: {subnetType:SubnetType.PUBLIC}

    });

### Error Log

I want to use the default vpc security group - but that does not seam possible.  A new one is created, that does not allow inboud traffic.  If I modify the security group manually to allow inbound trafic it works.  Don't see any way of doing that in cdk.

### Environment

  - **CLI Version      :1.15.0
  - **Framework Version:1.15.0
  - **OS               :**
  - **Language         :typescript

### Other

--- 

This is :bug: Bug Report

**Comment by jogold** [comment]
You can use the `connections` object of your endpoint:
```ts
myEndpoint.connections.allowDefaultPortFrom(...)
```

does this work for you?

**Comment by jogold** [comment]
`allowDefaultPortFrom(Peer.ipv4('<SUBNET_CIDR>'))`

**Comment by davidsteed** [comment]
Thank you

**Comment by SomayaB** [comment]
Thanks @jogold! Closing this issue since it seems resolved. Feel free to reopen.
