### ISSUE TITLE
Referencing context variables in Typescript

### ISSUE THREAD

**Issue by mscharp** [aws/aws-cdk#4764]
https://docs.aws.amazon.com/cdk/latest/guide/get_context_var.html

`const bucket_name = this.node.tryGetContext("bucket_name")`

Documentation should be enhanced to state that this syntax only works when you're attempting to get the context variable from within a Stack construct.  Outside of it, the following error is thrown:

error TS7017: Element implicitly has an 'any' type because type 'typeof globalThis' has no index signature.

To reference it outside of a stack, say in the initialization of the application, then this would work

`
const app = new cdk.App();
const bucket_name = app.node.tryGetContext("bucket_name")
`

---

This is a 📕 documentation issue

**Comment by Jerry-AWS** [comment]
That's a great catch! This is a small fix so I can get to it pretty much right away.

**Comment by Jerry-AWS** [comment]
I've updated this and it's wending its way through our publishing process right now. I'll close this issue when I see the update go live.

**Comment by Jerry-AWS** [comment]
This looks to be live, so I'll close this.
