### ISSUE TITLE
How to create EC2 with custom storage size

### ISSUE THREAD

**Issue by icecold21** [aws/aws-cdk#4773]
### The Question
How can I create ec2 node with defined storage size from CDK

### Environment

  - **CDK CLI Version:** 
1.13.1 (build 96cfc63)
  - **Module Version:** 
@aws-cdk/aws-ec2 version 1.13.1
  - **OS:** 
OSX Mojave
  - **Language:** 
TypeScript

### Other information

This is my construct
```
const instance = new Instance(this, 'SolrInstance', {
      vpc: vpc,
      instanceName: 'SolrInstance',
      instanceType: InstanceType.of(InstanceClass.BURSTABLE3, InstanceSize.NANO),
      machineImage: ubuntuImage,
      allowAllOutbound: true,
      keyName: 'solr-key',
      vpcSubnets: { subnetType: SubnetType.PRIVATE },
      securityGroup: SolrSecurityGroup,
    });
```

How do i specify the ebs volume of this instance?

**Comment by nmussy** [comment]
Hey @icecold21,

It looks like the [`BlockDeviceMappings`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-blockdevicemappings) is missing from the L2 `Instance` construct.

Until they're added, you'll need to modifiy the CloudFormation properties directly, something like:
```ts
const cfnInstance = instance.node.defaultChild as CfnInstance;
// @ts-ignore - readonly
cfnInstance.blockDeviceMappings = [{
  deviceName: '/dev/sda',
  ebs: {volumeSize: 20},
}];
```

I'll look into making a PR to ease that process
