### ISSUE TITLE
TaskDefinitionProps.cpu Number type or String type

### ISSUE THREAD

**Issue by bryan0515** [aws/aws-cdk#4774]
According to the doc below, the CPU type is an integer, but the type in the code is a string. Could you double-check?
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-containerdefinitions.html#cfn-ecs-taskdefinition-containerdefinition-cpu

https://github.com/aws/aws-cdk/blob/b082bf21cec9132e68455c3aedbdff8a73cc21ed/packages/%40aws-cdk/aws-ecs/lib/base/task-definition.ts#L129
### Reproduction Steps

and the memory as well
https://github.com/aws/aws-cdk/blob/b082bf21cec9132e68455c3aedbdff8a73cc21ed/packages/%40aws-cdk/aws-ecs/lib/base/task-definition.ts#L146

### Environment

  - **CLI Version      :**
  - **Framework Version:**
  - **OS               :**
  - **Language         :**

### Other

--- 

This is :bug: Bug Report

**Comment by pkandasamy91** [comment]
@bryan0515 the documentation you refer to: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-containerdefinitions.html#cfn-ecs-taskdefinition-containerdefinition-cpu refers to containerDefinition memory property, not the taskDefinition memory property. 

Container Definitions documentation: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-containerdefinitions.html#cfn-ecs-taskdefinition-containerdefinition-cpu
Container Definition CDK construct: https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-ecs/lib/container-definition.ts#L69

Task Definition CPU documentation: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-taskdefinition.html#cfn-ecs-taskdefinition-cpu
Task Definition CDK CPU Property: https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-ecs/lib/base/task-definition.ts#L129

**Comment by bryan0515** [comment]
mb. Thanks for clarify.
