### ISSUE TITLE
Step Function Condition and_(), not_(), and or_() methods generating wrong output in Python

### ISSUE THREAD

**Issue by JKCT** [aws/aws-cdk#4775]
Using combinations of Step Function Conditions by using the and_(), not_(), or_() methods in Python produces incorrect State Machine definitions.  

### Reproduction Steps
AWS CDK Python Code:
```
check_stack_status = sfn.Choice(
    self, "Stack ready?"
)
create_complete = sfn.Condition.string_equals(
    "$.stack_status", "CREATE_COMPLETE"
)
rollback_complete = sfn.Condition.string_equals(
    "$.stack_status", "ROLLBACK_COMPLETE"
)

definition = check_stack_status\
    .when(
        create_complete.or_(rollback_complete),
        sfn.Pass(self, "Pass")
    )
sfn.StateMachine(
    self, "StateMachine",
    definition=definition,
)
```

Produces the following CloudFormation template code with incorrect State Machine DefinitionString:
```  StateMachine2E01A3A5:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      DefinitionString: '{"StartAt":"Stack ready?","States":{"Stack ready?":{"Type":"Choice","Choices":[{"Or":[{"Variable":"$.stack_status","StringEquals":"ROLLBACK_COMPLETE"}],"Next":"Pass"}]},"Pass":{"Type":"Pass","End":true}}}'
```

Specifically:
```"Choices":[{"Or":[{"Variable":"$.stack_status","StringEquals":"ROLLBACK_COMPLETE"}],"Next":"Pass"}]}```

Should be:
```"Choices":[{"Or":[{"Variable":"$.stack_status","StringEquals":"CREATE_COMPLETE"}, {"Variable":"$.stack_status","StringEquals":"ROLLBACK_COMPLETE"}],"Next":"Pass"}]}```

It appears that only the last condition in the chain is added.  For example you can have an or_() chain of 5 conditions but only the last condition will actually be added to the state machine definition.  It appears that this error occurs with all the Condition joining methods(and, not, or).

Only tested with python so may or may not occur with other languages.

### Error Log

Deploys without error but produces incorrect templates.

### Environment

  - **CLI Version      :** 1.15.0
  - **Framework Version:** 1.15.0
  - **OS               :** macOS Mojave 10.14.6
  - **Language         :** Python 3.6.9 

### Other

--- 

This is :bug: Bug Report

**Comment by JKCT** [comment]
After many hours of trying different combinations and then submitting this issue I realized that and_(), or_(), and not_() are Static Methods of the Condition class.  Using the following code produces the expected output:
```
definition = check_stack_status\
    .when(
        sfn.Condition.or_(create_complete, rollback_complete),
        sfn.Pass(self, "Pass")
    )
```
Apologies this was a case of me not correctly reading the manual.  Issue closed.

**Comment by gcoleman72** [comment]
I made the same mistake. Thanks for posting your solution

**Comment by resnus** [comment]
Same here, this post helped me a lot!

**Comment by parthaskundu** [comment]
How can we add multiple conditions with and, or conditions in typescript? 
I am trying like this but it throws compilation error only! Some syntax error! 
`const conditionIsPresent = stepfunctions.Condition.isPresent('$.data.Config.title');
    const andConditionIsEqual = stepfunctions.Condition.stringEquals('$.data.Config.title', 'string');
    const orConditionIsEqual = stepfunctions.Condition.stringEquals('$.data.Config.title', 'STIRNG');
    const paymentsConditionIsEqual = stepfunctions.Condition.stringEquals('$.data.actionType', 'ACTION');

    const definition = preProcessor
      .next(new stepfunctions.Choice(this, 'Choice')
        .when(conditionIsPresent.and(andConditionIsEqual.or(orConditionIsEqual)), sf)
        .when(conditionIsPresent, sf)
        .when(paymentsConditionIsEqual, payments));`

**Comment by xmihal03** [comment]
> How can we add multiple conditions with and, or conditions in typescript? I am trying like this but it throws compilation error only! Some syntax error!
> 
> ```
> const conditionIsPresent = stepfunctions.Condition.isPresent('$.data.Config.title');
>     const andConditionIsEqual = stepfunctions.Condition.stringEquals('$.data.Config.title', 'string');
>     const orConditionIsEqual = stepfunctions.Condition.stringEquals('$.data.Config.title', 'STIRNG');
>     const paymentsConditionIsEqual = stepfunctions.Condition.stringEquals('$.data.actionType', 'ACTION');
> 
> const definition = preProcessor
>       .next(new stepfunctions.Choice(this, 'Choice')
>         .when(conditionIsPresent.and(andConditionIsEqual.or(orConditionIsEqual)), sf)
>         .when(conditionIsPresent, sf)
>         .when(paymentsConditionIsEqual, payments));
> ```

Like this

```
const conditionIsPresent = stepfunctions.Condition.isPresent('$.data.Config.title');
const andConditionIsEqual = stepfunctions.Condition.stringEquals('$.data.Config.title', 'string');
const orConditionIsEqual = stepfunctions.Condition.stringEquals('$.data.Config.title', 'STIRNG');
const paymentsConditionIsEqual = stepfunctions.Condition.stringEquals('$.data.actionType', 'ACTION');

const definition = preProcessor
      .next(new stepfunctions.Choice(this, 'Choice')
        .when(stepfunctions.Condition.and(andConditionIsEqual, orConditionIsEqual), sf)
        .when(stepfunctions.Condition.or(andConditionIsEqual, orConditionIsEqual), sf)
        .when(conditionIsPresent, sf)
        .when(paymentsConditionIsEqual, payments));
```

[Doc](https://github.com/aws/aws-cdk/blob/68204da91e3a5a8a7a3d2aa5c42aecac7be8e47e/packages/%40aws-cdk/aws-stepfunctions/lib/condition.ts#LL323C4-L323C4) 
```
 /**
   * Combine two or more conditions with a logical AND
   */
  public static and(...conditions: Condition[]): Condition {
    return new CompoundCondition(CompoundOperator.And, ...conditions);
  }
```
