### ISSUE TITLE
Lambda: make it easier to specify a list of files and directories instead of a directory for code assets

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#4776]
Since #4473 has landed, which has support for richer `.dockerignore` patterns, there is no need for this anymore. This is very simply achieved by:

```js
      code: lambda.Code.fromAsset(".", {exclude: ["**", "!index.py"]}),
```

You can consider adding this example somewhere if you wish, or just closing this outright.

_Originally posted by @nakedible in https://github.com/aws/aws-cdk/issues/4428#issuecomment-547931520_

**Comment by eladb** [comment]
Still think we should provide first class api for this

**Comment by melnikalex** [comment]
I don't know if this is related, but I'd like to also be able to upload a directory without zipping it. Is this feasible, already possible?

**Comment by eladb** [comment]
@melnikalex check out the [s3-deployment](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-s3-deployment-readme.html) module for that.

**Comment by ospfranco** [comment]
I just tried using this, at first it seemed to work fine, but I just realized that when I try to deploy, the latest version of my lambda is not detected.

I do some changes to the file, then run either `cdk diff` or `cdk deploy` and all I get are no changes.

Any suggestion to work around this?

**Comment by yogur** [comment]
How do I whitelist a directory from exclusion?

Whitelisting a file by using `"!index.py"` works. However, whitelisting a directory is not working. I tried `"!/dir/**", "!/dir", "!/dir/*". "!dir"` but non of them are working.

**Comment by Liooo** [comment]
@yogur 

alright this worked for me

```
lambda.Code.fromAsset(".", {exclude: ['**', '!dir', '!dir/*']})
```

**Comment by jjrv** [comment]
The `exclude` option is deprecated, is there a better alternative?

**Comment by zacyang** [comment]
The document is not even mention what is replacing it, just deprecate it....wat...

**Comment by iamchadarmstrong-pki** [comment]
I've been using this heavily and also just noticed it's been deprecated... Is there an existing alternate or one in the works?  Thanks!

**Comment by israelg99** [comment]
Update on this?

**Comment by maddyexplore** [comment]
Still not getting the file wise assert adding feature
