### ISSUE TITLE
CDK deletes exports that are still needed

### ISSUE THREAD

**Issue by binarythinktank** [aws/aws-cdk#4777]
apologies for the short bug report, but I'm in the middle of a project with a tight deadline so don't have time to delve deeper into the cause but i want to flag it here in case someone else is seeing the same and can add more information. (or i may be able to come back to it after my project is done). 

I have 3 stacks in my app, in the first stack i create a cognito pool
in stack 3 i create apigateway with an authorizer. The authorizer is linked to the cognito pool in stack 1.

when i remove the authorizer from stack 3, i guess CDK is deleting the exports for the cognito pool as they are no longer needed. However, when i deploy the stacks, cloudformation is failing and giving me an error that the exports are still needed in stack 3. There are no other references in stack 3 to these exports or the cognito pool. 

synth works fine, and i dont see any references there to the cognito pool, its only when i deploy it that cloudformation throws the error. for some reason it thinks the exports are still needed - i assume because its processing the "Delete exports" before the "delete authorizer". If my theory is correct, then a correct approach for CDK would be to delete the authorizer, but leave the exports there, then delete the exports on a next deploy? but just braindumping here. 

thanks

Update: my theory above seems to be correct. I added a request validator, and gave the request validator a name that included the cognito pool url, id and arn. With this in place, CDK did not remove the cognito pool exports and i was able to deploy successfully and the authorizer was removed. (now im stuck with the validator that i dont need, but at least it proved my point :) )

**Comment by jd-carroll** [comment]
@binarythinktank can you take a look at #3414 to see if that bug report encompasses what you are running into? (I'm thinking it will)

If so, you can take a look at #4014 for a possible workaround

**Comment by binarythinktank** [comment]
hi @jd-carroll thanks for your comment, #3414 is definitely describing the same issue. I had a look at #4014 but i don't have the time to try it. For now, I have stuck the exported params into a description field which creates an unnecessary description but at least no additional constructs.

**Comment by nakedible** [comment]
@binarythinktank I think you can just do `cdk deploy -e stack3` after removing the use of the reference. See #3414 for deeper discussion.

**Comment by binarythinktank** [comment]
@nakedible thanks, i missed that particular message before, but that's a great tip. thanks!
