### ISSUE TITLE
NetworkLoadBalancedFargateService to support listener other than tcp80

### ISSUE THREAD

**Issue by pahud** [aws/aws-cdk#4793]
At this moment `NetworkLoadBalancedFargateService` is extending `NetworkLoadBalancedServiceBase`, which only support listener on tcp80.

https://github.com/aws/aws-cdk/blob/d7654e714dc940565d76925dcbbb976cef6ddae4/packages/%40aws-cdk/aws-ecs-patterns/lib/base/network-load-balanced-service-base.ts#L248

Please support different port other than 80.

### Use Case

For some TCP application running on Fargate behind NLB, it's very common to listen on port other than 80.

### Proposed Solution

Add a `listenerPort` property for `NetworkLoadBalancedServiceBaseProps`.

https://github.com/aws/aws-cdk/blob/d7654e714dc940565d76925dcbbb976cef6ddae4/packages/%40aws-cdk/aws-ecs-patterns/lib/base/network-load-balanced-service-base.ts#L12-L110

### Other

* [v] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by pkandasamy91** [comment]
@pahud the loadBalancer is exposed to the user. You are able to add a new listener with a different port if you choose to listen on a different port.

**Comment by pahud** [comment]
Hi @pkandasamy91 

Yes it's possible. But then I need to specify another listener and specify targetgroup for this listener and I probably need to remove the default one on TCP80?

Why not just provide a `defaultLIstenerPort` like this and, if provided, override the default tcp 80?

In this case, we just need to add an optional property for it and that's all.

```js
    const svc = new ecsPatterns.NetworkLoadBalancedFargateService(this, 'NLBService', {
      assignPublicIp: true,
      cluster,
      defaultListenerPort: 6032,
      taskImageOptions: {
        image: ecs.ContainerImage.fromAsset('./dockerAssets.d'),
        enableLogging: true,
        containerPort: 6032
      }
    })
```
