### ISSUE TITLE
Example Network loadbalancer

### ISSUE THREAD

**Issue by davidsteed** [aws/aws-cdk#4794]
The example https://github.com/aws-samples/aws-cdk-examples/tree/master/typescript/ecs/fargate-load-balanced-service/

does not work

It used to in V1.5.0, but the network load balancer no longer has  a security group attached with ingres and egress properties (it used to in V1.5)

### Reproduction Steps

``` ts
export class NetworkloadbalancerStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);
    const vpc = new ec2.Vpc(this, 'MyVpc', { maxAzs: 2 });
    const cluster = new ecs.Cluster(this, 'Cluster', { vpc });

    // Instantiate Fargate Service with just cluster and image
    const fargateService = new ecs_patterns.NetworkLoadBalancedFargateService(this, "FargateService", {
      cluster,
      taskImageOptions: {
        image: ecs.ContainerImage.fromRegistry("amazon/amazon-ecs-sample"),
      },
    });

    // Output the DNS where you can access your service
    new cdk.CfnOutput(this, 'LoadBalancerDNS', { value: fargateService.loadBalancer.loadBalancerDnsName });
    // The code that defines your stack goes here
  }
}
```

### Error Log

After creating the stack curl the url provided and there is no response

### Environment

  - **CLI Version      :1.15.0
  - **Framework Version:1.15.0
  - **OS               :**
  - **Language         :typescript

### Other

--- 

This is :bug: Bug Report

**Comment by iamhopaul123** [comment]
Not sure if this fixes the bug. Probably should also address this issue in ecs pattern's README.

**Comment by pkandasamy91** [comment]
Resolved in: https://github.com/aws-samples/aws-cdk-examples/pull/155
