### ISSUE TITLE
Firelens taskDefinition with custom-resources "Failed to create resource. Unexpected key 'firelensConfiguration' found in params.containerDefinitions[0]"

### ISSUE THREAD

**Issue by nbrandaleone** [aws/aws-cdk#4799]
### Environment

    CDK CLI Version: 1.15.0
    Module Version: 1.15.0
    OS: OSX Mojave
    Language: TypeScript

### Other

--- 

This is :bug: Bug Report

**Comment by nbrandaleone** [comment]
Code:
------
import cdk = require('@aws-cdk/core');
import customresources = require('@aws-cdk/custom-resources');

export class CdkFirelensStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    // The code that defines your stack goes here
    const FirelensEnabledTask = new customresources.AwsCustomResource(this, 'FirelensEnabledTask', {
      onCreate: {
        service: 'ECS',
        action: 'registerTaskDefinition',
        parameters: {
          "requiresCompatibilities": ["FARGATE"],
          "networkMode": "awsvpc",
          "family": "firelens-demo",
          "cpu": "1024",
          "memory": "2048",
          "containerDefinitions": [
            {
              "essential": true,
              "image": "amazon/aws-for-fluent-bit:latest",
              "name": "log_router",
              "firelensConfiguration": {
                "type": "fluentbit",
                "options": {
                  "enable-ecs-log-metadata": "true"
                }
              },
              "memory": 25
            },
            {
              "essential": true,
              "image": "nginx",
              "name": "app",
              "portMappings": [
                {
                  "hostPort": 80,
                  "protocol": "tcp",
                  "containerPort": 80
                }],
              "logConfiguration": {
                "logDriver": "awsfirelens",
                "options": {
                  "Name": "cloudwatch",
                  "region": "us-east-1",
                  "log_group_name": "firelens-testing-fluent-bit",
                  "log_stream_prefix": "from-fluent-bit"
                }
              },
              "memory": 100,
              "dependsOn": [
                {
                "containerName": "log_router",
                "condition": "START"
                }
              ]
            }
          ]
        },
        physicalResourceIdPath: 'taskDefinition.taskDefinitionArn'
      },
    });

  const taskArn = FirelensEnabledTask.getData('taskDefinition.taskDefinition');

  new cdk.CfnOutput(this, 'NewTaskArn', {
    value: taskArn.toString()
  })

  }
}

**Comment by PettitWesley** [comment]
@nbrandaleone do you know what version of the SDK is being used [here](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/custom-resources/lib/aws-custom-resource-provider/index.ts)?

My understanding is that the custom resource provider uses the SDK to register the Task Definition; the error you're getting looks like the sort of error you'd get if you were using an old SDK version without FireLens support. The ECS API wouldn't output an error like this.

I'm not sure how to check which version of the SDK would be in use. @pkandasamy91 Do you know?

**Comment by jogold** [comment]
It's version `2.488.0`, the one available in the Node.js 10 runtime (https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html).

**Comment by PettitWesley** [comment]
That's the problem then [2.488.0](https://github.com/aws/aws-sdk-js/releases/tag/v2.488.0) is from July; SDK support for FireLens was released on August 30th if I remember correctly.

**Comment by nbrandaleone** [comment]
I am going to close the issue.  I have confirmed that the default node runtime is too old, and does not have the updated AWS SDK.  The solution, until the runtime is updated, is to use a custom lambda script/runtime with the latest SDK embedded.
