### ISSUE TITLE
Missing CodePipeline S3Deploy capability (Canned ACL)

### ISSUE THREAD

**Issue by ColWillis** [aws/aws-cdk#4800]
Hi all,

I have a Java CDK CodePipeline project that Deploys an SPA to a Bucket, it works, but the CDK does not have the Canned ACL Advanced Configuration properties. So I have to manually change this setting in CodePipeline after CDK is executed (v bad)

### Use Case

User should be able to deploy a SPA to a Bucket and have it automatically public-read

### Proposed Solution

CDK development for the Canned ACL option in the CodePipeline S3Deploy Action

### Other

Please see attached screenshots of:

1. Java CDK S3DeployActionProps.Builder available Methods
2. CodePipeline S3 Deploy Action desired new options

---

I cannot be the first person to request this?! (I have searched, but unable to find anything)

![CodePipelineS3DeployAction](https://user-images.githubusercontent.com/15360237/67988889-32580a00-fc29-11e9-8a7c-7abb1486b9a6.jpg)

![S3DeployActionPropsBuilder](https://user-images.githubusercontent.com/15360237/67988890-3421cd80-fc29-11e9-82d3-8c289bb90e14.jpg)

Big thx in advance!

**Comment by skinny85** [comment]
Hi @ColWillis ,

thanks for the issue. We have a [PR open](https://github.com/aws/aws-cdk/pull/3466) adding this support, although I have plans to take it over, as it haven't seen any activity in a while.

**Comment by skinny85** [comment]
This was done in # 5698 🙂

**Comment by chandrakala-adsk** [comment]
Do we have this supported with Cloud-formation template?

**Comment by skinny85** [comment]
@chandrakala-adsk I don't understand your question, sorry.

**Comment by chandrakala-adsk** [comment]
@skinny85 sorry for that
I am setting up my code pipeline with CFN template. My pipeline is to do a build and upload the artifacts to S3 bucket. While uploading the artifacts to S3 bucket I want to update the file permissions to Public Read. I am looking for an option how can I achieve this in CFN template instead I go and manually update the Canned ACL
here is my CFN 
 Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Location: !Ref 'S3BucketName'
        Type: S3
      Name: !Sub '${AWS::StackName}-pipeline'
      RoleArn: !GetAtt 'PipelineExecutionRole.Arn'
      Stages:
        - Name: Source
          Actions:
            - Name: DownloadCodeZip
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: S3
                Version: '1'
              Configuration:
                S3Bucket: !Ref 'S3BucketName'
                S3ObjectKey:
                  Fn::Sub:
                    - '${RepoName}/${GitBranch}/bundle.zip'
              OutputArtifacts:
                - Name: SourceZip
              RunOrder: 1
        - Name: app-build
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName: !Ref 'AppCodeBuildProject'
              InputArtifacts:
                - Name: SourceZip
              OutputArtifacts:
                - Name: !Sub '${ServiceStackName}AppBuildOutput'
              RunOrder: 1
        #- Name: dev-app-deploy
         # This is the prd deployment
        - Name: Deploy
          Actions:
            **### - Name: StgS3Upload**
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: S3
                Version: 1
              Configuration:
                BucketName: !Ref 'TargetBucket'
                **### #ACL: "PublicRead"**
                Extract: true
              InputArtifacts:
                - Name: !Sub '${ServiceStackName}AppBuildOutput'
              RunOrder: 1
