### ISSUE TITLE
aws-stepfunctions-tasks: Confusion between RunLambdaTask and InvokeFunction

### ISSUE THREAD

**Issue by otterley** [aws/aws-cdk#4801]
There are now two similar-looking constructs in aws-stepfunctions-tasks pertaining to Lambda tasks, and it's not clear which one to use.

Users who are used to historical Step Functions patterns and want things to easily work should use `InvokeFunction`.  However, there are some corner cases where people want special behavior (e.g., asynchronous execution) who like to use `RunLambdaTask`.

If you mix these up, be prepared to spend a lot of time debugging.  @ccfife and I spent the afternoon scratching our heads to figure out, when we accidentally used `RunLambdaTask`, why the event payload being sent to our Lambda function Tasks was an empty event.

Let's do something to disambiguate these and make clear when a user should use one or the other.

**Comment by rix0rrr** [comment]
I'm open to ideas for good verbiage to put in the class descriptions.

**Comment by rix0rrr** [comment]
Or the README

**Comment by sacag** [comment]
Since I am getting obsolete warning on InvokeFunction(this has been working fine for us), we moved to RunLambdaTask. Since then we have been receiving null ref exception in the lambda function. Seems like the payload passed to lambda function is null. Any thoughts? @rix0rrr @otterley The code with InvokeFunction looked like this:
I am using C#
`
 var postToApiTask = new Task(scope, $"{props.UniqueFunctionSuffix}-PostAPI-Task", new TaskProps
            {
                Task = new InvokeFunction(props.PostToAPILambda), //this is the lambda function
                InputPath = "$",
                ResultPath = "$.data.lambdaResult",
                Comment = "This task invokes API endpoint",
                Timeout = Duration.Seconds(30)
            });
`
I just replace InvokeFunction with RunLambdaTask. I tried setting some properties as well, but no luck.

**Comment by shivlaks** [comment]
@sacag can you share the code that you were using when you converted to `RunLambdaTask`? which properties did you set?

Did you set the [IntegrationPattern](https://docs.aws.amazon.com/cdk/api/latest/dotnet/api/Amazon.CDK.AWS.StepFunctions.Tasks.RunLambdaTaskProps.html#Amazon_CDK_AWS_StepFunctions_Tasks_RunLambdaTaskProps_IntegrationPattern) property? Wondering if it's the default of `FIRE_AND_FORGET` that's biting you here. 

In TypeScript it would look something like this:
```ts
  task: new tasks.RunLambdaTask(postToAPILambda, {
    integrationPattern: sfn.ServiceIntegrationPattern.WAIT_FOR_TASK_TOKEN,
    payload: {
      token: sfn.Context.taskToken
    }
  }),
  inputPath: '$',
  resultPath: '$.lambdaResult',
  comment: 'This task invokes API endpoint',
  timeout: Duration.seconds(30)
});
```

**Comment by sacag** [comment]
@shivlaks - I did not set the IntegrationPattern property. Also, my lambda function is not returning any token or anything of that sort. Below is how my C# code looks like:
`var postToApiTask = new Task(scope, $"{props.UniqueFunctionSuffix}-PostAPI-Task", 
         new TaskProps { Task = new InvokeFunction(postToAPILambda), //this is the lambda function 
                             InputPath = "$", ResultPath = "$.data.lambdaResult", 
                            Comment = "This task invokes API endpoint", 
                               Timeout = Duration.Seconds(30) });`

**Comment by sacag** [comment]
@shivlaks - I tried Context.EntireContext, Context.TaskToken..still same issue
`var applyFilterTransformTask = new Task(scope, $"{props.UniqueFunctionSuffix}-FilterTransform-Task", new TaskProps
            {
                Task = new RunLambdaTask(props.FilterTransformLambda, 
                        new RunLambdaTaskProps { IntegrationPattern = ServiceIntegrationPattern.WAIT_FOR_TASK_TOKEN, 
                                                Payload = new Dictionary<string, object>() { { "input",Context.EntireContext} } }),
                Comment = $"This task applies source/destination filters to {props.UserFriendlyTopicName} Message and also Transforms it",
                InputPath = "$",
                ResultPath = "$.data.lambdaResult",
                OutputPath = "$.data.lambdaResult",
                Timeout = Duration.Minutes(15),                
            });`

**Comment by sacag** [comment]
![image](https://user-images.githubusercontent.com/9053257/79244992-7f314500-7e45-11ea-8a53-2d583002fe14.png)
@shivlaks

**Comment by sacag** [comment]
@shivlaks - finally got it to work with the below code:
`new RunLambdaTask(props.PostToAPILambda,new RunLambdaTaskProps { Payload = new Dictionary<string, object>() { { "input", Context.StringAt("$$.Execution.Input") } } })`

**Comment by sacag** [comment]
@shivlaks, @rix0rrr  - I am seeing more issues with RunLambdaTask:
below is the code which works with InvokeFunction..$.Payload has my model in json string
```
 Task = new InvokeFunction(lambdaFunction),                
                InputPath = "$.Payload",
                ResultPath = "$.lambdaResult",
                OutputPath = "$.lambdaResult"
```
The same code when using RunLambdaTask...not sure how to access $.Payload in the Payload parameter, so that it can be passed over to the Lambda function? This is what I have

```
Task = new RunLambdaTask(lambdaFunction,
                            new RunLambdaTaskProps 
{ Payload = new Dictionary<string, object>() { { "lambdaResult", Context.StringAt("$$.Payload") } } }),
                InputPath = "$.Payload",
                ResultPath = "$.lambdaResult",
                OutputPath = "$.lambdaResult"
```
   When I do Context.StringAt(...) in RunLambdaTask, i think it takes the execution's input and not the task input..i think, maybe there is another way to access the TaskState input?
