### ISSUE TITLE
cdk.json does not properly merge

### ISSUE THREAD

**Issue by rwalker777** [aws/aws-cdk#4802]
If you place a context variable in ~/.cdk.json it is read and shows in the merged settings in verbose output from cdk synth.  However it is discarded in the final context.

### Reproduction Steps

place something like the below in ~/.cdk.json (makes sure it's not in cdk.json):
{
  "context": {
     "userName": "bob"
  }
}

### Error Log

The final context output will not contain the ~/.cdk.json values.

### Environment

  - **CLI Version      :**
  - **Framework Version:**
  - **OS               :**
  - **Language         :**

### Other

--- 

This is :bug: Bug Report

**Comment by shivlaks** [comment]
Reproduced issue where merged settings are not being utilized by the CLI.
Looking into a fix

**Comment by bitbauer** [comment]
Duplicate #10823 of merging context from ~/.cdk.json 
(... where I have added a PR)

**Comment by bitbauer** [comment]
@shivlaks can you please link PR #12394 ?
