### ISSUE TITLE
CDK fails when the STS token is expired during deploy operation

### ISSUE THREAD

**Issue by YiannisH** [aws/aws-cdk#4804]
### Description of the bug
I ran **cdk deploy** and suddenly the VScode command line outputted a **name.endsWith is not a function** error.

The cloudformation stack did not stop its execution and continued and finally finished successfully.

### Reproduction Steps
This is the tricky part as you need to run cdk deploy just in time that the STS token will expire.

### Error Log

what is the error message you are seeing?
Reading existing template for stack cdk-dummy-stack.
Using default AWS SDK credentials for account 328381275688
cdk-dummy-stack: deploying...
Waiting for stack CDKToolkit to finish creating or updating...
Using default AWS SDK credentials for account 328381275688
s3://cdktoolkit-dummybucketname/cdk/cdk-dummy-stack/03941d08ed2013ea62a2e3b015bf1931639d7b8eb1f41b750e1437a2dd674f42.yml: checking if already exists
s3://cdktoolkit-dummybucketname/cdk/cdk-dummy-stack/03941d08ed2013ea62a2e3b015bf1931639d7b8eb1f41b750e1437a2dd674f42.yml: uploading
s3://cdktoolkit-dummybucketname/cdk/cdk-dummy-stack/03941d08ed2013ea62a2e3b015bf1931639d7b8eb1f41b750e1437a2dd674f42.yml: upload complete
Stored template in S3 at: https://cdktoolkit-dummybucketname.s3.amazonaws.com/cdk/cdk-dummy-stack/03941d08ed2013ea62a2e3b015bf1931639d7b8eb1f41b750e1437a2dd674f42.yml
Attempting to create ChangeSet CDK-254c2ad6-9c32-4161-9195-c2f9865f6f69 to create stack cdk-dummy-stack
cdk-dummy-stack: creating CloudFormation changeset...
Initiated creation of changeset: arn:aws:cloudformation:eu-central-1:328381275688:changeSet/CDK-254c2ad6-9c32-4161-9195-c2f9865f6f69/1a66cc57-7e48-4ffc-8634-fdab360ca0ed; waiting for it to finish creating...
Waiting for changeset CDK-254c2ad6-9c32-4161-9195-c2f9865f6f69 on stack cdk-dummy-stack to finish creating...
Changeset CDK-254c2ad6-9c32-4161-9195-c2f9865f6f69 on stack cdk-dummy-stack is still creating
Initiating execution of changeset CDK-254c2ad6-9c32-4161-9195-c2f9865f6f69 on stack cdk-dummy-stack
Execution of changeset CDK-254c2ad6-9c32-4161-9195-c2f9865f6f69 on stack cdk-dummy-stack has started; waiting for the update to complete...
Waiting for stack cdk-dummy-stack to finish creating or updating...
Stack cdk-dummy-stack is still not stable (CREATE_IN_PROGRESS)
Stack cdk-dummy-stack is still not stable (CREATE_IN_PROGRESS)
Stack cdk-dummy-stack is still not stable (CREATE_IN_PROGRESS)
Stack cdk-dummy-stack is still not stable (CREATE_IN_PROGRESS)
Stack cdk-dummy-stack is still not stable (CREATE_IN_PROGRESS)
Stack cdk-dummy-stack is still not stable (CREATE_IN_PROGRESS)
Stack cdk-dummy-stack is still not stable (CREATE_IN_PROGRESS)
Stack cdk-dummy-stack is still not stable (CREATE_IN_PROGRESS)
Stack cdk-dummy-stack is still not stable (CREATE_IN_PROGRESS)
(node:11380) UnhandledPromiseRejectionWarning: TypeError: name.endsWith is not a function
    at formatError (internal/util/inspect.js:914:13)
    at formatRaw (internal/util/inspect.js:703:14)
    at formatValue (internal/util/inspect.js:591:10)
    at inspect (internal/util/inspect.js:221:10)
    at formatWithOptions (internal/util/inspect.js:1608:29)
    at Object.format (internal/util/inspect.js:1543:10)
    at Object.error (C:\Users\yhadjicharalambous\AppData\Roaming\npm\node_modules\aws-cdk\lib\logging.ts:13:33)
    at StackActivityMonitor.tick (C:\Users\yhadjicharalambous\AppData\Roaming\npm\node_modules\aws-cdk\lib\api\util\cloudformation\stack-activity-monitor.ts:131:7)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:11380) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11380) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate
the Node.js process with a non-zero exit code.
name.endsWith is not a function
TypeError: name.endsWith is not a function
    at formatError (internal/util/inspect.js:914:13)
    at formatRaw (internal/util/inspect.js:703:14)
    at formatValue (internal/util/inspect.js:591:10)
    at inspect (internal/util/inspect.js:221:10)
    at formatWithOptions (internal/util/inspect.js:1608:29)
    at Object.format (internal/util/inspect.js:1543:10)
    at Object.error (C:\Users\yhadjicharalambous\AppData\Roaming\npm\node_modules\aws-cdk\lib\logging.ts:13:33)
    at CdkToolkit.deploy (C:\Users\yhadjicharalambous\AppData\Roaming\npm\node_modules\aws-cdk\lib\cdk-toolkit.ts:173:9)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

### Environment

  - **CLI Version      : aws-cli/1.16.268 Python/3.8.0 Windows/10 botocore/1.13.4**
  - **Framework Version: 1.15.0**
  - **OS               : Windows10/VSCode/Git Bash**
  - **Language         : Typescript**

--- 

This is :bug: Bug Report

**Comment by SomayaB** [comment]
Hi @YiannisH,  thanks for reporting this. We will update this issue when there is  movement. If anyone wants to put in a PR, this is a good first issue and it would be much appreciated! 👍
