### ISSUE TITLE
Using getAtt that returns a list within a string that is joined in the generated template throws an error

### ISSUE THREAD

**Issue by gresham-Carling** [aws/aws-cdk#4808]
When referencing an attribute on a construct, that is then used within a joined string in the generated template, the generated template fails validation. In my use case, I am trying to retrieve the DNS IP addresess from a created directory and subsitute them into a file.

### Reproduction Steps
Code that is performing the substitution:

       let script = readFileSync(resolve(__dirname, "../windows/join_domain.ps1")).toString();

        const subs = {
            "#{SECRET_ID}": msad_secret.secretArn,
            "#{DNS_ADDRESSES}": String(ms_ad.getAtt("DnsIpAddresses"))
        };

        Object.entries(subs).forEach(
            ([key, value]) => script = script.replace(key, String(value))
        );

The generated template snippet that fails validation:
               
              Set-DnsClientServerAddress -InterfaceIndex $output.InterfaceIndex -ServerAddresses ("
              - Fn::GetAtt:
                  - directory
                  - DnsIpAddresses
              - >-
                ")

### Error Log

Template error: every Fn::Join object requires two parameters, (1) a string delimiter and (2) a list of strings to be joined or a function that returns a list of strings (such as Fn::GetAZs) to be joined.

### Environment

  - **CLI Version      : 1.15.0 (build bdbe3aa)
  - **Framework Version: ???
  - **OS               : macOS Catalina (10.15)
  - **Language         : TypeScript

### Other

We are able to manually fix the template for this to work, by joining the list into the string instead using the following snippet:

                Set-DnsClientServerAddress -InterfaceIndex $output.InterfaceIndex -ServerAddresses ("
              - Fn::Join:
                  [",", !GetAtt [directory, DnsIpAddresses]]
              - >-
                ")

If there is a way to get CDK to make the template in this way that I've missed, I'll happily amend my code and close the issue!

This is :bug: Bug Report

**Comment by eladb** [comment]
Hi @gresham-Carling we will need a bit more context to be able to reproduce this... Any chance you can a working minimal repro that demontrates the issue a bit more cleanly? It's hard for me to distill what the issue is from the snippet...

**Comment by gresham-Carling** [comment]
Hey, I realise now my reproduction steps were totally inadequate, here's a stack that should produce the issue:


```
import {App, Stack, StackProps, Tag} from "@aws-cdk/core"
import {
    CfnVPCPeeringConnection,
    Instance,
    InstanceClass,
    InstanceSize,
    InstanceType, Peer, Port, SecurityGroup,
    SubnetType,
    UserData,
    Vpc,
    WindowsImage,
    WindowsVersion
} from "@aws-cdk/aws-ec2";
import {CfnMicrosoftAD} from "@aws-cdk/aws-directoryservice"
import config from "../config/sharing"
import {resolve} from 'path';
import {readFileSync} from "fs";
import {ManagedPolicy, PolicyDocument, Role, ServicePrincipal} from "@aws-cdk/aws-iam";
import {Secret} from "@aws-cdk/aws-secretsmanager";

export class MSADDirectoryBugReplication extends Stack {
    constructor(app: App, id: string, props?: StackProps) {
        super(app, id, props);

        // VPC to house the MSAD
        const vpc = new Vpc(this, 'vpc', {
            cidr: '50.0.0.0/16',
            subnetConfiguration: [
                { name: 'management-private', subnetType: SubnetType.PRIVATE, cidrMask: 24 },
                { name: 'management-public', subnetType: SubnetType.PUBLIC, cidrMask: 24 }
            ]
        });

        const instance_role = new Role(this, 'instance-role', {
            roleName: 'management-instance-role',
            assumedBy: new ServicePrincipal('ec2.amazonaws.com')
        });
        instance_role.addManagedPolicy(ManagedPolicy.fromAwsManagedPolicyName('SecretsManagerReadWrite'));

        const msad_secret = new Secret(this, 'msad-ad-secret', {
            generateSecretString: {
                secretStringTemplate: JSON.stringify({ username: 'Admin' }),
                generateStringKey: 'password'
            }
        });

        const ms_ad = new CfnMicrosoftAD(this, "directory", {
            edition: 'Standard',
            name: 'caas.shared',
            password: msad_secret.secretValueFromJson('password').toString(),
            vpcSettings: {
                subnetIds: vpc.selectSubnets({
                    subnetGroupName: 'management-private',
                    onePerAz: true
                }).subnetIds,
                vpcId: vpc.vpcId
            }
        });

        const startup_data = UserData.forWindows();
        let script = readFileSync(resolve(__dirname, "../windows/join_domain.ps1")).toString();

        const subs = {
            "#{SECRET_ID}": msad_secret.secretArn,
            "#{DNS_ADDRESSES}": String(ms_ad.getAtt("DnsIpAddresses"))
        };

        Object.entries(subs).forEach(
            ([key, value]) => script = script.replace(key, String(value))
        );

        startup_data.addCommands(script);

        new Instance(this, 'management', {
            machineImage: new WindowsImage(WindowsVersion.WINDOWS_SERVER_2019_ENGLISH_FULL_BASE),
            instanceType: InstanceType.of(InstanceClass.T2, InstanceSize.MEDIUM),
            vpc: vpc,
            vpcSubnets: vpc.selectSubnets({
                subnetType: SubnetType.PUBLIC
            }),
            userData: startup_data,
            keyName: 'msad_management',
            role: instance_role
        });
    }
}
```

You'll probably want to change this path:
../windows/join_domain.ps1
To something that works for you.

**Comment by eladb** [comment]
Stale
