### ISSUE TITLE
How to add a chain step to an existing definition of an existing StateMachine?

### ISSUE THREAD

**Issue by Pinny3** [aws/aws-cdk#4811]
Hi there,

I am creating a state machine in one project like this:

` const stateMachine = new sfn.StateMachine(this, 'myStateMachine', {
            definition: chain,
            timeout: cdk.Duration.minutes(2)
        });`

In the other project I get the existing state machine using this:

`const stateMachine = sfn.StateMachine.fromStateMachineArn(this, 'myStateMachine', '<EXISTING_ARN>');`

The question is how to add a new step to the existing chain of the existing state machine.

Can anybody help?

**Comment by rix0rrr** [comment]
You can't. A state machine can only be defined upon creation.
