### ISSUE TITLE
aws-ecr to support onImageScanCompleted()

### ISSUE THREAD

**Issue by pahud** [aws/aws-cdk#4818]
Amazon ECR has [announced](https://aws.amazon.com/about-aws/whats-new/2019/10/announcing-image-scanning-for-amazon-ecr/?nc1=h_ls) the image scanning support and `aws-ecr` should add `onImageScanCompleted()` to trigger the event target from cloudwatch events.

### Use Case

To build a pipeline on image push, scanning on push and notification on scan completed.

More details and demos here: 

https://twitter.com/pahudnet/status/1189556289312935937
and
https://twitter.com/pahudnet/status/1189723775937343488

### Proposed Solution

Add `onImagePushCompleted` in [RepositoryBase](https://github.com/aws/aws-cdk/blob/6e22f262a6266aa6e525f3f43b988f60b1f28481/packages/%40aws-cdk/aws-ecr/lib/repository.ts#L88).

### Other

* [v] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by cmckni3** [comment]
Does adding the `onImageScanCompleted` event to a repository enable scan on push?

**Comment by pahud** [comment]
@cmckni3 Unfortunately, no. Because cloudformation doesn't support it now.  At this moment you need to manually enable it  after repository creation and all scan completed events will be captured. I am thinking maybe we can create a `ecr.enableScanOnPush()` with `custom-resource` implementation then we don't need to wait for the cloudformation native support.

**Comment by cmckni3** [comment]
That would be awesome.

I enabled scan on push via the console.

Thanks!

**Comment by cmckni3** [comment]
sweet, I ended up using a custom resource.
