### ISSUE TITLE
Support Advanced Tier SSM Parameters

### ISSUE THREAD

**Issue by balkat** [aws/aws-cdk#4829]
Add support for the Advanced Tier of SSM parameters, allowing:
* Choice of Tier
* Attachment of Resource Policies

### Use Case

* To avoid having to use Escape Hatches.
* Filling out the gaps in the Constuct interface

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by MrArnoldPalmer** [comment]
Tier support added in #6326, resource policies still needed.
