### ISSUE TITLE
Yarn is missing from the Dockerfile

### ISSUE THREAD

**Issue by arnulfojr** [aws/aws-cdk#4843]
At the moment when trying to use the "Full Docker build" the build fails because the `build.sh` script requires `yarn` to be installed.
This issue most probably relates to the following issue https://github.com/aws/aws-cdk/issues/611

### Reproduction Steps

```bash
docker build -t aws-cdk .
```

### Error Log

The build.sh script fails because it requires yarn installed and the Dockerfile does not install it.

```bash
Step 4/7 : RUN yum -y --security update   && yum install -y     git     rsync     zip     unzip     tar     xz     python3     python3-dev     py3-setuptools   && yum clean all   && rm -rf /var/cache/yum   && curl -fsSLO --compressed "https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-x64.tar.xz"   && curl -fsSLO --compressed "https://nodejs.org/dist/v$NODE_VERSION/SHASUMS256.txt"   && grep " node-v$NODE_VERSION-linux-x64.tar.xz\$" SHASUMS256.txt | sha256sum -c -   && tar -xJf "node-v$NODE_VERSION-linux-x64.tar.xz" -C /usr/local --strip-components=1 --no-same-owner   && ln -s /usr/local/bin/node /usr/local/bin/nodejs   && rm "node-v$NODE_VERSION-linux-x64.tar.xz" SHASUMS256.txt
 ---> Using cache
 ---> 1c649a05764a
Step 5/7 : COPY . .
 ---> ff8fefa17a19
Step 6/7 : RUN ./build.sh  && ./link-all.sh
 ---> Running in 212937f841a6
=============================================================================================
installing...
./build.sh: line 34: yarn: command not found
The command '/bin/sh -c ./build.sh  && ./link-all.sh' returned a non-zero code: 127
```

### Environment

I used the latest in master at the moment.

  - **CLI Version      :**
  - **Framework Version:**
  - **OS               :** `amazonlinux:2`
  - **Language         :**

### Other

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
@RomainMuller @eladb we have a Dockerfile in our repository root. Do we support that? What is it for? Why is its root not superchain?
