### ISSUE TITLE
Removing constructs from a stack

### ISSUE THREAD

**Issue by 3p3r** [aws/aws-cdk#4848]
### The Question

I am trying to remove all auto generated `CfnOutput` constructs from my stack to save some space. I attempted to do this with an aspect, but wanted to see if there is a cleaner solution to achieve this. The question is really, how to remove children from stack's root node given a path? I found ways to add children but not removing them.

```JS
class StackOutputRemover {
  visit(node) {
    // See that we're dealing with a CfnBucket
    if (node instanceof cdk.CfnOutput) {
      // stackName = node.stack.stackName;
      const pathComponents = node.node.path.split(cdk.ConstructNode.PATH_SEP);
      assert.ok(pathComponents.length >= 2, 'invalid construct path found');
      // is path an immediate child of the stack (${stack}/${construct})?
      const isImmediate = pathComponents.length == 2;
      // these are user added constructs, return
      if (isImmediate) return;
      assert.ok(pathComponents.shift() === node.stack.stackName);
      const connector = '.node._children.';
      eval(`delete node.stack${connector}${pathComponents.join(connector)}`);
    }
  }
}
```

### Environment

  - CDK CLI Version: 1.15.0 (build bdbe3aa)
  - Module Version: N/A
  - OS: Ubuntu 18.04
  - Language: JavaScript

### Other information

I am using constructs and abstractions in the `ecs-patterns` module and noticed it auto generates `CfnOutput` constructs for my stack. I do not want them and want to be able to filter them if possible.

**Comment by pasieronen** [comment]
Related to #1408

**Comment by eladb** [comment]
This was added is https://github.com/aws/aws-cdk/pull/5608
