### ISSUE TITLE
Cannot use existing security group with InterfaceVpcEndpoint

### ISSUE THREAD

**Issue by Lightning303** [aws/aws-cdk#4850]
Adding an InterfaceEndpoint to your VPN, in my case Athena, and then calling addSecurityGroup does not add another security group to that endpoint. The endpoint will only have a automatically created security group attached to it.

### Reproduction Steps

```
          const vpc = new ec2.Vpc(this, "vpc", {
            cidr: "10.0.0.0/16",
            maxAzs: 3,
            subnetConfiguration: [
                {
                    cidrMask: 20,
                    subnetType: ec2.SubnetType.PRIVATE,
                    name: "subnet-private"
                },
                {
                    cidrMask: 20,
                    subnetType: ec2.SubnetType.PUBLIC,
                    name: "subnet-public"
                }
            ],
            natGateways: 1,
            enableDnsHostnames: true,
            enableDnsSupport: true
        });

        const sg = new ec2.SecurityGroup(this, "athena", {
            vpc: vpc
        });

        vpc.addInterfaceEndpoint("athena-endpoint", {
            service: {
                name: `com.amazonaws.eu-west-1.athena`,
                port: 443
            },
            subnets: {
                subnetType: ec2.SubnetType.PRIVATE
            }
        }).connections.addSecurityGroup(sg);
```

### Environment

  - **CLI Version      : 1.16.232**
  - **Framework Version: 1.15.0**
  - **OS               : Windows 10 Pro**
  - **Language         : TypeScript**

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
That method is not intended to work like that. There should have been a way to pass a security group into the `add` call.

**Comment by Lightning303** [comment]
Hey,
i agree there should have been a way to pass it directly in the addInterfaceEndpoint method. However how is this method intended to be used?
I was able to workaround this by adding my ingress rules via `endpoint.connections.allowFrom(...)`.

**Comment by rix0rrr** [comment]
That is totally how you're supposed to do it.

**Comment by chefren** [comment]
close?
