### ISSUE TITLE
aws-sns support encrypted topics

### ISSUE THREAD

**Issue by aflinton** [aws/aws-cdk#4853]
SNS supports encrypted topics
SQS supports encrypted queues.
aws-sqs supports encrypted queues
aws-sns does not support encrypted topics

### Use Case

We have the need for end to end encryption by default. i.e. at rest and in flight.
Our basic pattern is a SNS topic feeding SQS queues.
At the moment we have to set up a topic with cdk and then use other means (for example the web-ui) to set it up for encryption.

End to end encryption in flight & at rest

### Proposed Solution

SQS:

    const logQ = new sqs.Queue(this, 'logQ', {
      visibilityTimeout: cdk.Duration.seconds(300),
      encryption: sqs.QueueEncryption.KMS_MANAGED
    });

SNS:

const mainTopic = new sns.Topic(this, 'mainTopic',{
encryption: sns.TopicEncryption.KMS_MANAGED
});

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by aflinton** [comment]
Or even just expose the kms master key e.g.

    const mainMeshTopic = new sns.Topic(this, 'mainMeshTopic',
    {
      kmsMasterKeyId:  snssqskey.keyArn;
    });

**Comment by nija-at** [comment]
Duplicate https://github.com/aws/aws-cdk/pull/5052
