### ISSUE TITLE
Validate that referenced SSM parameters/Secrets exist before deploy

### ISSUE THREAD

**Issue by jogold** [aws/aws-cdk#4855]
When deploying a stack that uses `cdk.SecretValue`, the CDK should validate that the referenced SSM parameters/secrets exist in order to fail early (CF only checks when the specific resources referencing the secret gets created).

### Proposed Solution
Use SDK to check before deploy (+ maybe add a `--validate-parameters` to `synth`?)

The IAM permissions required to deploy a stack referencing secret values will allow to check their existence.

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by eladb** [comment]
This is not something we want to do since it violates the isolation of “synth”, which is expected to be run from isolated build environments without account access

**Comment by jogold** [comment]
Yes, that's why I suggested to do it systematically on `deploy` (where permissions are guaranteed to exist) and only with a flag for `synth`.

**Comment by eladb** [comment]
deploy needs to be kept pure (I.e only use CloudFormation) in order to be able to have broad support for CI/CD systems that utilize CloudFormation.

**Comment by jogold** [comment]
Closing for now.
