### ISSUE TITLE
attach private subnet to existing VPC

### ISSUE THREAD

**Issue by fogfish** [aws/aws-cdk#4858]
Create a private subnet to VPC imported from other stack. It is possible to create a new subnet with `ec2.PrivateSubnet`. However, it is not possible to bind it default NAT route because nat gateways are not accessible outside of VPC class.  

#### Layered stacks

I’ve started with monolith Cloud Formation template that spin off entire infrastructure: networking gears, load balancers, compute resources, etc. The maintainability of it becomes a headache. It might even lead you to situation when you cannot apply updates without a downtime. Therefore, you have to split you solution for few independent layers - VPC networking shall be deployed in its own template.

The networking stack is deployed once per environment (e.g. dev, live). The deployment of The deployment of AWS resources in this design is grouped by unique routing requirement and deployed to appropriates subnets. 

**Existing** AWS CDK supports this use case

```typescript
// StackA
const vpc = new ec2.Vpc(this, 'Vpc', {/* config */})

// StackB
const vpc = /* ... pass VPC as props using multi-stack  */
```

The problem arise when we need to create a Private Subnet in StackB and ensure that subnet has internet connectivity via NAT.

```typescript
const subnet = new ec2.PrivateSubnet(this, 'MySubnet', {/* ... */})

subnet.addDefaultNatRoute(/* we are not able to add NAT here */)
``` 

The VPC class do not expose NAT GW!

### Proposed Solution

Indirectly Export natGatewayByAZ property, add method to VPC class.

```typescript
vpc.natGateway(az: string): string
```

```typescript
const gw = vpc.natGateway(vpc.availabilityZones[0])
subnet.addDefaultNatRoute(gw)
```

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by SamStephens** [comment]
Am I missing something here, or has the original issue not actually been addressed?

Yes, you can now make `NatProvider` configure NAT for a subnet created outside of a VPC. But that does not help if you're operating across two entirely separate CDK applications.

My scenario is that I was hoping to declare a VPC in one stack, and import it and add more subnets to it in another stack.

```
        vpc = ec2.Vpc.from_lookup(
            scope=self,
            id="VpnVpc",
            vpc_name="VpnVpcStack/VpnVpc",
        )

        task_subnets = [
            ec2.PrivateSubnet(
                scope=self,
                id="TestCdkSubnet1",
                vpc_id=vpc.vpc_id,
                availability_zone="us-west-2a",
                cidr_block="10.16.255.0/26",
            ).add_default_nat_route,
            ec2.PrivateSubnet(
                scope=self,
                id="TestCdkSubnet2",
                vpc_id=vpc.vpc_id,
                availability_zone="us-west-2b",
                cidr_block="10.16.255.64/26",
            ),
            ec2.PrivateSubnet(
                scope=self,
                id="TestCdkSubnet3",
                vpc_id=vpc.vpc_id,
                availability_zone="us-west-2c",
                cidr_block="10.16.255.128/26",
            ),
        ]
```

But now I have no way I can see to get a `NatProvider` instance for the imported VPC to add the subnets to.
