### ISSUE TITLE
AWS Lambda to Amazon DynamoDB Construct

### ISSUE THREAD

**Issue by hnishar** [aws/aws-cdk#4859]
Higher-level multi-service (L3) patterns construct for AWS Lambda to Amazon DynamoDB that follows a common architectural pattern.

### Use Case
This construct is designed to provide common pattern of deploying a Lambda function with the least privilege permission to read and write data to a DynamoDB table. The construct can optionally use an existing Lambda function so it can be used by other higher-level constructs e.g. IoT -> Lambda -> DynamoDB or API Gateway -> Lambda -> DynamoDB in future.

### Proposed Solution
Add a new construct to the CDK library under @aws-cdk/aws-solution-patterns The API for the construct will allow for the user to provide the input properties for Lambda function and DynamoDB table. The user provided properties will override any default properties set by the construct. Additionally users can pass an existing Lambda function object if they wish to not deploy a new function but instead use an existing function.

A minimal deployable pattern definition will look like:

```
const { LambdaToDynamoDB } = require('@aws-cdk/aws-solution-patterns');

new LambdaToDynamoDB(stack, 'LambdaToDynamoDB', {
  deployLambda: true,
  lambdaFunctionProps: {
    code: lambda.Code.fromAsset(path.join(__dirname, 'lambda/handler.zip')),
    runtime: lambda.Runtime.NODEJS_10_X,
    handler: 'index.handler'
  }
});
```

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by nija-at** [comment]
Closing this issue based on offline discussion around solution-patterns and their fit in the CDK.
