### ISSUE TITLE
ecs-patterns - listenerPort for HTTPS with ALB might listen on 80 not 443

### ISSUE THREAD

**Issue by pahud** [aws/aws-cdk#4861]
https://github.com/aws/aws-cdk/blob/47124bf36cb2da1b88b4e74d266a113f4134b58b/packages/%40aws-cdk/aws-ecs-patterns/lib/base/application-load-balanced-service-base.ts#L276-L288

As `this.loadBalancer.addListener` didn't specify the port, if a user is running HTTPS service the listener might be running on 80 not 443.

More discussion here:
https://github.com/aws/aws-cdk/pull/4825/files/a1a1a5112f33fab484abdd98f23e7ec71232b7ab#r342650081

### Environment

  - **CLI Version      :** 1.15.0
  - **Framework Version:**  1.15.0
  - **OS               :** Mac OS X
  - **Language         :** TypeScript

### Other

--- 

This is :bug: Bug Report

**Comment by pkandasamy91** [comment]
This is not an issue, the application-listener actually initializes the port to be either 80 or 443 if one is not specified, based on the protocol. If the protocol is HTTP, the port is 80 and if the protocol is HTTPS the port is 443. 

As per: https://github.com/aws/aws-cdk/blob/20b8e5dd6e3030bcc6f139f2fa07658d65cf77d4/packages/%40aws-cdk/aws-elasticloadbalancingv2/lib/shared/util.ts#L54
