### ISSUE TITLE
Amazon API Gateway to AWS Lambda Construct

### ISSUE THREAD

**Issue by hayesry** [aws/aws-cdk#4864]
Higher-level multi-service (L3) patterns construct for Amazon API Gateway to AWS Lambda that follows a common architectural pattern.

### Use Case

This construct is designed to provide a common pattern for deploying an API Gateway with the appropriate integration characteristics to interact with an AWS Lambda function. The construct can optionally accept an existing Lambda function for use with other higher-level constructs e.g. CloudFront -> API Gateway -> Lambda or API Gateway -> Lambda -> DynamoDB in future.

### Proposed Solution

Add a new construct to the CDK library under @aws-cdk/aws-solution-patterns. The API for the construct will allow for the user to provide the input properties for the API Gateway and Lambda function. Any user-provided properties will override any default properties set by the construct. Additionally, users can pass an existing Lambda function object if they wish to use an existing function instead of deploying a new one.

A minimal deployable pattern definition will look like:
```
const { ApiGatewayToLambda } = require('@aws-cdk/aws-solution-patterns');

new ApiGatewayToLambda(stack, 'ApiGatewayToLambda', {
  deployLambda: true,
  lambdaFunctionProps: {
    code: lambda.Code.fromAsset(path.join(__dirname, 'lambda/handler.zip')),
    runtime: lambda.Runtime.NODEJS_10_X,
    handler: 'index.handler'
  }
});
```

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rhboyd** [comment]
How would this construct be different from the [LambdaRestApi](https://github.com/aws/aws-cdk/blob/52b136b34ad5dd14131bdf856ec57c20bc75bb19/packages/%40aws-cdk/aws-apigateway/lib/lambda-api.ts#L44)?

**Comment by hayesry** [comment]
@rhboyd This would be a multi-service L3 construct to allow builders to deploy an API Gateway and a Lambda function as a repeatable pattern, in addition to the LambdaRestApi construct. It will also set the default input properties for the API Gateway and Lambda function constructs, which can be overridden by the builder. This construct can be part of the builder's CDK stack/application or other L3 constructs e.g. API Gateway -> Lambda -> DynamoDB.

**Comment by jamiepmullan** [comment]
@hayesry 
Just a suggestion/opinion... but is this more sensible to do in your own code? AWS provide the resources... how you want to implement/template them together is up to you? I've done something similar built from custom constructs and classes.

**Comment by nija-at** [comment]
Per conversation with @hnishar, @hayesry  and others, these patterns are not going to live in the CDK repository. 

Closing this issue.
