### ISSUE TITLE
Incorrect example of SNS Lambda subscription

### ISSUE THREAD

**Issue by ovchinnikov** [aws/aws-cdk#4879]
Hi! It seems that method _sns.Topic.subscribeLambda_ was removed in [this PR ](https://github.com/aws/aws-cdk/pull/2804) but [example](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-sns-readme.html#filter-policy) from documentation  use old way to configure lambda subscription

**Comment by rix0rrr** [comment]
Good call.

The example can be found here. Could you see your way to correcting it?

https://github.com/aws/aws-cdk/edit/master/packages/@aws-cdk/aws-sns/README.md

Thanks!

**Comment by hong823** [comment]
Created PR #5060 for the fix.
