### ISSUE TITLE
Failure adding  a stream of the DynamoDB regional table as an event source to a lambda function

### ISSUE THREAD

**Issue by dpllpd** [aws/aws-cdk#4882]
Incorrect error message "Error: Stack "my-great-stack-id" cannot consume a cross reference from stack "my-great-table-id/my-great-table-id-us-east-1". Cross stack references are only supported for stacks deployed to the same environment or between nested stacks and their parent stack" when creating a global DynamoDB table and signing up a lambda function to listen to a stream coming from a local regional table

##### The code below fails to synthesize:
```typescript
import cdk = require("@aws-cdk/core");
import { AttributeType } from "@aws-cdk/aws-dynamodb";
import { GlobalTable } from "@aws-cdk/aws-dynamodb-global";
import { InlineCode } from "@aws-cdk/aws-lambda";
import {
  DynamoEventSource,
  DynamoEventSourceProps
} from "@aws-cdk/aws-lambda-event-sources";
import lambda = require("@aws-cdk/aws-lambda");

const app = new cdk.App();

export class MyGreatStack extends cdk.Stack {
  constructor(app: cdk.App, id: string, props?: cdk.StackProps) {
    super(app, id, props);

    const globalTable = new GlobalTable(app, "my-great-table-id", {
      partitionKey: { name: "hashKey", type: AttributeType.STRING },
      tableName: "my-great-table-name",
      regions: ["us-east-1", "us-west-2"]
    });

    const handler = new lambda.Function(this, "my-great-function-id", {
      runtime: lambda.Runtime.NODEJS_8_10,
      code: new InlineCode("will never run"),
      handler: "my-handler"
    });

    const eventSourceProps: DynamoEventSourceProps = {
      startingPosition: lambda.StartingPosition.LATEST,
      batchSize: 10
    };

    handler.addEventSource(
      new DynamoEventSource(globalTable.regionalTables[0], eventSourceProps)
    );
  }
}

console.log("Starup");
new MyGreatStack(app, "my-great-stack-id", {
  env: {
    account: "123456789012",
    region: "us-east-1"
  }
});
app.synth();
console.log("Done");
```
##### But
If I remove the account reference from the environment when creating the stack:
```typescript
new MyGreatStack(app, "my-great-stack-id", {
  env: {
//    account: "123456789012",
    region: "us-east-1"
  }
});
```
it will work. I'm not talking about other issues that currently exist with global tables of dynamodb, I'm talking about just the synthesis part.
### Error Log
>/Users/dlief/dpl/devel/cvent/jnk/globaltable/node_modules/@aws-cdk/core/lib/stack.js:702
            throw new Error(`Stack "${this.node.path}" cannot consume a cross reference from stack "${target.node.path}". ` +
            ^

>Error: Stack "my-great-stack-id" cannot consume a cross reference from stack "my-great-table-id/my-great-table-id-us-east-1". Cross stack references are only supported for stacks deployed to the same environment or between nested stacks and their parent stack
>    at MyGreatStack.determineCrossReferenceFactory (/Users/dlief/dpl/devel/cvent/jnk/globaltable/node_modules/@aws-cdk/core/lib/stack.js:702:19)
>    at MyGreatStack.prepare (/Users/dlief/dpl/devel/cvent/jnk/globaltable/node_modules/@aws-cdk/core/lib/stack.js:455:34)
>    at Function.prepare (/Users/dlief/dpl/devel/cvent/jnk/globaltable/node_modules/@aws-cdk/core/lib/construct.js:87:27)
>    at Function.synth (/Users/dlief/dpl/devel/cvent/jnk/globaltable/node_modules/@aws-cdk/core/lib/construct.js:51:14)
>    at App.synth (/Users/dlief/dpl/devel/cvent/jnk/globaltable/node_modules/@aws-cdk/core/lib/app.js:71:52)
>    at Object.<anonymous> (/Users/dlief/dpl/devel/cvent/jnk/globaltable/gt.js:38:5)
>    at Module._compile (internal/modules/cjs/loader.js:936:30)
>    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
>    at Module.load (internal/modules/cjs/loader.js:790:32)
>    at Function.Module._load (internal/modules/cjs/loader.js:703:12)

### Environment
cdk 1.15.0

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hey @dpllpd ,

thanks for reporting the issue, but this behavior seems very natural to me.

Global DynamoDB requires you to provide specific regions your table will be in. If you don't provide the same region in your main stack, the CDK has no way of knowing that they are the same - in fact, they can be completely different, depending on your AWS configuration. So the error message is right here - if we don't know whether 2 things will be in the same region, we can't  easily reference them , as DynamoDB streams do not have physical names we can use (so we cannot just use an ARN for a reference that is cross-region).

Hope this answers your question!

Thanks,
Adam

**Comment by skinny85** [comment]
Oh, I see the problem. It's that the account is not inherited in the GlobalTable construct!

Scratch what I said above ;p. Will fix!

**Comment by dpllpd** [comment]
That's great, thank you so much. What's the ETA on this? 

David

**Comment by skinny85** [comment]
It should be released with `1.18.0` which will be published 2 weeks from now (next week is re:Invent, so we won't have a release that week).

**Comment by dpllpd** [comment]
Isn't 1.18.0 already out?

**Comment by skinny85** [comment]
Damn. I meant `1.19.0` ;p
