### ISSUE TITLE
Need to add base path to existing custom domain on api gatway. 

### ISSUE THREAD

**Issue by devarpi** [aws/aws-cdk#4887]
DomainName.fromDomainNameAttributes gives a way to add  existing custom domain for my new api. I would like to add base path mapping for this new api. 

### Use Case

We do not want to have multiple custom domain for our apis. As we develop, we want to add new apis with different base path under same custom domain, so we can brand our api for partners under same custom domain.

### Other

Like DomainName.fromDomainNameAttributes, there should be method to associate existing custom domain with new api with unique custom domain.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by devarpi** [comment]
Hi Guys, Sorry at the same time, It's stopping me to move forward with CDK for our implementation. I would really appreciate if you have any work around or a way forward for this request.

**Comment by nija-at** [comment]
I don't think I understand your issue/ask here. 

You should be able to add a base path mapping to your imported domain name using the [`BasePathMapping`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-apigateway.BasePathMapping.html) construct.

Could you describe more in detail what it is that you're trying and unable to do?

**Comment by devarpi** [comment]
So we have custom domain created for our API platform. And we want to add more apis under same custom domain as we build. Kind of branding our all api under same domain. Is BasePathMapping construct going to allow me to add and existing custom domain? If so I would appreciate if you have sample, I tried few things and that didn't work.

**Comment by nija-at** [comment]
We have some examples in our [documentation](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-apigateway/README.md#custom-domains) and in our [integ tests](https://github.com/aws/aws-cdk/blob/52b136b34ad5dd14131bdf856ec57c20bc75bb19/packages/%40aws-cdk/aws-apigateway/test/test.domains.ts#L97).

I would suggest to go read up on APIGateway documentation to see whether they have what you're looking for and what combination of APIGateway's primitives satisfies that.

CDK's role is here to make it easier to use AWS service, of which APIGateway is one. Closing this issue; re-open if you have a CDK issue.

**Comment by devarpi** [comment]
Sorry, I have looked at those already and issue with that is, it created new custom domain than allowing me to add new base path to existing custom domain.

**Comment by mbsimonovic** [comment]
Hey @devarpi  you figured this out?

**Comment by mbsimonovic** [comment]
this is doable with CloudFormation:

```
  NewApiGatewayBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      BasePath: your-new-basepath-here
      DomainName:
        Fn::ImportValue:
          Fn::Sub: ExistingCustomApiGatewayDomainName
      RestApiId:
        Ref: NewApiGateway
```
Now I'm trying to figure out how to get this with CDK, but dont see how `DomainName.fromDomainNameAttributes` can be used because it returns the interface `IDomainName`, which doesn't have `addBasePathMapping` method. Any suggestions?

**Comment by mbsimonovic** [comment]
Can someone post an example on how to use `DomainName.fromDomainNameAttributes` to fetch an existing domain and add a new base path mapping?

**Comment by devarpi** [comment]
Sorry for the late reply, I am on vacation after reInvant , will surely
look in to this and share, have learnt new technics to create custom
solution, that will help to fix this.
I really think this is an issue that needs to be resolved soon.

**Comment by devarpi** [comment]
Sorry for late reply. Here is the solution that worked.

   //Get custom domain from attribute
    const domainName = DomainName.fromDomainNameAttributes(this,
        `${envName}-${appName}-${YOUR_DOMAIN_NAME}`, {
        domainName: `${YOUR_DOMAIN_NAME}`,
        domainNameAliasTarget: `${domainNameAliasTarget}`,       // GET from Route 53- I would prefer having this property as optional
        domainNameAliasHostedZoneId: `${domainNameAliasHostedZoneId}` // GET from Route 53- I would prefer having this property as optional
    });


    //Rest API
    const api = new apiGateway.RestApi(this, `${envName}-${appName}`,
    {
        restApiName: `${envName}-${apiName}`,
        deployOptions: { stageName: envName }
    });



    //Used in custom domain
    const pathMapping = new BasePathMapping(this,
        `${envName}-${appName}-path-mapping`, {
        basePath: `${appName}-${envName}`,
        domainName: domainName,
        restApi: api
    });

**Comment by devarpi** [comment]
I started getting https://github.com/aws/aws-cdk/issues/5794 when upgraded cdk (1.25.0)

Ended up fixing as recommended on the issue page above.

 //BASE Path already exists issue with following 
                  
                    // //Used in custom domain
                    // const pathMapping = new BasePathMapping(this,
                    //     `${envName}-${appName}-path-mapping`, {
                    //     basePath: `${appName}-${envName}`,
                    //     domainName: domainName,
                    //     restApi: api
                    // });

                    //fix by CFNBasePathMapping.
                    new apiGateway.CfnBasePathMapping(this, `${envName}-${appName}-path-mapping`, {
                        basePath: `${appName}-${envName}`,
                        domainName: domainName.domainName,
                        restApiId: api.restApiId,
                        stage: api.deploymentStage.stageName
                    });

**Comment by mokus** [comment]
@devarpi where do you get domainNameAliasTarget? I try to get this parameter from PublicHostedZone construct in cdk, but don't see it anywhere.

**Comment by seanyu4296** [comment]
Hi @mokus did you figure out where to get the domainNameAliasTarget?

**Comment by logemann** [comment]
@mokus @seanyu4296 i am at the same question right now. The docs are kind of wishy washy there...

**Comment by mokus** [comment]
@seanyu4296 @logemann 
I've found using new DomainName(...).addBasePathMapping(...) the most convenient.

However in my specific case I need to unattach the same domain from one APIGateway and attach to another. And CDK can't swallow my scenario. So I ended creating a CustomResource with lambda attached to it that does all the stuff via aws-sdk.

**Comment by logemann** [comment]
cant use new DomainName() in my stack, thats the reason why i am using fromDomainNameAttributes() in the first place. And its not clear what **domainNameAliasTarget** is exactly. In my original Stack, the target is defined like this:

RecordTarget.fromAlias(new targets.ApiGatewayDomain(originalDomainName)),

**Comment by paulsjohnson91** [comment]
I'm having the same problem I have a pre existing custom domain name and am trying to just add a new base path mapping to it

**Comment by CliveBennett** [comment]
Hi, does anyone know how to see what "DomainNameAliasTarget" is? I cant see any reference in Route53 to get this value.

documentation seriously lacking !

**Comment by flexelem** [comment]
hey guys, I mentioned it from the related issue #19045. Hope it helps

**Comment by loi-avela** [comment]
> I started getting #5794 when upgraded cdk (1.25.0)
> 
> Ended up fixing as recommended on the issue page above.
> 
> //BASE Path already exists issue with following
> 
> ```
>                 // //Used in custom domain
>                 // const pathMapping = new BasePathMapping(this,
>                 //     `${envName}-${appName}-path-mapping`, {
>                 //     basePath: `${appName}-${envName}`,
>                 //     domainName: domainName,
>                 //     restApi: api
>                 // });
> 
>                 //fix by CFNBasePathMapping.
>                 new apiGateway.CfnBasePathMapping(this, `${envName}-${appName}-path-mapping`, {
>                     basePath: `${appName}-${envName}`,
>                     domainName: domainName.domainName,
>                     restApiId: api.restApiId,
>                     stage: api.deploymentStage.stageName
>                 });
> ```

works beatufully!
