### ISSUE TITLE
A newer version of the CDK CLI (>= 1.16.0) is necessary to interact with this app

### ISSUE THREAD

**Issue by hayesry** [aws/aws-cdk#4897]
## :question: General Issue
Receiving error message "A newer version of the CDK CLI (>= 1.16.0) is necessary to interact with this app" when running CDK CLI commands such as "cdk deploy" and "cdk synth", but only 1.15.0 is currently available on npm.

### The Question
Is there a version discrepancy between 1.15.0 and 1.16.0? Ran `npm install -g aws-cdk@1.16.0` and received "ERR No matching version found for aws-cdk@1.16.0".

### Environment

  - **CDK CLI Version:** 1.15.0 (build bdbe3aa)
  - **Module Version:** (npm) 1.15.0
  - **OS:** OSX Sierra 10.12.6 (16G2136)
  - **Language:** TypeScript

**Comment by JoshM1994** [comment]
This is now resolved (published 29 minutes ago as of this post)

**Comment by shivlaks** [comment]
@hayesry were you building locally? If you you would also have needed to call your CLI from your build. Since the CX protocol version was bumped but a release hadn't made it's way out yet, you would have had to do something like

i.e. `path-to-cdk/packages/aws-cdk/bin/cdk <command>` in place of `cdk<command>`.

**Comment by hayesry** [comment]
Thanks all for following up on this, works perfectly now!

**Comment by alex-a-ncino** [comment]
> Thanks all for following up on this, works perfectly now!

Hey, I'm getting the same error. I was wondering if you had to do anything to resolve the issue.

**Comment by hayesry** [comment]
Hey @alex-a-ncino - I did an `npm uninstall -g aws-cdk` followed by `npm install -g aws-cdk` to get the right version on my local environment. Brought mine up to `aws-cdk@1.16.1` I believe, which allowed the CLI commands to work again. Hope that helps!

**Comment by agalazis** [comment]
well  to anybody having the came issue there is a cdk command in package.json for a reason. Just use that since it will always be inline with your local cdk verion ie: `yarn cdk synth`

**Comment by iliapolo** [comment]
If anyone got here with a similar error (`>= 1.21.0`), solution is [here](https://github.com/aws/aws-cdk/issues/5986#issuecomment-578959404).
