### ISSUE TITLE
Cross-region/account references

### ISSUE THREAD

**Issue by rix0rrr** [aws/aws-cdk#49]
We were in the progress of defining how to transparently make this work. 

Tracking it here because it's one of the most important things to pick up post-release.

**Comment by kennu** [comment]
Use case: Route53 hostname records in a shared hosted zone
* Stack A -- defines a CloudFront distribution in AWS account A (aaa.example.org)
* Stack B -- defines a CloudFront distribution in AWS account B (bbb.example.org)
* Stack C -- Creates Route53 ALIAS records aaa.example.org and bbb.example.org in a single hosted zone, needs the distribution domain names as input

The challenge is that account A is using a different profile than account B in ~/.aws/credentials so AWS CDK would need to access both profiles to retrieve the distribution domain names.

**Comment by aripalo** [comment]
Use case:

I just hit this limitation by doing:
```
const primaryApi = new ApiStack(app, 'ApiStackIreland', { env: { region: 'eu-west-1' } }); // which has public readonly apiUrl: string;

new EdgeStack(app, 'EdgeStack', {
  primaryApiUrl: primaryApi.apiUrl,
  env: { region: 'us-east-1' }
});
```
And received this error:
```
node_modules/@aws-cdk/cdk/lib/cloudformation/cfn-tokens.js:65
            throw new Error('Can only reference cross stacks in the same region and account.');
```

Having "EdgeStack" in `us-east-1` makes sense as it is CloudFront's "main region" and is a must as one has to define ACM certificates and Lambda@Edge there.

This currently is somewhat blocking. 

Is there any workaround currently?

**Comment by rix0rrr** [comment]
There is not, unfortunately. You're going to have to thread the API URL across regions manually. That means:

- Deploy the `ApiStackIreland` first. Note the API URL (maybe make it an Output so that it's easy to get to).
- Deploy the `EdgeStack` and plug in the value of API URL from the first step.

There are a number of ways you could do this, and honestly I'm not sure which one to recommend.

I guess a pragmatic one would be to use `this.node.getContext()` and pass the value on the command-line when deploying the second stack (using the `-c KEY=VALUE` fflag), or put it into `cdk.json` under the `context: {}` section.

**Comment by rix0rrr** [comment]
You *could* do it automatically using a Lambda-backed Custom Resource in `EdgeStack` that would make a cross-region call to look up the API URL as well, but that's a little more work.

**Comment by briannab12** [comment]
@skinny85  Changes have been made since July. Is there still a way to set the role arn for a PipelineSourceAction? I am accessing a repo in a different AWS account.

**Comment by skinny85** [comment]
Hey @briannab12 ,

currently, there is no way to do that. If you're using TypeScript, the following hack should work:

```ts
(sourceAction as any)['role'] = yourRole;
```

We're working on this experience as we speak, and we hope to make it awesome - see the #1924 PR for details.

Thanks,
Adam

**Comment by briannab12** [comment]
```(sourceAction as any)['role'] = yourRole;```
This worked, thank you. 

Specifications for other:
sourceAction is a codepipeline.PipelineSourceAction object
yourRole is an iam.Role object

**Comment by windlessuser** [comment]
> Use case: Route53 hostname records in a shared hosted zone
> 
> * Stack A -- defines a CloudFront distribution in AWS account A (aaa.example.org)
> * Stack B -- defines a CloudFront distribution in AWS account B (bbb.example.org)
> * Stack C -- Creates Route53 ALIAS records aaa.example.org and bbb.example.org in a single hosted zone, needs the distribution domain names as input
> 
> The challenge is that account A is using a different profile than account B in ~/.aws/credentials so AWS CDK would need to access both profiles to retrieve the distribution domain names.

@kennu did you find a workaround?

**Comment by saltman424** [comment]
> > Use case: Route53 hostname records in a shared hosted zone
> > 
> > * Stack A -- defines a CloudFront distribution in AWS account A (aaa.example.org)
> > * Stack B -- defines a CloudFront distribution in AWS account B (bbb.example.org)
> > * Stack C -- Creates Route53 ALIAS records aaa.example.org and bbb.example.org in a single hosted zone, needs the distribution domain names as input
> > 
> > The challenge is that account A is using a different profile than account B in ~/.aws/credentials so AWS CDK would need to access both profiles to retrieve the distribution domain names.
> 
> @kennu did you find a workaround?

@eladb Since this issue is now closed, do we have a solution for the above use case?

I am trying something similar: having a public hosted zone in one account delegate to a public hosted zone in another account.

**Comment by cshenrik** [comment]
@eladb Can you offer some insights into why this issue was closed? A good generic solution would have taken CDK to the next level (IMHO).

**Comment by OperationalFallacy** [comment]
It looks like the project is trying to get around Cloudformation's native limitation: it can't read outputs from another account/region. Having this functionality in Cloudformation would be a perfect world.

Meanwhile, cdk can deal with the env variable, contexts, config files - why not make stacks outputs automatically available for subsequent stages in a known artifact?

**Comment by skinny85** [comment]
@OperationalFallacy I agree, and we have a feature request already for that functionality: https://github.com/aws/aws-cdk/issues/8566 .

Thanks,
Adam

**Comment by alehatsman** [comment]
> > > Use case: Route53 hostname records in a shared hosted zone
> > > 
> > > * Stack A -- defines a CloudFront distribution in AWS account A (aaa.example.org)
> > > * Stack B -- defines a CloudFront distribution in AWS account B (bbb.example.org)
> > > * Stack C -- Creates Route53 ALIAS records aaa.example.org and bbb.example.org in a single hosted zone, needs the distribution domain names as input
> > > 
> > > The challenge is that account A is using a different profile than account B in ~/.aws/credentials so AWS CDK would need to access both profiles to retrieve the distribution domain names.
> > 
> > 
> > @kennu did you find a workaround?
> 
> @eladb Since this issue is now closed, do we have a solution for the above use case?
> 
> I am trying something similar: having a public hosted zone in one account delegate to a public hosted zone in another account.

I am having a similar problem currently, has anyone tried to solve it using custom resources and cdk? A custom resource that calls lambda which is able to access the parent host zone and add records from stack A and B?

**Comment by OperationalFallacy** [comment]
Cdk has now a construct to add records with lambda, and it works well with pipelines 

https://github.com/OperationalFallacy/CdkRouter53/pull/1/files#diff-28e171489876432b7aa1c09d7d1a446d777028d46e763081600b19ead74c9111R25

**Comment by alehatsman** [comment]
> Cdk has now a construct to add records with lambda, and it works well with pipelines
> 
> https://github.com/OperationalFallacy/CdkRouter53/pull/1/files#diff-28e171489876432b7aa1c09d7d1a446d777028d46e763081600b19ead74c9111R25

Hello, thank you for the example, I have one issuer with this records are created without last dot.

```
ns-640.awsdns-16.net
ns-1775.awsdns-29.co.uk
ns-391.awsdns-48.com
ns-1299.awsdns-34.org
```

but should be

```
ns-640.awsdns-16.net.
ns-1775.awsdns-29.co.uk.
ns-391.awsdns-48.com.
ns-1299.awsdns-34.org.
```

Don't you have the same issue?

**Comment by alehatsman** [comment]
> Cdk has now a construct to add records with lambda, and it works well with pipelines
> 
> https://github.com/OperationalFallacy/CdkRouter53/pull/1/files#diff-28e171489876432b7aa1c09d7d1a446d777028d46e763081600b19ead74c9111R25

Thank you for your reply! It works well!
