### ISSUE TITLE
aws_s3.CfnBucket "bucket_encryption" required properties not implemented in Python

### ISSUE THREAD

**Issue by eduardohki** [aws/aws-cdk#4902]
Hi,

I'm trying to set the default server-side encryption in S3, using the `aws_s3.CfnBucket` module.

The problem is that if I implement a setting of the type `AWS::S3::Bucket.BucketEncryption` in the `bucket_encryption` parameter (as stated [here](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_s3/CfnBucket.html) in the docs), using a value like `{"ServerSideEncryptionByDefault": {"SSEAlgorithm": "AES256"}}` throws out an error, saying that it expects an object reference.

The problem is that I also tried to use the same object as used in the `aws_s3.Bucket` Construct (e.g. `aws_s3.BucketEncryption.S3_MANAGED`), but it is not recognised as well - it seems to me that this reference (`@aws-cdk/aws-s3.CfnBucket.BucketEncryptionProperty: serverSideEncryptionConfiguration`) is not correctly implemented for Python.

### Reproduction Steps

Create a CDK App using Python and add the following code inside the Stack:

```python
bucket = aws_s3.CfnBucket(
    self,
    "bucket",
    bucket_name="my_bucket",
    bucket_encryption={"ServerSideEncryptionByDefault": {"SSEAlgorithm": "AES256"}},
)
```

Then try to run any CDK command, like `cdk ls` or `cdk synth`.

### Error Log

When using a direct reference:
```
jsii.errors.JSIIError: Value did not match any type in union: Expected object reference, got {"ServerSideEncryptionByDefault":{"SSEAlgorithm":"AES256"}},Missing required properties for @aws-cdk/aws-s3.CfnBucket.BucketEncryptionProperty: serverSideEncryptionConfiguration
```

When using `aws_s3.BucketEncryption`:
```
jsii.errors.JSIIError: Value did not match any type in union: Expected object reference, got {"$jsii.enum":"@aws-cdk/aws-s3.BucketEncryption/S3_MANAGED"},Missing required properties for @aws-cdk/aws-s3.CfnBucket.BucketEncryptionProperty: serverSideEncryptionConfiguration
```

### Environment

  - **CLI Version      : 1.15.0 (build bdbe3aa)**
  - **Framework Version: 1.15.0**
  - **OS               : MacOS X Mojave**
  - **Language         : Python/3.7.5**

### Other
--- 

This is :bug: Bug Report

**Comment by eduardohki** [comment]
As seen in https://github.com/aws/aws-cdk/issues/4900, the Interface exists, but it's not documented in Python's implementation.

**Comment by eduardohki** [comment]
I wasn't able to find the correct usage in the Python docs, and found an alternative solution using the following override:

```python
bucket.add_override(
    "BucketEncryption",
    {
        "ServerSideEncryptionConfiguration": [
            {"ServerSideEncryptionByDefault": {"SSEAlgorithm": "AES256"}}
        ]
    },
)
```

**Comment by skinny85** [comment]
@eduardohki glad you got it working. Are you OK with closing this issue?

(BTW, can I ask why you're using the L1 construct (`CfnBucket`) instead of the L2 one (`Bucket`)?)

**Comment by eduardohki** [comment]
@skinny85 feel free to close.

I used the L1 construct because I needed a bucket with Access Logging enabled - which I didn't find in the L2 construct.

**Comment by eladb** [comment]
@eduardohki it should still be possible to use `s3.Bucket` and only patch the specific properties using [escape hatches](https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html).

@RomainMuller what would it take to support passing this by-value in Python?

**Comment by eladb** [comment]
Closing for now. Please reopen if this is still an issue
