### ISSUE TITLE
Amazon Lex

### ISSUE THREAD

**Issue by include** [aws/aws-cdk#4905]
Hi,

Are there any plans to introduce Amazon Lex?

Cheers,
F

This is a :rocket: Feature Request

**Comment by SomayaB** [comment]
Hi @include, thanks for submitting a feature request. Unfortunately until this is added to CloudFormation we can't add it to the CDK. You can let the CloudFormation team you're interested in this feature [here](https://forums.aws.amazon.com/forum.jspa?forumID=92).

**Comment by include** [comment]
Thanks @SomayaB for your reply.
I will ping them; maybe there are more people like me willing to play with Lex via CDK. Cheers.
