### ISSUE TITLE
Impossible to forward IoT to auto-named Firehose

### ISSUE THREAD

**Issue by JoshM1994** [aws/aws-cdk#4910]
I have scoured the API and all possible hacks I can think of but have been unable to find a way to create an IoT forwarding rule to Firehose without explicitly naming that Firehose delivery stream.

The issue is that, when allowing CF to name resources, the `deliveryStreamName` property of the Firehose resource is undefined. This would not usually be an issue but IoT requires the `deliveryStreamName` and __not__ the ARN. Furthermore, Firehose Fn:GetAtt does not expose the DeliveryStreamName, only the arn (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kinesisfirehose-deliverystream.html#aws-resource-kinesisfirehose-deliverystream-return-values-fn--getatt).

For now I am getting around the issue by giving my Firehose an explicit name but this is far from ideal. Am I missing something?

### Reproduction Steps

```
# Not explicitly specifying a delivery stream name
const fh = new firehose.CfnDeliveryStream(this, 'id');

const iotFwdRule = new iot.CfnTopicRule(this, 'MyRule', {
            topicRulePayload: {
                actions: [
                    {
                        firehose: {
                            roleArn: any role,
                            deliveryStreamName: fh.deliveryStreamName, // This is not allowed as this is can be (and is) undefined
                            separator: '\n',
                        },
                    },
                ],
                ruleDisabled: false,
                sql: `SELECT * FROM whatever`,
                awsIotSqlVersion: '2016-03-23',
            },
        });
```

### Environment

  - **CLI Version      :1.15.0 (build bdbe3aa)**
  - **Framework Version:1.15.0**
  - **OS               :Mac**
  - **Language         :TypeScript**

### Other

--- 

This is :bug: Bug Report

**Comment by JoshM1994** [comment]
The solution I have found to be most effective is using `Fn.split` and `Fn.select`...

```
actions: [
    {
        firehose: {
            roleArn: fhIotAssumedRole.roleArn,
            deliveryStreamName: Fn.select(1, Fn.split('/', fh.hoseArn)),
            separator: '\n',
        },
    },
],
```

but it seems there must/should be a more elegant solution.

**Comment by skinny85** [comment]
Hey @JoshM1994 ,

thanks for opening the issue. I believe you're correct, and your solution is actually the thing I would recommend :). We can't do much here unfortunately, the change would have to be to have an `Fn::GetAtt` attribute `Name` added to the `DeliveryStream` resource. Have you tried opening a support issue with the Kinesis team?

Thanks,
Adam

**Comment by JoshM1994** [comment]
Hi @skinny85,

Thanks for your response - I have submitted a support ticket with the Kinesis team and will update this issue if/when I receive a response.

**Comment by JoshM1994** [comment]
AWS Kinesis team got back to me on this one:

>  [...] The engineer is asking if using 'Ref :  <firehose_logical_id>' with the logical ID works for you? When the logical ID of the resource is provided to the Ref intrinsic function, Ref returns the delivery stream name, such as mystack-deliverystream-1ABCD2EF3GHIJ

In practice that looks like:

```ts
const iotFwdRule = new iot.CfnTopicRule(this, 'IotFhFwdRule', {
    topicRulePayload: {
        actions: [
            {
                firehose: {
                    roleArn: fhIotAssumedRole.roleArn,
                    // The `.ref` will resolve to the DeliverySteramName when used in this manner
                    deliveryStreamName: loggingHose.ref,
                    separator: '\n',
                },
            },
        ],
        ruleDisabled: false,
        sql: `SELECT something FROM somewhere
![Screen Shot 2019-12-13 at 13 03 14](https://user-images.githubusercontent.com/7046813/70832271-8e29bd00-1da9-11ea-99b0-784e061cb28d.png)
`,
        awsIotSqlVersion: '2016-03-23',
    },
});
```
