### ISSUE TITLE
aws-eks to support aws/aws-node-termination-handler as the official spot draining handler

### ISSUE THREAD

**Issue by pahud** [aws/aws-cdk#4913]
AWS supports Automated Draining for Spot Instance Nodes on Kubernetes
https://aws.amazon.com/tw/about-aws/whats-new/2019/11/aws-supports-automated-draining-for-spot-instance-nodes-on-kubernetes/

### Use Case

To use the official recommended spot draining handler.

### Proposed Solution

We probably need to update the `spot-interrupt-handler.ts` and replace this with the new one:

https://github.com/aws/aws-cdk/blob/887389ae7290471413702a0a8c2d516e1efdd01c/packages/%40aws-cdk/aws-eks/lib/spot-interrupt-handler.ts#L60

### Other

* [v] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by eladb** [comment]
Sounds good
