### ISSUE TITLE
Deploy Lambda Function using CodePipeline and CDK generated CloudFormation Template

### ISSUE THREAD

**Issue by tleef** [aws/aws-cdk#4941]
### The Question

Big picture, I'm trying to deploy a Lambda function defined by a CDK app using a CodePipeline where the CodePipeline is not defined in the same CDK app.

I am having trouble with the template parameters for the S3 bucket and object key of the Lambda code that are generated by `cdk synth`.

My setup is very similar to the one described in [this](https://docs.aws.amazon.com/cdk/latest/guide/codepipeline_example.html) example.

My CDK app for the Lambda function is co-located in the same repo as the code for my Lambda function. Since the CDK app has direct access to the Lambda code I was using `lambda.Code.fromAsset(path)`. 

I also have a CDK app for my CodePipeline but that is in a different repo. In the linked example, the CodePipeline is defined in the same CDK app with the Lambda function. That is the only real difference between my implementation and the example.

Having the CodePipeline in a separate repo is creating an issue for me because I can't be sure what the parameter names that are generated by `cdk synth` will be. Without knowing what the parameters are named, I can't set them to the values of my CodeBuild output asset in my CodePipeline.

I've also tried using the following in an attempt to set the parameter names manually.
```
lambda.Code.fromCfnParameters({
    bucketNameParam: new core_1.CfnParameter(this, "LambdaSourceBucket"),
    objectKeyParam: new core_1.CfnParameter(this, "LambdaSourceKey"),
})
```

In the above case, `cdk synth` still modifies the parameter names e.g. `AppLambdaSourceBucket8B89D730`. They are slightly more predictable but I'm still not able to reliably predict them in my CodePipeline.

The example avoids this problem by sharing the same [CfnParametersCode](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-lambda.CfnParametersCode.html) instance which allows them to do the following.
```
parameterOverrides: {
  ...props.lambdaCode.assign(lambdaBuildOutput.s3Location),
}
```
where `props.lambdaCode` is a reference to the `CfnParametersCode` instance.

What am I missing? 

It doesn't seem right that I need to have the CodePipeline in the same CDK app. In some cases, the CodePipeline might not be a CDK app at all.

I have also considered just running `cdk deploy` in CodeBuild but using a build stage to perform the duties of a deploy stage is hacky to say the least.

**Update:** I was able to solve my problem with `overrideLogicalId(newLogicalId)`

The following worked for me. It generates parameter names that match whatever string you pass to `overrideLogicalId(newLogicalId)` which is all that I needed.

```
const bucketNameParam = new cdk.CfnParameter(this, "LambdaSourceBucketName");
const objectKeyParam = new cdk.CfnParameter(this, "LambdaSourceObjectKey");
bucketNameParam.overrideLogicalId("LambdaSourceBucketName");
objectKeyParam.overrideLogicalId("LambdaSourceObjectKey");

const fn = new lambda.Function(this, "Fn", {
  code: lambda.Code.fromCfnParameters({
    bucketNameParam,
    objectKeyParam
  }),
  handler: "index.handler",
  runtime: lambda.Runtime.NODEJS_10_X
});
```

### Environment

  - **CDK CLI Version:** 1.15.0 (build bdbe3aa)
  - **Module Version:** ^1.15.0
  - **OS:** macOS Catalina 10.15.1 
  - **Language:** TypeScript

### Other information

This problem is not specific to Lambda deployments. In fact, [this issue](https://github.com/aws/aws-cdk/issues/4928) is about deploying a single-page app to S3 and is having the same problem. The answer there was to co-locate the CodePipeline but that doesn't work for everyone. 

The problem is that CodePipelines impose assumptions about the shape of your environment and they encode certain business practices. Therefore coupling them with whatever they are deploying makes what they are deploying less reusable.

Say you have a lambda function for an OAuth2/OpenID Connect server. That is highly reusable. Attaching a CodePipeline to that means that you need to adopt the same business practices regarding deployment as are assumed by your OAuth2/OpenID Connect server in order to reuse it.

**Comment by skinny85** [comment]
Hey @tleef ,

thanks for reporting. I believe when your Parameter would be directly under the `Stack` class, there would be no renaming. But anyway, your renaming strategy is what I would expected.

Can we help you with anything else?

Thanks,
Adam

**Comment by tleef** [comment]
All good, thanks!
