### ISSUE TITLE
cdk is not recognized inside PyCharm virtual env terminal (Win 10)?

### ISSUE THREAD

**Issue by scheung38** [aws/aws-cdk#4956]
## :question: General Issue

# Powershell
(.env)> cdk --version
1.15.0 (build bdbe3aa)

(.env)> cdk ls
The term 'cdk' is not recognized

# Pycharm terminal
(.env)> cdk --version  
'cdk' is not recognized 

the following is a fix but for TypeScript project, what is the change for a Python project?

https://github.com/aws/aws-cdk/issues/2657

### Environment

  - **CDK CLI Version:**  1.15.0 (build bdbe3aa)
  - **Module Version:**  
  - **OS:** Windows 10  
  - **Language:**   Python

**Comment by SomayaB** [comment]
Hi @scheung38, thanks for reporting this. We will update this issue when there is movement.

**Comment by davidfsmith** [comment]
I have a similar issue on OSX, outside of a Python virtual env the command `cdk` works just fine but inside a python virtual environment the command `cdk` is not recognised, I have to use the full path `/usr/local/bin/cdk`

**Comment by davidfsmith** [comment]
Just to update on this, investigated a bit further and resolved by removing `cdk` from my pyenv shim

`rm ~/.pyenv/shims/cdk`

Possibly a hang up from an earlier cdk install a while back.

**Comment by shivlaks** [comment]
@davidfsmith thanks for reporting that workaround. does that apply to both Windows and OS X?

Haven't had a chance to look at the Windows issue at all, but it might be helpful for other folks who run into the same issue nonetheless

**Comment by davidfsmith** [comment]
Sorry @shivlaks - I should've noted this only tested on OSX (all I have access to) but hopefully will help someone

**Comment by shivlaks** [comment]
I'm attempting to reproduce this issue on my windows machine and am not able to. Is this still an issue @scheung38 
It might just be staleness, but I'm testing with CLI version`1.59.0`.

I don't believe there is an actionable bug to take on here so dropping the `bug` label for now.
