### ISSUE TITLE
[s3] Support LoggingConfiguration for Bucket 

### ISSUE THREAD

**Issue by cmckni3** [aws/aws-cdk#4967]
### Use Case

Common use case is to set up `LoggingConfiguration` for a CloudTrail bucket.

### Proposed Solution

Allow specifying `LoggingConfiguration` as present in CloudFormation specification.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html#cfn-s3-bucket-loggingconfig

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by cmckni3** [comment]
I used the escape hatch as specified in https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html#cfn_layer_resource

```typescript
const cfnBucket = cloudtrailBucket.node.defaultChild as s3.CfnBucket;
cfnBucket.loggingConfiguration = {
  destinationBucketName: archiveLogsBucket.bucketName,
  logFilePrefix: 'cloudtraillogs',
};
```

**Comment by eladb** [comment]
Implemented in https://github.com/aws/aws-cdk/pull/5072
