### ISSUE TITLE
[apigateway] improved aws service integrations

### ISSUE THREAD

**Issue by rhboyd** [aws/aws-cdk#4991]
There have been a few issues <sup>[1](https://github.com/aws/aws-cdk/issues/4859)</sup> asking for APIGW -> Lambda -> [insert service here] but these aren't really the right approach. The [AwsIntegration](https://github.com/aws/aws-cdk/blob/52b136b34ad5dd14131bdf856ec57c20bc75bb19/packages/%40aws-cdk/aws-apigateway/lib/integrations/aws.ts#L72) still requires users to specify the request mapping template, any required headers, paths, etc ..... As a user, this is bad. I put my shoes on this morning while I still only had one sock on because I forgot to put on the other sock. I can't be trusted to supply a VTL Template that does this mapping.

### Use Case
I want direct APIGW Service Integrations (without Lambdas) but I don't want to learn VTL in order to do it. I also don't want to learn which x-amz-json-1.1.0 header is needed in which services to get the integration to work correctly.

### Proposed Solution
[Botocore](https://github.com/boto/botocore/tree/develop/botocore/data)/data fully defines these requirements in a nice JSON (as much as you can call JSON nice) document. 

The UX I imagine makes APIGW service integrations look very similar to the AwsCustomResource API.
```js
new AwsIntegrationResource(this, 'MyAPIResource', {
        put: {
            service: 'Athena',
            action: 'startQueryExecution',
            parameters: {
                QueryString: `CREATE EXTERNAL TABLE IF NOT EXISTS ${props.databaseName}.${props.tableName} (Date DATE, Time STRING, Location STRING) LOCATION 's3://${props.queryBucket.bucketName}'/`,
                QueryExecutionContext: {
                    Database: props.databaseName
                 },
                ResultConfiguration: {
                    OutputLocation: `s3://somebucket/path`
                },
            }
        },
        post: {
            service: 'EC2',
            action: 'createNatGateway',
            parameters: {
                AllocationId: `SomeAllocationId`,
                ClientToken: `MyToken`,
                SubnetId: `1234567`,
            }
        },
        policyStatements: [thirdPolicy]
    });
```

### Other

* [X] :wave: I may be able to *help* implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rhboyd** [comment]
Another benefit is that these Constructs won't be affected by runtime deprecations in Lambda. :D

**Comment by nija-at** [comment]
I like this idea; it would definitely make configuring service integrations easier and less error-prone.

We should try and make the APIs hold more type information; something like such -

```ts
new AwsIntegrationResource(this, 'MyAPIResource', [
        Athena.startQueryExecution({
          QueryString: `CREATE EXTERNAL TABLE IF NOT EXISTS ${props.databaseName}.${props.tableName} (Date DATE, Time STRING, Location STRING) LOCATION 's3://${props.queryBucket.bucketName}'/`,
          QueryExecutionContext: {
            Database: props.databaseName
          },
          ResultConfiguration: {
            OutputLocation: `s3://somebucket/path`
          },
    });
```

**Comment by falkhoury** [comment]
I also would be interested in an improved aws service integrations. 
I've tried to setup a gateway with a service integration but there are no examples on this and I couldn't get it to work. 

could someone please give me a hint. I would like to do the same thing in AWS Lambda-backed APIs section of https://docs.aws.amazon.com/cdk/api/latest/docs/aws-apigateway-readme.html but instead with a dynamodb integration.

**Comment by NightWatchman** [comment]
I'm currently struggling my way through getting an API Gateway to execute a Step Function myself. Like @falkhoury said, there's not much out there in the way of documentation for this. I'd love to see some improvements in this area, even just more detailed and informative documentation on service integrations with the CDK specifically would be a big help.
