### ISSUE TITLE
Lambda requires an S3 bucket, even if it is not being used

### ISSUE THREAD

**Issue by marioizquierdo** [aws/aws-cdk#4992]
Lambda Function prop `code` (type [Code](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-lambda.Code.html)) is mandatory. It can be [fromBucket, fromInline or fromAsset](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-lambda-readme.html#handler-code), however, there's no option to tell CDK to ignore the code.

The `code` prop should be optional, allowing to easily deploy a new lambda with no dependencies. The lambda code updates/deploys are often managed by another deploy script (at least in my case), which only care about updating the lambda code and not the S3 file.

### Use Case

For example, make a tiny Lambda with no advanced deploy strategies.

Currently, we have to specify an S3 bucket with a zip file just to be able to deploy the lambda stack:

```ts
class s3BucketStack extends cdk.Stack {
  public bucket: s3.IBucket;
  constructor(scope: cdk.Construct, name: string, props: cdk.StackProps) {
    this.bucket = new s3.Bucket(this, 'S3Bucket', {
      removalPolicy: RemovalPolicy.DESTROY,
    });
  }
}
```

The lambda stack needs to receive the bucket as parameter:

```ts
interface LambdaStackProps extends cdk.StackProps {
  s3Bucket: s3.IBucket; // bucket where the code file is located
  s3CodeFile: string; // zip file for the lambda function in the s3Bucket
}

export class LambdaStack extends cdk.Stack {
  constructor(scope: cdk.Construct, name: string, props: LambdaStackProps) {
    super(scope, name, props);

    new lambda.Function(this, 'LambdaHandler', {
        runtime: lambda.Runtime.GO_1_X,
        handler: 'main',
        code: lambda.Code.fromBucket(props.s3Bucket, props.s3CodeFile),
    });
  }
}
```

This have to be deployed in 3 steps:
 1. Deploy s3bucket stack
 2. Build and push the file (maybe from another repository)
 3. Deploy the lambda stack

The commands to deploy a new version of the code need to push it both to s3 and to lambda:

```sh
# Deploy zip file to lambda to run the new version
aws lambda update-function-code --function-name $LAMBDA_ARN --zip-file fileb://$PWD/build/function.zip

# Also deploy to s3 in case the lambda infra is updted in cdk
aws s3 cp ./build/function.zip s3://$BUCKET_ARN/
```

### Proposed Solution

The lambda stack should allow code to be optional. If not, at least allow using a `lambda.Code.Placeholder()` option to make a hello world function. That way, it can be defined without an s3 bucket:

```ts
export class LambdaStack extends cdk.Stack {
  constructor(scope: cdk.Construct, name: string, props: cdk.StackProps) {
    super(scope, name, props);

    new lambda.Function(this, 'LambdaHandler', {
        runtime: lambda.Runtime.GO_1_X,
        handler: 'main',
        // code: lambda.Code.Placeholder()
    });
  }
}
```

The script to deploy a new version does not have to worry about s3 anymore:

```sh
aws lambda update-function-code --function-name $LAMBDA_ARN --zip-file fileb://$PWD/build/function.zip
```

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by marioizquierdo** [comment]
This could be an issue with CloudFormation's [AWS::Lambda::Function](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html). I'm new to CloudFormation, so I'm not sure exactly if that is the case, but it seems that the code property is mandatory, and must be a reference from an S3 bucket (except for Python and JS that can be inline).

Maybe CDK can do something about it, like using a default S3 reference that is ignored later. But it would be ideal if the code could be ignored and left alone, so it is managed externally by another deploy tool.

**Comment by nija-at** [comment]
Thanks for filing this feature request @marioizquierdo. Unfortunately, this is not the fundamental design of CloudFormation and the CDK. It's not possible to create a Lambda function without the code being specified.

You could achieve this on your end, by having a basic 'hello world' placeholder code you add while creating the function and use `update-function-code` in your script to change this.

However, I'll caution that this approach is not a best practice. Any time a new CloudFormation deployment or update occurs, it can replace your 'updated' code with the placeholder code again and cause an outage to your application. The best practice is to manage your function configuration and code via your IaC (such as CloudFormation or CDK).
