### ISSUE TITLE
Pass parameters to CfnInclude

### ISSUE THREAD

**Issue by cmckni3** [aws/aws-cdk#4994]
Allow passing parameters to template included via `CfnInclude`.

### Use Case

It would be nice to be able to reuse existing templates (from quickstarts for example) that rely on parameters being passed to them.

### Proposed Solution

Not really sure but my workaround is to remove the parameters and hardcode them.

Perhaps `CfnInclude` could have a prop for `CfnParameter`s?

### Other

Reference example of importing an existing template. Imagine the template has parameters. The drupal quickstart is an example of a quickstart with many parameters.

```typescript
import cdk = require("@aws-cdk/core");
import fs = require("fs");

new cdk.CfnInclude(this, "ExistingInfrastructure", {
  template: JSON.parse(fs.readFileSync("my-template.json").toString())
});
```

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by cmckni3** [comment]
I wonder if it would be possible for `CfnInclude` to return a `Stack` with the constructs inside of it.

**Comment by joekiller** [comment]
When using CfInclude nothing is stopping you from using parameters in that stack. You can even use cdk parameters and then import. As long as the ID is aligned it'll work. I did something similar here:

https://gist.github.com/joekiller/36f28eeffeeb50d3c0f4373c3d372d9e

Note to parse and then include the stack I had to make the yaml "clean" ie no bang (!Ref) functions. Use Fn::Ref  instead. Your yaml module may vary (YYMMV)

**Comment by joekiller** [comment]
Typically you can do,

core.App()
core.stack(app)
CfnInclude(app, mystack)

And it's there.

**Comment by joekiller** [comment]
If I wasn't clear enough. Parameters import fine. If you want to replace those you can do something like my gist where you set the default of the parameter to what you want.

**Comment by cmckni3** [comment]
I have been reading about making use of context to provide defaults to when using `cdk deploy` as well.

Reading in existing templates parsing them as JSON/YAML and modifying them as necessary is a great first step and works for now.

Thanks @joekiller!

**Comment by cmckni3** [comment]
cdk-dasm is helpful as well

**Comment by flyingImer** [comment]
> When using CfInclude nothing is stopping you from using parameters in that stack. You can even use cdk parameters and then import. As long as the ID is aligned it'll work. I did something similar here:
> 
> https://gist.github.com/joekiller/36f28eeffeeb50d3c0f4373c3d372d9e
> 
> Note to parse and then include the stack I had to make the yaml "clean" ie no bang (!Ref) functions. Use Fn::Ref instead. Your yaml module may vary (YYMMV)

I'm interested in putting a resource value into a parameter 'Default' of an included CFN, for example, an S3 bucket name, the bucket is defined in another CDK stack. Is it feasible for your experience?

I know, by default, CDK does 'Fn::Import' and 'Fn::Export' for you. Since parameters are a little bit tricky here, they don't take intrinsic functions (and I don't think it makes any sense), any clue how to orchestrate this? is this another anti-pattern thing? (maybe this should leave to the CDK team...)

**Comment by logemann** [comment]
would love to see something implemented right into **CfnInclude**. Something like a attribute in the struct like **params** where you can supply a structure of key/values. 

Of course one can do this manually like @joekiller did,  but life is too short ;-)

**Comment by joekiller** [comment]
@logemann there is a --parameter switch now but you cannot set it any way other than via CLI. I'd like it if I could provide a map of parameters to a cloudformation context.

I ended up having to double down on some CLI switches. See https://github.com/aws/aws-cdk/issues/7576#issuecomment-620111485
