### ISSUE TITLE
[aws-eks] Cluster Tags

### ISSUE THREAD

**Issue by pahud** [aws/aws-cdk#4995]
To create tags with cluster.

### Use Case

Amazon EKS support resource tags, however, `aws-eks` doesn't support it at this moment.
https://docs.aws.amazon.com/eks/latest/userguide/eks-using-tags.html

cloudformation not yet to support it
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-eks-cluster.html

However, API/SDK/CLI support it
https://docs.aws.amazon.com/eks/latest/APIReference/API_CreateCluster.html

### Proposed Solution

To provide the tags property in the [ICluster](https://github.com/aws/aws-cdk/blob/a257d4d07f11cba666a7dd1b8005736ca7113bc3/packages/%40aws-cdk/aws-eks/lib/cluster.ts#L24-L87) interface and implement the cluster tagging in the [Cluster](https://github.com/aws/aws-cdk/blob/a257d4d07f11cba666a7dd1b8005736ca7113bc3/packages/%40aws-cdk/aws-eks/lib/cluster.ts#L233-L624) class with `custom-resources`.

Does it make any sense?

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by eladb** [comment]
Yes totally we already use a custom resource to provision the cluster so this should be easy to support

**Comment by pahud** [comment]
@eladb  OK Let me try.

Can you help look into this similar issue? https://github.com/aws/aws-cdk/issues/4979

**Comment by reillykw** [comment]
The botocore version supplied by [current python lambdas](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html) doesn't quite yet support tags with create_cluster function.  I gave python3.8 a go, since it was a higher version and still was receiving validation errors.  This may need a different layer supplied or just wait for the lambda environment to upgrade.

**Comment by aserour** [comment]
+1: Our customer is waiting for it

**Comment by adriantaut** [comment]
hey guys, any news on this one so far?

**Comment by iliapolo** [comment]
@adriantaut Hi, this is not currently planned. We will gladly accept a PR though if you are interested.
