### ISSUE TITLE
CDK version 1.16.2 - cdk deploy does not accept stackname

### ISSUE THREAD

**Issue by pputhran** [aws/aws-cdk#4997]
### The Question
Were there any recent changes related to passing stackname to CDK deploy?

Noticed my CDK deploy started failing since the version was updated to 1.16.2

I am passing a stack name to cdk deploy 

```
cdk deploy ${PERF_TEST_STACK_NAME} 
```
where `export PERF_TEST_STACK_NAME=somestackname`

but cdk deploy is returning **"No stack found matching 'somestackname'. Use "list" to print manifest”** and when I do cdk list, it returns `PerftestStackAirlineStack`

/bin/cdk-app.ts
```
const STACK_NAME = process.env.PERF_TEST_STACK_NAME
const app = new cdk.App();
new PerftestStackAirlineStack(app, 'PerftestStackAirlineStack', {stackName: STACK_NAME});
```

This was working before I updated the cdk version (previous working verison was 1.10.x). 

### Environment

  - **CDK CLI Version:**   1.16.2 (build 5893301)
  - **Module Version:**  @aws-cdk/core: 1.16.2
  - **OS:**  OSX Mojave
  - **Language:**  Typescript

**Comment by eladb** [comment]
Acknowledging as a regression. This should have been enabled only under a feature flag for new projects.

**Comment by eladb** [comment]
Hopefully we'll be able to release this shortly.

**Comment by btakita** [comment]
I'm still getting this error as of version `1.30.0`
