### ISSUE TITLE
Very long hiatus when deploying, destroying or diffing

### ISSUE THREAD

**Issue by PeterBengtson** [aws/aws-cdk#5000]
What is the CDK doing in this situation? It just sits there silently, sometimes up to 10 minutes. An animation would help, and/or some explanation as to what's happening in the background.

![screenshot_2019-11-13_at_11 47 57](https://user-images.githubusercontent.com/3897/68757977-30b91980-060d-11ea-8de4-fd4a47cef10f.png)

Using --verbose prints env info,  context info, and then a blob of the env, and then it just sits there again:

![screenshot_2019-11-13_at_11 53 35](https://user-images.githubusercontent.com/3897/68758012-4595ad00-060d-11ea-892b-ad595064283c.png)

What happens at this point is anybody's guess. No information is printed, nothing moves on screen (a rotating CLI character would be a great help). Sometimes the operation continues after a long while, sometimes not.

This is :bug: Bug Report

**Comment by PeterBengtson** [comment]
The operation can time out, but that more has to do with the `aws-login-tool`. In any case, it can take 5, 10 or 15 minutes before it decides to terminate, or indeed to finish as expected.

**Comment by PeterBengtson** [comment]
Might this possibly have something to do with CDK not scaling as expected? Our project encompasses almost 70 stacks.

**Comment by eladb** [comment]
Could definitely be related. Seems like it's hung during synthesis.

Quick sanity check: can you try to synthesize without the CLI by executing your CDK app directly? If you CDK app is under `app/myapp.js` then, you can synthesize it like this:

```
CDK_OUTDIR=cdk.out node app/myapp.js
```

I am curious if this will also take very long and/or get stuck.

**Comment by PeterBengtson** [comment]
Is `synth` really invoked as part of a `cdk deploy`?

I'll try the command above, but aren't these things unrelated?

**Comment by eladb** [comment]
Yes, it is, unless `--app` points to a `cdk.out` directory. Otherwise it will always synth first.

**Comment by shivlaks** [comment]
along with the suggestion @eladb had, can you also run your CLI with `node --prof`
It might give us a better clue of where time is being spent

**Comment by eladb** [comment]
I haven't seen this in a while. I think it has been resolved. Please reopen if this is still relevant.
