### ISSUE TITLE
aws_cloudfront.CustomOriginConfig not working in Python

### ISSUE THREAD

**Issue by tomomano** [aws/aws-cdk#5001]
I am facing a issue with using [aws_cloudfront.CustomOriginConfig](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_cloudfront/CustomOriginConfig.html#aws_cdk.aws_cloudfront.CustomOriginConfig) in Python. I know this class is still at experimental release, but I would greatly appreciate any help/comments that may resolve my issue.

### Reproduction Steps

I am trying to set up a CloudFront distribution with two origins, S3 and API Gateway. Below is the code snippet to prepare the distribution.

```python
import aws_cloudfront as cfront

...

# define cloudfront distribution
distribution = cfront.CloudFrontWebDistribution(
   self, "CloudFrontDistribution",
   origin_configs=[
         cfront.SourceConfiguration(
            s3_origin_source=cfront.S3OriginConfig(
               s3_bucket_source=site_bucket,
               origin_access_identity_id=props.oia.ref
            ),
            behaviors=[cfront.Behavior(is_default_behavior=True)],
         ),
         cfront.SourceConfiguration(
            custom_origin_source=cfront.CustomOriginConfig(
               domain_name=props.apigw_domain_name
            ),
            behaviors=[cfront.Behavior(
               allowed_methods=cfront.CloudFrontAllowedMethods.ALL,
               path_pattern="/api"
            )]
         )
   ],
)
```

### Error Log

Here is the error message I got when I ran `cdk synth`.

> jsii.errors.JSIIError: Got 'undefined' for non-optional instance of {"abstract":true,"docs":{"remarks":"Should not include the path - that should be in the parent SourceConfiguration","stability":"experimental","summary":"The domain name of the custom origin."},"immutable":true,"locationInModule":{"filename":"lib/web_distribution.ts","line":179},"name":"domainName","type":{"primitive":"string"}}

If I delete the `CustomOriginConfig` part (i.e. only with S3 origin), the build succeeds.

I am thinking that this may be a bug in the CDK. Or, am I using the functions in a wrong way?

### Environment

  - **CLI Version      : CDK v1.15
  - **Framework Version:**
  - **OS               : Ubuntu 16.04 LTS
  - **Language         : Python 3.7

### Other

--- 

This is :bug: Bug Report

**Comment by eladb** [comment]
The error message hints that `props.apigw_domain_name` might be null. Can you verify it indeed has a value?

**Comment by tomomano** [comment]
Ah, good point...!
First of all, if I replace `props.apigw_domain_name` with a random string, then cdk synth compiles!

In my app, API Gateway is defined in other stack in a normal way, like
```python
class APIStack(core.Stack):
    def __init__(self, parent, name, **kwargs):
        api = apigw.RestAPI(self, "API")
        self.api = api
```

And I am passing the `domain_name` attribute of the `RestApi` object to the other stack.

I noticed that when I add `print(props.apigw_domain_name)` in the child stack which accepts the domain name reference, I get

```
<aws_cdk.aws_apigateway.DomainName object at 0x7fbc63956310>
```

Does this mean that, at compile time, the value of `DomainName` is undefined? Is this something related to the "dependency" between the stacks?

**Comment by eladb** [comment]
@tomomano [`api.domainName`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-apigateway.RestApi.html#domainname-1) refers to a [`DomainName`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-apigateway.DomainName.html) object which is relevant when using custom domains. 

This property may be null in case your APIGW does not have a custom domain. If it's not null (which seems to be the case), and you want the actual domain name, you will need to use the [`api.domain_name.domain_name`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-apigateway.DomainName.html#domainname-1) property.

Please reopen if this doesn't help resolve the issue.

**Comment by toleabivol** [comment]
@tomomano a bit of an offtopic : how did you create the origin access identity via cdk ? I cannot find the CloudFrontOriginAccessIdentityConfig class anywhere in python cdk

**Comment by toleabivol** [comment]
ok - figured it out :
```
oai = cloudfront.CfnCloudFrontOriginAccessIdentity(
            self, f'origin-access-identity-{stage}-{app_name}-{version}',
            cloud_front_origin_access_identity_config=cloudfront.CfnCloudFrontOriginAccessIdentity
            .CloudFrontOriginAccessIdentityConfigProperty(
                comment=f'origin-access-identity-{stage}-{app_name}-{version}'
            )
        )
```
