### ISSUE TITLE
rds.DatabaseInstanceFromSnapshot does not correctly set POSTGRES master user name

### ISSUE THREAD

**Issue by gary-cowell** [aws/aws-cdk#5002]
When using          

```
this.myrds = new rds.DatabaseInstanceFromSnapshot(this, `dbid`, {
engine: rds.DatabaseInstanceEngine.POSTGRES,
instanceClass: ec2.InstanceType.of(ec2.InstanceClass.T3, ec2.InstanceSize.MEDIUM),
snapshotIdentifier: 'rds:snapshotid' ,
masterUsername: `newmasteruser`, 
deletionProtection: false,
allocatedStorage: 150,
vpc: this.vpc,
masterUserPassword: this.newmasterpass,
})
```

The masterUserPassword _**is**_ applied to the new database, but the masterUsername is not.

Documentation states:

```
masterUsername?🔹
Type: string (optional, default: inherited from the snapshot)
The master user name.
```

So, if specified, the new username should be set.

### Reproduction Steps

As above.

### Error Log

The master user name is inherited from the snapshot, regardless of this setting.

### Environment

  - **CLI Version      : 1.15 **
  - **Framework Version: 1.15 **
  - **OS               : Linux **
  - **Language         : typescript **

### Other

--- 

This is :bug: Bug Report

**Comment by jogold** [comment]
I think that this is a RDS/CloudFormation limitation, see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html#cfn-rds-dbinstance-masterusername

> If you specify the SourceDBInstanceIdentifier or DBSnapshotIdentifier property, don't specify this property. The value is inherited from the source DB instance or snapshot.

The API in CDK should be adapted accordingly.

**Comment by skinny85** [comment]
@jogold can you clarify what CDK change you see here?

**Comment by jogold** [comment]
> @jogold can you clarify what CDK change you see here?

Just meant to remove the `masterUsername` prop from `DatabaseInstanceFromSnapshot` props. Will open a PR.

After some research I can confirm it's currently not possible to change the master username of a RDS instance even when using a snapshot.

**Comment by jogold** [comment]
We need it for `generatorMasterUserPassword`, will update JSDoc
