### ISSUE TITLE
aws-codestarnotifications: support NotificationRule

### ISSUE THREAD

**Issue by LuqiPan** [aws/aws-cdk#5020]
__[Not a Contribution]__

With the introduction of [notifications for AWS CodeCommit, AWS CodeBuild, AWS CodeDeploy, and AWS CodePipeline](https://aws.amazon.com/about-aws/whats-new/2019/11/introducing-notifications-for-aws-codecommit-aws-codebuild-aws-codedeploy-and-asw-codepipeline/), it would be great if we can create CodeStar NotificationRule with aws-cdk

### Use Case

Create CodeStar Notification Rule with aws-cdk

### Proposed Solution

Implement CloudFormation Resource and CDK Construct for https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codestarnotifications-notificationrule.html

### Other

Reference:
- https://aws.amazon.com/about-aws/whats-new/2019/11/introducing-notifications-for-aws-codecommit-aws-codebuild-aws-codedeploy-and-asw-codepipeline/
- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codestarnotifications-notificationrule.html

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by luckily** [comment]
Hi @skinny85 and @LuqiPan 
I would like to contribute this implementation for this issue and I have the same problem too, but I used L1 CDK construct to resolve my problem.

This issue also need to Implement `chatbot.CfnSlackChannelConfiguration` and `codestarnotifications.CfnNotificationRule`.

The use case and pseudo code like as below:
``` typescript
const codebuildProject = new codebuild.Project(this, 'MyCodebuild', {...});

const slackChannel = new chatbot.SlackChannelConfiguration(this, 'MySlackChannel', {...});
const topis = new sns.Topic(this, 'MyTopic', {...});

codebuildProject.addNotification({
  notificationRuleName: 'MyNotificationRule',
  targets: [
    new SlackNotificationTarget(slackChannel),
    new SNSTopicNotificationTarget(topic),
  ],
  eventTypeIds: [
    ProjectEvent.BUILD_STATE_SUCCEEDED,
    ProjectEvent.BUILD_STATE_FAILED,
  ],
});
```

Maybe you can see that in few days. :)

**Comment by luckily** [comment]
PR undergoing

**Comment by teuteuguy** [comment]
Any news on this ?

**Comment by luckily** [comment]
> Any news on this ?

In progress. 🙂

**Comment by luckily** [comment]
@teuteuguy, merged!

**Comment by skinny85** [comment]
Done in https://github.com/aws/aws-cdk/pull/10833.
