### ISSUE TITLE
GatewayVpcEndpointAwsService should support SQS

### ISSUE THREAD

**Issue by vertti** [aws/aws-cdk#5024]
You can currently add VPC Endpoint for S3 and DynamoDB. AWS also supports SQS VPC Endpoint but CDK's `GatewayVpcEndpointAwsService` doesn't have an enum for SQS.

### Use Case

Calling SQS from Lambda that is placed inside VPC without travelling the public internet.

### Proposed Solution

Add `GatewayVpcEndpointAwsService.SQS`.

---

This is a :rocket: Feature Request

**Comment by Lightning303** [comment]
S3 and DynamoDB are the only gateway endpoints, all others are interface endpoints. Try `InterfaceVpcEndpointAwsService`.

**Comment by vertti** [comment]
Thank you @Lightning303
