### ISSUE TITLE
[Python] aws_servicediscovery PrivateDnsNamespace.name attribute issues

### ISSUE THREAD

**Issue by WillBroadbentMSM** [aws/aws-cdk#5027]
I'm unable to retrieve the name attribute from the object "PrivateDnsNamespace"

Also from a feature standpoint, it makes sense to be I should be able to pass the "PrivateDnsNamespace" object directly into the "default_cloud_map_namespace" parameter of ECS if it has been created in the same script. Which is how I stumbled across this issue

### Reproduction Steps

```
default_cloudmap = sd.PrivateDnsNamespace(self, "cloud-map-namespace",
    vpc = vpc,
    name = "tsm.local"
)
namespace_options = ecs.CloudMapNamespaceOptions(self, "options",
    name = default_cloudmap.name
)
# Create tsm cluster
cluster = ecs.Cluster(
    self, 'tsm_cluster',
    cluster_name="tsm",
    vpc=vpc,
    default_cloud_map_namespace=namespace_options
)
```

### Error Log

AttributeError: 'PrivateDnsNamespace' object has no attribute 'name'

### Environment

  - **CLI Version      : 1.16.2
  - **Framework Version: 
  - **OS               : Mac OS
  - **Language         : Python

### Other

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
You were probably looking for [namespace_name](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_servicediscovery/PrivateDnsNamespace.html#aws_cdk.aws_servicediscovery.PrivateDnsNamespace.namespace_name)
