### ISSUE TITLE
Make PublicAccessBlockConfiguration optional for cdk bootstrap

### ISSUE THREAD

**Issue by abelmokadem** [aws/aws-cdk#5028]
We would like to deploy the cdk bootstrap stack without the `PublicAccessBlockConfiguration` property.

### Use Case

Setting this property is restricted in our organization account.

### Proposed Solution

Possible solution:
```
cdk bootstrap --without-public-access-block-configuration
```

### Other

* [X] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by hoegertn** [comment]
I do not see any reason you would want a public bootstrap bucket.

**Comment by abelmokadem** [comment]
@hoegertn it is not that the bucket is public, these rules are managed on the account level and we only have limited access to what we can do within the account. Part of our permission boundary is that we can't perform `s3:PutPublicAccessBlock` which means that the cdk bootstrap stack fails with the following error:

```
API: s3:PutPublicAccessBlock Access Denied
```

**Comment by ashwgupt** [comment]
We also are hit and badly blocked by this issue now. Any plans to work on this sooner? Or any known workaround for this?

**Comment by m-mayank** [comment]
+1

**Comment by bruce-igaw** [comment]
@eladb, my company did not give s3 put permission to our organization access key for security reasons. "--without-public-access-block-configuration" 
it would be nice solution.

**Comment by eladb** [comment]
@skinny85 @rix0rrr I am assigning to you guys to consider as part of the new bootstrapping story.

**Comment by bminahan73** [comment]
+1

**Comment by bminahan73** [comment]
A valid but kinda sucky workaround is to manually create a cloudformation stack in each account and region you need named CDKToolkit. Run cdk bootstrap in one account/region to get the template, then modify the template to remove the public access block bit.

**Comment by bminahan73** [comment]
Our organization also requires versioning on our buckets + enforces a tagging standard, so you can do things that like as well with this approach (at least I was able to and make it work).

**Comment by jev11** [comment]
+1

**Comment by RV76** [comment]
+1, Same issue here and workaround is nasty when running pipeline as code.

**Comment by slushysnowman** [comment]
+1 same issue, I can't do `s3:PutPublicAccessBlock` and so my cdk bootstrap commands fail during stack creation:
API: s3:PutPublicAccessBlock Access Denied

Being able to add a flag to turn this off would be very very helpful.

**Comment by bartkeizer** [comment]
+1

**Comment by sudhirjena** [comment]
> A valid but kinda sucky workaround is to manually create a cloudformation stack in each account and region you need named CDKToolkit. Run cdk bootstrap in one account/region to get the template, then modify the template to remove the public access block bit.

👍

**Comment by abelmokadem** [comment]
🙏 🙏 🙏 🙏 🙏 🙏 🙏 🙏

**Comment by alimeerutech** [comment]
thanks all this is great!

**Comment by gl-lamhnguyen** [comment]
Ran into same issue on my first try with cdk, my Org restricts this permission from SCP, seems like cdk is a pass at this point :(

**Comment by alimeerutech** [comment]
Cdk has a new config setting to circumvent this issue

**Comment by gl-lamhnguyen** [comment]
@alimeerutech could you point me to it? I did some research but couldn't find anything

**Comment by alimeerutech** [comment]
https://github.com/aws/aws-cdk/issues/8724
