### ISSUE TITLE
Python dependencies incorrect - jsii incompatibile

### ISSUE THREAD

**Issue by mmesserman-verimatrix** [aws/aws-cdk#5041]
When trying to install aws-cdk.core==1.15.0 (or, really, any previous version), any dependencies are installed as the latest version (e.g. 1.16.3), which results in an error (warning) of:

ERROR: aws-cdk-cx-api 1.16.3 has requirement jsii~=0.20.5, but you'll have jsii 0.19.0 which is incompatible.

### Reproduction Steps

from a shell, run the following:

$ virtualenv -p python3 $.env
$ source $.env/bin/activate
($.env) $ pip install aws-cdk.core==1.15.0

### Error Log

ERROR: aws-cdk-cx-api 1.16.3 has requirement jsii~=0.20.5, but you'll have jsii 0.19.0 which is incompatible.

### Environment

  - **CLI Version      :1.16.219**
  - **Framework Version:ALL**
  - **OS               :OSX 10.15**
  - **Language         :python**

### Other

Full output of above commands:
$ virtualenv -p python3 $.env
Already using interpreter /Library/Frameworks/Python.framework/Versions/3.6/bin/python3
Using base prefix '/Library/Frameworks/Python.framework/Versions/3.6'
New python executable in /xxxxxxxx/$.env/bin/python3
Also creating executable in /xxxxxxx/$.env/bin/python
Installing setuptools, pip, wheel...
done.
$ source $.env/bin/activate
($.env) $ pip install aws-cdk.core==1.15.0
Looking in indexes: https://pypi.python.org/simple
Collecting aws-cdk.core==1.15.0
  Using cached https://files.pythonhosted.org/packages/b6/12/e4578fe423f1b362fe0dec0773d96db0ae917fb79718d944157f57f0f2b8/aws_cdk.core-1.15.0-py3-none-any.whl
Collecting aws-cdk.cx-api>=1.15.0,~=1.15
  Using cached https://files.pythonhosted.org/packages/e3/99/63faeb19ffd2ac1f843148e3a70361aa2cfaba83a9a6b432246a3433b75a/aws_cdk.cx_api-1.16.3-py3-none-any.whl
Collecting publication>=0.0.3
  Using cached https://files.pythonhosted.org/packages/f8/d3/6308debad7afcdb3ea5f50b4b3d852f41eb566a311fbcb4da23755a28155/publication-0.0.3-py2.py3-none-any.whl
Collecting jsii~=0.19.0
  Using cached https://files.pythonhosted.org/packages/f9/bd/7f949d09faee6428f60485f537328371ce4358c9fbffac2e4f7d230e21ee/jsii-0.19.0-py3-none-any.whl
Collecting python-dateutil
  Using cached https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl
Collecting importlib-resources; python_version < "3.7"
  Using cached https://files.pythonhosted.org/packages/2f/f7/b4aa02cdd3ee7ebba375969d77c00826aa15c5db84247d23c89522dccbfa/importlib_resources-1.0.2-py2.py3-none-any.whl
Collecting attrs>=18.2
  Using cached https://files.pythonhosted.org/packages/a2/db/4313ab3be961f7a763066401fb77f7748373b6094076ae2bda2806988af6/attrs-19.3.0-py2.py3-none-any.whl
Collecting cattrs
  Using cached https://files.pythonhosted.org/packages/4a/4e/f8bfec0990a2d4f9f79d4417336b761c58c849672cd3b81637a22f02bb20/cattrs-0.9.0-py2.py3-none-any.whl
Collecting typing-extensions>=3.6.4
  Using cached https://files.pythonhosted.org/packages/03/92/705fe8aca27678e01bbdd7738173b8e7df0088a2202c80352f664630d638/typing_extensions-3.7.4.1-py3-none-any.whl
Collecting six>=1.5
  Using cached https://files.pythonhosted.org/packages/65/26/32b8464df2a97e6dd1b656ed26b2c194606c16fe163c695a992b36c11cdf/six-1.13.0-py2.py3-none-any.whl
ERROR: aws-cdk-cx-api 1.16.3 has requirement jsii~=0.20.5, but you'll have jsii 0.19.0 which is incompatible.
Installing collected packages: six, python-dateutil, importlib-resources, attrs, cattrs, typing-extensions, jsii, publication, aws-cdk.cx-api, aws-cdk.core
Successfully installed attrs-19.3.0 aws-cdk.core-1.15.0 aws-cdk.cx-api-1.16.3 cattrs-0.9.0 importlib-resources-1.0.2 jsii-0.19.0 publication-0.0.3 python-dateutil-2.8.1 six-1.13.0 typing-extensions-3.7.4.1

--- 

This is :bug: Bug Report

**Comment by joekiller** [comment]
All versions <1.16.1 had this problem. You'll have to update to 1.16.1 to pin versions.
