### ISSUE TITLE
Peer.anyIpv6() should be ::/0 and not ::0/0

### ISSUE THREAD

**Issue by phillipCouto** [aws/aws-cdk#5043]
Peer.anyIpv6() is using a value that is corrected by AWS VPC when applied, at least in the context of a security group rule. The issue is this results in a stack that has drifted from the original configuration.

### Reproduction Steps

1. Create a stack with a security group that has a rule using Peer.anyIpv6()
2. Deploy the stack
3. Run drift detection
4. See that the stack as drifted because the template wanted to set `::0/0` but AWS normalized it to `::/0`

### Environment

  - **CLI Version: 1.16.260**
  - **Framework Version: 1.12.0**
  - **OS: macOS 10.15.1**
  - **Language: Typescript**

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
Thanks for reporting!

**Comment by phillipCouto** [comment]
No problem @rix0rrr happy to see quick progress on this 😄
