### ISSUE TITLE
JSII error that supertype (MethodDeploymentOptions) does not match subtype (StageOptions)

### ISSUE THREAD

**Issue by mmesserman-verimatrix** [aws/aws-cdk#5044]
Release Notes
https://github.com/aws/aws-cdk/releases

(python version of CDK) It appears that the RestApi constructor parameter for `deploy_options` changed from being of type `aws_cdk.aws_apigateway.MethodDeploymentOptions` to type `aws_cdk.aws_apigateway.StageOptions`. This causes a breaking change during build/execution when using cdk code originally written against older versions (<1.16) with the latest (>=1.16).

The result that appears when running CDK synth in this scenario is:
```bash
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: Wire struct type '@aws-cdk/aws-apigateway.MethodDeploymentOptions' does not match expected '@aws-cdk/aws-apigateway.StageOptions'
```

---

This is a 📕 documentation issue

**Comment by SomayaB** [comment]
Hi @mmesserman-verimatrix, I'm not sure what the issue is here. You've selected the template for documentation issues but it looks more like you're reporting a bug, is that correct? Or are you requesting a documentation update to reflect a change that occurred? Can you give me a little bit more info to help me understand the issue. Thanks!

**Comment by mmesserman-verimatrix** [comment]
Well it could be considered a bug, if the expectation on the part of the cdk developers is that there were no backwards-compatibility changes, but it seemed like an intentional change, to me, so I was recommending that the documentation be modified to indicate that there is a "Breaking Change" around this API.

**Comment by nija-at** [comment]
It doesn't look like we've changed the type of `deployOptions` ever. 

Looking at the commit that introduced this construct library - [b0f3857b](https://github.com/aws/aws-cdk/commit/b0f3857b5f4869c322acfa0108d8b667bfe9cc5a) - `deployOptions` has been of type `StageOptions` which is a sub type of `MethodDeploymentOptions`.

@mmesserman-verimatrix - it doesn't look there was any intended change here. 

However, we have had a few bugs with our JSII library over the last week and have actively worked on fixing and releasing patches. It's possible that you've hit such a bug. 

Can you run your code against our latest CDK release (`1.16.3`) and JSII release (`0.20.6`) and check if you still see this issue? 
You can find the versions you're using by running `pip list` or if you're using `virtualenv`, run `source .env/bin/activate && pip list`.

If you do see this error recur, it would be of great help if you can post the code that's causing this so we can triage it faster.

**Comment by nija-at** [comment]
I gave this a shot and it seems to happen when 

```python
restapi = apig.RestApi(stack,
  'myrestapi',
  deploy_options=apig.MethodDeploymentOptions(metrics_enabled=True)
)
```

but not when 

```python
restapi = apig.RestApi(stack,
  'myrestapi',
  deploy_options=apig.StageOptions(metrics_enabled=True)
)
```

**Comment by mmesserman-verimatrix** [comment]
I'm glad you found that - that is exactly the way that I encountered it. I guess the guys who wrote our CDK stack must have used the parent class instead of the subclass (no idea why we'd do that - maybe an earlier documentation issue), but it only started breaking with the introduction of 1.16.

**Comment by RomainMuller** [comment]
The Python internals are now a little more diligent in reporting expected types of values than it was before. And it does indeed appear that in this particular case the check in the jsii kernel is a little too strict.
