### ISSUE TITLE
metricHealthyHostCount() & metricUnHealthyHostCount() doesn't use required targetGroup dimension

### ISSUE THREAD

**Issue by phaniram** [aws/aws-cdk#5046]
Two of the LB Metrics are HealthyHostCount, HealthyHostCount

https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-cloudwatch-metrics.html

and they're only available with dimension 

LoadBalancer, TargetGroup

but not on 

LoadBalancer alone

where as the methods 

https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-elasticloadbalancingv2/lib/nlb/network-load-balancer.ts

        metricHealthyHostCount()
        metricUnHealthyHostCount()

will use the same dimensions as other metrics without TargetGroup in its dimension.

### Reproduction Steps

doing a simple 

        this.nlbDashboard = new cw.Dashboard(this, 'NLBDashboard', {
            dashboardName: "NLBDashboard",
        });

        const hostCountWidget =  new cw.GraphWidget({
            left: [loadBalancer.metricHealthyHostCount(), loadBalancer.metricUnHealthyHostCount()]
        });

        this.nlbDashboard.addWidgets(hostCountWidget, flowCountWidget, lcuWidget, networkWidget);

would produce a dashboard with a widget having these metrics but no data in it.

### Error Log

No metric displayed using metricHealthyHostCount(), metricUnHealthyHostCount() methods as they miss a required dimension.

### Environment

  - **CLI Version      :**
  - **Framework Version:**
  - **OS               :**
  - **Language         :**

### Other

We can still go ahead and modify the dimensions and plot, but the default methods are supposed to give metrics, where as they aren't here.

Either these have to use the required dimension (without explicit pass from customer) or not be 
here at all.

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
Thanks for the report.

**Comment by rix0rrr** [comment]
So I guess the solution would be to remove the metrics functions from the load balancer object, right? 

Or is there a way to get healthy host count in all target groups behind the load balancer?

**Comment by alex-borkun** [comment]
@rix0rrr please don't remove, they're useful :)
Rather you could find and refer to TargetGroups in `LoadBalancer => Listeners` with `loadBalancer.node.children API` or some other way.

Here are the possible Dimensions from [AWS Docs](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-cloudwatch-metrics.html) :
> **Dimensions**
> TargetGroup, LoadBalancer
> TargetGroup, AvailabilityZone, LoadBalancer
