### ISSUE TITLE
fromStringListParameterName return value should not be parsed

### ISSUE THREAD

**Issue by SomayaB** [aws/aws-cdk#5058]
Based on this comment :

We should add some documentation on `fromStringListParameterName` that explains that the returned value is a token and should not be parsed.

_Originally posted by @eladb in https://github.com/aws/aws-cdk/issues/3540#issuecomment-520768420_

---

This is a 📕 documentation issue

**Comment by rix0rrr** [comment]
@SomayaB would you consider making this change yourself? You could do it directly in GitHub's online editor?

Here's a link that takes you directly where you would need to do the edit:

https://github.com/aws/aws-cdk/edit/master/packages/@aws-cdk/aws-ssm/lib/parameter.ts#L416
