### ISSUE TITLE
dependencies vs peerDependencies

### ISSUE THREAD

**Issue by jd-carroll** [aws/aws-cdk#5064]
In a number of packages there are duplicate dependencies, for example:

[@aws-cdk/aws-kms](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-kms/package.json#L73-L81)
```{json}
  "dependencies": {
    "@aws-cdk/aws-iam": "1.16.1",
    "@aws-cdk/core": "1.16.1"
  },
  "homepage": "https://github.com/aws/aws-cdk",
  "peerDependencies": {
    "@aws-cdk/aws-iam": "1.16.1",
    "@aws-cdk/core": "1.16.1"
  },
```

Is this intentional? If so, what is the advantage of this approach? (I am unfamiliar)

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
We put them under `dependencies` so that they will be automatically installed, and we put them under `peerDependencies` so that if the package that uses THIS package also depends on the given CDK libraries, `npm ls` will complain if the versions aren't the same.

**Comment by rix0rrr** [comment]
Closing this as there is not really any work left to do.
