### ISSUE TITLE
java (dotnet?): arrays in CFN layer are always List<Object>

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#5067]
The type of `subscription` should be `List<CfnTopic.SubscriptionProperty>` but instead it is `List<Object>`.

<img width="620" alt="Screen Shot 2019-11-17 at 9 33 47" src="https://user-images.githubusercontent.com/598796/69004525-63b92100-091d-11ea-85e3-e19b523142bf.png">

### Reproduction Steps

```java
CfnTopic.Builder.create(this, "YourTopic").subscription(...)
```

### Environment

  - **Framework Version:** 1.16.3.DEVPREVIEW
  - **Language         :** Java (& .NET?)

**Comment by RomainMuller** [comment]
The property is typed (in TypeScript) as:

```
Array<SubscriptionProperty | IResolvable> | IResolvable
```

The `List<Object>` java signature is actually the best that can be emitted for this... :(

**Comment by eladb** [comment]
Why we can't generate the following overloads?

```java
subscription(List<Object> subscription)
subscription(IResolvable subscription)
subscription(List<SubscriptionProperty> subscription)
subscription(List<IResolvable> subscription)
```

**Comment by RomainMuller** [comment]
No we cannot - `List<Object>`, `List<SubscriptionProperty>`, and `List<IResolvable>` are all reified to `List` once compiled, so the java dispatcher wouldn't be able to effectively differentiate them (to schematize heavily - one could understand Java generics information is "lost" during compilation).

**Comment by eladb** [comment]
I am wondering if we should sacrifice List<IResolvable> and List<Object> in favor of List<Type> which is the common case and will have a dramatic improvement over the current t state. The other cases could be addressed through escape hatches easily.

**Comment by RomainMuller** [comment]
The only way you can get `List<IResolvable>` sacrificed is by removing the option from the TS code, which would result in a breaking change.

**Comment by RomainMuller** [comment]
Since this is now in the v2.0 issue, resolving this one.
