### ISSUE TITLE
secret from SecretsManager not resolved correctly

### ISSUE THREAD

**Issue by itajaja** [aws/aws-cdk#5070]
the secret doesn't seem to be correctly resolved when used in outputs

### Reproduction Steps

```ts
const secret = secretsManager.Secret.fromSecretArn(
  this,
  'Secrets',
  'arn:aws:secretsmanager:us-east-1:xxx:secret:yyy-secrets-zzz',
);
new cdk.CfnOutput(this, 'testoutput', {
  value: secret.secretValueFromJson('abcdef').toString(),
});
```

produces the following output:

```
app.testoutput = {{resolve:secretsmanager:arn:aws:secretsmanager:us-east-1:xxx:secret:yyy-secrets-zzz:SecretString:abcdef::}}
```

instead of the actual resolved secret
### Environment

using aws-cdk `v1.8.0`

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
This is probably a limitation of the underlying CloudFormation system.

I think they don't expect you to put a secret (something you want to keep hidden) in stack outputs (visible to everyone, will probably appear in CloudFormation logs).

**Comment by itajaja** [comment]
that makes sense. my actual use case is to use a secret from secretsManager as a k8s secret using `aws-cdk`'s `addResource` functionality. in that case as well the secret is not resolved. what would be a good workflow there?

**Comment by arjanschaaf** [comment]
running into the exact same problem creating a k8s secret using CDK + SecretsManager. Any guidance how to make this work would be much appriciated

**Comment by adrialucena-seat** [comment]
Same use case here. It seems something related to `addResource`, that doesn't resolve the value. 
But using `Secret.fromSecretArn` to create an environment variable in an ECS task definition works.
Any workarround for this?

**Comment by njlynch** [comment]
This is a limitation of CloudFormation and dynamic references. From [dynamic references docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/dynamic-references.html#dynamic-references-secretsmanager)

> Dynamic references for secure values, such as secretsmanager, are not currently supported in custom resources.

Tagging @eladb as the k8s expert to suggest if there's any workaround that springs to mind.

**Comment by itajaja** [comment]
thanks. I think we can probably close this issue

**Comment by khamooshi** [comment]
Running into a similar problem creating a Kinesis stream with a `redshiftDestinationConfiguration` where I need to pass Redshift credentials. `redshiftCluster.secret?.secretValueFromJson('password')` is not resolved in CDK code. Any workaround for this?

**Comment by tdalbo92** [comment]
So this is a dead end?  It's not possible to use secrets manager to bind and hydrate secrets into k8s? 

@itajaja If you've found a resolution or workaround, could you share?  We're stuck on this as well.
