### ISSUE TITLE
eks: Managed NodeGroups

### ISSUE THREAD

**Issue by pahud** [aws/aws-cdk#5086]
Amazon EKS announced the support for managed nodegroup today
https://aws.amazon.com/tw/blogs/containers/eks-managed-node-groups/

### Use Case

To create the cluster with a default managed nodegroup.

### Proposed Solution

https://github.com/aws/aws-cdk/blob/2d92ab3e22130408056257d87620a3e03d75b226/packages/%40aws-cdk/aws-eks/lib/cluster.ts#L421-L426

Maybe we can replace this by adding a default managed nodegroup here

We also need to support `--node-volume-size` (like eksctl)

### Other

AWS::EKS::NodeGroup - Managed Node Groups on EKS #264 
https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/264

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by pahud** [comment]
CFN has native support for `AWS::EKS::Nodegroup` now.

And please note the new `AWS::EKS::Cluster` resource also updated and will return the `ClusterSecurityGroupId` attribute for the managed nodegroup.

https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/264#issuecomment-557361433

**Comment by FarshadNiayesh** [comment]
Hi @pahud I used the code below to add a manged node group to the cluster:

`        eks_cluster.add_nodegroup(
            id='managed-nodegroup', 
            desired_size=int(os.environ["APP_DESIRED_CAPACITY"]),
            disk_size=int(os.environ["APP_DISK_SIZE"]), 
            instance_type=ec2.InstanceType(os.environ["APP_INSTANCE_TYPE"]), 
            max_size=int(os.environ["APP_MAX_CAPACITY"]), 
            min_size=int(os.environ["APP_MIN_CAPACITY"]), 
            nodegroup_name=f'eks-{os.environ["APP_NAME"]}-nodegroup', 
            remote_access=eks.NodegroupRemoteAccess(ssh_key_name=f'rpt-production-key-{self.ENVIRONMENT}', 
            # source_security_groups=[eks_sg]
            ),
            # node_role=eks_cluster_role
        )`

But I am getting this error: `

AccessDenied | Your worker nodes do not have access to the cluster. | EKS-Cluster-dev-RPTclusterdevNodegroupmanagednodeg-I0YOXX79E6MW
`

I use this function to create all the roles: 
`def eks_iam_roles(self):
        """ Define a cluster_admin_role that can be assumed by all users in the account"""
        cluster_admin_role = iam.Role(self, f"cluster-admin-role-{self.ENVIRONMENT}",
                                      role_name=f"KubernetesAdmin-{self.ENVIRONMENT}",
                                      assumed_by=iam.AccountRootPrincipal())

        """ Create adminPolicyStatement policy statements for the assume-KubernetesAdmin-role
        managed policies respectively."""
        admin_policy_statement = iam.PolicyStatement(resources=[cluster_admin_role.role_arn],
                                                     actions=[
                                                         "sts:AssumeRole"],
                                                     effect=iam.Effect.ALLOW)

        """ Creating a managed policy from the role and policy statemnt created """
        assume_EKS_admin_role = iam.ManagedPolicy(self, f"assume-eks-admin-role-{self.ENVIRONMENT}",
                                                  managed_policy_name=f"assume-KubernetesAdmin-role-{self.ENVIRONMENT}")

        assume_EKS_admin_role.add_statements(admin_policy_statement)
        
        ## TODO: add S3 and secrets managed policies for the eks_cluster_role
        """ a role that provides permissions for the Kubernetes control plane
        to make calls to AWS API operations on our behalf."""
        eks_cluster_role = iam.Role(self, f"eks-role-{self.ENVIRONMENT}",
                                    assumed_by=iam.ServicePrincipal(
                                        "eks.amazonaws.com"),
                                    managed_policies=[iam.ManagedPolicy.from_aws_managed_policy_name("AmazonEKSServicePolicy"),
                                                      iam.ManagedPolicy.from_aws_managed_policy_name("AmazonEKSClusterPolicy")])

        """ The Amazon EKS construct library allows to specify an IAM role
        that will be granted system:masters privileges on your cluster.
        Without specifying a mastersRole, it's not possible to interact
        manually with the cluster. """

        eks_master_role = iam.Role(self, f"eks-cluster-admin-{self.ENVIRONMENT}",
                                   assumed_by=iam.AccountRootPrincipal())
                                   
        return cluster_admin_role, eks_cluster_role, eks_master_role
`

Can you help me with this?
