### ISSUE TITLE
CfnInstance Metadata example.

### ISSUE THREAD

**Issue by ppsimatikas** [aws/aws-cdk#5087]
Dear AWS CDK developers,

I am trying to use the CfnInstance class documented here: https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_ec2/CfnInstance.html

This documentation is missing 1 critical example for the use of MetaData

I do not see the option of adding metadata to the CfnInstance class. Is that by design?

This is a 📕 documentation issue

**Comment by rix0rrr** [comment]
You would use the "escape hatch" functionality (`addOverride`) to add the proper metadata fields to your resource. 

https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html
