### ISSUE TITLE
Issue Mapping the Java SageMakerTransformJob Enums with the Enums provided in the Stepfunction Task

### ISSUE THREAD

**Issue by dahnny012** [aws/aws-cdk#5113]
## :question: General Issue

Hey CDK team,

I'm building a step function workflow where I have a Java Lambda reading a config file and then the StepFunction task takes that value and uses it to submit a BatchTransform Job.

The issue here is that I am unable to use the SageMaker SDK in java  to construct the parameters because the Enums there can't map to the Enums in the Typescript package. 

https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-stepfunctions-tasks/lib/sagemaker-task-base-types.ts

Here the Enums are all Uppercase however the Enums in Java are regular case. 

If possible could we remap this to be consistent with the Java version?

**Comment by dahnny012** [comment]
the following cant be mapped

```typescript
      task: new tasks.SagemakerTransformTask({
          ....
          batchStrategy:  (<any> tasks.BatchStrategy)[sfn.Data.stringAt("$.sageMakerParametersOutput.ModelConfiguration.BatchStrategy")],
          transformInput: {
              splitType: (<any> tasks.SplitType)[sfn.Data.stringAt("$.sageMakerParametersOutput.ModelConfiguration.TransformInput.SplitType")],
          },
          transformOutput: {
              assembleWith: (<any> tasks.AssembleWith)[sfn.Data.stringAt("$.sageMakerParametersOutput.ModelConfiguration.TransformOutput.AssembleWith")]
          }
          ...
      }
```

**Comment by dahnny012** [comment]
actually I dont think its possible to map a step function param to a enum at the moment during compile time which makes sense.  

How do we support Enums while support step function parameters at the same time?

**Comment by skinny85** [comment]
I believe this is more of a StepFunctions question than a SageMaker one, so I'll move this over.

@rix0rrr can you answer @dahnny012 's question? Thanks!

**Comment by rix0rrr** [comment]
I have to confess I don't understand the issue at all.

> The issue here is that I am unable to use the SageMaker SDK in java

Do you mean the SageMaker CDK Constructs in Java? Or do you mean the AWS SDK?

> Here the Enums are all Uppercase however the Enums in Java are regular case.

Are they? They shouldn't be. The Java docs [are telling me they are uppercase](https://docs.aws.amazon.com/cdk/api/latest/java/index.html).

> the following cant be mapped

That is true. Granted, the code you showed isn't going to work in TypeScript either, as it's indexing an enum with a string that is guaranteed to NOT be in the enum, and will most probably yield `undefined`. But I think I get what you're trying to achieve: you want to use runtime values to control parameters that are typed as enums, and Java will not let you bypass the type system.

If anything is going to work, it would have to be something like:

```
(BatchStrategy)Token.asAny(Data.stringAt("$.sageMakerParametersOutput.ModelConfiguration.BatchStrategy"))
```

But it might totally be that Java is going to serve you a `ClassCastException` if you try to do that.

The limitation here is that it is not possible to use Tokens in place of enum values, and I'm not sure what the solution to that would look like. @RomainMuller, @eladb, any thoughts?

**Comment by SomayaB** [comment]
Closing this issue since there hasn't been any response in a while. Feel free to reopen.
