### ISSUE TITLE
Unable to identify missing local dependencies during build

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#5114]
Since yarn currently hoists all local dependencies into the root node_modules, modules can accidentally use a dependency that they don't declare in their package.json. This causes latent production issues such as #1030

We should figure out a way to disable local-dependency hoisting or not use yarn because this is a huge gap in our test coverage.

**Comment by jogold** [comment]
Solution with ESLint https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-extraneous-dependencies.md

Essential when working with yarn workspaces

Should be integrated in https://github.com/aws/aws-cdk/pull/3430

**Comment by eladb** [comment]
Sounds great
