### ISSUE TITLE
vpc fromLookup: multiple (private) subnets sharing a route table are not classified properly

### ISSUE THREAD

**Issue by jmv12345** [aws/aws-cdk#5123]
### Environment

  - **CLI Version      :**
  - **Framework Version:**
  - **OS               :**
  - **Language         :**

### Other

--- 

This is :bug: Bug Report

**Comment by jmv12345** [comment]
I opened a case with AWS and here is their response:

" I think we managed to figure out why the CDK is behaving the way we observed with your environments.

I'd like to point out this bit of code here that processes a subnet type [1].

     if (this.routeTableIds.length !== this.subnetIds.length && routeTableIds != null) 

The code is checking the number of unique subnet IDs to a route table, and is where we observed the difference between the working environments, and the one that is not working. I will agree that this is not necessarily the best way of identifying what a private subnet is.

The interim solution for this is to create unique subnets for each private subnet, like what we see with the environment that works.

There seems to be older versions of the CDK that does not raise errors when this condition is met. Could you kindly check your CDK version, and ensure it is updated to the latest. We see a commit for the code that provided better warning [2]."

In the AWS environments where the private subnets are properly identified, we have a route table per private subnet. In the environment where private subnets are properly not identified, we have a single route table for all private subnets.

**Comment by SomayaB** [comment]
Hi @jmv12345, thanks for opening an issue. To help us understand your issue better, could you fill out the template by editing the issue. Could you also explain your use case and provide an expected behavior and observed behavior. And can you please provide the version you are using. Thank you!

**Comment by jmv12345** [comment]
If private subnets do not each have a route table, cdk will not detect that there are private subnets. When lambdas are created specifying that private subnets should be used and there is not a single route table for each subnet, the lambdas are placed in all subnets, including DMZ subnets.

At this point I can work around this by creating a route table per subnet. I was working with cdk versions 1.15.0 and 1.16.0. I understand that later versions may throw a warning when private subnets do not each have their own route table, but I have not tested this yet.


### Reproduction Steps

Try placing lambdas in private subnets in a VPC that only has one route table for 3 private subnets (using NAT gateways).


const lambda = require('@aws-cdk/aws-lambda');
const ec2 = require('@aws-cdk/aws-ec2');

const vpcRef = ec2.Vpc.fromLookup(this, 'VPC', {
                             vpcId: 'vpc-f3dad58a'});

 var OasisPolicyCreate = new lambda.Function(this, 'OasisPolicyCreate', {
                        runtime: lambda.Runtime.NODEJS_8_10, // Our standard runtime
                        handler: 'index.handler', // Standard handler
                        //code:       lambda.Code.asset('../deps/oasisworker'),
                        code: lambda.Code.asset(
                                path.join(__dirname, '../dist/oasisworker.zip')
                        ),
                        tracing: lambda.Tracing.ACTIVE, // X-Ray active by default
                        /* functionName : 'OasisPolicyCreate', */
                        vpc: vpcRef,
                        vpcPlacement: {
                                subnetType: ec2.SubnetType.PRIVATE
                        },
                        timeout: Duration.seconds(241),
                        role: OasisPolicyCreateRole,
                        environment: {
                                MYACCOUNT_AUDIT_QUEUE: cfg.MYACCOUNT_AUDIT_QUEUE,
                                mmicEnvironmentURI: cfg.s3_mmicEnvironmentURI,
                                umiaEnvironmentURI: cfg.s3_umiaEnvironmentURI,
                                SQSqueueURL: OasisQueue.queueUrl,
                                policyTable: t_products.tableName,
                                rateTable: cfg.T_RATE_TABLE,
                                paymentsTable: t_payments.tableName,
                                //'claimStatusUpdateTable' : '',
                                oasisIP: cfg.s3_oasisIP,
                                controllingState: cfg.s3_controllingState,
                                CORE_USERS: cfg.T_CORE_USERS, // Ability to lookup users & grant permission to policy
                                creditsSurchargesTable: t_creditsurcharges.tableName
                        }
                });




### Error Log



We are not seeing errors, only that our lambdas are placed in all VPC subnets.


### Environment

  - **CLI Version      :**
1.15.0, 1.16.0
  - **Framework Version:**
1.15.0, 1.16.0
  - **OS               :**
amazon EC2
  - **Language         :**
Javascript

### Other



A warning would be fine, which AWS support said has been added in later versions of cdk. Maybe  documentation on how private subnets are identified would be helpful. In the next few days I will test with the latest version of cdk to see if a warning is thrown.

Hopefully I have filled out the template correctly.

--- 

This is :bug: Bug Report

**Comment by jmv12345** [comment]
I have tested with cdk version 1.17.1.  With this version I am getting cloudformation vpc placement set to:

"SubnetIds": [
            "p-12345",
            "p-67890"
          ]

These are not real subnet IDs. Since this is for a production environment, I have not tested deploying a stack with these SubnetIds.

**Comment by rix0rrr** [comment]
Alright, I'm taking the fact that the subnets were sharing a route table as the probable root cause. Thanks for clarifying.

**Comment by redbaron** [comment]
As a workaround you can tag subnets with `aws-cdk:subnet-type` , then lookup will respect your classification

**Comment by corymhall** [comment]
@jmv12345 Looking at the code it looks like this issue may be fixed. Can you let me know if you are still seeing this issue on the latest version of the CDK?

**Comment by jmv12345** [comment]
This is fixed. I just used cdk 2.4.0 and the vpc private subnets are properly selected when using the directive vpcSubnets directive:

const vpcRef = ec2.Vpc.fromLookup(this, 'VPC', {
                             vpcId: 'vpc-f3dad58a'});

    var DummyLambda = new lambda.Function(this, 'DummyLambda', {
                        runtime: lambda.Runtime.NODEJS_12_X, // Our standard runtime
                        handler: 'index.handler', // Standard handler
                        code: lambda.Code.asset('dummylambda.zip'),
                        vpc: vpcRef,
                        vpcSubnets: {
                                subnetType: ec2.SubnetType.PRIVATE
                        },
                        timeout: Duration.seconds(241),
                });

**Comment by jmv12345** [comment]
The issue is fixed. I just tested with cdk 2.40. I updated the issue with sample code that places the lambda into the correct private subnets.

Jim

From: Cory Hall ***@***.***>
Reply-To: aws/aws-cdk ***@***.***>
Date: Wednesday, February 16, 2022 at 10:11 AM
To: aws/aws-cdk ***@***.***>
Cc: Jim Vergin ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [aws/aws-cdk] vpc fromLookup: multiple (private) subnets sharing a route table are not classified properly (#5123)

CAUTION: This message has originated from an External Source. Please use proper judgment and caution when opening attachments, clicking links, or responding to this email.

@jmv12345<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjmv12345&data=04%7C01%7Cjim.vergin%40constellationmutual.com%7C4901cc976cf44049c52e08d9f166f1fe%7Ce58d8beb03a040d6a31982b7c7e81fbd%7C0%7C0%7C637806246719061215%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=k5vl1roxT8mIDNfvQXsrsNKMjohZ1y4ht4cY2oCBPM0%3D&reserved=0> Looking at the code it looks like this issue may be fixed. Can you let me know if you are still seeing this issue on the latest version of the CDK?

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Faws%2Faws-cdk%2Fissues%2F5123%23issuecomment-1041829964&data=04%7C01%7Cjim.vergin%40constellationmutual.com%7C4901cc976cf44049c52e08d9f166f1fe%7Ce58d8beb03a040d6a31982b7c7e81fbd%7C0%7C0%7C637806246719061215%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=iinV8v6RAcC6iafP0SsVPTf4sQA9R0UAqXFBmP12whE%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAKVD2B7AZW4TQNAE3QU2QQDU3PEB3ANCNFSM4JPNQV5A&data=04%7C01%7Cjim.vergin%40constellationmutual.com%7C4901cc976cf44049c52e08d9f166f1fe%7Ce58d8beb03a040d6a31982b7c7e81fbd%7C0%7C0%7C637806246719061215%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=v24IyHwDYVHJEtYEZawThikNQK6wFXkz70xZOSJcJ2M%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjim.vergin%40constellationmutual.com%7C4901cc976cf44049c52e08d9f166f1fe%7Ce58d8beb03a040d6a31982b7c7e81fbd%7C0%7C0%7C637806246719061215%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ahLuRosvhRiAnzrXNWAFOps6Vr1zZKL9MlbHN6FDoZA%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cjim.vergin%40constellationmutual.com%7C4901cc976cf44049c52e08d9f166f1fe%7Ce58d8beb03a040d6a31982b7c7e81fbd%7C0%7C0%7C637806246719061215%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2F%2FON54V7l4gm2d1T9D0hT0gv0A75gMsTfVB38KrtLFQ%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

This email may contain confidential information. If you are not the intended recipient, or received it in error, do not review or copy. Please immediately notify the sender and permanently delete/destroy the email and any attachments.
