### ISSUE TITLE
How to tag subnets that are shared with another account

### ISSUE THREAD

**Issue by abelmokadem** [aws/aws-cdk#5142]
I have imported a VPC that was shared with my account and several subnets that were created using AWS-CDK. However, VPC sharing does not share the tags on the subnet, so right now I'm not able to use subnet selection in my account with the subnets that were shared with my account. 

Does anyone have an idea on how to solve this?

Cheers,

Ash

**Comment by rix0rrr** [comment]
Hi there,

We'd be happy to help you out, but GitHub issues is not a support forum. There are websites much better suited for that, such as StackOverflow. If you could please [ask that same question again on StackOverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk) and paste the link to it here, we will answer it for you over there.

I will now close this issue, feel free to reopen when pasting the StackOverflow link.

**Comment by abelmokadem** [comment]
I'm a bit confused now. Maybe I didn't phrase the question well enough. I can solve this issue myself by storing tags in the parameter store and then using a script to tag the subnets that were shared. I was just wondering if there is something that can be added to CDK to make vpc sharing easier and compatible with the cdk vpc lookup.

**Comment by CJ-IvoryTech** [comment]
Facing the same issue, anyone can help?
