### ISSUE TITLE
How to run cfn2ts?

### ISSUE THREAD

**Issue by austindimmer** [aws/aws-cdk#5145]
### The Question
I want to convert some existing CloudFormation resources into CDK TypeScript files. I am hoping I can do this with the cfn2ts https://github.com/aws/aws-cdk/tree/master/tools/cfn2ts

How can I run the cfn2ts tool? 

I tried a few things outlined below but could not work out how to run it successfully.

Any help to get this working is much appreciated.

### Environment

  - **CDK CLI Version: 1.17.1 (build fa4cb1f)
  - **OS: Windows Sub-system for Linux
  - **Language:TypeScript

### First failed attempt

(base) austin@AustinM17:/mnt/c/Dev/LS/AWS/CDK/aws-cdk/tools/cfn2ts/bin$ ./cfn2ts.ts -h
/mnt/c/Dev/LS/AWS/CDK/aws-cdk/tools/cfn2ts/bin/cfn2ts.ts:2
import fs = require('fs-extra');
       ^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:872:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)
    at internal/main/run_main_module.js:17:11
(base) austin@AustinM17:/mnt/c/Dev/LS/AWS/CDK/aws-cdk/tools/cfn2ts/bin$ cd ..
(base) austin@AustinM17:/mnt/c/Dev/LS/AWS/CDK/aws-cdk/tools/cfn2ts$ npm install
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/cdk-build-tools - Not found
npm ERR! 404
npm ERR! 404  'cdk-build-tools@1.17.1' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'cfn2ts'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/austin/.npm/_logs/2019-11-21T09_21_27_960Z-debug.log
(base) austin@AustinM17:/mnt/c/Dev/LS/AWS/CDK/aws-cdk/tools/cfn2ts$  

### Second failed attempt   

(base) austin@AustinM17:/mnt/c/Dev/LS/AWS/CDK/aws-cdk/node_modules/.bin$ ./cfn2ts -h
Error: --scope is not provided and cannot be auto-detected from package.json (under "cdk-build.cloudformation")
    at main (/mnt/c/Dev/LS/AWS/CDK/aws-cdk/tools/cfn2ts/bin/cfn2ts.js:19:15)
(base) austin@AustinM17:/mnt/c/Dev/LS/AWS/CDK/aws-cdk/node_modules/.bin$ 

![image](https://user-images.githubusercontent.com/533463/69328358-62566400-0c4f-11ea-97e1-937edd3acd08.png)

### Output from CDK build log

cfn2ts: yarn run v1.17.3
cfn2ts: $ npm run build && npm test
cfn2ts: > cfn2ts@1.17.1 build /mnt/c/Dev/LS/AWS/CDK/aws-cdk/tools/cfn2ts
cfn2ts: > cdk-build
@aws-cdk/cx-api: PASS test/environment.test.js
@aws-cdk/cx-api: PASS test/cloud-assembly-builder.test.js
@aws-cdk/cx-api: PASS test/cloud-assembly.test.js
@aws-cdk/cx-api: =============================== Coverage summary ===============================
@aws-cdk/cx-api: Statements   : 96.67% ( 261/270 )
@aws-cdk/cx-api: Branches     : 86.36% ( 95/110 )
@aws-cdk/cx-api: Functions    : 100% ( 47/47 )
@aws-cdk/cx-api: Lines        : 96.44% ( 244/253 )
@aws-cdk/cx-api: ================================================================================
@aws-cdk/cx-api: Test Suites: 3 passed, 3 total
@aws-cdk/cx-api: Tests:       26 passed, 26 total
@aws-cdk/cx-api: Snapshots:   6 passed, 6 total
@aws-cdk/cx-api: Time:        4.579s
@aws-cdk/cx-api: Ran all test suites.
@aws-cdk/cx-api: Tests successful. Total time (6.7s) | /mnt/c/Dev/LS/AWS/CDK/aws-cdk/node_modules/jest/bin/jest.js (6.6s)
@aws-cdk/cx-api: Done in 22.49s.
@aws-cdk/cloudformation-diff: yarn run v1.17.3
@aws-cdk/cloudformation-diff: $ npm run build && npm test
@aws-cdk/region-info: skipped: [awslint:docs-public-apis:@aws-cdk/region-info.Fact.regions] Public API element must have a docstring
@aws-cdk/region-info: skipped: [awslint:docs-public-apis:@aws-cdk/region-info.RegionInfo.regions] Public API element must have a docstring
@aws-cdk/region-info: skipped: [awslint:docs-public-apis:@aws-cdk/region-info.RegionInfo.name] Public API element must have a docstring
@aws-cdk/cloudformation-diff: > @aws-cdk/cloudformation-diff@1.17.1 build /mnt/c/Dev/LS/AWS/CDK/aws-cdk/packages/@aws-cdk/cloudformation-diff
@aws-cdk/cloudformation-diff: > cdk-build
@aws-cdk/region-info: > @aws-cdk/region-info@1.17.1 test /mnt/c/Dev/LS/AWS/CDK/aws-cdk/packages/@aws-cdk/region-info
@aws-cdk/region-info: > cdk-test
cfn2ts: > cfn2ts@1.17.1 test /mnt/c/Dev/LS/AWS/CDK/aws-cdk/tools/cfn2ts
cfn2ts: > cdk-test
cfn2ts: test.gen.js
cfn2ts: ✔ test me
cfn2ts: OK: 0 assertions (11ms)
cfn2ts: =============================== Coverage summary ===============================
cfn2ts: Statements   : 0% ( 0/682 )
cfn2ts: Branches     : 0% ( 0/312 )
cfn2ts: Functions    : 0% ( 0/121 )
cfn2ts: Lines        : 0% ( 0/649 )
cfn2ts: ================================================================================
cfn2ts: Tests successful. Total time (5.5s) | /mnt/c/Dev/LS/AWS/CDK/aws-cdk/node_modules/nyc/bin/nyc.js (5.4s)
cfn2ts: Done in 14.28s.

**Comment by eladb** [comment]
The tool you are after is https://www.npmjs.com/package/cdk-dasm

**Comment by austindimmer** [comment]
> The tool you are after is https://www.npmjs.com/package/cdk-dasm

Thanks. I see now this is not a great idea.
