### ISSUE TITLE
Typescript documentation site down

### ISSUE THREAD

**Issue by kevin-lindsay-1** [aws/aws-cdk#5148]
https://docs.aws.amazon.com/cdk/api/latest/typescript/api/index.html
is currently only showing the "cfnspec" namespace.

### Environment

  - **CLI Version      :**
  - **Framework Version:**
  - **OS               :**
  - **Language         :**

### Other

--- 

This is :bug: Bug Report

**Comment by eladb** [comment]
Yes, confirming we are having an issue with the TypeScript reference documentation website. We will report back as soon as this is resolved.

Pinning issue.

**Comment by eladb** [comment]
This has been resolved

**Comment by eladb** [comment]
So sorry for the bad experience. We will do our best so this doesn't occur again.
