### ISSUE TITLE
Can't read context in aws cdk construct when unit testing

### ISSUE THREAD

**Issue by jzhang777** [aws/aws-cdk#5149]
## :question: General Issue
Can't read context in aws cdk construct when unit testing
Here is the type script code in cdk constuct:
```
const ENV_NAME = this.node.tryGetContext("ENV_NAME") ?
this.node.tryGetContext("ENV_NAME") : ``;
        if (_.isEmpty(ENV_NAME)) {
            throw new Error('ENV_NAME context is required...')
        }
```
Following is the error when unit testing from my jest unit test after run...

 FAIL  test/cdk.predeploy.test.ts
  ✕ Empty Stack (5ms)

  ● Empty Stack

    ENV_NAME context is required...

Need help! Thanks.

### Environment

  - **CDK CLI Version:** 
  - **Module Version:** 
  - **OS:** 
  - **Language:**

**Comment by joekiller** [comment]
Set the context in the properties of App() when it is declared and you should be good.

https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.AppProps.html

**Comment by jzhang777** [comment]
Thanks @joekiller . It works now by following your instruction.

**Comment by tamizharasanr** [comment]
@joekiller 
But when I have other than a string type parameter in cdk.json which I can't set in App context while doing the testing.
Let's say I have the following property but when I try to do the testing I can't set integer in the app context. How to make this work?
```
"eks.nodeGroupDesiredCapacity": 3,
```

**Comment by joekiller** [comment]
@tamizharasanr it looks like app.ts [context.json](https://github.com/aws/aws-cdk/blob/5597bbe64446a07041f5469fc0897544448d4e95/packages/%40aws-cdk/core/lib/app.ts#L158) won't be properly populated unless [exec.ts](https://github.com/aws/aws-cdk/blob/0f0e2055cab08551bc6e5dfb8a1b6219368263c5/packages/aws-cdk/lib/api/cxapp/exec.ts) is loaded first which appears to only get loaded by the native cdk node program [bin/cdk.ts](https://github.com/aws/aws-cdk/blob/ac748c1786e68774f5d0ea9cfbec439034166c40/packages/aws-cdk/bin/cdk.ts#L11) so for tests you are stuck with setting your own context.

If you really really want to hack it in you can set in your environment 

    CDK_CONTEXT_JSON={"eks.nodeGroupDesiredCapacity":3}

and that'll work because [that key is set](https://github.com/aws/aws-cdk/blob/5597bbe64446a07041f5469fc0897544448d4e95/packages/%40aws-cdk/cx-api/lib/cxapi.ts#L5) when app loads

**Comment by jzhang777** [comment]
Thanks much. It helpful.

Jing Zhang

Sr. Software Engineer
Information Technology

The College Board
11955 Democracy Drive, Reston, VA 20190<webextlink://11955%20Democracy%20Drive,%20Reston,%20VA%2020190>

T 571-485-3310
zjing@collegeboard.org<mailto:zjing@collegeboard.org>

Clearing a path for all students to own their future

**Comment by bbrfkr** [comment]
I hope to load context of `cdk.json` when `npm test` run!

**Comment by maria-jackson** [comment]
I never figured out how to do this with some of my nested context values, but I did get my testing to work in Python when I refactored like this. May not be the best option for you, but it works.

```python
def my_method()
    app = core.App()

    app.node.try_get_context("thing")
    app.node.try_get_context("thing2")
```
And the mocking...
```python
self.expected_app = MagicMock()
self.mock_app = patch("aws_cdk.core.App")
self.mock_app.return_value = self.expected_app
self.expected_app.node.try_get_context.side_effect = [
    "thing",
    "thing2"
]
```

**Comment by thiagobasilio-nanga** [comment]
Using `CDK_CONTEXT_JSON` environment variable worked for me. However, when I tried to use `AppProps`, it didn't. At least, one of the available choices worked.

**Comment by tuliocasagrande** [comment]
Inspired by @jpSimkins above, this worked in Python:

```python
import json

import aws_cdk as cdk
import aws_cdk.assertions as assertions
from cdk.cdk_stack import CdkStack

with open("cdk.json") as fr:
    context = json.load(fr)["context"]


def test_sqs_queue_created():
    app = cdk.App(context=context)
    stack = CdkStack(app, "cdk")
    template = assertions.Template.from_stack(stack)

    ...
```

**Comment by RajasGujarathi** [comment]
Thanks @tuliocasagrande. 

_Can someone help in the below scenario_
Some parameters in the context are set using `cdk.json` and some are passed during synth/deploy time `cdk synth --context Environment=AbC`. How to read the context while unit testing `python3 -m pytest`, when the context is set from 2 places. (_Effective context is a union of both contexts_)
