### ISSUE TITLE
Stack defined in Java init template doesn't take props

### ISSUE THREAD

**Issue by Jerry-AWS** [aws/aws-cdk#5155]
The stack defined in the Java init template doesn't accept a props argument, making the user revise their constructor if they want to be able to pass in, say, an environment.

I'd suggest providing two constructors, one with props and one without, to match the behavior in other init templates. To wit:

```java
public class JavaJiveStack extends Stack {
    public JavaJiveStack(final Construct scope, final String id) {
        this(scope, id, null);
    }

    public JavajiveStack(final Construct scope, final String id, StackProps props) {
        super(scope, id, props);

        // The code that defines your stack goes here
    }
}
```

You'll also need an import for StackProps now.

--- 

This is :bug: Bug Report

**Comment by shivlaks** [comment]
@Jerry-AWS  thanks for reporting, will take a look at this one

**Comment by RomainMuller** [comment]
In fact this was already updated, but the new templates haven't been released *just yet*.

**Comment by SomayaB** [comment]
Closing this issue since the fix has already been implemented and is just waiting to be released.
