### ISSUE TITLE
aws-ecs:  Firelens log driver support

### ISSUE THREAD

**Issue by pahud** [aws/aws-cdk#5156]
AWS::ECS::TaskDefinition supports `FirelensConfiguration` now

https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/265#issuecomment-557380075

### Proposed Solution

Let's build a firelens log driver for [aws-ecs/lib/log-drivers](https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/aws-ecs/lib/log-drivers).

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by pkandasamy91** [comment]
@PettitWesley will pick this one up

**Comment by tsykora-verimatrix** [comment]
+1. My organisation would also appreciate CDK support for Firelens and we'd love to use it as our main logging driver going forward. CF support is there, CDK support would be awesome.
