### ISSUE TITLE
Cognito: Add "From" attribute of AWS::Cognito::UserPool EmailConfiguration

### ISSUE THREAD

**Issue by duarten** [aws/aws-cdk#5165]
Add the  "From" attribute of AWS::Cognito::UserPool EmailConfiguration to interface EmailConfigurationProperty of CfnUserPool.

### Use Case

When using Cognito's CustomMessage trigger, this attribute allows the sender's name to be displayed instead of just the e-mail address.

---

This is a :rocket: Feature Request

**Comment by cvrajeesh** [comment]
If anyone looking for a workaround till this feature is implemented, here is how to do it

```
const cfnUserPool = this.userPool.node.defaultChild as CfnUserPool;
    cfnUserPool.emailConfiguration = {
      emailSendingAccount: ....,
      replyToEmailAddress: ...,
      sourceArn: ....
    };
    cfnUserPool.addPropertyOverride(
      "EmailConfiguration.From",
      "Name <no-reply@example.com>"
    );
```

**Comment by nija-at** [comment]
I have a proposal to implement CDK APIs for Congito - https://github.com/aws/aws-cdk-rfcs/pull/91 - that will address this issue. 

The RFC is in the comments period. If you'd like to see how the API is going to look and propose changes, this is your chance.

**Comment by nija-at** [comment]
@duarten - looks like this is now available - https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cognito.CfnUserPool.EmailConfigurationProperty.html#from
