### ISSUE TITLE
Move secret rotation to aws-secretsmanager and add aws-secretsmanager-targets

### ISSUE THREAD

**Issue by jogold** [aws/aws-cdk#5194]
AWS Secrets Manager just announced support for Redshift and DocumentDB: https://aws.amazon.com/about-aws/whats-new/2019/11/aws-secrets-manager-easier-rotate-secrets-through-cloudformation/

The `SecretRotation` class is currently located in `aws-rds` but should be moved to `aws-secretsmanager`.

Secret target attachements should be implemented in a separate package `aws-secretsmanager-targets` (integration pattern).

Serverless applications should be updated to their latest version which include lambda permissions.

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
100% agreed.

**Comment by nsithamb** [comment]
Can this be used with redshiftserverless?
