### ISSUE TITLE
Can not enable Performance Insights for DatabaseCluster

### ISSUE THREAD

**Issue by vertti** [aws/aws-cdk#5195]
I would like to enable Performance Insights for my RDS Postgresql cluster but it doesn't seem to be possible.

### Reproduction Steps

`DatabaseInstanceProps` has a key `enablePerformanceInsights` but `DatabaseClusterProps` does not have that key. Also the `instanceProps` contained inside `DatabaseClusterProps` is `InstanceProps` type and does not have the `enablePerformanceInsights` key either.

### Environment

  - **CLI Version      :** 1.18.0
  - **Framework Version:** 1.18.0
  - **OS               :** Ubuntu
  - **Language         :** Typescript

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hey @vertti ,

unfortunately, the [`Cluster` resource](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbcluster.html) does not have an `enablePerformanceInsights` property, unlike the [`Instance` resource](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html), so I don't think this can actually be done.

Thanks,
Adam

**Comment by SomayaB** [comment]
Closing this issue. Feel free to reopen.

**Comment by vincent-dm** [comment]
We are also facing this issue. Currently our workaround is to get the instance identifiers and then enable performance insights using the SDK, which feels like a hack. What is the recommended way to enable performance insights using CDK on instances created using `DatabaseCluster`?

**Comment by mikevoets** [comment]
You can now enable performance insights with CDK v2 by setting `enablePerformanceInsights` in the `instanceProps` object:

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_rds.InstanceProps.html
https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_rds.InstanceProps.html#enableperformanceinsights

**Comment by Aarbel** [comment]
> You can now enable performance insights with CDK v2 by setting `enablePerformanceInsights` in the `instanceProps` object:
> 
> https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_rds.InstanceProps.html https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_rds.InstanceProps.html#enableperformanceinsights

@mikevoets no way to do it with CDK v1 ?

**Comment by mikevoets** [comment]
> > You can now enable performance insights with CDK v2 by setting `enablePerformanceInsights` in the `instanceProps` object:
> > https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_rds.InstanceProps.html https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_rds.InstanceProps.html#enableperformanceinsights
> 
> @mikevoets no way to do it with CDK v1 ?

There doesn't seem to be any official way to do it in CDK v1. I don't know v1 so I don't know if there's any workaround.

**Comment by Aarbel** [comment]
@mikevoets 

after a full day of diving, with 1.135.0 i did this:


```JS
const kmsKey = kms.Key.fromKeyArn(
  this,
  "rdsKmsKeyForPerformanceInsights",
  RDS_KMS_KEY_ARN
);

new rds.DatabaseCluster(this, "Database", {
  credentials,
  engine: rds.DatabaseClusterEngine.auroraPostgres({
    version: rds.AuroraPostgresEngineVersion.VER_13_4,
  }),
  instanceProps: {
    enablePerformanceInsights: true,
    parameters: {
      log_min_duration_statement: 500,
    },
    performanceInsightEncryptionKey: kmsKey,
    performanceInsightRetention: rds.PerformanceInsightRetention.LONG_TERM,
    instanceType: ec2.InstanceType.of(
      ec2.InstanceClass.BURSTABLE3,
      ec2.InstanceSize.XLARGE
    ),
    vpc,
  },
  removalPolicy: cdk.RemovalPolicy.RETAIN,
});

```

**Comment by MichaelWalker-git** [comment]
It's wild, that despite it being Q4 2024 and instanceProps being deprecated, there is no way to do this via the CDK still

**Comment by mikevoets** [comment]
> It's wild, that despite it being Q4 2024 and instanceProps being deprecated, there is no way to do this via the CDK still

This is how I solved it via CDK:

```typescript
new rds.DatabaseCluster(this, "Database", {
  vpc,
  writer: rds.ClusterInstance.provisioned('WriterInstance', { 
    instanceType: new ec2.InstanceType('t3.medium'),
    enablePerformanceInsights: true,
    # other instanceProps parameters ...
  }),
  # other parameters ...
});
```
