### ISSUE TITLE
Support for ECS DeploymentController

### ISSUE THREAD

**Issue by konstantinj** [aws/aws-cdk#5196]
I've just found out that Cloudformation supports the ecs deploymentcontroller configuration. When will this be supported by CDK?

### Use Case

Real blue/green deployment with only one ecs service is something that lots of people are interested in.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by SoManyHs** [comment]
Note that full support for blue/green deployments will require CFN support in CodeDeploy.

Related: https://github.com/aws/aws-cdk/issues/2056, https://github.com/aws/containers-roadmap/issues/130
