### ISSUE TITLE
aws-ecs to support service action events

### ISSUE THREAD

**Issue by pahud** [aws/aws-cdk#5203]
https://aws.amazon.com/tw/about-aws/whats-new/2019/11/amazon-ecs-service-events-now-available-as-cloudwatch-events/

### Use Case

When we create any ecs service, we can listen all available service events on it.

### Other

https://github.com/aws/containers-roadmap/issues/19

Service Action Events
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs_cwe_events.html#ecs_service_events

* [v] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by hencrice** [comment]
Left 2 comments on the draft PR. Removed needs-triage label because the PR is in-progress

**Comment by kewur** [comment]
the PR seems to have been canceled.
