### ISSUE TITLE
When creating CloudWatch Event Rules, all event pattern filters are converted to strings

### ISSUE THREAD

**Issue by bf-sodle** [aws/aws-cdk#5205]
### Reproduction Steps

I'm trying to create a CloudWatch event rule for GuardDuty findings. In order to match events by severity, I need to specify an array of matching number values as follows:

```
new events.CfnRule(this, "guardduty-rule", {
      name: "guardduty-findings",
      description: "GuardDuty Findings",
      state: "ENABLED",
      eventPattern: {
        source: ["aws.guardduty"],
        "detail-type": ["GuardDuty Finding"],
        detail: {
          severity: [
            5.5,
            5.6,
            5.7,
            5.8,
            5.9,
            6,
            6.1,
            6.2,
            6.3,
            6.4,
            6.5,
            6.6,
            6.7,
            6.8,
            6.9,
            7,
            7.0,
            7.1,
            7.2,
            7.3,
            7.4,
            7.5,
            7.6,
            7.7,
            7.8,
            7.9,
            8,
            8.0,
            8.1,
            8.2,
            8.3,
            8.4,
            8.5,
            8.6,
            8.7,
            8.8,
            8.9
          ]
        }
      }
    });
```

However, when using either the `Rule` or `CfnRule` constructor, the numeric values in the array are converted to string, causing them to not match. This is what I see in the CloudWatch Events console: 

```
{
  "detail-type": [
    "GuardDuty Finding"
  ],
  "source": [
    "aws.guardduty"
  ],
  "detail": {
    "severity": [
      "5.5",
      "5.6",
      "5.7",
      "5.8",
      "5.9",
      "6",
      "6.1",
      "6.2",
      "6.3",
      "6.4",
      "6.5",
      "6.6",
      "6.7",
      "6.8",
      "6.9",
      "7",
      "7",
      "7.1",
      "7.2",
      "7.3",
      "7.4",
      "7.5",
      "7.6",
      "7.7",
      "7.8",
      "7.9",
      "8",
      "8",
      "8.1",
      "8.2",
      "8.3",
      "8.4",
      "8.5",
      "8.6",
      "8.7",
      "8.8",
      "8.9"
    ]
  }
}
```

How do I input these as numbers instead of strings?

### Error Log

No error message, just unexpected behavior.

### Environment

  - **CLI Version:** aws-cli/1.16.260 Python/3.7.5 Darwin/18.7.0 botocore/1.12.250
  - **Framework Version:** 1.15.0
  - **OS:** macOS 10.14.6
  - **Language:** TypeScript

### Other

Perhaps you could allow us to provide a string for `eventPattern`, to escape whatever parsing is being done by the CDK or by CloudFormation?

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
Interesting. I can't think of why that would be happening, but I'll investigate.

**Comment by bf-sodle** [comment]
It looks like it might be a CloudFormation bug rather than a CDK one, but I'm not sure.

**Comment by jogold** [comment]
Related https://github.com/awslabs/serverless-application-model/issues/681

**Comment by krutsko** [comment]
+1

**Comment by rix0rrr** [comment]
Please make sure the issue has been reported to CloudFormation directly as well: https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap

**Comment by jogold** [comment]
It's here https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/251

**Comment by rrhodes** [comment]
This issue appears to be resolved - I see the [linked CloudFormation issue](https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/251) is closed. A test stack using container exit codes in the Rule detail property worked as I would expect: retaining numbers rather than converting to strings.

**Comment by peterwoodworth** [comment]
linked issue is resolved. this can be closed
