### ISSUE TITLE
class CfnDBCluster missing EnableHttpEndpoint property

### ISSUE THREAD

**Issue by aripalo** [aws/aws-cdk#5216]
Allow setting `EnableHttpEndpoint` boolean-property for [`CfnDBCluster`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-rds.CfnDBCluster.html) in RDS module.

### Use Case

We need this feature for configuring Aurora Serverless cluster with [Data API](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/data-api.html). 

Currently we have to solve this by using hacky CloudFormation custom resource which invokes a Python Lambda function where Boto3 enables the Data API:
```python
client = boto3.client('rds')
client.modify_db_cluster(
  DBClusterIdentifier=database_cluster_identifier,
  EnableHttpEndpoint=True
)
```

This feels completely unnecessary and it's also error-prone.

### Proposed Solution

CloudFormation released [support for `EnableHttpEndpoint` in November 21st 2019](https://docs.amazonaws.cn/en_us/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html):
![Screenshot 2019-11-27 at 16 31 29](https://user-images.githubusercontent.com/679146/69731969-7ad4eb80-1133-11ea-9152-146538a218e6.png)

As [`EnableHttpEndpoint`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbcluster.html#cfn-rds-dbcluster-enablehttpendpoint) is now available in CloudFormation for `AWS::RDS::DBCluster` resource it'd be nice if that same property would be available for CDK's `CfnDBCluster` class.

This would allow people to get rid of hacky and error-prone CloudFormation custom resources that are only used for enabling the Data API.

* [ ] :wave: I may be able to implement this feature request

---

This is a :rocket: Feature Request

**Comment by skinny85** [comment]
Hey @aripalo ,

thanks for opening the issue. We should get the `enableHttpEndpoint` property in `CfnDBCluster` when we update the CloudFormation specification, which we do every week.

Thanks,
Adam

**Comment by metaskills** [comment]
Thank y'all, very much 👁 this issue with anticipation.

**Comment by skinny85** [comment]
Should be done in https://github.com/aws/aws-cdk/pull/5339

**Comment by skinny85** [comment]
Actually, it was done here: https://github.com/aws/aws-cdk/pull/5297/files?file-filters%5B%5D=.json#diff-8e1268ed8f9bcc6e8d19f5283fcd7779R46731

Just waiting on the latest release `1.19.0` to have it available.

**Comment by metaskills** [comment]
I've confirmed the 1.19.0 release works as expected. This issue can be closed I think?

**Comment by skinny85** [comment]
Cool, thanks for checking @metaskills . Resolving.
