### ISSUE TITLE
Importing aws_cdk.aws_batch throws: "'aws_cdk.core' has no attribute 'IInspectable'"

### ISSUE THREAD

**Issue by jaidisido** [aws/aws-cdk#5217]
I am attempting to use the ```aws_cdk.aws_batch``` library for a Python project. When running the ```cdk bootstrap``` command, the below error is thrown. This error only appears with aws_batch and none of the other libraries.

### Reproduction Steps

```python
cdk bootstrap
```

### Error Log

```python
Traceback (most recent call last):
  File "app.py", line 6, in <module>
    from telemetry_lzo.telemetry_lzo import TelemetryBatchLZO
  File "/Users/jaidi/Documents/Python/TelemetryBatchMigration/telemetry_lzo/telemetry_lzo.py", line 2, in <module>
    from aws_cdk import aws_ecs, aws_ec2, aws_s3, aws_batch
  File "/Users/jaidi/Documents/Python/TelemetryBatchMigration/.env/lib/python3.7/site-packages/aws_cdk/aws_batch/__init__.py", line 34, in <module>
    @jsii.implements(aws_cdk.core.IInspectable)
AttributeError: module 'aws_cdk.core' has no attribute 'IInspectable'
Subprocess exited with error 1
```

### Environment

  - **CLI Version: 1.18.0**
  - **Framework Version: 1.18.0**
  - **OS: macOS Mojave 10.14.6**
  - **Language: Python**

### Other

--- 

This is a :bug: Bug Report

**Comment by skinny85** [comment]
Hey @jaidisido ,

can you:

1.  Show the version of the dependencies with `pip list`
2. Show the version of the CDK CLI you're using with `cdk --version`.

?

Thanks,
Adam

**Comment by yinghong** [comment]
I got the same error. 
pip list:
Package                             Version  
----------------------------------- ---------
attrs                               19.1.0   
aws-cdk.assets                      1.8.0    
aws-cdk.aws-apigateway              1.8.0    
aws-cdk.aws-applicationautoscaling  1.18.0   
aws-cdk.aws-autoscaling             1.8.0    
aws-cdk.aws-autoscaling-common      1.18.0   
aws-cdk.aws-autoscaling-hooktargets 1.8.0    
aws-cdk.aws-certificatemanager      1.8.0    
aws-cdk.aws-cloudformation          1.8.0    
aws-cdk.aws-cloudfront              1.8.0    
aws-cdk.aws-cloudwatch              1.8.0    
aws-cdk.aws-codebuild               1.8.0    
aws-cdk.aws-codecommit              1.8.0    
aws-cdk.aws-codepipeline            1.8.0    
aws-cdk.aws-dynamodb                1.18.0   
aws-cdk.aws-ec2                     1.8.0    
aws-cdk.aws-ecr                     1.8.0    
aws-cdk.aws-ecr-assets              1.8.0    
aws-cdk.aws-ecs                     1.8.0    
aws-cdk.aws-elasticache             1.14.0   
aws-cdk.aws-elasticloadbalancing    1.8.0    
aws-cdk.aws-elasticloadbalancingv2  1.8.0    
aws-cdk.aws-elasticsearch           1.14.0   
aws-cdk.aws-events                  1.8.0    
aws-cdk.aws-events-targets          1.8.0    
aws-cdk.aws-iam                     1.18.0   
aws-cdk.aws-kms                     1.8.0    
aws-cdk.aws-lambda                  1.8.0    
aws-cdk.aws-logs                    1.8.0    
aws-cdk.aws-route53                 1.8.0    
aws-cdk.aws-route53-targets         1.8.0    
aws-cdk.aws-s3                      1.8.0    
aws-cdk.aws-s3-assets               1.8.0    
aws-cdk.aws-secretsmanager          1.8.0    
aws-cdk.aws-servicediscovery        1.8.0    
aws-cdk.aws-sns                     1.8.0    
aws-cdk.aws-sns-subscriptions       1.8.0    
aws-cdk.aws-sqs                     1.8.0    
aws-cdk.aws-ssm                     1.8.0    
aws-cdk.aws-stepfunctions           1.8.0    
aws-cdk.core                        1.14.0   
aws-cdk.custom-resources            1.8.0    
aws-cdk.cx-api                      1.14.0   
aws-cdk.region-info                 1.18.0   
boto3                               1.9.229  
botocore                            1.12.231 
cattrs                              0.9.0    
certifi                             2019.9.11
chardet                             3.0.4    
click                               6.7      
colorama                            0.3.9    
docutils                            0.15.2   
elasticsearch                       7.0.4    
elasticsearch-curator               5.7.6    
future                              0.17.1   
idna                                2.8      
importlib-metadata                  0.23     
importlib-resources                 1.0.2    
jedi                                0.14.1   
jmespath                            0.9.4    
jsii                                0.20.8   
more-itertools                      7.2.0    
parso                               0.5.1    
pip                                 19.2.3   
pluggy                              0.13.0   
publication                         0.0.3    
pyasn1                              0.4.7    
python-dateutil                     2.8.0    
python-jsonrpc-server               0.2.0    
python-language-server              0.28.3   
PyYAML                              3.12     
requests                            2.22.0   
requests-aws4auth                   0.9      
rsa                                 3.4.2    
s3transfer                          0.2.1    
setuptools                          41.2.0   
six                                 1.12.0   
typing-extensions                   3.7.4    
urllib3                             1.24.3   
voluptuous                          0.11.7   
wheel                               0.33.6   
zipp                                0.6.0

cdk --version
1.18.0 (build bc924bc)

**Comment by skinny85** [comment]
Yep, you have a mix of `1.14.0` and `1.18.0` packages in there. Can you call `pip install --upgrade`, and see if that helps?

**Comment by SomayaB** [comment]
Closing this issue since there hasn't been a response in a while. Feel free to reopen.
