### ISSUE TITLE
Add support for CodePipeline variables

### ISSUE THREAD

**Issue by thomasklinger1234** [aws/aws-cdk#5219]
CodePipeline recently introduced variables in stages. CloudFormation support is available. 

There should be an extension to CodePipeline stages to allow for variables. In the first place, using it through a property in stages is fine. 

In a second stage there could also be an opportunity to construct the reference (`#{namespace.variable_key}`) through a CDK construct and provide a `render()` method to get the actual variable as accepted by CodePipeline.

When there are no reasons to not implement is, I would be happy to provide a PR.

### Use Case

Extending my current pipelines to use dynamic references (e.g. creating CloudFormation changesets based on git commit id).

### Proposed Solution

Extend [@aws-cdk/aws-codepipeline/lib/action.ts:: CommonActionProps](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-codepipeline/lib/action.ts) with the `namespace` property (optional). 

### Other

- CodePipeline docs: https://docs.aws.amazon.com/codepipeline/latest/userguide/reference-variables.html
- CloudFormation docs: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codepipeline-pipeline-stages-actions.html#cfn-codepipeline-pipeline-actiondeclaration-namespace

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by skinny85** [comment]
Thanks for opening the feature request @thomasklinger1234 !

Feel free to take a stab at an implementation PR, I'd be glad to review it :).

Thanks,
Adam
