### ISSUE TITLE
Add support for deployment path in S3DeployAction

### ISSUE THREAD

**Issue by redi-kilicb** [aws/aws-cdk#5223]
In the AWS Console, when you add an S3 deploy action to CodePipeline, you can specify the Deployment Path. But the cdk does not allow you to specify this:

https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-codepipeline-actions/lib/s3/deploy-action.ts

### Use Case

In order to deploy to a specific location in the S3 bucket instead of always the root.

### Proposed Solution

Add optional deploymentPath property here: https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-codepipeline-actions/lib/s3/deploy-action.ts

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by skinny85** [comment]
@redi-kilicb this is the documentation of the S3 deploy action in the [CodePipeline reference]():

Name of Provider | Provider Name in Action Type | Configuration Properties | Required Property?
-- | -- | -- | --
Amazon S3 (Deploy action provider) | S3 | |
| |  | BucketName | Required
| | | Extract | Required
| | | ObjectKey | Required if Extract = false
| | | KMSEncryptionKeyARN1 | Optional
| | | CannedACL2 | Optional
| | | CacheControl3 | Optional

I don't see `DeploymentPath` here... did you mean `ObjectKey` maybe? We do already support that one.

**Comment by SomayaB** [comment]
Closing this issue since there hasn't been a response in a while. Feel free to reopen.

**Comment by xcepti0n** [comment]
I think deployment path here stands for the folder name, when extracted is true.
Whereas with ObjectKey, complete fileName with path needs to be specified also when the extract is false.

Console does provide a way to ender deploymentPath, but S3DeployAction does not. Do tell if it does in some other way.

**Comment by skinny85** [comment]
Hello @xcepti0n ,

in fact there is only one attribute that controls the path in the S3 deploy Action, and it works like you described:

* If `extract` is `true` (which is the default in the CDK), `objectKey` is the "folder name" where the contents will be extracted (S3 doesn't actually have a concept of folders, but you know what I mean).
* If `extract` is `false`, `objectKey`  is the full path of the file to be put into the target Bucket, including its file name.

This is consistent with the AWS Console:

`extract` is true:

<img width="806" alt="Screen Shot 2020-09-21 at 9 28 52 AM" src="https://user-images.githubusercontent.com/460937/93794445-f33df900-fbec-11ea-92d3-50dab14e000a.png">

`extract` is false:

<img width="846" alt="Screen Shot 2020-09-21 at 9 29 16 AM" src="https://user-images.githubusercontent.com/460937/93794461-f638e980-fbec-11ea-9dc7-df930852f00f.png">

**Comment by xcepti0n** [comment]
Thanks @skinny85 for the detailed explanation. As the names were different on console and the documentation doesn't mention it, therefore I got confused. Now I got it.

**Comment by skinny85** [comment]
No problem @xcepti0n , glad we got it resolved!

**Comment by jzybert** [comment]
Is there a way to have `extract: false` but retain the "folder" path structure?

Example: My artifact is path in the `buildspec.yml` is `/v1.5/app.exe` and I would like that to be outputted in S3 using the `S3DeployAction` as `/v1.5/app.zip`. Right now, you have to manually specify an `objectKey` but you don't have access to the original artifact path

**Comment by jzybert** [comment]
The error I get when I try and do `artifact.s3Location.objectKey`:
```
The error was Template Error: Encountered unsupported function: Fn::GetArtifactAtt Supported functions are: [Fn::Base64, Fn::GetAtt, Fn::GetAZs, Fn::ImportValue, Fn::Join, Fn::Split, Fn::FindInMap, Fn::Select, Ref, Fn::Equals, Fn::If, Fn::Not, Condition, Fn::And, Fn::Or, Fn::Contains, Fn::EachMemberEquals, Fn::EachMemberIn, Fn::ValueOf, Fn::ValueOfAll, Fn::RefAll, Fn::Sub, Fn::Cidr]
```

**Comment by skinny85** [comment]
Yes, `artifact.s3Location.objectKey` is not supported as a `path` (that is supported only in the parameter overrides of the CloudFormation deploy Stack action).

I think what you want is to create an artifact in CodeBuild containing `/v1.5/app.zip`, and then just have root as the `path`.

**Comment by jzybert** [comment]
Is there a supported `zip` buildspec command for a `WindowsBuildImage.WIN_SERVER_CORE_2019_BASE`? I think right now that's my hangup on the suggestion, not sure how properly zip it

**Comment by skinny85** [comment]
You can use PowerShell on that platform, so it should be easy. Quick Googling found [this](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.archive/compress-archive?view=powershell-7.2), for example.

**Comment by egriffith** [comment]
Reopening this issue. I just spent much longer than should be needed trying to figure out how to get S3Deploy to extract to a prefix. I eventually assumed it just wasn't possible and was preparing to write a codebuild step to do it instead, until I found this issue. 

Can we please do a docs update so that the "ObjectKey" property notes that if extract is true then this property becomes "the prefix base path where the zip contents should be extracted" (or similar) and if extract is false then this property represents the actual zip file object key. Currently the property makes no mention about the fact that it also represents the base path for extraction if extract = true.

**Comment by skinny85** [comment]
@egriffith would you consider submitting a PR, clarifying the documentation of the `objectKey` property? The documentation is [here](https://github.com/aws/aws-cdk/blob/beac6753021138ee56abdbf02eef0318f7098dde/packages/aws-cdk-lib/aws-codepipeline-actions/lib/s3/deploy-action.ts#L59-L61).
