### ISSUE TITLE
Docs indicate `Map<K, V>` type where plain JavaScript object (used as a map) is intended

### ISSUE THREAD

**Issue by jenniwu** [aws/aws-cdk#5235]
When calling `Metric.createAlarm()` or new `Alarm()` with AlarmProps, I should be able to define a dimensions map and generate a corresponding CloudFormation template.
 
### Use Case
Cloudwatch Alarms support the definition of Dimension property in the CloudFormation template: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cw-alarm.html.
 
### Proposed Solution
Add an optional field in `CreateAlarmOptions` (which is extended by `AlarmProps`) representing dimensions (type `DimensionHash`). 

In `Metric.createAlarm()`, pass in the dimensions at metric level. 

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
Could you tell me why:

```ts
metric.with({ dimensions: { A: B, C: D}}).createAlarm()
```

Does not work for you?

**Comment by jenniwu** [comment]
https://github.com/aws/aws-cdk/blob/36431300677c5984525362a0f16d1da9bdd4b489/packages/%40aws-cdk/aws-cloudwatch/lib/metric.ts#L162-L165
This does not consider the dimensions.

**Comment by rix0rrr** [comment]
I'm not sure it won't.

Can you please provide a reproducible sample of the code where this is not working for you?

**Comment by jenniwu** [comment]
```
const dimensions = new Map<string, any>();
dimensions.set('Resource', '/my-resource');
dimensions.set('ApiName, 'MyService');
dimensions.set('Stage, 'prod');
dimensions.set('Method', 'MyMethod');

const apiGatewayCountAlarm = new cloudwatch.Metric({
  metricName: 'Count',
  namespace: 'AWS/ApiGateway',
  period: cdk.Duration.minutes(5),
  statistic: 'Sum',
  dimensions,
}).createAlarm(this, 'ApiGatewayCountMetricAlarm', {
  evaluationPeriods: 1,
  threshold: 1000,
  treatMissingData: TreatMissingData.IGNORE,
});
```

In the CloudFormation template it generates, dimensions are dropped from the alarm.

**Comment by rix0rrr** [comment]
```
        const dimensions = {
            Resource: '/my-resource',
            ApiName: 'MyService',
            Stage: 'prod',
            Method: 'MyMethod',
        };
```

We never have `new Map()` in the public APIs, it's always just plain JavaScript objects.

I now see that the documentation does say `Map<string, any>`. The `Map` there is more to indicate how the JavaScript object literal is supposed to be interpreted, rather than its literal type, but I see how this is incredibly confusing. I will repurpose this ticket into a documentation bug.
