### ISSUE TITLE
Lambda Event Source - failure handling for kinesis and dynamodb event sources

### ISSUE THREAD

**Issue by advaj** [aws/aws-cdk#5236]
Adding additional settings to Lambda Event Sources for handling failures while processing DynamoDB and Kinesis Streams

### Use Case

On Nov 25th, Lambda announced support for failure handling while processing DynamoDB and Kinesis Streams. This allows Lambda to take actions like retry limits, bisect on error etc and not retry the entire batch of records being processed. The feature announcement is here - https://aws.amazon.com/about-aws/whats-new/2019/11/aws-lambda-supports-failure-handling-features-for-kinesis-and-dynamodb-event-sources/

Currently, only batch size, starting position and max batching window are the additional parameters that are supported. 

This helps in reducing the number of retries and also avoids processing duplicate entries. 

### Other

The Cloud Formation resource is documented here - 
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-eventsourcemapping.html

The specific additional fields that I am requesting for are: 

      "BisectBatchOnFunctionError" : Boolean,
      "DestinationConfig" : DestinationConfig,
      "MaximumBatchingWindowInSeconds" : Integer,
      "MaximumRecordAgeInSeconds" : Integer,
      "MaximumRetryAttempts" : Integer,
      "ParallelizationFactor" : Integer

---

This is a :rocket: Feature Request

**Comment by xerofun** [comment]
Anyone working this yet?  I've been getting my build environment ready so that I could add these parameters in and started working it Friday.

**Comment by SomayaB** [comment]
Hi @xerofun, there hasn't been any work on this yet but it is a good first issue so you are welcome to have a go at it and create a PR yourself. Otherwise, we will update this issue when there is movement.

**Comment by xerofun** [comment]
Couldn't quite figure out how to assign it to the awslabs/aws-cdk group for review.  They didn't seem to show up in assignees
