### ISSUE TITLE
[lambda] support MaximumEventAge and MaximumRetryAttempts

### ISSUE THREAD

**Issue by nija-at** [aws/aws-cdk#5239]
https://aws.amazon.com/about-aws/whats-new/2019/11/aws-lambda-supports-max-retry-attempts-event-age-asynchronous-invocations/

---

This is a :rocket: Feature Request

**Comment by nija-at** [comment]
It seems that this feature is not available in CloudFormation yet. CDK can start supporting this only when CloudFormation supports it.

**Comment by jogold** [comment]
See https://github.com/aws/aws-cdk/issues/5240#issuecomment-559482525

**Comment by nija-at** [comment]
Thanks for pointing that out @jogold.
