### ISSUE TITLE
[lambda] support lambda destinations

### ISSUE THREAD

**Issue by nija-at** [aws/aws-cdk#5240]
https://aws.amazon.com/blogs/compute/introducing-aws-lambda-destinations/

---

This is a :rocket: Feature Request

**Comment by nija-at** [comment]
It seems that this feature is not available in CloudFormation yet. CDK can start supporting this only when CloudFormation supports it.

**Comment by jogold** [comment]
@nija-at it is supported. The resource is `AWS::Lambda::EventInvokeConfig`, needs an update of the specs.

**Comment by nija-at** [comment]
Thanks for pointing that out @jogold.
