### ISSUE TITLE
cdk init --language=java fails with IOException: Stream Closed

### ISSUE THREAD

**Issue by Raniz85** [aws/aws-cdk#5241]
When creating a new CDK project the intial build falis.

It fails in the same way if I try to execute `cdk ls` in the created project directory afterwards.

### Reproduction Steps
* Install NodeJS via NVM
* Install CDK from NPM
* Install Maven from package manager
* Try to init a new Java project

### Error Log
Complete log [here](https://pastebin.com/GUy1njJZ)

### Environment
My laptop:

  - **CLI Version      :*1.18.0*
  - **Framework Version:*1.18.0*
  - **OS               :*Arch Linux*
  - **Language         :*Java*
  - **Maven version   :*3.6.3*
  - **Java Version     :*1.8.0_232*
  - **NodeJS Version    :*v13.2.0"

Ubuntu 18.04 in EC2:

  - *CLI Version      :*1.18.0*
  - **Framework Version:*1.18.0*
  - **OS               :*Ubuntu 18.04*
  - **Language         :*Java*
  - **Maven version   :*3.6.3*
  - **Java Version     :*11.0.4*
  - **NodeJS Version    :*v13.2.0"

### Other
I've tried both locally and on a newly started EC2 instance and get the same error. I've dug around a bit with the Java debugger and managed to extract stderr from JsiiRuntime.java which says this:

```
internal/fs/utils.js:220
    throw err;
    ^

Error: EAGAIN: resource temporarily unavailable, read
    at Object.readSync (fs.js:516:3)
    at SyncStdio.readLine (/tmp/jsii-java-runtime7279641471746997836/jsii-runtime.js:13322:25)
    at InputOutput.read (/tmp/jsii-java-runtime7279641471746997836/jsii-runtime.js:13272:34)
    at KernelHost.run (/tmp/jsii-java-runtime7279641471746997836/jsii-runtime.js:7228:32)
    at Immediate.<anonymous> (/tmp/jsii-java-runtime7279641471746997836/jsii-runtime.js:7236:37)
    at processImmediate (internal/timers.js:439:21) {
  errno: -11,
  syscall: 'read',
  code: 'EAGAIN'
}
```

--- 

This is :bug: Bug Report

**Comment by eladb** [comment]
Looks like a dup of https://github.com/aws/aws-cdk/issues/5187. Can you try to downgrade your node v13.1.0 or less and see if this is resolved. Reopen if this is a different issue.
