### ISSUE TITLE
cli: improve colors used in CLI output to be friendly for dark/light background terminals

### ISSUE THREAD

**Issue by wolverian** [aws/aws-cdk#5242]
<img width="353" alt="Screenshot 2019-11-28 at 16 33 04" src="https://user-images.githubusercontent.com/42124/69814499-f8b0f980-11fc-11ea-94f6-fb63dda3c400.png">

### Reproduction Steps

Run `cdk init app --language=typescript` in a Terminal with a light background color. I used VS Code Insiders with the [i Light](https://marketplace.visualstudio.com/items?itemName=ctrlplusb.i-minimal-theme) color theme.

### Environment

  - **CLI Version      :** 1.18.0 (build bc924bc)
  - **Framework Version:**
  - **OS               :** macOS Catalina 10.15.1 (19B88)
  - **Language         :** 

### Other

In general I recommend disabling color output unless the user explicitly requests it.

--- 

This is :bug: Bug Report

**Comment by shivlaks** [comment]
@wolverian - are you able to use the `--no-color` option successfully?

**Comment by shivlaks** [comment]
the option can also be set as a preference in `~/.cdk.json` if that's a desired default

```json
{
"no-color": true
}
```

**Comment by rix0rrr** [comment]
Even if `--no-color` works, I would still propose that we don't have `logging.print()` add color.

**Comment by wolverian** [comment]
I can report that `--no-color` removes color from the output, thank you.

**Comment by shivlaks** [comment]
@rix0rrr - I can see the benefit there as well... I was briefly looking at [chalk](https://www.npmjs.com/package/chalk) and [yargonaut](https://www.npmjs.com/package/yargonaut) as better alternatives. happy to repurpose this issue into a feature request.

did you have something different in mind?

**Comment by wolverian** [comment]
So, there are two features here that I would like:

- Make the output equally readable on all dark and light backgrounds, and
- Don't use colors, _or_ support the `NO_COLOR` environment variable (ref. https://no-color.org).

**Comment by l0b0** [comment]
Why is this closed? There is a workaround, but the default is still colour (which is very useful) and the contrast is pretty bad on a dark background:

![Screenshot from 2020-12-15 12-02-42](https://user-images.githubusercontent.com/168301/102146339-a442ef80-3ecd-11eb-92e6-12caa90e689a.png)
