### ISSUE TITLE
How to create a conditional Glue trigger with predicates is not clearly documented. A sample would help.

### ISSUE THREAD

**Issue by ksadeghi** [aws/aws-cdk#5251]
---

This is a 📕 documentation issue

**Comment by ksadeghi** [comment]
I am struggling with creating a Glue workflow in my Python cdk script.
Specifically I want to create a trigger that is waiting for a set of Glue jobs to successfully complete before performing its action

**Comment by SomayaB** [comment]
Hi @ksadeghi, I've created a [feature request](https://github.com/aws-samples/aws-cdk-examples/issues/205) in the aws-samples/aws-cdk-examples repo.
