### ISSUE TITLE
BastionHostLinux

### ISSUE THREAD

**Issue by tomred-net** [aws/aws-cdk#5264]
### The Question
I would like to SSH to the bastion host created using the CDK. The [docs](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ec2.BastionHostLinux.html) declare that "You can also configure this bastion host to allow connections via SSH". This I assume is the `bastion.allowSshAccessFrom` method but there does not appear to be anywhere to select the ssh key pair for the host to use. 

Can you advise if I have missed something or is this unlike the [Instance ](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ec2.Instance.html) class which provides a means of specifying keyName as a configuration property.

### Environment

  - **CDK CLI Version:** 1.18.0
  - **Module Version:** 1.18.0
  - **OS:** Windows 10 | Ubuntu
  - **Language:** Java

**Comment by hoegertn** [comment]
Hi, using `bastion.allowSshAccessFrom` you can allow SSH traffic to your bastion host. To avoid sharing SSH keys you should use the EC2 instance connect feature to provide your temporary SSH key to the instance upon connect.

https://aws.amazon.com/about-aws/whats-new/2019/06/introducing-amazon-ec2-instance-connect/?nc1=h_ls

**Comment by tomred-net** [comment]
That is interesting thank you @hoegertn. We use our bastion as a ssh tunnel to access RDS and other private resources your suggested approach will work. I'll be interested to see how our team respond. I will close this on the basis of your response.
