### ISSUE TITLE
Glue database: is locationUri required?

### ISSUE THREAD

**Issue by cartmanez** [aws/aws-cdk#5268]
### The Question

Hi!

I tried creating glue database and noticed that if I don't specify locationUri, CDK creates one for me by creating an S3 bucket.
Here's the [source code](https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-glue/lib/database.ts#L97)

Just wondering, was that that intentional? Location URI is not a required parameter in Cloudformation - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-database-databaseinput.html#cfn-glue-database-databaseinput-locationuri .

### Environment

  - **CDK CLI Version:** 1.18.0 
  - **Module Version:** 1.18.0
  - **OS:** GNU/Linux
  - **Language:** TypeScript

**Comment by skinny85** [comment]
That's a good question!

@sam-goodwin (who is the author of this library), can you chime in on this one? Thanks!

**Comment by machielg** [comment]
A database without a location is valid. Always creating or expecting a bucket uri is not desired behavior IMO.

My current workaround is to specify a blank but not empty string as location
{databaseName: "mydb", locationUri: ' '}) 

Perhaps the uriLocation should be of "enum | string" type. The default should be no location.

Enum values: 
CREATE_BUCKET
NONE

**Comment by sam-goodwin** [comment]
I have vague memories of running into problems with no location but it's very possible I was doing something else wrong. I agree, if we can default to no location then we should do that. The forced bucket is a total nuisance.

**Comment by andreanerla** [comment]
I'm having problems because of no URI db locations, see [link](https://stackoverflow.com/questions/76613845/aws-glue-error-when-reading-from-data-catalog-with-iceberg-s3exception-access/76613853#76613853)
