### ISSUE TITLE
How to pass S3 ARN as payload to Step Functions task?

### ISSUE THREAD

**Issue by rschweizer** [aws/aws-cdk#5270]
### The Question

In the AWS [docs](https://docs.aws.amazon.com/step-functions/latest/dg/avoid-exec-failures.html) is described, that we should pass large payloads to a Step Functions task using an S3 ARN. However, it's unclear to me, how to achieve this using the CDK. Can anybody give me a pointer please?

### Environment

  - **CDK CLI Version:** 1.17.1
  - **Module Version:** 1.18.0
  - **OS:** macOS Catalina
  - **Language:** TypeScript

**Comment by nija-at** [comment]
Hello @rschweizer -

Sorry it's taken us so long to revert back to your query.

This isn't something solely achievable via the CDK. 

Using Stepfunctions, you pass the [S3 object's ARN](https://docs.aws.amazon.com/AmazonS3/latest/dev/s3-arn-format.html) as a data field between the task producing the data and the task consuming the data. 
See [here](https://docs.aws.amazon.com/AmazonS3/latest/dev/s3-arn-format.html) for more information on how to define data fields and pass them between states.

The CDK helps you define the state machine definition which, among many things, also defines what output fields of a task should be passed as input to which other tasks. 

Hope that helps. 
Feel free to re-open this task if I there was something else you were looking for, and I missed to address that.

**Comment by Smotrov** [comment]
I believe there is a wrong link in your phrase _See here for more information_
