### ISSUE TITLE
Cloudformation cannot delete AWS::RDS::DBSubnetGroup when DBInstance ist set to retain

### ISSUE THREAD

**Issue by konstantinj** [aws/aws-cdk#5282]
When creating either a dbcluster or dbinstance with all options to default it is not possible to delete the cloudformation stack afterwards since the dbinstance is per default set to retain but cfn still tries to delete the AWS::RDS::DBSubnetGroup which is not possible because the instance depends on it.

### Reproduction Steps

create a dbcuster or a dbinstance

```typescript
        const database = new rds.DatabaseCluster(this, 'DatabaseCluster', {
            defaultDatabaseName: 'test',
            masterUser: {
                username: 'test',
            },
            instances: 1,
            engine: rds.DatabaseClusterEngine.AURORA,
            instanceProps: {
                instanceType: ec2.InstanceType.of(ec2.InstanceClass.T3, ec2.InstanceSize.SMALL),
                vpc: vpc,
                vpcSubnets: {
                    subnetType: ec2.SubnetType.PRIVATE,
                }
            }
        });
```

### Error Log

cloudformation will not finish the deletion and time out after 4 hours of trying.

### Environment

  - **CLI Version      :1.18.0**
  - **Framework Version:1.18.0**
  - **OS               :osx**
  - **Language         :typescript**

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hey @konstantinj ,

thanks for opening the issue. This is a tradeoff between the defaults, which we want to be safe (we don't want to people accidentally deleting their database), and the desire the experiment.

Could perhaps changing `AWS::RDS::DBSubnetGroup` to also retain if the DB is retain be a satisfactory compromise here?

Thanks,
Adam

**Comment by mjsilva** [comment]
@skinny85 thanks for the clarification I just bumped on this today while testing CDK. I think it makes sense to leave `removalPolicy` retain by default. Maybe we just need to document or find a way to let the user know this is the expected behaviours before hand? If you have any suggestion where to document this I'm happy to open a PR.

I'm retesting with `removalPolicy: RemovalPolicy.DESTROY` and will report back how it goes.

**Comment by mjsilva** [comment]
`RemovalPolicy.DESTROY` works perfectly. So for now I added a `...: isProduction ? RemovalPolicy.RETAIN : RemovalPolicy.DESTROY` on stateful resources like DB, Logs etc...
