### ISSUE TITLE
superset template matching issue

### ISSUE THREAD

**Issue by tk3369** [aws/aws-cdk#5287]
### The Question
How does `beASupersetOfTemplate` work?  When I add a new attribute in the template, it fails.  When I delete an attribute from the template, it also fails.  I don't see how it differs from exact match so far.

An example has been uploaded to https://github.com/tk3369/aws-cdk-unit-testing/blob/master/test/cdk-jest-test.test.ts

It's basically a simple S3 bucket creation script.  Test case 1 is exact match, which works properly.  Test case 2 and 3 both failed.  

### Environment

```
$ cdk version
1.16.3 (build 8c7f593)

$ cat package.json 
{
  "name": "cdk-jest-test",
  "version": "0.1.0",
  "bin": {
    "cdk-jest-test": "bin/cdk-jest-test.js"
  },
  "scripts": {
    "build": "tsc",
    "watch": "tsc -w",
    "test": "jest",
    "cdk": "cdk"
  },
  "devDependencies": {
    "@aws-cdk/assert": "^1.16.3",
    "@types/jest": "^24.0.22",
    "@types/node": "10.17.5",
    "jest": "^24.9.0",
    "ts-jest": "^24.1.0",
    "aws-cdk": "^1.16.3",
    "ts-node": "^8.1.0",
    "typescript": "~3.7.2"
  },
  "dependencies": {
    "@aws-cdk/aws-s3": "^1.18.0",
    "@aws-cdk/core": "^1.16.3",
    "source-map-support": "^0.5.16"
  }
}
```

**Comment by tk3369** [comment]
Ping.... any idea?

**Comment by RomainMuller** [comment]
Superset should allow additional properties, but not removed properties. That may only apply from a certain depth of the object graph here (I vaguely remember something along those lines, but not for sure). What you're trying to do looks reasonable to me, though, so I reckon it should be made workable.

**Comment by eladb** [comment]
This seems to me like a bug. Filing as one.

**Comment by eladb** [comment]
In the meantime, can you try to use `haveResource` instead?

**Comment by SomayaB** [comment]
Hi @tk3369, have you been able to try `haveResource` ?

**Comment by SomayaB** [comment]
Closing for now since there hasn't been a response in a while. Feel free to reopen.
