### ISSUE TITLE
Embed recording of Contributing to the CDK re:Invent talk 

### ISSUE THREAD

**Issue by PaulMaddox** [aws/aws-cdk#5289]
The *Contributing to the AWS CDK* talk at re:Invent (by @leepa and @rix0rrr)  walks through creating a CDK construct from scratch, and covers a lot of useful information on how we approach creating CDK constructs and their best practices.

It would be good to have the YouTube video embedded in the CONTRIBUTING.md

---

This is a 📕 documentation issue

**Comment by Jerry-AWS** [comment]
This content will very likely be integrated into the CDK Developer Guide before too long.  :-)

**Comment by djwelch** [comment]
Is this the video https://www.youtube.com/watch?v=eqKxp5MzuVA?

**Comment by PaulMaddox** [comment]
Yes, that’s the one 👍

**Comment by cmckni3** [comment]
Is that video private now?

**Comment by SomayaB** [comment]
@cmckni3 I also see that video as private but it looks like maybe it was moved. Is [this](https://youtu.be/LsYlf7ggyrY) the same video?

**Comment by cmckni3** [comment]
@SomayaB Thanks! That appears to be the video.

**Comment by Jerry-AWS** [comment]
The CDK Developer Guide finally has a Videos page... or at least it will once the build finishes. I made sure to include this video.

It'll be at https://docs.aws.amazon.com/cdk/latest/guide/videoshtml within the next 24 hours.
