### ISSUE TITLE
Support cluster settings of ECS cluster

### ISSUE THREAD

**Issue by zxkane** [aws/aws-cdk#5296]
CloudFormation already supports the ECS cluster settings, such as `containerInsights`.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-cluster-clustersetting.html

### Use Case

Allow specifying this setting via both low level CfnCluster and high level Cluster API.

### Proposed Solution

Add optional setting prop to ClusterProps.

### Other

* [ x ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by zxkane** [comment]
Not sure how to generate the low level `CfnXXX` class. Any hint would be appreciated.

**Comment by hencrice** [comment]
PR looks good. Removed "needs-triage" label.

**Comment by MrArnoldPalmer** [comment]
Looks like this is already merged. https://github.com/aws/aws-cdk/pull/5601
