### ISSUE TITLE
aws-apigateway: support HttpApi

### ISSUE THREAD

**Issue by pahud** [aws/aws-cdk#5301]
Announcing HTTP APIs for Amazon API Gateway
https://aws.amazon.com/blogs/compute/announcing-http-apis-for-amazon-api-gateway/

### Other

AWS::ApiGatewayV2::Api

    Use the AWS::ApiGatewayV2::Api resource to create an HTTP API (beta).
AWS::ApiGatewayV2::Authorizer

    Use the AWS::ApiGatewayV2::Authorizer resource to create a JWT authorizer for an HTTP API (beta).
AWS::ApiGatewayV2::Integration

    Use the AWS::ApiGatewayV2::Integration resource to create an integration for an HTTP API (beta).
AWS::ApiGatewayV2::Stage

    Use the AWS::ApiGatewayV2::Stage resource to create a stage for an HTTP API (beta).

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by bionicles** [comment]
HttpApi:
  Type: AWS::ApiGatewayV2::Api
  Properties:
    Name: Lambda Proxy
    Description: Lambda proxy using quick create
    **ProtocolType: HTTP <—one line of code**
    Target: arn:aws:apigateway:{region}:lambda:path/2015-03-31/functions/arn:aws:lambda:{region}:{account-id}:function:{function-name}/invocations

**Comment by pahud** [comment]
Hi @nija-at 

Are we planning to build a new **aws-apigatewayv2** L2  just like **aws-elasticloadbalancingv2** or just extending the existing **aws-elasticloadbalancing** with `AWS::ApiGatewayV2::*` support?

**Comment by farzad-xgen** [comment]
When this will be ready? We really need this!
