### ISSUE TITLE
feat(cfnspec):  update CloudFormation Resource Specification to v10.0.0

### ISSUE THREAD

**Issue by pahud** [aws/aws-cdk#5302]
we got a few features pending on the v10.0.0 spec

### Use Case

https://github.com/aws/aws-cdk/issues/5156

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by shivlaks** [comment]
@pahud - I'm on it!

**Comment by pahud** [comment]
Wow @shivlaks thanks a lot!
