### ISSUE TITLE
VPC Factory function problem

### ISSUE THREAD

**Issue by KarlHarrisSungardAS** [aws/aws-cdk#5305]
### The Question

How can I remove the dummy vpc from the stack given the VPC.fromLookup() call did not find the correct vpc?

#### Synthesizer error with account number redacted:

```Error at /svt1stackv2] Could not find any VPCs matching {"account":xxxxxxxxxx,"region":"us-east-1","filter":{"vpc-id":"vpc-newTestID","isDefault":"false"},"returnAsymmetricSubnets":true}```

### Environment

  - **CDK CLI Version:** 1.18.0 (build bc924bc)
  - **Module Version:** @aws-cdk/aws-ec2
  - **OS:** OSX High Sierra 10.13.6
  - **Language:** TypeScript 

### Other information
https://gitter.im/awslabs/aws-cdk?at=5dddc07dc8b1546fd148a50b

**Comment by rix0rrr** [comment]
There is no conditional way to do this. If you want to import a VPC, it has to be there, or your CDK app becomes undeployable.

If you want to sometimes import a VPC and sometimes not, you will have to go around the CDK framework to do either a lookup in your app, or pass a parameter from a bash script or similar which will have encoded the knowledge on whether there is a VPC present to import or not.

**Comment by KarlHarrisSungardAS** [comment]
I would suggest a name change of Vpc.fromLookup to Vpc.getExistingVPC. The name fromLookup implies one can detect if a VPC exists then get the IVPC information for that vpc.
