### ISSUE TITLE
API Gateway proxy Lambda loses permissions when functionName is changed

### ISSUE THREAD

**Issue by masse-solita** [aws/aws-cdk#5306]
### Reproduction Steps

1. Create an API Gateway RestAPI and a LambdaIntegration
2. Deploy
3. Change the Lambda's functionName property.
4. Deploy

### Error Log
API Gateway fails to invoke the function and reports:
Execution failed due to configuration error: Invalid permissions on Lambda function

### Environment

  - **CLI Version**      : 1.18.0 (build bc924bc)
  - **Framework Version**: 1.18.0
  - **OS**               : Mac OSX
  - **Language**         : TypeScript

### Other
--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
Ack'ing this issue. Changing the function name in a API Gateway Lambda integration does break the integration.

Repro code -
```ts
import lambda = require('@aws-cdk/aws-lambda');
import apig = require('@aws-cdk/aws-apigateway');
import core = require('@aws-cdk/core');

const app = new core.App();
const stack = new core.Stack(app, 'mystack');

const handler = new lambda.Function(stack, 'myfunction', {
    functionName: 'myfunctionname-1',
    code: lambda.Code.fromAsset('resources'),
    runtime: lambda.Runtime.NODEJS_10_X,
    handler: 'index.handler'
});

const restapi = new apig.RestApi(stack, 'myrestapi');

restapi.root.addMethod('ANY', new apig.LambdaIntegration(handler));
```

**Comment by OG84** [comment]
Omg spent 2 days figuring out why i get an `AuthorizerConfigurationException` 500 response.
Until I found this issue :)
