### ISSUE TITLE
C# escape hatch example throws Unhandled exception. System.ArgumentException: Could not infer JSII type for .NET type 'List`1' (Parameter 'type')

### ISSUE THREAD

**Issue by drch-** [aws/aws-cdk#5317]
The code from the escape hatch documentation throws an exception.
https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html#cfn_layer_cfn

```Unhandled exception. System.ArgumentException: Could not infer JSII type for .NET type 'List`1' (Parameter 'type')```

### Reproduction Steps

Sample code
```csharp
using System.Collections.Generic;
using Amazon.CDK;

namespace Cdkcf
{
    public class CdkcfStack : Stack
    {
        internal CdkcfStack(Construct scope, string id, IStackProps props = null) : base(scope, id, props)
        {
            new CfnResource(this, "MyBucket", new CfnResourceProps
            {
                Type = "AWS::S3::Bucket",
                Properties = new Dictionary<string, object>
                {   // Note the PascalCase here! These are CloudFormation identifiers
                    ["AnalyticsConfigurations"] = new List<Dictionary<string, string>>
                    {
                        new Dictionary<string, string> {
                            ["Id"] = "Config"
                        }
                    }
                }
            });
        }
    }
}

```

### Error Log

```Unhandled exception. System.ArgumentException: Could not infer JSII type for .NET type 'List`1' (Parameter 'type')```

### Environment

  - **CLI Version      :** aws-cli/1.16.276 Python/3.7.5 Darwin/18.7.0 botocore/1.13.12
  - **Framework Version:** 1.18.0 (build bc924bc)
  - **OS               :** macOS
  - **Language         :** C#

### Other

Workaround: use array or .ToArray() on the list

--- 

This is :bug: Bug Report

**Comment by Jerry-AWS** [comment]
Might just need to correct this in the documentation (it looks like this came from the Dev Guide)
