### ISSUE TITLE
Implement an L2 for SAML providers

### ISSUE THREAD

**Issue by hoegertn** [aws/aws-cdk#5320]
Implement an L2 for SAMl providers

### Proposed Solution

Implement a custom resource to create SAML providers. No CFN support available

* [X] :wave: I will implement this feature request

---

This is a :rocket: Feature Request

**Comment by hoegertn** [comment]
@eladb I think it should be in the `iam` package. It has nothing to do with Cognito.

**Comment by eladb** [comment]
Thanks @hoegertn

**Comment by rix0rrr** [comment]
Yeah I've been thinking about this. Looks like a good idea, but I don't have a good idea of what all would be involved in it.

**Comment by hoegertn** [comment]
I think the MVP would be creating a SAML IdP from a local metadata file and being able to reference it in IAM roles as a principal in the assume role policy document.

**Comment by hoegertn** [comment]
@eladb I would love to implement this and several other constructs for IAM but the custom resource package depends on IAM. Any wishes where I should put the constructs? Will the monocdk fix these issues?

**Comment by jogold** [comment]
> but the custom resource package depends on IAM. Any wishes where I should put the constructs? Will the monocdk fix these issues?

In those cases you can always use the custom resource provider from core: https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/core#the-corecustomresourceprovider-class
