### ISSUE TITLE
Implement aws_cloudfront.CustomErrorResponseProperty in Python

### ISSUE THREAD

**Issue by tomomano** [aws/aws-cdk#5322]
Implement [aws_cloudfront.CustomErrorResponseProperty](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cloudfront.CfnDistribution.CustomErrorResponseProperty.html) in Python

### Use Case
This feature is apparently available in [TypeScript](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cloudfront.CfnDistribution.CustomErrorResponseProperty.html), but is missing in Python.

To properly route my Vue-generated SPA app hosted on S3 and distributed with CloudFront, I need to set this parameter. Otherwise, one cannot "directly" open subdirectories of SPA app deployed with "history" routing mode (as discussed [here](https://stackoverflow.com/a/47554827)). So I think there is in general good demand for this functionality.

### Proposed Solution

I know cloud_front module is still at beta, but I would love to see this feature coming soon!

---

This is a :rocket: Feature Request

**Comment by iliapolo** [comment]
@tomomano We might have an issue with the python documentation of nested classes. But the property you are looking for actually exists in python as well:

```python
cloudfront.CfnDistribution(self, "MyDist", distribution_config=cloudfront.CfnDistribution.DistributionConfigProperty(
    custom_error_responses=[
        cloudfront.CfnDistribution.CustomErrorResponseProperty(
            error_caching_min_ttl=42,
            error_code=42,
            response_code=42,
            response_page_path="42"
            )
    ],
    enabled=True
))

```

**Comment by tomomano** [comment]
@iliapolo Thank you for the information!

You're right, [the documentation](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cloudfront.CfnDistribution.CustomErrorResponseProperty.html) somehow says that the Python module path is `aws_cdk.aws_cloudfront.CustomErrorResponseProperty`, but the right path seems to be `aws_cdk.aws_cloudfront.CfnDistribution.CustomErrorResponseProperty`


According to your suggestion, I defined my `CloudFrontWebDistribution` in the following way, and it worked like a charm! Thank you so much for your help 😊

```python
from aws_cdk import aws_cloudfront as cfront

distribution = cfront.CloudFrontWebDistribution(
    self, "CloudFrontDistribution",
    error_configurations=[
        cfront.CfnDistribution.CustomErrorResponseProperty(
            error_caching_min_ttl=0,
            error_code=403,
            response_code=200,
            response_page_path="/index.html"
        ),
        cfront.CfnDistribution.CustomErrorResponseProperty(
            error_caching_min_ttl=0,
            error_code=404,
            response_code=200,
            response_page_path="/index.html"
        )
    ],
)
```


`

**Comment by iliapolo** [comment]
@tomomano Perfect, closing this issue :)

**Comment by sdil** [comment]
https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_cloudfront/CloudFrontWebDistribution.html

![image](https://user-images.githubusercontent.com/461537/90136569-f1d81000-dda6-11ea-87ad-5b4ca8adcd1a.png)

this part of CDK Cloudfront doc still confuses me because I cannot click on the `CustomErrorResponseProperty` property
