### ISSUE TITLE
[EKS] Failed to run eks.ClusterResource if upgrade lambda-layer-kubectl to 2.0.0-beta1

### ISSUE THREAD

**Issue by walkley** [aws/aws-cdk#5328]
eks.ClusterResource [lambda function](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-eks/lib/cluster-resource/index.py) raise exception if I upgrade lambda-layer-kubectl to 2.0.0-beta1

### Reproduction Steps
1. Upgrade version of [lambda-layer-kubectl](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-eks/lib/kubectl-layer.ts#L6) to 2.0.0-beta1:
    ```
    const KUBECTL_APP_VERSION = '2.0.0-beta1';
    ```
2. Create EKS Cluster: new eks.Cluster(...) then deploy cdk stack

### Error Log
Exception raised in lambda function:
Traceback (most recent call last):
  File "/var/task/index.py", line 192, in cfn_send
    response = requests.put(responseUrl, data=body, headers=headers)
AttributeError: module 'botocore.vendored.requests' has no attribute 'put'

### Environment

  - **CLI Version      :**
  - **Framework Version:** v1.18.0
  - **OS               :** Linux
  - **Language         :** Typescript

### Other
Actually lambda-layer-kubectl is unnecessary in [eks.ClusterResource](https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-eks/lib/cluster-resource.ts#L49), it's not used by any code in the [lambda function](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-eks/lib/cluster-resource/index.py), if I remove [kubectl layer in eks.ClusterResource](https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-eks/lib/cluster-resource.ts#L49) and related code in [lambda function](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-eks/lib/cluster-resource/index.py#L7), it still works fine.

I will submit a PR to fix this issue.

--- 

This is :bug: Bug Report

**Comment by pahud** [comment]
@eladb 

I believe we should remove the  `requests` from the `botocore.vendored`.
https://github.com/aws/aws-cdk/blob/465c8484c65acc69141acd3dad6a61e5955e7cc6/packages/%40aws-cdk/aws-eks/lib/cluster-resource/index.py#L9

Removing the vendored version of requests from Botocore
https://aws.amazon.com/tw/blogs/developer/removing-the-vendored-version-of-requests-from-botocore/

**Comment by eladb** [comment]
Related to #6279

**Comment by eladb** [comment]
Should be addressed by #7216
