### ISSUE TITLE
C# serverless example using Lambda authored in C#

### ISSUE THREAD

**Issue by pha3l** [aws/aws-cdk#5340]
## :question: General Issue

Looking through the .NET Core examples in the repo as well as the documentation site, the only example for using CDK to publish a lambda is using a lambda authored in javascript.  I've been struggling to figure out how to get it working with a C# lambda.  

I'm aware that I can first publish the lambda using something like the `package-ci` command of the AWS extensions for the dotnet CLI, and then reference the zip uploaded to S3.  But I'm hoping that there is or will soon be a way to integrate it such that it can handle compiling and packaging any C# (or any other language that requires compilation, processing, or compressing into a zip before deployment for that matter).  I could probably klooge something with msbuild and/or a shell script to get it working, but is this on the roadmap?

Thanks for the awesome tool!

### Environment

  - **CDK CLI Version:** 
  - **Module Version:** 
  - **OS:** 
  - **Language:**

**Comment by nija-at** [comment]
Hello @pha3l -

Thanks for opening this issue.

We don't currently have a clean story on how to use a C# lambda function using the CDK app. We'll get to this in time and make this experience cleaner.

In the meantime, I've created a sample project with documented steps on how to get this - https://github.com/aws-samples/aws-cdk-examples/pull/202. This is currently a pull request and until it's merged, you can see the code tree at https://github.com/aws-samples/aws-cdk-examples/tree/nija-at/c%23-lambda/csharp/capitalize-string.

Did this answer your questions sufficiently? Let us know if you have further questions.

**Comment by pha3l** [comment]
Thank you so much, this is super helpful.  I had managed to get this working using `package-ci` rather than `package` and then using the resulting s3 path as the asset location, but I much prefer being able to use the local reference to the assets.  

One thing I just wanted to make sure I'm understanding correctly.  From your example, I take it that CDK will essentially zip the contents of the directory passed to `Code.FromAsset` if it's a directory instead of a file?

**Comment by Jerry-AWS** [comment]
@pha3l That's exactly the case, directories get zipped.

**Comment by pha3l** [comment]
@Jerry-AWS Thanks, that's good to know.  Closing the issue now!
