### ISSUE TITLE
Fargate enable cloud map method unavailable

### ISSUE THREAD

**Issue by w601sxs** [aws/aws-cdk#5360]
'FargateService' object has no attribute 'enable_cloud_map'

### Reproduction Steps

I did

workerService = ecs.FargateService(self, ...,...,..,)
workerService.enable_cloud_map(..,.,)

For which I got the following error

'FargateService' object has no attribute 'enable_cloud_map'

It looks like it is available in the docs as a method https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_ecs/FargateService.html

### Error Log

'FargateService' object has no attribute 'enable_cloud_map'

### Environment

  - **CLI Version      :aws-cli/1.16.148 Python/3.6.5 Darwin/18.7.0 botocore/1.12.138
  - **Framework Version:1.18.0 (build bc924bc)
  - **OS               :Mac
  - **Language         :Python

### Other

--- 

This is :bug: Bug Report

**Comment by RomainMuller** [comment]
I was unable to reproduce this issue with CDK `1.19.0`. The code I used is the following:

```python
from aws_cdk import (
    core,
    aws_ecs,
)

class ReproductionStack(core.Stack):

    def __init__(self, scope: core.Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        cluster = aws_ecs.Cluster(self, 'Cluster',
            default_cloud_map_namespace=aws_ecs.CloudMapNamespaceOptions(name='CloudMapNameSpace'))

        task_definition = aws_ecs.FargateTaskDefinition(self, 'TaskDefinition',
            memory_limit_mib=512,
            cpu=256)

        task_definition.add_container('Essential', image=aws_ecs.ContainerImage.from_registry('jsii/superchain'))

        service = aws_ecs.FargateService(self, 'FargateService',
            cluster=cluster,
            task_definition=task_definition,
            desired_count=5)

        service.enable_cloud_map()
```
