### ISSUE TITLE
API Reference: is the assets module entry useful? 

### ISSUE THREAD

**Issue by ccfife** [aws/aws-cdk#5374]
---

This is a 📕 documentation issue

The [Assets](https://docs.aws.amazon.com/cdk/api/latest/docs/assets-readme.html)  module seems too low level and shouldn't be in the API reference.

**Comment by rix0rrr** [comment]
Right now we are committed to documenting everything. Not sure this classifies as a bug.

**Comment by rix0rrr** [comment]
In fact, going to close this. Chris, please follow up via other channels if you want to discuss more.
