### ISSUE TITLE
Opinionated Jest Assertions

### ISSUE THREAD

**Issue by Red-Folder** [aws/aws-cdk#5387]
I am suggesting a collection of opinionated Jest Assertions to help avoid common mistakes.

For example;

```
expect(stack).toHaveNoPublicS3Buckets();
expect(stack).toHaveNoUnencryptedS3Buckets();
```

### Use Case

To assist builders in following (opinionated) good practice.

AWS is huge and complex.  Its understandable that builders make common mistakes (public accessible S3 buckets for example).

By providing a collection of assertions, we can assist builders in avoiding some of those mistakes (in a similar manner to linter rules).

### Proposed Solution

Either additional methods to the jest assertions with the aws-cdk project or a separate project.

The former seems a better idea of adoption.

Example code for the above assertion;

```
expect.extend({
    toHaveNoPublicS3Buckets(actual: cxapi.CloudFormationStackArtifact | Stack) {
        const assertion = new HaveResourceAssertion('AWS::S3::Bucket', (resourceProps: any, inspection: InspectionFailure): boolean => {
            const expectedProps = {
                "PublicAccessBlockConfiguration": {
                    "BlockPublicAcls": true,
                    "BlockPublicPolicy": true,
                    "IgnorePublicAcls": true,
                    "RestrictPublicBuckets": true
                }
            };
            const errors: string[] = [];
            const allowValueExtension = false;
            if (isSuperObject(resourceProps, expectedProps, errors, allowValueExtension)) {
                return true;
            }

            inspection.failureReason = `${resourceProps.BucketName} allows public access`;

            return false;
        });

        return assertHaveResource(assertion, actual);
    }
});
```

### Other

The collection could be used by builders as either individual assertions (as per the above) or a full collection:

```
expect(stack).toFollowGoodPractice();
```

This would rule the stack through all opinionated assertions.  This somewhat breaks good unit testing principals of test one thing only - but would be very easy for adoption.

---

This is a :rocket: Feature Request

**Comment by eladb** [comment]
Interesting idea. Perhaps it makes more sense to implement these assertions through [aspects](https://docs.aws.amazon.com/cdk/latest/guide/aspects.html) and simply attach them to your stacks. In a sense it is like the stack has "built-in assertions".

Closing for now.
