### ISSUE TITLE
@aws-cdk/assert add toHaveOutput

### ISSUE THREAD

**Issue by abelmokadem** [aws/aws-cdk#5389]
I want to assert that certain outputs are created as part of my stack.

### Use Case
I really need to test the outputs because they are important.

### Proposed Solution
Add a method to @aws-cdk/assert for testing outputs. `toHaveOutput`

### Other

* [X] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by shivlaks** [comment]
duplicate of #1906 which has a PR in flight for it #5366
