### ISSUE TITLE
Python language support

### ISSUE THREAD

**Issue by cavanaug** [aws/aws-cdk#539]
+1 if you want to see Python language support for the CDK

@cavanaug wrote:

So I know everyone hates this question, but does anyone have any idea when python support might be added, even if its not a complete functionality set??   Weeks?  Months?  Years?

We have a team here that is very versed in python and we were going to be looking at troposphere soon, but we are curious about python support with cdk.

**Comment by eladb** [comment]
Hey @cavanaug, thanks for your question. We don't hate this question, as it gives us indication that there are users out there who are interested in such support. We are actively working on Python support (as oppose to say, Go support, which is in our roadmap, but haven't started to work on), which means it's going to come out at some point. I'd say in the coming few months, but truly can't commit on a date. As you know, software is always surprising (which is why it's fun).

**Comment by kennu** [comment]
I am also interested in Python support. TypeScript is great, but the build step is a little cumbersome. I think Python might be an optimal language for CDK in its terseness, even though the package management with virtualenvs etc. isn't that convenient. In fact, I would hope that AWS CDK defines some standard way of how to deal with Python package dependencies.

**Comment by steveparker-kcom** [comment]
Also interested

**Comment by eladb** [comment]
Follow up here: https://github.com/awslabs/jsii/pull/219

**Comment by tokenmathguy** [comment]
Is the intention that aws-cdk package.json will include jsii section at some point? Do you think this issue/feature request should be left open until the jsii section exists?

**Comment by eladb** [comment]
Reopening. This is in the works on the Jsii repository, but we’ll track that here as well so people can follow.

**Comment by eladb** [comment]
New pull request: https://github.com/awslabs/jsii/pull/319

**Comment by pkordes** [comment]
The pull request seems stalled?

**Comment by trondhindenes** [comment]
Any news around this? We'd love to start using the CDK, but are reluctant to change languages, as we're standardized on Python.

**Comment by kennu** [comment]
I, for one. am in pain with all the TypeScript compilation steps needed for projects that define lots of separate CDK constructs and stacks. It makes development very inconvenient. Hoping that Python support solves this.

**Comment by kennu** [comment]
@eladb I have not tried ts-node, I've just followed the way CDK generates projects with build scripts and obediently executed them. Do you recommend ts-node as the main way to run it? No surprising gotchas?

**Comment by eladb** [comment]
I don't think there should be an issue with ts-node. We are considering moving our templates to use it too. Would love to hear about your experience in #822

**Comment by alborworld** [comment]
+1 for python support. Thank you!

**Comment by tweaknc** [comment]
+1 python please!

**Comment by dsalavei** [comment]
+1

**Comment by chriswessells** [comment]
+1

**Comment by rnason** [comment]
+1

**Comment by jeff-shep** [comment]
+1

**Comment by Entr04y** [comment]
+1

**Comment by zzzThibaut** [comment]
+1

**Comment by mbylstra** [comment]
+1

**Comment by rongzuoliu** [comment]
+1

**Comment by laur1s** [comment]
+1

**Comment by jorgeluishdez** [comment]
+1

**Comment by ori-o** [comment]
+1

**Comment by tokenmathguy** [comment]
With the resolution of [awslabs/jsii#319](https://github.com/awslabs/jsii/pull/319), what process needs to happen to add python as a jsii target to the package.jsons?

**Comment by angusfz** [comment]
Using troposphere, it will be great for cdk supporting python

**Comment by eladb** [comment]
Python support has been released.

**Comment by laur1s** [comment]
> Python support has been released.

How can you say it's released when there are no documentation on how to actually use it?

**Comment by eladb** [comment]
You are right, we haven't officially announced it yet nor published the docs. Let's keep this open until we do. In the meantime, checkout [this blog post](https://rboyd.dev/b3a9137a-53c9-40a0-a70b-bc3752b75184) by @rhboyd

**Comment by ccfife** [comment]
Looks like we can close this one now. yea!
https://docs.aws.amazon.com/cdk/api/latest/python/index.html 
https://aws.amazon.com/blogs/developer/getting-started-with-the-aws-cloud-development-kit-and-python/
