### ISSUE TITLE
docs(ECS): fix wrong comparison, AWS Fargate vs Amazon ECS

### ISSUE THREAD

**Issue by sukjae** [aws/aws-cdk#5393]
### link to reference doc page:
https://docs.aws.amazon.com/cdk/api/latest/docs/aws-ecs-readme.html

### describe your issue:

in the middle of document, there is comparison between [AWS Fargate vs Amazon ECS.](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-ecs-readme.html#aws-fargate-vs-amazon-ecs)

but, in my opinion it should be **AWS Fargate vs Amazon EC2.**

also, following sentence right after title should be changed.

> There are two sets of constructs in this library; one to run tasks on **Amazon ECS** and one to run tasks on AWS Fargate.

to 

> There are two sets of constructs in this library; one to run tasks on **Amazon EC2** and one to run tasks on AWS Fargate.

---

This is a 📕 documentation issue

**Comment by hencrice** [comment]
Approved PR, waiting on checks. Removing "needs-triage" label
