### ISSUE TITLE
Wrong value generated by CfnAssociation.parameters, should interpret the ParameterValuesProperty list of string only for CF to accept it

### ISSUE THREAD

**Issue by chefren** [aws/aws-cdk#5400]
### The Question

aws-ssm.CfnAssociation expects a CfnAssociation.ParameterValuesProperty, but upon deployment, CF expects a list of string

### Environment

  - **CDK CLI Version:1.18.0 (build bc924bc)** 
  - **Module Version:1.18.0** 
  - **OS:all** 
  - **Language:Python** 

### Other information

First reported on [SO](https://stackoverflow.com/q/58328181/1736679)

CF error:

```bash
Value of {Parameters} must be a map where each value is a list of {String}
```

**Comment by chefren** [comment]
CDK generates what appears to match the CF doc type definition:

        "Parameters": {
          "Directory": {
            "ParameterValues": [
              "myWorkSpace"
            ]
          }
        }

The same CF [doc](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ssm-association.html) example actually shows a map of key:value, where the value is a list of strings. Which is also what is shown in the syntax initial section, and what the CF console appears to accept, according to the error.

        "Parameters": {
          "Directory": ["myWorkSpace"]
        },

**Comment by eladb** [comment]
Duplicate https://github.com/aws/aws-cdk/issues/4057
