### ISSUE TITLE
aws-codebuild ComputeType missing new options

### ISSUE THREAD

**Issue by DmitryNefedov** [aws/aws-cdk#5401]
## :question: General Issue

aws-codebuild is missing new options in ComputeType.
Only half of the available build environment compute types are present.
https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-compute-types.html

### Environment

  - **CDK CLI Version:** 1.18.0
  - **Module Version:** "@aws-cdk/aws-codebuild": "1.18.0"
  - **OS:**  Windows 10 
  - **Language:**  TypeScript

### Other information
https://github.com/aws/aws-cdk/blob/v1.18.0/packages/@aws-cdk/aws-codebuild/lib/project.ts#L998
```
project.d.ts
/**
 * Build machine compute type.
 */
export declare enum ComputeType {
    SMALL = "BUILD_GENERAL1_SMALL",
    MEDIUM = "BUILD_GENERAL1_MEDIUM",
    LARGE = "BUILD_GENERAL1_LARGE"
}
```

**Comment by skinny85** [comment]
@DmitryNefedov any chance you'd consider opening us a Pull Request with the changes? It should be as simple as adding the new values into [this enum](https://github.com/aws/aws-cdk/blob/e4309abf07f3b0cc9f2f2f89789f14669f3d3581/packages/%40aws-cdk/aws-codebuild/lib/project.ts#L998-L998) 🙂.

Thanks,
Adam

**Comment by DmitryNefedov** [comment]
@skinny85 sure thing. 
[Here you go](https://github.com/aws/aws-cdk/pull/5429)
