### ISSUE TITLE
Python: implementing IStepFunctionsTask causes jsii to throw "Don't know how to convert object to JSON"

### ISSUE THREAD

**Issue by chamcca** [aws/aws-cdk#5410]
When implementing the `aws_stepfunctions.IStepFunctionsTask` interface in python, jsii will raise a "Don't know how to convert object to JSON" error.

### Reproduction Steps
```python
@jsii.implements(sfn.IStepFunctionsTask)
class CustomStepFunctionsTask(sfn.IStepFunctionsTask):
    @jsii.member(jsii_name="bind")
    def bind(self, task: sfn.Task) -> sfn.StepFunctionsTaskConfig:
        return sfn.StepFunctionsTaskConfig(
            resource_arn='',
            policy_statements=[],
            parameters={}
        )
```

### Error Log

`TypeError: Don't know how to convert object to JSON: CustomStepFunctionsTask object at 0x11392a890>`

### Environment

  - **CLI Version      :** 1.18.0
  - **Framework Version:** 1.18.0
  - **OS               :** OSX
  - **Language         :** Python

### Other

--- 

This is :bug: Bug Report

**Comment by RomainMuller** [comment]
I believe you are incorrectly implementing the interface. This is unfortunately somewhat un-pythonic at the time (aws/jsii#576).

A correct way that I was able to try looks like the following:

```
from aws_cdk import (
    core,
    aws_stepfunctions as sfn,
)
import jsii

class TypeScriptStack(core.Stack):

    def __init__(self, scope: core.Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        step = CustomStepFunctionTask()

        sfn.StateMachine(self, 'StateMachine', definition=sfn.Task(self, 'ExecuteStep', task=step))

@jsii.implements(sfn.IStepFunctionsTask)
class CustomStepFunctionTask:
    def bind(self, task: sfn.Task) -> sfn.StepFunctionsTaskConfig:
        return sfn.StepFunctionsTaskConfig(
            resource_arn='my::phony::arn',
            policy_statements=[],
            parameters={}
        )
```
