### ISSUE TITLE
Convert from Construct to CfnResource and/or vice versa?

### ISSUE THREAD

**Issue by ccloutier** [aws/aws-cdk#5419]
I am wondering it it is possible (and I am missing the solution) or if not if it is a planned feature to convert any of the following classes:
1. Construct -> CfnResource
2. Construct <- CfnResource
3. Construct <=> CfnResource

### Use Case

For example, I created a lambda object via the `Function` class and an asset via the `AssetCode` class:

        self.example_lambda = _lambda.Function(
            self, "example-lambda-name",
            runtime=_lambda.Runtime.PYTHON_3_7,
            handler='example-lambda.handler',
            code=_lambda.Code.from_asset('lambda'),
            function_name="example-lambda-function-name"
        )

        self.example_asset = _lambda.AssetCode(
            'lambda/file-to-attach.txt'
        )

I am trying to attach this asset to the lambda function, and the only way I've found to do this is through `lambda.AssetCode.bind_to_resource`, which requires a `CfnResource` object as a parameter. Trying to pass it the lambda function gives me:

`jsii.errors.JSIIError: Object of type @aws-cdk/aws-lambda.Function is not convertible to @aws-cdk/core.CfnResource`

This is expected, but I feel like this should be possible. I am sure there are multiple other scenarios I haven't stumbled upon where this could come in handy.

---

This is a :rocket: Feature Request

**Comment by eladb** [comment]
You should be able to assign `self.example_asset` to the `code` keyword argument of your `Function`.
