### ISSUE TITLE
Lambda: unable to access event source mapping ID

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#5430]
When adding a Lambda event source which uses an event source mapping, such as an SQS queue or a DynamoDB table, it should be possible to access the event source ID (the `Ref` of the `AWS::Lambda::EventSourceMapping` resource).

### Use Case

For example, we are trying to write a lambda function that enables/disables the event source using the [UpdateEventSourceMapping](https://docs.aws.amazon.com/lambda/latest/dg/API_UpdateEventSourceMapping.html) API, we need access to the UUID.

### Proposed Solution

Expose the `eventSourceMappingId` as a property of `SqsEventSource` and friends, and of the `EventSourceMapping` resource.

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by eliasdraexler** [comment]
Hello, I would like to contribute to the cdk.
Does someone already work on this, or is this still open for contribution?
If so, I would love to submit a PR.

**Comment by nija-at** [comment]
@eliasdraexler - No one has claimed it as yet; all yours.
