### ISSUE TITLE
Tokenized URL Parser

### ISSUE THREAD

**Issue by evanderkoogh** [aws/aws-cdk#5433]
Hi,

There are a couple places where we a particular Resource returns a URL, but another URL requires a domain name.
The two scenarios I know about are both AppSync & API Gateway and Cloudfront. But as it quite likely that the URL is tokenized, regular URL parsers won't work.

So I wrote a 2 line function that parses out the domain name with `Fn.select` and `Fn.split` that I figured more people would benefit from, but I have no idea where to put it.

Is `Fn` itself a good place? It says it is for Cfn implicit functions, which this wouldn't really be.

``` javascript
const domainNameFromURL = (url: string): string => {
  const noHttps = Fn.select(1, Fn.split('//', url))
  return Fn.select(0, Fn.split('/', noHttps))
}
```

More than happy to make the PR if someone can point me to where they'd want it.

**Comment by NGL321** [comment]
@eladb Any suggestions on where to contribute this?

**Comment by eladb** [comment]
I like the idea of adding this to the `Fn.xxx` utility class. Maybe `Fn.parseDomainName(url)` or something like this.
