### ISSUE TITLE
ApplicationLoadBalancedFargateService stack becomes undeployable if a change requires re-creation of the ALB

### ISSUE THREAD

**Issue by schoeneu** [aws/aws-cdk#5440]
The Cloudformation bug described here: https://forums.aws.amazon.com/thread.jspa?threadID=254544 also hits CDK: The new LB is spun up, and the existing target group wants to be associated to the new ALB but can only be associated to one. Since the logical ID of the target group is kept constant, this leads to the error described in the forums thread.

### Reproduction Steps

Spin up the ApplicationLoadBalancedFargateService example from the docs.
cdk deploy.
Change the `publicLoadBalancer` attribute.
cdk deploy.

### Error Log

`Target group 'arn:aws:elasticloadbalancing:...' cannot be associated with more than one load balancer`

### Environment

  - **CLI Version      :** 1.18.0
  - **Framework Version:** 1.18.0
  - **OS               :** Linux
  - **Language         :** Typescript

### Other

--- 

This is :bug: Bug Report

**Comment by hencrice** [comment]
Hey @schoeneu 

We launched multiple target group support. Will it help in your use cases? https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/aws-ecs-patterns#application-load-balanced-services

**Comment by schoeneu** [comment]
Hey @hencrice , I don't think this solves the bug described here:
* The new feature allows attaching multiple target groups to one ALB.
* The bug here arises because a change to the LB configuration spins up a new LB that tries to use the existing target group *before* shutting down the old LB. In this situation, there are multiple  ALBs attached to one target group, which is not allowed.

I think the solution to this  bug would have to make sure that all changes that create a new ALB also create a new target group.
