### ISSUE TITLE
IoT Lambda Rule Action does not create lambda trigger

### ISSUE THREAD

**Issue by haandol** [aws/aws-cdk#5447]
Create IoT Lambda Rule Action using CDK does not create trigger for Lambda.
You can see the rule action on the console of `IoT Core - ACT - Rule` menu and the MQTT message comes in well. But the event does not trigger lambda unless you clear and select lambda function on the console manually.

### Reproduction Steps
Create Rule Action to trigger lambda.

```javascript
    new iot.CfnTopicRule(this, 'EdgeStartTrackerRule', {
      ruleName: 'EdgeStartTracker',
      topicRulePayload: {
        awsIotSqlVersion: '2016-03-23',
        sql: "SELECT * FROM 'edge/start' WHERE NOT type = 'entrance'",
        ruleDisabled: false,
        actions: [
          { lambda: { functionArn: edgeStartTrackerFn.functionArn } }
        ],
        errorAction: {
          republish: {
            roleArn: ruleErrorActionRole.roleArn,
            topic: 'lambda/error'
          },
        },
      }
    });
```

### Environment

  - **CLI Version      :** 1.18.0
  - **Framework Version:**
  - **OS               :** osx
  - **Language         :** typescript

### Other

--- 

This is :bug: Bug Report

**Comment by SomayaB** [comment]
Seems to be a duplicate of #5420

**Comment by haandol** [comment]
I close this is because it is duplicated #5420. Thanks.
