### ISSUE TITLE
Unknown Log Opt, splunk-sourceType

### ISSUE THREAD

**Issue by Stericson** [aws/aws-cdk#5456]
The wrong log option is used for the Splunk log driver when configuring sourcetype. The log option created by the java cdk is "splunk-sourceType" and it should be "splunk-sourcetype", note the lower case "t" in "type".

### Reproduction Steps

Configure a splunk log driver for an ECS Task definition using Java CDK 1.18.0

### Error Log

Error response from daemon: unknown log opt 'splunk-sourceType' for splunk log driver

### Environment

  - **CLI Version      : 1.18.0**
  - **Framework Version:**
  - **OS               : Mac**
  - **Language         : Java**

### Other

Change the log option to "splunk-sourcetype"

--- 

This is :bug: Bug Report

**Comment by pkandasamy91** [comment]
@Stericson, sorry for the delay. Would you be interested in contributing the fix for this issue? I'd be more than happy to review this fix.

**Comment by Stericson** [comment]
@pkandasamy91 Sure, I'll take a look and will follow back up.

**Comment by pkandasamy91** [comment]
Awesome! Thanks a lot @Stericson for picking this up!

**Comment by Stericson** [comment]
@pkandasamy91 Sorry if this is documented somewhere, but I should have permissions to push my branch to the repository correct?
