### ISSUE TITLE
SecurityGroup.addEgressRule doesn't add rules

### ISSUE THREAD

**Issue by flemjame-at-amazon** [aws/aws-cdk#5458]
When using addEgressRule, no matter what rules I seem to put in I only ever get the default "All outbound traffic" rule:

      "Type": "AWS::EC2::SecurityGroup",
      "Properties": {
        "GroupDescription": "NetworkingDemoStackBeta/Private SG",
        "SecurityGroupEgress": [
          {
            "CidrIp": "0.0.0.0/0",
            "Description": "Allow all outbound traffic by default",
            "IpProtocol": "-1"
          }
        ],

### Reproduction Steps

```
        Vpc test = new Vpc(this, "Test SG", VpcProps.builder()
                .maxAzs(5)
                .build());
        ISecurityGroup sg = new SecurityGroup(this, "SG", SecurityGroupProps.builder()
                        .vpc(test)
                        .build());
        sg.addEgressRule(Peer.ipv4(test.getVpcCidrBlock()), Port.tcp(80));
```

### Environment

  - **CLI Version      :**1.18
  - **Framework Version:**Java
  - **OS               :**MacOS
  - **Language         :**Java

### Other

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
Please disable `allowAllOutbound`?

**Comment by flemjame-at-amazon** [comment]
That worked, thanks!
