### ISSUE TITLE
aws-ecs-patterns: Substituting IApplicationLoadBalancer for ApplicationLoadBalancer results in JSII breaking change alert

### ISSUE THREAD

**Issue by bvtujo** [aws/aws-cdk#5465]
PR #5461 is an attempt to allow users to provide an imported load balancer to aws-ecs-patterns. This requires that I change some properties defined in aws-ecs-patterns from ApplicationLoadBalancer or NetworkLoadBalancer types to IApplicationLoadBalancer or INetworkLoadbalancer types. 

Expected: 
All unit tests and integration tests pass

Actual:
JSII causes CI build to fail with output "IApplicationLoadBalancer does not extend ApplicationLoadBalancer." This seems to be in error: objects of type ApplicationLoadBalancer *implement* IApplicationLoadBalancer and this should not result in any breaking UX changes. 

### Reproduction Steps

This issue appears in the build logs of #5461 

### Error Log

```
API elements with incompatible changes:
err  - PROP @aws-cdk/aws-ecs-patterns.ApplicationLoadBalancedEc2Service.loadBalancer: type @aws-cdk/aws-elasticloadbalancingv2.IApplicationLoadBalancer (formerly @aws-cdk/aws-elasticloadbalancingv2.ApplicationLoadBalancer): @aws-cdk/aws-elasticloadbalancingv2.IApplicationLoadBalancer does not extend @aws-cdk/aws-elasticloadbalancingv2.ApplicationLoadBalancer [changed-type:@aws-cdk/aws-ecs-patterns.ApplicationLoadBalancedEc2Service.loadBalancer]
err  - PROP @aws-cdk/aws-ecs-patterns.ApplicationLoadBalancedFargateService.loadBalancer: type @aws-cdk/aws-elasticloadbalancingv2.IApplicationLoadBalancer (formerly @aws-cdk/aws-elasticloadbalancingv2.ApplicationLoadBalancer): @aws-cdk/aws-elasticloadbalancingv2.IApplicationLoadBalancer does not extend @aws-cdk/aws-elasticloadbalancingv2.ApplicationLoadBalancer [changed-type:@aws-cdk/aws-ecs-patterns.ApplicationLoadBalancedFargateService.loadBalancer]
err  - PROP @aws-cdk/aws-ecs-patterns.ApplicationLoadBalancedServiceBase.loadBalancer: type @aws-cdk/aws-elasticloadbalancingv2.IApplicationLoadBalancer (formerly @aws-cdk/aws-elasticloadbalancingv2.ApplicationLoadBalancer): @aws-cdk/aws-elasticloadbalancingv2.IApplicationLoadBalancer does not extend @aws-cdk/aws-elasticloadbalancingv2.ApplicationLoadBalancer [changed-type:@aws-cdk/aws-ecs-patterns.ApplicationLoadBalancedServiceBase.loadBalancer]
```

[Build logs](https://dfq49x5zyi.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=c68ac8cd-2663-4421-ac83-2e370950caa7%2Fbuild.log) can be searched to locate the above text. 

### Environment
CI Build Environment as configured for the build in #5461 

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
This is not a bug.

Let's look at a simplified class diagram of `IApplicationLoadBalancer` and `ApplicationLoadBalancer`:

```
┌ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ┐
     IApplicationLoadBalancer      
├ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ┤
                                   
│ public loadBalancerArn: string  │
                                   
└ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ┘
                 △                 
                 │                 
                 │                 
                 │                 
┌─────────────────────────────────┐
│     ApplicationLoadBalancer     │
├─────────────────────────────────┤
│                                 │
│  public logAccessLogs(bucket)   │
│                                 │
└─────────────────────────────────┘
```

In the ORIGINAL VERSION, someone could write this:

```ts
class LoadBalancedApplication {
  public loadBalancer: ApplicationLoadBalancer;
}

const app = new LoadBalancedApplication();
app.loadBalancer.logAccessLogs(bucket); 
```

Now let's say you change to the type of the property  to`IApplicationLoadBalancer`:

```ts
class LoadBalancedApplication {
  public loadBalancer: IApplicationLoadBalancer;
}

const app = new LoadBalancedApplication();
app.loadBalancer.logAccessLogs(bucket); 
//                  ^^^^^--- error no such method 'logAccessLogs'
```

It is perfectly fine to substitute `IApplicationLoadBalancer` for INPUT properties (values that are supplied by the consumer and used by the construct), but you can't do this for OUTPUT properties (properties that are set by the construct and read by consumers), because type information will be lost.

Fortunately, `loadBalancer?` is already optional, so you can avoid setting the property it if the passed-in construct is not a real `ApplicationLoadBalancer` class.

**Comment by bvtujo** [comment]
The actual issue here was caused by erroneously replacing the output ApplicationLoadBalancer with IApplicationLoadBalancer, and forgetting to cast the input IALB to ALB in the ApplicationLoadBalancedServiceBase constructor
