### ISSUE TITLE
aws-ecs: support capacity provider

### ISSUE THREAD

**Issue by pahud** [aws/aws-cdk#5471]
https://aws.amazon.com/tw/about-aws/whats-new/2019/12/amazon-ecs-capacity-providers-now-available/

### Other

dependency https://github.com/aws/containers-roadmap/issues/631

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by ali-habibzadeh** [comment]
What is the likelihood of this being added to cfn?

**Comment by mb-dev** [comment]
Capacity Providers were just added to Cfn: https://github.com/aws/aws-cdk/commit/4ce27f4195c70bd9e365ec0e0df5c0ede863bc8a#diff-4a4e15a081904ee16b4d84e2f5cf5aee

**Comment by mb-dev** [comment]
FYI: @SoManyHs

**Comment by instigardo** [comment]
```
 const ondemandCapacity = cluster.addCapacity("OnDemandCapacity",{
          instanceType: new InstanceType(instanceType),
          minCapacity: 1,
          maxCapacity: 2,
          vpcSubnets: {
            subnets: vpc.privateSubnets
          }
        })
        const ondemandCapacityProvider = new CfnCapacityProvider(this, "OnDemandCapacityProvider", {
          name: "ondemandCapacityProvider",
          autoScalingGroupProvider: {
            autoScalingGroupArn: ### ondemandCapacity.autoScalingGroupArn,
            managedScaling: {
              maximumScalingStepSize: 10,
              minimumScalingStepSize: 1,
              status: "ENABLED",
              targetCapacity: 85
            }
          }
        })
```

This keeps on giving error 
`Invalid request provided: CreateCapacityProvider error: The specified Auto Scaling group ARN is invalid. Specify a valid ARN and try again.`

**Comment by mb-dev** [comment]
See here about some issues with the current implementation: 
https://github.com/aws/containers-roadmap/issues/631

These are items that still planned to be implemented:
```
Ability to reference the ASG name in the AWS::ECS::CapacityProvider resource
Ability to specify a custom capacity provider strategy in the AWS::ECS::Service resource
Ability to enable scale-in protection in the AWS::AutoScaling::AutoScalingGroup resource
```

**Comment by gandroz** [comment]
> ```
>  const ondemandCapacity = cluster.addCapacity("OnDemandCapacity",{
>           instanceType: new InstanceType(instanceType),
>           minCapacity: 1,
>           maxCapacity: 2,
>           vpcSubnets: {
>             subnets: vpc.privateSubnets
>           }
>         })
>         const ondemandCapacityProvider = new CfnCapacityProvider(this, "OnDemandCapacityProvider", {
>           name: "ondemandCapacityProvider",
>           autoScalingGroupProvider: {
>             autoScalingGroupArn: ondemandCapacity.autoScalingGroupArn,
>             managedScaling: {
>               maximumScalingStepSize: 10,
>               minimumScalingStepSize: 1,
>               status: "ENABLED",
>               targetCapacity: 85
>             }
>           }
>         })
> ```
> 
> This keeps on giving error
> `Invalid request provided: CreateCapacityProvider error: The specified Auto Scaling group ARN is invalid. Specify a valid ARN and try again.`

got the same issue in v1.53 :(

**Comment by mb-dev** [comment]
@gandroz did you try putting asg name in the `autoScalingGroupArn` field? they added this option recently.

**Comment by pahud** [comment]
Hi folks,

I am working on the PR today and seems working fine in my integ test.

See: https://twitter.com/pahudnet/status/1285440342045515777

Will create a PR draft shortly.

**Comment by iamhopaul123** [comment]
We'll hold this issue because there are some feature gaps for CFN Capacity Provider to be narrowed. For example, the cyclic dependency that is already discussed [here](https://github.com/aws/containers-roadmap/issues/631#issuecomment-663786537). Even if we try to break the cyclic dependency by using the hard code cluster name, we'll still have problems when deleting resources. Hence, we decided to hold this issue and wait for CFN update on Capacity Provider before we support it in CDK.

**Comment by andreialecu** [comment]
@iamhopaul123 I believe this may have been unblocked recently?

https://aws.amazon.com/about-aws/whats-new/2020/10/aws-fargate-spot-for-amazon-ecs-now-supported-in-aws-cloudformation/

I'm not sure if it only applies to Fargate and whether it can work with EC2 as well.

**Comment by iamhopaul123** [comment]
Hi @andreialecu thank you so much for bringing this great news to us! We'll take a look at it to see if it could fit in fixing this issue. Thanks!

**Comment by iamhopaul123** [comment]
Hello @andreialecu, looks like number 4 and 5 of https://github.com/aws/containers-roadmap/issues/631#issuecomment-702580141 are still waiting to be fixed. Unfortunately though CFN support could simplify the CDK support for quite a lot, without fixing the circular dependency problem there is not much we could do. We'll keep waiting until there are more updates on this.

**Comment by pv93** [comment]
Hello everyone. Is there any news on this issue?

**Comment by muraleee** [comment]
Is this coming soon?

**Comment by iamhopaul123** [comment]
Hello, we don't have any update for now. We'll update this issue we there's any news.

**Comment by rsmogura** [comment]
We are interest in this too, mainly due possibilities to use launch templates.

I think I’ve got idea how to solve it and I did preliminary tests.

We could create custom cloud formation resource “CapacityProviderAttachment”, which will have two inputs cluster & capacity providers - this is simple lambda. Custom resource could be part of “bootstrap” or some kind of inner stack (I prefer later as CF templates are commonly used).

The resource would call put-capacity-providers on creation and remove from cluster on deletion.

I would have to validate deletion only, to have final results.

**Comment by otterley** [comment]
Supporting EC2 Capacity Providers may now be possible, now that the [AWS::ECS::ClusterCapacityProviderAssociations resource](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-clustercapacityproviderassociations.html) is available.

**Comment by rsmogura** [comment]
I missed this one. So this ticket and bunch of other leading go to launch templates can be shortly solved.``
