### ISSUE TITLE
BastionHostLinux AMI update

### ISSUE THREAD

**Issue by pasieronen** [aws/aws-cdk#5473]
I'm not totally sure if this is a bug report or feature request.

### Use Case

Since BastionHostLinux uses the latest Amazon Linux AMI (read from SSM parameter `/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2`) I was sort of 
expecting that something happens when that AMI/SSM parameter is updated. It looks like nothing happens currently: there's nothing in `cdk diff`, and nothing in CloudFormation drift detection.

I've previously used Terraform to set up bastion hosts, and if you use the "latest Amazon Linux AMI" lookup in Terraform, you do get a diff in `terraform plan` when a new AMI is published (and if you deploy the diff, you get a new instance with the new AMI).

(Of course, you wouldn't want to store any persistent data on your bastion if it regularly gets replaced.)

### Proposed Solution

I'm not sure what would be the best way to handle this kind of thing in CDK or CloudFormation, but I'd like to be able to say declaratively that "desired state is a bastion host with latest Amazon Linux AMI", and  somehow get indication (in `cdk diff` or CloudFormation drift detection, or otherwise) when this is no longer the case.

Since some folks may indeed store persistent data on the bastion, perhaps this could be behind a `replaceInstanceWhenAmiIsUpdated` flag or something...

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
You are saying the host DOES get replaced, but you are not getting advance warning of that, correct?

Related to https://github.com/aws/aws-cdk/issues/5675

**Comment by pasieronen** [comment]
@rix0rrr No, it looks like in this case the host is NOT replaced (but I'd like to get it replaced, so I don't have to manually install security updates via `yum update`...)

**Comment by hoegertn** [comment]
You still need to run patch management, as new AMIs are not released that often. So you always need some form of update mech.

**Comment by ragona** [comment]
This also adds unfortunate friction to using AWS Instance Connect since `mssh` isn't present on the host, but I'm gathering that perhaps AWS SSM is the better supported path these days?
