### ISSUE TITLE
Step Function StartExecution behaves differently to InvokeFunction

### ISSUE THREAD

**Issue by bpearson** [aws/aws-cdk#5474]
### The Question
StartExecution seems to be returning different output than InvokeFunction. Ideally, I want to call functions and child step functions inside one big parent step function. The way below feels the cleanest but there is a slight difference between the use of InvokeFunction and StartExecution.

### Environment

  - **CDK CLI Version:** 1.19.0 (build 5597bbe)
  - **Module Version:** @aws-cdk/aws-stepfunctions-tasks: 1.19.0
  - **OS:** Ubuntu
  - **Language:** Typescript

### Other information
**Reproduction**:
the main stack file looks like...
```typescript
import cdk         = require('@aws-cdk/core');
import lambda      = require('@aws-cdk/aws-lambda');
import sfn         = require('@aws-cdk/aws-stepfunctions');
import sfn_tasks   = require('@aws-cdk/aws-stepfunctions-tasks');

export class CdkStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    // Functions.
    const functionStart = new lambda.Function(this, 'stage-start', {
        code: new lambda.AssetCode('lib/stages/start'),
        handler: 'main.handler',
        runtime: lambda.Runtime.NODEJS_10_X,
        environment: {
        }
    });
    const functionMiddle = new lambda.Function(this, 'stage-middle', {
        code: new lambda.AssetCode('lib/stages/middle'),
        handler: 'main.handler',
        runtime: lambda.Runtime.NODEJS_10_X,
        environment: {
        }
    });
    const functionFinish = new lambda.Function(this, 'stage-finish', {
        code: new lambda.AssetCode('lib/stages/finish'),
        handler: 'main.handler',
        runtime: lambda.Runtime.NODEJS_10_X,
        environment: {
        }
    });

    // Child State Machine.
    const childStep = {
        "middle": new sfn.Task(this, 'Test - Middle', {
            task: new sfn_tasks.InvokeFunction(functionMiddle)
        }),
    };
    const childChain = sfn.Chain.start(childStep["middle"]);
    const childSfn = new sfn.StateMachine(this, 'TestChild', { definition: childChain, timeout: cdk.Duration.minutes(2) });

    // State Machine.
    const step = {
        "start": new sfn.Task(this, 'Test - Start', {
            task: new sfn_tasks.InvokeFunction(functionStart)
        }),
        "middle": new sfn.Task(this, 'Test - Middle Chain', {
            task: new sfn_tasks.StartExecution(childSfn, {
                input: {
                    name: sfn.Data.stringAt('$.name')
                },
                integrationPattern: sfn.ServiceIntegrationPattern.SYNC
            }),
        }),
        "finish": new sfn.Task(this, 'Test - Finish', {
            task: new sfn_tasks.InvokeFunction(functionFinish),
        }),
    };
    const chain = sfn.Chain.start(step["start"]).next(step["middle"]).next(step["finish"]);
    new sfn.StateMachine(this, 'TestParent', { definition: chain, timeout: cdk.Duration.minutes(2) });
  }
}
```
Each function is coded like:
```typescript
export const handler = async (event: any = {}, context: any = {}, callback: any = null) : Promise <any> => {
    event.name = 'FUNCTIONNAME';

    return event;
};
```
And when deployed to AWS, the InvokeFunction product output like:
```json
{
  "Comment": "Insert your JSON here",
  "name": "FUNCTIONNAME"
}
```
But running StartExecution, the resulting output is:
```json
{
  "ExecutionArn": "EXECUTIONARN",
  "Input": "{\"name\":\"FUNCTIONNAME\"}",
  "Name": "6574ffe0-ddab-4f1b-8a52-a6edbdbab725",
  "Output": "{\"name\":\"NEXTFUNCTIONNAME\"}",
  "StartDate": 1576648928530,
  "StateMachineArn": "STATEMACHINEARN",
  "Status": "SUCCEEDED",
  "StopDate": 1576648928966
}
```
And even trying to adjust the output path of the Task with `$.Output` results in a string not a JSON object.

I have only been playing with Step Functions and Lambdas, so I am unaware if other functions fit either pattern, but to me, it looks like InvokeFunction handles it correctly but StartExecution does not.

Bonus round: The input looks different as well, but I have managed to find "a way" (as shown above) but if there is a way to make it behave consistently with InvokeFunction would be 0rsm!

**Comment by rix0rrr** [comment]
I see what you're saying and I agree the data format is unfortunate, but  I'm afraid this is not something the CDK has any control over. I would ask you direct your question to the StepFunctions team.

**Comment by rix0rrr** [comment]
I have talked to the StepFunctions team about this.

Currently, this is just the way it stands, but the are aware of the issue.

Currently the recommendation is to put a Lambda function in between to parse the string to an object. The CDK contains an "eval" task you might be able to use for this.

**Comment by SomayaB** [comment]
Closing this issue since it isn't actionable for the CDK. Feel free to reopen.

**Comment by samwhitford** [comment]
It looks like a recent update to Step Functions might address this issue:
https://twitter.com/DRo_604/status/1263253771099881472
https://docs.aws.amazon.com/step-functions/latest/dg/connect-stepfunctions.html

Specifically setting the sync version to 2

`startExecution.sync:2`
