### ISSUE TITLE
CfnIdentityPoolRoleAttachment is missing the role mapping type

### ISSUE THREAD

**Issue by ryanvade** [aws/aws-cdk#5480]
[CfnIdentityPoolRoleAttachment](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cognito.CfnIdentityPoolRoleAttachment.html) should support the Role Mapping Type as described by [AWS::Cognito::IdentityPoolRoleAttachment](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-identitypoolroleattachment-rolemapping.html#cfn-cognito-identitypoolroleattachment-rolemapping-type). According to the CloudFormation docs the Type field is required so it should be a supported property. 

### Use Case

I want to use the Token role mapping type and not the Rule type.

### Proposed Solution

Add a type parameter to CfnIdentityPoolRoleAttachment. 

### Other

* [X] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by SomayaB** [comment]
Hi @ryanvade, I don't quite understand what's missing. Isn't [this](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cognito.CfnIdentityPoolRoleAttachment.RoleMappingProperty.html#type) what you are looking for?

**Comment by ryanvade** [comment]
Hello @SomayaB ,

Given this example:
```
    const defaultPolicy = new CfnIdentityPoolRoleAttachment(this, 'Default', {
      identityPoolId: identityPool.ref,
      roles: {
        'unauthenticated': unauthenticated.roleArn,
        'authenticated': authenticated.roleArn
      }
    });
```

I should be able to add the role type right? Like this:
```
    const defaultPolicy = new CfnIdentityPoolRoleAttachment(this, 'Default', {
      identityPoolId: identityPool.ref,
      roles: {
        'unauthenticated': unauthenticated.roleArn,
        'authenticated': authenticated.roleArn
      },
		type: "Token"
    });
```

**Comment by SomayaB** [comment]
Hi @ryanvade, `CfnIdentityPoolRoleAttachment` doesn't have a `type` prop. But `CfnIdentityPoolRoleAttachment` has an optional `roleMappings` property, which takes a map of a string and `RoleMappingProperty` and that has a `type` prop.

Let me know if this works:
``` ts
const defaultPolicy = new CfnIdentityPoolRoleAttachment(this, 'Default', {
    identityPoolId: identityPool.ref,
    roles: {
        'unauthenticated': unauthenticated.roleArn,
        'authenticated': authenticated.roleArn
    },
    roleMappings: {
        'mapping': {
            type: "Token"
        }
    }
});

**Comment by ryanvade** [comment]
Oh I see, I read the cloud formation documentation wrong. My apologies.

**Comment by agarwri** [comment]
is this equivalent to selecting "Choose role from token" for the authenticated role selection for the identity pool on the AWS management console?

**Comment by pzttpsc** [comment]
@agarwri no it's not. You need to provide different role mapping to achieve that:
Python code:
```Python
role_mappings={
    'cognito-user-pool': cognito.CfnIdentityPoolRoleAttachment.RoleMappingProperty(
        type='Token',
        ambiguous_role_resolution='AuthenticatedRole',
        identity_provider=cdk.Fn.join(':', [self.user_pool.user_pool_provider_name, self.user_pool_client.user_pool_client_id])
    )
}
```

**Comment by serverlesspolska** [comment]
@agarwri no it's not. You need to provide different role mapping to achieve that:
Python code:
```Python
role_mappings={
    'cognito-user-pool': cognito.CfnIdentityPoolRoleAttachment.RoleMappingProperty(
        type='Token',
        ambiguous_role_resolution='AuthenticatedRole',
        identity_provider=cdk.Fn.join(':', [self.user_pool.user_pool_provider_name, self.user_pool_client.user_pool_client_id])
    )
}
```
