### ISSUE TITLE
Fact uses static variables to store fact values

### ISSUE THREAD

**Issue by VladimirA** [aws/aws-cdk#5481]
Static variables stop working if multiple instances of the same module are used in the project.

In my case I had package `A` that registers some values into Fact and package `B` that calls package `A` to register values and later uses `RegionInfo.get`. When package `B` attempts to read values that were registered by package `A`, `RegionInfo` returns `undefined`.

### Reproduction Steps

1. Create 2 packages (`A` and `B`), both of them depend on `@aws-cdk/region-info`.
1. Create class/function in `A` register some fact by following README https://github.com/aws/aws-cdk/blob/5901d6ec983df898312613fb4471ad86439e1da1/packages/%40aws-cdk/region-info/README.md#supplying-new-or-missing-information
1. Create class/function in `B` that invokes function from package `A` from previous step ^
1. In package `B` use low-level API to read values that you just registered using function from package `A` https://github.com/aws/aws-cdk/blob/5901d6ec983df898312613fb4471ad86439e1da1/packages/%40aws-cdk/region-info/README.md#low-level-api

### Error Log

No error log, it just don't work properly

### Environment

  - **CLI Version      :** 1.19.0
  - **Framework Version:**
  - **OS               :** osx
  - **Language         :** typescript

### Other

--- 

This is :bug: Bug Report

**Comment by eladb** [comment]
This is a problem. I am wondering if the correct model is to make this non-static and expose this from core.Stack, so in order to access, users will do:

```ts
Stack.of(this).regionInfo.bla
```

@RomainMuller what do you think?

**Comment by RomainMuller** [comment]
There should not be multiple instances of the library in the closure. The recommended set-up is to involve `peerDependencies` on `@aws-cdk/region-info` (and other `@aws-cdk` packages).

I'd like to know more about what specific facts you're looking to register here... (The general kind of information is enough - I don't necessarily need to see the actual values here if they're private).
