### ISSUE TITLE
[aws-appsync] support mapping template for paginated responses

### ISSUE THREAD

**Issue by Townsheriff** [aws/aws-cdk#5486]
Creating resolver where request mapping template is `MappingTemplate.dynamoDbScanTable()` and providing response mapping template `MappingTemplate.dynamoDbResultList()` is incompatible with required response mapping template structure.

### Reproduction Steps
1. Create resolver with request mapping template `MappingTemplate.dynamoDbScanTable()` and response mapping template `MappingTemplate.dynamoDbResultList()`

### Error Log
Response mapping template is not correctly mapped to graphql schema.

### Environment

  - **CLI Version      : aws-cli/2.0.0dev1 Python/3.7.4 Darwin/18.7.0 botocore/2.0.0dev1
  - **Framework Version:1.19.0
  - **OS               :MacOS
  - **Language         :Typescript

### Other

What actually is produced in response mapping template: `$util.toJson($ctx.result.items)`
What should be produced in response mapping template: 
```
{
  "items": $utils.toJson($context.result.items)
}
```

Graphql types:
```
type Encoders {
    items: [Encoder]
}
```

--- 

This is :bug: Bug Report

**Comment by hoegertn** [comment]
I will look into it. Is there a special reason you are creating a nested type and not just something like:

```
getData(): [Item]
```

This will produce the correct result. If you have a custom response structure you need to write your own response template.

**Comment by Townsheriff** [comment]
I was trying reproduce what I did in console in aws-cdk where I created example project, cdk produced output was different from console example. In both cases it used Scan request resolver.

**Comment by hoegertn** [comment]
The template for `MappingTemplate.dynamoDbResultList()` is correct. What you mean is a template for paginated responses that is also available in AppSync. It would be a feature request to add this to the predefined mapping templates.
