### ISSUE TITLE
New dynamo global table version support

### ISSUE THREAD

**Issue by hleb-albau** [aws/aws-cdk#5489]
Currently, cdk **aws-dynamodb-global.GlobalTable** creates old version of Global Table implementation (Version 2017.11.29). My proposal is to add support for new  **Version 2019.11.21** version.

### Use Case
Provisioning global tables with new enhanced version using aws cdk.

### Proposed Solution

From the client point of view: add a new property called **version** to **aws-dynamodb-global.GlobalTable**. 

From the impl side: 
- [ ] update custom resource to be able to deploy new version of global tables.
- [ ] create global table using version from a new **version** property

This is a :rocket: Feature Request

**Comment by SomayaB** [comment]
Hi @hleb-albau, thanks for submitting a feature request! Could you please fill out the template above to help us understand your request better. Thank you!

**Comment by hleb-albau** [comment]
> Hi @hleb-albau, thanks for submitting a feature request! Could you please fill out the template above to help us understand your request better. Thank you!

Done. You can delete this 2 messages to clean up issue :)

**Comment by skinny85** [comment]
There is already a PR with this functionality: https://github.com/aws/aws-cdk/pull/5821 :)
