### ISSUE TITLE
CDK creates an invalid security group

### ISSUE THREAD

**Issue by par-texx** [aws/aws-cdk#5492]
### Reproduction Steps
Sorry, I don't have access to the raw code, just the template created by CDK.  

### Environment

  - **CLI Version      :**
  - **Framework Version:**
  - **OS               :**
  - **Language         :**

### Other

--- 

This is :bug: Bug Report

**Comment by SomayaB** [comment]
Hi @par-texx, thanks for submitting a bug report. We need more information in order to understand the issue better. Can you please tell us more about the specifics of the issue. And knowing your environment info would also be helpful. Thank you!

**Comment by SomayaB** [comment]
Closing this issue since there hasn't been a response in a while. Feel free to reopen.
