### ISSUE TITLE
Add Fn::Sub to CloudWatch Dashboard DashboardBody

### ISSUE THREAD

**Issue by dastbe** [aws/aws-cdk#5496]
### Use Case

We have pre-existing cfn templates that generate cloudformation dashboards and leverage parameter interpolation for specifying metric dimensions at deploy time. While this is fixable for most other constructs using the existing fn::sub function, because the construct itself is constructing the dashboard body string there's no straightforward way to leverage the construct w/ interpolated values.

### Proposed Solution

It should be sufficient to add an "interpolation" option to [the existing cdk construct](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-cloudwatch/lib/dashboard.ts#L82) that both turns on interpolation and takes an optional map of interpolatable values like [the existing Fn::Sub option](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.Fn.html#static-subbody-variables)

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
Unlikely to be added by us, but if a community PR pops up to support it we will consider it.
