### ISSUE TITLE
scaleOnMetric does not allow to change periods/datapoints to alarm

### ISSUE THREAD

**Issue by toleabivol** [aws/aws-cdk#5505]
Hi , how to change the defaults alarms created with autoscaling module for scaleOnMetric ? It sets datapoints to 1 and period to 60s.
I tried this but it does not work (shows no changes):
```
scaling = autoscalinggroup.scale_on_metric(
            f'ScaleToNrMessInQueue-{stage}-{app_name}-{version}',
            metric=queue.metric("ApproximateNumberOfMessagesVisible"),
            scaling_steps=[
                autoscaling.ScalingInterval(upper=0, change=0),
                autoscaling.ScalingInterval(lower=0, upper=1, change=1),
                autoscaling.ScalingInterval(lower=2, upper=3, change=2),
                autoscaling.ScalingInterval(lower=3, change=3)
            ],
            adjustment_type=autoscaling.AdjustmentType.EXACT_CAPACITY
        )

scaling.lower_alarm.datapoints_to_alarm = 5
scaling.lower_alarm.evaluation_periods = 5
scaling.lower_alarm.period = core.Duration.minutes(5)
```

I see one such property hardcoded here https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-autoscaling/lib/step-scaling-policy.ts#L110

### Environment

  - **CDK CLI Version:** 1.19.0 (build 5597bbe)
  - **Module Version:** latest/master
  - **OS:** Windows 7
  - **Language:** Python

**Comment by toleabivol** [comment]
I tried with module 1.21.1 and still this is an issue. The problem is that the instance will be terminated before the job is done as it sees the ApproximateNumberOfMessagesVisible is 0 while the message is still in flight. That is why I need to increase the time or evaluation periods on that lower alarm.

**Comment by toleabivol** [comment]
@NetaNir this issue still remains unsolved. Could you please check it out ?

**Comment by NetaNir** [comment]
@toleabivol, 

Wouldn't you be able to achieve this by setting [grace](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_autoscaling/Ec2HealthCheckOptions.html#aws_cdk.aws_autoscaling.Ec2HealthCheckOptions.grace) on the [health_check](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_autoscaling/HealthCheck.html#healthcheck) property of the `autoscalinggroup` to allow warm up time? see CloudFormation [docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-group.html#cfn-as-group-healthcheckgraceperiod). 

You can add it to the `autoscalinggroup`:

```python
        asg = autoscaling.AutoScalingGroup(
        self,
        "ASG",
        vpc=vpc,
        instance_type=ec2.InstanceType.of(
        ec2.InstanceClass.BURSTABLE2, ec2.InstanceSize.MICRO,
        ),
        health_check=autoscaling.HealthCheck.ec2(grace=core.Duration.seconds(5)),
        machine_image=ec2.AmazonLinuxImage(generation=ec2.AmazonLinuxGeneration.AMAZON_LINUX_2)
        )
```

Generally, to override the `lower_alarm ` properties you need to use  [escape hatches](https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html) which will allow you to override the defined alarm properties:

```python
cfn_alarm = scaling.lower_alarm.node.default_child
cfn_alarm.evaluation_periods = 5
```

**Comment by toleabivol** [comment]
@NetaNir thanks - escape hatch worked. Will this though be added to "normal" cdk without escape hatch ? If not then you can close the issue.

**Comment by NetaNir** [comment]
I'm not sure we would want want to expose the alarm properties given the ability to configure the autoscaling group behavior. I'll label this as a feature request.
