### ISSUE TITLE
Docs out of sync for secretsmanager and possibly others

### ISSUE THREAD

**Issue by tleef** [aws/aws-cdk#5509]
**`secretsmanager.SecretRotationApplication`**
*Docs:*
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-secretsmanager.SecretRotationApplication.html
*Source:*
https://github.com/aws/aws-cdk/blob/v1.19.0/packages/@aws-cdk/aws-secretsmanager/lib/secret-rotation.ts

**`secretsmanager.Secret.attach()`**
*Docs:*
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-secretsmanager.Secret.html
*Source:*
https://github.com/aws/aws-cdk/blob/v1.19.0/packages/@aws-cdk/aws-secretsmanager/lib/secret.ts

**`codebuild.ComputeType.X2_LARGE`**
*Docs:*
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-codebuild.ComputeType.html
*Source:*
https://github.com/aws/aws-cdk/blob/v1.19.0/packages/@aws-cdk/aws-codebuild/lib/project.ts

The docs reference code that exists in master but is not part of the v1.19.0 release. I found two example so far in @aws-cdk/aws-secretsmanager.

1. class `secretsmanager.SecretRotationApplication` exists in master but not in the v1.19.0 release
2. function `secretsmanager.Secret.attach()` exists in master but not in the v1.19.0 release

In both cases, they show up in the documentation but are not available in the release.

I'm not sure if this problem is isolated to the secretsmanager package or not. It appears that the documentation was generated from master, not the release tag. If that's the case other packages may be affected as well. 

I'll update this issue if I find any more inconsistencies.

**edit**
I just confirmed that this problem is not isolated to secrets manager. @aws-cdk/aws-codebuild is also affected. ComputeType. X2_LARGE was added after the v1.19.0 release and it still appears in the docs.

---

This is a 📕 documentation issue

**Comment by tleef** [comment]
I think this got automatically labeled as a feature-request because I used the documentation issue template but its more of a bug.

**Comment by rix0rrr** [comment]
You are correct, and apologies for the inconvenience. The next release will fix this.
