### ISSUE TITLE
Typo in aws-sns-notifications README example code

### ISSUE THREAD

**Issue by reesscot** [aws/aws-cdk#5512]
The `subscriptions` variable is written as `subsscriptions` in the README example code.
https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-sns-subscriptions/README.md

```
myTopic.addSubscription(new subsscriptions.SqsSubscription(queue));
```

---

This is a 📕 documentation issue

**Comment by SomayaB** [comment]
Hi @reesscot, thanks for catching that and putting in a PR. Much appreciated! 👍
