### ISSUE TITLE
DynamoDb Global Table add grant_read/write methods

### ISSUE THREAD

**Issue by hleb-albau** [aws/aws-cdk#5516]
Many resources in aws cdk has feature like:
``` 
var resource = Resourse()
var lambda = Lambda()
resource.grantWrite(lambda)
```

Add same functionality to **aws_cdk.aws_dynamodb_global** construct.

### Use Case
Multi-regions deployments becomes more popular over time. Currently, cdk users should create polices and roles to provide access to dynamo global tables. Introducing such feature can decries number of code to connect various aws services to dynamo.

### Proposed Solution

Add `grantRead`,  `grantWrite` method to **aws_cdk.aws_dynamodb_global** construct. Specified methods creates managed policy(only once) with required permissions. For each  `IGrantable` creates  and attaches role.

* [x] :wave: I can try to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by skinny85** [comment]
That's a great suggestion @hleb-albau , however, with the recent release of new global table support, the old one might get deprecated (see https://github.com/aws/aws-cdk/pull/5821 ), so I'm not sure it's wise to invest much in it (unless you have a reason you can't use the new support, and have to stay with the old one).

Thanks,
Adam
