### ISSUE TITLE
Remove String Validation in Tag Value (core.Tag.add)

### ISSUE THREAD

**Issue by ianclark2992** [aws/aws-cdk#5521]
There currently is a string validation to ensure that the value for the tag is of a string. 

### Use Case

I use the import value function to populate some of my tags, when I synthesize the template and execute it through console, it runs fine. However, when deploying through CDK I get the validation error.

### Proposed Solution

Change / remove validation

**Comment by moofish32** [comment]
@ianclark2992 

Can you provide a reproduction? 

There are some situations which I know do work. For example, I tested this:

```ts
    const key = new kms.Key(this, 'SecretStore', {
      alias: 'alias/secret_store_key',
      enableKeyRotation: true,
    });
    key.addToResourcePolicy(new iam.PolicyStatement({
      actions: ['kms:*'],
      principals: [new iam.AccountRootPrincipal],
    }));
    const myImport = cdk.Fn.importValue('myVpcId');
    cdk.Tag.add(key, 'test', myImport.toString());
```

There can also be issues with tag permissions, which may not be default granted with your kms key policy.
