### ISSUE TITLE
Update github-codebuild-logs to version 1.3.0

### ISSUE THREAD

**Issue by jogold** [aws/aws-cdk#5522]
### The Question

Update `github-codebuild-logs` to version 1.3.0 which offers an option to delete previous comments. This avoids bloating PR comments which can make review difficult.

See my PR https://github.com/jlhood/github-codebuild-logs/pull/21

@eladb

**Comment by jogold** [comment]
@eladb Have you seen this? It will make PR review here much more comfortable...

**Comment by eladb** [comment]
Yes!

**Comment by jogold** [comment]
@skinny85 @eladb any update here? `effort/medium`?

would greatly improve PR reviews...

**Comment by eladb** [comment]
This is here if you want to take a whack at it: https://github.com/awslabs/aws-delivlib/blob/master/lib/auto-build.ts
