### ISSUE TITLE
Add GlobalAccelerator construct

### ISSUE THREAD

**Issue by hleb-albau** [aws/aws-cdk#5527]
There is GlobalAccelerator service provided by aws. It would be nice, if it can be deployable from cdk.

### Use Case

Use GlobalAccelerator in cdk stacks for multi-region services.

### Proposed Solution

There are a few implementation of CF custom resource, that support  GlobalAccelerator deploy, may be we can reuse one of them as a starting point.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by netroy** [comment]
This is currently not supported by Cloudformation. 
Progress can be tracked [here](https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/255)

**Comment by hleb-albau** [comment]
> This is currently not supported by Cloudformation.
> Progress can be tracked [here](https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/255)

Yeah, dynamo global tables too, but they implemented via custom resources. If you know internal status of CF impl for Global Accelerator, maybe you can suggest to wait a bit.... if no, we can try to impl it using https://github.com/binxio/cfn-global-accelerator-provider or something like that.

**Comment by netroy** [comment]
Global tables is already implemented in CDK as a custom resource [here](https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/aws-dynamodb-global).
Maybe you can create something similar for GlobalAccelerator

**Comment by hleb-albau** [comment]
> Global tables is already implemented in CDK as a custom resource [here](https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/aws-dynamodb-global).
> Maybe you can create something similar for GlobalAccelerator

yeah, that's a point. let's wait some aws contact, maybe they will shine on CF Global Accelerator impl date.

**Comment by ccfife** [comment]
Creating a CDK Construct Library for GlobalAcclerator via a custom resource is not prioritized on the CDK [roadmap](https://github.com/orgs/aws/projects/7) at this time. Please [+1 the issue](https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/255) on the CloudFormation roadmap so that it's implemented as a proper resource type, and then automatically added to the AWS Construct Library when the CDK build processes the CFN resource spec that includes this resource.

**Comment by RomainMuller** [comment]
According to [this news](https://aws.amazon.com/fr/about-aws/whats-new/2020/05/aws-global-accelerator-supports-aws-cloudformation/), GlobalAccelerator is now available in CloudFormation. It has however not yet surfaced in the CloudFormation Resource Specification (only a matter of time!).

Once the resource is advertised in the specification, CDK will pick this up automatically and include it in the next release or so.

**Comment by hleb-albau** [comment]
Good news everyone!

**Comment by pahud** [comment]
I have a working sample here
https://twitter.com/pahudnet/status/1262939019886817281

Will be happy to create L2 for it when L1 has been checked in.

**Comment by pahud** [comment]
I'm working on it now https://github.com/aws/aws-cdk/pull/8221
