### ISSUE TITLE
How do you rename CDK Main App class in Java

### ISSUE THREAD

**Issue by andybirenzi** [aws/aws-cdk#5554]
I used CDK Init to create my application in Java, Once the application was created, I tried to rename the class and the package that was created, then ran mvn clean compile, it compiled successfully but when I run cdk synth or deploy, I get an error referencing to the old class name.

Am I missing something? How would you rename the main application?

---

This is a 📕 documentation issue

**Comment by michaelbrewer** [comment]
@andybirenzi - You will need to update the "mainClass" in the pom.xml to reflect your changes.

**Comment by andybirenzi** [comment]
Thank you! It worked fine
