### ISSUE TITLE
Add missing URL for review 'externalEntityLink' to manual-approval-action

### ISSUE THREAD

**Issue by michaelbrewer** [aws/aws-cdk#5557]
As part of a manual action in CodePipeline you can specify the URL for review.

https://docs.aws.amazon.com/codepipeline/latest/userguide/approvals-action-add.html

### Use Case

When creating a manual approval action you would want to share the test URL for QA the team to review.

### Proposed Solution

Adding 'externalEntityLink' to 'ManualApprovalActionProps' and 'ManualApprovalAction' will fix this issue.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by skinny85** [comment]
This was done in #5558.
