### ISSUE TITLE
S3DeployAction Cross Region Support

### ISSUE THREAD

**Issue by ekinrf** [aws/aws-cdk#5562]
Able to deploy to an S3 bucket in a different region other than the pipeline region.

### Use Case

We use different regions for different deployment stages. 

---

This is a :rocket: Feature Request

**Comment by skinny85** [comment]
Hi @ekinrf ,

thanks for opening the issue. This functionality should already work - if you pass an `IBucket` to the `S3DeployAction` that belongs to a `Stack` in a different region than your CodePipeline, the construct should do the wiring that's required for the cross-region functionality. Is that not the case?

Thanks,
Adam

**Comment by stephendwu** [comment]
@skinny85 I'm currently on ***1.19.0 (build 5597bbe)***, and this is what I see from my deploy pipeline for the `S3DeployAction` (us-west-2 to us-east-1):

>The deployment S3 bucket you chose (bucketname) is in an AWS Region different from the action Region. You must use the same Region for your action and the deploy bucket.

Here is a snippet of how I'm setting up the deploy:
```
      const siteBucket = Bucket.fromBucketAttributes(
        this,
        'staticSiteBucket',
        {
          bucketName: bucketName,
          bucketRegionalDomainName: `${bucketName}.s3.us-east-1.amazonaws.com`,
        }
      );

      const staticSiteDeployProdAction = new S3DeployAction({
        actionName: `staticSiteRepoDeploy${stage}Action`,
        role: crossAccountRole,
        bucket: siteBucket,
        input: staticSiteBuildOutput,
      });

      pipeline.addStage({
        stageName: `Deploy-${stage}`,
        actions: [staticSiteDeployProdAction],
      });
```

**Comment by ekinrf** [comment]
> Hi @ekinrf ,
> 
> thanks for opening the issue. This functionality should already work - if you pass an `IBucket` to the `S3DeployAction` that belongs to a `Stack` in a different region than your CodePipeline, the construct should do the wiring that's required for the cross-region functionality. Is that not the case?
> 
> Thanks,
> Adam

Thanks for the reply. I was referring to the [document](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-codepipeline-readme.html) where it says 

> You can also use the cross-region feature to deploy resources (currently, only CloudFormation Stacks are supported) into a different region than your Pipeline is in.

Anyway, thanks for your tip. Followed your suggestion, I now have a different stack that creates an IBucket in the App, and then passed it to the main stack for deployment. I was expecting this 'cross-region' can be created automatically for the S3DeployAction (just like the CloudFomrationXXXAction)

**Comment by ekinrf** [comment]
> @skinny85 I'm currently on _**1.19.0 (build [5597bbe](https://github.com/aws/aws-cdk/commit/5597bbe64446a07041f5469fc0897544448d4e95))**_, and this is what I see from my deploy pipeline for the `S3DeployAction` (us-west-2 to us-east-1):
> 
> > The deployment S3 bucket you chose (bucketname) is in an AWS Region different from the action Region. You must use the same Region for your action and the deploy bucket.
> 
> Here is a snippet of how I'm setting up the deploy:
> 
> ```
>       const siteBucket = Bucket.fromBucketAttributes(
>         this,
>         'staticSiteBucket',
>         {
>           bucketName: bucketName,
>           bucketRegionalDomainName: `${bucketName}.s3.us-east-1.amazonaws.com`,
>         }
>       );
> 
>       const staticSiteDeployProdAction = new S3DeployAction({
>         actionName: `staticSiteRepoDeploy${stage}Action`,
>         role: crossAccountRole,
>         bucket: siteBucket,
>         input: staticSiteBuildOutput,
>       });
> 
>       pipeline.addStage({
>         stageName: `Deploy-${stage}`,
>         actions: [staticSiteDeployProdAction],
>       });
> ```

I got the same error, and but created a different stack just for the S3DeployAction solved it. For your reference:

```
const app = new cdk.App();

const emrProdBucket : s3.IBucket = new S3Stack(app, "s3-stack", "somebucket-us-east-1",
    {env: {region: "us-east-1", account: awsAccount}}).bucket;
new InfraStack(app, 'infra-stack', emrProdBucket,
    {env: {region: "us-west-2", account: awsAccount}});

export class ManthanS3Stack extends cdk.Stack {
    public readonly bucket: s3.IBucket;
    constructor(scope: cdk.Construct, id: string, bucketName: string, props?: cdk.StackProps) {
        super(scope, id, props);
        this.bucket = s3.Bucket.fromBucketName(this, id, bucketName)
    }
}

export class ManthanInfraStack extends cdk.Stack {
 ...
 const emrDeployAction = new pipeline_actions.S3DeployAction({
            actionName: 'Prod',
            bucket: deploymentBucket,
            objectKey: 'artifects',
            extract: true,
            input: emrBuildProj.buildOutput,
        });
 ...
}
```

**Comment by skinny85** [comment]
@stephendwu yes, what @ekinrf said is correct. The `region` the `IBucket` is in is determined from the `Stack` it belongs to, not from the `region` part of the `bucketRegionalDomainName`, for instance.

Hope this makes it clearer!

Thanks,
Adam

**Comment by SomayaB** [comment]
Closing this issue. Feel free to reopen.
