### ISSUE TITLE
Lambda provisioned concurrency support for application autoscaling

### ISSUE THREAD

**Issue by lazydragon** [aws/aws-cdk#5564]
Now application autoscaling has supported lambda provisioned concurrency.
Can we add CDK support for it?

### Use Case

easy lambda autoscaling setup

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by NetaNir** [comment]
Hi!

This is was added in https://github.com/aws/aws-cdk/pull/5308 and is available in cdk version >=1.19.0
Happy coding!

**Comment by lazydragon** [comment]
Hi, looking at #5308 , it only supports provisioned concurrency in lambda, but not autoscaling of provisioned concurrency, doesn't it?

**Comment by NetaNir** [comment]
@lazydragon yes you are right! 
Are you still up for picking it up?

**Comment by NetaNir** [comment]
wip in https://github.com/aws/aws-cdk/pull/6394
