### ISSUE TITLE
.gitignore file is missing from the python app project

### ISSUE THREAD

**Issue by parroty** [aws/aws-cdk#5566]
`.gitignore` file seems missing from the python app project (`cdk init --language=python`), though the template exists in `aws-cdk/lib/init-templates/app/python/.gitignore`.

I'm wondering that it is ignored from the npm package (through `npm publish`).
Other languages (ex. `typescript`) seems working fine as the file is named as `.template.gitignore` (`aws-cdk/lib/init-templates/app/typescript/.template.gitignore`).

The same naming (`.template.gitignore`) can be applied to python too?

#### cdk-init behavior
`.gitignore` is contained for `language=typescript`, but not for `language=python`.

```
$ npm install -g aws-cdk
$ cdk --version
1.19.0 (build 5597bbe)
```

```
$ mkdir sample && cd $_
$ cdk init --language=python
$ ls .* | grep "^\."
.env:
.git:
```

```
$ mkdir sample && cd $_
$ cdk init --language=typescript
$ ls .* | grep "^\."
.gitignore
.npmignore
.git:
```

#### npm package
tarball in the npm repository seems not contain the `.gitignore` file for python.

```
$ wget $(npm view aws-cdk dist.tarball)
$ tar zxvf aws-cdk-1.19.0.tgz

$ ls package/lib/init-templates/app/python/.*
zsh: no matches found: package/lib/init-templates/app/python/.*

$ ls package/lib/init-templates/app/typescript/.*
package/lib/init-templates/app/typescript/.template.gitignore
package/lib/init-templates/app/typescript/.template.npmignore
```

There's an issue report for `npm` which discuss about `.gitignore` will not be included in the npm package.

- [NPM Publish Doesn't Include .gitignore](https://github.com/npm/npm/issues/3763)

### Environment

  - CLI Version      : 1.19.0
  - Framework Version: - 
  - OS               : macOS 10.14
  - Language         : python

### Other

Rename `.gitignore` to `.template.gitignore` resolve the issue? (though template expansion may not be needed).

--- 

This is :bug: Bug Report

**Comment by shivlaks** [comment]
@parroty thanks for reporting, i'm taking a look
