### ISSUE TITLE
Hide / mask sensitive data in CI pipelines

### ISSUE THREAD

**Issue by screendriver** [aws/aws-cdk#5576]
### Use Case

I want to use the AWS CDK to deploy one of my open source projects with [GitHub Actions](https://github.com/features/actions). I have a dedicated `yarn cdk deploy` script in my `package.json` that should do the job in my CI pipeline. Unfortunately everybody can see some sensitive data like my account id, the stack ARN and the public available URL of my API gateway in the output of the pipeline:

```sh
$ /home/runner/work/project/node_modules/.bin/cdk deploy --ci --require-approval never
MyStack: deploying...
Updated: asset.bbf8577689d8006a1691c5757d47991b266685e5243ca679b08ff063f97406b0 (zip)
MyStack: creating CloudFormation changeset...
  0/12 | 12:48:00 PM | UPDATE_IN_PROGRESS   | AWS::Lambda::Function       | TestFunction (TestFunction848BF7AF) 
  1/12 | 12:48:00 PM | UPDATE_COMPLETE      | AWS::Lambda::Function       | TestFunction (TestFunction848BF7AF) 
  2/12 | 12:48:03 PM | UPDATE_COMPLETE_CLEA | AWS::CloudFormation::Stack  | MyStack 

 ✅  MyStack

Outputs:
MyStack.MyApiEndpoint28B7279C = https://123foobar.execute-api.***.amazonaws.com/prod/

Stack ARN:
arn:aws:cloudformation:***:123456789:stack/MyStack/ae8b07e0-2a46-11ee-86b6-064468627800
Done in 57.23s.
```

### Proposed Solution

It would be great to have an additional CLI argument like `--silent` or automatically enable such a functionally when you provide the already existing `--ci` flag (which I initially thought does exactly that. But obviously it doesn't?) that masks or completely hides such data.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
I don't think this constitutes a p1.

Account IDs and Stack IDs are not sensitive information. You can use `myApi.node.tryRemoveChild('Endpoint')` to remove the `CfnOutput` that exposes your API gateway URL.

**Comment by madeline-k** [comment]
Thank you for submitting this feature request! After closer examination of the issue by CDK product and development team, there are no plans to implement this in the near feature. This would be a good candidate for a separate tool. If you are still interested in discussing this with the CDK team and community, please open a [discussion](https://github.com/aws/aws-cdk/discussions).
