### ISSUE TITLE
[core] availabilityZones with account and region specified not working in nested stacks

### ISSUE THREAD

**Issue by cmckni3** [aws/aws-cdk#5594]
Availability zones are not resolved correctly for VPCs created in nested stacks. The value is not resolved and the `dummyValue` is returned. In the case of `availabilityZones`, the dummy value is `['dummy1a', 'dummy1b', 'dummy1c']`.

### Reproduction Steps

```javascript
export class MyNestedStack extends cfn.NestedStack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.NestedStackProps) {
    super(scope, id, props);

    new ec2.Vpc(this, 'VPCA');
  }
}
```

### Error Log

From CloudFormation:

```
Value (dummy1a) for parameter availabilityZone is invalid. 
```

### Environment

  - **CLI Version      : 1.19.0**
  - **Framework Version: 1.19.0**
  - **OS               : macOS**
  - **Language         : TypeScript**

### Other

--- 

This is :bug: Bug Report

**Comment by cmckni3** [comment]
I tracked the issue down to `reportMissingContext`. I noticed this method does not invoke the context providers in nested stacks. I confirmed my suspicion by replacing the method with the following code:

```javascript
reportMissingContext(report) {
  if (this.nested) {
    this.nestedStackParent.reportMissingContext(report);
  } else {
    this._missingContext.push(report);
  }
}
```

I think there's a bigger issue that code won't solve but I will leave that to the CDK team.

**Comment by cmckni3** [comment]
For now, I was able to work around the issue by placing the following code into my `NestedStack`.

```javascript
    cdk.ContextProvider.getValue(scope, {
      provider: cxapi.AVAILABILITY_ZONE_PROVIDER,
      dummyValue: ['dummy1a', 'dummy1b', 'dummy1c'],
    }).value;
```

> N.B. it is pulling the context from the parent stack using `scope`

**Comment by eladb** [comment]
@NetaNir is picking this up

**Comment by davidsteed** [comment]
I tried doing as advised above:

class MyNestedStack extends cfn.NestedStack {
    constructor(scope: Construct, id: string, props?: cfn.NestedStackProps) {
        super(scope, id, props);

        ContextProvider.getValue(scope, {
            provider: cxapi.AVAILABILITY_ZONE_PROVIDER,
            dummyValue: ['dummy1a', 'dummy1b', 'dummy1c'],
        }).value;

        new s3.Bucket(this, 'NestedBucket');
    }
}


export class ParentStack extends Stack {
    constructor(scope: Construct, id: string,  props: MultistackProps) {
        super(scope, id, props);


        new MyNestedStack(scope, 'Nested1');

    }
}
but still have the problem.  Am I doing something wrong?

**Comment by cmckni3** [comment]
@davidsteed I don’t see a vpc or any other resource that would need AZs in your stack.

**Comment by davidsteed** [comment]
There isn't one.  But I am getting the error
Nested stacks must be defined within scope of another non-nested stack
and I thought this was a work around for avoiding that.
I'm guessing not.

**Comment by davidsteed** [comment]
What I am actually trying to do is register certificates in a stack in us-east-1 and use them in another stack in another region.

**Comment by cmckni3** [comment]
I think that error is caused by `new MyNestedStack(scope, 'Nested1');`

It's usually `new MyNestedStack(this, 'Nested1');`

**Comment by eladb** [comment]
This is supposed to be fixed in the next release (soon!)

**Comment by davidsteed** [comment]
new MyNestedStack(this, 'Nested1'); appears to work.  The example  https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/aws-cloudformation needs to be changed to reflect this.  It also does not compile -which made me suspicious anyway:
constructor(scope: Construct, id: string, props: cfn.NestedStackProps)
must be changed to constructor(scope: Construct, id: string, props?: cfn.NestedStackProps)

**Comment by davidsteed** [comment]
But when I use this in the stack I want to deploy ie. passing the a cluster generated in the parent to a child I get Resolution error: Cannot use resource XXX in a cross-environment fashion, the resource's physical name must be explicit set or use `PhysicalName.GENERATE_IF_NEEDED`
Not sure what to do

**Comment by cmckni3** [comment]
Right, you would need to pass in props to the nested stack or specify it as optional in TypeScript as you have done with `constructor(scope: Construct, id: string, props?: cfn.NestedStackProps)`

**Comment by cmckni3** [comment]
It sounds like you are trying to use a resource in another region?

> What I am actually trying to do is register certificates in a stack in us-east-1 and use them in another stack in another region.

Notes about certificates:

1. If it's for ELB, the certificate and ELB must be in the same region.
2. If it's CloudFront, the certificate must be in us-east-1

https://docs.aws.amazon.com/acm/latest/userguide/acm-regions.html

**Comment by cmckni3** [comment]
Awesome @eladb. I see 1.20.0 was released.

**Comment by cmckni3** [comment]
For posterity:

This works perfectly now without my workaround. I tried 1.40.0 and it works great. Also, nice to see the `Name` tag added automatically.
