### ISSUE TITLE
Make Lambda Function VPC-enabled After Creation

### ISSUE THREAD

**Issue by ccloutier** [aws/aws-cdk#5600]
### Description
I would like to have my Lambda function get access to a VPC after the creation of the Lambda `Function`. During creation of the instance, you can assign it via the "vpc" parameter, but I have not found a way to assign the VPC after the fact. Perhaps I'm missing something but I've found nothing that relates to this subject.

### Use Case

If I create a lambda in a construct and later create a VPC in my stack __init__ class, I would like to be able to attach that lambda to a VPC. I have tried to find a way to accomplish this using the `Connections` object assigned to the lambda, but the documentation says `Will fail if not a VPC-enabled Lambda Function`.

### Proposed Solution

Some sort of method that allows me to add a VPC, much like the already existing `add_permission, add_environment`, etc. methods. It shouldn't have to return anything. Perhaps like:

```
def add_to_vpc(self, vpc: IVpc) -> None
```

---

This is a :rocket: Feature Request

**Comment by netroy** [comment]
@calvincloutier you can pass the the VPC object in the `Function` constructor.
Cloudformation will detect this change, & add the lambda function to that VPC automatically.

**Comment by calvincloutier** [comment]
@netroy thank you for the response! Unfortunately I'm not totally following you. My situation is that I first created a lambda `Function`, followed by a `VPC` instance. In this order, I can't find a way to assign that VPC to the function I've created. There appears to be no method to so, which is what I'm proposing.

I've tried using `setattr`, but the cdk does not appear to recognize this change:
`setattr(example_lambda, 'vpc', example_vpc)`

I also tried through object assignment, but this threw a TypeError:
`example_lambda['vpc'] = example_vpc`

If I'm missing something would you mind providing a quick example?

**Comment by netroy** [comment]
@calvincloutier 
I assume you are creating your lambda function with code like this
```python
function = aws_lambda.Function(self, "lambda_function",
                                    runtime=aws_lambda.Runtime.PYTHON_3_7,
                                    handler="lambda-handler.main",
                                    code=aws_lambda.Code.asset("./lambda"))
```

and then later creating a VPC with something like
```python
vpc = aws_ec2.Vpc(self, "NewVPC", max_azs=2)
```

You can now change the original lambda code to 

```python
function = aws_lambda.Function(self, "lambda_function",
                                    runtime=aws_lambda.Runtime.PYTHON_3_7,
                                    handler="lambda-handler.main",
                                    code=aws_lambda.Code.asset("./lambda"),
                                    vpc)
```

adding the VPC parameter at the end would tell Cloudformation that 
* if this lambda does not exist, then create a new lambda in the VPC
* if this lambda already exists, but is not in the VPC, then move it to the VPC
* if this lambda is already in the VPC, then do nothing

This logic is handled by Cloudformation. 
So, you don't need new code to define updates on your resources. 
You can simply change the original code for that resource, & Cloudformation would create a change-set, & apply it correctly.

**Comment by calvincloutier** [comment]
@netroy 
Thanks for the example, that will resolve my issue!

Even so, I would still advocate for the creation of a method to handle this. Some `Function` parameters have one (environment, layers, etc.) and some don't, so it would be good practice to have one for all modifiable parameters to the function itself.

**Comment by LiveGood** [comment]
I also agree with OP. Being able add vpc, security group or bundling after creation of the lambda would be very useful. I am currently trying to make our lambda generation very generic and then add specific options to each lambda, but I can't find a way to do some things after the creation of the lambda, which is weird because in the AWS console, you can update any part of a lambda after it's creation.
