### ISSUE TITLE
ApplicationMultipleTargetGroupsFargateService missing from ecs.patters nuget package

### ISSUE THREAD

**Issue by kalvagadda** [aws/aws-cdk#5605]
Hi,
I was planning to use ApplicationMultipleTargetGroupsFargateService construct but it is not available in 1.19.0 nuget package of ecs patterns, it's available according to 1.19.0 documentation. Not sure whether this is issue with documentation or it's a bug as it's missing from nuget package.

https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs-patterns.ApplicationMultipleTargetGroupsFargateService.html

---

This is a 📕 documentation issue

**Comment by rix0rrr** [comment]
Unfortunately our docs are currently a little ahead of the release. Will be fixed during the next release. Sorry for the inconvenience.
