### ISSUE TITLE
Problem with auto-naming of singleton lambda functions

### ISSUE THREAD

**Issue by reidca** [aws/aws-cdk#5616]
### The Question
When creating a Singleton Lambda function (https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-lambda.SingletonFunction.html) and not specifying the FunctionName  property specifically, CDK creates a name in the format "StackName-SingletonLambdaGUID"

e.g. S3FtpStack-SingletonLambda0d11343f709a4e728c0caf32-XRCK830I30HY

If you have multiple singleton lambda functions this makes it impossible to work out what the function does since they look identical apart from the guid at the end.

I would have expected CDK to use the resource name provided to stem the function name just like it does when creating a  lambda.Function.

e.g. S3FtpStack-ftpUploaderHandler6825122D-1LK6V6JG68LPJ

I do not want to name the function specifically because this then makes it impossible for cloudformation to replace the function.

Is this expected behaviour? If so why and could it be changed?

### Environment

  - **CDK CLI Version:** 1.15.0 (build bdbe3aa)
  - **Module Version:**  1.11.0",
  - **OS:** All
  - **Language:** TypeScript

**Comment by cmckni3** [comment]
I have the same issue with [logical id](https://docs.aws.amazon.com/cdk/latest/guide/identifiers.html#identifiers_logical_ids) generation in general. I set a `description` on singleton lambda to help me identify them.

I cleaned up logical ids by overriding [allocateLogicalId](https://github.com/aws/aws-cdk/blob/0f0e2055cab08551bc6e5dfb8a1b6219368263c5/packages/%40aws-cdk/core/lib/stack.ts#L697).

I understand the reasoning behind the unique id generation and logical id stability. It makes it difficult to identity resources (especially in nested stacks). It seems to have been discussed before in #1424 and #1594.

I would appreciate guidance from the CDK team as well.

**Comment by reidca** [comment]
Reading the docs it seems you should be able to override the logical id generation however this doesn't work in my tests.

```
let baseCfnFunction = myFunction.node.defaultChild as lambda.CfnFunction
baseCfnFunction .overrideLogicalId("mylambdaname")
```

When I use this code on a lambda.SingletonFunction I get a runtime undefined error:

```
Cannot read property 'overrideLogicalId' of undefined
Subprocess exited with error 1
```

**Comment by cmckni3** [comment]
I ran into the same issue. The method definitely exists on `CfnElement` still.

`renameLogicalId` may work.

**Comment by cmckni3** [comment]
https://github.com/aws/aws-cdk/issues/207#issuecomment-515507159

**Comment by cmckni3** [comment]
Looks like `defaultChild` is not set for some reason.

**Comment by nija-at** [comment]
@reidca & @cmckni3 - we have an option for this called [`lambdaPurpose`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-lambda.SingletonFunction.html#lambdapurpose) as part of `SingletonFunction`. 

Have you tried using that?

**Comment by cmckni3** [comment]
@nija-at yes, I figured that out.

Is it possible to override purpose on CDK provided custom resources?

**Comment by reidca** [comment]
> @reidca & @cmckni3 - we have an option for this called [`lambdaPurpose`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-lambda.SingletonFunction.html#lambdapurpose) as part of `SingletonFunction`.
> 
> Have you tried using that?

Can I understand why the Lambda.SingletonFunction is different from the Lambda.Function in the way they are named by CDK?

**Comment by nija-at** [comment]
The `SingletonFunction` lets you add this function into your stack any number of times and guarantees that it will be added only once, as long as the `uuid` and the `lambdaPurpose` remain the same. 

This allows for another construct to define a lambda function as part of its construction (using `SingletonFunction`) such that this other construct can be added to the stack any number of times  while guaranteeing that the lambda function is added only once. For example, the [`GlobalTableCoordinator`](https://github.com/aws/aws-cdk/blob/0f0e2055cab08551bc6e5dfb8a1b6219368263c5/packages/%40aws-cdk/aws-dynamodb-global/lib/global-table-coordinator.ts#L15) construct can be added to your stack any number of times but there will be one and only one of the underlying lambda function in the stack.

On the other hand, the regular `Function` construct will fail with the error that the function already exists in the stack.

Hope that makes sense?

Closing this issue for now. Please reopen if there's something I've missed.
