### ISSUE TITLE
[apigateway] support lambda request authorizer

### ISSUE THREAD

**Issue by nija-at** [aws/aws-cdk#5617]
Add support for lambda request authorizer - https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-use-lambda-authorizer.html

Upvote this issue if you're looking for this.

----

This is a :rocket: Feature Request

**Comment by CaerusKaru** [comment]
Isn't this already supported? [Source](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-apigateway/lib/authorizers/lambda.ts)

**Comment by nija-at** [comment]
In progress - https://github.com/aws/aws-cdk/pull/5642

**Comment by nija-at** [comment]
This is complete #5642
