### ISSUE TITLE
Lambda-DLQ Integration:Message Getting truncated in DLQ message attribute (Error Message)

### ISSUE THREAD

**Issue by sacag** [aws/aws-cdk#5623]
### Environment

  - **CLI Version      :**
  - **Framework Version:** cdk 1.19 (.net core 2.1)
  - **OS               :** Windows 10
  - **Language         :** C#

### Other

--- 

This is :bug: Bug Report

**Comment by sacag** [comment]
CDK code:
'
var testFunc = new Function(this, "Test-SA_Func", new FunctionProps
            {
                Runtime = Runtime.DOTNET_CORE_2_1,
                Code = Code.FromAsset("src/Resources/AWSLambda1/AWSLambda1/AWSLambda1.zip"),
                FunctionName = "Test-SA_Func",
                Handler = "AWSLambda1::AWSLambda1.Function::FunctionHandler",
                Timeout = Duration.Seconds(10),               
                DeadLetterQueueEnabled = true,
                DeadLetterQueue = new Queue(this, "Test-SA-DLQ",
                new QueueProps
                {
                    QueueName = "Test-SA-DLQ",

                }),               
                MemorySize = 256,

            });
'

Function Handler code:
'
public class Function
    {      
        public void FunctionHandler(ILambdaContext context)
        {
            string test = "<km:FMIMessage xmlns:km='http://xsdrepo.foundationmedicine.com/messaging/esb' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:schemaLocation='http://xsdrepo.foundationmedicine.com/messaging/esb http://xsdrepo-qa.foundationmedicine.com/messaging/esb/ESBMessageV3.xsd'><km:Header><km:MsgVersion>1</km:MsgVersion><km:MsgType>CRMEvents</km:MsgType><km:MsgTypeFilter>Entity.Study</km:MsgTypeFilter><km:Source>FMI.CRM.Integration.Outbound.Service</km:Source><km:Route>activemq:topic:crm.events</km:Route><km:Destination>ALL</km:Destination><km:ReplyTo/><km:CorrelationID>ae3ba1ca-bcf3-4e03-a743-b80757154278</km:CorrelationID></km:Header><km:Payload><CrmEvent xmlns='http://xsdrepo.foundationmedicine.com/messaging/crm' xmlns:xsd='http://www.w3.org/2001/XMLSchema' xsi:schemaLocation='http://xsdrepo.foundationmedicine.com/messaging/crm http://xsdrepo-qa.foundationmedicine.com/messaging/crm/event.xsd'><Entity>Study</Entity><Id>{670E73EF-4C18-EA11-A811-000D3A1913BC}</Id><Event>Update</Event><Properties><Property><Type/><Name>StudyName</Name><Value>FoundationOne-BPA-PRO-19-38699</Value><FormattedValue/><IsKey>false</IsKey></Property><Property><Type/><Name>ClientId</Name><Value>{CEA8D5F0-F4C7-E811-A961-000D3A1D7B43}</Value><FormattedValue/><IsKey>false</IsKey></Property><Property><Type/><Name>ClientName</Name><Value>AutomationClient</Value><FormattedValue/><IsKey>false</IsKey></Property><Property><Type/><Name>BaitSet</Name><Value>T7</Value><FormattedValue/><IsKey>false</IsKey></Property><Property><Type/><Name>ClientProjectName</Name><Value/><FormattedValue/><IsKey>false</IsKey></Property><Property><Type/><Name>StudyId</Name><Value>{670E73EF-4C18-EA11-A811-000D3A1913BC}</Value><FormattedValue/><IsKey>false</IsKey></Property></Properties></CrmEvent></km:Payload></km:FMIMessage>";
            try
            {
                int i = 0;
                int j = 10 / i;
            }
            catch (Exception)
            {
                XmlDocument doc = new XmlDocument();
                doc.LoadXml(test);

                string json = JsonConvert.SerializeXmlNode(doc);
                throw new CustomException(json);
            }
            
        }
    }

    public class CustomException : Exception
    {
        public CustomException(string message) : base(message)
        {
        }
    }
'

**Comment by sacag** [comment]
I finally found the documentation where it clearly says that ONLY first 1 KB of message is sent to DLQ for async lambda invocation integrated with DLQ. https://docs.aws.amazon.com/lambda/latest/dg/invocation-async.html#invocation-async-destinations

Any thoughts on how I can get more amount of data to DLQ from async lambda invocation?

**Comment by nija-at** [comment]
Unfortunately, this seems to be a limitation of Lambda DLQs.

If you really want to get more of the error message out, you'll have to add a global try-catch in your lambda function and in your catch block, capture and send all of the info that you would like captured to your own data store that supports larger data storage (DynamoDB, S3, etc.).
