### ISSUE TITLE
Update encryptionKey  attribute in TransformOutput to accept IKey instead of Key

### ISSUE THREAD

**Issue by foxpro24** [aws/aws-cdk#5624]
### The Question

Taking a look at the [usage](https://github.com/aws/aws-cdk/blob/0f0e2055cab08551bc6e5dfb8a1b6219368263c5/packages/%40aws-cdk/aws-stepfunctions-tasks/lib/sagemaker-transform-task.ts#L197) of `encryptionKey ` in [TransformOutput](https://github.com/aws/aws-cdk/blob/0f0e2055cab08551bc6e5dfb8a1b6219368263c5/packages/%40aws-cdk/aws-stepfunctions-tasks/lib/sagemaker-task-base-types.ts#L533), it seems we only need the arn of the key. In such case we should update the type to `Ikey`. This will enable us to use an existing key defined or grab it from a bucket. 

### Environment

  - **CDK CLI Version:** 1.17.1
  - **OS:** all
  - **Language:** TypeScript

**Comment by skinny85** [comment]
Thanks for opening the issue @foxpro24 . Would you be interested in contributing a fix for it?

**Comment by foxpro24** [comment]
@skinny85 Sure, I would be happy to contribute the fix.

**Comment by shivlaks** [comment]
Resolved in #7429
