### ISSUE TITLE
Status of Kinesis Firehose module

### ISSUE THREAD

**Issue by lukehedger** [aws/aws-cdk#5626]
What is the status of the Kinesis Firehose construct - is it being actively worked on or is it planned work? It'd be helpful to have this information to determine whether we can wait for the module to land or to define this part of our infra in another way.

### Use Case

Define Kinesis Data Firehose infrastructure using the CDK.

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by SomayaB** [comment]
Hi @lukehedger, sorry for the late reply. We are not working on this Firehose at the moment but we welcome any contribution.

**Comment by lukehedger** [comment]
This feature is now being tracked in #7536 - add a 👍 there if you'd like to see it implemented!

**Comment by iliapolo** [comment]
Closing in favor of the tracking issue mentioned here: https://github.com/aws/aws-cdk/issues/7536
