### ISSUE TITLE
aws-kms - Asymmetric keys

### ISSUE THREAD

**Issue by sblackstone** [aws/aws-cdk#5639]
Please let me know if I missed something, is there not a way to create an asymmetric key via the aws-kms module?   I've been grepping and googling and can't find anything anywhere..

**Comment by skinny85** [comment]
This is still waiting on CloudFormation: https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/337

**Comment by donatoaz** [comment]
It seems the Cloudformation side of things is taken care of: https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-kms/pull/24 so this might be coming soon now.

**Comment by njlynch** [comment]
As of CDK v1.77.0 (released Dec 7, 2020), this functionality is available in the `CfnKey` construct, but has not yet been bubbled up to the `Key` construct.

Volunteers welcome to help add this functionality! We would want to define ["enum-like"](https://github.com/aws/aws-cdk/blob/master/DESIGN_GUIDELINES.md#enums) classes for the key spec and key usage, and then add them as properties on `KeyProps`, along with validation that only valid combos are used (e.g., RSA 2048 + SIGN_VERIFY is invalid). If anyone is interested in contributing, I'm happy to work with you to get it in!

In the meantime, you can use [escape hatches](https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html#cfn_layer_resource) to access the `keySpec` and `keyUsage` properties of the underlying `Key`. The following is an example of setting up an asymmetric ECC 521 key for sign/verify operations:

```ts
const key = new kms.Key(stack, 'MyKey');
const cfnKey = key.node.defaultChild as kms.CfnKey;
cfnKey.keySpec = 'ECC_NIST_P521';
cfnKey.keyUsage = 'SIGN_VERIFY';
```
