### ISSUE TITLE
Nested Fn::Join doesn't work with Fn::Split

### ISSUE THREAD

**Issue by GusEggert** [aws/aws-cdk#5655]
If Fn::Split is used with nested Fn::Joins, then an optimization attempting to flatten the joins incorrectly assumes the value of the join is an array at synth time, when it fact it's a late-binding CloudFormation list.

I'm trying to append a new security group to a list of existing security groups that are imported via a CFN value.

### Reproduction Steps

```typescript
const securityGroupIds = Fn.split(",", Fn.importValue("SecurityGroupIDs"));
const securityGroup = new SecurityGroup(this, "SecurityGroup", {
    description: `security group`,
    vpc: vpc
});

// mimic synth, fails with error
stack.resolve(Fn.join(",", [
                Fn.join(",", securityGroupIds),
                securityGroup.securityGroupId,
            ]))
```

### Error Log
```
      values.splice(i, 1, ...el['Fn::Join'][1]);
             ^
source-map-support.js:465
TypeError: Resolution error: Found non-callable @@iterator.
Object creation stack:
  at new FnJoin (node_modules/@aws-cdk/core/lib/cfn-fn.ts:655:26)
  at Function.join (node_modules/@aws-cdk/core/lib/cfn-fn.ts:45:12)
...
```

### Environment

  - **CLI Version      :*1.19.0 (build 5597bbe)*
  - **Framework Version:*        "@aws-cdk/core": "1.19.0"*
  - **OS               :*MacOS*
  - **Language         :*Typescript*

### Other

The bug occurs here:

https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/core/lib/private/cloudformation-lang.ts#L158

The value that it's trying to spread into the splice is not an array, but an object that CFN will resolve into a list:

```
> JSON.stringify(el['Fn::Join'][1])
"{"Fn::Split":[",",{"Fn::ImportValue":"SecurityGroupIDs"}]}"
```

I *think* that if the `isSplicableFnJoinIntrinsic` function were updated to also check `Array.isArray(obj['Fn::Join'][1])`, then it would skip the optimization in this case.

--- 

This is :bug: Bug Report

**Comment by eladb** [comment]
Thanks. Ack

**Comment by marcheil** [comment]
This also breaks with split -> importvalue -> sub nesting. Like so:
