### ISSUE TITLE
Error Handling for step functions.

### ISSUE THREAD

**Issue by miaekim** [aws/aws-cdk#5673]
### Use Case

CDK already supports Condition.

https://docs.aws.amazon.com/step-functions/latest/dg/amazon-states-language-choice-state.html

However, CDK needs to support Error Handling when the step fails.

https://docs.aws.amazon.com/step-functions/latest/dg/tutorial-handling-error-conditions.html

### Proposed Solution

There is [next function](https://github.com/aws/aws-cdk/blob/9d19aef869f27001ed88189fd277aa721de29886/packages/%40aws-cdk/aws-stepfunctions/lib/chain.ts#L57), we need catch function.

**Comment by jogold** [comment]
See [`addCatch()`](https://github.com/aws/aws-cdk/blob/v1.19.0/packages/@aws-cdk/aws-stepfunctions/lib/states/task.ts#L137
) and [`addRetry()`](https://github.com/aws/aws-cdk/blob/v1.19.0/packages/@aws-cdk/aws-stepfunctions/lib/states/task.ts#L137
).

https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-stepfunctions.Task.html#methods

**Comment by miaekim** [comment]
Thanks!

**Comment by ddgr01** [comment]
Looks like  
[addCatch](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-stepfunctions.Task.html#add-wbr-catchhandler-props-span-class-api-icon-api-icon-deprecated-title-this-api-element-is-deprecated-its-use-is-not-recommended-span) api element is deprecated.

**Comment by ingwinlu** [comment]
Since google dropped me off here:
The whole Task construct is deprecated, not just addCatch. However it is used the same way on the constructs that replaced Task (LambdaInvoke, ...)
