### ISSUE TITLE
ec2: MachineImages that use SSM queries get unwantedly replaced on deployments

### ISSUE THREAD

**Issue by phillipCouto** [aws/aws-cdk#5675]
## General Issue

I currently have a CDK project with many stacks in them and the issue I am having is I have one stack that is a generic load balancer shared between applications and the other is an EC2 instance that is accessed through the load balancer. I am making a change to the load balancer but the CDK deploy function seems to run the deploy on any stacks that have resources referenced by my load balancer stack. The EC2 instance stack has no changes and when I run cdk diff on that stack it shows no changes but when I run deploy on the EC2 stack or on the load balancer stack which runs deploy on the EC2 stack it detects the AMI for the latest version of windows is different and tries to replace my instance. The issue is I deployed the EC2 stack back in November which for my region used AMI `ami-07d23537f44fe67c1` but now the latest version in my region is `ami-06eed5c2539ba3e74`. I am using the `ca-central-1` region.

I feel like this is a bug as I can't see why an EC2 instance should be replaced after deployment just because the latest AMI was updated.

### Environment

  - **CDK CLI Version:** 1.19.0
  - **Module Version:** 1.19.0
  - **OS:** macOS 10.15.2
  - **Language:** Typescript

**Comment by rix0rrr** [comment]
That is fair. As a workaround, you can use `GenericWindowsImage` which takes an AMI map:

```ts
new GenericWindowsImage({
  'ca-central-1': 'ami-07d23537f44fe67c1'
});
```

**Comment by rix0rrr** [comment]
To fix this:

* Make it clear in the documentation that this type of image will always be up to date and may cause replacements.
* Direct people to `LookupMachineImage`.
* Make a `MachineImage` class with static factories to mirror the enum-like pattern.
