### ISSUE TITLE
Service Action Enums in CDK

### ISSUE THREAD

**Issue by lohithsamaga** [aws/aws-cdk#5676]
When creating IAM policies we need to provide actions as strings like "s3:GetObject".
AWS Java SDK provides these actions in each package. For example S3Actions enum.

So, instead of String, we can use S3Actions.GetObject.getActionName()

However, now, we need to import the related AWS SDK in the cdk project.
Can we have this enum as part of the respective cdk package too?

### Use Case
Creation of IAM policies
No need to remember action name strings. All action names will be AWS CDK variables.

### Proposed Solution

For example: S3.
Include com.amazonaws.auth.policy.actions.S3Actions in S3 CDK package.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
https://awscdk.io/packages/iam-floyd@0.4.0#/ seems to fill this void

**Comment by husny-ahamed-mg** [comment]
Any update on this??

**Comment by mmoallemi99** [comment]
I'm surprised such a thing doesn't already exist
