### ISSUE TITLE
CfnAuthorizer: name is required by CloudFormation

### ISSUE THREAD

**Issue by thantos** [aws/aws-cdk#5678]
CDK type `CfnAuthorizer`'s `name` property is optional, but stack deployment fails when omitted. On adding a name, the deployment succeeded. 

cdk: https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-apigateway.CfnAuthorizer.html
cfn: https://docs.aws.amazon.com/apigateway/api-reference/resource/authorizer/

### Reproduction Steps

```typescript
    const authorizer = new CfnAuthorizer(this, 'authorizer', {
      restApiId: coreApi.restApiId,
      type: "TOKEN",
      identitySource: "method.request.header.Authorization",
      authorizerResultTtlInSeconds: 300,
      authorizerUri: `arn:aws:apigateway:${this.region}:lambda:path/2015-03-31/functions/${authorizerFunction.functionArn}/invocations`,
      authorizerCredentials: authorizerRole.roleArn,
      //name: "authorizer"
    });
```

### Error Log

```
 4/9 | 12:00:58 AM | CREATE_FAILED        | AWS::ApiGateway::Authorizer   | authorizer 1 validation error detected: Value null at 'createAuthorizerInput.name' failed to satisfy constraint: Member must not be null (Service: AmazonApiGateway; Status Code: 400; Error Code: ValidationException; Request ID: 2f1b2889-cda1-499f-831e-527c8695128f)
```

### Environment

  - **CLI Version      :** `1.19.0 (build 5597bbe)`
  - **Framework Version:** `v12.14.0`
  - **OS               :** `Windows 10`
  - **Language         :** `Typescript`

### Other

After adding a name...
```
 4/9 | 12:05:33 AM | CREATE_COMPLETE      | AWS::ApiGateway::Authorizer   | authorizer
```

--- 

This is :bug: Bug Report

**Comment by netroy** [comment]
From the API docs, looks like `name` is required when creating new Authorizers
[v1 docs](https://docs.aws.amazon.com/apigateway/api-reference/link-relation/authorizer-create/) & [v2 docs](https://docs.aws.amazon.com/apigatewayv2/latest/api-reference/apis-apiid-authorizers.html#CreateAuthorizer)

Perhaps the Cloudformation docs are incorrect?

**Comment by nija-at** [comment]
Internal reference: issues/CFN-30099

**Comment by radarcg** [comment]
This seems to be an issue again in the 2.0 CDK library, I just ran into this issue.
