### ISSUE TITLE
rds.DatabaseCluster creates SecurityGroup without rules

### ISSUE THREAD

**Issue by konstantinj** [aws/aws-cdk#5680]
While creating an rds.DatabaseCluster it also created a SecurityGroup but without rules so that the DatabaseCluster is not reachable.

### Reproduction Steps

```typescript
const database = new rds.DatabaseCluster(this, 'DatabaseCluster', {
            removalPolicy: RemovalPolicy.DESTROY,
            defaultDatabaseName: 'wordpress'
            masterUser: {
                username: 'wordpress',
            },
            instances: 1,
            engine: rds.DatabaseClusterEngine.AURORA,
            instanceProps: {
                instanceType: ec2.InstanceType.of(ec2.InstanceClass.T3, ec2.InstanceSize.SMALL),
                vpc: vpc,
                vpcSubnets: {
                    subnetType: ec2.SubnetType.PRIVATE,
                },
            }
        })
```

### Environment

  - **CLI Version      :** 1.19.0
  - **Framework Version:** 1.19.0
  - **OS               :** osx
  - **Language         :** Typescript

--- 

This is :bug: Bug Report

**Comment by netroy** [comment]
@konstantinj can you please share what your VPC looks like?
with a `new Vpc(this, 'VPC')`,  I'm seeing an "Allow all outbound traffic" egress rule.

**Comment by SomayaB** [comment]
Closing this issue since there hasn't been a response in a while. Feel free to reopen.
