### ISSUE TITLE
Nested stacks must be defined within scope of another non-nested stack error when using cfn.NestedStack

### ISSUE THREAD

**Issue by davidsteed** [aws/aws-cdk#5686]
Nested stacks must be defined within scope of another non-nested stack error when using cfn.NestedStack

### Reproduction Steps

The example given in the documentation does not work
Copy and paste example https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/aws-cloudformation 
btw this does not compile without modification
```
constructor(scope: Construct, id: string, props: cfn.NestedStackProps)
```
must be changed to 
```
constructor(scope: Construct, id: string, props?: cfn.NestedStackProps)
```
otherwise this does not compile

### Error Log

Nested stacks must be defined within scope of another non-nested stack when running cdk synth

### Environment

  - **CLI Version      :1.19.0
  - **Framework Version:**
  - **OS               :Mac
  - **Language         :typescript

### Other

--- 

This is :bug: Bug Report

**Comment by davidsteed** [comment]
I think this is related to  #5594

**Comment by eladb** [comment]
Thanks for the report. Indeed the sample in the README is broken.
Fix: https://github.com/aws/aws-cdk/pull/5729
