### ISSUE TITLE
EKS: Control Plan Logs

### ISSUE THREAD

**Issue by kossmoboleat** [aws/aws-cdk#5709]
### The Question

We're trying to setup log shipping from EKS clusters to CloudWatch according to [this AWS guide](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Container-Insights-setup-EKS-quickstart.html). This logging setup needs to setup the instance role of the cluster to allow sending to CloudWatch. CDK seems to create a role that doesn't have this permission by default.

I don't see how we can specify/craete or modify the IAM role to add permissions for writing/modifying CloudWatch. Is there another way to achieve this or would this be a feature request?

I've also created a [stackoverflow question about this](https://stackoverflow.com/questions/59643258/how-to-modify-the-default-capacity-instance-role-for-eks-using-cdk).

### Environment

  - **CDK CLI Version:** 1.18.0
  - **Module Version:** 1.18.0
  - **OS:** OSX Mojave
  - **Language:** TypeScript

**Comment by RicoToothless** [comment]
I think use IRSA is best practice
and it's working on it
https://github.com/aws/aws-cdk/issues/3949

**Comment by kossmoboleat** [comment]
The role seems to be created based on the AutoScalingGroup according to the [CDK code](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-eks/lib/cluster.ts#L497). I assume this can be overwritten to add different roles...

**Comment by eladb** [comment]
Duplicate #4159
