### ISSUE TITLE
[redshift] L2 Construct for Redshift

### ISSUE THREAD

**Issue by bweigel** [aws/aws-cdk#5711]
Implement an L2 construct Redshift.  

### Proposed Solution

Implement an L2 construct for Redshift analogous to RDS's `DatabaseCluster` construct.
Solution should implement `ec2.IConnectable` and `secretsmanager.ISecretAttachmentTarget` interfaces. Maybe others as well?

### Other

* [X] :wave: I may be able to implement this feature request

---

This is a :rocket: Feature Request

**Comment by skinny85** [comment]
@bweigel if you want to take a stab at starting an L2 for Redshift (the first PRs do not have to be the complete thing!), go ahead - we're not working on it ATM.

Thanks!

**Comment by SomayaB** [comment]
Thanks for putting in a PR @bweigel! 👍
