### ISSUE TITLE
Python Cloudformation key override

### ISSUE THREAD

**Issue by kostrahb** [aws/aws-cdk#5714]
I am really missing an option to add a custom description (or add/replace/delete any other yaml/json key) to the Cloudformation template in python.

### Use Case

We have a script that automatically generates documentation from the Cloudformation template and this script uses `resources.*.Description` key. We would like to upgrade from plain Cloudformations to AWS CDK (preferably using python), but the fact, that python does not have something like `addPropertyOverride()` function (at least I was unable to find) blocks us a little bit. 

### Proposed Solution

Add a function to each python object that simply resolves into typescript native `addPropertyOverride()`.

**Comment by RomainMuller** [comment]
That method should be present in the same way and place than on the TypeScript counterparts.
