### ISSUE TITLE
cdk deploy method instead of cli?

### ISSUE THREAD

**Issue by eakrum** [aws/aws-cdk#5715]
Maybe this exists already but wondering if there is a workaround or possibility to incorporate a `cdk deploy` method instead of deploying resources via cli?

### Use Case

```
    app = core.App()
    MyTestStack(app, "RdsTest")
    app.synth()
    app.deploy()
```

**Comment by saltman424** [comment]
+1

**Comment by shivlaks** [comment]
Duplicate of #601
