### ISSUE TITLE
cdk diff does not work with nested stacks

### ISSUE THREAD

**Issue by cmckni3** [aws/aws-cdk#5722]
Running `cdk diff` only lists the S3 templates of the root stack as changed.

### Reproduction Steps

Create a nested stack with some resources in a nested stack. Deploy the nested stack. Add more resources to nested stack.

`cdk diff` should report the changes in the nested stack.

### Error Log

N/A

### Environment

  - **CLI Version      : 1.19.0**
  - **Framework Version: 1.19.0**
  - **OS               : macOS**
  - **Language         : TypeScript**

--- 

This is :bug: Bug Report

**Comment by LanderN** [comment]
When a resource inside a nested stack fails, the error details are nowhere to be found.

In nested stack:
```
Embedded stack [enormousId] was not successfully created: The following resource(s) failed to create: [schema].
```

Without nested stack:
```
schema Property validation failure: [Length of value for property {/Definition} is less than minimum allowed length {1}]
```

The second error is obviously way more helpful, but is nowhere to be found when using nested stacks. Maybe this is related?

**Comment by cmckni3** [comment]
@LanderN it might be related. There's an issue for that exact issue at #4489

**Comment by cmckni3** [comment]
Maybe #5722 and #4488 are related.

**Comment by cmckni3** [comment]
any updates on this?

**Comment by LanderN** [comment]
This issue, #4489, #4490 and #5974 make working with Nested Stacks in CDK much more troublesome than it should be.
Is there any update on this?

**Comment by cmckni3** [comment]
@LanderN agreed

I updated to 1.33.0 yesterday but haven’t tried running `cdk diff` yet.

**Comment by makruege** [comment]
We were forced to use nested stacks because we hit the former stack's resource limit. With nested stacks a "cdk diff" is pointless and can lead to some troublesome behaviour because you won't see changes made by Cloudformation beforehand.

**Comment by strottos** [comment]
Any updates, we just hit this problem as well and it will cause us issues with using AWS. Is there a workaround?

**Comment by cmckni3** [comment]
I wonder if the recent announcement about nested stack change sets will help.

https://aws.amazon.com/about-aws/whats-new/2020/11/aws-cloudformation-change-sets-now-support-nested-stacks/

**Comment by NetaNir** [comment]
@cmckni3 It does! I will look into what is required to add this to the cdk. Thanks!

**Comment by sindrig** [comment]
@NetaNir any updates on this?

**Comment by sindrig** [comment]
Thess issues make working with CDK extremely hard for us, and we're not getting the confidence we were hoping we would be getting from this tool.

@rix0rrr can we get any indication on when work on this issue (and other related issues https://github.com/aws/aws-cdk/issues/4489, https://github.com/aws/aws-cdk/issues/4490 and https://github.com/aws/aws-cdk/issues/5974) can be expected to begin? Or even better, finished and shipped?
@NetaNir removed the in-progress label on January 13th, what does that mean? The re-assignment by @NGL321 on January 25th, does that mean work started then?

**Comment by NetaNir** [comment]
Hi everyone!

Sorry for not providing an update for a while.  This is not currently being worked on, and it is currently not planed. The label `p1` means it is something  we want to add to the AWS CDK, and it will get a higher priority in our planing. As for the "when", I don't have an answer, we are currently focused on v2 and it is unlikely we will get to this before v2 release.

**Comment by rectalogic** [comment]
In the interim, could you pass `IncludeNestedStacks: true` to `createChangeSet` and then we can see the diffs in the CFN console (using `cdk deploy --no-execute`)? https://github.com/aws/aws-cdk/blob/master/packages/aws-cdk/lib/api/deploy-stack.ts#L249

**Comment by yukiarrr** [comment]
Using [this shell script](https://gist.github.com/yukiarrr/ca846d599d166c750bff5e8c8ac986f8), for example, it is possible to check simple diffs.

### Diff

```diff
...

 export class CdkWorkshopStack extends cdk.Stack {
   constructor(scope: cdk.App, id: string, props?: cdk.StackProps) {
     super(scope, id, props);

     new SqsStack(this, "CdkWorkshopSqsStack");
     new SnsStack(this, "CdkWorkshopSnsStack");
   }
 }

 class SqsStack extends cdk.NestedStack {
   constructor(scope: cdk.Construct, id: string, props?: cdk.NestedStackProps) {
     super(scope, id, props);

     new sqs.Queue(this, "CdkWorkshopQueue", {
-      visibilityTimeout: cdk.Duration.seconds(300),
+      visibilityTimeout: cdk.Duration.seconds(100),
     });
   }
 }

...
```

### Check

```diff
 $ YOUR_PARENT_STACK_NAMES='CdkWorkshopStack' ./nested-stack-diff.sh
 ------------------------------------------------------------------
 CdkWorkshopSqsStack...
 ------------------------------------------------------------------
 {
   Resources: {
     CdkWorkshopQueue50D9D426: {
       Properties: {
-        VisibilityTimeout: 300
+        VisibilityTimeout: 100
       }
     }
   }
 }
```

https://gist.github.com/yukiarrr/ca846d599d166c750bff5e8c8ac986f8

However, this is only a simplified version, so it is desirable to be able to check it with "cdk diff".

**Comment by robertofd1995** [comment]
Any new about this? @NetaNir

**Comment by suds-sky** [comment]
We are having same issue with our CDK app. Is there any update on this one, please. It will improve our dev workflow with nested stacks

**Comment by andreialecu** [comment]
Hate to needlessly bump this, but it is a pretty big problem and it is now among the top 2% most upvoted issues.

We recently completed a refactoring of some stacks and moved them into nested stacks, not knowing about this issue which turns out to be pretty blocking. What was meant to be a refactoring made us lose most of the usefulness of the cdk.

Is there any update here? Is this hard to implement? Any guidance into how it might be implemented would be helpful, perhaps

**Comment by andreialecu** [comment]
Hate to needlessly bump this, but it is a pretty big problem and it is now among the top 2% most upvoted issues.

We recently completed a refactoring of some stacks and moved them into nested stacks, not knowing about this issue which turns out to be pretty blocking. What was meant to be a refactoring made us lose most of the usefulness of the cdk.

Is there any update here? Is this hard to implement? Any guidance into how it might be implemented would be helpful, perhaps I can take a look at the implementation myself. 

/cc @NetaNir, @rix0rrr

**Comment by timxyz** [comment]
It could at least be documented, this must be a very common problem for people building non-trivial infrastructure - AFAIK it is the "recommended" way of working around the 500-resource limit. I too have implemented an architecture based around the nested stack pattern only to be surprised it does not work with core CDK functionality. 

Specifically, these links seem like they should mention the limitation in a big red warning block:

- `NestedStack` resource does not mention the limitation - https://docs.aws.amazon.com/cdk/api/latest/docs/core-readme.html
- CLI diff command does not mention it - https://docs.aws.amazon.com/cdk/latest/guide/cli.html
