### ISSUE TITLE
type object 'Vpc' has no attribute 'fromLookup'

### ISSUE THREAD

**Issue by riponbanik** [aws/aws-cdk#5724]
### Reproduction Steps

from aws_cdk import (
  core,
  aws_ec2 as ec2
)

class Ec2Stack(core.Stack):

    def __init__(self, scope: core.Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        # Get details of vpc, name:np
        vpc = ec2.Vpc.fromLookup(self, 'VPC', {
          isDefault: True
        });

### Error Log

Traceback (most recent call last):
  File "app.py", line 9, in <module>
    Ec2Stack(app, "ec2")
  File ".../ec2/.env/lib/python3.8/site-packages/jsii/_runtime.py", line 66, in __call__
    inst = super().__call__(*args, **kwargs)
  File ".../ec2/ec2_stack.py", line 12, in __init__
    vpc = ec2.Vpc.fromLookup(self, 'VPC', {
AttributeError: type object 'Vpc' has no attribute 'fromLookup'

### Environment

  - **CLI Version      : aws-cli/1.16.294
  - **Framework Version: 1.19.0 (build 5597bbe)
  - **OS               : Linux/4.4.0-17763-Microsoft (WSL)
  - **Language         :Python

### Other

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
@riponbanik try `Vpc.from_lookup` :)

**Comment by skinny85** [comment]
More info: https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_ec2/Vpc.html#aws_cdk.aws_ec2.Vpc.from_lookup

**Comment by riponbanik** [comment]
@skinny85 I have tried with the below but same issue 

from aws_cdk.aws_ec2 import Vpc
........
vpc = Vpc.fromLookup(self, 'VPC', {
          vpcName: "np",	
          isDefault: False
        });

**Comment by riponbanik** [comment]
@skinny85 Thanks. Why the pros are different than the typescript one?

**Comment by skinny85** [comment]
> @skinny85 Thanks. Why the props are different than the typescript one?

Property names follow the conventions of the native languages. Python uses snake_case for method names, hence `fromLookup` becomes `from_lookup`.

**Comment by RicoToothless** [comment]
for more multiple languages example
https://docs.aws.amazon.com/cdk/latest/guide/multiple_languages.html

**Comment by SomayaB** [comment]
Closing this issue since it seems to have been resolved. Feel free to reopen.
