### ISSUE TITLE
Auto assume credentialsRole for aws integration when credentialsRole is true

### ISSUE THREAD

**Issue by whimzyLive** [aws/aws-cdk#5725]
Currently `AwsIntegration` requires consumer Construct to provide assumable `IAM Role` and does not have IGrantable interface, which makes it impossible to use `<resource>.grant` syntax. 
Though, It is not that hard to create assumable IAM role and attach it to `credentialsRole`, it would be really handy to be able to grant permissions to an integration.

### Use Case

I use api-gateway <-> s3 to store raw events data, and I do that very often, mainly to store raw events. Most of the times s3 buckets are different and which means new IAM Role needs to be created  with permission to access given bucket. Currently I have a helper function which takes bucket arn and filters and returns a new Role with permission to given bucket and directory.

It would be really handy to be able to do i.e  eventsBucket.grant(s3Integration,"/raw/events"}).
Not sure what others think. 🤔

### Proposed Solution
I am Not that familiar with CDK codebase but, seems like need to create a IAM Role with `assumedBy: new ServicePrincipal('apigateway.amazonaws.com')` which some how gets used when granting permissions.  

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
Yep, I see how that can be useful.

Implementing `IGrantable` and setting `this.grantPrincipal = this.role` will do it.

**Comment by whimzyLive** [comment]
Okay, I will do a PR tonight.

**Comment by rix0rrr** [comment]
Oh and creating an implicit role when no role is given, of course.
