### ISSUE TITLE
VpnConnection should allow supplying existing CustomerGateway

### ISSUE THREAD

**Issue by ivanskof** [aws/aws-cdk#5728]
## :question: General Issue

Hi, I'm getting this error when creating VPN: 
```console
CustomerGateway with type "ipsec.1", ip-address "x.x.x.x", and bgp-asn "65000" already exists
```
Code used to create VPN:
```csharp
new VpnConnection(this, "myVPN", new VpnConnectionProps
            {
                Vpc = myVpc,
                Ip = "x.x.x.x"
            });
```
This CGW x.x.x.x indeed already exists, we are using it in some other vpc...
So, how can I create VPN using this CGW?

### Environment

  - **CDK CLI Version:** 1.19.0 (build 5597bbe)
  - **Module Version:** Amazon.CDK.AWS.EC2, Version=1.0.0.0
  - **OS:** Windows 10
  - **Language:** c#

**Comment by rix0rrr** [comment]
This is a CloudFormation question, not a CDK work item
