### ISSUE TITLE
KMS resource policy cannot grant permissions to IAM Groups

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#573]
As described [here]. This will fail upon deployment with the error `InvalidArnException`, but would be nice if we can identify this case during synthesis.

This will require:

1. Add something like `kind` to `IPrincipal` so it will be possible to identify that the principal being granted is a group.
2. Move the details of how to grant key permissions to `kms.EncryptionKey.grantXxx` from `s3.BucketRef.grant`

[here]: https://docs.aws.amazon.com/kms/latest/developerguide/key-policies.html

**Comment by rix0rrr** [comment]
Interesting. How/when did this come up?

**Comment by eladb** [comment]
My blog post 😉

**Comment by eladb** [comment]
Reopen if needed
