### ISSUE TITLE
Cloudwatch GraphWidget.to_json() does not return a valid widget json in 1.20.0 but does in 1.19.0

### ISSUE THREAD

**Issue by wsoula** [aws/aws-cdk#5735]
In cdk 1.19.0 the cloudwatch GraphWidget.to_json() function does not return a valid widget json leading to errors about metrics must be an array of arrays from cloudformation if you try to use it in a CfnDashboard dashboard_body parameter

### Reproduction Steps
* Make a new folder, below I used wsoula-test
* cd to the folder and run `cdk-init --language python`
* copy below into requirements.txt
```
aws-cdk.core==1.20.0
aws-cdk.aws-cloudwatch==1.20.0
pylint
```
* copy below into wsoula_test/wsoula_test_stack.py
```
from aws_cdk import(
    aws_cloudwatch as cloudwatch,
    core)
import json


class WsoulaTestStack(core.Stack):

    def __init__(self, scope: core.Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        widget=cloudwatch.GraphWidget(title='wsoula',left=[cloudwatch.Metric(
                metric_name='RequestCount',
                namespace='AWS/ELB',
                dimensions={'LoadBalancerName': 'foo'})])
        print(widget.to_json())
        cloudwatch.CfnDashboard(self,'wsoula',dashboard_body="""{"start": "-P1D","widgets": """+json.dumps(widget.to_json())+'}')
```
* `source .env/bin/activate`
* `pip3 install -r requirements.txt`
* `cdk synth -j > tmp`
the first line will have a bunch of extra stuff in it like `creationStack` and `ret._ensureSync` and paths if you run the above against 1.19.0 you get the below correct output:
`[{'type': 'metric', 'width': 6, 'height': 6, 'properties': {'view': 'timeSeries', 'title': 'wsoula', 'region': '${Token[AWS::Region.4]}', 'metrics': [['AWS/ELB', 'RequestCount', 'LoadBalancerName', 'foo', {'yAxis': 'left', 'period': 300, 'stat': 'Average'}]], 'yAxis': {}}}]`

The problem starts with the metrics attribute:
`'metrics': [{'value': ['AWS/ELB', 'RequestCount', 'LoadBalancerName', 'foo'], 'creationStack': ['new DropEmptyObjectAtTheEndOfAnArray (...`
it isn't an array of arrays, instead it adds a `value` attribute and other things

### Error Log

```
 1/2 | 12:40:36 PM | CREATE_FAILED        | AWS::CloudWatch::Dashboard | wsoula The dashboard body is invalid, there are 2 validation errors:
[
  {
    "dataPath": "/widgets/0/properties/metrics/0",
    "message": "Should be array"
  },
  {
    "dataPath": "/widgets/0/properties/metrics/0",
    "message": "Field \"metrics\" has to be an array of array of strings, with an optional metricRenderer object as last element"
  }
] (Service: AmazonCloudWatch; Status Code: 400; Error Code: InvalidParameterInput; Request ID: 3d6797cc-aca2-45e6-b988-688b7679ca59)
```

### Environment

  - **CLI Version      : aws-cli/1.16.240 Python/3.7.4 Darwin/18.7.0 botocore/1.12.230**
  - **Framework Version: 1.20.0**
  - **OS               : mac**
  - **Language         : python**

### Other

--- 

This is :bug: Bug Report

**Comment by netroy** [comment]
I don't know if this is actually a regression or not. 
But this is due to metrics now being evaluated lazily.
for more info see [this PR ](https://github.com/aws/aws-cdk/pull/5628).

@wsoula if you are okay with using `cloudwatch.Dashboard` instead of `cloudwatch.CfnDashboard`, I'd recommend doing it like this:

```python
class WsoulaTestStack(core.Stack):
    def __init__(self, scope: core.Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        widget=cloudwatch.GraphWidget(title='wsoula',left=[cloudwatch.Metric(
                metric_name='RequestCount',
                namespace='AWS/ELB',
                dimensions={'LoadBalancerName': 'foo'})])

        dashboard=cloudwatch.Dashboard(self,'wsoula')
        dashboard.add_widgets(widget)
```

**Comment by wsoula** [comment]
I'm using CfnDashboard because there were widgets I was adding that I could not create with the existing cdk, I may be able to create them now with the addition of the metric math, but it will take a bit to refactor.  If you are saying `GraphWidget.to_json()` will never return a valid widget json then I don't see a use case for it and think it and should be removed from the code or the documentation should be updated that it cannot be used in a dashboard, currently the documentation says: `Return the widget JSON for use in the dashboard.` and I take that to mean it will produce json suitable to be used if I construct a json dashboard.  It really seems to me like a regression since it was working as I expected before and now the behavior is different and I do not see a use case for the current output.  It was also an easy escape hatch to use which is what I thought the Cfn items were for.  Before you could use the `CfnDashboard` with the rest of the cdk but just sending everything `to_json()` now there is really no way to use `CfnDashboard` without creating your own functions to generate proper widget json which negates the purpose of the cdk.

**Comment by netroy** [comment]
I'm not familiar with why `to_json` is public, or what it's default behavior should be.

I think @rix0rrr might be able to address this better than I can.

**Comment by rix0rrr** [comment]
You can't really use L1 classes (`CfnDashboard`) with L2 classes (`GraphWidget`). You should use `Dashboard` instead. You can always write your own classes that implement `IWidget` if you need custom rendering that cannot be achieved any other way.

If you insist on using `CfnDashboard` directly, you should probably use the Token aware JSON stringifier that comes with the framework instead of the Python stringifier:

```
        cloudwatch.CfnDashboard(self,'wsoula',dashboard_body=self.to_json_string({
          "start": "-P1D",
          "widgets": [widget.to_json()]
        }))
```
