### ISSUE TITLE
Missing StepFunction Map state class in overview

### ISSUE THREAD

**Issue by stephendwu** [aws/aws-cdk#5736]
https://docs.aws.amazon.com/cdk/api/latest/docs/aws-stepfunctions-readme.html#amazon-states-language

On initial glance, noticed that `Map` was missing from the the list of "supported" state classes, however it looks like it is actually supported:
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-stepfunctions.Map.html

---

This is a 📕 documentation issue

**Comment by SomayaB** [comment]
Hi @stephendwu, thanks for reporting this. And thanks @stowns for opening a PR, much appreciated! 👍
