### ISSUE TITLE
DnsValidatedCertificate shouldn't require iam:PutRolePolicy when passing a customResourceRole

### ISSUE THREAD

**Issue by nsvarich** [aws/aws-cdk#5737]
This is a follow-up to https://github.com/aws/aws-cdk/issues/3519 and https://github.com/aws/aws-cdk/pull/3785. Even with https://github.com/aws/aws-cdk/pull/3785 in place, the `iam:PutRolePolicy` Action is still required for the deploying user.

A provided `customResourceRole` would already have the policies added ahead of time (at least for my usecase) so this IAM Action would not be required for the deploying user.

### Use Case

Users deploying stacks may intentionally only have the ability to pass existing IAM roles/policies (`iam:PassRole`) without the ability to dynamically create new roles/policies (`iam:CreateRole`, `iam:PutRolePolicy`) for security reasons.

### Proposed Solution

dns-validated-certificate.ts should not call `addToRolePolicy` when a `customResourceRole` is provided:

```typescript
        if (!props.customResourceRole) { // Proposed solution
            requestorFunction.addToRolePolicy(new iam.PolicyStatement({
                actions: ['acm:RequestCertificate', 'acm:DescribeCertificate', 'acm:DeleteCertificate'],
                resources: ['*'],
            }));
            requestorFunction.addToRolePolicy(new iam.PolicyStatement({
                actions: ['route53:GetChange'],
                resources: ['*'],
            }));
            requestorFunction.addToRolePolicy(new iam.PolicyStatement({
                actions: ['route53:changeResourceRecordSets'],
                resources: [`arn:aws:route53:::hostedzone/${this.hostedZoneId}`],
            }));
        }
```

#### Steps to reproduce the problem

For a user without the `iam:PutRolePolicy`, the following code in CDK 1.20.0:
```typescript
    new DnsValidatedCertificate(stack, 'Cert', {
      domainName: 'hello.com',
      hostedZone: helloDotComZone,
      customResourceRole: role
    });
```

Results in the following error:
```
TestCertRole/Policy (TestCertRolePolicy89A40D01) API: iam:PutRolePolicy User: arn:aws:sts::[redacted]:assumed-role/TestRole/test-user is not authorized to perform: iam:PutRolePolicy on resource: role CustomResourceRole
```

* [x] :wave: I may be able to implement this feature request
* [x] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
You can now pass `myCustomRole.withoutPolicyUpdates()` to make sure the custom resource does not change the role it's being given.
