### ISSUE TITLE
ELBv2 currently not supporting HTTP Header Conditions

### ISSUE THREAD

**Issue by konstantinj** [aws/aws-cdk#5739]
### Description

It looks like the the ELBv2 currently does not support HTTP Header Conditions.

https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-listeners.html#http-header-conditions

while Cloudformation does

https://docs.aws.amazon.com/de_de/AWSCloudFormation/latest/UserGuide/aws-properties-elasticloadbalancingv2-listenerrule-httpheaderconfig.html.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by SomayaB** [comment]
Hi @konstantinj, thanks for submitting an issue. In order to evaluate this feature request we need a bit more information. Could you edit the original post and fill out the template as much as possible to give us a better idea of what your ask is. Thanks!

**Comment by SomayaB** [comment]
Closing this issue since we need more information in order to implement this request. Feel free to reopen this issue.

**Comment by willbt** [comment]
This shouldn't be closed. 
The request is simple, the ALB Listener Rules support HTTP Headers for routing, Cloudformation supports this but CDK does not.

**Comment by allycoops80** [comment]
I would support reopening this issue:
The LoadBalancerAttribute `routing.http.drop_invalid_header_fields.enabled` is not supported in CDK, whilst other LoadBalancerAttributes such as `deletion_protection.enabled` are manageable via the ApplicationLoadBalancer class (https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationLoadBalancer.html)

This is just functionality that has been added to the API & Cloudformation that's missing in CDK

**Comment by ahmetsevki** [comment]
AWS Config for HIPAA conformance pack complains about this rule, and there is no way to set it properly using cdk
https://docs.aws.amazon.com/config/latest/developerguide/alb-http-drop-invalid-header-enabled.html

Can we re-open this?

**Comment by kellertk** [comment]
Please see https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_elasticloadbalancingv2.CfnLoadBalancer.LoadBalancerAttributeProperty.html.

```ts
declare const vpc: Vpc;
export class CdkTestingFolderStack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);

    const lb = new elbv2.ApplicationLoadBalancer(this, 'astring', {
      vpc,
      internetFacing: true,
    });
    lb.setAttribute(
      'routing.http.drop_invalid_header_fields.enabled', 'true'
    )
  }
}
```

**Comment by clueleaf** [comment]
`routing.http.drop_invalid_header_fields.enabled` is supported now in https://github.com/aws/aws-cdk/pull/22466

You can do like this:

```typescript
const alb = new elbv2.ApplicationLoadBalancer(this, 'MyALB', {
    vpc,
    internetFacing: true,
    dropInvalidHeaderFields: true,
});
```
