### ISSUE TITLE
Layers not working with sam local

### ISSUE THREAD

**Issue by Hasan-git** [aws/aws-cdk#5741]
It's the first time that I use aws and aws cdk, I am trying to add lambda layer and invoking the function locally using sam. unfortunately, the build fails but works again whenever I remove the function layer. 

![image](https://user-images.githubusercontent.com/8820596/72143301-257d3280-339f-11ea-8dc2-714e1aecf2c6.png)

---

This is a 📕 documentation issue

**Comment by nija-at** [comment]
@Hasan-git - thanks for filing this issue. 

Could you provide more details such as a CDK app that you're finding problematic and a set of steps you executed with the error message you received?

**Comment by SomayaB** [comment]
Closing this issue since there hasn't been a response in a while. Feel free to reopen.
