### ISSUE TITLE
Key-value accountId in CloudWatch's Metric class not generated

### ISSUE THREAD

**Issue by ManuelVs** [aws/aws-cdk#5747]
### The Question

I am trying to use [CloudWatch Metric](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cloudwatch.Metric.html) to autogenerate dashboards. I want to show metrics that are from an external account, but `cdk deploy` doesn't create the right metric json configuration.

### Environment

  - **CDK CLI Version:** 1.20.0 (build 021c521)
  - **Module Version:** "@aws-cdk/aws-cloudwatch": "^1.20.0"
  - **OS:** Amazon Linux 2
  - **Language:** TypeScript

### Other information

As far as I know, the commits [212687](https://github.com/aws/aws-cdk/commit/212687c1427b4e0e6dde11c69139e5036a1ce087#diff-ed7ad309f46c8a0509ff40c8ee3be7d4) and [a7f189](https://github.com/aws/aws-cdk/commit/a7f189e980fdc21b44b8d20fcb491d798ffb682e#diff-ed7ad309f46c8a0509ff40c8ee3be7d4) made it possible to have cross-region metrics (even with math expressions and alarms, that is my real concern). I think that line 50 of [rendering.ts](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-cloudwatch/lib/private/rendering.ts) file makes it, but for some reason it is not working.

If this is not the way of doing it, how can I get the `accountId` being printed? It's my last parameter to get my dashboards working.

#### How to reproduce

```bash
$ mkdir test && cd test
$ cdk init app --language typescript
```

Modify `./lib/test-stack.ts` file to:

```typescript
import * as cdk from '@aws-cdk/core';
import { Metric, GraphWidget, Dashboard } from '@aws-cdk/aws-cloudwatch'

export class TestStack extends cdk.Stack {
    constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
        super(scope, id, props);

        const metric = new Metric({
            metricName: 'MY_METRIC_NAME',
            namespace: 'MY_NAMESPACE',
            account: 'THE_OTHER_ACCOUNT_ID',
            dimensions: {
                Family: `MY_FAMILY`,
                Host: 'MY_HOST',
                URLType: 'URL_TYPE',
                CustType: 'CUST_TYPE',
            },
            period: cdk.Duration.hours(1),
            region: 'eu-west-1',
            statistic: "SampleCount"
        })

        const graphWidget = new GraphWidget({
            title: 'MY_GRAPH_WIDGET',
            left: [metric]
        })

        const dashboard = new Dashboard(this, 'MY_DASHBOARD', {
            start: "-P1D",
            dashboardName: 'MY_DASHBOARD_NAME'
        })
        
        dashboard.addWidgets(graphWidget)
    }
}
```

Of course, edit `package.json` adding `"@aws-cdk/aws-cloudwatch": "^1.20.0"`. Then run:

```bash
$ npm install
$ cdk diff
$ cdk deploy
```

#### Actual behaviour

If you go to the `` widget on the `` dashboard and click `View/Edit source`, you will notice that no key-value pair `accountId` is created inside the metric's option json (end of the array):

```json
{
    "view": "timeSeries",
    "title": "MY_GRAPH_WIDGET",
    "region": "eu-west-1",
    "metrics": [
        [ "MY_NAMESPACE", "MY_METRIC_NAME", "CustType", "CUST_TYPE", "Family", "MY_FAMILY", "Host", "MY_HOST", "URLType", "URL_TYPE", { "period": 3600, "stat": "SampleCount" } ]
    ],
    "period": 300
}
```

#### Expected behaviour

The `accountId` key-value pair is created:

```json
{
    "view": "timeSeries",
    "title": "MY_GRAPH_WIDGET",
    "region": "eu-west-1",
    "metrics": [
        [ "MY_NAMESPACE", "MY_METRIC_NAME", "CustType", "CUST_TYPE", "Family", "MY_FAMILY", "Host", "MY_HOST", "URLType", "URL_TYPE", { "accountId": "THE_OTHER_ACCOUNT_ID", "period": 3600, "stat": "SampleCount" } ]
    ],
    "period": 300
}
```

**Comment by rix0rrr** [comment]
This is the result of a design decision that on second thought was maybe not entirely thought through.

The fix will be to make the stack account-specific (right now it's account-agnostic).

See https://docs.aws.amazon.com/cdk/latest/guide/environments.html

Either make it explicit, or use the mechanism where you use `process.env.CDK_DEFAULT_ACCOUNT` to switch dynamically based on the current credentials loaded into the CLI.

**Comment by ManuelVs** [comment]
Thanks! The temporal fix works like a charm! I am waiting for the next version!

For future readers, the minimal change to make it work is to change `bin/test.ts` file as:

```typescript
#!/usr/bin/env node
import 'source-map-support/register';
import * as cdk from '@aws-cdk/core';
import { TestStack } from '../lib/test-stack';

const app = new cdk.App();
new TestStack(app, 'TestStack', {
    env: {
        region: 'eu-west-1',
        account: 'THIS_ACCOUNT_ID'
    }
});
```
