### ISSUE TITLE
S3 onCloudTrailWriteObject does not work

### ISSUE THREAD

**Issue by konstantinj** [aws/aws-cdk#5748]
I want to get my lambda function triggered on every new file in my s3 bucket. The following code deploys fine but nothing happens.

Do I need to configure CloudTrail in a special way to make this work?

### Reproduction Steps

```typescript
import cdk = require('@aws-cdk/core');
// eslint-disable-next-line no-unused-vars
import {App} from '../bin/tracking'
import {AssetCode, Function, Runtime} from '@aws-cdk/aws-lambda'
import {RetentionDays} from '@aws-cdk/aws-logs'
import {Duration} from '@aws-cdk/core'
import {Bucket} from '@aws-cdk/aws-s3'
import {LambdaFunction} from '@aws-cdk/aws-events-targets'

export class TrackingSorterStack extends cdk.Stack {
    constructor(scope: App, id: string, props?: cdk.StackProps) {
        super(scope, id, props)

        const bucket = Bucket.fromBucketName(this, 'TrackingBucket', 'ggs-tracking-production')

        const fn = new Function(this, 'TrackingSorterFn', {
            code: AssetCode.fromAsset('app/tracking-sorter/bin/'),
            handler: './tracking-sorter',
            runtime: Runtime.GO_1_X,
            logRetention: RetentionDays.TWO_WEEKS,
            memorySize: 2048,
            timeout: Duration.seconds(300),
        })

        bucket.grantReadWrite(fn)

        bucket.onCloudTrailWriteObject('SortEvents', {
            target: new LambdaFunction(fn, {})
        })
    }
}
```

### Environment

  - **CLI Version: 1.20.0**
  - **Framework Version: 1.20.0**
  - **OS: OSX**
  - **Language: Typescript**

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hey @konstantinj ,

you have to make sure the `ggs-tracking-production` bucket is part of a CloudTrail Trail, like the name suggests :). If your account doesn't have a Trail yet, you can create one using the CDK - see https://docs.aws.amazon.com/cdk/api/latest/docs/aws-cloudtrail-readme.html.

Thanks,
Adam

**Comment by konstantinj** [comment]
Ok. So obviously I don't get what this function does.

What I was looking for is a way to subscribe the lambda function to S3 events so that it's getting triggered when theres a new object in my bucket.

It seems there is no other way in CDK to subscribe a lambda to S3 I thought that must be the way.

Actually in bare Cloudformation I had the event configured together with my bucket. In another stack I had my lambda. Unfortunately with bare Cloudformation it was not possible to subscribe to the S3 bucket from the other stack. Was hoping with CDK there must be a way.

We're also having CloudTrail configured on another bucket. But I did not wanted to do anything with CloudTrail specifically.

**Comment by skinny85** [comment]
Were you looking for [S3 notifications](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-s3-notifications.LambdaDestination.html) by chance?

**Comment by konstantinj** [comment]
@skinny85 I'm using notifications currently but since I've moved my lambda to a different stack than my bucket I thought notifications do not work here. Do you have an example to your link?

What I've also tried is this but this only works with the bucket in the same stack:

```typescript
fn.addEventSource(new S3EventSource(bucket, {
            events: [s3.EventType.OBJECT_CREATED]
        }))
```

**Comment by skinny85** [comment]
I don't think I understand fully. #4671 talks about not being able to use S3 bucket notifications for imported bucket, which is accurate; however, if you're creating a new bucket, then everything should work, you just need to pass your `Bucket` object from one to the other. Or is that not working as well?
