### ISSUE TITLE
ParameterOverrides string can fail CloudFormation character limit

### ISSUE THREAD

**Issue by lukehedger** [aws/aws-cdk#5749]
It is possible to generate a CloudFormation template with a value in the `CodePipeline.Stages.Actions.Configuration.ParameterOverrides` field that violates the maximum character limit.

### Reproduction Steps

```js
new CloudFormationCreateUpdateStackAction({
  parameterOverrides: {
    test: "somethingOver1000Characters..."
  }
});
```

### Error Log

```
Pipeline (PipelineXYZ) 1 validation error detected: Value at 'pipeline.stages.4.member.actions.1.member.configuration' failed to satisfy constraint: Map value must satisfy constraint: [Member must have length less than or equal to 1000, Member must have length greater than or equal to 1]
```

### Environment

  - **CLI Version      :** aws-cli/1.16.130 Python/3.7.4 Darwin/18.7.0 botocore/1.12.120
  - **Framework Version:** 1.20
  - **OS               :** macOS
  - **Language         :** TypeScript

### Other

As a possible solution, it seems the JSON to string transformation performed [here](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-codepipeline-actions/lib/cloudformation/pipeline-actions.ts#L314) could be adapted to make us of the [`Fn::Join`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-join.html) function.

Looking at the tests it would suggest this is already being done but I have not been able to generate a CFN template that uses `Fn::Join` as asserted [here](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-codepipeline-actions/test/cloudformation/test.cloudformation-pipeline-actions.ts#L362).

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hey @lukehedger ,

thanks for opening the issue. Couple of follow-up questions:

1. I'm not sure what the original ask is. Do you want us to perform this validation sooner, so that it fails at CDK build time, instead of deployment time?
2. To force the use of `Fn::Join`, you can pass a Token inside the parameters; for example, similar like the test does:

```ts
new cpactions.CloudFormationCreateUpdateStackAction({
    // ...
    parameterOverrides: {
      RepoName: new codecommit.Repository(this, 'Repo', {
        repositroyName: 'repo'
      }).repositoryName,
    },
  }));
```

Thanks,
Adam

**Comment by lukehedger** [comment]
Hey @skinny85 - thanks for the message. The ask is primarily how do I change the generation of the `parameterOverrides` value to stop throwing this error.

I am using the `parameterOverrides` to provide the dynamic S3 location of Lambda code (for 4 Lambdas) at the pipeline's runtime, as described in this example:

```ts
parameterOverrides: {
  ...props.lambdaCode.assign(lambdaBuildOutput.s3Location),
}
```

The output looks something like this:
```json
"ParameterOverrides": "{\"LambdaSourceBucketNameParameter00000000\":{\"Fn::GetArtifactAtt\":[\"LambdaBuildOutput\",\"BucketName\"]},\"LambdaSourceObjectKeyParameter00000001\":{\"Fn::GetArtifactAtt\":[\"LambdaBuildOutput\",\"ObjectKey\"]}
```

How would I pass a Token here to force use of `Fn::Join`?

Or is the only way to actually get around the 1000 character limit to shorten the keys or split up the Lambdas across multiple stacks?

**Comment by skinny85** [comment]
> Or is the only way to actually get around the 1000 character limit to shorten the keys or split up the Lambdas across multiple stacks?

Yes. I'm 99% certain using `Fn::Join` would not change anything here.

I think the solution you're looking for is this: https://github.com/aws/aws-cdk/issues/1588#issuecomment-550502381

**Comment by lukehedger** [comment]
Okay thanks @skinny85 I will use this solution. Thanks for your help!

**Comment by skinny85** [comment]
No problem, let me know if that fixes your issue!

**Comment by lukehedger** [comment]
All fixed, thanks @skinny85!
