### ISSUE TITLE
Support Version 2 of DynamoDB Global Tables

### ISSUE THREAD

**Issue by mmesserman-verimatrix** [aws/aws-cdk#5752]
Support in CDK for the new version of Global Tables in DynamoDB (https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/globaltables.V2.html) - standard CRUD-style operations.

### Use Case

We use global tables in several of the services that we deploy with CDK. However v1 of the DDBG tables was limiting in that you could not promote a non-global table to become global once it was populated, and you could not add regions to an existing global table - we need to be able to do both of these, to support our customers in multiple regions. V2 of DDBG allows for this, so we would like to use this in our services, but CDK does not currently support it.

### Proposed Solution

Implement DDBGv2 in CDK - https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/globaltables.V2.html

### Other

https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/globaltables.V2.html

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by SomayaB** [comment]
Hi @mmesserman-verimatrix, thanks for submitting a feature request! Looks like @jogold is already on it! Thanks 👍
