### ISSUE TITLE
Enable logging for express stepfunctions

### ISSUE THREAD

**Issue by jonny-rimek** [aws/aws-cdk#5754]
Express stepfunctions work differently than the old ones, the logs are directly written to cloudwatch logs, if enabled. It would be amazing if there was a property on StateMaschineProps to activate logs.

### Use Case

For everyone using express stepfunctions and needing observability 

### Proposed Solution

Add it to the higher level construct

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by nija-at** [comment]
This will need to implement the property [`LoggingConfiguration`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-stepfunctions-statemachine.html#cfn-stepfunctions-statemachine-loggingconfiguration).
