### ISSUE TITLE
[Glue] Empty string is not considered a proper value

### ISSUE THREAD

**Issue by melgenek** [aws/aws-cdk#5763]
An empty string is a [Falsy](https://developer.mozilla.org/en-US/docs/Glossary/Falsy) js value.
It is not possible to set an empty `s3Prefix` for Glue Table https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-glue/lib/table.ts#L239
This issue also does not give to have an empty location in the Glue Database https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-glue/lib/database.ts#L93 

### Reproduction Steps
In browser execute js:
```
"" || "/data"
```
the result is "/data"

### Environment

  - **CLI Version      :** 1.20.0
  - **Framework Version:** 1.20.0
  - **OS               :** GNU/Linux
  - **Language         :** Java

### Other

A similar issue has already been closed once https://github.com/aws/aws-cdk/pull/801
There is a related issue that could be closed if there was a possibility to pass empty strings https://github.com/aws/aws-cdk/issues/5268  

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Thanks for opening the issue @melgenek . Would you consider opening us a PR changing this? It should be a simple fix.

**Comment by melgenek** [comment]
I have created a PR that fixes the s3Prefix https://github.com/aws/aws-cdk/pull/5783.
During implementation, I figured out that https://github.com/aws/aws-cdk/issues/5268 is actually a better fit for `locationUri` problem because an empty locationUri is not allowed by cloudformation so the param should not be passed at all.

**Comment by SomayaB** [comment]
Thanks for opening those PRs @melgenek, much appreciated! 👍
