### ISSUE TITLE
route53.CaaAmazonRecord ignores recordName prop

### ISSUE THREAD

**Issue by touzoku** [aws/aws-cdk#5764]
**route53.CaaAmazonRecord** construct accepts a `recordName` prop per [documentation](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-route53.CaaAmazonRecord.html), however, in the [code](https://github.com/aws/aws-cdk/blob/01220cf2139ea801a52d939d4e6e3747720dd3b7/packages/%40aws-cdk/aws-route53/lib/record-set.ts#L383) it gets the value of `props.zone.zoneName` instead of `props.recordName ?? props.zone.zoneName`. 

Therefore, regardless of what value is specified under `recordName` it would always create it for the root.

### Reproduction Steps

```typescript
const hostedZone = route53.HostedZone.fromLookup(this, 'exampleHostedZone', {
      domainName: 'example.com'
 })

new route53.CaaAmazonRecord(this, 'exampleCAARecord', {
      zone: hostedZone,
      recordName: 'subdomain.example.com',
})
```
The code above should create a CAA record for `subdomain.example.com` but creates for `example.com` instead.

### Error Log

None.

### Environment

  - **CLI Version      :** 1.20.0 (build 021c521)
  - **Framework Version:** 1.20.0 
  - **OS               :** macOS Catalina 10.15.2
  - **Language         :** English

### Other

--- 

This is :bug: Bug Report

**Comment by jogold** [comment]
Correct, it doesn't work as expected. Are you sure this is perfectly valid/supported to have CAA records on subdomains?

**Comment by touzoku** [comment]
@jogold Yes. In [RFC 6844](https://tools.ietf.org/html/rfc6844) it has a following example:

> A CAA record with an issue parameter tag that specifies a domain name
> is a request that certificate issuers perform CAA issue restriction
> processing for the corresponding domain and grants authorization to
> the certificate issuer specified by the domain name.
>
> For example, the following CAA record set requests that no
> certificates be issued for the domain 'certs.example.com' by any
> certificate issuer other than the example.net certificate issuer.
>
> certs.example.com       CAA 0 issue "example.net"

**Comment by touzoku** [comment]
By the way, a workaround for this issue is as follows:

```javascript
const hostedZone = route53.HostedZone.fromLookup(this, 'exampleHostedZone', {
      domainName: 'example.com'
 })

new route53.CaaRecord(this, 'WebsiteCAARecord', {
  zone: hostedZone,
  recordName: 'subdomain.example.com',
  values: [
    { flag: 0, tag: route53.CaaTag.ISSUE, value: 'amazon.com' }
  ]
})
```
