### ISSUE TITLE
NotificationBucketHandler uses EOL Node.js 8.10 runtime

### ISSUE THREAD

**Issue by markkesty** [aws/aws-cdk#5768]
When adding an event notification to an S3 bucket to an SNS Topic, a Lambda is created. This Lambda uses NodeJS 8.10 runtime which is EOL.

The CDK will not be able to create the function with this runtime after January 6, 2020. (Which has already passed).

### Use Case

In order to add event notifications to an S3 bucket.

### Proposed Solution

https://github.com/aws/aws-cdk/blob/v1.10.1/packages/@aws-cdk/aws-s3/lib/notifications-resource/notifications-resource-handler.ts#L82

Change to value used in master branch

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by nija-at** [comment]
This has been fixed since v1.17.0 - https://github.com/aws/aws-cdk/commit/7a3a3b1c45fd5d773db71c2a6c45a3ff64c5510c
