### ISSUE TITLE
CodeBuild SourceVersion

### ISSUE THREAD

**Issue by knorms101** [aws/aws-cdk#5777]
I would like to be able to specify the `sourceVersion` associated with a CodeBuild project. 

```typescript
new cb.Project(this, projectName, {
    source: cb.Source.gitHub({
        owner: githubOwner,
        repo: githubRepo,
      }),
    sourceVersion: "branch-name",
});
```

### Use Case

To specify which Github branch CodeBuild should use for its source version.

### Proposed Solution

Would need to add an optional `sourceVersion` property that errors if a `source` isn't specified.
https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-codebuild/lib/project.ts#L521

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by skinny85** [comment]
Hey @knorms101 ,

thanks for opening the issue, but I think I would solve it differently :).

I think we should add an optional property `branch` to the `GitHubProps` interface, and then an optional `sourceVersion` property to the [`SourceConfig` interface](https://github.com/aws/aws-cdk/blob/5292bd56ad4f7c2bf68767861c5e252b13282f34/packages/%40aws-cdk/aws-codebuild/lib/source.ts#L18-L18), and populate it from the [`GitHubSource` class](https://github.com/aws/aws-cdk/blob/5292bd56ad4f7c2bf68767861c5e252b13282f34/packages/%40aws-cdk/aws-codebuild/lib/source.ts#L573).

Would you be interested in submitting us a PR with this feature @knorms101 ?

Thanks,
Adam

**Comment by knorms101** [comment]
Hello @skinny85,

I'm happy to submit a PR for this! And I prefer your solution, so I'll plan on submitting a PR with that implementation later this week or early next week.

Thanks,
Katie

**Comment by SomayaB** [comment]
Thanks for opening a PR @knorms101, much appreciated! 👍

**Comment by skinny85** [comment]
This was done in #5890 . Thanks again for the contribution @knorms101 !
