### ISSUE TITLE
eks: node-volume-size

### ISSUE THREAD

**Issue by jialechan** [aws/aws-cdk#5785]
## :question: 

CDK typescript dose not have "node-volume-size" feature?

### The Question

```shell
eksctl create cluster \
--node-volume-size 100
```
```typescript
const eksCluster = new eks.Cluster(this, 'Cluster', {
    ???
});
```
I'm trying to change the eksctl command to TypeScript's cdk code. But it seems that it does not support the managed and node-volume-size feature? Is there any solution? Thx!
### Environment

  - **CDK CLI Version:** 1.20
  - **Module Version:** 1.20
  - **OS:** Ubuntu
  - **Language:** Typescript

**Comment by eladb** [comment]
Duplicate #5086

**Comment by pgollucci** [comment]
Yes, I also need this functionality.
