### ISSUE TITLE
DynamoDB Autoscaling for provisioned

### ISSUE THREAD

**Issue by mrpadigala** [aws/aws-cdk#5788]
working with typescript

I would like to create DynamoDB table with Provisioned options, when create using the provision through put option, autoscaling is disabled.

I would like enable the autoscaling, for this 
AWS::ApplicationAutoScaling::ScalableTarget [for write capacity and read capacity]

 I need to create the I am role "AWS::IAM::Role", attach policies

"AWS::ApplicationAutoScaling::ScalingPolicy" also need to write the details for read and write.

Documentation is not clear, can you help with this please ?

 

### Environment

  - **CDK CLI Version:** 
1.20.0 (build 021c521)
 - **Module Version:** 
  - **OS:** 
macOS Catalina  
- **Language:** 
Typescript

**Comment by RomainMuller** [comment]
Hey @mrpadigala,

Can you please show the code that you currently have (only what's relevant to the DynamoDB table & afferent auto-scaling set-up)?

**Comment by mrvindu** [comment]
Hi Romain
Thanks for asking 
I sorted my issue, here is the code


    const readScaling = Table1.autoScaleReadCapacity({ minCapacity: 5, maxCapacity: 50 });
    readScaling.scaleOnUtilization({
      targetUtilizationPercent: 50,
    });
    const writeScaling = Table1.autoScaleWriteCapacity({ minCapacity: 5, maxCapacity: 50 });
    writeScaling.scaleOnUtilization({
      targetUtilizationPercent: 50,

**Comment by RomainMuller** [comment]
Glad you figured it out!
