### ISSUE TITLE
CDK Synth doesn't create CloudFormation without full credentials (1.20.0)

### ISSUE THREAD

**Issue by RenkeMeuwese** [aws/aws-cdk#5791]
In CDK version 1.20.0 the command CDK synth now needs full credentials to run. This is an undocumented (?) breaking change. Creating a CloudFormation template for an account and region without the linked secret key and key ID is no longer possible. This means that my company currently cannot use 1.20.0, as the access key id and secret access key would not be available in the development of the templates. For automatic testing this would also be breaking, as we would obviously not want to have the full credentials in the repository that would do an integration test. Surely CDK should (continue to) be able to create templates without needing deployment credentials at that stage. 

### Reproduction Steps

Create an environment with an AWS_REGION and an AWS_ACCOUNT, but without a matching AWS_ACCESS_KEY_ID or AWS_SECRET_ACCESS_KEY.

### Error Log

[Error at /test/skeleton] Need to perform AWS calls for account [redacted], but no credentials found. Tried: default credentials.

### Environment

  - **CLI Version      :1.20.0
  - **Framework Version:1.20.0
  - **OS               :OS Mac Catalina
  - **Language         :Python 3.6.5

--- 

This is :bug: Bug Report

**Comment by richardhboyd** [comment]
Are you preforming any fromAttributes(....) calls or uploading any assets in your code? My understanding is that these are the ones that require credentials for `synth`

**Comment by skinny85** [comment]
Can you show the code that's causing this @RenkeMeuwese ?

**Comment by shivlaks** [comment]
in addition to the code as requested by @skinny85 can you also run the command with `--v` flag and share the output? Please redact the cli output as necessary.

**Comment by RenkeMeuwese** [comment]
Replicated the error in 1.21.1. I can see that despite the error message, the cdk.out is populated when performing cdk synth. However, the cdk.context.json is empty and the CLI seems to suggest that the synth step failed.. See the difference in output below when using a dummy value for account or an authenticated account.
[outputdummyvsauthenticated.pdf](https://github.com/aws/aws-cdk/files/4075894/outputdummyvsauthenticated.pdf)

**Comment by RenkeMeuwese** [comment]
Attached the output with -v
[output-v.pdf](https://github.com/aws/aws-cdk/files/4075966/output-v.pdf)

**Comment by RenkeMeuwese** [comment]
Attached: code that causes the error.

[Archive.zip](https://github.com/aws/aws-cdk/files/4076419/Archive.zip)

**Comment by amedveshchek** [comment]
Is there any update? I have the same issue: as soon as I've added VPC to my CDK code, `cdk synth` started to ask for credentials.
```
[Error at /Lambdas-Alpha] Need to perform AWS calls for account XXXXXXXXXXX, but no credentials have been configured
```
