### ISSUE TITLE
Incorrect domain name produced when using HTTPS in ApplicationLoadBalancedFargateService 

### ISSUE THREAD

**Issue by Don-CA** [aws/aws-cdk#5801]
When creating a `ApplicationLoadBalancedFargateService` with a  fully qualified `domainName`  the incorrect domain name for record the set is produced.

### Reproduction Steps

Deploy a stack that looks like this
```typescript
const app = new App();
const stack = new Stack(app, 'aws-ecs-integ');
const vpc = new Vpc(stack, 'Vpc', { maxAzs: 2 });
const cluster = new Cluster(stack, 'Cluster', { vpc });


// Loadbalancer with HTTPS
new ApplicationLoadBalancedFargateService(stack, 'myService', {
  cluster,
  memoryLimitMiB: 512,
  taskImageOptions: {
    image: ContainerImage.fromRegistry("amazon/amazon-ecs-sample"),
  },
  protocol: ApplicationProtocol.HTTPS,
  enableECSManagedTags: true,
  domainName: 'test.example.com',
  domainZone: {
    hostedZoneId: 'fakeId',
    zoneName: 'example.com.',
    hostedZoneArn: 'arn:aws:route53:::hostedzone/fakeId',
    stack,
    node: stack.node,
  },
});
```

### Error Log
Running deploy will produce the following error
` FATAL problem: DomainLabelEmpty (Domain label is empty) encountered with 'test.example.com.example.com..' (Service: AmazonRoute53; Status Code: 400; Error Code: InvalidInput`

### Environment

  - **CLI Version      : 1.20**
  - **Framework Version: 1.20**
  - **OS               : MacOS**
  - **Language         : Typescript**

### Other

This is because `determineFullyQualifiedDomainName` should be ignoring the trailing dot in the `IHostedZone.zoneName` and `HostedZone` adds the the dot in the constructor. Instead it assumes the `providedName` and `zoneName` should be concatenated and have an extra dot added.

So you get `test.example.com.example.com..` instead of `test.example.com`

--- 

This is :bug: Bug Report

**Comment by SomayaB** [comment]
Hi @Don-CA, thanks for reporting this issue and putting in a PR, much appreciated! 👍

**Comment by francipvb** [comment]
Hello all,

I found a regression of this issue.

Check this:

```typescript
    // Rest of the stack
    const nginx = new ApplicationLoadBalancedFargateService(this, "TestNginx", {
      cluster: this._cluster,
      taskDefinition: nginxTaskDefinition,
      serviceName: "nginx",
      domainZone: this._hostedZone, // dev.example.com
      domainName: Fn.join(".", ["test", this._hostedZone.zoneName]), // generates test.dev.example.com.dev.example.com
      certificate: this._certificate, // test.dev.example.com if not provided
      protocol: ApplicationProtocol.HTTPS,
      targetProtocol: ApplicationProtocol.HTTP,
    });

```
