### ISSUE TITLE
CLI: support custom CA bundles while using a proxy

### ISSUE THREAD

**Issue by rix0rrr** [aws/aws-cdk#5804]
At the moment it is not possible to specify a custom CA bundle while using the CLI's proxy support.

This is not a hard limitation, but the code path needed to support it traces through some JavaScript which lacks an API specification and it's not obvious what the right parameters would be.

Upvote this issue if you would like to see CA bundle+proxy support.

If someone could tell us what the input to this function should be in order to support both a proxy address and a CA bundle at the same time, that would be very helpful:

https://github.com/TooTallNate/node-proxy-agent/blob/master/index.js#L79

---

This is a :rocket: Feature Request

**Comment by mcable1004** [comment]
Not sure how to fix it, but glad to test if needed.

**Comment by Kyeongtaek-Lim** [comment]
We are using specify a custom CA bundle in the proxy environment by setting the following environment variables.

"HTTPS_PROXY": Proxy address
"NODE_EXTRA_CA_CERTS": a CA bundle path

**Comment by brday** [comment]
Has anybody found a fix or a work around for this issue yet. Trying to use it for work but keep getting the error: "At the moment, cannot specify Proxy (MY_PROXY_URL) and CA Bundle (MY_BUNDLE_PATH) at the same time. See https://github.com/aws/aws-cdk/issues/5804". This tool is very helpful for me on my personal project and would love to use it at work as well as teach my colleagues how to use it.

**Comment by emilioego** [comment]
Any update about the issue?

**Comment by emilioego** [comment]
@brday 
> Has anybody found a fix or a work around for this issue yet. Trying to use it for work but keep getting the error: "At the moment, cannot specify Proxy (MY_PROXY_URL) and CA Bundle (MY_BUNDLE_PATH) at the same time. See #5804". This tool is very helpful for me on my personal project and would love to use it at work as well as teach my colleagues how to use it.


We found this workaround. You have to modify the next file: **node_modules/aws-cdk/lib/api/aws-auth/sdk-provider.js** You will need to make the following changes, on switching the function **parseHttpOptions** on line 263.

![image](https://user-images.githubusercontent.com/11303493/116511593-f443b100-a8c6-11eb-9ea8-90eff206047c.png)

**Comment by RishiKapadia20** [comment]
@emilioego could you please specify (give example) to what part of the proxy url you are adding in host/hostname/href, would really apricate it, unable to get this workaround to work, i'm not sure if I am filling in the blanks correctly

**Comment by emilioego** [comment]
> @emilioego could you please specify (give example) to what part of the proxy url you are adding in host/hostname/href, would really apricate it, unable to get this workaround to work, i'm not sure if I am filling in the blanks correctly

This is the schema: 

      protocol: 'http:',
      slashes: true,
      auth: null,
      host: 'proxy-url:8080',
      port: '8080',
      hostname: 'proxy-url',
      hash: null,
      search: null,
      query: null,
      pathname: '/',
      path: '/',
      href: 'http://**proxy-url**:8080/',
      ca: readIfPossible(caBundlePath),
      keepAlive: true,

**Comment by zradlo1984** [comment]
What about this in sdk-provider.js to setup both proxy and CA budle

        const ProxyAgent = require('proxy-agent');
        config.httpOptions.agent = new ProxyAgent(proxyAddress);
        config.httpOptions.ca = readIfPossible(caBundlePath);

also _if then else_ structure is wrong in parseHttpOptions. When both proxy and CA are specified, then only last if (with CA settings) wins and overwrites proxy settings.

        if(proxyAddress && caBundlePath) {}  
        if(proxyAddress ) {} //!!!! this is logically wrong else is missing 
        if(caBundlePath) {} //!!!! this is logically wrong else is missing

correct code is

    if(proxyAddress && caBundlePath) {
        const ProxyAgent = require('proxy-agent');
        config.httpOptions.agent = new ProxyAgent(proxyAddress);
        config.httpOptions.ca = readIfPossible(caBundlePath);
    }
    else if (proxyAddress ) { .... }
    else if (caBundlePath) { .... }

**Comment by synyster90** [comment]
I found a fix doing so
`if (proxyAddress && caBundlePath) {	
	logging_1.debug('Using proxy server: %s', proxyAddress);
	config.httpOptions.proxy = proxyAddress;
	
	logging_1.debug('Using CA bundle path: %s', caBundlePath);
	config.httpOptions.agent = new https.Agent({
		ca: readIfPossible(caBundlePath),
		keepAlive: true,
	});
}`

**Comment by markusl** [comment]
Hi @rix0rrr and the team! Do you have any news on this? It's one of the main causes of confusion for our users and has been for a long time. We would be very happy if this gets fixed at some point.
