### ISSUE TITLE
EnableDockerBridge for EKS Node doesnt work

### ISSUE THREAD

**Issue by steveizzle** [aws/aws-cdk#5811]
### The Question

For me it seems that by defining bootstrapOptions: { enableDockerBridge: true }, wrong user data is created. bootstrap.sh awaits a parameter true after --enable-docker-bridge like in --use-max-pods. 

### Environment

  - **CDK CLI Version:** 1.18
  - **Module Version:** 1.20
  - **OS:** Ubuntu
  - **Language:** Typescript

### Other information
It should be easy to fix, the error should be in packages/@aws-cdk/aws-eks/lib/user-data.ts:22

**Comment by eladb** [comment]
Duplicate #5786
