### ISSUE TITLE
Cannot synthesize when cdk.out/mainfest.json is missing AND outdir set to anything besides 'cdk.out'

### ISSUE THREAD

**Issue by saltman424** [aws/aws-cdk#5815]
### What is the problem?

I am having the same problem described here: #3717 #5586

However, the cause of the problem seems to differ in that in my case, it occurs whenever I specify an outdir other than cdk.out, whether or not I call app.synth(). In this case, I get the same error of:
`ENOENT: no such file or directory, open 'cdk.out/manifest.json'`

If I synthesize without a modified outdir (producing a cdk.out/mainfest.json), and then synthesize with a modified outdir, it successfully outputs the expected files to the modified outdir. So it seems that at some point during the process it needs to read from cdk.out/manifest.json, whether or not the outdir property is set to cdk.out, and then it proceeds to behave as expected.

Is it possible that 'cdk.out' is hard-coded somewhere?

### Reproduction Steps
1. Go to any CDK project (I have tried for two different projects, and it seems to be the case for both)
2. Specify the outdir property in the arguments for the App's constructor to be anything other than 'cdk.out'
3. Remove the cdk.out directory
4. Run cdk synth

### Error Log
`ENOENT: no such file or directory, open 'cdk.out/manifest.json'`

### Environment

  - **CLI Version      : 1.20.0** 
  - **Framework Version: 1.20.0** 
  - **OS               : Windows 10** 
  - **Language         : TypeScript** 

### Other

It also appears that a cdk.out folder is created when running cdk synth with a modified outdir

Additionally, it seems that in at least one project where I am having this issue, running cdk deploy deploys the templates in cdk.out, not the specified outdir. So it seems like currently the outdir is just not really useful.

--- 

This is :bug: Bug Report

**Comment by shivlaks** [comment]
@saltman424 I think we reopened #3717 and I'd love if you could add onto that issue. Feels like we should use one issue to track and fix all potential causes. can I have you add your comment to that thread please?

**Comment by saltman424** [comment]
@shivlaks  Yeah, no problem. I just added the comment.

**Comment by SomayaB** [comment]
Closing this issue since it's being tracked at #3717.

**Comment by aloksinghGIT** [comment]
do we have a resolution on this?
