### ISSUE TITLE
Importing KMS Key or Alias requires Key ARN

### ISSUE THREAD

**Issue by jakebanks** [aws/aws-cdk#5823]
### The Question
IKey is [only obtainable with the key's ARN](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-kms-readme.html#importing-existing-keys), which is a little bit unwieldy.

I'd like to be able to import a Key by its Alias value. This is especially valuable in a multi account structure with keys that have the same alias.

I can almost achieve this via [Alias.fromAliasAttributes](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-kms.Alias.html#static-from-wbr-alias-wbr-attributesscope-id-attrs) (it is great we can use IAlias in places that IKey is expected!), but this call requires an IKey in its AliasAttributes anyway. 

### Environment

  - **CDK CLI Version:** 1.20.0 (build 021c521)
  - **Module Version:** 1.20.0
  - **OS:** Windows 10
  - **Language:** TypeScript

**Comment by humblelistener** [comment]
The real issue from my experience is that both CF & CLI takes alias as a value wherever KMS KeyId is the parameter. This allows in our architecture to have one friendly named alias per account as an input contract for people creating stacks in various accounts and regions.

Example such as [create-db-instance in rds](https://docs.aws.amazon.com/cli/latest/reference/rds/create-db-instance.html)
![image](https://user-images.githubusercontent.com/2118714/73030392-a521fb80-3e8d-11ea-8f5c-13d3a4a445d8.png)

However, this is not possible with L2 types. While IAlias extends IKey which is well thought `fromAliasAttributes ` method seem to create a dependency on IKey again as forces knowing the key id.

**Comment by skinny85** [comment]
Yep, agreed @humblelistener .

**Comment by jakebanks** [comment]
Closed by https://github.com/aws/aws-cdk/pull/8299
