### ISSUE TITLE
CLI: `cdk init` fails if run under a directory where `cdk.json` exists

### ISSUE THREAD

**Issue by rix0rrr** [aws/aws-cdk#5826]
I have a messy `~/Temp` directory where I try out all kinds of things.

It so happens that `~/Temp/cdk.json` exists, but what happens since https://github.com/aws/aws-cdk/pull/5772 is that I can't run `cdk init` anymore anywhere under `~/Temp`, which I do all the time:

```
huijbers ~/Temp> cd cdk-java-app/
huijbers ~/T/cdk-java-app> cdk init --language=java
'cdk init' cannot be run in a non-empty directory!
```

Well the directory is empty! I just made it! 

Turns out that the CLI `chdir()`s to `~/Temp` before `cdk init` is run, but it's super hard for me to figure that out.

Can I suggest that the magic `chdir` behavior only happens when applicable to an existing CDK app, for commands like `synth` and `deploy` etc?

--- 

This is :bug: Bug Report

**Comment by eladb** [comment]
Two days ago, @eladb said: "Eli, don't worry about the case where someone has a cdk.json file in /tmp, it's such a fringy case..."

**Comment by iliapolo** [comment]
@eladb Famous last words strikes again...

**Comment by rix0rrr** [comment]
I would argue this is not really a p0 though.

**Comment by jialechan** [comment]
cdk init sample-app --language=java
work for me

**Comment by iliapolo** [comment]
I am closing this issue since the [feature](https://github.com/aws/aws-cdk/issues/5691) that caused this bug was [reverted](https://github.com/aws/aws-cdk/commit/842cc5fa16248fa458753a19f9f6541f7270e0f9) in version `1.21.1`.
