### ISSUE TITLE
certificatemanager : DnsValidatedCertificate doesn't wait long enough

### ISSUE THREAD

**Issue by ralovely** [aws/aws-cdk#5831]
Hi.

I'm running into this [issue](https://github.com/aws/aws-cdk/issues/3912) still.
Twice in a row, I've had a certificate take just above 10mn to validate, where the function is set to timeout after 9:30 (ironic).
When creating a DNS validated certificate via the console, there is a warning saying it can take 30mn, or more. I'm sure this would be an extreme case, but apparently, 10mn is not long enough.

Could we increase [maxAttempts](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-certificatemanager/lambda-packages/dns_validated_certificate_handler/lib/index.js#L157) a tad more ?
(personally, I'd double go with 60 to match the console warning).

Cheers.

---
  - **CDK CLI Version:** 1.19.0 (build 5597bbe)
  - **Module Version:** "@aws-cdk/aws-certificatemanager@^1.21.0"
  - **OS:** OSX Mojave
  - **Language:** JS

**Comment by scanning** [comment]
I'm also currently experiencing the same issue. I've used this approach before and it's worked successfully but it isn't at the moment.  It seems DNS must just be taking longer to update & propagate.

**Comment by starsolutions** [comment]
There is an issue, where the lambda hit's a max timeout at 15 minutes, which is I think why the limits are currently set where they are.  I'm playing around with an idea where we could get around that limit. Will open a PR if it works :)

**Comment by skinny85** [comment]
@starsolutions any luck?

**Comment by skinny85** [comment]
I guess we could migrate DnsValidatedCertificate to our new custom resource framework.

**Comment by vineethsoma** [comment]
Not quite related to this issue but, I have a use case where I need to add the nameservers of the new sub-domain zone to its root domain zone. I am creating the DnsValidatedCertificate part of a pipeline so it just waits till I go add the nameservers and make it pass the validation. Is there anyway to make it be in Pending Validation and move on?  

I like that the cert record set gets added to the hosted zone if I use DnsValidatedCertificate instead of Certificate.

Thanks.

**Comment by starsolutions** [comment]
@skinny85  - Sorry for being out of the loop for a while.  Unfortunately I hadn't gotten a chance to look at it, got pulled into some other things.  Glad to see this is in progress though.  Let me know @nlang  if there is anything that I can help with

**Comment by SergeyRusskih** [comment]
> I guess we could migrate DnsValidatedCertificate to our new custom resource framework.

What did you mean by the 'new custom resource framework'? Do you have any workaround in mind?

**Comment by ralovely** [comment]
I think #8552 shouldn't close this.
`DnsValidatedCertificate` is still very much "active" given it's the only way to do cross-region, and the timeout issue should be at least improved, if not fixable.

The Lambda timeout is not something we can work around, but we should at least increase this function's timeout to the maximum Lambda allows.
Currently, it's 19x30s. I found (from a very un-scientifical gut estimation) that without modifying the timeout, I get around 50/60% success, against 80/90% when setting the timeout to 29x30sec.
Not perfect, but it would make this function as reliable as it can be (while waiting for native CFn cross-domain certificates).

**Comment by nlang** [comment]
@ralovely @skinny85 I already created a fix for this but the PR is outdated and was closed. If this is still an issue worth fixing I can rebase my PR on current master. Just let me know.

**Comment by ralovely** [comment]
@nlang since I change the timeout each time before creating a new certificate, I haven't encountered it lately, but I also see no reason it wouldn't be needed anymore either.
Given the change is minor and probably safe, if it can save a few headaches to other people, I'd say it's worth it.

Thank you.

**Comment by bundgaard** [comment]
We are currently experiencing this problem, should we create a new issue ticket or can we hi-jack this?

**Comment by Stf-F** [comment]
Same problem here
