### ISSUE TITLE
CLI: Don’t transfer feature flags to cdk.context.json

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#5834]
The CLI automatically transfers context keys from cdk.json to cdk.context.json. I believe feature flags should not be transferred.

### Use Case

It confuses people:

See #5832 

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by shivlaks** [comment]
@eladb I think that makes sense. Running `cdk context` would still display the keys (including feature flags) that are in `cdk.json`. Wouldn't that still be a point of confusion?

**Comment by eladb** [comment]
I think people's perception (quite legitimately) is that `cdk.context.json` includes context information obtained through context providers and managed by the CLI, while `cdk.json` includes application-level settings. Personally I'd expect that if a user (or `cdk init` for that matter) puts something in `cdk.json` under the `context` key, it won't get transferred to `cdk.context.json`. It's usually not a good practice to edit user-managed files.

**Comment by shivlaks** [comment]
Closed by #7563
