### ISSUE TITLE
eks: CIDR whitelist ranges for public API endpoints

### ISSUE THREAD

**Issue by rwkarg** [aws/aws-cdk#5839]
Allow specification of CIDR ranges to whitelist access to public cluster API endpoints.

This is similar to #5220 to configure availability of public/private API endpoints, but allows further specification of the public endpoint to only allow specific CIDR ranges to access the public API

### Use Case

Our current direct connect infrastructure does not allow private endpoints to be accessed from our internal (non-AWS) networks and we will not allow public API endpoints without specific whitelisting in place.

### Proposed Solution

Allow specification of the `publicAccessCidrs` used to configure the public API endpoint.
https://docs.aws.amazon.com/eks/latest/userguide/cluster-endpoint.html

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by eladb** [comment]
Duplicate #5220
