### ISSUE TITLE
Stack Outputs example in Core module documentation produces invalid CloudFormation

### ISSUE THREAD

**Issue by michaelday008** [aws/aws-cdk#5845]
https://docs.aws.amazon.com/cdk/api/latest/docs/core-readme.html#stack-outputs

The code sample has the following line:
```
exportName: 'Global.BucketName', // Registers a CloudFormation export
```
However, if you use this line of code in your CDK application, and use `cdk synth` to produce CloudFormation, and then try to upload it to Service Catalog or CloudFormation Designer, the following errors occur
1. Service Catalog
```
Failed to add version: Invalid templateBody. Please make sure that your template is valid
```
2. CloudFormation Designer
```
1/16/2020, 3:50:56 PM - Template contains errors.: Template format error: Output BucketName is malformed. The Name field of every Export member must be specified and consist only of alphanumeric characters, colons, or hyphens
```
Removing the period and using the following code instead will not produce a CloudFormation validation error.
```
exportName: 'BucketName', // Registers a CloudFormation export
```

The documentation should be updated with an example that produces valid CloudFormation instead of producing an error message when copied and used.

---

This is a 📕 documentation issue

**Comment by eladb** [comment]
Want to send a PR to fix this? 

https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/core/README.md
