### ISSUE TITLE
Generated Python docs infer incorrect type URL

### ISSUE THREAD

**Issue by joe-king-sh** [aws/aws-cdk#5863]
# The link destination of the S3 Bucket parameter in the Python API reference is incorrect

+ link to reference doc page:  
https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_s3/Bucket.html
https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_s3/BucketProps.html

+ describe your issue:
> lifecycle_rules (Optional[List[LifecycleRule]]) – Rules that define how Amazon S3 manages objects during their lifetime. Default: - No lifecycle rules.

The link destination of LifecycleRule parameter  is aws_cdk.**aws_ecr**.LifecycleRule.
https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_ecr/LifecycleRule.html

I think it should be  aws_cdk.**aws_s3**.LifecycleRule.
https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_s3/LifecycleRule.html

I'll be happy to fix it if I can, but are there any plans to contribute the documentation?

---

This is a 📕 documentation issue

**Comment by RicoToothless** [comment]
I face this issue today.
this issue only in Python document. 
TypeScript document is fine.

**Comment by Chriscbr** [comment]
It looks like this issue is also being tracked in [aws/jsii#1300](https://github.com/aws/jsii/issues/1300).

**Comment by RomainMuller** [comment]
I believe this is now fixed, so I'm resolving.
