### ISSUE TITLE
ALB Security Group created in wrong stack when creating ECS Service

### ISSUE THREAD

**Issue by TrueBrain** [aws/aws-cdk#5864]
https://github.com/aws/aws-cdk/pull/5813 broke our stack deployment, in a way I am currently not able to fix / work around. It seems this PR fixed one use-case, but did not consider others.

How we build ours stacks, is that we have 2 parent stacks: ECS and ALB. Next, we have one stack per service. All administrative things like roles and security-related things are all done int he ECS and/or ALB stacks.
These "service" stacks can be redeployed at any time. The benefit of this approach is that the IAM doing the redeployment only need access to the Service, and nothing else. (well, and TaskDefinitions in our case, but the Services are what is giving the issues here :D).
This method of redeployment we heavily use for our continues-delivery. A simple redeploy of a "service" stack fetches just enough information to bring online a new version. To apply good security practice, this IAM has as little rights as possible (if for some unlucky reason the secret keys are stolen, the harm is minimized to being able to redeploy other versions).

Now with this PR, that IAM user also needs to add/read SecurityGroups. That is something we are not willing to do (for the obvious reasons). Sadly, there is also not a way (from what I can tell) to revert to the original behaviour, or indicate in which stack these SecurityGroups should be generated. Also the step cannot be skipped to fix it myself later, nor can I find a way to remove the created SecurityGroups after-the-fact. So sadly I also haven't been able to work around this problem.

### Reproduction Steps

Create three stacks: ECS, ALB, and a TaskDefinition/Service Stack.
As by PR, the Service Stack now introduces the SecurityGroups, and there is no way to avoid it / change it to another stack. This means the IAM user deploying the Service Stack always also needs to be able to deploy a SecurityGroup.

### Error Log

IAM user deploying the stack has no rights to add/change SecurityGroups, and thus deployments fail.

### Environment

  - **CLI Version      :** 1.21.1
  - **Framework Version:** 1.21.1
  - **OS               :** n/a
  - **Language         :** n/a

### Other

For me, this is a regression.

As I am not sure my use-case is the weird one, or the author of the PR has the weird use-case, I am perfectly fine with a workaround for this. But as I failed to find one, I created this bug-report. Hopefully any of you can help me out here!

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
The PR was necessary to prevent situations that would be impossible to deploy. The change was focused on making all deployments work, not necessarily on restricting the permissions required to do said deployments. I'm sorry that broke your use case. 

It's going to be tricky to make this configurable in a sane way. We'll have to sit on that for a bit.

> nor can I find a way to remove the created SecurityGroups after-the-fact

In fact you can.  There is `alb.node.tryRemoveChild()` which will allow you to get rid of the Security Groups.

**Comment by TrueBrain** [comment]
> In fact you can. There is `alb.node.tryRemoveChild()` which will allow you to get rid of the Security Groups.

Ha, that was what I was looking for. Well, it turns out the SecurityGroupIngress/SecurityGroupEgress was not registered on the alb, but on the ec2Service. It was a bit looking around, but I found it:

```python
        service = Ec2Service(..)
        service.node.try_remove_child("SecurityGroup1")
        for security_group in cluster.connections.security_groups:
            service.connections.add_security_group(security_group)
```

This reverts it back to the 1.20 behaviour, and is exactly what I was looking for! Tnx for the pointers, and I hope you can think of a way to solve this in a more robust way :D
