### ISSUE TITLE
Add TriggeredFargateTask

### ISSUE THREAD

**Issue by agalazis** [aws/aws-cdk#5887]
TriggerredFargateTask that allows you to specify any event you want would be a better foundation .
SchecduledFargateTask could just extend TiggerredFargateTask to facilitate  the specific kind of trigger whch is via scehduled cloudwatch event

**Comment by PettitWesley** [comment]
@agalazis Curious what your use case is? What other sorts of events do you want to trigger the task on?

**Comment by agalazis** [comment]
Cloud watch events all sorts of. In my case it's a custom one I trigger through event bridge (putEvent) but it could be anything based on cloud watch event patterns you configure for the rule.

**Comment by agalazis** [comment]
The main issue is accepting the schedule config rather than the rule, which is limiting. In my TriggeredFargateClass I just accepts a rule (which at the end could be a schedule one).

**Comment by agalazis** [comment]
btw tasks that are triggered via event rule are still called scheduled in the console I renaming it to triggered I was just intending to highlight the need to trigger tasks based on event rules vs time schedule that is currently supported.

**Comment by pkandasamy91** [comment]
@agalazis, would you be interested in implementing the feature? I'd be more than happy to review your changes once it's ready
