### ISSUE TITLE
CodePipeline default artifact bucket has "blocked public access = off"

### ISSUE THREAD

**Issue by DmitryNefedov** [aws/aws-cdk#5900]
### The Question
When we do not specify artifact bucket for CodePipeline the default one gets created.
By default, Block Public Access is "Off", it's not a security vulnerability since only owner access created within bucket policy and KMS key is in use.
However, its against AWS guidelines
> AWS recommends that you turn on Block all public access

### Environment

  - **CDK CLI Version:** 1.21.1
  - **Module Version:** "@aws-cdk/aws-codepipeline": "1.21.1"
  - **OS:**  Windows 10 
  - **Language:**  TypeScript

**Comment by SomayaB** [comment]
Hi @DmitryNefedov, thanks for reporting this and putting in a PR, much appreciated! 👍
