### ISSUE TITLE
Default CodePipeline Bucket creates malformed KMS Key

### ISSUE THREAD

**Issue by WillBroadbentMSM** [aws/aws-cdk#5905]
When creating a CodePipeline in CDK the default Artifact bucket it creates does not have the correct permissions

The new key policy will not allow you to update the key policy in the future. (Service: AWSKMS; Status Code: 400; Error Code: MalformedPolicyDocumentException; Request ID: {some_id})

### Reproduction Steps

Pastebin: https://pastebin.com/0BxrJ5d2
pipeline = codepipeline.Pipeline(self, "SamPipeline",
            role=adf_code_pipeline_role,
            #artifact_bucket=artifact_bucket, <- Do not provide artifact bucket
            stages=[
                codepipeline.StageProps(stage_name="Source",
                    actions=[
                        codepipeline_actions.CodeCommitSourceAction(
                            action_name="CodeCommit_Source",
                            repository=source_repo,
                            output=source_output,
                            role=adf_code_commit_role,
                            trigger=codepipeline_actions.CodeCommitTrigger.NONE,
                        )        
                    ]

### Error Log

Cloudformation errors with the following:
The new key policy will not allow you to update the key policy in the future. (Service: AWSKMS; Status Code: 400; Error Code: MalformedPolicyDocumentException; Request ID: {some_id})

### Environment

  - **CLI Version      :1.21.1
  - **Framework Version:**
  - **OS               :MacOS
  - **Language         :Python

This is :bug: Bug Report

**Comment by skinny85** [comment]
Thanks for reporting @WillBroadbentMSM , but I was unable to reproduce your error.

Version `1.21.1`:

```
$ pip list
pip list
Package                             Version Location                                                                                                            
----------------------------------- ------- --------------------------------------------------------------------------------------------------------------------
attrs                               19.3.0  
aws-cdk.assets                      1.21.1  
aws-cdk.aws-apigateway              1.21.1  
aws-cdk.aws-applicationautoscaling  1.21.1  
aws-cdk.aws-autoscaling             1.21.1  
aws-cdk.aws-autoscaling-common      1.21.1  
aws-cdk.aws-autoscaling-hooktargets 1.21.1  
aws-cdk.aws-certificatemanager      1.21.1  
aws-cdk.aws-cloudformation          1.21.1  
aws-cdk.aws-cloudfront              1.21.1  
aws-cdk.aws-cloudwatch              1.21.1  
aws-cdk.aws-codebuild               1.21.1  
aws-cdk.aws-codecommit              1.21.1  
aws-cdk.aws-codedeploy              1.21.1  
aws-cdk.aws-codepipeline            1.21.1  
aws-cdk.aws-codepipeline-actions    1.21.1  
aws-cdk.aws-ec2                     1.21.1  
aws-cdk.aws-ecr                     1.21.1  
aws-cdk.aws-ecr-assets              1.21.1  
aws-cdk.aws-ecs                     1.21.1  
aws-cdk.aws-elasticloadbalancing    1.21.1  
aws-cdk.aws-elasticloadbalancingv2  1.21.1  
aws-cdk.aws-events                  1.21.1  
aws-cdk.aws-events-targets          1.21.1  
aws-cdk.aws-iam                     1.21.1  
aws-cdk.aws-kms                     1.21.1  
aws-cdk.aws-lambda                  1.21.1  
aws-cdk.aws-logs                    1.21.1  
aws-cdk.aws-route53                 1.21.1  
aws-cdk.aws-route53-targets         1.21.1  
aws-cdk.aws-s3                      1.21.1  
aws-cdk.aws-s3-assets               1.21.1  
aws-cdk.aws-sam                     1.21.1  
aws-cdk.aws-secretsmanager          1.21.1  
aws-cdk.aws-servicediscovery        1.21.1  
aws-cdk.aws-sns                     1.21.1  
aws-cdk.aws-sns-subscriptions       1.21.1  
aws-cdk.aws-sqs                     1.21.1  
aws-cdk.aws-ssm                     1.21.1  
aws-cdk.aws-stepfunctions           1.21.1  
aws-cdk.core                        1.21.1  
aws-cdk.cx-api                      1.21.1  
aws-cdk.region-info                 1.21.1  
cattrs                              1.0.0   
cdk-python-app                      0.0.1   /Users/adamruka/workplace/cdk/on-call/codepipeline-default-bucket-malformed-key-policy/cdk-python-app/cdk_python_app
jsii                                0.21.1  
pip                                 19.2.3  
publication                         0.0.3   
python-dateutil                     2.8.1   
setuptools                          41.2.0  
six                                 1.14.0  
typing-extensions                   3.7.4.1 
```

My code:

```python
from aws_cdk import (
    aws_codebuild as codebuild,
    aws_codepipeline as codepipeline,
    aws_codepipeline_actions as cpactions,
    core,
)


class CdkPythonAppStack(core.Stack):

    def __init__(self, scope: core.Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        source_output = codepipeline.Artifact()
        codepipeline.Pipeline(
            self, 'Pipeline',
            stages=[
                codepipeline.StageProps(
                    stage_name='Source',
                    actions=[
                        cpactions.GitHubSourceAction(
                            action_name='GitHub_Source',
                            owner='skinny85',
                            repo='test-code-build-deploy-spring-boot-project',
                            oauth_token=core.SecretValue.secrets_manager('my-github-token'),
                            output=source_output,
                        ),
                    ],
                ),
                codepipeline.StageProps(
                    stage_name='Build',
                    actions=[
                        cpactions.CodeBuildAction(
                            action_name='CodeBuild',
                            input=source_output,
                            project=codebuild.PipelineProject(
                                self, 'PipelineProject',
                                environment=codebuild.BuildEnvironment(
                                    build_image=codebuild.LinuxBuildImage.UBUNTU_14_04_OPEN_JDK_8,
                                ),
                            ),
                        ),
                    ],
                ),
            ],
        )
```

Everything deploys correctly. Here's a screenshot of the green pipeline: 
<img width="620" alt="python-pipeline" src="https://user-images.githubusercontent.com/460937/72935982-391f8600-3d1b-11ea-8d87-8d9fccda729c.png">

Can you show your code?

Thanks,
Adam

**Comment by SomayaB** [comment]
Closing this issue since there hasn't been a response in a while. Feel free to reopen.

**Comment by dpistole** [comment]
I encountered this error when the credentials I was using w/ `cdk deploy` didn't have the `kms:PutKeyPolicy` permission. It didn't manifest itself in the usual "not authorized to perform x" error, instead I got the error message about "The new key policy will not allow you to update the key policy in the future" (which lead me here).

Once I added the `kms:PutKeyPolicy` permission I got back to the comforting "not authorized to perform X" errors that I am used to.

**Comment by bryan-yu** [comment]
> I encountered this error when the credentials I was using w/ `cdk deploy` didn't have the `kms:PutKeyPolicy` permission. It didn't manifest itself in the usual "not authorized to perform x" error, instead I got the error message about "The new key policy will not allow you to update the key policy in the future" (which lead me here).
> 
> Once I added the `kms:PutKeyPolicy` permission I got back to the comforting "not authorized to perform X" errors that I am used to.

beautiful, thanks that helped

**Comment by Lock128** [comment]
I propose to re-open this @SomayaB and convert it to a feature request to enhance the error message as this one is REALLY hard to  understand.

**Comment by skinny85** [comment]
@Lock128 unfortunately, that error message is coming from the KMS service, so we can't really do anything about it in the CDK.

**Comment by Lock128** [comment]
Well @skinny85 - I understand that, but having a pre-check if the required permissions are available on the role being used to create the Codepipeline would be possible I assume, right?
And then rather fail on the CDK side during synth before the actual deployment, or is this not possible currently?

**Comment by skinny85** [comment]
@Lock128 unfortunately, the problem of whether a given User/Role has the permissions to correctly deploy a given CloudFormation Stack is _extremely_ difficult. It is not something we expect to solve in the CDK (it's a much more generic problem than the KMS permissions).

**Comment by Lock128** [comment]
Thanks for the answer, that makes sense!

Might be worth an epic to look into for the future direction of the CDK as it would improve developers experience... :-)

**Comment by skinny85** [comment]
Fair enough. Maybe an issue in the [CDK RFC repo](https://github.com/aws/aws-cdk-rfcs)...?
