### ISSUE TITLE
Adding logRetention property to a Lambda breaks the build of CDK scripts

### ISSUE THREAD

**Issue by audriusi** [aws/aws-cdk#5907]
If I take any CDK Lambda function and and update it by adding `logRetention: RetentionDays.ONE_WEEK` the initial deployment of the stack will work fine, but afterwards `npm run build` command will always fail while compiling the CDKLogRetention Lambda. 

### Reproduction Steps
1. Take any lambda and update it with setting logRetention property to any value.
2. Compile CDK stack `npm run build`
3. Run `cdk diff` command. 
4. Now run `npm run build` again. The build will fail with the error message specified below. This seems to be the issue in LogRetentionLambda added by CDK, because if I check the `cdk.out/asset.a21dfc0f418e70430bdd5c90de2445a8e6129603bfa18aa1944c0aa7510f847f` directory, it contains 2 files:

- index.js - which is the code for LogRetetentionLambda
- index.d.ts - which is the file that's causing the compilation issue

The contents of **index.d.ts** file is just a single line:
`export declare function handler(event: AWSLambda.CloudFormationCustomResourceEvent, context: AWSLambda.Context): Promise<void>;`

### Error Log
 tsc

cdk.out/asset.a21dfc0f418e70430bdd5c90de2445a8e6129603bfa18aa1944c0aa7510f847f/index.d.ts:1:40 - error TS2503: Cannot find namespace 'AWSLambda'.

1 export declare function handler(event: AWSLambda.CloudFormationCustomResourceEvent, context: AWSLambda.Context): Promise<void>;
                                         ~~~~~~~~~

cdk.out/asset.a21dfc0f418e70430bdd5c90de2445a8e6129603bfa18aa1944c0aa7510f847f/index.d.ts:1:94 - error TS2503: Cannot find namespace 'AWSLambda'.

1 export declare function handler(event: AWSLambda.CloudFormationCustomResourceEvent, context: AWSLambda.Context): Promise<void>;
                                                                                               ~~~~~~~~~

Found 2 errors.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! cdk@0.1.0 build: `tsc`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the cdk@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

### Environment

  - **CLI Version      : 1.20.0**
  - **Framework Version:**
  - **OS               : Ubuntu 18.04 LTS**
  - **Language         : TypeScript**

--- 

This is :bug: Bug Report

**Comment by jogold** [comment]
You should exclude `cdk.out` in your `tsconfig.json`.

See (recommended) [`tsconfig.json`](https://github.com/aws/aws-cdk/blob/v1.21.1/packages/aws-cdk/lib/init-templates/app/typescript/tsconfig.json) in TS init template:
https://github.com/aws/aws-cdk/blob/842cc5fa16248fa458753a19f9f6541f7270e0f9/packages/aws-cdk/lib/init-templates/app/typescript/tsconfig.json#L21-L23

**Comment by audriusi** [comment]
You're right, excluding solves the issue. Thank you.
