### ISSUE TITLE
AWS::Events::Rule InputTransformer adds extra quotes to string messages

### ISSUE THREAD

**Issue by IsmaelMartinez** [aws/aws-cdk#5924]
When creating adding extra quotes to the messages.

For a message like 'This is an error message' it generates a cdk.out with the following InputTemplate   "InputTemplate": "\"This is an error message\""

The following test shows the issue is there.
https://github.com/aws/aws-cdk/blob/0f0e2055cab08551bc6e5dfb8a1b6219368263c5/packages/%40aws-cdk/aws-events/test/test.rule.ts#L222

### Reproduction Steps
Code to reproduce the error. You just need to check the cloudformation output.
```
const failureTopicMessage = 'This is an error message'

const topic = new Topic(this, 'MyTopic', {
      topicName: 'myTopicName',
});

const schedulerRule = new Rule(this, 'MonitorSchedulerECS', {
        eventPattern: {
          source: ['aws.ecs'],
          detailType: ['ECS Task State Change'],
          detail: {
            containers: {
              exitCode: [1],
            },
            lastStatus: ['STOPPED'],
          },
        },
        targets: [new SnsTopic(topic, {
          message: RuleTargetInput.fromMultilineText(failureTopicMessage),
        })],
      });
```

### Error Log
Messages, specially sending SNS Emails, look pretty odd as they add an extra quotes to each line

### Environment

  - **CLI Version      : *1.21.1*
  - **Framework Version: *1.21.1*
  - **OS               : *Linux*
  - **Language         : *Typescript*

### Other

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
This is true, and I believe there is nothing to be done about this.

If you can provide us a CloudFormation template that contains a multiline string without the quotes, we can update our behavior to match, but I believe this is a limitation of AWS Events.

**Comment by IsmaelMartinez** [comment]
Yeah, confirmed that it is a CloudFormation "feature" or "requirement". A bit odd but I will do with it. Thanks and apologies for the noise.
