### ISSUE TITLE
NLB: Can't make a private NLB

### ISSUE THREAD

**Issue by rix0rrr** [aws/aws-cdk#5928]
Bug report extracted from https://github.com/aws/aws-cdk/issues/4319.

It is not possible to make a non-public NLB. See the linked issue for details.

--- 

This is :bug: Bug Report

**Comment by RenkeMeuwese** [comment]
In https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-elasticloadbalancingv2/test/nlb/test.load-balancer.ts there seems to be a test of this though, and we don't seem to be able to reproduce the error as indicated in this issue. So is the problem actually that https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs-patterns.NetworkLoadBalancedFargateService.html itself doesn't function as expected, and the problem does not lie in the NLB itself?
