### ISSUE TITLE
[Step Functions] Run ECS Task with dynamic Task Definition

### ISSUE THREAD

**Issue by skorfmann** [aws/aws-cdk#5931]
### The Question

I'm wondering why this can't be an `ITaskDefinition`, since I'd like to dynamically pull the task definition from the input. According to the Step Functions UI it's possible to do so

https://github.com/aws/aws-cdk/blob/0f0e2055cab08551bc6e5dfb8a1b6219368263c5/packages/%40aws-cdk/aws-stepfunctions-tasks/lib/run-ecs-task-base.ts#L18-L24

![Screenshot 2020-01-23 at 14 49 47](https://user-images.githubusercontent.com/136789/72991037-79e9ce80-3df1-11ea-8b8d-3320a76aa76b.png)

### Environment

  - **CDK CLI Version:** `1.21.1 (build 842cc5f)`
  - **Module Version:**  `@aws-cdk/aws-stepfunctions-tasks": "1.19.0`
  - **OS:**  `OSX Catalina`
  - **Language:** `TypeScript`

**Comment by nija-at** [comment]
Hello @skorfmann -

I've re-classified this as a feature request.

Can you explain how changing this to `ITaskDefinition` would enable to you to pull the task definition from the input?

Thanks.

**Comment by SomayaB** [comment]
Closing for now since there hasn't been a response in a while. Feel free to reopen.
