### ISSUE TITLE
Option to not add a role to a construct

### ISSUE THREAD

**Issue by claabs** [aws/aws-cdk#5941]
The option to decline creating a role on a construct that consumes or creates one.

### Use Case

Most constructs with a `role` property accept `iam.IRole | undefined`, where you can either pass in a role (IRole), or have it create one automatically (undefined). There is a potential third desired outcome, which is don't attach a role to the resource at all. 

Some resources display a different behavior, like a [CodePipeline Action Declaration](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codepipeline-pipeline-stages-actions.html). In this case it assumes the pipeline's role. You'd think that just giving it the same role as the pipeline would resolve this, but depending on the role's permissions, you can get `<PipelineRole> is not authorized to perform AssumeRole on role <PipelineRole>`. 

In this case, just removing the `RoleArn` property from the CloudFormation template would resolve the error, but that isn't possible through CDK.

### Proposed Solution

A third option for all appropriate `role` properties, such as accepting `null` as a third option, or some sort of `NullRole()` implementation of `IRole`.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by vandreykiv** [comment]
Any updates on this issue? In our case we have around 150 pipelines right now and they created like 1500 IAM roles (around 10 per pipeline) that is quite big amount. Maybe we have some workaround to reduce this number?

**Comment by arshadmohd** [comment]
Any update on this issue? Or any workaround for now, if I m trying to use a pre-created role?
