### ISSUE TITLE
Expose the overrideArtifactName property on S3ArtifactsProps

### ISSUE THREAD

**Issue by alexnikolis** [aws/aws-cdk#5955]
Add the `overrideArtifactName` property to the `S3ArtifactsProps` interface.

### Use Case
The `overrideArtifactName` property enables dynamically naming artifacts from the project's buildspec.
- https://docs.aws.amazon.com/codebuild/latest/APIReference/API_ProjectArtifacts.html#CodeBuild-Type-ProjectArtifacts-overrideArtifactName
- https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html#build-spec-ref-syntax

### Proposed Solution
Include `overrideArtifactName` in the `S3ArtifactsProps` interface and include it in the compiled CloudFormation template.

### Other
N/A

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by skinny85** [comment]
Thanks for opening the issue @alexnikolis . Would you be interested in contributing this feature?

**Comment by shearn89** [comment]
I'm having a quick stab at this as I've just hit the bug and would like the functionality. Hope to raise a PR soon.

**Comment by shearn89** [comment]
Having trouble building and running my unit tests, probably because I'm on windows at the minute. I have a branch in my fork, just need to test it before raising a PR to make sure I've added a test in the right place!
