### ISSUE TITLE
CLI Enhancements in service of better customer communication

### ISSUE THREAD

**Issue by iliapolo** [aws/aws-cdk#5956]
## :question: General Issue

Lets add some CLI capabilities that will improve information exchange between us and our customers.

### Issues Warning

The main idea of this feature is to provide a mechanism that exposes customers to severe issues that might exist in the version they are using. We don't want users using bad versions.

Ideally, severe issues (regressions/p0) would be printed during the upgrade process. I know its fairly easy doing this with python, but I don't think its possible to control this with languages like Java and CSharp.

If you have any ideas on how to achieve that, it would be great.

In the meanwhile, we can add a `cdk issues` command that fetches issues that were detected after the release (from GitHub) and prints them in a nice and scary redish font.

### Version

Our `cdk version` command should print library versions in addition to the CLI version.

### Environment

Lets add a command that helps customers report bugs. We could very easily detect all the necessary environment we require when reporting bugs.

Maybe something like `cdk env`.

### Environment

  - **CDK CLI Version:** ALL 
  - **Module Version:** ALL 
  - **OS:** ALL 
  - **Language:** ALL

**Comment by rix0rrr** [comment]
The diagnostics command exists. It's called `cdk doctor`, but it's quite anemic atm so we haven't really trained users to use it.

We should build it out into a reliable tool so we can start recommending it to users, so they will over time get trained into running it.

**Comment by rix0rrr** [comment]
By the way, we should still decide if we need to be able to push communication to customers (instead of them pulling it).

I'm also not sure if it's worth keeping issues #5957 and #5958 open if all they're going to be doing is just pointing to this issue. Those other 2 aren't really actionable I feel. Let's close them?

**Comment by iliapolo** [comment]
@rix0rrr Maybe the phrasing in those two issues was confusing, but I didn't mean to have them simply link to this one. I think they are actionable on their own merit. 

They simply describe the manual processes that we can already be doing, just by deciding to do them. Going forward, some of them might become redundant or automated, depending on what features we put in the CLI as part of this issue.
