### ISSUE TITLE
Communicating regressions to customers

### ISSUE THREAD

**Issue by iliapolo** [aws/aws-cdk#5957]
## :question: General Issue

We should probably create some kind of process that notifies our users when we detect regressions. 

Here is what I had in mind:

1. Create a GitHub issue.
2. Suggest workarounds in the issue (maybe not right away).
3. Gitter Notification.
4. Comment in the relevant GitHub tracking issues.

We can start doing all of these immediately, however, they still don't guarantee users will actually see it. To improve on this, we should also [discuss](https://github.com/aws/aws-cdk/issues/5956) how can we use the CLI itself to help. 

### Environment

  - **CDK CLI Version:** ALL 
  - **Module Version:** ALL 
  - **OS:** ALL 
  - **Language:** ALL

**Comment by iliapolo** [comment]
@NGL321 Im assigning this to you. Its basically the issue mitigation protocol we discussed.

**Comment by NGL321** [comment]
This slipped through the cracks. Closing as it was resolved by the issue-mitigation protocol document
