### ISSUE TITLE
Communicating Upgrade Procedures To Customers

### ISSUE THREAD

**Issue by iliapolo** [aws/aws-cdk#5959]
## :question: General Issue

Upgrading CDK installations is not a trivial process. This is because there are two parts of the tool:

- Command Line Tool (`cdk`)
- Libraries (Aka Framework) (`@aws-cdk/`)

We strive to always provide new features / bug fixes by requiring an upgrade only to the libraries, using the standard package managers.

However, a change may require an upgrade to either the CLI, the Framework, or Both.

We currently have a [mechanism](https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/cx-api/lib/versioning.ts) that tells customers to upgrade the CLI version in case the framework version they upgraded to, is not compatible with their existing CLI version. While this is good, it doesn't solve some confusion that might occur.

### Example

Adding support for custom docker files, required an upgrade to both the CLI and the framework. In addition, the change was fully backwards compatible. If a customer were to only upgrade the framework, the feature wouldn't have worked, nor would the customer have gotten a message instructing to upgrade (which is ok).

I think it would be nice if every change that requires a non-trivial upgrade process (i.e simply upgrading the framework) were to somehow document the required process.

Ideally, this would somehow appear in the release notes, next to the relevant bullet. 

### Environment

  - **CDK CLI Version:** ALL 
  - **Module Version:** ALL 
  - **OS:** ALL 
  - **Language:** ALL

**Comment by rix0rrr** [comment]
> If a customer were to only upgrade the framework, the feature wouldn't have worked, nor would the customer have gotten a message instructing to upgrade

We control this by means of the CX version, which WILL tell the user to upgrade.

We can write a GitHub action that requires any change that touches the CX version to also include a note in either the change title (`(requires CLI 1.2.3)`) or in a `BREAKING CHANGE` block

**Comment by iliapolo** [comment]
This was addressed by the introduction of [@aws-cdk/cloud-assembly-schema](https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/cloud-assembly-schema)
