### ISSUE TITLE
CLI vs Framework Compatibility

### ISSUE THREAD

**Issue by iliapolo** [aws/aws-cdk#5961]
## :question: General Issue

Ideally, every CLI version would be compatible with every framework version, and vice versa. This of course is not always possible, however, our state of mind should be to *maintain compatibility **unless** there is a good reason not to.*

Lets break down the various possibilities:

### New CLI

Currently, we provide a compatibility promise regarding CLI versions. That is, new CLI should always be compatible with older frameworks.

However, we don't actually have a mechanism that enforces this. 

What we do have, is [test-backwards-compat.sh](https://github.com/aws/aws-cdk/blob/master/packages/aws-cdk/test/integ/cli/test-backwards-compat.sh). This test invokes `cdk synth` on cloud-assemblies that were created with older (specific) framework versions.

The problem is that its not enough. Many issues may arise either during `cdk deploy`, or by using (other) very specific cloud-assemblies.

I'd like us to come up with a generic way of running compatibility tests without cherry-picking specific assemblies and use-cases.

#### Suggestion

What if we run **old** integration tests, using the **new** CLI, but with an **old** framework?

This should guarantee that the new CLI supports all current functionality, without relying on a new framework.

### New Framework

We don't have a compatibility promise on framework versions. That is, its ok for the framework to require a newer version of the CLI to work. However, it would be nice to minimize those occurrences. 

In accordance to the state of mind I mentioned before:

#### Suggestion

Run **old** integration tests, using an **old** CLI version, but with a **new** framework version.

I think that having this suite, can prevent us from pushing incompatible changes unless it's absolutely necessary, or at least, intentional.

Things to consider:

- Sometimes, we will have to push incompatible changes to the framework. This means we need to be able to somehow flag that specific version are not compatible, so that this suite can ignore it. This is actually not so bad, because it forces us to document those incompatibilities and also provide a justification.

### Environment

  - **CDK CLI Version:** ALL 
  - **Module Version:** ALL 
  - **OS:** ALL 
  - **Language:** ALL

**Comment by rix0rrr** [comment]
I see a problem with this ticket and the previous one: we have to settle on what our "integration tests" are and what they do.

We have 2 different sets of integration tests, CLI and per-framework-library, and the second one can't properly be called integration test. So we need to define those first.

**Comment by iliapolo** [comment]
Closing this issue in favor of [RFC: Compatibility Assurance Strategy](https://github.com/aws/aws-cdk-rfcs/pull/111)
