### ISSUE TITLE
aws-s3.BucketAccessControl has invalid values for S3DeployAction

### ISSUE THREAD

**Issue by mbonig** [aws/aws-cdk#5963]
The S3DeployActionProps.accessControl is an enum of s3.BucketAccessControl. Current (1.22) values are things like 'PublicRead'. However, when using this deploy action it will fail with the error:

```
Invalid canned ACL: PublicRead. For a list of valid options, see https://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html#canned-acl
```

And as the url points out, it's expecting values like 'public-read' and not 'PublicRead'.

### Reproduction Steps

```

        const s3DeployAction = new S3DeployAction({
            actionName: 'copy-files',
            bucket: this.websiteBucket!,
            input: compiledSite,
            runOrder: 1,
            accessControl: BucketAccessControl.PUBLIC_READ
        });
```

### Environment

  - **CLI Version      :**  1.22
  - **Framework Version:** 1.22
  - **OS               :** Deepin 15.11
  - **Language         :** Typescript

### Other

--- 

This is :bug: Bug Report

**Comment by netroy** [comment]
I've been using camel-cased CannedACLs & haven't seen this issue so far.
But, I tried changing the values to "kebab-case", in a Cloudformation yaml file & a test CDK app, & didn't face any issues.

Checking the console UI for creating pipeline stages, & after reading the docs, it looks like "kebab-case" is the expected format.
Even though I can't reproduce this error, I'd highly recommend changing the `BucketAccessControl` enum to reflect values as expected by AWS.

**Comment by SomayaB** [comment]
Hi @mbonig, thanks for reporting this. And thanks @netroy for opening a PR, much appreciated! 👍
