### ISSUE TITLE
awslint should require justification for exclusions

### ISSUE THREAD

**Issue by iliapolo** [aws/aws-cdk#5965]
Have `awslint` require justification when adding exclusions.

### Use Case

Currently, when we add exclusions to `awslint` for a specific project, it looks like this:

```json
  "awslint": {
    "exclude": [
      "construct-ctor-props-optional:@aws-cdk/custom-resources.AwsCustomResource",
    ]
  }
```

Unless we provide inline code comments that explain these exclusions, its rather difficult to understand why they were added. 

### Proposed Solution

We would like the exclusions section to look something like this:

```json
  "awslint": {
    "exclude": [
      {
        "type": "construct-ctor-props-optional",
        "location": "@aws-cdk/custom-resources.AwsCustomResource",
        "justification": "props cannot be made optional because it requires at least one of onCreate/onUpdate/onDelete"
      }
    ]
  }
```

This has the benefits of:

- Easily understand why exclusions were introduced.
- Make it harder to introduce exclusions because we would have to rationalize the justification :)

### Other

* [X] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by richardhboyd** [comment]
additionally, the `CONTRIBUTING.md` should contain information on how to address awslint failures and how to supply overrides.
