### ISSUE TITLE
Make it easier to configure RestApi policy

### ISSUE THREAD

**Issue by nija-at** [aws/aws-cdk#5975]
Currently, the policy for `RestApi` is [an `iam.PolicyDocument`](https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-apigateway/lib/restapi.ts#L86).

This policy document needs a reference to the ARN of the RestApi (self-reference) that is still being constructed. The solution for this [comes from CloudFormation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-restapi.html#cfn-apigateway-restapi-policy) to use the `Fn::Join` instrinsic with special values for the delimiter.

Make this first class in the CDK so customers can get this for free. 

---

This is a :rocket: Feature Request

**Comment by marcogrcr** [comment]
I'm not sure I understand this feature request. What's wrong with:

```ts
new RestApi(this, "Api", {
  // ...
  policy: new PolicyDocument({
  statements: [
    new PolicyStatement({
      actions: ["execute-api:Invoke"],
      resources: ["execute-api:/{stage}/{method}/{path}"], // or "*"
      principals: [new AccountPrincipal("...")]
    })
  ]
});
```

The fact that you have to know the special `execute-api:/*` syntax?
