### ISSUE TITLE
AppSync L2: support for read consistency

### ISSUE THREAD

**Issue by duarten** [aws/aws-cdk#5980]
Allow specifying the `consistentRead` toggle in the `GetItem`, `ScanTable`, and `Query` mapping templates.

### Use Case

To control the amount of replicas contacted during DynamoDB reads.

### Proposed Solution

Add an enum parameter to the `dynamoDbGetItem`, `dynamoDbScanTable` and `dynamoDbQuery` methods.

Depends on #5861.

### Other

* [X] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by YichenQian09** [comment]
Can we add a boolean parameter to the dynamoDbGetItem, dynamoDbScanTable and dynamoDbQuery methods?
