### ISSUE TITLE
CLI: cdk context --clear clears feature flags

### ISSUE THREAD

**Issue by Jerry-AWS** [aws/aws-cdk#5981]
Feature flags are stored as context values. `cdk context --clear` clears them along with all other context values. This can change the behavior of the user's app with no warning and no obvious way to restore the behavior, since the user might not even be aware that a feature flag was set on their project.

I'd expect CLI to either recognize known feature flags and retain them when context is cleared, or else store them somewhere besides context where they won't be cleared.

### Environment

  - **CLI Version      :** 1.22.0
  - **Framework Version:** 1.22.0
  - **OS               :** Windows
  - **Language         :** All

--- 

This is :bug: Bug Report

**Comment by shivlaks** [comment]
@Jerry-AWS - thanks for reporting! I think that's a good point and something we should account for. Would you still expect `cdk context` to display feature flags at all? We're thinking of moving them to `cdk doctor` #5627

We also have a story to stop transferring flags to `cdk.context.json #5834

Feel free to add anything you can think of to these related issues!

**Comment by Jerry-AWS** [comment]
@shivlaks If I were designing feature flags from scratch, I'd store them in a separate structure (under e.g. a `"feature-flags"` key in `cdk.json`) or even a separate file. They seem a fundamentally different thing from context values.

Using context values does let you apply feature flags programmatically, and even to different parts of your construct tree. But that seems like it could be a good way to write confusing code, and maybe not something that should be encouraged or supported in the first place.

**Comment by shivlaks** [comment]
With the closure of #5834, we don't automatically move any context established in `cdk.json` into `cdk.context.json`

Since the context that's set in `cdk.json` is readonly, the CLI will not clear or remove it. 
let me know if that works for you @Jerry-AWS

**Comment by Jerry-AWS** [comment]
This issue has been addressed (and documented in the CDK Guide).

https://docs.aws.amazon.com/cdk/latest/guide/context.html
https://docs.aws.amazon.com/cdk/latest/guide/featureflags.html
