### ISSUE TITLE
A newer version of the CDK CLI (>= 1.21.0) is necessary to interact with this app

### ISSUE THREAD

**Issue by iliapolo** [aws/aws-cdk#5986]
Initializing an app using cdk `1.21.0` and trying to `synth` it results in an error.

```console
A newer version of the CDK CLI (>= 1.21.0) is necessary to interact with this app
```

### Workaround 

A workaround is to install `1.22.0` (or latest) version of the CLI.

```console
npm install -g aws-cdk@1.22.0
```

see https://github.com/aws/aws-cdk/issues/5986#issuecomment-578959404

### Reproduction Steps

```console
npm install -g aws-cdk@1.21.0
cdk init --language typescript
cdk synth
```

### Error Log

```text
A newer version of the CDK CLI (>= 1.21.0) is necessary to interact with this app
```

### Environment

  - **CLI Version      :** 1.21.0
  - **Framework Version:** NA
  - **OS               :** MacOS
  - **Language         :** Typescript

### Other

```console
❯ cdk --version                                                                                                                                                       [23:07:16]
1.21.0 (build bf6ab14)
```

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment]
Actually, this will happen in all versions except for the latest (1.22.0 at the time of writing). This is because we still use a [caret dependency](https://github.com/aws/aws-cdk/blob/master/packages/aws-cdk/lib/init-templates/app/typescript/package.template.json#L24) for `@aws-cdk/core` in our templates. Combine this with a [protocol change](https://github.com/aws/aws-cdk/pull/5733) that version `1.22.0` introduced, and we get this error.

**Comment by iliapolo** [comment]
The error message itself is misleading, and is actually a bug in and of itself. It instructs the user to install `>= 1.21.0`, which is what is installed (`1.21.0`)

Installing version `1.22.0` will resolve this problem.

**Comment by w601sxs** [comment]
Doing `npm install -g aws-cdk@1.22.0` as suggested

gives ..
```bash
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code EEXIST
npm ERR! syscall symlink
npm ERR! path ../lib/node_modules/aws-cdk/bin/cdk
npm ERR! dest /home/ubuntu/.nvm/versions/node/v10.18.0/bin/cdk
npm ERR! errno -17
npm ERR! EEXIST: file already exists, symlink '../lib/node_modules/aws-cdk/bin/cdk' -> '/home/ubuntu/.nvm/versions/node/v10.18.0/bin/cdk'
npm ERR! File exists: /home/ubuntu/.nvm/versions/node/v10.18.0/bin/cdk
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2020-02-18T14_34_29_253Z-debug.log
```

Doing `npm install -g --force aws-cdk@1.22.0` as suggested in the error message, and then doing `cdk --version` gives 1.22 [succeeds]

```bash
npm WARN using --force I sure hope you know what you are doing.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
/home/ubuntu/.nvm/versions/node/v10.18.0/bin/cdk -> /home/ubuntu/.nvm/versions/node/v10.18.0/lib/node_modules/aws-cdk/bin/cdk

core-js-pure@3.6.4 postinstall /home/ubuntu/.nvm/versions/node/v10.18.0/lib/node_modules/aws-cdk/node_modules/core-js-pure

node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
https://opencollective.com/core-js 
https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)```
