### ISSUE TITLE
Cryptic error message when stack tags use late-bound values

### ISSUE THREAD

**Issue by moatazelmasry2** [aws/aws-cdk#5992]
When trying to add tags to a stack, I'm receiving the following error:
❌  MyStack failed: InvalidParameterType: Expected params.Tags[0].Value to be a string

### Reproduction Steps

Here is how I'm adding tags:
```
const stack = new AccountSetupStack(app, 'AccountSetupStack', {
    "description": "Account setup"
});
stack.tags.setTag("StackName", cdk.Aws.STACK_NAME, 0, true)
```

Adding tags directly to the stack also produces the same error: 
```
const stack = new AccountSetupStack(app, 'AccountSetupStack', {
    "description": "Account setup",
    "tags": {
        "StackName": cdk.Aws.STACK_NAME
    }
});
stack.tags.setTag("StackName", cdk.Aws.STACK_NAME, 0, true)

```

### Environment

  - **CLI Version      : 1.22.0 (build 309ac1b)
  - **Language         : Typescript

--- 

This is :bug: Bug Report

**Comment by eladb** [comment]
CloudFormation stack tags are applied upon stack creation and not during deployment and therefore they cannot use pseudo parameters like `Aws.STACK_NAME`. 

You can use `stack.stackName` instead, which is early-bound:

```ts
stack.tags.setTag('StackName', stack.stackName);
```

We should add a validation that will emit a more informative error.

**Comment by moatazelmasry2** [comment]
Thanks for explanation. I'm truly learning a lot here.

**Comment by moatazelmasry2** [comment]
I'd say @eladb  answer resolves the issue. Thanks!!!
