### ISSUE TITLE
How to capture the LamdaRestAPI URL details after deployment

### ISSUE THREAD

**Issue by rampatina** [aws/aws-cdk#5993]
### The Question
We have a lambda and which is backed by LamdaRestAPI for endpoints. Deployment was success and I was trying to capture the URL of the LamdaRestAPI after deployment.
Getting below URL with tokenized:

`https://${Token[TOKEN.139]}.execute-api.us-east-1.${Token[AWS::URLSuffix.19]}/${Token[TOKEN.145]}/`

As well I tried with `cdk.CfnOutput` still returning same thing. Am I  missing something? Please help me with this

### Environment

  - **CDK CLI Version:** 
  - **Module Version:** 
  - **OS:** 
  - **Language:**

**Comment by richardhboyd** [comment]
That should not happen. You should see the fully realized url if you are using CfnOutput. Are you trying to `console.log()` the output?

**Comment by nija-at** [comment]
@rhboyd is correct! Can you share the code or code snippet on how you're doing this?
