### ISSUE TITLE
RDS DB identifiers have obscure names

### ISSUE THREAD

**Issue by itajaja** [aws/aws-cdk#6000]
some resources get pretty ARNs (that is, they are prefixed with the id, so it's easy to look for them), while some others don't: RDS databases and EKS clusters are the ones I can't find. here is how my databases and clusters look:

![image](https://user-images.githubusercontent.com/697647/73287067-a2dddb00-41c6-11ea-8d96-337ff166dd89.png)

![image](https://user-images.githubusercontent.com/697647/73287120-ba1cc880-41c6-11ea-82cb-a7ceca903a46.png)

this means that looking up resources is quite painful. compare it to other resources buckets where the arn is something like `{LOGICAL_ID}-{random_number}`. I don't want to set resource names in my definitions, as that leads to problems. is there a way to avoid this?

**Comment by eladb** [comment]
I believe EKS clusters should now have a nicer name that includes some form of the logical ID ([ref](https://github.com/aws/aws-cdk/blob/d681d964b91048eaf2044a27c8c70c05b2b9e2bc/packages/%40aws-cdk/aws-eks/lib/cluster-resource-handler/cluster.ts#L190)).

As for RDS databases, that's definitely something we can consider.

**Comment by jogold** [comment]
For RDS the CDK default is to let CloudFormation generate an instance identifier (see `instanceIdentifier` prop). This is a good default because setting an [instance identifier](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html#cfn-rds-dbinstance-dbinstanceidentifier) has CF implications:
> ⚠️ **Important**
If you specify a name, you cannot perform updates that require replacement of this resource. You can perform updates that require no or some interruption. If you must replace the resource, specify a new name.

**Comment by jogold** [comment]
You can rely on the `aws:cloudformation:xxx` tags (`aws:cloudformation:logical-id`, `aws:cloudformation:stack-id`, `aws:cloudformation:stack-name`) when filtering in the console.

**Comment by itajaja** [comment]
> For RDS the CDK default is to let CloudFormation generate an instance identifier (see `instanceIdentifier` prop). This is a good default because setting an [instance identifier](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html#cfn-rds-dbinstance-dbinstanceidentifier) has CF implications.

yes, I am aware of that. but the name can still partly contain the resource id. eg, when I create a bucket with id `foobar` the resulting bucket will be `foobar-<random_hash>`

**Comment by nija-at** [comment]
@itajaja - to reiterate @jogold's comment, any attempt to control the name of the database instance from by the CDK would result in a state where CloudFormation cannot execute updates when its properties are modified. 

However, if you are ok with this limitation, you can generate your own prefix-based naming scheme and specify them against the [`databaseName` property](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-rds.DatabaseInstance.html#databasename-span-class-api-icon-api-icon-experimental-title-this-api-element-is-experimental-it-may-change-without-notice-span).

**Comment by itajaja** [comment]
> @itajaja - to reiterate @jogold's comment, any attempt to control the name of the database instance from by the CDK would result in a state where CloudFormation cannot execute updates when its properties are modified.

so you are saying that this is an issue on cloudformation end rather than CDK? if that's the case, why then was the [problem solved](https://github.com/aws/aws-cdk/blob/d681d964b91048eaf2044a27c8c70c05b2b9e2bc/packages/%40aws-cdk/aws-eks/lib/cluster-resource-handler/cluster.ts#L190) on CDK's side for EKS clusters? Isn't that applicable to RDS too? Is it because EKS is actually a custom resource and not a cloudformation construct?

**Comment by nija-at** [comment]
> Is it because EKS is actually a custom resource and not a cloudformation construct?

@itajaja - yes, that's accurate.
