### ISSUE TITLE
inconsistent property name, provisionedExecutions vs provisionedConcurrentExecutions

### ISSUE THREAD

**Issue by sblackstone** [aws/aws-cdk#6003]
In aws-lambda, the Function class's addVersion method uses the property name "provisionedExecutions"

In the Version class or the Alias class the name is provisionedConcurrentExecutions...

**Comment by nija-at** [comment]
Thanks for filing this issue. 

Can you let us know if you find this just inconsistent, or confusing; and if confusing, why?

Unfortunately, there isn't much we can do about this now. And it probably isn't worth deprecating this property and adding a new one, unless it impacts usability seriously.

**Comment by sblackstone** [comment]
I just found it confusing / annoying, thats all - I copied the property from and Alias config I had in the same block of code while testing something and noticed it didn't work.

I wasn't sure if you guys were stable on this API so I figured I'd mention it..

Thanks
