### ISSUE TITLE
CoreDNS pods not starting automatically after eks.FargateCluster deployment

### ISSUE THREAD

**Issue by AndrzejKomarnicki** [aws/aws-cdk#6005]
**Issue:**
CoreDNS deployment fails to scale the 3 pods automatically to running status after deploying with the FargateCluster construct.
```console
**Andrzejs-MacBook-Pro:awscdk-eks-fargate-cluster anti9to5$ kubectl get pods -n kube-system**
NAME                       READY   STATUS    RESTARTS   AGE
coredns-56678dcf76-nhkzq   0/1     Pending   0          73m
coredns-7dc94799cb-b2ph6   0/1     Pending   0          70m
coredns-7dc94799cb-h7srw   0/1     Pending   0          70m
**Andrzejs-MacBook-Pro:awscdk-eks-fargate-cluster anti9to5$ kubectl describe deployment coredns --namespace kube-system**
Name:                   coredns
Namespace:              kube-system
CreationTimestamp:      Tue, 28 Jan 2020 11:13:28 -0500
Labels:                 eks.amazonaws.com/component=coredns
                        k8s-app=kube-dns
                        kubernetes.io/name=CoreDNS
Annotations:            deployment.kubernetes.io/revision: 2
                        kubectl.kubernetes.io/last-applied-configuration:
                          {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"eks.amazonaws.com/component":"coredns","k8s-app":"kube...
Selector:               eks.amazonaws.com/component=coredns,k8s-app=kube-dns
Replicas:               2 desired | 2 updated | 3 total | 0 available | 3 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  1 max unavailable, 25% max surge
Pod Template:
  Labels:           eks.amazonaws.com/component=coredns
                    k8s-app=kube-dns
  Annotations:      eks.amazonaws.com/compute-type: fargate
  Service Account:  coredns
  Containers:
   coredns:
    Image:       602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/coredns:v1.6.6
    Ports:       53/UDP, 53/TCP, 9153/TCP
    Host Ports:  0/UDP, 0/TCP, 0/TCP
    Args:
      -conf
      /etc/coredns/Corefile
    Limits:
      memory:  170Mi
    Requests:
      cpu:        100m
      memory:     70Mi
    Liveness:     http-get http://:8080/health delay=60s timeout=5s period=10s #success=1 #failure=5
    Readiness:    http-get http://:8080/health delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /etc/coredns from config-volume (ro)
      /tmp from tmp (rw)
  Volumes:
   tmp:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
   config-volume:
    Type:               ConfigMap (a volume populated by a ConfigMap)
    Name:               coredns
    Optional:           false
  Priority Class Name:  system-cluster-critical
Conditions:
  Type           Status  Reason

  Available      False   MinimumReplicasUnavailable
  Progressing    False   ProgressDeadlineExceeded
OldReplicaSets:  coredns-56678dcf76 (1/1 replicas created)
NewReplicaSet:   coredns-7dc94799cb (2/2 replicas created)
Events:          <none>
```
**Workaround** 
`kubectl scale -n kube-system deployment/coredns --replicas=0`
`kubectl scale -n kube-system deployment/coredns --replicas=3`

**Comment by pahud** [comment]
same here with cdk 1.23.0

I noticed the annotation patch on `deployment/coredns` has been applied

<img width="1138" alt="圖片" src="https://user-images.githubusercontent.com/278432/74045785-55544000-4a08-11ea-82df-bd728937a2c1.png">

And the deployment was trying to create new replicaset to replace the old one

<img width="895" alt="圖片" src="https://user-images.githubusercontent.com/278432/74045846-76b52c00-4a08-11ea-9f1f-a612701c199b.png">

And all the pods are `Pending`

<img width="770" alt="圖片" src="https://user-images.githubusercontent.com/278432/74045987-b0863280-4a08-11ea-9760-4a41a775ff8f.png">

However, according to this
https://docs.aws.amazon.com/eks/latest/userguide/fargate-getting-started.html#fargate-gs-next-steps

If I run `kubectl rollout restart -n kube-system deployment coredns`, all the coredns pods are running.

<img width="807" alt="圖片" src="https://user-images.githubusercontent.com/278432/74046184-12df3300-4a09-11ea-9496-5e7abba6eac3.png">

I am not sure if this is a bug but the `kubectl rollout restart` does work.

**Comment by eladb** [comment]
@pahud  is this still an issue in >= 1.46.0

**Comment by eladb** [comment]
Closing in the meantime, please open if relevent.

**Comment by mrajancsr** [comment]
Hello I'm using fargate to deploy my apps.  I also have an Aws elastic cache redis.  My fargate profile has the same subnet as redis.  Same security group.  Same vpc as well.  I'm having a coredns issue in my fargate cluster as I try to connect to redis.  What is the solution for this?
