### ISSUE TITLE
VPC: VPN route propagation shouldn't try to use PRIVATE subnets if they don't exist

### ISSUE THREAD

**Issue by aztecrex** [aws/aws-cdk#6008]
The VPC component in @aws-cdk/aws-ec2 does not allow for a configuration that includes
a VPN but excludes a NAT

This is our most common scenario when using VPNs in AWS. It is necessary because all traffic, including traffic to public Internet, is required to be routed through the VPN for monitoring and threat mitigation.

To fix this, CDK needs to enable creation of VPN Gateway for ISOLATED subnets --or-- enable PRIVATE networks without NAT Gateway.

### Reproduction Steps

Try to create a VPC without NAT. You will be required to mark subnets as ISOLATED.

Then try to add a VPN Gateway. You will be informed you have no subnets that are PRIVATE.

Make the subnets PRIVATE. That will cause a NAT Gateway to be provisioned. 

### Environment

  - **CLI Version      : 1.21
  - **OS               :  N/A
  - **Language         :Typescript

--- 

This is :bug: Bug Report

**Comment by jogold** [comment]
You should be able to do the following:
```ts
new ec2.Vpc(this, 'Vpc', {
  subnetConfiguration: [
    {
      name: 'isolated',
      subnetType: ec2.SubnetType.ISOLATED,
    },
  ],
  vpnGateway: true,
  vpnRoutePropagation: [
    {
      subnetType: ec2.SubnetType.ISOLATED,
    },
  ],
});
```

The key here is to specify `vpnRoutePropagation`.

**Comment by aztecrex** [comment]
@jogoid you solution works. Thank you.

I still think this is a bug, however, or at least requires an API review--the `vpnRoutePropagation` key seems like the wrong place to specify this. Route propagation is about something entirely different.

**Comment by jogold** [comment]
> the `vpnRoutePropagation` key seems like the wrong place to specify this. Route propagation is about something entirely different.

A VPN gateway is [attached](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpc-gateway-attachment.html) to a VPC not to subnets. It is only by specifying a [`AWS::EC2::VPNGatewayRoutePropagation`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpn-gatewayrouteprop.html) that subnet's route tables are updated and traffic can flow.

Can you elaborate on why you think this is something entirely different? Would a "smarter" default for `vpnRoutePropagation` be a solution?
