### ISSUE TITLE
How to add sns topic as target to event rule in AWS CDK typescript?

### ISSUE THREAD

**Issue by Kiddinglife** [aws/aws-cdk#6010]
### The Question
How to add sns topic as target to event rule in AWS CDK typescript?
the codes below does not compile.
```typescript
import { Topic} from '@aws-cdk/aws-sns';
let alertsTopic: Topic = {...};
this.rule.addTarget(alertsTopic);
```

**Comment by jogold** [comment]
You need to use an integration class from [`@aws-cdk/aws-events-targets`](https://github.com/aws/aws-cdk/tree/v1.22.0/packages/@aws-cdk/aws-events-targets)

```ts
this.rule.addTarget(new targets.SnsTopic(alertsTopic));
```

See [integ test](https://github.com/aws/aws-cdk/blob/v1.22.0/packages/%40aws-cdk/aws-events-targets/test/sns/integ.sns-event-rule-target.ts).

**Comment by skinny85** [comment]
@Kiddinglife would you mind posting this question on Stackoverflow, and linking to it from here?

**Comment by SomayaB** [comment]
Closing this issue since there hasn't been a response in a while. Feel free to reopen.
