### ISSUE TITLE
Using the VPC construct results in error: Value (us-west-1b) for parameter availabilityZone is invalid. Subnets can currently only be created in the following availability zones: us-west-1a, us-west-1c. 

### ISSUE THREAD

**Issue by pcgeek86** [aws/aws-cdk#6015]
Using the high-level VPC construct results in an error message, when deploying into the `us-west-1` AWS region.

### Reproduction Steps

```python
from aws_cdk import (
    core,
    aws_ec2 as ec2
)

class AwscdktestStack(core.Stack):
    def __init__(self, scope: core.Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)
        ec2.Vpc(self, 'vpccdktest')

app = core.App()
AwscdktestStack(app, "awscdktest", env=core.Environment(region="us-west-1"))
app.synth()
```

### Error Log

> Value (us-west-1b) for parameter availabilityZone is invalid. Subnets can currently only be created in the following availability zones: us-west-1a, us-west-1c. 

### Environment

  - **CLI Version      :** 1.22.0 (build 309ac1b)
  - **Framework Version:** aws-cdk.core 1.22.0
  - **OS               :** MacOS Catalina
  - **Language         :** Python 3.7.5

### Other

--- 

This is :bug: Bug Report

**Comment by ColeMurray** [comment]
+1

**Comment by ColeMurray** [comment]
As a fix, you can add context about the AZ in the cdk.json
See: https://github.com/aws/aws-cdk/issues/9226#issuecomment-719838539

**Comment by corymhall** [comment]
@pcgeek86 it looks like this may have been fixed. I just tried to reproduce the error and I was able to create a VPC successfully.
