### ISSUE TITLE
Allow importing of existing Github Webhooks for Codepipeline Github source

### ISSUE THREAD

**Issue by gbooth27** [aws/aws-cdk#6020]
I would like to be able to import a pre-existing webhook URL from github into the Codepipeline Github source action, instead of having each action create its own webhook automatically. so you could pass something like `webhookURL` in the [props](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-codepipeline-actions.GitHubSourceActionProps.html) and it would just use that existing webhook instead of creating a new one.

### Use Case

I am running into an issue where when I try have more than 20 AWS codepipelines sourcing from the same repository (each one deploys from a different branch) Github prevents the 21st from registering the Push webhook that a github source for codepipeline autocreates. Github does not allow more than 20 webhooks per repo. I reached out to Github support and they were not very helpful:
![Screen Shot 2020-01-29 at 1 31 18 PM](https://user-images.githubusercontent.com/13037196/73408811-435cf980-42b2-11ea-8290-7c1a4f1933ef.png)

### Proposed Solution

I would like to be able to import a pre-existing webhook URL from github into the Codepipeline Github source action, instead of having each action create its own webhook automatically. so you could pass something like `webhookURL` in the [props](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-codepipeline-actions.GitHubSourceActionProps.html) and it would just use that existing webhook instead of creating a new one.

You dont need one webhook per pipeline, as the pipeline filters on the branch. so re-use is possible

### Other
I realize that this is likely not a trivial change, as it does not look like this is even supported in the console. but I figured it couldn't hurt to ask. 

I have gotten around it for now by using the polling option for Github Triggers, but in all of your documentation that method is not recommended, so hoping to switch off of that if I can

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by skinny85** [comment]
Hey @gbooth27 ,

unfortunately, I don't think it's possible to reuse the same webhook in multiple pipelines. If you look at the code [that creates the webhook](https://github.com/aws/aws-cdk/blob/e7ef5e5660457eb82252e8992214da775b83c41c/packages/%40aws-cdk/aws-codepipeline-actions/lib/github/source-action.ts#L118-L118):

```typescript
      new codepipeline.CfnWebhook(scope, 'WebhookResource', {
        authentication: 'GITHUB_HMAC',
        authenticationConfiguration: {
          secretToken: this.props.oauthToken.toString(),
        },
        filters: [
          {
            jsonPath: '$.ref',
            matchEquals: 'refs/heads/{Branch}',
          },
        ],
        targetAction: this.actionProperties.actionName,
        targetPipeline: stage.pipeline.pipelineName,
        targetPipelineVersion: 1,
        registerWithThirdParty: true,
      });
```

As you can see, both the branch, action, and pipeline are all in the WebHook definition, so sharing them probably won't work.

You should be able to experiment with this yourself by using `GitHubSourceAction`'s `trigger` property set to `GitHubTrigger.NONE` and creating the webhook resource as above, but I'm not sure it's going to work.

Thanks,
Adam

**Comment by SomayaB** [comment]
Closing this issue since there hasn't been a response in a while. Feel free to reopen.
