### ISSUE TITLE
VPC look up shows always the same VPC even after change of tags

### ISSUE THREAD

**Issue by githubnoobieme** [aws/aws-cdk#6025]
When I filter a VPC by tag it still shows the same VPC even if this VPC has new tag. 

My code look like this

`vpc=ec2.Vpc.from_lookup(self,"VPC",is_default=False,tags={"endpoint":"yes"})`

When I change the tag on the VPC to "no" and to "yes" on another VPC, I would expect another VPC to show up. But the output of synth still show the first VPC with its ID.

**Comment by rix0rrr** [comment]
This is on purpose. Either change the query or clear the context cache:

https://docs.aws.amazon.com/cdk/latest/guide/context.html
