### ISSUE TITLE
eks.Cluster.addAutoScalingGroup is not a function when called from another stack

### ISSUE THREAD

**Issue by moatazelmasry2** [aws/aws-cdk#6028]
So I'm creating the eks cluster in stack1 and trying to add an ASG in stack2 to that cluster. The Cluster is being loaded into stack2 using eks.Cluster.fromClusterAttributes() 

### Reproduction Steps

```stack1.ts
const vpc = ec2.Vpc(this, "vpc")
const eks = eks.Cluser(this,"EKS", {vpc: vpc}
```

```stack2.ts
const vpc = ec2.Vpc.fromVpcAttributes(this, 'VPC1Default', {
            vpcId: "vpcid-xxxx",
            availabilityZones: ['eu-central-1a', 'eu-central-1b', 'eu-central-1c'],
            vpcCidrBlock: "xxxxx"
            publicSubnetIds: [ "subnet1id", "subnet2id", "subnet3id", ]
        })
        //
        const eksCluster = eks.Cluster.fromClusterAttributes(this, "Cluster", {
            clusterArn: "arn::xxx",
            clusterName: "somename",
            vpc: vpc,
            securityGroups: [],
            clusterCertificateAuthorityData: "",
            clusterEndpoint: ""
        }) as eks.Cluster
eksCluster.addAutoScalingGroup(onDemandASG, {

        })

```

### Error Log

cdk synth produces the following error: 
**eksCluster.addAutoScalingGroup is not a function**

### Environment

  - **CLI Version**      : 1.17.7
  - **Framework Version:** 1.22.0 (build 309ac1b)

### Other

Obliviously if I put everything into one stack, things work. But this is quite irritating, since one file tends to grow too big too fast

--- 

This is :bug: Bug Report

**Comment by eladb** [comment]
The `fromClusterAttributes` returns an object that implements `ICluster` and not a `Cluster` class. There are some things that you currently cannot do with imported clusters,. such as adding auto scaling groups.

Related to #8608
