### ISSUE TITLE
Typo in aws-lambda-destinations README.md for SnsDestination class

### ISSUE THREAD

**Issue by hom-bahrani** [aws/aws-cdk#6030]
The link to the documentation is [here](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-lambda-destinations-readme.html)

There's a small typo in the readme example for publishing to an SNS topic on succesful Lambda invocations, it should be `onSuccess: new destinations.SnsDestination(myTopic)` not `SnsDestionation`

---

This is a 📕 documentation issue

**Comment by hom-bahrani** [comment]
Fix https://github.com/aws/aws-cdk/pull/6031

**Comment by SomayaB** [comment]
Hi @hom-bahrani, thanks for reporting this and putting in a PR, much appreciated! 👍
