### ISSUE TITLE
`DynamoEventSource` does not accept `ITable`

### ISSUE THREAD

**Issue by thomasrodenhausen** [aws/aws-cdk#6032]
[Table.fromTableArn()](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-dynamodb.Table.html#static-from-wbr-table-wbr-arnscope-id-tablearn) returns an `ITable` which instead of a `Table` and thus imported tables cannot be used to create a [DynamoEventSource](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-lambda-event-sources.DynamoEventSource.html).

Should `DynamoEventSource` accept `Table`?

Can other functionality ([grantFullAccess()](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-dynamodb.Table.html#grant-wbr-full-wbr-accessgrantee), [tableStreamArn](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-dynamodb.Table.html#tablestreamarn)) be made available on Table made accessible on ITable?

### Reproduction Steps

```
const table = Table.fromTableArn(this, "table", "tableArn");
new DynamoEventSource(table, { startingPosition: StartingPosition.LATEST });
```

### Error Log
DynamoEventSource does not accept `ITable`

### Environment

  - **CDK Version:** 1.22
  - **OS               :** Mac OS
  - **Language         :** Typescript

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
@thomasrodenhausen -

Thanks for filing this issue.

Unfortunately, only DDB tables which have streams enabled can be connected as event source to a lambda function. There is no way for us to find out if the imported table has this turned on or not, without interacting with the DynamoDB service. 
Without this check, the user experience will be sub-optimal in that there will be a failure when the stack is being deployed. 

On the other hand, when we explicitly use `Table`, the CDK app already has enough information to know if streams are enabled on the table.

For your use case, I would suggest using the `addEventSource()` API on the `Function` construct and specify the table's stream ARN there. The ARN will be available in the response to DynamoDB's `DescribeTable` API.
