### ISSUE TITLE
ALB Lambda Target Support doesn't enable health check when set

### ISSUE THREAD

**Issue by mouyigang** [aws/aws-cdk#6036]
```
const target_group = listener.addTargets('Targets', {
            targets: [new LambdaTarget(mylambda)],
            healthCheck: {
                path: "/health"
            }
        });
```
doesn't enable health check on target group for Lambda function

### Environment

  - **CLI Version:** 1.19.0
  - **Framework Version:**
  - **OS:** Mac
  - **Language:** ts

### Other

cdk should automatically enable health check when set from addTargets

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
Fixed in #7023
