### ISSUE TITLE
If --role-arn or --profile are provided, env = {account: "xxxxx", region: "xxxxx"} should work with no additional credentials

### ISSUE THREAD

**Issue by moatazelmasry2** [aws/aws-cdk#6037]
When creating a new VPC and I want the subnets to spread on more than 2 subnets, then according to this documentation:
https://docs.aws.amazon.com/cdk/latest/guide/environments.html
and https://docs.aws.amazon.com/cdk/api/latest/docs/aws-ec2-readme.html
I must provide aws credentials.

As a new user, this is very confusing to me, since I am already providing the credentials through **--profile**, I was expecting cdk to remotely fetch the correct info about my account and region to create the vpc, which didn't happen. First when I defined the environment variables AWS_ACCESS_KEY and the secret key did it work.

There should be no difference really, whether the credentials are provided as --role-arn or --profile or as environment variables, the vpc creation as well the stack creation should work.

### Use Case
It is less confusing to new users

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by richardhboyd** [comment]
IAM Roles are not tied to specific regions. By knowing the Role ARN we may not know which region you want the infrastructure built in.

**Comment by moatazelmasry2** [comment]
But if I am providing a profile, then this can contains a region and I shouldn't explicitly specify a region again

**Comment by moatazelmasry2** [comment]
So in other words, if a user provides `--profile` there should be no need to check for AWS_ACCESS_KEY. Morover maybe there can be some clear defined and documented behavior, for example in the following priority


1. If `--role-arn` AND `--profile` are provided, and account id and region and role arn are fetched from those information. This takes the highest priority.
2. If NO `--role-arn` is provided, but `--profile` is provided, then still the account and region information are extracted using these information
3. If NO `--profile` is provided, then region and account information are extracted from the env {} object using the default profile or the environment variables AWS_ACCESS and SECRET_KEY_ID
4. If no env {} is provided, then the region and account number are extracted from AWS_ACCESS and SECRET_KEY_ID + AWS_DEFAULT_REGION variable.

Honestly the priority/logic is unimportant to me. Important is to remove the confusion. Right now it seems that cdk obtains the vpc information solely using env {} + AWS_ACCESS_KEYS_ID + AWS_SECRET_ACCESS_KEY, while `cdk deploy` happily runs with `--profile`and/or `--role-arn`

**Comment by rix0rrr** [comment]
```ts
new MyDevStack(app, 'dev', { 
  env: { 
    account: process.env.CDK_DEFAULT_ACCOUNT, 
    region: process.env.CDK_DEFAULT_REGION 
}});
```

https://docs.aws.amazon.com/cdk/latest/guide/environments.html

**Comment by moatazelmasry2** [comment]
Hi @rix0rrr thanks for the documentation. This still does not answer the question. Why do I need to provide an env {} if I already provided a `--profile`
