### ISSUE TITLE
CDK Destroy order of resource deletion

### ISSUE THREAD

**Issue by pankaj200788** [aws/aws-cdk#6041]
CDK destroy to delete resources based on order of some Id.

### Use Case

I tried to destroy my CDK stack and it started removing DbSubnetGroup etc. before actually removing my DB Instance and hence failed. 

Ideally, it should have deleted DB Instance then ParameterGroup, DBSubnetGroup etc.

### Proposed Solution

CDK should recognise the order in which these resources are interlinked with each other.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by moatazelmasry2** [comment]
Have you tried using the function node.addDependancy() ? This might solve your problem.

The same behavior happens btw in pure cloudformation, so imo this is not an cdk problem

**Comment by skinny85** [comment]
Hey @pankaj200788 ,

thanks for opening the issue. Is this a duplicate of #5282 ? (Check what RetentionPolicy your DBInstance has set, and see whether termination protection is enabled - both make your DB be retained by default).

**Comment by SomayaB** [comment]
I will assume this is a duplicate since there hasn't been a response in a while. Closing this issue. Feel free to reopen.
