### ISSUE TITLE
rds.DatabaseInstance.backup_retention doesn't accept core.RemovalPolicy as value

### ISSUE THREAD

**Issue by IvanBodnar** [aws/aws-cdk#6042]
I'm passing core.RemovalPolicy.DESTROY to rds.DatabaseInstance backup_retention parameter, to change it's default behavior (core.RemovalPolicy.RETAIN), and I'm getting:

jsii.errors.JSIIError: Expected object reference, got {"$jsii.enum":"@aws-cdk/core.RemovalPolicy/DESTROY"}

### Reproduction Steps

db = rds.DatabaseInstance(
           ...
            backup_retention=core.RemovalPolicy.DESTROY,
           ...
        )

### Error Log

jsii.errors.JSIIError: Expected object reference, got {"$jsii.enum":"@aws-cdk/core.RemovalPolicy/DESTROY"}

### Environment

  - **CLI Version      :  aws-cli/1.17.9 Python/3.7.3 Linux/5.0.0-38-generic botocore/1.14.9**
  - **Framework Version: aws-cdk.core 1.22.0**
  - **OS               : Ubuntu 19.04**
  - **Language         : Python**

### Other

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hey @IvanBodnar ,

you are passing an incorrect type there. `backup_retention` is of the type `Duration`: https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_rds/DatabaseInstance.html

Thanks,
Adam

**Comment by IvanBodnar** [comment]
Yep, my mistake.

Thanks a lot @skinny85
