### ISSUE TITLE
Add user_data to bastion host

### ISSUE THREAD

**Issue by agalazis** [aws/aws-cdk#6059]
I need to customize the initial setup of my bastion host.

### Use Case

I want a bastion host with preinstalled psql  client, a public key setup (for ssh) and possibly many other customizations.

### Proposed Solution
Support adding user_data configuration that will allow for setup customizations(as in ec2 instance user_data )

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
Once this is merged (https://github.com/aws/aws-cdk/pull/6065/files) you can do this by instantiating a `UserData` object and passing to the `MachineImage` you're passing to the bastion host.

It would be better to allow direct control of the UserData like on AutoScalingGroups, which is going to be the FR for this issue.

**Comment by vanniktech** [comment]
This can be done now:

```kotlin
val userData = UserData.forLinux()
        userData.addCommands("yes | sudo amazon-linux-extras install postgresql10")

BastionHostLinux.Builder.create(this, ec2ProxyId)
            .machineImage(MachineImage.latestAmazonLinux(AmazonLinuxImageProps.builder()
                .userData(userData)
                .build())
            )
```

**Comment by gshpychka** [comment]
This can be closed @agalazis

**Comment by gshpychka** [comment]
@agalazis ...you're the one who can close it :)

**Comment by sophistafunk** [comment]
I have the same request to customize the user data for the bastion host, however Is there a solution for this in Python? When looking up `BastionHostLinux.Builder` all I am able to find are the java docs [here](https://docs.aws.amazon.com/cdk/api/latest/java/software/amazon/awscdk/services/ec2/BastionHostLinux.Builder.html) for it, I wasn't able to find anything in the docs that indicates this is the recommended way implement in Python.
