### ISSUE TITLE
Asset.fingerprint() does not account for file mode, only file type and content

### ISSUE THREAD

**Issue by nathanpeck** [aws/aws-cdk#6072]
When adding files to an Asset staging area a hash is calculated that attempts to verify that the files have actually changed in order to avoid unneeded rebuilds. However, the [fingerprint() function that calculates this hash](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/assets/lib/fs/fingerprint.ts#L24-L64) only takes into account the type of the file (file or folder) and its content.

It does not take into account the [Unix file mode](https://en.wikipedia.org/wiki/Modes_(Unix)). So if you change the mode of a file the asset system will not detect a change and will not rebuild the asset.

### Reproduction Steps

I created a Dockerfile that executes a bash script. Initially forgot to `chmod +x` the script file, so it was not executable. I built the asset with CDK, which built the Docker image and pushed it.

Once I realize the error of my ways and the Docker image failed to run in my dev environment I went back and ran `chmod +x` on the bash script file so that it could actually be executed. 

I did a CDK build again and noted that CDK skipped the asset build because it did not notice any changes. Despite the file mode change CDK continued to use the previous version of the Docker image without picking up my changes. I had to make another file change by adding a comment before CDK noticed a change and rebuilt the asset

### Environment

  - **CLI Version      : 1.22.0**
  - **Framework Version: 1.22.0**

--- 

This is :bug: Bug Report

**Comment by eladb** [comment]
Nice one!

**Comment by christophgysin** [comment]
Bad bot.

**Comment by nathanpeck** [comment]
@eladb I think the last time we had chatted about this you had said that ya'll were planning to rewrite the assets completely. Is this something that actually happened or is this actually still an issue?

**Comment by nathanpeck** [comment]
Alright I did some more research. Based on the code it does look like this is still an issue: https://github.com/aws/aws-cdk/blob/2f1fc959b1cbe406351cc0d3e057841497af1c19/packages/%40aws-cdk/core/lib/fs/fingerprint.ts#L24-L76

I don't see anything in this fingerprint function which can account for the Unix file mode.

**Comment by eladb** [comment]
Contributions are welcome!
