### ISSUE TITLE
CDK Diff not working with PolicyDocument.Statement

### ISSUE THREAD

**Issue by bpcrao** [aws/aws-cdk#6073]
description of the bug:

- Create a Managed Policy with multiple policy statements 
-  manually modify the policy from AWS console 
- the CDK diff from command line does not give the right diff and does not detect the drift

ℹ️ CDK Version: 1.21.1 (build 842cc5f)
ℹ️ No AWS environment variables
ℹ️ No CDK environment variables

### Reproduction Steps

created a management policy using
new ManagementPolicy(scope, id, { managedPolicyName: managedProps.name, statements:statements })

which succesfully created the policy 
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "KMSDataSID",
            "Effect": "Allow",
            "Action": [
                "kms:Decrypt",
                "kms:Encrypt"
            ],
            "Resource": "arn:aws:kms:*:*:key/XXXXXXXX"
        },
```
.....

but when we edit the policy and remove few statements from the policy in AWS console 

then do a 'cdk diff' the command line does not show any diff

### Environment

  - **CLI Version      :**
  - **Framework Version:**
  - **OS               :**  macOS Sierra
  - **Language         :** Typescript

### Other

--- 

This is :bug: Bug Report

**Comment by bpcrao** [comment]
to help more I think the cdk diff is comparing the stack with the template json last time deployed
and not the actual resources on AWS

**Comment by bpcrao** [comment]
I think this is not a bug seems AWS CDK is designed to be like this , so the feature needed is something like DRIFT any solution to that would be highly appreciated.

**Comment by shivlaks** [comment]
@bpcrao This is not a bug as it is expected that changes that are made out of band are not tracked by diff.

As per the `--help` option in `diff`
> Compares the specified stack with the deployed stack or a local template file, and returns with status 1 if any difference is found

I think what you want is CloudFormation drift detection. Feel free to upvote #1723

**Comment by bpcrao** [comment]
@shivlaks also one more problem I see is the diff output dues not show the policy document with the statements
