### ISSUE TITLE
ScheduledFargateTaskDefinitionOptions type requires unused schedule property

### ISSUE THREAD

**Issue by floehopper** [aws/aws-cdk#6076]
`ScheduledFargateTaskDefinitionOptions` should not extend `ScheduledTaskBaseProps`. This is because in the scenario when `ScheduledFargateTaskProps` is supplied with the `scheduledFargateTaskDefinitionOptions` property set, the instance of `ScheduledFargateTaskDefinitionOptions` is required to have a `schedule` property set even though this is ignored by the `ScheduledTaskBase` & `ScheduledFargateTask` constructors and the `schedule` property of the "wrapper" `ScheduledFargateTaskProps` instance is used.

### Reproduction Steps

Broken:

```ts
const task = new ScheduledFargateTask(this, 'task', {
  scheduledFargateTaskDefinitionOptions: {
    taskDefinition: taskDefinition
  },
  schedule: schedule
});
```

Workaround:

```ts
const task = new ScheduledFargateTask(this, 'task', {
  scheduledFargateTaskDefinitionOptions: {
    taskDefinition: taskDefinition,
    schedule: schedule // required, but ignored
  },
  schedule: schedule // required
});
```

### Error Log

Something along the lines of:

```
Property 'schedule' is missing in type '{ taskDefinition: ecs.FargateTaskDefinition; }' but required in type 'ScheduledFargateTaskDefinitionOptions'
```

### Environment

  - **CLI Version      : 1.22.0**
  - **Framework Version: 1.22.0**
  - **OS               : MacOS v10.15.1**
  - **Language         : Typescript**

### Other

I'd be happy to supply a pull request to fix this, but I wanted to check I'd identified a genuine problem and that my suggested solution of having `ScheduledFargateTaskDefinitionOptions` not extend `ScheduledTaskBaseProps` is sensible. Perhaps I'm missing something...?

--- 

This is :bug: Bug Report

**Comment by iamhopaul123** [comment]
related to #5830

**Comment by iamhopaul123** [comment]
@floehopper Yes, `extends ScheduledTaskBaseProps` should be removed from both `ScheduledEc2TaskDefinitionOptions` and `ScheduledFargateTaskDefinitionOptions`. This will not break anything. Thank you for catching this bug!

**Comment by floehopper** [comment]
🎉
