### ISSUE TITLE
DatabaseInstance construct creates an RDS using EC2-Classic networking

### ISSUE THREAD

**Issue by stevenoctopus** [aws/aws-cdk#6079]
When creating a RDS instance, specifically MySQL 8.0.16, using the DatabaseInstance construct, the console shows a recommendation to place your database in a VPC.

![ec2-classic](https://user-images.githubusercontent.com/4183386/73695653-8c44f180-46a8-11ea-8944-5ba1f6d1e7aa.png)

```
this.rds = new DatabaseInstance(this, 'RDS', {
      engine: DatabaseInstanceEngine.MYSQL,
      instanceClass: InstanceType.of(InstanceClass.STANDARD5, InstanceSize.LARGE),
      masterUsername: 'root',
      vpc: props.vpc,
      allocatedStorage: 100,
      backupRetention: Duration.days(3),
      cloudwatchLogsExports: [
        'error',
        'general',
        'slowquery'
      ],
      cloudwatchLogsRetention: RetentionDays.SIX_MONTHS,
      engineVersion: '8.0.16',
      monitoringInterval: Duration.seconds(60),
      multiAz: true,
      parameterGroup: new ParameterGroup(this, 'RDSParameterGroup', {
        family: 'mysql8.0',
        parameters: {
          'general_log': '1',
          'slow_query_log': '1',
          'log_output': 'FILE'
        },
        description: 'Default parameter group for mysql8.0 with logging to CloudWatch'
      }),
      removalPolicy: RemovalPolicy.DESTROY,
      storageEncrypted: true
});
```

### Environment

  - **CDK CLI Version:** 1.22.0 (build 309ac1b)
  - **Module Version:** 1.22.0
  - **OS:** Ubuntu
  - **Language:** Typescript

**Comment by stevenoctopus** [comment]
Checked the console today, I still have the recommendation but that instance does NOT exist in my account.

The only instance I have has a different instance identifier now?

---

I deleted the entire stack, bringing me down to 0 RDS instances, and still had the recommendation.

I redeployed the stack without making any changes and an RDS instance was created successfully, without a new recommendation.

---

Not sure what happened yesterday while deploying and not sure why I still have a recommendation for an instance that doesn't exist.

**Comment by nija-at** [comment]
Unfortunately, the recommendations page is controlled by RDS and the CDK does not interact with it, so there's not much we can help out here. 

It's likely that the scans they do and the recommendations they post is delayed and you may have seen the recommendation of an instance that you had long removed. Caveat: I'm guessing here.
