### ISSUE TITLE
expect (from @aws-cdk/assert) fails when passed a CloudFormationStackArtifact

### ISSUE THREAD

**Issue by cmackie** [aws/aws-cdk#6083]
The override of `expect` defined in `@aws-cdk/assert` fails when passed a `CloudFormationStackArtifact` object retrieved with the [`SynthUtils`](https://github.com/aws/aws-cdk/blob/16f9721955b2aacec5ed3850b8b8d399ffecfe75/packages/%40aws-cdk/assert/lib/synth-utils.ts#L7) api. This only happens in projects which do not have a flat dependency tree, instead producing the full dependency tree (which should be supported) in node_modules. The root of the problem is that [`@aws-cdk/core`](https://github.com/aws/aws-cdk/blob/16f9721955b2aacec5ed3850b8b8d399ffecfe75/packages/%40aws-cdk/core/package.json#L160) has `@aws-cdk/cx-api` as a direct dependency even though it exposes classes within `@aws-cdk/cx-api` (the `CloudFormationStackArtifact` retrieved though `SynthUtils` is ultimately created in [`ConstructNode`](https://github.com/aws/aws-cdk/blob/16f9721955b2aacec5ed3850b8b8d399ffecfe75/packages/%40aws-cdk/core/lib/construct.ts#L34). This means that when the `instanceof` operator is [used](https://github.com/aws/aws-cdk/blob/16f9721955b2aacec5ed3850b8b8d399ffecfe75/packages/%40aws-cdk/assert/lib/expect.ts#L8) on a `CloudFormationStackArtifact` anywhere in `@aws-cdk/assert`, the left hand side was created by the `@aws-cdk/cx-api` module required by `@aws-cdk/core`, whereas the right hand side class comes from the `@aws-cdk/cx-api` module required by `@aws-cdk/assert`. This causes `instanceof` to return false. 

In addition to the issue with `expect` (which I think is most serious), this problem causes several other methods (like `SynthUtils.toCloudFormation` within `@aws-cdk/assert` to misbehave subtly).

### Reproduction Steps

While I've only been able to naturally reproduce this in my own project (which I cannot share here), this is fairly easy to reproduce with the simple project created by `cdk init`. Just follow these steps:

1. `mkdir dep-test && cd dep-test`
2. `cdk init --typescript`
3. Replace `dep-test/test/dep-test.test.ts` with the attached file.
[dep-test.test.txt](https://github.com/aws/aws-cdk/files/4150957/dep-test.test.txt)

At this point, running `npm run test` succeeds because `npm install` creates a flat `node_modules`. To reproduce the error, we need to simulate the results of using an older version of npm, or any other build system which creates the full dependency tree.

4. `mkdir -p node_modules/@aws-cdk/assert/node_modules/@aws-cdk && cp -r node_modules/@aws-cdk/cx-api "$_"`
5. `mkdir -p node_modules/@aws-cdk/core/node_modules/@aws-cdk && cp -r node_modules/@aws-cdk/cx-api "$_"`

Now running `npm run test` fails, for the reason I described earlier in this report.

### Error Log

```
TypeError: Cannot read property 'root' of undefined

       8 |     const stack = new HelloCdk.HelloCdkStack(app, 'MyTestStack');
       9 |     // THEN
    > 10 |     expectCDK(SynthUtils.synthesize(stack));
         |     ^
      11 | });

      at Function._synthesizeWithNested (node_modules/@aws-cdk/assert/lib/synth-utils.ts:54:29)
      at Object.expect (node_modules/@aws-cdk/assert/lib/expect.ts:8:90)
      at Object.<anonymous> (test/hello-cdk.test.ts:10:5)
```

### Environment

  - **CLI Version      :** 1.22.0
  - **Framework Version:** 1.22.0
  - **OS               :** macOS 10.14.6
  - **Language         :** TypeScript

### Other

--- 

This is :bug: Bug Report

**Comment by eladb** [comment]
We are aware that there are issues related to how CDK is released ("hyper-modular"). The current best practice is to always use a single version line and have npm flatten the dependency graph.

You can stay tuned here for updates: https://github.com/aws/aws-cdk-rfcs/issues/6
