### ISSUE TITLE
ECS Container Definition - Execution Role is wrong when using existing log group, unable to launch tasks

### ISSUE THREAD

**Issue by rmmeans** [aws/aws-cdk#6097]
When creating a ContainerDefinition for ECS and setting up logging using the AwsLogDriver with a pre-existing CloudWatch Logs Group, the underlying execution role that is automatically generated for you by the CDK does not have the proper grants created, this is resulting in the ECS task (in my case, with fargate) from ever being able to stand up.

### Reproduction Steps
This is in Scala (via the Java CDK):
```scala
  val containerDef: ContainerDefinition = ContainerDefinition.Builder
    //Other features redacted
    .logging(AwsLogDriver.Builder
        .create()
        .logGroup(LogGroup.fromLogGroupName(this, "loggroup", "my-existing-log-group"))
        .streamPrefix("Fargate")
        .datetimeFormat("%Y-%m-%d").build())
    .build()
```

After running `cdk synth` the relevant cloudformation generated would look like this: 

```json

  {
              "Action": [
                "logs:CreateLogStream",
                "logs:PutLogEvents"
              ],
              "Effect": "Allow",
              "Resource": {
                "Fn::Join": [
                  "",
                  [
                    "arn:",
                    {
                      "Ref": "AWS::Partition"
                    },
                    ":logs:",
                    {
                      "Ref": "AWS::Region"
                    },
                    ":",
                    {
                      "Ref": "AWS::AccountId"
                    },
                    ":log-group:my-existing-log-group"
                  ]
                ]
              }

```

### Error Log

When ECS attempts to launch the container, an error will be received that is truncated in ECS, but looking further in cloudtrail we can see that the execution role got a deny for creating a log stream:

```json
    "errorCode": "AccessDenied",
    "errorMessage": "User: arn:aws:sts::REDACTED:assumed-role/REDACTED is not authorized to perform: logs:CreateLogStream on resource: arn:aws:logs:us-east-1:REDACTED:log-group:my-existing-log-group:log-stream:Fargate/container/REDACTED",
```

I was able to fix this via a manual change to IAM to adjust the execution role policy that was created, it was missing a `:*` wildcard at the end of the generated statement (it should have been generated as such: ```:log-group:my-existing-log-group:*```. Looking closer as the CDK source - I see the following information: https://github.com/aws/aws-cdk/blob/v1.22.0/packages/@aws-cdk/aws-logs/lib/log-group.ts#L167-L169

>       // A LogGroup ARN out of CloudFormation already includes a ':*' at the end to include the log streams under the group.
>       // See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-loggroup.html#w2ab1c21c10c63c43c11

It would appear the CDK for CloudWatch on grant did not assume the proper case for when a cloudwatch log group was already existing when referenced as I listed above for when creating an ECS task. I believe my only way around this right now is to not create the log group outside of the CDK.

### Environment

  - **CLI Version      : 1.22.0 (build 309ac1b)**
  - **Framework Version:**
  - **OS               :**
  - **Language         :Scala (Java)**

--- 

This is :bug: Bug Report

**Comment by iamhopaul123** [comment]
@eladb I think CDK doesn’t format the log group ARN correctly (missing “:*” in the end of the ARN) when importing a log group using its name. As reference (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-loggroup.html#w2ab1c21c10c63c43c11) the ARN should be ended with “:*” so that log-stream-level write permission can be granted to the ECS service. Can we make changes to “aws-logs” packages to fix this issue? What do you think?

**Comment by pkandasamy91** [comment]
Resolved in https://github.com/aws/aws-cdk/pull/7668/files
