### ISSUE TITLE
Clean up feature flags source files

### ISSUE THREAD

**Issue by Jerry-AWS** [aws/aws-cdk#6098]
The files https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/cx-api/lib/future.ts and https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/cx-api/lib/features.ts together comprise a list of the currently-supported feature flags.

Problem is, `future.ts` doesn't tell you what the feature flags are actually named, while `features.ts` lists things besides feature flags. Aside from being difficult for users to figure out, it makes it hard to link to a succinct list of feature flags (e.g. from the Feature Flags topic in the Developer Guide).

Maybe these could be unified or otherwise cleaned up.

**Comment by Jerry-AWS** [comment]
Added myself so I can make sure the right link gets into the Dev Guide once this is finalized.

**Comment by eladb** [comment]
PR in: https://github.com/aws/aws-cdk/pull/6181

**Comment by eladb** [comment]
@Jerry-AWS the link you need is `features.ts` (which I believe is the one you already have, correct)?

**Comment by Jerry-AWS** [comment]
Yes, the link is already correct. I'll clean up the wording around it a bit. Thanks!
