### ISSUE TITLE
Generated IDs + Swagger (APIG Land)

### ISSUE THREAD

**Issue by mindstorms6** [aws/aws-cdk#61]
So we generate these super fun logical IDs.

Which is dope.

But most folks will use imported swagger (failry common) . 

Problem being swagger needs to have the ref's to the Lambda (and sometimes the APIG role) - and that's not very easy to do right now. I think I'll have to bascially search the import JSON for kind of a placeholder value, and replace it :/

We should make this super clean and intuitive for customers

**Comment by SomayaB** [comment]
Closing this issue since there hasn't been activity on it in a while. Feel free to reopen.
