### ISSUE TITLE
CodePipeline Manual Approval Configuration should not require an SNS Topic.

### ISSUE THREAD

**Issue by brettswift** [aws/aws-cdk#6100]
### Description

Something I noticed, which is low priority - the simple work around is to supply an SNS topic even if you don't want to use it. 

Code pipeline manual approval configuration does not appear in the pipeline if an SNS topic is not provided.

The console should show "additional information" and the "external link" if there isn't an SNS topic, so approvers in the console can read the message.  Cloudformation allows this,  CDK does not. 

The code that causes this is the conditional here:  
https://github.com/aws/aws-cdk/blob/be2e3e305eee5d90552c08512a4d476db74b91d0/packages/%40aws-cdk/aws-codepipeline-actions/lib/manual-approval-action.ts#L79-L85

### Reproduction Steps
Run the following stack and look at the configuration output: 

To isolate the part of the template this convenience command is provided
`npm run build ; npx cdk synth  | grep -i 'Category: Approval' -A 10 -B 10`
  
```typescript
import * as cdk from '@aws-cdk/core';
import codepipeline = require('@aws-cdk/aws-codepipeline');
import codepipelineActions = require('@aws-cdk/aws-codepipeline-actions');
import s3 = require('@aws-cdk/aws-s3');
import sns = require('@aws-cdk/aws-sns');

export class CodepipelineBugReproStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const sourceOutput = new codepipeline.Artifact("SourceArtifact");

    const sourceBucket = new s3.Bucket(this, `SourceBucket`, {
      versioned: true,
      removalPolicy: cdk.RemovalPolicy.DESTROY,
      bucketName: `bswift-bugreproduce-codepipeline`
    });

    const sourceAction = new codepipelineActions.S3SourceAction({
      actionName: 'S3Source',
      bucket: sourceBucket,
      bucketKey: 'artifact.zip',
      output: sourceOutput,
    } as codepipelineActions.S3SourceActionProps);

    const approval = new codepipelineActions.ManualApprovalAction({
      actionName: `Manual-Approval`,
// Comment this line out and deploy to reproduce ////////////////////////
      notificationTopic: new sns.Topic(this, 'dummyTopic'), 
/////////////////////////////////////////////////////////////////////////////////////////////////
      additionalInformation: "This deploy is scary, will you approve it?!",
      externalEntityLink: "https://bitbucket.com/amazingrepo",
      runOrder: 1,
    } as codepipelineActions.ManualApprovalActionProps)

    new codepipeline.Pipeline(this, 'TestPipeline', {
      pipelineName: 'BugReproPipeline',
      stages: [
        {
          stageName: 'source',
          actions: [sourceAction],
        },
        {
          stageName: 'deploy',
          actions: [approval]
        }
      ]
    });

  }
}

```
 

### Environment

  - **CLI Version      :*1.22.0*
  - **Framework Version:*1.22.0*
  - **OS               :*OSX*
  - **Language         :*typescript*

--- 

### To Fix

I'm not sure what combination of those config properties is valid - if they are all valid independently the code should reflect that and allow it. 

 I can't seem to find this in the documentation for cloudformation - the actions show examples but don't seem to declare any other rules.  I have successfully deployed an approval without SNS and with the other 2 configs. 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Thanks for reporting @brettswift . I'll work on a fix.
