### ISSUE TITLE
Can't deploy or synth ECS service from pre-existing stacks

### ISSUE THREAD

**Issue by geof2001** [aws/aws-cdk#6109]
### Bug

```All arguments to Vpc.fromLookup() must be concrete (no Tokens)```

my lookups and cluster declaration:
```
    const myAg = autoscaling.AutoScalingGroup.fromAutoScalingGroupName(this, "myAg", "dev-compute-cluster-us-west-2")
    const myCluster = Fn.importValue("ecs-clusters-DevComputeCluster");
    const mySgName = Fn.importValue("network-InstanceSecurityGroup")
    const mySg = Vpc.SecurityGroup.fromSecurityGroupId(this, "mySg", mySgName)
    const myVpcId = Fn.importValue("network-VPCID")
    const myVpc = ec2.Vpc.fromLookup(this, "myVpc", {vpcId: myVpcId});
```

```
  const ecsCluster = Cluster.fromClusterAttributes(this, "ecsCluster", {
    clusterName: myCluster,
    vpc: myVpc,
    securityGroups: [mySg],
    hasEc2Capacity: true,
    autoscalingGroup: myAg
  });
  const myEcsService = new ecs.CfnService(this, `${prefix}_myEcsService`, {
    cluster: myCluster,
    serviceName: `${prefix}_myEcsService`,
    desiredCount: 1
  });
```
then just doing cdk synth

### Error Log

```
All arguments to Vpc.fromLookup() must be concrete (no Tokens)
Subprocess exited with error 1
```

### Environment

  - **CLI Version:** aws-cli/1.17.1 Python/2.7.10 Darwin/18.5.0 botocore/1.14.1
 - **CDK Version:** 1.21.1 (build 842cc5f)
  Darwin Kernel Version 18.5.0
  - **Language:** typescript

### Other

Not sure how I'm supposed to be fetching the ID of vpc other than from lookups of existing resources.  We have a large investment in layered cloudformation stacks with many exports being used in service layer stacks for things like sg's, az's, subnets, vpc's.  The service constructs natively in cloudformation support this style of direct import so not sure why this isn't working here.  CDK seems to want a lot of ITypes for properties that just need a string.  

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
This is not a bug report, the framework is working as intended.

-----

We're happy to help you out, but GitHub issues is not a support forum. There are
websites much better suited for that, such as StackOverflow.

Please ask that same question again on [StackOverflow under the
aws-cdk](https://stackoverflow.com/questions/ask?tags=aws-cdk). If you can't get
a response to your question, please bring it to our attention again and we will
do our best to answer it.
