### ISSUE TITLE
aws-cdk npm package dependency licences..

### ISSUE THREAD

**Issue by karthikga** [aws/aws-cdk#6112]
## :question: General Issue
aws-cdk npm package has some dependencies that does not have the correct LICENSE info , and hence gets rejected / marked as suspect by some corporate security / scanning tools. The package in suspect are listed below. PLs help to remedy nad repackage in the next npm packaging of aws-cdk.

### Environment and Other Details

  - **CDK CLI Version:** 
  - **Module Version:** 
  - **OS:** 
  - **Language:** 

npm install aws-cdk  fails due to validation of dependecies ( check for valid OSS Licenses ) for below dependent oss libs..

Artifact:                    NPM - aws-cdk@1.22.0
  Dependencies (229)

    Dependency: NPM - cli-color@0.1.7
      RejectReasons (1)
        RejectReason:   b4a36a87-69da-4964-890e-11b11e84cd1d
          Type:      UNKNOWN_LICENSE_FOUND
          License:   Custom: https://github.com/medikoo/clock
    Dependency: NPM - difflib@0.2.4
      RejectReasons (1)
        RejectReason:   aa30d726-2a96-433c-aea9-1339eed3b9ce
          Type:      UNKNOWN_LICENSE_FOUND
          License:   PSF
    Dependency: NPM - dreamopt@0.6.0
      RejectReasons (1)
        RejectReason:   b1f49ace-0b28-46ee-8887-557b6c325952
          Type:   NO_LICENSES_FOUND

    Dependency: NPM - heap@0.2.6
      RejectReasons (1)
        RejectReason:   9e471fc2-c7fb-4dbb-8d6b-2a9dadd533ee
          Type:      UNKNOWN_LICENSE_FOUND
          License:   PSF
		  
		  --------

**Comment by shivlaks** [comment]
@karthikga - thanks for reporting this issue... at a first glance, it seems that these are either older or deprecated packages and we should seek to upgrade them whenever possible.

* Is this list comprehensive? or would an audit be required?
* what types of licenses are acceptable at your organization? this might help better understand restrictions and reason about them?
  * i.e. `cli-color` uses the `ISC` license, which doesn't seem like it would be problematic

**Comment by SomayaB** [comment]
Closing for now since there hasn't been a response in a while. Feel free to reopen.
