### ISSUE TITLE
Resource name generation stripping hyphens/dashes

### ISSUE THREAD

**Issue by aflinton** [aws/aws-cdk#6116]
### The Question

We are trying to use a standardised naming strategy for our infrastructure resources (buckets, topic, queues etc).
The naming strategy involves separating development stage (e.g. sandbox = sbx, development = dev etc),module and where the module lives in the mental onion. and then starting the name with that e.g. If I have a queue called BobQueue then it's full name will be up being sbx-ee-core-BobQueue. Note there is text removed from links etc as this is a public forum.
Some physical names have the hyphens preserved e.g. https://sqs.../number/sbx-ee-core-BobQueue

While others for example buckets & topics lose the hyphens e.g. https://amazon.com/s3/home?region=region&bucket=emiseetest-sbxeecoretests3bucket3cc25994-1itgflirpo0li

or:

arn:aws:sns:region:number:emiseetest-sbxeecoretestTopicB80D33CA-165M0LBN3GIQ8

Is there anyway hyphens could be maintained? e.g. in 
https://github.com/aws/aws-cdk/blob/46febad2a5633f171fb835c8569eebaa056c876a/packages/%40aws-cdk/core/lib/private/uniqueid.ts#L32

Could the regex be altered to be alphanumeric & hyphen as per : 
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-name.html

"Names must begin with a letter; contain only ASCII letters, digits, and hyphens; and not end with a hyphen or contain two consecutive hyphens"

Or is there a known workaround for this problem?

### Environment

  - **CDK CLI Version:** 
  - **Module Version:** 
  - **OS:** 
  - **Language:**

**Comment by eladb** [comment]
If you wish, you can supply custom logical ID generation by overriding [allocateLogicalId](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.Stack.html#protected-allocate-wbr-logical-wbr-idcfnelement)
