### ISSUE TITLE
Getting ValidationError: Parameters: do not exist in the template while deploying

### ISSUE THREAD

**Issue by rampatina** [aws/aws-cdk#6119]
### The Question
In my CDK project have one stack and which has the lambda construct. While deploying the app it is throwing below error
` ❌  dev-ramsApp failed: ValidationError: Parameters: [AssetParametersd31648d1ddf3168166c543733439d89bfc721f0a19e78338afac49a9fa96f4b5ArtifactHashD17F28D4, AssetParametersd31648d1ddf3168166c543733439d89bfc721f0a19e78338afac49a9fa96f4b5S3VersionKeyB7A8C138, AssetParametersd31648d1ddf3168166c543733439d89bfc721f0a19e78338afac49a9fa96f4b5S3BucketA51A2111] do not exist in the template
Parameters: [AssetParametersd31648d1ddf3168166c543733439d89bfc721f0a19e78338afac49a9fa96f4b5ArtifactHashD17F28D4, AssetParametersd31648d1ddf3168166c543733439d89bfc721f0a19e78338afac49a9fa96f4b5S3VersionKeyB7A8C138, AssetParametersd31648d1ddf3168166c543733439d89bfc721f0a19e78338afac49a9fa96f4b5S3BucketA51A2111] do not exist in the template`
### Environment

  - **CDK CLI Version:** 1.21.1
  - **Module Version:** 1.20.0
  - **OS:** Mac
  - **Language:** Typescript

### Other information
Getting this issue If the lambda code is from the asset. If the lambda code is from inline code then deployed successfully. Below is the code:
`const testProps: FunctionProps = {
            runtime: lambda.Runtime.NODEJS_10_X,
            code: lambda.Code.fromAsset(path.join(__dirname, 'resources/test')), // This case throwing error
            //code: lambda.Code.fromInline('exports.handler = function(event, ctx, cb) { return cb(null, "hi"); }'),// This case deployed Successfully
            handler: "test.get",
            functionName: serviceName,
            description: 'Lambda-based HTTP Test service.'
        }
        const testLambda: lambda.Function = new lambda.Function(this, 'testService', testProps);`

**Comment by eladb** [comment]
How are you deploying this? Is this through `cdk deploy` or directly through cloudformation?

**Comment by eladb** [comment]
Please reopen if this is still relevant.

**Comment by bpcrao** [comment]
how is this solved? I am facing the same through CDK

**Comment by plenti-daniel-ho** [comment]
Same issue, any hints?

**Comment by bdastur** [comment]
The behavior I see is if you have a CDK app with multiple stacks and if one of the stack is using cfnParameters, you will need to deploy that stack individually like below:

cdk deploy Stack3 --parameters uploadBucketName=testbucket100

The usual cdk deploy --all wont work even if you pass parameters on the command line.

This is with CDK version 2.56.0 (build 1485f48)

**Comment by chubbard** [comment]
What's the deal with this bug?  Is anyone looking into it?  I'm encountering it as well.  Same issue as described.  I converted from single stack to multiple stacks where one of those stacks uses parameters and it will not deploy.  Works fine if I have a single stack.

**Comment by pavelBorisovZetta** [comment]
> The behavior I see is if you have a CDK app with multiple stacks and if one of the stack is using cfnParameters, you will need to deploy that stack individually like below:
> 
> cdk deploy Stack3 --parameters uploadBucketName=testbucket100
> 
> The usual cdk deploy --all wont work even if you pass parameters on the command line.
> 
> This is with CDK version 2.56.0 (build [1485f48](https://github.com/aws/aws-cdk/commit/1485f48c515f81fa585a325e02f1602f56443605))

This bug is still unresolved in CDK version 2.95.1

A workaround is to deploy the stack that uses the parameters separately with the **--exclusively** flag to bypass CDK automatically including dependency stacks.

However, this means that you have to separate your deployment process into "steps" as you can't do **cdk deploy --all** with the parameters.

Another workaround would be to restructure everything into one stack with multiple nested ones.
OR
Import the parameter(s) into all of your stacks (although they might not be needed there).

Alternatively, you can import your OS into your App file and utilize environment variables by passing them as arguments to the stack.

**Comment by vidhyasagarj-RP** [comment]
I am facing this issue when I export my aws amplify project and deploy with cdk. Any updates on this item.

**Comment by tkonsta** [comment]
For anyone running into this problem and ending up in this issue: 
We also had the issue and we could get rid of it by prepending the parameter name with the Stack name in which the parameter is used. This is described in detail in the CDK deploy docs https://docs.aws.amazon.com/cdk/v2/guide/ref-cli-cmd-deploy.html

So for example if during deployment three Stacks are being deployed, but the parameter is only used in StackA, then the command must be 
```
cdk deploy --parameters StackA:paramName=paramValue
```
