### ISSUE TITLE
Export ec2 instance id after creation in stack

### ISSUE THREAD

**Issue by RyanoftheDocuTapTribe** [aws/aws-cdk#6126]
### The Question

is there a way to export the EC2 instance of a newly created instance in a stack?

[2]: http://

### Environment

  - **CDK CLI Version:** 1.22.0
  - **Module Version:** <
  - **OS:**  [all ] 
  - **Language:**  [ TypeScript  ]

**Comment by rix0rrr** [comment]
We're happy to help you out, but GitHub issues is not a support forum. There are websites much better suited for that, such as StackOverflow.

Please ask that same question again on [StackOverflow under the aws-cdk](https://stackoverflow.com/questions/ask?tags=aws-cdk) tag. If you can't get a response to your question, please bring it to our attention again and we will do our best to answer it.
