### ISSUE TITLE
API Gateway's LambdaIntegration does not set permissions to allow me to use test invoke

### ISSUE THREAD

**Issue by andrewdibiasio6** [aws/aws-cdk#6127]
## Overview
The AwsIntegration, LambdaIntegration, does not set correct permissions on my backend lambda to allow me to test a method execution via API Gateway console even though I set the flag to true.

### Output of cdk deploy 
```
cdk deploy 
HelloCdkStack: deploying...
HelloCdkStack: creating CloudFormation changeset...

...edited...

 ✅  HelloCdkStack

Outputs:
HelloCdkStack.helloapi2EndpointFA0FEB4B = https://{end-point}

Stack ARN:
arn:aws:cloudformation:us-west-1:{account}:stack/HelloCdkStack/{edited}
```

### Lambda response when I hit URL directly in my browser is as expected
URL: https://{end-point}/v1
```
Hello, CDK! You've hit /v1
```

### Error Logs when I hit test button in API Gateway for /v1 - GET - Method Execution 
```
Execution log for request f6b4301a-15d6-4f4f-b25f-edd70c483f6a
Wed Feb 05 17:39:16 UTC 2020 : Starting execution for request: f6b4301a-15d6-4f4f-b25f-edd70c483f6a


... edited ...

Wed Feb 05 17:39:16 UTC 2020 : Endpoint request body after transformations: 

...edited...

Wed Feb 05 17:39:16 UTC 2020 : Execution failed due to configuration error: Invalid permissions on Lambda function
Wed Feb 05 17:39:16 UTC 2020 : Method completed with status: 500
```

### My stack .ts code:
```
import cdk = require('@aws-cdk/core');
import lambda = require('@aws-cdk/aws-lambda');
import apigw = require('@aws-cdk/aws-apigateway');
import { LambdaIntegration } from '@aws-cdk/aws-apigateway';

export class HelloCdkStack extends cdk.Stack {
  constructor(scope: cdk.App, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

     //#### Note: Content is not important, can just be hello world ####
    const test_func = new lambda.Function(this, 'my_func', {
      runtime: lambda.Runtime.NODEJS_10_X,
      handler: 'hello.handler',
      code: lambda.Code.fromAsset('lambda')
    });

    const api = new apigw.RestApi(this, 'hello-api-2', {});
    const resource = api.root.addResource('v1');

    //#### Note: A Simple Test, PROD code will use a lot more properties ####
    const integration = new LambdaIntegration(test_func, {
      proxy: true,
      ///### Set to true! 
      allowTestInvoke: true,
    });

    resource.addMethod('GET', integration, {
    });
  }
}

```
### Steps
1.) deploy this stack with any simple lambda you like
2.)  hit resource "/v1" on the deployed endpoint via a browser, you will see successful response from lambda. 
3.)  go to the API Gateway console and try to test " /v1 - GET - Method Execution " via the test button, it will fail. 

### Environment

  - **CLI Version:** 1.22.0 (build 309ac1b)
  - **Framework Version:** Type Script
  - **My OS:**  mac OS High Sierra 10.13.6
  - **Language:**  NodeJS for my lambda

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
I've tried reproducing this and the test invoke from the API Gateway console works just fine for me. The only difference between your code and mine is that, I have `Code.fromInline('exports.handler = async function(event, context) { return { "statusCode": 200, "body": "success" } }')` for the `code` property in the lambda function definition.

I'm about to call `curl //xxxxxxxxxx.execute-api.eu-west-1.amazonaws.com/prod/v1` as well as use the test invoke button on the API Gateway console; and both return status code 200 and a success response as expected.

**Comment by andrewdibiasio6** [comment]
Ok, hm, strange. If the way you define the lambda is the only difference, I will define mine like yours and see if that has any impact.  Also, does the name of the stage have any impact? I would assume not, but my stage is named prod.

**Comment by andrewdibiasio6** [comment]
And I assume we are using the same CLI version?

**Comment by nija-at** [comment]
@andrewdibiasio6 - yes correct. The CLI version should not matter here, but only the framework version. And the framework version I was used was 1.22.0`; also, nothing in this code area has changed in many versions.

**Comment by SomayaB** [comment]
Closing this issue since there hasn't been an update since our last response. Feel free to reopen if the issue hasn't been resolved on your end.
