### ISSUE TITLE
feat (assert) countResourcesLike helper method

### ISSUE THREAD

**Issue by substantial-kst** [aws/aws-cdk#6132]
Provide method `countResourcesLike` which returns a boolean value if the number of Resources with specified properties in a Stack matches the specified expected number.  Similar idea to existing `haveResourceLike` method where the matches for a given Type are filtered by their Properties values.

### Use Case

Stack w/ multiple API Gateway Resources is created with each having a single HTTP method (`"GET"`), and we want to test both:

1. ...that we have an "AWS::ApiGateway::Method" resource corresponding to a specific API Gateway `Resource`'s `resourceId` with a `HttpMethod` property value of "GET" (currently available via `haveResourceLike`)
2. ...and there is **only 1 Method defined** for that Resource (`countResources` is insufficient here as it will get the count for **all** "AWS::ApiGateway::Method" resources in the Stack)

### Proposed Solution

countResourcesLike(resourceType: string, count = 1, properties?: any)

### Other

* [X] :wave: I may be able to implement this feature request

---

This is a :rocket: Feature Request

**Comment by SomayaB** [comment]
Hi @substantial-kst, thanks for submitting a feature request and opening up a PR, much appreciated! 👍

**Comment by nwesoccer** [comment]
This `toCountResourcesLike` method is great!  However, can we get it added to the global jest matcher: https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/assert-internal/jest.ts?
