### ISSUE TITLE
[EKS] Set up node groups in their own stacks

### ISSUE THREAD

**Issue by bgdnlp** [aws/aws-cdk#6145]
More of a question than a feature request, not sure how well it applies to CDK.

With EKS, we'd like to have node groups set up as a different CloudFormation stack, the way eksctl sets it up.

### Use Case

It would make it easy to manage (delete) a node group without touching the CDK code. Keeping the master and node groups in separate CFN stacks would facilitate use cases where the configuration of nodes can be changed without risking touching the master. With or without using the CDK.

It makes much more sense in the context of managed node groups and Autoscaler, where the nodes are automatically discovered. For example, issuing a simple 'cdk destroy stack' would be enough to remove the nodes from the cluster.

However, I'm not sure if that's desired or if it make sense in the context of using CDK exclusively.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by eladb** [comment]
You should be able to define another CDK stack in your app and put the node groups in there. No?

**Comment by bgdnlp** [comment]
I did. I created two stacks, Cluster for the masters and NodeGroup for workers. But after synth the nodes were included in the Cluster stack and the NodeGroup stack was left with only metadata. 

I'd put the code here, but it's gone now. Decided to go with eksctl for unrelated reasons, S3 IP restrictions on our side.

**Comment by eladb** [comment]
Closing for now. Please reopen with your code if this is still of interest. Would love to help out.
