### ISSUE TITLE
Python package source code out of sync

### ISSUE THREAD

**Issue by jkpl** [aws/aws-cdk#6148]
In Python package `aws-cdk/core=1.22.0`, the docs for [Tag.add](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.core/Tag.html#aws_cdk.core.Tag.add) includes three mandatory parameters: `scope`, `key`, and `value`. When I download and use that package, it works as expected. However, the source code in the package contains another mandatory parameter called `cls`. This causes VS Code to show a error on missing parameter even though `cdk synth` accepts the code as is.

### Reproduction Steps

* Install CDK version 1.22.0
* Create a Python CDK project
* Create a virtualenv and install the dependencies
* Use `aws_cdk.core.Tag.add` with 3 parameters.
* Load the project in VS Code
* Load the virtualenv in VS Code

### Environment

  - **CLI Version      :** 1.22.0
  - **Framework Version:** 1.22.0
  - **OS               :** Linux
  - **Language         :** Python
--- 

This is :bug: Bug Report

**Comment by eladb** [comment]
Redirecting to @RomainMuller to triage as a jsii issue

**Comment by RomainMuller** [comment]
I guess this is because it's a class method. We'll have to look at whether annotations are missing that'll allow VSCode to interpret the declaration as intended...

**Comment by jkpl** [comment]
@RomainMuller That makes sense.
