### ISSUE TITLE
Spelling mistake - 4rd party => 3rd party

### ISSUE THREAD

**Issue by seawatts** [aws/aws-cdk#6152]
https://docs.aws.amazon.com/cdk/api/latest/docs/aws-iam-readme.html#configuring-an-externalid

This says `4rd` party but I'm pretty sure it should say `3rd` party 😄 

---

This is a 📕 documentation issue

**Comment by tuxinaut** [comment]
@seawatts looks like you could fix it by yourself :smile: 

https://github.com/aws/aws-cdk/blob/ea4ca3ea251e54921c39ee79f321cae2701837ad/packages/%40aws-cdk/aws-iam/README.md

**Comment by Jerry-AWS** [comment]
Just fixed this.  :-) @seawatts Thanks for flagging it!

**Comment by seawatts** [comment]
> @seawatts looks like you could fix it by yourself 😄
> 
> https://github.com/aws/aws-cdk/blob/ea4ca3ea251e54921c39ee79f321cae2701837ad/packages/%40aws-cdk/aws-iam/README.md

Ah, sorry didn't realize that was where it was coming from. Next time I will 😄
