### ISSUE TITLE
Differences between Clouformation & cdk elasticsearch CfnDomain

### ISSUE THREAD

**Issue by salam-seek** [aws/aws-cdk#6158]
Hi 👋 

I'm trying to add an update policy to my elasticsearch cfnDomain in order to add the `UpgradeElasticsearchVersion` option as per the following documentation : https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticsearch-domain.html#cfn-elasticsearch-domain-elasticsearchversion & https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-updatepolicy.html#cfn-attributes-updatepolicy-upgradeelasticsearchversion to enable smoother upgrades for version in my cluster via 

```json
"UpdatePolicy" : {
  "EnableVersionUpgrade" : Boolean
}
```

however, it seems that this option is not part of the `@aws-cdk/aws-elasticsearch.CfnDomain.cfnOptions.updatePolicy`

### Reproduction Steps

```typescript
var es = new elasticsearch.CfnDomain(scope, id, esProps)
es.cfnOptions.updatePolicy.EnableVersionUpgrade // << this property is not defined
```

### Environment

  - **CDK Version      :** 1.22.0 (build 309ac1b)
  - **OS               :** MacOS
  - **Language         :** Typescript
--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment]
Hi @salam-seek 

Thanks for reporting this. Looks like we are indeed missing this specific update policy. 

Stay tuned for the fix :)

P.S: If you feel you want to take a stab at contributing a fix here, you are more than welcome. We will of course provide support and guidance.

**Comment by iliapolo** [comment]
For self reference, we need to add this policy to the [`CfnUpdatePolicy`](https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/core/lib/cfn-resource-policy.ts#L104) interface:

```typescript
enableVersionUpgrade?: boolean;
```
