### ISSUE TITLE
getting error: Adding this dependency (${reason}) would create a cyclic reference.

### ISSUE THREAD

**Issue by rampatina** [aws/aws-cdk#6160]
### The Question
I was trying to add custom authorizer for the API gateway and getting below error:
```
/node_modules/@aws-cdk/core/lib/stack.ts:639
        throw new Error(`'${target.node.path}' depends on '${this.node.path}' (${cycle.join(', ')}). Adding this dependency (${reason}) would create a cyclic reference.`);
              ^
Error: 'xxx' depends on 'tokenizer' (xxx -> xxx/CustomVaildator/Resource.Ref). Adding this dependency (xxx -> xxx/x/x/Resource.Ref) would create a cyclic reference.
```
Below is the code snippet:

```
const auth = new apigw.TokenAuthorizer(this, 'customVaildator', {
      handler: handler <This handler contains lambda to use as custom authorizer>
});

const exampleGateway = new apigw.RestApi(this, 'customGateway', { });

const lambdaIntegration = new apigw.LambdaIntegration(lambdaHandler); // lambdaHandler is a lmbda
const version = this.exampleGateway.root.addResource('1.1');
const gateway =  version.addResource('test')
gateway.addMethod('POST', lambdaIntegration, { authorizer : auth });
```
### Environment

  - **CDK CLI Version:** 1.21.1
  - **Module Version:** 
  - **OS:** Mac
  - **Language:** Typescript

**Comment by nija-at** [comment]
It seems the error you're seeing is coming from elsewhere and not from the code that you have pointed at.

I wrote the following CDK app based on your sample and I can run `cdk synth` successfully -

```ts
#!/usr/bin/env node
import { App, Stack } from '@aws-cdk/core';
import { CfnUserPool } from '@aws-cdk/aws-cognito';
import { TokenAuthorizer, RestApi, LambdaIntegration } from '@aws-cdk/aws-apigateway';
import { Function, Code, Runtime } from '@aws-cdk/aws-lambda';

const app = new App();
const stack = new Stack(app, 'mystack');

const authhandler = new Function(stack, 'authfn', {
  code: Code.fromInline('foo'),
  handler: 'index.handler',
  runtime: Runtime.NODEJS_12_X,
});

const apihandler = new Function(stack, 'apifn', {
  code: Code.fromInline('foo'),
  handler: 'index.handler',
  runtime: Runtime.NODEJS_12_X,
});

const auth = new TokenAuthorizer(stack, 'customVaildator', {
  handler: authhandler
});

const exampleGateway = new RestApi(stack, 'customGateway');

const lambdaIntegration = new LambdaIntegration(apihandler);
const version = exampleGateway.root.addResource('1.1');
const gateway =  version.addResource('test')
gateway.addMethod('POST', lambdaIntegration, { authorizer : auth });
```

**Comment by rampatina** [comment]
I was trying with the scope 'this', like
const auth = new TokenAuthorizer(**this**, 'customVaildator', {
  handler: authhandler
});

**Comment by nija-at** [comment]
I'm not sure this is the difference. The first parameter of `TokenAuthorizer` needs to be a construct, typically, this is the `Stack`. 

If the `Stack` is modeled as a class and the authorizer is instantiated in the constructor, `this` will be the first parameter. If the `Stack` is simply instantiated (in the way I have in my code snippet), then the member assigned to it is passed as the first parameter.

Either the issue you're seeing is coming from somewhere in your code that you've not shared here.

Feel free to re-open when you have more information, and have sufficiently identified that there is a bug in the cdk.
