### ISSUE TITLE
sam.CfnApi does not wait for all resources

### ISSUE THREAD

**Issue by ayush987goyal** [aws/aws-cdk#6167]
The `CfnApi` resource from `@aws-cdk/aws-sam` does not wait for all the resources to finish. This leads to some issues where other resource, like BasePathMapping, that depend on ApiStage, gets deployed first and fails.

This might be related to https://github.com/awslabs/serverless-application-model/issues/313#

One solution for this can be to add `addDependsOn` to the `BasePathMapping` for the `ApiStage`. But `CfnApi` does not expose the `ApiStage` to the consumers and hence this cannot be done.

Is there any other alternatives/fix for this?

### Environment

  - **CLI Version      :** 1.22.0
  - **Framework Version:** 1.17.1
  - **OS               :**
  - **Language         :** TS

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
Hello @ayush987goyal -

Unfortunately, the CDK support for SAM is very basic and only has support for [low-level constructs](https://docs.aws.amazon.com/cdk/latest/guide/constructs.html#constructs_lib). Until we build a more comprehensive CDK coverage for SAM, the feature set available via the CDK is limited to what's available via SAM and CloudFormation.

You will have to reach out to either of these teams to resolve your issue.
