### ISSUE TITLE
How to set different tag values for different environments?

### ISSUE THREAD

**Issue by lohithsamaga** [aws/aws-cdk#6177]
## :question: General Issue

I am creating a cdk app in Java 1.8
I have three environments dev, uat and prod.
I have created yaml files which contain tag info as well as other data like database names, vpc ids, etc. These vary from dev to uat to prod.

In the cdk app, I create the same stack in dev, uat and prod.
All the variables are substituted correctly for each environment.
However, for Tags, it is always the values from the last environment that is picked up. 

When I synthesize a dev stack, I get the template correct with dev variables, but the tags are from uat (= the last) environment.

### The Question

How can we get appropriate tag values for each environment?
### Environment

  - **CDK CLI Version: 1.23.0**
  - **Module Version: 1.22.0**
  - **OS: Windows 10**
  - **Language: java 1.8.0_212**

**Comment by eladb** [comment]
We would need a code snippet to be able to help out here

**Comment by lohithsamaga** [comment]
Hi @eladb,


The sample code is below:

public class MyApp {
	
	private static App app;
	
	
	 private static MyStack makeMyStack(final String name,
			 MyProfile profile) {


     MyStack ms =  new MyStack(app, name, StackProps.builder()
	             .env(Environment.builder()
	                 .account(profile.getAwsAccountId())
	                 .region(profile.getRegion())
	                 .build())
	             .stackName(name)
	             .build());
	     
	     Tag.add(app, "Environment", profile.getEnvironment());
	     Tag.add(app, "AccountId", profile.getAwsAccountId());
	     
	     
	     return ms;
	 }
 
    public static void main(final String[] args) {
        app = new App();
        
        
        Profile devProfile = read profile file...
        MyStack devStack = makeMyStack("App-dev", devProfile);

        Profile uatProfile = read profile file...
        MyStack uatStack = makeMyStack("App-uat", uatProfile);

        app.synth();
    }
}
``

I hope this helps.
When I synthesize dev stack, the tags are from uat profile. In general, it is from the last profile in the main method.

**Comment by eladb** [comment]
You should add the tags on the stack and not on the app:

```java
Tag.add(ms, "Environment", profile.getEnvironment());
Tag.add(ms, "AccountId", profile.getAwsAccountId());
```

Reopen if this does not work.
