### ISSUE TITLE
Incorrect description for AWS-IAM Policy statements prop

### ISSUE THREAD

**Issue by boomary** [aws/aws-cdk#6180]
link to reference doc page: https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-iam.Policy.html#statements

describe your issue: The description for this "statements" prop might be incorrect. The description suggests that the "**addPermission**(statement)" method could be used to add permissions. However, the correct method should be "**addStatements**(...statement: PolicyStatement[])" instead. 

---

This is a 📕 documentation issue

**Comment by rix0rrr** [comment]
Good catch. The source is here: https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-iam/lib/policy.ts#L54

 If you would be so kind, could you click the edit button at the top-right of that screen and submit a PR fixing this?

**Comment by Chriscbr** [comment]
This issue can be closed per #6238.
