### ISSUE TITLE
ECS::FargateService assignPublicIp does not use subnet default

### ISSUE THREAD

**Issue by httpdigest** [aws/aws-cdk#6182]
I was investigating an issue where a ECS task could not fetch the Docker images of the containers and it was a networking issue caused by the Elastic Network Interface not having been given a public IP address even though the service was deployed to public subnets only and those were configured to auto-assign public IPv4 addresses.

The issue was then when using the ECS::FargateService without specifying the [assignPublicIp](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs.FargateService.html#assignpublicip) property in the [FargateServiceProps](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs.FargateServiceProps.html#assignpublicip) parameter, `cdk synthesize` will generate `AssignPublicIp: DISABLED` in the CloudFormation template and _will not_ use the subnet default (as advertized in the documentation).

### Environment
  - **CLI Version      :** none (deploying via aws-cdk on Windows)
  - **CDK Version      :** 1.23.0
  - **OS               :** Windows 10 x64
  - **Language         :** TypeScript

This is _either_ a :bug: or a documentation Bug Report, as the current implementation does not behave according to the documentation, which would either mean the documentation is wrong or the implementation is not according to the documentation.

EDIT: Looking at the CloudFormation documentation for [AWS::ECS::Service AwsVpcConfiguration](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-service-awsvpcconfiguration.html#cfn-ecs-service-awsvpcconfiguration-assignpublicip) for this property, it states here that the default is _not_ to use the subnet configuration, but the default instead is `DISABLED`. So this is likely a documentation issue on the side of CDK.

**Comment by iamhopaul123** [comment]
Hello @httpdigest, 

Just a recap: the current behavior for `AssignPublicIp` is `DISABLED`. However, it is supposed to be left blank instead. Is it a correct statement?

> ... it states here that the default is not to use the subnet configuration

Also, would you mind referring the link for this?

**Comment by httpdigest** [comment]
I've referenced everything in my initial post/comment to this issue.
1. The aws-cdk documentation of the [assignPublicIp](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs.FargateService.html#assignpublicip) property states:
> Type: boolean (optional, default: **Use subnet default.**)

2. The [AWS CloudFormation documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-service-awsvpcconfiguration.html#cfn-ecs-service-awsvpcconfiguration-assignpublicip) states:
> Whether the task's elastic network interface receives a public IP address. **The default value is DISABLED.**

**Comment by iamhopaul123** [comment]
I see your point. We should change the default value for cdk to "DISABLE" instead of "ENABLE" according to CFN doc.

**Comment by httpdigest** [comment]
> We should change the default value for cdk to "DISABLE"

Yes, please. Thanks!

> instead of "ENABLE" according to CFN doc.

No. Not "instead of ENABLE", but instead of "Use subnet default". It was never "ENABLE" in the aws-cdk docs, but wrongly "Use subnet default".

**Comment by iamhopaul123** [comment]
> No. Not "instead of ENABLE", but instead of "Use subnet default". It was never "ENABLE" in the aws-cdk docs, but wrongly "Use subnet default".

I think there seems to be a discrepancy between cdk doc and the implementation. By looking at the code it seems like `AssignPublicIp` by default is set to "ENABLED" instead of "using subnet default". https://github.com/aws/aws-cdk/blob/5c3a739ff39916f00281a1849a8fb0c0fda87807/packages/%40aws-cdk/aws-ecs/lib/base/base-service.ts#L606

**Comment by httpdigest** [comment]
No, by default it is set to 'DISABLE'. "By default" means 'if no value is provided'. And the ternary operator ?: selects 'ENABLED' only when the supplied `assignPublicIp` is truthy.

**Comment by iamhopaul123** [comment]
oh yeah my fault. nvm
