### ISSUE TITLE
EventBridge matcher support

### ISSUE THREAD

**Issue by jmnarloch** [aws/aws-cdk#6184]
EventBridge had release improved set of matchers for it's Pattern by end of 2019. This had been described in detail in [Blog post](https://aws.amazon.com/blogs/compute/reducing-custom-code-by-using-advanced-rules-in-amazon-eventbridge/) and [Documentation page](https://docs.aws.amazon.com/eventbridge/latest/userguide/content-filtering-with-event-patterns.html)

The current implementation of EventPattern needs to be changed to address it: https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-events/lib/event-pattern.ts#L30

The operators to be supported:
* Prefix
* AnythingBut
* Numeric
* Exists

### Use Case

The use case is to allow customer use the full capabilities of EventBridge pattern matching through CDK.

### Proposed Solution

This is to be discuss, I would like to expand the existing way using the union like structure that would convert the existing definition from i.e.:

```
readonly source?: string[]
```

into:

```
readonly source?: string[] | Prefix | AnythingBut | Exists | Numeric 
```

Providing the this can be supported by CDK transcompilation. 

### Other

* [X] :wave: I may be able to implement this feature request
* [X] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
We don't support unions in our transcompilation. We usually follow the pattern of a union-like class with static factory functions.

**Comment by jmnarloch** [comment]
The I don't see other way to support this without changing the types from 

```
readonly attribute?: string[]
```

into
 
```
readonly attribute?: object[]
```

In language like Java this is going to be backward compatible change as the array are covariant, though not sure about other cases.

**Comment by jogold** [comment]
Note that https://github.com/aws/aws-cdk/issues/5205 is still relevant here. For example, when using `[{ "exists": true }]` the generated template preserves the booleans but the CF deployment fails with `Reason: exists match pattern must be either true or false`...

**Comment by jogold** [comment]
https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/251#issuecomment-582284568

**Comment by ryanvade** [comment]
Apparently this works for now:
```typescript
source: [ { prefix: "your.prefix.here"} ] as any[]
```

**Comment by paul42** [comment]
is there a workaround for `{exists:` right now?

**Comment by rrhodes** [comment]
This issue appears to be resolved - I see the [linked CloudFormation issue](https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/251#issuecomment-582284568) is closed.

**Comment by davecap** [comment]
Is there a known workaround for CDK Python?

**Comment by niebloomj** [comment]
Does the request here change at all now that this is an open source library? https://aws.amazon.com/blogs/opensource/open-sourcing-event-ruler/

**Comment by MarkCaro** [comment]
Waiting for this to be implemented for Go as well.
Currently, you can't set the Prefix for `awsevents.EventPattern.Source` because its type is `*[]*string`.
This is a problem for statically-typed languages like Java and C# as well.

Having support for pattern matching for EventBridge in CDK will give users a lot of flexibility when routing events.

**Comment by otaviomacedo** [comment]
CDK now supports these matchers (see the [README]):

```ts
const rule = new events.Rule(this, 'rule', {
  eventPattern: {
    detail: {
      object: {
        // Matchers may appear at any level
        size: events.Match.greaterThan(1024),
      },

      // 'OR' condition
      'source-storage-class': events.Match.anyOf(
        events.Match.prefix("GLACIER"),
        events.Match.exactString('DEEP_ARCHIVE'),
      ),
    },

    // If you prefer, you can use a low level array of strings, as directly consumed by EventBridge
    source: ['aws.s3'],

    region: events.Match.anythingButPrefix('us-gov'),
  },
});
```

[README]: https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_events-readme.html#rule

**Comment by jvliwanag** [comment]
Might be missing something here. But the current change only supports matchers on the `detail` part, but not on the `source` part yet. In particular, we're still not able to create:

```
source: [ { prefix: "your.prefix.here"} ]
```

Should we re-open/create new issue?

**Comment by dominik-richter** [comment]
> Might be missing something here. But the current change only supports matchers on the `detail` part, but not on the `source` part yet. In particular, we're still not able to create:
> 
> ```
> source: [ { prefix: "your.prefix.here"} ]
> ```

For me, 
`source: events.Match.prefix(''),`
seems to work.
