### ISSUE TITLE
APIGW: logs role is still referenced after removal

### ISSUE THREAD

**Issue by richardhboyd** [aws/aws-cdk#6194]
If I deploy an API Gateway REST API, CDK will create an IAM Role for API Gateway to push logs to CloudWatch Logs and add this Role to API Gateway's settings. If I delete the Construct the Role is deleted but the reference is not removed from API Gateway which leads users to believe that there is a Role present that is pushing logs to CWL.

### Reproduction Steps
Deploy a RestApi()
Delete the RestApi()
Deploy a apigwv2.CfnApi()
Note the old Role name still present in the API Gateway console.

### Environment

  - **CLI Version      :**
  - **Framework Version:**
  - **OS               :**
  - **Language         :**

### Other

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
Hey Richard - 

This seems to be an issue with CloudFormation and APIGateway. They don't seem to be honouring deletion of the `AWS::ApiGateway::Account` resource. 

Internal tracking: t.corp/D15330883

**Comment by richardhboyd** [comment]
Cool. thanks for looking into this.

**Comment by 404unf** [comment]
Still seeing this issue. Is there a workaround for this issue?

**Comment by 404unf** [comment]
I was able to workaround this issue by going to API Gateway console > Settings > Logging > Edit.
Updated the IAM role to a blank string.
