### ISSUE TITLE
testing for cfnspec module generation

### ISSUE THREAD

**Issue by nija-at** [aws/aws-cdk#6198]
Over time, we have built up a lot of logic in our `cfnspec` updates - https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/cfnspec/build-tools. However, it has no testing in place.

We should bridge that gap with any necessary refactor and, unit and integration tests.

**Comment by eladb** [comment]
I would argue we have sufficient "implicit tests" for this and the unit test coverage gap is a very low risk, but I would love to hear about any use cases where a unit test would have helped us catch an issue.

**Comment by eladb** [comment]
Closing for now. @nija-at please reopen if you think we need this.
