### ISSUE TITLE
CodeBuild badge not supported with CodeCommit repositories

### ISSUE THREAD

**Issue by sahilpalvia** [aws/aws-cdk#6205]
### Reproduction Steps

* While trying to enable the badge option with AWS CodeCommit repo, the CDK fails reporting badge is not supported.
* Badge is supported with CodeBuild and CodeCommit repositories. Sample CFN template: https://github.com/aws-samples/aws-codecommit-pull-request-approver-demo/blob/master/template.yaml

```typescript
const projectProps = {
    projectName: 'BuildProject',
    description: 'Sample build',
    source: codebuild.Source.codeCommit({<REPOSITORY>}),
    role: "<ROLE>",
    badge: true,
    environment: {
        buildImage: codebuild.LinuxBuildImage.AMAZON_LINUX_2_2,
        computeType: ComputeType.SMALL,
        privileged: true
    }
};

const codebuildProject = new codebuild.Project(this, "CodeBuildProject", projectProps);

```

### Error Log

```bash
$ cdk list
Badge is not supported for source type CODECOMMIT
Subprocess exited with error 1

```

### Environment

  - **CLI Version      : 1.23.0 (build 01f326e)**
  - **Framework Version: 1.22.0**
  - **OS               : MacOS High Sierra**
  - **Language         : Typescript**

### Other

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Thanks for reporting the issue @sahilpalvia . Fix is in https://github.com/aws/aws-cdk/pull/6211.
