### ISSUE TITLE
Instances property on DatabaseCluster is not working as expected

### ISSUE THREAD

**Issue by kalva1kk** [aws/aws-cdk#6214]
I'm creating Database Cluster using "DatabaseCluster" class, I would like to have only primary instance but a reader instance. I set "Insances" value both 0 and 1, in both cases read replica is getting created

### Environment

  - **CLI Version      :** 1.16.309
  - **Framework Version:** 1.21.1
  - **OS               :** Windows 10
  - **Language         :** C#

### Other

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
Please provide more information by providing 
1. a sample of the code that you're using that's causing this problem, 
2. a snippet of the CloudFormation template that CDK generates that contains the invalid or missing value, as well as, what the correct value should be.
