### ISSUE TITLE
Create/deploy child stack without deploying dependencies

### ISSUE THREAD

**Issue by lohithsamaga** [aws/aws-cdk#6215]
## :question: General Issue
I have a stack, say, app-stack, that depends on another stack, say, core-stack, which is already deployed by another team. I need to reference the core-stack in app-stack to add managed policies in app-stack to group created in core-stack.
If I use app-stack.addDependency(core-stack), core-stack's contents will also be listed for deployment which is not needed.

### The Question
How can we deploy only child stack?

### Environment

  - **CDK CLI Version:** 
  - **Module Version:** 
  - **OS:** 
  - **Language:**

**Comment by eladb** [comment]
You can use `cdk deploy --exclusively` is you wish to deploy only a stack without it's deps.
