### ISSUE TITLE
CLI: don’t attempt to update stack if template didn’t change

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#6216]
We should add “short circuit” feature to the CLI which will skip change set creation and execution if the currently deployed template is identical to the one we are we’re requested to deploy.

### Use Case

This will improve the user experience and will address two issues :

1. #6046: where nested stacks cause an update even if they haven’t changed. CloudFormation currently attempts to update nested stacks even if their template haven’t changed. This is because theoretically CFN can’t tell if the template had changed or not, but CDK nested stack templates are immutable and therefore if the URL didn’t change, we know for sure that an update is not needed.

2. #2553: creating a change set with no updates fails.

### Proposed Solution

We should make this the default behavior but allow people to disable through something like `--force`

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by eladb** [comment]
@shivlaks I am picking this up

**Comment by jmrtinb** [comment]
Is there any reason the output regarding how to override (using the --force flag) is printed only at debug? I just spent quite a while trying to figure out some stacks weren't deploying (they used SSM parameters, so the *template* doesn't change, but if the parameter values change the stack needs to be updated), and this was the cause. It would have been much easier to debug what was going on if there was an output along with "no changes" stating *why* cdk thought there were no changes.
