### ISSUE TITLE
Get Default Security Group of Nat Provider

### ISSUE THREAD

**Issue by processmaker-cloudops** [aws/aws-cdk#6224]
## Get Default Security Group of Nat Provider
Hi guys i have the next code
```typescript
    const natGatewayProvider = ec2.NatProvider.instance({
      instanceType: new ec2.InstanceType('t3.micro'),
      keyName: 'Ubuntu-KP'
    });

    const vpc = new ec2.Vpc(this, 'DEV_VPC', {
      cidr: '10.0.0.0/26',
      maxAzs: 1,
      subnetConfiguration:[
        {
          subnetType: ec2.SubnetType.PUBLIC,
          name: 'NAT',
          cidrMask: 28
        },
        {
          subnetType: ec2.SubnetType.PRIVATE,
          name: 'WEB',
          cidrMask: 28
        }
      ],
      natGatewayProvider,
      natGateways:1,
    });
    Tag.add(vpc, 'Name', 'Development VPC');
```
So I want to get the security group of Nat Instance to modify its rules
Regards

**Comment by rix0rrr** [comment]
We're happy to help you out, but GitHub issues is not a support forum. There are websites much better suited for that, such as StackOverflow.

Please ask that same question again on [StackOverflow under the aws-cdk](https://stackoverflow.com/questions/ask?tags=aws-cdk) tag. If you can't get a response to your question, please bring it to our attention again and we will do our best to answer it.
