### ISSUE TITLE
AppSync: support conditions in DynamoDB PutItem

### ISSUE THREAD

**Issue by duarten** [aws/aws-cdk#6226]
Currently the PutItem mapping template doesn't support conditions.

### Use Case

Conditionally writing to DynamoDB.

### Proposed Solution

Provide a hierarchy based on KeyCondition to allow specifying conditions on PutItem.

### Other

* [X] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by danielmatuki** [comment]
Hi @MrArnoldPalmer @SomayaB I'm available to help with this if it is still open. Thanks.

**Comment by MrArnoldPalmer** [comment]
Go for it @danielmatuki !!

**Comment by duarten** [comment]
@danielmatuki In case it helps, here's my implementation for it: https://github.com/umani/ribosome/blob/main/src/dynamo/dynamo-conditions.ts

**Comment by danielmatuki** [comment]
Thanks @MrArnoldPalmer and @duarten yes I will check the implementation for reference.
