### ISSUE TITLE
Enable cross stack (native object) exports even when they are not used

### ISSUE THREAD

**Issue by michaelwiles** [aws/aws-cdk#6228]
I have parent stack and two child stacks, let's call them A and B.

The parent stack "exports" (via object references) resources for child A.

Then I want to build B, it references the parent stack but does not use any of the exported dependencies of A.

When I deploy this child (B) stack it tries deploys the dependent parent stack but because the child stack does not use the exported value it tries to delete the exported value. This of course fails because it is in use in stack A (the other child stack).

I would appreciate a mechanism to mark a property as an "exported one" so that even if it is not used by a child stack it is still exported.

### Use Case

Doing this will enable me to have a parent stack that has two children... The parent stack contains the shared infrastructure without any changes in deployment mechanisms (the workaround is to do an exclusive deployment of B)

Unless I actually use the exported values in the children stack, cdk wants to remove the exported values.

### Proposed Solution

Ideally I would like to be able to mark a field as an "exported value" thus ensuring that it is exported always (even if it's not used). I don't think I can manually export it (via a CfnOutput) as that would conflict with the preferred "native" approach.
### References
See https://github.com/aws-samples/aws-cdk-examples/tree/master/python/cross-stack-resources/native-objects for an example of how I do this cross stack referencing.

**Comment by richardhboyd** [comment]
Are all three stacks in the same CDK App?

**Comment by michaelwiles** [comment]
They are part of the same application but not deployed as the same CDK app.

In once instance we deploy the parent stack and child A and the other we deploy parent stack and child B.

child A and B are separate "components" but they both require the constructs provided in the parent stack. Parent stack creates the topics and child apps register against the topics.

**Comment by madshargreave** [comment]
I'm encountering the same problem. 

@michaelwiles have you found a work-around?

**Comment by michaelwiles** [comment]
The obvious work around is to do an exclusive deploy of the child stack... that implies that you don't try and deploy the parent stack - when you do this it won't try and delete the dependencies exported by the parent stack.

**Comment by NGL321** [comment]
Bumping this for attention as it is related to internal request.

**Comment by s-maheshbabu** [comment]
Looks like this was closed for staleness without an actual resolution. Is there a solution for this problem now?
