### ISSUE TITLE
AppSync: support for additional authorization modes

### ISSUE THREAD

**Issue by duarten** [aws/aws-cdk#6247]
Currently the AppSync L2 constructs don't provide a way to configure additional authorization modes.

### Use Case

For example, configuring a GraphQL API with user pool authorization doesn't allow unauthenticated access, and one way to solve that without splitting the API is to add an additional authorization mode.

### Other

* [X] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by interrobrian** [comment]
I have this problem, but I need to use the OPENID_CONNECT authenticationType.
