### ISSUE TITLE
elbv2: ALB listener rule supports path-routing condition with multiple values(up to 5 currently)

### ISSUE THREAD

**Issue by zxkane** [aws/aws-cdk#6251]
ALB listener rule currently supports [path-routing condition](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticloadbalancingv2-listenerrule-pathpatternconfig.html) that is allowed up to 5 rules.

Currently the high level [construct API **ApplicationListener. addTargets()**](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-elasticloadbalancingv2.AddApplicationTargetsProps.html#pathpattern) only supports specifying one path rule for each listener rule.

[Host Conditions](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticloadbalancingv2-listenerrule-hostheaderconfig.html) also has same limitation.
### Use Case

Fully support the capability of ALB listener rule

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment]
Why will this be a breaking change? Will the API need to change?

**Comment by zxkane** [comment]
You're right. Just add a new array priority for backward compatibility.

**Comment by rix0rrr** [comment]
Already implemented
