### ISSUE TITLE
CfnReplicationGroup snapshot configuration failure

### ISSUE THREAD

**Issue by TiltedTower** [aws/aws-cdk#6256]
While using the CDK (Typescript), we are having trouble setting up snapshotting for our replication group.  The [documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticache-replicationgroup.html#cfn-elasticache-replicationgroup-snapshottingclusterid) mentions how we can't specify a `SnapshottingClusterId` for replication groups, but when we set the `SnapshotRetentionLimit`, it errors out with an `InvalidParameterCombination`.

### Reproduction Steps

This is the template we're using to create a replicationGroup:

```
new elasticache.CfnReplicationGroup(stack, 'replication-group', {
      replicationGroupDescription: 'Redis replication group decription',
      atRestEncryptionEnabled: true,
      numCacheClusters: 2,
      cacheNodeType: 'cache.t2.micro',
      engine: 'redis',
      port: 5555,
      transitEncryptionEnabled: true,
      snapshotRetentionLimit: 2
})
```

### Error Log

```Must specify both SnapshotRetentionLimit and SnapshottingClusterId to turn on snapshots (Service: AmazonElastiCache; Status Code: 400; Error Code: InvalidParameterCombination```

### Environment

  - **CLI Version      :  1.23**
  - **Language         :  Typescript**

### Other

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment]
Hi @TiltedTower 

Notice that the [documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticache-replicationgroup.html#cfn-elasticache-replicationgroup-snapshottingclusterid) states that `SnapshottingClusterId` cannot be set **only for cluster enabled** redis replication groups. 

The default (which is what you are using based on the code snippet), is *cluster mode disabled*, which requires the `SnapshottingClusterId` to turn snapshotting on.

You can use *cluster mode enabled* by setting a different [`CacheParamaterGroupName`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticache-replicationgroup.html#cfn-elasticache-replicationgroup-cacheparametergroupname), in which case, you will not to set `SnapshottingClusterId`

**Comment by iliapolo** [comment]
Hi @TiltedTower 

Any updates on this? Did you manage to get to a working setup?

**Comment by TiltedTower** [comment]
Yes, I was able to get a working setup by creating/specifying a parameter group and omitting the snapshotting cluster id.  Thanks for the help.
