### ISSUE TITLE
Support Method-Chaining e.g. on ContainerDefinition

### ISSUE THREAD

**Issue by konstantinj** [aws/aws-cdk#6266]
Currently all methods e.g. on ContainerDefinition return void. It would be nice if you would support method chaining on those constructs where many settings need to be made.

### Use Case
```typescript
container.addUlimits({
    name: UlimitName.NOFILE,
    softLimit: 16384,
    hardLimit: 16384,
})

container.addPortMappings({
    containerPort: 80,
})

container.addPortMappings({
    containerPort: 22,
})

container.addMountPoints({
    sourceVolume: this.stackName,
    containerPath: '/data',
    readOnly: false,
})
```
### Proposed Solution
```typescript
container.addUlimits({
    name: UlimitName.NOFILE,
    softLimit: 16384,
    hardLimit: 16384,
})
.addPortMappings({
    containerPort: 80,
})
.addPortMappings({
    containerPort: 22,
})
.addMountPoints({
    sourceVolume: this.stackName,
    containerPath: '/data',
    readOnly: false,
})
```
* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by pkandasamy91** [comment]
@konstantinj, I'm not really seeing the added benefit of changing methods to be invoked this way. This would remove the clarity of specifically what construct is being invoked. I don't think this is something we would want to do, as it would only make sense if it was done everywhere else in the CDK. 

@rix0rrr let me know if you disagree?

**Comment by rix0rrr** [comment]
We generally don't do fluent interfaces, so correct, I would also not recommend this.

**Comment by pkandasamy91** [comment]
Resolving this as something we don't plan to fix. Feel free to reopen if you have any more questions about this.
