### ISSUE TITLE
Route53 A/AAAA Alias Record to ELB does not use "dualstack" prefix

### ISSUE THREAD

**Issue by httpdigest** [aws/aws-cdk#6271]
When creating an ALIAS A/AAAA record in Route53 pointing to an ELB on the Web Console, the name will always have a "dualstack" prefix, as also suggested by the AWS documentation: https://aws.amazon.com/de/premiumsupport/knowledge-center/alias-resource-record-set-route53-cli/
> If you're pointing to an Elastic Load Balancer, always include dualstack in the value for the DNSName key-value pair of the JSON file.

This ensures that both IPv4 _and_ IPv6 addresses are solved.

However, a CDK ARecord as well as a AaaaRecord with a LoadBalancerTarget will not add this "dualstack" prefix.

### Reproduction Steps
```typescript
import * as route53 from '@aws-cdk/aws-route53';
import * as route53targets from '@aws-cdk/aws-route53-targets';
...
const elbZoneAAAARecord = new route53.AaaaRecord(this, 'ElbAaaaRecord', {
  zone: zone,
  target: route53.RecordTarget.fromAlias(new route53targets.LoadBalancerTarget(elb)),
});
```
When looking at Route53 record in the the Web Console, the record will not have the "dualstack" prefix.

### Environment

  - **CLI Version      :** 1.23.0 (build 01f326e)
  - **Framework Version:** 1.23.0 (build 01f326e)
  - **OS               :** Windows 10 x64
  - **Language         :** typescript

This is :bug: Bug Report

**Comment by shivlaks** [comment]
@httpdigest is it just the `prefix` that needs to be `dualstack` or anywhere in the value? The documentation snippet is a little confusing here. But as i understand it, doing it from the console results in `dualstack` as the prefix.

**Comment by httpdigest** [comment]
I think the documentation is pretty clear about "dualstack" being a simple prefix to the DNS name of the ELB, as per the example:
> For example, if your load balancer's Amazon-provided DNS name is ALB-xxxxxxxx.us-west-2.elb.amazonaws.com, use:
> "DNSName": "dualstack.ALB-xxxxxxxx.us-west-2.elb.amazonaws.com"

**Comment by shivlaks** [comment]
> I think the documentation is pretty clear about "dualstack" being a simple prefix to the DNS name of the ELB, as per the example:
> 
> > For example, if your load balancer's Amazon-provided DNS name is ALB-xxxxxxxx.us-west-2.elb.amazonaws.com, use:
> > "DNSName": "dualstack.ALB-xxxxxxxx.us-west-2.elb.amazonaws.com"

okay, i was thinking it could be anywhere in the value based on the phrasing of
> If you're pointing to an Elastic Load Balancer, always include dualstack in the value for the DNSName key-value pair of the JSON file.

**Comment by erikdebruin** [comment]
Is this issue being addressed? I can successfully create a DNS recordset (alias) to a LB, but the value doesn't include the 'dualstack.' prefix. Manually adding the prefix fixed the recordset. 

Is there a workaround I can use while waiting for the framework to be fixed?
