### ISSUE TITLE
Vpc.fromVpcAttributes throws Validation exception from ec2 construct

### ISSUE THREAD

**Issue by ayush987goyal** [aws/aws-cdk#6289]
When I import an existing VPC using this 
```ts
const vpc = ec2.Vpc.fromVpcAttributes(this, 'Vpc', {
      vpcId: cdk.Fn.importValue('VPC'),
      availabilityZones: cdk.Fn.getAzs(),
      privateSubnetIds: [1, 2, 3].map(i => cdk.Fn.importValue(`PrivateSubnet0${i}`)),
      publicSubnetIds: [1, 2, 3].map(i => cdk.Fn.importValue(`PublicSubnet0${i}`))
});
```
I get the following error while synthesis:
```
There is already a Construct with name 'undefinedSubnet2' in ImportedVpc [Vpc]

/node_modules/@aws-cdk/core/lib/construct.ts:48
        throw new Error(`Validation failed with the following errors:\n  ${errorList}`);
              ^

```

What is the correct way to resolve this problem?

### Environment

  - **CLI Version      :*1.22.0*
  - **Framework Version:*1.23.0*
  - **OS               :**
  - **Language         :*TS*

### Other

--- 

This is :bug: Bug Report

**Comment by richardhboyd** [comment]
Are you exporting PrivateSubnet01, PrivateSubnet02, PrivateSubnet03, PublicSubnet01, PublicSubnet02, and PublicSubnet03 from other stacks in the same Account and Region?

**Comment by ayush987goyal** [comment]
Yes these are exported from another stack in the same account and region.
On the same note, private and public subnets are not required parameters but cdk won't synthesize unless I pass them. Is that also expected?

**Comment by rix0rrr** [comment]
I think the issue is that you are using an array import. The following works:

```ts
      availabilityZones: [0, 1, 2].map(i => cdk.Fn.select(i, cdk.Fn.getAzs())),
```

**Comment by ayush987goyal** [comment]
Hi,

I tried the above implementation but I am not getting another error related to the same:

```
Cannot determine scope for context provider hosted-zone.
This usually happens when one or more of the provider props have unresolved tokens
```

The current implementation I have is
```ts
const vpc = ec2.Vpc.fromVpcAttributes(this, 'Vpc', {
      vpcId: cdk.Fn.importValue('VPC'),
      availabilityZones: [0, 1, 2].map(i => cdk.Fn.select(i, cdk.Fn.getAzs('us-east-1'))),
      privateSubnetIds: [1, 2, 3].map(i => cdk.Fn.importValue(`PrivateSubnet0${i}`)),
      publicSubnetIds: [1, 2, 3].map(i => cdk.Fn.importValue(`PublicSubnet0${i}`))
});
```

**Comment by rix0rrr** [comment]
Fairly sure that this has nothing to do with your VPC, given that the error message says "context provider hosted-zone". You are probably doing `HostedZone.fromLookup(Fn.importValue(...))` or similar.

That won't work because `fromLookup()` is evaluated by CDK and `Fn.importValue()` is evaluated by CFN (which happens later in time, so `fromLookup()` can never use the actual value CFN would have imported).

See here for an explanation: https://docs.aws.amazon.com/cdk/latest/guide/apps.html#lifecycle

You need concrete parameters, not `Fn.importValues()`.
