### ISSUE TITLE
aws-s3-deployment: CacheControl.sMaxAge(t) returns wrong value

### ISSUE THREAD

**Issue by d2kx** [aws/aws-cdk#6292]
### Reproduction Steps
```ts
const deployment = new BucketDeployment(this, "BucketDeployment", {
  cacheControl: [
    CacheControl.setPublic(),
    CacheControl.maxAge(cdk.Duration.seconds(0)),
    CacheControl.sMaxAge(cdk.Duration.days(365))
  ]
});

// Cache-Control: 'public, max-age=0, s-max-age=31536000'
```

### Error Log

CacheControl.sMaxAge(t) returns `s-max-age=<t>`, which gets ignored by CloudFront & everyone else.

It should have been `s-maxage=<t>`, without the '-' in between 'max age'. See below.

### Environment

  - **CLI Version      :** 1.24.0
  - **Framework Version:** 1.24.0
  - **OS               :** Windows 10
  - **Language         :** German

### Other

This is regarding `aws-s3-deployment`: `CacheControl.sMaxAge(t)`, see [CDK API Doc](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-s3-deployment.CacheControl.html#static-s-wbr-max-wbr-aget-span-class-api-icon-api-icon-experimental-title-this-api-element-is-experimental-it-may-change-without-notice-span)

I am not too surprised about this issue, since the Cache-Control standard is a bit weird/inconsistent, because it is `max-age` with a '-' on the browser side, but `s-maxage` without a '-' for the proxy side. `s-max-age` as it is being set by CacheControl.sMaxAge(t) is being ignored by CloudFront and other web servers, as it doesn't exist.

It can currently be worked around by doing `CacheControl.fromString('s-maxage=<t>')`.

See
[Cache-Control, MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control)
[Cache-Control, AWS CloudFront documentation](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Expiration.html)

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
This also needs to be fixed in the [`S3DeployAction` in the `@aws-cdk/aws-codepipeline` module](https://github.com/aws/aws-cdk/blob/ea272fa270fd7dc09e0388a90e82bfb27a88491f/packages/%40aws-cdk/aws-codepipeline-actions/lib/s3/deploy-action.ts#L35-L35).
