### ISSUE TITLE
CDK automated zip creation of Lambda function with custom library dependencies

### ISSUE THREAD

**Issue by randude** [aws/aws-cdk#6294]
### Use Case
AWS CDK currently supports 3 kinds of "Assets":

* [InlineCode](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-lambda.InlineCode.html) - useful for one-line-lambdas
* [AssetCode](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-lambda.AssetCode.html) - one-file lambdas without dependencies
* [S3Code](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-lambda.S3Code.html) - existing lambda packages already uploaded in an S3 bucket

There is, however, no support for more complex lambda function which require third party dependencies.
So, in this case I need to zip by **myself** my Lambda function with all it's custom libraries. 
However, I'm also working with **Chalice**, and there they solved that issue by automating the zip creation (which is awesome!).

While doing research on the matter, I stumbled across this:
 https://gitlab.com/josef.stach/aws-cdk-lambda-asset
This great guy solved the matter in less than 150 lines by creating a new construct which creates a zip for you from your lambda and adds only the custom libraries (he doesn't add the aws libraries).

I think it would benefit the community a lot if CDK took the same approach as Chalice in the matter and formalized this process, instead of having each developers add a few steps per Lambda function to the build process in their projects. It would be more native and easier to maintain.

Another bonus here is that his solution allows to keep track of dependencies and version control since you have a requirements.txt file.

### Proposed Solution

Implement a new construct which works in the same matter this guy wrote:
 https://gitlab.com/josef.stach/aws-cdk-lambda-asset

He described his solution as such:
```python
CDK AssetCode which builds lambda function and produces a ZIP file with dependencies.
    Lambda function is built either in Docker or natively when running on Linux.

There is, however, no support for more complex lambda function which require third party dependencies.
This repository presents one possible approach to lambda packaging.
The construct is aware of libraries bundled in the AWS lambda runtime and automatically removes those for you to save space.
It also counts with compiled C dependencies such as NumPy and takes care of library stripping.
```

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by yoslev** [comment]
Required

**Comment by eladb** [comment]
Hey @randude, this is definitely something we are interested in. @jogold had recently added @aws-cdk/aws-lambda-nodejs with a `NodeJsFunction` construct that automatically creates bundles for Node.js functions. Would you be interested in working on a @aws-cdk/aws-lambda-python?

**Comment by risenberg-cyberark** [comment]
Hi @eladb,
Yeah, this sounds great. Could you point me to some tips/tutorial on how to contribute to your project?
Could you also point me to the  NodeJsFunction source or requirements so I know what is required of the solution?

**Comment by risenberg-cyberark** [comment]
Hey @eladb  and @jogold , could you give me some pointers as to the requirements here? 
I noticed that NodeJsFunction uses a tool called Parcel which I'm not entirely sure is the right fit for general python modules. Do you think it's better to use Poetry for Python in this case?

**Comment by eladb** [comment]
See https://github.com/aws/aws-cdk-rfcs/issues/7#issuecomment-590060873 for some discussion

**Comment by risenberg-cyberark** [comment]
@eladb , Hey, I commented on the other discussion. 
However, I'd like to get a better understanding of the time frame here and whether my help is required here at all. What do you think the time frame for python lambda assets will be? 
Is my help still required?

**Comment by apalumbo** [comment]
@eladb Would you be interested to an alternate implementation for NodeJs, I've seen that the construct use parcel that unfortunately does not support tree-shaking

**Comment by davidaam** [comment]
This is obviously not an ideal solution, but if you are looking for a workaround for Typescript CDK, you can loop through your assets in cdk,out directory and install the dependencies after synthesizing the CDK App. Something like this:

```typescript
import cdk = require('@aws-cdk/core');
import cxApi = require('@aws-cdk/cx-api');
import path = require('path');
import fs = require('fs');
import { exec } from 'child_process';

function buildLambdas(cloudAssembly: cxApi.CloudAssembly) {
    const cdkOutDir = path.join(__dirname, 'cdk.out');
    const stackArtifacts = cloudAssembly.stacks[0].assets
        .map(asset => asset.path)
        .map(asset => path.join(cdkOutDir, asset))
        .filter(dir => fs.readdirSync(dir, { withFileTypes: true }).find(file => file.name == "requirements.txt"))
        .map(dir => exec(`cd ${dir} && pip install -r requirements.txt --target .`));
}

const app = new cdk.App();
....
const cloudAssembly = app.synth();
buildLambdas(cloudAssembly);
```

**Note:** you may want to install the dependencies in a Docker container if you are not on Linux (similar to what sam build --use-container does).

**Comment by w2fong** [comment]
Here is a simple solution I found.  First I created a top-level directory to store all my lambda functions.  Second, I added package.json with some quick scripts which allow me to install npm modules for all my lambdas store at a top-level lambda directory.  I then use the "aws-s3-assets" to manage and upload the lambda bundle and this easily worked with lambda.Code.fromBucket.

`
import * as cdk from '@aws-cdk/core';
import * as lambda from '@aws-cdk/aws-lambda';
import * as assets from '@aws-cdk/aws-s3-assets';
import * as path from 'path';

export class CdkStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const myLambdaAsset = new assets.Asset(this, 'lambda.zip', {
      path: path.join(__dirname, '..', '..', 'lambda', 'myLambdaFunction'),
    });

    const myLambdaFunction = new lambda.Function(this, 'myLambdaFunction', {
      code: lambda.Code.fromBucket(myLambdaAsset.bucket, myLambdaAsset.s3ObjectKey),
      runtime: lambda.Runtime.NODEJS_12_X,
      handler: 'index.handler',
    });

  }
}
`

**Comment by eladb** [comment]
This is going to be addressed using https://github.com/aws/aws-cdk/pull/7898

**Comment by eladb** [comment]
Closing, let us know if NodejsFunction solves your issue

**Comment by esteban-uo** [comment]
#7898 relies on docker and its for nodejs, why closing it? seems to be for now the best solution is using what josef.stach created.

**Comment by esteban-uo** [comment]
I just published a simple example to deal with it, hope it helps someone else https://github.com/esteban-uo/aws-cdk-python-application-dependencies (based on https://stackoverflow.com/a/61248003)

**Comment by bingtimren** [comment]
> Hey @randude, this is definitely something we are interested in. @jogold had recently added @aws-cdk/aws-lambda-nodejs with a `NodeJsFunction` construct that automatically creates bundles for Node.js functions. Would you be interested in working on a @aws-cdk/aws-lambda-python?

Just did some experiment with this solution and the result is pretty good. Report here:

(1) Document link: 

https://docs.aws.amazon.com/cdk/api/latest/docs/aws-lambda-nodejs-readme.html

(2) My project

My experiment project is in a @microsoft/rush monorepo. The lambda is written in Typescript and uses two packages. One is a normal package installed from npm public registry. The other is a package inside the monorepo and is never published. The packages are installed by `rush update` command in node_modules dir as symbol-links. 

(3) Experiment 1 - docker build
```ts

import * as core from "@aws-cdk/core";
import * as apigateway from "@aws-cdk/aws-apigateway";
import * as lambda from "@aws-cdk/aws-lambda-nodejs";

export class GreetingService extends core.Construct {
  constructor(scope: core.Construct, id: string) {
    super(scope, id);

    const handler = new lambda.NodejsFunction(this, "GreetingHandler", {
      entry: 'resources/lambdas/greeting.ts',
      handler: 'greeting'
    })

    // ...... API Gateway integration ......
  }
}

```
`cdk synth` fails in this experiment. The message reports "esbuild cannot run locally. Switching to Docker bundling.". However docker bundling is slow in the first run (download the images) and could not resolve both the packages used by lambda.

(4) Experiment 2 - esbuild

The document states that "If esbuild is available it will be used to bundle your code in your environment". So I installed esbuild with command `rush add -p esbuild@0` and then everything worked.

Conclusion:

- NodejsFunction works
- Lambda building is slow and cannot handle the symbol linked libraries in my monorepo
- local esbuild is fast, and works well with the monorepo
- the local esbuild can handle Typescript directly, no need to compile Typescript into Javascript first
- This API is still experimental, though. So use with care.
