### ISSUE TITLE
cdk.json does not respect ".." on Windows

### ISSUE THREAD

**Issue by sashasochka** [aws/aws-cdk#6296]
`cdk.json`:

```
{
  "app": "../gradlew run"
}
```

Running results in 

```
'..' is not recognized as an internal or external command,
operable program or batch file.
```

On Windows 10. Running on Linux works OK. If you replace forward with back slash, everything works perfectly.

Seems like CDK does not respect parent directories on Windows

**Comment by ldavison-sg** [comment]
It would be good if cdk could handle cross-platform gradlew executions. As it stands,

```json
{ "app" : "./gradlew run"
}
```
Will not work on Windows. And:
```json
{ "app" : "gradlew run"
}
```
Will not work on Linux.
Which means that I can't use the same cdk.json file for both Windows and Linux based deployments, for instance developing on Windows but deploying through Github Actions on a Linux runner.
