### ISSUE TITLE
Lambda Ruby Runtime doesn't Support ZipFile

### ISSUE THREAD

**Issue by skorfmann** [aws/aws-cdk#6302]
This implies that the Lambda Ruby runtime supports `ZipFile` (aka inline code).  https://github.com/aws/aws-cdk/blob/a1cd7432eb817a0a9361c907445c01eea4cb1321/packages/%40aws-cdk/aws-lambda/lib/runtime.ts#L50

However, when deploying a function like this

```typescript
new lambda.Function(stack, 'foobar', {
  code: new lambda.InlineCode('def handler(event:, context:) ; "success" ; end'),
  handler: 'index.handler',
  timeout: cdk.Duration.seconds(15),
  runtime: lambda.Runtime.RUBY_2_5
});
```

I get the following error from CloudFormation 

```
 19/52 | 9:14:58 PM | CREATE_FAILED        | AWS::Lambda::Function            | foobar (foobarF27D68A9) ZipFile can only be used when Runtime is set to either of nodejs8.10, nodejs10.x, nodejs12.x, python2.7, python3.6, python3.7.
```

The [docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-function-code.html) are also mentioning just nodejs and python 

### Environment

  - **CLI Version 1.22.0 (build 309ac1b)**

This is :bug: Bug Report

**Comment by nija-at** [comment]
Ack, supports `inlineCode` needs to be unset for Ruby.
