### ISSUE TITLE
Ability to specify "runOrder" for codebuild.PipelineProject construct

### ISSUE THREAD

**Issue by Dzhuneyt** [aws/aws-cdk#6303]
I use CDK to deploy a `new codepipeline.Pipeline()` that has multiple stages. One of these stages consists of multiple CodeBuild jobs that I'd like to orchestrate in a fan-out/fan-in pattern.

However, currently, I see no possibility to define the `runOrder` property of the CodeBuild actions that represent the CodePipeline stage.

### Proposed Solution

        new codepipeline.Pipeline(this, 'pipeline', {
            restartExecutionOnUpdate: true,
            stages: [
                {
                    stageName: 'Source',
                    actions: [
                        sourceAction.build(),
                    ],
                },
                {
                    stageName: 'Tests',
                    actions: [
                        new codebuild.PipelineProject(this, 'step-1-a', {....}),
                        new codebuild.PipelineProject(this, 'step-1-b', {....}),
                        new codebuild.PipelineProject(this, 'step-2', {....}),
                    ],
                },
        // .... truncated

In the above example, all 3 steps will be ran with runOrder=1 (parallel). A prop that allows to define it would be nice.
* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by skinny85** [comment]
Hey @Dzhuneyt ,

I think the types got away from you there a little bit :). The code you posted will not compile.

The property `actions` has type `IAction[]`, and there is a [`CodeBuildAction` in the `@aws-cdk/aws-codepipeline` package](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-codepipeline-actions.CodeBuildAction.html). In the `CodeBuildAction`, you have the [`runOrder` property](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-codepipeline-actions.CodeBuildActionProps.html#runorder).

For more information on Actions, check out the [ReadMe of the `@aws-cdk/aws-codepipeline-actions` package](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-codepipeline-actions-readme.html).

Thanks,
Adam

**Comment by Dzhuneyt** [comment]
You are right. While extracting relevant pieces of code to illustrate the example, it seems I missed a piece of code we had in the parent class (the one that creates the codepipeline.CodeBuildAction instance).

Sorry about the confusion. This can be closed.
