### ISSUE TITLE
Guidance on how to stop rollback a nested  stack

### ISSUE THREAD

**Issue by nikhilbhoj** [aws/aws-cdk#6305]
## :question: General Issue
I have a EKS stack that is creating a nested stack. I have some company wide boundary policy that are to be added in the role. My nested stack is failed to be created and it by default getting rolled back, the information are not sufficient to be debugged for error. I searched the cdk documentation on how to  stop rollback but unable to find out.

Please share the information or code snippet that would help.

### Environment

  - **CDK CLI Version:** 
  - **Module Version:** 
  - **OS:** 
  - **Language:**

**Comment by eladb** [comment]
You should be able to view old events in the CloudFormation console and use this information to debug your issue.
