### ISSUE TITLE
Invalid bucket name CloudFrontWebDistribution

### ISSUE THREAD

**Issue by davidsteed** [aws/aws-cdk#6313]
Using a bucket to host a website using CloudFrontWebDistribution works, but when the bucket is set up to redirect to another URL, it does not.  The issue is if you use s3OriginSource:bucket in cdk, the bucket name generated is bucketname.s3.us-east-1.amazonaws.com.  This works for website hosting, but for some bizarre reason for a redirect bucket it must be bucketname.s3-website.us-east-1.amazonaws.com.  This is such bizarre behaviour that it has taken me ages to work out what was going on   

### Reproduction Steps
 if you create a bucket like this 
```
 const redirectBucket = new s3.Bucket(this, 'ReDirect', {
            bucketName: props.domainName,
            publicReadAccess: true,
            websiteRedirect: {
                hostName: siteDomain
            },
            removalPolicy: cdk.RemovalPolicy.RETAIN,
        });

and use

this.distribution = new cloudfront.CloudFrontWebDistribution(this, 'SiteDistribution', {
            aliasConfiguration: {
                acmCertRef: certificateArn,
                names: [props.siteName],
                sslMethod: cloudfront.SSLMethod.SNI,
                securityPolicy: cloudfront.SecurityPolicyProtocol.TLS_V1_1_2016,
            },
           
            originConfigs: [
                {
                    s3OriginSource: {
                        s3BucketSource:redirectBucket
                    },
                    behaviors: [{
                        isDefaultBehavior: true

                       
                    }],
                }
            ]
        });
```
### Error Log
Cloudfront displays 
```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>XXXX</RequestId>
<HostId>
XXXX
</HostId>
</Error>
```
cdk populates bucketname.s3.us-east-1.amazonaws.com in  the cloudfront distribution Origin Domain name and path.  I you use the console to edit this to bucketname.s3-website.us-east-1.amazonaws.com.

Everything works

### Environment

  - **CLI Version      :1.22.0
 
  - **Language         :typescript

--- 

This is :bug: Bug Report

**Comment by hoegertn** [comment]
The way you are initializing the CFDistribution it uses the bucket as an S3 Origin. For redirects to work you hat to use it as a custom origin using the website endpoint.

You can look at https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-route53-patterns/lib/website-redirect.ts for advice or just use this construct.

This is not a bug given the provided properties.

**Comment by davidsteed** [comment]
Thanks
