### ISSUE TITLE
Give feedback when parcel is building Lambda functions

### ISSUE THREAD

**Issue by jogold** [aws/aws-cdk#6319]
For stacks with a few `NodejsFunction`s the build time can be important and there's currently no feedback given to the user.

### Use Case

Giving feedback would improve the CLI experience.

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by eladb** [comment]
See https://github.com/aws/aws-cdk-rfcs/issues/7#issuecomment-590060873

@jogold I wonder what you think. Maybe that is our way out?

**Comment by jogold** [comment]
Closing in favor of #8956
